### ISSUE TITLE
[WebView] injectedJS variable injected not accesible from the webview scripts

### ISSUE THREAD

**Issue by jawadrehman** [facebook/react-native#2629]
I have injected the following 

var script = 'window.mobile_cookie = "'+Actions.cookie+'"; alert(window.mobile_cookie)';

and the alert shows up fine with the correct response, but in my webview , the following
<div id ="mobile_test">

</div>

<script>
document.getElementById("mobile_test").innerHTML=window.mobile_cookie;
</script>

doesnt work. is the injectedJS passed to the webview ?

**Comment by browniefed** [comment]
I vaguely remember someone mentioning that iOS now doesn't allow you to access cookies in webview but I could be mistaken

**Comment by brentvatne** [comment]
@jawadrehman - could you try posting this (along with a more complete code example) to StackOverflow ([as per our 'Getting Help' section of the README](https://github.com/facebook/react-native#getting-help))? If you still can't find an answer after a few days on there or in Slack, feel free to ping me here and we can reopen.
