### ISSUE TITLE
I am unable to programmatically move children using ScrollView

### ISSUE THREAD

**Issue by Louis345** [facebook/react-native#26291]
Hello, I was previously able to programmatically moving ScrollView's children and now I am unable to do so. I think this might be a bug.  I have created a StackOverflow post requesting help to no avail. (https://stackoverflow.com/questions/57385037/react-natives-animated-scrollview-is-not-allowing-me-to-programmatically-scroll)

I have created a snack to demonstrate my problem. 

This problem is driving me nuts because I cannot upgrade and this keeps me from using hooks. 

React Native version:

  React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
      Memory: 72.58 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.1 - /usr/local/bin/node
      Yarn: 1.2.0 - /usr/local/bin/yarn
      npm: 5.6.0 - /usr/local/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    IDEs:
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
      react-native-scripts: 1.5.0

Describe what you expected to happen:
I expect to be able to programmatically move ScrollView's children like I was able to do previously.

https://snack.expo.io/@louis345/scrollto-not-working

https://stackoverflow.com/questions/57385037/react-natives-animated-scrollview-is-not-allowing-me-to-programmatically-scroll

And here is a link to my repo where the code actually works 
https://github.com/Louis345/mobileLanguageApp/blob/Dev/screens/CreateCard.js

**Comment by fellmann** [comment]
Same problem for me on Android.

**Comment by carmenchapa** [comment]
I have the same problem

**Comment by fellmann** [comment]
Still open
