### ISSUE TITLE
Init project with template typescript get error

### ISSUE THREAD

**Issue by GreatAuk** [facebook/react-native#26303]
React Native version: 0.61.0-rc.0

## Steps To Reproduce

excute ```npx react-native@0.61.0-rc.0 init RNTest --template typescript```

but ```npx react-native init RNTest --template typescript``` is ok.

Snack, code example, screenshot, or link to a repository:
![image](https://user-images.githubusercontent.com/20253809/64147559-3f3bc580-ce53-11e9-965f-f271ea876fcb.png)

**Comment by bartolkaruza** [comment]
Hi there, this will get resolved (if possible) faster at the react-native-cli repo, so I moved the issue there. Closing here. :)
