### ISSUE TITLE
Text when there is only one line on Android

### ISSUE THREAD

**Issue by bashen1** [facebook/react-native#26302]
React Native version:
```
React Native Environment Info:
    System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 123.38 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.5.0 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.10.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 22, 23, 24, 25, 26, 27, 28
      Build Tools: 24.0.1, 25.0.2, 27.0.3, 28.0.2, 28.0.3, 29.0.0
  IDEs:
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-create-library: 3.1.2
    react-native-git-upgrade: 0.2.7

```

## Steps To Reproduce

Just add punctuation or change the color of the font. Under Android, there will be a BUG in the current situation.

Describe what you expected to happen:

Snack, code example, screenshot, or link to a repository:
![IMG_4133](https://user-images.githubusercontent.com/4652791/64139107-58804a00-ce32-11e9-8487-330a08946a8c.PNG)
![Screenshot_2019-09-03-09-57-33-319_com manmanbuy bijia](https://user-images.githubusercontent.com/4652791/64139159-7f3e8080-ce32-11e9-93ed-4e6a505e14e6.png)

```react
<View style={{borderWidth: 1, borderColor: '#FF6600', marginVertical: 5}}>
    <Text style={{fontSize: 14, lineHeight: 20}}>
        <Text style={{color: '#617095'}}>我</Text>
        <Text style={{color: '#353535'}}>:&nbsp;的</Text>
    </Text>
</View>
<View style={{borderWidth: 1, borderColor: '#FF6600', marginVertical: 5}}>
    <Text style={{fontSize: 14, lineHeight: 20}}>
        <Text style={{color: '#617095'}}>我</Text>
        <Text style={{color: '#353535'}}>：&nbsp;的</Text>
    </Text>
</View>
<View style={{borderWidth: 1, borderColor: '#FF6600', marginVertical: 5}}>
    <Text style={{fontSize: 14, lineHeight: 20}}>
        <Text style={{color: '#617095'}}>我</Text>
        <Text style={{color: '#ED0000'}}>:&nbsp;的</Text>
    </Text>
</View>
<View style={{borderWidth: 1, borderColor: '#FF6600', marginVertical: 5}}>
    <Text style={{fontSize: 14, lineHeight: 20}}>
        <Text style={{color: '#617095'}}>我</Text>
        <Text style={{color: '#617095'}}>:&nbsp;的</Text>
    </Text>
</View>
```

**Comment by RobinCsl** [comment]
Hello @bashen1  👋 

I could reproduce your issue on Android in this Expo Snack: https://snack.expo.io/@robincsl/e378d4 and using the emulator provided by Appetize.io through Expo Snack.

On a fresh `npx react-native init MyAwesomeApp` or `npx expo init MyAwesomeApp` (with "blank" template), I could not reproduce it with my Android emulator under API version 28 (Android 9). This is what it looks like:
<div align="center">
<img width="300" src="https://user-images.githubusercontent.com/22741774/64472800-2f2e2980-d164-11e9-87b0-c4eb6f8f15d8.png" />
</div>

But, on my emulator under API version 27 (Android 8.1), I can observe the same issue you're reporting. This is what it looks like:
<div align="center">
<img width="300" src="https://user-images.githubusercontent.com/22741774/64473127-baf48580-d165-11e9-99e7-a8b7bbb23e3d.png" />
</div>


I'm not much of an Android expert, so someone else would have to jump in, but it looks related to the Android API version. Maybe @ferrannp would know something about that?
