### ISSUE TITLE
Cookies and authorization headers dropped when making HTTP requests that redirect [iOS] - AGAIN

### ISSUE THREAD

**Issue by kyhnlbyrk** [facebook/react-native#26311]
### Environment
react-native -v: react-native-cli: 2.0.1; react-native: 0.59.8
node -v: v8.10.0
npm -v: 3.5.2
### 
Steps to Reproduce
Make an HTTP fetch request to an endpoint that performs redirects.
Inspect the traffic.
Note that cookies from responses are not included in subsequent HTTP redirected requests.
Also note that authorization headers (if any) in the original request are not included in subsequent HTTP redirected requests.
### Expected Behavior
Expect fetch request to carry cookie and authorization headers over to subsequent HTTP requests when being redirected.

### Actual Behavior
Cookies and authorization headers from responses are not carried over into subsequent HTTP requests when being redirected.

**Comment by retyui** [comment]
I have the same problem!

**Comment by Return-1** [comment]
i can confirm this is an issue

**Comment by Return-1** [comment]
This is still an issue

**Comment by hussainahmad** [comment]
with ny post service  my Server responds with Set-Cookie header, containing standard JSESSIONID cookie. which I am not receiving in header. In header only receiving map object and URL.

**Comment by thijs-qv** [comment]
Can this be reopened?
