### ISSUE TITLE
-[RCTRedBox showError:] called from background

### ISSUE THREAD

**Issue by jwyld** [facebook/react-native#2631]
-[RCTBatchedBridge _actuallyInvokeAndProcessModule:method:arguments:] asserts it is on the JS thread.  It creates processResponse which calls -[RCTRedBox showError:] and passes this along as the callback to -[NSObject<RCTJavaScriptExecutor> executeJSCall:method:arguments:callback:].  Both RCTContextExecutor and RCTWebViewExecutor, effectively, dispatch this to their respective -executeBlockOnJavaScriptQueue: method.  Both will re-dispatch to its respective JS thread.  In the case of RCTWebViewExecutor, this is the main thread.  For RCTContextExecutor, this is a background thread.

-[RCTBatchedBridge _actuallyInvokeAndProcessModule:method:arguments:] should probably dispatch_async the call to -[RCTRedBox showError:] inside processResponse.

**Comment by tadeuzagallo** [comment]
Fixed it internally, should out soon. Thanks

**Comment by tadeuzagallo** [comment]
I had a diff for that but just double checked and `showError:` dispatches everything to the main thread, so it should be safe.
