### ISSUE TITLE
Unable to find a specification for `React-fishhook (= 0.60.4)` depended upon by `React-RCTWebSocket`

### ISSUE THREAD

**Issue by ahmad6242** [facebook/react-native#26310]
React Native version:

Describe what you expected to happen:
it should run this process and create xcode project workspace. but i am always stuck around this error. 

i have attached screen shot for all the dependencies i am running. 

"dependencies": {
    "@react-native-community/async-storage": "^1.3.3",
    "@react-native-community/netinfo": "^4.1.5",
    "axios": "^0.18.0",
    "moment": "^2.24.0",
    "native-base": "^2.12.1",
    "react": "16.8.6",
    "react-native": "0.60.4",
    "react-native-animatable": "^1.3.2",
    "react-native-calendars": "^1.110.0",
    "react-native-ci-tools": "^1.1.0",
    "react-native-device-info": "^2.1.2",
    "react-native-firebase": "^5.3.1",
    "react-native-flash-message": "^0.1.13",
    "react-native-fs": "^2.14.1",
    "react-native-gesture-handler": "^1.1.0",
    "react-native-google-drive-api-wrapper": "^1.2.0",
    "react-native-google-signin": "^2.0.0",
    "react-native-image-crop-picker": "^0.25.0",
    "react-native-image-grid": "^1.0.0",
    "react-native-image-marker": "^0.5.1",
    "react-native-image-rotate": "^2.1.0",
    "react-native-loading-spinner-overlay": "^1.0.1",
    "react-native-modal-datetime-picker": "^7.5.0",
    "react-native-push-notification": "^3.1.9",
    "react-native-popup-menu": "^0.15.6",
    "react-native-share": "^1.1.3",
    "react-native-splash-screen": "^3.2.0",
    "react-native-swiper": "^1.5.14",
    "react-native-vector-icons": "^6.4.2",
    "react-native-version-check": "^3.3.0",
    "react-navigation": "^3.9.0",
    "react-redux": "^7.0.2",
    "redux": "^4.0.1",
    "redux-axios-middleware": "^4.0.0",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.3.0",
    "rn-fetch-blob": "^0.10.16"
  },
  "devDependencies": {
    "@babel/core": "^7.5.5",
    "@babel/runtime": "^7.5.5",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.8.0",
    "eslint": "^6.1.0",
    "jest": "^24.8.0",
    "metro-react-native-babel-preset": "^0.55.0",
    "react-test-renderer": "16.8.6"
  },

![image](https://user-images.githubusercontent.com/12858657/64177142-f0505900-ce6f-11e9-9f71-7771203135a9.png)

**Comment by blaisethom** [comment]
I had the same error message just now and upgrading react-native to 0.60.5 fixed it for me.

**Comment by ahmad6242** [comment]
Okey i will try. 
Actually i am using other libraries, which are working fine with this react native version. Like the React native firebase. I have tried once to update before, application start having some other issues with the react native firebase. so i downgraded to this version. 
Is there any other workaround for this. 
Anyway I will try and see if it works now !
@blaisethom Thanks

**Comment by tststs** [comment]
same issue with 0.60.5

**Comment by haoniukun** [comment]
> same issue with 0.60.5

Same here.

**Comment by tststs** [comment]
```rm -fr ~/.cocoapods/repos/master && pod install --repo-update``` solved the issue for me.

**Comment by VictorAugustoDn** [comment]
I'm using 0.60.4 too, for me solved by add the following line below "React-DevSupport" in PodFile:
pod 'React-fishhook', :path => '../node_modules/react-native/Libraries/fishhook'

Example:
target 'ExampleApp' do
    pod 'React', :path => '../node_modules/react-native/'
    pod 'React-Core', :path => '../node_modules/react-native/React'
    pod 'React-DevSupport', :path => '../node_modules/react-native/React'
    **pod 'React-fishhook', :path => '../node_modules/react-native/Libraries/fishhook'**
    pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
    pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
    pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
    pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
    pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
    pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
    pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
    pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
    pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
    pod 'React-RCTWebSocket', :path => '../node_modules/react-native/Libraries/WebSocket'

    pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
    pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
    pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
    pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
    pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  
    # React Native third party dependencies podspecs
    pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
    pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
    pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

    use_native_modules!

  end
