### ISSUE TITLE
[Modal] Switching Between Modals Fails

### ISSUE THREAD

**Issue by ender672** [facebook/react-native#2632]
Run the following app.

In the Main Window, press "Open 2".
This opens the second Modal.

In the second Modal, press "Open 1".
This closes the second Modal, logs an error to the console, and fails to open the first Modal.

In the Main Window, press "Open 1".
This does nothing.

```javascript
'use strict';

var React = require('react-native');
var {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  Modal,
  TouchableHighlight
} = React;

var rnex = React.createClass({
  getInitialState: function() {
    return {
      mod1: false,
      mod2: false,
    };
  },

  open1: function() {
    this.setState({
      mod1: true,
      mod2: false,
    });
  },

  open2: function() {
    this.setState({
      mod1: false,
      mod2: true,
    });
  },

  openAll: function() {
    this.setState({
      mod1: true,
      mod2: true,
    });
  },

  closeAll: function() {
    this.setState({
      mod1: false,
      mod2: false,
    });
  },

  modalButtons: function() {
    return (
      <View>
        <TouchableHighlight onPress={this.open1}>
          <Text>Open 1</Text>
        </TouchableHighlight>
        <TouchableHighlight onPress={this.open2}>
          <Text>Open 2</Text>
        </TouchableHighlight>
        <TouchableHighlight onPress={this.openAll}>
          <Text>Open All</Text>
        </TouchableHighlight>
        <TouchableHighlight onPress={this.closeAll}>
          <Text>Close All</Text>
        </TouchableHighlight>
      </View>
    );
  },

  render: function() {
    return (
      <View style={styles.container}>
        <Text>This is the Main Window</Text>
        {this.modalButtons()}
        <Modal visible={this.state.mod1} animated={true}>
          <View style={styles.container}>
            <Text>This is Modal 1</Text>
            {this.modalButtons()}
          </View>
        </Modal>
        <Modal visible={this.state.mod2} animated={true}>
          <View style={styles.container}>
            <Text>This is Modal 2</Text>
            {this.modalButtons()}
          </View>
        </Modal>
      </View>
    );
  }
});

var styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
});

AppRegistry.registerComponent('rnex', () => rnex);
```

**Comment by ender672** [comment]
It's clear that Modal components were not designed to be siblings.

I am trying to integrate React Native into an existing iOS application. I ran into a scenario where I want to invoke a view from the existing application (through a Native Module call) within a React Native Modal component. I was unable to juggle the state of my React application alongside the iOS view hierarchy.

When the Modal component is presented, the Native Module call cannot present a view of its own.

There is no way to invoke the Native Module call after the Modal component has been dismissed.

This made me wonder how React handles this kind of scenario internally, and hence the example above.

**Comment by dsibiski** [comment]
@ender672 I don't think I fully understand what your original problem is, but it **could** perhaps have to do with multiple instances of bridge modules depending on how you are calling your RN code from your existing app.

Check out this example repo for some concepts for working with existing applications and how you can communicate with RN (specifically the discussion and example for "Native Modal With RN Navigation": https://github.com/dsibiski/react-native-embedded-app-example

There is a chance that nothing there will help you at all! But it may also give you some insight that could help you figure out another way to do what you are trying to accomplish. I'm also looking for other interesting problems to solve, so more info (open and issue on that example repo) on specific use-cases is welcome.

Of course, there may be a legitimate bug here in RN, but in the meantime you might find a different solution.

**Comment by ide** [comment]
I strongly discourage using Modal unless you need to present a view on top of a native UIViewController that is not controlled by React Native. In a pure React Native app you should instead use a top-level Navigator component and push a new scene when presenting a modal view.

cc @sahrens, does my understanding of Modal match its intended use case? If so, I'll write some documentation clarifying that Modal is intended for hybrid apps.

**Comment by sahrens** [comment]
Yeah, <Modal> should only be necessary for hybrid apps where you need your
react view to cover up other native views outside your react stuff.

**Comment by ender672** [comment]
Thanks for clarifying on the intent of the Modal component.

@dsibiski - thanks for pointing out alternative approaches!

**Comment by ide** [comment]
Docs PR here: https://github.com/facebook/react-native/pull/2663

**Comment by mkonicek** [comment]
@facebook-github-bot answered
