### ISSUE TITLE
Creating a dynamic gallery in React Native, but images will not appear

### ISSUE THREAD

**Issue by Tacoholic** [facebook/react-native#26328]
React Native version:
RN-Cli: 2.0.1
React-Native: 0.60.3
## Steps To Reproduce
1. I created a JSON folder with all my images for each character, which is a total of 3. 
2. I then created a folder for the gallery, where I would pull in all the images dynamically. 

Describe what you expected to happen:
Inside a character's profile page, when I click on the gallery button, which is in the header, it should take me to that character's gallery of pictures.

**Comment by fonov** [comment]
can you provide some demo?
