### ISSUE TITLE
main.jsbundle does not exist. This must be a bug with

### ISSUE THREAD

**Issue by appa3151** [facebook/react-native#26324]
when i create release  build time

**Comment by fonov** [comment]
Please provide some demo for reproduce this bug

**Comment by zhllucky** [comment]
@appa3151  did you solve it

**Comment by darran-kelinske-fivestars** [comment]
Getting this too

**Comment by excitedcat** [comment]
Getting this too

**Comment by excitedcat** [comment]
Node memory out of range caused this problem, bundle file generate failure. 

# The way to fix this:

![image](https://user-images.githubusercontent.com/8253512/67755914-034c6780-fa74-11e9-9ddf-39e46f2b7bc0.png)

# Bundle React Native code and images
Add this line `export NODE_OPTIONS=--max_old_space_size=4096` 

@appa3151 @fonov @zhllucky

**Comment by Warmachine13** [comment]
> Node memory out of range caused this problem, bundle file generate failure.
> 
> # The way to fix this:
> ![image](https://user-images.githubusercontent.com/8253512/67755914-034c6780-fa74-11e9-9ddf-39e46f2b7bc0.png)
> 
> # Bundle React Native code and images
> Add this line `export NODE_OPTIONS=--max_old_space_size=4096`
> 
> @appa3151 @fonov @zhllucky

this make run but still gets the same error after open app
