### ISSUE TITLE
Can't open the app in CHPlay when enableHermes and build bundle app after update to 0.60.5

### ISSUE THREAD

**Issue by ThoMiDev** [facebook/react-native#26335]
React Native version: 0.60.5

## Steps To Reproduce

1. Init new project with version 0.60.5
2. Set enableHermes: true
3. Update enableSeparateBuildPerCPUArchitecture = true
4. def enableProguardInReleaseBuilds = true
5. Everything is OK, I make sure that the app debug and release can be install and open.
6. Build bundle .aab and upload to CHPlay, their tester can open and the app was test (They register new account in my app) then the app available on CHPlay.
7. Now, I download the app, but the app can't open. The app doesn't log anything.

**Comment by ethanneff** [comment]
Same problem here. I can run the .apk and .aab locally. However, as soon as I upload the .aab to the  Google Play Console, my app instant white screens and crashes on Google Play Store download.
