### ISSUE TITLE
Unable to build the tvOS App on 0.60.5

### ISSUE THREAD

**Issue by SenthilKumar-J** [facebook/react-native#26341]
React native version 0.60.5
Created a fresh project using the steps mentioned in https://facebook.github.io/react-native/docs/getting-started with react-native init AwesomeProject command.
iOS code is working and tvOS is not building.
Screenshots attached below.

This issue didn't occur in 0.59.9 version.

## React Native version:
  System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 354.59 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.9.1 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.10.3 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
  IDEs:
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1

## Steps To Reproduce

1. react-native init AwesomeProject
2. Open project workspace
3. Change target to tvOS 
4. Build the app.

## Describe what you expected to happen:
tvOS target should build and be able to run on Simulator or device.

## Snack, code example, screenshot, or link to a repository:

<img width="1401" alt="Screenshot 2019-09-05 at 3 11 03 PM" src="https://user-images.githubusercontent.com/54936444/64330915-7e068280-cfef-11e9-8a6a-b2bc5e71a9d4.png">
<img width="1398" alt="Screenshot 2019-09-05 at 3 11 20 PM" src="https://user-images.githubusercontent.com/54936444/64330916-7e9f1900-cfef-11e9-99c2-24cd388f58bb.png">

**Comment by aparedes** [comment]
You should use this if you want to use react-native on tvOS https://github.com/react-native-community/react-native-tvos

**Comment by SenthilKumar-J** [comment]
As per this link https://facebook.github.io/react-native/docs/building-for-apple-tv, it is considered part of the Core repo. Why this is separated now? 
Is this publicly announced that will be separated or support in the native is discontinued from the RN?

**Comment by aparedes** [comment]
Yeah I only found out about it when i saw your issue. The docs are not updated or has been announced. 
I think it got separated as it uses different pods but I have no more info

**Comment by TheoGit** [comment]
@aparedes I'm maintaining an App built on RN 0.59 - runs good for the most part, a few really odd bugs - I just found RN Tester, great idea!  In the new RN TV repository it states:

**TVFocusGuideView**: This component provides support for Apple's UIFocusGuide API, to help ensure that focusable controls can be navigated to, even if they are not directly in line with other controls. A new example is provided in **RNTester.**
