### ISSUE TITLE
ld: library not found for -lDoubleConversion for React Native 0.60.4

### ISSUE THREAD

**Issue by ldco2016** [facebook/react-native#26348]
I continue to get a library not found for -lDoubleConversion.

This is my podfile:

```
platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

abstract_target 'defaults' do
  # Pods for NFIBEngage
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/React'
  pod 'React-DevSupport', :path => '../node_modules/react-native/React'
  pod 'React-fishhook', :path => '../node_modules/react-native/Libraries/fishhook'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-RCTWebSocket', :path => '../node_modules/react-native/Libraries/WebSocket'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  target 'PROD'
  target 'DEV'
  target 'QA'
  target 'UA'
  target 'IN'
  target 'NFIBEngageTests'
  target 'NFIBEngage-tvOS'
  target 'NFIBEngage-tvOSTests'

  use_native_modules!

end
```

I have run out of ideas of why Xcode does not see DoubleConversion. It is there. Its in my Linked Frameworks and Libraries in the General tab and its in Link Binary With Libraries inside of Build Phases tab.

I believe the DoubleConversion library is set up correctly in Podfile, but Xcode is looking for DoubleConversion instead of double-conversion.

React Native version:

  ```
SDKs:
    iOS SDK:
      Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 23.0.1, 26.0.2, 27.0.3, 28.0.3
      System Images: android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 10.1/10B61 - /usr/bin/xcodebuild
  npmPackages:
    @react-native-community/cli: 2.9.0 => 2.9.0
    react: 16.8.6 => 16.8.6
    react-native: 0.60.4 => 0.60.4
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
```

## Steps To Reproduce

1. `open NFIBEngage.xcodeproj`
2. Run **Clean**
3. Run **Build**

You can use this repo to reproduce:
https://github.com/ldco2016/NFIBEngage

**Comment by raghavyadavm** [comment]
#25804

**Comment by psrrao** [comment]
I manage to solve this issue.

Make sure you make the build after opening workspace in XCode.

e.g. open .xcworkspace not the .xcodeproj

**Comment by Billmike** [comment]
I spent the last five days stuck on this, trying out everything suggested on the internet. This is what finally worked for me. (Before proceeding, make sure 
```pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'``` is included in your podfiles
```
1. Delete Podfile.lock
2. cd ios
3. pod deintegrate
4. pod install
5. cd ..
6. rm -rf node_modules && yarn
7. Add use_frameworks! to your Podfile
```
Run react-native-run-ios or Build with Xcode by opening the xcworkspace file in your ios directory. Hope this helps someone!

**Comment by outluch** [comment]
Had the same problem, but build succeeded after this:
https://github.com/react-native-community/react-native-maps/issues/2829#issuecomment-488816768

**Comment by Maxoos** [comment]
If you're here from google (and a note to myself as I might forget), make sure the IOS version in podsfile AND project AND any test targets that you may have are the same. Otherwise it simply will not complete the release/archive.

**Comment by alexisbronchart** [comment]
I now have this issue after updating to 0.62.0 (it was fine before).
It doesn't seem to happen if I remove `use_frameworks!` from my `Podfile`, however I absolutely need it for some dependencies. Any ideas?

**Comment by Lekhrajk** [comment]
I am getting same error tried everything but nothing works 
I am using RN 0.64

**Comment by hugoh59** [comment]
Me too but with AppAuth.

**Comment by yongpengW** [comment]
> I am getting same error tried everything but nothing works
> I am using RN 0.64

I am also RN 64, did you solve the problem? I have tried everything above

**Comment by chenweigh** [comment]
the same problem for 0.65
