### ISSUE TITLE
Issue with viewManage is returning nil for it's methodQueue, which is not permitted(...)

### ISSUE THREAD

**Issue by Lohit9** [facebook/react-native#2635]
ViewManagerName is returning nil for it's methodQueue, which is not permitted. You must either return a pre-initialized queue, or @synthesize the methodQueue to let the bridge create a queue for you.

I think this is a packaging issue, can anyone please tell me how to solve it ?

I had this issue earlier but a later version fixed it,  dunno what to do in this case. Similar issue here: https://github.com/brentvatne/react-native-overlay/issues/10

**Comment by Lohit9** [comment]
i tried adding this:  

    @synthesize methodQueue = _methodQueue;
in between @synthesize bridge = _bridge; and RCT_EXPORT_MODULE() lines. 

But it's still giving me this error: 'unknown' has no propTypes defined

**Comment by brentvatne** [comment]
hey @Lohit9 - if you post the JS code for this component on StackOverflow I think someone will be able to spot the issue for you :)
