### ISSUE TITLE
iOS refresh control doesn't show up after initial pull to refresh

### ISSUE THREAD

**Issue by kingdaro** [facebook/react-native#26350]
On iOS, the refresh control won't show if the `refresh` prop changes outside of a manual pull to refresh.

```
React Native version: 0.60.3
System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Memory: 50.39 MB / 8.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.6.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28
      Build Tools: 23.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.1, 28.0.2, 28.0.3
      System Images: android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64
, android-28 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.1 AI-173.4907809
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.3 => 0.60.3 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
```

## Steps To Reproduce

1. Open this snack https://snack.expo.io/@kingdaro/scrollview-refresh-control-bug 
1. Tap "trigger refresh", the control will show up as expected
1. Pull to refresh, the control shows up as expected
1. Tap "trigger refresh" again, the control does _not_ show up

Describe what you expected to happen:

The refresh control should always show if `refreshing` is true.

Snack, code example, screenshot, or link to a repository: https://snack.expo.io/@kingdaro/scrollview-refresh-control-bug

**Comment by plimerence** [comment]
same issue

**Comment by kingdaro** [comment]
This still occurs

**Comment by ca057** [comment]
The same issue occurs on my side. As far as I can see, this PR describes the same behavior and should fix it: https://github.com/facebook/react-native/pull/27397, so hopefully this will be fixed with the next release.

**Comment by kingdaro** [comment]
I ran the snack with expo 37, ran through the same steps, bug still happens. Unless 37 isn't on the latest RN version, this still happens

**Comment by kingdaro** [comment]
This appears to be fixed on expo v38! 🎉
