### ISSUE TITLE
Unable to create an app with React native latest version 0.60.5, welcome screen is not coming.

### ISSUE THREAD

**Issue by akhter004** [facebook/react-native#26353]
I am creating an app using react native CLI using USB mode (android device) but welcome screen is not coming white screen is appearing in my device screen.

React Native version:
 OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
    Memory: 7.69 GB / 15.56 GB
    Shell: 5.4.2 - /usr/bin/zsh
  Binaries:
    Node: 8.10.0 - /usr/bin/node
    npm: 6.9.0 - /usr/local/bin/npm
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5 
  npmGlobalPackages:
    create-react-native-app: 2.0.2
    react-native-cli: 2.0.1
    node - v8.10.0
## Steps To Reproduce

1. I have installed Sdk as per the steps mention the fb doc
2. Install Android Debug Bridge (adb)-
   sudo apt-get install android-tools-adb android-tools-fastboot
3.Start Android Debug Bridge (adb)-
    sudo adb start-server
    sudo adb kill-server
4.Install react native cli-
    sudo npm install -g react-native-cli
5.Create project directory- 
    sudo react-native init <ProjectName>
6. Set “SDK location" inside  /home/<username>/<ProjectName>/android/local.properties
7.Run React Native application
    cd <ProjectName>
    run -- sudo react-native run-android
	      sudo react-native start
8.Using remote javascript debugging console log -
	 1 - enable debug JS remotely from developer tools
	 http://localhost:8081/debugger-ui/

**When i reload the app screen then the white screen is appearing. even Loading dependency graph, done.
 BUNDLE  [android, dev] ./index.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100.0% (563/563), done.
**

Describe what you expected to happen:

**The welcome screen is not coming.**

![Screenshot from 2019-09-06 08-22-18](https://user-images.githubusercontent.com/28755729/64398246-b48cdd80-d081-11e9-8267-b6abc5bfe2d4.png)
![Screenshot from 2019-09-06 08-22-39](https://user-images.githubusercontent.com/28755729/64398254-bbb3eb80-d081-11e9-96d7-acbce29564ef.png)

Please help me. what i am doing in wrong way the big prob is with only latest version same above steps work for 0.59 version. 

![Screenshot from 2019-09-06 08-47-25](https://user-images.githubusercontent.com/28755729/64398624-2580c500-d083-11e9-8891-34b660117946.png)

After this screen i run sudo react-native start

![Screenshot from 2019-09-06 08-48-07](https://user-images.githubusercontent.com/28755729/64398662-3fbaa300-d083-11e9-8b0d-d63fb7e65e5d.png)

**Comment by mukeshmandiwal** [comment]
It working on both emulator and physical device 
I'm using 
Ubuntu 18.04.2 LTS 
React native  0.60.5

**Comment by anderssonq** [comment]
I have the same problem, please help us!

**Comment by AustP** [comment]
I just had this issue as well. I closed everything down and ran everything in this order:

1. Start React Native
2. Start Emulator
3. `react-native run-android`

Then it worked as expected. Your mileage may vary.

**Comment by syamjayaraj** [comment]
I am using Windows 10 OS and I also have the same issue.

 BUNDLE  [android, dev] ./index.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100.0% (1/1), done.
 BUNDLE  [android, dev] ./index.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100.0% (1/1), done.
 BUNDLE  [android, dev] ./index.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100.0% (1/1), done.
