### ISSUE TITLE
How to fix extra spacing when set minHeight?

### ISSUE THREAD

**Issue by pavm035** [facebook/react-native#26368]
When i set container view with minHeight value when children grows it adds extra padding at bottom when container height is greater minHeight if i understood properly it should set minHeight when container size is less than minHeight but not when it's greater than minHeight and here is my code

React Native version:
info Fetching system and libraries information...
System:
    OS: macOS 10.14.4
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 162.77 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.16.2 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
  IDEs:
    Android Studio: 3.2 AI-181.5540.7.32.5056338
    Xcode: 10.1/10B61 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.5 => 0.60.5
  npmGlobalPackages:
    react-native-cli: 2.0.1

## Steps To Reproduce

1. Run sample code below and observe extra spacing
2.

Describe what you expected to happen:
It should not add extra spacing

Snack, code example, screenshot, or link to a repository:

```
import React, { Component } from 'react';
import { Text, View } from 'react-native';

export default class HelloWorldApp extends Component {
render() {
return (
<View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
<View
style={{
width: '100%',
flexDirection: 'row',
flexWrap: 'wrap',
justifyContent: 'space-between',
borderWidth: 1.5,
borderRadius: 8,
minHeight: 70,
}}>
<View
style={{ width: 100, height: 50, backgroundColor: 'powderblue' }}
/>
<View
style={{ width: 100, height: 50, backgroundColor: 'skyblue' }}
/>
<View
style={{ width: 100, height: 50, backgroundColor: 'steelblue' }}
/>
<View style={{ width: 100, height: 50, backgroundColor: 'red' }} />
<View style={{ width: 100, height: 50, backgroundColor: 'blue' }} />
<View style={{ width: 100, height: 50, backgroundColor: 'green' }} />
);
}
}
```

<img width="320" alt="Screen Shot 2019-09-07 at 20 11 46" src="https://user-images.githubusercontent.com/6092412/64474157-c4084580-d1ab-11e9-8daa-304173c057c3.png">

**Comment by teeolendo** [comment]
Couldn't reproduce the error here https://snack.expo.io/@teeolendo/min-height-error

Have you since resolved this?

**Comment by pavm035** [comment]
@teeolendo  Would you please test it in iOS or Android simulator instead?

**Comment by teeolendo** [comment]
Ok, I can confirm that it actually is as you say when running on the device. The observable behavior is that if minHeight is greater than the child element height, it multiplies the difference by the number of rows created and creates a bigger margin. I assume for your implementation that you have to use minHeight and flexwrap in this way?

**Comment by pavm035** [comment]
@teeolendo Yes i expect web app behavior when we run the above code so for devices should i do anything to fix this?
