### ISSUE TITLE
StatusBar barStyle prop not working when dark-mode activated on iOS 13 beta.

### ISSUE THREAD

**Issue by cuttlas** [facebook/react-native#26369]
On iOS 13 beta, I'm trying to change the style of the status bar using the StatusBar component, but it doesn't work when the System's Appearance is set to Dark. Note that it does work as expected when the System's Appearance is light.

React Native version: 0.59.1

## Steps To Reproduce

1. On iOS 13 beta, change the system's Appearance to Dark in Settings -> Developer.
2. Try to set the barStyle prop on the StatusBar component to "dark-content": 

`<StatusBar barStyle="dark-content" />
`

### Describe what you expected to happen:

I expect the color of status bar elements (battery, network...) to be black, but they remain white.

**Comment by mezod** [comment]
we are experiencing the same issue

**Comment by tr3v3r** [comment]
Related pull request https://github.com/facebook/react-native/pull/25919

**Comment by nonoyek** [comment]
i facing this issue too, cant change to "light-content"

**Comment by tr3v3r** [comment]
@nonoyek What we managed to do for now it just to adopt application to dark mode. I mean change light colors to dark and etc.

**Comment by wenkangzhou** [comment]
Has any progress？

**Comment by mashaole** [comment]
has there been any progress ? so far i just keep the background color of the status bar as dark so that if my app is in dark mode or light mode i can see the content

**Comment by AurangzaibRamzan** [comment]
+1

**Comment by cristianoccazinsp** [comment]
+1

**Comment by r1ckyrockz** [comment]
+1

**Comment by fonov** [comment]
working solution https://github.com/facebook/react-native/issues/26619#issuecomment-536813690

**Comment by WaveMeUp** [comment]
Same problem here

**Comment by seajean** [comment]
Same problem here

**Comment by svenlombaert** [comment]
I upgraded to 0.62 and this issue seems resolved.

**Comment by ortigozamatias** [comment]
We are using Expo SDK `v36.0.0`, which is based on `react-native v0.61.4` and still having the same problem.

**Comment by DenisSokoloff** [comment]
> 
> 
> I upgraded to 0.62 and this issue seems resolved.

![image](https://user-images.githubusercontent.com/18741464/72885915-8860b900-3d11-11ea-8ac1-efcf5ce31915.png)

A u from future? :)

**Comment by svenlombaert** [comment]
@DenisSokoloff yes I am.

On a serious note: upgraded to 0.61, and yes, it works 😉

**Comment by DenisSokoloff** [comment]
> 
> 
> @DenisSokoloff yes I am.
> 
> On a serious note: upgraded to 0.61, and yes, it works 😉

I have     "react-native": "0.61.5",
But in iOS I do not see changes from dark and light :(

**Comment by fedarenchyk** [comment]
> > @DenisSokoloff yes I am.
> > On a serious note: upgraded to 0.61, and yes, it works 😉
> 
> I have "react-native": "0.61.5",
> But in iOS I do not see changes from dark and light :(

+1

**Comment by yastrebovb** [comment]
> > @DenisSokoloff yes I am.
> > On a serious note: upgraded to 0.61, and yes, it works 😉
> 
> I have "react-native": "0.61.5",
> But in iOS I do not see changes from dark and light :(

Same issue.

**Comment by brunnohofmann** [comment]
Its happening to me as well. On Ios its working well. Im using Android 5 on simulator

**Comment by fedarenchyk** [comment]
> Its happening to me as well. On Ios its working well. Im using Android 5 on simulator

I don't know why, but on Android 5 `StatusBar.setBarStyle('dark-content/light-content')` does not working. Android 6 and upper working correctly

**Comment by svenlombaert** [comment]
As the docs state (https://facebook.github.io/react-native/docs/statusbar) dark-content on Android is only working for Android API >= 25. That's Android 6 and above.

**Comment by xhirazi** [comment]
+1
