### ISSUE TITLE
writingDirection doesn't work on Android

### ISSUE THREAD

**Issue by Noaya** [facebook/react-native#26375]
My app can be used in different languages, including Hebrew (which is RTL).
For all of my text elements, I am using:
writingDirection: I18nManager.isRTL ? 'rtl' : 'ltr'

This works flawlessly on iOS, but doesn't work on Android. The text (which combines Hebrew and English) is messed up, only on Android.

React Native version:
  React Native Environment Info:
    System:
      OS: macOS 10.14.6
      CPU: (12) x64 Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
      Memory: 18.14 MB / 32.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.14.2 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 27.0.3, 28.0.3
        System Images: android-26 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.10 => 0.59.10 
    npmGlobalPackages:
      react-native-cli: 2.0.1## Steps To Reproduce

**Comment by dulmandakh** [comment]
Please provide reproducible demo code
