### ISSUE TITLE
Jetifier stucks at "info Running jetifier to migrate libraries to AndroidX."

### ISSUE THREAD

**Issue by seeseesky** [facebook/react-native#26372]
When I ran ```npx react-native run-android```, it gets stuck at ```info Running jetifier to migrate libraries to AndroidX.``` for 30mins already but still not advancing to the next step. However, it was working fine last week.

React Native version: 0.60.4
React version: 16.8.6

## Steps To Reproduce

1. Running```npx react-native run-android```

Describe what you expected to happen:
I expected the jetifier will quickly jetified all packages and start compiling the app.

Snack, code example, screenshot, or link to a repository:
<img width="855" alt="Screenshot 2019-09-08 at 11 35 54 AM" src="https://user-images.githubusercontent.com/9151401/64482919-e42c1900-d22c-11e9-8930-ee9d4e362216.png">

**Comment by yogeshkotadiya** [comment]
Did you migrate your project to AndroidX?
if not check this guide for [Migrating to AndroiX](https://developer.android.com/jetpack/androidx/migrate)

After that try running `jetifier` separately.
```bash
$ npx jetify
```

then run
```bash
$ npx react-native run-android --no-jetifier
```

Also `unlink` those libraries which support RN0.60 [Autolinking](https://facebook.github.io/react-native/blog/2019/07/03/version-60#native-modules-are-now-autolinked).

**Comment by seeseesky** [comment]
@yogeshkotadiya Yes I did migrate it to AndroidX already and it is working before. I did also unlink those libraries already but no luck
