### ISSUE TITLE
"RnDiffApp" has not been registered - 0.60.5 to 61.0-rc.2

### ISSUE THREAD

**Issue by PhamMinhKha** [facebook/react-native#26373]
After I upgraded from 0.60.5 to 61.0-rc.2. On ios devices working normally, but android has this error:
Invariant Violation: "RnDiffApp" has not been registered. This can happen if: * Metro (the local dev server) is run from the wrong folder. Check if Metro is running, strop and restart it in the current project.
* A module failed to load due to an error and 'AppRegistry.registerComponent' wasn't called.
![Screen Shot 2019-09-08 at 10 25 35 AM](https://user-images.githubusercontent.com/12944689/64482842-61eb2700-d223-11e9-9a44-e7ae9fef21d7.png)

React Native version:

  System:
    OS: macOS 10.14.3
    CPU: (8) x64 Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
    Memory: 72.03 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.2 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.11.2 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: ^16.9.0 => 16.9.0 
    react-native: ^0.61.0-rc.2 => 0.61.0-rc.2 
  npmGlobalPackages:
    react-native-cli: 2.0.1
Phams-Mac-mini-2:SuaChuaPro phamminhkha$

**Comment by PhamMinhKha** [comment]
sorry. this it not issue

**Comment by lucas-wilmart** [comment]
I have the exact same issue. What do you mean this is not an issue ?

How did you solve it ?

**Comment by leosena777** [comment]
@lucas-wilmart complementing what PhamMinhKha said:
Make sure your MainActivity.java file has the correct project name.

`@Override
    protected String getMainComponentName() {
        return "FastFest";
    }
`

I had the same problem when I used react-native's helper update. I didn't bother to see that I should not change the project name in this method.

**Comment by mukhtorov** [comment]
In my case, I've deleted the node_modules and android/app/build files,

> working fine on me

**Comment by sooriyaprakasht** [comment]
> @lucas-wilmart complementing what PhamMinhKha said:
> Make sure your MainActivity.java file has the correct project name.
> 
> `@Override protected String getMainComponentName() { return "***name of your project****" } `
> 
> I had the same problem when I used react-native's helper update. I didn't bother to see that I should not change the project name in this method.

If you want to change it to something else, you need to change in two places and dont forget to restart the metro server after the changes.
1. MainActivity.java -> getMainComponentName should return the new name 
2. index.js (or whichever is your initial file) in the project root should register for the new name :: AppRegistry.registerComponent("new name", () => App);

**Comment by creditcoder** [comment]
> In my case, I've deleted the node_modules and android/app/build files,
> 
> > working fine on me

Worked on my project also.

**Comment by 3DEsprit** [comment]
For iOS, you need to change the moduleName found in the AppDelegate.m file. When upgrading, this defaults back to the generic RnDiffApp name.

**Comment by arielon** [comment]
> For iOS, you need to change the moduleName found in the AppDelegate.m file. When upgrading, this defaults back to the generic RnDiffApp name.

@3DEsprit  What's the final name of moduleName? I only ran npx react-native init NameProject and try to ran it and obtain same issue

**Comment by 3DEsprit** [comment]
@arielon the module name set in the AppDelegate.m file should match your project name, and make sure it's formatted as an Objective-C string (should lead with a @). Here's an example:

<img width="834" alt="appdelegate" src="https://user-images.githubusercontent.com/3156278/76051109-5a38e080-5f2f-11ea-92d9-f09e18207140.png">

If that's still giving you trouble, you may want to make sure it matches the name set in the Xcode project itself, as well as the name in the app.json file. If you don't have an app.json file, make sure the name used in the initial index.js AppRegistry.registerComponent call matches as well. 

I hope that helps!

**Comment by MrLih** [comment]
I changed the content structure of app.js. after this, it was something like this 
{
  "expo": {
   "name": "WishList",
   "icon": "./assets/logo.png",
   "version": "1.0.0",
   "slug": "wish-list",
   "splash":{
    "image":"./assets/splash.png",
    "resizeMode":"contain",
    "backgroungColor":"#1AAACF"
   },
   "ios": {
     "bundleIdentifier": "io.alejo.WishList",
     "buildNumber": "1.0.0"
   },
   "android": {
     "package": "io.alejo.WishList",
     "versionCode": 1
   }
  }
}

what I had to do was change index.js like so

import {AppRegistry} from 'react-native'
import App from './src/index'
import {expo as appName} from './app.json'

console.log('appName: ',appName)

AppRegistry.registerComponent(appName.name, () => App)

**Comment by darshantogadiya** [comment]
> @lucas-wilmart complementing what PhamMinhKha said:
> Make sure your MainActivity.java file has the correct project name.
> 
> `@Override protected String getMainComponentName() { return "***name of your project****" } `
> 
> I had the same problem when I used react-native's helper update. I didn't bother to see that I should not change the project name in this method.

Thank you @leosena777. this is also working for me

**Comment by xwchris** [comment]
Just use lowercase as a project name when init project !
