### ISSUE TITLE
“However, this package itself specifies a `main` module field”， why?

### ISSUE THREAD

**Issue by Staryixing** [facebook/react-native#26380]
bundling failed: Error: While trying to resolve module `react-navigation` from file `/Users/macos/ant-design-demo01/cai-rn-demo/caiDemo/App/App.js`, the package `/Users/macos/ant-design-demo01/cai-rn-demo/caiDemo/node_modules/react-navigation/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved

**Comment by Staryixing** [comment]
"react-navigation": "^4.0.0"
"react-native": "0.60.5",

**Comment by garmon25** [comment]
i am also having this issue as well same 
  "react-native": "0.60.5",
    "react-navigation-stack": "^1.7.3"

**Comment by Staryixing** [comment]
Are you using ios or android?

I use ios
Before, the third-party library needed react-native link XXX（the third-party library）
Now I use CocoaPods
cd ios
pod install
cd..

**Comment by alivevietnam** [comment]
I have a same issue

"react-native": "0.60.5",
"react-navigation": "^4.0.10",

**Comment by prateekagarwal721** [comment]
i am also getting the same issue

"react-native": "0.60.5
