### ISSUE TITLE
[Docs] Should be able to answer the question: "what do I need to do when I'm ready to deploy to production?"

### ISSUE THREAD

**Issue by cheyueyong** [facebook/react-native#2638]
same as to title.

**Comment by brentvatne** [comment]
While this type of question is usually best suited for StackOverflow, I think we do need some better documentation around it. Check this out for now: https://facebook.github.io/react-native/docs/running-on-device-ios.html#content

If you need more assistance for the moment I encourage you to repost this to StackOverflow :)

**Comment by cheyueyong** [comment]
ok  3q @brentvatne
