### ISSUE TITLE
ENOENT: no such file or directory, scandir '/Users/sukhwindersingh/iCloud Drive (Archive)/Documents/Project/assets'

### ISSUE THREAD

**Issue by sukhwinder-559** [facebook/react-native#26382]
ENOENT: no such file or directory, scandir '/Users/sukhwindersingh/iCloud Drive (Archive)/Documents/Project/assets'
Failed building JavaScript bundle.

this is the error i am getting please help me out here. 
earlier i was able ti run my same project but all of a sudden it stopped working. 

https://www.heypasteit.com/clip/0IT7NR﻿ 

this is my code for firebase authentication

used: firebase react-navigation native-base
![Screenshot 2019-09-09 at 3 48 14 PM](https://user-images.githubusercontent.com/32087224/64523611-4f9fe480-d31a-11e9-9e41-e731bcbc5b8f.png)

_Originally posted by @sukhwinder-559 in https://github.com/facebook/metro/issues/126#issuecomment-529405059_

**Comment by karasanyijohnson** [comment]
npm install solved my problem
