### ISSUE TITLE
[0.60.5] onPress with Fragment app ignored

### ISSUE THREAD

**Issue by hustlercoder** [facebook/react-native#26392]
React Native version: 0.60.5

## Steps To Reproduce

1. Create a basic app with a react-native init
2. Add a touchable element and onPress function. When you click nothing goes on.If you change the app container from fragment to View everything works.

Describe what you expected to happen: Using app with Fragment as container seems to not call onPress or ignore it every time.If you change Fragment with View the onPress is called again. I need to understand if can i use Fragment with onPress functions...because it seems to be part of the standard now

Snack, code example, screenshot, or link to a repository:

**Comment by TylerNRobertson** [comment]
Code example? I have never ran into this issue before.

**Comment by kesha-antonov** [comment]
Please share your code
