### ISSUE TITLE
Keyboardavoidingview does not work  with react-navigation in Android

### ISSUE THREAD

**Issue by bommala2019** [facebook/react-native#26394]
I have a TextInput at the bottom of the mobile screen and when user gets into focus of it , keyboard view is shown but it is getting overlapped with the TextInput and user cant see what is typed in it. For this problem to solve I tried  react-native inbuilt compoent 'Keyboardavoidingview' was tried  but it did not work as expected in Android.  the important point to note here is that I am using react-navigation header component. If I remove this component then it works perfectly so it is issue with the usage of react-navigation component.

React Native version:
React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
      Memory: 4.14 GB / 15.88 GB
    Binaries:
      Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5692245

## Steps To Reproduce

1. Use react - navigation component
2. Define any textInput at the bottom of the mobile screen.
3. Type on this textbox.

 
It is expected that it is automatically scrolled up and user can see what is typed in.

**Comment by Novsochetra** [comment]
@bommala2019

According to my experience, I face the problem the same as you.
Have you tried to look at this [issue](https://github.com/facebook/react-native/issues/13000)?

**Note:** Make sure you show the status bar.

**Comment by ARKEOLOGIST** [comment]
Still have this issue.

**Comment by GoranTopic** [comment]
I'm have the exact same issue

**Comment by ARKEOLOGIST** [comment]
I fixed my issue at least temporarily by removing android:windowSoftInputMode="adjustResize" from AndroidManifest.xml . I hope this helps some people until a dedicated fix comes along. I'm also using react-navigation in my project.
