### ISSUE TITLE
NavigationBar is default to `position:absolute`?

### ISSUE THREAD

**Issue by iostalk** [facebook/react-native#2639]
I write a component like below code, and I found that the <Text>ssss</Text> always is shown in the left-top position, the navigation bar is just like  `position:absolute` effect, doesn't possess any height.
What's the best practise to take this?
```
var MyV2EXApp = React.createClass({
  render: function() {
    return (
      <Navigator
        initialRoute={{
          title: '最新'
        }}
        renderScene={(route, navigator) => {
          const Component = route.component;
          return (
            <Text>ssss</Text>
          );
        }}
        navigationBar={
          <Navigator.NavigationBar
            routeMapper={NavigationBarRouteMapper}
            style={styles.navBar}
          />
        }
      />
    );
  }
});
```

**Comment by browniefed** [comment]
For questions about implementation please ask on StackOverflow and keep github for bugs/issues.
The best solution would be to give it a height.

@brentvatne stackoverlfow/implemenation question.

**Comment by ide** [comment]
Put `height: 64

**Comment by iostalk** [comment]
Okay,thank you!
