### ISSUE TITLE
Android Picker ArrayIndexOutOfBoundsException when length of children change

### ISSUE THREAD

**Issue by scarlac** [facebook/react-native#26406]
React Native version:
```
12:39:42 ~/jobs/pickercrash ⚡️ react-native info
info Fetching system and libraries information...
System:
    OS: macOS 10.14.5
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 26.04 MB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.8.0 - ~/.nvm/versions/node/v12.8.0/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.10.2 - ~/.nvm/versions/node/v12.8.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 27.0.3, 28.0.2, 28.0.3
      System Images: android-25 | Google Play Intel x86 Atom, android-27 | Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom_64
  IDEs:
    Android Studio: 3.2 AI-181.5540.7.32.5056338
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5
```

## Steps To Reproduce

1. Clone the repo
2. Run the project on Android
2. Tap "Foods"
3. Select "Japanese"
4. Tap "Pets"

An error occurs:

```
09-11 12:54:50.007 11910 11910 E unknown:ReactNative: Exception in native call
09-11 12:54:50.007 11910 11910 E unknown:ReactNative: java.lang.ArrayIndexOutOfBoundsException: length=3; index=3
09-11 12:54:50.007 11910 11910 E unknown:ReactNative: 	at java.util.Arrays$ArrayList.get(Arrays.java:3769)
09-11 12:54:50.007 11910 11910 E unknown:ReactNative: 	at android.widget.ArrayAdapter.getItem(ArrayAdapter.java:393)
09-11 12:54:50.007 11910 11910 E unknown:ReactNative: 	at com.facebook.react.views.picker.ReactPickerManager$ReactPickerAdapter.getView(ReactPickerManager.java:116)
09-11 12:54:50.007 11910 11910 E unknown:ReactNative: 	at com.facebook.react.views.picker.ReactPickerManager$ReactPickerAdapter.getView(ReactPickerManager.java:107)
09-11 12:54:50.007 11910 11910 E unknown:ReactNative: 	at android.widget.Spinner.makeView(Spinner.java:712)
09-11 12:54:50.007 11910 11910 E unknown:ReactNative: 	at android.widget.Spinner.layout(Spinner.java:660)
09-11 12:54:50.007 11910 11910 E unknown:ReactNative: 	at android.widget.AbsSpinner.setSelectionInt(AbsSpinner.java:306)
09-11 12:54:50.007 11910 11910 E unknown:ReactNative: 	at android.widget.AbsSpinner.setSelection(AbsSpinner.java:283)
09-11 12:54:50.007 11910 11910 E unknown:ReactNative: 	at com.facebook.react.views.picker.ReactPicker.commitStagedData(ReactPicker.java:142)
09-11 12:54:50.007 11910 11910 E unknown:ReactNative: 	at com.facebook.react.views.picker.ReactPickerManager.onAfterUpdateTransaction(ReactPickerManager.java:80)
09-11 12:54:50.007 11910 11910 E unknown:ReactNative: 	at com.facebook.react.views.picker.ReactPickerManager.onAfterUpdateTransaction(ReactPickerManager.java:36)
09-11 12:54:50.007 11910 11910 E unknown:ReactNative: 	at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:47)
09-11 12:54:50.007 11910 11910 E unknown:ReactNative: 	at com.facebook.react.uimanager.NativeViewHierarchyManager.updateProperties(NativeViewHierarchyManager.java:139)
09-11 12:54:50.007 11910 11910 E unknown:ReactNative: 	at com.facebook.react.uimanager.UIViewOperationQueue$UpdatePropertiesOperation.execute(UIViewOperationQueue.java:93)
09-11 12:54:50.007 11910 11910 E unknown:ReactNative: 	at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:844)
09-11 12:54:50.007 11910 11910 E unknown:ReactNative: 	at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:952)
09-11 12:54:50.007 11910 11910 E unknown:ReactNative: 	at com.facebook.react.uimanager.UIViewOperationQueue.access$2200(UIViewOperationQueue.java:44)
09-11 12:54:50.007 11910 11910 E unknown:ReactNative: 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1012)
09-11 12:54:50.007 11910 11910 E unknown:ReactNative: 	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
09-11 12:54:50.007 11910 11910 E unknown:ReactNative: 	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:172)
09-11 12:54:50.007 11910 11910 E unknown:ReactNative: 	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:84)
09-11 12:54:50.007 11910 11910 E unknown:ReactNative: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:947)
09-11 12:54:50.007 11910 11910 E unknown:ReactNative: 	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
09-11 12:54:50.007 11910 11910 E unknown:ReactNative: 	at android.view.Choreographer.doFrame(Choreographer.java:693)
09-11 12:54:50.007 11910 11910 E unknown:ReactNative: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
09-11 12:54:50.007 11910 11910 E unknown:ReactNative: 	at android.os.Handler.handleCallback(Handler.java:873)
09-11 12:54:50.007 11910 11910 E unknown:ReactNative: 	at android.os.Handler.dispatchMessage(Handler.java:99)
09-11 12:54:50.007 11910 11910 E unknown:ReactNative: 	at android.os.Looper.loop(Looper.java:193)
09-11 12:54:50.007 11910 11910 E unknown:ReactNative: 	at android.app.ActivityThread.main(ActivityThread.java:6669)
09-11 12:54:50.007 11910 11910 E unknown:ReactNative: 	at java.lang.reflect.Method.invoke(Native Method)
09-11 12:54:50.007 11910 11910 E unknown:ReactNative: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
09-11 12:54:50.007 11910 11910 E unknown:ReactNative: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
09-11 12:54:50.013 11910 11910 D AndroidRuntime: Shutting down VM
09-11 12:54:50.014 11910 11910 E AndroidRuntime: FATAL EXCEPTION: main
09-11 12:54:50.014 11910 11910 E AndroidRuntime: Process: com.pickercrash, PID: 11910
```

**Describe what you expected to happen:**
Picker options are re-rendered with the newly rendered `selectedValue` prop.

**Snack, code example, screenshot, or link to a repository:**
The issue does not reproduce in an Expo Snack, with the latest version, so I must assume it's a bug introduced in later versions.

I have created a standalone project here:
https://github.com/scarlac/pickercrash

<img width="498" alt="image" src="https://user-images.githubusercontent.com/895369/64729594-52254a00-d492-11e9-9d3f-06777fa20a7d.png">

**Speculation:**
I am speculating that the options within `Picker` (ie. `Picker.Item`) are re-rendered before the parent Picker has a chance to change value. Because the native re-render is not in sync with the virtual dom, the list of Picker.Item will be re-rendered to a shorter list (list of 3 pets vs 4 foods), but the native Picker will still carry the old setting, causing a crash, despite the virtual dom being in perfect sync.

**Workaround / hack:**
Add a `key` to the Picker that is in sync with the category, such that React Native internally doesn't re-use the existing Picker across categories.

**Comment by catrinalee91** [comment]
👍

**Comment by Joel-Raju** [comment]
adding `key` did fix the crash. 

Thanks @scarlac

**Comment by rszalski** [comment]
I had the same issue, but in my case I was using the same `Picker` component for rendering and handling 2 separate sets of values (conditions based on another Picker's value). The `key` workaround did not work for me for some reason (didn't debug it deeper) but I simply split the component into 2. And hey, the code is cleaner now :)

**Comment by BogdanRad** [comment]
I have same error on release app on android.. if I test on the emulator I get no error ...
here is my code: 
`// @flow
import React, { useEffect, useRef, useState } from 'react';
import {
  Animated,
  Dimensions,
  FlatList,
  TouchableOpacity,
  View,
  Alert,
} from 'react-native';
import Map, { Callout, PROVIDER_GOOGLE, Marker } from 'react-native-maps';
import Geolocation from '@react-native-community/geolocation';
import Permissions from 'react-native-permissions';

import { Icon } from '../Icon';
import { OffersOverlay } from '../OffersOverlay';
import { generateMarkers } from './generateMarkers';
import { mapStyles } from './mapStyles';

import { style } from './style';
import { colour } from '../../theme';
import { mapCutout } from '../../images';
import { animate } from '../../utils/animatedTiming';

import type { ID, Offer } from '../../types';
import permissionStrings from '../../constants/permissionStrings';

type OffersMapProps = {
  offers: Offer[],
  onGoToOffer: (id: ID) => void,
};

const { height, width } = Dimensions.get('window');
const ASPECT_RATIO = width / height;

const LATITUDE = 51.523662;
const LONGITUDE = -0.097687;
const LATITUDE_DELTA = 0.015;
const LONGITUDE_DELTA = LATITUDE_DELTA * ASPECT_RATIO;

const OffersMap = (props: OffersMapProps) => {
  const { offers, onGoToOffer } = props;

  const mapElement = useRef(null);
  const [markers, setMarkers] = useState([]);
  const [currentIndex, setCurrentIndex] = useState(0);
  const [interacting, setInteracting] = useState(false);
  const [animatedValue] = useState(new Animated.Value(0));
  const [region, setRegion] = useState({
    latitude: LATITUDE,
    longitude: LONGITUDE,
    latitudeDelta: LATITUDE_DELTA,
    longitudeDelta: LONGITUDE_DELTA,
  });
  const [zIndexMap, setZIndexMap] = useState(1);

  const centerLocation = async (animation?: boolean) => {
    const permType = permissionStrings.types.location;
    await Permissions.request(permType).then(requestResponse => {
      if (requestResponse === 'denied' && animation) {
        Alert.alert('Please allow location services');
      }
      if (
        requestResponse === permissionStrings.responses.undetermined ||
        requestResponse === permissionStrings.responses.authorized
      ) {
        Geolocation.getCurrentPosition(
          position => {
            setRegion({
              latitude: position.coords.latitude,
              longitude: position.coords.longitude,
              latitudeDelta: LATITUDE_DELTA,
              longitudeDelta: LONGITUDE_DELTA,
            });
            if (animation && mapElement.current) {
              mapElement.current.animateToRegion({
                ...region,
                // Center the map slightly higher because of overlay
                latitude: region.latitude - 0.002,
              });
              setInteracting(false);
            }
          },
          error => console.error(error.message),
          { enableHighAccuracy: true, timeout: 20000, maximumAge: 1000 },
        );
      }
    });
  };

  useEffect(() => {
    centerLocation();
  }, []);

  useEffect(() => {
    setMarkers(generateMarkers(offers));
    centerLocation();
    setCurrentIndex(0);
  }, [offers]);

  useEffect(() => {
    animate({
      element: animatedValue,
      toValue: interacting ? 1 : 0,
      useNativeDriver: true,
    });
  }, [interacting]);

  const overlayOpacity = {
    opacity: animatedValue.interpolate({
      inputRange: [0, 1],
      outputRange: [0, 1],
    }),
  };

  const onMapReady = () => {
    setZIndexMap(-1);
  };

  return (
    <View style={style.container}>
      <Animated.Image
        pointerEvents="none"
        source={mapCutout}
        style={[style.mapOverlay, overlayOpacity]}
      />
      <TouchableOpacity
        style={style.centerLocation}
        onPress={() => centerLocation(true)}>
        <Icon name="location" color={colour.brand} type="light" />
      </TouchableOpacity>
      <Map
        customMapStyle={mapStyles}
        followsUserLocation
        initialRegion={region}
        onRegionChange={() => setInteracting(true)}
        onRegionChangeComplete={() => setInteracting(false)}
        provider={PROVIDER_GOOGLE}
        ref={mapElement}
        showsIndoors
        showsUserLocation
        style={[style.map, { zIndex: zIndexMap }]}
        onMapReady={onMapReady}>
        {markers.map(
          (marker, i) =>
            marker.coordinate.latitude &&
            marker.coordinate.longitude && (
              <Marker
                flat
                key={
                  currentIndex === i
                    ? marker.offer.id
                    : `android-fix${marker.offer.id}`
                }
                title={marker.title}
                description={marker.description}
                coordinate={marker.coordinate}
                calloutOffset={{ y: -0.5, x: 0 }}
                pinColor={
                  currentIndex === i ? colour.brand : colour.secondaryBrand
                }
                onPress={() => setCurrentIndex(i)}
                tracksViewChanges>
                {/* Disabled tooltip */}
                <Callout tooltip />
              </Marker>
            ),
        )}
      </Map>
      {markers && markers.length > 0 && (
        <View style={style.overlayContainer}>
          <FlatList
            scrollEnabled={false}
            data={markers}
            extraData={currentIndex}
            keyExtractor={item => `${item.offer.id}`}
            renderItem={({ item, index }) => (
              <OffersOverlay
                key={index}
                currentIndex={currentIndex}
                itemIndex={index}
                offer={item.offer}
                onGoToOffer={onGoToOffer}
              />
            )}
          />
        </View>
      )}
    </View>
  );
};

export default OffersMap;
`
and i received this error: 
ArrayIndexOutOfBoundsExceptioncom.facebook.react.uimanager.ViewGroupDrawingOrderHelper in getChildDrawingOrder
fatal
length=5; index=5

How to fix this problem?

**Comment by scarlac** [comment]
There is no indication that the ticket was fixed. If someone knows that it has, feel free to let me know so I can close it, otherwise the issue can still be considered active.
