### ISSUE TITLE
Unable to run new app created from cli RN 0.60.5 version pod install glog (0.3.5) error, help me

### ISSUE THREAD

**Issue by amitrai98** [facebook/react-native#26409]
React Native version: 0.60.5
System:
    OS: macOS 10.14.3
    CPU: (4) x64 Intel(R) Core(TM) i3-4130 CPU @ 3.40GHz
    Memory: 2.20 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    Android SDK:
      API Levels: 23, 27, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 10.1/10B61 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
mojaves-iMac:NativeBridgeDemo mojave$ 

## Steps To Reproduce

1. react-native init "ProjectName"

Installing DoubleConversion (1.1.6)
Installing Folly (2018.10.22.00)
Installing React (0.60.5)
Installing React-Core (0.60.5)
Installing React-DevSupport (0.60.5)
Installing React-RCTActionSheet (0.60.5)
Installing React-RCTAnimation (0.60.5)
Installing React-RCTBlob (0.60.5)
Installing React-RCTImage (0.60.5)
Installing React-RCTLinking (0.60.5)
Installing React-RCTNetwork (0.60.5)
Installing React-RCTSettings (0.60.5)
Installing React-RCTText (0.60.5)
Installing React-RCTVibration (0.60.5)
Installing React-RCTWebSocket (0.60.5)
Installing React-cxxreact (0.60.5)
Installing React-jsi (0.60.5)
Installing React-jsiexecutor (0.60.5)
Installing React-jsinspector (0.60.5)
Installing boost-for-react-native (1.63.0)
Installing glog (0.3.5)
[!] /bin/bash -c 
set -e
#!/bin/bash
# Copyright (c) Facebook, Inc. and its affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

set -e

PLATFORM_NAME="${PLATFORM_NAME:-iphoneos}"
CURRENT_ARCH="${CURRENT_ARCH}"

if [ -z "$CURRENT_ARCH" ] || [ "$CURRENT_ARCH" == "undefined_arch" ]; then
    # Xcode 10 beta sets CURRENT_ARCH to "undefined_arch", this leads to incorrect linker arg.
    # it's better to rely on platform name as fallback because architecture differs between simulator and device

    if [[ "$PLATFORM_NAME" == *"simulator"* ]]; then
        CURRENT_ARCH="x86_64"
    else
        CURRENT_ARCH="armv7"
    fi
fi

export CC="$(xcrun -find -sdk $PLATFORM_NAME cc) -arch $CURRENT_ARCH -isysroot $(xcrun -sdk $PLATFORM_NAME --show-sdk-path)"
export CXX="$CC"

# Remove automake symlink if it exists
if [ -h "test-driver" ]; then
    rm test-driver
fi

./configure --host arm-apple-darwin

# Fix build for tvOS
cat << EOF >> src/config.h

/* Add in so we have Apple Target Conditionals */
#ifdef __APPLE__
#include <TargetConditionals.h>
#include <Availability.h>
#endif

/* Special configuration for AppleTVOS */
#if TARGET_OS_TV
#undef HAVE_SYSCALL_H
#undef HAVE_SYS_SYSCALL_H
#undef OS_MACOSX
#endif

/* Special configuration for ucontext */
#undef HAVE_UCONTEXT_H
#undef PC_FROM_UCONTEXT
#if defined(__x86_64__)
#define PC_FROM_UCONTEXT uc_mcontext->__ss.__rip
#elif defined(__i386__)
#define PC_FROM_UCONTEXT uc_mcontext->__ss.__eip
#endif
EOF

# Prepare exported header include
EXPORTED_INCLUDE_DIR="exported/glog"
mkdir -p exported/glog
cp -f src/glog/log_severity.h "$EXPORTED_INCLUDE_DIR/"
cp -f src/glog/logging.h "$EXPORTED_INCLUDE_DIR/"
cp -f src/glog/raw_logging.h "$EXPORTED_INCLUDE_DIR/"
cp -f src/glog/stl_logging.h "$EXPORTED_INCLUDE_DIR/"
cp -f src/glog/vlog_is_on.h "$EXPORTED_INCLUDE_DIR/"

checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for arm-apple-darwin-strip... no
checking for strip... strip
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for arm-apple-darwin-gcc... /Applications/Xcode 3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -arch armv7 -isysroot /Applications/Xcode 3.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk
checking whether the C compiler works... no
/Users/mojave/Library/Caches/CocoaPods/Pods/External/glog/2263bd123499e5b93b5efe24871be317-1f3da/missing: Unknown `--is-lightweight' option
Try `/Users/mojave/Library/Caches/CocoaPods/Pods/External/glog/2263bd123499e5b93b5efe24871be317-1f3da/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: in `/Users/mojave/Library/Caches/CocoaPods/Pods/External/glog/2263bd123499e5b93b5efe24871be317-1f3da':
configure: error: C compiler cannot create executables
See `config.log' for more details

It Should have created a new project rather than this.

Snack, code example, screenshot, or link to a repository:

**Comment by prabakarviji** [comment]
@amitrai98 Hope this solution help https://forums.expo.io/t/pod-install-errors-on-newly-detached-app-on-macos-installing-glog-bin-bash-configure-bin-sh-m-bad-interpreter-no-such-file-or-directory/10054/3. Worked for me 😃

**Comment by arisupriatna14** [comment]
Yeah, mee too. I have same issues. :(

**Comment by amitrai98** [comment]
Resolved this issue, 
open xcode and navigate to the settings 
xcode>preference>location
change the value of command line tools to the latest version of xcode you have
my previous version was 9.3.1
I updated it to 10.2.1
now navigate to the location of derived data from the same menu by clicking forward arrow 
under derived data menu
delete the data and quit xcode also epty the trash and try now 
it worked for me.

**Comment by ham118** [comment]
> Resolved this issue,
> open xcode and navigate to the settings
> xcode>preference>location
> change the value of command line tools to the latest version of xcode you have
> my previous version was 9.3.1
> I updated it to 10.2.1
> now navigate to the location of derived data from the same menu by clicking forward arrow
> under derived data menu
> delete the data and quit xcode also epty the trash and try now
> it worked for me.

After cleaning derived data still, throw the same error

**Comment by andcosta** [comment]
You either need to do a xcode-select, or at least in XCode. Preferences/Locations/Command Line Tools

**Comment by migueldaipre** [comment]
> Resolved this issue,
> open xcode and navigate to the settings
> xcode>preference>location
> change the value of command line tools to the latest version of xcode you have
> my previous version was 9.3.1
> I updated it to 10.2.1
> now navigate to the location of derived data from the same menu by clicking forward arrow
> under derived data menu
> delete the data and quit xcode also epty the trash and try now
> it worked for me.

Work for me, thanks!
