### ISSUE TITLE
fatal error: 'double-conversion/double-conversion.h' file not found during upgrade from rn version 0.59.8 to 0.60.5

### ISSUE THREAD

**Issue by knight-hub** [facebook/react-native#26405]
I was using the [React Native upgrade helper](https://react-native-community.github.io/upgrade-helper/?from=0.59.8&to=0.60.5) to upgrade from React Native Version 0.59.8 to 0.60.5. After changing all non Android specific files building the project failed with the hint: `fatal error: 'double-conversion/double-conversion.h' file not found`. A `Podfile` already existed in the project before upgrading React Native and was modified in the process: [Podfile_New.txt](https://github.com/facebook/react-native/files/3602083/Podfile_New.txt), 
[Podfile_Old.txt](https://github.com/facebook/react-native/files/3602085/Podfile_Old.txt)

Interestingly changing the line `#include <double-conversion/double-conversion.h>` to `#include <DoubleConversion/double-conversion.h>` in `ios/Pods/Folly/folly/Conv.h` seems to solve this problem, however other errors are then triggered. Also this does not feel like a 'real' solution.

React Native version:

System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 51.46 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.14.0 - /usr/local/bin/node
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
  IDEs:
    Android Studio: 3.4 AI-183.5429.30.34.5452501
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    @react-native-community/cli: 1.10.0 => 1.10.0 
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1

**Comment by RZzero** [comment]
Having the same issue.

**Comment by Dagorik** [comment]
Having the same issue.

**Comment by kenMarquez** [comment]
I also have the same issue  !

**Comment by kenMarquez** [comment]
I'm solving that with :

- removing `use_frameworks!` from your Podfile
- close xCode
- rm -rf ~/library/developer/xcode/deriveddata
- rm -rf ~/.rncache
- rm -rf node_modules && yarn install && cd ios && rm -rf Pods && pod install && cd ..
- clean and run

**Comment by knight-hub** [comment]
Thank you @kenMarquez, your steps solved the problem for me! I skipped the first step (because I never had `use_frameworks!` in my Podfile) and then executed the remaining 5 steps. After that I only had to unlink a few dependencies and the build was successful.

**Comment by waheedakhter** [comment]
@kenMarquez I need to use use_frameworks since I am using react-native-applozic-chat library and that requires this thing. what would be the solution for me?

**Comment by AdrianMrn** [comment]
@waheedakhter did you find a solution for this?

**Comment by kenMarquez** [comment]
@waheedakhter @AdrianMrn If you upgrade your RN version to 0.61.0 in that version solve the problems with the frameworks

![image](https://user-images.githubusercontent.com/10731555/67042398-6b529380-f0ed-11e9-9fab-ba7d1dd11018.png)


You also download manually the library and paste into the Frameworks folder and don't forget add in `Link Binary With Libraries`

**Comment by AdrianMrn** [comment]
@kenMarquez Thanks, I'm upgrading now 🤞

**Comment by CVRamana** [comment]
> I'm solving that with :
> 
> * removing `use_frameworks!` from your Podfile
> * close xCode
> * rm -rf ~/library/developer/xcode/deriveddata
> * rm -rf ~/.rncache
> * rm -rf node_modules && yarn install && cd ios && rm -rf Pods && pod install && cd ..
> * clean and run

If i remove the use_frameworks from the pod file then it give the firebaseMessaging Error =>Protobuf/Any.h not found and to solve this i have to write use_frameworks! in the pod file 

so finally iam in the loop of this Error..

**Comment by CVRamana** [comment]
> @waheedakhter @AdrianMrn If you upgrade your RN version to 0.61.0 in that version solve the problems with the frameworks
> 
> ![image](https://user-images.githubusercontent.com/10731555/67042398-6b529380-f0ed-11e9-9fab-ba7d1dd11018.png)
> 
> You can also download manually the library and paste into the Frameworks folder and don't forget add in `Link Binary With Libraries`

Please provide the full solution

**Comment by AugustoAleGon** [comment]
@kenMarquez Solution works. I had the same problem with use framework. So I just upgrade to RN 0.61.5.
@CVRamana just take a look to rn-diff-purge.
