### ISSUE TITLE
[TextInput] alignText props does not work with multiline TextInput.

### ISSUE THREAD

**Issue by f15gdsy** [facebook/react-native#2641]
Hi,
when I use alignText props with non-multiline TextInput, it works fine.
But when I use it with multiline TextInput, it doesn't work.

Here is the screenshot.
The upper TextInput has multiline set to false, and textAlign set to 'right'.
The lower one doesn't work with textAlign set to 'right' or 'end'.

![Screenshot](https://dl.dropboxusercontent.com/u/27907965/images/Screen%20Shot%202015-09-12%20at%2012.36.15%20am.png)

**Comment by brentvatne** [comment]
Hi there! Multiline TextInput is likely to be re-written to support auto-scaling based on content size: #1229 
cc @lukasreichart let's make sure that the rewrite supports this.

**Comment by lukasreichart** [comment]
@f15gdsy @brentvatne Thanks for reporting. I'll look into this problem.

**Comment by brentvatne** [comment]
Thanks @lukasreichart we :heart: you

**Comment by ms88privat** [comment]
@lukasreichart also "multiline" does not set the cursor correctly if an initial value is provided. You will start typing in front of the provided text. Tested on iOS only. 

Thanks a lot

**Comment by ms88privat** [comment]
@dnbrwstr does this fix my mentioned issue from above too? (or was it fixed in some other version by now?)

**Comment by antonzy** [comment]
Looks like the placeholder text still ignores textAlign when multiline is true.
Using RN 0.26.3.
