### ISSUE TITLE
React Native Hermes: undefined is not a function js engine: hermes

### ISSUE THREAD

**Issue by mronline** [facebook/react-native#26411]
![d06haykOB7S2Y4PvtwxH8sGAK9qTjf-FzJ6Nje4ubV15wUASCqYsxHfPTvlit](https://user-images.githubusercontent.com/7905030/64766476-b574b200-d54e-11e9-8117-85ba4f20ab19.jpeg)

React Native version: 0.60.5

## Steps To Reproduce

1. I have updated the react native version to be able to use hermes. `0.60 => 0.60.5`
I updated it with: https://react-native-community.github.io/upgrade-helper/?from=0.60.0&to=0.60.5
2. Then I applied here: https://facebook.github.io/react-native/docs/hermes/ and I am encountering such error: undefined is not a function js engine: hermes

**Comment by radko93** [comment]
Please provide some code snippet or we might not help.

**Comment by Nghi-NV** [comment]
Same issues when use hermes (RN version 0.61.1). The problem occurred when I used the library react-native-jwt-io

<img width="346" alt="image" src="https://user-images.githubusercontent.com/32028055/66123394-1b170400-e60c-11e9-850d-e7193368d65b.png">
