### ISSUE TITLE
Dev mode trying to find /index.android.bundle (Unable to resolve module `./index.android` from ``)

### ISSUE THREAD

**Issue by JB-CHAUVIN** [facebook/react-native#26418]
Hello,

I upgraded from RN 0.59.9 to 0.61.0.rc3.

On Android, when I compile the app (after yarn install and cleaning the Android project), I have a red crash error saying :
```
Error: Unable to resolve module `./index.android` from ``:

None of these files exist:
  * index.android(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.svg|.native.svg|.svg)
  * index.android/index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.svg|.native.svg|.svg)
    at ModuleResolver.resolveDependency (/Users/jbchauvin1/Documents/Projets/Santoyamo/Cegedim/new/Mobile/app-dev/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:163:15)
    at ResolutionRequest.resolveDependency (/Users/jbchauvin1/Documents/Projets/Santoyamo/Cegedim/new/Mobile/app-dev/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (/Users/jbchauvin1/Documents/Projets/Santoyamo/Cegedim/new/Mobile/app-dev/node_modules/metro/src/node-haste/DependencyGraph.js:282:16)
    at /Users/jbchauvin1/Documents/Projets/Santoyamo/Cegedim/new/Mobile/app-dev/node_modules/metro/src/lib/transformHelpers.js:267:42
    at Server.<anonymous> (/Users/jbchauvin1/Documents/Projets/Santoyamo/Cegedim/new/Mobile/app-dev/node_modules/metro/src/Server.js:1088:41)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/jbchauvin1/Documents/Projets/Santoyamo/Cegedim/new/Mobile/app-dev/node_modules/metro/src/Server.js:99:24)
    at _next (/Users/jbchauvin1/Documents/Projets/Santoyamo/Cegedim/new/Mobile/app-dev/node_modules/metro/src/Server.js:119:9)
```

And my app/build.gradle : 
```
project.ext.react = [
    entryFile: "index.js",
    bundleAssetName: "index.android.bundle",
    bundleInDebug: false,
    bundleInRelease: true,
    enableHermes: false,  // clean and rebuild if changing
]
```

React Native version:
0.61 RC 3

## Steps To Reproduce

1. react-native run-android 
2. Red crash error...

Describe what you expected to happen:
I would like to see the Android app without any problems. That's weird, I don't understand why it's trying to load the index.android.bundle file.

Thanks for the help

**Comment by tsehiuming** [comment]
Hi JB-CHAUVIN, 
Came across the exact same issue this morning, here is my steps to solve the issue

1. Remove the bundleAssetName from project.ext.react (in app/build.gradle)
```
project.ext.react = [
    entryFile: "index.js",
    enableHermes: false,  // clean and rebuild if changing
]
```
2. Please make sure the function getJSMainModuleName() exist in MainApplication.java
```
public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      @SuppressWarnings("UnnecessaryLocalVariable")
      List<ReactPackage> packages = new PackageList(this).getPackages();
      // Packages that cannot be autolinked yet can be added manually here, for example:
      // packages.add(new MyReactNativePackage());
      return packages;
    }

    @Override
    protected String getJSMainModuleName() {
      return "index";
    }
  };
```

**Comment by rikur** [comment]
:+1:

**Comment by luavelino** [comment]
+1 anyone?

**Comment by ScripterSugar** [comment]
+1 for this issue

**Comment by steele-cjf** [comment]
so，no solution?

**Comment by ScripterSugar** [comment]
@steele-cjf I resolved the issue by creating index.android.js file that simply imports original index.js file, but I'm not sure it can be applied on other cases. give it a try.

**Comment by steele-cjf** [comment]
@ScripterSugar need any content in this file?

**Comment by ScripterSugar** [comment]
`import index.js from './'`

@steele-cjf mine looks like this.

**Comment by vojeda** [comment]
@ScripterSugar  Your solution has not helped me.

My application is ready for production and when uploading to Google Play they have stopped it because it is not compatible with 64bits. I have migrated from RN 0.54 to 0.61.5 and everything has been a headache, I have encountered several errors, including this one. I have reviewed the LOG and there is nothing very descriptive.

**Only when I access the route**
http://localhost:8081/index.android.bundle?platform=android&dev=false&hot=false&minify=false

**I can see the message appears**
Error: Unable to resolve module `./index.android` from ``: 

None of these files exist:
  * index.android(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * index.android/index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
    at ModuleResolver.resolveDependency (/Proyecto/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:163:15)
    at ResolutionRequest.resolveDependency (/Proyecto/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (/Proyecto/node_modules/metro/src/node-haste/DependencyGraph.js:282:16)
    at /Proyecto/node_modules/metro/src/lib/transformHelpers.js:267:42
    at Server.<anonymous> (/Proyecto/node_modules/metro/src/Server.js:1088:41)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Proyecto/node_modules/metro/src/Server.js:99:24)
    at _next (/Proyecto/node_modules/metro/src/Server.js:119:9)

**react-native info**
System:
    OS: macOS 10.15.2
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Memory: 30.63 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.1 - /usr/local/bin/node
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28, 29
      Build Tools: 23.0.1, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.3, 28.0.0, 28.0.2, 28.0.3, 29.0.0
      System Images: android-28 | Google Play Intel x86 Atom, android-29 | Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: ^0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1

**I am also using "react-native-navigation": "^ 6.3.3"**

HELP ME PLEASE!!

**Comment by kwoxer** [comment]
Same issue here.

**Comment by 592da** [comment]
Same issue here.... any thoughts?

**Comment by AlecksJohannes** [comment]
I ended up fixing this issue by create `index.android.js`  from `index.js`. I'm not sure if this is the right fix but it works for me.

**Comment by unpokolokko** [comment]
solution by @tsehiuming solve my problem. i missed out 
```
@Override
    protected String getJSMainModuleName() {
      return "index";
    }
```

**Comment by ktjd123** [comment]
> I ended up fixing this issue by create `index.android.js` from `index.js`. I'm not sure if this is the right fix but it works for me.

this helped me, but not sure too if this is right solution..
