### ISSUE TITLE
 Could not find or load main class org.gradle.wrapper.GradleWrapperMain

### ISSUE THREAD

**Issue by mdshadman** [facebook/react-native#26414]
when i execute the command react-native run-android i gets this error
System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
    Memory: 3.02 GB / 7.86 GB
  Binaries:
    Node: 10.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5522156
## Steps To Reproduce

1.react-native init demo and cd demo
2.react-native run-android

Expected
It should install and run on device.
```
 Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
The system cannot find the path specified.
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain

````
It was working absolutely fine before but as I created a new project from then i am getting this error.
![Screenshot (36)](https://user-images.githubusercontent.com/39180102/64775615-2b3f4480-d574-11e9-803e-4fdb1d40574c.png)

**Comment by asielykey** [comment]
In my case, I try many way people share but still not work
so:
- I reboot my computer,
- clear cache of user/admin/.gradle
- remove and reinstall C:/Gradle 
- rename project folder to a normal name.

I don't know what make it run. but it work :)))
