### ISSUE TITLE
[Android] Debug mode not connecting to server, debugger, not even showing developer menu

### ISSUE THREAD

**Issue by mrigo** [facebook/react-native#26417]
React Native version:
System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
    Memory: 294.97 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
    Watchman: 4.7.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 19, 23, 25, 26, 27, 28
      Build Tools: 23.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.1, 27.0.3, 28.0.3
      System Images: android-19 | Intel x86 Atom, android-22 | Google APIs Intel x86 Atom, android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64, android-26 | Google APIs Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-27 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.5 => 0.60.5

## Steps To Reproduce

1. install react native
2. react-native run-android OR react-native run-android --variant=debug 

Describe what you expected to happen:
Shaking the device must show me the developer menu, connecting to the debugger, or at least to local node server.

Neither with adb shell input keyevent 82 something happens...

I restarted the mac, android studio removing .idea and .iml files, but nothing.. with iOS all is working without problems...

Thanks
\m

**Comment by martinsinghk** [comment]
I recently encountered the same issue after an upgrade from v0.59.4 to v0.60.5, and it only happened in Android devices or simulators too. Wonder if my solution works for you. If you could find an import line from MainApplication.java:
`import com.facebook.react.BuildConfig`

Just delete or comment it out and give it a try. The problem in my case was that it had never returned properly...

**Comment by mrigo** [comment]
Yeah that was the problem! Removing it solved the issue! Thanks!
