### ISSUE TITLE
why after running react-native run, say me "Unable to resolve module

### ISSUE THREAD

**Issue by mohammad-khosrojerdi** [facebook/react-native#26410]
hi, i have a monorepo project with lerna and i have app, web and common packages in monorepo folder. my app package is react-native project and my web package is react-native-web project. i add common dependency in web and app package from lerna add command. the result of my web project is fine but when i run app project, alert me "Unable to resolve module". while i find the common folder in node_modules folder in app package root. why react-native not found my common dependency?

![Screenshot from 2019-09-12 08-43-26](https://user-images.githubusercontent.com/10862208/64758186-2913c080-d549-11e9-9318-1a5631c8d377.png)

![Screenshot from 2019-09-12 08-49-19](https://user-images.githubusercontent.com/10862208/64758201-33ce5580-d549-11e9-8e1d-a1846cbebcae.png)

**Comment by zzAlexzz** [comment]
I have the same issue.
e.g. , in my `mobile` project, it install `flag` npm(https://www.npmjs.com/package/flag), but when I run `react-native ios`, the error occurred: `Unable to resolve module`. same as mohammad's screen shot. Is it related to lerna or react-native issue?
