### ISSUE TITLE
'React/UIView+React.h' file not found after upgrade to RN 0.60.5

### ISSUE THREAD

**Issue by YahiaYasLife** [facebook/react-native#26428]
I upgraded my project from RN  0.59.10 to 0.60.5 but when I run the project I receive this error.
I followed the change steps from https://react-native-community.github.io/upgrade-helper/?from=0.59.10&to=0.60.5
and of course, I installed the new pods

React Native version: 0.60.5

System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-4288U CPU @ 2.60GHz
    Memory: 357.99 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.9.1 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.10.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 23.0.1, 26.0.2, 27.0.3, 28.0.2, 28.0.3
      System Images: android-28 | Android TV Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64
  IDEs:
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7

![Screen Shot 2019-09-13 at 17 33 03](https://user-images.githubusercontent.com/46672998/64875086-9eb48500-d64c-11e9-8cb4-e3de875a50cd.png)

**Comment by RichardLindhout** [comment]
Did you convert your code to cocoapods? If so, did you do a pod install in the iOS directory?

**Comment by YahiaYasLife** [comment]
@RichardLindhout 
yes I updated my project to cocoapods and I installed the pod dependency with `pod install`

**Comment by kumbhar-ketan** [comment]
@YahiaYasLife How you solved this issue ?

**Comment by YahiaYasLife** [comment]
@RichardLindhout @kumbhar-ketan 
I resolved the issue by removing all libraries from `Libraries` folder.
And installing the dependency @react-native-community/art
`yarn add @react-native-community/art`
 `cd ios && pod install`

**Comment by MayoudP** [comment]
It didn't worked for me :/ I tried both like you said, or by adding directly `  pod 'React-ART', :path => '../node_modules/react-native/Libraries/ART'` inside my podfile, but none of them worked, and still getting this error. 
<img width="379" alt="Capture d’écran 2020-03-02 à 19 35 08" src="https://user-images.githubusercontent.com/48682041/75706113-f4452280-5cbc-11ea-9ad5-4bac14dc627f.png">

any ideas why ?

**Comment by YahiaJabeur** [comment]
@MayoudP 
Did you remove all libraries from ios Libraries folder?
Did you unlink all dependencies?
when you install `yarn add @react-native-community/art` you don't need to link it manually.

**Comment by MayoudP** [comment]
I basically deleted the folder `LIbrairies`, concerning the unlink, should I remove all the item in `Link Binary with Libraries` and keep none ? cc @YahiaJabeur

**Comment by YahiaJabeur** [comment]
@MayoudP 
As far as I remember, I unlinked all libraries with the command `react-native unlink` if it's not working try to unlink manually.
Then I removed all libraries but I kept the folder `Libraries` exist in the ios project

**Comment by MayoudP** [comment]
@YahiaJabeur Thanks it indeed worked, stuck now with another error which I already got in react-native 0.59.X and again in 0.60 (but the fixe I had before is not working anymore). The error is about this : 
`Unable to resolve module ./DeprecatedColorPropType from .../react-native/Libraries/Components/View/ViewStylePropTypes.js`
Since it's not concering this issue, I'm gonna investigate on it somewhere else (but if you know an existing issue which fixing it in 0.60, I'd be glad to have the redirection #) !
