### ISSUE TITLE
[Android] App doesn't open when downloaded from Play Store if Hermes is enabled, Works Fine in Local Testing

### ISSUE THREAD

**Issue by IAmMarcellus** [facebook/react-native#26424]
Since first publishing to the Play Store, I tried to update to 60.5 but had some troubles so I created a new project and copied over the necessary files (including the entire android folder). I also added react-native-fbsdk, and released the update to the store.  However, the updated app doesn't work when downloaded from the play store (although it works fine when run from my computer in both debug and release modes). The app doesn't open (not even the splash screen) and if I keep trying to open it, I get a message saying that the app keeps crashing.
 
I thought the problem might be related to keyhashes and fbsdk as mentioned here: https://stackoverflow.com/questions/56765235/facebook-login-doesnt-work-if-app-is-downloaded-from-google-play (although I'm not using facebook login).  But even after removing react-native-fbsdk and cleaning all the caches, the problem still happens.

Any idea what the issue might be or even how I might go about further troubleshooting the problem? I didn't retain the initial release in the play console either so the only versions of the app I have right now are all broken! Please help!

React Native version: 0.60.5
## React Native Info:
System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Memory: 202.52 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.8.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.10.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 25, 26, 27, 28, 29
      Build Tools: 27.0.3, 28.0.3, 29.0.0, 29.0.1, 29.0.2
      System Images: android-25 | Android TV Intel x86 Atom, android-25 | China version of Android Wear ARM EABI v7a, android-25 | China version of Android Wear Intel x86 Atom, android-25 | Android Wear ARM EABI v7a, android-25 | Android Wear Intel x86 Atom, android-25 | Intel x86 Atom, android-25 | Intel x86 Atom_64, android-25 | Google APIs ARM 64 v8a, android-25 | Google APIs ARM EABI v7a, android-25 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom_64, android-25 | Google Play Intel x86 Atom, android-27 | Intel x86 Atom, android-27 | Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64
      Android NDK: 20.0.5594570
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
 
Also, I don't know if this is related to the problem, but I am splitting the builds for separate architectures.

## Steps To Reproduce
N/A

Describe what you expected to happen:
The app to perform the same when downloaded from the play store as it does when installed from my computer.

Snack, code example, screenshot, or link to a repository:
N/A

**Comment by IAmMarcellus** [comment]
15 updates later and I can finally say that I've found the source of the problem: Hermes. I disabled that and now the app opens if it's downloaded from the Play Store. However, I don't think I should close this issue, since the bug does exist and disabling Hermes is really just a workaround. It would be nice to be able to use Hermes to make the build smaller.

**Comment by roots-ai** [comment]
Any updates here?

**Comment by IAmMarcellus** [comment]
@roots-ai Not that I've heard. I turned off Hermes so everything's working fine now, but I never found a workaround that keeps Hermes working. Not sure if its been fixed in newer versions of RN.

**Comment by roots-ai** [comment]
@IAmMarcellus I could make it work with Hermes. There were several issues that I had to go through. But it is worth the effort if your app is large. It's a huge performance booster.
