### ISSUE TITLE
react-native init template.config?

### ISSUE THREAD

**Issue by imgregduh** [facebook/react-native#26443]
React Native version:
```
System:
    OS: Windows 10
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
    Memory: 16.77 GB / 31.93 GB
  Binaries:
    Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
```

## Steps To Reproduce

1.`npm i -g react-native`
2.`react-native init MyApp`

Describe what you expected to happen:
Tried to `init` with `react-native` globally installed.  It seems to be attempting to download the template and attempting to copy it from my temp directory even though I see that file sitting in the global `node_modules/react-native` directory.  I am using `nvm` to manage my node versions if that matters.  I have used powershell, gitbash, and cmd all result the same with even with run as admin.  I tried using `npx` but that resulted also in the same way 

```
? Directory "MyApp" already exists, do you want to replace it? (y/N) y
? Directory "MyApp" already exists, do you want to replace it? Yes
- Downloading template
√ Downloading template
- Copying template
× Copying template
error Error: Cannot find module 'C:\Users\Greg\AppData\Local\Temp\rncli-init-template-aaH8ON\node_modules\react-native\template.config'
```
```
$ npm list -g --depth=0
C:\Program Files\nodejs
+-- npm@6.9.0
+-- UNMET PEER DEPENDENCY react@16.8.6
`-- react-native@0.60.5

npm ERR! peer dep missing: react@16.8.6, required by react-native@0.60.5
```

I did google around and found other post about using `--template` and using the `@next` but still similar problems.  Though I was not interested in using typescript so that wouldnt have been ideal.

**Comment by radko93** [comment]
Globally installed `react-native-cli` is no longer supported. If you want to use your template you have to create a` template.config`, please read more here and open an issue in the CLI repo if you have questions https://github.com/react-native-community/cli/blob/master/docs/init.md#creating-custom-template
