### ISSUE TITLE
Question: Jest issue since upgrading from RN59 to RN61.rc3

### ISSUE THREAD

**Issue by jrwpatterson** [facebook/react-native#26447]
anybody able to help me since upgrading to RN61 when I try to mock native modules in this way...

jest.mock('Alert', () => ({
alert: jest.fn()
}))

it just tells me

Cannot find module 'Alert' from '.tsx'

I haven't changed the code...

**Comment by ide** [comment]
You need to mock the JS module -- either a file or a package, but not a native module. Ex: you could mock the package: `jest.mock('react-native', ...)`.
