### ISSUE TITLE
Question: could not determine the dependencies of task ':app:mergeDebugAssets.'

### ISSUE THREAD

**Issue by Pavelbure34** [facebook/react-native#26449]
![issue](https://user-images.githubusercontent.com/44696888/64933298-9d34b980-d812-11e9-9311-3e5b346b4b06.png)
![system](https://user-images.githubusercontent.com/44696888/64933303-a0c84080-d812-11e9-92c4-3e9ef0275e16.png)
![version](https://user-images.githubusercontent.com/44696888/64933308-a1f96d80-d812-11e9-8e94-6832e040afca.png)

![buildGradle](https://user-images.githubusercontent.com/44696888/64933401-221fd300-d813-11e9-8abe-64619ab4dd9f.png)
![gradleWrapper](https://user-images.githubusercontent.com/44696888/64933402-23e99680-d813-11e9-9ca2-cc517d9d273b.png)

I have been trying to run this application in android environment and keep getting this issue. Please help. This application was originally made for iOS and I am trying to optimize it for Android also.

**Comment by ayushpuri13** [comment]
Hey did you got any solution?
