### ISSUE TITLE
Unable to resolve module “react-transform-hmr/lib/index.js” #26440

### ISSUE THREAD

**Issue by jhizzle84** [facebook/react-native#26441]
When trying to launch a project, the project crashes with a 500 from the dev server citing 
`Unable to resolve module ./../../../../../usr/lib/node-modules/react-native/node-modules/react-transform-hmr/lib/index.js`

React Native version:
.0.60.5

## Steps To Reproduce

1. yarn install
2. react-native run-android

Android Sdk 28, node 10.16.3 on Kubuntu 19.04

Describe what you expected to happen:
successful load

Snack, code example, screenshot, or link to a repository:

https://github.com/jhizzle84/wallet

**Comment by arnnis** [comment]
starting the packager with `yarn start` or `npx react-native start` worked for me.

**Comment by jhizzle84** [comment]
Seems to have gotten me closer, thanks.

**Comment by jhizzle84** [comment]
> starting the packager with `yarn start` or `npx react-native start` worked for me.

Seems to have gotten me closer, thanks.
