### ISSUE TITLE
React-native using socket setState not working

### ISSUE THREAD

**Issue by shikhars371** [facebook/react-native#26456]
Hello Sir, i am using a socket URL to get real-time data and i am trying to set it in the state , as data comes very swiftly from socket URL , react-native throws error while setting state using setState to rerender the compoenet, it throws setstate is not defined please help me out as i have to show updated data frequesntly as the socket response

**Comment by ycai2** [comment]
@shikhars371 can you include a code sample or snippet? It'd be hard to tell if there's no code.

**Comment by radko93** [comment]
Please ask this on StackOverflow, I don't think this is a bug within React Native.
