### ISSUE TITLE
Websocket throws Error writing to stream error on iOS platform

### ISSUE THREAD

**Issue by ashokadichill** [facebook/react-native#26450]
Websocket throws Error writing to stream error on iOS platform

React Native version:

```
React Native Environment Info:
    Fetching system and libraries information...
System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Memory: 26.56 MB / 4.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    npm: 6.9.0 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 10.1/10B61 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

## Steps To Reproduce

1. create a web socket connection in react-native using new WebSocket()
2.once the web socket trying to connect to the server it will Throws the error

Describe what you expected to happen:

Expecting the socket to communicate the server and wait for the server response.
Added AppTransportSecurity still gets me error

Snack, code example, screenshot, or link to a repository:
[https://snack.expo.io/r14899hLS]()

**Comment by ashokadichill** [comment]
React native version:

```
info Fetching system and libraries information...
System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Memory: 26.56 MB / 4.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    npm: 6.9.0 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 10.1/10B61 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

**Logs**
2019-09-16 13:18:58.050064+0530 NewApp[11722:149060]SocketStream write error [0x0]: 1 9
2019-09-16 13:18:58.052 [info][tid:com.facebook.react.JavaScript] Error writing to stream
2019-09-16 13:18:58.051788+0530 NewApp[11722:149040] Error writing to stream

Upgraded to latest version of react-native still the error occurred in ios.

Source Code:

```
componentDidMount() {
    //websocket
    var ws = new WebSocket('ws:3.8.35.116:8002/api/socket');
    ws.onopen = () => {
      // connection opened
      ws.send('something'); // send a message
    };
    ws.onmessage = (e) => {
      // a message was received
      console.log(e.data);
    };
    ws.onerror = (e) => {
      // an error occurred
      console.log(e.message);
    };
    ws.onclose = (e) => {
      // connection closed
      console.log(e.code, e.reason);
    };
  }
```

**Comment by aleftenorio** [comment]
Hello people,

I have exactly the same error, any possible solution ???

"react-native": "0.58.5"

Thank you very much

**Comment by shiftrtech** [comment]
anyone have news with this?

**Comment by shiftrtech** [comment]
After testing for a while, i found the error, when i try to set the URL for socket connection i did (like yours) something like this:

`new WebSocket('ws:sandbox.example.com:8080');`

when a change it to:

`new WebSocket('ws://sandbox.example.com:8080');` it works on android and ios.

Don't know why on android doesnt fail.
