### ISSUE TITLE
Unable to install app on android emulator using MAC

### ISSUE THREAD

**Issue by AbhishekChourasia16690** [facebook/react-native#26468]
Hello Team,

Kindly find below my MAC configuration:
    OS: macOS 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 6.29 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1

Once I run the command react native run-android I get the error attached in the screenshot.
 
<img width="1679" alt="Screenshot 2019-09-17 at 9 58 06 AM" src="https://user-images.githubusercontent.com/22599405/65011600-b1230d00-d931-11e9-9ee4-b3592f0cdf3c.png">

After running the above command I expect the android emulator to start and the android app should launch and start executing code.

I need to resolve this issue asap.

Waiting for your reply.

Thanks.

**Comment by AbhishekChourasia16690** [comment]
Hello Team,

Please elaborate what else data you need to provide me exact and working solution.

Waiting for your reply.

Thanks.

**Comment by radko93** [comment]
This is not related to react native, please search for your error https://stackoverflow.com/questions/38096225/automatically-accept-all-sdk-licences

**Comment by AbhishekChourasia16690** [comment]
Hello,

I tried that issue but it didn't work.

Waiting for your response.

Thanks & Regards,
Abhishek

**Comment by radko93** [comment]
Please try running using Android Studio then.
