### ISSUE TITLE
Another react-native link doesn't work

### ISSUE THREAD

**Issue by Hypothesis-github** [facebook/react-native#26465]
React Native version:   0.59.10

## Steps To Reproduce

1. react-native link dependency
2. press enter ?

Describe what you expected to happen:

I expect this little piece of code to run

```
import React, { Component } from 'react';
import Video from 'react-native-video';
import light from './assets/1.mp4'

class App extends Component {
  videoPlayer;


  render() {
    return (
      <View style={styles.container}>
        <Video source={light}
          ref={(ref) => {
            this.player = ref
          }}
          style={styles.backgroundVideo} />
      </View>
```

On pressing react-native link react-native-video nothing happens. No linking is done and I get this error 

```
TypeError: Object(...) is not a function
Module.../../../../../../../../../Documents/Englishvid/node_modules/react-native-video/Video.js
C:/Users/shaha/Documents/Englishvid/node_modules/react-native-video/Video.js:475
  472 |   ...ViewPropTypes,
  473 | };
  474 | 
> 475 | const RCTVideo = requireNativeComponent('RCTVideo', Video, {
  476 |   nativeOnly: {
  477 |     src: true,
  478 |     seek: true,
```

What I am not looking forward to

1- This is not a bug
2- This issue is already solved here ####

This issue is not solved and the cli is created to link and it does not do so.

**Comment by radko93** [comment]
You did not even shared what version of RN do you use. Please use template when opening issues.

**Comment by Hypothesis-github** [comment]
> You did not even shared what version of RN do you use. Please use template when opening issues.

As if it makes a difference. this issue has been going on for 2 years now and as far as I am concerned nothing has been done.

**Comment by radko93** [comment]
Yes, it makes a difference, because in the latest RN there is no linking anymore, modules are autolinked. If you have an issue with react-native-video open an issue there.
