### ISSUE TITLE
There are no Libraries linked in iOS project of react-native

### ISSUE THREAD

**Issue by sourish** [facebook/react-native#26478]
I have tried to create a new project in react-native, After creating when I have opened the iOS project, in libraries folder I could not any libraries and I am not able to run the iOS Project. I have tried react-native run-ios Got error like "error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening AppName.xcodeproj."

react-native info logs
System:
    OS: macOS 10.14.5
  Binaries:
    Node: 11.3.0 - /usr/local/bin/node
    Yarn: 1.5.1 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1

## Steps To Reproduce

1. react-native init AppName
2. cd AppName
3. Open .xcodeproj & In Libraries there are no libraries found. I have tried to create multiple projects, but still no luck of getting libraries

![No Libraries Found](https://user-images.githubusercontent.com/1575118/65095327-4bd92580-d9de-11e9-907e-d778084934cc.png)

**Comment by samjt** [comment]
My guess is that you need to install cocoapods:
Do `gem install cocoapods` in terminal, followed by `cd ios && pod install` in your project folder.

**Comment by sourish** [comment]
@samjt : Yeah you are right, After I have done those, it worked out.
