### ISSUE TITLE
App crashes on start while building for 'x86_64' & 'arm64-v8a'

### ISSUE THREAD

**Issue by nakraniprakash** [facebook/react-native#26472]
**My app crashes immediately after the start when I am trying to build it for 64-bit support**

React Native version:
react-native-cli: 2.0.1
react-native: 0.57.8

React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
      Memory: 7.33 GB / 15.88 GB
    Binaries:
      Yarn: 1.17.3 - C:\Users\Admin\AppData\Roaming\npm\yarn.CMD
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5056338

## Steps To Reproduce

In your app/build.gradle make the following changes
        ndk {
            abiFilters "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
        }

       abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
        }

        def versionCodes = ["armeabi-v7a":1, "x86":2, "arm64-v8a": 3, "x86_64": 4]

2. Run with `react-native run-android` on a physical device. 

App is crashing at start

**Comment by radko93** [comment]
React Native 0.59 or higher is required to use 64bit support. Please update first.

**Comment by CodingApp** [comment]
@radko93  I'm using react native 0.59.10 and i got this issue too i need to upload the apk or aab file to google play but once i do so on some devices it work and on some it crashes on start.

**Comment by waqaramjad** [comment]
same issue here any update ?
