### ISSUE TITLE
Android dependency 'com.google.android.gms:play-services-stats' has different version for the compile (16.0.1) and runtime (17.0.0) classpath. You should manually set the same version via DependencyResolution

### ISSUE THREAD

**Issue by bashirpour** [facebook/react-native#26475]
React Native version: 0.55.3

	Environment:
	  OS: Windows 10
	  Node: 10.16.0
	  Yarn: 1.9.4
	  npm: 6.9.0
	  Watchman: Not Found
	  Xcode: N/A
	  Android Studio: Version  3.1.0.0 AI-173.4819257

	Packages: (wanted => installed)
	  react: 16.3.1 => 16.3.1
	  react-native: 0.55.3 => 0.55.3

## Steps To Reproduce

When run my app with this command `cd android && gradlew cleanBuildCache && gradlew clean && cd ../ && react-native run-android` i get this error:

> Android dependency 'com.google.android.gms:play-services-stats' has different version for the compile (16.0.1) and runtime (17.0.0) classpath. You should manually set the same version via DependencyResolution

### `android/build.gradle`

    // Top-level build file where you can add configuration options common to all sub-projects/modules.
    
    buildscript {
        ext {
            buildToolsVersion = '27.0.3'
            minSdkVersion = 16
            compileSdkVersion = 27
            targetSdkVersion = 27
            supportLibVersion = "27.1.1"
            playServicesVersion = "16.0.0"
        }
        repositories {
            google()
            jcenter()
        }
        dependencies {
            classpath 'com.android.tools.build:gradle:3.0.1'
    
            classpath 'com.google.gms:google-services:4.2.0' // google-services plugin
    
        }
    }
    
    allprojects {
        repositories {
            mavenLocal()
            maven {
                url "https://maven.google.com"
            }
            jcenter()
            maven {
                // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
                url "$rootDir/../node_modules/react-native/android"
            }
            google() // Google's Maven repository
        }
    }

### `android/app/build.gradle`

    buildscript {
        repositories {
            maven { url 'https://plugins.gradle.org/m2/' } // Gradle Plugin Portal
        }
        dependencies {
            classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.10.0, 0.99.99]'
        }
    }

    apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'

    apply plugin: "com.android.application"

    import com.android.build.OutputFile

    /**
     * The react.gradle file registers a task for each build variant (e.g. bundleDebugJsAndAssets
     * and bundleReleaseJsAndAssets).
     * These basically call `react-native bundle` with the correct arguments during the Android build
     * cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
     * bundle directly from the development server. Below you can see all the possible configurations
     * and their defaults. If you decide to add a configuration block, make sure to add it before the
     * `apply from: "../../node_modules/react-native/react.gradle"` line.
     *
     * project.ext.react = [
     *   // the name of the generated asset file containing your JS bundle
     *   bundleAssetName: "index.android.bundle",
     *
     *   // the entry file for bundle generation
     *   entryFile: "index.android.js",
     *
     *   // whether to bundle JS and assets in debug mode
     *   bundleInDebug: false,
     *
     *   // whether to bundle JS and assets in release mode
     *   bundleInRelease: true,
     *
     *   // whether to bundle JS and assets in another build variant (if configured).
     *   // See http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants
     *   // The configuration property can be in the following formats
     *   //         'bundleIn${productFlavor}${buildType}'
     *   //         'bundleIn${buildType}'
     *   // bundleInFreeDebug: true,
     *   // bundleInPaidRelease: true,
     *   // bundleInBeta: true,
     *
     *   // whether to disable dev mode in custom build variants (by default only disabled in release)
     *   // for example: to disable dev mode in the staging build type (if configured)
     *   devDisabledInStaging: true,
     *   // The configuration property can be in the following formats
     *   //         'devDisabledIn${productFlavor}${buildType}'
     *   //         'devDisabledIn${buildType}'
     *
     *   // the root of your project, i.e. where "package.json" lives
     *   root: "../../",
     *
     *   // where to put the JS bundle asset in debug mode
     *   jsBundleDirDebug: "$buildDir/intermediates/assets/debug",
     *
     *   // where to put the JS bundle asset in release mode
     *   jsBundleDirRelease: "$buildDir/intermediates/assets/release",
     *
     *   // where to put drawable resources / React Native assets, e.g. the ones you use via
     *   // require('./image.png')), in debug mode
     *   resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",
     *
     *   // where to put drawable resources / React Native assets, e.g. the ones you use via
     *   // require('./image.png')), in release mode
     *   resourcesDirRelease: "$buildDir/intermediates/res/merged/release",
     *
     *   // by default the gradle tasks are skipped if none of the JS files or assets change; this means
     *   // that we don't look at files in android/ or ios/ to determine whether the tasks are up to
     *   // date; if you have any other folders that you want to ignore for performance reasons (gradle
     *   // indexes the entire tree), add them here. Alternatively, if you have JS files in android/
     *   // for example, you might want to remove it from here.
     *   inputExcludes: ["android/**", "ios/**"],
     *
     *   // override which node gets called and with what additional arguments
     *   nodeExecutableAndArgs: ["node"],
     *
     *   // supply additional arguments to the packager
     *   extraPackagerArgs: []
     * ]
     */

    project.ext.react = [
        entryFile: "index.js"
    ]

    apply from: "../../node_modules/react-native/react.gradle"

    /**
     * Set this to true to create two separate APKs instead of one:
     *   - An APK that only works on ARM devices
     *   - An APK that only works on x86 devices
     * The advantage is the size of the APK is reduced by about 4MB.
     * Upload all the APKs to the Play Store and people will download
     * the correct one based on the CPU architecture of their device.
     */
    def enableSeparateBuildPerCPUArchitecture = false

    /**
     * Run Proguard to shrink the Java bytecode in release builds.
     */
    def enableProguardInReleaseBuilds = false

    android {
        compileSdkVersion rootProject.ext.compileSdkVersion
        buildToolsVersion rootProject.ext.buildToolsVersion

        defaultConfig {
            applicationId "com.deml.android"
            minSdkVersion rootProject.ext.minSdkVersion
            targetSdkVersion rootProject.ext.targetSdkVersion
            versionCode 24
            versionName "2.3"
            ndk {
                abiFilters "armeabi-v7a", "x86"
            }
        }
        signingConfigs {
            release {
                if (project.hasProperty('MYAPP_RELEASE_STORE_FILE')) {
                    storeFile file(MYAPP_RELEASE_STORE_FILE)
                    storePassword MYAPP_RELEASE_STORE_PASSWORD
                    keyAlias MYAPP_RELEASE_KEY_ALIAS
                    keyPassword MYAPP_RELEASE_KEY_PASSWORD
                }
            }
        }
        splits {
            abi {
                reset()
                enable enableSeparateBuildPerCPUArchitecture
                universalApk false  // If true, also generate a universal APK
                include "armeabi-v7a", "x86"
            }
        }
        buildTypes {
            debug {
                    manifestPlaceholders = [excludeSystemAlertWindowPermission: "false"]
             }
            release {
                manifestPlaceholders = [excludeSystemAlertWindowPermission: "true"]
                minifyEnabled enableProguardInReleaseBuilds
                proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"

     signingConfig signingConfigs.release

            }
        }
        // applicationVariants are e.g. debug, release
        applicationVariants.all { variant ->
            variant.outputs.each { output ->
                // For each separate APK per architecture, set a unique version code as described here:
                // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
                def versionCodes = ["armeabi-v7a":1, "x86":2]
                def abi = output.getFilter(OutputFile.ABI)
                if (abi != null) {  // null for the universal-debug, universal-release variants
                    output.versionCodeOverride =
                            versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
                }
            }
        }
    }

    dependencies {
        implementation project(':react-native-google-analytics-bridge')
        implementation(project(':react-native-maps')){
             exclude group: 'com.google.android.gms', module: 'play-services-base'
             exclude group: 'com.google.android.gms', module: 'play-services-maps'
         }
         implementation 'com.google.android.gms:play-services-base:10.0.1'
         implementation 'com.google.android.gms:play-services-maps:10.0.1'

        implementation project(':react-native-fcm')

        implementation "com.google.android.gms:play-services-gcm:16.0.0"

        implementation fileTree(dir: "libs", include: ["*.jar"])

        implementation "com.android.support:appcompat-v7:27.0.1"
        implementation "com.facebook.react:react-native:+"  // From node_modules

        implementation 'com.facebook.fresco:fresco:1.9.0'

        // For animated GIF support
        implementation 'com.facebook.fresco:animated-gif:1.9.0'

        // For WebP support, including animated WebP
        implementation 'com.facebook.fresco:animated-webp:1.9.0'
        implementation 'com.facebook.fresco:webpsupport:1.9.0'

        implementation project(':react-native-svg')

        // Automatically selecting the latest available version
        implementation 'com.google.firebase:firebase-core:16.0.8'
        implementation 'com.google.firebase:firebase-messaging:17.6.0'
    }

    // Run this once to be able to run the application with BUCK
    // puts all compile dependencies into folder libs for BUCK to use
    task copyDownloadableDepsToLibs(type: Copy) {
        from configurations.compile
        into 'libs'
    }

    apply plugin: 'com.google.gms.google-services'

### `android/gradle.properties`

    # Project-wide Gradle settings.
    
    # IDE (e.g. Android Studio) users:
    # Gradle settings configured through the IDE *will override*
    # any settings specified in this file.
    
    # For more details on how to configure your build environment visit
    # http://www.gradle.org/docs/current/userguide/build_environment.html
    
    # Specifies the JVM arguments used for the daemon process.
    # The setting is particularly useful for tweaking memory settings.
    # Default value: -Xmx10248m -XX:MaxPermSize=256m
    # org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
    
    # When configured, Gradle will run in incubating parallel mode.
    # This option should only be used with decoupled projects. More details, visit
    # http://www.gradle.org/docs/current/userguide/multi_project_builds.html#sec:decoupled_projects
    # org.gradle.parallel=true
    
    android.useDeprecatedNdk=true
    android.enableAapt2=false
    
    firebaseCoreVersion=16.0.8
    firebaseMessagingVersion=17.6.0

**Comment by bashirpour** [comment]
The upgrade to latest release is currently not possible for me.
Please remove the "Resolution: Old Version" label. @react-native-bot

**Comment by jerameel** [comment]
Try something like
```
implementation(project(":react-native-google-analytics-bridge`"),  {
  exclude group: "com.google.android.gms"
})
implementation "com.google.android.gms:play-services-analytics:16.0.0"
```

**Comment by bashirpour** [comment]
@jerameel Thank you very much.
This problem was solved but then I got into another problem.

>Execution failed for task ':app:transformDexArchiveWithDexMergerForDebug'.
>com.android.build.api.transform.TransformException: com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/internal/measurement/zzbp;
