### ISSUE TITLE
0.61-rc3 Background image override the View color

### ISSUE THREAD

**Issue by Trobyss** [facebook/react-native#26485]
Hi !

I just upgrade to ReactNative 0.61-rc3 and i would like to report an issue about background and position absolute:

![Screenshot_1568795935](https://user-images.githubusercontent.com/43353685/65132239-ec404180-da00-11e9-9503-6d685ad68fa7.png)

The component appear correctly but the background color doesn't follow the properties of z-index (maybe ?).

```tsx
const Component: React:FC<{}> = props => (
  <SafeArea>
    <BackgroundImage source={greenImage} />
    <FrontComponent />
  </SafeArea>
)

const BackgroundImage = styled.Image`
  width: 100%;
  position: absolute;
  top: 0;
  right: 0;
  left: 0;
`
const FrontComponent = styled.View`
  background-color: white;
`
```

Any idea ?

React Native version: 
`
System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 40.20 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.3 - /usr/local/opt/node@10/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/opt/node@10/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 28
      Build Tools: 28.0.3, 29.0.2
      System Images: android-26 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.0-rc.3 => 0.61.0-rc.3 
  npmGlobalPackages:
    react-native-cli: 2.0.1
`
Trobyss'

**Comment by pontusab** [comment]
Notice the same issue with elements using `position: absolute`

**Comment by victorhermes** [comment]
I'd like your code link to review it, please.

**Comment by Trobyss** [comment]
Hello  !
The problem come from styled-component package. I link you the issue on the styled repo :)
https://github.com/styled-components/styled-components/issues/2759

Trobyss

**Comment by B27** [comment]
this looks like bug with 'absolute' position
