### ISSUE TITLE
Receive binary data over WebSocket (RN 0.60.5)

### ISSUE THREAD

**Issue by RobinBobin** [facebook/react-native#26488]
React Native version:

System:
    OS: Linux 4.18 Ubuntu 18.10 (Cosmic Cuttlefish)
    CPU: (4) x64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
    Memory: 536.00 MB / 5.72 GB
    Shell: 4.4.19 - /bin/bash
  Binaries:
    Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
    npm: 6.10.2 - ~/.nvm/versions/node/v10.15.0/bin/npm
  SDKs:
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 23.0.1, 23.0.3, 25.0.0, 26.0.1, 27.0.3, 28.0.3, 29.0.2
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1

## Steps To Reproduce

1. Connect to a websocket server from an RN app.
2. Send binary data from the server to the app.

Describe what you expected to happen:
WebSocket `onmessage` being called with an instance of `ArrayBuffer` containing the data from the server.

In fact an empty `ArrayBuffer` is received. When the app sends binary data to the server, the data is transmitted just fine.

**Comment by bartolkaruza** [comment]
Hi there, thank you for reporting this! Could you help us out with a minimal reproducible demo app? It's time-consuming to try and reproduce your issue and I will probably not get it right for your specific case.

**Comment by RobinBobin** [comment]
Hello!

Thanks for answering. Shall I send a websocket server, or will an RN app suffice?


>Среда, 18 сентября 2019, 17:12 +03:00 от Bartol Karuza <notifications@github.com>:
>
>Hi there, thank you for reporting this! Could you help us out with a minimal reproducible demo app? It's time-consuming to try and reproduce your issue and I will probably not get it right for your specific case.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
� убен Шалимов
