### ISSUE TITLE
[iOS] Having gitignore set for ios/pods causes long build times

### ISSUE THREAD

**Issue by samjt** [facebook/react-native#26483]
With the new template settings adding `ios/pods` to `.gitignore` by default, cocoapods have to be installed every time our build chain runs.
For those without cocoapods installed, the build fails.
This step wasn't necessary pre-0.60

React Native version:
```
System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
    Memory: 41.03 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.14.2 - ~/.nvm/versions/node/v10.14.2/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.11.1 - ~/.nvm/versions/node/v10.14.2/bin/npm
    Watchman: 4.7.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 22, 23, 26, 27, 28
      Build Tools: 22.0.1, 23.0.1, 23.0.3, 26.0.0, 26.0.1
      System Images: android-23 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.2 AI-181.5540.7.32.5056338
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: ^16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-create-library: 3.1.2
    react-native-git-upgrade: 0.2.7
    react-native-rename: 2.2.2
```

## Steps To Reproduce

1. Create react-native project using ^0.60.5
2. Commit to Git
3. Check out to a different machine, run `npm install`
4. Build fails with missing support files
5. Run `cd ios && pod install`
6. Build succeeds 

```
ios/Pods/Target Support Files/boost-for-react-native/boost-for-react-native.xcconfig: unable to open file (in target "boost-for-react-native" in project "Pods") (in target 'boost-for-react-native')
...
```

Describe what you expected to happen:
It's common practice for Pods to be committed to git, allowing a build to happen without needing cocoapods installed or the reinstallation of pods.

https://guides.cocoapods.org/using/using-cocoapods.html#should-i-check-the-pods-directory-into-source-control

Currently reinstalling pods on every build means downloading appx. 1Gb of files for every build run, followed by resolving deltas, performing a checkout etc. 
This adds appx. 10 min to every build.

If this is to do with updating React Native itself, would using e.g. `pod update React-Core` be more efficient?

**Comment by vonovak** [comment]
Having / not having pods in repo this is up to consumers to decide, no one is keeping you from committing the pods directory. 

> Currently reinstalling pods on every build means ... This adds appx. 10 min to every build.

is this a difference between having pods in gitignore and not having them there? Or is this difference between pre-0.60 and 0.60 build times?

**Comment by samjt** [comment]
The difference is in having pods in gitignore or not, which I'm happy to change, but I'm curious as to why it's set to be ignored in the first place?
