### ISSUE TITLE
Hot reloading not working with components as functions

### ISSUE THREAD

**Issue by gbbarroso** [facebook/react-native#26498]
I just started a new project and it seems hot reload doesn't work when using components as functions, however it works when changing it to a class that extends `React.Component`

React Native version: 0.60.5

info Fetching system and libraries information...
System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
    Memory: 7.19 GB / 15.88 GB
  Binaries:
    Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    Android Studio: Version  3.3.0.0 AI-182.5107.16.33.5314842

## Steps To Reproduce

1. react-native init myproj
2. cd ./myproj
3. react-native run-android
4. Enable hot reload on app
5. Change some `Text` on `App.js` and save it
6. Hot reload's tooltip shows up, but no changes are applied
7. Refactor `App` function into a class that extends from `React.component` and move into a `render()` method.
8. Hot reloading is now working.

Describe what you expected to happen:
From what I understand it should work for functions components as well, I was reading into react hooks documentations and it even said it would make things easier for hot reloading.

Snack, code example, screenshot, or link to a repository:

**Comment by ghondar** [comment]
@gbbarroso in version 0.61-rc3 it already works correctly, but react-native-gesture-handler stops working, in case you are using it

**Comment by QutfulloOchilov** [comment]
I have also the same problem

**Comment by B27** [comment]
> @gbbarroso in version 0.61-rc3 it already works correctly, but react-native-gesture-handler stops working, in case you are using it

next release/rc will have fix to react-native-gesture-handler https://github.com/react-native-community/releases/issues/140#issuecomment-532819601 
>> "A temporary workaround for the problem is to use gestureHandlerRootHOC to wrap top level component of your RN app."

**Comment by TheSavior** [comment]
Closing as this is fixed with fast refresh in 0.61 RC
