### ISSUE TITLE
React Native version mismatch

### ISSUE THREAD

**Issue by Akeysa** [facebook/react-native#26502]
I just updated react-native-svg and now I got this error after starting expo: 

„React Native version mismatch.

JavaScript: 0.60.5
Native: 0.59.8“

My React Native Version is 0.60.5 and I already tried to reinstall React Native and the SVG and also updated npm.
I cleared the chaches and after that I closed all terminals.

But nothing works.

If I downgrade my React Native Version to a Version < 0.60.0 it works. But thats not what I want.

**Comment by vonovak** [comment]
The problem is that you did not rebuild the native (android / ios) project. After you rebuild, the problem will be gone.
