### ISSUE TITLE
 iOS App Crashes in Launch screen on device with Namespace SPRINGBOARD

### ISSUE THREAD

**Issue by sourish** [facebook/react-native#26500]
When I am running my React-native project on iPhone 6 device, The application is staying in the launch for a while(close to 20-30 secs) and then the app crashes . Does anybody know how to fix the crash.

React Native version:

System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz
    Memory: 634.68 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.6.0 - /usr/local/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.10.2 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    Android SDK:
      API Levels: 23, 26, 27, 28
      Build Tools: 23.0.1, 27.0.3, 28.0.3, 29.0.2
      System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 10.1/10B61 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5 
  npmGlobalPackages:
    create-react-native-app: 2.0.2
    react-native-cli: 2.0.1

## Steps To Reproduce

1. Opened the .xcodeproj from ios with Xcode 10.3 and ran
2. App stays in Launch screen
3. I have updated to latest Xcode 11 and yet the app got crashed

The Crash that I have got from crashlogs is 
Exception Type:  EXC_CRASH (SIGKILL)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: Namespace SPRINGBOARD, Code 0x8badf00d
Termination Description: SPRINGBOARD, scene-create watchdog transgression: com.buzzboard.buzzboardconnect exhausted real (wall clock) time allowance of 19.87 seconds | ProcessVisibility: Foreground | ProcessState: Running | WatchdogEvent: scene-create | WatchdogVisibility: Foreground | WatchdogCPUStatistics: ( | "Elapsed total CPU time (seconds): 21.260 (user 21.260, system 0.000), 53% CPU", | "Elapsed application CPU time (seconds): 0.153, 0% CPU" | )
Triggered by Thread:  0

Describe what you expected to happen:

How can I fix this issue and make app stable?

**Comment by sourish** [comment]
How to upgrade react-native version to the latest in the current project ?

**Comment by rmamtaventures** [comment]
Same issue on ios app at 0.60. Any uodate?

**Comment by rmamtaventures** [comment]
Getting this issue when upgrading app from app store.

**Comment by yastrebovb** [comment]
Sames issue in production while releasing new version of the app.

**Comment by mgcrea** [comment]
Encountering this today when attempting to run a clean project `npx react-native init SandboxProject --template react-native-template-typescript` on my device (iPhone 11 Pro Max running iOS 13.2.3)
