### ISSUE TITLE
Question: Keyboard dismisses instantly when I tap the textInput.

### ISSUE THREAD

**Issue by haolipang** [facebook/react-native#26518]
Why the keyboard always dismisses instantly when I tap  an textInput? The strange thing is this only happens on one particular page of my app. 
![untitled](https://user-images.githubusercontent.com/51696790/65335605-4b67a700-dbf7-11e9-936d-8e62bf63ea1f.gif)

This is the only code in the script, nothing seems wrong:
  <View>
            <TextInput
              style={{
                paddingVertical: 0,
                textAlignVertical: 'center',
                height: height * 0.05,
                width: width * 0.4,
                fontSize: height * 0.027,
                color: '#E1E1F2',
                borderBottomWidth: 1,
                borderBottomColor: '#6B778A',
                justifyContent: 'center',
              }}
              placeholderTextColor={'#6B778A'}
              underlineColorAndroid='black'/>
  </View>

Please send help

**Comment by 7ameed** [comment]
i'm facing the same issue

**Comment by codyi96** [comment]
Facing the same issue

**Comment by swapkids** [comment]
+1 here. please reopen
