### ISSUE TITLE
Examples/Movies/SearchBar.ios.js needs marginTop:64 while MovieScreen.js doesn't need.

### ISSUE THREAD

**Issue by iostalk** [facebook/react-native#2651]
In the Examples/Movies folder, SearchBar.ios.js(included in SearchScene.js) has a style below:

```js
var styles = StyleSheet.create({
  searchBar: {
    marginTop: 64,
```

I think `marginTop: 64` is used to avoid SearchBar being covered by the navigation bar, but I can not understand why the MovieScreen.js (the movie detail view) doesn't have similar code, which is pushed as the second view.
Someone who can explain this would be appreciated.

**Comment by brentvatne** [comment]
Hi @iostalk! This isn't an issue with React Native itself, so could you please repost this to StackOverflow? People there are strongly rewarded with *magical digital career reputation points* to encourage them to answer, here we just want to make React Native better ;)

**Comment by iostalk** [comment]
Okay,thank you!
