### ISSUE TITLE
Mapbox Store Locator zoom problem

### ISSUE THREAD

**Issue by reshiDeveloper** [facebook/react-native#26514]
Hi. 
When I upgrade react native to 0.60.5, I can not see all places in my app. I created map with mapbox and store locator kit. I reduced zoom level. But anthing didnot change, it is too much zoom.I can't see any place location from my current position.
 How can I see all places? 

This is StoreLocatorKit.Mapview:
  <StoreLocatorKit.MapView
            simulateUserLocation
            accessToken={MAPBOX_ACCESS_TOKEN}
            theme={this.state.activeTheme}
            centerCoordinate={this.state.initialLocation}
            featureCollection={places}
            zoomLevel={10}
            style={styles.matchParent} />

**Comment by dulmandakh** [comment]
Please file an issue to StoreLocatorKit
