### ISSUE TITLE
Question: UIWebView deprecated.

### ISSUE THREAD

**Issue by ZeroOnet** [facebook/react-native#26511]
ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

**Comment by koutily** [comment]
Even I am also getting the same issue. Does anyone know how to solve it

**Comment by koutily** [comment]
I didn't use  react native webview. But i am getting this error

**Comment by jhenrich** [comment]
Do you use Expo?

**Comment by minhnguyentps** [comment]
Yes, I am using the Expo and I have this issue. @jhenrich, Can you help me to explain this and how can I resolve this problem with Expo?

**Comment by hengkx** [comment]
Does anyone know how to solve it
