### ISSUE TITLE
gif not working on android, added android/app/build.gradle line to support gif

### ISSUE THREAD

**Issue by vivek25constants** [facebook/react-native#26515]
React Native version:

## Steps To Reproduce

1.
2.

Describe what you expected to happen:

Snack, code example, screenshot, or link to a repository:

**Comment by vivek25constants** [comment]
I solved it, I had to add the lines at the bottom of the pile of "implementation"'s in the gradle file

**Comment by diamont1001** [comment]
not work for me

**Comment by carl0804** [comment]
gif not work on Android

os: mac os 10.15.1
Android Studio: 3.5.1
gradle: 5.5

buildToolsVersion = "28.0.3"
minSdkVersion = 16
compileSdkVersion = 28
targetSdkVersion = 28

"react": "16.9.0",
"react-native": "0.61.4"

`dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.facebook.react:react-native:+"  // From node_modules
    // support gif
    implementation 'com.facebook.fresco:animated-gif:1.12.0'

    if (enableHermes) {
        def hermesPath = "../../node_modules/hermes-engine/android/";
        debugImplementation files(hermesPath + "hermes-debug.aar")
        releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
        implementation jscFlavor
    }
}`

**Comment by carl0804** [comment]
> gif not work on Android
> 
> os: mac os 10.15.1
> Android Studio: 3.5.1
> gradle: 5.5
> 
> buildToolsVersion = "28.0.3"
> minSdkVersion = 16
> compileSdkVersion = 28
> targetSdkVersion = 28
> 
> "react": "16.9.0",
> "react-native": "0.61.4"
> 
> `dependencies {
> implementation fileTree(dir: "libs", include: ["*.jar"])
> implementation "com.facebook.react:react-native:+" // From node_modules
> 
> ```
> **// support gif, already added this
> implementation 'com.facebook.fresco:animated-gif:1.12.0'**
> 
> if (enableHermes) {
>     def hermesPath = "../../node_modules/hermes-engine/android/";
>     debugImplementation files(hermesPath + "hermes-debug.aar")
>     releaseImplementation files(hermesPath + "hermes-release.aar")
> } else {
>     implementation jscFlavor
> }
> ```
> 
> }`

Problem sovled, use "implementation 'com.facebook.fresco:animated-gif:2.0.0'" instead of implementation 'com.facebook.fresco:animated-gif:1.12.0'

**Comment by allindeveloper** [comment]
I used
`implementation 'com.facebook.fresco:animated-gif:2.0.0'`
still not working
