### ISSUE TITLE
Question: Image from localhost URL not rendering

### ISSUE THREAD

**Issue by rosnaib11** [facebook/react-native#26516]
I'm trying to display my uploaded image saved from to my backend folder. Its on different file so to retrieve I have to call it `http://localhost:3333/api/userprofile/5/5.jpeg`. But it does not work on my react native code, I tested it on android and IOS

```
<Thumbnail
                  small
                  source={{
                    uri: `http://localhost:3333/userprofile/${this.props.user.id}/${
                      this.props.user.avatar
                    }`
                  }}
                />
```

it works when I open it on browser. It also work if I use different url like `https://picsum.photos/200/300` how to deal with this?

This is kinda similar to this question but don't have proper answer
#3496

**Comment by rosnaib11** [comment]
This is not Stackoverflow.

**Comment by Berser6523** [comment]
same problem here

**Comment by vinicius507** [comment]
Did you fix it?
