### ISSUE TITLE
contentContainerStyle: FlastList : contentContainerStyle

### ISSUE THREAD

**Issue by mehdiyaq** [facebook/react-native#26521]
contentContainerStyle works in FlastList but it is not mentioned in doc of FlastList section.

**Comment by ganes1410** [comment]
@mehdiyaq  In this section(https://facebook.github.io/react-native/docs/flatlist#props), it tells you that Flatlist props are inherited from ScrollView props. so `contentContainerStyle` is part of Scrollview property inherited by Flatlist.

Can you please close the issue if you don't have any more queries.
