### ISSUE TITLE
fetch res.json() SyntaxError: Unexpected token ﻿ in JSON at position 0

### ISSUE THREAD

**Issue by YanYuanFE** [facebook/react-native#26523]
React Native version: 0.60.5 and 0.59.3

## Steps To Reproduce

1. use fetch report error but worked on browser

Describe what you expected to happen:
res.json() work.
 
Snack, code example, screenshot, or link to a repository:

```
fetch('http://minisite.medtoday.com.cn/cycle/v-tipr-physician/getcolumnbycompanyid.php?company_id=1&parent_id=0').then(res => res.json())
    .then(res => {
      console.log(res);
    })
```

**Comment by YanYuanFE** [comment]
![image](https://user-images.githubusercontent.com/17774285/65370270-6e429b80-dc89-11e9-8540-4e4340cf4a05.png)

**Comment by YanYuanFE** [comment]
res.text() can work, but JSON.parse() for after res.text(), also not work.

**Comment by JKCooper2** [comment]
Have you confirmed the response status is 200? Try using the code from https://developers.google.com/web/updates/2015/03/introduction-to-fetch#fetch and see if that prints it out

**Comment by YanYuanFE** [comment]
response status is 200, but response header not status 200, is this reason?

**Comment by JKCooper2** [comment]
Not sure, however i believe its an issue with fetch you're having, not an issue with react-native

**Comment by ravirajn22** [comment]
This error is not related to fetch or react-native i think. Print the raw body text from the response and check if you can parse it to json in chrome dev tools. Most probably the issue is due to response body not in proper format to parse to json.

**Comment by reshiDeveloper** [comment]
firstly get data in json format and after get response.

look at below example:

function getMoviesFromApiAsync() {
  return fetch('https://facebook.github.io/react-native/movies.json')
    .then((response) => response.json())
    .then((responseJson) => {
      return responseJson.movies;
    })
    .catch((error) => {
      console.error(error);
    });
}
