### ISSUE TITLE
RTL is forced in android RTL devices

### ISSUE THREAD

**Issue by sm2017** [facebook/react-native#26522]
React Native version:

```
System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i3-8100 CPU @ 3.60GHz
    Memory: 3.80 GB / 11.85 GB
  Binaries:
    Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    Android Studio: Version  3.3.0.0 AI-182.5107.16.33.5314842
```

## Steps To Reproduce

I have same issue https://github.com/facebook/react-native/issues/10204

But my app has both RTL and LTR layout , my multilingual app currently works fine in LTR devices in both RTL and LTR forced layout and in RTL devices in forced RTL layout

But LTR forced is not working in  RTL devices

the solution described in https://github.com/facebook/react-native/issues/10204 is not dynamic , As I have multilingual app , I have to dynamically change layout

`I18nManager.forceRTL(false);` is not working in RTL devices

Describe what you expected to happen:
RTL forced layout must works in android RTL devices

**Comment by StasD** [comment]
You could try something like this:

`yarn add react-native-restart`, then

```
import RNRestart from 'react-native-restart';

  async componentDidMount() {
    // ... some preparation code here

    let is_rtl = !!locale['is_rtl'];

    if (I18nManager.isRTL !== is_rtl) {
      I18nManager.forceRTL(is_rtl);
      RNRestart.Restart();
    }

    SplashScreen.hide();
  }
```

Though, yeah, I would also prefer RN team made something to make it take effect without restart if that's at all possible...

**Comment by sm2017** [comment]
Before openning issue , I do exacly what you told

When you test in LTR devices everything is ok, when you test in RTL devices in RTL locale it is ok too

BUT When you test in RTL devices , in LTR locales ‌، `I18nManager.isRTL !== is_rtl` is always true and app repeatedly restarted 

Please do this to reproduce issue

1- change your phone's system language to a RTL language like arabic , farsi , ...
2- Run your app and change the app locale to LTR locale, like English
The app restarted repeatedly

**Comment by StasD** [comment]
Weird... I did not experience this... yet :) Maybe adding `I18nManager.allowRTL(is_rtl);` will help?
