### ISSUE TITLE
"iPhone X" simulator is disabled

### ISSUE THREAD

**Issue by Resten1497** [facebook/react-native#26529]
React Native version: 0.60.4

## Steps to reproduce

<img width="626" alt="스크린샷 2019-09-22 오후 10 17 33" src="https://user-images.githubusercontent.com/19689492/65388500-54877e00-dd87-11e9-9b41-a645a5aa5cbb.png">

The Xcode is updated version 11 and the "iPhone X" simulator is disabled and cannot be run with an existing "react-native run-ios".

**Comment by owlstack** [comment]
I have the same issue! Please fix!

**Comment by ScreamZ** [comment]
https://github.com/react-native-community/cli/issues/739#issuecomment-533885641

But still, this is not building… You can also add Iphone X back by managing device in Xcode

**Comment by jwaldrip** [comment]
Same issue, RN 0.59.10. The work around does not work.

**Comment by owlstack** [comment]
Go to node_modules>@react-native-community>cli>build>commands>runIOS>findMatchingSimulator.js

Change the 'YES' in this line to true: 

> if (simulator.availability !== '(available)' && simulator.isAvailable !== true) {
>         continue; 

This is how I got it working.

Thanks!

**Comment by craigotis** [comment]
The iPhone X simulator has been replaced in Xcode 11 with the newer iPhone 11. It seems React is hard-coded to look for iPhone X.

You can specify the newer simulator using:
```
react-native run-ios --simulator "iPhone 11"
```

**Comment by Resten1497** [comment]
I found another way.

open Xcode > Add Additional Simulators > Create a new Simulator > 
Device type > iPhone X > Create

Now you can run it without an "--simulator " option

**Comment by ganes1410** [comment]
@Resten1497 comment will work. For some reason, after the latest Xcode update, `iPhone X` was not present in the default list of simulators.

**Comment by cookiekitty** [comment]
Adding an iPhoneX simulator is not working for me, on 0.59.8. I have 4 simulators for iPhone X, with 12.0, 12.1, 12.2 and 13.0 iOS versions and am still getting the same error message. Is there a specific version of iOS simulator that I need to re-install?

**Comment by scalalang2** [comment]
I found that iPhone X is not installed in Xcode 11.

![스크린샷 2019-09-30 오후 6 17 31](https://user-images.githubusercontent.com/2603286/65865691-b1e68500-e3ae-11e9-9f1b-18fb70ec1a7e.png)

You can build the app with this command as below
`~$ react-native run-ios --simulator "iPhone 8"`
