### ISSUE TITLE
StoreLocatorKit.MapView zoom level not working

### ISSUE THREAD

**Issue by reshiDeveloper** [facebook/react-native#26534]
Hi. I use Mapbox and store locator kit.  I set zoom level to 1 or 3 or 15. But anything does not change.
How can I solve this problem?

 <StoreLocatorKit.MapView
            simulateUserLocation
            accessToken={MAPBOX_ACCESS_TOKEN}
            theme={this.state.activeTheme}
            centerCoordinate={this.state.initialLocation}
            featureCollection={places}
            zoomLevel={13}
            style={styles.matchParent} />

**Comment by dulmandakh** [comment]
Please file an issue to StoreLocatorKit
