### ISSUE TITLE
Problems when running on ios in RN 0.60.5

### ISSUE THREAD

**Issue by reshiDeveloper** [facebook/react-native#26539]
Hi
My react native project version is 0.60.5. When i run app on ios, give me errors.
I added libs to package.json and run npm install. My project runs on android, but doesnot on ios.  I did only pod install in cd ios. But anything didnt change
Please help me

**Comment by mrigo** [comment]
Hi @reshiDeveloper ,
can you bring some more informations?
Errors in ios, why the app doesn't run, if you're running from XCode or from terminal with "run ios" , the package.json file, ecc..
Thanks

**Comment by cortinico** [comment]
Closing as this issue is 3 years old, 0.60 is a really old RN version. Please open a separate issue if you still have this problem
