### ISSUE TITLE
Problem building on iOS - RN 0.60.5

### ISSUE THREAD

**Issue by gabrielklose** [facebook/react-native#26532]
Hey guys!
I have the following problem when trying to build my project:
![image](https://user-images.githubusercontent.com/26801238/65359628-80620280-dbd3-11e9-91f1-7f2e4d3c158c.png)

after some building, he doesn't build anymore.
There is no different code than when starting a project with "react-native init example". I just installed some packages.

I already deleted the node_modules, Podfile.lock, already ran pod install, update. It worked, but stopped out of the blue, without making any changes to the code.

sorry my english, I used the translator, lol.
Can someone help me?
ps: i’m using .xcworkspace.

React Native version:
System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz
    Memory: 5.61 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    npm: 6.10.2 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 28, 29
      Build Tools: 29.0.1
      System Images: android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1

package.json:
{
"name": "estudante",
"version": "0.0.1",
"private": true,
"scripts": {
"start": "react-native start",
"test": "jest",
"lint": "eslint ."
},
"dependencies": {
"apisauce": "^1.1.1",
"prop-types": "^15.7.2",
"react": "16.8.6",
"react-native": "0.60.5",
"react-native-agora": "^2.9.0-alpha.1",
"react-native-camera": "^3.4.0",
"react-native-elements": "^1.2.0",
"react-native-gesture-handler": "^1.4.1",
"react-native-image-crop-picker": "^0.25.2",
"react-native-image-picker": "^1.1.0",
"react-native-masked-text": "^1.13.0",
"react-native-material-textfield": "^0.12.0",
"react-native-modal": "^11.3.1",
"react-native-paper": "^2.16.0",
"react-native-reanimated": "^1.2.0",
"react-native-vector-icons": "^6.6.0",
"react-navigation": "^4.0.5",
"react-navigation-drawer": "^2.2.1",
"react-navigation-stack": "^1.8.0",
"react-navigation-tabs": "^2.5.3",
"react-redux": "^7.1.1",
"redux": "^4.0.4"
},
"devDependencies": {
"@babel/core": "7.6.0",
"@babel/runtime": "7.6.0",
"@react-native-community/eslint-config": "0.0.3",
"babel-jest": "24.9.0",
"eslint": "6.4.0",
"jest": "24.9.0",
"metro-react-native-babel-preset": "0.54.1",
"react-test-renderer": "16.8.6",
"redux-devtools": "^3.5.0"
},
"jest": {
"preset": "react-native"
}
}

Podfile:
platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'estudante' do
pod 'React', :path => '../node_modules/react-native/'
pod 'React-Core', :path => '../node_modules/react-native/React'
pod 'React-DevSupport', :path => '../node_modules/react-native/React'
pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
pod 'React-RCTWebSocket', :path => '../node_modules/react-native/Libraries/WebSocket'

pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

pod 'react-native-agora', :path => '../node_modules/react-native-agora'

pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

target 'estudanteTests' do
inherit! :search_paths
end

use_native_modules!
end

target 'estudante-tvOS' do

target 'estudante-tvOSTests' do
inherit! :search_paths
end

end

post_install do |installer|
installer.pods_project.targets.each do |target|
targets_to_ignore = %w(React yoga)

if targets_to_ignore.include? target.name
  target.remove_from_project
end
end
end

**Comment by javierdac** [comment]
Have you did pod install in the ios folder?

**Comment by gabrielklose** [comment]
@javierdac , yes.

**Comment by mnemanja** [comment]
I can confirm this. I am trying to build a release but I'm getting an error. When building in debug mode, then it works.

The error that I'm getting is:
```ts
Undefined symbols for architecture x86_64:
  "YGConfig::YGConfig(int (*)(YGConfig*, YGNode*, YGLogLevel, char const*, __va_list_tag*))", referenced from:
      _YGConfigNew in libYoga.a(Yoga.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

The result of my `react-native info` command:
```ts
$ react-native info
info Fetching system and libraries information...
System:
    OS: macOS 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 60.99 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.11.2 - ~/.nvm/versions/node/v10.16.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 26, 27, 28, 29
      Build Tools: 27.0.3, 28.0.3, 29.0.2
      System Images: android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    react: ^16.9.0 => 16.9.0 
    react-native: ^0.61.1 => 0.61.1 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```
