### ISSUE TITLE
Crash when using Voiceover

### ISSUE THREAD

**Issue by YoungGA** [facebook/react-native#26546]
Crash only when using Voiceover, good performance when shutting down

This only happens on XCode 11 and iOS 13

My Reat-native version is 0.59.8

void SendDelegateMessage(NSInvocation *): delegate (webView:resource:didFinishLoadingFromDataSource:) failed to return after waiting 10.000000 seconds. main run loop mode: kCFRunLoopDefaultMode

nw_connection_receive_internal_block_invoke [C26] Receive reply failed with error "Operation canceled"

Message from debugger: Terminated due to memory issue

This is the last content that appears in the console, then the program crashes

info 
  React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
      Memory: 107.11 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.12.0 - /usr/local/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    IDEs:
      Xcode: 11.0/11A419c - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.8 => 0.59.8 
    npmGlobalPackages:
      react-native-cli: 2.0.1

**Comment by BeccaSheldon** [comment]
I'm also running into this with issue using Xcode 11, iOS 13.1, react 16.8.3, and react-native 0.59.9, only when building with `react-native run-ios --device`. If I build from Xcode, it works as expected with VoiceOver.

**Comment by bryanjclark** [comment]
Whenever I run in debug with VoiceOver enabled on a physical device, I'm seeing an `EXC_BAD_ACCESS` on `perform_rebinding_with_section` in `RCTWebSocket > fishhook.c`

This is preventing me from properly supporting VoiceOver in the Khan Academy app. Yikes!

This is in Xcode 11.1, building to iOS 13.1 on an iPhone XS, with react-native 0.59.9

**Comment by douglaskim06** [comment]
Has anyone gotten any solutions? I'm running VoiceOver on with Debug build configuration and hitting the same issue as @bryanjclark

**Comment by hramos** [comment]
Please make sure to fill in the issue template.
