### ISSUE TITLE
Fast Refresh error - EXC_BAD_ACCESS 

### ISSUE THREAD

**Issue by talut** [facebook/react-native#26557]
Hi, I created a new project to try 0.61 and Fast Refresh. When I change somethings and if that changes generate an error there is no problem. 
But when I'm not solve that error and keep change something else and save it 5-6 times then IOS app crashing and XCODE saying:
`com.facebook.react.JavaScript (38): EXC_BAD_ACCESS (code=2, address=0x70000145dff8)`

React Native version:
```
System:
    OS: macOS Mojave 10.14.6
    Memory: 198.57 MB / 16.00 GB
    Shell: 3.2.57 -
  Binaries:
    Node: 11.14.0 -
    Yarn: 1.15.2 - 
    npm: 6.7.0 - 
    Watchman: 4.9.0 -
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: ^16.9.0 => 16.9.0 
    react-native: ^0.61.0 => 0.61.0 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```
## Steps To Reproduce

1. Create a new project via `react-native init` 
2. Run app form _xcode_
3. Make sure Fast Refresh is on
4. Generate a syntax etc. error. 
5. Make some changes and save 5-6 times.

I can generate this issue every time just you'll need create an error like use some undefined variable in jsx etc. then make some changes and save code every time. This error will occur.

_Describe what you expected to happen:_
App shows a red error screen but when you try to refresh _etc._ it's not work because app was crashed directly from native. And if you'll look xcode you'll see this error:
<img width="1101" alt="Screen Shot 2019-09-25 at 10 51 28" src="https://user-images.githubusercontent.com/7842301/65580506-7862e380-df82-11e9-8c04-218d209dc6c5.png">
```
com.facebook.react.JavaScript (38): EXC_BAD_ACCESS (code=2, address=0x70000145dff8)
```

_Snack, code example, screenshot, or link to a repository:_

`user is not defined`

```
import React from "react"
import { Text, View } from "react-native"

const SignIn = () => {

  return (
    <View>
      <Text>TEST</Text>
      <Text>{user !== undefined && user.hasError && "ERROR"}</Text>
    </View>
  )
}
export default SignIn
```

**Comment by gaearon** [comment]
The exact project you used and an exact video showing *what* you did would really help here. This is unfortunately too vague to try to fix.

**Comment by talut** [comment]
@gaearon Thanks for reply. I will shoot a screen record and create example project for this issue as soon as possible.

**Comment by gaearon** [comment]
Thank you!

**Comment by gaearon** [comment]
Looks a bit similar to https://github.com/facebook/react-native/issues/21434.

Can you try cleaning all build artifacts and doing a full rebuild? Like delete `ios/build` etc.

**Comment by gaearon** [comment]
Also re-run `pod install`.

**Comment by talut** [comment]
@gaearon Thank you for your time. Right now I tried reproduce issue with fresh install (0.61.2) for screen record  and error is does not occur.  Also this issue was not a blocker. It's just annoying because you need to re-run the project when it happens.

**Comment by gaearon** [comment]
I see. Maybe it had to do with some bad cached build then. Please feel free to close if you can’t reproduce anymore.
