### ISSUE TITLE
[Android] LayoutAnimation during Keyboard dismiss leads to empty space

### ISSUE THREAD

**Issue by samiede** [facebook/react-native#26551]
Using LayoutAnimation in conjunction with dismissing the keyboard leads to a weird behaviour in which the app seems to try to show the keyboard layout wise without actually showing the keyboard, but **only every other time**.

![ezgif-2-8a255d583d3c](https://user-images.githubusercontent.com/6050746/65513756-210a3800-dedc-11e9-9aa9-55980f8abe84.gif)

React Native version:

  Binaries:
    Node: 12.9.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.10.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    Android SDK:
      API Levels: 27, 28, 29
      Build Tools: 27.0.3, 28.0.3, 29.0.0, 29.0.1, 29.0.2
      System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64
      Android NDK: 20.0.5594570
  IDEs:
    Xcode: /undefined - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.5 => 0.60.5

## Steps To Reproduce

1. Use 
```    
LayoutAnimation.configureNext(LayoutAnimation.create(200, 'easeInEaseOut', 'opacity'))
```
in a function that triggers the keyboard to be dismissed or use the hardware back button
2. Trigger layout change by e.g. changing screens

**Describe what you expected to happen:**

Layout animation is consumed.

Instead, something seems to trigger a layout change that still has the keyboard extended.

I found a GitHub issue form January of last year of someone having the same problem:
https://stackoverflow.com/questions/48503892/react-native-android-layoutanimation-keyboard-flatview-bug

**Comment by VictorioMolina** [comment]
> Using LayoutAnimation in conjunction with dismissing the keyboard leads to a weird behaviour in which the app seems to try to show the keyboard layout wise without actually showing the keyboard, but **only every other time**.
> 
> ![ezgif-2-8a255d583d3c](https://user-images.githubusercontent.com/6050746/65513756-210a3800-dedc-11e9-9aa9-55980f8abe84.gif)
> 
> React Native version:
> 
> Binaries:
> Node: 12.9.0 - /usr/local/bin/node
> Yarn: 1.17.3 - /usr/local/bin/yarn
> npm: 6.10.3 - /usr/local/bin/npm
> Watchman: 4.9.0 - /usr/local/bin/watchman
> SDKs:
> Android SDK:
> API Levels: 27, 28, 29
> Build Tools: 27.0.3, 28.0.3, 29.0.0, 29.0.1, 29.0.2
> System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64
> Android NDK: 20.0.5594570
> IDEs:
> Xcode: /undefined - /usr/bin/xcodebuild
> npmPackages:
> react: 16.8.6 => 16.8.6
> react-native: 0.60.5 => 0.60.5
> 
> ## Steps To Reproduce
> 1. Use
> 
> ```
> LayoutAnimation.configureNext(LayoutAnimation.create(200, 'easeInEaseOut', 'opacity'))
> ```
> 
> in a function that triggers the keyboard to be dismissed or use the hardware back button
> 2. Trigger layout change by e.g. changing screens
> 
> **Describe what you expected to happen:**
> 
> Layout animation is consumed.
> 
> Instead, something seems to trigger a layout change that still has the keyboard extended.
> 
> I found a GitHub issue form January of last year of someone having the same problem:
> https://stackoverflow.com/questions/48503892/react-native-android-layoutanimation-keyboard-flatview-bug

Having the same problem did you fix it?

**Comment by VictorioMolina** [comment]
Exactly the same problem

**Comment by samiede** [comment]
I ended up not using Layout Animations, unfortunately :/

**Comment by bberak** [comment]
Hey @samiede and @VictorioMolina,

I'm having the same issue unfortunately.. Would hate to disable LayoutAnimation entirely because the UI seems so static without it :(

Did you have any luck with this problem in he last few months?

**Comment by bberak** [comment]
Hey @samiede and @VictorioMolina,

I never found the root cause of the problem, but what solved it for **me** was enabling `react-native-screens`

Run:

```
expo install react-native-screens
```

Then place the following code at the top of your root file before rendering any screens:

```
import { enableScreens } from "react-native-screens";

enableScreens();
```

> Note: I am using `Expo SDK 38`, so I'm not sure if this *fix* is applicable in non-Expo environments. Here is a link to the [Expo docs](https://docs.expo.io/versions/latest/sdk/screens/)

**Comment by xsevios** [comment]
Hey, @bberak,

I am not using Expo and i followed installation instruction from [react-native-screens](https://github.com/software-mansion/react-native-screens) as it described [here](https://reactnavigation.org/docs/react-native-screens/) and it solved the problem for me.

**Comment by ourmaninamsterdam** [comment]
@bberak Thanks for the heads up - this also solved a different `LayoutAnimation` issue for us.
