### ISSUE TITLE
Linking.openUrl with a telephone number throws an error

### ISSUE THREAD

**Issue by andrewsouthard** [facebook/react-native#26554]
React Native version:
System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 37.91 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.4.0 - ~/.nvm/versions/node/v12.4.0/bin/node
    Yarn: 1.12.1 - ~/.yarn/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v12.4.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 27, 28
      Build Tools: 27.0.3, 28.0.0, 28.0.2, 28.0.3
      System Images: android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.0 => 0.61.0

## Steps To Reproduce

1. `react-native init phonetest`
2. Change App.js to the following:
```import React from 'react';
import {Button, Linking, SafeAreaView} from 'react-native';

const App = () => {
  return (
    <SafeAreaView>
      <Button
        onPress={() => {
          Linking.openURL('tel:555-867-5309').catch(err =>
            console.error('An error occurred', err),
          );
        }}
        title="Call"
      />
    </SafeAreaView>
  );
};

export default App;
```

3. `react-native run-ios`

Describe what you expected to happen:
Dialog box asking whether to call the number or cancel

Instead, received the following error:
![Simulator Screen Shot - iPhone X - 2019-09-24 at 16 04 12](https://user-images.githubusercontent.com/10569175/65546411-772fa900-dee5-11e9-88c4-c0083cbbad14.png)

**Comment by andrewsouthard** [comment]
I'm getting an error still with the same App.js file as above.

**Comment by lucasbento** [comment]
This is expected, you can not make phone calls on simulator, if you test this on a real device you will see that it works.

**Comment by andrewsouthard** [comment]
@lucasbento That makes sense. Thanks! Would it be possible to throw an error message indicating that to prevent any confusion?

**Comment by kelset** [comment]
> Would it be possible to throw an error message indicating that to prevent any confusion?

Maybe instead of an error it could be a warning?
That said, I think that it's a good idea anyway - could you open a PR for it? 🤗

(since Hacktoberfest is close and I think that it's not too complicated - but I may be wrong - I'll also add the good first issue label)

**Comment by lucasbento** [comment]
Yeah, this definitely would benefit from a better error message!

**Comment by espipj** [comment]
@kelset I think this can be closed now

**Comment by kelset** [comment]
awesome, thanks!
