### ISSUE TITLE
Upgrade from 0.61.0-rc.3 to 0.61?

### ISSUE THREAD

**Issue by spyshower** [facebook/react-native#26560]
This isn't exactly a bug report.

How do I update from `0.61.0-rc.3` to `0.61`? The upgrade-helper doesn't mention rc versions.

**Comment by mattmcdonald-uk** [comment]
`0.61.0-rc.3` to `0.61` doesn't appear to have any changes, except minor version differences in `devDependencies`.

`0.61.0` to `0.61.1` does have some differences as a couple of changes were reverted so you could go straight to `0.61.1` from `0.61.0-rc.3`. Be aware that there's a problem currently with the upgrade helper suggesting reverting to React 16.8 which isn't intended (https://github.com/react-native-community/releases/issues/146#issuecomment-534965294)

**Comment by lucasbento** [comment]
@mattmcdonald-uk: thanks for linking this issue!

We just merged react-native-community/upgrade-helper#91 adding support to show the latest release candidates on the select, you can now just toggle `Show latest release candidates`:

![Show latest release candidates](https://user-images.githubusercontent.com/6207220/65597966-a5bb8b80-df9a-11e9-8719-2b71752b417b.png)

[Try it here](https://react-native-community.github.io/upgrade-helper/).
