### ISSUE TITLE
handleOpenURL() not getting triggered DeepLinking when app is dead

### ISSUE THREAD

**Issue by AliNajafi1998** [facebook/react-native#26565]
React Native version:

    System:
      OS: Windows 10
      CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
      Memory: 1.89 GB / 7.89 GB
    Binaries:
      Yarn: 1.17.3 - C:\Users\AliNajafi\AppData\Roaming\npm\yarn.CMD
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5692245

The poblem is When the app is not running in the background(Means dead) I click over the link and it opens the app but not navigate to intended screen but when the app is running in background it navigates

 having this manifest :
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
      package="com.samtbook">

       <application
        android:name=".MainApplication"
        android:label="@string/app_name"
        android:icon="@mipmap/ic_launcher"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:allowBackup="false"
        android:theme="@style/AppTheme"
        android:supportsRtl="false"
        android:usesCleartextTraffic="true"
        >
    <activity
            android:launchMode="singleTask"
            android:name=".MainActivity"
            android:label="@string/app_name"
            android:screenOrientation="portrait"
            android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
            android:windowSoftInputMode="adjustResize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN"/>
            <category android:name="android.intent.category.LAUNCHER"/>
        </intent-filter>
        <intent-filter android:autoVerify="true">
            <action android:name="android.intent.action.VIEW"/>
            <category android:name="android.intent.category.DEFAULT"/>
            <category android:name="android.intent.category.BROWSABLE"/>
            <data android:scheme="http" android:host="samtbook.me"/>
        </intent-filter>
    </activity>
    <activity android:name="com.facebook.react.devsupport.DevSettingsActivity"/>
    <meta-data
            android:name="com.google.android.geo.API_KEY"
            android:value="API_KEY"/> // HIDDEN
     </application>
    </manifest>

and registering the DeepLink like this:

    componentWillUnmount() {
        Linking.removeEventListener('url', this.handleOpenURL);
    }

    handleOpenURL(event) {
        setTimeout(_ => {
            alert(event.url);
        })
    }

    componentDidMount() {
        Linking.addEventListener('url', this.handleOpenURL);
     }
and this Link:
"http://samtbook.me/:HI"

**Comment by vonovak** [comment]
hi! you need to use [getInitialUrl](https://facebook.github.io/react-native/docs/linking#getinitialurl)

**Comment by AliNajafi1998** [comment]
@vonovak  
Hi! Could u give me an example?

**Comment by vonovak** [comment]
In componentDidMount, call also getInitialUrl instead of just Linking.addEventListener

**Comment by AliNajafi1998** [comment]
Thanks :)

**Comment by AliNajafi1998** [comment]
@vonovak The problem is the componentDidMount function not called at the first time!

**Comment by vonovak** [comment]
Hi, sorry but the discussion is pointless without having a runnable repro. ComponentDidMount most certainly does get called.
