### ISSUE TITLE
Out of Memory Stringify

### ISSUE THREAD

**Issue by kidandcat** [facebook/react-native#26576]
React Native version:
0.59.10

09-25 19:46:17.809 19931 20021 E UncaughtException: com.facebook.react.common.JavascriptException: Out of memory, stack:
09-25 19:46:17.809 19931 20021 E UncaughtException: stringify@-1
09-25 19:46:17.809 19931 20021 E UncaughtException: <unknown>@2491:8504
09-25 19:46:17.809 19931 20021 E UncaughtException: apiResponse@2491:4730
09-25 19:46:17.809 19931 20021 E UncaughtException: E@2490:10322
09-25 19:46:17.809 19931 20021 E UncaughtException: <unknown>@2490:10582
09-25 19:46:17.809 19931 20021 E UncaughtException: <unknown>@2493:929
09-25 19:46:17.809 19931 20021 E UncaughtException: value@123:1505
09-25 19:46:17.809 19931 20021 E UncaughtException: value@122:5917
09-25 19:46:17.809 19931 20021 E UncaughtException: value@122:2835
09-25 19:46:17.809 19931 20021 E UncaughtException: value@49:1280
09-25 19:46:17.809 19931 20021 E UncaughtException: value@28:3311
09-25 19:46:17.809 19931 20021 E UncaughtException: <unknown>@28:822
09-25 19:46:17.809 19931 20021 E UncaughtException: value@28:2565
09-25 19:46:17.809 19931 20021 E UncaughtException: value@28:794
09-25 19:46:17.809 19931 20021 E UncaughtException: value@-1
09-25 19:46:17.809 19931 20021 E UncaughtException:
09-25 19:46:17.809 19931 20021 E UncaughtException:     at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:54)
09-25 19:46:17.809 19931 20021 E UncaughtException:     at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:38)
09-25 19:46:17.809 19931 20021 E UncaughtException:     at java.lang.reflect.Method.invoke(Native Method)
09-25 19:46:17.809 19931 20021 E UncaughtException:     at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
09-25 19:46:17.809 19931 20021 E UncaughtException:     at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
09-25 19:46:17.809 19931 20021 E UncaughtException:     at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
09-25 19:46:17.809 19931 20021 E UncaughtException:     at android.os.Handler.handleCallback(Handler.java:907)
09-25 19:46:17.809 19931 20021 E UncaughtException:     at android.os.Handler.dispatchMessage(Handler.java:105)
09-25 19:46:17.809 19931 20021 E UncaughtException:     at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
09-25 19:46:17.809 19931 20021 E UncaughtException:     at android.os.Looper.loop(Looper.java:216)
09-25 19:46:17.809 19931 20021 E UncaughtException:     at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
09-25 19:46:17.809 19931 20021 E UncaughtException:     at java.lang.Thread.run(Thread.java:784)

## Steps To Reproduce

1. It just started happening 

Describe what you expected to happen:
App don't crash

With this Stacktrace is impossible to debug anything. That's from logcat, same info when react-native run-android. It happens in dev mode and also in release APK. I've tested in emulator with 4GB heap memory + 6GB RAM, it still happens

**Comment by kidandcat** [comment]
I have 0 JSON.stringify in App code, also the trace doesn't help at all

**Comment by tbrent** [comment]
I'm getting this too with React 0.60.4

**Comment by SteffenSorensen** [comment]
I'm getting kind of the same on iOS with React Native 0.59.5. So far only release builds, and only on customer phones. I can't reproduce on my own devices. I see it on iOS 12 and 13, and on iPhone 7, 8 and X. Crashlytics reports `RAM free` of above 200 and 300 MB in some instances.

```
Fatal Exception: RCTFatalException: Unhandled JS Exception: Out of memory
Unhandled JS Exception: Out of memory, stack: stringify@<null>:<null> E@690:677 p@690:582 y@123:657 callTimers@123:2816 value@36:3311 <unknown>@36:822 value@36:2565 value@36:794 value@<null>:<null>
```

With native stack trace:
```
Fatal Exception: RCTFatalException: Unhandled JS Exception: Out of memory
0  CoreFoundation                 0x1a652498c __exceptionPreprocess
1  libobjc.A.dylib                0x1a624d0a4 objc_exception_throw
2  MyAppName                      0x100a8c680 RCTFormatError + 163 (RCTAssert.m:163)
3  MyAppName                      0x100a88bb4 -[RCTExceptionsManager reportFatalException:stack:exceptionId:] + 58 (RCTExceptionsManager.m:58)
4  CoreFoundation                 0x1a652ad90 __invoking___
5  CoreFoundation                 0x1a63fabd0 -[NSInvocation invoke]
6  CoreFoundation                 0x1a63fb7a8 -[NSInvocation invokeWithTarget:]
7  MyAppName                      0x100a9fc74 -[RCTModuleMethod invokeWithBridge:module:arguments:] + 554 (RCTModuleMethod.mm:554)
8  MyAppName                      0x100adf438 facebook::react::invokeInner(RCTBridge*, RCTModuleData*, unsigned int, folly::dynamic const&) + 104 (RCTNativeModule.mm:104)
9  MyAppName                      0x100adf198 invocation function for block in facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int) + 365 (Optional.h:365)
10 libdispatch.dylib              0x1a61f1610 _dispatch_call_block_and_release
...
```

**Comment by williamtran1988** [comment]
I am getting this kind of issue with react 0.60.5. Have any ideas? Actually, i could not reproduce it on both real device and simulator.

**Comment by SteffenSorensen** [comment]
@williamtran1988 I’m using Redux with Redux Persist. It turns out, when I remove a certain element from the whitelist of what Redux Persist should persist, then I stop getting the crash.
