### ISSUE TITLE
Question: React-Native project stuck on :app:installDebug after init new project version 0.61

### ISSUE THREAD

**Issue by vuggg** [facebook/react-native#26571]
After install react-native version 0.61, I installed some UI libary, and my computer lag then stop working.

Now, every time I run react-native run-android It stuck at 99%, I have tried install apk by drag apk file into Virtual device, but it didn't work.

**Comment by vuggg** [comment]
Delete Virtual device and create new one.

**Comment by shakyarahul** [comment]
You can try by reconnecting your device and deleting the older version of the same project which are upgrading.. worked for me
