### ISSUE TITLE
[0.61.0] Debugging console is not link log to the source

### ISSUE THREAD

**Issue by ripzery** [facebook/react-native#26570]
On `0.61.0`, every console log is now always pointing to `setUpDeveloperTools.js:73` instead of pointing to the source. Not sure if it related to these changes 🤔 (https://github.com/facebook/react-native/commit/81ec2112a15e3d66b7973f0e1aaa8986fcca753f#diff-8863a34349d2a00986749efcf471649c)

It used to work fine on `0.60.4`.

![image](https://user-images.githubusercontent.com/4509570/65613615-8a736f00-dfe0-11e9-9be3-38605cbbd041.png)

## React Native version:
```
System:
    OS: macOS Mojave 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 540.27 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.3.1 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 15, 19, 22, 23, 24, 25, 26, 27, 28
      Build Tools: 27.0.3, 28.0.0, 28.0.2, 28.0.3, 29.0.0
      System Images: android-22 | Google APIs Intel x86 Atom, android-24 | Google APIs Intel x86 Atom, android-P | Google Play Intel x86 Atom, android-Q | Google APIs Intel x86 Atom
      Android NDK: 19.2.5345600
  IDEs:
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.0 => 0.61.0 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

## Steps To Reproduce

1. Launch application in debug mode.
2. Add `console.log` somewhere in the code.
3. Open the debugger console.
4. Every log is coming from `setUpDeveloperTools.js:73`

## Describe what you expected to happen:

The debugger console should link the log to the source file & number of lines.

**Comment by luisorduz** [comment]
the same thing happens to me, please a solution!
I'm using the Google Chrome browser..
![Screen Shot 2019-09-27 at 11 45 43 AM](https://user-images.githubusercontent.com/8128447/65786502-6026cc00-e11c-11e9-95d6-83535579f066.png)

**Comment by davichoso** [comment]
Have the same issue in version   "react-native": "0.61.1"

**Comment by rsallar** [comment]
Same problem here.

**Comment by iOSUser110** [comment]
facing same issue . Cant debug the source code with latest version . debugger stops on Exception

**Comment by magrinj** [comment]
Same problem on version 0.61.1

**Comment by darknblack** [comment]
Same problem here.

**Comment by makn3tiza** [comment]
Same problem "react-native": "0.61.2"

**Comment by cauyyl** [comment]
Same problem react-native@0.61.1

**Comment by IceDev-xyz** [comment]
Same problem here :(

**Comment by ankithtv** [comment]
got same problem "react-native": "0.61.2"

**Comment by lander854** [comment]
Same after upgrading to 61.2

**Comment by IceDev-xyz** [comment]
Just FYI to everybody, it seems this will be fixed on the next release. 

https://github.com/facebook/react-native/pull/26883

**Comment by makn3tiza** [comment]
In the meantime you can "patch" your /node_modules/react-native/Libraries/Core/setUpDeveloperTools.js

In line 57

replace 

**if (!Platform.isTesting) {**

by

**if (!Platform.isTesting && global.nativeLoggingHook) {**

**Comment by drinikol** [comment]
^^^ RN 0.61.3 still didnt updated this fix.

**Comment by daihieptn97** [comment]
> In the meantime you can "patch" your
> 
> **/node_modules/react-native/Libraries/Core/setUpDeveloperTools.js**
> 
> ### In line 57
> replace
> 
> **if (!Platform.isTesting) {**
> 
> by
> 
> **if (!Platform.isTesting && global.nativeLoggingHook) {**
> 
> and source will be showed up until next RN's release
> 
> ![Captura de Pantalla 2019-10-21 a la(s) 7 29 09 a  m](https://user-images.githubusercontent.com/40246676/67205054-8286cf00-f3d4-11e9-889b-8a0ca0b3cffe.png)

working for me 💯  , thanks you

**Comment by jianjiade** [comment]
Same problem "react-native": "0.61.2"

**Comment by grabbou** [comment]
Looks like this has been fixed via https://github.com/facebook/react-native/commit/42ac240bceb104474494c6007df0089baec00f7a. I will cherry-pick the fix.

**Comment by mrsnow070** [comment]
Patch package to fix it

react-native+0.61.3.patch

`diff --git a/node_modules/react-native/Libraries/Core/setUpDeveloperTools.js b/node_modules/react-native/Libraries/Core/setUpDeveloperTools.js
index 7a9ff42..40ce9eb 100644
--- a/node_modules/react-native/Libraries/Core/setUpDeveloperTools.js
+++ b/node_modules/react-native/Libraries/Core/setUpDeveloperTools.js
@@ -54,7 +54,7 @@ if (__DEV__) {
       JSInspector.registerAgent(require('../JSInspector/NetworkAgent'));
     }

-    if (!Platform.isTesting) {
+    if (!Platform.isTesting && global.nativeLoggingHook) {
       const HMRClient = require('../Utilities/HMRClient');
       [
         'trace',
`
