### ISSUE TITLE
Cannot find module 'C:\Users\USER\AppData\Roaming\npm\node_modules\expo-cli\bin\expo.js

### ISSUE THREAD

**Issue by Hysome** [facebook/react-native#26575]
Immediately after updating node i got an error of 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node@8.16.1 preinstall: `node installArchSpecificPackage`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node@8.16.1 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\USER\AppData\Roaming\npm-cache\_logs\2019-09-25T17_14_47_778Z-debug.log

Someone on stackover flow suggested to me to remove the folder of Node_module..now I'm getting two errors module not found and that i posted above

**Comment by brentvatne** [comment]
update node to the latest LTS version as the documentation suggests. you can download that from https://nodejs.org/en/download/

nodejs 8 is not supported

**Comment by musiimephillip** [comment]
> update node to the latest LTS version as the documentation suggests. you can download that from https://nodejs.org/en/download/
> 

Thanks. This helped. Encountered the same problem

**Comment by omar-bakhsh** [comment]
** I still have the error**
    
    ```
Amoory@S MINGW64 ~/Desktop
    $ expo init my-new-project
    internal/modules/cjs/loader.js:797
    throw err;
    ^

Error: Cannot find module 'C:\Users\Amoory\AppData\Roaming\npm\node_modules\expo-cli\bin\expo.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
     
```

**Comment by omar-bakhsh** [comment]
> ** I still have the error **
> 
> ```
> ```Amoory@S MINGW64 ~/Desktop
> $ expo init my-new-project
> internal/modules/cjs/loader.js:797
> throw err;
> ^
> 
> Error: Cannot find module 'C:\Users\Amoory\AppData\Roaming\npm\node_modules\expo- 
> cli\bin\expo.js'
> at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
> at Function.Module._load (internal/modules/cjs/loader.js:687:27)
> at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
> at internal/main/run_main_module.js:17:11 {
>   code: 'MODULE_NOT_FOUND',
>    requireStack: []
> ```
> 
> }```
```

Amoory@S MINGW64 ~/Desktop
$ node -v
v12.13.0

Amoory@S MINGW64 ~/Desktop
$ npm -v
6.12.0

Amoory@S MINGW64 ~/Desktop
$ npm doctor
npm notice PING https://registry.npmjs.org/
npm WARN verifyCachedFiles Content garbage-collected: 50 (24927770 bytes)
npm WARN verifyCachedFiles Cache issues have been fixed
Check                               Value                                     Recommendation
npm ping                            ok
npm -v                              v6.12.0                                   Use npm v6.13.1
node -v                             v12.13.0                                  Use node v12.13.1
npm config get registry             https://registry.npmjs.org/
which git                           C:\Program Files\Git\mingw64\bin\git.EXE
Perms check on cached files         ok
Perms check on global node_modules  ok
Perms check on local node_modules   ok
Verify cache contents               verified 2991 tarballs


```

**Comment by lupapp** [comment]
tengo el mismo problema

**Comment by Wixi105** [comment]
I also have the same problem I ran the command and got an error message just like that

**Comment by Wixi105** [comment]
I found the solution just run it in your user folder because it does not respond when you ran it in a different directory other than maybe C:\Users\User_Name

**Comment by mehtabismail** [comment]
plzzz help ,,,,,,errorr



internal/modules/cjs/loader.js:957
    throw err;
    ^

Error: Cannot find module 'C:\Users\mehta\AppData\Roaming\npm\node_modules\expo-cli\bin\expo.js'
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:954:17)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:847:27)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:67:12)[39m
[90m    at internal/main/run_main_module.js:17:47[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []
}

**Comment by omar-bakhsh** [comment]
> plzzz help ,,,,,,errorr
> 
> internal/modules/cjs/loader.js:957
> throw err;
> ^
> 
> Error: Cannot find module 'C:\Users\mehta\AppData\Roaming\npm\node_modules\expo-cli\bin\expo.js'
> �[90m at Function.Module._resolveFilename (internal/modules/cjs/loader.js:954:17)�[39m
> �[90m at Function.Module._load (internal/modules/cjs/loader.js:847:27)�[39m
> �[90m at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:67:12)�[39m
> �[90m at internal/main/run_main_module.js:17:47�[39m {
> code: �[32m'MODULE_NOT_FOUND'�[39m,
> requireStack: []
> }

try with cmd in user files

**Comment by jkanchelov** [comment]
I have the same problem trying to install the expo. I am using node v13.2.0. Reproducing it on 2 different systems

**Comment by ciruz** [comment]
I had the same error, so I tried to reinstall expo-cli globally, and noticed there's an error with envsub@3.1.0.

There really is an issue regarding envsub and the solution there, solved the "cannot find module" for me, reinstalling expo with git bash (Windows).

https://github.com/expo/expo-cli/issues/1284#issuecomment-560019506

**Comment by AxelMendez1** [comment]
> Tuve el mismo error, así que intenté reinstalar expo-cli a nivel mundial y noté que hay un error con envsub@3.1.0.
> 
> Hay otro problema de GitHub con respecto al error envsub y la solución allí resolvió el "no se puede encontrar el módulo" para mí. Reinstalar expo con git bash (Windows) hizo el truco.
> 
> [expo / expo-cli # 1284 (comentario)](https://github.com/expo/expo-cli/issues/1284#issuecomment-560019506)

Como hiciste para resolverlo? lo de expo-cli

**Comment by lucashdp** [comment]
Hey guys,

`npm install -g expo-cli --force`

Works for me.

**Comment by omarome** [comment]
You just have some files missing so you need to install all the packages needed, try this out :

npm install mysql @types/mysql

**Comment by bawanthi** [comment]
I have this error. please help 

react-native : File C:\Users\bawan\AppData\Roaming\npm\react-native.ps1 cannot be loaded because running scripts is disabled on this system. For more information, 
see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ react-native run-android
+ ~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess

**Comment by NooKai20** [comment]
I have this error. please help

react-native : File C:\Users\bawan\AppData\Roaming\npm\react-native.ps1 cannot be loaded because running scripts is disabled on this system. For more information,
see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1

react-native run-android
  + CategoryInfo          : SecurityError: (:) [], PSSecurityException
  + FullyQualifiedErrorId : UnauthorizedAccess

**Comment by araujowp** [comment]
npm install -g expo-cli --force

Works for me. too 

tks @lucashdp

**Comment by kurbanovjasur** [comment]
> Hey guys,
> 
> `npm install -g expo-cli --force`
> 
> Works for me.

Works for me as well

**Comment by bsdaoquang** [comment]
> Hey guys,
> 
> `npm install -g expo-cli --force`
> 
> Works for me.

thank you very much, it works for me too

**Comment by arupgorai** [comment]
Hi,
`npm install -g expo-cli --force`

works for me too..

Thanks

**Comment by ShujaShah** [comment]
none of the above answers works for me :(

**Comment by rikikuswo** [comment]
Hello,
npm install -g expo-cli --force

works for me too..

Thank you

**Comment by mohamad7694** [comment]
hello 
npm install -g expo-cli --force
it works 
thanks

**Comment by kaal007** [comment]
bbb

**Comment by alejomon** [comment]
npm install -g react-native-cli --force
with that i achieved run my app when i had this problem.

**Comment by ah-idx9** [comment]
I had the same problem. It was due to expo cli script being installed into C:\Program Files\nodejs instead of the AppData location. To fix do the following on Windows :

C:\>where expo 
C:\Program Files\nodejs\expo
C:\Program Files\nodejs\expo.cmd
C:\Users\anand\AppData\Roaming\npm\expo
C:\Users\anand\AppData\Roaming\npm\expo.cmd


You need to make sure that the expo cli being found is the correct one. In the case above, i just renamed C:\Program Files\nodejs\expo and expo.cmd and everything started working.

**Comment by FizaWaseem** [comment]
I am facing a problem when create a rect native project

C:\Users\FizaWaseem>node --version
v12.16.3

C:\Users\FizaWaseem>npm --version
6.14.4
-----------------------here is proble--------------
PS F:\React-native\APP> expo init AwesomeProject
internal/modules/cjs/loader.js:960
  throw err;
  ^

Error: Cannot find module 'C:\Users\FizaWaseem\AppData\Roaming\npm\node_modules\expo-cli\bin\expo.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

**Comment by FizaWaseem** [comment]
> none of the above answers works for me :(

same ..please help me if you find solution

**Comment by oguzhnatly** [comment]
Hey guys,
`npm install -g expo-cli --force`
Thanks for solution, it works for me but if it doesn't work for anyone in here, try to type `expo start` instead of yarn or npm start. Also this worked for me too.

Thanks!

**Comment by rihab486** [comment]
j'ai toujours c errr ,, plz aider moi 
C:\Users\lenovo>node -v
v12.19.0

C:\Users\lenovo>npm install -g create-react-app
internal/modules/cjs/loader.js:834
  throw err;
  ^

Error: Cannot find module 'C:\Users\lenovo\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js'
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:687:27)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)←[39m
←[90m    at internal/main/run_main_module.js:17:47←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: []
}

**Comment by clewertonx1** [comment]
> Hey guys,
> 
> `npm install -g expo-cli --force`
> 
> Works for me.

works to me too

**Comment by rihab486** [comment]
Hi
Thanx for the help


Le jeu. 28 janv. 2021 à 20:17, Clewerton Roque <notifications@github.com> a
écrit :

**Comment by Umairali2562** [comment]
> ** I still have the error **
> 
> ```
> ```Amoory@S MINGW64 ~/Desktop
> $ expo init my-new-project
> internal/modules/cjs/loader.js:797
> throw err;
> ^
> 
> Error: Cannot find module 'C:\Users\Amoory\AppData\Roaming\npm\node_modules\expo- 
> cli\bin\expo.js'
> at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
> at Function.Module._load (internal/modules/cjs/loader.js:687:27)
> at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
> at internal/main/run_main_module.js:17:11 {
>   code: 'MODULE_NOT_FOUND',
>    requireStack: []
> ```
> 
> }```

C:\Users\Amoory\AppData\Roaming\npm\node_modules\expo- 
> cli\bin\expo.js  delete this file and then try 

npm rm gulp -g   ---> this will uninstall the gulp completely if you ever had played it around with
npm install --global gulp  --> a fresh copy will install

**Comment by ochiroo11** [comment]
Error: Cannot find module 'C:\Users\FuLL\AppData\Roaming\npm\node_modules\expo-cli\bin\expo.js'
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:725:27)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)[39m
[90m    at internal/main/run_main_module.js:17:47[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []
}

**Comment by kys38337** [comment]
> Hey guys,
> 
> `npm install -g expo-cli --force`
> 
> Works for me.

works for me to
