### ISSUE TITLE
Memory Leak after app refresh?

### ISSUE THREAD

**Issue by msqar** [facebook/react-native#26581]
React Native version:
```
  System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz
    Memory: 20.73 MB / 8.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 11.10.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.7.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: ^0.60.5 => 0.60.5
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

I've noticed on my current app, using a real iPhone XS device, that whenever I start it up, the Profiler in Xcode says 50-60MB usage of RAM, but as soon as i shake it to refresh, the RAM usage keeps stacking up every time.
I saw there was a bug ticket before and was closed due to "no more activity" on it. But i'm using 0.60.5 and this is happening.

Can anyone confirm this?

If this is not a bug, why can this be caused or how to possibly fix it? My concern is if this could happen in a release version.

Thanks.

**Comment by msqar** [comment]
What? 0.61 has already been released? I'll check that.

**Comment by Gabrielfcs** [comment]
I have a similar problem, but running the app on the simulator
I realize that if I don't use the cmd + r command to update, the app flows all day without problems. But as I refresh, it slows down and consumes more memory.
It even seems that with each refresh, React Native creates a new instance of the same app without destroying the previous instance and accumulating memory.

**Comment by msqar** [comment]
@Gabrielfcs i guess it won't be a problem in the future, then. Thanks!
