### ISSUE TITLE
use_frameworks support

### ISSUE THREAD

**Issue by annakocheshkova** [facebook/react-native#26588]
Hi there react-native community! Greetings from App Center (again :slightly_smiling_face:).

We have a question concerning "Better support for use_frameworks!" in your 0.61 release. Does that include our case or still not quite?
We have a dynamic AppCenter framework linked to the static AppCenterReactNative one, and based on my latest tests, it still doesn't work with `use_frameworks!`. [Here](https://github.com/microsoft/appcenter-sdk-react-native/issues/714) for example one of our customer's issue.

I was having the impression that it is partially fixed in your new release, is that so? We haven't found any more documentation on this. Thanks!

**React Native version:** 0.61-rc3

## Steps To Reproduce

[Here](https://github.com/microsoft/appcenter-sdk-react-native/issues/714)

**Comment by rickhanlonii** [comment]
Hey @annakocheshkova, I'm not familiar with your use case.

Can you help us understand what's not working?

**Comment by rickhanlonii** [comment]
@jtreanor could you help with this?

**Comment by jtreanor** [comment]
Yes, `use_frameworks!` should be working in the latest 0.61 RC. I can take a closer look to see if I can figure why this isn't working in your case.

**Comment by annakocheshkova** [comment]
Hey there, thanks for the quick response! 

Basically one of our customers wrote in saying that he read about "Better use_frameworks! support" in 0.61 version and he tried that with our module but it didn't work. I can confirm it's true.

The reason is that we have 3 sets of plugins:
- Plugins for each module (**appcenter**, **appcenter-analytics**, **appcenter-crashes** etc.)
- Shared plugin (**AppCenterReactNativeShared**) referenced from each of those ^
- And native iOS framework named **AppCenter** referenced from **AppCenterReactNativeShared**.

As seen from the original customer's issue, react-native doesn't see the latter framework because it's not a conventional static framework, so react-native tries to search for **AppCenter** headers used in **AppCenterReactNativeShared**, but searches them in **appcenter** folder and fails.
This is the structure:
![image](https://user-images.githubusercontent.com/34677812/65700308-1e4c4600-e088-11e9-9cd9-2d10aaf480c0.png)

**Comment by jtreanor** [comment]
From your description, I'm not sure this is related to the CocoaPods `use_frameworks!` option, but perhaps I am mistaken. The improvements in 0.61 are purely concerned with supporting integrating React Native via CocoaPods with `use_frameworks!` enabled.

**Comment by annakocheshkova** [comment]
Well I narrowed it down to this because it works fine without `use_frameworks!`. 

Not sure if that is entirely the case, but one of the reasons at least.
The gist of the issue is that Xcode somehow ignores the case and looks for AppCenter headers inside appcenter folder at the moment of build. 
This is either Xcode/Cocoapods issue, or something in react-native doesn't allow to search inside a dynamic framework target. Not even sure where to dig.

What led me to my assumptions is this:
![image](https://user-images.githubusercontent.com/34677812/65714460-c9b6c400-e0a3-11e9-8b4a-08aef3c7302e.png)

**Comment by kevinvangelder** [comment]
Not sure if this will be any help at all or not, but I recently tried to use Expo's unimodules in a 0.60.5 project and discovered that using both the `use_unimodules!` and the `use_native_modules!` (autolinking) declarations prevented my pods from being properly included in my project.

**Comment by JuanSeBestia** [comment]
Hello, I am in the same predicament of @annakocheshkova, I have the same conclusions, I really do not know where to start digging, if you have any idea I am all ears

**Comment by tomchomiak** [comment]
bump
