### ISSUE TITLE
React Native Project won't start anymore.

### ISSUE THREAD

**Issue by yesIamFaded** [facebook/react-native#26595]
Hi Guys for some reason my app that was working normal yesterday doesnt start up today :/

React Native version: 0.59.8 //// But also tried with 0.59.5 and 0.59.9

## Steps To Reproduce

1 .Just start up the App.
2. It was working normally yesterday and today its bugged

Describe what you expected to happen:

So I have a RN app which I have for a few months now and i started to continue with it yesterday.
Everything was working fine yesterday but for some reason it is not working today.

No matter if I start it up with:
1. npm start
2. npm run android ( react-native run-android )
3. npm start -- --reset-cache + npm run android

it always crashes with some different code.

I tried many fixes but none of them work for me.
- I tried to link gesture-handler again and reinstalling it.
- tried using jetifier
- deleted node-modules and reinstalled it
- and some other fixes like updating packages...

=> for some reason I always get an error even though it was working yesterday

ty for your help Faded.

package.json file : 

![Unbenannt](https://user-images.githubusercontent.com/48751859/65678697-14105480-e054-11e9-8ecd-7562a9f35fff.PNG)

Snack, code example, screenshot, or link to a repository:

case npm start: 
Metro Bundler starts up fine if I refresh the app i get: 

![npm start](https://user-images.githubusercontent.com/48751859/65678374-72890300-e053-11e9-9824-8e9400876999.PNG)

case npm run android (react-native run-android) : 

![npmRunandroid](https://user-images.githubusercontent.com/48751859/65678444-93e9ef00-e053-11e9-9bb6-435dbc3a25d8.PNG)

case npm start -- --reset-cache and npm run android: 
Metro bundler starts normally but then when runing npm run android => 

![npmreset](https://user-images.githubusercontent.com/48751859/65678599-e4614c80-e053-11e9-9713-181f19cd8919.PNG)

any ideas where the probleme may be ?

**Comment by TheSavior** [comment]
From the error message it looks like your node module `pg` has a problem with it's dependency `util`
