### ISSUE TITLE
Picker's Initial Value:  It's automatically selects first value 

### ISSUE THREAD

**Issue by ezranbayantemur** [facebook/react-native#26596]
I'm storing a value on my local memory and when user changes picker's value it's directly storing local memory, replace the older.
And when user opens app again I want to show stored value as picker's inital value, but it's directly selects it's initial value on ``` <Picker.Item>``` list.

I can't chagne item list because it's fetching on API directly.

Problem example: 
```
picker values: [ 1, 2, 3, 4 ]
inital value 1

-> user selects 3, and it's stored on local data
-> re-open app

picker values: [ 1, 2, 3, 4 ]
inital value 1 (it has to be 3)

```

Any solution about it?

```
"react-native": "0.60.4"
```

**Comment by sauzy34** [comment]
When you're initializing the state do it like this:

```
state = {
    isLoading: false,
    pickerValue: valueFromLocalStorage || []
  }
```

**Comment by tytech3** [comment]
I'm having this issue as well. It's quite a staggering UI experience when this happens.

So this is kinda my 'slap a bandaid on it and call it a day' method to fixing it..

`<Picker
          selectedValue={this.state.plan_number}
          style={{ color: EStyleSheet.value('$textColor') }}
          onValueChange={(itemValue) =>{

            if(did_load === 0){
              did_load += 1;
              return;
            }

            this.setState({plan_number: itemValue})
            this.onRefresh(itemValue);
          }
          }>`

did_load is a global variable that will stop the picker from initializing as the first component. 

I have a websocket that retrieves the currently selected item, and sets the state for the selectedValue. I added a console.log in the render method to see what the state actually is for selected value, and its correct all but the last time. When it's finally done rendering, the picker calls its own onValueChange method with the itemValue of 0. Is there a reason it needs to default to 0? Why can't i set the default value? 

When i select different values, i have to query my websocket again and retrieve the data they have selected. When this happens, the picker will flash to the initial value, then switch to user selected value. It's a pretty unfavorable UX.

**Comment by hramos** [comment]
Closing after several months without followup from the author. Please make sure to fill in the issue template if you decide to file a new issue.
