### ISSUE TITLE
Build failed after updating xCode from 10.3 to 11.0 (iOS)

### ISSUE THREAD

**Issue by NemanjaManot** [facebook/react-native#26594]
I cannot build iOS locally (on simulator) after updating my xCode from 10.3 to 11.0.

When I build my iOS app on BuddyBuild with xCode version 11.0 everything is working - build successful.

But I cannot build my app in simulator.

React Native version:

>   React Native Environment Info:
>     System:
>       OS: macOS 10.14.6
>       CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
>       Memory: 2.44 GB / 16.00 GB
>       Shell: 3.2.57 - /bin/bash
>     Binaries:
>       Node: 10.16.0 - /usr/local/bin/node
>       npm: 6.9.0 - /usr/local/bin/npm
>       Watchman: 4.9.0 - /usr/local/bin/watchman
>     SDKs:
>       iOS SDK:
>         Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
>       Android SDK:
>         API Levels: 26, 28, 29
>         Build Tools: 28.0.3, 29.0.1
>         System Images: android-28 | Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
>     IDEs:
>       Android Studio: 3.4 AI-183.6156.11.34.5692245
>       Xcode: 11.0/11A420a - /usr/bin/xcodebuild
>     npmPackages:
>       react: ^16.9.0 => 16.9.0 
>       react-native: 0.59.10 => 0.59.10 
>     npmGlobalPackages:
>       react-native-cli: 2.0.1

## Steps To Reproduce

- When I run command react-native run-ios --simulator="iPhone 8" I got this error

> error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening myApp.xcworkspace

- When I run my app from myApp.xcworkspace I got this error:

> ld: library not found for -lBVLinearGradient clang: error: linker command failed with exit code 1 (use -v to see invocation)

Very strange is that **build is working when I am building my app on BuddyBuild** service. But I **cannot build and test my app in simulator**.

How I can fix this?

**Comment by NemanjaManot** [comment]
Thank you bot, but that is not option at the momment.

**Comment by cmcaboy** [comment]
For the error 65 issue, was there any more output above? Unfortunately, 65 is a generic error.

**Comment by NemanjaManot** [comment]
This was a issue with `react-native-linear-gradient` library.
I changed version to 2.4.0 and everything is working fine now. Strange.

**Comment by Aung-Myint-Thein** [comment]
> This was a issue with `react-native-linear-gradient` library.
> I changed version to 2.4.0 and everything is working fine now. Strange.

From which version of react-native-linear-gradient you changed to 2.4.0?

**Comment by Aung-Myint-Thein** [comment]
@NemanjaManot  I changed to `react-native-linear-gradient` 2.4.0 and now it is working but only about 10 seconds and the app still crashes on xcode 11. We are using RN 0.61.4. It was working fine on xcode 10. Any clue..?

![Screenshot 2019-11-26 at 7 30 17 AM](https://user-images.githubusercontent.com/612366/69590695-ae722180-101e-11ea-837a-d3447650aeee.png)
