### ISSUE TITLE
The performance of the ListView in iPhone 4 is not native

### ISSUE THREAD

**Issue by danicomas** [facebook/react-native#2660]
After do the first scroll down and do more we can see as the performance worsens.

IPhone 4 iOS 7.1

**Comment by brentvatne** [comment]
ListView performance is a well known issue, there is a discussion going on here https://github.com/facebook/react-native/issues/332 about improving the performance and some work being done internally at FB to optimize this, however, it is not a top priority so I encourage you to explore solutions in #332, we would all like to see a nice solution to this!

**Comment by ide** [comment]
Try putting `style={{overflow: 'hidden'}` on each row and `removeClippedSubviews` on the ListView: https://facebook.github.io/react-native/docs/scrollview.html. Also the iPhone 4 has a single-core processor which can't take full advantage of RN's triple-threaded design.

**Comment by pvinis** [comment]
can i ask why triple threaded? i thought it was two parts. the js running and the layouting. what am i missing?

**Comment by ide** [comment]
Rendering work is done on the main thread.

**Comment by pvinis** [comment]
so one is running js, main is rendering, and the third?

**Comment by ide** [comment]
Layout

**Comment by pvinis** [comment]
oh. ok, right. i forgot that layout and render is separated.. thanks.
