### ISSUE TITLE
Question: getting error on 'react-native start'

### ISSUE THREAD

**Issue by nwkevin** [facebook/react-native#26603]
Hi, 
1. I just installed node.js & cli 
- * installed node.js
> npm -g react-native-cli

2. And created a 'new project'. 
> react-native init new_project

3. and inside that 'new_project' directory, I tired to see if metro bundler works well. 
> react-native start

But the command gives me following error and metro is not starting.
Any clue for fixing this error? 
(I'm using windows 10 OS.)

------------------error message I am getting----------------------
C:\projects\new_proj>react-native start
error Invalid regular expression: /(.*\\__fixtures__\\.*|node_modules[\\\]react[\\\]dist[\\\].*|website\\node_modules\\.*|heapCapture\\bundle\.js|.*\\__tests__\\.*)$/: Unterminated character class. Run CLI with --verbose flag for more details.
SyntaxError: Invalid regular expression: /(.*\\__fixtures__\\.*|node_modules[\\\]react[\\\]dist[\\\].*|website\\node_modules\\.*|heapCapture\\bundle\.js|.*\\__tests__\\.*)$/: Unterminated character class
    at new RegExp (<anonymous>)
    at blacklist (D:\projects\new_proj\node_modules\metro-config\src\defaults\blacklist.js:34:10)
    at getBlacklistRE (D:\projects\new_proj\node_modules\react-native\node_modules\@react-native-community\cli\build\tools\loadMetroConfig.js:69:59)
    at getDefaultConfig (D:\projects\new_proj\node_modules\react-native\node_modules\@react-native-community\cli\build\tools\loadMetroConfig.js:85:20)
    at load (D:\projects\new_proj\node_modules\react-native\node_modules\@react-native-community\cli\build\tools\loadMetroConfig.js:121:25)
    at Object.runServer [as func] (D:\projects\new_proj\node_modules\react-native\node_modules\@react-native-community\cli\build\commands\server\runServer.js:82:58)
    at Command.handleAction (D:\projects\new_proj\node_modules\react-native\node_modules\@react-native-community\cli\build\cliEntry.js:160:21)
    at Command.listener (D:\projects\new_proj\node_modules\commander\index.js:315:8)
    at Command.emit (events.js:210:5)
    at Command.parseArgs (D:\projects\new_proj\node_modules\commander\index.js:651:12)

**Comment by LeoLei** [comment]
It's caused by node v12.11.0, downgrade to v12.10.0 will solve it.

**Comment by liudonghua123** [comment]
Yes, maybe it's a bug in the latest v12.11.0 node, see https://stackoverflow.com/questions/58120990/question-getting-error-on-react-native-start# for more details.

**Comment by mengao02** [comment]
O mesmo estava acontecendo comigo, fiz o downgrade do node e funcionou.

**Comment by armohammadi56** [comment]
It appears in \node_modules\metro-config\src\defaults\blacklist.js, there is an invalid regular expression that needed changed. I changed the first expression under sharedBlacklist from:

var sharedBlacklist = [
  /node_modules[/\\]react[/\\]dist[/\\].*/,
  /website\/node_modules\/.*/,
  /heapCapture\/bundle\.js/,
  /.*\/__tests__\/.*/
];

to:

var sharedBlacklist = [
  /node_modules[\/\\]react[\/\\]dist[\/\\].*/,
  /website\/node_modules\/.*/,
  /heapCapture\/bundle\.js/,
  /.*\/__tests__\/.*/
];

**Comment by archit6204** [comment]
Yes, it is the bug in the newer version of node.js.


It appears in \node_modules\metro-config\src\defaults\blacklist.js, there is an invalid regular expression that needed to be changed. I changed the first expression under sharedBlacklist from:

var sharedBlacklist = [
  /node_modules[/\\]react[/\\]dist[/\\].*/,
  /website\/node_modules\/.*/,
  /heapCapture\/bundle\.js/,
  /.*\/__tests__\/.*/
];
to:

var sharedBlacklist = [
  /node_modules[\/\\]react[\/\\]dist[\/\\].*/,
  /website\/node_modules\/.*/,
  /heapCapture\/bundle\.js/,
  /.*\/__tests__\/.*/
];


Source: https://stackoverflow.com/questions/58120990/question-getting-error-on-react-native-start/58122821#58122821

**Comment by MagedYaseen** [comment]
Go to your Project Folder\node_modules\metro-config\src\defaults\blacklist.js
Change
var sharedBlacklist = [
  /node_modules[/\\]react[/\\]dist[/\\].*/,
  /website\/node_modules\/.*/,
  /heapCapture\/bundle\.js/,
  /.*\/__tests__\/.*/
];

TO

var sharedBlacklist = [
  /node_modules[\/\\]react[\/\\]dist[\/\\].*/,
  /website\/node_modules\/.*/,
  /heapCapture\/bundle\.js/,
  /.*\/__tests__\/.*/
];

It works fine now

**Comment by MagedYaseen** [comment]
Go to your Project Folder\node_modules\metro-config\src\defaults\blacklist

Get the changes from attached file:
[blacklist.txt](https://github.com/facebook/react-native/files/3807347/blacklist.txt)


UPDATE
I noticed that the editor here removes the (*) from the code, so I attached a file containing the code.
It works fine now

**Comment by sparda-65** [comment]
i had the same issue its work fine for me

**Comment by SrViny** [comment]
> Vá para a pasta do projeto \ node_modules \ metro-config \ src \ defaults \ blacklist
> 
> Obtenha as alterações do arquivo anexado:
> [blacklist.txt](https://github.com/facebook/react-native/files/3807347/blacklist.txt)
> 
> ATUALIZAÇÃO
> Observei que o editor aqui remove o (*) do código, então anexei um arquivo que contém o código.
> Funciona bem agora

**Comment by SrViny** [comment]
very good it works

**Comment by allenyoung1979** [comment]
Thank you; MagedYaseen; Works perfectly : )

**Comment by kpangba** [comment]
- Go to node_modules/metro-config/src/defaults/blacklist.js
- Replace your var sharedBlacklist to this

var sharedBlacklist = [
  /node_modules[\/\\]react[\/\\]dist[\/\\].*/,
  /website\/node_modules\/.*/,
  /heapCapture\/bundle\.js/,
  /.*\/__tests__\/.*/
];
