### ISSUE TITLE
NativeModules.SettingsManager.settings doesn't have AppleLocale field on iOS 13

### ISSUE THREAD

**Issue by grindos** [facebook/react-native#26606]
**React Native version:**
0.59.9

**iOS version on simulator:**
13.0

## Steps To Reproduce

1. Check the OS type.
2. If the OS type is not Android, try to get the locale.
3. Get the `NativeModules.SettingsManager.settings` object and take `AppleLocale` field from it.
4. Take only last two letters from the string to get the region name. E.g. for `en-US` will be returned `US`.

**Describe what you expected to happen:**
For iOS 12.2 and earlier the `NativeModules.SettingsManager.settings` object contained `AppleLocale` field, so everything worked correctly on the same React Native version. I expected that for iOS 13 it will work correctly too.

**Code example:**
```
  const locale = Platform.OS === 'android' ?
    NativeModules.I18nManager.localeIdentifier :
    NativeModules.SettingsManager.settings.AppleLocale;
  const localeLastChars = locale.slice(-2);
```

**Comment by grindos** [comment]
Also was mentioned in #26540

**Comment by bgold0** [comment]
This is also happening to me on react-native version `0.61.3`

**Comment by MrPingoo** [comment]
It's the same for me but I'm using expo

**Comment by MrPingoo** [comment]
I solved my problem with this https://docs.expo.io/versions/v34.0.0/sdk/localization/
And I used only Localization.locale

**Comment by sibelius** [comment]
try this

```jsx
const getDeviceLocale = () => {
  if (Platform.OS === 'ios') {
    let locale = NativeModules.SettingsManager.settings.AppleLocale // "fr_FR"
    if (locale === undefined) {
        // iOS 13 workaround, take first of AppleLanguages array  ["en", "en-NZ"]
        locale = NativeModules.SettingsManager.settings.AppleLanguages[0];
        if (locale) {
          return locale;
        }
    }
  }

  if (Platform.OS === 'android') {
    return NativeModules.I18nManager.localeIdentifier;
  }

  return 'pt-BR';
};
```

**Comment by secretgh** [comment]
@sibelius 
That code will come back with an error evaluating the t.proptypes

**Comment by grindos** [comment]
@secretgh @sibelius in fact, I'm using the same workaround at this moment and it works fine, but it would be great to have not a workaround solution, but make available `AppleLocale` at every moment. I don't think that iOS works without locale sometimes, especially if `AppleLanguages` is available
