### ISSUE TITLE
Status Bar Dark Content Not Working On iOS 13 Dark Mode

### ISSUE THREAD

**Issue by mronline** [facebook/react-native#26619]
React Native version: 0.60.0

## Steps To Reproduce

1. StatusBar.setBarStyle('dark-content'); // Not Working

**Comment by mokai** [comment]
+1

**Comment by mauricioblum** [comment]
Same here

**Comment by gpawlik** [comment]
As a workaround you could probably update the following keys in the `Info.plist` file, overriding the system dark mode:

````
<key>UIUserInterfaceStyle</key>
<string>Light</string>
<key>UIViewControllerBasedStatusBarAppearance</key>
<true/>
```

**Comment by mronline** [comment]
I've already added this: Dark mode disabled, but: status bar does not affect.
```
<key>UIUserInterfaceStyle</key>
<string>Light</string>
```

```
<key>UIViewControllerBasedStatusBarAppearance</key>
<true/>
```
And the problem is solved when I add it, but this time I get an error like this:
![Simulator Screen Shot - iPhone 11 Pro Max - 2019-09-27 at 21 11 12](https://user-images.githubusercontent.com/7905030/65792144-ce46af80-e16b-11e9-8353-8d2a1e51692b.png)

**Comment by elliotstokes** [comment]
This appears to be the same issue as this https://github.com/facebook/react-native/issues/26369

**Comment by mronline** [comment]
I solved the problem.

Apple has added a new constant to the status bar with the latest update, so dark-content doesn't work. (in dark-mode)

https://developer.apple.com/documentation/uikit/uistatusbarstyle?language=objc

New Constant: UIStatusBarStyleDarkContent - A dark status bar, intended for use on light backgrounds.

- Open XCode
- Search: RCTStatusBarManager.m
- Pods/Development Pods/React-Core/Modules/RCTStatusBarManager.m (xCode)

- Other Editor
node_modules/react-native/React/RCTStatusBarManager.m
```
RCT_ENUM_CONVERTER(UIStatusBarStyle, (@{
  @"default": @(UIStatusBarStyleDefault),
  @"light-content": @(UIStatusBarStyleLightContent),
  @"dark-content": @(UIStatusBarStyleDefault),
}), UIStatusBarStyleDefault, integerValue);
```

To Change:

```
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunguarded-availability"

RCT_ENUM_CONVERTER(UIStatusBarStyle, (@{
  @"default": @(UIStatusBarStyleDefault),
  @"light-content": @(UIStatusBarStyleLightContent),
  @"dark-content": (@available(iOS 13.0, *)) ? @(UIStatusBarStyleDarkContent) : @(UIStatusBarStyleDefault),
}), UIStatusBarStyleDefault, integerValue);

#pragma clang diagnostic pop
```

**Comment by cristianoccazinsp** [comment]
> #pragma clang diagnostic pop

Seems to work. Can we expect this to be pushed into RN anytime soon?

**Comment by suraneti** [comment]
@mronline's solution worked perfectly on **RN 0.59.9**

**Comment by tamago3keran** [comment]
@mronline's solution worked on **RN 0.59.2** :tada:

**Comment by cristianoccazinsp** [comment]
So not just an issue with RN 0.60? Hopefully it can be fixed for 59, 60 and 61 then... Monkey patching the xcode file is awful.

**Comment by wphestiraid** [comment]
I solved the problem with this commit.

https://github.com/facebook/react-native/commit/796b3a1f8823c87c9a066ea9c51244710dc0b9b5

**Comment by fonov** [comment]
for hot fixed react-native file can be used this package https://github.com/ds300/patch-package

**Comment by karaoak** [comment]
@wphestiraid You made my day! thank you 😃

**Comment by vladbars** [comment]
+1

**Comment by karaoak** [comment]
> +1

This has been fixed in RN 0.61.2 or can be patched as described above. I think this issue can be closed.

**Comment by divyanshunegi** [comment]
> #pragma clang diagnostic push
> #pragma clang diagnostic ignored "-Wunguarded-availability"
> 
> RCT_ENUM_CONVERTER(UIStatusBarStyle, (@{
>   @"default": @(UIStatusBarStyleDefault),
>   @"light-content": @(UIStatusBarStyleLightContent),
>   @"dark-content": (@available(iOS 13.0, *)) ? @(UIStatusBarStyleDarkContent) : @(UIStatusBarStyleDefault),
> }), UIStatusBarStyleDefault, integerValue);
> 
> #pragma clang diagnostic pop

Also please make sure you have this enabled in your `info.plist` file

```
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<true/>
```

and edit the code to this, so it supports the newest `13.1.2` as well.

```
RCT_ENUM_CONVERTER(UIStatusBarStyle, (@{
  @"default": @(UIStatusBarStyleDefault),
  @"light-content": @(UIStatusBarStyleLightContent),
  @"dark-content": (@available(iOS 13, *)) ? @(UIStatusBarStyleDarkContent) : @(UIStatusBarStyleDefault),
}), UIStatusBarStyleDefault, integerValue);

#pragma clang diagnostic pop
```

**Comment by fonov** [comment]
> Also please make sure you have this enabled in your info.plist file

It wrong no add this to info.plist otherwise you receive red box error.

**Comment by divyanshunegi** [comment]
@fonov I just did that and it works perfectly fine in my iOS 13 device and iOS 13.1.2 as well

**Comment by yuzhakovvv** [comment]
Actually `StatusBar.setBarStyle('dark-content');` worked for Expo SDK `v33.0.0` which is based on RN `0.59.8`. We had to use it as we can't do `pod install` in Expo

Source: expo/expo#3874

**Comment by mifi** [comment]
Note that now it seems that we need to explicitly set `StatusBar.setBarStyle('dark-content');` (in `index.js`?) to restore pre-0.61.2 behaviour. Before 0.61.2 it defaulted to dark-content when nothing was set.

**Comment by ortigozamatias** [comment]
We are using Expo SDK `v36.0.0` and this is still happening.

**Comment by xhirazi** [comment]
Successfully fixed this issue by making changes in info.plist describe [https://github.com/facebook/react-native/issues/26619#issuecomment-536019357](here) and changes in RCTStatusBarManager.m describe [https://github.com/facebook/react-native/issues/26619#issuecomment-536191518](here). 

credits goes  to @gpawlik & @mronline

**Comment by YesSkyscrapers** [comment]
> Successfully fixed this issue by making changes in info.plist describe [here](https://github.com/facebook/react-native/issues/26619#issuecomment-536019357) and changes in RCTStatusBarManager.m describe [here](https://github.com/facebook/react-native/issues/26619#issuecomment-536191518).
> 
> credits goes to @gpawlik & @mronline

It helped me a lot.
We're skipped modifying node_modules file, cuz in React-Native 0.61 its already fixed. 
And changed in Info.plist only 1 parameter:
`<key>UIViewControllerBasedStatusBarAppearance</key>
<string>NO</string>`
Cuz its throwing exception if use <false />

**Comment by anutting** [comment]
I'm running react-native 0.61.5 and am still seeing white content when I want it to be dark.
`<StatusBar translucent={true} backgroundColor='transparent' barStyle='dark-content'/>`

**Comment by MannySAD** [comment]
the changes @mronline suggest is very different from the lines of code in my RCTStatusBarManager.m file. My react native version is: 0.63.4, the string fixes mentioned by @gpawlik in info.plist result in the same red error OP has shown. Although the app does not crash it is still unpleasant to be told its wrong.
