### ISSUE TITLE
openDrawer not working 

### ISSUE THREAD

**Issue by MortezaHeydari97** [facebook/react-native#26617]
Hi. I'm trying to open the DrawerLayoutAndroid with this:

useEffect(() => {
    DrawerLayoutAndroid.prototype.openDrawer();
}. [])

But it's not working and says: ***"Cannot read property 'current' of undefined"*** :( 

Please help me, how can I open the drawer when the hamburger icon clicker.
**So thanks**

**Comment by octaviotastico** [comment]
I'm having the same issue :(
