### ISSUE TITLE
Console Line Number reports are missing

### ISSUE THREAD

**Issue by philipyun** [facebook/react-native#26634]
Any console.log/error/warn etc are not having their line numbers reported by the chrome dev console.  It does however show up in yellow and red boxes in the simulator. (not helpful for generic logs)

![image](https://user-images.githubusercontent.com/12608723/65828564-04aa2a80-e251-11e9-9cc2-52760719bda3.png)

React Native version:

System:
    OS: macOS Mojave 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 682.03 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
  IDEs:
    Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.1 => 0.61.1

## Steps To Reproduce

1. Open JS Debugger
2. console.log
3. look for line number

Describe what you expected to happen:

Snack, code example, screenshot, or link to a repository:

**Comment by ismetsezer** [comment]
you can use console._errorOriginal('log  is missing number') to provide its line, I've forked and trying to fix this problem. Thanks
