### ISSUE TITLE
StatusBar barStyle prop not working when force to light-mode activated on iOS 13 beta.

### ISSUE THREAD

**Issue by songzuyun** [facebook/react-native#26635]
Mobile phone's current mode is dark-mode，and I force settings light-mode by info.plist User Interface Style  with the value  "Light", but when I change StatusBar barStyle to 'default' and 'dark-mode' ,I still can't see the status bar.

**Comment by muhammaddadu** [comment]
@songzuyun did you manage to resolve this issue?
