### ISSUE TITLE
app not run in android simulator 

### ISSUE THREAD

**Issue by Bhagirath123** [facebook/react-native#26641]
i have create my first react native app and run that in to android simulator 
i have use this react-native run-android command for run app
then after display this " Jetifier found 914 file(s) to forward-jetify. Using 4 workers..."
then after nothing happens 

i am not found any error in my terminal 

this is my config :

react-native-cli: 2.0.1
react-native: 0.60.5
npm version : 6.11.2
node version : v10.16.3

React native info

System:
    OS: Linux 4.4 Ubuntu 16.04.5 LTS (Xenial Xerus)
    CPU: (4) x64 Intel(R) Core(TM) i3-4030U CPU @ 1.90GHz
    Memory: 720.95 MB / 7.71 GB
    Shell: 4.3.48 - /bin/bash
  Binaries:
    Node: 10.16.3 - /usr/bin/node
    npm: 6.11.2 - /usr/bin/npm
  IDEs:
    Android Studio: 3.4 AI-183.5429.30.34.5400832
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1

**Comment by Bhagirath123** [comment]
This is my react-native info

System:
    OS: Linux 4.4 Ubuntu 16.04.5 LTS (Xenial Xerus)
    CPU: (4) x64 Intel(R) Core(TM) i3-4030U CPU @ 1.90GHz
    Memory: 720.95 MB / 7.71 GB
    Shell: 4.3.48 - /bin/bash
  Binaries:
    Node: 10.16.3 - /usr/bin/node
    npm: 6.11.2 - /usr/bin/npm
  IDEs:
    Android Studio: 3.4 AI-183.5429.30.34.5400832
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1

**Comment by hyochan** [comment]
@Bhagirath123 Have you tried to open up your `android` project in `android-studio`? After `studio` builds success, you may try the script again.

**Comment by Bhagirath123** [comment]
i am fraser in react native so i don't no how to run react native project in android studio
can you explain step for run in android studio
