### ISSUE TITLE
Cannot not fetch android 10 react-native

### ISSUE THREAD

**Issue by khanhnn09** [facebook/react-native#26648]
System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz
    Memory: 56.67 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.3.0 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    Android SDK:
      API Levels: 25, 26, 27, 28, 29
      Build Tools: 26.0.3, 27.0.3, 28.0.3
      System Images: android-26 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom_64, android-26 | Google Play Intel x86 Atom, android-27 | Intel x86 Atom, android-27 | Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 10.1/10B61 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-rename: 2.4.0

I can't fetch on android but I use axios i see response has a spacing on first line:
example: " {check: true}", i checked postman and ios it normal. I think it issue I can't fetch on android. Please help me solve issue

**Comment by radko93** [comment]
Without code snippets and your response, we won't be able to help.  Also, look here https://github.com/facebook/react-native/issues/22375

**Comment by khanhnn09** [comment]
![android](https://user-images.githubusercontent.com/33776469/65868689-f1a76f80-e3a2-11e9-8014-6eb8403a9d41.jpg)

Image : error android when fetch response radko93
