### ISSUE TITLE
Android local release/debug works, play store version crashes

### ISSUE THREAD

**Issue by DanielJanke** [facebook/react-native#26657]
I've developed a react-native app and published it to the play store. After upgrading React Native to v0.60.5 and adding some features the updated version 1.1.0 stopped working.

While the local builds (debug/release) built in android studio are working, the uploaded app bundle available in play store is not.

The version downloaded in the play store stucks in the slash screen and isn't returning any feedback.

React Native version: 0.60.5

`adb logcat *:E` is throwing following lines:

```
09-30 17:40:33.025  1194  1253 E PackageManager: failed to find package com.brive_app
09-30 17:40:33.025  1194  1253 E OverlayManager: Failed to change enabled overlays for com.brive_app user 0

09-30 17:40:50.114 30740 30740 E com.brive_app: Not starting debugger since process cannot load the jdwp agent.

09-30 17:41:56.791 25572 25600 E s.nexuslaunche: Failed to open APK '/data/app/com.brive_app-6ENCGUCstJdR8hpsQylxaw==/base.apk' I/O error
09-30 17:41:56.791 25572 25600 E ResourcesManager: failed to add asset path /data/app/com.brive_app-6ENCGUCstJdR8hpsQylxaw==/base.apk
09-30 21:43:31.034  1194  1244 E ActivityManager: ANR in com.brive_app (com.brive_app/.MainActivity)
09-30 21:43:31.034  1194  1244 E ActivityManager: PID: 12998
09-30 21:43:31.034  1194  1244 E ActivityManager: Reason: Input dispatching timed out (Waiting because no window has focus but there is a focused application that may eventually add a window when it finishes starting up.)

```

What I did already 

- Clean the whole project
- Restarted everything

Used packages

```
   "@react-native-community/async-storage": "^1.6.1",
    "@react-native-community/netinfo": "^4.2.2",
    "@types/react-native-svg-charts": "^5.0.2",
    "@types/react-redux": "^7.1.2",
    "@types/redux-api-middleware": "^3.0.1",
    "interpolate-range": "^2.1.0",
    "moment": "^2.24.0",
    "react": "16.8.6",
    "react-native": "0.60.5",
    "react-native-background-fetch": "^2.7.0",
    "react-native-device-info": "^2.3.2",
    "react-native-iphone-x-helper": "^1.2.1",
    "react-native-keychain": "^3.1.3",
    "react-native-maps": "0.25.0",
    "react-native-modal": "^11.3.1",
    "react-native-navigation": "3.0.0-alpha.11",
    "react-native-svg": "^9.6.4",
    "react-native-svg-charts": "^5.3.0",
    "react-native-webview": "^6.9.0",
    "react-native-zendrive": "^1.0.2",
    "react-redux": "^7.1.0",
    "redux": "^4.0.4",
    "redux-api-middleware": "^3.0.1",
    "redux-persist": "^5.10.0",
    "redux-thunk": "^2.3.0",
    "string-format": "^2.0.0"
```

**Comment by usernameisrichin** [comment]
Did you find any fix for the above issue??

**Comment by DanielJanke** [comment]
@usernameisrichin No unfortunately not – I guess it could be related to the app signing progress. 
I discovered, that the hash value of the apk (downloaded in the play store) on my device

`/data/app/com.brive_app-4MOTQRqvfusy3yg3AzEgRA`
is not the same as the device is searching for:
`ResourcesManager: failed to add asset path /data/app/com.brive_app-6ENCGUCstJdR8hpsQylxaw==/base.apk`

**Comment by vipin-developer** [comment]
@DanielJanke did you resolve it? is that problem occurs with some specific mobile phones? in my case it is onePlus3T. Please let me know if you find any solutions.

**Comment by DanielJanke** [comment]
@vipin-developer No I couldn't resolve it, one workaround is to switch to APK instead of generating app bundles (AAB).

**Comment by gamingumar** [comment]
I am also facing the same issue.

**Comment by Nico924** [comment]
@DanielJanke I have the same issue with RN 0.60.6 and the only workaround I found is indeed to switch to APK.
Let me know if you find something else please.

I did not try with RN 0.61, maybe it is the solution.

**Comment by DanielJanke** [comment]
@Nico924 Good to know that I'm not the only person with this issue. Once I updated the React-Native version I will let you know!

**Comment by gamingumar** [comment]
I have tried with 0.61.1 and I still face the issue. @Nico924

**Comment by RichardLindhout** [comment]
@grabbou We have the same problem

**Comment by RichardLindhout** [comment]
Also on React Native 0.61.2, looks like it's working on Android 5 devices.

**Comment by RichardLindhout** [comment]
I'll share more details and crash logs tomorrow

**Comment by brunolemos** [comment]
Is that happening to all Android apps using react-native 0.60 or just the ones with Hermes enabled?

**Comment by RichardLindhout** [comment]
I have hermes enabled

**Comment by RichardLindhout** [comment]
Looks like the same issue!

**Comment by DanielJanke** [comment]
Ok than close this one and move over! 💡

**Comment by RichardLindhout** [comment]
![Schermafbeelding 2019-10-08 om 09 46 15](https://user-images.githubusercontent.com/6492229/66376723-8c5e0a80-e9b0-11e9-8172-834a26f6158a.png)

**Comment by RichardLindhout** [comment]
duplicate of: #26400

**Comment by Temirtator** [comment]
@RichardLindhout it is the same issue, where you commented to
