### ISSUE TITLE
invalid uri the format of the uri could not be determined

### ISSUE THREAD

**Issue by reshiDeveloper** [facebook/react-native#26650]
When I get response from server. It gives me this error:
invalid uri the format of the uri could not be determined

I must get https link in string format, but I cant get

**Comment by sauzy34** [comment]
Which component or method is returning this error?

**Comment by reshiDeveloper** [comment]
.

**Comment by cortinico** [comment]
Closing as 3 years old + it doesn't follow the issue template.
