### ISSUE TITLE
Pod install error "env: node: No such file or directory" and "Invalid `Podfile` file: A JSON text must at least contain two octets!."

### ISSUE THREAD

**Issue by krstffr** [facebook/react-native#26651]
When trying to create a new react-native project using `react-native init` I get the following error when running `pod install`:

```
env: node: No such file or directory

[!] Invalid `Podfile` file: A JSON text must at least contain two octets!.

 #  from /Users/kristoffer/rnt/ios/Podfile:42
 #  -------------------------------------------
 #
 >    use_native_modules!
 #  end
 #  -------------------------------------------`
```

Node is installed, running `node --version` yields `v10.16.3.` 
`cocoapods` is version 1.8.1.
`ruby` is version `ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]`

React Native version:
  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 3.21 GB / 16.00 GB
    Shell: Unknown - /usr/local/bin/fish
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
  IDEs:
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmGlobalPackages:
    react-native: 0.61.1

## Steps To Reproduce

1. `react-native init rnt`
2. `cd rnt`
3. `cd ios`
4. `pod install`

Describe what you expected to happen:

Pods should be installed without error.

Snack, code example, screenshot, or link to a repository:

<img width="759" alt="Skärmavbild 2019-09-30 kl  13 29 15" src="https://user-images.githubusercontent.com/93975/65874629-56080600-e386-11e9-8f3f-32e6409087bf.png">

**Comment by mutabazigakuba** [comment]
Any solutions. i have the same issue.

**Comment by krstffr** [comment]
Issue was that I had two different versions of Cocoa Pods installed, make sure you have the latest version only. 

Skickat från min iPhone
