### ISSUE TITLE
Build successful locally but when it opens the app it keeps on stopping

### ISSUE THREAD

**Issue by liljosi** [facebook/react-native#26658]
React Native version: 0.61.1

## Steps To Reproduce

1. upgrade to RN 0.60 >
2. migrate to androidx

Describe what you expected to happen:

for the app to start

**Comment by Khlyl** [comment]
لا يمكن لك طمس الحقيقة اريد محكمة جنايات دولية لأنك لص وهكر انت لست ضامن اجتماعي

الحصول على Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by builtbyproxy** [comment]
@liljosi Is this still an issue?
And whilst it seems dumb to ask could you confirm:
- this is happening with android? 
- On the simulator or device?
