### ISSUE TITLE
xCode  React (missing)

### ISSUE THREAD

**Issue by broros** [facebook/react-native#26665]
the new version of react native is giving me errors... 
when I check xCode edit scheme,  I get React (missing)

<img width="906" alt="Screenshot 2019-09-30 at 10 56 44 PM" src="https://user-images.githubusercontent.com/598228/65941644-63ea7500-e3e0-11e9-9c9c-20c85da2af08.png">

React Native version:
0.61.1

## Steps To Reproduce

1. react-native run-ios
2. 

Describe what you expected to happen: 

build ios emulator 

Snack, code example, screenshot, or link to a repository:

```
fatal error: 'React/RCTDefines.h' file not found
#import <React/RCTDefines.h>
```

**Comment by radko93** [comment]
Did you upgrade or create a new app? If you have upgraded you need to update your `Podfile` and run `pod install`

**Comment by Alaa-Ben** [comment]
+1, If you have upgraded, you need to `cd ios && pod install`.
Then go to the same screen (scheme/build), Delete the React (missing), click on the + on the bottom left, add React (from pods section). Finally, check all the checkboxes and place React at the top of the list.

**Comment by broros** [comment]
no luck,  something to do with this.

fatal error: 'React/RCTDefines.h' file not found
#import <React/RCTDefines.h>

**Comment by Alaa-Ben** [comment]
Did you add React to your podfile ?

**Comment by broros** [comment]
pod 'React', :path => '../node_modules/react-native/'

**Comment by broros** [comment]
does this need updating?

https://github.com/jonathanpalma/react-native-tesseract-ocr

**Comment by radko93** [comment]
@broros probably, I don't know

**Comment by radko93** [comment]
If you belevie this is an issue within React Native I will reopen this.

**Comment by ziyoshams** [comment]
This issue is related to missing React scheme #25838

**Comment by eddskt** [comment]
Same issue, some solution?

**Comment by austinthetaco** [comment]
I'm also having this issue. Any update?

**Comment by nihp** [comment]
I also have the same issue after upgrading react-native. Any quick solution for this?

**Comment by pedromelo98** [comment]
React Native 0.61 doesn't have React.xcodeproj, but library imports are still looking up to it, it's not a recommended solution but i just downgraded my react-native version at package.json from 0.61.5 to 0.60.0

**Comment by Farhadkm** [comment]
Here is what worked for me:
1. First make sure that your Podfile is same as the latest Podfile found here:
https://react-native-community.github.io/upgrade-helper/?from=0.60.6&to=0.61.5 
2. close xcode. 
3. do the cd ios/ && pod install
4. see if you can find the React in the pods installed.

**Comment by Alaa-Ben** [comment]
@JakeHadley Weird ! you shouldn't have to chose between those. In my case, I have "React" as a target (with the bullseye icon) in this list

**Comment by lenichols** [comment]
Same issue... there is no "React" in edit scheme and React is missing... 

<img width="414" alt="Screen Shot 2019-12-26 at 9 38 59 PM" src="https://user-images.githubusercontent.com/5247113/71503012-3b7be680-2828-11ea-9d33-217301f0c788.png">

**Comment by lisichka999** [comment]
Same issue, have no React library appear in this list like for @JakeHadley. please advise

**Comment by JakeHadley** [comment]
I ended up making a while new project. I couldn't get it to work.

**Comment by nihp** [comment]
I also created a new project and copied all my code thier.

**Comment by luatnd** [comment]
To sum up, 
If you're upgrading to react-native@0.61.x, you got **xCode React(missing)**, you got **'React/RCT<module>.h' file not found**

You should step by step to prevent redundant actions:
1. Check if XCode > Product > Schema > Edit Schema > Build has React(missing) or not
    - If React is present, then you continue to check header search path
    - If React is missing, try to delete it then add it back by pressing Plus sign
         - If you cannot found React in Pods > React after click plus sign. Please check your pod file if someone remove `pod 'React', :path => '../node_modules/react-native/'` from Pod, or they use `target.remove_from_project` to remove it on `post_install`
2. Look at your project dir >  Libraries: Depend on your library, some libraries were auto-linked so you don't need it here anymore, it causes React/RCT*.h not found. Trying to read the latest installation guide and you might remove it (not for all library, just some):
![image](https://user-images.githubusercontent.com/1859127/71714548-e69c2980-2e40-11ea-96df-43e7eed6e33c.png)

2. If the issue still exists, re-check your Pod file, some npm packages already did `auto-linking` if it has `.podspec` file in node_modules/foo/bar.podspec ==> Remove the package that supports auto-linking from Pod file
2. If the issue still exists, ensure to load your package only **ONCE**, via one of those methods: [`project dir >  Libraries`, `Pod file`, `auto-linking`]
   Normally, you can read the installation guide once more
2. If the issue still exists, Check headers search path like above quote sections
3. If the issue still exists, it's might be the library *.podspec or sth else, you need to investigate further.
4. If you write own your library, use `__has_include`
  ```
  #if __has_include(<React/RCTDefines.h>)
    #import <React/RCTDefines.h>
  #else
    #import "RCTDefines.h"
  #endif
  ```

That's how I solve the issue, do not mess your problem up

**Comment by qi0727** [comment]
i fixed this issue by going `System Preferences -> Security & Privacy`  . under `privacy` tab  allow xcode accessing my files and folders.

what actually happen is i upgrade my os to Catalina. somehow the access to files and folder right is not granted to xcode, hence xcode is not able to read the file and having this issue. 
hope it help.

<img width="665" alt="Screenshot 2020-01-08 at 2 36 11 pm" src="https://user-images.githubusercontent.com/32862453/71955791-3eada400-3224-11ea-94d4-fce567af925e.png">

**Comment by nihp** [comment]
I have React with concentric circles, not a React shape of house.

If I add this does it works for me?

**Comment by TERRUSS** [comment]
@nihp I'm in the same case, if you have an answer I would love to ear it 🤗

**Comment by nihp** [comment]
> @nihp I'm in the same case, if you have an answer I would love to ear it 🤗

It worked for me.

**Comment by TylerEikenberg** [comment]
> +1, If you have upgraded, you need to `cd ios && pod install`.
> Then go to the same screen (scheme/build), Delete the React (missing), click on the + on the bottom left, add React (from pods section). Finally, check all the checkboxes and place React at the top of the list.

Thank you for this comment, this helped me solve an error I've been having.

**Comment by aqibnaveed** [comment]
Using solution at no. 8 here -> https://github.com/facebook/react-native/issues/26665#issuecomment-571082076

I have encountered the following error.

73 duplicate symbols for architecture x86_64 clang: error: linker command failed with exit code 1 (use -v to see invocation)
