### ISSUE TITLE
Scrollview on Android does not call onMomentumScrollEnd when scrolled programmatically 

### ISSUE THREAD

**Issue by zomars** [facebook/react-native#26661]
This is a follow-up of #25672.

React Native version:

System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
    Memory: 37.81 MB / 16.00 GB
    Shell: 5.0.9 - /usr/local/bin/bash
  Binaries:
    Node: 8.15.0 - ~/.nvm/versions/node/v8.15.0/bin/node
    Yarn: 1.19.0 - /usr/local/bin/yarn
    npm: 6.11.3 - ~/.nvm/versions/node/v8.15.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 23, 25, 26, 28
      Build Tools: 23.0.1, 25.0.1, 26.0.1, 26.0.2, 28.0.1, 28.0.3
      System Images: android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.1 => 0.61.1
  npmGlobalPackages:
    react-native-cli: 2.0.1

## Steps To Reproduce

1. Call scrollTo({ x: something, y: something, animated: true})
2. Watch how on Android the `onMomentumScrollEnd` isn't being called, while in iOS works fine.

**Comment by jakubmas** [comment]
I faced same issue with the newest React Native. Any solutions?

**Comment by aravind1078** [comment]
same issue no workarounds as of now?

**Comment by Bardiamist** [comment]
I faced with it. Not only programmatically. I use horizontal FlatList. `onMomentumScrollEnd` very often not called if stop scroll with small velosity.

**Comment by jd20** [comment]
Can verify it's still happening in v0.61.5 on Android.

**Comment by varshan09** [comment]
Same issue on Android, is there any solution for it?

**Comment by djhr** [comment]
still happening on react-native v0.63.1

**Comment by scrapecoder** [comment]
confirm in React-native v0.63.0

**Comment by camazorro** [comment]
same on react-native v0.63.2

**Comment by amblicity** [comment]
still happening in react-native 0.63.3

**Comment by ajpaulingalls** [comment]
I have added a PR to address this.  If anyone here could test it or review it and comment on the PR, I'd love to get some momentum to help it get merged.  Thanks!

**Comment by anastely** [comment]
> I have added a PR to address this. If anyone here could test it or review it and comment on the PR, I'd love to get some momentum to help it get merged. Thanks!

How can I use Your PR in my current project to test it?

**Comment by ajpaulingalls** [comment]
> How can I use Your PR in my current project to test it?

I have a fork you could try, its based off 0.63.3.  The branch name is release/paul-v2.  

https://github.com/ajpaulingalls/react-native/tree/release/paul-v2

You can reference it in package.json like this:
```
    "react-native": "github:ajpaulingalls/react-native#release/paul-v2",
```

I would only use it for testing the fix while we wait for a possible merge.  Sadly there has been no momentum on that, so please help by upvoting the PR...

**Comment by anastely** [comment]
@ajpaulingalls sadly not work with me :\ still not triggered!

here's my code snippet if u want to see it or something
https://gist.github.com/anastely/0252cbe613bb0a5a6652fc498f0ce7d4

**Comment by ajpaulingalls** [comment]
> @ajpaulingalls sadly not work with me :\ still not triggered!
> 
> here's my code snippet if u want to see it or something
> https://gist.github.com/anastely/0252cbe613bb0a5a6652fc498f0ce7d4

Can you verify you have the actual changes?  Check for this file in your node_modules and validate it has the calls to `handleSmoothScrollMomentumEvents();`

https://github.com/ajpaulingalls/react-native/blob/release/paul-v2/ReactAndroid/src/main/java/com/facebook/react/views/scroll/ReactScrollViewManager.java

sometimes yarn/npm can be messy.  I have verified the change both in my code as well as the RNTester app (both in 0.63.3 fork as well as master) so I'm confident it works...

**Comment by anastely** [comment]
> > @ajpaulingalls sadly not work with me :\ still not triggered!
> > here's my code snippet if u want to see it or something
> > https://gist.github.com/anastely/0252cbe613bb0a5a6652fc498f0ce7d4
> 
> Can you verify you have the actual changes? Check for this file in your node_modules and validate it has the calls to `handleSmoothScrollMomentumEvents();`
> 
> https://github.com/ajpaulingalls/react-native/blob/release/paul-v2/ReactAndroid/src/main/java/com/facebook/react/views/scroll/ReactScrollViewManager.java
> 
> sometimes yarn/npm can be messy. I have verified the change both in my code as well as the RNTester app (both in 0.63.3 fork as well as master) so I'm confident it works...

Yes, Actually before I wrote my comment here, I have checked out your changes from the fork and it's existing in my node_modules!

I don't know why not work here!
Can u use my code (this gist) in a project with your fork to ensure if I miss anything?

**Comment by christophemenager** [comment]
Same for me, I tried to patch react-native with your PR diffs + directly use `github:ajpaulingalls/react-native#release/paul-v2` you repo, nothing worked for me, the `onMomentumScrollEnd` is still not triggered

**Comment by safaiyeh** [comment]
> > @ajpaulingalls sadly not work with me :\ still not triggered!
> > here's my code snippet if u want to see it or something
> > https://gist.github.com/anastely/0252cbe613bb0a5a6652fc498f0ce7d4
> 
> Can you verify you have the actual changes? Check for this file in your node_modules and validate it has the calls to `handleSmoothScrollMomentumEvents();`
> 
> https://github.com/ajpaulingalls/react-native/blob/release/paul-v2/ReactAndroid/src/main/java/com/facebook/react/views/scroll/ReactScrollViewManager.java
> 
> sometimes yarn/npm can be messy. I have verified the change both in my code as well as the RNTester app (both in 0.63.3 fork as well as master) so I'm confident it works...

Hey @ajpaulingalls thanks for working on this. Could you open this PR to the main repo so I can take a look at it?

**Comment by ajpaulingalls** [comment]
> Hey @ajpaulingalls thanks for working on this. Could you open this PR to the main repo so I can take a look at it?

Hi @safaiyeh which repo do you mean by main repo?  The PR is open against facebook:master.  You can view it here:

https://github.com/facebook/react-native/pull/30367

do you have a different repo in mind?

**Comment by ella33** [comment]
Confirm it still happens on react-native: 0.63.2.

**Comment by AlphaJuliettOmega** [comment]
Confirming it happens in react-native; 0.64.2

**Comment by IvKr95** [comment]
Confirming it happens in react-native 0.65.1

**Comment by olie-chan** [comment]
Appears to still be an issue in 0.66.3

**Comment by Inbal-Tish** [comment]
Still an issue on react-native `0.66.4`
