### ISSUE TITLE
[iOS] Gif image not showing when TintColor is set.

### ISSUE THREAD

**Issue by jinshin1013** [facebook/react-native#26664]
When setting `tintColor` on Gif image on iOS makes the gif image invisible.

React Native version:
react-native: 0.61.2
react: 16.9.0

## Steps To Reproduce

1. Create a fresh react native project: `react-native init project`
2. Put a gif image:
```tsx
<Image 
  source={require('path-to-gif-image.gif')} 
  style={{ tintColor: 'pink', width: 100, height: 100 }} 
/>
```

I didn't include the reproduction as it's simple to reproduce but let me know if required I can quickly mock one up.

Cheers guys.

**Comment by ganes1410** [comment]
@jinshin1013 
I tried to reproduce this (https://snack.expo.io/@ganes1410/ccf067). 
But in ios version of the snack, Both of the gifs are playing. Can you please check the above snack?

**Comment by jinshin1013** [comment]
Hi @ganes1410, Expo snack doesn't use the latest React Native. Here is the reproduction repo https://github.com/jinshin1013/rn-repro

**Comment by joepake** [comment]
I have the same issue. Seem tintColor only works on react native v0.60.x but not on v.0.61.x
