### ISSUE TITLE
PermissionsAndroid not prompted

### ISSUE THREAD

**Issue by DeciusAntiochus** [facebook/react-native#26667]
React Native version:
System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz
    Memory: 1.09 GB / 7.95 GB
  Binaries:
    Node: 8.12.0 - G:\Program Files\nodejs\node.EXE
    Yarn: 1.19.0 - G:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.4.1 - G:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 23, 27, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-28 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.1 => 0.61.1

## Steps To Reproduce

1. Use PermissionsAndroid as in official documentation.

```
 async requestCameraPermission() {
    try {
      const granted = await PermissionsAndroid.request(
        PermissionsAndroid.PERMISSIONS.CAMERA,
        {
          title: 'Cool Photo App Camera Permission',
          message:
            'Cool Photo App needs access to your camera ' +
            'so you can take awesome pictures.',
          buttonNeutral: 'Ask Me Later',
          buttonNegative: 'Cancel',
          buttonPositive: 'OK',
        },
      );
      if (granted === PermissionsAndroid.RESULTS.GRANTED) {
        console.log('You can use the camera');
      } else {
        console.log('Camera permission denied');
      }
    } catch (err) {
      console.warn(err);
    }
  }
```

2. "Camera permission is denied" is logged, as  permission is not being prompted by the application.

Describe what you expected to happen:

Camera permission should be prompted, as it does on a RN 0.59 other application I have.

**Comment by dulmandakh** [comment]
Did you listed the permission in the manifest file?

**Comment by DeciusAntiochus** [comment]
I tried (though it shouldn’t have any effect with RN 0.61.1/SDK28).

Didn’t help.

**Comment by DeciusAntiochus** [comment]
Does anyone have the same issue?
