### ISSUE TITLE
ld: library not found for -lRCTActionSheet

### ISSUE THREAD

**Issue by SkyPeer** [facebook/react-native#26679]
Hi guys!

After upgrading to the lates version RN and reinstall pods
i can't build project (iOS):

Error:
ld: library not found for -lRCTActionSheet
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Library not found for -lRCTActionSheet

React Native version:
OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
    Memory: 1.45 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    npm: 6.11.2 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
  IDEs:
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.1 => 0.61.1 
  npmGlobalPackages:
    react-native-cli: 2.0.1

I tried to create 'clean' project , and i had successful build, but i can't build My updated project.

Could you please tell me, what segments/params i need to change/update to fix that?

Thank you!

**Comment by radko93** [comment]
Please use [upgrade helper](https://react-native-community.github.io/upgrade-helper/) to figure out what you need to update. Probably you did not update your Podfile properly. If you have any other issues I can reopen this later on.
