### ISSUE TITLE
React-Native app is getting crashed with the following stacktrace

### ISSUE THREAD

**Issue by chaira19** [facebook/react-native#26670]
JSCRuntime.cpp | facebook::jsc::JSCRuntime | JSCRuntime() | 285
-- | -- | -- | --
memory | facebook::jsc | makeJSCRuntime() | 3078
JSCExecutorFactory.mm | facebook::react::JSCExecutorFactory | createJSExecutor(std::__1::shared_ptr<facebook::react::ExecutorDelegate>, std::__1::shared_ptr<facebook::react::MessageQueueThread>) | 20
NativeToJsBridge.cpp | facebook::react::NativeToJsBridge | NativeToJsBridge(facebook::react::JSExecutorFactory*, std::__1::shared_ptr<facebook::react::ModuleRegistry>, std::__1::shared_ptr<facebook::react::MessageQueueThread>, std::__1::shared_ptr<facebook::react::InstanceCallback>) | 93
memory | std::__1::__function::__func<facebook::react::Instance::initializeBridge(std::__1::unique_ptr<facebook::react::InstanceCallback, std::__1::default_delete<facebook::react::InstanceCallback> >, std::__1::shared_ptr<facebook::react::JSExecutorFactory>, std::__1::shared_ptr<facebook::react::MessageQueueThread>, std::__1::shared_ptr<facebook::react::ModuleRegistry>)::$_0, std::__1::allocator<facebook::react::Instance::initializeBridge(std::__1::unique_ptr<facebook::react::InstanceCallback, std::__1::default_delete<facebook::react::InstanceCallback> >, std::__1::shared_ptr<facebook::react::JSExecutorFactory>, std::__1::shared_ptr<facebook::react::MessageQueueThread>, std::__1::shared_ptr<facebook::react::ModuleRegistry>)::$_0>, void ()> | operator()() | 3078
RCTCxxUtils.mm | facebook::react | tryAndReturnError(std::__1::function<void ()> const&) | 72
RCTMessageThread.mm | facebook::react::RCTMessageThread | tryFunc(std::__1::function<void ()> const&) | 59
RCTMessageThread.mm | facebook::react::RCTMessageThread | runOnQueueSync(std::__1::function<void ()>&&) | 81
Instance.cpp | facebook::react::Instance | initializeBridge(std::__1::unique_ptr<facebook::react::InstanceCallback, std::__1::default_delete<facebook::react::InstanceCallback> >, std::__1::shared_ptr<facebook::react::JSExecutorFactory>, std::__1::shared_ptr<facebook::react::MessageQueueThread>, std::__1::shared_ptr<facebook::react::ModuleRegistry>) | 46
RCTCxxBridge.mm | RCTCxxBridge | _initializeBridgeLocked: | 569
RCTCxxBridge.mm | RCTCxxBridge | _initializeBridge: | 550
RCTCxxBridge.mm | RCTCxxBridge | start | 344
RCTCxxUtils.mm | facebook::react | tryAndReturnError(std::__1::function<void ()> const&) | 72
RCTCxxBridge.mm | RCTCxxBridge | _tryAndHandleError: | 257
RCTCxxBridge.mm | RCTCxxBridge | runRunLoop | 249

**Comment by radko93** [comment]
Please open another issue using the template.
