### ISSUE TITLE
Is it possible to add a image/text/view over a mapview?

### ISSUE THREAD

**Issue by phongyewtong** [facebook/react-native#2667]
Is it possible to add a image/text/view over a mapview?

**Comment by browniefed** [comment]
Yes, you would have to absolutely position it over the top of the view. 
Example: https://rnplay.org/apps/HFs2lQ

**Comment by phongyewtong** [comment]
Thanks you so much!

**Comment by dvcrn** [comment]
Can someone put the example up again? This is the only thing I found and still have difficulties with it
