### ISSUE TITLE
0.61.1 Android set borderRadius have no effect

### ISSUE THREAD

**Issue by aijason** [facebook/react-native#26676]
"react": "16.9.0",
"react-native": "0.61.1",
in IOS ok, in Android no effect

<View style={{
    width: 60,
    height: 60,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 5,
    backgroundColor: 'red'
  }}>
  <Text style={{fontSize: 14, color: 'white'}}>
Test
</Text>
</View>

**Comment by aijason** [comment]
"react": "16.9.0",
"react-native": "0.61.1",
in IOS ok, in Android no effect

<View style={{
    width: 60,
    height: 60,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 5,
    backgroundColor: 'red'
  }}>
  <Text style={{fontSize: 14, color: 'white'}}>
Test
</Text>
</View>

**Comment by andvm** [comment]
[https://github.com/facebook/react-native/issues/26627](url)

**Comment by radko93** [comment]
Duplicate of #26627

**Comment by aflahkp** [comment]
but #26627 is not fixed yet
