### ISSUE TITLE
Error when trying to launch debugger

### ISSUE THREAD

**Issue by BenjaminPcrd** [facebook/react-native#26675]
I shake my phone to open dev tools and I click on debug to open the debugger in firefox and then I have 2 errors:

TypeError: cannot use the given object as a weak map key index.delta:42125:11
Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)

Impossible to find a solution on others issues.

react-native info:
System:
&nbsp;&nbsp; OS: Linux 4.19 Debian GNU/Linux 10 (buster) 10 (buster)
&nbsp;&nbsp; CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
&nbsp;&nbsp; Memory: 1.48 GB / 7.68 GB
&nbsp;&nbsp; Shell: 5.0.3 - /bin/bash
&nbsp; Binaries:
&nbsp;&nbsp; Node: 10.15.2 - /usr/bin/node
&nbsp;&nbsp; npm: 5.8.0 - /usr/bin/npm
&nbsp; SDKs:
&nbsp;&nbsp; Android SDK:
&nbsp;&nbsp;&nbsp; API Levels: 23, 25, 28, 29
&nbsp;&nbsp;&nbsp; Build Tools: 28.0.3, 29.0.2
&nbsp;&nbsp;&nbsp; System Images: android-28 | Intel x86 Atom_64, android-29 | Intel x86 Atom_64
&nbsp; npmPackages:
&nbsp;&nbsp; react: 16.9.0 => 16.9.0 
&nbsp;&nbsp; react-native: 0.61.1 => 0.61.1 
&nbsp; npmGlobalPackages:
&nbsp;&nbsp; react-native-cli: 2.0.1

**Comment by radko93** [comment]
Do you get it on an empty app?

**Comment by BenjaminPcrd** [comment]
no, it works well on an empry app.
After creating a new project and installing all tha packages one by one, it seems that is `react-native-firebase` that is the problem. I do not have any error, just crashing when turning on debugger...

**Comment by radko93** [comment]
I think you should post this under their repo then. Maybe try using Chrome instead of Firefox.
