### ISSUE TITLE
using onKeyPress with TextInput disables value and onTextChange props

### ISSUE THREAD

**Issue by shannonjensen** [facebook/react-native#26686]
When I add an onKeyPress prop to my TextInput component the value and onTextChange prop are suddenly neutered and the component becomes uncontrolled.

React Native version:
React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
      Memory: 18.36 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.5.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.11.3 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    IDEs:
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.9 => 0.59.9
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-log-ios: 1.0.1

## Steps To Reproduce

 *I came across this bug while troubleshooting why onKeyPress was not working in my text input*

1. This code results in the input value staying static with the initial word (set with useState) while logging the user's typing, as it should:
```
<TextInput
        value={word}
        onChangeText={w => console.log(w)}
        style={styles.input}
        placeholder={'e.g. Rewarding, Busy, Frustrating'}
      />
```
2. This code results in an uncontrolled input component, logging nothing but changing the value according to the user's typing.
```
<TextInput
        value={word}
        onChangeText={w => console.log(w)}
        style={styles.input}
        placeholder={'e.g. Rewarding, Busy, Frustrating'}
        onKeyPress={e => console.log(e)}
      />
```

Describe what you expected to happen:

I expect to be able to have an onKeyPress prop without disabling my value and onTextChange props.

Snack, code example, screenshot, or link to a repository:

**Comment by radko93** [comment]
Can you provide an expo snack with latest RN? Without it we won't be able to fix it.
