### ISSUE TITLE
How the scrolling cursor handle is known while scrolling list in react-native flatlist

### ISSUE THREAD

**Issue by nihp** [facebook/react-native#26688]
How can I know the scrolling is in here. (i.e) can I know the scrolling offset in my list.

For Eg) I have a large number of items in Flatlist I have scrolled the screen and then how do I know the cursor is at this point

**Comment by nihp** [comment]
Issue not fixed yet

**Comment by hramos** [comment]
Please make sure to fill in the issue template.
