### ISSUE TITLE
[Android] Zoomed views in android. 

### ISSUE THREAD

**Issue by saketkumar** [facebook/react-native#26691]
Views are zoomed in Android devices sometimes. Happens on all the android devices. Killing the app solves the issues. 

React Native version: **0.60.5**

## Steps To Reproduce

1. Not sure how to reproduce it as it happens randomly. Killing the app fixes this problem though. I tried the case where changing the font size or display size by keeping the app in background. But no luck.

**Actual behaviour :** 
![issue1](https://user-images.githubusercontent.com/21558765/66068750-ccb22880-e56b-11e9-8936-22bf1be88fa4.png)
![issue2](https://user-images.githubusercontent.com/21558765/66068752-ccb22880-e56b-11e9-8c56-2d9a747ab4e4.png)

**Expected behaviour :** 
![original](https://user-images.githubusercontent.com/21558765/66068554-6d541880-e56b-11e9-8776-f2854ec20d86.png)

@cpojer any help regarding this?

**Comment by saketkumar** [comment]
Got reproduced and solved. Closing this.

**Comment by aliwaqar981** [comment]
@saketkumar  Getting same issue on react-native 0.63.3.
