### ISSUE TITLE
Component state is reset when AppState is inactive or background

### ISSUE THREAD

**Issue by andrewheekin** [facebook/react-native#26695]
The Component state is reset whenever AppState is `inactive` or `background`. I ran into this issue when users had entered their email address on a login screen then navigated away from the app to a 3rd party password manager.

React Native version:
0.59

## Steps To Reproduce

1. Modify some component state, a text input for example
2. Open another app or double tap the home button to view all open apps then return to the react native app and notice the component state has been cleared

## Describe what you expected to happen:
The component state will persist even though the AppState has changed to `inactive` or `background`

**Comment by radko93** [comment]
Can you provide an expo snack that proves that? Seems that your component is unmounted when you leave the app.

**Comment by andrewheekin** [comment]
@radko93 an external library was unmounting the component, good call
