### ISSUE TITLE
background Color not working with borderRadius after upgrading to 0.61.1

### ISSUE THREAD

**Issue by YazeedAsaad** [facebook/react-native#26703]
I've upgraded my project to the latest version and i noticed that there's a huge UI issues , after looking it turns out that using border radius hides any background color i've given my components

React Native version:0.61.1

## Steps To Reproduce

1.set backgroundColor and borderRadius to any view on Android

Describe what you expected to happen: works

Snack, code example, screenshot, or link to a repository:
http://prntscr.com/pe98sc without border radius (the yellow box)
http://prntscr.com/pe98zt with border radius , same as the "Add" button

**Comment by mareksl** [comment]
https://github.com/facebook/react-native/issues/26544

**Comment by aflahkp** [comment]
#26627

**Comment by aflahkp** [comment]
Too much UI Issues after the upgrade.

**Comment by radko93** [comment]
Please try upgrading to 0.61.2.

**Comment by YazeedAsaad** [comment]
> Please try upgrading to 0.61.2.

Fixed on .2
