### ISSUE TITLE
Calling synchronous methods on native modules is not supported in Chrome

### ISSUE THREAD

**Issue by i7soft** [facebook/react-native#26705]
Call the synchronized api, this appears:
![image](https://user-images.githubusercontent.com/10511797/66122212-b6f73e80-e611-11e9-8008-7db7c0ade12a.png)

React Native version:

React Native Environment Info:
    System:
      OS: macOS 10.14.6
      CPU: (4) x64 Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz
      Memory: 19.07 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.7.0 - /usr/local/bin/node
      Yarn: 1.3.2 - /usr/local/bin/yarn
      npm: 6.10.0 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
      Android SDK:
        API Levels: 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 7, 8, 9
        Build Tools: 22.0.1, 23.0.1, 28.0.0, 28.0.1, 28.0.2, 28.0.3, 29.0.0, 29.0.1, 29.0.2
        System Images: android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 11.0/11A420a - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.10 => 0.59.10 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-create-library: 3.1.2

## Steps To Reproduce

1.
2.

Describe what you expected to happen:

Snack, code example, screenshot, or link to a repository:

**Comment by i7soft** [comment]
@react-native-bot 

I have updated to the latest version, but I still have this error.

```
info Fetching system and libraries information...
System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz
    Memory: 30.93 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.7.0 - /usr/local/bin/node
    Yarn: 1.3.2 - /usr/local/bin/yarn
    npm: 6.10.0 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 7, 8, 9
      Build Tools: 22.0.1, 23.0.1, 28.0.0, 28.0.1, 28.0.2, 28.0.3, 29.0.0, 29.0.1, 29.0.2
      System Images: android-28 | Google APIs Intel x86 Atom
      Android NDK: 20.0.5594570
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.2 => 0.61.2 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-create-library: 3.1.2
    react-native-git-upgrade: 0.2.7
```

**Comment by zhigang1992** [comment]
imho, it should this be in  

https://github.com/react-native-community/react-native-device-info/issues/776

**Comment by i7soft** [comment]
@zhigang1992 the error string is from:
`/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js` line 186:
```
if (__DEV__) {
      invariant(
        global.nativeCallSyncHook,
        'Calling synchronous methods on native ' +
          'modules is not supported in Chrome.\n\n Consider providing alternative ' +
          'methods to expose this method in debug mode, e.g. by exposing constants ' +
          'ahead-of-time.',
      );
    }
```

**Comment by i7soft** [comment]
It seems that the api with the sync mark has this error.
ios: `RCT_EXPORT_BLOCKING_SYNCHRONOUS_METHOD`
android: `isBlockingSynchronousMethod=true`

**Comment by TheNoodleMoose** [comment]
@i7soft Did you ever find a solution for this problem? Currently experiencing this right now, and not being able to use a debugger is rough.

**Comment by i7soft** [comment]
@TheNoodleMoose no💔,i am waitting a solution

**Comment by TheNoodleMoose** [comment]
@i7soft Was react native the only thing you have updated? Ours was working after our React Native upgrade to the latest version, what broke it was a different package being upgraded. We used git bisect to find the culprit.

**Comment by i7soft** [comment]
@TheNoodleMoose i try this:
1. `react-native init demo`👈 the lastest version
2.add package "`react-native-device-info`" to the demo
3.add code to `App.js`:
```
import DeviceInfo from 'react-native-device-info';
console.log(DeviceInfo.isCameraPresentSync());👈 call a sync function
```
4.open debug mode
5.restart app,then show:
```
Invariant Violation: Calling synchronous methods on native modules is not supported in Chrome.

 Consider providing alternative methods to expose this method in debug mode, e.g. by exposing constants ahead-of-time.
```

**Comment by TheNoodleMoose** [comment]
@i7soft So since it seems to be the ```react-native-device-info``` package, I think they figured out the solution was to have a check for whether you: 1. Have a debugger or 2. Are in development mode. If either of those is present, then just mock the sync value. It's a shame but there was good reasoning behind it. Here is link discussing the solution: https://github.com/react-native-community/react-native-device-info/issues/776#issuecomment-533410011

**Comment by i7soft** [comment]
@TheNoodleMoose I use `react-native-device-info` just for example. In fact, I need to develop synchronous native features. I found that when debugging, I can't use the synchronous method. I don't know if it's my problem, or react native will improve this in the future.

**Comment by cjddny** [comment]
I also meet this problem, i can not find any method to debug when i use synchronous method

**Comment by KarlHerler** [comment]
Ran into this problem when upgrading to react native 0.62.0. Still present.

We are using `react-native-device-info` version 5.5.3.

**Comment by nechmads** [comment]
Same here. Removing calls to Appearance in version 0.62 solved it.
I reverted back to using expo/react-native-appearance package

**Comment by Johan-dutoit** [comment]
Can confirm that this happens with the Appearance API on the latest version (0.62)

**Comment by kelset** [comment]
hey folks, thanks for surfacing this issue - we are putting it in front of the team that worked on it so that they can help us understand how to get this fixed.

**Comment by couch4** [comment]
Still getting this, but in react-native-svg on Path.isPointInFill() method.

Unsure if it's a react-native-svg or react-native problem?

**Comment by kaushikwavhal** [comment]
Still facing this on v0.63.3, although temporarily commenting out the sync method works.

**Comment by luskin** [comment]
We are experiencing the same issue on 0.63.3

**Comment by nomi9995** [comment]
you can use this temporary solution https://stackoverflow.com/a/66583605/8079868

**Comment by madroneropaulo** [comment]
same here

**Comment by stdavis** [comment]
@kelset Did anything ever come from the team taking a look at this? I'm having the same issue attempting to debug with React Native Debugger.

**Comment by nomi9995** [comment]
@madroneropaulo @stdavis i made PR https://github.com/facebook/react-native/pull/31153 . but they closed PR by saying this is a feature. you have to patch react native like this https://stackoverflow.com/a/66583605/8079868

**Comment by stdavis** [comment]
@nomi9995 That patch from SO led to other errors for me.

**Comment by madroneropaulo** [comment]
@nomi9995 @stdavis I opened a new Issue, since I think the new one is related to the AuthRequest and not this one. https://github.com/expo/expo/issues/12712

**Comment by 29er** [comment]
why is this closed when it still occurs ?

**Comment by nomi9995** [comment]
@29er they will not handle this on chrome. you can see #31153. if you wanna run this on chrome then you can use patch https://stackoverflow.com/a/66583605/8079868

**Comment by deepakaggarwal7** [comment]
I'm getting this warning in the default ReactNative demo on running the application in debug mode (No dependencies added).

 ```
 },
  "dependencies": {
    "react": "17.0.2",
    "react-native": "0.65.1"
  },
  "devDependencies": {
    "@babel/core": "7.15.5",
    "@babel/runtime": "7.15.4",
    "@react-native-community/eslint-config": "2.0.0",
    "babel-jest": "26.6.3",
    "eslint": "7.14.0",
    "jest": "26.6.3",
    "metro-react-native-babel-preset": "0.66.0",
    "react-native-codegen": "^0.0.7",
    "react-test-renderer": "17.0.2"
  },
```

**Comment by betoharres** [comment]
@deepakaggarwal7  I have the same exact issue; I tried multiple solutions but no luck.

**Comment by betoharres** [comment]
@deepakaggarwal7 just created a new issue related to this with detailed info, feel free to comment there if you need

**Comment by zzeerak** [comment]
+1, facing the same. Would be great if someone can help. Unable to debug the app on iOS and android.

**Comment by alex-noel** [comment]
experiencing exact same issue. It only happened after transition to react-native 0.65.1
worked totally fine before that.
Tried to apply different solutions, but they all lead to some other issues.

**Comment by meshackjr** [comment]
> experiencing exact same issue. It only happened after transition to react-native 0.65.1
> worked totally fine before that.
> Tried to apply different solutions, but they all lead to some other issues.

1+ facing the same issue after just upgrading to 0.65.1

**Comment by 3KINGZ** [comment]
same issue on 0.65.1

**Comment by EHRdev** [comment]
Same issue on **0.65.1** please help us

**Comment by bhaktitud** [comment]
I'm facing the same issue, it happens when debug mode is active, please help!

`NativeUIManager.getConstantsForViewManager('Text') threw an exception. Invariant Violation: Calling synchronous methods on native modules is not supported in Chrome.

 Consider providing alternative methods to expose this method in debug mode, e.g. by exposing constants ahead-of-time. 
CountBadge@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.apolloxendit&modulesOnly=false&runModule=true:80660:35
RCTView
View
RCTView
View
TouchableWithoutFeedback@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.apolloxendit&modulesOnly=false&runModule=true:79148:36
LogBoxButton@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.apolloxendit&modulesOnly=false&runModule=true:80889:33
RCTView
View
LogBoxLogNotification@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.apolloxendit&modulesOnly=false&runModule=true:80587:25
RCTView
View
RCTView
View
_LogBoxNotificationContainer@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.apolloxendit&modulesOnly=false&runModule=true:80445:16
LogBoxStateSubscription@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.apolloxendit&modulesOnly=false&runModule=true:22856:38
RCTView
View
AppContainer@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.apolloxendit&modulesOnly=false&runModule=true:76863:36
RootComponentWithMeaningfulName@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.apolloxendit&modulesOnly=false&runModule=true:84232:24 index.bundle:20995:28`

**Comment by betoharres** [comment]
guys, please refer to this open issue:
https://github.com/facebook/react-native/issues/32197

it's better to report this on an open issue
