### ISSUE TITLE
[AlertIOS] [Idea] Allow omitting message entirely

### ISSUE THREAD

**Issue by grabbou** [facebook/react-native#2671]
So the following example does not throw:

```js
AlertIOS.alert('Are you sure?', [
   {text: 'Ok', onPress: logout}
]);
```

WDYT? It should be just a matter of checking if `message` is an array and reassigning that variable respectively.

**Comment by mkonicek** [comment]
I don't understand "omitting", in your example there's a message "Are you sure?". Why does it throw currently? What do you mean by "reassigning that variable"?

**Comment by grabbou** [comment]
@mkonicek it's actually a title, there's a second argument message that is optional but needs to be defined when an array of actions is passed.
