### ISSUE TITLE
assembleReleas does not work with hermes

### ISSUE THREAD

**Issue by valery-lavrik** [facebook/react-native#26717]
React Native version:
System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
    Memory: 1.72 GB / 7.49 GB
  Binaries:
    Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.7.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 23, 26, 28
      Build Tools: 28.0.3
      System Images: android-27 | Google Play Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom      
  IDEs:
    Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5791312
  npmPackages:
    react: 16.9.0 => 16.9.0 

## Steps To Reproduce
1 react-native init test
2 enableHermes -> true  (in build.gradle)
3 cd test/android
4 ./gradlew clean
5 ./gradlew assembleRelease

![image](https://user-images.githubusercontent.com/8047999/66200977-e60dbe80-e6aa-11e9-9d76-fec04346e795.png)

**Comment by shivaping** [comment]
Anyone looking into this for Windows ? Apparently, the workaround mentioned in the below link works but keen on getting proper version to integrate as we cannot put this workaround in the build and release process of jenkins.

https://medium.com/@mahyarfrd/add-hermes-to-react-native-0-60-5-9a9bea89c6e

**Comment by valery-lavrik** [comment]
@shivaping 
Not a single release with hermes has I earned on windows  yet
I think the developers do not pay attention to windows at all
