### ISSUE TITLE
The playback speed of gif images on Image component is too fast

### ISSUE THREAD

**Issue by mk0116** [facebook/react-native#26716]
React Native version:

## Steps To Reproduce

1. have gif url on Image component

Describe what you expected to happen:
Simply gif images are too fast on Image component with RN 0.61.2.
It was okay with 0.59.

Snack, code example, screenshot, or link to a repository:

**Comment by mk0116** [comment]
Just checked it works just fine on 0.60.6
So this must be an issued started from 0.61

**Comment by terrysahaidak** [comment]
@mk0116 Could you please add reproducing example, it will help a lot to debug and fix that bug.

**Comment by mk0116** [comment]
@terrysahaidak
It's really simple to reproduce.
Just set the gif http url on Image component and observe on iOS with RN 0.61.
I was not able to successfully launch the android app with 0.61 so I couldn't figure if it doesn't work on android as well.

**Comment by chelovekdrakon** [comment]
@mk0116 I have the same issue! straggling all day! Did you find any solutions?

@terrysahaidak here is the repro: https://github.com/chelovekdrakon/lottie-issue/tree/image-gif

I've started not from it <Image />, but from <LottieView />. 
Their animations are also going crazy after the upgrade of react-native.
Here is the repro: https://github.com/chelovekdrakon/lottie-issue/tree/lottie-animation

Looking forward to updates!

**Comment by mk0116** [comment]
@chelovekdrakon
I figured that the code for animating gif images has changed since 0.60.0
I guess the bug was made in this commit.

https://github.com/facebook/react-native/commit/3b67bfab1ed8f2a4cede4e58b41a8b11c63ab484#diff-e57b12f931820d7e0949e5cbb2701dcf

**Comment by WdBly** [comment]
same problem

**Comment by dingdongping** [comment]
same problem,How to solve

**Comment by octodhruv** [comment]
GIFs used with the Image component are now playing at double speed after our RN upgrade from .59 to .61 -> it seems like the logic for playing GIFs was updated. Are there any temporary workarounds to fix this, or can we leverage any external libraries to solve this problem?

**Comment by ericlewis** [comment]
There is a good chance this is caused by the component not replicating behavior from browsers. Currently, it relies on the GIF providing proper frame length data, but if the GIF doesn’t have that then it will appear to run quite quickly. The solution for this is to typically hack in a 100ms wait to the animation code which is similar to what Firefox does, for instance.

**Comment by surajj2223** [comment]
Facing the same issue on RN 0.61.5 :(

**Comment by amourya-systango** [comment]
Same problem on 0.61.5, Any solution ?

**Comment by y-sumanth** [comment]
Gif are not being played. Any setting I have to do in build.gradle. Please help.

**Comment by mk0116** [comment]
@y-sumanth You have to add these lines in build.gradle
implementation 'com.facebook.fresco:fresco:1.12.0'
implementation 'com.facebook.fresco:animated-gif:1.12.0'

**Comment by mk0116** [comment]
I found a workaround.
The problem is that the prop named 'kCGImagePropertyGIFUnclampedDelayTime' of the gif images have an empty value so that the delay is set as 0.

workaround:

Open RCTAnimatedImage.m and change line #106

from 
if (delayTimeUnclampedProp != nil){

to
if (delayTimeUnclampedProp != nil && [delayTimeUnclampedProp floatValue] != 0) {

I'll make a PR when I get a chance.

**Comment by FrederickEngelhardt** [comment]
Has this been fixed on iOS?

**Comment by ericlewis** [comment]
If I can find the time this weekend I will put in the proper fix.

**Comment by jpaulomotta** [comment]
I'm experiencing the same issue on iOS as of ```0.61``` with Expo ```v37.0.0```

**Comment by mouhanad-alaskari** [comment]
Same problem on IOS , any updates ?

**Comment by mk0116** [comment]
Closing this issue since it's fixed on 0.62.2
