### ISSUE TITLE
react-native template typescript doesn't copy the template directory

### ISSUE THREAD

**Issue by ipinlnd** [facebook/react-native#26727]
When creating a new react-native project with typescript as the template, it creates a `template` directory inside the project, but doesn't move the contents of that directory, in the root. So we would have a react-native directory without typescript, and then `template` directory inside it.

React Native version:
```
System:    
OS: Windows 10    
CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz 
Memory: 7.13 GB / 15.89 GB 
Binaries:
    Node: 10.16.0 - C:\Program Files\nodejs\node.EXE 
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD  
SDKs:  
    Android SDK: 
    API Levels: 23, 24, 25, 26, 27, 28, 29 
    Build Tools: 28.0.3, 29.0.0
    System Images: android-28 \| Google Play Intel x86 Atom  
IDEs:   
    Android Studio: Version  3.3.0.0 AI-182.5107.16.33.5199772
npmPackages:  
    react: 16.9.0 => 16.9.0  
    react-native: 0.61.2 => 0.61.2
--
```

## Steps To Reproduce

1. `react-native init PROJECT_NAME --template typescript`

Describe what you expected to happen:
Expected to have a project with typescript template. Should probably move the contents of template directory to the root directory and then do a `npm install` to install the new dependencies. 

## screenshot:
![image](https://user-images.githubusercontent.com/7761128/66252001-5e37bb00-e763-11e9-9d3a-09c67d2e68b9.png)

**Comment by fendorio** [comment]
Seeing this also.

**Comment by radko93** [comment]
You're using the wrong command for creating new project with the template. Please see https://github.com/react-native-community/react-native-template-typescript/blob/master/README.md#note-on-the-legacy-clip and if you have more issues open an issue there.

**Comment by ipinlnd** [comment]
@radko93 thanks
So this should probably be changed:
https://facebook.github.io/react-native/docs/0.60/typescript

**Comment by radko93** [comment]
@ipinlnd there's a PR but it's not merged
