### ISSUE TITLE
changes in node_modules not loading (react-native 0.61.1)

### ISSUE THREAD

**Issue by pbfrias17** [facebook/react-native#26720]
React Native version:
```
  System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
    Memory: 207.18 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.12.0 - ~/.nvm/versions/node/v11.12.0/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.7.0 - ~/.nvm/versions/node/v11.12.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28
      Build Tools: 23.0.1, 23.0.3, 25.0.0, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.2, 28.0.3
      System Images: android-23 | Intel x86 Atom_64, android-24 | Intel x86 Atom_64, android-24 | Google Play Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.1 => 0.61.1
  npmGlobalPackages:
    react-native-git-upgrade: 0.2.7
```

## Steps To Reproduce

1. Start packager and run app in simulator
2. Change any utilized code in node_modules
3. Restarting the packager doesn't load changed code (also tried clearing cache, re-installing app, re-installing watchman)

Describe what you expected to happen:
I expect the changes I made to node_modules to take effect when refreshing the app in the simulator. The same steps work expectedly on react-native 0.60

**Comment by hyochan** [comment]
Does this occurs in both platforms (ios & android)?

**Comment by HoogsterInc** [comment]
I think I have a similar problem - if I install any package then something happens and the code never refreshes to show the changes. The only thing that has worked for me when this happens is to restart my computer. From what I've seen on other threads about the code not changing after restarting the packager - clear watchman, reset the cache... or restart your comp. Clearing didn't work for me.
