### ISSUE TITLE
network request failed react native Expo

### ISSUE THREAD

**Issue by luiscuevasxd** [facebook/react-native#26721]
I have an error, I don't know what produces it or why it occurs

I have more code is why, it is test

![Screenshot_7](https://user-images.githubusercontent.com/32911975/66213346-32de9e80-e685-11e9-8677-5a2c6b5a7421.png)

import React, { Component } from 'react';
import {
    Platform,
    StyleSheet,
    Text,
    TextInput,
    Button,
    View,
    Image,
    ImageBackground,
    TouchableHighlight,
    Alert,
    AsyncStorage
} from 'react-native';
import * as Font from 'expo-font';
import { FontAwesomeIcon } from '@fortawesome/react-native-fontawesome';
import { faUser } from '@fortawesome/free-solid-svg-icons';
import { faLock } from '@fortawesome/free-solid-svg-icons';

class Login extends Component {
  constructor(props) {
    super(props);
      this.state = {
        loading: false,
        pressed: true,
        username: '',
        pass: '',
        url: 'http://192.168.1.2:80/webapp/api/login'
      }
    }

    componentDidMount(){
      this._loadInitialState().done();
    }

    _loadInitialState = async () => {
      var value = await AsyncStorage.getItem('user');
      if (value !== null) {
        this.props.navigation.navigate('Home');
      }
    }
    login = () => {
      let formData = new FormData();
      formData.append('Nom_Email_Tlf', this.username);
      formData.append('Pass', this.pass);
      fetch(this.url, {
        method: 'POST',
        headers: {
          'Accept': 'application/json',
          'Content-Type': 'applicaction/json',
        },
        body: formData
        /*body: JSON.stringify({
          username: this.state.username,
          pass: this.state.pass,
        })*/
      })
      .then((response) => response.json())
      .then ((res) => {
        if (res.success === true) {
          AsyncStorage.setItem('user', res.user);
          this.props.navigation.navigate('Home');
        }
        else {
          alert(res.message);
        }
      })
      .done()
    }
    chequearLogin = () => {
      const { username, pass } = this.state
      if( username == 'admin' || pass == 'admin '){
        this.props.navigation.navigate('Home', {
          name: this.username
        });
      }
      else{
        Alert.alert(
          'Error',
          'Usuario/Contraseña no coinciden',
          [
            {text: 'OK', onPress: () => console.log('OK Pressed')},
          ],
          {cancelable: false},
        );
      }
    }
    iniciarSesionPress = () => {
        this.props.navigation.navigate('Home', {
            name: 'Luis Cuevas'
        });
    }
    olvidarPassPress = () => {
        this.props.navigation.navigate('Home');
    }
    registroUsuarioPress = () => {
        this.props.navigation.navigate('RegistroUsuario');
    }
    registroTrabajadorPress = () => {
        this.props.navigation.navigate('Home');
    }
    render() {
      return (
        <View style={estilos.contenedor}>
          <ImageBackground
            source={require('../../../assets/img/body/01.png')}
            style={estilos.imgFondo}
          >
          <View style={{flex: 1, alignItems: 'center'}}>
            <View style={estilos.contLogo}>
              <Image 
                source={require('../../../assets/img/logo.png')}
                style={{ width: 300, height: 100, resizeMode: 'contain' }}
              /> 
            </View>
            <View style={ estilos.contForm }>
              <View style={ estilos.pForm }>
                <View style={estilos.row}>
                  <FontAwesomeIcon icon={ faUser } size={23} style={estilos.icono} />
                  <Text style={estilos.iconoRaya}></Text>
                    <TextInput
                      style={ estilos.input }
                      onChangeText={text => this.setState({ username: text })}
                      underlineColorAndroid = "transparent"
                      placeholder="Usuario"
                      placeholderTextColor='#818181'
                    />
                </View>
                <View style={estilos.row}>
                  <FontAwesomeIcon icon={ faLock } size={23} style={estilos.icono} />
                  <Text style={estilos.iconoRaya}></Text>
                    <TextInput
                      style={ estilos.input }
                      onChangeText={text => this.setState({ pass: text })}
                      secureTextEntry={true}
                      placeholder="Contraseña"
                      placeholderTextColor='#818181'
                    />
                </View>
                <Text style={{ color:'#4DAC33', marginBottom: 25, textAlign: 'center', fontSize: 12 }} onPress={this.olvidarPassPress}>¿Olvidó su contraseña?</Text>
                <View style={ estilos.btnSubmitContainer }>
                  <TouchableHighlight
                    onPress={this.login}
                    underlayColor={0}
                    style={[
                      estilos.btnEnviar,
                        this.state.pressed ? { backgroundColor: "#4DAC33" } : { backgroundColor: "#44A529" }
                      ]}
                    onHideUnderlay={() => {
                      this.setState({ pressed: false });
                    }}
                    onShowUnderlay={() => {
                      this.setState({ pressed: true });
                    }}
                  >
                    <Text style={ this.state.pressed ? estilos.noPress : estilos.Press }>
                      Entrar
                    </Text>
                  </TouchableHighlight>
                </View>
                  <View style={{ paddingVertical: 20}}>
                    <Text style={{ fontSize: 13, padding: 4, textAlign: 'center', color: '#545454' }}>¿No Eres Miembro? <Text style={{ color: '#f77e12', fontSize: 14, fontWeight: 'bold' }} onPress={this.registroUsuarioPress}>¡Registrate aquí!</Text></Text>
                    <Text style={{ fontSize: 13, padding: 4, textAlign: 'center', color: '#545454' }}>Perfil Para de Empresa <Text style={{ color: '#044d88', fontSize: 14, fontWeight: 'bold' }} onPress={this.registroTrabajadorPress}>Entrar aquí</Text></Text>
                  </View>
                </View>
              </View>
            </View>
          </ImageBackground>
        </View>
        )
    }
    
}

const estilos = StyleSheet.create({
  contenedor: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Platform.select({
      ios: '#F5FCFF',
      android: '#FAFDF5',
    }),
  },
  imgFondo: {
    width: '100%',
    height: '100%',
    resizeMode: 'contain'
  },
  contLogo: {
    width: '70%',
    flex: 1,
    justifyContent: 'flex-end',
    alignItems: 'center',
    //marginVertical: 80,
    paddingBottom: 30
  },
  contForm: {
    width: '78%',
    flex: 2,
    paddingVertical: 10,
  },
  pForm: {
    backgroundColor: '#FFFFFF',
    height: 'auto',
    width: '100%',
    borderRadius: 30,
    padding: 20,
  },
  input: {
    marginLeft: 30,
    color: "#000000",
    padding: 8,
    marginVertical: 5,
    marginLeft: 5,
    fontSize: 16,
    width: '68%',
    textAlign: 'center'
  },
  icono: {
    color: '#4DAC33',
    padding: 3,
    marginTop: 12,
    marginBottom: 3,
    marginHorizontal: 10,
    width: '30%'
  },
  iconoRaya: {
    borderRightColor: '#4DAC33',
    borderRightWidth: 2.4,
    borderStyle: 'solid',
    marginBottom: 7,
    width: '2%'
  },
  row: {
    flexDirection: 'row',
    width: '100%',
  },
  btnSubmitContainer: {
    marginTop: 2,
    width: '98%',
    alignSelf: 'center',
  },
  btnEnviar: {
    width: '100%',
    height: 35,
    borderRadius: 8,
  },
  Press: {
    color:'#F0F0F0',
    fontSize: 18,
    fontWeight: 'bold',
    marginTop: 5,
    textAlign: 'center',
  },
  noPress: {
    color:'#FFFFFF',
    fontSize: 18,
    fontWeight: 'bold',
    marginTop: 5,
    textAlign: 'center',
  },
});

export default Login;

**Comment by ramonvermeulen** [comment]
Getting exactly the same error when I use fetch() for POST requests (So with a body). GET requests are working fine for example.

**Comment by manjunathvustepalli** [comment]
Thanks for posting even i have the same issuse and i am strugling with it since few days but it works when we run in normal devices instead of emulator.

**Comment by ramonvermeulen** [comment]
> Thanks for posting even i have the same issuse and i am strugling with it since few days but it works when we run in normal devices instead of emulator.

It might be the debugger. Had some similar issues in the past, but when I turned my RN debugger off it all worked just fine.
