### ISSUE TITLE
Application has not been registered

### ISSUE THREAD

**Issue by longfay** [facebook/react-native#26724]
System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz
    Memory: 31.35 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.6.0 - ~/.nvm/versions/node/v10.6.0/bin/node
    Yarn: 1.7.0 - /usr/local/bin/yarn
    npm: 6.1.0 - ~/.nvm/versions/node/v10.6.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 23.0.1, 25.0.0, 25.0.2, 26.0.1, 26.0.2, 26.0.3, 27.0.2, 27.0.3, 28.0.0, 28.0.1, 28.0.2, 28.0.3
      System Images: a...google_apis | Google APIs Intel x86 Atom Sys...
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 10.1/10B61 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.60.0 => 0.60.0

I have this issue after upgrading react-native to 60.0.0, but I have my index.js in my project's root folder and its

import { AppRegistry } from 'react-native';
import InTow from './App';

AppRegistry.registerComponent('InTow', () => InTow);

and my app.json is 

{
  "name": "InTow",
  "displayName": "InTow"
}

Not sure why is this happen. Anyone could help?

Thanks!!!

![image](https://user-images.githubusercontent.com/13905071/66221187-77c1ff80-e69c-11e9-9e41-31305721f73c.png)

**Comment by radko93** [comment]
Did you change your app name?

**Comment by wenushkamallikarachchi** [comment]
Please check your index.android.bundle.and replace with your project name AppRegistry.registerComponent('PROJECTNAME',function(){return o.default})}

**Comment by radko93** [comment]
Closing this as there is no feedback.
