### ISSUE TITLE
App terminated in background when WebSocket is open

### ISSUE THREAD

**Issue by fonov** [facebook/react-native#26731]
#### I using WebSocket in my app when app move to background it terminated in short time, but I expect OS suspended app. Test on IOS 13.1.2 release mode

log from device

```
default	21:26:15.204466 +0300	SpringBoard	Firing exit handlers for 63390 with context <RBSProcessExitContext; specific: <RBSProcessExitStatus; domain: runningboard (15); code: 0x2182baad>; terminationContext: <RBSTerminateContext: 0x6000032f29c0; code: 0x2182BAAD; explanation: "Timed-out waiting for process [application<org.reactjs.native.example.test-bg>:63390] to invalidate assertion with identifier 4170-63390-4366 and explanation 'Shared Background Assertion 2 for org.reactjs.native.example.test-bg'. Direct this report to owners of that process"; reportType: 0; maxRole: 7; maxTerminationResistance: 3>>
default	21:26:15.207509 +0300	SpringBoard	[application<org.reactjs.native.example.test-bg>:63390]* Process exited: <RBSProcessExitContext; specific: <RBSProcessExitStatus; domain: runningboard (15); code: 0x2182baad>; terminationContext: <RBSTerminateContext: 0x6000032f29c0; code: 0x2182BAAD; explanation: "Timed-out waiting for process [application<org.reactjs.native.example.test-bg>:63390] to invalidate assertion with identifier 4170-63390-4366 and explanation 'Shared Background Assertion 2 for org.reactjs.native.example.test-bg'. Direct this report to owners of that process"; reportType: 0; maxRole: 7; maxTerminationResistance: 3>>.
default	21:26:15.207568 +0300	SpringBoard	[application<org.reactjs.native.example.test-bg>:63390]* Setting process task state to: Not Running
default	21:26:15.207611 +0300	SpringBoard	[application<org.reactjs.native.example.test-bg>:63390]* Setting process visibility to: Unknown
default	21:26:15.207704 +0300	SpringBoard	Removing: <FBApplicationProcess: 0x7feb8f7225d0; application<org.reactjs.native.example.test-bg>:63390>
default	21:26:15.207906 +0300	SpringBoard	Process exited: <FBApplicationProcess: 0x7feb8f7225d0; application<org.reactjs.native.example.test-bg>:63390> -> <RBSProcessExitContext; specific: <RBSProcessExitStatus; domain: runningboard (15); code: 0x2182baad>; terminationContext: <RBSTerminateContext: 0x6000032f29c0; code: 0x2182BAAD; explanation: "Timed-out waiting for process [application<org.reactjs.native.example.test-bg>:63390] to invalidate assertion with identifier 4170-63390-4366 and explanation 'Shared Background Assertion 2 for org.reactjs.native.example.test-bg'. Direct this report to owners of that process"; reportType: 0; maxRole: 7; maxTerminationResistance: 3>>
default	21:26:15.208345 +0300	SpringBoard	Application process state changed for org.reactjs.native.example.test-bg: (null)
```

full log https://github.com/fonov/rn-websocket/blob/master/device_log.txt

it look like socket can’t finished task and OS kill app

React Native version:
```
  IDEs:
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.2 => 0.61.2 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

## Steps To Reproduce

https://github.com/fonov/rn-websocket

i create fresh rn project and add this code

```
componentDidMount() {
    const ws = new WebSocket('wss://echo.websocket.org');

    ws.onopen = () => {
      ws.send('something');
    };

    ws.onmessage = e => {
      setTimeout(() => {
        ws.send('something');
      }, 1000);
    };

    ws.onerror = e => {
      // an error occurred
      console.warn(e.message);
    };

    ws.onclose = e => {
      // connection closed
      console.warn(e.code, e.reason);
    };
  }
```  

in `App.js`

1. clone repo 
1. run release app from the Home screen rather than from Xcode
1. go to home screen
1. wait a little bit and app is terminated

**Comment by radko93** [comment]
Without the websocket your app is not terminated?

**Comment by fonov** [comment]
yes of course, if delete code above with websocket from template project, app work perfect and system suspended app after inter to background

**Comment by fonov** [comment]
this app log without webSocket


```
12:59:35.680151 +0300	symptomsd	org.reactjs.native.example.test-bg: Foreground: false
12:59:35.742659 +0300	SpringBoard	[org.reactjs.native.example.test-bg] Snapshot data for <XBApplicationSnapshot: 0x15c3ae5e0; …8CDB0E0A8555> written to file:/1844D800-461F-4EB6-85F7-429D0C9CEE33/Library/SplashBoard/Snapshots/sceneID:org.reactjs.native.example.test-bg-default/41B54F8B-5CE6-49AF-B84B-8CDB0E0A8555@3x.ktx
12:59:35.745796 +0300	runningboardd	Invalidating assertion 905-936-1249 (target:application<org.reactjs.native.example.test-bg>) from originator 936
12:59:35.772201 +0300	SpringBoard	[org.reactjs.native.example.test-bg] Snapshot data for <XBApplicationSnapshot: 0x15c6aedf0; …AEC4721DB276> written to file:/1844D800-461F-4EB6-85F7-429D0C9CEE33/Library/SplashBoard/Snapshots/sceneID:org.reactjs.native.example.test-bg-default/downscaled/42109088-97A4-492F-8427-AEC4721DB276@3x.ktx
12:59:35.778613 +0300	runningboardd	Invalidating assertion 905-1403-1251 (target:application<org.reactjs.native.example.test-bg>) from originator 1403
12:59:35.780531 +0300	SpringBoard	[sceneID:org.reactjs.native.example.test-bg-default] Scene action [Logical Deactivate][0x41b0] completed with success: 1
12:59:35.781833 +0300	SpringBoard	[sceneID:org.reactjs.native.example.test-bg-default] Scene action [SceneLifecycleEventOnly][0x327e] completed with success: 1
12:59:35.781964 +0300	SpringBoard	[sceneID:org.reactjs.native.example.test-bg-default] Scene activity state did change: BackgroundInactive.
12:59:35.782291 +0300	runningboardd	Invalidating assertion 905-936-1250 (target:application<org.reactjs.native.example.test-bg>) from originator 936
12:59:35.852105 +0300	runningboardd	Removed last relative-start-date-defining assertion for process application<org.reactjs.native.example.test-bg>
12:59:35.853311 +0300	runningboardd	Calculated state for application<org.reactjs.native.example.test-bg>: running-suspended (role: None)
12:59:35.853592 +0300	runningboardd	[application<org.reactjs.native.example.test-bg>:1403] Suspending task.
12:59:35.854311 +0300	runningboardd	[application<org.reactjs.native.example.test-bg>:1403] Shutdown sockets (SVC)
12:59:35.854425 +0300	runningboardd	[application<org.reactjs.native.example.test-bg>:1403] Set darwin role to: None
12:59:35.854537 +0300	runningboardd	[application<org.reactjs.native.example.test-bg>:1403] Set GPU priority to "deny"
12:59:35.867537 +0300	SpringBoard	[application<org.reactjs.native.example.test-bg>:1403] Setting process task state to: Suspended
12:59:35.867647 +0300	SpringBoard	Application process state changed for org.reactjs.native.example.test-bg: <SBApplicationProcessState: 0x281a27760; pid: 1403; taskState: Suspended; visibility: Background>
```

in short time app 

```
Shutdown sockets (SVC)
```

and then 

```
Setting process task state to: Suspended
```

if look on log file with websocket (https://github.com/fonov/rn-websocket/blob/master/device_log.txt), you not found line with `Shutdown sockets (SVC)`

My suggestion app tried end socket but exceeds time limit on executed background task os and system terminated app

**Comment by radko93** [comment]
iOS will suspend your app and you cannot block it, I don't think it's react native issue then?

**Comment by fonov** [comment]
### I feel a misunderstanding of my issue.

**ios suspend app and it absolutely right, i expected this behavior, it part of app life cycle, after suspend app user may return to app and see the state he was in when he left the app, but terminated app is reset inner state**

### Normally change application life cycles

user open app, state changes from

`not running -> inactive -> active`

user make some work in app and go to home screen

`active -> inactive -> background -> suspended`

then user open app again and app move active state

`suspended -> background -> inactive -> active`

and **inner state** app not reset, user stay on screen when he stay last time

### With WebSocket change application life cycles

user open app, state changes from

`not running -> inactive -> active`

user make some work in app and go to home screen

`active -> inactive -> background -> not running (terminated)`

then user open app again

`not running -> inactive -> active`

**inner state** is lost

**Now if used WebSocket from react-native, app when going in background mode can't to complete task for a certain number of time and system terminated app and innner state reset**

**I expect when i use websocket in my app after hide app websoket finish tasks and app move to suspend mode and inner state not reset**

> I don't think it's react native issue then?

**it is react-native issue, because websocket is part of RN**

App-Based Life-Cycle Events
https://developer.apple.com/documentation/uikit/app_and_environment/managing_your_app_s_life_cycle?language=objc
<img src="https://docs-assets.developer.apple.com/published/c63cd35863/4d403429-fa30-4706-863f-5e3617ee21d0.png" width="400px">

**Comment by xiao99xiao** [comment]
Same here. **It is a react-native issue.**

**Comment by oleksandr-dziuban** [comment]
@xiao99xiao @fonov I have almost same issue: https://github.com/facebook/react-native/issues/26746

But I don't use Websockets. But app is crashing in sleep mode anyway on iOS 13.1.2

**Comment by oleksandr-dziuban** [comment]
@xiao99xiao @fonov @radko93 I have reproduced this even on fresh react-native app without any additional code!

Steps:
1) Use iOS 13.0 or 13.1 Simulator, Xcode 11.0 or 11.1
2) Generate fresh app: `react-native init TestApp`
3) Run iOS app in Simulator: `react-native run-ios --simulator="iPhone 11"`
4) Wait until application will be assembled and home screen activated
5) Click on Hardware Power Button on the right side in Simulator, device will activate sleep mode
6) Wait ~ 1 min and Unlock Simulator screen
7) Application will be crashed

**Comment by fonov** [comment]
> I have reproduced this even on fresh react-native app without any additional code! 

You test on product build? because debug build use websocket by default for downloading bundle

**Comment by oleksandr-dziuban** [comment]
@fonov Hi, yes, I have crashes on iOS 13.1.2 in production mode. I have added crash reports in my separate issue: https://github.com/facebook/react-native/issues/26746

**Comment by fonov** [comment]
@oleksandr-dziuban my app not terminated in background mode when i run without webSockets (iPhone XS Max iOS 13.1.2)

I found workaround for resolve problem with WebSocket

close ws on transaction in background mode and open again ws on move to foreground 

```
_handleAppStateChange = (nextAppState) => {
    if (this.appState === AppStateStatus.BACKGROUND && nextAppState === AppStateStatus.ACTIVE) {
      this.socket.open();
    }

    if (this.appState === AppStateStatus.INACTIVE && nextAppState === AppStateStatus.BACKGROUND) {
      this.socket.close();
    }

    this.appState = nextAppState;
  };
```

**Comment by oleksandr-dziuban** [comment]
I’m using GraphQL Apollo Client, maybe it is using websockets under the hood

**Comment by oleksandr-dziuban** [comment]
iOS 13.2 released, interesting is this issue still exists on it?

**Comment by radko93** [comment]
@xiao99xiao can you try this and report back? https://github.com/facebook/react-native/issues/26696#issuecomment-548056694

**Comment by xiao99xiao** [comment]
@radko93 Yes, that fix works.

**Comment by fonov** [comment]
fixed in https://github.com/facebook/react-native/commit/d7c9173b07171164bcadf73855454e90e07b31be

**Comment by vforvasile** [comment]
In my case, I didn't configure my iOS info.plist file correctly,

here's a [snippet](https://gist.github.com/vforvasile/f42d4256f2140bda4e6e0a7aa84c432c) that solved my issue in production.
