### ISSUE TITLE
Error while updating property 'flexDirection' in shadow node of type: RCTView

### ISSUE THREAD

**Issue by kiranAndr** [facebook/react-native#26734]
I'm using `borderStyle: 'dotted'` but getting the error like **Error while updating property 'borderStyle' in shadow node of type: RCTView**

React Native version:
0.60.4

![Capture](https://user-images.githubusercontent.com/15002093/66265561-644a9c00-e836-11e9-9299-3332ecd6c3aa.PNG)

**Comment by jeswinsimon** [comment]
Could you post a sample code to reproduce this issue?
