### ISSUE TITLE
couldn't find DSO to load: libhermes.so

### ISSUE THREAD

**Issue by courptwayne** [facebook/react-native#26738]
React Native version: 0.61.2
Xcode: 11
Android: 3.5.1

## Steps To Reproduce

1.
2.

Describe what you expected to happen:

Snack, code example, screenshot, or link to a repository:

**Comment by Relax594** [comment]
same but with `libreactnativejni.so`

**Comment by aa5279aa** [comment]
@Relax594  0.61.1 is also don't have libhermes.so,but 0.59.0 is fin
