### ISSUE TITLE
Fresh application react-native@0.61.2 error build in Xcode 11.0

### ISSUE THREAD

**Issue by oleksandr-dziuban** [facebook/react-native#26748]
Impossible to assemble a build in latest Xcode 11.0 with fresh application, react-native@0.61.2.
Xcode always shows "Failed Build error":
```bash
ld: library not found for -lDoubleConversion
clang: error: linker command failed with exit code 1 (use -v to see invocation)
``` 
With Xcode 10.2.1 everything worked fine.

React Native version:
```bash
System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz
    Memory: 105.80 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.4.0 - ~/.nvm/versions/node/v12.4.0/bin/node
    Yarn: 1.19.0 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v12.4.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28
      Build Tools: 23.0.1, 25.0.1, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.0, 28.0.3
      System Images: android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-25 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    @react-native-community/cli: 2.9.0 => 2.9.0 
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.2 => 0.61.2 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

## Steps To Reproduce

1. Generate fresh application with `react-native init TestApp`
2. Open this project in Xcode 11.0
3. Press build application
4. Always throws an error

Expected result:
Build assembled correctly.

**Comment by franckboudraa** [comment]
Same issue for me when building for device from Xcode.
When building to iOS simulator from Xcode I don't have the problem.

`ld: library not found for -lDoubleConversion
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

Xcode 11.0
react-native 0.60.5

**Comment by oleksandr-dziuban** [comment]
@franckboudraa Thanks to confirm.
Interesting that with CLI everything assembling correctly

**Comment by pabloluz** [comment]
Same as @franckboudraa here.

**Comment by pabloluz** [comment]
In my case, downgrading to Xcode 10.3 didn't resolve the issue.

**Comment by franckboudraa** [comment]
> In my case, downgrading to Xcode 10.3 didn't resolve the issue.

Have you tried to reinstall pods and clean the Xcode build cache ?

**Comment by pabloluz** [comment]
Hmm.. Not really. I'll try this out later today, thanks for the tip, Franck
;)

What I noticed was that I'm now able to run the project through
command line (but, of course, this is not enough if you need to sign and
publish it).

(Apart from that, it's not clear for me if is this a React or a Xcode
issue. I'd appreciate if someone could clarify it.)

**Comment by pabloluz** [comment]
> > In my case, downgrading to Xcode 10.3 didn't resolve the issue.
> 
> Have you tried to reinstall pods and clean the Xcode build cache ?

I tried to reinstall everything (all libraries I'm currently using) again (for the 3rd or 4th time), using a fresh RN project, cleaning up the caches, installing the pods and everything else... and now I'm able to build for both Android and iOS...

However, I still can't build using Xcode. Maybe later on today I'll try to upgrade again to Xcode 11 and build using it.

**Comment by oleksandr-dziuban** [comment]
@pabloluz Even with fresh generated rect native project we can't build project in Xcode. Reinstallation of everything doesn't help.
With CLI everything is working as usual

**Comment by pabloluz** [comment]
@oleksandr-dziuban @franckboudraa are any of you guys able to build and release sign your apps? If so, could you please tell me how? Via command line?

Thank you very much.

**Comment by oleksandr-dziuban** [comment]
I’m using Fastlane to sign, build and deploy apps

**Comment by franckboudraa** [comment]
@pabloluz Yes, on Xcode : select build for "Generic iOS device", then go to "Product > Archive".

On Android Studio : go to "Build > Generate signed bundle / APK".

**Comment by pabloluz** [comment]
.xcodeproj doesn't build, but when I tried using .xcworkspace file it worked. 
Thank you @franckboudraa, @oleksandr-dziuban.

Even though I'm now able to build and release-sign the app, the issue initially mentioned by @oleksandr-dziuban is still happening.

**Comment by pabloluz** [comment]
Hey guys, quick update: it's now working for me. If you are still interested in the topic, please check my comments out on this issue: https://github.com/facebook/react-native/issues/25546#issuecomment-545177371

Should you have any questions, feel free to ask me ;)

**Comment by oleksandr-dziuban** [comment]
Thanks @pabloluz 
I will close this issue as we have newest same issue with more comments.
