### ISSUE TITLE
Error installing React Native 

### ISSUE THREAD

**Issue by Brandon9502** [facebook/react-native#26747]
I've tried installing React Native, and installing homebrew, initiating a new project, and everytime im getting an error. I tried updating homebrew but it doesn't do anything. 
<img width="1115" alt="Screen Shot 2019-10-07 at 12 30 25 PM" src="https://user-images.githubusercontent.com/56052316/66342627-ba831200-e8fe-11e9-9cc5-30e3353e704d.png">
<img width="598" alt="Screen Shot 2019-10-07 at 12 30 43 PM" src="https://user-images.githubusercontent.com/56052316/66342630-bce56c00-e8fe-11e9-94c1-c679ed2b3ef6.png">

**Comment by stianjensen** [comment]
This seems to be a permission error with your .config folder. Try running `sudo chown -R $(whoami) ~/.config` to ensure this folder is owned by your current user, and not root.
