### ISSUE TITLE
An application bundle was not found at the provided path.

### ISSUE THREAD

**Issue by farimarwat** [facebook/react-native#26741]
The basic initialized project build and run on iPhone 11 simulator successfully using Xcode but 
gives this error while using the command (react-native run-ios --simulator="iPhone 11"

========================================
debug + DEST=/Users/admin/Library/Developer/Xcode/DerivedData/Build/Products/Debug-iphonesimulator/ctse.app
+ [[ Debug = *Debug* ]]
+ [[ ! iphonesimulator == *simulator ]]
+ [[ -n '' ]]

debug + case "$CONFIGURATION" in
+ [[ iphonesimulator == *simulator ]]
+ [[ -n '' ]]

debug + echo 'Skipping bundling in Debug for the Simulator (since the packager bundles for you). Use the FORCE_BUNDLING flag to change this behavior.'
Skipping bundling in Debug for the Simulator (since the packager bundles for you). Use the FORCE_BUNDLING flag to change this behavior.
+ exit 0

debug 

debug ** BUILD SUCCEEDED **

info Installing "DerivedData/Build/Products/Debug-iphonesimulator/ctse.app"
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist
error Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier DerivedData/Build/Products/Debug-iphonesimulator/ctse.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier DerivedData/Build/Products/Debug-iphonesimulator/ctse.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

    at checkExecSyncError (child_process.js:621:11)
    at Object.execFileSync (child_process.js:639:15)
    at runOnSimulator (/Users/admin/Documents/Projects/ctse/node_modules/@react-native-community/cli-platform-ios/build/commands/runIOS/index.js:174:45)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Command.handleAction (/Users/admin/Documents/Projects/ctse/node_modules/@react-native-community/cli/build/cliEntry.js:160:7)

My environment info
System:
    OS: macOS Mojave 10.14.6
    CPU: (2) x64 Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz
    Memory: 88.79 MB / 4.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.10.0 - /usr/local/bin/node
    Yarn: 1.19.0 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.2 => 0.61.2 
  npmGlobalPackages:
    react-native-cli: 2.0.1

**Comment by kbaxx** [comment]
still experiencing this isseu

**Comment by jerryheir** [comment]
Still experiencing this in 2021
