### ISSUE TITLE
[IOS] Iphone X+ overall performance is worth than other devices

### ISSUE THREAD

**Issue by mmamoyco** [facebook/react-native#26756]
## Description
We have RN application already in both stores with some base of users and we experience IphoneX performance issues. All runs smoothly on iphones 6,7,8 and Android, but IphoneX has some laggy behaviour. It's completely usable, but experience is worth than other devices. 

Lags are noticeable on transitions and application start.
For those who will say to look into navigation library or read performance documentation - We followed all guidelines of both RN and navigation library we using. No redundant updates,

I want to know, does somebody experience  the same issue? Or have some clues about this issue. This one really affecting quality of out product.

Thank you.

## React Native version:
System:
    OS: macOS 10.14.5
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 6.33 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-29 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
  npmPackages:
    react: ^16.8.6 => 16.8.6 
    react-native: ^0.59.8 => 0.59.8 

## Steps To Reproduce

1. Create two scenes using random navigation library
2. Test transition on Iphone X

**Comment by mmamoyco** [comment]
This issue exist from 0.56 version. In changelog i didn't noticed anything that can solve issue

**Comment by radko93** [comment]
Unfortunately, this is very general and since there are no other reports of similar behaviour. Personally I suggest that you try to use tools built to monitor performance/memory to check what's going in.
