### ISSUE TITLE
KeyboardAvoidingView styles don't compose nicely

### ISSUE THREAD

**Issue by garrettgu10** [facebook/react-native#26755]
https://github.com/facebook/react-native/blob/92073d4a71d50a1ed80cf9cb063a6144fcc8cf19/Libraries/Components/Keyboard/KeyboardAvoidingView.js

In the render function of KeyboardAvoidingView, the calculation of the styles of the container view are not calculated with regards to the given props.style. For example, on line 194, bottomHeight is used for the bottom style attribute rather than (bottomHeight + contentContainerStyle.bottom).

React Native version: 0.61

## Steps To Reproduce

1. Render a KeyboardAvoidingView with behavior "padding" and set the paddingBottom of its style. 
2. Toggle the keyboard. The paddingBottom attribute is reset.

Describe what you expected to happen:
I expect the extra keyboard padding to be added to the given paddingBottom rather than replace it. 

Snack, code example, screenshot, or link to a repository:
https://snack.expo.io/ryk4ftKOS
Notice that the bottom padding starts off being 20, but after toggling the keyboard, it is reset to 0.

**Comment by lunaleaps** [comment]
Line 194 is only for behavior "position", you'd want to update the appropriate "padding" handling in KeyboardAvoidingView.

**Comment by lunaleaps** [comment]
Added a comment on the attempted fix: #26948. I challenge whether this is a good idea and rather discourage styling KeyboardAvoidingView with paddingBottom, bottom values.
We should guide users to instead be styling an inner view. @garrettgu10, @jeswinsimon let me know if there's a use-case I'm not understanding.

**Comment by lunaleaps** [comment]
As discussed on #26948, let's update the docs to discourage padding/height styles on KeyboardAvoidingView. @garrettgu10 assigning this to you so we have a clear owner. Feel free to assign to me if you want to pass.
