### ISSUE TITLE
[Colors][Android] Using fractional rgb values causes an error

### ISSUE THREAD

**Issue by ide** [facebook/react-native#2675]
When you use Animated to animate from one color to another, it creates rgb() strings with fractional values. The Java side assumes the rgb values are always ints and calls Integer.parseInt on them -- which leads to a fatal when decimals are passed in. After thinking about the problem a bit, I think the right solution is for the native layer to be more robust and parseFloats that are then rounded at the last moment.

**Comment by andreicoman11** [comment]
We're changing the way color processing is done, and it will fix this issue along the way.

**Comment by bsansouci** [comment]
If you're working on this, it seems like `"rgba(0, 0, 0, 0.155)"` works but `"rgba(0, 0, 0, 0.1554)"` doesn't (4 digits). I'm not sure if it's even worth supporting though.

**Comment by cmrichards** [comment]
Until this is fixed, Is there another way to animate colours using react[android]?

**Comment by chirag04** [comment]
@ide is this still a problem? I think color processing moved to js.

**Comment by ide** [comment]
Haven't seen this problem with animated recently.
