### ISSUE TITLE
Android push is not working when app is in foreground

### ISSUE THREAD

**Issue by bony06aug** [facebook/react-native#26776]
React Native version:

## Steps To Reproduce

just integrated the FCM and launches the app.

Describe what you expected to happen:

It should receive a notification when app is in the foreground as well this.notifactionlistener should get called.

**Comment by stianjensen** [comment]
This doesn't seem like a react-native specific issue. All android apps need custom code to handle receiving FCM notifications in the foreground. Check out this article for a guide on integrating FCM in your react native app: https://medium.com/@anum.amin/react-native-integrating-push-notifications-using-fcm-349fff071591
