### ISSUE TITLE
[0.61.2] Keeps saying "JavaScript version: 0.59.5 vs Native 0.61.2"

### ISSUE THREAD

**Issue by guidolodetti** [facebook/react-native#26770]
After upgrading from RN 0.60.4 to RN 0.61.2, I keep getting an initial error screen telling me about a RN mismatch (JS 0.59.5 vs Native 0.61.2). I can't find any reference to RN 0.59 in my code, and I was previously using 0.60.4. Dismissing the error screen allows me to use the app.

<img width="487" alt="Screenshot 2019-10-08 at 21 35 27" src="https://user-images.githubusercontent.com/7063023/66427356-0c698c00-ea14-11e9-90df-d8b3f4f83132.png">

React Native version:
```
System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz
    Memory: 185.06 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
    Yarn: 1.3.2 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.0/bin/npm
    Watchman: 4.7.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 22, 23, 24, 25, 26, 27, 28
      Build Tools: 23.0.1, 24.0.2, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.3, 28.0.3
      System Images: android-26 | Google Play Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.2 => 0.61.2 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
```

## Steps To Reproduce
Upgraded from 0.60.4 to 0.61.2

Describe what you expected to happen:
No red error screen

Snack, code example, screenshot, or link to a repository:
<img width="487" alt="Screenshot 2019-10-08 at 21 35 27" src="https://user-images.githubusercontent.com/7063023/66427356-0c698c00-ea14-11e9-90df-d8b3f4f83132.png">

**Comment by Spencer-Yoder** [comment]
Have you 
1. Tried what it said to do in the error (deleting caches)
2. Delete node_modules and reinstall

**Comment by guidolodetti** [comment]
Uh yes, removing `node_modules` did the trick! Thanks @Spencer-Yoder
