### ISSUE TITLE
[Development][Android] Distribution over npm & linking with Gradle

### ISSUE THREAD

**Issue by ide** [facebook/react-native#2677]
It sounds like there is a lot of overhead to Maven. I thought about the process some more and I'm becoming more convinced that react-native should be distributed through npm and linked with Gradle/CocoaPods for a couple of reasons:

- Almost all current react-native developers download react-native from npm, either by manually specifying it in their own package.json file or using the react-native init script.
- When developing on both Android and iOS it's important to have the same copy of react-native for both platforms so that the application JS targets a consistent version of react-native.
- Several developers -- anyone who contributes back, in particular -- develop against their own forks of react-native and are often testing master or the RC with patches.
- Having a good process for publishing via npm and linking with Gradle/CocoaPods establishes a way for community-authored modules to be distributed. If someone writes a camera component, for example, they want to just publish the JS + Java + ObjC to npm instead three different package repositories.

**Comment by kmagiera** [comment]
@ide would be good to include into consideration the fact that RN for android depend on external libraries such as fresco, okhttp and android-jsc. That's not the case for iOS implementation so it's easy to just include whole framework code in npm bundle.
Do you think it would still be better if we only include rn java code in npm package but still use maven to pull in external dependencies?

**Comment by ide** [comment]
> Do you think it would still be better if we only include rn java code in npm package but still use maven to pull in external dependencies?

Yeah. That'd be a great first step and would solve most scenarios. The scenario that is not solved is when a contributor needs to modify fresco and react-native, but I think that is uncommon.

**Comment by chirag04** [comment]
@ide In that can he can compile :ReactAndroid project and give the path of reactAndroid src in settings.gradle. Not sure if i'm correct.

**Comment by kmagiera** [comment]
We'd also like to avoid requiring users to build :ReactAndroid from source. Note that it contains native code so not only android SDK is required to be setup but also android NDK would be. In our quick guide instructions we didn't included steps for setting up NDK as it's not required for the case when AAR is fetched through maven, although I assure you that NDK setup is painful and error prone and we should avoid making it a requirement. For iOS we don't have a choice and we need to compile from source but on the other hand the dev environment setup is as simple as installing Xcode

**Comment by ide** [comment]
@chirag04 yes, that's what I've been doing actually. I guess the two things I'd like are better launch performance and a solution for external native modules.

For launch performance there are a few things that could be improved:
- the Boost task is slow because there are a lot of files (known problem)
- look into Buck instead of Gradle -- there may be potential improvements
- loading the app onto the device takes a few seconds -- some poweruser instructions on how to use exopackage would solve this

**Comment by chirag04** [comment]
@kmagiera  I only meant that for power users who wants to play with RN source code.

@ide Interesting suggestions. Buck and exopackage could help. Will take a look later.

Should be document one way of publishing modules today and then revise it if we find a better way?
That one way being using the ``compile project(:Module)`` with npm.

**Comment by mkonicek** [comment]
The options that come to my mind are:
1. Ask people to publish the Java code to [JCenter](https://bintray.com/bintray/jcenter), it's pretty easy to do, users will need to update their build.gradle to fetch the code
2. Publish the Java source to for the module to npm along with JS
3. Publish a jar for the module to npm along with JS

In 2. and 3. we need to figure out a way to make Gradle look into `node_modules`.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/developmentandroid-distribution-over-npm-linking-with-gradle

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.

**Comment by mkonicek** [comment]
We don't use Maven anymore, yay! :)
