### ISSUE TITLE
Not getting all cookies in android react-native 0.60

### ISSUE THREAD

**Issue by wibes** [facebook/react-native#26781]
Not getting cookies in react native version 0.60 android. Solution here https://github.com/facebook/react-native/issues/18837#issuecomment-398779994 seems not to work in latest version

React Native version: 0.60

**Comment by pinstripe-potatohead** [comment]
This is a long standing issues ( See #21795 ), and will probably never get fixed. Facebook doesn't really care about fixing things which doesn't affect them.

**Comment by wibes** [comment]
Is there any temp solution for version 0.60 ?
