### ISSUE TITLE
Archive error IOS: library not found for -lReact

### ISSUE THREAD

**Issue by Luckygirlllll** [facebook/react-native#26785]
When I'm trying to make an archive via Xcode, I'm getting an error: `" library not found for -lReact"`. I have deleted Derived Data and clean the project, however, I'm still getting this error. 

React Native version:

 React Native Environment Info:
    System:
      OS: macOS 10.14.6
      CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
      Memory: 6.69 GB / 32.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
      Android SDK:
        API Levels: 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 25.0.0, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 27.0.1, 27.0.3, 28.0.3
        System Images: android-23 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom, android-25 | Google Play Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 11.0/11A420a - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.10 => 0.59.10 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-device-info: 2.0.0
      react-native-gesture-handler: 1.4.1
      react-native-git-upgrade: 0.2.7
      react-native-maps: 0.25.0
      react-native-reanimated: 1.2.0

## Steps To Reproduce

1. Create Archive for App Store

Describe what you expected to happen:
Can create archive  

Snack, code example, screenshot, or link to a repository:

**Comment by callcter** [comment]
same issue.
react-native 0.61.2

**Comment by wildcookie007** [comment]
Same issue here.
in Xcode workspace I can see linked RCT libraries under Libraries folder, however, none of the actual .xcodeproj files exist under `node_modules/react-native/Libraries` and they are not showing up red. They were automatically added when upgrading from .59 and now they are failing to build.

**Comment by Luckygirlllll** [comment]
I have fixed that problem by manually adding React to Libraries folder in Xcode and then adding it to `Build Phases -> Link binary with Libraries `

**Comment by wildcookie007** [comment]
Are you sure you are using RN 0.6 and higher? Because manual linking should not be a thing.

I was upgrading from RN 0.59 to 0.6x
I have solved this problem by getting rid of every framework inside the libraries folder (because the .xcodeproj files don't exist in the first place). That got my project up and running.

It seems that if you had linked any frameworks before - you have to let pods take care of integrating them. If the pods added references of those frameworks to the library folder then that I found is definitely the incorrect way to build.

**Comment by Luckygirlllll** [comment]
@wildcookie007 I'm using react-native 0.59.10, so manual linking still exists there.

**Comment by callcter** [comment]
i solved my problem when i upgraded to 0.61.2 from 0.59.5 #26812 
you can try to add react.xcodeproject to Library manually at 0.59.x

**Comment by SmartArray** [comment]
I have had the same issue when upgrading to RN 0.61.2.
Just remove the references from the 'Libraries' group and you should be fine as React, React-Core, etc. will be installed via Pods

**Comment by TheoGit** [comment]
@SmartArray so you removed all references from 'Libraries' and instead they should be added to the Podfile?
