### ISSUE TITLE
[Docs] Document the difference of opacity:0 between iOS and Android

### ISSUE THREAD

**Issue by ide** [facebook/react-native#2678]
iOS doesn't consume touches while Android does. https://facebook.github.io/react-native/docs/view.html#style would be a good place to document this. Currently the docblocks for the style properties don't seem to be rendered in the docs, so that's the first step.

**Comment by kmagiera** [comment]
@ide it's documented in "known issues" http://facebook.github.io/react-native/docs/known-issues.html#content
