### ISSUE TITLE
React-RCTCameraRoll Podspec missing in 0.61.2

### ISSUE THREAD

**Issue by brien-crean** [facebook/react-native#26792]
It's no longer possible to install the camera roll library via CocoaPods on 0.61.2. It looks like the `React-RCTCameraRoll.podspec` is missing in the latest release. It was previously present in 0.60.6. 

Podfile command:
`pod 'React-RCTCameraRoll', :path => '../node_modules/react-native/Libraries/CameraRoll'`

I included screenshots below of the `/node_modules/react-native/Libraries/CameraRoll/` directory. Both new projects created from scratch with `react-native init` - 0.60.6 on the left and 0.61.2 on the right.

![cameraroll](https://user-images.githubusercontent.com/11700939/66512462-dc5ecf00-ea8d-11e9-9603-6871c5684240.png)

React Native version:

System:
    OS: macOS Mojave 10.14.5
    CPU: (12) x64 Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
    Memory: 591.88 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash

  Binaries:
    Node: 8.4.0 - ~/.nvm/versions/node/v8.4.0/bin/node
    npm: 5.3.0 - ~/.nvm/versions/node/v8.4.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 24, 25, 26, 27, 28, 29
      Build Tools: 27.0.2, 28.0.3, 29.0.2
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.2 => 0.61.2
  npmGlobalPackages:
    react-native-cli: 2.0.1

## Steps To Reproduce

1. create a new project with `react-native init --version 0.61.2 <ProjectName>` 
2. open `/node_modules/react-native/Libraries/CameraRoll` directory and observe the podspec file is missing

Describe what you expected to happen:
Expected the following pod file command to install the camera roll library
`pod 'React-RCTCameraRoll', :path => '../node_modules/react-native/Libraries/CameraRoll'`

**Comment by Joyreece** [comment]
same issue~~

**Comment by brien-crean** [comment]
I just noticed the react-native-community repo [https://github.com/react-native-community/react-native-cameraroll](url) which provides the same API. I just installed it following their docs so closing this ticket

**Comment by action456789** [comment]
I have the same problem for react-native version 0.61.5, and `pod 'React-RCTCameraRoll', :path => '../node_modules/react-native/Libraries/CameraRoll'` not work for me

**Comment by th0r0nd0r** [comment]
I'm seeing the same issue on version 0.61.0

**Comment by adamsolomon1986** [comment]
any updates on this?

**Comment by chanphy** [comment]
I copy the file “RNCameraRoll.podspec”  from https://github.com/chanphy/react-native-cameraroll, and change its name to “React-RCTCameraRoll.podspec” and in the file, the same to change the s.name as "React-RCTCameraRoll" and 
package = JSON.parse(File.read(File.join(__dir__, "..", "..", "package.json"))).

then pod install....successfully and as the normal following:

Downloading dependencies
Installing GTMSessionFetcher 1.4.0 (was 1.3.1 and source changed to `https://cdn.cocoapods.org/` from `trunk`)
Installing RNCameraRoll (1.0.0-alpha2)
Installing React-RCTCameraRoll (0.62.2)
Generating Pods project
Integrating client project
Pod installation complete! There are 71 dependencies from the Podfile and 79 total pods installed.

hope you guys get it works.

**Comment by sundariragavan** [comment]
any updates on this?
