### ISSUE TITLE
[Android][TextInput] Bug when combine secureTextEntry + keyboardType props

### ISSUE THREAD

**Issue by retyui** [facebook/react-native#26799]
React Native version:
```
System:
    OS: Linux 4.15 Linux Mint 19.1 (Tessa)
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 5.34 GB / 15.51 GB
    Shell: 2.7.1 - /usr/bin/fish
  Binaries:
    Node: 10.16.3 - /usr/bin/node
    Yarn: 1.17.3 - ~/.yarn/bin/yarn
    npm: 6.11.3 - /usr/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.2 => 0.61.2 
  npmGlobalPackages:
    create-react-native-web-app: 0.1.14
    react-native-cli: 2.0.1
    react-native-create-library: 3.1.2

```

## Steps To Reproduce

1. Just use `secureTextEntry` +  `keyboardType`
```
<TextInput secureTextEntry keyboardType="email-address"/>
<TextInput secureTextEntry keyboardType="phone-pad"/>
```
2. Now you will see that on Android when `keyboardType` is `email-address` or `phone-pad` value visible for users.

![image](https://user-images.githubusercontent.com/4661784/66545269-fb6b6880-eb42-11e9-83b2-fe23574ec685.png)

![image](https://user-images.githubusercontent.com/4661784/66545266-f9090e80-eb42-11e9-96f6-abf3c80c863a.png)

Describe what you expected to happen:

Should work the same as iOS

Snack & code example:

https://snack.expo.io/@retyui/2793f1

## Links

- [keyboardType](https://facebook.github.io/react-native/docs/textinput#keyboardtype)
- [secureTextEntry](https://facebook.github.io/react-native/docs/textinput#securetextentry)

**Comment by retyui** [comment]
Up

**Comment by retyui** [comment]
bot stop it!

**Comment by retyui** [comment]
@stale о т в а л и

**Comment by fabriziobertoglio1987** [comment]
@retyui Please delete that comment. Had a friend of mine from Minsk.

**Comment by fabriziobertoglio1987** [comment]
https://github.com/facebook/react-native/blob/cfa42605989eee5a9de42bdb1259fb7f4d9451fb/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactTextInputManager.java#L710-L719

I'll fix this. Thanks

**Comment by fabriziobertoglio1987** [comment]
This is a limitation of the Android Sdk

They use [TYPE_CLASS_PHONE](https://developer.android.com/reference/android/text/InputType#TYPE_CLASS_PHONE) which `supports no variations or flags.`

while `INPUT_TYPE_KEYBOARD_NUMBER_PAD` supports flag [TYPE_NUMBER_VARIATION_PASSWORD](https://developer.android.com/reference/android/text/InputType#TYPE_NUMBER_VARIATION_PASSWORD)

https://github.com/facebook/react-native/blob/34ff9b7259e77f271c156bd75b837d4890ba9c81/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactTextInputManager.java#L747-L764

**Comment by retyui** [comment]
Игнор

**Comment by lpasquini** [comment]
Same problem, any workaround here?

**Comment by pagecow** [comment]
secureTextEntry={true} does not work for me on android. I can't believe this is an issue. Is there any way to block a password in a text input as the user is typing the password?

**Comment by retyui** [comment]
any progress?

**Comment by retyui** [comment]
any progress?

**Comment by NishitTibicle** [comment]
Come on guys ? this is not working in android do something for it

**Comment by retyui** [comment]
.

**Comment by shubhamguptadream11** [comment]
Hi @retyui,
After looking into the issue, it appears that the inability to mask text input when using keyboardType="phone-pad" with secureTextEntry is the default behavior on Android. The `InputType.TYPE_CLASS_PHONE` does not support secure text masking [[here](https://developer.android.com/reference/android/text/InputType#TYPE_CLASS_PHONE)], which is why the text remains visible. This is the expected behavior on Android and not specific to React Native.
