### ISSUE TITLE
RefreshControl not spinning/animating when app resumes

### ISSUE THREAD

**Issue by lapto** [facebook/react-native#26801]
## Info

When the RefreshControl component is active ( spinner visible and spinning) and the user move the app to the background. Then resume the app, the spinner is visible but not animating/spinning.

The bug only affect iOS. 
Tested and confirmed the bug on 0.59, 0.60 and 0.61  

## System Info
React Native version:
### System:
    OS: macOS Mojave 10.14.4
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 19.41 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
###  Binaries:
    Node: 8.11.3 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 5.6.0 - /usr/local/bin/npm
###  SDKs:
    iOS SDK:
      Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 21, 23, 24, 25, 26, 27, 28, 29
      Build Tools: 23.0.1, 25.0.0, 25.0.1, 25.0.2, 26.0.1, 26.0.2, 26.0.3, 27.0.2, 27.0.3, 28.0.0, 28.0.3, 29.0.0, 29.0.1, 29.0.2
      System Images: android-21 | Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-24 | Intel x86 Atom_64, android-24 | Google Play Intel x86 Atom, android-25 | Google APIs ARM 64 v8a, android-25 | Google Play Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom
###  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
 ### npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.2 => 0.61.2
 ### npmGlobalPackages:
    create-react-native-app: 1.0.0
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7

## Steps To Reproduce

1. create new project and replace App.js code with the code below
2. Pull to refresh
3. Move app to background (swipe up in simulator to enter the menu system)
4. Re-enter app -> stuck spinner

### Describe what you expected to happen:
Expect the spinner to continue animating when re-entering the app if its still visible

### Snack, code example, screenshot, or link to a repository:

```
import React from 'react';
import {
  ScrollView,
  RefreshControl,
  StyleSheet,
  Text,
  SafeAreaView,
} from 'react-native';

function wait(timeout) {
  return new Promise(resolve => {
    setTimeout(resolve, timeout);
  });
}

export default function App() {
  const [refreshing, setRefreshing] = React.useState(false);

  const onRefresh = React.useCallback(() => {
    setRefreshing(true);

    wait(10000).then(() => setRefreshing(false));
  }, [refreshing]);

  return (
    <SafeAreaView style={styles.container}>
      <ScrollView
        contentContainerStyle={styles.scrollView}
        refreshControl={
          <RefreshControl refreshing={refreshing} onRefresh={onRefresh} />
        }>
        <Text>Pull down to see RefreshControl indicator</Text>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    marginTop: 40,
  },
  scrollView: {
    flex: 1,
    backgroundColor: 'pink',
    alignItems: 'center',
    justifyContent: 'center',
  },
});

```

**Comment by zhongwuzw** [comment]
@lapto Hi, it's the Apple's default behavior. I may suggest you re-animate the RefreshControl by observing app state.

**Comment by lapto** [comment]
@zhongwuzw Hi, Thanks for the quick reply and suggestion.

I gave it a quick go, but it seems like since the animation is running native side there is some mismatch behavior. The code example below gives the right output (console.logs) but the spinner wont be visible when the app is resumed. 

```
render this.state.shouldRefresh: true
refreshing: true
currentAppState: inactive active
should hide spinner
render this.state.shouldRefresh: false
refreshing: true
currentAppState: background inactive
refreshing: true
currentAppState: active background
should show spinner
render this.state.shouldRefresh: true
```


```
import React, {Component} from 'react';
import {
  ScrollView,
  RefreshControl,
  StyleSheet,
  Text,
  SafeAreaView,
  AppState,
} from 'react-native';

export default class App extends Component {
  state = {refreshing: false, shouldRefresh: false};
  currentAppState = AppState.currentState;

  onRefresh = () => {
    this.setState({refreshing: true, shouldRefresh: true});
    setTimeout(() => {
      this.setState({refreshing: false, shouldRefresh: false});
    }, 10000);
  };

  componentDidMount() {
    AppState.addEventListener('change', this.handleAppStateChange);
  }

  componentWillUnmount() {
    AppState.removeEventListener('change', this.handleAppStateChange);
  }

  handleAppStateChange = nextAppState => {
    console.log('refreshing:', this.state.refreshing);
    console.log('currentAppState:', nextAppState, this.currentAppState);

    if (
      this.currentAppState.match(/inactive|background/) &&
      nextAppState === 'active'
    ) {
      if (this.state.refreshing) {
        console.log('should show spinner');

        this.setState({shouldRefresh: true});
      }
    } else if (
      nextAppState.match(/inactive|background/) &&
      this.currentAppState === 'active'
    ) {
      if (this.state.refreshing) {
        console.log('should hide spinner');

        this.setState({shouldRefresh: false});
      }
    }
    this.currentAppState = nextAppState;
  };

  render() {
    console.log('render this.state.shouldRefresh:', this.state.shouldRefresh);
    return (
      <SafeAreaView style={styles.container}>
        <ScrollView
          contentContainerStyle={styles.scrollView}
          refreshControl={
            <RefreshControl
              refreshing={this.state.shouldRefresh}
              onRefresh={this.onRefresh}
            />
          }>
          <Text>Pull down to see RefreshControl indicator</Text>
        </ScrollView>
      </SafeAreaView>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    marginTop: 40,
  },
  scrollView: {
    flex: 1,
    backgroundColor: 'pink',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```

**Comment by zhongwuzw** [comment]
@lapto You also need to adjust the `contentOffset` of `ScrollView`, because iOS only update the contentOffset when end refreshing, if we need to start refreshing, we need to update contentOffset programmatically.

https://stackoverflow.com/questions/14718850/uirefreshcontrol-beginrefreshing-not-working-when-uitableviewcontroller-is-ins/23766824

**Comment by lapto** [comment]
@zhongwuzw thanks for the follow up. Seems like setting contentOffset JS side didn't make the spinner visible. But forcing it to scroll to top without animation (even if it was on top when moving the app to the background).

The tradeoff is a bit painful, but incase anyone else hits the same issue, heres the updated code:
```
if (this.state.refreshing) {
handleAppStateChange = nextAppState => {
    console.log('refreshing:', this.state.refreshing);
    console.log('currentAppState:', nextAppState, this.currentAppState);

    if (
      this.currentAppState.match(/inactive|background/) &&
      nextAppState === 'active'
    ) {
      if (this.state.refreshing) {
        console.log('should show spinner');
        this.setState({shouldRefresh: true});
      }
    } else if (
      nextAppState.match(/inactive|background/) &&
      this.currentAppState === 'active'
    ) {
      if (this.state.refreshing) {
        console.log('should hide spinner');
        if (this.scrollViewRef) {
          this.scrollViewRef.scrollTo({y: 0, animated: false});
        }
        this.setState({shouldRefresh: false});
      }
    }
    this.currentAppState = nextAppState;
  };
```
