### ISSUE TITLE
React Native doesn't support newest Node (12.11.1)

### ISSUE THREAD

**Issue by Coruscate5** [facebook/react-native#26808]
React Native version: 0.61
(System:
    OS: Windows 10
    CPU: (16) x64 Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz
    Memory: 10.17 GB / 31.91 GB
  Binaries:
    Node: 12.11.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.11.3 - C:\Users\SOMEONE\AppData\Roaming\npm\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 19, 21, 22, 23, 24, 27, 28, 29
      Build Tools: 19.1.0, 21.1.2, 22.0.1, 23.0.1, 23.0.2, 23.0.3, 27.0.3, 28.0.3, 29.0.2
      System Images: android-19 | ARM EABI v7a, android-19 | Intel x86 Atom, android-23 | Google APIs ARM EABI v7a, android-23 | Google APIs Intel x86 Atom, android-24 | Android TV Intel x86 Atom, android-24 | Android Wear ARM EABI v7a, android-24 | Android Wear Intel x86 Atom, android-24 | ARM 64 v8a, android-24 | ARM EABI v7a, android-24 | Intel x86 Atom, android-24 | Intel x86 Atom_64, android-28 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom
      Android NDK: 17.1.4828580
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.2 => 0.61.2)

## Steps To Reproduce

1. Follow "Getting Started" guide to install latest Node version
2. Attempt to run "react-native run-android" on Windows using Emulator or physical device
3. Fails

Describe what you expected to happen:
Sample app works

Snack, code example, screenshot, or link to a repository:
Related issue here was closed prematurely by author: https://github.com/facebook/react-native/issues/26598

**Comment by NyauIf** [comment]
After some investigation i found the bug and already created a pull request for the Metro Bundler
https://github.com/facebook/metro/pull/464
hopefully this gets accepted soon.

**Comment by gluons** [comment]
Is it fixed? Can I safely upgrade my Node to 12?

**Comment by gluons** [comment]
Is it clearly fixed?

**Comment by oleksandr-dziuban** [comment]
@gluons @NyauIf  
Just update ``metro-react-native-babel-preset`` to latest ``0.59.0`` version and issue will be fixed.
I'm on latest ``NodeJS 12.18.0`` and react-native ``0.62.2``

**Comment by gnprice** [comment]
I believe this has been fixed and can be closed.

In addition to @oleksandr-dziuban 's report above: our project has been using Node 12 for some time, with RN v0.61.5, and we've seen no sign of problems related to the Node version.
