### ISSUE TITLE
Attempt to invoke virtual method 'double java.lang.Doubld.doubleValue()' on a null object reference

### ISSUE THREAD

**Issue by eventengineering** [facebook/react-native#26806]
This error message comes up masking the actual cause of the error behind it, making it very difficult to debug the actual issue.

![image](https://user-images.githubusercontent.com/12428462/66581457-02f93480-eb78-11e9-99df-b4b685797379.png)

React Native version:
System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 3.78 GB / 15.87 GB
  Binaries:
    Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 21, 22, 23, 24, 25, 26, 27, 28
      Build Tools: 27.0.3, 28.0.0, 28.0.1, 28.0.2, 28.0.3
      System Images: android-22 | Intel x86 Atom_64, android-25 | Android Wear ARM EABI v7a, android-25 | China version of Android Wear Intel x86 Atom, android-25 | Google APIs Intel x86 Atom, android-26 | Android Wear Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
      Android NDK: 20.0.5594570
  IDEs:
    Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5791312
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.1 => 0.61.1

## Steps To Reproduce

1. run any app with a null for a value somewhere

Describe what you expected to happen:
I expect there to be an error, but for it to highlight the location of the error rather than the location of this error.

Worth looking at the number of other bugs raised with this issue, each of which was caused by something not highlighted by this error:
#23378
#23193
#23126
#20727
#20549
#19423
#19413

**Comment by eventengineering** [comment]
Worth noting, this happens on Android but not on iOS

**Comment by danielmtavares** [comment]
We have this exact issue in production and it's impossible to tell what the actual error is.

**Comment by eventengineering** [comment]
That doesn't make this any less of a major bug.

Any bug in the bug handling area should be resolved ASAP as it makes handling and debugging of other bugs impossible.
