### ISSUE TITLE
Text overflows other element

### ISSUE THREAD

**Issue by acpardal** [facebook/react-native#26815]
After rotating 2x the tablet the text overflows other components.
It seems the bug occurs when using scrollview, view with flexDirection row, flexWrap wrap and text
![Screenshot 2019-10-11 at 09 34 12](https://user-images.githubusercontent.com/7581527/66638276-895f5600-ec0c-11e9-81ba-509580227ab8.png)

![giphy](https://user-images.githubusercontent.com/7581527/66638605-27ebb700-ec0d-11e9-9bb8-f67338e8f0cd.gif)

React Native version:

```
System:
    OS: macOS Mojave 10.14.5
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 527.30 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      Android NDK: 20.0.5594570
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.1 => 16.8.1 
    react-native: 0.61.2 => 0.61.2 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native: 0.61.2
```
## Steps To Reproduce
It happens either on smartphone or tablet, IOS or Android.
1. git clone https://github.com/acpardal/RNTextBug.git
2.
```
yarn && cd ios && pod install && cd .. && yarn ios --simulator 'iPad Pro (12.9-inch) (3rd generation)'
```

Describe what you expected to happen:
When returning to portrait it should be the same layout as first time.

**Comment by nikilarigela** [comment]
@acpardal  did you find any solution.

**Comment by acpardal** [comment]
@nikilarigela no not yet

**Comment by acpardal** [comment]
Still happening
