### ISSUE TITLE
/node_modules/react-native/Libraries/CameraRoll/RCTImagePickerManager.h:9: 'React/RCTBridgeModule.h' file not found

### ISSUE THREAD

**Issue by RyanMitchellWilson** [facebook/react-native#26819]
React Native version:

System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 1.22 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.10.0 - ~/.nvm/versions/node/v8.10.0/bin/node
    npm: 5.6.0 - ~/.nvm/versions/node/v8.10.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28, 29
      Build Tools: 26.0.2, 28.0.3, 29.0.1, 29.0.2
      System Images: android-24 | Google Play Intel x86 Atom, android-25 | Google Play Intel x86 Atom, android-26 | Intel x86 Atom, android-26 | Intel x86 Atom_64, android-26 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom_64, android-26 | Google Play Intel x86 Atom, android-27 | Intel x86 Atom, android-27 | Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64, android-29 | Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native: 0.60.5

## Steps To Reproduce

1. Follow the linking steps here https://facebook.github.io/react-native/docs/cameraroll.html
1. Add RCTCameraRoll.xcodeproj to libraries in my app.
1. Add libRCTCameraRoll.a to Build Phases -> Link Binary With Libraries
1. Try to build. Instantly fails with 'React/RCTBridgeModule.h' file not found

Describe what you expected to happen:

It should not fail.

Snack, code example, screenshot, or link to a repository:

`CameraRoll.saveToCameraRoll(url)`

**Comment by RyanMitchellWilson** [comment]
I tried to upgrade to 0.61.2 and they've removed cameraRoll entirely. So I installed the react-native-community version and had the exact same issue. So it looks both versions have the same issue.

**Comment by qyhongfan** [comment]
same issue~~

**Comment by shanghaikangshuai** [comment]
+1 ,and I do not know how to resolve for a few days

**Comment by zhijianzhang** [comment]
0.60.4 同样的问题

**Comment by zhijianzhang** [comment]
我在Podfile 添加    pod 'React-RCTCameraRoll', :path => '../node_modules/react-native/Libraries/CameraRoll' 执行 pod install 成功运行
