### ISSUE TITLE
running React Native how come it suddenly exits the shell or stops running but it works when building ????

### ISSUE THREAD

**Issue by iqbalnur323** [facebook/react-native#26822]
🚨 Please do not open a documentation issue in the core React Native repository. 🚨

The React Native website is hosted on a separate repository. You may let the
team know about any issues with the documentation by opening an issue there:
- https://github.com/facebook/react-native-website
- https://github.com/facebook/react-native-website/issues

**Comment by retyui** [comment]
dublicate https://github.com/facebook/react-native/issues/26823
