### ISSUE TITLE
running React Native how come it suddenly exits the shell or stops running but it works when building ????Docs:

### ISSUE THREAD

**Issue by iqbalnur323** [facebook/react-native#26823]
![Administrator_ Command Prompt 10_12_2019 9_29_31 AM_LI](https://user-images.githubusercontent.com/49528318/66693458-24226800-ecd3-11e9-8b7d-398d03c0c93e.jpg)

please help me ??

**Comment by retyui** [comment]
@iqbalnur323 

Af first for Android, you should run metro bandler

```sh
yarn start
# or
npm run start
```

`react-native run-android` - only build java code and then install an app
