### ISSUE TITLE
错误：程序包android.support.v4.view不存在

### ISSUE THREAD

**Issue by 1512751361** [facebook/react-native#26825]
React Native version:

## Steps To Reproduce

错误：程序包android.support.v4.view不存在
错误：程序包android.support.annotation不存在
错误：程序包android.support.v4.content不存在
react-native: 0.60.6
react: 16.9.6

Describe what you expected to happen:

Snack, code example, screenshot, or link to a repository:

**Comment by retyui** [comment]
@1512751361 

Run once: 

```sh
npx jetify
```

**Comment by Duringzha** [comment]
npx jetify
npx cap sync
