### ISSUE TITLE
React-native start has erorr and my first project can not start

### ISSUE THREAD

**Issue by momozizi** [facebook/react-native#26829]
i have some problem:
`react-native start` has error

    Invalid regular expression

and after running `react-native run-android` my android device show me

    unable to load script. make sure you...

then I tried to run `choco unistall nodejs` and run `choco install nodejs-lts` but `react-native start` has that error). so I run `react-native info` and result is:

    info Fetching system and libraries information...
    System:
    OS: Windows 7
    CPU: (8) x64 Intel(R) Core(TM) i7 CPU Q 740 @ 1.73GHz
    Memory: 925.38 MB / 3.98 GB
    Binaries:
    Node: 12.11.1 - C:\Program Files\nodejs\node.EXE
    npm: 6.11.3 - C:\Program Files\nodejs\npm.CMD
    SDKs:
    Android SDK:
    API Levels: 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29
    Build Tools: 25.0.0, 25.0.3, 26.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.
    1, 28.0.2, 28.0.3, 29.0.1, 29.0.2
    System Images: android-25 | Google APIs Intel x86 Atom, android-28 | Googl
    e APIs Intel x86 Atom_64
    npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.2 => 0.61.2

I could not find my answer.

**Comment by NyauIf** [comment]
Hey in this #26598 issue the same error message occurs but switching to the node-lts version fixed it. Are you sure you have the Node LTS 10.16.3 version installed ? i am asking because in the given info from you stands "`Node: 12.11.1.`" You can check your Node version easy with `node -v`

**Comment by FLGMwt** [comment]
As mentioned in https://github.com/facebook/react-native/issues/26598#issuecomment-546520915, you should be able to fix this by using node version 12.9.1 or earlier.

**Comment by cpojer** [comment]
Thank you for your report. We fixed this just now with the release of Metro 0.56.4 and 0.57.0. Update your packages and re-create your project and things should work for you again :) Sorry for the inconvenience.
