### ISSUE TITLE
[Android][Linux] Replace launchChromeDevTools.applescript for Linux

### ISSUE THREAD

**Issue by ChristianHersevoort** [facebook/react-native#2684]
Launching the Chrome DevTools from Android doesn't work on Linux because it requires applescript. 

The launchChromeDevTools.applescript should be replaced by something cross-platform like bash.

I know that Linux isn't officially supported, but it works for the most part. :smile:  (I just tested the tutorial and live-reloading)

**Comment by kmagiera** [comment]
Thanks @ChristianHersevoort. We have a couple of people internally that use it on Linux. We prioritize smooth user experience with setting up sample project. Except from a couple of places where we use shell scripts it works fine on both linux and windows. Feel free to send PR, I'll leave this issue open

**Comment by frantic** [comment]
There is a PR open #2406. @ChristianHersevoort could you please take a look and check if it works for you?

**Comment by kmagiera** [comment]
#2406 only fixes applescript use to launch chrome devtools, there is another one we use in `react-native run-android` command that we use to start packager in new terminal window.

**Comment by ChristianHersevoort** [comment]
@frantic It works!
![react-native-android linux](https://cloud.githubusercontent.com/assets/136455/9863514/1056186c-5b41-11e5-9ffc-41e2ac79aa84.png)

I only had too rebase it and change it to use chromium!

**Comment by kmagiera** [comment]
Merging to master linux support task #2693
