### ISSUE TITLE
ReactNative 0.61.2 Issue

### ISSUE THREAD

**Issue by omurburuk** [facebook/react-native#26844]
Hi,I upgrade 0.55.3 to 0.61.2 react-native version. I have an issue that is script version 0.55.3 and react native version 0.61.2 on android 9 device.

React Native version: 0.61.2

**Comment by mmahdigh** [comment]
Have you tried deleting node modules and doing `npm install` again?
If it didn't work, check `react-native start --reset-cache`
If the error didn't go away then seeing your `package.json` and `build.gradle` would be helpful.

**Comment by Shaghlaty** [comment]
react-native start --reset-cache don't work with me its finish bundle but  the app didnt start at all
