### ISSUE TITLE
Touchable should be selectable but is not when using top or marginTop

### ISSUE THREAD

**Issue by haveamission** [facebook/react-native#26859]
When using top or marginTop, touchables do not work on Android

React Native version:
.61

## Steps To Reproduce

1. Create a touchable
2. Use sufficient marginTop or Top to move it below (perhaps outside of the view?)

Describe what you expected to happen:

Touchable should be selectable

**Comment by Asad-Comm** [comment]
Touchables donot support selectable property, only text elements do.
