### ISSUE TITLE
RN 0.61.2 Picker component displays only dropdown picker. Dialog box is not working.

### ISSUE THREAD

**Issue by ahuseyn** [facebook/react-native#26854]
Hello, Picker component dialog mode doesn't work.

**Comment by aithashi** [comment]
+1, Same issue (Currently in RN 0.60.5)

**Comment by hramos** [comment]
Please make sure to fill in the issue template if you decide to file a new issue.

**Comment by aithashi** [comment]
> +1, Same issue (Currently RN 0.60.5)



> +1, Same issue (Currently RN 0.60.5)

Now works fine with both mode in the mentioned version. Thanks

**Comment by aithashi** [comment]
_> +1, Same issue (Currently RN 0.60.5)_

**Now works fine with both mode in the mentioned version. Thanks**
