### ISSUE TITLE
[iOS] Undefined symbols for architecture arm64: "_RCTSetLogFunction"

### ISSUE THREAD

**Issue by Javanaise** [facebook/react-native#2685]
Hello,
I have this linking error:
Undefined symbols for architecture arm64:
  "_RCTSetLogFunction", referenced from:
      -[PropertyFinderTests testRendersWelcomeScreen] in PropertyFinderTests.o

When i try to compile the default project on iOS. (using react-native init)

**Comment by mkonicek** [comment]
If anything broke this it might have been my commit: https://github.com/facebook/react-native/commit/19f922aa806b027348d9243b0085126fe553e266

@ide @kmagiera Are you hitting this as well? My Xcode is unfortunately busted, reinstalling now.

**Comment by mkonicek** [comment]
If anything broke this it might have been my commit: https://github.com/facebook/react-native/commit/19f922aa806b027348d9243b0085126fe553e266

@kmagiera @brentvatne @ide Are you hitting this as well? My Xcode is unfortunately busted, reinstalling now.

**Comment by mkonicek** [comment]
@javache is in London and it's quite late here. Can you unblock yourself by commenting out the test code until we can repro?

**Comment by kmagiera** [comment]
@javache is with me at @scale conf in SJ, he promised to take a look

**Comment by mkonicek** [comment]
Awesome, thank you @kmagiera and @javache!

**Comment by mkonicek** [comment]
Just did `react-native init MyAwesomeApp` and the app builds from Xcode and runs on an iPhone 6 simulator. What device are you using?

**Comment by brentvatne** [comment]
@Javanaise - which version of Xcode? Only 6.3+ are supported

**Comment by Javanaise** [comment]
@mkonicek A real iphone 6
@brentvatne 6.4

**Comment by brentvatne** [comment]
@Javanaise - try pressing ⌘+k to clean the build and run it again

**Comment by Javanaise** [comment]
@brentvatne did a Clean and a Clean build folder, still fails

**Comment by brentvatne** [comment]
@Javanaise - have you tried in the simulator?

**Comment by Javanaise** [comment]
@brentvatne it's working in the simulator

**Comment by brentvatne** [comment]
@Javanaise - what OS?

**Comment by hernanmateo** [comment]
Same problem on iphone 6 ios 8.3. It is working on the simulator.

**Comment by ide** [comment]
Also what simulator? Make sure it's 5s or newer which runs the x86_64 libs.

**Comment by Javanaise** [comment]
@brentvatne os x ? 10.10.5
@ide I used iphone 6 for the simulator, and it built. 
I only have a problem with both my iphone 6 (and 5) real phones.

**Comment by fukai7722** [comment]
The same problem
iPhone 6
iOS 8.4
OS X El Capitan 15A282b

**Comment by ide** [comment]
Compiling fine for me (even after cleaning) w/actual iPhone 6, Xcode 7 GM, El Cap beta 8. Wonder if Xcode is the issue here...

**Comment by mingzgc** [comment]
Also same problem
iphone6 plus
ios 8.4.1
OSX 10.10.5

**Comment by jondot** [comment]
Same here,

Xcode 7 GM
iphone6
ios 8.4.1
OSX 10.10.5

fails only on real device.

as a quick workaround, removing tests makes this go away

**Comment by javache** [comment]
I can repro this when building the SampleApp for testing for iPhone 6 using Xcode 7 GM. Investigating.

**Comment by javache** [comment]
The problem seems that Xcode's dead code stripping removes the RCTSetLogFunction, since it's not being called anywhere. Disabling "Dead Code Stripping" from your main target's build settings will disable the build error.

This method was changed in https://github.com/facebook/react-native/commit/b998e5a7b74905b30b1137a02e14cd5e6f97fccc

**Comment by xuwenmin** [comment]
i have some error,but only remove test target,it's ok!

**Comment by jhabdas** [comment]
The solution @javache provided worked for me after encountering this error running on a physical device from Xcode 7 after to React Native `v0.11.0`. Thanks for opening this issue @Javanaise!!

**Comment by tealtail** [comment]
Disabling "Dead Code Stripping" let me run on my physical device.
Thanks @javache!

**Comment by bidatacoder** [comment]
Same issue here. In my case, this is caused by missing 'libReact.a' in the AwesomeProjectTests link path.

Symptom
------------
Fresh 'react-native init AwesomeProject'. Load it with Xcode and build failed at AwesomeProjectTest target for iphone device with the errors:

  "_RCTSetLogFunction", referenced from:
      -[AwesomeProjectTests testRendersWelcomeScreen] in AwesomeProjectTests.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

This is because libReact.a is not at the 'AwesomeProjectTests' target build Phases -> 'Link Binary With Libraries' 

Workaround
----------------
Manually add libReact.a to 'AwesomeProjectTests' target 'Link Binary With Libraries'.
1. Open Xcode project page.
2. Select Targets->"AwesomeProjectTests"
3. Select 'Build Phases'-> 'Link Binary With Libraries'
4. Press '+' to add item.
5. Select 'Workspace'->libReact.a, hit 'Add'
6. Rebuild the project, and build succeeded.

react-native-cli@0.1.4
Xcode Version 7.0 (7A220)
iOS: 9.0 (13A344)

**Comment by leoabacade** [comment]
same issue here,

the solution of @javache works for me too.

**Comment by MossP** [comment]
I didn't try the dead code stripping but the solution by @bidatacoder worked fine for me. Thanks :)

**Comment by jonolock91** [comment]
How do you disable 'Dead Code Stripping', I'm new to Xcode unfortunately, and am having the same problem.

**Comment by tealtail** [comment]
@jonolock91, you can get to the build settings by clicking on the main xcodeproj file (the one with the blue icon) in the sidebar. There will be a search bar in the now-opened build settings pane so you can start typing "Dead code stripping" to filter out the other settings. Expand the Dead Code Stripping setting and change debug to NO.

![image](https://cloud.githubusercontent.com/assets/1327886/10048448/e92e7238-61e0-11e5-9b9f-a3b926f4f02e.png)

**Comment by jonolock91** [comment]
@tealtail thanks for the help, that has now worked for me too! :)

**Comment by chetstone** [comment]
Thanks @bidatacoder

**Comment by eddanger** [comment]
Dead Code Stripping trick worked for me.

**Comment by kevincobain2000** [comment]
+1 Dead Code Stripping

**Comment by BilalBudhani** [comment]
Dead Code Stripping trick worked for me as well. :+1: @tealtail

**Comment by seanmthompson** [comment]
Dead code stripping worked for me.

**Comment by hoffman211** [comment]
+1 Dead Code Stripping

**Comment by weisjohn** [comment]
Dead code stripping worked for me, too.

**Comment by hidace** [comment]
Was having the same issue. @javache's solution worked for me. Thanks, appreciate it!!

**Comment by skeie** [comment]
+1 here, @javache's solution worked for me too. Big thanks!

**Comment by ptubig** [comment]
+1 on @javache solution

**Comment by rosickey** [comment]
+1 Dead Code Stripping

**Comment by tlightsky** [comment]
meet this too

**Comment by hugebug4ever** [comment]
Yes, "dead strip trick" works for me too. 
But, how could I give up "dead strip" which is a crucial feature for an app?

@bidatacoder  your workaround seems not working :(

**Comment by stephenzhao** [comment]
checkout ur net-work, try to connect ur mac with proxy and change the localhost of jsCodeLocation to ur ip

**Comment by niftylettuce** [comment]
why is this issue closed?  this is obviously still an issue.

**Comment by niftylettuce** [comment]
having to do a "dead trick" or "workaround" does not constitute this issue from being resolved, at least I don't think it should be.

**Comment by sghiassy** [comment]
Setting `Dead Code Stripping` to `no` worked for me. Thx

![screen shot 2015-12-02 at 4 51 52 pm](https://cloud.githubusercontent.com/assets/792606/11548807/0b166e26-9915-11e5-8f99-971c605a1d6e.png)

**Comment by jlyman** [comment]
+1 on @bidatacoder's solution, allows me to keep `dead code stripping` as YES and still create a successful release build.

**Comment by bradbumbalough** [comment]
+1  for @bidatacoder's solution. I had the exact same issue detailed above.

**Comment by andrecassal** [comment]
I'm seeing this error and I had Dead Code Stripping set to NO. Any other ideas?

**Comment by moschan** [comment]
+1 Thank you for @tealtail's solution. It worked.

**Comment by irfaan** [comment]
@bidatacoder's solution worked! https://github.com/facebook/react-native/issues/2685#issuecomment-142137371

Thanks!

**Comment by Mokto** [comment]
Is "set Dead Code Stripping to No" or @bidatacoder solution better ?

**Comment by calvinf** [comment]
@Mokto - I believe bigdatacoder's solution is better as it allows the app to strip out unneeded code from the build.

via [Apple's docs](https://developer.apple.com/library/mac/documentation/General/Conceptual/MOSXAppProgrammingGuide/Performance/Performance.html)
> For statically linked executables, dead-code stripping is the process of removing unreferenced code from the executable file. If the code is unreferenced, it must not be used and therefore is not needed in the executable file. Removing dead code reduces the size of your executable and can help reduce paging.

**Comment by nosensezzz** [comment]
Disable Dead Code Stripping in the build setting fix my issue. Thanks @javache

**Comment by CreativeManix** [comment]
'Dead code Stripping' Disabling fixes this issue, Thanks @javache.

**Comment by alexprice91** [comment]
If I remove 'Dead Code Stripping' on the release build, will I have logs when I submit my app to iTunes connect?

I tried to use @bidatacoder's method, but I do not see `libReact.a` as a library that I can add.

**Comment by avioli** [comment]
# For anyone poking with this and having issues with the @bidatacoder's method:

You have to select the **TESTS** target (that is `<AppName>Tests`) and add the `libReact.a` there, not your actual app's target, which has the `libReact.a` already!

**Comment by ysyyork** [comment]
@avioli @bidatacoder Thanks! This works better than turning down dead code stripping!

**Comment by geekyme** [comment]
Just in case someone is doesn't know how to add the extra configuration mentioned by @avioli, in Xcode:

1. Select your the test target `<AppName>Tests`

2. Select `Build Phases`

3. Under `Link Binary with Libraries`, click the + icon and then add `libReact.a`. Then build again. 

Should work. Thanks @avioli

**Comment by javache** [comment]
Could you submit a pull request that changes the project generator to do this by default? Thanks!

**Comment by herkyl** [comment]
I had the same issue. However, it was caused by renaming the app. I fixed it by doing a project wide search and replacing **all** occurrences of the name. I also had to change a few directory and file names.

**Comment by jonigl** [comment]
Same Issue here but adding libReact.a to my test target do the trick! :)

**Comment by KGALLET** [comment]
Same issue and disabling Dead Code Stripping didn't solve the problem whereas @bidatacoder solution worked fine for me 👍

**Comment by tylerxo** [comment]
I'm encountering this issue, but disabling Dead Code Stripping did not work, and libReact.a is already included in my Link Binary With Libraries. Anyone other ideas?

**Comment by longsangstan** [comment]
HI,
I have the same problem but
-it says architecture i386 instead of arm64
-it only happens when i choose iphone 5/4s simulators; other version such as 5s/6/6s don't have the problem

I tried the dead code stripping and add libReact.a to TESTS, both of them are not working for me.

Have anyone had the same problem?

**Comment by zdol** [comment]
For anyone having this problem, make sure you add the `-lc++` flag to your `<AppName>Tests` target and not your normal target (where it probably already exists.)

**Comment by czl1378** [comment]
@zdol <AppName>Tests has no 'Other Linker Flags' option

**Comment by czl1378** [comment]
In **Build Settings** **All**, I found that option, and after add `-lc++` flag, it works! Thank you @zdol !

**Comment by testxin** [comment]
@czl1378 it's work for me thanks

**Comment by benjaminb10** [comment]
Here is a screenshot, thanks @czl1378 

![screenshot_2016-12-20 19 08 31_7naokg](https://cloud.githubusercontent.com/assets/2952678/21362284/fa6e0f28-c6e7-11e6-9e1d-7a35dc21d491.png)

**Comment by tianxind** [comment]
I have been struggling with this for a while after upgrading to rn0.39, and the answer @czl1378 and @benjaminb10 is correct. you need to add other linker flags.

**Comment by felipecocco** [comment]
+1 -- Adding the flags fixed the build errors for me on 0.40.0

**Comment by IljaDaderko** [comment]
@benjaminb10 +1 adding that flag fixes the issue

**Comment by sashakid** [comment]
> Under Link Binary with Libraries, click the + icon and then add libReact.a. Then build again.

For me, vice versa, removing `libReact.a` helped me and my tests and my app runs both on simulator and device.

**Comment by yimingtang** [comment]
I'm using CocoaPods 1.2.0 and React Native 0.42.0. When I try to archive a release build, the error occurs.

It seems that your solutions won't work in my situation. Any ideas?

**Comment by smccamley** [comment]
@bidatacoder 's solution didnt work for me :-( I don't have 'Workspace'->libReact.a ... the closest I have is libcxxreact.a

Any ideas?
