### ISSUE TITLE
place holder direction bug in secret text inputs

### ISSUE THREAD

**Issue by mahshadalishahi** [facebook/react-native#26866]
React Native version: 0.60.5

## Steps To Reproduce
1. Add TextInput with secureTextEntry props true with a placeholder mixed of two languages ( one is rtl one like Persian and the other is ltr like English) 

Describe what you expected to happen:
I expect to placeholder works same as filling it in Text component or non secret input but after setting secureTextEntry to true, text-direction would be shown in wrong orders as shown in bottom screenshot.
Something that‍`s right and should show :

![Screenshot from 2019-10-15 15-54-23](https://user-images.githubusercontent.com/38342380/66831268-19cacd00-ef64-11e9-8237-3446fc8c6a8f.png)

Something that‍`s wrong and it shows right now:

![Screenshot from 2019-10-15 15-47-46](https://user-images.githubusercontent.com/38342380/66830854-534f0880-ef63-11e9-9768-82bfcd32d50a.png)

**Comment by RZsam** [comment]
same here  
with `secureTextEntry` in TextInput placeholder moved to the left.

second input has `secureTextEntry` in props:
![Screenshot_1571207514](https://user-images.githubusercontent.com/26380519/66894266-d53f4000-effc-11e9-954d-0c2038d9480b.png)
