### ISSUE TITLE
Multiple Bugs when upgrading to 61.2

### ISSUE THREAD

**Issue by prinse1545** [facebook/react-native#26860]
React Native version: 61.2

## I have the project on a private repo I'm getting the following errors and haven't been able to find any issues after upgrading to 61.2 it seems header files are missing I made sure they're linked as well

These are the screenshots:

<img width="260" alt="Screen Shot 2019-10-14 at 1 14 03 PM" src="https://user-images.githubusercontent.com/26307526/66779314-ca20ce80-ee9b-11e9-8030-d48895630b92.png">
Snack, code example, screenshot, or link to a repository:

**Comment by ptcasa** [comment]
I have this error when install pod file:

```
[!] Unable to find a specification for `ReactCommon/turbomodule/core (= 0.61.2)` depended upon by `React-CoreModules`

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
```

**Comment by TommyLeong** [comment]
I have difficulty in getting React/{file} as well. There's a solution given by some developer by _adding "React" as Target_ into your project scheme and it shall work fine.  Unfortunately it doesn't happen on me, not sure what's missing. 

I'm on RN0.61.

**Comment by prinse1545** [comment]
It's saying React(missing) so I deleted it and tried to add React, but I can only add the bullseye version and it won't build. React.xcodeproj is in my Libraries

**Comment by TommyLeong** [comment]
I finally found a [solution](https://stackoverflow.com/a/58398989/4311268) for this issue, feel free to take a look. Hope it helps!

**Comment by prinse1545** [comment]
Thank you but I'm not entirely sure how to follow his instructions...I need to make a third party podspec?

**Comment by TommyLeong** [comment]
You should look if the 3 dependencies you are using has .podspec file. If yes, you should add them under your podfile, so it will be executed during podinstall. 

If no, you should then create podspec file based on the instructions given. You can simply copy an existing podspec from other libraries and modify accordingly.

**Comment by osterbergmarcus** [comment]
@TommyLeong When you say "create podspec file" do you mean that every developer should add it locally? Even if that would be a possible solution it does not seem to be an effective solution. I would rather see that the lib author/contributors adds a `podspec` to the project that are missing a `podspec` file.

**Comment by TommyLeong** [comment]
@osterbergmarcus  Maybe to better rephrase, I should name it as workaround. To have lib author/contributor append podspec in their open-source project would be an ideal case, however there are libraries which no longer supported hence the proposed '_solution_' would be the current workaround (at least it works).

**Comment by adamfellon** [comment]
Hi @TommyLeong @osterbergmarcus , I'm in the process of migrating from `0.57.8` to `0.61.2` and am getting a similar error.

I had React(missing) so I removed it and added the bullseye to the top of the build scheme.

After that I get this error associated with the UIKit.h import:
```
/ios/Pods/Headers/Public/React-Core/React/RCTJavaScriptLoader.h:8:9: While building module 'UIKit' imported from /ios/Pods/Headers/Public/React-Core/React/RCTJavaScriptLoader.h:8:
```

Any ideas?  I don't have the `React.xcodeproj` (or any other frameworks for the matter) imported anymore after migrating.

Thanks in advance!

**Comment by TommyLeong** [comment]
@adamfellon  First of all, here's why you don't find `React.xcodeproj` anymore. [Read more](https://facebook.github.io/react-native/blog/#breaking-changes)
> effectively deprecates the React .xcodeproj support, and the file has been removed starting 0.61

have you tried the '[workaround](https://stackoverflow.com/questions/58373425/react-rctdefines-h-file-not-found-rn0-61/58398989#58398989)` here? This is how I tackle this issue for my project.

**Comment by adamfellon** [comment]
I realized later in the day that I shouldn't be expecting to have the `React.xcodeproj` after reading the notes you mentioned.

Is adding the react bullseye target to the build scheme something I should be doing at all?

I think my issue is something slightly different, I'm not running into issues with third party packages referencing `<React/{whatever}` but generic `cstdarg` errors in the Folly/string.h import and Foundation/CoreFoundation are failing in the build process.

Have you seen anything like that?

Thanks!

**Comment by TommyLeong** [comment]
Like i mentioned in my workaround, I don't add the bulleye to my scheme. So I don't think it's necessary. Have not seen any issue like you mentioned, maybe it's better you perform a cleaning again using  `npx react-native-project-clean`

Reinstall node_modules and pod install again.

**Comment by adamfellon** [comment]
Thanks for the reply, this ended up being an issue with the Header Search Paths.

After removing the the React (target) from my build scheme I looked at the differences between my project and a fresh `react-native init` project and because I had previously used pods without `use_native_modules!` I had `$(PODS_ROOT)/Pods (recursive)` ...I simply had to set that to `non-recursive so that the header info would be built correctly.

👋 3 days of my life.

**Comment by davidmarinangeli** [comment]
> I finally found a [workaround](https://stackoverflow.com/a/58398989/4311268) for this issue, feel free to take a look. Hope it helps!

Unfortunately, this is not my problem because I have already added the pubspec of the library that is giving problems ( `react-native-navigation` ).

**Comment by osterbergmarcus** [comment]
@davidmarinangeli You have to expose React core module for react-native-navigation if react-native-navigation is manually linked.

Try adding to your pod file:
target 'ReactNativeNavigation' do
   project '../node_modules/react-native-navigation/ios/ReactNativeNavigation.xcodeproj'
   pod 'React', :path => '../node_modules/react-native/'
end

This fixed my issue.

**Comment by davidmarinangeli** [comment]
hi @osterbergmarcus, unfortunately, it does not work for me. I fixed the path for the RNN `.xcodeproj` file and tried to run `pod install`

```
target 'ReactNativeNavigation' do
  project '../node_modules/react-native-navigation/lib/ios/ReactNativeNavigation.xcodeproj'
  pod 'React', :path => '../node_modules/react-native/'
  end
```

but the problem is that it does not find the specification for `React-Core`: 
```
[!] Unable to find a specification for `React-Core (= 0.61.2)` depended upon by `React`
```
