### ISSUE TITLE
After upgrade of react-native (v0.59 --> v0.61) lottie animations runs too fast

### ISSUE THREAD

**Issue by chelovekdrakon** [facebook/react-native#26868]
React Native version:
  Binaries:
    Node: 12.3.1 
    Yarn: 1.19.0 
    npm: 6.9.0 
    Watchman: 4.9.0
  SDKs:
    iOS SDK:
      Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
  IDEs:
    Xcode: 11.1
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.1 => 0.61.1

## Steps To Reproduce

1. init react-native project
2. integrate lottie-react-native
3. Run <LottieView /> with animation
4. **Animation runs too fast** (almost instant)
5. Image component with **".gif" runs too fast**

Describe what you expected to happen:

1. ... 3 ...
4. The animation runs with proper speed
5. Image component with ".gif" run with proper speed

Snack, code example, screenshot, or link to a repository:

Branch with **\<LottieView /\>** repro: https://github.com/chelovekdrakon/lottie-issue/tree/lottie-animation
Branch with **\<Image /\>** with gif repro: https://github.com/chelovekdrakon/lottie-issue/tree/image-gif

**Comment by chelovekdrakon** [comment]
Maybe will be helpful : https://github.com/facebook/react-native/issues/26716#issuecomment-542551667

**Comment by ericlewis** [comment]
I don't think this should be related to the changes made to GIFs, but rather 2 issues

**Comment by RenatoMartinsFerreira** [comment]
Hello guys, im dealing with the same issue, after some hours studying maybe I can help with some hints.

I removed the props style from <LottieView/> then  the animation ran with proper speed.

So I tried to see where that hint can bring us, I cloned the [react-native-community/lottie-react-native](https://github.com/react-native-community/lottie-react-native) repo and made some tests.

In resume the master branch of [react-native-community/lottie-react-native](https://github.com/react-native-community/lottie-react-native) works well even with the `style={{flex: 1}}` props, on CHANGELOG it seems to fix other IOS speed trouble: 	

•	Fix iOS speed not changing dynamically

For now I recommend to don’t use `style={{flex: 1}}` props on <LottieView /> until the v3.3.3, I had tried to downgrade lottie-react-native and lottie-ios, to lottie-react-native@2.5.11 and lottie-ios@2.5.3 works on IOS but don’t build on Android.

If you really need to use `style={{flex: 1}}` props on <LottieView /> with RN 0.61.x, a work around can be done by wrapping <LottieView/> with a <View/> at that fork of your repo I used it and worked well: [https://github.com/RenatoMartinsFerreira/lottie-issue](https://github.com/RenatoMartinsFerreira/lottie-issue)

That is my first interaction with the community, but I think that I had something to add to the discussion.

Thanks you all!
