### ISSUE TITLE
Cannot run my script on Android Emulator

### ISSUE THREAD

**Issue by Leseli** [facebook/react-native#26865]
I don't have any experience with React but I followed the React Native CLI Quickstart guide step by step to get things started. 
C:\Windows\System32\AwesomeProject>react-native info
info Fetching system and libraries information...
System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
    Memory: 6.51 GB / 15.81 GB
  Binaries:
    Node: 12.12.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.11.3 - C:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.2, 28.0.3, 29.0.2
      System Images: android-28 | Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5900203
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.2 => 0.61.2

C:\Windows\System32\AwesomeProject>

My Emulator is up and running and this is what I got on CMD:

C:\Windows\System32\AwesomeProject>react-native run-android
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 863 file(s) to forward-jetify. Using 8 workers...
info Starting JS server...
info Installing the app...
Starting a Gradle Daemon (subsequent builds will be faster)
> Task :app:mergeDebugResources FAILED
10 actionable tasks: 2 executed, 8 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> 8 exceptions were raised by workers:
  com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource compilation failed
  C:\Windows\System32\AwesomeProject\android\app\build\intermediates\res\merged\debug: error: directory does not exist.

  com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource compilation failed
  C:\Windows\System32\AwesomeProject\android\app\build\intermediates\res\merged\debug: error: directory does not exist.

  com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource compilation failed
  C:\Windows\System32\AwesomeProject\android\app\build\intermediates\res\merged\debug: error: directory does not exist.

  com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource compilation failed
  C:\Windows\System32\AwesomeProject\android\app\build\intermediates\res\merged\debug: error: directory does not exist.

  com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource compilation failed
  C:\Windows\System32\AwesomeProject\android\app\build\intermediates\res\merged\debug: error: directory does not exist.

  com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource compilation failed
  C:\Windows\System32\AwesomeProject\android\app\build\intermediates\res\merged\debug: error: directory does not exist.

  com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource compilation failed
  C:\Windows\System32\AwesomeProject\android\app\build\intermediates\res\merged\debug: error: directory does not exist.

  com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource compilation failed
  C:\Windows\System32\AwesomeProject\android\app\build\intermediates\res\merged\debug: error: directory does not exist.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 13s

error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> 8 exceptions were raised by workers:
  com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource compilation failed
  C:\Windows\System32\AwesomeProject\android\app\build\intermediates\res\merged\debug: error: directory does not exist.

  com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource compilation failed
  C:\Windows\System32\AwesomeProject\android\app\build\intermediates\res\merged\debug: error: directory does not exist.

  com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource compilation failed
  C:\Windows\System32\AwesomeProject\android\app\build\intermediates\res\merged\debug: error: directory does not exist.

  com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource compilation failed
  C:\Windows\System32\AwesomeProject\android\app\build\intermediates\res\merged\debug: error: directory does not exist.

  com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource compilation failed
  C:\Windows\System32\AwesomeProject\android\app\build\intermediates\res\merged\debug: error: directory does not exist.

  com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource compilation failed
  C:\Windows\System32\AwesomeProject\android\app\build\intermediates\res\merged\debug: error: directory does not exist.

  com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource compilation failed
  C:\Windows\System32\AwesomeProject\android\app\build\intermediates\res\merged\debug: error: directory does not exist.

  com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource compilation failed
  C:\Windows\System32\AwesomeProject\android\app\build\intermediates\res\merged\debug: error: directory does not exist.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 13s

    at checkExecSyncError (child_process.js:621:11)
    at execFileSync (child_process.js:639:15)
    at runOnAllDevices (C:\Windows\System32\AwesomeProject\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:74:39)
    at buildAndRun (C:\Windows\System32\AwesomeProject\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:158:41)
    at C:\Windows\System32\AwesomeProject\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:125:12
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Command.handleAction (C:\Windows\System32\AwesomeProject\node_modules\react-native\node_modules\@react-native-community\cli\build\cliEntry.js:160:7)

C:\Windows\System32\AwesomeProject>

Please help

**Comment by clytras** [comment]
@Leseli don't ever use a system directory to store any kind of files, especially an entire project!
`%windir%\System32` is a system directory and it is protected of course, so `react-native` can't write any outputs.

**Comment by Teenayc** [comment]
@clytras thnx for your response.

**Comment by Leseli** [comment]
> @Leseli don't ever use a system directory to store any kind of files, especially an entire project!
> `%windir%\System32` is a system directory and it is protected of course, so `react-native` can't write any outputs.

The fix above by @Teenayc worked for me!
