### ISSUE TITLE
[0.61.2] react-native run-android --port option is not working

### ISSUE THREAD

**Issue by vukmandavid** [facebook/react-native#26867]
I run **react-native run-android --port 8889** and the bundler opens on port 8081.
I've just upgraded from 0.60.3 where this feature was working.
 

React Native version: 
  System:
    OS: macOS 10.14.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
    Memory: 496.68 MB / 16.00 GB
    Shell: 3.2.57 - /bin/sh
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.2 => 0.61.2
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7 

## Steps To Reproduce

1. run react-native run-android --port 8889
2. when metro bundler opens check the port it is 8081

This maybe helps:
If I run the command without device attached I can see this in the error:
Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=**8889**

**Comment by jeremybarbet** [comment]
Are you not suppose to do `react-native run start --port 8889` too?

**Comment by Chris92de** [comment]
> Are you not suppose to do `react-native run start --port 8889` too?

No this should be unnecessary. It worked for me in 0.59.9 and now I'm experiencing the same issue after upgrading to 0.61.2 and even after initializing a fresh project.

This seems to be a regression. Also applies to iOS, where the same --port parameter in `react-native run-ios --port 1234` does nothing as well

**Comment by ehtasham89** [comment]
facing same problem when running with different port. 
Not working in react-native 0.61.2
`react-native run-android --port=8085 `

**Comment by EhsanSarshar** [comment]
react-native start --port=8097
worked for me
