### ISSUE TITLE
Setting the property "swipeEnabled" to "true" for createMaterialTopTabNavigator causes the app to crash in release mode.

### ISSUE THREAD

**Issue by Vj3213** [facebook/react-native#26863]
I upgraded my react-native version to 0.61.2 and found that, in createMaterialTopTabNavigator, if we don't pass the property "swipeEnabled" or set it to "true", then touching any of the screens passed as a route configs in MaterialTopTabNavigator crashes the app in release mode but it works fine in debug mode.

React Native version:
System:
    OS: Linux 4.15 Ubuntu 16.04.6 LTS (Xenial Xerus)
    CPU: (4) x64 Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
    Memory: 2.58 GB / 15.58 GB
    Shell: 4.3.48 - /bin/bash
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.17.3 - /usr/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.3
      System Images: android-23 | Intel x86 Atom, android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-24 | Intel x86 Atom, android-24 | Intel x86 Atom_64, android-24 | Google APIs Intel x86 Atom, android-24 | Google APIs Intel x86 Atom_64, android-25 | Intel x86 Atom, android-25 | Intel x86 Atom_64, android-25 | Google APIs ARM 64 v8a, android-25 | Google APIs Intel x86 Atom, android-26 | Intel x86 Atom, android-26 | Intel x86 Atom_64, android-26 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom_64, android-26 | Google Play Intel x86 Atom, android-27 | Intel x86 Atom, android-27 | Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-28 | Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64, android-Q | Intel x86 Atom
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.2 => 0.61.2 
  npmGlobalPackages:
    react-native-cli: 2.0.1

## Steps To Reproduce
1.import { createMaterialTopTabNavigator } from 'react-navigation-tabs';
   import screenOne from './screenOne';
   import screenTwo from './screenTwo';

2.const topTabNavigator = createMaterialTopTabNavigator(
  {
    screenOne: screenOne,
    screenTwo: screenTwo,
  },
  {
   ...
    swipeEnabled: true,   // or dont pass this property.
   ...
  },
);

3. Run the app in release mode (react-native run-android --variant=release)

4. Now go to screenOne or screenTwo and just touch it, the app will be crashed.

Describe what you expected to happen: Swipe should have been worked for moving from one tab to another.

**Comment by kkoudev** [comment]
@Vj3213  This is a react-native-gesture-handler issue.
Please check here.
https://github.com/kmagiera/react-native-gesture-handler/issues/783#issuecomment-538273999

**Comment by Vj3213** [comment]
> @Vj3213 This is a react-native-gesture-handler issue.
> Please check here.
> [kmagiera/react-native-gesture-handler#783 (comment)](https://github.com/kmagiera/react-native-gesture-handler/issues/783#issuecomment-538273999)

Thank you @kkoudev ,   this worked perfectly.
