### ISSUE TITLE
Keyboard Component doesn't work on S10e

### ISSUE THREAD

**Issue by KoreanThinker** [facebook/react-native#26872]
React Native version: 0.59 (expo 35.0.0)

## Steps To Reproduce

1. use {Keyboard.addlistner} on samsung S10e (SM-G970N)
2. It works well on other devices.

Describe what you expected to happen:
![InkedKakaoTalk_20191016_144148274_LI](https://user-images.githubusercontent.com/48207131/66891528-62e25600-f024-11e9-8a58-dac2f8878f7e.jpg)

Snack, code example, screenshot, or link to a repository:
`
componentDidMount() {
        this.keyboardDidShowListener = Keyboard.addListener('keyboardDidShow', this._keyboardDidShow.bind(this));
        this.keyboardDidHideListener = Keyboard.addListener('keyboardDidHide', this._keyboardDidHide.bind(this));
}
`

**Comment by aprilcoskun** [comment]
it doesn't work on samsung galaxy s6 too.
