### ISSUE TITLE
expo not working

### ISSUE THREAD

**Issue by CLETON** [facebook/react-native#26878]
info
  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (2) x64 Intel(R) Pentium(R) CPU 2127U @ 1.90GHz
      Memory: 899.14 MB / 5.89 GB
    Binaries:
      Yarn: 1.19.1 - C:\Users\CLETON\AppData\Roaming\npm\yarn.CMD
      npm: 6.11.3 - C:\Program Files\nodejs\npm.CMD

error Invalid regular expression: /(.*\\__fixtures__\\.*|node_modules[\\\]react[\\\]dist[\\\].*|website\\node_modules\\.*|heapCapture\\bundle\.js|.*\\__tests__\\.*)$/: Unterminated character class. Run CLI with --verbose flag for more details.

Metro Bundler process exited with code 1
Set EXPO_DEBUG=true in your env to view the stack trace.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start: `expo start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\CLETON\AppData\Roaming\npm-cache\_logs\2019-10-16T09_41_28_786Z-debug.log

**Comment by FLGMwt** [comment]
As mentioned in https://github.com/facebook/react-native/issues/26598#issuecomment-546520915, you should be able to fix this by using node version 12.9.1 or earlier.

**Comment by cpojer** [comment]
Thank you for your report. We fixed this just now with the release of Metro 0.56.4 and 0.57.0. Update your packages and re-create your project and things should work for you again :) Sorry for the inconvenience.

**Comment by ChristianTucker** [comment]
@cpojer Not sure if I should re-open an issue or post here, but having the same issue with node 12.14.1, npm 6.13.4


```
  "dependencies": {
    "expo": "^37.0.7",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz",
    "react-native-web": "~0.11.7"
  },
```

Windows 10.
