### ISSUE TITLE
Question: how show 'next' button in number-pad TextInput

### ISSUE THREAD

**Issue by saimonventura** [facebook/react-native#26885]
I have a form with some TextInputs, someone of the are number-pad.
How can I show next button with number-pad keyboard?

### DONE button works fine.
```
<TextInput keyboardType="number-pad" returnKeyType={ 'done' } />
```
![image](https://user-images.githubusercontent.com/3719710/66939831-31648d00-f01a-11e9-818c-b5ece8149b8d.png)

### NEXT button is not visible.
``` 
<TextInput keyboardType="number-pad" returnKeyType={ 'next' } />
```
![image](https://user-images.githubusercontent.com/3719710/66939993-80aabd80-f01a-11e9-9605-e92fb38ede83.png)

**Comment by stevenschmatz** [comment]
+1

**Comment by RuairiOliver** [comment]
Anyone find a solution to this?

**Comment by movie4** [comment]
(Platform.OS === 'ios') ? 'done' : 'next' — good spike 🥇

**Comment by jpamarohorta** [comment]
This still happens in `0.61.2` Is there a iOS reason for the "Next" not to appear?

**Comment by brunohkbx** [comment]
Any updates on this?

**Comment by gsevla** [comment]
> (Platform.OS === 'ios') ? 'done' : 'next' — good spike 🥇

If you use formik, done as returnKeyType dispatch handleSubmit so done is not an option.

**Comment by rafaelbpa** [comment]
Why this is closed? Still a problem too me too in 0.61.5

**Comment by santiagomarcano** [comment]
Same problem here. Any solution??

**Comment by ssuzzi** [comment]
Simply add an InputAccessoryView and bind the next input focus event to a button inside that view

**Comment by MorenoMdz** [comment]
> Simply add an InputAccessoryView and bind the next input focus event to a button inside that view

I am curious about this approach, could you share a code block example? Thanks

**Comment by MorenoMdz** [comment]
> > (Platform.OS === 'ios') ? 'done' : 'next' — good spike 🥇
> 
> If you use formik, done as returnKeyType dispatch handleSubmit so done is not an option.

Thats odd, I am trying to solve this and I am using Formik, had to create a whole class component just to hold my forms to be able to focus the next input as useRef was not working for me, and calling `returnKeyType="done"` in IOS goes to the next field for me, instead of submitting. I had to explicit set the last input to submit with `onSubmitEditing={() => handleSubmit()}`

```javascript
<FormInput
                    allowFontScaling={false}
                    onChangeText={handleChange('redemptionsTotal')}
                    onBlur={handleBlur('redemptionsTotal')}
                    name="redemptionsTotal"
                    value={values.redemptionsTotal}
                    error={errors.redemptionsTotal}
                    touched={touched.redemptionsTotal}
                    placeholder="TOTAL"
                    returnKeyType={Platform.OS === 'ios' ? 'done' : 'next'}
                    blurOnSubmit={false}
                    keyboardType="numeric"
                    setInpRef={inpRedeemTotal =>
                      (this.inpRedeemTotal = inpRedeemTotal)
                    }
                    onSubmitEditing={() => this.inpRedeemUser.focus()}
                    style={styles.inputShort}
                  />
```

**Comment by QueenTallicia69-cloud** [comment]
> I have a form with some TextInputs, someone of the are number-pad.
> How can I show next button with number-pad keyboard?
> 
> ### DONE button works fine.
> ```
> <TextInput keyboardType="number-pad" returnKeyType={ 'done' } />
> ```
> ![image](https://user-images.githubusercontent.com/3719710/66939831-31648d00-f01a-11e9-818c-b5ece8149b8d.png)
> 
> ### NEXT button is not visible.
> ``` 
> <TextInput keyboardType="number-pad" returnKeyType={ 'next' } />
> ```
> ![image](https://user-images.githubusercontent.com/3719710/66939993-80aabd80-f01a-11e9-9605-e92fb38ede83.png)
>

**Comment by ngocht143** [comment]
@react-native-bot Same problem here. Any solution?

**Comment by colaquecez** [comment]
Same problem here, any solution? :(

**Comment by allanzi** [comment]
Using 0.63 and same problem 😭

**Comment by allanzi** [comment]
Why it's closed?

**Comment by henrymoulton** [comment]
Still an issue, why is this closed?

**Comment by Hustenbonbon** [comment]
I created a new issue that follows the template, maybe this will be looked at. Please upvote the new issue if you want this bug to be solved: https://github.com/facebook/react-native/issues/31794
