### ISSUE TITLE
Get absolute local image path for android

### ISSUE THREAD

**Issue by IsmetGlumcevic** [facebook/react-native#26880]
Hi ,  
I am trying to share image on android. I use react-native-share to share image and react-native-fs to get image path from my local image. 
On ios work fine. I get path like 'file://' + RNFS.MainBundlePath + shareimgurl. 
On android don't work. I trying with 'file://' + RNFS.DocumentDirectoryPath + shareimgurl, RNFS.ExternalStorageDirectoryPath.... 
I do not understand how like absolute path for local image. My image is in folder 'slike' in app root. 
This is issue https://github.com/react-native-community/react-native-share/issues/593
Thanks.

System:
    OS: macOS 10.15
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 23, 28, 29
      Build Tools: 28.0.3, 29.0.0
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.3 => 0.60.3 
  npmGlobalPackages:
    react-native-cli: 2.0.1

**Comment by IsmetGlumcevic** [comment]
Any tips, i try to find path like
file:///storage/emulated/0/slike/page1.png
file:///storage/emulated/0/Android/data/com.mojapp/files/slike/page1.png

this is folder structure 

![Screenshot 2019-10-03 at 12 49 56](https://user-images.githubusercontent.com/14037875/67080330-4ade1400-f195-11e9-86fb-3d82af848519.png)

**Comment by sujatha2016** [comment]
did u succeed in this ?

**Comment by sujatha2016** [comment]
did u succeed in this ?

**Comment by sujatha2016** [comment]
did u succeed in this ?
