### ISSUE TITLE
base64 images do block get queued with orther network requests even though it does not need to.

### ISSUE THREAD

**Issue by coulix** [facebook/react-native#26898]
React Native version: sdk-34.0.1

## Steps To Reproduce

Given an image

``` 
<Image
          style={{width: 66, height: 58}}
          source="basedata:image/png;base64,iVBORw0K....="
>
```

On a react native application that has `n` other `non base64` (classic http:// url) src images loading (where `n` is around 10 and 20), the `base64` src does not get priority and is only rendered after the queued network calls do resolve.
 
 
Describe what you expected to happen:

The base64 src Image should render right away and a network call should not get queued.

**Comment by dulmandakh** [comment]
Please provide demo code, so we can re-produce the issue. Will re-open the issue once we have demo.
