### ISSUE TITLE
Device warning suppressed?

### ISSUE THREAD

**Issue by dsissitka** [facebook/react-native#2690]
In order to get `react-native run-android` to work with a device I had to run `adb reverse tcp:8081 tcp:8081`. There's a warning but it never bubbled up to me:

https://github.com/facebook/react-native/blob/42eb5464fd8a65ed84b799de5d4dc225349449be/ReactAndroid/src/main/java/com/facebook/react/devsupport/DevServerHelper.java#L132-L135

Maybe I just wasn't looking in the right place?

**Comment by kmagiera** [comment]
Notice that this is also documented in http://facebook.github.io/react-native/docs/running-on-device-android.html#content

**Comment by dsissitka** [comment]
Shouldn't that warning make it to the user? At the moment that page is pretty easy to miss. It doesn't look like it's linked to in the quick start guide or the tutorial and at least three of us got bit within hours of the release announcement.

http://stackoverflow.com/questions/32572399/react-native-android-failed-to-load-js-bundle/32574502
https://news.ycombinator.com/item?id=10216898

**Comment by vickychijwani** [comment]
@dsissitka Actually, the warning comes in the adb logcat, not the output of `react-native run-android` or `react-native start`. This bit me too, but I just wasn't looking in the right place.

**Comment by dsissitka** [comment]
@vickychijwani It doesn't appear to work for me:

    $ react-native run-android
    JS server already running.
    ...
    Starting: Intent { cmp=com.awesomeproject/.MainActivity }
    $ # At this point I'm getting the "Unable to download JS bundle." error on my
    $ # device.
    $ adb logcat -d > logcat.log
    $ grep "You seem to" logcat.log
    $

**Comment by vickychijwani** [comment]
I'm not sure what's happening here, those same commands show me lots of warnings in the log if I don't run adb reverse:

```
W/unknown:React(20605): You seem to be running on device. Run 'adb reverse tcp:8081 tcp:8081' to forward the debug server's port to the device.
```

FWIW, I'm using v0.11.0, not master.

**Comment by seekshiva** [comment]
This should be listed in the Android Setup page.
