### ISSUE TITLE
Loading an image from local storage failing on Android 10 (API 29)

### ISSUE THREAD

**Issue by tuncaulubilge** [facebook/react-native#26900]
`getExternalStoragePublicDirectory ` is [deprecated on API 29](https://developer.android.com/reference/android/os/Environment#getExternalStoragePublicDirectory(java.lang.String)) but React Native 0.61.2 is still using it, which results in a permission error. (https://github.com/facebook/react-native/blob/0.61-stable/ReactAndroid/src/main/java/com/facebook/react/modules/camera/CameraRollManager.java#L135)

React Native version: 0.61.2

## Steps To Reproduce

1. Try to load a image from local storage `file:///storage/emulated/0/.....`
2. Throws an error with: `open failed: EACCES (Permission denied)`

Describe what you expected to happen:

Images from local storage to load normally. 

Snack, code example, screenshot, or link to a repository:
https://github.com/facebook/react-native/blob/0.61-stable/ReactAndroid/src/main/java/com/facebook/react/modules/camera/CameraRollManager.java#L135

**Comment by dulmandakh** [comment]
Please don't change targetSdk in your app, because RN still use SDK 28. We're just starting transition to SDK 29 with https://github.com/facebook/react-native/pull/26909.
