### ISSUE TITLE
React native App slows down when remote debugging is off.

### ISSUE THREAD

**Issue by rushikeshc7** [facebook/react-native#26901]
I am currently working on app. It is working fine when remote debugging is ON. But it's getting slow when I turned off the remote debug mode. Please help me with the solution.

React Native Environment Info:
    System:
      OS: macOS 10.15
      CPU: x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
      Memory: 17.00 MB / 8.00 GB
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.16.3 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5900203
      Xcode: 11.0/11A420a - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.9.0 => 16.9.0 
      react-native: ^0.59.1 => 0.59.1 
    npmGlobalPackages:
      react-native-cli: 2.0.1

The App should not lag. Dropdown modal, Button click events are getting slow when remote debugging is Off. The App is working fine when remote debug is ON.

**Comment by Navidhp** [comment]
@rushikeshc7 your problem on android ? and hermes on ? if your answer true this your problem for hermes , hermes compile your code and feel laggy on develop mode is oky on release mode.
if you problem with hermes  , turn off on develop mode

**Comment by alesanderlopez** [comment]
I have the same problem, when i'm working with the debug js the app work fine but when i'm disable debug js, the view takes 1 minute around to load, i removed a lot of code in the view like **VirtualizedList** with a lot of elements but the performance is slow too. 

Using the debug js the load is immediately. 

I tried to enable the Hermes in the next guide but the performance is the same that the debug mode off. 

https://facebook.github.io/react-native/docs/hermes/ 

I updated a RN app from 0.58 to 0.60 and the libraries are update to the latest and fixed the bugs. 

```bash
System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 87.61 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.12.0 - /usr/local/bin/node
    Yarn: 1.19.1 - ~/lib/node_modules/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
    Watchman: 4.7.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 22, 23, 24, 25, 26, 27, 28
      Build Tools: 22.0.1, 23.0.1, 23.0.2, 23.0.3, 24.0.0, 24.0.1, 24.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.3, 27.0.2, 27.0.3, 28.0.0, 28.0.2, 28.0.3
      System Images: android-26 | Google Play Intel x86 Atom, android-28 | Intel x86 Atom_64, android-P | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
```
