### ISSUE TITLE
enabled hermes request PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION - Application get crash on device production realase

### ISSUE THREAD

**Issue by cassubianApp** [facebook/react-native#26913]
# Bug
actually the whole problem in the title ... although there is a question whether Hermes is supported. In the developer version I used hermes enabled, there were no problems ...

## Environment info

React native info output:

```bash
Devive: OnePluse 6
 Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.2 => 0.61.2 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

**Comment by cassubianApp** [comment]
okey when i quit react-native-permissions and used PermissionsAndroid in react native i have the same problem. so is not the problem in react native permission library

**Comment by cassubianApp** [comment]
in log i have:

E/libc: Access denied finding property "vendor.debug.egl.swapinterval"

**Comment by Rapsssito** [comment]
Same issue.

**Comment by cassubianApp** [comment]
Not working, nothing change

czw., 5 mar 2020, 00:50 użytkownik no-response[bot] <
notifications@github.com> napisał:
