### ISSUE TITLE
Dev server fails to start automatically on Ubuntu 14.04.

### ISSUE THREAD

**Issue by dsissitka** [facebook/react-native#2691]
```
$ sudo netstat -lnp | grep 8081
$ react-native run-android
Starting JS server...
...
$ sudo netstat -lnp | grep 8081
$ react-native start > /dev/null 2>&1 &
[3] 6602
$ sudo netstat -lnp | grep 8081
tcp6       0      0 :::8081                 :::*                    LISTEN      6612/node       
$
```

Manually start the dev server and React Native appears to work fine on Ubuntu.

**Comment by mkonicek** [comment]
Linux is not supported yet: https://facebook.github.io/react-native/docs/getting-started.html

Happy to review PRs if you want to get the CLI to work on Linux, see:
- https://github.com/facebook/react-native/blob/master/local-cli/run-android.js
- https://github.com/facebook/react-native/blob/master/react-native-cli/CONTRIBUTING.md

**Comment by SirCmpwn** [comment]
:+1: had to wait ages for android, now have to wait ages for Linux. Come on, I want to play with this!

**Comment by kmagiera** [comment]
Marging to master task #2693 - let's discuss issues related to linux support and workarounds there

**Comment by liuhong1happy** [comment]
When can it support Ubuntu 14.04?

**Comment by lesterzone** [comment]
I'm using ubuntu  14.04 

```
react-native start
```

```
react-native run-android
```

using "0.11.3"

node v0.12.2
npm 2.13.2
nvm 0.25.4

**Comment by calidion** [comment]
+1 for Linux

**Comment by bozzmob** [comment]
+1 for Linux. When can we expect?

**Comment by ide** [comment]
From https://facebook.github.io/react-native/docs/linux-windows-support.html#content:

>As React Native on iOS requires a Mac and most of the engineers at Facebook and contributors use Macs, support for OS X is a top priority. However, we would like to support developers using Linux and Windows too. We believe we'll get the best Linux and Windows support from people using these operating systems on a daily basis.

>Therefore, Linux and Windows support for the development environment is an ongoing community responsibility. This can mean filing issues and submitting PRs, and we'll help review and merge them. We are looking forward to your contributions and appreciate your patience.

>As of version 0.13 (currently in rc) Android development with React native is mostly possible on Linux and Windows. You'll need to install Node.js 4.0 or newer. On Linux we recommend installing watchman, otherwise you might hit a node file watching bug.

**Comment by elifraha** [comment]
Not working still..any one succeeded running on ubuntu?
help please...
