### ISSUE TITLE
[Android] App performance is laggy in production build in Most of the Android-9 devices.

### ISSUE THREAD

**Issue by tejachundru** [facebook/react-native#26912]
React Native version:

info 
  React Native Environment Info:
    System:
      OS: macOS 10.15
      CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
      Memory: 558.57 MB / 16.00 GB
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.16.3 - /usr/local/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
      Android SDK:
        API Levels: 23, 25, 27, 28, 29
        Build Tools: 28.0.3, 29.0.2
        System Images: android-29 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5900203
      Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.10 => 0.59.10 
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Steps To Reproduce

We are observing Lags especially on android 9 devices, we use  **FlatlistComponent**  for all of Listviews.

We tried **removeClippedSubviews** and many other options to improve Flatlist Performance from 

[https://github.com/filipemerker/flatlist-performance-tips/](url)

But, same Thing Persists.

Describe what you expected to happen:

Snack, code example, screenshot, or link to a repository:

**Comment by dulmandakh** [comment]
Please provide demo code, so we can re-produce the issue. Will re-open the issue once we have demo.
