### ISSUE TITLE
Error Build com.google.firebase:firebase-common:19.2.0/androidManifest.xml

### ISSUE THREAD

**Issue by wongjow0** [facebook/react-native#26919]
Error Build :
Execution Failed for task ':processReleaseManifest'
[com.google.firebase:firebase-common:19.2.0]
AndroidManifest.xml : Error: invalid instuction 'targetApi', valid instructions are : REMOVE,REPLACE,STRICT

**Comment by mmuff93** [comment]
@wongjow0 How did you manage to resolve this im having the same issue currently, thanks Michael
