### ISSUE TITLE
[android] Text components that are wrapped in a View are not accessible individually.

### ISSUE THREAD

**Issue by FrancisLeigh** [facebook/react-native#26910]
I have upgraded from RN `0.59.10` to `0.61.2` in order to get my codebase up to date and also squash a bug where the Android 8^ update made TextField's in-accessible. 

Now a new issue has arrised where my `<Text />` components that were previously - individually accessible are now not accessible when wrapped in a `<View />` (a very common use case). 
This issue baffles me as i found a way to fix this bug by wrapped the parent View in a Fragment.
Wrapping the parent View in a Fragment then allows the Text components to be individual accessible. This obviously is not an ideal approach as my whole code-base wil need refactoring.

React Native version:
System:
    OS: macOS Mojave 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Memory: 673.32 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.10.0 - /usr/local/bin/node
    npm: 6.11.3 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-25 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.2 => 0.61.2 
  npmGlobalPackages:
    react-native-cli: 2.0.1

## Steps To Reproduce

1. Wrap a two Text components with different text content in a View.
2. turn screen reader on and focus to the text.
3. Screen reader will read out all of it's contents.
4. swipe away from screen reader.
5. be moved to next relevant item and not the nested texts.

6. wrap the parent View in a Fragment `<>...</>`
7. repeat steps 1 & 2
8. notice how the individual Text components are now fucussed individually. (ideal scenario)

Describe what you expected to happen:
Focus individual text elements

### Reads out the text content as a whole when the View is focussed.
"i should be accessible. i should be accessible as well."
```
render() {
    return (
        <View style={{ flexDirection: "row", justifyContent: "center" }}>
            <Text>I should be accessible.</Text>
            <Text>I should be accessible as well.</Text>
        </View>
    );
}

```

### Reads out the indivual Text component when the user swipes through. (ideal scenario)
*swipe*
"i should be accessible"
*swipe*
"i should be accessible as well."
```
render() {
    return (
        <>
            <View style={{ flexDirection: "row", justifyContent: "center" }}>
                <Text>I should be accessible.</Text>
                <Text>I should be accessible as well.</Text>
            </View>
        </>
    )
}
```

For me this is a huge issue as accessibility within our app is very important and everything was working fine in `RN 0.59.10`

I understand i could be missing an attribute on my parent View... any inside knowledge would be very helpful! i'm trying to avoid refactoring all my code!!!!!

**Comment by FrancisLeigh** [comment]
A fix for this seems to be wrapping your whole page components in fragments.

*this cannot be a viable fix* this must be a bug.

**Comment by Asad-Comm** [comment]
Tried running the same scenario in android 7, it works fine there. Nevertheless, try disabling accessibility property explicitly on that view.  

> <View accessible = {false} > 
> </View>

Can't say for sure but as per the react-native's official documentation when you enable the accessible prop on a view then all the children of that view will be grouped and  treated as one accessibility element i.e the whole View being that element. Now by default all touchable elements are accessible according to the official documentation. Keeping that in mind, maybe explicitly forcing accessibility prop to be disabled on that View element might result in Text elements being treated as individual accessibility elements.

**Comment by rumbogs** [comment]
I'm also having problems with this one. There's a snack here: https://snack.expo.io/ryDThaqsS.
After switching to fragments, the individual text items can be focused, though there's another issue where the focus is set only on the second text item instead of the first, unless the `setTimeout` is large enough.

**Comment by FrancisLeigh** [comment]
A side affect of mym temprary fix (wrapping form pages in a fragment) causes another error where if you press outside of a textField - the keyboard is not dismissed.
