### ISSUE TITLE
textAlignVertical: center not working

### ISSUE THREAD

**Issue by danipralea** [facebook/react-native#26926]
# Bug

I am trying to vertically align the text inside a `Text` component. I tried pretty much everything (```
        textAlignVertical: 'center',
        alignItems:'center',
        alignSelf: 'center',```), but it still doesn't work.
<img width="144" alt="Screenshot 2019-10-12 18 19 54" src="https://user-images.githubusercontent.com/768893/66703775-b3a13880-ed1e-11e9-9366-f2a0f1c3047f.png">

## Environment info

React native info output:

```bash
System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 225.43 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.4.0 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.2 => 0.61.2
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

Library version: 0.61.2

## Steps To Reproduce

1. create the componet
2. set its `style`
3. text inside doesn't get vertically aligned

Describe what you expected to happen:

1. text inside to be vertically aligned

## Reproducible sample code

```javascript
// code. pretty much most basic way of doing it
<Text style={styles.Initials}>HO</Text>

// css
Initials: {
        height: 64,
        width: 64,
        borderRadius: 32,
        color: 'white',
        fontWeight: '600',
        fontSize: 18,
        textAlign: 'center',
        textAlignVertical: 'center',
        alignItems:'center',
        alignSelf: 'center',
        backgroundColor: colors.colorPrimary,
        overflow: 'hidden'
    }
```

**Comment by retyui** [comment]
This prop [supported on Android only](https://facebook.github.io/react-native/docs/text-style-props#textalignvertical)

![image](https://user-images.githubusercontent.com/4661784/67158565-355a1d00-f342-11e9-9d9b-959f8cb1239f.png)

**Comment by danipralea** [comment]
oh. Got it, thanks 

Kind regards,
Dănuț Pralea.

**Comment by denizbas92** [comment]
Did you find any solution ?

**Comment by danipralea** [comment]
> Did you find any solution ?

not really. it's only supported on Android. I've embedded inside a `View` object and set the alignment there

**Comment by denizbas92** [comment]
Thats Why I did, thank you.

10 Şub 2020 Pzt 16:12 tarihinde Danut Pralea <notifications@github.com>
şunu yazdı:

**Comment by thundertrick** [comment]
I fix it with following style:
```
{
    height: 30,
    textAlignVertical: 'center',
    ...Platform.select({
        ios: {
            lineHeight: 30 // as same as height
        },
        android: {}
    })
}
```

Hope it helps

**Comment by daviddossantos** [comment]
hey guys, I created a component that worked for me, I'm sharing
https://github.com/daviddossantos/textinput-multiline-multiplataform

**Comment by Whales1992** [comment]
@thundertrick  your solution will only work if the text is a single line of text! but with multiple lines, it will either cut off the remaining texts or ellipsize it.

**Comment by GiulioFede** [comment]
This is my solution. I simply surround the text with a view. Then I tell the view to align the content and that's it:

```
<View style={{ justifyContent:"center" }}>
     <Text >content...</Text>
</View>

```

Without the view it is possible that the text, as an area, takes up much more than its height in terms of font. In this way, instead, it is the view that takes the height it wants, while the text area adheres perfectly to the height of the font. In this way you align the text area within the view obtaining the equivalent of android's textAlignVertical also for ios.
