### ISSUE TITLE
[0.12] Things we should get in for the next release

### ISSUE THREAD

**Issue by ide** [facebook/react-native#2692]
- ~~Making sure Android works with 0.12. Currently it has been tested against 0.11. I'm not yet sure what works or doesn't work. This is the biggest item. cc @mkonicek~~
- ~~Fixing an arm64 error: https://github.com/facebook/react-native/issues/2685 cc @javache~~
- ~~Get the tests green~~ 
- ~~Node 4 support. package.json has been updated which is the most important part, but it would be nice to get the diffs covered in https://github.com/facebook/react-native/issues/2545 in. At any rate, after 0.12 ships everyone using it should install Node 4 or newer. No more io.js.~~
- ~~Reloading sometimes crashes the app due to some race condition when deallocing CoreText objects: https://github.com/facebook/react-native/issues/2001. Update: fixing this will take longer according to @tadeuzagallo~~ (Fixed in master, we can ship with 0.13-rc)
- ~~Android displays red box on sample project: https://github.com/facebook/react-native/issues/2983~~

heads up @brentvatne @vjeux

**Comment by matth3wga0** [comment]
Do support Xcode 6.2 on Mavericks.

**Comment by ide** [comment]
AFAIK there are no plans for that. If anything Xcode 7 will become a requirement (not 100% sure that will be the case and depends on Facebook's Xcode upgrade path, but users of projects like React Native tend towards cutting-edge technologies).

**Comment by brentvatne** [comment]
This list looks good to me :+1:

**Comment by vjeux** [comment]
@ide we already have both xcode6 and xcode7 running in our infra :)

**Comment by ide** [comment]
@vjeux sweet. I have a PR out to move the tests to run on Travis CI's Xcode 7 machines.. I think it doesn't pass the tests yet but good to know that FB is on XC 7 now.

**Comment by ide** [comment]
Two remaining issues before we can cut 0.12: the crash in NSTextStorage deallocation and the state of the test suite. Once these are fixed I believe we're in the clear for the next release.

**Comment by mkonicek** [comment]
Now that we have a way to merge Android pull requests I will focus on getting the tests to green and making sure that the 'Getting Started' flow works on master. Once that is done and #2001 is fixed we can cut the 0.12 branch.

One caveat: I'll be away (in Turkey) Sep 25 - 30.

**Comment by ide** [comment]
I added https://github.com/facebook/react-native/issues/2983 (Android red box when running the sample project). We've seen a couple of these errors where the Java layer expected a value of a different type and the app doesn't handle it gracefully.

**Comment by vjeux** [comment]
@mkonicek we have an end-2-end test for iOS to make sure that it doesn't instant redbox. Would be nice to add one for Android as well.

**Comment by BerndWessels** [comment]
@mkonicek I think [#2983](https://github.com/facebook/react-native/issues/2983) is a real show stopper since it basically means Android development is broken.

I can retest this on my Windows machine again as soon as you've got a fix for us.

Another important issue is [#2989](https://github.com/facebook/react-native/pull/2989). It is the last missing fix to finally enable RN development on Windows.

**Comment by mkonicek** [comment]
Thanks so much for sending https://github.com/facebook/react-native/pull/2989! Commented. We can cherry-pick that into the release branch.

Commented on https://github.com/facebook/react-native/issues/2983 too.

**Comment by mkonicek** [comment]
@vjeux I completely agree, adding Travis tests is on the roadmap :)

**Comment by mkonicek** [comment]
According to @tadeuzagallo #2001 is unlikely to get fixed right now, let's discuss on the issue.

**Comment by mkonicek** [comment]
Based on the above I think we're good to cut the release branch.

**Comment by mkonicek** [comment]
Just published 0.12.0-rc to npm and published Android artifacts to Bintray (with one caveat: https://github.com/facebook/react-native/commit/12b92c1520786e350a47f2d876910addac932fb3).

Here are the commits the just missed the cut and we should probably cherry-pick to the 0.12-stable branch:
https://github.com/facebook/react-native/commit/fcd7de5301655b39832d49908e5ca72ddaf91f7e
https://github.com/facebook/react-native/commit/03222d66bb1ce90d0150557290a1c93cea1d3171
https://github.com/facebook/react-native/commit/428f76d8a2417310d03cae5ac0711188b8e82ca7

**Comment by mkonicek** [comment]
I haven't published to [CocoaPods](https://cocoapods.org/pods/React) - do we publish rc releases?

**Comment by chirag04** [comment]
react-native-cli need to be published as well?

**Comment by ide** [comment]
Any harm in pulling everything from master over to 0.12.0-rc? Also I believe we're not doing RCs anymore and just releasing 0.12.0 (cc @brentvatne).

**Comment by vjeux** [comment]
@chirag04 hopefully not. We designed react-native-cli to forward all the commands to the local revision so we should never ever have to update it

**Comment by chirag04** [comment]
yup. I just saw some minor changes to react-native-cli so thought maybe you guys want to publish that as well.

**Comment by mkonicek** [comment]
I'm back from vacation :)

> Any harm in pulling everything from master over to 0.12.0-rc?

@ide That would mean we can publish a "stable" version in an unstable state, right?

**Comment by mkonicek** [comment]
I'll pick some of the commits soon-ish, should probably pick https://github.com/facebook/react-native/commit/f6ec854e238fef9d8b3808dbea0b63ba7a10f007 too. Linux support is super cool!

**Comment by mkonicek** [comment]
I'll probably cherry-pick the fix for https://github.com/facebook/react-native/issues/2949 too.

**Comment by BerndWessels** [comment]
@mkonicek Please try to get the Windows support in too.

There is a [Gist](https://gist.github.com/davidgilbertson/9bee68548037fe00f2a8) that explains all the things that need to be done and I believe that most of it already made it into master.

I can confirm that react-native 0.11.4 with the changes from this [Gist](https://gist.github.com/davidgilbertson/9bee68548037fe00f2a8) works great on Windows 8.1 and 10.

To make it a perfect experience on Windows it also needs this:

	@@ -184,22 +184,24 @@ function getDevToolsLauncher(options) {
	+  var launched = false;
	   return function(req, res, next) {
		 if (req.url === '/debugger-ui') {
		   var debuggerPath = path.join(__dirname, 'debugger.html');
		   res.writeHead(200, {'Content-Type': 'text/html'});
		   fs.createReadStream(debuggerPath).pipe(res);
		 } else if (req.url === '/launch-chrome-devtools') {
		   var debuggerURL = 'http://localhost:' + options.port + '/debugger-ui';
	-      var script = 'launchChromeDevTools.applescript';
		   console.log('Launching Dev Tools...');
	-      execFile(path.join(__dirname, script), [debuggerURL], function(err, stdout, stderr) {
	-        if (err) {
	-          console.log('Failed to run ' + script, err);
	-        }
	-        console.log(stdout);
	-        console.warn(stderr);
	-      });
	+      if (!launched) {
	+        require('child_process').exec('start chrome "' + debuggerURL + '"', function (err) {
	+          if (err) {
	+            console.log("error", err);
	+          }
	+        });
	+        launched = true;
	+      }
		   res.end('OK');
		 } else {
		   next();
		 }
	   };
	 }

I took this from [here](https://github.com/facebook/react-native/pull/2406) but had to modify it slightly:

	+        require('child_process').exec('start chrome "' + debuggerURL + '"', function (err) {


As I said it works great and hopefully you can get it into the release.

Let me know if you need somebody to test it.

Cheers
Bernd

**Comment by mkonicek** [comment]
Thanks @BerndWessels! We should probably work towards merging https://github.com/facebook/react-native/pull/2406 or your fix. I'm releasing 0.12 soon, our aim was to have Windows support in 0.13 but if there's so little missing we could even get it to 0.12.x.

**Comment by mkonicek** [comment]
And sorry for the delay @BerndWessels. Hang tight, we definitely want Windows support too :

**Comment by ide** [comment]
Im slating preliminary Windows support for 0.13-rc so if it doesn't land in 0.12, we'll have something for Windows users shortly after.

**Comment by mkonicek** [comment]
@BerndWessels #2406 is not making much progress. Can you submit a PR with your change? Make sure you add a platform check to only do this on Windows, we want to keep the exact same behavior we have on Mac.

See also #3348.

**Comment by BerndWessels** [comment]
@mkonicek It looks like things have already changed in master - unfortunately without taking care of Windows.

    35f9ac8	9/10/2015 10:20 AM	Martín Bigio*	Unify oss and internal version of dev-tools middleware...

There is no `getDevToolsLauncher` in `master` anymore but a new `getDevToolsMiddleware.js`.

I will try the latest `master` tomorrow and see if there is anything missing that I can fix.

Cheers
Bernd

**Comment by ide** [comment]
We'll merge PRs for Windows support into the 0.13 branch, which should be going out in the next 24 hours unless something unexpected happens.

**Comment by BerndWessels** [comment]
@ide Latest `master` and `r13` branch don't work on my Windows 10 64bit anymore.

`react-native run-android` gives me this:

    ...
    ...

	FAILURE: Build failed with an exception.

	* What went wrong:
	Execution failed for task ':app:preDexDebug'.
	> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_60\bin\java.exe'' finished with non-zero exit value 1

	* Try:
	Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

	BUILD FAILED

	Total time: 14.358 secs
	Could not install the app on the device, see the error above.

**Comment by ide** [comment]
@BerndWessels With 0.13 and future releases, Windows support and ongoing maintenance is a community responsibility. See https://github.com/facebook/react-native/issues/3348 if you are interested in helping out.

**Comment by ide** [comment]
Closing since 0.12 is out.
