### ISSUE TITLE
Error running 'react-native run-android' in version 0.61

### ISSUE THREAD

**Issue by JohnAugust934** [facebook/react-native#26929]
React Native version:

## Steps To Reproduce

1. react-native init "name"
2. react-native run-android

Describe what you expected to happen:

expected the app to be compiled and installed on the emulator and open

Snack, code example, screenshot, or link to a repository:

info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 863 file(s) to forward-jetify. Using 2 workers...
info Starting JS server...
info Installing the app...
Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details
:ReactNative:Cannot run program "npx": error=2, Arquivo ou diretório inexistente
:ReactNative:Automatic import of native modules failed.

FAILURE: Build failed with an exception.

* Where:
Script '/home/johnaugust/Apps/receitas/node_modules/@react-native-community/cli-platform-android/native_modules.gradle' line: 171

* What went wrong:
A problem occurred evaluating script.
> Cannot invoke method getErrorStream() on null object

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 12s

error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* Where:
Script '/home/johnaugust/Apps/receitas/node_modules/@react-native-community/cli-platform-android/native_modules.gradle' line: 171

* What went wrong:
A problem occurred evaluating script.
> Cannot invoke method getErrorStream() on null object

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 12s

    at checkExecSyncError (child_process.js:601:13)
    at execFileSync (child_process.js:621:13)
    at runOnAllDevices (/home/johnaugust/Apps/receitas/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:94:39)
    at buildAndRun (/home/johnaugust/Apps/receitas/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:158:41)
    at then.result (/home/johnaugust/Apps/receitas/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:125:12)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by thedarkknight197** [comment]
i have the same problem. I run react-native init new but when i run react-native run-android it not build. ios work.

My Versions: react-native --version
react-native-cli: 2.0.1
react-native: 0.61.2

**Comment by thedarkknight197** [comment]
The start of my log:
react-native run-android
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 863 file(s) to forward-jetify. Using 4 workers...
info JS server already running.
info Installing the app...

FAILURE: Build failed with an exception.

* Where:
Settings file '/Volumes/SASMUNG T5/React/PorscheCarreraCup/android/settings.gradle'

* What went wrong:
Could not compile settings file '/Volumes/SASMUNG T5/React/PorscheCarreraCup/android/settings.gradle'.
> startup failed:
  General error during semantic analysis: Unsupported class file major version 57
  
  java.lang.IllegalArgumentException: Unsupported class file major version 57

**Comment by mattdamon108** [comment]
I have a same issue. I've been working with 0.60.x and working fine. But after I ran `react-native upgrade` to upgrade to `0.61.2`, the android studio starts complaining about `cannot invoke the method getErrorStream()`, even can not sync gradle with same error

**Comment by mrwisu** [comment]
Try using the newest version of react-native-cli:

$ npx react-native --version
3.0.0-alpha.7

Run:
npx react-native init "name"
npx react-native run-android

Note that, you shouldn't be using global installation of react-native.

**Comment by thedarkknight197** [comment]
> Try using the newest version of react-native-cli:
> 
> $ npx react-native --version
> 3.0.0-alpha.7
> 
> Run:
> npx react-native init "name"
> npx react-native run-android
> 
> Note that, you shouldn't be using global installation of react-native.

i don't use npx, how can i update it?

**Comment by mrwisu** [comment]
Don't use global react-native-cli, use v3:
https://github.com/react-native-community/cli#updating-the-cli

**Comment by thedarkknight197** [comment]
> Don't use global react-native-cli, use v3:
> https://github.com/react-native-community/cli#updating-the-cli

not work. i use:

"@react-native-community/cli@^3.0.0-alpha.1":
  version "3.0.0-alpha.7"
  resolved "https://registry.yarnpkg.com/@react-native-community/cli/-/cli-3.0.0-alpha.7.tgz#df8cb6a878d106da36e4f994f9d8c3541c3834ee"
  integrity sha512-gmAnmH9sqReBEvfZxk0A3gw0Ddb6UNHYvbjjyM+qgH2TbEAWCfLHLqiHNSCYxfO3hkDyz4mj/cvtb8ahFjTdIw==
  dependencies:
    "@hapi/joi" "^15.0.3"
    "@react-native-community/cli-platform-android" "^3.0.0-alpha.7"
    "@react-native-community/cli-platform-ios" "^3.0.0-alpha.7"
    "@react-native-community/cli-tools" "^3.0.0-alpha.7"
    "@react-native-community/cli-types" "^3.0.0-alpha.7"
    "@types/mkdirp" "^0.5.2"
    "@types/node-notifier" "^5.4.0"

**Comment by nuKs** [comment]
Got that after upgrading to last Android Studio version.
 
Fixed by recreating Android studio project:

```shell

$ rm android/*.iml
$ rm -r android/.idea
```

**Comment by thedarkknight197** [comment]
> Got that after upgrading to last Android Studio version.
> 
> Fixed by recreating Android studio project:
> 
> ```shell
> $ rm android/*.iml
> $ rm -r android/.idea
> ```

rm android/*.iml
rm: android/*.iml: No such file or directory

rm -r android/.idea
rm: android/.idea: No such file or directory

I use vscode

**Comment by nuKs** [comment]
@thedarkknight197 

Fixed a problem a few days ago by removing white spaces in path, don't remember if that's any related (probably not) but maybe it can do for you as well. Your copy/pasted exception has a weird line break at that level.

**Comment by thedarkknight197** [comment]
> @ thedarkknight197
> 
> Risolto un problema qualche giorno fa rimuovendo gli spazi bianchi nel percorso, non ricordare se questo è correlato (probabilmente no) ma forse può fare anche per te. La tua eccezione copia / incollata ha una strana interruzione di riga a quel livello.

ok but why if i start a new project, to default not run react-native run-android if the only command that i run are:
react-native init Project
cd Project
react-native run-android 

but react-native run-ios work?

**Comment by itsam** [comment]
In my case, everything works on terminal (npx react-native run-android), no global react-native, but I get the 
```
ERROR: Cannot invoke method getErrorStream() on null object
```
```
org.gradle.internal.exceptions.LocationAwareException: Script '/home/<MYPATH>/node_modules/@react-native-community/cli-platform-android/native_modules.gradle' line: 171
```
when trying to sync gradle inside Android Studio

Versions used: 

- react-native 3.0.0-alpha.7
- "react": "16.9.0",
- "react-native": "0.61.2"

**Comment by nuKs** [comment]
For `Cannot invoke method getErrorStream() on null object`:

Try launching Android Studio from command line so it share your env path, for OSX.
`/Applications/Android\\ Studio.app/Contents/MacOS/studio`

**Comment by nuKs** [comment]
Also cross ref https://github.com/react-native-community/cli/issues/795#issuecomment-544909119.

**Comment by itsam** [comment]
@nuKs Thanks for pointing this out. I am using kubuntu and still haven't managed to make it work. It's definitely on my side (so no react-native issues definitely) as everything works perfect in manjaro linux. I will try on my mac as well. Probably some different setup. I will inform If I could spot it.

**Comment by thedarkknight197** [comment]
i not already have a solution for my mac :/

**Comment by mdelclaro** [comment]
> For `Cannot invoke method getErrorStream() on null object`:
> 
> Try launching Android Studio from command line so it share your env path, for OSX.
> 
> ```shell
> $ /Applications/Android\\ Studio.app/Contents/MacOS/studio
> ```

This worked for me on Ubuntu 18.04, but... Every time I need to build a project I will have to lunch Android Studio through command line? :/

**Comment by fabriciocovalesci** [comment]
Bood night @mdelclaro, you managed to fix this bug in ubuntu, I have the same problem, use Ubuntu 18.08 LTS

React native --version
``` react-native-cli: 2.0.1```
```react-native: 0.61.4```

Bug :
```:ReactNative:Cannot run program "npx": error=2, Arquivo ou diretório inexistente```
```:ReactNative:Automatic import of native modules failed.```
```Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081```

**Comment by mdelclaro** [comment]
> ReactNative:Cannot run program "npx":

I'm not sure if it's the same issue, but I resolved mine by running Android Studio through the terminal, opening my project and building it. After that, I'm able to run `react-native run-android` inside the project's directory.

**Comment by farshidshahmoradi1996** [comment]
I have same issue .I init my new RN Project with `npx react-native init myapp --version 0.61.4` after run with `npx react-native run-android` .

**Comment by farshidshahmoradi1996** [comment]
I have same problem in `windows OS` with rn `0.61.4`
I remove `node (12.x.x)` and install `node (10.13.0)`
and remove `react-native-cli` with `npm uninstall react-native-cli -g`.
then init new project with `npx react-native init awesomeapp`.
then `npx react-native run-android`.
and it's work correclty .

**Comment by GlCap** [comment]
I have the same problem on `Arch Linux` with with `react-native 0.61.4`
To be noted that I am using `nvm` to manage npm versions
someone suggested that the $PATH variable isn't inherited through getRuntime().exec in this [https://github.com/react-native-community/cli/issues/795#issuecomment-549082562](url) issue on the react-native-cli repository

**Comment by quocdai92** [comment]
Make sure these packages are correct version as below:
`...`
`"@react-native-community/cli-platform-android": "^2.9.0",`
` "@react-native-community/cli-platform-ios": "^2.9.0",`
` "react": "16.9.0",`
`"react-native": "0.61.3"`
`...`

**Comment by acoutts** [comment]
I was able to fix it on mine by removing nvm and installing npm from here:
https://github.com/nodesource/distributions/blob/master/README.md

Must have been issues with the nvm path not being inherited somewhere. Kudos to @GlCap above.

**Comment by Bartmr** [comment]
NVM sets up it's environment variables in the `.bashrc` file, which only sets the environment variables for Bash. These seem to not be accessible to terminal commands ran from Gradle. The solution is to move the NVM specific code from the `.bashrc` file in the home directory to the `.profile` file, also in the home directory. This NVM specific code looks like this:
```
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
```

**Comment by GoshaEgorian** [comment]
The last string is not necessary to move, only first and second:
```bash
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
```

**Comment by Brent-rb** [comment]
For me the solution provided by @Bartmr didn't work (maybe because I use the fish shell instead of bash) so I had to resolve the issue using a different approach: symlinks.

I'd like to mention that I do NOT recommend this approach and you should use the solution mentioned by Bartmr if it works for you. With that out of the way here are the steps for my solution:

1. Find out where npx and node are installed:
`whereis npx
whereis node`
The output will be something like 
`/home/<user>/.config/nvm/10.18.1/bin/node
/home/<user>/.config/nvm/10.18.1/bin/npx`

2. Create symlinks
`sudo ln -s /home/<user>/.config/nvm/10.18.1/bin/node /usr/bin/node
sudo ln -s /home/<user>/.config/nvm/10.18.1/bin/npx /usr/bin/npx`

3. Make them executable
`sudo chmod +x /usr/bin/node
sude chmod +x /usr/bin/npx`

4. Gradle should now be able to find both npx and node.

**Comment by itsam** [comment]
The solution for me was to follow @Brent-rb and also to add in android/app/build.gradle 
```
project.ext.react = [
    entryFile: "index.js",
    enableHermes: true,  // clean and rebuild if changing
    nodeExecutableAndArgs : ["/usr/local/bin/node"] 
]
```

the line `nodeExecutableAndArgs : ["/usr/local/bin/node"] `

**Comment by GoshaEgorian** [comment]
This issue wasn't fixed just workaround found.

**Comment by srknnaydnn** [comment]
You can do that by going to {project root folder}\android\gradle\wrapper\gradle-wrapper.properties and changing the distributionUrl value to upgrade the Gradle version. You can check out here the lastest releases of Gradle https://gradle.org/releases/.

**Comment by guillaumekh** [comment]
Same issue after upgrading Android Studio to Bumblebee. I can circumvent it with `open -a /Applications/Android\ Studio.app`. Other suggested fixes fail.

I have submitted an [issue](https://issuetracker.google.com/issues/216429435) upstream to Android Studio's issue tracker.
