### ISSUE TITLE
Error Build apk in cordova : com.google.firebase:firebase-common:19.2.0/androidmanifest.xml 

### ISSUE THREAD

**Issue by wongjow0** [facebook/react-native#26931]
Error Build com.google.firebase:firebase-common:19.2.0/androidmanifest.xml 
React Native version: cli : 2.0.1

## Steps To Reproduce

1. Cordova Build --release

**Expected behavior**
Build Error
Describe what you expected to happen:

Snack, code example, screenshot, or link to a repository:
:preBuild UP-TO-DATE
:preReleaseBuild UP-TO-DATE
:checkReleaseManifest
:preDebugBuild UP-TO-DATE
:CordovaLib:preBuild UP-TO-DATE
:CordovaLib:preDebugBuild UP-TO-DATE
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugAidl UP-TO-DATE
:CordovaLib:compileDebugNdk UP-TO-DATE
:CordovaLib:compileLint UP-TO-DATE
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugShaders UP-TO-DATE
:CordovaLib:compileDebugShaders UP-TO-DATE
:CordovaLib:generateDebugAssets UP-TO-DATE
:CordovaLib:mergeDebugAssets UP-TO-DATE
:CordovaLib:mergeDebugProguardFiles UP-TO-DATE
:CordovaLib:packageDebugRenderscript UP-TO-DATE
:CordovaLib:compileDebugRenderscript UP-TO-DATE
:CordovaLib:generateDebugResValues UP-TO-DATE
:CordovaLib:generateDebugResources UP-TO-DATE
:CordovaLib:packageDebugResources UP-TO-DATE
:CordovaLib:processDebugManifest UP-TO-DATE
:CordovaLib:generateDebugBuildConfig UP-TO-DATE
:CordovaLib:processDebugResources UP-TO-DATE
:CordovaLib:generateDebugSources UP-TO-DATE
:CordovaLib:incrementalDebugJavaCompilationSafeguard UP-TO-DATE
:CordovaLib:compileDebugJavaWithJavac UP-TO-DATE
:CordovaLib:processDebugJavaRes UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForDebug UP-TO-DATE
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForDebug UP-TO-DATE
:CordovaLib:mergeDebugJniLibFolders UP-TO-DATE
:CordovaLib:transformNative_libsWithMergeJniLibsForDebug UP-TO-DATE
:CordovaLib:transformNative_libsWithSyncJniLibsForDebug UP-TO-DATE
:CordovaLib:bundleDebug UP-TO-DATE
:CordovaLib:preReleaseBuild UP-TO-DATE
:CordovaLib:checkReleaseManifest
:CordovaLib:prepareReleaseDependencies
:CordovaLib:compileReleaseAidl UP-TO-DATE
:CordovaLib:compileReleaseNdk UP-TO-DATE
:CordovaLib:copyReleaseLint UP-TO-DATE
:CordovaLib:mergeReleaseShaders UP-TO-DATE
:CordovaLib:compileReleaseShaders UP-TO-DATE
:CordovaLib:generateReleaseAssets UP-TO-DATE
:CordovaLib:mergeReleaseAssets UP-TO-DATE
:CordovaLib:mergeReleaseProguardFiles UP-TO-DATE
:CordovaLib:packageReleaseRenderscript UP-TO-DATE
:CordovaLib:compileReleaseRenderscript UP-TO-DATE
:CordovaLib:generateReleaseResValues UP-TO-DATE
:CordovaLib:generateReleaseResources UP-TO-DATE
:CordovaLib:packageReleaseResources UP-TO-DATE
:CordovaLib:processReleaseManifest UP-TO-DATE
:CordovaLib:generateReleaseBuildConfig UP-TO-DATE
:CordovaLib:processReleaseResources UP-TO-DATE
:CordovaLib:generateReleaseSources UP-TO-DATE
:CordovaLib:incrementalReleaseJavaCompilationSafeguard UP-TO-DATE
:CordovaLib:compileReleaseJavaWithJavac UP-TO-DATE
:CordovaLib:processReleaseJavaRes UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForRelease UP-TO-DATE
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForRelease UP-TO-DATE
:CordovaLib:mergeReleaseJniLibFolders UP-TO-DATE
:CordovaLib:transformNative_libsWithMergeJniLibsForRelease UP-TO-DATE
:CordovaLib:transformNative_libsWithSyncJniLibsForRelease UP-TO-DATE
:CordovaLib:bundleRelease UP-TO-DATE
:prepareAndroidArchCoreRuntime110Library UP-TO-DATE
:prepareAndroidArchLifecycleLivedataCore110Library UP-TO-DATE
:prepareAndroidArchLifecycleRuntime110Library UP-TO-DATE
:prepareAndroidArchLifecycleViewmodel110Library UP-TO-DATE
:prepareAndroidxArchCoreCoreRuntime200Library UP-TO-DATE
:prepareAndroidxAsynclayoutinflaterAsynclayoutinflater100Library UP-TO-DATE
:prepareAndroidxCoordinatorlayoutCoordinatorlayout100Library UP-TO-DATE
:prepareAndroidxCoreCore100Library UP-TO-DATE
:prepareAndroidxCursoradapterCursoradapter100Library UP-TO-DATE
:prepareAndroidxCustomviewCustomview100Library UP-TO-DATE
:prepareAndroidxDocumentfileDocumentfile100Library UP-TO-DATE
:prepareAndroidxDrawerlayoutDrawerlayout100Library UP-TO-DATE
:prepareAndroidxFragmentFragment100Library UP-TO-DATE
:prepareAndroidxInterpolatorInterpolator100Library UP-TO-DATE
:prepareAndroidxLegacyLegacySupportCoreUi100Library UP-TO-DATE
:prepareAndroidxLegacyLegacySupportCoreUtils100Library UP-TO-DATE
:prepareAndroidxLifecycleLifecycleLivedata200Library UP-TO-DATE
:prepareAndroidxLifecycleLifecycleLivedataCore200Library UP-TO-DATE
:prepareAndroidxLifecycleLifecycleRuntime200Library UP-TO-DATE
:prepareAndroidxLifecycleLifecycleViewmodel200Library UP-TO-DATE
:prepareAndroidxLoaderLoader100Library UP-TO-DATE
:prepareAndroidxLocalbroadcastmanagerLocalbroadcastmanager100Library UP-TO-DATE
:prepareAndroidxPrintPrint100Library UP-TO-DATE
:prepareAndroidxSlidingpanelayoutSlidingpanelayout100Library UP-TO-DATE
:prepareAndroidxSwiperefreshlayoutSwiperefreshlayout100Library UP-TO-DATE
:prepareAndroidxVersionedparcelableVersionedparcelable100Library UP-TO-DATE
:prepareAndroidxViewpagerViewpager100Library UP-TO-DATE
:preDebugAndroidTestBuild UP-TO-DATE
:prepareComAndroidSupportMultidex101Library UP-TO-DATE
:prepareComAndroidSupportSupportCompat2711Library UP-TO-DATE
:prepareComAndroidSupportSupportCoreUi2711Library UP-TO-DATE
:prepareComAndroidSupportSupportCoreUtils2711Library UP-TO-DATE
:prepareComAndroidSupportSupportFragment2711Library UP-TO-DATE
:prepareComAndroidSupportSupportMediaCompat2711Library UP-TO-DATE
:prepareComAndroidSupportSupportV42711Library UP-TO-DATE
:prepareComCommit451PhotoView124Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesAdsIdentifier1700Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesAnalyticsImpl1700Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesBase1710Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesBasement1700Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesClearcut1700Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesFlags1601Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesMeasurement1720Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesMeasurementApi1720Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesMeasurementBase1720Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesMeasurementImpl1720Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesMeasurementSdk1720Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesMeasurementSdkApi1720Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesPhenotype1700Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesStats1700Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesTagmanager1700Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesTagmanagerApi1700Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesTasks1700Library UP-TO-DATE
:prepareComGoogleFirebaseFirebaseAbt1900Library UP-TO-DATE
:prepareComGoogleFirebaseFirebaseAnalytics1720Library UP-TO-DATE
:prepareComGoogleFirebaseFirebaseAuth1910Library UP-TO-DATE
:prepareComGoogleFirebaseFirebaseAuthInterop1800Library UP-TO-DATE
:prepareComGoogleFirebaseFirebaseCommon1920Library UP-TO-DATE
:prepareComGoogleFirebaseFirebaseConfig1903Library UP-TO-DATE
:prepareComGoogleFirebaseFirebaseCore1720Library UP-TO-DATE
:prepareComGoogleFirebaseFirebaseCrash1621Library UP-TO-DATE
:prepareComGoogleFirebaseFirebaseIid2000Library UP-TO-DATE
:prepareComGoogleFirebaseFirebaseIidInterop1700Library UP-TO-DATE
:prepareComGoogleFirebaseFirebaseMeasurementConnector1800Library UP-TO-DATE
:prepareComGoogleFirebaseFirebaseMessaging2000Library UP-TO-DATE
:prepareComGoogleFirebaseFirebasePerf1901Library UP-TO-DATE
:prepareComSoundcloudAndroidAndroidCrop100Library UP-TO-DATE
:prepareMeLeolinShortcutBadger114Library UP-TO-DATE
:prepareOrgApacheCordovaCordovaLib630ReleaseLibrary UP-TO-DATE
:prepareReleaseDependencies
:compileReleaseAidl UP-TO-DATE
:compileReleaseRenderscript UP-TO-DATE
:generateReleaseBuildConfig UP-TO-DATE
:generateReleaseResValues UP-TO-DATE
:generateReleaseResources UP-TO-DATE
:mergeReleaseResources UP-TO-DATE
:processReleaseManifest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processReleaseManifest'.
> [com.google.firebase:firebase-common:19.2.0] G:\project\platforms\android\build
\intermediates\exploded-aar\com.google.firebase\firebase-common\19.2.0\AndroidMa
nifest.xml:13:9-17:35: Error: Invalid instruction 'targetApi', valid instruction
s are : REMOVE,REPLACE,STRICT

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

Total time: 2 mins 48.596 secs
cmd: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processReleaseManifest'.
> [com.google.firebase:firebase-common:19.2.0] G:\project\platforms\android\build
\intermediates\exploded-aar\com.google.firebase\firebase-common\19.2.0\AndroidMa
nifest.xml:13:9-17:35: Error: Invalid instruction 'targetApi', valid instruction
s are : REMOVE,REPLACE,STRICT

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

**Plugin Version**
using

**Additional context**
The build was working fine 15-10-2019

**Comment by IceRole** [comment]
same issue here any luck?

**Comment by mithabavkar** [comment]
Please provide solution on this issue.

**Comment by IceRole** [comment]
> Please provide solution on this issue.

I updated the cordova android version, then deleted the plugin and android folder and build it again
