### ISSUE TITLE
RN0.61.2 crashed on Android 5.1.1, couldn't find DSO to load: libhermes.so, lib-main/libc++_shared.so is 64-bit instead of 32-bit

### ISSUE THREAD

**Issue by hweister** [facebook/react-native#26938]
I had used the lated version of react native.

React Native version: 0.61.2

## Steps To Reproduce

1. react_native init
2.cd Android
3. ./gradlew assembleRelease
4. run the app on some android 5.1.1 machine (with vivo x7 or onePlus 2)
5. app crashed
6. here atteched fabric crash report:

Fatal Exception: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes.so caused by: couldn't find DSO to load: libc++_shared.so caused by: dlopen failed: "/data/data/xxx/lib-main/libc++_shared.so" is 64-bit instead of 32-bit
       at com.facebook.soloader.SoLoader.doLoadLibraryBySoName + 738(SoLoader.java:738)
       at com.facebook.soloader.SoLoader.loadLibraryBySoName + 591(SoLoader.java:591)
       at com.facebook.soloader.SoLoader.loadLibrary + 529(SoLoader.java:529)
       at com.facebook.soloader.SoLoader.loadLibrary + 484(SoLoader.java:484)
       at com.facebook.hermes.reactexecutor.HermesExecutor.<clinit> + 20(HermesExecutor.java:20)
       at com.facebook.hermes.reactexecutor.HermesExecutorFactory.create + 27(HermesExecutorFactory.java:27)
       at com.facebook.react.ReactInstanceManager$5.run + 952(ReactInstanceManager.java:952)
       at java.lang.Thread.run + 818(Thread.java:818)

Describe what you expected to happen:
work correctly.

Thanks

**Comment by hweister** [comment]
app/build.gradle:
`packagingOptions {
        pickFirst '**/armeabi-v7a/libc++_shared.so'
        pickFirst '**/x86/libc++_shared.so'
        pickFirst '**/arm64-v8a/libc++_shared.so'
        pickFirst '**/x86_64/libc++_shared.so'
        pickFirst '**/x86/libjsc.so'
        pickFirst '**/armeabi-v7a/libjsc.so'
    }`

android/build.gradle:
`allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }
        google()
        jcenter()

        maven { url "https://jitpack.io" }
    }
}`

**Comment by hweister** [comment]
Since vivo x7 is 64bit CPU, why libhermes.so looking for a 32 bit version of  libc++_share.so?

**Comment by BoazYago** [comment]
Reproduced on Vivo X6S A with Android 5.1.1 as well.
Using RN v0.60.4.

**Comment by RichardLindhout** [comment]
Happened for me after react-native upgrade. Started android studio and clicked build > clean project. After that it started working again ;)
