### ISSUE TITLE
image with http cannot show in my android apk pakacge

### ISSUE THREAD

**Issue by Kariko** [facebook/react-native#26937]
![image](https://user-images.githubusercontent.com/14925329/67182366-956bc480-f411-11e9-84b3-d695611635d4.png)
As what  you see, the first two image are https,  the last one is http and it cannot show. It happens in the release apk. I found many solution about it with IOS but not android.

React Native version: 0.61.1

## Steps To Reproduce

1. pack an apk, then install it on my phone.
2. go to the page i load http image.

Describe what you expected to happen: 
I want my image work even it is a http image.

Snack, code example, screenshot, or link to a repository:
![image](https://user-images.githubusercontent.com/14925329/67182734-5c801f80-f412-11e9-959c-8bc4971743f9.png)
![image](https://user-images.githubusercontent.com/14925329/67182815-8afdfa80-f412-11e9-946a-84054ba0172a.png)

**Comment by dulmandakh** [comment]
Android requires HTTPS, please read https://developer.android.com/training/articles/security-ssl.
