### ISSUE TITLE
[Android][linux] Support building/running RN android apps from linux/windows host machine

### ISSUE THREAD

**Issue by kmagiera** [facebook/react-native#2693]
This is master task for linux support of rn android. We've got a lot of issues reported for that, so to summarize:
1) Only host platform we support is OSX
2) What seems to be the only holdback are shell scripts (and apple scripts) used in packager and CLI (see #2406 that removes one of that dependency)

**Comment by SirCmpwn** [comment]
I was able to get the dev server started, but I get the red screen of death (is that a thing?) because it can't download the JS bundle. Installing iojs, will report back.

**Comment by kmagiera** [comment]
If anyone is interested in working on this here are some pointers:
https://github.com/facebook/react-native/blob/master/local-cli/run-packager.js
https://github.com/facebook/react-native/blob/master/react-native-cli/CONTRIBUTING.md

**Comment by SirCmpwn** [comment]
I'm running this on a real device, fwiw. Is that supported? Or just the emulator?

**Comment by SirCmpwn** [comment]
Result with iojs:

    node_modules/react-native/packager/packager.sh: line 19: 18593 Segmentation fault      (core dumped) node "$THIS_DIR/packager.js" "$@"

So that didn't work.

**Comment by ide** [comment]
@SirCmpwn RN 0.11 should support Node (4 and up). When you upgrade Node, clear node_modules and reinstall.

**Comment by ayosec** [comment]
> If anyone is interested in working on this here are some pointers:

So, Facebook is going to support *only* OSX platforms?

**Comment by ide** [comment]
@ayosec It runs on Linux with some small changes (launching the Chrome debugger for example) and with some changes you can get a limited version running on Windows (no Watchman). Most FB programmers use Macs so that naturally receives more attention and dogfooding.

**Comment by darkyen** [comment]
I am curious why os dependent scripts as opposed to using something like a taskrunner like gulp ? It may involve slightly higher amount of work but the end result is usually easily portable and less bugs + gulp / grunt both have excellent plugins that exist.

**Comment by vjeux** [comment]
@darkyen: because it was easier to just write down some bash scripts. But indeed we need to move them in js

**Comment by despairblue** [comment]
Might be easier to port it to [shelljs](https://github.com/shelljs/shelljs) instead of gulp/grunt/etc.

**Comment by kmagiera** [comment]
@despairblue Seems like shelljs won't solve the issues on windows.

**Comment by despairblue** [comment]
I think I missed that, which issues do you mean specifically? Opening chrome seems to be covered by #2406 and invoking gradle (part of react-native-cli, but still mentioning it) can be done via [shelljs' exec command](http://documentup.com/shelljs/shelljs#execcommand--options--callback) even on windows, at least the documentation does not note that exec won't work on windows.

Or do you mean the main problem on windows is not having watchman?

**Comment by nikhildaga** [comment]
Looks like you are willing to support platforms other than OSX. Saved me a 1000+ dollars. Thank you!

**Comment by nicolas-despres** [comment]
I am very interested by the windows support as well. Tks all!

**Comment by BerndWessels** [comment]
+1 Basically React-Native for Android works on Windows now if you follow the mentioned issues which have the fixes and workarounds you need to make to get it running.

I am using it for about a week now and it works great with the simulator and my real Samsung Galaxy S4 device.

I really hope you guys will integrate all the necessary fixes into master soon, so that everybody can start using React-Native and build great components.

Cheers
Bernd

**Comment by ippa** [comment]
Thanks Bernd for your personal interest in getting this matter solved. I'm one of those that got bitten by this, found all the githubissues but is waiting for an official release.

**Comment by rockneverdies55** [comment]
Can someone please tell what exactly needs to be done to develop with react.native on linux?

**Comment by mkonicek** [comment]
@rockneverdies55 Everything works on Linux except:
- `react-native run-android` can't open a new Window, you need to use `react-native start`. Will be fixed in next release
- Debugging in Chrome currently relies on an AppleScript to launch Chrome. There's a PR to replace that.

**Comment by rockneverdies55** [comment]
Great to hear. Thank you @mkonicek .

I believe this should be stated in [getting started guide](https://facebook.github.io/react-native/docs/getting-started.html)

**Comment by mkonicek** [comment]
We'd like to document Linux support once it's fully working.

**Comment by mkonicek** [comment]
Actually feel free to send a PR to Getting Started that links to this issue.

**Comment by beberlei** [comment]
Launching the Chrome dev tools is done with an applescript in `node_modules/react-native/packager/packager.js` calling `node_modules/react-native/packager/launchChromeDevTools.applescript`. This should probably be converted to a shell script, the following two liner shell script worked for me:

    #!/bin/bah
    google-chrome $1

**Comment by despairblue** [comment]
The script should probably test for different binaries. On arch linux, the
installed binaries could be `chromium` or `google-chrome-stable`, the
latter should probably be preferred if installed, though chromium works
just fine as well.

Even preferably is a JavaScript solution in my opinion.

On Thu, Oct 8, 2015, 02:38 Benjamin Eberlei <notifications@github.com>
wrote:

> Launching the Chrome dev tools is done with an applescript in
> node_modules/react-native/packager/packager.js calling
> node_modules/react-native/packager/launchChromeDevTools.applescript. This
> should probably be converted to a shell script, the following two liner
> shell script worked for me:
>
> #!/bin/bah
> google-chrome $1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/facebook/react-native/issues/2693#issuecomment-146380190>
> .
>
-- 
--------------------------------------------
Q: Why is this email five sentences or less?
A: http://five.sentenc.es

**Comment by davidgilbertson** [comment]
@beberlei will that work for Windows?

**Comment by beberlei** [comment]
@davidgilbertson no, it just works on Linux. We should move that code completly to javascript i guess.

**Comment by guillaume86** [comment]
[Karma chrome launcher](https://github.com/karma-runner/karma-chrome-launcher) should be a good start to do that.

**Comment by PaulBGD** [comment]
After running everything in git bash and doing `sh node_modules/react-native/packager/packager.js` to start the server, it looks like it's running nearly perfectly on Windows.

**Comment by davidgilbertson** [comment]
@PaulBGD if you change the `package.json` start script to `"start": "node node_modules/react-native/packager/packager.js"` you can then just start the server with `npm start`.

**Comment by PaulBGD** [comment]
@davidgilbertson Ah okay, I wasn't sure if anything the sh file was doing was important.

**Comment by PaulBGD** [comment]
I noticed @ide said earlier you can get Windows running without watchman, however live reloading and such was working fine for me. Not sure if that's new or not.

**Comment by mkonicek** [comment]
The status is now tracked here, feel free to send pull requests: https://github.com/facebook/react-native/blob/master/docs/LinuxWindowsSupport.md

I'll close this issue.
