### ISSUE TITLE
Fetch API returns Network request failed on some websites.

### ISSUE THREAD

**Issue by crimson-med** [facebook/react-native#26939]
fetch API return `Network request failed` only on some websites.
I was trying to ping the api from my website and found out I kept getting a request error. I can ping the url via postman as a normal get request but for some reason the Fetch API won't let me.

This happens when debugging on Android (note 9)

React Native version:
```
  React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
      Memory: 19.91 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.9.1 - /usr/local/bin/node
      Yarn: 1.19.1 - ~/.yarn/bin/yarn
      npm: 6.12.0 - ~/.config/yarn/global/node_modules/.bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 27, 28
        Build Tools: 28.0.3
        System Images: android-24 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.1 AI-173.4697961
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
```

## Steps To Reproduce

1. Fetch a famous url (facebook , google) no issue.
2. Fetch a less famous url (crash)

Describe what you expected to happen:

Snack, code example, screenshot, or link to a repository:

https://snack.expo.io/SkFgBWoFH

Code to reproduce:

```js
fetch('https://facebook.github.io/react-native/movies.json')
    .then(response => {
        console.log(response);
    })
    .catch(function(err) {
        console.info(err);
    });

fetch('https://pixiumdigital.com')
    .then(response => {
        console.log(response);
    })
    .catch(function(err) {
        console.info(err);
    });
```

**Comment by crimson-med** [comment]
This issue has never been fixed as it was never picked up dear bot.

**Comment by andrekristanto1798** [comment]
any updates?

**Comment by antoinerousseau** [comment]
Same here, in Android only (both debug and release), for example trying to `fetch("https://www.mocky.io/v2/5185415ba171ea3a00704eed")` raises a `NetworkError`.

**Comment by antoinerousseau** [comment]
Update, after doing some [tests](https://gist.github.com/antoinerousseau/ddafa517cf6cb35331291cc966d84095), we came to the conclusion that it's due to failing SSL certificates. We don't know what's wrong with these, but the issue also happens in Postman with the "SSL certificate verification" option enabled. Could it be that the certificate authority is not in the phone's list?

**Comment by antoinerousseau** [comment]
I tried to apply https://github.com/facebook/flipper/issues/993#issuecomment-619823916 but I'm still getting the same `Network request failed` with that new Flipper 0.39.0 when trying to `fetch("https://www.mocky.io/v2/5185415ba171ea3a00704eed")`, even though it works in Chrome/Firefox/Safari.

**Comment by abumostafa** [comment]
> I tried to apply [facebook/flipper#993 (comment)](https://github.com/facebook/flipper/issues/993#issuecomment-619823916) but I'm still getting the same `Network request failed` with that new Flipper 0.39.0 when trying to `fetch("https://www.mocky.io/v2/5185415ba171ea3a00704eed")`, even though it works in Chrome/Firefox/Safari.

I had similar issues with Android. It was happening because my Nginx SSL was not compatible with android.

Try comparing both the working URL and the not working one using `SSL` check services like https://www.ssllabs.com/ssltest/

**Comment by antoinerousseau** [comment]
Well it's just B-graded, is that so bad?
https://www.ssllabs.com/ssltest/analyze.html?d=www.mocky.io

**Comment by scgough** [comment]
I'm also seeing this since upgrading to RN0.62 from 0.59x. 
It occurs for both iOS and Android apps when debugging on my physical devices. 

I've tried updating Flipper to 0.41.0 on the Android side of things w/ no luck.

As an aside, if I build the apps in release mode this bypasses the issue (obviously as Flipper isn't in the mix).

**Comment by geremora** [comment]
I'm getting randomly network errors in our app in IOS.  1 or 2 of 20 requests fail and said network error. Are like randomly.  I did a stress test from the postman and hundreds of requests works ok and response code 200.

**Comment by crimson-med** [comment]
I don't think this is stale as a few people have had the same issue and this was never addressed.
