### ISSUE TITLE
STUCK AT "Loading dependency graph, done."

### ISSUE THREAD

**Issue by Jackie1210** [facebook/react-native#26934]
I run `react-native run-ios` and then the second window stuck at "Loading dependency graph, done."

React Native version:
System:
    OS: macOS Mojave 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 137.85 MB / 8.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 28
      Build Tools: 28.0.3
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.3 AI-182.5107.16.33.5314842
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.2 => 0.61.2

## Steps To Reproduce

1. run `react-native init myApp`
2.`cd myApp`
3.`react-native run-ios`

Describe what you expected to happen:

run app successfully.

Snack, code example, screenshot, or link to a repository:
![31571638746_ pic_hd](https://user-images.githubusercontent.com/14737221/67180989-d82b9d80-f40d-11e9-949f-4fa39637cb9b.jpg)

------
Hey, guys! I have found the **SOLUTION**: 

**change your host**

You can download an app called 'SwitchHosts'

HERE IS LINK : [SwitchHosts](https://github.com/oldj/SwitchHosts/releases)

once you download it, you can change your host like this:

![image](https://user-images.githubusercontent.com/14737221/67365262-e01d4600-f5a3-11e9-9522-f64bec156450.png)

enjoy using RN :v:

**Comment by ashadnasim52** [comment]
same issue struggling

**Comment by ifyapishore** [comment]
https://github.com/facebook/react-native/issues/16798#issuecomment-430460451

You really need to show more clear message like "Server is READY". A lot of people confused by current message.

**Comment by Jackie1210** [comment]
@ifyapishore Thanks for your reply.I am new to RN. What i've done is follow the steps the RN site shows.like what i said:`react-native init myApp``cd myApp``react-native run-ios`. And all the results is hanging on 'Loading dependency graph, done'.Anyway, i will keep going to find the solution.

**Comment by Jackie1210** [comment]
I've give a solution and update it in my issue above.Hope it can help you if you are struggling! ❤️

**Comment by 349989153** [comment]
Well, I tried to downgrade node version from 12.4 to 10.16.0 AND use react-native start --reset-cache BUT STILL IN STUCK.

However, I tried sudo npm start --reset-cache(NOT sudo react-native start --reset-cache), and IT FINALLY WORKED!

You gotta be kidding me...
