### ISSUE TITLE
Network requests are not working on android target build 29, seems to work for 27

### ISSUE THREAD

**Issue by 82rules** [facebook/react-native#26944]
Networking is broken on brand new React native project on android. There is no outbound network request registered, and promises fail to trigger either then or catch.

React Native version:
System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
    Memory: 198.49 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.11.1 - ~/.nvm/versions/node/v12.11.1/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.11.3 - ~/.nvm/versions/node/v12.11.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.2 => 0.61.2

## Steps To Reproduce

1. react-native init networktest
2. cd networktest
3. react-native run-android
4. trigger a fetch request to https://google.com and log info, here is an example

```/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * @format
 * @flow
 */

import React from 'react';
import {
  SafeAreaView,
  StyleSheet,
  ScrollView,
  View,
  Text,
  TouchableOpacity,
  StatusBar,
} from 'react-native';

import {
  Header,
  Colors,
} from 'react-native/Libraries/NewAppScreen';

class App extends React.Component {

  clicked = () => {
    console.log('hit');
    fetch('https://google.com')
      .then(response => {
        console.log('worked');
        console.log(response);
      })
      .catch(() => {
        console.log('failed');
      });
  }
  render() {
    return (
      <>
        <StatusBar barStyle="dark-content" />
        <SafeAreaView>
          <ScrollView
            contentInsetAdjustmentBehavior="automatic"
            style={styles.scrollView}>
            <Header />
            <TouchableOpacity onPress={this.clicked}>
              <Text>Press Me</Text>
            </TouchableOpacity>
          </ScrollView>
        </SafeAreaView>
      </>
    );
  }

};

const styles = StyleSheet.create({
  scrollView: {
    backgroundColor: Colors.lighter,
  },
  engine: {
    position: 'absolute',
    right: 0,
  },
  body: {
    backgroundColor: Colors.white,
  },
  sectionContainer: {
    marginTop: 32,
    paddingHorizontal: 24,
  },
  sectionTitle: {
    fontSize: 24,
    fontWeight: '600',
    color: Colors.black,
  },
  sectionDescription: {
    marginTop: 8,
    fontSize: 18,
    fontWeight: '400',
    color: Colors.dark,
  },
  highlight: {
    fontWeight: '700',
  },
  footer: {
    color: Colors.dark,
    fontSize: 12,
    fontWeight: '600',
    padding: 4,
    paddingRight: 12,
    textAlign: 'right',
  },
});

export default App;

```

Describe what you expected to happen:
hit is seen on both 29 and 27, but I expected to see either a worked or failed console log, but I get nothing. No errors, no response, nothing. On 27 I get worked, on 29 I get nothing.

I also opened an ngrok to a local api to see if there was any network request even made. Ngrok registered no inbound request at any point. The app seems to fail to even make a request let alone handle the response.

**Comment by 1051435548** [comment]
Hello, I have the same problem with you. Can you solve it?

**Comment by HarshitMadhav** [comment]
Try this solution https://stackoverflow.com/questions/51902629/how-to-allow-all-network-connection-types-http-and-https-in-android-9-pie/55834683#55834683

**Comment by glburgess** [comment]
I am having what seems like this same problem:
https://stackoverflow.com/questions/58907840/fetch-get-request-not-getting-to-api-on-android

If I put the response into console.warn(response) I get "Syntax Error: JSON Parse Error unexpected EOF parse@[native code]"

The API I'm trying to reach is HTTPS through AWS API Gateway, and doesn't show that it has been reached at all.

**Comment by inpendio** [comment]
I believe I have same error. After second/third ( sometimes even on first) fetch, app just crashes/ or reloads.
`System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 20.70 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.13.0 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 17, 25, 27, 28
      Build Tools: 26.0.3, 27.0.0, 27.0.1, 27.0.2, 27.0.3, 28.0.0, 28.0.0, 28.0.0, 28.0.1, 28.0.2, 28.0.3
      System Images: android-17 | ARM EABI v7a, android-17 | MIPS, android-17 | Intel x86 Atom, android-17 | Google APIs ARM EABI v7a, android-17 | Google APIs Intel x86 Atom, android-19 | Google APIs Intel x86 Atom, android-25 | China version of Android Wear ARM EABI v7a, android-25 | China version of Android Wear Intel x86 Atom, android-25 | Android Wear ARM EABI v7a, android-25 | Android Wear Intel x86 Atom, android-25 | Intel x86 Atom, android-25 | Intel x86 Atom_64, android-25 | Google APIs ARM 64 v8a, android-25 | Google APIs ARM EABI v7a, android-25 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom_64, android-25 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.3 AI-182.5107.16.33.5314842
    Xcode: 11.2/11B52 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-create-library: 3.1.2
    react-native-git-upgrade: 0.2.7`

I get this error in log cat:

`E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
    Process: com.pheonixmobile, PID: 22667
    java.lang.OutOfMemoryError: Failed to allocate a 113246216 byte allocation with 25165824 free bytes and 93MB until OOM, max allowed footprint 128275992, growth limit 201326592
        at java.util.Arrays.copyOf(Arrays.java:3260)
        at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:125)
        at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:605)
        at java.lang.StringBuilder.append(StringBuilder.java:191)
        at android.util.JsonReader.nextString(JsonReader.java:901)
        at android.util.JsonReader.nextValue(JsonReader.java:708)
        at android.util.JsonReader.objectValue(JsonReader.java:691)
        at android.util.JsonReader.peek(JsonReader.java:347)
        at com.facebook.react.devsupport.JSDebuggerWebSocketClient.onMessage(JSDebuggerWebSocketClient.java:187)
        at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:323)
        at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:219)
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:105)
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:274)
        at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:214)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)`

**Comment by glburgess** [comment]
Inpendio which method are you trying to use with fetch?

**Comment by glburgess** [comment]
> Try this solution https://stackoverflow.com/questions/51902629/how-to-allow-all-network-connection-types-http-and-https-in-android-9-pie/55834683#55834683

I haven’t tried this because I don’t know of a way to change that in the manifest while in Expo. But I am making a call to an API with HTTPS and a SSL, so this shouldn’t be an issue.

**Comment by inpendio** [comment]
> Inpendio which method are you trying to use with fetch?

Tried both http and https.

**Comment by glburgess** [comment]
> > Inpendio which method are you trying to use with fetch?
> 
> Tried both http and https.

Was it a GET req. or POST (some people have had trouble with Fetch / okhttp adding a header in a POST req.)?

**Comment by inpendio** [comment]
> > > Inpendio which method are you trying to use with fetch?
> > 
> > 
> > Tried both http and https.
> 
> Was it a GET req. or POST (some people have had trouble with Fetch / okhttp adding a header in a POST req.)?

Both GET.

**Comment by eyalabadi98** [comment]
Any updates here? I'm facing the same issue with AWS @inpendio

**Comment by inpendio** [comment]
> Any updates here? I'm facing the same issue with AWS @inpendio

nope, nothing new...

**Comment by glburgess** [comment]
I’m not sure what your actual code is and since your reproduction it simple and straight forward I don’t think my issue was the same(sorry). I fixed my problem by taking the MySQL wildcards (%) out of my URL string and putting them into the backend in node.js.  Apparently wildcard characters that will work on iOS do not Android. Sorry I’m no help!
