### ISSUE TITLE
RN ^0.61.2 Fonts don't render

### ISSUE THREAD

**Issue by oviedo97fer** [facebook/react-native#26943]
React Native version: 0.61.2
## Problem
Fonts don't render when run app. 
No errors logs,
No errors build.
Just, doesn't show font style
## Steps To Reproduce

1. Add fonts assets to `react-native-config.js`
![image](https://user-images.githubusercontent.com/37948156/67214716-980cf080-f3f6-11e9-900e-0195ef329116.png)

2. Run `react-native link`
3. Result: 
![image](https://user-images.githubusercontent.com/37948156/67214670-8297c680-f3f6-11e9-91ae-b20058251e17.png)
4. `fontFamily: 'Poppins'`

System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
    Memory: 3.76 GB / 11.90 GB
  Binaries:
    Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.11.3 - C:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 27.0.3, 28.0.3, 29.0.2
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel 
x86 Atom, android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5791312
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.2 => 0.61.2

**Comment by Huzaifaak** [comment]
They render correctly. I did this today. I guess you are missing a step where you have to put them in your android folder aswell. android/buid/main/assets/fonts

**Comment by oviedo97fer** [comment]
> They render correctly. I did this today. I guess you are missing a step where you have to put them in your android folder aswell. android/buid/main/assets/fonts

:/ Works when I've add fonts .ttf in `android/app/src/main/assets/fonts`
