### ISSUE TITLE
Image component not invoking onError when the image uri is an empty string

### ISSUE THREAD

**Issue by DaniAkash** [facebook/react-native#26942]
React Native version: 0.61

## Steps To Reproduce
The following code snippet wouldn't invoke onError event
```jsx
export default class App extends React.Component {

  onImageError = () => {
    alert("Image failed to load");
  }

  render() {
    return (
      <View style={styles.container}>
        <Image source={{uri: ""}} onError={this.onImageError} />
      </View>
    );
  }
}
```

Describe what you expected to happen:
`onError` should be invoked since empty string is not a valid image url

Snack, code example, screenshot, or link to a repository:
https://snack.expo.io/@daniakash/image-component-issue

**Comment by DaniAkash** [comment]
The issue hasn't been fixed sadly...

**Comment by DaniAkash** [comment]
Thanks for reminding me. Let me check with the latest version...

**Comment by DaniAkash** [comment]
No idea when this is going to be fixed...

**Comment by DaniAkash** [comment]
Unfortunately, I'm unable to add labels to this issue for some reason... But yeah this issue still exists. I have updated the snack to work with latest expo sdk

**Comment by DaniAkash** [comment]
Verified. This issue is fixed now xD 🎉

**Comment by sagrawalcb** [comment]
still facing the issue

**Comment by KryptKode** [comment]
Same here.
