### ISSUE TITLE
`runAfterIteractions` nested works terribly 

### ISSUE THREAD

**Issue by kangbb** [facebook/react-native#26949]
## `react-native` version

```sh
info 
  React Native Environment Info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
      CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
      Memory: 328.77 MB / 7.68 GB
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 10.16.3 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5900203
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
```
## Steps To Reproduce

I use `runAfterIteractions` to do a modal switch. With the simple switch, it works well. And I want to add a time-consuming task after switch, by `runAfterIteractions` nested. It looks like:

```sh
set first-modal-visible false;
runAfterInteractions(()=> {
  set second-modal-visible true;
  runAfterInteractions(()=> {
    run time-consuming task;
  });
});
```
Actually, it will run the task, then do a `Modal` switch. What's the reason?

## Describe what you expected to happen

 I want to add a time-consuming task after `Modal` switch. But, actually, the task will run before `Modal` switch.

**Comment by kangbb** [comment]
> Thanks for submitting your issue. Can you take another look at your description and make sure the issue template has been filled in its entirety?
> 
>  [Click here if you want to take another look at the Bug Report issue template.](https://github.com/facebook/react-native/issues/new?template=bug_report.md)

I have done it.

**Comment by safaiyeh** [comment]
Hi @kangbb, thank you for the issue.

Can you include some more information for this can be investigated:
• Verify it happens on the latest RN version
• Provide a Snack or reproducible demo
