### ISSUE TITLE
[0.61.2] Can't bundle/assemble release, debug works

### ISSUE THREAD

**Issue by SirKadogan** [facebook/react-native#26959]
I updated my project to 0.61.2 to make use of hermes to shrink my app size and now I can't generate a release version. I tested with a new app and the same error happens:

`A problem occurred starting process 'command '..\..\node_modules\hermes-engine\win64-bin\hermes''`

I also get this other error in my project, didn't try to reproduce it here. I get either one

`error ENOENT: no such file or directory, open 'C:\Users\Thales\myOtherProject\android\app\build\intermediates\sourcemaps\react\release\index.android.bundle.packager.map'`

I've tried cleaning, rebuilding, updating the CLI, recreating node_modules, checking the path to hermes-engine and still nothing.

React Native version:
 OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i7-3517U CPU @ 1.90GHz
    Memory: 2.38 GB / 7.89 GB
  Binaries:
    Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.12.0 - C:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 16, 20, 23, 25, 26, 27, 28, 29
      Build Tools: 23.0.1, 25.0.1, 26.0.1, 26.0.2, 26.0.3, 27.0.1, 27.0.3, 28.0.0, 28.0.2, 28.0.3, 29.0.2
      System Images: android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-27 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5900203
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.2 => 0.61.2

## Steps To Reproduce

1. react-native init newApp
2. Enable Hermes and Proguard
3. react-native run-android --variant=release

Describe what you expected to happen:
Should generate a release apk and install app on device/emulator

**Comment by zrelyydereva** [comment]
I'm on same status and I modified react.gradle L19
```
- def hermesCommand = config.hermesCommand ?: "../../node_modules/hermes-engine/%OS-BIN%/hermes"
+ def hermesCommand = config.hermesCommand ?: "../node_modules/hermes-engine/%OS-BIN%/hermes"
```
that's works for me, but I don't know background of these path.
somebody can make it sure?

**Comment by zrelyydereva** [comment]
I've found some useful variables,so used it for hermes path.
Can someone review this patch?
If I can,I'll make a PR(but this is my second PR in my life,please teach me how to. )
I want to support React Native to being more Exelent.

**Comment by excitedcat** [comment]
Node memory out of range caused this problem, bundle file generate failure. 

# The way to fix this:

![image](https://user-images.githubusercontent.com/8253512/67755914-034c6780-fa74-11e9-9ddf-39e46f2b7bc0.png)

# Bundle React Native code and images
Add this line `export NODE_OPTIONS=--max_old_space_size=4096` 

@zrelyydereva @mojodna @jsierles

**Comment by SirKadogan** [comment]
I haven't had time to check on this issue again, I'll do as soon as possible and see if your fix does the job for me

**Comment by ammarRajabA** [comment]
This issue happens with me as well , Windows 10 using React-Native 0.60.5

Instead of the mentioned above I go to `android/app` folder and run `../gradlew assembleRelease` for example to work. from `android` using `./gradlew assembleRelease` not finding hermese although it's there!
