### ISSUE TITLE
listView item delete not properly removing item

### ISSUE THREAD

**Issue by Joshuabaker2** [facebook/react-native#2696]
Running some example code, I am running into an issue where the listView does not properly rerender a list that has been modified. For example, I have a hardcoded array of objects like:
```
datasetsItems = [
 {firstObjectWithMultipleParams},
 {secondObjectWithMultipleParams},
 ...
]
```
Then I created a button that did the following: 
```
datasetsItems.splice(1,1) // To delete the object at index 1
this.setState({dataSource: this.state.dataSource.cloneWithRows(
			datasetsItems
		    )});
```
However, this renders it with the last object in the array deleted, not the one specified at the index. I checked in the debugger and the splice function is working properly and deleting the requested object so it is not an issue with the splicing function. 

I then tried the following: 
```
datasetsItems = [...datasetsItems.slice(0,1),...datasetsItems.slice(2,datasetsItems.length)];
this.setState({dataSource: this.state.dataSource.cloneWithRows(
			datasetsItems
		    )});
```

And this works and renders the list as expected without the object at index 1. So then I did the following, just to test: 

```
datasetsItems.splice(1,1);
let newDs = datasetsItems.slice();
this.setState({dataSource: this.state.dataSource.cloneWithRows(
			newDs
		      )});
```
But this doesn't work, and fails in the same way as the first example. 

Is there a reason for this behaviour? I am also wondering if the way I am doing it with slicing gets rid of React's ability to just modify the changed row and therefore fully rerenders everything?

**Comment by MossP** [comment]
Are you keying your cells? and what compare rule does your datasource use?

**Comment by Joshuabaker2** [comment]
I am keying them with the key={rowID} during the renderRow. The compare rule uses the same on in the tutorial, the ```{rowHasChanged: (row1, row2) => row1 !== row2})```. I found that slicing and then splicing also works as well.

**Comment by brentvatne** [comment]
Hi there!

This kind of question is best suited for StackOverflow -- as far as I know there aren't any bugs with this and we use the issues for bug reports and feature requests.

If you repost there and it turns out there is a bug I'd be happy to reopen this issue! Thanks and good luck!

**Comment by khetaram** [comment]
Can you post code for full list view and deletion of item??
