### ISSUE TITLE
invalid regular expression

### ISSUE THREAD

**Issue by Niteshsingh007** [facebook/react-native#26969]
error Invalid regular expression: /(.*\\__fixtures__\\.*|node_modules[\\\]react[
\\\]dist[\\\].*|website\\node_modules\\.*|heapCapture\\bundle\.js|.*\\__tests__\
\.*)$/: Unterminated character class. Run CLI with --verbose flag for more detai
ls.

React Native version:

## Steps To Reproduce

1.
2.

Describe what you expected to happen:

Snack, code example, screenshot, or link to a repository:

**Comment by ecreeth** [comment]
Do you can provide the steps to reproduce?

**Comment by FLGMwt** [comment]
As mentioned in https://github.com/facebook/react-native/issues/26598#issuecomment-546520915, you should be able to fix this by using node version 12.9.1 or earlier.

**Comment by cpojer** [comment]
Thank you for your report. We fixed this just now with the release of Metro 0.56.4 and 0.57.0. Update your packages and re-create your project and things should work for you again :) Sorry for the inconvenience.
