### ISSUE TITLE
Xcode11 + iPhone Xs Max Device（iOS13）Crash When Caller 'CIFilter' 

### ISSUE THREAD

**Issue by AbeiOS** [facebook/react-native#26964]
React Native version:

## Steps To Reproduce

crash in fishhook.c line:106 
code: indirect_symbol_bindings[i] = cur->rebindings[j].replacement;

Describe what you expected to happen:

Snack, code example, screenshot, or link to a repository:

**Comment by cgxy1995** [comment]
I also have this problem.... can't resolve it. please help!!

**Comment by luzetian** [comment]
me,please help!!

**Comment by sathyaZomato** [comment]
Facing the same problem when I run the code on a device.
Please update the fishhook node_module dependency to the latest version.
Had to place null checks and array limit checks in fishhook (line:106) to avoid the crash:
if (indirect_symbol_bindings != NULL && sizeof(indirect_symbol_bindings) > i &&
     cur != NULL && cur->rebindings != NULL && sizeof(cur->rebindings) > j) {
          indirect_symbol_bindings[i] = cur->rebindings[j].replacement;
}

**Comment by trevyn** [comment]
+1

**Comment by AbeiOS** [comment]
Replace 'fishhook.c' with latest https://github.com/facebook/fishhook 

then solve it
