### ISSUE TITLE
ReactNativeModules$_addReactNativeModuleDependencies_closure

### ISSUE THREAD

**Issue by andreasasprou** [facebook/react-native#26974]
React Native version:
System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 154.96 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.11.1 - /var/folders/rv/n6_yg0ks5qv1n76vzyljgrw40000gn/T/yarn--1571841618307-0.9902893914720248/node
    Yarn: 1.19.1 - /var/folders/rv/n6_yg0ks5qv1n76vzyljgrw40000gn/T/yarn--1571841618307-0.9902893914720248/yarn
    npm: 6.11.3 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 25, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.2 => 0.61.2

## Steps To Reproduce

```
react-native run-android

...

info Installing the app...

FAILURE: Build failed with an exception.

* Where:
Script '/Users/andyasprou/Documents/flick/FlickAssistant/node_modules/@react-native-community/cli-platform-android/native_modules.gradle' line: 102

* What went wrong:
A problem occurred evaluating project ':app'.
> ReactNativeModules$_addReactNativeModuleDependencies_closure2
```

Describe what you expected to happen:

To build and run the app in an android simulator

**Comment by refo** [comment]
I was getting the same error due to having an gradle version older than project requires.
Removing .gradle folder in the user directory solved my problem.

```bash
rm -rf ~/.gradle
```

**Comment by rolivegab** [comment]
Had the same problem, and @refo solution worked to me!
