### ISSUE TITLE
Error about cli during launching after upgrading nodejs to 12.13.0

### ISSUE THREAD

**Issue by emclab** [facebook/react-native#26977]
Upgraded nodejs to 12.13.0 from 10.13.6. Launching react native app throws error when `react-native run-android`:

`FAILURE: Build failed with an exception.

* Where:
Script 'C:\D\code\js\emps_fe6\node_modules\@react-native-community\cli-platform-android\native_modules.gradle' line: 182

* What went wrong:
A problem occurred evaluating script.
> Text must not be null or empty`

React Native version:

info Fetching system and libraries information...
System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
    Memory: 705.94 MB / 7.76 GB
  Binaries:
    Node: 12.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 27, 28, 29
      Build Tools: 27.0.3, 28.0.3, 29.0.0, 29.0.0
      System Images: android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5522156
  npmPackages:
    react: 16.11.0 => 16.11.0
    react-native: 0.61.2 => 0.61.2

## Steps To Reproduce

1. upgrading nodejs to 12.13.0
2. launch app for android emulator: react-native run-android

Describe what you expected to happen:

Snack, code example, screenshot, or link to a repository:

**Comment by NyauIf** [comment]
There is currently a bug in Facebook-Metro when you are using a version greater than Node 12.10.8 
I think. A solution would be to downgrade again or make this https://github.com/facebook/metro/pull/464 very small change your self 
`But your error message Text must not be null or empty` dose not fit to that.
May be you have somewhere a empty Text component
