### ISSUE TITLE
Flash of white LaunchScreen.xib after splash screen (iOS)

### ISSUE THREAD

**Issue by JeremyBradshaw7** [facebook/react-native#26971]
I'm seeing the standard white screen (LaunchScreen.xib) displayed after my splash screen for a second or two on production builds, this is the one with the app name and the "Powered by React Native" label below. We don't want this displayed at all, and it never used to be but I think came in after upgrading to RN 0.59.10. 

The building for production advice hasn't changed and still says:

> As your App Bundle grows in size, you may start to see a blank screen flash between your splash screen and the display of your root application view. If this is the case, you can add the following code to AppDelegate.m in order to keep your splash screen displayed during the transition.
> 
>   // Place this code after "[self.window makeKeyAndVisible]" and before "return YES;"
>   UIView* launchScreenView = [[[NSBundle mainBundle] loadNibNamed:@"LaunchScreen" owner:self options:nil] objectAtIndex:0];
>   launchScreenView.frame = self.window.bounds;
>   rootView.loadingView = launchScreenView;

So we still do this. Is this the same "blank" screen as I'm seeing? Is a change needed here? Should it still work?

React Native version:
```
~/ccf * PHASE5 > react-native info
info
  React Native Environment Info:
    System:
      OS: macOS 10.14.6
      CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
      Memory: 74.38 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.5.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.10.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 23.0.1, 23.0.2, 25.0.0, 25.0.1, 25.0.2, 26.0.2, 26.0.3, 27.0.0, 27.0.3, 28.0.2, 28.0.3
        System Images: android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: ^0.59.10 => 0.59.10
    npmGlobalPackages:
      create-react-native-typescript-app: 1.2.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
      react-native-html-to-pdf: 0.7.0
      react-native-log-ios: 1.0.1
      react-native-rename: 2.2.2
      react-native-spinkit: 1.3.0
```

## Steps To Reproduce

1. Do a production build on an app with splash screens (as generated by generator-rn-toolbox)
2. Deploy to iOS device and start it up, see the splash screen quickly replaced by white "Powered by React Native" screen for a few seconds, then app.

Describe what you expected to happen:
- splash screen should stay up until app ready.

**Comment by TikiTDO** [comment]
This doesn't seem to really be fixed, if it needs extra 3rd party libs.

**Comment by JeremyBradshaw7** [comment]
Happy to re-open if you are experiencing the same issue with 0.61

**Comment by maxowy** [comment]
In AppDelegate.m replace `[RNSplashScreen show];`
with `[RNSplashScreen showSplash:@"LaunchScreen" inRootView:rootView];`

**Comment by MingyuJeon** [comment]
@maxowy, it doesn't work in my case.
```
"react": "16.9.0",
"react-native": "0.61.5"
```
