### ISSUE TITLE
Fresh Project fail to start 

### ISSUE THREAD

**Issue by waqaramjad** [facebook/react-native#26973]
React Native version:
tem:
    OS: Windows 10
    CPU: (4) ia32 Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
    Memory: 1.64 GB / 7.89 GB
  Binaries:
    Node: 8.9.4 - C:\Program Files (x86)\nodejs\node.EXE
    npm: 5.6.0 - C:\Program Files (x86)\nodejs\npm.CMD
  IDEs:
    Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5791312
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.1 => 0.61.2

## Steps To Reproduce

1. `react-native init projectName`
2. `react-native run-android`

Describe what you expected to happen:
i am expected my project start without errors 

Snack, code example, screenshot, or link to a repository:
i have a fresh project and i did not make any changes to it 

here is the console error that i am facing 

`FAILURE: Build failed with an exception.

* Where:
Script 'E:\RN projects\EximApp\node_modules\@react-native-community\cli-platform-android\native_modules.gradle' line: 182        

* What went wrong:
A problem occurred evaluating script.
> Unable to determine the current character, it is not a string, number, array, or object
  
  The current character read is 'E' with an int value of 69
  Unable to determine the current character, it is not a string, number, array, or object
  line number 1
  index number 0`

**Comment by mmahdigh** [comment]
Could you share your project via a git repo so we can investigate it further?

**Comment by waqaramjad** [comment]
i am going to closed that issue 
it's due to node version 
i upgraded from 8.0.9 to 12.0.0 and it work fine 
don't install node v 12.11.0 it have a bug

**Comment by waqaramjad** [comment]
i am going to closed that issue 
it's due to node version 
i upgraded from 8.0.9 to 12.0.0 and it work fine 
don't install node v 12.11.0 it have a bug
