### ISSUE TITLE
[docs]When deploying react-native server whether  need to jsx transform to js use some tools like react-tools

### ISSUE THREAD

**Issue by cheyueyong** [facebook/react-native#2698]
same as to title.

**Comment by brentvatne** [comment]
When you are going to deploy to the app store you just need to run `react-native bundle` and make sure that your AppDelegate points to the file that is generated. The bundle command compiles all of your code into a single file, applying any transformations done by Babel including pre-processing the JSX! Does that answer your question?

**Comment by cheyueyong** [comment]
yes. it's really nice!  @brentvatne

**Comment by cheyueyong** [comment]
react-native  command  not  found   on ubuntu14.04.    I have been installed iojs with using nvm.    but it's ok on  OS X.

**Comment by cheyueyong** [comment]
i solved it @brentvatne
