### ISSUE TITLE
Cannot scroll smoothly if the UI has lot of image in iOS

### ISSUE THREAD

**Issue by nihp** [facebook/react-native#26983]
Scrolling of images is not smoothened in UI. I am using Flatlist to scroll the images and the scroll is not user friendly. I am using iOS. 

Here I am fetching images by 20 by 20 from server and showing it in UI. Here the scroll works not smoothly in Flatlist.

Any solution?

```
react-native-cli: 2.0.1
react-native: 0.58.4
```

**Comment by radko93** [comment]
You might want to update your React Native version for improvements. Also, check out react-native-fast-image.
