### ISSUE TITLE
FlatList's onEndReached gets called whenever data prop updates not whenever threshold is reached

### ISSUE THREAD

**Issue by hossamnasser938** [facebook/react-native#26988]
# Description
I'm building a Profile screen in which I have some components on the top such as cover photo, profile photo, etc. Then I'm displaying some horizontal tabs and finally a `FlatList` based on the selected tab. All these components are wrapped with a `ScrollView` to make sure that we scroll at any point in the screen. Here is a screenshot of what I'm trying to describe:
![Screenshot_1571920746](https://user-images.githubusercontent.com/27894818/67486787-f2af8200-f66c-11e9-8bd0-bbc7da0d54d8.png)

On the `FlatList`, I'm setting `onEndReachedThreshold` to 0.5 so that I do something before the user reaches the end of the list. This something assigned to `onEndReached` prop as a callback is that I go and fetch more data to the `FlatList` to render. The problem is that the `onEndReached` callback keeps called for ever as long as the `data` prop is updated.
 
React Native version: 0.59.8

Describe what you expected to happen:
I expect `onEndReached` to get called whenever I scroll before the end of the list not when `data` prop gets updated.

I read that `FlatList` does not work properly when rendered inside `ScrollView` and came across issues where `FlatList` does not scroll when wrapped with `ScrollView` but this is not the case for my issue[My `FlatList` scrolls correctly].

Could you please guide me on where is the problem and hopefully how to solve it?

**Comment by nachozullo** [comment]
Im having the same problem.
