### ISSUE TITLE
App crashes when downloaded (realease )from the App Store IOS 13, Works perfectly when built from XCode 11.

### ISSUE THREAD

**Issue by kasback** [facebook/react-native#26991]
Hello Guys, i've built a react-native app that works perfectly in my ios device or ios emulators but in the realease (when downloaded from the App Store) half of my features e.g : button clicks, pressing navigation back button make the app crash. I've been stuck with this the last two days. Any kind of help would be welcomed thank you.

React Native version:
OS: macOS Mojave 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz
    Memory: 87.57 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.13.0 - /usr/local/bin/node
    Yarn: 1.19.0 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 25, 26, 27, 28
      Build Tools: 26.0.0, 28.0.3, 29.0.2
      System Images: android-27 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.2 => 0.61.2 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-vector-icons: 6.6.0

## Steps To Reproduce

1.Download app from App Store
2.Try clicking on a navigation back button. or a button that triggers a function.

Describe what you expected to happen:
When Clicking on the navbar backbutton the app crashes and closes instead of going back in the nav stack.
When Clicking on a button that will trigger a method the app crashes and closes instead of acctually runing the method.

Im i missing something ? Should i do something before releasing my app?

**Comment by radko93** [comment]
Try adding crash reporting service and you will find out. You can also try running your app in release mode  https://facebook.github.io/react-native/docs/running-on-device#2-configure-release-scheme. If you can show that's a react native issue I will reopen this.
