### ISSUE TITLE
red screen right after clicking play ( + code signing issues with xcode)

### ISSUE THREAD

**Issue by hyusetiawan** [facebook/react-native#270]
I am encountering 2 different problems:
* red screen with a white text: "react-packager has encountered an internal error, please check your terminal error output for more details" right after the splash screen AwesomeProject powered by react native http://screencast.com/t/Yzzd2cackc5Z
this is different from the other red screen issue that is reported here: https://github.com/facebook/react-native/issues/257
. Accessing http://localhost:8081/index.ios.bundle yields:
```{
type: "InternalError",
message: "react-packager has encountered an internal error, please check your terminal error output for more details"
}```

* Randomly x-code would ask for code signing credentials (I have one already but it's for a different app) I am not sure if this is react native related or xcode, since I am not familiar with xcode at all.


I am using node v0.12.1 through nvm
this is the dump of the init debug messages: http://pastebin.com/JKws43qs

**Comment by amasad** [comment]
Xcode should start a terminal. Could you check that for any error logs?

**Comment by hyusetiawan** [comment]
@amasad it works now, what I had to do was kill the terminal that xcode started. Unfortunately, I didn't I forgot to get the console output of the terminal window before killing it.

And to answer my own question for the code signing, if you kill xcode and then open it again with your project, for some reason, it will set the target automatically to your phone (maybe because I have my iphone connected..) if that is the case, change it back to the simulator.

**Comment by chroth7** [comment]
FWIW, I just had the same problem (should anybody ever come back to this issue via google):

My XCode was not reopening the Terminal after I closed it before and a node server was blocking the 8081 port. After killing that server, and rebuilding in XCode, everything worked again.
