### ISSUE TITLE
Docs:real device can't connect developer 8081

### ISSUE THREAD

**Issue by DungBuiDeveloper** [facebook/react-native#27009]
a pretty annoying bug I need to share, my application doesn't work on 8081 when using xcode and this is how I solved it

1 . sudo npm install -g ios-deploy --unsafe-perm=true
2. react-native run-ios --device

**Comment by fabriziobertoglio1987** [comment]
8081 usually does not work for me on `ios` when I enable https transport security. `ios-deploy` seems just a workaround to disable it.

![image](https://user-images.githubusercontent.com/24992535/80348898-c02a5000-886e-11ea-8fcf-955b65cec00f.png)
