### ISSUE TITLE
Align text justify does not work with selectable text on Android

### ISSUE THREAD

**Issue by mikelmi** [facebook/react-native#27001]
Style `{textAlign: 'justify'}` for `<Text>` component does not work if `'selectable'` prop is `true`.

React Native version:
```
npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.2 => 0.61.2 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

## Steps To Reproduce

1. Create a fresh react native application
2. Insert sample `<Text>` component with `style={{textAlign: 'justify'}}` and `selectable={true}` properties into `<App>` component. E. g.: 

```
const App: () => React$Node = () => {
  return (
    <>
      <View>
        <Text style={{textAlign: 'justify'}} selectable>
               Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud    exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
        </Text>
      </View>
    </>
  );
};
```
If remove `selectable` property from `<Text>` it works fine.

**Comment by vance-liu** [comment]
+1, I tested in android, It is a real bug. IOS is ok.
