### ISSUE TITLE
TextInput inside FlatList based on API response. 

### ISSUE THREAD

**Issue by harikanammi** [facebook/react-native#27005]
Hi, i am displaying TextInputs inside FlatList based on API response. But in FlatList i have check-boxes, drop-downs and TextInputs. If i can check one item in array then it will add some objects (contains TextInputs) in array. When a value is entered on a particular TextInput it's working fine but if uncheck that item i should remove some objects (contains TextInputs) in array. In this case i am facing an issue like after unchecking the check-box text-field (what i have entered value before) is appending to below TextInput.

React Native version:

> "react-native": "0.60.5"

## Steps To Reproduce

1. How can i append the values to text-input after changing their positions like when i add some objects and remove some objects

 ```
 this.state = {
      textInputsValue: [],
    };
  onChangeText(text) {
    const { index, item } = this.props;
    const textInputsValue = [...this.state.textInputsValue];
    textInputsValue[index] = text;
    this.setState({
      textInputsValue
    });
  }
  <Mytextinput
                  placeholder="Enter Here"
                  value={this.state.textInputsValue[index]}
                  onChangeText={this.onChangeText}
                  onEndEditing={this.onEndEditingText}
                  onSubmitEditing={() => Keyboard.dismiss()}
                />
```
Describe what you expected to happen:
- Text-input values should not append to another text-inputs when i add some objects or remove some objects in array.

Screenshot:-

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/31063894/67564092-d3355980-f73f-11e9-9177-b9f26c284f6b.gif)

**Comment by radko93** [comment]
I don't think it's a bug in React Native. You should use keys so the inputs are not reused (or you have a mistake in your implementation). Also, you can use ScrollView instead of Flatlist.

**Comment by harikanammi** [comment]
hi @radko93, thank you for your response. I am getting response (array) from api. So i am using FlatList. Without FlatList how can i implement TextInputs based on array. Because i need to implement the UI elements based on API response. Please re-open this issue.

**Comment by radko93** [comment]
I cannot reopen because it's not a react native issue. Please ask this question on Stackoverflow. I can only say that you can try:
```
<ScrollView>
dynamicInputs.map(input =>
   (<TextInput />))
</ScrollView>

**Comment by harikanammi** [comment]
hi @radko93, i am asking about how to accept multiple values in TextInput.

**Comment by radko93** [comment]
Just render them separately, why not? Please ask on Stackoverflow, this is not a bug.

**Comment by harikanammi** [comment]
yes, i am using FlatList for rendering the Text-inputs. But i am displaying text-inputs based on API response. So it is a dynamic array. I am getting an issue in UI part. Please go through the above gif file.

I am adding some objects in an array and entered the values in text-inputs and remove that objects in an array. So that the input value is assigned to another object.
