### ISSUE TITLE
JS output must populate lineCount

### ISSUE THREAD

**Issue by aldebout** [facebook/react-native#27011]
Hey!

Not a 100% sure this is the right place to report this, and the bug is quite difficult to describe.

![Simulator Screen Shot - iPhone X - 2019-10-25 at 14 42 20](https://user-images.githubusercontent.com/822800/67596334-800ad900-f736-11e9-999e-ce42e8e449dc.png)
(transcript for google: `bundling failed: Invariant Violation: JS output must populate lineCount, but xxx/index.component.tsx has js/module output with lineCount 'undefined'`)

React Native version:
```
System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 112.32 MB / 8.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.16.1 - ~/.nvm/versions/node/v10.16.1/bin/node
    Yarn: 1.19.1 - ~/.yarn/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9 => 16.9.0
    react-native: 0.61.2 => 0.61.2
```

## Steps To Reproduce

I have (react-navigation-wrapped) SectionList inside a .tsx file.
This input causes the above error:
```
sections={[{ title: 'Current', data: props.studies.filter(s => s.status === 'ENROLLED') }]}
```
This one has no issue
```
sections={[{ title: 'Current', data: props.studies.filter(study => study.status === 'ENROLLED') }]}
```

I don't really care about fixing it since I can very easily change names, but I didn't find anything when googling the error and thought it might help someone some day.

**Comment by thatcharles** [comment]
same problem here, have you found the solution? thanks!
