### ISSUE TITLE
关闭当前RN模块的时候，模块内如果使用reactnavigation的load方法后，系统会自动进行退栈操作

### ISSUE THREAD

**Issue by siwei123** [facebook/react-native#27014]
React Native version:

## Steps To Reproduce

1.
2.

Describe what you expected to happen:

Snack, code example, screenshot, or link to a repository:

**Comment by ntcong91** [comment]
??? english please :)

**Comment by siwei123** [comment]
当前RN模块退出时，系统清理栈的资源时，不应该一级一级的退，应该直接关闭，这个现象在安卓上就不会发生
