### ISSUE TITLE
[Android][WebView] Getting No ViewManager defined for class RCTWebView

### ISSUE THREAD

**Issue by ecompton3** [facebook/react-native#2701]
I'm in the process of trying to port a react native iOS app over to Android but am running into an issue with the built in WebView Component. Even when trying to use the example code listed both in the docs and in this repo I keep getting the "No ViewManager defined for class RCTWebView" error in the Android Emulator when attempting to load a view with the WebView component. The emulator has Google API 23, I have v0.11.0 of react native, updated my react native cli, and am running node v4.0.0. I have tested the existing code in iOS against this new version of react and it still works fine. Anyone have any idea what could be causing this error?

This is the view containing the a component LoginWebView:

```javascript
/*
 *  React
 */

var React = require('react-native');
var {
  StyleSheet,
  Text,
  View,
  Navigator
} = React;

/*
 *  Flux
 */

var Fluxxor = require('fluxxor');
var FluxMixin = Fluxxor.FluxMixin(React);

/*
 *  Components
 */

var LoginWebView = require('../../components/login-webview');

/*
 *  LoginWebViewScene
 */

var LoginWebViewScene = React.createClass({

  mixins: [FluxMixin],

  render: function() {
    return(
      <View style={styles.container}>
        <LoginWebView flux={this.getFlux()}></LoginWebView>
      </View>
    );
  }

});

/*
 *  Styling
 */

var styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'stretch',
  }
});

module.exports = LoginWebViewScene;
```

And this is the LoginWebView itself, which should just display the content at a given URL:

```javascript
/*
 *  Properties
 */

var React = require('react-native');
var constants = require('../constants.js');
var {
  View,
  WebView,
  StyleSheet
} = React;

/*
 *  Flux
 */

var Fluxxor = require('fluxxor');
var FluxMixin = Fluxxor.FluxMixin(React);

/*
 *  LoginWebView
 */

var LoginWebView = React.createClass({

  mixins: [FluxMixin],

  onNavigationStateChange: function(obj) {
    // Don't forward to Flux until the webview has stopped loading
    if (!obj.loading) {
        this.getFlux().actions.newRouteForWebview(obj.url);
    }
  },

  render: function() {
    return(
      <View style={styles.webview}>
        <WebView
          url={constants.url}
          onNavigationStateChange={this.onNavigationStateChange}
          javaScriptEnabledAndroid={true}>
        </WebView>
      </View>
    );
  }

});

/*
 *  Styling
 */

var styles = StyleSheet.create({
  webview: {
    flex: 1,
    alignItems: 'stretch',
    backgroundColor: '#f00'
  },
});

module.exports = LoginWebView;
```

**Comment by kmagiera** [comment]
@ecompton3 WebView component is not a part of initial android release. As we have implementation of that component internally (we use it in AdsManager) we should be able to export it to github very soon

**Comment by brentvatne** [comment]
@ecompton3 - list of upcoming components for Android: https://facebook.github.io/react-native/docs/known-issues.html#missing-modules-and-native-views

**Comment by browniefed** [comment]
@brentvatne maybe point out in the opacity portion that `pointerEvents:none` could be used to stop touches?

**Comment by brentvatne** [comment]
@browniefed - done! https://github.com/facebook/react-native/commit/4fd0a2de0d39107103470e40ad38cdb501acd926

**Comment by ecompton3** [comment]
@brentvatne I had seen that initially but then was confused when I saw the WebView.android.js file that exists in the current release of react native. Perhaps it should be removed until the native module for it exists?

**Comment by brentvatne** [comment]
Fair point @ecompton3! cc @kmagiera @mkonicek

**Comment by kmagiera** [comment]
WebView.android.js is required to build JS bundles that use WebView on iOS. Otherwise packager will pick ios.js file which is also not what we want.
@mkonicek We should prehaps replace WebView.android with UnimplementedView

**Comment by deminoth** [comment]
@kmagiera could you tell me when the implementation will be published? :eyes:

**Comment by ecompton3** [comment]
+1 on the ETA for implementation. My team has an app that requires a WebView for OAuth 2.0 and would love to get an Android app going soon

**Comment by syarul** [comment]
SO there is actually no WebView support currently.. feel like April 1st

**Comment by GasperKolenc** [comment]
+1 for ETA as well.

**Comment by mkonicek** [comment]
On this list the highly requested ones are maps, intent and webview. I'll be away for two weeks preparing for a conference, and there are many other high-pri things to work on. Will work on open sourcing more view once I'm back though.

**Comment by mkonicek** [comment]
In the meantime you can look for 3rd party modules at https://react.parts/native

**Comment by mkonicek** [comment]
To give more context, the React Native for Android project was started much later than iOS. The plan is to eventually catch up on feature parity but it is not realistic to expect everything that works on iOS will work out of the box on Android, as explained in [Known Issues](https://facebook.github.io/react-native/docs/known-issues.html).

**Comment by ryanmcdermott** [comment]
I guess we will have to be patient! Would also be helpful to see the "iOS namespace" on WebView in the docs, to make it apparent it's not available on Android yet: `WebViewIOS`

**Comment by syarul** [comment]
+1, I'm waiting this impatiently, anyway kudos this is really great project! anyway for the time being if anyone need map solution mapbox already has support for map on android,
[https://github.com/mapbox/react-native-mapbox-gl](https://github.com/mapbox/react-native-mapbox-gl)

**Comment by PierBover** [comment]
Any ETA for this?

**Comment by codemanki** [comment]
+1 on ETA :)

**Comment by deminoth** [comment]
Maybe we should wait at https://github.com/facebook/react-native/issues/3796

**Comment by ide** [comment]
@mkonicek do you think WebView.android.js will be available by Jan 2016, just to set a time frame?

**Comment by patoroco** [comment]
Currently we're using [react-native-webview-android](https://www.npmjs.com/package/react-native-webview-android) and it runs good. Anyway, we plan to do the upgrade without issues with official react-native webview for android release.
