### ISSUE TITLE
Reloading App not updating for the latest modified code RN 0.61x

### ISSUE THREAD

**Issue by hugoh59** [facebook/react-native#27029]
```
System:
    OS: macOS Mojave 10.14.5
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 16.87 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.2 => 0.61.2 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
```

Since this morning, after not doing anything new to my project, the code suddenly stopped updating the view in my Xcode project. I have tried everything reseting the cache, reinstalling watchman, disabling fast refresh but nothing works. It seems as the project is no longer linked to the current version of my code somehow but keeps referring back to previous version.

**Comment by bockc** [comment]
I have the exact same issue. The only state reloaded by RN is the state right after installing the app, any further change won't be executed after a reload. Even by killing the app and starting it again, code modifications don't apply...
I hope there's a fix for this coming soon, I don't wanna redeploy my app from XCode everytime I change a single bit of code.

**Comment by mtnt** [comment]
Live reload still updates code (with the debugger turned on).

**Comment by hugoh59** [comment]
I don't use react-native-debugger but still has this issue since updating to RN 0.61x, what works for me is completely restarting my computer but that's very time consuming.

**Comment by mtnt** [comment]
@hugoh59 I started new project with RN 0.61.1 and It worked ok including debugging via Chrome console.log and debugger... until this morning - and I did not do anything too (just open my laptop and refresh the simulator)

**Comment by bockc** [comment]
Are you guys connecting to the Chrome debugger via `localhost:8081/debugger-ui` ? In my case there's absolutely no issue this way, but I don't really see why this would change anything ?

**Comment by mtnt** [comment]
And I don`t really see how good code that already worked ok and protected by package-lock and Podfile.lock could be broken without any updates...

**Comment by mtnt** [comment]
@hugoh59 @bockc is it works well now? It seems ok to me... and yes, I did not do anything to fix it

**Comment by hugoh59** [comment]
@mtnt I get the exact same issue. It's incomprehensible. It happened to me during the day as well now. It's like ghost code continue to live on even tho the code no longer exists, it still consol log things that I have erased and my code isn't updated.

It's super frustrating I'm wasting hours on looking where this could come from with not result so far. Any help from the team would be appreciated.

**Comment by hugoh59** [comment]
I still get the issue but it goes away and comes back for no reason. It also happens when I disable fast refresh.

**Comment by hugoh59** [comment]
I've tried a lot of things including `rm -rf .git/index.lock` and now it works again, I'm not sure if that's what solved it but try it out in case it ever comes back.

**Comment by bockc** [comment]
Well I just ran across this same issue right now using the chrome debugger this time. Had to kill the app and the debugger to actually reload my code. This is definitely an issue with the new react-native reload feature as no matter which debugger I use, this seems to occur randomly.

I'd also like some feedback from the team, just to know if they could quickly take a look at it.

@hugoh59 I don't have any .git/index.lock nor .hg/index.lock :/

**Comment by hugoh59** [comment]
@bockc Yes I did not have one either yesterday and this morning I had one, I'm really lost into what's going on I'm sorry I can't help any further... What I would do is kill everything and restart my computer but even that only works some of the times.

**Comment by bockc** [comment]
@hugoh59 I still don't have any of these files, so I guess the issue is deeper than a simple lock-file hidden in my project. I thought it could be some sort of cache, but I cleared every single cache related to my development environment and this has not changed anything. Also, my watchman is up to date (v 4.9.0_3). I literally have no clue where this could come from.

**Comment by mtnt** [comment]
It`s here again! =) And I don`t have the .git/index.lock

**Comment by bockc** [comment]
@mtnt try disabling `remote debugging` and enabling it again, works for me most of the time. Not ideal, but this is currently my best option while waiting for a fix from the team.

**Comment by mtnt** [comment]
I did - no results... It starts working ok while debug is disabled, and returns just on enabling debug

**Comment by hugoh59** [comment]
Same here...

**Comment by jwaldrip** [comment]
Having the same issue. This is extremely frustrating.

**Comment by ThiagoAlencar12** [comment]
My app in react native, i lost every time my states, i'm using hooks of react, useStates but, every time i update my app i lose my data, please help!

**Comment by brien-crean** [comment]
Has anyone found a workaround so debugging can be enabled? As soon as I enable debugging old code is being loaded. I've tried all of the suggestions above.

Disabling debugging fixes it but I need debugging enabled for some of the modules I use to work correctly. Such a frustrating issue!

**Comment by bockc** [comment]
@brien-crean Usually what I do when this occurs is I disable `Debug`, close my debugger, kill the app, press the start button in XCode and then I am fine for a few hours.
Definitely not ideal, but I don't have a better workaround right now.

**Comment by brien-crean** [comment]
@bockc that unfortunately doesn't work for me. This happens on android and ios for me. I ended up having to clone my project repo to a new location and that resolved it for now

**Comment by hugoh59** [comment]
Any help from the team would be appreciated. Not sure who to mention here.

**Comment by bockc** [comment]
I'm not really sure if this really is what is causing the issue, but I noticed that when I got an exception in my code, I have the famous red screen and if I reload by saving my code after that, I will never be able to get the new code state, only the one that was before the exception crash. Once more, I'm not sure if that's exactly what's causing the issue.

**Comment by hbarylskyi** [comment]
I'm forced to use XCode's console window and attaching to the process. It's kind of a workaround.

**Comment by SamiChab** [comment]
Same issue here... Can anyone help on how to fix this temporarily?

**Comment by bockc** [comment]
After encountering this issue more and more and more... I figured that every time I save a modification in an arrow function component, or an arrow function defined and exported in a standalone file, and that `Fast refresh` is enabled, the code will never be updated anymore when debugging.

That's kind of ironic as react pushes us to use more and more of these features...

**Comment by rikur** [comment]
Facing the same issue. With debugging enabled, old stale JS is being loaded. At first it used to happen with react-native-debugger, but now it happens with Chrome Devtools as well.

**Comment by SamiChab** [comment]
Thanks @bockc !
In my case it happened as I updated a module (`react-native-webview`). As I installed the new version, the JS didn't update anymore...
When I disable debugging, it works again. But as soon as I enable it again, the old code is loaded...
@react-native-bot is this enough informations?

**Comment by karthik-balasubramanyam15** [comment]
Sometimes with the debugger is connected, the browser caches the data. Try clearing the cache, kill the server and run it again. It worked for me :)

**Comment by alitsvin** [comment]
Got similar issue. Have no changes even if reload or rebuild the app. Only restarting Metro with resetting cache can reload the app.(

**Comment by bockc** [comment]
guys, somebody found the [solution](https://github.com/jhen0409/react-native-debugger/issues/423#issuecomment-557945625) ! :D

I can confirm that this worked for me using both the Chrome console and the react-native-debugger :)

**Comment by xutm** [comment]
> I've tried a lot of things including `rm -rf .git/index.lock` and now it works again, I'm not sure if that's what solved it but try it out in case it ever comes back.

It take me a lot of time to solve. 
Just `rm -rf .git/index.lock` .

**Comment by kozillla** [comment]
I have the opposite problem. I use expo-gl package to run openGL on RN . It requires RN debugger to be disabled. Everything is fine until I will not turn it on.  Once the debugger is on, the latest code will only be reloaded when debug mode stays enabled. When I disable debug mode, RN does not reload the latest code anymore (even through force ```Reload```  also Fast Refresh seems to be completely ignored by RN in such a scenario). Then pretty much the whole project is not usable anymore as I am not able to reload code with disable debugger, and I can't enable debugger on openGL projects as it will cause the app to crash.

**Comment by razaadeel** [comment]
Does any one found the solution? I am not using debugger but still got the same problem. I've tried every solution that are mentioned above but problem remains same.

**Comment by haivato** [comment]
I have face this issue. And my solution is, My old flow is Home >>> Register, i will change Home >>> Account, this time my code will be updated. And I change flow as previous, then Updating Modified Coding is work

**Comment by thumbraise** [comment]
> guys, somebody found the [solution](https://github.com/jhen0409/react-native-debugger/issues/423#issuecomment-557945625) ! :D
> 
> I can confirm that this worked for me using both the Chrome console and the react-native-debugger :)

This worked for me after trying many other things. Just check the box in Chrome dev tools > Network > Disable cache

**Comment by jbarnickol** [comment]
> guys, somebody found the [solution](https://github.com/jhen0409/react-native-debugger/issues/423#issuecomment-557945625) ! :D
> 
> I can confirm that this worked for me using both the Chrome console and the react-native-debugger :)

This worked for me after trying many other things. I simply needed to check the box in Chrome dev tools > Network > Disable cache

**Comment by adamgins** [comment]
@jbarnickol  thanks - that worked! https://github.com/jhen0409/react-native-debugger/issues/423#issuecomment-564485919

**Comment by fo-fo** [comment]
Was experiencing the same issue. Thanks for the "Disable cache" workaround – it works!

Has something changed in Metro that causes the browser to think it can cache the bundle file? Would be nice to see a proper fix for this.

**Comment by thanh90** [comment]
fast refresh is suck, good for UI changes only, when I change the logic(for ex: add a new function) it throws out an error

**Comment by viz21** [comment]
For me changing **Debug server host & port for device** in **Dev settings** to `localhost:8081` worked

**Comment by matthiasleitner** [comment]
This is also happening for me using react-native 0.62.1, only restarting the packager allows to get changes reloaded.

**Comment by JakubSvihla** [comment]
Shake the device and tap on "Enable Live Reload"
Having done this, the app reloads on file save.

**Comment by ridhoassuryadi** [comment]
solved when i tried
* rm -rf .git/index.lock
* disabled remote debugginng and enabled it again

**Comment by RatebSeirawan** [comment]
nothing worked for me it's been 8 hours of unproductive wasted time with no results.
tried all of the above and i am not using react-native-debugger

**Comment by medmo7** [comment]
What solved is for me `npx react-native-clean-project clean-project-auto` 
+
new metro bundle
+
and running a new build `react-native run-ios`

**Comment by mehmetaydar** [comment]
On Mac: Run react-native for ios then, Go to 

> Simulator->Hardware->Erase all content and settings

Then go to Vscode, 

> Run without debugging

This made hot reload working for me.

**Comment by wandhi** [comment]
In my case I try to close React Native Debuger from my chrome and I re run my project and its work for me thanks

**Comment by johhansantana** [comment]
> guys, somebody found the [solution](https://github.com/jhen0409/react-native-debugger/issues/423#issuecomment-557945625) ! :D
> 
> I can confirm that this worked for me using both the Chrome console and the react-native-debugger :)

so it's basically clearing the cache of the debugger tab..... who would ever expect this to be the bug lol

**Comment by conradjonp** [comment]
I've tried every solution mentioned above and nothing worked for me. Also did a nuke (deleting pods, deleting node_modules, yarn run cache clean, etc...). Disabling debug and fast refresh didn't work either. The code is still stale and I have to rebuild to get my code changes. I recently upgraded react-native on 0.61.

**Comment by mechanizzed** [comment]
> > I've tried a lot of things including `rm -rf .git/index.lock` and now it works again, I'm not sure if that's what solved it but try it out in case it ever comes back.
> 
> It take me a lot of time to solve.
> Just `rm -rf .git/index.lock` .

Thanks,

`rm -rf .git/index.lock` 
works for me!

**Comment by Sbphillips19** [comment]
> npx react-native-clean-project clean-project-auto

That will cause major issues to your project if you don't know what you are doing.  Force updating all your module versions has major impacts

**Comment by medmo7** [comment]
> > npx react-native-clean-project clean-project-auto
> 
> That will cause major issues to your project if you don't know what you are doing. Force updating all your module versions has major impacts.
> 
> As far as the issue, I have tried everything else mention. I am getting an has already been declared from me saving a reducer file with a statement I accidentally used twice. After removing I can't get rid of the error no matter how many times I use clean, rebuild, removing and reinstalling app, etc... I haven't touched the app for about 2 months, but had no issues 2 months abgo.
`npx react-native-clean-project clean-project-auto` gives option you can say yes only to caches and ios/android build  clean if you want. Thanks

**Comment by huseyin39** [comment]
Closing - Opening back the Node server worked for me.

**Comment by hassan-irshad** [comment]
> > guys, somebody found the [solution](https://github.com/jhen0409/react-native-debugger/issues/423#issuecomment-557945625) ! :D
> > I can confirm that this worked for me using both the Chrome console and the react-native-debugger :)
> 
> This worked for me after trying many other things. I simply needed to check the box in Chrome dev tools > Network > Disable cache

This Worked

**Comment by filipenatanael** [comment]
I was facing this issue few minutes ago, I managed to get it work by following the instructions below

- Disable the firewall or adjust the permissions there
- Run: ```adb kill-server && adb start-server```
- Run: ```adb -s YOUR_DEVICE_ID reverse tcp:8081 tcp:8081```

Also, I tried ```rm -rf .git/index.lock``` but didn't help me on my especifically situation

**Comment by jbarnickol** [comment]
In case it helps someone - I've noticed if I have any javascript syntax errors, the app will launch the last working version (no new code) which can be very confusing. The errors are logged in the metro terminal session so I now watch for that when running new code.

**Comment by victormaggie** [comment]
I got the same issue, and it was so annoying. Once I disable Debug module, it works perfect for me. Just disable the debug module in the developer menu, and it will be fast reloading when you save the file.

**Comment by ricardosoaresl** [comment]
1- Cleaning the build folder in Xcode: cmd+shift+k
2- In the "Device" menu of Simulator, click "Erase All Content and Settings"
3- Reinstall app

**Comment by zahidalidev** [comment]
1-  import "NativeModules" from react-native
2-  call "NativeModules.DevSettings.reload()" on button press to reload app like below

import { NativeModules } from "react-native";

handleReload = () => {
     NativeModules.DevSettings.reload();
}

**Comment by saksham2410** [comment]
Having the same problem on 0.63.3. Tried all the above changes

**Comment by cglacet** [comment]
Does someone know why `.git/index.lock` is causing this kind of issues?

**Comment by jakezegil** [comment]
If you made it this far, it's worth noting that hot reloading only works in the render method of a class component. This gave me a run for my money trying to figure out why my StackHavigator Header wasn't updating:
https://stackoverflow.com/a/49552575/12475345

**Comment by abduls30** [comment]
To see your updated changes,
You have to restart your server

**Comment by toni-trable** [comment]
still having the same issue with  react-native: 0.63.4. 
I have tried all those changes but nothing

**Comment by Vishu1694** [comment]
> still having the same issue with react-native: 0.63.4.
> I have tried all those changes but nothing

Same for me
Whenever I start the app in Virtual Device, it loads the Previous build. I have to manually build the app again using command 'react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res' everytime I have to make a change to the app for it to show but I can't do it everytime.

**Comment by stgreenman** [comment]
Same for me except only for externally defined functions. 

Workaround: Update logic or UI on a functional component. Metro for some reason rebuilds external functions then which is faster than rebuilding the entire project every time.

**Comment by lenis96** [comment]
> I've tried a lot of things including `rm -rf .git/index.lock` and now it works again, I'm not sure if that's what solved it but try it out in case it ever comes back.

it solved to me

**Comment by bartodt** [comment]
Any new solutions on this? These ones didnt work for me
