### ISSUE TITLE
StatusBar not hiding on android

### ISSUE THREAD

**Issue by lithin** [facebook/react-native#27035]
React Native version:
0.61.0; still experiencing it after upgrading to 0.61.2
This issue started when we upgraded from 0.59.2 to 0.61.0

## Steps To Reproduce

1. Have a full screen element (in our case it's a WebRTC element)
2. Add `<StatusBar hidden />`
3. Observe on Android that there is a white bar on top of the screen instead of no `StatusBar`

Describe what you expected to happen:
`StatusBar` would be hidden/invisible and would yield its space to the content

<img width="595" alt="Screenshot 2019-10-28 at 15 26 56" src="https://user-images.githubusercontent.com/6726858/67686969-d034a600-f997-11e9-8113-c7d6612bf0b7.png">

When we remove `<StatusBar hidden />`, we see status bar there instead of the white bar:
<img width="590" alt="Screenshot 2019-10-28 at 10 50 36" src="https://user-images.githubusercontent.com/6726858/67687354-78e30580-f998-11e9-9c1f-0b39f08e77ea.png">

Steps we tried to fix this:
Making the content absolute and trying to move it upwards doesn't hide the status bar,  same for negative margin-top. We have tried `SafeView` etc but nothing seemed to make this bar disappear.

**Comment by ArturTimoxin** [comment]
I have the same problem :(

**Comment by aqeebimtiaz** [comment]
Any update yet? I'm having the same kind of problem in some devices, although on some devices & emulators the status bar is hiding perfectly...
