### ISSUE TITLE
[Android] Building from bundle

### ISSUE THREAD

**Issue by ngreenwood6** [facebook/react-native#2703]
I have been working with react-native on iOS and found the bundling option in the `AppDelegate.m` file and it works great once you bundle it. However, I saw that Android was released today and I am not able to figure out how to do the same on Android. In iOS there is some code like this:

```
sourceURL = [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
```

Is there an equivalent way to do this in Android or am I missing something? I just want to bundle it on the device so I can use it without being near my computer.

**Comment by sulliwane** [comment]
I'm also interested in the location of the AppDelegate.m equivalent for Android. Thanks.

**Comment by ide** [comment]
MainActivity.java is the equivalent of the AppDelegate.

**Comment by kmagiera** [comment]
@ngreenwood6 In `MainActivity.java` generated from template project there is a line `setJSMainModuleName("index.android")` which basically makes java native code load js from android assets but with the current setup this will only happen if the file is present in assets. 
Then you should be able to use `react-native bundle` to generate js bundle in the assets folder from which android build system should pick it up, but apparently this step doesn't seem to work cc @foghina

**Comment by sulliwane** [comment]
Ok. I was looking for how to download the index.android.bundle over http from the android device. I'll wait 0.12 then!

**Comment by brentvatne** [comment]
@sulliwane - oh, that works right now - see: https://facebook.github.io/react-native/docs/running-on-device-android.html#content

**Comment by sulliwane** [comment]
@brentvatne AWSOME, thanks a lot.

**Comment by kmagiera** [comment]
As a workaround you may have try the following:
1. Run packager in your project dir: `react-native start`
2. Use curl to fetch bundle from server and place it in android asset dir: `curl -k  'http://localhost:8081/index.android.bundle' > android/app/src/main/assets/index.android.bundle`

**Comment by stephenparish** [comment]
In addition to @kmagiera's workaround, you may also want to pass in the query params to the packager for minifying / disabling dev:
`http://localhost:8081/index.android.bundle?dev=false&minify=true&runModule=true`

For the params available, see: https://github.com/facebook/react-native/blob/master/packager/README.md#pathtomodulenamemapbundle-query-params

**Comment by yinzSE** [comment]
i got "index.android.bundle", and then what should i do  to let it to be  an apk file?

**Comment by stephenparish** [comment]
You can drop that into `android/src/main/assets/`.

**Comment by satya164** [comment]
Closing as this feature is already in the stable releases.

**Comment by sujalBandhara** [comment]
How can i change localhost to my own server IP? please help!!
