### ISSUE TITLE
[Android] TocuhableOpacity and zIndex / overflow problem

### ISSUE THREAD

**Issue by sorinbogdan95** [facebook/react-native#27030]
TouchableOpacity is not triggered when it's positioned in an overflowing view, even if zIndex is set and the view is displayed above sibling. Might be related to zIndex or overflow implementation in react native.

React Native version:

  0.61

## Steps To Reproduce

Press buttons 2,3,4.

Buttons 2, 3, 4 onPress is not fired ON ANDROID.

Describe what you expected to happen:

Buttons 2,3,4 onPress should be called on press.

Snack, code example, screenshot, or link to a repository:

Snack: https://snack.expo.io/@sorinbogdan/working-maybe

When inspecting, even if my content is shown, this is what I see on Android:

![image](https://user-images.githubusercontent.com/38883435/67675179-2f3def00-f987-11e9-9500-fbee9ed4f323.png)

It seems like even though my view has zIndex set, the blue view renders above somehow for event handling. :|

Setting parent view (with green background) position to absolute is only a workaround and it is not a solution. Also using TouchableOpacity from "react-native-gesture-handler" seems to work but is still a workaround. Please fix this issue.

( TL;DR a touchable component that is nested in a component positioned absolute, cannot be touched outside of the wrapping component)

**Comment by KumariShalini** [comment]
i have same problem with touchable is not working when one view is overlapping on another view. Please out me from this problem, give some solution. I want this one, but here click is not working.
<img width="199" alt="Screenshot 2019-10-30 at 4 44 06 PM" src="https://user-images.githubusercontent.com/23182585/67853416-87feba80-fb34-11e9-8c1f-e84f1a2805e8.png">
