### ISSUE TITLE
[Android] Allow debugging from ports other than 8081

### ISSUE THREAD

**Issue by ngreenwood6** [facebook/react-native#2704]
I was using https://ngrok.com/ to expose my local host (port 8081) to a remote host (port 80) so that I could package an apk to send to a friend to test with. However, trying to change the host in the debug menu to the host ngrok gave me it would not work still. I looked through the source code and found this line https://github.com/facebook/react-native/blob/42eb5464fd8a65ed84b799de5d4dc225349449be/ReactAndroid/src/main/java/com/facebook/react/devsupport/DevServerHelper.java#L57. It seems to be hardcoded to only allow it on port `8081`, is there any chance that we can get this updated to just accept the url instead? I think that should work if you change lines 52-54 in that same file to append the `:8081` to the end of them. I am not sure how to test this code and see if it would work since it did not download the project to my local computer.

**Comment by ide** [comment]
More generally, it's not possible to customize the URL and how the bundle gets loaded. This flexibility is useful to have.

With the iOS version you can specify an RCTBridgeDelegate (basically an implementation of an interface with methods like loadBundle) and any URL. This is flexible enough to allow for use cases like ngrok, HTTP/2 connections, custom caching, and other requirements that we haven't anticipated.

On Android, there could be a similar way to configure the ReactInstanceManager. For example, there could be a ReactInstanceLoadHandler that is in charge of loading bundles. The default implementation of the handler would keep the current behavior (load with DevServerHelper during development and the asset bundle in production), so the learning curve stays the same.

I hope to look into this myself and work towards making the ReactInstanceManager more configurable while keeping the default behavior the same as today.

**Comment by dsibiski** [comment]
@ide This is something that we need for the React Native Playground as well. We're definitely interested in collaborating on this, getting a fork going first then perhaps getting it into core.

**Comment by WillCoder** [comment]
Also why we don't have the interface to change the Url? or I didn't find it?

**Comment by dsibiski** [comment]
@WillCoder We do: Shake Device (or F2 on emu) > Dev Settings > Debug server host for device.

You can also check out my PR to see an example of setting the IP programmatically (although it's a hack and won't work unless you are using port 8081 or you're using my fork).

**Comment by lonehacker** [comment]
+1 on an easy interface for loading react bundles programatically. I'm excited about a use case where the react native code could be loaded seamlessly in the background from a CDN and updated next time the app is run.
I know there are ways to achieve this in iOS, does anyone have any POCs / ideas for android?
