### ISSUE TITLE
CocoaPods could not find compatible versions for pod "React/Core" - react-native version 0.61.2

### ISSUE THREAD

**Issue by sachinhegde** [facebook/react-native#27041]
Trying to integrate ReactNative to an existing Xcode project. Followed instructions from https://facebook.github.io/react-native/docs/integration-with-existing-apps

While running pod install I get the following error

[!] CocoaPods could not find compatible versions for pod "React/Core":
  In Podfile:
    React/Core (from `../node_modules/react-native`)

None of your spec sources contain a spec satisfying the dependency: `React/Core (from `../node_modules/react-native`)`.

React Native version:
react: 16.9.0 => 16.9.0 
react-native: ^0.61.2 => 0.61.2 

## Steps To Reproduce

1. Followed instructions from https://facebook.github.io/react-native/docs/integration-with-existing-apps
2.

System:
    OS: macOS 10.15
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 222.31 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.12.0 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 24, 25, 26, 27
      Build Tools: 25.0.2, 26.0.1, 26.0.2, 27.0.3, 28.0.3
      System Images: android-27 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.2 AI-181.5540.7.32.5056338
    Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: ^0.61.2 => 0.61.2 
  npmGlobalPackages:
    react-native-cli: 2.0.1

**Comment by SuhairZain** [comment]
Sorry. It's happening to me as well. How do we remove the stale label?
