### ISSUE TITLE
componentWillUnmount is not working

### ISSUE THREAD

**Issue by amalcltpba** [facebook/react-native#27043]
React Native version:
   OS: Linux 3.19 Ubuntu 14.04.5 LTS, 
    Shell: 4.3.11 - /bin/bash
  Binaries:
    Node: 10.15.1 
    Yarn: 1.6.0 
    npm: 6.4.1 
  SDKs:
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28
      Build Tools: 19.1.0, 23.0.1, 23.0.2, 24.0.1, 25.0.0, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.2, 27.0.3, 28.0.3
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.1 => 0.61.1 
  npmGlobalPackages:
    create-react-native-app: 2.0.2
    react-native-cli: 2.0.1
    react-native-rename: 2.4.0

All components  componentWillUnmount is stoped. Can anyone suggest me a solution to my problem

**Comment by anmolpandeyy** [comment]
@amalcltpba  Please share your code so that we could look into it.

**Comment by HarshitMadhav** [comment]
@amalcltpba  are you using react-navigation for navigating?
