### ISSUE TITLE
I reload the application but it is not updated

### ISSUE THREAD

**Issue by IvanAllue** [facebook/react-native#27048]
React Native version: 0.59.9

System info:  
 OS: Windows 10
      CPU: (4) x64 Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz
      Memory: 1.06 GB / 7.84 GB
    Binaries:
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD

description: 

It has already happened to me several times (many) that I am programming and suddenly when I save things the application does not react. I can restart the service, run run-android again and nothing, it still doesn't react. I go crazy changing the code without knowing why it doesn't work until I see what I do, even a simple log doesn't. At that time (even if you restart the computer) it still does not react. And it is because as much as I run the run-android the android emulator is running a version of the application in which I was stuck and I have to uninstall the application and rerun the android run and until I do that it does not work. I would like to know if there is any solution. I can't update or change the native rea version because there are many people with that application.

PD: I'm sorry if you misunderstand, this translated with google translator

**Comment by brien-crean** [comment]
@IvanAllue Is it related to this issue? -> https://github.com/facebook/react-native/issues/27029

**Comment by IvanAllue** [comment]
> @IvanAllue ¿Está relacionado con este problema? -> [# 27029](https://github.com/facebook/react-native/issues/27029)

Not exactly, my problem is that it stops updating but when I delete cache, uninstall the app etc and launch it again it updates, what happens is that I don't know if there is a method for the cache to be updated and / or not to install the app from the cache. More than anything because if I do not realize I can stay for a while until I see that the error is not my code.
