### ISSUE TITLE
App crash on button click in release mode, debugging is fine

### ISSUE THREAD

**Issue by ErHarinderSingh** [facebook/react-native#27058]
I am facing this strange issue. 
When I click on signin button it crashes the app in release mode, works in debugging mode.

1. I am not sure it is the issue with react-native-reanimated , react-native-gesture-handler or react-native itself.
2. In release apk, I tried hermes enable true and false both. But nothing works. It means, I am sure that issue is with not the hermes-engine.

I have updated all the libraries (react-native-reanimated , react-native-gesture-handler) but still not worked for me.

Here is the some code. 

```
import Animated, {Easing} from 'react-native-reanimated';
import {TapGestureHandler, State} from 'react-native-gesture-handler';
const {
  Value,
  event,
  block,
  cond,
  eq,
  set,
  Clock,
  startClock,
  stopClock,
  debug,
  timing,
  clockRunning,
  interpolate,
  Extrapolate,
  concat,
} = Animated;

```
```
this.buttonOpacity = new Value(1);
    this.onStateChange = event([
      {
        nativeEvent: ({state}) =>
          block([
            cond(
              eq(state, State.END),
              set(this.buttonOpacity, runTiming(new Clock(), 1, 0)),
            ),
          ]),
      },
    ]);

    this.buttonY = interpolate(this.buttonOpacity, {
      inputRange: [0, 1],
      outputRange: [100, 0],
      extrapolate: Extrapolate.CLAMP,
    });
```
```
<TapGestureHandler onHandlerStateChange={this.onStateChange}>
            <Animated.View
              style={{
                ...styles.button,
                opacity: this.buttonOpacity,
                transform: [{translateY: this.buttonY}],
              }}>
              <Text style={{fontSize: 20, fontWeight: 'bold'}}>SIGN IN</Text>
            </Animated.View>
          </TapGestureHandler>
```
 ```
 "hermes-engine": "^0.2.1",
    "react": "16.8.1",
    "react-native": "0.61.3",
    "react-native-gesture-handler": "^1.5.0",
    "react-native-reanimated": "^1.3.0",
```

There is one thing, If code is wrong then why everything is working in debugging mode as I want it to be work?
Just crash in release mode even Hermes enabled or disabled.

**Comment by robstermarinho** [comment]
I´m facing the same issue. It´s something related to the react-native-gesture-handler buttons. I changed all my gesture handler buttons to the default React Button and It worked good. I´m still trying to find a solution to fix that.

**Comment by maxbbb** [comment]
Was facing a similar issue, this fixed it - https://github.com/kmagiera/react-native-gesture-handler/issues/320#issuecomment-537945905

**Comment by ErHarinderSingh** [comment]
Yeah @maxbbb, it works. I implemented it 2 days ago but forgot to add it to in comments here. Thanks bro.

**Comment by hramos** [comment]
Please make sure to fill in the issue template if you decide to file a new issue.
