### ISSUE TITLE
小米8 Android 10crash

### ISSUE THREAD

**Issue by Oliverxyj123** [facebook/react-native#27055]
OS verison: 
![image](https://user-images.githubusercontent.com/15978950/67825286-caf46a00-fb03-11e9-973e-7fb67d1e4b29.png)

crash report:
![image](https://user-images.githubusercontent.com/15978950/67825234-9385bd80-fb03-11e9-88fa-6d9a389a0d42.png)

**Comment by hramos** [comment]
Closing after several months without followup from the author. Please make sure to fill in the issue template if you decide to file a new issue.
