### ISSUE TITLE
Setting ScrollView bounces={false} disables scrolling entirely.

### ISSUE THREAD

**Issue by justinadenharrison** [facebook/react-native#27051]
I cannot disable bouncing within a ScrollView without disabling scrolling entirely with either alwaysBouncesVertical or bounces set to false. I'm using a simulator to test. If I explicitly set scrollEnabled={true} with either of those set to false, then scrolling will still not work.

System:
    OS: macOS 10.15
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Memory: 874.58 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.12.0 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
  IDEs:
    Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.2 => 0.61.2

## Steps To Reproduce

1. Create a ScrollView with enough content to be scrollable.
2. Try to disable bouncing with alwaysBouncesVertical or bounces set to false. Bouncing will be disabled, but you won't be able to scroll, at least within a simulator.

```
<ScrollView
     scrollEnabled={true}
     // alwaysBounceVertical={false} DOES NOT WORK
     // bounces={false} DOES NOT WORK
    style={styles.componentList}>
    {components.map((component, index) => {
        const isSelected = selected.includes(index)			
        const componentStyle = isSelected ? {
	    ...styles.component,
	    backgroundColor: 'rgba(0, 0, 0, 0.57)'
	} : styles.component
						
	const componentLabelStyle = isSelected ? {
		...styles.componentLabel,
		color: 'white'
	} : styles.componentLabel

	return (
		<TouchableOpacity
		        key={index}
		        onPress={() => this.handlePress(component, index)}
			style={componentStyle}>
			<Text style={componentLabelStyle}>
			     {component.label}
			</Text>
		</TouchableOpacity>
	)
	})}
</ScrollView>

```

I expected to be able to disable bouncing on lists.

**Comment by justinadenharrison** [comment]
It was an issue with the bounding height of the ScrollView.

**Comment by annyswang** [comment]
@jhar Hi, i know this is a long time ago, but could you elaborate a bit more on how the bounding height was affecting the scroll? Do you remember what you did eventually to resolve this issue? Thank you!
