### ISSUE TITLE
Image onLoad, onLoadEnd, onLoadStart not working

### ISSUE THREAD

**Issue by sburaksak** [facebook/react-native#27050]
I am using Image component of React Native, sometimes images may load late and I need to add loading component, so to do this, I need to handle image load or not. There are methods for this(onLoad,onLoadEnd) but not working :( 

React Native version:
System:
    OS: macOS Mojave 10.14.4
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 19.46 MB / 8.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    Android SDK:
      API Levels: 22, 23, 24, 25, 26, 27, 28
      Build Tools: 23.0.1, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.3, 28.0.2, 28.0.3
      System Images: android-26 | Google APIs Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64
  IDEs:
    Android Studio: 3.1 AI-173.4907809
    Xcode: 10.1/10B61 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.2 => 0.61.2

## Steps To Reproduce

1.try image component onLoad
  <Image
          onLoad={() => console.warn('onLoad')}
          onLoadStart={() => console.warn('onLoadStart')}
          onLoadEnd={() => console.warn('onLoadEnd')}
          source={source}
          style={style}
        />

Describe what you expected to happen:
onLoadMethod work

**Comment by ShuChangSC** [comment]
same problem...

**Comment by bartoszboruta** [comment]
same problem

**Comment by apolineaire** [comment]
I had the same issue **on Android** while working with `onLoadEnd`. 

I found two issues in my situation :
1. I was using `elevation` / `zIndex` to show skeleton screens above my component while it loads. But I did it _without_ using `position:'absolute'`, only `elevation` / `zIndex`. So I finally used `position : 'absolute'` and now onLoadEnd method is firing correctly.
2. The second problem was that I used `FlatList`. On Android, images outside the screen are rendered but events on images are not fired until the user scroll to those images.

Hope it might help 👋.

**Comment by tills98** [comment]
same problem

**Comment by amiratak88** [comment]
same problem, i can see the image but the event handlers don't seem to be triggered.

**Comment by amiratak88** [comment]
I was able to fix this using this [issue](https://github.com/facebook/react-native/issues/13763#issuecomment-306418171).

**Comment by zeptonaut** [comment]
In case this helps anyone else: at least in React Native Web, I was running into the issue where `onLoad` was never being called. It turned out that when the image was first rendered, I was passing it a null `source` (or a `source` of `{uri: null }`). When the source was later swapped out for a meaningful one, `onLoad` was never called.

I got around this by conditionally rendering the `Image` only after the URI had a meaningful value:

```js
{imageSource && imageSource.uri && <Image source={imageSource} .../>}
```
