### ISSUE TITLE
:app:bundleReleaseJsAndAssets hangs forever on Hermes

### ISSUE THREAD

**Issue by MarekPawlowskiGelato** [facebook/react-native#27057]
`react-native run-android --variant=release` hangs forever on :app:bundleReleaseJsAndAssets.

After brief debugging it seems it hangs on hermes command:
`../../node_modules/hermes-engine/osx-bin/hermes -emit-binary -out /Users/marekpawlowski/Workspace/my-app/android/app/build/generated/assets/react/staging/release/index.android.bundle.hbc /Users/marekpawlowski/Workspace/my-app/android/app/build/generated/assets/react/staging/release/index.android.bundle -O -output-source-map`

It throws a lot of warnings like this:
`/Users/marekpawlowski/Workspace/my-app/android/app/build/generated/assets/react/staging/release/index.android.bundle:28:134: warning: the variable "Promise" was not declared in function "isBoldTextEnabled"
...)(r(d[1])),t=r(d[2]),o=r(d[3]),s=new Map,c={isBoldTextEnabled:function(){return Promise.resolve(!1)},isGrayscaleEnabled:function(){return Promise.resolve(!1)},isInver...
                                                                                   ^~~~~~~`
and hangs... forever.

I've have played a little bit with this command and it seems that removing the last two args `-O -output-source-map` makes it working. (it still throws a lot of warning but it is not hanging)

React Native version:
System:
    OS: macOS 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 5.05 GB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.6.0 - ~/.nvm/versions/node/v12.6.0/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v12.6.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 28.0.3
      System Images: android-24 | Google APIs Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
      Android NDK: 19.2.5345600
  IDEs:
    Android Studio: 3.3 AI-182.5107.16.33.5314842
    Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.2 => 0.61.2
  npmGlobalPackages:
    react-native-cli: 2.0.1

## Steps To Reproduce

1. Just `react-native run-android --variant=release`
And it hangs forever:
`<======-------> 50% EXECUTING [25m 31s]
> IDLE
> :app:bundleReleaseJsAndAssets`

Describe what you expected to happen:
Please verify source map building on hermes as it seems to be broken

**Comment by romanbarzyczakgelato** [comment]
same issue

**Comment by MarekPawlowskiGelato** [comment]
Switching off source map is temp sollution you can do this by adding following key to project.ext.react:
`project.ext.react = [
        enableHermes: true,  // clean and rebuild if changing
        entryFile: "index.js",
        hermesFlagsRelease: [],
]
`

**Comment by ekegodigital** [comment]
Same here, with `hermesFlagsRelease: []` the build takes 3 minutes, without it takes over 11 minutes.

Do we loose anything by the workaround (e.g. performance)?
