### ISSUE TITLE
Flatlist scrolling shows an empty white space in UI 

### ISSUE THREAD

**Issue by nihp** [facebook/react-native#27056]
I am using react-native-flatlist to scroll my list. Here while scrolling I can see a white space in UI. It is not good to see. Also, the scrolling is not smooth

**Comment by nihp** [comment]
This is my sample code. 

```
import React, { Component } from 'react';
import {
  ActivityIndicator,
  Image,
  Platform,
  StyleSheet,
  Text,
  FlatList,
  Button,
  View,
  SafeAreaView,
  ScrollView,
  TouchableOpacity,
  PixelRatio,
  Dimensions,
  StatusBar
} from 'react-native';
import _ from 'lodash';
import ImageCropPicker from 'react-native-image-crop-picker';
import Orientation from 'react-native-orientation';
import FastImage from 'react-native-fast-image';

class MyShowroom extends Component {
  constructor() {
    super();
    this.state = {
      index: 0,
      section: 0,
      width: 0,
      height: 0,
      isPageLoaded: false,
      loadingMoreItems: false,
      lastItemIndex: 0,
      page: 0,
    }
    Orientation.addOrientationListener(this._updateOrientation.bind(this))
  }


        renderList(item) {
            return(
              <TouchableOpacity>
                <View style={{backgroundColor: 'white', alignItems: 'center'}}>
                  <FastImage style={{width: gridWidth, height: gridHeight}}
                    resizeMode={FastImage.resizeMode.contain}
                    source={item.uri}/>
                </View>
              </TouchableOpacity>
            );
          }

    // extra data is rendering from the  redux 
        render(){
          return(
            <FlatList
                          ref={(ref) => { this.flatListRef = ref; }}
                          data={Items}
                          renderItem={({ item }) => this.renderList(item)}
                          numColumns={2}
                          extraData={this.props.pagination}
                          keyExtractor={item => item.id}
                          onEndReached={this._handleMoreItems}
                          maxToRenderPerBatch={10}
                          initialNumToRender = {14}
                          shouldComponentUpdate= {this.shouldItemUpdate()}
                          onEndReachedThreshold={0.001}
                          ListFooterComponent={this._renderFooter}
                          legacyImplementation = {true}
                          bounces = {false}
                          onMomentumScrollEnd={e => this.scroll(e.nativeEvent.contentOffset)}
                        />
          )
        }
```

**Comment by barakmichaely** [comment]
I’d recommend posting your entire code. It looks like there’s other parts you didn’t include here like `_renderFooter` which may be causing the issue, and would help us help you figure out the issue.



For performance, I’d recommend wrapping your list items in a component, and using the `shouldComponentUpdate`. If done properly, it will prevent react from over-rendering the list items (which causes performance issues). 
In your example, the `renderItem` method renders a `TouchableOpacity` as its child. Instead, try something like this:

```
_renderItem(data) {
   return (
      <MyListRow data={data} />
   )
}
```

MyListRow component
```
class MyListRow extends Component {
   shouldComponentUpdate(...) {
      // some logic to determine if we should update
   }

   render() {
      return (
         <TouchableOpacity>
         { ... }
         </TouchableOpacity>
      )
   }
}
```

Also, if you haven’t already, I’d recommend reading this guide. It has helpful tips about FlatList performance.

https://github.com/filipemerker/flatlist-performance-tips/blob/master/README.md

**Comment by nihp** [comment]
@barakmichaely I have updated my code. Can you suggest any solution for this?

```
componentDidMount() {
    let { page } = this.state;
    this.props.fetchAllItems();
    if (page == 0) {
      page = page + 1;
      this.setState({page: page})
      this.props.fetchItemsPerPage(page);
    }
  }

renderList(){
return(
      <TouchableOpacity activeOpacity = { .5 } >
        <View style={{backgroundColor: 'white', alignItems: 'center'}}>
          <FastImage style={{width: deviceWidth, height: deviceWidth}}
            source={item.uri}/>
        </View>
      </TouchableOpacity>
    );
}
_renderFooter(){
return <ActivityIndicator color="#000000" style = {{marginBottom:10, marginTop:10}}/>;
}

shouldItemUpdate(){
    return false;
  }

renderListItems(){
          return(
            <FlatList
                          ref={(ref) => { this.flatListRef = ref; }}
                          data={Items}
                          renderItem={({ item }) => this.renderList(item)}
                          numColumns={2}
                          extraData={this.props.pagination}
                          keyExtractor={item => item.id}
                          onEndReached={this._handleMoreItems}
                          maxToRenderPerBatch={10}
                          initialNumToRender = {14}
                          shouldComponentUpdate= {this.shouldItemUpdate()}
                          onEndReachedThreshold={0.001}
                          ListFooterComponent={this._renderFooter}
                          legacyImplementation = {true}
                          bounces = {false}
                          onMomentumScrollEnd={e => this.scroll(e.nativeEvent.contentOffset)}
                        />
          )
        }

render(){
   return(
   {this.renderListItems()}
)  
}
```

**Comment by barakmichaely** [comment]
Hey @nihp can you post a screenshot or video showing the issue?

**Comment by nihp** [comment]
@barakmichaely Unable to attach video with extension .mov.So I am facing the exact issue of this [comment](https://github.com/necolas/react-native-web/issues/1337#issue-440254501). Scrolling sometimes shows a blank black space. In my case it is white according to the background color. But the issue is with flatlist which I explained above with my code

**Comment by ptcasa** [comment]
> @barakmichaely Unable to attach video with extension .mov.So I am facing the exact issue of this [comment](https://github.com/necolas/react-native-web/issues/1337#issue-440254501). Scrolling sometimes shows a blank black space. In my case it is white according to the background color. But the issue is with flatlist which I explained above with my code

I have same issue, when moving to screen has Flatlist component, It appears.

**Comment by RahulNainwal** [comment]
I am also getting the same issue when I try to implement a flatlist inside a modal and has height of 250 px. Screens are similar like that :
![Screenshot_2019-12-10-11-24-30-291_com firebasepushnotification](https://user-images.githubusercontent.com/36499090/70500085-aa76f100-1b40-11ea-8aa4-4aa40550d1e2.jpg)
![Screenshot_2019-12-10-11-24-52-926_com firebasepushnotification](https://user-images.githubusercontent.com/36499090/70500086-aa76f100-1b40-11ea-80be-ae0f9ec7b9ce.jpg)

**Comment by ptcasa** [comment]
`<SafeAreaView style={{ flex: 0, backgroundColor: colors.purple }} forceInset={{bottom:'never',top:'never'}}/>
				<StatusBar barStyle="light-content" />
				<SafeAreaView style={{ flex: 1, backgroundColor: colors.white }} forceInset={{top:'never'}}>`

and import SafeAreaView from navigation 
`import { NavigationActions, SafeAreaView } from 'react-navigation';`

I use this code for my FlatList  inside and it fixed blank space issue.

**Comment by kevin-klein** [comment]
> `<SafeAreaView style={{ flex: 0, backgroundColor: colors.purple }} forceInset={{bottom:'never',top:'never'}}/>
> 
> <SafeAreaView style={{ flex: 1, backgroundColor: colors.white }} forceInset={{top:'never'}}>`
> 
> and import SafeAreaView from navigation
> `import { NavigationActions, SafeAreaView } from 'react-navigation';`
> 
> I use this code for my FlatList inside and it fixed blank space issue.

This actually worked for me too. Thanks

**Comment by afrinsulthana1** [comment]
> `<SafeAreaView style={{ flex: 0, backgroundColor: colors.purple }} forceInset={{bottom:'never',top:'never'}}/>
> 
> <SafeAreaView style={{ flex: 1, backgroundColor: colors.white }} forceInset={{top:'never'}}>`
> 
> and import SafeAreaView from navigation
> `import { NavigationActions, SafeAreaView } from 'react-navigation';`
> 
> I use this code for my FlatList inside and it fixed blank space issue.

This helped me fix the UI width issue - **UI elements not getting aligned properly filling the screen width**. Thanks @ptcasa 👍

**Comment by Toparound** [comment]
> > `<SafeAreaView style={{ flex: 0, backgroundColor: colors.purple }} forceInset={{bottom:'never',top:'never'}}/>
> > <SafeAreaView style={{ flex: 1, backgroundColor: colors.white }} forceInset={{top:'never'}}>`
> > and import SafeAreaView from navigation
> > `import { NavigationActions, SafeAreaView } from 'react-navigation';`
> > I use this code for my FlatList inside and it fixed blank space issue.
> 
> This actually worked for me too. Thanks

Please could you short explain? I can't understand where to paste this code - for each item or wrap a flatList.
