### ISSUE TITLE
Question:  Memory leak when repeatedly rendering components

### ISSUE THREAD

**Issue by mumu-xi** [facebook/react-native#27054]
React Native version: 0.60.4

## Steps To Reproduce
0. Create a react native project using the official cli tool
1. I defined a component and set a timer inside the component. The rendering of the component is triggered every 100 milliseconds.

![image](https://user-images.githubusercontent.com/23031522/67823998-14db5100-fb00-11e9-8715-388002fc6689.png)
2. Use the dumpsys command to view memory usage. 
```
dumpsys meminfo com.rndemo60
```
Found that the value of **unkown** in **private dirty** has been growing. 
Beginning:
![image](https://user-images.githubusercontent.com/23031522/67824269-d1cdad80-fb00-11e9-8ffb-498e70276ff4.png)
After a few minutes
![image](https://user-images.githubusercontent.com/23031522/67824314-ec078b80-fb00-11e9-9c79-86535f0df983.png)

Describe what you expected to happen:

I want to know why memory is always growing. Or is this normal? If not, how to solve this problem?

**Comment by bashen1** [comment]
https://github.com/facebook/react-native/issues/26995

Very simple and must-have bug, but no reply. 0.61.3 also exists, very basic functional methods actually have BUG

**Comment by mumu-xi** [comment]
> #26995
> 
> Very simple and must-have bug, but no reply. 0.61.3 also exists, very basic functional methods actually have BUG

Yes, very helpless!!!

**Comment by barakmichaely** [comment]
I don’t have a solution for you, but I suspect that the memory leak may be related to the `ImageView` component. You might want to try replacing `ImageView` with a simple component like `Text`, then see if the memory leak still happens. If it replacing it fixes the leak, then at least we’ll know the problem is with the `ImageView` component itself.

If so, you may want to try `react-native-fast-image`, it has some added features like image caching.

https://github.com/DylanVann/react-native-fast-image

**Comment by mumu-xi** [comment]
> I don’t have a solution for you, but I suspect that the memory leak may be related to the `ImageView` component. You might want to try replacing `ImageView` with a simple component like `Text`, then see if the memory leak still happens. If it replacing it fixes the leak, then at least we’ll know the problem is with the `ImageView` component itself.
> 
> If so, you may want to try `react-native-fast-image`, it has some added features like image caching.
> 
> https://github.com/DylanVann/react-native-fast-image


I have tried testing with Text and the result is a memory leak.

**Comment by Rodrigo77777** [comment]
I am experiencing this issue as well, however from my own testing it seems related to timers, and is only happening on iOS. Any setInterval or setTimeout trigger on iOS seems to increase memory usage until the app inevitably crashes. It is a very small increase each time, but it is consistent so it becomes inevitable for the app to crash eventually, if running a setInterval or recurring setTimeouts. The shorter the interval you have, the quicker the app will crash.

The issue does not manifest on Android in my case, the timers do not add memory and the app never crashes. Hopefully the React Native team can have a look at this soon.

**Comment by MichaelBorde** [comment]
OP uploaded screenshots of android dumpsys command. I think the memory leak she encounters is on android plateform and not related to iOS timer bug.

This issue is very similar to https://github.com/facebook/react-native/issues/26407
