### ISSUE TITLE
[iOS][regression] Dev debug menu isn't persisting Chrome Debugging setting

### ISSUE THREAD

**Issue by negativetwelve** [facebook/react-native#2706]
In the latest master, when running the Movies sample app, and selecting "Debug in Chrome", the app refreshes, and the first log sometimes appears in chrome, but all further logs (such as logging something in render) is outputted in the Xcode console rather than the chrome console.

Looking at the menu, the button still asks if I want to "Debug in Chrome" instead of "Disable Chrome Debugging". It might be something related to saving to NSUserDefaults? I believe this commit (https://github.com/facebook/react-native/commit/515d5a5f4b48ffa4f7ac5af0f2dd1b91fb980bfc) is what caused this regression but not positive. Reverting back to (b998e5a7b74905b30b1137a02e14cd5e6f97fccc) before React Native Android and the commit above, the issue is no longer there.

cc @nicklockwood

**Comment by nicklockwood** [comment]
OK, thanks - I'll take a look.

**Comment by negativetwelve** [comment]
Looks like this was fixed via https://github.com/facebook/react-native/commit/b450e36ef8a3bf1920252b3f630d6cbada9ca88e

Thanks @nicklockwood !
