### ISSUE TITLE
when one view overlapping on other view, the clickable is not working... means a button in one view, and that view is out of parent and overlap on another view, there onpress is not working on button.

### ISSUE THREAD

**Issue by KumariShalini** [facebook/react-native#27067]
React Native version:

## Steps To Reproduce

1.
2.

Describe what you expected to happen:

Snack, code example, screenshot, or link to a repository:

**Comment by anmolpandeyy** [comment]
![test](https://user-images.githubusercontent.com/43908929/67923906-32c6b580-fbd5-11e9-9d3e-78681f63bef9.gif)

I just tested it with a fresh react-native application and it seems to be working fine.
