### ISSUE TITLE
Elevation transition delay

### ISSUE THREAD

**Issue by DarkGamesBR** [facebook/react-native#27079]
**Elevation is "delayed" when page switching (react-navigation).**

![alt text](https://i.imgur.com/2n451Sz.gif[/img])

Does anyone know how to solve?

**React Native version:**
> System:
>     OS: Windows 10
>     CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
>     Memory: 1.61 GB / 7.94 GB
>   Binaries:
>     Node: 12.10.0 - C:\Program Files\nodejs\node.EXE
>     Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
>     npm: 6.10.3 - C:\Program Files\nodejs\npm.CMD
>   SDKs:
>     Android SDK:
>       API Levels: 23, 28
>       Build Tools: 28.0.3, 29.0.2
>       System Images: android-28 | Google Play Intel x86 Atom
>   npmPackages:
>     react: ^16.10.2 => 16.11.0
>     react-native: ^0.61.2 => 0.61.3

**Comment by radko93** [comment]
Can you reproduce this without any navigation library e.g. when you switch between components on one screen?

**Comment by brentvatne** [comment]
this is a dup of https://github.com/facebook/react-native/issues/23090
