### ISSUE TITLE
Unable to build project containing Swift libraries and manually linked react native modules

### ISSUE THREAD

**Issue by kmvkrish** [facebook/react-native#27071]
When using Swift libraries (eg: Crashlytics, SwiftKeychainWrapper) installed via CocoaPods in the project along with manually linked ReactNative modules, the project is failing to build.

The issue is causing when "use_frameworks!" directive is used for enabling dynamic frameworks feature.

React Native version: **0.61.2**

## Steps To Reproduce

1. Create a new project with `react-native init rndemo` 2.`cd rndemo`
2. run `npm install realm --save`
3. `cd ios`
4. Open Podfile with a text editor.
5. Add the lines

   > use_frameworks!
   > pod 'SwiftKeychainWrapper'
   > pod 'Crashlytics'

6. run `pod install` and open the rndemo.xcworkspace to open the project.
7. Manually link the RealmReact.xcodeproj since Realm for React Native doesn't support installation via CocoaPods
8. Build the app

The final Podfile should look like below:

> platform :ios, '9.0'
> require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
> 
> target 'rndemo' do
> 
>   pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
>   pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
>   pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
>   pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
>   pod 'React', :path => '../node_modules/react-native/'
>   pod 'React-Core', :path => '../node_modules/react-native/'
>   pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
>   pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
>   pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
>   pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
>   pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
>   pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
>   pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
>   pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
>   pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
>   pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
>   pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
>   pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'
> 
>   pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
>   pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
>   pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
>   pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
>   pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
>   pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
>   pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
> 
>   pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
>   pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
>   pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
> 
>  use_frameworks!
>  pod 'SwiftKeychainWrapper'
>  pod 'Crashlytics'
>
>   target 'rndemoTests' do
>     inherit! :search_paths
>   end
> 
>   use_native_modules!
> end
> 
> target 'rndemo-tvOS' do
> 
>   target 'rndemo-tvOSTests' do
>     inherit! :search_paths
>   end
> 
> end

## Describe what you expected to happen:
With "use_frameworks!" in the Podfile, the project must be built successfully without any errors.

## Actual result:
When linking RealmReact for the iOS project, the RealmReact.mm file imports React/RCTBridge+Private.h file from the React headers. But the import failed due to missing header files.

The build is successful when we remove either Swift libraries or linked RealmReact.xcodeproj from the project. But we need the project to contain both libraries.

**Note: If the "use_frameworks!" is removed, then the headers are available but the pods are not being linked to the project and the build is failing.** SwiftKeychainWrapper could not be build when `use_frameworks!` is removed.

**Comment by jianxinzhoutiti** [comment]
+1

**Comment by adithyareddyZ** [comment]
+1
