### ISSUE TITLE
a jsc-crash

### ISSUE THREAD

**Issue by foolishgao** [facebook/react-native#27083]
I use ReactNative version 0.59.2.

When my Android app runs for a while, I get a jsc crash below, the crash route is not unique.

How can I fix it?

java.lang.Throwable: jni-crash
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'HONOR/STF-AL00/HWSTF:9/HUAWEISTF-AL00/9.1.0.201C00:user/release-keys'
Revision: '0'
Author: collect by 'libunwind'
ABI: 'arm64-v8a'
pid: 26814, tid: 13602, name: AutomaticThread  
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xfffffff3

backtrace:
    r0 d0000000  r1 a9f2f320  r2 00000000  r3 00000001
    r4 c03f5130  r5 0000001d  r6 a9f2f320  r7 ffffffce
    r8 c03f5130  r9 be7ff818  sl 00000001  fp 00000000
    ip c03f5130  sp be7ff7d0  lr c19cd129  pc c19cd16e  cpsr a0010030

    #00 pc 0043116e  ==/lib/arm/libjsc.so   (JSC::JSCallee::visitChildren(JSC::JSCell*, JSC::SlotVisitor&))

    #01 pc 00434d95  ==/lib/arm/libjsc.so   (JSC::JSFunction::visitChildren(JSC::JSCell*, JSC::SlotVisitor&)

    #02 pc 002b2503  ==/lib/arm/libjsc.so   (_ZZN3JSC11SlotVisitor5drainEN3WTF13MonotonicTimeEENK3$_3clERNS_14MarkStackArrayE + 0x00db)

    #03 pc 002b0261  ==/lib/arm/libjsc.so    (JSC::SlotVisitor::drain(WTF::MonotonicTime)

    #04 pc 002b0947  ==/lib/arm/libjsc.so    (JSC::SlotVisitor::drainFromShared(JSC::SlotVisitor::SharedDrainMode, WTF::MonotonicTime))

    #11 pc 00065ac7  /system/lib/libc.so (_ZL15__pthread_startPv+22)
    #12 pc 0001e9ad  /system/lib/libc.so (__start_thread+32)

**Comment by radko93** [comment]
JSC crashes on 0.59 won't be supported, unfortunately. You can try to upgrade your JSCor try a different VM machine.
