### ISSUE TITLE
A JSC-Crash

### ISSUE THREAD

**Issue by foolishgao** [facebook/react-native#27091]
I use ReactNative version 0.59.2.
In our test pure, our Android app runs well，
but when our Android app runs online for a while, we get a JSC crash below, the crash route is not unique

### crash log:

java.lang.Throwable: jni-crash

Build fingerprint: 'HONOR/STF-AL00/HWSTF:9/HUAWEISTF-AL00/9.1.0.201C00:user/release-keys'
Revision: '0'
Author: collect by 'libunwind'
ABI: 'arm64-v8a'
pid: 26814, tid: 13602, name: AutomaticThread
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xfffffff3

backtrace:
r0 d0000000 r1 a9f2f320 r2 00000000 r3 00000001
r4 c03f5130 r5 0000001d r6 a9f2f320 r7 ffffffce
r8 c03f5130 r9 be7ff818 sl 00000001 fp 00000000
ip c03f5130 sp be7ff7d0 lr c19cd129 pc c19cd16e cpsr a0010030

#00 pc 0043116e  ==/lib/arm/libjsc.so   (JSC::JSCallee::visitChildren(JSC::JSCell*, JSC::SlotVisitor&))

#01 pc 00434d95  ==/lib/arm/libjsc.so   (JSC::JSFunction::visitChildren(JSC::JSCell*, JSC::SlotVisitor&)

#02 pc 002b2503  ==/lib/arm/libjsc.so   (_ZZN3JSC11SlotVisitor5drainEN3WTF13MonotonicTimeEENK3$_3clERNS_14MarkStackArrayE + 0x00db)

#03 pc 002b0261  ==/lib/arm/libjsc.so    (JSC::SlotVisitor::drain(WTF::MonotonicTime)

#04 pc 002b0947  ==/lib/arm/libjsc.so    (JSC::SlotVisitor::drainFromShared(JSC::SlotVisitor::SharedDrainMode, WTF::MonotonicTime))

#11 pc 00065ac7  /system/lib/libc.so (_ZL15__pthread_startPv+22)
#12 pc 0001e9ad  /system/lib/libc.so (__start_thread+32)

### React Native version:

info
  React Native Environment Info:
    System:
      OS: macOS 10.14.6
      CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
      Memory: 170.96 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.11.0 - ~/.nvm/versions/node/v8.11.0/bin/node
      Yarn: 1.16.0 - ~/.nvm/versions/node/v8.11.0/bin/yarn
      npm: 5.6.0 - ~/.nvm/versions/node/v8.11.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
      Android SDK:
        API Levels: 20, 21, 22, 23, 24, 25, 26, 27, 28, 29
        Build Tools: 19.1.0, 20.0.0, 21.1.2, 22.0.1, 23.0.1, 23.0.2, 23.0.3, 24.0.0, 24.0.1, 24.0.2, 24.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.1, 27.0.2, 27.0.3, 28.0.0, 28.0.0, 28.0.0, 28.0.1, 28.0.2, 28.0.3, 29.0.0, 29.0.0, 29.0.2
        System Images: android-22 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-25 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.2 => 0.59.2
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Steps To Reproduce

1.
2.

Describe what you expected to happen:

Snack, code example, screenshot, or link to a repository:

**Comment by danibonilha** [comment]
@foolishgao check this [issue](https://github.com/facebook/react-native/issues/24261#issuecomment-548149232), maybe this can help you.

**Comment by tobi512** [comment]
Hey @foolishgao, check your JSC-android version (usually in your package.json) and make sure it is at least version 245459.0.0
Older versions suffer from different native crashes, we had the same problems and fixed these by simply updating the JSC. Updating React Native usually also brings you the latest version of the JSC (if you do not explicitly use a specific version) so that might as well be something you should do...

**Comment by pengcao1** [comment]
could anybody help to answer this question?
react-native-community/jsc-android-buildscripts#127

**Comment by jocoders** [comment]
I have the similar error on react-native 0.63.2, jsc-android: ^245459.0.0:
```
Crashed: Thread :  SIGSEGV  0x0000000000000010
#00 pc 0x73121a9748 libjsc.so 
#01 pc 0x73121f5fe8 libjsc.so 
#02 pc 0x7407046ba8 libc.so 
```
Any ideas how to solve it?
