### ISSUE TITLE
 Images posted to server via fetch get their size inflated significantly

### ISSUE THREAD

**Issue by thmsl** [facebook/react-native#27099]
**React Native version:**

System:

    OS: macOS 10.15
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Memory: 181.84 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  
  Binaries:
  
    Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  
  SDKs:
  
    iOS SDK:
      Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
  
  IDEs:
  
    Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
  
  npmPackages:
  
    react: 16.8.1 => 16.8.1
    react-native: 0.61.3 => 0.61.3

 react-native-cli: 2.9.0

## Description

After upgrading to RN 0.61.3, we observed that the hash of an image received on the server differs with the hash of the original picture on the phone.

The size is actually inflated significantly
jpg on the phone: 264KB
jpg received on the server: 628KB

This issue happens on iOS (13.1 tested only)
No issue detected on Android

Downgrading to 0.59 fixes the issue.

_body

```javascript=
  const formData = new FormData()
  formData.append(`files`, {
    uri: 'file://' + filepath,
    name: 'test.jpg',
    filename: 'test.jpg',
    type: 'application/octet-stream'
  })

```

Headers
```javascript=
      {
        Accept: 'application/json',
        // doesn't work with 'application/octet-stream' neither
        'Content-Type': 'multipart/form-data'
      }
```

Request
```javascript=
  // prepare form data
  // send post request
  fetch(`http://localhost:3000/upload`, 
  {
    method: 'POST',
    headers: {
      Accept: 'application/json',
      // doesn't work with 'application/octet-stream' neither
      'Content-Type': 'multipart/form-data'    
    },
    body: formData
  }).then(resp => {
    console.log('success: ' + JSON.stringify(resp))
  }).catch(err => {
    console.log('error: ' + err.message)
  })

```

The image size is unchanged until it is posted.
Image received by the server is modified.

### Clone test repository
https://github.com/ivzeus/test-uploader

### Start local node server to receive file uploads
The server sample is based on this [repository](https://github.com/Majidkn/nodejs-simple-file-upload.git)
```bash
# in project root
cd server
npm i
node ./server.js
```
It starts a server at `localhost:3000` and accepts file upload through `/upload` POST request. Uploaded files will be stored in `server/uploads` folder.

### Run ReactNative sample
This sample was created by initializing a blank React Native project

To run the demo:
```bash
# in project root
npm i
cd ios
pod install
cd ..
npm run ios
```
- First click on `DOWNLOAD IMG` and `DOWNLOAD BIN` to save an image and a binary file to app storage ([original image](https://images.unsplash.com/photo-1547531455-c20b677ded4b?ixlib=rb-1.2.1&w=1000&q=80) size: 260,062 bytes)

- Then try clicking on `UPLOAD IMG` or `UPLOAD BIN` and observe the server console
- Notice how the image file has been changed when uploaded, but not the binary file (new image size: 718,367 bytes)

**Comment by thmsl** [comment]
We are now refactoring using rn-fetch-blob instead of axios.

**Comment by tareqdayya** [comment]
same happens with me when trying to convert image to blob to send over network:
```
const img = await fetch(MY_IMAGE_URI);
const blob = await img.blob();
console.log(blob.size);
```

the blob size is 2x the size of the original picture. The problem appears to only affect ios. Android is fine.

I now use react-native-fetch-blob to work around this.

**Comment by builtbyproxy** [comment]
> We are now refactoring using rn-fetch-blob instead of axios.

Hey @thmsl Could you please offer some insight into why this change was made? 
Also, if we don't want this size increase how would you suggest we prevent it?

**Comment by cristianoccazinsp** [comment]
Facing the same issue on iOS. Uploaded image with fetch is inflated and loses all its metadata, what's going on? Why is the file even tampered with?

**Comment by MrZhaoCn** [comment]
the reason is that：when we upload a jpg image，react native will use RCTImageLoader to load the image , in RCTImageLoader:
- (id)sendRequest:(NSURLRequest *)request withDelegate:(id<RCTURLRequestDelegate>)delegate
{
    __block RCTImageLoaderCancellationBlock requestToken;
    requestToken = [self loadImageWithURLRequest:request callback:^(NSError *error, UIImage *image) {
        if (error) {
            [delegate URLRequest:requestToken didCompleteWithError:error];
            return;
        }

        NSString *mimeType = nil;
        NSData *imageData = nil;
        if (RCTImageHasAlpha(image.CGImage)) {
            mimeType = @"image/png";
            imageData = UIImagePNGRepresentation(image);
        } else {
            mimeType = @"image/jpeg";
            imageData = UIImageJPEGRepresentation(image, 1.0);
        }

        NSURLResponse *response = [[NSURLResponse alloc] initWithURL:request.URL
                                                            MIMEType:mimeType
                                               expectedContentLength:imageData.length
                                                    textEncodingName:nil];

        [delegate URLRequest:requestToken didReceiveResponse:response];
        [delegate URLRequest:requestToken didReceiveData:imageData];
        [delegate URLRequest:requestToken didCompleteWithError:nil];
    }];

    return requestToken;
}

when a jpg image upload,RCTImageLoader will use UIImageJPEGRepresentation(image, 1.0) to get the blob ,while UIImageJPEGRepresentation function get the size is different of the origin image size.that the reason why jpg image size is different, png size is same

**Comment by cristianoccazinsp** [comment]
Why does react native need all that? Can't it just treat the image as a
regular file? Loading the whole image in memory and doing professing on it
is definitely a bad idea; it should be treated as any file.

**Comment by ganzik** [comment]
https://stackoverflow.com/questions/56682109/react-native-through-upload-image-on-s3-bucket-using-aws-sdk

1. add node-module 'base64-arraybuffer'
```sh
yarn add base64-arraybuffer
```

2. 
```js
import {decode} from 'base64-arraybuffer';

 const base64 = await RNFS.readFile(filePath, 'base64');
  // console.log('base64', base64); //get base64 data

  const arrayBuffer = decode(base64);
  //console.log('arrayBuffer', arrayBuffer.byteLength);

 await Storage.put(uploadPath, arrayBuffer, {
    progressCallback(progress) {
      image.progress = (progress.loaded / progress.total) * 100;
      // dispatch or setState image progress
    },
    contentType: mime,
  })
```

**Comment by MayoudP** [comment]
@cristianoccazinsp Did you succeed to fixe it or found a workaround ?

**Comment by cristianoccazinsp** [comment]
@MayoudP I ended up using rn-fetch-blob to upload files.

**Comment by MayoudP** [comment]
> @MayoudP I ended up using rn-fetch-blob to upload files.

I wasn't able to make this library works with a pre-signed URL for an upload on S3... By any chances, do you have any snippet code or example ?

**Comment by cristianoccazinsp** [comment]
Actually, now that I look again, I'm using https://github.com/Vydia/react-native-background-upload (my own fork actually https://github.com/cristianoccazinsp/react-native-background-upload) for iOS uploads, and regular fetch for Android.

I don't have an AWS example, but it shouldn't be any different, just a bunch of headers/query string parameters.

**Comment by awinograd** [comment]
My workaround using expo-file-system

```js
  // Workaround for https://github.com/facebook/react-native/issues/27099
  if (Platform.OS === 'ios' && blob.type === 'image/jpeg') {
    const originalUri = uri;
    uri = `${FileSystem.documentDirectory}resumableUploadManager-${fileName}.toupload`;
    await FileSystem.copyAsync({ from: originalUri, to: uri });
    blob = new Blob([await getBlobForUri(uri)], { type: 'image/jpeg' });
  }

```

**Comment by chrisbobbe** [comment]
Stale-bot, it looks like there hasn't been an official fix or workaround. 🙂

**Comment by gensc004** [comment]
Hello everyone in the future still struggling with this. I was struggling with a similar issue trying to upload images to AWS S3 through a PreSigned PUT URL with metadata (specifically EXIF data like GPS coordinates). RNFS uploadFiles doesn't play nicely with signed S3 urls, so I was trying to use the built in XMLHttpRequest. I was able to upload files, but their metadata was just being silently removed due to things discussed earlier in this thread. Following through on @ganzik83 's train of thought, I was able to finally get metadata to stick through the upload process by converting the image to base64, fetching the base64, converting the result of the fetch into a blob, and then uploading that blob. The code ended up looking like this:

```
import RNFS from 'react-native-fs';

const uploadImageToSignedURL = async (signedURL, imagePath) => { // NOTE: In my case, Signed URL was configured with Content-Type: 'image/jpeg'
        const getBlob = async (fileUri) => {
            const base64 = await RNFS.readFile(fileUri, 'base64');
            const resp = await fetch(`data:image/jpeg;base64,${base64}`);
            const imageBody = await resp.blob();
            return imageBody;
        };

        const uploadImage = async (uploadUrl, imagePath) => {
            const imageBody = await getBlob(imagePath);

            return fetch(uploadUrl, {
                method: "PUT",
                body: imageBody,
            });
        };
        
        return uploadImage(signedURL, imagePath)
}
```

**Comment by simonmitchell** [comment]
@ShogunPanda is this definitely resolved in 0.64.2? I can't find anything about it in the release notes! I'm not 100% sure I want to do the workaround you've posted as seems a bit hacky which could result in future bugs 😬

**Comment by ShogunPanda** [comment]
@simonmitchell It is hacky. :)

Unfortunately I couldn't update the project I'm currently on so I have no idea if 0.64.2 fixes for real or not. I trust RN devs on this.

**Comment by simonmitchell** [comment]
I tried in the end @ShogunPanda and seemed not to be fixed :( I think I'll go for hacky solution for now and try and keep an eye on when this issue is resolved! Thanks for the help ☺️

**Comment by tungduonghgg123** [comment]
It seems this issue still exist on latest react-native version 0.65.1

**Comment by arthuralee** [comment]
It's fixed in 0.66 (https://github.com/facebook/react-native/blob/main/CHANGELOG.md#v0660)

**Comment by mpatafio** [comment]
I'm experiencing this issue on react-native 0.66.4

**Comment by dmarkow** [comment]
Having the same issue on 0.66.4. Looks like the [fix was reversed pretty quickly](https://github.com/facebook/react-native/commit/e83feffeba567b4e304181632128ee1caa036c45), so I'm wondering if it ever actually got included in a release...

**Comment by StampixSMO** [comment]
This is indeed still an issue in the latest release. It only happens when you have a file uri that has the jpeg extension however, as beautifully found out by @MrZhaoCn.

I find the easiest solution to be to rename the file with RNFS
```ts
const newUri = originalUri.replace(/\.jpe?g$/i, '.bin');
await RNFS.moveFile(originalUri, newUri);
```
