### ISSUE TITLE
devDisabledInDebug not building apk with dev disabled

### ISSUE THREAD

**Issue by Sumit-Chakole** [facebook/react-native#27090]
`project.ext.react = [
    entryFile: "index.js",
    bundleInDebug: true,
    devDisabledInDebug: true
]

apply from: "../../node_modules/react-native/react.gradle`

Apk built using following ways, its still shows development menu on shake
* react-native run-android
* gradlew assembleDebug
* react-native run-android --variant=debug
* gradlew bundleDebugJsAndAssets then gradlew assembleDebug

React Native version: 0:59:10

  React Native Environment Info:
    System:
      OS: Windows 8.1
      CPU: (4) x64 Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
      Memory: 1.70 GB / 7.88 GB
    Binaries:
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5900203

## Steps To Reproduce

1. react-native init AwesomeProject --version 0.59.10
2. Add following in app build.gradle file before react gradle is applied
```
bundleInDebug: true,
    devDisabledInDebug: true
```
3. react-native run-android

Describe what you expected to happen:
1. Debug build of apk should work without metro bundler and it should not show development menu or yellow warning boxes. This is suppose to be given to our tester

Link to a repository of minimum code that reproduce issue:
https://github.com/Sumit-Chakole/rn-dev-disable-issue

**Comment by radko93** [comment]
Can you reproduce it in latest RN? If not this won't be resolved on React Native 0.59.

**Comment by Sumit-Chakole** [comment]
Issue exists in latest version of react native too- https://github.com/Sumit-Chakole/dev_disabled_repo2

**Comment by Sumit-Chakole** [comment]
Any update on this? Any work around for this? I have tried using build variant= UAT to build apk for uat. Problem is-
1. I have dependencies on other native projects in my app which didn't understand variant= UAT
2. Varaint can only build android build not iOS

How others react native users are providing their builds for UAT?
