### ISSUE TITLE
> Task :app:mergeDebugResources FAILED

### ISSUE THREAD

**Issue by gnolmahp** [facebook/react-native#27104]
I can't run my first react native project.
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> 8 exceptions were raised by workers:
  com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource compilation failed
  C:\Windows\System32\aaa\android\app\build\intermediates\res\merged\debug: error: directory does not exist.

**Comment by hramos** [comment]
Closing after several months without followup from the author. Please make sure to fill in the issue template if you decide to file a new issue.
