### ISSUE TITLE
[Android] StatusBar jumps whole screen when hidden

### ISSUE THREAD

**Issue by svenlombaert** [facebook/react-native#27106]
Was coming across this issue: https://github.com/facebook/react-native/issues/24417 which was closed because the reporter didn't care to post his environment info. Just copy-pasting from that issue into here

React Native version: 0.60  (using a patched version with V8 as js engine)
```
System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 23.32 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.12.0 - /usr/local/bin/node
    Yarn: 1.10.1 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: github:getdelta/react-native#0.60-patched+v8-prebuilt => 0.60.5-patch.5
  npmGlobalPackages:
    create-react-native-app: 1.0.0
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
```

## Steps To Reproduce

1. Hide the statusbar on any screen

### Describe what you expected to happen:

The statusbar should disappear, but the screen should not jump down.

This happens on the Google Pixel 3 XL, but is fine on the normal Google Pixel 3. It must be something with the notch.

![](https://i.imgur.com/4LZcsec.gif)

**Comment by svenlombaert** [comment]
This is still an issue

**Comment by arnriu** [comment]
Still an issue on rn 0.62

**Comment by arnriu** [comment]
Solved it with:
```
<item name="android:windowLayoutInDisplayCutoutMode">shortEdges</item>
```
in `android/app/src/main/res/values/styles.xml`

And
```
import android.view.View;

....

@Override
public void onCreate(Bundle savedInstanceState) {

...

    getWindow().getDecorView()
        .setSystemUiVisibility(View.SYSTEM_UI_FLAG_LAYOUT_STABLE | View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN);
```
in `android/app/src/main/java/com/gotobridge/MainActivity.java`

**Comment by PoLePanda** [comment]
This is still an issue

**Comment by tailorem** [comment]
Also still an issue on Galaxy Note 10 Ultra and Huawei P30 Pro in React Native 0.63.3.

**Comment by Brightness99** [comment]
Same issue
