### ISSUE TITLE
node_modules/@babel/runtime/helpers/interopRequireWildcard.js: "" is not a valid identifer name

### ISSUE THREAD

**Issue by darkstar3057** [facebook/react-native#27119]
## Description
I ran expo start --ios and got the following error (screenshot below):

```
node_modules/@babel/runtime/helpers/interopRequireWildcard.js: "" is not a valid identifer name
Failed building JavaScript bundle.
```

Note that I had done some stuff with AWS Amplify right before this started happening, but I rolled that all back and I still get the error.

## Environment
    System:
      OS: macOS 10.14.6
      CPU: (8) x64 Intel(R) Core(TM) i7-4750HQ CPU @ 2.00GHz
      Memory: 1.27 GB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.2 - /usr/local/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.12.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
      Android SDK:
        API Levels: 28
        Build Tools: 28.0.0
        System Images: android-29 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5900203
      Xcode: 11.2/11B52 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1

## Steps To Reproduce
1. expo start --ios

## Screenshot
![Simulator Screen Shot - iPhone 11 Pro Max - 2019-11-05 at 17 35 35](https://user-images.githubusercontent.com/22609096/68207522-1e2f5680-fff5-11e9-93bf-e76fadff67d4.png)

**Comment by yanavoznuk** [comment]
The same problem :(

**Comment by arthedza** [comment]
Babel 7.7.0 was released today

**Comment by arthedza** [comment]
https://github.com/facebook/react-native/issues/27120#issuecomment-549830783
