### ISSUE TITLE
Latest NPX Documentation for react-native error, cant start

### ISSUE THREAD

**Issue by jordanl010** [facebook/react-native#27112]
Hi there, 

I am running on linux, I installed react-native via the latest documentation here:
https://facebook.github.io/react-native/docs/getting-started

NOTE: I followed the non-expo version so the cli version.

React Native version:
3.0.0-alpha.7

## Steps To Reproduce

1. Follow steps outlined in the instructions via github getting-started tutorial.
2. Prepare emulator as defined in the tutorial.
3. Run npx react-native run-android

NOTE: This is with the emulator running already. tried both with it running and not running. Opened via android studio and ran manually and it worked.

------------------------------------
Emulator listed: 

$ emulator -list-avds
Nexus_5X_API_29_x86

Describe what you expected to happen:

Error: 

$ npx react-native run-android
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 864 file(s) to forward-jetify. Using 8 workers...
info Starting JS server...
/bin/sh: 1: adb: not found
info Launching emulator...
error Failed to launch emulator. Reason: No emulators found as an output of `emulator -list-avds`.
warn Please launch an emulator manually or connect a device. Otherwise app may fail to launch.
info Installing the app...

> Task :app:installDebug
07:38:19 V/ddms: execute: running am get-config
07:38:19 V/ddms: execute 'am get-config' on 'emulator-5554' : EOF hit. Read: -1
07:38:19 V/ddms: execute: returning
Installing APK 'app-debug.apk' on 'Nexus_5X_API_29_x86(AVD) - 10' for app:debug
07:38:19 D/app-debug.apk: Uploading app-debug.apk onto device 'emulator-5554'
07:38:19 D/Device: Uploading file onto device 'emulator-5554'
07:38:19 D/ddms: Reading file permision of /home/ghostface/Projects/AwesomeDude/android/app/build/outputs/apk/debug/app-debug.apk as: rw-r--r--
07:38:20 V/ddms: execute: running pm install -r -t "/data/local/tmp/app-debug.apk"
07:38:24 V/ddms: execute 'pm install -r -t "/data/local/tmp/app-debug.apk"' on 'emulator-5554' : EOF hit. Read: -1
07:38:24 V/ddms: execute: returning
07:38:24 V/ddms: execute: running rm "/data/local/tmp/app-debug.apk"
07:38:24 V/ddms: execute 'rm "/data/local/tmp/app-debug.apk"' on 'emulator-5554' : EOF hit. Read: -1
07:38:24 V/ddms: execute: returning
Installed on 1 device.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.5/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 12s
27 actionable tasks: 5 executed, 22 up-to-date
info Connecting to the development server...
warn Failed to connect to development server using "adb reverse": spawnSync adb ENOENT
info Starting the app...

**Comment by kamrankamrani** [comment]
i have the same issue
