### ISSUE TITLE
yarn install command is not downloading .plist file for frameworks

### ISSUE THREAD

**Issue by govindprasadgupta** [facebook/react-native#27117]
I am using yarn in stall command for installing react native package. I am using react naive version 0.61. Using yarn I am not able to download info.plist file for react native iOS framework(RCTVibration). While using npm command I am able to download these files.

Using nom command RCTVibration:
<img width="882" alt="Screen Shot 2019-11-05 at 5 03 11 PM" src="https://user-images.githubusercontent.com/2104937/68204541-39e32e80-ffee-11e9-91e7-84e1f5223067.png">

Using yarn command:
<img width="882" alt="Screen Shot 2019-11-05 at 5 03 15 PM" src="https://user-images.githubusercontent.com/2104937/68204556-42d40000-ffee-11e9-9487-39a279d1e907.png">

Can you tell me reason for not downloading plist file using yarn command

**Comment by Fawxy** [comment]
Just ran into this myself. did you manage to solve it?

**Comment by ARazaAnjum** [comment]
same issue is appearing for me.  did you manage to solve it?
