### ISSUE TITLE
[Android] Creating an Android bundle

### ISSUE THREAD

**Issue by cosmith** [facebook/react-native#2712]
Hi, I'm not sure if this is me not finding the relevant info in the docs or if the functionality is not there yet.
How do I create an Android bundle?

```
react-native bundle
Building package...
transforming [========================================] 100% 309/309
Build complete
Successfully saved bundle to ios/main.jsbundle
```

No mention of android, and if I delete `index.ios.js` the bundling breaks.

Also there's no mention that I could find of creating a release APK, any info on this? Are we supposed to run `./gradlew assembleRelease` in the android folder or something similar?

Sorry for all the questions ;)

**Comment by foghina** [comment]
See #2703 for more discussion on this topic.

Basically, you need to manually download the Android bundle (e.g. `http://localhost:8081/index.android.bundle`) and put it in `android/app/src/main/assets`. `./gradlew assembleRelease` should work after that.

**Comment by cosmith** [comment]
Thanks, I hadn't realized it was the same thing. I'll close this then.
