### ISSUE TITLE
could not found @ReactModule annotation in com.swmansion.gesturehandler.react.RnGestureHandleModule 

### ISSUE THREAD

**Issue by bigkrys** [facebook/react-native#27130]
i run command react-native run-android,and then i got  this
![image](https://user-images.githubusercontent.com/17899020/68264165-e5d65980-0082-11ea-9a72-df7efe7e9a2e.png)

React Native version:0.58.6

React Native Environment Info:
System:
OS: Windows 10
CPU: (20) x64 Intel(R) Xeon(R) CPU E5-2660 v2 @ 2.20GHz
Memory: 3.98 GB / 15.93 GB
Binaries:
Yarn: 1.19.1 - C:\Users\Administrator.SC-20191023
## Steps To Reproduce

1.
2.

Describe what you expected to happen:
good running

Snack, code example, screenshot, or link to a repository:

**Comment by dulmandakh** [comment]
Please upgrade you RN to 0.60 or above, as @ReactModule annotation is introduced in 0.60. Thanks
