### ISSUE TITLE
Can't build release APK Windows

### ISSUE THREAD

**Issue by mezalejandro** [facebook/react-native#27139]
With hermes enabled can't compile without this:
[https://github.com/facebook/react-native/issues/25599#issuecomment-515304874](url)

And now i have this error: 
* What went wrong:
Execution failed for task ':app:transformNativeLibsWithMergeJniLibsForRelease'.
> More than one file was found with OS independent path 'lib/x86/libc++_shared.so'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with 
1m--scan to get full insights.

React Native version:

System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
    Memory: 15.79 GB / 31.89 GB
  Binaries:
    Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 23, 25, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5900203
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.3 => 0.61.3

## Steps To Reproduce

1. cd android
2. ./gradlew assembleRelease

Describe what you expected to happen:

Snack, code example, screenshot, or link to a repository:

**Comment by TommyLeong** [comment]
Issue you face seems to be fixed with the [RN 0.61.4](https://github.com/react-native-community/releases/blob/master/CHANGELOG.md).

**Comment by mezalejandro** [comment]
with version 0.61.4 it is solved!
