### ISSUE TITLE
Unable to find a specification for `FBReactNativeSpec (= 0.61.4)` depended upon by `React-CoreModules`

### ISSUE THREAD

**Issue by codler** [facebook/react-native#27140]
After upgrading from 0.60.5 to 0.61.4 I no longer can start the app again..

Unable to find a specification for `FBReactNativeSpec (= 0.61.4)` depended upon by `React-CoreModules`

error: Build input file cannot be found: '/node_modules/react-native/ReactCommon/yoga/yoga/YGMarker.cpp' (in target 'yoga' from project 'Pods')

React Native version:
System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 29.32 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.10.0 - /usr/local/bin/node
    npm: 6.10.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 23, 28
      Build Tools: 28.0.3, 29.0.2
      System Images: android-28 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    react: ^16.11.0 => 16.11.0
    react-native: ^0.61.4 => 0.61.4
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7

## Steps To Reproduce

Upgrading from 0.60.5 to 0.61.4

**Comment by ZsKLiQuid** [comment]
How do you resolve this issue ?

**Comment by codler** [comment]
Adding this to `Podfile`

```
  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
```

**Comment by boostmerlin** [comment]
➜  ios pod install --repo-update
Updating local specs repositories
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `Folly` from `../node_modules/react-native/third-party-podspecs/Folly.podspec`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
[!] Unable to find a specification for `React-RCTBlob (= 0.61.4)` depended upon by `React`

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

**Comment by RavindraMaddukuri** [comment]
@boostmerlin I tried what you said above but getting the same error which is given below.
[!] Unable to find a specification for `FBReactNativeSpec (= 0.61.5)` depended upon by `React-CoreModules`

**Comment by aashish-pixere** [comment]
Anyone know about this solution? Please help.

**Comment by ICeZer0** [comment]
This should be the correct directory @RavindraMaddukuri .`pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"`

Did you run `pod install --repo-update` ?

**Comment by professorkolik** [comment]
I had similar issue, when I upgraded RN to 0.62+ I missed below line in ios/PodFile

`use_react_native!(:path => config["reactNativePath"])`

**Comment by zaheerahmad92001** [comment]
run following command 
pod install --repo-update
it solve my issue
