### ISSUE TITLE
Android: Initial render with scale 0 does not work

### ISSUE THREAD

**Issue by nick-michael** [facebook/react-native#27146]
React Native version: 0.61.4 (also tried with 0.61.2)

## Steps To Reproduce

1. On Android, render a component with scale 0

Describe what you expected to happen:
The item should not be visible. This works fine on iOS.

What actually happens:
The item renders normal size. Changing the value to something like `0.0001` works, but too many zeros will break it. Also the threshold for the number of zeros that break it seems to be related to how complex the children are but I'm not 100% sure with this one. I just know that some of my views break even with scale set to 0.1.

This seems very similar to https://github.com/facebook/react-native/issues/6278 but it looks like that issue was supposedly fixed by https://github.com/facebook/react-native/commit/ab80001c905dbfb9354232c7a6c7e887736642b5

Snack, code example, screenshot, or link to a repository:
I have been unable to reproduce this in a basic example so I will paste one of the use cases along with some gifs.

Component being rendered:
```js
import React, { Component } from 'react';
import { Animated } from 'react-native';

import style from './loading.style';

const dotKeys = ['dotOne', 'dotTwo', 'dotThree'];
const dotMin = 1;
const dotMax = 1.5;
const duration = 250;

const flatten = arr => [].concat(...arr);

export class Loading extends Component {
  private timeout: any;

  state = {
    hidden: true,
    width: new Animated.Value(0.00001),
    dotOne: new Animated.Value(1),
    dotTwo: new Animated.Value(1),
    dotThree: new Animated.Value(1),
  };

  componentDidMount() {
    this.timeout = setTimeout(() => {
      this.setState({ hidden: false });
    }, 2000);
  }

  componentWillUnmount() {
    clearTimeout(this.timeout);
  }

  componentDidUpdate(_, { hidden: prevHidden }) {
    if (prevHidden && !this.state.hidden) {
      const appear = Animated.timing(this.state.width, {
        toValue: 1,
        duration: 100,
        useNativeDriver: true,
      });
      const animations = dotKeys.map(dotKey => [
        Animated.timing(this.state[dotKey], {
          toValue: dotMax,
          duration,
          useNativeDriver: true,
        }),
        Animated.timing(this.state[dotKey], {
          toValue: dotMin,
          duration,
          useNativeDriver: true,
        }),
      ]);
      appear.start(() => {
        Animated.loop(Animated.sequence(flatten(animations))).start();
      });
    }
  }

  render() {
    return (
      <Animated.View style={[style.container, { transform: [{ scaleX: this.state.width }] }]}>
        {dotKeys.map(dotKey => (
          <Animated.View key={dotKey} style={[style.dot, { transform: [{ scale: this.state[dotKey] }] }]} />
        ))}
      </Animated.View>
    );
  }
}
```

============================================
**Gifs**

Working:
![scale-working](https://user-images.githubusercontent.com/9058133/68354724-0810bb80-0105-11ea-9471-b99b41857ea8.gif)

Broke - Scale 0:
![scale-0-dead](https://user-images.githubusercontent.com/9058133/68354740-1363e700-0105-11ea-8a45-0472a075e349.gif)

Broke - Scale Nearly 0:
![scale-nearly-0-dead](https://user-images.githubusercontent.com/9058133/68354755-2080d600-0105-11ea-83cf-1af9e023fb0a.gif)

**Comment by jiasongs** [comment]
+1

**Comment by mmazzarolo** [comment]
For some reason this also happen with the initial value of an opacity animation on Android.
Fading out a view with an initial value of `1` doesn't work. `0.99` works fine.

**Comment by RichardLindhout** [comment]
I think React Native Paper had problems with this too: https://github.com/callstack/react-native-paper/pull/1440

**Comment by guopeng1994** [comment]
+1

**Comment by wodin** [comment]
Here's a snack that reproduces the problem for me on a Galaxy S8:

https://snack.expo.io/@wodin/rn-27146

It seems there might be a race condition involved, because sometimes deleting/changing lines that should have no effect and then reloading causes the `scaleX: 0` `Block`s to be different lengths. Usually they seem to be the same length as the `Block` rendered immediately above each `scaleX: 0` `Block`, though.

![All red blocks should be invisible](https://user-images.githubusercontent.com/4579020/75345660-d08d7100-58a5-11ea-8f14-c1bf6870e770.jpg)

**Comment by Paduado** [comment]
Just bumped into this! Any workarounds?

**Comment by wodin** [comment]
The workaround is basically to use 0.1 or 0.01 etc. instead of 0.
