### ISSUE TITLE
Missing Domain-name Validation and Lack of Certificate Pinning

### ISSUE THREAD

**Issue by n00bm5st3r69** [facebook/react-native#27145]
We have performed an app scan and received the following vulnerabilities below. Does anyone know how to resolve these issues?

Vulnerability Name | Calling Method | Method Signature | Location
-- | -- | -- | --
Missing Domain-name Validation | okio.Okio.sink(java.net.Socket):okio.Sink | com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake():void | (okio\Okio.java:117)
Missing   Domain-name Validation | okio.Okio.source(java.net.Socket):okio.Source | com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake():void | (okio\Okio.java:203)
Missing Domain-name Validation | okhttp3.internal.connection.RealConnection.connectTls(int,   int, okhttp3.internal.connection.ConnectionSpecSelector):void | com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake():void | (okhttp3\internal\connection\RealConnection.java:241)
Lack   of Certificate Pinning | okhttp3.internal.connection.RealConnection.connectTls(int,   int, okhttp3.internal.connection.ConnectionSpecSelector):void | com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake():void | (okhttp3\internal\connection\RealConnection.java:241)
Lack of Certificate Pinning | okio.Okio.sink(java.net.Socket):okio.Sink | com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake():void | (okio\Okio.java:117)
Lack   of Certificate Pinning | okio.Okio.source(java.net.Socket):okio.Source | com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake():void | (okio\Okio.java:203)

We've been using the IBM Application Security on Cloud to check for any app vulnerabilities.

react-native: 0.42.3

**Comment by ruler47** [comment]
@n00bm5st3r69 any updates?

**Comment by moxorama** [comment]
You can use https://www.npmjs.com/package/react-native-ssl-pinning

**Comment by dulmandakh** [comment]
Please upgrade your RN to current version, and check again.
