### ISSUE TITLE
Text field placeholder text becomes barely readable when in dark mode of iOS13

### ISSUE THREAD

**Issue by nico-bellante** [facebook/react-native#27142]
Here is the text field placeholder while the phone is in light mode:
![image](https://user-images.githubusercontent.com/35939126/68345657-b9343900-00a6-11ea-9e0d-9576a7a4d625.png)

Here is the same text field placeholder while the phone is in dark mode:
![image](https://user-images.githubusercontent.com/35939126/68345630-a6216900-00a6-11ea-82ba-2e3a8b3b7069.png)

React Native version:
```
System:
    OS: macOS 10.14.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 1.57 GB / 32.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 11.13.0 - ~/.nvm/versions/node/v11.13.0/bin/node
    Yarn: 1.19.1 - ~/.yarn/bin/yarn
    npm: 6.7.0 - ~/.nvm/versions/node/v11.13.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-29 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 11.2/11B52 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.1 => 16.8.1
    react-native: 0.61.3 => 0.61.3
  npmGlobalPackages:
    create-react-native-app: 2.0.2
    react-native-cli: 2.0.1
```
## Steps To Reproduce

1. Switch phone from light to dark mode and watch the placeholder become lighter.

Describe what you expected to happen:
The placeholder text to still be legible

**Comment by compojoom** [comment]
I thought that this was a RN 0.59.x error. I just found a workaround for that. Go to your info.plist and set:
`UIUserInterfaceStyle` to `Light`
this fixed it for me
