### ISSUE TITLE
Clarification: I need to crop an image without zoom in/out functionality

### ISSUE THREAD

**Issue by nihp** [facebook/react-native#27156]
I need to add support to crop image in my app. I have checked with different packages but all the packages have zoom in/out functionality. 

Can anyone suggest me any package to crop an image alone? I don't need the zoom in and zoom out. 

React Native version:

## Steps To Reproduce

1.
2.

Describe what you expected to happen:

Snack, code example, screenshot, or link to a repository:

**Comment by neiker** [comment]
You can do it by yourself using ScrollView and ImageEditor

https://facebook.github.io/react-native/docs/scrollview
https://facebook.github.io/react-native/docs/imageeditor

**Comment by nihp** [comment]
@neiker 

Are you suggesting the above will be achieved by using image editor.

Can you give any example?

**Comment by neiker** [comment]
@nihp you can use `cropImage` from this package:

https://github.com/react-native-community/react-native-image-editor#crop-image

You can check the example app.

The second paramenter should be an object including `offset`, `size` and `displaySize` which you can obtain from image size and scrollview.
