### ISSUE TITLE
Android: Elevation is increasing when used multiple times

### ISSUE THREAD

**Issue by go-mad** [facebook/react-native#27152]
Here is the screenshot of the bug:

<img width="520" alt="Screenshot 2019-11-07 at 12 39 52 PM" src="https://user-images.githubusercontent.com/53913590/68368832-dd535100-015e-11ea-82d7-3eaaa2c3506e.png">

**We can clearly see the elevation is increasing gradually.**

React Native version:

<img width="882" alt="Screenshot 2019-11-07 at 12 42 39 PM" src="https://user-images.githubusercontent.com/53913590/68368842-e04e4180-015e-11ea-82ff-ab7794351769.png">

## Steps To Reproduce

1. Create a `View` with an elevation of 3 or 5 (just to see clearly)
2. Render the above view using `<FlatList />` or `<ScrollView />`

Here is the gist for the same:
https://gist.github.com/go-mad/c0520ae9228cb9c8d07015f0377827ec

In above gist `Card.js` is the `View` in step 1 and `App.js` is  where the rendering is happening (Step2).

**Comment by janicduplessis** [comment]
This is the normal behaviour for elevation on android, the shadow is affected by the y position of the view on the screen. See https://stackoverflow.com/questions/45035475/same-elevation-of-views-looks-different-for-top-and-bottom-views
