### ISSUE TITLE
Tool: Jest test snapshot not working as expected

### ISSUE THREAD

**Issue by zeroidentidad** [facebook/react-native#27159]
**I see that when using Jest to test with snapshot style changes  are not detected, only other js render elements on content.**

**React Native version**: 
System:
    OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-2630QM CPU @ 2.00GHz
  Binaries:
    Node: 10.17.0 - /usr/bin/node
    Yarn: 1.19.1 - /usr/bin/yarn
    npm: 6.11.3 - /usr/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    Android SDK:
      API Levels: 10, 15, 23, 24, 25, 26, 28
      Build Tools: 23.0.1, 23.0.3, 25.0.2, 26.0.1, 28.0.3, 29.0.1, 29.0.2
      System Images: android-10 | ARM EABI v7a, android-28 | Google Play Intel x86 Atom
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.4 => **0.61.4** 
  npmGlobalPackages:
    react-native-cli: 2.0.1

## Steps To Reproduce

1. Add code to test with snapshot
2. Run test to take snapshot
3. Modify code related to styles on src file (e.g. App.js)
4. Run test to verify changes if fail test

**Describe what you expected to happen:** 

> Test not fails in  order to detect changes

### Evidence:
- writing snapshot:
![captura](https://user-images.githubusercontent.com/2924638/68445912-e107c780-01a0-11ea-9135-492d1751b47c.png)

- on run test, style changes are not detected:
![captura_1](https://user-images.githubusercontent.com/2924638/68445933-ec5af300-01a0-11ea-90b6-3bb8a8e8adef.png)

- test another js content changes are detected:
![captura_2](https://user-images.githubusercontent.com/2924638/68445951-f67cf180-01a0-11ea-8302-ef830b194f66.png)

**App-test.js example code:**
import 'react-native';
import React from 'react';
import App from '../App';

// Note: test renderer must be required after react-native.
import renderer from 'react-test-renderer';

it('renders correctly', () => {
  renderer.create(<App />);
});

**test("component renders correctly", () => {
  const tree = renderer.create(<App />).toJSON();
  expect(tree).toMatchSnapshot();
});**

Reference on my [Github](https://github.com/zeroidentidad/javascript_fullstack/tree/master/mobile/aRNforMobile/jestBasico/__tests__)

**Comment by kelset** [comment]
Hello there 👋 this issue seems to have been inactive for the past few years. Because of this, it's likely that the issue is not a high priority anymore or it has been solved by OP; for these reasons, we'll close it.

But please, if it's actually still an issue with latest (RN64 at the time of writing) please comment below and we can reopen it or please send a Pull Request with a fix 😊
