### ISSUE TITLE
"defaultSource" on Android is not supported on release.

### ISSUE THREAD

**Issue by dhlolo** [facebook/react-native#27155]
React Native version: 0.61.4

## Steps To Reproduce

1. "defaultSource" on Android is not supported on release.

Describe what you expected to happen:

Snack, code example, screenshot, or link to a repository:
"defaultSource" on Android is not supported on release.

**Comment by dulmandakh** [comment]
defaultSource works only on release build, because it requires a resource to be on a device. So during development it's no shown, because resources are requested from metro or bundler over the network.
