### ISSUE TITLE
xcode 11 js inspector

### ISSUE THREAD

**Issue by Lorenzo30** [facebook/react-native#27158]
guys please someone help me I find nothing on the internet with this error. already deleted derived data and does not work CompileC

`/Users/vanixgoncalves/Library/Developer/Xcode/DerivedData/Entremasons-cvtojofshnpjljdymxtfqfjqhren/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-jsinspector.build/Objects-normal/x86_64/InspectorInterfaces.o /Users/vanixgoncalves/Desktop/Entremasons/node_modules/react-native/ReactCommon/jsinspector/InspectorInterfaces.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'React-jsinspector' from project 'Pods')
    cd /Users/vanixgoncalves/Desktop/Entremasons/ios/Pods
    export LANG=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c++ -target x86_64-apple-ios9.0-simulator -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu++14 -stdlib=libc++ -fmodules -fmodules-cache-path=/Users/vanixgoncalves/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/vanixgoncalves/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wdocumentation -Wunreachable-code -Werror=deprecated-objc-isa-usage -Werror=objc-root-class -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wno-newline-eof -Wno-c++11-extensions -DPOD_CONFIGURATION_DEBUG=1 -DDEBUG=1 -DCOCOAPODS=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk -fasm-blocks -fstrict-aliasing -Wdeprecated-declarations -Winvalid-offsetof -g -Wno-sign-conversion -Winfinite-recursion -Wmove -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wrange-loop-analysis -Wno-semicolon-before-method-body -Wunguarded-availability -index-store-path /Users/vanixgoncalves/Library/Developer/Xcode/DerivedData/Entremasons-cvtojofshnpjljdymxtfqfjqhren/Index/DataStore -iquote /Users/vanixgoncalves/Library/Developer/Xcode/DerivedData/Entremasons-cvtojofshnpjljdymxtfqfjqhren/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-jsinspector.build/React-jsinspector-generated-files.hmap -I/Users/vanixgoncalves/Library/Developer/Xcode/DerivedData/Entremasons-cvtojofshnpjljdymxtfqfjqhren/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-jsinspector.build/React-jsinspector-own-target-headers.hmap -I/Users/vanixgoncalves/Library/Developer/Xcode/DerivedData/Entremasons-cvtojofshnpjljdymxtfqfjqhren/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-jsinspector.build/React-jsinspector-all-target-headers.hmap -iquote /Users/vanixgoncalves/Library/Developer/Xcode/DerivedData/Entremasons-cvtojofshnpjljdymxtfqfjqhren/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-jsinspector.build/React-jsinspector-project-headers.hmap -I/Users/vanixgoncalves/Library/Developer/Xcode/DerivedData/Entremasons-cvtojofshnpjljdymxtfqfjqhren/Build/Products/Debug-iphonesimulator/React-jsinspector/include -I/Users/vanixgoncalves/Desktop/Entremasons/ios/Pods/Headers/Private -I/Users/vanixgoncalves/Desktop/Entremasons/ios/Pods/Headers/Private/React-jsinspector -I/Users/vanixgoncalves/Desktop/Entremasons/ios/Pods/Headers/Public -I/Users/vanixgoncalves/Desktop/Entremasons/ios/Pods/Headers/Public/React-jsinspector -I/Users/vanixgoncalves/Library/Developer/Xcode/DerivedData/Entremasons-cvtojofshnpjljdymxtfqfjqhren/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-jsinspector.build/DerivedSources-normal/x86_64 -I/Users/vanixgoncalves/Library/Developer/Xcode/DerivedData/Entremasons-cvtojofshnpjljdymxtfqfjqhren/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-jsinspector.build/DerivedSources/x86_64 -I/Users/vanixgoncalves/Library/Developer/Xcode/DerivedData/Entremasons-cvtojofshnpjljdymxtfqfjqhren/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-jsinspector.build/DerivedSources -F/Users/vanixgoncalves/Library/Developer/Xcode/DerivedData/Entremasons-cvtojofshnpjljdymxtfqfjqhren/Build/Products/Debug-iphonesimulator/React-jsinspector -include /Users/vanixgoncalves/Desktop/Entremasons/ios/Pods/Target\ Support\ Files/React-jsinspector/React-jsinspector-prefix.pch -MMD -MT dependencies -MF /Users/vanixgoncalves/Library/Developer/Xcode/DerivedData/Entremasons-cvtojofshnpjljdymxtfqfjqhren/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-jsinspector.build/Objects-normal/x86_64/InspectorInterfaces.d --serialize-diagnostics /Users/vanixgoncalves/Library/Developer/Xcode/DerivedData/Entremasons-cvtojofshnpjljdymxtfqfjqhren/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-jsinspector.build/Objects-normal/x86_64/InspectorInterfaces.dia -c /Users/vanixgoncalves/Desktop/Entremasons/node_modules/react-native/ReactCommon/jsinspector/InspectorInterfaces.cpp -o /Users/vanixgoncalves/Library/Developer/Xcode/DerivedData/Entremasons-cvtojofshnpjljdymxtfqfjqhren/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-jsinspector.build/Objects-normal/x86_64/InspectorInterfaces.o

error: error reading '/Users/vanixgoncalves/Desktop/Entremasons/node_modules/react-native/ReactCommon/jsinspector/InspectorInterfaces.cpp'`

**Comment by mostafagalal94** [comment]
have the same problem any solution i get this error only when i run from xcode

**Comment by Lorenzo30** [comment]
yes running via terminal the project works, but by xcode it presents this error.
One previous solution that works for me is to recreate the project.
but when I turn off the computer the error comes back.
it is very strange this error

**Comment by bashen1** [comment]
If your system is Catalina, please give XCode disk access. The easiest way is to:
1. Restart your computer
2. Open your project with Xcode
3. Then Product--->Archive
4. Then pop up the disk access in the Archive, click on the permission to come

**Comment by mostafagalal94** [comment]
@bashen1  not working for me

**Comment by Lorenzo30** [comment]
I can't find any solution to that

**Comment by mostafagalal94** [comment]
finally i resolved the problem you have to give xcode full disk access all toy have to do
1- open system preference 
2- open security & privacy
3- click on full disk access 
![image](https://user-images.githubusercontent.com/30387307/69606308-221a2b80-102b-11ea-89ac-a62a2dbb00ef.png)
4- click on this to add new one and choose xcode 
![image](https://user-images.githubusercontent.com/30387307/69606366-45dd7180-102b-11ea-8a65-bc1ebcf1db61.png)

after that you will able to run your project from xcode this is work for me i hope it will help you

**Comment by temitopealabi** [comment]
Thanks @mostafagalal94  your solution works for me

**Comment by rsyong** [comment]
> 如果您的系统是Catalina，请授予XCode磁盘访问权限。最简单的方法是：
> 
> 1. 重启你的电脑
> 2. 使用Xcode打开您的项目
> 3. 然后产品--->存档
> 4. 然后在存档中弹出磁盘访问权限，单击权限即可

真的很不错，成功的解决了这个问题，困扰我很多天了

**Comment by JSONJuggler** [comment]
@mostafagalal94 thank you so much! Was feeling helpless the last few weeks not being able to get my app running on my physical device (runs on simulator just fine) because of read errors of yoga files that I couldn't find any information on anywhere until I tried your suggestion. THANK YOU!!!
