### ISSUE TITLE
[Android] Rotating UIExplorer example app loses state

### ISSUE THREAD

**Issue by jpeiffer** [facebook/react-native#2716]
React Native: v0.11

In the Android example UIExplorer app, when the device is rotated between portrait and landscape, the app loses state and resets back to the initial page.  This same issue is not present in the iOS version of the UIExplorer app.

**Comment by foghina** [comment]
We don't yet support saving state. We could either lock rotation or handle the `configChange` to work around this for rotation changes.

**Comment by kmagiera** [comment]
By default sample app creates ReactRootView on activity level. If you try putting it within persistent fragment instead then the react context shouldn't get recreated on orientation change

**Comment by marty-wang** [comment]
We need a good solution of responding to activity life cycle. Orientation change is just one of these cases where activities get destroyed and recreacted. Not to mention such life cycle change can occur so often in Android.

**Comment by mattsoftware** [comment]
Not an android developer so this came as quite a shock for me. This link explains why and offers some suggestions. I have not dug into the react source yet to know if I could try to help solve, but this is a bit of a blocker for me at the moment.

http://developer.android.com/guide/topics/resources/runtime-changes.html#HandlingTheChange

**Comment by satya164** [comment]
The default template no longer restarts the activity on rotation change. Closing this.

**Comment by masom** [comment]
@satya164 "The default template no longer restarts the activity on rotation change. Closing this." what is the solution for existing app?

Searching on google links back to this issue with no apparent way to fix this in existing applications.

**Comment by satya164** [comment]
@masom For existing apps, update your `AndroidManifest.xml` to include this line - https://github.com/facebook/react-native/blob/master/local-cli/generator-android/templates/src/app/src/main/AndroidManifest.xml#L14

**Comment by chetstone** [comment]
In case anyone else runs into this, here is an updated link to the  line that may be missing in your `AndroidManifest.xml`:

https://github.com/facebook/react-native/blob/f7d872d433c280bcb8931a597d82642591246252/local-cli/generator-android/templates/src/app/src/main/AndroidManifest.xml#L22

**Comment by itswaze** [comment]
Im still having this issue, and my AndroidManifest.xml has that line.
Everytime I rotate my phone, it resets to initial screen. On iOS works as expected.
