### ISSUE TITLE
Unable to get y position of render items on Flatlist

### ISSUE THREAD

**Issue by jigarkbarot** [facebook/react-native#27169]
Unable to get position of render items on Flatlist

I am trying to get an item's position in flatlist but it always returns "0".sample code are attached bellow.

Here is sample code :
```
<FlatList 
data={["test1","test2","test2"]}
renderItem={({item,index}) => {
return(
<View 
onLayout={(event) => {
  let {x, y, width, height} = event.nativeEvent.layout;
}}
>
<Text>{item}</Text>
</View>
)
}}
 />
```
Can you please help me to get out from this stuff.

**Comment by hramos** [comment]
Please make sure to fill in the issue template if you decide to file a new issue.

**Comment by dressas** [comment]
Is this issue solved? @hramos

**Comment by gibrangul** [comment]
@hramos Is there any update on this issue? 
I'm still getting { x: 0, y: 0 } from event.nativeEvent.layout in flatlist children onLayout methods.

**Comment by andreisuharew** [comment]
Same question. No visible solutions found in two days of surfing the internet.

**Comment by gaurav107** [comment]
Replace `renderItem` with `CellRendererComponent` and it'll work

**Comment by gaurav107** [comment]
use `CellRendererComponent` instead of `renderItem` and you should be able to see x, y getting populated correctly.

**Comment by andreisuharew** [comment]
> use `CellRendererComponent` instead of `renderItem` and you should be able to see x, y getting populated correctly.

thanks for the reply! I tried and it overload my app somehow so i can't actually tap on anything and even toogling inspector doesn't work... seems that there is no practical usage of this method and no documentation at all in internet. Can you please share some info where to find instructions? 
Thanks a lot

**Comment by gaurav107** [comment]
Here's a working example: https://snack.expo.io/@gaurav107/b735d9. Select Android/iOS on the right, and click on the bottom left bar to see the Logs window. I can see the correct (x,y) coordinates getting logged here.

And here's the documentation for [CellRendererComponent](https://reactnative.dev/docs/virtualizedlist#cellrenderercomponent)

The only difference between CellRendererComponent and renderItem props of FlatList is that renderItem wraps the item in a container <View>, whereas CellRendererComponent doesn't. Hence, the (x, y) layout coordinates for CellRendererComponent come relative Flatlist layout, whereas in renderItem, they come relative to parent <View> and hence are (0, 0).

**Comment by ryantafakori** [comment]
<FlatList data={this.state.dataList}
     ...
     renderItem={({item, index}) => this.renderRow(item, index)}
     ...
     console.log("current index is " + index)

   />

**Comment by blazk0** [comment]
The implementation i am using is adding numColumns={2} 
CellRendererComponent is behaving completely different than renderItem as each item is actually an array of 2 elements.

**Comment by Bayramito** [comment]
> The implementation i am using is adding numColumns={2}
> CellRendererComponent is behaving completely different than renderItem as each item is actually an array of 2 elements.

then set your containerStyle like this
`<FlatList  
       contentContainerStyle={{
               flexDirection: "row",
              width: width,
              flexWrap: "wrap",
}}
/>`
