### ISSUE TITLE
React native - InspectorInterfaces.h operation not permitted

### ISSUE THREAD

**Issue by patouxp** [facebook/react-native#27179]
XCode (version 10.3) is throwing this error when trying to build my React Native (version 0.61.2) project:

**error: open .../node_modules/react-native/ReactCommon/jsinspector/InspectorInterfaces.h: Operation not permitted**

I tried the following:
$ git reset --hard origin/master
$ git pull origin master
$ rm -rf node_modules/
$ npm install

also:
$ npm start -- --reset-cache

And of course a Clean Build in Xcode.

Not sure what to try else - any suggestions?

**Comment by progerchai** [comment]
i hava the same question
react-native info follows:
--- 
System:
    OS: macOS 11.0.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 323.13 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v12.13.0/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v12.13.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.1
      System Images: android-27 | Google APIs Intel x86 Atom, android-28 | Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom
      Android NDK: 22.0.7026061
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.3/12C33 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_271 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.0.0 => 16.0.0 
    react-native: ^0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
