### ISSUE TITLE
[Android] Running examples

### ISSUE THREAD

**Issue by omnidan** [facebook/react-native#2718]
https://github.com/facebook/react-native#examples does not explain how to run examples for android, only for iOS

**Comment by dsibiski** [comment]
Right now, you can look here for instructions on running examples: https://github.com/facebook/react-native/blob/master/ReactAndroid/README.md

**Comment by kmagiera** [comment]
@mkonicek we should probably add that to examples section

**Comment by mkonicek** [comment]
Added here: https://github.com/facebook/react-native/blob/master/README.md#running-the-examples-on-android

Although I don't like we require people to have the NDK in order to check out the examples. Leaving this open until I fix that.

**Comment by omnidan** [comment]
Thank you so much @mkonicek - looks good now :+1:

**Comment by kmagiera** [comment]
@mkonicek I though examples build files reference rn version from maven, no?

**Comment by mkonicek** [comment]
@kmagiera The [`settings.gradle`](https://github.com/facebook/react-native/blob/master/settings.gradle) contains `:ReactAndroid`, Gradle parses that and there's a function in `release.gradle` that checks for NDK. Will think of a way to split this up so the people can run the examples independently of `ReactAndroid`'s Gradle files.

**Comment by brentvatne** [comment]
@mkonicek - want to split that out into a separate issue now that the one described in title seems to be resolved?

**Comment by mkonicek** [comment]
Yes let's close this, thanks for the ping. Each example has a README now describing how to run it.
