### ISSUE TITLE
Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports. 

### ISSUE THREAD

**Issue by anwartan** [facebook/react-native#27185]
![screenshot-2019-11-10_23 07 36 854](https://user-images.githubusercontent.com/32921446/68546967-eec28480-040e-11ea-80dd-50a12867abb0.png)

it happens when i put some code
![image](https://user-images.githubusercontent.com/32921446/68547015-4c56d100-040f-11ea-8805-42b0783394e4.png)

this is my info
info Fetching system and libraries information...
System: 
 OS: Windows 10                                                                                                          
CPU: (8) x64 Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz                                                                   Memory: 965.45 MB / 7.85 GB                                                                                           
Binaries:                                                                                                                 
Node: 10.16.3 - C:\Program Files\nodejs\node.EXE                                                                        
Yarn: 1.19.1 - C:\Users\Anwar Tan\AppData\Roaming\npm\yarn.CMD                                                          npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD                                                                          
SDKs:                                                                                                                     
Android SDK:                                                                                                              
API Levels: 25, 28, 29                                                                                                  
Build Tools: 27.0.3, 28.0.3, 29.0.2                                                                                     
System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom                              npmPackages:                                                                                                              
react: 16.9.0 => 16.9.0                                                                                                 
react-native: 0.61.2 => 0.61.2

**Comment by hramos** [comment]
Closing after no followup from the author. Please make sure to fill in the issue template if you decide to file a new issue.
