### ISSUE TITLE
Issue with native_modules.gradle on fresh init, with new install

### ISSUE THREAD

**Issue by hazelf42** [facebook/react-native#27198]
First time user of react native. Been trying for like 7 hours to set this up. Keep running into the problem after running react-native init atest, react-native android-run:

Script 'C:\Users\usernamehere\OneDrive\Desktop\Development\atest\node_modules\@react-native-community\cli-platform-android\native_modules.gradle' line: 182

* What went wrong:
A problem occurred evaluating script.
> Unable to determine the current character, it is not a string, number, array, or object

  The current character read is 'T' with an int value of 84
  Unable to determine the current character, it is not a string, number, array, or object
  line number 1
  index number 0

Looking at the script it occurs on this 
def json = new JsonSlurper().parseText(reactNativeConfigOutput)

Similar to issue #25936 but I tried all the fixes in that thread and none worked.

Not sure how this is happening seeing as I have a fresh install of choco, node, npm, react native etc etc.

**Comment by hazelf42** [comment]
Followed https://github.com/facebook/react-native/issues/26945#issuecomment-549381164 
(basically do a
>yarn add @react-native-community/cli-platform-android)

Maybe going to leave this open since lots of people are having this problem and no fix seems to work for everyone.

**Comment by thymikee** [comment]
Please [update the `@react-native-community/cli`](https://github.com/react-native-community/cli#updating-the-cli) to the latest version, this should hopefully help.
