### ISSUE TITLE
 Unable to resolve module `RCTDeviceEventEmitter` 

### ISSUE THREAD

**Issue by AllenCai1991** [facebook/react-native#27193]
bundling failed: Error: Unable to resolve module `RCTDeviceEventEmitter`

my code is 
import RCTDeviceEventEmitter from "RCTDeviceEventEmitter";

React Native 0.60.5 is ok ,but i upgrade 0.61.0 get error,and i import dismissKeyboard  get the same error. please tell me why,and what should I do. thanks so mush.

React Native version:

    "react-native": "^0.61.0"

**Comment by fcoppola4222** [comment]
Same bug 👍  "dependencies": {
    "@react-native-community/push-notification-ios": "^1.0.2",
    "react": "16.9.0",
    "react-native": "0.61.2",
    "react-native-notifications": "^2.1.5"
  },

**Comment by kiran-mantana** [comment]
Facing the same issue, Any solution

**Comment by kangkfly** [comment]
0.60.6 upgrade to 0.61.5 got the same error, I tried RCTDeviceEventEmitter DeviceEventEmitter instead, and get the same dismissKeyboard error, is RCTDeviceEventEmitter abandoned?I haven't found in the documents and the change log

**Comment by kangkfly** [comment]
0.60.6 upgrade to 0.61.5 got the same error, I tried RCTDeviceEventEmitter DeviceEventEmitter instead, and get the same dismissKeyboard error, is RCTDeviceEventEmitter abandoned?I haven't found in the documents and the change log

**Comment by jtstodola** [comment]
Try `import {RCTDeviceEventEmitter} from 'react-native'`

**Comment by Naturalclar** [comment]
@AllenCai1991 
I was able to work around by importing directry from the file in RN 0.61.5

```js
import RCTDeviceEventEmitter from 'react-native/Libraries/EventEmitter/RCTDeviceEventEmitter';
```

**Comment by conor909** [comment]
Where do you import these suggestions?

**Comment by Naturalclar** [comment]
@conor909 I use them for PushNotificationIOS to provide Push notification to the users :)

```
    RCTDeviceEventEmitter.emit('remoteNotificationReceived', {
      remote: true,
      aps: {
        alert: 'Sample notification',
        badge: '+1',
        sound: 'default',
        category: 'REACT_NATIVE',
        'content-available': 1,
      },
    });
```

**Comment by conor909** [comment]
Ok sorry, its probably unrelated to my issue.
