### ISSUE TITLE
Question: How is css-layout pulled into the project?

### ISSUE THREAD

**Issue by daviskoh** [facebook/react-native#272]
According to [this](https://github.com/facebook/react-native/blob/master/React/Layout/Layout.h#L10), it is pulled in using an **import.sh** script which I can't seem to find.

**Comment by vjeux** [comment]
I never ended up committing this import script. It's just copy and pasted

**Comment by daviskoh** [comment]
I guess there is already an [issue](https://github.com/facebook/react-native/issues/235) opened addressing this...
