### ISSUE TITLE
New Functionality: Force fetch over Wifi when Wifi has no internet and connected to Mobile Data

### ISSUE THREAD

**Issue by thehellmaker** [facebook/react-native#27207]
Similar to 
https://github.com/facebook/react-native/issues/25070
https://stackoverflow.com/questions/55938253/react-native-force-fetch-to-use-wifi

Consider a wifi network without internet and mobile data the react-native fetch() always routes it through mobile data even if i want to access an ip appdress on wifi network. 
For example I have IOT devices on the wifi network and there's no way to force react-native app to communicate with those devices using IP address. Issues like this before have been closed because they looked like questions and not bugs. But because they have been unanswered until now I believe that this feature is missing from react-native and hence opening this as a feature request

React Native version:
System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
    Memory: 2.13 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.12.0 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.13.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 26, 28, 29
      Build Tools: 28.0.3, 29.0.2
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 11.2.1/11B53 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.10.2 => 16.10.2 
    react-native: 0.61.2 => 0.61.2 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
    react-native-iot-wifi: 1.0.0
    react-native-log-ios: 1.0.1

## Steps To Reproduce

1. Have a server running on wifi network
2.Make sure wifi network doesn't have internet
3. connect react-native app to wifi network and also mobile data network.
4. Try to access the ip address of the server on your Wifi network.
5. This fails because the request to the IP address is routed through mobile data network.

**Comment by pjunior94** [comment]
https://www.npmjs.com/package/react-native-android-wifi

This npm package helped me with this issue forcing to fetch data over wifi instead of mobile network. May be useful for you.
