### ISSUE TITLE
ScrollView bug - does not re-render correctly on deleting last index of the array.

### ISSUE THREAD

**Issue by panda0603** [facebook/react-native#27206]
Please excuse my English, explanation may be a little long before I actually talk about the problem.

Currently, I have horizontal scrollview with paging enabled. I have 5 items in result array with each item shown in one screen at a time, and since paging is enabled there are 5 screens in scrollview which you can scroll..

I try to delete an item(or equivalent to screen) by id in result array by clicking a button located at that screen: 

```
_onPressDelete = index => {
    let newArr = this.state.result;
    newArr.splice(index, 1);
    this.setState({result: newArr});
  };
```

Here is a simulation of the problem.

---------------------------Horizontal ScrollView---------------------------------

<img width="650" alt="스크린샷 2019-11-13 오전 10 54 01" src="https://user-images.githubusercontent.com/34116285/68726184-07e05680-0604-11ea-9bd8-91984509e810.png">

For example, if I click the delete button in screen 2, component re-renders and next screen(screen 3) is shown as screen2 disappears. This should be the correct response. This is the next state after delete:

<img width="463" alt="스크린샷 2019-11-13 오전 10 56 19" src="https://user-images.githubusercontent.com/34116285/68726268-42e28a00-0604-11ea-9dfc-2d63263a607a.png">

Deleting any screen from screen1 to screen 3 works without any problem since there is a screen after the deleted screen. However problem occurs when I try to delete the last screen (screen 4). Since screen 4 is last screen and there is no screen 5 to move to, scrollview re-renders with just blank screen. 

This problem only occurs on android, not on ios, so I guess it is android problem only. 
Any fixes to the problem? 

## Steps To Reproduce
1. I have provided a code below to try. It will be much easier to understand if you try the code. 
2. If you press delete button in screen 5, it will show blank as it re-renders. Other screens work perfectly fine. 

```
import React, {Component} from 'react';
import {
  StyleSheet,
  ScrollView,
  View,
  Text,
  Dimensions,
  Button,
} from 'react-native';

class App extends Component {
  state = {
    result: ['screen 1', 'screen 2', 'screen 3', 'screen 4', 'screen 5'],
  };

  _onPressDelete = index => {
    let newArr = this.state.result;
    newArr.splice(index, 1);
    this.setState({result: newArr});
  };

  render() {
    return (
      <View style={styles.container}>
        <ScrollView horizontal pagingEnabled>
          {this.state.result.map((item, index) => {
            return (
              <View style={styles.pageItem} key={item}>
                <Text style={{fontSize: 20}}>{item}</Text>
                <Button
                  title="delete"
                  onPress={() => {
                    this._onPressDelete(index);
                  }}
                />
              </View>
            );
          })}
        </ScrollView>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  pageItem: {
    width: Dimensions.get('window').width,
    height: Dimensions.get('window').height,
    backgroundColor: 'lightgrey',
    justifyContent: 'center',
  },
});

export default App;

```

React Native version:
System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
    Memory: 3.11 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    npm: 6.13.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 26, 28
      Build Tools: 28.0.3, 29.0.2
      System Images: android-28 | Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.4 => 0.61.4 
  npmGlobalPackages:
    react-native-cli: 2.0.1

**Comment by Ashutosh8127** [comment]
Hey I have checked it i think that is not a problem with scrollview when first time its rendered you added a screen width with screen when you delete some value from array you also need to clear the same width from stylesheet

**Comment by panda0603** [comment]
@Ashutosh8127 Thank you for the reply. Any ideas how I should fix it?

**Comment by panda0603** [comment]
> Hey I have checked it i think that is not a problem with scrollview when first time its rendered you added a screen width with screen when you delete some value from array you also need to clear the same width from stylesheet

also, on ios it works fine though. So I guess it is a problem on android?

**Comment by Ashutosh8127** [comment]
Give me some time i will check it
