### ISSUE TITLE
ScrollView onscroll is not executed at rendering

### ISSUE THREAD

**Issue by SergiuTudos** [facebook/react-native#27215]
When I try to render a list of ScollView components I am trying to programmatically scroll using either onContentSizeChange or useEffect nothing happens. According to documentation, it should work.

## React Native version:
System:
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    npm: 6.4.1 - /usr/local/bin/npm
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.2 => 0.61.2 

## Steps To Reproduce
1. Swipe Hero list to left 
2. Swipe up Hero list 

Actual output:
<img width="320" alt="Screen Shot 2019-11-13 at 9 16 35 PM" src="https://user-images.githubusercontent.com/2741419/68796759-16f2f300-065c-11ea-80e9-89a8f0f37509.png">

Expected to happen:
I expect the hero ScrollView to be scrolled and aligned to tiny images
scrollTo in useEffect method should run correctly

 useEffect(() => {
            scrollView.current.scrollTo({ x: state.big}) 
        
      },[state.heroIndex]);

<img width="321" alt="Screen Shot 2019-11-13 at 9 16 42 PM" src="https://user-images.githubusercontent.com/2741419/68796741-0c385e00-065c-11ea-846c-0db70371a383.png">

Snack, code example, screenshot, or link to a repository:
https://snack.expo.io/r1L24RFsB

**Comment by thymikee** [comment]
This is likely an issue with the logic, which is pretty complicated here and I have troubles understanding what's actually wrong. Use the simplest possible version to demonstrate the "bug" (which it likely isn't)

**Comment by SergiuTudos** [comment]
import React, { Component, useReducer, useRef, useEffect } from 'react';
import { View, ScrollView, Animated, Dimensions, StyleSheet, Image, SafeAreaView } from 'react-native';

const { width } = Dimensions.get('window');

const tinyView = {
    width: width / 3,
    height: width / 3,
    margin: 3,
    borderRadius: 10,
    backgroundColor: 'blue',
}

export default App = () => {

    scrollViewTotal = useRef();
    scrollContainer=()=>{
       if(scrollViewTotal.current){
        scrollViewTotal.current.scrollTo({x:150})        
       } 
    }
    buildView=()=>{
        return(
        <View>
        <Image
            style={tinyView}
        />
    </View>)
    }
    useEffect(() => {
        scrollContainer()
     },[]);
    return (
            <SafeAreaView style={{ backgroundColor: 'red' }} >
                <ScrollView horizontal nestedScrollEnabled={false} directionalLockEnabled={true}
                    ref={(scrollViewTotal)}
                    onScrollEndDrag={(e) => { scrollContainer() }}
                >
                                {buildView()}
                                {buildView()}
                                {buildView()}
                                {buildView()}
                                {buildView()}
                                {buildView()}
                                {buildView()}
                                {buildView()}
                                {buildView()}                               
                </ScrollView>
                
            </SafeAreaView>
    );

}
