### ISSUE TITLE
On build for release react-native 0.59.8  on ios

### ISSUE THREAD

**Issue by Warmachine13** [facebook/react-native#27219]
+ echo 'error: File /Users/dev1/Library/Developer/Xcode/DerivedData/ByMedsTabelas-donsteewgfigxiclcwnwuarzofdb/Build/Products/Release-iphonesimulator/ByMedsTabelas.app/main.jsbundle does not exist. This must be a bug with'
error: File /Users/dev1/Library/Devel

React Native version:

## Steps To Reproduce

1. Open Xcode
2. Build fo release

Describe what you expected to happen:

Snack, code example, screenshot, or link to a repository:

export NODE_BINARY=node
../node_modules/react-native/scripts/react-native-xcode.sh ./src/index.js

**Comment by thymikee** [comment]
Can't really tell anything from this repro unfortunately. Please try the latest version if possible.
