### ISSUE TITLE
Could not find iPhone 6 simulator

### ISSUE THREAD

**Issue by Anjing1993** [facebook/react-native#27212]
Code I am executing:
react-native run-ios

Error:

Found Xcode project myrn.xcodeproj
Could not find iPhone 6 simulator

  React Native Environment Info:
    Environment:
        OS: macOS 10.15.1
        Node: 10.0.0
       Yarn: 1.12.3
       npm: 5.6.0
       Watchman: 4.9.0
       Xcode: Xcode 11.2 Build version 11B52
       Android Studio: Not Found

   Packages: (wanted => installed)
        react: 16.3.1 => 16.3.1
        react-native: 0.55.4 => 0.55.4

**Comment by xdavipereira** [comment]
You can specify the device the simulator should run with the --simulator flag, followed by the device name as a string. The default is "iPhone X". If you wish to run your app on an iPhone 5s, run react-native run-ios --simulator="iPhone 5s".

There is more information here: 
https://facebook.github.io/react-native/docs/running-on-simulator-ios

**Comment by Anjing1993** [comment]
> You can specify the device the simulator should run with the --simulator flag, followed by the device name as a string. The default is "iPhone X". If you wish to run your app on an iPhone 5s, run react-native run-ios --simulator="iPhone 5s".
> 
> There is more information here:
> https://facebook.github.io/react-native/docs/running-on-simulator-ios

It is not work for me.
![image](https://user-images.githubusercontent.com/9416309/68780863-d900c980-0671-11ea-906a-b29ad3988918.png)

![image](https://user-images.githubusercontent.com/9416309/68780807-c1c1dc00-0671-11ea-8a32-6171255294c4.png)

**Comment by thymikee** [comment]
This is fixed in the latest CLI. Please [update the `@react-native-community/cli`](https://github.com/react-native-community/cli#updating-the-cli) to the latest version.
