### ISSUE TITLE
Is this a bug?

### ISSUE THREAD

**Issue by a603938361** [facebook/react-native#27211]
React Native Environment Info:
    System:
      OS: macOS 10.14.6
      CPU: (4) x64 Intel(R) Core(TM) i3-8100B CPU @ 3.60GHz
      Memory: 40.11 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.3.1 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    IDEs:
      Xcode: 11.0/11A420a - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.9 => 0.59.9 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-vector-icons: 6.6.0

is my code :
![image](https://user-images.githubusercontent.com/9567891/68750347-af787b80-063a-11ea-8b26-92e2dd1910b3.png)

UI display:
![image](https://user-images.githubusercontent.com/9567891/68750384-bc956a80-063a-11ea-9202-572a9373e200.png)

but, I hope the numbers are followed by words.

help me   ths

**Comment by usmanf8c** [comment]
Hello, can you explain in a little more detail what the issue is?

**Comment by a603938361** [comment]
> Hello, can you explain in a little more detail what the issue is?

hi  The code is very simple, just a text component contains a piece of text, but the UI display is a problem,Just wrap the Chinese in front and automatically wrap it. I hope the numbers are followed by words.
