### ISSUE TITLE
iOS: Font weight of "condensed" font is not obeyed

### ISSUE THREAD

**Issue by simonmitchell** [facebook/react-native#27227]
When using a condensed font for an application, in our case "Acumin Pro Condensed" the font weight and styling is not obeyed when using with React Native.

React Native version:

info 
  React Native Environment Info:
    System:
      OS: macOS 10.15.1
      CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
      Memory: 579.14 MB / 16.00 GB
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 11.10.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    IDEs:
      Xcode: 11.2.1/11B53 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.10 => 0.59.10 
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Steps To Reproduce

1. Install custom font "Acumin Pro Condensed" to React Native project.
2. Try using italic variant of font, using `textStyle: "italic"`. (Or a different weight)
3. Observe regular variant of font is used instead.

Describe what you expected to happen:

The font should be correctly rendered as italic or a different weight.

Snack, code example, screenshot, or link to a repository:

```
<Text style={{
    fontStyle: 'italic',
    fontFamily: 'Acumin Pro Condensed'
}}>Hello World</Text>
```

**Comment by simonmitchell** [comment]
I know why this is happening. On [this line](https://github.com/facebook/react-native/blob/63b534a745329a5d744b6a6b82e315f24184c235/React/Views/RCTFont.mm#L260) `isCondensed` is allocated as `NO`. If font is nil, it is then never set to yes or no, which means that it remains no, and if your font is detected as a "Condensed" font, no match is found.

I don't have time to submit a PR unfortunately but there are a couple of ways I can see to resolve this:

### 1

Change the if statement [here](https://github.com/facebook/react-native/blob/63b534a745329a5d744b6a6b82e315f24184c235/React/Views/RCTFont.mm#L331) to be:
```
if (isItalic == isItalicFont(match) &&
       (isCondensed == isCondensedFont(match) || font == nil))
```

### 2

Add a second check after the for loop containing the above if statement, which doesn't include the `isCondensed` check at all.

### 3

Provide a text style prop from the JavaScript side which is `isCondensed` or similar and check this in the same way italics are checked [here](https://github.com/facebook/react-native/blob/63b534a745329a5d744b6a6b82e315f24184c235/React/Views/RCTFont.mm#L276)

**Comment by simonmitchell** [comment]
@react-native-bot I can see this issue is still present in the latest version, but don't have time to update my whole app to support it!

**Comment by WelkinXie** [comment]
Same problem. If I want to use a font which is ```UIFontDescriptorTraitCondensed``` , the variable ```isCondensed``` will be compared with ```match``` which is just initialized as **NO** while the param ```font``` is passed nil while calling the method:

````
+ (UIFont *)updateFont:(UIFont *)font
            withFamily:(NSString *)family
                  size:(NSNumber *)size
                weight:(NSString *)weight
                 style:(NSString *)style
               variant:(NSArray<NSString *> *)variant
       scaleMultiplier:(CGFloat)scaleMultiplier;
```

**Comment by bitttttten** [comment]
I also ran into this with Acumin Pro Condensed. Just out of curiosity @simonmitchell, do you also have line-height issues with the condensed font too? For me, Acumin Pro Cond is rendering very differently on iOS than it is on Android.

**Comment by simonmitchell** [comment]
Line height issues are generally just a PITA on iOS. You have to go into the font file itself and play around with the line height extender properties unfortunately @bitttttten. I can't seem to attach font files here, but you can find a tutorial on doing this here: https://www.tothenew.com/blog/fix-vertical-position-issue-of-custom-ios-fonts/

**Comment by bitttttten** [comment]
Thanks @simonmitchell ! And yeah tell me about it. On Android it looks perfect, shame it's such an odd experience on iOS. I tried my best to edit these values as close as the article's instructions as possible, although his formula didn't quite work for me so I just had to do it by eye. It took almost the last hour :, )

Did you manage to fix it for Acumin Pro Condensed? If so would you mind comparing / sharing the hhea config? Don't worry if not. I have only done Acumin Pro Condensed Bold and my values are:

```
<hheaTable
	versionMajor="1"
	versionMinor="0"
	ascender="760"
	descender="0"
	lineGap="0"
	advanceWidthMax="1032"
	minLeftSideBearing="-177"
	minRightSideBearing="-191"
	xMaxExtent="1000"
	caretSlopeRise="1"
	caretSlopeRun="0"
	caretOffset="0"
	metricDataFormat="0"
	numberOfHMetrics="792"
/>
```
