### ISSUE TITLE
Failed to run a react-native app in iOS 11 - 13.2.2

### ISSUE THREAD

**Issue by theo82** [facebook/react-native#27239]
So I have been running my app on an Android device and works fine as shown below.

![Screenshot_1573913201](https://user-images.githubusercontent.com/7755518/68994388-168c6f00-088b-11ea-818b-9068560af4be.png)

However, I can't test it on an iOS emulator. I load the emulator by typing

`open -a simulator
`
It opens up. Then I type `npm run ios` and get this back.

```
`error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening confusion.xcodeproj

** BUILD FAILED **


The following build commands failed:
        CompileC /Users/theodosiostziomakas/Desktop/React-Native-Coursera/ios/build/confusion/Build/Intermediates.noindex/confusion.build/Debug-iphonesimulator/confusion.build/Objects-normal/x86_64/main.o /Users/theodosiostziomakas/Desktop/React-Native-Coursera/ios/confusion/main.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
. Run CLI with --verbose flag for more details.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ ios: `react-native run-ios`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ ios script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/theodosiostziomakas/.npm/_logs/2019-11-16T12_59_45_224Z-debug.log
Theodosioss-MacBook-Pro:React-Native-Coursera theodosiostziomakas$ npm run android

> @ android /Users/theodosiostziomakas/Desktop/React-Native-Coursera
> react-native run-android`

```
My package.json file is this

`{
  "scripts": {
    "start": "react-native start",
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "web": "expo start --web",
    "postinstall": "jetify"
  },
  "dependencies": {
    "expo": "^35.0.0",
    "react": "16.8.3",
    "react-dom": "16.8.3",
    "react-native": "0.59.10",
    "react-native-elements": "^1.0.0-beta8",
    "react-native-gesture-handler": "~1.4.1",
    "react-native-reanimated": "~1.3.0",
    "react-native-screens": "1.0.0-alpha.23",
    "react-native-unimodules": "0.6.0",
    "react-native-web": "^0.11.7"
  },
  "devDependencies": {
    "@babel/core": "^7.6.0",
    "babel-jest": "24.9.0",
    "babel-preset-expo": "^7.1.0",
    "jest": "24.9.0",
    "jetifier": "^1.6.4",
    "metro-react-native-babel-preset": "0.56.0",
    "react-test-renderer": "16.9.0"
  },
  "private": true
}
`
Is there any way to fix this? Thanks.

**Comment by hramos** [comment]
Closing after several months without followup from the author. Please make sure to fill in the issue template if you decide to file a new issue.
