### ISSUE TITLE
Nested Flatlist in ScrollView doesn't work with TextInput focused

### ISSUE THREAD

**Issue by buchereli** [facebook/react-native#27244]
If you nest a `FlatList` in a `ScrollView` then focus a `TextInput` you can only scroll the outer `ScrollView`.

If the `TextInput` is not focused the nested `FlatList` can be scrolled.

Here is a very simple snack showing the bug: https://snack.expo.io/Byvj5DCoB

**React Native version: v0.61.2**
System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-3820QM CPU @ 2.70GHz
    Memory: 368.29 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.14.0 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 24, 26, 27, 28
      Build Tools: 23.0.1, 26.0.2, 27.0.3, 28.0.3, 29.0.1
      System Images: android-16 | Intel x86 Atom, android-21 | Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 11.2/11B52 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.2 => 0.61.2
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7

## Steps To Reproduce
1. Make a `ScrollView`
2. Add a `FlatList` to the `ScrollView` which has more content than it's fixed height
3. Add a `TextInput` to the `ScrollView`
4. Focus the `TextInput`
5. Try to scroll the `FlatList`

**Here's the code to repro:**
```
<ScrollView>
    <TextInput />
    <FlatList
         data={data}
         style={{height: 45}}
         renderItem={({ item }) => <Text>{item}</Text>}
     />
</ScrollView>
```

**Describe what you expected to happen:**
I expect when you focus the `TextInput` that the `FlatList` can be scrolled this is necessary for creating a good autocomplete UI that sometime must be nested in a scrollview.

**Snack, code example, screenshot, or link to a repository:**
https://snack.expo.io/Byvj5DCoB

`TextInput` seems to really mess up touch events. Does anyone know of a better alternative to `TextInput`?

**Potential Fixes**
1. Disable scroll view scroll using `scrollEnabled={false}`. Unfortunately this does not work. It just makes the scrollview also not respond to scroll gestures.
2. Use an animated view and handle scrolling yourself. I haven't tested this but it might work but seems like a terrible solution.
3. Using an `absolute` layout to render the `FlatList` in the correct location on the screen does work (the list still can not be a child of the `ScrollView`) but is a bit wonky depending on what you're trying to do.

**Comment by edferreira** [comment]
As far as I know you shouldn't be nesting ScrollViews and FlatLists like that (at least not since the 0.61 version). What I do to work around this issue is to put your my components inside the FlatList header component. 

I have made some changes to your example, hope it's helpful 
https://snack.expo.io/B1nkQOlhB

**Comment by buchereli** [comment]
@edferreira 

Yeah I'm seeing a warning now about nesting a virtualized list inside a plain scroll view. I'm not sure how you would create a text input with suggestions without doing this though (assuming the text input must be inside a scroll view).

Your example doesn't work. It has the same issue. Focus the text input and you can't scroll the flatlist only the outer scroll view.

**Comment by edferreira** [comment]
Sorry, I don't understand the problem.
The example I've made doesn't have a ScrollView, only a FlatList with your input as a sticky header. This way you only have a FlatList to scroll and your TextInput will always be shown on top of the screen

**Comment by buchereli** [comment]
@edferreira The snack you made does have a `ScrollView` maybe you left it there by mistake?

The problem is that I want to make a `TextInput` that has a dropdown of suggestions. The dropdown has a defined size and should be scrollable.

This works fine as long as this component is not placed inside a `ScrollView`. The suggestions need to scroll independent of the outer `ScrollView`.

**Comment by edferreira** [comment]
maybe this [answer](https://github.com/facebook/react-native/issues/1966#issuecomment-285130701) can help you

**Comment by buchereli** [comment]
@edferreira Thanks but as I mentioned in my original report `scrollEnabled` doesn't have any effect on the issue. Setting the outer scrollview to scrollEnabled to false just make neither the scroll view or the listview scrollable when the text input is focused.
