### ISSUE TITLE
stickyHeaderIndices cannot be sticky for several child views at the same time

### ISSUE THREAD

**Issue by PonorogoCreativeIT** [facebook/react-native#27246]
i want to ask about `stickyHeaderIndices` on `ScrollView`, on RN version 0.59 can sticky some child view at the same time, but when updating the latest version of RN 0.61 only can sticky one by one per child. So if user scrolled to last child view, only last index can be sticky

React Native version: 
```
System:
    OS: Linux 5.0 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-3632QM CPU @ 2.20GHz
    Memory: 228.95 MB / 15.53 GB
    Shell: 5.4.2 - /usr/bin/zsh
  Binaries:
    Node: 10.16.3 - /usr/bin/node
    Yarn: 1.17.3 - /usr/bin/yarn
    npm: 6.12.1 - /usr/bin/npm
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: ^0.61.4 => 0.61.4 
  npmGlobalPackages:
    react-native-asset: 2.0.0
    react-native-cli: 2.0.1
    react-native-create-library: 3.1.2
    react-native-git-upgrade: 0.2.7

```

## Steps To Reproduce

1. Create more than 1 View Child inside `ScrollView`
2. Set index view on `stickyHeaderIndices`

## Expected:
all child views that are set stickyHeaderIndices should be sticky. not only can sticky one by one per child.

### Snack:
https://snack.expo.io/H1y-ehCor

**Comment by edferreira** [comment]
I believe that's how it is supposed to work. It will have only one sticky component at time

**Comment by naveedulaziz** [comment]
Hey! If you just consider it. You will find out that the content is sticking just fine. But the content is scrolling over it instead of scrolling under it. As I'm working stickyheader, I came across the same behaviour. It only bugs in Android.

**Comment by naveedulaziz** [comment]
So now the question is did you find any solution?

**Comment by ovlis** [comment]
Any update on this?
