### ISSUE TITLE
PermissionsAndroid always return never_ask_again 

### ISSUE THREAD

**Issue by ironhide0396** [facebook/react-native#27240]
Whenever requesting for any permission using the PermissionsAndroid.reques() method, the granted state always is never_ask_again . 
No prompt for permission request is shown or displayed.
Same issue is described in multiple issues , but no fix has been provided.

React Native version:0.59.10

React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (4) x64 Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
      Memory: 2.47 GB / 7.92 GB
    Binaries:
      npm: 6.9.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.3.0.0 AI-182.5107.16.33.5314842

## Steps To Reproduce

1.Create a new react-native app using command line 
2.Ask for any permission as mentioned in react native official docs at [https://facebook.github.io/react-native/docs/permissionsandroid](url)
3.The value for granted always returns never_ask_again
 
Expected : 
Prompt to be shown asking for a permission.
 
 ` var granted = await PermissionsAndroid.request(
                PermissionsAndroid.PERMISSIONS.READ_SMS,
                {
                    title: "Auto Verification OTP",
                    message: "need access to read sms, to verify OTP",
                    buttonPositive: "Button Positive"
                }
            );
            if (granted === PermissionsAndroid.RESULTS.GRANTED) {
                granted = await PermissionsAndroid.request(
                    PermissionsAndroid.PERMISSIONS.RECEIVE_SMS,
                    {
                        title: "Receive SMS",
                        message: "Need access to receive sms, to verify OTP",
                        buttonPositive: "Button Positive"
                    }
                );
                if (granted === PermissionsAndroid.RESULTS.GRANTED) {
                    showMessage("RECEIVE_SMS permissions granted");
                } else {
                    showMessage("RECEIVE_SMS permissions denied");
                }
            } else {
                showMessage("sms read permissions denied");
            }`
 

Always shows the message "sms read permission denied"

**Comment by marcosilvestroni** [comment]
Same here with react native 0.60.1 with  Android 8 (Oreo) not with the 9 and 10 version

**Comment by ironhide0396** [comment]
Closing this issue as this was solved by the workaround mentioned in [#13097
](https://github.com/facebook/react-native/issues/13097)
Simply making target and compile sdk version as same, the above code started working without a change
