### ISSUE TITLE
Linking.getInitialUrl always returning null in Android

### ISSUE THREAD

**Issue by shubham234** [facebook/react-native#27242]
I'm new to React Native world and is implementing OAuth on my App using AWS Amplify. I'm able to successfully login by redirecting to a link in the browser and is able to Deep Link back to my App but on doing Linking.getInitialUrl it is always returning null. I've set android:launchMode = "singleTask". The same code returns OAuth redirectUri "example://test?code=[Code]&state=[State]" when ran on IOS.

## Steps To Reproduce

1. Add a Deep Link to you App.
2. In the Deep Linked screen's componentDidMount add below code. It always print null in any case.

        Linking.getInitialURL().then((url) => {

          if (url) {

            console.warn('Initial url is: ' + url);

          } else {

            console.warn('Initial url is null');

          }

        }).catch(err => console.warn('An error occurred', err));`

## Describe what you expected to happen:

1. Linking.getInitialUrl() should return the link through which the App was triggered .

## What I have tried till now:
1. I used AppState change event and printed Linking.getInitialUrl() output in its callback. Still it printed null.
2. Turned off the debugger as mentioned [here](https://stackoverflow.com/questions/55482111/why-is-linking-getinitialurl-always-returning-null).
3. I searched for this issue and found many links indicating the same issue. https://github.com/facebook/react-native/issues/25675, https://github.com/facebook/react-native/issues/26565 but none of them have a concrete answer.

## React Native version:
* react: "16.3.1"
* react-native: "0.59.8"
* Android Version: "8.0.0"
* Android API Level : "26"

**Comment by shubham234** [comment]
Adding below lines in Android Activity class solved the issue for me:

    @Override
    protected void onNewIntent(final Intent intent) {
        super.onNewIntent(intent);
        setIntent(intent);
    }

There was nothing wrong with Linking Library.

**Comment by gron01** [comment]
I have same problem please give to full code
