### ISSUE TITLE
selectTextOnFocus does not work with multiline text inputs iOS

### ISSUE THREAD

**Issue by TheSavior** [facebook/react-native#27253]
A multiline textinput with `selectTextOnFocus={true}` selects the text on focus, and then instantly unselects the text. 

For an example repro, this code from RNTester will demonstrate the issue:

```
<TextInput
  placeholder="text is selected on focus"
  defaultValue="text is selected on focus"
  selectTextOnFocus={true}
  multiline={true}
/>
```

You can find this in the TextInput example page in RNTester on iOS as well.
![textinputfocus](https://user-images.githubusercontent.com/249164/69100225-8d537480-0a11-11ea-9f44-2187c4649ab7.gif)

React Native version:
0.61.4

**Comment by safaiyeh** [comment]
Backlog

**Comment by kelsyvghn** [comment]
is this a good issue to get started on? I'd love to take a stab at it.

**Comment by TheSavior** [comment]
Hi @kelsyvghn, yeah, I think this is a good first issue for someone wanting to get familiar with React Native internals. It looks like something is blurring or taking focus from the React Native text input control. This will probably require setting some breakpoints in the Objc code and trying to figure out what is happening.

I think this is where it is selecting all of the text, but I'm not sure what is taking the focus away.
https://github.com/facebook/react-native/blob/c8ed2dbbb287deed05a8782fb8665c1edf45bbac/Libraries/Text/TextInput/RCTBaseTextInputView.m#L330-L332

**Comment by kelsyvghn** [comment]
Awesome, I’d love to take it.

**Comment by chirag-singhal** [comment]
@kelsyvghn are you working on this?

**Comment by kelsyvghn** [comment]
I started it but unfortunately I’ve been too busy at work to work on it.

>

**Comment by chirag-singhal** [comment]
@kelsyvghn could i take on this, if you don't mind.

**Comment by kelsyvghn** [comment]
Yes go ahead. Thank you 

>

**Comment by thehanimo** [comment]
Is this issue fixed? Unable to reproduce it on the latest commit (c03b7dd).

**Comment by tobiasr** [comment]
I'm also unable to reproduce this on [6d3dcc7](https://github.com/facebook/react-native/commit/6d3dcc72c58758c8818b75720b8a37a730e8d485).

**Comment by TheSavior** [comment]
Thanks for the comments all! I'm glad this is resolved, I'll close it out!
