### ISSUE TITLE
Image resizeMode='contain' distorts some images on Android devices and emulators

### ISSUE THREAD

**Issue by shah95rukh** [facebook/react-native#27256]
The resizeMode='contain' in the React Native Image component distorts some images on Android devices and emulators. For most images, it creates a distorted line in the PNG image background. I've tried many different images, also tried resizing them, but nothing fixes the distorted coloured line. 
Note: All those images look fine on iOS.

**React Native version: v0.61.4**
System:
    OS: macOS 10.15.1
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 1.43 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.12.0 - /usr/local/bin/node
    npm: 6.11.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 26.0.3, 27.0.3, 28.0.2, 28.0.3, 29.0.2
      System Images: android-26 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom_64, android-26 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.4 => 0.61.4

## Steps To Reproduce

1. Created a grid-like nested `View`
2. Add `Image` component with height and width undefined
3. Add some png images to an image folder
4. run the app in Android and iOS to compare

**Here is the small snippet of code:**

```
<View style={{ height: 600, flexDirection: 'row', backgroundColor: 'transparent', marginVertical: 10 }}>
        <View style={{
          flex: 1, flexDirection: 'column', marginHorizontal: 20,
          borderWidth: 2, borderColor: 'lightgray', borderRadius: 10
        }}>
          <Image
            style={{
              flex: 1, height: '50%', width: '100%', borderColor: 'black', borderWidth: 1,
            }}
            source={require('./Images/pizza3.png')}
            resizeMode='contain'>
          </Image>
          <Text style={{ fontSize: 20, marginVertical: 5, marginHorizontal: 10 }}>Pizza 1</Text>
          <Text style={{ fontSize: 17, marginTop: 15, marginBottom: 10, marginHorizontal: 10 }}>$10.99</Text>
        </View>
        <View style={{
          flex: 1, flexDirection: 'column', backgroundColor: 'transparent',
          borderWidth: 2, borderColor: 'lightgray', borderRadius: 10, marginRight: 20,
        }}>
          <Image
            style={{
              flex: 1, height: undefined, width: undefined, borderColor: 'black', borderWidth: 1
            }}
            source={require('./Images/pizza1copy.png')}
            resizeMode='contain'>
          </Image>
          <Text style={{ fontSize: 20, marginVertical: 5, marginHorizontal: 10 }}>Pizza 2</Text>
          <Text style={{ fontSize: 17, marginTop: 15, marginBottom: 10, marginHorizontal: 10 }}>$10.99</Text>
        </View>
      </View>
```

Describe what you expected to happen:
I expect images to not get distorted on Android devices like iOS.

**Screenshots:**

Amazon Fire Tablet 8th Gen.
<img width="383" alt="Screen Shot 2019-11-15 at 8 46 34 PM" src="https://user-images.githubusercontent.com/12913466/69108139-c73c6f00-0a41-11ea-971c-46046e933585.png">

Android Nexus 10 API 28 emulator
<img width="411" alt="Screen Shot 2019-11-15 at 8 39 09 PM" src="https://user-images.githubusercontent.com/12913466/69108163-d4f1f480-0a41-11ea-9992-f22b42fcaf67.png">

iPad Pro (11-inch) simulator
<img width="423" alt="Screen Shot 2019-11-15 at 8 40 05 PM" src="https://user-images.githubusercontent.com/12913466/69108171-dfac8980-0a41-11ea-83f5-e579889d27ab.png">

**Note:**
Dimensions for the first image, i.e., pizza3.png are 2422 x 2422
Dimensions for the second image, i.e., pizza1copy.png are 1000 x 1000

I downloaded the png images for testing from the following website.
http://pngimg.com/imgs/food/pizza/

**Comment by shekharskamble** [comment]
I have the same issue
