### ISSUE TITLE
React-native run-android app not working

### ISSUE THREAD

**Issue by DucSilva** [facebook/react-native#27257]
Hi all! I got an error when i run react-native run-android that it's not working! I run adb logcat *:E, i recieved message error: Didn't find class "android.support.v4.app.CoreComponentFactory" on path: DexPathList[[],nativeLibraryDirectories=[/system/priv-app/GoogleSdkSetup/lib/x86, /system/lib, /system/lib]]
Does anyone help me fix this bug! Thank very so much!

**Comment by tuantvk** [comment]
The root cause is related to androidx, google play service... try upgrade project to androidx.
This problem seems to be triggered by the version of react-native-device-info, ...?
