### ISSUE TITLE
Weird behaviour of animated interpolation with absolutely positioned views

### ISSUE THREAD

**Issue by pernifin** [facebook/react-native#27252]
I'm trying to build a sliding panel, but stumbled upon unexpected behaviour of interpolation. It might be I simply do something in a wrong way.

I'm expecting to shift block down using `translateY` by the height of the block itself. To achieve this I use `onLayout` to retrieve correct block's height, then use it as a value for `Animated.Value` and a boundary in interpolation.

The reason I need interpolation at all is that its purpose is to clamp input range as you see I commented that line. On the first render interpolation range is `[0, 0]`, but after `onLayout` I expect it to have correct boundaries, but they are not updated. As result block is not shifted down:

![image](https://user-images.githubusercontent.com/1961407/69051463-1320f100-0a0d-11ea-8702-24d8fba28843.png)

But if you do any of the following:
1. Remove `position: 'absoulte'` from the view
2. Remove interpolation — use `Animated.Value` directly
3. Set initial boundaries of interpolation other than `[0, 0]`, e.g. `[-1, 0]`

the block is shifted as expected:
![image](https://user-images.githubusercontent.com/1961407/69051728-de616980-0a0d-11ea-8dc0-e219e56575bc.png)

So could you help me figure this thing out?

### React Native version: 0.61.2

System:
    OS: macOS 10.15.1
    CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
    Memory: 289.34 MB / 16.00 GB
    Shell: 5.0.11 - /usr/local/bin/bash
Binaries:
    Node: 12.10.0 - /usr/local/bin/node
    npm: 6.11.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
SDKs:
    iOS SDK:
      Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
npmPackages:
    react: ^16.9.0 => 16.9.0 
    react-native: ^0.61.0 => 0.61.2 
npmGlobalPackages:
    react-native-cli: 2.0.1

### Steps To Reproduce
1. Just run attached gist with component as a root

### Describe what you expected to happen:
The interpolation should work as expected.

### Component gist:

https://gist.github.com/pernifin/3f3cd35ac4d06416d58cd12f87a876f6

**Comment by edferreira** [comment]
You haven't called an animate function, so I added this one `Animated.timing(this.state.shift, {toValue: 1, duration: 300}).start()`
Also, for some reason your `getViewTranslation` isn't working here, but I am not sure why

I have made some changes to your code. It's working here, you can take a look.

```
import React, { Component } from 'react';
import { Animated, StyleSheet } from 'react-native';

type State = {
  height: number;
  shift: Animated.Value;
}

export default class Playground extends Component<{}, State> {
  constructor(props) {
    super(props);

    this.state = {
      height: 0,
      shift: new Animated.Value(0)
    };
  }

  onLayout = ({ nativeEvent }) => {
    const height = nativeEvent.layout.height;

    setTimeout(()=>(
      Animated.timing(this.state.shift, {toValue: 1, duration: 300}).start()
    ), 300); 
    this.setState({ height });
  }

  render() {
    return (
      <Animated.View onLayout={this.onLayout}
        style={[
          styles.container,
          { transform: [{ translateY: this.state.shift.interpolate({
            inputRange: [0, 1],
            outputRange: [0, this.state.height]
          })}]}
        ]}
      >
      </Animated.View>
    )
  }
}

const styles = StyleSheet.create({
  container: {
    position: 'absolute',
    width: '100%',
    height: 100,
    backgroundColor: 'red'
  }
});
```

**Comment by pernifin** [comment]
Shouldn't call to `setValue` directly influence `Animated.Value` right away? Why do we have to call animation function? The thing is that I need to set its value instantly, because at the time the screen is rendered I should display the block in one of two states.
