### ISSUE TITLE
Change datepicker Cancel/OK buttons text (Android)?

### ISSUE THREAD

**Issue by dehghani-mehdi** [facebook/react-native#27265]
React Native version: latest

## Steps To Reproduce

1. Create new app
2. Try using Datepicker in Android
3. Try to change cancel/ok button's text

Describe what you expected to happen:
I could not find any related documentation about it, is there any way to do it?

Snack, code example, screenshot, or link to a repository:

**Comment by dehghani-mehdi** [comment]
I'm still waiting for answer and solution stale (be a good bot and remove the label)

**Comment by safaiyeh** [comment]
Hi @dehghani-mehdi datetime picker has been moved to https://github.com/react-native-community/react-native-datetimepicker, try out that module and see if the issue persists.

Otherwise, open the issue there.

cc @TheSavior to close
