### ISSUE TITLE
missing global.nativePerformanceNow

### ISSUE THREAD

**Issue by parth3724** [facebook/react-native#27274]
In React native android app, using react native version 0.59.8, global.nativePerformanceNow is not defined.

React Native version: 0.59.8

## Steps To Reproduce

1. Try to get time value in any js file using global.nativePerformanceNow()

Describe what you expected to happen:
As it was described in RN version 55.3 AndroidJSCFactory.cpp,
  // Since SystemClock.uptimeMillis() is commonly used for performance measurement in Java
  // and uptimeMillis() internally uses clock_gettime(CLOCK_MONOTONIC),
  // we use the same API here.
  // We need that to make sure we use the same time system on both JS and Java sides.

We cannot use systrace in Android (since only stub is open sourced). We invested so much in building tooling to measure performance, and now when we change the version, such basic api vanishes.

https://github.com/facebook/react-native/blob/0.53-stable/ReactAndroid/src/main/jni/react/jni/AndroidJSCFactory.cpp

**Comment by emilisb** [comment]
I have encountered very same issue. After Profiler API (https://reactjs.org/docs/profiler.html) was released, this feature is even more important than before. Currently it is impossible to get precise execution time without the real performance.now() (and without using a remote debugger). Without performanceNow we are forced to use local date, which is not good enough. 

It seems like this feature was removed during transition from JSC to JSI and it was never reimplemented.

I found commits that removed this feature:

Android: https://github.com/facebook/react-native/commit/7ffb406517e70a2ac299d20020d3798a5b7dc612#diff-c2a333229249aaff833b2a50be32a489

iOS: https://github.com/facebook/react-native/commit/816d41718998868f276d83b0c21e17d11ad392a2

I don't see any reason to not reimplement it again. 

In addition to that, could we implement a performance polyfill with at least most popular functions? Performance docs: https://developer.mozilla.org/en-US/docs/Web/API/Performance
