### ISSUE TITLE
Fetch Fails on Android, works on IOS

### ISSUE THREAD

**Issue by eyalabadi98** [facebook/react-native#27272]
React Native version:
```
System:
    OS: macOS 10.15.1
    CPU: (4) x64 Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz
    Memory: 47.02 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.11.0 - /usr/local/bin/node
    Yarn: 1.10.1 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.7.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5977832
    Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.4 => 0.60.4 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
    react-native-svg: 6.0.0-rc1
```

## Steps To Reproduce
1. Create API with AWS Lambda and API Gateway
2. Call the following code:
 ```
var headers = {
    'Authorization': 'Bearer ${Cognito.signInUserSession.idToken.jwtToken}'
  }
  console.log("Headers" , headers);
  const qs = `{users(username: "aUserName") {username, leagues {name, start, currentTime, ready, creator, totalPlayers, joinedPlayers, creatorInfo {fullName}, draftPicks{user{username, fullName} order,numTickets}}} }`

  const URL = 'https://someID.execute-api.us-east-1.amazonaws.com/Prod/graphql?query=${qs}';
  return (
    fetch(URL, {
      method: 'GET',
      headers,
    })
```
3. Use IOS and Postman, it works fine, on Android I get status 400

Describe what you expected to happen:

I expect the code to work and get 200 response

![image](https://user-images.githubusercontent.com/3536706/69207016-7483b580-0b1c-11ea-867d-0dd5232ccdf8.png)

IOS screenshot that shows it works:
![image](https://user-images.githubusercontent.com/3536706/69207194-01c70a00-0b1d-11ea-9a56-8264ed3173de.png)

**Comment by tuantvk** [comment]
@eyalabadi98 check issues [Fetch not working on Android 9 API 28](https://github.com/facebook/react-native/issues/24627#issuecomment-492159371)

**Comment by eyalabadi98** [comment]
@tuantvk Unfortunately it's a different issue. I am using https. I tried it and i still get 400 error.

Thanks for the link tho

**Comment by glCoder8** [comment]
@eyalabadi98 please check backend response status.

If backend is sending contents using 205 status - `205 RESET CONTENT`
Android system recognize it as an error - `HTTP 205 had non-zero Content-Length: 25`.

You can check the status code on postman.
So, in this case, the error should be fixed on backend.

**Comment by vardaro** [comment]
Did you find a solution? I'm facing the same error on latest version of RN. Using Android 9, API 28. It fails on Android but works on iOS.

**Comment by quietbits** [comment]
I'm getting the same error on RN version 0.61.5. The exact same call with the same params works on iOS (both device and simulator) and Postman on the web but fails on anything Android (device, emulators with different OS versions). It's an HTTPS call.
It's also interesting that it works when RN debugger is enabled.

**Comment by hramos** [comment]
The different behavior in Android, as well as when the debugger is enabled, tells me this is related to the JavaScript VM. Since you’re seeing different behavior with fetch across engines, I recommend importing and using a different networking package to ensure consistent behavior regardless of which JS engine your code is running on.
