### ISSUE TITLE
Configure react native android jscodelocation

### ISSUE THREAD

**Issue by Matthew-C** [facebook/react-native#2727]
How am I suppose to configure jscodelocation for react native android in real product? Is it doable?

**Comment by ide** [comment]
During development you can set a key in SharedPreferences called "debug_http_host" to configure the host of the packager server.

```java
SharedPreferences preferences =
   PreferenceManager.getDefaultSharedPreferences(getApplicationContext());
preferences.edit().putString("debug_http_host", "localhost").apply();
```

Currently you can curl/wget your JS from the packager, include it with your APK, and tell the ReactInstanceManager to load the JS from an asset (see `setBundleAssetName`). That is the extent to which you can customize things for now.

**Comment by Matthew-C** [comment]
Thanks, will try.
