### ISSUE TITLE
TouchableWithoutFeedback onLongPress wont work some android devices

### ISSUE THREAD

**Issue by AlisanCakir** [facebook/react-native#27276]
TouchableWithoutFeedback onLongPress props wont work some android devices, Ios is work but some android device wont work onLongPress prop, my TouchableWithoutFeedback is

```
    <TouchableWithoutFeedback
      disabled={this.props.disabled}
      onLongPress={this.props.onLongPress}
      delayLongPress={2000}
      onPress={this.props.onPress}
      onPressIn={this.pressIn.bind(this)}
      onPressOut={this.pressOut.bind(this)}>
        <Animated.View style={[styles.view, this.state.style, {backgroundColor: backgroundColor}]}>
            {this.props.leftImage != undefined ? this._getImage('leftImage') : null }
            <Text
              numberOfLines={1}
              style={[styles.text, this.props.styleText]}>
                {this.props.text}
            </Text>
            {this.props.rightImage != undefined ? this._getImage('rightImage') : null }
            {this.props.children}
        </Animated.View>
    </TouchableWithoutFeedback>
```
React Native version: 59.1

**Comment by Kida007** [comment]
Hey @AlisanCakir ,

This Particular Issue was fixed in version 0.59.4. so upgrading react-native would solve it .

**Comment by AlisanCakir** [comment]
Thanks for response @Kida007, upgrade is complicated sitituation, cause another problem can I solve without upgrading

**Comment by Kida007** [comment]
You can follow this PR ( https://github.com/facebook/react-native/commit/59e50237bff9521d2b78d7576abf4e23d844ac1b ).

Although Ideal Situation would be upgrading .

**Comment by AlisanCakir** [comment]
Thanks again  @Kida007 I will try
