### ISSUE TITLE
Unhandled JS Exception: Unexpected token '?'  no stack

### ISSUE THREAD

**Issue by williamgoodhew** [facebook/react-native#27279]
I am trying to run the app in the simulator using react-native run-ios.

There are very basic error reports. All I am getting in the simulator is 

Unhandled JS Exception: Unexpected token '?'

no stack

React Native version:

 React Native Environment Info:
    System:
      OS: macOS 10.14.6
      CPU: (4) x64 Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz
      Memory: 1.36 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 9.6.1 - /usr/local/bin/node
      npm: 5.6.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
      Android SDK:
        API Levels: 23, 26, 27, 28
        Build Tools: 23.0.1, 26.0.2, 26.0.3, 27.0.3
        System Images: android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64
    IDEs:
      Android Studio: 3.0 AI-171.4443003
      Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.8.3 => 16.8.3
      react-native: ^0.59.9 => 0.59.9
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-router-flux: 4.0.0-beta.31
      react-native-run-android: 0.0.1

**Comment by yalamandarao** [comment]
I'm facing same issue.

node : v13.7.0
yarn : 1.19.0
"npm": "^6.3.0",
"react": "16.8.3",
"react-native": "https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz",
"react-native-drawer": "^2.5.0",

Xcode : Version 11.3.1 (11C504) iOS 13.3
![Simulator Screen Shot - iPad Pro (11-inch) - 2020-02-03 at 10 38 09](https://user-images.githubusercontent.com/2649017/73621636-c941c180-4671-11ea-90b8-f33a7f1da8d5.png)

**Comment by anasbalkhadir** [comment]
Hy, I got this issue when running on android. 
node : v13.10.0
"npm": "7.6.0",
"react": "^17.0.1",
"react-native": "0.63.3",
 "react-native-web": "^0.14.4",

It works fine at the beginning, maybe the issue was produced by some files config. 
Do you have any tracks on treating this?
