### ISSUE TITLE
react-native run-android 没有运行起来 

### ISSUE THREAD

**Issue by jinyuqiqi** [facebook/react-native#27285]
![image](https://user-images.githubusercontent.com/26156103/69304871-317d2b80-0c5d-11ea-9766-7e2a77c997de.png)

这是运行命令后的信息 
Android studio安装了 Android sdk安装了 夜神安卓模拟器也安装了
求各位大佬帮忙解决

**Comment by tuantvk** [comment]
@jinyuqiqi i think no connected devices.
