### ISSUE TITLE
Live Streaming is not available in React Native

### ISSUE THREAD

**Issue by awais-devden** [facebook/react-native#27289]
Live Streaming is not available in React Native, i want to access each frame of camera in real time but none of the existing package provide this functionality i tried this thing with react native camera package but failed to do so, kindly help if anyone know anything about it,
Regards.

**Comment by dulmandakh** [comment]
It looks like a feature request, and I'm afraid that this won't make into RN core because of Lean Core https://github.com/facebook/react-native/issues/23313. Please feel free to use third-party modules, or develop your own module. Thanks
