### ISSUE TITLE
I am getting an error after upgrading the react-native to the latest version(Could not find the following native modules)

### ISSUE THREAD

**Issue by nihp** [facebook/react-native#27298]
I done the following to update all npm and react-ative latest version.

```
For npm, I ran npm update

To update the react-native, I have changed the version in package.json and ran npm install. It updated the react-native version

```
After this, I have run react-native run-ios it shows all my packages are manually linked and you need to unlink all packages.

Also, can anyone clarify the react-native-config.js file is mandatory for this after updating to the latest react-native.

Always I open the app.Xcodeproj but the below shows I need to open app.xcworkspace. Can anyone clarify this?
```


warn The following packages use deprecated "rnpm" config that will stop working from next release:
  - react-native-fetch-blob: https://github.com/wkh237/react-native-fetch-blob#readme
  - react-native-orientation: https://github.com/yamill/react-native-orientation#readme
  - rn-fetch-blob: https://github.com/joltup/rn-fetch-blob#readme
Please notify their maintainers about it. You can find more details at https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide.
error Could not find the following native modules: BugsnagReactNative, react-native-camera, react-native-cookies, react-native-fast-image, react-native-fetch-blob, RNFS, RNGestureHandler, RNImageCropPicker, react-native-image-picker, RNImageRotate, BVLinearGradient, react-native-orientation, RNShare, RNSVG, RNVectorIcons, RNViewShot, react-native-webview, rn-fetch-blob. Did you forget to run "pod install" ?
info Found Xcode workspace "Fashion.xcworkspace"
```

**Comment by nihp** [comment]
react-native info

 ```
react-native info
warn The following packages use deprecated "rnpm" config that will stop working from next release:
  - react-native-fetch-blob: https://github.com/wkh237/react-native-fetch-blob#readme
  - react-native-orientation: https://github.com/yamill/react-native-orientation#readme
  - rn-fetch-blob: https://github.com/joltup/rn-fetch-blob#readme
Please notify their maintainers about it. You can find more details at https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide.
info Fetching system and libraries information...
System:
    OS: macOS Mojave 10.14.2
    CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
    Memory: 158.01 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 9.4.0 - ~/.nvm/versions/node/v9.4.0/bin/node
    npm: 5.6.0 - ~/.nvm/versions/node/v9.4.0/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
  IDEs:
    Xcode: 10.1/10B61 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.1 => 16.8.1 
    react-native: ^0.61.4 => 0.61.4 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
```

**Comment by Kida007** [comment]
Hey nihp , 

First of all upgrading like that will only upgrade react-native core files. But your  IOS / Android Files won't be in sync with the latest updates. 

You can either do that manually by using : [upgrade-helper](https://react-native-community.github.io/upgrade-helper/)

or you can also automate most of that using the upgrade command in cli : react-native upgrade  /

Hope this helps !

**Comment by nihp** [comment]
react-native upgrade not works for me. So I have changed the package.json and make it to upgrade.


`error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening Fashion.xcworkspace. Run CLI with --verbose flag for more details.
`

`error Could not find the following native modules: BugsnagReactNative, react-native-cookies, react-native-fast-image, react-native-fetch-blob, react-native-image-picker, react-native-orientation, RNSVG, rn-fetch-blob. Did you forget to run "pod install" ?`

**Comment by kimobrian** [comment]
Follow this upgrade helper and make sure you add this to your Podfile:

```
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

....

use_native_modules!
```
Then run `pod install`. This solved my issue.

**Comment by jay-most** [comment]
> Follow this upgrade helper and make sure you add this to your Podfile:
> 
> ```
> require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
> 
> ....
> 
> use_native_modules!
> ```
> 
> Then run `pod install`. This solved my issue.

running pod install create a dependency issue
144 duplicate symbols for architecture x86_64
