### ISSUE TITLE
TextInput multiline is selectable even when is not editable

### ISSUE THREAD

**Issue by rgras-devborn** [facebook/react-native#27296]
The TextInput control in multiline mode is selectable even if is configured as not editable and there is no way to disable the selection property.

React Native version:

  React Native Environment Info:
    System:
      OS: macOS 10.14.6
      CPU: (4) x64 Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz
      Memory: 138.67 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5977832
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.5 => 16.8.5 
      react-native: 0.59.9 => 0.59.9 

## Steps To Reproduce

**Multiline:**

`<TextInput editable={false} multiline value="Test" />`

![Screen Shot 2019-11-21 at 20 05 39](https://user-images.githubusercontent.com/29492197/69384344-c5211d00-0c9a-11ea-8c62-ac756fc25f29.png)

**Not Multiline:**

`<TextInput editable={false} value="Test" />`

![Screen Shot 2019-11-21 at 20 04 32](https://user-images.githubusercontent.com/29492197/69384328-bd617880-0c9a-11ea-85c2-f8184053120a.png)

Describe what you expected to happen:

Selection should not be selectable if the TextInput is not editable, just like in the single-line mode.

**Comment by Bardiamist** [comment]
If somebody will fix it then please add `selectable` prop for keep current selection behaviour. Or better implement similar behavior for `Text` component:)
