### ISSUE TITLE
You can't set barTintColor on NavigatoriOS

### ISSUE THREAD

**Issue by coenert** [facebook/react-native#273]
I see that in the code that you can set the barTintColor property on NavigatoriOS, but the property isnt actually given to the Objc code.

Is there a another way to set the background of the navigator or is this a bug?

**Comment by vjeux** [comment]
This is most probably a bug. We're not using the navigatorios in any of our real apps so it likely has bugs/unimplemented features

**Comment by hyusetiawan** [comment]
@vjeux out of curiosity, what do you guys use for the navigation?

**Comment by vjeux** [comment]
The Navigation component. It supports left/right navigation with swipe to go back and custom header (we implemented breadcrumbs instead of the standard ios one). Also supports coming from the bottom and swiping down from the top to dismiss.

It is written purely in js and reacf

**Comment by igodzp** [comment]
I would love to see the example of implementing an app using Navigation component. NavigationIOS has so many limitations. :sob:

**Comment by hyusetiawan** [comment]
@igodzp https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/Navigator/NavigatorExample.js

**Comment by igodzp** [comment]
@hyusetiawan Thank you so much! Can't believe I missed that one haha

**Comment by brentvatne** [comment]
This has been fixed!
