### ISSUE TITLE
RN0.61 React.xcodeproj could not be found

### ISSUE THREAD

**Issue by cx5168** [facebook/react-native#27302]
Installed react-native-community/push-notification-ios, compile error [React/RCTEventEmitter.h file not found]
There is no React.xcodeproj below the [\node_modules\react-native\React] folder.

React Native version:
react: 16.9.0 => 16.9.0
react-native: 0.61.4 => 0.61.4

![スクリーンショット 2019-11-22 15 51 10](https://user-images.githubusercontent.com/29448456/69407886-f35d3600-0d48-11ea-866a-b86a0cb0ede7.png)

**Comment by Kida007** [comment]
Hey @cx5168 ,

can you try `pod install` in the ios directory ?

**Comment by cx5168** [comment]
@Kida007 
I don't think it has anything to do with pod. When react-native init creates a project, it is already installed in node_modules. The react-native0.60.4 creation project exists in node_modules/react-native/react with react.xcodeproj

**Comment by cx5168** [comment]
I'm solved it!

1. Libraries→PushNotificationIOS.xcodeproj→build setting→Search Paths→Header Search Paths:
$(SRCROOT)/../../../../ios/Pods/Hearders/Public

2. menu(Product)→Scheme→Edit Scheme:
 [+]→Pods→React
![123](https://user-images.githubusercontent.com/29448456/69602755-f5323c80-105b-11ea-9fa1-7678bc07c8bc.png)

3. clean→build

**Comment by mrousavy** [comment]
@cx5168 I have those header search paths, but the `node_modules/react-native/React` folder does not contain an xcodeproj file..?

**Comment by fabriziobertoglio1987** [comment]
the file is here https://github.com/facebook/react-native/blob/master/React/Modules/RCTEventEmitter.h
