### ISSUE TITLE
Can't add share title on IOS 

### ISSUE THREAD

**Issue by chismadalina** [facebook/react-native#27306]
I have to integrate the Share API in my app and on Android works ok but on IOS the message is always shared as title so what I add on `title` is ignored. 

**React Native version:**
System:
    OS: macOS Mojave 10.14.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 533.27 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.3.0 - ~/.nvm/versions/node/v8.3.0/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 5.3.0 - ~/.nvm/versions/node/v8.3.0/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5977832
    Xcode: 11.2/11B52 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.4 => 0.61.4
## Steps To Reproduce

1. Add title and message in share content
2. See that on IOS the message is always added both as title and message and title is not used at all

Describe what you expected to happen:

**Snack, code example, screenshot, or link to a repository:**
`  const shareContentAndroid = {
      title: productInfo,
      message: shareMessage
    };
    const shareContentIOS = {
      title: 'Share via',
      message: productInfo, //title
      url: null
    };
    let shareContent = IfAndroid(shareContentAndroid, shareContentIOS);
    let shareOptions = {
      dialogTitle: 'dialog title',
      subject: 'subject'
    }
    Share.share(shareContent, shareOptions);`

**Comment by jeswinsimon** [comment]
UIActivityViewController does not have provision to display a title. The `title` attribute in [Share](https://github.com/facebook/react-native/blob/8c0c860e38f57e18296f689e47dfb4a54088c260/Libraries/Share/Share.js#L117) is not being used in case of iOS. This seems to be an error in the documentation.
