### ISSUE TITLE
How to regenerate iOS and Android Folder in React Native Project

### ISSUE THREAD

**Issue by Angel82800** [facebook/react-native#27301]
Hello,

I try to regenerate iOS and Android Folder in React Native Project. (react-native version is 0.61.4).

Before "react-native eject" and "react-native upgrade --legacy true" works for me. But they doesn't work in the current react-native version. 

Please help me. 
Thank you

**Comment by Angel82800** [comment]
Binaries:
    Node: 12.12.0 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.13.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.4 => 0.61.4 
  npmGlobalPackages:
    react-native-cli: 2.0.1

**Comment by RinMinase** [comment]
@hramos  Why was this closed? This seems to be a valid problem.

**Comment by chenyu1990** [comment]
@hramos Why was this closed? This seems to be a valid problem.

**Comment by Albert0405** [comment]
Recently i tried to `npm install` on a project that i saved on a flash drive (I copied all except the Android, IOS and node_modules folders). After the installation is done, it downloads all libraries and generated a node_modules folder but there are no `Android` or `iOS` folders. 

I tried to `react-native run-android` on the project folder but it says ` Android project not found. Are you sure this is a React Native project?` Question is, how can generate its `Android` and `iOS` folders without creating a whole fresh project?

**Comment by OriAlon** [comment]
@hramos Why was this closed? This seems to be a valid problem.
if "react-native eject" & "react-native upgrade" are no longer available 
what command should be used for a full, clean generation of native apps?

**Comment by DanielRiera** [comment]
+1

**Comment by nullxx** [comment]
+1

**Comment by Ustingit** [comment]
react: 16.9.0, react-native: 0.61.5 The same issue. How can we resolve this and why this issue has been closed ?

**Comment by hramos** [comment]
It was closed because the issue template wasn't followed. If you're running into this, please make a new issue.
![Screen Shot 2020-02-04 at 2 49 54 PM](https://user-images.githubusercontent.com/165856/73794582-9f65c900-475d-11ea-888d-2b6b59dc2704.png)

**Comment by Quezion** [comment]
This is still a problem, at least in the sense that it broke instructions for renaming a react-native project. Existing instructions recommend using either eject or upgrade --legacy; both are 100% verifiably gone in the current release and I don't know a replacement.

I was able to follow this comment to rename all files. I did some additional grep + replace, not sure if it mattered, but it should get you most of the way there. https://github.com/facebook/react-native/issues/24616#issuecomment-487574475

**Comment by shubhankar30** [comment]
+1

**Comment by SahilRS200** [comment]
Is the issue still closed?

**Comment by nthh** [comment]
[This solution](https://github.com/react-native-community/cli/issues/808#issuecomment-543207588) worked for me, although there should be an easier way to regenerate the folders.

**Comment by Dalcio** [comment]
I solve this on ubuntu running 
sudo npx react-native run-android

**Comment by phantom-factotum** [comment]
I've just encountered this same problem. Lucky for me, I had started off using expo so I just re-ran expo eject.

**Comment by bdeepu** [comment]
If you want to upgrade with React Native CLI but you don't use Git#
While your project does not have to be handled by the Git versioning system -- you can use Mercurial, SVN, or nothing -- you will still need to install Git on your system in order to use npx react-native upgrade. Git will also need to be available in the PATH. If your project doesn't use Git, initialize it and commit:

```
git init # Initialize a Git repository
git add . # Stage all the current files
git commit -m "Upgrade react-native" # Save the current files in a commit
```

After you finish upgrading you may remove the .git directory.

https://reactnative.dev/docs/upgrading#i-want-to-upgrade-with-react-native-cli-but-i-don-t-use-git

**Comment by vishwajeetraj11** [comment]
I installed expo. ```yarn add expo```
then i ran ```expo eject```
it worked i got the android folder

**Comment by OCompiled** [comment]
Just run: `expo eject`, and it will create both an Ios and Android folder for you

**Comment by cleandevcode** [comment]
Are there any updates for regenerating android & ios folder?

This is my RN info.

```
Node: 14.17.2
Yarn: 1.22.10
npm: 6.14.13
```


```
API Levels: 29, 30
Build Tools: 28.0.3, 29.0.2, 30.0.3
```

```
react: 17.0.1 => 17.0.1
react-native: 0.64.2 => 0.64.2
```

`react-native eject` and `react-native upgrade --legacy true` did not work.

Any updates?
