### ISSUE TITLE
React native ios not building release verision

### ISSUE THREAD

**Issue by faisal212** [facebook/react-native#27314]
i am trying to build the react native  ios app release build  
i am getting this error File /Users/admin/Library/Developer/Xcode/DerivedData/treeofdreams-furflaxhzosozlcbjuxsugryahiq/Build/Products/Release-iphonesimulator/treeofdreams.app/main.jsbundle does not exist. This must be a bug with'

the steps i followed 
1st: I run this command on my project react-native bundle --entry-file index.js --platform ios --dev false --bundle-output ios/main.jsbundle --assets-dest ios
2nd:  Then i go to edit schema inside xcode and change the run tab from debug to release

3rd: then i run the build its take more then 15 minutes then failed with the above error

My Enviouriment information is 
System:
    OS: macOS 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Memory: 89.25 MB / 10.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5977832
    Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
macbook:treeofdreamsapp admin$

**Comment by romanbarzyczakgelato** [comment]
I have facing the same problem

**Comment by EzeRangel** [comment]
I'm facing this too.

I have embedded an iOS app extension that works on development but in release I only see a blank screen.

**Comment by gokhandoslu** [comment]
No watchman installation found. Please install watchman by using the code below
```
brew install watchman
```
For more detail, please visit the documentation: https://facebook.github.io/react-native/docs/getting-started.

You have an issue about the code in node_modules/react-native/scripts/react-native-xcode.sh

Please try to create  main.jsbundle with reset cache parameter.
If you use the Yarn package manager, you can use yarn instead of npx when running React Native commands inside an existing project.

```
npx react-native bundle --entry-file index.js --platform ios --dev false --bundle-output ios/main.jsbundle --assets-dest ios --reset-cache
```

the output like this:
```
warning: the transform cache was reset.
Loading dependency graph, done.
info Writing bundle output to:, ios/main.jsbundle
info Done writing bundle output
info Copying 2 asset files
info Done copying assets
```

**Comment by developer239** [comment]
@gokhandoslu What does this issue have to do with `watchman`? 🙂

**Comment by filiphosko** [comment]
Make sure you didn't mess with babel configuration (babel.config.js file). That could cause that some things could not be transpiled, it would error out and the bundle will not be generated.

**Comment by adarshraj87** [comment]
I tried everything, but @filiphosko comment saved me, I have some configuration changes in babel.config.js for react-native paper, but the library wasn't available.
