### ISSUE TITLE
App crashes after setting state from asyncstorage/

### ISSUE THREAD

**Issue by a-c-sreedhar-reddy** [facebook/react-native#27317]
React Native version:

```
System:
    OS: Linux 5.0 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
    Memory: 152.31 MB / 7.70 GB
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/bin/yarn
    npm: 6.13.0 - /usr/local/bin/npm
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.4 => 0.61.4

```

## Steps To Reproduce

1. On click I wanted to remove a link
2. 
```
function remove(index) {
    AsyncStorage.setItem(
      'links',
      JSON.stringify(Array.from(links).filter((item, i) => i !== index)),
    ).then(() =>
      AsyncStorage.getItem('links')
        .then(link => {
          setLinks(JSON.parse(link));
        })
        .then(() => ToastAndroid.show('Deleted', ToastAndroid.SHORT)),
    );
  }
```

Describe what you expected to happen:
View should be updated but I get this error.
![Screenshot from 2019-11-23 17-14-52](https://user-images.githubusercontent.com/16081083/69478141-f160a900-0e14-11ea-8a03-a91464ac16df.png)

Snack, code example, screenshot, or link to a repository:
[https://github.com/a-c-sreedhar-reddy/Link/blob/master/pages/Home.js#L26](https://github.com/a-c-sreedhar-reddy/Link/blob/master/pages/Home.js#L26)

**Comment by Simek** [comment]
Internal React Native `AsyncStorage` module is deprecated and looking at your file imports you are using package moved to React Native Community repo:
> `import AsyncStorage from '@react-native-community/async-storage';`

I that case issue should be reported here: https://github.com/react-native-community/async-storage.

**Comment by a-c-sreedhar-reddy** [comment]
yeah but I think this issue is also related to RN.

**Comment by Simek** [comment]
@a-c-sreedhar-reddy Please look at examples in the Usage section in `async-storage` repository. 
There has been some changes since extraction from core and both methods are now async:

* https://github.com/react-native-community/async-storage#usage

**Comment by a-c-sreedhar-reddy** [comment]
@Simek yeah i am using .then with them.

**Comment by a-c-sreedhar-reddy** [comment]
My issue was I was importing `TouchableOpacity` from `RNGestureHandler`. When imported from `react-native` there is no issue.
