### ISSUE TITLE
Android Emulator on reload: Could not connect to development server

### ISSUE THREAD

**Issue by kirandash** [facebook/react-native#27315]
I have my project built with react native (0.59.10). In order to launch the application on android emulator, I run the following commands:

    react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res

    react-native start

    react-native run-android

The application then launches on the emulator. But when I reload the application on emulator, I get the following error:

[![enter image description here][1]][1]

Any idea what can be done here so that application reloads properly.

**My Attempts:**

    adb reverse tcp:8081 tcp:8081

But the above command does not fix the issue.

  [1]: https://i.stack.imgur.com/cqoDp.png

**Comment by a-c-sreedhar-reddy** [comment]
once try to load url in your phone browser and check if its available
