### ISSUE TITLE
Docs:

### ISSUE THREAD

**Issue by muhyidin3222** [facebook/react-native#27313]
the compilation I run  ./gradlew bundleRelease , I get this error repeatedly 
  java.lang.RuntimeException: java.lang.RuntimeException: Cannot start "jarsigner" process, please add it to the PATH

**Comment by Archulan** [comment]
Can I take this issue? Can anyone guide me solving this?

**Comment by rickhanlonii** [comment]
@muhyidin3222 thanks for reporting! If you believe this is a bug, would you mind updating your description to fill out the bug template?
