### ISSUE TITLE
Multiple cookies merged as a single string in set-cookies header

### ISSUE THREAD

**Issue by dquessenberry** [facebook/react-native#27336]
There is a fundamental issue with the way React Native is handling multiple cookies in a response header. From a high level, the set-cookies header is intended to be an array with each cookie string as an item in that array. React Native appears to be concatenating those cookie strings into a single comma separated string. There is a fundamental problem to this approach as the standard date format for a cookie's expiration includes a comma, i.e. "Expires=Wed, 21 Oct 2020 07:28:00 GMT";. Therefore splitting this aggregated string by a comma incorrectly breaks up the cookies. Of course a clever RegEx or parsing algorithm could parse these strings correctly, but that is completely unnecessary logic and in my opinion a total hack that could potentially be different per instance or API call since the format of a cookie could be in varying order. 

Additional known issue: on Android devices, only the last cookie in the set-cookie array is returned in the "aggregated" string, of which has apparently been fix recently with this commit, which I believe is included in the latest RN release, v0.61.5: [https://github.com/facebook/react-native/commit/1df8bd4932f42958c01dccf44cee92b75a6988ed](https://github.com/facebook/react-native/commit/1df8bd4932f42958c01dccf44cee92b75a6988ed)

---------------------------------------------

React Native version:
System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
    Memory: 2.60 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.2 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 26, 27, 28
      Build Tools: 28.0.3
      System Images: android-26 | Google Play Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel
x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5977832
    Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.2 => 0.61.2
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7

## Steps To Reproduce
Note: I am using axios, v0.19.0, but fetch will also render the same issue.
1. Create an axios call that expects a response with multiple cookies, i.e.:
`axois.post('/some_api/login', { data: { email: 'test@test.com, password: 'abc123}}).then(response => { console.log('response cookies', response.headers['set-cookie']); });`

2. Verify that all cookie strings have been concatenated into a single string in the set-cookie header. With the above example the response.headers['set-cookie'] array will only have a single item, and that item is a single string of all cookie strings concatenated with a comma separating each cookie.

3. Parse concatenated cookie string. Since the aggregated cookie string was concatenated with a comma separator, splitting the cookie string by a comma separator breaks the cookie up incorrectly because the expiration date includes a comma as well, i.e. "Expires=Wed, 21 Oct 2020 07:28:00 GMT";

Describe what you expected to happen:
Honestly, I would expect React Native to NOT convert the set-cookie array of cookies strings into a single string to begin with, especially since the standard for a set-cookie header is an array of individual cookies  This also breaks helper libraries such as, [set-cookie-parser](https://www.npmjs.com/package/set-cookie-parser), that expect an array of cookies strings, not a single string of multiple cookies. And if for some unknown reason this concatenation must happen, then I would expect RN to not use a comma as the separator since the standard format of a cookie string includes a comma in the date format of the expiration.

This proper fix for this fundamental issue will likely be a breaking change to all those RN apps that are hacking out some parsing logic to deal with this issue. A flag could be used to prevent the cookie aggregation, but then that would require third party libraries, such as axios, to support this flag as well. To be honest, it seems like RN painted itself into the corner on this one, and I don't really have an easy solution without releasing a breaking change.

**Comment by Return-1** [comment]
i believe this is fixed in 0.61.5 but haven't checked myself
