### ISSUE TITLE
Question: any progress towards supporting concurrent mode in react-native?

### ISSUE THREAD

**Issue by AugustoCalaca** [facebook/react-native#27332]
I am trying to use `useTransition` with react-native but I face this mistake 

```
import React from 'react';
const { useTransition } = React;
...
const SUSPENSE_CONFIG = {
  timeoutMs: 3000,
}
...
const [startTransition] = useTransition(SUSPENSE_CONFIG);
```
![Captura de tela de 2019-11-25 12-03-20](https://user-images.githubusercontent.com/28552058/69552691-a7df9d80-0f7d-11ea-8a8c-f3765116493a.png)

**Comment by TheSavior** [comment]
The Fabric work is a prerequisite for concurrent mode. We want it too! :-)

**Comment by hosseinmd** [comment]
How could fabric work on react-native?

**Comment by joerex** [comment]
@TheSavior do you know if there is any kind of roadmap for getting ready native running in concurrent mode?
