### ISSUE TITLE
Carification: Is the new react-native version 0.61.5 works without any runtime issue

### ISSUE THREAD

**Issue by nihp** [facebook/react-native#27345]
I am trying to upgrade react-native version from 0.58.6 to 0.61.5.

I am getting RCTBrigeModule.h file not found error.

Many of us facing the same issue. Can anyone build react-native app without any issues.

I am trying to build the app for 1 week after upgrade. Can any one give any solution for this?

React native version

```
System:
    OS: macOS Mojave 10.14.2
  Binaries:
    Node: 9.4.0 - ~/.nvm/versions/node/v9.4.0/bin/node
    npm: 5.6.0 - ~/.nvm/versions/node/v9.4.0/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
  IDEs:
    Xcode: 10.1/10B61 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
```

**Comment by nihp** [comment]
Updated the environment info for react-native

**Comment by dulmandakh** [comment]
Please see https://react-native-community.github.io/upgrade-helper/?from=0.58.6&to=0.61.5.

**Comment by nihp** [comment]
@dulmandakh But I faced with runtime issues and can't able to build the app in latest react-native version 0.61.5
