### ISSUE TITLE
Integration with Existing Apps iOS 

### ISSUE THREAD

**Issue by bharath424** [facebook/react-native#27341]
React Native version: 0.61.5

## Steps To Reproduce

1. https://facebook.github.io/react-native/docs/integration-with-existing-apps
2. pod install

Describe what you expected to happen:

CocoaPods could not find compatible versions for pod "React/Core" in podfile

My package.json file

"dependencies": {
    "react": "^16.12.0",
    "react-native": "^0.61.5"
  }

<img width="1440" alt="Screenshot 2019-11-26 at 4 07 36 PM" src="https://user-images.githubusercontent.com/50517204/69624406-a344e300-106a-11ea-8e5b-994a57ff234f.png">

**Comment by alessandrocapra** [comment]
Same issue here, and no way to solve it apparently after hours spent on Google. Please share if you know how to make it work

**Comment by WASHSWATDAVID** [comment]
+1

**Comment by gokhandoslu** [comment]
Hi,
I updated documentation and opened a pull request.
Please check this link below.

https://github.com/facebook/react-native-website/commit/042b7dbe5c6a3b8a0a2d04d2dabf1f2815ddd21e
