### ISSUE TITLE
react-native run-android build successful but Does not work with Access Denied

### ISSUE THREAD

**Issue by merryholiday-YK** [facebook/react-native#27364]
I'm a developer developing react-native using VSC on Windows. The build succeeds, but it turns out not to run

The react-native run-android command printed BUILD SUCCESSFUL.

![WUG0g](https://user-images.githubusercontent.com/45347148/69839996-3feec700-129d-11ea-9803-b2fdd27d30dc.png)
But unfortunately in the next line Access is denied. With only a message, the app is installed on the device, but it doesn't run. When I run it, I see the make sure blabla error screen that appears when there is no node server.

i try using 'npm start' , 'yarn start' powershell ran as administrator. But it doesn't build. I tried npm start But 
"BUNDLE [android, dev] ./index.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100.0% (969/969), done." 
Stopped at Try react-native run-android in new powershell. No response Didn't work for me.

This problem eliminated my two days. I want to get help.

Ps. Note that project asd is a new project for testing. If you look at the existing project and test project, I guess it might be Java configuration, but ... I am suffering because there is no proper solution.
-------------------------------------------------------------------------------------------------------------
React Native version:
info
  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
      Memory: 9.39 GB / 15.89 GB
    Binaries:
      Yarn: 1.17.3 - C:\Users\YK\AppData\Roaming\npm\yarn.CMD
      npm: 6.11.3 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5977832

-------------------------------------------------------------------------------------------------------------
## Steps To Reproduce
One day, when nothing special happened, it suddenly happened.

Describe what you expected to happen:
It is the same as above.

**Comment by dl-husky73** [comment]
Any updates here?   I am having the same issue after updating react & react-native.
