### ISSUE TITLE
Metro Bundler did not started automatically, blacklist.js has some issue!

### ISSUE THREAD

**Issue by tusharojha** [facebook/react-native#27369]
React Native version: 0.60

## Steps To Reproduce

1. Create a new react-native project using "npx react-native init NewProject".
2. Try to run it using "npx react-native run-android".

## Problems
1. Metro Bundler Server automatically starts but closes before app launches.
2. When we try to launch metro bundler manually, then it shows following error: 
error Invalid regular expression: /(.\fixtures.|node_modules[]react[]dist[].|website\node_modules.|heapCapture\bundle.js|.\tests.)$/: Unterminated character class. Run CLI with --verbose flag for more details. SyntaxError: Invalid regular expression: /(.\fixtures.|node_modules[]react[]dist[].|website\node_modules.|heapCapture\bundle.js|.\tests.)$/: Unterminated character class at new RegExp () at blacklist (D:\projects\new_proj\node_modules\metro-config\src\defaults\blacklist.js:34:10) at getBlacklistRE (D:\projects\new_proj\node_modules\react-native\node_modules@react-native-community\cli\build\tools\loadMetroConfig.js:69:59) at getDefaultConfig (D:\projects\new_proj\node_modules\react-native\node_modules@react-native-community\cli\build\tools\loadMetroConfig.js:85:20) at load (D:\projects\new_proj\node_modules\react-native\node_modules@react-native-community\cli\build\tools\loadMetroConfig.js:121:25) at Object.runServer [as func] (D:\projects\new_proj\node_modules\react-native\node_modules@react-native-community\cli\build\commands\server\runServer.js:82:58) at Command.handleAction (D:\projects\new_proj\node_modules\react-native\node_modules@react-native-community\cli\build\cliEntry.js:160:21) at Command.listener (D:\projects\new_proj\node_modules\commander\index.js:315:8) at Command.emit (events.js:210:5) at Command.parseArgs (D:\projects\new_proj\node_modules\commander\index.js:651:12)

## Solution
Change the content of  \node_modules\metro-config\src\defaults\blacklist.js file by following :
var sharedBlacklist = [
  /node_modules[/\\]react[/\\]dist[/\\].*/,
  /website\/node_modules\/.*/,
  /heapCapture\/bundle\.js/,
  /.*\/__tests__\/.*/
];

to

var sharedBlacklist = [
  /node_modules[\/\\]react[\/\\]dist[\/\\].*/,
  /website\/node_modules\/.*/,
  /heapCapture\/bundle\.js/,
  /.*\/__tests__\/.*/
];

## Result
Finally, project runs successfully!
But need to have a permanent solution.

Please read the detailed solution in comments.

**Comment by saifali96** [comment]
I think you don't define the difference properly..

**Comment by ikayz** [comment]
@saifali96 @tusharojha I am facing the same issue. I've tried several solutions none have worked so far. The solution by @tusharojha isn't properly defined as stated by @saifali96

**Comment by tusharojha** [comment]
Open this file in any text editor
[Your Project]\node_modules\metro-config\src\defaults\blacklist.js

In this file you will find a variable called sharedBlacklist.
Regex value stored in this value is not correct i.e.
var sharedBlacklist = [
/node_modules[/\]react[/\]dist[/\]./,
/website/node_modules/./,
/heapCapture/bundle.js/,
/./tests/./
];

it should be

var sharedBlacklist = [
  /node_modules[\/\\]react[\/\\]dist[\/\\].*/,
  /website\/node_modules\/.*/,
  /heapCapture\/bundle\.js/,
  /.*\/__tests__\/.*/
];

Sorry, In the post I had mistakenly pasted the same value again.

**Comment by ikayz** [comment]
![image](https://user-images.githubusercontent.com/31007212/70054241-ce39b480-15df-11ea-8029-407449a3f959.png)
@tusharojha  That's what the file looks like. ESlint displays some errors.

**Comment by tusharojha** [comment]
Try removing spaces and remove the first sharedBlacklist variable.

**Comment by tusharojha** [comment]
<img width="544" alt="Capture" src="https://user-images.githubusercontent.com/36601970/70054672-005a0f00-15fe-11ea-813f-217928df1e85.PNG">

**Comment by ikayz** [comment]
@tusharojha I make it exactly like your screenshot.

**Comment by ikayz** [comment]
@tusharojha thanks man, you are a lifesaver your solution worked. I searched Stackoverflow and countless websites with no avail. Though I'd have to add that line to every project, it's temporary. The React Native team need to fix this issue ASAP.

**Comment by tusharojha** [comment]
> I think you don't define the difference properly..

changes updated. thanks

**Comment by ikayz** [comment]
Created a temp gist for those who want to copy the code.
https://gist.github.com/ikayz/d5f727fd42ea3677171baed60386518f

**Comment by cpojer** [comment]
Thank you for your report. We fixed this just now with the release of Metro 0.56.4 and 0.57.0. Update your packages and re-create your project and things should work for you again :) Sorry for the inconvenience.
