### ISSUE TITLE
Execution failed for task ':app:transformDexArchiveWithDexMergerForDebug'

### ISSUE THREAD

**Issue by anastely** [facebook/react-native#27362]
```
System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i3-3110M CPU @ 2.40GHz
    Memory: 161.06 MB / 8.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.12.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 16, 23, 27, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-16 | Intel x86 Atom, android-23 | Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```
I have App written with react-native  and it's work very fine previously

 **but** when I install [RN async-storage][1]
> I Don't change anything in native android code 

I got an error when running the app

I'm trying to remove it and rebuild my app BUT the issue still I don't know why!!

I'm tried to run these command 

    rm -rf node_modules 
    npm install

then

    cd android && gradlew clean
 
and it's building successfully without any error

but after run
react-native run-android

I got 

> * What went wrong: Execution failed for task ':app:transformDexArchiveWithDexMergerForDebug'.
> > com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException:
> com.android.builder.dexing.DexArchiveMergerException: Error while
> merging dex archives:    The number of method references in a .dex
> file cannot exceed 64K.   Learn how to resolve this issue at
> https://developer.android.com/tools/building/multidex.html

 
SO how can I solve it? please it's important "I'm in deadline" :V

  [1]: https://github.com/react-native-community/async-storage

**Comment by sa2812** [comment]
Have you tried following the instructions at the following URL?

> Learn how to resolve this issue at
https://developer.android.com/tools/building/multidex.html

**Comment by anastely** [comment]
@sa2812  yes, but I can't re-build the app I got the same error !

**Comment by sa2812** [comment]
The error is caused because there at more than 64K methods in your app (including all of your dependencies).

In your `android/app/build.gradle`, add the following (I'm assuming that you're using AndroidX since you're on RN 0.60.5:

```gradle
android {
    defaultConfig {
        ...
        minSdkVersion 15 
        targetSdkVersion 28
        multiDexEnabled true
    }
    ...
}
```
and
```gradle
dependencies {
    ...
    def multidex_version = "2.0.1"
    implementation 'androidx.multidex:multidex:$multidex_version'
}
```

Then, in your `MainApplication.java` add the following import at the top
```
import androidx.multidex.MultiDexApplication;
```

and replace this
```java
public class MainApplication extends Application implements ReactApplication {
```
with this
```java
public class MainApplication extends MultiDexApplication implements ReactApplication {
```

For reference or more questions, look at this answer on [StackOverflow](https://stackoverflow.com/questions/44140496/how-do-i-enable-multidex-for-react-native).

After you run your build you shouldn't get this same error again

**Comment by hongweiCui** [comment]
@sa2812 thanks!

**Comment by TitanFury19** [comment]
just add this in android/app/build.gradle

```
android{
defaultConfig{
  .......
 multiDexEnabled true 
  }
}

```

**Comment by shani-maini** [comment]
Hope it's Help

https://medium.com/@tiwarishani/task-app-transformdexarchivewithdexmergerfordebug-failed-in-react-native-6d03bc4655af

**Comment by eramudeep** [comment]
> just add this in android/app/build.gradle
> 
> ```
> android{
> defaultConfig{
>   .......
>  multiDexEnabled true 
>   }
> }
> ```

Yes.!!!  **Worked for me**

**Comment by anastely** [comment]
Hello Guys again, 
I've faced the same error but `Execution failed for task ':app:transformDexArchiveWithDexMergerForRelease'.` when releasing an APK.

I follow all answers here but not works for me :(

**Comment by nadzic** [comment]
Same here an anastely mentiond, did you find any solution?

**Comment by jinaddavid** [comment]
Am having the same project after upgrading from 0.59.3 to 0.59.9 . please any solution to this.?
