### ISSUE TITLE
AppRegistry.registerComponent componentProvider call more than once

### ISSUE THREAD

**Issue by middle2021** [facebook/react-native#27368]
Android devices

React Native version: 0.59.9

## Steps To Reproduce

1. first installed and open, then press  home button
2. when app from background to foreground, the method  【run】will call again,

![image](https://user-images.githubusercontent.com/11364516/69854856-1e093a80-12c5-11ea-9a44-59fd386e88e3.png)

**Comment by dulmandakh** [comment]
Please see https://github.com/facebook/react-native/issues/27370

**Comment by middle2021** [comment]
thank you😁
