### ISSUE TITLE
Question: -[UIImage animatedImageFrameCount]: unrecognized selector sent to instance 

### ISSUE THREAD

**Issue by fypyxz** [facebook/react-native#27367]
环境：Xcode:11.2
"react": "16.9.0",
    "react-native": "0.61.3",
JS代码:<Image source={{ uri: 'file://'+ this.props.appPath + '/1024.png' }} 
              style={styles.localImage}/>
<Image
          source={{uri: item.posters.thumbnail}}
          style={styles.thumbnail}
        />
简单的使用图片，导致使用图片位置崩溃最后跟踪到RCTUIImageViewAnimated.m文件，
这块代码：if ([image respondsToSelector:@selector(animatedImageFrameAtIndex:)]) {
修改成是否支持协议：
if ([image.class conformsToProtocol:@protocol(RCTAnimatedImage)]) {
就可以正常运行，
不知道是不是我项目配置问题，还是RCTUIImageViewAnimated.m文件的bug。
有个奇怪的问题就是我重新创建了一个demo,不用修改RCTUIImageViewAnimated.m文件也能够正常加载图片，所以比较疑问？

**Comment by 17554265585** [comment]
> 环境：Xcode:11.2
> "react": "16.9.0",
> "react-native": "0.61.3",
> JS代码:<Image source={{ uri: 'file://'+ this.props.appPath + '/1024.png' }}
> style={styles.localImage}/>
> <Image
> source={{uri: item.posters.thumbnail}}
> style={styles.thumbnail}
> />
> 简单的使用图片，导致使用图片位置崩溃最后跟踪到RCTUIImageViewAnimated.m文件，
> 这块代码：if ([image respondsToSelector:@selector(animatedImageFrameAtIndex:)]) {
> 修改成是否支持协议：
> if ([image.class conformsToProtocol:@protocol(RCTAnimatedImage)]) {
> 就可以正常运行，
> 不知道是不是我项目配置问题，还是RCTUIImageViewAnimated.m文件的bug。
> 有个奇怪的问题就是我重新创建了一个demo,不用修改RCTUIImageViewAnimated.m文件也能够正常加载图片，所以比较疑问？

我也遇到了一样的问题，0.61.5版本

**Comment by damoncoo** [comment]
Same issue here

**Comment by NathanOu** [comment]
Same issue here

**Comment by yy-linye** [comment]
“animatedImageFrameAtIndex”  repeat in the project
