### ISSUE TITLE
canOpenURL return wrong.

### ISSUE THREAD

**Issue by xclidongbo** [facebook/react-native#27375]
React Native version:
info
  React Native Environment Info:
    System:
      OS: macOS 10.15.1
      CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
      Memory: 33.48 MB / 8.00 GB
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.12.0 - /usr/local/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.11.3 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
      Android SDK:
        API Levels: 23, 25, 26, 27, 28, 29
        Build Tools: 27.0.3, 28.0.3
        System Images: android-29 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5977832
      Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: ^0.59.10 => 0.59.10

## Steps To Reproduce

```
Linking.canOpenURL('http://mail.sinosig.com')
              .then(supported=>{
                if (!supported) {
                  // 不支持
                  console.log('不支持');
                } else {
                  // 支持
                  console.log('支持');
                }
              }).catch(err=>{
                console.log(err);
                console.log('不支持-错误');
              })
```

Describe what you expected to happen:

Snack, code example, screenshot, or link to a repository:

**Comment by big-toni** [comment]
this is stupid, canOpenURL() now throws instead of returning False bool if link cannot be open, this does, not make any sense

**Comment by janziemba** [comment]
Our app started crashing in production because of this.
