### ISSUE TITLE
Missing 'Enter' key event from external keyboard after updating to 0.60+ version

### ISSUE THREAD

**Issue by ivanushka1703** [facebook/react-native#27385]
I use react-native-keyevent package (https://github.com/kevinejohn/react-native-keyevent) for barcode handling using bluetooth scanner. It works as external bluetooth keyboard.
After updating react-native to above 0.60 version event for 'Enter' button doesn't firing on Android. Other keyboard events work as usual.

I tried to use DeviceEventEmitter instead, but with the same result.

It's noteworthy that if I set focus to TextInput and scan the barcode, everything will work as expected with the 'Enter' event at the end. After the TextInput focus loss, the event of the `Enter` button triggers only once, while the second scan does not trigger the event.

React Native version:

```
React Native Environment Info:
    System:
    OS: macOS 10.15.1
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Memory: 7.22 GB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.0.0 - /usr/local/bin/node
    Yarn: 1.19.2 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 27, 28
      Build Tools: 23.0.1, 27.0.3, 28.0.3, 29.0.0
      System Images: android-26 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

## Steps To Reproduce

1. Connect device with external keyboard (barcode scanner)
2. Add listener for keyboard events
3. Scan a barcode or enter a string with 'Enter' on the end.

Describe what you expected to happen:
Event of 'Enter' button works as usually before updating to above 0.60 a version of react native.

Snack, code example, screenshot, or link to a repository:

MainActivity.java
```
public class MainActivity extends ReactFragmentActivity {
  @Override // overide onKeyDown method to listen external keyboard events
  public boolean onKeyDown(int keyCode, KeyEvent event) {
      KeyEventModule.getInstance().onKeyDownEvent(keyCode, event);

    super.onKeyDown(keyCode, event);
    return true;
  }
...
```

KeyEventModule.java
```
...
public void onKeyDownEvent(int keyCode, KeyEvent keyEvent) {
    if (!mReactContext.hasActiveCatalystInstance()) {
        return;
    }

    if (mJSModule == null) {
        mJSModule = mReactContext.getJSModule(DeviceEventManagerModule.RCTDeviceEventEmitter.class);
    }
    mJSModule.emit("onKeyDown", getJsEventParams(keyCode, keyEvent, null));
};
...
private WritableMap getJsEventParams(int keyCode, KeyEvent keyEvent, Integer repeatCount) {
    WritableMap params = new WritableNativeMap();
    int action = keyEvent.getAction();
    char pressedKey = (char) keyEvent.getUnicodeChar();

    if (keyEvent.getAction() == KeyEvent.ACTION_MULTIPLE && keyCode == KeyEvent.KEYCODE_UNKNOWN) {
        String chars = keyEvent.getCharacters();
        if (chars != null) {
            params.putString("characters", chars);
        }
    }

    if (repeatCount != null) {
        params.putInt("repeatcount", repeatCount);
    }

    params.putInt("keyCode", keyCode);
    params.putInt("action", action);
    params.putString("pressedKey", String.valueOf(pressedKey));

    return params;
 }
...
```
BarcodeListener.jsx
```
...
componentDidMount() {
    KeyEvent.onKeyDownListener(({ pressedKey, keyCode }) => {
      if (keyCode === 10) { // Enter button
        this.handleSubmit();
      } else {
        this.setState(({ barcode }) => ({
          barcode: `${barcode}${pressedKey}`,
        }));
      }
    });
  }
...
```

**Comment by djayan07** [comment]
I use react-native-keyevent package (https://github.com/kevinejohn/react-native-keyevent) for barcode handling using bluetooth scanner. It works as external bluetooth keyboard.

After updating react-native to above 0.60 version event for 'Enter' button doesn't firing on Android. Other keyboard events work as usual.

React Native version::

```
System:
    OS: Windows 10 10.0.17134
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 4.87 GB / 31.85 GB
  Binaries:
    Node: 12.8.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.12.0 - C:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 16, 17, 18, 19, 21, 22, 23, 26, 28, 29
      Build Tools: 21.1.2, 23.0.1, 23.0.2, 23.0.3, 27.0.3, 28.0.3, 29.0.1, 29.0.2
      System Images: android-25 | Google Play Intel x86 Atom
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
```

# Steps To Reproduce
* Connect device with external keyboard (barcode scanner Zebra Symbol RS507X)
* Add react-native-keyevent package
* Scan a barcode .

Describe what you expected to happen:
Event of 'Enter' button works as usually before updating to above 0.60 a version of react native.

Snack, code example, screenshot, or link to a repository:

app.js

```
...
componentDidMount() {
    KeyEvent.onKeyDownListener((keyEvent) => {
        if (keyEvent.keyCode === keyEvent.KEYCODE_ENTER) {
            submitMessage();
        }
    });
...
```

**Comment by hntddt123** [comment]
Any solution to this?

**Comment by ivanushka1703** [comment]
> Any solution to this?

I was able to get around this bug with a dirty hack by adding 'TouchableHighlight' to the render function of my barcode listener component. 
As I can see, for Android, pressing the 'Enter' key sets the focus on the first element available for focusing in the app and then presses it. You need to manually set the focus on the 'TouchableHighlight' (use ref for this `touchable.current.setNativeProps({ hasTVPreferredFocus: true })`) on every key pressing and add an onPress handler to it.

**Comment by arrowlikeme** [comment]
try this

MainActivity (Kotlin):

```
  override fun dispatchKeyEvent(e: KeyEvent): Boolean {
    if (e.keyCode == KeyEvent.KEYCODE_ENTER) {
      return false
    }
    return super.dispatchKeyEvent(e)
  }
```
