### ISSUE TITLE
RCTFatal + 668

### ISSUE THREAD

**Issue by augustbjornberg** [facebook/react-native#27387]
I've noticed that a not insignificant number of my iOS users experience the fatal error ( RCTFatal + 668 ) in production. The error occurs about 0.004 times per session, not terrible, but not great either. 

There seems to be no correlation between the error and what iOS version the user is running, the number of crashes seems to be directly tied to the number of sessions for each iOS version. What iOS device the user has doesn't seem to correlate with the error either.

I'm unable to reproduce the bug in local, staging, or production. How can i debug this error further?

___

**react-native info**

	System:
	  OS: macOS Mojave 10.14.6
	  CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
	  Memory: 189.93 MB / 16.00 GB
	  Shell: 3.2.57 - /bin/bash

	Binaries:
	  Node: 12.8.0 - /usr/local/bin/node
	  Yarn: 1.17.3 - /usr/local/bin/yarn
	  npm: 6.4.1 - /usr/local/bin/npm
	  Watchman: 4.9.0 - /usr/local/bin/watchman

	SDKs:
	  iOS SDK:
	    Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
	  Android SDK:
	    Android NDK: 20.0.5594570

	IDEs:
	  Android Studio: 3.5 AI-191.8026.42.35.5977832
	  Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild

	npmPackages:
	  react: 16.9.0 => 16.9.0
	  react-native: 0.61.2 => 0.61.2

___

**Screenshot from crashes tab in Xcode** (App name blurred for privacy)

<img width="825" alt="Screen Shot 2019-12-02 at 2 52 39 PM" src="https://user-images.githubusercontent.com/1137612/70002625-720a5e00-1515-11ea-94cd-7fbc656a8977.png">

___

_**P.S** I'm aware that i'm not running the very latest version of RN. By the time i've upgraded RN, pushed to review, passed review, and got 2 weeks of crash reports there will always be a new version out. If this is known to be fixed in a later RN version, i will happily upgrade._

**Comment by augustbjornberg** [comment]
👀

**Comment by tukaEmad** [comment]
I have the same issue, any solutions?

**Comment by stefnnn** [comment]
I got the same 668 fatal crashes on-device only and it turned out to be related to my react-navigation configuration (forgot to import gesture-handler in index.js). See here: https://github.com/software-mansion/react-native-gesture-handler/issues/320#issuecomment-447534290

**Comment by augustbjornberg** [comment]
> I got the same 668 fatal crashes on-device only and it turned out to be related to my react-navigation configuration (forgot to import gesture-handler in index.js). See here: [software-mansion/react-native-gesture-handler#320 (comment)](https://github.com/software-mansion/react-native-gesture-handler/issues/320#issuecomment-447534290)

Since my app didn't crash when i performed a swiped backwards, and that the pop to previous screen action didn't occur (which was the behavior that i wanted), i assumed everything was fine. It wasn't until i swiped backwards twice in fast succession in the production environment on device that the app crashed. Since backwards swipe wasn't a behavior that i wanted, i instead solved the issue by disabling gesture events in my stack navigator.

    createStackNavigator({
    ...
    }, {
        defaultNavigationOptions: {
            gesturesEnabled: false
        }
    })
