### ISSUE TITLE
Blank white screen when foreground app

### ISSUE THREAD

**Issue by DinhHuyHoang** [facebook/react-native#27400]
React Native version:

## Steps To Reproduce

1. Turn on app
2. Put app to background 
3. Wait for long time
4. Turn on again app
5. This time, blank white screen show up

Note: app released and put to store ch-play

System:
    OS: Windows 10 10.0.17763
    CPU: (8) x64 Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz
    Memory: 6.98 GB / 15.89 GB
  Binaries:
    Node: 12.10.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.10.3 - C:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28
      Build Tools: 23.0.1, 26.0.1, 26.0.3, 27.0.3, 28.0.2, 28.0.3, 29.0.1, 29.0.2
      System Images: android-26 | Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-27 | Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
      Android NDK: 20.0.5594570
  IDEs:
    Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5791312
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5

**Comment by ryzhak** [comment]
+1

**Comment by ryzhak** [comment]
@DinhHuyHoang 

to fix it please check this file https://raw.githubusercontent.com/react-native-community/rn-diff-purge/release/0.62.0-rc.0/RnDiffApp/android/app/src/main/AndroidManifest.xml and apply the following changes:
```
android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode"
android:launchMode="singleTask"
```

**Comment by janziemba** [comment]
It still happens even with `android:launchMode="singleTask"` 😕

**Comment by alejandrorangel** [comment]
I have seen this behavior, but so far, I haven't been able to reproduce it consistently.

**Comment by danwhite-ipc** [comment]
I am having this issue on iOS, when the app is in the background for 12+ hours

**Comment by Esxiel** [comment]
I'm also seeing this issue on the iOS, presumably for the same reasons, since on the iOS, apps that have been in the background for a long time will re-show their splash screen...
@danwhite-ipc can I please ask you about your tools? Are you using react-navigation? Are you using apollo? Have you used the pro tip listed here https://reactnative.dev/docs/running-on-device#pro-tip ? I'm just trying to find common points, in my case I'm using react navigation and apollo,and I also haven't used that pro tip yet.

**Comment by danwhite-ipc** [comment]
@Esxiel I am using react-navigation, I am not using apollo. I haven't tried the pro tip but I use react-native-splash-screen to control the splash screen. My app processes background notifications and this issue only seems to affect users in which background notifications are not being given the resources to run.

Here are my project dependencies.
> "dependencies": {
    "@fortawesome/fontawesome-svg-core": "^1.2.28",
    "@fortawesome/pro-light-svg-icons": "^5.13.0",
    "@fortawesome/pro-regular-svg-icons": "^5.13.0",
    "@fortawesome/pro-solid-svg-icons": "^5.13.0",
    "@fortawesome/react-native-fontawesome": "^0.2.5",
    "@react-native-community/async-storage": "^1.9.0",
    "@react-native-community/masked-view": "^0.1.9",
    "@react-native-community/netinfo": "^5.7.0",
    "@react-native-community/push-notification-ios": "^1.2.0",
    "@react-navigation/bottom-tabs": "^5.2.6",
    "@react-navigation/compat": "^5.1.8",
    "@react-navigation/native": "^5.1.5",
    "@react-navigation/stack": "^5.2.10",
    "appcenter": "3.0.1",
    "appcenter-analytics": "3.0.1",
    "appcenter-crashes": "3.0.1",
    "deepmerge": "^4.2.2",
    "es6-promise-polyfill": "^1.2.0",
    "immer": "^6.0.3",
    "jssip": "*****",
    "prop-types": "^15.7.2",
    "react": "16.11.0",
    "react-native": "0.62.2",
    "react-native-actionsheet": "^2.4.2",
    "react-native-callkeep": "3.0.12",
    "react-native-config": "^1.2.1",
    "react-native-contacts": "^5.2.1",
    "react-native-dark-mode": "^0.2.2",
    "react-native-device-info": "^5.5.4",
    "react-native-dropdownalert": "4.2.1",
    "react-native-elements": "^2.0.4",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-image-crop-picker": "^0.28.0",
    "react-native-incall-manager": "^3.2.7",
    "react-native-keychain": "^6.0.0",
    "react-native-lightweight-responsive": "^0.0.6",
    "react-native-localization": "^2.1.6",
    "react-native-notifications": "^3.2.1",
    "react-native-permissions": "^2.1.1",
    "react-native-reanimated": "^1.8.0",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-screens": "^2.4.0",
    "react-native-search-filter": "^0.1.5",
    "react-native-splash-screen": "^3.2.0",
    "react-native-svg": "^12.1.0",
    "react-native-tab-view": "^2.14.0",
    "react-native-vector-icons": "^6.6.0",
    "react-native-voip-push-notification": "^2.0.0",
    "react-native-webrtc": "github:nimbleape/react-native-webrtc#84-plus-dtmf-plus-field-trial",
    "react-redux": "^7.2.0",
    "redux": "^4.0.5",
    "redux-logger": "^3.0.6",
    "redux-persist": "^6.0.0",
    "redux-persist-transform-encrypt": "^2.0.1",
    "reselect": "^4.0.0",
    "time-stamp": "^2.2.0",
    "tslib": "^1.11.1",
    "uuid-by-string": "^3.0.2",
    "valid-url": "^1.0.9"
  },

**Comment by kirantripathi** [comment]
@Esxiel  @danwhite-ipc  I am also. facing same issue in IOS after few days when app is in background ,it. shows white screen when you open it How did you. guys tackle it ?

**Comment by danwhite-ipc** [comment]
My issue turned out to be an exception caused by keychain which caused intermittent rendering issues

**Comment by kirantripathi** [comment]
@danwhite-ipc  I am facing this in IPA that I sent to the user to check, so can it also happen in such case too?

**Comment by danwhite-ipc** [comment]
My issue was around keychain accessibility option, quite specific to my implementation

**Comment by Sach-SPF** [comment]
@kirantripathi - I too facing the same issue, did you able to come over this issue?

**Comment by prankymat** [comment]
we're facing this issue on Android, can't reproduce reliably, tried using singleTask and updating Firebase didn't seem to help.

**Comment by saranya20-t** [comment]
Guys, did you find any solution? I'm also facing this issue in iOS app

**Comment by prankymat** [comment]
We found out later that we have a setting for Expo auto update which had an invalid URL and the app stopped loading the JS bundle. We removed the auto update feature from expo and the white screen issue is gone.
