### ISSUE TITLE
EventEmitter in react-native 0.61 is not working as 0.60

### ISSUE THREAD

**Issue by kamelj** [facebook/react-native#27413]
When I using EventEmitter in react-native 0.61 I got this error:

Unable to resolve module `EventEmitter` from `Main.js`: EventEmitter could not be found within the project.

This is Main.js look like:
```
import _EventEmitter from 'EventEmitter';
export const EventEmitter = new _EventEmitter();

export const toast = (msg, duration = 4000) => { 
EventEmitter.emit(Constants.EmitCode.Toast, msg, duration) ;
};
```

**Comment by GunnarAK** [comment]
The magic you describe has been removed: https://github.com/facebook/react-native/issues/24316

To fix the import issue:
```
import EventEmitter from "react-native/Libraries/vendor/emitter/EventEmitter";
```

Searching `EventEmitter.js` in node_modules tells you the path. Same method can be applied on other imports having this type of error.
Example:
```
import type EmitterSubscription from "EmitterSubscription";
```
to
```
import type EmitterSubscription from "react-native/Libraries/vendor/emitter/EmitterSubscription";
```

**Comment by youssef212** [comment]
@GunnarAK  solution saves the day but still this is an issue

**Comment by demedos** [comment]
Still an issue on 0.64
