### ISSUE TITLE
[iOS][MapView] Support for changing annotation image

### ISSUE THREAD

**Issue by phongyewtong** [facebook/react-native#2741]
Any plan for allowing change of annotation image on the mapview?

**Comment by mkonicek** [comment]
I'll let @tadeuzagallo answer and close this (based on git blame).

**Comment by Andr3wHur5t** [comment]
+1

**Comment by kenwheeler** [comment]
I got this working locally, would a PR be accepted/entertained for this?

**Comment by kenwheeler** [comment]
If you want this to work with local xcassets imagery:

- In `RCTMapManager.m`, change:

```
MKPinAnnotationView *annotationView = [[MKPinAnnotationView alloc] initWithAnnotation:annotation reuseIdentifier:@"RCTAnnotation"];
  annotationView.animatesDrop = annotation.animateDrop;
```
to

```
MKAnnotationView *annotationView = [[MKAnnotationView alloc] initWithAnnotation:annotation reuseIdentifier:@"RCTAnnotation"];
  annotationView.image = annotation.image;
```

- In `RCTPointAnnotation.h` add:

```
@property (nonatomic, copy) UIImage *image;
```

- In `RCTConvert+MapKit.m` , in the PointAnnotation portion add:

```
shape.image = [UIImage imageNamed:[RCTConvert NSString:json[@"image"]]];
```

In a proper PR I would imagine you'd want to account for external images and non-existince of the image prop and then default to `MkPinAnnotationView`.

**Comment by tadeuzagallo** [comment]
Feel free to send a PR and assign to me.
As for missing images, using `[RCTConvert UIImage:]` should do all the necessary checks.
