### ISSUE TITLE
error: Trying to upgrade from newer version "0.59.9" to older "0.59.10"

### ISSUE THREAD

**Issue by souravkm** [facebook/react-native#27428]
While trying to update from version 0.59.9 to 0.59.10 I have encountered an issue. The upgrade fails and the error message seems to be incorrect for the scenario.

React Native version: 0.59.9
```
  info 
  React Native Environment Info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
      CPU: (4) x64 AMD Ryzen 3 2200G with Radeon Vega Graphics
      Memory: 478.39 MB / 14.69 GB
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 10.16.1 - ~/.nvm/versions/node/v10.16.1/bin/node
      Yarn: 1.19.1 - /usr/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.1/bin/npm
    SDKs:
      Android SDK:
        API Levels: 28, 29
        Build Tools: 28.0.3, 29.0.2
        System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.9 => 0.59.9 
```

## Steps To Reproduce

1. When in version 0.59.9
2. Trying to upgrade using the command:  `react-native upgrade 0.59.10`
3. I get an error as: `error Trying to upgrade from newer version "0.59.9" to older "0.59.10"
`

Instead of upgrading to the newer version, I get an error saying the newer version is older.

![image](https://user-images.githubusercontent.com/37179905/70299673-9028d480-181b-11ea-9d09-3691f79938d1.png)

**Comment by levibuzolic** [comment]
Looks like this was fixed in https://github.com/react-native-community/cli/commit/00b930877c2a133196dee8231552a53669aff61d should be available in 2.0.1 of `react-native-cli`.
