### ISSUE TITLE
textAlignVertical top not working as expected on Android

### ISSUE THREAD

**Issue by asaharan** [facebook/react-native#27438]
**_textAlignVertical: top_** is not working on Android as  **_verticalAlign: super_** works on web.

OR

**_textAlignVertical: top_** is not working on React Native Android as  it works on React Native Web.

React Native version:

System:
    OS: macOS 10.15.1
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Memory: 36.43 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
    Yarn: 1.19.2 - ~/.yarn/bin/yarn
    npm: 6.12.1 - ~/.nvm/versions/node/v12.13.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 28, 29
      Build Tools: 27.0.3, 28.0.1, 28.0.3, 29.0.2
      System Images: android-28 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5977832
    Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.4 => 0.61.4
  npmGlobalPackages:
    react-native-git-upgrade: 0.2.7

## Steps To Reproduce

1.
2.

Describe what you expected to happen:

Snack, code example, screenshot, or link to a repository:
Snack code: https://snack.expo.io/B1ASXgFpr

### Screenshots
Screenshot of Snack on an Android device
<img width="324" alt="Screenshot 2019-12-07 at 3 11 11 PM" src="https://user-images.githubusercontent.com/11248242/70372401-731c0080-1904-11ea-984b-abd94041eb16.jpg">
 

Screenshot of Snack on web 
<img width="324" alt="Screenshot 2019-12-07 at 3 11 11 PM" src="https://user-images.githubusercontent.com/11248242/70372411-9c3c9100-1904-11ea-9175-ed6a3082be11.png">

**Comment by tuantvk** [comment]
@asaharan Plz rename variable `super` to other. Because `super` is systax in javascript Example:
```js
// current
	super: {
		fontSize: 8,
		textAlignVertical: 'top',
	},
// to
	text_super: {
		fontSize: 8,
		textAlignVertical: 'top',
	},

// inlineStyles
{styles: ['text_super'], length: 1, text: '2'},
```
