### ISSUE TITLE
[Suggestion] Enhancement on react native

### ISSUE THREAD

**Issue by 1nfinite** [facebook/react-native#27436]
Coming from a non mobile developer background, i struggle a lot on react native especially on the configuration and compilation part. That being say that, it wouldn't be an easy job to release the app if the developer has no mobile development background.

Initially I thought that it will ease the process but in the end I have to google all over the place to get it work for android and ios debug and release apk.

I hope that react native would prioritize following on roadmap instead.

**1) Auto generate splashscreen/icon of different size (based on android/ios default guideline)**
Also, when build time it will auto copy into relevant android/ios folder.
```
react-native generate-icon --icon.jpg 
react-native generate-splashscreen --splashscreen.jpg
```
```
assets
- android
  - splashscreen
  - icon
  icon.jpg
- ios
  - splashscreen
  - icon
  splashscreen.jpg
```

**2) A config file to specify. debug and release mode**
- This should also be copy into relevant android/ios folder when build
- will override default config in android/ios folder
```
android-debug.json
android-release.json
ios-debug.json
ios-release.json

{
   "packageName": "com.hello.package",
   "version": "",
   "keystoreLocation": "",
   "screenOrientation": "portrait",
   "fixScreenOrientation": true
   "promptPermissionOnFirst": false, 
   "minTargetSdk": 16,
   "maxTargetSdk": 28,
   "appPermission": [
	"camera", // all permission can be configure here
        "geolocation",
   ]
}
```

**3) Command to build debug and release apk file (based on config file above)**
```
react-native build-android --debug
react-native build-android --release
react-native build-ios --debug
react-native build-ios --release
```

**4) Automated deployment to play store/apple store** (ok, mayb this is too much)

**Comment by terrysahaidak** [comment]
Hi @1nfinite, did you take a look at expo.io? It attempts to solve most of the problems you described.

**Comment by hramos** [comment]
https://github.com/react-native-community/discussions-and-proposals might be a better fit for this type of issue (we're only using GitHub Issues in this repo to track reproducible bugs)
