### ISSUE TITLE
TypeError: Cannot read property 'getItem' of undefined reoccur on RN 0.61.x

### ISSUE THREAD

**Issue by vincent-cm** [facebook/react-native#27431]
Redbox is showing: 

TypeError: Cannot read property 'getItem' of undefined
This error is located at:
    in FlatList (at YellowBoxList.js:87)
    in RCTView (at YellowBoxList.js:79)
    in YellowBoxList (at YellowBox.js:108)
    in YellowBox (at AppContainer.js:96)
    in RCTView (at AppContainer.js:119)
    in AppContainer (at renderApplication.js:39)

React Native version:
System:
    OS: macOS 10.15.1
    CPU: (4) x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
    Memory: 21.21 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
    npm: 6.13.2 - ~/.nvm/versions/node/v12.13.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5977832
    Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.12.0 => 16.12.0 
    react-native: 0.61.5 => 0.61.5

## Steps To Reproduce

1. do not know which function caused this error
2. when tracing from bottom I can see the prop is not set from Flatlist.js, See screenshot

It first called super(prop), then this.prop should set but no.

<img width="577" alt="Screenshot 2019-12-06 at 12 12 34" src="https://user-images.githubusercontent.com/22391049/70323073-c2d6cb00-1823-11ea-9a33-2fb59a279489.png">

<img width="898" alt="Screenshot 2019-12-06 at 12 13 36" src="https://user-images.githubusercontent.com/22391049/70323086-c9fdd900-1823-11ea-9f54-fd59aead5400.png">

Describe what you expected to happen:
No red box pop up

**Comment by tabekg** [comment]
Any solution?

**Comment by kyryloz** [comment]
Looks like `VirtualizedList` require some new attributes:
```
type RequiredProps = {
  /**
   * The default accessor functions assume this is an Array<{key: string} | {id: string}> but you can override
   * getItem, getItemCount, and keyExtractor to handle any type of index-based data.
   */
  data?: any,
  /**
   * A generic accessor for extracting an item from any sort of data blob.
   */
  getItem: (data: any, index: number) => ?Item,
  /**
   * Determines how many items are in the data blob.
   */
  getItemCount: (data: any) => number,
};
```
My WebStorm is also complained about missing required attributes for a FlatList:
```
Element FlatList doesn't have required attribute getItem 
Element FlatList doesn't have required attribute getItemCount 
```
The code works, no runtime crashes but my tests are failing. 
I also spent some time finding any of information about these new required params but didn't manage to find any.

React-Native 0.61.5.

**Comment by georgecirilo** [comment]
We are running with the same issue, this is not fixed. Tracking down the issue it seems that the initialization of these variables is failing:

///// React-Native 0.61.5 code - actual in use:
```
.....
_checkProps(props: Props<ItemT>) {
    const {
      getItem,
      getItemCount,
      horizontal,
      numColumns,
      columnWrapperStyle,
      onViewableItemsChanged,
      viewabilityConfigCallbackPairs,
    } = props;
    invariant(
      !getItem && !getItemCount,
      'FlatList does not support custom data formats.',
    );
    if (numColumns > 1) {
      invariant(!horizontal, 'numColumns does not support horizontal.');
    } else {
      invariant(
        !columnWrapperStyle,
        'columnWrapperStyle not supported for single column lists',
      );
    }
    invariant(
      !(onViewableItemsChanged && viewabilityConfigCallbackPairs),
      'FlatList does not support setting both onViewableItemsChanged and ' +
        'viewabilityConfigCallbackPairs.',
    );
  }
.....
```


Comparing code with 0.62.x, they seem to know about this but still it does not work propperly.

//////// 0.62.x code below - compared code:
```
....
 _checkProps(props: Props<ItemT>) {
    const {
      // $FlowFixMe this prop doesn't exist, is only used for an invariant
      getItem,
      // $FlowFixMe this prop doesn't exist, is only used for an invariant
      getItemCount,
      horizontal,
      numColumns,
      columnWrapperStyle,
      onViewableItemsChanged,
      viewabilityConfigCallbackPairs,
    } = props;
....

```

![image](https://user-images.githubusercontent.com/15729832/79701363-df275180-8272-11ea-9436-c61a7a49e868.png)

**Comment by mlazari** [comment]
I see this error starts appearing when I try to remove `@babel/plugin-transform-flow-strip-types` plugin from `babel.config.json`. With it the error does not occur.

**Comment by mlazari** [comment]
Nevermind, there was another plugin in `babel.config.js` - `['@babel/plugin-proposal-class-properties', { loose: true }],`. If I remove both `['@babel/plugin-proposal-class-properties', { loose: true }],` and `['@babel/plugin-transform-flow-strip-types'],` then the issue goes away.

**Comment by juliuspopa** [comment]
As pointed out elsewhere, I deleted my `babel.config.js`, and moved the babel config to my `package.json`.

`"babel": { "plugins": [ [ "@babel/plugin-proposal-decorators", { "legacy": true } ], [ "@babel/plugin-proposal-class-properties", { "loose": true } ] ] }`
