### ISSUE TITLE
android have not React.NativeModules.UIManager.Dimensions.window object.

### ISSUE THREAD

**Issue by buhe** [facebook/react-native#2744]
Awesome project!
Android has React.NativeModules.UIManager.Dimensions.windowPhysicalPixels, it is not different from ios.

harebu

**Comment by mikearmstrong001** [comment]
Have you looked into using the Dimensions module?

https://github.com/facebook/react-native/blob/master/Libraries/Utilities/Dimensions.js
```
var Dimensions = require('Dimensions');
var width = Dimensions.get('window').width
var height = Dimensions.get('window').height
```

**Comment by brentvatne** [comment]
To add on to what @mikearmstrong001 said above, you should try to use `Dimensions` via the React object:

```
var { Dimensions } = require('react-native');
var width = Dimensions.get('window').width
var height = Dimensions.get('window').height
```

In the future it may not be possible to require internal React Native modules directly based off of @providesModule (which is what allows for an un-namespaced `require('Dimensions')`)

**Comment by buhe** [comment]
Thank you!
