### ISSUE TITLE
Question: 'React/RCTBridgeDelegate.h' file not found

### ISSUE THREAD

**Issue by xclidongbo** [facebook/react-native#27446]
$ fastlane env
[✔] 🚀
[20:56:53]: fastlane detected a Gemfile in the current directory
[20:56:53]: However, it seems like you didn't use `bundle exec`
[20:56:53]: To launch fastlane faster, please use
[20:56:53]:
[20:56:53]: $ bundle exec fastlane env
[20:56:53]:
[20:56:53]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[20:56:56]: Generating fastlane environment output, this might take a few seconds...
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.1                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.23.0                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.1 (19B88)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.2.1                                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane


default_platform(:ios)

# 全局变量
Appfile_identifier = CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)
Appfile_apple_id = CredentialsManager::AppfileConfig.try_fetch_value(:apple_id)
Appfile_team_id = CredentialsManager::AppfileConfig.try_fetch_value(:team_id)

# info.plist path
INFO_PLIST_PATH = './WorkbenchApp/Info.plist'.freeze
OUTPUT_DIRECTORY = '../../ipas'.freeze
WORK_SPACE_FILE = 'WorkbenchApp.xcworkspace'.freeze
SCHEME_NAME = 'WorkbenchApp'.freeze
PROFILE_DEV = 'SUNCPECNM_dev'.freeze
PROFILE_DIT = 'SUNCPECNM_dist'.freeze

APPSTORE_INFO_PLIST_PATH = './WorkbenchAppStore-Info.plist'.freeze
APPSTORE_SCHEME_NAME = 'WorkbenchAppStore'.freeze
APPSTORE_PROFILE_DEV = 'sunshineJia_dev'.freeze
APPSTORE_PROFILE_DIT = 'sunshineJia_dist'.freeze

platform :ios do

  # before_all do |lane, options|
  #   # 一般用于git pull 或者cocoapods install等操作
  # end

  desc '根据参数进行打包'
  lane :buildExportIpa do |options|
    # environment
    # 指定配置
    # info plist path
    path = options[:info_path]
    configuration = options[:configuration]
    export_method = options[:method]
    # bundle_id = options[:bundle_id]
    # profile_name = options[:profile_name]
    workspace = options[:workspace]
    scheme = options[:scheme]

    puts(path)
    puts(configuration)
    puts(export_method)
    # puts(bundle_id)
    # puts(profile_name)
    puts(workspace)
    puts(scheme)

    # env ||= 'Debug'
    # create_time
    create_time = Time.new.strftime('%Y%m%d-%H%M')
    today = Time.new.strftime('%Y%m%d')
    # build increment
    # increment_build_number
    # version
    version_num = get_info_plist_value(
      path: path,
      key: 'CFBundleShortVersionString'
    )
    # build version
    build_version_num = get_info_plist_value(
      path: path,
      key: 'CFBundleVersion'
    )
    # ipaName = app_name + version_num + build_version_num + date
    bundle_name = get_info_plist_value(
      path: path,
      key: 'CFBundleDisplayName'
      # key: 'CFBundleName'
    )
    ipa_name = bundle_name + "_v#{version_num}" + "_b#{build_version_num}" + "_#{create_time}"

    # dSYM_name = output_directory + app_name + version_num + build_version_num + date
    if configuration == 'Debug'
      output_directory = OUTPUT_DIRECTORY + '/dev/' + today
    elsif configuration == 'Staging'
      output_directory = OUTPUT_DIRECTORY + '/stag/' + today
    else
      output_directory = OUTPUT_DIRECTORY + '/dit/' + today
    end
    dsym_name = "#{output_directory}/" + ipa_name
    # set env
    #   full_ipa_name = ipaName + "_Debug.ipa"
    #   dsym_file_name = dSYM_name + "_Debug.ipa"
    #   export_method = "development"
    full_ipa_name = ipa_name + "_#{configuration}.ipa"
    dsym_file_name = dsym_name + "_#{configuration}.app.dSYM.zip"

    # 指定构建App的配置

    # configuration = 'Release'
    # if env == 'Debug'
    #   export_method = 'development'
    #   export_profile = PROFILE_DEV
    # elsif env == 'Staging'
    #   export_method = 'enterprise'
    #   export_profile = PROFILE_DIT
    # else
    #   export_method = 'app-store'
    #   export_profile = PROFILE_DIT
    # end

    # check branch
    # ensure_git_branch(
    #   branch: 'dev'
    # )

    # build ipa
    # include_bitcode: true,
    #
    build_app(
      # workspace: WORK_SPACE_FILE,
      # scheme: SCHEME_NAME,
      workspace: workspace,
      scheme: scheme,
      configuration: configuration,
      silent: true,
      clean: true,
      include_symbols: true,
      output_directory: output_directory,
      output_name: full_ipa_name,
      export_options: {
        method: export_method,
        # provisioningProfiles: {
        #   # Appfile_identifier => export_profile
        #   bundle_id => profile_name
        # }
      }
    )
    # return ipa name
    full_ipa_name
  end

  desc '调试包'
  lane :ios_dev do
    # add actions here: https://docs.fastlane.tools/actions
    RNHandle()
    ipa_name = buildExportIpa(
      info_path: INFO_PLIST_PATH,
      configuration: 'Debug',
      method: 'development',
      # bundle_id: Appfile_identifier,
      # profile_name: PROFILE_DEV,
      workspace: WORK_SPACE_FILE,
      scheme: SCHEME_NAME
    )
    puts(ipa_name)
  end
  desc "测试包"
  lane :ios_test do |options|
    #add actions here
    RNHandle()
    ipa_name = buildExportIpa(
      info_path: INFO_PLIST_PATH,
      configuration: 'Staging',
      method: 'enterprise',
      # bundle_id: Appfile_identifier,
      # profile_name: PROFILE_DIT,
      workspace: WORK_SPACE_FILE,
      scheme: SCHEME_NAME
    )
    puts(ipa_name)
  end

  desc '企业包'
  lane :ios_etp do
    RNHandle()
    ipa_name = buildExportIpa(
      info_path: INFO_PLIST_PATH,
      configuration: 'Release',
      method: 'enterprise',
      # bundle_id: Appfile_identifier,
      # profile_name: PROFILE_DIT,
      workspace: WORK_SPACE_FILE,
      scheme: SCHEME_NAME
    )
    puts(ipa_name)
  end

  desc "打包前执行sh,更改三方源码"
  lane :RNHandle do |options|
    # build before
    sh('sh ./BeforeLane.sh')
  end

  desc "发布到fir.im"
  lane :ios_fir do
    ios_etp()
    firim(firim_api_token: '5235d1a45bb3db82072270bfe46b3afa')
  end

  desc "发布到appStore"
  lane :ios_appStore do |options|
    #add actions here
    RNHandle()
    ipa_name = buildExportIpa(
      info_path: APPSTORE_INFO_PLIST_PATH,
      configuration: 'Release',
      method: 'app-store',
      # bundle_id: Appfile_identifier,
      # profile_name: PROFILE_DIT,
      workspace: WORK_SPACE_FILE,
      scheme: APPSTORE_SCHEME_NAME
    )
    # upload_to_app_store
    # slack(message: "Successfully uploaded a new App Store build")
    puts(ipa_name)

  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address

app_identifier 'com.sinosig.SUNCPECNM'
apple_id '233140438@qq.com'
team_id 'LH28XA7T22'


for_platform :ios do
    # team_id '123' # for all iOS related things
    for_lane :ios_dev do
        app_identifier 'com.sinosig.SUNCPECNM'
        team_id 'LH28XA7T22'
    end
    for_lane :ios_test do
        app_identifier 'com.sinosig.SUNCPECNM'
        team_id 'LH28XA7T22'
    end
    for_lane :ios_etp do
        app_identifier 'com.sinosig.SUNCPECNM'
        team_id 'LH28XA7T22'
    end

    for_lane :ios_appStore do
        app_identifier 'com.sinosig.sunshineJia'
        team_id 'V6WA75SK4R'
    end
end


# app_store_identifier('com.sinosig.sunshineJia')
# app_team_id('V6WA75SK4R')

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.137.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                | Version | Update-Status |
| --------------------- | ------- | ------------- |
| fastlane-plugin-firim | 0.2.2   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.6        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.12.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.67.0       |
| faraday                   | 0.17.0       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 2.0.2        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.6        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2019.1009  |
| mime-types                | 3.3          |
| multi_json                | 1.14.1       |
| signet                    | 0.12.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.1        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.2.1        |
| google-cloud-core         | 1.3.1        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| firim                     | 0.2.2        |
| fastlane-plugin-firim     | 0.2.2        |
</details>

*generated on:* **2019-12-08**
</details>
[20:57:16]: Take notice that this output may contain sensitive information, or simply information that you don't want to make public.

**Comment by xclidongbo** [comment]
Debug and Release Can build successed. but custom configuration 'Staging' failed.

**Comment by xclidongbo** [comment]
0000

**Comment by KarenQiao** [comment]
same issue!!!,any update?
