### ISSUE TITLE
react-native start giving Invalid regular expression invalid error

### ISSUE THREAD

**Issue by Rananjaya** [facebook/react-native#27445]
React Native version:

## Steps To Reproduce

1.react-native start
2.react-native run-android

**Comment by Rananjaya** [comment]
I Fixed this issue 
go to 
node_modules\metro-config\src\defaults\blacklist.js and add this line of code

var sharedBlacklist = [
  /node_modules[\/\\]react[\/\\]dist[\/\\].*/,
  /website\/node_modules\/.*/,
  /heapCapture\/bundle\.js/,
  /.*\/__tests__\/.*/
];

**Comment by FMGordillo** [comment]
How is this a solution :c
