### ISSUE TITLE
Unable to center a View

### ISSUE THREAD

**Issue by crazo7924** [facebook/react-native#27468]
I have a custom Component wrapped with a View and set the wrapper View' s style as follows:
`<View style = {{
                    flex: 1,
                    justifyContent: 'center',
                    alignSelf: 'center',
                }}>
     <MyCustomComponent/>
</View>`

React Native version:

System:
    OS: Windows 10 10.0.18363
    CPU: (12) x64 AMD Ryzen 5 2600 Six-Core Processor
    Memory: 2.62 GB / 7.95 GB
  Binaries:
    Node: 10.17.0 - E:\IDEs\node-v10.17.0\node.EXE
    npm: 6.11.3 - E:\IDEs\node-v10.17.0\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 25, 26, 27, 28, 29
      Build Tools: 28.0.3, 29.0.0, 29.0.0, 29.0.0, 29.0.1, 29.0.2
      System Images: android-28 | Google Play Intel x86 Atom_64
      Android NDK: 20.1.5948944
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
## Steps To Reproduce

1. Try the stated code
2. Ctrl + S to live refresh 

Describe what you expected to happen:

The Component should get centered on the screen

Snack, code example, screenshot, or link to a repository:

The component is not visible but interactable. A screenshot won't help much.

**Comment by crazo7924** [comment]
Component contains few TextInputs. They are interactable

**Comment by crazo7924** [comment]
Tried on Expo. Works fine. But not on my Android phone (Samsung Galaxy A30)

**Comment by levibuzolic** [comment]
There's not enough information here to replicate the issue, typically the style object you've provided will work correctly for centering a view. 

Do you have an expo example?

Can you provide any more information about `MyCustomComponent` ?

Using the inspector or React Native Devtools can be useful for debugging layout issues. Alternatively could you add some borders or background colours to your views to get a better idea where the layout isn't behaving as expected?
