### ISSUE TITLE
Fast-refresh doesn't work with Typescript Interface

### ISSUE THREAD

**Issue by dunglamhawking** [facebook/react-native#27467]
I suddenly found something about Fast Refresh today. I have a file containing an interface called UserRepo, and another file containing a class HttpUserRepo implementing UserRepo. Then I imported HttpUserRepo into another file. Whenever I save changes in HttpUserRepo, the file depending on HttpUserRepo doesn't rerun. 

Then I change interface UserRepo to abstract class and make HttpUserRepo to extend it. Then, Fast Refresh works as expected. Am i missing something? I think the difference is what Typescript compiles to but not sure

React Native version: 0.61.5

## Steps To Reproduce

1. Create an interface called UserRepoInterface in a file called UserRepoInterface.ts
2. Create a class called HttpUserRepo implementing UserRepoInterface in a file called HttpUserRepo
3. Make some changes on HttpUserRepo and save to trigger Fast-refresh

Describe what you expected to happen:
Module importing HttpUserRepo should re-run and reflect HttpUserRepo changes

Snack, code example, screenshot, or link to a repository: https://github.com/dunglamhawking/rnovermindexample

**Comment by gaearon** [comment]
Can't get the project running. :-(

```
error: /Users/gaearon/p/rnovermindexample/ios/Pods/Target Support Files/Pods-RNOvermindExample/Pods-RNOvermindExample.debug.xcconfig: unable to open file (in target "RNOvermindExample" in project "RNOvermindExample") (in target 'RNOvermindExample' from project 'RNOvermindExample')
```

<img width="321" alt="Screen Shot 2019-12-11 at 2 00 01 PM" src="https://user-images.githubusercontent.com/810438/70627667-8ab5fa80-1c1e-11ea-874b-a277b891dd67.png">

**Comment by dunglamhawking** [comment]
> Can't get the project running. :-(
> 
> ```
> error: /Users/gaearon/p/rnovermindexample/ios/Pods/Target Support Files/Pods-RNOvermindExample/Pods-RNOvermindExample.debug.xcconfig: unable to open file (in target "RNOvermindExample" in project "RNOvermindExample") (in target 'RNOvermindExample' from project 'RNOvermindExample')
> ```
> 
> <img alt="Screen Shot 2019-12-11 at 2 00 01 PM" width="321" src="https://user-images.githubusercontent.com/810438/70627667-8ab5fa80-1c1e-11ea-874b-a277b891dd67.png">

Sorry for late reply! What is your XCode version? Mine is 10.2.
