### ISSUE TITLE
overflow: 'hidden' has wrong affect on scaleX and scaleY on Android 7.0 (API 24)

### ISSUE THREAD

**Issue by SaeedZhiany** [facebook/react-native#27480]
React Native version:
0.61.5

## Steps To Reproduce

I have created a [simple expo](https://snack.expo.io/@saeedzhiany/cb024c) to reproduce the problem but please **note** that the problem does not show up on Expo's emulator.

I have tested it on a few Android emulators with different API levels and some real devices and still no bug and currently, I'm not to test it on the IOS platform.

1. android emulator: API 19
2. android emulator: API 22
3. android emulator: API 23
4. android emulator: API 28
5. android device: LG K4, android version 5.1.1
5. android device: Samsung Galaxy J2, android version 5.1.1
5. android device: Huawei CUN-L21, android version 5.1

**I just could reproduce the bug on My LG Stylus 2 with android 7.0** so it's too hard to reproduce it, but it's a bug I think, a rare one. you can reproduce it on an Android emulator API 24 (android 7.0)

here are some results of playing with `overflow`, `scaleX`, and `scaleY` styles

| overflow  | scaleX  | scaleY | result |
| --- | ---- | ---- | ---- |
| visible |1|1|![Screenshot_2019-12-11-15-12-04](https://user-images.githubusercontent.com/13766432/70618681-b8a03c80-1c28-11ea-8481-2b2f9f2ee744.png)|
| visible |1.5|1.5|![Screenshot_2019-12-11-15-13-51](https://user-images.githubusercontent.com/13766432/70618772-e6858100-1c28-11ea-9927-f1f2f4020dba.png)|
| hidden |1|1|![Screenshot_2019-12-11-15-15-13](https://user-images.githubusercontent.com/13766432/70618867-12086b80-1c29-11ea-95cf-7bc3b3054619.png)|
| hidden |1.5|1|![Screenshot_2019-12-11-15-16-16](https://user-images.githubusercontent.com/13766432/70618953-382e0b80-1c29-11ea-94e5-ceebdb9570d7.png)|
| hidden |1|1.5|![Screenshot_2019-12-11-15-17-08](https://user-images.githubusercontent.com/13766432/70618998-585dca80-1c29-11ea-8a75-ffa122ac7512.png)|
| hidden |1.5|1.5|![Screenshot_2019-12-11-15-17-53](https://user-images.githubusercontent.com/13766432/70619042-70354e80-1c29-11ea-9e50-358be571ea6e.png)|
| | | | ![GIF-191211_174634](https://user-images.githubusercontent.com/13766432/70629818-cdd49580-1c3f-11ea-8244-82653e8751b4.gif)|

Describe what you expected to happen:
I expect that the View renders correctly in given scaleX or scaleY no matter what value of `overflow` is.

Snack, code example, screenshot, or link to a repository:

[Snack example](https://snack.expo.io/@saeedzhiany/cb024c)
but please try to run the example on a real device especially if you have **LG Stylus 2** or an Android emulator running API 24.

The only workaround I found is to remove `overflow: 'hidden'` style and modify my inner views styles to respect their parent's current style which is not good for maintenance.

update
--
in the case of the above snack example accidentally removed. I just copied the snack code here without any change.

```tsx
import * as React from 'react';
import { Text, View, StyleSheet } from 'react-native';

export default class App extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        <View style={styles.indicatorContainer}>
          <View style={styles.indicator} />
        </View>
        <View style={styles.textContainer}>
          <Text>some text</Text>
        </View>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    width: 120,
    height: 70,
    borderRadius: 5,
    borderWidth: 1.5,
    overflow: 'hidden',
    position: 'absolute',
    top: 200,
    left: 120,
    backgroundColor: '#FFFFFF',
    borderColor: '#ff7171',
    // play with scaleX and scaleY to see the bug
    scaleY: 1.5,
    scaleX: 1.5,
  },
  indicatorContainer: {
    flex: 0.65,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FDFFDB',
  },
  indicator: {
    width: 20,
    height: 20,
    borderRadius: 5,
    borderColor: '#000',
    borderWidth: 2,
  },
  textContainer: {
    flexDirection: 'row',
    flex: 0.35,
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```

**Comment by SaeedZhiany** [comment]
No one is interested in this issue?!

**Comment by chrisbobbe** [comment]
(I think the `Flow` label was misapplied by the bot; this has nothing to do with Flow type-checking.)

**Comment by safaiyeh** [comment]
Hi @SaeedZhiany apologies you are having issues. Thank you for the detailed issue and Snack! Adding the correct tags

**Comment by SaeedZhiany** [comment]
a

**Comment by SaeedZhiany** [comment]
Update:
I recently can reproduce it on an Android emulator running API 24 (Android 7).

**Comment by SaeedZhiany** [comment]
it's been 3 years now :))))

**Comment by SaeedZhiany** [comment]
Someone attentaions

**Comment by SaeedZhiany** [comment]
attention please :))))

**Comment by SaeedZhiany** [comment]
@safaiyeh is there any progress on this issue? it's been 3 years now :))))

if this bug has no priority maybe it needs to close it. I prevented @github-actions bot from closing this issue multiple times.
Thanks.
