### ISSUE TITLE
InputAccessoryView disappears after TextBox receives focus

### ISSUE THREAD

**Issue by zeevl** [facebook/react-native#27495]
The [docs](https://facebook.github.io/react-native/docs/inputaccessoryview) say,

>This component can also be used to create sticky text inputs (text inputs which are anchored to the top of the keyboard). To do this, wrap a TextInput with the InputAccessoryView component, and don't set a nativeID

However, if you do so, and a `TextInput` receives focus on the view, the `InputAccessoryView` disappears, and does not come back, even after blur or the keyboard is dismissed.

```
        <ScrollView style={styles.fill} keyboardDismissMode="interactive">
          <TextInput style={{marginTop: 100, borderStyle: 'solid', borderWidth: 1, height: 32}} placeholder="text box" />
        </ScrollView>        
        <InputAccessoryView backgroundColor="#fffffff7">
          <Button>Click me</Button>
        </InputAccessoryView>
```

React Native version:
```
System:
    OS: macOS 10.15.1
    CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
    Memory: 120.55 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.7.0 - /usr/local/bin/node
    Yarn: 1.19.2 - ~/.yarn/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 26, 27, 28
      Build Tools: 28.0.3
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
```

## Steps To Reproduce

1. Add a <TextInput> to a screen
2. Add a <InputAccessoryView> to the screen with no `nativeID`
3. Run the app
4. see the input accessory
5. focus on the `TextInput`

Result: view disappears
Expect: input accessory to remain

Snack, code example, screenshot, or link to a repository:
https://snack.expo.io/@geosteve/arrogant-soda

**Comment by niksudan** [comment]
I'm having this issue with this component too.
