### ISSUE TITLE
[Android][Networking]Does react-native-android handle json responses? I got a response with `null` body

### ISSUE THREAD

**Issue by trave7er** [facebook/react-native#2749]
Hi there, 

I just tried to run my app on Android today. When I am calling our api, instead of getting a response with json payload in the response body, I got a `null` body, a responseText field with stringified json, status code **200**, and content-type `null`. The same code works for iOS, though.

I checked the **java** code, and there is a [TODO(5472580) handle headers properly](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/modules/network/NetworkingModule.java#L183) in `NetworkingModule.java`, not sure if it is related to my issue.

I know basic java, and would love to help if anyone can point me to the right direction, either on solving my issue or fixing a bug.

Thank you very much,

Huang

**Comment by foghina** [comment]
You can just do `JSON.parse(responseText)` for now.

**Comment by trave7er** [comment]
Any updates or time frame for this to be updated? Thanks, Huang

**Comment by trave7er** [comment]
Here is a PR addressed to this issue: [#3062](https://github.com/facebook/react-native/pull/3062)
