### ISSUE TITLE
Can not execute react-native run-android

### ISSUE THREAD

**Issue by jdgalani** [facebook/react-native#27501]
FAILURE: Build failed with an exception.

* Where:
Script 'C:\JD\Projects\react-native\versionDemo\node_modules\@react-native-community\cli-platform-android\native_modules.gradle' line: 200

* What went wrong:
A problem occurred evaluating script.
> Failed to parse React Native CLI configuration. Expected running 'npx.cmd --quiet --no-install react-native config' command from 'C:\JD\Projects\react-native\versionDemo' directory to output valid JSON, but it didn't. This may be caused by npx resolving to a legacy global react-native binary. Please make sure to uninstall any global 'react-native' binaries: 'npm uninstall -g react-native react-native-cli' and try again

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s

error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
:ReactNative:Failed to parse React Native CLI configuration: groovy.json.JsonException: Unable to determine the current character, it is not a string, number, array, or object

The current character read is 'C' with an int value of 67
Unable to determine the current character, it is not a string, number, array, or object
line number 1
index number 0
C:\JD\Projects\react-native\versionDemo\node_modules\react-native\cli.js{  "root": "C:\\JD\\Projects\\react-native\\versionDemo",  "reactNativePath": "C:\\JD\\Projects\\react-native\\versionDemo\\node_modules\\react-native",  "dependencies": {},  "commands": [    {      "name": "log-ios",      "description": "starts iOS device syslog tail"    },    {      "name": "run-ios",      "description": "builds your app and starts it on iOS simulator",      "examples": [        {          "desc": "Run on a different simulator, e.g. iPhone 5",          "cmd": "react-native run-ios --simulator \"iPhone 5\""        },        {          "desc": "Pass a non-standard location of iOS directory",          "cmd": "react-native run-ios --project-path \"./app/ios\""        },        {          "desc": "Run on a connected device, e.g. Max's iPhone",          "cmd": "react-native run-ios --device \"Max's iPhone\""        },        {          "desc": "Run on the AppleTV simulator",          "cmd": "react-native run-ios --simulator \"Apple TV\"  --scheme \"helloworld-tvOS\""        }      ], 
..
..
..     
..//omiting some of the lines
..
..
..
"C:\\JD\\Projects\\react-native\\versionDemo\\android\\app\\src\\main\\AndroidManifest.xml",      "buildGradlePath": "C:\\JD\\Projects\\react-native\\versionDemo\\android\\app\\build.gradle",      "settingsGradlePath": "C:\\JD\\Projects\\react-native\\versionDemo\\android\\settings.gradle",      "assetsPath": "C:\\JD\\Projects\\react-native\\versionDemo\\android\\app\\src\\main\\assets",      "mainFilePath": "C:\\JD\\Projects\\react-native\\versionDemo\\android\\app\\src\\main\\java\\com\\versiondemo\\MainApplication.java",      "packageName": "com.versiondemo"    }  }}
^

FAILURE: Build failed with an exception.

* Where:
Script 'C:\JD\Projects\react-native\versionDemo\node_modules\@react-native-community\cli-platform-android\native_modules.gradle' line: 200

* What went wrong:
A problem occurred evaluating script.
> Failed to parse React Native CLI configuration. Expected running 'npx.cmd --quiet --no-install react-native config' command from 'C:\JD\Projects\react-native\versionDemo' directory to output valid JSON, but it didn't. This may be caused by npx resolving to a legacy global react-native binary. Please make sure to uninstall any global 'react-native' binaries: 'npm uninstall -g react-native react-native-cli' and try again

* Try:Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s

    at checkExecSyncError (child_process.js:601:13)
    at execFileSync (child_process.js:621:13)
    at runOnAllDevices (C:\JD\Projects\react-native\versionDemo\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:94:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

React Native version:
System:
    OS: Windows 10 10.0.16299
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 2.82 GB / 7.90 GB
  Binaries:
    Node: 8.11.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 5.6.0 - C:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 19, 21, 22, 23, 24, 25, 26, 27, 28, 29
      Build Tools: 19.1.0, 21.1.2, 22.0.1, 23.0.1, 23.0.3, 24.0.3, 25.0.1, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.1, 28.0.2, 28.0.3, 29.0.2
      System Images: android-25 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5900203
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5

## Steps To Reproduce

1. create new project with : react-native init demo

2. execute in project directory : react-native run-android

on windows machine only..

Describe what you expected to happen:

Tried searching on SO and github community, but coudn't find right solution.

Thanks for helping...

**Comment by KoratParas** [comment]
Facing same issue @jdgalani

**Comment by abhishekSutariya** [comment]
I am also facing the same issue.

**Comment by msf26** [comment]
a have this problem too ....

**Comment by Demonjsj** [comment]
me too .... Who has a solution

**Comment by Demonjsj** [comment]
“Node: 8.11.3 - C:\Program Files\nodejs\node.EXE”
your need update node.js

**Comment by builtbyproxy** [comment]
I don't doubt you've removed global `react-native` installations and such, however along with that ensure you search across multiple nvm verions. I had a similar bug as discussed here: https://github.com/react-native-community/cli/pull/831

The error was I had a specific `nvm` running in my project which had a globally installed `react-native` package.

If you want to be certain, copy my code from that PR linked above and then patch-package `react-native` to collect config from root. If it's working after this then you should know to look for globals across your node versions

**Comment by Donkey-Kurt** [comment]
me too,
and while i run `react-native doctor`,
i found error ` Android SDK - Required for building and installing your app on Android`
bug actually, i have a 26.0.x sdk

![image](https://user-images.githubusercontent.com/15633802/71708843-e2ffa700-2e2e-11ea-94dc-fd464d58dcf1.png)

my sdk list  as below  ↓↓↓

![image](https://user-images.githubusercontent.com/15633802/71708858-fd398500-2e2e-11ea-924f-3eb678383d16.png)
![image](https://user-images.githubusercontent.com/15633802/71708864-0591c000-2e2f-11ea-882a-12764f9ba07e.png)
![image](https://user-images.githubusercontent.com/15633802/71708885-16dacc80-2e2f-11ea-80f4-6ea127d87d18.png)

**Comment by Donkey-Kurt** [comment]
@jdgalani 
i found solution.

remove your sdk build-tools
![image](https://user-images.githubusercontent.com/15633802/71709565-e4cb6980-2e32-11ea-9299-01322a23ef3b.png)

and run command again.......

but i dont know why

**Comment by jdgalani** [comment]
@Demonjsj yes updating node had resolved my issue. but i dont know why it is not working for node 8.x.x.
