### ISSUE TITLE
[Android][Flatlist][Horizontal] Last item delete in horizontal flatlist does not adjust scroll position.

### ISSUE THREAD

**Issue by jayshah123** [facebook/react-native#27504]
React Native version: 0.59.10

![output](https://user-images.githubusercontent.com/659202/70800493-6dc22880-1dd2-11ea-8a43-66e87ba867d9.gif)

## Steps To Reproduce

```
export default class App extends Component<Props> {

  constructor(props) {
    super(props);
    this.dataItems = [{
      id: 1,
      text: 'one'
    },{
      id: 2,
      text: 'two'
    },{
      id: 3,
      text: 'three'
    }, {
      id: 4,
      text: 'four',
    }, {
      id: 5,
      text: 'five'
    }];
  }

  removeItem = (id) => {
    this.dataItems = this.dataItems.filter((item) => item.id !== id);
    this.setState({});
  };

  renderItem = ({item}) => {
    return (
      <View style={{ width: 140, height: 140, backgroundColor: 'yellow', margin: 10}}>
        <Text>{item.text}</Text>
        <TouchableOpacity onPress={() => {
          this.removeItem(item.id);
        }}>
          <Text>{'Remove me'}</Text>
        </TouchableOpacity>
      </View>
    )
  };

  render() {
    return (
      <View style={styles.container}>
        <View style={{height: 140, width: '100%'}}>
          <FlatList
            horizontal
            data={this.dataItems}
            renderItem={this.renderItem}
            keyExtractor={item => `${item.id}`}
          />
        </View>
      </View>
    );
  }
}

```
Describe what you expected to happen:
After removing last item, scroll position should be adjusted.

Snack, code example, screenshot, or link to a repository:

**Comment by jayshah123** [comment]
This problem will most likely also be present on the latest version from the code it seems.

**Comment by jayshah123** [comment]
The fix can be simple: add a hierarchy change + layout change listener, which does a `scrollTo` whenever we have scrolled beyond capacity post an item removal. This is already present in ReactScrollView.

**Comment by Peeeep** [comment]
Thank you, kind little bot, but this still needs a fix :/

**Comment by alexeyvax** [comment]
I would suggest to use scrollToEnd(), but anyway you need to know screen width and each item width. In case you have two or only one item in your list, you will need to use scrollToIndex({ index: 0 }) instead

**Comment by jayshah123** [comment]
The PR (https://github.com/facebook/react-native/pull/27514) has the exact fix for Horizontal Scroll View which is already present in vertical scrollview in production/master since a long time.

**Comment by jayshah123** [comment]
latest pr is https://github.com/facebook/react-native/pull/28977

**Comment by bboure** [comment]
I am facing this issue too. Any workaround while waiting for the fix?

**Comment by Klescouar** [comment]
Up ! Same problem on my side...

**Comment by sanduluca** [comment]
I have the same problem with **react-native 0.64.2** 😕

**Comment by victoralmeidadev** [comment]
Same problem here.

A workaround while waiting fix: use scrollToEnd when removing the last item.

**Example:** 

```typescript
import React, { useState, useRef, useCallback } from "react";
import { FlatList } from "react-native";

function ExampleComponent() {
  const [items, setItems] = useState<[]>([]);
  const flatListRef = useRef<FlatList>();

  const handleRemoveFlatListItem = useCallback(
    (index: number) => {
      const canScrollToEnd = index === items.length - 1;
      const newItems = [...items] as [];
      newItems.splice(index, 1);
      setItems([...newItems]);
      if (flatListRef?.current && canScrollToEnd)
        flatListRef.current.scrollToEnd();
    },
    [items, flatListRef]
  );

  const renderItem = ...

  return (
    <FlatList
      horizontal
      data={items}
      renderItem={renderItem}
      keyExtractor={(item) => `${item.id}`}
    />
  );
}
```

**Comment by Michaeliaaa** [comment]
Same problem here, hope it get fixed soon.

**Comment by wangliang1124** [comment]
Same problem on 0.63.4

**Comment by Lisergishnu** [comment]
Same problem on 0.67.4

**Comment by xhirazi** [comment]
+1

**Comment by mbezard** [comment]
I have this issue on 0.67.4, but with a scrollview like:
```
<ScrollView>
    {array.map((item) => (
        <Item onPress={() => removeItem(item.id)} key={item.id} />
    )}
</ScrollView>
```

**Comment by fabriziobertoglio1987** [comment]
<details><summary>Branch - Last item delete in horizontal flatlist does not adjust scroll position.</summary>
<p>


Test case documents PR https://github.com/facebook/react-native/pull/34141

<video src="https://user-images.githubusercontent.com/24992535/177932116-755955a4-42eb-46d3-8229-35da255515a6.mov" width="1000" />

<details><summary>sourcecode example</summary>
<p>


```javascript
import React from "react";
import {
  SafeAreaView,
  View,
  FlatList,
  StyleSheet,
  Text,
  StatusBar,
  Button,
} from "react-native";

const DATA = [
  {
    id: "bd7acbea-c1b1-46c2-aed5-3ad53abb28ba",
    title: "First Item",
  },
  {
    id: "3ac68afc-c605-48d3-a4f8-fbd91aa97f63",
    title: "Second Item",
  },
  {
    id: "58694a0f-3da1-471f-bd96-145571e29d72",
    title: "Third Item",
  },
  {
    id: "bd7acbea-c1b1-46c2-aed5-3ad53abb8bbb",
    title: "Fourth Item",
  },
  {
    id: "3ac68afc-c605-48d3-a4f8-fbd91aa97676",
    title: "Fifth Item",
  },
  {
    id: "58694a0f-3da1-471f-bd96-145571e27234",
    title: "Sixth Item",
  },
  {
    id: "58694a0f-3da1-471f-bd96-145571e29234",
    title: "Seven Item",
  },
  {
    id: "58694a0f-3da1-471f-bd96-145571429234",
    title: "Eight Item",
  },
  {
    id: "58694a0f-3da1-471f-bd96-115571429234",
    title: "Nine Item",
  },
  {
    id: "58694a0f-3da1-471f-bd96-1155h1429234",
    title: "Ten Item",
  },
];

const Item = ({ title }) => (
  <Text style={[styles.item, styles.title]}>{title}</Text>
);

const renderItem = ({ item }) => <Item title={item.title} />;
const ITEM_HEIGHT = 50;

const renderFlatList = ({ item }) => (
  <NestedFlatList item={item} />
);

function NestedFlatList(props) {
  const [items, setItems] = React.useState(DATA);
  return (
    <View>
      <Button
      title="add an item"
      onPress={() => setItems([...items, {title: 'new item'}])}
      />
      <Button
        title="remove an item"
        onPress={() => {
          const newItems = [...items];
          newItems.splice(items.length - 1, 1)
          setItems(newItems);
        }}
      />
      <Text>Flatlist</Text>
      <FlatList
        horizontal={true}
        style={{height: 400}}
        inverted={true}
        renderItem={renderItem} data={items} />
    </View>
  )
}

const FlatList_nested = () => {
  let flatlist = React.useRef(0);
  return (
    <FlatList
      ref={(ref) => flatlist = ref}
      data={[1,2,3]}
      renderItem={renderFlatList}
      keyExtractor={(item) => item.toString()}
    />
  );
};

const styles = StyleSheet.create({
  item: {
    backgroundColor: "#f9c2ff",
    padding: 20,
    marginVertical: 8,
    marginHorizontal: 16,
  },
  title: {
    fontSize: 16,
  },
});

export default ({
  title: 'Nested',
  name: 'nested',
  description: 'nested FlatList',
  render: () => <FlatList_nested />,
}: RNTesterModuleExample);
```

</p>
</details>

</p>
</details>

**Comment by fabriziobertoglio1987** [comment]
<details><summary>Main - Last item added/deleted in vertical flatlist does not adjust scroll position.</summary>
<p>

<video src="https://user-images.githubusercontent.com/24992535/178283738-194b36af-3e59-4a89-b665-9886620a8166.mov" width="1000" />

</p>
</details>

**Comment by kneza23** [comment]
same problem on Android on 0.71.3

**Comment by jayshah123** [comment]
Will re raise the fix after taking a look at source once again.

**Comment by stuckj** [comment]
So...I see this is closed, but it's still broken. Is there another thread where it's not closed?

**Comment by stuckj** [comment]
Given this is unfixed after 3 years I just went with a workaround. :-P

In my case I'm not explicitly removing an item from a list, but rather getting updated data from an API call which could change the data in a horizontal list. If viewing the last item when this happens it will exhibit this behavior. And since I don't explicitly know that the last item was removed (or any item to make the list shorter I guess) I just went with a more brute force approach.

I store the current content offset by observing `onScrollEndDrag` and `onMomentumScrollEnd`. And I added an `onContentSizeChange` callback to check for when the width changes (i.e., and item was removed). I also know the width of the items by measuring them when the items layout (if your item widths vary this would be more complicated). Finally, in a useEffect, if contentOffset + itemWidth > contentWidth then I know I've hit a case where this bug has happened and I'm showing past the end of the scrollview. If that is true, then call `scrollToEnd` (without animation in my case) on a reference to the list.

Bit of a pain, but not too bad and works for me.

**Comment by sergeyzhukov** [comment]
still broken

**Comment by usmansbk** [comment]
sigh!

**Comment by ashwinmridul** [comment]
call `FlatListRef.scrollToEnd()` inside `onEndReached` handler of FlatList to scroll to end whenever you reach to the end because of dynamically remove any item.

Can do more optimisations to restrict not calling this scrollToEnd forcefully everytime.

**Comment by Bezaatay** [comment]
`<FlatList
    ref={flatListRef}
    onEndReached={() => {
        if (Platform.OS === 'android') flatListRef.current.scrollToEnd();
    }}
/>`

**Comment by Bezaatay** [comment]
`<FlatList
    ref={flatListRef}
    onEndReached={() => {
        if (Platform.OS === 'android') flatListRef.current.scrollToEnd();
    }}
/>`
