### ISSUE TITLE
[Meta] Github issue bot for cc'ing people on pull requests

### ISSUE THREAD

**Issue by brentvatne** [facebook/react-native#2751]
- New pull request is created
- Bot is pinged by webhook
- Looks at PR lines changed -- picks out the three most common people who appear in the git blame
- Add a "cc @each-of-their-names" comment to the pull request

**Comment by grabbou** [comment]
Ha, this indeed would be super handy for other projects as well.

**Comment by christopherdro** [comment]
@brentvatne Closing this out since we have that feature now.
