### ISSUE TITLE
JS server closed immediately!

### ISSUE THREAD

**Issue by sajaddp** [facebook/react-native#27516]
Hi,
I want to use react-native on windows 10 that is new installed,
So i flow all instructions on [https://facebook.github.io/react-native/docs/getting-started](https://facebook.github.io/react-native/docs/getting-started) (React Native CLI Quickstart).

But when i use `npx react-native run-android` the `JS server` closed immediately!

How can i solve it?

My system info:
```
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-4810MQ CPU @ 2.80GHz
    Memory: 9.97 GB / 15.88 GB
  Binaries:
    Node: 13.3.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.21.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 19, 23, 26, 27, 28, 29
      Build Tools: 23.0.1, 26.0.3, 27.0.3, 28.0.3, 29.0.2
      System Images: android-28 | Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: Version  3.5.0.0 AI-191.8026.42.35.6010548
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
```

**Comment by gokhandoslu** [comment]
I think this is not an issue about react-native, please search it on stackoverflow first.
Did you check port 8081 is already in use? 
Can you share any log about the error?

**Comment by ajinkyabhosale85** [comment]
I'm having the same issue!
This is the error that shows
![image](https://user-images.githubusercontent.com/58915063/70867025-99fab800-1f3e-11ea-9a05-9f1c3189d0f3.png)

![image](https://user-images.githubusercontent.com/58915063/70867022-949d6d80-1f3e-11ea-84f4-56ea7520f583.png)
 up in cmd
React-Native version:0.61.5

**Comment by gokhandoslu** [comment]
This is an issue about metro-config. I think it has been fixed by this commit
https://github.com/facebook/metro/commit/7c6f30b592b2fb23cee55b54f1aa4b7a522dec18

metro-config version in @react-native-community/cli should be updated to fix this issue.
You can follow this issue from https://github.com/react-native-community/cli/issues/853

**Comment by ajinkyabhosale85** [comment]
I'm actually super new to React-Native and this was my first attempt to set up the server. Can u pls clarify the specific steps I am supposed to take. React-Native version: 0.61.5 plus I also followed every step showed on the get started in React-Native page.

**Comment by gokhandoslu** [comment]
Until the pull request (https://github.com/react-native-community/cli/pull/864) merged, you can try a workaround below but I am not sure if it will work.

- open `node_modules/metro-config/src/defaults/blacklist.js`
- update its content with this one: https://github.com/facebook/metro/blob/7c6f30b592b2fb23cee55b54f1aa4b7a522dec18/packages/metro-config/src/defaults/blacklist.js
- run `npx react-native run-android`

Please provide a feedback on whether the solution works or not

**Comment by ajinkyabhosale85** [comment]
Thank you! This alternative worked. I put [] brackets around the \/ in the first line, but I don't know if not putting them works.
var sharedBlacklist = [
  /node_modules[\/]react[\/]dist[\/].*/,
  /website\/node_modules\/.*/,
  /heapCapture\/bundle\.js/,
  /.*\/__tests__\/.*/,
];
