### ISSUE TITLE
could not connect to development server

### ISSUE THREAD

**Issue by jiteshstack** [facebook/react-native#27524]
React Native version:

## Steps To Reproduce

1. Even i have done all things from my side, like reserver tcp:8081, remove node_module and install
2. I have checked Airplane mode and checked adb list in which device name is showing too.

Thanks in advance!!

**Comment by ExitTrance** [comment]
Check out this Issue comment [here](https://github.com/facebook/react-native/issues/27516#issuecomment-565841536).

The outlined steps work perfectly for me.

**Comment by xgAnd** [comment]
save error.
android phone and development server is in same wifi network.
![92174CFD-2C3F-4555-A68E-202C874A0311](https://user-images.githubusercontent.com/27660602/71228822-5f1dc900-231e-11ea-8941-caa7f45d21fc.png)
click the development server address can connect.
adb devices can show the phone
![F07FACD5-941F-4430-8A9B-68F2BB9E60AC](https://user-images.githubusercontent.com/27660602/71228874-8c6a7700-231e-11ea-9946-ace24045bede.png)
Airplane Mode is disabled
![98EE7980-A246-47B2-983E-6086B900766E](https://user-images.githubusercontent.com/27660602/71229596-1d425200-2321-11ea-83c3-c72da7ba3934.png)
"react": "16.9.0",
 "react-native": "0.61.4",
mac  10.14.6
how can fix this. thanks
