### ISSUE TITLE
How to change the ButtonIcon in NavigatorIOS?

### ISSUE THREAD

**Issue by yangaqi** [facebook/react-native#2752]
<NavigatorIOS
        initialRoute={{
          component: LiveResult,
          title: 'My View Title',
          leftButtonIcon: require('image!xxx'),
          onLeftButtonPress:() => {
            console.log('change leftButtonIcon!');
          },
          rightButtonIcon: require('image!xxx'),
          onRightButtonPress: () => {
            console.log('change rightButtonIcon!');
          },
        }}
        tintColor="#FFFFFF"
        barTintColor='#C2185B'
        titleTextColor="#FFFFFF" />

**Comment by brentvatne** [comment]
Hi there,

This type of question is best suited for StackOverflow - we use Github to track bugs and feature requests.

Good luck!
:rocket: :guitar:

**Comment by yangaqi** [comment]
oh..................... NavigatorIOS can not change the leftButtonIcon or rightButtonIcon!  in a page i can not change current navigatorIOS item  leftButtonIcon or rightButtonIcon. 


i solve it like this: hide the NavigatorIOS and use a custom navigatorbar  in each page top
