### ISSUE TITLE
Server-closes-shortly-after-opened

### ISSUE THREAD

**Issue by ajinkyabhosale85** [facebook/react-native#27520]
React Native version:0.61.5

## Steps To Reproduce

1.Craete a server 
2.Start it: expo start

Describe what you expected to happen: Expected not to crash/ work perfectly

Snack, code example, screenshot, or link to a repository:
![image](https://user-images.githubusercontent.com/58915063/70866896-315f0b80-1f3d-11ea-8545-2513b5453235.png)

**Comment by gokhandoslu** [comment]
Duplicate of #27516
