### ISSUE TITLE
[iOS]Random white screen on launch

### ISSUE THREAD

**Issue by damandeepsingh93** [facebook/react-native#27531]
We are getting the random white screen issue on app launch. It tries to start the "Splash" component but gets stuck on white screen. Its very random. Happens only on iOS.

React Native version:
System:
    OS: macOS 10.15.1
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 72.43 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 11.14.0 - /usr/local/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.13.1 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 11.3/11C24b - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-create-library: 3.1.2

## Steps To Reproduce
Very Random on Launch

## Describe what you expected to happen:
Shouldnt get stuck on Launch

I am attaching the video and logs along with it
[ios_white_screen_issue(1).log](https://github.com/facebook/react-native/files/3968274/ios_white_screen_issue.1.log)

Gif:
![ios_white_screen_small](https://user-images.githubusercontent.com/58249749/71063600-0110aa80-2193-11ea-998b-ac10ab3b5440.gif)

**Comment by avichopra1989** [comment]
I am facing the same issue. Can somebody provide a resolution for this?

**Comment by JonathanVegasP** [comment]
I am facing the same issue. I have to deploy to the app store, can somebody provide a resolution for this situation?

**Comment by damandeepsingh93** [comment]
Any update, Can somebody please look into this. 
Even tried using RAM bundles.

**Comment by HardikDhanani** [comment]
I am facing the same issue. Any update?

**Comment by narendraitservice** [comment]
same issue.

**Comment by glintpursuit** [comment]
@HardikDhanani @narendraitservice @JonathanVegasP @avichopra1989 

Try Below 

https://facebook.github.io/react-native/docs/running-on-device#pro-tip

// Place this code after "[self.window makeKeyAndVisible]" and before "return YES;"
UIView* launchScreenView = [[[NSBundle mainBundle] loadNibNamed:@"LaunchScreen" owner:self options:nil] objectAtIndex:0];
launchScreenView.frame = self.window.bounds;
rootView.loadingView = launchScreenView;
