### ISSUE TITLE
Android keyboard disappears when TextInput is behind the keyboard area

### ISSUE THREAD

**Issue by ericdevries** [facebook/react-native#27537]
When you have a FlatList with regular View's, but upon clicking a View (or touchable) they become TextInput elements, the keyboard won't properly show for items that are below the next keyboard position. Please see attached GIF for an example

![Kapture 2019-12-16 at 22 08 01](https://user-images.githubusercontent.com/817612/70943234-ac651680-2050-11ea-8b5b-acc6de5f8457.gif)

React Native version:

```
info Fetching system and libraries information...
System:
    OS: macOS 10.15.1
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 713.34 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.3.0 - /usr/local/bin/node
    Yarn: 1.19.2 - /usr/local/bin/yarn
    npm: 6.13.2 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 26, 27, 28, 29
      Build Tools: 28.0.3, 29.0.0
      System Images: android-24 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

## Steps To Reproduce

1. Copy code below into a standard project
2. Tap on one of the items on the lower part of the screen (no need to scroll)
3. Witness keyboard popping up as expected but then closing immediately 

Describe what you expected to happen:
I expect the keyboard to appear and the content to be resized so the bottom of the list is still visible, or at the very least have the focussed input element to be scrolled up above the keyboard

Snack, code example, screenshot, or link to a repository:

```
import React from "react";
import { FlatList, KeyboardAvoidingView, StyleSheet, Text, TextInput, TouchableNativeFeedback, View } from 'react-native';


class TestBrokenStuff extends React.PureComponent {
    public state = {
        searchResults: [],
        editting: null,
    };

    public componentDidMount() {
        const items = [];

        for (let i = 0; i < 100; ++i) {
            items.push('item ' + i);
        }

        this.setState({
            searchResults: items
        });
    }

    public onEdit = (id) => {
        this.setState({
            editting: id,
        });
    };

    public renderTagItem = ({ item }) => {
        return (
            <View style={styles.item}>
                {item === this.state.editting && (
                    <TextInput
                        value={item}
                        autoFocus
                    />
                )}

                {item !== this.state.editting && (
                    <TouchableNativeFeedback onPress={() => this.onEdit(item)}>
                        <Text>{item}</Text>
                    </TouchableNativeFeedback>
                )}
            </View>

        );
    };

    public keyExtractor = (item) => {
        return item;
    };

    public render() {
        const { searchResults } = this.state;

        return (
            <View>
                <KeyboardAvoidingView>
                    <FlatList
                        data={searchResults}
                        renderItem={this.renderTagItem}
                        keyExtractor={this.keyExtractor}
                        keyboardShouldPersistTaps="handled"
                        extraData={this.state.editting}
                    />
                </KeyboardAvoidingView>
            </View>

        );
    }

}

export default TestBrokenStuff;

const styles = StyleSheet.create({
    item: {
        height: 32
    },
});

```

**Comment by ericdevries** [comment]
I have added the missing information

**Comment by slalom-mike** [comment]
I ran into this bug and what seems to be happening is related to the keyboardDismissMode functionality. When the keyboard first appears, the input goes out of the view, and when keyboardDismissMode is set to 'on-drag' that triggers the closing of the keyboard. The order of operations there needs to change so that it's not checking whether the input is out of view before it's had a chance to reposition everything for 'on-drag' to be usable. To avoid this, it currently needs to be 'none'.
What makes this even more difficult is that FlatList doesn't seem to be passing the keyboardDismissMode prop to it's underlying ScrollList - I've had to create a FlatList alternative that does honor this prop to even use this workaround.

**Comment by falxcerebri** [comment]
Yeah, my team also faced this issue. Kinda annoying. We've placed a workaround by wrapping `TouchableOpacity` in `<ScrollView keyboardDismissMode='none' scrollEnabled={false}>`, but that's dirty.

**Comment by falxcerebri** [comment]
Oh don't worry, if author cannot provide details my team will. I'll just ask a guy who crashed against this.

**Comment by ericdevries** [comment]
I gave a complete and simple bit of code that demonstrates the issue, what else do you need?

**Comment by kesha-antonov** [comment]
Same issue!

**Comment by kesha-antonov** [comment]
@falxcerebri 

Your hack worked! Thanks!

I wrapped FlatList in ```<ScrollView keyboardDismissMode='none'>```

**Comment by fabriziobertoglio1987** [comment]
I can not run your example.

**Comment by 2333Ge** [comment]
Flast add  removeClippedSubviews={false}

**Comment by safaiyeh** [comment]
We have a few solutions here:

> Yeah, my team also faced this issue. Kinda annoying. We've placed a workaround by wrapping `<TouchableOpacity>` in `<ScrollView keyboardDismissMode='none' scrollEnabled={false}>`, but that's dirty.
@falxcerebri

> Flast add removeClippedSubviews={false}
@2333Ge 

Have these solved the issue you were having @ericdevries

**Comment by falxcerebri** [comment]
Nah, I don't think it was fixed.

**Comment by route33software** [comment]
This problem persist, and I found the solution in this line:
`Flast add removeClippedSubviews={false`
@2333Ge 

Thanks all for this Discussion.

**Comment by plasmarob** [comment]
Same issue, took a lot to find this one. Adding the attribute `removeClippedSubviews={false}` to FlatList does indeed fix it.

**Comment by gfmoore** [comment]
None of these fixed my case. What exactly is causing the keyboard to disappear the first time I click into a TextInput, but be okay the second time I click into it?

Basically I have 
```
return (
  <View>
    <Flatlist

    />

    <View>
      <TextInput

      />
      <TouchableOpacity><Text> </Text></TouchableOpacity>
    </View>
    <Text></Text>
  </View>
)
```
![image](https://user-images.githubusercontent.com/22768967/133897939-921d0c5a-f8f5-4d4a-8271-a0dedd85f4f2.png)

Should be pretty straightforward surely? Click on the text input, up comes the keyboard. No reason for it to disappear the first time, but then be okay (but have same issue if navigate away and return).

**Comment by gfmoore** [comment]
Uhmmm, just noticed that I get to this screen by navigating from the maps screen? (That's why it shows an underline under maps), but it's actually the same screen as the Tracks tab screen. That then works fine.

(Sorry, don't know how to change the size of the image. I'll upload a smaller one.)

**Comment by digholesnehal** [comment]
Please do not add Math.random() as your key, that causes this issue in the Flatlist or when you're mapping an array and using TextInput  inside of it.
Provide a unique and static key which will remain same even after rerendering of an element.

I noticed the above issue and following above steps solved it.

**Comment by afj95** [comment]
> Flast add removeClippedSubviews={false}
@2333Ge 
this worked for me bet there is a note from reac-native said:
**Note: may have bugs (missing content) in some circumstances - use at your own risk.**

Do you have any idea about this note ?
