### ISSUE TITLE
zIndex is not working on android

### ISSUE THREAD

**Issue by ngdlmk** [facebook/react-native#27548]
zIndex is not working on android but it is working well on IOS. 
RN 0.61.5

**Comment by kubilaykiymaci** [comment]
Hi @ngdlmk,

you should use elevation on android.

from react native docs:

**elevation**
(Android-only) Sets the elevation of a view, using Android's underlying elevation API. This adds a drop shadow to the item and affects z-order for overlapping views. Only supported on Android 5.0+, has no effect on earlier versions.

**Comment by ngdlmk** [comment]
Hey @kubilaykiymaci thanks for the answer as you said elevation is working but there is an other problem if I use touchableopacity and if it is overlapping to a view it is being unclickable. 

`<TouchableOpacity 
          onPress={() => alert("oonon")} 
          style={{
            position: 'absolute', 
            top:0 , 
            left: 0, 
            elevation: 3,
            zIndex: 4,
            backgroundColor: 'red', 
            width: 200, 
            height: 200
          }}></TouchableOpacity>
        <View 
          style={{
            position: 'absolute', 
            top:100 , 
            left: 100, 
            zIndex: 1, 
            elevation: 2,
            backgroundColor: 'black', 
            width: 200, 
            height: 200
          }}></View>`

**Comment by kubilaykiymaci** [comment]
@ngdlmk  elevation should be 1 higher than zIndex. that's why your elevation should be 5.

**Comment by ngdlmk** [comment]
@kubilaykiymaci I replaced the code like this but touchable opacity still unclickable
``
<TouchableOpacity 
        onPress={() => alert("hello")}
        style={{
          width: 200,
          height: 200,
          backgroundColor: 'red',
          position: 'absolute',
          elevation: 3,
          zIndex: 2
        }}></TouchableOpacity>
      <View style={{
          width: 200,
          height: 200,
          backgroundColor: 'black',
          position: 'absolute',
          elevation: 2,
          zIndex: 1
        }}></View>
``

**Comment by kubilaykiymaci** [comment]
i can't say anything then. i should see your code and style file. maybe you have a another transparent layer which is infront of your touchable. maybe you have a container which has higher zIndex and background color transparent. but i know that zIndex and elevation works on android, i used it in my project.

**Comment by arberK** [comment]
I have the same problem only on android. In my case, a want to dynamically change the ordering of the views.

**Comment by Bradblooms** [comment]
Here you can find the answer, you should change the order of your Elements,
let's say you have.
<TouchableOpacity><Text>Close</Text></TouchableOpacity>
<View></View>

To fix it Change it to :
<View></View>
<TouchableOpacity><Text>Close</Text></TouchableOpacity>

**Comment by qam12** [comment]
Try this 
xyz{
elevation: 4
}

**Comment by danielkhaleb** [comment]
@qam12 Work for me, thanks 

 `  <View
            style={{
              borderRadius: 16,
              backgroundColor: '#E03400',
              padding: 10,
              position: 'absolute',
              zIndex: 1,
              marginLeft: '45%',
              marginTop: 30,
              width: '55%',
              elevation: 4,
            }}
          > 
            <Text
              style={{
                fontFamily: 'OpenSans-Semibold',
                fontSize: 10,
                color: '#FFFFFF',
              }}
            >
              {textContent}
            </Text>
          </View>`

**Comment by anupp-11** [comment]
> you should change the order of your Elements,
> let's say you have.
> 
> ```
> <TouchableOpacity><Text>Close</Text></TouchableOpacity>
> <View></View>
> ```
> 
> To fix it Change it to :
> 
> ```
> <View></View>
> <TouchableOpacity><Text>Close</Text></TouchableOpacity>
> ```

thanks Man worked
