### ISSUE TITLE
glog-0.3.5 getting logging.h not found in iOS

### ISSUE THREAD

**Issue by MrQureshi** [facebook/react-native#27547]
React Native version:
  React Native Environment Info:
    System:
      OS: macOS 10.14.6
      CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
      Memory: 22.05 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.15.0 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 28, 29
        Build Tools: 28.0.3, 29.0.2
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.9 => 0.59.9
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Steps To Reproduce

1. after remove node_modules and yarn install 
2. remove Pod and install again
3. lunch Xcode 10.2 select project 
4. clean and run .

Legacy build system
5. 'glog/logging.h' file not found

New build system error
6. configure: error: in `gs-gospark-mobile/node_modules/react-native/third-party/glog-0.3.5':
configure: error: C compiler cannot create executables
See `config.log' for more details
Command PhaseScriptExecution emitted errors but did not return a nonzero exit code to indicate failure

Describe what you expected to happen:

I want to generate build on debug and release as well as Generic build

Snack, code example, screenshot, or link to a repository:

![Screenshot 2019-12-17 at 11 43 32 PM](https://user-images.githubusercontent.com/30835780/71024661-3da6bc80-2127-11ea-8337-8b697b651684.png)

**Comment by kubilaykiymaci** [comment]
Probably, your installing didn't finished successfully. 
Please check your node modules.

**Comment by MrQureshi** [comment]
> Probably, your installing didn't finished successfully.
> Please check your node modules.

It's xCode version issue, in my mac there was two xCode 10.1 and 10.2,  i have uninstall 10.1 . After that some object C issue. finally some version issue of pod. 
it take a lot of time to resolve but i get success to do. thank you @kubilaykiymaci
