### ISSUE TITLE
Debugging at chrome breakpoint, unable to pop up data info window

### ISSUE THREAD

**Issue by mengerzhuanyong** [facebook/react-native#27541]
React Native version:

        System:
        OS: macOS Mojave 10.14.2
        CPU: (4) x64 Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
        Memory: 32.95 MB / 8.00 GB
        Shell: 3.2.57 - /bin/bash
      Binaries:
        Node: 12.10.0 - /usr/local/bin/node
        Yarn: 1.10.1 - ~/.yarn/bin/yarn
        npm: 6.13.1 - /usr/local/bin/npm
        Watchman: 4.9.0 - /usr/local/bin/watchman
      SDKs:
        iOS SDK:
          Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
        Android SDK:
          API Levels: 17, 22, 23, 24, 25, 26, 27, 28
          Build Tools: 23.0.1, 23.0.3, 24.0.2, 25.0.0, 25.0.2, 26.0.1, 26.0.2, 26.0.3, 27.0.1, 27.0.3, 28.0.1, 28.0.2, 28.0.3
          System Images: android-28 | Google Play Intel x86 Atom
      IDEs:
        Android Studio: 3.5 AI-191.8026.42.35.5977832
        Xcode: 10.1/10B61 - /usr/bin/xcodebuild
      npmPackages:
        react: 16.9.0 => 16.9.0 
        react-native: 0.61.4 => 0.61.4 
      npmGlobalPackages:
        react-native-cli: 2.0.1
        react-native-git-upgrade: 0.2.7
## Steps To Reproduce

Describe what you expected to happen:

![image](https://user-images.githubusercontent.com/19523478/70969014-cb59bc00-20d5-11ea-842b-c28eb39b834e.png)

**Comment by ReneMarquez** [comment]
having the same issue here
