### ISSUE TITLE
View has a shadow set but cannot calculate shadow efficiently.

### ISSUE THREAD

**Issue by yvbeek** [facebook/react-native#27546]
In our app we are applying a shadow to an Image component. Unfortunately that generates the following warning:

> View ... of type RCTImageView has a shadow set but cannot calculate shadow efficiently. Consider setting a background color to fix this, or apply the shadow to a more specific component.

The warning is generated by these lines of code:

https://github.com/facebook/react-native/blob/5a9b7d7adcb43d6c19a450018fe38dc1ba7fe400/React/Views/RCTView.m#L850-L853

Is there a way to turn off this warning for this specific image?
I don't want to turn off all warnings.

**React Native version:**
```
System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 3.43 GB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 13.3.0 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5977832
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5
```

## Steps To Reproduce

- Add a Image component
- Set shadow style properties on the component, don't set a background

https://snack.expo.io/@yvbeek/react-native-image-shadow

**Comment by kubilaykiymaci** [comment]
as a workaround, maybe you can make your background transparent.

**Comment by yvbeek** [comment]
@kubilaykiymaci Unfortunately that doesn't work. Here is the entire code inside of `RCTView` that raises the warning:

```objective-c
static void RCTUpdateShadowPathForView(RCTView *view)
{
  if (RCTLayerHasShadow(view.layer)) {
    if (CGColorGetAlpha(view.backgroundColor.CGColor) > 0.999) {

      // If view has a solid background color, calculate shadow path from border
      const RCTCornerRadii cornerRadii = [view cornerRadii];
      const RCTCornerInsets cornerInsets = RCTGetCornerInsets(cornerRadii, UIEdgeInsetsZero);
      CGPathRef shadowPath = RCTPathCreateWithRoundedRect(view.bounds, cornerInsets, NULL);
      view.layer.shadowPath = shadowPath;
      CGPathRelease(shadowPath);

    } else {

      // Can't accurately calculate box shadow, so fall back to pixel-based shadow
      view.layer.shadowPath = nil;

      RCTLogAdvice(@"View #%@ of type %@ has a shadow set but cannot calculate "
        "shadow efficiently. Consider setting a background color to "
        "fix this, or apply the shadow to a more specific component.",
        view.reactTag, [view class]);
    }
  }
}
```

So if the background is not transparent (`alpha > 0.999`) it will render a shadow on the entire bounds of the view. Which is a nice optimization, because if you have a background color, you probably expect the shadow to be underneath the entire view.

If the background is transparent it will render a shadow underneath the content (which is great for a transparent image, because you want to have the shadow underneath the individual pixels, not the entire bounds of the image). The warning makes sense if you use this in a List where it would really matter for performance, but just for a single view I'd like to disable the warning.
