### ISSUE TITLE
Clipboard Issue

### ISSUE THREAD

**Issue by PrantikMondal** [facebook/react-native#27556]
i have import {Clipboard} from 'react-native' 
import { WebView } from "react-native-webview";
Clipboard.getString() not working (App crashing) on some android version like 8.0 or 8.1 while coping something from Webview and device google chrome version is not updated.
While i update chrome to latest version then Clipboard.getString() is working fine. 
  
React Native version:
0.61.5
React Native Webview version: 
8.0.1

**Comment by amahJennifer** [comment]
Thanks

**Comment by PrantikMondal** [comment]
Can anyone help me on this? I am still waiting for a solution

**Comment by safaiyeh** [comment]
Hi Prantik, you can file WebView related issues to: https://github.com/react-native-community/react-native-webview
