### ISSUE TITLE
RNCViewPager was not found in the UIManager

### ISSUE THREAD

**Issue by PursuitLife** [facebook/react-native#27557]
React Native version:

## Steps To Reproduce

1.
2.

Describe what you expected to happen:

Snack, code example, screenshot, or link to a repository:

**Comment by dazza5000** [comment]
This is the full stacktrace for me:

`Fatal Exception: com.facebook.react.common.JavascriptException: Invariant Violation: requireNativeComponent: "RNCViewPager" was not found in the UIManager.

This error is located at:
    in N
    in o
    in n
    in RCTView
    in RCTView
    in h, js engine: hermes, stack:
anonymous (address at@1:217114
anonymous (address at@1:220324
anonymous (address at@1:206253
Al (address at@1:131034
Ml (address at@1:128798
Ul (address at@1:126273
Pl@-1
anonymous@-1
anonymous (address at@1:210509
an (address at@1:100919
sn (address at@1:101177
cn (address at@1:101071
_e (address at@1:145972
Ne (address at@1:95290
Ue (address at@1:95623
receiveTouches (address at@1:140689
apply@-1
value (address at@1:56680
anonymous (address at@1:55106
value (address at@1:56279
value (address at@1:55064

       at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:71)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:371)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
       at android.os.Looper.loop(Looper.java:214)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
       at java.lang.Thread.run(Thread.java:919)`

**Comment by dazza5000** [comment]
I resolved this in the following way:

I added the following to my settings.gradle


```
include ':@react-native-community_viewpager'
project(':@react-native-community_viewpager').projectDir = new File(rootProject.projectDir, '../node_modules/@react-native-community/viewpager/android')
```

Then I added the following to app/build.gradle

`    implementation project(':@react-native-community_viewpager')`

I then updated my Android Application class with an import

`import com.reactnativecommunity.viewpager.RNCViewPagerPackage;`

and then added it to the list of RN Packages:




```
    private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
        @Override
        public boolean getUseDeveloperSupport() {
            return BuildConfig.DEBUG;
        }

        @Override
        protected List<ReactPackage> getPackages() {
            return Arrays.asList(
                    new MainReactPackage(),
                    new MapsPackage(),
                    new Interactable(),
                    new LocationServicesPackage(),
                    new AnalyticsPackage(),
                    new ConfigPackage(),
                    new BlurViewPackage(),
                    new RNI18nPackage(),
                    new NavigationPackage(),
                    new RemoteConfigPackage(),
                    new LottiePackage(),
                    new ReanimatedPackage(),
                    new GeolocationPackage(),
                    new NetInfoPackage(),
                    new RNCViewPagerPackage()
            );
        }
    };
```
