### ISSUE TITLE
Minimum Android version for React Native?

### ISSUE THREAD

**Issue by jondot** [facebook/react-native#2756]
Hi,
From source, I see that min. version is Android 4.1 for React Native - is this also an official standpoint for the future? should it be mentioned in the docs?

Thanks!

**Comment by ide** [comment]
cc @mkonicek @kmagiera

**Comment by foghina** [comment]
Yes, it's 4.1 (API 16). This is the version that introduced `Choreographer` which we make heavy use of, so supporting anything older would be pretty hard. And yes, we should probably document it.

**Comment by jondot** [comment]
Thanks, makes sense :+1:

**Comment by brentvatne** [comment]
Added a note for this to the README: https://github.com/facebook/react-native/commit/e2841c05b4bc67aad90854c7013b278ca4abe03a :rocket:
