### ISSUE TITLE
ld: library not found for -lGoogleAnalyticsServices

### ISSUE THREAD

**Issue by massoprod** [facebook/react-native#27572]
Hi,

I am upgrading react-native version from **0.59.10** to **0.61.5** and I have some issues with building iOs project.

I was upgrading by this helper: [https://react-native-community.github.io/upgrade-helper/?from=0.59.10&to=0.61.5](https://react-native-community.github.io/upgrade-helper/?from=0.59.10&to=0.61.5)

When I am building to iOs, all time I have error like this:
 **`ld: library not found for -lGoogleAnalyticsServices`**

In my project I am using  **react-native-google-analytics-bridge**

**Xcode version:** 10.2.1

Could you help me to resolve this issue, please?

Thank you 🙏 

React Native version: 0.61.5

**Comment by albinhubsch** [comment]
**react-native-google-analytics-bridge** is deprecated and probably not updated to support auto-linking, thereby your issue with the library not being found. [see repo](https://github.com/idehub/react-native-google-analytics-bridge)

You should convert to firebase analytics.

**Comment by CyrusZei** [comment]
easy fix for this is to remove the google analytics bridge comething in your package.json and remove it from the podfile and then remove node_modules and pod.lock.

1. Remove google analytics bridge from package.json
2. Remove node_modules
3. Remove googel analytics bridge from podfile
4. Remove pod.lock file
5. yarn install
6. pod install

and it should work. Why I think it does not work is cuz it says it is deprecated and it won't download the package and that is why podfile cant find it

**Comment by CyrusZei** [comment]
thank you past me for helping future me <3
