### ISSUE TITLE
null is not an object (evaluating '_RNGestureHandlerModule.default.handleSetJSResponder')

### ISSUE THREAD

**Issue by DucSilva** [facebook/react-native#27578]
Hi all! 
when i tap on screen I got an error as image below!  i don't know what's it? Does anyone help me fix this?
Thanks
![s](https://user-images.githubusercontent.com/46064085/71142854-38db2900-224b-11ea-8f35-782345e72cc1.png)

**Comment by StarkAndy** [comment]
@DucSilva  this issues usually comes when the library is not present in your ios.
It's issue with library you can manually add the library in your xcode .
follow the following steps:
1.Right click in library > add more file >

inside  node_modules/react-native-gesture-handler/ios/ you will find a file with .xcodeproj extension add that file.

2.Open it you will see product

3.Drag .a file to >Build Setting /Link Binary With Libraries delete derived data and rebuild it.

Hope this will help.
