### ISSUE TITLE
Error when running npm start

### ISSUE THREAD

**Issue by Ognen67** [facebook/react-native#27584]
I'm experiencing this problem when i run npm start. I'm new to using react native. 
[2019-12-20T15_58_04_808Z-debug.log](https://github.com/facebook/react-native/files/3989063/2019-12-20T15_58_04_808Z-debug.log)
![Screenshot_1](https://user-images.githubusercontent.com/35491291/71267080-fe0bea80-2349-11ea-9ccc-908c0601ccf7.png)

**Comment by Ognen67** [comment]
I tried with the newest node.js version then i downgraded it to an older one (12.14.0 LTS)

**Comment by ExitTrance** [comment]
@Ognen67 
Might be related to [issue 27516](https://github.com/facebook/react-native/issues/27516#issuecomment-565841536) where the regex inside the blacklist file doesn't seem to work. Replacing the file with the one mentioned in gokhandoslu's comment does the trick.

**Comment by LyhourChhen** [comment]
Seem your problem match with this solution let try this via StackOverflow https://stackoverflow.com/questions/58117377/react-native-start-giving-invalid-regular-expression-invalid-error

**Comment by cpojer** [comment]
Thank you for your report. We fixed this just now with the release of Metro 0.56.4 and 0.57.0. Update your packages and re-create your project and things should work for you again :) Sorry for the inconvenience.
