### ISSUE TITLE
SecureTextEntry and/or textContentType={"password"} hides suggestions for other textinputs on IOS

### ISSUE THREAD

**Issue by JustinRohweller** [facebook/react-native#27586]
## If you pass secureTextEntry prop to one textinput, other textinputs on the page without the prop still cannot show text suggestions.

React Native version:
Just tested on snack. Happens in both Expo SDK36 and 34.
https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz

## Steps To Reproduce

1. Render two textinputs.
2. Tell one to show suggestions with autoCorrect={true}
3. Pass other one either/or these props: secureTextEntry, textContentType={"password"}

Describe what you expected to happen:
I expect to be able to see text suggestions on the first textinput, which does not have the securetextentry prop. As in, the first textinput should show text suggestions, the second one should not.

Snack, code example, screenshot, or link to a repository:
https://snack.expo.io/Hyktr0qAr

```
import * as React from 'react';
import { Text, View, TextInput } from 'react-native';

export default class App extends React.Component {
  render() {
    return (
      <View style={{ flex: 1, justifyContent: 'center' }}>
        <Text>
          Type in both inputs below on an Iphone. I am unable to get text suggestions 
          if you enable secureTextEntry or textContentType
        </Text>
        <View style={{ height: 20, backgroundColor: 'orange' }}>
          <TextInput autoCorrect secureTextEntry={false} />
        </View>
        <View style={{ height: 20, backgroundColor: 'orange', marginVertical: 10 }}>
          <TextInput 
          secureTextEntry
          // textContentType={"password"}
          />
        </View>
      </View>
    );
  }
}
```

Thanks in advance.  Easy way to see the issue is just to copy paste the code above into snack, and run ON DEVICE. The snack simulator does not appear to have the same issue as a real device. Can easily see there that the first textinput does not have suggestions, and if you comment out securetextentry on the second input, like magic the first textinput can have suggestions again.

**Comment by fareedagha** [comment]
@JustinRohweller you can do this by component state 
for e.g make {secureTextEntry} false in state and make it true onFocus function in textField and again false state onBlur(), i hope it will work thanks

**Comment by MshahzadRasheed** [comment]
> @JustinRohweller you can do this by component state
> for e.g make {secureTextEntry} false in state and make it true onFocus function in textField and again false state onBlur(), i hope it will work thanks

Thanks @fareedagha save my day ....below is the example how it works properly
  <TextInput
            ref={ref => {
              this.password = ref;
            }}
            onFocus={() => {
              this.setState({secureEntry: true});
            }}
            onBlur={() => {
              this.setState({secureEntry: false});
            }}
            label="Password"
            secureTextEntry={this.state.secureEntry}
            onChangeText={value => this._onChange('password', value)}
            returnKeyType="next"
            onSubmitEditing={this.submitPassword}
            maxLength={16}
          />
onFocus={() => {
              this.setState({secureEntry: true});
            }}
            onBlur={() => {
              this.setState({secureEntry: false});
            }}
