### ISSUE TITLE
error on the site

### ISSUE THREAD

**Issue by valery-lavrik** [facebook/react-native#27593]
Good afternoon!
Your site has been down for almost a week now. In console error:
![image](https://user-images.githubusercontent.com/8047999/71345532-b6b67180-2576-11ea-864c-e0207ad27098.png)
[https://react-native.org/doc/getting-started.html](url)

userAgent: **Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 YaBrowser/19.12.3.252 (beta) Yowser/2.5 Safari/537.36**

**Comment by hramos** [comment]
The react-native.org domain is not affiliated with React Native in any capacity.
