### ISSUE TITLE
Question: React Native App in google Playstore always give same size of update, every-time I Release new Updates (android only)

### ISSUE THREAD

**Issue by jigaryadav** [facebook/react-native#27591]
RN Version: 0.61.5

i have an application which is completely made with RN and it is released in google play store.

i am creating release with ./gradlew bundleRelease command which will create a bundle unlike apk, also recommended by RN

ref. https://facebook.github.io/react-native/docs/signed-apk-android#generating-the-release-apk

now i am confuse that every-time i upload a new update i have to download a complete apk even if the update is so small

please help me in this. i have used proGard also in the android part to minimise the app size

**Comment by VyankeshH** [comment]
@jigaryadav Did you find any solution on this ? I have a same Issue,any response much appreciated.
Thank you.

**Comment by jigaryadav** [comment]
@VyankeshH i did not found any, but it look like this process is automated by google play
