### ISSUE TITLE
React native executing older versions of the code after fast-refreshing/restarting

### ISSUE THREAD

**Issue by Kemosabert** [facebook/react-native#27599]
We have an app which makes use of redux for global state management and redux-sagas for handling async actions such as saving and fetching data via an API we build. Recently we had some customers sending in complaints about new records being created twice.  

We started noticing that in the debugger on Android, we saw `console.log`'s from older versions of the code. So if the app restarted because of the fast-refresh feature, our saga's would still log things from a previous version of the code. 

This also was in line with our suspicion that these saga's were somehow run multiple times. Actually, we found that they run as many times as React Native did a 'fast refresh' of the app due to code changes, each instance running that version of the code. 

I am not entirely sure if this is a react native issue or an issue from the libraries we use, but because we are seeing logs from older versions of the code I suspect that there's something which makes RN execute older versions (due to fast refresh or bringing the app from the back to the fore-ground).

We only saw this behaviour on Android and I can't seem to find much other issues about this problem. Is this a known bug/quirk? Thanks for your help in advance!

I will see if I can make a fiddle to reproduce this issue.

React Native version:
  Binaries:
    Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
    Yarn: 1.19.0 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.13.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
  IDEs:
    Android Studio: 3.3 AI-182.5107.16.33.5199772
    Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
  npmPackages:
    @react-native-community/cli: ^3.0.4 => 3.0.4
    react: 16.9.0 => 16.9.0
    react-native: 0.61.3 => 0.61.3
  npmGlobalPackages:
    react-native-cli: 2.0.1

**Comment by florian-milky** [comment]
@Kemosabert you closed this. Did you find a solution?

**Comment by yash1511** [comment]
Any updates?

**Comment by florian-milky** [comment]
FYI I found out that I had a circular dependency.
For some reason it's not handled well by fast refresh. When you update a file it will update all the files that import it. So if you have an import in that file that get refreshed later, it will not pick up the new instance.
