### ISSUE TITLE
TextInput.contextMenuHidden doesn't work for Android

### ISSUE THREAD

**Issue by papabone** [facebook/react-native#27595]
TextInput.contextMenuHidden doesn't work for Android platform

## Steps To Reproduce
_Need to do_: Try to select text (long press on the input) in the input. <TextInput contextMenuHidden={true} />
_Result:_ the text is highlighted, the context menu opens
_Expected Result:_nothing to happen (long press on the input - disabled)

**Tested on**:  Pixel 3, Pixel 2 (Virtual), Lenovo A7000-a (Device)

**React Native version**:
 - react-native: 0.61.2, 0.61.5

**Environment**: 

- node: 8.12.0
- npm: 6.4.1
- react-native-cli: 2.0.1

**Comment by safaiyeh** [comment]
`contextMenuHidden` disables the long press on the input.

This behavior gets disabled with the `contextMenuHidden`.
![Dec-28-2019 21-51-20](https://user-images.githubusercontent.com/8675043/71552997-35b70a00-29bc-11ea-9f1e-cd2474cae97a.gif)

You want `selectTextOnFocus={false}` to disable the contextMenu of the highlighted text.

**Comment by papabone** [comment]
> `contextMenuHidden` disables the long press on the input.
> 
> This behavior gets disabled with the `contextMenuHidden`.
> ![Dec-28-2019 21-51-20](https://user-images.githubusercontent.com/8675043/71552997-35b70a00-29bc-11ea-9f1e-cd2474cae97a.gif)
> 
> You want `selectTextOnFocus={false}` to disable the contextMenu of the highlighted text.

Thanks for your comment! I have tried to make description more clear. 
Probably, I should tasted it by more divices, but for thes devises, wich i tested, epxpected behavier did not reprodused (selectTextOnFocus={true} did not disabled opening context menu). Actualy, for IoS - behavior - correct.

**Comment by safaiyeh** [comment]
`selectTextOnFocus={false}` disables it

**Comment by papabone** [comment]
> `selectTextOnFocus={false}` disables it

oh sorry first time i didn't catch: now i see. I'll check this solution. Thank you!

**Comment by papabone** [comment]
> > `selectTextOnFocus={false}` disables it
> 
> oh sorry first time i didn't catch: now i see. I'll check this solution. Thank you!

unfortunately it looks like it doesn't work
