### ISSUE TITLE
Feature request: Web support 

### ISSUE THREAD

**Issue by bhaskar8088** [facebook/react-native#27592]
Hi,

In near future, is it possible to build android, ios and web with same code base. There is a third party plugin "react-native-web" but robust inbuilt support is better.

Also, is it possible to have better performance like that of flutter. React native already has better performance, but if we can achieve the same level of performance like that of flutter, that will be good. The reason for requesting is, react native is more comfortable to develop than others so having web support and best performance makes it 100% useful to everyone.

**Comment by hramos** [comment]
https://github.com/react-native-community/discussions-and-proposals might be a better fit for this issue.
