### ISSUE TITLE
Possibility to show pins on MapView (MKPointAnnotation) 

### ISSUE THREAD

**Issue by DanielMSchmidt** [facebook/react-native#276]
Hi there,

first of all thanks for open sourcing this great library, it really made my day (and will likely make my month).
I would like to ask if there is yet a possibility to show markers / pins (MKPointAnnotation is the real name I guess)  on the map? If not and if you would like, I would be glad to work an a PR for this feature.

Regards and thanks for the great work!

**Comment by LinusPahl** [comment]
+1

**Comment by dbanck** [comment]
:+1:

**Comment by tadeuzagallo** [comment]
Hey @DanielMSchmidt, there isn't any api for that so far... but please, if you want to work on it, go ahead! :)

**Comment by DanielMSchmidt** [comment]
Great, I will do so ;)

**Comment by lloydh6** [comment]
:+1:

**Comment by DanielMSchmidt** [comment]
@tadeuzagallo Would this syntax be okay?

```
<MapView pins={this.state.pins} />
```

**Comment by tadeuzagallo** [comment]
It's good to me, although I'm not the best for naming... if someone is against it, it should be fairly easy to rename the property later, so I'd say go for it!

**Comment by BenHall** [comment]
@DanielMSchmidt What's the latest on this? Anything I can do to help as I need it for my app?

**Comment by DanielMSchmidt** [comment]
The current status is, that it's possible to add pins to the map, but after some seconds the map freezes. I haven't updated any documentation yet, nor written any tests. As I am (unfortunately) on vacation, I won't have time to fix this, but I could and likely will write the documentation and some tests. 

I would be really happy if you would take a look at the current status and fix the freezing. My hint would be, that I simply added the annotations at the wrong time of the maps lifecycle or in a method that gets called too often. I added you as collaborator to my [fork](https://github.com/DanielMSchmidt/react-native) and if you need an example implementation, see [here.](https://github.com/DanielMSchmidt/mapReference) Thanks for your help!

**Comment by DanielMSchmidt** [comment]
Update: the code is working now, I will soon add the documentation and tests and then I will open a PR

**Comment by DanielMSchmidt** [comment]
Pins seem to be implemented as annotaions while I have been working on this PR, just FYI.

**Comment by dominicthomas** [comment]
Any tips on how to change the design of the pins to incorporate say an image or a custom view?

**Comment by seb0zz** [comment]
@dominicthomas did you find out how to style custom markers/pins?

**Comment by jaygarcia** [comment]
Does it freeze on the device too? I've been doing map work with RN and the simulator sucks compared to the device for maps

**Comment by seb0zz** [comment]
Yes, same problem on my device (iPhone 6).

**Comment by dominicthomas** [comment]
@seb0zz no not yet. I was about to start looking at creating a custom MkAnnotationView and extend the RN MapView to pass in an image URL either for a custom pin or an image in the custom annotation view. Will then need to try a similar approach on android.

**Comment by GantMan** [comment]
:+1:  would be awesome to have custom annotations @dominicthomas

**Comment by dominicthomas** [comment]
@GantMan Totally. to get going I've had to duplicate the RCTMap and RCTMapManager as well as the MapView js so I can make changes. Shouldn't be too hard to change the view type being rendered as annotation. I'll post back if I get anywhere.

**Comment by jaygarcia** [comment]
Unfortunately, this is something that has to be done due to the patterns that react native uses.  :(

I documented this problem and have not gotten confirmation on if this is the best/only way to "extend" react native  components. 

https://github.com/facebook/react-native/issues/3444

**Comment by GantMan** [comment]
@dominicthomas and @jaygarcia I admire your willingness to jump in!  I'm focussed on an MVP right now, but if either of you completely patch RN to get this feature, I'd love to hear about the process.  I'm a fan of contributing to OSS and would be enthralled to hear all that's involved to get an extension like this.
