### ISSUE TITLE
[ReactAndroid] tintColor doesn't work unless borderRadius has a value.

### ISSUE THREAD

**Issue by hayeah** [facebook/react-native#2760]
tintColor shows:

```
<Image style={{borderRadius: 1, width: 150, height: 150, tintColor: "#00FF00" }} source={ASSETS.thumb_normal}/>
```

tintColor doesn't show:

```
<Image style={{width: 150, height: 150, tintColor: "#00FF00" }} source={ASSETS.thumb_normal}/>
```

Tracing the code in ReactImageManager.java, `view.setColorFilter` does get the correct color, it's just not showing up for some reason...

**Comment by andreicoman11** [comment]
This is a problem with fresco (the android image library that we use for react-native-android) that will be fixed with the next fresco version.
