### ISSUE TITLE
Native Modules Setup on iOS

### ISSUE THREAD

**Issue by PomegranateApps** [facebook/react-native#27611]
React Native version:
  React Native Environment Info:
    System:
      OS: macOS 10.15.2
      CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
      Memory: 51.21 MB / 32.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.14.0 - /usr/local/bin/node
      Yarn: yarn install v0.23.4
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.34s. - /opt/local/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
      Android SDK:
        API Levels: 21, 28
        Build Tools: 21.1.2, 28.0.3
        System Images: android-21 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5900203
      Xcode: 11.3/11C29 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.8.3 => 16.12.0 
      react-native: ^0.59.10 => 0.59.10 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

## Steps To Reproduce
I am following this guide here.
https://facebook.github.io/react-native/docs/native-modules-setup

When I try and run the iOS target from Xcode I get this error message.

'React/RCTBridgeModule.h' file not found
I looked at the build settings for the project and it has these two header search paths to React.

$(SRCROOT)/../../../React
$(SRCROOT)/../../react-native/React

These paths aren't correct. I'm not sure where the first one is supposed to point to but the second one is stored here but I still can't get Xcode to find this header file.

$(SRCROOT)/../node_modules/react-native/
The full path for that header file is $(SRCROOT)/../node_modules/react-native/React/Base/RCTBridgeModule.h.

**Comment by builtbyproxy** [comment]
To fix this head to (from root) `ios/<yourProjectName>/AppDelegate.m` and around line `13` you should see `#import React/RCTBridgeModule.h`
Try changing this to `#import <React/RCTBridge.h>` and let me know how you go 👍
