### ISSUE TITLE
[DatePickerIOS] minuteInterval not respected when mode="time"

### ISSUE THREAD

**Issue by adamterlson** [facebook/react-native#2763]
Following the [DatePickerIOS example](https://facebook.github.io/react-native/docs/datepickerios.html) verbatim, the `minuteInterval` property is not respected (that is, the minutes increment by one instead of the interval) on the `mode="time"` example:

          <Heading label="Time picker, 10-minute interval" />
          <DatePickerIOS
            date={this.state.date}
            mode="time"
            timeZoneOffsetInMinutes={this.state.timeZoneOffsetInHours * 60}
            onDateChange={this.onDateChange}
            minuteInterval={10}
          />

However, if `mode="time"` is changed to `mode="datetime"` the `minuteInterval` setting works as expected.

I would expect the `minuteInterval` to work with either mode setting.

EDIT: It is perhaps of little value, but I implemented the `RCTDatePickerIOS` and it has the same issue.

          <RCTDatePickerIOS
            style={styles.datePickerIOS}
            date={this.state.date}
            mode="time"
            timeZoneOffsetInMinutes={this.state.timeZoneOffsetInHours * 60}
            onChange={this._onChange}
            minuteInterval={10}
          />

**Comment by christopherdro** [comment]
Looks like this is happening from 0.11.0 and on.
Can be tested here with different builds here. https://rnplay.org/apps/kWYsTA

@nicklockwood Any idea what could've caused this to break?
The minuteInterval prop still gets passed down to the native component so I'm not sure whats going on.

I have noticed this warnings from DatePickerIOS regardless of what mode it's set in.

`Warning: Failed propType: Required prop `onDateChange` was not specified in `<<anonymous>>`.`
 `Warning: Failed propType: Invalid prop `date` supplied to `RCTDatePicker`, expected instance of `Date`.`
`Warning: Failed propType: Required prop `onDateChange` was not specified in `RCTDatePicker`.`

**Comment by yberstad** [comment]
I'm having the same issue, currently running 0.12.0. Does anyone know if this is fixed in any of the later versions?

**Comment by nicklockwood** [comment]
You can safely ignore this, it's a false positive due to a limitation of our propType checking. The public prop is a date, but the internal native prop is a number, so when it's converted internally, it thinks the type is wrong.

**Comment by cosmith** [comment]
This is fixed in 0.13 and 0.14.

**Comment by cosmith** [comment]
Actually it was working fine before but not anymore... I don't know what changed in my code between the working version and the new one. So still an issue in 0.14.2

**Comment by cosmith** [comment]
I upgraded to 0.16 and it seems to be fixed.

**Comment by carlos-wong** [comment]
I am use 0.17 the warning is appear again

**Comment by CapitanRedBeard** [comment]
I'm getting these as error in 0.20

**Comment by faxioman** [comment]
Same error, minuteInterval ignored, in 0.24. It works correctly only inside the simulator.

**Comment by nullfox** [comment]
I'm seeing this behavior in 0.39.2

When mode is set to "datetime" minuteInterval is respected, when set to "time" it is not and every minute is available.

**Comment by tiaaaa123** [comment]
Same issue in 0.40.0.

**Comment by cosmith** [comment]
@facebook-github-bot reopen

**Comment by boudellaredouane** [comment]
Same issue on 0.43.3
When mode is set to "datetime" minuteInterval is respected, when set to "time" it is not and every minute is available.

**Comment by HouLinguo** [comment]
Same issue in 0.44

**Comment by blutarche** [comment]
Same issue in 0.53.0

**Comment by zaiz91** [comment]
If I set "minuteInterval" with a setTimeout it works. It won't work without setTimeout.
