### ISSUE TITLE
React/RCTBundleURLProvider.h' file not found

### ISSUE THREAD

**Issue by lawgimenez** [facebook/react-native#27648]
React Native version:
  System:
    OS: macOS 10.15.2
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Memory: 7.62 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.5.0 - /usr/local/bin/node
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.12.0 => 16.12.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1

## Steps To Reproduce

1. Tried to compile but error found in AppDelegate, `React/RCTBundleURLProvider.h' file not found`
2.

Describe what you expected to happen:

Snack, code example, screenshot, or link to a repository:

**Comment by pepibumur** [comment]
@lawgimenez did you open the project using the .xcworkspace?

**Comment by lawgimenez** [comment]
@pepibumur Yes. Also, this project has been updated from a very outdated version of React Native, from 0.44 to 0.61.

**Comment by seco35** [comment]
Facing same issue...

**Comment by San10694** [comment]
has anybody found the solution? facing the same issue.

**Comment by chancelee** [comment]
has anybody found the solution? facing the same issue.?

**Comment by nicseve** [comment]
Same issue here.

**Comment by faridomarzadeh** [comment]
same problem
