### ISSUE TITLE
null is not an object (evaluating blob.data)

### ISSUE THREAD

**Issue by sankar9659** [facebook/react-native#27645]
React Native version:

## Steps To Reproduce

1.
2.

Describe what you expected to happen:

Snack, code example, screenshot, or link to a repository:

**Comment by leotm** [comment]
@sankar9659 How did you resolve it in the end?

I'm getting this only after an async call (HEAD request returning 200).

<img width="469" alt="Screenshot 2020-03-14 at 17 06 54" src="https://user-images.githubusercontent.com/1881059/76686814-3bfd6f80-6616-11ea-90dc-5e7d4d94d2c1.png">
