### ISSUE TITLE
packager swallows startup errors

### ISSUE THREAD

**Issue by threepointone** [facebook/react-native#2764]
whenever there's a problem with the packager's startup, it swallows the error silently (in code here - [this section](https://github.com/facebook/react-native/blob/65c4088340225a49c3f699aee5f22ad42adf1945/react-native-cli/index.js#L25-L28)) Specifically, an invalid babelrc will generate a cryptic error 'Command start unrecognized. Did you mean to run this inside a react-native project?' while the error has actual details of babel failing. Could we `console.log` that error/stack?

**Comment by mkonicek** [comment]
cc @martinbigio
