### ISSUE TITLE
 iOS release build crash on launch with RN version 0.59.10

### ISSUE THREAD

**Issue by anand00** [facebook/react-native#27657]
I have updated my RN version from 0.57.7 to 0.59.10. Its working fine when I run from Xcode but when I archive and install the build through TestFlight, App gets crash on launch.

React Native version: 0.59.10

Attached is my crash logs and the test flight crash error: 
![Screenshot 2020-01-03 at 1 18 05 PM](https://user-images.githubusercontent.com/6582396/71713775-29560580-2e31-11ea-8b76-80bdca12514c.png)
[crashlog-9D577B1D-A844-427F-A6D3-AFCA6B960AB0 (1).txt](https://github.com/facebook/react-native/files/4018499/crashlog-9D577B1D-A844-427F-A6D3-AFCA6B960AB0.1.txt)

**Comment by Jcgama** [comment]
Facing the same issue. Any updates?

**Comment by naderghanbari** [comment]
Thanks for saving us a lot of time by reporting this! I was going to uprade to `0.59.10` but holding off in view of this bug.

**Comment by Nordzisko** [comment]
Having the very same issue. 
Any updates please?
