### ISSUE TITLE
react native init project

### ISSUE THREAD

**Issue by sdaulibin** [facebook/react-native#2766]
0 info it worked if it ends with ok
1 verbose cli [ 'node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   'react-native' ]
2 info using npm@2.10.1
3 info using node@v0.12.4
4 verbose node symlink /usr/local/bin/node
5 verbose install initial load of /Users/andylee/react-native-ios/Test/package.json
6 verbose readDependencies loading dependencies from /Users/andylee/react-native-ios/Test/package.json
7 silly cache add args [ 'react-native', null ]
8 verbose cache add spec react-native
9 silly cache add parsed spec { raw: 'react-native',
9 silly cache add   scope: null,
9 silly cache add   name: 'react-native',
9 silly cache add   rawSpec: '',
9 silly cache add   spec: '*',
9 silly cache add   type: 'range' }
10 silly addNamed react-native@*
11 verbose addNamed "*" is a valid semver range for react-native
12 silly addNameRange { name: 'react-native', range: '*', hasData: false }
13 silly mapToRegistry name react-native
14 silly mapToRegistry using default registry
15 silly mapToRegistry registry https://registry.npmjs.org/
16 silly mapToRegistry uri https://registry.npmjs.org/react-native
17 verbose addNameRange registry:https://registry.npmjs.org/react-native not in flight; fetching
18 verbose request uri https://registry.npmjs.org/react-native
19 verbose request no auth needed
20 info attempt registry request try #1 at 22:43:16
21 verbose request id 84988262d1092f96
22 verbose etag "38YYRRDG4COSRHZ7KZX3R1T71"
23 http request GET https://registry.npmjs.org/react-native
24 http 304 https://registry.npmjs.org/react-native
25 silly get cb [ 304,
25 silly get   { date: 'Wed, 16 Sep 2015 14:43:16 GMT',
25 silly get     via: '1.1 varnish',
25 silly get     'cache-control': 'max-age=60',
25 silly get     etag: '"38YYRRDG4COSRHZ7KZX3R1T71"',
25 silly get     age: '0',
25 silly get     connection: 'keep-alive',
25 silly get     'x-served-by': 'cache-itm7421-ITM',
25 silly get     'x-cache': 'HIT',
25 silly get     'x-cache-hits': '1',
25 silly get     'x-timer': 'S1442414596.680752,VS0,VE189',
25 silly get     vary: 'Accept' } ]
26 verbose etag https://registry.npmjs.org/react-native from cache
27 verbose get saving react-native to /Users/andylee/.npm/registry.npmjs.org/react-native/.cache.json
28 silly addNameRange number 2 { name: 'react-native', range: '*', hasData: true }
29 silly addNameRange versions [ 'react-native',
29 silly addNameRange   [ '0.0.0',
29 silly addNameRange     '0.0.5',
29 silly addNameRange     '0.0.6',
29 silly addNameRange     '0.1.0',
29 silly addNameRange     '0.2.0',
29 silly addNameRange     '0.2.1',
29 silly addNameRange     '0.3.0',
29 silly addNameRange     '0.3.1',
29 silly addNameRange     '0.3.2',
29 silly addNameRange     '0.3.3',
29 silly addNameRange     '0.3.4',
29 silly addNameRange     '0.3.5',
29 silly addNameRange     '0.3.6',
29 silly addNameRange     '0.3.7',
29 silly addNameRange     '0.3.8',
29 silly addNameRange     '0.3.9',
29 silly addNameRange     '0.3.10',
29 silly addNameRange     '0.3.11',
29 silly addNameRange     '0.4.0',
29 silly addNameRange     '0.4.1',
29 silly addNameRange     '0.4.2',
29 silly addNameRange     '0.4.3',
29 silly addNameRange     '0.4.4',
29 silly addNameRange     '0.5.0-rc1',
29 silly addNameRange     '0.5.0',
29 silly addNameRange     '0.6.0-rc',
29 silly addNameRange     '0.6.0',
29 silly addNameRange     '0.7.0-rc',
29 silly addNameRange     '0.7.0-rc.2',
29 silly addNameRange     '0.7.1',
29 silly addNameRange     '0.8.0-rc',
29 silly addNameRange     '0.8.0-rc.2',
29 silly addNameRange     '0.8.0',
29 silly addNameRange     '0.9.0-rc',
29 silly addNameRange     '0.9.0',
29 silly addNameRange     '0.10.0-rc',
29 silly addNameRange     '0.10.0',
29 silly addNameRange     '0.11.0-rc',
29 silly addNameRange     '0.10.1',
29 silly addNameRange     '0.11.0' ] ]
30 silly addNamed react-native@0.11.0
31 verbose addNamed "0.11.0" is a plain semver version for react-native
32 silly mapToRegistry name react-native
33 silly mapToRegistry using default registry
34 silly mapToRegistry registry https://registry.npmjs.org/
35 silly mapToRegistry uri https://registry.npmjs.org/react-native
36 verbose addRemoteTarball https://registry.npmjs.org/react-native/-/react-native-0.11.0.tgz not in flight; adding
37 verbose addRemoteTarball [ 'https://registry.npmjs.org/react-native/-/react-native-0.11.0.tgz',
37 verbose addRemoteTarball   '00f3b4f1aac3c320bfc2f18cf75c1b09cea54a85' ]
38 info retry fetch attempt 1 at 22:43:17
39 info attempt registry request try #1 at 22:43:17
40 http fetch GET https://registry.npmjs.org/react-native/-/react-native-0.11.0.tgz
41 http fetch 200 https://registry.npmjs.org/react-native/-/react-native-0.11.0.tgz
42 silly fetchAndShaCheck shasum 00f3b4f1aac3c320bfc2f18cf75c1b09cea54a85
43 verbose stack Error: shasum check failed for /var/folders/n9/czlryz9n13bbjrt7pgsw414m0000gn/T/npm-19671-6a7af240/registry.npmjs.org/react-native/-/react-native-0.11.0.tgz
43 verbose stack Expected: 00f3b4f1aac3c320bfc2f18cf75c1b09cea54a85
43 verbose stack Actual:   da39a3ee5e6b4b0d3255bfef95601890afd80709
43 verbose stack From:     https://registry.npmjs.org/react-native/-/react-native-0.11.0.tgz
43 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/sha/index.js:38:8
43 verbose stack     at ReadStream.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/sha/index.js:85:7)
43 verbose stack     at ReadStream.emit (events.js:129:20)
43 verbose stack     at _stream_readable.js:908:16
43 verbose stack     at process._tickCallback (node.js:355:11)
44 verbose cwd /Users/andylee/react-native-ios/Test
45 error Darwin 14.1.0
46 error argv "node" "/usr/local/bin/npm" "install" "--save" "react-native"
47 error node v0.12.4
48 error npm  v2.10.1
49 error shasum check failed for /var/folders/n9/czlryz9n13bbjrt7pgsw414m0000gn/T/npm-19671-6a7af240/registry.npmjs.org/react-native/-/react-native-0.11.0.tgz
49 error Expected: 00f3b4f1aac3c320bfc2f18cf75c1b09cea54a85
49 error Actual:   da39a3ee5e6b4b0d3255bfef95601890afd80709
49 error From:     https://registry.npmjs.org/react-native/-/react-native-0.11.0.tgz
50 error If you need help, you may report this error at:
50 error     <https://github.com/npm/npm/issues>
51 verbose exit [ 1, true ]

**Comment by foghina** [comment]
Seems like a simple checksum failure, please try running `react-native init` again. In the future you should post this type of question to [stackoverflow with tag **react-native**](http://stackoverflow.com/questions/tagged/react-native).

**Comment by yisiben** [comment]
you can try this: $ sudo react-native init helloworld
