### ISSUE TITLE
[Android TV] Navigating large ScrollView with D-pad scrolls the ScrollView instead of focusing on next item

### ISSUE THREAD

**Issue by satellink** [facebook/react-native#27663]
Same as #26133 which was closed before I was able to update it. It already has some discussion in it.

----
When clicking RIGHT D-pad -button while focusing on first element of ScrollView, the ScrollView scrolls instead of focusing to the second item in the ScrollView. The same issue happens also when being focused on the last item, and clicking LEFT on D-pad.

We manage to reliably reproduce this issue on emulators and few real devices, that run Android 7.0, 8.0 and 8.1. There was no issue on Android 6 or 9.

This issue only appears when ScrollView have large-enough amount of items. The amount of items also depends of the size of the item. With large items you need less items for this bug to be reproduced.

The test code below have three different sample item counts, and assigning each of the value with relevant value for horizontal-prop of ScrollView will behave differently when using it with D-pad.

### System info
System:
    OS: macOS 10.15.2
Binaries:
    Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5

React Native version: 0.61.5

Also reproduced with react-native versions 0.59.8, 0.60.5

### Steps To Reproduce
1. Clone the repository (https://github.com/satellink/ReactNativeAndroidTvScrollViewBug) 
2. run it on Android TV emulators (7.0, 8.0, 8.1) or real devices (tested on Xiaomi Mi Box and TCL tv running Android 8.0 and 8.1)
3. Click D-pad arrows to focus on Item 1
4. Click D-pad RIGHT
5. Observe the ScrollView scrolling instead of changing focus to Item 2
6. Click D-pad RIGHT a few times, until you notice that the focus starts to eventually behave correctly.
7. Click D-pad LEFT until focusing on Item 1
8. Click D-pad RIGHT and observe the scroll view still scrolling instead of changing focus.

Repeat the steps 2-8 by changing the amount of items rendered, and ScrollView prop horizontal={true|false} depending on constant.

**Expected result**
I expect that clicking on D-pad RIGHT would always focus on the item on the right, and clicking D-pad LEFT always to move focus to the item on the left.

Specifically, on steps 4 and 7. the ScrollView should not scroll - only change focus to Item 2.

### Sample code
https://github.com/satellink/ReactNativeAndroidTvScrollViewBug

1. clone the repository
2. yarn install
3. yarn android

### Related issue
#20099 looks like being the same issue; however, it is already closed.

**Comment by mgenev** [comment]
This issue is haunting us right now. Does anyone have a work around?

**Comment by satellink** [comment]
@mgnev One workaround is to use nextFocus/Up/Down/Left/Right props of <View /> to tell the view to go to the view you want. Not the easiest way as you need to handle everything yourself, but I don't see any other solutions right now.

Anyway, if you find any other workaround, please share! It doesn't look like this bug is getting attention any time soon.
