### ISSUE TITLE
Blank Black Screen on iOS Device

### ISSUE THREAD

**Issue by MOwais** [facebook/react-native#27668]
All of a sudden I am seeing a blank black screen when testing my react-native app on my iOS device. Everything was fine prior and nothing has changed in the codebase since. 

The command I am using is `react-native run-ios --device 'My iPhone'`. It builds successfully without any errors but when I launch the app on my phone I see a blank black screen. The app crashes about 20s later.

App runs fine on the simulator.

ENV:

```
SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: ^0.61.5 => 0.61.5 
```

Please let me know if you need any more info.

**Comment by ridhoassuryadi** [comment]
hi, any update about this issue. i had same issue too
