### ISSUE TITLE
Unrecognized font family "PingFangSC-Regular,PingFangSC-Semibold"

### ISSUE THREAD

**Issue by cliek** [facebook/react-native#27662]
Getting error Unrecognized font family 'PingFangSC-Regular,PingFangSC-Semibold' in iOS  Real machine debugging only. App works fine on android emulator.

React Native version:

**Environment:**
OS: macOS High Sierra 10.13.3
Node: 11.2.0
Yarn: 1.9.4
npm: 5.7.1
Xcode: Version 10.1 (10B61)

Packages: (wanted => installed)
react: 16.6.3
react-native: 0.50.2

Expected Behavior
App should properly open the app.

Describe what you expected to happen:

![image](https://user-images.githubusercontent.com/29326163/71723355-51f8f200-2e67-11ea-95cb-5e48658ee98b.png)

**Supplementary note**
I referenced this description #18087 
I traversed the font name and got the same name as the unauthenticated font. This error is still reported.

That you should place in "AppDelegate.m", after NSURL *jsCodeLocation;

```
for (NSString* family in [UIFont familyNames])
  {
    NSLog(@"%@", family);

    for (NSString* name in [UIFont fontNamesForFamilyName: family])
    {
      NSLog(@"  %@", name);
    }
}
```

Get the default font name of mac and the font name on the error message:
![image](https://user-images.githubusercontent.com/29326163/71723614-435f0a80-2e68-11ea-999e-ef5e2ba99ff3.png)

![image](https://user-images.githubusercontent.com/29326163/71723888-460e2f80-2e69-11ea-8c90-4f4a699aa345.png)

**Comment by morneluckybeard** [comment]
What did you do to resolve this @cliek ?
