### ISSUE TITLE
how to fix error Could not install the app on the device, read the error above for details.

### ISSUE THREAD

**Issue by sam9010** [facebook/react-native#27672]
how to fix it?
it worked 2 days ago
now not working
and this error 

BUILD FAILED in 13s
25 actionable tasks: 1 executed, 24 up-to-date
error Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html
error Command failed: gradlew.bat app:installDebug. Run CLI with --verbose flag for more details.

**Comment by cliffgor** [comment]
you could try uninstalling it from the device, it's clashing with versions

**Comment by gdoudeng** [comment]
+1
