### ISSUE TITLE
IOS crashes after splash screen on certain devices

### ISSUE THREAD

**Issue by Legi0n1138** [facebook/react-native#27675]
The app works fine in the simulator, builds run normally on some of the devices but they always crash on the client's iPhone right after the splash screen.
And for some reason, I can't fully symbolicate the crash logs, here's the maximum I can get:
[symbolicated.txt](https://github.com/facebook/react-native/files/4022096/symbolicated.txt)

As a side note, Android version works fine.

Can someone tell me what are the possible reasons for the issue? At this stage, I have no idea what to look for.

React Native version:
```
System:
    OS: macOS 10.15
    CPU: (4) x64 Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
    Memory: 277.82 MB / 5.86 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.2.0 - /usr/local/bin/node
    Yarn: 1.19.2 - /usr/local/bin/yarn
    npm: 6.13.1 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5

```

**Comment by jarvisluong** [comment]
The stack trace you gave explained that one native module was called and there was a fatal exception, which then crashes the app. It seems that the method `[RNSplashScreen show]` was the issue.

**Comment by Legi0n1138** [comment]
@jarvisluong thanks for the response, I'll investigate

**Comment by carlosmenezes** [comment]
@Legi0n1138 Have you found the issue? I'm facing the same problem here.

**Comment by Legi0n1138** [comment]
@carlosmenezes for me it turned out to be an inconsistent device languageCode detection that was conflicting with in-app localization
