### ISSUE TITLE
After migration to 61 developer menu looks different

### ISSUE THREAD

**Issue by lisichka999** [facebook/react-native#27686]
After migration to react-native 61 from 59 the developer menu in emulator looks different and when click on debug it is show me an error

![Simulator Screen Shot - iPhone 11 Pro - 2020-01-06 at 15 27 36](https://user-images.githubusercontent.com/44223548/71821024-a97ea400-3099-11ea-8156-b0a4e60335cb.png)
![Simulator Screen Shot - iPhone 11 Pro - 2020-01-06 at 15 30 51](https://user-images.githubusercontent.com/44223548/71821026-ab486780-3099-11ea-9deb-5e0f7d1ca13f.png)

Please advise,
Thanks

**Comment by lisichka999** [comment]
React Native version:
System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
    Memory: 5.41 GB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.0/11A419c - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1

## Steps To Reproduce

1. Edit Schema to 'Debug'
2. Run application from Xcode for some emulator
3. Once installed open developer menu

Describe what you expected to happen:
See the regular react native developer menu with Enable hot reloading option

**Comment by kelset** [comment]
Hello there 👋 by using the repro / the list of steps to reproduce, we can't actually see the reported bug on RN 0.61 so we'll close this issue.

It may have something to do with your local setup, please double check that you are using the correct version of Android Studio / XCode / Android NDK / Yarn / etc.

**Comment by lisichka999** [comment]
@kelset It is for sure something in my environment, my question is why I am getting this weird developer menu instead of regular React Native menu("Debug" instead of "Debug JS remotely" no "Enable hot reloading option"). I added Pod file to my project, may be it can be related?
Thanks

**Comment by kelset** [comment]
In 0.61 there was a overhaul of the debug experience via the new Fast Refresh feature. You can read more about it here -> https://facebook.github.io/react-native/blog/2019/09/18/version-0.61

**Comment by kelset** [comment]
Maybe try with a new `react-native init`-ed project?

**Comment by lisichka999** [comment]
@kelset, ok, I init a new project and saw the developer menu, it is looks different then mine. I think the problem is then the metro bundler does not run, it is just never opened. Do you have any idea why the metro bundler stop working? The App installed properly
