### ISSUE TITLE
TextInput component with placeholderTextColor attribute appears to overlap cursor

### ISSUE THREAD

**Issue by lao9** [facebook/react-native#27687]
Noticed in our application that the placeholder text appeared _above_  the cursor:

<img width="366" alt="Screen Shot 2020-01-03 at 6 48 14 PM" src="https://user-images.githubusercontent.com/4068853/71755674-ba40d700-2e59-11ea-89ac-373b21fc5849.png">

Occurs on both iOS and Android platforms.

Simply removing the `placeholderTextColor` attribute appears to fix the overlap:

![Image from iOS](https://user-images.githubusercontent.com/4068853/71829234-2dbd3100-3072-11ea-930e-a527840de341.jpg)

React Native version:

```
System:
    OS: macOS 10.15.2
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 1.21 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 28, 29
      Build Tools: 29.0.2
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  npmPackages:
    react: link:../libraries/node_modules/react => 16.11.0
    react-native: ^0.61.5 => 0.61.5
```

## Steps To Reproduce

1. Create a `TextInput`
2. Add a `placeholderTextColor` (in our case, the value was `#CFCECE`)

**Describe what you expected to happen:**

We expected the cursor to continue to appear over the placeholder text.

**Snack, code example, screenshot, or link to a repository:**

I tried to reproduce in this snack: https://snack.expo.io/B12ftrpkL 

Unfortunately, not reproducible on iOS, however it seems to be an issue _with or without_ the `placeholderTextColor` attribute on Android, so I'm not sure this simulator can be trusted for this specific issue. 😕 

![image](https://user-images.githubusercontent.com/4068853/71829482-c2279380-3072-11ea-903c-7625b538f7c2.png)

**Comment by ericlewis** [comment]
Does this occur the same for both multiline and single line inputs?
