### ISSUE TITLE
[Android] [Image] `tintColor` doesn't work on Android

### ISSUE THREAD

**Issue by bsansouci** [facebook/react-native#2769]
The title says it all. It works on iOS simulator. Here is the style:
```jsx
<View className="fab colored" style={{
  alignItems: 'center',
  justifyContent: 'center',
  height: 40,
  width: 40,
}}>
  <Image
    className="icon"
    style={{
      width: 24,
      height: 24,
      tintColor: 'white', // won't work
    }}
    source={{uri: "someImageUrl"}} />
</View>
```

**Comment by ide** [comment]
cc @mkonicek This is quite useful and should be possible to implement on Android for just Images.

**Comment by brentvatne** [comment]
:+1: this is an extremely useful feature

**Comment by andreicoman11** [comment]
'tintColor' works only when borderRadius is set, because of a bug in fresco (the android image library that is used in react-native-android). This bug will be fixed in the next version of fresco.

**Comment by mkonicek** [comment]
See also: [Known Issues](https://facebook.github.io/react-native/docs/known-issues.html)

Updated here: https://github.com/facebook/react-native/commit/0962d8f33bb55fe31038fb0f8a7c1d8c9acbbf2b

There's a small missing feature in the website generator that doesn't add the `ios` badge to styles.

**Comment by bsansouci** [comment]
@andreicoman11 thanks for the fix! Awesome work guys.
