### ISSUE TITLE
react-native-community/eslint and TypeScript 3.7

### ISSUE THREAD

**Issue by sidferreira** [facebook/react-native#27690]
`react-native-community/eslint` uses 
```
    "@typescript-eslint/eslint-plugin": "^1.5.0",
    "@typescript-eslint/parser": "^1.5.0",
    "prettier": "1.17.0"
```

which are limited to TypeScript `3.5.*`, blocking features like `null coalescing` and `optional chaining`. With the overrides below I managed to skip such errors and get only the errors I really had to deal with.

```
  "resolutions": {
    "**/@typescript-eslint/eslint-plugin": "2.15.0",
    "**/@typescript-eslint/parser": "2.15.0",
    "**/prettier": "1.19.1"
  },
```

I can create a PR fixing it if you guys want 

---

React Native version:
```
info Fetching system and libraries information...
System:
    OS: macOS 10.15.2
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.12.1 - ~/.nvm/versions/node/v12.13.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 27, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.4 => 0.61.4
```

## Steps To Reproduce

1. https://facebook.github.io/react-native/docs/typescript#adding-typescript-to-an-existing-project
2. Use `TypeScript 3.7` and `react-native-community/eslint:0.0.6`

**Comment by Hoffi-Coffi** [comment]
+1

**Comment by antt001** [comment]
+1

**Comment by romain-faust** [comment]
There is an open [PR](https://github.com/facebook/react-native/pull/27319) that could resolve the issue once merged.

**Comment by Naturalclar** [comment]
the community eslint config has updated prettier to v2 in this commit https://github.com/facebook/react-native/commit/89d04b5e4a3fd0b0f77b5a390c0aa62a3804e2bc#diff-07d8dac5e415f4617208ba79d55bc35f which should resolve the issue

**Comment by Naturalclar** [comment]
I believe this issue is resolved, as `@react-native-community/eslint-config` v1.0.0 supports newer version of typescript-estree and prettier

**Comment by hannojg** [comment]
Have just tested it with 1.1.0 doesn't seem to work (at least for me)

**Comment by sidferreira** [comment]
Now my only problem is that it ignores our `.prettierrc`...
