### ISSUE TITLE
[WebSocket & JS] Use a websocket module that doesn't require native modules

### ISSUE THREAD

**Issue by amasad** [facebook/react-native#277]
ws package requires native modules. And it's a bit fragile while installing. Let's find a pure JS one

**Comment by naartjie** [comment]
@amasad have you managed to get ws working at all? I would like to use it for Firebase.

Also, have you seen these: #579 #619 and this project: https://github.com/tptee/RCTWebSocket

**Comment by amasad** [comment]
This is about the server use of WS (for debugging). When you `npm install` it installs native extensions which slows down the install.

**Comment by naartjie** [comment]
ah, gotcha, doh. thanks ;-)

**Comment by vkurchatkin** [comment]
> ws package requires native modules

It doesn't, actually. Native deps are optional

**Comment by amasad** [comment]
@vkurchatkin great, how do we disable them?

**Comment by vkurchatkin** [comment]
I don't think we can. Being optional dependency means that if npm fails to install it, it still proceeds.

**Comment by brentvatne** [comment]
@amasad - Would this be a websocket polyfill that relies on polling? Is this still an issue that is worth following up on? It seems like the built in WebSocket Native Module works well :smile:

**Comment by amasad** [comment]
What I meant, is that it's easy to implement a websocket server without node c/c++ extensions. And I don't know why they have to be native. Anyways, I'm just being pedantic :P
