### ISSUE TITLE
React Native CLI does not produce a working app

### ISSUE THREAD

**Issue by shannonjensen** [facebook/react-native#27706]
After `npx react-native init`, `npx react-native run-android` produces a crashing app on android with the following error messages:

`TypeError: Cannot read property 'Direction' of undefined`
`Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)`

`run-ios` produces a similar error:
`TypeError: null is not an object (evaluating '_RNGestureHandlerModule.default.Direction')`

React Native version:
System:
    OS: macOS 10.15.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 199.85 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.5.0 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5

## Steps To Reproduce

1. `npx react-native init test`
2. `cd test`
3. `npx react-native run-android` or `npx react-native run-ios`

Describe what you expected to happen:
I expect the default initial app to show as the getting started docs indicate.

Snack, code example, screenshot, or link to a repository:

**Comment by smooJitter** [comment]
are you using react-native-gesture-handler?   I am experiencing the same issue and it seems to be related to the proper installation of react-native-gesture-handler.

**Comment by Jarred-Sumner** [comment]
have you tried running `cd ios; pod install; cd ../; react-native run-ios;`?

When I read this error `TypeError: Cannot read property 'Direction' of undefined`, I read this as: the parent object of `Direction` doesn't actually exist, so then I ask myself "what is the parent object and why doesn't the parent object exist?" It looks like that's `_RNGestureHandlerModule.default`, which is the babel-ified name of `react-native-gesture-handler`. I know that with React Native modules, they sometimes have constants defined in native code and its saying the native module (`RNGestureHandlerModule.default`) doesn't exist, so there's a good chance that the native module isn't linked correctly. Therefore, to ensure it's linked, try running `pod install`.

**Comment by smooJitter** [comment]
This worked for me...  Essential auto-linking takes a little extra effort...
[https://github.com/react-navigation/react-navigation/issues/5687#issuecomment-552505259](url)

**Comment by shannonjensen** [comment]
It does seem to be related to react-native-gesture-handler but I have not installed it. Literally, these are the basic instructions for initializing a new react-native project and I have added nothing whatsoever and it doesn't work. I am a bit confused as to how react-native's core instructions for initializing a new project without expo do not produce a working app.

**Comment by shannonjensen** [comment]
> have you tried running `cd ios; pod install; cd ../; react-native run-ios;`?
> 
> When I read this error `TypeError: Cannot read property 'Direction' of undefined`, I read this as: the parent object of `Direction` doesn't actually exist, so then I ask myself "what is the parent object and why doesn't the parent object exist?" It looks like that's `_RNGestureHandlerModule.default`, which is the babel-ified name of `react-native-gesture-handler`. I know that with React Native modules, they sometimes have constants defined in native code and its saying the native module (`RNGestureHandlerModule.default`) doesn't exist, so there's a good chance that the native module isn't linked correctly. Therefore, to ensure it's linked, try running `pod install`.

I did do this, to no effect. All pods already linked/installed by the `react-native init`

**Comment by shannonjensen** [comment]
I tried again with a new project and it works, no clue why this one doesn't, so closing.
