### ISSUE TITLE
Building failed when try to compile the RCTRequired Pod Lib 

### ISSUE THREAD

**Issue by zyangSir** [facebook/react-native#27705]
## React Native version:
System:  
    OS: macOS 10.15.2  
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz  
    Memory: 4.42 GB / 16.00 GB  
    Shell: 5.7.1 - /bin/zsh  
  Binaries:  
    Node: 10.0.0 - /usr/local/bin/node  
    Yarn: 1.21.1 - ~/.yarn/bin/yarn  
    npm: 6.10.3 - /usr/local/bin/npm  
    Watchman: 4.9.0 - /usr/local/bin/watchman    
  SDKs:  
    iOS SDK:  
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1  
  IDEs:  
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild   
  npmPackages:  
    react: 15.4.0 => 15.4.0  
    react-native: 0.61.0 => 0.61.0  
  npmGlobalPackages:  
    react-native-cli: 2.0.1  
    react-native-git-upgrade: 0.2.7  

## Steps To Reproduce

1.  upgrade an existing iOS project's RN codebase to version 0.61.0 manually(change the packge.json file, then yarn, then modify some components code to let it compliance with the lastes RN requirements, such as delete @providesModule syntax...)

2. edit the podfile(specific code see as below) , pod install, so far so good.

3. when I try to run the project, it failed when try to build the __RCTRequired PodLib__ , and compiler told me:

     	 `RCTRequired 2 issues`    
       `Lexical or Preprocessor Issue`  
       `'React/RCTBridgeDelegate.h' file not found`   
       `AppDelegate.h`  
       `'react/components/view/AccessibilityPrimitives.h' file not found`   
       `AccessibilityProps.h`  

 ##Describe what you expected to happen:      

Build all RN's relevant pod libs(esspecially __RCTRequired__) successfully, no error.

 ##Snack, code example, screenshot, or link to a repository:        
  
My pod file is as below:  
 *# Uncomment this line to define a global platform for your project  
platform :ios, '9.0'  

 *# Uncomment the next line to activate CDN boost up!  
 source 'https://github.com/CocoaPods/Specs.git'  

target 'MyProject' do  
  *# Uncomment this line if you're using Swift or would like to use dynamic frameworks   
  *# use_frameworks!   
  
  *#RN Core Code   
  pod 'React', :path => '../RN/node_modules/react-native/'   
  pod 'React-Core', :path => '../RN/node_modules/react-native/'    
  pod 'React-CoreModules', :path => '../RN/node_modules/react-native/React/CoreModules/'    
  pod 'React-Core/DevSupport', :path => '../RN/node_modules/react-native/'    
  
 * #RN Common Code Base    
  pod 'React-cxxreact', :path => '../RN/node_modules/react-native/ReactCommon/cxxreact'    
  pod 'React-jsi', :path => '../RN/node_modules/react-native/ReactCommon/jsi'    
  pod 'React-jsiexecutor', :path => '../RN/node_modules/react-native/ReactCommon/jsiexecutor'    
  pod 'React-jsinspector', :path => '../RN/node_modules/react-native/ReactCommon/jsinspector'    
  pod 'ReactCommon/turbomodule/core', :path => '../RN/node_modules/react-native/ReactCommon/'    
  pod 'Yoga', :path => '../RN/node_modules/react-native/ReactCommon/yoga'    

  *#RN Official Lib    
  pod 'React-RCTBlob', :path => '../RN/node_modules/react-native/Libraries/Blob/'    
  pod 'React-ART', :path => '../RN/node_modules/react-native/Libraries/ART/'    
  pod 'React-RCTActionSheet', :path => '../RN/node_modules/react-native/Libraries/ActionSheetIOS/'    
  pod 'React-RCTImage', :path => '../RN/node_modules/react-native/Libraries/Image/'    
  pod 'React-RCTNetwork', :path => '../RN/node_modules/react-native/Libraries/Network/'    
  pod 'React-RCTText', :path => '../RN/node_modules/react-native/Libraries/Text/'    
  pod 'React-RCTVibration', :path => '../RN/node_modules/react-native/Libraries/Vibration/'    
  pod 'React-RCTSettings', :path => '../RN/node_modules/react-native/Libraries/Settings/'    
  pod 'React-RCTLinking', :path => '../RN/node_modules/react-native/Libraries/LinkingIOS/'    
  pod 'React-RCTAnimation', :path => '../RN/node_modules/react-native/Libraries/NativeAnimation/'    
  
  pod 'FBLazyVector', :podspec => '../RN/node_modules/react-native/Libraries/FBLazyVector/FBLazyVector.podspec'    
  pod 'FBReactNativeSpec', :podspec => '../RN/node_modules/react-native/Libraries/FBReactNativeSpec/FBReactNativeSpec.podspec'    
  pod 'RCTRequired', :podspec => '../RN/node_modules/react-native/Libraries/RCTRequired/RCTRequired.podspec'    
  pod 'RCTTypeSafety', :podspec => '../RN/node_modules/react-native/Libraries/TypeSafety/RCTTypeSafety.podspec'    

 * #RN 3rd Plugins    
  pod 'DoubleConversion', :podspec => '../RN/node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'    
  pod 'glog', :podspec => '../RN/node_modules/react-native/third-party-podspecs/glog.podspec'    
  pod 'Folly', :podspec => '../RN/node_modules/react-native/third-party-podspecs/Folly.podspec'    
  pod 'ReactNativeNavigation', :podspec => '../RN/node_modules/react-native-navigation/ReactNativeNavigation.podspec'    

 * #视图模型类, MVVM设计模式使用
  pod 'ReactiveViewModel', '~> 0.3'    
  
 * #简洁优雅的轻量级约束布局库
  pod 'Masonry', '~> 1.0.0'    
  
  *#小巧快速的内存/磁盘缓存库
  pod 'YYCache', '~> 1.0.4'    
  
  *#小而美的弹出提醒框
  pod 'SVProgressHUD', '~> 2.2.5'    

  *# Crash 收集平台
  pod 'Bugly', '~> 2.5.0'    
  

  target 'MyProjectTests' do    
    inherit! :search_paths    
    # Pods for testing    
  end    

end

**Comment by zyangSir** [comment]
any one heard me?

**Comment by damoncoo** [comment]
New to RN, same issue here
