### ISSUE TITLE
Duplicate issue java.lang.UnsatisfiedLinkError: at com.facebook.soloader.SoLoader.doLoadLibraryBySoName (SoLoader.java:738)

### ISSUE THREAD

**Issue by john1jan** [facebook/react-native#27703]
Creating a new issue because old [issue](https://github.com/facebook/react-native/issues/25782) closed by @react-native-bot 

App crashes after android app bundle.

React Native version:
React Native Environment Info:
System:
OS: macOS 10.14.4
CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
Memory: 36.11 MB / 16.00 GB
Shell: 3.2.57 - /bin/bash
Binaries:
Node: 11.6.0 - /usr/local/bin/node
Yarn: 1.13.0 - /usr/local/bin/yarn
npm: 6.5.0 - /usr/local/bin/npm
SDKs:
Android SDK:
API Levels: 23, 25, 26, 27, 28
Build Tools: 23.0.1, 26.0.2, 28.0.3
System Images: android-19 | Intel x86 Atom, android-19 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
IDEs:
Android Studio: 3.4 AI-183.6156.11.34.5692245
Xcode: /undefined - /usr/bin/xcodebuild
npmPackages:
react: 16.8.5 => 16.8.5
react-native: 0.59.5 => 0.59.5
npmGlobalPackages:
generator-react-native-ignite: 1.13.0
react-native-cli: 2.0.1
react-native-ignite: 1.13.0

**Comment by witalobenicio** [comment]
This error is still happening with me on most recent version

**Comment by eshunnar** [comment]
Smae issue
