### ISSUE TITLE
[RN 0.60.6] YellowBox Warning Disable not working on Android

### ISSUE THREAD

**Issue by codeithuman** [facebook/react-native#27700]
When building the release (production) version of our app for Android, the YellowBox warnings are not disabled. When we build release (production) for iOS, the warnings are disabled as they should be. 

In addition, we tried disabling the warnings in our application's `index.js` file according to the React Native documentation, but YellowBox warnings still appear on the debug and release builds for Android. 

```JavaScript
// index.js
import { AppRegistry, YellowBox } from 'react-native'
import App from './src/screens/App'
import { name as appName } from './app.json'

console.disableYellowBox = true
YellowBox.ignoreWarnings(['Warning:'])

AppRegistry.registerComponent(appName, () => App)
```

To build and run our release Android application, we're using the following commands
```bash
cd android && ./gradlew bundleRelease
cd .. && react-native run-android --variant=release
```

![Screenshot_20200107-100556](https://user-images.githubusercontent.com/3494509/71917670-72f66700-3135-11ea-9478-e128c12c0a1b.png)

React Native version:
```bash
System:
    OS: macOS Mojave 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
    Memory: 2.28 GB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.4.0 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.13.1 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 27, 28
      Build Tools: 27.0.3, 28.0.3
      System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-Q | Intel x86 Atom, android-Q | Intel x86 Atom_64, android-Q | Google APIs Intel x86 Atom, android-Q | Google APIs Intel x86 Atom_64
      Android NDK: 20.0.5594570
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.6 => 0.60.6
```

Describe what you expected to happen:

We expect that building Android for release (production) will automatically disable YellowBox warnings, but it does not. 

We also expect that manually disabling YellowBox warnings will disable YellowBox warnings for debug and release builds, but it does not for Android. 

Again, this code in our root `index.js` file is not working.
```javascript
// index.js
console.disableYellowBox = true
YellowBox.ignoreWarnings(['Warning:'])
```

See the screenshot above for our visible warnings in an Android release (production) build running on the device.

**Comment by bashmentarium** [comment]
I am using RN v0.61.5 and the ```componentWillReceiveProps``` warning persists.

**Comment by codeithuman** [comment]
I was able to fix the issue by rebuilding our `index.android.bundle`. I had not included this step in our build and release process. I believe our previous `index.android.bundle` was built for debugging, hence the yellow box warnings. 

I added the following scripts to our package.json and run them in our build and release process:
```json
// package.json
{
  "scripts": {
    "build-android-release": "yarn run refresh-android-bundle && cd android && rm -r app/build && ./gradlew clean && ./gradlew bundleRelease && cd ..",
    "run-android-release": "react-native run-android --variant=release",
    "refresh-android-bundle": "yarn run remove-android-bundle && yarn run bundle-android",
    "remove-android-bundle": "rm android/app/src/main/assets/index.android.bundle",
    "bundle-android": "react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res"
  },
}
```

**Comment by up-ayudkin** [comment]
disable yellow box
