### ISSUE TITLE
Android: Unable to build application. Problem with react-native config

### ISSUE THREAD

**Issue by malashkevich** [facebook/react-native#27707]
Unable to build an android application on CI when the application is not in the git root folder.

React Native version:
System:
    OS: macOS 10.15.2
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 3.50 GB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.4 AI-183.5429.30.34.5452501
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5

## Steps To Reproduce

1. make a root directory
2. in that root directory run react-native init
3. try to compile application on bitrise

Describe what you expected to happen:

I'm using Bitrise for CI which under the hood uses fastlane. So I've created a new project and tried to build it on a build server. Android build produces the next error:

```
:ReactNative:Unexpected empty result of running 'npx --quiet --no-install react-native config' command from 'null' directory.
:ReactNative:Running 'npx --quiet --no-install react-native config' command from 'null' directory failed.
FAILURE: Build failed with an exception.
* Where:
Script '/Users/vagrant/git/app/node_modules/@react-native-community/cli-platform-android/native_modules.gradle' line: 170
* What went wrong:
A problem occurred evaluating script.
> java.lang.Exception (no error message)
```

There are several bugs regarding it:
https://github.com/react-native-community/cli/issues/804
https://github.com/facebook/react-native/issues/27443

Not sure if this is cli issue or react-native one. But this bug is for tracking status.

**Comment by malashkevich** [comment]
@rickhanlonii will you have a chance to look at this one? Let me know if you need more info here.

**Comment by rickhanlonii** [comment]
Hey @malashkevich sorry for the delay here. It appears the issue in react-native cli which has been fixed: https://github.com/react-native-community/cli/issues/804. If you're still seeing it in the latest version let me know and I'll re-open.
