### ISSUE TITLE
React native ios pod install issue

### ISSUE THREAD

**Issue by StarkAndy** [facebook/react-native#27716]
I been facing issues related with react-native ios .I was adding library manually but there are few library for which pod install was required to get it running .As soon as i go with pod install my whole project goes messed up and i have to remove all the ios folder and node-modules and run again .It's kind of tedious task.I have to either remove library import <React/example.h> to import "example.h" .Even then it doesn't work for other library.

React Native version:
0.59.10

## Steps To Reproduce
Pod install command inside ios folder

Expected to happen:
pod install should work without any issue

**Comment by gokhandoslu** [comment]
Cocoapods support added after RN >= 0.60.0
https://github.com/facebook/react-native/releases/tag/v0.60.0
