### ISSUE TITLE
after build in xcode for ios react native 

### ISSUE THREAD

**Issue by achalakk** [facebook/react-native#27718]
<img width="1513" alt="Screenshot 2020-01-09 at 4 43 01 PM" src="https://user-images.githubusercontent.com/56485672/72063218-61f95180-32ff-11ea-8db2-2da0aab15af2.png">

**Comment by StarkAndy** [comment]
@achalakk  hi seems like your derived file inside ios is creating issues try deleting it and rebuild the project again.
