### ISSUE TITLE
BatchedBridge.enqueueNativeCall Parameters Reversed in BatchedBridge.NativeModules genMethod Call

### ISSUE THREAD

**Issue by jstheoriginal** [facebook/react-native#27714]
The success and fail callbacks seem to be reversed in the `genMethod` call in `NativeModules.js` when calling `BatchedBridge.enqueueNativeCall`. The method indicates that onFail is the 4th parameter and onSuccess is the 5th parameter, but when the method is called in `genMethod` it passes the failure callback to the 5th parameter (success) instead of the 4th. Not sure what this is affecting but I just noticed it while debugging an issue in RN 0.59 and notice it's still this way on master.

The reversed params are here: https://github.com/facebook/react-native/blob/66601e755fcad10698e61d20878d52194ad0e90c/Libraries/BatchedBridge/NativeModules.js#L110

The method signature is here: https://github.com/facebook/react-native/blob/66601e755fcad10698e61d20878d52194ad0e90c/Libraries/BatchedBridge/MessageQueue.js#L253

React Native version:
0.59+ at least

**Comment by lhuazai** [comment]
In my .js file, i  require('BatchedBridge') this module , it can't be find,my RN version is 0.61.5
