### ISSUE TITLE
Live reload: app reloads when editing redux action, but doesn't use latest code until manual reload

### ISSUE THREAD

**Issue by dancherb** [facebook/react-native#27723]
RN 0.61.5

When editing a redux action that is imported into a component via react-redux connect(), the edit triggers a full app reload. However, the latest action code isn't actually used - for example, if I've added a console.log this won't occur until I manually (CTRL+R) reload the app. This means edits to actions often require two app reloads (one automatic and one manual).

**Comment by jimtang9527** [comment]
@dancherb have you solved this problem? The hot update is incomplete. Is there a configuration for the code to reload completely. It takes a lot of time to develop the app by hand every time.
