### ISSUE TITLE
chrome devtools performance tab can not find the debugger worker thread

### ISSUE THREAD

**Issue by anhuiliujun** [facebook/react-native#27726]
React Native version: 0.61.5
## Steps To Reproduce

1. npx react-native init AwesomeProject
2. npx react-native run-ios
3. cmd + D
4. open the http://localhost:8081/debugger-ui/
5. use the performance tab to record performance
6. clear the recorded performance
7. repeat 4 to 6

Describe what you expected to happen:

expected the result have debugger worker thread

Snack, code example, screenshot, or link to a repository:

![image](https://user-images.githubusercontent.com/721395/72129466-48b0dd80-33b1-11ea-829f-01e9662d8956.png)

demo: https://github.com/anhuiliujun/react-native-debug-performance

**Comment by AndrewMorsillo** [comment]
Start the profiler then reload your app (cmd+r) while the profiler is still running. There seems to be a bug where performance profiling doesn't get picked up until a reload happens. The state of react-native debugging tools is unfortunate at the moment, many of them don't work as stated in the docs.
