### ISSUE TITLE
Fast refresh is not working

### ISSUE THREAD

**Issue by romanakash** [facebook/react-native#27734]
So fast refreshing was working smoothly on an android Pixel 3 emulator and then one day it stopped working. Any changes to the code are not updated automatically, while manually reloading seems to load the new code.

React Native version:
System:
    OS: Linux 5.0 Ubuntu 18.04.2 LTS (Bionic Beaver)
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 1.51 GB / 15.31 GB
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 12.14.0 - /usr/local/bin/node
    npm: 6.13.4 - /usr/local/bin/npm
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5

## Steps To Reproduce

1. Enable Fast Refresh on Android

Describe what you expected to happen:

Expected app to automatically refresh when Fast Refresh is enabled and there are new changes to the code. Tried clearing metro and npm cache but no luck ☹️

**Comment by tomoima525** [comment]
Related to this https://github.com/facebook/react-native/issues/27029#issuecomment-561597907

**Comment by romanakash** [comment]
Tried the solution mentioned in the comment but the problem still persists. Also tried going back to an earlier commit still no luck.

**Comment by romanakash** [comment]
Deleting the local repo and cloning the same commit from GitHub seems to have fixed the issue.

**Comment by guillaume-g** [comment]
Just to give an answer, removing the index.lock in the .git folder fix the issue.
I have not a simple idea why.

**Comment by outrowender** [comment]
I dont even have git in my project and i have the same issue

**Comment by knro** [comment]
I tried everything. There is no index.git in my git. Restarted and deleted the app several times. Cleared all cache and still fast refresh is not working. Now it's a pain to develop must restart on every small change.
