### ISSUE TITLE
use fbjni as gradle dependency to solve flipper issue for android

### ISSUE THREAD

**Issue by gengjiawen** [facebook/react-native#27732]
See https://github.com/facebook/flipper/issues/707#issuecomment-573025000.

I want to know is there some hack or pitfalls in current repo.

I see fbjni already as an indendenct repo https://github.com/facebookincubator/fbjni.

cc @passy @swolchok

**Comment by rickhanlonii** [comment]
I believe this is the strategy in https://github.com/facebook/react-native/pull/27729

**Comment by gengjiawen** [comment]
> I believe this is the strategy in #27729

yeap.
