### ISSUE TITLE
Packager as webpack plugin

### ISSUE THREAD

**Issue by baverman** [facebook/react-native#2773]
Webpack is a perfect tool to resolve deps. It will be really nice to delegate most work to webpack and do simple wrapping in tiny plugin.

**Comment by mkonicek** [comment]
React Native uses the React Native Packager and won't be switching to Webpack soon, I think there was a long discussion on this topic somewhere.

Have you checked out https://github.com/mjohnston/react-native-webpack-server?

**Comment by mkonicek** [comment]
See also https://github.com/facebook/react-native/issues/395
