### ISSUE TITLE
react-native run-android can't notice package.json 's change

### ISSUE THREAD

**Issue by jiamo** [facebook/react-native#2774]
After I add a new depence in package.json, I run `react-native run-android ` can't take effect. the mobile app can't find the module I add.  I close the package console  by coincidence  and re run  `react-native run-android ` will work fine. So do we need make `react-native run-android ` to notice the change of source code's module depends?

**Comment by mkonicek** [comment]
You need to run `npm install` when you update `package.json`, I believe that's a standard practice when working with JavaScript apps.

`react-native run-android` doesn't do this automatically and I'm not convinced it should, cc @foghina
