### ISSUE TITLE
some javascript is slow why not use javascript engine v8

### ISSUE THREAD

**Issue by sirpy** [facebook/react-native#27748]
Using javascript crypto libraries is very slow on JSC on android (device+simulator) while on iOS simulator it seems to run fine
Using v8 with JIT is significantly faster.

**Comment by fabriziobertoglio1987** [comment]
https://github.com/Kudo/react-native-v8

**Comment by sirpy** [comment]
@fabriziobertoglio1987 like i said in the issue description v8 with JIT is in did much faster.
The repo you pointed to only has it without JIT enabled (ie slow), i've made my own fork and PR for them to add JIT (which i've tested and in did it's fast) to their build matrix.
My question here, is why is it fast on iOS and not on android, is JIT  truly enabled on android like the react docs says?

**Comment by ssssssssssss** [comment]
Upgrade JSC for Android. https://github.com/react-native-community/jsc-android-buildscripts

**Comment by sirpy** [comment]
@ssssssssssss i've tried it and it is still slow. faster but still slow. packaged JSC takes 4seconds to run my benchmark.
the latest version takes 1.8 seconds
react native v8 with JIT 0.5 seconds

**Comment by ssssssssssss** [comment]
What's the bottleneck? Did you do any profiling?

**Comment by sirpy** [comment]
> What's the bottleneck? Did you do any profiling?

nope don't know how. But given that jit enabled run fast it's probably the intensive repetitive loops and function calls of encryption algorithms
