### ISSUE TITLE
placeholder's text for TextInput  disappears on touch

### ISSUE THREAD

**Issue by HadisSharif** [facebook/react-native#27744]
Sometimes when I touch the TextInput, the placeholder text disappers and the same time keyboard doesn't pop up. I should reload the page to get the placeholder text again.

**Comment by fabriziobertoglio1987** [comment]
thanks @HadisSharif, please include additional information to your question. For example your sourcecode and a detailed explanation of your issue

**Comment by xgAnd** [comment]
> thanks @HadisSharif, please include additional information to your question. For example your sourcecode and a detailed explanation of your issue

hello guy i guess this error is like this.
https://github.com/facebook/react-native/issues/27655#issuecomment-572472942
