### ISSUE TITLE
not allowing consideration of ... deferring to libdir

### ISSUE THREAD

**Issue by JacobSolomonUCF** [facebook/react-native#27754]
Hi, 

We are developing a GIS Application and we are using React Native to support both iOS and Android. Our company's primary GIS Provider is Esri and they provide both an iOS SDK and Android SDK for consuming their services. We have created a port to allow us to integrate their SDK with our RN project.

Our issue is that during the initial install of the Android application we are seeing the below error message which results in a white screen. The solution to this is to re-launch the application and the error goes away. I am unsure if the error is a problem with the Android SDK provided by Esri or ApkSoSource.

I have opened a ticket in SoLoader & on the ESRI Android SDK but have yet to receive a response from either. Any additional information that can be provided on why we are receiving this error would be greatly beneficial.

React Native version:

```
System:
    OS: macOS 10.15.1
    CPU: (4) x64 Intel(R) Core(TM) i7-4558U CPU @ 2.80GHz
    Memory: 3.95 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.16.3 - /usr/local/opt/node@10/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/opt/node@10/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-25 | Google APIs ARM 64 v8a, android-25 | Google APIs ARM EABI v7a, android-28 | Android TV Intel x86 Atom, android-28 | China version of Wear OS Intel x86 Atom, android-28 | Wear OS Intel x86 Atom, android-28 | Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5977832
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.2 => 0.61.2
  npmGlobalPackages:
    create-react-native-module: 0.12.0
    react-native-cli: 2.0.1
    react-native: 0.61.4
```

## Steps To Reproduce

1. Clone the dummy project & install deps
2. Run on Android emulator

Describe what you expected to happen:
I would expect the application to load without a white screen after being installed to the device.

Snack, code example, screenshot, or link to a repository:
Dummy project that replicates the issue: https://github.com/JacobSolomonUCF/RN-DummyArcGIS

Additional Refereneces:
https://community.esri.com/thread/246073-android-sdk-weird-behavior
https://github.com/facebook/SoLoader/issues/57

**Comment by JacobSolomonUCF** [comment]
The error we are receiving on the first launch after install
```
D/ApkSoSource: not allowing consideration of lib/arm64-v8a/libc++_shared.so: deferring to libdir
 not allowing consideration of lib/arm64-v8a/libfb.so: deferring to libdir
 not allowing consideration of lib/arm64-v8a/libfolly_futures.so: deferring to libdir
 not allowing consideration of lib/arm64-v8a/libfolly_json.so: deferring to libdir
D/ApkSoSource: not allowing consideration of lib/arm64-v8a/libglog.so: deferring to libdir
 not allowing consideration of lib/arm64-v8a/libglog_init.so: deferring to libdir
 not allowing consideration of lib/arm64-v8a/libimagepipeline.so: deferring to libdir
 not allowing consideration of lib/arm64-v8a/libjsc.so: deferring to libdir
 not allowing consideration of lib/arm64-v8a/libjscexecutor.so: deferring to libdir
 not allowing consideration of lib/arm64-v8a/libjsijniprofiler.so: deferring to libdir
 not allowing consideration of lib/arm64-v8a/libjsinspector.so: deferring to libdir
D/ApkSoSource: not allowing consideration of lib/arm64-v8a/libnative-filters.so: deferring to libdir
 not allowing consideration of lib/arm64-v8a/libnative-imagetranscoder.so: deferring to libdir
 not allowing consideration of lib/arm64-v8a/libreactnativeblob.so: deferring to libdir
 not allowing consideration of lib/arm64-v8a/libreactnativejni.so: deferring to libdir
D/ApkSoSource: not allowing consideration of lib/arm64-v8a/libruntimecore.so: deferring to libdir
 not allowing consideration of lib/arm64-v8a/libruntimecore_java.so: deferring to libdir
 not allowing consideration of lib/arm64-v8a/libyoga.so: deferring to libdir
```

**Comment by fabriziobertoglio1987** [comment]
This issue is connected to 64bit libraries which should be supported in rn-0.61.2

Maybe you have an issue with your configurations? As explained in the [following post](https://github.com/facebook/react-native/issues/11694#issuecomment-323647061), a similar problem was solved with the correct settings in `android/app/build.gradle`

```gradle
android {
    compileSdkVersion rootProject.ext.compileSdkVersion
            include "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
        }
    }
    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }

    // etc..etc..
    buildTypes {
       // etc..
    }
}
```

this example was taken from [the upgrade helper](https://react-native-community.github.io/upgrade-helper/?from=0.59.10&to=0.61.2)

**Comment by JacobSolomonUCF** [comment]
Thanks for the reply @fabriziobertoglio1987 

We are already doing something similar and if I analyze the APK I see all .so's there. What I find very strange is that this issue only occurs during the initial load after installing the application. All subsequent launches do not face this issue.

![apk](https://user-images.githubusercontent.com/19891051/72283961-78f0ba00-3605-11ea-89a2-05f646258283.png)

**Comment by JacobSolomonUCF** [comment]
Issue's root cause was related to the version of the ArcGIS Android SDK
