### ISSUE TITLE
React-native run-ios error Failed to build iOS project

### ISSUE THREAD

**Issue by DucSilva** [facebook/react-native#27750]
When i run react-native run-ios i got an error (as image below). Can anyone help me fix this?

<img width="1740" alt="Screen Shot 2020-01-13 at 3 24 29 PM" src="https://user-images.githubusercontent.com/46064085/72246243-de07d800-3624-11ea-8119-7dd09aff5a38.png">

**Comment by fabriziobertoglio1987** [comment]
https://github.com/Kudo/react-native-v8
