### ISSUE TITLE
Change text and emoji fontSize in TextInput on iOS

### ISSUE THREAD

**Issue by gurbela** [facebook/react-native#27752]
There is a problem on the `TextInput` which contains `text` and `emoji` together and try to resize them or change `color/fontSize`  by other component (not manually) .

Resizing, changing `color` and `fontSize` of `TextInput`'s content works only without `emoji`.

Can you help how to resolve `TextInput` problem (described above) with text+emoji content?

I don't have this problem with Android. 

`allowFontScaling={false}` => Didn't helped me.

React Native version: 0.61.5

**Comment by antbui** [comment]
Hello @gurbela 

I'm getting the same issue with you when trying to apply style for text input with text and emoji.

Did you have any workaround to overcome this issue?

**Comment by gurbela** [comment]
Hi,

Hacks => force render the component. It is workaround.

```

let timeout = null;
const lastTextValue = useRef('');
const [textValue, setTextValue] = useState('');


const onFontSizeChange = value => {
    setFontSize(val);
    fontSizeIsChanged.current = !fontSizeIsChanged.current;
};

// 
const updateinput = () => {
    if (Platform.OS === 'ios') {
      lastTextValue.current = textValue;
      if (timeout == null) {
        setTextValue(`${lastTextValue.current} `);
        timeout = setTimeout(() => {
          timeout = null;
          setTextValue(lastTextValue.current.trim());
        }, 1);
      }
    }
  };

useEffect(() => {
    input.current.setNativeProps({
      style: {
        fontSize,
        lineHeight: fontSize + 4,
      },
    });
    updateinput();
  }, [fontSizeIsChanged.current]);
```
