### ISSUE TITLE
Release mode shows a crash with error Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'DevSettings' could not be found. Verify that a module by this name is registered in the native binary.

### ISSUE THREAD

**Issue by nihp** [facebook/react-native#27758]
I am trying to build by app in release mode and need to run in simulator and in real device. 

In simulator I am getting the error as 

```
Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'DevSettings' could not be found. Verify that a module by this name is registered in the native binary.
2020-01-14 11:36:50.365808+0530 App[23363:273674] *** Terminating app due to uncaught exception 'RCTFatalException: Unhandled JS Exception: Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'DevSettings' could not be found. Verify that a module by this name is registered in the native binary.', reason: 'Unhandled JS Exception: Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'DevSettings' could not be found. Verify that a module by this name is registered in the na..., stack:
```

react-native info

```
System:
    OS: macOS Mojave 10.14.2
    CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
    Memory: 38.57 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 9.4.0 - ~/.nvm/versions/node/v9.4.0/bin/node
    npm: 5.6.0 - ~/.nvm/versions/node/v9.4.0/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
  IDEs:
    Xcode: 10.1/10B61 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
```

**Comment by PJLX** [comment]
I met the same problem。
```
2020-04-07 17:49:43.375 [error][tid:com.facebook.react.JavaScript] Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'DevSettings' could not be found. Verify that a module by this name is registered in the native binary.
2020-04-07 17:49:43.411 [fatal][tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'DevSettings' could not be found. Verify that a module by this name is registered in the native binary.
```

**Comment by yaronlevi** [comment]
RN@0.61.4 when running on  the iOS simulator
Happens here also:
`Unhandled JS Exception: Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'DevSettings' could not be found. Verify that a module by this name is registered in the na..., stack:
getEnforcing@5462:28
<unknown>@41853:50
loadModuleImplementation@271:14
<unknown>@41812:40
loadModuleImplementation@271:14
<unknown>@36393:18
loadModuleImplementation@271:14
<unknown>@29638:16
loadModuleImplementation@271:14
guardedLoadModule@163:47`

Any directions for solution?

**Comment by Sunlity** [comment]
I met the same problem
I find that when i set --dev to false. it can run well.
So I think,You can add the config "__dev false" when you create the js.bundle

**Comment by cbedoy** [comment]
I still having same issue since three weeks ago, I've been trying different solutions. I created new project with 0.63.2 it works
but I can't figure it out why mine still broken.

**Comment by dehypnosis** [comment]
Anyone has clear solution?

**Comment by gabrieldonadel** [comment]
This is probably related to  https://github.com/facebook/react-native/issues/26987

**Comment by mrshahzeb7** [comment]
any solution to this ?

**Comment by elsurudo** [comment]
I'm having the same issue as well, and tried what solutions I could, including this:

> I met the same problem
> I find that when i set --dev to false. it can run well.
> So I think,You can add the config "--dev false" when you create the js.bundle

Any other ideas?

**Comment by elsurudo** [comment]
Well, I feel pretty dumb, but in my case it ended up being that _I was using DevSettings in my index.js file_, so I needed to make sure that code only ran in dev, like so:

```
if (Config.ENV == 'development') {
  ...
}
```
