### ISSUE TITLE
Invariant Violation: Native module cannot be null. (IOS)

### ISSUE THREAD

**Issue by massoprod** [facebook/react-native#27753]
Hi there, I have an issue with upgrading react-native version from 0.59.10 to 0.61.5. We are using our own native modules and it seems like to be problem with them. This problem I have only on iOS.

React Native version:
```
System:
   OS: macOS 10.15.2
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 70.44 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.5.0 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.12.0 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 27, 28, 29
      Build Tools: 28.0.3, 29.0.0, 29.0.1, 29.0.2
      System Images: android-26 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
      Android NDK: 20.0.5594570
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
    react-native: 0.61.5
```

![Simulator Screen Shot - iPhone 8 - 2020-01-13 at 15 28 32](https://user-images.githubusercontent.com/8200096/72263953-2d94d680-361a-11ea-8231-cbf864ee039c.png)

Thanks

**Comment by fabriziobertoglio1987** [comment]
Read more about [`react native auto linking`](https://github.com/react-native-community/cli/blob/master/docs/autolinking.md).
[Try `manual linking`](https://facebook.github.io/react-native/docs/linking-libraries-ios#manual-linking)

**Comment by massoprod** [comment]
@fabriziobertoglio1987 what about Pod files? Do I need to do something with them? How does it work in the new react-native version?

**Comment by fabriziobertoglio1987** [comment]
https://github.com/react-native-community/cli/blob/master/docs/autolinking.md#how-can-i-autolink-a-local-library

>How can I autolink a local library?

>We can leverage CLI configuration to make it "see" React Native libraries that are not part of our 3rd party dependencies. To do so, update your react-native.config.js's dependencies entry to look like this:

```
// react-native.config.js
module.exports = {
  dependencies: {
    'local-rn-library': {
      root: '/root/libraries',
    },
  },
};
```

**Comment by fabriziobertoglio1987** [comment]
https://github.com/react-native-community/cli/blob/master/docs/autolinking.md#platform-ios

> Platform iOS

>The native_modules.rb script required by Podfile gets the package metadata from react-native config during install phase and:

    Adds dependencies via CocoaPods dev pods (using files from a local path).
    Adds build phase scripts to the App project’s build phase. (see examples below)

>This means that all libraries need to ship a Podspec either in the root of their folder or where the Xcode project is. Podspec references the native code that your library depends on.

>The implementation ensures that a library is imported only once. If you need to have a custom pod directive then include it above the use_native_modules! function.

>What do I need to have in my package to make it work?

>You’re already using Gradle, so Android support will work by default.

>On the iOS side, you will need to ensure you have a Podspec to the root of your repo. The react-native-webview Podspec is a good example of a package.json-driven Podspec. Note that CocoaPods does not support having /s in the name of a dependency, so if you are using scoped packages - you may need to change the name for the Podspec.
How can I customize how autolinking works for my package?

>A library can add a react-native.config.js configuration file, which will customize the defaults.
How can I disable autolinking for unsupported library?

>During the transition period some packages may not support autolinking on certain platforms. To disable autolinking for a package, update your react-native.config.js's dependencies entry to look like this:

```javascript
// react-native.config.js
module.exports = {
  dependencies: {
    'some-unsupported-package': {
      platforms: {
        android: null, // disable Android platform, other platforms will still autolink if provided
      },
    },
  },
};
```
