### ISSUE TITLE
[Docs] Need a section on performance

### ISSUE THREAD

**Issue by brentvatne** [facebook/react-native#2775]
Should discuss general philosophy, terminology, and common performance problems and solutions..

eg: 
- `InteractionManager.runAfterInteractions` to defer rendering when pushing a new route.
- When to use `shouldRasterizeIOS` and the Android equivalent
- Animated vs LayoutAnimation
- transform scale vs width/height on images
- removeClippedSubviews

**Comment by mkonicek** [comment]
Thanks for doing this!

**Comment by corbt** [comment]
Also would be a good place to document how to test your app's performance in production mode. I can't find any docs related to this, at least for Android.

**Comment by mkonicek** [comment]
We're working on tooling internally but it's not ready to be open sourced yet.

**Comment by mkonicek** [comment]
Please note this is a very early release we tried to get out to you as early as possible.
