### ISSUE TITLE
[Text] this is a bug for wrap with a long string

### ISSUE THREAD

**Issue by tanqq1** [facebook/react-native#27768]
`render(){
    // 现在的问题其实可以总结为单词间换行  word-break:'break-all'
    const text = `no use, that is so hard!!this is a link，https://segmentfault.com/a/1190000015995283?utm_source=tag-newest `;
    return (
      <View style={styles.containers}>
        <Text 
        style={styles.text} 
        >
          1、{text}
        </Text>
        <Text style={styles.text}>2、this islonglongloooooooooooooooooooooooooooooooogString</Text>
      </View>
    )
  }`

![image](https://user-images.githubusercontent.com/32407541/72422320-2e19a280-37bd-11ea-9f0a-a4eeb931d4ae.png)

version Infos:
"react": "16.8.3",
"react-native": "0.59.10",

## Steps To Reproduce

1. when string has some special charactor and some words is  long ，that will  has a long space within string when word Wrap , i think this is a bug for Text component
2.

**Comment by Leehee1on** [comment]
+1
