### ISSUE TITLE
Attempt to invoke virtual method 'double java.lang.Double.doubleValue()' on a null object reference

### ISSUE THREAD

**Issue by chayankiit** [facebook/react-native#27769]
Environment
---------------------------------------------------------------------------------------------------

System:
    OS: Linux 5.0 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
    Memory: 7.79 GB / 15.55 GB
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 12.14.0 - ~/.nvm/v12.14.0/bin/node
    Yarn: 1.21.1 - ~/.yarn/bin/yarn
    npm: 6.13.4 - ~/.nvm/v12.14.0/bin/npm
  SDKs:
    Android SDK:
      API Levels: 24, 26, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-24 | Android TV Intel x86 Atom, android-24 | ARM 64 v8a, android-24 | ARM EABI v7a, android-24 | Intel x86 Atom, android-24 | Intel x86 Atom_64, android-24 | Google APIs ARM 64 v8a, android-24 | Google APIs ARM EABI v7a, android-24 | Google APIs Intel x86 Atom, android-24 | Google APIs Intel x86 Atom_64, android-24 | Google Play Intel x86 Atom, android-26 | Android TV Intel x86 Atom, android-26 | China version of Android Wear Intel x86 Atom, android-26 | Android Wear Intel x86 Atom, android-26 | Intel x86 Atom, android-26 | Intel x86 Atom_64, android-26 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom_64, android-26 | Google Play Intel x86 Atom, android-28 | Android TV Intel x86 Atom, android-28 | China version of Wear OS Intel x86 Atom, android-28 | Wear OS Intel x86 Atom, android-28 | Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64, android-29 | Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5

--------------------------------------------------------------------------------------------------------------------------
when the user taps on the next or previous buttons, a state change happens.
I get this error when the user taps on these buttons rapidly.
--------------------------------------------------------------------------------------------------------------------------

![WhatsApp Image 2020-01-15 at 15 16 00](https://user-images.githubusercontent.com/14080295/72423579-85fade00-37aa-11ea-8839-b8e539b9eac6.jpeg)

**Comment by Developer-Nijat** [comment]
Seems to be a problem with react-native-reanimated 1.5.0 which was released a few hours ago. Downgrading to 1.4.0 solved it

`"react-native-reanimated": "1.4.0"`

**Comment by pete-wiley** [comment]
@Developer-Nijat THANK YOU. I have been banging my head on the wall over this for the past hour and a half. I could not hit that thumbs up hard enough.

**Comment by lordmaul** [comment]
I am getting this error when I call animateToRegion on a map obj (react-native-maps). any fix would be appreciated?
