### ISSUE TITLE
[Docs] BackAndroid documentation needed

### ISSUE THREAD

**Issue by brentvatne** [facebook/react-native#2777]
"To get BackAndroid to work you need to return `false` in your back event handler. This will prevent exiting the app and you can handle the transition to the previous screen. For an example check out the UIExplorer sample app.

I'm sure I documented this somewhere, but it probably got overwritten at some point (we sync code between a few places and sometimes this happens). Will add it back."

As per: https://corbt.com/posts/2015/09/16/one-day-with-react-native-for-android.html#comment-2256643777

**Comment by corbt** [comment]
Note that this isn't just a documentation issue -- using the default template project `BackAndroid` won't work at all because the `onBackPress` event is never handed to the JS. I've opened #2801 to amend this.

**Comment by corbt** [comment]
Also @brentvatne I think your description of the return is backwards -- to indicate that the event has been handled I need to return `true`.

**Comment by mkonicek** [comment]
Awesome, thanks @corbt!

**Comment by mkonicek** [comment]
This has been fixed.
