### ISSUE TITLE
TextInput ignores numberOfLines prop

### ISSUE THREAD

**Issue by orhan** [facebook/react-native#27772]
`TextInput` component that have its `multiline` and `numberOfLines` props enabled do **not** limit their height automatically, as one would expect. Instead the `maxHeight` has to be set to get the desired behavior.

React Native version:
  System:
    OS: macOS 10.15.2
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 40.17 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.12.0 - ~/.nvm/versions/node/v12.13.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 26, 28, 29
      Build Tools: 26.0.2, 28.0.3, 29.0.2
      System Images: android-29 | Google Play Intel x86 Atom
      Android NDK: 20.0.5594570
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.6 => 0.60.6 
  npmGlobalPackages:
    react-native-cli: 2.0.1

## Steps To Reproduce

1. Use `multiline={true}` and `numberOfLines={2}` prop in a `TextInput` component that has multiple at least 3 lines of input

Describe what you expected to happen:
The height of the `TextInput` should be limited to 2 lines of text, but it expands along when entering more than 2 lines. Only way to restrict the height is to calculate and set the `maxHeight` of the component.

## Expo Snack

https://snack.expo.io/rynCx!3lL

**Comment by Archulan** [comment]
@orhan Have you verified it on the latest version?

**Comment by daviddossantos** [comment]
https://github.com/daviddossantos/textinput-multiline-multiplataform, maybe it works
