### ISSUE TITLE
【Text】A long text wrap leaves a lot of space

### ISSUE THREAD

**Issue by tanqq1** [facebook/react-native#27770]
**i need help!!!**
`
render(){
    const text = "no use, that is so hard!!this is a link，https://segmentfault.com/a/1190000015995283?utm_source=tag-newest ";
    return (
      <View style={styles.containers}>
        <Text 
        style={styles.text} 
        >
          1、{text}
        </Text>
        <Text style={styles.text}>2、this islonglongloooooooooooooooooooooooooooooooogString</Text>
      </View>
    )
  }
`
![image](https://user-images.githubusercontent.com/32407541/72423894-0aa42700-37c0-11ea-9d85-5ea5a9a80178.png)

![image](https://user-images.githubusercontent.com/32407541/72423929-198ad980-37c0-11ea-8002-187f7be9b90d.png)

**css**
![image](https://user-images.githubusercontent.com/32407541/72424488-117f6980-37c1-11ea-93bf-5127e4d2e81a.png)

React Native version:
"react": "16.8.3",
"react-native": "0.59.10",

## Steps To Reproduce
1、https://github.com/facebook/react-native/issues/22888，that issue described  same question but not resolved yet

**Comment by tanqq1** [comment]
Some special characters,like ? = ，That would lead to this situation

**Comment by aihui0730** [comment]
that bothers me too ,I'm going mad!!!
