### ISSUE TITLE
KeyboardAvoidingView doesn't work properly with TextInput with multiline enabled

### ISSUE THREAD

**Issue by milgron** [facebook/react-native#27788]
When you have a KeyboardAvoidingView with a TextInput with multiline=true, the "translating" effect just doesn't work (at least in ios)

React Native version:
0.59.8 (Expo sdk 34.0.1)

## Steps To Reproduce

1. Add a KeyboardAvoidingView, and as a child component, a TextInput with multiline={true}

Describe what you expected to happen:
I expected that this just works well

KeyboardAvoidingView attributes:
- style={{flex:1}} 
- behavior={Platform.OS === "ios" ? "padding" : null} 
- enabled
- keyboardVerticalOffset={45}

`<TextInput multiline={true} />`

**Comment by Arwantys** [comment]
Same problem since deleting and reinstalling modules.

**Comment by hgezim** [comment]
@Arwantys Are you suggesting this is a regression?

**Comment by hgezim** [comment]
This seems to be because bottom height for `KeyboardAvoidingView` is only calculated in `_onKeyboardChange` when keyboard frame changes not when view size changes:

```
Keyboard.addListener('keyboardWillChangeFrame', this._onKeyboardChange)
```

**Comment by hgezim** [comment]
Duplicate of #16826.
