### ISSUE TITLE
Fonts are unrecognizable

### ISSUE THREAD

**Issue by huntermetts** [facebook/react-native#27784]
I've added a react-native.config.js file, added `module.exports = {
    assets:['./assets/fonts']
}`

ran `react-native link`

restarted everything

And have attempted to use the font and it just says it's unrecognized

React Native version:
react-native-cli: 2.0.1
react-native: 0.61.5

## Steps To Reproduce

1. Create react-native.config.js folder with "module.exports = {
    assets:['./assets/fonts']
}"
2. Create assets folder with fonts folder and the a font inside of it
3. run react-native link
4. Use the font in a styles.js file
5. run react-native run-ios

Describe what you expected to happen:
"unrecognized font family 'ProximaNovaAlt-Bold'

<img width="266" alt="Screen Shot 2020-01-15 at 2 12 07 PM" src="https://user-images.githubusercontent.com/44845206/72469255-a9bb2580-37a4-11ea-8654-555f4ab14b0e.png">
<img width="609" alt="Screen Shot 2020-01-15 at 2 12 21 PM" src="https://user-images.githubusercontent.com/44845206/72469256-a9bb2580-37a4-11ea-8893-6869a538a71c.png">
<img width="328" alt="Screen Shot 2020-01-15 at 2 22 00 PM" src="https://user-images.githubusercontent.com/44845206/72469257-a9bb2580-37a4-11ea-92d7-6292dace182b.png">
<img width="253" alt="Screen Shot 2020-01-15 at 2 23 30 PM" src="https://user-images.githubusercontent.com/44845206/72469258-a9bb2580-37a4-11ea-87b1-17e48eb72e9b.png">
<img width="449" alt="Screen Shot 2020-01-15 at 2 38 34 PM" src="https://user-images.githubusercontent.com/44845206/72469282-b9d30500-37a4-11ea-8181-2fed074ad960.png">

**Comment by mtt87** [comment]
You also need to check if they are listed in your `info.plist` i.e.
```
	<key>UIAppFonts</key>
	<array>
		<string>FedraSansPro-Book.ttf</string>
		<string>FedraSansPro-Medium.ttf</string>
		<string>AntDesign.ttf</string>
		<string>Entypo.ttf</string>
		<string>EvilIcons.ttf</string>
		<string>Feather.ttf</string>
		<string>FontAwesome.ttf</string>
		<string>Foundation.ttf</string>
		<string>Ionicons.ttf</string>
		<string>MaterialIcons.ttf</string>
		<string>MaterialCommunityIcons.ttf</string>
		<string>SimpleLineIcons.ttf</string>
		<string>Octicons.ttf</string>
		<string>Zocial.ttf</string>
		<string>FontAwesome5_Brands.ttf</string>
		<string>FontAwesome5_Regular.ttf</string>
		<string>FontAwesome5_Solid.ttf</string>
		<string>Fontisto.ttf</string>
	</array>
```

**Comment by hramos** [comment]
@huntermetts did @mtt87's suggestion help?

**Comment by dulmandakh** [comment]
Also make sure to use font family name, not font file name.
