### ISSUE TITLE
WARNING: The specified Android SDK Build Tools version (23.0.1) is ignored, as it is below the minimum supported version (28.0.3) for Android Gradle Plugin 3.4.2. Android SDK Build Tools 28.0.3 will be used.

### ISSUE THREAD

**Issue by haratmalli** [facebook/react-native#27785]
But i am using 

> buildToolsVersion = "28.0.3"

so why its saying this warning?

**Comment by milesros** [comment]
im having a similar issue `The specified Android SDK Build Tools version (28.0.0) is ignored, as it is below the minimum supported version (28.0.3) for Android Gradle Plugin 3.4.2.`

My buildtoolsversion is the following:

> buildToolsVersion = "28.0.3"

**Comment by dulmandakh** [comment]
it's caused by a native module to use outdated build tools version

**Comment by haratmalli** [comment]
what can we do or just ignoring it

**Comment by safaiyeh** [comment]
@haratmalli find the module and maybe make a PR to it!
