### ISSUE TITLE
Wiki: Broken link for finding unresolved issues

### ISSUE THREAD

**Issue by brodin** [facebook/react-native#27794]
On this page https://github.com/facebook/react-native/wiki/Issues#triage one is instructed to: 

> First, filter out any issues that already contain one of the resolution labels.

And it links to this issue filter: https://github.com/facebook/react-native/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3A%22Bug+Report%22+-label%3A%22Resolution%3A+Needs+More+Information%22+-label%3A%22Resolution%3A+Needs+Repro%22+-label%3A%22Resolution%3A+Old+Version%22+-label%3A%22Resolution%3A+No+Template%22+-label%3A%22Resolution%3A+Missing+Environment+Info%22+-label%3A%22Resolution%3A+For+Stack+Overflow%22

Which leads to an empty feed, and this is not because there is no issue without resolution, there is simply no issues tagged `"Bug Report"`. If you do the same search with label `"Bug"` you get 614 open issues without resolution. Is this correct or something that could be updated? 🙏

**Comment by hramos** [comment]
Thanks! We did rename the label to just Bug recently. I'll fix the link.

**Comment by hramos** [comment]
Fixed: https://github.com/facebook/react-native/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3A%22Bug%22+-label%3A%22Resolution%3A+Needs+More+Information%22+-label%3A%22Resolution%3A+Needs+Repro%22+-label%3A%22Resolution%3A+Old+Version%22+-label%3A%22Resolution%3A+No+Template%22+-label%3A%22Resolution%3A+Missing+Environment+Info%22+-label%3A%22Resolution%3A+For+Stack+Overflow%22
