### ISSUE TITLE
React Native Metro Server Not Start

### ISSUE THREAD

**Issue by adispartadev** [facebook/react-native#27792]
I just install and run react native and try to run it but it not work in emulator 

React Native version:
"react": "16.9.0",  
"react-native": "0.61.5"

## Installation step

1. I created new project using `npx react-native init newProject`
2. Run android emulator using `./emulator @Pixel_2_API_28`
3. Run react native app using `npx react-native run-android`

Build process was successfully, but my terminal not watch the command. This is my terminal looks like: 
![image](https://user-images.githubusercontent.com/16744864/72598562-fc364680-394a-11ea-9a83-5001c0639a5a.png)

And this is error message from my android emulator.

![image](https://user-images.githubusercontent.com/16744864/72597929-c04eb180-3949-11ea-861f-2e3d7a550c4a.png)

How to solved this issue? Thanks in advanced

**Comment by jamsch** [comment]
I believe that on some operating system configurations (Ubuntu in my case) the packager doesn't run in a separate process when you execute `react-native run-android`. You can however manually run it by typing `react-native start` after the app has been compiled and installed the attached device.

**Comment by hramos** [comment]
Running `react-native start` should solve this.
