### ISSUE TITLE
Linking.canOpenURL now throws error  if  link cannot be open, this is stupid

### ISSUE THREAD

**Issue by big-toni** [facebook/react-native#27798]
It does not make sense to throw an error, it should just return False bool.

## React Native version:
  System:
    OS: macOS 10.15.2
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Memory: 31.38 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.3.1 - ~/.nvm/versions/node/v12.3.1/bin/node
    Yarn: 1.17.3 - ~/.nvm/versions/node/v12.3.1/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.3.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  npmPackages:
    react: ^16.9.0 => 16.11.0 
    react-native: ^0.61.3 => 0.61.3 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-log-ios: 1.0.1

## Steps To Reproduce

const canOpenLink = Linking.canOpenURL('someshithere://blabla.blabla.blabla');

## Describe what you expected to happen:

Should return **FALSE** bool

with this change, canOpenUrl stops to be useful anymore, and you need to write code like this: 

```
try {
      await Linking.openURL(googleMapsUrl);
    } catch {
      try {
        await Linking.openURL(appleMapsUrl);
      } catch {
        try {
          await Linking.openURL(webMapsUrl);
        } catch {
          captureException(new Error(`Actual error here`));
        }
      }
    }
```

**Comment by vonovak** [comment]
The docs include an explanation of why the call may reject: https://facebook.github.io/react-native/docs/linking#canopenurl :

> The Promise will reject on Android if it was impossible to check if the URL can be opened, and on iOS if you didn't add the specific scheme in the LSApplicationQueriesSchemes key inside Info.plist (see bellow).

The docs do not say clearly whether it resolves to a boolean, maybe that can be improved. 

> It does not make sense to throw an error, it should just return False bool.

Some people may care about the fact that there was an error, and returning false would not provide this information. If all you care about is true / false, you can create your own wrapper around the function and return a boolean.

**Comment by safaiyeh** [comment]
Agreed that `openURL` should have the error thrown. The precheck `canOpenURL` seems like there can be improvement around how it is handled
