### ISSUE TITLE
[iOS Xcode] React-Native build failed in Xcode with l library not found for -lBVLinearGradient

### ISSUE THREAD

**Issue by JungDonggun** [facebook/react-native#27806]
Using react-native run-ios --configuration Release --device 'utaha iPhone Xs Max' is successfully, when I use Xcode to build and run the project, produce this error:

d: warning: directory not found for option '-L/Users/utaha/Library/Developer/Xcode/DerivedData/univel-adctxukeyblcztayrsjystpejsrz/Build/Products/Release-iphoneos/BVLinearGradient'
ld: warning: directory not found for option '-L/Users/utaha/Library/Developer/Xcode/DerivedData/univel-adctxukeyblcztayrsjystpejsrz/Build/Products/Release-iphoneos/BoringSSL-GRPC'
ld: warning: directory not found for option '-L/Users/utaha/Library/Developer/Xcode/DerivedData/univel-adctxukeyblcztayrsjystpejsrz/Build/Products/Release-iphoneos/DoubleConversion'
ld: warning: directory not found for option '-L/Users/utaha/Library/Developer/Xcode/DerivedData/univel-adctxukeyblcztayrsjystpejsrz/Build/Products/Release-iphoneos/FBReactNativeSpec'
ld: warning: directory not found for option '-L/Users/utaha/Library/Developer/Xcode/DerivedData/univel-adctxukeyblcztayrsjystpejsrz/Build/Products/Release-iphoneos/FirebaseAuth'
ld: warning: directory not found for option '-L/Users/utaha/Library/Developer/Xcode/DerivedData/univel-adctxukeyblcztayrsjystpejsrz/Build/Products/Release-iphoneos/FirebaseCore'
ld: warning: directory not found for option '-L/Users/utaha/Library/Developer/Xcode/DerivedData/univel-adctxukeyblcztayrsjystpejsrz/Build/Products/Release-iphoneos/FirebaseCoreDiagnostics'
ld: warning: directory not found for option '-L/Users/utaha/Library/Developer/Xcode/DerivedData/univel-adctxukeyblcztayrsjystpejsrz/Build/Products/Release-iphoneos/FirebaseDynamicLinks'
ld: warning: directory not found for option '-L/Users/utaha/Library/Developer/Xcode/DerivedData/univel-adctxukeyblcztayrsjystpejsrz/Build/Products/Release-iphoneos/FirebaseFirestore'
ld: warning: directory not found for option '-L/Users/utaha/Library/Developer/Xcode/DerivedData/univel-adctxukeyblcztayrsjystpejsrz/Build/Products/Release-iphoneos/FirebaseInstanceID'
ld: warning: directory not found for option '-L/Users/utaha/Library/Developer/Xcode/DerivedData/univel-adctxukeyblcztayrsjystpejsrz/Build/Products/Release-iphoneos/FirebaseMessaging'
ld: warning: directory not found for option '-L/Users/utaha/Library/Developer/Xcode/DerivedData/univel-adctxukeyblcztayrsjystpejsrz/Build/Products/Release-iphoneos/Folly'
ld: warning: directory not found for option '-L/Users/utaha/Library/Developer/Xcode/DerivedData/univel-adctxukeyblcztayrsjystpejsrz/Build/Products/Release-iphoneos/GTMSessionFetcher'
ld: warning: directory not found for option '-L/Users/utaha/Library/Developer/Xcode/DerivedData/univel-adctxukeyblcztayrsjystpejsrz/Build/Products/Release-iphoneos/GoogleDataTransport'
ld: warning: directory not found for option '-L/Users/utaha/Library/Developer/Xcode/DerivedData/univel-adctxukeyblcztayrsjystpejsrz/Build/Products/Release-iphoneos/GoogleDataTransportCCTSupport'
ld: warning: directory not found for option '-L/Users/utaha/Library/Developer/Xcode/DerivedData/univel-adctxukeyblcztayrsjystpejsrz/Build/Products/Release-iphoneos/GoogleUtilities'
ld: warning: directory not found for option '-L/Users/utaha/Library/Developer/Xcode/DerivedData/univel-adctxukeyblcztayrsjystpejsrz/Build/Products/Release-iphoneos/Permission-Camera'
ld: warning: directory not found for option '-L/Users/utaha/Library/Developer/Xcode/DerivedData/univel-adctxukeyblcztayrsjystpejsrz/Build/Products/Release-iphoneos/Permission-LocationAlways'
ld: warning: directory not found for option '-L/Users/utaha/Library/Developer/Xcode/DerivedData/univel-adctxukeyblcztayrsjystpejsrz/Build/Products/Release-iphoneos/Permission-LocationWhenInUse'
ld: warning: directory not found for option '-L/Users/utaha/Library/Developer/Xcode/DerivedData/univel-adctxukeyblcztayrsjystpejsrz/Build/Products/Release-iphoneos/Permission-Microphone'
ld: warning: directory not found for option '-L/Users/utaha/Library/Developer/Xcode/DerivedData/univel-adctxukeyblcztayrsjystpejsrz/Build/Products/Release-iphoneos/Permission-Motion'
ld: warning: directory not found for option '-L/Users/utaha/Library/Developer/Xcode/DerivedData/univel-adctxukeyblcztayrsjystpejsrz/Build/Products/Release-iphoneos/Permission-Notifications'
ld: warning: directory not found for option '-L/Users/utaha/Library/Developer/Xcode/DerivedData/univel-adctxukeyblcztayrsjystpejsrz/Build/Products/Release-iphoneos/Permission-PhotoLibrary'
ld: warning: directory not found for option '-L/Users/utaha/Library/Developer/Xcode/DerivedData/univel-adctxukeyblcztayrsjystpejsrz/Build/Products/Release-iphoneos/Permission-StoreKit'
ld: warning: directory not found for option '-L/Users/utaha/Library/Developer/Xcode/DerivedData/univel-adctxukeyblcztayrsjystpejsrz/Build/Products/Release-iphoneos/Protobuf'
ld: warning: directory not found for option '-L/Users/utaha/Library/Developer/Xcode/DerivedData/univel-adctxukeyblcztayrsjystpejsrz/Build/Products/Release-iphoneos/RCTTypeSafety'
ld: warning: directory not found for option '-L/Users/utaha/Library/Developer/Xcode/DerivedData/univel-adctxukeyblcztayrsjystpejsrz/Build/Products/Release-iphoneos/RNCAsyncStorage'
ld: warning: directory not found for option '-L/Users/utaha/Library/Developer/Xcode/DerivedData/univel-adctxukeyblcztayrsjystpejsrz/Build/Products/Release-iphoneos/RNFBApp'
ld: warning: directory not found for option '-L/Users/utaha/Library/Developer/Xcode/DerivedData/univel-adctxukeyblcztayrsjystpejsrz/Build/Products/Release-iphoneos/RNFBAuth'
ld: warning: directory not found for option '-L/Users/utaha/Library/Developer/Xcode/DerivedData/univel-adctxukeyblcztayrsjystpejsrz/Build/Products/Release-iphoneos/RNFBDynamicLinks'
ld: warning: directory not found for option '-L/Users/utaha/Library/Developer/Xcode/DerivedData/univel-adctxukeyblcztayrsjystpejsrz/Build/Products/Release-iphoneos/RNFBFirestore'
ld: warning: directory not found for option '-L/Users/utaha/Library/Developer/Xcode/DerivedData/univel-adctxukeyblcztayrsjystpejsrz/Build/Products/Release-iphoneos/RNFBMessaging'
ld: warning: directory not found for option '-L/Users/utaha/Library/Developer/Xcode/DerivedData/univel-adctxukeyblcztayrsjystpejsrz/Build/Products/Release-iphoneos/RNFastImage'
ld: warning: directory not found for option '-L/Users/utaha/Library/Developer/Xcode/DerivedData/univel-adctxukeyblcztayrsjystpejsrz/Build/Products/Release-iphoneos/RNGestureHandler'
ld: warning: directory not found for option '-L/Users/utaha/Library/Developer/Xcode/DerivedData/univel-adctxukeyblcztayrsjystpejsrz/Build/Products/Release-iphoneos/RNPermissions'
ld: warning: directory not found for option '-L/Users/utaha/Library/Developer/Xcode/DerivedData/univel-adctxukeyblcztayrsjystpejsrz/Build/Products/Release-iphoneos/RNReanimated'
ld: warning: directory not found for option '-L/Users/utaha/Library/Developer/Xcode/DerivedData/univel-adctxukeyblcztayrsjystpejsrz/Build/Products/Release-iphoneos/RNSVG'
ld: warning: directory not found for option '-L/Users/utaha/Library/Developer/Xcode/DerivedData/univel-adctxukeyblcztayrsjystpejsrz/Build/Products/Release-iphoneos/React-Core'
ld: warning: directory not found for option '-L/Users/utaha/Library/Developer/Xcode/DerivedData/univel-adctxukeyblcztayrsjystpejsrz/Build/Products/Release-iphoneos/React-CoreModules'
ld: warning: directory not found for option '-L/Users/utaha/Library/Developer/Xcode/DerivedData/univel-adctxukeyblcztayrsjystpejsrz/Build/Products/Release-iphoneos/React-RCTActionSheet'
ld: warning: directory not found for option '-L/Users/utaha/Library/Developer/Xcode/DerivedData/univel-adctxukeyblcztayrsjystpejsrz/Build/Products/Release-iphoneos/React-RCTAnimation'
ld: warning: directory not found for option '-L/Users/utaha/Library/Developer/Xcode/DerivedData/univel-adctxukeyblcztayrsjystpejsrz/Build/Products/Release-iphoneos/React-RCTBlob'
ld: warning: directory not found for option '-L/Users/utaha/Library/Developer/Xcode/DerivedData/univel-adctxukeyblcztayrsjystpejsrz/Build/Products/Release-iphoneos/React-RCTImage'
ld: warning: directory not found for option '-L/Users/utaha/Library/Developer/Xcode/DerivedData/univel-adctxukeyblcztayrsjystpejsrz/Build/Products/Release-iphoneos/React-RCTLinking'
ld: warning: directory not found for option '-L/Users/utaha/Library/Developer/Xcode/DerivedData/univel-adctxukeyblcztayrsjystpejsrz/Build/Products/Release-iphoneos/React-RCTNetwork'
ld: warning: directory not found for option '-L/Users/utaha/Library/Developer/Xcode/DerivedData/univel-adctxukeyblcztayrsjystpejsrz/Build/Products/Release-iphoneos/React-RCTSettings'
ld: warning: directory not found for option '-L/Users/utaha/Library/Developer/Xcode/DerivedData/univel-adctxukeyblcztayrsjystpejsrz/Build/Products/Release-iphoneos/React-RCTText'
ld: warning: directory not found for option '-L/Users/utaha/Library/Developer/Xcode/DerivedData/univel-adctxukeyblcztayrsjystpejsrz/Build/Products/Release-iphoneos/React-RCTVibration'
ld: warning: directory not found for option '-L/Users/utaha/Library/Developer/Xcode/DerivedData/univel-adctxukeyblcztayrsjystpejsrz/Build/Products/Release-iphoneos/React-cxxreact'
ld: warning: directory not found for option '-L/Users/utaha/Library/Developer/Xcode/DerivedData/univel-adctxukeyblcztayrsjystpejsrz/Build/Products/Release-iphoneos/React-jsi'
ld: warning: directory not found for option '-L/Users/utaha/Library/Developer/Xcode/DerivedData/univel-adctxukeyblcztayrsjystpejsrz/Build/Products/Release-iphoneos/React-jsiexecutor'
ld: warning: directory not found for option '-L/Users/utaha/Library/Developer/Xcode/DerivedData/univel-adctxukeyblcztayrsjystpejsrz/Build/Products/Release-iphoneos/React-jsinspector'
ld: warning: directory not found for option '-L/Users/utaha/Library/Developer/Xcode/DerivedData/univel-adctxukeyblcztayrsjystpejsrz/Build/Products/Release-iphoneos/ReactCommon'
ld: warning: directory not found for option '-L/Users/utaha/Library/Developer/Xcode/DerivedData/univel-adctxukeyblcztayrsjystpejsrz/Build/Products/Release-iphoneos/SDWebImage'
ld: warning: directory not found for option '-L/Users/utaha/Library/Developer/Xcode/DerivedData/univel-adctxukeyblcztayrsjystpejsrz/Build/Products/Release-iphoneos/SDWebImageWebPCoder'
ld: warning: directory not found for option '-L/Users/utaha/Library/Developer/Xcode/DerivedData/univel-adctxukeyblcztayrsjystpejsrz/Build/Products/Release-iphoneos/Yoga'
ld: warning: directory not found for option '-L/Users/utaha/Library/Developer/Xcode/DerivedData/univel-adctxukeyblcztayrsjystpejsrz/Build/Products/Release-iphoneos/abseil'
ld: warning: directory not found for option '-L/Users/utaha/Library/Developer/Xcode/DerivedData/univel-adctxukeyblcztayrsjystpejsrz/Build/Products/Release-iphoneos/gRPC-C++'
ld: warning: directory not found for option '-L/Users/utaha/Library/Developer/Xcode/DerivedData/univel-adctxukeyblcztayrsjystpejsrz/Build/Products/Release-iphoneos/gRPC-Core'
ld: warning: directory not found for option '-L/Users/utaha/Library/Developer/Xcode/DerivedData/univel-adctxukeyblcztayrsjystpejsrz/Build/Products/Release-iphoneos/glog'
ld: warning: directory not found for option '-L/Users/utaha/Library/Developer/Xcode/DerivedData/univel-adctxukeyblcztayrsjystpejsrz/Build/Products/Release-iphoneos/leveldb-library'
ld: warning: directory not found for option '-L/Users/utaha/Library/Developer/Xcode/DerivedData/univel-adctxukeyblcztayrsjystpejsrz/Build/Products/Release-iphoneos/libwebp'
ld: warning: directory not found for option '-L/Users/utaha/Library/Developer/Xcode/DerivedData/univel-adctxukeyblcztayrsjystpejsrz/Build/Products/Release-iphoneos/nanopb'
ld: warning: directory not found for option '-L/Users/utaha/Library/Developer/Xcode/DerivedData/univel-adctxukeyblcztayrsjystpejsrz/Build/Products/Release-iphoneos/react-native-date-picker'
ld: warning: directory not found for option '-L/Users/utaha/Library/Developer/Xcode/DerivedData/univel-adctxukeyblcztayrsjystpejsrz/Build/Products/Release-iphoneos/react-native-geolocation'
ld: warning: directory not found for option '-L/Users/utaha/Library/Developer/Xcode/DerivedData/univel-adctxukeyblcztayrsjystpejsrz/Build/Products/Release-iphoneos/react-native-image-picker'
ld: warning: directory not found for option '-L/Users/utaha/Library/Developer/Xcode/DerivedData/univel-adctxukeyblcztayrsjystpejsrz/Build/Products/Release-iphoneos/react-native-splash-screen'
ld: library not found for -lBVLinearGradient
clang: error: linker command failed with exit code 1 (use -v to see invocation)

My Environment:

React Native version:  0.61.4
Xcode version: 11
Podfile
  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

  permissions_path = '../node_modules/react-native-permissions/ios'

  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways.podspec"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse.podspec"
  pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone.podspec"
  pod 'Permission-Motion', :path => "#{permissions_path}/Motion.podspec"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications.podspec"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary.podspec"
  pod 'Permission-StoreKit', :path => "#{permissions_path}/StoreKit.podspec"

  pod 'react-native-geolocation', path: '../node_modules/@react-native-community/geolocation'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
    # add the Firebase pod for Google Analytics
    pod 'Firebase/Analytics'
    pod 'Firebase/Auth'
    # Add the pod for Firebase Cloud Messaging
    pod 'Firebase/Messaging'
    # add pods for any other desired Firebase products
    # https://firebase.google.com/docs/ios/setup#available-pods

**Comment by abinhho** [comment]
See here: https://stackoverflow.com/a/66202089/9585130
