### ISSUE TITLE
[CI] Snapshot Test reference images differ on Circle CI

### ISSUE THREAD

**Issue by hramos** [facebook/react-native#27801]
We're tracking a known issue where the snapshot test reference images differ slightly when generated on Circle CI as compared to a regular macOS install when Xcode 11 is used. We suspect this might be related to the use of the GPU by the simulator, a feature that is new to Xcode 11 (see similar issue at https://github.com/uber/ios-snapshot-test-case/issues/109). This is based off the assumption that the way Circle CI handles macOS jobs might not provide access to a GPU.

Snapshot tests will be disabled on Circle CI until this issue is resolved.

## Reference

The actual differences between the images are imperceptible to the naked eye, and may be attributed to slight differences in how the views are rendered on and off GPU.

This is the diff for `testSwitchExample`:

![Screen Shot 2020-01-17 at 10 33 01 AM](https://user-images.githubusercontent.com/165856/72645444-88834200-3928-11ea-85bd-8b5106376662.png)

These are the two images, side by side:
![Screen Shot 2020-01-17 at 12 56 56 PM](https://user-images.githubusercontent.com/165856/72645591-db5cf980-3928-11ea-8bad-ce59ef130919.png)

**Comment by ChiWhiteSox56** [comment]
I just updated to Catalina / Xcode 11.4.1 about a week ago, and my tests started breaking. The issue that you describe here seems to be what I'm encountering. Do you have any updates on this?

Thanks in advance.

**Comment by fabriziobertoglio1987** [comment]
I'm also having issues running the test suite and I am considering using [the docker image](https://github.com/facebook/react-native/wiki/Building-from-source#publish-your-own-version-of-react-native) to run the test suite

**Comment by fabriziobertoglio1987** [comment]
I am also experiencing issues with test and I may resort running [CircleCI](https://github.com/facebook/react-native/wiki/Tests#continuous-testing) locally and set up with [docker](https://github.com/facebook/react-native/wiki/Building-from-source#publish-your-own-version-of-react-native)

**Comment by fabriziobertoglio1987** [comment]
@ChiWhiteSox56 I'm on Ubuntu 19.10 and I am following the [Docker Instructions](https://github.com/facebook/react-native/blob/master/.circleci/DockerTests.md) writter from Hector Ramos. :smiley: Thanks a lot for the amazing instructions. Could not make it without them.
