### ISSUE TITLE
Question: Regular lookbehind is supported?

### ISSUE THREAD

**Issue by DavidNineRoc** [facebook/react-native#27807]
yes
`new RegExp(/\n(?!\s{4})/g)`

no
`new RegExp(/(?<!\s|\d)(\d+)/g)`

![image](https://user-images.githubusercontent.com/28035971/72676867-e5b9f780-3ad0-11ea-817f-2957af453146.png)

**Comment by chriswayg** [comment]
I would consider it a bug, if it is not supported. It is supported on node.js, so it's strange that it is apparently not supported in React Native.
