### ISSUE TITLE
zIndex diff behaviour in Android/iOS

### ISSUE THREAD

**Issue by 1nfinite** [facebook/react-native#27802]
React Native version: 0.61.5

## Steps To Reproduce
Apply position absolute outside of TouchableOpacity inside as following code.

## Outcome
1) In android the TouchableOpacity is pressable.
2) In iOS the TouchableOpacity is not pressable.

I need to set zIndex: 1 in View style for it to work on iOS.

## Expected Behaviour
Code should execute similar behaviour in both platform. De facto standard is that a position absolute view should have higher zIndex than relative view.

```
 <View
    style={{
        flexDirection: 'row',
        position: 'absolute',
        height: '100%',
    }}>
    <TouchableOpacity
        onPress={this._onClick}
        style={{width: '100%'}}></TouchableOpacity>
</View>

```

**Comment by VladyslavKochetkov** [comment]
This is probably due to Android handling pointer events differently. See https://facebook.github.io/react-native/docs/view#pointerevents
