### ISSUE TITLE
Re-render component when multiple styles

### ISSUE THREAD

**Issue by Levin228** [facebook/react-native#27815]
React Native version:: 0.61.5

Hello,
I'm faced with a problem: when array of styles passed through props to some component, it re-renders but styles do not change.
I can use shouldComponentUpdate in React.Component, but in my case it's better to use PureComponent.
What can be done about this?

**Comment by valoricDe** [comment]
@JoshuaGross I believe this is a bug and thus should be reopened.
Here are the react-native infos:

System:
    OS: macOS 10.15.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 6.33 GB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.0 - /var/folders/3c/kqbx68hn61n3_33m5pv4n9gh0000gp/T/yarn--1594790304950-0.5599283170296678/node
    Yarn: 1.22.4 - /var/folders/3c/kqbx68hn61n3_33m5pv4n9gh0000gp/T/yarn--1594790304950-0.5599283170296678/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.18.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK: Not Found
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.2 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.8.3 => 16.8.3 
    react-native: ^0.63.0 => 0.63.0 
  npmGlobalPackages:
    *react-native*: Not Found

My page is server side rendered and thus has mobile styles (flexDirection: column).
When it then gets initialised in the browser the style object changes to flexDirection row but the classes in the browser inspector still are containing flexDirection: column

**Comment by OoDeLally** [comment]
I have the same problem.
```tsx
<ButtonComponent style={[styles.button, dynamicbuttonStyle]}>
  Stuff
</ButtonComponent>
```

doesnt re-render when `dynamicbuttonStyle` changes.

My workaround:
```tsx
<ButtonComponent key={JSON.stringify(buttonStyle)} style={[styles.answerButton, buttonStyle]}>
  Stuff
</ButtonComponent>
```
