### ISSUE TITLE
ScrollView not working on first scroll : ScrollView doesn't take rejection well - scrolls anyway

### ISSUE THREAD

**Issue by Mokto** [facebook/react-native#2781]
Hi, 

It's the first time I'm raising an issue on Github, so feel free to let me know if my way of  doing is wrong. 

When I scroll for the first time on my ListView, a javascript error appears : "ScrollView doesn't take rejection well - scrolls anyway." And then i can scroll as usual. 

(Might be duplicate of #41)

Here is my code :
```
<ScrollView>
        <ListView
          dataSource={this.props.dataSource}
          renderRow={this.renderAlbum}
          contentContainerStyle={styles.listView}
        />
</ScrollView>
```
```
  listView: {
    flexDirection: 'row',
    flexWrap: 'wrap'
  },
```

Albums are views wide as 50% of the device. They contain an image + text. 

Thanks very much, 
Theo Mathieu.

**Comment by ide** [comment]
Hi @Mokto -- currently nested ScrollViews (that includes ListViews, which are a wrapper around ScrollViews) don't work very well in React Native. Could you address your use case another way by using only a ListView, and putting content above/below it with the `renderHeader` and `renderFooter` props?

**Comment by Mokto** [comment]
Ok,

I didn't know that ListViews are wrappers around ScrollViews.
Removing parent ScrollView works fine.

Thanks a lot for your help & reactivity !
