### ISSUE TITLE
NullPointerException at UIViewOperationQueue$1.run 

### ISSUE THREAD

**Issue by evelant** [facebook/react-native#27819]
Random crashes in UIViewOperationQueue$1.run across multiple device types and Android versions in production build. One similar issue here was closed without resolution https://github.com/facebook/react-native/issues/22867

Not really sure how to debug this further as it's random, only on production, happening across Android versions, and I can't reliably reproduce it.

## Stack
```
java.lang.NullPointerException: 
  at com.facebook.react.uimanager.UIViewOperationQueue$1.run (UIViewOperationQueue.java:779)
  at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches (UIViewOperationQueue.java:888)
  at com.facebook.react.uimanager.UIViewOperationQueue.access$2200 (UIViewOperationQueue.java:42)
  at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded (UIViewOperationQueue.java:948)
  at com.facebook.react.uimanager.GuardedFrameCallback.doFrame (GuardedFrameCallback.java:28)
  at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame (ReactChoreographer.java:174)
  at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame (ChoreographerCompat.java:84)
  at android.view.Choreographer$CallbackRecord.run (Choreographer.java:909)
  at android.view.Choreographer.doCallbacks (Choreographer.java:723)
  at android.view.Choreographer.doFrame (Choreographer.java:655)
  at android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:897)
  at android.os.Handler.handleCallback (Handler.java:789)
  at android.os.Handler.dispatchMessage (Handler.java:98)
  at android.os.Looper.loop (Looper.java:164)
  at android.app.ActivityThread.main (ActivityThread.java:6944)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:327)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1374)
```

## Package.json
```
{
    "name": "myapp",
    "version": "0.0.1",
    "private": true,
    "scripts": {
        "start": "node node_modules/react-native/local-cli/cli.js start",
        "test": "jest",
        "postinstall": "jetify"
    },
    "dependencies": {
        "@bankify/react-native-animate-number": "^0.2.1",
        "@invertase/react-native-apple-authentication": "^0.1.1",
        "@react-native-community/async-storage": "^1.6.3",
        "@react-native-community/google-signin": "^3.0.3",
        "@react-native-community/netinfo": "^4.6.1",
        "babel-plugin-rewrite-require": "^1.14.5",
        "clevertap-react-native": "^0.3.6",
        "date-fns": "^1.30.1",
        "deepdash-es": "^4.2.17",
        "fast-safe-stringify": "^2.0.7",
        "instabug-reactnative": "^9.0.0",
        "lodash": "^4.17.15",
        "metro-react-native-babel-preset": "^0.57.0",
        "mobx": "^5.15.0",
        "mobx-react": "^6.1.4",
        "mobx-state-tree": "^3.15.0",
        "moment": "^2.24.0",
        "react": "16.9.0",
        "react-native": "^0.61.5",
        "react-native-animatable": "^1.3.3",
        "react-native-branch": "^4.2.1",
        "react-native-code-push": "^5.7.0",
        "react-native-confetti": "^0.1.0",
        "react-native-countup": "^0.0.2",
        "react-native-draggable-flatlist": "^1.1.9",
        "react-native-easy-toast": "^1.2.0",
        "react-native-exception-handler": "^2.10.8",
        "react-native-fbsdk": "^1.1.1",
        "react-native-firebase": "^5.6.0",
        "react-native-firebase-test-lab": "^0.0.2",
        "react-native-gesture-handler": "^1.5.1",
        "react-native-os": "^1.2.5",
        "react-native-particles": "^0.0.8",
        "react-native-popover-view": "^2.0.5",
        "react-native-portal": "^1.3.0",
        "react-native-pose": "^0.9.1",
        "react-native-reanimated": "^1.4.0",
        "react-native-restart": "^0.0.13",
        "react-native-screens": "^1.0.0-alpha.13",
        "react-native-shimmer": "^0.5.0",
        "react-native-sortable-listview": "^0.2.9",
        "react-native-sound": "^0.11.0",
        "react-native-svg": "^9.13.3",
        "react-native-v8": ">=0.61.5-patch.0 <0.61.6",
        "react-native-vector-icons": "^6.6.0",
        "react-native-version-number": "^0.3.6",
        "react-navigation": "^4.0.10",
        "react-navigation-drawer": "^2.3.3",
        "react-navigation-stack": "^1.10.3",
        "react-navigation-tabs": "^2.6.0",
        "rn-sprite-sheet": "^1.1.3",
        "smartlook-react-native-wrapper": "=0.21.0",
        "styled-components": "^4.4.1",
        "tinycolor2": "^1.4.1"
    },
    "devDependencies": {
        "@babel/core": "^7.7.4",
        "@babel/plugin-proposal-decorators": "^7.7.4",
        "@babel/runtime": "^7.7.4",
        "@react-native-community/cli": "^3.0.4",
        "@types/jest": "^24.0.23",
        "@types/lodash": "^4.14.149",
        "@types/moment": "^2.13.0",
        "@types/react": "^16.9.13",
        "@types/react-native": "^0.60.23",
        "@types/react-native-fbsdk": "^1.0.0",
        "@types/react-native-google-signin": "^1.0.2",
        "@types/react-native-restart": "^0.0.0",
        "@types/react-native-vector-icons": "^6.4.4",
        "@types/react-navigation": "^3.4.0",
        "@types/react-test-renderer": "^16.9.1",
        "@types/styled-components": "^4.4.0",
        "@types/tinycolor2": "^1.4.2",
        "babel-jest": "^24.9.0",
        "jest": "^24.9.0",
        "prettier": "^1.19.1",
        "react-test-renderer": "16.9.0",
        "typescript": "^3.7.2"
    },
    "jest": {
        "preset": "react-native"
    },
    "rnpm": {
        "assets": [
            "./assets/fonts"
        ]
    },
    "react-native": {
        "os": "react-native-os"
    }
}

```

React Native version:
System:
    OS: macOS 10.15.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 21.48 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.10.0 - ~/.nvm/versions/node/v12.10.0/bin/node
    Yarn: 1.19.2 - ~/.yarn/bin/yarn
    npm: 6.10.3 - ~/.nvm/versions/node/v12.10.0/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    @react-native-community/cli: ^3.0.4 => 3.0.4
    react: 16.9.0 => 16.9.0
    react-native: ^0.61.5 => 0.61.5

## Steps To Reproduce

Unknown. Crash is random on production build on Android. Unable to reproduce reliably.

**Comment by AndrewMorsillo** [comment]
I haven't been able to chase this one down or find really any clues at all. This continues to plague the production release of my app affecting seemingly randomly ~10% of users. Any pointers about where to start looking or how to debug would be appreciated!

**Comment by AndrewMorsillo** [comment]
Continuing to investigate this one and coming up empty. I upgraded all packages in my project to the latest version. I investigated all uses of Coreographer by packages in my project and found only trivial usages. I'm really stuck on this one and it's affecting a large portion of my users. Any insight would be greatly appreciated.

**Comment by AndrewMorsillo** [comment]
This is still an issue. I've worked around it by forking RN and adding a null check around the execute call. That stops it from crashing and my app seems to run OK but it doesn't explain or solve why it was happening in the first place. As someone said on the PR relating to this, the fix in that PR wasn't a fix and the SoftAssertion about a null in mOperations doesn't do anything to help.

**Comment by AndrewMorsillo** [comment]
This is still an issue.

**Comment by AndrewMorsillo** [comment]
This is still an issue requiring discussion! My users continue to report random app crashes due to this bug.

**Comment by safaiyeh** [comment]
Hi @AndrewMorsillo, I'm sorry you're having issues. It is hard to pinpoint the issue without something that could cause it.

Is there a user flow, a component, where this happens? Some hints to get closer

**Comment by AndrewMorsillo** [comment]
Unfortunately I haven't been able to figure out when or why this happens. It seems to be random, usually during a user interaction (tap).

There's a related closed PR with a lot more information here: https://github.com/facebook/react-native/pull/11428
Also an old issue unfortunately without much info: https://github.com/facebook/react-native/issues/22867

I believe this is an internal bug with react-native Android but it's very difficult to figure out exactly what triggers it. I've tried switching to Hermes but the issue persists.

**Comment by AndrewMorsillo** [comment]
@safaiyeh Any thoughts or possible assistance on this would be greatly appreciated. This is absolutely plaguing us, 15-40% of production sessions are crashing with this error. We're totally at our wits end about reproducing or fixing this. It's so bad that we're considering leaving react-native and rewriting the whole app in Flutter. We can't proceed with our beta and get accurate retention metrics due to this. It's a total showstopper for us.

**Comment by safaiyeh** [comment]
Looks like you have a fix for the null pointer? Mind putting it up for someone to check out?

**Comment by AndrewMorsillo** [comment]
I can't share the app code unfortunately. 

The crash is in native react-native android java code, not in our app code. The issue as discussed in https://github.com/facebook/react-native/pull/11428 indicates that this is likely a thread safety bug inside of RN. 

I haven't been able to reliably trigger the issue or make a reproduction, it seems totally random other than user reports that it seems to happen randomly when tapping a button (Touchable) just about anywhere in the app. I've even rebased our code onto a fresh `react-native init` removed most of the dependencies in my app to rule out unstable 3rd party native code but the issue remains. 

Our app is very animation heavy so it seems likely to me that we're triggering a subtle bug in react-native that most other apps don't manage to trigger.

**Comment by sfuqua** [comment]
I am hitting this same stack in my application and have reached all of your same conclusions @AndrewMorsillo. I very much appreciate the linked PRs and the Instabug issue.

The one commonality I can find between Instabug/Instabug-React-Native#514 and my code is that we're calling `context.getNativeModule(UIManagerModule.class).prependUIBlock` in a native component.

I can't figure out where the NullPointerException is coming from in the UIOperationQueue, but this call to `prependUIBlock` seems like a common culprit in both codebases. How is this resulting in a crash??

**Comment by sfuqua** [comment]
I can confirm that removing the native module component (a blurred view) that is calling `prependUIBlock` has caused this crash to stop showing up in our analytics.

This isn't a fix - we've just stopped hitting the crash by removing some of our UI - but does point the finger at `prependUIBlock` and possibly a thread safety issue in how it's mutating the queue.

**Comment by MAKARD** [comment]
react-native 0.70 the issue still exists. According to Dynatrace logs there are no specific steps to reproduces, as app crashes in different places at different time

**Comment by MarcinGazda** [comment]
Hi, i got null pointer on android implementation RN: 0.71.3

IllegalStateException
Missing pointer 0

com.smartlook.sdk.interactions.gesture.GestureDetector in a at line 53
com.smartlook.sdk.interaction.m in a at line 33
com.smartlook.sdk.interactions.Interactions$a in dispatchTouchEvent at line 2
com.android.internal.policy.DecorView in dispatchTouchEvent at line 728
android.view.View in dispatchPointerEvent at line 14636
android.view.ViewRootImpl$ViewPostImeInputStage in processPointerEvent at line 6579
android.view.ViewRootImpl$ViewPostImeInputStage in onProcess at line 6357
android.view.ViewRootImpl$InputStage in deliver at line 5793
android.view.ViewRootImpl$InputStage in onDeliverToNext at line 5846
android.view.ViewRootImpl$InputStage in forward at line 5812
android.view.ViewRootImpl$AsyncInputStage in forward at line 5968
android.view.ViewRootImpl$InputStage in apply at line 5820
android.view.ViewRootImpl$AsyncInputStage in apply at line 6025
android.view.ViewRootImpl$InputStage in deliver at line 5793
android.view.ViewRootImpl$InputStage in onDeliverToNext at line 5846
android.view.ViewRootImpl$InputStage in forward at line 5812
android.view.ViewRootImpl$InputStage in apply at line 5820
android.view.ViewRootImpl$InputStage in deliver at line 5793
android.view.ViewRootImpl in deliverInputEvent at line 9029
android.view.ViewRootImpl in doProcessInputEvents at line 8886
android.view.ViewRootImpl in enqueueInputEvent at line 8839
android.view.ViewRootImpl$WindowInputEventReceiver in onInputEvent at line 9166
android.view.InputEventReceiver in dispatchInputEvent at line 194
android.view.InputEventReceiver in nativeConsumeBatchedInputEvents
android.view.InputEventReceiver in consumeBatchedInputEvents at line 183
android.view.ViewRootImpl in doConsumeBatchedInput at line 9106
android.view.ViewRootImpl$ConsumeBatchedInputRunnable in run at line 9193
android.view.Choreographer$CallbackRecord in run at line 999
android.view.Choreographer in doCallbacks at line 797
android.view.Choreographer in doFrame at line 725
android.view.Choreographer$FrameDisplayEventReceiver in run at line 984
android.os.Handler in handleCallback at line 883
android.os.Handler in dispatchMessage at line 100
android.os.Looper in loop at line 237
android.app.ActivityThread in main at line 8167
java.lang.reflect.Method in invoke
com.android.internal.os.RuntimeInit$MethodAndArgsCaller in run at line 496
com.android.internal.os.ZygoteInit in main at line 1100

**Comment by MAKARD** [comment]
https://github.com/facebook/react-native/pull/38581

**Comment by devwasabi2** [comment]
@evelant @MAKARD @sfuqua Has anyone been able to reliably reproduce this on an isolated react native app environment? I'm working on a similar issue and I haven't been able to pin down exactly where we are adding a null value to the queue.
