### ISSUE TITLE
VirtualizedList => measureLayoutRelativeToContainingList threw an error TypeError: this.context.virtualizedList.getOutermostParentListRef(...).getScrollRef(...).getNativeScrollRef is not a function

### ISSUE THREAD

**Issue by sivakumar-cf** [facebook/react-native#27813]
React native Flatlist throws warning message
` measureLayoutRelativeToContainingList threw an error TypeError: this.context.virtualizedList.getOutermostParentListRef(...).getScrollRef(...).getNativeScrollRef is not a function`
React Native version:
System:
   OS: macOS 10.15.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 49.25 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 25, 27, 28, 29
      Build Tools: 28.0.0, 28.0.3, 29.0.2
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.2/11B52 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: ^0.61.5 => 0.61.5
  npmGlobalPackages:
    react-native-cli: 2.0.1
## Steps To Reproduce

1. render Flatlist in any React.component

Snack, code example, screenshot, or link to a repository:

<img width="1266" alt="Screenshot 2020-01-20 at 10 44 39 AM" src="https://user-images.githubusercontent.com/22584937/72700608-5107d600-3b72-11ea-8b9e-f0268503ea05.png">

**Comment by hramos** [comment]
Can you share the code that reproduces this?

**Comment by sivakumar-cf** [comment]
```js
<Flatlist
  ref={scrollRef => (this.scrollRef = scrollRef)}
  data={this.getDataSource()}
  contentContainerStyle={[
    !_.isEmpty(this.getPageActions())
      ? { paddingBottom: this.getScaledHeight(80) }
      : {},
    this.getContentContainerStyle()
  ]}
  onScroll={this._onScroll}
  showsVerticalScrollIndicator={false}
  removeClippedSubviews={false}
  ListHeaderComponent={this._renderListHeader}
  ListFooterComponent={this._renderListFooter}
  ItemSeparatorComponent={this._renderDivider}
  keyExtractor={this._keyExtractor}
  onEndReachedThreshold={0.5}
  onEndReached={() => {
    if (this.paginationEnabled()) this.onEndReached();
  }}
  {...this.getlistProps()}
  renderItem={this._renderItem}
/>;
```

**Comment by sivakumar-cf** [comment]
Closing this, as the issue happening in `react-navigation` exported FlatList component.
