### ISSUE TITLE
Clarification: Is this package is supported as in app 

### ISSUE THREAD

**Issue by nihp** [facebook/react-native#27814]
I need to show the dark and light mode inside my app.(i.e) need to set the mode in my settings of my Hello app. 

Is it work in this case. 

Or need to change the settings of the device

Note: Need to set for both android and iOS

**Comment by VladyslavKochetkov** [comment]
You could probably make use of this library to detect if the dark theme is on system-wide (You cannot change system settings from within your app). https://www.npmjs.com/package/react-native-dark-mode

You could also probably write your own setting inside the app that would allow users to override system properties.

Then you could probably do something like

``` js
function Components(props) {
  const isDarkMode = useDarkMode() || useSelector(state => state.theme.dark); // assuming you use redux
  // now you know if dark mode is enabled
  // ...
}
```

**Comment by nihp** [comment]
react-native-dark-mode will works in iOS 13+
