### ISSUE TITLE
Object.Prop return Undefined

### ISSUE THREAD

**Issue by AkatsukiRyu** [facebook/react-native#27825]
React Native version: "0.60.5"

## Steps To Reproduce

1. `const mapStateToProps = (state: any) => {
  const {product}: {product: ProductReducersProps} = state;
  const {stampDetails}: {stampDetails: ISTampDetails} = product;

  return {
    stampDetails,
  };
};`

when log stampDetails it's return Object with full data.

2. At the render() function
I tried to log stampDetails in Props of component. it's return the same (*)
But at the next line i'm trying logging StampDetails.id it's return of undefined.

Please help me. How can I passing this issue?

**Comment by hramos** [comment]
Can you make sure the entire issue template is filled in? Thanks!
