### ISSUE TITLE
[Android] Provide a way to handle links

### ISSUE THREAD

**Issue by satya164** [facebook/react-native#2782]
Currently there is now way to handle external links on Android. Most apps will have links of some sorts, so it's important that there is an inbuilt module to handle it.

iOS has https://facebook.github.io/react-native/docs/linkingios.html

**Comment by brentvatne** [comment]
Hi there! This is already listed under known issues, this is called "Intent"

Thanks for reporting though :)

**Comment by satya164** [comment]
Thank you. Hope somebod implements it soon :)
