### ISSUE TITLE
Location request timed out on Android 10 

### ISSUE THREAD

**Issue by 8bitpravibyte** [facebook/react-native#27822]
I am trying to log in my app via emulator using Android 10 on it. 
The error that I am getting is `{TIMEOUT: 3, POSITION_UNAVAILABLE: 2, PERMISSION_DENIED: 1, message: "Location request timed out", code: 3}` while on Android 9 works properly and the app is working. 

In the emulator settings I've added geo coordinates and tried to send them to the app. I've tried commenting the object with information passed as 3rd argument to the getCurrentPosition method, adding `<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />` in `AndroidManifest.xml`, toggling enableHighAccuracy, increasing values of timeout and maximumage but it still shows the message. 

Does anybody have stumbled upon the same problem and how can we find solution to this?

React Native version:

System:
    OS: Windows 10 10.0.17763
    CPU: (4) x64 Intel(R) Core(TM) i5-4310M CPU @ 2.70GHz
    Memory: 9.94 GB / 15.91 GB
  Binaries:
    Node: 12.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.1 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.12.0 - C:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 23, 28
      Build Tools: 28.0.3, 29.0.2
      System Images: android-23 | Google APIs Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5977832
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5

## Steps To Reproduce

1. Try to get geolocation info on Android 10

Describe what you expected to happen:
Log the coordinates succesfully and continue with showing the app

Code example:
`Geolocation.getCurrentPosition(info =>
          {
              this.setState({
                  longtude: info["coords"].longitude,
                  latitude: info["coords"].latitude
              })
              console.log(info["coords"]);
          },
          error => {console.error(error)},
          {
             enableHighAccuracy: false,
             timeout: 50000,
             maximumAge: 10000
          }
`

**Comment by VladyslavKochetkov** [comment]
I would suggest using https://www.npmjs.com/package/react-native-geolocation-service 

Your issue is described in their desc.
