### ISSUE TITLE
[0.61.2] Hermes does not support custom variants

### ISSUE THREAD

**Issue by jacob-israel-turner** [facebook/react-native#27829]
The logic in `react.gradle` relies on the variant name to contain `release` in order for Hermes to build properly.

[Source 1](https://github.com/facebook/react-native/blob/master/react.gradle#L166) [Source 2](https://github.com/facebook/react-native/blob/a3b08048674e324dbe1f0ca816f35607e9e06a2f/react.gradle#L302)

In my case, I had a variant called `staging`.  In order for hermes to work for me, I had to rename my variant to `releasestaging`.  Instead, we should be able to pass required options in through `app/build.gradle`, without having to rename the variant.

React Native version:

> System:
>     OS: macOS Mojave 10.14.6
>     CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
>     Memory: 2.35 GB / 32.00 GB
>     Shell: 5.3 - /bin/zsh
>   Binaries:
>     Node: 10.18.1 - ~/.nvm/versions/node/v10.18.1/bin/node
>     Yarn: 1.17.3 - /usr/local/bin/yarn
>     npm: 6.13.4 - ~/.nvm/versions/node/v10.18.1/bin/npm
>     Watchman: 4.9.0 - /usr/local/bin/watchman
>   SDKs:
>     iOS SDK:
>       Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
>     Android SDK:
>       API Levels: 23, 26, 27, 28, 29
>       Build Tools: 27.0.3, 28.0.3, 29.0.2
>       System Images: android-28 | Google Play Intel x86 Atom
>   IDEs:
>     Android Studio: 3.5 AI-191.8026.42.35.5791312
>     Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
>   npmPackages:
>     react: 16.9.0 => 16.9.0
>     react-native: 0.61.2 => 0.61.2

## Steps To Reproduce

1. Create new React Native project
2. Create custom variant that does _not_ include `release` in its name
3. Enable hermes
4. Build to device and see error when launching app:
```
couldn't find DSO to load: libhermes-executor-debug.so caused by: dlopen failed: cannot locate symbol "_ZTIN8facebook6hermes8debugger13EventObserverE" referenced by "/data/app/com.freeplay-q767SRYD9UinoTtLFqtR4Q==/lib/arm64/libhermes-inspector.so"...
```

Describe what you expected to happen:
Expect to build to device and the app to run successfully with Hermes enabled.

Snack, code example, screenshot, or link to a repository:
[Example failing android/app/build.gradle](https://gist.github.com/jacob-israel-turner/3a401e651d94cb3e0f3f0a288471a4b7).  Replacing `staging` with `releasestaging` fixes the issue.

[Related issue](https://github.com/facebook/react-native/issues/25601#issuecomment-511667987).

**Comment by mhorowitz** [comment]
The gradle hacks you refer to are also causing issues with hermes and the android gradle plugin v3.5.  I'm not a gradle expert (I find their patterns hard to work with), but I think I've worked out how to improve this.  But, it will take a few weeks for me to get to it.  Stay tuned.

**Comment by ajiagahari** [comment]
you need to add custom implementation on your '/app/build.gradle'
```
if (enableHermes) {
        def hermesPath = "../../node_modules/hermes-engine/android/"
        debugImplementation files(hermesPath + "hermes-debug.aar")
        releaseImplementation files(hermesPath + "hermes-release.aar")
        stagingImplementation files(hermesPath + "hermes-release.aar")
    } else {
        implementation jscFlavor
    }
```
'staginImplementaion' matches applicationSuffix on build config, as its mention here
> https://developer.android.com/studio/build/dependencies#dependency_configurations

**Comment by dougkeen** [comment]
Alternatively, where there are `targetName.toLowerCase().contains("release")` checks, the gradle file could also honor the `config."devDisabledIn${targetName}"` setting.

**Comment by eliaslecomte** [comment]
This is still a problem in 62.2.

**Comment by mhorowitz** [comment]
I tried to make this work better, but I wasn't able to.  If someone who is better at gradle than I am can submit a PR to improve this, that would be really helpful.
