### ISSUE TITLE
[Android] Unsupported interpolation type : keyboard

### ISSUE THREAD

**Issue by djhr** [facebook/react-native#27839]
As reported in https://github.com/facebook/react-native/issues/23343 and incorrectly closed, `LayoutAnimation.configureNext()` on Android throw's error when using `LayoutAnimation.Types.keyboard` as type.

React Native version:
```
System:
    OS: macOS 10.15.2
    CPU: (4) x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
    Memory: 12.61 GB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.6 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 24, 26, 27, 28
      Build Tools: 27.0.3, 28.0.3, 29.0.2
      System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
      Android NDK: 19.2.5345600
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5
```

## Steps To Reproduce

1. On Android run the following code

```
const animation = LayoutAnimation.create(250, LayoutAnimation.Types.keyboard, 'opacity');
LayoutAnimation.configureNext(animation);
this.setState(...);
```

Describe what you expected to happen:
App not to throw error

Snack, code example, screenshot, or link to a repository:

![Screenshot 2020-01-22 at 16 59 42](https://user-images.githubusercontent.com/1210832/72910319-a988d000-3d38-11ea-882c-452109e23835.png)

**Comment by hramos** [comment]
Did you add the `UIManager.setLayoutAnimationEnabledExperimental(true);` code snippet from https://facebook.github.io/react-native/docs/layoutanimation?

**Comment by djhr** [comment]
> Did you add the `UIManager.setLayoutAnimationEnabledExperimental(true);` code snippet from https://facebook.github.io/react-native/docs/layoutanimation?

Yes

**Comment by yaserloz** [comment]
I have the same pronlem, ``UIManager.setLayoutAnimationEnabledExperimental(true);`` is enabled in the code, the problem is in  ``LayoutAnimation.configureNext({ duration, update: { duration, type:"keyboard" } })``, what is the reason for this error?
