### ISSUE TITLE
[iOS] [Text] allowFontScaling does not adjust the line height correctly

### ISSUE THREAD

**Issue by negativetwelve** [facebook/react-native#2783]
Changing `allowFontScaling` to false disables the font scaling on the font itself, but it does not change the line height which causes interesting layouts to occur (in a bad way).

This line and possibly a few others around it should fix it: https://github.com/facebook/react-native/blob/master/Libraries/Text/RCTShadowText.m#L271

I can make this change if it is confirmed to be a bug and not the desired effect!

**Comment by aprilzero** [comment]
+1, we're having this same issue & it's destroying our app layout if you change accessibility settings, even though fontScaling is set to false.

**Comment by aprilzero** [comment]
Changing line 271 to `CGFloat lineHeight = round(_lineHeight * (_allowFontScaling && _fontSizeMultiplier > 0.0 ? self.fontSizeMultiplier : 1.0));` fix it for us, using the same multiplier code for line height as font size is.

**Comment by Emibob** [comment]
+1 also experiencing this

**Comment by GuilhermeMedeiros** [comment]
+1

Line 282 of RCTShadowText.m on my version seems to be a temporary fix.
```obj-c
CGFloat lineHeight = round(_lineHeight * (_allowFontScaling && _fontSizeMultiplier > 0.0 ? self.fontSizeMultiplier : 1.0));
```
