### ISSUE TITLE
Unable to resolve module `react-native-webview`

### ISSUE THREAD

**Issue by JintoAntony** [facebook/react-native#27832]
I just upgraded to React Native to 0.61. Now, I am getting this error : error: bundling failed: Error: Unable to resolve module `react-native-webview` from `node_modules/react-native-render-html/src/HTMLRenderers.js`: react-native-webview could not be found within the project.

React Native version:
System:
    OS: macOS 10.15.1
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 76.38 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.18.1 - /usr/local/opt/node@10/bin/node
    npm: 6.13.4 - /usr/local/opt/node@10/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5977832
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.12.0 => 16.12.0 
    react-native: ^0.61.5 => 0.61.5

**Comment by vikas5914** [comment]
Try deleting your **node_modules** folder and run `npm install` to install fresh packages.

**Comment by dnlowman** [comment]
Do you have a dependency on https://github.com/react-native-community/react-native-webview? This was recently extracted out of core into it's own package.

**Comment by hramos** [comment]
This is likely due to a dependency on an extracted module as @dnlowman pointed out. We are not tracking this type of question here, so I'll go ahead and close this. We should have a dedicated place for upgrade support soon.

**Comment by JintoAntony** [comment]
Simple solution for this:
$ npm i jetifier
$ npx jetify
