### ISSUE TITLE
[Navigator] Add pushAndPopN method

### ISSUE THREAD

**Issue by chirag04** [facebook/react-native#2784]
@ericvicenti  I can PR a method ``pushAndPopN`` which would push a route and then pop(without animation) n routes present before push.

Eg:
currentRoutes: A, B, C, D

pushAndPopN('E', 1) => A, B, C, E // like replace with push animation
pushAndPopN('E', 2) => A, B, E

Is there a way to this with existing codebase?

cc @ide

**Comment by PhilippKrone** [comment]
@chirag04 I had a discussion about such a feature in here before. My idea was basically to seperate modifications of the routeStack from transitions. Taking your example, my API suggestion was the following:

1) addToRouteStack(<new route>, <index>) // adds route to routeStack at index <index> without transition
2) removeAtIndex(<index>) // removes route from routeStack at index <index>

I think the PR discussion was here: https://github.com/facebook/react-native/pull/2197
Please note that "AddToRouteStack" was implemented as additional functionality to "replaceAtIndex" in this PR.

Regards
Philipp

**Comment by chirag04** [comment]
Interesting. I think addToRouteStacka dn removeAtIndex could potentially solve my case as well. 

Only problem is people would want to do different custom navigation. We should think of an api which allows extensions like this in userland. Not saying this issue solves that.

**Comment by chirag04** [comment]
@PhilippKrone After doing ``removeAtIndex`` do you get the ``pop`` to be smooth?

For me i do removeAtIndex and then pop later. pop does not animate.

**Comment by PhilippKrone** [comment]
@chirag04 I have not had this use case yet. I was rather performing my action first (pop(), popToTop(), push(), etc.) and then use "removeAtIndex()" to modify the routeStack. I had no issues before but as you can see, the PR is already quite old and I'm  not using it actively as I try to stay as close to this RN master as possible. :/
