### ISSUE TITLE
[iOS][Image] No suitable image URL loader found for ph://

### ISSUE THREAD

**Issue by kundarmah** [facebook/react-native#27847]
React Native version: 0.61.5

## Steps To Reproduce

1. Create an Image Component
2. Add a PHAsset source as uri `No suitable image URL loader found for ph://CC95F08C-88C3-4012-9D6D-64A413D254B3/L0/001`

Describe what you expected to happen:
Before upgrading to RN 61.5 my application is working fine to use PHAsset as url

Snack, code example, screenshot, or link to a repository:

![image](https://user-images.githubusercontent.com/6825559/73004410-34092680-3e42-11ea-8413-79cb4ce4bdfe.png)

**Comment by iamrenejr** [comment]
Also running into this. It seems like 0.61.5 cannot render a PHAsset URI. Have you made any progress in rendering the image?

**Comment by Ashoat** [comment]
I'm also seeing trouble trying to render an `assets-library://` URL
