### ISSUE TITLE
JS variable shadowing behavior in Release configuration is different from browsers

### ISSUE THREAD

**Issue by askel4dd** [facebook/react-native#27846]
### Details
I installed JS package, which uglified version includes a code like this (i made it more readable, but the structure is the same):

```js
  const test = function(orly) {
    function orly(orly) {
      console.log("😇 It worked");
    }

    orly('💥 Boom');
  };

  test();
```

Application is working fine in a development environment, but production build will crash with `Unhandled JS Exception: TypeError: l is not a function. (In 'l('\ud83d\udca5 boom')', 'l' is undefined)`. Notice that `orly` variable name was changed to `l` after a minification.

If you will run the same code in your browser (Firefox for example) the result of the function will be `undefined` and a logged message. 

### React Native version:
```
System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
    Memory: 178.95 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 13.2.0 - ~/.nvm/versions/node/v13.2.0/bin/node
    Yarn: 1.19.2 - /usr/local/bin/yarn
    npm: 6.13.1 - ~/.nvm/versions/node/v13.2.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5
```

## Steps To Reproduce

1. `npx react-native init RNFunctionBug`
2. Copy the following code into `App.js` file:
```js
const test = function(orly) {
  function orly(orly) {
    console.log("😇 It worked");
  }

  orly('💥 Boom');
};

test();
```
3. Launch application in Release mode: `yarn ios --configuration="Release"`

**OR**

Launch application using Xcode. That way you will see useful debug information. Change `Run` build configuration to `Release`, like so: 
<img width="922" alt="image" src="https://user-images.githubusercontent.com/7442658/73002408-afe87c00-3e0c-11ea-933d-e3324115dc21.png">

Application will crash with this error:

<img width="435" alt="image" src="https://user-images.githubusercontent.com/7442658/73004589-48ccc680-3e10-11ea-9ca8-a3c9e8eb378f.png">

```
2020-01-23 18:24:11.130 [error][tid:com.facebook.react.JavaScript] TypeError: l is not a function. (In 'l('\ud83d\udca5 boom')', 'l' is undefined)

2020-01-23 18:24:11.132 [fatal][tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: TypeError: l is not a function. (In 'l('\ud83d\udca5 boom')', 'l' is undefined)

2020-01-23 18:24:11.139 [error][tid:com.facebook.react.JavaScript] Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)

2020-01-23 18:24:11.148979+0200 RNFunctionBug[1293:1034276] *** Terminating app due to uncaught exception 'RCTFatalException: Unhandled JS Exception: TypeError: l is not a function. (In 'l('\ud83d\udca5 boom')', 'l' is undefined)', reason: 'Unhandled JS Exception: TypeError: l is not a function. (In 'l('\ud83d\udca5 boom')', 'l' is undefined), stack:
```

Expected behavior is: Application should run as usual with a logged `😇 It worked` message.

**Comment by askel4dd** [comment]
My progress:

1. I tried to run the code inside JavaScriptCore repl `/System/Library/Frameworks/JavaScriptCore.framework/Versions/Current/Resources/jsc` and it's working fine. Result of the function is `undefined` and a logged message.

2. I suspected that since this bug is only occurs in Release configuration (aka production mode) it has to be something with JS bundling/minification.

I created a separate file `test.js` in the project root directory with the problematic function and processed it with metro bundler like so: `metro build test.ts --dev=false --out=test.output.js`

```
const test = function (orly) {
    function orly(orly) {
        console.log("😇 IT WORKED")
    }

    orly('💥 boom');
};

test();
```

was transformed into:

```
  // Bundler specific code here which i cut
  var test = function test(orly) {
    orly('💥 boom');
  };

  test();
  // Bundler specific code here which i cut
```

**Comment by Gray-Wind** [comment]
Original source of provided reproduction is in uglified version of some of npm package. We cannot control usage of this uglification, so it is possible source of many problems in RN applications.

Uglifier could (and in our case did) provide a source code, which works in almost all cases, except in React Native application.

**Comment by askel4dd** [comment]
After further debugging i found out that disabling babel `constantFoldingPlugin` by commenting out inside `node_modules/metro/src/JSTransformer/worker.js` file following line:

```js
      if (!options.dev) {
        plugins.push([constantFoldingPlugin, opts]);
      }
```

This pluging in located here: `node_modules/metro/src/JSTransformer/worker/constant-folding-plugin.js`.

So, my previous assumption that the bug was related `uglify-es` is incorrect.
