### ISSUE TITLE
Cannot use focus() on Android TV

### ISSUE THREAD

**Issue by mrcatman** [facebook/react-native#27859]
I'm trying to build a React Native app for Android TV. In some parts of app I need to manually focus on some elements. But if I try to focus on any of them using refs, an error appears:
"Illegal number of arguments for 'UpdateHotspot' command".

For some reason, focusing on TextInput does work as expected, focusing on another components does not. 

React Native version:
System:
    OS: Windows 8.1 6.3.9600
    CPU: (8) x64 Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
    Memory: 945.05 MB / 15.90 GB
  Binaries:
    Node: 12.10.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.10.3 - C:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 17, 23, 25, 27, 28, 29
      Build Tools: 27.0.3, 28.0.3, 29.0.2
      System Images: android-17 | MIPS, android-17 | Google APIs Intel x86 Atom,
 android-19 | Google APIs Intel x86 Atom, android-22 | Android TV Intel x86 Atom
, android-25 | Android TV Intel x86 Atom, android-27 | Google Play Intel x86 Ato
m, android-28 | Android TV Intel x86 Atom
  IDEs:
    Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5692245
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5

## Steps To Reproduce
```
import React from 'react';
import {
    SafeAreaView,
    ScrollView,
    View,
    TouchableHighlight,
    Button
} from 'react-native';

class App extends React.Component {
    constructor() {
        super();
        this.focusRef = this.focusRef.bind(this);
     }

    focusRef(ref) {
        ref.focus();
    }

    render() {
        return (
            <>
                <SafeAreaView>
                    <ScrollView>
                        <View>

                            <TouchableHighlight hasTVPreferredFocus={true} ref={ref => this.focusRef(ref)}>
                                <Button title="test">
                                </Button>
                            </TouchableHighlight>
                        </View>
                    </ScrollView>
                </SafeAreaView>
            </>
        );
    }
};
export default App;
```

**Comment by ricardoMogg** [comment]
We are seeing the same issue. Has anyone found any other way to force focus on a non-textInput element on AndroidTV?
