### ISSUE TITLE
TextInput Text is not shown on IOS 13.3

### ISSUE THREAD

**Issue by appify-waheed** [facebook/react-native#27856]
I am using react-native `0.61.2` and while entering text into textInput didn't show anything but text entered successfully, this issues only happens with IOS `v13.3` on the other versions and on android it works fine.

React Native version:
  System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
    Memory: 23.05 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.2 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 22, 23, 24, 25, 26, 27, 28, 29
      Build Tools: 23.0.1, 25.0.3, 26.0.2, 27.0.3, 28.0.3
      System Images: android-18 | Google APIs ARM EABI v7a, android-21 | Google APIs ARM EABI v7a, android-21 | Google APIs Intel x86 Atom, android-21 | Google APIs Intel x86 Atom_64, android-22 | Google APIs ARM EABI v7a, android-22 | Google APIs Intel x86 Atom, android-22 | Google APIs Intel x86 Atom_64, android-23 | Google APIs ARM EABI v7a, android-23 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-24 | Google APIs ARM EABI v7a, android-24 | Google APIs Intel x86 Atom, android-24 | Google APIs Intel x86 Atom_64, android-25 | Google APIs ARM 64 v8a, android-25 | Google APIs ARM EABI v7a, android-25 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom_64, android-25 | Google Play Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-29 | Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.2 => 0.61.2 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7

## Steps To Reproduce
use IOS `13.3` and enter text into textinput.

Describe what you expected to happen:
Text should appears on ios version `13.3`, By the way i am using IPhone 8 plus.

![EmptyText](https://user-images.githubusercontent.com/45425486/73077277-b0067b80-3ee1-11ea-9edc-a2e8f2ae503e.gif)

**Comment by fuggerstadt1907** [comment]
Looks like an iOS 13 Dark-Mode Issue. White Text on White Background.
Try to change the font color of your Inputs

**Comment by appify-waheed** [comment]
@fuggerstadt1907 yeah you are right issue is with dark mode when i turns off dark mode then i can see text. any solution of it ?

**Comment by fuggerstadt1907** [comment]
Yes, like already mentioned in my last post. Give your Input Text a font color != white

**Comment by appify-waheed** [comment]
@fuggerstadt1907 Thanks i already did this and it works.

**Comment by JonnyBurger** [comment]
Found the bug I believe and made a PR: https://github.com/facebook/react-native/pull/28280
