### ISSUE TITLE
Can't scrollToOffset() FlatList when use with Animated.ScrollView

### ISSUE THREAD

**Issue by ogous** [facebook/react-native#27864]
React Native version:
0.61.4

## Steps To Reproduce

When i use renderScrollComponent for Flatlist with a Animated.ScrollView:

renderScrollComponent={props => (
<Animated.ScrollView
{...props}
/>

FlatList's scrollTo functions (like scrollToOffset) stop working.

Here is a re-pro: [scrollToOffset becomes undefined](https://snack.expo.io/@cyborg/cant-scrolltooffset-flatlist)

If you use it with a RN ScrollView everything works normally. It seems problem occurs when you use Animated component for renderScrollComponent. It is same with RN-Animated and RN-Reanimated.

Anybody have an idea about it?

**Comment by 592da** [comment]
This issue occurs when using regular `ScrollView`, with nested `SectionList`, and trying to scroll to a specific section index.

Please advice folks :)

**Comment by djendacott** [comment]
+1 can we get this bug fixed please?

**Comment by co2nut** [comment]
+1

**Comment by machadolucasvp** [comment]
+1 This issue is currently blocking me, someone knows a workaround ?

**Comment by aqos156** [comment]
+1 react-native 0.63.1

**Comment by aqos156** [comment]
A sufficient fix for me was to replace in `node_modules/react-native/Libraries/Lists/VirtualizedList.js` any occurrence of `this._scrollRef.scrollTo(.....)` with:

    const scrollComponent = this._scrollRef?.getNode ? this._scrollRef.getNode() : this._scrollRef;

    scrollComponent.scrollTo(.....);

After that i used [patch-package](https://github.com/ds300/patch-package) to apply this any time i use `yarn install`

**Comment by aqos156** [comment]
This issue still seems to persist in version 64. I am still able to fix it with previously mentioned package `patch-package` with this diff:

```diff
diff --git a/node_modules/react-native/Libraries/Lists/VirtualizedList.js b/node_modules/react-native/Libraries/Lists/VirtualizedList.js
index 2249d54..cb52f1b 100644
--- a/node_modules/react-native/Libraries/Lists/VirtualizedList.js
+++ b/node_modules/react-native/Libraries/Lists/VirtualizedList.js
@@ -454,7 +454,9 @@ class VirtualizedList extends React.PureComponent<Props, State> {
       return;
     }
 
-    this._scrollRef.scrollTo(
+    const scrollComponent = this._scrollRef?.getNode ? this._scrollRef.getNode() : this._scrollRef;
+
+    scrollComponent.scrollTo(
       horizontal ? {x: offset, animated} : {y: offset, animated},
     );
   }
```

**Comment by lame-dev** [comment]
+1

**Comment by geoffroyBellemare** [comment]
+1
