### ISSUE TITLE
Function component renders incorrectly after Fast Refresh

### ISSUE THREAD

**Issue by mxhold** [facebook/react-native#27862]
I've encountered at least one scenario where a function component rendered after a Fast Refresh looks wrong and requires a hard refresh to fix. Changing it to a class component fixes this.

GIF:
![expo-fast-refresh-bug](https://user-images.githubusercontent.com/1921012/73113137-fe5a5100-3ec6-11ea-802d-616a4da63b0c.gif)

React Native version:
```
System:
    OS: macOS 10.15.2
    CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
    Memory: 17.85 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 13.7.0 - /var/folders/7q/w_rts5kx5gzfk051cpw8vlzh0000gn/T/yarn--1579912407030-0.8849373494224462/node
    Yarn: 1.21.1 - /var/folders/7q/w_rts5kx5gzfk051cpw8vlzh0000gn/T/yarn--1579912407030-0.8849373494224462/yarn
    npm: 6.13.6 - ~/.nvm/versions/node/v13.7.0/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3.1/11C505 - /usr/bin/xcodebuild
  npmPackages:
    react: ~16.9.0 => 16.9.0
    react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4
```

## Steps To Reproduce

1. Pull down this project: https://github.com/mxhold/rn-fast-refresh-bug
2. Open app in iOS simulator with Fast Refresh turned on.
3. Uncomment the commented line in App.tsx that sets `flexGrow`.
4. Save the file, triggering a refresh. Note the border is unchanged, as expected.
5. Comment out the same line (returning the file to its original contents).
6. Save the file again, triggering a refresh again.  Note the border has collapsed as if `flex: 1` was not set (!).
7. Press Cmd-R to refresh. Note the border goes back to the original position.

Describe what you expected to happen:

It is surprising that after step 6 the screen renders incorrectly and requires a hard refresh to render correctly.

I would have expected that after step 6, the border would have stayed in the same position but instead the view is rendered as if `flex: 1` was not set at all.

## Notes

- This example doesn't work if you change `App` to a class component. It has to be a function component.
- This doesn't seem to be reproducible in a Snack.

**Comment by gaearon** [comment]
I just saw this (for future reference, please @-mention me instead of assigning because I don't see assignments anywhere). Unfortunately, since I already read this issue, it has already disappeared from my notifications, so I won't see it again unless someone pings me. Please ping me again next week! Thank you.

**Comment by mxhold** [comment]
@gaearon

**Comment by chrisglein** [comment]
This has sit stale for awhile. Issues with Fast Refresh can be frustrating for inner loop efficiency. Does this still repro on latest?

**Comment by gaearon** [comment]
Bump

**Comment by chrisglein** [comment]
> Bump

Is that a yes? Were you able to repro on latest? This issue was opened against 61.

**Comment by AndrewMorsillo** [comment]
I may be encountering the same or a related issue. I have a function component that works fine when first loaded. If I edit the file and the component is fast refreshed it starts an infinite loop. Even after a reload it _still_ infinite loops. Only way to break the loop is to close the app on the emulator and open it again, seems some sort of bad state is persisted even across reload? Working on nailing down a repro to see if it's the same kind of issue as reported here.

@gaearon

**Comment by gaearon** [comment]
@AndrewMorsillo This sound quite bizarre! (I don't think it has any relation to this issue btw.)

**Comment by gaearon** [comment]
>Is that a yes? Were you able to repro on latest? This issue was opened against 61.

No, I just haven't got a confirmation that this either doesn't repro or that it was fixed.

**Comment by gaearon** [comment]
Actually I wonder if this case is related to conflicting values between long and shorthand `flex` property notation.
We warn for this in the DOM because it's broken: https://reactjs.org/blog/2020/02/26/react-v16.13.0.html#warnings-for-conflicting-style-rules
Maybe RN has the same problem?
