### ISSUE TITLE
E ActivityTrigger: activityStartTrigger: not whiteListed com.wesleyapp/com.wesleyapp.MainActivity/1

### ISSUE THREAD

**Issue by bmbmjmdm** [facebook/react-native#27866]
### **Overview**
(My app name is wesleyapp)

I am able to run my app perfectly fine with `react-native run-android` after creating a dev bundle. 

However when I try to run `react-native run-android --variant=release`, the app crashes immediately when started. This is after creating a release bundle. 

Bundle command being used (without `--dev false` for dev bundle): `react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle`

Looking at the logs, there appear to be a few possible culprits. The most likely one, I believe, is the one in the title: `E ActivityTrigger: activityStartTrigger: not whiteListedcom.wesleyapp/com.wesleyapp.MainActivity/1`

The next most likely candidate would be `W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class `...

And lastly `E ReactNativeJS: { [RangeError: Maximum call stack size exceeded.] line: 343, column: 7038, sourceURL: 'index.android.bundle' }`

After scouring these forums and attempting to debug for 3 days now, I'm turning to you for help.

I tried looking through these similar issues but have found no success:
https://github.com/facebook/react-native/issues/6692
https://github.com/facebook/react-native/issues/16689
https://github.com/facebook/react-native/issues/20476

### **React Native version:**
Environment:
  OS: Windows 10
  Node: 10.16.2
  Yarn: Not Found
  npm: 6.9.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5692245

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4

### **Package.json**
```
{
  "name": "wesleyapp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "@babel/runtime": "^7.7.7",
    "react": "16.3.1",
    "react-native": "0.55.4",
    "stacktrace-parser": "0.1.4",
    "react-native-audio": "^4.3.0",
    "react-native-image-picker": "^1.1.0",
    "react-native-sound": "^0.11.0",
    "react-native-tts": "^3.0.0",
    "vue-native-core": "0.0.8",
    "vue-native-helper": "0.0.11",
    "vuex": "^3.1.1",
  },
  "devDependencies": {
    "babel-jest": "24.8.0",
    "babel-preset-react-native": "4.0.1",
    "jest": "24.8.0",
    "react-test-renderer": "16.3.1",
    "vue-native-scripts": "0.0.16"
  },
  "jest": {
    "preset": "react-native"
  }
}
```
### **Android logs:**

https://gist.github.com/bmbmjmdm/5f6c971fc43a207c68edcd65949aa77f

**Comment by bmbmjmdm** [comment]
Upgraded to latest version. New version info:
```
System:
    OS: Windows 10 10.0.18362
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 7.01 GB / 15.93 GB
  Binaries:
    Node: 10.16.2 - C:\Program Files\nodejs\node.EXE
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5692245
  npmPackages:
    react: 16.11.0 => 16.11.0
    react-native: 0.62.0-rc.1 => 0.62.0-rc.1
```
First two errors are gone! Last one still remains however, making me unable to run app: 
```
[21:38:37] D | ReactNative ▶︎ ReactInstanceManager.ctor()
[21:38:37] D | ReactNative ▶︎ ReactInstanceManager.createReactContextInBackground()
                           └ ReactInstanceManager.recreateReactContextInBackgroundInner()
[21:38:37] D | ReactNative ▶︎ ReactInstanceManager.recreateReactContextInBackgroundFromBundleLoader()
                           │ ReactInstanceManager.recreateReactContextInBackground()
                           └ ReactInstanceManager.runCreateReactContextOnNewThread()
[21:38:37] D | ReactNative ▶︎ ReactInstanceManager.createReactContext()
[21:38:37] D | ReactNative ▶︎ Initializing React Xplat Bridge.
[21:38:37] D | ReactNative ▶︎ Initializing React Xplat Bridge before initializeBridge
[21:38:37] D | ReactNative ▶︎ Initializing React Xplat Bridge after initializeBridge
                           └ CatalystInstanceImpl.runJSBundle()
[21:38:37] D | ReactNative ▶︎ ReactInstanceManager.setupReactContext()
[21:38:37] D | ReactNative ▶︎ CatalystInstanceImpl.initialize()
[21:38:37] D | ReactNative ▶︎ ReactInstanceManager.attachRootViewToInstance()
[21:38:37] D | ReactNative ▶︎ ReactInstanceManager.createReactContextInBackground()
[21:38:37] D | ReactNative ▶︎ ReactInstanceManager.attachRootViewToInstance()
[21:38:38] I | ReactNativeJS ▶︎ Running "wesleyapp" with {"rootTag":1}
[21:38:38] E | ReactNativeJS ▶︎ RangeError: Maximum call stack size exceeded.
```
`ReactNativeJS ▶︎ RangeError: Maximum call stack size exceeded.` has a stack trace of 
```
get
index.android.bundle:394:5662
addDep
index.android.bundle:394:15002
depend
index.android.bundle:394:4355
get
index.android.bundle:394:5662
...
```

**Comment by bmbmjmdm** [comment]
bump please remove the label, I've tested with the latest version and the problem persists

**Comment by bmbmjmdm** [comment]
bump, gonna start a new bug report soon if this doesnt get a response

**Comment by alexcohn** [comment]
`activityStartTrigger: not whiteListed` is not an error. It only says that your activity is not getting some very special privileges reserved to some system (or vendor) apps.

**Comment by vietnt-uet** [comment]
I'm facing the same problem and sometimes (but constantly) can't start App from the launcher in Android.

**Comment by derwaldgeist** [comment]
> `activityStartTrigger: not whiteListed` is not an error. It only says that your activity is not getting some very special privileges reserved to some system (or vendor) apps.

If it is not an error, then why is it flagged as one?
