### ISSUE TITLE
Issue With redirect image url

### ISSUE THREAD

**Issue by mhmdAljefri** [facebook/react-native#27868]
React Native version:

react: 16.8.3 => 16.8.3 
react-native: 0.59.10 => 0.59.10 

Package.json:

```
{
  "name": "tracks",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "npx jetify && node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "@react-native-community/async-storage": "^1.6.1",
    "@react-native-firebase/app": "^6.0.2",
    "@react-native-firebase/messaging": "^6.0.2",
    "axios": "^0.18.0",
    "axios-debug-log": "^0.6.2",
    "babel-plugin-inline-import": "^3.0.0",
    "babel-plugin-transform-inline-environment-variables": "^0.4.3",
    "formik": "^1.5.4",
    "i18next": "^17.0.4",
    "lodash": "^4.17.15",
    "prop-types": "^15.7.2",
    "qs": "^6.7.0",
    "react": "16.8.3",
    "react-i18next": "^10.11.2",
    "react-native": "0.59.10",
    "react-native-animatable": "^1.3.2",
    "react-native-gesture-handler": "^1.2.1",
    "react-native-google-signin": "^2.0.0",
    "react-native-image-picker": "^1.0.1",
    "react-native-list-gallery": "^1.0.5",
    "react-native-localize": "^1.1.3",
    "react-native-maps": "^0.24.2",
    "react-native-modal": "^11.0.1",
    "react-native-navigation-bar-color": "^0.1.0",
    "react-native-restart": "^0.0.12",
    "react-native-safe-area-context": "^0.6.1",
    "react-native-safe-area-view": "^1.0.0",
    "react-native-share": "1.2.1",
    "react-native-vector-icons": "^6.4.2",
    "react-navigation": "^3.9.1",
    "react-navigation-fluid-transitions": "^0.3.2",
    "react-redux": "^7.0.3",
    "redux": "^4.0.1",
    "redux-persist": "^5.10.0",
    "redux-promise-middleware": "^6.1.0",
    "redux-thunk": "^2.3.0",
    "yup": "^0.27.0"
  },
  "devDependencies": {
    "@babel/core": "^7.4.5",
    "@babel/runtime": "^7.4.5",
    "babel-jest": "^24.8.0",
    "eslint": "^5.16.0",
    "eslint-config-airbnb": "^17.1.0",
    "eslint-config-prettier": "^4.2.0",
    "eslint-plugin-import": "^2.17.2",
    "eslint-plugin-jsx-a11y": "^6.2.1",
    "eslint-plugin-prettier": "^3.0.1",
    "eslint-plugin-react": "^7.13.0",
    "eslint-plugin-react-native": "^3.7.0",
    "husky": "2.2.0",
    "jest": "^24.8.0",
    "jetifier": "^1.6.3",
    "lint-staged": "8.1.6",
    "metro-config": "^0.54.0",
    "metro-react-native-babel-preset": "^0.54.1",
    "prettier": "^1.17.0",
    "react-native-svg-transformer": "^0.13.0",
    "react-test-renderer": "16.8.3"
  },
  "lint-staged": {
    "*.{js,jsx}": [
      "eslint --fix",
      "git add"
    ],
    "*.{json,md,yaml,yml}": [
      "prettier --write",
      "git add"
    ]
  },
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  },
  "jest": {
    "preset": "react-native"
  }
}

```

## Steps To Reproduce

1.
2.

Describe what you expected to happen:

It should show the images, instead of blank spaces

Snack, code example, screenshot, or link to a repository:

In developement:

![WhatsApp Image 2020-01-17 at 11 57 35 AM](https://user-images.githubusercontent.com/15002714/73169501-45d21e80-410d-11ea-921d-858027b020eb.jpeg)

In Production (Released version):

![WhatsApp Image 2020-01-17 at 10 36 27 AM](https://user-images.githubusercontent.com/15002714/73169486-3bb02000-410d-11ea-844a-50cbffb446a0.jpeg)

**Comment by leosena777** [comment]
@mhmdAljefri can you provide the code snippet where you render the images?
Does the file come from an api or is it locally in the project?

**Comment by leosena777** [comment]
@mhmdAljefri if uri, is it being called via https or http?

**Comment by mhmdAljefri** [comment]
sure @leosena777

code below for image component used in multiple places in my codebase.

```
import React from 'react';
import PropTypes from 'prop-types';
import { View } from 'react-native';
import Image from 'react-native-fast-image';
import { Transition } from 'react-navigation-fluid-transitions';

function AvatarContainer({ avatarUrl, style }) {
  
  return (
    <Transition shared={avatarUrl}>
      <View
        style={[
          {
            width: 64,
            height: 64,
            overflow: 'hidden',
            borderRadius: 64,
            margin: 10,
            backgroundColor: '#fff',
          },
          style,
        ]}
      >
        <Image style={{ flex: 1 }} resizeMode="contain" source={{ uri: avatarUrl }} />
      </View>
    </Transition>
  );
}

AvatarContainer.defaultProps = {
  style: {},
  avatarUrl: null,
};
AvatarContainer.propTypes = {
  avatarUrl: PropTypes.string,
  style: PropTypes.oneOfType([PropTypes.object, PropTypes.array]),
};

export default AvatarContainer;

```

local images work fine and also image from api without redirect.

issue happend with rails image which was implemented with redirect approach. such link below:
https://api.findmytruck.ae/rails/active_storage/representations/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdFFDIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5e17701e0b3fd5a69dcedd17faab777a04916417/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCam9MY21WemFYcGxTU0lNTVRBd2VERXdNQVk2QmtWVSIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--1fe8cc9c709478a2a4ce49cfefe9d8b5d952ddb1/Chickery%20Logo.jpeg

![image](https://user-images.githubusercontent.com/15002714/73182590-5fce2a00-412a-11ea-9801-32d6d56adce1.png)

**Comment by leosena777** [comment]
@mhmdAljefri 

Nunca tive esse problema, sorry :/ , mas fiz uma pesquisa e sugeriram um componente para correção desse problema no stackoverflow. Veja se é útil para você.

https://stackoverflow.com/questions/46716067/remote-images-not-following-redirect-on-android-using-react-native

**Comment by leosena777** [comment]
@mhmdAljefri 

I never had this problem, sorry :/  , but I did some research and suggested a component to fix this problem in the stackoverflow. See if it's useful for you.

https://stackoverflow.com/questions/46716067/remote-images-not-following-redirect-on-android-using-react-native

**Comment by mhmdAljefri** [comment]
Thank you @leosena777 .

It was happened because the configuration of Network security for android was missing.
https://developer.android.com/training/articles/security-config#CleartextTrafficPermitted

**Comment by JiboStore** [comment]
Image source that points to url with redirect finally works for me..

In my case, the url has to return http/301 (tested for double redirection) or http/307 (tested) with `Location` on the header pointing to next (or final) url that returns http/200

**Comment by justinthiele** [comment]
Ensuring that the image URL was https and not http fixed it for me.
