### ISSUE TITLE
[Gradle] Compilation error when building react native gradle plugin

### ISSUE THREAD

**Issue by geof90** [facebook/react-native#2786]
Line 52 here causes a compilation error.
https://github.com/facebook/react-native/blob/master/react-native-gradle/src/test/java/com/facebook/react/PackageJSTasksTest.java#L52

If u look at Line 17 here
https://github.com/facebook/react-native/blob/master/react-native-gradle/src/main/java/com/facebook/react/PackageDebugJsTask.java#L17

PackageDebugJsTask.packageJS() throws Exception, which is not specified in the method signature here:
https://github.com/facebook/react-native/blob/master/react-native-gradle/src/test/java/com/facebook/react/PackageJSTasksTest.java#L48

**Comment by foghina** [comment]
The gradle plugin is on hold right now as we are exploring alternatives (i.e. making `react-native bundle` work with Android).

**Comment by mkonicek** [comment]
Closing as Felix answered this.
