### ISSUE TITLE
react native force light mode in android app

### ISSUE THREAD

**Issue by Mohammad1704** [facebook/react-native#27876]
React Native version:

in other words how to disable dark mode from android app 

thank you so much 😊

**Comment by inferusvv** [comment]
Issue closed, but no answers.. How to disable this mode? I don't want phone settings affect my app styles.

**Comment by eliasjnior** [comment]
Probably related to #29387

**Comment by amerllica** [comment]
Dear @dulmandakh, why you close this important issue without an answer?

**Comment by dulmandakh** [comment]
Sorry, themes are related to Android, not React Native, so please look into Android documentation.

**Comment by amerllica** [comment]
@Mohammad1704, For disable force dark mode you can follow [this StackOverflow answer](https://stackoverflow.com/a/64339016/6877799)

**Comment by amerllica** [comment]
Dear @dulmandakh, this kind of behavior or answering just caused discourage and disappoint developers. actually, answering others' questions and attention to them is attention to yourself. all of us know `force dark mode theme` is for Android but your developers faced this new unwanted feature and a little help can help the community.

**Comment by leoyb** [comment]
@amerllica I tried your method, but it didn't work

**Comment by amerllica** [comment]
@leoyb, that is impossible, why it didn't work? can you write about your environment?

**Comment by dulmandakh** [comment]
@amerllica you can open your project in Android Studio, then edit styles.xml to extend a theme you want to use. I closed the issue because it's not related to React Native neither resolvable in it. Sorry.

**Comment by leoyb** [comment]
@amerllica 

## Environment
```js
Environment:
  OS: macOS Catalina 10.15.6
  Node: 10.16.0
  Yarn: 1.16.0
  npm: 6.9.0

Packages:
  "react": "16.13.1",
  "react-native": "0.63.2"
```

Configuration information:
![image](https://user-images.githubusercontent.com/10185166/97250956-fbb7ce00-1841-11eb-87af-b54c8c85ad04.png)
![image](https://user-images.githubusercontent.com/10185166/97250972-01adaf00-1842-11eb-9bef-7b052d09f1b2.png)

**Comment by amerllica** [comment]
@leoyb, what is the `compileSdkVersion` in your `android/app/build.gradle`  file:

```
android {
    compileSdkVersion ???
```

What is `???` for your project?

**Comment by leoyb** [comment]
@amerllica 
![image](https://user-images.githubusercontent.com/10185166/97280385-2c662a80-1877-11eb-977b-de8113bf75f2.png)

**Comment by amerllica** [comment]
@leoyb, Use `compileSdkVersion` version **30**, the `android/app/build.gradle` is ok, just change the `android/build.gradle`.

Please attention, at the end of [my StackOverflow post](https://stackoverflow.com/a/64339016/6877799), delete all last builds and catches:

> Hint: For being sure that you have a new build, completely delete your last build by using the `rm -rf android/app/build` command and uninstall the app on your Emulator/Device and then run `yarn android` again.

**Comment by leoyb** [comment]
@amerllica 
According to your method, it still doesn't work

**Comment by amerllica** [comment]
@leoyb, Could you upload a re-production of your project somewhere?

**Comment by amerllica** [comment]
@leoyb, Let me know, What does it mean _It doesn't work!_. Could you explain what's your desire and what happened what you said _It doesn't work!_. and another question, Could you upload a re-production of your project somewhere?

**Comment by kruz123** [comment]
@amerllica  i apply your [https://stackoverflow.com/a/64339016/6877799](url) solutions but didn't work below attach my enviroment images :
android/app/build.gradle file ss:
![1_ss](https://user-images.githubusercontent.com/62372729/103605354-b565a600-4f39-11eb-8176-8e08d93f0c3d.png)
android/build.gradle file ss:
![3_ss](https://user-images.githubusercontent.com/62372729/103605388-cd3d2a00-4f39-11eb-93ca-bc20552472a0.png)
react index.js file ss:
![2_ss](https://user-images.githubusercontent.com/62372729/103605408-da5a1900-4f39-11eb-91c5-2979e8f3b4db.png)
styles.xml file ss :
![4_ss](https://user-images.githubusercontent.com/62372729/103605451-ec3bbc00-4f39-11eb-8b9c-dbabc58211de.png)

so please help me and solve my problem

**Comment by amerllica** [comment]
@kruz123, exactly follow my solution, for example use `<item name="android:forceDarkAllowed">false</item>` this. exactly what I logged in that SO answer, clean your last builds and even caches. then try again, if still it doesn't work so change the `29` to `30`, and try again. it should work.

**Comment by mattgle** [comment]
Hey guys! I've found a solution to force the app to stay in Light-theme you just need to follow this steps.

_**For Android:**_ 
Go to `android/app/src/main/res/values/styles.xml` and add the following line: 
```
<item name="android:forceDarkAllowed">false</item>
```
The file will look like this:
```
<resources>
    <!-- Base application theme. -->
    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <!-- Customize your theme here. -->
        <item name="android:textColor">#000000</item>
        <item name="android:forceDarkAllowed">false</item>
    </style>
</resources>
```
_**For iOS:**_
Go to the `Info.plist` and add the following code:
```
<key>UIUserInterfaceStyle</key>
<string>Light</string>
```

That's all, don't forget to delete previous builds. I hope this works for you! Cheers.

**Comment by pavelpashkovsky** [comment]
in `android/app/src/main/java/com/rrmobile/MainApplication.java` 

add `import androidx.appcompat.app.AppCompatDelegate;` to top import section. Then add `AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_NO);` to `onCreate()`. This action disables dark mode on android.

![image](https://user-images.githubusercontent.com/7372044/125782053-67e2387d-d72e-4d19-b686-60600f63e446.png)

**Comment by Souravpakhira** [comment]
If anyone Still facing the dark mode issue here how I solved my problem.
I just changed the DayNight to Light in AppTheme.
    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
This is how my files look after changing.
 `<resources>

    
    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        
        <item name="android:textColor">#000000</item>
        <item name="android:forceDarkAllowed">false</item>
    </style>

</resources>`

**Comment by 9r4ik** [comment]
Выдает эту ошибку при билде
AAPT: error: style attribute 'android:attr/forceDarkAllowed' not found.

**Comment by inferusvv** [comment]
> i face with this error when build AAPT: error: style attribute 'android:attr/forceDarkAllowed' not found.

Could you provide full code?

**Comment by 9r4ik** [comment]
// styles.xml
<resources>

    
    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        
        <item name="android:forceDarkAllowed">false</item>
        <item name="android:textColor">#000000</item>
    </style>

</resources>



> > i face with this error when build AAPT: error: style attribute 'android:attr/forceDarkAllowed' not found.
> 
> Could you provide full code?

**Comment by inferusvv** [comment]
@9r4ik Is it wrapper in `<resources>`?

My styles.xml:

```
<resources>

    <!-- Base application theme. -->
    <style name="AppTheme" parent="Theme.AppCompat.DayNight.NoActionBar">
        <item name="android:textColor">#000000</item>
        <item name="android:forceDarkAllowed">false</item>
        <item name="android:navigationBarColor">#000000</item>
        <item name="android:windowBackground">#000000</item>
    </style>

</resources>

```

**Comment by 9r4ik** [comment]
> @9r4ik Is it wrapper in `<resources>`?
> 
> My styles.xml:
> 
> ```
> <resources>
> 
>     
>     <style name="AppTheme" parent="Theme.AppCompat.DayNight.NoActionBar">
>         <item name="android:textColor">#000000</item>
>         <item name="android:forceDarkAllowed">false</item>
>         <item name="android:navigationBarColor">#000000</item>
>         <item name="android:windowBackground">#000000</item>
>     </style>
> 
> </resources>
> ```

sorry, yes

**Comment by inferusvv** [comment]
@9r4ik  Maybe you could try to change your `parent` attribute in styles.xml?

` parent="Theme.AppCompat.DayNight.NoActionBar"`
