### ISSUE TITLE
LaunchScreen.xib: error: Encountered an error communicating with IBAgent-iOS.

### ISSUE THREAD

**Issue by xchinjo** [facebook/react-native#27877]
$npx react-native run-ios

LaunchScreen.xib: error: Encountered an error communicating with IBAgent-iOS.
    Failure Reason: IBAgent-iOS (48034) failed to launch and exited with status 6
    Recovery Suggestion: Please check Console.app for crash reports for "IBAgent-iOS" for further information.
    Underlying Errors:
        Description: Failed to launch IBAgent-iOS via CoreSimulator spawn
        Underlying Errors:
            Description: Failed to handshake with platform tool
            Failure Reason: Failed to keep platform tool alive
            Underlying Errors:
                Description: Failed to keep launch platform tool and keep alive
                Recovery Suggestion: Try restarting your computer
                Underlying Errors:
                    Description: Failed to communicate with helper tool
                    Failure Reason: The tool closed the connection

** BUILD FAILED **

React Native version:
System:
    OS: macOS 10.15.2
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 1.03 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.17.0 - /usr/local/bin/yarn
    npm: 6.11.2 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 23.0.1, 26.0.1, 26.0.3, 27.0.3, 28.0.3, 29.0.0, 29.0.2
      System Images: android-24 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
    react-native-location: 2.5.0

**Comment by hramos** [comment]
This issue needs a bit more fleshing out before it can be evaluated. Please fill out the entire issue template.

**Comment by krutarth-sportsbet** [comment]
Check if Xcode has a write permission to `/Library/Logs` folder. Softwares like `DaisyDisk` could mess up the permissions for that folder which could result to the error you are facing.

You will be able to find "permission denied" on Console.app logs. If that is the issue.

**Comment by lucaschen93** [comment]
Hello, I've encountered this error while using Xcode 13. All my .xib files were unable to be used on my project. 

So my solution was to downgrade my Xcode version to 12.5.1 by downloading here https://developer.apple.com/download/all/ If my solution can help someone, it would be fine !
