### ISSUE TITLE
Error while updating property 'accessibilityRole' of a view managed by:RCTView

### ISSUE THREAD

**Issue by NareshPalle9** [facebook/react-native#27884]
Hi I am getting following error. PFA

Error while updating property 'accessibilityRole' of a view managed by:RCTView
null
Invalid accessibility role value:tab

React Native Environment Info:
    System:
      OS: macOS 10.15.2
      CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
      Memory: 53.47 MB / 8.00 GB
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
      npm: 6.13.4 - ~/.nvm/versions/node/v12.14.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
      Android SDK:
        API Levels: 28, 29
        Build Tools: 28.0.3, 29.0.2
        System Images: android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3 
      react-native: ^0.59.10 => 0.59.10 
![Screenshot 2020-01-28 at 1 09 53 PM](https://user-images.githubusercontent.com/57945978/73244238-7b3f4080-41cf-11ea-84e9-e7758a3146c6.png)

**Comment by maskaravivek** [comment]
I am also facing a similar issue.

**Comment by rafwell** [comment]
+1

**Comment by maskaravivek** [comment]
I think it got fixed for me once i updated by RC version.

**Comment by ceessay** [comment]
Hi @maskaravivek which version of react native did you end up using and did you identify the cause of the problem ?

**Comment by maskaravivek** [comment]
I ended up using 0.61.5. Unfortunately I don't remember the exact change that fixed the issue.

**Comment by Vijaysreekar4994** [comment]
i'm having the same problem, could you please let me know the solution ?

**Comment by Vijaysreekar4994** [comment]
> i'm having the same problem, could you please let me know the solution ?

i solved it by linking all the libraries. its wrkng now!
