### ISSUE TITLE
Android Build Gradle 3.5.3

### ISSUE THREAD

**Issue by wincod75** [facebook/react-native#27882]
Error when syncing files or running gradlew clean:
Could not find com.android.tools.build:gradle:3.5.3.
     Searched in the following locations:
       - https://jcenter.bintray.com/com/android/tools/build/gradle/3.5.3/gradle-3.5.3.pom
       - https://jcenter.bintray.com/com/android/tools/build/gradle/3.5.3/gradle-3.5.3.jar
     Required by:

React Native version:
0.61.5

buildscript {
    ext {
        buildToolsVersion = "29.0.2"
        minSdkVersion = 16
        compileSdkVersion = 29
        targetSdkVersion = 29
        supportLibVersion = "29.0.2"
    }
    repositories {
      mavenLocal()
      mavenCentral()
      maven {
          url 'https://maven.google.com/'
          name 'Google'
      }
      maven {
         url 'https://maven.fabric.io/public'
      }
      google()
      jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.3'
        classpath 'com.google.gms:google-services:4.3.3'  // Google Services plugin
        classpath 'io.fabric.tools:gradle:1.28.1'
    }
}

allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
        google()
        jcenter()
    }
}

wrapper {
    gradleVersion = '5.5.1'
    distributionUrl = distributionUrl.replace("bin", "all")
}

**Comment by GHOSTLORE** [comment]
same problems in china!

**Comment by wincod75** [comment]
@GHOSTLORE Check your Android Studio logs for the affected package. Somehow mine got messed up, deleted it from node modules, reinstalled, ran npx jetify and just like that it was resolved.
