### ISSUE TITLE
Security issue: fetch stores http secure cookies alongside cookies in http-cache in Android

### ISSUE THREAD

**Issue by JofBigHealth** [facebook/react-native#27897]
In [OkHTTPClientProvider](https://github.com/facebook/react-native/blob/aee88b6843cea63d6aa0b5879ad6ef9da4701846/ReactAndroid/src/main/java/com/facebook/react/modules/network/OkHttpClientProvider.java#L92), network requests along with all cookies - regardless of security settings - are persisted to the filesystem in http-cache folder. This means on some operating systems any third party application can potentially extract those cookies thus defeating the point of secure cookies.

This is a major security issue, in my opinion, because it's not acting like a browser and people would expect otherwise.

## React Native version:

0.61.5

## Steps To Reproduce

1. Create an app and call `fetch('https://n1fbe.sse.codesandbox.io/set')` (a basic express server I coded - see source [source](https://codesandbox.io/s/jovial-ptolemy-n1fbe))
2. Go to Android Studio and then "View > Tools Windows > Device File Explorer" within that window navigate to data/data/your.app.name/cache/http-cache
3. Open the cache files
4. See the two tokens are set. E.g.

```
set-cookie: nameOfCookie1=cookieValue1; Max-Age=3600; Path=/; Expires=Wed, 29 Jan 2020 11:47:41 GMT; HttpOnly; Secure
set-cookie: nameOfCookie2=cookieValue2; Max-Age=3600; Path=/; Expires=Wed, 29 Jan 2020 11:
```

![http-cache](https://user-images.githubusercontent.com/38071585/73355383-f36d3b00-428f-11ea-951e-5b227e1fb8a5.png)

## What should happen

I don't know precisely as I'm not experienced with Android security. Main point is put secure cookies anywhere safe. Just not there.

**Comment by yrezgui** [comment]
Files stored in the application directly internal storage aren't accessible by others applications: https://developer.android.com/training/data-storage (see App-specific files section)

**Comment by JofBigHealth** [comment]
Ah, thanks!

**Comment by JofBigHealth** [comment]
Closing as Yacine's nailed it. Panic over.
