### ISSUE TITLE
KeyboardAvoidingView is buggy after updating modules

### ISSUE THREAD

**Issue by Arwantys** [facebook/react-native#27896]
After performing an npm update, KeyboardAvoidingView no longer works correctly, my TextInput can no longer climb above the keyboard, I have checked several times with different versions of my application.

React Native version:
System:
    OS: macOS 10.15.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 1.27 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.12.1 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5977832
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: ^16.11.0 => 16.12.0 
    react-native: ^0.61.5 => 0.61.5 
  npmGlobalPackages:
    create-react-native-app: 2.0.2
    react-native-cli: 2.0.1
    react-native-gesture-handler: 1.4.1
    react-native-paper: 2.16.0
    react-native-reanimated: 1.2.0
    react-native-rename: 2.4.1
    react-native-scripts: 2.0.1
    react-native: 0.61.4

## Steps To Reproduce

1. Use just KeyboardAvoidingView with Flatlist and TextInput

Before npm update : https://gyazo.com/de9f9412559c9a9d1e08acd306d0b261
After npm update : https://gyazo.com/6fc4dc9d30264d2a63ca37069af6ea62

**Comment by hramos** [comment]
Can you share a code example that reproduces the issue?

**Comment by artashsanoyan** [comment]
TextInput will be hidden behind popped up keyboard. tested on both simulator and physical device. Anyway if i set the keyboardVerticalOffset manually it will work as expected.

```
import React from 'react';
import {KeyboardAvoidingView, FlatList, SafeAreaView} from 'react-native';

const DATA = [{id: 1, text: 'some text'}];

function Chat() {
  return (
    <KeyboardAvoidingView
      style={{ flex: 1 }}
      behavior='padding'>
      <SafeAreaView style={styles.fullSpace}>
        <FlatList
          keyExtractor={item => item.id}
          data={DATA}
          renderItem={({ item }) => <Text>{item.text}</Text>}
        />
      </SafeAreaView>
    </KeyboardAvoidingView>
  );
}
```

**Comment by artashsanoyan** [comment]
Why this was closed ? I'm still facing this issue, @arwantys  did you find a solution ?
