### ISSUE TITLE
SHARE My app close when I press the screen in the moment between Pressing the button that execute Share.share and the native modal appears (ONLY ANDROID))

### ISSUE THREAD

**Issue by felire** [facebook/react-native#27890]
The app is being minimized instead of open the modal. That only happen if I press in any place of the screen in the lapse between the moment I press the button to open the modal and the moment when the modal appears. If I don't click in any other place at all, this work perfectly.
This is only happening on ANDROID, in ios works fine

### Steps to reproduce
1. Write a button that execute Share.open in the onPress event
2. Run the app
3. Press the button faster and many times

### Expected behaviour
The modal should appear

### Actual behaviour
The app is being closed without errors

### Environment
- **React Native version**:  0.61.5
- **React Native platform + platform version**: All android devices

This same issue is happening also in the library `react-native-share` . I reported there too https://github.com/react-native-community/react-native-share/issues/685

**Comment by felire** [comment]
The error appear only in one of my apps. Do you have any idea what conflict could be interfering with the correct behaviour of this?

**Comment by hramos** [comment]
Can you provide a code example? It'd make it easier to follow what you're reporting here.

**Comment by felire** [comment]
@hramos I only use Share as the docs says. I have a button and in the onPress I call a function like this one:

```
handlePress = () => {
    Share.share({
        title: 'bla',
       message: 'bla'
      })
}
```
There is a conflict with my project and this library that reproduces the error I described. But really I don't know which is the reason.

**Comment by hramos** [comment]
Can you provide an example using [Snack](https://snack.expo.io/)? We find that issues that do not provide a Snack are less likely to get investigated.
