### ISSUE TITLE
ImageBackground blurRadius < 5 does not work on iOS

### ISSUE THREAD

**Issue by iqbalfaisal** [facebook/react-native#27905]
### **Description:**

blurRadius of ImageBackground isn't working on **IOS** (emulator & device) but it's working perfectly on **Android**.

### **React Native version:**

System:
    OS: Windows 10 10.0.17763
    CPU: (8) x64 Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
    Memory: 5.73 GB / 15.89 GB
  Binaries:
    Node: 11.12.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.15.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.7.0 - C:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28
      Build Tools: 23.0.1, 26.0.1, 27.0.3, 28.0.2, 28.0.3
      System Images: android-22 | Google APIs Intel x86 Atom, android-24 | Google Play 
Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 
Atom
  IDEs:
    Android Studio: Version  3.4.0.0 AI-183.5429.30.34.5452501
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.5 => 0.60.5

## Snack, code example, screenshot, or link to a repository:
```
<ImageBackground blurRadius={3} source={Img[this.Index]} />
```

**Comment by Usamaliaquat123** [comment]
You are right @iqbalfaisal. [blurRadius](https://facebook.github.io/react-native/docs/image#blurradius) isn't a property of  [ImageBackground](https://facebook.github.io/react-native/docs/imagebackground) looks like it Inherits from [ImageProps](https://facebook.github.io/react-native/docs/image#props). I saw the same issue #16780 its closed :( but it look like didn't get the better answer.

**Comment by hramos** [comment]
Reopening. Thanks for sending the docs PR. Before I look at that, I want to re-open this bug so we can perhaps get to the root of why < 5 is not working as expected on iOS. I'd rather fix this, if possible.
