### ISSUE TITLE
Could not connect to the development server - Genymotion & React-Native

### ISSUE THREAD

**Issue by diamantisufi** [facebook/react-native#27907]
## Description:
I am trying to run a react-native app. The app creates and builds without any erros. But when I try to reload to view my app's code, it gives me this error: ``Could not connect to the development server`` - Android

- I have tried multiple solutions:
1. Giving my IP adress and the port number  to the `debug server host & port for device` in the Genymotion emulator.
2.I checked if the server is on, even if on the error still displays,
3. I tried `adb reverse tcp:8081 tcp:8081`
4. I ran : `react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res`
5. Tried `android:usesCleartextTraffic="true" to AndroidManifest.xml`

.. I basically tried every solution that I saw related to this error, but I still get the error.

![err2](https://user-images.githubusercontent.com/28764471/73462261-cc8c3300-437b-11ea-93bf-ce1381bfd38a.PNG)

**React Native version:**
react-native-cli: 2.0.1
react-native: 0.61.5

## Steps To Reproduce
1.Generate a new react-native Project using react-native-cli
2.Go to the project directory, and run:
`react-native run-android`

## Expected Results

- Reload the app and show me the changes I have made.

## Snack, code example, screenshot, or link to a repository:

  Any project. I tested on a fresh new projects.

**Comment by dulmandakh** [comment]
I would recommend to use Android Emulator + HAXM, because it supports Google Play Services. I'm closing this because it's not a RN issue, but Genymotion.

**Comment by diamantisufi** [comment]
It displays the same error with Android Emulator.

**Comment by inferusvv** [comment]
Have you found to way to fix that?
