### ISSUE TITLE
Hangs on :app:installDebug, cause and solution proposal

### ISSUE THREAD

**Issue by andrejohansson** [facebook/react-native#27909]
### Description

After creating a new react-native app using react native cli and the guide on [this page](https://facebook.github.io/react-native/docs/getting-started). I could not get the app to launch on any emulated device. 

- Everything built fine
- The ``adb devices`` command showed the emulator correctly
- An emulator started nicely
- I could use ``adb install myapk.apk`` to install the app
- I googled and tried all possible solutions such as:
    - Recreating the avd
    - Cold booting the avd
    - Wiping the data
    - And many more...

Nothing worked, until I noticed a warning in the console when the emulator started:

```
ERROR: Unable to access 'C:\Users\Andr├⌐Johansson\.emulator_console_auth_token': emulator console will not work
```

Which after som more verbose logging revealed an exception:

```
Exception in thread "Device List Monitor" java.lang.NullPointerException
        at com.android.ddmlib.EmulatorConsole.checkConnection(EmulatorConsole.java:319)
        at com.android.ddmlib.EmulatorConsole.getConsole(EmulatorConsole.java:233)
        at com.android.ddmlib.DeviceMonitor.queryAvdName(DeviceMonitor.java:281)
        at com.android.ddmlib.DeviceMonitor.updateDevices(DeviceMonitor.java:254)
        at com.android.ddmlib.DeviceMonitor.access$500(DeviceMonitor.java:59)
        at com.android.ddmlib.DeviceMonitor$DeviceListUpdateListener.deviceListUpdate(DeviceMonitor.java:704)
        at com.android.ddmlib.DeviceMonitor$DeviceListMonitorTask.processIncomingDeviceData(DeviceMonitor.java:889)
        at com.android.ddmlib.DeviceMonitor$DeviceListMonitorTask.run(DeviceMonitor.java:823)
```

So, there is an issue with the emulator console not starting properly. The emulator have trouble with my username ``AndréJohansson`` because of special characters. Also, it is not respecting the environment variable ``ANDROID_EMULATOR_HOME`` for the token file (which I have set to ``E:\Android\.android``).

### React Native version

```
D:\rduce\src\pixon-app>react-native info
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.18363
    CPU: (12) x64 Intel(R) Xeon(R) E-2176M  CPU @ 2.70GHz
    Memory: 17.13 GB / 31.71 GB
  Binaries:
    Node: 10.18.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.21.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.1, 28.0.2, 28.0.3, 29.0.0, 29.0.1, 29.0.2, 29.0.3
      System Images: android-22 | Android TV Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Android TV Intel x86 Atom, android-28 | Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-29 | Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: Version  3.5.0.0 AI-191.8026.42.35.6010548
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
```

## Steps To Reproduce

1. Follow the starter guide on a Windows 10 machine with a user that have non-ascii character ``é`` in it´s username.
    
    ![image](https://user-images.githubusercontent.com/2828428/73476448-82627c00-4392-11ea-914c-9f44427a8cc6.png)

2. Run ``yarn install`` then ``yarn android``

## Expected Results

    I expect 
    - the project to build
    - metro bundler to launch
    - android emulator to launch
    - the app to be installed on the emulator
    - the app to be started on the emulator

## Workarounds/solutions
Essentially the communication between the build script and the emulator is broken. Which means that:

- Errors from the emulator wont show in your console

    - **Example** I had a build error (MainActivity was not found since I had renamed my package) it **will not show** due to the broken communication.

- Commands sent to the emulator wont work (such as "start the app")

### What to do

- Create a user account without special characters. Then fix the build errors on a computer account without special characters in the name.

- If you dont have any build errors, the app will actually still be transferred to the emulator and you can find it and launch it from within the emulator and then it will connect to metro.

# Who is stupid enough to have unicode characters in their username?

Well, actually...a lot, but not willingly. If you join a computer to an Azure Active directory you will get the username from your name and you have nothing to say about it. It´s also not possible to change the local username in a reliable manner except for adding another user manually (which can be quite a lot of work).

# Suggestions

I guess that the real problem here is the emulator not supporting the paths, but I have found a lot of people online searching for the same hangup on installDebug, therefore I post it here as it might help someone. As for the react native project goes:

 - Investigate if there is another way of communicating with the emulator?
 - Figure out if there is any possible way to configure the emulator to use another folder for the ``.emulator_console_auth_token`` file. Perhaps some environment variable?
 - Highlight this issue in the documentation, to avoid frustration from beginners.

This is posted at the [google bug tracker](https://issuetracker.google.com/issues/146753528) aswell.

**Comment by hramos** [comment]
Trust me... I feel your pain, my name is Héctor and it trips all sorts of systems. I think this might need to be addressed in the AVD emulator tool itself, but if there's anything I can do to fix this on the React Native side, I'll try to get it fixed. Please do let me know if you hear back from Google.

**Comment by andrejohansson** [comment]
I think that just a note/warning in the docs would help many beginners to avoid a lot of pain and confusion. "If you have special characters...you will be in pain". 

Cheers!
