### ISSUE TITLE
SHA-1 for file (......./pollyfills-require.js) is not computed

### ISSUE THREAD

**Issue by diamantisufi** [facebook/react-native#27903]
![error](https://user-images.githubusercontent.com/28764471/73437346-7a7fe900-434c-11ea-84c0-3d19e67fccfb.PNG)
## Description:

I'm trying to bundle index.android.bundle for getting the famous RN error:
`Unable to load script from assets ‘index.android.bundle’`

I followed all the guides that were shown into the official documentation of RN.

## React Native version:

I'm using the `latest version of react-native`. Specifically, I installed all the packages and tools yesterday.

## Steps To Reproduce
1.Generate a new react-native Project using react-native-cli
2.Remove react-native-cli and install @react-native-community/cli (old cli knows how to create new projects, new CLI does not)
3.Go to the project directory, and run:
 ``react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res``
4.Wait couple of seconds

## Expected Results
 1 `.index.android.bunlde` should finish bundling 
2. After hitting `react-native run-android`, the project should start and display in the android emulator that is active.
 

## Snack, code example, screenshot, or link to a repository:

    Any project. I tested on a fresh new project from react-native-cli.

You can find the full error attached here.

**Comment by Usamaliaquat123** [comment]
@diamantisufi  great... . [react-native-cli](https://github.com/react-native-community/cli/blob/master/packages/global-cli) its global convenience package, which is a proxy to [@react-native-community/cli](https://github.com/react-native-community/cli) ,just a global installation helper. Actually this a part of 
[Lean Core](https://github.com/facebook/react-native/issues/23313) inintiative there's an [ongoing effort](https://github.com/react-native-community/cli/issues/76) to remove this module so we can use just react-native as the only package necessary to install and run React Native commands

**Comment by diamantisufi** [comment]
@Usamaliaquat123  Yes, but when using only react-native-cli, was not able to create and run a project, a lot of suggestions were pointing to the @react-native-community/cli and with that in place the creation of the project was successful.

I think that the instructions are a little bit weird, for example the **SDK version** suggested in the official documentation is 9.0 and not the latest one 10.0. I think that a lot of developers are having issues just running their react-native projects, with more than 100K+ views on react-native errors.

**Comment by hramos** [comment]
Please post the full envinfo dump in your issue. We discourage using "latest version" and would rather prefer bug reports contain be specific about the version that is being used.

**Comment by Liqiankun** [comment]
npx react-native start

**Comment by ecemac** [comment]
I've been dealing with this issue for a long time now. I'm still looking for a permanent solution, but if you need it to work run `npx react-native start` and open the app from your emulator manually. In my case, I get this error with `react-native run-android` but it does build the app, just doesn't start it. You will need to repeat these steps if you want a new build though.
