### ISSUE TITLE
[Android][Windows] The Android App only shows a blank white screen.

### ISSUE THREAD

**Issue by BerndWessels** [facebook/react-native#2790]
Hello

If you have followed [this issue](https://github.com/facebook/react-native/issues/2780) you know already that we are close to be able to use react native with android on windows.

Can you please help us fix this "Blank App Screen" problem?

Thank you
Bernd

**Comment by hzzcc** [comment]
+1

**Comment by hzzcc** [comment]
http://www.jcodecraeer.com/a/anzhuokaifa/androidkaifa/2015/0916/3467.html
for android5.0 
react-native run-android
you should run:
adb reverse tcp:8081 tcp:8081

for android 4.0
need to open the windows permissions in the application settings

**Comment by BerndWessels** [comment]
Thank you @hzzcc .

I haven't had to the `adb reverse` thing of change any of my configurations.

The solution for me was to follow @mqli fix which you can find [here](https://gist.github.com/mqli/e1e6576e9838d885a43a).

React-Native Android development is now working on Windows with the mentioned fixes.

I hope this will make it into the official React-Native package very soon so that we will become a huge fantastic community.

I leave this issue open so that people can find this fix until it is part of the official React-Native package.

Again special thanks to @mqli

**Comment by shipengyan** [comment]
+1

**Comment by jozn** [comment]
+1

**Comment by shipengyan** [comment]
finally, I solve it in windows, haha, here it is.

![e8a52423-39f6-4b4d-a827-1c15b890758e](https://cloud.githubusercontent.com/assets/1212932/9962204/1e947810-5e57-11e5-817b-022a1dad612c.jpg)

I check all config which i can think.

1.  http://www.jcodecraeer.com/a/anzhuokaifa/androidkaifa/2015/0916/3467.html
@hzzcc  , it is usefull.

2. check firewall in windows, exclude node.exe in firewall
![9a997a9a-7516-49ad-b4ef-0e828142c2c6](https://cloud.githubusercontent.com/assets/1212932/9962263/642e3e9c-5e57-11e5-96f5-91185c614af8.png)

![77c8b601-ef41-44f3-a912-de030a2de5ad](https://cloud.githubusercontent.com/assets/1212932/9962277/716c105c-5e57-11e5-8337-114a7925206a.png)

![99ce0d54-982a-4b66-a2dd-5d5aea5eb91e](https://cloud.githubusercontent.com/assets/1212932/9962288/77b79274-5e57-11e5-9e30-7528ab12dca2.png)

![9879f40c-0a01-4959-9c20-5ac0bfcf858a](https://cloud.githubusercontent.com/assets/1212932/9962301/8a384d12-5e57-11e5-89fc-f381fd8a091f.jpg)

**Comment by tdzl2003** [comment]
This issue may related to these two pull-request: #2813 #2812
