### ISSUE TITLE
AppState.removeEventListener does not remove the event listener

### ISSUE THREAD

**Issue by masaltzman** [facebook/react-native#27911]
Description:

    Please provide a clear and concise description of what the bug is. Include screenshots if needed.
    Please test using the latest React Native release to make sure your issue has not already been fixed: http://facebook.github.io/react-native/docs/upgrading.html

React Native version:

System:
    OS: macOS 10.15.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 20.60 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.13.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 27, 28, 29
      Build Tools: 27.0.3, 28.0.2, 28.0.3, 29.0.2
      System Images: android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: ^16.12.0 => 16.12.0 
    react-native: ^0.61.5 => 0.61.5

## Steps To Reproduce

1. component adds event listener for 'change' to AppState
2. press home button to leave the app
3. event listener receives the 'change' event
4. go back to the app
5. component removes the event listener
6. press home button to leave the app
7. event listener still receives the 'change' event even though it was removed

## Expected Results

Component should not receive the 'change' event after removing the event handler from AppState
## Snack, code example, screenshot, or link to a repository:

Snack here:
https://snack.expo.io/@masaltzman/c38c13

Code here:
`
import React, { useState, Fragment, useContext, useEffect } from 'react';
import { Text, View, StyleSheet, AppState, Button } from 'react-native';
import Constants from 'expo-constants';

// You can import from local files
import AssetExample from './components/AssetExample';

// or any pure javascript modules available in npm
import { Card } from 'react-native-paper';

function appStateChangeHandler(newState) {
  console.log('AppState changed:', newState);
}

function removeListener() {
  console.log("listener removed");
  AppState.removeEventListener('change', appStateChangeHandler)
}

export default props => {
  function appStateChangeHandler(newState) {
    console.log('AppState changed:', newState);
  }

  useEffect(() => {
    console.log("listener added");
    AppState.addEventListener('change', appStateChangeHandler);
    // AppState.removeEventListener('change', appStateChangeHandler);
  }, []);

  return (
    <View style={{margin: 100}}>
      <Button title="remove" onPress={() => removeListener()}/>
    </View>
  );
};
`

**Comment by dulmandakh** [comment]
Pressing Home won't close an app, so event listeners will be called. Also you didn't removed the listener. Thanks

**Comment by masaltzman** [comment]
It tries to remove the listener when the button is pressed. That happens in the removeListener function which is attached to the button

**Comment by dulmandakh** [comment]
it looks that you have 2 appStateChangeHandler functions, and you're adding inner one to AppState and trying removing outer one, thus differ. Please remove inner one, and I hope that I'll work just fine.

**Comment by tjrrrr** [comment]
Is the removeEventListener only works on ComponentWillUnmount? 

`
this.state = {
      appState: AppState.currentState
};
componentDidMount(){
    AppState.addEventListener('change', this._handleChange);
}
_handleChange = (nextAppState) => {
    console.log('handleChange')
    if (
      this.state.appState.match(/inactive|background/) &&
      nextAppState === 'active'
    ) {
      console.log('App has come to the foreground!');
    }
    this.setState({appState: nextAppState});
};

static onExit(){
      console.log('On Exit')
      AppState.removeEventListener('change', this._handleChange);
 }
`

The handleChange is not removing with the code above. Any advise on this?

**Comment by masaltzman** [comment]
> The handleChange is not removing with the code above. Any advise on this?

_handleChange is not static, so you can't access it from within the static onExit method.

**Comment by tjrrrr** [comment]
> > The handleChange is not removing with the code above. Any advise on this?
> 
> _handleChange is not static, so you can't access it from within the static onExit method.

Any advise how to access it other than ComponentWillUnmount?

**Comment by dulmandakh** [comment]
What do you want to achieve?

**Comment by tjrrrr** [comment]
I want to remove the event listener when navigate or exit the screen. However, I would not able to remove it via ComponentWillUnmount, due to the stack <Scene> of React Native Router Flux or it's a Tab bar as a root.

**Comment by dulmandakh** [comment]
I don’t know React Native Router Flux, but there must be an event or way to handle it. BTW, I looked into React Native Router Flux web site and looks like React Navigation 5.0, which was releases just yesterday.

**Comment by PoulsQ** [comment]
Had the same issue in a class component, the `AppState.removeEventListener ` was not working.
Here is how I finally managed it: https://stackoverflow.com/questions/50565458/app-state-in-react-native-does-not-remove-the-listener/65289424#65289424
