### ISSUE TITLE
default value of declared value is true instead of undefined

### ISSUE THREAD

**Issue by IsmaelMiber** [facebook/react-native#27912]
Description:
I have a functional component that render a text and 3 squares, if the values of these squares are less than or equal zero, a variable called reduceSpace will have true value, then the text will have marginBottom: 0, unless it will have marginBottom: 49,

I have this condition in my code: 
`if(Fat <= 0 && Carbs <= 0 && Protein <= 0) {
        var reduceSpace = true;
    }`
if theses 3 values are larger than zero, the default value of reduceSpace is undefined by default, it is normal and it works in dev mode but in prod mode the default value is true of reduceSpace.
I test it in several ways, and what I get undefined in dev mode and true in prod mode.
I test it also using expo to test if my environment have an issue or not. ( I use react-native not expo but for testing this confuse behavior I test it on expo).

I fixed it by declaring the reduceSpace above the if condition like this: 
`var reduceSpace;
if(Fat <= 0 && Carbs <= 0 && Protein <= 0) {
       reduceSpace = true;
}
`
and it worked well with undefined in prod and dev mode and it what I expected.

can anyone explain why this confused behavior happened ?

React Native version:
![image](https://user-images.githubusercontent.com/16901328/73480930-77641780-43a3-11ea-9768-d4fc23069547.png)

## Steps To Reproduce
1. run the app in dev mode.
2. then you will get this text: "undefined".
3. run the app in prod mode.
4. then you will get this text: "true".

## Expected Results
result expected is undefined value in two modes (prod and dev mode)

## Snack, code example, screenshot, or link to a repository:
https://snack.expo.io/@ismaelmiber/b6e070

Prod Mode:
![image](https://user-images.githubusercontent.com/16901328/73485678-3ae8e980-43ac-11ea-9328-dec5948fb8a4.png)

Dev Mode:
![image](https://user-images.githubusercontent.com/16901328/73485695-44725180-43ac-11ea-8682-5fcc0154a690.png)

**Comment by dulmandakh** [comment]
I'm not sure about what the cause is but I would use below

```js
var reduceSpace = Fat <= 0 && Carbs <= 0 && Protein <= 0
```
