### ISSUE TITLE
Frequently losing debugging access while on latest RN version

### ISSUE THREAD

**Issue by bobber205** [facebook/react-native#27913]
I've been using RN for about a year now and I love it.

In the last couple months however I am frequently losing access to the debugging tools. Debugger statements stop workin and console logs no longer work. Sometimes I'll see older console logs but any new ones stop working.

Really annoying! The only way I know how to fix it is to quit the Simulator, run `yarn start --reset-cache` and recompile from scratch. I have to do this several times a day.

This is the error I start seeing in the console where `yarn start` is running. Once this happens a few times there's no hope and I have to do the above steps

```
Error: Unable to resolve module `./debugger-ui/debuggerWorker.d9da4ed7` from ``:

None of these files exist:
  * debugger-ui/debuggerWorker.d9da4ed7(.native|.native.js|.js|.native.json|.json|.native.ts|.ts|.native.tsx|.tsx)
  * debugger-ui/debuggerWorker.d9da4ed7/index(.native|.native.js|.js|.native.json|.json|.native.ts|.ts|.native.tsx|.tsx)
    at ModuleResolver.resolveDependency (/Users/myname/mycompany/myapp/node_modules/react-native/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:163:15)
    at ResolutionRequest.resolveDependency (/Users/myname/mycompany/myapp/node_modules/react-native/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (/Users/myname/mycompany/myapp/node_modules/react-native/node_modules/metro/src/node-haste/DependencyGraph.js:282:16)
    at /Users/myname/mycompany/myapp/node_modules/react-native/node_modules/metro/src/lib/transformHelpers.js:267:42
    at /Users/myname/mycompany/myapp/node_modules/react-native/node_modules/metro/src/Server.js:1305:37
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/myname/mycompany/myapp/node_modules/react-native/node_modules/metro/src/Server.js:99:24)
    at _next (/Users/myname/mycompany/myapp/node_modules/react-native/node_modules/metro/src/Server.js:119:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
::1 - - [30/Jan/2020:20:30:27 +0000] "POST /symbolicate HTTP/1.1" 500 - "-" "myapp/8 CFNetwork/1121.2.1 Darwin/19.0.0"
```

React Native version:
```
System:
    OS: macOS 10.15.1
    CPU: (4) x64 Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz
    Memory: 26.24 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - /var/folders/11/4dsnq9p12xx9s0lt7l20fbfh0000gq/T/yarn--1580416524443-0.8441704962126151/node
    Yarn: 1.21.1 - /var/folders/11/4dsnq9p12xx9s0lt7l20fbfh0000gq/T/yarn--1580416524443-0.8441704962126151/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 26, 27, 28
      Build Tools: 26.0.2, 27.0.3, 28.0.3
      System Images: android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    @react-native-community/cli: ^2.7.0 => 2.10.0
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
```

**Comment by rarira** [comment]
exactly same error.. can't develop..
---
```
System:
    OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz
    Memory: 1.84 GB / 32.00 GB
    Shell: 5.7.1 - /usr/local/bin/zsh
  Binaries:
    Node: 12.14.0 - /var/folders/_2/d03ksn01075b5vm8k7hwplf00000gn/T/yarn--1580580896909-0.02626580486109087/node
    Yarn: 1.19.1 - /var/folders/_2/d03ksn01075b5vm8k7hwplf00000gn/T/yarn--1580580896909-0.02626580486109087/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 18, 23, 24, 25, 27, 28, 29
      Build Tools: 23.0.1, 25.0.0, 25.0.2, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.2, 28.0.3
      System Images: android-18 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-24 | Google APIs Intel x86 Atom_64, android-24 | Google Play Intel x86 Atom, android-25 | Google APIs Intel x86 Atom_64, android-25 | Google Play Intel x86 Atom, android-26 | Google APIs Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom_64, android-Q | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: ^0.61.5 => 0.61.5
```

**Comment by bobber205** [comment]
This is becoming a huge issue -- wasting tons of time trying to work around it.

Almost everyday after about an hour or so of development I lose all access to the debugger.

```
Error: Unable to resolve module `./debugger-ui/debuggerWorker.d9da4ed7` from ``:
```

Can this please be prioritized or have some input from the react native team? I never saw this before 0.61.5

**Comment by bobber205** [comment]
Not having proper debugging support or it constantly "going away" is pure torture.

**Comment by bobber205** [comment]
Some more info -- I see this in my connected debugging window in Chrome's console in lieu of a stacktrace.
```
Unable to symbolicate stack trace: The stack is null
```

**Comment by ebaynaud** [comment]
Duplicates of #27765 ?
Check this solution: https://github.com/facebook/react-native/issues/27765#issuecomment-575271936

**Comment by bobber205** [comment]
@ebaynaud That "occasionally" will work. Nowhere near consistent enough to be considered a solution that's for sure.

**Comment by bobber205** [comment]
Doing a daily checkin on this issue that's costing me about 10 hours a week of frustrating.
I've tried everything I can think of.

1) Run `yarn star/npm start`with and without clearing the cache.
2) Deleting app off the simulator and rebuilding dev from scratch.
3) Doing the above with debugging in the chrome tab enabled and disabled in each variation.

Still happens 90% of the time I hit an exception.

```
Error: Unable to resolve module `./debugger-ui/debuggerWorker.d9da4ed7` from ``:
```

This desperately needs to be prioritized.

**Comment by bobber205** [comment]
Tried using `npm start` vs running it with yarn because I noticed some people mentioning it's due to a npm version issue.

I also tried having the Chrome debugging window in it's own tab and with other tabs in the same window. No difference.

FWIW the crux of the issue the lack of a stack trace in the debugging window. Generally console logs and debugger statements work (a high enough % to not be an issue, nothing's perfect of course). Not being able to see anything resembling a stack trace in the browser or even the console is what's at play here.

**Comment by bobber205** [comment]
Hey @ebaynaud if you are still suffering with this I've resorted to turn on https://app.bugsnag.com/ for local development. Works great with a RN app and debugging odd issues you'd normally use a stacktrace for. <3 Good luck!

**Comment by dmitryshelomanov** [comment]
+1

**Comment by dmitryshelomanov** [comment]
Maybe this was because you has cycle dependencies

**Comment by kurtb** [comment]
I ran into this issue as well but it was a red herring for me.

I believe the "Unable to resolve module" is actually coming from missing source map files in the debugger-ui package for the debuggerWorker.d9da4ed7.js file. When I add some fake ones side by side the error goes away.

My issue was that `onPress` handlers weren't firing for `TouchableOpacity` components when the debugger was attached.

I'm debugging an Android app in the emulator. It looks like there's a timing issue when detecting a press vs. a long press. When in the debugger all of my presses look like long presses.

I imagine whatever overhead exists to proxy to Chrome exceeds the long press threshold. When I put a breakpoint on `onPressIn` I somehow fix the timing issue - I imagine because I delay the timer being registered by not the press events on the wire. I imagine if I tweak the long press delay things will work as well.

Not sure if this is what other people are running in to. But for me the debugger is actually fine I just managed to hit a react-native bug that combined with that error made it look otherwise.

**Comment by flache** [comment]
Manually setting the cli-debugger-ui version in package.json solved it for me, as described here https://github.com/react-native-community/cli/issues/1081#issuecomment-614223917

**Comment by chrisglein** [comment]
Many potential mitigations suggested here, but silence from the original filer for awhile. Not sure if you've had any luck @bobber205 with any of those. Try them out and/or update and report back?

**Comment by HenriqueDerosa** [comment]
I am facing the same issue with onPress, it doesn't work anymore. Weird that if I create a new TouchableOpacity, it is firing the event at first time, but never again.

I'm using RN 0.62.2, It's not an older version as github-actions bot said above. 🤔 
```
❯ react-native info                                        
info Fetching system and libraries information...
System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 275.14 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.7.0 - ~/.nvm/versions/node/v13.7.0/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.6 - ~/.nvm/versions/node/v13.7.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 27, 28
      Build Tools: 27.0.3, 28.0.3
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_231 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found
```
