### ISSUE TITLE
[0.62.0-rc.1] Vibration.vibrate has unspecified nullability on iOS

### ISSUE THREAD

**Issue by trevyn** [facebook/react-native#27920]
Description:

- Vibration.vibrate() errors on iOS on 0.62.0-rc.1. Looks like something to do with TurboModules.

- Error: **Argument 0 (NSNumber) of Vibration.vibrate has unspecified nullability but React requires that all NSNumber arguments are explicitly marked as 'nonnull' to ensure compatibility with Android.**

React Native version:

```
System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz
    Memory: 1014.98 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 13.6.0 - /usr/local/bin/node
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.0-rc.1 => 0.62.0-rc.1 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

## Steps To Reproduce

    Vibration.vibrate(1);

## Expected Results

Error-free vibration.

**Comment by hramos** [comment]
According to the docs, specifying a duration in `vibrate(duration)` on iOS should have no effect. Can you remove the argument and see if that solves the error?

Even in that case, I think this could be handled better. I'll flag this with the team.

**Comment by trevyn** [comment]
@hramos Correct that the value of the duration parameter is ignored on iOS, but the docs also say that it is required. And indeed, calling without any arguments rightfully complains about the lack of arguments.

The docs also make it sound like vibrate(Array) should have a meaning on iOS, but it looks completely unimplemented. No idea if this is a regression or not.

**Comment by hramos** [comment]
I'm looking at RNTester, in Vibration example, where I added an example that calls `Vibration.vibrate(3)`. I couldn't get an error to show up. No red screen, nothing in the Xcode console. Where are you seeing the error? If I can repro this, I might be able to fix the spec.

Docs do seem out of date as RCTVibration shows vibration by pattern is not implemented on iOS.

**Comment by brunobar79** [comment]
@hramos  I can reproduce  on v0.62 rc1  and it doesn't matter if I call it with a number as a param or without parameter, which makes sense because of it's being called without params for iOS [here](https://github.com/facebook/react-native/blob/master/Libraries/Vibration/Vibration.js#L89)

![IMG_3758](https://user-images.githubusercontent.com/1247834/73802172-c981b000-478a-11ea-9dba-59795c47b2f7.PNG)

@trevyn  is right about this being related to TurboModules. The problem is that numbers are not supported as nullable arguments in functions,

Just submitted a PR to fix the issue: https://github.com/facebook/react-native/pull/27951

**Comment by dsernst** [comment]
Still seeing this in `react-native@0.62.0` in iOS.

### To reproduce on a fresh build:

```jsx
import React from 'react'
import { Vibration, Button } from 'react-native'

const Example = () => <Button onPress={() => Vibration.vibrate()} title="Push me to crash" />
)
```

### Results in:
<img src="https://user-images.githubusercontent.com/6340841/78106874-34292380-73a9-11ea-8146-9204be9b2850.png" width="300px" />

### Expected:

Would expect this simple `Vibration.vibrate()` call to work, per [the first example from the docs](https://github.com/facebook/react-native-website/blame/6632be52597665f9253afa2663329973858375e0/docs/vibration.md#L50).

-----

Looks like the suggested PR (https://github.com/facebook/react-native/pull/27951) has status `Waiting on Facebook`?

Is there anything we can do to help? 🙂

**Comment by mateusmirandaalmeida** [comment]
Mesmo problema aqui
