### ISSUE TITLE
Fatal Exception: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/com.asda.android/lib-main/libgnustl_shared.so" is 32-bit instead of 64-bit

### ISSUE THREAD

**Issue by kgoedert** [facebook/react-native#27921]
Hi,

I am having the exception mentioned in the title. 

Fatal Exception: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/com.asda.android/lib-main/libgnustl_shared.so" is 32-bit instead of 64-bit.

I tried every suggestion I could find on the internet, especially the ones pointed here. https://github.com/facebook/react-native/issues/18599#issuecomment-520712334

When the app works on a physical device with android 10, it is not accepted by play store. When I try the suggestions that make it work on the playstore, they don't work on the device.

I tried every version of react-native from 0.57.1 to 0.59.1 

What should I do to make it be accepted on the device, and work on my phone when I download it.

**Comment by dulmandakh** [comment]
It looks like this might be caused by a third-party module.
