### ISSUE TITLE
Android TV Touchables onPress fires three time

### ISSUE THREAD

**Issue by aalbaharnah** [facebook/react-native#27937]
Description:
when using TouchableWithoutFeedback, TouchableHighlight, TouchableOpacity or TouchableNativeFeedback. `onPress` will be executed three time when pressing the "select" button on the TV remote.

React Native version:
```
    OS: macOS 10.15.2
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Memory: 8.95 GB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: 1.19.0 - /usr/local/bin/yarn
    npm: 6.13.6 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.4 AI-183.5429.30.34.5452501
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: ~16.9.0 => 16.9.0 
    react-native: ~0.61.4 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

## Steps To Reproduce

1. create new react-native application 
2. apply Build changes for Android TV devices
3. add a Touchable to your application

## Expected Results

pressing the "select" button on the TV remote once, onPress should be fired one time only.

## Snack, code example, screenshot, or link to a repository:

```
import React, { Component } from 'react';
import { StyleSheet, Text, View, TouchableOpacity } from 'react-native';

export default class App extends Component {
  state = {
    count: 0
  }
  render() {
    return (
      <View style={styles.container}>
        <Text>{this.state.count}</Text>
        <TouchableOpacity onPress={() => this.setState({ count: this.state.count + 1 })}>
          <Text style={styles.text}>Remote Controll Press</Text>
        </TouchableOpacity>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  text: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
});
```

**Comment by GeekLime** [comment]
same issue here

**Comment by StevenB45** [comment]
Same here! Worked on 0.59.10...

**Comment by MwareSolutons** [comment]
Same here to Worked on 0.59.5 not on 61.5

**Comment by ChrisCodeCole** [comment]
Having the same issue on Amazon FireStick 3rd gen..just tried upgrading to the latest stable version (RN 0.62.2) without any success. Same issue was on my previous version RN 0.61.2 also.

**Comment by aalbaharnah** [comment]
I was able to fix this issue doing this issue by modify this Touchable component.
at  APP_ROOT/node_modules/react-native/Libraries/Components/Touchable/Touchable.js

add `&& Platform.OS !== 'android'` 
`componentDidMount` method should be looking like this:

```
componentDidMount: function () {
    if (!Platform.isTV) {
      return;
    }

    this._tvEventHandler = new TVEventHandler();
    this._tvEventHandler.enable(this, function (cmp, evt) {
      const myTag = ReactNative.findNodeHandle(cmp);
      evt.dispatchConfig = {};
      if (myTag === evt.tag) {
        if (evt.eventType === 'focus') {
          cmp.touchableHandleFocus(evt);
        } else if (evt.eventType === 'blur') {
          cmp.touchableHandleBlur(evt);
        } else if (evt.eventType === 'select' && Platform.OS !== 'android') {
          cmp.touchableHandlePress &&
            !cmp.props.disabled &&
            cmp.touchableHandlePress(evt);
        }
      }
    });
  }
```

**Comment by nklhrstv** [comment]
@aalbaharnah i dont see any difference between your componentDidMount and the one in RN.
Where do you add `&& Platform.OS !== 'android'`?

**Comment by daominhsangvn** [comment]
@nklhrstv  try this https://github.com/facebook/react-native/issues/25979#issuecomment-575564756
It's working for me

**Comment by yvbeek** [comment]
Can we reopen this issue?

This still happens on React-Native 0.63.3 + Android TV.
For example, when you press enter in the emulator, it fires the onPress event three times.

**Comment by safaiyeh** [comment]
@yvbeek just to clarify this happens on Android as well?

If it is just Android TV, future development has been moved to https://github.com/react-native-tvos/react-native-tvos

The issue is a bit dated, if it still happens on Android could you open a new issue with the template filled out.

**Comment by yvbeek** [comment]
@safaiyeh Thank you for your reply.
Isn't the `react-native-tvos` library only for Apple TV? Not for Android TV?

This ticket was labeled as (Apple's) `tvOS`, but it is about `Android TV`
I can open a new ticket, it looks like the issue was never properly resolved.

**Comment by safaiyeh** [comment]
It's for both. Yeah the language on the repo doesn't really mention AndroidTV I'll ask them about it

**Comment by MwareSolutons** [comment]
if you are on 63.4 the solution is to delete this from APP_ROOT/node_modules/react-native/Libraries/Components/Touchable/Touchable.js

its cause there is a tvtouchable.js in the same folder

delete: 

   this._tvEventHandler = new TVEventHandler();
    this._tvEventHandler.enable(this, function (cmp, evt) {
      const myTag = ReactNative.findNodeHandle(cmp);
      evt.dispatchConfig = {};
      if (myTag === evt.tag) {
        if (evt.eventType === 'focus') {
          cmp.touchableHandleFocus(evt);
        } else if (evt.eventType === 'blur') {
          cmp.touchableHandleBlur(evt);
        } else if (evt.eventType === 'select' && Platform.OS !== 'android') {
          cmp.touchableHandlePress &&
            !cmp.props.disabled &&
            cmp.touchableHandlePress(evt);
        }
      }
    });
