### ISSUE TITLE
Add TODOs Badge to README

### ISSUE THREAD

**Issue by patrickdevivo** [facebook/react-native#27931]
Hi there! I wanted to propose adding the following badge to the README to indicate how many `// TODO` comments are in this codebase:

[![TODOs](https://img.shields.io/endpoint?url=https://todos.tickgit.com/badge?repo=github.com/facebook/react-native)](https://todos.tickgit.com/browse?repo=github.com/facebook/react-native)

The badge links to `tickgit.com` which is a free service that indexes and displays TODO comments in public github repos. It can help surface latent work and be a way for new contributors to find areas of code to improve.

The markdown is:

```
[![TODOs](https://img.shields.io/endpoint?url=https://todos.tickgit.com/badge?repo=github.com/facebook/react-native)](https://todos.tickgit.com/browse?repo=github.com/facebook/react-native)
```

Thanks for considering, feel free to close this issue if it's not appropriate or you prefer not to!

**Comment by hramos** [comment]
Hey Patrick! Thanks for the suggestion. This sounds like a nice way of directing folks to areas of the codebase that need help. We've been using the "Good first issue" label, but it's nice to have an automated alternative. 

One concern I have with this approach is that it might not mesh well with the way we use TODOs at Facebook. Every TODO in the codebase should be linked to an internal task on the internal Facebook task tracker used by Facebook employees, and these tasks are not publicly visible to external folks. I'm afraid this might lead to frustration if the TODO comment does not provide all the necessary context (ideally, the comment explains what needs to be done, and the task is just an artifact for keeping track internally of these).

We are working on increasing transparency around the work we do with React Native. Ensuring these TODOs have the necessary context is one way. May I suggest you open a discussion at https://github.com/react-native-community/discussions-and-proposals? It's a better place to talk about this, as we use the core repo to track bugs.

**Comment by patrickdevivo** [comment]
Thank you for the comment @hramos! I understand the concern and appreciate your consideration and explanation of how TODOs are handled at Facebook. Very illuminating! I'd be happy to move the discussion to the repo you linked, and am curious to know more about TODO habits at FB (is there any public documentation/mention by chance?)

My hope is that tickgit can grow into a more robust project management tool that helps bridge the gap between `// TODO` and ticket, for small and large projects. There are a couple of features in the works to make the index UI more actionable (card view, button to create Github issue from TODO, etc). I'd like to parse out links/references to other ticketing systems from a TODO comment, to make the back-and-forth a little easier as well.

Anyways, thank you for considering the badge, and if there's a more appropriate place in this repo for it, please let me know! If it's not useful as a way of surfacing "Good first issues," perhaps it's just interesting to make more accessible! Either way, thanks again
