### ISSUE TITLE
Error when I import a valid object: "TypeError: undefined is not an object" 

### ISSUE THREAD

**Issue by BravenxX** [facebook/react-native#27936]
Description:

When I import a valid Object, and I use its values react-native gives me an error (only when I Reload manually, if auto-reload is used its all ok). 

React Native version:

   "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "react-native": "^0.61.5",
 "@babel/core": "^7.8.3",
    "@babel/runtime": "^7.8.3",

E.g. With the code below gets me this error because the console.log(...).  :

"TypeError: undefined is not an object (evaluating '_index2.default')

But when I remove that line and write it after then when hot reload, console.log(...) gets me the correct value => Metric Color #ffffff and the error doesn't appear.

Metric.js:

```
import { Color } from "../../index";
import { heightPercentageToDP as hp } from "react-native-responsive-screen";

console.log("Metric Color", Color?.surface?.normal);
export default {
  surface: {
    margin: {
      bottom: hp(1)
    },
    padding: {},
    color: {
      // normal: Color.surface.normal
      //  dark: Color.surface.dark
    },
    style: {},
    font: {
      size: {
        title: hp(2.4),
        subtitle: hp(2),
        description: hp(1.7),
        anotation: hp(1)
      },
      color: {
        //   onNormal: Color.surface.onNormal,
        //  onDark: Color.surface.onDark
      },
      style: {}
    }
  }
};
```

index.js
`export { default as Color } from "./colors/index";`

colors/index.js: 
```
export default {
  ...
  surface: {
    normal: "#ffffff",
    dark: "#E3F2FD",

    onNormal: "#014C84",
    onDark: "#002557"
  }
  ...
};
```

**Comment by farshed** [comment]
Have you tried importing it as a default export?

`import Colors from '../../index'`;
