### ISSUE TITLE
QuestionCall the function in react natively from other javascript files? 

### ISSUE THREAD

**Issue by monepa** [facebook/react-native#27933]
Hi, I'm new to react native, can I call a function (ex. to save data into realm database) in app.js or index.js from another javascript file, for example I want to call the savedata(name, country) function from myapp.js as follows :

`//myapp.js`
`var name = 'John';`
`var country = 'Indonesia';`
`savedata(name, country);`

Thanks for helping me.

**Comment by Usamaliaquat123** [comment]
`export` and `import` that func into `app.js`

**Comment by monepa** [comment]
thanks @Usamaliaquat123 that's what i need..
