### ISSUE TITLE
[Android] Multiple bouncycastle jars thwart building demo Android project

### ISSUE THREAD

**Issue by smallsaucepan** [facebook/react-native#2793]
Hi all.

Having problems getting the Android demo in the [Getting Started](http://facebook.github.io/react-native/docs/getting-started.html) running. During `react-native run-android` gradle installs two different versions of bcprov-jdk15on into ~/.gradle/

    ~/.gradle/caches/modules-2/files-2.1/org.bouncycastle/bcprov-jdk15on/1.48/960dea7c9181ba0b17e8bab0c06a43f0a5f04e65/bcprov-jdk15on-1.48.jar
    ~/.gradle/wrapper/dists/gradle-2.4-all/6r4uqcc6ovnq6ac6s0txzcpc0/gradle-2.4/lib/plugins/bcprov-jdk15on-1.51.jar

Which causes :app:packageDebug to fail with:

    class org.bouncycastle.asn1.ASN1Primitive overrides final method equals.(Ljava/lang/Object;)Z

The 1.51 version seems to come from gradle itself (gradle-2.4-all.zip) and the older and problematic 1.48 from [com.android.tools.build:builder:1.3.0](http://mvnrepository.com/artifact/com.android.tools.build/builder/1.3.0)

Have attempted to work from as clean an environment as possible e.g. old jars, jdks. For starters, could someone please confirm whether there should be two variants of bcprov downloaded to the gradle cache?

Many thanks
James

**Comment by ide** [comment]
I have multiple copies of bcprov:
```
.gradle$ find . -type f -name 'bcprov-*'
./caches/modules-2/files-2.1/org.bouncycastle/bcprov-jdk15on/1.48/3824866f059053c43b118eb5a067ea1800d8c913/bcprov-jdk15on-1.48-sources.jar
./caches/modules-2/files-2.1/org.bouncycastle/bcprov-jdk15on/1.48/645352132b8d239bcc737c3c164f435af97cd9bb/bcprov-jdk15on-1.48.pom
./caches/modules-2/files-2.1/org.bouncycastle/bcprov-jdk15on/1.48/960dea7c9181ba0b17e8bab0c06a43f0a5f04e65/bcprov-jdk15on-1.48.jar
./wrapper/dists/gradle-1.12-all/2apkk7d25miauqf1pdjp1bm0uo/gradle-1.12/lib/plugins/bcprov-jdk15-1.46.jar
./wrapper/dists/gradle-2.2.1-all/c64ydeuardnfqctvr1gm30w53/gradle-2.2.1/lib/plugins/bcprov-jdk15-1.46.jar
./wrapper/dists/gradle-2.3-bin/a48v6zq5mdp1uyn9rwlj56945/gradle-2.3/lib/plugins/bcprov-jdk15on-1.51.jar
./wrapper/dists/gradle-2.4-all/6r4uqcc6ovnq6ac6s0txzcpc0/gradle-2.4/lib/plugins/bcprov-jdk15on-1.51.jar
./wrapper/dists/gradle-2.6-all/2j4sg4877lcsg31diboouhun8/gradle-2.6/lib/plugins/bcprov-jdk15on-1.51.jar
```

cc @kmagiera @mkonicek

**Comment by smallsaucepan** [comment]
Thanks @ide. Investigated further, with some debugging of where org.bouncycastle.asn1.ASN1Object parent class was being loaded from. I'd erroneously thought renaming an old jar was enough to take it out of the picture. Turns out the class above was still being loaded from `/Library/Java/Extensions/bcmail-jdk15-143.jar.DISABLED`.  Moved it to another directory entirely, and it's happy days.

My bad. Thanks for your help!

**Comment by mkonicek** [comment]
OK, glad it works now!

**Comment by mkonicek** [comment]
For reference:

    $ find ~/.gradle -path "*bcprov-*.jar"
    ./caches/modules-2/files-2.1/org.bouncycastle/bcprov-jdk15on/1.48/960dea7c9181ba0b17e8bab0c06a43f0a5f04e65/bcprov-jdk15on-1.48.jar
    ./wrapper/dists/gradle-2.2.1-all/6dibv5rcnnqlfbq9klf8imrndn/gradle-2.2.1/lib/plugins/bcprov-jdk15-1.46.jar
    ./wrapper/dists/gradle-2.2.1-all/c64ydeuardnfqctvr1gm30w53/gradle-2.2.1/lib/plugins/bcprov-jdk15-1.46.jar
    ./wrapper/dists/gradle-2.3-bin/a48v6zq5mdp1uyn9rwlj56945/gradle-2.3/lib/plugins/bcprov-jdk15on-1.51.jar
    ./wrapper/dists/gradle-2.4-all/6r4uqcc6ovnq6ac6s0txzcpc0/gradle-2.4/lib/plugins/bcprov-jdk15on-1.51.jar
