### ISSUE TITLE
Question: auto height

### ISSUE THREAD

**Issue by sharifashraful** [facebook/react-native#27944]
Help pls,
how to set auto height of parent view. i have a native ad UI implemented by java.  code something like
<AdsView 
          style={{width:'100%'}}
 />

problem is ad does not display for height issue. when i manually add height:350 in style that time ad displayed.

question is how to set auto height in this case...

my java code 
`public class NativeAdView extends FrameLayout {

@Override
    public void requestLayout() {
        super.requestLayout();

        // The spinner relies on a measure + layout pass happening after it calls requestLayout().
        // Without this, the widget never actually changes the selection and doesn't call the
        // appropriate listeners. Since we override onLayout in our ViewGroups, a layout pass never
        // happens after a call to requestLayout, so we simulate one here.
        post(measureAndLayout);
    }

    private final Runnable measureAndLayout = new Runnable() {
        @Override
        public void run() {
            measure(MeasureSpec.makeMeasureSpec(getWidth(), MeasureSpec.EXACTLY),
                   MeasureSpec.makeMeasureSpec(getHeight(), MeasureSpec.EXACTLY));
            layout(getLeft(), getTop(), getRight(), getBottom());
        }
    };

private void refreshAd(NativeAdView v) {
        
        if (TextUtils.isEmpty(admobAdUnitId)) {
            admobAdUnitId = ADMOB_AD_UNIT_ID;
        } else {
            Log.d(TAG, "admobAdUnitId is not null");
        }
        AdLoader.Builder builder = new AdLoader.Builder(getContext(), admobAdUnitId);

        builder.forUnifiedNativeAd(new UnifiedNativeAd.OnUnifiedNativeAdLoadedListener() {
            @Override
            public void onUnifiedNativeAdLoaded(UnifiedNativeAd _unifiedNativeAd) {
                if (_unifiedNativeAd != null) {
                    // You must call destroy on old ads when you are done with them,
                    // otherwise you will have a memory leak.
                    if (_nativeAd != null) {
                        _nativeAd.destroy();
                    }
                    _nativeAd = _unifiedNativeAd;
                    LayoutInflater layoutInflater = LayoutInflater.from(__context);
                    View viewRoot = layoutInflater.inflate(R.layout.ad_unified, null);
                    //if(unifiedNativeAdView!=null) {
                        // unifiedNativeAdView.removeAllViews();
                        // v.removeAllViews();
                    //}
                    unifiedNativeAdView = (UnifiedNativeAdView)viewRoot;//(UnifiedNativeAdView) viewRoot.findViewById(R.id.unified_ad_view);
                    //v.addView(unifiedNativeAdView);
                    populateUnifiedNativeAdView(_unifiedNativeAd);
                    v.removeAllViews();
                    v.addView(viewRoot);
                    Log.d(TAG, v.getMeasuredHeight () + " " + unifiedNativeAdView.getMeasuredHeight());
                    // v.requestLayout();
                    // printNativeInfo(_unifiedNativeAd);
                }
                sendEvent(AdsViewManager.EVENT_UNIFIED_NATIVE_AD_LOADED, null);
            }
        });
.....................
.........................

}`

**Comment by farshed** [comment]
Have you tried using flexbox? Alternatively, you can use the [Dimensions](https://facebook.github.io/react-native/docs/dimensions) api to get the device height and then size your component accordingly. Something like this,

```
import { Dimensions } from 'react-native';

const ScreenHeight = Dimensions.get('window').height;

<AdsView
style={{ height: ScreenHeight }}
/>
```

**Comment by sharifashraful** [comment]
I dont know native ad height. it may be 350 , 330 or something else. in that case how to handle height in react native end.
