### ISSUE TITLE
Unexpected token '?' 

### ISSUE THREAD

**Issue by martinfpas** [facebook/react-native#27940]
hi, im new in react-native, and i'm trying to run a project in my physical device using expo. I  attached the error image.

![Screenshot_20200203-152757_Expo](https://user-images.githubusercontent.com/5508133/73689962-2fe4d080-46ae-11ea-828e-4e087c6fadc7.jpg)

This is my enviroment:

info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.17763
    CPU: (8) x64 Intel(R) Core(TM) i7-4771 CPU @ 3.50GHz
    Memory: 912.48 MB / 7.67 GB
  Binaries:
    Node: 8.11.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.13.7 - C:\Users\martin\AppData\Roaming\npm\npm.CMD
  IDEs:
    Android Studio: Version  3.5.0.0 AI-191.8026.42.35.6010548
  npmPackages:
    react: 16.8.3 => 16.8.3
    react-native: 0.61.4 => 0.61.4

Expo::  v: 3.11.7

Any ideas?

**Comment by farshed** [comment]
Looks like you might have a typo somewhere in your code. Most likely, a question mark (as the error message indicates).
