### ISSUE TITLE
Application Getting Crashed on Android 8 and below while using "defaultSource" props

### ISSUE THREAD

**Issue by ghost** [facebook/react-native#27942]
Description:

while using Image Property "defaultSource", the application is getting crash.
Works fine on android 9 and above.
Also in IOS the prop works fine. 

React Native version:

    react-native: 0.61.5 => 0.61.5

## Steps To Reproduce

    <Image
                                    source={'./abcd.png'}
                                    style={{ height: xxx, width: xxx }}
                                    resizeMode={'cover'}
                                    defaultSource={require('./image.jpg')}
                                />

## Expected Results

    Works smoother like performing in android 9 and above

**Comment by iqbalfaisal** [comment]
Kindly read docs

https://facebook.github.io/react-native/docs/image#defaultsource

**Comment by ijazahameds** [comment]
> Kindly read docs
> 
> https://facebook.github.io/react-native/docs/image#defaultsource

It says `Note: On Android, the default source prop is ignored on debug builds.` but nothing about a crash. I got crash on release build.

**Comment by iqbalfaisal** [comment]
@ijazahameds  did follow the instructions that's how to add source path?

**Comment by ijazahameds** [comment]
@iqbalfaisal Yes

**Comment by happy32x** [comment]
// `defaultSource` doesn't work on android...
//Please follow the method bellow to fix it:
//Dont forget to import View, ImageBackground, & Image

```
class MyComponent extends Component {
  constructor() {
    this.state = {
      isImageLoading: true,
    }
  }

  render() {
    <View>
      <ImageBackground
        source={{ uri: this.state.isImageLoading ? YOUR_DEFAULT_IMAGE : null }}          
      >
        <Image
          source={{ uri: YOUR_IMAGE }}
          onLoad={() => this.setState({ isImageLoading: false })}
        />                
      </ImageBackground>
    </View>
  }
}
```

**Comment by kelset** [comment]
Hello there 👋 this issue seems to have been inactive for the past few months. Because of this, it's likely that the issue is not a high priority anymore or it has been solved by OP; for these reasons, we'll close it.

But please, if it's actually still an issue with latest (RN64 at the time of writing) please comment below and we can reopen it or please send a Pull Request with a fix 😊
