### ISSUE TITLE
TextInput select and edit menu labels don't follow system locale on iOS

### ISSUE THREAD

**Issue by jsamr** [facebook/react-native#27941]
Description:

`TextInput` edit menu labels remain in English ignoring system locale on iOS. The issue has been reproduced on iOS 12.4 and 13.3.

![ios](https://user-images.githubusercontent.com/3646758/73698499-0e8ce000-46c0-11ea-9498-ee2a1923a2a1.png)

React Native version:

System:
    OS: Linux 5.3 Manjaro Linux undefined
    CPU: (8) x64 Intel(R) Core(TM) i7-8809G CPU @ 3.10GHz
    Memory: 2.01 GB / 31.29 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.5.0 - /usr/bin/node
    Yarn: 1.21.1 - ~/.node_modules/bin/yarn
    npm: 6.13.4 - /usr/bin/npm
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5

## Steps To Reproduce

Prerequisite: set the system locale to a different locale from English.

1. In a TextInput component, type some text.
2. Select text that was previously typed.
3. An select menu appears with labels in English.
4. Press "Select All"
5. An edit menu appears

## Expected Results

The select and edit menus labels should be translated to system locale language.

## Snack, code example, screenshot, or link to a repository:

https://github.com/jsamr/react-native-ios-textinput-locale-bug

**Comment by jsamr** [comment]
Has anyone been able to reproduce on latest RN version?

**Comment by jsamr** [comment]
Dear stale bot, this issue is still relevant.

**Comment by s123121** [comment]
I am having this issue now on one of my app.

**Comment by jsamr** [comment]
@amarlette Do you think this issue would be a good candidate for the GAAD pledge since it causes important usability issues for non-English speakers?

**Comment by amarlette** [comment]
Thank you for bringing this to my attention! Let me ask some folks who know a bit more about iOS behaviors.

**Comment by blavalla** [comment]
@jsamr, I think the issue here is actually at your XCode project level, and not specific to React Native.  

In the example project you linked the only languages set in the project file are english.

Here's a screenshot showing the view where you add languages to support in your app.

![Screen Shot 2021-06-21 at 3 21 07 PM](https://user-images.githubusercontent.com/1518064/122834908-5bb52600-d2a4-11eb-94b4-ce9a3c7beffe.png)

**Comment by jsamr** [comment]
@blavalla You're right! Good catch. Don't know how I missed this SO when I reported https://stackoverflow.com/a/11282184/2779871

Thanks for your insight. I'm closing now
