### ISSUE TITLE
[SectionList] Unhandled JS Exception: Invariant Violation: scrollToIndex out of range: requested index 0 but maximum is -1

### ISSUE THREAD

**Issue by djhr** [facebook/react-native#27950]
Description:

An empty `SectionList` crashes when calling `scrollToLocation({sectionIndex: 0, itemIndex: 0});`

React Native version:

```
System:
    OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Memory: 18.54 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.11.4 - /usr/local/bin/node
    Yarn: 1.21.1 - ~/.yarn/bin/yarn
    npm: 6.13.6 - /usr/local/bin/npm
    Watchman: 4.7.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 28
      Build Tools: 28.0.3, 29.0.2
      System Images: android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5
```

## Steps To Reproduce

```
const list = React.createRef();

<SectionList
  ref={list}
  sections={[]}
  renderItem={() => null}
/>

list.current.scrollToLocation({sectionIndex: 0, itemIndex: 0});

```

## Expected Results

Not throw an Error, a warning maybe or even nothing. Also `maximum is -1` doesn't feel right

## Snack, code example, screenshot, or link to a repository:

<img width="406" alt="Screenshot 2020-02-05 at 01 25 06" src="https://user-images.githubusercontent.com/1210832/73799843-61958e80-47b7-11ea-9560-f9c5c309e3e4.png">

**Comment by lafiosca** [comment]
I also experienced this unexpected behavior. Thanks for opening this issue.

**Comment by fabriziobertoglio1987** [comment]
>**Expected Results**
>Not throw an Error, a warning maybe or even nothing. Also maximum is -1 doesn't feel right

I am not sure about this. Maybe the core team will not accept a pull request to change this behaviour as the Javascript developer could easily handle this and avoid scrolling to index that does not exist.
