### ISSUE TITLE
AndroidManifest warnings when remove default permissions 

### ISSUE THREAD

**Issue by MohamadKh75** [facebook/react-native#27955]
Description:

I wanted to remove default permissions and followed [this guide](https://facebook.github.io/react-native/docs/removing-default-permissions). everything is ok but I get some warnings:

```bash
> Task :app:processDebugManifest
~\RN61\android\app\src\debug\AndroidManifest.xml:9:5-95 Warning:
        uses-permission#android.permission.READ_PHONE_STATE was tagged at AndroidManifest.xml:9 to remove other declarations but no other declaration present

~\RN61\android\app\src\debug\AndroidManifest.xml:10:5-100 Warning:
        uses-permission#android.permission.READ_EXTERNAL_STORAGE was tagged at AndroidManifest.xml:10 to remove other declarations but no other declaration present

```

React Native version:

```
System:
    OS: Windows 8.1 6.3.9600
    CPU: (8) x64 Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz
    Memory: 9.48 GB / 15.92 GB
  Binaries:
    Node: 10.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.21.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.11.3 - C:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 23.0.1, 25.0.0, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.3, 28.0.3
      System Images: android-22 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-25 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5692245
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
```

## Steps To Reproduce

1. create a blank project `npx react-native init RN61`
2. follow [this guide](https://facebook.github.io/react-native/docs/removing-default-permissions) 
3. try to build `cd android && gradlew assembleRelease`
4. the warnings will be in the console log!

## Expected Results

Don't get any warning :grin: 

## Snack, code example, screenshot, or link to a repository:

`null`

**Comment by safaiyeh** [comment]
Seems like the docs are just out of date. If you can pinpoint where the permissions were applied (might be removed or moved to AsyncStorage, etc..), then you can update the appropriate docs.
