### ISSUE TITLE
keyboardType 'email-address' does not work on iOS devices with the OS language set to Japanese

### ISSUE THREAD

**Issue by Karstagg** [facebook/react-native#27954]
Description:

keyboardType prop for 'email-address' type is ignored on iOS devices with the OS Language set to Japanese and possibly other languages. 

The default Japanese keyboard (10 key) is displayed. 

I suspect that this originates from the iOS code and there may be no legitimate way to fix in react-native. It seems as though this has potentially been an issue for some time with iOS. However I thought it would be good to create an issue incase anyone has an idea of how to deal with this.

***

React Native version:

System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 3.67 GB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1

***

## Steps To Reproduce

To replicate this issue please do the following:
1. start the [snack](https://snack.expo.io/By1mIsvzU) via expo either on an iOS device or in the expo iOS simulator in the snack.
2. Leave the app and set the OS language to Japanese
    * Settings>General>Language and region>iPhone Language>Japanese
3. re-open the app
4. Touch the TextInput field

***

## Expected Results

A text input such as the following will open the email entry keyboard regardless of OS Language 

`<TextInput
     placeholder="enter text here"
     keyboardType="email-address"
 />`

This is the expected behavior:

<img width="281" alt="Screen Shot 2020-02-05 at 11 30 21" src="https://user-images.githubusercontent.com/21345628/73806110-eb6f4700-480b-11ea-9938-c0f1442d1cb0.png">

Here is the actual behavior:

<img width="281" alt="Screen Shot 2020-02-05 at 11 32 43" src="https://user-images.githubusercontent.com/21345628/73806203-28d3d480-480c-11ea-82e1-8a2ce08a4b6c.png">

## Snack:

This snack can be used to replicate this issue. 

https://snack.expo.io/By1mIsvzU

**Comment by fonov** [comment]
Hi, this is not problem a react native, this is normal system behavior, you can see it - open default app "Contact" add or edit contact and try input email

<img src="https://user-images.githubusercontent.com/17071211/73885408-c2d16680-4878-11ea-9dc5-646728469684.png" width="300"/>

**Comment by Karstagg** [comment]
> Hi, this is not problem a react native, this is normal system behavior, you can see it - open default app "Contact" add or edit contact and try input email
> 
> <img alt="" width="300" src="https://user-images.githubusercontent.com/17071211/73885408-c2d16680-4878-11ea-9dc5-646728469684.png">
> 
> > It seems as though this has potentially been an issue for some time with iOS.
> 
> I don't think this is a problem with ios, rather it is a feature of the keyboard for the Japanese language not showing **@** symbol
> 
> However user can select @ symbol press on **ABC** button
> 
> > However I thought it would be good to create an issue incase anyone has an idea of how to deal with this.
> 
> if you really need keyboard with @, only one option create custom keyboard

Thanks for looking into this, I think you are right. it's not a React-Native issue. 

The problem was that our app was flagged during the Apple review process for this issue. 

keyboardType 'url' will show a 10 key input with roman alphabet characters and the @ symbol,

The keyboard can also be forced into english by toggling the secureTextEntry prop on and off. 

So I guess one of those will do for now.
