### ISSUE TITLE
missing autoCompleteType value for new password

### ISSUE THREAD

**Issue by thilonel** [facebook/react-native#27952]
Description:
The [autoCompleteType](https://facebook.github.io/react-native/docs/textinput#autocompletetype) is missing the [AUTOFILL_HINT_NEW_PASSWORD](https://developer.android.com/reference/androidx/autofill/HintConstants#AUTOFILL_HINT_NEW_PASSWORD) value, which would help the users when signing up to a service tremendously.

I believe it should be added ad [Libraries/Components/TextInput/TextInput.js#L310]( https://github.com/facebook/react-native/blob/master/Libraries/Components/TextInput/TextInput.js#L310)

React Native version:

I'm on 0.60.5 at the moment, but I guess it would be useful for all versions.

PS: I know that this is not really a bug, but I haven't found the proper way to submit a feature request.

**Comment by safaiyeh** [comment]
Hi @thilonel, if you don't got the time to send a PR for this I can take it on.

**Comment by thilonel** [comment]
I'd appreciate the help @safaiyeh

**Comment by safaiyeh** [comment]
@thilonel I added the missing type; however, since there a bunch more missing types missing. I'll add them all in one go.

You can track it here: https://github.com/facebook/react-native/pull/28008

**Comment by safaiyeh** [comment]
One question I have, maybe @dulmandakh or @JoshuaGross can answer.

This introduces the `androidx.autofill:autofill:1.0.0` dependency (added to the PR branch). Is there any concern about that?

**Comment by safaiyeh** [comment]
Another thing, `setAutofillHints` takes an array of strings, right now we are only supporting 1 hint type. This would be a breaking change; however, how viable would be:

1. Creating a enum of all the hints, verbatim to the strings `HintConstants` is for example [AUTOFILL_HINT_EMAIL_ADDRESS](https://developer.android.com/reference/android/view/View.html#AUTOFILL_HINT_EMAIL_ADDRESS) is just string `emailAddress`.

```javascript
enum TextInputAutofillHints {
  emailAddress = 'emailAddress'
  ...
}
```

2. Refactor `TextInput. setTextContentType` to simple set the string array without all the manual if statements. This can include being more verbose with the method name to `setAutoCompleteHints`. Plan could be deprecate `setTextContentType` to not break apps and introduce the new prop.

**Comment by dulmandakh** [comment]
Dependency addition requires some work on FB side, and it might take a while. Feel free to create a PR, and I'll be happy to review it.

**Comment by thilonel** [comment]
Hello @safaiyeh! I see you have a draft PR for this! How is that going? :)

**Comment by safaiyeh** [comment]
Hi @thilonel sorry for the delay, I haven't had time to check it out. I can pick it back up again.

**Comment by safaiyeh** [comment]
A year later lol... My PR is ready for review now

**Comment by safaiyeh** [comment]
https://github.com/facebook/react-native/pull/28008

**Comment by safaiyeh** [comment]
PR Merged

**Comment by TheNeumann** [comment]
This is a great improvement for Android -- will it be included in v.65.0?
