### ISSUE TITLE
App looks different in Simulator/Real Device

### ISSUE THREAD

**Issue by Estebank94** [facebook/react-native#27953]
Description:

Hello,

My app suddenly started to look different when I run it on a real iPhone Device compared to how it looks on the simulator.

The app looks fine using the emulator (both iOS and Android) but when running on a real device, some styles disappear for some reason. 

I tryed cleaning the build foalder, uninstall and installing the app but it still looks wrong.

![Simulator Screen Shot - iPhone 11 - 2020-02-05 at 00 44 29](https://user-images.githubusercontent.com/5116089/73809124-f1840a00-47b0-11ea-84ab-afa911d9bb8d.png)
![Screenshot_1580873842](https://user-images.githubusercontent.com/5116089/73809126-f34dcd80-47b0-11ea-869a-45badbab1520.png)
![IMG_8476](https://user-images.githubusercontent.com/5116089/73809197-3e67e080-47b1-11ea-96c9-cf5fbb2e219c.PNG)

React Native version:

    React Native Environment Info:
    System:
      OS: macOS 10.15
      CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
      Memory: 58.45 MB / 8.00 GB
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 8.11.3 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.1.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
      Android SDK:
        API Levels: 23, 24, 25, 26, 27, 28, 29
        Build Tools: 23.0.1, 25.0.0, 25.0.1, 25.0.2, 26.0.1, 26.0.2, 26.0.3, 28.0.2, 28.0.3, 29.0.1
        System Images: android-23 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.10 => 0.59.10 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
      react-native-rename: 2.4.1

## Steps To Reproduce

1. Run app

## Expected Results

    The app should look the same in the simulator and real device

## Snack, code example, screenshot, or link to a repository:

I don't know what code to show as this is too general.

**Comment by cloudnickde** [comment]
My 2¢... does your IPhone have Dark Mode? Some UI framework override only few colors and styles from the system UI, thus when Dark Mode enabled, some texts will appear light grey instead of black.

**Comment by Estebank94** [comment]
Thanks @cloudnickde, that was the problem.

To anyone having the same issue, you have to change the `UIUserInterfaceStyle` value in your info.plist file.
