### ISSUE TITLE
UIDocumentInteractionController menu does not dismiss.

### ISSUE THREAD

**Issue by kubanac95** [facebook/react-native#27965]
Description:

I have an issue with `UIDocumentInteractionController` which is used to open a PDF document.

The problem at this point is when user interacts with the menu my clicking on the `Open in {app_name}` action, the menu itself fails to close after user interaction leaving the menu open when user comes back to the app.

Dismissing the menu at this point requires user to tap twice on the `X` in order for menu to be dismissed.

I also tried to close the menu dynamically when app returns to active state by running `dismissMenuAnimated` on `UIDocumentInteractionController` instance but it does not work in this case, it does however dismiss the dialog if no interaction was made on it and the method is called.

One note, this issue is only present on never iOS version 13+. On older OS the menu is closed after interaction as expected.

React Native version:

```
System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz
    Memory: 34.29 MB / 4.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.3.0 - ~/.nvm/versions/node/v8.3.0/bin/node
    npm: 6.8.0 - ~/.nvm/versions/node/v8.3.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
  IDEs:
    Xcode: 10.1/10B61 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    create-react-native-module: 0.13.0
```

## Steps To Reproduce

It can be reproduced by using the function provided by the module `rn-fetch-blob` module.

https://github.com/joltup/rn-fetch-blob/wiki/iOS-API#iosopendocumentpathstring

I also tried different approach by writing by own code which has the same result.

```
@property (nonatomic, strong) UIDocumentInteractionController *documentInteractionController;
@property (atomic) CGRect rect;

RCT_EXPORT_METHOD(openDocumentInteractionControllerWithFileURL:(NSURL *)fileURL){
    if (!fileURL) {
        // Return NO because there was no valid fileURL.
        return;
    }
    
    UIViewController *rootCtrl = [[[[UIApplication sharedApplication] delegate] window] rootViewController];
    
    // Open "Open in"-menu
    self.documentInteractionController = [UIDocumentInteractionController interactionControllerWithURL:fileURL];
    self.documentInteractionController.delegate = self;

    BOOL sucess; // Sucess is true if it was possible to open the controller and there are apps available

    sucess = [self.documentInteractionController presentOpenInMenuFromRect:self.rect inView:rootCtrl.view animated:YES];

    
    if(!sucess){
        // Inform app that the activity has finished
        // Return NO because the service was canceled and did not finish because of an error.
        // http://developer.apple.com/library/ios/#documentation/uikit/reference/UIActivity_Class/Reference/Reference.html
    }
}

RCT_EXPORT_METHOD(dismissDocumentInteractionController){
    // Hide menu
    [self.documentInteractionController dismissMenuAnimated:YES];
}

```
## Expected Results

The menu should be dismissed after any user interaction.

**Comment by chrisglein** [comment]
If I'm understanding correctly, this isn't a problem with [rn-fetch-blob]https://github.com/joltup/rn-fetch-blob/wiki/iOS-API#iosopendocumentpathstring) or [react-native-document-controller](https://github.com/deldreth/react-native-document-controller) modules, but something you can also reproduce by calling directly. And that this is true starting with iOS 13+.  Were there any changes in the native behavior in that version? Is this an RN issue or a change in the platform?

**Comment by kubanac95** [comment]
@chrisglein You guessed it correctly, it's an issue that occurs on iOS 13+ version.

I can't tell if its a react-native issue or just a general platform issue. Some things have most certainly changed in the platform as well since the UI of the dialog has changed a bit, but the API did not, as war as I could tell.

But based on the official documentation and behavior it has on the prior platform version, the menu itself should be auto-dismissed after any user interaction. which fails in this case.

I did not try it again after with never version of react-native nor the platform, so the issue may no longer persist, and if it was platform based I supposed it may be resolved.
