### ISSUE TITLE
Promise polyfill and async/await transpliation make it hard to debug

### ISSUE THREAD

**Issue by EdenGottlieb** [facebook/react-native#27966]
## Description:
During debugging, stack traces of code that contains Promises doesn't supply data about code executed before promise resolution.

That is because currently have two mechanisms in place:
1. Promises are polyfilled using [promise](https://www.npmjs.com/package/promise) 
2. async/await is transpiled using [regenerator](https://github.com/facebook/regenerator/tree/master/packages/regenerator-transform).

We can get a pretty stack trace if we manage to turn off the Promise polyfill and regenerator transpliations.

1. Promise polyfill can be removed on both iOS (Supported from iOS 10 which is React Native's new minimum & Android (JSCore & Hermes on Android support native Promises). Should be tested thoroughly to make sure the native implementations work as expected and are stable.

2. Regenerator (async await) can't be removed yet (as Hermes doesn't support it and iOS minimum is iOS 12), but maybe we can supply an easy option to turn it off (using some flag in metro?)

## React Native version:

 0.61

## Steps To Reproduce

1. Create a react-native project 
2. Write code with async/await or Promises
3. Debug
4. Put a breakpoint after promise resolution (inside `.then()` callback or after `await`
5. Look at the stack trace

## Expected Results

See the full stack trace including code that ran before the Promise was initiaited, as is supported in Chrome DevTools.

## Snack, code example, screenshot, or link to a repository:

  
How the stack trace looks currently (bad):
![image (1)](https://user-images.githubusercontent.com/1867324/73849275-5469b580-4832-11ea-8e6a-b078b5175475.png)
How the stack trace looks with native Promise & async/await (good):
![image (2)](https://user-images.githubusercontent.com/1867324/73849415-8ed35280-4832-11ea-926a-6eeb150be8aa.png)

Code taken from open source project [react-native-demo](https://github.com/voximplant/react-native-demo)

**Comment by EdenGottlieb** [comment]
During my testing I found some specific calls to NativeModules (such as `FileReaderModule.readAsText` and `Networking.addListener`) fail on the native side due to a mismatch in arguments. 
This happens only after disabling `regenerator-transform` (using native `Promise` works fine).

I'm investigating it now (suggestions for possible causes are welcome!)

<img src="https://user-images.githubusercontent.com/1867324/73937320-770cd480-48ed-11ea-8069-0db8e6eb84e0.png" width=300> <img src="https://user-images.githubusercontent.com/1867324/73937325-78d69800-48ed-11ea-98ed-110d82e88753.png" width=300>

**Comment by FilipMaslovaric** [comment]
Not stale.

This is still an ongoing issue: not just within the context of debugging, but also performance/bundle size. On newer iOS/Android versions these transforms are unnecessary.

**Comment by SimpleCreations** [comment]
> (using native `Promise` works fine)

@EdenGottlieb could you please share how did you manage to disable React Native's `Promise` polyfill?

**Comment by EdenGottlieb** [comment]
> > (using native `Promise` works fine)
> 
> @EdenGottlieb could you please share how did you manage to disable React Native's `Promise` polyfill?


Sure.
This was a long time ago, so I can't recall it perfectly, and it may not work on recent versions, so take this with a pinch of salt.
It worked in a "hello world" app but didn't do so well in a full fledged app.

For using native Promise:
`node_modules/react-native/Libraries/Core/InitializeCore.js:`
Comment out this line:
`require('./polyfillPromise');`

For native async-await (this one caused me most of the problems):
1. `node_modules/react-native/Libraries/Core/InitializeCore.js:`
 Comment out this line:
`require('./setUpRegeneratorRuntime');` 
2. `node_modules/metro-react-native-babel-preset/src/configs/main.js`:
 From the `defaultPlugins` array, remove the entry with  `@babel/plugin-transform-regenerator` (should look something like ` [require("@babel/plugin-transform-regenerator")]`)

Good luck!
