### ISSUE TITLE
Problems running Android

### ISSUE THREAD

**Issue by TYRONEMICHAEL** [facebook/react-native#2796]
I have tried two different computers and keep getting the same issue. I have installed all Support Libraries as instructed from the website under Android Support. 

    Could not find com.android.support:appcompat-v7:23.0.0.
    Could not find com.android.support:support-v4:21.0.3.

I am running OSX. The urls are also returning 404's. I.e https://jcenter.bintray.com/com/android/support/appcompat-v7/23.0.0/appcompat-v7-23.0.0.jar. No support folder either https://jcenter.bintray.com/com/android/

**Comment by mayuelei66** [comment]
I had the same problem，and I solved it by reading the react official docs.https://facebook.github.io/react-native/docs/android-setup.html#content,do exactly as the docs say.And also I found genymotion is faster than the native avd powered by Google.Here is the my demo
![image](https://cloud.githubusercontent.com/assets/5960165/9930107/eba71bb8-5d63-11e5-99c5-d26ec1e5ee5a.png)

**Comment by mkonicek** [comment]
Thanks for replying @mayuelei66!

@TYRONEMICHAEL Please make sure you have the prerequisites installed:
https://facebook.github.io/react-native/docs/android-setup.html

**Comment by TYRONEMICHAEL** [comment]
Uninstalled and reinstalled the support library. Seems to have done the trick. Thanks @mayuelei66.

**Comment by mbrookes** [comment]
@mkonicek  - there are contradictory instructions in the Android Setup Guide. Under "Install and configure SDK" it says:

>"Start a new shell and run android; in the window that appears make sure you check:
>Android SDK Build-tools version 23.0.1
>Android 6.0 (API 23)
>Android Support Repository"

All of "Android 6.0 (API 23)"? Really?

But in the next section "Install and run Android stock emulator" it says:

>"Start a new shell and run android; in the window that appears make sure you check:
>Intel x86 Atom System Image (for Android 5.1.1 - API 22)
>Intel x86 Emulator Accelerator (HAXM installer)"

Oh, so just "Intel x86 Atom System Image"

But then in the screenshots it shows:

>Android SDK Tools
>Android SDK Platform tools
>Android SDK Build tools
>Android 6.0 (API 23) / SDK Platform
>Android 6.0 (API 23) / Intel x86 Atom_64 System Image
_and_
>Android 6.0 (API 23) / Intel x86 Atom System Image

Then:

>Android Support Repository
_and_
>Android Support Library

As well as:

>Intel x86 Emulator Accelerator (HAXM installer)

Needless to say, it's very confusing what is actually needed to get this running...

**Comment by grigio** [comment]
+1 I've all the packages as specified in the docs, but I can't align all the dependencies
```
> Failed to notify project evaluation listener.
   > Could not resolve all dependencies for configuration ':ReactAndroid:_debugCompile'.
      > Could not find com.android.support:appcompat-v7:23.0.1.
```

**Comment by aqumus** [comment]
Did anyone got a solution for this issue , I am also facing the same issue .

Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not find com.android.support:appcompat-v7:23.2.
     Searched in the following locations:
         file:/C:/Users/aquib/.m2/repository/com/android/support/appcompat-v7/23.2/appcompat-v7-23.2.pom
         file:/C:/Users/aquib/.m2/repository/com/android/support/appcompat-v7/23.2/appcompat-v7-23.2.jar
         https://jcenter.bintray.com/com/android/support/appcompat-v7/23.2/appcompat-v7-23.2.pom
         https://jcenter.bintray.com/com/android/support/appcompat-v7/23.2/appcompat-v7-23.2.jar
     Required by:
         helloWorld:app:unspecified
   > Could not find com.android.support:recyclerview-v7:23.0.1.
     Searched in the following locations:
         file:/C:/Users/aquib/.m2/repository/com/android/support/recyclerview-v7/23.0.1/recyclerview-v7-23.0.1.pom
         file:/C:/Users/aquib/.m2/repository/com/android/support/recyclerview-v7/23.0.1/recyclerview-v7-23.0.1.jar
         https://jcenter.bintray.com/com/android/support/recyclerview-v7/23.0.1/recyclerview-v7-23.0.1.pom
         https://jcenter.bintray.com/com/android/support/recyclerview-v7/23.0.1/recyclerview-v7-23.0.1.jar
     Required by:
         helloWorld:app:unspecified > com.facebook.react:react-native:0.20.1
   > Could not find com.android.support:appcompat-v7:23.2.
     Searched in the following locations:
         file:/C:/Users/aquib/.m2/repository/com/android/support/appcompat-v7/23.2/appcompat-v7-23.2.pom
         file:/C:/Users/aquib/.m2/repository/com/android/support/appcompat-v7/23.2/appcompat-v7-23.2.jar
         https://jcenter.bintray.com/com/android/support/appcompat-v7/23.2/appcompat-v7-23.2.pom
         https://jcenter.bintray.com/com/android/support/appcompat-v7/23.2/appcompat-v7-23.2.jar
     Required by:
         helloWorld:app:unspecified > com.facebook.react:react-native:0.20.1
   > Could not find com.android.support:support-v4:21.0.3.
     Searched in the following locations:
         file:/C:/Users/aquib/.m2/repository/com/android/support/support-v4/21.0.3/support-v4-21.0.3.pom
         file:/C:/Users/aquib/.m2/repository/com/android/support/support-v4/21.0.3/support-v4-21.0.3.jar
         https://jcenter.bintray.com/com/android/support/support-v4/21.0.3/support-v4-21.0.3.pom
         https://jcenter.bintray.com/com/android/support/support-v4/21.0.3/support-v4-21.0.3.jar
     Required by:
         helloWorld:app:unspecified > com.facebook.react:react-native:0.20.1 > com.facebook.fresco:fresco:0.8.1 > com.facebook.fresco:imagepipeline:0.8.1
         helloWorld:app:unspecified > com.facebook.react:react-native:0.20.1 > com.facebook.fresco:fresco:0.8.1 > com.facebook.fresco:drawee:0.8.1

**Comment by sercanov** [comment]
I have the same issue with @aqumus

**Comment by grigio** [comment]
+1 I confirm "Local Maven repository" fixes this issue

**Comment by jamesone** [comment]
+1 can confirm installing `Local Maven Repository` fixed this issue. If you cannot see `Local Maven Repository`, then you have to update the old `Android Support Repository` until `Local Maven Repository` shows up.

**Comment by outofculture** [comment]
I had to install `Android Repository` to get it to build.

**Comment by dannysindra** [comment]
I got this error as well. I have followed the tutorial from react-native page, re-install "Android Support Repository" but still not working.

The "Local Maven Repository" seemed to be removed now from SDK manager, so the recent suggestions above not working as well.

**Comment by tobyreynold** [comment]
@mayuelei66 You give the url (https://facebook.github.io/react-native/docs/android-setup.html#content) is redirect to the react-native getting started (https://facebook.github.io/react-native/docs/getting-started.html). It will not help other people to fix this problem.

**Comment by konark-hike** [comment]
Can't see Local Maven Repository in my SDK manager, have "Android Support Repository" installed but still facing this error ::
Error:Could not find com.facebook.fresco:fresco:0.11.0.
Required by:
    android-client:ReactAndroid:unspecified
<a href="searchInBuildFiles">Search in build.gradle files</a>
For all react-native dependencies on building from source in my already running project. 
@mayuelei66 @jamesone Can you please help in finding the solution for this

**Comment by vlamitin** [comment]
This what worked for me:
as we can see here Local Maven Repo now included in Android Support Repository and Google Repository
https://developer.android.com/studio/intro/update.html

So, I installed both of them and finally built my project.
