### ISSUE TITLE
RCTLogConvertError when use 'react-native-push-notification'

### ISSUE THREAD

**Issue by VladVader** [facebook/react-native#27971]
## Description:

I get error, when I try to schedule localNitification using react-native-push-notification. Notification is scheduled and an error is thrown. When I dismiss it, notifications work properly.
![photo_2020-02-06_10-31-27](https://user-images.githubusercontent.com/27889786/73923970-ff7a7d80-48cb-11ea-8ed4-d34719593a8c.jpg)

React Native version:  0.62.0-rc.1
react-native-push-notification :  3.1.3

## Steps To Reproduce
1. Install react-native-background-fetch, react-native-push-notification
2. try to schedule local notification using PushNotification.localNotificationSchedule

## Expected Results

There should be no error, when we try to schedule local notification

## Snack, code example, screenshot, or link to a repository:
Probably this is the place, where we got this error :
![image_2020-02-06_10-35-46](https://user-images.githubusercontent.com/27889786/73924260-7b74c580-48cc-11ea-9302-463078d06dd7.png)

**Comment by chrisglein** [comment]
Sounds like you're reporting an issue with [react-native-push-notification](https://github.com/zo0r/react-native-push-notification). You should open an issue there unless this is a problem caused by the core platform (I see you opened against the 0.62 RC, which is now released).
