### ISSUE TITLE
In React-native While Launch app in Emulator It will Be crash or force Stopped V0.61.5

### ISSUE THREAD

**Issue by Thirumalaisamy-paulraj** [facebook/react-native#27970]
Description:

 If I upgraded the  latest Versions and also async libary as a latest Version..after that i run the app using the command react-native run-android and its build successfully but emulator  I open the App it will be shown as force stopped while open the app 

React Native version:

  System:
    OS: Linux 5.0 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (8) x64 AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx
    Memory: 148.21 MB / 7.41 GB
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 12.14.1 - /usr/bin/node
    Yarn: 1.21.1 - /usr/bin/yarn
    npm: 6.13.1 - /usr/local/bin/npm
  SDKs:
    Android SDK:
      API Levels: 23, 26, 27, 28
      Build Tools: 23.0.1, 27.0.3, 28.0.3, 29.0.2
      System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
  npmPackages:
    react: ^16.9.0 => 16.12.0 
    react-native: ^0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1

## Expected Result of mine
[ForceStop](https://user-images.githubusercontent.com/52504374/73912646-0e1c6100-48db-11ea-9663-2c00a3801d5c.png)

**Comment by vksgautam1** [comment]
might be third party dependency could be creating the issue with latest RN
