### ISSUE TITLE
Warning: Each child in a list should have a unique "key"

### ISSUE THREAD

**Issue by iway1** [facebook/react-native#27979]
Description:
    React Native throws a warning every time I render an array where the elements don't have a "key" property. Obviously this was intended but it is ill-suited to common use-cases including every case where a list is not dynamic.

React Native version:

    https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz

## Steps To Reproduce

1. Render a list without including a "key" property in each element:
```
<View>
    {items.map(function(item){
        return (<View/>)
    }
</View>
```
This throws a warning. Every single time I've encountered this, I end up writing the exact same code (which effectively does nothing except silence this warning):

```
function Comp() {
    var c = 0;
    items = [{...}, {...}]
    return (
        <View>
            {items.map(function(item){
                return (<View key={"" + c++} />)
            }
        </View>
    )
}
```

This code is literally just creating a counter and then assigning a counter to that key, setting the key of each view element to be it's index in the items list.

## Expected Results

react-native should automatically generate a key whenever one is not provided if it is really that big a deal. It could simply set the key to the index of the item in the original list. It does not makes sense that I have to write extra code every time I render a list of items simply to silence a warning. 

It would be better if every line of code I write actually does something.

**Comment by hramos** [comment]
I *think* this is coming from React. Perhaps https://github.com/facebook/react is better suited for this issue?

**Comment by dulmandakh** [comment]
This is not an issue, it's the feature. Please provide unique value to key, perhaps item.id as below.

```js
function Comp() {
    var c = 0;
    items = [{...}, {...}]
    return (
        <View>
            {items.map(function(item){
                return (<View key={item.id} />)
            }
        </View>
    )
}
```

**Comment by iway1** [comment]
@Dulmana

> This is not an issue, it's the feature. Please provide unique value to key, perhaps item.id as below.
> 
> ```js
> function Comp() {
>     var c = 0;
>     items = [{...}, {...}]
>     return (
>         <View>
>             {items.map(function(item){
>                 return (<View key={item.id} />)
>             }
>         </View>
>     )
> }
> ```

Explain how requiring developers to write additional code that serves absolutely no purpose is "Not an issue"? 

In many common use cases, this key that we're having to pass as a prop does absolutely nothing. It's not a feature if it requires developers to do additional work that doesn't result in additional functionality. Please reopen this issue or explain why a key would be needed in cases where the items should be rendered in the same order that they appear in the list. 

Just saying something is "A feature" without any idea of it's usefulness is nonsense. It seems to me it is clearly an issue in every case where we should render array items in the order they appear in that array, which is very common practice. 

I'm sorry, but your reply and closing this issue without explanation is antithetical to the progression of react-native as a framework. Please consider explaining yourself.

**Comment by dulmandakh** [comment]
This is how React.js works, please see why you need to provide key prop https://reactjs.org/docs/lists-and-keys.html. Thanks
