### ISSUE TITLE
[android] null pointer exception

### ISSUE THREAD

**Issue by h87kg** [facebook/react-native#2798]
E/AndroidRuntime(20401): FATAL EXCEPTION: main
E/AndroidRuntime(20401): Process: com.navigatordemo, PID: 20401
E/AndroidRuntime(20401): java.lang.NullPointerException
E/AndroidRuntime(20401): 	at android.widget.TextView.getExtendedPaddingTop(TextView.java:1824)
E/AndroidRuntime(20401): 	at android.widget.TextView.getTotalPaddingTop(TextView.java:1918)
E/AndroidRuntime(20401): 	at com.facebook.react.views.text.ReactTextView.reactTagForTouch(ReactTextView.java:34)
E/AndroidRuntime(20401): 	at com.facebook.react.uimanager.TouchTargetHelper.getTouchTargetForView(TouchTargetHelper.java:139)
E/AndroidRuntime(20401): 	at com.facebook.react.uimanager.TouchTargetHelper.findTargetTagForTouch(TouchTargetHelper.java:50)
E/AndroidRuntime(20401): 	at com.facebook.react.ReactRootView.handleTouchEvent(ReactRootView.java:145)
E/AndroidRuntime(20401): 	at com.facebook.react.ReactRootView.onInterceptTouchEvent(ReactRootView.java:221)
E/AndroidRuntime(20401): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1859)
E/AndroidRuntime(20401): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
E/AndroidRuntime(20401): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
E/AndroidRuntime(20401): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
E/AndroidRuntime(20401): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
E/AndroidRuntime(20401): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
E/AndroidRuntime(20401): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)

**Comment by mkonicek** [comment]
Thanks for reporting!

Could you please post your JS, ideally a minimal repro?

**Comment by h87kg** [comment]
[Here's the source](https://github.com/h87kg/NavigatorDemo)
It's only happened once.

**Comment by satya164** [comment]
There have been many changes to the touch handling fixing many issues. So hopefully this is fixed. If not, lets reopen.

**Comment by codetomylaw** [comment]
java.lang.NullPointerException
com.facebook.react.views.text.ReactTextView.setText(ReactTextView.java:37)

RN： 0.29.2

why ？
