### ISSUE TITLE
TextInput issue 

### ISSUE THREAD

**Issue by bhuvin25** [facebook/react-native#27985]
Description : 
I want only alphabets to be entered in textinput not symbols and special characters.
If there any prop or way to do that other than onChangeText function call and using regex in IOS and android in react native 

Because in native android and IOS has property to allow only alphabets and number .

for ex:  android:digits="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ "

React-native info : 
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5

Steps To Reproduce : 
 1)Add a TextInput component.

Expected Results :
1) TextInput must allow only alphabets not special characters and numbers .

**Comment by hramos** [comment]
Please make sure to use one of the provided issue templates at https://github.com/facebook/react-native/issues/new/choose

**Comment by bhuvin25** [comment]
Description :
I want only alphabets to be entered in textinput not symbols and special characters.
If there any prop or way to do that other than onChangeText function call and using regex in IOS and android in react native

Because in native android and IOS has property to allow only alphabets and number .

for ex: android:digits="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ "

React-native info :
react: 16.9.0 => 16.9.0
react-native: 0.61.5 => 0.61.5

Steps To Reproduce :
1)Add a TextInput component.

Expected Results :

TextInput must allow only alphabets not special characters and numbers .
