### ISSUE TITLE
TypeScript support for 0.62

### ISSUE THREAD

**Issue by TheSavior** [facebook/react-native#27997]
There are some changes in React Native that need to get updated in the TypeScript type definitions for 0.62.0

- [x] Host components should have methods like measure, measureInWindow, measureLayout
- [x] Direct UIManager methods for the above are deprecated
- [ ] Proper HostComponent typing and APIs that accept a host component should be properly constrained. 
- [x] [Animated's useNativeDriver config flag is now a required property](https://github.com/react-native-community/releases/pull/156#issuecomment-582142057)

**Comment by alloy** [comment]
> APIs that accept a host component should be properly constrained

@TheSavior Can you point me to such an API? I can’t seem to find any.

**Comment by TheSavior** [comment]
Search the codebase for arguments with `HostComponent<`. 

One example is ref.measureLayout. Also search for `.Commands`.

**Comment by NativeCoder25** [comment]
I can't seem to use the measureLayout to get the position of a Button component and it's giving me the error that says 'undefined is not a function', even after I try importing the function from react-native module. Is this a bug?

**Comment by alloy** [comment]
@NativeCoder25 While this PR touches on `measureLayout`, this PR is about typings for the unreleased 0.62 version of RN. Your needs are better served on StackOverflow or one of the various community platforms, see: https://reactnative.dev/help

**Comment by safaiyeh** [comment]
@TheSavior Does HostComponent still need appropriate types?

**Comment by TheSavior** [comment]
I think this is resolved. Thanks for flagging!
