### ISSUE TITLE
READMEs for npm packages

### ISSUE THREAD

**Issue by amasad** [facebook/react-native#280]
react-native-cli

**Comment by jsierles** [comment]
Here's a README:

Use react-native-cli to initialize a working starter React Native app using the latest react-native version in npm. This package should be installed globally.

Usage:

```
% npm install -g react-native-cli
% react-native-cli init myApplication
```

**Comment by ide** [comment]
@jsierles want to add README.md to https://github.com/facebook/react-native/tree/master/react-native-cli? npm should automatically take care of the rest when it comes to displaying the docs on npmjs.com.

**Comment by jsierles** [comment]
#1444

**Comment by brentvatne** [comment]
Nice :smile:
