### ISSUE TITLE
[ios] no visible @interface for 'RCTRootView' declares the selector error after upgrade to React Native 0.11

### ISSUE THREAD

**Issue by aksonov** [facebook/react-native#2800]
```
/Users/aksonov/Documents/react-native-tableview/examples/TableViewDemo/iOS/AppDelegate.m:48:48: error: no visible @interface for 'RCTRootView' declares the selector 'initWithBundleURL:moduleName:launchOptions:'
  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                           ~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by grabbou** [comment]
Not an issue. The signature has changed and you need to pass `initialProperties:nil`.

Instead, you were doing:
```
rootView.initialProperties = @{}
```
which was a complete opt-in. Now you need to include that as well. If you start writing `initWithBundleURL` XCode will suggest you proper signature.

CC: @brentvatne

**Comment by aksonov** [comment]
Looks like breaking change in v0.11 ? Strange, didn't found any mention on it...

**Comment by ide** [comment]
Added to breaking changes in the 0.11-rc notes.

**Comment by idibidiart** [comment]
Ouch. Please note the breaking changes before pushing a new version. My last experience working with a Facebook API was rocky as it kept changing faster than the changes could be documented. I am hoping that React and React Native are going to be different :). I just had the same issue. I am hlad it is an issue with a simple fix.  Whew.

**Comment by rhaker** [comment]
Just encountered this as well. For me, the steps to fix were:

1) In AppDelegate.m change:

RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"yourAppName"
                                                      initialProperties:nil
                                                   launchOptions:launchOptions];

FROM

RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"yourAppName"
                                                   launchOptions:launchOptions];

2) Within your tests folder (e.g. yourAppNameTests), comment out the line in the .m file:

redboxError = [[RCTRedBox sharedInstance] currentErrorMessage];

Then it should build with no errors.

FYI, Facebook et al is doing a really great job with this...

**Comment by grabbou** [comment]
PS. For the future, it might be better to just print deprecation warnings on methods that are being replaced with a new ones (e.g. different signature) and remove the old ones in the following release.

**Comment by shatran** [comment]
Thanks @rhaker. Worked for me.

**Comment by edo1493** [comment]
Could this affect devices that have iOS 8 installed? 
I have updated my react native and added the missing params, but when releasing on TestFlight I get blank screen on a device which hasn't updated to iOS9 yet.
