### ISSUE TITLE
onPress TouchableOpacity triggers more than once

### ISSUE THREAD

**Issue by armagedan** [facebook/react-native#28003]
I ma building an android application and It seems that the touchable opacity when pressed from keyboard and d-pad, presses 4 times. I have my button as a separate component.

There is also another issue occurring and I think it's a bug. When I use the `hasTVPreferredFocus` true, it auto presses the button when it focuses on the button.  Here is my button component and my App.js

CustomButton.js:

```
import React, { Component } from 'react';
import {View, Text, TouchableOpacity, Animated, Easing} from 'react-native';

export default class CustomButton extends Component {

    constructor(props) {
        super(props);
        this.state = {
            loaded: false
        };
        this.focusIn = this.focusIn.bind(this);
        this.focusOut = this.focusOut.bind(this);
    }

    componentDidMount() {
        this.animatedValue = new Animated.Value(1);
        this.setState({loaded: true});
    }

    focusIn() {
        Animated.spring(this.animatedValue, {
            toValue: this.props.toValue
        }).start()
    }
    focusOut() {
        Animated.spring(this.animatedValue, {
            toValue: 1,
            friction: 3,
            tension: 40
        }).start()
    }

    render() {

        const animatedStyle = {
            transform: [{ scale: !this.state.loaded ? 1 : this.animatedValue}]
        }

        return (

            <Animated.View style={animatedStyle}>
                <TouchableOpacity hasTVPreferredFocus={this.props.selected} onPress={this.props.onPress} activeOpacity={1} style={this.props.buttonStyle} onFocus={this.focusIn} onBlur={this.focusOut}>

                        <View style={this.props.buttonWrapper}>
                                <Text style={this.props.buttonLabel}>{this.props.buttonName}</Text>
                        </View>

                </TouchableOpacity>
            </Animated.View>
        );
    }
}

```

App.js:

```
<CustomButton
   buttonStyle={styles.button}
   buttonWrapper={styles.buttonWrapper}
   buttonLabel={styles.buttonLabel}
   buttonName="Add"
   toValue={1.2}
   onPress={()=>this.addToBasket()}
   selected={true}
/>
```

in order to fix the multiple button press issue, I am using dbounce package from lodash. But is it really a viable option here? Because when using it, the presses feels slower because I have set the time to 200ms. Either way, I want to know if this is a bug or an issue with my project. I would still prefer not using dbounce (from my experience, presses are slower). But at the same time, I can't have a state set 4 times or call a function (which will eventually make an API request) 4 times.

**Comment by Peridon** [comment]
Maybe someone can add throttle prop to button, that doesn't call onPress until some global delay, shared by all buttons has passed. there doesn't need to be a default value, it can be disabled. In some cases it's justified to be able to click multiple times quickly. This throttling is useful e.g. if onPress calls api or does something expensive.

**Comment by armagedan** [comment]
Is this a bug or a problem with my code? When I touch, it seems to work fine. It just happens when I press the button. Only for the onPress. onFocus seems fine too. What is actually happening here?
