### ISSUE TITLE
Unable to connect to server running in an IPV6 network

### ISSUE THREAD

**Issue by christian-hess-94** [facebook/react-native#28022]
Description:
I'm sending request from my React Native app to a Glassfish server. Aparently the server is being hosted in an environment IPV6 enabled environment. When I try to connect to the server via wifi connection that is only IPV4 enable, the requests work as intended (both server and phone are not in the same network but can see each other fine). When the same thing is done via 4g or some network that has IPV6 enabled, the requests take about about 3 to 4 minutes to recieve their responses, for about 1kb of data being transmitted.

React Native version:
System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-7500T CPU @ 2.70GHz
    Memory: 1.06 GB / 7.88 GB
  Binaries:
    Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: 4.9.4 - C:\watchman\watchman.EXE
  IDEs:
    Android Studio: Version  3.5.0.0 AI-191.8026.42.35.6010548

## Steps To Reproduce

    Provide a detailed list of steps that reproduce the issue.
    Issues without reproduction steps or code are likely to stall.

1. Create any starter app using react-native init
2. Execute a fetch(url) command to any IP address that is inside an IPV6 enabled network, from another IPV6 enabled network (like 4g)

## Expected Results

The request should work like intended when using IPV4. the response should take about 3 seconds, it takes about 180 seconds.

## Snack, code example, screenshot, or link to a repository:

fetch(url)
.then(...display the message)
.catch(...display the error)

**Comment by faustoct** [comment]
I think it's a related issue https://github.com/facebook/react-native/issues/28038

**Comment by chrisglein** [comment]
Some version information here, but not for React Native itself.
