### ISSUE TITLE
[ios] Inside NetInfo.fetch(), resolve's argument seems to be always undefined

### ISSUE THREAD

**Issue by 0517** [facebook/react-native#2802]
While I am trying to find a solution to detect if the device is under the WIFI environment, the sample code in the docs seems doesn't work 

    componentDidMount: function() {
        NetInfo.addEventListener(
            'change',
            this._handleReachabilityChange
        );
        NetInfo.fetch().done(
            (reachability) => { this.setState({reachability}); }
        );
    },

The reachability always return undefined. So I read the source code and find that inside the NetInfo.fetch() function, it resolve with a maybe undefined argument

    resolve(resp.network_reachability);

However the resp is actually of that format: {network_info: }. I wonder if it is a bug or I lost some step to make it right?

**Comment by yogesh-patel** [comment]
Same issue I was facing with react-native version 0.11.4, I tried to change NetInfo.js (line no 171) from resolve(resp.network_reachability); to  resolve(resp.network_info);, and its working. I wonder its a bug.

**Comment by christopherdro** [comment]
Related to #3333. Fixed with PR #3345.

**Comment by jamesfzhang** [comment]
Thanks for the fix @yogesh-patel
