### ISSUE TITLE
[Android] ScrollView clip children even with overflow: 'visible'

### ISSUE THREAD

**Issue by Tiltorito** [facebook/react-native#28026]
As the title says the scrollview clip children. Having a quick look on the source code seems that all the classes that extend from [ReactViewGroup](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/views/view/ReactViewGroup.java#L129) have setClipChildren(false);

[ReactScrollView](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/views/scroll/ReactScrollView.java#L48) on the other hand doesn't extend from ReactViewGroup and hence setClipChildren is not being set to false.

I might be **completely** wrong but it's a potential suggestion to fix the bug - I am using React 0.61.4

**Comment by sorakrisc** [comment]
not working in react-native 0.61.2 as well

**Comment by Twelvefat** [comment]
not working in react native 0.63.2 as well

**Comment by avlonder** [comment]
not working on 0.62.2
any workarounds?

**Comment by RickardZrinski** [comment]
Here's an Expo Snack reproducing the issue: https://snack.expo.io/Xw1c66W8R

Note how the behaviour differs when using a View instead of a ScrollView. The View parent doesn't clip its child, while ScrollView does.

**Comment by dehlen** [comment]
Why is this issue closed it is not resolved-
