### ISSUE TITLE
RCTLocationObserver is undefined on android

### ISSUE THREAD

**Issue by mattiamanzati** [facebook/react-native#2803]
Hi all, I started a new project using react-native init, and added some code to watch the current geolocation position, so I added a command to my package.json to deploy over my device via usb

"deploy-android": "curl \"http://localhost:8081/index.android.bundle?platform=android\" -o \"android/app/src/main/assets/index.android.bundle\" && react-native run-android"

but when I try to run the app on my device I get the redox saying 

undefined is not an object (evaluating RCTLocationObserver.startObserving) in watchPosition.

Is this an error I've done or am I wrong?
Also, have I to setup gps permissions? If so, how and where?

Thanks for feedback and help! :)

**Comment by foghina** [comment]
We haven't open sourced geolocation on Android yet, it's on the [Known Issues](https://facebook.github.io/react-native/docs/known-issues.html).

**Comment by mattiamanzati** [comment]
Uh, sorry I missed it!

**Comment by saidimu** [comment]
Can't see anything on the Known Issues page about geolocation on Android. The [geolocation](https://facebook.github.io/react-native/docs/geolocation.html#content) page doesn't mention anything either.

**Comment by foghina** [comment]
@saidimu on the known issues page the first section is *Missing Modules and Native Views*, geolocation is mentioned under *Modules*. We should probably make it more obvious somehow.

**Comment by saidimu** [comment]
@foghina Ah ha! At first glance I took the list to mean what is already included: `Our provisional plan... includes:`

Perhaps the list titles could read `Planned Views` and `Planned Modules`.

**Comment by mkonicek** [comment]
Closing as this has been answered.
