### ISSUE TITLE
ImageBackground imageRef not Image Component

### ISSUE THREAD

**Issue by steavengong** [facebook/react-native#28045]
Description:
     ImageBackground imageRef not Image Component
   
{current: ReactNativeFiberHostComponent}
current: ReactNativeFiberHostComponent
_nativeTag: 5
_children: []
viewConfig: {directEventTypes: {…}, NativeProps: {…}, uiViewClassName: "RCTImageView", validAttributes: {…}, bubblingEventTypes: undefined}
__proto__: Object
__proto__: Object

![image](https://user-images.githubusercontent.com/10862092/74395817-3d871c80-4e4b-11ea-9478-5b7f3a430f36.png)

my code 
```
import React , {useRef}from 'react';
import {ImageBackground, SafeAreaView, Button} from 'react-native';
import Style from './style'

export default (props) => {
    const {style} = props

    const imageRef = useRef(null)

    const onPress  = ()=>{
        console.log(imageRef)
    }

    return (
        <SafeAreaView style={[Style.page,{...style}]}>
            <ImageBackground source={require('imagePath')} imageRef={imageRef} style={{flex:1}}>
                <Button onPress={onPress} title={'show imageRef'}/>
            </ImageBackground>

        </SafeAreaView>
    );
}

```

what's happened? or  I used wrong?

React Native version:

System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 21.25 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.14.1 - /var/folders/m3/2yk59j796c79h1y0l08j4xnw0000gn/T/yarn--1581560427115-0.8790761087847496/node
    Yarn: 1.21.1 - /var/folders/m3/2yk59j796c79h1y0l08j4xnw0000gn/T/yarn--1581560427115-0.8790761087847496/yarn
    npm: 6.13.7 - ~/.nvm/versions/node/v12.14.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5

    Run `react-native info` in your terminal and copy the results here.

**Comment by loverdeveloper** [comment]
@steavengong Did you fix this?

**Comment by loverdeveloper** [comment]
@steavengong I think you must do this 
`console.log(imageRef.current)` 
not
`console.log(imageRef)`
