### ISSUE TITLE
CreateProcess error=193, %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by Waqas-Jani** [facebook/react-native#28055]
Description:
    i'm facing this error in react native version 0.61.5 
error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
:ReactNative:Running 'E:\xxx\xxx\JS\ReactNative\Other-Projects\todoapp\node_modules\@react-native-community\cli\build\bin.js config' command failed.

FAILURE: Build failed with an exception.

* Where:
Script 'E:\xxx\xxx\JS\ReactNative\Other-Projects\todoapp\node_modules\@react-native-community\cli-platform-android\native_modules.gradle' line: 154

* What went wrong:
A problem occurred evaluating script.
> Cannot run program "E:\xxx\xxx\JS\ReactNative\Other-Projects\todoapp\node_modules\@react-native-community\cli\build\bin.js": CreateProcess error=193, %1 is not a valid Win32 application

React Native version:
   "react-native": "0.61.5"

**Comment by CorwinMoyne** [comment]
Same problem

**Comment by sclavijo93** [comment]
same problem here in a fresh react native app

**Comment by leolivm** [comment]
same

**Comment by andreaSimonePorceddu** [comment]
Same. The problem started after the 3.1.0 minor release.  Released 5 hours ago.

**Comment by sclavijo93** [comment]
Here's a workaround https://github.com/react-native-community/cli/issues/945#issuecomment-585976462

**Comment by tony-tsx** [comment]
I created a temporary solution with few changes in @react-native-community/cli-platform-android native_module.gradle
[Issue](https://github.com/react-native-community/cli/issues/965)

**Comment by grabbou** [comment]
Fixed via https://github.com/react-native-community/cli/issues/965#issuecomment-586011638

Please reinstall node_modules and remove `lockfile`.
