### ISSUE TITLE
`react-native help` CLI

### ISSUE THREAD

**Issue by gre** [facebook/react-native#2805]
Would be great if we could list all available commands.

```
➜  react-native help
Command `help` unrecognized. Did you mean to run this inside a react-native project?
➜  react-native -h
Command `-h` unrecognized. Did you mean to run this inside a react-native project?
➜ react-native --help
Command `--help` unrecognized. Did you mean to run this inside a react-native project?
```

**Comment by kohver** [comment]
:+1:

**Comment by mkonicek** [comment]
Can you send a pull request to do this?

**Comment by tdzl2003** [comment]
Now run "react-native" without any argument in a project can print a help message. But run it anywhere else will only "You did not pass any commands, did you mean to run `react-native init`?"

**Comment by mkonicek** [comment]
Yes this is the current behavior. Please feel free to send a PR to improve this!
