### ISSUE TITLE
Modal View resizes automatically when keyboard opens (Android)

### ISSUE THREAD

**Issue by panda0603** [facebook/react-native#28063]
Description:

I'm using Modal component, which contains multiple views as child. The View has some TextInput elements. When the keyboard pops up, the modal view resizes to fit into the remaining space above the keyboard, and reverts back when keyboard closes(checked by giving borderWidth), but I don't want the Modal to resize when keyboard opens.

This does not happen for IOS. And also, it does not happen in non-modal Views for Android.

I have windowSoftInputMode="adjustPan" set in my android Manifest, but it doesn't seem to be applied on the Modal.

Tried applying fixed height to the Modal, and full screen height to modal's child view as well, but doesn't work

React Native version:

    0.61.5

## Steps To Reproduce

TextInput within a modal.

## Expected Results

   Modal view to retain its height.

**Comment by ashertoufeeq** [comment]
Can you provide screen shots?

**Comment by panda0603** [comment]
@ashertoufeeq Sure thing. 

Before textInput focused: 
![image](https://user-images.githubusercontent.com/34116285/74602680-a510c680-50ee-11ea-8468-3791f7a5f53f.png)

After text input focused:
![image](https://user-images.githubusercontent.com/34116285/74602683-ba85f080-50ee-11ea-96db-4c96c4ddb9fd.png)

You can see that red border shrinks as keyboard popsup

**Comment by safaiyeh** [comment]
Hello, Modal was moved to a community repo, can you make the issue there and make sure you’re using that one. https://github.com/react-native-community/react-native-modal
