### ISSUE TITLE
Can not run first app on Windows 10

### ISSUE THREAD

**Issue by DenisProgrammer** [facebook/react-native#28068]
Description:

    npx react-native run-android not work

React Native version:

    System:
       OS: Windows 10 10.0.18362
       CPU: (12) x64 AMD Ryzen 5 1600 Six-Core Processor
       Memory: 8.03 GB / 15.93 GB
    Binaries:
       Node: 13.8.0 - C:\Program Files\nodejs\node.EXE
       npm: 6.13.7 - C:\Program Files\nodejs\npm.CMD
    SDKs:
        Android SDK:
        API Levels: 29
        Build Tools: 29.0.2
        System Images: android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 
    Atom
       IDEs:
       Android Studio: Version  3.5.0.0 AI-191.8026.42.35.6010548
    npmPackages:
       react: 16.9.0 => 16.9.0 
       react-native: 0.61.5 => 0.61.5

## Steps To Reproduce   

1. Run "npx react-native run-android"
2. 

> $ npx react-native run-android
> info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
> Jetifier found 864 file(s) to forward-jetify. Using 12 workers...
> info JS server already running.
> info Installing the app...
> :ReactNative:Unexpected empty result of running 'node -e console.log(require('@react-native-community/cli').bin);' command.
> :ReactNative:Running 'node -e console.log(require('@react-native-community/cli').bin);' command failed.
> 
> FAILURE: Build failed with an exception.
> 
> * Where:
> Script 'D:\__DI-Group\Code\GIT_025_react_native\AppDemo\node_modules\@react-native-community\cli-platform-android\native_modules.gradle' line: 170
> 
> * What went wrong:
> A problem occurred evaluating script.
> > internal/modules/cjs/loader.js:983  throw err;  ^Error: Cannot find module '@react-native-community/cli'Require stack:- D:\__DI-Group\Code\GIT_025_react_native\AppDemo\android\[eval]    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)    at Function.Module._load (internal/modules/cjs/loader.js:862:27)    at Module.require (internal/modules/cjs/loader.js:1040:19)    at require (internal/modules/cjs/helpers.js:72:18)    at [eval]:1:13    at Script.runInThisContext (vm.js:120:20)    at Object.runInThisContext (vm.js:311:38)    at Object.<anonymous> ([eval]-wrapper:10:26)    at Module._compile (internal/modules/cjs/loader.js:1151:30)    at evalScript (internal/process/execution.js:94:25) {  code: 'MODULE_NOT_FOUND',  requireStack: [    'D:\\__DI-Group\\Code\\GIT_025_react_native\\AppDemo\\android\\[eval]'  ]}
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 1s
> 
> error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
> Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
> :ReactNative:Unexpected empty result of running 'node -e console.log(require('@react-native-community/cli').bin);' command.  
> :ReactNative:Running 'node -e console.log(require('@react-native-community/cli').bin);' command failed.
> 
> FAILURE: Build failed with an exception.
> 
> * Where:
> Script 'D:\__DI-Group\Code\GIT_025_react_native\AppDemo\node_modules\@react-native-community\cli-platform-android\native_modules.gradle' line: 170
> 
> * What went wrong:
> A problem occurred evaluating script.
> > internal/modules/cjs/loader.js:983  throw err;  ^Error: Cannot find module '@react-native-community/cli'Require stack:- D:\__DI-Group\Code\GIT_025_react_native\AppDemo\android\[eval]    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)    at Function.Module._load (internal/modules/cjs/loader.js:862:27)    at Module.require (internal/modules/cjs/loader.js:1040:19)    at require (internal/modules/cjs/helpers.js:72:18)    at [eval]:1:13    at Script.runInThisContext (vm.js:120:20)    at Object.runInThisContext (vm.js:311:38)    at Object.<anonymous> ([eval]-wrapper:10:26)    at Module._compile (internal/modules/cjs/loader.js:1151:30)    at evalScript (internal/process/execution.js:94:25) {  code: 'MODULE_NOT_FOUND',  requireStack: [    'D:\\__DI-Group\\Code\\GIT_025_react_native\\AppDemo\\android\\[eval]'  ]}
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 1s
> 
>     at checkExecSyncError (child_process.js:611:11)
>     at execFileSync (child_process.js:629:15)
>     at runOnAllDevices (D:\__DI-Group\Code\GIT_025_react_native\AppDemo\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:94:39)
>     at buildAndRun (D:\__DI-Group\Code\GIT_025_react_native\AppDemo\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:179:41)
>     at D:\__DI-Group\Code\GIT_025_react_native\AppDemo\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:133:12
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)
>     at async Command.handleAction (D:\__DI-Group\Code\GIT_025_react_native\AppDemo\node_modules\react-native\node_modules\@react-native-community\cli\build\index.js:182:9)

**Comment by GyllieGyllie** [comment]
We are facing the same issue in our deployments of our react-native apps since yesterday (shortly after the latest version deploy) and are currently trying to find a fix/work-around.

I think it's related to an issue alike #25067 where the deployment might have not worked correctly.
