### ISSUE TITLE
no such file or directory, open 'app\build\intermediates\merged_manifests\debug\AndroidManifest.xml'

### ISSUE THREAD

**Issue by MochIsrin068** [facebook/react-native#28062]
Description:

  React native project cannot running a server, after i create the new project use `npx react-native 
  init projectname` and running with `npx react-native run-android`

React Native version:

   System:
    OS: Windows 10 10.0.17134
    CPU: (4) x64 Intel(R) Core(TM) i3-7020U CPU @ 2.30GHz
    Memory: 926.31 MB / 3.88 GB
  Binaries:
    Node: 12.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 27, 28, 29
      Build Tools: 26.0.2, 27.0.3, 28.0.3, 29.0.0, 29.0.2, 29.0.3
  IDEs:
    Android Studio: Version  3.5.0.0 AI-191.8026.42.35.6010548
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5

## Expected Results

 npx react-native run-android
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 864 file(s) to forward-jetify. Using 4 workers...
info Starting JS server...
error ENOENT: no such file or directory, open 'app\build\intermediates\merged_manifests\debug\AndroidManifest.xml'. Run CLI with --verbose flag for more details.
Error: ENOENT: no such file or directory, open 'app\build\intermediates\merged_manifests\debug\AndroidManifest.xml'
    at Object.openSync (fs.js:440:3)
    at Object.readFileSync (fs.js:342:35)
    at getLaunchPackageName (D:\PROJECT LATIHAN\react_native\rn_route\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\getLaunchPackageName.js:161:33)
    at buildAndRun (D:\PROJECT LATIHAN\react_native\rn_route\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:163:63)
    at D:\PROJECT LATIHAN\react_native\rn_route\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:135:12
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async Command.handleAction (D:\PROJECT LATIHAN\react_native\rn_route\node_modules\@react-native-community\cli\build\index.js:182:9)

**Comment by sitintermilan** [comment]
i found a solution
package.json

"dependencies": {
"@react-native-community/cli-platform-android": "3.0.3" //ADD
}

**Comment by MochIsrin068** [comment]
@sitintermilan this not work for me

**Comment by ayubmm** [comment]
@MochIsrin068  Try replacing the AndroidManifest.xml from another project that is currently working. Good luck

**Comment by ayubmm** [comment]
@MochIsrin068 There is a solution from another forum =
there is a package named @react-native-community in the node_modules folder, when I used @react-native-community package of my previous project and replace, It worked perfectly

**Comment by NguyenHoangMinhkkkk** [comment]
Same issue with me, last night i did create a new project normally and it work properly but today is not.
This morning, run android with command line is broken and I've try to build new project in Android Studio and it's work.

**Comment by akikoyura** [comment]
same issue with me, I don't know how to deal with it.

**Comment by MochIsrin068** [comment]
thank you all for  this issue, I found a solution,
add in your package.json :

  "resolutions": {
    "@react-native-community/cli-platform-android": "2.9.0"
  },

**Comment by grabbou** [comment]
Fixed, please re-create the project once again.

**Comment by Vikalp19041999** [comment]
Re-creating the project is also giving the same error. Suggest something
![Screenshot from 2020-02-14 12-46-15](https://user-images.githubusercontent.com/37984055/74509628-020e5000-4f28-11ea-9e84-a683c9753f0e.png)

**Comment by grabbou** [comment]
Can you run `/home/ulcom17/Desktop/React Native/Team Manager Console/AppCode/node_modules/@react-native-community/cli/build/bin.js config` and tell us the output?

**Comment by Vikalp19041999** [comment]
There is nothing like cli/build/bin.js inside the @react-native-community folder......
![Screenshot from 2020-02-14 14-29-18](https://user-images.githubusercontent.com/37984055/74516458-67693d80-4f36-11ea-896c-826b3ef735f6.png)

**Comment by grabbou** [comment]
We are shipping a fix for you as we speak. The root cause is spaces inside your directory path.

**Comment by hieunguyendut** [comment]
Thanks @ayubmm

**Comment by Vikalp19041999** [comment]
Hey @grabbou you got anything?
