### ISSUE TITLE
Error integrating with native android project

### ISSUE THREAD

**Issue by 1nfinite** [facebook/react-native#28074]
**Description:**

 I am trying to integrating react native in existing android native project from this tutorial.
[https://facebook.github.io/react-native/docs/integration-with-existing-apps](https://facebook.github.io/react-native/docs/integration-with-existing-apps)

But android studio prompt me error as follow thus i can't build the project.
1) import com.facebook.react.common.LifecycleState; (cannot resolve symbol LifecycleState)
2) Cannot resolve method `setJSMainModulePath` (i can use with `setJSMainModuleName`)
3) Cannot resolve method `onHostPause`, `onHostResume`, `onHostDestroy`

**Comment by umarF** [comment]
same issue.. how did you fix it ?
