### ISSUE TITLE
Setting height on a TextInput causes text to cut off 

### ISSUE THREAD

**Issue by dbarner1** [facebook/react-native#28078]
Description:
- Set a height on any text input.
- Try to input text.  Notice how the text is cut off in the beginning.

React Native version:

## Steps To Reproduce
- Set a height on any text input.
- Try to input text.  Notice how the text is cut off in the beginning.

## Expected Results
- I expect the text to not cut off, or otherwise its width be affected by settings its height.

## Snack, code example, screenshot, or link to a repository:
Here's a text input with no height set, and in editing mode:
<img width="374" alt="Screen Shot 2020-02-14 at 11 00 17 PM" src="https://user-images.githubusercontent.com/23145200/74581485-e6359900-4f7d-11ea-81ce-ca068bca9b98.png">

Here's a text input with a height set, and in editing mode:
<img width="374" alt="Screen Shot 2020-02-14 at 10 59 48 PM" src="https://user-images.githubusercontent.com/23145200/74581488-e9308980-4f7d-11ea-8cc9-6eea29ac6c02.png">

**Comment by aryankush25** [comment]
You can add `padding: 0;`
And it will work fine.

**Comment by dbarner1** [comment]
Thanks @aryankush25 .  Though, from my perspective, `padding: 0` works fine when textInput is not focused, but fails to fix when it is in focus.

**Comment by thestonebro** [comment]
same problem

**Comment by dbarner1** [comment]
Still requires discussion/attention. 

I don't have the power to add/edit labels.  
Please help, stalebot. You are our only hope!

**Comment by amila93** [comment]
I'm also having the same issue

**Comment by HansLiang088** [comment]
I got this fixed after vertical center the <TextInput>

**Comment by r0gi** [comment]
I'm having the same issue on iOS. 

The only viable workaround is to set the height of the parent view. If that's not an option, then you can wrap the `TextInput` with a `View` and set the height on that, along with `alignItems: "center"` or `justifyContent: "center"` depending on the flex direction.

**Comment by shterev-soft** [comment]
I had same issue on iOS 13.7, iPhone 11 simulator and fix it by adding `width`.
On same phone with iOS 14.0 is fine without adding width.

**Comment by Nathanotal** [comment]
Setting width will solve the problem but you might run into size issues. I solved it by setting flex to 0.9.

**Comment by dgtman** [comment]
Still happening as of this date.  Adding width:'100%' does seem to "fix" it, but we are all hacking around the problem instead of getting a proper resolution.

**Comment by muhammadashfaq** [comment]
I've fixed this issue in this way. Hope it will help everyone

` <TextInput
            label="Email"
            value={email}
            mode={'outlined'}
            //mode={'flat'}
            error={emailError}
            keyboardType={'email-address'}
            autoCapitalize={'none'}
            placeholder={'Email'}
            style={styles.input}
            render={innerProps => (
              <NativeTextInput
                {...innerProps}
                style={[
                  {
                    paddingHorizontal: 12,
                    height: HP('5'),
                  },
                ]}
              />
            )}
            theme={{
              colors: {
                primary:
                  !emailError && email !== '' ? 'green' : colors.colorPrimary,
                error: colors.snackRed,
              },
            }}
            selectionColor={colors.colorPrimary}
            placeholderTextColor={colors.black}
            onChangeText={text => setEmail(text)}
          />`
          
 added this customer render
 
 ` render={innerProps => (
              <NativeTextInput
                {...innerProps}
                style={[
                  {
                    paddingHorizontal: 12,
                    height: HP('5'),
                  },
                ]}
              />
            )}`

**Comment by Gentlee** [comment]
As of android bug with cutting TextInput text fix is to set new key every time value changed programmatically.

**Comment by Soft-Gurus** [comment]
same issue is happening on iOS. setting height to a value crops the text from bottom. also padding:0 is working only when text is not focussed.

**Comment by xying9511** [comment]
set lineHeight to the text style can fix the issue

**Comment by D0nVitalio** [comment]
in addition to @aryankush25 you can also play with marginBottom and set it to 0 or negative

**Comment by sourabhkhandelwal099** [comment]
did anyone find the solution?

**Comment by fabriziobertoglio1987** [comment]
I wanted to ask if you still experience this issue. 
I'm planning to do 1-2 months of opensource and I'm preparing a list of tasks.

I have been contributing to facebook/react-native for 4 years and I specialize on the Text/TextInput components.

Thanks a lot

**Comment by Aminat00** [comment]
> I wanted to ask if you still experience this issue. I'm planning to do 1-2 months of opensource and I'm preparing a list of tasks.
> 
> I have been contributing to facebook/react-native for 4 years and I specialize on the Text/TextInput components.
> 
> Thanks a lot

I am still facing this issue, can you help me please

**Comment by garyThrels** [comment]
I had a similar issue when setting the height on the outer `style` prop. I then set the hight on the `contenStyle` instead and it seems to have fixed my issue
