### ISSUE TITLE
secureTextEntry and maxLength causes onChangeText to be triggered.

### ISSUE THREAD

**Issue by ghost** [facebook/react-native#28072]
Description:

Using conditional rendering to render two TextInputs, the first with secureTextEntry={true} and the second with maxLength={someValue}:

Whenever entering a text into the first TextInput with a length greater than the maxLength of the second TextInput, onChangeText of the second TextInput is called when it is rendered. The onChangeText of the second TextInput, gets the value entered in the first TextInput.

This issue only occurs on Android.

React Native version:

```
System:
    OS: macOS 10.15.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 4.46 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.19.0 - /usr/local/opt/node@10/bin/node
    npm: 6.13.4 - /usr/local/opt/node@10/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5
```
## Steps To Reproduce

1. npx react-native init someProjectName
2. Use the code provided below in App.js
3. Enter anything into the first TextInput with a length greater than maxLength of the second TextInput (4).
4. Press the Next button.

## Expected Results

Don't trigger the onChangeText of the second TextInput.

## Snack, code example, screenshot, or link to a repository:

```
import React, {useState} from 'react';
import {View, TextInput, Button} from 'react-native';

export default function App() {
  const [section, setSection] = useState(0);
  const [text1, setText1] = useState('');
  const [text2, setText2] = useState('');

  const renderSection = () => {
    if (section === 0) {
      return (
        <>
          <TextInput
            onChangeText={text => {
              console.log('TextInput 1: ' + text);
              setText1(text);
            }}
            value={text1}
            secureTextEntry={true}
          />
          <Button
            title="Next"
            onPress={() => {
              setSection(1);
            }}
          />
        </>
      );
    } else {
      return (
        <>
          <TextInput
            onChangeText={text => {
              console.log('TextInput 2: ' + text);
              setText2(text);
            }}
            maxLength={4}
            value={text2}
          />
          <Button
            title="Repeat"
            onPress={() => {
              setSection(0);
            }}
          />
        </>
      );
    }
  };

  return <View>{renderSection()}</View>;
}
```

**Comment by kelset** [comment]
Hello there 👋 this issue seems to have been inactive for the past few months. Because of this, it's likely that the issue is not a high priority anymore or it has been solved by OP; for these reasons, we'll close it.

But please, if it's actually still an issue with latest (RN64 at the time of writing) please comment below and we can reopen it or please send a Pull Request with a fix 😊
