### ISSUE TITLE
React Native Android - Static Resources not Showing

### ISSUE THREAD

**Issue by jacobross85** [facebook/react-native#2808]
I'm just trying to load an image as a static resource. Here is an example that gives me a blank white screen instead of the desired image. 

```
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 */

'use strict';

var React = require('react-native');
var {
  AppRegistry,
  StyleSheet,
  Text,
  Image,
  View
} = React;

var impowerz = React.createClass({
  displayName : "Login",
  render: function() {
    return (
     <View style={styles.container}>
      <Image source={require('image!bg_splash')} style={styles.bg} />
     </View>
    );
  }
});

var styles = StyleSheet.create({
  bg : {
    height: 667,
    width: 375
  },
  container: {
    flex: 1,
  },
});

AppRegistry.registerComponent('impowerz', () => impowerz);
```

I tried to console.log() the assetsRoot property in `react-native/packager/packager.js` and it came back as `/impowerz/assets/` which is where my image lives. I made a `@2x` and `@3x` as suggested [here](http://stackoverflow.com/a/29381280/1595997).

I tried using .jpg instead of .png images.  I also used Chrome Debugger and it looks like the asset is found but is just not rendering.

![screen shot 2015-09-15 at 4 22 33 pm](https://cloud.githubusercontent.com/assets/2907515/9940201/25ab7868-5d23-11e5-8275-337659b2fd0a.png)

I have also tried replacing `require('image!bg_splash')` with `{uri: 'assets/image/bg_splash.jpg'}` (with and without the ext).

I have a question open on [StackOverflow](http://stackoverflow.com/questions/32597290/react-native-android-static-resources-not-showing)

**Comment by h87kg** [comment]
Static resources are not supported now.

```
  public void setSource(@Nullable String source) {
    mUri = null;
    if (source != null) {
      try {
        mUri = Uri.parse(source);
        // Verify scheme is set, so that relative uri (used by static resources) are not handled.
        if (mUri.getScheme() == null) {
          mUri = null;
        }
      } catch (Exception e) {
        // ignore malformed uri, then attempt to extract resource ID.
      }
      if (mUri == null) {
        mUri = getResourceDrawableUri(getContext(), source);
        mIsLocalImage = true;
      } else {
        mIsLocalImage = false;
      }
    }
    mIsDirty = true;
  }
```

**Comment by dsibiski** [comment]
@h87kg That's not true. Static images are indeed supported.

You need to place your images in the `drawable-hdpi` `-xhdp`, etc folders. Don't worry what the packager told you the `assetsRoot` is. I have a project where static images work just fine.

Look at this page in the documentation: http://facebook.github.io/react-native/docs/image.html#adding-static-resources-to-your-android-app

**Comment by jacobross85** [comment]
@dsibiski Wow, I don't know how the heck I missed that part in the docs!

**Comment by dsibiski** [comment]
No problem. :+1:

**Comment by jacobross85** [comment]
@dsibiski Actually that didn't work either. I created `drawable-<qualifier>`, divided up my images to each folder and normalized the file names. However, I go an error `unknown module image!bg_splash` so instead of using `<yourapp>/android/app/src/main/res/`I put my drawable folders in `<yourapp>/assets/ like so

![screen shot 2015-09-17 at 2 25 25 pm](https://cloud.githubusercontent.com/assets/2907515/9946447/2c0a865c-5d48-11e5-8a3e-3c7bf8e8e2f6.png)

And it worked.

**Comment by dsibiski** [comment]
Very strange, mine are definitely in `res` and so are the ones in the `Movies` app.

https://github.com/facebook/react-native/tree/master/Examples/Movies/android/app/src/main/res/drawable-hdpi

Well at least it's working for you.

**Comment by mkonicek** [comment]
Thanks @dsibiski, yes please check the Movies sample app for reference. Closing, please reopen if you see more issues.

**Comment by jacobross85** [comment]
When I add new images and rebuild the app, none of the images render. Currently the only way I can fix this is by 
 1. moving all the drawable folders out of my `<approot>/assets` folder and into `<approot>/android/app/src/main/res/`
 2. rebuild, get an error `Unable to download JS Bundle`
 3. rebuild again, get same error `Unable to download JS Bundle`
 Here's the fun part
 4. move the drawable folders back to `<approot>/assets` and Reload JS to which all images are rendering just fine.
 5. Sit and ponder 'what the heck'

**Comment by baotoan1905** [comment]
I got the same issue and ponder 'what the heck' till now :(. I tried many ways but no luck. 
i'm running on android not 'ios' no the solution for ios is not work for me 
$ node_modules/react-native/packager/packager.sh --assetRoots path/to/Images.xcassets. 
Anybody know 'what the heck' with this ?

**Comment by zechau** [comment]
i missed the same issue too in Android 6.0 of Nexus5, only "source={{uri:'http://xxxxx'}}" works, any source get from require('xxx') just show me the white blank. That's weird.

**Comment by baotoan1905** [comment]
You can try this way for android

Check http://reactnative.vn/mot-so-loi-thuong-gap-khi-khoi-tao-mot-project-react-native/

**Comment by pareekkhushboo77** [comment]
you can load static images by converting images into base64 and loading base64 ..
I have used it, and its working absolutely flawless..
It is also stated in official React Native Component....

https://facebook.github.io/react-native/docs/image.html
