### ISSUE TITLE
yarn audit shows 17K + vulnerabilities

### ISSUE THREAD

**Issue by safaiyeh** [facebook/react-native#28082]
Description:

<img width="601" alt="Screen Shot 2020-02-15 at 8 31 01 AM" src="https://user-images.githubusercontent.com/8675043/74591546-b1e9c900-4fcd-11ea-9fb6-c7a21cd633e3.png">

React Native version:
on master

## Steps To Reproduce
1. run `yarn audit`

## Expected Results
Should output 0 vulnerabilities

## Snack, code example, screenshot, or link to a repository:
N/A

**Comment by medha-yadav** [comment]
I would like to work on this.Could you please guide on this.

**Comment by safaiyeh** [comment]
@medha-yadav Pick one of the vulnerabilities and investigate how to resolve it :D

**Comment by maschad** [comment]
Hey @safaiyeh thanks for pointing this out, I created a PR https://github.com/facebook/react-native/pull/28181 to address it. Let me know what you think 💃

**Comment by CoenWarmer** [comment]
Current status: @cpojer states [here](https://github.com/facebook/react-native/pull/28181#issuecomment-592215238) that upgrading of certain libraries (i.e. Lodash) that contain security advisories needs to be picked up by FB internally.

**Comment by maschad** [comment]
Can we close this @cpojer ?

**Comment by kelset** [comment]
@safaiyeh is it worth keeping this open?

**Comment by rahulnainwal107** [comment]
<img width="353" alt="Screenshot 2022-12-10 at 9 35 30 PM" src="https://user-images.githubusercontent.com/36499090/206864151-2dd485e3-861a-4435-b01f-e416df163503.png">

It looks fine now. Checking in master branch.
