### ISSUE TITLE
TextInput eats parent Pan Gestures 😋 [iOS only]

### ISSUE THREAD

**Issue by desmondmc** [facebook/react-native#28089]
Description:

If a TextInput is a child of a View with a `PanResponder`, gestures that begin in the TextInput are ignored. Even when the `PanResponder` is set to capture the Pan Gesture. (`onMoveShouldSetPanResponderCapture: () => true`). This isn't an issue on Android and as you can see from the gif, `Button`s (and other components i've tried) respect the gesture capture from the parent View.

I made a sample project that reproduces the issue: 
https://github.com/desmondmc/RNTextInputGestureBug 

![gesture-bug](https://user-images.githubusercontent.com/2319027/74611193-fc686400-50f9-11ea-9f1b-fbc8508dbece.gif)

React Native version:

```
info Fetching system and libraries information...
System:
    OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
    Memory: 291.82 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.10.1 - ~/.nvm/versions/node/v11.10.1/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.7.0 - ~/.nvm/versions/node/v11.10.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 26, 27, 28, 29
      Build Tools: 27.0.3, 28.0.3
      System Images: android-19 | Google APIs Intel x86 Atom, android-21 | Google APIs Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
```

## Steps To Reproduce

1. Implement a View with a `PanResponder`
2. Add `onMoveShouldSetPanResponderCapture: () => true` to the responder
3. Add a `TextInput` as child to a View with a PanResponder.
4. Run it and notice gestures are eaten by the TextInput.

## Expected Results

The TextInput should respect the gesture capture from the parent view

## Snack, code example, screenshot, or link to a repository:

https://github.com/desmondmc/RNTextInputGestureBug

**Comment by mzdon-ema** [comment]
Setting the `rejectResponderTermination` prop to `false` on my `TextInput` components resolved this issue for me.

**Comment by tgreco** [comment]
This is still an issue.

**Comment by stockHuman** [comment]
This is indeed still an issue.

**Comment by seanhuggins1** [comment]
Ran into this issue now
