### ISSUE TITLE
Enable the new LogBox (RN)

### ISSUE THREAD

**Issue by andrefedev** [facebook/react-native#28090]
I'm trying to enable the new LogBox in React Native (v0.62.0-rc.2), I just have to add a line to the "index.js" file but it doesn't work.

> RC2 introduces the new LogBox experience behind a feature flag. To try
> it out, add the following to your index.js file:

```
require('react-native').unstable_enableLogBox()
```

index.js
```
require('react-native').unstable_enableLogBox();

import {AppRegistry} from 'react-native';
import App from './App';
import {name as appName} from './app.json';

AppRegistry.registerComponent(appName, () => App);
```

Error output:
```
TypeError: _$$_REQUIRE(_dependencyMap[1], "react-native").unstable_enableLogBox is not a function.
```

I'm sure I'm doing something wrong, maybe it's not the right way.

**Comment by sibelius** [comment]
did you figure it out?

**Comment by hsavit1** [comment]
how do you do this in typescript?

**Comment by Sub-Zero-1** [comment]
Anybody got it to run on typescript?
import { LogBox } from 'react-native' not found in App.tsx

**Comment by fahelmoreira** [comment]
> Anybody got it to run on typescript?
> import { LogBox } from 'react-native' not found in App.tsx

Did you update your @types/react-native to version 0.63.18?

**Comment by fikrireformasi** [comment]
I think that problem same with me. My problem is using console.log but the variables doesn't print in terminal. Anyone can help me? Or this issues is my answer? Thanks before

**Comment by cretumarius** [comment]
@fahelmoreira Thanks. I was facing "YellowBox.ignorWarnings was replaced with LogBox.IgnoreLogs" and your suggestion was the solution for me.
