### ISSUE TITLE
Native FB Login, Share, Send, etc.

### ISSUE THREAD

**Issue by gilchenzion** [facebook/react-native#281]
Any chance there is either an example of or intent to create react native implementations of the FB login and/or social buttons?

**Comment by brentvatne** [comment]
@gilchenzion - I was just discussing this with some folks in IRC and learned that for the F8 app they used a RCTBridgeModule wrapper around the Facebook iOS SDK and then use the JavaScript SDK to do operations after that.

I made an example app [brentvatne/facebook-login](https://github.com/brentvatne/facebook-login) and a [blog post](http://brentvatne.ca/facebook-login-with-react-native/) too.

I can't comment on whether the team plans to make a standard implementation of this type of thing though.

**Comment by gilchenzion** [comment]
@brentvatne :+1: Thanks for the link, sounds like a great work around for now. Definitely would love to hear from the FB team still regarding standard implementation

**Comment by magus** [comment]
I've just finished working on a wrapper for the native Facebook button. Hooked up to various events as well, in addition to exposing native methods to the React component. I imagine what I've done is similar to what they used for the F8 app and would be interested to see how it compares.

https://github.com/magus/react-native-fb-login

**Comment by joewood** [comment]
@magus - this looks great. Suggest you add it to [react.parts](http://react.parts).

**Comment by soheil** [comment]
@magus magnificent! You should really do a pull request for this or add to http://react.parts/native-ios or this: http://www.reactnative.com/

**Comment by ide** [comment]
Closing this out since there are 3rd party solutions available.
