### ISSUE TITLE
Question: TroubleModuleRegistr.getEnforcing(...); Linking manager could not be found

### ISSUE THREAD

**Issue by sardarusama41062** [facebook/react-native#28100]
🚨 The issue tracker is not for questions. 🚨
I just installed react-native-maps and react-native-geolocation-services and seeing this error
"Invariant Violation: TroubleModuleRegistr.getEnforcing(...); Linking manager could not be found. Verify that a module by this name is registered in the native binary ".

RN version 0.61.4
"react-native-geolocation-service": "^4.0.0",
"react-native-maps": "^0.26.1",

The code was running on IOS but now when i tried it on android, it started showing this error.

**Comment by artmerlop** [comment]
It's an issue... @sardarusama41062 did you fixed it?
