### ISSUE TITLE
onPanResponderRelease is not working in android

### ISSUE THREAD

**Issue by Rakgowda** [facebook/react-native#28102]
Can anyone please look at my code
import React,{useState,useEffect} from 'react'
import {Text, View,StyleSheet,Button,Alert,TouchableOpacity,FlatList,Linking ,Dimensions,Image} from 'react-native';
import { Card, Badge,ListItem, Icon,Divider } from 'react-native-elements'
import { Foundation } from '@expo/vector-icons';
const oimageicon =''
import { withNavigation } from 'react-navigation';

import {RefreshControl,Animated,PanResponder,UIManager,LayoutAnimation } from 'react-native'
import SkeletonLoading from "../component/skeletonloading"

const {width} = Dimensions.get('window')

const CradDesign=({navigation,forYouNews,refreshContent})=>{

    
  const [yy,setY]=useState(0);

    const [anim] = useState(new Animated.ValueXY())
    const [pan] = useState(PanResponder.create({
        onStartShouldSetPanResponder: (evt, gestureState) => true,
        onPanResponderMove: (event,gesture)=>{
                    //    setY(Math.abs(gesture.dy)*10)hi
            console.log("hi")

            // Animated.spring(
            //     anim,
            //     {toValue:{x:0,y:gesture.dy*10}}
            // ).start()
        },
        onPanResponderRelease: (evt, gestureState) => {
            console.log("df")

        },
        
        

      }))
// console.log(pan.panHandlers)
    useEffect(() => {
        
        UIManager.setLayoutAnimationEnabledExperimental &&
  UIManager.setLayoutAnimationEnabledExperimental(true);
  LayoutAnimation.spring()
    }, [])

    function wait(timeout) {
        return new Promise(resolve => {
          setTimeout(resolve, timeout);
        });
      }

    const [refreshing, setRefreshing] = React.useState(false);

    const onRefresh = React.useCallback(() => {
        
      setRefreshing(true);
     
      refreshContent()
  
      wait(2000).then(() => setRefreshing(false));
    }, [refreshing]);

    return (forYouNews.length==0?<SkeletonLoading />
    :
   <Animated.View
   {...pan.panHandlers}
   style={anim.getLayout()}>
       
    <FlatList
    style={{backgroundColor:"white"}}
        refreshControl={
          <RefreshControl refreshing={refreshing} onRefresh={onRefresh} />
        }
    keyExtractor={(list)=>list.title}
    data={forYouNews}
    
    renderItem={({item,index })=>{
    return <Card>
        <View style={styles.textView}>
       <Text style={{fontSize:12,color:"rgb(29, 132, 242)"}}>{index+1 +". "}</Text>
       <View style={styles.insideText}>
       <Badge value={item.source.name} status="primary" />
          
      
       <Text style={styles.text}  onPress={() => {
           //on clicking we are going to open the URL using Linking
           navigation.navigate('webView',{urlLink:item.url})
         }}>{item.title}</Text>
       
       </View>
       <View>
     
       <Image style={styles.img} source={{uri:item.urlToImage==null?oimageicon:item.urlToImage}}></Image>
       {/* <Foundation name="page-copy" style={styles.fullcoverrage} ></Foundation> */}
       </View>
        
       </View> 
       
    </Card>
     
        
    }}
    >
    </FlatList> 
    </Animated.View>

    )
}

const styles = StyleSheet.create({ 
    text:{
       
        alignItems:"flex-start",
        width:width-150,
        fontSize:17,
        alignSelf:"flex-start",
       marginTop:10,
        alignSelf:"center"
        

    },
    fullcoverrage:{
        fontSize:20,
        color:"rgb(29, 132, 242)",
        alignSelf:"flex-end",
       
        // marginTop:10
        

    },
    textView:{
    
        flexDirection:"row",
        left:-15
    },
    img:{
        width:90,
        height:100,
        borderRadius:15,
        borderColor:"rgb(29, 132, 242)",
        borderWidth:3
    },
    insideText:{
        alignItems:"flex-start"
    },
    sourcename:{
        
        backgroundColor:"black",
        color:"white",
        fontSize:12,
        
      
        
    },
    skeletonText:{
        width:200,
        height:10
    }
});

export default withNavigation(CradDesign)

**Comment by KingAmo** [comment]
same problem here

**Comment by Oliverxyj123** [comment]
> same problem here

replace with onPanResponderEnd
