### ISSUE TITLE
Migrate off of old context APIs

### ISSUE THREAD

**Issue by TheSavior** [facebook/react-native#28103]
We want to get rid of our usage of the `prop-types` package. The last remaining usage of this is a couple of old components that use [the old React context API](https://reactjs.org/docs/context.html#classcontexttype). We need to migrate these components to use the modern `React.createContext` API.

The components using the old context API are:
- ~~[VirtualizedList](https://github.com/facebook/react-native/blob/master/Libraries/Lists/VirtualizedList.js#L1979)~~
- ~~[Modal](https://github.com/facebook/react-native/blob/master/Libraries/Modal/Modal.js#L162-L166) (@satya164)~~
- [AppContainer](https://github.com/facebook/react-native/blob/master/Libraries/ReactNative/AppContainer.js#L49-L59) (@safaiyeh)
- ~~[Incremental](https://github.com/facebook/react-native/blob/master/Libraries/Experimental/Incremental.js#L109-L117) (@venits)~~

For more information about the old API and how to migrate to the new API you can check out the React docs for Context: https://reactjs.org/docs/context.html#classcontexttype

If we are able to remove the usage of prop-types from React Native we should be able to substantially lower the bundle size of React Native. We'd love your help!

**Comment by Naturalclar** [comment]
I'd love to help out! Could I work on `Modal`?

**Comment by venits** [comment]
I would love to take care of `Incremental` :)

**Comment by mikaoelitiana** [comment]
hey there, I can check virtualizedlist

**Comment by thymikee** [comment]
@Naturalclar @mikaoelitiana they're all yours to take :)

**Comment by mikaoelitiana** [comment]
@thymikee thanks, I am already working on `VirtualizedList`, the module is quite big and I try to make sure I am doing things the right way

**Comment by TheSavior** [comment]
It looks like Modal actually only uses the VirtualizedList Context and AppContainer Context, it doesn't have its own context. So we need to get the VirtualizedList and AppContainer ones done first.

**Comment by mikaoelitiana** [comment]
So this means these contexts need to be exported, right?

**Comment by TheSavior** [comment]
Yeah, the root tag context is already exported, unstable_RootTagContext, the VirtualizedList one can be exported as a static property on VirtualizedList: VirtualizedList.Context

**Comment by thymikee** [comment]
@TheSavior is the VirtualizedList context used internally at FB? It looks like Modal overwrites the `virtualizedList` context with null, so it doesn't propagate further and there are no consumers of this inside RN codebase. So, if there are no internal FB components using this context, we could maybe kill it entirely? But I guess there are 😄

**Comment by TheSavior** [comment]
Yeah, these contexts are all used fairly heavily. Any kind of portal type thing would use it like Modal or BottomSheet.

**Comment by joelbrewer** [comment]
It appears all of the tasks on this issue have been claimed? Looking for my first RN issue to help out on :)

**Comment by awalmubarak** [comment]
> It appears all of the tasks on this issue have been claimed? Looking for my first RN issue to help out on :)

It appears so. I wanted to work on this but i'll have to move on to another issue

**Comment by thymikee** [comment]
VirtualizedList was migrated in https://github.com/facebook/react-native/commit/7bd694fc6f4bb027b6d7ee04034cad41a43e5695. So only AppContainer left now

**Comment by gdstewart** [comment]
Is AppContainer still taken? Or could I give it a try?

**Comment by MayheMatan** [comment]
can i give appContainer a try too?

**Comment by gittysachin** [comment]
If no one is working on AppContainer, then I'd like to take it up. Thanks!

**Comment by mohamadhamad300** [comment]
do you can give me  simple task  to contribute  it
