### ISSUE TITLE
> ReactNativeModules$_generatePackagesFile_closure3

### ISSUE THREAD

**Issue by SERGEIBARATS** [facebook/react-native#28108]
Description:

 Hello,
I am trying to run project on android and it failed with this issue
error Failed to install the app. Make sure you have the Android development environment set up: 
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* Where:
Script '/Users/sergeibarats/leumicardvgc/node_modules/@react-native-community/cli-platform-android/native_modules.gradle' line: 130

* What went wrong:
Execution failed for task ':app:generatePackageList'.
> ReactNativeModules$_generatePackagesFile_closure3
### 

React Native version: 0.61.5

**Comment by stefanvesca** [comment]
+1

**Comment by Gutyn** [comment]
anything? @SERGEIBARATS

**Comment by personapp** [comment]
+1

**Comment by tapz** [comment]
Started to occur also with `react-native run-android`. Earlier only with `./gradlew assembleTulkaRelease`. With assemble `--scan` helped, but with react-native there is no such option.

**Comment by tapz** [comment]
Is there a way to pass arguments to gradlew from react-native? I could live with this Gradle mess by using --scan.

**Comment by dhawal1248** [comment]
+1

**Comment by kemvrn** [comment]
```android./gradlew assembleDebug``` helped me

**Comment by resting** [comment]
Had the same problem while upgrading to 0.63.3.
Turn out it was due to syntax error in MainApplication.java while copying the diff.
Check all the functions are closed properly.
`./gradlew assembleDebug` --scan helped showed more details
