### ISSUE TITLE
Platform.OS returns the wrong OS

### ISSUE THREAD

**Issue by pahferreira** [facebook/react-native#28109]
Description:

   I'm facing problems when tried to use react-native-camera. My code was triggering iOS methods even in Android, so, when I went deep into the RNCamera component and printed the Platform Object, I saw that it was returned iOS, even when I build it on Android.

React Native version:

    System:
    OS: Linux 4.15 elementary OS 5.0 Juno
    CPU: (4) x64 Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
    Memory: 228.79 MB / 15.62 GB
    Shell: 5.4.2 - /usr/bin/zsh
  Binaries:
    Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
    Yarn: 1.19.1 - /usr/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
  SDKs:
    Android SDK:
      API Levels: 23, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1

## Steps To Reproduce

    Provide a detailed list of steps that reproduce the issue.
    Issues without reproduction steps or code are likely to stall.

    I can't give too many details on the project, but in general, is like that above

1. Created a project and Build it in Android
2. Latter I managed to build it to iOS
3. Then my project OS is always iOS in both platforms

## Expected Results

    Recognization of Android Platform 

## Snack, code example, screenshot, or link to a repository:

<img src="https://i.imgur.com/pcotx8N.png">

**Comment by ShutoYamada** [comment]
I also faced the same problem.
In my case, the cause was a source code mistake.

```javascript
import { Platform } from 'react-native';

if(Platform.OS = 'ios') { // <-- Platform.OS changed to 'ios'!!
    // Processing for iOS...
}
```
