### ISSUE TITLE
react-cli init should declare SYSTEM_ALERT_WINDOW

### ISSUE THREAD

**Issue by mping** [facebook/react-native#2811]
When generating a new project through `react-native init ... ` some permissions are missing from the android manifest. 

Relevant PR: https://github.com/facebook/react-native/pull/2810

**Comment by mkonicek** [comment]
Does this cause any issues? Both permissions should already be present, see https://github.com/facebook/react-native/pull/2810

Please reopen if that's not the case.

**Comment by mping** [comment]
Yeah its working now, dunno what happened. My local manifest didn't have any permissions when I tried it through the generator.

Thanks.
