### ISSUE TITLE
Push notification token getting stopped for sometimes in iOS

### ISSUE THREAD

**Issue by nagaraju1121** [facebook/react-native#28110]
Description:

  I am using expo ejected react-native-cli and developing app for both android and iOS.

I have integrated below push notification package through npm in my project.
https://github.com/zo0r/react-native-push-notification#readme

React Native version: "0.61.4",

System:

    OS: macOS Mojave 10.14.5

    CPU: (4) x64 Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz

    Memory: 975.43 MB / 4.00 GB

    Shell: 3.2.57 - /bin/bash

  Binaries:

    Node: 12.13.0 - /usr/local/bin/node

    npm: 6.13.7 - /usr/local/bin/npm

  SDKs:

    iOS SDK:

      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1

  IDEs:

    Android Studio: 3.5 AI-191.8026.42.35.5977832

    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild

  npmPackages:

    react: ~16.9.0 => 16.9.0 

    react-native: ~0.61.4 => 0.61.5 

  npmGlobalPackages:

    react-native-cli: 2.0.1

**Comment by hramos** [comment]
Can you fill out the rest of the issue template? It's not clear from the description what issue you're reporting or how to reproduce it.
