### ISSUE TITLE
error Unrecognized command "run-android". info Run "react-native --help" to see a list of all available commands.

### ISSUE THREAD

**Issue by ManishStark** [facebook/react-native#28116]
i have facing the issue while running the React-Native project in my Android physical Device... why this occurred can anyone please tell tell me with solution

**Comment by marcosrodriguezseminole** [comment]
Are you in the root of your project (not the android folder)?

**Comment by ManishStark** [comment]
yes... all works perfectly fine but since last week.. i am getting an error
that " react-native run-android" unrecognized ..what should i do please
help me
