### ISSUE TITLE
axios/fetch request stuck with no error or no response on IOS only 

### ISSUE THREAD

**Issue by mohanagy** [facebook/react-native#28111]
Description:
sending a request with **Axios or fetch** in IOS not work and it doesn't matter if the API is `HTTPS` or `HTTP` 
no error reaches the catch or no response received 
also no errors, only warnings 
```
2020-02-18 21:31:21.096 [warn][tid:com.facebook.react.NetworkingQueue][RCTEventEmitter.m:53] Sending `didReceiveNetworkResponse` with no listeners registered.
2020-02-18 21:31:21.100 [warn][tid:com.facebook.react.NetworkingQueue][RCTEventEmitter.m:53] Sending `didReceiveNetworkData` with no listeners registered.
2020-02-18 21:31:21.100 [warn][tid:com.facebook.react.NetworkingQueue][RCTEventEmitter.m:53] Sending `didCompleteNetworkResponse` with no listeners registered.
```
this only happin with IOS , android works fine 

React Native version:

```
System:
    OS: macOS 10.15.3
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 40.29 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.15.0 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.7 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-28 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5977832
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.12.0 => 16.12.0
    react-native: 0.61.5 => 0.61.5
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

## Steps To Reproduce

1. just send any request to any API 
2.

## Expected Results

get a result or even error from the API 

## Snack, code example, screenshot, or link to a repository:
the app stuck here because I'm waiting for a result or error from the request
![image](https://user-images.githubusercontent.com/11216054/74772004-df699780-5297-11ea-8dab-ab831c4b9e7f.png)

my simple function 
```
export const checkAuth = (accessToken) => async (dispatch, getState) => {
  try {
    const response = await fetch('https://www.google.com', {
      method: 'GET',
      headers: {
        // Accept: 'application/json',
        // Authorization: `Bearer ${accessToken}`,
      },
    })
    const json = await response.json()
    const { error } = json

    if (error) {
      return false
    }
    return true
  }
  catch (error) {
    return false
  }
}
```
my info.plist 
![image](https://user-images.githubusercontent.com/11216054/74772184-32434f00-5298-11ea-8ef9-6abc65d9a3f8.png)

**Comment by mohanagy** [comment]
@hramos  why do you think this is a question and not a bug?

**Comment by GoktuqCan** [comment]
I'm also getting this error with iOS in release build. I'm trying to send a request to https.
Weirdly if i turn off then turn on my iphone's wi-fi requests starts working.
But after a while requests keep failing again.
I think this issue needs to be reopened.

**Comment by yll090** [comment]
I've also received issues for an app I'm working on for this exact behavior -- app runs fine, then randomly the first request that needs to be done by the app just hangs and user has to force close the app. Happens only on a release version of the app, so I've used logs to come this far. Has anyone had any luck yet? @mohanagy @GoktuqCan  ?

**Comment by jonasgroendahl** [comment]
i have the same issue, every http request gets stuck, happened after struggling to get the metro bundler to load the app

**Comment by Lastvegac** [comment]
Same problem, any solutions?

**Comment by flavio80s** [comment]
I have the same problem, but with axios.post. Any solution?

**Comment by mohanagy** [comment]
not for me

**Comment by jbouaziz** [comment]
This is still happening with expo 40 and axios as the main dependencies.
I tested it with iOS 14 and it just fails every time over cellular network but works great over wifi. It was also tested on iOS 12 which works great over 4G.

Did anyone find a solution? I'll dig into the server configuration related to ipv6, it could be a lead.

**Comment by GoktuqCan** [comment]
@jbouaziz Adding/Editing **NSAppTransportSecurity** key in **Info.plist** file helped for me
```
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
		<key>NSExceptionDomains</key>
		<dict>
			<key>www.yourdomain.com</key>
			<dict>
				<key>NSExceptionAllowsInsecureHTTPLoads</key>
				<true/>
			</dict>
			<key>localhost</key>
			<dict>
				<key>NSExceptionAllowsInsecureHTTPLoads</key>
				<true/>
			</dict>
		</dict>
	</dict>
```

**Comment by jaroslav009** [comment]
same issue

**Comment by jonasgroendahl** [comment]
seems to be network related, try changing between wired, wifi and 4g. google dns gave some problems for me...

**Comment by EKT2000** [comment]
Still having the same issue, but it does not happen on every ios device though... Connecting via WIFI works fine, but using mobile network results no response. The endpoint is using https so i have no clue what could be the issue
