### ISSUE TITLE
Switching between numeric and alphanumeric TextInput changes keyboard layout

### ISSUE THREAD

**Issue by PiPoutch** [facebook/react-native#28122]
Description: 
Any application that has several `TextInput` with at least one that includes `keyboardType="numeric"` will change the iOS keyboard layout when returning to a TextInput that shows an alphanumeric keyboard (i.e. `keyboardType="default"`) after focusing a numeric `TextInput`.
This behavior occurs when the user has two keyboards layouts set up in iOS, with at least one of them being English (United States) and with the other one (in my case, French (France), but I also tested Spanish (Spain) ) being on top of the layout list in the iOS settings.
It seems that this problem exists only if the secondary keyboard's layout is English (United States).

![67E13A31-06DE-4E91-9E56-C2555B93CD20](https://user-images.githubusercontent.com/8088969/74828834-17acbc80-5310-11ea-87f5-74cc98dfcc45.png)

The problem seems to also occur with `keyboardType="number-pad"`, `keyboardType="decimal-pad"` and `keyboardType="phone-pad"`

When focusing a `TextInput` that uses one of these mode, the iOS device logs : `Can't find keyplane that supports type 8 for keyboard iPhone-PortraitChoco-DecimalPad; using 25727_PortraitChoco_iPhone-Simple-Pad_Default`

React Native version: 0.61.5

System:
    OS: macOS 10.15.2
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Memory: 22.48 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.13.7 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5977832
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    create-react-native-app: 2.0.2
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7

## Steps To Reproduce

1. Create new blank react-native application
2. In a view, have two `TextInput`, one that has `keyboardType="default"`, one that has `keyboardType="numeric"`
3. Run app on iOS 13.3 device, with several keyboard layouts. In order, layouts should be 1) French (France), 2) Emoji, 3) English (United States)
4. Select the default field, check that layout starts with AZERTY.
5. Focus the numeric field
6. refocus the default field. Layout is now QWERTY

## Expected Results

Layout should stay the same in-between identical keyboardType fields

## Snack, code example, screenshot, or link to a repository:

After a `react-native init`, replace App.js content with:

```
import React from 'react';
import {SafeAreaView, TextInput} from 'react-native';

const App: () => React$Node = () => {
  return (
    <SafeAreaView>
      <TextInput style={{color: 'black'}} keyboardType="default">
        TEST
      </TextInput>
      <TextInput style={{color: 'black'}} keyboardType="decimal-pad">
        1234
      </TextInput>
    </SafeAreaView>
  );
};

export default App;

```

**Comment by semcelik** [comment]
any update on this issue?

**Comment by PiPoutch** [comment]
None. I started building a new app in-between and will try to see if there are any workarounds when coming to that part again. I will try to use library components to see if they have the same problem, and if they don't I'll try to understand why.

**Comment by semcelik** [comment]
i think it might be a problem about ios version. I run into this problem in IOS 13.1 but it worked perfectly in IOS 12.2

**Comment by morgane1806** [comment]
I finally found a solution that worked for me 😁

### The issue
There is an issue on IOS, when you use a numeric keyboard, it changes the keyboard language and **uses app default language** : variable `CFBundleDevelopmentRegion`
--> In my case CFBundleDevelopmentRegion was "en", that's why it transformed azerty keyboard to qwerty keyboard

### Solution
Solution that worked for my : **Remove** the following 2 lines in info.plist
```
<key>CFBundleDevelopmentRegion</key>
<string>en</string>
```

**Comment by PiPoutch** [comment]
That solution works for me as well, thanks! As it seems to be strictly iOS-related, I will close this issue.
