### ISSUE TITLE
[iOS] Thread 1: signal SIGABRT when running on iPhone 8 iOS 13.3.1

### ISSUE THREAD

**Issue by duyanhv** [facebook/react-native#28127]
Description:

    The app works fine on simulator (iPhone 8 iOS 13.3.1)   but when I used Xcode to built and ran on a real device (iPhone 8 iOS 13.3.1),   the app crashed on splash screen with Thread 1: signal SIGABRT
<img width="853" alt="Screen Shot 2020-02-19 at 11 49 41 PM" src="https://user-images.githubusercontent.com/20358572/74855371-2aa4a880-5373-11ea-97a4-b977eb461f1a.png">

With the error in the debug console: 
<img width="488" alt="Screen Shot 2020-02-19 at 11 55 05 PM" src="https://user-images.githubusercontent.com/20358572/74855478-56279300-5373-11ea-9927-672cc1691327.png">

React Native version:

    System:
    OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 451.29 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.14.1 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 24, 27, 28, 29
      Build Tools: 28.0.3, 29.0.1
      System Images: android-24 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmGlobalPackages:
    react-native-vector-icons: 6.6.0

## Steps To Reproduce

    Provide a detailed list of steps that reproduce the issue.
    Issues without reproduction steps or code are likely to stall.

1. react-native run-ios --device 'name of the device'

## Expected Results

    The app running without thread 1 SIGABRT

**Comment by safaiyeh** [comment]
Hi @duyanhv thank you for the issue. We need a couple things from you to investigate more.

1. Run `react-native info` and paste the output in your issue.
2. Verify this happens on the latest version of RN
3. Provide a reproducible Snack or repository that demonstrates this issue.
