### ISSUE TITLE
Jest preprocessor does not correctly hoist jest.mock calls

### ISSUE THREAD

**Issue by nwalters512** [facebook/react-native#28129]
## Description

Using the Jest preprocessor provided by React Native (from `jest/preprocessor.js`) does not correctly hoist calls to `jest.mock()`. Using this preprocessor is currently the recommended way to use Jest with React Native: https://github.com/facebook/jest/blob/3d09c5c0c0f336af2e30f5e2e0252913a5cb36dd/examples/react-native/jest.config.js

This is deliberately duplicating #20614 (and possibly #19859, although it's less clear if that is related). They were closed with suggested workarounds, but this is a bug with code provided by React Native and should still be fixed here.

React Native version:

```
System:
    OS: macOS Mojave 10.14.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 3.05 GB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.18.1 - /usr/local/opt/node@10/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/opt/node@10/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

## Steps To Reproduce

I've created a self-contained minimal reproduction at https://github.com/nwalters512/react-native-jest-hoisting-bug. After cloning the repository, follow these steps to reproduce both the bug and the expected behavior.

1. Run `yarn` to install dependencies.
2. Run `yarn test`. This will execute the tests defined in `src/index.test.js` with React Native's Jest preprocessor.
3. Observe how the test fails with the exception thrown from `src/example.js`. This is unexpected, since the implementation of that function should be mocked.
4. Delete `jest.config.js` to turn off the `react-native` preset and use the standard `babel-jest` transformer.
5. Run `yarn test` again.
6. Observe how the test now passes. This is because the call to `jest.mock` is correctly hoisted to the top of the file, so the function from `src/example.js` is now properly mocked.

## Proposed solution

Adding [`babel-plugin-jest-hoist`](https://www.npmjs.com/package/babel-plugin-jest-hoist) to the list of Babel plugins in `jest/preprocessor.js` should fix this problem. I'm happy to open a PR with this change if maintainers think this is the right solution.

**Comment by VitorBrangioni** [comment]
Same issue. Any solution?
