### ISSUE TITLE
[ISSUE] Error fetching https url on Android 4.4.4

### ISSUE THREAD

**Issue by fgagneten** [facebook/react-native#28143]
Description:

 I'm having an android native error when I try to fetch some json data from my remote api, using HTTPS. The error only occurs in my Android 4.4.4 after upgrading to RN 0.61 (Worked with RN 0.59). I found a workaround implementing conscrypt (see details below) but I would like to know if there is any possibility to find a solution without using my workaround..

React Native version:

    info Fetching system and libraries information...
    System:
        OS: Windows 10 10.0.18363
        CPU: (4) x64 Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
        Memory: 3.13 GB / 15.88 GB
      Binaries:
        Node: 12.9.0 - C:\Program Files\nodejs\node.EXE
        Yarn: 1.12.3 - C:\Users\Faustino\AppData\Roaming\npm\yarn.CMD
        npm: 6.13.6 - C:\Users\Faustino\AppData\Roaming\npm\npm.CMD
      SDKs:
        Android SDK:
          API Levels: 23, 24, 25, 26, 27, 28, 29, 8
          Build Tools: 19.1.0, 20.0.0, 21.1.1, 21.1.2, 22.0.0, 22.0.1, 23.0.0, 23.0.1, 23.0.2, 23.0.3, 24.0.0, 24.0.1, 24.0.2, 24.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.1, 27.0.2, 27.0.3, 28.0.0, 28.0.0, 28.0.0, 28.0.2, 28.0.3, 29.0.2
          System Images: android-24 | Android Wear ARM EABI v7a, android-24 | Intel x86 Atom_64, android-24 | Google Play Intel x86 Atom, android-25 | Android TV Intel x86 Atom, android-25 | Google APIs ARM 64 v8a, android-25 | Google APIs ARM EABI v7a, android-25 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom_64, android-Q | Google APIs Intel x86 Atom
          Android NDK: 21.0.6113669
      IDEs:
        Android Studio: Version  3.5.0.0 AI-191.8026.42.35.6010548
      npmPackages:
        react: 16.9.0 => 16.9.0
        react-native: 0.61.5 => 0.61.5

## Steps To Reproduce

1. Just running my app with an Android 4.4.4 Sony Xperia E2104 and fetching some https request to my server (Connection with TLS 1.2. Issuer: Let's Encrypt Authority X3)

It is only happens with my Android 4.4.4 device.

## Expected Results

    Get te json result.

I can solve the problem implementing the following line in my build.gradle (app)

        implementation 'org.conscrypt:conscrypt-android:2.2.1'

And also adding in onCreate method of the MainApplication

          Security.insertProviderAt(new org.conscrypt.OpenSSLProvider(), 1);

Using React Native 0.59 worked with this phone. After upgrading to RN 0.61 stop working.

Thanks!

##

**Comment by francozini2** [comment]
I have the same error!
