### ISSUE TITLE
Malformed calls from JS:field sizes are different.

### ISSUE THREAD

**Issue by kirandesai303** [facebook/react-native#28146]
When I pass the  ArrayBuffer data or Uint16Array to native ReadableArray on Android at that time get these error.

    const buff = new Uint16Array(result);
    Record.playSound(buff);

  @ReactMethod
  public void playSound(ReadableArray  audioTrack)

![Screenshot_1582279451](https://user-images.githubusercontent.com/33322714/75024747-fa1e5500-54bf-11ea-8d0c-731065d9e36a.png)

**Comment by hyochan** [comment]
Came from #23835. I've experienced the same issue in RN `0.63.4`. I've resolved this issue when I removed `fbt` translation in `TextInput` `placeholder`. `value` is ok!

I just wanted to share the resolution.

**Comment by SudoPlz** [comment]
I just posted a long answer here about what's happening and how to troubleshoot that: https://stackoverflow.com/a/67100389/1658268
