### ISSUE TITLE
Can't swipe a FlatList inside a TouchableWithoutFeedback

### ISSUE THREAD

**Issue by tankpower1** [facebook/react-native#28148]
Hello,
I have a horizontal FlatList wrapped with a TouchableWithoutFeedback and every time i try to swipe horizontally it instead activates the Touchable's onPress. How can one fix this bug?

React Native version:

    0.61.5

**Comment by Djunnni** [comment]
refer to #14155

**Comment by safaiyeh** [comment]
Thank you for the issue @tankpower1, we need more information to debug this.

• Could you make sure to follow the full issue template?
• Could you provide a Snack or repo that demonstrates this bug?
