### ISSUE TITLE
App crash on splash screen in iOS (Xcode) on react-native (0.61.5) version

### ISSUE THREAD

**Issue by imvishalsingh** [facebook/react-native#28159]
package.json
{
  "name": "AwesomeProject",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "react": "16.9.0",
    "react-native": "0.61.5"
  },
  "devDependencies": {
    "@babel/core": "^7.8.4",
    "@babel/runtime": "^7.8.4",
    "@react-native-community/eslint-config": "^0.0.7",
    "babel-jest": "^25.1.0",
    "eslint": "^6.8.0",
    "jest": "^25.1.0",
    "metro-react-native-babel-preset": "^0.58.0",
    "react-test-renderer": "16.9.0"
  },
  "jest": {
    "preset": "react-native"
  }
}

Output
![Untitled](https://user-images.githubusercontent.com/6008292/75104656-d3802b80-5631-11ea-952e-c30a6beffc6f.gif)

**Comment by AnuragVadd** [comment]
Having the same issue here. This happens when using CLI after installing a few navigator libraries even on creating a new project (without expo).
