### ISSUE TITLE
MyApp got lots of crash  in JSCRuntime::evaluateJavaScript , please help me

### ISSUE THREAD

**Issue by hgxpy** [facebook/react-native#28154]
Description:
My app in Applestore got lots of crash when app lauch.   I just init a bridge in globalQueue ，and when the bridge excute bundle source, it crash occasionally .

crash in com.facebook.react.JavaScript,  the stack is not all the same
![image](https://user-images.githubusercontent.com/3425718/75089600-68811700-5595-11ea-9ce4-4490311dcfc3.png)

![image](https://user-images.githubusercontent.com/3425718/75089578-26f06c00-5595-11ea-9e30-10ea849832fb.png)

![image](https://user-images.githubusercontent.com/3425718/75089636-f230e480-5595-11ea-9e98-6b27d8f6db48.png)

![image](https://user-images.githubusercontent.com/3425718/75089653-20aebf80-5596-11ea-8ee2-cc0b681a0a93.png)

![image](https://user-images.githubusercontent.com/3425718/75089659-2a382780-5596-11ea-875e-1ca153f2aece.png)

React Native version: 0.61.2

  

## Steps To Reproduce

Just get crash in AppleStore report, I can reproduce myself

1. when RN bridge execute the bundle source, it occasionally crash。please help me

**Comment by hramos** [comment]
Hi, can you make sure the issue template is properly filled out? Thanks
