### ISSUE TITLE
ScrollView doesn't take rejection well - scrolls anyway: With single scrollview

### ISSUE THREAD

**Issue by Joshuabaker2** [facebook/react-native#2815]
So there appear to have been issues raised for this but many of them seem to be closed/inactive, and deal with nested listviews.

I have a vertical listview which renders rows that have a swipe-to-delete functionality (my own implementation). The swipe-to-delete uses a panresponder to capture the swiping action. I set 
``` onPanResponderTerminationRequest: () => false``` as one of the props for the panresponder, which works for stopping my other animations. However, as a horizontal swipe-to-delete motion occurs, if any vertical movement occurs in the gesture, the listview will begin scrolling and a warning in the console appears saying that the scrollview doesn't take rejection well. 

Is there a setting I can change to stop this behaviour, or do I have to do a workaround where I have to set ```scrollEnabled``` to false during my horizontal swipe?

**Comment by doochik** [comment]
I have the same problem. Do you know workarounds?

**Comment by IanVS** [comment]
I've got a similar problem, whereby I have a scrollview which I do not want to allow to scroll while swiping.  I've set the `scrollEnabled` to false when swiping, but the `onScroll` is still firing and it causes some jankiness in the experience.  It seems that `scrollEnabled` is not always respected.

**Comment by aleclarson** [comment]
A `ScrollView` based in Javascript would fix this. Since `Animated` will soon support native animations, this is feasible.

**Comment by Obooman** [comment]
@aleclarson Could you please be more clear? I have the same problem which really annoying me.Thanks😭.

**Comment by aleclarson** [comment]
I think Facebook is working on a native solution for this (as evidenced here: 5c1ac2a).

Right now, React Native's JS `ScrollView` wraps around the native `UIScrollView`. If the `ScrollView` was written from the ground-up in JS, it could partake in the JS responder system. That would effectively avoid this error. But it's up to Facebook to decide if a JS-based `ScrollView` is feasible.

**Comment by geirman** [comment]
@facebook-github-bot stack-overflow

**Comment by geirman** [comment]
For the JS only implementation, check product pains and either vote up an existing or add a new request.
