### ISSUE TITLE
Could not connect to development server

### ISSUE THREAD

**Issue by abdulbasit1248** [facebook/react-native#28152]
Description:
Could not connect to development server:
Ensure the following 
-Node server is running & available on the same network -run npm start from react native root.
-Node server URL is correctly setup in app delegate
-wifi is enabled & connected to same network as node server

React Native version:
"react-native": "0.61.5",
"node":  "10.14.1"

## Steps To Reproduce
1.Running app using Xcode & using iphone X simulator
2.Not testing the app on any physical device
3.Changed the ports as well for the specific project.
4. But metro bundler not working

## Expected Results

Metro bundler should connect and app should run

## Snack, code example, screenshot, or link to a repository:
<img width="314" alt="Screenshot 2020-02-21 at 10 06 02 PM" src="https://user-images.githubusercontent.com/43878789/75089091-192bee00-5577-11ea-8628-84aa5b70d805.png">
elp/mcve

**Comment by abdulbasit1248** [comment]
I tried multiple solutions for the above issue.
1) rm -rf node_modules/ && rm -rf yarn_lock/ && yarn install && cd ios && pod install
2) checking out the specific process & cancel that thread/process by specifying the p_id
3) nmp audit --fix

None of the above solution worked for me except this command
<img width="809" alt="Screenshot 2020-02-22 at 1 25 16 PM" src="https://user-images.githubusercontent.com/43878789/75089127-8770b080-5577-11ea-8bba-55d5308867fa.png">

After all you have to do 
yarn add react-native-gesture-handler react-native-reanimated react-native-screens

Close bundler & shift +cmd + k on xcode and run the app by cmd + R

**Comment by ardyfeb** [comment]
> You can access the developer menu by shaking your device or by selecting "Shake Gesture" inside the Hardware menu in the iOS Simulator. You can also use the ⌘D keyboard shortcut when your app is running in the iOS Simulator, or ⌘M when running in an Android emulator on Mac OS and Ctrl+M on Windows and Linux. Alternatively for Android, you can run the command adb shell input keyevent 82 to open the dev menu (82 being the Menu key code).


After dev menu open, press `Settings` -> `Debug server host & port for device` fill with `<your computer ip>:8081` then reload

**Comment by skaynetmen** [comment]
**Description:**
I have the same problem.
Could not connect to development server:

React Native version:
"react-native": "0.62.0"
node --version
v10.18.1
Xcode Version 11.4 (11E146)
Mac OS Catalina 10.15.3

**Steps To Reproduce**
1. npx react-native init newProject
2. cd newProject
3. npx react-native start
4. npx react-native run-ios

**Expected Results**
Metro bundler should connect and app should run

**Snack, code example, screenshot, or link to a repository:**
![Screenshot 2020-03-29 at 20 53 22](https://user-images.githubusercontent.com/5357263/77856416-99d9ac00-71ff-11ea-942c-c2cf2b7cc7a1.png)

> sudo lsof -i :8081
COMMAND     PID      USER   FD   TYPE            DEVICE SIZE/OFF NODE NAME
Google      901 skavenger   23u  IPv6 0x1c2e5b32b49e681      0t0  TCP localhost:49841->localhost:sunproxyadmin (ESTABLISHED)
node      24899 skavenger   24u  IPv6 0x1c2e5b32b4a29e1      0t0  TCP *:sunproxyadmin (LISTEN)
node      24899 skavenger   31u  IPv6 0x1c2e5b32b49eca1      0t0  TCP localhost:sunproxyadmin->localhost:49836 (ESTABLISHED)
node      24899 skavenger   32u  IPv6 0x1c2e5b32b4a1781      0t0  TCP localhost:sunproxyadmin->localhost:49837 (ESTABLISHED)
node      24899 skavenger   33u  IPv6 0x1c2e5b32b49f8e1      0t0  TCP localhost:sunproxyadmin->localhost:49838 (ESTABLISHED)
node      24899 skavenger   39u  IPv6 0x1c2e5b32b4a1161      0t0  TCP localhost:sunproxyadmin->localhost:49841 (ESTABLISHED)
newProjec 25153 skavenger   25u  IPv4 0x1c2e5b321f07241      0t0  TCP localhost:49836->localhost:sunproxyadmin (ESTABLISHED)
newProjec 25153 skavenger   26u  IPv4 0x1c2e5b321f07241      0t0  TCP localhost:49836->localhost:sunproxyadmin (ESTABLISHED)
newProjec 25153 skavenger   29u  IPv4 0x1c2e5b3222604e9      0t0  TCP localhost:49837->localhost:sunproxyadmin (ESTABLISHED)
newProjec 25153 skavenger   30u  IPv4 0x1c2e5b3222604e9      0t0  TCP localhost:49837->localhost:sunproxyadmin (ESTABLISHED)
newProjec 25153 skavenger   31u  IPv4 0x1c2e5b321f4f879      0t0  TCP localhost:49838->localhost:sunproxyadmin (ESTABLISHED)
newProjec 25153 skavenger   32u  IPv4 0x1c2e5b321f4f879      0t0  TCP localhost:49838->localhost:sunproxyadmin (ESTABLISHED)

**Comment by JBerendes** [comment]
Having the exact same problem.

**Comment by JBerendes** [comment]
#28786 Might be the same issue

**Comment by JBerendes** [comment]
@skaynetmen @abdulbasit1248 did either of you ever get it working?

**Comment by JBerendes** [comment]
![pending_forever](https://user-images.githubusercontent.com/596925/85074679-93b1f680-b182-11ea-8678-dc9753bf97e9.jpg)

**Comment by linus-komnick** [comment]
All you have to do is open the in-app developer menu, then go to “Configure Bundler” and enter the ip of your node server and the port!
