### ISSUE TITLE
Scrolling is not working as expected on Forms with few android devices (Android V7 and V10)

### ISSUE THREAD

**Issue by iswanj** [facebook/react-native#28164]
Description:
I have a scrolling issue(scrolling doesn't start) on forms when you start scrolling with a tap on the input element (e.g. TextInput) but if you tap outside the input element (e.g. label or outside form area) scrolling is working as expected. I have only face this issue on Android versions 7 and 10. 

PS: This is not happening on IOS 

React Native version:

    System:
    OS: Linux 5.3 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 2.72 GB / 15.53 GB
    Shell: 4.4.20 - /bin/bash
    Binaries:
    Node: 12.13.0 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/bin/yarn
    npm: 6.12.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
    Android SDK:
      API Levels: 25, 26, 28, 29
      Build Tools: 19.1.0, 28.0.0, 28.0.3, 29.0.2
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5

## Snack, code example, screenshot, or link to a repository:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/7093947/75129419-da776e80-5703-11ea-9c4e-fc8a0bb2b0c5.gif)

**Comment by safaiyeh** [comment]
Hi @iswanj thank you or the issue! Could you provide a repo that demonstrates this bug so we can investigate?

**Comment by iswanj** [comment]
@safaiyeh thank you for your attention, this is happening when you define a height to input element instead of padding. So since having a workaround, I'm going to close this issue.
