### ISSUE TITLE
TouchableHighlight swallows my View on Android

### ISSUE THREAD

**Issue by bsansouci** [facebook/react-native#2816]
I'm probably doing something wrong here, but I can't figure it out. It doesn't render the View or the image. This works on iOS.
Here's my code:

```jsx
<TouchableHighlight onPress={this.props.onPress}>
  <View className="fab colored" style={this.props.style}>
    <Image
      style={{
        width: 24,
        height: 24,
        tintColor: 'white',
        borderRadius: 1, // Bug in Android (#2769 on react-native)
      }}
      source={{uri: "someUrl"}} />
  </View>
</TouchableHighlight>
```

**Comment by mkonicek** [comment]
I don't think `className` is a valid `View` prop.
The code looks OK, can you try removing the `View` and only keep the `Image` to get a simpler repro?

**Comment by mkonicek** [comment]
Re:

   // Bug in Android (#2769 on react-native)

Note that this is a very early and it can't be expected everything will that works on iOS will work, see:
https://facebook.github.io/react-native/docs/known-issues.html#missing-modules-and-native-views

**Comment by ms88privat** [comment]
I don't know if it is related, but did you tried this?
<View collapsable={false}>

**Comment by bsansouci** [comment]
@mkonicek That would make sense, I might've copy pasted some html and blindly changed `class` to `className` ;)
yeah the comment was more for me to know why the heck that was there. I'm not expecting everything to work from the get-go, this is already an amazing gift that you guys are giving the community.

I removed the `View` and I could see the `Image`. I removed part of the `this.props.style` to __not__ have:
```js
position: 'absolute',
left: 140,
top: -70,
```

and it appeared! My guess is that it's showing but under some other component. I'm not sure if it's normal that `TouchableHighlight` changes the positioning of things?


@ms88privat didn't seem to change much.

**Comment by foghina** [comment]
>     top: -70

Sounds to me like you were relying on `overflow: visible`. Overflowing content is hidden on Android and there's currently no way to change that.

**Comment by foghina** [comment]
See: https://facebook.github.io/react-native/docs/known-issues.html#the-overflow-style-property-defaults-to-hidden-and-cannot-be-changed-on-android

**Comment by bsansouci** [comment]
@foghina I found it! Both the `View` and the `Image` were hidden under the `View` drawn above. However I move that `View` around, it's always drawn under the other `View`s. How can I make it appear on top?

**Comment by satya164** [comment]
@bsansouci Currently the only way to change positioning order is to change the order in which they appear in the view hierarchy.
