### ISSUE TITLE
app crashes on launch with CLI after installing react-navigation

### ISSUE THREAD

**Issue by AnuragVadd** [facebook/react-native#28177]
Description:

I created a new project without expo using this guide : https://reactnative.dev/docs/getting-started. After running the app for the first time using `react-native run-android`, i got an error saying that module react-native-safe-area-context was not found. 

I followed this guide to install the missing module : https://icetutor.com/question/getting-this-error-error-bundling-failed-error-unable-to-resolve-module-react-native-safe-area-context/ 

I have used npm install to install the module. After that i tried to run the app but even though the build is successful, it immediatley crashes on launch without any errors.

i have also tried to link the package manually but it later showed that automatic linking was enabled.

I have installed the following libraries : 

```
    "react-native-gesture-handler": "^1.6.0",
    "react-native-reanimated": "1.7.0",
    "react-native-screens": "2.0.0-beta.13",
    "react-navigation": "4.2.1",
    "react-navigation-stack": "2.2.1",
    "react-native-safe-area-context": "^0.7.3",
   "react-native-safe-area-view": "^1.0.0",
```

React Native version:

info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i7-4700HQ CPU @ 2.40GHz
    Memory: 1.39 GB / 7.89 GB
  Binaries:
    Node: 12.16.1 - D:\nodejs\node.EXE
    Yarn: 1.22.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.4 - D:\nodejs\npm.CMD
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5

## Steps To Reproduce

1. create new project without expo
2. install the following packages : 
```
    "react-native-gesture-handler": "^1.6.0",
    "react-native-reanimated": "1.7.0",
    "react-native-safe-area-view": "^1.0.0",
    "react-native-screens": "2.0.0-beta.13",
    "react-navigation": "4.2.1",
    "react-navigation-stack": "2.2.1"
```
3. install `react-native-safe-area-view` with auto link
4. run application using `react-native run-andriod`

## Snack, code example, screenshot, or link to a repository:

I was trying to run this snippet -

NOTE: i am not trying to use this package anywhere in the application; I just need the app to run
```
export default class someClass extends Component{
  render(){
    return (
    <View><Text>just testing to see if app is working</Text></View>
   );
    }
  }
```

**Comment by chk-profiq** [comment]
Hi, did You set up the navigation correctly? 
https://reactnavigation.org/docs/4.x/getting-started
Or for react-navigation version 5
https://reactnavigation.org/docs/getting-started

**Comment by AnuragVadd** [comment]
Yes, I have followed the steps correctly. My colleagues have provided an older version of react native with some boilderplate packages pre-installed and it worked perfectly, these are the versions and packages which was in the biolerplate project - 

```
  "dependencies": {
    "react": "16.9.0",
    "react-native": "0.61.0",
    "@react-native-community/masked-view": "^0.1.6",
    "axios": "^0.19.1",
    "native-base": "^2.13.8",
    "react-native-gesture-handler": "^1.5.3", 
    "react-native-reanimated": "^1.6.0",
    "react-native-safe-area-context": "^0.6.2",
    "react-native-screens": "^2.0.0-alpha.25",
    "react-native-vector-icons": "^6.6.0",
    "react-navigation": "^4.0.10",
    "react-navigation-stack": "^2.0.15",
    "react-redux": "^7.1.3",
    "redux": "^4.0.5"
  },

```

I am not sure if this is due to an issue with latest react-native version or if it is a problem with the navigation package itself.

here are the full dependencies (which i can confirm is not working ) of the project which was unable to run with react-navigation / safe-area installed-

```
  "dependencies": {
    "@react-native-community/masked-view": "^0.1.6",
    "@react-navigation/native": "^5.0.8",
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-gesture-handler": "^1.6.0",
    "react-native-reanimated": "^1.7.0",
    "react-native-safe-area-context": "^0.7.3",
    "react-navigation": "^4.2.2"
  },
```

**Comment by AnuragVadd** [comment]
I have also tried to link it manually using `react-native link` but it gave me an error that autolinking was enabled, so i unlinked it.

**Comment by AnuragVadd** [comment]
also note that I had uninstalled `react-native-screens` from the latest project after installing `react-navigation` since i had a hunch that that package was causing the issue. But even with the screens package installed i can confirm that the application failed to launch

**Comment by jimkhan** [comment]
i also faced same problem

**Comment by jimkhan** [comment]
Add the following dependencies to \android\app\build.gradle to avoid this error:
implementation 'androidx.appcompat:appcompat:1.1.0-rc01'
implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0-alpha02'

**Comment by AnuragVadd** [comment]
hm.. I created a new project and added the dependencies again and this time it did not crash. Perhaps there was some issue with npm install? either way it is not affecting me anymore so will be closing this issue. @jimkhan thank you for the suggestion
