### ISSUE TITLE
Memory leak causing crashes in iOS/Release builds.

### ISSUE THREAD

**Issue by meros** [facebook/react-native#28188]
Description:

Having large images combined with TextInput causes large memory leaks. We encountered this in a production app, but I have isolated the issue in a small newly created test app.

React Native version:

➜  RNTestMemoryLeak git:(master) npx react-native info
info Fetching system and libraries information...
System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
    Memory: 53.27 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.13.0 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.13.7 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5

## Steps To Reproduce

1. Generate a new RN project
2. Add large images to view
3. Add TextInput to view
4. Build for iOS in Release mode
5. Run app on real device and monitor memory
6. Focus on the TextInput and start cycling app between foreground and background (pressing home button), allow app to stay in background for 1-2 seconds each time. 

## Expected Results

I expect the memory to stay flat over time, what I see is the memory related to the images being allocated each time app goes into background state

## Snack, code example, screenshot, or link to a repository:

https://github.com/meros/RNTestMemoryLeak

![image](https://user-images.githubusercontent.com/450310/75450831-ccc62100-596f-11ea-9516-3238e582f001.png)

**Comment by sivakumar-cf** [comment]
+1, After I updated react-native 0.59.10 to 0.61.5, I am facing the same issue.

**Comment by meros** [comment]
I tried the same from 0.59.10 to latest rc and get the same problem in both extremes...
