### ISSUE TITLE
Android - Cannot build without development server

### ISSUE THREAD

**Issue by sadikyalcin** [facebook/react-native#28185]
## Description:

I'm trying to build a debug-apk without the development server but it doesn't seem to work. Upon an error on the app, reloading / dismiss the error and the app is stuck with the development server error (see screenshot). The filesize is no smaller which I don't think should be the case.

## React Native version:

    System:
        OS: macOS 10.15.3
        CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
        Memory: 646.83 MB / 16.00 GB
        Shell: 3.2.57 - /bin/bash
    Binaries:
        Node: 12.10.0 - ~/.nvm/versions/node/v12.10.0/bin/node
        Yarn: 1.13.0 - /usr/local/bin/yarn
        npm: 6.10.3 - ~/.nvm/versions/node/v12.10.0/bin/npm
        Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
        iOS SDK:
            Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
        Android SDK:
            API Levels: 23, 26, 27, 28
            Build Tools: 28.0.3
            System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
        Android Studio: 3.5 AI-191.8026.42.35.6010548
        Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
        react: 16.9.0 => 16.9.0 
        react-native: 0.61.5 => 0.61.5 
    npmGlobalPackages:
        react-native-cli: 2.0.1

## Steps To Reproduce

1. Edit `build.gradle`
2. Update project args to;

```
project.ext.react = [
    entryFile: "index.js",
    bundleInDebug: true,
    bundleInRelease: true,
    devDisabledInDebug: true,
    enableHermes: false,  // clean and rebuild if changing
]
```
3. `cd android & ./assembleDebug`
4. Install apk on physical device.
5. or run `react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res` and `cd android & ./assembleDebug` and install apk on physical device.

## Expected Results

I should have a debug-apk without the dev server.
   
## Snack, code example, screenshot, or link to a repository:

![photo_2020-02-27_11-13-32](https://user-images.githubusercontent.com/8109619/75439951-b2317f00-5952-11ea-9fe4-87a7cfdd3a6e.jpg)

Along with all this, I am still unsure how to build a debug-apk without the development server so I can test the application without publishing to the app store. Either there is no docs explaining this or it's out of my reach because I cannot find anything regarding this on the docs. If there is, please do share the link.

**Comment by anshdroid** [comment]
You'll have to generate a KeyStore file which will contain your key and password for Signing for this you have to run command : 

```
keytool -genkey -v -keystore mykeystore.keystore -alias mykeyalias -keyalg RSA -keysize 2048 -validity 10000
```
after filling  all the entries when you run this command, a keystore file will generate put that file at location android/app

Now in the App level build gradle, change signingConfigs block according to the infomation you filled 

and then run command  
```
gradlew assembleRelease
```

You might stuck at key-alias name, so run this command:
```
keytool -list -v -keystore keystore_name > keystore_output.txt
```

for more info follow this URL : 
https://www.instamobile.io/android-development/generate-react-native-release-build-android/
cheers to the author of this link
