### ISSUE TITLE
iOS App Crashes in Launch screen on device with Namespace SPRINGBOARD

### ISSUE THREAD

**Issue by zonghui1006** [facebook/react-native#28186]
When I am running my React-native project on iPhone XS Max device, The application is staying in the launch for a while(close to 20-30 secs) and then the app crashes . Does anybody know how to fix the crash.

react native After update to 0.61, Find out
 
Xcode Version 11.2.1 
iOS ：13.3
"react": "16.9.0",
"react-native": "^0.61.4",

The Crash that I have got from crashlogs is
Exception Type:  EXC_CRASH (SIGKILL)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: Namespace SPRINGBOARD, Code 0x8badf00d
Termination Description: SPRINGBOARD, scene-create watchdog transgression: application<xxx>:70760 exhausted real (wall clock) time allowance of 19.98 seconds | ProcessVisibility: Background | ProcessState: Running | WatchdogEvent: scene-create | WatchdogVisibility: Foreground | WatchdogCPUStatistics: ( | "Elapsed total CPU time (seconds): 3.830 (user 3.830, system 0.000), 18% CPU", | "Elapsed application CPU time (seconds): 0.024, 0% CPU" | )
Triggered by Thread:  0

![image](https://user-images.githubusercontent.com/59638556/75443528-8cc96300-599c-11ea-9b42-941ff979435a.png)

Is there any solution?

**Comment by hramos** [comment]
Hi, can you make sure the issue template is properly filled out?

**Comment by zonghui1006** [comment]
> Hi, can you make sure the issue template is properly filled out?

I found the problem, because I upgraded from 0.58 to 0.61， without modifying the entry file, and the problem was eliminated after the modification. Thank you
