### ISSUE TITLE
new keyboard device events fire twice with different event object

### ISSUE THREAD

**Issue by dvine-multimedia** [facebook/react-native#2818]
When listening to new keyboardWillShow and keyboardWillHide events they fire twice for each keyboard change with different event objects:

```{endCoordinates: Object, startCoordinates: Object, duration: 250}```
and
```{begin: Object, end: Object, duration: 0.25}```
for each.

**Comment by ide** [comment]
cc @a2 @nicklockwood

**Comment by dvine-multimedia** [comment]
sorry guys. my bad. close the issue. the second event came from the still active react-native-keyboard-events module.
