### ISSUE TITLE
Android: Debug mode is broken

### ISSUE THREAD

**Issue by lucasriondel** [facebook/react-native#28191]
Description:

I think my debug mode for android is kinda broken. I cannot open the debug menu, event though I have yellow-orange boxes for warnings on my device (which tells that i'm running the app on debug mode). No chrome tab opens with a debugger when i run a `react-native run-android`. 

The metro bundler doesn't seem to bundle anything by the way. I used to have a green progress bar but now nothing, even though my app does start on my device. 

![image](https://user-images.githubusercontent.com/7773454/75460067-4581a900-5981-11ea-9ed0-65c956af0395.png)

`react-native log-android` gives me logs from the app, as if I was looking a the console.

`adb shell input keyevent 82` doesn't do anything.

React Native version:

```
    System:
      OS: Windows 10
      CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU 
@ 2.20GHz
      Memory: 6.96 GB / 19.74 GB
    Binaries:
      Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD 
    IDEs:
      Android Studio: Version  3.5.0.0 AI-191.8026.42.35.6010548
```

```
    "react": "16.8.3",
    "react-native": "0.59.9",
```

## Expected Results

    I would like to have my debug menu back.

**Comment by hramos** [comment]
I am not sure this belongs on this repository. Can you provide a list of steps to reproduce this on the latest version? Feel free to submit a new issue with this information.
