### ISSUE TITLE
ScrollResponder.scrollResponderScrollNativeHandleToKeyboard calls deprecated apis

### ISSUE THREAD

**Issue by janicduplessis** [facebook/react-native#28203]
Description:

[ScrollResponder.scrollResponderScrollNativeHandleToKeyboard](https://github.com/facebook/react-native/blob/da9364fa3e2e78ed3e06d469af8414933611501b/Libraries/Components/ScrollResponder.js#L591) calls deprecated `getInnerViewNode` and `getInnerViewRef`. The warning recommends using `innerViewRef`, however I'm not sure how this could be done from `ScrollResponder`.

React Native version:

Master

## Steps To Reproduce

Call `scrollResponderScrollNativeHandleToKeyboard` on a ScrollView responder instance.

## Expected Results

No deprecation warnings.

## Snack, code example, screenshot, or link to a repository:

 N/A

**Comment by janicduplessis** [comment]
cc @kacieb @TheSavior

**Comment by TheSavior** [comment]
Thanks for flagging!

**Comment by TheSavior** [comment]
Hmm. I can't seem to assign @kacieb here. :-/

**Comment by hramos** [comment]
I think @kacieb might need to be added to the Facebook GitHub org

**Comment by hramos** [comment]
> React Native version:
> 
> Master

❤️

**Comment by TheSavior** [comment]
Yeah, @janicduplessis, it's super awesome that you are able to give this feedback to us so quickly by running on Master. It's so much better than finding out months later when people use a release.

**Comment by janicduplessis** [comment]
I mean I get to use cool things before everyone :D

**Comment by TheSavior** [comment]
@kacieb removed these warnings to unblock 63 in this commit: https://github.com/facebook/react-native/commit/3246f68952c8fe065367ef8d2cdf7da5dfff78e4

She said she'll plan on relanding those warnings with the additional correct fixes at a later date.
