### ISSUE TITLE
Fast Refresh - Same file works, different file and it stops working

### ISSUE THREAD

**Issue by codecog** [facebook/react-native#28207]
**Description:** Updating a component imported as a child does not update without a hard refresh when moved to it's own file.

**React Native version:** 0.61.5

## Steps To Reproduce
1. Create a basic component with a child component. Make a change to the child component and fast refresh works here without issue. 

2. Terminate the metro bundler, move the `<Header />` component to it's own file and than import it into the `<Root />` component and then try to make a change in `<Header />`. The text does not update without a hard refresh.

## Expected Results
Fast refresh updates the text without a hard reload.

## Snack, code example, screenshot, or link to a repository:
```
// Header.js
const Header = () => (
  <View>
    <Text>Title</Text>
  </View>
);

export default Header;

// Root.js
const Root = () => {
  return (
    <View>
      <Header />
      <Text>Testing</Text>
    </View>
  );
};

export default Root;
```

**Comment by codecog** [comment]
Further investigation seems like this is an issue with alos using @welldone-software/why-did-you-render

**Comment by Maddoc42** [comment]
I can confirm this. @welldone-software/why-did-you-render@4.1.3 does break fast refresh on RN 0.62.2. Corresponding issue is https://github.com/welldone-software/why-did-you-render/issues/105.
