### ISSUE TITLE
React-Native | TextInput clipboard menu localization problem only on IOS.

### ISSUE THREAD

**Issue by akinmac002** [facebook/react-native#28218]
## Description:
My problem is in the 59.9 version; Holding a long press on the text in the textinput, the clipboard is about the language in the menu. This problem only happens on IOS. Device language is selected in Turkish. Device country is selected in Turkey. But textinput clipboard menu language is English.

## React Native version: 59.9
```
React Native Environment Info:
    System:
      OS: macOS 10.15.2
      CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
      Memory: 105.99 MB / 8.00 GB
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.15.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
      Android SDK:
        API Levels: 10, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 23.0.2, 24.0.0, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.1, 27.0.3, 28.0.3
        System Images: android-19 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-25 | Google Play Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-28 | Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5199772
      Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.9 => 0.59.9 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

## Steps To Reproduce
1. Open any IOS device.
2. Add any textinput to the your React-Native any page.
3. Make the device language other than English.
4. run react-native run-ios.
5. Write any text in the textinput.
6. Long press on the text you wrote.
7. You will see the opened clipboard menu.

## Expected Results
Clipboard menu language must match device language.

## Screenshot:
![ReacNative-TextInput-ClipboardMenu-Localization](https://i.ibb.co/PgXN7gp/rntilocale.png)

**Comment by safaiyeh** [comment]
Hi @akinmac002 thank you for the issue! For us to investigate further, could you provide a Snack with the current React Native?
