### ISSUE TITLE
error while installing react native on ubuntu 19.01 .

### ISSUE THREAD

**Issue by jet2018** [facebook/react-native#28212]
error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at '/home/jet/AwesomeProject/android/local.properties'.

**Comment by asadikhlas** [comment]
Hi, jet,
To make sure your environment is set up properly for android, go to the root of your react-native project. Open the android project(folder) in the Android Studio IDE.

All errors with your environment will show up, and that will automatically start the Gradle Daemon to sync and configure the build for you. Once it finished, close the Android Studio and come back to command-line and run: react-native run-android

This works fine.

**Comment by asadikhlas** [comment]
Hi, jet,
To make sure your environment is set up properly for android, go to the root of your react-native project. Open the android project(folder) in the Android Studio IDE.

All errors with your environment will show up, and that will automatically start the Gradle Daemon to sync and configure the build for you. Once it finished, close the Android Studio and come back to command-line and run: react-native run-android

This works fine.

**Comment by umairx97** [comment]
@asadikhlas Thanks I had the same problem your solution worked 👍
