### ISSUE TITLE
Port overriding failing on 0.61.5

### ISSUE THREAD

**Issue by carlost** [facebook/react-native#28216]
Application fails in iOS simulator with `No bundle URL present.` error.

<img width="241" alt="Screen Shot 2020-03-02 at 11 23 29 AM" src="https://user-images.githubusercontent.com/514078/75700519-2be1a980-5c80-11ea-8b61-8206d38d3a8c.png">

My macbook pro is running macafee virusscan on port 8081.  I export `RCT_METRO_PORT` env var with a value of 8088.  When i execute `yarn ios` metro starts up on port 8088 but application in simulator attempts to connect to metro using port 8081.

Metro console output:
```
┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│  Running Metro Bundler on port 8088.                                         │
│                                                                              │
│  Keep Metro running while developing on any JS projects. Feel free to        │
│  close this tab and run your own Metro instance if you prefer.               │
│                                                                              │
│  https://github.com/facebook/react-native                                    │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘
```

When i logged the value of `RCT_METRO_PORT` in `AppDelegate.sourceURLForBridge()` (TestApp/ios/AppDelegate.m) the value was `8081`:

```
- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
   RCTLog(@"in AppDelegate.sourceURLForBridge RCT_METRO_PORT: %lu", metroDefaultPort);
...
```

When i logged the value of `url` in `RCTBundleURLProvider.isPackagerRunning` (TestApp/node_modules/react-native/React/Base/RCTBundleURLProvider.m) the value was `http://localhost:8081/status`:

```
#if RCT_DEV
- (BOOL)isPackagerRunning:(NSString *)host
{
  RCTLogWarn(@"in RCTBundleURLProvider.isPackagerRunning");
  RCTLogWarn(@"checking on host: %@", host);

  NSURL *url = [serverRootWithHostPort(host) URLByAppendingPathComponent:@"status"];

  RCTLogWarn(@"url to check: %@", [url absoluteString]);
...
```

Commit [33d710e8c58ef1dc69816a59ac1cf390894e7cb9](https://github.com/facebook/react-native/commit/33d710e8c58ef1dc69816a59ac1cf390894e7cb9), first released in v0.53.0-rc.0, added `RCT_METRO_PORT=${RCT_METRO_PORT}"` as a `GCC_PREPROCESSOR_DEFINITIONS` to the debug targets of:

- React/React.xcodeproj/project.pbxproj, and
- Libraries/WebSocket/RCTWebSocket.xcodeproj/project.pbxproj

These files were removed in v0.61.0-rc.0 as part of the effort to adopt CocoaPods. I do not believe the Podfiles that replaced the prior .xcodeproj dirs address the metro port `GCC_PREPROCESSOR_DEFINITIONS`.

## React Native version:
React Native version:
yarn run v1.21.1
$ /Users/cefernan/workspace/TestApp/node_modules/.bin/react-native info
info Fetching system and libraries information...
System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 69.61 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.18.1 - /var/folders/fm/l9pn13051z7d43lcnqftsj59tkd6tm/T/yarn--1583172377612-0.7099214206886124/node
    Yarn: 1.21.1 - /var/folders/fm/l9pn13051z7d43lcnqftsj59tkd6tm/T/yarn--1583172377612-0.7099214206886124/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5
✨  Done in 1.96s.

## Steps To Reproduce

1. export RCT_METRO_PORT=8088.  (See below)
1. run `npx react-native init TestApp`
1. run `yarn ios`

Metro will spin up on port 8088 but the TestApp running in iOS simulator cannot connect to metro.

### Exporting RCT_METRO_PORT
As recently as RN v0.55.x, i was able to do this via an export statement in terminal.  However, i think that changes in either RN or xcode prevent that from working.  I had to export this via a plist file in `~/Library/LaunchAgents`: 
```
cat ~/Library/LaunchAgents/environment.plist 
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>cefernan.env.vars</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/launchctl</string>
    <string>setenv</string>
    <string>RCT_METRO_PORT</string>
    <string>8088</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>StandardOutPath</key>
  <string>/Users/cefernan/.launchctl/rct_metro_port.log</string>
  <key>StandardErrorPath</key>
  <string>/Users/cefernan/.launchctl/rct_metro_port.log</string>
  <key>Debug</key>
  <true/>
</dict>
</plist>
```
You can run `launchctl load` and a few killall commands to get this loaded up.  However, i am not 100% sure if there are gaps/differences in how that works. So it is safest to just restart your machine.

## Expected Results

I expect the TestApp running in iOS simulator to connect to metro on port 8088.

## Snack, code example, screenshot, or link to a repository:

Let me know if you need a sample repo to verify this?

Sorry if some of this is incoherent, I only recently picked up the RN compilation and tooling issues on our project.

Pretty sure this is identical to #27237 (which was closed)

**Comment by carlost** [comment]
I am able to get `yarn ios` working if i add a post_install hook to the Podfile that adds the `RCT_METRO_PORT` friendly `GCC_PREPROCESSOR_DEFINITIONS` build setting back.

```
post_install do |installer|
    installer.pods_project.targets.each do |target|
      puts "targets: #{target.name}"
      if ['React', 'React-Core'].include?(target.name)
        target.build_configurations.each do |build_configuration|
          if build_configuration.name == 'Debug'
            Pod::UI.message("Adding RCT_METRO_PORT GCC_PREPROCESSOR_DEFINITIONS build setting for '#{target.name} - #{build_configuration.name}'")
            defs = build_configuration.build_settings['GCC_PREPROCESSOR_DEFINITIONS']
            # set to an standard set of debug defs in case it is nil
            defs ||= %w($(inherited) COCOAPODS=1 DEBUG=1)
            # single quoted string because we want to preserve the ${} escape
            # syntax so that xcode can set the RCT_METRO_PORT value based on
            # the RCT_METRO_PORT env var
            defs << 'RCT_METRO_PORT=${RCT_METRO_PORT}'
            build_configuration.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = defs
          end
        end
      end
    end
  end
```

I am not 100% sure if this is the best solution to this problem.  Moreover, this only seems to work when i launch the simulator from Terminal with `yarn ios`.  Even with these changes I can't get the simulator to work properly when I launch the simulator from xcode.

**Comment by carlost** [comment]
sorry ... i didn't realize that the env info parser was so finicky

**Comment by chrisglein** [comment]
Do we think this is specifically a metro issue? I wonder if there's more assistance to be had on [this repo](https://github.com/facebook/metro). I'm not sure what the issue handling process is there but it's worth looking over there too.

**Comment by GP-Moon** [comment]
HOW CAN I CHANGE PORT????????????????????


Showing Recent Messages
Port 8081 already in use, packager is either not running or not running correctly

Showing Recent Messages
Port 8081 already in use, packager is either not running or not running correctly


Showing Recent Messages
Port 8081 already in use, packager is either not running or not running correctly


Showing Recent Messages
Port 8081 already in use, packager is either not running or not running correctly


Showing Recent Messages
Port 8081 already in use, packager is either not running or not running correctly


Showing Recent Messages
Port 8081 already in use, packager is either not running or not running correctly


Showing Recent Messages
Port 8081 already in use, packager is either not running or not running correctly


Showing Recent Messages
Port 8081 already in use, packager is either not running or not running correctly


Showing Recent Messages
Port 8081 already in use, packager is either not running or not running correctly


Showing Recent Messages
Port 8081 already in use, packager is either not running or not running correctly


Showing Recent Messages
Port 8081 already in use, packager is either not running or not running correctly


Showing Recent Messages
Port 8081 already in use, packager is either not running or not running correctly


Showing Recent Messages
Port 8081 already in use, packager is either not running or not running correctly


Showing Recent Messages
Port 8081 already in use, packager is either not running or not running correctly


Showing Recent Messages
Port 8081 already in use, packager is either not running or not running correctly


Showing Recent Messages
Port 8081 already in use, packager is either not running or not running correctly


Showing Recent Messages
Port 8081 already in use, packager is either not running or not running correctly


Showing Recent Messages
Port 8081 already in use, packager is either not running or not running correctly


Showing Recent Messages
Port 8081 already in use, packager is either not running or not running correctly

?????????????????????????????????????????????????????????

**Comment by GP-Moon** [comment]
Showing Recent Messages
Command PhaseScriptExecution failed with a nonzero exit code

Showing Recent Messages
Command PhaseScriptExecution failed with a nonzero exit code


Showing Recent Messages
Command PhaseScriptExecution failed with a nonzero exit code


Showing Recent Messages
Command PhaseScriptExecution failed with a nonzero exit code


Showing Recent Messages
Command PhaseScriptExecution failed with a nonzero exit code


Showing Recent Messages
Command PhaseScriptExecution failed with a nonzero exit code


Showing Recent Messages
Command PhaseScriptExecution failed with a nonzero exit code
