### ISSUE TITLE
[Android][Windows] Debug in Chrome is broken

### ISSUE THREAD

**Issue by BerndWessels** [facebook/react-native#2822]
Hello

Now that we are able to develop React-Native Android Apps on Windows I came across this problem.

When trying to `Debug in Chrome` from the Android emulator I get error in the development server console:

      Launching Dev Tools...
          Error: spawn UNKNOWN
      at exports._errnoException (util.js:837:11)
      at ChildProcess.spawn (internal/child_process.js:298:11)
      at exports.spawn (child_process.js:339:9)
      at exports.execFile (child_process.js:141:15)
      at Object.handle (Y:\Mobile\node_modules\react-native\packager\packager.js:193:7)
      at next (Y:\Mobile\node_modules\react-native\node_modules\connect\lib\proto.js:190:15)
      at Object.openStackFrameInEditor [as handle] (Y:\Mobile\node_modules\react-native\packager\packager.js:179:5)
      at next (Y:\Mobile\node_modules\react-native\node_modules\connect\lib\proto.js:190:15)
      at IncomingMessage.<anonymous> (Y:\Mobile\node_modules\react-native\packager\packager.js:169:5)
      at emitNone (events.js:67:13)
      [8:56:22 AM] <START> request:/index.android.bundle?platform=android
          [8:56:22 AM] <END>   request:/index.android.bundle?platform=android (12ms)
      ::ffff:127.0.0.1 - - [Thu, 17 Sep 2015 20:56:23 GMT] "GET /flow/ HTTP/1.1" 404 - "-" "okhttp/2.4.0"

I think this is related to the problem that @mqli discovered and fixed regarding 'ChildProcess.spawn' [here](https://github.com/facebook/react-native/issues/2787).

I will have a look into it too, but might not be the best person to fix it. Please help to fix it and make the development experience on Windows as enjoyable as it already is on OSX.

Thank you
Bernd

**Comment by mkonicek** [comment]
Thanks for reporting! If you get it to work please send a PR or coordinate with @mqli.

**Comment by BerndWessels** [comment]
@mkonicek OK, will do.

I find it very hard to get the `node remote debugger` to connect to `react-native start`. Haven't figured out yet where to add the `--debug` flag to be able to debug.

Cheers
Bernd

**Comment by mkonicek** [comment]
Not sure myself, I would look in the code for "Launching Dev Tools..." and what's in the stack trace:

at Object.handle (Y:\Mobile\node_modules\react-native\packager\packager.js:193:7)

**Comment by BerndWessels** [comment]
OK, here is some progress, but still not solved yet.

In `/node_modules/react-native/packager/packager.js` I changed `getDevToolsLauncher` from Line 193 to:

      console.log('Launching Dev Tools...');
      var childProcess = require('child_process');
      childProcess.exec('start chrome http://localhost:8081/debugger-ui');
      //execFile(path.join(__dirname, script), [debuggerURL], function(err, stdout, stderr) {
      //  if (err) {
      //    console.log('Failed to run ' + script, err);
      //  }
      //  console.log(stdout);
      //  console.warn(stderr);
      //});
      res.end('OK');

This change enables us now to `Debug in Chrome` in the Android emulator. It then opens a new Chrome Window and you can open the chrome dev tools to debug.

But now in `debugger-ui` line 95 it seems to fail somehow and says `Unknown method` because `object.method` is `undefined.

    ws.onmessage = function(message) {
      var object = JSON.parse(message.data);
      var sendReply = function(result) {
        ws.send(JSON.stringify({replyID: object.id, result: result}));
      };
      var handler = messageHandlers[object.method];
      if (handler) {
        handler(object, sendReply);
      } else {
        console.warn('Unknown method: ' + object.method); // <<<<<<<<<<<<<<<<<<<<<<<
      }
    };

I keep on digging but am no expert in this area at all, so please help.
@mqli @mkonicek

Thank you
Bernd

**Comment by BerndWessels** [comment]
OK, I was too fast, hehe.

So the fix actually works. It opens Chrome - !! now be a bit patient before opening the dev tools !! ;)

That is kind of great. I can now put breakpoints in chrome dev tools and they get hit when I reload the app in the simulator.

But it seems that Android, the simulator or whatever is very fragile.
- You can't stay long in a breakpoint, or else the app breaks.
- Often when you continue out of a breakpoint the app will be just plain white.
- There are some error messages in the console which feel a bit dodgy.

So overall I would say that needs some investigation from experts in that area!

Please help to make the react native development experience great on all platforms.

Thank you
Bernd

**Comment by mqli** [comment]
I just find out there is a dev tool feature(just play RN for 2 days)!!!
http://localhost:8081/debugger-ui,get an module load error
I will look into it see what I can do

**Comment by mqli** [comment]
And @mkonicek, It seem like that the recent few PRs(even the typo fix) all failed in the CI build with same issue:
```
 FAIL  Libraries/StyleSheet/__tests__/processColor-test.js 
```
Seem relate to the 'tinycolor2' package. I hope some may need to look into it, maybe problem with the test suit or CI config.

**Comment by mqli** [comment]
@BerndWessels  It seem that by ignore the error log. chrome debugger will work just fine.

**Comment by tdzl2003** [comment]
I solve this problem by open url "http://localhost:8081/debugger-ui" in chrome manually.

The script that open chrome is not implemented on windows.

**Comment by ChristianHersevoort** [comment]
@tdzl2003 It should already be fixed on Windows because of https://github.com/facebook/react-native/pull/2406

**Comment by BerndWessels** [comment]
Hi guys
Please keep this issue open until it is fixed and merged into master.
Cheers
Bernd

**Comment by kmagiera** [comment]
Referencing #2693 here as a master task for tracking windows/linux efforts

**Comment by jsierles** [comment]
This seems to have been addressed. As mentioned in #2693, Windows support is tracked in the documentation. Reopen is there's still an issue, thanks!
