### ISSUE TITLE
React Native Android - Single/Multiline comments throws error

### ISSUE THREAD

**Issue by jacobross85** [facebook/react-native#2823]
If I put a single or multiline comment inside a `<View>` enclosure throws an error `Trying to add unknown view tag:` and what looks like an array map of the tags. 

![screen shot 2015-09-17 at 3 13 00 pm](https://cloud.githubusercontent.com/assets/2907515/9947390/a0726bda-5d4e-11e5-96bf-5080097f2207.png)

Also found that if I use a multiline comment, the interpreter still renders the commented out elements

Such as

```
/*
   <View>
      <Image source={require('image!bg_splash')} style={{}} />
   </View>
*/
```

I still received `unknown module 'image!bg_splash'` during my last issue [#2808](https://github.com/facebook/react-native/issues/2808)

**Comment by ide** [comment]
This is how JSX works (independent of React Native). JSX does not support comments - you need to push them in to JS, ex: `{/* comment */}`

**Comment by jacobross85** [comment]
Got it. Thank you.

**Comment by phongyewtong** [comment]
Just curious, does this create any performance overhead?
