### ISSUE TITLE
Crash in RCTView

### ISSUE THREAD

**Issue by Elfoniok** [facebook/react-native#28233]
Description:

This is one of the crashes that I experience when I am using react-native-debugger AND when I enable Inspector to highlight the components. Please see  reproduction steps.

NOTE: I am using expo on top.

```
ExceptionsManager.js:44 Invariant Violation: [339,"RCTView",{"left":"<<NaN>>","top":"<<NaN>>","width":"<<NaN>>","height":"<<NaN>>"}] is not usable as a native method argument

This error is located at:
    in RCTView (at ElementBox.js:64)
    in ElementBox (at InspectorOverlay.js:59)
    in RCTView (at InspectorOverlay.js:67)
    in InspectorOverlay (at Inspector.js:250)
    in RCTView (at Inspector.js:248)
    in Inspector (at AppContainer.js:65)
    in RCTView (at AppContainer.js:119)
    in AppContainer (at renderApplication.js:39)

```

React Native version:
System:
    OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
    Memory: 263.64 MB / 15.55 GB
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 8.10.0 - /usr/bin/node
    Yarn: 1.21.1 - /usr/bin/yarn
    npm: 3.5.2 - /usr/bin/npm
  npmPackages:
    react: ~16.9.0 => 16.9.0 
    react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4 
  npmGlobalPackages:
    create-react-native-app: 2.0.2

## Steps To Reproduce

1. Use code attached as an App.js.
2. Start react-native-debugger, have it listen on 19001 or whatever your metro bundler expose
3. Start app with expo start, then choose android emulator (but you can use device the same thing happens).
4. After the application loaded, open developer menu and use Debug option. Hopefully your react-native-debugger will overtake, you should see the application structure in it.
5. Once again from developer menu open inspector, it should be collapsed and you should be able to highlight the content on your target while walking through the structure. But as soon as you highlight RCTView, you will get error attached above. If I remove style from the code, inspector is working without problems.

## Expected Results

Should not crash :)

## Snack, code example, screenshot, or link to a repository:

I have minimal test case, it is so simple that I will paste in here. In fact it is so simple that I am afraid that maybe I am doing something wrong?
```
import React from 'react';
import { StyleSheet, View, Text } from 'react-native';

export default function App() {
	return (
		<View style={styles.container}>
			<Text>Dupa</Text>
		</View>
	);
}

const styles = StyleSheet.create({
	container: {
		marginTop: 50
	}
});
```
The clue is in style, if I remove this style inspector is working as expected.

**Comment by Elfoniok** [comment]
I did some investigation on my own.
1. It seems to be connected with registering callback that inspector use to obtain UI element measurement:
`      UIManager.measure(node, (x, y, width, height, left, top) => {
        this.setState({
          hierarchy: [],
          inspected: {
            frame: {left, top, width, height},
            style: props ? props.style : {},
          },
        });
      });`
2. This will enqueue this function in native system event queue. And at later point this function will be called as success callback (MessageQueue.js::__invokeCallback(cbID: number, args: any[])). 
3. But the code is actually crashing at this place
`invariant(
        isValidArgument(params),
        '%s is not usable as a native method argument',
        JSON.stringify(params, replacer),
      );`
It turn out that style parameters even though on the beginning are typeof "undefined", when this invariant is checked they have value "NaN" which is a number type.
If I modify the code to accept "number" as valid type Inspector is working as expected.

But the question is why this is failing in the first place? Does version of Android SDK matter for this?

**Comment by Elfoniok** [comment]
Can someone advise how to fix this properly? Or maybe this is fixed already?

**Comment by mhorowitz** [comment]
The "<<NaN>>" in the invariant violation comes from a little bit above the invariant, here: https://github.com/facebook/react-native/blob/ce1703a84d2712a7df8f93a3f3ecbb2c04b72e57/Libraries/BatchedBridge/MessageQueue.js#L291

This is good signal that those state values are a NaN numeric value, which cannot be reliably passed across the bridge.

If they are initialized as undefined, but NaN when you try to pass then across the bridge, it seems likely there's some bit of code somewhere which is applying arithmetic operations on the state without checking for undefined, as that's what happens when you do math on an undefined value:

```
>>> x = undefined
undefined
>>> x + 1
NaN
>>> x * 2
NaN
```

I don't know anything about the Inspector so I can't provide additional specific advice.  You'll need to find where in the JS code the state values are being set to NaN, and fix them.

**Comment by Elfoniok** [comment]
I suddenly remembered why I dislike dynamic type languages so much...

**Comment by Elfoniok** [comment]
I have tracked it down to following function
```
function completeUnitOfWork(unitOfWork) {
```

Also clarified some confusion I have created. So unit of work seems to have some nested structure of fibers. I confused the leaf node which is the ElementBox where it's pendingProps are "undefined" as expected with its "parent" an RTCView which has pendingProps as "NaN's". This is the view which is causing problems.

I suspect that mhorowitz  is right that someone is doing arithmetic operation on "undefined". Because this only happens when I add style of marginTop (probably also other kind of margins). It is very likely that it is used during RTCView creation.

However I have no idea where or when it is created when completeUnitOfWork is processing.

**Comment by Elfoniok** [comment]
@shergin Could you have a look at that? I have problem reading objective C. Or point me to someone who can help with that?

**Comment by Elfoniok** [comment]
I think I have found the problem. However I am not sure how to fix it correctly. @yungsters maybe you could give it a hand?

The problem is in ElementBox.js render function. When using Inspector with Overlays this 

```
const frameStyle = {...this.props.frame};
```

 will return frame style with undefined properties. Then we are doing arithmetic on them as @mhorowitz  suggested.

```
      frameStyle.top -= margin.top;
      frameStyle.left -= margin.left;
      frameStyle.height += margin.top + margin.bottom;
      frameStyle.width += margin.left + margin.right;
```

Then the frameStyle properties which are already NaN are assigned to View, which is then much later passed to BatchedBridge, but fails on invariant.

Quick fix would be to check for undefined, since this is debug feature anyway. Is that the way to go?

**Comment by yungsters** [comment]
Wow, thanks for the detailed bug report and investigation, @Elfoniok.

Checking for undefined could be the fix, but we should first try to understand why they are undefined and what the downstream consequences of this are.

These styles are used to eventually style `<ElementBox>` which displays a rectangle on top of the inspected view. In theory, this should work for `RCTView`, too. (Or at least as a developer, I would expect it to work.) So checking for undefined here seems like it could be the wrong fix.

It seems that the source of undefined values is from the callback argument that is supplied to `UIManager.measure`. Would you be open to investigating whether this is true, and if so, why `UIManager` is yielding undefined values for `RCTView`?

**Comment by Elfoniok** [comment]
@yungsters Yes, this is in fact due to `UIManager.measure` callback being called with `undefined`. However currently I have no idea how to debug this. @mhorowitz Do you have any idea why the callback is returning `undefined` for `RCTView`?

Otherwise It seems hard to debug unless any of you have some advises. I can see that the call is enqued in MessageQueue but I do not understand how and where this queue is processed.

Also I am not sure if BatchBridge is using websocket to communicate with native side? Or is this just debugger implementation details that are coming into my way?
I can see that the communication is going through `bundle.js`, `RNDebuggerWorker.js` and especially `backend.js`. But this seems to be part of debugger tools... 

After all the only thing that I can say for sure is that after we pass callback, with function ID to queue in MessageQueue.js,  `enqueueNativeCall(` it is magically processed somewhere, and later we receive callback associated with particular callID. ` __invokeCallback(cbID: number, args: any[]) {` the args returned are already, undefined. Or actually there is something funky here. It seems like maybe the spread operator is creating them, because args are empty? `callback(...args);`

After all I think maybe RCTView suppose to return `undefined`? Maybe it make no sens to show overlay for it? I am also interested what does it mean `folly-convertible` in validation parameters in MessageQueue? And most important, how to debug what is happening "on the other side" ?

**Comment by Elfoniok** [comment]
Yeah I am pretty sure, `__invokeCallback(cbID: number, args: any[])` receive 0 length array, as a response to measure call for RCTView. Then the spread operator creates array of undefined props.

**Comment by yungsters** [comment]
Do you know whether this only reproduces on Android? Can you see what happens if you set `collapsable={false}` on the `<View>`?

**Comment by Elfoniok** [comment]
I will try to check iOS and collapsable when I will have some time once again.

**Comment by 16oh4** [comment]
I am having the same problem when inspecting elements in react-devtools! 
![image](https://user-images.githubusercontent.com/37783822/78156525-877c8f80-7404-11ea-89de-562bb68c1552.png)

**Comment by oak-chantosa** [comment]
@16oh4 I'm using `npx react-devtools@3`, as version 4 does not work, and I'm seeing this same issue.

**Comment by Tav0** [comment]
I'm having the same issue, identical error on ElementBox and I'm developing on iOS

**Comment by Elfoniok** [comment]
I think this can be closed now. Seems a lot has changed since I was using it. I cant reproduce it anymore with :+1: System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
    Memory: 551.15 MB / 15.52 GB
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 10.19.0 - /usr/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.14.4 - /usr/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: Not Found
    Python: 2.7.18 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: ^0.63.2 => 0.63.2 
  npmGlobalPackages:
    *react-native*: Not Found

Definitely I recommend updating the react-native to 63.2 and expo to 39. I think it is important to note that react-native-debugger 0.11 also underwent major updates to use newer react-devtools might be also important.
