### ISSUE TITLE
Task :app:transformDexArchiveWithDexMergerForDebug FAILED

### ISSUE THREAD

**Issue by uendar** [facebook/react-native#28238]
I just created new RN project with latest version and installed some module. When i run project in debug mode i get:

> > Task :app:transformDexArchiveWithDexMergerForDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithDexMergerForDebug'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives:
  The number of method references in a .dex file cannot exceed 64K.
  Learn how to resolve this issue at https://developer.android.com/tools/building/multidex.html

**Comment by uendar** [comment]
I tried to add 

> dependencies {
>     def multidex_version = "2.0.1"
>     implementation 'androidx.multidex:multidex:$multidex_version'
> }


But same error

**Comment by ardyfeb** [comment]
Make sure you have set `multiDexEnabled true`

```
    android {
        defaultConfig {
            ...
            minSdkVersion 15
            targetSdkVersion 28
            multiDexEnabled true
        }
        ...
    }

    dependencies {
      implementation 'com.android.support:multidex:1.0.3'
    }
    
```

**Comment by marktoope** [comment]
you can add

yourApp/android/app/build.gradle

....

 buildTypes {
        debug {
            signingConfig signingConfigs.debug
        //add
            multiDexEnabled true
        }
        release {
            // Caution! In production, you need to generate your own keystore file.
            // see https://facebook.github.io/react-native/docs/signed-apk-android.
            signingConfig signingConfigs.debug
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        //add
            multiDexEnabled true

        }
    }
