### ISSUE TITLE
Android ACTIVITY_RECOGNITION permission | Android Q

### ISSUE THREAD

**Issue by vsk-pvr** [facebook/react-native#28231]
Description:

    Since the Android Q release google introduced 'android.permission.ACTIVITY_RECOGNITION' a run time permission. (https://developer.android.com/about/versions/10/privacy/changes#physical-activity-recognition). React Native permission(https://reactnative.dev/docs/permissionsandroid) should support this new permission.  

https://github.com/facebook/react-native/blob/c0d8c1db9077d08c3832b23e959bf70ad204307d/Libraries/PermissionsAndroid/PermissionsAndroid.js#L38

**Comment by hey99xx** [comment]
if you add it and send a PR, I suppose it'd be accepted
