### ISSUE TITLE
in react-native release package , libjsc.so have some safe compile options issue

### ISSUE THREAD

**Issue by lvdengmei** [facebook/react-native#28234]
Description:
    we use react-native 0.59.10, when we use the binscope  0.3.4 check the compile options, and find that libjsc.so BIND_NOW and Strip result is No. the libjsc.so is from jsc-android library, and react-native use the binary . so how to fix it and pass the compile options check.
    react-native 0.59.10  check result:
   
![image](https://user-images.githubusercontent.com/13557137/75965710-26949100-5f04-11ea-9bb7-b988ab32c43e.png)
    latest release version 0.61.5 check result:
![image](https://user-images.githubusercontent.com/13557137/75966630-9e16f000-5f05-11ea-93d7-291da289ebe8.png)
  in 0.6x.x have remove the jsc-android 

React Native version:
  0.59.10
    Run `react-native info` in your terminal and copy the results here.

## Steps To Reproduce
    1.uzip the react-native/android/com/facebook/react/react-native/0.59.10/react-native-0.59.10.aar
    2. get the so library in the jni/armeabi-v7a
    3. use the binscope tool check the armeabi-v7a
    4. check the scan result ,you can find this issue

## Expected Results
    excpect all library can meet the safe compile options . avoid security risk

## Snack, code example, screenshot, or link to a repository:
jsc-android should add safe compile options in build script
-s and -z,now

**Comment by hramos** [comment]
It looks like this is not an issue in 0.61.
