### ISSUE TITLE
[Android] Height and Width is not fixed

### ISSUE THREAD

**Issue by cnkyrpsgl** [facebook/react-native#28235]
Description:

    In the official document it says "All dimensions in React Native are unitless, and represent density-independent pixels." [https://reactnative.dev/docs/height-and-width]

	React native gives buttons responsive size even the height is given fixed and style is not overwritten by anything. It says dimensions represents density independent pixels  but it behaves so. I expect my buttons to be same height on different devices independent of pixels and size.

React Native Info:

    System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
    Memory: 468.47 MB / 16.00 GB
    Shell: 5.0.9 - /usr/local/bin/bash
  Binaries:
    Node: 12.14.1 - /usr/local/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: ^16.12.0 => 16.12.0 
    react-native: ^0.61.4 => 0.61.4 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native: 0.61.5

## Expected Results

    I expect my buttons to be same height on different devices independent of pixels and [size.](url
![Screen Shot 2020-03-05 at 09 29 28](https://user-images.githubusercontent.com/31376095/75977596-ce529480-5eed-11ea-8212-a37a1c23c5be.png)
)

**Comment by prasannabisen** [comment]
can I work on this?

**Comment by fabriziobertoglio1987** [comment]
This issues needs to be closed

This is exactly what hi / low dpi should look like

Research about dpi online and then close this issue

It is not a big, it is a feature.. otherwise how can I make button bigger on 4k screen!

**Comment by cnkyrpsgl** [comment]
@fabriziobertoglio1987 i would give percentage size like height: ‘30%’ if i want to make it look similar. Your argument doesn’t give a solution if i want to make a fixed size element.

**Comment by fabriziobertoglio1987** [comment]
this is not stackoverflow, I don't have to give you a solution. Issues are opened to fix bugs in the source code. It's mathematical impossible having different dpi and same resolution and same size in buttons. The foundations of your issue is mathematical impossible

**Comment by fabriziobertoglio1987** [comment]
@cnkyrpsgl Do you have a reproducible example so that I can investigate this issue? Thanks
