### ISSUE TITLE
[Crash Android app] App is crashing after compile.

### ISSUE THREAD

**Issue by aakashgolui** [facebook/react-native#28232]
Description:

 After load the js bundler the app is crashing immediately. 

React Native version:

    System:
    OS: Linux 5.3 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (6) x64 Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
    Memory: 2.30 GB / 7.72 GB
    Shell: 5.4.2 - /usr/bin/zsh
  Binaries:
    Node: 12.15.0 - ~/.nvm/versions/node/v12.15.0/bin/node
    npm: 6.13.7 - ~/.nvm/versions/node/v12.15.0/bin/npm
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.4 => 0.61.4

**Comment by aakashgolui** [comment]
Sorry its the problem with the gradel.

**Comment by garfiaslopez** [comment]
@aakashgolui Hey! How did you fix this? I'm facing the same problem and I completely stuck :c Any help will be appreciated, thanks!
