### ISSUE TITLE
FlatList's RTL rendering broken for Android

### ISSUE THREAD

**Issue by cp-rf** [facebook/react-native#28247]
Description:
  The Flat list component works fine for iOS for both the cases when RTL is forced and in case when it is not. 
But in case of Android, it doesn't work fine when RTL is forced, in case the content which it needs to render doesn't exceeds the frame of the FlatList. In such case FlatList Renders content from LTR and not RTL.

![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/47721938/76079253-48f0e200-5fca-11ea-8e96-065a9b7e7dd4.jpeg)

![MicrosoftTeams-image (7)](https://user-images.githubusercontent.com/47721938/76010894-a4bf5a80-5f39-11ea-913d-d3b517c73da3.jpeg)
    

React Native version:

    System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 1.41 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.1.0 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 28.0.3, 29.0.0
      System Images: android-23 | Google APIs ARM EABI v7a, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1

## Steps To Reproduce

  import React, {Component} from 'react';
import {
  StyleSheet,
  View,
  FlatList,
  I18nManager,
  Text,
  Dimensions,
} from 'react-native';
const {width} = Dimensions.get('window');

const guidelineBaseWidth = 375;

const scale = size => (width / guidelineBaseWidth) * size;
I18nManager.forceRTL(true);

export class SignInScreen extends Component {
  render() {
    const DATA = [
      {
        id: 'bd7acbea-c1b1-46c2-aed5-3ad53abb28ba',
        title: 'First Item',
      },
      {
        id: '3ac68afc-c605-48d3-a4f8-fbd91aa97f63',
        title: 'Second Item',
      },
    ];
    return (
      <View style={styles.container}>
        <View>
          <FlatList
            style={{backgroundColor: 'red'}}
            horizontal={true}
            data={DATA}
            renderItem={({item}) => (
              <View
                style={{
                  backgroundColor: '#f9c2ff',
                  padding: 20,
                  marginVertical: 8,
                  marginHorizontal: 16,
                }}>
                <Text style={styles.title}>{item.title}</Text>
              </View>
            )}
            keyExtractor={item => item.id}
          />
        </View>
      </View>
    );
  }
}
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  header: {
    width: '100%',
    height: scale(215),
    alignItems: 'center',
    justifyContent: 'center',
  },
  logo: {
    width: scale(130),
    height: scale(40),
  },
});

## Expected Results

![Simulator Screen Shot - iPhone X - 2020-03-06 at 11 22 33](https://user-images.githubusercontent.com/47721938/76056483-b554ec80-5f9c-11ea-9a69-f443836babb3.png)

First Item should be right aligned and not left aligned

**Comment by Ketn** [comment]
+1

**Comment by H4ckint0sh** [comment]
+1

**Comment by AliHaidar110** [comment]
same issue
