### ISSUE TITLE
Inconsistent resource bundle in release mode

### ISSUE THREAD

**Issue by hamidsani** [facebook/react-native#28243]
## Description

   I have a pretty large application that our team has been working on for over a year and deployed without any issue. But in the last month I have noticed that on certain screens when I create a release build, assets are incorrectly bundled. For example the image below there are 2 different distinct imports:
```
import PositiveIcon from 'native/statics/icons/thumbsUp.png';
import NegativeIcon from 'native/statics/icons/negativeFeedback.png';
```

![image](https://user-images.githubusercontent.com/7751704/76032231-47ea8280-5eee-11ea-86fb-613c1fbc2fe8.png)

They appear fine in debug mode but I see some inconsistencies throughout the app. Sometimes the thumbs are pointed down. No matter what I do I can't seem to fix the issue. Here are the original assets:
![negativeFeedback](https://user-images.githubusercontent.com/7751704/76433722-574c4e80-637a-11ea-8d79-5bd220834b44.png)
![thumbsUp](https://user-images.githubusercontent.com/7751704/76433728-59161200-637a-11ea-8c50-48c94105127f.png)

I even moved the entire build to AWS to eliminate such issue to no avail. So tried both builds in Linux and Windows. 

React Native version:
```
    System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 1.89 GB / 15.84 GB

  Binaries:
    Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.21.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.7 - C:\Program Files\nodejs\npm.CMD

  SDKs:
    Android SDK:
      API Levels: 18, 19, 21, 22, 23, 24, 25, 26, 27, 28, 29
      Build Tools: 19.1.0, 21.1.2, 22.0.1, 23.0.1, 23.0.3, 25.0.0, 25.0.2, 26.0.1, 27.0.3, 28.0.2, 28.0.3
      System Images: android-24 | Google APIs Intel x86 Atom, android-27 | Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom    

  IDEs:
     Android Studio: Version  3.5.0.0 AI-191.8026.42.35.6010548

npmPackages:
    react: ^16.9.0 => 16.12.0
    react-native: ^0.61.5 => 0.61.5
```

## Steps To Reproduce

   Here is my build script:

```
react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
rm -r android/app/src/main/res/raw
rm -r android/app/src/main/res/drawable-*
cd android
chmod +x ./gradlew
./gradlew clean
./gradlew assembleRelease
```
I also tried not removing the raw and drawable and instead build with `./gradlew assembleRelease -x bundleReleaseJsAndAssets`

**Comment by safaiyeh** [comment]
Hi @hamidsani thanks for the issue. For the team to be able to investigate this, could you provide a minimum reproducible repo that demonstrates the issue.
