### ISSUE TITLE
[CI] Migrate Windows builds to Circle CI

### ISSUE THREAD

**Issue by hramos** [facebook/react-native#28241]
First, some background: The Facebook Open Source team has been working on improving the tooling that supports this open source repository. For example, whenever a Facebook engineer is working on a change to React Native using our internal source control tooling, they can export their patch to a GitHub PR against the open source repository. When they do that, any failures in external CI will be reported alongside our own internal test results.

As it happens, AppVeyor is not widely used at Facebook, and its integration with our internal tooling will no longer be supported in the future. Historically, React Native used AppVeyor because Circle CI did not support Windows. Now that [Circle CI has Windows support](https://circleci.com/docs/2.0/hello-world-windows/), we can consolidate on a single CI again.

If you are interested in working on this, please comment below. You can find the existing AppVeyor config at https://github.com/facebook/react-native/blob/master/.appveyor/config.yml and the Circle CI config at https://github.com/facebook/react-native/blob/master/.circleci/config.yml You can find an example of the work required to do this by looking at the React pull request where they moved away from AppVeyor: https://github.com/facebook/react/pull/17984

**Comment by Naturalclar** [comment]
@hramos Could I work on this?
