### ISSUE TITLE
Pods/boost-for-react-native/boost/compatibility/cpp_c_headers/cstdlib:11:11: error: no member named 'abort' in the global namespace  

### ISSUE THREAD

**Issue by alertross** [facebook/react-native#28248]
Description:

When I integrated Rect-Native into my existing project, I got the following error:

React Native version:
{
  "name": "PetParadise_User",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "yarn react-native start"
  },
  "dependencies": {
    "react": "16.9.0",
    "react-native": "^0.61.5"
  }
}

## Snack, code example, screenshot, or link to a repository:

The error message is as follows:
In file included from /Users/liuqiang/Desktop/PetPro 2/PetParadise_User/PetParadise_User/PetParadise-User-Prefix.pch:17:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIKit.h:8:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:18:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/usr/include/assert.h:44:
In file included from Pods/Folly/folly/portability/stdlib.h:19:
Pods/boost-for-react-native/boost/compatibility/cpp_c_headers/cstdlib:11:11: error: no member named 'abort' in the global namespace
  using ::abort;
        ~~^
Pods/boost-for-react-native/boost/compatibility/cpp_c_headers/cstdlib:12:11: error: no member named 'atexit' in the global namespace
  using ::atexit;
        ~~^
Pods/boost-for-react-native/boost/compatibility/cpp_c_headers/cstdlib:13:11: error: no member named 'exit' in the global namespace
  using ::exit;
        ~~^
Pods/boost-for-react-native/boost/compatibility/cpp_c_headers/cstdlib:14:11: error: no member named 'getenv' in the global namespace
  using ::getenv;
        ~~^
Pods/boost-for-react-native/boost/compatibility/cpp_c_headers/cstdlib:15:11: error: no member named 'system' in the global namespace
  using ::system;
        ~~^
Pods/boost-for-react-native/boost/compatibility/cpp_c_headers/cstdlib:16:11: error: no member named 'calloc' in the global namespace
  using ::calloc;
        ~~^
Pods/boost-for-react-native/boost/compatibility/cpp_c_headers/cstdlib:17:11: error: no member named 'malloc' in the global namespace
  using ::malloc;
        ~~^
Pods/boost-for-react-native/boost/compatibility/cpp_c_headers/cstdlib:18:11: error: no member named 'free' in the global namespace
  using ::free;
        ~~^
Pods/boost-for-react-native/boost/compatibility/cpp_c_headers/cstdlib:19:11: error: no member named 'realloc' in the global namespace
  using ::realloc;
        ~~^
Pods/boost-for-react-native/boost/compatibility/cpp_c_headers/cstdlib:20:11: error: no member named 'atol' in the global namespace
  using ::atol;
        ~~^
Pods/boost-for-react-native/boost/compatibility/cpp_c_headers/cstdlib:21:11: error: no member named 'mblen' in the global namespace
  using ::mblen;
        ~~^
Pods/boost-for-react-native/boost/compatibility/cpp_c_headers/cstdlib:22:11: error: no member named 'strtod' in the global namespace
  using ::strtod;
        ~~^
Pods/boost-for-react-native/boost/compatibility/cpp_c_headers/cstdlib:23:11: error: no member named 'wctomb' in the global namespace
  using ::wctomb;
        ~~^
Pods/boost-for-react-native/boost/compatibility/cpp_c_headers/cstdlib:24:11: error: no member named 'atof' in the global namespace
  using ::atof;
        ~~^
Pods/boost-for-react-native/boost/compatibility/cpp_c_headers/cstdlib:25:11: error: no member named 'mbstowcs' in the global namespace
  using ::mbstowcs;
        ~~^
Pods/boost-for-react-native/boost/compatibility/cpp_c_headers/cstdlib:26:11: error: no member named 'strtol' in the global namespace
  using ::strtol;
        ~~^
Pods/boost-for-react-native/boost/compatibility/cpp_c_headers/cstdlib:27:11: error: no member named 'wcstombs' in the global namespace
  using ::wcstombs;
        ~~^
Pods/boost-for-react-native/boost/compatibility/cpp_c_headers/cstdlib:28:11: error: no member named 'atoi' in the global namespace
  using ::atoi;
        ~~^
Pods/boost-for-react-native/boost/compatibility/cpp_c_headers/cstdlib:29:11: error: no member named 'mbtowc' in the global namespace
  using ::mbtowc;
        ~~^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.

**Comment by alexlevy0** [comment]
@alertross did you fix this error ?

**Comment by suwu150** [comment]
How to solve it?
