### ISSUE TITLE
Unable to run app on android (npx react-native run-android)

### ISSUE THREAD

**Issue by contactmukulsaini** [facebook/react-native#28255]
Description:
I have followed the instructions on https://reactnative.dev/docs/getting-started to setup my React Native CLI app. Everything have been installed and setup as documented (a fresh application) but when I run the command "npx react-native run-android", then I get the error regarding gradle.

React Native info:
C:\Users\muks\Documents\Shabdkoshish\dev\FunKhelHN>npx react-native info
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.17134
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 26.42 GB / 31.84 GB
  Binaries:
    Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29
      Build Tools: 19.1.0, 20.0.0, 21.1.2, 22.0.1, 23.0.3, 24.0.3, 25.0.3, 26.0.3, 27.0.3, 28.0.3, 29.0.2, 29.0.3
      System Images: android-28 | Intel x86 Atom, android-28 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5056338
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5

React Native version:
C:\Users\muks\Documents\Shabdkoshish\dev\FunKhelHN>npx react-native --version
3.2.1

C:\Users\muks\Documents\Shabdkoshish\dev\FunKhelHN>npm -v
6.9.0

C:\Users\muks\Documents\Shabdkoshish\dev\FunKhelHN>gradle -v

------------------------------------------------------------
Gradle 6.2.2
------------------------------------------------------------

Build time:   2020-03-04 08:49:31 UTC
Revision:     7d0bf6dcb46c143bcc3b7a0fa40a8e5ca28e5856

Kotlin:       1.3.61
Groovy:       2.5.8
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          1.8.0_221 (Oracle Corporation 25.221-b27)
OS:           Windows 10 10.0 amd64

Error:
C:\Users\muks\Documents\Shabdkoshish\dev\FunKhelHN>npx react-native run-android
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 864 file(s) to forward-jetify. Using 12 workers...
info Starting JS server...
info Installing the app...
'gradlew.bat' is not recognized as an internal or external command,
operable program or batch file.

error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
'gradlew.bat' is not recognized as an internal or external command,
operable program or batch file.

    at checkExecSyncError (child_process.js:629:11)
    at execFileSync (child_process.js:647:13)
    at runOnAllDevices (C:\Users\muks\Documents\Shabdkoshish\dev\FunKhelHN\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:94:39)
    at buildAndRun (C:\Users\muks\Documents\Shabdkoshish\dev\FunKhelHN\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:179:41)
    at then.result (C:\Users\muks\Documents\Shabdkoshish\dev\FunKhelHN\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:133:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)

## Expected Results
    App must run in the attached android phone (My device is listed in adb devices also).

**Comment by chakrihacker** [comment]
You can try running `react-native run-android` or `npm run react-native run-android`
Maybe docs needs to be updated

**Comment by contactmukulsaini** [comment]
> You can try running `react-native run-android` or `npm run react-native run-android`
> Maybe docs needs to be updated

@chakrihacker Thanks for your comment.
I have tried both the commands but the error is still the same.

**Comment by ccfz** [comment]
Did you get the app to build and run in the emulator? I.e. is this a problem with the device installation or a problem with the app build not running in general.

**Comment by Juke-99** [comment]
I also experienced that problem. I then used version of openJDK is 13.0.1. I could run I fixed the openJDK version to 12.0.2.
