### ISSUE TITLE
CxxNativeModule::invoke is copying parameters that are meant to be moved

### ISSUE THREAD

**Issue by mmallet-youilabs** [facebook/react-native#28271]
### Description:

The `CxxNativeModule::invoke` function [makes use of a lambda](https://github.com/facebook/react-native/blob/0.62-stable/ReactCommon/cxxreact/CxxNativeModule.cpp#L136-L159) to run a native module function on the message queue thread. However the lambda isn't marked as `mutable` -- this prevents the `params` capture from being movable [when calling the method itself](https://github.com/facebook/react-native/blob/0.62-stable/ReactCommon/cxxreact/CxxNativeModule.cpp#L146). If the `params` argument is expensive to copy, this can impact performance.

### React Native version:

This can be seen in v0.62.

Steps to reproduce (and expected results) are not applicable (unless running with a profiler).

**Comment by hramos** [comment]
Thanks for bringing this to our attention. Do you think you can send a PR to address this?

**Comment by mmallet-youilabs** [comment]
I was going to, but unfortunately getting the CLA signed is too high a bar :(

**Comment by hramos** [comment]
Oh, sorry to hear that. Are there any particular concerns?

**Comment by maschad** [comment]
I could look into this @hramos

**Comment by mmallet-youilabs** [comment]
@hramos just that I'd need to get it signed on behalf of the company I work for, which means lawyers and all that. It's been talked about before so I'm sure we'll get it done at some point

@maschad thanks! 👍
