### ISSUE TITLE
Duplicate protocol definition of 'RCTBridgeModule' is ignored

### ISSUE THREAD

**Issue by shiios** [facebook/react-native#28273]
Description:

 Mac ：10.15.3
Xcode: 11.3

React Native version:

    "react": "^16.0.0-alpha.6",
    "react-native": "0.43.4",

## Steps To Reproduce

    Provide a detailed list of steps that reproduce the issue.
    Issues without reproduction steps or code are likely to stall.

1.
![image](https://user-images.githubusercontent.com/14368983/76275316-f2cbb980-62bd-11ea-8bb9-977635c48f23.png)

2.
![Snip20200310_29](https://user-images.githubusercontent.com/14368983/76275494-6a014d80-62be-11ea-8869-b8b90c858685.png)
![Snip20200310_30](https://user-images.githubusercontent.com/14368983/76275506-708fc500-62be-11ea-9b75-4fba95b3ffda.png)

## Expected Results

    Xcode can run it normal

## Snack, code example, screenshot, or link to a repository:

    Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
    You may provide a screenshot of the application if you think it is relevant to your bug report.
    Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by chrisglein** [comment]
0.43 is pretty old at this point, and not guaranteed to work with xcode 11.3. Can you please test on latest?
