### ISSUE TITLE
Changing visibility of status bar affect flexibility on android

### ISSUE THREAD

**Issue by devildummy** [facebook/react-native#28276]
Description:

With default android:windowSoftInputMode, when you have a { flex: 1 } view
 
<details>
  <summary>View with wide border</summary>
  
![close](https://user-images.githubusercontent.com/37071920/76309914-d2f8bd80-62de-11ea-9dfa-c2a9d7995873.jpg)
</details>

and open keyboard, it must push the view above the keyboard.

<details>
  <summary>Keybord open when status bar is visible (look at the red bottom border above keyboard)</summary>
  
![open_true](https://user-images.githubusercontent.com/37071920/76309927-dbe98f00-62de-11ea-8503-eb383cd9fbbb.jpg)
</details>

But when you hide the status bar and open keyboard, view stay the same.

<details>
  <summary>Keybord open when status bar is hidden (there is no red bottom border above keyboard)</summary>
  
![open_false](https://user-images.githubusercontent.com/37071920/76309959-ed329b80-62de-11ea-8091-91b8e9a733b3.jpg)

</details>

React Native version: 0.61.5

## Steps To Reproduce

1. Create view with flex: 1 and text input
2. Tap the input

If your status bar is hidden (by StatusBar.setHidden(true) or by \<StatusBar hidden={true} />, doesnt matter), keyboard will not push view to top

## Expected Results

    StatusBar doesnt affect flexibility

## Additioanl info
  
  Hiding / showing navbar work as expected

Snack example, but bug dont reproduce on it) just a code to copy
https://snack.expo.io/@devildummy/surprised-juice-box
idk how to change android:windowSoftInputMode on Snack, maybe here is a problem, if you create own project with exact code, you will see a problem

**Comment by chrisglein** [comment]
Interesting issue, thank you for the screenshots. Can you put together a Snack of this minimal repo to make it easier to investigate?

**Comment by devildummy** [comment]
@chrisglein Add link to additional info, but on Snack this bug dont reproduce, so it just code to copy :)
