### ISSUE TITLE
[iOS] Crash in RCTWebSocketModule didFailWithError

### ISSUE THREAD

**Issue by Etienne-M** [facebook/react-native#28278]
Description:

We're seeing some crashes in our Crashlytics dashboard with the following error:
```
Fatal Exception: NSInvalidArgumentException
*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]
```
coming from
```
RCTWebSocketModule.m
-[RCTWebSocketModule webSocket:didFailWithError:]
```

React Native version: 0.61.5

## Steps To Reproduce

Unknown, although having a WebSocket would be a good start to reproduce.

## Expected Results

The app should not crash.

**Comment by xiao99xiao** [comment]
This issue exists for a long time. The reason is the `socketID` and `error` in RCTWebSocketModule.m could sometimes be `nil` .
I patched the file like below and it never bothered me again.
```
-    @"message": error.localizedDescription,
-    @"id": socketID
+    @"message": error.localizedDescription ?: @"",
+    @"id": socketID ?: @(-1)
```

**Comment by chrisglein** [comment]
Can you produce a minimal repo so we can narrow this down? (e.g. a Snack or pointer to a repo of a minimal repo)
You provided the version (thank you!), but can you run 'react-native info' to get the rest of the context?

**Comment by Etienne-M** [comment]
> Can you produce a minimal repo so we can narrow this down? (e.g. a Snack or pointer to a repo of a minimal repo)
> You provided the version (thank you!), but can you run 'react-native info' to get the rest of the context?

Hello! Sorry, it took me a while to get you this info. There you:
```
System:
OS: macOS Mojave 10.14.6
CPU: (3) x64 Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
Memory: 10.96 GB / 16.00 GB
Shell: 3.2.57 - /bin/bash
Binaries:
Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
npm: 6.14.3 - ~/.nvm/versions/node/v12.13.0/bin/npm
SDKs:
iOS SDK:
Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
IDEs:
Xcode: 11.3.1/11C505 - /usr/bin/xcodebuild
npmPackages:
@react-native-community/cli: 3.0.4 => 3.0.4
react: 16.9.0 => 16.9.0
react-native: 0.61.5 => 0.61.5
```
As for steps to reproduce, I can't really help you with that, I'm sorry

**Comment by luatnd** [comment]
This issue still occurs
