### ISSUE TITLE
Android ignores unicode soft hyphen (u00AD)

### ISSUE THREAD

**Issue by ccfz** [facebook/react-native#28279]
Description:
On android soft-hyphen unicode `u00AD` is ignored, neither the word break nor the hyphen are displayed correctly. Using `u200B` is a workaround for getting better word wrapping results but is still missing the hyphen. 

React Native version:

```
System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 108.98 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.10.1 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.7 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.0, 29.0.1
      System Images: android-28 | Google Play Intel x86 Atom, android-29 | Intel x86 Atom_64
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.12.0 => 16.12.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

## Steps To Reproduce

Render the following on android vs. iOS

```javascript
const testString = 'sup\u00ADer\u00ADfrag\u00ADilis\u00ADtice\u00ADxpial\u00ADidocious'

return (
  <View>
    <Text style={{ width: 100 }}>
      {testString}
    </Text>
  </View>
);
```

## Expected Results

Screenshot from iOS
![IMG_DB2643BEA609-1](https://user-images.githubusercontent.com/6050682/76325546-bb720280-62e7-11ea-98ae-aba541486e13.jpeg)

## Actual Result 
Screenshot from Android
![IMG_25E611476E59-1](https://user-images.githubusercontent.com/6050682/76325607-d04e9600-62e7-11ea-8398-0811775e5970.jpeg)

**Comment by plaa** [comment]
This makes it very hard / practically impossible to get proper when-needed hyphenation on Android. iOS works perfectly and is easy to make buttons that properly wrap the text only when needed.

**Comment by lennartdemeij** [comment]
What would the 'very hard' way be to get the hyphenation working on Android with this version of React Native? I'm experiencing the same bug...

**Comment by ccfz** [comment]
Good question, you would need to build some kind of regex/matcher that checks for `u200B` followed by a new line and append "-" if it matches. Don't know if that is possible but it would be my first guess for a workaround.

**Comment by fabriziobertoglio1987** [comment]
seems to me that this is the default android behaviour https://stackoverflow.com/questions/4454911/hyphenation-in-android

**Comment by lennartdemeij** [comment]
That was my thought as well, however, I don't know of any method to check where the new line starts/old line breaks...

**Comment by ochrstn** [comment]
> hyphenedText += line.text.substr(0, line.text.length - 1) + "- ";

With this solution I have some weird effects because the changed text (additional "- ") is triggering the onTextLayout again, which is performing changes again because the text has to change again ... in an endless loop 🔁

**Comment by lennartdemeij** [comment]
I'm checking for that as well.
 ```
if (line.text.substr(line.text.length - 2) === "- ") {
  alreadyHyphenated = true;
 }
```

and I don't change the text again if alreadyHyphenated === true

**Comment by ochrstn** [comment]
> It also sometimes brings the hyphenated word to the next line because the added dash pushes it over the edge. I'll have to think of a solution for that as well...

Yes, that's what I'm experiencing right now too. Almost all dashes are within the words because the new lines breaks are different after adding the dashes.

**Comment by fabriziobertoglio1987** [comment]
as we can read [in this medium article](https://medium.com/@tkuenneth/about-hyphenation-in-android-q-2a684ae6c465) it is possible on android thanks to [setHyphenationFrequency](https://developer.android.com/reference/android/widget/TextView)

so I solved this in native code like this in ReactTextView.java:

![image](https://user-images.githubusercontent.com/24992535/84877820-41d97580-b089-11ea-9b01-192e2529b6e9.png)

I'll write a pull request to add a prop `<Text androidHyphenationFrequency="normal" />`

**Comment by fabriziobertoglio1987** [comment]
this functionality will be available with 0.64 https://github.com/react-native-community/releases/blob/20a632d3a61153f813c020ef2c6bca6910958a10/CHANGELOG.md Thanks :pray:

**Comment by AnisDerbel** [comment]
Can someone confirm here that this is working in react-native 0.64? because it is not working for me (tested with device > v23) cc @fabriziobertoglio1987

**Comment by leethree** [comment]
it doesn't work for me either.

**Comment by henrik-d** [comment]
@fabriziobertoglio1987 It does not work for me either. 
```
 const testString = 'sup\u00ADer\u00ADfrag\u00ADilis\u00ADtice\u00ADxpial\u00ADidocious';

  return (
    <Text style={{ fontSize: 32, color: 'white' }} android_hyphenationFrequency={'normal'}>
      {testString}
    </Text>
  );
```
The word is breaking `superfragilisticexpiaid ocious` and without hyphen. Is there something wrong with my code?

**Comment by fabriziobertoglio1987** [comment]
https://developer.android.com/reference/android/widget/TextView#setHyphenationFrequency(int)

>setHyphenationFrequency
>Sets the frequency of automatic hyphenation to use when determining word breaks.

**Comment by luanccp** [comment]
it doesn't work for me either. 
@fabriziobertoglio1987 do you have some code examples?
