### ISSUE TITLE
New Xcode break the app

### ISSUE THREAD

**Issue by nosensezzz** [facebook/react-native#2827]
Hi, Guys

After I upgrade the xcode to latest version today, my react native app got broken.

The build is success with some warning(which I don't have before, same images issue), but when launch the app in the simulator, I got error "could not connect to development server. Ensure node server is running and available on the same network ..."

Does anyone have same issue like me?

**Comment by ide** [comment]
This is related to App Transport Security. I forget the specifics but you should google around to learn how to whitelist localhost or all domains in your Info.plist.

**Comment by dsibiski** [comment]
Here is Apple's documentation on it: https://developer.apple.com/library/prerelease/ios/technotes/App-Transport-Security-Technote/index.html

**Comment by nosensezzz** [comment]
I saw another issue pretty similar to this one, and I also saw how ppl resolved it, so I closed the issue.
