### ISSUE TITLE
Cuál método utilizar class o arrow functions para crear un componente en cualquier framework

### ISSUE THREAD

**Issue by Luzmario1708** [facebook/react-native#28288]
Hola Grupo:

Tengo una duda.

Cual es la diferencia entre crear un componente arrow functions y hacerlo por medio de una clase, teniendo en cuenta que con arrow functions por medio de las propiedades que se pasen dentro del componente padre se pueden heredar al componente hijo:

**Componente que se crea con un arrow functions y hereda del componente padre unas propiedades:**

    const AppLogin = (props) => {
     
      const [user, setUser] = useState({ name: '', pass: '', entrada: 0 });
     
      const ingresar = () => {
        setUser( { entrada: 1 } )
      };
     
      let { entrada } = user;
      let { name } = user;
      let { pass } = user;
     
      return (
        <View style={styles.container}>
              {
                < Text />
              }
        </View>
      );
    }

**Componente que se crea como una clase: 
Clase Padre**

    class Animal {
        constructor (nombre, genero) {
            this.nombre = nombre;
            this.genero = genero;
        }
        sonar() {
            console.log('Hago sonidos porque estoy vivo');
        }
     
    }

**Clase hija**

    class Perro extends Animal {
        constructor(nombre, genero, tamanio) {
            super( nombre, genero );
            this.tamanio = tamanio;
        }
        sonar() {
            console.log('Soy un perro y mi sonido es un ladrido');
        }
     
        ladrar() {
            console.log('Guauuuu, Guauuuuu!!');
        }
    }
    const scooby = new Perro('Scooby', 'Macho', 'Gigante');
     
    console.log(scooby);

La idea es que si se cambia de framework no se tenga traumatismos en el código, sea algo más universal.

Agradezco si me pudiera aclarar está duda de forma sencilla.

Gracias por tu ayuda y colaboración.

Saludos.

**Comment by hramos** [comment]
Saludos. Típicamente, no consideramos preguntas en este repositorio, ya que es exclusivamente para mantener cuenta de problemas en React Native específicamente. En tu caso, me parece que tu duda es mas bien relacionada a React como tal. Te recomiendo que investigues cuales son tus opciones en https://reactjs.org/community/support.html

La gran mayoría de los que estamos pendientes a este repositorio somos de varios países, y solo tenemos como idioma en común el inglés, así que de brindar a luz algún problema con React Native en el futuro, sugiero utilizar inglés.
