### ISSUE TITLE
Border width differing between iOS and Android

### ISSUE THREAD

**Issue by CampbellMG** [facebook/react-native#28289]
### Description:

When adding a bottom/left border with a radius, the width and radius seem to be completely different on Android vs iOS. 

iOS
![ios](https://i.imgur.com/Q06Ts2H.png)

Android
![android](https://i.imgur.com/Vn4pg18.png)

The top view has the same width and radius as the bottom and matches on android/ios, however, when you remove the top border or top left radius as in the bottom view they look completely different.

React Native version: 0.61

## Steps To Reproduce

Create a component with a bottom left radius, left border width and bottom border width.

## Expected Results

The border width and radius should match between android and iOS 

## Snack, code example, screenshot, or link to a repository:

Use this code to reproduce the images from above, or use this [snack](https://snack.expo.io/@campbellmg/border-issue)

```
export default class App extends React.Component {
  render() {
    return (
      <View style={styles.container}>
      <View style={styles.semicircle}/>
      <View style={styles.corner}/>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: Constants.statusBarHeight,
    backgroundColor: '#ecf0f1',
    padding: 8,
  },
    semicircle: {
    borderBottomLeftRadius: 100,
    borderTopLeftRadius: 100,
    borderLeftWidth: 10,
    borderBottomWidth: 10,
    borderTopWidth: 10,
    height: 50,
    width: 50,
    borderColor: 'red'
  },
  corner: {
    borderBottomLeftRadius: 100,
    borderLeftWidth: 10,
    borderBottomWidth: 10,
    height: 50,
    width: 50,
    borderColor: 'red'
  },
});
```

**Comment by safaiyeh** [comment]
Appreciate the filling out the issue fields @CampbellMG. Confirmed that the issue exists
