### ISSUE TITLE
Not seeing metro bundler start up after executing `npx react-native run-ios`

### ISSUE THREAD

**Issue by rencire** [facebook/react-native#28281]
Description:

 Not seeing metro bundler start up automatically after executing `npx react-native run-ios`.
   
Seeing the `launchPackager.command` open in a new Terminal window, but metro bundler does not seem to start correctly:
<img width="489" alt="Screen Shot 2020-03-10 at 5 58 42 PM" src="https://user-images.githubusercontent.com/546296/76372186-d2b9eb80-62f9-11ea-99df-8a8546b960dc.png">

Note: Metro bundler starts up fine when manually starting in a new shell via `npx react-native build`.

React Native version:

```
System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 162.72 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
```

## Steps To Reproduce

Same steps as creating a new react native project, as per the [docs](https://reactnative.dev/docs/getting-started.html):

1. `npx react-native init myproj3`
2. `cd myproj3`
3. `npx react-native run-ios`
4. Notice that metro bundler does not start up correctly.

## Expected Results

Expected metro bundler to start automatically in a new terminal window after running `npx react-native run-ios`.

## Snack, code example, screenshot, or link to a repository:

Output from `npx react-native run-ios`
<img width="1102" alt="Screen Shot 2020-03-10 at 5 59 06 PM" src="https://user-images.githubusercontent.com/546296/76372588-22e57d80-62fb-11ea-9f61-21db6222f169.png">

Resulting error in simulator from not having a js bundle:
<img width="421" alt="Screen Shot 2020-03-10 at 5 55 25 PM" src="https://user-images.githubusercontent.com/546296/76372237-fc731280-62f9-11ea-9d7d-5ced062b0913.png">

**Comment by ccfz** [comment]
Does `react-native start` open metro?

**Comment by rencire** [comment]
> Does `react-native start` open metro?

Yes it does when I run `npx react-native start`.

**Comment by ccfz** [comment]
I think this might be duplicate with this: https://github.com/facebook/react-native/issues/25509

**Comment by chrisglein** [comment]
Issue is resolved, moved to the CLI repo: https://github.com/react-native-community/cli/issues/484
That is resolved, but has some more recent comments. This seems to need a fresh investigation and should move to the CLI repo.

**Comment by hramos** [comment]
@rencire can you open this issue in the CLI repo?

**Comment by archfz** [comment]
Related hotfix for linux in  #28807
