### ISSUE TITLE
[Android][Linux] Building master RNTester on Linux fails while building Folly

### ISSUE THREAD

**Issue by willholen** [facebook/react-native#28298]
Description:

I'm on the latest git commit, and RNTester fails to build on Linux:

```
/tmp$ git clone https://github.com/facebook/react-native &&
   cd react-native &&
   npm install && 
   ./gradlew :RNTester:android:app:installJSCDebug
[...]
[armeabi-v7a] Compile++ thumb: folly_json <= FileUtil.cpp
make: Leaving directory '/tmp/react-native/ReactAndroid/src/main/jni/react/jni'
/tmp/react-native/ReactAndroid/build/third-party-ndk/folly/folly/FileUtil.cpp:37:14: error: no matching function for call to 'wrapNoInt'
  return int(wrapNoInt(open, name, flags, mode));
             ^~~~~~~~~
/tmp/react-native/ReactAndroid/build/third-party-ndk/folly/folly/detail/FileUtilDetail.h:34:9: note: candidate template ignored: couldn't infer template argument 'F'
ssize_t wrapNoInt(F f, Args... args) {
        ^
1 error generated.
make: *** [/tmp/fetchleak/sdk/ndk-bundle/build/core/build-binary.mk:478: /tmp/react-native/ReactAndroid/build/tmp/buildReactNdkLib/local/armeabi-v7a/objs/folly_json/folly/FileUtil.o] Error 1
make: *** Waiting for unfinished jobs....
[...]
make: Leaving directory '/tmp/react-native/ReactAndroid/src/main/jni/react/jni'

> Task :ReactAndroid:buildReactNdkLib FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':ReactAndroid:buildReactNdkLib'.
> Process 'command '/tmp/fetchleak/sdk/ndk-bundle/ndk-build'' finished with non-zero exit value 2
```

React Native version:

Git master, commit 5ebca708132be8720c28a565e03b04e1087326cf from Mar 12 (Android SDK downloaded today, commandlinetools-linux-6200805_latest.zip)

## Steps To Reproduce

0. Be on Linux. The problem does not appear on macOS. 
1. git clone https://github.com/facebook/react-native
2. cd react-native
3. npm install
4. ./gradlew :RNTester:android:app:installJSCDebug

## Expected Results

I expected RNTester to run

## Snack, code example, screenshot, or link to a repository:

https://github.com/facebook/react-native/

The first commit that fails is 6e2131b8fa85da8b3fb0391803e7fbecba890ffb, "Upgrade Folly to v2020.01.13.00 (#27811)". The preceding commit, a3cb377645f2ccb7632ded73c230a41025d38f6f, builds successfully.

**Comment by willholen** [comment]
I kludged around this by overwriting `ReactAndroid/build/third-party-ndk/folly/folly/FileUtil.cpp` with a version that defines `openNoInt` by copying the logic from `wrapNoInt` rather than calling it. I can then build successfully:

```
int openNoInt(const char* name, int flags, mode_t mode) {
  ssize_t r;
  do {
    r = open(name, flags, mode);
  } while (r == -1 && errno == EINTR);
  return r;
}
```

**Comment by tempbottle** [comment]
`wrapNoInt` error also appear on windows build. 
read here for help:
https://github.com/tempbottle/react-native/blob/master/downloads/Readme.md

**Comment by fabriziobertoglio1987** [comment]
what is the output of `ndk-build`? 
you probably downloaded the ndk [here](https://github.com/facebook/react-native/wiki/Building-from-source) otherwise you find it at `$ANDROID_SDK/ndk/<version>`

**Comment by hsource** [comment]
I have this problem as well on MacOS as well.

```
make: Entering directory '/Users/harry/react-native/ReactAndroid/src/main/jni/react/jni'
/Users/harry/react-native/ReactAndroid/build/third-party-ndk/folly/folly/FileUtil.cpp:37:14: error: no matching function for call to 'wrapNoInt'
[armeabi-v7a] Compile++ thumb: folly_json <= FileUtil.cpp
  return int(wrapNoInt(open, name, flags, mode));
make: Leaving directory '/Users/harry/react-native/ReactAndroid/src/main/jni/react/jni'
             ^~~~~~~~~
/Users/harry/react-native/ReactAndroid/build/third-party-ndk/folly/folly/detail/FileUtilDetail.h:34:9: note: candidate template ignored: couldn't infer template argument 'F'
ssize_t wrapNoInt(F f, Args... args) {
        ^
1 error generated.
make: *** [/Users/harry/Library/Android/sdk/ndk/21.1.6352462/build/core/build-binary.mk:478: /Users/harry/react-native/ReactAndroid/build/tmp/buildReactNdkLib/local/armeabi-v7a/objs/folly_json/folly/FileUtil.o] Error 1
```

My NDK version is 21.1.6352462. I haven't tested it with other versions:

**Comment by hsource** [comment]
As of the latest master ~1 week ago, this is still an issue. Perhaps updating `folly` will fix it?

**Comment by safaiyeh** [comment]
Checked Folly's master it looks like it still has this. Should this be raised with Folly?

**Comment by psionic12** [comment]
The problem still exists, I tried ndk 21 and 22 and both report this error.

**Comment by Kudo** [comment]
created a pr for folly to address this: https://github.com/facebook/folly/pull/1593
this may not have much difference to the workaround but should explain why this broken after ndk r21.

**Comment by cortinico** [comment]
> The problem still exists, I tried ndk 21 and 22 and both report this error.

Can someone give it another try. I've been pushing a lot of changes to the NDK setup recently and I believe folly + NDK21 + Linux setup should be good to go 👍
