### ISSUE TITLE
are we using UIWebView ?

### ISSUE THREAD

**Issue by girish54321** [facebook/react-native#28306]
Description:
i got mail form apple
Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs starting from April 2020

React Native version:
IN MY PROJECT IM USEING   
       "react": "16.8.3",
       "react-dom": "16.8.3",
       "react-native": "0.59.10",
React Native Environment Info:
    System:
      OS: macOS 10.15.2
      CPU: (8) x64 Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz
      Memory: 1.74 GB / 8.00 GB
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.6.0 - /usr/local/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
      Android SDK:
        API Levels: 23, 26, 27, 28, 29
        Build Tools: 25.0.0, 26.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.2, 28.0.3
        System Images: android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.3/11C29 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.10 => 0.59.10 
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-cli: 2.0.1
      react-native: 0.61.5

## Steps To Reproduce

should have upload to testflight without error or warning

## Expected Results

    should have upload to testflight without error or warning

## Snack, code example, screenshot, or link to a repository:

 after running ---- grep -r UIWebView node_modules/*

Binary file node_modules/@philly25/react-native-paytm/ios/libPaymentsSDK.a matches
node_modules/@philly25/react-native-paytm/ios/PGTransactionViewController.h:@interface PGTransactionViewController : UIViewController <UIWebViewDelegate, UIActionSheetDelegate>
node_modules/@types/react-native/index.d.ts: * If true, use WKWebView instead of UIWebView.
node_modules/fbjs/lib/UserAgent.js.flow: * - UIWebView
node_modules/fbjs/lib/UserAgent.js: * - UIWebView
node_modules/metro/node_modules/fbjs/lib/UserAgent.js.flow: * - UIWebView
node_modules/metro/node_modules/fbjs/lib/UserAgent.js: * - UIWebView
node_modules/react-native/node_modules/fbjs/lib/UserAgent.js.flow: * - UIWebView
node_modules/react-native/node_modules/fbjs/lib/UserAgent.js: * - UIWebView
node_modules/react-native/Libraries/Components/WebView/WebView.android.js: * If true, use WKWebView instead of UIWebView.
node_modules/react-native/Libraries/Components/WebView/WebView.ios.js: * If true, use WKWebView instead of UIWebView.
node_modules/react-native/React/Views/RCTWebView.m:@interface RCTWebView () <UIWebViewDelegate, RCTAutoInsetsProtocol>
node_modules/react-native/React/Views/RCTWebView.m: UIWebView *_webView;
node_modules/react-native/React/Views/RCTWebView.m: _webView = [[UIWebView alloc] initWithFrame:self.bounds];
node_modules/react-native/React/Views/RCTWebView.m:#pragma mark - UIWebViewDelegate methods
node_modules/react-native/React/Views/RCTWebView.m:- (BOOL)webView:(__unused UIWebView *)webView shouldStartLoadWithRequest:(NSURLRequest *)request
node_modules/react-native/React/Views/RCTWebView.m: navigationType:(UIWebViewNavigationType)navigationType
node_modules/react-native/React/Views/RCTWebView.m: @(UIWebViewNavigationTypeLinkClicked): @"click",
node_modules/react-native/React/Views/RCTWebView.m: @(UIWebViewNavigationTypeFormSubmitted): @"formsubmit",
node_modules/react-native/React/Views/RCTWebView.m: @(UIWebViewNavigationTypeBackForward): @"backforward",
node_modules/react-native/React/Views/RCTWebView.m: @(UIWebViewNavigationTypeReload): @"reload",
node_modules/react-native/React/Views/RCTWebView.m: @(UIWebViewNavigationTypeFormResubmitted): @"formresubmit",
node_modules/react-native/React/Views/RCTWebView.m: @(UIWebViewNavigationTypeOther): @"other",
node_modules/react-native/React/Views/RCTWebView.m:- (void)webView:(__unused UIWebView *)webView didFailLoadWithError:(NSError *)error
node_modules/react-native/React/Views/RCTWebView.m: // Error code 102 "Frame load interrupted" is raised by the UIWebView if
node_modules/react-native/React/Views/RCTWebView.m:- (void)webViewDidFinishLoad:(UIWebView *)webView
node_modules/react-native-fbsdk/js/FBShareDialog.js: * Displays the dialog in a UIWebView within the app.
Binary file node_modules/react-native-maps/.gradle/4.10.3/taskHistory/taskHistory.bin matches
node_modules/react-native-webview/README.md:- 7.0.1 - Removed UIWebView
node_modules/ua-parser-js/test/browser-test.json: "ua" : "Mozilla/5.0 (iPhone; CPU iPhone OS 10_0_2 like Mac OS X) AppleWebKit/602.1.50 (KHTML, like Gecko) Mobile/14A456 QQ/6.5.3.410 V1_IPH_SQ_6.5.3_1_APP_A Pixel/1080 Core/UIWebView NetType/WIFI Mem/26",

**Comment by hramos** [comment]
Please see https://reactnative.dev/blog/2018/08/27/wkwebview

**Comment by girish54321** [comment]
are you using the WebView component? 
ANS = No
im useing react-native-webview version: 7.5.2 to show html data and render to screen
when i search for UIWebView then i saw some usage in react native and react native fbsdk ...(node_modules "folder") 
so should i upgrade to react-native  "0.59.10"-->"0.61.5" 
thanks for response ..
