### ISSUE TITLE
ImageBackground with width: '100%', height: '100%', in FlatList

### ISSUE THREAD

**Issue by codetoaj** [facebook/react-native#28301]
Description:
     I have to show a list with ImageBackground in a flatlist.  But the all the image in the list shown as single image with strange behavior. Anyhow I found the solution. This issue is related to #10256 will proper solution.

React Native version:
System:
    OS: Linux 4.19 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (4) x64 Intel(R) Core(TM) i3-6098P CPU @ 3.60GHz
    Memory: 1.57 GB / 7.69 GB
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
    npm: 6.13.4 - ~/.nvm/versions/node/v12.14.1/bin/npm
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5

## Steps To Reproduce
1. Create a view with ImageBackground as a list item
2. Pass it as renderItem to FlatList

## Expected Results
N number of list should shown with N Number of images.

## Snack, code example, screenshot, or link to a repository:
Sorry I can't share the screen shot or code

**Comment by codetoaj** [comment]
```
        <ImageBackground 
          source={quickBookSample} 
          style={styles.bgImage}
          imageStyle={styles.bgImageStyle}
        >
          <View style={styles.detailInner}>
            <Text style={styles.detailTitle}>Blah blah</Text>
          </View>
          <Text style={styles.detailTime}>05:00 to 09:00</Text>
        </ImageBackground>

  bgImage: {
    width: '100%',
    height: 'auto',
    resizeMode: 'stretch',
    flex: 1
  },
```

This will help you to achieve the solution

**Comment by safaiyeh** [comment]
hi @codetoaj, could you provide a reproducible example with a fresh template. This will allow us to isolate the issue vs a possible styling issue from other places from your app.
