### ISSUE TITLE
 [0.62.0-rc.3][Android]ReactNative causing Pytorch crash

### ISSUE THREAD

**Issue by arunkumarpaleti** [facebook/react-native#28305]
We are using ReactNative for one of the module in our app.Recently we started using Pytorch for our research.After integration of Pytorch App started crashing with below error

Error:-
java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libpytorch_jni.so caused by: dlopen failed: cannot locate symbol "_ZN8facebook3jni11JByteBuffer5orderENS0_9alias_refINS0_10JByteOrderEEE" referenced by "/data/app/com.****-thbX8es5mHtefnS-RBdYcQ==/lib/arm64/libpytorch_jni.so"...

Steps to reproduce:
1.Download latest version of react native 0.62.0-rc.3
2.Integrate Pytorch in sample app
3.Try to run sample model using pytorch

Actual:App should work without any crash

Expected:App crashes with above mentioned error

**Comment by HugoGresse** [comment]
There is a more broad subject related to conflicted fbjni lib on pytorch & also on react-native :/ both does not cohabitate :/
