### ISSUE TITLE
error Unrecognized command "bundle".

### ISSUE THREAD

**Issue by 06065044** [facebook/react-native#28319]
> Task :xingeApp:bundleFlavor_releaseDebugJsAndAssets FAILED
error Unrecognized command "bundle".
info Run "react-native --help" to see a list of all available commands.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':xingeApp:bundleFlavor_releaseDebugJsAndAssets'.
> Process 'command 'cmd'' finished with non-zero exit value 1

React Native version:
System:
OS: macOS 10.14.6
CPU: (12) x64 Intel(R) Core(TM) i5-8850H CPU @ 2.60GHz
Memory: 274.45 MB / 8.00 GB
Shell: 5.7.1 - /bin/zsh
Binaries:
Node: 13.1.0 - /usr/local/bin/node
Yarn: 1.19.1 - /usr/local/bin/yarn
npm: 6.12.1 - /usr/local/bin/npm
Watchman: 4.9.0 - /usr/local/bin/watchman
SDKs:
iOS SDK:
Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
IDEs:
Android Studio: 3.5 AI-191.8026.42.35.5977832
Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
npmPackages:
    "react": "16.9.0",
    "react-native": "0.61.0"

**Comment by 06065044** [comment]
when i changed the rn version to 0.58.6,it works

**Comment by safaiyeh** [comment]
Glad you found a fix! @06065044 closing this issue, if it comes up again please make an issue following the issue template.
