### ISSUE TITLE
state is not being update from listfootercomponent

### ISSUE THREAD

**Issue by rahulnainwal107** [facebook/react-native#28318]
Description:

The state is not being updated from listfootercomponent.
I am trying to update the state from ListFooterComponet but not able to do that from listfootercomponent. My flatlist code is like that
````
<FlatList
            data={modifierData}
            keyExtractor={this.keyExtractor}
            renderItem={this.renderItem}
            ListHeaderComponent={<>
              <CountView>
                <Icon
                  iconName="ios-remove"
                  size={30}
                  iconColor={Color.black}
                  onPress={decrement}
                />
                <H2>{count}</H2>
                <Icon
                  iconName="ios-add"
                  size={30}
                  iconColor={Color.black}
                  onPress={increment}
                />
              </CountView>
            </>}
            ListFooterComponent={<>
              <H2>{strings.additionalInstruction} ({strings.optional})</H2>
              <MultiLineTextInput
                style={layout.multiLineTextInput}
                onChangeText={this.addAdditionalInstructions}
                value={additionalInstructions}
              />
            </>}
          />
````
onChangeText of MultiLineTextInput inside listFooterComponent is not triggering. When I am putting same code outside of flatlist it working fine.

React Native version:
System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
    Memory: 21.52 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.17.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 26, 28
      Build Tools: 23.0.1, 26.0.1, 26.0.2, 26.0.3, 28.0.3, 29.0.2
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5

## Expected Results

I wants to update state from list footer component.

## Snack, code example, screenshot, or link to a repository:
![fllist](https://user-images.githubusercontent.com/36499090/76827719-8153b400-6845-11ea-9bd1-752e07c94be8.png)

**Comment by rahulnainwal107** [comment]
React Native version:
System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
    Memory: 220.42 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.17.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 26, 28
      Build Tools: 23.0.1, 26.0.1, 26.0.2, 26.0.3, 28.0.3, 29.0.2
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5

**Comment by safaiyeh** [comment]
Hi @rahulnainwal107 thank you for providing your environment info. Can you edit your original comment using the issue template and provide a Snack that demonstrates the issue you are having?
