### ISSUE TITLE
Unable to open a project with Xcode (freeze)

### ISSUE THREAD

**Issue by barbhackk** [facebook/react-native#28316]
React Native version:
```
    System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 40.65 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
```

## Steps To Reproduce

1. Init a new project with `npx react-native init AwesomeProject`
2.Open project Xcode `ios/MoviesAndMe.xcworkspace`with command `xed -b ios` or directly with Xcode (double click)

## Expected Results

Xcode does not open. It is lag and I have to force the program to quit.
I tried to launch the application with the command `npx react-native run-ios`. The simulator is launched but not the node server. The terminal does not give me back my hand. It blocks. After that I can't open a project with xcode. My macbook pro is getting long. I have to restart. I removed and then reinstalled Xcode completely from my computer, but the problem persists. I think that it comes from `react-native-cli`. I started to experience the problem with the latest version.
I created a Swift project with Xcode directly and it works.

Sometimes the project opens on Xcode but it is very long.

## Snack, code example, screenshot, or link to a repository:

When I use the command `xed -b ios`, and I force the closing because it turns in a vacuum, I have this error: `2020-03-15 18:26:11.888 xed[1777:45447] Error: Error Domain=NSOSStatusErrorDomain Code=-1712 "errAETimeout: the AppleEvent timed out " UserInfo={ErrorNumber=-1712}`

**Comment by barbhackk** [comment]
I try with react-native 0.60.0 and same problem. Open project with Xcode it's so long. Run app launch simulator but not node server. This app not on simulator. On the screenshot, I've been stuck there for 30 min ... and still nothing on the simulator.
<img width="1440" alt="Capture d’écran 2020-03-15 à 19 23 48" src="https://user-images.githubusercontent.com/8588805/76707836-d9c66c80-66f2-11ea-916c-37e5d3f786f8.png">

The funny thing is that now that i have tried to launch the application, xcode is even longer. As if a process was running.

Thanks for your help.

**Comment by barbhackk** [comment]
Hi, I try to delete and re-install Xcode 11 and same problem.

**Comment by barbhackk** [comment]
I thinks it’s because i use ios 13 instead ios 9 ? No ?

Thanks for your help.

**Comment by barbhackk** [comment]
I think my problem is with Xcode and IOS version. I managed to open a project but I have a lot of errors that evoke IOS 9, IOS 10 ... I understand that this does not compile or that xcode has a hard time opening the project. Problem with cocoapods?
<img width="1440" alt="Capture d’écran 2020-03-16 à 14 41 15" src="https://user-images.githubusercontent.com/8588805/76764150-a63c1e80-6794-11ea-8344-c9f56afd4091.png">

**Comment by roxana-web** [comment]
hi , having same issue, i created  my react-native  init MapsProject --version0.57.8 as this version is stable for map, as i found in my online course, and now Xcode has problem opening the project and when i run " react-native run-ios " i get the error could not found Iphone x simulator
!

**Comment by roxana-web** [comment]
Try :  Xcode >preference >and install the appropriate IOS

**Comment by ryanhefner** [comment]
@barbhackk / @roxana-web Were either of you able to find a fix for this? I recently updated to the latest Xcode / Catalina patch and I am now experiencing this issue. Curious if you were able to find a fix, beyond blowing away your system and reverting back to an old backup.

**Comment by MangoBird** [comment]
Why is xcode source of all my problem? I have same issues. I want to go to sleep
