### ISSUE TITLE
Android - Could not resolve all artifacts for configuration ':classpath'

### ISSUE THREAD

**Issue by hrc7505** [facebook/react-native#28323]
Description:
I installed react native using the documentation given in the [website](https://reactnative.dev/docs/getting-started)  on my mac. IOS is working fine but android is giving an error. 

React Native version:
```

System:
    OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
    Memory: 1.03 GB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 13.10.1 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.7 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5

```
## Steps To Reproduce

    Provide a detailed list of steps that reproduce the issue.
    Issues without reproduction steps or code are likely to stall.

1. Open android folder in Android Studio
2. Building gives error

## Expected Results

   Project should run smoothly

## Snack, code example, screenshot, or link to a repository:
![image](https://user-images.githubusercontent.com/17545364/76756374-8fed8d00-67ab-11ea-8f72-126ce1a59a59.png)

**Comment by safaiyeh** [comment]
Hi @hrc7505 thank you for the issue! In order for us to debug this, could you provide a reproducible repo for investigation?

**Comment by hrc7505** [comment]
@safaiyeh I have just did what is in the documentation. I tried reinstalling the project. And issue is same. I didn't add any new library(dependencies) in the project. Although I am providing a [repository url ](https://github.com/hrc7505/AwesomeProject)

**Comment by chrisglein** [comment]
Errors indicate some sort of network error. Does this reproduce on a different machine? Are there some details about your setup that might be important/different?

This might be helpful: https://stackoverflow.com/questions/37409265/no-cached-version-available-for-offline-mode
