### ISSUE TITLE
Image's are not displaying on  Android version 4.3

### ISSUE THREAD

**Issue by AnOptimistSeePessimist** [facebook/react-native#28327]
Description:

    Images are not displayed in Android version 4.3

React Native version:

System:
  OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
    Memory: 384.18 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.18.0 - ~/.nvm/versions/node/v10.18.0/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v10.18.0/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v10.18.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 27, 28, 29
      Build Tools: 28.0.3
      System Images: android-18 | Google APIs Intel x86 Atom, android-22 | Google APIs Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5

## Steps To Reproduce

1. npx react-native init AwesomeProject --version 0.61.5
2. overwrite App.js whit the following code
```
import React from 'react';
import {View, Image, StyleSheet, Text} from 'react-native';

const styles = StyleSheet.create({
  wapper: {
    flex: 1,
    backgroundColor: '#fff',
  },
  imageWrapper: {
    borderWidth: 5,
    borderColor: 'red',
    marginVertical: 5,
    marginHorizontal: 10,
    padding: 10,
  },
  image: {
    height: 150,
    width: 180,
  },
});

export default function App() {
  return (
    <View style={styles.wapper}>
      <View style={styles.imageWrapper}>
        <Text>can't display</Text>
        <Image
          resizeMode="cover"
          style={styles.image}
          source={{uri: 'https://reactnative.dev/img/homepage/phones.png'}}
        />
      </View>
      <View style={styles.imageWrapper}>
        <Text>this is ok</Text>
        <Image
          resizeMode="cover"
          style={styles.image}
          source={require('./phones.png')}
        />
      </View>
    </View>
  );
}

```

## Expected Results

    can display image

**Comment by hramos** [comment]
Can you provide more information? The title implies this works on some version of Android, but not on Android 4.3 Jellybean. Did you happen to only test this on 4.3, or have you confirmed that it does work on newer versions of Android?

**Comment by AnOptimistSeePessimist** [comment]
I tested on Android 4.3 real device, Android 5.1 emulator, Android 9 emulator. On Android 4.3 devices only, using `source = {{uri: url}}` is not displayed, but using `source = {require ('./ phone.jpg')}` is displayed normally.

![WX20200318-102010](https://user-images.githubusercontent.com/27407218/76919294-72333b80-6903-11ea-9483-6789a817aaa0.png)
