### ISSUE TITLE
Animated.Value resets when component was re-mounted

### ISSUE THREAD

**Issue by GuaYang918** [facebook/react-native#28324]
If Animated.Value is used for a natively driven animation and then the component is unmounted, when the component is mounted back, the rendered value resets to the initial state.

**Comment by safaiyeh** [comment]
Hi @IvanStack thank you for the issue, before moving forward could you follow the issue template and provide environment info, RN version, and a snack.

**Comment by Frans-L** [comment]
Same issue: https://github.com/facebook/react-native/issues/28114
