### ISSUE TITLE
TypeScript and React Native

### ISSUE THREAD

**Issue by enkuush-ca** [facebook/react-native#28322]
I would like to move my app code onto src folder to follow this directory structure: https://github.com/react-navigation/react-navigation/tree/master/example/src

By the way, here is any official recommendation about react native directory structure? 🤔

So I created a blank TypeScript (blank (TypeScript)) with expo and then moved the code structure.

I know this issue was opened multiple time, but none of the solution I found fit my problem.

**Comment by safaiyeh** [comment]
Hello @enaqx this issue board is for bugs with React Native. This question is better suited for StackOverflow. Thank you!
