### ISSUE TITLE
Elevation does not animate

### ISSUE THREAD

**Issue by Digicrest** [facebook/react-native#28320]
Elevation shadow stays in place while screen interpolator animation plays; and disappears at the end of animation.

**React Native version:**
System:
    OS: macOS Mojave 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Memory: 4.73 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    npm: 6.4.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native: 0.59.5

## Steps To Reproduce
1. create a header component with some elevation
2. attach a screen interpolator animation
3. navigate to/away from the screen with that component

## Expected Results
You'll see the elevation shadow hangs momentarily

**Comment by safaiyeh** [comment]
Hello @Digicrest, thank you for the issue. In order for us to investigate further could you add a Snack that displays the issue.

**Comment by chrisglein** [comment]
Related to #23090?
