### ISSUE TITLE
doesn't work includeFontPadding to false with lineheight.

### ISSUE THREAD

**Issue by toy0605** [facebook/react-native#28331]
Description:

 Sorry for bad english... I'm creating an app with Korean lanugage, and using NotoSansCJK for text font. but NotoSansCJK font has some problem with includes font padding. I always create a style with 'includeFontPadding' to false. but it only works to first line if lineHeight has high value.

![image](https://user-images.githubusercontent.com/19731220/76856809-64e06780-6897-11ea-8db3-5ed035c67ba3.png)

React Native version:
```
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.18363
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 16.49 GB / 31.82 GB
  Binaries:
    Node: 12.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.12.1 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 21, 25, 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3
      System Images: android-21 | Google APIs Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64, android-25 | Google APIs ARM EABI v7a, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom_64
      Android NDK: 17.2.4988734
  IDEs:
    Android Studio: Version  3.5.0.0 AI-191.8026.42.35.6010548
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.9.0 => 16.9.0
    react-native: 0.62.0-rc.5 => 0.62.0-rc.5
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce

1. Use Text component with NotoSansCJK's font.
2. Style like below code.
```
        includeFontPadding: false,
        fontFamily: "NotoSansKR-Medium",
        lineHeight: 30 // higher value is easy to reproduce
```

## Expected Results

 I expect It doesn't have font padding.

## Snack, code example, screenshot, or link to a repository:

```
<Text selectable style={{
    padding: 0,
    margin: 0,
    includeFontPadding: false,
    fontFamily: "NotoSansKR-Medium",
    fontSize: 14,
    lineHeight: 31,
    letterSpacing: -0.42
}}>
    밥을 날카로우나 끓는 곧 지혜는 피가 구할 끓는다. 미묘한 못할 얼음 놀이 힘있다. 쓸쓸한 돋고, 목숨이 뛰노는 이상의 그들은 불러 만천하의 붙잡아 힘있다. 얼음에 이것을 할지니, 살았으며, 바이며, 하는 보배를 원질이 따뜻한 황금시대다. 긴지라 원대하고, 안고, 청춘의 끝에 청춘에서만 꽃이 끓는다. 거선의 희망의 영원히 그들에게 얼마나 사막이다. 우리의 품고 그들의 곳으로 것이다. 열매를 사는가 꽃이 아니더면, 약동하다. 인간은 희망의 이상, 그들은 있는 영락과 없는 인간이 아니다.{"\n\n"}
들어 역사를 따뜻한 인생을 것이다. 이성은 피에 위하여, 것이다. 가지에 미인을 것이다.보라, 있음으로써 듣는다. 봄바람을 싶이 넣는 끓는 없으면, 평화스러운 뿐이다. 끝에 거친 맺어, 얼마나 커다란 아니다. 크고 석가는 사랑의 봄날의 끝에 끓는다. 밝은 찾아다녀도, 않는 때문이다. 구하지 보배를 일월과 발휘하기 갑 날카로우나 물방아 있으랴? 웅대한 피가 청춘 인간이 심장은 약동하다. 때에, 것은 천자만홍이 같이, 찾아다녀도, 들어 무엇을 이상의 아니다.{"\n\n"}
우리 꽃이 끓는 자신과 별과 사랑의 그리하였는가? 찾아 인간이 있는 때까지 천지는 인생을 봄바람이다. 소리다.이것은 공자는 그들은 사랑의 청춘의 그리하였는가? 평화스러운 이상 크고 인생을 우리의 어디 사는가 많이 수 때문이다. 놀이 영락과 천고에 새가 장식하는 꽃이 아름다우냐? 이상은 때에, 꾸며 황금시대다. 품었기 역사를 피에 힘있다. 길을 황금시대의 위하여 이성은 인간의 뛰노는 위하여 보라. 동산에는 반짝이는 옷을 아니한 그들은 그들은 넣는 관현악이며, 구하기 듣는다.
</Text>
```

**Comment by toy0605** [comment]
I found same issue. #20644
but it doesn't fixed.

**Comment by fabriziobertoglio1987** [comment]
`For best results also set textAlignVertical to center` from [Text docs](https://reactnative.dev/docs/text)


https://github.com/facebook/react-native/blob/e3f4a7ba0975741231c2e1e0b16ed05887df0b94/ReactAndroid/src/main/java/com/facebook/react/views/text/TextLayoutManager.java#L264-L271


[`StatiLayout` public constructor](https://developer.android.com/reference/android/text/StaticLayout#public-constructors)

>StaticLayout(CharSequence source, TextPaint paint, int width, Layout.Alignment align, float spacingmult, float spacingadd, boolean includepad)

[`setIncludePad`](https://developer.android.com/reference/android/text/StaticLayout.Builder#setIncludePad(boolean))

>setIncludePad
>Added in API level 23
```java
public StaticLayout.Builder setIncludePad (boolean includePad)
```
>Set whether to include extra space beyond font ascent and descent (which is needed to avoid clipping in some languages, such as Arabic and Kannada). The default is true.

I quote [stackoverflow answer](https://stackoverflow.com/a/36590179/11452286)

![image](https://user-images.githubusercontent.com/24992535/83141674-61b3f400-a0f0-11ea-9b99-cd69582c986a.png)

[`setLineSpacing`](https://stackoverflow.com/a/25830131/11452286)

I m testing this on Android project

**Comment by fabriziobertoglio1987** [comment]
as you can see this issue is with android not react-native

<img src="https://user-images.githubusercontent.com/24992535/83143553-69749800-a0f2-11ea-973b-9ce59f1037fe.png" width="250" />

The sourcecode https://github.com/fabriziobertoglio1987/MyApplication.git

**Comment by toy0605** [comment]
> as you can see this issue is with android not react-native
> 
> <img alt="" width="250" src="https://user-images.githubusercontent.com/24992535/83143553-69749800-a0f2-11ea-973b-9ce59f1037fe.png">
> 
> The sourcecode https://github.com/fabriziobertoglio1987/MyApplication.git
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
>   xmlns:custom="http://schemas.android.com/apk/res/com.example.myapplication"
>   android:layout_width="match_parent"
>   android:layout_height="match_parent"
>   android:orientation="vertical" >
>   <TextView android:id="@+id/text"
>     android:includeFontPadding="false"
>     android:layout_width="wrap_content"
>     android:layout_height="wrap_content"
>     android:text="밥을 날카로우나 끓는 곧 지혜는 피가 구할 끓는다. 미묘한 못할 얼음 놀이 힘있다. 쓸쓸한 돋고, 목숨이 뛰노는 이상의 그들은 불러 만천하의 붙잡아 힘있다. 얼음에 이것을 할지니, 살았으며, 바이며, 하는 보배를 원질이 따뜻한 황금시대다. 긴지라 원대하고, 안고, 청춘의 끝에 청춘에서만 꽃이 끓는다. 거선의 희망의 영원히 그들에게 얼마나 사막이다. 우리의 품고 그들의 곳으로 것이다. 열매를 사는가 꽃이 아니더면, 약동하다. 인간은 희망의 이상, 그들은 있는 영락과 없는 인간이 아니다. 들어 역사를 따뜻한 인생을 것이다. 이성은 피에 위하여, 것이다. 가지에 미인을 것이다.보라, 있음으로써 듣는다. 봄바람을 싶이 넣는 끓는 없으면, 평화스러운 뿐이다. 끝에 거친 맺어, 얼마나 커다란 아니다. 크고 석가는 사랑의 봄날의 끝에 끓는다. 밝은 찾아다녀도, 않는 때문이다. 구하지 보배를 일월과 발휘하기 갑 날카로우나 물방아 있으랴? 웅대한 피가 청춘 인간이 심장은 약동하다. 때에, 것은 천자만홍이 같이, 찾아다녀도, 들어 무엇을 이상의 아니다. 우리 꽃이 끓는 자신과 별과 사랑의 그리하였는가? 찾아 인간이 있는 때까지 천지는 인생을 봄바람이다. 소리다.이것은 공자는 그들은 사랑의 청춘의 그리하였는가? 평화스러운 이상 크고 인생을 우리의 어디 사는가 많이 수 때문이다. 놀이 영락과 천고에 새가 장식하는 꽃이 아름다우냐? 이상은 때에, 꾸며 황금시대다. 품었기 역사를 피에 힘있다. 길을 황금시대의 위하여 이성은 인간의 뛰노는 위하여 보라. 동산에는 반짝이는 옷을 아니한 그들은 그들은 넣는 관현악이며, 구하기 듣는다" />
> </LinearLayout>
> ```

your text lines shown as screenshot all have same spacing. but mine is not.
react-native's text lines are not having same spacing height **especially first line** on my settings.
and you even don't add lineSpacingExtra to prove it is android issue.
if it is android issue, I could see your android native's having same problem. but not.

**Comment by fabriziobertoglio1987** [comment]
Please add example following this template 

<img src="https://user-images.githubusercontent.com/24992535/84417844-8478f900-ac16-11ea-8b7d-8f1db634f6ad.png" width="250" />

https://github.com/facebook/react-native/blob/03443d77f589d7aed8c9eb465607943076853b8e/RNTester/js/components/TextLegend.js#L96-L223

**Comment by toy0605** [comment]
It cause something different reason. close issue and create another issue. #29232
