### ISSUE TITLE
react-native init error

### ISSUE THREAD

**Issue by YComputer** [facebook/react-native#2833]
YComputerdeMacBook-Pro:test ycomputer$ react-native  init Test
    This will walk you through creating a new React Native project in /Users/ycomputer/ReactNative/test/Test
     
    > spawn-sync@1.0.13 postinstall /Users/ycomputer/ReactNative/test/Test/node_modules/react-native/node_modules/yeoman-generator/node_modules/cross-spawn/node_modules/spawn-sync
    > node postinstall

     
    > bufferutil@1.2.1 install /Users/ycomputer/ReactNative/test/Test/node_modules/react-native/node_modules/ws/node_modules/bufferutil
    > node-gyp rebuild

      CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
      SOLINK_MODULE(target) Release/bufferutil.node
    ld: library not found for -lgcc_s.10.5
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    make: *** [Release/bufferutil.node] Error 1
    gyp ERR! build error 
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/Users/ycomputer/.nvm/versions/node/v4.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
    gyp ERR! stack     at emitTwo (events.js:87:13)
    gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
    gyp ERR! System Darwin 14.5.0
    gyp ERR! command "/Users/ycomputer/.nvm/versions/node/v4.0.0/bin/node" "/Users/ycomputer/.nvm/versions/node/v4.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /Users/ycomputer/ReactNative/test/Test/node_modules/react-native/node_modules/ws/node_modules/bufferutil
    gyp ERR! node -v v4.0.0
    gyp ERR! node-gyp -v v3.0.1
    gyp ERR! not ok 
     
    > utf-8-validate@1.2.1 install /Users/ycomputer/ReactNative/test/Test/node_modules/react-native/node_modules/ws/node_modules/utf-8-validate
    > node-gyp rebuild

      CXX(target) Release/obj.target/validation/src/validation.o
      SOLINK_MODULE(target) Release/validation.node
    ld: library not found for -lgcc_s.10.5
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    make: *** [Release/validation.node] Error 1
    gyp ERR! build error 
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/Users/ycomputer/.nvm/versions/node/v4.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
    gyp ERR! stack     at emitTwo (events.js:87:13)
    gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
    gyp ERR! System Darwin 14.5.0
    gyp ERR! command "/Users/ycomputer/.nvm/versions/node/v4.0.0/bin/node" "/Users/ycomputer/.nvm/versions/node/v4.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /Users/ycomputer/ReactNative/test/Test/node_modules/react-native/node_modules/ws/node_modules/utf-8-validate
    gyp ERR! node -v v4.0.0
    ERR! node-gyp -v v3.0.1
    gyp ERR! not ok 
    npm WARN optional dep failed, continuing bufferutil@1.2.1
     
    > fsevents@0.3.8 install /Users/ycomputer/ReactNative/test/Test/node_modules/react-native/node_modules/babel/node_modules/chokidar/node_modules/fsevents
    > node-gyp rebuild

      SOLINK_MODULE(target) Release/.node
    ld: library not found for -lgcc_s.10.5
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    make: *** [Release/.node] Error 1
    gyp ERR! build error 
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/Users/ycomputer/.nvm/versions/node/v4.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
    gyp ERR! stack     at emitTwo (events.js:87:13)
    gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
    gyp ERR! System Darwin 14.5.0
    gyp ERR! command "/Users/ycomputer/.nvm/versions/node/v4.0.0/bin/node" "/Users/ycomputer/.nvm/versions/node/v4.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /Users/ycomputer/ReactNative/test/Test/node_modules/react-native/node_modules/babel/node_modules/chokidar/node_modules/fsevents
    gyp ERR! node -v v4.0.0
    gyp ERR! node-gyp -v v3.0.1
    gyp ERR! not ok 
    npm WARN optional dep failed, continuing utf-8-validate@1.2.1
    npm WARN optional dep failed, continuing fsevents@0.3.8
    react-native@0.11.0 node_modules/react-native
    ├── absolute-path@0.0.0
    ├── progress@1.1.8
    ├── graceful-fs@4.1.2
    ├── stacktrace-parser@0.1.3
    ├── react-timer-mixin@0.13.3
    ├── wordwrap@1.0.0
    ├── underscore@1.7.0
    ├── image-size@0.3.5
    ├── semver@4.3.6
    ├── debug@2.1.0 (ms@0.6.2)
    ├── yargs@1.3.2
    ├── immutable@3.7.5
    ├── optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)
    ├── chalk@1.0.0 (escape-string-regexp@1.0.3, ansi-styles@2.1.0, supports-color@1.3.1, strip-ansi@2.0.1, has-ansi@1.0.3)
    ├── bser@1.0.0 (node-int64@0.4.0)
    ├── source-map@0.1.31 (amdefine@1.0.0)
    ├── worker-farm@1.3.1 (xtend@4.0.0, errno@0.1.4)
    ├── promise@7.0.4 (asap@2.0.3)
    ├── sane@1.2.0 (watch@0.10.0, minimist@1.2.0, exec-sh@0.2.0, fb-watchman@1.6.0, minimatch@0.2.14, walker@1.0.7)
    ├── rebound@0.0.12
    ├── connect@2.8.3 (methods@0.0.1, uid2@0.0.2, fresh@0.1.0, cookie-signature@1.0.1, pause@0.0.1, qs@0.6.5, bytes@0.2.0, buffer-crc32@0.2.1, cookie@0.1.0, send@0.1.2, formidable@1.0.14)
    ├── uglify-js@2.4.16 (uglify-to-browserify@1.0.2, async@0.2.10, optimist@0.3.7, source-map@0.1.34)
    ├── ws@0.8.0 (options@0.0.6, ultron@1.0.2)
    ├── regenerator@0.8.36 (private@0.1.6, through@2.3.8, recast@0.10.25, commoner@0.10.3, esprima-fb@15001.1.0-dev-harmony-fb, defs@1.1.0)
    ├── jstransform@11.0.1 (object-assign@2.1.1, base62@1.1.0, source-map@0.4.4, esprima-fb@15001.1.0-dev-harmony-fb, commoner@0.10.3)
    ├── module-deps@3.5.6 (inherits@2.0.1, shallow-copy@0.0.1, duplexer2@0.0.2, minimist@0.2.0, parents@1.0.1, subarg@0.0.1, concat-stream@1.4.10, readable-stream@1.1.13, through2@0.4.2, resolve@0.7.4, stream-combiner2@1.0.2, browser-resolve@1.9.1, JSONStream@0.7.4, detective@3.1.0)
    ├── babel@5.8.21 (slash@1.0.0, path-is-absolute@1.0.0, path-exists@1.0.0, fs-readdir-recursive@0.1.2, convert-source-map@1.1.1, commander@2.8.1, source-map@0.4.4, output-file-sync@1.1.1, glob@5.0.14, chokidar@1.0.5, lodash@3.10.1)
    ├── joi@5.1.0 (topo@1.0.3, isemail@1.2.0, hoek@2.16.2, moment@2.10.6)
    ├── yeoman-environment@1.2.7 (escape-string-regexp@1.0.3, log-symbols@1.0.2, diff@1.4.0, text-table@0.2.0, untildify@2.1.0, mem-fs@1.1.0, globby@2.1.0, grouped-queue@0.3.0, lodash@3.10.1, inquirer@0.8.5)
    ├── yeoman-generator@0.20.3 (read-chunk@1.0.1, detect-conflict@1.0.0, yeoman-welcome@1.0.1, path-is-absolute@1.0.0, path-exists@1.0.0, yeoman-assert@2.1.0, rimraf@2.4.3, async@1.4.2, text-table@0.2.0, user-home@2.0.0, xdg-basedir@2.0.0, mime@1.3.4, dargs@4.0.1, istextorbinary@1.0.2, nopt@3.0.4, mkdirp@0.5.1, run-async@0.1.0, shelljs@0.5.3, cli-table@0.3.1, through2@2.0.0, diff@2.1.1, pretty-bytes@2.0.1, underscore.string@3.2.2, dateformat@1.0.11, glob@5.0.14, findup-sync@0.2.1, cross-spawn@2.0.0, github-username@2.0.0, mem-fs-editor@2.0.4, class-extend@0.1.1, download@4.2.0, gruntfile-editor@1.0.0, html-wiring@1.2.0, sinon@1.16.1, lodash@3.10.1, inquirer@0.8.5)
    ├── react-tools@0.14.0-beta1 (commoner@0.10.3)
    └── babel-core@5.8.21 (slash@1.0.0, try-resolve@1.0.1, babel-plugin-remove-console@1.0.1, babel-plugin-remove-debugger@1.0.1, babel-plugin-eval@1.0.1, babel-plugin-jscript@1.0.4, babel-plugin-inline-environment-variables@1.0.1, babel-plugin-property-literals@1.0.1, babel-plugin-member-expression-literals@1.0.1, babel-plugin-undefined-to-void@1.1.6, babel-plugin-react-constant-elements@1.0.3, shebang-regex@1.0.0, trim-right@1.0.1, to-fast-properties@1.0.1, path-exists@1.0.0, babel-plugin-react-display-name@1.0.3, path-is-absolute@1.0.0, babel-plugin-constant-folding@1.0.1, fs-readdir-recursive@0.1.2, babel-plugin-proto-to-assign@1.0.4, babel-plugin-dead-code-elimination@1.0.2, babel-plugin-runtime@1.0.7, private@0.1.6, globals@6.4.1, esutils@2.0.2, convert-source-map@1.1.1, js-tokens@1.0.1, babylon@5.8.23, resolve@1.1.6, bluebird@2.10.0, json5@0.4.0, detect-indent@3.0.1, debug@2.2.0, babel-plugin-undeclared-variables-check@1.0.2, output-file-sync@1.1.1, source-map@0.4.4, source-map-support@0.2.10, is-integer@1.0.6, repeating@1.1.3, home-or-tmp@1.0.0, line-numbers@0.2.0, minimatch@2.0.10, lodash@3.10.1, regexpu@1.2.0, regenerator@0.8.35, core-js@1.1.4)
    Setting up new React Native app in /Users/ycomputer/ReactNative/test/Test
       create .flowconfig
       create .gitignore
       create .watchmanconfig
       create index.ios.js
       create index.android.js
       create ios/main.jsbundle
       create ios/Test/AppDelegate.h
       create ios/Test/AppDelegate.m
       create ios/Test/Base.lproj/LaunchScreen.xib
       create ios/Test/Images.xcassets/AppIcon.appiconset/Contents.json
       create ios/Test/Info.plist
       create ios/Test/main.m
       create ios/TestTests/TestTests.m
       create ios/TestTests/Info.plist
       create ios/Test.xcodeproj/project.pbxproj
       create ios/Test.xcodeproj/xcshareddata/xcschemes/Test.xcscheme
       create android/app/build.gradle
       create android/app/proguard-rules.pro
       create android/app/src/main/AndroidManifest.xml
       create android/app/src/main/res/values/strings.xml
       create android/app/src/main/res/values/styles.xml
       create android/build.gradle
       create android/gradle.properties
       create android/settings.gradle
       create android/app/src/main/res/mipmap-hdpi/ic_launcher.png
       create android/app/src/main/res/mipmap-mdpi/ic_launcher.png
       create android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
       create android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
       create android/gradle/wrapper/gradle-wrapper.jar
       create android/gradle/wrapper/gradle-wrapper.properties
       create android/gradlew
       create android/gradlew.bat
       create android/app/src/main/java/com/test/MainActivity.java
    To run your app on iOS:
       Open /Users/ycomputer/ReactNative/test/Test/ios/Test.xcodeproj in Xcode
       Hit Run button
    To run your app on Android:
       Have an Android emulator running, or a device connected
       cd /Users/ycomputer/ReactNative/test/Test
       react-native run-android

**Comment by jaygarcia** [comment]
i *always* get errors with gyp. :(  I've just gotten used to ignoring them.

```
This will walk you through creating a new React Native project in /www/ios/KeyGenMusicPlayer/Test

> spawn-sync@1.0.13 postinstall /www/ios/KeyGenMusicPlayer/Test/node_modules/react-native/node_modules/yeoman-generator/node_modules/cross-spawn/node_modules/spawn-sync
> node postinstall


> utf-8-validate@1.2.1 install /www/ios/KeyGenMusicPlayer/Test/node_modules/react-native/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 404 status code downloading tarball
gyp ERR! stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:246:14)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:169:7)
gyp ERR! stack     at Request.onRequestResponse (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1176:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:415:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:305:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/Cellar/iojs/2.3.3/bin/iojs" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /www/ios/KeyGenMusicPlayer/Test/node_modules/react-native/node_modules/ws/node_modules/utf-8-validate
gyp ERR! node -v v2.3.3
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 

> bufferutil@1.2.1 install /www/ios/KeyGenMusicPlayer/Test/node_modules/react-native/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 404 status code downloading tarball
gyp ERR! stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:246:14)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:169:7)
gyp ERR! stack     at Request.onRequestResponse (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1176:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:415:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:305:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/Cellar/iojs/2.3.3/bin/iojs" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /www/ios/KeyGenMusicPlayer/Test/node_modules/react-native/node_modules/ws/node_modules/bufferutil
gyp ERR! node -v v2.3.3
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm WARN optional dep failed, continuing utf-8-validate@1.2.1
npm WARN optional dep failed, continuing bufferutil@1.2.1

> fsevents@0.3.8 install /www/ios/KeyGenMusicPlayer/Test/node_modules/react-native/node_modules/babel/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 404 status code downloading tarball
gyp ERR! stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:246:14)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:169:7)
gyp ERR! stack     at Request.onRequestResponse (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1176:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:415:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:305:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/Cellar/iojs/2.3.3/bin/iojs" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /www/ios/KeyGenMusicPlayer/Test/node_modules/react-native/node_modules/babel/node_modules/chokidar/node_modules/fsevents
gyp ERR! node -v v2.3.3
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm WARN optional dep failed, continuing fsevents@0.3.8
react-native@0.11.0 node_modules/react-native
├── absolute-path@0.0.0
├── progress@1.1.8
├── graceful-fs@4.1.2
├── stacktrace-parser@0.1.3
├── react-timer-mixin@0.13.3
├── wordwrap@1.0.0
├── underscore@1.7.0
├── image-size@0.3.5
├── debug@2.1.0 (ms@0.6.2)
├── bser@1.0.0 (node-int64@0.4.0)
├── chalk@1.0.0 (escape-string-regexp@1.0.3, ansi-styles@2.1.0, supports-color@1.3.1, strip-ansi@2.0.1, has-ansi@1.0.3)
├── semver@4.3.6
├── optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)
├── yargs@1.3.2
├── promise@7.0.4 (asap@2.0.3)
├── worker-farm@1.3.1 (xtend@4.0.0, errno@0.1.4)
├── source-map@0.1.31 (amdefine@1.0.0)
├── immutable@3.7.5
├── sane@1.2.0 (watch@0.10.0, minimist@1.2.0, exec-sh@0.2.0, fb-watchman@1.6.0, walker@1.0.7, minimatch@0.2.14)
├── ws@0.8.0 (options@0.0.6, ultron@1.0.2)
├── rebound@0.0.12
├── connect@2.8.3 (methods@0.0.1, uid2@0.0.2, fresh@0.1.0, cookie-signature@1.0.1, pause@0.0.1, qs@0.6.5, bytes@0.2.0, buffer-crc32@0.2.1, cookie@0.1.0, send@0.1.2, formidable@1.0.14)
├── uglify-js@2.4.16 (uglify-to-browserify@1.0.2, async@0.2.10, optimist@0.3.7, source-map@0.1.34)
├── regenerator@0.8.36 (private@0.1.6, through@2.3.8, recast@0.10.25, commoner@0.10.3, esprima-fb@15001.1.0-dev-harmony-fb, defs@1.1.0)
├── jstransform@11.0.1 (object-assign@2.1.1, base62@1.1.0, source-map@0.4.4, esprima-fb@15001.1.0-dev-harmony-fb, commoner@0.10.3)
├── module-deps@3.5.6 (inherits@2.0.1, shallow-copy@0.0.1, duplexer2@0.0.2, minimist@0.2.0, concat-stream@1.4.10, parents@1.0.1, subarg@0.0.1, readable-stream@1.1.13, through2@0.4.2, stream-combiner2@1.0.2, resolve@0.7.4, browser-resolve@1.9.1, JSONStream@0.7.4, detective@3.1.0)
├── babel@5.8.21 (slash@1.0.0, path-is-absolute@1.0.0, path-exists@1.0.0, fs-readdir-recursive@0.1.2, convert-source-map@1.1.1, commander@2.8.1, source-map@0.4.4, output-file-sync@1.1.1, glob@5.0.14, chokidar@1.0.6, lodash@3.10.1)
├── joi@5.1.0 (topo@1.0.3, isemail@1.2.0, hoek@2.16.2, moment@2.10.6)
├── react-tools@0.14.0-beta1 (commoner@0.10.3)
├── yeoman-environment@1.2.7 (log-symbols@1.0.2, escape-string-regexp@1.0.3, diff@1.4.0, text-table@0.2.0, untildify@2.1.0, mem-fs@1.1.0, globby@2.1.0, grouped-queue@0.3.0, lodash@3.10.1, inquirer@0.8.5)
├── yeoman-generator@0.20.3 (read-chunk@1.0.1, detect-conflict@1.0.0, yeoman-welcome@1.0.1, path-is-absolute@1.0.0, path-exists@1.0.0, yeoman-assert@2.1.0, rimraf@2.4.3, async@1.4.2, xdg-basedir@2.0.0, user-home@2.0.0, text-table@0.2.0, mime@1.3.4, dargs@4.0.1, istextorbinary@1.0.2, nopt@3.0.4, run-async@0.1.0, mkdirp@0.5.1, shelljs@0.5.3, cli-table@0.3.1, pretty-bytes@2.0.1, dateformat@1.0.11, through2@2.0.0, glob@5.0.14, diff@2.1.1, findup-sync@0.2.1, underscore.string@3.2.2, github-username@2.0.0, mem-fs-editor@2.0.4, cross-spawn@2.0.0, class-extend@0.1.1, download@4.2.0, html-wiring@1.2.0, sinon@1.16.1, gruntfile-editor@1.0.0, lodash@3.10.1, inquirer@0.8.5)
└── babel-core@5.8.21 (slash@1.0.0, try-resolve@1.0.1, babel-plugin-remove-debugger@1.0.1, babel-plugin-remove-console@1.0.1, babel-plugin-jscript@1.0.4, babel-plugin-property-literals@1.0.1, babel-plugin-inline-environment-variables@1.0.1, babel-plugin-react-constant-elements@1.0.3, babel-plugin-eval@1.0.1, babel-plugin-member-expression-literals@1.0.1, babel-plugin-undefined-to-void@1.1.6, to-fast-properties@1.0.1, shebang-regex@1.0.0, path-is-absolute@1.0.0, path-exists@1.0.0, trim-right@1.0.1, babel-plugin-react-display-name@1.0.3, fs-readdir-recursive@0.1.2, babel-plugin-constant-folding@1.0.1, babel-plugin-proto-to-assign@1.0.4, babel-plugin-dead-code-elimination@1.0.2, babel-plugin-runtime@1.0.7, private@0.1.6, globals@6.4.1, esutils@2.0.2, convert-source-map@1.1.1, home-or-tmp@1.0.0, babel-plugin-undeclared-variables-check@1.0.2, line-numbers@0.2.0, js-tokens@1.0.1, debug@2.2.0, is-integer@1.0.6, repeating@1.1.3, detect-indent@3.0.1, source-map@0.4.4, output-file-sync@1.1.1, babylon@5.8.23, minimatch@2.0.10, resolve@1.1.6, bluebird@2.10.0, source-map-support@0.2.10, json5@0.4.0, regexpu@1.2.0, regenerator@0.8.35, lodash@3.10.1, core-js@1.1.4)
Setting up new React Native app in /www/ios/KeyGenMusicPlayer/Test
   create .flowconfig
   create .gitignore
   create .watchmanconfig
   create index.ios.js
   create index.android.js
   create ios/main.jsbundle
   create ios/Test/AppDelegate.h
   create ios/Test/AppDelegate.m
   create ios/Test/Base.lproj/LaunchScreen.xib
   create ios/Test/Images.xcassets/AppIcon.appiconset/Contents.json
   create ios/Test/Info.plist
   create ios/Test/main.m
   create ios/TestTests/TestTests.m
   create ios/TestTests/Info.plist
   create ios/Test.xcodeproj/project.pbxproj
   create ios/Test.xcodeproj/xcshareddata/xcschemes/Test.xcscheme
   create android/app/build.gradle
   create android/app/proguard-rules.pro
   create android/app/src/main/AndroidManifest.xml
   create android/app/src/main/res/values/strings.xml
   create android/app/src/main/res/values/styles.xml
   create android/build.gradle
   create android/gradle.properties
   create android/settings.gradle
   create android/app/src/main/res/mipmap-hdpi/ic_launcher.png
   create android/app/src/main/res/mipmap-mdpi/ic_launcher.png
   create android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
   create android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
   create android/gradle/wrapper/gradle-wrapper.jar
   create android/gradle/wrapper/gradle-wrapper.properties
   create android/gradlew
   create android/gradlew.bat
   create android/app/src/main/java/com/test/MainActivity.java
To run your app on iOS:
   Open /www/ios/KeyGenMusicPlayer/Test/ios/Test.xcodeproj in Xcode
   Hit Run button
To run your app on Android:
   Have an Android emulator running, or a device connected
   cd /www/ios/KeyGenMusicPlayer/Test
   react-native run-android


```

**Comment by mkonicek** [comment]
Looks like a problem with your setup. @ide does everything work with Node v4? I'm still on io.js.

**Comment by jaygarcia** [comment]
@mkonicek , tbh, yes. I'm on io.js too!

**Comment by ide** [comment]
@mkonicek yes, Node v4 is supported as of 0.11. I've been using it for awhile and now am recommending it along with nvm.

@jaygarcia It looks like your io.js is installed with Homebrew, which might have issues with gyp. Could I ask you to install Node 4.x with nvm (you can get it via `brew install nvm` or a direct download: https://github.com/creationix/nvm#installation if you don't have it already)? `nvm install node && nvm alias default node` will make Node 4.1 the default on your system. I haven't had sudo or gyp issues with nvm and haven't looked back.

**Comment by yinzSE** [comment]
maybe u should not use "test" as ur project name or dir name;

**Comment by vikeri** [comment]
This worked for me: `rm -R node_modules`, `rm -R ~/.node-gyp`, `rm -R ~/.npmrc` and then a restart and ultimately `npm install` again.
Solution from: https://github.com/nodejs/node-gyp/issues/809
