### ISSUE TITLE
Wrapping SafeAreaView around ScrollView doesn't work properly on iPhone XR / XS max

### ISSUE THREAD

**Issue by simonepizzamiglio** [facebook/react-native#28347]
Description:

Hi guys,
I'm trying to get a scrollable SafeAreaView, so I tried to wrap a SafeAreaView around a ScrollView, after some tweaks I got it working except on iPhone XR/XS max, the bottom safe area just doesn't work.

This is my code
```js
<ScrollView
	contentInsetAdjustmentBehavior="automatic"
	scrollEnabled={withScrollView}
	style={{ backgroundColor: 'aquamarine' }}
	contentContainerStyle={{ flexGrow: 1 }}
>
	<SafeAreaView
		style={{
			flex: 1,
			backgroundColor: 'coral',
			justifyContent: 'space-between',
		}}
	>
		<Text>Top SafeAreaView</Text>
		<Text>Bottom SafeAreaView</Text>
	</SafeAreaView>
</ScrollView>
```

As you can see in image below, only the first text is visible because the second one is out of the screen.

![Screenshot 2020-03-19 at 21 12 29](https://user-images.githubusercontent.com/12150102/77111443-a6078180-6a27-11ea-9db8-7463747835bb.png)

In the following screenshot I scrolled down a little bit and as you can see the SafeAreaView covers the entire screen as expected but it doesn't apply the safe area padding.
Nothing changes if I try to replace the SafeAreaView with a normal View or a Fragment, I just get the same behaviour so it looks like the SafeAreaView doesn't work at all.

![Screenshot 2020-03-19 at 21 13 54](https://user-images.githubusercontent.com/12150102/77112803-f089fd80-6a29-11ea-8f12-888ac6d36170.png)

Is this a bug or there is a workaround for this? Any suggestion?

React Native version:

System:
    OS: macOS 10.15.1
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 21.67 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.14.2 - ~/.nvm/versions/node/v10.14.2/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.14.1 - ~/.nvm/versions/node/v10.14.2/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 28, 29
      Build Tools: 28.0.3, 29.0.1
      System Images: android-23 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.4 => 0.61.4

**Comment by therealadum** [comment]
Hey @simonepizzamiglio. If you're trying to get a safe area scrollview, try wrapping the SafeAreaView around the ScrollView:

`<SafeAreaView
      style={{
        flexGrow: 1,
        backgroundColor: 'coral',
      }}>
      <ScrollView
        style={{
          backgroundColor: 'aquamarine',
        }}
        contentContainerStyle={{
          flexGrow: 1,
          justifyContent: 'space-between',
        }}>
        <Text>Top SafeAreaView</Text>
        <Text>Bottom SafeAreaView</Text>
      </ScrollView>
    </SafeAreaView>`

**Comment by simonepizzamiglio** [comment]
> Hey @simonepizzamiglio. If you're trying to get a safe area scrollview, try wrapping the SafeAreaView around the ScrollView:
> 
> ```
> <SafeAreaView
>       style={{
>         flexGrow: 1,
>         backgroundColor: 'coral',
>       }}>
>       <ScrollView
>         style={{
>           backgroundColor: 'aquamarine',
>         }}
>         contentContainerStyle={{
>           flexGrow: 1,
>           justifyContent: 'space-between',
>         }}>
>         <Text>Top SafeAreaView</Text>
>         <Text>Bottom SafeAreaView</Text>
>       </ScrollView>
>     </SafeAreaView>
> ```

That's not the behaviour I want to achieve, I want the top and bottom black bars to overlap the content of my page while scrolling

**Comment by simonepizzamiglio** [comment]
I resolved this issue with [react-native-safe-area-contenxt](https://github.com/th3rdwave/react-native-safe-area-context) library
