### ISSUE TITLE
安卓 release环境打包成功，在手机上安装完成以后，无打开按钮以及在界面上无图标，请问这是什么问题

### ISSUE THREAD

**Issue by SillyMrTang** [facebook/react-native#28344]
安卓 release环境打包成功，在手机上安装完成以后，无打开按钮以及在界面上无图标，请问这是什么问题

**Comment by hramos** [comment]
It doesn't seem like this issue has enough information for us to act on. Please open a new issue and make sure to fill out the issue template in its entirety. Thank You!
