### ISSUE TITLE
Improve TVEventHandler events

### ISSUE THREAD

**Issue by pedro-pedrosa** [facebook/react-native#28348]
Description:

The `TVEventHandler` class does not emit events for common Android TV remote buttons. For instance my remote controller has separate buttons for play (`KEYCODE_MEDIA_PLAY`) and pause (`KEYCODE_MEDIA_PLAY`) but only `KEYCODE_MEDIA_PLAY_PAUSE` is mapped in https://github.com/facebook/react-native/blob/aee88b6843cea63d6aa0b5879ad6ef9da4701846/ReactAndroid/src/main/java/com/facebook/react/ReactAndroidHWInputDeviceHelper.java#L29

Could be worth considering expanding the current set of mapped events to include the following?
`KEYCODE_MEDIA_NEXT`
`KEYCODE_MEDIA_PAUSE`
`KEYCODE_MEDIA_PLAY`
`KEYCODE_MEDIA_PREVIOUS`
`KEYCODE_MEDIA_SKIP_BACKWARD`
`KEYCODE_MEDIA_SKIP_FORWARD`
`KEYCODE_MEDIA_STEP_BACKWARD`
`KEYCODE_MEDIA_STEP_FORWARD`
`KEYCODE_MEDIA_STOP`

React Native version:
`0.61.5`

## Steps To Reproduce
Use an Android TV remote with separate buttons for play and pause

## Expected Results
Proper events should be caught by the `TVEventHandler`

## Snack, code example, screenshot, or link to a repository:
N/A

**Comment by cruzach** [comment]
Hi! thanks for reporting this, but Android TV isn't explicitly supported, so an issue probably isn't the best place to keep track of this. I think this is more of a feature request, or maybe should apply to the [`react-native-tvos` community repo](https://github.com/react-native-community/react-native-tvos)

As an aside- [`TVEventHandler`](https://github.com/facebook/react-native/blob/0b9ea60b4fee8cacc36e7160e31b91fc114dbc0d/Libraries/Components/AppleTV/TVEventHandler.js) seems to be only for AppleTV
