### ISSUE TITLE
event cannot be both direct and bubbling react native index.android.js

### ISSUE THREAD

**Issue by ohadpartuck** [facebook/react-native#2834]
installed the newest react-native-cli
ran the emulator, the js server is live (tried with both `node 4.0 `and `io.js3`)
getting this
<img width="431" alt="screen shot 2015-09-18 at 1 58 49 pm" src="https://cloud.githubusercontent.com/assets/2236337/9958292/14e9412e-5e11-11e5-9750-c25db892b4ff.png">

**Comment by foghina** [comment]
Can you try reinstalling your node modules? I.e. in your app do:

    $ rm -rf node_modules
    $ npm cache clean
    $ npm install

Make sure you are using node 4.0.0 when you are doing this, as switching node versions breaks installed node_modules. Then you can try `react-native run-android` again.

**Comment by ohadpartuck** [comment]
@foghina thanks it seems to works (now I need to find out how to shake the android emulator :-) )
Can you explain what was the issue that you fixed?

**Comment by ide** [comment]
When you switch versions of Node, your old binary Node modules are not compatible with newer versions so you need to recompile them.

**Comment by ohadpartuck** [comment]
ok! thanks. @ide and @foghina
