### ISSUE TITLE
`requireNativeComponent` warns expected number of arguments

### ISSUE THREAD

**Issue by cHaLkdusT** [facebook/react-native#28351]
Description:

Wrapping native UI Compnent using `requireNativeComponent` shows a warning in ESLint checker. 

React Native version:

```
System:
    OS: macOS 10.15.3
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.13.0 - /usr/local/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.12.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5977832
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5
```

## Steps To Reproduce

1. Follow integration guide: https://reactnative.dev/docs/native-components-ios
2. In section **[Properties](https://reactnative.dev/docs/native-components-ios#properties)**, `requireNativeComponent` has now two arguments

## Expected Results

No ESLint warning

## Snack, code example, screenshot, or link to a repository:

<img width="559" alt="image" src="https://user-images.githubusercontent.com/2569355/77137473-14d8ef00-6aa9-11ea-833d-9392240e6643.png">

Related issue: [Issue 1741](https://github.com/facebook/react-native-website/issues/1741) in react-native-website

**Comment by TheSavior** [comment]
Ah, this is a bug with the docs. `requireNativeComponent` only expects one argument. Can you send a PR to update the docs?

**Comment by cHaLkdusT** [comment]
Hi @TheSavior, I've checked other libraries that exposes native UI components and they also seem to pass the second argument if they expose native properties. I think it is the TypeScript signature that needs updating?

**Comment by TheSavior** [comment]
It used to take two arguments, but now it only takes one: 

https://github.com/facebook/react-native/blob/22eb711c84587ac92da97e486fecaa79424fa925/Libraries/ReactNative/requireNativeComponent.js#L27

This change was made two years ago in https://github.com/facebook/react-native/commit/8dc3ba0444c94d9bbb66295b5af885bff9b9cd34 which first shipped with 0.56

**Comment by cHaLkdusT** [comment]
Gotcha! I'm happy to create a PR to update the docs.

By the way, I have a question regarding this part:
> Sometimes your native component will have some reserved properties that you don't want to be part of the API for the associated React component. For example, Switch has a custom onChange handler for the raw native event, and exposes an onValueChange handler property that is invoked with the boolean value rather than the raw event. Since you don't want these native only properties to be part of the API, you don't want to put them in propTypes, but if you don't you'll get an error. The solution is to add them to the nativeOnly option, e.g.
```
var RCTSwitch = requireNativeComponent('RCTSwitch', Switch, {
  nativeOnly: {onChange: true},
});
```

Does it mean, it's not applicable anymore? Thanks!

**Comment by ferdicus** [comment]
@cHaLkdusT, did you find any resolution to your last comment?
