### ISSUE TITLE
Unable to resolve module http

### ISSUE THREAD

**Issue by imanolpg** [facebook/react-native#28360]
## Description:
When I try to run my react-native app on ios or android Metro Bundler raises an error saying that I dont have http module installed.

I have tryed this but does not work:
`watchman watch-del-all`
`rm -rf node_modules`
`run yarn install`
`yarn start --reset-cache`
`rm -rf /tmp/metro-*`

I have also reinstalled react-native again, downgraded the version, reinstalled express module and create another new project but the error still exists.

### React Native version:

    Node: 13.11.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.7 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
    react: 16.13.1 => 16.13.1 
    react-native: 0.61.5 => 0.61.5

## Steps To Reproduce

1. Try to upload a new app into any simulator.

## Expected Results

I was expecting the app to work normally as it did one month ago.

## Snack, code example, screenshot, or link to a repository:

error: bundling failed: Error: Unable to resolve module `http` from `node_modules/express/lib/application.js`: http could not be found within the project.

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules: rm -rf node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
    at ModuleResolver.resolveDependency (node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:186:15)
    at ResolutionRequest.resolveDependency (node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (node_modules/metro/src/node-haste/DependencyGraph.js:282:16)
    at Object.resolve (node_modules/metro/src/lib/transformHelpers.js:267:42)
    at node_modules/metro/src/DeltaBundler/traverseDependencies.js:426:31
    at Array.map (<anonymous>)
    at resolveDependencies (node_modules/metro/src/DeltaBundler/traverseDependencies.js:423:18)
    at node_modules/metro/src/DeltaBundler/traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)
```

**Comment by vkurchatkin** [comment]
You are trying to run node.js app with React Native runtime. This is probably a mistake, but either way this won't work

**Comment by imanolpg** [comment]
I was able to run the app one month ago doing exactly this.

The problem is that some internal module wants to load a file called `index.js` in `http` module and the file its not there. 

I have reinstalled http moudle but it has not the file

**Comment by therealadum** [comment]
@imanolpg it looks like you are trying to use express? If this isn't the case and one of your dependencies is, can you upload your package.json or link to your project?

**Comment by imanolpg** [comment]
@therealadum yes. I am using express. When internally express tryes to load the file `index.js` from `node_modules/http` it does not found it. I think that the problem is not in the http module itself but in a path inside express

**Comment by therealadum** [comment]
Express can’t be used with the RN runtime - only the Node.js runtime. What is your use case?

**Comment by imanolpg** [comment]
@therealadum i think this is what you mean. I am just importing response from express import `{ response } from 'express'` but in the background express tryes to load `http` node module and it finds `packaje.json`. `package.json` is the only file I have inside `http` module folder `node_modules/http` and when it tryes to find `index.js` it does not find it.

Here is the complete error:

 bundling failed: Error: While trying to resolve module `http` from file `projectPath/node_modules/express/lib/application.js`, the package `projectPath/node_modules/http/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`projectPath/node_modules/http/index.js`. Indeed, none of these files exist:
'projectPath/node_modules/http/index.js`

**Comment by therealadum** [comment]
@imanolpg why do you need the response module? it still has Node.js runtime dependencies, which means you can't use it in react native projects

**Comment by imanolpg** [comment]
@therealadum yes, I need it for the style

**Comment by imanolpg** [comment]
Ok guys. I have figured out the error. It was my mistake when using the variable styles

**Comment by Nimesh1993** [comment]
@imanolpg  I am facing same issue. I am trying to include express like :
const express = require('express')

I am unable to understand the solution from above comments. Could you please let me know how did you resolve the issue.

**Comment by imanolpg** [comment]
@Nimesh1993 when I tryed to build the app I had an error with my styles variable (StyleSheet.create()). The error sayd that I shoud include express. When importing express I had this problem.

I think this error might be due to the path of where the express module is looking for the modules when importing express manually.

My error was a misspelling the variable styles. The error message told me to import express and http but the real error was in the wrong variable id (variable name).

**Comment by Heimdall21** [comment]
I have the exact same problem. Could you please explain where you you had this style variable problem and how you found it?

**Comment by imanolpg** [comment]
@Heimdall21 ensure the variable is correctly spelled. I hat a typo in my program

**Comment by Egehanozsoy** [comment]
> @Heimdall21 ensure the variable is correctly spelled. I hat a typo in my program

what variable can you please be more clear I'm having the same problem as well

**Comment by imanolpg** [comment]
> > @Heimdall21 ensure the variable is correctly spelled. I hat a typo in my program
> 
> what variable can you please be more clear I'm having the same problem as well

It was `style` variable. I was missing a letter
