### ISSUE TITLE
[Android][Image] Image's are not displaying on Android

### ISSUE THREAD

**Issue by justinmakaila** [facebook/react-native#2836]
I'm currently adding support for Android to an existing iOS repo.

There were some issues with importing assets to the Android app (Android is very opinionated on how to name assets), and we solved this by creating an `ImageAssets` module which looks like this:

```javascript
// index.android.js
// Backgrounds
export const BACKGROUND__BLUE_GRADIENT_LOGO = require('image!android_bg__blue_gradient_logo')
export const BACKGROUND__BLUE_GRADIENT = require('image!android_bg__blue_gradient')
...
```
```javascript
// index.ios.js
// Backgrounds
export const BACKGROUND__BLUE_GRADIENT_LOGO = require('image!bg__blue-gradient-logo')
export const BACKGROUND__BLUE_GRADIENT = require('image!bg__blue-gradient')
...
```

This allows us to individually specify which asset to use based on the platform, without having to change our code (It's actually kind of a bummer, but it works for now).

The major issue is that images do not display on Android. Their containers display (`<Image>`) with the correct styles applied, but the image itself is not rendered.

![screen shot 2015-09-17 at 16 19 17](https://cloud.githubusercontent.com/assets/1638996/9960263/85862016-5de7-11e5-9588-01a2759dcf81.png)

The images log out to the console like this:

<img width="893" alt="screen shot 2015-09-18 at 09 26 21" src="https://cloud.githubusercontent.com/assets/1638996/9960286/b9b14c62-5de7-11e5-9429-4258e5131f8b.png">

I'm completely stumped as to what may be happening.

Any ideas?

**Comment by foghina** [comment]
This is more suited as a question on [StackOverflow] than an issue here. I'll try to answer anyway.

It looks to me like you are putting your resources in `mipmap-*dpi`. As per [the documentation][docs], you should be putting them in `drawable-*dpi`. Please update with whether this fixes your issue or not.

[StackOverflow]: http://stackoverflow.com
[docs]: https://facebook.github.io/react-native/docs/image.html#adding-static-resources-to-your-android-app

**Comment by justinmakaila** [comment]
Appreciate the answer. I put them in drawable, and they now show up, but they're the wrong sizes. Consider the initial issue closed. Thanks!

**Comment by foghina** [comment]
The same docs page I linked to explains where to put each drawable. Also note that dimensions used in JS are treated as dp (density-independent), so if you put width/height on your `<Image>` you should use the canonical (i.e. 1x) dimensions.

**Comment by justinmakaila** [comment]
So we should only provide the `drawable-mdpi` (1x) assets?

**Comment by foghina** [comment]
No, 1x assets go in `drawable-mdpi`, 1.5x in `drawable-hdpi` and so on. But in your code, you only use:

    <Image style={{width: <width-of-mdpi>, height: <height-of-mdpi>}} source=...

**Comment by justinmakaila** [comment]
Ah, ok. Thanks!
