### ISSUE TITLE
KeyboardAvoidingView - When keyboardVerticalOffset is too big, view does not return to initial position.

### ISSUE THREAD

**Issue by mattproch** [facebook/react-native#28367]
## Description:

When I set the keyboardVerticalOffset of KeyboardAvoidingView to a number higher than ~180, the view does not return properly to the right position when the keyboard disappears. Lower numbers work fine.

## React Native version:

```
System:
    OS: macOS 10.15.3
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 116.71 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.10.1 - /usr/local/bin/node
    npm: 6.13.7 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

## Steps To Reproduce

I am using React-Navigation 5 tabs navigator and nested stack navigator.

App:

```
<NavigationContainer>
    <BottomTab.Navigator>
        ...
        <BottomTab.Screen name="Post" component={AddPostScreen}/>
    </BottomTab.Navigator>
</NavigationContainer>
```

AddPostScreen:

```
<Stack.Navigator>
    <Stack.Screen name="AddInfoStep">
        {props => <AddInfoStep {...props} setTitle={this.setTitle} post={this.state} addPost={this.addPost} />}
    </Stack.Screen>
    ...
</Stack.Navigator>
```

AddInfoStep:

```
<KeyboardAvoidingView 
    style={{
        alignItems: 'center',
        backgroundColor: '#fff',
        flex: 1,
        justifyContent: 'center',
        padding: 30,
    }} 
    behavior="padding" 
    keyboardVerticalOffset={250}
>
    <View style={styles.imageContainer}>
        <Image >
    </View>

    <Formik >
        {({setFieldValue, handleBlur, handleSubmit, values, touched, errors }) => (
            <>
                <FormTextInput />

                <Button />
            </>
        )}
    </Formik>

    <Link />
</KeyboardAvoidingView>
```

## Expected Results

View should return to initial position.

## Snack, code example, screenshot, or link to a repository:

![BeFunky-collage](https://user-images.githubusercontent.com/20935135/77253392-30cfc280-6c5a-11ea-9daf-33bfec991bae.jpg)

**Comment by hramos** [comment]
Would it be possible to provide a minimum reproduction case? For example, is react-navigation necessary to reproduce this issue?

**Comment by pranavtad** [comment]
I am also having this issue — I use react-navigation with a header and bottomTabNavigator. The keyboardVerticalOffset padding seems to just remain present when the keyboard is dismissed.

**Comment by 3luyka** [comment]
Same issue. Unfortunately, I can't provide a reproducible demo.

**Comment by brunocrpontes** [comment]
I'm facing the same issue. But its hard to find the cause to share a reproducible demo.
