### ISSUE TITLE
Cannot read property 'transformFile'

### ISSUE THREAD

**Issue by mazenwrq** [facebook/react-native#28369]
Hi,
I getting the error code below.

Body:{'type':'InternalError','error':[],'message':'Metro bundler has encountered an error: cann't read property 'transformFile' of undefined'}

![image](https://user-images.githubusercontent.com/9509393/77282342-513b6380-6cd2-11ea-8a1e-4669123618a7.png)

below is package.json:
"name": "test",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-community/masked-view": "^0.1.7",
    "@react-navigation/native": "^5.0.8",
    "@react-navigation/stack": "^5.1.1",
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-gesture-handler": "^1.6.0",
    "react-native-reanimated": "^1.7.0",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-screens": "^2.2.0",
    "react-redux": "^7.2.0",
    "redux": "^4.0.5"
  },
  "devDependencies": {
    "@babel/core": "7.7.5",
    "@babel/runtime": "7.7.6",
    "@react-native-community/eslint-config": "0.0.5",
    "babel-jest": "24.9.0",
    "eslint": "6.7.2",
    "jest": "24.9.0",
    "metro-react-native-babel-preset": "0.56.3",
    "react-test-renderer": "16.9.0"
  },
  "jest": {
    "preset": "react-native"
  }

**Comment by robinalexandre** [comment]
Hi,

How did you resolve this ?

Thanks

**Comment by mazenwrq** [comment]
> Hi,
> 
> How did you resolve this ?
> 
> Thanks

yes

**Comment by robinalexandre** [comment]
> > Hi,
> > How did you resolve this ?
> > Thanks
> 
> yes

Can you explain how did you do please ?

Thanks

**Comment by zcwhdz** [comment]
Can you explain how did you do please ?
Thanks!
@mazenwrq
