### ISSUE TITLE
[Android] WebSocket support

### ISSUE THREAD

**Issue by satya164** [facebook/react-native#2837]
It would be cool to have WebSockets implemented on Android too.

I've implemented a basic working sample with Native Module, but not sure how to contribute to the code to React Native. Any guidance will be appreciated.

**Comment by foghina** [comment]
Check out [README], [DevExperience] and [Using pull requests][PRs]. PRs are greatly appreciated!

[README]: https://github.com/facebook/react-native/blob/master/ReactAndroid/README.md
[DevExperience]: https://github.com/facebook/react-native/blob/master/ReactAndroid/DevExperience.md
[PRs]: https://help.github.com/articles/using-pull-requests/

**Comment by satya164** [comment]
@foghina Okay, I sent a pull request, but I have no idea how to write tests. Could you point me to some docs?

**Comment by Tjorriemorrie** [comment]
What's the status of this? Is it possible to use this at least for dev?

**Comment by mkonicek** [comment]
@Tjorriemorrie Will be merging this today.

**Comment by mkonicek** [comment]
Took longer than expected but it's finally in! See #3229 for details.

**Comment by ide** [comment]
@satya164 @mkonicek awesome work guys!

**Comment by chirag04** [comment]
kudo guys! :+1:

**Comment by chemuto** [comment]
Hi guys. I am trying to connect react native on android with meteor using this ddp client https://github.com/hharnisc/node-ddp-client. 
I am getting an error (Cannot read property 'connect' of undefined) at Websocket.js:35:0 (connectToSocketImpl):
RCTWebSocketModule.connect(url, this._socketId);
I am using the react native master branch at 9f1dab69c133841c8da3b67e0a8ded3891b12bb4

Am I doing something wrong or should this thing be working?
Thanks

![screenshot react native error](https://cloud.githubusercontent.com/assets/5112372/10412678/ebe38e9a-6fbf-11e5-8240-424ee191de71.jpg)

**Comment by satya164** [comment]
@chemuto Are you sure that both Java and JavaScript code are in sync?

**Comment by chemuto** [comment]
@satya164 Thanks for your answer. How can I configure/check that?

**Comment by mikemintz** [comment]
I get a similar error trying websocket after installing react-native npm module directly from github: `[TypeError: undefined is not an object (evaluating 'RCTWebSocketModule.connect')]`

**Comment by satya164** [comment]
@chemuto @mikemintz You also need to configure gradle to compile the version you installed instead of the version from maven.

**Comment by ansarizafar** [comment]
@chemuto Is ddp client working for you? I also want to use Meteor backend for my reactnative android app.

**Comment by Sh3kar** [comment]
Use 192.168.xx.xxx:3000 instead of localhost:3000 

var ddpclient = new DDPClient({ url: 'ws://192.168.xx.xxx:3000/websocket'});

**Comment by tgoldenberg** [comment]
@ansarizafar @chemuto  Second that, it would be a huge breakthrough if we can use ddp-client with Android. Please respond to the [SO post](http://stackoverflow.com/questions/33360674/react-native-ddp-connection-for-android)

**Comment by chemuto** [comment]
I just did a small test and seemed to be working. At least a was able to do
a connect through ddp to my meteor server. I will try again when I have
some free time cause I would also like to develop in RN using the meteor
backend.



On Tue, Oct 27, 2015 at 1:50 PM, Thomas Goldenberg <notifications@github.com

**Comment by sunny-g** [comment]
Having this issue with React Native 0.13.2 on iOS. Any help much appreciated!
