### ISSUE TITLE
The development server returned response error code: 500. Invalid property of babel-preset-react-native

### ISSUE THREAD

**Issue by conan19842002** [facebook/react-native#28377]
Description:

   I've got this bug when running 'react-native run-android' on my react-native Android app. I've changed different versions of react-native and also babel-preset-react-native but still did not work

React Native version:

    Run `react-native info` in my terminal and here are the results:
System:
    OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 170.52 MB / 15.32 GB
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 13.6.0 - ~/.nvm/versions/node/v13.6.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 5.3.0 - ~/.nvm/versions/node/v13.6.0/bin/npm
  SDKs:
    Android SDK:
      API Levels: 26, 28, 29
      Build Tools: 26.0.2, 28.0.3, 29.0.3
      System Images: android-29 | Google APIs Intel x86 Atom_64, android-R | Google Play Intel x86 Atom_64
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.54.4 => 0.61.5

## Steps To Reproduce

1. Run 'react-native init myapp'
2. Start a AVD
3. 'react-native run-android'

## package.json file:
{
  "name": "myapp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "react": "16.9.0",
    "react-native": "0.54.4"
  },
  "devDependencies": {
    "@babel/core": "^7.9.0",
    "@babel/runtime": "^7.9.2",
    "@react-native-community/eslint-config": "^0.0.7",
    "babel-jest": "^25.1.0",
    "eslint": "^6.8.0",
    "jest": "^25.1.0",
    "metro-react-native-babel-preset": "^0.59.0",
    "react-test-renderer": "16.9.0"
  },
  "jest": {
    "preset": "react-native"
  }
}

## Expected Results

    A hello world screen.

## Screenshot error:
![Screenshot from 2020-03-23 17-01-21](https://user-images.githubusercontent.com/3224630/77402783-1820f300-6da7-11ea-9a61-b5fa09108afa.png)

**Comment by hramos** [comment]
Can you try running `react-native start` to explicitly start the Metro server?

**Comment by conan19842002** [comment]
Hello,

The Metro server is running but the error is still there.

---



An Nguyen


https://www.linkedin.com/in/annguyen1984
