### ISSUE TITLE
not working on fedora 31, struck at info Starting JS server...

### ISSUE THREAD

**Issue by ashutosh-sajan** [facebook/react-native#28373]
⇒  npx react-native run-android        

info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 864 file(s) to forward-jetify. Using 8 workers...
info Starting JS server...

=>  npx react-native info 
info Fetching system and libraries information...
System:
    OS: Linux 5.5 Fedora 31 (Thirty One) 31 (Thirty One)
    CPU: (8) x64 AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx
    Memory: 1.81 GB / 7.27 GB
    Shell: 5.7.1 - /usr/bin/zsh
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5

**Comment by EvertonCosmo** [comment]
same #26097

**Comment by sajan1231** [comment]
is there any solution to fix this?

**Comment by EvertonCosmo** [comment]
> is there any solution to fix this?
temporary fix 
https://github.com/facebook/react-native/issues/26097#issuecomment-570109662
