### ISSUE TITLE
Invariant Violation: Native module cannot be null

### ISSUE THREAD

**Issue by SunilPandey-** [facebook/react-native#28372]
Description:

    Please provide a clear and concise description of what the bug is. Include screenshots if needed.
    Please test using the latest React Native release to make sure your issue has not already been fixed: https://reactnative.dev/docs/upgrading.html

React Native version: 0.61.5

    Run `react-native info` in your terminal and copy the results here.

## Steps To Reproduce

    Provide a detailed list of steps that reproduce the issue.
    Issues without reproduction steps or code are likely to stall.

1.While upgrade from RN-0.59 to RN-0.61.5 I am getting this error: 'Invariant violation: Native module cannot be null.
<img width="421" alt="Screenshot 2020-03-23 at 4 48 33 PM" src="https://user-images.githubusercontent.com/4963103/77311753-bb7df380-6d26-11ea-9b0c-2cbac9d718f8.png">
I am unable to find which library is causing this issue

2.

## Expected Results

    Describe what you expected to happen.

## Snack, code example, screenshot, or link to a repository:

    Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
    You may provide a screenshot of the application if you think it is relevant to your bug report.
    Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by SunilPandey-** [comment]
closing issue, as found library causing after spending 2 days

**Comment by EhteshamAnwar** [comment]
> as found library causing after spending 2 days

@SunilPandey-  do share your solution here.

**Comment by prazgaitis** [comment]
For anyone who ends up here - check to make sure your IDE didn't auto-import a library that you didn't want to include. This was the cause for me!
