### ISSUE TITLE
Launch image on iOS is cached

### ISSUE THREAD

**Issue by antseburova** [facebook/react-native#28389]
## Description
After updating a launch image within `Images.xcassets`, iOS does not pick up the change unless you reinstall the app. That "fix" definitely doesn't work for existing app users who just update the app. Renaming the image file doesn't help.

## React Native version:
0.61.2

## Steps To Reproduce
1. Update a launch image within `Images.xcassets` on iOS
2. Restart/update the app.

## Expected Results
I expect to see the new launch image.

**Comment by denisoliveira** [comment]
@antseburova I think that issue is not from react-native. If you want update the cached image do you need clean the cache.


``` objective-c
NSFileManager *fileManager = [NSFileManager defaultManager];
NSString *path = [NSString stringWithFormat:@"%@%@", NSHomeDirectory(),  @"/Library/SplashBoard"];
NSError *error;
if ([fileManager removeItemAtPath:path error:&error]) {
    NSLog(@"Success to delete launch screen cache");
}
else {
   NSLog(@"Failed to delete launch screen cache: %@", error);
}
```

**Comment by antseburova** [comment]
Hi @denisoliveira,
Thank you very much for your response. For some reason, I keep getting the following error when I run your code: `SplashBoard couldn’t be removed.`

**Comment by antseburova** [comment]
@denisoliveira Never mind, the error was there when I was testing it on a simulator. However, When I tested it on a real device, it worked! Thank you so much!
A note for people who will try the same approach in the future: the first time you launch the app the cache is cleared after the launch image is displayed. So, you will be able to see the new image only on the next app launch.
