### ISSUE TITLE
RN@0.57.8 Red Screen with warning.length undefined

### ISSUE THREAD

**Issue by vikas1992** [facebook/react-native#28388]
## Description
I npm install'ed in my project and started getting red screen with message "warning.length undefined". I even tried it on a fresh project, init --version@0.57.8, and its reproducible.

## React Native version:
React Native Environment Info:
    System:
      OS: macOS 10.14.6
      CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
      Memory: 187.94 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.18.1 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
      Android SDK:
        API Levels: 23, 25, 26, 27, 28, 29
        Build Tools: 27.0.3, 28.0.3, 29.0.2
        System Images: android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.3/11C29 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3 
      react-native: 0.57.8 => 0.57.8 
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Steps To Reproduce

1. react-native init NewProject --version react-native@0.57.8
2. Run on Android, and you'll see red screen as in screenshot.

## Screenshot:
![Screenshot_2020-03-24-23-40-50-301_com fareye](https://user-images.githubusercontent.com/60089921/77474928-f9ba0680-6e3d-11ea-9285-b1ac88cd2ba6.png)

**Comment by akhileshagrhari** [comment]
facing same issue

**Comment by vikas1992** [comment]
I can't update RN version at this point of time it.
Does anyone else facing this solution or have any work around ?

**Comment by akhtartehseen** [comment]
facing same issue

**Comment by shiwanjalyFareye** [comment]
facing same issue

**Comment by RamolaWeb** [comment]
Facing same issue

**Comment by WGoinz** [comment]
Only happening with android for me. Is anyone else experiencing this with iOS as well?
"react-native": "0.58.6",

**Comment by vin725k** [comment]
Facing same issue 👍🏻

**Comment by shubhampriyadarshi22** [comment]
Facing same issue :(

**Comment by vikas-singh-fareye** [comment]
@WGoinz Yupp, its android only.

**Comment by misomaniac** [comment]
Facing same issue

**Comment by vijay-kumar-gupta** [comment]
I am also facing the same issue.

**Comment by WGoinz** [comment]
@vikas-singh-fareye when you enable "Debug JS Remotely" does your build work?

**Comment by vikas-singh-fareye** [comment]
@WGoinz Yes build is working but we're using realm also in our project. So, when debug mode is on, i'm getting some realm constructor error, before this issue everything was working fine.

**Comment by mohdabid0786** [comment]
facing same issue

**Comment by Varun-sharma0089** [comment]
I am also facing the same issue.

**Comment by vksharma2412** [comment]
I am also facing the same issue.

**Comment by khalidkhan020** [comment]
I am also facing similar issue

**Comment by sundeepsingh12** [comment]
Same issue. Please rectify this as soon as possible .

**Comment by Udbhav12** [comment]
I am facing the exact same issue. I have tried everything,re-installing project from scratch/re-installing node/npm etc

Nothing is working. I am not in favour of writing post installation script and modifying [YellowBoxListRow](https://github.com/facebook/react-native/blob/0.57-stable/Libraries/YellowBox/UI/YellowBoxListRow.js) file  as I don't know what adverse impact it might cause

**Comment by arjunsinghsaini** [comment]
Facing same problem :(

**Comment by TheSavior** [comment]
0.57.8 (the version mentioned in the OP) was released on Dec 13, 2018. That was a very long time ago.

All of you are stuck on 0.57.8 and reporting that you are having the same problem? That seems very surprising.

We also aren't going to be fixing anything a release from 15 months ago. I recommend seeing if this issue occurs on a recent release and opening a new issue with more recent information if it does.

**Comment by Isaacs9** [comment]
I had the same problem and found that the changes are related to @ babel / code-frame and some libraries that each new install adds changes in versions. I suggest you go back to a working commit and run a yarn again, so that you can proceed with the compilation.

**Comment by pjsaxena** [comment]
Try to add all required babel dependencies to your project directly. In my case added below @babel/* devDependencies and that worked for RN@0.57.8.

> "devDependencies": {
>    "@babel/plugin-proposal-class-properties": "7.8.3",
>   "@babel/plugin-proposal-export-default-from": "7.8.3",
>   "@babel/plugin-proposal-nullish-coalescing-operator": "7.8.3",
>   "@babel/plugin-proposal-object-rest-spread": "7.8.3",
>   "@babel/plugin-proposal-optional-catch-binding": "7.8.3",
>   "@babel/plugin-proposal-optional-chaining": "7.8.3",
>   "@babel/plugin-syntax-dynamic-import": "7.8.3",
>   "@babel/plugin-syntax-export-default-from": "7.8.3",
>   "@babel/plugin-syntax-flow": "7.8.3",
>   "@babel/plugin-transform-arrow-functions": "7.8.3",
>   "@babel/plugin-transform-block-scoping": "7.8.3",
>   "@babel/plugin-transform-classes": "7.8.3",
>   "@babel/plugin-transform-computed-properties": "7.8.3",
>   "@babel/plugin-transform-destructuring": "7.8.3",
>   "@babel/plugin-transform-exponentiation-operator": "7.8.3",
>   "@babel/plugin-transform-flow-strip-types": "7.8.3",
>   "@babel/plugin-transform-for-of": "7.8.3",
>   "@babel/plugin-transform-function-name": "7.8.3",
>   "@babel/plugin-transform-literals": "7.8.3",
>   "@babel/plugin-transform-modules-commonjs": "7.8.3",
>   "@babel/plugin-transform-object-assign": "7.8.3",
>   "@babel/plugin-transform-parameters": "7.8.3",
>   "@babel/plugin-transform-react-display-name": "7.8.3",
>   "@babel/plugin-transform-react-jsx": "7.8.3",
>   "@babel/plugin-transform-react-jsx-source": "7.8.3",
>   "@babel/plugin-transform-regenerator": "7.8.3",
>   "@babel/plugin-transform-runtime": "7.8.3",
>   "@babel/plugin-transform-shorthand-properties": "7.8.3",
>   "@babel/plugin-transform-spread": "7.8.3",
>   "@babel/plugin-transform-sticky-regex": "7.8.3",
>   "@babel/plugin-transform-template-literals": "7.8.3",
>   "@babel/plugin-transform-typescript": "7.8.3",
>   "@babel/plugin-transform-unicode-regex": "7.8.3",
>   "@babel/core": "7.8.3",
>   "@babel/types": "7.8.3",
>   "@babel/code-frame": "7.8.3",
>   "@babel/traverse": "7.8.3",
>   "@babel/helper-validator-identifier": "7.9.0",
>   "@babel/helper-module-transforms": "7.8.3",
>   "@babel/helper-function-name": "7.8.3",
>   "@babel/helper-create-class-features-plugin": "7.8.3",
>   "@babel/helpers": "7.8.3",
>   "@babel/helper-builder-react-jsx": "7.8.3",
>   "@babel/generator": "7.8.3",
>   "@babel/parser": "7.8.3",
>   "@babel/highlight": "7.8.3",
>   "@babel/template": "7.8.3",
>   "@babel/runtime": "7.8.3",
> }

**Comment by lchenfox** [comment]
The same issue for me. Android only. React Native version: 0.57.4. Everything works very well before. Only occurring this error after several months. It's very supprising that I really did nothing with project. Tried many ways like reinstall npm dependencies. Unfortunately, all don't work. Any ideas?
