### ISSUE TITLE
What is the upgrade schedule for dependencies like okhttp? 

### ISSUE THREAD

**Issue by dazza5000** [facebook/react-native#28395]
This version of okhttp is over a year oold

https://github.com/facebook/react-native/blob/72ac2125bc8dd28bfd8d94e555458664f9995111/ReactAndroid/gradle.properties#L16

**Comment by hramos** [comment]
Dependencies are upgraded as needed, be that due to bug fixes, new features, or security issues. If there's a need for using a newer version of okhttp, you can upgrade the version and send a pull request after verifying it doesn't introduce any new issues.
