### ISSUE TITLE
Simple App Creation not working

### ISSUE THREAD

**Issue by mgoral2** [facebook/react-native#28391]
Hi.  I am trying to create a react native app using "react-native init NameMyBand".  However, after doing this, when I cd into the created folder and run using "npx react-native run-android" I get the following error:  When I run "adb devices" it successfully detects my android phone that is plugged in with usb.  Thanks!

"error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at '/Users/mg8686./Desktop/NameMyBand/NameMyBand/android/local.properties'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

    at checkExecSyncError (child_process.js:629:11)
    at execFileSync (child_process.js:647:13)
    at runOnAllDevices (/Users/mg8686./Desktop/NameMyBand/NameMyBand/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:94:39)
    at buildAndRun (/Users/mg8686./Desktop/NameMyBand/NameMyBand/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:179:41)
    at then.result (/Users/mg8686./Desktop/NameMyBand/NameMyBand/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:133:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)"

**Comment by mgoral2** [comment]
Here's a new one, running "react-native info" gives me "unknown option: '--info'".  I don't know what command to run

**Comment by ChrisJabb21** [comment]
Hi @mgoral2 I am having the same issue as you are at this time. Have you tried running `npx react-native info`

here is what it looks like for me
`C:\Users\chris\development\React_Native\StarterProject>npx react-native info
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    Memory: 1.76 GB / 15.75 GB
  Binaries:
    Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.21.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    Android Studio: Version  3.5.0.0 AI-191.8026.42.35.6010548
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5`

**Comment by Kunalpaul12** [comment]
Buddy what the error is telling you that it need Android SDK location but it has not found it 

To solve this issues you just need to create local.properties file in root of android folder than in that file  specify the location of the sdk 

example 
`sdk.dir = /Users/yourUserName/Library/Android/sdk`

have a look at the image for refrence
![Screenshot 2020-03-25 at 12 18 51 PM](https://user-images.githubusercontent.com/21304202/77509599-03218e00-6e93-11ea-846c-184799553245.png)

**Comment by mgoral2** [comment]
Thanks @Kunalpaul12 .  Is there an easy way to tell where my android sdk is installed?  I'm using a mac.  Thanks again!

**Comment by ChrisJabb21** [comment]
Hey @mgoral2 I have used mac before and use Windows. Here is a link I found that I think might help out.

**Comment by Kunalpaul12** [comment]
Open android studio and in the main menu u can see SDK maneger which will
tell u the location of the app

**Comment by hramos** [comment]
@mgoral2 the error message points to a issue with your development environment. Make sure to follow all the steps in the Getting Started guide on the website.
