### ISSUE TITLE
Can I write extension in Swift instead of Objective-C?

### ISSUE THREAD

**Issue by goddyZhao** [facebook/react-native#284]

**Comment by vjeux** [comment]
We're not using Swift at Facebook so we're unlikely going to spend time building support for Swift ourself. But, we open sourced the project to get help from the community to add support for what people actually use

**Comment by goddyZhao** [comment]
Ok, got it, thanks so much @vjeux

**Comment by sahrens** [comment]
It's unlikely you'd be able to write an extension in pure swift based on the way the system currently works, but you can probably write the majority in swift and provide a thin registration wrapper in ObjC (implement the RCTBridgeModule protocol) to expose it in JS.

**Comment by mhart** [comment]
Tracked at a high level over at #207
