### ISSUE TITLE
Emulator: emulator: WARNING: EmulatorService.cpp:448: Cannot find certfile: C:\Users\Van Peterson\.android\emulator-grpc.cer security will be disabled.

### ISSUE THREAD

**Issue by Van-peterson** [facebook/react-native#28403]
## Description
I ran the command "react-native run-android"
and the return is this:

19:55	Emulator: emulator: WARNING: EmulatorService.cpp:448: Cannot find certfile: C:\Users\Van Peterson\.android\emulator-grpc.cer security will be disabled.

19:55	Emulator: Started GRPC server at 127.0.0.1:8554

## React Native version:
System:
    OS: Windows 10 10.0.18362
    CPU: (4) x64 Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz
    Memory: 1.30 GB / 7.82 GB
  Binaries:
    Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6241897
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5

  Java --version : 14

## Expected Results
I must be able to compile my project.

## Snack, code example, screenshot, or link to a repository:
  "dependencies": {
    "@react-native-community/async-storage": "^1.7.1",
    "@react-native-community/cli-platform-android": "^3.0.3",
    "@react-native-community/netinfo": "^5.5.1",
    "axios": "^0.19.2",
    "moment": "^2.24.0",
    "numeral": "^2.0.6",
    "qs": "^6.9.1",
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-gesture-handler": "^1.5.2",
    "react-native-image-picker": "^1.1.0",
    "react-native-paper": "^3.4.0",
    "react-native-reanimated": "^1.4.0",
    "react-native-screens": "^2.0.0-alpha.22",
    "react-native-snackbar": "^2.2.0",
    "react-native-unimodules": "^0.7.0",
    "react-native-vector-icons": "^6.6.0",
    "react-native-web": "^0.12.0-rc.1",
    "react-native-webview": "^8.0.3",
    "react-native-youtube": "^2.0.0",
    "react-navigation": "^4.0.10",
    "react-navigation-stack": "^1.10.3",
    "react-navigation-tabs": "^2.6.2",
    "react-redux": "^7.1.3",
    "redux": "^4.0.5",
    "redux-persist": "^6.0.0"
  },

**Comment by mohamaed2019222** [comment]
i have same propleme i cant what i can dot
