### ISSUE TITLE
Modal is visible even when visible is set to false?

### ISSUE THREAD

**Issue by adititipnis** [facebook/react-native#28402]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
https://snack.expo.io/@adititipnis/surprised-ice-cream
The modal is visible even when visible property is set to false

## React Native version:
0.61.4

## Steps To Reproduce
https://snack.expo.io/@adititipnis/surprised-ice-cream
Run the app

## Expected Results
The modal should not be shown when the value for modalVisible is false

## Snack, code example, screenshot, or link to a repository:
https://snack.expo.io/@adititipnis/surprised-ice-cream

**Comment by loverg-c** [comment]
I think its happening on run on web browser and not on ios/android emulator

**Comment by adititipnis** [comment]
> I think its happening on run on web browser and not on ios/android emulator

Yes. This is not happening on my android.
