### ISSUE TITLE
Task :app:stripDebugDebugSymbols FAILED & Task :app:generateDebugBuildConfig FAILED

### ISSUE THREAD

**Issue by Van-peterson** [facebook/react-native#28404]
## Description
I ran the command "react-native run-android"
and the return is this:

> Task :app:stripDebugDebugSymbols FAILED
> Task :app:generateDebugBuildConfig FAILED

## React Native version:
System:
    OS: Windows 10 10.0.18362
    CPU: (4) x64 Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz
    Memory: 1.30 GB / 7.82 GB
  Binaries:
    Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6241897
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5

  Java --version : 13.0.2

## Expected Results
I must be able to compile my project.

![Screen Shoot RN](https://user-images.githubusercontent.com/4678823/77649343-a0e38e80-6f61-11ea-95c0-04a263ed28d3.png)

## Snack, code example, screenshot, or link to a repository:
  "dependencies": {
    "@react-native-community/async-storage": "^1.7.1",
    "@react-native-community/cli-platform-android": "^3.0.3",
    "@react-native-community/netinfo": "^5.5.1",
    "axios": "^0.19.2",
    "moment": "^2.24.0",
    "numeral": "^2.0.6",
    "qs": "^6.9.1",
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-gesture-handler": "^1.5.2",
    "react-native-image-picker": "^1.1.0",
    "react-native-paper": "^3.4.0",
    "react-native-reanimated": "^1.4.0",
    "react-native-screens": "^2.0.0-alpha.22",
    "react-native-snackbar": "^2.2.0",
    "react-native-unimodules": "^0.7.0",
    "react-native-vector-icons": "^6.6.0",
    "react-native-web": "^0.12.0-rc.1",
    "react-native-webview": "^8.0.3",
    "react-native-youtube": "^2.0.0",
    "react-navigation": "^4.0.10",
    "react-navigation-stack": "^1.10.3",
    "react-navigation-tabs": "^2.6.2",
    "react-redux": "^7.1.3",
    "redux": "^4.0.5",
    "redux-persist": "^6.0.0"
  },

**Comment by gabrielmoncea** [comment]
It just happened to me too. I don't know how.
I had to downgrade gradle dependecy
`classpath 'com.android.tools.build:gradle:3.4.2'`

**Comment by xlcrr** [comment]
```
Execution failed for task ':app:stripDebugDebugSymbols'.
> No version of NDK matched the requested version 20.0.5594570. Versions available locally: 21.0.6113669
```

Open Android Studio -> Preferences -> Appearance & Behaviour -> System Settings -> Android SDK -> SDK Tools -> Show Package Details -> Select "NDK" -> select missing package -> Apply

**Comment by EliHood** [comment]
> It just happened to me too. I don't know how. I think from upgrading AndroidStudio
> I had to downgrade gradle dependecy
> `classpath 'com.android.tools.build:gradle:3.4.2'`

I had this issue when cloning a repo, i did a similar approach for example 

the repo was using 

   `  classpath('com.android.tools.build:gradle:3.6.2')`

and i used this build instead

    `classpath("com.android.tools.build:gradle:3.5.2")`

**Comment by magic990619** [comment]
Thank you. @xlcrr 
I have updated the android studio. While updating, NDK version has mismatched I think.
I installed the missed version and then it's working.

**Comment by 007arunwilson** [comment]
> It just happened to me too. I don't know how. I think from upgrading AndroidStudio
> I had to downgrade gradle dependecy
> `classpath 'com.android.tools.build:gradle:3.4.2'`

Done this after a Gradle clean. (y)

**Comment by mattkenefick** [comment]
![image](https://user-images.githubusercontent.com/149809/92240883-4db82500-ee8b-11ea-96ee-cc3cf9dc09c3.png)

For visual people

**Comment by Biplovkumar** [comment]
> Show Package Details

@xlcrr  it helped thanku.

**Comment by jorcelinojunior** [comment]
@xlcrr Thank you very much. You saved me!

**Comment by spandan114** [comment]
check your react-native-image-picker configuration properly.

**Comment by godwin-c** [comment]
> 
> 
> check your react-native-image-picker configuration properly.

Can explain what you mean? What configuration could be causing it?

**Comment by maronski** [comment]
> > check your react-native-image-picker configuration properly.
> 
> Can you explain what you mean? What configuration could be causing it?

@godwin-c  check this:  https://github.com/ivpusic/react-native-image-crop-picker/issues/1416#issuecomment-700644075

**Comment by Sezer67** [comment]
![image](https://user-images.githubusercontent.com/49758941/118046831-8bf2d600-b382-11eb-974a-3b193e12b14e.png)

Bende böyle bir hata alıyorum NDK versiyonu olarak son sürümü yükledim ama hata devam ediyor

**Comment by rohanshukla9** [comment]
inside the build.gradle file there's a specified version given for ndk
`ndkVersion = "20.1.5948944"`

Make sure you are not having any other NDK version in your system.

**Comment by ervalmz27** [comment]
Go inside your SDK location and find the directory called ndk then delete the content inside that directory. Then build the app again. Probably the ndk version has corrupted and Android Studio will replace it with the latest.




16622 silver badges77 bronze badges
This solution is for Unable to find bundled Java version error in your terminal. Its from August 9, 2021 Check the link for the solution stackoverflow.com/a/68703869/8555332 –

**Comment by Jia-SH** [comment]
> 

same problem, don't know how to deal it

**Comment by yalamandarao** [comment]
I'm also facing same issue.  I'm using below build gradle version and NDK.

classpath 'com.android.tools.build:gradle:3.5.4'

ndkVersion "24.0.8215888"

**Comment by cortinico** [comment]
> classpath 'com.android.tools.build:gradle:3.5.4'

Closing as this issue is really old and the version of Android Gradle Plugin are far beyond (7.x). If you're having a similar problem please open another issue
