### ISSUE TITLE
Hide strong password TextInput

### ISSUE THREAD

**Issue by jaroslav009** [facebook/react-native#28416]
When I pass in text input one symbol i got this
![Знімок екрана 2020-03-27 о 17 23 21](https://user-images.githubusercontent.com/33982583/77771687-ad461500-704f-11ea-8c41-d454d3f043a6.png)
How i can hide this yellow block with text "Strong password"?

## React Native version:
react-native: 0.61.5

## Snack, code example, screenshot, or link to a repository:
![Знімок екрана 2020-03-27 о 17 25 38](https://user-images.githubusercontent.com/33982583/77772130-542ab100-7050-11ea-8d1e-c39a72c48b1f.png)
![Знімок екрана 2020-03-27 о 17 27 09](https://user-images.githubusercontent.com/33982583/77772133-55f47480-7050-11ea-8f42-6439b60b517b.png)

**Comment by safaiyeh** [comment]
Hi @jaroslav009 that looks like Safari's password suggestion. Try using `textContentType="none"` on your text input.

**Comment by jaroslav009** [comment]
unfortunately did not help

**Comment by garrettjoecox** [comment]
Happening here as well, no combination of `textContentType` or `autoCompleteType` is working for me.

Might be worth mentioning this only happens for me when I press the "Return" key on the keyboard. The input losing focus does not cause the issue.

**Comment by garrettjoecox** [comment]
A workaround for us was using these props on the TextInput
```
blurOnSubmit={false}
onSubmitEditing={() => Keyboard.dismiss()}
```

Obviously you can replace the Keyboard dismiss with your desired functionality.

**Comment by jaroslav009** [comment]
> A workaround for us was using these props on the TextInput
> 
> ```
> blurOnSubmit={false}
> onSubmitEditing={() => Keyboard.dismiss()}
> ```
> 
> Obviously you can replace the Keyboard dismiss with your desired functionality.

thanks but it did not help

**Comment by AlexandrDobrovolskiy** [comment]
Same on 0.62, `blurOnSubmit` not helping

**Comment by safaiyeh** [comment]
@jaroslav009 is this still an issue?

Could you provide a repro on the latest RN version? Otherwise, feel free to close.

**Comment by enrickdl** [comment]
Still happening to me. Maybe it should be something related to Xcode12?

**Comment by akinlekan28** [comment]
Still happening here too, the issue comes up if you have two textinput with secureTextEntry in a component just as in a form password and confirmpassword input fields.

**Comment by CVincent88** [comment]
Hi same problem here !
And it is indeed happening when there are two inputText with the secureTextEntry in the component.
I was not able to reproduce the error when there is only one.
