### ISSUE TITLE
Animated.Text and ReactCommon/jscallinvoker problem since react-native update

### ISSUE THREAD

**Issue by yasminromi** [facebook/react-native#28418]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Im getting undefined is not a object _reactNative.Animated.Text.propTypes.style since I updated react-native.
I also had the issue CocoaPods could not find compatible versions for pod “ReactCommon/jscallinvoker”.
Returning to 0.61.5 version of react-native stopped the error.

## React Native version:
I had issues using the new 0.62.0 react-native version

## Steps To Reproduce

1. update react-native version
2. try to run your app

## Expected Results
Never had issues with Animated.Text or ReactCommon/jscallinvoker on Podfile before.

## Snack, code example, screenshot, or link to a repository:
https://imgur.com/vAp9zrM
https://imgur.com/kpE0yer

**Comment by netshade** [comment]
`ReactCommon/jscallinvoker` should be `ReactCommon/callinvoker`, see upgrade diff for `ios/Podfile` [here](https://react-native-community.github.io/upgrade-helper/?from=0.61.5&to=0.62.0).

**Comment by yasminromi** [comment]
@netshade I already changed, but still having problems with Animated.Text

**Comment by TheSavior** [comment]
From the changelog: 
https://github.com/react-native-community/releases/blob/master/CHANGELOG.md#removed
`Remove propTypes from Animated components. (86d90c03eb by @yungsters)`

You are probably referencing those proptypes in one of your or your 3rd party package components.

**Comment by TheSavior** [comment]
Do you see this problem when creating a new project? If this issue doesn't occur in a new project, I recommend you create an issue on the [upgrade-support](https://github.com/react-native-community/upgrade-support) repo instead. Sharing your issues when upgrading on that repo will improve the likelihood that you will find others with the same problem and find fixes. It also helps others find you! 😄

**Comment by yasminromi** [comment]
@TheSavior  I just use the style property like below. I even tested my code without the Animated.Text component and still get the same error.

`<Animated.View style={[styles.countDown, { opacity: fadeTimer }]} >` 

I'll open an issue on upgrade-support repo like you suggested, thank you!

**Comment by brunsy** [comment]
@yasminromi If it's not your code, it's probably just one of your dependencies. 
Search node_modules for "Animated.Text.propTypes.style".

**Comment by EricWiener** [comment]
I'm getting the same issue. None of my dependencies contain `Animated.Text.propTypes.style`.

**Comment by lkw1830** [comment]
I'm getting the same error on the release build. Any ideas to solve this issue?

**Comment by EricWiener** [comment]
@lkw1830 it ended up being a dependency problem for me. I thought I was searching globally, but I was actually searching only in my `src` directory. I would do a search for the following line and comment all instances of it out:

```
Text.propTypes.style
```

[I mentioned this in this issue as well](https://github.com/react-native-community/upgrade-support/issues/34#issuecomment-608584342)

**Comment by chakripy** [comment]
I am receiving the same now. When I commented this line of code it worked but the styling looked very bad. 
    style: { }   //Animated.Text.propTypes.style    ----- > passed empty object for style and it worked but looked worse on front end with no proper style.

**Comment by venzersiz** [comment]
I have the same problem with 'react-native-material-dropdown'. When I removed it, everything was ok. Consider 3rd party libraries.

**Comment by sanoopks** [comment]
The issue is with 'react-native'  0.62.2 version. They  have remove 'propTypes' from from core components [.](https://reactnative.dev/blog/2020/03/26/version-0.62#breaking-changes). So In my case the problem is in 'react-native-material-dropdown' which uses 'react-native-material-textfield' that contains `Animated.Text.propTypes.style`. I fixed the error by commenting `Animated.Text.propTypes.style` code in node_modules/react-native-material-textfield.

1.  node_modules/react-native-material-textfield/src/components/label/index.js

Check line 31 or 32, comment the code below inside `static propTypes = {...}`

 **` style: Animated.Text.propTypes.style,`**

2. node_modules/react-native-material-textfield/src/components/affix/index.js

Check line 27 or 28, comment the code below inside `static propTypes = {...}`

 **` style: Animated.Text.propTypes.style,`**

1. node_modules/react-native-material-textfield/src/components/helper/index.js

Check line 13 , comment the code below inside `static propTypes = {...}`

 **` style: Animated.Text.propTypes.style,`**

**Comment by elijahhampton** [comment]
> The issue is with 'react-native' 0.62.2 version. They have remove 'propTypes' from from core components [.](https://reactnative.dev/blog/2020/03/26/version-0.62#breaking-changes). So In my case the problem is in 'react-native-material-dropdown' which uses 'react-native-material-textfield' that contains `Animated.Text.propTypes.style`. I fixed the error by commenting `Animated.Text.propTypes.style` code in node_modules/react-native-material-textfield.
> 
> 1. node_modules/react-native-material-textfield/src/components/label/index.js
> 
> Check line 31 or 32, comment the code below inside `static propTypes = {...}`
> 
> **` style: Animated.Text.propTypes.style,`**
> 
> 1. node_modules/react-native-material-textfield/src/components/affix/index.js
> 
> Check line 27 or 28, comment the code below inside `static propTypes = {...}`
> 
> **` style: Animated.Text.propTypes.style,`**
> 
> 1. node_modules/react-native-material-textfield/src/components/helper/index.js
> 
> Check line 13 , comment the code below inside `static propTypes = {...}`
> 
> **` style: Animated.Text.propTypes.style,`**
> 
> Let's hope 'react-native-material-dropdown' will release new version by fixing the issue.

Thank you for posting!  I just ran into this problem.

**Comment by hcantave** [comment]
I should say it's with 'react-native' > 0.61.5 cause I had the same from version 0.61..5

**Comment by dagan-arbox** [comment]
This is unresolved! 
it is bad the change node_modules folder..

**Comment by CVRamana** [comment]
> The issue is with 'react-native' 0.62.2 version. They have remove 'propTypes' from from core components [.](https://reactnative.dev/blog/2020/03/26/version-0.62#breaking-changes). So In my case the problem is in 'react-native-material-dropdown' which uses 'react-native-material-textfield' that contains `Animated.Text.propTypes.style`. I fixed the error by commenting `Animated.Text.propTypes.style` code in node_modules/react-native-material-textfield.
> 
> 1. node_modules/react-native-material-textfield/src/components/label/index.js
> 
> Check line 31 or 32, comment the code below inside `static propTypes = {...}`
> 
> **` style: Animated.Text.propTypes.style,`**
> 
> 1. node_modules/react-native-material-textfield/src/components/affix/index.js
> 
> Check line 27 or 28, comment the code below inside `static propTypes = {...}`
> 
> **` style: Animated.Text.propTypes.style,`**
> 
> 1. node_modules/react-native-material-textfield/src/components/helper/index.js
> 
> Check line 13 , comment the code below inside `static propTypes = {...}`
> 
> **` style: Animated.Text.propTypes.style,`**
> 
> Let's hope 'react-native-material-dropdown' will release new version by fixing the issue.

doesnt works for me in RN0.63.3
