### ISSUE TITLE
Undefined symbol on Flipper using 0.62 on real iOS device

### ISSUE THREAD

**Issue by jfbaraky** [facebook/react-native#28419]
## Description
I'm not able to run the 0.62 version of the react native when I target a real device on the XCode. Using the simulator is running normally.
I've got this error:
```
Undefined symbol: FlipperState::start(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)
Undefined symbol: folly::ScopedEventBaseThread::ScopedEventBaseThread()
Undefined symbol: facebook::flipper::FlipperClient::instance()
Undefined symbol: folly::ScopedEventBaseThread::~ScopedEventBaseThread()
Undefined symbol: facebook::flipper::FlipperClient::getStateElements()
Undefined symbol: facebook::flipper::FlipperClient::getState()
Undefined symbol: facebook::flipper::FlipperClient::getPlugin(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)
Undefined symbol: facebook::flipper::FlipperClient::setStateListener(std::__1::shared_ptr<FlipperStateUpdateListener>)
Undefined symbol: FlipperStep::complete()
Undefined symbol: facebook::flipper::FlipperClient::performAndReportError(std::__1::function<void ()> const&)
Undefined symbol: facebook::flipper::FlipperClient::init(facebook::flipper::FlipperInitConfig)
Undefined symbol: facebook::flipper::FlipperClient::removePlugin(std::__1::shared_ptr<facebook::flipper::FlipperPlugin>)
Undefined symbol: facebook::flipper::FlipperClient::addPlugin(std::__1::shared_ptr<facebook::flipper::FlipperPlugin>)
Undefined symbol: facebook::flipper::FlipperClient::refreshPlugins()
```

## React Native version:
System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz
    Memory: 1.23 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.11.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.7 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.4/11E146 - /usr/bin/xcodebuild
  Languages:
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.0 => 0.62.0 
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
1. Created a new project with `react-native init`
2. Added a team on the XCode
3. Opened the Flipper application
4. Build using a real iPad as target device

## Expected Results
Expected to run like on the simulator

## Snack, code example, screenshot, or link to a repository:
![image](https://user-images.githubusercontent.com/20716607/77782103-82e75e00-7035-11ea-9a1c-c3b3bc137a42.png)

**Comment by charway** [comment]
I have the same problem

**Comment by charway** [comment]
Try remove the "armv7" in VALID_ARCHS of Build Settings @jfbaraky

**Comment by adamaveray** [comment]
As explained by @charway opening the `Pods.xcproj` project within the workspace, selecting each of the `Flipper*` targets, and editing the "Valid Architectures" to remove `armv7` and `armv7s` stops Xcode trying to build all the Flipper pods for actual devices. This gets overwritten every time `pod install` is run, however, so instead adding the following to the `flipper_post_install` section of the `Podfile` will apply that change automatically on every install:

```ruby
# Post Install processing for Flipper
def flipper_post_install(installer)
  installer.pods_project.targets.each do |target|
    if target.name == 'YogaKit'
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.1'
      end
    end

    # Enable Flipper for simulators only
    if target.name.start_with?('Flipper')
      target.build_configurations.each do |config|
        config.build_settings['VALID_ARCHS'] = 'arm64 arm64e'
      end
    end
  end
end
```

Then since it's no longer being built for those architectures, to stop importing/applying Flipper on actual devices edit your app's `AppDelegate.m` file, replacing the `#if DEBUG` macros with `#if DEBUG && TARGET_OS_SIMULATOR` as below:

```objc
// ...

#if DEBUG && TARGET_OS_SIMULATOR
#import <FlipperKit/FlipperClient.h>
#import <FlipperKitLayoutPlugin/FlipperKitLayoutPlugin.h>
#import <FlipperKitUserDefaultsPlugin/FKUserDefaultsPlugin.h>
#import <FlipperKitNetworkPlugin/FlipperKitNetworkPlugin.h>
#import <SKIOSNetworkPlugin/SKIOSNetworkAdapter.h>
#import <FlipperKitReactPlugin/FlipperKitReactPlugin.h>

static void InitializeFlipper(UIApplication *application) {
  FlipperClient *client = [FlipperClient sharedClient];
  SKDescriptorMapper *layoutDescriptorMapper = [[SKDescriptorMapper alloc] initWithDefaults];
  [client addPlugin:[[FlipperKitLayoutPlugin alloc] initWithRootNode:application withDescriptorMapper:layoutDescriptorMapper]];
  [client addPlugin:[[FKUserDefaultsPlugin alloc] initWithSuiteName:nil]];
  [client addPlugin:[FlipperKitReactPlugin new]];
  [client addPlugin:[[FlipperKitNetworkPlugin alloc] initWithNetworkAdapter:[SKIOSNetworkAdapter new]]];
  [client start];
}
#endif

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
#if DEBUG && TARGET_OS_SIMULATOR
  InitializeFlipper(application);
#endif

// ...
```

The app should now build successfully for actual devices again (the log will show all the Flipper components were skipped).

**Comment by billmoyers** [comment]
Just doing this I got an error `Library not found for -lFlipper-DoubleConversion`.  I  resolved that by removing the `-lFlipper*` entries from `OTHER_LDFLAGS` in the corresponding `Pods-*.xcconfig` file(s), but this seems like the wrong way to do it.

**Comment by 13thdeus** [comment]
@adamaveray thanks. I've build my app under iOS 13.1 succefuly. But build fails for iOS 10.3 with Library not found for "-lFlipper-DoubleConversion", so I've modified flipper pod post install step:
`# Post Install processing for Flipper
def flipper_post_install(installer)
  installer.pods_project.targets.each do |target|
    if target.name == 'YogaKit'
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.1'
      end
    end

    # Enable Flipper for simulators only
    if target.name.start_with?('Flipper') || target.name == 'Flipper'
      target.build_configurations.each do |config|
        config.build_settings['VALID_ARCHS'] = 'arm64 arm64e'
        config.build_settings['ARCHS'] = '${ARCHS_STANDARD_64_BIT}'
      end
    end
  end

  installer.pods_project.save
end`

**Comment by AndrewMorsillo** [comment]
After trying these steps I still can't build for generic device in debug configuration.

```
Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_FlipperClient", referenced from:
      objc-class-ref in libreact-native-flipper.a(FlipperReactNativeJavaScriptPluginManager.o)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by SaveYourTime** [comment]
> After trying these steps I still can't build for generic device in debug configuration.
> 
> ```
> Undefined symbols for architecture armv7:
>   "_OBJC_CLASS_$_FlipperClient", referenced from:
>       objc-class-ref in libreact-native-flipper.a(FlipperReactNativeJavaScriptPluginManager.o)
> ld: symbol(s) not found for architecture armv7
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> ```

Same here 😭

**Comment by adamaveray** [comment]
@AndrewMorsillo @SaveYourTime Have you run `pod install` again after making those changes?

**Comment by AndrewMorsillo** [comment]
Yes I did

**Comment by YahiaJabeur** [comment]
@AndrewMorsillo  @SaveYourTime 
can you plz check the solution here ?
https://github.com/facebook/flipper/issues/976

**Comment by SaveYourTime** [comment]
> @AndrewMorsillo @SaveYourTime
> can you plz check the solution here ?
> [facebook/flipper#976](https://github.com/facebook/flipper/issues/976)

Thank for the suggestion. Finally, I fixed it and successfully build and run with Xcode. 😄

For anyone who is facing the same issue with the react native version v0.62.0 or v0.62.1.
Check this out!

1. Following the upgrade helper to upgrade your project to react native `v0.62.2`
2. Checking your dependencies
> If you don’t have `react-native-flipper` and `flipper-plugin-rn-redux-inspector` in your dependencies, the issue must be fixed after upgraded. 
3. If you have either `react-native-flipper` or `flipper-plugin-rn-redux-inspector` just remove both of them.
> npm uninstall react-native-flipper flipper-plugin-rn-redux-inspector
4. Remove `node_modules` and `Pods`
5. Run `npm install` (or yarn, if you use yarn) and `cd ios && pod install`

**Comment by maxmturner** [comment]
Just in case someone else is having the same problem as me.. I was getting this same error simply because I forgot to edit the scheme in Xcode and switch to Release

**Comment by jonathanmachado** [comment]
I have same problem

**Comment by dtmp** [comment]
if you use react-native-flipper, then you can solve it like this (disable auto-linking for ios react-native-flipper, linking manually for debugging only)

./react-native.config.js

```
module.exports = {
    dependencies: {
        'react-native-flipper': {
            platforms: {
                ios: null,
            },
        },
    },
};
```

./ios/Podfile
```
def add_flipper_pods!(versions = {})
  ...
  
  pod 'react-native-flipper', :path => '../node_modules/react-native-flipper', :configuration => 'Debug'
end
```

**Comment by abeyuya** [comment]
In my case, update react native version from 0.62.0 to 0.62.2 was not fixed.
However, it is now possible to run a real device with the workaround below.

```
  # add_flipper_pods!
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
```

**Comment by declanelcocks** [comment]
@dtmp +1 I had to do the same to get it to work. `react-native-flipper` was still being included in the build and trying to reference Flipper from its `.a` file.

**Comment by jonathanzufi** [comment]
> Try remove the "armv7" in VALID_ARCHS of Build Settings @jfbaraky

Holy *** this also sped up my build time by about 1000x (newbie here). Thank you!

**Comment by CharlesAbetz** [comment]
Yes removing the armv7 architectures works to get a successful build but it m ewans that it excludes iPhone 5s from being supported, I would like them to be supported.

Is there another way to build the flipper kit for armv7?

**Comment by anantha322** [comment]
Update flipper to 0.49 , that should do the trick

**Comment by TheWirv** [comment]
> As explained by @charway opening the `Pods.xcproj` project within the workspace, selecting each of the `Flipper*` targets, and editing the "Valid Architectures" to remove `armv7` and `armv7s` stops Xcode trying to build all the Flipper pods for actual devices. This gets overwritten every time `pod install` is run, however, so instead adding the following to the `flipper_post_install` section of the `Podfile` will apply that change automatically on every install:
> 
> ```ruby
> # Post Install processing for Flipper
> def flipper_post_install(installer)
>   installer.pods_project.targets.each do |target|
>     if target.name == 'YogaKit'
>       target.build_configurations.each do |config|
>         config.build_settings['SWIFT_VERSION'] = '4.1'
>       end
>     end
> 
>     # Enable Flipper for simulators only
>     if target.name.start_with?('Flipper')
>       target.build_configurations.each do |config|
>         config.build_settings['VALID_ARCHS'] = 'arm64 arm64e'
>       end
>     end
>   end
> end
> ```
> 
> Then since it's no longer being built for those architectures, to stop importing/applying Flipper on actual devices edit your app's `AppDelegate.m` file, replacing the `#if DEBUG` macros with `#if DEBUG && TARGET_OS_SIMULATOR` as below:
> 
> ```objc
> // ...
> 
> #if DEBUG && TARGET_OS_SIMULATOR
> #import <FlipperKit/FlipperClient.h>
> #import <FlipperKitLayoutPlugin/FlipperKitLayoutPlugin.h>
> #import <FlipperKitUserDefaultsPlugin/FKUserDefaultsPlugin.h>
> #import <FlipperKitNetworkPlugin/FlipperKitNetworkPlugin.h>
> #import <SKIOSNetworkPlugin/SKIOSNetworkAdapter.h>
> #import <FlipperKitReactPlugin/FlipperKitReactPlugin.h>
> 
> static void InitializeFlipper(UIApplication *application) {
>   FlipperClient *client = [FlipperClient sharedClient];
>   SKDescriptorMapper *layoutDescriptorMapper = [[SKDescriptorMapper alloc] initWithDefaults];
>   [client addPlugin:[[FlipperKitLayoutPlugin alloc] initWithRootNode:application withDescriptorMapper:layoutDescriptorMapper]];
>   [client addPlugin:[[FKUserDefaultsPlugin alloc] initWithSuiteName:nil]];
>   [client addPlugin:[FlipperKitReactPlugin new]];
>   [client addPlugin:[[FlipperKitNetworkPlugin alloc] initWithNetworkAdapter:[SKIOSNetworkAdapter new]]];
>   [client start];
> }
> #endif
> 
> @implementation AppDelegate
> 
> - (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
> {
> #if DEBUG && TARGET_OS_SIMULATOR
>   InitializeFlipper(application);
> #endif
> 
> // ...
> ```
> 
> The app should now build successfully for actual devices again (the log will show all the Flipper components were skipped).

I'm wondering why this it not part of release 0.63.0? Now I have to patch my RN again..

**Comment by Friis1978** [comment]
I found another solution

In podfile, just make sure that the flipper versions are:

  versions['Flipper'] ||= '> 0.49.1'
  versions['DoubleConversion'] ||= '1.1.7'
  versions['Flipper-Folly'] ||= '> 2.1'
  versions['Flipper-Glog'] ||= '0.3.6'
  versions['Flipper-PeerTalk'] ||= '~> 0.0.4'
  versions['Flipper-RSocket'] ||= '~> 1.0'

And in the AppDelegate.m file just add:
TARGET_OS_SIMULATOR to the flipper implementation in line 8, and in didFinishLaunchingWithOptions after the '#if DEBUG' 

thats all, now the app will work on both real devices and simulators.

**Comment by AlinDev** [comment]
@Friis1978  can you please show some code,as it is not clear for me

**Comment by Friis1978** [comment]
@AlinDev, In AppDelegate.m the code should look like this, the only thing to replace is '#if DEBUG' with '#if DEBUG && TARGET_OS_SIMULATOR'

Example:
// ...

#if DEBUG && TARGET_OS_SIMULATOR
#import <FlipperKit/FlipperClient.h>
#import <FlipperKitLayoutPlugin/FlipperKitLayoutPlugin.h>
#import <FlipperKitUserDefaultsPlugin/FKUserDefaultsPlugin.h>
#import <FlipperKitNetworkPlugin/FlipperKitNetworkPlugin.h>
#import <SKIOSNetworkPlugin/SKIOSNetworkAdapter.h>
#import <FlipperKitReactPlugin/FlipperKitReactPlugin.h>

static void InitializeFlipper(UIApplication *application) {
  FlipperClient *client = [FlipperClient sharedClient];
  SKDescriptorMapper *layoutDescriptorMapper = [[SKDescriptorMapper alloc] initWithDefaults];
  [client addPlugin:[[FlipperKitLayoutPlugin alloc] initWithRootNode:application withDescriptorMapper:layoutDescriptorMapper]];
  [client addPlugin:[[FKUserDefaultsPlugin alloc] initWithSuiteName:nil]];
  [client addPlugin:[FlipperKitReactPlugin new]];
  [client addPlugin:[[FlipperKitNetworkPlugin alloc] initWithNetworkAdapter:[SKIOSNetworkAdapter new]]];
  [client start];
}
#endif

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
#if DEBUG && TARGET_OS_SIMULATOR
  InitializeFlipper(application);
#endif

// ...

And in the podfile, just change the  flipper version to: 0.49.1 & DoubleConversion to 1.1.7

**Comment by localdrive** [comment]
As @Friis1978 commented to change the flipper version to: 0.49.1 & DoubleConversion to 1.1.7, it worked for me!

**Comment by samerdernaika** [comment]
im starting to move to flutter because react native start to contain so many issue with no fixed
