### ISSUE TITLE
TypeError: Super expression must either be null or a function

### ISSUE THREAD

**Issue by JonsonHI** [facebook/react-native#28423]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
```
TypeError: Super expression must either be null or a function

_inherits
    inherits.js:5:10
<unknown>
    index.bundle?platform=ios&dev=true&minify=false:157734:27
<unknown>
    index.bundle?platform=ios&dev=true&minify=false:157939:3
loadModuleImplementation
    require.js:321:4
guardedLoadModule
    require.js:210:11
metroRequire
    require.js:128:6
<global>
    index.js:7
loadModuleImplementation
    require.js:321:4
guardedLoadModule
    require.js:210:11
metroRequire
    require.js:128:6
```

## React Native version:
```
System:
    OS: macOS 10.15.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 1.49 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.19.0 - ~/.nvm/versions/node/v10.19.0/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v10.19.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  React-native :
    0.61.5 => 0.62

## Steps To Reproduce
Upgrade error

## Expected Results

```
![image](https://user-images.githubusercontent.com/18373125/77816874-73354b80-7101-11ea-854c-5938bc0a4b18.png)

**Comment by emersonhsieh** [comment]
I had this issue after upgrading from 0.61.5 to 0.62, and it was caused by @expo/react-native-action-sheet. 

https://github.com/expo/react-native-action-sheet/issues/161

**Comment by JonsonHI** [comment]
I had this problem with a lot of files, which made the whole project unusable

**Comment by JonsonHI** [comment]
Turned out to be "teaset": "^0.7.1"
What syntax has RN0.62 updated?

**Comment by felix4321** [comment]
+1

**Comment by JonsonHI** [comment]
```
export default class Base extends TouchableOpacity
```

extends的问题 需要修改所有的  extends

**Comment by RodrigoAngeloValentini** [comment]
+1

**Comment by excitedcat** [comment]
@JonsonHI update `teaset` to 0.7.4, fixed this

**Comment by shrshk** [comment]
I have this problem with 'react-grid-layout'

**Comment by matteocollina** [comment]
I fixed my problem, replacing:
`export class MyComponent extends TouchableHighlight {`
with
`export class MyComponent extends React.Component { `

**Comment by MarkyDeParky** [comment]
> I have this problem with 'react-grid-layout'

Me too in that exact same component, although I'm not using react-grid-layout in a react-native context but in a browser with react-js. I got here just by googling the OP's error. In my case, the issue only appears when I run a 'release', minified build, but not in a debug build. I'll continue to search for a solution and post here if I come across anything.

**Comment by shrshk** [comment]
@MarkyDeParky though the error was trigged on react-grid-layout component 
"terser-webpack-plugin": "2.3.5",
updating the above package fixed the problem for me

**Comment by barak109** [comment]
I used 0.62.2 and it's work fine in IOS , but when i trying to run it with android i get the error you mention above... i checked all your's suggestions but it's didn't help.
Any advise guys?

**Comment by curiousdustin** [comment]
All the workarounds I'm seeing are to change the class you are extending, or upgrade a library.

Can someone explain the underlying issue that causes this error?

**Comment by dzoba** [comment]
I am running into this issue as well and, like @curiousdustin , am really curious of the underlying cause.  I'm not sure where to start looking for what is broken.  The stack trace is minified code on top of minified code.

**Comment by superandrew** [comment]
In my case the problem was indeed react-native-gifted-chat, however I am adding myself to the list of the curious people who would like to know the cause of the problem and mostly why it happens only on android.

**Comment by rishabjain88** [comment]
ni samjh ara

**Comment by MileanCo** [comment]
Im still hitting this problem on iOS. I dont use any of the other dependencies listed in this thread so far 

"react": "17.0.1",
react-native": "0.64.3
"expo": "^43.0.0",

**Comment by ramiel1999** [comment]
In my case it was a a cyclic import. When I fixed the cycle import, it was fixed
