### ISSUE TITLE
Getting "Failed prop type: Invalid props.style key `fontsize` supplied to `Text`." warning

### ISSUE THREAD

**Issue by PragyaSingla** [facebook/react-native#28438]
Getting below warning in console:

Warning: Failed prop type: Invalid props.style key `fontsize` supplied to `Text`.
Bad object: {
  "fontSize": 24,
  "color": "white",
  "marginLeft": 16,
  "marginRight": 16,
  "marginHorizontal": 40,
  "marginTop": 5,
  "fontsize": 32,
  "fontFamily": "Ionicons",
  "fontWeight": "normal",
  "fontStyle": "normal"
}
Valid keys: [
  "display",
  "width",
  "height",
  "start",
  "end",
  "top",
  "left",
  "right",
  "bottom",
  "minWidth",
  "maxWidth",
  "minHeight",
  "maxHeight",
  "margin",
  "marginVertical",
  "marginHorizontal",
  "marginTop",
  "marginBottom",
  "marginLeft",
  "marginRight",
  "marginStart",
  "marginEnd",
  "padding",
  "paddingVertical",
  "paddingHorizontal",
  "paddingTop",
  "paddingBottom",
  "paddingLeft",
  "paddingRight",
  "paddingStart",
  "paddingEnd",
  "borderWidth",
  "borderTopWidth",
  "borderStartWidth",
  "borderEndWidth",
  "borderRightWidth",
  "borderBottomWidth",
  "borderLeftWidth",
  "position",
  "flexDirection",
  "flexWrap",
  "justifyContent",
  "alignItems",
  "alignSelf",
  "alignContent",
  "overflow",
  "flex",
  "flexGrow",
  "flexShrink",
  "flexBasis",
  "aspectRatio",
  "zIndex",
  "direction",
  "shadowColor",
  "shadowOffset",
  "shadowOpacity",
  "shadowRadius",
  "transform",
  "transformMatrix",
  "decomposedMatrix",
  "scaleX",
  "scaleY",
  "rotation",
  "translateX",
  "translateY",
  "backfaceVisibility",
  "backgroundColor",
  "borderColor",
  "borderTopColor",
  "borderRightColor",
  "borderBottomColor",
  "borderLeftColor",
  "borderStartColor",
  "borderEndColor",
  "borderRadius",
  "borderTopLeftRadius",
  "borderTopRightRadius",
  "borderTopStartRadius",
  "borderTopEndRadius",
  "borderBottomLeftRadius",
  "borderBottomRightRadius",
  "borderBottomStartRadius",
  "borderBottomEndRadius",
  "borderStyle",
  "opacity",
  "elevation",
  "color",
  "fontFamily",
  "fontSize",
  "fontStyle",
  "fontWeight",
  "fontVariant",
  "textShadowOffset",
  "textShadowRadius",
  "textShadowColor",
  "letterSpacing",
  "lineHeight",
  "textAlign",
  "textAlignVertical",
  "includeFontPadding",
  "textDecorationLine",
  "textDecorationStyle",
  "textDecorationColor",
  "textTransform",
  "writingDirection"
]
    in Text (at create-icon-set.js:92)
    in Icon (at IconNB.js:90)
    in IconNB (at connectStyle.js:392)
    in Styled(IconNB) (at Icon/index.js:81)
    in Icon (at connectStyle.js:392)
    in Styled(Icon) (at sidebar/index.tsx:64)
    in RCTView (at Button.js:114)
    in TouchableNativeFeedback (at Button.js:106)
    in RCTView (at Button.js:99)
    in Button (at connectStyle.js:392)
    in Styled(Button) (at sidebar/index.tsx:62)
    in RCTView (at View.js:10)
    in ViewNB (at connectStyle.js:392)
    in Styled(ViewNB) (at sidebar/index.tsx:51)
    in RCTView (at View.js:10)
    in ViewNB (at connectStyle.js:392)
    in Styled(ViewNB) (at sidebar/index.tsx:50)
    in RCTView (at Container.js:12)
    in Container (at connectStyle.js:392)
    in Styled(Container) (at sidebar/index.tsx:48)
    in SideBar (created by ConnectFunction)
    in ConnectFunction (at router.tsx:85)
    in contentComponent (at DrawerSidebar.tsx:101)
    in RCTView (at DrawerSidebar.tsx:100)
    in DrawerSidebar (at DrawerView.tsx:157)
    in RCTView (at createAnimatedComponent.js:222)
    in AnimatedComponent (at Drawer.tsx:579)
    in RCTView (at createAnimatedComponent.js:222)
    in AnimatedComponent (at Drawer.tsx:528)
    in PanGestureHandler (at Drawer.tsx:518)
    in Drawer (at DrawerView.tsx:268)
    in DrawerView (at createNavigator.js:80)
    in Navigator (at SceneView.js:9)
    in SceneView (at StackView.tsx:298)
    in RCTView (at CardContainer.tsx:193)
    in RCTView (at CardContainer.tsx:192)
    in RCTView (at Card.tsx:508)
    in RCTView (at createAnimatedComponent.js:151)
    in AnimatedComponent (at Card.tsx:491)
    in PanGestureHandler (at Card.tsx:484)
    in RCTView (at createAnimatedComponent.js:151)
    in AnimatedComponent (at Card.tsx:480)
    in RCTView (at Card.tsx:473)
    in Card (at CardContainer.tsx:160)
    in CardContainer (at CardStack.tsx:581)
    in RCTView (at createAnimatedComponent.js:151)
    in AnimatedComponent (at CardStack.tsx:129)
    in MaybeScreen (at CardStack.tsx:574)
    in RCTView (at CardStack.tsx:104)
    in MaybeScreenContainer (at CardStack.tsx:460)
    in CardStack (at StackView.tsx:411)
    in KeyboardManager (at StackView.tsx:409)
    in RNCSafeAreaView (at src/index.tsx:26)
    in SafeAreaProvider (at SafeAreaProviderCompat.tsx:34)
    in SafeAreaProviderCompat (at StackView.tsx:406)
    in GestureHandlerRootView (at GestureHandlerRootView.android.js:31)
    in GestureHandlerRootView (at StackView.tsx:405)
    in StackView (at StackView.tsx:41)
    in StackView (at createStackNavigator.tsx:33)
    in Unknown (at createNavigator.js:80)
    in Navigator (at SceneView.js:9)
    in SceneView (at src/index.tsx:78)
    in RCTView (at Transitioning.js:133)
    in Wrapped (at src/index.tsx:73)
    in AnimatedSwitchView (at createNavigator.js:80)
    in Navigator (at createAppContainer.js:430)
    in NavigationContainer (at App.tsx:31)
    in Provider (at App.tsx:24)
    in App (at renderApplication.js:40)
    in RCTView (at AppContainer.js:101)
    in RCTView (at AppContainer.js:119)
    in AppContainer (at renderApplication.js:39)

According to warning, we cannot use fontSize prop to 'Text'. But this props is available to use on 'Text'. Please help to solve this issue.

**Comment by ConstantineDB** [comment]
you have both 'fontsize' and 'fontSize' in your style object, try removing 'fontsize'

**Comment by rsmelo92** [comment]
![Screenshot_20200403-231903](https://user-images.githubusercontent.com/16295402/78416758-9714f780-7601-11ea-8f4a-7f380bf5a4e7.png)

**Comment by danielstern** [comment]
This bug is alive and well in the current version of React Native
