### ISSUE TITLE
textAlign: justify can't work if the string is chinese

### ISSUE THREAD

**Issue by qwaszx99** [facebook/react-native#28436]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
textAlign: justify can't work if the string is chinese. when I use English or other languages，it works fine.

## React Native version:
npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.2 => 0.61.2 
  npmGlobalPackages:
    react-native-cli: 2.0.1
## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.
<View style={styles.container}>
        <Text  style={{textAlign: 'justify', paddingHorizontal: 20}}> 这个别说打架，从来就没跟人吵过架的孤僻少年，从小到大就不喜欢跟同龄人待在一起，比陈平安或是顾粲，更像是一头独来独往的野猫崽子。他喜欢有事没事就抓一把石子，一边走一边丢，当然力道都很轻，看似漫不经心的玩耍，没有人当回事，只是马苦玄在廊桥底下的岸边，四下无人的时候，就会独自打水漂，稍稍薄一些的石子，往往能够在水面上打出十数个涟漪之后，撞在对岸石拱桥的内壁上，砰然粉碎，膂力之大，手劲之巧，可想而知。 两人相隔不过十数步而已，之前两次躲避掉马苦玄的石子，陈平安的身形脚步，更偏向于敏捷轻灵，并没有任何泄露出筋骨强壮的地方，草鞋少年就像一片轻飘飘的树叶子，但是陈平安和马苦玄即将对撞的时候，陈平安终于展露出“重”的一面，接连三大步，既快又猛，充满张力，落地如铁锤砸剑条，抬脚则如拔起一座山峰的山根 </Text>
      </View>

## Expected Results
I want the words can be justify
## Snack, code example, screenshot, or link to a repository:
Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by Bruce-zxy** [comment]
+1

**Comment by fabriziobertoglio1987** [comment]
it works for me https://snack.expo.io/@fabrizio.bertoglio/insane-raisins on android

<img src="https://user-images.githubusercontent.com/24992535/82800025-44c2bb00-9e7b-11ea-9e5a-09da41666b5e.png" width="250" />

**Comment by qwaszx99** [comment]
> it works for me https://snack.expo.io/@fabrizio.bertoglio/insane-raisins on android
> 
> <img alt="" width="250" src="https://user-images.githubusercontent.com/24992535/82800025-44c2bb00-9e7b-11ea-9e5a-09da41666b5e.png">

it has some blank-space in right side. I mean both sides can align.

**Comment by fabriziobertoglio1987** [comment]
I measured and they are exactly the same

**Comment by Bruce-zxy** [comment]
> > it works for me https://snack.expo.io/@fabrizio.bertoglio/insane-raisins on android
> > <img alt="" width="250" src="https://user-images.githubusercontent.com/24992535/82800025-44c2bb00-9e7b-11ea-9e5a-09da41666b5e.png">
> 
> it has some blank-space in right side. I mean both sides can align.

中文有一个语法规则是标点符号不能在行首，所以有可能右边的空隙是为了满足这个规则

**Comment by qwaszx99** [comment]
> > it has some blank-space in right side. I mean both sides can align.
> 
> 中文有一个语法规则是标点符号不能在行首，所以有可能右边的空隙是为了满足这个规则
两边分散对齐对中文日文不起作用，它还是按照左对齐的方式，对英文、德文之类起作用，我希望它能够像web 或者ios上面那样两端对齐，这种效果我用android原生实现了，不过比较麻烦，希望官方能够支持一下中文的这种效果

**Comment by gedeagas** [comment]
Can confirm that this is only happening on android. @fabriziobertoglio1987 if you run your snack on iOS it should display the correct behavior instead of the wrong behavior on android ( it has blank-space in both sides).

**Comment by normanzb** [comment]
> it works for me https://snack.expo.io/@fabrizio.bertoglio/insane-raisins on android
> 
> <img alt="" width="250" src="https://user-images.githubusercontent.com/24992535/82800025-44c2bb00-9e7b-11ea-9e5a-09da41666b5e.png">

For justify aligned paragraph there should be no empty space at the end of the line, each character should be evenly spread out to fill the empty at the end and the space between each character should be equal within the same line.

from your screenshot there are a few apparent empty spaces, they are marked out in red:

![image](https://user-images.githubusercontent.com/130634/92490740-47a6a900-f1e9-11ea-9a0c-8b3c70323c3d.png)


here is an example comparison of `text-align:start` and `text-align: justify` rendered inside chrome:

![image](https://user-images.githubusercontent.com/130634/92490429-eda5e380-f1e8-11ea-88e0-f00960b3419d.png)

**Comment by fabriziobertoglio1987** [comment]
quickly went through this issue, I understand the difference now. It's hard to understand/troubleshoot this issues without knowledge of the Chinese Grammar/Layout rules, but for sure if we reproduce this on Android using the same API we are using with ReactAndroid, we maybe be able to understand if the issue is on the Android Sdk or on ReactAndroid. Probably this must be connected to the Android API we are using with ReactAndroid.

**Comment by ayuan-gy** [comment]
Any new developments on this issue?

**Comment by ayuan-gy** [comment]
> > > it has some blank-space in right side. I mean both sides can align.
> > 
> > 
> > 中文有一个语法规则是标点符号不能在行首，所以有可能右边的空隙是为了满足这个规则
> 
> 两边分散对齐对中文日文不起作用，它还是按照左对齐的方式，对英文、德文之类起作用，我希望它能够像web 或者ios上面那样两端对齐，这种效果我用android原生实现了，不过比较麻烦，希望官方能够支持一下中文的这种效果

原生是怎么实现的

**Comment by fabriziobertoglio1987** [comment]
@qwaszx99 Do you still experience this issue? If yes, I will publish the fix in the react-native-improved package https://github.com/fabriziobertoglio1987/react-native-improved. Thanks a lot
