### ISSUE TITLE
Error running project on Android in Linux: Sha1 not computed

### ISSUE THREAD

**Issue by dmerniestic1987** [facebook/react-native#28432]
## Description
I can't run an app in my linux environment with an Android emulator with AVD. Application breaks before starting by calculation of sha-1

## React Native version:
System:
    OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 162.13 MB / 15.55 GB
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.21.1 - /usr/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Python: 2.7.15+ - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Run a new emulator with AVD.
2. react-native start
3. react-native run-android

## Expected Results
Run the application in the android emulator

## Snack, code example, screenshot, or link to a repository:
![Screenshot_20200328_201846](https://user-images.githubusercontent.com/38772839/77836037-60d30600-7131-11ea-8db5-99d771617889.png)

Stacktrace
```
error: ReferenceError: SHA-1 for file /home/diegoall/.nvm/versions/node/v12.16.1/lib/node_modules/react-native/node_modules/metro/src/lib/polyfills/require.js (/home/diegoall/.nvm/versions/node/v12.16.1/lib/node_modules/react-native/node_modules/metro/src/lib/polyfills/require.js) is not computed
    at DependencyGraph.getSha1 (/home/diegoall/.nvm/versions/node/v12.16.1/lib/node_modules/react-native/node_modules/metro/src/node-haste/DependencyGraph.js:263:13)
    at /home/diegoall/.nvm/versions/node/v12.16.1/lib/node_modules/react-native/node_modules/metro/src/DeltaBundler/Transformer.js:211:26
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/home/diegoall/.nvm/versions/node/v12.16.1/lib/node_modules/react-native/node_modules/metro/src/DeltaBundler/Transformer.js:46:24)
    at _next (/home/diegoall/.nvm/versions/node/v12.16.1/lib/node_modules/react-native/node_modules/metro/src/DeltaBundler/Transformer.js:66:9)
    at /home/diegoall/.nvm/versions/node/v12.16.1/lib/node_modules/react-native/node_modules/metro/src/DeltaBundler/Transformer.js:71:7
    at new Promise (<anonymous>)
    at /home/diegoall/.nvm/versions/node/v12.16.1/lib/node_modules/react-native/node_modules/metro/src/DeltaBundler/Transformer.js:63:12
    at Transformer.transformFile (/home/diegoall/.nvm/versions/node/v12.16.1/lib/node_modules/react-native/node_modules/metro/src/DeltaBundler/Transformer.js:236:7)
    at /home/diegoall/.nvm/versions/node/v12.16.1/lib/node_modules/react-native/node_modules/metro/src/Bundler.js:87:34
```

**Comment by abdelrahmannasr** [comment]
any update about this issue, I have this issue too

**Comment by rfischer** [comment]
I had the same problem and resetting the cache helped me:
 
`react-native start --reset-cache`
