### ISSUE TITLE
High CPU load of diagnosticd process while running React Native app on iOS simulator

### ISSUE THREAD

**Issue by maartenvandillen** [facebook/react-native#28442]
## Description
After running a React Native app in debug mode on the iOS simulator (either directly from Xcode or via react-native run-ios) the diagnosticd process slowly increases CPU usage to 150% after a couple of (5 to 10) minutes. My laptop becomes unusable because the process is also eating up all file handles of the OS. Pressing the home button on the simulator immediately drops cpu usage and releases all resources.

## React Native version:
System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4750HQ CPU @ 2.00GHz
    Memory: 454.38 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.4.0 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 5.6.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 23.0.1, 25.0.2, 26.0.1, 26.0.2, 27.0.3, 28.0.0, 28.0.3, 29.0.0
      System Images: android-27 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5977832
    Xcode: 11.4/11E146 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.11.0 => 16.11.0
    react-native: 0.62.0 => 0.62.0
  npmGlobalPackages:
    create-react-native-app: 1.0.0
    react-native-cli: 2.0.1
    react-native-create-library: 3.1.2
    react-native-git-upgrade: 0.2.7
    react-native-rename: 2.2.2

## Steps To Reproduce
1. npx react-native init AwesomeProject
2. react-native run-ios
3. wait 5 to 10 minutes while monitoring the cpu usage of the diagnosticd process

## Expected Results
Normal cpu usage so that I can develop more than 5 minutes.

## Snack, code example, screenshot, or link to a repository:
This happens on a new project.

[Edit]
I just realised this has always happened on my system while the simulator was showing the (any) red error screen of a RN app. Dismissing the error would lower the cpu again. The difference is, this is now also happening during normal app operation.

**Comment by maartenvandillen** [comment]
[Sample of diagnosticd.txt](https://github.com/facebook/react-native/files/4413970/Sample.of.diagnosticd.txt)
I managed to sample the diagnosticd process just before my system became unstable again. Maybe this helps?

**Comment by JackClown** [comment]
I am facing the  same problem

**Comment by maartenvandillen** [comment]
@JackClown That's too bad, but I'm glad I'm not the only one. I had found a work around by starting a debug session on an Android device and hijacking that with the iOS simulator (just reload the JS while debugging). This solved the problem for a while. Then I noticed it was also working normally without the workaround for a couple of days. But since yesterday it's back again. I still have no clue what is causing it.

**Comment by JackClown** [comment]
@maartenvandillen Thank you! And my workaround is that just closing the APP and opening it again. Of course, this is extremely time-consuming.😔

**Comment by maartenvandillen** [comment]
Yes that works too. Better not forget to close it before all hell breaks loose. Extremely annoying.

**Comment by maartenvandillen** [comment]
I have found that Xcode is logging a lot of these lines: `xcode nw_connection_get_connected_socket Client called nw_connection_get_connected_socket on unconnected nw_connection`. A few of them every second. Shutting down NSLog by adding an environment variable `OS_ACTIVITY_MODE` with value `disable` to the Scheme (Run) in Xcode fixes the high cpu usage of the diagnosticd process. However, the resources (file or network socket handles) are still being used up resulting in an unstable system after a couple of minutes.

**Comment by syaau** [comment]
The memory usage also starts to gradually increase.

**Comment by Sebastian-Neubert** [comment]
This solved the problem for me:
https://stackoverflow.com/a/39461256/8184317

**Comment by maartenvandillen** [comment]
@Sebastian-Neubert are you sure? At first I thought that had solved my problem too, but it turns out my laptop becomes just as unstable after a while. It's true the high cpu load disappears but the system resources are still being used up.

**Comment by Sebastian-Neubert** [comment]
@maartenvandillen You've got a point with that. The high cpu usage of diagnosticd is gone but has simply been "shifted" to the app process for me. The only advantage with this is that there is more time before I have to restart the app again because the cpu usage is increasing slower than for diagnosticd.

**Comment by maartenvandillen** [comment]
Problem still persists. Sometimes it's gone for one app run but then the next run it's back again.

**Comment by russelRajitha** [comment]
Issue still exist on macbook pro 2017,i5, big sur. suddenly close all apps like chrome, intellij skype etc. what is exactly this issue? any help please.

**Comment by DigitalZebra** [comment]
I noticed I started getting this issue after switching around the default ports/bundle location used by the app when running on a simulator. After resetting everything to the defaults (dev menu -> configure bundler -> reset to default) the high CPU usage SEEMS to have improved.

**Comment by maartenvandillen** [comment]
@DigitalZebra thanks for the info. I never change anything in the dev menu. However, a default installation (react-native init) does not work on the iOS Simulator on my machine. It always shows the error No bundle URL present. To fix this I have to change the url in AppDelegate.m to 127.0.0.1:8081. Maybe this is the cause of the high CPU usage? Does anybody else who commented in this issue have the same problem?

**Comment by maartenvandillen** [comment]
I think I found the solution! I was always wondering why the default url in AppDelegate.m did not work. So I started focusing on that. It turns out that my huge adblocking hosts file was the cause of this. Restoring the original /etc/hosts file solved both problems! 🎉
