### ISSUE TITLE
Ideal Image element resizing doesn't seem to be happening with CameraRoll

### ISSUE THREAD

**Issue by jasonmerino** [facebook/react-native#2844]
I am trying to render out some images from the CameraRoll and am running into trouble with it rendering the full sized images. The Image element documentation says that it will choose the most optimal image size when loading images from a camera roll.

> iOS saves multiple sizes for the same image in your Camera Roll, it is very important to pick the one that's as close as possible for performance reasons. You wouldn't want to use the full quality 3264x2448 image as source when displaying a 200x200 thumbnail. If there's an exact match, React Native will pick it, otherwise it's going to use the first one that's at least 50% bigger in order to avoid blur when resizing from a close size. All of this is done by default so you don't have to worry about writing the tedious (and error prone) code to do it yourself.

[Documentation Reference](https://facebook.github.io/react-native/docs/image.html#best-camera-roll-image)

I tracked down the code that looks like it should resize the image and when I set a breakpoint it never gets hit. [Here are the lines that never get hit.](https://github.com/facebook/react-native/blob/master/Libraries/Image/RCTImageView.m#L180-L189) Note that this is for v0.11.0 and master is already different, so maybe this has been fixed.

Am I missing something like a property that I'm not passing to the Image element, or is the automatic most optimal image selection not working as I think it should?

**Comment by mkonicek** [comment]
Looks like @nicklockwood might have context on this.

**Comment by jasonmerino** [comment]
Anyone have any more information on this?

**Comment by aroth** [comment]
Can you better summarize what is (or is not) happening on your end? (screenshots, etc)

Also, please try the latest release if possible. Version 0.12 just landed with additional CameraRoll refactoring. You'll need to add the RCTCameraRoll library and then link it under Build Phases. I can better help you then.

**Comment by jasonmerino** [comment]
@aroth I can probably get a better description of what is going on in the next day or two. I'll try updating to 0.12 first to see if that resolves it. Thanks.

**Comment by jasonmerino** [comment]
@aroth So after updating to 0.12 I am not seeing the same behavior. Whether that is because something was fixed or I was misunderstanding what was going on...who knows.

Thanks for the help!
