### ISSUE TITLE
iOS: Compile fails when gflags is installed

### ISSUE THREAD

**Issue by KDederichs** [facebook/react-native#28446]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
When trying to build an iOS version of a react native app, the compilation of the `glog` (and `Flipp-er-Glog`) pods will fail if the machine has the gflags package installed (`brew install gflags`).
This seems to be due to the configure script picking up the `gflags.h` file and in turn enabling this line in logging.h by setting the if precompile flag to true:

```
#if 0
#include <gflags/gflags.h>
#endif
```

## React Native version:

```
System:
    OS: macOS 10.15.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
    Memory: 16.84 GB / 64.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.14.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-29 | Google Play Intel x86 Atom
  IDEs:
    Xcode: 11.4/11E146 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5
```

This bug should hit all existing RN versions that relay on glog and starting RN 62 also the Flipper integration.

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. install gflags via `brew install gflags`
2. try to compile a fresh react native project that was setup AFTER! you installed `gflags`

## Expected Results
The app should still compile regardless if the user has setup gflags or not.

## Snack, code example, screenshot, or link to a repository:
Not needed

**Comment by KDederichs** [comment]
Still in the Backlog

**Comment by KDederichs** [comment]
I'd assume it's still an issue

**Comment by waqas19921** [comment]
I am also facing this issue it is due to wrong glog which is installed using brew. But why i have to remove all the glog in mac os.

**Comment by waqas19921** [comment]
Following steps worked for me
1. Remove gflags from homebrew
`brew uninstall --ignore-dependencies gflags`
2. Run following command to clear all cache from pod and xcode.
`rm -rf ~/Library/Caches/CocoaPods Pods ~/Library/Developer/Xcode/DerivedData/*; pod deintegrate; pod setup; pod install;`

**Comment by KDederichs** [comment]
Yes uninstalling it "fixes" it.
The problem is that it sees the system level header files and tries to compile them into the project.
I actually did open a PR back in March that would fix the issue but so far no one cared :)
https://github.com/facebook/react-native/pull/28451

**Comment by alesso-x** [comment]
I'm receiving the following error for `glog` using `react-native` 0.63.4. It might be a separate issue but seems `glog` and brew dependencies are conflicting.

```
checking build system type...
/Users/alesso/Library/Caches/CocoaPods/Pods/External/glog/2263bd123499e5b93b5efe24871be317-40a13/missing: Unknown `--is-lightweight' option
Try `/Users/alesso/Library/Caches/CocoaPods/Pods/External/glog/2263bd123499e5b93b5efe24871be317-40a13/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
Invalid configuration `arm64-apple-darwin21.2.0': machine `arm64-apple' not recognized
configure: error: /bin/sh ./config.sub arm64-apple-darwin21.2.0 failed
```

```
System:
    OS: macOS 12.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 314.55 MB / 16.00 GB
    Shell: 3.3.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 17.3.1 - /opt/homebrew/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.3.0 - /opt/homebrew/bin/npm
    Watchman: 2022.01.03.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7935034
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
    Python: 2.7.18 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: ~0.63.4 => 0.63.4
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Following the comments above, I removed `gflags` but still had the issue. I left `gflags` installed (it's a dependency for `watchman`) and uninstalled all my other brew dependencies. I went one by one installed each brew dependencies and ran `pod install`. I found that `coreutils` is the one causing the error.

**Comment by shubhambajoria11** [comment]
<img width="802" alt="image" src="https://user-images.githubusercontent.com/66531296/219923058-0d2c6a5f-8ea3-400d-9a77-ec167d341da3.png">


Open Xcode and go to Preferences. 

then go to the command line tools and then select the Xcode version from the drop down
Also ensure that the below location is also visible (/Applications/Xcode.app)


This solved my problem

**Comment by Teczer** [comment]
> <img alt="image" width="802" src="https://user-images.githubusercontent.com/66531296/219923058-0d2c6a5f-8ea3-400d-9a77-ec167d341da3.png">
> 
> Open Xcode and go to Preferences.
> 
> then go to the command line tools and then select the Xcode version from the drop down Also ensure that the below location is also visible (/Applications/Xcode.app)
> 
> This solved my problem

GOAT
