### ISSUE TITLE
Custom fonts not working on React-Native 0.62

### ISSUE THREAD

**Issue by aldimirprincipal** [facebook/react-native#28448]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
I'm trying to use a custom font on my app but it doesn't work. I have followed numerous steps from other similar questions but nothing works.

I'm not getting any error.

The path to the assets folder: https://i.stack.imgur.com/loEph.png

This is what I tried:

1. Creating react-native.config.js file on root project with the following code:

```
module.exports = {
    project: {
      ios: {},
      android: {},
    },
    assets: ['./src/assets/fonts']
  };
```

2. Running react-native link: This didnt give me any errors:

```
info Linking assets to ios project
info Linking assets to android project
success Assets have been successfully linked to your project
```

3. Naming the font exactly as its named in styles WITHOUT using any fontWeight:

```
<Text style={[styles.texto_Titulo, {fontFamily: "LatoBlack"}]}>
      ENTRADA
</Text>
```
Recompiling with npx react-native run-android after react-native link

In android/src/main/assets/fonts they get correctly added.
The name I use is the same and is correct, and I also tried changing the names to lower case but that didn't work.

Why is this not working?

## React Native version:
Binaries:
    Node: 13.9.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.13.7 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6241897
  Languages:
    Python: 2.7.17
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.9.0 => 16.9.0
    react-native: ^0.62.0 => 0.62.0
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by anwersolangi** [comment]
I also got the same issue.... I follow the guideline https://medium.com/@mehran.khan/ultimate-guide-to-use-custom-fonts-in-react-native-77fcdf859cf4.
I Created the react-native.config.js file with 
module.exports = {
  project: {
    ios: {},
    android: {},
  },
  assets: ['./assets/fonts'],
};

run the npx react-native link and also tried with yarn react-native link and there is no error.
I saw the fonts in the android/src/main/assets/fonts folder with my fonts.
I use the same and correct font name which i used in the fonts file but still not getting the desired/custom fonts. I also tried to make the font name in lower case also but that did not work also.
Please look over the issue and resolve it. Thanks

**Comment by ajiehatajie** [comment]
same issue in version 0.62

**Comment by anwersolangi** [comment]
> same issue in version 0.62

I got it working by changing the directory of the assets/fonts folder from the android/src/main/assets to android/app/src/main/assets/fonts
i think the problem is somehow in the linking process/react-native-cli.
This is temporary solution for the problem. But we want it to be fixed as soon as possible, Thanks

**Comment by aldimirprincipal** [comment]
As @anwersolangi commented, copying the assets to android/app/src/main/ worked wonders! Please fix this bug for future problems because this is just a workaround and sometimes this just doesnt happen, so its inconsistent.

**Comment by turbothinh** [comment]
@anwersolangi did you fix for iOS?

**Comment by anwersolangi** [comment]
> @anwersolangi did you fix for iOS?

I use this for android development only.

**Comment by regalstreak** [comment]
`npx react-native link` isn't working for me after adding
```
module.export = {
    project: {
        ios: {},
        android: {}
    },
    assets: ['./assets/fonts/']
}
```

I had to manually copy my `assets` directory to `android/app/src/main` to make them work on Android. For iOS, you'll have to search for a guide or something and edit Info.plist or use xcode to generate it.

**Comment by maaz-jabbar** [comment]
Use the manual Linking procedure in this guide
https://medium.com/@mehran.khan/ultimate-guide-to-use-custom-fonts-in-react-native-77fcdf859cf4

**Comment by sonvodev** [comment]
Was it fixed?
I'm using react native newest version to test but it seems to not working
I followed 2 links
https://medium.com/@mehran.khan/ultimate-guide-to-use-custom-fonts-in-react-native-77fcdf859cf4
https://medium.com/react-native-training/react-native-custom-fonts-ccc9aacf9e5e

When i ran react-native link. I saw the fonts were linked to android/app/src/main/assets/fonts
But nothing special then. For the ios, it's working smoothly.
Please give me some advices. 
Thank in advance!

**Comment by ilya-raevskiy** [comment]
> Was it fixed?
> I'm using react native newest version to test but it seems to not working
> I followed 2 links
> https://medium.com/@mehran.khan/ultimate-guide-to-use-custom-fonts-in-react-native-77fcdf859cf4
> https://medium.com/react-native-training/react-native-custom-fonts-ccc9aacf9e5e
> 
> When i ran react-native link. I saw the fonts were linked to android/app/src/main/assets/fonts
> But nothing special then. For the ios, it's working smoothly.
> Please give me some advices.
> Thank in advance!

Same problem, looking for solutions

**Comment by sonvodev** [comment]
@ilya-raevskiy 
I've tried to remove react-native.config.js and added the code below to package.json
It's working now. But i think you can keep react-native.config.js.

`"rnpm": {
    "assets": [
      "./src/assets/fonts"
    ]
  }`

then `rm -rf node_module && yarn install && react-native run-android`

**Comment by SujithStellargoldcoin** [comment]
I have followed the exact same thing mentioned here and it works 

https://medium.com/@mehran.khan/ultimate-guide-to-use-custom-fonts-in-react-native-77fcdf859cf4

Using: Mac OS && React Native 0.62

1. Create a Folder called assets & Create a Fonts folder inside it.
2. Place the fonts in TTF format within there
3. run npx react-native link (I am using native CLI)
4. Open and see your Info.plist and android/app/main/assets/fonts you will see your fonts.

**Comment by wuazhu** [comment]
> Use the manual Linking procedure in this guide
> https://medium.com/@mehran.khan/ultimate-guide-to-use-custom-fonts-in-react-native-77fcdf859cf4
> For both iOS and Android.

it didn't work for my andorid

**Comment by lauriharpf** [comment]
https://medium.com/@mehrankhandev/ultimate-guide-to-use-custom-fonts-in-react-native-77fcdf859cf4 worked on iOS and Android with RN 0.62.2. If it's not working for you:

**Double-check**

1. Are your fonts in TTF format?
1. Did you rename font files as in the article (filename without prefix matches PostScript name)?
1. Have a) font files been copied to `/android/app/src/main/assets/fonts` and b) do `ios/MyProjectName/Info.plist` & `ios/MyProjectName.xcodeproj/project.pbxproj` contain rows with the font file names? If not:
    * Did you run `npx react-native link` (or `react-native link`, depending on your setup)?
    * Did you create the `react-native.config.js` as in the article? (note the two dots, **`.config.js`**)
1. Do you use `fontWeight`? If yes, try removing it (can cause problems on Android, see https://stackoverflow.com/a/58765980 ).
1. Is your style definition correct, e.g. `style={{ fontFamily: "SFUIDisplay-Bold" }}`? Try it on other `<Text>` elements in your app to weed out problems related to the element itself (e.g. the `fontWeight` issue).
1. Have you stopped the Metro bundler and any emulators (e.g. rebooted your machine)?
1. Have you tried other fonts than the ones you actually want? Try e.g. the fonts in the article to rule out problems with your fonts.
1. Are you using Expo instead of vanilla React Native? If yes, check out https://docs.expo.io/guides/using-custom-fonts/

Good luck!

**Comment by putupadang** [comment]
> https://medium.com/@mehrankhandev/ultimate-guide-to-use-custom-fonts-in-react-native-77fcdf859cf4 worked on iOS and Android with RN 0.62.2. If it's not working for you:
> 
> **Double-check**
> 
> 1. Are your fonts in TTF format?
> 2. Did you rename font files as in the article (filename without prefix matches PostScript name)?
> 3. Have a) font files been copied to `/android/app/src/main/assets/fonts` and b) do `ios/MyProjectName/Info.plist` & `ios/MyProjectName.xcodeproj/project.pbxproj` contain rows with the font file names? If not:
>    
>    * Did you run `npx react-native link` (or `react-native link`, depending on your setup)?
>    * Did you create the `react-native.config.js` as in the article? (note the two dots, **`.config.js`**)
> 4. Do you use `fontWeight`? If yes, try removing it (can cause problems on Android, see https://stackoverflow.com/a/58765980 ).
> 5. Is your style definition correct, e.g. `style={{ fontFamily: "SFUIDisplay-Bold" }}`? Try it on other `<Text>` elements in your app to weed out problems related to the element itself (e.g. the `fontWeight` issue).
> 6. Have you stopped the Metro bundler and any emulators (e.g. rebooted your machine)?
> 7. Have you tried other fonts than the ones you actually want? Try e.g. the fonts in the article to rule out problems with your fonts.
> 8. Are you using Expo instead of vanilla React Native? If yes, check out https://docs.expo.io/guides/using-custom-fonts/
> 
> Good luck!



> https://medium.com/@mehrankhandev/ultimate-guide-to-use-custom-fonts-in-react-native-77fcdf859cf4 worked on iOS and Android with RN 0.62.2. If it's not working for you:
> 
> **Double-check**
> 
> 1. Are your fonts in TTF format?
> 2. Did you rename font files as in the article (filename without prefix matches PostScript name)?
> 3. Have a) font files been copied to `/android/app/src/main/assets/fonts` and b) do `ios/MyProjectName/Info.plist` & `ios/MyProjectName.xcodeproj/project.pbxproj` contain rows with the font file names? If not:
>    
>    * Did you run `npx react-native link` (or `react-native link`, depending on your setup)?
>    * Did you create the `react-native.config.js` as in the article? (note the two dots, **`.config.js`**)
> 4. Do you use `fontWeight`? If yes, try removing it (can cause problems on Android, see https://stackoverflow.com/a/58765980 ).
> 5. Is your style definition correct, e.g. `style={{ fontFamily: "SFUIDisplay-Bold" }}`? Try it on other `<Text>` elements in your app to weed out problems related to the element itself (e.g. the `fontWeight` issue).
> 6. Have you stopped the Metro bundler and any emulators (e.g. rebooted your machine)?
> 7. Have you tried other fonts than the ones you actually want? Try e.g. the fonts in the article to rule out problems with your fonts.
> 8. Are you using Expo instead of vanilla React Native? If yes, check out https://docs.expo.io/guides/using-custom-fonts/
> 
> Good luck!

thankyou, my problem is using ### fontWeight

**Comment by putupadang** [comment]
thankyou sir @lauriharpf , my problem is using fontWeight

**Comment by mdehghani65** [comment]
> thankyou sir @lauriharpf , my problem is using fontWeight

me too. I was using fontWeight: 'bold' without including the bold version of the font in the project. after including that too, worked fine

**Comment by hengsoheak** [comment]
I am facing this problem too

**Comment by dougmbarcellos** [comment]
same problem here

**Comment by hkar19** [comment]
in my case on iOS, in some parts i got the fonts working but on other parts it retains default font family and gives error `unrecognized font family`

**Comment by hkar19** [comment]
edit:
In my case, i got it working by using the font name using postscript style:
e.g: if i have a font that has name `Random Font Name Bold` i will name the font file `RandomFontName-Bold` and if i have font such as `Random Font Name` i will name the font file `RandomFontName`

**Comment by irakeshsuthar** [comment]
> https://medium.com/@mehrankhandev/ultimate-guide-to-use-custom-fonts-in-react-native-77fcdf859cf4 worked on iOS and Android with RN 0.62.2. If it's not working for you:
> 
> **Double-check**
> 
> 1. Are your fonts in TTF format?
> 2. Did you rename font files as in the article (filename without prefix matches PostScript name)?
> 3. Have a) font files been copied to `/android/app/src/main/assets/fonts` and b) do `ios/MyProjectName/Info.plist` & `ios/MyProjectName.xcodeproj/project.pbxproj` contain rows with the font file names? If not:
>    
>    * Did you run `npx react-native link` (or `react-native link`, depending on your setup)?
>    * Did you create the `react-native.config.js` as in the article? (note the two dots, **`.config.js`**)
> 4. Do you use `fontWeight`? If yes, try removing it (can cause problems on Android, see https://stackoverflow.com/a/58765980 ).
> 5. Is your style definition correct, e.g. `style={{ fontFamily: "SFUIDisplay-Bold" }}`? Try it on other `<Text>` elements in your app to weed out problems related to the element itself (e.g. the `fontWeight` issue).
> 6. Have you stopped the Metro bundler and any emulators (e.g. rebooted your machine)?
> 7. Have you tried other fonts than the ones you actually want? Try e.g. the fonts in the article to rule out problems with your fonts.
> 8. Are you using Expo instead of vanilla React Native? If yes, check out https://docs.expo.io/guides/using-custom-fonts/
> 
> Good luck!

Just remove fontWeight guys

**Comment by irakeshsuthar** [comment]
> > https://medium.com/@mehrankhandev/ultimate-guide-to-use-custom-fonts-in-react-native-77fcdf859cf4 worked on iOS and Android with RN 0.62.2. If it's not working for you:
> > **Double-check**
> > 
> > 1. Are your fonts in TTF format?
> > 2. Did you rename font files as in the article (filename without prefix matches PostScript name)?
> > 3. Have a) font files been copied to `/android/app/src/main/assets/fonts` and b) do `ios/MyProjectName/Info.plist` & `ios/MyProjectName.xcodeproj/project.pbxproj` contain rows with the font file names? If not:
> >    
> >    * Did you run `npx react-native link` (or `react-native link`, depending on your setup)?
> >    * Did you create the `react-native.config.js` as in the article? (note the two dots, **`.config.js`**)
> > 4. Do you use `fontWeight`? If yes, try removing it (can cause problems on Android, see https://stackoverflow.com/a/58765980 ).
> > 5. Is your style definition correct, e.g. `style={{ fontFamily: "SFUIDisplay-Bold" }}`? Try it on other `<Text>` elements in your app to weed out problems related to the element itself (e.g. the `fontWeight` issue).
> > 6. Have you stopped the Metro bundler and any emulators (e.g. rebooted your machine)?
> > 7. Have you tried other fonts than the ones you actually want? Try e.g. the fonts in the article to rule out problems with your fonts.
> > 8. Are you using Expo instead of vanilla React Native? If yes, check out https://docs.expo.io/guides/using-custom-fonts/
> > 
> > Good luck!
> 
> Just remove fontWeight guys

Thanks Dude . You made my day

**Comment by nbaua** [comment]
Do NOT use **FONT-WEIGHT** this was the main culprit for fonts not working on Android..

**Comment by mtakac** [comment]
But then what do you use to specify the `fontWeight`? It works correctly on iOS for me. Now I would have to create different styles for android and reference different font weights like this: `fontFamily: 'nunitosans_light'` which is not really ideal.

Was anybody able to make custom fonts work with `fontWeight` on Android?

**Comment by nbaua** [comment]
> But then what do you use to specify the `fontWeight`? It works correctly on iOS for me. Now I would have to create different styles for android and reference different font weights like this: `fontFamily: 'nunitosans_light'` which is not really ideal.
> 
> Was anybody able to make custom fonts work with `fontWeight` on Android?

I used different static font files for the regular and bold versions in stead of using weights with the variable fonts.
Why this is better? https://blog.logrocket.com/variable-fonts-is-the-performance-trade-off-worth-it/

I guess this helps.

**Comment by shanu95** [comment]
> https://medium.com/@mehrankhandev/ultimate-guide-to-use-custom-fonts-in-react-native-77fcdf859cf4 worked on iOS and Android with RN 0.62.2. If it's not working for you:
> 
> **Double-check**
> 
> 1. Are your fonts in TTF format?
> 2. Did you rename font files as in the article (filename without prefix matches PostScript name)?
> 3. Have a) font files been copied to `/android/app/src/main/assets/fonts` and b) do `ios/MyProjectName/Info.plist` & `ios/MyProjectName.xcodeproj/project.pbxproj` contain rows with the font file names? If not:
>    
>    * Did you run `npx react-native link` (or `react-native link`, depending on your setup)?
>    * Did you create the `react-native.config.js` as in the article? (note the two dots, **`.config.js`**)
> 4. Do you use `fontWeight`? If yes, try removing it (can cause problems on Android, see https://stackoverflow.com/a/58765980 ).
> 5. Is your style definition correct, e.g. `style={{ fontFamily: "SFUIDisplay-Bold" }}`? Try it on other `<Text>` elements in your app to weed out problems related to the element itself (e.g. the `fontWeight` issue).
> 6. Have you stopped the Metro bundler and any emulators (e.g. rebooted your machine)?
> 7. Have you tried other fonts than the ones you actually want? Try e.g. the fonts in the article to rule out problems with your fonts.
> 8. Are you using Expo instead of vanilla React Native? If yes, check out https://docs.expo.io/guides/using-custom-fonts/
> 
> Good luck!

In my case it works on android after removing font-weight.

**Comment by murtuzamacdev** [comment]
Whats worked for me was:

I had to rename the font file name to the same name as the font name which I would use in fontFamily. 

Example: `fontFamily: "Rancho"`

The file name I had for this Rancho font was `rancho-regular.ttf` (Incorrect)

I renamed it to `Rancho.ttf` (correct) 

And now its working for both Android and iOS

**Comment by RohithBhandaru** [comment]
> Whats worked for me was:
> 
> I had to rename the font file name to the same name as the font name which I would use in fontFamily.
> 
> Example: `fontFamily: "Rancho"`
> 
> The file name I had for this Rancho font was `rancho-regular.ttf` (Incorrect)
> 
> I renamed it to `Rancho.ttf` (correct)
> 
> And now its working for both Android and iOS

This worked for me. Thanks for the pointer. I changed `Arvo-Regular.ttf` to `Arvo.ttf`.

**Comment by pdhruv93** [comment]
> https://medium.com/@mehrankhandev/ultimate-guide-to-use-custom-fonts-in-react-native-77fcdf859cf4 worked on iOS and Android with RN 0.62.2. If it's not working for you:
> 
> **Double-check**
> 
> 1. Are your fonts in TTF format?
> 2. Did you rename font files as in the article (filename without prefix matches PostScript name)?
> 3. Have a) font files been copied to `/android/app/src/main/assets/fonts` and b) do `ios/MyProjectName/Info.plist` & `ios/MyProjectName.xcodeproj/project.pbxproj` contain rows with the font file names? If not:
>    
>    * Did you run `npx react-native link` (or `react-native link`, depending on your setup)?
>    * Did you create the `react-native.config.js` as in the article? (note the two dots, **`.config.js`**)
> 4. Do you use `fontWeight`? If yes, try removing it (can cause problems on Android, see https://stackoverflow.com/a/58765980 ).
> 5. Is your style definition correct, e.g. `style={{ fontFamily: "SFUIDisplay-Bold" }}`? Try it on other `<Text>` elements in your app to weed out problems related to the element itself (e.g. the `fontWeight` issue).
> 6. Have you stopped the Metro bundler and any emulators (e.g. rebooted your machine)?
> 7. Have you tried other fonts than the ones you actually want? Try e.g. the fonts in the article to rule out problems with your fonts.
> 8. Are you using Expo instead of vanilla React Native? If yes, check out https://docs.expo.io/guides/using-custom-fonts/
> 
> Good luck!

Font weight was breaking the family
