### ISSUE TITLE
RN 0.62.0 update = 'folly/gen/String.h' file not found

### ISSUE THREAD

**Issue by lorenc-tomasz** [facebook/react-native#28441]
Hi,
I have updated app to RN 0.62.0 and it doesn't build. I got

`'folly/gen/String.h' file not found` with Flipper-Folly pod

Any suggestions how to fix it?

**Comment by lorenc-tomasz** [comment]
Workaround:

1. Add this to postinstall actions:

`cd ios && rm -rf ~/Library/Caches/CocoaPods Pods ~/Library/Developer/Xcode/DerivedData/*; pod deintegrate; pod setup; pod install --repo-update;"

2. Add this to podfile:

```
# Post Install processing for Flipper
def flipper_post_install(installer)
  installer.pods_project.targets.each do |target|
    if target.name == 'YogaKit'
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.1'
      end
    end
  end
  file_name = Dir.glob("*.xcodeproj")[0]
  app_project = Xcodeproj::Project.open(file_name)
  app_project.native_targets.each do |target|
    target.build_configurations.each do |config|
      cflags = config.build_settings['OTHER_CFLAGS'] || '$(inherited) '
      unless cflags.include? '-DFB_SONARKIT_ENABLED=1'
        puts 'Adding -DFB_SONARKIT_ENABLED=1 in OTHER_CFLAGS...'
        cflags << '-DFB_SONARKIT_ENABLED=1'
      end
      config.build_settings['OTHER_CFLAGS'] = cflags
    end
    app_project.save
  end
  installer.pods_project.save
end
```

**Comment by TheSavior** [comment]
Do you see this problem when creating a new project? If this issue doesn't occur in a new project, I recommend you create an issue on the [upgrade-support](https://github.com/react-native-community/upgrade-support) repo instead. Sharing your issues when upgrading on that repo will improve the likelihood that you will find others with the same problem and find fixes. It also helps others find you! 😄

**Comment by benhjames** [comment]
For anyone else coming to this issue, for us it was caused by the `gen/` line in `.gitignore`...!

**Comment by sraza295** [comment]
> ```
> cd ios && rm -rf ~/Library/Caches/CocoaPods Pods ~/Library/Developer/Xcode/DerivedData/*; pod deintegrate; pod setup; pod install --repo-update;
> ```

Thanks, buddy
you saved my day
