### ISSUE TITLE
Missing user-agent header for ios websocket open connection request

### ISSUE THREAD

**Issue by dusan-dragon** [facebook/react-native#28450]
## Description
When creating websocket connection from react-native app, the ios does not inject `user-agent` header into initial upgrade request.
The android does inject user-agent.

IOS:
```
headers: {
      host: 'localhost:4000',
      'sec-websocket-protocol': 'graphql-ws',
      'sec-websocket-key': 'XYZ==',
      'sec-websocket-version': '13',
      upgrade: 'websocket',
      origin: 'http://localhost:4000',
      connection: 'Upgrade'
    },
```

Android:
```
headers: {
      origin: 'http://localhost:4000',
      'sec-websocket-protocol': 'graphql-ws',
      upgrade: 'websocket',
      connection: 'Upgrade',
      'sec-websocket-key': 'XYZ==',
      'sec-websocket-version': '13',
      host: 'localhost:4000',
      'accept-encoding': 'gzip',
      'user-agent': 'okhttp/3.12.4'
    },
```

## React Native version:
```
info Fetching system and libraries information...
System:
    OS: macOS 10.15.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 3.77 GB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
    npm: 6.12.1 - ~/.nvm/versions/node/v12.13.1/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    @react-native-community/cli: 2.9.0 => 2.9.0
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Open websocket connection from ios
2. Check headers on ws server

## Expected Results
Websocket upgrade request should have user-agent headers

### Possible solution
Set the header here: https://github.com/facebook/react-native/blob/master/Libraries/WebSocket/RCTSRWebSocket.m#L458
I am not sure what would be correct value, was looking for a place where it is set for "normal" request in ios but did not found it.

**Comment by kashif-sk** [comment]
We can add `User-Agent` in header which can be passed as third parameter of Websocket

Following code works for me: 
`let ws = new WebSocket(url, '', {headers: {'User-Agent': 'ReactNative'}});`

**Comment by xipher0** [comment]
The new React Native WebSocket API does not allow setting a user agent. RN 0.63.4

Any ideas how to solve this or inject the user agent header?

**Comment by kashif-sk** [comment]
@xipher0 This works for me on RN 0.63.4

> We can add `User-Agent` in header which can be passed as third parameter of Websocket
> 
> Following code works for me:
> `let ws = new WebSocket(url, '', {headers: {'User-Agent': 'ReactNative'}});`
