### ISSUE TITLE
Brand new Windows installation not allowing me to run any react-native apps on Android. "Task 'installDebug' not found in project ':app'.". 

### ISSUE THREAD

**Issue by ghost** [facebook/react-native#28467]
## Description
My windows got some files corrupted this weekend and I have to format it in order to get back to work. After reinstalling everything, I went back to start working on my react-native project and there's no way I can run it either on my phone or on an AVD.

Task 'installDebug' not found in project ':app'. - Is the error code I get from it, I tried reinstalling all the tools needed, tried running via console, via Kali Linux terminal for W10, via Webstorm and Android Studio but I always get the same error. I also tried creating a new project from scratch in every way I could and got nothing out of it.

What seemed like the most reasonable solution would be to fix the gradle by the search I did on the internet, but all the possible solutions I tried led me to nothing.

## React Native version:
React Native v2.0.1
Node.js v13.12.0
JDK v14
OnePlus 7T Pro AV10

## Steps To Reproduce
Not really much to say on this as it was the first thing that happened once I started trying to run any sort of app on Android.

## Complete error description:
"C:\Program Files\nodejs\node.exe" C:\Users\Metsamies\AppData\Roaming\npm\node_modules\react-native-cli run-android
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 960 file(s) to forward-jetify. Using 8 workers...
info JS server already running.
info Installing the app...

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.0.1/userguide/command_line_interface.html#sec:command_line_warnings

FAILURE: Build failed with an exception.

* What went wrong:
Task 'installDebug' not found in project ':app'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s

Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Task 'installDebug' not found in project ':app'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s

    at makeError (C:\Users\Metsamies\WebstormProjects\Blergh\node_modules\execa\index.js:174:9)
    at C:\Users\Metsamies\WebstormProjects\Blergh\node_modules\execa\index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async runOnAllDevices (C:\Users\Metsamies\WebstormProjects\Blergh\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:94:5)
    at async Command.handleAction (C:\Users\Metsamies\WebstormProjects\Blergh\node_modules\react-native\node_modules\@react-native-community\cli\build\index.js:186:9)
error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.

**Comment by satsuya0114** [comment]
same on macOS 

node : 12.16.1
react-native:  0.62.0
react: 16.11.0
react-native-cli :  2.0.1 
Brand new project with react-native-cli created 

> react-natvie run-android 

got error below:

Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:installDebug'.
> Failed to install on any devices.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 26s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

**Comment by harsh13799** [comment]
same issue occur with me.

**Comment by cortinico** [comment]
Closing as we fixed all the Android/Windows issues in React Native 0.71
