### ISSUE TITLE
KeyboardAvoidingView - Screen is getting render when keyboard pops-up

### ISSUE THREAD

**Issue by sakum22** [facebook/react-native#28462]
## Description
In the latest release 0.62, Keyboard avoiding view is not working as expected. Page is getting rendered within available space when the keyboard shows up.
 
## React Native version:
Run `react-native info` in your terminal and copy the results here.

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Able to see the issue in Expo project given in React native page itself(https://reactnative.dev/docs/keyboardavoidingview)
![image](https://user-images.githubusercontent.com/62931587/78004936-78400800-7358-11ea-9176-79eadae9d47f.png)

When clicked on the username input field,
![image](https://user-images.githubusercontent.com/62931587/78004979-8a21ab00-7358-11ea-8f97-cff27612d669.png)

## Expected Results
Keyboard should come and the View on the screen should remain same when https://reactnative.dev/docs/keyboardavoidingview is used.
Which is when username field is clicked the button should remind in the same place and should be behind the keyboard.

## Snack, code example, screenshot, or link to a repository:
https://snack.expo.io/?session_id=snack-session-Ty_UXxqEW&preview=true&platform=web&iframeId=cyafwt4l53&supportedPlatforms=android,ios&name=KeyboardAvoidingView&description=Example%20usage&waitForData=true

**Comment by akshit5230** [comment]
Can you share your code? Also can you share Android Manifest code?

**Comment by joelrorseth** [comment]
I don't believe you should expect the children of the KeyboardAvoidingView to *always* remain in the same position / layout. In that case, you should just use a normal View. From the KeyboardAvoidingView docs:

> It is a component to solve the common problem of views that need to move out of the way of the virtual keyboard. 

If you look at the [source code](https://github.com/facebook/react-native/blob/master/Libraries/Components/Keyboard/KeyboardAvoidingView.js), KeyboardAvoidingView is really just a View that dynamically adjusts its height / bottom padding (depending on *behavior*), to avoid intersecting the keyboard. If the View will intersect the keyboard when it appears (which it does in the docs example), then the View bounds will change when the keyboard appears.
