### ISSUE TITLE
Switching to RN62.0 from RN61.5 issues

### ISSUE THREAD

**Issue by Sixzero** [facebook/react-native#28475]
## Description
Crashlytics error we receive after the upgrade for 1-3% of users:
Fatal Exception: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes.so caused by: APK was built for a different platform
       at com.facebook.soloader.SoLoader.doLoadLibraryBySoName + 789(SoLoader.java:789)
       at com.facebook.soloader.SoLoader.loadLibraryBySoName + 639(SoLoader.java:639)
       at com.facebook.soloader.SoLoader.loadLibrary + 577(SoLoader.java:577)
       at com.facebook.soloader.SoLoader.loadLibrary + 525(SoLoader.java:525)
       at com.facebook.hermes.reactexecutor.HermesExecutor.<clinit> + 20(HermesExecutor.java:20)
       at com.facebook.hermes.reactexecutor.HermesExecutorFactory.create + 29(HermesExecutorFactory.java:29)
       at com.facebook.react.ReactInstanceManager$5.run + 997(ReactInstanceManager.java:997)
       at java.lang.Thread.run + 761(Thread.java:761)

This happens on devices: 
 - TaintArt for x86, Android 7.1.2
 - SM-A505FN Android 9
 - and some Android 5.1 devices. 

## React Native version:
System:
    OS: Linux 5.3 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
    Memory: 7.80 GB / 62.74 GB
    Shell: 5.4.2 - /usr/bin/zsh
  Binaries:
    Node: 8.13.0 - ~/.nvm/versions/node/v8.13.0/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v8.13.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^16.11.0 => 16.13.0 
    react-native: 0.62.0 => 0.62.0 
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
1. Upgrade to RN62.0 following the steps here: https://react-native-community.github.io/upgrade-helper/?from=0.61.5&to=0.62.0

## Expected Results
There should be no error in crashlytics.

## Snack, code example, screenshot, or link to a repository:
Can't provide example code, but we are based on official example code.

**Comment by farshidshahmoradi1996** [comment]
I have problem with `Hermes Engine` on `release`.

Try to init RN Project in version `0.62.0` and enabling Hermes in `build.gradle` then `clean gradle`.

there is no problem on debug mode but run with `npx react-native run-android --variant=release` crashing .

*log-cat report
--------- beginning of crash
04-02 01:14:57.207 13279 13279 D ReactNative: ReactInstanceManager.ctor()
04-02 01:14:57.275 13279 13279 D ReactNative: ReactInstanceManager.createReactContextInBackground()
04-02 01:14:57.275 13279 13279 D ReactNative: ReactInstanceManager.recreateReactContextInBackgroundInner()
04-02 01:14:57.275 13279 13279 D ReactNative: ReactInstanceManager.recreateReactContextInBackgroundFromBundleLoader()
04-02 01:14:57.275 13279 13279 D ReactNative: ReactInstanceManager.recreateReactContextInBackground()
04-02 01:14:57.275 13279 13279 D ReactNative: ReactInstanceManager.runCreateReactContextOnNewThread()
