### ISSUE TITLE
Cant run using Xcode 7 on IOS 9 iPhone

### ISSUE THREAD

**Issue by lelandcope** [facebook/react-native#2847]
Im having an issue where I go to run the default hello world app that gets installed on `react-native init` on my iPhone and I get the following errors.

<img width="881" alt="screen shot 2015-09-18 at 9 36 33 am" src="https://cloud.githubusercontent.com/assets/4503835/9965138/1a99186a-5de9-11e5-9594-424bf1b45fc2.png">

It will run fine using the simulator. Any help to get this working would be great.

**Comment by ide** [comment]
This should be fixed in the next release.

**Comment by dgellow** [comment]
Hello @ide, could you provide more information about the way to solve this problem?

**Comment by ide** [comment]
You could check out the master branch here and use it, or I think you can disable Dead Code Stripping in your compiler options.

**Comment by dgellow** [comment]
@ide Thank you, it works with Dead Code Stripping disabled
