### ISSUE TITLE
0.62 iOS TextInput font is shaking with chinese

### ISSUE THREAD

**Issue by musicode** [facebook/react-native#28488]
## Description

ios TextInput font is shaking when inputing with chinese.

![QQ20200402-104452-HD](https://user-images.githubusercontent.com/2732303/78205567-076f2c00-74cf-11ea-9116-63580fae6272.gif)

## React Native version:

```
info Fetching system and libraries information...
System:
    OS: macOS 10.15.2
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 20.15 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.2.0 - ~/.nvm/versions/node/v13.2.0/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.13.1 - ~/.nvm/versions/node/v13.2.0/bin/npm
    Watchman: 4.7.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 19, 22, 23, 24, 25, 26, 27, 28, 29
      Build Tools: 23.0.1, 23.0.2, 24.0.0, 24.0.1, 24.0.2, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.3, 28.0.1, 28.0.3, 29.0.0, 29.0.2
      System Images: android-19 | Google APIs Intel x86 Atom, android-23 | Intel x86 Atom, android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-24 | Google APIs Intel x86 Atom, android-25 | Google APIs ARM 64 v8a, android-25 | Google APIs ARM EABI v7a, android-25 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom_64, android-25 | Google Play Intel x86 Atom
      Android NDK: 19.1.5304403
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  Languages:
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.0 => 0.62.0
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by romanakash** [comment]
Maybe try adding fontWeight: "normal" to the text style

**Comment by musicode** [comment]
@romanakash fontWeight is not work.

**Comment by NishidaRyu416** [comment]
I am also facing that issue with Japanese.

**Comment by jiyoon127** [comment]
same issue with Korean

**Comment by NishidaRyu416** [comment]
> I got same issue with Korean. But it's work OK with multiLine mode. Only singleLine mode is the problem.

Yeah exactly!

**Comment by NishidaRyu416** [comment]
I resolved the issue by downgrading the version of react native to 0.61.5😭

**Comment by excitedcat** [comment]
same issue!

**Comment by hisothreed** [comment]
Facing this issue in arabic too, rn 0.60+, enabling multi line fixes the issue

**Comment by ChengGC** [comment]
same issue! rn 0.62.2

**Comment by dlgmltjr0925** [comment]
When entering Korean, there is no shake at fontSize 17, but shake occurs at other sizes.

**Comment by ivinsh** [comment]
same issue!

**Comment by zusinShinpei** [comment]
@alloy @TheSavior anybody cannot reply this issue?

**Comment by excitedcat** [comment]
这个是个大问题，很影响使用啊

**Comment by zgjYswor** [comment]
> When entering Korean, there is no shake at fontSize 17, but shake occurs at other sizes.
same for Chinese

**Comment by bombomzhou** [comment]
i meet the same issue

**Comment by HADMARINE** [comment]
I have the same issue.

**Comment by Liqiankun** [comment]
I got same issue under `react native 0.62.8`.

**Comment by kettyy** [comment]
same issue! `react native 0.62.1`

**Comment by ktjd123** [comment]
It does not happen when ascii char is at the very first of the string.
but when if korean comes first and then ascii comes, it have the problem.

hope helps.

**Comment by Liqiankun** [comment]
@musicode Did you solve it?

**Comment by musicode** [comment]
@Liqiankun not yet

**Comment by alloy** [comment]
Has anybody verified this in `v0.63-rc.0` or `master` yet? If it happens to already be fixed there, then the fix can be identified and perhaps cherry-picked for a new `v0.62.x` release.

**Comment by edoko** [comment]
> Has anybody verified this in `v0.63-rc.0` or `master` yet? If it happens to already be fixed there, then the fix can be identified and perhaps cherry-picked for a new `v0.62.x` release.

I entered Korean, but this issue has the same in `v0.63-rc0`.

**Comment by edoko** [comment]
I guess https://github.com/facebook/react-native/commit/e271fa190d16e7d5d3bc8971c68e4797649d0057 occured this issue.
I reverted this commit, and seems to resolved.

**Comment by alloy** [comment]
Ace, good sleuthing, @edoko 👌 

cc @shergin

**Comment by Liqiankun** [comment]
@edoko Did you test it ? It works?

**Comment by alloy** [comment]
@Liqiankun I don’t know, I’m just an outside spectator. Perhaps you could verify @edoko’s findings by reverting that change in your app and let us know that it works?

**Comment by Liqiankun** [comment]
@alloy? You mean roll back?

**Comment by shergin** [comment]
I afraid, I have no idea how e271fa1 could break it, it just reshuffle stuff a bit without actually changing things much. :(

**Comment by rouge3351** [comment]
in 0.62.2 same issue occurs!

**Comment by Liqiankun** [comment]
@zhongwuzw Would you like to take a look at this issue?

**Comment by alloy** [comment]
> @alloy? You mean roll back?

Yeah, for instance by reverting those changes in your `node_modules/react-native` installation?

**Comment by zhongwuzw** [comment]
> @zhongwuzw Would you like to take a look at this issue?

Hey, https://github.com/facebook/react-native/pull/28805 should fix this issue, can you check it?

**Comment by alloy** [comment]
@zhongwuzw Nice on 🙌

**Comment by Liqiankun** [comment]
@zhongwuzw I know you can make it! That’s why I mention you! I also helped!😂

**Comment by shergin** [comment]
Thank you @zhongwuzw!!1

**Comment by Liqiankun** [comment]
@zhongwuzw I tested it, It worked. Thank you.

**Comment by ifsnow** [comment]
There seems to be a lot of people who are faced on this problem. So, I made this patch(#28805) available for RN 0.62.

Please try it once.

https://github.com/ifsnow/react-native-cjk-textinput-patch

**Comment by rajkumarwaghmare** [comment]
I am using Expo SDK 38 which is still using RN 0.62 https://www.npmjs.com/package/expo
As its Expo ,i cant use above patch to fix the issue.

Any suggestions to fix this issue in this situation?

**Comment by foloinfo** [comment]
I'm also using Expo so this fix hasn't been released.
I could implement a workaround from this comment https://github.com/facebook/react-native/issues/28488#issuecomment-609009993
Use `multiline: true` and set `numberOfLines: 1` will stop shaking the font.

```
<TextInput multiline={true} numberOfLines={1} />
```

**Comment by Yasernova** [comment]
Happens with arabic 2
