### ISSUE TITLE
Library not found after update React Native 0.62

### ISSUE THREAD

**Issue by ilya-raevskiy** [facebook/react-native#28483]
Library not found after update React Native 0.62

```
ld: warning: directory not found for option '-L-L/Users/raevskiy/Library/Developer/Xcode/DerivedData/App-dcmmftlmkqpjgghaeoecsjji/Build/Products/Release-iphonesimulator/BVLinearGradient'
ld: library not found for -lBVLinearGradient
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

<img width="754" alt="Снимок экрана 2020-04-02 в 00 33 41" src="https://user-images.githubusercontent.com/1379392/78178779-9baea400-7479-11ea-84cd-7a43510e092f.png">

React Native version:
```
System:
    OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 183.48 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.11.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 11.4/11E146 - /usr/bin/xcodebuild
  Languages:
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.0 => 0.62.0 
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by matids** [comment]
Same here. It's not related to BVLinearGradient, after deleting the dependency from the project it failed with Base64. 

```
directory not found for option '-L-L/Users/ME/Library/Developer/Xcode/DerivedData/PROJECT-cmusevsphwkwubcskyhaoktwmrir/Build/Products/Debug-iphoneos/Base64'
ld: library not found for -lBase64
```

But if I go to the directory that's on the error message

```
ls /Users/ME/Library/Developer/Xcode/DerivedData/PROJECT-cmusevsphwkwubcskyhaoktwmrir/Build/Products/Debug-iphoneos/Base64
libBase64.a
```
As you can see the library is there...

Things I've tried:
```
rm -rf node_modules
yarn install
cd ios && pod deintegrate && pod install
```


React Native version:
```
System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 413.32 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.9.2 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.0 AI-171.4443003
    Xcode: 11.4/11E146 - /usr/bin/xcodebuild
  Languages:
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: ^0.62.0 => 0.62.0 
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by snairsumith** [comment]
Any updates regarding this issue.I have same issue
<img width="543" alt="Screen Shot 2020-04-07 at 4 03 28 PM" src="https://user-images.githubusercontent.com/8740519/78659559-5eb73700-78e9-11ea-8394-6e27c8e6f4ce.png">
.

**Comment by hoanganhx86** [comment]
I faced the same issue and fixed it by open Xcode and change the `Library Search Paths` to
<img width="847" alt="Screen Shot 2020-04-08 at 15 53 51" src="https://user-images.githubusercontent.com/988115/78764759-398dfb80-79b1-11ea-8e77-fe3d50795a1e.png">

**Comment by hanjjang18** [comment]
@hoanganhx86 
I chage Library Search Paths But Still not working.

**Comment by Mokto** [comment]
It solved the issue for me.

Thanks @hoanganhx86

**Comment by snairsumith** [comment]
I solved the issue by changing the build system from 
File-> Workspace Settings -> Build System -> "New Build System"

**Comment by hoanganhx86** [comment]
> @hoanganhx86
> I chage `Library Search Paths` but still not working.

Can you share your error screen?

**Comment by hanjjang18** [comment]
> > @hoanganhx86
> > I chage `Library Search Paths` but still not working.
> 
> Can you share your error screen?

I solved the issue 

change the  `Library Search Paths` and change build system from `Legacy `to `New Build System`

**Comment by pjay79** [comment]
Same issue for me, tried all the above and not working.

`library not found for -lBase64`

```
System:
    OS: macOS 10.15.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 5.37 GB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.16.2 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 16, 21, 22, 23, 24, 25, 26, 27, 28
      Build Tools: 23.0.1, 25.0.0, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.1, 27.0.2, 27.0.3, 28.0.2, 28.0.3, 29.0.2
      System Images: android-22 | Google APIs Intel x86 Atom, android-25 | Google APIs ARM 64 v8a, android-25 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
      Android NDK: 20.0.5594570
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 11.2.1/11B53 - /usr/bin/xcodebuild
  npmPackages:
    react: ~16.9.0 => 16.9.0
    react-native: ~0.61.5 => 0.61.5
  npmGlobalPackages:
    create-react-native-app: 1.0.0
    react-native-cli: 2.0.1
    react-native-create-library: 3.1.2
    react-native-git-upgrade: 0.2.7
```

**Comment by Rapig1915** [comment]
I am running on MacOS 10.14 Mojave.
Working with React Native 0.62.
Changing build system from Legacy to New worked for me.
Thanks for a Great article!

**Comment by Rapig1915** [comment]
> I solved the issue by changing the build system from
> File-> Workspace Settings -> Build System -> "New Build System"

**Comment by ColtraneNadler** [comment]
Ilya, were you able to resolve this?

I am running into the same issue. Although- I had started with React native 0.62, and everything was working smoothly until I installed a new package, and then I got this error.

**Comment by nsdrt** [comment]
https://medium.com/@punjabicoder/react-native-version-0-62-e7414c2b2d35
here is the solution guys.

**Comment by rahulthakur0090** [comment]
> Ilya, were you able to resolve this?
> 
> I am running into the same issue. Although- I had started with React native 0.62, and everything was working smoothly until I installed a new package, and then I got this error.

https://medium.com/@punjabicoder/react-native-version-0-62-e7414c2b2d35

> Ilya, were you able to resolve this?
> 
> I am running into the same issue. Although- I had started with React native 0.62, and everything was working smoothly until I installed a new package, and then I got this error.

https://medium.com/@punjabicoder/react-native-version-0-62-e7414c2b2d35
check thia

**Comment by TheMrugraj** [comment]
Already have proper other linker flags but, still the same issue.

**Comment by fabriziobertoglio1987** [comment]
follow the instructions at https://github.com/react-native-community/react-native-linear-gradient

remove that library. My opinion is this issue should be closed. 

1) You are not using latest react-native version
2) The issue is connected to an external library https://github.com/react-native-community/react-native-linear-gradient
3) The issue is connected to the user troubleshooting his update process and belongs to stackoverflow
4) There is no reproducible example

Please close. Thanks

**Comment by rahulthakur0090** [comment]
> Already have proper `Library Search Path` but, still the same issue

have you check in both target as well in project

**Comment by jpriesten** [comment]
Thank you @hoanganhx86 
It worked for me

**Comment by aemc** [comment]
I get something similar with Library not found for -lRNFirebase

ld: warning: directory not found for option '-L/Users/user/Library/Developer/Xcode/DerivedData/Mobile-ffdrrqgiyphlinerkjxrqqqeocrs/Build/Intermediates.noindex/ArchiveIntermediates/Mobile/BuildProductsPath/Release-iphoneos/React'

**Comment by trflagg** [comment]
For anyone here whose error string includes `directory not found for option '-L-L/Users/....` (particularly notice the `-L-L`).

The solution is to move `$(inherited)` to the bottom of your Library Search Paths: https://github.com/react-native-community/upgrade-support/issues/36#issuecomment-611516268

**Comment by llMrRongll** [comment]
> Same here. It's not related to BVLinearGradient, after deleting the dependency from the project it failed with Base64.
> 
> ```
> directory not found for option '-L-L/Users/ME/Library/Developer/Xcode/DerivedData/PROJECT-cmusevsphwkwubcskyhaoktwmrir/Build/Products/Debug-iphoneos/Base64'
> ld: library not found for -lBase64
> ```
> 
> But if I go to the directory that's on the error message
> 
> ```
> ls /Users/ME/Library/Developer/Xcode/DerivedData/PROJECT-cmusevsphwkwubcskyhaoktwmrir/Build/Products/Debug-iphoneos/Base64
> libBase64.a
> ```
> 
> As you can see the library is there...
> 
> Things I've tried:
> 
> ```
> rm -rf node_modules
> yarn install
> cd ios && pod deintegrate && pod install
> ```
> 
> React Native version:
> 
> ```
> System:
>     OS: macOS 10.15.4
>     CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
>     Memory: 413.32 MB / 16.00 GB
>     Shell: 5.7.1 - /bin/zsh
>   Binaries:
>     Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
>     Yarn: 1.9.2 - /usr/local/bin/yarn
>     npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
>     Watchman: 4.9.0 - /usr/local/bin/watchman
>   Managers:
>     CocoaPods: 1.9.1 - /usr/local/bin/pod
>   SDKs:
>     iOS SDK:
>       Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
>     Android SDK: Not Found
>   IDEs:
>     Android Studio: 3.0 AI-171.4443003
>     Xcode: 11.4/11E146 - /usr/bin/xcodebuild
>   Languages:
>     Python: 2.7.16 - /usr/bin/python
>   npmPackages:
>     @react-native-community/cli: Not Found
>     react: 16.11.0 => 16.11.0 
>     react-native: ^0.62.0 => 0.62.0 
>   npmGlobalPackages:
>     *react-native*: Not Found
> ```

have you solved this propblem now? And how to fix it?

**Comment by wem2017** [comment]
Hello! 
- I follow https://fbflipper.com/docs/troubleshooting/
Go to the tab Build Settings;
Search for LD_RUNPATH_SEARCH_PATHS (make sure that All is selected);
Double-click Runpath Search Paths and, in the dialog that opens, click on the plus button at the bottom-left corner and paste /usr/lib/swift 
$(inherited)
Now search for LIBRARY_SEARCH_PATHS;
Double-click Library Search Paths and, in the dialog that opens, add the following items:
"$(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME)"
"$(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)"
"$(inherited)"
but still library not found for -lCocoaAsyncSocket.
![Screen Shot 2020-07-19 at 09 30 50](https://user-images.githubusercontent.com/58833808/87865691-a5b1cf80-c9a2-11ea-95a2-fc0935c7907b.png)
![Screen Shot 2020-07-19 at 09 31 08](https://user-images.githubusercontent.com/58833808/87865695-ac404700-c9a2-11ea-8a19-cdb845d54859.png)
![Screen Shot 2020-07-19 at 09 31 24](https://user-images.githubusercontent.com/58833808/87865697-b06c6480-c9a2-11ea-9226-86290497d690.png)

**Comment by pulkitgulati** [comment]
I'm  getting this error "Library not found for -lRNAdMobManager" for the iOS version after installing React Native Firebase @react-native-firebase/app and @react-native-firebase/admob in React Native 0.62.2. Can anyone help please?
It's working fine in Android.

**Comment by Biplovkumar** [comment]
> I solved the issue by changing the build system from
> File-> Workspace Settings -> Build System -> "New Build System"

I Used this and also removed .ttf files which has came from link vector icons in copy bundle resources tab.

**Comment by Iman-Jamali** [comment]
> I faced the same issue and fixed it by open Xcode and change the `Library Search Paths` to
> <img alt="Screen Shot 2020-04-08 at 15 53 51" width="847" src="https://user-images.githubusercontent.com/988115/78764759-398dfb80-79b1-11ea-8e77-fe3d50795a1e.png">
> without the quote sign

This plus a `Clean Build Folder` worked for me. Thanks

**Comment by hegazi9** [comment]
> I faced the same issue and fixed it by open Xcode and change the `Library Search Paths` to
> <img alt="Screen Shot 2020-04-08 at 15 53 51" width="847" src="https://user-images.githubusercontent.com/988115/78764759-398dfb80-79b1-11ea-8e77-fe3d50795a1e.png">
> without the quote sign

how delete it :)

**Comment by MANTENN** [comment]
I checked the path and the file is there but its not being loaded for some reason with the same error:
```
ld: library not found for -lCocoaAsyncSocket
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

`ls` of that directory
```
CocoaAsyncSocket         RCTTypeSafety            React-cxxreact
DoubleConversion         React-Core               React-jsi
FBReactNativeSpec        React-CoreModules        React-jsiexecutor
Flipper                  React-RCTAnimation       React-jsinspector
Flipper-DoubleConversion React-RCTBlob            ReactCommon
Flipper-Folly            React-RCTImage           Yoga
Flipper-Glog             React-RCTLinking         YogaKit
Flipper-PeerTalk         React-RCTNetwork         glog
Flipper-RSocket          React-RCTSettings        libPods-myprojectname.a
FlipperKit               React-RCTText            myprojectname.app
Folly                    React-RCTVibration
➜  Debug-iphonesimulator 

```

**Comment by MANTENN** [comment]
> I checked the path and the file is there but its not being loaded for some reason with the same error:
> 
> ```
> ld: library not found for -lCocoaAsyncSocket
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> ```
> 
> `ls` of that directory
> 
> ```
> CocoaAsyncSocket         RCTTypeSafety            React-cxxreact
> DoubleConversion         React-Core               React-jsi
> FBReactNativeSpec        React-CoreModules        React-jsiexecutor
> Flipper                  React-RCTAnimation       React-jsinspector
> Flipper-DoubleConversion React-RCTBlob            ReactCommon
> Flipper-Folly            React-RCTImage           Yoga
> Flipper-Glog             React-RCTLinking         YogaKit
> Flipper-PeerTalk         React-RCTNetwork         glog
> Flipper-RSocket          React-RCTSettings        libPods-myprojectname.a
> FlipperKit               React-RCTText            myprojectname.app
> Folly                    React-RCTVibration
> ➜  Debug-iphonesimulator 
> ```
> 
> Also CocoaASync is the first library that is loaded and fails.

Make sure you do not copy the quotes. Bad IDE. 

I get a dif error now.

**Comment by sramezani** [comment]
I faced the same issue for `react-native-viewpager` and fixed it:

![Screenshot 2021-02-09 at 11 (1)](https://user-images.githubusercontent.com/33284430/107313269-236b3300-6acd-11eb-8ce5-f5ef5fa66e98.jpg)


You need to check `Library Search Paths` for package you faced issue. If you din't find in the list you need click on `+` button and add your package:
e.g.
```
${PODS_CONFIGURATION_BUILD_DIR}/react-native-viewpager
```

**Comment by zubko** [comment]
For my case, updating the Xcode project to recommended settings helped to fix the issue that libraries were not found for the Release build because for some reason the CocoaPods didn't compile before the main target.

These steps are mentioned here:
https://github.com/react-native-community/upgrade-support/issues/13

**Comment by aleBiriri** [comment]
In my case i did the following:
1. Remove quotes from Library Search Path ([like this](https://github.com/facebook/react-native/issues/28483#issuecomment-610839293))
2. Set New Build System ([like this](https://github.com/facebook/react-native/issues/28483#issuecomment-612840043))
3. Change Target version to 11.00 ([like this](https://github.com/facebook/react-native/issues/26106#issuecomment-743716220))

Environment setup:
React Native 0.64.0
XCode 12.04

**Comment by fachrighiffary** [comment]
> Any updates regarding this issue.I have same issue
> <img alt="Screen Shot 2020-04-07 at 4 03 28 PM" width="543" src="https://user-images.githubusercontent.com/8740519/78659559-5eb73700-78e9-11ea-8394-6e27c8e6f4ce.png">
> .

did you solve this problem?,, ive got this proble too

**Comment by abhikking** [comment]
> Any updates regarding this issue.I have same issue
> <img alt="Screen Shot 2020-04-07 at 4 03 28 PM" width="543" src="https://user-images.githubusercontent.com/8740519/78659559-5eb73700-78e9-11ea-8394-6e27c8e6f4ce.png">
> .

did you resolved your problem? I have the same issue

**Comment by elencho** [comment]
> For anyone here whose error string includes `directory not found for option '-L-L/Users/....` (particularly notice the `-L-L`).
> 
> The solution is to move `$(inherited)` to the bottom of your Library Search Paths: [react-native-community/upgrade-support#36 (comment)](https://github.com/react-native-community/upgrade-support/issues/36#issuecomment-611516268)
> 
> The reason this is happening is because the inherited ends up blank, so the compile command is inserting an extra blank argument before the first actual link argument, so `-L -L/Users/....` turns into `-L-L/Users/...` which fails.

Bro I don't know how to thanks, I spent 4 days working on it, Thank you very much

**Comment by rush86999** [comment]
Still having the same issue if anybody solves it.

**Comment by ilkerceng** [comment]
> I faced the same issue and fixed it by open Xcode and change the `Library Search Paths` to
> <img alt="Screen Shot 2020-04-08 at 15 53 51" width="847" src="https://user-images.githubusercontent.com/988115/78764759-398dfb80-79b1-11ea-8e77-fe3d50795a1e.png">
> without the quote sign

Also changing target version to 11 fixed. Thanks
