### ISSUE TITLE
React Native auto RTL text switch not work in IOS but true in android

### ISSUE THREAD

**Issue by mrengineer20** [facebook/react-native#28494]
I have problem in iOS Text, it is my output in android and iOS , but in iOS not true(don't support auto switch rtl in iOS). And i want to selectable Text.

![Screen Shot 2020-04-02 at 13 20 44](https://user-images.githubusercontent.com/7191226/78250766-9d25ae00-7505-11ea-9881-05f8eb740edc.png)

            
       import React from "react";
       import { View, Text, TextInput } from "react-native";
                
      export default function App() {
        var desc = 'English \r\n انگلیسی \r\n Persion \r\n فارسی \r\n Arabic \r\n العربی';
        return (
          <View style={{ padding: 20, paddingTop: 100 }}>
            <TextInput
              underlineColorAndroid="transparent"
              placeholder="Type something"
              placeholderTextColor="grey"
              numberOfLines={10}
              multiline={true}
              selectable={true}
              value={desc}
            />

            <Text selectable={true}>
              {desc}
            </Text>
          </View>
        );
      }

**React Native version:**
System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 139.79 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.1 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.3.1/11C505 - /usr/bin/xcodebuild
  Languages:
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.0 => 0.62.0 
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by Abdullah-Shamhan** [comment]
Did you manage to fix it?
