### ISSUE TITLE
[Android] Theme for Alert.alert dialog does not change upon dark mode

### ISSUE THREAD

**Issue by panda0603** [facebook/react-native#28502]
## Description
On IOS, when change to dark mode, alert dialog also changes to dark mode. 
However on Android, alert dialog still stays white when change to dark mode. 
I have tried on the latest version of android 10.

## React Native version:
0.61.5

## Steps To Reproduce
Call Alert.alert in android on dark mode. 

## Expected Results
Alert dialog color change to dark in dark mode.

**Comment by bitfabrikken** [comment]
Verified - Alert.alert is still bright white in dark mode on Android.
react-native: 0.63.0-rc.1

**Comment by tr3v3r** [comment]
The same here

**Comment by bitfabrikken** [comment]
@hramos

**Comment by SMJ93** [comment]
Hey,

We've just updated to 0.63.1 and the `Alert.alert` title and button text are not visible on Android if the device is in dark mode:

```
Alert.alert(
      "Alert Title",
      "My Alert Msg",
      [
        {
          text: "Cancel",
          onPress: () => console.log("Cancel Pressed"),
          style: "cancel"
        },
        { text: "OK", onPress: () => console.log("OK Pressed") }
      ],
      { cancelable: false }
    );
```

| Dark mode | Light mode |
|---|---|
| ![Screenshot_1595167045](https://user-images.githubusercontent.com/2145641/87876533-892c8c00-c9d0-11ea-8b21-ea99fa26a519.png) | ![Screenshot_1595167132](https://user-images.githubusercontent.com/2145641/87876538-96497b00-c9d0-11ea-9334-db7b540e1ded.png) |

This is using the example snippet from the [docs](https://reactnative.dev/docs/alert).

**Comment by ShivamJoker** [comment]
> <resources>
>     
>     <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
>         
>         <item name="android:windowIsTranslucent">true</item>
>         <item name="android:editTextBackground">@android:color/transparent</item>
>         <item name="android:textColor">#000000</item>
>         <item name="android:alertDialogTheme">@style/AlertDialogTheme</item>
>     </style>
>     <style name="AlertDialogTheme" parent="Base.Theme.AppCompat.Light.Dialog.Alert">
>         <item name="android:background">@color/alert_background</item>
>         <item name="android:textColor">@color/alert_text</item>
>         <item name="android:textColorPrimary">@color/alert_text</item>
>     </style>
> </resources>

Make it `xml` not `yml` and yeah it worked but React Native needs to implement this internally we shouldn't be doing this cause alert is the native component.

**Comment by ShivamJoker** [comment]
### @DmitriiMelnik and also it created this issue how do we fix it ?

<img src="https://user-images.githubusercontent.com/23727670/96713248-ebc16980-13bd-11eb-9ecb-d1f76f8d84e2.png" width="400"/>

**Comment by DmitriiMelnik** [comment]
> > <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
> >         
> >         true
> >         @android:color/transparent
> >         #000000
> >         @style/AlertDialogTheme
> >     </style>
> >     <style name="AlertDialogTheme" parent="Base.Theme.AppCompat.Light.Dialog.Alert">
> >         @color/alert_background
> >         @color/alert_text
> >         @color/alert_text
> >     </style>
> 
> Make it `xml` not `yml` and yeah it worked but React Native needs to implement this internally we shouldn't be doing this cause alert is the native component.

You are right, need to name the file `colors.xml`

**Comment by DmitriiMelnik** [comment]
> ### @DmitriiMelnik and also it created this issue how do we fix it ?
> <img alt="" width="400" src="https://user-images.githubusercontent.com/23727670/96713248-ebc16980-13bd-11eb-9ecb-d1f76f8d84e2.png">

I didn't notice this. I will research this issue a little later

**Comment by DmitriiMelnik** [comment]
@ShivamJoker 
You can change text color in debug menu with 
```
<item name="android:textColorAlertDialogListItem">@color/alert_text</item>
```
in AlertDialogTheme

**Comment by dprevost-LMI** [comment]
To have different colors for the title/body text vs the button we can use:
```
        <!-- Used for the title and body text -->
        <item name="android:textColorPrimary">@color/alert_text</item>
        <!-- Used for the buttons -->
        <item name="android:colorAccent">@color/alert_button_text</item>
```

but we need to remove:

```
<item name="android:textColor">@color/alert_text</item>
```

**Comment by ShivamJoker** [comment]
I am not sure what to do the alert box is not coming with white text

**Comment by pickle636** [comment]
> You can change colors just like in android create folder `values-night` in `android` -> `app` -> `src` -> `main` -> `res` create file `colors.yml` in `values-night` folder
> 
> file `values-night/colors.xml`
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> <resources>
>     <color name="alert_background">#393947</color>
>     <color name="alert_text">#ffffff</color>
> </resources>
> ```
> 
> file `values/colors.xml`
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> <resources>
>     <color name="alert_background">#ffffff</color>
>     <color name="alert_text">#0f2438</color>
> </resources>
> ```
> 
> file `values/styles.xml`
> 
> ```
> <resources>
>     
>     <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
>         
>         <item name="android:windowIsTranslucent">true</item>
>         <item name="android:editTextBackground">@android:color/transparent</item>
>         <item name="android:textColor">#000000</item>
>         <item name="android:alertDialogTheme">@style/AlertDialogTheme</item>
>     </style>
>     <style name="AlertDialogTheme" parent="Base.Theme.AppCompat.Light.Dialog.Alert">
>         <item name="android:background">@color/alert_background</item>
>         <item name="android:textColor">@color/alert_text</item>
>         <item name="android:textColorPrimary">@color/alert_text</item>
>     </style>
> </resources>
> ```

I did the same, but the problem is that the theme change is not happening on the fly. You need to reopen the dialog and only then it will open in the corresponding theme.
