### ISSUE TITLE
Inspect websocket traffic with Flipper

### ISSUE THREAD

**Issue by mdoesburg** [facebook/react-native#28518]
## Description
I am using [Flipper](https://fbflipper.com/) for debugging purposes, and opened an [issue](https://github.com/facebook/flipper/issues/960) on the Flipper repo, but I was told that this would be a question for the React Native team.

I am building a React Native app (RN 0.62.0) with AWS Amplify / AWS AppSync on macOS Catalina. When running the app in both an iOS and Android simulator I don't see the websocket that AWS Amplify opens. I can see the websocket when I use the Inspector in the simulator dev menu, but I don't see the websocket in the Network plugin on Flipper. I do see regular requests on Flipper like POST and GET requests.

Within AWS Amplify I use DataStore which uses the [@aws-amplify/pubsub](https://github.com/aws-amplify/amplify-js/tree/master/packages/pubsub) package for websockets I think. Is there anyway to make the websocket connection show up on Flipper?

## React Native version:
```
System:
    OS: macOS 10.15.2
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 132.64 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.5.0 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.3
      System Images: android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  Languages:
    Python: 3.7.4 - /usr/local/opt/python/libexec/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.0 => 0.62.0 
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Create a React Native project
2. Open a websocket
3. It won't show up in Flippers network plugin

## Expected Results
I expect to be able to see all network requests (websockets) on Flipper, and not only POST, GET, HEAD etc.

**Comment by fabriziobertoglio1987** [comment]
workaround https://hackernoon.com/intercept-https-traffic-on-a-android-emulator-46023f17f6b3
