### ISSUE TITLE
Application upgraded to 0.62 does not work

### ISSUE THREAD

**Issue by xldsdr124** [facebook/react-native#28527]
## Description
I ported my react-native application from 0.61.5 to 0.62.1. My application cannot be opened normally in the release version. This application can be run normally in dev mode. I cannot locate any of my error messages. Package dependent content:
`"dependencies": {
    "@react-native-community/masked-view": "^0.1.7",
    "@react-navigation/bottom-tabs": "^5.2.4",
    "@react-navigation/native": "^5.1.3",
    "@react-navigation/stack": "^5.2.8",
    "react": "16.11.0",
    "react-native": "0.62.1",
    "react-native-elements": "^1.2.7",
    "react-native-fast-image": "^8.1.5",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-htmlview": "^0.15.0",
    "react-native-picker-select": "^6.6.0",
    "react-native-reanimated": "^1.7.1",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-screens": "^2.4.0",
    "react-native-sound": "^0.11.0",
    "react-native-vector-icons": "^6.6.0"
  }`

## React Native version:
System:
    OS: Windows 10 10.0.19592
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 4.84 GB / 15.95 GB
  Binaries:
    Node: 12.16.1 - C:\Users\GM-PRO~1\AppData\Local\Temp\yarn--1586001173023-0.8437840897722515\node.CMD
    Yarn: 1.22.4 - C:\Users\GM-PRO~1\AppData\Local\Temp\yarn--1586001173023-0.8437840897722515\yarn.CMD
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Python: 3.8.2 - C:\Python38\python.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.1 => 0.62.1
  npmGlobalPackages:
    *react-native*: Not Found
## Steps To Reproduce
cd android && ./gradlew assembleRelease

**Comment by kamui545** [comment]
0.62.1 is broken, please see https://github.com/facebook/react-native/issues/28519

I would suggest using 0.62.0 for now or waiting for the next release

**Comment by xldsdr124** [comment]
> 0.62.1 is broken, please see #28519
> 
> I would suggest using 0.62.0 for now or waiting for the next release

**Comment by manjeets12** [comment]
https://stackoverflow.com/questions/61413837/react-native-0-62-0-getting-unable-to-find-a-matching-variant-of-project-reac/61414002?noredirect=1#comment108641879_61414002
