### ISSUE TITLE
Images are not respecting the width and height

### ISSUE THREAD

**Issue by marcosdourado** [facebook/react-native#28529]
## Description
Images are not respecting the width and height, the final size is the original and not the one defined in the properties.

## React Native version:
System:
    OS: Linux 5.5 Arch Linux undefined
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 1.51 GB / 15.35 GB
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.21.1 - ~/.nvm/versions/node/v10.16.0/bin/yarn
    npm: 6.13.6 - ~/.nvm/versions/node/v10.16.0/bin/npm
    Watchman: 4.9.0 - /usr/bin/watchman
  SDKs:
    Android SDK:
      API Levels: 24, 26, 28, 29
      Build Tools: 27.0.3, 28.0.3, 29.0.1, 29.0.2
      System Images: android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
  npmPackages:
    @react-native-community/cli: ^2.9.0 => 2.10.0 
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.0 => 0.62.0 
  npmGlobalPackages:
    react-native: 0.61.3

## Steps To Reproduce
1. npx react-native init newProject;
2. Add the image component, with a large image and try to define the width and height;
3. The defined width and height will not be respected.

## Expected Results
According to the [documentation](https://reactnative.dev/docs/image) and like the editable example in it, the expected result is this:
![image](https://user-images.githubusercontent.com/4989884/78458080-3202e580-7685-11ea-824c-e6de3fd17f6a.png)

However the result achieved, using the same code is this:
![Screenshot_1586022825](https://user-images.githubusercontent.com/4989884/78458109-552d9500-7685-11ea-96cd-3a215bfcfdb3.png)

The code used:
```js
import React from 'react';
import {Image, View, StyleSheet} from 'react-native';

import logo from './logo.png';

const styles = StyleSheet.create({
  container: {
    paddingTop: 50,
  },
  logo: {
    width: 66,
    height: 58,
  },
});

const App = () => {
  return (
    <View style={styles.container}>
      <Image source={logo} styles={styles.logo} />
    </View>
  );
};

export default App;
```

**Comment by chris9753** [comment]
What happens if you try "requiring" the image?
 i.e
```
<View style={styles.container}>
      <Image source={require('./logo.png')} styles={styles.logo} />
    </View>
```

**Comment by mydesweb** [comment]
@marcosdourado the problem is your code, instead of styles={styles.logo} use style={styles.logo} without (s)

**Comment by marcosdourado** [comment]
Thanks @mydesweb , it was a big vacuum on my part, it was drawn by an S, who never? Thank you very much.
