### ISSUE TITLE
[Android][Image] Loading images from the file system

### ISSUE THREAD

**Issue by arbesfeld** [facebook/react-native#2854]
The use of `GenericDraweeView` makes it difficult to use images from the SDCard. It would be great to have a plugin architecture similar to iOS where we can add new resource handlers.

**Comment by mkonicek** [comment]
Can you share code? Are you using file:// URLs with `<Image />`?

**Comment by mkonicek** [comment]
We have a Camera Roll module coming that will let you load images from the gallery, see:
https://facebook.github.io/react-native/docs/known-issues.html

**Comment by arbesfeld** [comment]
Hi @mkonicek, for our use case we'd like to be able to dynamically change the source image used during runtime. This is enabled on the iOS side via the pluggable "ImageLoader" system: https://github.com/facebook/react-native/commit/36444a65c700f4658d54a6be32bae700b228f6da

**Comment by mkonicek** [comment]
@arbesfeld Can you share some code to demo what you're doing in JS? That would help us understand this. I'm going on vacation tomorrow but will talk about it with the Fresco team next week.

**Comment by arbesfeld** [comment]
Hi @mkonicek,

We are downloading new images to a device and saving them to the file:///data/data/com.*/ folder like so:

```
File file = new File(getFilesDir(), "images");
FileOutputStream fout = new FileOutputStream(file);
fout.write(...);
```

It (usually) works to access them from JavaScript like so:

```
<Image source="file:///data/data/com.apphub.io/files/images/foo.png" />
```

But hard-coding this path doesn't always work, as `getFilesDir()` behaves differently from device to device.

An ideal solution would allow us to handle "file" URLs with our own Android handler.

Alternatively, it would be nice if could write paths like so:

```
<Image source="~/images/foo.png" />
```

Where the `~` would resolve to `getFilesDir()`.

**Comment by arunabha** [comment]
This would indeed be very useful, esp for displaying things like user profile images, once the user has logged in.

**Comment by mkonicek** [comment]
Thanks for the explanation! "~/images/foo.png" is interesting. How does iOS do this? Sorry for the delay :(

**Comment by mkonicek** [comment]
This PR might be interesting: https://github.com/facebook/react-native/pull/4527

**Comment by christopherdro** [comment]
Fixed via https://github.com/facebook/react-native/commit/0fb86c2495157038ded99fc22bfa1e19652989d6
