### ISSUE TITLE
Missing Typescript type for Appearance

### ISSUE THREAD

**Issue by martintreurnicht** [facebook/react-native#28548]
## Description
Type for import Appearance on Typescript is missing

## React Native version:
System:
    OS: macOS 10.15.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 11.97 GB / 32.00 GB
    Shell: 3.1.0 - /usr/local/bin/fish
  Binaries:
    Node: 13.11.0 - /var/folders/bd/k2ffsv5j2w15smsf94r39jqc0000gn/T/yarn--1586196714006-0.4378570942327491/node
    Yarn: 1.22.4 - /var/folders/bd/k2ffsv5j2w15smsf94r39jqc0000gn/T/yarn--1586196714006-0.4378570942327491/yarn
    npm: 6.13.7 - ~/.nvm/versions/node/v13.11.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 21, 23, 25, 26, 27, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-21 | Google APIs Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6308749
    Xcode: 11.4/11E146 - /usr/bin/xcodebuild
  Languages:
    Python: 2.7.17 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.0 => 0.62.0
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Try and import from typescript:
```typescript
import { Appearance } from 'react-native'
```

## Expected Results
To find type

**Comment by safaiyeh** [comment]
Hi @martintreurnicht I did a quick check of the types https://github.com/DefinitelyTyped/DefinitelyTyped/blob/cc2ea21db06ffacab61ea99a7b81ec9b866c95ae/types/react-native/index.d.ts#L8247

Seems like they are there. Could you verify your `@types/react-native`version?

**Comment by martintreurnicht** [comment]
@safaiyeh Ok, i didn't realize that the separate types is still supported. i figured after you guys started adding types directly to `react-native`, `@types/react-native` will become deprecated. Is the official stance from `react-native` to still use `@types/react-native`? And if so, why does `react-native` include their own types that is not kept in sync?

**Comment by martintreurnicht** [comment]
> @safaiyeh Ok, i didn't realize that the separate types is still supported. i figured after you guys started adding types directly to `react-native`, `@types/react-native` will become deprecated. Is the official stance from `react-native` to still use `@types/react-native`? And if so, why does `react-native` include their own types that is not kept in sync?

Ah never mind. I had a look in more detail and realized it's still coming from `@types/react-native` we were just not including it explicitly anymore, something else must be pulling it in. Thanks for the response!

**Comment by safaiyeh** [comment]
Glad I could help!
