### ISSUE TITLE
Template app uses XIB for launch screen, needs to be Storyboard (new App Store guidelines)

### ISSUE THREAD

**Issue by jonasb** [facebook/react-native#28560]
## Description

Received this from [Apple](https://developer.apple.com/news/?id=03262020b): "Apps for iPhone or iPad must be built with the iOS 13 SDK or later and **use an Xcode storyboard** to provide the app’s launch screen." (my emphasis)

Currently the template app uses [LaunchScreen.xib](https://github.com/facebook/react-native/blob/master/template/ios/HelloWorld/Base.lproj/LaunchScreen.xib).

My interpretation is that the XIB file needs to be changed to a Storyboard in order to be accepted by Apple's review.

## React Native version:
```
info Fetching system and libraries information...
System:
    OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
    Memory: 837.37 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
    Yarn: 1.17.0 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.4 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  Languages:
    Java: javac 12 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.1 => 0.62.1
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce

1. Create new app (`npx react-native init AwesomeProject`)
2. Check that it includes `LaunchScreen.xib` (`ls AwesomeProject/ios/AwesomeProject/Base.lproj/LaunchScreen.xib`)

## Expected Results
I expect the project to use a storyboard launch screen instead of a XIB. So that I can submit my app to the App Store and go through their review.

**Comment by jeswinsimon** [comment]
A PR is already in place for addressing this https://github.com/facebook/react-native/pull/28239

**Comment by KristineTrona** [comment]
When will version 63.0 be released? The new apple guidelines need to be implemented before July 1st, but the latest released react native version still contains .xib Launch screen
