### ISSUE TITLE
[Android][Native UI] Couldn't make self-implemented android native ui work.

### ISSUE THREAD

**Issue by rayshih** [facebook/react-native#2856]
I kind of go though the guide from the official document <https://facebook.github.io/react-native/docs/native-components-android.html#content>. But I couldn't make it work. Here is my source code:

(this is just a test so I didn't implement the `updateView` function

``` FloatingActionButtonManager.java
package com.awesomeproject;

import android.support.design.widget.FloatingActionButton;

import com.facebook.react.uimanager.SimpleViewManager;
import com.facebook.react.uimanager.ThemedReactContext;

public class FloatingActionButtonManager extends SimpleViewManager<FloatingActionButton> {
    @Override
    public String getName() {
        return "RCTFloatingActionButton";
    }

    @Override
    protected FloatingActionButton createViewInstance(ThemedReactContext themedReactContext) {
        return new FloatingActionButton(themedReactContext);
    }
}
```

``` MyReactPackage.java
package com.awesomeproject;

import com.facebook.react.ReactPackage;
import com.facebook.react.bridge.JavaScriptModule;
import com.facebook.react.bridge.NativeModule;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.uimanager.ViewManager;

import java.util.Collections;
import java.util.List;
import java.util.Arrays;

public class MyReactPackage implements ReactPackage {
    @Override
    public List<NativeModule> createNativeModules(ReactApplicationContext reactApplicationContext) {
        return Collections.emptyList();
    }

    @Override
    public List<Class<? extends JavaScriptModule>> createJSModules() {
        return Collections.emptyList();
    }

    @Override
    public List<ViewManager> createViewManagers(ReactApplicationContext reactApplicationContext) {
        return Arrays.asList(new ViewManager[]{new FloatingActionButtonManager()});
    }
}
```

``` FloatingActionButton.js
var {requireNativeComponent} = require('react-native');

var iface = {
  name: 'FloatingActionButton',
  propTypes: {},
};

module.exports = requireNativeComponent('RCTFloatingActionButton', iface);
```

And I encounter these errors:

```
Warning: Native component for "RCTModalHostView" does not exist
Warning: Native component for "RCTTextView" does not exist
Warning: Native component for "RCTTextField" does not exist
Warning: Native component for "RCTFloatingActionButton" does not exist
```

**Comment by mkonicek** [comment]
I assume you used `MyReactPackage` in your `MainActivity`?

You'll still need all the views and modules from the default package:
https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/shell/MainReactPackage.java

You can use [`CompositeReactPackage`](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/CompositeReactPackage.java) to create a package that combines both `MyPackage` and `MainReactPackage`: in your `MainActivity`, you can do:

    new CompositeReactPackage(new MainReactPackage(), new MyPackage())

Thanks for reporting the docs are not clear enough! Hope this helps and feel free to send a pull request for making the docs clearer or tell me which part you found unclear and I'll fix it.

**Comment by mkonicek** [comment]
Btw, good idea to expose the `FloatingActionButton`!

**Comment by rayshih** [comment]
Thanks for reply. But after I use `CompositeReactPackage` the errors stay the same.
I have tried clean & rebuild.

**Comment by ide** [comment]
Those messages are warnings, not errors. I don't think they are causing your issue (try loading a clean project and seeing if the warnings are still there).

**Comment by rayshih** [comment]
This is a clean project actually.

**Comment by Wingie** [comment]
i'm also facing an issue while trying to develop a native UI component.
have reported it here@ [stackoverflow](http://stackoverflow.com/questions/32670494/react-native-android-error-while-trying-to-write-custom-ui-component-for-viewp)

**Comment by andreaskeller** [comment]
@rayshih I had the same problem and after a while I found out that the UIManagerModule doesn't export view managers with no properties https://github.com/facebook/react-native/blob/42eb5464fd8a65ed84b799de5d4dc225349449be/ReactAndroid/src/main/java/com/facebook/react/uimanager/UIManagerModuleConstantsHelper.java#L67-L77. Adding a property solved it for me.

**Comment by corbt** [comment]
Can confirm @andreaskeller -- RN wasn't recognizing my custom component, and adding a prop to the view manager caused everything to work as expected.

**Comment by ide** [comment]
cc @mkonicek @kmagiera see @andrewskeller's comment about components without props.

**Comment by kmagiera** [comment]
I'm landing large changes to the ViewManager API, will verify that component with no props get properly registered

**Comment by gs-akhan** [comment]
@rayshih Are all these files siblings to MainActivity.java file under com>project ??

Thanks

**Comment by gs-akhan** [comment]
@mkonicek 
Hi, I had hard time getting my first Native module to work. The missing pieces in the docs were these. I have added a PR though. Thanks..
https://github.com/facebook/react-native/pull/3078

**Comment by yanni858** [comment]
I'm also having a hard time adding a native Android component, even though I'm getting closer thanks to this thread.  
If there were just one complete working example checked in somewhere it would help tremendously. Ideally it would be something extremely simple, say exposing the native RadioButton to JS.

**Comment by kmagiera** [comment]
Hey. Landed this https://github.com/facebook/react-native/commit/5623c831b3a938e234df18dd5b4c82c4ddf2f2c7 couple of days ago, can you verify whether the issue still persists on master?

**Comment by rayshih** [comment]
Thanks. I'll check that today.

**Comment by zenlambda** [comment]
@kmagiera I'm still finding it necessary to use a dummy property on react-native 0.12.0.

@rayshih I was actually trying to do the same thing as you. This is my code, perhaps it will help you. I am still not happy about the button icon size, it is still too small. The material ui guide gives specific [measurements](https://www.google.com/design/spec/components/buttons-floating-action-button.html#buttons-floating-action-button-floating-action-button) (in dp) but I'm still confused on the relationship with react units (px?).

<b>Component:</b>

```java
import android.support.design.widget.FloatingActionButton;
import android.support.v4.content.ContextCompat;
import android.widget.ImageView;
import com.facebook.react.common.ReactConstants;
import com.facebook.react.uimanager.SimpleViewManager;
import com.facebook.react.uimanager.UIProp;
import com.facebook.react.uimanager.CatalystStylesDiffMap;
import com.facebook.react.views.image.ImageResizeMode;
import com.facebook.react.uimanager.ThemedReactContext;
import com.facebook.react.uimanager.ViewProps;
import javax.annotation.Nullable;

public class FloatingActionButtonManager extends SimpleViewManager<FloatingActionButton> {

    @UIProp(UIProp.Type.STRING)
    public static final String PROP_TEXT_INPUT_TEXT = "text"; // dummy prop

    public static final String REACT_CLASS = "MyFloatingActionButton";

    private final @Nullable Object mCallerContext;

    public FloatingActionButtonManager(
        Object callerContext) {
        mCallerContext = callerContext;
    }

    public FloatingActionButtonManager() {
        mCallerContext = null;
    }

    @Override
    public String getName() {
        return REACT_CLASS;
    }

    @Override
    public FloatingActionButton createViewInstance(ThemedReactContext context) {
        return new FloatingActionButton(context);
    }

    @Override
    public void updateView(final FloatingActionButton view,
            final CatalystStylesDiffMap props) {
        view.setImageDrawable(
            ContextCompat.getDrawable(view.getContext(), R.drawable.ic_add));
        view.setImageTintList(
            ContextCompat.getColorStateList(view.getContext(), android.R.color.white));
        view.setScaleType(ImageView.ScaleType.CENTER);
        super.updateView(view, props);
    }

}
```

Package:
```java
class FabReactPackage implements ReactPackage {

    @Override
    public List<NativeModule> createNativeModules(
        ReactApplicationContext reactContext) {

        List<NativeModule> modules = new ArrayList<>();

        modules.add(new ToastModule(reactContext));

        return modules;
    }

    @Override
    public List<ViewManager> createViewManagers(
            ReactApplicationContext reactContext) {
        return Arrays.<ViewManager>asList(
            new ReactImageManager(),
            new FloatingActionButtonManager()
        );
    }

    @Override
    public List<Class<? extends JavaScriptModule>> createJSModules() {
      return Collections.emptyList();
    }
}
```

<b>Main Activity:</b>
```java
public class MainActivity extends Activity implements DefaultHardwareBackBtnHandler {

    private ReactInstanceManager mReactInstanceManager;
    private ReactRootView mReactRootView;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        mReactRootView = new ReactRootView(this);
        Log.i("React", "Hello World");
        mReactInstanceManager = ReactInstanceManager.builder()
                .setApplication(getApplication())
                .setBundleAssetName("index.android.bundle")
                .setJSMainModuleName("index.android")
                .addPackage(new MainReactPackage())
                .addPackage(new FabReactPackage()) // <--- add fab package here
                .setUseDeveloperSupport(BuildConfig.DEBUG)
                .setInitialLifecycleState(LifecycleState.RESUMED)
                .build();

        mReactRootView.startReactApplication(mReactInstanceManager, "FabApp", null);

        setContentView(mReactRootView);
    }

// the rest of your activity methods

```

<b>JS component module</b>
```javascript
var { PropTypes, requireNativeComponent } = require('react-native');

var iface = {
    name: 'MyFloatingActionButton',
    propTypes: {
        text: PropTypes.string
    }
}

module.exports = requireNativeComponent('MyFloatingActionButton', iface);
```
<b> Usage </b>
```jsx
var FloatingActionButton = require('./components/FloatingActionButton');

renderFloatingButton() {
  return (
    <FloatingActionButton
      style={
        {
          position: 'absolute', bottom: 25, right: 25,
          width:56, height:56
        }
      }
      text="foo"/>
  );
},
```

**Comment by rayshih** [comment]
wow thx for the code snippet.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/androidnative-ui-couldnt-make-self-implemented-android-native-ui-work

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.
