### ISSUE TITLE
Screen is freezing issue after closing Modal by Swipe down

### ISSUE THREAD

**Issue by mowais-ac** [facebook/react-native#28567]
## Description
I am having an issue in React Native, I have a screen where I have a to-do list along with search bar, on click on any todo item It opens a Modal where It has close button and content.

On closing the Modal by pressing a close button, It's working fine but, when I am doing swipe down my screen is freezing, I am unable to scroll and tab on todo list item also unable to press the search bar to type.

also, on swipe down popup is closing but it's not triggering `onRequestClose` and `onDismiss`

## React Native version:
```
npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5 
npmGlobalPackages:
    react-native-cli: 2.0.1
```
**Modal code**
```
creditCardsModalVisibleHandler = (visible) => {
    this.setState({creditCardsModalVisible: visible});
}

<Modal
    animationType="slide"
    transparent={false}
    visible={creditCardsModalVisible}
    presentationStyle="formSheet"
    onDismiss={() => {
        console.log('Close handled');
        this.creditCardsModalSwipeHandler();
    }}
    onRequestClose={() => {
        console.log('Modal has been closed');
        this.creditCardsModalSwipeHandler();
    }}
>
    <View style={[modal.main]}>
        <TouchableOpacity onPress={() => {this.creditCardsModalVisibleHandler(!creditCardsModalVisible);}}>
            <View style={[modal.closeButton]}>
                <ImageBackground source={modal.closeBackgroundImage} style={[modal.closeButtonImage]}/>
            </View>
        </TouchableOpacity>
    </View>
</Modal>
```
Steps
![bou-app-modal-issue](https://user-images.githubusercontent.com/33151104/78873388-d86f3200-7a5b-11ea-9e40-c2b153971181.gif)

Thank you

**Comment by kurniawanw0194** [comment]
It happens to me as well.

**Comment by mowais-ac** [comment]
This issue not resolved but I have fixed this by changing my modal `presentationStyle` from `formSheet` to `fullscreen`
```
<Modal
    animationType="slide"
    transparent={false}
    visible={creditCardsModalVisible}
    presentationStyle="fullScreen"
>
```
