### ISSUE TITLE
Building project with custom ReactAdroid failed

### ISSUE THREAD

**Issue by kyle-belle** [facebook/react-native#28561]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
I made some changes to a react native core component and am now trying to build that so i can use it. I removed the default pre-built library from the gradle file i.e `"implementation "com.facebook.react:react-native:+"  // From node_modules` and replaced it with `implementation project(':ReactAndroid')`. i also set up the `ndk.dir` in local.properties to point to the one i downloaded from the link in the wiki pages.

## React Native version:
System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
    Memory: 602.00 MB / 7.89 GB
  Binaries:
    Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.15.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    Android Studio: Version  3.4.0.0 AI-183.5429.30.34.5452501
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Stop using default prebuilt library `"implementation "com.facebook.react:react-native:+"  // From node_modules`  and use `implementation project(':ReactAndroid')` instead
2. also be sure to add the ndk.dir and add the ReactAndroid project in settings.gradle.
3. Attempt to build

## Expected Results
Expect a successful build

## What I Got

`C:/Users/kyleb/AppData/Local/Android/Ndk/android-ndk-r17c-windows-x86_64/android-ndk-r17c/build//../toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld: error: cannot open C:/Users/kyleb/AppData/Local/Android/Ndk/android-ndk-r17c-windows-x86_64/android-ndk-r17c/build//../toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/lib/../lib/armv7-a/libatomic.a: No such file or directory
C:/Users/kyleb/AppData/Local/Android/Ndk/android-ndk-r17c-windows-x86_64/android-ndk-r17c/build//../toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld: error: cannot open C:/Users/kyleb/AppData/Local/Android/Ndk/android-ndk-r17c-windows-x86_64/android-ndk-r17c/build//../toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/lib/../lib/armv7-a/libatomic.a: No such file or directory
clang++.exe: clang++.exeerror: : linker command failed with exit code 1 (use -v to see invocation)
error: linker command failed with exit code 1 (use -v to see invocation)
C:/Users/kyleb/AppData/Local/Android/Ndk/android-ndk-r17c-windows-x86_64/android-ndk-r17c/build//../toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld: error: cannot open C:/Users/kyleb/AppData/Local/Android/Ndk/android-ndk-r17c-windows-x86_64/android-ndk-r17c/build//../toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/lib/../lib/armv7-a/libatomic.a: No such file or directory
clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [C:\Users\kyleb\Documents\trp\node_modules\react-native\ReactAndroid/local/armeabi-v7a/libglog.so] Error 1   make: *** Waiting for unfinished jobs....
make: *** [C:\Users\kyleb\Documents\trp\node_modules\react-native\ReactAndroid/local/armeabi-v7a/libjsinspector.so] Error 1
make: *** [C:\Users\kyleb\Documents\trp\node_modules\react-native\ReactAndroid/local/armeabi-v7a/libfb.so] Error 1     
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':ReactAndroid:buildReactNdkLib'.
> Process 'command 'C:\Users\kyleb\AppData\Local\Android\Ndk\android-ndk-r17c-windows-x86_64\android-ndk-r17c\ndk-build.cmd'' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4m 18s`

**Comment by fabriziobertoglio1987** [comment]
```
cannot open C:/Users/kyleb/AppData/Local/Android/Ndk/android-ndk-r17c-windows-x86_64/android-ndk-r17c/build//../toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/lib/../lib/armv7-a/libatomic.a: No such file or directory
```

**Comment by fabriziobertoglio1987** [comment]
I had the same issue on linux, my `ndk-build` command would finish with non-zero exit value 2.

you can troubleshoot this by running  `C:\Users\kyleb\AppData\Local\Android\Ndk\android-ndk-r17c-windows-x86_64\android-ndk-r17c\ndk-build.cmd` in your terminal

It will show the complete error message from that command.

My error when running that command was

```
Android NDK: Could not find platform files (headers and libraries)
```

I solved this by installing the `ndk` with `android studio sdk manager` then setting correct env variables

```
export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
export PATH=$PATH:$JAVA_HOME/bin
export ANDROID_HOME=$HOME/Android/Sdk
export ANDROID_SDK=$HOME/Android/Sdk
export ANDROID_NDK=$ANDROID_SDK/ndk/17.2.4988734
```
