### ISSUE TITLE
Alarm - Reminders

### ISSUE THREAD

**Issue by genexasif** [facebook/react-native#28570]
Is there any alarm manager class available in react native repository? So we can use it for create alarms or reminders in our app.
We want to implement repeat reminders feature in our app for android & ios as well. Where user can select days from week & times for their reminders. Like pill reminder type functionality.
Can you please suggest us any library or officially documentation.

**Comment by genexasif** [comment]
> react-native info
  Binaries:
    Node: 13.7.0 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.7 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-firebase: 5.5.6

**Comment by safaiyeh** [comment]
Hi @genexasif React Native core does not.

I did a quick search for you to see community packages available to help you out.

Alarm specific:
https://github.com/emekalites/react-native-alarm-notification

Notifications:
https://github.com/wix/react-native-notifications
https://docs.expo.io/versions/latest/guides/push-notifications/
https://github.com/react-native-community/push-notification-ios + https://github.com/react-native-community/push-notification-android
