### ISSUE TITLE
Animated value resets when component is rendered in background app

### ISSUE THREAD

**Issue by kabbi** [facebook/react-native#28574]
## Description
Animated value resets to zero when app is rendered in the background. This was specifically noticed with `Share` popup on android: we have animated bottom sheets, and they go crazy in the background.

Also reproduced in the latest expo version (v37.0.0)
Originally reproduced on 0.59, still exists on 0.62.2

## React Native version:
```
System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Memory: 594.21 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 13.5.0 - ~/.nvm/versions/node/v13.5.0/bin/node
    Yarn: 1.21.1 - ~/.nvm/versions/node/v13.5.0/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v13.5.0/bin/npm
    Watchman: 4.7.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.4 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28
      Build Tools: 23.0.1, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.1, 27.0.3, 28.0.3
      System Images: android-28 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_131 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
The following conditions must be met (this is easier to encounter them all than it seems):

1. there is any animated value
2. it was at least once animated with `useNativeDriver: true`
3. app is in the background on android (in demo using `Share` popup)
4. component is rendered

- animated value resets to zero (at least visually, listeners don't seem to trigger with zero values)
- animated value is restored when app is in foreground again 

## Expected Results
Expected animated value to stay the same.

## Snack, code example, screenshot, or link to a repository:
https://snack.expo.io/MON0mcGPk
![ezgif-4-257a4fbccfc8](https://user-images.githubusercontent.com/1160550/78916022-84813f00-7a95-11ea-97e8-5d271fb2302f.gif)

**Comment by kabbi** [comment]
Still reproduced on the latest 0.62.2

**Comment by mnsrv** [comment]
+1, why Animated Value resets?

**Comment by sunnylqm** [comment]
Please reopen

**Comment by Guuz** [comment]
Can this issue be reopend? i'm having this too.. No clue how to fix it :(
My usecase is the biometric prompt on android as an overlay/bottom sheet over the app. Resetting all animations.
