### ISSUE TITLE
Provide a way to style the overflow icon in ToolbarAndroid

### ISSUE THREAD

**Issue by saidimu** [facebook/react-native#2858]
Currently the overflow icon in `<ToolbarAndroid>` (three vertical dots) is always black with no way to style it. A hack around it is to provide a [custom View](https://github.com/facebook/react-native/blob/master/Examples%2FUIExplorer%2FToolbarAndroidExample.android.js#L59) or to [omit actions](https://github.com/facebook/react-native/blob/master/Examples%2FUIExplorer%2FToolbarAndroidExample.android.js#L84) altogether as shown in the examples.

In both cases one would have to implement the floating menu that appears when the overflow icon is clicked.

**Comment by andreicoman11** [comment]
cc @foghina

**Comment by foghina** [comment]
We'd love a PR for this. You just need to add a prop in `ToolbarAndroid.android.js` and handle it in `ReactToolbarManager.java` to call [setOverflowIcon].

[setOverflowIcon]: https://developer.android.com/reference/android/support/v7/widget/Toolbar.html#setOverflowIcon(android.graphics.drawable.Drawable)

**Comment by abasak** [comment]
One option is to use the native styling feature provided by android. The icon color can be changed by adding the following line to the `android/app/src/main/res/values/styles.xml` file.

`<item name="android:textColorSecondary">@android:color/white</item>`

Source: http://stackoverflow.com/a/31139160
