### ISSUE TITLE
[0.61.5] FlatList `onEndReachedThreshold` not working with `horizontal` prop

### ISSUE THREAD

**Issue by dkoprowski** [facebook/react-native#28587]
FlatList `onEndReachedThreshold` not working with `horizontal={true}` prop.

## Description
Scrolling through *horizontal* FlatList to the right is ignoring `onEndReachedThreshold={0.5}` prop. `onEndReached` callback is executed when end is really reached so it is really poor experience for our users. Then need to go to the very end of list and then wait for load another page - it breaks "infinite scroll" feeling of the list.

## React Native version:
```
System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 654.07 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.19.0 - /usr/local/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.13.7 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```
## Steps To Reproduce

1. Create component with FlatList for example:
```jsx
    <FlatList
      data={auctions}
      renderItem={renderListItem}
      horizontal
      onEndReachedThreshold={0.5}
      onEndReached={handleLoadMore}
    />
```
2. Setup log to `handleLoadMore` to see when it is called
3. Scroll to the right
4. Observe that `handleLoadMore` is called after right edge of the elements is reached instead after passing half of the list

## Expected Results
Horizontal <FlatList /> should behave the same way as vertical one. It should respect `onEndReachedThreshold` prop.

**Comment by rashtell** [comment]
I am having the same issue but with vertical scrolling.
"react": "16.13.1",
"react-native": "0.63.1"
 
onEndReached only gets called at the end of the list irrespective of onEndReachedThreshold value.

**Comment by take-o20** [comment]
This issue was happened me.
"react": "16.13.1"
"react-native": "0.62.2"

However, it was not the right way to use it in the first place.
"onEndReachedThreshold" and "onEndReached" should be used with style's "height".
`<FlatList
      data={auctions}
      renderItem={renderListItem}
      horizontal
      onEndReachedThreshold={0.5}
      onEndReached={handleLoadMore}
      style={{height: '100%'}}   // this
/>`
I was so concerned about infinite scrolling that I completely lost sight of this possibility.

And I found that this can be used with <ScrollView> like....
`<ScrollView nestedScrollEnabled={true}>  //Don't forget nestedScrollEnabled={true} in Android
    <FlatList
         nestedScrollEnabled={true}
         style={{height: '100%'}} 
         ..........
         ......
    />
  <ScrollView />
`

**Comment by crushy26** [comment]
+1 @rashtell  @dkoprowski were you people able to fix this?
