### ISSUE TITLE
[UIImage animatedImageFrameCount]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by damoncoo** [facebook/react-native#28586]
## Description
Add Image to React Native page, Images can't be shown correctly.It crashes

## React Native version:
Run `react-native info` in your terminal and copy the results here.
System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 388.16 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.15.0 - ~/.nvm/versions/node/v11.15.0/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v11.15.0/bin/yarn
    npm: 6.7.0 - ~/.nvm/versions/node/v11.15.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 20, 21, 22, 23, 24, 25, 26, 27, 28
      Build Tools: 28.0.3
      System Images: android-28 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_112 - /Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/bin/javac
    Python: 2.7.16 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11 => 16.11.0
    react-native: 0.62 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Every time show RN page with images

## Expected Results
Describe what you expected to happen.

## Snack, code example, screenshot, or link to a repository:
       <Image
          source={require("../img/warning-circle.png")}
          style={{
            width: 10,
            height: 10,
            backgroundColor: "#f00",
          }}
        ></Image>

**Comment by hramos** [comment]
Thanks for the code sample. The repro case is incomplete, however, as it refers to image asset. How is your project structured? You could use a Snack to reproduce this.

**Comment by NathanOu** [comment]
Same issue here

**Comment by damoncoo** [comment]
I think I know why it crashed. I have a third party lib that has extension of UIImage which is animatedImageFrameAtIndex:. I do find this code  below in RCTUIImageViewAnimated.

![1587370823885](https://user-images.githubusercontent.com/4880373/79730081-e9088d80-8322-11ea-8570-46c65a4c0c9a.jpg)
