### ISSUE TITLE
[0.62.2] Using base64 strings for an Image URI crashes app

### ISSUE THREAD

**Issue by RnbWd** [facebook/react-native#28583]
## Description
I'm using base64 strings as image sources throughout my app. After upgrading react-native from 0.61.5 to 0.62.2, my app crashes immediately upon loading any image with the source as `{"uri": 'base64encodedstring'}`. There are no logs prior to the app crashing.  My app uses `data:image/jpeg;base64` encoded strings.

## React Native version:
System:
    OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
    Memory: 101.43 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.11.0 - ~/.nvm/versions/node/v13.11.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.7 - ~/.nvm/versions/node/v13.11.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.4 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 27, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-26 | Google APIs Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.4/11E146 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_232 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Use `{"uri": 'base64encodedstring'}` as an Image source inside of a component

## Expected Results
Image loads properly

**Comment by myckhel** [comment]
Same issue here with rn v62.2

**Comment by guhungry** [comment]
version 0.62.1 also affected

**Comment by RnbWd** [comment]
I've tested this issue on iOS

**Comment by daniel-sudz** [comment]
Same issue on ios @latest react-native

**Comment by weslei-dias-vakt** [comment]
@daniel-sudz you are a hero. Thank you.

**Comment by empitechathu** [comment]
@daniel-sudz shut the front door ... you are a life savior

**Comment by Shariaty** [comment]
@daniel-sudz You saved my life. TNX man.

**Comment by justcodejs** [comment]
I am using React Native 62.2 and changing versions['Flipper'] ||= '~> 0.37.0' solved my problem too. :)

JustCode
https://justnice.net/wp/blog/

**Comment by Ding95** [comment]
> Edit:
> For anyone else that comes across this just change the version of Flipper in the podfile to
> 
> ```
>   versions['Flipper'] ||= '~> 0.37.0'
> ```
> 
> as this is what the pr did

You perhaps should change the version of Flipper-Folly
```
versions['Flipper-Folly'] ||= '~> 2.2'
```

**Comment by soroushm** [comment]
update flipper Not working for me
```
  versions['Flipper'] ||= '~> 0.37.0'
  versions['DoubleConversion'] ||= '1.1.7'
  versions['Flipper-Folly'] ||= '~> 2.2'
  versions['Flipper-Glog'] ||= '0.3.6'
  versions['Flipper-PeerTalk'] ||= '~> 0.0.4'
  versions['Flipper-RSocket'] ||= '~> 1.1'
```

**Comment by riteshapatel** [comment]
Along with the flipper update I also had to update,

```
  versions['Flipper-Folly'] ||= '~> 2.2'
  versions['Flipper-RSocket'] ||= '~> 1.1'
```

After updating versions in the pod file run

```
pod install --repo-update
```

Cheers!

**Comment by ganes1410** [comment]
I can also confirm the updating the version fixes this issue.

**Comment by tushar-inno** [comment]
Thanks for the solution @daniel-sudz and @riteshpatel

**Comment by ismail2009** [comment]
@daniel-sudz Thanks a lot

**Comment by alanyong91** [comment]
> Edit:
> For anyone else that comes across this just change the version of Flipper in the podfile to
> 
> ```
>   versions['Flipper'] ||= '~> 0.37.0'
> ```
> 
> as this is what the pr did

the real contributor !

**Comment by patelgaurav4u** [comment]
> Edit:
> For anyone else that comes across this just change the version of Flipper in the podfile to
> 
> ```
>   versions['Flipper'] ||= '~> 0.37.0'
> ```
> 
> as this is what the pr did

working fine with this changes

**Comment by pavermakov** [comment]
I get the following error when I try to upgrade flipper
![Снимок экрана 2020-08-06 в 13 07 21](https://user-images.githubusercontent.com/10779996/89519916-c8871500-d7e5-11ea-85d3-84bb0b5f1ca5.png)

**Comment by kkkasio** [comment]
> Edit:
> For anyone else that comes across this just change the version of Flipper in the podfile to
> 
> ```
>   versions['Flipper'] ||= '~> 0.37.0'
> ```
> 
> as this is what the pr did

I had the same problem here!
its worked for me <3

**Comment by safaiyeh** [comment]
> Along with the flipper update I also had to update,
> 
> ```
>   versions['Flipper-Folly'] ||= '~> 2.2'
>   versions['Flipper-RSocket'] ||= '~> 1.1'
> ```
> 
> After updating versions in the pod file run
> 
> ```
> cd ios && pod install --repo-update && cd ..
> ```
> 
> Cheers!

Closing as we have a fix, thanks everyone

**Comment by amirulasrof** [comment]
> I get the following error when I try to upgrade flipper
> ![Снимок экрана 2020-08-06 в 13 07 21](https://user-images.githubusercontent.com/10779996/89519916-c8871500-d7e5-11ea-85d3-84bb0b5f1ca5.png)

Happen to me as well, when run pod install
