### ISSUE TITLE
App termination due to [NSURLResponse allHeaderFields]:  unrecognized selector sent to instance

### ISSUE THREAD

**Issue by kennetpostigo** [facebook/react-native#28589]
## Description
My app basically crashes after reaching 100% from the code being bundled. 
So far what I have done is:
- Go thru the [upgrade tool](https://react-native-community.github.io/upgrade-helper/?from=0.61.5&to=0.62.2) to upgrade from `0.61.5` -> `0.62.2`
- Follow the xcode upgrade instructions here:  https://github.com/react-native-community/upgrade-support/issues/13

If anyone has any idea why I get this issue below, so far I have followed linked issues point to logbox/flipper image issue. There are no useful instructions or hints on how to fix this issue and/or the issue has been closed. I've spent hours trying to figure this issue out 🥺

I'd be super glad if anyone can point me in the right direction to get this figured out:
```
Terminating app due to uncaught exception 'NSInvalidArgumentException', 
reason: '-[NSURLResponse allHeaderFields]: 
unrecognized selector sent to instance 0x6000002756e0'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23e3dcce __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff50b3b9b2 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23e5e9f4 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff23e426cc ___forwarding___ + 1436
	4   CoreFoundation                      0x00007fff23e449b8 _CF_forwarding_prep_0 + 120
	5   yotie                               0x00000001091de02c +[SKResponseInfo shouldStripReponseBodyWithResponse:] + 76
	6   yotie                               0x00000001091ddf01 -[SKResponseInfo initWithIndentifier:timestamp:response:data:] + 241
	7   yotie                               0x00000001091b7cd9 __71-[FLEXNetworkRecorder recordLoadingFinishedWithRequestID:responseBody:]_block_invoke + 825
	8   libdispatch.dylib                   0x000000010cf6ff11 _dispatch_call_block_and_release + 12
	9   libdispatch.dylib                   0x000000010cf70e8e _dispatch_client_callout + 8
	10  libdispatch.dylib                   0x000000010cf776fd _dispatch_lane_serial_drain + 788
	11  libdispatch.dylib                   0x000000010cf7828f _dispatch_lane_invoke + 422
	12  libdispatch.dylib                   0x000000010cf83b65 _dispatch_workloop_worker_thread + 719
	13  libsystem_pthread.dylib             0x00007fff51b9ea3d _pthread_wqthread + 290
	14  libsystem_pthread.dylib             0x00007fff51b9db77 start_wqthread + 15
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 
```

## React Native version:
0.62.2

## Steps To Reproduce
- Go thru the [upgrade tool](https://react-native-community.github.io/upgrade-helper/?from=0.61.5&to=0.62.2) to upgrade from `0.61.5` -> `0.62.2`
- Follow the xcode upgrade instructions here:  https://github.com/react-native-community/upgrade-support/issues/13

## Expected Results
App to open up and run properly

**Comment by guhungry** [comment]
@kennetpostigo is it because of base64 image as https://github.com/facebook/react-native/issues/28583?

**Comment by kennetpostigo** [comment]
@guhungry  I don't even think i'm using a base64 image anywhere

**Comment by ivanmoskalev** [comment]
Can this be related to #28454?

**Comment by kennetpostigo** [comment]
Updating flipper to at least 37 fixed this

**Comment by tushar-inno** [comment]
Using this post I fixed this issue: https://github.com/facebook/react-native/issues/28583#issuecomment-614239427 and https://github.com/facebook/react-native/issues/28583#issuecomment-630519103

**Comment by azhararmar** [comment]
@tushar-inno it worked for me as well on RN 0.62.2, thank you.
