### ISSUE TITLE
facebook ip  address 69.171.242.30 (840)?

### ISSUE THREAD

**Issue by hejun041** [facebook/react-native#28582]
## Description
When my app is uploaded to the app marketplace, it prompts me to include facebook's IP access.
So,what's the use of accessing this IP address?

## React Native version:
"react": "16.8.6",
"react-native": "0.60.5"

**Comment by hramos** [comment]
Are you using the Facebook SDK?

**Comment by hejun041** [comment]
`implementation project(':react-native-svg')
    implementation project(':react-native-linear-gradient')
    implementation project(':lottie-react-native')
    implementation project(':react-native-fast-image')
    implementation project(':react-native-gesture-handler')
    implementation 'androidx.appcompat:appcompat:1.0.2'
    implementation 'com.facebook.react:react-native:+'
    implementation project(':react-native-picker')
    implementation project(':react-native-code-push')
    implementation 'com.facebook.fresco:animated-gif:1.13.0'
    implementation project(':jpush-react-native')
    implementation project(':jcore-react-native')
    implementation project(':react-native-webview')
    implementation project(':@react-native-community_netinfo')`

`"dependencies": {
    "@react-native-community/netinfo": "^4.1.3",
    "control.monads": "^0.6.0",
    "crypto-js": "^3.1.9-1",
    "deprecated-react-native-listview": "0.0.5",
    "han": "0.0.7",
    "hermes-engine": "^0.1.0",
    "immutable": "3.7.6",
    "jcore-react-native": "^1.2.5",
    "jpush-react-native": "^2.2.2",
    "lottie-ios": "^3.0.3",
    "lottie-react-native": "^3.3.2",
    "mathjs": "^3.4.1",
    "mobx": "^4.2.0",
    "mobx-react": "^5.0.0",
    "moment": "^2.24.0",
    "object-assign": "4.0.1",
    "react": "16.8.6",
    "react-addons-pure-render-mixin": "^15.6.2",
    "react-native": "0.60.5",
    "react-native-barcodescanner": "^3.1.1",
    "react-native-code-push": "^5.6.1",
    "react-native-communications": "0.1.0",
    "react-native-deprecated-custom-components": "^0.1.2",
    "react-native-fast-image": "^7.0.2",
    "react-native-gesture-handler": "^1.1.0",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-masonry-list": "^2.10.4",
    "react-native-root-toast": "^3.1.1",
    "react-native-scrollable-tab-view": "^0.10.0",
    "react-native-snap-carousel": "^3.8.0",
    "react-native-svg": "^11.0.1",
    "react-native-swipeout": "^2.0.12",
    "react-native-vector-icons": "^4.6.0",
    "react-native-viewpager": "^0.2.11",
    "react-native-webview": "^5.12.1",
    "react-native-xtabbar": "^0.2.1",
    "react-navigation": "^3.11.1",
    "react-navigation-props-mapper": "^1.0.1",
    "react-static-container": "^1.0.1",
    "react-timer-mixin": "^0.13.3",
    "uuid-js": "0.7.5"
  },
  "devDependencies": {
    "@babel/core": "^7.5.0",
    "@babel/plugin-proposal-decorators": "^7.3.0",
    "@babel/plugin-transform-runtime": "7.3.4",
    "@babel/runtime": "^7.5.0",
    "babel-jest": "^24.1.0",
    "jest": "^24.1.0",
    "jetifier": "^1.6.3",
    "metro-react-native-babel-preset": "0.54.1",
}`


It doesn't use Facebook SDK

**Comment by hejun041** [comment]
Under what circumstances will this happen?
