### ISSUE TITLE
TouchableOpacity in absolute position view on ios

### ISSUE THREAD

**Issue by lizhming** [facebook/react-native#28596]
## Description
I'm building the react native project.
This code works well on Android but doesn't work well on ios.
if I touch the first half of the button, it works, but touch doesn't work on the end of the button on iOS.

```
      <View style={{backgroundColor: 'red', position: 'absolute', bottom: 0, alignSelf: 'center', width: 300}}>
        <TouchableOpacity onPress={()=>{console.log('clicked!');}>
          
          <View style={{flex: 1, backgroundColor: 'blue', width: 300}}>
            <Text style={{flex: 1, backgroundColor: 'green', width: '100%', textAlign: 'center'}}>
            Click Me!
            </Text>
           </View>

        </TouchableOpacity>
      </View>
```

## React Native version:
System:
    OS: macOS 10.15.4
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.13.0 - /usr/local/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.13.0 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.8.4 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  Languages:
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.0 => 0.62.0 
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by arunim2405** [comment]
how was this fixed? @lizhming
