### ISSUE TITLE
gitignore file contians /android/ folder

### ISSUE THREAD

**Issue by Priya-Raut** [facebook/react-native#28595]
## Description
The gitignore file contains /android/ folder. 
![image](https://user-images.githubusercontent.com/13897222/79047105-4ff6ba00-7c32-11ea-97e9-3b1b445a41f3.png)

## React Native version:
Applicable to all the versions if the following gitignore file is used.

## Steps To Reproduce
Please visit line number 54 in the following location. 
https://github.com/facebook/react-native/blob/master/.gitignore

## Expected Results
As someone might need to modify native codes for Android platform, we should not mention
/android/  in gitignore file.

## Snack, code example, screenshot, or link to a repository:
Not applicable

**Comment by jeswinsimon** [comment]
The .gitignore file mentioned above is for the this repo (i.e. the react native source code repo). The .gitignore file that is generated when setting up a new react native project is based on the template provided here: https://github.com/facebook/react-native/blob/master/template/_gitignore

**Comment by Priya-Raut** [comment]
@jeswinsimon 
Thank you for the clarification!
I will close this issue now.
