### ISSUE TITLE
RefreshControl 'enabled' && 'refreshing' broken -> temporary fix

### ISSUE THREAD

**Issue by iSamuelBarney** [facebook/react-native#28591]
```js <ScrollView
        style={{flex: 2, overflow: 'visible'}}
        refreshControl={
          !adding && ( <-- only works when you DON'T RENDER it at all
            <RefreshControl
              enabled={false} <-- doesn't work (doesn't seem to affect anything)
              refreshing={false} <-- doesn't work (affects other things though)
              onRefresh={onRefresh}
              tintColor={'rgb(220,220,220)'}
            />
          )
        }
```

## Description
Here's the closed issue: https://github.com/facebook/react-native/issues/5839 I'm not sure why this would be closed. The enabled & refreshing props should be updated or removed if nobody intends on fixing this. Hopefully this temporary fix helps someone.

## React Native version:
62

**Comment by AntoineDoubovetzky** [comment]
Hi @iSamuelBarney,

The refreshing prop seems to be working fine [here](https://snack.expo.io/?session_id=snack-session-3h!C5dZV2&preview=true&platform=web&iframeId=ykdvzrx4nc&supportedPlatforms=ios,android&name=RefreshControl&description=Example%20usage&waitForData=true)

Can you please provide a Snack or reproducible demo ?
