### ISSUE TITLE
Follow the Android Setup document, I failed by step "Install and run Android stock emulator"

### ISSUE THREAD

**Issue by charmingzuo** [facebook/react-native#2860]
I didn't find the `Intel x86 Emulator Accelerator (HAXM installer)` in my `Android SDK Manager`.

This is the `Android SDK Manager` snapshot in [`Android Setup`](http://facebook.github.io/react-native/docs/android-setup.html) doc:
![9ab7216e-1273-4819-a075-80afb9fd9381](https://cloud.githubusercontent.com/assets/2429983/9974556/d39e39d4-5ec6-11e5-8685-07986b9def4f.png)

But this is mine:
![539c77af-1dd3-48b0-991a-1c1679ec423f](https://cloud.githubusercontent.com/assets/2429983/9974560/23814892-5ec7-11e5-85a1-360cca797edd.png)

Is there has anything I missed?

**Comment by ide** [comment]
I would try going ahead without the HAXM installer. It just makes the simulator faster but you can use another simulator like genymotion or a real device.

**Comment by charmingzuo** [comment]
Sounds good, thank you!
By the way, the `HAXM installer` now appeared in my Android SDK Manager, it's weird...
