### ISSUE TITLE
Unable to find a specification for `RCTTypeSafety (= 0.62.2)` depended upon by `React-RCTAnimation

### ISSUE THREAD

**Issue by siddhant-mohan** [facebook/react-native#28605]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description

[!] Unable to find a specification for `RCTTypeSafety (= 0.62.2)` depended upon by `React-RCTAnimation`

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

[!] use_native_modules! skipped the react-native dependency 'react-native-range-slider'. No podspec file was found.
    - Check to see if there is an updated version that contains the necessary podspec file
    - Contact the library maintainers or send them a PR to add a podspec. The react-native-webview podspec is a good
    example of a package.json driven podspec. See
    https://github.com/react-native-community/react-native-webview/blob/master/react-native-webview.podspec
    - If necessary, you can disable autolinking for the dependency and link it manually. See
    https://github.com/react-native-community/cli/blob/master/docs/autolinking.md#how-can-i-disable-autolinking-for-unsupported-library

getting the above error while upgrading from 0.60.2 to 0.62.2

## React Native version:
System:
    OS: macOS 10.15.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 2.63 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.13.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.7.5 - /Users/s/.rvm/rubies/ruby-2.3.1/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.4/11E146 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.2 - /usr/bin/javac
    Python: 2.7.17 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.8.6 => 16.8.6
    react-native: ^0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. upgrading from 0.60.2 to 0.62.2

**Comment by AliHamdyR** [comment]
Did you find the solution ?

**Comment by muhsinaldemir** [comment]
It tries to find a podspec so you should add it.Add your pod file the following line. It's tested for version 0.62.2.

pod 'RCTTypeSafety', :path => '../node_modules/react-native/Libraries/TypeSafety'
