### ISSUE TITLE
onBlur event conflicting with Alert.alert

### ISSUE THREAD

**Issue by akhil-ksolves** [facebook/react-native#28610]
Alert is creating the problem of losing the focus in TextInput. Let for an example:

    <TextInput onBlur = {() => Alert.alert('focus has been gone from TextInput')} onChangeText = {(text) => Alert.alert('u input something')} />

When I am entering the data, first I am getting alert for onChangeText but consequently the second alert due to the onBlur (I think due to losing the focus after opening the Alert). Is there any way to stop text input to lose focus on Alert opening?

System:
    OS: macOS 10.15.2
    CPU: (4) x64 Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
    Memory: 26.61 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.14.0 - /usr/local/bin/node
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 27, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5

**Comment by lesydat** [comment]
Same issue happen to iOS
