### ISSUE TITLE
[Android] XHR Response Headers empty

### ISSUE THREAD

**Issue by paramaggarwal** [facebook/react-native#2861]
Raising issue to keep track of it. When I am using `superagent` which wraps `XMLHTTPRequest` on iOS - it works fine and I see all the headers. But same code on Android does not have the response headers, this is probably not getting exposed correctly on Android's wrapper.

`xhr.responseHeaders` is `{}`. Probably related to this comment: [NetworkingModule.java#L183](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/modules/network/NetworkingModule.java#L183)

**Comment by mkonicek** [comment]
Thanks for reporting this @paramaggarwal! Would be happy to review a pull request, would you like to look into it?

**Comment by lexs** [comment]
Just going to link the PR from here so somebody doesn't do duplicate work: https://github.com/facebook/react-native/pull/3062

**Comment by nucleartux** [comment]
I think it issue can be closed by PR https://github.com/facebook/react-native/pull/3709

**Comment by lexs** [comment]
Closing as https://github.com/facebook/react-native/issues/2861 was merged.
