### ISSUE TITLE
iOS: Add build configuration other than Debug and Release

### ISSUE THREAD

**Issue by Chakroun-Anas** [facebook/react-native#28613]
## Description

By default they are two build configurations (Debug and Release) that works just fine, however when a new build configuration is added (by duplicating the Release one per example) the build fail targeting it.   

## React Native version:

System:
    OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
    Memory: 1.49 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.4 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 24, 26, 28
      Build Tools: 27.0.3, 28.0.3
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6308749
    Xcode: 11.4/11E146 - /usr/bin/xcodebuild
  Languages:
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.1 => 0.62.1
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Create a new react native project
2. Open iOS folder in Xcode
3. Duplicate Release build configuration (name it Stage per example)
4. Move to the project folder and run the following commande : 

`react-native run-ios --configuration Stage --device`

## Expected Results

The app should run fine. 

## Actual Result 

`fatal error: module map file 'PathToBuildFolder/Stage-iphoneos/YogaKit/YogaKit.modulemap' not found`

**Comment by chrisglein** [comment]
Sounds like the CLI is getting confused by the changes made to your xcode project. This appears to be out of scope of React Native itself, can you engage with the [CLI repo](https://github.com/react-native-community/cli)?
