### ISSUE TITLE
`yarn react-native --version` returns version number of RN CLI instead of RN

### ISSUE THREAD

**Issue by joshglenn** [facebook/react-native#28612]
## Description
Running `yarn react-native --version` returns the react-native-cli version instead of the version number of react-native.

## React Native version:
<= 0.62.2

## Steps To Reproduce
If you open Terminal and `cd` to some random directory and run `react-native --version` (assuming you also have `react-native-cli` installed), the response will look something like this:

```bash
$ react-native --version
react-native-cli: 2.0.1
react-native: n/a - not inside a React Native project directory
```

If you then cd to a react-native project's root folder and run `react-native --version`, it will return the actual version number of that local project.

However, when you run `yarn react-native --version` from the root folder of a react-native project, what actually gets returned is the version of the `@react-native-community/cli` installation. (Something like 4.6.3)

I have discovered that if I want to know the exact react-native version my local project is using, I can use `react-native info`, which is great, but...

## Expected Results
I would expect that `yarn react-native --version` should return the version number of react-native, instead of the react-native cli. Am I thinking about this the right way?

**Comment by seriiix** [comment]
No. `react-native-cli` and `react-native` are two different things. You may have two or more projects using different versions of `react-native`. If you want to check the `react-native` version of your project simple check the `package.json` file.

**Comment by safaiyeh** [comment]
Hi @joshglenn for issues concerning the CLI, you should create issues on this repo: https://github.com/react-native-community/cli
