### ISSUE TITLE
[iOS][TextInput] Clear value after insert a character that exceeds maxLength

### ISSUE THREAD

**Issue by kaioduarte** [facebook/react-native#28622]
## Description
In iOS the content of `TextInput` (with `maxLength` and initial value as longer as it's not possible to add any multi character) is getting cleared when I insert a multi character.

## React Native version:
- 0.61.4, the same as Snack (only tested there)

## Steps To Reproduce
1. Set `maxLength` to 10 (arbitrary value)
2. Set the initial value to a 9 characters string ('abcdefghi')
3. Add an emoji through `TextInput`

## Expected Results
- The value should not change

## Snack, code example, screenshot, or link to a repository:
https://snack.expo.io/@kaioduarte/keyboard-bug

### iOS
![iOS](https://user-images.githubusercontent.com/11046907/79222081-d4be1f80-7e4e-11ea-8f9d-c3ca05082291.gif)

### Android
![Android](https://user-images.githubusercontent.com/11046907/79222210-0c2ccc00-7e4f-11ea-8725-48e571d51488.gif)

**Comment by ariel-diaz** [comment]
Any solution? thanks!
