### ISSUE TITLE
'React/RCTViewManager.h' file not found

### ISSUE THREAD

**Issue by alejandroAhumada** [facebook/react-native#28628]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
When compiling the app. on find 'React / RCTViewManager.h'.

## React Native version:
 React Native Environment Info:
    System:
      OS: macOS 10.14.6
      CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
      Memory: 895.89 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 13.12.0 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
      Android SDK:
        API Levels: 26, 27, 28, 29
        Build Tools: 27.0.2, 27.0.3, 28.0.0, 28.0.1, 28.0.2, 28.0.3, 29.0.0, 29.0.1, 29.0.2, 29.0.3
        System Images: android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6241897
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3 
      react-native: 0.59.5 => 0.59.5 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-navigation: 6.3.2
      react-native-svg: 12.0.3

## Steps To Reproduce

1. Add ARTShape to library

**Comment by xbaos** [comment]
same problem i found, in the react-native-community/art at ios

**Comment by MAhtishamShahzad** [comment]
'React/RCTViewManager.h' file not found after upgrade 0.62 to 0.63.2

**Comment by NightWarrior** [comment]
Anyone still having this issue, check your `ios/Podfile.lock` file and search for React, mine was turning being set to 0.11.0 for some reason while i was on 0.63.4 react native version. The issue causing that was in `package.json` file under `resolutions`, i deleted the followings and it fixed itself 

`"@react-native-community/cli": "3.0.0-alpha.2",
    "@react-native-community/cli-platform-android": "3.0.0-alpha.2",
    "@react-native-community/cli-platform-ios": "3.0.0-alpha.2",
    "@react-native-community/cli-tools": "2.8.3"`
