### ISSUE TITLE
ios - TurboModuleRegistry.getEnforcing 'ImageLoader' issue

### ISSUE THREAD

**Issue by Desintegrator** [facebook/react-native#28620]
## Description
Cannot startup ios app after upgrade RN version from 0.59.9 to 0.62.2. Have no idea where the issue is and how to fix it.

## React Native version:
System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 1.36 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.14.1 - /usr/local/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.4 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 23.0.1, 23.0.3, 25.0.0, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.2, 28.0.3
      System Images: android-19 | Google APIs ARM EABI v7a, android-19 | Google APIs Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom
      Android NDK: 17.1.4828580
  IDEs:
    Android Studio: Not Found
    Xcode: 10.1/10B61 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_181 - /usr/bin/javac
    Python: 2.7.15 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^16.11.0 => 16.13.1 
    react-native: ^0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
1. upgrade from RN 0.59.9 to 0.62.2
2. run app in Xcode

## Expected Results
app successfully started

## Snack, code example, screenshot, or link to a repository:
![image](https://user-images.githubusercontent.com/17068034/79218113-5a4ec900-7e69-11ea-9f80-f3b4d91b2ef1.png)

**Comment by flyingcircle** [comment]
+1 same issue

**Comment by flyingcircle** [comment]
Some tests I've tried. I tried creating a react-native init app with version 61.5 which I was able to get running. However, it was when I started to add some third party libraries that this error started to appear. However, OP doesn't list any of the third party libraries that caused this error to show for me. It must be something that changed recently in the react-create init itself that's causing this?

**Comment by flyingcircle** [comment]
@Desintegrator what version of react-native-cli are you using?

**Comment by Desintegrator** [comment]
> @Desintegrator what version of react-native-cli are you using?

@flyingcircle how can i check it?

**Comment by flyingcircle** [comment]
@designorant I'm not entirely convinced it has to do with that version anymore, but you would get it from `react-native --version`

**Comment by Desintegrator** [comment]
@flyingcircle i'm downgraded to 0.61.5 and version is -- react-native-cli: 2.0.1

**Comment by flyingcircle** [comment]
That's also my version! We may be onto something here.

**Comment by Desintegrator** [comment]
> Do you need help upgrading to a newer React Native version? Visit the [Upgrade Support repository](https://github.com/react-native-community/upgrade-support) or use the [upgrade helper](https://react-native-community.github.io/upgrade-helper/) to see the changes that need to be made to upgrade your app.

I've latest RN and followed upgrade helper

**Comment by adityaCarmatec** [comment]
I solved it by stopping the debugger  after that used the empty catch and hard relead
