### ISSUE TITLE
AppState 'change' event handler function doesen't have access to state

### ISSUE THREAD

**Issue by Borming** [facebook/react-native#28639]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
There is a bug with a code example that's on the page: https://reactnative.dev/docs/appstate#app-states. It tries to compare the current state appState to the nextAppState but the appState is always the same. For some reason, the appState is not accessible.

## React Native version:
System:
    OS: macOS 10.15.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 563.62 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.13.1 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.12.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 11.4/11E146 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Copy/paste example from https://reactnative.dev/docs/appstate#app-states
2. Run app

## Expected Results
The if clause should work and output "App has come to the foreground!" but it doesn't as appState is not accessible for some reason.

**Comment by cHaLkdusT** [comment]
Hi all, this is still an issue in react-native v0.62.1. Apparently, any useState "set" methods doesn't update the component's state.

**Comment by cHaLkdusT** [comment]
This only occurs to the functional component that uses `useState` hooks. The class-based component is working as expected.

**Comment by Borming** [comment]
@cHaLkdusT Yes. That's correct. Any fix for this? Is this an issue with react-native or with hooks?

**Comment by cHaLkdusT** [comment]
Hey bot! Don't close this issue yet.

**Comment by Borming** [comment]
I think this issue shouldn't be closed.

**Comment by LaurenceRolandJames** [comment]
This is not a documentation issue.

I've reproduced the issue here: https://github.com/LaurenceRolandJames/AppStateActiveRepro/tree/master

**Comment by jaworek** [comment]
I think my issue is exactly the same #29218

**Comment by cHaLkdusT** [comment]
Hey @Borming 

Using react-native v0.62.2, I've retested this issue and seems working now. See reference for function component example [here](https://reactnative.dev/docs/appstate). Let me know if it works on your end so we can now close this issue.

**Comment by jaworek** [comment]
@cHaLkdusT Thanks! I'll check it out and let you know.

**Comment by jaworek** [comment]
@cHaLkdusT I'm currently using react-native 0.63.2 and react 16.13.1. I'm still having this problem on iOS. When leaving the app state goes to 'background', but then in logs I can see that it changes to 'active', even though I have not returned to the app. Thus, when I come back to the app, current and next state are both 'active', which prevents me from detecting that user opened app again from the background.

**Comment by CTOverton** [comment]
@cHaLkdusT I'm also still having this issue in react-native 0.63.2. All I have is another
```jsx
const [open, setOpen] = useState(false)
```
That when accessed from inside the listener at 
```js
console.log("App has come to the foreground!");
```
It is always the same value even when updated previously
