### ISSUE TITLE
Image.getSizeWithHeaders not working on iOS RN 0.62 

### ISSUE THREAD

**Issue by caigehui** [facebook/react-native#28632]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description

the second param "Headers" is  not working

## React Native version:
Run `react-native info` in your terminal and copy the results here.

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.
2.

## Expected Results
Describe what you expected to happen.

## Snack, code example, screenshot, or link to a repository:
Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by wincjh** [comment]
did you solve it?

**Comment by caigehui** [comment]
> did you solve it?

Not yet, Downgrade to 0.61.5 works fine

**Comment by rgoldiez** [comment]
I can confirm this is an issue that started with RN 0.62.  Calling `getSizeWithHeaders` with headers doesn't work right on iOS.  Android is fine.  Both platforms are fine on 0.61

**Comment by johhansantana** [comment]
has this been fixed in 0.63? Mine seems to fail but when I use the headers to load normally in the component it works. Just not in `Image.getSizeWithHeaders`

**Comment by PaitoAnderson** [comment]
@johhansantana This was fixed in 0.63.3.

https://github.com/react-native-community/releases/blob/master/CHANGELOG.md#v0633

**Comment by johhansantana** [comment]
Ah! Gotta update. I'm in 0.63.2. Thank you!
