### ISSUE TITLE
The movies demo work well on genymotion,but not my Mi 2s(Android)

### ISSUE THREAD

**Issue by dumingxin** [facebook/react-native#2863]
I just followed the Docs,It can work well on genymotion,but the activity is empty on Mi 2s, The version is Android 5.0.2

**Comment by timzaak** [comment]
the android phone will ask 127.0.0.1:8081 for resource, but your npm server run on your pc, http://facebook.github.io/react-native/docs/running-on-device-android.html#content may solve your problem

**Comment by dumingxin** [comment]
It works,thank you
