### ISSUE TITLE
TouchableOpacity triggers touch animation when scrolling.

### ISSUE THREAD

**Issue by padapada09** [facebook/react-native#28635]
With a list of touchable opacity components, if I scroll, the touchableOpacities trigger the touch animation. It should be prevented.

## React Native version:
System:
    OS: Linux 5.3 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
    Memory: 452.29 MB / 7.60 GB
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 12.14.0 - ~/Apps/nodejs/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.14.4 - ~/Apps/nodejs/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  npmPackages:
    react: 16.8.1 => 16.8.1 
    react-native: 0.61.2 => 0.61.2

## Steps To Reproduce

1. Create a scrollView component.
2. 'Fill it' with a set of touchable opacity components
3. When scrolling, the touchable opacity animation will trigger.

## Expected Results
I think it shoul not trigger the touch animation if it's not been press but scrolled.

**Comment by andreialecu** [comment]
You can add a small delay to the touchable, like `delayPressIn={100}` to resolve this.

**Comment by JoeDurand3** [comment]
This is still an issue as of 0.63 - I can produce a repro if that would be helpful, although it is simply a TouchableOpacity within a ScrollView...
