### ISSUE TITLE
How to import buildStyleInterpolator ?

### ISSUE THREAD

**Issue by Desintegrator** [facebook/react-native#28633]
## Description
cannot use buildStyleInterpolator after RN upgrade from 0.59.9 to 0.61.5

## React Native version:
System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 477.53 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.14.1 - /usr/local/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 23.0.1, 23.0.3, 25.0.0, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.2, 28.0.3
      System Images: android-19 | Google APIs ARM EABI v7a, android-19 | Google APIs Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom
      Android NDK: 17.1.4828580
  IDEs:
    Xcode: 10.1/10B61 - /usr/bin/xcodebuild
  npmPackages:
    react: ^16.12.0 => 16.13.1 
    react-native: ^0.61.5 => 0.61.5 
  npmGlobalPackages:
    create-react-native-app: 1.0.0
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7

## Steps To Reproduce

1. import buildStyleInterpolator
2. start app

## Expected Results
all works properly

## Snack, code example, screenshot, or link to a repository:

`import buildStyleInterpolator from 'buildStyleInterpolator'`
`const buildStyleInterpolator = require('buildStyleInterpolator')`
`const {buildStyleInterpolator} = require('react-native')`

none of this works

![image](https://user-images.githubusercontent.com/17068034/79331469-a0bd2a00-7f34-11ea-99df-2990a764c7c0.png)

**Comment by Desintegrator** [comment]
same question about ExceptionsManager utility

**Comment by retyui** [comment]
@Desintegrator 

```js
// RN 0.63.x
import buildStyleInterpolator from 'react-native/Libraries/Utilities/buildStyleInterpolator';
```

**Comment by Desintegrator** [comment]
@retyui thanks, will try it soon
