### ISSUE TITLE
Android upload file just doesn't work RN 0.62.0

### ISSUE THREAD

**Issue by omerman** [facebook/react-native#28630]
Hi, I'll head right to the chase

opening a fresh RN project, version 0.62.0, not able to upload Android file to server.

You are welcome to take a look at a fresh repo, Compared to RN 0.62, only modified App.js to show my failing attempts of uploading an android asset to the server.
The used host is https://www.google.com, but it really doesnt matter because the request throws before it gets to the network.

https://github.com/omerman/React-native-android-upload-file-errors

## React Native version:
System:
OS: macOS 10.15.3
CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
Memory: 268.94 MB / 8.00 GB
Shell: 5.7.1 - /bin/zsh
Binaries:
Node: 10.14.1 - /usr/local/bin/node
Yarn: 1.22.4 - /usr/local/bin/yarn
npm: 6.4.1 - /usr/local/bin/npm
Watchman: Not Found
Managers:
CocoaPods: 1.7.2 - /usr/local/bin/pod
SDKs:
iOS SDK:
Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
Android SDK:
API Levels: 23, 26, 27, 28
Build Tools: 26.0.3, 27.0.2, 27.0.3, 28.0.3
System Images: android-28 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
Android NDK: Not Found
IDEs:
Android Studio: 3.3 AI-182.5107.16.33.5264788
Xcode: 11.4/11E146 - /usr/bin/xcodebuild
Languages:
Python: 2.7.16 - /usr/bin/python
npmPackages:
@react-native-community/cli: Not Found
react: 16.11.0 => 16.11.0
react-native: 0.62.2 => 0.62.2
npmGlobalPackages:
react-native: Not Found

Please let me know if any more details are required,

Thanks in advance

**Comment by omerman** [comment]
Just FYI, this lib seems to get the job done (uploading android file)
https://github.com/joltup/rn-fetch-blob

But it should also be possible without using any external library, dont you agree?

**Comment by omerman** [comment]
Dev env info

System:
    OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 268.94 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.14.1 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.7.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 26, 27, 28
      Build Tools: 26.0.3, 27.0.2, 27.0.3, 28.0.3
      System Images: android-28 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.3 AI-182.5107.16.33.5264788
    Xcode: 11.4/11E146 - /usr/bin/xcodebuild
  Languages:
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by caigehui** [comment]
Same issue here.
Unable to upload file by "fetch" RN 0.62

**Comment by ceressteven** [comment]
Same issue here.
Unable to upload file by "fetch" on RN 0.62.2,and when i debug. with android studio ,i got an info:
Stop reading file since a wrong offset may cause an infinite loop: 0,
i think the erro maybe is catch with this

**Comment by devvit** [comment]
Flipper cause issue #28551

**Comment by omerman** [comment]
@devvit Thank you.
closing as it seems to be duplicate of #28551

**Comment by sjonchhe** [comment]
Holy lord!!! Flipper was the issue!! I upgraded it to 0.45.0 and it worked.

**Comment by take-o20** [comment]
I use react-native 0.62.2 . I can't resoleve this problem by above.
But I can upload image file by using "uploadFiles" func  of react-native-fs .
https://github.com/itinance/react-native-fs

**Comment by RNTop** [comment]
Please disable "initializeFlipper(this, getReactNativeHost().getReactInstanceManager());" in MainApplication.java.
it will works for you perfectly.

**Comment by roberts-d** [comment]
Anyone still having the issue, try XHR request

```
const URL = "ANY_SERVER/upload/image"
  const xhr = new XMLHttpRequest();
  xhr.open('POST', url); // the address really doesnt matter the error occures before the network request is even made.
  const data = new FormData();
  data.append('image', { uri: image.path, name: 'image.jpg', type: 'image/jpeg' });

  xhr.send(data);
  xhr.onreadystatechange = e => {
    if (xhr.readyState !== 4) {
      return;
    }

    if (xhr.status === 200) {
      console.log('success', xhr.responseText);
    } else {
      console.log('error', xhr.responseText);
    }
  };
```
It's working for me
