### ISSUE TITLE
How to set margin-top/bottom/left/right auto trick in RN?

### ISSUE THREAD

**Issue by Bayramito** [facebook/react-native#28644]
Hello,

I wonder how can i do the  margin trick in RN such as we do on web

For example lets say we have 2 divs. And i want the bottom one expand to  the top.Think about a chat screen and you need to set  messages go from bottom to top... How would set such a setup ?

Iin WEB you just set message container to flex 1 and and make a empty  component on top of the list and give kt a margin-top:auto... And empty component will take all the empty space untill the list item..

So how to do same thing in flatlist in react native??

I actually tried inverted=true in flatlist props but this gives me everything reversed..  i dont need that..

**Comment by therealadum** [comment]
@Bayramito could you provide a rough drawing of what you need? Based off of your requirements you could potentially use flexbox column reverse, but i'd love to see your use-case to better help you out

**Comment by Bayramito** [comment]
> @Bayramito could you provide a rough drawing of what you need? Based off of your requirements you could potentially use flexbox column reverse, but i'd love to see your use-case to better help you out

Hi,
Thank you for you response. 

So my goal is to create a chatting screen. As you can gues, chat ballons starts from bottom and goes to top. For this effect i could use flatlist with prop called inverted=true,  but then the data inside of it, also being reversed. Of course i can manipulate the data before putting in flatlist but, it causes me different problems. 

The major problem is, i can't find a way to put the date of the message on top of the message box.  

My case is explained much more detailed here please take a look at :) Thank you!

https://stackoverflow.com/questions/61237564/how-can-i-show-days-by-group-like-whatsapp-chat-screen
