### ISSUE TITLE
Unresolved reference: PermissionAwareActivity

### ISSUE THREAD

**Issue by idanavs** [facebook/react-native#28647]
## Description
After updating the android studio, now that is what happened.. 

![image](https://user-images.githubusercontent.com/28900951/79441184-9c018000-7fdf-11ea-87d7-699d978e7897.png)

## React Native version:
```
System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 22.83 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.12.0 - /usr/local/bin/node
    npm: 6.14.4 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6308749
    Xcode: 11.4/11E146 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

**Comment by safaiyeh** [comment]
Hi @idanavs this looks like an issue with Expo's permission library. You should make an issue with them over at: https://github.com/expo/expo

**Comment by JeroenVanSteijn** [comment]
![image](https://user-images.githubusercontent.com/32145092/106297783-60c0fc80-6253-11eb-82a0-3e45721f41c5.png)
Changing the react native version from a .tar.gz link to the actual NPM package fixed it for me
