### ISSUE TITLE
devices about react-native run-android command

### ISSUE THREAD

**Issue by 2239559319** [facebook/react-native#28652]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
I connect my PC with usb, and I also have an Android simulator on my computer. Then I run `react-native run-android` command. Sometimes programs are on  Android simulator and sometimes on my phone.

## React Native version:
System:
    OS: Windows 10 10.0.18362
    CPU: (4) x64 Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz
    Memory: 7.94 GB / 15.80 GB
  Binaries:
    Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-28 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5900203
  Languages:
    Java: 1.8.0_221
    Python: 3.7.4
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce

1. connect my phone and PC with usb
2. run `react-native run-android` command

## Expected Results
I want to run program on my phone not Android simulator on my PC, and I don't want to uninstall Android simulator. Is there any option to select a device 

## Snack, code example, screenshot, or link to a repository:
Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by farshidshahmoradi1996** [comment]
this related to Android Debug Bridge (aka `adb`).
try this :<br>
```shell
$ adb devices
```
this command should list of all connect devices and simulator such as :<br>
```shell
List of devices attached 
emulator-5554 device
7f1c864e  device
```
for specify  device :<br>
```shell
adb -s 7f1c864e shell
```
see also [this](http://developer.android.com/tools/help/adb.html#directingcommands)
------ 
use `npx react-native run-android`  insted of ` react-native run-android`

**Comment by hramos** [comment]
The React Native CLI supports running your app on a specific emulator or physical device. From [the instructions](https://github.com/react-native-community/cli/blob/master/docs/commands.md#run-android),

```
--deviceId [string]
builds your app and starts it on a specific device/simulator with the given device id (listed by running "adb devices" on the command line).
```

...you should be able to run `react-native run-android --deviceId [string]` where `[string]` is the id of your device as obtained by running `adb devices`.

**Comment by johnakon** [comment]
Ok guys. I want to run this command on my Android phone that i use. Will my phone data get wiped? how does it work ?
