### ISSUE TITLE
[Android][StyleSheet] Unitless string used as value causes app crash

### ISSUE THREAD

**Issue by Simek** [facebook/react-native#28654]
## Description

Refs facebook/react-native-website#1834.

Currently when unitless string is used as property value (where `number` or `string` with unit can be used) Android application crashes, while on iOS value is converted to the `number` and on the web invalid property is omitted app works correctly.

## React Native version:
* Expo `37.0.0`
* React Native `0.62.2`

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Use unitless string as property value (where `number` or `string` with unit can be used).

## Expected Results
Property with invalid value should be converted like on iOS or omitted like on the web. Also Android 
app should not crash.

~~As a feature request, it could be nice to convert that value to `number` and print console warning in `DEV` mode.~~

## Snack, code example, screenshot, or link to a repository:
* https://snack.expo.io/@simek/unitless-string-crash-on-android

**Comment by TheSavior** [comment]
In Dev I see the crash on android, and a redbox on iOS. 

Android:
```
04-16 11:46:29.882 12338 12402 E ReactNative: java.lang.IllegalArgumentException: Unknown value: 10
04-16 11:46:29.882 12338 12402 E ReactNative: 	at com.facebook.react.uimanager.LayoutShadowNode$MutableYogaValue.setFromDynamic(LayoutShadowNode.java:63)
04-16 11:46:29.882 12338 12402 E ReactNative: 	at com.facebook.react.uimanager.LayoutShadowNode.setPaddings(LayoutShadowNode.java:688)
```

![Simulator Screen Shot - iPhone 11 Pro - 2020-04-16 at 11 49 18](https://user-images.githubusercontent.com/249164/79494762-660ccd80-7fd8-11ea-9945-c6cbe31687fa.png)

I haven't figured out what the prod experience is yet. Are you saying that in prod iOS continues and Android crashes?

**Comment by Simek** [comment]
I'm just a "re-reporter", I can only confirm that `expo` example crashes on Android (in web player and on the device), when on iOS in both cases app is running. I don't have physical Android device right now to test this out more, but before I reported that issue I got a confirmation that it also crashes Android without `expo`.

**Comment by TheSavior** [comment]
In Fabric (at least on Android) the behavior is different as well. `padding: "100"` is treated as the number `padding: 100` and does not crash.

**Comment by TheSavior** [comment]
I tried this out on 0.60 and was able to get a redbox on Android.

![android_Phone Screen Shot 2020-04-16 at 14 13 21](https://user-images.githubusercontent.com/249164/79507408-85adf100-7fec-11ea-88a9-45c23e8a0c4a.png)

**Comment by Simek** [comment]
Using unitless `string` as `fontSize` value on iOS produces different RedBox in DEV mode than you posted in first reply:
<img src="https://user-images.githubusercontent.com/719641/79511172-0d245000-803f-11ea-9331-ed9121ff80c1.PNG" width="260">

**Comment by Simek** [comment]
🤖
