### ISSUE TITLE
Android Image.getSize throws Pool hard cap violation

### ISSUE THREAD

**Issue by frankyjuang** [facebook/react-native#28668]
## Description

Call `Image.getSize` with several images (less than 10) throws error
```
[Error: Pool hard cap violation? Hard cap = 150994944 Used size = 108316036 Free size = 0 Request size = 48771072]
```

Related to 
https://github.com/facebook/react-native/issues/10170
https://github.com/facebook/react-native/issues/10569
https://github.com/facebook/react-native/issues/11326

## React Native version:

```
System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
    Memory: 29.09 MB / 8.00 GB
    Shell: 5.0.16 - /usr/local/bin/bash
  Binaries:
    Node: 10.15.1 - /var/folders/cd/p2ngbvv541q7d31dzv1rhfjc0000gn/T/yarn--1587133738606-0.8272158970505921/node
    Yarn: 1.22.4 - /var/folders/cd/p2ngbvv541q7d31dzv1rhfjc0000gn/T/yarn--1587133738606-0.8272158970505921/yarn
    npm: 6.12.0 - ~/.nvm/versions/node/v10.15.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6308749
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

## Steps To Reproduce

```typescript
    Image.getSize(
      uri,
      (width, height) => {},
      (err) => console.log(err)
    );
```

## Expected Results

Returns image width and height without error.

**Comment by safaiyeh** [comment]
Hi @frankyjuang we would like to see a minimum repro with this issue for us to investigate. It helps to understand all the factors in play

**Comment by frankyjuang** [comment]
@safaiyeh weird i can't repro on expo android. Will reopen if i find more info.

**Comment by diegovfeder** [comment]
@frankyjuang did you manage to fix this issue? 
I'm having a similar problem while loading a list of "heavy" images.

**Comment by frankyjuang** [comment]
@diegovfeder not really. end up with other workaround to get image sizes

**Comment by diegovfeder** [comment]
Actually I found a solution. As I was getting this problem only for Android I needed to add this to "android/app/src/main/AndroidManifest.xml"

<application android:largeHeap="true"

**Comment by danilo900** [comment]
> application android:largeHeap="true"

GOD! I used, that increased a lot.
But, what IF I need more? HAHAH

`Pool hard cap violation? Hard cap = 402653184 Used size = 402518748 Free size = 0 Request size = 709800`

**Comment by marcaaron** [comment]
In our case, this was solved by adding `removeClippedSubviews` to the `FlatList` and `SectionList` that load these images.

**Comment by karatekid430** [comment]
@marcaaron using removeClippedSubviews not only solved our images not loading on Android, but also resulted in a vast performance improvement. Life saver. Thank you!
