### ISSUE TITLE
Error react-native run-android

### ISSUE THREAD

**Issue by edmirsobrinho123** [facebook/react-native#28666]
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 967 file(s) to forward-jetify. Using 4 workers...
info JS server already running.
'adb' n�o � reconhecido como um comando interno
ou externo, um programa oper�vel ou um arquivo em lotes.
info Launching emulator...
error Failed to launch emulator. Reason: No emulators found as an output of `emulator -list-avds`.
warn Please launch an emulator manually or connect a device. Otherwise app may fail to launch.
info Installing the app...

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.0.1/userguide/command_line_interface.html#sec:command_line_warnings

FAILURE: Build failed with an exception.

* What went wrong:
Task 'installDebug' not found in project ':app'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Task 'installDebug' not found in project ':app'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s

    at makeError (C:\Users\LENOVO\Desktop\PROJETOS.ANO.2020\PROJETOS 02.2020\APLICATIVOS.REACT.NATIVE\app\app\node_modules\execa\index.js:174:9)
    at C:\Users\LENOVO\Desktop\PROJETOS.ANO.2020\PROJETOS 02.2020\APLICATIVOS.REACT.NATIVE\app\app\node_modules\execa\index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async runOnAllDevices (C:\Users\LENOVO\Desktop\PROJETOS.ANO.2020\PROJETOS 02.2020\APLICATIVOS.REACT.NATIVE\app\app\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:94:5)
    at async Command.handleAction (C:\Users\LENOVO\Desktop\PROJETOS.ANO.2020\PROJETOS 02.2020\APLICATIVOS.REACT.NATIVE\app\app\node_modules\react-native\node_modules\@react-native-community\cli\build\index.js:186:9)

**Comment by SuporteWebGerente** [comment]
> error Failed to launch emulator. Reason: No emulators found as an output of emulator -list-avds

The error message implies that you don't have an emulator running... You can use Android Studio (option AVD Manager) to setup and run one.

**Comment by edmirsobrinho123** [comment]
Hi, but its strange because my emulator is already opened

**Comment by osman144** [comment]
So you have the emulator open and its giving this error?

**Before you go ahead with these instructions** 

Do you have any emulators/virtual devices in android studio ? Open android studio --> go to the bottom --> select configure --> Then avd manager to see the devices in your system. 

**If you have devices listed proceed with these steps**

1) Open android studio. Select 'open project'. Go to root of your react native project, then go to the android folder. Open the project as a gradle project in Android studio ide. It will build the gradle project. 

<img width="983" alt="Screen Shot 2020-04-18 at 11 27 52 PM" src="https://user-images.githubusercontent.com/25594064/79679570-5e157f00-81cc-11ea-8ba4-8c41fc6678ea.png">

2)  After the IDE opens, the gradle daemon will do its thing and sync and configure the build for you, and the project builds successfully.  If it does not, you might have some missing dependencies. 

4.) Open the build tab at the bottom of the IDE, and watch for changes as you run the project in the emulator. Look for any errors as it launches the project

3.)  Once its finished. Select your emulator. Press the play button. Or run 'react-native run-android'. 

<img width="831" alt="Screen Shot 2020-04-18 at 11 31 53 PM" src="https://user-images.githubusercontent.com/25594064/79679638-4094e500-81cd-11ea-91d6-e4069207fcd0.png">

**Comment by AkshayNaikRB** [comment]
Facing same issue, here's the output on running `react-native run-android` 

E:\My Projects\New folder\WVTEST>react-native run-android
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 960 file(s) to forward-jetify. Using 4 workers...
info Starting JS server...
The system cannot find the path specified.
info Launching emulator...
error Failed to launch emulator. Reason: No emulators found as an output of `emulator -list-avds`.
warn Please launch an emulator manually or connect a device. Otherwise app may fail to launch.
info Installing the app...
> Task :app:mergeDebugResources FAILED
8 actionable tasks: 8 executed

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> Multiple task action failures occurred:
   > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
      > AAPT2 aapt2-4.0.0-6051327-windows Daemon #5: Daemon startup failed
        Please check if you installed the Windows Universal C Runtime.
        This should not happen under normal circumstances, please file an issue if it does.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
      > AAPT2 aapt2-4.0.0-6051327-windows Daemon #4: Daemon startup failed
        Please check if you installed the Windows Universal C Runtime.
        This should not happen under normal circumstances, please file an issue if it does.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
      > AAPT2 aapt2-4.0.0-6051327-windows Daemon #6: Daemon startup failed
        Please check if you installed the Windows Universal C Runtime.
        This should not happen under normal circumstances, please file an issue if it does.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
      > AAPT2 aapt2-4.0.0-6051327-windows Daemon #7: Daemon startup failed
        Please check if you installed the Windows Universal C Runtime.
        This should not happen under normal circumstances, please file an issue if it does.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
      > AAPT2 aapt2-4.0.0-6051327-windows Daemon #8: Daemon startup failed
        Please check if you installed the Windows Universal C Runtime.
        This should not happen under normal circumstances, please file an issue if it does.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
      > AAPT2 aapt2-4.0.0-6051327-windows Daemon #9: Daemon startup failed
        Please check if you installed the Windows Universal C Runtime.
        This should not happen under normal circumstances, please file an issue if it does.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
      > AAPT2 aapt2-4.0.0-6051327-windows Daemon #10: Daemon startup failed
        Please check if you installed the Windows Universal C Runtime.
        This should not happen under normal circumstances, please file an issue if it does.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
      > AAPT2 aapt2-4.0.0-6051327-windows Daemon #11: Daemon startup failed
        Please check if you installed the Windows Universal C Runtime.
        This should not happen under normal circumstances, please file an issue if it does.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> Multiple task action failures occurred:
   > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
      > AAPT2 aapt2-4.0.0-6051327-windows Daemon #5: Daemon startup failed
        Please check if you installed the Windows Universal C Runtime.
        This should not happen under normal circumstances, please file an issue if it does.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
      > AAPT2 aapt2-4.0.0-6051327-windows Daemon #4: Daemon startup failed
        Please check if you installed the Windows Universal C Runtime.
        This should not happen under normal circumstances, please file an issue if it does.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
      > AAPT2 aapt2-4.0.0-6051327-windows Daemon #6: Daemon startup failed
        Please check if you installed the Windows Universal C Runtime.
        This should not happen under normal circumstances, please file an issue if it does.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
      > AAPT2 aapt2-4.0.0-6051327-windows Daemon #7: Daemon startup failed
        Please check if you installed the Windows Universal C Runtime.
        This should not happen under normal circumstances, please file an issue if it does.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
      > AAPT2 aapt2-4.0.0-6051327-windows Daemon #8: Daemon startup failed
        Please check if you installed the Windows Universal C Runtime.
        This should not happen under normal circumstances, please file an issue if it does.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
      > AAPT2 aapt2-4.0.0-6051327-windows Daemon #9: Daemon startup failed
        Please check if you installed the Windows Universal C Runtime.
        This should not happen under normal circumstances, please file an issue if it does.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
      > AAPT2 aapt2-4.0.0-6051327-windows Daemon #10: Daemon startup failed
        Please check if you installed the Windows Universal C Runtime.
        This should not happen under normal circumstances, please file an issue if it does.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
      > AAPT2 aapt2-4.0.0-6051327-windows Daemon #11: Daemon startup failed
        Please check if you installed the Windows Universal C Runtime.
        This should not happen under normal circumstances, please file an issue if it does.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s

    at makeError (E:\My Projects\New folder\WVTEST\node_modules\execa\index.js:174:9)
    at E:\My Projects\New folder\WVTEST\node_modules\execa\index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async runOnAllDevices (E:\My Projects\New folder\WVTEST\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:94:5)
    at async Command.handleAction (E:\My Projects\New folder\WVTEST\node_modules\react-native\node_modules\@react-native-community\cli\build\index.js:186:9)




Note: i do have adb devices running
