### ISSUE TITLE
../node_modules/react-native/scripts/react-native-xcode.sh': not a valid identifier

### ISSUE THREAD

**Issue by Maochengfag** [facebook/react-native#28660]
## React Native version:
Run `react-native info` in your terminal and copy the results here.

/Users/edz/Library/Developer/Xcode/DerivedData/good-gztkgdoqzhchftevshndpqzmgvjb/Build/Intermediates.noindex/good.build/Debug-iphonesimulator/good.build/Script-00DD1BFF1BD5951E006B06BC.sh: line 2: export: `../node_modules/react-native/scripts/react-native-xcode.sh': not a valid identifier
Command PhaseScriptExecution failed with a nonzero exit code

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

001. to fix this problem 
Script-00DD1BFF1BD5951E006B06BC.sh: line 3: ../node_modules/react-native/packager/react-native-xcode.sh: No such file or directory

1.open Xcode Build Phases > Bundle React Native code and images
2.edit export NODE_BINARY=node ../node_modules/react-native/packager/react-native-xcode.sh to export NODE_BINARY=node ../node_modules/react-native/scripts/react-native-xcode.sh
<img width="823" alt="image" src="https://user-images.githubusercontent.com/5634505/79528190-e811fa80-809b-11ea-9689-da1f979a9d9d.png">

002 build project

## Expected Results
Describe what you expected to happen.
I want to know how to fix this error

Best wishes!!!

## Snack, code example, screenshot, or link to a repository:
Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by maxgertner** [comment]
Under bundle react native code and images in the Build Phases tab, replace the existing export file with:

`export NODE_BINARY=node
../node_modules/react-native/scripts/react-native-xcode.sh ./src/index.ios.js`

**Comment by amangeldimagjan** [comment]
I just added quotes
`export NODE_BINARY="node /Users/dev/Desktop/projects/msk/node_modules/react-native/scripts/react-native-xcode.sh"`

**Comment by abbyhilman** [comment]
> Hello, result of react native info : OS: macOS 10.15.7 CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz Memory: 278.38 MB / 8.00 GB Shell: 5.7.1 - /bin/zsh Binaries: Node: 12.9.0 - /usr/local/bin/node Yarn: Not Found npm: 6.10.2 - /usr/local/bin/npm Watchman: Not Found Managers: CocoaPods: 1.11.0. - /usr/local/bin/pod SDKs: iOS SDK: Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0 Android SDK: Not Found IDEs: Android Studio: 2020.3 AI-203.7717.56.2031.7621141 Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild Languages: Java: 13.0.2 - /usr/bin/javac npmPackages: @react-native-community/cli: Not Found react: 17.0.2 => 17.0.2 react-native: 0.65.0 => 0.65.0 react-native-macos: Not Found npmGlobalPackages: _react-native_: Not Found
> 
> I am getting this error - ../node_modules/react-native/scripts/react-native-xcode.sh: line 84: /scripts/find-node.sh: No such file or directory
> 
> Can any one please suggest some way around to resolve this this ?



> Hello, result of react native info : OS: macOS 10.15.7 CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz Memory: 278.38 MB / 8.00 GB Shell: 5.7.1 - /bin/zsh Binaries: Node: 12.9.0 - /usr/local/bin/node Yarn: Not Found npm: 6.10.2 - /usr/local/bin/npm Watchman: Not Found Managers: CocoaPods: 1.11.0. - /usr/local/bin/pod SDKs: iOS SDK: Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0 Android SDK: Not Found IDEs: Android Studio: 2020.3 AI-203.7717.56.2031.7621141 Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild Languages: Java: 13.0.2 - /usr/bin/javac npmPackages: @react-native-community/cli: Not Found react: 17.0.2 => 17.0.2 react-native: 0.65.0 => 0.65.0 react-native-macos: Not Found npmGlobalPackages: _react-native_: Not Found
> 
> I am getting this error - ../node_modules/react-native/scripts/react-native-xcode.sh: line 84: /scripts/find-node.sh: No such file or directory
> 
> Can any one please suggest some way around to resolve this this ?

Same issue

**Comment by soyadrianhurtado** [comment]
I have the same problem, my solution was to change the path :
 `../node_modules/react-native/scripts/react-native-xcode.sh:` 
with :
` ../../../node_modules/react-native/scripts/react-native-xcode.sh:` 
 where is my parent folder 

Make this configuration in the file path
`myproject/ios/MYPROJECT.xcodeproj/project.pbxproj`
Happy Coding :)

**Comment by maxgertner** [comment]
Same. My solution was to shit on my computer, pee on it, then close the lid and bring it to Best Buy for them to fix.    Sent from my iPhoneOn Mar 1, 2023, at 10:01 PM, github-actions[bot] ***@***.***> wrote:﻿
This issue is waiting for author's feedback since 24 days. Please provide the requested feedback or this will be closed in 7 days.
