### ISSUE TITLE
Reload JS on Genymotion not works

### ISSUE THREAD

**Issue by barock19** [facebook/react-native#2866]
press F2 or ⌘-M doesn't show anything on Genymotion, any suggestion ?

**Comment by barock19** [comment]
sorry .. my bad, update genymotion to latest version solve the issue.

**Comment by Shadowlong** [comment]
@barock19 Hi  what is your Genymotion version? Mine is 2.5.2 but It doesn't work when I press command + M   many thanks...

**Comment by barock19** [comment]
@Shadowlong it's no need to update actually, all you need is just make sure that the `menu` button is shown, if not shown I won't bind. just drag the button group that contain `menu` button or resize the genymotion player so It's make the button visible.

dont be like this
<img width="495" alt="screen shot 2015-10-27 at 4 57 25 pm" src="https://cloud.githubusercontent.com/assets/474500/10754679/d72dd960-7ccb-11e5-98dc-f85e6174b839.png">

be like this
<img width="625" alt="screen shot 2015-10-27 at 4 54 15 pm" src="https://cloud.githubusercontent.com/assets/474500/10754686/de8fa292-7ccb-11e5-9989-654ae0f08ffa.png">

**Comment by Shadowlong** [comment]
WOW!  You are so awesome ~ Thanks a lot! It works!

**Comment by Shadowlong** [comment]
@barock19  Thank you very much again!

**Comment by deju** [comment]
@barock19 Great!!!

**Comment by SeyfertCode** [comment]
where is the "Reload JS" option?

**Comment by nicolasiensen** [comment]
"Reload JS" is not working on Nexus 5x emulator, I installed Nexus 5 and it's working perfectly

**Comment by nadpr** [comment]
I press ctrl+M , F2 , home but it's still doesn't work . I'm using samsung galaxy s6

**Comment by deju** [comment]
@nadpr  I recommond [frappe](http://getfrappe.com/)  if you use Mac OSX.

**Comment by nadpr** [comment]
@deju unfortunately , i'm using windows

**Comment by aseem2625** [comment]
Thanks @barock19 
People, if Command + M isn't working then follow as what he said. Just that dragging this button didn't work for me,
![image](https://cloud.githubusercontent.com/assets/6055628/14761660/66da005c-0985-11e6-8b34-f8e4a0a56c90.png)

So, I right clicked this black side panel where buttons are present and delselected the Widgets and there you go

![image](https://cloud.githubusercontent.com/assets/6055628/14761665/c0d4fb84-0985-11e6-9178-258f4643f2ee.png)

I've not my this button(3rd btn in image) present in the side bar which shows options when pressed command + M
![image](https://cloud.githubusercontent.com/assets/6055628/14761667/d523289a-0985-11e6-91d0-8f950b3e1538.png)

**Comment by jose920405** [comment]
R+R works for android emulators.

**Comment by mystikraz** [comment]
Press F1 in Genymotion and click on "Reload JS" incase of react-native app development.

Press F2 for Android Studio emulator.
