### ISSUE TITLE
Please fix https://reactnative.dev/blog/2018/05/07/using-typescript-with-react-native

### ISSUE THREAD

**Issue by kotpal** [facebook/react-native#28672]
Please fix the documentation

## Description
Outdated information is provided:
> react-native init MyAwesomeProject --template typescript

## React Native version:
4.7.0 (react-native info didn't work. Had to use react-native --version)

## Steps To Reproduce
1. Got to https://reactnative.dev/blog/2018/05/07/using-typescript-with-react-native
2. Follow the updated step to create react-native with TypeScript support. 
3. No project is created. Complains that 'typescript' template is not found

## Expected Results
Just to work and initialize the project

## Snack, code example, screenshot, or link to a repository:
![image](https://user-images.githubusercontent.com/7716123/79611678-fbc75c00-80af-11ea-8019-dcdcae0b8a4e.png)

**Comment by safaiyeh** [comment]
Hi @kotpal please create an issue in the docs repo here: https://github.com/facebook/react-native-website

In the meantime if you are having issues with the typescript template check out the community repo here: https://github.com/react-native-community/react-native-template-typescript
