### ISSUE TITLE
resizeMode center does not shrink local images on iOS release mode.

### ISSUE THREAD

**Issue by louiszawadzki** [facebook/react-native#28670]
## Description
When applying resizeMode `center` on an `Image` while setting a width and a height larger than the image's size, the image is displayed at its full width and height in Release scheme in iOS (i.e. in production).
It should be shrunk to fit the specified width and height as per the documentation and as it works when using the Debug scheme.

**EDIT** : The bug only appears when the image is locally stored, not when loaded by URL.

You can see screenshots at the bottom of the issue.

## React Native version:
```
System:
    OS: macOS 10.15.1
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 281.55 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
    Watchman: Not Found
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 23.0.1, 25.0.2, 25.0.3, 26.0.1, 27.0.3, 28.0.2, 28.0.3
      System Images: Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_192 - /usr/bin/javac
    Python: 2.7.16 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce

1. Create a new app
2. Add an image with resizeMode center, set a width and a height smaller than the image dimension
3. Open XCode
4. Go to Product > Edit scheme
5. Select "Release" scheme instead of debug
6. Add an appropriate provisioning profile to enable signing in release mode (I changed the bundle ID to be the one of my app then added my certificate)
7. Click on the "Run" button

## Expected Results

The image should be shrunk, just as if it was using resizeMode `contain`. 

## Snack, code example, screenshot, or link to a repository:
You can add this component in an existing React Native application: 

```
import React from "react";
import { StyleSheet, Image, View } from "react-native";

export default function App() {
  return (
    <View style={styles.container}>
      <Image
        source={require("./dale.jpg")}
        resizeMode="center"
        style={{ height: 200, width: 200 }}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
});
```

The image I used is https://3w8dlo2orf8y3crtc22sslbh-wpengine.netdna-ssl.com/wp-content/uploads/2020/04/Twin-Peaks-Large.jpg

_With debug scheme:_

<img width="461" alt="Capture d’écran 2020-04-17 à 17 54 35" src="https://user-images.githubusercontent.com/8973379/79589528-d4838580-80d5-11ea-9e2f-60c5af2abe2f.png">

_With release scheme:_

<img width="447" alt="Capture d’écran 2020-04-17 à 18 03 23" src="https://user-images.githubusercontent.com/8973379/79589522-d1889500-80d5-11ea-9f51-00948a421fcb.png">

**Comment by louiszawadzki** [comment]
If that helps anybody, I managed to reproduce the issue using the Debug Scheme by removing the "DEBUG=1" Preprocessor macro in the Build Settings of my project.
Now, I don't have any idea yet on what that does, but if anybody can clarify I'd be happy to go on :)

**Comment by cenzovit** [comment]
This problem seems to occur with resizeMode repeat as well.

**Comment by nandantal** [comment]
did you find any solution ?

**Comment by mistenkt** [comment]
Having the same issue with resizeMode repeat. In release mode the image is twice the scale as in dev.

**Comment by bekkii77** [comment]
I’m having the same issue with an image in repeat mode on RN 0.63.3.

**Comment by austintp** [comment]
Has anyone come up with an elegant work around for this issue?

**Comment by tufanlodos** [comment]
I’m having the same issue with an image in center mode on RN 0.64.0

**Comment by bekkii77** [comment]
Nothing elegant, I ended up rescaling my image so that the pattern was 2x smaller than I wanted it.  Then, when it got blown up in production, it was at least the right size. 🤷‍♀️

**Comment by lukasa1993** [comment]
why is this ignored ?

**Comment by hm-harshit** [comment]
![image](https://user-images.githubusercontent.com/34433141/122594109-377afe80-d084-11eb-9e2e-c290d7b19294.png)

same issue I am facing. I am Used `resizeMode={'center'}` on android its working fine, but on IOS image does not shrink!

**Comment by jb-asi** [comment]
Bumped. Still occurring.

**Comment by irshad-ali-md** [comment]
Any solution for this issue? I’m having the same issue on RN 0.61.5. Built on Xcode v12.5.1.

**Comment by Humad** [comment]
Having the same issue and eagerly waiting for an update

**Comment by thanhluantl2304** [comment]
Any update on this? I also faced this

**Comment by anhkieet** [comment]
I am facing the same issue. Can anyone check this? :(

**Comment by alexxsanchezm** [comment]
for ios - release I commented `resizeMode="center"` and seems to work, I guess there have to be a better way.

**Comment by shailesh896** [comment]
same issue with `resizeMode="center"` any fixes.

**Comment by Pratap22** [comment]
Any update on this? Anyone manage to fix this?

**Comment by jallusparta** [comment]
I worked around this to reach a target width by using `resizeMode="cover" `and calculating the height by the source images aspect ratio

```
    backgroundImage: {
        width: Dimensions.get('screen').width - 2 * 32,
        height: (Dimensions.get('screen').width - 2 * 32) * (848 / 1332), // Calculate the height with target width's aspect ratio
    }
```

**Comment by BadhanGanesh-HappyFox** [comment]
This needs to be addressed. Anyone had any luck with this?

**Comment by mweel1** [comment]
+1

**Comment by Louis-jk** [comment]
Is it resolved?

**Comment by TapsaleDipa** [comment]
Facing same issue, but after removing app from background and open again it showing me correct image.

**Comment by TapsaleDipa** [comment]
resizeMode: 'contain', width: 200, you can try this, it worked for me

**Comment by tonydatw** [comment]
This issue is still valid in 2023, i am experiencing the same, i ended up replacing the whole image with another one

**Comment by tniezurawski** [comment]
`resizeMode: 'repeat'` option stopped properly working for me when I upgraded from `react-native@0.64.3` to `@0.68.2`. It's a bit weird this issue gets zero interest. This problem should be common. Do people not use images and resizing? 🤔

**Comment by Bi0max** [comment]
have the same issue with resizeMode="center"

**Comment by futuretechlab** [comment]
This is still an issue. We are seeing image scaling issues. I works on the simulator for iOS however when deployed to a phone it shows the image incorrectly scaled up.

**Comment by hubastard** [comment]
Since this issue is not resolved yet, I've decided to try to see if I can find a fix for it.

So far I found a "workaround", local images using the `.webp` file format are working properly.

I'll continue to dig more.

**Comment by hubastard** [comment]
Here's the fix for it ^

**Comment by hubastard** [comment]
For those that do not want to wait for the fix to be merged. I've uploaded the patch-package patch here:
https://gist.github.com/hubastard/727eb71071d0822a19ad7f6859d3382e

**Comment by cuongtranduc** [comment]
> For those that do not want to wait for the fix to be merged. I've uploaded the patch-package patch here: https://gist.github.com/hubastard/727eb71071d0822a19ad7f6859d3382e

I can't apply this patch on version 0.71.10. "  This error was caused because patch-package cannot apply the following patch file". 
I am the only one get the error?
