### ISSUE TITLE
enableHermes : true   build fail  

### ISSUE THREAD

**Issue by skyline1314** [facebook/react-native#28683]
## Description
enableHermes : true   

FAILURE: Build failed with an exception.

* Where:
Script 'D:\rndemo\hermer\node_modules\react-native\react.gradle' line: 165

* What went wrong:
Execution failed for task ':app:bundleReleaseJsAndAssets'.
> Process 'command 'cmd'' finished with non-zero exit value -1073741515

## React Native version:
0.62.2

![905033C8-B2B2-4554-9C4C-C749BD11B369](https://user-images.githubusercontent.com/18283994/79636343-85a72000-81a9-11ea-92de-817f3c349976.png)
![B4C3590C-9E00-44c4-A9E6-B4346A04C85C](https://user-images.githubusercontent.com/18283994/79636365-bab37280-81a9-11ea-9d71-a2f32dbab08b.png)
![8696AF39-67F6-4d0e-9C17-DA6824A8EBF3](https://user-images.githubusercontent.com/18283994/79636371-c30bad80-81a9-11ea-839c-919f0dab30fb.png)

![3EA4E4E5-2C9A-4859-891A-EF77FADB4465](https://user-images.githubusercontent.com/18283994/79636442-36152400-81aa-11ea-8073-82e7d25d462d.png)

**Comment by safaiyeh** [comment]
Hi @skyline1314 could you provide your environment info and a small repro (or at least verify this happens on a clean template).

Thanks!

**Comment by hridoy43** [comment]
> ## Description
> enableHermes : true
> 
> FAILURE: Build failed with an exception.
> 
> * Where:
>   Script 'D:\rndemo\hermer\node_modules\react-native\react.gradle' line: 165
> * What went wrong:
>   Execution failed for task ':app:bundleReleaseJsAndAssets'.
> 
> > Process 'command 'cmd'' finished with non-zero exit value -1073741515
> 
> ## React Native version:
> 0.62.2
> 
> ![905033C8-B2B2-4554-9C4C-C749BD11B369](https://user-images.githubusercontent.com/18283994/79636343-85a72000-81a9-11ea-92de-817f3c349976.png)
> ![B4C3590C-9E00-44c4-A9E6-B4346A04C85C](https://user-images.githubusercontent.com/18283994/79636365-bab37280-81a9-11ea-9d71-a2f32dbab08b.png)
> ![8696AF39-67F6-4d0e-9C17-DA6824A8EBF3](https://user-images.githubusercontent.com/18283994/79636371-c30bad80-81a9-11ea-839c-919f0dab30fb.png)
> 
> ![3EA4E4E5-2C9A-4859-891A-EF77FADB4465](https://user-images.githubusercontent.com/18283994/79636442-36152400-81aa-11ea-8073-82e7d25d462d.png)

Same Issue on windows 10... Don't know how to fix :(

**Comment by hridoy43** [comment]
@skyline1314 did you fix that?

**Comment by shirleywsywong** [comment]
Try running `node_modules\hermes-engine\win64-bin\hermes.exe`, it should run without errors.
If it gives you an error on "missing VCRUNTIME140_1.dll", you should install https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

**Comment by AlexandrMesh** [comment]
I have same issue, who did fix it?

**Comment by AlexandrMesh** [comment]
> @skyline1314 did you fix that?

Did you fix it?

**Comment by AlexandrMesh** [comment]
I've solved this problem. I've installed Visual Studio 2019 community version.

**FYI**: `VCRUNTIME140_1.dll` file should locate in `Windows/System32` folder and you can download and paste manually this file into this folder or you should install Visual Studio 2019.
