### ISSUE TITLE
Build additional target in Xcode: Error 'React/RCTBridgeDelegate.h' file not found in AppDelegate.h

### ISSUE THREAD

**Issue by the-smart-home-maker** [facebook/react-native#28685]
## Description
Building my React Native app in Xcode 11.3.1 gives me the error:

> "React/RCTBridgeDelegate.h" file not found in AppDelegate.h

only when building an additional target (Release Scheme) directly in Xcode. When building the standard development target, I have no problems.

## React Native version:

System:
    OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
    Memory: 230.99 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 13.8.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.2 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.4 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  Languages:
    Java: 12.0.2 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.9.0 => 16.9.0 
    react-native: ^0.62.1 => 0.62.1 
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
I have a React Native app with a Watch companion app. The app is equipped with different additional React Native modules. The app runs smoothly when building it in the standard build target (Development scheme) via React Native cli (react-native run-ios) as well as when building the standard build target (Development scheme) directly in Xcode. Already a while ago, I have created a duplicate set of targets in Xcode (Release scheme). Building the duplicate target for the iOS app in Xcode bundles the React Native code and images as an additional build phase to be able to deploy the app on an iPhone not depending on the development server. Building this target worked out smoothly as well for a long time.

Now all of a sudden since some days when I want to build my duplicate target (Release scheme) in Xcode I am getting the error

> "React/RCTBridgeDelegate.h" file not found in AppDelegate.h

I can still build the standard build target (Development scheme) via console react-native run-ios and also directly in Xcode with no problems. I not sure what caused this issue now, the only change to my config I have made some days ago is that I have added some additional modules to my React Native app, e.g. react-native-keychain and react-native-push-notification. Both have been configured correctly as I would assume, also pods have been installed as necessary and I can see that those modules also work well when building the development target, so I don't think that adding those additional modules caused the issue.

I have read all issues here and on StackOverflow describing this problem and have already tried all of the following solution proposals with no effect unfortunately:

1.  Make sure that "Parallelize builds" is deactivated in scheme (had already done that by the time when duplicating the development target creating a release target). Also make sure that target "React" is listed above the app build target in "Build" option of the scheme.

1.  Deintegrate pods and re-install pods

1.  List additional target in the Podfile with "inherit! :search_paths", again deintegrate and re-install pods --> gives me a warning that the additional target in the Podfile "overrides the HEADER_SEARCH_PATHS build setting"

1.  Clean the build and repeat step 2

1.  Add the React path directly in the HEADER_SEARCH_PATHS in target build settings --> gives me linker errors

1. Explicitly build target "React" first - Clean Build, Build target "React", then build my release target

## Expected Results
It should just build without problems

## Snack, code example, screenshot, or link to a repository:
See also the [StackOverflow issue](https://stackoverflow.com/questions/61200789/build-additional-target-in-xcode-error-react-rctbridgedelegate-h-file-not-fou) I have created some days ago with no responses

**Comment by safaiyeh** [comment]
Hi @the-smart-home-maker could you provide a minimal repro so we can investigate?

**Comment by the-smart-home-maker** [comment]
I am OK to close it even though there is no solution. I do not know which code to post for repro - I guess it would be necessary to post the whole project. Therefore we should close it. It's definitely an issue that I do only have on one specific project and this project must have somewhere a bug which I still can't find, unfortunately...
