### ISSUE TITLE
npx react-native run-ios fail 

### ISSUE THREAD

**Issue by skykingit** [facebook/react-native#28684]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
i create a new project by "npx react-native init project"
after successed,i follow the tips to run app in MAC's TERMINAL
but io failed with the reason below 
"error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65"

**But the weirdest thing 
when i run "yarn ios" in VS Code TERMINAL ,it successed

## React Native version:
Run `react-native info` in your terminal and copy the results here.
System:
    OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Memory: 424.00 MB / 10.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.13.0 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.5.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6308749
    Xcode: 11.4/11E146 - /usr/bin/xcodebuild
  Languages:
    Java: 12.0.1 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by safaiyeh** [comment]
Hi @skykingit this is a duplicate of https://github.com/facebook/react-native/issues/25240

Could you verify if some of the work arounds they provide are helpful?
