### ISSUE TITLE
KeyboardAvoidingView misplaces absolutely positioned elements

### ISSUE THREAD

**Issue by vmaark** [facebook/react-native#28697]
## Description
Having an element with `position: absolute` in a `KeyboardAvoidingView` with `behavior="padding` and `keyboardVerticalOffset` greater than `0`, moves the element permanently (even after closing the keyboard).

## React Native version:
```
System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
    Memory: 727.96 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.21.1 - ~/.yarn/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
    Watchman: 4.7.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 23.0.1, 25.0.2, 26.0.1, 27.0.3, 28.0.3
      System Images: a...google_apis | Google APIs Intel x86 Atom Sys...
      Android NDK: 17.0.4754217
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_102 - /usr/bin/javac
    Python: 2.7.17 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Run app
2. Tap on text input
3. Close text input

## Expected Results
After closing the keyboard the element should be at its original position.

## Snack, code example, screenshot, or link to a repository:
link to snack:
https://snack.expo.io/@vmark/keyboardavoiding-absolute-positioning-bug
link to repo:
https://github.com/vujevits/KeyboardAvoidingAbsoluteExample

## Screenshots
<img width="200" alt="Screenshot 2020-04-20 at 15 33 04" src="https://user-images.githubusercontent.com/2270661/79757672-b22f7900-831c-11ea-95ba-b33e4814bda4.png">
<img width="200" alt="Screenshot 2020-04-20 at 15 33 14" src="https://user-images.githubusercontent.com/2270661/79757683-b360a600-831c-11ea-8c69-136405e7d9ce.png">
<img width="200" alt="Screenshot 2020-04-20 at 15 33 20" src="https://user-images.githubusercontent.com/2270661/79757687-b491d300-831c-11ea-8d30-2fdda6d7f919.png">

**Comment by randytorres** [comment]
@vujevits Did you find a solution?

**Comment by vujevits** [comment]
@randytorres I'm afraid I had to get rid of the absolute positioning.

**Comment by a-eid** [comment]
@vujevits remove `{flex: 1}` from your `KeyboardAvoidingView` so that it take only as much space as it's children. that should fix it right up.

**Comment by a-eid** [comment]
why have you added `keyboardVerticalOffset` ? 
this works as expected.
 
```jsx
 <KeyboardAvoidingView
      behavior="padding"
      style={styles.container}
      contentContainerStyle={styles.container}
      keyboardVerticalOffset={0}
    >
      <SafeAreaView style={styles.container}>
        <View style={styles.container}>
          <TextInput style={styles.paragraph} placeholder="Click here" />
          <View style={styles.button} /></View>
      </SafeAreaView>
    </KeyboardAvoidingView>
```

**Comment by a-eid** [comment]
if you are using positioning as behavior your `KeyboardAvoidingView` only as much space as it actually needs, so you should not have `{flex: 1}`

**Comment by vujevits** [comment]
@a-eid not sure what are you suggesting, the bug report is about using specific settings, in which case the absolutely positioned element is permanently moved to another location, even after closing the keyboard.

**Comment by AndresdoSantos** [comment]
Hello guys, I solved this by taking the 'event' and checking if the keyboard was 'visible' or 'hidden', put it in a state and did the logic.

```
const [keyboard, setKeyboard] = useState(Boolean);

  useEffect(() => {
    Keyboard.addListener('keyboardDidShow', _keyboardDidShow);
    Keyboard.addListener('keyboardDidHide', _keyboardDidHide);

    return () => {
      Keyboard.removeListener('keyboardDidShow', _keyboardDidShow);
      Keyboard.addListener('keyboardDidHide', _keyboardDidHide);
    };
  }, []);

  const _keyboardDidShow = () => {
    setKeyboard(true);
  };

  const _keyboardDidHide = () => {
    setKeyboard(false);
  };
```

and...

``` 
{!keyboard && (
    <View style={{ position: 'absolute', bottom: 0, height: 60 }} >
      <Text style={{ alignSelf: 'center' }} >Criar uma conta</Text>
    </View>
  )}
```

To be honest, I didn't like the solution 100% because of the size of adding code for something so 'simple', but that's what I did.

**Comment by andrisole92** [comment]
This is total shit my friends! I can't believe it's still there!

**Comment by ikeller96** [comment]
This is still an issue for me as well. Has there been any update on this? I need elements to be absolutely positioned on my screen but I also need to use the KeyboardAvoidingView.

**Comment by shreyas-jadhav** [comment]
any updates?

**Comment by pankti-0627** [comment]
any updates ?

**Comment by tibbe** [comment]
I'm suffering from this as well. I feel like I spend about 50% of my RN dev time dealing with the keyboard behavior (covering the wrong things, not hiding when you click on certain things, etc).

**Comment by owdji** [comment]
Hey ! I had the same problem, I was  using `keyboardAvoidingView `with `absolute` position and putting it at the bottom of the screen.

This  code was not working :  
`<KeyboardAvoidingView 
      style={{    
        position: 'absolute',
        top: WINDOWHEIGHT - 100, 
...
`

But this code is working : 
`      <KeyboardAvoidingView 
      style={{    
        position: 'absolute',
        left: 0, right: 0, bottom: 0,
...`

**Comment by chase-robbins** [comment]
experiencing the same issue

**Comment by merganon** [comment]
Same problem here

Make sure to add a 👍 reaction to the issue so the RN team can filter and prioritize this

**Comment by rdick** [comment]
FIXED IT!!! WOOOO!

This will automatically move the whole screen up 
    ```
<KeyboardAvoidingView
      keyboardVerticalOffset={headerHeight}
      style={{position: 'absolute', width: '100%', bottom: 0, flex: 1}}
      behavior={'position'}
      enabled>
     CONTENT
</KeyboardAvoidingView>
```

**Comment by senrymori** [comment]
i found a solution for myself. Since I have many inputs, I use ScrollView + KeyboardAvoidingView, but outside of these components, I have a button that I want to hide when the keyboard is open

none of the options above solved my problem perfectly, but everything turned out to be much simpler, I just added on top of the flex button: 1
```javascript
<ScrollView>
        <KeyboardAvoidingView
          style={[{marginBottom: Insets.bottom}, styles.ph27]}
          behavior={Platform.OS === 'ios' ? 'padding' : 'height'}>
          // My inputs
        </KeyboardAvoidingView>
</ScrollView>
```
```javascript
<View style={[flex: 1, styles]}>
        <ButtonUI
          style={[{marginBottom: Insets.bottom}, styles.mb20]}
          text={t(LangText.buttonsReady)}
          onPress={() => {}}
          rightIcon={<CheckIcon color={ColorsUI.white} />}
        />
</View>
```

!!!!!!!! READ THIS !!!!!!!!
when you don't have many inputs this solution won't help, but in those cases you may not need to use KeyboardView at all as the keyboard won't overlap your inputs

**Comment by nadiln** [comment]
I found a solution using flex layout for this issue (using tailwind for react native)

 <View className="flex-1 flex-col w-full justify-between items-center">
            <View className=" px-6 mt-6 w-full ">
              <View>
                <Controller
                  control={control}
                  name="firstname"
                  render={({ field: { value, onChange }, fieldState: { error } }) => (
                    <>
                      <SomeTextInput />
                     
                    </>
                  )}
                />
              </View>
              <View className="mt-6">
                <Controller
                  control={control}
                  name="lastname"
                  render={({ field: { value, onChange } }) => (
                    <>
                      <SomeTextInput />
                    </>
                  )}
                />
              </View>
            </View>
            <View className=" mt-6 w-full">
              <Button >
                Confirm
              </Button>
            </View>
          </View>

**Comment by Linuhusainnk** [comment]
Any updates on this issue?
![android](https://github.com/facebook/react-native/assets/80395697/32c6c871-a8c3-4cca-b51b-dc13ccd74326)


props tried
keyboardVerticalOffset:
    Platform.OS === 'ios' ? 90 :75,
  behavior: Platform.OS === 'ios' ? 'padding' : 'height',
