### ISSUE TITLE
Android: Overlap TouchableOpacity and View behave differently when there is backgroundColor style 

### ISSUE THREAD

**Issue by gie3d** [facebook/react-native#28694]
## Description
I created 2 Views that display overlaps to each others. The top and the bottom

![2563-04-20 at 16 31](https://user-images.githubusercontent.com/1977772/79736831-9d56e380-8324-11ea-80e6-b0688fdab060.png)

When the bottom view background wasn't configured. It responded to the press event correctly. Let's say when I press on the overlap zone, it showed that the bottom one had been pressed

However, when I configured the bottom view backgroundColor. When I pressed on the overlap zone, on `Android`, it responded as I pressed on the top view which I think it's incorrect. (iOS it responded correctly that the bottom was pressed)

![2563-04-20 at 16 37](https://user-images.githubusercontent.com/1977772/79737254-3b4aae00-8325-11ea-960d-e4b0ef18cf24.png)

## React Native version:
System:
    OS: macOS 10.15.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 605.80 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.0 - ~/.nvm/versions/node/v12.16.0/bin/node
    Yarn: 1.22.0 - ~/.nvm/versions/node/v12.16.0/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.0/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  npmPackages:
    react: ~16.9.0 => 16.9.0 
    react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4 
  npmGlobalPackages:
    react-native-cli: 2.0.1

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.
Here is an example component
```js
const OverlapseTouchExample = ({backgroundColor}) => {
  const [pressedBox, setPressefBox] = React.useState('')
  return (
    <View>
      <Text>{pressedBox} pressed</Text>
      <TouchableOpacity style={[styles.box, {backgroundColor: 'blue'}]} onPress={() => setPressefBox('top')} />
      <View style={backgroundColor ? { backgroundColor: 'orange' } : null}>
        <View style={{marginTop: -75}}>
          <TouchableOpacity style={[styles.boxBottom, backgroundColor ? { backgroundColor: 'green '} : null]} onPress={() => setPressefBox('bottom')} />
        </View>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  box: {
    width: 150,
    height: 150,
    borderWidth: 1,
  },
  boxBottom: {
    width: 120,
    height: 200,
    borderWidth: 1,
  }
})
```

The problem found when set the backgroundColor to true
`<OverlapseTouchExample backgroundColor={true} />`

## Expected Results
It should response to the press event the same whether or not backgroundColor is configured or not.

## Snack, code example, screenshot, or link to a repository:
https://snack.expo.io/@gie3d/9b6c32

**Comment by fabriziobertoglio1987** [comment]
I reproduced the issue in the following example 

```javascript
import React, { useState } from 'react';
import { Text, View, StyleSheet, TouchableOpacity, ScrollView } from 'react-native';

export default function App() {
  const [pressedBox, setPressefBox] = React.useState('')
  return (
    <React.Fragment>
      <TouchableOpacity style={styles.box} onPress={() => setPressefBox('top')} />
      <View accessible={false}>
        <TouchableOpacity style={styles.boxBottom} onPress={() => setPressefBox('bottom')} />
      </View>
    </React.Fragment>
  );
}

const styles = StyleSheet.create({
  box: {
    width: 150,
    height: 150,
    borderWidth: 1,
  },
  boxBottom: {
    width: 120,
    height: 200,
    borderWidth: 1,
    marginTop: -75,
  }
})
```
Top Square pressability
![Screenshot from 2020-05-28 17-13-43](https://user-images.githubusercontent.com/24992535/83159881-cbd79380-a106-11ea-8a89-c46dd6f7fe34.png)

Bottom Square pressability
![Screenshot from 2020-05-28 17-13-54](https://user-images.githubusercontent.com/24992535/83159907-d2fea180-a106-11ea-927f-aa762895022c.png)

**Comment by gie3d** [comment]
Many thanks to your investigation and effort. Even though I don’t have much knowledge in Android layout.

For the time being, I should go with the absolute position.

**Comment by fabriziobertoglio1987** [comment]
https://github.com/facebook/react-native/issues/27333#issuecomment-657566412
