### ISSUE TITLE
Calling normalize('NFKD') on unicode strings crashes the js engine

### ISSUE THREAD

**Issue by Ajkcki** [facebook/react-native#28698]
As stated in the title, here is an example 
```
let x ='的 一 是 在 不 了 有 和 人 这 中 大'
x.normalize('NFKD')  //<---------------crash the js engine
```
Calling with params NFC and NFD are OK, neither NFKC nor NFKD works 

My environement
"react": "16.9.0",
 "react-native": "0.61.5",

**Comment by andordavoti** [comment]
Having the same issue... Works fine in production, but crashes on android.

**Comment by alexlevy0** [comment]
@andordavoti       
https://github.com/walling/unorm 👍
