### ISSUE TITLE
Error: react-native run-android

### ISSUE THREAD

**Issue by tusharmutreja200** [facebook/react-native#28692]
## Description
I have created the app new app and Initially, it was working fine now I got this error

## React Native version:
System:
    OS: Linux 4.4 Ubuntu 16.04.1 LTS (Xenial Xerus)
    CPU: (4) x64 Intel(R) Core(TM) i3-4010U CPU @ 1.70GHz
    Memory: 4.29 GB / 7.68 GB
    Shell: 4.3.48 - /bin/bash
  Binaries:
    Node: 10.18.1 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  IDEs:
    Android Studio: 3.1 AI-173.4670197
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5

## Error in terminal:
error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:preDebugBuild'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.facebook.react:react-native:+.
     Required by:
         project :app
      > Failed to list versions for com.facebook.react:react-native.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/facebook/react/react-native/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/com/facebook/react/react-native/maven-metadata.xml'.
               > Connect to jcenter.bintray.com:443 [jcenter.bintray.com/52.26.64.218, jcenter.bintray.com/52.11.170.179] failed: connect timed out

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 36s

    at checkExecSyncError (child_process.js:629:11)
    at execFileSync (child_process.js:647:13)
    at runOnAllDevices (/home/chirag/worldwar2/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:94:39)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by 824420263** [comment]
Environment:
  OS: macOS 10.15.3
  Node: 14.0.0
  Yarn: 1.22.4
  npm: 6.14.4
  Watchman: 4.9.0
  Xcode: Xcode 11.4 Build version 11E146
  Android Studio: 3.6 AI-192.7142.36.36.6392135

Packages: (wanted => installed)
  react: 16.9.0 => 16.9.0
  react-native: ^0.55.4 => 0.55.4

![image](https://user-images.githubusercontent.com/7644287/80169434-f7eb8a80-8617-11ea-8ba5-13040e35e3e7.png)

**Comment by fabriziobertoglio1987** [comment]
I suggest you to use expo
