### ISSUE TITLE
borderStyle="dashed" not work with borderBottom it only works with full border.

### ISSUE THREAD

**Issue by EhsanSarshar** [facebook/react-native#28695]
## React Native version:
System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
    Memory: 227.65 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.13.0 - /usr/local/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.13.7 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 25, 27, 28, 29
      Build Tools: 27.0.3, 28.0.3, 29.0.2
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3.1/11C505 - /usr/bin/xcodebuild
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^16.11.0 => 16.11.0 
    react-native: ^0.62.2 => 0.62.2 
  npmGlobalPackages:

```
export default () => (
      
     <View  style={{borderBottomWidth: 10, borderStyle: "dashed", borderRadius: 1}}/>

)
```

Snack 
https://snack.expo.io/J6IlJ7LT3

**Comment by Gazizbek** [comment]
You can set style like below for only bottom border:
borderRadius: 1,
borderWidth: 10,
borderLeftWidth: 0,
borderRightWidth: 0,
borderTopWidth: 0,
borderStyle: 'dashed'

**Comment by fabriziobertoglio1987** [comment]
https://github.com/facebook/react-native/pull/29099

**Comment by EhsanSarshar** [comment]
@fabriziobertoglio1987 tnx alot
can you plz fix the issue to pass all the tests

**Comment by fabriziobertoglio1987** [comment]
> Please, is it possible to merge this PR in the next version ?

To answer the question of when the pr https://github.com/facebook/react-native/pull/29099 which fixes this issue will be released in the next version of React Native, I suggest you to follow the discussions at https://github.com/react-native-community/releases/issues by subscribing to those threads. The process of releasing a new version with a bug fix is the following:

- an Issue is opened in facebook/react-native
- a contributor writes a Pull Request to fix/close the react-native Issue
- The Pull Request is merged in Master
- For each realease (the upcoming one is 0.64.1) there will be a separate discussion on https://github.com/react-native-community/releases/issues where anyone can request a commit to be cherrypicked from master. The link need to be from the a **commit** from master (for ex. https://github.com/facebook/react-native/pull/29157#issuecomment-651430945) and not a Pull Request not yet merged in master :peace_symbol: :pray:

**Comment by NibyP** [comment]
Is this issue fixed? I got the same problem on React Native 0.65 version. None of the above solution worked.
