### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'props.getItem') on RN 0.61.x

### ISSUE THREAD

**Issue by georgecirilo** [facebook/react-native#28693]
#27431 
## Description
Flatlist is failing to work.

## React Native version:
System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
    Memory: 37.83 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.16.1 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 27, 28, 29
      Build Tools: 27.0.3, 28.0.3, 29.0.2
      System Images: android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.11.0 => 16.11.0 
    react-native: ^0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-camera: 3.3.0
    react-native-cli: 2.0.1
    react-native-fbsdk: 1.0.2
    react-native-fs: 2.14.1
    react-native-geolocation-service: 3.1.0
    react-native-gesture-handler: 1.4.1
    react-native-image-picker: 1.1.0
    react-native-maps: 0.25.0
    react-native-svg: 9.8.1
    react-native-vector-icons: 6.6.0
    react-native: 0.61.5

## Steps To Reproduce
Rendering any flatlist with data 

## Expected Results
Render successful which is not.

## Extra information

Tracking down the issue it seems that the initialization of these variables is failing:

///// React-Native 0.61.5 code - actual in use:

```
.....
_checkProps(props: Props<ItemT>) {
    const {
      getItem,
      getItemCount,
      horizontal,
      numColumns,
      columnWrapperStyle,
      onViewableItemsChanged,
      viewabilityConfigCallbackPairs,
    } = props;
    invariant(
      !getItem && !getItemCount,
      'FlatList does not support custom data formats.',
    );
    if (numColumns > 1) {
      invariant(!horizontal, 'numColumns does not support horizontal.');
    } else {
      invariant(
        !columnWrapperStyle,
        'columnWrapperStyle not supported for single column lists',
      );
    }
    invariant(
      !(onViewableItemsChanged && viewabilityConfigCallbackPairs),
      'FlatList does not support setting both onViewableItemsChanged and ' +
        'viewabilityConfigCallbackPairs.',
    );
  }
.....
```
Comparing code with 0.62.x, they seem to know about this but still it does not work properly.

//////// 0.62.x code below - compared code:

```
....
 _checkProps(props: Props<ItemT>) {
    const {
      // $FlowFixMe this prop doesn't exist, is only used for an invariant
      getItem,
      // $FlowFixMe this prop doesn't exist, is only used for an invariant
      getItemCount,
      horizontal,
      numColumns,
      columnWrapperStyle,
      onViewableItemsChanged,
      viewabilityConfigCallbackPairs,
    } = props;
....
```

![image](https://user-images.githubusercontent.com/15729832/79701706-93c27280-8275-11ea-919c-cb93456944cc.png)

**Comment by safaiyeh** [comment]
Hi @georgecirilo could you share your usage of FlatList in a Snack. It would be helpful to investigate your issue.

**Comment by georgecirilo** [comment]
Hello, this seems to be an issue with mobX state tree integration more than a rn version issue. 

Things went back to normal when deleted "mobx" preset from .babel file that is created upon mobx installation. I'll leave the reference link, bare in mind that this issue keeps coming back:

https://github.com/facebook/react-native/issues/24421#issuecomment-482600467


Thanks!
