### ISSUE TITLE
Visual Studio Code reporting typescript error after react-native init myTestApp

### ISSUE THREAD

**Issue by ChrisHarveyHub** [facebook/react-native#28699]
## Description
Please provide a clear and concise description of what the bug is. Include screenshots if needed.
After running "react-native init myTestApp" in the terminal I get a typescript error in Visual Studio code for the very beginning of the App.js file.
![Screen Shot 2020-04-20 at 12 03 53 PM](https://user-images.githubusercontent.com/14862980/79789473-18a59e80-82ff-11ea-9d40-7cc1ddfb09bb.png)
I may have done something without realizing but an init command should return compilable code every time.

## React Native version:
Run `react-native info` in your terminal and copy the results here.
System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 469.98 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.1 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 11.4/11E146 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.2 - /usr/bin/javac
    Python: 2.7.16 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.
1. run "react-native init {project name here}"
2. open project in Visual Studio Code
3. See error in App.js

## Expected Results
Describe what you expected to happen.
I expected Visual Studio Code to recognize and not report errors on any files.

I would provide code but this isn't really a but with the code but more it's method of deployment.

**Comment by safaiyeh** [comment]
@ChrisHarveyHub I believe that is because the ts plugin is mistaking the flow type as a TypeScript type. The fix would be to remove flow integration as it comes by default via the template.

**Comment by safaiyeh** [comment]
Let me know if that helps!

**Comment by xcaluca** [comment]
> @ChrisHarveyHub I believe that is because the ts plugin is mistaking the flow type as a TypeScript type. The fix would be to remove flow integration as it comes by default via the template.

I am with the same problem here and I don't know how to fix this. Can you explain to me how to remove the flow?

**Comment by safaiyeh** [comment]
> > @ChrisHarveyHub I believe that is because the ts plugin is mistaking the flow type as a TypeScript type. The fix would be to remove flow integration as it comes by default via the template.
> 
> I am with the same problem here and I don't know how to fix this. Can you explain to me how to remove the flow?

Remove the // @flow comment at the top of the file and remove the type
