### ISSUE TITLE
TextInput not visible when it's height greater than some value

### ISSUE THREAD

**Issue by msbadar** [facebook/react-native#28701]
## Description
Text input becomes invincible when it's height is a bigger value (mostly >= window.hiegth ). Tested in Android.  It's working normal for lower values.

## Code to reproduce the issue
```
import { AppRegistry } from 'react-native';
import { name as appName } from './app.json';
import React from 'react';
import {
    SafeAreaView,
    ScrollView,
    Dimensions,
    TextInput,
} from 'react-native';

const App = () => (
    <SafeAreaView>
        <ScrollView contentInsetAdjustmentBehavior="automatic">
            <TextInput
                style={{
                    backgroundColor: "red",
                    width: Dimensions.get('window').width,
                    height: 2 * Dimensions.get('window').height,
                }}
            />
        </ScrollView>
    </SafeAreaView>
);

AppRegistry.registerComponent(appName, () => App);
````

## React Native version:
```
react": "16.11.0",
react-native": "0.62.2"
```

## Steps To Reproduce

1. react-native init <project-name>
2. update above code and run

## Expected Results
TextInput should not hide when it reaches to some limit

**Comment by vonovak** [comment]
Let me just add that this is not reproducible on all devices / versions. I cannot reproduce it on my android 10 device but can reproduce on android 8 device and emulator.

Here's a snack where you can observe the problem: https://snack.expo.io/@vonovak/rn-28701

- the issue is present with multiline textinput too, where this indeed is a problem
- the trouble seems to be in wrapping the textinput in ScrollView. Without ScrollView the issue is not there, so perhaps this is a ScrollView problem, not a TextInput one. 
- I can also reproduce this in RN tester, I reproduced this on master with bf5f3c6a79fba839225576da889d3b7f835a19f6

**Comment by msuma268** [comment]
Still facing the same issue

**Comment by tarouboy** [comment]
I have tested on Android 5-10, only happens on Android 8 and it is easy to reproduce.
Please re-open this issue.

**Comment by tarouboy** [comment]
> Let me just add that this is not reproducible on all devices / versions. I cannot reproduce it on my android 10 device but can reproduce on android 8 device and emulator.
> 
> Here's a snack where you can observe the problem: https://snack.expo.io/@vonovak/rn-28701
> 
> * note that the textinput is still mounted, you can interact with it, just not see it
> * the issue is present with multiline textinput too (if you fill it up with enough text), where this indeed is a problem
> * the trouble seems to be in wrapping the textinput in ScrollView. Without ScrollView the issue is not there, so perhaps this is a ScrollView problem, not a TextInput one. However, if I just change TextInput to View, it works; so some interplay between TextInput and ScrollView is causing this
> * I can also reproduce this on master, I tried it with RNTester on [bf5f3c6](https://github.com/facebook/react-native/commit/bf5f3c6a79fba839225576da889d3b7f835a19f6)

@vonovak Would you please re-open this issue?

**Comment by Caundy** [comment]
Can verify this issue is present on RN 61.2 when running on an android 8 device. 
Setting TextInput's maxHeight to screen height or less seems to "fix" it

**Comment by tarouboy** [comment]
I've created a $100 bounty for this issue. Please submit a PR if you could help.
https://issuehunt.io/r/tarouboy/react-native/issues/1
