### ISSUE TITLE
Can't run the app on Android 4.4.4 since I am not able to open 'Dev Settings'

### ISSUE THREAD

**Issue by oren** [facebook/react-native#2871]
OS: Ubuntu 15.04
node.js: v2.5.0
react-native-cli@0.1.4
Phone: Android 4.4.4. Moto X. HW version: p30

I am following the [quick start tutorial](https://facebook.github.io/react-native/docs/tutorial.html) and can't run the app on my device.
Since my phone is 4.4.4, I can't use this command `adb reverse tcp:8081 tcp:8081` so I try to 'Configure device to connect to the dev server via Wi-Fi' as described [here](https://facebook.github.io/react-native/docs/running-on-device-android.html) but my phone doesn't do anything when I shake it.

Thanks!

**Comment by mjetek** [comment]
Did the app install on your device without any problems, what happen when you start it, can you see red screen with message saying that it's unable to download JS bundle?

**Comment by oren** [comment]
Yeah, i see a red screen tells me 'unable to download JS bundle. Did you forget to start the development server or connect your device'.

**Comment by ide** [comment]
You can set the key "debug_http_host" in your SharedPreferences object as a workaround.

**Comment by oren** [comment]
since i am new to react and react-native, i am not sure what exactly the change i need to make or where should i make it. 

Here is the output of grepping for that string:
```
AwesomeProject/android ag debug_http_host

app/build/intermediates/exploded-aar/com.facebook.react/react-native/0.11.0/res/xml/preferences.xml
34:        android:key="debug_http_host"

app/build/intermediates/res/merged/debug/xml/preferences.xml
34:        android:key="debug_http_host"
```

**Comment by ide** [comment]
grep the android code to see how that preferences key is used.

**Comment by oren** [comment]
I assume you mean to grep the react-native repo. I'll do that and report my findings.

**Comment by oren** [comment]
grepping react-native codebase gave me 3 files:

1. ReactAndroid/src/main/java/com/facebook/react/devsupport/DevServerHelper.java 
1. ReactAndroid/src/main/java/com/facebook/react/devsupport/DevInternalSettings.java
1. ReactAndroid/src/main/res/devsupport/xml/preferences.xml

The first one had an interesting comment:
```
One can use 'debug_http_host' shared preferences key to provide a host name for the debug server.
If the setting is empty we support and detect two basic configuration that works well for android
emulators connectiong to debug server running on emulator's host:
 - Android stock emulator with standard non-configurable local loopback alias: 10.0.2.2,
 - Genymotion emulator with default settings: 10.0.3.2
```

It looks like this key should have a host name for some kind of debug server. is my laptop function as this debug server? if that's the case should I use tool like [localtunnel](https://github.com/localtunnel/localtunnel) or [ngrok](https://github.com/bubenshchykov/ngrok)?
Also, how do I set that key? is it an environment variable?

**Comment by buhe** [comment]
see https://github.com/facebook/react-native/issues/2754

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/cant-run-the-app-on-android-444-since-i-am-not-able-to-open-dev-settings

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.

**Comment by RameshSain** [comment]
Try this :-

https://github.com/facebook/react-native/issues/15594
