### ISSUE TITLE
onFocus does not show keyboard on android device  for TextInput when debugger is running

### ISSUE THREAD

**Issue by vivekmahato26** [facebook/react-native#28715]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
While debugger is running. If I tap on textInput feild cursor blinks once then disappears. Mobile device keyboard is not shown at all but the same code works fine when the debugger is not running.
I am having same issue with button press and touchable components.
Only onPress prop working is with Text field
## React Native version:
react-native-cli: 2.0.1
react-native: 0.62.2

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. create a simple textinput inside a view. 
2. try entering something while the debugger is running 

## Expected Results
One should be able to input in textinput weather or not the debugger is running.

## Snack, code example, screenshot, or link to a repository:
https://github.com/vivekmahato26/open-source-mobile
try entering anything in the search field or in the form fields while debugger is running

**Comment by apbuteau** [comment]
I'm hitting this issue as well.  Any update?

**Comment by yozenou** [comment]
Hello, i get the same issue, do you find from where the problem comes ?

Thanks

**Comment by alejocor** [comment]
Hello, same issue with
react-native: 0.62.2

**Comment by sparcbr** [comment]
Same here. 

Android 9, RN 0.62.2

**Comment by ferbeb** [comment]
Same, RN 0.62.2 on Android 10

**Comment by wanderlust252** [comment]
same issue.

**Comment by kimmimy** [comment]
I updated  FLIPPER_VERSION=0.49.0 and now I get this behavior

**Comment by daxaxelrod** [comment]
Having this issue as well. 61.2 on Android 10

**Comment by KristineTrona** [comment]
Having the same issue also on RN 0.63.3. My text input is inside a `KeyboardAvoidingView` inside a modal, and has `autoFocus` set to true. Only after tapping the input manually, the keyboard appears. On iOS everything works as expected.

**Comment by smrafi1993** [comment]
Having the same issue, anyone found any solution ?
does flipper help ?

**Comment by mrmikardo** [comment]
I can confirm that I haev the same problem, with `react-native` version `0.63.2`.

**Comment by asmakhalfallah2018** [comment]
In my case i have set a zIndex value to my textInput and it solves the problem
