### ISSUE TITLE
Deep linking return null via push notification when i kill the app

### ISSUE THREAD

**Issue by darbaoui** [facebook/react-native#28727]
**Current Behavior**

```javascript

// App.js

componentDidMount() {
  Linking.getInitialURL().then(url => {
      this.navigate(url);
  });
  Linking.addEventListener('url', this.handleOpenURL);
}

handleOpenURL = event => {
    this.navigate(event.url);
};

navigate = url => {
    const route = url.replace(/.*?:\/\//g, '');
    const route_id = route.match(/\/([^\/]+)\/?$/)[1];
    const routeName = route.split('/')[0];

    this.navigator &&
          this.navigator.dispatch(
            NavigationActions.navigate({
               routeName
               params: {
                 route_id,
               },
             }),
          );
}

```

i have 2 scenarios in **IOS**:

- if the app is already opened and it is in the background, send push notification from intercom with deep link, i receive it then i click on it the app opened and redirect me to the screen that i want.
- if i kill the app by swipping it, i send the same notifcation, if i click on it, that only open the app no redirection, **in this case if i use safari with my app url schema like `appname://....`, i can  open the app and navigate to the disired screen.**, only from push notification that not work.

**Expected Behavior**

- if i kill the app and receive notification with deep link action i can navigate to the desired screen.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS                  | 13.3.1
| react-navigation               | ^4.0.10
| react-navigation-stack         | ^1.10.3
| react-navigation-tabs          | ^2.5.6
| react-native-reanimated        | ^1.4.0
| react-native-gesture-handler   |  ^1.5.0
| react-native-screens           | ^2.0.0-alpha.11
| react-native                   | 0.61.4"
| node                           | v13.6.0
| yarn                    | 1.21.1

**Comment by Aure77** [comment]
I facing exact same issue

**Comment by Aure77** [comment]
Similar to https://github.com/facebook/react-native/issues/11191

**Comment by cx5168** [comment]
same issue.
any way for it?

**Comment by cx5168** [comment]
follow:
https://github.com/facebook/react-native/issues/5047

solved it!

**Comment by Aure77** [comment]
> follow:
> #5047
> 
> solved it!

Can you explain us the solution ? Last comment is same code as provided on this issue (listener + getInitialURL).

I notice that it seems working when dev server is not used (bundle file instead of bridge url).

**Comment by cx5168** [comment]
> > follow:
> > #5047
> > solved it!
> 
> Can you explain us the solution ? Last comment is same code as provided on this issue (listener + getInitialURL).
> 
> I notice that it seems working when dev server is not used (bundle file instead of bridge url).

my solution:
node_modules/react-native/Libraries/LinkingIOS/RCTLinkingManager.m

getInitialURL:

RCT_EXPORT_METHOD(getInitialURL:(RCTPromiseResolveBlock)resolve
                  reject:(__unused RCTPromiseRejectBlock)reject)
{
  NSURL *initialURL = nil;
    
  if (self.bridge.launchOptions[UIApplicationLaunchOptionsURLKey]) {
    initialURL = self.bridge.launchOptions[UIApplicationLaunchOptionsURLKey];
      
  }else if (self.bridge.launchOptions[UIApplicationLaunchOptionsRemoteNotificationKey]){
      // keep in mind I'm extracting a dict here as my notification payload is a dictionary but it could be modified to extract any specific thing your payload sends
      NSDictionary *dict = self.bridge.launchOptions[UIApplicationLaunchOptionsRemoteNotificationKey];
      NSString *string_url = [dict valueForKey:@"url"];
      initialURL = [NSURL URLWithString:string_url];
  } else {
    NSDictionary *userActivityDictionary =
      self.bridge.launchOptions[UIApplicationLaunchOptionsUserActivityDictionaryKey];
    if ([userActivityDictionary[UIApplicationLaunchOptionsUserActivityTypeKey] isEqual:NSUserActivityTypeBrowsingWeb]) {
      initialURL = ((NSUserActivity *)userActivityDictionary[@"UIApplicationLaunchOptionsUserActivityKey"]).webpageURL;
    }
  }
  resolve(RCTNullIfNil(initialURL.absoluteString));
}

["url"]：
The url should be determined according to the key of the deeplink of the notification payload.

good luck!

**Comment by emawby** [comment]
This issue is caused because when launching the app from a notification the launch options will not contain the initial url, and since the React-Native run time is not available yet, the url event listener won't fire.
