### ISSUE TITLE
Error trying to use NavigatorIOS: Element type is invalide.

### ISSUE THREAD

**Issue by Cael00** [facebook/react-native#28728]
## Description
Trying to run the NavigatorIOS example form official React-Native documentation (https://reactnative.dev/docs/navigatorios#__docusaurus) but get this error:

"Error: Element type is invalid: expected a string...."

## React Native version:
React Native version: 2.0.1
XCode version: 11.4.1

## Steps To Reproduce
Just create a new React-Native project and past the sample code in App.js

## Expected Results
Show a simple  UINavigationController in the App.

## Snack, code example, screenshot, or link to a repository:
This is the code I use:

```
import PropTypes from 'prop-types';
import React, {Component} from 'react';
import {NavigatorIOS, Text, TouchableHighlight, View} from 'react-native';

export default class NavigatorIOSApp extends Component {
  render() {
    return (
      <NavigatorIOS
        initialRoute={{
          component: MyScene,
          title: 'My Initial Scene',
        }}
        style={{flex: 1}}
      />
    );
  }
}

class MyScene extends Component {
  static propTypes = {
    title: PropTypes.string.isRequired,
    navigator: PropTypes.object.isRequired,
  };

  _onForward = () => {
    this.props.navigator.push({
      title: 'Scene',
    });
  };

  render() {
    return (
      <View>
        <Text>Current Scene: {this.props.title}</Text>
        <TouchableHighlight onPress={this._onForward}>
          <Text>Tap me to load the next scene</Text>
        </TouchableHighlight>
      </View>
    );
  }
}
```

This is the error screenshot:

<img width="364" alt="image" src="https://user-images.githubusercontent.com/63990211/80016429-1f6c1700-84a1-11ea-86a9-7dcbceed5418.png">

The same error occurs at https://snack.expo.io.

What's causing this?

**Comment by troZee** [comment]
Are you sure about react native version ? 
`React Native version: 2.0.1`

and FYI: `NavigatorIOS has been removed from the core React Native package in version 0.58.`
