### ISSUE TITLE
Touchables using forwardRef are not covered by Flow

### ISSUE THREAD

**Issue by draperunner** [facebook/react-native#28726]
## Description

When importing TouchableOpacity, it is treated as `any` by Flow. Same goes for TouchableHighlight. I think this is because of the use of `React.forwardRef` in their respective files. Flow understands TouchableWithoutFeedback, which does not use forwardRef.

This blog post might be relevant for typing forwardRef in Flow: https://medium.com/flow-type/supporting-react-forwardref-and-beyond-f8dd88f35544

I was hoping to use `React.ElementConfig<typeof TouchableOpacity>` to type the Props of my own Button component, but that does not work because of this. I am using `React.ElementConfig<typeof TouchableWithoutFeedback>` now as a workaround.

## React Native version:
0.62.2
Flow version 0.113.0

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Import TouchableOpacity in a component file
2. Use your Flow tools in your editor to inspect that TouchableOpacity is treated as `any` or use it "illegally" and run flow to see that it passes. Like for instance
```
cons x: number  = TouchableOpacity
```

## Expected Results
I expect Flow to understand that TouchableOpacity is not "any", but a React component with a set of valid Props.

## Snack, code example, screenshot, or link to a repository:
<img width="632" alt="image" src="https://user-images.githubusercontent.com/4339443/79979414-c18bff00-84a1-11ea-96f0-5e22eec8b370.png">

**Comment by safaiyeh** [comment]
Appreciate filling out the issue template! I quick check of the component
https://github.com/facebook/react-native/blob/0b9ea60b4fee8cacc36e7160e31b91fc114dbc0d/Libraries/Components/Touchable/TouchableOpacity.js#L302

It shows the component is typed correctly, any more info you can provide about your setup?

**Comment by draperunner** [comment]
Thanks for the reply @safaiyeh. I have done some more digging and think I've found something interesting.

This works:

```diff
module.exports = (React.forwardRef((props, hostRef) => (
  <TouchableOpacity {...props} hostRef={hostRef} />
-)): React.ComponentType<$ReadOnly<$Diff<Props, {|hostRef: React.Ref<typeof Animated.View>|}>>>);
+)): React.AbstractComponent<$ReadOnly<$Diff<Props, {|hostRef: React.Ref<typeof Animated.View>|}>>>);
```

In the [Flow.js docs](https://flow.org/en/docs/react/types/#toc-react-componenttype) I found this:

> Note: In 0.89.0+, React.ComponentType is an alias for React.AbstractComponent<Config, any>, which represents a component with config type Config and any instance type.
https://flow.org/en/docs/react/types/#toc-react-componenttype

So I'm thinking that since the instance type is treated as `any` with ComponentType, Flow treats TouchableOpacity as `any` as well.

**Comment by safaiyeh** [comment]
Nice find. Feel free to make a PR and someone will take a look!
