### ISSUE TITLE
[iOS] Splash screen cache on update version from AppStore/TestFlight

### ISSUE THREAD

**Issue by suraneti** [facebook/react-native#28732]
## Description
Splash screen cache from the previous version and I've to delete and reinstall the application.

## React Native version:
```
  React Native Environment Info:
    System:
      OS: macOS 10.15.4
      CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
      Memory: 537.39 MB / 16.00 GB
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.13.0 - /usr/local/bin/node
      npm: 6.14.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
      Android SDK:
        API Levels: 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 26.0.1, 26.0.2, 27.0.3, 28.0.2, 28.0.3
        System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5900203
      Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: ^0.59.9 => 0.59.10 
```

## Steps To Reproduce
1. Archive application.
2. Upload to appstoreconnect.
3. Update application on a device.

## Expected Results
The splash screen should change to a new version.

**Comment by Frans-L** [comment]
Same problem.  @suraneti Have you find any workaround yet? 

There has been some tricks to this problem. Such as http://arsenkin.com/launch_screen_image_cache.html but they are not working for iOS 13.

**Comment by suraneti** [comment]
@Frans-L the solution that I did in Xcode.

1.  Clean project (Product -> Clean).
2. Delete any folders in the DerivedData folder.
3. Try to move something in the Storyboard file and save.
(this will update version of Storyboard file when you move something each time, so I just move a logo to somewhere and move back).


If those step doesn't work try to create Image set in `Images.xcassets` and then import in Storyboard instead of an image file path.

**Comment by Frans-L** [comment]
@suraneti  
Thanks for the help!. Unfortunately, steps 1-3 didn't work for me. The launch screen is updated still only after a user has deleted and redownloaded the app.
I have also tried to rename launch screen images / image sets, haven't helped either. 

What do you mean ".... then import in Storyboard instead of an image file path"?

**Comment by suraneti** [comment]
@Frans-L I mean use image sets instead of an image file path, but you already try.

Could you try this [solution](http://arsenkin.com/launch_screen_image_cache.html).

**Comment by Frans-L** [comment]
@suraneti Yeah, I tried. I still haven't found any solution :/

**Comment by rendomnet** [comment]
same here
