### ISSUE TITLE
Duplicating Debug Configuration Does Not Connect to Packager on iOS

### ISSUE THREAD

**Issue by timothystewart6** [facebook/react-native#28738]
## Description
I am trying to simply switch the Run Phase for iOS that points to `Debug` to a new configuration, `DebugQA`

I have duplicated the `Debug` configuration to `DebugQA` and everything works great except when the app launches. It crashes with:

```
No bundle URL present.\n\nMake sure you're running a packager server or have included a .jsbundle file in your application bundle.
```

## React Native version:
``
 react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
``

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Duplicate `Debug` Build Configuration in XCode, name it `DebugQA`
2. Modify scheme Run confiuration to point to `DebugQA`
3. `cd ios && pod install && cd ..`
4. start bundler `react-native start`
5. `react-native run-ios`
6. app builds, installs, launches
7. Error:
```
No bundle URL present.\n\nMake sure you're running a packager server or have included a .jsbundle file in your application bundle.
```

## Expected Results
I would expect this new config to behave just like the existing `Debug` config and connect to metro bundler/ packager.

I have made sure the metro bundler is running and if I switch the Run configuration back to `Debug` it works fine. It's almost as if the app's new config isn't making the `GET` for the bundle from the metro bundler.

Making a `GET` to the bundler outside of the app responds just fine.

```
::1 - - [23/Apr/2020:17:26:56 +0000] "GET /favicon.ico HTTP/1.1" 404 150 "http://localhost:8081/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36"
```

I've had success building other packages using this method however never creating a new Debuggable config that tries to connect to metro bundler. Any help is greatly appreciated.

**Comment by timothystewart6** [comment]
More findings:

Duplicating `Debug` config and having `Debug` in the name produces these results.
Deuplicating `Deubg` with a different name like `SomethingElse` bundles the JS and includes it with the app.  App is not debuggable with react native.

**Comment by jdcookie** [comment]
Yeah I am seeing the same thing - trying to get configurations and schemes working at the moment.

If you look in the /node_modules/react-native/scripts/react-native-xcode.sh you will see

`case "$CONFIGURATION" in
  *Debug*)
    if [[ "$PLATFORM_NAME" == *simulator ]]; then
      if [[ "$FORCE_BUNDLING" ]]; then
        echo "FORCE_BUNDLING enabled; continuing to bundle."
      else
        echo "Skipping bundling in Debug for the Simulator (since the packager bundles for you). Use the FORCE_BUNDLING flag to change this behavior."
        exit 0;
      fi
    else
      echo "Bundling for physical device. Use the SKIP_BUNDLING flag to change this behavior."
    fi

    DEV=true
    ;;
  "")
    echo "$0 must be invoked by Xcode"
    exit 1
    ;;
  *)
    DEV=false
    ;;
esac`

So I think you have to meet that criteria of your configuration having 'Debug' in it's name for the bundling to be skipped.

**Comment by ribamarsantos** [comment]
Hi guys, I'm currently facing this issue on RN version 0.62.2. 

Having configuration name Debug works fine but if I rename it to DebugTest DebugQA it does not work. I have tried move to 0.63 version as well and didn't work. Any clues ? 

I didn't like to create multiple Schemes if that's the only option. 

Thanks in advance.

**Comment by ValterSantosMatos** [comment]
Same issue here, think this should be reopen

**Comment by IngyuTae** [comment]
solved the issue by initiating project with vanilla react-native js and applying typescript manually.

**Comment by jwoodmansey** [comment]
Maybe I am missing something here but for curiosities sake I tried patching the script to the following, without using wildcards and hardcoding our two "Debug" configuration names. It still throws the same error message as shown above.

```
diff --git a/node_modules/react-native/scripts/.packager.env b/node_modules/react-native/scripts/.packager.env
new file mode 100644
index 0000000..361f5fb
--- /dev/null
+++ b/node_modules/react-native/scripts/.packager.env
@@ -0,0 +1 @@
+export RCT_METRO_PORT=8081
diff --git a/node_modules/react-native/scripts/react-native-xcode.sh b/node_modules/react-native/scripts/react-native-xcode.sh
index da9e44c..5d45f45 100755
--- a/node_modules/react-native/scripts/react-native-xcode.sh
+++ b/node_modules/react-native/scripts/react-native-xcode.sh
@@ -13,7 +13,7 @@ set -x
 DEST=$CONFIGURATION_BUILD_DIR/$UNLOCALIZED_RESOURCES_FOLDER_PATH
 
 # Enables iOS devices to get the IP address of the machine running Metro
-if [[ "$CONFIGURATION" = *Debug* && ! "$PLATFORM_NAME" == *simulator ]]; then
+if [[ ("$CONFIGURATION" == "Dev - Debug" || "$CONFIGURATION" == "Prod - Debug") && ! "$PLATFORM_NAME" == *simulator ]]; then
   IP=$(ipconfig getifaddr en0)
   if [[ -z "$IP" || -n "`ifconfig $value | grep 'baseT'`" ]]; then
     IP=$(ipconfig getifaddr en1)
@@ -31,7 +31,7 @@ if [[ "$SKIP_BUNDLING" ]]; then
 fi
 
 case "$CONFIGURATION" in
-  *Debug*)
+  "Dev - Debug"|"Prod - Debug")
     if [[ "$PLATFORM_NAME" == *simulator ]]; then
       if [[ "$FORCE_BUNDLING" ]]; then
         echo "FORCE_BUNDLING enabled; continuing to bundle."

```
Has anybody had any success in getting this to work?

**Comment by humbkr** [comment]
I also have the same issue, I would like to duplicate my Debug configuration so I can run 2 versions of my app with different names / bundle id / ... but it seems impossible.

**Comment by joaoguilhermee** [comment]
Same issue here, think this should be reopen

**Comment by marcshilling** [comment]
Just ran into this, anyone ever solve it?
