### ISSUE TITLE
fresh 0.62.2 install shows error when trying to run on Apple TV simulator

### ISSUE THREAD

**Issue by vgrafe** [facebook/react-native#28741]
## Description
When installing a fresh environment v0.62.2, it is not possible to run the app on Apple TV simulator. Other platforms works well (ios, android, androidTV).

Thank you for any guidance on this!

## React Native version:
```
System:
    OS: macOS 10.15.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 21.07 GB / 64.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.4.0 - /usr/local/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.4 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.1 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. `npx react-native init something`
2. Open Xcode, select `something-tvOS` target, try to build or run
3. An error appears: "undeclared identifier 'FlipperClient'" in AppDelegate.m

## Expected Results
I was expecting the app to run on the TV simulator. The tips listed in [this issue](https://github.com/facebook/react-native/issues/28406) didn't help: when preventing Flipper to initialize with `#if false` blocks, I run into another error `ld: library not found for -lPods-something-tvOS`.

**Comment by Simek** [comment]
Hi @vgrafe, official support for `tvOS` in the core package has been dropped in the 0.62 release. Since 0.62 you should use [`react-native-tvos`](https://github.com/react-native-community/react-native-tvos) package to build for TVs. For the details please check the release [blog post](https://reactnative.dev/blog/#moving-apple-tv-to-react-native-tvos).

**Comment by vgrafe** [comment]
Thanks for the info. Is there any similar plans for Android TV?

**Comment by Simek** [comment]
To be honest, I don't know. I'm looking for this answer too, to finish my facebook/react-native-website#1859 PR.
