### ISSUE TITLE
[0.63-rc.0] [Android] Could not find Native Module for JSDevSupport

### ISSUE THREAD

**Issue by jerameel** [facebook/react-native#28746]
## Description
Enabling debug mode on android for a new project shows the following error. See screenshot below.

## React Native version:
System:
    OS: macOS 10.15.3
    CPU: (12) x64 Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
    Memory: 158.79 MB / 16.00 GB
    Shell: 5.0.11 - /usr/local/bin/bash
  Binaries:
    Node: 13.0.1
    npm: 6.12.0
    Watchman: 4.9.0
  SDK:
    Android SDK:
        API Levels: 23, 25, 26, 27, 28, 29
        Build Tools: 28.0.3, 29.0.2, 29.0.3
  Languages:
    Java: 1.8.0_222
    Python: 2.7.16
  npmPackages:
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.0-rc.0 => 0.63.0-rc.0 

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. `npx react-native init RN063 --version 0.63.0-rc.0`
2.`react-native start` and `react-native run-android`
3. Enable debug mode on react native dev menu.

## Expected Results
Should work the same as debug mode disabled

![Screenshot_1587742830](https://user-images.githubusercontent.com/15943153/80230806-015f0c00-8685-11ea-973d-1152c6c68e61.png)

**Comment by acuariol** [comment]
report

**Comment by cryptedx** [comment]
I am having the same problem with my app. iOS fine. Android with debugging enabled is not working.

**Comment by lylysunshinee** [comment]
I am having the same problem with android app in debug mode. IOS fine

**Comment by kesha-antonov** [comment]
Same here

**Comment by aleppos** [comment]
Same here on Android when running debug and it work normally when stop debugging

**Comment by RobTheFiveNine** [comment]
> Same here on Android when running debug and it work normally when stop debugging

Same scenario here

**Comment by tuanpi** [comment]
Similarly when running on real devices

**Comment by BrunoVillanova** [comment]
Same here.

**Comment by alexwasner** [comment]
I was getting a white screen upon upgrading. Attempted to toggle debugger and discovered this as well.

**Comment by BrunoVillanova** [comment]
Are some of you using wix RNN?

**Comment by jreason** [comment]
@BrunoVillanova no we are using @react-navigation
