### ISSUE TITLE
[Android][TextInput] Can't change fontStyle from 'italic' to 'normal' when typing and set secureTextEntry is true  

### ISSUE THREAD

**Issue by wasitajeew** [facebook/react-native#28745]
I have example code 

` <TextInput
                style={[TEXT_STYLE.textInput,
                {
                    ...Platform.select({
                        ios: {
                            fontFamily: password ? type.base : type.italic,
                            fontSize: placeholderSize
                        },
                        android: {
                            fontFamily: 'Lato-Regular',
                            fontStyle: password ? 'normal' : 'italic',
                            fontSize: placeholderSize
                        }
                    })
                }
                ]}
                secureTextEntry={true}
                onChangeText={(text) => setPassword(text)}
                value={passwordInput}
                placeholder={placeholder}
                placeholderTextColor={COLORS.Default.darkGray}
            />
`

If password is empty, it's should be 'italic'. But if password is not empty, it's should be 'normal'.
iOS work but android doesn't work.

Component: TextInput
Platform: Android
RN: 0.0.61

**Comment by fabriziobertoglio1987** [comment]
I tried and can not reproduce, no reproducible example ..setting this up took me too much time sorry
