### ISSUE TITLE
react-native run-ios --device failed to launch app on iPhone

### ISSUE THREAD

**Issue by vicary** [facebook/react-native#28749]
## Description
I can run debug version of the app via XCode, but CLI fails to do so.

We have a few real devices as well as simulators connected to a XCode Server for CI tests, so launching the apps from CLI is crucial to us. 

Running `react-native run-ios --device` prompts the following in the console and stuck at the last line.

```
$ yarn react-native run-ios --device
info Found Xcode workspace "scarletboar.xcworkspace"
info Using first available device named "SE 13.3.1" due to lack of name supplied.
info Building (using "xcodebuild -workspace [redacted].xcworkspace -configuration Debug -scheme [redacted] -destination id=[redacted]")
...........................................................
2020-04-25 16:35:02.487 xcodebuild[28201:470390] [MT] iPhoneConnect: 📱<DVTiOSDevice (0x7fb3ff324c40), SE 13.3.1, iPhone, 13.3.1 (17D50), [redacted]> == Underlying device preparation errors ==
2020-04-25 16:35:02.487 xcodebuild[28201:470390] [MT] iPhoneConnect: Failed _shouldMakeReadyForDevelopment check even though device is not locked by passcode.
Domain: com.apple.platform.iphoneos
Code: 5
Failure Reason: allowsSecureServices: 1. isConnected: 0. Platform: <DVTPlatform:0x7fb3fcc3c560:'com.apple.platform.iphoneos':<DVTFilePath:0x7fb3fcc3c2b0:'/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform'>>. DTDKDeviceIdentifierIsIDID: 0
User Info: {
    DVTDeviceDescription = "\Ud83d\Udcf1<DVTiOSDevice (0x7fb3ff324c40), SE 13.3.1, iPhone, 13.3.1 (17D50), [redacted]>";
}
--
2020-04-25 16:35:02.487 xcodebuild[28201:470390] [MT] iPhoneConnect: 📱<DVTiOSDevice (0x7fb3ff324c40), SE 13.3.1, iPhone, 13.3.1 (17D50), [redacted]> == END: Underlying device preparation errors ==
2020-04-25 16:35:02.895 xcodebuild[28201:470390] [MT] iPhoneConnect: 📱<DVTiOSDevice (0x7fb3ff324c40), SE 13.3.1, iPhone, 13.3.1 (17D50), [redacted]> == Underlying device preparation errors ==
2020-04-25 16:35:02.895 xcodebuild[28201:470390] [MT] iPhoneConnect: Failed _shouldMakeReadyForDevelopment check even though device is not locked by passcode.
Domain: com.apple.platform.iphoneos
Code: 5
Failure Reason: allowsSecureServices: 1. isConnected: 0. Platform: <DVTPlatform:0x7fb3fcc3c560:'com.apple.platform.iphoneos':<DVTFilePath:0x7fb3fcc3c2b0:'/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform'>>. DTDKDeviceIdentifierIsIDID: 0
User Info: {
    DVTDeviceDescription = "\Ud83d\Udcf1<DVTiOSDevice (0x7fb3ff324c40), SE 13.3.1, iPhone, 13.3.1 (17D50), [redacted]>";
}
--
2020-04-25 16:35:02.896 xcodebuild[28201:470390] [MT] iPhoneConnect: 📱<DVTiOSDevice (0x7fb3ff324c40), SE 13.3.1, iPhone, 13.3.1 (17D50), [redacted]> == END: Underlying device preparation errors ==
info Installing and launching your app on SE 13.3.1
```

## React Native version:
Run `react-native info` in your terminal and copy the results here.

```
System:
    OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
    Memory: 72.53 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.13.1 - /var/folders/k_/twn4fnrn6g56kn0xjlkp3zx00000gn/T/yarn--1587804585783-0.1203554637512787/node
    Yarn: 1.22.4 - /var/folders/k_/twn4fnrn6g56kn0xjlkp3zx00000gn/T/yarn--1587804585783-0.1203554637512787/yarn
    npm: 6.14.3 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.8.4 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 28, 29
      Build Tools: 27.0.3, 28.0.3, 29.0.2, 30.0.0
      System Images: android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_212-release - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.1 => 0.62.1 
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Run `react-native init`
2. Open the project with XCode
3. Register a test device (iPhone) to the project
4. Run `react-native run-ios --device`

## Expected Results
The app launches in iPhone.

## Snack, code example, screenshot, or link to a repository:
Not really related to code, and our iPhone is not responding so no screenshots. Our only clue is the CLI output above.

**Comment by ArrayZoneYour** [comment]
It should be the issue of [@react-native-community/cli](https://github.com/react-native-community/cli/blob/2d575b0758e9a05b2b751ffe452a50e01fd9ca2d/packages/platform-ios/src/commands/runIOS/index.ts#L255) or [ios-deploy](https://github.com/ios-control/ios-deploy)

**Comment by vicary** [comment]
@ArrayZoneYour Thanks for the reply. I would like to further look into this, how can I copy the generated command from [@react-native-community/cli](https://github.com/react-native-community/cli/blob/2d575b0758e9a05b2b751ffe452a50e01fd9ca2d/packages/platform-ios/src/commands/runIOS/index.ts#L255) and test myself?

**Comment by ArrayZoneYour** [comment]
./node_modules/@react-native-community/cli-platform-ios/build/commands/runIOS/index.js

**Comment by vicary** [comment]
Adding console logs after the line `const iosDeployInstallArgs = [...]` did nothing, not sure if there was a build system in place.

Did one thing that fixed my issue, the `ios-deploy` was installed with `yarn global add` and it doesn't work. While I was tinkering around I did `npm i -g --unsafe-perm=true ios-deploy` and it went through into the iPhone.

Package version didn't change, it was `1.10.0`.

I am closing this, really don't bother further digging this to know if it was either `yarn` over `npm` or just build configs in `ios-deploy`.

**Comment by 1280103995** [comment]
```npm i -g --unsafe-perm=true ios-deploy``` it work. Thank! @vicary

**Comment by amma-dev** [comment]
just update the cli-platform-ios inside @react-native-community/
try this
npm i @react-native-community/cli-platform-ios

hope it works

**Comment by gabrielmoncea** [comment]
Build not working anymore since I've installed `@react-native-community/cli-platform-ios` on MacOS with M1
