### ISSUE TITLE
space between cursor and text in TextInput will add letterSpacing

### ISSUE THREAD

**Issue by L-x-C** [facebook/react-native#28755]
## Description
when add letterSpacing to a TextInput, the space between cursor and text will not be 0, but letterSpacing

eg: 
letterSpacing: 200

#### In android
![image](https://user-images.githubusercontent.com/4329120/80300066-f793f080-87cb-11ea-90e3-dc2b1ca14e72.png)
![image](https://user-images.githubusercontent.com/4329120/80300067-fc58a480-87cb-11ea-8b8b-ef5bc141da24.png)

#### in IOS
![image](https://user-images.githubusercontent.com/4329120/80300096-36c24180-87cc-11ea-8e3b-c8a3aad87cbb.png)
![image](https://user-images.githubusercontent.com/4329120/80300098-3aee5f00-87cc-11ea-88cd-da415a9fea9f.png)

That's what we expect

## React Native version:
react: 16.9.0 
react-native: 0.61.5

**Comment by fabriziobertoglio1987** [comment]
maybe connected to how android sets those spans in `ReactEditText.java`

```java
  private void manageSpans(SpannableStringBuilder spannableStringBuilder) {
    Object[] spans = getText().getSpans(0, length(), Object.class);
    for (int spanIdx = 0; spanIdx < spans.length; spanIdx++) {
      // Remove all styling spans we might have previously set
      if (spans[spanIdx] instanceof ReactSpan) {
        getText().removeSpan(spans[spanIdx]);
      }

      if ((getText().getSpanFlags(spans[spanIdx]) & Spanned.SPAN_EXCLUSIVE_EXCLUSIVE)
          != Spanned.SPAN_EXCLUSIVE_EXCLUSIVE) {
        continue;
      }
      Object span = spans[spanIdx];
      final int spanStart = getText().getSpanStart(spans[spanIdx]);
      final int spanEnd = getText().getSpanEnd(spans[spanIdx]);
      final int spanFlags = getText().getSpanFlags(spans[spanIdx]);

      // Make sure the span is removed from existing text, otherwise the spans we set will be
      // ignored or it will cover text that has changed.
      getText().removeSpan(spans[spanIdx]);
      if (sameTextForSpan(getText(), spannableStringBuilder, spanStart, spanEnd)) {
        spannableStringBuilder.setSpan(span, spanStart, spanEnd, spanFlags);
      }
    }
  }
```

please provide reproducible example so i can debug this. thanks

**Comment by L-x-C** [comment]
> maybe connected to how android sets those spans in `ReactEditText.java` and the usage of [`getSpanStart`](https://developer.android.com/reference/android/text/SpannableStringBuilder#getSpanStart(java.lang.Object))
> 
> ```java
>   private void manageSpans(SpannableStringBuilder spannableStringBuilder) {
>     Object[] spans = getText().getSpans(0, length(), Object.class);
>     for (int spanIdx = 0; spanIdx < spans.length; spanIdx++) {
>       // Remove all styling spans we might have previously set
>       if (spans[spanIdx] instanceof ReactSpan) {
>         getText().removeSpan(spans[spanIdx]);
>       }
> 
>       if ((getText().getSpanFlags(spans[spanIdx]) & Spanned.SPAN_EXCLUSIVE_EXCLUSIVE)
>           != Spanned.SPAN_EXCLUSIVE_EXCLUSIVE) {
>         continue;
>       }
>       Object span = spans[spanIdx];
>       final int spanStart = getText().getSpanStart(spans[spanIdx]);
>       final int spanEnd = getText().getSpanEnd(spans[spanIdx]);
>       final int spanFlags = getText().getSpanFlags(spans[spanIdx]);
> 
>       // Make sure the span is removed from existing text, otherwise the spans we set will be
>       // ignored or it will cover text that has changed.
>       getText().removeSpan(spans[spanIdx]);
>       if (sameTextForSpan(getText(), spannableStringBuilder, spanStart, spanEnd)) {
>         spannableStringBuilder.setSpan(span, spanStart, spanEnd, spanFlags);
>       }
>     }
>   }
> ```
> 
> please provide reproducible example so i can debug this. thanks

`<TextInput style={{ letterSpacing: 100 }}></TextInput>`

Try this on Android and Ios, and you will see...

Thanks a lot
