### ISSUE TITLE
Unable to resolve module

### ISSUE THREAD

**Issue by nancyruya** [facebook/react-native#28754]
Description

Unfortunately, I’ve run into a devastating bug that prevents me from loading any new modules into my app. I first discovered this bug when installing dependencies for navigator and import it on my App.js.

After installing @react-nativation/stack, I imported it, and refreshed the simulator. After refreshing I was greeted with the message shown below:
![Screen Shot 2020-04-25 at 8 14 45 PM](https://user-images.githubusercontent.com/34261425/80293869-81db4680-8731-11ea-9db0-174184314288.png)

![Screen Shot 2020-04-25 at 8 18 32 PM](https://user-images.githubusercontent.com/34261425/80293924-f4e4bd00-8731-11ea-873a-af7b11ab99d3.png)

I have followed the suggested instructions and took me quite a while to run these 4 steps successfully. But the Error continue shows.

PS. Let me know what other info is needed to solve this issue.

NPM version: 6.13.4
Yarn version: 1.22.4
Xcode version: 11.3.1
Platform: iOS
Operating System: MacOS Mojave 10.14.6
This bug absolutely kills my ability to proceed with any tutorials/courses. I'd really appreciate if someone could help me out with this.

Thanks :)

**Comment by nancyruya** [comment]
> react-native info

System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 438.72 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.16.1 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: ~16.9.0 => 16.9.0 
    react-native: 0.61.4 => 0.61.4 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7

**Comment by fabriziobertoglio1987** [comment]
https://github.com/react-navigation/stack has been archived from the owner

So I believe this issue needs to be closed, as the repo you are trying to install has been archived. You need to use the latest dependencies and follow updated react-native course.

see also https://github.com/facebook/react-native/issues/23908
