### ISSUE TITLE
iOS crashes if JSON.stringify receives a function as first argument

### ISSUE THREAD

**Issue by finom** [facebook/react-native#28757]
## Description
`JSON.stringify(func)` crashes iOS app even if it's wrapped by try..catch. I've implemented a hook where I didn't handle functions by mistake and passed them to `JSON.stringify`. Unfortunately I didn't receive any error but got the app crashed instead without any additional information.
 
## React Native version:
https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz

## Steps To Reproduce
Add to your code: 
```js
try { JSON.stringify(() => {}) } catch(e) {}
```

## Expected Results
It should do nothing if wrapped by try..catch or throw a normal error if isn't.

## Snack, code example, screenshot, or link to a repository:
Unfortunately snack.expo doesn't work for me. I hope the description allows to reproduce the bug easily.

**Comment by cruzach** [comment]
Hi @finom , I created a snack to reproduce this [here](https://snack.expo.io/@charliecruzan/frisky-chip), and it is not crashing. I tried the same code in a local project, and still didn't see a crash
