### ISSUE TITLE
[iOS] warning is not a function when runnning init project

### ISSUE THREAD

**Issue by Javanaise** [facebook/react-native#2875]
![screen shot 2015-09-20 at 00 01 56](https://cloud.githubusercontent.com/assets/14178589/9978385/dde7ee1c-5f2a-11e5-8cb9-a9aa702fc1ec.png)

**Comment by jasalguero** [comment]
I had a similar problem until I realised that because of nvm I created the project with an older version of node. Deleted the project and recreated it with 4.0 and it worked nicely

**Comment by Javanaise** [comment]
@jasalguero updated to node 4.1 and it fixed my problem, thanks.
