### ISSUE TITLE
 integrity checksum failed when using sha512

### ISSUE THREAD

**Issue by vksgautam1** [facebook/react-native#28759]
Please provide all the information requested. Issues that do not follow this format are likely to stall.
i am trying to install react native 0.62.2. this error is coming
## Description
Please provide a clear and concise description of what the bug is. Include screenshots if needed.
Please test using the latest React Native release to make sure your issue has not already been fixed: https://reactnative.dev/docs/upgrading.html

## React Native version:
Run `react-native info` in your terminal and copy the results here.
version--0.62.2
node 12.10.0
npm 6.10.0
![error](https://user-images.githubusercontent.com/4745491/80310340-b580a400-87f7-11ea-8a44-bc350bd91576.png)

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. npm install react-native@0.62.2
2.

## Expected Results
Describe what you expected to happen.

## Snack, code example, screenshot, or link to a repository:
Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by fabriziobertoglio1987** [comment]
https://github.com/nodejs/node/issues/13635

**Comment by vksgautam1** [comment]
None of the above given worked
