### ISSUE TITLE
Modal not hiding when setState updates are done in try / catch and the response is quick

### ISSUE THREAD

**Issue by lucastonon** [facebook/react-native#28753]
Hi, I would like to reopen https://github.com/facebook/react-native/issues/10417

I am having this problem for a while and the only solution that worked for me was to create a timeout big enough that even in slow devices it works.

When using try/catch, if the work is finished quickly (quick api responses for instance), when we setState({showLoader: false}) it won't remove the Modal and we will have to close and run the app again to clear it.

I am going to use the same example as the issue link mentioned

```
makeRequest = () => {
  this.setState({ loading: true })
  Media.request(url)
  .then(response => {
    // todo
  }, e => {
    this.setState({ loading: false })
  })
}

render() {
  return(
    <View>
      <Modal
          animationType={'slide'}
          transparent={false}
          visible={this.state.loading}
          onRequestClose={() => {} }
       >
        <View></View>
      </Modal>
      <Text onPress={this.makeRequest}>Do Magic</Text>
    </View>
  )
}
```

![e7a3ffba-9406-11e6-9731-bfbe503324b2](https://user-images.githubusercontent.com/38772994/80286510-378ea100-8702-11ea-82e7-27b126b69b86.png)

**Comment by RinorDreshaj** [comment]
have you tried putting the request after the setState 


```
makeRequest = () => {
	this.setState({ 
		loading: true 
	}, () => {
		// this ensures that the state has been set to loading: true
		Media.request(url)
		.then(response => {
			// todo
		}, e => {
			this.setState({ loading: false })
		})	
	})
}
```


and to make the code cleaner you can use .catch clause as its the same as onRejected callback: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/catch

and even better use the finally clause to set the loading to false, so you know that either if promise is fulfilled or rejected the laoding will be set to false

```
makeRequest = () => {
	this.setState({ 
		loading: true 
	}, () => {
		// this ensures that the state has been set to loading: true
		Media.request(url)
		.then(response => {/* todo */})
		.catch(error => {})
		.finally(() => {
			this.setState({ loading: false })
		})		
	})
}
```
