### ISSUE TITLE
ReactInstanceManager#mCurrentActivity wrong assignment at onHostResume

### ISSUE THREAD

**Issue by maiwenchang** [facebook/react-native#28758]
#Description
ReactInstanceManager#mCurrentActivity wrong assignment at onHostResume method.

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.
We have three Activity: A, B and C.
Activity B is a translucent Activity which has `<item name="android:windowIsTranslucent">true</item>` style and it look like a Dialog.

Now we:
1.start Activity A
2.start Activity B
3.start Activity C

After the C called onHostResume, the A would call onHostResume and onHostPause.

**Comment by fabriziobertoglio1987** [comment]
I would avoid using `Activity B` as translucent Dialog, instead use some of the react-native components like modal or similar... 

did you have a look at the code in [ReactInstanceManager](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/ReactInstanceManager.java) and what do you think about it?

How can I help you if you do not provide a React-Native example to test on generic android phone.

```java
  /** Use this method when the activity resumes. */
  @ThreadConfined(UI)
  public void onHostResume(Activity activity) {
    UiThreadUtil.assertOnUiThread();

    mCurrentActivity = activity;

    if (mUseDeveloperSupport) {
      // Resume can be called from one of two different states:
      // a) when activity was paused
      // b) when activity has just been created
      // In case of (a) the activity is attached to window and it is ok to add new views to it or
      // open dialogs. In case of (b) there is often a slight delay before such a thing happens.
      // As dev support manager can add views or open dialogs immediately after it gets enabled
      // (e.g. in the case when JS bundle is being fetched in background) we only want to enable
      // it once we know for sure the current activity is attached.

      // We check if activity is attached to window by checking if decor view is attached
      final View decorView = mCurrentActivity.getWindow().getDecorView();
      if (!ViewCompat.isAttachedToWindow(decorView)) {
        decorView.addOnAttachStateChangeListener(
            new View.OnAttachStateChangeListener() {
              @Override
              public void onViewAttachedToWindow(View v) {
                // we can drop listener now that we know the view is attached
                decorView.removeOnAttachStateChangeListener(this);
                mDevSupportManager.setDevSupportEnabled(true);
              }

              @Override
              public void onViewDetachedFromWindow(View v) {
                // do nothing
              }
            });
      } else {
        // activity is attached to window, we can enable dev support immediately
        mDevSupportManager.setDevSupportEnabled(true);
      }
    }

    moveToResumedLifecycleState(false);
  }

```

**Comment by maiwenchang** [comment]
Our project is not a pure RN project. We have some reason to design an Activity as the translucent Dialog. 
I have read the code of the ReactInstanceManager. I think the `mCurrentActivity` shouldn't be held by the ReactInstanceManager.

**Comment by fabriziobertoglio1987** [comment]
https://github.com/facebook/react-native/blob/10314fe621e1649654e83df197adf657e0ca8363/ReactAndroid/src/main/java/com/facebook/react/ReactInstanceManager.java#L113-L131

https://doc.ebichu.cc/react-native/releases/0.40/docs/integration-with-existing-apps.html
https://github.com/facebook/react-native/issues/6410
