### ISSUE TITLE
How to remove the border in picker  in iOS. 

### ISSUE THREAD

**Issue by nihp** [facebook/react-native#28766]
I need to remove the border which shown default from the picker. I have designed the border grey color with 1.5 boderWidth. But it shows a border in a thin line. Kindly refer the attached image. Any solution 

```
import { Picker } from 'react-native';

<View style={{display: 'flex', flexDirection: 'row',borderColor:"transparent",	alignItems: 'center',marginBottom:13,}}>
            <Picker
              style={{paddingHorizontal: 1,  borderWidth:1.5, borderRadius:4,borderRightWidth:1, borderColor: isValidNumber ? 'grey': 'red', color: 'red', flex:0.5}}
              itemStyle={{height: 47,backgroundColor: "white",borderColor:"transparent",fontSize: 15, fontWeight:'400'}}
            >
              <Picker.Item style={{borderColor:"transparent"}} key={dialCode} value={dialCode} label={dialCode} />
          </Picker>
<View>

```

![Screenshot 2020-04-27 at 7 46 26 PM](https://user-images.githubusercontent.com/36992338/80383574-5e470600-88c1-11ea-873e-ff897f8fffa1.png)

**Comment by nihp** [comment]
The above is still an issue

**Comment by karimcambridge** [comment]
Yea, we we should be able to do this

**Comment by nihp** [comment]
@karimcambridge Kindly let me know if you have any solution

**Comment by karimcambridge** [comment]
> @karimcambridge Kindly let me know if you have any solution

Lol no.

I got the bottom border looking part removed. The top.. nope. Seems like thats built in...
