### ISSUE TITLE
Upgrading from 0.61.1 to 0.62.2: Library not found for -lReact-RCTActionSheet

### ISSUE THREAD

**Issue by krstffr** [facebook/react-native#28763]
## Description
When upgrading to 0.62.2 from 0.61.1 I get the following error when trying to build the app: `Library not found for -lReact-RCTActionSheet`. I have run `npm i` and `pod install`. 

-lReact-RCTActionSheet is listed in **Link binary with libraries**.

## React Native version:
```System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 636.80 MB / 16.00 GB
    Shell: 2.2.0 - /usr/local/bin/fish
  Binaries:
    Node: 12.16.2 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 11.2.1/11B53 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_121 - /usr/bin/javac
    Python: 2.7.16 - /Users/kristoffer/.local/lib/aws/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: ^0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Have an app at 0.61.1
2. Upgrade to 0.62.2

## Expected Results
The app is upgraded and working.

## Snack, code example, screenshot, or link to a repository:
<img width="777" alt="image" src="https://user-images.githubusercontent.com/93975/80353109-2914c680-8875-11ea-9a2b-d7ee66863879.png">

<img width="776" alt="image" src="https://user-images.githubusercontent.com/93975/80353228-595c6500-8875-11ea-8cf0-6d07c74290a7.png">

**Comment by anhtuank7c** [comment]
I have the same issue while upgrading RN from 0.61.5 to 0.63.3

**Comment by anhtuank7c** [comment]
I found the solution.

Go to `Build Settings` and searching for `OTHER_F`, double click then remove all the thing except these lines in the image bellow

![Screen Shot 2020-10-08 at 22 43 44](https://user-images.githubusercontent.com/3163410/95482431-4e773600-09b8-11eb-9764-b2e456b0c8f1.png)
