### ISSUE TITLE
Running example apps from the latest commit

### ISSUE THREAD

**Issue by woniesong92** [facebook/react-native#2876]
When you do `react-native init AwesomeProject` the pak

`node_modules/react-native/packager/packager.js`

doesn't have any JS6 reserved keywords like `const`. I cloned the latest version of react-native from GitHub, and the packager file located at

`packager/packager.js`

has such keywords. When I try to run an example app from xCode, I get an error

      const dumpName = '/tmp/dump_' + Date.now() + '.json';
      ^^^^^
    SyntaxError: Use of const in strict mode.

and the app fails to run. What can I do to fix this?

**Comment by io3** [comment]
@woniesong92 nodejs@v4.0.0 ?

**Comment by Selayar** [comment]
Thanks​
[image: 1 Maret 2013]1 Maret 2013 2 foto
<https://photos.google.com/album/AF1QipPIX6XtOLTXGacPLp5V-RkgAlqvRXeH9CLmiFU>
​

2015-09-19 18:37 GMT-07:00 io3 <notifications@github.com>:

**Comment by iggied** [comment]
brew install watchman

see https://github.com/facebook/react-native/issues/1920

**Comment by iggied** [comment]
Edit react-native/packager.sh to add the --harmony parameter to the node command. The line should read as follows

node --harmony "$THIS_DIR/packager.js" "$@"

**Comment by ide** [comment]
Sounds like you need to install Node 4, as the Docs say in multiple places.

**Comment by 3210jr** [comment]
I had the same issue and installing node 4 got it working
