### ISSUE TITLE
"Too many open files" error when bundling - watchman installed, ulimit=2048

### ISSUE THREAD

**Issue by dancherb** [facebook/react-native#28761]
I have a lot of images to bundle with my app (a few thousand, as part of an emoji pack), and recently (after further images were added) I'm receiving the following output and error when attempting to create a bundle with the following command:

`react-native bundle --platform=android --dev=false --entry-file=index.js --bundle-output=android/app/src/main/assets/index.android.bundle --assets-dest=android/app/src/main/res
`

**result**

```
Loading dependency graph, done.
Loading dependency graph...info Writing bundle output to:, android/app/src/main/assets/index.android.bundle
info Done writing bundle output
error EMFILE: too many open files, open 'C:\App\node_modules\bugsnag-react-native\package.json'.
Run CLI with --verbose flag for more details.
Error: EMFILE: too many open files, open 'C:\App\node_modules\bugsnag-react-native\package.json'
```

I can see that the latest images have not been added to res and do not show in release builds of the app.

I'm using Git Bash on VSCode on Windows 10. 

I have tried increasing the ulimit open files count with `ulimit -n 2048`. Before increasing the limit, the error showed a different file for the "too many open files" example (unrelated to Bugsnag, the file currently shown).

Watchman is installed, and I have tried re-installing it. Running `watchman.exe -v` returns `4.9.4`. Maybe it's relevant that watchman is not accessible via `watchman -v` without the `.exe`? This seems to be how Bash works on Windows.

## React Native version:
```
System:
    OS: Windows 10 10.0.17763
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 2.35 GB / 7.82 GB
  Binaries:
    Node: 10.15.2 - C:\Program Files\nodejs\node.EXE
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    Watchman: 4.9.4 - C:\AppData\Local\watchman\watchman.EXE
  SDKs:
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 23.0.1, 25.0.0, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.2, 28.0.3, 29.0.0, 29.0.1, 29.0.2
      System Images: android-22 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6308749
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
```

**Comment by fabriziobertoglio1987** [comment]
https://github.com/facebook/create-react-app/issues/4540#issuecomment-393310226
