### ISSUE TITLE
Build Failed IOS - React Native 0.62.2

### ISSUE THREAD

**Issue by DanMCX** [facebook/react-native#28777]
## Description
After installing a new fresh React Native app, and after updating Xcode to version 11.4.1, it keeps crashing with these errors:

**The following build commands failed:**
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
	CompileSwift normal x86_64 /Users/user/Desktop/testing/ios/Pods/YogaKit/YogaKit/Source/YGLayoutExtensions.swift

## System
    OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Memory: 542.31 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.12.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    **react-native: 0.62.2 => 0.62.2** 
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by DanMCX** [comment]
##Development Environment:
OS: macOS 10.15.4
CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
Memory: 542.31 MB / 8.00 GB
Shell: 5.7.1 - /bin/zsh
Binaries:
Node: 13.12.0 - /usr/local/bin/node
Yarn: 1.22.4 - /usr/local/bin/yarn
npm: 6.14.4 - /usr/local/bin/npm
Watchman: 4.9.0 - /usr/local/bin/watchman
Managers:
CocoaPods: 1.9.1 - /usr/local/bin/pod
SDKs:
iOS SDK:
Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
Android SDK: Not Found
IDEs:
Android Studio: 3.6 AI-192.7142.36.36.6241897
Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
npmPackages:
@react-native-community/cli: Not Found
react: 16.11.0 => 16.11.0
react-native: 0.62.2 => 0.62.2
npmGlobalPackages:
react-native: Not Found

**Comment by chrisglein** [comment]
Version being used in circleci is 11.3, whereas this is 11.4.1. It should, but it may be less tested. Anticipate that being upgraded at some point in the future.
Would be helpful to have more of the xcode output if you could supply that? Build logs and such? Also might be helpful to link to a repo of the empty new project just in case there was something else.

**Comment by phamhoaivu911** [comment]
Hi @chrisglein , I have a similar issue. This is my build log from AppCenter.

[17_Xcode build (signed).txt](https://github.com/facebook/react-native/files/4591887/17_Xcode.build.signed.txt)

Please let me know if there's anything I can help with. Thank you!

**Comment by anurbecirovic** [comment]
@DanMCX, i had the same problem. The reason is outdated CocoaPods. After running this command "sudo gem install cocoapods" I deleted old initial project and created new one with "npx react-native init AwesomeProject", after that, everything worked fine.

**Comment by ryndshn** [comment]
i'm having the same problem when generating a new RN app and attempting to run. it seemed to work on the first app i generated, but after closing the metro terminal window and simulator, it started doing this and continues on all of the new apps i generate. it seems to run ok from within Xcode, but not from the terminal.

**Comment by BenHurMartins** [comment]
Hi, I'am having the same issue, since I updated my Mac last night, I can't run my project anymore.

tried to pod update with no effect.

My environment setup:

`System:
    OS: macOS 10.15.5
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 29.47 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.13.1 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.12.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.4 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_232 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found
`

**Comment by MCKmecik** [comment]
I have the same problem after updating macOS and Xcode.

System:
    OS: macOS 10.15.5
    CPU: (4) x64 Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
    Memory: 18.84 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.12.0 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_101 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by MCKmecik** [comment]
@ryndshn Thank you. It is working again after computer restart.

**Comment by lukeramsden** [comment]
Getting this too, it's stopping me from building with Fastlane.

```
System:
    OS: macOS 10.15.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 295.65 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.19.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.3, 30.0.0, 30.0.1
      System Images: android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 12.0/12A7209 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_242 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by pedrocardoz0** [comment]
> i'm having the same problem when generating a new RN app and attempting to run. it seemed to work on the first app i generated, but after closing the metro terminal window and simulator, it started doing this and continues on all of the new apps i generate. it seems to run ok from within Xcode, but not from the terminal.
> 
> edit: i'm sure this isn't helpful, but after restarting my mac it worked as expected

it worked for me

**Comment by destryteeter** [comment]
> i'm having the same problem when generating a new RN app and attempting to run. it seemed to work on the first app i generated, but after closing the metro terminal window and simulator, it started doing this and continues on all of the new apps i generate. it seems to run ok from within Xcode, but not from the terminal.
> 
> edit: i'm sure this isn't helpful, but after restarting my mac it worked as expected

worked for me as well.  I have 2 "sister" apps that work together, both worked fine then suddenly only 1 ran into this issue.

Up to date on the latest packages and development tools.

**Comment by Bardiamist** [comment]
Hmm, today I got it on `0.63.3`. Previously worked fine, seems I updated something (dependency or Xcode) but revert not helping.

**Comment by lukeramsden** [comment]
It's clearly not a local environment issue as I get the same error when running my Fastlane release lane on GitHub actions.

**Comment by Bardiamist** [comment]
Builded by Bitrise successfully but I'd to build also by cli locally:)

**Comment by yj-ang** [comment]
Close all terminal windows and re-open it worked for me.

**Comment by JosePaniagua7** [comment]
> @ryndshn Thank you. It is working again after computer restart.

This good old trick worked for me

**Comment by iocuydi** [comment]
Closing terminals and restarting didn't work for me, nor did uninstalling and reinstalling xcode/npm/brew for a couple different versions of xcode. Not much other info online about this, so what **did** work was backing up my project and reformatting my Mac :upside_down_face:

**Comment by rci20021028** [comment]
WOW!!! Very perfect!!!
I have just restarted my pc and it is working correctly!!!
Thanks for @MCKmecik and @ryndshn.

**Comment by Md-Mudassir** [comment]
> @ryndshn Thank you. It is working again after computer restart.

restarting didn't fix but closed **Xcode** and then deleted **node_modules** and then ran
`npm install`
`cd ios && pod install --repo-update`
` npx react-native run-ios` 

It somehow fixed it

**Comment by Darkiring** [comment]
It worked for me to close all terminals including Visual Studio Code, and closing the emulator. Then the terminal compiled without errors.

**Comment by Navipro70** [comment]
All ways above doesn't help on Mac Apple Silicon m1 :(

**Comment by Navipro70** [comment]
@rhenanteix @leizard something similar was founded in [31941](https://github.com/facebook/react-native/issues/31941)

**Comment by dhamodar** [comment]
**final call** 

- just run `npm start` && `npm run ios(react-native run ios)`

**Comment by ateethk** [comment]
Had this issue as well, turned out to be because I have a space in one of the directory name's that the project is under.

**Comment by mgithubmessier** [comment]
I got this working on my m1 mac by setting up a rosetta terminal to run my react-native run-ios command
https://www.courier.com/blog/tips-and-tricks-to-setup-your-apple-m1-for-development/

**Comment by fellipe-ribeiro** [comment]
- Restart Computer
- Run: yarn start --reset-cache
Worked for me....

**Comment by elmcapp** [comment]
Issue can be closed.All you have to do is close the terminal then reopen it

**Comment by markbell2410** [comment]
> Had this issue as well, turned out to be because I have a space in one of the directory name's that the project is under.

Thank you! I don't know if to cheer or cuss at this stage after spending a long time with this issue!!

I wonder how many of the people who have suffered with this problem had a parent folder labelled "React Native" ☺️

**Comment by JoshuaSunsheng** [comment]
This issue takes me time and try all answers in the Google. Only this page helps me out. Can any developer of facebook to solve this problem or give some tips on the React Native home page?

**Comment by danielreis58** [comment]
It took me two days to resolve this, in my case, the error when running the pod install command was this:

`CompileSwift normal x86_64 (in target 'PurchasesHybridCommon' from project 'Pods')`

**SOLUTION**:

1. Update **react-native-purchases** in package.json **from "^4.3.1" to "^4.6.1"**
2. `rm -rf ios/Pods;`
3. `rm -rf node_modules;`
4. `npm install or cd ios && pod install`

```
System:
    OS: macOS 12.4
    CPU: Apple M1 Pro
Binaries:
    Node: 16.15.1
    npm: 8.11.0
Managers:
    CocoaPods: 1.11.3
npmPackages:
    "react": "16.9.0",
    "react-native": "0.63.4",
```

**Comment by Ruben-Krueger** [comment]
I am still affected by this issue, and unfortunately none of the solutions above work for me.

**Comment by malks14** [comment]
@Ruben-Krueger where you able to solve it?

**Comment by PiyushChandra17** [comment]
@DanMCX did you find the solution? got stuck on the same problem
