### ISSUE TITLE
Stalls on "find dependencies" w/ node warning: Recursive process.nextTick detected

### ISSUE THREAD

**Issue by JAStanton** [facebook/react-native#2878]
Alright so here is the behavior, I created a new project, it installed wonderfully, I open up my project, I build/run simulator. everything works great, I make one change and hit Cmd + R, it reloads, GREAT! I make a second change, I hit reload and it gets stuck. From this point on I don't know how to get myself in a good state. I can kill everything and start it back up again and it works but now from this point on any edits will spam my logs then pause on ` <START> find dependencies` and it will always timeout from this point on.

Logs: https://gist.github.com/JAStanton/170ca0afd47db6d3bdf8
Screenshot: 
<img width="1280" alt="screen shot 2015-09-19 at 7 00 20 pm" src="https://cloud.githubusercontent.com/assets/645300/9978853/1f47c4ce-5f01-11e5-8354-4eb2cc2fa35a.png">

System info, Osx 10.10.5, XCode 7.0,

**Comment by ide** [comment]
What version of Node are you using? (We support only 2.0 and up.)

**Comment by JAStanton** [comment]
```
➜  ~  node -v
v0.10.38
```

**Comment by ide** [comment]
Upgrade your Node (4.0 preferred) and this should be fixed.

**Comment by JAStanton** [comment]
Yup, I did, then dropped my `node_modules` directory and re-ran `npm install` then `npm start` and it worked great :) Thanks!

**Comment by icd2k3** [comment]
Thanks, this helped me as well. Simply re-installing from nodejs.org did the trick.
