### ISSUE TITLE
RN-IOS Not loading images when build 

### ISSUE THREAD

**Issue by ibrahimyolbir** [facebook/react-native#28791]
## Description
After upgrading the react native version(0.62.2), I tried to set up the system with the react-native run-ios but it doesn't load the assets (images)

*Application working fine
*Android working fine
<img width="445" alt="Screenshot 2020-04-29 at 13 29 51" src="https://user-images.githubusercontent.com/25623304/80706379-849aba80-8ae8-11ea-8bb7-b0101aa5935d.png">

## React Native version:
System:
OS: macOS 10.15.3
CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
Memory: 187.51 MB / 16.00 GB
Shell: 5.7.1 - /bin/zsh
Binaries:
Node: 13.11.0 - /usr/local/bin/node
Yarn: Not Found
npm: 6.13.7 - /usr/local/bin/npm
Watchman: 4.9.0 - /usr/local/bin/watchman
Managers:
CocoaPods: 1.9.1 - /usr/local/bin/pod
SDKs:
iOS SDK:
Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
Android SDK: Not Found
IDEs:
Android Studio: 3.6 AI-192.7142.36.36.6241897
Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
Languages:
Java: 1.8.0_242 - /usr/bin/javac
Python: 2.7.16 - /usr/bin/python
npmPackages:
@react-native-community/cli: Not Found
react: ^16.13.1 => 16.13.1
react-native: ^0.62.2 => 0.62.2
npmGlobalPackages:
react-native: Not Found

 ## Steps To Reproduce
1- Before build the system i removed ios/build folder everytime
2- Removed mainjs.bundle
3- react-native bundle --entry-file='index.js' --bundle-output='./ios/main.jsbundle' --dev=false --platform='ios' --assets-dest='./ios'
4- Xcode "project name" > targets > build phases > Copy bundle resources try to add "assets" folder here

## Expected Results
![WhatsApp Image 2020-04-30 at 13 45 23](https://user-images.githubusercontent.com/25623304/80706648-ebb86f00-8ae8-11ea-8bbe-1d9afc09e15e.jpeg)

**Comment by RageBill** [comment]
Same issue here, only happens to iOS but not Android. Looking for solution.

**Comment by SmartRefillAndroid** [comment]
Hi @RageBill 
What kind of problem you have, i will try to help if you share detailed information

My problem was that the '**react-native-webp-support**' plugin was not supported in the top versions of React Native for images with a .webp extension. I used **react-native-webview** instead

**Comment by ibrahimyolbir** [comment]
Hi @RageBill 
What kind of problem you have, i will try to help if you share detailed information

My problem was that the **'react-native-webp-support'** plugin was not supported in the top versions of React Native for images with a .webp extension. I used **react-native-webview** instead

**Comment by RageBill** [comment]
I was trying to upgrade from RN 0.61.5 to 0.62.2.

After upgrading with compliance to [RN upgrade helper](https://react-native-community.github.io/upgrade-helper/), everything worked fine on my local development simulators (both Android and iOS).

Once deployed to production, it happens that only for iOS the image assets loaded locally were missing. I did not use webp, and my images were `.png`. I tried both with RN's `Image` component and `[react-native-fast-image](https://github.com/DylanVann/react-native-fast-image)`'s `FastImage` component, both unsuccessful in solving this problem.

**Comment by RageBill** [comment]
After some digging, I realize my problem was with [this](https://github.com/react-native-community/upgrade-support/issues/26).

The images required inside project root folder were correctly shown all-along, but those outside of the project root were not. I was using a monorepo structure for my project, so some of the shared-assets were outside of the project root folder. And that's where the problem came from.

Thanks for helping anyway! Hope this will help whoever faces the same problem.

**Comment by vanGalilea** [comment]
We're having sort of the same issue on iOS only in PROD, but we're using a **_url_** and **_base64_** in the images and nothing shows up.

Any ideas guys?

**Comment by vanGalilea** [comment]
can @ASCE1885 reopen this please?
