### ISSUE TITLE
EdgeLight: Screen borders are not going beyond the notch and softkeys

### ISSUE THREAD

**Issue by sanjeevkse** [facebook/react-native#28793]
I am just trying to implement "edge light" [Ref](https://play.google.com/store/apps/details?id=com.edgeround.lightingcolors.rgb&hl=en) in react native. 

**Environment:** 
It happens in Android.
System:
    OS: Windows 10 10.0.18362
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
    Memory: 5.31 GB / 11.89 GB
  Binaries:
    Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.2 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6241897
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5

I have this below code to achieve it. 
`<Layout style={{ flex: 1, paddingTop: 18, paddingBottom: 18, paddingLeft: 28, paddingRight: 28, borderWidth: 10, borderColor: '#36ABA5', justifyContent: 'center', backgroundColor: '#000', color: '#fff' }}>
// All my code
</Layout>
`
This seems to be working fine for the mobiles which are having straigh screens. But I am facing 2 issues,

1. The same is not working when the mobile has notch or the mobile's softkeys are enabled. 
2. in Honor 8x the border itself is not coming when softkeys are disabled, when those are enabled, the border comes above the softkeys, 

I tried calculating the window height, screen height and put the border. It seems to be not happening.

## In Straight phone: 
![imageedit_6_7381619458](https://user-images.githubusercontent.com/4029801/80741370-26e18f00-8b37-11ea-8247-fe9742366d77.jpg)

## In Notch phone:
![imageedit_2_9850327413](https://user-images.githubusercontent.com/4029801/80741389-2e089d00-8b37-11ea-8be3-4d3f3c2831f6.jpg)

## In Softkeys enabled:
![imageedit_8_4677322059](https://user-images.githubusercontent.com/4029801/80741403-32cd5100-8b37-11ea-9db0-da0ec68ec61b.jpg)

## In Softkeys disabled:
![imageedit_10_9665714475](https://user-images.githubusercontent.com/4029801/80741415-37920500-8b37-11ea-8291-ec341ef5bf01.jpg)

## Wanted similar to this, but not colorful/ Expected Results: 
![imageedit_4_2716283588](https://user-images.githubusercontent.com/4029801/80741426-3c56b900-8b37-11ea-94cd-84c5496c817f.jpg)

**Comment by sanjeevkse** [comment]
Hi, Please help me here.

**Comment by sanjeevkse** [comment]
Hi

**Comment by sanjeevkse** [comment]
Please help me for this

**Comment by safaiyeh** [comment]
Hi @sanjeevkse sorry you haven't been getting a response! Could you provide a repo that demonstrates the error you are having?
