### ISSUE TITLE
finished callback doesn't run with Animated.loop and useNativeDriver: true

### ISSUE THREAD

**Issue by AndrewMorsillo** [facebook/react-native#28799]
The finish callback never runs when stopping an Animated.loop that's using the native driver. Finish callback runs as expected with useNativeDriver: false

## React Native version:
```
System:
    OS: Windows 10 10.0.19613
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
    Memory: 8.87 GB / 31.93 GB
  Binaries:
    Node: 10.18.1 - ~\AppData\Local\Temp\yarn--1588347676709-0.3825794711513324\node.CMD
    Yarn: 1.22.4 - ~\AppData\Local\Temp\yarn--1588347676709-0.3825794711513324\yarn.CMD
    npm: 6.13.4 - C:\dev\tools\nodejs\npm.CMD
    Watchman: 4.9.4 - C:\dev\tools\watchman\watchman.EXE
  SDKs:
    Android SDK:
      Android NDK: 21.0.6113669
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 12.0.2 - C:\Users\imagi\scoop\apps\openjdk12\current\bin\javac.EXE
    Python: 2.7.17 - C:\dev\Python27\python.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. call `.start(() => console.log("Finish"))` on an Animated.loop with useNativeDriver: true
2. Call .stop() on the animation, the finish callback will not run

## Expected Results
The finish callback should run per the docs here: https://reactnative.dev/docs/animated#start

## Snack, code example, screenshot, or link to a repository:
Snack: https://snack.expo.io/1dtES!THV
Note that Animated.loop doesn't seem to work on web, run on a device to see issue

**Comment by IyiolaOwabumowa** [comment]
This issue still happens in June 2021
