### ISSUE TITLE
[RootView] RCTRootView initializer has problems when configuring the executor

### ISSUE THREAD

**Issue by ide** [facebook/react-native#288]
The new RCTRootView initializer takes the bundle URL and calls `-[loadBundle]` immediately. This creates the bridge and executor, giving no time for the code to customize the executor. A cheap fix would be to use dispatch_async in `setScriptURL:` before loading the bundle but I think ultimately the root view should require a call to loadBundle or reload in the app delegate to kick off the initial load.

**Comment by facebook-github-bot-3** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
