### ISSUE TITLE
Invariant Violation: Module RCTDeviceEventEmitter is not a registered callable module

### ISSUE THREAD

**Issue by piiih** [facebook/react-native#28801]
## Description
I'm trying to create a fresh `react-native` project with a fresh native module without any new code. I installed the `MyLibrary` into `MyApp` using `yarn add file:/path/to/module`, I don't know if it could be the problem :/

![image](https://user-images.githubusercontent.com/8054607/80845081-98284d00-8bde-11ea-86bf-97ec8b20df22.png)

## React Native version:
System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 452.77 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.16.3 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 22, 23, 25, 27, 28
      Build Tools: 25.0.3, 26.0.2, 28.0.3
      System Images: android-28 | Intel x86 Atom_64
      Android NDK: 19.2.5345600
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_252 - /usr/bin/javac
    Python: 2.7.16 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found

I'm using `react-native` CLI from `npx`.

## Steps To Reproduce
I just did exactly what is in this guide https://reactnative.dev/docs/native-modules-setup and when I try to run my app on my phone I got the screenshot error.

**Comment by piiih** [comment]
I'm using `react-native` CLI from `npx`.

**Comment by AngeloMateus** [comment]
I'm having this issue as well

**Comment by alex521** [comment]
+1

**Comment by ChannelJuanNews** [comment]
+1

**Comment by leonzalion** [comment]
I experienced this problem as well, and after a whole day of trying to fix the problem, what worked for me was changing the dependencies in the package.json of MyLibrary so that all that was left was:
```
"peerDependencies": {
  "react-native": "^0.62.2"
}
```
without `devDependencies` nor `dependencies`. Make sure you also remove `node_modules` after making this change in MyLibrary. This is what the directory structure of MyLibrary (I called it MusicKit) looked like for me after I got it working:

![Screenshot from 2020-06-25 08-06-51](https://user-images.githubusercontent.com/36966635/85716834-d7dd5380-b6ba-11ea-97c1-e78216156517.png)

And here is a screenshot of the package.json:

![Screenshot from 2020-06-25 08-07-58](https://user-images.githubusercontent.com/36966635/85716964-ff342080-b6ba-11ea-8cf7-b35f5bf400b0.png)

**Comment by gokul-t** [comment]
I'm having this issue as well

**Comment by safaiyeh** [comment]
Hi @piiih thank you for the issue. Could you provide a repro that consistently demonstrates this error?

**Comment by DeepRolling** [comment]
I have same issue , in my condition , it cause by i update my node version . 
solution : delete all node_modules which already downloaded ,and run "yarn install" command for re-install them .
then they will be work .

**Comment by luatnd** [comment]
I have same issue:
> Invariant Violation: Module RCTLog is not a registered callable module (calling logIfNoNativeHook)

It only occur on remote debugging mode, if you disable remote debugging in dev mode, it's still work

**Comment by michaelgmcd** [comment]
Make sure you have one version of react-native installed. `npm ls react-native` should help.

**Comment by cristiangu** [comment]
> If it helps anyone:
> 
> **metro.config.js**
> 
> ```js
> const path = require("path");
> const watchFolders = [
>   //Relative path to packages directory because I'm in yarn workpspaces
>   path.resolve(__dirname + "/../.."),
> ];
> module.exports = {
>   resolver: {
>     extraNodeModules: {},
>   },
>   transformer: {
>     getTransformOptions: async () => ({
>       transform: {
>         // this defeats the RCTDeviceEventEmitter is not a registered callable module
>         inlineRequires: true,
>       },
>     }),
>   },
>   watchFolders,
> };
> ```
> 
> ```shell
> react-native start --reset-cache
> ```

This helped me to fix it!

Many many many thanks! 🙏🙏🙏

**Comment by arled** [comment]
Surely this cannot be the fix right?
