### ISSUE TITLE
Task :app:lintVitalRelease FAILED

### ISSUE THREAD

**Issue by hrezah** [facebook/react-native#28804]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
when I trying to release a apk using assembleRelease command . it shows the error below : 

> Task :app:lintVitalRelease FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:lintVitalRelease'.
> Could not resolve all files for configuration ':app:lintClassPath'.
   > Could not find lint-gradle-26.5.2.jar (com.android.tools.lint:lint-gradle:26.5.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint-gradle/26.5.2/lint-gradle-26.5.2.jar
   > Could not find lint-26.5.2.jar (com.android.tools.lint:lint:26.5.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint/26.5.2/lint-26.5.2.jar
   > Could not find lint-checks-26.5.2.jar (com.android.tools.lint:lint-checks:26.5.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint-checks/26.5.2/lint-checks-26.5.2.jar
   > Could not find lint-api-26.5.2.jar (com.android.tools.lint:lint-api:26.5.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint-api/26.5.2/lint-api-26.5.2.jar
   > Could not find intellij-core-26.5.2.jar (com.android.tools.external.com-intellij:intellij-core:26.5.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/external/com-intellij/intellij-core/26.5.2/intellij-core-26.5.2.jar
   > Could not find kotlin-compiler-26.5.2.jar (com.android.tools.external.com-intellij:kotlin-compiler:26.5.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/external/com-intellij/kotlin-compiler/26.5.2/kotlin-compiler-26.5.2.jar       
   > Could not find uast-26.5.2.jar (com.android.tools.external.org-jetbrains:uast:26.5.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/external/org-jetbrains/uast/26.5.2/uast-26.5.2.jar

## React Native version:
React native V .62.2

## Expected Results
relase apk as usual . without any error

**Comment by ghasemikasra39** [comment]
Same here with react native 0.62.2
```
System:
    OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 135.38 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.12.1 - ~/.nvm/versions/node/v12.13.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_232 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```
Any solution?

**Comment by ghasemikasra39** [comment]
Dear @hrezah. From 2nd have you found any solution for this?

**Comment by ghasemikasra39** [comment]
Found a solution. Just delete `android/app/build/outputs/apk/release/output.json`

**Comment by safaiyeh** [comment]
@hrezah thank you for the issue and @ghasemikasra39 thank you for providing a solution!

Closing for now, feel free to open another issue if this comes up again

**Comment by Lloyd1229** [comment]
请问解决了吗

**Comment by hufans** [comment]
app -> build.gradle -> add     lintOptions {
        checkReleaseBuilds false
        abortOnError false
    } to android
