### ISSUE TITLE
Unsupported node type: param

### ISSUE THREAD

**Issue by RitikaSrivastava11oct** [facebook/react-native#28803]
After yarn start on the console , my React native app's home page does not appear 
rather it shows a page with message unsupported node type:param.
Though no error logs are printed on console.
Please find screenshot of the error.
![IMG_20200502_113922](https://user-images.githubusercontent.com/30169218/80856701-b5562d80-8c69-11ea-9669-8ba10172a0b5.jpg)

**Comment by Jumail** [comment]
I'm having the same issue right now. Have you found a fix for this?
