### ISSUE TITLE
 App stuck in splash on xcode11.4.1 [IOS]

### ISSUE THREAD

**Issue by ashryOlarm** [facebook/react-native#28816]
## Description
My App is working fine on xcode10.1, but when i'm running my App on xcode11.4.1 it stuck into splash screen.

## React Native version:
 React Native version: 0.57.1

## Steps To Reproduce
1. Running my App with xcode11.4.1 

## Expected Results
App should working fine

## Snack, code example, screenshot, or link to a repository:
<img width="728" alt="Screen Shot 2020-05-03 at 11 45 58 AM" src="https://user-images.githubusercontent.com/43812016/80911130-b6a05c80-8d34-11ea-83dc-e1e249603947.png">
<img width="695" alt="Screen Shot 2020-05-03 at 11 47 53 AM" src="https://user-images.githubusercontent.com/43812016/80911171-fa936180-8d34-11ea-8ce4-1502ac855c4f.png">

**Comment by troZee** [comment]
You need to update your project to 0.60 to fix it. Alternatively as workaround, you can use patch-package and copy/paste code, which fix this error (you can easy find this code snippet in google).
