### ISSUE TITLE
Catalyst + ReactNative: Typedef redefinition with different types ('uint8_t' (aka 'unsigned char') vs 'enum clockid_t') error when building for mac target

### ISSUE THREAD

**Issue by 0xmtn** [facebook/react-native#28810]
## Description
I'm getting the  following errors when building for mac. This is a default application, created via `react-native init`.
Error 1: `Typedef redefinition with different types ('uint8_t' (aka 'unsigned char') vs 'enum clockid_t')`
Error 2: `ld: in /Users/jh/Documents/projects/VST/Trial3/ios/Pods/OpenSSL-Universal/ios/lib/libcrypto.a(cryptlib.o), building for Mac Catalyst, but linking in object file built for iOS Simulator, file '/Users/jh/Documents/projects/VST/Trial3/ios/Pods/OpenSSL-Universal/ios/lib/libcrypto.a' for architecture x86_64`

## React Native version:
```
MacOS: 10.15.4
Xcode: 11.4
RN: 0.62.0-rc.5
RN Cli: 4.8.0
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. `react-native init App`
2. `react-native run-ios` - Works fine
3. Open `App.xcworkspace`, select mac as a target and clean build.

## Expected Results
Application working on Mac too.

## Snack, code example, screenshot, or link to a repository:
![image](https://user-images.githubusercontent.com/732147/80891844-5b884e80-8ccf-11ea-9375-4e8993a77744.png)

I commented out the following line in Time.h:
```
//typedef uint8_t clockid_t;
extern "C" int clock_gettime(clockid_t clk_id, struct timespec* ts);
extern "C" int clock_getres(clockid_t clk_id, struct timespec* ts);
#endif
```

Then tried to build again and the Error 1 disappeared but Error 2 still exists:
![image](https://user-images.githubusercontent.com/732147/80891902-b4f07d80-8ccf-11ea-869f-2443dde60b80.png)

Should I do something for migration to build for mac?

**Comment by 0xmtn** [comment]
I got it working by deleting Facebook Flipper and everything else related to it. Here are the steps to take: 
1. Open Podfile and delete everything related to Flipper and FlipperKit. There are some post-install functions, delete them too.
2. `rm -Rf Pods/*`
3. `pod cache clean --all`
4. Open AppDelegate.m and delete everything inside `DEBUG`.
5. Hit Run and voila. 

![image](https://user-images.githubusercontent.com/732147/80952724-ca19f900-8e02-11ea-9087-b8ea6489af41.png)

**Comment by RSRajendra** [comment]
Just Comment 
use_flipper!() function inside pod files 
remove Pods and podfile.lock

again pod install worked for me
