### ISSUE TITLE
Blank screen in debug mode after update RN 0.54 to 0.59.5

### ISSUE THREAD

**Issue by vojeda** [facebook/react-native#28818]
## Description
After updating RN 0.54 to 0.59.5 the android emulator doesn't work. The application works well in release mode but debug mode does not load, this only happens in Android, IOS works correctly.

I use a react-native-navigation ^ 1.1.493, but not if that will be since it would not work in release mode. Does anyone have any idea what might be going on?.  Help me please!

## React Native version:
  React Native Environment Info:
    System:
      OS: macOS 10.15.2
      CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
      Memory: 315.73 MB / 16.00 GB
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.1 - /usr/local/bin/node
      npm: 6.13.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
      Android SDK:
        API Levels: 23, 24, 25, 26, 27, 28, 29
        Build Tools: 23.0.1, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.3, 28.0.0, 28.0.2, 28.0.3, 29.0.0
        System Images: android-28 | Google Play Intel x86 Atom, android-29 | Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5900203
      Xcode: 11.3/11C29 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.5 => 0.59.5 
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.
1. Updating RN 0.54 to 0.59.5
2. Launch app in debug mode

## Expected Results
The application should start correctly

## Snack, code example, screenshot, or link to a repository:
![image](https://user-images.githubusercontent.com/9805049/80930408-64d1f380-8d81-11ea-8808-795977fcc41f.png)

![image](https://user-images.githubusercontent.com/9805049/80930402-5e437c00-8d81-11ea-9cbf-806f013c3ddb.png)

Log Genymotion
![image](https://user-images.githubusercontent.com/9805049/80930505-fb9eb000-8d81-11ea-843a-a930dec756a6.png)

05-04 00:09:56.628 I/Chrome_DBThread( 1829): type=1400 audit(0.0:3245): avc: denied { read } for name="app_webview" dev="sdb3" ino=81952 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:system_data_file:s0:c512,c768 tclass=dir permissive=1
05-04 00:09:56.628 I/Chrome_DBThread( 1829): type=1400 audit(0.0:3246): avc: denied { open } for path="/data/data/com.testreactnative.app/app_webview" dev="sdb3" ino=81952 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:system_data_file:s0:c512,c768 tclass=dir permissive=1
05-04 00:09:56.650 W/zygote  ( 1829): Long monitor contention with owner main (1829) at void com.android.webview.chromium.WebViewChromiumFactoryProvider$1.run()(WebViewChromiumFactoryProvider.java:375) waiters=1 in void java.lang.Object.wait() for 378ms
05-04 00:09:56.656 I/netd    (  330): type=1400 audit(0.0:3247): avc: denied { getopt } for path="/dev/socket/fwmarkd" scontext=u:r:netd:s0 tcontext=u:r:init:s0:c512,c768 tclass=unix_stream_socket permissive=1
05-04 00:09:56.656 I/netd    (  330): type=1400 audit(0.0:3248): avc: denied { read } for path="/dev/socket/fwmarkd" scontext=u:r:netd:s0 tcontext=u:r:init:s0:c512,c768 tclass=unix_stream_socket permissive=1

 _I leave the Genymotion log but no "Exception" appears that could give a new one. I just see it repeating **Couldn't load memtrack module**_

**Comment by adsalihac** [comment]
yarn start
