### ISSUE TITLE
Broken Cyrillic symbols support in TextInput with custom fonts. RN 0.62[iOS]

### ISSUE THREAD

**Issue by seniv** [facebook/react-native#28829]
## Description
In iOS, when I type any Cyrillic letter in TextInput with custom font family that doesn't have Cyrillic symbols support then text in input starts flickering(see gif below).
At every odd symbol in TextInput, all Cyrillic symbols just disappear

This issue appears in 0.62. On version 0.61 and below it works fine
![img](https://i.imgur.com/LTfiCth.gif)

## React Native version:
```
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Memory: 42.68 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.17.0 - ~/.nvm/versions/node/v10.17.0/bin/node
    Yarn: 1.19.2 - /usr/local/bin/yarn
    npm: 6.11.3 - ~/.nvm/versions/node/v10.17.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.4 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5977832
    Xcode: 11.4/11E146 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.5 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Init RN 0.62.* project `npx react-native init AwesomeProject`
2. link some font that doesn't support Cyrillic symbols
3. Use that font in `TextInput`
4. Write any Cyrillic text in the input

## Expected Results
A font that doesn't support Cyrillic shouldn't flicker in TextInput, as it was in RN 0.61 and below

## Snack, code example, screenshot, or link to a repository:
You can try these fonts from my example:
[Modak](https://fonts.google.com/specimen/Modak?preview.text=hello+world+%D0%BA%D0%B8%D1%80%D0%B8%D0%BB%D0%B8%D1%86%D1%8F&preview.text_type=custom&query=Modak) 
[Pacifico](https://fonts.google.com/specimen/Pacifico?preview.text=hello+world+%D0%BA%D0%B8%D1%80%D0%B8%D0%BB%D0%B8%D1%86%D1%8F&preview.text_type=custom)
```javascript
<Text style={styles.footer}>Modak: Doesnt support cyrillic</Text>
<TextInput style={{fontFamily: 'Modak'}} placeholder="Modak Font" />
<Text style={styles.footer}>Pacifico: Support cyrillic</Text>
<TextInput style={{fontFamily: 'Pacifico'}} placeholder="Pacifico Font" />
```

**Comment by MargaritaZagalets** [comment]
I have the same issue

**Comment by davx1992** [comment]
Hi also having the same issue. Interesting thing is that when I set multiline then it works without flickering.

**Comment by fabriziobertoglio1987** [comment]
I wanted to ask if you still experience this issue. 
I'm planning to do 1-2 months of opensource and I'm preparing a list of tasks.

I have been contributing to facebook/react-native for 4 years and I specialize on the Text/TextInput components.

Thanks a lot
