### ISSUE TITLE
Websocket work in debug version, but not in release version

### ISSUE THREAD

**Issue by Hugogsalas** [facebook/react-native#28821]
## Description
I was developing an app with a websocket connection with IOT devices, in the debug version all works, but when I install the release version, my app can't make the connection.

## React Native version:
RN 62.2

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.this.ws = new WebSocket(`ws://${direction}/`);
2.Test in debug app and all is right
3.Test in realease app and dosen´t work

## Expected Results
Make a successful connection

## Snack, code example, screenshot, or link to a repository:
      this.ws = new WebSocket(`ws://${direction}/`);
      this.ws.onopen = () => {
                this.ws.onmessage = (e) => {
                let data = JSON.parse(e.data)
                console.log(data)
                if (data.Exito) {
                    if (data.Temperature) {
                        this.updateTemperature(data.Temperature)
                    }
                    else if (data.EstadoInfra !== undefined) {
                        this.onInfraRed(data.EstadoInfra)
                    }
                    else if (data.EstadoLight !== undefined) {
                        this.onLight(data.EstadoLight)
                    }
                }

            };

            this.ws.onerror = (e) => {
                console.log(e.message);
                this.setState({
                    websocketAvaible: false
                })
                BackgroundTimer.clearInterval(temperatureCheck)
                temperatureCheck = null
                this.ws = null;
            };

            this.ws.onclose = (e) => {
                console.log(e.code, e.reason);
            };

            temperatureCheck = BackgroundTimer.setInterval(() => {
                this.ws.send("T")
            }, 3000)

            this.setState({
                websocketAvaible: true
            })
        }

I tried to use socket.io, but i got the same result

this.ws=io(`ws://${direction}:80/`, { transports: ['websocket'], forceNew: true });

**Comment by Hugogsalas** [comment]
Someone knows if this error have fix??? I tried to test with a new app, but the issue still appear

**Comment by troZee** [comment]
Websocket only works for debug version. You can change it on native side. Just find a code responsible for connecting to websocket and Voila

**Comment by Hugogsalas** [comment]
OK, thanks for the information @troZee , I think is necesary add this detail into the networking page, because there dont say that, i fix my problem creating a tcp connection, but I would have preferred use websockets directly in the react native code.
