### ISSUE TITLE
react native paper require cycle warnings

### ISSUE THREAD

**Issue by khaledBou** [facebook/react-native#28830]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
I tried to use react native paper components for my react native applications.
Currently i use  `"react-native-paper": "^3.9.0",`
I launched the application in Android mobile
I got warnings 
`[Tue May 05 2020 13:06:41.270]  WARN     Require cycle: node_modules\react-native-paper\lib\module\components\Checkbox\Checkbox.js -
> node_modules\react-native-paper\lib\module\components\Checkbox\CheckboxItem.js -> node_modules\react-native-paper\lib\module\compo
nents\Checkbox\Checkbox.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
[Tue May 05 2020 13:06:41.272]  WARN     Require cycle: node_modules\react-native-paper\lib\module\components\FAB\FAB.js -> node_mod
ules\react-native-paper\lib\module\components\FAB\FABGroup.js -> node_modules\react-native-paper\lib\module\components\FAB\FAB.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
[Tue May 05 2020 13:06:41.273]  WARN     Require cycle: node_modules\react-native-paper\lib\module\components\RadioButton\RadioButto
n.js -> node_modules\react-native-paper\lib\module\components\RadioButton\RadioButtonItem.js -> node_modules\react-native-paper\lib\
module\components\RadioButton\RadioButton.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
[Tue May 05 2020 13:06:41.273]  WARN     Require cycle: node_modules\react-native-paper\lib\module\components\Appbar\Appbar.js -> no
de_modules\react-native-paper\lib\module\components\Appbar\AppbarHeader.js -> node_modules\react-native-paper\lib\module\components\
Appbar\Appbar.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
[Tue May 05 2020 13:06:41.273]  WARN     Require cycle: node_modules\react-native-paper\lib\module\components\ToggleButton\ToggleBut
ton.js -> node_modules\react-native-paper\lib\module\components\ToggleButton\ToggleButtonRow.js -> node_modules\react-native-paper\l
ib\module\components\ToggleButton\ToggleButton.js`
## React Native version:
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 12.35 GB / 23.88 GB
  Binaries:
    Node: 12.16.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 27, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-28 | Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: 20.0.5594570
  IDEs:
    Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6241897
  Languages:
    Java: 1.8.0_211 - /c/Program Files/Java/jdk1.8.0_211/bin/javac
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce

1. yarn add react-native-paper
2. react-native run-android

## Expected Results
I don't want to see warnings about react native paper

**Comment by khaledBou** [comment]
![react-native-paper](https://user-images.githubusercontent.com/39246997/81062973-44b44880-8ed7-11ea-96d9-81ca5c799f74.png)

**Comment by thymikee** [comment]
Hey! Please file this issue at https://github.com/callstack/react-native-paper. Thanks! :) cc @Trancever @satya164
