### ISSUE TITLE
Invariant Violation: requireNativeComponent:"***" was not found in theUIManager

### ISSUE THREAD

**Issue by liyuewen** [facebook/react-native#28836]
在MyWebViewManager.java中
`
public class MyWebViewManager extends SimpleViewManager<TextView> {

  public static final String REACT_CLASS = "MyWebViewManager";

  @Override
  public String getName() {
      return REACT_CLASS;
  }

  @Override
  protected TextView createViewInstance(ThemedReactContext reactContext) {
      TextView tv = new TextView(reactContext);
      tv.setText("hello from android !");
      return tv;
  }
}
`

在MyWebViewPackage.java中
`
public class MyWebViewPackage implements ReactPackage {

  @Override
  public List<ViewManager> createViewManagers(ReactApplicationContext reactContext) {
      return Collections.emptyList();
  }

  @Override
  public List<NativeModule> createNativeModules(
          ReactApplicationContext reactContext) {
      List<NativeModule> modules = new ArrayList<>();

      modules.add(new MyWebViewManager());

      return modules;
  }

}
`

在ScannerView.js中
`
import React, { Component } from 'react'
import { View, requireNativeComponent } from 'react-native'

const MyWebViewManager = requireNativeComponent('MyWebViewManager', ScannerView);

class ScannerView extends Component {
    render() {
        return <MyWebViewManager />
    }
}

ScannerView.propTypes = {
    ...View.propTypes
}

export default ScannerView
`
在模拟器中发生错误
Invariant Violation: requireNativeComponent:"MyWebViewManager" was not found in theUIManager.

**Comment by liyuewen** [comment]
我的环境信息
System:
    OS: Windows 10 10.0.17763
    CPU: (8) x64 Intel(R) Core(TM) i7-4710MQ CPU @ 2.50GHz
    Memory: 2.90 GB / 7.89 GB
  Binaries:
    Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 23, 25, 27, 28, 29
      Build Tools: 23.0.1, 27.0.3, 28.0.3, 29.0.2
      System Images: android-23 | Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5791312
  Languages:
    Java: 1.8.0_221
    Python: 2.7.12
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by TheHothihi** [comment]
在MyWebViewPackage.java中, 需要將MyWebViewManager 添加到createViewManagers method之中,
如果只添加到createNativeModules method之中,只能在NativeModules中使用

`
public class MyWebViewPackage implements ReactPackage {

@override
public List createViewManagers(ReactApplicationContext reactContext) {
 /* 添加到createViewManagers method之後才能在requireNativeComponent中引用*/
  List modules = new ArrayList<>();
  modules.add(new MyWebViewManager());
  return modules;
//return Collections.emptyList();
}

@override
public List createNativeModules(
ReactApplicationContext reactContext) {
 /* 添加到createViewManagers method之後才能在NativeModules中引用, eg.NativeModules. MyWebViewManager */
  List modules = new ArrayList<>();
  modules.add(new MyWebViewManager());
  return modules;
}

}
`

**Comment by liyuewen** [comment]
> 在MyWebViewPackage.java中，需要将MyWebViewManager添加到createViewManagers方法之中，
> 如果只添加到createNativeModules方法之中，只能在NativeModules中使用
> 
> `
> 公共类MyWebViewPackage实现了ReactPackage {
> 
> @override
> public List createViewManagers（ReactApplicationContext reactContext）{
> / *添加到createViewManagers方法之后才能在requireNativeComponent中引用* /
> 列表模块= new ArrayList <>（）;
> modules.add（new MyWebViewManager（））;
> 返回模块；
> //返回Collections.emptyList（）;
> }
> 
> @override
> public List createNativeModules（
> ReactApplicationContext reactContext）{
> / *添加到createViewManagers方法之后才能在NativeModules中引用，例如。NativeModules。MyWebViewManager * /
> 列表模块= new ArrayList <>（）;
> modules.add（new MyWebViewManager（））;
> 返回模块；
> }
> 
> }
> `

我已经找到问题了，是我js注册的时候发生了问题，但是还是感谢哦。
