### ISSUE TITLE
Jest-"How to test Native Modules using jest"

### ISSUE THREAD

**Issue by venkataluri** [facebook/react-native#28839]
Hi ,

NativeModules unit test with jest

react: 16.9.0 => 16.9.0 
react-native: 0.61.4 => 0.61.4 

I am using react native **Native Module** code in my project.
I am facing difficulty in writing unit tests for Native module code.
Below is my code, i want to run tests for **NativeModules.EncryptPassword.encryptPassword** and **login** mutation
```
//LoginPage.js

const LoginPage = ({navigation, ...props}) => { 

const [**login**, {loading, error}] = useMutation(Queries.GET_USER_LOGIN)
 return (
  <TouchableOpacity 
          style={styles.login}
          onPress={() => {
             NativeModules.EncryptPassword.encryptPassword( values.password, (value) => {
                  console.log("NativeModules encryptPassword is " + value)
                  encrypPassword = value;
                  let json = {
                    Email: 'test@gmail.com',
                    Password: encrypPassword,
                  };

                  login({
                    variables: {
                      input: json,
                    },
                  });
                })
          }} >
            <Text> Login </Text>
    </TouchableOpacity>  
 )
};
export default LoginPage;
```
Can anyone help me in creating  unit test cases for the above.

Thanks

**Comment by troZee** [comment]
You cannot test native modules using Jest. You need to do it on native side. 
If you want to test JS part, you need to mock native module and check, if proper method has been called once button clicked. 

Probably this issue should be moved to Jest repo. 
cc @thymikee

**Comment by thymikee** [comment]
From the JS point of view, all you can do is to mock `NativeModules.EncryptPassword` using JS implementation. It's sometimes all you need to do, but if you want to test what's happening on native side, you'll either need to write native unit tests, or e2e tests with Detox, Appium, or some other solution.

Here's how to mock NativeModules:
```js
jest.mock("react-native", () => {
  const RN = jest.requireActual("react-native"); // use original implementation, which comes with mocks out of the box

  // mock modules/components created by assigning to NativeModules
  RN.NativeModules.ReanimatedModule = {
    configureProps: jest.fn(),
    createNode: jest.fn(),
    connectNodes: jest.fn(),
    connectNodeToView: jest.fn()
  };

  // mock modules created through UIManager
  RN.UIManager.getViewManagerConfig = name => {
    if (name === "SomeNativeModule") {
      return {someMethod: jest.fn()}
    }
    return {};
  };
  return RN;
});
```
