### ISSUE TITLE
Invariant Violation: Native module cannot be null. (IOS) 

### ISSUE THREAD

**Issue by gaminilesh** [facebook/react-native#28849]
Hi there, I have an issue with upgrading the react-native version from 0.59.10 to 0.62.2. We are using our own native modules and it seems like to be a problem with them. This problem I have only on iOS.

## React Native version:
System:
    OS: macOS 10.15.1
    CPU: (4) x64 Intel(R) Core(TM) i5-4308U CPU @ 2.80GHz
    Memory: 37.41 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.2 AI-181.5540.7.32.5056338
    Xcode: 11.3.1/11C505 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.1 - /usr/bin/javac
    Python: 2.7.16 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^16.11.0 => 16.13.1 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found

## Package.json
{
  "name": "myapp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-community/async-storage": "^1.9.0",
    "@react-native-community/datetimepicker": "^2.3.2",
    "@react-native-community/masked-view": "^0.1.9",
    "@react-native-community/netinfo": "^5.7.1",
    "@react-navigation/bottom-tabs": "^5.2.7",
    "@react-navigation/compat": "^5.1.10",
    "@react-navigation/drawer": "^5.5.0",
    "@react-navigation/native": "^5.1.6",
    "@react-navigation/stack": "^5.2.11",
    "axios": "^0.19.2",
    "core-js": "^3.6.5",
    "data.task": "^3.1.2",
    "moment": "^2.24.0",
    "react": "^16.11.0",
    "react-native": "0.62.2",
    "react-native-actionsheet": "^2.4.2",
    "react-native-audio": "^4.3.0",
    "react-native-background-upload": "^5.6.1",
    "react-native-cached-image": "^1.4.3",
    "react-native-elements": "^1.2.7",
    "react-native-fetch-blob": "^0.10.8",
    "react-native-firebase": "^5.6.0",
    "react-native-fs": "^2.16.6",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-get-random-values": "^1.4.0",
    "react-native-google-cast": "^3.3.0",
    "react-native-google-places": "^3.1.2",
    "react-native-image-crop-picker": "^0.28.0",
    "react-native-image-picker": "^2.3.1",
    "react-native-image-view": "^2.1.9",
    "react-native-indicators": "^0.17.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.1",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-loading-spinner-overlay": "^1.1.0",
    "react-native-modal-datetime-picker": "^8.5.4",
    "react-native-permissions": "^2.1.2",
    "react-native-push-notification": "^3.1.9",
    "react-native-reanimated": "^1.8.0",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-screens": "^2.5.0",
    "react-native-snap-carousel": "^3.9.0",
    "react-native-sound": "^0.11.0",
    "react-native-thumbnail": "^1.1.3",
    "react-native-vector-icons": "^6.6.0",
    "react-native-video": "^4.4.5",
    "react-native-video-helper": "^1.4.4",
    "react-native-webview": "^9.0.1",
    "react-navigation": "^4.3.7",
    "react-redux": "^7.2.0",
    "redux": "^4.0.5",
    "redux-thunk": "^2.3.0",
    "sendbird": "^3.0.121",
    "socket.io-client": "^2.3.0",
    "tipsi-stripe": "^7.5.3"
  },
  "devDependencies": {
    "@babel/core": "^7.6.2",
    "@babel/runtime": "^7.6.2",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.9.0",
    "eslint": "^6.5.1",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.58.0",
    "react-test-renderer": "16.11.0"
  },
  "jest": {
    "preset": "react-native"
  },
  "rnpm": {
    "assets": [
      "./src/assets/fonts"
    ]
  }
}

![Simulator Screen Shot - iPhone 11 - 2020-05-07 at 21 11 39](https://user-images.githubusercontent.com/8748763/81317571-a4168200-90aa-11ea-8191-f2b540ba64a7.png)
![Simulator Screen Shot - iPhone 11 - 2020-05-07 at 21 11 42](https://user-images.githubusercontent.com/8748763/81317655-bdb7c980-90aa-11ea-9fe7-4bee33155bf5.png)

**Comment by ezranbayantemur** [comment]
Can you try `yarn install` and `cd ios && pod install`
