### ISSUE TITLE
Unsupported layout animation createConfig property (null)

### ISSUE THREAD

**Issue by PhilippKrone** [facebook/react-native#2884]
Hi,

I was not able to reproduce it within a simple example, that's why I have to explain it here: When pop()ing away from a scene that has a keyboard open (due to have a TextInput field on the scene), I get the following redbox error:

![screen shot 2015-09-20 at 12 02 56](https://cloud.githubusercontent.com/assets/11861008/9980198/901b88e6-5f8f-11e5-8750-3f409667adee.png)

When debugging through RCTUIManager.m, setting a breakpoint on line 542, I see the following properties of the object "createAnimation":

<img width="450" alt="screen shot 2015-09-20 at 12 01 05" src="https://cloud.githubusercontent.com/assets/11861008/9980197/7cc747e4-5f8f-11e5-8c81-deaa60f210cd.png">

Does anyone have an idea how to fix that? My temporary fix is to comment out the RCTLogError..

Regards
Philipp

**Comment by PhilippKrone** [comment]
CC @sahrens: you've worked a lot on the Animated API havent you?

**Comment by sahrens** [comment]
Animated and LayoutAnimation are completely separate systems. What looks like is happening is that somewhere in your code you're improperly configuring a LayoutAnimation.
