### ISSUE TITLE
which is root file in react native

### ISSUE THREAD

**Issue by uendar** [facebook/react-native#28842]
I am trying to set a notification receiver in RN but i want that whenever i am in page to receive it.  So i was wondering which is root file in react native combine with react navigation so i can implement my handlers there and than receive notification anywhere in project?

**Comment by troZee** [comment]
index.js in main folder ?
eg:
```jsx
import React from 'react';
import {AppRegistry} from 'react-native';

import {name as appName} from './app.json';
import ExampleView from './ExampleView';

class ExampleApp extends React.Component<{}> {
  render() {
    // capture notification here and pass it as prop 
   // to your navigation or view
    return <ExampleView notification={notification}/>;
  }
}

AppRegistry.registerComponent(appName, () => ExampleApp);
```

**Comment by ezranbayantemur** [comment]
Probably you have splash screen for application. You can use it for receiver.

**Comment by uendar** [comment]
I am using index.android.js 

Here is my file:

`import React, {Component} from 'react';
import {
    AppRegistry, SafeAreaView
} from 'react-native';
import Logins from './marian/loging/IsLoged';
import configureStore from './marian/configureStore';
import {Provider} from 'react-redux';
const store =configureStore();

export default class Marian extends Component {
    constructor(props) {
        super(props);
        this.state = {
        };
      }

    render() {
 
        return (
            <Provider store={store}>
                <Logins navigate={this.props.navigation}/>
            </Provider>
        );
    }
}

AppRegistry.registerComponent('APP', () => APP);`




if i use the component for receiving notification inside      <Provider > i get error.
