### ISSUE TITLE
iOS: Modal not dismissed when dragging formSheet/pageSheet down

### ISSUE THREAD

**Issue by mrousavy** [facebook/react-native#28859]
## Description

The Modal's `onDismiss` and/or `onRequestClose` functions are not called when presenting the Modal with `presentationStyle="formSheet"` or `presentationStyle="pageSheet"`. This results in the main/host view being unresponsive, because it still thinks the modal is shown.

> (iOS only, as the formSheet is iOS only)

![Demo video](https://user-images.githubusercontent.com/15199031/81474445-ccff5a00-9205-11ea-98db-4dc120cb5ffe.gif)

## React Native version:

```
System:
    OS: macOS 10.15.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 12.16 GB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.2.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 25, 28, 29
      Build Tools: 28.0.3, 29.0.3, 30.0.0
      System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_252 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Create a Modal like this:

```jsx
<Modal
	presentationStyle="pageSheet"
	visible={this.state.modalShown}
	animationType="slide"
	onShow={() => console.log('modal onShow')}
	onDismiss={() => console.log('modal onDismiss')}
	onRequestClose={() => console.log('modal onRequestClose')}>
	// some content view
</Modal>
```

2. Open Modal by setting state to `modalShown: true`
3. Drag modal sheet-view down

## Expected Results

`onDismiss` gets called and the main/host view responds to touches again.

## Snack, code example, screenshot, or link to a repository:

[Snack example](https://snack.expo.io/@mrousavy/modal-formsheet-bug-demo)

**Comment by mrousavy** [comment]
Edit: This issue has been raised before, my bad. For anyone experiencing the same: This is a known bug in React Native (0.62.2), to fix this use `patch-package`. https://gist.github.com/r0b0t3d/3c9f77434e6fbcfa78698dcf57614fad

**Comment by tsiory** [comment]
Hey guys! how to use that patch? thanks
