### ISSUE TITLE
Android:  Font weight numeric values do not work with System default fonts of android 

### ISSUE THREAD

**Issue by mnkshukl** [facebook/react-native#28854]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
React native supports Font weight values with Android SDK 28 and above for custom fonts. But with System default fonts these numeric values are not supported. Only value - 700 is for bold and others are for normal font. As android 28 and above supports font weights react-native can spuport font weight for system default fonts also.

## React Native version:
System:
    OS: Windows 10 10.0.18363
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
    Memory: 39.93 GB / 63.87 GB
  Binaries:
    Node: 10.20.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.0 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3
      System Images: android-29 | Google Play Intel x86 Atom
      Android NDK: 17.2.4988734
  IDEs:
    Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6392135
  Languages:
    Java: Not Found
    Python: 3.8.2 - D:\Office\Build\OfficeNugetInit\gen\InPath\python.cmd
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found

issue in all react-native versions. 

## Steps To Reproduce
Create a Text with font weight values from 100 to 900 (without any custom fonts )
**only font weight 700 is shown as bold** other are shown as normal 

![Screenshot_1588922598](https://user-images.githubusercontent.com/60392150/81381874-10d16100-912b-11ea-8a82-1b461a2018a9.png)

## Expected Results
font weight  values should change font effect in android sdk 28 and above.
Expected result should look like this 

![Screenshot_1588921349](https://user-images.githubusercontent.com/60392150/81380190-14afb400-9128-11ea-8d86-54c368c79f68.png)

## Snack, code example, screenshot, or link to a repository:

"<RNTesterBlock title="Font Weight">
          <Text style={{fontSize: 20, fontWeight: 'bold'}}>Move fast and be bold</Text>
          <Text style={{fontSize: 20, fontWeight: 'normal'}}>Move fast and be bold</Text>
          <Text style={{fontSize: 20, fontWeight: '100'}}>Move fast and be bold</Text>
          <Text style={{fontSize: 20, fontWeight: '200'}}>Move fast and be bold</Text>
          <Text style={{fontSize: 20, fontWeight: '300'}}>Move fast and be bold</Text>
          <Text style={{fontSize: 20, fontWeight: '400'}}>Move fast and be bold</Text>
          <Text style={{fontSize: 20, fontWeight: '500'}}>Move fast and be bold</Text>
          <Text style={{fontSize: 20, fontWeight: '600'}}>Move fast and be bold</Text>
          <Text style={{fontSize: 20, fontWeight: '700'}}>Move fast and be bold</Text>
          <Text style={{fontSize: 20, fontWeight: '800'}}>Move fast and be bold</Text>
          <Text style={{fontSize: 20, fontWeight: '900'}}>Move fast and be bold</Text>
  </RNTesterBlock>"

**Comment by Maskedman99** [comment]
For me they don't work in ReactJs either   :)

**Comment by fabriziobertoglio1987** [comment]
Please check the docs before opening an issue 

https://reactnative.dev/docs/text-style-props#fontweight

![image](https://user-images.githubusercontent.com/24992535/83541380-dbd1e780-a4f9-11ea-967d-8a1f14cb9e25.png)

**Comment by fangasvsass** [comment]
any update? 0.59.10 upgrade to 0.62.2 fontWeight not work

**Comment by mnkshukl** [comment]
@fangasvsass - I suppose it supported normal and bold values as <500 for normal and >=500 for bold previously which has changed to 700 for bold now.
but All different values are and were never supported for system default fonts.

**Comment by fabriziobertoglio1987** [comment]
even if this was a bug and I could write a pull request for it, with 120 open pull request it will take very long time to get it reviewed and merged as seems to me not a priority

**Comment by Maskedman99** [comment]
@fabriziobertoglio1987 if the changes are small then the PR might get merged quickly.

**Comment by fabriziobertoglio1987** [comment]
https://github.com/facebook/react-native/blob/b4c13929e2eeb2a697978b0d55f10139272326e3/ReactAndroid/src/main/java/com/facebook/react/views/text/ReactTypefaceUtils.java#L110

Publishing Pull Request Tonight

**Comment by fabriziobertoglio1987** [comment]
> Please, is it possible to merge this PR in the next version ?

To answer the question of when the pr https://github.com/facebook/react-native/pull/29117 which fixes this issue will be released in the next version of React Native, I suggest you to follow the discussions at https://github.com/react-native-community/releases/issues by subscribing to those threads. The process of releasing a new version with a bug fix is the following:

- an Issue is opened in facebook/react-native
- a contributor writes a Pull Request to fix/close the react-native Issue
- The Pull Request is merged in Master
- For each realease (the upcoming one is 0.64.1) there will be a separate discussion on https://github.com/react-native-community/releases/issues where anyone can request a commit to be cherrypicked from master. The link need to be from the a **commit** from master (for ex. https://github.com/facebook/react-native/pull/29157#issuecomment-651430945) and not a Pull Request not yet merged in master :peace_symbol: :pray:

**Comment by Maskedman99** [comment]
> @fabriziobertoglio1987 if the changes are small then the PR might get merged quickly.

Turns out I was very much wrong ! :smile:
