### ISSUE TITLE
Animated component - attach/detach native views on each render

### ISSUE THREAD

**Issue by usrbowe** [facebook/react-native#28864]
I just noticed, that each re-render of my animated component, it will detach and attach native events for the same view. 
I believe the root cause is the check in `componentDidUpdate`, which uses `this._prevComponent` to do equality check.

https://github.com/facebook/react-native/blob/master/Libraries/Animated/src/createAnimatedComponent.js#L197-L205

The issue is that  `this._prevComponent` will always be `undefined`, since we only set it inside `setRef` method, which being invoked only once per component instance.

https://github.com/facebook/react-native/blob/master/Libraries/Animated/src/createAnimatedComponent.js#L143-L145

Currently not sure, what is intended behaviour in `componentDidUpdate` method. So just raising issue without PR.

Another concern is related to `UNSAFE_componentWillReceiveProps`. This will invoke `__detach` on every parent re render, even if props are same.

**Comment by JetA2** [comment]
I ran into this issue as well. Did you ever find a workaround?

**Comment by JetA2** [comment]
Switching to the react-native-reanimated library solved the issue.
