### ISSUE TITLE
Android - Button is not clickable when useWindowDimensions is invoked in functional component 

### ISSUE THREAD

**Issue by briancldo** [facebook/react-native#28866]
## Description
I have managed to isolate a bug in my project, and that is the inability for a Button and useWindowDimensions to co-exist. I use useWindowDimensions() to get the height and width of my screen, and suddenly I cannot tap on the Button (on Android. Works perfectly on web and iOS).

I don't know if it's relevant, but I used expo to create my project. It's a brand new project; all I did was import the useWindowDimensions and add a Button in App.js. Here's a repository of the code:
https://github.com/briancldo/ReactNative-UnclickableButtonBug

## React Native version:
0.61.4

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

Code can be found in the above repository, but here's what I did: 
1. Create a new React Native project (not sure if it's relevant, but I used expo). **Note:** do not use Expo Snack. The bug does not occur when running from Snack. Make a new local project with "expo init" and selecting a blank project.
2. Edit App.js with the following: import useWindowDimensions and Button from react-native.
3. Invoke useWindowDimension in the functional component to get the height and width.
4. Add a Button, preferably with some sort of feedback.
5. I used the expo app on Android to test my code. Again, this bug isn't present for web or iOS. In testing, I could not click on the button at all.

## Expected Results
Android only:
- Button is pressed and feedback is given (in my code, it's a simple alert()).
- I think it's worth mentioning that the 'Dismiss' button on the yellow warning box in expo can't be pressed either, so maybe this is more of an expo problem?

## Snack, code example, screenshot, or link to a repository:
https://github.com/briancldo/ReactNative-UnclickableButtonBug

**Comment by Brumor** [comment]
I have a similar problem, but for me just launching the app on a physical Android device (works on emulator) and enabling Debug mode does that, I also can't click any button, including the LogBox, I don't know if it's linked but it seems like it

**Comment by Stenbaek** [comment]
I also have a similar problem.

When I use the useWindowDimensions hook, and change the orientation of the device, the app would freeze, and in development mode I would get an error that I cannot dismiss:
`State updates from the useState() and useReducer() Hooks don't support the second callback argument`

I ended up using Dimensions.get("width") instead.

**Comment by fabriziobertoglio1987** [comment]
it works for me on android build with expo https://snack.expo.io/@fabrizio.bertoglio/rude-waffles

additionally where is useWindowDimensions included in the documentation https://docs.expo.io/versions/v37.0.0/react-native/dimensions/

**Comment by briancldo** [comment]
@fabriziobertoglio1987 
Try running it on a local expo project, rather than on Snack. For some reason, it works with Snack, but not a local run (of the same exact code). I'll update the original post to reflect this.

Also, the documentation for useWindowDimensions is here: https://reactnative.dev/docs/usewindowdimensions
