### ISSUE TITLE
Native crash "RN version 0.62.x" with 3rd party SDK

### ISSUE THREAD

**Issue by pmolcany** [facebook/react-native#28874]
Running react native sample with our face recognition SDK crashes the app. Our SDK uses libc++_shared.so.

## Description
If I create new project and with our SDK, init with System.loadLibrary("iface") in Activity onCreate - app crashes, crash log is attached. If I call System.loadLibrary("iface") in Application onCreate before everything else app does not crash. It also does not crash if I load System.loadLibrary("c++_shared") instead in Application onCreate.

## React Native version:
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 7.01 GB / 31.88 GB
  Binaries:
    Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      Android NDK: 21.1.6352462
  IDEs:
    Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6392135
  Languages:
    Java: javac 11 - C:\Program Files\Java\jdk-11\bin\javac.EXE
    Python: 3.6.0 - C:\Users\pmolcany\AppData\Local\Programs\Python\Python36\python.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.0 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Setup the face recognition SDK with instructions below
2. System.loadLibrary("iface") in Activity onCreate
[crash.txt](https://github.com/facebook/react-native/files/4611215/crash.txt)

## Expected Results
App should not crash

## Snack, code example, screenshot, or link to a repository:
To load the face recognition SDK into project add repository in build.gradle allprojects
```
maven {
            url 'http://maven.innovatrics.com/releases'
        }
```
And add dependency to app/build.gradle
```
implementation 'com.innovatrics.android:dot:2.16.2'
```
App does dot crash with react native 0.61.5

**Comment by majirosstefan** [comment]
hey, just asking... Was this solved somehow or just ignored ?
