### ISSUE TITLE
Touchable/Button in Modal dismisses keyboard on Touch if Modal's parent is a ScrollView without keyboardShouldPersistTaps

### ISSUE THREAD

**Issue by divonelnc** [facebook/react-native#28871]
## Description
If you have a TextInput and a Touchable (or Button) inside a Modal, inside a ScrollView that doesn't have keyboardShouldPersistTaps on always or handled, touching the Touchable will dismiss the keyboard.

## React Native version:
System:
    OS: Windows 10 10.0.18362
    CPU: (4) x64 Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz
    Memory: 3.15 GB / 15.96 GB
  Binaries:
    Node: 10.15.3 - E:\nodejs\node.EXE
    Yarn: 1.22.0 - E:\Yarn\bin\yarn.CMD
    npm: 6.14.5 - E:\nodejs\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 29
      Build Tools: 29.0.0, 29.0.3
      System Images: android-29 | Google APIs Intel x86 Atom
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4
  npmGlobalPackages:
    create-react-native-app: 2.0.2
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7

## Steps To Reproduce
1. Create a ScrollView without keyboardShouldPersistTaps set
2. Add a Modal inside this view, containing a Button or Touchable and a TextInput
3. focus on the TextInput to show the keyboard
4. Tap the Touchable/Button
5. Keyboard gets dismissed

## Expected Results
Tapping the touchable should not dismiss the Keyboard. The ancestor ScrollView should not cause the Keyboard to get dismissed, as the Modal itself doesn't have a scrollView. 

## Snack, code example, screenshot, or link to a repository:
```
function TestComp() {
	const [showingModal, setshowingModal] = React.useState(false);
	return (
		<ScrollView contentContainerStyle={{ flex: 1, justifyContent: "center", alignItems: "center" }}>
			<Button title={"Show modal"} onPress={() => setshowingModal(true)} />

			<Modal visible={showingModal} onRequestClose={() => setshowingModal(false)}>
				<View style={{ flex: 1, justifyContent: "center", alignItems: "center" }}>
					<View style={{ flex: 1, marginTop: 22 }}>
						<Button title={"hide modal"} onPress={() => setshowingModal(false)} />
					</View>
					<TextInput autoFocus />
				</View>
			</Modal>
		</ScrollView>
	);
}
```

**Comment by SiroSong** [comment]
same issue，when i use input element embed Modal in Scrollview，keyboard seem to be stop the callback on Madal, when I first touched screen the keyboard will hide, but Madal did nothing, only when I second touched, callback on Modal worked.
I tried, Flatlist same trouble yet.

**Comment by mysport12** [comment]
I ran into the same issue, but was able to work around it by adding keyboardShouldPersistTaps='handled' to the Modal's parent ScrollView as noted.

**Comment by cristianoccazinsp** [comment]
Is there any way to have the scrollview of the parent use `keyboardShouldPersistTaps={'never'}` but the modal itself behave has "handled" ? Why does the parent scrollview interfere with the modal? Nonsense.
