### ISSUE TITLE
FLATLIST not possible to render local json

### ISSUE THREAD

**Issue by davStar** [facebook/react-native#28872]
## Description
My FlatList didn't render my local json file described inside a JS file. 

My BoardData.js describing my json:

`
var BoardData = [

			{
				"id":"1",
				"status": "declared",
				"date": "03-DEC-2019",
				"category": "Fuite d'eau",
				"event_info": "Contact du Plombier",
				"adress": "2 rue de la queuleuleu, 31200 Toulouse",
				"imageUrl": "..data/photo/photo_123456.webp"
			},
			{
			
				"id":"2",
				"status": "run",
				"date": "12-JAN-2020",
				"category": "eclairage",
				"event_info": "Contact du Plombier",
				"adress": "3 impasse alphonse-daudet, 31700 Blagnac",
				"imageUrl": "../data/photo/photo_234459.jpg"
			},
			 {
				"id":"3",
				"status": "declared",
				"date": "20-FEB-2020",
				"category": "chaussee",
				"event_info": "Contact du Plombier",
				"adress": "50 avenue de Fronton, 31140 Aucamville",
				"imageUrl": "../data/photo/photo_458049.jpg"
			},

			{
				"id":"4",
				"status": "closed",
				"date": "04-DEC-2019",
				"category": "Poubelle",
				"event_info": "Contact du Plombier",
				"adress": "3 rue de la queuleuleu, 31200 Toulouse",
				"imageUrl": "../data/photo/photo_123456.webp"
			},

			{
				"id":"5",
				"status": "closed",
				"date": "13-JAN-2020",
				"category": "Ascenceur",
				"event_info": "Contact du Plombier",
				"adress": "4 impasse alphonse-daudet, 31700 Blagnac",
				"imageUrl": "../data/photo/photo_234459.jpg"
			},

			{
				"id":"6",
				"status": "run",
				"date": "21-FEB-2020",
				"category": "chaussee",
				"event_info": "Contact du Plombier",
				"adress": "52 avenue de Fronton, 31140 Aucamville",
				"imageUrl": "../data/photo/photo_458049.jpg"
			},
		
	];

	module.exports = BoardData;
`

My Board.js file used to render myFlatList of Card. 

`
import React, { Component } from react;

import {
	FlatList, ScrollView, StyleSheet, Platform, View, Image, Dimensions, TouchableOpacity,
  } from react-native;
  
  // Galio components
  import {
	Block, NavBar, Icon,Text
  } from galio-framework;
import {Card, CardItem, Left, Right, Thumbnail, Title, Subtitle} from native-base;
import theme from ./theme.js;
import BoardData from ../data/BoardData.js

`
console.log ('BoardData : ', BoardData)

export default class BoardScreen extends Component {
	constructor(){

		super();
		this.state = {
			boarderstatus: 'declared',
			myCases: [],

		}

	}

	componentDidMount () {
		this.setState({myCases:BoardData })

	}

	// Synchronization concerning the gesture
	async setBoarder(value){

		console.log("SETBoarder value : " + value)
		this.setState({boarderstatus:value })
		console.log("SETBoarder boarderstatus : " + value)

	}

	renderCard(item,index){

		console.log("Boarder value ITEM : " + item.category)
		console.log("Boarder value BOARDERSTATUS : " + this.state.boarderstatus)

		if (item.category === this.state.boarderstatus)
		{
			return (
	
				<TouchableOpacity styles={style.btn}>

				<Card>
					<CardItem>
						<Left>
							<Thumbnail 

							source={require('../data/photo/photo_234459.jpg')}
							style={{width:80,height:80}}/>
							<Block left style={{top:-15, left:5}}>
								<Title>{item.category}</Title>
								<Subtitle>{item.date}</Subtitle>
							</Block>
						
						</Left>

						<Right>
							<Block>
								
							</Block>
						</Right>
					</CardItem>

				</Card>

				</TouchableOpacity>
			
			);
		}
	

	}
	render() {
		return (
			...
					
					<FlatList
						data={BoardData}
						keyExtractor={(item)=>item.id}
						renderItem={(item, index) => this.renderCard(item, index)}
					/>
					
			
		
		);
	}
}

const style = StyleSheet.create({
    
    background: {
       backgroundColor: '#E1D7D8',
       paddingHorizontal: 10,
    },

    btn: {
        backgroundColor: COLOR_WHITE,
        borderRadius: BASE_SIZE / 2,
        height: width * 0.28,
        width: width * 0.28,
        shadowOpacity: 0.4,
        elevation: BASE_SIZE / 2,
        shadowColor: 'rgba(0,0,0, .4)', // IOS
        shadowOffset: { height: 1, width: 1 }, // IOS
        shadowOpacity: 1, // IOS
        shadowRadius: 1, //IOS
        padding: 10
    
    },

});
`
When I log the BoardData variable I can see the following output:

`
[{"adress": "2 rue de la queuleuleu, 31200 Toulouse", "category": "Fuite d'eau", "date": "03-DEC-2019", "event_info": "Contact du Plombier", "id": "1", "imageUrl": "..data/photo/photo_123456.webp", "status": "declared"}, {"adress": "3 impasse alphonse-daudet, 31700 Blagnac", "category": "eclairage", "date": "12-JAN-2020", "event_info": "Contact du Plombier", "id": "2", "imageUrl": "../data/photo/photo_234459.jpg", "status": "run"}, {"adress": "50 avenue de Fronton, 31140 Aucamville", "category": "chaussee", "date": "20-FEB-2020", "event_info": "Contact du Plombier", "id": "3", "imageUrl": "../data/photo/photo_458049.jpg", "status": "declared"}, {"adress": "3 rue de la queuleuleu, 31200 Toulouse", "category": "Poubelle", "date": "04-DEC-2019", "event_info": "Contact du Plombier", "id": "4", "imageUrl": "../data/photo/photo_123456.webp", "status": "closed"}, {"adress": "4 impasse alphonse-daudet, 31700 Blagnac", "category": "Ascenceur", "date": "13-JAN-2020", "event_info": "Contact du Plombier", "id": "5", "imageUrl": "../data/photo/photo_234459.jpg", "status": "closed"}, {"adress": "52 avenue de Fronton, 31140 Aucamville", "category": "chaussee", "date": "21-FEB-2020", "event_info": "Contact du Plombier", "id": "6", "imageUrl": "../data/photo/photo_458049.jpg", "status": "run"}]
`

## React Native version:
`
npx react-native info
info Fetching system and libraries information...
System:
    OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
    Memory: 19.48 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.5.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.4 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 25, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-24 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-R | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6308749
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_121 - /usr/bin/javac
    Python: 2.7.12 - /Library/Frameworks/Python.framework/Versions/2.7/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^16.13.1 => 16.13.1 
    react-native: ^0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found
`

## Expected Results
I except the FlatList render the items of json files. But when I log one of them e.g item.category the value is undefined .

## Snack, code example, screenshot, or link to a repository:
The screenshot bellow show a switchselector i ididn't show on teh code extrction above to avoid to polluate the post. But each click on the switch on the top set the state (this.boarderstatus). Logs confirmed the value is well set.

![Simulator Screen Shot - iPhone 11 - 2020-05-11 at 10 29 13](https://user-images.githubusercontent.com/26174579/81583870-42a82900-93b2-11ea-8bdb-f8b34f30e3e0.png)

**Comment by arcollector** [comment]
renderItem={({ item, index })=> this.renderCard(item, index)}

**Comment by davStar** [comment]
Just for my knowledge why we should pass an array as an argument as no array is waited in the function renderCard . Sorry I m a little new in js.
