### ISSUE TITLE
PermissionsAndroid: The system permission prompt is still shown if the "rationale" dialog box is rejected

### ISSUE THREAD

**Issue by udeyrishi** [facebook/react-native#28876]
## Description

`PermissionsAndroid::request` seems to ignore the user selection in the "rationale" dialog box, and always shows the follow-up system permission dialog box. 

**Expectation**: If the user clicks the neutral or negative buttons in the "rationale" dialog box, or taps outside the dialog box itself, the permission is denied and no follow-up system prompt is shown.
**Actual**: The follow-up system prompt is shown regardless of the user selection.

## React Native version:

```
System:
    OS: macOS 10.15.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.90 GB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.2.0 - ~/.nvm/versions/node/v13.2.0/bin/node
    Yarn: 1.21.1 - ~/.dev/yarn/1.21.1/bin/yarn
    npm: 6.13.1 - ~/.nvm/versions/node/v13.2.0/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 21, 24, 25, 26, 27, 28, 29
      Build Tools: 26.0.2, 28.0.3, 29.0.2
      System Images: android-21 | Google APIs Intel x86 Atom, android-22 | Google APIs Intel x86 Atom, android-23 | Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-24 | Google APIs Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-25 | Google APIs Intel x86 Atom_64, android-26 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom_64, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.2 => 0.61.2
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

0. The permission history has been cleared via `adb shell pm reset-permissions PACKAGE_ID android.permission.ACCESS_FINE_LOCATION`
1. The permission is requested in code when the button is pressed
2. Since this is the first time the request is made, the system prompt is shown (correctly)
3. The request is denied
4. The button is pressed again; that requests the permission again in code
5. This time the rationale dialog is first shown (correctly)
6. The negative button/neutral button/area outside the dialog is clicked
7. Expectation: no follow-up dialogs, and the permission gets rejected. Actual: The user is spammed with a follow-up system dialog.

See the following GIF for the visual context:

<img src="https://user-images.githubusercontent.com/4692593/81677040-dc261800-9450-11ea-97c9-ae0d5a0c56ae.gif" width=400/>

## Expected Results

The follow-up system dialog is only shown if the user clicks the "Positive button"

## Snack, code example, screenshot, or link to a repository:

This code snippet is used for requesting the permission when the button is pressed:

```ts
const result = await PermissionsAndroid.request(
      'android.permission.ACCESS_FINE_LOCATION',
      {
        title: 'Some permission title',
        message: 'Some permission message',
        buttonPositive: 'Positive button',
        buttonNegative: 'Negative button',
        buttonNeutral: 'Neutral button',
      }
    )
```

**Comment by udeyrishi** [comment]
I did some initial digging to see why this is happening. Here are some of my findings:

It looks like the "button pressed" callback passed to the `NativeDialogManagerAndroid.showAlert` function is not checking <a href="https://github.com/facebook/react-native/blob/master/Libraries/PermissionsAndroid/PermissionsAndroid.js#L225-L226">_which button_ was actually pressed</a>. Looking at the signature of `showAlert`, it should pass the `DialogButtonKey` as the <a href="https://github.com/facebook/react-native/blob/b65b00ab6b3f414c57604bba5f91240caa0b8e72/Libraries/NativeModules/specs/NativeDialogManagerAndroid.js#L45">second param</a>. So given my limited understanding, I think the fix should just involve adding a buttonKey check there.

**Comment by udeyrishi** [comment]
This one still needs attention

**Comment by HengJunXi** [comment]
This one still needs attention

**Comment by narcismihaitech** [comment]
Having the same problem - no matter if the user taps on the positive or negative button, the system pop-up for requesting permission is still displayed.

**Comment by HengJunXi** [comment]
This issue might have been solved by https://github.com/facebook/react-native/pull/28201, but it still needs someone to review it.

**Comment by ThatMate** [comment]
I am facing the same issue
![Screenshot_1605691254](https://user-images.githubusercontent.com/54436468/99510836-87d69480-29ad-11eb-9e77-51b88c249432.png)
when pressed "Not Now", it shows a second system dialog 
![Screenshot_1605691262](https://user-images.githubusercontent.com/54436468/99510938-a50b6300-29ad-11eb-85b8-346d42a83b53.png)

**Comment by HectorRicardo** [comment]
FB team: Could we get an update about this bug?

**Comment by naishe** [comment]
No updates? :(
