### ISSUE TITLE
Image component cannot be placed in Text component

### ISSUE THREAD

**Issue by KarenQiao** [facebook/react-native#28886]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Image component cannot be placed in Text component，The Image component has a white background

## React Native version:
 System:
      OS: macOS 10.14.5
      CPU: (4) x64 Intel(R) Core(TM) m3-7Y32 CPU @ 1.10GHz
      Memory: 36.14 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.13.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
      Android SDK:
        API Levels: 23, 26, 27, 28
        Build Tools: 27.0.3, 28.0.3
        System Images: android-26 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.9 => 0.59.9 
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

  <Text style={[styles.commonFont, styles.nameInfo, {color: '#5E5F64'}]}
                                  ellipsizeMode={'tail'} numberOfLines={2}>
                             KarenQiao：
                              
                                   <Image style={styles.violationsImg} source={require('../../images/news/icon_violations.png')}/>
                                    <Text style={[styles.commonFont, styles.violationsText]}>{reactFilter.complainStatus(item.status)}</Text>

<Text>

**Comment by KarenQiao** [comment]
![image](https://user-images.githubusercontent.com/27947842/81780622-6a6dcd00-9529-11ea-9149-67ffb26474af.png)

**Comment by irohitb** [comment]
Are you sure image does not have white background? it looks like image might have background.

**Comment by KarenQiao** [comment]
yes,this image does not have background.

![image](https://user-images.githubusercontent.com/27947842/81898500-5094be80-95eb-11ea-8c72-2f49dbbff6ed.png)

**Comment by fabriziobertoglio1987** [comment]
```javascript
import * as React from 'react';
import { Image, Text, View, StyleSheet } from 'react-native';

export default class App extends React.Component {
  render() {
    return (
      <>
      <Text>
        My text.
        My Image <Image style={{height: 100}} source={{ uri: "https://play.google.com/intl/en_us/badges/static/images/badges/en_badge_web_generic.png" }} />
      </Text>
      <Image style={{height: 100}} source={{ uri: "https://play.google.com/intl/en_us/badges/static/images/badges/en_badge_web_generic.png" }} />

      </>

    );
  }
}

const styles = StyleSheet.create({
});
```
<img src="https://user-images.githubusercontent.com/24992535/83532418-817f5980-a4ee-11ea-9768-9ab38554498f.png" width="250" />

**Comment by fabriziobertoglio1987** [comment]
commenting this line shows the image

https://github.com/facebook/react-native/blob/68714163280695c3148544b95b05a2c1464dbbba/ReactAndroid/src/main/java/com/facebook/react/views/text/frescosupport/FrescoBasedReactTextInlineImageSpan.java#L152

<img src="https://user-images.githubusercontent.com/24992535/83538069-b04cfe00-a4f5-11ea-9619-303fe622aab2.png" width="250" />

I should be close to writing a pr

**Comment by fabriziobertoglio1987** [comment]
Unluckily I wasted time working on this. Can not reproduce. Author did not include reproducible example

**Comment by fabriziobertoglio1987** [comment]
if you give certain style to the image, that background will be applied.. to be closed.

**Comment by KarenQiao** [comment]
> if you give certain style to the image, that background will be applied.. to be closed.

what's  certain style ?.I just give width,height to the image

**Comment by fabriziobertoglio1987** [comment]
How can I fix your problem?

If I don't have your source-code and I can not reproduce your issue ? 

:disappointed:

**Comment by maxfurman** [comment]
My team ran into a similar issue after upgrading to Xcode 11/ iOS SDK 13. Images inside a Text node also render a placeholder page-with-bent-corner icon. We're on RN 0.60.6. I can't provide all our source code but a simple repro is
```jsx
<Text>
  Some text with an
  <Image style={{height: 20, width: 20}} source={{uri: 'some/image.png'}} />
  in the middle
</Text>
```

<img width="250" alt="Screen Shot 2020-06-15 at 12 13 20 PM" src="https://user-images.githubusercontent.com/6634694/84681091-a1a51480-af01-11ea-908c-bf1d8e406cbc.png">

**Comment by maxfurman** [comment]
It turns out this is a manifestation of https://github.com/facebook/react-native/issues/26577; upgrading to 0.61.3 or higher should fix it.
