### ISSUE TITLE
Adding custom fonts to iOS project with existing Resources folder fails

### ISSUE THREAD

**Issue by maniramezan** [facebook/react-native#28883]
## Description

Adding custom fonts to an iOS project with existing Resources folder fails without any warning or proper error message. This issue is due to `react-native link` in RN ≥ 0.60 creating a group in Xcode without a backing folder on disk and then adding references to custom fonts under that group. This works until you already have a Resources group with a backing folder in your Xcode project on the root. Then `react-native link` just adds the references in this folder, but doesn't fix the path for taking into account this extra level of folder and adding `..` to file paths. This causes builds for Xcode fails for copying these fonts.

## React Native version:

```
    OS: macOS 10.15.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 3.94 GB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.2.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  Languages:
    Java: javac 14 - /usr/bin/javac
    Python: 2.7.17 - /Users/maniramezan/.pyenv/shims/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Create a new react project, `react-native init sample`
2. Go to project, `cd sample`
3. Create fonts folder under src/assets `mkdir -p src/assets/fonts`
4. Copy some custom fonts into that folder
5. Create `react-native.config.js` file with following content:
    module.exports = {
        project: {
            ios: {},
            android: {},
        },
        assets: ['./src/assets/fonts/']
    };
6. Open "ios/Sample.xcworkspace" in Xcode
7. Right click on `Sample.xcodeproj` and choose "New Group"

<img width="279" alt="Screen Shot 2020-05-12 at 3 59 46 PM" src="https://user-images.githubusercontent.com/2628592/81739649-b3f6e300-9469-11ea-9335-9bd73ad74a1e.png">
<img width="326" alt="Screen Shot 2020-05-12 at 3 59 56 PM" src="https://user-images.githubusercontent.com/2628592/81739651-b3f6e300-9469-11ea-824a-16281b44f78d.png">

8. Go to terminal and run `react-native link` on root of your project
9. Open Xcode and try to build the project

You can also check the file path of your custom fonts in Xcode and notice they're pointing to `ios/src/assets/fonts` instead of `src/assets/fonts`

## Expected Results

`react-native link` to throw an error message or properly fix the file path when `Resources` folder already exists.

## Snack, code example, screenshot, or link to a repository:

Following steps, it should be straightforward to reproduce the issue

**Comment by jmlavoier** [comment]
I'm facing the same issue. 
https://github.com/facebook/react-native/issues/25852#issuecomment-631534806

**Comment by maniramezan** [comment]
This shouldn't be closed, unless someone fixes it or confirms it's an expected behavior 🤷‍♂️

**Comment by bengordon-dev** [comment]
Having similar problems - react-native linking a ttf nuked my entire project.

**Comment by bengordon-dev** [comment]
I should note that I was able to link a font to a new bare-bones react native project and then copy all of my old code over - it eventually all worked. This should not have to happen though.
