### ISSUE TITLE
Format text of TextInput but invisible for the user

### ISSUE THREAD

**Issue by felire** [facebook/react-native#28888]
## Description
Hi, what I want to do is change the "." by "," in my app, but I want to do it in a way that is invisible for the user, and with the way I'm doing now is taking a DELTA time in change, maybe 1 second or less but is perceptible. Is there a way to do it without a Native solution? Why this is not implemented in the core of `TextInput`?

## React Native version:
`0.61.5`

## Steps To Reproduce

This is my code:
```parseValue={value => {
                if (typeof value === 'string') {
                  return value?.replace('.', ',');
                }
                return {
                  ...value,
                  nativeEvent: {
                    ...value.nativeEvent,
                    text: value?.nativeEvent?.text.replace('.', ',')
                  }
                };
              }}
```
I did it with formik, and I modify the nativeEvent or the value itself.

## Gif
![point as coma](https://user-images.githubusercontent.com/11776795/81811725-780c5e00-94fb-11ea-83fe-2358f68bfdc5.gif)

It's not much perceptible in ios but in android is very obvious that there is a delay.

**Comment by chrisglein** [comment]
There's some innate delay in this going through JavaScript on the current infrastructure. It's possible this will go away with Fabric, but in the meantime it seems like your recourse is to do it with native handling. If indeed Fabric will address then it doesn't make sense to go add this as a core feature to TextInput.

**Comment by chrisglein** [comment]
Sounds like this is a feature request. Generally new features should be discussed [here](https://github.com/react-native-community/discussions-and-proposals/issues/) and this repo is used for bug reports. Going to close this out, hopefully the above was helpful, but feel free to continue the discussion on the other repo.

**Comment by felire** [comment]
@chrisglein Okay thanks! I implemented a solution in react native with two TextInput and one of them invisible. It works good but you lose the possibility of interact with the real TextInput, select the text, and you lose the cursor too. I parse the data in the invisible TextInput and update the visible in the `onChange` of the Invisible Input. I don't know if there is another possibility, is there? And sorry but, what is `Fabric`? I didn't find much about it.
