### ISSUE TITLE
Pod install erro

### ISSUE THREAD

**Issue by GustavoMSevero** [facebook/react-native#28897]
I formatted my MacBook Pro 13, Late 2011 yestarday.
Now i reinstalled reac-native-cli and cloned my app from github and when i run "pod install" it start install the dependencies but get some errors:

![Captura de Tela 2020-05-14 às 12 34 28](https://user-images.githubusercontent.com/2678092/81954623-74520780-95df-11ea-9100-886c8d079120.png)
![Captura de Tela 2020-05-14 às 12 34 44](https://user-images.githubusercontent.com/2678092/81954680-859b1400-95df-11ea-9f68-5180608cd81a.png)
![Captura de Tela 2020-05-14 às 12 35 01](https://user-images.githubusercontent.com/2678092/81954708-8d5ab880-95df-11ea-9341-d83885886622.png)

When i try to run the app
![Captura de Tela 2020-05-13 às 23 38 18](https://user-images.githubusercontent.com/2678092/81957367-da8c5980-95e2-11ea-8e80-0d5ded0f8ad7.png)

As my Macbook é too old, Late 2011, i could not get XCode from App Store, because Xcode is version 11, incompatible wit my macOS High Sierra 10.13.6 so i had to search other source and found out this [page](https://developer.apple.com/download/more/?name=Xcode). So i downloaded Xcode 10.1, file ".xip".

Xcode i downloaded
![Captura de Tela 2020-05-14 às 13 06 37](https://user-images.githubusercontent.com/2678092/81958105-ddd41500-95e3-11ea-995b-f6d8b8e091ba.png)

My react-native version:
react-native-cli: 2.0.1
react-native: 0.61.3

pod verion: 1.9.1

System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i5-2435M CPU @ 2.40GHz
    Memory: 3.75 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.2.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.3
      System Images: android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: /undefined - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.3 => 0.61.3 
  npmGlobalPackages:
    react-native-cli: 2.0.1

So, i don't know what can be wrong.
Someone can help!?
Since know, thank you so much for your attention.

**Comment by SConaway** [comment]
Make sure `XCode` is in `/Applications/` and that you've opened the app once. Additionally, try running `react-native doctor` and see what suggestions that shows.
