### ISSUE TITLE
FlatList strange behaviour

### ISSUE THREAD

**Issue by chequochuu** [facebook/react-native#28898]
## Description
I can use FlatList normally, but something strange happens when I put the first element of the list is 0, it doesn't trigger onViewableItemChanged. 
## React Native version:
Run `react-native info` in your terminal and copy the results here.
System:
    OS: Linux 5.3 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Memory: 3.93 GB / 15.52 GB
    Shell: 5.4.2 - /usr/bin/zsh
  Binaries:
    Node: 12.16.1 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.14.2 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 11.0.6 - /usr/lib/jvm/jdk-11.0.6/bin/javac
    Python: 2.7.17 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found
## Steps To Reproduce

```import React from 'react';
import {Text, View, FlatList} from 'react-native';

export default class App extends React.Component {
  myFunc(info) {
    console.log('it should log me!');
    console.log(info);
  }
  render() {
    //it not work
    const data = [0, 5, 6, 7, 1, 1, 2, 3, 1];
    //Using array without leading 0 will work
    // const data = [1, 5, 6, 7, 1, 1, 2, 3, 1];
    console.log(data);
    return (
      <View>
        <FlatList
          data={data}
          renderItem={({item}) => <Text style={{fontSize: 80}}> ss </Text>}
          keyExtractor={(item, index) => index + 3}
          onViewableItemsChanged={this.myFunc}
        />
      </View>
    );
  }
}
```
This code will not log as expected. However if I replace first element to 1 it will log normally.

**Comment by rebeccatay92** [comment]
Bump. This happened to me too until I removed the 0.
