### ISSUE TITLE
how can I generate index.android.bundle file only ?

### ISSUE THREAD

**Issue by shipengyan** [facebook/react-native#2889]
if i donot want to use packager?

`react-native bundle` only works for ios now. can you fix them?

**Comment by NishanthShankar** [comment]
For now you can run this command
`curl "http://localhost:8081/index.android.bundle?platform=android" -o "android/app/src/main/assets/index.android.bundle"`

**Comment by shipengyan** [comment]
@NishanthShankar ,thanks a lot.
I just want to use `react-native bundle`, maybe it bug for this command. I hope team to fix it. thanks.

**Comment by kmagiera** [comment]
Yes, `react-native bundle` will be fixed soon for android, there is a task for this open but cannot find it at the moment. Closing
