### ISSUE TITLE
XMLHttpRequest responds with a 200 if the response is malformed and contains a leading new line

### ISSUE THREAD

**Issue by kkirby** [facebook/react-native#28906]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
When using XMLHttpRequest to load a document where the response contains a leading new line, the response status will be 200 and the response text will be whatever was sent, regardless of any HTTP parsing. I only tested this on iOS.

## React Native version:
```
System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 380.57 MB / 16.00 GB
    Shell: 3.1.2 - /usr/local/bin/fish
  Binaries:
    Node: 14.2.0 - /usr/local/bin/node
    Yarn: 1.19.2 - /usr/local/bin/yarn
    npm: 6.13.6 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      Android NDK: 14.1.3816874
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  Languages:
    Java: 14.0.1 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce

_I used PHP to create a mock socket server_

1. Create a mock socket server in PHP using the following code:
```php
<?php
// Error checking removed for brevity
set_time_limit(0);
$sock = socket_create(AF_INET, SOCK_STREAM, SOL_TCP);
socket_bind($sock, '0.0.0.0', 9091);
socket_listen($sock, 5);
$msgsock = socket_accept($sock);
$msg = "\nThis is a test.";
socket_write($msgsock, $msg, strlen($msg));
socket_close($msgsock);
socket_close($sock);
```
2. Run the PHP code to start the server: `php -f path/to/server.php`
3. In a react-native project, run the following code, replacing IP with your IP address:
```javascript
const req = new XMLHttpRequest();
req.onloadend = () => {
  console.log({
    status: req.status,
    text: req.responseText,
  });
};
req.open('GET', 'http://IP:9091');
req.send();
```
4. Observe the output of the console.log is:
```JSON
{
  "status": 200,
  "text":   "\nThis is a test."
}
```

## Expected Results

Currently if a response begins with valid HTTP but ends prematurely (not having \r\n\r\n) an error is sent back with the status set to 0 and response text set to "cannot parse response". I would expect this to occur in my given scenario.

## Snack, code example, screenshot, or link to a repository:

See code samples in the steps to reproduce

**Comment by fabriziobertoglio1987** [comment]
please add this information:

1) Create public endpoint
2) Create an expo app that uses that enpoint and reproduces the error 

Thanks

**Comment by fabriziobertoglio1987** [comment]
Please explain this:
>Currently if a response begins with valid HTTP but ends prematurely (not having \r\n\r\n) an error is sent back with the status set to 0 and response text set to "cannot parse response". I would expect this to occur in my given scenario.

**Comment by kkirby** [comment]
> Please explain this:
> 
> > Currently if a response begins with valid HTTP but ends prematurely (not having \r\n\r\n) an error is sent back with the status set to 0 and response text set to "cannot parse response". I would expect this to occur in my given scenario.

If the response from the server looks like this:
 
    HTTP/1.1 200 Success\r\nContent-Type: text\r\n

Then the Ajax request fails, which is correct because it’s malformed. A proper HTTP response must have a blank line followed by \r\n to terminate the headers and signify content is next.

A proper response would look like

    HTTP/1.1 200 Success\r\nContent-Type: text\r\n\r\n

But that’s all irrelevant to the issue. I’m just saying I would expect to get the same error instead of a 200 success if the response began with \n

**Comment by kkirby** [comment]
> please add this information:
> 
> 1. Create public endpoint
> 2. Create an expo app that uses that enpoint and reproduces the error
> 
> Thanks

I’m not going to create a public endpoint. I can create a docker file though and you can use that to test this.

**Comment by kkirby** [comment]
@fabriziobertoglio1987 Here's a repo that contains the minimum to reproduce the bug: https://github.com/kkirby/react-native-networking-bug

You'll need docker.

If you use something like netcat to connect to the server running inside docker you'll see that the response from the server isn't valid HTTP. Yet `XMLHttpRequest` says the request to the server was successful and returns the content that was sent.

**Comment by kkirby** [comment]
This is still an issue.

**Comment by kkirby** [comment]
This is still an issue.

**Comment by fabriziobertoglio1987** [comment]
sorry my ignorance, but does `react-native` have something to do with `XMLHttpRequest` ?

https://github.com/facebook/react-native/blob/6e6443afd04a847ef23fb6254a84e48c70b45896/Libraries/Core/setUpXHR.js#L16-L19

or does react-native just use an external library for this? 
in this case, would be better making sure this is an actual react-native issue...

**Comment by kkirby** [comment]
@fabriziobertoglio1987 I took a couple of minutes to investigate myself to see where the actual cause of the problem was. It appears this may actually be a bug in iOS. The `NSURLResponse` given to `- (void)URLRequest:(id)requestToken didReceiveResponse:(NSURLResponse *)response` has a status code of `200`: https://github.com/facebook/react-native/blob/6a9525c9b0fc0aa5d729a3ea3258586df7aece92/Libraries/Network/RCTNetworkTask.mm#L138

I'll have to investigate further and see if this is actually reproducible outside of react-native.
