### ISSUE TITLE
Use CocoaPod in new React Native project

### ISSUE THREAD

**Issue by oney** [facebook/react-native#2890]
I know I can integrate React Native with Existing Apps by [this](https://facebook.github.io/react-native/docs/embedded-app-ios.html#content).
My question is I start a new project by using `react-native init AwesomeProject`, and I want to use CocoaPod to include some third-party open sources(I will bridge native codes to Javascript).
How can I do it? Thank you so much.

**Comment by ide** [comment]
react-native ships with React.podspec, which you can require from your Podfile. You can either depend on the "React" pod that is published to the CocoaPods specs repo, or you can specify a local path to the podspec under `node_modules/react-native/React.podspec`.

**Comment by mihirsoni** [comment]
@ide 

Thanks for the response my another question is , if i don't want to touch React.podspec and I want to use podfile for other libraries like SQLLITE , how can I achieve this in new project which is being created using react-native init.
