### ISSUE TITLE
Upload file using fetch API, return error

### ISSUE THREAD

**Issue by liukefu2050** [facebook/react-native#28907]
## Description
Upload file using fetch API, return error

## React Native version:
    "react": "16.11.0",
    "react-native": "0.62.1",

## Steps To Reproduce
code：
        let files = [{
           height: 360,
           mime: "image/jpeg",
           name: "IMG_158959717147661_compressed.jpg",
           type: "multipart/form-data",
           uri: "file:///storage/emulated/0/DCIM/IMMQY/compressed/IMG_158959717147661_compressed.jpg",
           width: 720
       }]
        let formData = new FormData();
        formData.append("images",files[0]);
        let fetchOptions = {
            method: 'POST',
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'multipart/form-data',
            },
            body: formData
        };

        fetch("https://www.xiushangsh.com/upload.json", fetchOptions)
            .then((response) => {
                console.log(response);
            })
            .then((responseText) => {
                console.log(responseText);
            })
            .catch((err) => {
                console.log(err);
            });

## Expected Results
The old version is normal

## Snack, code example, screenshot, or link to a repository:
![aa](https://user-images.githubusercontent.com/21030225/82109122-4ea33a80-9766-11ea-8da6-8194d2a4869a.png)

**Comment by irekrog** [comment]
https://github.com/facebook/react-native/issues/28551 

Check this. Looks like problem with Flipper

**Comment by liukefu2050** [comment]
thanks
