### ISSUE TITLE
Make Custom Template React Native

### ISSUE THREAD

**Issue by lfoliveir4** [facebook/react-native#28901]
I need to create a custom template with react-native but this is being a lot of work. After seeing several instructions, and trying the react-native when downloading the template informs me of the following error:

## React Native version:
Latest

## Expected Results
Describe what you expected to happen.
![image](https://user-images.githubusercontent.com/32423942/81993227-a3866a00-961b-11ea-953b-e84d23b6964c.png)

# Struct Folder 
fatherfolder/
template/mytemplate
package.json
template.config.js

**Comment by fabriziobertoglio1987** [comment]
has nothing to do with react-native
