### ISSUE TITLE
Image defaultSource dosen't support WebP on iOS native code

### ISSUE THREAD

**Issue by billxie1988** [facebook/react-native#28917]
## Description
Image defaultSource dosen't support WebP on iOS 

## Expected Results
To support imageType WebP

## Snack, code example, screenshot, or link to a repository:

Class RCTConvert
URL:"http://localhost:8081/assets/src/assets/default-bg@2x.webp
```
+ (UIImage *)UIImage:(id)json {
...
    image = [UIImage imageWithData:[NSData dataWithContentsOfURL:URL]];
...
}
```
image will return null

## React Native version:
System:
    OS: macOS 10.15
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 2.04 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.13.0 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.12.0 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: ^0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by arcollector** [comment]
ios dont support webp images, you need to use a https://github.com/SDWebImage/SDWebImageWebPCoder but obviously you need to create your custom module to be use it in your rn project

**Comment by billxie1988** [comment]
> ios dont support webp images, you need to use a https://github.com/SDWebImage/SDWebImageWebPCoder but obviously you need to create your custom module to be use it in your rn project

why ImageModule support webp but it‘s placeholder does not
