### ISSUE TITLE
fetch request success but still catching error.

### ISSUE THREAD

**Issue by dharmendrashah** [facebook/react-native#28916]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
I'm trying to fetch the API request in a `class component's function`. When i send the data all the data is sended success but responsing an error
called  `[TypeError: Network request failed]` but when `JSON.stringify(res)` it gives me another error
`{"line":27764,"column":31,"sourceURL":"http://localhost:8081/index.bundle?platform=android&dev=true&minify=false"}
`
when i reach the line and the column it says there is nothing to look at

first i think that `api `header gives an error but it doesn't possible at beause if the header reproducing it it will not `fetch `the request success

my `ngrok `client says that `POST /imApi/sendMessage success`

## React Native version: 0.62.2```

System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Core(TM) i3-7100 CPU @ 3.90GHz
    Memory: 2.76 GB / 7.89 GB
  Binaries:
    Node: 12.16.2 - C:\node\12.16.2\withNpm\node.EXE
    Yarn: 1.21.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.4 - C:\node\12.16.2\withNpm\npm.CMD
    Watchman: 20200415.154218.0 - C:\Users\hp\Downloads\Compressed\watchman\windows\bin\watchman.EXE
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6308749
  Languages:
    Java: 13.0.1 - C:\Program Files\Java\jdk-13.0.1\bin\javac.EXE
    Python: 3.8.2 - C:\Python38\python.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^16.13.1 => 16.13.1
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found

```
## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. make a class function with react native gifted chat and send a message o your back-end in the send message function
2.log the error and boom you've got it

## Expected Results
Describe what you expected to happen.
the expected result will be a success response

## Snack, code example, screenshot, or link to a repository:
Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

sample code

```
import React, {Component} from 'react'
import {Giftedchat} from 'react-native-gifted-chat'

export Default class extends Component{
state: {
sending : true,

}
constructor(props){
//fetch the old messages
}
render(){
const send = (messages = []) => {
this.setState((previousState) => ({
        messages: GiftedChat.append(previousState.messages, messages),
      }));
     
      console.log('message Send button clicked');
      const newSendMessage = messages[0]['text'];
      var data = new FormData();
      data.append('groupId', this.state.groupIdNew);
      data.append('memberId[]', this.state.members);
      data.append('message', newSendMessage);
      data.append('userId', ApiUserId);
      const withMessage = {
        method: 'POST',
        body: data,
        headers: {
          Authorization: AUTH,
          Authorizationkeyfortoken: AUTH_TOKEN,
        },
      };

      fetch(API_HOST + 'imApi/sendMessage', withMessage)
        .then((res) => res.json())
        .then((json) => {
         console.log(JSON.stringify(json))
        })
        .catch((e) => {
          console.log(JSON.stringify(e));
          
        });
}
return(
<GiftedChat />
)
}
}
//remeber this is a mock code please make your own code
```

**Comment by moddatherrashed** [comment]
I am facing this problem on production, it keeps catching the error even the request did go well.

**Comment by galkinsden** [comment]
similar problem(
