### ISSUE TITLE
Android TextInput with secureTextEntry={true} extremely laggy.

### ISSUE THREAD

**Issue by jorrharris** [facebook/react-native#28911]
## Description
Using a TextInput with secureTextEntry={true} seems extremely laggy on Android. Inputting data into the TextInput seems like it takes 500ms - 1000ms to enter a letter in, and you can type atleast 3 characters before the keyboard responds to your inputs. The TextInput without the secureTextEntry is much faster. After checking the performance, the JS frames can drop below 8fps when typing into the input field. (Yes, I am updating the state in these textInputs, see code below). How can I make this less laggy?

## React Native version:
I'm using Expo SDK v37.0.1

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Create a TextInput without the secureTextEntry attribute
2. Create a TextInput with the secureTextEntry attribute
3. Test the performance when typing in each input

## Expected Results
The 

## Snack, code example, screenshot, or link to a repository:

          <TextInput
            placeholder="Email"
            keyboardType="email-address"
            onChangeText={(text) => this.setState({ email: text })}
            onFocus={this.focusEmail}
          />
          <TextInput
            placeholder="Password"
            secureTextEntry={true}
            onChangeText={(text) => this.setState({ password: text })}
            onFocus={this.focusPassword}
          />

**Comment by jorrharris** [comment]
Lottie Animation was playing in the background.

**Comment by BrotskyS** [comment]
> Lottie Animation was playing in the background.
More details please

**Comment by MaximeTroiano** [comment]
This issue is still present.
I'm on IOS v 14.4 #31223
