### ISSUE TITLE
BackAndroid does not work well.

### ISSUE THREAD

**Issue by shipengyan** [facebook/react-native#2891]
````
var reactAndroidSample = React.createClass({
  displayName: 'ReactAndroidSample',
  componentDidMount: function () {
    BackAndroid.addEventListener('hardwareBackPress', function () {
      console.log('back press event.');

      if (!this.onMainScreen()) {
        this.goBack();
        return true;
      }
      return false;
    });
  },
...
````

the function not trigger when i press the backspace button. why?

**Comment by vjeux** [comment]
If I understand you correctly, you are talking about the backspace button

![nl4pk](https://cloud.githubusercontent.com/assets/197597/9984462/9bf8ff6c-5fcc-11e5-9e8d-15623c40a053.png)

but this module is used to detect the Android hardware back button (at the bottom left of the following screenshot)

![screen shot 2011-12-24 at 6 59 03 pm](https://cloud.githubusercontent.com/assets/197597/9984459/84b3b1e4-5fcc-11e5-91ad-6c474566aa02.png)

**Comment by ivanph** [comment]
See #2801 . Make sure this function is in your MainActivity.java 
```java
@Override
public void onBackPressed() {
    if (mReactInstanceManager != null) {
        mReactInstanceManager.onBackPressed();
    } else {
        super.onBackPressed();
    }
}
```

**Comment by shipengyan** [comment]
@vjeux, I am sorry,  it's back button

**Comment by shipengyan** [comment]
@ivanph  thanks. it works
