### ISSUE TITLE
Error while updating property 'textAlign' in shadow node of type: RCTVirtualText

### ISSUE THREAD

**Issue by artemkhalygov** [facebook/react-native#28925]
## Description
This issue tracked by Sentry and it's happened only few times, but will be good if it's possible to fix.
![image](https://user-images.githubusercontent.com/10270025/82327991-ed8a9980-99e7-11ea-97e8-6d67c4759f36.png)

As you can see it's crashed because textAlign property is not correct. But I don't have property 'start' in my code.
## React Native version:
0.62.2

**Comment by fabriziobertoglio1987** [comment]
impossible to solve without reproducible example

**Comment by ridhoassuryadi** [comment]
Hi, i got the same issue. I think this issue occurred because of trying to render html through web view. You can read the full [explanation here](https://github.com/archriss/react-native-render-html/issues/347#issuecomment-660668784)

**Comment by artemkhalygov** [comment]
Yes, I found problem. There was HTML code with css style { text-align: start }.

**Comment by dhcmega** [comment]
Hi! I have the same problem. Is there any solution? My app crashing because of this.
Thanks!
