### ISSUE TITLE
Failed to find target with hash string 'android-29'

### ISSUE THREAD

**Issue by prahack** [facebook/react-native#28926]
## Description
When I try to run a react-native app, it doesn't build successfully and return "Failed to find target with hash string 'android-29'" error.

## React Native version:
System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 1.69 GB / 7.89 GB
  Binaries:
    Node: 12.16.2 - E:\node.EXE
    npm: 6.14.4 - E:\npm.CMD
  IDEs:
    Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5056338
  Languages:
    Java: 14.0.1 - /c/Program Files/Java/jdk-14.0.1/bin/javac
    Python: Not Found
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5

## Steps To Reproduce
1. install Android Studio
2. clone react-native project on GitHub
3. run npm install
4. run react-native run-android

## Expected Results
Successfully build and run the app on the emulator.

## Snack, code example, screenshot, or link to a repository:
![err](https://user-images.githubusercontent.com/31022509/82336259-f723f980-9a07-11ea-8a5a-8ee07e49604a.jpeg)

**Comment by fabriziobertoglio1987** [comment]
Please close this issue. The error clearly states that you are missing the android emulator image sdk 29

![Screenshot from 2020-05-19 16-17-16](https://user-images.githubusercontent.com/24992535/82337625-46f4c780-99ec-11ea-8fdf-f2e691d5465c.png)


follow the docs https://reactnative.dev/docs/environment-setup and open an issue on stackoverflow if you have problems

**Comment by prahack** [comment]
> Please close this issue. The error clearly states that you are missing the android emulator image sdk 29
> 
> ![Screenshot from 2020-05-19 16-17-16](https://user-images.githubusercontent.com/24992535/82337625-46f4c780-99ec-11ea-8fdf-f2e691d5465c.png)
> 
> follow the docs https://reactnative.dev/docs/environment-setup and open an issue on stackoverflow if you have problems

this solution does not work for me

**Comment by fabriziobertoglio1987** [comment]
search on google for the error message before posting an issue on github 

https://stackoverflow.com/questions/40457524/failed-to-find-target-with-hash-string-android-25

**Comment by prahack** [comment]
> search on google for the error message before posting an issue on github
> 
> https://stackoverflow.com/questions/40457524/failed-to-find-target-with-hash-string-android-25

these solutions do not work for me that's why I posted this as GitHub issue.

**Comment by fabriziobertoglio1987** [comment]
check that directory, you dont have the sdk
