### ISSUE TITLE
React Native Dimensions returns incorrect window size in Share Extension

### ISSUE THREAD

**Issue by EricWiener** [facebook/react-native#28929]
## Description
When using an iOS Share Extension developed with React Native, `Dimensions.get('window').width` will return 0 always, while `Dimensions.get('screen').width` will return the correct version. 

## React Native version:
My React and React Native versions:
```
"react": "16.13.1",
"react-native": "0.62.2",
```

Run `react-native info` in your terminal and copy the results here.
```
System:
    OS: macOS 10.15.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 73.47 MB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 26, 28, 29
      Build Tools: 28.0.3, 29.0.3
      System Images: android-28 | Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  Languages:
    Python: 3.7.3 - /Users/ericwiener/anaconda3/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```
## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Create a share extension using React Native (sorry this step likely makes it hard to reproduce if you don't have one lying around).
2. Use Dimensions.get('screen').width

## Expected Results
The dimensions returned by `Dimensions.get('screen').width` are accurate

## Snack, code example, screenshot, or link to a repository:
Sorry the repository I'm working in is private, but I still wanted to make sure the issue was known.

**Comment by Theo-Cheynel** [comment]
I have a very similar issue, only I am working on a Password AutoFill extension and not a Share Extension. `Dimensions.get('screen').width` works, whereas `Dimensions.get('window').width` returns 0.

**Comment by EricWiener** [comment]
This is still an issue

**Comment by sirnacnud** [comment]
I did some debugging on this issue, for extensions you can't access the keyWindow. I'm not for sure how this could be fixed.

Current code in RCTUtils.m:

```
UIWindow *__nullable RCTKeyWindow(void)
{
  if (RCTRunningInAppExtension()) {
    return nil;
  }

  // TODO: replace with a more robust solution
  for (UIWindow *window in RCTSharedApplication().windows) {
    if (window.keyWindow) {
      return window;
    }
  }
  return nil;
}

**Comment by miladnikad** [comment]
This is still an issue. is there any update?

**Comment by megabayt** [comment]
Facing same issue with react-native-in-app-review v3.2.2 and react-native v0.63.4
