### ISSUE TITLE
[Android] Facing issues with running examples locally

### ISSUE THREAD

**Issue by prathamesh-sonpatki** [facebook/react-native#2892]
When I try to run examples locally for android, I get this exception https://gist.github.com/prathamesh-sonpatki/65601e72ef2a292b4271. I have followed instructions from http://facebook.github.io/react-native/docs/android-setup.html#content to setup android sdk and also set `local.properties` file with `sdk.dir` and `ndk.dir`.

**Comment by jodybrewster** [comment]
You need to make sure you install the android-sdk 23.  In the command line type 'android' to see the list of sdks.  If android isn't installed you'll need to install the sdk & ndk.

**Comment by prathamesh-sonpatki** [comment]
@jodybrewster I have it installed. Please check 
![android sdk manager 2015-09-20 17-47-45](https://cloud.githubusercontent.com/assets/621238/9983124/c6b6e5d2-5fbf-11e5-9b8c-0b1230236230.jpg)

**Comment by ide** [comment]
Did you install the Android Support Repository? https://facebook.github.io/react-native/docs/android-setup.html#content

**Comment by prathamesh-sonpatki** [comment]
@ide that was the issue. Thanks!
