### ISSUE TITLE
There is no response when you click CMD +D or CMD +r on the iOS simulator. But sometimes the first run can be a CMD + D after the normal popover. But the second time you press it, it doesn't matter

### ISSUE THREAD

**Issue by ma569322307** [facebook/react-native#28931]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Please provide a clear and concise description of what the bug is. Include screenshots if needed.
Please test using the latest React Native release to make sure your issue has not already been fixed: https://reactnative.dev/docs/upgrading.html

## React Native version:
Run `react-native info` in your terminal and copy the results here.

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.
2.

## Expected Results
Describe what you expected to happen.

## Snack, code example, screenshot, or link to a repository:
Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by SConaway** [comment]
This happens to me as well. Here's the `react-native info` from my project as well:
```
$ yarn react-native info 
info Fetching system and libraries information...
System:
    OS: macOS 10.15.5
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Memory: 99.38 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.2.0 - /private/var/folders/p7/clrj2l611sb4hpvndl6k1y040000gn/T/xfs-63352211/node
    Yarn: 2.0.0-rc.33 - /private/var/folders/p7/clrj2l611sb4hpvndl6k1y040000gn/T/xfs-63352211/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v14.2.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.2 - /usr/bin/javac
    Python: 3.7.7 - /usr/local/opt/python/libexec/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: ^0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by phil3903** [comment]
I too was facing this issue - no debugging, long boot times, no hot reload (or reloading in general). It all started after upgrading to macOS 10.15.5, and upgrading Xcode. My guess is theres something broken with RN62 on 10.15.5. Upgrading to RN63-rc1 has fixed all my issues. Hopefully you have the ability to give that a try. I'm optimistic we'll get a prod release for RN63 soon.

**Comment by SConaway** [comment]
Yes. I did notice that. Just thought I'd share the info if any devs wanted to triage it

**Comment by RageBill** [comment]
This is probably due to the emulator not getting your input. This problem happens randomly to me too, usually after fast refresh on code changes.

To fix, you can go to the top bar > `I/O` > `Input` > `Send Keyboard Input to Device`.

After that, your CMD + D or CMD + R will function again.

**Comment by kamui545** [comment]
Please see https://github.com/facebook/react-native/issues/27384

**Comment by thangtmc73** [comment]
@kamui545 The solution with #27384 could not fix this problem. I tried using iOS 13.3 and other solutions but in there but nothings worked.

**Comment by SConaway** [comment]
Yeah. Sometimes it stays checked, others not. That is the main issue that I have. I'm going to try reporting this as a bug for XCode.

**Comment by AndriiChubariev** [comment]
Noticed it as well!

**Comment by defualt** [comment]
Press R, and then press Command + R

**Comment by GreatAuk** [comment]
> Press R, and then press Command + R

Press R, and then press Command + R
Press D, and then press Command + D
😭

**Comment by kamui545** [comment]
It looks like this is finally fixed on XCode 12 + iOS 14 ✨

**Comment by safaiyeh** [comment]
Closing as the issue template is not filled out. Please create a new issue with all fields filled out.

**Comment by Fannolo** [comment]
> Press R, and then press Command + R 

This worked for me
