### ISSUE TITLE
TextInput piles up the letters

### ISSUE THREAD

**Issue by waelvilla** [facebook/react-native#28936]
## Description
When typing into the TextInput box, sometimes the letteres get piled up all in one place instead of showing up like normal text. Some other times, no text shows up at all in the box. This has been observed on Huawei P30 so far. The text does indeed get saved and goes through `onChangeText` , but it does not display correctly on UI. We tried switching to G board but the same bug occured there too, so we're doubting it being a keyboard problem. I have attached some videos to demonstrate it. 
Has anyone experienced anything similar? 
[text piling up video ](https://trello-attachments.s3.amazonaws.com/5e08aaa25f31910a8c8051b7/5e9f6c38e5865026746518fc/6d1a7242c1d279bca57b38ac52d1d104/SVID_20200422_005538_1.mp4)
[text disappearing video](https://trello-attachments.s3.amazonaws.com/5e08aaa25f31910a8c8051b7/5e9f6c38e5865026746518fc/6d1a7242c1d279bca57b38ac52d1d104/SVID_20200422_005538_1.mp4)

## React Native version:
System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
    Memory: 3.02 GB / 15.68 GB
  Binaries:
    Node: 10.16.0 - D:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - D:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - D:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 25, 26, 28, 29
      Build Tools: 28.0.3, 29.0.0, 29.0.1
      System Images: android-28 | China version of Wear OS Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4

## Steps To Reproduce
So far we could not reproduce the problem on development. It only occured in production App and Sentry couldn't capture anything as it is a UI bug. We could not find a pattern that results in reproducing this bug. It seems to occur at random times
It might be worth noting that the users mostly type in Arabic. However, once the bug occurs, switching to English leads to the same behavior, and the English letters end up being piled up as well. 

## Expected Results
The full text is expected to be displayed on the screen in a readable way. 

## Code example
Here is the code of my TextInput and its styling. Most of the styling has been added in attempt to specifically fix the bug

```
  renderComposer(props) {
    const { text } = this.state
    const { placeholder } = this.state.lang.ar
    const inputStyle = this.inputStyle(text)
    const isNewLine = /\r?\n/.test(text[0]) ? false : true

    return (
      <TextInput
        value={text}
        multiline={isNewLine}
        style={[styles.textInput, inputStyle]}
        autoFocus={true}
        onChangeText={(text) => this.onTextInput(text)}
        placeholder={placeholder}

      />
    )
  }

  inputStyle = (text) => {
    let numberOfLines = text.split(/\r?\n/).length;
    let marginTop = 3;
    let marginBottom = 3
    let paddingBottom = 10
    let paddingTop = 10
    if (numberOfLines > 2) {
      marginTop = 15
      marginBottom = 7
    }
    return {
      marginTop, paddingTop, marginBottom, paddingBottom
    }
  }

const styles =  StyleSheet.create({
  textInput: {
    flex: 1,
    marginLeft: 10,
    fontSize: 16,
    lineHeight: 16,
    maxHeight: 200,
    justifyContent: 'flex-end',
    alignSelf: 'center',
    direction: Platform.select({
      ios: 'rtl'
    }),
    marginTop: Platform.select({
      ios: 6,
      android: 0,
    }),
    marginBottom: Platform.select({
      ios: 7,
      android: 3,
    }),
  },
})
```

**Comment by TheAlienDrew** [comment]
I've also been experiencing this issue, from what I can tell, Android version doesn't matter, Webview version doesn't matter, but what has been a weird factor is the different device models, which to me doesn't make a whole lot of sense. Here's a small list of confirmed devices that are having issues with text input: Redmi Note 7, Sony G8342, Samsung J5 SM-G570M, and including my own phone a Samsung Galaxy S10e... My assumption is either, device manufacturers are turning on a feature in a system update that breaks text input for react native, or there is an issue with language text localization that causes input issues for some, while not causing it for others.
