### ISSUE TITLE
Getting "Should not already be working."

### ISSUE THREAD

**Issue by azizhk** [facebook/react-native#28948]
## Description
Our users are facing a lot of crashes with this error message without any information related to the component which caused this error or what lifecycle.

Screenshot from app:
![1](https://user-images.githubusercontent.com/5094296/82631978-90bff680-9c14-11ea-80f6-a7c9f5bca89d.png)

Screenshot from Bugsnag Error Report:
<img width="1291" alt="Screenshot 2020-05-22 at 10 11 58 AM" src="https://user-images.githubusercontent.com/5094296/82632031-bcdb7780-9c14-11ea-8895-5b5a46f8a216.png">

## React Native version:
Run `react-native info` in your terminal and copy the results here.
```
System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Memory: 29.42 MB / 8.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.16.1 - /var/folders/wb/fwkfg3q119bbp5_9sqch657m0000gn/T/yarn--1590122549879-0.7328687889363668/node
    Yarn: 1.22.0 - /var/folders/wb/fwkfg3q119bbp5_9sqch657m0000gn/T/yarn--1590122549879-0.7328687889363668/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK: Not Found
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28
      Build Tools: 26.0.0, 26.0.2, 27.0.3, 28.0.2, 28.0.3, 29.0.2
      System Images: android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_161 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Don't have any. If we had some information related to which component is causing maybe we can help isolate what's causing this. Is this maybe the bizzaro context Sebastian Markbåge talks about in [this tweet](https://twitter.com/sebmarkbage/status/1258856732656164864).

## Expected Results
Should not crash the app.

## Snack, code example, screenshot, or link to a repository:
If we can add some information to the error related to the component or lifecycle, maybe we can understand what might be causing and would help provide a meaningful reproduction.

**Comment by fabriziobertoglio1987** [comment]
https://github.com/facebook/react-native/search?q=%22Should+not+already+be+working.%22&unscoped_q=%22Should+not+already+be+working.%22&type=Code

**Comment by cristianoccazinsp** [comment]
Just saw this today as well from the error reporting tool. 

Android 7 (old device) I believe. RN 0.61.5

**Comment by cristianoccazinsp** [comment]
Still happening

**Comment by sirajulm** [comment]
Still happening. Unable to reproduce it manually.
