### ISSUE TITLE
Animated just animate first time, don't show animation when Animated.timing back to old value

### ISSUE THREAD

**Issue by iamvucms** [facebook/react-native#28941]
## React Native version:
Binaries:
    Node: 13.10.1 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.7 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  Languages:
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

`
 import React, { useRef, useState, RefObject, MutableRefObject, useEffect } from 'react'
import { StyleSheet, Animated, View, TouchableOpacity } from 'react-native'
export interface SwitcherOptions {
    onTurnOn: () => void,
    onTurnOff: () => void,
    on: boolean
}
const index = ({ on, onTurnOn, onTurnOff }: SwitcherOptions) => {
    const _circleOffsetx = new Animated.Value(0)
    const _onToggle = () => {
        if (on) {
            onTurnOff()
        } else {
            onTurnOn()
        }
    }
    useEffect(() => {
        if (on) {
            Animated.timing(_circleOffsetx, {
                toValue: 35 - 24,
                duration: 200,
                useNativeDriver: false
            }).start()
        } else {
            Animated.timing(_circleOffsetx, {
                toValue: 0,
                duration: 200,
                useNativeDriver: false
            }).start()
        }
    }, [on])
    
    return (
        <TouchableOpacity
            onPress={_onToggle}
            activeOpacity={1}
            style={{
                ...styles.container,
                backgroundColor: on ? '#78b5ff' : 'gray'
            }}>
            <Animated.View style={{
                ...styles.circle,
                backgroundColor: on ? '#318bfb' : '#ddd',
                left: _circleOffsetx,
            }} />
        </TouchableOpacity>
    )
}

export default index

const styles = StyleSheet.create({
    container: {
        height: 15,
        width: 35,
        borderRadius: 10,
        position: 'relative'
    },
    circle: {
        position: 'absolute',
        zIndex: 1,
        top: (15 - 24) / 2,
        height: 24,
        width: 24,
        borderRadius: 24,

    }
})

`
2.

## Expected Results
I used Animated from react-native but, I only got animation on first time. But when I use Animated 2nd to back to old value, I don't see any animation, even callback was called after 200ms.
Hope you can help me get out this issue. Thank for reading

**Comment by 3plusalpha** [comment]
It might be the same issue like this one: #27003

**Comment by iamvucms** [comment]
I fixed with React.useMemo(()=>new Animated.Value(0),[])
