### ISSUE TITLE
React Native App Crashes on Launch in Android (API 19)

### ISSUE THREAD

**Issue by Gogul-S** [facebook/react-native#28940]
## Description
I have created a project with **react-native-cli**

When I launch the app using the command "**react-native run-android**" on Devices and Emulators with Android API level 21+ App is launching.

But for devices less than API 21, the app crashing on launch.

I have specified in **android gradle minSdk version to 16**.

I viewed the stack trace using **"adb logcat"** the crash was due to **OkHttp3** that is used internally somewhere.

**I haven't used any OkHttp3 Dependency explicitly in my app**

## React Native version:
6.14.4

## Steps To Reproduce

1. Create a project using react-native CLI **not Expo CLI**
2. Navigate to the project folder
3. Connect a device or an emulator with API less than 21
3. run command "react-native run-android" to run app on the connected device

## Expected Results
The App should launch without any crash.

## Android Logs
```
 E/AndroidRuntime( 3745): java.lang.RuntimeException: Unable to create application com.infifive.MainApplication: java.lang.RuntimeException: Requested enabled DevSupportManager, but DevSupportManagerImpl class was not found or could not be created
E/AndroidRuntime( 3745): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4347)
E/AndroidRuntime( 3745): 	at android.app.ActivityThread.access$1500(ActivityThread.java:135)
E/AndroidRuntime( 3745): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
E/AndroidRuntime( 3745): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 3745): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 3745): 	at android.app.ActivityThread.main(ActivityThread.java:5017)
E/AndroidRuntime( 3745): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 3745): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 3745): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
E/AndroidRuntime( 3745): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
E/AndroidRuntime( 3745): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 3745): Caused by: java.lang.RuntimeException: Requested enabled DevSupportManager, but DevSupportManagerImpl class was not found or could not be created
E/AndroidRuntime( 3745): 	at com.facebook.react.devsupport.DevSupportManagerFactory.create(DevSupportManagerFactory.java:90)
E/AndroidRuntime( 3745): 	at com.facebook.react.ReactInstanceManager.<init>(ReactInstanceManager.java:238)
E/AndroidRuntime( 3745): 	at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:281)
E/AndroidRuntime( 3745): 	at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:87)
E/AndroidRuntime( 3745): 	at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:39)
E/AndroidRuntime( 3745): 	at com.infifive.MainApplication.onCreate(MainApplication.java:47)
E/AndroidRuntime( 3745): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
E/AndroidRuntime( 3745): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4344)
E/AndroidRuntime( 3745): 	... 10 more
E/AndroidRuntime( 3745): Caused by: java.lang.reflect.InvocationTargetException
E/AndroidRuntime( 3745): 	at java.lang.reflect.Constructor.constructNative(Native Method)
E/AndroidRuntime( 3745): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
E/AndroidRuntime( 3745): 	at com.facebook.react.devsupport.DevSupportManagerFactory.create(DevSupportManagerFactory.java:80)
E/AndroidRuntime( 3745): 	... 17 more
E/AndroidRuntime( 3745): Caused by: java.lang.ExceptionInInitializerError
E/AndroidRuntime( 3745): 	at okhttp3.OkHttpClient.newSslSocketFactory(OkHttpClient.java:263)
E/AndroidRuntime( 3745): 	at okhttp3.OkHttpClient.<init>(OkHttpClient.java:229)
E/AndroidRuntime( 3745): 	at okhttp3.OkHttpClient$Builder.build(OkHttpClient.java:1015)
E/AndroidRuntime( 3745): 	at com.facebook.react.devsupport.DevServerHelper.<init>(DevServerHelper.java:132)
E/AndroidRuntime( 3745): 	at com.facebook.react.devsupport.DevSupportManagerImpl.<init>(DevSupportManagerImpl.java:183)
E/AndroidRuntime( 3745): 	... 20 more
E/AndroidRuntime( 3745): Caused by: java.lang.IllegalStateException: Expected Android API level 21+ but was 19
E/AndroidRuntime( 3745): 	at okhttp3.internal.platform.AndroidPlatform.buildIfSupported(AndroidPlatform.java:238)
E/AndroidRuntime( 3745): 	at okhttp3.internal.platform.Platform.findPlatform(Platform.java:202)
E/AndroidRuntime( 3745): 	at okhttp3.internal.platform.Platform.<clinit>(Platform.java:79)
```
## Screenshot
![image](https://user-images.githubusercontent.com/65705377/82538501-75e47800-9b69-11ea-863a-8421f8e0d1a1.png)

**Comment by info-bit** [comment]
Hi @Gogul-S finally someone else with the same problem. This is probably a duplicate of #28924. Do you use Hermes Engine? If so, are you able to build in release mode with Hermes enables? I don't know if running on old Android api and building with Hermes are affected by the same problem or not.

**Comment by Gogul-S** [comment]
No I am not using Hermes Engine

**Comment by Gogul-S** [comment]
> Hi @Gogul-S finally someone else with the same problem. This is probably a duplicate of #28924. Do you use Hermes Engine? If so, are you able to build in release mode with Hermes enables? I don't know if running on old Android api and building with Hermes are affected by the same problem or not.

No I am not using Hermes Engine.

And this not a duplicate.

#28924 error log is noClassDef found.

Here OkHttp expects API 21+ though I have specified minSdk as 16

**Comment by info-bit** [comment]
Try to disable Flipper entirely. This is not related to the Hermes issue.

**Comment by Gogul-S** [comment]
> Try to disable Flipper entirely. This is not related to the Hermes issue.
How to disable Flipper ?

**Comment by info-bit** [comment]
https://github.com/facebook/react-native/issues/28481#issuecomment-615359320. Sadly Flipper seems to be only a part of the problem in my app.

**Comment by Gogul-S** [comment]
> [#28481 (comment)](https://github.com/facebook/react-native/issues/28481#issuecomment-615359320). Sadly Flipper seems to be only a part of the problem in my app.

Disabling Flipper also didn't work for me

OkHttp3 is being used internally somewhere by the RN framework, which expecting API level 21+.

Is there a way to configure this for API less than 21+ ?

**Comment by fabriziobertoglio1987** [comment]
need to upgrade dependencies here 

https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/third-party/java/okhttp/BUCK#L13
with
https://stackoverflow.com/a/59213435/11452286

I tried but the problem reproduces..

**Comment by Gogul-S** [comment]
Release build works fine one API level below 21.

Since there is no reply or anymore comments on this issue,

As of my understanding,

We cannot use Android devices with API less than 21 for debugging react-native apps

**Comment by MartinGao** [comment]
Same issue here.
Release build works fine but Debug build keeps getting errors.

**Comment by fabriziobertoglio1987** [comment]
@Gogul-S I know, I tried to update react-native master dependencies and I re-created this test case in an app that is using react-native from source... but I think that I need to trigger a buck build ... react native uses buck to build dependencies

I don't know buck well so I focus on other issues

**Comment by safaiyeh** [comment]
Hi @Gogul-S, sorry for not getting to this sooner. OkHttp 3.12.x branch supports Android 2.3+ (API level 9+), [Source](https://github.com/square/okhttp#requirements)

This might be an issue outside of OkHttp, is this still an issue for you?
