### ISSUE TITLE
Line height of Gilroy font in Text component is not respected

### ISSUE THREAD

**Issue by vijayst** [facebook/react-native#28949]
## Description
When I specify a line height for Gilroy font, I am getting a line height which is 6 pixels more than the specified line height. In the below screen shot, the font size is 24 pixels, line height is 25 pixels. And total height of text component is 62 pixels. So, the line height for each line is 31 pixels - 6 pixels more than the specified line height.

<img width="308" alt="Screenshot 2020-05-21 at 10 39 30 PM" src="https://user-images.githubusercontent.com/3457565/82633966-35910280-9c1a-11ea-8bc3-feeb5cbf1d9f.png">

## React Native version:
RN version: 0.61.5

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Specify line height of text component with Gilroy font
2. Verify the text component display

## Expected Results
The height of the text component should be the same as the line height specified.

## Snack, code example, screenshot, or link to a repository:
I have a Github repo with Gilroy Bold font and minimum reproducible example.
[https://github.com/vijayst/font-height](https://github.com/vijayst/font-height)

**Comment by fabriziobertoglio1987** [comment]
@vijayst Do you still experience this issue? If yes, I will publish the fix in the react-native-improved package https://github.com/fabriziobertoglio1987/react-native-improved. Thanks a lot

**Comment by fabriziobertoglio1987** [comment]
@vijayst  I wanted to ask if you still experience this issue. 
I'm planning to do 1-2 months of opensource and I'm preparing a list of tasks.

I have been contributing to facebook/react-native for 4 years and I specialize on the Text/TextInput components.

Thanks a lot

**Comment by vijayth2-cerebras** [comment]
@fabriziobertoglio1987 That was a long time back. I think I resolved it by switching to some other font.

**Comment by fabriziobertoglio1987** [comment]
yes, because each font has their own ascent/descent. iOS does not adjust the baseline of the text based on the font, so I'm sure this real issue on iOS, don't know andorid

**Comment by fabriziobertoglio1987** [comment]
https://github.com/facebook/react-native/pull/38359
