### ISSUE TITLE
How to set focus in TouchableHighlight?

### ISSUE THREAD

**Issue by artem54325** [facebook/react-native#28957]
I am trying to set and turn off the focus in the TouchableHighlight item for Android TV for remote control,
How can I do that?

npm -v
6.13.4
react-native -v
react-native-cli: 2.0.1

```
  enableTVEventHandler() {
    this.evtHandler = new TVEventHandler();
    this.evtHandler.enable(this, this.handleTVRemoteEvent);
  }

  disableTVEventHandler() {
    if (this.evtHandler) {
      this.evtHandler.disable();
      delete this.evtHandler;
    }
  }
  handleTVRemoteEvent = (cmp, event) => {
    const { eventType, tag } = event;
  }
  render() {
    const { children, hide, ...props } = this.props;

    return (
      <TouchableHighlight {...props} ref={this.myRef} style={[props.style]}>
        {children}
      </TouchableHighlight>
    )
```

**Comment by artem54325** [comment]
I updated:
System:
    OS: Linux 5.3 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
    Memory: 818.41 MB / 11.64 GB
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 10.19.0 - /usr/bin/node
    npm: 6.13.4 - /usr/bin/npm
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
  npmPackages:
    react: ^16.13.1 => 16.13.1 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    create-react-native-app: 2.0.2
    react-native-cli: 2.0.1

**Comment by fabriziobertoglio1987** [comment]
https://github.com/facebook/react-native/issues/24448#issuecomment-633460564
