### ISSUE TITLE
Network request failed with every trick

### ISSUE THREAD

**Issue by nimahkh** [facebook/react-native#28950]
when I want to upload a taken photo by react native camera with (axios, fetch , xhr) i got : Network request failed, error. 

## Description
i test it with axios, fetch and XHR and result is same, 

## React Native version:
0.62.2

## what I tried

1. commenting Flip in MainApplication
2. creating {uri, name, type} object and removing file:// for ios ( my test env is on android)
3. adding android:usesCleartextTraffic="true"> inside AndroidManifest.xml 
4. adding  network_security_config inside xml 
5. upgrading flipping version to 0.41
6. testing with fetch , axios and xhr, multipar/form-data with credentials. 

These are what I did and getting error again. 
I read a lot of issues and posts about it and did all of them, but nothing changed. 
Can you please give me a guide?

**Comment by dotfelixb** [comment]
Try this https://github.com/facebook/react-native/issues/25244#issuecomment-632740422

**Comment by wildseansy** [comment]
I had to use https://github.com/joltup/rn-fetch-blob to get this to work on android

**Comment by IamDhana** [comment]
I solved the issue by upgrading to the latest Flipper version in the following file

android/gradle.properties 

`#Version of flipper SDK to use with React Native.

FLIPPER_VERSION=0.44.0 // Upgrade to the latest flipper version`

[Check this comment](https://github.com/facebook/react-native/issues/28551#issuecomment-624347067)

**Comment by safaiyeh** [comment]
Hi @nimahkh apologies for not getting to this sooner. This has been a long standing issue, you can check it out this comment for work arounds: https://github.com/facebook/react-native/issues/28551#issuecomment-682276503
