### ISSUE TITLE
Build Error from "react-native run-ios" command

### ISSUE THREAD

**Issue by anupamhore** [facebook/react-native#28955]
## Description
Created a new project using react-native command. Everything is created including the pod for iOS.But when I tried to run the command 
react-native run-ios 
I am getting error

CompileC /Users/XXX/Library/Developer/Xcode/DerivedData/albums-gnnqffkyfazehwcywcchxrdqkvpd/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-RCTText.build/Objects-normal/x86_64/RCTBaseTextInputView.o /ReactNative/albums/node_modules/react-native/Libraries/Text/TextInput/RCTBaseTextInputView.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler

How to solve this? I tried running from xcode as well. There also getting error 

## React Native version:
System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 1.09 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 11.3, macOS 10.13, tvOS 11.3, watchOS 4.3
    Android SDK:
      API Levels: 21, 22, 23, 24, 25, 26, 27, 28, 29
      Build Tools: 28.0.3
      System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.4 AI-183.5429.30.34.5452501
    Xcode: 9.3.1/9E501 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_211 - /usr/bin/javac
    Python: 3.7.3 - /Users/anupamhore/anaconda3/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found
## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Created project from react-native
2. Run react-native run-ios

## Expected Results
Describe what you expected to happen.
It should open the simulator and the project should open

**Comment by anupamhore** [comment]
Guys any help on this

**Comment by fabriziobertoglio1987** [comment]
it is not an error .. just says CompileC

probably you need to have clang installed 

https://apple.stackexchange.com/questions/227026/how-to-install-recent-clang-with-homebrew

anyway follow the instructions on the website to set up your environment

https://reactnative.dev/docs/environment-setup

if you can not set up react-native env, then just opt out and use expo

You don't have an error.

Good luck

**Comment by fabriziobertoglio1987** [comment]
https://www.google.com/search?client=ubuntu&channel=fs&q=xcode+delete+derived+data&ie=utf-8&oe=utf-8
