### ISSUE TITLE
Android: No way to pass js-touches through the views without "pointerEvents="NONE"

### ISSUE THREAD

**Issue by stephenkopylov** [facebook/react-native#28953]
Hi all and thanks for this project!

We are creating this small [library](https://github.com/ibitcy/react-native-hole-view) to cut the holes inside view and pass clicks through them.

So, we faced that there is no way on Android to pass **js-touch** events (that needed for all Touchables) through the custom view, using default android's way 
```java
onTouchEvent(event: MotionEvent){
   return false;
}
```

The one and only click-checking mechanism, that we've found located in **TouchTargetHelper.java** and it uses only view's bounding (top, bottom, left, right) + hitSlopRect

<details>

<summary>code:</summary>  

```java
private static boolean isTransformedTouchPointInView(
      float x, float y, ViewGroup parent, View child, PointF outLocalPoint) {
    float localX = x + parent.getScrollX() - child.getLeft();
    float localY = y + parent.getScrollY() - child.getTop();
    Matrix matrix = child.getMatrix();
    if (!matrix.isIdentity()) {
      float[] localXY = mMatrixTransformCoords;
      localXY[0] = localX;
      localXY[1] = localY;
      Matrix inverseMatrix = mInverseMatrix;
      matrix.invert(inverseMatrix);
      inverseMatrix.mapPoints(localXY);
      localX = localXY[0];
      localY = localXY[1];
    }
    if (child instanceof ReactHitSlopView && ((ReactHitSlopView) child).getHitSlopRect() != null) {
      Rect hitSlopRect = ((ReactHitSlopView) child).getHitSlopRect();
      if ((localX >= -hitSlopRect.left
              && localX < (child.getRight() - child.getLeft()) + hitSlopRect.right)
          && (localY >= -hitSlopRect.top
              && localY < (child.getBottom() - child.getTop()) + hitSlopRect.bottom)) {
        outLocalPoint.set(localX, localY);
        return true;
      }

      return false;
    } else {
      if ((localX >= 0 && localX < (child.getRight() - child.getLeft()))
          && (localY >= 0 && localY < (child.getBottom() - child.getTop()))) {
        outLocalPoint.set(localX, localY);
        return true;
      }

      return false;
    }
  }
```

</details>

So we'd like to write some custom method to check click availability for View.

Something like 
```java
interceptsTouchEvent(touchX: Float, touchY: Float): Boolean
```
for ReactViewGroup
What do you guys think about it? 

## Description
Violet view - custom android's view (inherited from `ReactViewGroup`) with 
```java
onTouchEvent(event: MotionEvent){
   return false;
}
```

So it's passes all native touches to scroll view, but don't do it with `TouchableOpacity`

![out](https://user-images.githubusercontent.com/5202281/82710364-60676f00-9c8b-11ea-84e2-4a4f3f50c24f.gif)

## React Native version:
System:
    OS: macOS 10.15.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 195.21 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.2 - ~/.nvm/versions/node/v12.16.2/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.16.2/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /Users/stepankopylov/.rvm/rubies/ruby-2.6.3/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 28, 29
      Build Tools: 28.0.3, 29.0.2, 30.0.0
      System Images: android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_222 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Create native android module with view that passes all touches through 
Cover all the screen with it, put some Touchables under, and try to click

## Expected Results
Passing clicks to Touchables under

**Comment by stephenkopylov** [comment]
I've made PR for solve this issue:
https://github.com/facebook/react-native/pull/28956

It would be nice if some'll have a look on it

**Comment by safaiyeh** [comment]
Hi @stephenkopylov thanks for the issue and the PR! I'm curious if Pressable component would solve your issues with this?

**Comment by stephenkopylov** [comment]
Hi @safaiyeh!

We in our team are going to check if `onTouchEvent` is calling with Pressable

But in this case we'll need to force users use Pressable instead of Touchable, so the root of problem (impossibility to make proper hit-test for transparent pixels) will not be solved...

**Comment by safaiyeh** [comment]
Agreed! I'm leaving this open until your PR can be looked at.

If Pressable, solves your case it could be a quicker solve for you but definitely TocuhableOpacity is not working as expected.

**Comment by fabriziobertoglio1987** [comment]
when you prepare a pr that solves an issue, you can connect it to the issue by including the following text in the pr summary

fixes https://github.com/facebook/react-native/issues/28953

this will automatically link the issue to the pr, once the pr is merged the issue will automatically be closed
additionally a very useful icon shows in the issues list so other developers do not try to solve it

![image](https://user-images.githubusercontent.com/24992535/108335712-89457200-71d3-11eb-9cf3-bb1f9c47d6a1.png)

and also on top of the issue, it will show the linked pr so other developers do not troubleshooot that issue

![image](https://user-images.githubusercontent.com/24992535/108335755-95c9ca80-71d3-11eb-93e1-5aa2729a38a5.png)

more info
https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue

thanks a lot for the pr :pray: :peace_symbol:
