### ISSUE TITLE
TextInput not calling onChangeText

### ISSUE THREAD

**Issue by ntachev** [facebook/react-native#28964]
It seems like setting the numberOfLines={1} prop or setting the css property to overflow: 'hidden' on a TextInput stops it from calling onChangeText when initially rendered with a text that would cause it to overflow

please fix or let me know if already fixed <3

"dependencies": {
"expo": "^35.0.1",
"native-base": "^2.13.8",
"node-libs-browser": "^2.2.1",
"node-libs-react-native": "^1.0.3",
"react": "16.8.3",
"react-dom": "16.8.3",
"react-native": "0.59.10",
"react-native-elements": "^1.2.7",
"react-native-masked-text": "^1.13.0",
"react-native-router-flux": "^4.2.0",
"react-native-screens": "^1.0.0-alpha.23",
"react-native-unimodules": "0.6.0",
"react-native-web": "^0.11.7",
},
"devDependencies": {
"@babel/core": "^7.8.7",
"@types/react": "^16.9.23",
"@types/react-native": "^0.57.65",
"babel-jest": "24.9.0",
"babel-preset-expo": "^7.1.0",
"jest": "24.9.0",
"jest-expo": "^35.0.0",
"jetifier": "^1.6.5",
"metro-react-native-babel-preset": "0.56.0",
"react-test-renderer": "16.9.0",
"typescript": "^3.8.3"
},

Testing with input 1010101010101010101010101010101010101010
TextInput size of around 200px on iPhone X

## Expected Results
for onChangeText to be called

**Comment by ntachev** [comment]
info
  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
      Memory: 3.99 GB / 15.82 GB
    Binaries:
      Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.1.0.0 AI-173.4720617

**Comment by safaiyeh** [comment]
Hi @ntachev thanks for the issue! Been a while since you reported this.

Can you confirm this happens on the latest RN version and provide a Snack that demonstrates this.
