### ISSUE TITLE
Android resource linking failed  /home/harouna/.gradle/caches/transforms-2/files-2.1/efad880540fb7feb42c301dc466f4bf9/appcompat-1.0.2/res/values-v26/values-v26.xml:5:5-8:13: AAPT: error: resource android:attr/colorError not found.

### ISSUE THREAD

**Issue by hadpro24** [facebook/react-native#28969]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Please provide a clear and concise description of what the bug is. Include screenshots if needed.
Please test using the latest React Native release to make sure your issue has not already been fixed: https://reactnative.dev/docs/upgrading.html

## React Native version:
Run `react-native info` in your terminal and copy the results here.

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. ./gradlew assembleRelease -x bundleReleaseJsAndAssets

## Expected Results
Building the app release.

## Snack, code example, screenshot, or link to a repository:
Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by fabriziobertoglio1987** [comment]
very bad. You provided 0 info for this issue

**Comment by hadpro24** [comment]
> very bad. You provided 0 info for this issue

I get an error during the build .. with ./gradlew assembleRelease

error console: Android resource linking failed

**Comment by jonneymendoza** [comment]
HI. DId this ever get resolved? I am getting the same error
