### ISSUE TITLE
Component Elevation Shadow when screen change

### ISSUE THREAD

**Issue by Shanks0465** [facebook/react-native#28975]
## Description
A background shadow of the component (elevation set to 1 and above) gets casted on the background when transitioning between screens.

## React Native version:
System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
    Memory: 1.58 GB / 7.86 GB
  Binaries:
    Node: 14.2.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 26.0.3, 28.0.3, 29.0.2, 30.0.0
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6241897
  Languages:
    Java: javac 14 - C:\Program Files\Java\jdk-14\bin\javac.EXE
    Python: 2.7.18 - C:\Python27\python.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.Create a new App
2.Add two screens along with navigation( BottomTabNavigation)
3. Create a View Component with elevation set to 1 or above (Code Given Below)
4.Run App and switch between screens.

## Expected Results
Switch Between Screens without component shadow being rendered when changing screens

## Code Along with Recording:
```
import React, { Component } from 'react'
import { View, Text, StyleSheet,TouchableOpacity } from 'react-native'

export default class MyGoals extends Component {
    render() {
        return (
            <View>
                <View style={{height:100,width:100,elevation:10,backgroundColor:'white',borderRadius:15}}>

                </View>
            </View>
        )
    }
}
```
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/48712410/82878986-f20c0080-9f59-11ea-8456-68adba6b8efa.gif)

**Comment by chrisglein** [comment]
> 2.Add two screens along with navigation( BottomTabNavigation)

What are you using to transition between screens? There are a couple of community navigation modules. Which are you using? This likely is an issue in the transition animation being used by that module and will need to be reported against that repo.

**Comment by Shanks0465** [comment]
I am using reactnavigation
