### ISSUE TITLE
Scrollview horizontal wrap container when keyboard pop up (only Android ) 

### ISSUE THREAD

**Issue by michaelVictoriaDev** [facebook/react-native#28971]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Im using Scrollview horizontal={true}  Im having a problem when the keyboard pop up the scroll view wrapped

![image](https://user-images.githubusercontent.com/44763288/82853253-d859c180-9f37-11ea-871e-d4827951dcc3.png)

## React Native version:
Run `react-native info` in your terminal and copy the results here.

```
 System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 123.28 MB / 8.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 13.10.1 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.7 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: 10.1/10B61 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

you can show the gif the container of scrollview is wrapped
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/44763288/82853356-266ec500-9f38-11ea-8fa4-1975b8bcde57.gif)

## Expected Results
the scrollview height will not be wrapped

**Comment by fabriziobertoglio1987** [comment]
please publish example on https://snack.expo.io/ and I ll try to fix this issue in a pull request. Thanks
