### ISSUE TITLE
com.facebook.react.bridge.ReadableNativeMap cannot be cast to java.lang.string

### ISSUE THREAD

**Issue by orihero** [facebook/react-native#28978]
## Description
In my app have to listen for `startActivityForResult`. I have implemented it as described in [here][1]

  [1]: https://reactnative.dev/docs/native-modules-android.html#getting-activity-result-from-startactivityforresult

Here is the code of native module implementation

    //Module initialization
    Module(ReactApplicationContext reactContext) {
        super(reactContext);
        this.reactContext = reactContext;
        reactContext.addActivityEventListener(mActivityEventListener);
    }

    private final ActivityEventListener mActivityEventListener = new BaseActivityEventListener() {
        @Override
        public void onActivityResult(Activity activity, int requestCode, int resultCode, Intent data) {
            //Throws an error on any kind of argument 
            //com.facebook.react.bridge.ReadableNativeMap cannot be cast to java.lang.string
            WritableArray result = Arguments.createArray();
            result.pushString("VAL");
            promise.resolve(result);
        }
    }

    @ReactMethod
    public void anyMethod(ReadableMap params, final Promise promise) {
        this.promise = promise;
        Intent intent = new Intent();
        intent.setClassName("APP_NAME", "APP_ACTIVITY");
        getReactApplicationContext().startActivityForResult(intent, REQUEST_CODE, null);
    }

When it successfully reaches to `onActivityResult` but it fails to resolve promise with any argument with exception:

> com.facebook.react.bridge.ReadableNativeMap cannot be cast to java.lang.string
## React Native version:
OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 154.78 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.8.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.10.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 26, 27, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Created a native module inside of main/java/APP_NAME/
2. Added to the packages in getPackages() of `MainApplication

## Expected Results
Promise had to be resolved successfully

## Snack, code example, screenshot, or link to a repository:
stackoverflow link: https://stackoverflow.com/questions/62020491/react-bridge-readablenativemap-cannot-be-cast-to-java-lang-string

**Comment by fabriziobertoglio1987** [comment]
react native uses special types `ReadableNativeMap` to cast the result of the promise from the Java JSON/Array format to Javascript JSON format

check this [example](https://github.com/react-native-community/react-native-camera/blob/master/android/src/main/java/org/reactnative/camera/CameraModule.java#L327-L352) on how to use the bridge ... or review the code from the react-native repository to see how they use the bridge

Obviously `promise.resolve("value")` is wrong

should be something like 

```java
  @ReactMethod
  public void getSupportedRatios(final int viewTag, final Promise promise) {
      final ReactApplicationContext context = getReactApplicationContext();
      UIManagerModule uiManager = context.getNativeModule(UIManagerModule.class);
      uiManager.addUIBlock(new UIBlock() {
          @Override
          public void execute(NativeViewHierarchyManager nativeViewHierarchyManager) {
              final RNCameraView cameraView;
              try {
                  cameraView = (RNCameraView) nativeViewHierarchyManager.resolveView(viewTag);
                  WritableArray result = Arguments.createArray();
                  if (cameraView.isCameraOpened()) {
                      Set<AspectRatio> ratios = cameraView.getSupportedAspectRatios();
                      for (AspectRatio ratio : ratios) {
                          result.pushString(ratio.toString());
                      }
                      promise.resolve(result);
                  } else {
                      promise.reject("E_CAMERA_UNAVAILABLE", "Camera is not running");
                  }
              } catch (Exception e) {
                  e.printStackTrace();
              }
          }
      });
  }
```

where `result` is a [`WritableArray`](https://www.google.com/search?client=ubuntu&channel=fs&q=react+native+WritableArray&ie=utf-8&oe=utf-8), a type that facebook create to send data through the bridge

**Comment by orihero** [comment]
I tried Writable array as well but the error says ```com.facebook.react.bridge.ReadableNativeMap cannot be cast to java.lang.string```

**Comment by fabriziobertoglio1987** [comment]
because 

```
 result.pushString(ratio.toString());
```

is converting `ratio.toString()`. You can not convert `.toString()` all data types

I am just giving you a heads up, I'm unsubscribing from this thread as there is no bug in react-native to fix for me 

You just need to get into `react-native` development more gradually.. my first feature was for `react-native-camera` ... you can try to write a pull request to their repo and ask their assistance .. they will help you to write a pull request

here we have 800 open issues so you will not receive attention, but can exchange some knowledge in exchange of help on other repositories of react-native-community

this way you get assistance on how to write native ui components etc...

**Comment by orihero** [comment]
I assume that it is specific to the version of react-native because the same code I wrote in my previous project is working!

**Comment by orihero** [comment]
> react native uses special types `ReadableNativeMap` to cast the result of the promise from the Java JSON/Array format to Javascript JSON format
> 
> check this [example](https://github.com/react-native-community/react-native-camera/blob/master/android/src/main/java/org/reactnative/camera/CameraModule.java#L327-L352) on how to use the bridge ... or review the code from the react-native repository to see how they use the bridge
> 
> Obviously `promise.resolve("value")` is wrong
> 
> should be something like
> 
> ```java
>   @ReactMethod
>   public void getSupportedRatios(final int viewTag, final Promise promise) {
>       final ReactApplicationContext context = getReactApplicationContext();
>       UIManagerModule uiManager = context.getNativeModule(UIManagerModule.class);
>       uiManager.addUIBlock(new UIBlock() {
>           @Override
>           public void execute(NativeViewHierarchyManager nativeViewHierarchyManager) {
>               final RNCameraView cameraView;
>               try {
>                   cameraView = (RNCameraView) nativeViewHierarchyManager.resolveView(viewTag);
>                   WritableArray result = Arguments.createArray();
>                   if (cameraView.isCameraOpened()) {
>                       Set<AspectRatio> ratios = cameraView.getSupportedAspectRatios();
>                       for (AspectRatio ratio : ratios) {
>                           result.pushString(ratio.toString());
>                       }
>                       promise.resolve(result);
>                   } else {
>                       promise.reject("E_CAMERA_UNAVAILABLE", "Camera is not running");
>                   }
>               } catch (Exception e) {
>                   e.printStackTrace();
>               }
>           }
>       });
>   }
> ```
> 
> where `result` is a [`WritableArray`](https://www.google.com/search?client=ubuntu&channel=fs&q=react+native+WritableArray&ie=utf-8&oe=utf-8), a type that facebook create to send data through the bridge

First of all you can resolve a promise with `String` since argument to the `resolve` method is `Object`:
