### ISSUE TITLE
Infinite loop in console after enabling MessageQueue.spy

### ISSUE THREAD

**Issue by mrbrentkelly** [facebook/react-native#28970]
## Description

Setting `MessageQueue.spy(true)` causes an infinite loop of console logs and a RedBox error `'Exception in HostFunction: Malformed Calls from JS'`.

Related: https://github.com/facebook/react-native/issues/27027

## React Native version:

**0.62.2**

```
System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 7.28 GB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.16.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /Users/brent.kelly/.rvm/gems/ruby-2.6.3/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 26, 27, 28, 29
      Build Tools: 28.0.2, 28.0.3, 29.0.0, 29.0.1, 29.0.2, 29.0.3
      System Images: android-21 | Intel x86 Atom_64, android-22 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64, android-24 | ARM 64 v8a, android-25 | Intel x86 Atom_64, android-27 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6308749
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_201 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce

1. `npx react-native init InfiniteLoop`
2. open `index.js` and add...

```JavaScript
import MessageQueue from 'react-native/Libraries/BatchedBridge/MessageQueue';
MessageQueue.spy(true);
```

3. `yarn android`

## Expected Results

Console should log `TO_JS` and `TO_NATIVE` traffic on the bridge.

## Snack, code example, screenshot, or link to a repository:

<img width="250" alt="Screenshot 2020-05-25 at 23 24 23" src="https://user-images.githubusercontent.com/5814579/82846049-e6c7bf00-9ede-11ea-9640-a5b1c5103b97.png">

**Comment by mrbrentkelly** [comment]
Debugged this a bit today. 

The `enqueueNativeCall` function in [MessageQueue.js](https://github.com/facebook/react-native/blob/master/Libraries/BatchedBridge/MessageQueue.js#L236) is getting called over and over by the `'send'` method from `WebSocketModule`. I'm not sure if this is expected or not? 

If it is expected then we should perhaps suppress logging traffic from WebSocketModule by default (since there is just so much of it and it never ends)?

Would just need to update this block:

https://github.com/facebook/react-native/blob/21186034af265c093901c8b37497b600e97e4740/Libraries/BatchedBridge/MessageQueue.js#L321-L328

With something like:

```diff
if (__DEV__ && this.__spy && isFinite(moduleID)) {
+  const moduleName = this._remoteModuleTable[moduleID];
+  if (moduleName !== 'WebSocketModule') {
        this.__spy({
          type: TO_NATIVE,
          module: this._remoteModuleTable[moduleID],
          method: this._remoteMethodTable[moduleID][methodID],
          args: params,
        });
+  }
}
```

**For anyone needing this behavior now you can do the following workaround when spying on the MessageQueue...**

```TypeScript
import MessageQueue from 'react-native/Libraries/BatchedBridge/MessageQueue';

MessageQueue.spy((data) => {
  // Ignore logs from WebSocketModule 
  if (data.module === 'WebSocketModule') {
    return;
  }

  console.log(data);
});
```

**Comment by shixinzhang** [comment]
> Debugged this a bit today.
> 
> The `enqueueNativeCall` function in [MessageQueue.js](https://github.com/facebook/react-native/blob/master/Libraries/BatchedBridge/MessageQueue.js#L236) is getting called over and over by the `'send'` method from `WebSocketModule`. I'm not sure if this is expected or not?
> 
> If it is expected then we should perhaps suppress logging traffic from WebSocketModule by default (since there is just so much of it and it never ends)?
> 
> Would just need to update this block:
> 
> https://github.com/facebook/react-native/blob/21186034af265c093901c8b37497b600e97e4740/Libraries/BatchedBridge/MessageQueue.js#L321-L328
> 
> With something like:
> 
> ```diff
> if (__DEV__ && this.__spy && isFinite(moduleID)) {
> +  const moduleName = this._remoteModuleTable[moduleID];
> +  if (moduleName !== 'WebSocketModule') {
>         this.__spy({
>           type: TO_NATIVE,
>           module: this._remoteModuleTable[moduleID],
>           method: this._remoteMethodTable[moduleID][methodID],
>           args: params,
>         });
> +  }
> }
> ```
> 
> **For anyone needing this behavior now you can do the following workaround when spying on the MessageQueue...**
> 
> ```ts
> import MessageQueue from 'react-native/Libraries/BatchedBridge/MessageQueue';
> 
> MessageQueue.spy((data) => {
>   // Ignore logs from WebSocketModule 
>   if (data.module === 'WebSocketModule') {
>     return;
>   }
> 
>   console.log(data);
> });
> ```

Thanks for the workaround, save my day.
