### ISSUE TITLE
run-android starts wrong activity

### ISSUE THREAD

**Issue by zirmax** [facebook/react-native#28972]
## Description
I am trying to move an existing android app which uses native c code to react-native. I managed to build everything but on start it starts the wrong activity:

```
BUILD SUCCESSFUL in 15s
52 actionable tasks: 14 executed, 38 up-to-date
info Connecting to the development server...
info Starting the app on "emulator-5554"...
Starting: Intent { cmp=ch.ethz.asl.agast/.MainActivity }
Error type 3
Error: Activity class {ch.ethz.asl.agast/ch.ethz.asl.agast.MainActivity} does not exist.
```

The MainActivity it tries to start is of a git submodule.

It starts fine in android studio.

## React Native version:
```
System:
    OS: Linux 5.3 Linux Mint 19.3 (Tricia)
    CPU: (12) x64 AMD Ryzen 5 2600 Six-Core Processor
    Memory: 158.54 MB / 15.63 GB
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 10.17.0 - /tmp/yarn--1590473861444-0.3285895976764093/node
    Yarn: 1.22.4 - /tmp/yarn--1590473861444-0.3285895976764093/yarn
    npm: 6.11.3 - /usr/local/lib/nodejs/node-v10.17.0-linux-x64/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: Not Found
    Python: 2.7.17 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. `git clone git@github.com:zirmax/RtkGps.git`
2. `cd <DIR> `
3. `git submodule update --init --recursive`
4. `yarn install`
5. `yarn android`

## Expected Results
It should start `gpsplus.rtkgps.MainActivity`.

## Snack, code example, screenshot, or link to a repository:
My repo: https://github.com/zirmax/RtkGps

**Comment by fabriziobertoglio1987** [comment]
```bash
./gradlew :app:installDebug --daemon
adb shell am start -n 'com.example.myapplication/com.example.myapplication.MainActivity' -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
```

just replace in the `adb shell` command `'com.example.myapplication/com.example.myapplication.MainActivity'` with your activity

you save this is a `script` in your `$PATH` and use it instead of `react-native run-android`. I bind this to a shortcut.

**Comment by zirmax** [comment]
> ```shell
> ./gradlew :app:installDebug --daemon
> adb shell am start -n 'com.example.myapplication/com.example.myapplication.MainActivity' -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
> ```
> 
> just replace in the `adb shell` command `'com.example.myapplication/com.example.myapplication.MainActivity'` with your activity
> 
> you save this is a `script` in your `$PATH` and use it instead of `react-native run-android`. I bind this to a shortcut.

Thanks, that worked :)
