### ISSUE TITLE
Android EdgeEffect Color In ScrollViews And FlatLists

### ISSUE THREAD

**Issue by jack-coder-25** [facebook/react-native#28973]
## Android EdgeEffect

Hello Everyone,

I am trying to figure out how can we have edge effect which we get when there is no more
content to scroll like in other android apps.

React native by default provides white effect which i don't want i want to implement
my own color

![image](https://user-images.githubusercontent.com/63912668/82870104-0990bc80-9f4d-11ea-9e1f-fe9e4a4c1385.png)

Picture Is Not Mine

Info

System:
    OS: Windows 10 10.0.18362
    CPU: (2) x64 Intel(R) Core(TM)2 Duo CPU     E7400  @ 2.80GHz
    Memory: 1.62 GB / 4.00 GB
  Binaries:
    Node: 12.16.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5791312
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
  npmGlobalPackages:
    react-native-cli: 2.0.1

**Comment by troZee** [comment]
Put this inside android/app/src/res/values/styles.xml
```xml
<item name="android:colorEdgeEffect">#E53644</item>
```
