### ISSUE TITLE
Android TV: Flatlist Items with TouchableOpacity all get focussed in Modal & TVEventHandler not logging any events.

### ISSUE THREAD

**Issue by prashantchothani** [facebook/react-native#28980]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
While making an App for Android TV, in a Component, the TVEventHandler is getting initialised and events are being logged in the console. In the Component there is a Button and Flatlist and the both the Button and Flatlist items which have TouchableOpacity are getting focussed on D Pad but if we move the same components to Modal in the same Component, all the items onfocus events are triggered. Also the TVEventHandler is not logging in th console the events while using D Pad.

## React Native version:
System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 4.22 GB / 15.86 GB
  Binaries:
    Node: 12.2.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 22, 23, 24, 25, 26, 27, 28, 29
      Build Tools: 28.0.3, 30.0.0
      System Images: android-24 | Android TV Intel x86 Atom, android-28 | Android TV Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-Q | Android TV Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6392135
  Languages:
    Java: 1.8.0_211
    Python: 2.7.16
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Use a Component with Flatlist with Items having TouchableOpacity and a TouchableOpacity encapsulated button.
2. Initialise the TVEventHandler to log in console the D Pad events.
3. The console will log properly the events and focus will also move correctly.
4. Now shift the components in Modal within the same Component.
5. No TVEventHandler events will be logged in the console and all items of the Flatlist will trigger onfocus events. On D Pad being used, no onfocus events are triggered and focus does not move.

## Expected Results
In the Modal too, the behaviour should have been identical what we get without a Modal

## Snack, code example, screenshot, or link to a repository:
Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by prashantchothani** [comment]
Fixed as of noy

**Comment by safeandroidtv** [comment]
> Fixed as of noy

Hi, how did you deside this problem? I am currently experiencing this problem on Android TV.
