### ISSUE TITLE
How add .aar file into React Native project and how to call lib methods

### ISSUE THREAD

**Issue by pedroenrre** [facebook/react-native#28981]
I hava created the folder 'libs' into /android/app/.

Then, on app/build.gradlew I added:
  implementation fileTree(dir: "libs", include: ["*.aar"])

The compilation works fine. I have no errors on it.

My Question is: How do I call the methods from the lib I put on folder 'libs'.

I have tried to use NativeModules. But it did not work.

Do I have to do someting else?

**Comment by fabriziobertoglio1987** [comment]
https://github.com/react-native-community/react-native-camera/pull/2834/files

close

**Comment by busterbogheart** [comment]
@pedroenrre Did you solve this?
