### ISSUE TITLE
Click Run in Xcode 7 won't automatically open terminal and run node

### ISSUE THREAD

**Issue by kevinzzz007** [facebook/react-native#2899]
When I click "run" in Xcode 7, Xcode won't automatically open terminal and run node, instead I have to cd to the app directory and run "npm start" manually, is this an issue only for Xcode 7?  Thanks!

**Comment by grabbou** [comment]
Can confirm this happens on Xcode 7 only (same build works on Xcode 6 flawlessly)

**Comment by grabbou** [comment]
Well, in my case it was because of CocoaPods. I believe this could've been mentioned in the docs. Anyway, add his `Run Script` to your build phases just before `Link binary with files`:

```
if nc -w 5 -z localhost 8081 ; then
  if ! curl -s "http://localhost:8081/status" | grep -q "packager-status:running" ; then
  echo "Port 8081 already in use, packager is either not running or not running correctly"
  exit 2
fi
else
  open $SRCROOT/node_modules/react-native/packager/launchPackager.command || echo "Can't start packager automatically"
fi
```

**Comment by kevinzzz007** [comment]
Umm, I added that, but the terminal still didn't launch...

**Comment by bcharp** [comment]
I replaced 
```
open $SRCROOT/node_modules/react-native/packager/launchPackager.command || echo "Can't start packager automatically"
```

with

```
open -a Terminal $SRCROOT/../node_modules/react-native/packager/packager.sh
```

And it works

**Comment by kevinzzz007** [comment]
@bcharp @grabbou thanks so much for the help!  So I found that if you have a folder name with a space in it, e.g.`Weekly projects`, then Xcode can't seem to find the `packager.sh` or the `launchPackager.command` files, but if you take away the space and make sure all folder names in this line-`/Users/YourUsername/Desktop/WeeklyProjects/ProjectName/node_modules/react-native/packager/launchPackager.command`-don't have spaces, the terminal will launch perfectly!  @brentvatne @ide is this something we can fix so that even if you have spaces in folder names the terminal will still launch?

**Comment by grabbou** [comment]
I guess it's probably because it needs to be escaped. I think I've been mentioning that bug in another issue quite a few weeks ago.
