### ISSUE TITLE
Error : "useEffect is read only"

### ISSUE THREAD

**Issue by kg-kartik** [facebook/react-native#28996]
## Description
I am running an asynchronous function in useEffect hook , but it returns error that useEffect is read only, although it should run perfectly.

## React Native version:
 react-native: 0.62.2 => 0.62.2

## Steps To Reproduce
1. The below code doesnt work.

`
import React, {useEffect} from "react"
import AsyncStorage from '@react-native-community/async-storage';

import {
    Text,
} from "react-native"

const Home = ({navigation}) => {

    useEffect = (() => {
        const detectLogin = async () => {
            const token = await AsyncStorage.getItem('token');
            console.log(token);
            if(token) {
                navigation.replace("profile");
            }
            else {
                navigation.replace("login");
            }
        }
        detectLogin();
    },[])

    return (
         <Text> Arbitary Text </Text>
    )
}
`

## Expected Results
Expected to replace the screen successfully based upon the condition in the code.

## Snack, code example, screenshot, or link to a repository:
Screenshot of error : 
![image](https://user-images.githubusercontent.com/24389474/83128679-603af980-a0f9-11ea-9640-d62549ab4e95.png)

**Comment by Sushant-Sardeshpande** [comment]
It is readonly, you would have to call it as:
useEffect(() => {
    const detectLogin = async () => {
        const token = await AsyncStorage.getItem('token');
        console.log(token);
        if(token) {
            navigation.replace("profile");
        }
        else {
            navigation.replace("login");
        }
    }
    detectLogin();
},[])

**Comment by kg-kartik** [comment]
Oh...Thanks a lot!
