### ISSUE TITLE
border top/left/bottom/right width not working

### ISSUE THREAD

**Issue by jlongster** [facebook/react-native#29]
I have this in my render method:

```js
    return View(
      { style: { flex: 1 } },
      TouchableWithoutFeedback(
        { onPress: this.handlePress },
        View({
          style: {
            flex: 0,
            backgroundColor: 'gray',
            height: 50,
            alignItems: 'center',
            justifyContent: 'center',
            borderWidth: 1,
            borderColor: 'white'
          },
        }, Text({ style: { color: 'white' }}, "^"))
      ),
      TouchableWithoutFeedback(
        { onPress: this.handlePress },
        View({
          style: {
            flex: 0,
            backgroundColor: 'gray',
            height: 50,
            alignItems: 'center',
            justifyContent: 'center'
          },
        }, Text({ style: { color: 'white' }}, "v"))
      )
    )
```

It renders this:

![screen shot 2015-02-02 at 9 43 33 am](https://cloud.githubusercontent.com/assets/17031/6002312/3e63f120-aac0-11e4-8e62-102988736bb1.png)

But if I change the `borderWidth` in the first component to `borderBottomWidth` or any of the other top/left/bottom/right methods, there is no border. There should be a white border on one side of the component:

![screen shot 2015-02-02 at 9 43 40 am](https://cloud.githubusercontent.com/assets/17031/6002325/5c05afe8-aac0-11e4-9430-4ecf46812635.png)

**Comment by vjeux** [comment]
Should be working now

**Comment by janmonschke** [comment]
It's not yet working for me (on 0.4.0)

**Comment by janmonschke** [comment]
Argh, nevermind, Apparently it is not activated for `<Text />` nodes and I'm now wrapping a `<View />` around them.

**Comment by grabbou** [comment]
Not working on 0.5.0. TextInput does not use border<Whatever>Width, only borderWidth works.

**Comment by axelg12** [comment]
Can confirm that this works in 0.8.0 for ```<View />```

But is there a reason why it doesn't support ```<Text />```

**Comment by mikefrancis** [comment]
+1 for `<Text />` support

**Comment by JeanLebrument** [comment]
:+1: I need this for `<TextInput />`

**Comment by ilansas** [comment]
+1 for `<TextInput />`

**Comment by elisei-timofte** [comment]
+1 for <Text>

**Comment by AlexGustafsson** [comment]
Any news on support for <Text /> support?

**Comment by chinloong91** [comment]
+1 for <TextInput /> as well

**Comment by vjeux** [comment]
Can you add it to https://productpains.com/product/react-native/ so that we can figure out prioritization?

**Comment by elisei-timofte** [comment]
sure. thanks

**Comment by mhollweck** [comment]
fyi: https://productpains.com/post/react-native/add-borderwidth-left-right-top-bottom-to-textinput-/

**Comment by leeight** [comment]
+1

**Comment by rclai** [comment]
@ide, you guys don't have labels for this type of issue?

**Comment by akshaysmurthy** [comment]
Definitely need it for `<TextInput />`

**Comment by jorilallo** [comment]
+1 on `<TextInput />`

**Comment by flCer** [comment]
+1 `<TextInput />`

**Comment by Overload119** [comment]
+1 `<TextInput />`, Googling brought me to this issue.

**Comment by zires** [comment]
+1 `<TextInput />`

**Comment by claytongulick** [comment]
Ugh, spent hours banging my head against the wall trying to figure this out before I found this... +1 gajillion to make this work everywhere the docs say it should, like TextInput...

**Comment by keeganmccallum** [comment]
+1 for TextInput

**Comment by rclai** [comment]
Guys, make sure that you're voting it up in here: https://productpains.com/post/react-native/add-borderwidth-left-right-top-bottom-to-textinput-/

**Comment by vjeux** [comment]
Also, this is not a controversial feature. A pull request would be much more impactful :)

**Comment by rclai** [comment]
A workaround is to wrap your `TextInput` or `Text` in a `View` and apply the borders on the `View`.

**Comment by voidvoxel** [comment]
:+1:  for <TextInput />

**Comment by prometheansacrifice** [comment]
@rclai. Thanks for the workaround

**Comment by magrinj** [comment]
:+1: `TextInput` :) 
Up also here guys: https://productpains.com/post/react-native/add-borderwidth-left-right-top-bottom-to-textinput-/

**Comment by zhaotai** [comment]
Hi, although I can use <View> to wrap the <TextInput> and <Text> to support borderLeft/Right..., I still need them. I don't want to wrap too many <View>s to hack.

My react-native version is 0.24.1

**Comment by DenisIzmaylov** [comment]
It seems still doesn't working properly, have a look at the first item:

![image](https://cloud.githubusercontent.com/assets/1690596/16089938/0aeea09c-3336-11e6-9455-c7086ff49276.png)

```
  return (
    <View style={[styles.eventInRoom, { borderLeftColor: roomColor }, styles.feedEventContainer]}>
      <View style={styles.feedEventContent}>
```

Which has the following styles:
```
  feedEventContainer: {
    margin: 10,
    marginBottom: 5,
    borderRadius: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: .3,
    shadowRadius: 1.3,
    backgroundColor: '#ffe',
  },
  eventInRoom: {
    borderLeftWidth: 3,
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
  },
```

**Comment by ospfranco** [comment]
Hey, how about <Image> Support, this doesn't seem to be working on it

**Comment by nicolasduranl** [comment]
+1 for `<TextInput />`, also upvoted in productpain (Y)

**Comment by arthurkushman** [comment]
There is no pain guys - all will work with <View> wrapping any <Text>, <TextInput>, <Touchable...>

**Comment by lukescott** [comment]
`<View>` wrapping is painful. It makes styling a pain. Especially with error states. 1 field = 4 independent styles.

**Comment by grundmanise** [comment]
+1 for `Textinput`

**Comment by gotoAndBliss** [comment]
+1 for `TextInput`..

In the meantime, anyone know a best practice for wrapping a `<TextInput />` in a `<View/>` . This seems to be trickier than I thought.

**Comment by rushg** [comment]
+1 for `Text`

**Comment by alexhhn** [comment]
+1 for Text and TextInput

**Comment by Naoto-Ida** [comment]
+1 for what? TextInput 😙

**Comment by mycool0943** [comment]
+1 for TextInput

**Comment by tested01** [comment]
+1 <TextInput />

**Comment by aaroncrawford** [comment]
+1 for TextInput

**Comment by Rebsos** [comment]
+1 Text

**Comment by narayananramu** [comment]
+1 for TextInput

**Comment by rileytg** [comment]
+1 for TextInput support, sooo many views for layout already :(

**Comment by IOriens** [comment]
+1 for Text

**Comment by hfigueira** [comment]
+1 for TextInput (Pleeeeeease!)

**Comment by herarya** [comment]
+1 for TextInput

**Comment by Chatharaju** [comment]
+1 for TextInput

**Comment by GetSource1234** [comment]
+1 for TextInput and View (RN 0.44)

**Comment by lako90** [comment]
i opened a request here https://react-native.canny.io/feature-requests/p/add-borderleft-right-top-bottomwidth-to-textinput--on-ios

please vote it =)

**Comment by markusguenther** [comment]
+1 for Text

**Comment by hramos** [comment]
There's way too many +1 comments in this thread, considering the issue was closed a long time ago. If you feel strongly about this being added to TextInput, please send a PR or upvote the entry on Canny: https://react-native.canny.io/feature-requests/p/add-borderwidth-left-right-top-bottom-to-textinput-

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
