### ISSUE TITLE
Non-portable path to file Target Support Files/Yoga/Yoga-prefix.pch

### ISSUE THREAD

**Issue by rajeshsmallarc** [facebook/react-native#29008]
## Error
/<built-in>:1:10: Non-portable path to file '"/mysystempath/mytest/ios/Pods/Target Support Files/Yoga/Yoga-prefix.pch"'; specified path differs in case from file name on disk

## Description
I have tried with existing projects  and created new test project but the below error same for all the projects.

## React Native version:
System:
    OS: macOS 10.15.2
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Memory: 1.31 GB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.17.0 - /usr/local/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-28 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5977832
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
    react-native-rename: 2.3.1

**Comment by sarath-pits** [comment]
Hi,
Do you had any solution on this ?
I am also facing the same issue .

**Comment by rajeshsmallarc** [comment]
@sarath-pits After searching everywhere in web I was unable to find a solution. Then I formatted my system. Installed OS again. Now everything working fine.

**Comment by russelRajitha** [comment]
still have the issue. is there any solution?
