### ISSUE TITLE
Error with recoil. recoil atom is not a function

### ISSUE THREAD

**Issue by hackemateninja** [facebook/react-native#29005]
I have been tested recoil on a react native app and get an error

## Description
when I try to implements recoil with react native CLI app got me this error:

```
TypeError: {0._recoil.atom} is not a function. '(0,_recoil.atom)({
  key: 'textState',
  default: 'initial value'
})','(0,_recoil.atom)' is undefined)
```

## React Native version:
System:
    OS: Linux 4.19 Manjaro Linux
    CPU: (4) x64 Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
    Memory: 923.70 MB / 15.42 GB
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.2 - ~/.nvm/versions/node/v12.14.1/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 11.0.7 - /usr/lib/jvm/default/bin/javac
    Python: 3.6.5 - /usr/local/anaconda/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce

1. npx react-native init recoil
2. npx react-native start
3. yarn add recoil
4. npx react-native run-android

## Expected Results
I need to run correctly to manage the state

## Snack, code example, screenshot, or link to a repository:

```
import React from 'react';
import {RecoilRoot, useRecoilValue, atom} from 'recoil';
import {View, Text} from 'react-native';

export const textState = atom({
  key: 'textState',
  default: 'initial value',
});

const RecoilTest = () => {
  const fontSizeLabel = useRecoilValue(textState);
  return (
    <View>
      <Text>{fontSizeLabel}</Text>
    </View>
  );
};

const App = () => {
  return (
    <RecoilRoot>
      <RecoilTest />
    </RecoilRoot>
  );
};


export default App;
```

**Comment by todorone** [comment]
@hackemateninja Recoil does not support RN yet, but PR is already in progress.
https://github.com/facebookexperimental/Recoil/issues/99
