### ISSUE TITLE
React native progurad file --keep Okhttp 

### ISSUE THREAD

**Issue by lalchand92** [facebook/react-native#29016]
React native proguard file keep okhttp in consumerProguardFiles. Which gets merge with application proguard file and hence okhttp code doesn't get obfusticate in application Dex. 

Existing configuration:
https://github.com/facebook/react-native/blob/master/ReactAndroid/proguard-rules.pro

-keepattributes Signature
-keepattributes *Annotation*
-keep class okhttp3.** { *; }
-keep interface okhttp3.** { *; }
-dontwarn okhttp3.**

Okhttp has update it with new configuration: 
  
-dontwarn javax.annotation.**
-keepnames class okhttp3.internal.publicsuffix.PublicSuffixDatabase
-dontwarn org.codehaus.mojo.animal_sniffer.*
-dontwarn okhttp3.internal.platform.ConscryptPlatform

If it's update with new configuration then okhttp code in application will get obfusticate. Any idea/plan to do it? or any other workaround for the same?

**Comment by doniwinata0309** [comment]
any plan to remove okhttp rules from react native side ?
actually this can saving some amount of code and reduce the apk size. 
They mentioned here that the consumer proguard will handle it.
https://square.github.io/okhttp/r8_proguard/
