### ISSUE TITLE
Some Android models have a 1 pixel gap in the relative layout.

### ISSUE THREAD

**Issue by ryanypm** [facebook/react-native#29010]
## Description
Some Android models have a 1 pixel gap in the relative layout.

Renderings:
![image](https://user-images.githubusercontent.com/7519919/83325149-cc099780-a29c-11ea-85b9-3004d8e3f358.png)

![bbb](https://user-images.githubusercontent.com/7519919/83325340-3a9b2500-a29e-11ea-9e62-5f3e102d04d7.jpg)

## React Native version:
```
System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 110.71 MB / 8.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.16.3 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.4 - ~/n/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  Languages:
    Java: 13.0.1 - /usr/bin/javac
    Python: 2.7.10 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: ^0.62.2 => 0.62.2 
```

## Steps To Reproduce
The first installation or Multiple restarts

## Expected Results
No spacing

## Snack, code example, screenshot, or link to a repository:

This is my test layout structure:
````
<View style={{ width: 414, backgroundColor: 'green', flexWrap: 'wrap', flexDirection: 'row' }}>
      <View style={{ width: 207,  height: 120, backgroundColor: 'red' }}></View>
      <View style={{ width: 207,  height: 120,  backgroundColor: 'red' }}></View>
      <View style={{ width: 207,  height: 124,  backgroundColor: 'red' }}></View>
      <View style={{ width: 207,  height: 124,  backgroundColor: 'red' }}></View>
      <View style={{ width: 207,  height: 100,  backgroundColor: 'red' }}></View>
      <View style={{ width: 207,  height: 100,  backgroundColor: 'red' }}></View>
</View>
````

Similar problems:
#28076

**Comment by ryanypm** [comment]
#28076

**Comment by chenqizheng** [comment]
Because Android does not support the width and height of decimals, but yoga is supported.

### Solution:

1. Listen onLayout function, get a Real size and setNativeProps

2. set Safe Height
```
function dpiSafeHeight (height) {
    const dpi = PixelRatio.get();
    const px = height * dpi;
    const int_px = Math.round(px);
    const diff = int_px - px;
    return height + (diff / dpi);
}
```

**Comment by fabriziobertoglio1987** [comment]
@chenqizheng you are writing a pull request for this :smiley: ?

**Comment by ryanypm** [comment]
> Because Android does not support the width and height of Float, but yoga is supported.
> 
> ### Solution:
> 1. Listen onLayout function, get a Real size and setNativeProps
> 2. set Safe Height
> 
> ```
> function dpiSafeHeight (height) {
>     const dpi = PixelRatio.get();
>     const px = height * dpi;
>     const int_px = Math.round(px);
>     const diff = int_px - px;
>     return height + (diff / dpi);
> }
> ```
