### ISSUE TITLE
[android] Paste into TextInput blocks UI for few seconds

### ISSUE THREAD

**Issue by ggunti** [facebook/react-native#29026]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
I copy some little bit longer text from 'Facebook Messenger' app. Then, I paste this text into my TextInput component in my app. It works. After that, I want to edit the pasted text, but the problem is that always when I type a new character into the TextInput, the UI blocks for few seconds.

The device is a Samsung Galaxy S5, running android 6.0. Please check the video below:
https://www.kapwing.com/videos/5ed54f6b6c43020015f4277d

## React Native version:
Run `react-native info` in your terminal and copy the results here.
```
System:
    OS: macOS 10.15.2
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 221.81 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.16.3 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.4 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 23.0.1, 26.0.2, 27.0.3, 28.0.3
      System Images: android-27 | Google Play Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_201 - /usr/bin/javac
    Python: 2.7.16 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
```

## Steps To Reproduce
<details>
<summary>1. Copy below hidden text and paste it into the TextInput component</summary>
Let's consider the $$(a_n)$$ and $$(b_n)$$ sequences such that:
i) $$0<b_1<b_2<...<b_n<b_{n+1}<\cdots$$ and $$\lim_{n\rightarrow\infty}{b_n}=+\infty;$$
ii) $$\exists \lim_{n\rightarrow\infty}{\frac{a_{n+1}-a_n}{b_{n+1}-b_n}}:=l\in\overline{\mathbb{R}}.$$

Then, $$\exists \lim_{n\rightarrow\infty}{\frac{a_n}{b_n}}$$ and $$\lim_{n\rightarrow\infty}{\frac{a_n}{b_n}} = l.$$

Proof.

Let's consider $$l\in\mathbb{R}$$.
Because of ii), for any fixed $$\varepsilon>0$$ exists $$n_\varepsilon\in\mathbb{N}$$ such that $$\left|{\frac{a_{n+1}-a_n}{b_{n+1}-b_n}-l}\right|<\frac{\varepsilon}{3}$$, $$\forall n>n_\varepsilon$$, so $$\left(b_{n+1}-b_n\right)\left(l-\frac{\varepsilon}{3}\right) < a_{n+1}-a_n<\left(b_{n+1}-b_n\right)\left(l+\frac{\varepsilon}{3}\right).$$...(*)

Let's write down the (*) inequalities for $$n=n_{\varepsilon}+1,...,n_{\varepsilon}+p-1$$ and sum up the corresponding sides. Then, we obtain the
$$\left(b_{n_{\varepsilon}+p}-b_{n_{\varepsilon}+1}\right)\left(l-\frac{\varepsilon}{3}\right)<a_{n_{\varepsilon}+p}-a_{n_{\varepsilon}+1}<\left(b_{n_{\varepsilon}+p}-b_{n_{\varepsilon}+1}\right)\left(l+\frac{\varepsilon}{3}\right)$$ inequalities, from which follows that:
$$l-\frac{\varepsilon}{3}-\left(l-\frac{\varepsilon}{3}\right)\frac{b_{n_{\varepsilon}+1}}{b_{n_{\varepsilon}+p}}+\frac{a_{n_{\varepsilon}+1}}{b_{n_{\varepsilon}+p}}<\frac{a_{n_{\varepsilon}+p}}{b_{n_{\varepsilon}+p}}<$$$$l+\frac{\varepsilon}{3}-\left(l+\frac{\varepsilon}{3}\right)\frac{b_{n_{\varepsilon}+1}}{b_{n_{\varepsilon}+p}}+\frac{a_{n_{\varepsilon}+1}}{b_{n_{\varepsilon}+p}}
</details>

2. Type other characters into the TextInput.

3. For each newly typed character, the UI will be blocked for few seconds.

## Expected Results
After text was pasted, I should be able to type in new characters without always blocking the UI for few seconds.

## Snack, code example, screenshot, or link to a repository:
Just add the following code in your `App.tsx` file:
```
import React, { Component } from 'react';
import { TextInput } from 'react-native';

export default class App extends Component<{}> {
  state = {
    text: '',
  };

  render() {
    return (
      <TextInput
        style={{ fontSize: 16, paddingHorizontal: 10 }}
        placeholder='Content of your post'
        underlineColorAndroid='rgba(0, 0, 0, 0.5)'
        multiline={true}
        showSoftInputOnFocus={true} // available only on android
        value={this.state.text}
        onChangeText={(text: string) => this.setState({ text })}
      />
    );
  }
}
```

**Comment by fabriziobertoglio1987** [comment]
You experience this when copying text only from messanger or from any other app?
By the way, I tested copy and paste with your example on android api 28 emulator and works just fine (without using facebook)

**Comment by fabriziobertoglio1987** [comment]
could you better explain step 1) ? thanks

**Comment by ggunti** [comment]
I tried again to do exactly the same steps that I did in the video and... now everything works as it should (no UI block anymore). That's extremely strange, I have no idea what's going on.
