### ISSUE TITLE
Vulnerability found with libjpeg-turbo 1.5.3 used internally by react-native

### ISSUE THREAD

**Issue by pawan4444** [facebook/react-native#29029]
Hi,
I found vulnerability with older version of libjpeg-turbo 1.5.3, could you please look into it.
Here is the screenshot 
<img width="990" alt="Screenshot 2020-06-02 at 5 42 30 PM" src="https://user-images.githubusercontent.com/777503/83518741-73ced180-a4f8-11ea-93e5-0f91a140e1b2.png">

**Comment by pawan4444** [comment]
warn The following packages use deprecated "rnpm" config that will stop working from next release:
  - react-native-extra-dimensions-android: https://npmjs.com/package/react-native-extra-dimensions-android
Please notify their maintainers about it. You can find more details at https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide.
info Fetching system and libraries information...
System:
    OS: macOS 10.15.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 27.75 MB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.2 => 0.61.2 
  npmGlobalPackages:
    create-react-native-module: 0.11.1
    react-native-cli: 2.0.1

**Comment by verareddy17** [comment]
we have been facing same issue even latest version react-native 0.63 as well. i am requesting react-native peoples to look into it and update there its version.

**Comment by M9lab** [comment]
Same here!

**Comment by KFrysztak** [comment]
any update on this one?
