### ISSUE TITLE
[Question] How to make a partially opened FormSheet/PageSheet Modal

### ISSUE THREAD

**Issue by mrousavy** [facebook/react-native#29030]
## Description

First off, I'm sorry for posting this here, I couldn't find any documentation on this and found no existing questions/answers.

I'm trying to create a 3 stage form sheet/page sheet modal dialog, just like the iOS Share Sheet. Is that possible with React Native?

<table>
<tr>
<th>Closed</th>
<th>Partially opened</th>
<th>Fully opened</th>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/15199031/83522193-9e149500-a4e0-11ea-9a9b-f31533ded6fe.png"/> </td>
<td><img src="https://user-images.githubusercontent.com/15199031/83522233-abca1a80-a4e0-11ea-92bd-6cc117d2ea7f.png"/> </td>
<td><img src="https://user-images.githubusercontent.com/15199031/83522237-ae2c7480-a4e0-11ea-851a-dc938b31e25f.png"/> </td>
</tr>
</table>

## Code

My code now:

```jsx
<Modal
  presentationStyle="pageSheet"
  visible={this.state.modalShown}
  hardwareAccelerated={true}
  animationType="slide"
```

Using this I can only fully close or fully open it, no way to partially open it. I've tried using the `top` property, but that produces weird results and won't let the user drag it up to fully open it (like the native Share Sheet)

## React Native version:

> because apparently it's required.

```
info Fetching system and libraries information...
System:
    OS: macOS 10.15.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 8.04 GB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.3.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 25, 28, 29
      Build Tools: 28.0.3, 29.0.3, 30.0.0
      System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_252 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by navi-d97** [comment]
Try this module created by me. It uses animated view instead of modal. 
https://www.npmjs.com/package/react-native-swipeable-bottom-sheet

**Comment by luco** [comment]
You can use a pageSheet presentation style with transparent. Then, style it the height you want.

**Comment by KristineTrona** [comment]
Hey, I am looking for the same feature. The presentationStyle `pageSheet` does not seem to support `transparent` prop.

<img width="276" alt="Screenshot 2020-07-24 at 16 12 28" src="https://user-images.githubusercontent.com/39855778/88400337-7945eb00-cdc8-11ea-9a73-ea5ee1e61ff3.png">

I would like to achieve an effect like:

![WOvTpG3A](https://user-images.githubusercontent.com/39855778/88400524-c7f38500-cdc8-11ea-9d1c-8ef7fb02c566.jpeg)
