### ISSUE TITLE
Wrong (or at least not descriptive) "error Android project not found" msg 

### ISSUE THREAD

**Issue by scarlehoff** [facebook/react-native#29035]
## Description
A badly formatted AndroidManifest file will make `react-native run-android` fail with the following message:
```
error Android project not found. Are you sure this is a React Native project? If your Android files are located in a non-standard lo
cation (e.g. not inside 'android' folder), consider setting `project.android.sourceDir` option to point to a new location
```
It will be very useful to either point to the actual error or just say that it could not run _for some reason_ without giving a wrong reason.

## React Native version:
  Binaries:
    Node: 14.3.0 - /usr/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.14.5 - /usr/bin/npm
    Watchman: 4.9.0 - /usr/bin/watchman
  SDKs:
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3
      System Images: android-29 | Google APIs Intel x86 Atom
  npmPackages:
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    react-native: 0.60.5

## Steps To Reproduce

1. Open `android/app/src/main/AndroidManifest.xml`
2. Add some random mistakes
3. Try to run `react-native run-android`

Great project and thank you very much for your hard work!

**Comment by virtumonde** [comment]
I have the same behavior.

**Comment by amangoelfv** [comment]
any update ?

**Comment by soorajnraju** [comment]
I also faced the same issue

**Comment by HishamMubarak** [comment]
Faced the same issue, got it fixed by running `./gradlew clean` inside android folder.
Worked once, and next time the same issue popped up again, got it fixed by the following step.

> Open your React Native Project Root Directory and locate android -> app -> build -> intermediates -> signing_config -> debug -> out -> signing-config.json. Delete the signing-config.json file and then again GoTo your react native project root directory and run again project using react-native run-android command.  After this your react native project will run successfully.

Source: [https://reactnativecode.com/android-project-not-found/](https://reactnativecode.com/android-project-not-found/)

**Comment by safaiyeh** [comment]
Hi @scarlehoff thank you for the issue!

I've bumped into this too 😅 pretty annoying. This issue board is for issues pertaining to React Native core items. Please file an issue with the CLI repo, they can better address this. Thanks!

https://github.com/react-native-community/cli

**Comment by BenHurMartins** [comment]
Faced same issue, almost rewrote all the project from scratch, thanks.

**Comment by janilamppu** [comment]
Encountered the same message. Had ” instead of " in AndroidManifest.xml. Spent a good while looking until I found this discussion. Thanks!

**Comment by joaorenatojr87** [comment]
> ## Description
> A badly formatted AndroidManifest file will make `react-native run-android` fail with the following message:


Indeed I got lost for a few minutes because of this. Thanks a lot!
