### ISSUE TITLE
React Native version mismatch. JavaScript version: 0.50.4 Native version: 0.61.4

### ISSUE THREAD

**Issue by AdeelShoukatAli** [facebook/react-native#29045]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
I upgraded the old project now getting this error i've search out a lot but no success. 

## React Native version:
System:
    OS: macOS Mojave 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz
    Memory: 42.09 MB / 4.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.16.1 - /usr/local/bin/node
    npm: 6.13.7 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    Android SDK:
      API Levels: 15, 16, 17, 18, 20, 21, 22, 23, 24, 25, 26, 27, 28
      Build Tools: 19.1.0, 22.0.1, 23.0.1, 23.0.2, 24.0.0, 24.0.1, 24.0.2, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.2, 27.0.1, 27.0.2, 27.0.3, 28.0.0, 28.0.2, 28.0.3, 29.0.2
      System Images: android-22 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: /undefined - /usr/bin/xcodebuild
  npmPackages:
    react: ^16.9.0 => 16.13.1 
    react-native: ^0.61.4 => 0.61.4 
  npmGlobalPackages:
    react-native-git-upgrade: 0.2.7
    react-native: 0.62.2

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Running project from Android studio gets crashed just after couple of seconds

## Expected Results
Should run without any bug

## Snack, code example, screenshot, or link to a repository:
com.facebook.react.common.JavascriptException: React Native version mismatch.
    
    JavaScript version: 0.50.4
    Native version: 0.61.4

**Comment by AdeelShoukatAli** [comment]
Package.json
`
{
  "name": "WhoopaUserApp",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "@babel/core": "^7.8.6",
    "@babel/plugin-proposal-class-properties": "^7.10.1",
    "@babel/plugin-transform-runtime": "^7.10.1",
    "@babel/preset-env": "^7.10.2",
    "@babel/preset-react": "^7.10.1",
    "babel-preset-expo": "~8.1.0",
    "babel-preset-react-native-stage-0": "^1.0.1",
    "jest-expo": "^37.0.0",
    "react-native-clean-project": "^3.3.0",
    "react-native-cli": "^2.0.1",
    "react-test-renderer": "16.0.0-alpha.12",
    "redux-logger": "^3.0.6"
  },
  "scripts": {
    "start": "react-native start",
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "test": "node node_modules/jest/bin/jest.js --watch"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "rnpm": {
    "assets": [
      "./src/assets/fonts/"
    ]
  },
  "dependencies": {
    "@sentry/react-native": "^1.4.1",
    "ac-qrcode": "^1.0.1",
    "babel-preset-react-native": "^4.0.1",
    "errno": "^0.1.7",
    "expo": "^37.0.3",
    "fetchival": "^0.3.3",
    "glob": "^7.1.6",
    "immutability-helper": "^2.4.0",
    "jsc-android": "^241213.1.0",
    "metro-react-native-babel-preset": "^0.59.0",
    "normalizr": "^3.2.4",
    "numeral": "^2.0.6",
    "prop-types": "^15.6.0",
    "react": "^16.9.0",
    "react-dom": "^16.9.0",
    "react-native": "^0.61.4",
    "react-native-cached-image": "^1.4.3",
    "react-native-camera": "git+https://git@github.com/react-native-community/react-native-camera.git",
    "react-native-config": "^0.10.0",
    "react-native-easy-toast": "^1.1.0",
    "react-native-fbsdk": "^0.6.3",
    "react-native-fetch-blob": "^0.10.8",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-google-signin": "^0.12.0",
    "react-native-i18n": "^2.0.9",
    "react-native-maps": "0.26.1",
    "react-native-modal": "^4.0.0",
    "react-native-orientation": "^3.1.0",
    "react-native-popup-dialog": "^0.10.43",
    "react-native-progress": "^3.4.0",
    "react-native-reanimated": "~1.7.0",
    "react-native-responsive-dimensions": "^1.0.2",
    "react-native-router-flux": "^4.0.0-beta.24",
    "react-native-screens": "~2.2.0",
    "react-native-scrollable-tab-view": "^0.8.0",
    "react-native-splash-screen": "3.0.6",
    "react-native-swipe-list-view": "^1.0.4",
    "react-native-swipe-out": "^2.0.14",
    "react-native-swipeable": "^0.6.0",
    "react-native-swipeview": "^1.0.3",
    "react-native-swiping-row": "^0.1.2",
    "react-native-update-js": "^1.0.8",
    "react-native-vector-icons": "^6.6.0",
    "react-native-web": "^0.12.2",
    "react-redux": "^5.0.6",
    "redux": "^3.7.2",
    "redux-persist": "^5.4.0",
    "redux-saga": "^0.16.0",
    "reselect": "^3.0.1"
  }
}
`
App.Json
`
{
  "expo": {
    "sdkVersion": "37.0.0"
  },
  "name": "WhoopaUserApp",
  "displayName": "Whoopa"
}
`

**Comment by hahtml** [comment]
Have u tried to close all terminals and run the build again? I think your old version of react-native is still alive in nodejs server for some reason.

**Comment by eduplus** [comment]
> Have u tried to close all terminals and run the build again? I think your old version of react-native is still alive in nodejs server for some reason.

Yep I get this error message usually in that situation and closing the running metro instance and rerunning has fixed this.

**Comment by AdeelShoukatAli** [comment]
> Have u tried to close all terminals and run the build again? I think your old version of react-native is still alive in nodejs server for some reason.

I've tried all the stuffs. restarted computer created new project put my files. Same error.

**Comment by AdeelShoukatAli** [comment]
> > Have u tried to close all terminals and run the build again? I think your old version of react-native is still alive in nodejs server for some reason.
> 
> Yep I get this error message usually in that situation and closing the running metro instance and rerunning has fixed this.

Thanks for your suggestion but i've tried restarted computer several times same error. if i downgrade my RN version to 0.50.4 error disappears. But i need latest RN to resolve the 32 bit issue warning.

**Comment by AdeelShoukatAli** [comment]
I'm still facing the same error. Anybody here to help please?

**Comment by eduplus** [comment]
Try running `rm -vrf "$TMPDIR/metro-cache"` and `watchman watch-del-all`. Remove node_modules and install dependencies again. (iOS run pod isntall too)). Then starting metro bundler with `npm run start --reser-cache`.

**Comment by AdeelShoukatAli** [comment]
> Try running `rm -vrf "$TMPDIR/metro-cache"` and `watchman watch-del-all`. Remove node_modules and install dependencies again. (iOS run pod isntall too)). Then starting metro bundler with `npm run start --reser-cache`.

Tried Sir. But Same result. Tried killing node processes. Rebuild. but same result.

**Comment by AdeelShoukatAli** [comment]
> Try running `rm -vrf "$TMPDIR/metro-cache"` and `watchman watch-del-all`. Remove node_modules and install dependencies again. (iOS run pod isntall too)). Then starting metro bundler with `npm run start --reser-cache`.

Running with `expo` this error isn't appearing. Can you please look again.

**Comment by AdeelShoukatAli** [comment]
After struggling for days Finally i solved it. react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/

**Comment by amSaighi** [comment]
The same issue here, 
I cleaned my cache, reinstall npm dependencies, I tried all recommendation
 ` "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "~38.0.8",
    "expo-status-bar": "^1.0.2",
    "react": "~16.11.0",
    "react-dom": "~16.11.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-38.0.0.tar.gz",
    "react-native-web": "~0.11.7"
  },
  "devDependencies": {
    "@babel/core": "^7.8.6",
    "babel-preset-expo": "~8.1.0"
  },`
![Capture](https://user-images.githubusercontent.com/3142753/94366163-76bc8600-00d6-11eb-83aa-e5ec02d064ae.PNG)

**Comment by seo-audit** [comment]
> After struggling for days Finally i solved it. react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/

Bro can you explain it plz
