### ISSUE TITLE
Cannot modify the width of Switch component

### ISSUE THREAD

**Issue by HectorRicardo** [facebook/react-native#29047]
## Description

On Android, it is possible to modify the width of a Switch by using the `android:switchMinWidth` attribute

```xml
<Switch android:switchMinWidth="50dp" />
```

or by using the `.setSwitchMinWidth(int pixels)` method.

```java
Switch mySwitch = findViewById(R.id.mySwitch);
mySwitch.setSwitchMinWidth(400);
```

![image](https://user-images.githubusercontent.com/16261233/83707241-2a0ce680-a5df-11ea-9436-bf1f881259a3.png)

There is no such attribute in React-Native. Ideally, it would be nice to have a "width" attribute for the Switch component, such that we can do

```javascript
<Switch width={50} />
```
to achieve something similar as the above screenshot.

## React Native version:

System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Memory: 6.39 GB / 15.87 GB
  Binaries:
    Node: 12.16.3 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      Android NDK: 17.2.4988734
  IDEs:
    Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6392135
  Languages:
    Python: 3.8.3 - C:\Python38\python.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.1 => 0.62.1
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by HectorRicardo** [comment]
I think the following code changes will allow to control the Switch's width:

On ReactAndroid/src/main/java/com/facebook/react/views/switchview/ReactSwitchManager.java:
[https://www.diffchecker.com/1k7qqHI9](https://www.diffchecker.com/1k7qqHI9)

On ReactAndroid/src/main/java/com/facebook/react/views/switchview/ReactSwitch.java:
[https://www.diffchecker.com/WnCUHbRK](https://www.diffchecker.com/WnCUHbRK)

**Comment by fabriziobertoglio1987** [comment]
I already found the solution and I m writing a pull request

But changing only the width is not enough 

it needs to change also the click area

**Comment by safaiyeh** [comment]
Thanks for the issue @HectorRicardo! Sorry, for the delay to getting to this but it looks like @fabriziobertoglio1987 has it handled.

**Comment by fabriziobertoglio1987** [comment]
thanks @safaiyeh I am accepting https://github.com/facebook/react-native/pull/29059#issuecomment-640222747 @dulmandakh suggestion

>why not support minWidth in style?

I believe it is very important having a uniform android/iOS API
I moved the PR to draft and will make the changes as soon as https://github.com/facebook/react-native/pull/29070 is completed. Thanks a lot
