### ISSUE TITLE
Error: Network Error (on axios call as well as fetch)

### ISSUE THREAD

**Issue by vikil143** [facebook/react-native#29058]
Error: Network Error
    at createError (createError.js:16)
    at XMLHttpRequest.handleError (xhr.js:83)
    at XMLHttpRequest.dispatchEvent (event-target-shim.js:818)
    at XMLHttpRequest.setReadyState (XMLHttpRequest.js:574)
    at XMLHttpRequest.__didCompleteResponse (XMLHttpRequest.js:388)
    at XMLHttpRequest.js:501
    at RCTDeviceEventEmitter.emit (EventEmitter.js:189)
    at MessageQueue.__callFunction (MessageQueue.js:436)
    at MessageQueue.js:111
    at MessageQueue.__guard (MessageQueue.js:384)

Getting this error on axios catch.
Basically I m fetching data from backend its works fine postman but on mobile app getting this message it my request was like this 
  axios('URL',{
data,
method:"POST",
headers:headers
})
        .then(response => {
          console.log('Response, response);
        // code

        })
        .catch(error => {
          console.log('ERROR ', error);
         // code

        });

IT not even getting error.response (which is getting undefined)

System:
    OS: Linux 5.3 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i5-2500 CPU @ 3.30GHz
    Memory: 961.11 MB / 15.47 GB
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 13.10.1 - ~/.nvm/versions/node/v13.10.1/bin/node
    npm: 6.13.7 - ~/.nvm/versions/node/v13.10.1/bin/npm
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1

Please help me

Thanks in advance

**Comment by vikil143** [comment]
This issues was coming because of passing wrong data to formData so after fix it will solved

**Comment by hxzAugustinus** [comment]
@vikil143    i not  use   formData   and my axios  header  setting
`
axios.defaults.headers.post['Content-Type'] = 'application/json;charset=UTF-8';
`
but i get  the   same   problem

**Comment by klever34** [comment]
anyone got a solution yet? Just

**Comment by katye333** [comment]
I am encountering the same problem

**Comment by vajid-khan** [comment]
Facing same problem on iOS. Any solution?

**Comment by vikil143** [comment]
actually  I m facing this issue becoz of passing work param to formdata

**Comment by myasarF** [comment]
any solution ?

**Comment by leejaehyup** [comment]
When appending data to formdata, value must be USVString or Blob.
If you put the value as an object, convert it to JSON.stringify
