### ISSUE TITLE
Crashes in PermissionsModule.onRequestPermissionsResult

### ISSUE THREAD

**Issue by luxiliu** [facebook/react-native#29056]
I'm developing using Pixel 3 with Android API 29. After permission requesting dialog dismissed(Accept or Decline), the app crashes.

## Description

     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.facebook.react.bridge.Callback.invoke(java.lang.Object[])' on a null object reference
        at com.facebook.react.modules.permissions.PermissionsModule.onRequestPermissionsResult(PermissionsModule.java:208)
        at com.facebook.react.ReactActivityDelegate$2.invoke(ReactActivityDelegate.java:171)
        at com.facebook.react.ReactActivityDelegate.onResume(ReactActivityDelegate.java:102)
        at com.facebook.react.ReactActivity.onResume(ReactActivity.java:57)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1453)
        at android.app.Activity.performResume(Activity.java:7962)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4195)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4237) 
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 

## React Native version:
```
System:
    OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 660.12 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.3.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 26, 28, 29
      Build Tools: 26.0.2, 28.0.3, 29.0.3
      System Images: android-21 | Google APIs Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  npmPackages:
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    react-native-create-library: 3.1.2
    react-native: 0.61.5
```

## Snack, code example, screenshot, or link to a repository:
```
import {PermissionsAndroid} from 'react-native';

export default async function requestAllPermissions() {
  try {
    const granted = await PermissionsAndroid.requestMultiple(
      [PermissionsAndroid.PERMISSIONS.CAMERA, PermissionsAndroid.PERMISSIONS.RECORD_AUDIO]
    );

    if (granted[PermissionsAndroid.PERMISSIONS.CAMERA] == PermissionsAndroid.RESULTS.GRANTED) {
      console.log('You can use the camera');
    } else {
      console.log('Camera permission denied');
    }
  } catch (err) {
    console.warn(err);
  }
}
```

**Comment by luxiliu** [comment]
> The docs don't mention needing to add these permissions to your manifest, which is actually a required step (and the docs should be updated). Do you have the permissions for these in your manifest?

Yes, I have the permission in AndroidManifest.xml

`  <uses-permission android:name="android.permission.CAMERA"/>`
`<uses-permission android:name="android.permission.RECORD_AUDIO"/>`

**Comment by luxiliu** [comment]
> Can you give some more information about what you're getting back as `granted`? Is it not coming back as an array maybe?

My JS code is:

import {PermissionsAndroid} from 'react-native';

export default async function requestAllPermissions() {
  try {
    const granted = await PermissionsAndroid.requestMultiple(
      [PermissionsAndroid.PERMISSIONS.CAMERA, PermissionsAndroid.PERMISSIONS.RECORD_AUDIO]
    );

    if (granted[PermissionsAndroid.PERMISSIONS.CAMERA] == PermissionsAndroid.RESULTS.GRANTED) {
      console.log('You can use the camera');
    } else {
      console.log('Camera permission denied');
    }
  } catch (err) {
    console.warn(err);
  }
}

**Comment by fabriziobertoglio1987** [comment]
https://github.com/facebook/react-native/blob/f53267f7031dec9f8e61c679bf786d025d634eb6/ReactAndroid/src/main/java/com/facebook/react/modules/permissions/PermissionsModule.java#L204-L210

crashes because `mCallbacks.get(requestCode)` is null

Reasons:
1) You could be passing the wrong Permission `requestCode`
2) `mCallback` does not include that permissions... don't know why

https://github.com/facebook/react-native/blob/f53267f7031dec9f8e61c679bf786d025d634eb6/ReactAndroid/src/main/java/com/facebook/react/modules/permissions/PermissionsModule.java#L113-L130

**Comment by fabriziobertoglio1987** [comment]
**Your issue does not reproduce and it should be closed**

I created [an example with your code](https://github.com/fabriziobertoglio1987/AwesomeProject/commit/11c77367bcb29a9db6fdfcc9d9080d5801fe830a) and this is the result:

<img src="https://user-images.githubusercontent.com/24992535/84357690-61bef400-abc6-11ea-8831-b15abd201a8f.png" width="250" />

**Comment by luxiliu** [comment]
But mCallbacks.get(requestCode) doesn't need a null check?

**Comment by ThinhVu** [comment]
@luxiliu 

We have the same error but the problem come from 3rd module (react native callkeep), not from react-native itself (or maybe it is).

Reference: https://github.com/react-native-webrtc/react-native-callkeep/issues/288

Btw, null check before calling a method is better than do nothing. +1 for your idea.

**Comment by qindachang** [comment]
I found that this problem ocurred in others native module call (activity)requestPermissions(String[] permissions, int requestCode), not (reactActivty)requestPermissions(String[] permissions, int requestCode, PermissionListener listener). 

Look at the react permission main process first:

```java

// ReactActivity.java

public abstract class ReactActivity extends AppCompatActivity
    implements DefaultHardwareBackBtnHandler, PermissionAwareActivity {

  @Override
  public void onRequestPermissionsResult(
      int requestCode, String[] permissions, int[] grantResults) {
    mDelegate.onRequestPermissionsResult(requestCode, permissions, grantResults);
  }

}

// ReactActivityDelegate.java

public class ReactActivityDelegate {

  public void onRequestPermissionsResult(
      final int requestCode, final String[] permissions, final int[] grantResults) {
    mPermissionsCallback =
        new Callback() {
          @Override
          public void invoke(Object... args) {
            if (mPermissionListener != null
                && mPermissionListener.onRequestPermissionsResult(
                    requestCode, permissions, grantResults)) {
              mPermissionListener = null;
            }
          }
        };
  }

}

// PermissionsModule.java

public class PermissionsModule extends NativePermissionsAndroidSpec implements PermissionListener {

  private final SparseArray<Callback> mCallbacks;

  public void requestPermission(final String permission, final Promise promise) {
    Context context = getReactApplicationContext().getBaseContext();
    if (Build.VERSION.SDK_INT < Build.VERSION_CODES.M) {
      promise.resolve(
          context.checkPermission(permission, Process.myPid(), Process.myUid())
                  == PackageManager.PERMISSION_GRANTED
              ? GRANTED
              : DENIED);
      return;
    }
    if (context.checkSelfPermission(permission) == PackageManager.PERMISSION_GRANTED) {
      promise.resolve(GRANTED);
      return;
    }

    try {
      PermissionAwareActivity activity = getPermissionAwareActivity();

      mCallbacks.put(
          mRequestCode,
          new Callback() {
            @Override
            public void invoke(Object... args) {
              int[] results = (int[]) args[0];
              if (results.length > 0 && results[0] == PackageManager.PERMISSION_GRANTED) {
                promise.resolve(GRANTED);
              } else {
                PermissionAwareActivity activity = (PermissionAwareActivity) args[1];
                if (activity.shouldShowRequestPermissionRationale(permission)) {
                  promise.resolve(DENIED);
                } else {
                  promise.resolve(NEVER_ASK_AGAIN);
                }
              }
            }
          });

      activity.requestPermissions(new String[] {permission}, mRequestCode, this);
      mRequestCode++;
    } catch (IllegalStateException e) {
      promise.reject(ERROR_INVALID_ACTIVITY, e);
    }
  }

  /** Method called by the activity with the result of the permission request. */
  @Override
  public boolean onRequestPermissionsResult(
      int requestCode, String[] permissions, int[] grantResults) {
    mCallbacks.get(requestCode).invoke(grantResults, getPermissionAwareActivity());
    mCallbacks.remove(requestCode);
    return mCallbacks.size() == 0;
  }

}

```

Steps:
1. Call requestPermission multiple times at the same time in js side,  mCallbacks will has more than one elements. And even though onRequestPermissionsResult be called, mCallbacks.size() == 0 will never return true.
2. Others native module call (activity)requestPermissions(String[] permissions, int requestCode), example
    ```java
    requestPermissions(new String[]{Manifest.permission.CAMERA}, 1000); // requestCode=1000
    ```
3. Because mCallbacks.size() == 0 will never return true, so mPermissionListener will not assigned null in ReactActivityDelegate.java . When others native module call requestPermissions, at this time ReactActivityDelegate.onRequestPermissionsResult be called. Finally onRequestPermissionsResult be called in PermissionsModule.java. But requestCode is 1000.
4. NullPointException.
