### ISSUE TITLE
Android app crash on release build, Fatal Exception: java.lang.RuntimeException

### ISSUE THREAD

**Issue by ArchanaSharma95** [facebook/react-native#29053]
Android app crash on release build. I have enable firebase crash logs, This is crash I found :

**Crash Log ::**

> Fatal Exception: java.lang.RuntimeException: com.facebook.react.bridge.JavaJSExecutor$ProxyExecutorException: java.net.SocketException: Software caused connection abort
>        at com.facebook.react.bridge.DefaultNativeModuleCallExceptionHandler.handleException(DefaultNativeModuleCallExceptionHandler.java:19)
>        at com.facebook.react.devsupport.DevSupportManagerImpl.handleException(DevSupportManagerImpl.java:261)
>        at com.facebook.react.bridge.CatalystInstanceImpl.onNativeException(CatalystInstanceImpl.java:600)
>        at com.facebook.react.bridge.CatalystInstanceImpl.access$1000(CatalystInstanceImpl.java:45)
>        at com.facebook.react.bridge.CatalystInstanceImpl$NativeExceptionHandler.handleException(CatalystInstanceImpl.java:618)
>        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:28)
>        at android.os.Looper.loop(Looper.java:165)
>        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
>        at java.lang.Thread.run(Thread.java:760)

**Environment::**

> System:
>     OS: macOS 10.15.1
>     CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
>     Memory: 35.79 MB / 8.00 GB
>     Shell: 5.7.1 - /bin/zsh
>   Binaries:
>     Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
>     Yarn: 1.22.0 - ~/.nvm/versions/node/v12.13.1/bin/yarn
>     npm: 6.12.1 - ~/.nvm/versions/node/v12.13.1/bin/npm
>     Watchman: 4.9.0 - /usr/local/bin/watchman
>   SDKs:
>     iOS SDK:
>       Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
>     Android SDK:
>       API Levels: 23, 25, 26, 27, 28, 29
>       Build Tools: 23.0.1, 28.0.3, 29.0.2
>   IDEs:
>     Android Studio: 3.6 AI-192.7142.36.36.6241897
>     Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
>   npmPackages:
>     react: ^16.13.0 => 16.13.1 
>     react-native: ^0.61.5 => 0.61.5 
>   npmGlobalPackages:
>     create-react-native-module: 0.16.0
>     react-native-cli: 2.0.1

Please help not able to find out a solution.

**Comment by pasine** [comment]
Same error for me on Android 4.4.  
```
System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 898.84 MB / 32.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v10.16.0/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v10.16.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 16, 17, 18, 19, 21, 27, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-18 | Google APIs Intel x86 Atom, android-19 | Google APIs Intel x86 Atom, android-22 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_232 - /usr/bin/javac
    Python: 2.7.16 - /Users/pasine/.pyenv/shims/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found
```
