### ISSUE TITLE
Network Error Failed on Android

### ISSUE THREAD

**Issue by imansalhi** [facebook/react-native#29057]
My react-native project gets network request failed when user is using mobile data.  

## Description
this bug raises accidentally then it will work on again after some minutes.
 when the device is on wify-network every thing works on but when its using mobile data the problem will happened after some minutes. 
unfortunately i could not find out when exactly the bug will raised. most of the times it will happened when the app is on background state and user takes it to foreground after some minutes spent. but i'm sure it will happened only when the device uses **mobile-data** 

at first i knew i get an error seems has came from our server with **status 503** while there were no log which illustrates the request is reaching to the server!.
 so i added another fetch request to another server to detect if the problem is really related to the server-side.

a set a code to send a fetch request request to starwar api, only when i got the status 503 from server our server. then i found out i will get **error type network request failed** in this case!!!!! while react native net info cant detect i have not internet access on app.
in most of the time it will fix up when i come to another app like chrome and do some active on that and back to the app..then the problem will solve again and i can get response from both servers.

i use  `android:usesCleartextTraffic="true"` in manifest as well 

`
```javascript
  fetch('https://swapi.dev/api/people/1', {
            method: 'Get',
            headers: {
                "Content-Type": "application/json; charset=utf-8",
                'Accept': 'application/json'
            },
        }).then(response => {
            if (response.status == 200) {
                alert(JSON.stringify(response))
                response.json().then((res) => {
                    console.log(res)
                }).catch((er) => {
                    console.log('Error:', er)
                })
            }else{
                alert(JSON.stringify(response))
                console.log('Error:', response)
            }


        }).catch((er) => {
            alert(er)
            console.log('No-res', er)
        })
```
`

maybe its remarkable our staging server is not SSL but... the starwar api is so we cant say the problem is because of that.
 

## React Native version:
`"`[`react-native`](https://npmjs.com/package/react-native)`": "`[`0.61.5`](https://npmjs.com/package/react-native)`",`

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.turn on mobile data on android
2.it will happened accidentally after some minute

**Comment by NMehralizadeh** [comment]
I have the same issue

**Comment by alexkendall** [comment]
I also have this issue "react-native": "0.61.2"

**Comment by khushbuthakur** [comment]
Any solution? 
I have same issue for **"react-native":"0.62.2"**. 
This seems to be a problem in only **one plus** devices so far.

**Comment by IVBC** [comment]
Any solution?

**Comment by ianberttusil** [comment]
I also have this issue in "react-native": "~0.63.3"

**Comment by khushbuthakur** [comment]
I was facing same issue too. Implementing below solution fixed it for me. 

```
<?xml version="1.0" encoding="utf-8"?> <network-security-config> <domain-config cleartextTrafficPermitted="true"> <domain includeSubdomains="true">example.com</domain> <domain includeSubdomains="false">localhost</domain> <domain includeSubdomains="false">10.0.2.2</domain> <domain includeSubdomains="false">10.0.3.2</domain> </domain-config> </network-security-config>
```

Reference : https://stackoverflow.com/a/57747157

**Comment by IVBC** [comment]
Any solution???

**Comment by Biplovkumar** [comment]
**Sol 1** :- just change flipper version in gradle.properties

**`FLIPPER_VERSION=0.54.0`** 

**Sol 2** :- 
I got the same issue on Android 9 because of the "http" and issue resolved by just adding android:usesCleartextTraffic="true" in 
**AndroidManifest.xml**

```
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
<application
  android:usesCleartextTraffic="true"
 .......>
 .......
</application>
```

**Comment by henaharon** [comment]
@IVBC Did it happen on debug mode ?
if yes, 
go to android/app/src/debug/AndroidManifest.xml
and change 
`<application android:usesCleartextTraffic="true" tools:targetApi=<your targetSdkVersion> .../>`

**Comment by Haseeba393** [comment]
I'm facing the same issue. These are the version that i'm using:
"axios": "^0.21.1",
"react": "16.13.1",
"react-native": "0.63.4",
FLIPPER_VERSION=0.54.0

I have following ways to encounter this problem:
1. Add android:usesCleartextTraffic="true"
2. Add network-security-config with my domain
3. Comment this line initializeFlipper(this, getReactNativeHost().getReactInstanceManager());
4. Downgrade Flipper version to 0.41.0

and some more methods but nothing is working for me on android side. Can you please help me out

**Comment by gulshanAI** [comment]
I am also facing the same issue but in case of IOS it's work
