### ISSUE TITLE
use_frameworks! fails on 0.63.0-rc.1

### ISSUE THREAD

**Issue by dulmandakh** [facebook/react-native#29051]
## Description
I'm trying to upgrade RN to 0.63.0-rc.1, where I have **use_frameworks!** in Podfile, and got error below

```shell
Pods-RN063' target has transitive dependencies that include statically linked binaries:
```

## React Native version:
System:
    OS: macOS 10.15.5
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 410.96 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.4.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3
      System Images: android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_242 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
1. Create a new project using RN 0.63.0-rc.1 or npx react-native init RN063 --version  0.63.0-rc.1
2. Find Podfile and add **use_frameworks!**, then run **pod install** and it'll fail.

## Expected Results
**pod instal** would run successfully, then compile and run the project.

## Snack, code example, screenshot, or link to a repository:
Podfile example

```ruby
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'RN063' do
  use_frameworks!
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'RN063Tests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'RN063-tvOS' do
  # Pods for RN063-tvOS

  target 'RN063-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
```

**Comment by dulmandakh** [comment]
it seems caused by **OpenSSL-Universal**

**Comment by alloy** [comment]
It’s not just OpenSSL-Universal, but from what I recall also, at least, CocoaLibEvent.

While this is indeed something I would like to see differently, it’s a known thing and hence the comment in the `Podfile`:

```ruby
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
```

If anything, this issue should be filed in the flipper repo, but there probably already is one.
