### ISSUE TITLE
[Android] Flexbox broken?

### ISSUE THREAD

**Issue by BerndWessels** [facebook/react-native#2906]
Hi

I have a simple layout where I want the text in a button centered. Unfortunately it seems that this is broken in Android, because the text sticks to the Left.

Is this an issue, or am I doing something wrong?

    render() {
        return (
            <View style={styles.container}>
                <Text style={styles.heading}>
                    Welcome
                </Text>
                <TextInput style={styles.input}
                           placeholder="Username"
                           placeholderTextColor="#AAAAAA"
                           onChangeText={(text)=>this.setState({username: text})}
                           autoCapitalize="none"/>
                <TextInput style={styles.input}
                           placeholder="Password"
                           placeholderTextColor="#AAAAAA"
                           onChangeText={(text)=>this.setState({password: text})}
                           secureTextEntry={true}/>
                <TouchableHighlight style={styles.button}
                                    onPress={this.onLoginPressed.bind(this)}>
                    <Text style={styles.buttonText}>
                        Log in
                    </Text>
                </TouchableHighlight>
                <ActivityIndicatorIOS animating={this.state.showProgress}
                                      size="large"
                                      style={styles.loader}/>
                <Text style={styles.error}>
                    {this.state.error}
                </Text>
            </View>
        );
    }

    var styles = StyleSheet.create({
        container: {
            flex: 1,
            justifyContent: 'center',
            alignItems: 'center',
            padding: 10,
            paddingTop: 40,
            backgroundColor: 'transparent'
        },
        heading: {
            fontSize: 30,
            marginTop: 10,
            color: '#FFFFFF'
        },
        input: {
            height: 50,
            marginTop: 10,
            padding: 4,
            fontSize: 18,
            borderWidth: 1,
            borderColor: '#CFDE00',
            color: '#FFFFFF'
        },
        button: {
            alignSelf: 'stretch',
            justifyContent: 'center',
            alignItems: 'center',
            marginTop: 10,
            height: 50,
            backgroundColor: '#CFDE00'
        },
        buttonText: {
            fontSize: 22,
            color: '#000000'
        },
        error: {
            marginTop: 10,
            color: 'red'
        }
    });

![flexbox](https://cloud.githubusercontent.com/assets/1776695/9985027/025f57dc-6078-11e5-8af7-7744963af136.png)

**Comment by kocyigityunus** [comment]
use textAlignCenter prop. https://facebook.github.io/react-native/docs/text.html

![screen shot 2015-09-21 at 10 05 20](https://cloud.githubusercontent.com/assets/922418/9986684/4c27825c-6048-11e5-8076-2f12f34e6d34.png)

**Comment by BerndWessels** [comment]
Thank you @kocyigityunus. But I can't get it centered the way you mentioned.

Can you please post an example code here, how you achieved it.

Thanks
Bernd

**Comment by kocyigityunus** [comment]
@BerndWessels  https://rnplay.org/apps/CZzneg -- look at the index.android.js and make sure you selected android at the right side. if this not solves your problem make sure you have right react-native version, right android version & tools and your command line looking right ANDROID_HOME

**Comment by BerndWessels** [comment]
Interesting, the exact same code does not have the same result in my Simulator. Even though I think I have the latest Android installed - downloaded the full package a week ago and installed everything from scratch.
Which emulator do you use?
Thanks
Bernd

**Comment by BerndWessels** [comment]
OK, I think I have an idea whats wrong. It seems the Android Flexbox behaves slightly differently than the IOS one. So on Android I have to use `alignSelf: 'stretch'` when I have a container with `flex: 1` within another container with `flex: 1`. That is not necessary on IOS.
Will do some more investigation and might open another issue on that if necessary.
Cheers
Bernd
