### ISSUE TITLE
Animation translateX does not flip in RTL mode

### ISSUE THREAD

**Issue by YOEL311** [facebook/react-native#29060]
Animation  comes off the screen when it receives a positive value
in IOS where the direction is rtl

    "react": "16.11.0",
    "react-native": "0.62.2"

## Expected Results
Describe what you expected to happen.

I expect RTL direction mode
The animation will move from right to left
And not from left to right

````
import React, {useRef} from 'react';

import {StyleSheet, View, Animated, Button} from 'react-native';

const App: () => React$Node = () => {
  const animation = useRef(new Animated.Value(0)).current;

  const left = animation.interpolate({
    inputRange: [0, 1],
    outputRange: [0, 30],
  });

  const onClick = () => {
    Animated.timing(animation, {
      toValue: 1,
      duration: 1000,
      useNativeDriver: true,
    }).start();
  };
  const onClickReset = () => {
    Animated.timing(animation, {
      toValue: 0,
      duration: 1000,
      useNativeDriver: true,
    }).start();
  };

  return (
    <>
      <View      
       style={{
            direction:'rtl }} //<this line
         >
        <Animated.View
          style={{
            backgroundColor: 'red',
            width: 100,
            height: 100,
            transform: [{translateX: left}],
            margin: 20,
          }}
        />
        <Button style={{margin: 10}} onPress={onClick} title={'to move'} />
        <Button style={{marginUp: 10}} onPress={onClickReset} title={'reset'} />
      </View>
    </>
  );
};

export default App;
````
![IOS](https://user-images.githubusercontent.com/39925212/84181805-202d2c80-aa92-11ea-9b63-2f59d3f1231c.gif)

**Comment by chrisglein** [comment]
Recreated in a Snack: https://snack.expo.io/@chrisglein/issue_29060

Documentation for [transforms](https://reactnative.dev/docs/transforms) doesn't really indicate the expected units. I would expect a `transformX` of 30 to be similar to a left `margin` of 30, but maybe that's not the case?

**Comment by YOEL311** [comment]
Hi
I updated the issue
