### ISSUE TITLE
Both libhermes-executor-release.so and libhermes-executor-debug.so was include in the apk

### ISSUE THREAD

**Issue by jinshiyi11** [facebook/react-native#29064]
## Description
On android,both libhermes-executor-release.so and libhermes-executor-debug.so was include in the output apk.
![image](https://user-images.githubusercontent.com/3433961/83846979-1330d600-a73e-11ea-8680-9b1ac023fcdb.png)

## React Native version:
0.63.0-rc.1

## Steps To Reproduce
just build the apk

## Expected Results
if enableHermes is false. no hermes so was include in the apk.if enableHermes,debug apk only include debug so and release include release so.

**Comment by kmkrtich** [comment]
Same for me.
I use even react-native-v8 engine with enableHermes=false, but still see libs from hermes

**Comment by matt-oakes** [comment]
This is still an issue and should be left open.

**Comment by maxammann** [comment]
Just created a PR to fix this: https://github.com/facebook/react-native/pull/30303

**Comment by cortinico** [comment]
Closing as this has been fixed in RN 0.71 and also backported on previous versions by a number of different fixes
