### ISSUE TITLE
Header of Flatlist unmounting

### ISSUE THREAD

**Issue by AndisKush** [facebook/react-native#29061]
**Hello,**

I am trying to put a header in my FlatList, it works fine but when scroll to the end of the FlatList and call the function onEndReached the Header unmount, it disappear. I tried to bind the header in the cronstructor but not worked.

This is my code

`
import 'react-native-gesture-handler';
import api from '../services/api';

import React, { Component } from 'react';
import { View, Text, FlatList, TouchableOpacity, StyleSheet, Image, Dimensions } from 'react-native';

//import SwiperFlatList from 'react-native-swiper-flatlist';

export default class Main extends Component {

    constructor(props, context) {
        super(props, context);
        this._headerComponent = this._headerComponent.bind(this);
        this.state ={
            productInfo: {},
            docs: [],
            page: 1,
            user:{},
            docsGroup:[]
        };
    }

    

    componentDidMount() {
        this.loadProducts();
        this.loadGroupProducts();
    }

    loadProducts = async (page = 1) => {
            const response = await api.get(`/products?page=${page}`);
            //...productInfo retorna todo o restante do json em outro variavel
            const { docs, ...productInfo} = response.data;
            this.setState({ 
                //somando a lista anterior com docs: [...this.state.docs
                //se deixar somente docs ele sobescreve o array
                docs: [...this.state.docs, ...docs], 
                productInfo,
                page 
            });
    };

    loadMore = () => {
        const {page, productInfo} = this.state;
        if(page === productInfo.pages) return;
        const pageNumber = page + 1;
        this.loadProducts(pageNumber);
    };

    renderItem = ({item}) => (
        <View style={styles.productContainer}>  
            <Text style={styles.productTitle}>{item.title}</Text>
            <Text style={styles.productDescription}>{item.description}</Text>
            <TouchableOpacity style={styles.productButton} onPress={() => {}}>
                <Text style={styles.productButtonText}>Acessar</Text>
            </TouchableOpacity>
        </View>
    )
    

    loadGroupProducts = async () => {
        const response = await api.get(`/groupproducts`);
        //...productInfo retorna todo o restante do json em outro variavel
        const { docs } = response.data;
        this.setState({ 
            //somando a lista anterior com docs: [...this.state.docs
            //se deixar somente docs ele sobescreve o array
            docsGroup: [...this.state.docsGroup, ...docs]
        });
    };

    renderGroup = ({item}) => (
        <View style={styles.slide}>
            <Image source={require('../images/group1.png')}/>
            <Text style={styles.text}>{item.title}</Text>
        </View>
    )

    _headerComponent = () => (
        <View >
            <FlatList style={styles.wrapper} 
                horizontal={true}
                contentContainerStyle={styles.list}
                data={this.state.docsGroup}
                keyExtractor={item => item._id}
                renderItem={this.renderGroup}
                showsHorizontalScrollIndicator={false}
            />
        </View>
    )

    render() {
        return (
            <View style={styles.container}>
                <FlatList 
                    contentContainerStyle={styles.list}
                    data={this.state.docs}
                    keyExtractor={item => item._id}
                    renderItem={this.renderItem}
                    onEndReached={this.loadMore}
                    onEndReachedThreshold={0.1}
                    ListHeaderComponent={this._headerComponent}
                    
                />
            </View>    
        );
    }
}
export const { width, height } = Dimensions.get('window');

const styles = StyleSheet.create({
    container:{
        flex: 1,
        backgroundColor: "#fafafa"
    },

    list:{
        padding: 20
    },

    productContainer:{
        backgroundColor: "#FFF",
        borderWidth: 1,
        borderColor: "#DDD",
        borderRadius: 5,
        padding: 20,
        marginBottom: 20
    },

    productTitle:{
        fontSize: 18,
        fontWeight: "bold",
        color: "#333"
    },

    productDescription:{
        fontSize: 16,
        color: "#999",
        marginTop: 5,
        lineHeight: 24
    },

    productButton: {
        height: 42,
        borderRadius: 5,
        borderWidth: 2,
        borderColor: "#DA552F",
        backgroundColor: "transparent",
        justifyContent: "center",
        alignItems: "center",
        marginTop: 10
    },

    productButtonText:{
        fontSize: 16,
        color: "#DA552F",
        fontWeight: 'bold'
    },

    //HeaderFlatList
    wrapper: {
        flex:1,
        backgroundColor: "#fafafa",
        paddingVertical: 10,
        borderRadius: 20,
        
    },
    slide: {
        height: 55,
        width: 115,
        justifyContent: 'center',
        alignItems:"center"
    },
    text: {
    color: '#000',
    fontSize: 10,
    fontWeight: 'bold',
    justifyContent: 'center',
    alignItems: "center",
  }
});
`

I am starting now with React Native so any tips is welcome

**Comment by AndisKush** [comment]
I forgot to put to bind on the header

`ListHeaderComponent={this._headerComponent.bind(this)}`

But then I see another problem, when I turn the phone and come back to the original position the header gone

**Comment by ArekChr** [comment]
+1
The same problem using functional component (hooks)
