### ISSUE TITLE
Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'LinkingManager' could not be found. Verify that a module by this name is registered in the native binary

### ISSUE THREAD

**Issue by TdAmitKatiyar** [facebook/react-native#29079]
## Description
Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'LinkingManager' could not be found. Verify that a module by this name is registered in the native binary

## React Native version:
OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Memory: 24.67 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.6.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.5.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.5.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    Android SDK:
      API Levels: 21, 23, 24, 26, 27, 28, 29
      Build Tools: 27.0.2, 27.0.3, 28.0.2, 28.0.3, 29.0.0, 29.0.3
      System Images: android-27 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: 10.1/10B61 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_191 - /usr/bin/javac
    Python: 2.7.10 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
1. On Android run npx react-native run-android or npx react-native run-android --variant=debug

## Expected Results
.

## Snack, code example, screenshot, or link to a repository:
![WhatsApp Image 2020-06-06 at 8 31 59 PM (1)](https://user-images.githubusercontent.com/64525584/83947492-eca19680-a834-11ea-99c1-0d1e757b68b5.jpeg)

**Comment by chrisglein** [comment]
Potentially the same error on StackOverflow [here](https://stackoverflow.com/questions/58659906/turbomoduleregistry-getenforcing-networking-could-not-be-found-verify-that-a) and [here](https://stackoverflow.com/questions/61206109/react-native-turbomoduleregistry-getenforcing-imageloader-issue). Neither has an answer.

**Comment by TdAmitKatiyar** [comment]
Solved. It was my fault :- Somewhere at my code I ussed = instead of === for platform check. So it polluted the global variable and set the platform to 'ios' and since ios needs LinkingManager which cant be. found in android build of course.
.

**Comment by wdevon99** [comment]
> platform

You are a life saver! Thank you for the solution!

**Comment by GIRIRAJNAGAR768** [comment]
> Solved. It was my fault :- Somewhere at my code I ussed = instead of === for platform check. So it polluted the global variable and set the platform to 'ios' and since ios needs LinkingManager which cant be. found in android build of course.
> .

thanks..

**Comment by senica** [comment]
I'm using expo. I solved this by removing the `sdkVersion` from my `app.json` file. I had copied it over from an old build.

**Comment by Smallworld-P** [comment]
我降低了 npm 版本，并重新 npm install 解决了

**Comment by Smallworld-P** [comment]
Lowering the NPM version is resolved
