### ISSUE TITLE
DOC site turns grey

### ISSUE THREAD

**Issue by maixuanhan** [facebook/react-native#29078]
Hi,
Sorry, I know that you want to support the community but turning grey the DOC site does not help. All the site turns dark now and there is a big stick banner on top. It's very hard to learn now :(

https://reactnative.dev

![image](https://user-images.githubusercontent.com/12881054/83945612-75710000-a83e-11ea-8bb0-eb75c8789568.png)

**Comment by kelset** [comment]
👋 @maixuanhan - thanks for reporting this. The correct repo for this is actually the website one, where another person also reported the problem https://github.com/facebook/react-native-website/issues/1983 and it has already been fixed https://github.com/facebook/react-native-website/commit/464399355ba1df51b182b89b4d4515bb399bced5
