### ISSUE TITLE
textInput bugs with secureTextEntry value

### ISSUE THREAD

**Issue by mayuelei66** [facebook/react-native#2908]
I found a interesting thing.When I use the TextInput with secureTextEntry property.If
<code>
<TextInput
                    placeholder='Password'
                    secureTextEntry={true}
                    /></code>
both Android and IOS works fine.But When I use it like this <code>
<TextInput
                    placeholder='Password'
                    secureTextEntry='true'
                    /></code>
the  Android version just go wrong.But the IOS version works fine.
![image](https://cloud.githubusercontent.com/assets/5960165/9987008/884f95c6-6075-11e5-88de-45c4f3eb35d4.png).

**Comment by kmagiera** [comment]
Duplicate #2907
