### ISSUE TITLE
Android production build crashes on start (0.62.2)

### ISSUE THREAD

**Issue by kenobi91** [facebook/react-native#29085]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
As title implies production build for android carashes on start. App opens splash screen and after few seconds closes with msg "Unfortunately, {AppName} stoped.". Relese build vent ok with no error msg, running variant=release ond evice also causes same issue but debug version builds and runs ok, simulator runs ok also.

## React Native version:
System:
    OS: macOS 10.15.5
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 293.88 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.3.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.1.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 22, 23, 24, 25, 26, 27, 28
      Build Tools: 23.0.1, 23.0.3, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.0, 28.0.1, 28.0.2, 28.0.3, 29.0.0, 30.0.0
      System Images: android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_171 - /usr/bin/javac
    Python: 2.7.15 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found

## Expected Results
App to run.

## Snack, code example, screenshot, or link to a repository:
**### adb logcat** 

06-07 16:19:55.748  6824  1166 E AudioRecord-JNI: Error -4 during AudioRecord native read
06-07 16:19:55.749  6824  1173 E DeviceStateChecker: DeviceStateChecker cancelled
06-07 16:19:55.786  6824  7033 E AudioSource: Stop listening is called on already closed AudioSource
06-07 16:19:56.788  1622  1622 E unknown:ReactNative: Unable to launch logbox because react was unable to create the root view
06-07 16:19:58.385  1622  1658 E ReactNativeJS: ReferenceError: Can't find variable: registerScript
06-07 16:19:58.401  1622  1658 E ReactNativeJS: Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
06-07 16:19:58.415  1622  1662 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
06-07 16:19:58.415  1622  1662 E AndroidRuntime: Process: com.appName, PID: 1622
06-07 16:19:58.415  1622  1662 E AndroidRuntime: com.facebook.react.common.JavascriptException: ReferenceError: Can't find variable: registerScript, stack:
06-07 16:19:58.415  1622  1662 E AndroidRuntime: <unknown>@1674:108
06-07 16:19:58.415  1622  1662 E AndroidRuntime: v@2:1473
06-07 16:19:58.415  1622  1662 E AndroidRuntime: <unknown>@1497:223
06-07 16:19:58.415  1622  1662 E AndroidRuntime: v@2:1473
06-07 16:19:58.415  1622  1662 E AndroidRuntime: <unknown>@1494:416
06-07 16:19:58.415  1622  1662 E AndroidRuntime: v@2:1473
06-07 16:19:58.415  1622  1662 E AndroidRuntime: <unknown>@1487:323
06-07 16:19:58.415  1622  1662 E AndroidRuntime: v@2:1473
06-07 16:19:58.415  1622  1662 E AndroidRuntime: <unknown>@1486:295
06-07 16:19:58.415  1622  1662 E AndroidRuntime: v@2:1473
06-07 16:19:58.415  1622  1662 E AndroidRuntime: <unknown>@1226:2094
06-07 16:19:58.415  1622  1662 E AndroidRuntime: v@2:1473
06-07 16:19:58.415  1622  1662 E AndroidRuntime: <unknown>@536:962
06-07 16:19:58.415  1622  1662 E AndroidRuntime: v@2:1473
06-07 16:19:58.415  1622  1662 E AndroidRuntime: <unknown>@534:255
06-07 16:19:58.415  1622  1662 E AndroidRuntime: v@2:1473
06-07 16:19:58.415  1622  1662 E AndroidRuntime: <unknown>@423:316
06-07 16:19:58.415  1622  1662 E AndroidRuntime: v@2:1473
06-07 16:19:58.415  1622  1662 E AndroidRuntime: <unknown>@422:117
06-07 16:19:58.415  1622  1662 E AndroidRuntime: v@2:1473
06-07 16:19:58.415  1622  1662 E AndroidRuntime: <unknown>@6:69
06-07 16:19:58.415  1622  1662 E AndroidRuntime: v@2:1473
06-07 16:19:58.415  1622  1662 E AndroidRuntime: d@2:875
06-07 16:19:58.415  1622  1662 E AndroidRuntime: global code@2121:3
06-07 16:19:58.415  1622  1662 E AndroidRuntime: 
06-07 16:19:58.415  1622  1662 E AndroidRuntime: 	at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:79)
06-07 16:19:58.415  1622  1662 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-07 16:19:58.415  1622  1662 E AndroidRuntime: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
06-07 16:19:58.415  1622  1662 E AndroidRuntime: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
06-07 16:19:58.415  1622  1662 E AndroidRuntime: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
06-07 16:19:58.415  1622  1662 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
06-07 16:19:58.415  1622  1662 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
06-07 16:19:58.415  1622  1662 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
06-07 16:19:58.415  1622  1662 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
06-07 16:19:58.415  1622  1662 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
06-07 16:19:58.415  1622  1662 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
06-07 16:19:58.511  1622  1658 E ReactNativeJS: Invariant Violation: Module AppRegistry is not a registered callable module (calling unmountApplicationComponentAtRootTag)
06-07 16:19:58.572  1622  1622 E WindowManager: 
06-07 16:19:58.572  1622  1622 E WindowManager: android.view.WindowLeaked: Activity com.appName.MainActivity has leaked window com.android.internal.policy.PhoneWindow$DecorView{5c4f5e8 V.E...... R....... 0,0-1080,1920} that was originally added here
06-07 16:19:58.572  1622  1622 E WindowManager: 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:368)
06-07 16:19:58.572  1622  1622 E WindowManager: 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:299)
06-07 16:19:58.572  1622  1622 E WindowManager: 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
06-07 16:19:58.572  1622  1622 E WindowManager: 	at android.app.Dialog.show(Dialog.java:319)
06-07 16:19:58.572  1622  1622 E WindowManager: 	at org.devio.rn.splashscreen.SplashScreen$1.run(SplashScreen.java:36)
06-07 16:19:58.572  1622  1622 E WindowManager: 	at android.app.Activity.runOnUiThread(Activity.java:5524)
06-07 16:19:58.572  1622  1622 E WindowManager: 	at org.devio.rn.splashscreen.SplashScreen.show(SplashScreen.java:27)
06-07 16:19:58.572  1622  1622 E WindowManager: 	at org.devio.rn.splashscreen.SplashScreen.show(SplashScreen.java:49)
06-07 16:19:58.572  1622  1622 E WindowManager: 	at org.devio.rn.splashscreen.SplashScreen.show(SplashScreen.java:56)
06-07 16:19:58.572  1622  1622 E WindowManager: 	at com.appName.MainActivity.onCreate(MainActivity.java:12)
06-07 16:19:58.572  1622  1622 E WindowManager: 	at android.app.Activity.performCreate(Activity.java:6251)
06-07 16:19:58.572  1622  1622 E WindowManager: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
06-07 16:19:58.572  1622  1622 E WindowManager: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
06-07 16:19:58.572  1622  1622 E WindowManager: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
06-07 16:19:58.572  1622  1622 E WindowManager: 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
06-07 16:19:58.572  1622  1622 E WindowManager: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
06-07 16:19:58.572  1622  1622 E WindowManager: 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-07 16:19:58.572  1622  1622 E WindowManager: 	at android.os.Looper.loop(Looper.java:148)
06-07 16:19:58.572  1622  1622 E WindowManager: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
06-07 16:19:58.572  1622  1622 E WindowManager: 	at java.lang.reflect.Method.invoke(Native Method)
06-07 16:19:58.572  1622  1622 E WindowManager: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
06-07 16:19:58.572  1622  1622 E WindowManager: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

### **android/build.gradle**

```
buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 21
        compileSdkVersion = 28
        targetSdkVersion = 28
        multiDexEnabled = true
        supportLibVersion = "28.0.0"
        playServicesVersion = "17.0.0"  
        androidMapsUtilsVersion = "1.3.3"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:3.5.2")

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        google()
        jcenter()
        maven { url 'https://www.jitpack.io' }
    }
}
```

### **android/app/build.gradle**

```
apply plugin: "com.android.application"
apply from: project(':react-native-config').projectDir.getPath() + "/dotenv.gradle"
apply from: "../../node_modules/react-native-vector-icons/fonts.gradle"

import com.android.build.OutputFile

/**
 * The react.gradle file registers a task for each build variant (e.g. bundleDebugJsAndAssets
 * and bundleReleaseJsAndAssets).
 * These basically call `react-native bundle` with the correct arguments during the Android build
 * cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
 * bundle directly from the development server. Below you can see all the possible configurations
 * and their defaults. If you decide to add a configuration block, make sure to add it before the
 * `apply from: "../../node_modules/react-native/react.gradle"` line.
 *
 * project.ext.react = [
 *   // the name of the generated asset file containing your JS bundle
 *   bundleAssetName: "index.android.bundle",
 *
 *   // the entry file for bundle generation. If none specified and
 *   // "index.android.js" exists, it will be used. Otherwise "index.js" is
 *   // default. Can be overridden with ENTRY_FILE environment variable.
 *   entryFile: "index.android.js",
 *
 *   // https://facebook.github.io/react-native/docs/performance#enable-the-ram-format
 *   bundleCommand: "ram-bundle",
 *
 *   // whether to bundle JS and assets in debug mode
 *   bundleInDebug: false,
 *
 *   // whether to bundle JS and assets in release mode
 *   bundleInRelease: true,
 *
 *   // whether to bundle JS and assets in another build variant (if configured).
 *   // See http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants
 *   // The configuration property can be in the following formats
 *   //         'bundleIn${productFlavor}${buildType}'
 *   //         'bundleIn${buildType}'
 *   // bundleInFreeDebug: true,
 *   // bundleInPaidRelease: true,
 *   // bundleInBeta: true,
 *
 *   // whether to disable dev mode in custom build variants (by default only disabled in release)
 *   // for example: to disable dev mode in the staging build type (if configured)
 *   devDisabledInStaging: true,
 *   // The configuration property can be in the following formats
 *   //         'devDisabledIn${productFlavor}${buildType}'
 *   //         'devDisabledIn${buildType}'
 *
 *   // the root of your project, i.e. where "package.json" lives
 *   root: "../../",
 *
 *   // where to put the JS bundle asset in debug mode
 *   jsBundleDirDebug: "$buildDir/intermediates/assets/debug",
 *
 *   // where to put the JS bundle asset in release mode
 *   jsBundleDirRelease: "$buildDir/intermediates/assets/release",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in debug mode
 *   resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in release mode
 *   resourcesDirRelease: "$buildDir/intermediates/res/merged/release",
 *
 *   // by default the gradle tasks are skipped if none of the JS files or assets change; this means
 *   // that we don't look at files in android/ or ios/ to determine whether the tasks are up to
 *   // date; if you have any other folders that you want to ignore for performance reasons (gradle
 *   // indexes the entire tree), add them here. Alternatively, if you have JS files in android/
 *   // for example, you might want to remove it from here.
 *   inputExcludes: ["android/**", "ios/**"],
 *
 *   // override which node gets called and with what additional arguments
 *   nodeExecutableAndArgs: ["node"],
 *
 *   // supply additional arguments to the packager
 *   extraPackagerArgs: []
 * ]
 */

project.ext.react = [
    enableHermes: false,  // clean and rebuild if changing
]

apply from: "../../node_modules/react-native/react.gradle"
apply from: "../../node_modules/@sentry/react-native/sentry.gradle"

/**
 * Set this to true to create two separate APKs instead of one:
 *   - An APK that only works on ARM devices
 *   - An APK that only works on x86 devices
 * The advantage is the size of the APK is reduced by about 4MB.
 * Upload all the APKs to the Play Store and people will download
 * the correct one based on the CPU architecture of their device.
 */
def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false

/**
 * The preferred build flavor of JavaScriptCore.
 *
 * For example, to use the international variant, you can use:
 * `def jscFlavor = 'org.webkit:android-jsc-intl:+'`
 *
 * The international variant includes ICU i18n library and necessary data
 * allowing to use e.g. `Date.toLocaleString` and `String.localeCompare` that
 * give correct results when using with locales other than en-US.  Note that
 * this variant is about 6MiB larger per architecture than default.
 */
/** def jscFlavor = 'org.webkit:android-jsc:+'
  * NOTE: Replacec with 'org.webkit:android-jsc-intl:+' as intl wasn't working
  */
def jscFlavor = 'org.webkit:android-jsc-intl:+'

/**
 * Whether to enable the Hermes VM.
 *
 * This should be set on project.ext.react and mirrored here.  If it is not set
 * on project.ext.react, JavaScript will not be compiled to Hermes Bytecode
 * and the benefits of using Hermes will therefore be sharply reduced.
 */
def enableHermes = project.ext.react.get("enableHermes", false);

android {
    compileSdkVersion rootProject.ext.compileSdkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        applicationId "com.appName"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
        }
    }
    signingConfigs {
        release {
            if (project.hasProperty('APP_NAME_RELEASE_STORE_FILE')) {
                storeFile file(APP_NAME_RELEASE_STORE_FILE)
                storePassword APP_NAME_RELEASE_STORE_PASSWORD
                keyAlias APP_NAME_RELEASE_KEY_ALIAS
                keyPassword appName_RELEASE_KEY_PASSWORD
            }
        }
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            resValue "string", "app_name", "appName"
            signingConfig signingConfigs.release
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
        // release {
        //     // Caution! In production, you need to generate your own keystore file.
        //     // see https://facebook.github.io/react-native/docs/signed-apk-android.
        //     signingConfig signingConfigs.debug
        //     minifyEnabled enableProguardInReleaseBuilds
        //     proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        // }
    }

    packagingOptions {
        pickFirst "lib/armeabi-v7a/libc++_shared.so"
        pickFirst "lib/arm64-v8a/libc++_shared.so"
        pickFirst "lib/x86/libc++_shared.so"
        pickFirst "lib/x86_64/libc++_shared.so"
    }

    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // https://developer.android.com/studio/build/configure-apk-splits.html
            def versionCodes = ["armeabi-v7a": 1, "x86": 2, "arm64-v8a": 3, "x86_64": 4]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }

        }
    }
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    //noinspection GradleDynamicVersion
    implementation "com.facebook.react:react-native:+"  // From node_modules

    implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.0.0"

    debugImplementation("com.facebook.flipper:flipper:${FLIPPER_VERSION}") {
      exclude group:'com.facebook.fbjni'
    }

    debugImplementation("com.facebook.flipper:flipper-network-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.facebook.flipper'
    }

    debugImplementation("com.facebook.flipper:flipper-fresco-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.facebook.flipper'
    }

    if (enableHermes) {
        def hermesPath = "../../node_modules/hermes-engine/android/";
        debugImplementation files(hermesPath + "hermes-debug.aar")
        releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
        implementation jscFlavor
    }
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)
```

**Comment by Zero-Zheng** [comment]
If you use__ DEV__ , try to disable，in react native 0.62 . Solved my problem。

**Comment by kenobi91** [comment]
I think something is off with react-navigation as app will build if i exclude it from code.

**Comment by chrisglein** [comment]
Sounds like you suspect [react-navigation](https://github.com/react-navigation/react-navigation) is the difference between this working and not. Have you tried seeking support via an issue there? This repo only tracks issues with core, not with community modules.

**Comment by kenobi91** [comment]
Hi @chrisglein yes i found issue, issue was with binded function that returned empty string literal and in release variant that failed.

**Comment by Kailash23** [comment]
**Solution**
In the root of your application.
// Import only in dev mode

```
if (__DEV__) {
  import('./utils/ignoreWarnings');
}
```

Inside utils folder

```
import {LogBox} from 'react-native';

LogBox.ignoreLogs([]);
```
