### ISSUE TITLE
On Android, when debugging, clicking on a clickable does nothing a few times

### ISSUE THREAD

**Issue by kovkev** [facebook/react-native#29083]
## Description
On Android, when debugging, If there is anything clickable, a button, a title bar button, an TouchableOpacity, the clicks don't work for many few times. After a few clicks, the click's action finally works (screen change, function is called, etc..)

## React Native version:
```
info Fetching system and libraries information...
System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 2.83 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 13.3.0 - ~/.nvm/versions/node/v13.3.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.1 - ~/.nvm/versions/node/v13.3.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/lib/ruby/gems/2.7.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.2 - /usr/bin/javac
    Python: 2.7.15 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: ^0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Run the app on Android
2. Use the debugger
3. Click on anything clickable that should trigger an action
4. Click a few more times
5. Click a few more times and finally the action will trigger.

## Expected Results
When I click on something, it should trigger the event/action. It does not

**Comment by chrisglein** [comment]
Can you provide a Snack or a snippet of the clickable content in question?

**Comment by vsheyanov** [comment]
@chrisglein I was going to create a new issue, but seems like this one is exactly that's happening in our projects.

Reproduction repo: https://github.com/vsheyanov/touch-opacity-issue
How it looks on a device (Galaxy S7): https://drive.google.com/file/d/1Pg3nk82TVQjroGHFPfglaNMWwaxcWqpy/view?usp=sharing

It happens only when debugging on 2 Physical Android devices (Galaxy S7 & One Plus 7).

```
const App = () => {
  const onPress = () => {
    Alert.alert('This is an alert');
  };
  return (
    <TouchableOpacity style={{ backgroundColor: 'blue' }} onPress={onPress}>
      <View>
        <Text style={{ color: 'white' }}>Alert is not shown when running on Android device - Galaxy S8</Text>
      </View>
    </TouchableOpacity>
  );
};
```

**Comment by WadhahEssam** [comment]
I confirm this on one plus 6t 

it happend in release build too
