### ISSUE TITLE
iOS: UI will be blocked when show Alert while closing Modal

### ISSUE THREAD

**Issue by teckel12** [facebook/react-native#29082]
Issue #10471 was locked and closed but is still an issue. Only way around it is to use a timeout which is a total hack.

**Comment by teckel12** [comment]
Problem first reported in 2016. Dirty timer work-around only viable "solution".

**Comment by Great-hijack** [comment]
@teckel12 
what do you think about this https://github.com/facebook/react-native/issues/10471#issuecomment-255087481
