### ISSUE TITLE
Fetch API working in postman but not in React-Native App

### ISSUE THREAD

**Issue by riturajpandey** [facebook/react-native#29081]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Fetch API working in postman but not working in a react-native app.

## React Native version:
System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 19.79 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.1 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 23.0.1, 28.0.3, 29.0.2
      System Images: android-25 | Google APIs ARM EABI v7a, android-27 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.4/11E146 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_231 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 

## Steps To Reproduce

1. Try and see API working in postman or in browsers.
2. Same API is not working within react-native app.

## Expected Results

API should work in react-native.

## Snack, code example, screenshot, or link to a repository:
[react-native-code](https://snack.expo.io/@swapaniljain525/react-native-test) even this is working in the web version but not in android or ios.

[node-js-code](https://repl.it/@swapaniljain/Fetch-API) is working with same api.

**Comment by guhungry** [comment]
Is the url happen to be http not the **https**?

- https://android-developers.googleblog.com/2018/04/protecting-users-with-tls-by-default-in.html
- https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW33

**Comment by riturajpandey** [comment]
Hi @guhungry 

I am using [Rapid API](https://rapidapi.com/community/api/manga-eden/endpoints) so it can not be changed from https to HTTP. (I guess).

**Comment by riturajpandey** [comment]
I am having similar issue with image as well.

Image is not displaying with particular uri.pleas have a look into [code](https://snack.expo.io/@swapaniljain525/react-native-snippets)

**Comment by safaiyeh** [comment]
Hi @riturajpandey apologies for the image issues. This is a known bug,

there are workarounds mentioned here: https://github.com/facebook/react-native/issues/28551#issuecomment-678830015
