### ISSUE TITLE
LayoutAnimation + Keyboard bug?

### ISSUE THREAD

**Issue by VictorioMolina** [facebook/react-native#29086]
Hi, I am having a little bug with my app using LayoutAnimation on Android (Samsung Galaxy S8).

Another user reported this error a while ago... (It is exactly the same)
https://github.com/facebook/react-native/issues/26551

Is this an incompatibility with react navigation 5?
Any solution?

It works good on my iOS (iPhone 6)

This is my react native version:

react-native-cli: 2.0.1
react-native: **0.61.4**

Here I explain more widely the problem: https://stackoverflow.com/questions/62244339/react-native-layoutanimation-bug-with-react-navigation

**Comment by bberak** [comment]
For others encountering this problem - take a look at: https://github.com/facebook/react-native/issues/26551#issuecomment-686316279
