### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'process.version.split')

### ISSUE THREAD

**Issue by nihp** [facebook/react-native#29095]
After upgrading the RN to 0.62.2 then it failed and then shows the above **evaluating 'process.version.split'.**

`TypeError: undefined is not an object (evaluating 'process.version.split')`

![Simulator Screen Shot - iPhone 8 - 2020-06-09 at 10 51 42](https://user-images.githubusercontent.com/36992338/84108987-3958bd80-aa3f-11ea-888d-127e3c557560.png)

**Comment by bn185068** [comment]
Any update or action here? Seeing the same issue.
