### ISSUE TITLE
pod install failure with glog 

### ISSUE THREAD

**Issue by genk1** [facebook/react-native#29101]
## Description
I have been trying to start with npx react-native init AwesomeProject but having failure with glog.

<details>
<summary>ERROR LOG</summary>

```
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `Folly` from `../node_modules/react-native/third-party-podspecs/Folly.podspec`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
Downloading dependencies
Installing CocoaAsyncSocket (7.6.4)
Installing CocoaLibEvent (1.0.0)
Installing DoubleConversion (1.1.6)
Installing FBLazyVector (0.62.2)
Installing FBReactNativeSpec (0.62.2)
Installing Flipper (0.33.1)
Installing Flipper-DoubleConversion (1.1.7)
Installing Flipper-Folly (2.2.0)
Installing Flipper-Glog (0.3.6)
[!] /bin/bash -c
set -e
#!/bin/bash
# Copyright (c) Facebook, Inc. and its affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

set -e

PLATFORM_NAME="${PLATFORM_NAME:-iphoneos}"
CURRENT_ARCH="${CURRENT_ARCH}"

if [ -z "$CURRENT_ARCH" ] || [ "$CURRENT_ARCH" == "undefined_arch" ]; then
    # Xcode 10 beta sets CURRENT_ARCH to "undefined_arch", this leads to incorrect linker arg.
    # it's better to rely on platform name as fallback because architecture differs between simulator and device

    if [[ "$PLATFORM_NAME" == *"simulator"* ]]; then
        CURRENT_ARCH="x86_64"
    else
        CURRENT_ARCH="armv7"
    fi
fi

export CC="$(xcrun -find -sdk $PLATFORM_NAME cc) -arch $CURRENT_ARCH -isysroot $(xcrun -sdk $PLATFORM_NAME --show-sdk-path)"
export CXX="$CC"

# Remove automake symlink if it exists
if [ -h "test-driver" ]; then
    rm test-driver
fi

./configure --host arm-apple-darwin

# Fix build for tvOS
cat << EOF >> src/config.h
/* Add in so we have Apple Target Conditionals */
#ifdef __APPLE__
#include <TargetConditionals.h>
#include <Availability.h>
#endif
/* Special configuration for AppleTVOS */
#if TARGET_OS_TV
#undef HAVE_SYSCALL_H
#undef HAVE_SYS_SYSCALL_H
#undef OS_MACOSX
#endif
/* Special configuration for ucontext */
#undef HAVE_UCONTEXT_H
#undef PC_FROM_UCONTEXT
#if defined(__x86_64__)
#define PC_FROM_UCONTEXT uc_mcontext->__ss.__rip
#elif defined(__i386__)
#define PC_FROM_UCONTEXT uc_mcontext->__ss.__eip
#endif
EOF

# Prepare exported header include
EXPORTED_INCLUDE_DIR="exported/glog"
mkdir -p exported/glog
cp -f src/glog/log_severity.h "$EXPORTED_INCLUDE_DIR/"
cp -f src/glog/logging.h "$EXPORTED_INCLUDE_DIR/"
cp -f src/glog/raw_logging.h "$EXPORTED_INCLUDE_DIR/"
cp -f src/glog/stl_logging.h "$EXPORTED_INCLUDE_DIR/"
cp -f src/glog/vlog_is_on.h "$EXPORTED_INCLUDE_DIR/"

checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for arm-apple-darwin-strip... no
checking for strip... strip
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for arm-apple-darwin-gcc... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -arch armv7 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.5.sdk
checking whether the C compiler works... no
/Users/genkiamagata/Library/Caches/CocoaPods/Pods/Release/Flipper-Glog/0.3.6-1dfd6/missing: Unknown `--is-lightweight' option
Try `/Users/genkiamagata/Library/Caches/CocoaPods/Pods/Release/Flipper-Glog/0.3.6-1dfd6/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: in `/Users/genkiamagata/Library/Caches/CocoaPods/Pods/Release/Flipper-Glog/0.3.6-1dfd6':
configure: error: C compiler cannot create executables
See `config.log' for more details
```

</details>

## React Native version:

`npx react-native info`
```
System:
    OS: macOS 10.15.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 1.80 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.16.1 - ~/.anyenv/envs/nodenv/versions/12.16.1/bin/node
    Yarn: 1.22.4 - ~/.anyenv/envs/nodenv/versions/12.16.1/bin/yarn
    npm: 6.13.4 - ~/.anyenv/envs/nodenv/versions/12.16.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 14.0.1 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found
```
`npx react-native --version`
> 4.10.0

`xcrun -k --sdk iphoneos --show-sdk-path`
> /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.5.sdk

`xcode-select --print-path`
> /Applications/Xcode.app/Contents/Developer

my bash_profile 
```bash_profile
export PS1="\W \$"

export PATH="$HOME/.anyenv/bin:$PATH"
eval "$(anyenv init -)"

export PKG_CONFIG_PATH="/usr/local/opt/libxml2/lib/pkgconfig"
export LDFLAGS="/usr/local/opt/libxml2/lib"
export CPPFLAGS="/usr/local/opt/libxml2/include"
export CXXCPP="/usr/bin/cpp"
```

## Steps To Reproduce

1. `npx react-native init AwesomeApp`
2. `error Error: Failed to install CocoaPods dependencies for iOS project, which is required by this template.`
3. `cd ./Awesome/ios && pod install`
4. installation error not fixed.

## What I have tried

1. run comamnd `sudo xcode-select --switch /Applications/Xcode.app`
2. uninstall and install xcode, cocoapods
3. re-creating new projects

Thanks for your help.

**Comment by madeinquant** [comment]
I encounter a same error with javascript but it worked with typescript template. Please feel free to comment.
npx react-native init MyApp --template react-native-template-typescript@next

**Comment by genk1** [comment]
> @genk1, I encounter a same error with javascript but it worked with typescript template. Please feel free to comment.
> npx react-native init MyApp --template react-native-template-typescript@next

Thanks, but that didn't hel[ my problem... did you try anything else??

**Comment by madeinquant** [comment]
It can be fixed before Flipper was used (I am using react-native 0.61.5). It cannot be fixed with 0.63, I modified the  ios-configure-glog.sh with step 4, but it still can't find a modified os-configure-glog.sh. It seems it was cached in someway 


The following method is only apply for  react-native <= 0.61.5, without Flipper
=============================================================
1. You are staying in the project directory 
2. cd node_modules/react-native/scripts
3. vi ios-configure-glog.sh
4. Add these two lines and command the original c compiler directory.
    export CC=/usr/local/Cellar/gcc/10.1.0/bin/gcc-10
    export CXX=/usr/local/Cellar/gcc/10.1.0/bin/g++-10

    #export CC="$(xcrun -find -sdk $PLATFORM_NAME cc) -arch $CURRENT_ARCH -isysroot $(xcrun -sdk $PLATFORM_NAME --show-sdk-path)"
    #export CXX="$CC"

**Comment by daviditsygin** [comment]
I googled this for hours and tried every solution including the one above, but I was finally able to fix it by doing 

`git config --global core.autocrlf false`

and then running `pod install` again

**Comment by nnphuong9718** [comment]
> I googled this for hours and tried every solution including the one above, but I was finally able to fix it by doing
> 
> `git config --global core.autocrlf false`
> 
> and then running `pod install` again

you are my sunshine, you saved my life.

**Comment by zayedelfasa** [comment]
> I googled this for hours and tried every solution including the one above, but I was finally able to fix it by doing
> 
> `git config --global core.autocrlf false`
> 
> and then running `pod install` again

Paradise waiting for you brother! You save my life too!

**Comment by safaiyeh** [comment]
> I googled this for hours and tried every solution including the one above, but I was finally able to fix it by doing
> 
> `git config --global core.autocrlf false`
> 
> and then running `pod install` again

Thanks for the solution!

**Comment by tmaly1980** [comment]
None of these work for me. Any suggestions?

**Comment by vaibhavmittal5** [comment]
run cmd -- sudo xcode-select --switch /Applications/Xcode.app
then try -- pod install

**Comment by smecnarowski** [comment]
Clone of: https://github.com/react-native-community/cli/issues/1194
