### ISSUE TITLE
[iOS] Caps lock native icon keeps being shown despite the caps are disabled

### ISSUE THREAD

**Issue by federicomiralles** [facebook/react-native#29108]
## Description
Native iOS caps lock icon is displayed even though caps are disabled as shown below highlighted in red:
![Simulator Screen Shot - iPhone 11 - 2020-06-10 at 17 31 27](https://user-images.githubusercontent.com/53195495/84315747-82dd0180-ab40-11ea-8c96-4ab5b3a2f64f.png)

## React Native version:
0.62.2

## Steps To Reproduce
You can reproduce the issue following the next steps on the code provided below...

1. Tap on the password text input
2. As soon as the soft keyboard is displayed double tap the caps key to lock it
3. Then tap on the button that says **Show pass** to show the typed in password
4. Disable caps by taping once again on the caps key in the soft-keyboard
5. Caps lock icon remains shown even though it's disabled

## Expected Results
Caps lock icon should not be shown if caps are not enabled

## Snack, code example, screenshot, or link to a repository:
```
import React, {useState} from 'react';
import {TextInput, StyleSheet, View, Button} from 'react-native';

declare const global: {HermesInternal: null | {}};

const App = () => {
  const [value, setValue] = useState('');
  const [secureTextEntry, setSecureTextEntry] = useState(true);

  return (
    <View style={styles.container}>
      <View style={styles.row}>
        <TextInput
          style={styles.input}
          value={value}
          onChangeText={(text) => setValue(text)}
          secureTextEntry={secureTextEntry}
        />
        <Button
          title={secureTextEntry ? 'Show pass' : 'Hide pass'}
          onPress={() => setSecureTextEntry(!secureTextEntry)}
        />
      </View>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  input: {
    flex: 1,
    borderColor: 'grey',
    borderWidth: 2,
    borderRadius: 5,
    padding: 10,
    color: 'black',
  },
});

export default App;
```

**Comment by pybuche** [comment]
Any update on this?

**Comment by ammarRajabA** [comment]
Any way to resolve this ? @federicomiralles

**Comment by federicomiralles** [comment]
> Any way to resolve this ? @federicomiralles

Unfortunately I couldn't find any so far
