### ISSUE TITLE
Linking.openURL(url) is not working on iOS (Trying to open Whatsapp)

### ISSUE THREAD

**Issue by sebackend** [facebook/react-native#29119]
I'm kind of stuck with this problem, sorry if this issue is not descriptive at all, but i need to find at least an idea where the problem comes from.

## Description
For some reason, the linking feature to open a whatsapp contact is not working on iOS, i followed the guide on this url for the setup https://reactnative.dev/docs/linking but always when i try to push the button that calls to whatsapp app to write a message directly, the app says something like

_Could not open this link, please review it and try again_

![IMG-20200611-WA0000](https://user-images.githubusercontent.com/14254060/84435541-fdb92180-abff-11ea-9325-85e5d09b9860.jpg)

The button for open whatsapp is this
```javascript
openWhatsappUrl = () => {
    const url = 'whatsapp://send?phone=+XXXXXXXXXXX';
    Linking.canOpenURL(url).then((supported) => {
      if (supported) {
        Linking.openURL(url);
      } else {
        Alert.alert(
          'Alert',
          'WhatsApp is not installed',
        );
      }
    });
  };

// This is on the render section from my screen
<DefaultButton
   title="¡Say Hi!"
   containerStyles={styles.centeredButton}
   onPress={() => this.openWhatsappUrl()}
/>
```
The AppDelegate.m file has this configuration
``` swift
#import <React/RCTLinkingManager.h>
...
- (BOOL)application:(UIApplication *)application
   openURL:(NSURL *)url
   options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{
  return [RCTLinkingManager application:application openURL:url options:options];
}
```

The Info.plist file
``` xml
<key>LSApplicationQueriesSchemes</key>
    <array>
         <string>whatsapp</string>
         <string>fbapi</string>
	 <string>fb-messenger-share-api</string>
         <string>fbauth2</string>
	 <string>fbshareextension</string>
    </array>
```

## React Native version:
System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
    Memory: 24.91 MB / 8.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.22.0 - ~/.yarn/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28, 29
      Build Tools: 23.0.1, 25.0.2, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.0, 28.0.1, 28.0.2, 28.0.3, 29.0.2
      System Images: android-26 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.0 AI-171.4408382
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.5 => 0.60.5
  npmGlobalPackages:
    create-react-native-app: 2.0.2
    react-native-cli: 2.0.1

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Follow the linking instructions from https://reactnative.dev/docs/linking
2. Add some button to call the same action in the onPress prop (With custom cellphone number)
3. Run the app and press the button

## Expected Results
I need to see the contact number on whatsapp to sending a message directly.

**Comment by sebackend** [comment]
Any idea?

**Comment by sebackend** [comment]
Solved!!!! by removing the plus sign from the phone number :o

**Comment by maxmanager** [comment]
tnks!!!

**Comment by mirshanv** [comment]
thanks dude :)
