### ISSUE TITLE
react key prop not working, still have "Each child in a list should have a unique "key" prop."

### ISSUE THREAD

**Issue by Majdewave** [facebook/react-native#29115]
i need help plz , 
this is my attached code : 
[New Text Document.txt](https://github.com/facebook/react-native/files/4765910/New.Text.Document.txt)

**Comment by jupmorenor** [comment]
This is react-native repo

**Comment by kiranjd** [comment]
Whatever you JSX you map needs an id. In this case, you are mapping the `Loader` as well which is missing the id.
It's better to map over your items only when loading is completed. That would uncomplicate things

**Comment by Majdewave** [comment]
thank you :)

**Comment by kiranjd** [comment]
@Majdewave Would you mind closing this issue if your issue is resolved?
