### ISSUE TITLE
[Android] press submit TextInput crashes the app with no error in log

### ISSUE THREAD

**Issue by mattiamanzati** [facebook/react-native#2911]
Hi all,
I have a TextInput that if I press the android submit button make crash my app.
(I event removed every property and just left it as <TextInput style={...} /> to try if it was a event handler bug, but the app still crashes)
On iOS the input works fine with no errors, and on android gives no error in the console.
How can I fix this? is this a known bug?
If that would help, I can give you my app sources.
![Error gif](http://zippy.gfycat.com/SparklingIgnorantFugu.gif)

**Comment by andreicoman11** [comment]
On android, if the app crashes, the logs will be in adb logcat. This is explained in [Getting Started/To run the Android app](http://facebook.github.io/react-native/docs/getting-started.html#quick-start).
Can you submit the error message from there and maybe a small example where this would crash?

**Comment by mattiamanzati** [comment]
Sorry, but I am not an android expert, and sorry for that because maybe it's just an error of mine, this is the error and a link to a gist with a sample project with the error.

https://gist.github.com/mattiamanzati/3dda55ae4b59cf6b9a5e

I/Vold    (  322): [LGE][VOLD][NetlinkHandler.cpp][onEvent()] subsys:cpu, action:0
V/WifiServiceExtension(  671): checkPollTimer Cnt= 0 rssi =-68 threshold=-100
V/AudioPolicyService(  333): getRingerMode() mRingerMode:1
V/AudioPolicyService(  333): getPhoneState() mode : 0
W/SoundPool( 1348): Do NOT play soundpool with system stream neither normal mode nor incall
I/ViewRootImpl( 1348): ViewRoot's Touch Event : Touch Down
I/ViewRootImpl( 1348): ViewRoot's Touch Event : Touch UP
E/View    ( 9983): hasTransientState decremented below 0: unmatched pair of setHasTransientState calls
D/AndroidRuntime( 9983): Shutting down VM
W/dalvikvm( 9983): threadid=1: thread exiting with uncaught exception (group=0x41abce48)
E/AndroidRuntime( 9983): FATAL EXCEPTION: main
E/AndroidRuntime( 9983): Process: com.demoerror, PID: 9983
E/AndroidRuntime( 9983): java.lang.IllegalStateException: focus search returned a view that wasn't able to take focus!
E/AndroidRuntime( 9983): 	at android.widget.TextView.onEditorAction(TextView.java:4410)
E/AndroidRuntime( 9983): 	at com.android.internal.widget.EditableInputConnection.performEditorAction(EditableInputConnection.java:138)
E/AndroidRuntime( 9983): 	at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:297)
E/AndroidRuntime( 9983): 	at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:77)
E/AndroidRuntime( 9983): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 9983): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 9983): 	at android.app.ActivityThread.main(ActivityThread.java:5103)
E/AndroidRuntime( 9983): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 9983): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 9983): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
E/AndroidRuntime( 9983): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:606)
E/AndroidRuntime( 9983): 	at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager(  671):   Force finishing activity com.demoerror/.MainActivity
V/ActivityManager(  671): Moving to PAUSING: ActivityRecord{42c002c0 u0 com.demoerror/.MainActivity t7 f}
I/Vold    (  322): [LGE][VOLD][NetlinkHandler.cpp][onEvent()] subsys:cpu, action:0
D/dalvikvm(  671): GC_FOR_ALLOC freed 2003K, 17% free 19780K/23612K, paused 136ms, total 138ms
D/dalvikvm(  671): GC_FOR_ALLOC freed 88K, 16% free 19918K/23612K, paused 116ms, total 116ms
I/dalvikvm-heap(  671): Grow heap (frag case) to 21.887MB for 214528-byte allocation
I/SystemUI(  671): PhoneWindowManager.updateSystemUiVisibilityLw() :
I/SystemUI(  671): visibility=0x0, pkg=android
D/WifiStateMachine(  671): handleMessage: E msg.what=131155
D/WifiStateMachine(  671): processMsg: ConnectedState
D/WifiStateMachine(  671): processMsg: L2ConnectedState
D/WifiNative-wlan0(  671): doString: SIGNAL_POLL
D/wpa_supplicant( 8430): RX ctrl_iface - hexdump(len=11): 53 49 47 4e 41 4c 5f 50 4f 4c 4c

**Comment by andreicoman11** [comment]
This was fixed last week, it's a one line change https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactTextInputManager.java#L102

**Comment by brentvatne** [comment]
Nice @andreicoman11 :+1:

**Comment by benwicks** [comment]
What was the change that fixed this? The above link references a line that has changed

**Comment by smart-fun** [comment]
@benwicks I think it was:
editText.setImeOptions(EditorInfo.IME_ACTION_DONE);
taken from Commits on Sep 17, 2015
Line 102
