### ISSUE TITLE
[Fetch] network request is slow on Android with 4G network when integrate into an exist app 

### ISSUE THREAD

**Issue by KingAmo** [facebook/react-native#29129]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
i am integrate RN into an exist Android project, and when open a RN activity, the initial network request is slow，fetch api is called, but it seems need more than 30 second to **really** send the request by `okhttp`, but after initialized the network request is really fast, i guess the okhttp delay the request on 4G network;  or when in 4G network, it need more time to initialize `okhttp`; 

btw, with wifi network condition, everything is just fine 

refrence: https://medium.com/dailyjs/network-layer-in-react-native-eec841f11861
## React Native version:
Run `react-native info` in your terminal and copy the results here.
```
System:
    OS: macOS 10.15.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 206.92 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.12.0 - /usr/local/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 21, 23, 26, 27, 28
      Build Tools: 23.0.1, 26.0.1, 26.0.2, 28.0.3, 29.0.2
      System Images: android-28 | Google Play Intel x86 Atom, android-R | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_212 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.
2.

## Expected Results
when integrate RN to exist project, network request do not delay when initialize RN activity on HuaWei device 

## Snack, code example, screenshot, or link to a repository:
Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by KingAmo** [comment]
it seem that this happens only in HuaWei or Honor in android 10

**Comment by KingAmo** [comment]
we have received a lot of user feedback that described like above; and i have tested on about 10 android device , and 4 are android 10, they all have this issue;  2 are android 9, and one of them have this issue; others are bellow android 10, and they are all fine

**Comment by KingAmo** [comment]
seems happened more common on HuaWei device

**Comment by buccinator** [comment]
can confirm this is an issue on android 9, 10, 11 on wifi or data

makes many small requests compared to other android versions eg. 7

downloading large videos is far slower, on android 7 a 50mb file can make 3 requests and on android 9+ about 15 requests

**Comment by ashokkumar88** [comment]
@buccinator Did you find any work around?

**Comment by buccinator** [comment]
> @buccinator Did you find any work around?

used exoplayer instead of native android player

**Comment by ashokkumar88** [comment]
I added AAAA records to my DNS zone and it is working fine now.

**Comment by bmbmjmdm** [comment]
this is still an issue

**Comment by Zarpen** [comment]
Yes, fetch do not behave correctly in all situations
