### ISSUE TITLE
[iOS] RN 0.62.2 fails to build: RCTConvert.h: 'yoga/Yoga.h' file not found

### ISSUE THREAD

**Issue by rahamin1** [facebook/react-native#29124]
## Description
I am using Xcode 11.3 on macOS Catalina (10.15.4), react-native 0.62.2 (upgraded from 0.59.9), and getting this error when I try to build.

## React Native version:
```
System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz
    Memory: 5.49 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.16.2 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
```

### The import statement in RCTConvert.h:

    #import <yoga/Yoga.h>

### Files' locations

     ./node_modules/react-native/React/Base/RCTConvert.h
     ./node_modules/react-native/ReactCommon/yoga/yoga/Yoga.h

### Build settings -> Header Search Path

As you can see below, I tried to add the yoga directory. Didn't help.

[![Build settings -> Header Search Path][1]][1]
### This is my podfile:

    platform :ios, '11.0'
    
    target 'xxx' do
      # Comment the next line if you don't want to use dynamic frameworks
      use_frameworks!
    
      permissions_path = '../node_modules/react-native-permissions/ios'
    
      pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
      pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
      pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
      pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
      pod 'React', :path => '../node_modules/react-native/'
      pod 'React-Core', :path => '../node_modules/react-native/'
      pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
      pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
    
      pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
      pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
      pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
      pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
      pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
      pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
      pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
      pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
      pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
      pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'
      pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
      pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
      pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
      pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
      pod 'ReactCommon/callinvoker', :path => "../node_modules/react-native/ReactCommon"
      pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
    
      pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga', :modular_headers => true
      pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
      pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
      pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
    
      # Pods for xxx
      pod 'RNSquareInAppPayments', :path => '../node_modules/react-native-square-in-app-payments'
      pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
      pod 'react-native-nfc-manager', :path => '../node_modules/react-native-nfc-manager'
    
      target 'xxxTests' do
        inherit! :search_paths
        # Pods for testing
      end
    
    end
    
    target 'xxx-tvOS' do
      # Comment the next line if you don't want to use dynamic frameworks
      use_frameworks!
    
      # Pods for xxx-tvOS
    
      target 'xxx-tvOSTests' do
        inherit! :search_paths
        # Pods for testing
      end
    
    end

  [1]: https://i.stack.imgur.com/zeV19.png

**Comment by pedrohsreis** [comment]
I'm facing the same issue

**Comment by rahamin1** [comment]
Since I couldn't solve the problem, I started a new project in RN 0.62.2, and copied my files over.
I didn't get the error any more.

**Comment by olkunmustafa** [comment]
I faced the same issue RN 0.62.2 I tried many ways but I could not solve the issue. Now I am trying to create a new react Native project and try to copy my files. I will write after I complete.
