### ISSUE TITLE
Type annotations can only be used in TypeScript files.ts(8010) on React-Native CLI Startup

### ISSUE THREAD

**Issue by KelvnPere** [facebook/react-native#29123]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
I have created like 2 starter project in ReactNative using **npx react-native init [projectName]**, and that error in the title always comes with the starter code, precisely on line 27.  

## React Native version:
System:
    OS: Windows 10 10.0.18362
    CPU: (2) x64 Intel(R) Celeron(R) 2957U @ 1.40GHz
    Memory: 1.76 GB / 7.89 GB
  Binaries:
    Node: 12.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6392135
  Languages:
    Java: javac 12
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Create a new react native project
2. Open the starter code from any editor, i use VScode.
3. Go to App.js and scroll to line 27.
4. Hold on a little bit then the error would occur. 

## Expected Results 
   Since it is a starter code from the react-native team, which helps new developers to understand the codebase and how it works, that error should not be there. It can scare a new developer coming into ReactNative. 

## Snack, code example, screenshot, or link to a repository:
![react_errorr](https://user-images.githubusercontent.com/36895007/84487283-6eab1880-ac96-11ea-87e5-7c5e886d11ea.PNG)

**Comment by rkratnesh852** [comment]
Getting same issue ....
![Screenshot from 2020-06-15 12-57-20](https://user-images.githubusercontent.com/35485762/84629531-17ac7a00-af08-11ea-97aa-4d6bb5cabd56.png)

**Comment by rkratnesh852** [comment]
https://stackoverflow.com/questions/48859169/js-types-can-only-be-used-in-a-ts-file-visual-studio-code-using-ts-check

**Comment by ecreeth** [comment]
:100:  This can be closed now. The answer is correct!

**Comment by safaiyeh** [comment]
Hi all the reason for this is that React Native template ships with a flow config. This error is a result of your VSCode plugins not working playing well with flow.



> https://stackoverflow.com/questions/48859169/js-types-can-only-be-used-in-a-ts-file-visual-studio-code-using-ts-check

This should help you resolve the error!

**Comment by luojinghui** [comment]
Use "javascript.validate.enable": false in your VS Code settings.

**Comment by khaja-nizamuddin1** [comment]
https://stackoverflow.com/a/50726464/7344761

This worked for me ..quick fix!!
Simply go to VS Code >>File>>Preferences>>Settings >> go to javascript(or search javascript and scroll down)>validate> enable/disable >>disable or uncheck

**Comment by dmassissa** [comment]
i use this link and help me fix this issues 
**https://www.youtube.com/watch?v=UQV2HMQZK4o** 

or  this but is some video 

https://www.facebook.com/watch/?v=2782095745399197&extid=T54ZcHrD4BPCy62c

**Comment by kohenchia** [comment]
Disabling syntax validation is not a fix. Just because you don't see the red squiggly doesn't mean it's fixed - it's just not running at all. Your code quality will be worse for it.

**Comment by sebazelonka** [comment]
@kohenchia  I agree with you, this works for me because I only want to try something in a very clean environment, but is not a solution at all.

**Comment by xsubject** [comment]
```js
const App = () => {
  return (
  // ...
```

**Comment by lordliquid** [comment]
My issue was node_module files had Typescript code in .js files. The error squiggles were getting annoying. 
This was my solution. 
I made VS Code associate all .js and .ts extensions as TS / React  ( I didn't have to change any other settings ):

By adding this to the settings.json:

```javascript
"files.associations": {
    "*.js": "typescriptreact",
    "*.jsx": "typescriptreact",
    "*.tsx": "typescriptreact",
    "*.ts": "typescriptreact"
}, 
```

**Comment by TheEhsanSarshar** [comment]
this issue still exists for `tsx` files.
maybe there is some conflicts between eslint and typescript

**Comment by ionansantos** [comment]
![Captura de Tela (9)](https://user-images.githubusercontent.com/69859498/121110028-01679000-c7e3-11eb-84bf-96a94d450ecd.png)
 alguem sabe como resolver?

**Comment by GZBland** [comment]
Vai na área de Extensões do VS Code e pesquisa
@builtin TypeScript and JavaScript Language Features
Após isso clique em Desabilitar.

Isso é o intelliSense que autocorrige o código, como os erros gerados são coisas de TypeScript e vc esta em um JavaScript da isso mesmo. só desligando a inteligência para não ter o erro. porem não tem como auto completar o código.
