### ISSUE TITLE
'backgroundColor' is not supported by native animated module 

### ISSUE THREAD

**Issue by kelvin-dev** [facebook/react-native#29139]
Please help support below feature in next release
'backgroundColor' is not supported by native animated module 
Thanks team

**Comment by ssssssssssss** [comment]
As FB is working on Fabric, I think they are not in favor of implementing this feature. You may check this PR out if you are interested in roll your own. https://github.com/facebook/react-native/pull/18187

**Comment by kelvin-dev** [comment]
> As FB is working on Fabric, I think they are not in favor of implementing this feature. You may check this PR out if you are interested in roll your own. #18187
 
2 years passed, we needa a real built-in feature, the ownership that helps minimize the scope of testings and productivity
