### ISSUE TITLE
problems with StatusBar and SYSTEM_UI_FLAG_IMMERSIVE_STICKY 

### ISSUE THREAD

**Issue by luigbren** [facebook/react-native#29132]
I have configured the Inmmersive as follows:
```
package com.myapp;

import com.facebook.react.ReactActivity;
import android.os.Bundle;
import android.view.View;

public class MainActivity extends ReactActivity {

  /**
   * Returns the name of the main component registered from JavaScript. This is used to schedule
   * rendering of the component.
   */
  @Override
  protected String getMainComponentName() {
    return "MyApp";
  }
  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    hideNavigationBar();
  }

  @Override
  public void onWindowFocusChanged(boolean hasFocus) {
    super.onWindowFocusChanged(hasFocus);
    if (hasFocus) {
      hideNavigationBar();
    }
  }

  private void hideNavigationBar() {
    getWindow().getDecorView()
        .setSystemUiVisibility(View.SYSTEM_UI_FLAG_HIDE_NAVIGATION | View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY);
  }
}

```

When I start the App the interface works fine, it hides the lower android buttons, but! if I configure the colors of the Status bar, either from the App.js or the browser container

```
App.js
......
import { StatusBar } from 'react-native';
StatusBar.setBackgroundColor("#ffffff") // BackGround White!
StatusBar.setBarStyle("dark-content")  // Color Text in Black
StatusBar.setTranslucent(false)
......
```

```
or by Navigation Config..

const BaseAppStack = createStackNavigator();
export function BaseAppStackScreen(props) {
  return (
    <NavigationContainer  >
      <StatusBar barStyle="dark-content" backgroundColor="#ffffff" translucent={false} />
      <BaseAppStack.Navigator headerMode="none" initialRouteName="BaseTabs">
        <BaseAppStack.Screen
          name="BaseTabs"
          component={BaseTabs}
          options={{ headerShown: false, ...TransitionPresets.SlideFromRightIOS }}
        />
      ........
      </BaseAppStack.Navigator>
    </NavigationContainer>
  );
}
```
When I turn off the screen with the app open, or lower the notification bar, or minimize the application and open again, or run a modal, and then I do some of those things and then the app is shown again (focus), the Status bar puts the font color in white, so it resets StatusBar! to the default colors text (White), after that problem happens, the StatusBar remains in white background color (my configuration) and the White Text color (default), I have to close the app and open it again

"react-native": "0.61.5"

**Comment by draggie** [comment]
I also have experienced this on Android, RN 0.63.1

**Comment by sherlinshaji** [comment]
When I turn off the screen with the app open, or lower the notification bar, or minimize the application and open again, my header height is changing

**Comment by mrbrentkelly** [comment]
I'm also hitting a similar issue...

I have a bridge module for hiding the Status Bar and Bottom Navigation bar on Android. Hiding works great but when showing the status bar and navigation bar again, it appears like the status bar remains hidden... 

The issue is that the StatusBar text color is getting set to white on a white background (whereas before hiding the StatusBar the text color was set to black).

My workaround is to configure the StatusBar again as soon as I exit immersive mode...

```TypeScript
// Hide StatusBar and bottom navigation controls (i.e. go immersive)
SomeBridgeModule.hideStatusAndNavBar();

// Show StatusBar and bottom navigation controls (i.e. exit immersive)
SomeBridgeModule.showStatusAndNavBar();
StatusBar.setBackgroundColor('white');
StatusBar.setBarStyle('dark-content');
```

**Comment by Minishlink** [comment]
@mrbrentkelly As a curiosity, does your bridge module that hides the bottom navigation bar works in a modal? Thanks

**Comment by mrbrentkelly** [comment]
Yes (I think 😄 ). You could try and see. Here's my library https://github.com/hudl/react-native-system-bars#react-native-android-system-bars

**Comment by Minishlink** [comment]
@mrbrentkelly Thanks :) It kind of works with modals, something like 2 out 3 times, so there must be a race condition in RN code somewhere (around there #21078)
Might also be related to the problems in this issue
