### ISSUE TITLE
[iOS] AppDelegate.m: 'FlipperKit/FlipperClient.h' file not found

### ISSUE THREAD

**Issue by rahamin1** [facebook/react-native#29133]
## This is what I did:
- Created a new project using react-native 0.62.2 (I had many other problems after upgrading from 0.59.9)
- Copied my source to the new project
- Build failed with the following error:

`/Users/user172615/Documents/new-rn62/plumpPlum/ios/plumpPlum/AppDelegate.m:10:9: 'FlipperKit/FlipperClient.h' file not found`

- Copied `Post Install processing for Flipper` from https://github.com/facebook/react-native/issues/28406#issuecomment-604907817
- Build still gives the same error
- Podfile and AppDelegate.m are attached below

## React Native version:

```
System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz
    Memory: 3.20 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.16.2 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  Languages:
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 

```

## Podfile

```
#import "AppDelegate.h"

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>

@import SquareReaderSDK;

#if DEBUG
#import <FlipperKit/FlipperClient.h>
#import <FlipperKitLayoutPlugin/FlipperKitLayoutPlugin.h>
#import <FlipperKitUserDefaultsPlugin/FKUserDefaultsPlugin.h>
#import <FlipperKitNetworkPlugin/FlipperKitNetworkPlugin.h>
#import <SKIOSNetworkPlugin/SKIOSNetworkAdapter.h>
#import <FlipperKitReactPlugin/FlipperKitReactPlugin.h>

static void InitializeFlipper(UIApplication *application) {
  FlipperClient *client = [FlipperClient sharedClient];
  SKDescriptorMapper *layoutDescriptorMapper = [[SKDescriptorMapper alloc] initWithDefaults];
  [client addPlugin:[[FlipperKitLayoutPlugin alloc] initWithRootNode:application withDescriptorMapper:layoutDescriptorMapper]];
  [client addPlugin:[[FKUserDefaultsPlugin alloc] initWithSuiteName:nil]];
  [client addPlugin:[FlipperKitReactPlugin new]];
  [client addPlugin:[[FlipperKitNetworkPlugin alloc] initWithNetworkAdapter:[SKIOSNetworkAdapter new]]];
  [client start];
}
#endif

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
#if DEBUG
  InitializeFlipper(application);
#endif

  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"plumpPlum"
                                            initialProperties:nil];

  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  [SQRDReaderSDK initializeWithApplicationLaunchOptions:launchOptions];
  return YES;
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

@end
```

### AppDelegate.m

```
#import "AppDelegate.h"

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>

@import SquareReaderSDK;

#if DEBUG
#import <FlipperKit/FlipperClient.h>
#import <FlipperKitLayoutPlugin/FlipperKitLayoutPlugin.h>
#import <FlipperKitUserDefaultsPlugin/FKUserDefaultsPlugin.h>
#import <FlipperKitNetworkPlugin/FlipperKitNetworkPlugin.h>
#import <SKIOSNetworkPlugin/SKIOSNetworkAdapter.h>
#import <FlipperKitReactPlugin/FlipperKitReactPlugin.h>

static void InitializeFlipper(UIApplication *application) {
  FlipperClient *client = [FlipperClient sharedClient];
  SKDescriptorMapper *layoutDescriptorMapper = [[SKDescriptorMapper alloc] initWithDefaults];
  [client addPlugin:[[FlipperKitLayoutPlugin alloc] initWithRootNode:application withDescriptorMapper:layoutDescriptorMapper]];
  [client addPlugin:[[FKUserDefaultsPlugin alloc] initWithSuiteName:nil]];
  [client addPlugin:[FlipperKitReactPlugin new]];
  [client addPlugin:[[FlipperKitNetworkPlugin alloc] initWithNetworkAdapter:[SKIOSNetworkAdapter new]]];
  [client start];
}
#endif

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
#if DEBUG
  InitializeFlipper(application);
#endif

  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"plumpPlum"
                                            initialProperties:nil];

  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  [SQRDReaderSDK initializeWithApplicationLaunchOptions:launchOptions];
  return YES;
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

@end
```

**Comment by timjuenemann** [comment]
@rahamin1 You pasted the AppDelegate.m instead of the Podfile. Could you fix that?

I had the same error, because I forgot to add `add_flipper_pods!` before `post_install do |installer|`. Maybe that'll fix yours too.

**Comment by rahamin1** [comment]
Hmmm... Right.
I made so many changes since then and the error is gone, so I don't have the file which caused the error. If it happens again, I will reopen this issue.

**Comment by jafar-jabr** [comment]
errors come and go randomly in xcode ^_*

**Comment by sanjeevkse** [comment]
I am facing the issue.

**Comment by renanxd25** [comment]
> Estou enfrentando o problema.
> <img alt="Captura de tela 2021-04-28 às 5 51 07 PM" width="1037" src="https://user-images.githubusercontent.com/4029801/116402804-7641c480-a84a-11eb-89ad-3740a65d0e1a.png">
> 
> Eu até habilitei o flipper.
> <img alt="Captura de tela 2021-04-28 às 5 52 30 PM" width="496" src="https://user-images.githubusercontent.com/4029801/116402848-822d8680-a84a-11eb-948a-ad49d57dced2.png">
> 
> Por favor me ajude.

Managed to solve? I have the same problem

**Comment by sanjeevkse** [comment]
> > Estou enfrentando o problema.
> > <img alt="Captura de tela 2021-04-28 às 5 51 07 PM" width="1037" src="https://user-images.githubusercontent.com/4029801/116402804-7641c480-a84a-11eb-89ad-3740a65d0e1a.png">
> > Eu até habilitei o flipper.
> > <img alt="Captura de tela 2021-04-28 às 5 52 30 PM" width="496" src="https://user-images.githubusercontent.com/4029801/116402848-822d8680-a84a-11eb-948a-ad49d57dced2.png">
> > Por favor me ajude.
> 
> Managed to solve? I have the same problem

No, Not able to. I am trying.

**Comment by renanxd25** [comment]
> > > Estou enfrentando o problema.
> > > <img alt="Captura de tela 2021-04-28 às 5 51 07 PM" width="1037" src="https://user-images.githubusercontent.com/4029801/116402804-7641c480-a84a-11eb-89ad-3740a65d0e1a.png">
> > > Eu até habilitei o flipper.
> > > <img alt="Captura de tela 2021-04-28 às 5 52 30 PM" width="496" src="https://user-images.githubusercontent.com/4029801/116402848-822d8680-a84a-11eb-948a-ad49d57dced2.png">
> > > Por favor me ajude.
> > 
> > 
> > Managed to solve? I have the same problem
> 
> No, Not able to. I am trying.

figured out how to fix the error. . I wish it works for you !=) 
Comment out these lines of your code
// AppDelegate.m

// Comment out Flipper.
...
//#import <FlipperKit/FlipperClient.h>
//#import <FlipperKitLayoutPlugin/FlipperKitLayoutPlugin.h>
//#import <FlipperKitUserDefaultsPlugin/FKUserDefaultsPlugin.h>
//#import <FlipperKitNetworkPlugin/FlipperKitNetworkPlugin.h>
//#import <SKIOSNetworkPlugin/SKIOSNetworkAdapter.h>
//#import <FlipperKitReactPlugin/FlipperKitReactPlugin.h>
...

//static void InitializeFlipper(UIApplication *application) {
//  FlipperClient *client = [FlipperClient sharedClient];
//  SKDescriptorMapper *layoutDescriptorMapper = [[SKDescriptorMapper alloc] initWithDefaults];
//  [client addPlugin:[[FlipperKitLayoutPlugin alloc] initWithRootNode:application withDescriptorMapper:layoutDescriptorMapper]];
//  [client addPlugin:[[FKUserDefaultsPlugin alloc] initWithSuiteName:nil]];
//  [client addPlugin:[FlipperKitReactPlugin new]];
//  [client addPlugin:[[FlipperKitNetworkPlugin alloc] initWithNetworkAdapter:[SKIOSNetworkAdapter new]]];
//  [client start];
//}

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
...
//#ifdef FB_SONARKIT_ENABLED
//  InitializeFlipper(application);
//#endif
...
}

**Comment by sanjeevkse** [comment]
> * didFinishLaunchingWithOptions

Thanks, it worked. :)

But I am facing `linker command failed with exit code 1 (use -v to see invocation)` now, Its a different issue i think related to Google Analytics. Let me fix it. 

But Thanks for the reply. It worked for me.

**Comment by Ciberusps** [comment]
In my case just switching to 0.95.0 helped
```
use_flipper!({ 'Flipper' => '0.95.0' }) # should match the version of your Flipper client app
```
