### ISSUE TITLE
Auth-Session not persisted on iOS after closing app

### ISSUE THREAD

**Issue by emmanuel-D** [facebook/react-native#29134]
I am using:
- SDK Version: 36.0.0
- Platforms(Android/iOS)

I have builded a simple server with [Spring Security](https://spring.io/guides/gs/securing-web/) that provides a **Basic Auth** via a REST-API for my **Expo Standalone app**.

- On **Android**, after successfully login the session is persisted, even if I close the app and reopen it. Also after app-updates, the session is still available and the server can authorize me access the ressources. So all here works well (It is the same case on browser).

- But on **iOS**, after successfully login a first time, the server authozire me access the ressources as long as the app is not closed. After I close the app and immediately reopen it, the session disappears and I must login again.

I am not understanding what is not working on **iOS**. Maybe the **cookies** are deleted each times ?
I would like to release the first version of the app, but the **iOS** behaviour does not allow me now.

**Comment by ssssssssssss** [comment]
https://github.com/react-native-community/cookies 
Cookies to the rescue.

**Comment by hbendix** [comment]
Same issue here with Expo. I posted on the Expo GitHub [here](https://github.com/expo/expo/issues/9213).

**Comment by dulmandakh** [comment]
Closing the issue because this issue tracker is intended to track React Native issues, but your issue is related to Expo only features.

**Comment by brentvatne** [comment]
@dulmandakh - i think this actually relates to the default functionality of cookie persistence in react-native core, does it not?

**Comment by douglasjunior** [comment]
Same issue here with a bare react-native app `0.64.0`.

Cookies are persisted on Android, but not on iOS.

Even if a set the cookie manually on the request with axios.

**Comment by roots-ai** [comment]
Any resolution to this?
Also, using https://github.com/react-native-community/cookies is resetting the cookies on some post requests.
