### ISSUE TITLE
setInterval has a bug?

### ISSUE THREAD

**Issue by CHANCCCZQ** [facebook/react-native#29149]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Please provide a clear and concise description of what the bug is. Include screenshots if needed.
Please test using the latest React Native release to make sure your issue has not already been fixed: https://reactnative.dev/docs/upgrading.html

The timer that runs once a second becomes four to five seconds

![image](https://user-images.githubusercontent.com/22274839/84733590-3c205900-afd1-11ea-95e2-2b3d8d126126.png)

## React Native version:
Run `react-native info` in your terminal and copy the results here.
0.62.2
## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.useEffect to set a interval
2. console.log for output each callback

this is another way
```
const useInterval = (callback, delay) => {
  const savedCallback = useRef();

  useEffect(() => {
    savedCallback.current = callback;
  });
  useEffect(() => {
    function tick() {
      savedCallback.current();
    }
    if (delay !== null) {
      let id = setInterval(tick, delay);
      return () => clearInterval(id);
    }
  }, [delay]);
}

 useInterval(() => {
    console.log('render', new Date());
  }, 1000);
```
## Expected Results
Describe what you expected to happen.

run per second

## Snack, code example, screenshot, or link to a repository:
Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by chybisov** [comment]
I have the same problem. @CHANCCCZQ have you figure it out?
