### ISSUE TITLE
error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.

### ISSUE THREAD

**Issue by zarater** [facebook/react-native#29147]
I'm having a hard time trying to initially start a simple android emulator. I get an error as titled to this report. below is the full run traceback. I see an emulator, but I don't get the gui from react-native that's sopposed to be showing on the android device. Windows 10.

Here is what I'm following so far to get this running:
https://blog.jetbrains.com/webstorm/2016/12/developing-mobile-apps-with-react-native-in-webstorm/
* I follow the directions with react up to the point where I'm running android emulator.

https://reactnative.dev/docs/environment-setup

* I have followed the directions on https://reactnative.dev/docs/environment-setup, **React Native CLI Quickstart**. I went through and checklisted  up to **Creating a new application**.

## Description

"C:\Program Files\nodejs\node.exe" C:\Users\zarat\AppData\Roaming\npm\node_modules\react-native-cli run-android
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 960 file(s) to forward-jetify. Using 4 workers...
info JS server already running.
info Launching emulator...
info Successfully launched emulator.
info Installing the app...

ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.

Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

    at makeError (C:\Users\zarat\WebstormProjects\reacttry2\node_modules\execa\index.js:174:9)
    at C:\Users\zarat\WebstormProjects\reacttry2\node_modules\execa\index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async runOnAllDevices (C:\Users\zarat\WebstormProjects\reacttry2\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:94:5)
    at async Command.handleAction (C:\Users\zarat\WebstormProjects\reacttry2\node_modules\@react-native-community\cli\build\index.js:186:9)
error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.

## React Native version:
react-native-cli: 2.0.1
react-native: 0.62.2

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. insall android studio and configure api level 28 and manage an avd.
2. install npm install -g react-native-cli
3. make sure variables and path are correct
4. npm install -g react-native-cli

## Expected Results
Able to see the welcome screen from react-native on adroid device.

## Snack, code example, screenshot, or link to a repository:
![TODO4](https://user-images.githubusercontent.com/21065299/84714735-63205180-af23-11ea-84bb-3e83c78fc9bb.JPG)
![TODO3](https://user-images.githubusercontent.com/21065299/84714737-63b8e800-af23-11ea-8ecd-f75738629839.JPG)
![TODO2](https://user-images.githubusercontent.com/21065299/84714739-64ea1500-af23-11ea-9a49-ff22cb95806b.JPG)
![TODO1](https://user-images.githubusercontent.com/21065299/84714741-6582ab80-af23-11ea-9ece-f06173df50d2.JPG)
![TODO6](https://user-images.githubusercontent.com/21065299/84714743-6582ab80-af23-11ea-8395-2d7f65bb4d71.JPG)
![TODO5](https://user-images.githubusercontent.com/21065299/84714744-661b4200-af23-11ea-9d52-e39dcd8fa3d4.JPG)

**Comment by kiranjd** [comment]
It helps to verify the PATH variables using `echo %ANDROID_HOME%`

**Comment by zarater** [comment]
Yeah thats no pr
![TODO1](https://user-images.githubusercontent.com/21065299/84804827-2bafb480-afb8-11ea-956e-e12a5161c6c4.JPG)
oblem:

**Comment by kiranjd** [comment]
Right.
I can these in when you run your command:
```
info Launching emulator...
info Successfully launched emulator.
info Installing the app...
```
This means the ANDROID_HOME is set up properly because that is where the emulator is called from.

Here is where your problem is: 
`ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.`

Might have been something wrong with the installation. I would do a complete reinstall of the deps if I were you. Saves a lot of time.

**Comment by zarater** [comment]
* I see, I didn't catch that. I did set that up. issue solved.
* In case anyone else has the same issue and need some guidance for windows 10 or any environment issues use this: 
https://confluence.atlassian.com/doc/setting-the-java_home-variable-in-windows-8895.html
https://stackoverflow.com/questions/48298910/react-native-java-home-is-not-set-and-no-java-command-could-be-found-in-your
https://reactnative.dev/docs/environment-setup

* These helped me in the process of setting up android device.

**Comment by kiranjd** [comment]
@zarater  I think the issue can be closed now?

**Comment by fabriziobertoglio1987** [comment]
please close

**Comment by errsolve7** [comment]
[[Already Solved] error Failed to install the app. Make sure you have the Android development environment set up in React Native](https://exerror.com/error-failed-to-install-the-app-make-sure-you-have-the-android-development-environment-set-up-in-react-native/)
