### ISSUE TITLE
release apk com.facebook.react.common.javascriptexception:null is not an object (evaluating t(r(d[1])).default.direction react native

### ISSUE THREAD

**Issue by sathyab18** [facebook/react-native#29140]
Release build crashes on iOS and Android. Fatal Exeption.

Error:
release apk com.facebook.react.common.javascriptexception:null is not an object (evaluating t(r(d[1])).default.direction react native

package.json
"dependencies": {
    "appcenter": "^3.0.3",
    "appcenter-analytics": "^3.0.3",
    "appcenter-crashes": "^3.0.3",
    "expo": "^33.0.0",
    "hermesvm": "^0.1.1",
    "jsc-android": "^241213.1.0",
    "react": "16.8.3",
    "react-dom": "~16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz",
    "react-native-device-info": "^5.6.1",
    "react-native-elements": "^2.0.0",
    "react-native-snap-carousel": "^3.9.0",
    "react-native-web": "~0.11.7",
    "react-navigation": "^3.11.0"
  },

**Comment by ryantando** [comment]
Hi @sathyab18 . I'm facing this problem. How did you fix this?
