### ISSUE TITLE
Hermes enabled prevents from having Intl on Android (date intl)

### ISSUE THREAD

**Issue by LMestre14** [facebook/react-native#29141]
# Description
Basically I changed the jscFlavor to **org.webkit:android-jsc-intl:+** in order to get intl in my luxon format strings. I did in another project and it worked perfectly and had intl for android and ios. In this project it wasn't working, the only difference between these 2 projects was the react-native version, and hermes was enabled.

Disabled hermes on my current project and intl worked. So basically hermes is doing something that prevent intl from being configured on generating the apk

For testing I was using the Luxon library for date management

## React Native version:
System:
    OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 96.13 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.13.1 - /usr/local/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. change jscFlavor to 'org.webkit:android-jsc-intl:+'
2. enable hermes

## Expected Results
Intl should work wether or not Hermes is enabled

**Comment by chrisbobbe** [comment]
(Linking https://github.com/facebook/hermes/issues/23, as I don't see it linked in this issue yet.)

**Comment by ngocvu576** [comment]
me too

**Comment by qcho** [comment]
> (Linking [facebook/hermes#23](https://github.com/facebook/hermes/issues/23), as I don't see it linked in this issue yet.)

Almost done!

**Comment by bviebahn** [comment]
Having the same problem using react-native 0.65.1 and hermes 0.8.1, which should include the Intl API as I understand it. Does anybody know how to get it to work?

**Comment by metinaltinbas** [comment]
Having the same problem. Is there anyone has a solution for this ?
