### ISSUE TITLE
Build failing on iOS - glog.build

### ISSUE THREAD

**Issue by sadikyalcin** [facebook/react-native#29153]
## Description
Newly created projects fail on iOS.

## React Native version:
    System: OS: macOS 10.15.5
    Binaries:
        Node: 12.10.0 - ~/.nvm/versions/node/v12.10.0/bin/node
        Yarn: 1.13.0 - /usr/local/bin/yarn
        npm: 6.10.3 - ~/.nvm/versions/node/v12.10.0/bin/npm
        Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
        CocoaPods: 1.8.4 - /usr/local/bin/pod
    SDKs:
        iOS SDK:
            Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
        Android SDK:
            API Levels: 23, 26, 27, 28
            Build Tools: 28.0.3
            System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
        Android NDK: Not Found
    IDEs:
        Android Studio: 3.5 AI-191.8026.42.35.6010548
        Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
    npmPackages:
        @react-native-community/cli: Not Found
        react: 16.11.0 => 16.11.0 
        react-native: 0.62.2 => 0.62.2 
    npmGlobalPackages:
        *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. `npx react-native init MyTestApp`
2. `yarn ios`

## Expected Results

App to build and run on the simulator

## Snack, code example, screenshot, or link to a repository:

** BUILD FAILED **

`The following build commands failed:
	CompileC /Users/admin/Library/Developer/Xcode/DerivedData/MyTestApp-duxqvfnhjrcxkkaptbxvelievdei/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/glog.build/Objects-normal/x86_64/vlog_is_on.o /Users/admin/Sites/MyTestApp/ios/Pods/glog/src/vlog_is_on.cc normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/admin/Library/Developer/Xcode/DerivedData/MyTestApp-duxqvfnhjrcxkkaptbxvelievdei/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/glog.build/Objects-normal/x86_64/raw_logging.o /Users/admin/Sites/MyTestApp/ios/Pods/glog/src/raw_logging.cc normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(2 failures)`

**Comment by szhigunov** [comment]
Try `sudo xcode-select -s /Applications/Xcode.app/Contents/Developer/` it solved the same problem.

**Comment by jinhale** [comment]
I have an existing project which I can no longer build for Apple but I can for Android.

```
$ npx react-native info
info Fetching system and libraries information...
System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i3-8100B CPU @ 3.60GHz
    Memory: 1.86 GB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.21.1 - ~/npm-global/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
  IDEs:
    Xcode: 12.0/12A7209 - /usr/bin/xcodebuild
  npmGlobalPackages:
    react-native-cli: 2.0.1

```

Using `sudo xcode-select -s /Volumes/External\ HD\ OS/Xcode.app/Contents/Developer/` has no effect on the outcome, nor does using `sudo xcode-select -s /Volumes/External\ HD\ OS/Xcode.app`.

I recently upgraded XCode, to 12.0 (12A7209), after having build issues. 

Here is the error message I get after `Installing glog (0.3.5)` when I run `pod install` from the ios directory: 

```
[!] /bin/bash -c 
set -e
#!/bin/bash
# Copyright (c) Facebook, Inc. and its affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

set -e

PLATFORM_NAME="${PLATFORM_NAME:-iphoneos}"
CURRENT_ARCH="${CURRENT_ARCH}"

if [ -z "$CURRENT_ARCH" ] || [ "$CURRENT_ARCH" == "undefined_arch" ]; then
    # Xcode 10 beta sets CURRENT_ARCH to "undefined_arch", this leads to incorrect linker arg.
    # it's better to rely on platform name as fallback because architecture differs between simulator and device

    if [[ "$PLATFORM_NAME" == *"simulator"* ]]; then
        CURRENT_ARCH="x86_64"
    else
        CURRENT_ARCH="armv7"
    fi
fi

export CC="$(xcrun -find -sdk $PLATFORM_NAME cc) -arch $CURRENT_ARCH -isysroot $(xcrun -sdk $PLATFORM_NAME --show-sdk-path)"
export CXX="$CC"

# Remove automake symlink if it exists
if [ -h "test-driver" ]; then
    rm test-driver
fi

./configure --host arm-apple-darwin

# Fix build for tvOS
cat << EOF >> src/config.h

/* Add in so we have Apple Target Conditionals */
#ifdef __APPLE__
#include <TargetConditionals.h>
#include <Availability.h>
#endif

/* Special configuration for AppleTVOS */
#if TARGET_OS_TV
#undef HAVE_SYSCALL_H
#undef HAVE_SYS_SYSCALL_H
#undef OS_MACOSX
#endif

/* Special configuration for ucontext */
#undef HAVE_UCONTEXT_H
#undef PC_FROM_UCONTEXT
#if defined(__x86_64__)
#define PC_FROM_UCONTEXT uc_mcontext->__ss.__rip
#elif defined(__i386__)
#define PC_FROM_UCONTEXT uc_mcontext->__ss.__eip
#endif
EOF

# Prepare exported header include
EXPORTED_INCLUDE_DIR="exported/glog"
mkdir -p exported/glog
cp -f src/glog/log_severity.h "$EXPORTED_INCLUDE_DIR/"
cp -f src/glog/logging.h "$EXPORTED_INCLUDE_DIR/"
cp -f src/glog/raw_logging.h "$EXPORTED_INCLUDE_DIR/"
cp -f src/glog/stl_logging.h "$EXPORTED_INCLUDE_DIR/"
cp -f src/glog/vlog_is_on.h "$EXPORTED_INCLUDE_DIR/"

checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for arm-apple-darwin-strip... no
checking for strip... strip
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for arm-apple-darwin-gcc... /Volumes/External HD OS/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -arch armv7 -isysroot /Volumes/External HD OS/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.0.sdk
checking whether the C compiler works... no
/Users/stewarthealey/Library/Caches/CocoaPods/Pods/External/glog/2263bd123499e5b93b5efe24871be317-1f3da/missing: Unknown `--is-lightweight' option
Try `/Users/stewarthealey/Library/Caches/CocoaPods/Pods/External/glog/2263bd123499e5b93b5efe24871be317-1f3da/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: in `/Users/stewarthealey/Library/Caches/CocoaPods/Pods/External/glog/2263bd123499e5b93b5efe24871be317-1f3da':
configure: error: C compiler cannot create executables
See `config.log' for more details
```

**Comment by jinhale** [comment]
```
$ pod env

### Stack

```
   CocoaPods : 1.8.4
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.6 (19G2021)
       Xcode : 12.0 (12A7209)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

**Comment by jinhale** [comment]
After trying `git bisect` to look at the difference between the latest successful release and current code, I get the same error, so the problem appears to be a version incompatibility. I save `package.json`, `Podfile`, etc to git, so I don't think the npm packages are to blame. I'm guessing there is some incompatibility between XCode 12.0 and some command related to installing glog - whatever that is.

**Comment by jinhale** [comment]
After installing an older XCode version, 11.7 (11E801a), and running `sudo xcode-select --switch /Applications/Xcode.app/` I was finally able to run `pod install` without error. 

If you have this problem, the best course of action seem to be to [download](https://developer.apple.com/download/more/) the old app zip file, extract to the `/Applications` folder or wherever you plan to switch to, then proceeding as normal. 

Please comment when the relevant packages are updated to enable compatibility with XCode 12 and beyond.

**Comment by Goldziher** [comment]
I encounter the same error using xcode 12. Weirdly this only happens when im building for production.

error:
▸ Compiling utilities.cc
/builds/SnyeLeWj/0/repo/app/ios/Pods/glog/src/base/mutex.h:105:10: 'config.h' file not found
#include "config.h"           // to figure out pthreads support
         ^~~~~~~~~~
▸ Compiling vlog_is_on.cc
/builds/SnyeLeWj/0/repo/app/ios/Pods/glog/src/base/mutex.h:105:10: 'config.h' file not found
#include "config.h"           // to figure out pthreads support
         ^~~~~~~~~~
▸ Compiling symbolize.cc
/builds/SnyeLeWj/0/repo/app/ios/Pods/glog/src/base/mutex.h:105:10: 'config.h' file not found
#include "config.h"           // to figure out pthreads support
         ^~~~~~~~~~
▸ Compiling signalhandler.cc
/builds/SnyeLeWj/0/repo/app/ios/Pods/glog/src/base/mutex.h:105:10: 'config.h' file not found
#include "config.h"           // to figure out pthreads support
         ^~~~~~~~~~

**Comment by codinronan** [comment]
For future Googlers, this occurs because (from what I can tell) the configure script RN generates during `pod install` can't properly detect whether pthreads support is included on macOS. This appears to be due to some difference between Xcode 11 and Xcode 12 because people who have downgraded said the problem went away.

In any case, the following worked for me:
* Open `ios/Pods/Flipper-Glog/src/config.h` and ADD `#define HAVE_PTHREAD 1` anywhere in the file and change the `HAVE_RWLOCK` flag to `#define HAVE_RWLOCK 1` as well
* Open `ios/Pods/glog/src/config.h` and do the same. You need to do both libraries.

Making this change made things work for me. This isn't just forcing it to work, it's correcting something that was previously working. I verified in older projects that these fields were correctly set (and pthread support is widespread among macOS, the simulators and iOS).

**Comment by yapadubpadoo** [comment]
@codinronan your suggestion works for me. Thanks!

**Comment by herparis** [comment]
1 - run `brew uninstall watchman`
2 - run `brew install watchman` or `arch -arm64 brew install watchman` if you are on an M1
3 - closed the current terminal (console) session
4 - open it again and go to the project directory
5 - `cd ios && rm -rf Pods Podfile.lock && pod install --repo-update`
6 - run `watchman watch-del-all`
7 - if you have the iOS simulator opened, closed
8 - run `yarn react-native run-los`
