### ISSUE TITLE
[RN 0.61.5]: Talkback narrates accessibility role = "header" twice.

### ISSUE THREAD

**Issue by IshaTyagi** [facebook/react-native#29152]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Talkback narrates accessibility role = "header" twice in Android phone.

## React Native version:
Run `react-native info` in your terminal and copy the results here.
System:
    OS: macOS 10.15.5
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 36.57 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 13.11.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.7 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: ^0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.
No steps

## Expected Results
It should narrated "role" only once.

**Comment by jamesgit123** [comment]
Same. I have seen the same issue in React Native 0.61.5.

If this could be fixed it would be great.

**Comment by chetansehgal99** [comment]
Check if this link helps:
https://github.com/facebook/react-native/pull/27496/files

**Comment by MahendraBalu** [comment]
@chetansehgal99 do you know in which release above fix will be available?
