### ISSUE TITLE
[Android] Perspective transform styles not working

### ISSUE THREAD

**Issue by marcshilling** [facebook/react-native#2915]
I am passing ```    transform: [
      { perspective: 500 }
    ]``` to one of my view's style. Works on iOS, throws following error on Android:

"undefined is not a function (evaluating 'MatrixMath.inverse3x3(perspectiveMatrix)')"

**Comment by marsprince** [comment]
I saw MatrixMath.js and couldn't find it, maybe uncompeleted on Android

**Comment by chirag04** [comment]
Just got hit by this.

**Comment by marsprince** [comment]
I got it,it'a bug,look this [issue](https://github.com/facebook/react-native/issues/2999)
