### ISSUE TITLE
How to make numColumns property of Flatlist dynamic?

### ISSUE THREAD

**Issue by thegeekybaniya** [facebook/react-native#29163]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
I made a web+mobile app using React Native I used a FlatList grid on one of the screens. I used Screen width and width of my listitem to determine the numColumns value and it works perfectly on all platforms. But on web when I resize the content of the FlaList grid is hidden. How to overcome this?

**Comment by esthor** [comment]
this might be a question for `react-native-web` (or whatever tool you are using to target web).
