### ISSUE TITLE
react-native deep link Does not  Work Some Device(xiaomi or huawei)

### ISSUE THREAD

**Issue by AMINDRH91** [facebook/react-native#29164]
This code in `AndroidManifest` work on samsung but not work on xiaomi or huawei
`<intent-filter android:label="xxx"  android:autoVerify="true">
          <action android:name="android.intent.action.VIEW" />
          <category android:name="android.intent.category.DEFAULT" />
          <category android:name="android.intent.category.BROWSABLE" />
          
       <data android:scheme="https"
       android:host="*.xxxxx.com"
        android:pathPrefix="/p" />
        </intent-filter>`

**Comment by AMINDRH91** [comment]
System:
    OS: macOS 10.15.5
    CPU: (4) x64 Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz
    Memory: 57.62 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v10.13.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 21, 23, 24, 25, 26, 27, 28, 29
      Build Tools: 23.0.1, 27.0.3, 28.0.0, 28.0.1, 28.0.2, 28.0.3, 29.0.1, 29.0.2
      System Images: android-21 | Google APIs Intel x86 Atom_64, android-22 | Google APIs Intel x86 Atom_64, android-24 | Google Play Intel x86 Atom, android-25 | Google Play Intel x86 Atom, android-26 | Google APIs Intel x86 Atom_64, android-26 | Google Play Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
      Android NDK: 19.2.5345600
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    create-react-native-app: 2.0.2
    react-native-cli: 2.0.1
    react-native-rename: 2.4.1

**Comment by safaiyeh** [comment]
Hello @AMINDRH91 could you follow the issue template? It will help understand your issue better.

**Comment by AMINDRH91** [comment]
I hope the code can be help to all


`
```xml
 <activity
            android:screenOrientation="portrait"
        android:name=".MainActivity"
        android:label="@string/app_name"
       android:configChanges="keyboard|keyboardHidden|screenSize"
        android:launchMode="singleTask"
        android:windowSoftInputMode="adjustResize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>



  <intent-filter android:label="NAME_YOUR_APP">
          <action android:name="android.intent.action.VIEW" />
          <category android:name="android.intent.category.DEFAULT" />
          <category android:name="android.intent.category.BROWSABLE" />
          <data android:scheme="http" />
          <data android:scheme="https" />
          <data android:host="www.NAME_YOUR_APP.com" />

        </intent-filter>

  

      </activity>
````
