### ISSUE TITLE
On android only, onResponderRelease method for View (Animated.View) specifically does not work

### ISSUE THREAD

**Issue by mgoldfi1** [facebook/react-native#29173]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
So I built a circular button with an animation that follows the circumference of the button with react-native.  I start a timer on button hold and it is cleared when the button is released.  If the button is held for one second with no release, an event will fire off and the device will vibrate.  It works perfectly on iOS, but on android you dont even have to hold the button for a second, if you just click it the event happens.  I tried logging out when the event for onResponderRelease fires and its very irregular and doesn't happen at all.  Again, this works perfectly on iOS simulator AND physical device.  Works on neither android emulator or physical android device.

## React Native version:
0.61.5

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.  Attach responder events to a view, they work on iOS but do not work properly on android
2. It looks like the issue has more to do with the release than the start but I think both have problems.

## Expected Results
I expect you to have to hold the button for 1 second without releasing it for the onPress() function to be called.
## Snack, code example, screenshot, or link to a repository:
```
const AlertButton = ({children, onPress, color}) => {
  const state = useValue(State.UNDETERMINED);
  const gestureHandler = useGestureHandler({state});
  const isActive = eq(state, State.BEGAN);
  const duration = cond(isActive, 1000, 250);
  const progress = withTransition(isActive, {duration});

  let timer;
  const onStartShouldSetResponder = () => {
    console.log('start');
    timer = setTimeout(() => {
      Vibration.vibrate();
      onPress();
    }, 1000);
    return true;
  };

  const onResponderRelease = () => {
    console.log('stop');
    clearTimeout(timer);
    return true;
  };
  return (
    <TapGestureHandler {...gestureHandler}>
      <Animated.View
        style={{borderWidth: 1, borderColor: color, borderRadius: SIZE / 2 + 1}}
        onStartShouldSetResponder={onStartShouldSetResponder}
        onResponderRelease={onResponderRelease}>
        <CircularProgress
          radius={SIZE / 2}
          bg="white"
          fg={color}
          {...{progress}}
        />
        <View style={styles.container}>{children}</View>
      </Animated.View>
    </TapGestureHandler>
  );
};

export default AlertButton;
```

**Comment by jorjordandan** [comment]
Could this be because you are using a TapGestureHandler instead of a LongPressGestureHandler?
