### ISSUE TITLE
RN 0.62.2 android profiling crash app

### ISSUE THREAD

**Issue by pqminh** [facebook/react-native#29170]
**RN 0.62.2 android profiling crash app**

## Description
E/SoLoader: Error when loading lib: dlopen failed: library "libjsc.so" not found lib hash
W/System.err: java.lang.UnsatisfiedLinkError: dlopen failed: library "libjsc.so" not found
E/SoLoader: couldn't find DSO to load: libjscexecutor.so caused by: dlopen failed: library "libjsc.so" not found result: 0
D/SoLoader: About to load: libfbjni.so
D/SoLoader: libfbjni.so not found on /data/data/com.app.stg/lib-main
D/SoLoader: libfbjni.so found on /data/app/com.app.stg-FqK5G90kf0Gbe1zH7lScJw==/lib/arm
    Not resolving dependencies for libfbjni.so
A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x1f in tid 8872 (FlipperEventBas), pid 8758 (com.app.stg)

## React Native version:
System:
    OS: Linux 4.15 Ubuntu 16.04.6 LTS (Xenial Xerus)
    CPU: (8) x64 Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
    Memory: 3.53 GB / 15.55 GB
    Shell: 4.3.48 - /bin/bash
  Binaries:
    Node: 12.17.0 - /usr/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.14.4 - /usr/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 23, 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3
      System Images: android-29 | Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64
      Android NDK: 21.3.6528147
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 1.8.0_252 - /usr/lib/jvm/java-8-openjdk-amd64/bin/javac
    Python: 2.7.12 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
1. change enableHermes: false to enableHermes: true
2. Run 'app'
3. Profile 'app'

**Comment by TheHothihi** [comment]
Have you clean and rebuild the project after changing enableHerme？

**Comment by fangasvsass** [comment]
same issue 0.62.2

**Comment by pqminh** [comment]
> Have you clean and rebuild the project after changing enableHerme？

Sure 
0.61.5 also crash

**Comment by sreekanth-14** [comment]
Hey! Anyone solved this?
I'm getting the same error

**Comment by franck-nadeau** [comment]
I am getting the same error, on react native 0.62.2. If anyone has resolved this, can you please share how you did so?

**Comment by nghiant96** [comment]
> I am getting the same error, on react native 0.62.2. If anyone has resolved this, can you please share how you did so?

Metoo.
