### ISSUE TITLE
RN 0.62.2 on ios TextInput secureTextEntry option does not show last character typed on

### ISSUE THREAD

**Issue by timtmok** [facebook/react-native#29172]
## Description
Typing in a `TextInput` with the `secureTextEntry` option hides all characters, even the last character typed for ios. This was reproduced in 0.62.2. It works fine in 0.61.5 and would briefly show the last character typed. Running this on Android with RN 0.62.2 briefly shows the last character typed.

## React Native version:
System:
    OS: macOS 10.15.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 623.41 MB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.4.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 28, 29
      Build Tools: 28.0.3, 29.0.3
      System Images: android-28 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_252 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found
## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Select the text input and begin typing
2. All characters are obscured immediately as typed

## Expected Results
It is expected that the last character typed is briefly revealed before being obscured. This used to work in RN 0.61.5 but has changed in RN 0.62.2 for ios only. 

## code example
```
import React from 'react';
import {TextInput, Text, SafeAreaView} from 'react-native';

const App = () => {
  const [value, setValue] = React.useState('');
  return (
    <SafeAreaView>
      <Text>Password</Text>
      <TextInput
        value={value}
        onChangeText={text => setValue(text)}
        secureTextEntry
      />
      <Text>Password 2</Text>
      <TextInput secureTextEntry />
    </SafeAreaView>
  );
};

export default App;
```

**Comment by timtmok** [comment]
Expo v38 has correct version of RN to reproduce this error: https://snack.expo.io/W!SW9YerN

**Comment by anoraxdev** [comment]
Any updates on this issue?

**Comment by Commoddity** [comment]
+1 having the same issue. Same RN version. Android works but iOS does not (both on SIM and actual device using TestFlight).

**Comment by innergap** [comment]
Having same issue on iOS with same RN version 0.62.2

**Comment by fempyrean** [comment]
Any updates on this? Does anyone know if upading expo/react-native fixes this?

**Comment by paulvilledieu** [comment]
Up 👆🏼

**Comment by fabriziobertoglio1987** [comment]
I wanted to ask if you still experience this issue. 
I'm planning to do 1-2 months of opensource and I'm preparing a list of tasks.

I have been contributing to facebook/react-native for 4 years and I specialize on the Text/TextInput components.

Thanks a lot

**Comment by timtmok** [comment]
@fabriziobertoglio1987 I don't have an ios device anymore to try this out but the Expo snack no longer reproduces the problem. So I think this was fixed at some point through some other change.
