### ISSUE TITLE
console.count() doesn't work without turning on remote debugging

### ISSUE THREAD

**Issue by gupta-ji6** [facebook/react-native#29188]
## Description
`console.count()` logs in the application gives an error if we have turned off remote debugging from developer tools.

I use it to log the count of re-renders of a component, but it gives error shown in screenshot below when I turn off remote debugging.

It should work like `console.log()` or `console.warn()` does without errors, I suppose.

## React Native version:
OS: Linux 4.15 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i3-8145U CPU @ 2.10GHz
    Memory: 922.68 MB / 7.67 GB
    Shell: 5.4.2 - /usr/bin/zsh
  Binaries:
    Node: 12.16.1 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 23, 26, 28, 29
      Build Tools: 23.0.1, 25.0.0, 28.0.3, 29.0.2, 29.0.3
      System Images: android-28 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 1.8.0_252 - /usr/bin/javac
    Python: 2.7.17 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: ^4.2.1 => 4.10.1 
    react: ^16.12.0 => 16.13.1 
    react-native: ^0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Add a `console.count("Lorem Ipsum")` function in any component's `render()` or `constructor()`.
2. Make sure remote debugging is off in developer tools.
3. You must see an error in the device as `undefined is not a function`.

## Expected Results
It should log the same results as it does in a JavaSript console.
Example:
`Lorem Ipsum: 1`
`Lorem Ipsum: 2`

## Snack, code example, screenshot, or link to a repository:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/21218732/85294835-c0387c00-b4bc-11ea-88cd-57b1d317522f.png)

**Comment by SrBrahma** [comment]
The behaviour of the stale bot really sucks. I already have seen many valid issues like this that also happens to me that keep getting closed for inactivity. Yes, they can be recreated but it is really counter intuitive and boring to do so.
