### ISSUE TITLE
NavigatorIOS component view too tall

### ISSUE THREAD

**Issue by Jpoliachik** [facebook/react-native#2918]
The component view for a NavigatorIOS view is exactly 64 points too tall. This is exactly the height of the iOS status bar plus UINagivationBar. Is it not accounting for this in the height calculation?

A bottom margin of 64 on the container view is a temporary solution. 

Sample code and screenshots included below:

NavigatorIOS Layout
```
 var TestApp = React.createClass({
   render: function() {
     StatusBarIOS.setStyle('light-content', false);
     return (
       <NavigatorIOS
         style={styles.nav}
         initialRoute={{
           title: 'Test',
           component: TestView,
         }}
         titleTextColor='white'
         tintColor='white'
         barTintColor='red'
         translucent={false}
         itemWrapperStyle={styles.wrappedView}
       />
     );
   }
 });

 var styles = StyleSheet.create({
   nav: {
     flex: 1,
   },
   wrappedView: {
     backgroundColor: Colors.GreyBackground,
     // NavigationIOS container height workaround
    //  marginBottom: 64,
   }
 });
```

Child View layout: 
```
var TestView = React.createClass({
   render: function() {
     return (
       <View style={styles.container}>
       <View style={styles.emptyView}>
       </View>
         <View style={styles.bottomBar}>
         </View>
       </View>
     );
   },
 });

 var styles = StyleSheet.create({
   container: {
     flex: 1,
     flexDirection: 'column',
   },
   emptyView: {
     flex: 1,
     backgroundColor: 'yellow',
   },
    bottomBar: {
      backgroundColor: 'red',
      height: 64,
    }
 });
```

With bottom view height 80:
![screen shot 2015-09-21 at 5 16 17 pm](https://cloud.githubusercontent.com/assets/5148640/10005323/94743668-6084-11e5-8ce9-5f6542fff469.png)

With bottom view height 64:
![screen shot 2015-09-21 at 5 16 47 pm](https://cloud.githubusercontent.com/assets/5148640/10005327/a1b9dc42-6084-11e5-9def-c496adadd552.png)

**Comment by chefnobody** [comment]
I believe it is recommended that you use `Navigator` rather than `NavigatorIOS`. See the last sentence on this page: https://facebook.github.io/react-native/docs/navigator-comparison.html

**Comment by deanmcpherson** [comment]
I can reproduce, it happens when you disable transparency transparency={false}, set to true and it works correctly.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/navigatorios-component-view-too-tall

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.
