### ISSUE TITLE
'folly/folly-config.h' file not found

### ISSUE THREAD

**Issue by Inomezi** [facebook/react-native#29186]
## Description
Hi, i'm using react-native-reanimated 1.9.0 , when i import it i get error in xcode - 'folly/folly-config.h' file not found
![image](https://user-images.githubusercontent.com/24946599/85261605-0e299180-b475-11ea-9efb-1d981a11ed8c.png)

I tried:

1. rm -rf $TMPDIR/metro-* && rm -rf $TMPDIR/haste-* && watchman watch-del-all && npm cache clean --force && npm cache verify && rm -rf ios/build && rm -rf node_modules/ && npm i
rm -rf pods && pod install
2. scripts/ios-install-third-party.sh
cd third-party/glog-0.3.5
./configure
3. Xcode - Legacy Build
4. Xcode Clean Build Folder

But nothing helped

## Steps To Reproduce
https://github.com/Inomezi/react-native-reanimated-example/tree/master

**Comment by somparkash** [comment]
Hi @Inomezi , I have a same problem. Did you find any solution?

**Comment by Inomezi** [comment]
> Hi @Inomezi , I have a same problem. Did you find any solution?

Hi, you need disable turbo modules - https://github.com/software-mansion/react-native-reanimated/issues/918

**Comment by somparkash** [comment]
Hi @Inomezi ,  Thank you for quick reply.

Please have a look on my PodFile

`# Uncomment the next line to define a global platform for your project
# platform :ios, '10.3'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

use_frameworks!
swift_version = "4.2"

target 'Squealock' do

   
    pod 'Alamofire'
    pod 'DKImagePickerController', :subspecs => ['PhotoGallery', 'Camera', 'InlineCamera']
    pod 'DZNEmptyDataSet'
    pod 'FontAwesomeKit/FontAwesome'
#    pod 'Google/Analytics'
    #pod 'GoogleAPIClient'
    pod 'GoogleAPIClientForREST'
    pod 'GooglePlaces'
    pod 'GrowingTextViewHandler', '1.0.3'
    pod 'JGActionSheet', '1.0.5'
    pod 'MBProgressHUD', '0.9.1'
   #pod 'MZFormSheetPresentationController'
    pod 'PAPreferences', '0.5'
    pod 'Player', '~> 0.8.0'
    pod 'PromiseKit', '~> 6.2.5'
    pod 'RealmSwift', '~> 3.20.0'
    pod 'SCLAlertView-Objective-C', '1.0.3'
    pod 'SelectionDialog'
    pod 'SVPullToRefresh', '0.4.1'
    pod 'TTGSnackbar', '1.7.1'
    pod 'Toast', '~> 3.1.0'
    #pod 'AgoraRtcEngine_iOS'
    pod 'Firebase/Crashlytics'
    pod 'JitsiMeetSDK', '~> 2.9.0'
    pod 'TrueTime'

    config = use_native_modules!
   use_react_native!(:path => config["../node_modules/react-native"])

end
`

**Comment by Un3qual** [comment]
Any update on this besides disabling turbo modules?

**Comment by robrecord** [comment]
Currently unable to use reanimated 2 alpha 7 due to this error. Added to a project and immediately got the error.

**Comment by Ahsanali012** [comment]
Still getting this issue with RN 0.72.3
