### ISSUE TITLE
TypeError: undefined is not a function (near '...this._scrollRef.scrollTo...')

### ISSUE THREAD

**Issue by Miraj98** [facebook/react-native#29192]
## Description
Functions like `scrollToEnd()` and `scrollToItem()` not working when used on nested FlatList

## React Native version:
```
System:
    OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz
    Memory: 78.10 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.0 - /usr/local/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 26, 27, 28, 29
      Build Tools: 28.0.3, 29.0.0, 29.0.2, 29.0.3
      System Images: android-28 | Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_201 - /usr/bin/javac
    Python: 2.7.15 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce

NOTE: These steps have been tested for Android only.

1. Create a React component that returns a `FlatList` and write a simple `renderItem` component which has its own `FlatList`. Let's call the `renderItem` component as `<NestedFlatList />`
2. Try to invoke `scrollToEnd` or `scrollToItem` on the `FlatList` inside the `<NestedFlatList />`

## Expected Results
`scrollToEnd` or `scrollToItem` should work for the `FlatList` defined inside `<NestedFlatList />`. Instead the app crashes.

## Snack, code example, screenshot, or link to a repository:
Here is a snack that reproduces this error: https://snack.expo.io/@miraj98/eager-waffles

**Comment by charles-goode** [comment]
Having same issue.. (ListEmptyComponent is another FlatList). There's also some jank when both are horizontal but you can fix this with `style={{flexDirection:'row'}}` on the inner one.

**Comment by danieloi** [comment]
I have the same issue
