### ISSUE TITLE
A replacement for binaryTobase64

### ISSUE THREAD

**Issue by rahamin1** [facebook/react-native#29195]
**Dear bot,
Please leave this alive at least for 24 hours... Your bosses removed something that I was using and now I am a bit lost... :(**

I just upgraded an app from react-native 0.59.9 to 0.62.2.
Not everything is code that I have written, and that code included the following lines:

```
_import binaryToBase64 from 'binaryToBase64';

let input = new Uint8Array(5);
// Here some code setting 'input'
const base64String = binaryToBase64(input);_
```

I understand that binaryToBase64 is not supported in RN0.62.
What can I use as an exact replacement of the above?

I am aware of the existence of btoa and react-native-base64 but they don't seem to provide an alternative that will enable me to get exactly what binaryToBase64 used to do.

I saw some comments about that https://github.com/mathiasbynens/utf8.js may be used. Doesn't look like that, unless I am missing anything.

Any idea what I can use as an EXACT replacement for `const base64String = binaryToBase64(r2);` ?

## React Native version:
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 3.16 GB / 15.87 GB
  Binaries:
    Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28, 29
      Build Tools: 25.0.2, 28.0.3, 29.0.2
      System Images: android-25 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Version  2.3.0.0 AI-162.3764568
  Languages:
    Java: 1.8.0_112-release
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2

**Comment by EyMaddis** [comment]
This is now more aligned with the rest of the JS ecosystem:
**base64.js:**
```js
import { Buffer } from 'buffer'

export function toBase64(input) {
  return Buffer.from(input, 'utf-8').toString('base64')
}

export function fromBase64(encoded) {
  return Buffer.from(encoded, 'base64').toString('utf8')
}

```

**Comment by rahamin1** [comment]
I forgot to close... Thanks, @EyMaddis !
