### ISSUE TITLE
Metro Bundle did not launch when starting React Native

### ISSUE THREAD

**Issue by john-nuemow** [facebook/react-native#29199]
## Description
I am new to react using a win10 machine. Init AwesomeProject without a problem (latest version of rn as of today) and I have followed the process closely to set up the environment. After cd into AwesomeProject and trying to start React-Native Start, I get Welcome to React Native bla bla but no evidence that the Metro server started at all. I was given option to reload using R or open dev menu using d. 

Reloading using 'r' gives me this message "warn No apps connected. ....

I can see the emulator under ADB devices

## React Native version:
+ react-native-cli@2.0.1
+ react-native@0.62.2

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.npx React-Native start

## Expected Results
Metro server does not start

## Snack, code example, screenshot, or link to a repository:
This person here has the exact same issue
https://stackoverflow.com/questions/62533613/metro-server-does-not-run-and-not-connect-to-the-app-in-react-native

**Comment by JBerendes** [comment]
@john-nuemow  When you go to localhost:8081 does it say the packager is running?

**Comment by john-nuemow** [comment]
@JBerendes yes. Shows React Native package is running.

When I open another terminal to run "npx react-native run-android"

I get this error:

BUILD FAILED in 990ms

error Failed to install the app. Make sure you have the Android development environment set up: 
https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

Also on the emulator, it doesn't look like anything is happening.

**Comment by DracotMolver** [comment]
Do you get the same error if you only start up metro?  `npm start`.

**Comment by JBerendes** [comment]
Maybe it's watchman not kicking in. How did you install watchman? 

It looks like you are on windows. On mac I had similar problem. I installed watchman with brew so it was installed system wide. My solution was to uninstall it. Add it to the project with yarn.. `yarn add watchman` And then run the project again. Try that and let us know how it goes.

**Comment by JBerendes** [comment]
I wrote an article, basically the long story that got me to what I suggested above. [“Loading dependency graph…” forever.](https://lab651.com/returning-to-react-native/)
