### ISSUE TITLE
Fetch (or axios) causes hard crash on some URLs (but not others)

### ISSUE THREAD

**Issue by hardcodet** [facebook/react-native#29196]
## Description

My app is crashing hard when doing API calls, and I narrowed it down to this point:

- it's not an HTTP vs HTTPS thing
- I eventually used two different mock APIs and one worked, the other didn't, both HTTP (see snippet below)
- running on an Android device (no emulator): Galaxy S10e, Android 10
- same behavior on both WIFI or cellular network
- same issue in axios instead of fetch
- the `catch` block is invoked, but then the app still crashes hard

```
async foo() {
        try {

            // this endpoint CRASHES my app
            const r = await fetch("http://jsonplaceholder.typicode.com/todos/1");
            
            // this endpoint works just fine
            //const r = await fetch("http://echo.jsontest.com/key/value/one/two");

        } catch(e) {
            console.log("Invoked with a non-descript network error, but the app still crashes hard right after");
        }
}
```

## React Native version:

```
System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7 CPU         860  @ 2.80GHz
    Memory: 2.12 GB / 15.99 GB
  Binaries:
    Node: 12.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 23.0.1, 25.0.0, 25.0.2, 26.0.2, 27.0.0, 27.0.3, 28.0.2, 28.0.3, 29.0.2, 29.0.3
      System Images: android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6514223
  npmPackages:
    react: ~16.9.0 => 16.9.0
    react-native: ~0.61.5 => 0.61.5
  npmGlobalPackages:
    react-native-create-library: 3.1.2
    react-native-git-upgrade: 0.2.7
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Just invoke the snippet and replace one URL with the other.
2. One crashes my app, the other one doesn't

**Comment by hardcodet** [comment]
I found a hint in Logcat - it appears that using OkHttp3 is causing some sort of versioning conflict that only manifests in one of the responses (maybe due to CORS headers) or anything.

My fix was to change my dependency on OkHttp3 in `build.gradle` from

    implementation "com.squareup.okhttp3:okhttp:4.7.2"

to

    api(platform("com.squareup.okhttp3:okhttp-bom:4.7.2"))
    api("com.squareup.okhttp3:okhttp")
    api("com.squareup.okhttp3:logging-interceptor")


Can't say whether this is a proper fix, or a workaround to an underlying RN problem, so I'll keep this open for now for others to review. Thanks!

**Comment by latobibor** [comment]
We also have faced this issue and the workaround above fixes it. Please if there is official fix or workaround on this, let us know, so we can update the code (or bump the package).

**Comment by mazorvanunu** [comment]
any news on this issue? i have no gradle.build on my project and when i eject (to find this gradle.build) i have no reference for the said line of 'okhttp'

my app simply crashes without any error on a simple https request (while other sites work) 
is this a CORS issue? 
i cannot understand why this issue persist, we are talking about the most simple of network usage.............!
i ejected the app and built an apk alone, the issue persist, both on simulator and on an android device..........
the simple network usage.

**Comment by mazorvanunu** [comment]
btw, funny the issue is closed.. @hardcodet, you work for facebook ???

**Comment by mazorvanunu** [comment]
when i post a message the app simply crashes, when i just 'get' a url it returns no problem ...

**Comment by mazorvanunu** [comment]
when i use xmlhttprequest i get the error: unable to resolve host, no address associated with hostname - which, in itself - is the most murky error message i have seen (ever), a host and a hostname address are the same thing. things get even funnier when you look it up on google, hehe

**Comment by mazorvanunu** [comment]
try to xmlhttprequest with server ip gives handshake error - i mean common, is this really so half-baked??? WOW!

**Comment by mazorvanunu** [comment]
LOLLLLLZ, found a solution - wont share it here tho - changed NOTHING in the code but the solution (it worked) suddenly i get a blue screen with an error about exp.host - no address associated with host name - (PS for the code to even reach the area i was working on before i have to click a button), even after reverting the change (literally one text line) and restart expo - WTF! DEMONS! WOW !! haha, dont know if i should cry or just laugh (im obviously laughing, this is so amateuristic)

**Comment by subhadeepshome1** [comment]
thanks @hardcodet in my case the issue is solved

**Comment by Seibold** [comment]
I experience the same issue.

- Axios Version [0.24.0]
- OS: [Android 11]
- Additional Library Versions [e.g. React 17.0.2, React Native 0.66.3]

**Comment by Flip437** [comment]
Hello everyone,

in my case, I didn't have this line in my ./android/build.gradle:

`implementation "com.squareup.okhttp3:okhttp:4.7.2"`

I tried to add it, but no luck, same error.

So I added those three lines in build.gradle:
`api(platform("com.squareup.okhttp3:okhttp-bom:4.7.2"))
api("com.squareup.okhttp3:okhttp")
api("com.squareup.okhttp3:logging-interceptor")`

and IT WORKED !!!

OMG, 2 days searching, this droves me crazy.

Thanks a lot guys.
Is there a fix planned for this issue ?

flip

**Comment by FrancescoBonizzi** [comment]
I face the same issue also on iOS, it's terrible. 

Why try catch is not catching? 😭

**Comment by vietnt-uet** [comment]
@FrancescoBonizzi Did you solve it, I face the kind of the same issue with my RN version 0.73.x in my iOS too. It's so weird.

**Comment by mordechaim** [comment]
Adding `connection: close` to the fetch init object seems to resolve this issue
