### ISSUE TITLE
RN 0.62.2 KeyboardAvoidingView race condition on iOS

### ISSUE THREAD

**Issue by Iskander508** [facebook/react-native#29198]
## Description
Discovered a bug in `KeyboardAvoidingView` on iOS after upgrading to RN `0.62.2` (can't reproduce on previous version `0.61.2`). It happens randomly and rarely, only reproduced on iOS (both simulator and physical phone: iPhone7 iOS 13.3). When using the `KeyboardAvoidingView` (with `behavior="padding"`) inside which is `autoFocus`ed `TextInput` being aligned to the bottom of the screen, the input is sometimes (very rarely, hard to reproduce) covered by the software keyboard when opening the screen, instead of pushed up in the view.

## React Native version:
```
System:
    OS: macOS 10.15.5
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 20.86 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.17.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.3, 30.0.0
      System Images: android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_252 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2
```

```
    "react-navigation": "^4.0.10",
    "react-navigation-fluid-transitions": "^0.3.2",
    "react-navigation-hooks": "^1.1.0",
    "react-navigation-stack": "^1.9.4",
    "react-navigation-tabs": "^2.5.6",
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Use iOS and open screen using react-navigation v4 library.
1. Open a new screen with `react-navigation-stack`
2. Use `KeyboardAvoidingView`, `behavior="padding"`
3. Add `TextInput` with `autoFocus` aligned to the bottom

## Expected Results
The TextInput is pushed above the software keyboard on the bottom of the screen.

## Code example:
```
<KeyboardAvoidingView
  behavior="padding"
  style={{
    flex: 1,
    height: '100%',
    width: '100%',
  }}>
  <View style={{ flex: 1 }} /> {/* this is to push the TextInput to bottom*/}
  <TextInput
    style={{
      backgroundColor: 'red',
      width: '100%',
    }}
    keyboardType="numeric"
    autoFocus
    placeholder="test"
  />
</KeyboardAvoidingView>
```

## Screenshots:
I've been digging into the code to see why it breaks occasionally, and it is most likely because the layout callbacks are not properly handled inside the `KeyboardAvoidingView` component. Sometimes they get called in different order and then the logic breaks. I have altered the RN component code and added some logging to see in which order the internal methods are called:

This is when the callbacks are called in regular order (most of the cases). The `TextInput` gets pushed up when opening the screen:
![Correct](https://user-images.githubusercontent.com/4604361/85413748-7eb2da00-b56b-11ea-98d0-e440aa771991.png)

This is when the callbacks are called in different (rare case) order. As you can see the `LayoutAnimation` doesn't happen when `_onKeyboardChange` is called before `_onLayout` (which happens rarely on iOS with RN `0.62.2`). Then the `TextInput` component gets covered by the software keyboard:
![DSC_1323](https://user-images.githubusercontent.com/4604361/85413888-b28dff80-b56b-11ea-91f0-2d6091df2406.JPG)

**Comment by Kameshwaran** [comment]
I'm still facing it. Please reopen it
