### ISSUE TITLE
TextInput with Typescript Error:-Type 'number' is not assignable to type 'string | undefined'

### ISSUE THREAD

**Issue by proteche** [facebook/react-native#29190]
` <TextInput
          keyboardType="numeric"
          style={{ marginHorizontal: 10, backgroundColor: 'white' }}
          label="Mobile Number"
          value={formData.mobileNumber}
          onChangeText={(text) =>
            setFormData({ ...formData, mobileNumber: parseInt(text, 10) })
          }`
typescript giving error in "value" attribute **"Type 'number' is not assignable to type 'string | undefined'"**

**Comment by drop-george** [comment]
React Native does not support typescript officially. This sounds like an issue with the [DefinitelyTyped typings, you probably want to submit an issue there](https://github.com/DefinitelyTyped/DefinitelyTyped/issues)
