### ISSUE TITLE
Error: app/main.jsbundle does not exist. This must be a bug with

### ISSUE THREAD

**Issue by mgecawicz** [facebook/react-native#29205]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Upon building my application in XCode, I am faced with one error reading:

error: File /Users/[Me]/Library/Developer/Xcode/DerivedData/[myApplication]/Build/Products/Release-iphoneos/[myApplicatoin].app/main.jsbundle does not exist. This must be a bug with

## React Native version:
System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz
    Memory: 320.16 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.9.1 - ~/emsdk/node/12.9.1_64bit/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.10.2 - ~/emsdk/node/12.9.1_64bit/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 10.0.2 - /usr/bin/javac
    Python: 3.7.4 - /Users/[Me]/opt/anaconda3/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
1. XCode > Product > Build

## Expected Results
The app should build and be ready for archiving and uploading to Testflight

## Snack, code example, screenshot, or link to a repository:
<img width="842" alt="Screen Shot 2020-06-24 at 1 21 54 AM" src="https://user-images.githubusercontent.com/44035616/85504317-c9f3d980-b5b9-11ea-86cb-975929bd2c12.png">

**Comment by lorenzoangelini** [comment]
@mgecawicz I have the same error.

**Comment by cleandersonlobo** [comment]
I have the same error. RN 0.62.2

**Comment by wuzubo** [comment]
I have the same error. I'm using RN 0.61.5

...app/main.jsbundle does not exist. This must be a bug with.

**Comment by Sachanski** [comment]
I encountered a similar issue when upgrading to 0.63. [This](https://stackoverflow.com/questions/62806319/main-jsbundle-does-not-exist-this-must-be-a-bug-with-main-jsbundle-issue-afte/62829256#62829256) is what was the problem for me.

**Comment by lorenzoangelini** [comment]
@Sachanski  yes in my case, 
Error: Unable to resolve module `src/splashScreen/screen` from `src/_shared/routes/Navigator.tsx`: src/splashScreen/screen could not be found within the project or in these directories:
  /Users/lorenzo/apps/app/node_modules/src/splashScreen
it is strange because in debug mode it works. When launch the release i have this problem

**Comment by Sachanski** [comment]
@lorenzoangelini I am not that familiar with React Native, but isn't the `main.jsbundle` file only used in release mode (i.e. in debug the files are fetched from the Metro Server)?

**Comment by vrgimael** [comment]
None of the above fixed it for me, but it works with this PR, it'll probably be released soon https://github.com/facebook/react-native/pull/29477

Just in case somebody finds it useful :)
