### ISSUE TITLE
Totally at a loss: Module AppRegistry is not a registered callable module (calling startHeadlessTask)

### ISSUE THREAD

**Issue by flikQ** [facebook/react-native#29207]
## Description
I am not confident it is a general RN issue specifically, but I am currently at a loss as to the potential cause as very little info is given (that I can understand in order to track down the issue), so I wanted to query to community for some potential insight if anyone has experienced a similar issue.

The reason I am reaching out is that this crash is happening at least 6000 times a day and although it isn't causing a direct issue with users visually seeing a crash it of course impacts our KPI's for crash % and skews the results.

## React Native version:
RN 0.61.5

## Steps To Reproduce
It seems from the error details being offered in out BugSnag report is that it's happening while the app is inactive, so generally speaking it's not a crash users are actively seeing as when they go to resume the app it simply boots as normal.

## Expected Results
To not occur (vague I know)

Here is the error output - only reproducible in production - but only passively as explained above. 

`Error Module AppRegistry is not a registered callable module (calling startHeadlessTask) 
    /Users/flikq/Dev/epics-mobile/node_modules/invariant/browser.js:39:8 exports
    /Users/flikq/Dev/epics-mobile/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:424:4 value
    /Users/flikq/Dev/epics-mobile/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:111:26 
    /Users/flikq/Dev/epics-mobile/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:384:8 value
    /Users/flikq/Dev/epics-mobile/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:110:17 value
    [native code] value`

I am fully at a loss as what could possibly cause such as issue to 80% of our android users. I was hoping someone might be able to recognise something about it from their own experiences or who has a much greater knowledge of RN as a whole to help resolve. 

Thanks in advance, however if I have written this report incorrectly please let me know and I'll correct. I am sure you can understand why I am unable to provide snippets to reproduce directly.

**Comment by N3TC4T** [comment]
Unfortunately I have the same problem on Android, the crash log is not so clear so I can't realize where is the problem. 

for the record I'm guessing maybe the problem comes from this two library :

```
react-native-navigation
react-native-firebase
```
