### ISSUE TITLE
Accessibility label getting read out on a single tap as well as double tap on iOS

### ISSUE THREAD

**Issue by prabathRN** [facebook/react-native#29209]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
When using the application on voiceover mode on iOS on hovering/focusing an element in accessibility reads it and then when I double tap on the same element again accessibility is reading that element label again.

## React Native version:
System:
OS: macOS 10.15.5
CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
Memory: 320.02 MB / 8.00 GB
Shell: 5.7.1 - /bin/zsh
Binaries:
Node: 10.16.3 - /usr/local/bin/node
Yarn: Not Found
npm: 6.9.0 - /usr/local/bin/npm
Watchman: Not Found
Managers:
CocoaPods: 1.9.3 - /usr/local/bin/pod
SDKs:
iOS SDK:
Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
Android SDK: Not Found
IDEs:
Android Studio: Not Found
Xcode: 11.5/11E608c - /usr/bin/xcodebuild
Languages:
Java: 12.0.2 - /usr/bin/javac
Python: 2.7.16 - /usr/bin/python
npmPackages:
@react-native-community/cli: Not Found
react: 16.11.0 => 16.11.0
react-native: 0.62.0 => 0.62.0

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Turn on the voice-over in iOS device
2. Focus on an element with single tap. Accessibilitymanager reads out accessibility label
3. Double-tap on the same element Accessibilitymanager reads out accessibility label again

## Expected Results
On double tap accessibility should not read the same element again.

## code example
const DATA = [
  {
    id: 'bd7acbea-c1b1-46c2-aed5-3ad53abb28ba',
    title: 'First Item',
  },
  {
    id: '3ac68afc-c605-48d3-a4f8-fbd91aa97f63',
    title: 'Second Item',
  },
  {
    id: '58694a0f-3da1-471f-bd96-145571e29d72',
    title: 'Third Item',
  },
];

 SafeAreaView style={styles.container}
      FlatList
        data={DATA}
        renderItem={({ item }) => (
          Item
            id={item.id}
            title={item.title}
            selected={!!selected.get(item.id)}
            onSelect={onSelect}
          /
        )}
        keyExtractor={item => item.id}
        extraData={selected}
      /
    /SafeAreaView

**Comment by kotavy** [comment]
I'm encountering this same issue. Using an accessibility label like so:
`accessibilityLabel={\`${isSelecting ? 'Disable' : 'Enable'} selection mode.\`}`

I single tap to focus the element and hear "Enable selection mode."
Then I double-tap to activate the element, which changes the isSelecting prop (passed from parent component, for context, in case the lifecycle is affecting anything here) and then I hear "Enable selection mode. Disable selection mode."

**Comment by philyboysmith** [comment]
Is there any update on this? For a use case as to to why this is problematic I have a play button that when pressed reads out audio. However, when using VoiceOver the word Play, is read over the script that is being played.

**Comment by koktavy** [comment]
@blavalla Thanks for the reply and for confirming the expected behavior! I agree that it was some kind of race condition due to the react update lifecycle. I didn't have access to the project anymore, so I won't be able to revisit this issue.

You say "unfortunately" but it you can't reproduce what I described that's good!

Sounds to me like this issue can be closed.
