### ISSUE TITLE
Image component does not load image from specific URI on iOS

### ISSUE THREAD

**Issue by rmacqueen** [facebook/react-native#29215]
## Description
The `Image` component does not render an image on iOS when loaded from a specific URI

## React Native version:

System:
    OS: macOS 10.15.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 234.47 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.20.0 - ~/.nvm/versions/node/v10.20.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v10.20.0/bin/npm
    Watchman: Not Found
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 14.0.1 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.9.0 => 16.9.0
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
See code snippet below

## Expected Results
I would expect the code below to render an image on screen. It does do that on Android, but _not_ on iOS. If i go to that link in a browser or `curl` it from the terminal it renders or downloads as expected. But React Native on iOS does not render it.

## Snack, code example, screenshot, or link to a repository:

```
<Image style={{height: 100, width: 100}} source={{ uri: 'https://api.openpay.mx/barcode/185017437691737?width=1&height=100' }} />
```

See example here: https://snack.expo.io/QH4nUBfc6

**Comment by ryanpag3** [comment]
I'm seeing this issue too. Are you running IOS 14 beta?

**Comment by rmacqueen** [comment]
@ryanpag3 No, I'm running iOS 13.5

**Comment by DennisdeWitNL** [comment]
Can confirm. I have the same problem on iOS 14.

**Comment by LewisYearsley** [comment]
All images not loading for me on iOS 14 beta

**Comment by torgeadelin** [comment]
Same, uri or local images not working. I have Xcode 12, iOS 14.

**Comment by rdperottoni** [comment]
iOS 13.5.1 + XCode 11.5 works fine here.

**Comment by SConaway** [comment]
Yep, same here. It only started occurring recently, so I think it must be from some dependency RN pulls in.

**Comment by rdperottoni** [comment]
This is most likely coming from iOS SDK 14, which comes with XCode 12. Should probably stay away from XCode 12 for a few months for production builds.

**Comment by SConaway** [comment]
I disagree. Even using the release SDK and toolchain still causes this on my end.

**Comment by rdperottoni** [comment]
> I disagree. Even using the release SDK and toolchain still causes this on my end.

Hey @SConaway, could you post the output you're getting from executing `xcodebuild -showsdks` in the terminal?

**Comment by ryanpag3** [comment]
@rdperottoni The issue is reproducible on the snack emulator linked in the original post. I highly doubt that is using pre-release SDKs.

**Comment by SConaway** [comment]
Sure thing.

With the production XCode selected (images don't work):
```
$ xcodebuild -showsdks
iOS SDKs:
	iOS 13.5                      	-sdk iphoneos13.5

iOS Simulator SDKs:
	Simulator - iOS 13.5          	-sdk iphonesimulator13.5

macOS SDKs:
	DriverKit 19.0                	-sdk driverkit.macosx19.0
	macOS 10.15                   	-sdk macosx10.15

tvOS SDKs:
	tvOS 13.4                     	-sdk appletvos13.4

tvOS Simulator SDKs:
	Simulator - tvOS 13.4         	-sdk appletvsimulator13.4

watchOS SDKs:
	watchOS 6.2                   	-sdk watchos6.2

watchOS Simulator SDKs:
	Simulator - watchOS 6.2       	-sdk watchsimulator6.2
```

With the beta XCode (images don't work):
```
$ xcodebuild -showsdks
iOS SDKs:
	iOS 14.0                      	-sdk iphoneos14.0

iOS Simulator SDKs:
	Simulator - iOS 14.0          	-sdk iphonesimulator14.0

macOS SDKs:
	DriverKit 20.0                	-sdk driverkit.macosx20.0
	macOS 10.16                   	-sdk macosx10.16

tvOS SDKs:
	tvOS 14.0                     	-sdk appletvos14.0

tvOS Simulator SDKs:
	Simulator - tvOS 14.0         	-sdk appletvsimulator14.0

watchOS SDKs:
	watchOS 7.0                   	-sdk watchos7.0

watchOS Simulator SDKs:
	Simulator - watchOS 7.0       	-sdk watchsimulator7.0
```

Again, as @rmacqueen, @ryanpag3 and @DennisdeWitNL said, it occurs with the production XCode and iOS 13.x.

In the example snack, however, my phone successfully loads the local and base64 images, but not the remote one. I'm able to access it in Chrome on my computer and iPhone Safari, so there's an issue there as well. 

Clearing my DerivedData seems to have resolved this issue on both SDK versions. Give that a shot. Sorry for the slow response time @rdperottoni, I am a dual-core i5 MBP that builds slowly.

**Comment by ryanpag3** [comment]
@SConaway What was your technique for clearing your DerivedData? I deleted my project folder @ `~/Library/Developer/Xcode/DerivedData/` and it did not fix the issue for me.

**Comment by legion-zver** [comment]
> All images not loading for me on iOS 14 beta

See https://github.com/SDWebImage/SDWebImage/pull/3043/commits/bb7b1914e6091a04feae858ad2fb85aa37ecd87d

**Comment by DennisdeWitNL** [comment]
> > All images not loading for me on iOS 14 beta
> 
> See [SDWebImage/SDWebImage@bb7b191](https://github.com/SDWebImage/SDWebImage/commit/bb7b1914e6091a04feae858ad2fb85aa37ecd87d)

How do we integrate this fix with React Native? Where does React Native keep the SDWebImage library?

**Comment by QuintonC** [comment]
I'm also experiencing this issue, but only on iOS 14.

Images are working/loading just fine on iOS 13.x, but as soon as the same app is put on iOS 14 images are not displaying (neither local or remote).

**Comment by SConaway** [comment]
That's odd. Building with the 13.5 SDK results in working images. Can anyone test building with the 14 SDK and using an iOS 13 (or before) iPhone?

**Comment by QuintonC** [comment]
> That's odd. Building with the 13.5 SDK results in working images. Can anyone test building with the 14 SDK and using an iOS 13 (or before) iPhone?

@SConaway I just switched over to iOS 14 SDK and am running on a 13.5 iPhone 11 Simulator: 

![Screen Shot 2020-06-26 at 10 31 09 PM](https://user-images.githubusercontent.com/4250423/85912731-d451e580-b7fc-11ea-9e57-98e97b4ccf54.png)


```
➜  ~ xcodebuild -showsdks
iOS SDKs:
	iOS 14.0                      	-sdk iphoneos14.0

iOS Simulator SDKs:
	Simulator - iOS 14.0          	-sdk iphonesimulator14.0

macOS SDKs:
	DriverKit 20.0                	-sdk driverkit.macosx20.0
	macOS 10.16                   	-sdk macosx10.16

tvOS SDKs:
	tvOS 14.0                     	-sdk appletvos14.0

tvOS Simulator SDKs:
	Simulator - tvOS 14.0         	-sdk appletvsimulator14.0

watchOS SDKs:
	watchOS 7.0                   	-sdk watchos7.0

watchOS Simulator SDKs:
	Simulator - watchOS 7.0       	-sdk watchsimulator7.0
```

When running in 13.5 simulator all images show as intended. You can see a video of it running in iOS 13.5 [here.](https://drive.google.com/file/d/1LnfzfaZxGxnmbxOyuEwa4Bt9IGSPNFnQ/view?usp=sharing)

when running in 14.0 simulator with iOS 14.0 SDK none of the images display. You can see a video of that [here.](https://drive.google.com/file/d/1bLl2OCHGziyvE55x5W7uSFCIniZP1_kt/view?usp=sharing)

**Comment by QuintonC** [comment]
So, interesting discovery --

I rebuilt the application on another Mac that was using Catalina. Rebuilt with the most recent prod-ready Xcode version and the application built successfully and images are displaying (even in iOS 14.0).

So it looks like iOS 14 itself isn't the issue.

**Comment by DennisdeWitNL** [comment]
> So, interesting discovery --
> 
> I rebuilt the application on another Mac that was using Catalina. Rebuilt with the most recent prod-ready Xcode version and the application built successfully and images are displaying (even in iOS 14.0).
> 
> So it looks like iOS 14 itself isn't the issue.

I built the app with iOS 13 SDK and even on iOS 14 the images show perfectly fine. I built the app on Big Sur. The problem either is Xcode 12 or iOS 14 SDK.

**Comment by QuintonC** [comment]
> > So, interesting discovery --
> > I rebuilt the application on another Mac that was using Catalina. Rebuilt with the most recent prod-ready Xcode version and the application built successfully and images are displaying (even in iOS 14.0).
> > So it looks like iOS 14 itself isn't the issue.
> 
> I built the app with iOS 13 SDK and even on iOS 14 the images show perfectly fine. I built the app on Big Sur. The problem either is Xcode 12 or iOS 14 SDK.

That's what I'm thinking as well. Initially, I thought it was an iOS 14 issue, but that wouldn't have made sense anyway since other apps were loading images just fine.

**Comment by rmacqueen** [comment]
The snack linked in original post does _not_ work on iOS device running iOS 13.4.1

**Comment by lucasriondel** [comment]
RN 0.62.2, iOS 13.5.1 and xcode 11.5 here, working perfectly. But I'm facing issues on local images, only on Android.

**Comment by legion-zver** [comment]
@DennisdeWitNL use patch-package and my patch file (work with rn 0.63)

`react-native+0.63.0.patch`

```
diff --git a/node_modules/react-native/Libraries/Image/RCTUIImageViewAnimated.m b/node_modules/react-native/Libraries/Image/RCTUIImageViewAnimated.m
index 21f1a06..2444713 100644
--- a/node_modules/react-native/Libraries/Image/RCTUIImageViewAnimated.m
+++ b/node_modules/react-native/Libraries/Image/RCTUIImageViewAnimated.m
@@ -272,6 +272,9 @@ - (void)displayDidRefresh:(CADisplayLink *)displayLink
 
 - (void)displayLayer:(CALayer *)layer
 {
+  if (!_currentFrame) {
+    _currentFrame = self.image;
+  }
   if (_currentFrame) {
     layer.contentsScale = self.animatedImageScale;
     layer.contents = (__bridge id)_currentFrame.CGImage;
diff --git a/node_modules/react-native/scripts/.packager.env b/node_modules/react-native/scripts/.packager.env
new file mode 100644
index 0000000..361f5fb
--- /dev/null
+++ b/node_modules/react-native/scripts/.packager.env
@@ -0,0 +1 @@
+export RCT_METRO_PORT=8081
```

**Comment by DennisdeWitNL** [comment]
> @DennisdeWitNL use patch-package and my patch file (work with rn 0.63)
> 
> `react-native+0.63.0.patch`
> 
> ```
> diff --git a/node_modules/react-native/Libraries/Image/RCTUIImageViewAnimated.m b/node_modules/react-native/Libraries/Image/RCTUIImageViewAnimated.m
> index 21f1a06..2444713 100644
> --- a/node_modules/react-native/Libraries/Image/RCTUIImageViewAnimated.m
> +++ b/node_modules/react-native/Libraries/Image/RCTUIImageViewAnimated.m
> @@ -272,6 +272,9 @@ - (void)displayDidRefresh:(CADisplayLink *)displayLink
>  
>  - (void)displayLayer:(CALayer *)layer
>  {
> +  if (!_currentFrame) {
> +    _currentFrame = self.image;
> +  }
>    if (_currentFrame) {
>      layer.contentsScale = self.animatedImageScale;
>      layer.contents = (__bridge id)_currentFrame.CGImage;
> diff --git a/node_modules/react-native/scripts/.packager.env b/node_modules/react-native/scripts/.packager.env
> new file mode 100644
> index 0000000..361f5fb
> --- /dev/null
> +++ b/node_modules/react-native/scripts/.packager.env
> @@ -0,0 +1 @@
> +export RCT_METRO_PORT=8081
> ```

I can confirm this worked! Thank you!

For those who don't know how this works:

npm i -g patch-package
Make a new folder called packaged
Make a new file called react-native+0.63.0.patch
Add the source code above.
patch-package
enter

**Comment by abiespinal04** [comment]
> npm i -g patch-package

where do you make the new folder?

**Comment by joewired** [comment]
I made a folder called patches at the root of the project and it worked.

However; with the patch, the images show up but they do  not update (size, etc) - They are just stuck.

**Comment by DennisdeWitNL** [comment]
@abiespinal04 You make a new folder called ‘patches’ right in your React Native project folder. 

@joewired This is strange. I applied the patch too, and I have multiple images with a width and height of 50 pixels, just as I programmed. And I also have a screen width filling Image Background, which is working fine too. I don’t have this problem.

**Comment by scarlac** [comment]
I can confirm that @DennisdeWitNL's fix https://github.com/facebook/react-native/issues/29215#issuecomment-657231577 also works for React Native 0.61.2, using Xcode 12 beta 3, iOS 14 simulator.

**Comment by shoopi12** [comment]
is it a good idea to use this patch? any possible negative side effects?
How long are we expected to need this patch? do I need to manually delete it later when the issue is fixed?

**Comment by ryanpag3** [comment]
@DennisdeWitNL's solution worked for me, although I made a few small adjustments.

1. Install packages locally 
`yarn patch-package postinstall-postinstall`
2. include new script in `package.json` that will run this after you invoke `yarn install` (or equivalent)
```
    "postinstall": "patch-package"
```

These steps were found in the `patch-package` README.

**Comment by maxbaldrighi** [comment]
My problem was with both local and uri images.

I was able to fix the issue by applying the suggested patch. I confirm that works well with previous RN versions:

- RN: 0.62.2
- Xcode: 12.0
- iOS simulator: 14

**Comment by dragonfire1119** [comment]
Same problem with local & remote not showing images.

The fix is the patch https://github.com/facebook/react-native/issues/29215#issuecomment-657231577

This patch does work on older RN versions.

Reach Native: 0.61.2
Xcode: 12.0
iOS Sim: 14

**Comment by andrewaarestad** [comment]
Worked for me with:

React Native: 0.61.5
Xcode: 12.0

I did the same as @ryanpag3 with one small tweak for step 1:
```
yarn add patch-package postinstall-postinstall
```

**Comment by keung7251** [comment]
Error: Patch file found for package  react-native which is not present at node_modules/ react-native

**Comment by eowino** [comment]
I came across this same issue too yesterday after an OS update. Lost a few hours trying to figure out the problem. Updating to the [latest version](https://github.com/facebook/react-native/commits/0.63-stable) of react-native fixed it for me, it looks like it contains the [fix](https://github.com/facebook/react-native/pull/29420).

**Comment by Dror-Bar** [comment]
@eowino you mean version 0.63.2?

**Comment by eowino** [comment]
@Dror-Bar Yes, 0.63.2.

**Comment by zhangyandong** [comment]
#import "RCTUIImageViewAnimated+WLAdd.h"
#import <objc/runtime.h>

@implementation RCTUIImageViewAnimated (WLAdd)

+(void)load {
  static dispatch_once_t onceToken;
  dispatch_once(&onceToken, ^{
    Method fromMethod = class_getInstanceMethod([self class], @selector(displayLayer:));
    Method toMethod = class_getInstanceMethod([self class], @selector(wl_displayLayer:));
    method_exchangeImplementations(fromMethod, toMethod);
  });
}

- (void)wl_displayLayer:(CALayer *)layer {
  UIImage *currentFrame = [self valueForKey:@"currentFrame"];
  CGFloat animatedImageScale = [[self valueForKey:@"animatedImageScale"] floatValue];
  if (currentFrame) {
      layer.contentsScale = animatedImageScale;
      layer.contents = (__bridge id)currentFrame.CGImage;
    } else {
      [super displayLayer:layer];
    }
}

@end

**Comment by zhangyandong** [comment]
`#import "RCTUIImageViewAnimated+WLAdd.h"
#import <objc/runtime.h>

@implementation RCTUIImageViewAnimated (WLAdd)

+(void)load {
  static dispatch_once_t onceToken;
  dispatch_once(&onceToken, ^{
    Method fromMethod = class_getInstanceMethod([self class], @selector(displayLayer:));
    Method toMethod = class_getInstanceMethod([self class], @selector(wl_displayLayer:));
    method_exchangeImplementations(fromMethod, toMethod);
  });
}

- (void)wl_displayLayer:(CALayer *)layer {
  UIImage *currentFrame = [self valueForKey:@"currentFrame"];
  CGFloat animatedImageScale = [[self valueForKey:@"animatedImageScale"] floatValue];
  if (currentFrame) {
      layer.contentsScale = animatedImageScale;
      layer.contents = (__bridge id)currentFrame.CGImage;
    } else {
      [super displayLayer:layer];
    }
}

@end`

**Comment by zhangyandong** [comment]
`#import "RCTUIImageViewAnimated+WLAdd.h"
#import <objc/runtime.h>

@implementation RCTUIImageViewAnimated (WLAdd)

+(void)load {
  static dispatch_once_t onceToken;
  dispatch_once(&onceToken, ^{
    Method fromMethod = class_getInstanceMethod([self class], @selector(displayLayer:));
    Method toMethod = class_getInstanceMethod([self class], @selector(wl_displayLayer:));
    method_exchangeImplementations(fromMethod, toMethod);
  });
}

- (void)wl_displayLayer:(CALayer *)layer {
  UIImage *currentFrame = [self valueForKey:@"currentFrame"];
  CGFloat animatedImageScale = [[self valueForKey:@"animatedImageScale"] floatValue];
  if (currentFrame) {
      layer.contentsScale = animatedImageScale;
      layer.contents = (__bridge id)currentFrame.CGImage;
    } else {
      [super displayLayer:layer];
    }
}

@end`

**Comment by zhangyandong** [comment]
```

#import "RCTUIImageViewAnimated+WLAdd.h"
#import <objc/runtime.h>

@implementation RCTUIImageViewAnimated (WLAdd)

+(void)load {
  static dispatch_once_t onceToken;
  dispatch_once(&onceToken, ^{
    Method fromMethod = class_getInstanceMethod([self class], @selector(displayLayer:));
    Method toMethod = class_getInstanceMethod([self class], @selector(wl_displayLayer:));
    method_exchangeImplementations(fromMethod, toMethod);
  });
}

- (void)wl_displayLayer:(CALayer *)layer {
  UIImage *currentFrame = [self valueForKey:@"currentFrame"];
  CGFloat animatedImageScale = [[self valueForKey:@"animatedImageScale"] floatValue];
  if (currentFrame) {
      layer.contentsScale = animatedImageScale;
      layer.contents = (__bridge id)currentFrame.CGImage;
    } else {
      [super displayLayer:layer];
    }
}

@end
```

**Comment by QueenTallicia69-cloud** [comment]
try and test...
🤷‍♀️🤷‍♀️🤷‍♀️

Op vr 18 sep. 2020 02:44 schreef shoopi12 <notifications@github.com>:

**Comment by bpred754** [comment]
For those running older versions of React Native (e.g., 0.60.6) the patch is not possible since the `RCTUIImageViewAnimated.m` file doesn't exist. I solved this problem by using [React Native Fast Image](https://github.com/DylanVann/react-native-fast-image) v8.1.5 and upgrading SDWebImage pod with `pod update SDWebImage`. More specifically, I upgraded SDWebImage from v5.8.1 to v5.9.2.

**Comment by VisheshNucleusTeq** [comment]
**If any one is still facing the problem here are stepwise solution which worked for me :-**

1. Navigate to **node_modules>>react-native>>Libraries>>image**
2. Open **RCTUIImageViewAnimated.m** in your fav. editor 
3. Replace the following code 
`if (_currentFrame) {
    layer.contentsScale = self.animatedImageScale;
    layer.contents = (__bridge id)_currentFrame.CGImage;
  }` 
with
`if (_currentFrame) {
    layer.contentsScale = self.animatedImageScale;
    layer.contents = (__bridge id)_currentFrame.CGImage;
  }else {
    [super displayLayer:layer];
  }`
4. Save the file 
5. Close the packager if already running 
6. ReLaunch the application (npx/ yarn ios)

**Comment by Dror-Bar** [comment]
@VisheshNucleusTeq the issue with editing a node_modules library directly is that after reinstalling with npm install for example, all of those edits are lost. This is a sure way to get very hard to find bugs later on.

**Comment by VisheshNucleusTeq** [comment]
@Dror-Bar  
this is a temp solution this won't be need with the upcoming update 
creating the post install script must be kept as first way  but if that doesn't work then this is sure shot solution

**Comment by sam-freelancer** [comment]
> 3\. if (_currentFrame) { layer.contentsScale = self.animatedImageScale; layer.contents = (__bridge id)_currentFrame.CGImage;   }else { [super displayLayer:layer];   }

this patch worked

**Comment by sam-freelancer** [comment]
> **If any one is still facing the problem here are stepwise solution which worked for me :-**
> 
> 1. Navigate to **node_modules>>react-native>>Libraries>>image**
> 2. Open **RCTUIImageViewAnimated.m** in your fav. editor
> 3. Replace the following code
>    `if (_currentFrame) { layer.contentsScale = self.animatedImageScale; layer.contents = (__bridge id)_currentFrame.CGImage;   }`
>    with
>    `if (_currentFrame) { layer.contentsScale = self.animatedImageScale; layer.contents = (__bridge id)_currentFrame.CGImage;   }else { [super displayLayer:layer];   }`
> 4. Save the file
> 5. Close the packager if already running
> 6. ReLaunch the application (npx/ yarn ios)

this worked like butter

**Comment by oporter1** [comment]
I am still not able to see any images with the iOs 14.2 update. I have implemented:
1. npm install --save react-native-fix-image
2. react-native+0.63.0.patch
3. manually within node_modules

Is anyone else seeing these solutions not working for them?


I am on:
react-native-cli: 2.0.1
react-native: 0.61.4
Managed Expo:
  Expo CLI 3.28.2 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 15.0.1 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.0.3 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    IDEs:
      Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.12 => 37.0.12 
      react: 16.9.0 => 16.9.0 
      react-dom: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4 
      react-native-web: ^0.11.7 => 0.11.7 
      react-navigation: ^3.13.0 => 3.13.0 
    npmGlobalPackages:
      expo-cli: 3.28.2
    Expo Workflow: managed

**Comment by paulbreslin** [comment]
Finally fixed this by downgrading react-native from `0.63.3` to `0.63.0`. Then applied the [patch](https://github.com/facebook/react-native/issues/29279#issuecomment-657284028) using the postinstall npm script.

Also, remember to set a width and height on the image style as it could be loading but just not displaying properly - this threw me off for a bit during testing.

**Comment by nHiRanZ** [comment]
> **If any one is still facing the problem here are stepwise solution which worked for me :-**
> 
> 1. Navigate to **node_modules>>react-native>>Libraries>>image**
> 2. Open **RCTUIImageViewAnimated.m** in your fav. editor
> 3. Replace the following code
>    `if (_currentFrame) { layer.contentsScale = self.animatedImageScale; layer.contents = (__bridge id)_currentFrame.CGImage;   }`
>    with
>    `if (_currentFrame) { layer.contentsScale = self.animatedImageScale; layer.contents = (__bridge id)_currentFrame.CGImage;   }else { [super displayLayer:layer];   }`
> 4. Save the file
> 5. Close the packager if already running
> 6. ReLaunch the application (npx/ yarn ios)

Worked like a charm!

**Comment by Bullden** [comment]
@VisheshNucleusTeq  thank you. It is really help me

**Comment by gnprice** [comment]
As mentioned [above](https://github.com/facebook/react-native/issues/29215#issuecomment-695954736), this issue appears to be a duplicate of #29279. The issue is fixed in v0.63.2 (with https://github.com/facebook/react-native/commit/b6ded7261544c703e82e8dbfa442dad4b201d428) and the upcoming v0.64 (with https://github.com/facebook/react-native/commit/123423c2a9258c9af25ca9bffe1f10c42a176bf3).

It'd be good for someone who's able to do so to mark this issue as closed.

**Comment by erdugen** [comment]
I using 0.63.4 and cli 2.0.1.
It's still continue this issue.
I'm using this link http://placehold.it/32x32
simulator 14.3

**Comment by Andrea-Arguello** [comment]
I am using RN 0.61.5 and Xcode 11.1, I am still getting this issue, but only when I try to make a Release build. Adding the else to node_modules/react-native/Libraries/Image/RCTUIImageViewAnimated.m only worked for Debug buids.
Could this also be an issue with a Pods library? I am getting ```[framework] CUICatalog: Invalid asset name supplied: '(null)'``` on Xcode's logs

**Comment by anback** [comment]
I solved this by using `react-native-fast-image`

**Comment by infinitbility** [comment]
Any dev want to `patch-package` step by step doc to solve image issue checkout below link

https://infinitbility.com/image-not-showing-in-ios-14-react-native

**Comment by UsmanJ** [comment]
> Any dev want to `patch-package` step by step doc to solve image issue checkout below link
> 
> https://infinitbility.com/image-not-showing-in-ios-14-react-native

I'm having this issue with my app on an actual device with the release build (images from URI only). However, on the simulator it works perfectly fine. Would this fix also work for this scenario?

Thanks

**Comment by MerryCello** [comment]
URI (from cache or web) image won't load either on physical device ios 14.4

using:
* react-native: 4.14.0
* expo: 4.1.6
* node: 14.15.4

**Comment by WashingtonLuiz99** [comment]
> **Se alguém ainda está enfrentando o problema, aqui estão uma solução passo a passo que funcionou para mim: -**
> 
> 1. Navegue até **node_modules >> react-native >> Libraries >> image**
> 2. Abra **RCTUIImageViewAnimated.m** em seus favoritos. editor
> 3. Substitua o seguinte código 
>    `if (_currentFrame) { layer.contentsScale = self.animatedImageScale; layer.contents = (__bridge id)_currentFrame.CGImage;   }`
>    por
>    `if (_currentFrame) { layer.contentsScale = self.animatedImageScale; layer.contents = (__bridge id)_currentFrame.CGImage;   }else { [super displayLayer:layer];   }`
> 4. Salve o arquivo
> 5. Feche o empacotador se já estiver em execução
> 6. Reinicie o aplicativo (npx / yarn ios)

That solved for me thank you

**Comment by perdona** [comment]
> > Any dev want to `patch-package` step by step doc to solve image issue checkout below link
> > https://infinitbility.com/image-not-showing-in-ios-14-react-native
> 
> I'm having this issue with my app on an actual device with the release build (images from URI only). However, on the simulator it works perfectly fine. Would this fix also work for this scenario?
> 
> Thanks

I'm having the same issue. Works fine on simulator. When I release it to TestFlight, it does not show remote images.

**Comment by BenHurMartins** [comment]
Hi everyone, face this issue today, Xcode 12, and iOS 14.3, tried the patch. without success,

So in the end of the url, that was using 'http', I replaced for 'https' and it worked:

.replace('http','https')

In my case my urls are http.

**Comment by curchadw** [comment]
I might be in the wrong place, but I am using my android device and when I try to view the screen in my browser I can see the login screen with image file fine, but when I scan the qr code to my phone, the console is telling me that  the image file does not exist.  I am wondering if this is similar to this issues.
