### ISSUE TITLE
[iOS][TextInput] Space doesn't switch back to default keyboard type

### ISSUE THREAD

**Issue by jparksecurity** [facebook/react-native#29216]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Clicking space bar on the iOS numbers-and-punctuation type should switch to the iOS default type.
But it sometimes doesn't work as expected on TextInput.
What I found so far is
1. if you have `value` prop, it doesn't work.
2. if you have `value` and set `multiline` true, it works.
3. if you don't have `value` prop, it works

Refer to [here](https://lefkowitz.me/visual-guide-to-react-native-textinput-keyboardtype-options/) to see how each type looks.
Refer to [here](https://discussions.apple.com/thread/2417454?threadID=2417454) to understand better this behavior
## React Native version:
```
System:
    OS: macOS 10.15.5
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 47.82 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.16.1 - /var/folders/d0/7pxjwmtn02q_plh_g1wwjl9r0000gn/T/yarn--1593047685741-0.06260074613902389/node
    Yarn: 1.22.4 - /var/folders/d0/7pxjwmtn02q_plh_g1wwjl9r0000gn/T/yarn--1593047685741-0.06260074613902389/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6308749
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  npmPackages:
    react: ~16.9.0 => 16.9.0 
    react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Go to https://snack.expo.io/?session_id=snack-session-00oEA18O_&preview=true&platform=web&iframeId=cyl5x0bd8b&supportedPlatforms=ios,android,web&name=TextInput&description=Example%20usage&waitForData=true (it's https://reactnative.dev/docs/textinput snack example)
2. Run the code on iOS
3. Type some number and symbol, then type space
4. Confirm that it doesn't switch back to the default type
5. pass `multiline` prop in source code
6. Repeat number 3
7. Confirm that it switches back to the default
8. Remove `value` and `multiline` props
9. Repeat number 3, 7

## Expected Results
Clicking space bar on the iOS numbers-and-punctuation type should switch to the iOS default type.

## Snack, code example, screenshot, or link to a repository:
https://snack.expo.io/?session_id=snack-session-00oEA18O_&preview=true&platform=web&iframeId=cyl5x0bd8b&supportedPlatforms=ios,android,web&name=TextInput&description=Example%20usage&waitForData=true

**Comment by pynner** [comment]
Happening for me as well in RN 63.3.

You're a legend for finding that adding `multiline` to the TextInput is a workaround ❤️
