### ISSUE TITLE
[RN 0.61.1] Android TV d-pad navigation keys not working after menu key press

### ISSUE THREAD

**Issue by sureshsu** [facebook/react-native#29210]
## Description
Sometimes D-pad / navigation key events not coming after menu key press. 

## React Native version:
Run `react-native info` in your terminal and copy the results here.
System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 529.74 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.16.2 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.1 => 0.61.1
  npmGlobalPackages:
    react-native-cli: 2.0.1

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.
Attached the sample apk to reproduce the issue
1. Install the apk in a Android TV device (emulator or actual device)
2. Launch the apk (Awesome app)
3. Press menu key in TV remote or input key from terminal using - adb shell input keyevent 82 
4. Again press menu key in TV remote or send again from terminal - adb shell input keyevent 82
5. Now press any d-pad key in TV remote or input key from terminal - adb shell input keyevent 19 (or 20 or 21 or 22)

Another variation:
1. launch apk for first time.
2. press any d-pad navigation key (or use adb shell to inject key events)
3. press MENU key.
4. Press any d-pad /navigation key.
5. Press MENU key.
6. Press any navigation key (here no navigation key events reach Java code or RN code)

## Expected Results
1. Navigation key events should reach React native code nor Java code. But it doesn't .  Check the logs while running the apk.

## Snack, code example, screenshot, or link to a repository:
Note: This sample contains npm react-native-keyevent for key handling but even if this package is not used, the issue can be observed.

public class MainActivity extends ReactActivity {

  /**
   * Returns the name of the main component registered from JavaScript. This is used to schedule
   * rendering of the component.
   */
  @Override
  protected String getMainComponentName() {
    return "AwesomeProject";
  }

  @Override
  public boolean onKeyDown(int keyCode, KeyEvent event) {
    Log.d("onKeyDown", "onKeyDown: " + keyCode);
    KeyEventModule.getInstance().onKeyDownEvent(keyCode, event);
    return super.onKeyDown(keyCode, event);
  }

  @Override
  public boolean onKeyUp(int keyCode, KeyEvent event) {
    Log.i("onKeyUp", "onKeyUp: " + keyCode);
    KeyEventModule.getInstance().onKeyUpEvent(keyCode, event);
    return super.onKeyUp(keyCode, event);
  }

  @Override
  public boolean onKeyLongPress(int keyCode, KeyEvent event) {
    Log.d("onKeyLongPress", "onKeyLongPress: " + keyCode);
    return super.onKeyLongPress(keyCode, event);
  }

  @Override
  public boolean onKeyMultiple(int keyCode, int repeatCount, KeyEvent event) {
    Log.d("onKeyMultiple", "onKeyMultiple: " + keyCode);
    KeyEventModule.getInstance().onKeyMultipleEvent(keyCode, repeatCount, event);
    return super.onKeyMultiple(keyCode, repeatCount, event);
  }
}

Recovery: 
The only way after multiple menu key press (3 or more) after which d-pad navigation keys work.

[app-release.apk.zip](https://github.com/facebook/react-native/files/4824879/app-release.apk.zip)

**Comment by fabriziobertoglio1987** [comment]
no need for the apk, but include a github repo with minimum code to reproduce this issue.

**Comment by sureshsu** [comment]
@fabriziobertoglio1987 
Refer to github repo: https://github.com/sureshsu/rn-menu-issue/tree/master/AwesomeProject

**Comment by sureshsu** [comment]
@fabriziobertoglio1987
Any fix possible for the issue? Already shared the repo.

**Comment by sureshsu** [comment]
By re-arranging the code usage for react-native-keyevent and conditional statements, avoided the issue.
