### ISSUE TITLE
NativeModules are empty

### ISSUE THREAD

**Issue by Sebulec** [facebook/react-native#29228]
## Description
When creating new native library for application, when library is attached to the react native mobile application in iOS, the NativeModules are empty (`{}`)

## React Native version:
System:
    OS: macOS 10.15.5
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Memory: 30.54 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.14.1 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.14.2 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6308749
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    create-react-native-app: 3.4.0
    react-native-create-library: 3.1.2
    react-native: 0.61.4

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Create new RN application using `create-react-native-app my-project`
2. Create new native library using ` react-native-create-library -—platforms ios,android my-library`
3. Configure XCode .xcworkspace project, link React library to the project, to let project see React binaries.
4. In my-project app add 
```
import { Button, NativeModules } from 'react-native';
const App: () => React$Node = () => {
  return (
    <>
      <StatusBar barStyle="dark-content" />
      <SafeAreaView>
        <Button title="Press" onPress={() => onPress()}></Button>
      </SafeAreaView>
    </>
  );

  function onPress() {
    console.log(NativeModules);
  }
};
```

## Expected Results
It doesn't matter if it's XCode 11 or XCode 10, the NativeModules is empty. When printing 
NativeModules.MyLibrary it's null.

**Comment by chrisbobbe** [comment]
Does the behavior vary with remote JS debugging being enabled and disabled?

**Comment by Sebulec** [comment]
@chrisbobbe Thanks for response, when JS is enabled, I can see some libraries but there is no MyLibrary.
![Zrzut ekranu 2020-07-10 o 07 13 43](https://user-images.githubusercontent.com/11884019/87118986-12c7b580-c27d-11ea-88ee-4ec7257539e8.png)

**Comment by mojtabasji** [comment]
i have same issue
nativeModule returns null for both android and ios

**Comment by 123jiacheng123** [comment]
> 

我也是，请问你解决了 吗？

**Comment by rb185264** [comment]
I too.

**Comment by macro6461** [comment]
Anybody working on this issue or has anyone found a fix? I am currently experiencing the issue too.

expo: "~48.0.4"
react: "18.2.0"
react-native: "0.71.3"

Gradle version is 7.5.1.
XCode version is 1.74.3 (Universal)

Can't share the project as it is private but I was working from [this tutorial.](https://reactnative.dev/docs/native-modules-android).

**Comment by silvabacc** [comment]
Yes, I am feeling the same issue on the same version of `react-native` `0.71.3`. I can see a duplicate issue [here](https://github.com/facebook/react-native/issues/35302). I followed the same guide @macro6461

**Comment by lumairink** [comment]
Same happening on version `0.71.13`

**Comment by Gowthamr221** [comment]
Happening to me i created a native component following the guide from react native docs the native component returns null 
on version` 0.73.1`. i found old discussion about this issue[Native Modules #96]( https://github.com/react-native-community/discussions-and-proposals/issues/96) but no proper resolution yet.

**Comment by SamuelScheit** [comment]
I encountered a similar issue after upgrading to version 0.75.2 with the new architecture enabled.

My observations was that `NativeModules` appears empty during the app's startup.

Specifically, when iterating over the keys of `NativeModules`, it returns an empty object.
However, accessing the native functions directly from `NativeModules` works as expected.

This behavior affects React Native packages that expose their native functions using the following pattern:

```js
export default {
    ...NativeModules.MyNativeModule
};
```

Since no keys are defined on `MyNativeModule` at the time of access, this approach returns an empty object. 

To resolve this issue every native function needs to be manually exported as shown below:
```js
export default {
    myNativeFunction: NativeModules.MyNativeModule.myNativeFunction,
    // Manually export all other functions in the same way
};
```

This ensures the native functions are properly available in the exported object.
