### ISSUE TITLE
Error with task: undefined is not an object (evaluating '_this.view{component.measureInWindow')

### ISSUE THREAD

**Issue by wenit123** [facebook/react-native#29226]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Issue after I update the version to... 

"react-native": "0.62.2",
"react-navigation": "^4.3.9",

## React Native version:
Run `react-native info` in your terminal and copy the results here.

System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 25.89 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.10.0 - ~/git/versions/node/v8.8.0/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 5.4.2 - ~/git/versions/node/v8.8.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 21, 23, 24, 26, 28
      Build Tools: 24.0.3, 25.0.0, 26.0.3, 28.0.3, 29.0.3
      System Images: android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_101 - /usr/bin/javac
    Python: 2.7.12 - /Users/Iting/.pyenv/shims/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. run on xcode
2.

## Expected Results
Describe what you expected to happen.

![image](https://user-images.githubusercontent.com/16068081/85798336-26f2ab00-b6f2-11ea-8a46-20cac3d1b026.png)

## Snack, code example, screenshot, or link to a repository:
Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by Coffeegerm** [comment]
Having the same issue trying to upgrade our application from react-native 0.59 to 0.62 and react-navigation from 3.x to 5.x

**Comment by IrfanKhan01** [comment]
Did you find any solution for this @wenit123

**Comment by wenit123** [comment]
@IrfanKhan01 no luck :(  I ended up create a new repo with new version and refactor after

**Comment by Satishpethani92** [comment]
Having the same issue trying to upgrade our application from react-native 0.59 to 0.63.3 and react-navigation from 3.3.0

**Comment by mitjnextt** [comment]
I don't want to create new project, Any better solution for the same?
