### ISSUE TITLE
bounce / overscroll / spring animation missing in scrollview / Flatlist

### ISSUE THREAD

**Issue by nomi9995** [facebook/react-native#29225]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
I know there is `bounce` property for react native, but it only works for iOS, but missing in android.

Here is What I need in android.

[![Example][1]][1]

  [1]: https://i.stack.imgur.com/ja78h.gif

## React Native version:
Run `react-native info` in your terminal and copy the results here.
```
OS: macOS 10.14.4
React Native version:
react: 16.8.6 => 16.8.6
react-native: 0.60.3 => 0.60.3
```

## Steps To Reproduce
try to overscroll in android scrollview or flatlist there will not be bounce

## Expected Results
when we try to overscroll on android it should be overscroll / bounce

**Note:** `CoordinatorLayout` in android working as expected but how can we implement `CoordinatorLayout` in android react native

## Snack, code example, screenshot, or link to a repository:
https://snack.expo.io/@nomi9995/flatlist---bounce

**Comment by maltoze** [comment]
Did you solve it?

**Comment by fantasyado** [comment]
anyone has a solution to this?
