### ISSUE TITLE
[iOS 9] Static Resources (Images) not Showing

### ISSUE THREAD

**Issue by gauravmc** [facebook/react-native#2922]
Updated to 0.11.0 and Xcode 7 simultaneously and static images stopped working. Let me know some sort of starting point (not sure where to start digging for this one) and I can help.

#### Before
<img width="385" alt="screen shot 2015-09-21 at 23 42 56" src="https://cloud.githubusercontent.com/assets/1014540/10010554/f2550812-60ba-11e5-93e1-dfa05611d50a.png">

#### After
<img width="383" alt="screen shot 2015-09-21 at 23 43 46" src="https://cloud.githubusercontent.com/assets/1014540/10010558/f9936358-60ba-11e5-8760-14ac79680910.png">

**Comment by lloydho** [comment]
Had the same issue. Changing the images from jpg to png fixed it for me.

**Comment by mkonicek** [comment]
cc @frantic

**Comment by frantic** [comment]
How do you require the images? `require('image!...')`? Any warnings in Xcode logs?

**Comment by gauravmc** [comment]
@frantic Yea, doing `require('image!...')`. Check [here](https://github.com/gauravmc/Annotations/blob/481ec2d8d0affbc3304123faa21cefa4db3ed915/app/BookRow.js#L31). Will let you know about if there are any warnings later when I can try again

**Comment by ippy04** [comment]
same thing happened to me going from 0.11.4 to 0.13.2. Images being loaded from a URL (or using the new './img/' paths work, but anything in Images.xcassets is just blank now with no error / warning. If I try a filename that doesn't exist in Images.xcassets I get the red error, so it appears as though the require is finding the image, but it's not being displayed. Any ideas?

**Comment by frantic** [comment]
@ippy04 could you please give a link to example project? Are you images pngs? I've just tried it and it works fine (React Native 0.13.2). Note that you have to recompile Xcode project and explicitly set width/height in Image's style for this to work.

**Comment by ippy04** [comment]
Hi @frantic I had width / height set, tried pngs, used same name as the image in Images.xcassets but nothing worked.

Turned out it was this issue: https://github.com/facebook/react-native/issues/3888. Looks like using react-native from cocoapods breaks static image loading both from Images.xcassets and also using the new asset packaging system. Have verified that this commit fixes the problem: https://github.com/facebook/react-native/pull/3889

**Comment by browniefed** [comment]
@facebook-github-bot close

**Comment by andmix** [comment]
@ippy04 i have the same problem in  react-native 0.20.0, xcode 8.1, ios 10.1.1 , how do you resolve it???

**Comment by mahgolfa** [comment]
u should implicity set width and height and give ur images a proper style whether they are static or dynamic images ;)
