### ISSUE TITLE
FlatList scrollToIndex method scrolls to wrong item with RTL

### ISSUE THREAD

**Issue by alexandra-oshmyanskaya** [facebook/react-native#29220]
## Description
Horizontal FlatList scrollToIndex method scrolls to wrong (opposite) item when app uses RTL.
For example, if I call `scrollToIndex(0)` the list will be scrolled to the leftmost item although index 0 is the rightmost one.

## React Native version:
System:
    OS: macOS 10.15.5
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 681.12 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.21.0 - ~/.nvm/versions/node/v10.21.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v10.21.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 28, 30
      Build Tools: 28.0.3, 30.0.0
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_252 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
See snack below

## Expected Results
I expect the FlatList in app with RTL to assign indexes from right to left.

## Snack, code example, screenshot, or link to a repository:
https://snack.expo.io/@iserzhan/sandbox-react-native

**Comment by anastely** [comment]
Hey!
Did you found any workaround to solve this issue?

**Comment by PrgrmmrOleg** [comment]
Found a solution.
```
flatListRef.current.scrollToIndex({
          index: I18nManager.isRTL && Platform.OS === "ios" ? list.length - 1 - index : index,
        });
```
For some reason ios scrolls to the opposite value in rtl localization.
That is, when choosing the latter to the first. When choosing the penultimate to the second and so on.
