### ISSUE TITLE
[iOS][TextInput] I got a TextInput  fixed at bottom , when I type text , how to make TextInput  not  covered by the keyboard . 

### ISSUE THREAD

**Issue by nice2mu** [facebook/react-native#2923]
![an1 0jo1x 6ihj e _g8k0](https://cloud.githubusercontent.com/assets/2330165/10010334/8f1dc420-611c-11e5-98e6-9cd5347d2403.jpg)

![x59q 4ybhgfbhl 3ew7zc](https://cloud.githubusercontent.com/assets/2330165/10010333/8e0b9e72-611c-11e5-9755-b77516a02fda.jpg)

**Comment by deanmcpherson** [comment]
http://stackoverflow.com/questions/29313244/how-to-auto-slide-the-window-out-from-behind-keyboard-when-textinput-has-focus/30773343#30773343

**Comment by nice2mu** [comment]
Awesome!  thanks, buddy !

**Comment by deanmcpherson** [comment]
No worries, @brentvatne @vjeux this can be closed
