### ISSUE TITLE
[NavigatorNavigationBar] Allow widths less than the device width

### ISSUE THREAD

**Issue by JedWatson** [facebook/react-native#2924]
The `NavigatorNavigationBarStyles` module currently uses the device dimensions to precalculate the layout of the three elements supported by the `NavigatorNavigationBar` component; `Title`, `LeftButton` and `RightButton`.

I'm using the `Navigator` in a `Modal` component which only takes up 80% of the screen on an iPad app, but am currently blocked from being able to use the `NavigatorNavigationBar` component with it.

Another use-case needing a less-than-full-width Navigator would would be using it in a split-screen iPad App, with a similar layout to Mail.

Having had a look through the code, I suspect a reasonable way to remove the current limitation would be to turn `NavigatorNavigationBarStyles` into a method that returns calculated dimensions for a given width. For performance it could internally cache the values for any given width, with the expectation there wouldn't be too many widths actually in use by an app.

The Navigator also contains references to hard-set widths and heights, with the comment:

```
// TODO: this is not ideal because there is no guarantee that the navigator
// is full screen, hwoever we don't have a good way to measure the actual
// size of the navigator right now, so this is the next best thing.
```

If there's still no way to measure the size of the navigator, perhaps a reasonable interim solution would be to allow a `width` prop to be provided. While this might change when orientation changes (haven't figured out how that's handled with the current approach...) at the moment I'd be happy with setting custom widths `<=` the smallest edge of the device to work around that issue.

I'm happy to have a go at a PR to fix this if someone can green-light my approach and / or point me in the right direction.

**Comment by brentvatne** [comment]
This seems like a reasonable interim solution to me -- thoughts @ericvicenti? cc @ide 

If you need this soon I would recommend working off of a fork on your project, we're trying to speed up our ability to handle PRs but that's a work in progress still :)

**Comment by ide** [comment]
Could we use `left: 0, right: 0`? Not as flexible as custom widths but works very well with the layout system instead of needing to know the width up front, or waiting one frame for `onLayout`.

**Comment by ericvicenti** [comment]
I agree with @ide's intuition that we should just use the layout system for this. If anything, the measurement hack should be inside of the navigation bar. For some reason I remember there being difficulty with `left: 0, right: 0`, but you are welcome to experiment. I'd be happy to help merge a PR that improves the flexibility while maintaining the existing behavior

**Comment by mkonicek** [comment]
Thanks for looking @ericvicenti!

**Comment by JedWatson** [comment]
Thanks for the quick feedback guys, much appreciated. I've worked around the urgent issue for now by copying `NavigatorNavigationBar.js` and `NavigatorNavigationBarStyles.js` into my project and changing them directly, and I'll experiment with ways to get this working properly.

I think moving the measurement hack into the NavigationBar and turning NavigationBarStyles into a method would be a good start; any concerns about caching the generated values?

Also going to see what I can figure out in terms of getting the size of the component like @ide suggests with `onLayout`. Are there any good examples of that being used elsewhere that I could refer to?

The difficulty I see with using `left` and `right` to position the elements during animations is that they won't work to animate an element from `RightToLeft`.

**Comment by ide** [comment]
> any concerns about caching the generated values

I'm not sure how split-screen view on iPad or some Android tablets works -- whether you can continuously resize them or not. If that's the case we'll want to keep the cache size small.

`onLayout` is pretty straightforward... probably the best way to figure out how it behaves is to try putting it on a View or looking at the UIExplorer's layout demo.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/navigatornavigationbar-allow-widths-less-than-the-device-width

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.
