### ISSUE TITLE
onViewableItemsChanged called with empty viewableItems if index < initialScrollIndex

### ISSUE THREAD

**Issue by 7patricia** [facebook/react-native#29247]
## Description
Hi!

I'm using a `FlatList` to develop a scrollable calendar.
I found an issue while using `onViewableItemsChanged`. If I set `initialScrollIndex` to, for example, 1 and then scroll to the previous item of the list, `onViewableItemsChanged` is triggered but `viewableItems` is empty, while it should have the item at index 0.

This is happening whenever the `initialScrollIndex` is greater than 0.

When `initialScrollIndex` is 0 it works correctly,  I scroll back and forward and it works as expected, `onViewableItemsChanged` always returns the expected `viewableItems`.

## React Native version:
```
System:
    OS: macOS 10.15.5
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 4.56 GB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.20.1 - /usr/local/opt/node@10/bin/node
    Yarn: 1.21.0 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/opt/node@10/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-29 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_231 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found
```
## Steps To Reproduce
1. Create a FlatList;
2. Set `initialScrollIndex` to 1;
2. Define `onViewableItemsChanged` and `viewabilityConfig`;
3. Scroll to the item with index 0 (I'm using `flatListRef.current.scrollToIndex` for that);
4. Check that `onViewableItemsChanged` is called with an empty array on `viewableItems`;

## Expected Results
I expected that when I tried scrolling to the previous index, `onViewableItemsChanged` would be triggered with `viewableItems` being an array with the element on the previous index. 

## Snack, code example, screenshot, or link to a repository:
Here's a code example to show how I'm using the FlatList, and it's configurations: 
```
const viewabilityConfig = {
  itemVisiblePercentThreshold: 10
};

export const Calendar = ({ preSelected }) => {
  ...

  // function that is called when I press an arrow do scroll to the previous item of the list
  const onPressPrevious = () => {
    if (selectedIndex === 0) {
      return;
    }

    const index = selectedIndex - 1;

    flatListRef.current.scrollToIndex({ index });
  };

  const onViewableItemsChanged = useRef(({ viewableItems }) => {
    console.log('viewableItems', viewableItems);
  });

  return (
    ...
    <FlatList
       bounces={false}
       data={months}
       decelerationRate={0}
       getItemLayout={(data, index) => ({ index, length: MONTH_WIDTH, offset: MONTH_WIDTH * index })}
       horizontal
       initialNumToRender={NUMBER_OF_VISIBLE_MONTHS / 2}
       initialScrollIndex={selectedIndex}
       keyExtractor={(item, index) => index}
       maxToRenderPerBatch={NUMBER_OF_VISIBLE_MONTHS}
       onViewableItemsChanged={onViewableItemsChanged.current}
       ref={flatListRef}
       removeClippedSubviews
       renderItem={renderMonth}
       scrollEventThrottle={200}
       showsHorizontalScrollIndicator={false}
       showsVerticalScrollIndicator={false}
       snapToInterval={MONTH_WIDTH}
       viewabilityConfig={viewabilityConfig}
       window={NUMBER_OF_VISIBLE_MONTHS}
    />
);

}

```

**Comment by Sargnec** [comment]
I was having same issue. Some of the items was same so when viewableItems encounter first of the same items it was returning empty array.

**Comment by samuthekid** [comment]
I'm also seeing an issue, and I think it's related to this matter.
If I set initialScrollIndex to 2 for example, the onViewableItemsChanged function gets called, but always with the first item in the list, which we know it's not the one being shown.
In my case, a list of videos, and I play the first in the viewableItems array, but that element is always the one with index 0, and not equal to initialScrollIndex that we set before. So I can see the 3rd video (paused) and the audio from the first one playing.

This only happens in iOS!

**Comment by rogerkerse** [comment]
Having same issue

**Comment by nomi9995** [comment]
it is also with `initialScrollIndex={0}`

**Comment by Yuniac** [comment]
Having the same issue here in 2024 😄 also while trying to use the list to play videos

**Comment by shubhamdeol** [comment]
I had to migrate to flashlist by spotify to fix similar issue.

**Comment by gfaraj** [comment]
Having the same issue
