### ISSUE TITLE
iOS 14 onload app message popup "MyAPP pasted from {other installed app}"

### ISSUE THREAD

**Issue by ghobashy** [facebook/react-native#29254]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
With iOS 14 new release, device is detecting that my app is accessing clipboard and coping data from other apps, however my app not even using Clipboard.

## React Native version:
Run `react-native info` in your terminal and copy the results here.
System:
    OS: macOS 10.15.5
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 170.30 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 11.1.0 - ~/.nvm/versions/node/v11.1.0/bin/node
    Yarn: 1.22.1 - /usr/local/bin/yarn
    npm: 6.5.0 - ~/.nvm/versions/node/v11.1.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 23.0.1, 25.0.0, 25.0.2, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.1, 28.0.3
      System Images: android-28 | Google Play Intel x86 Atom, android-R | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  npmPackages:
    react: 16.11.0 => 16.11.0
    react-native: 0.61.5 => 0.61.5
  npmGlobalPackages:
    create-react-native-app: 2.0.2
    generator-react-native-ignite: 1.13.0
    react-native-cli: 2.0.1
    react-native-ignite: 1.13.0

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Setup an new project with CRNA 
2. Copy any text from another app
3. Open the react native app (iOS 14)
4. then the "MyAPP pasted from {other installed app}" as in screenshot

## Expected Results
No to see this message as I'm not accessing Clipboard

## Screenshot

![Screen Shot 2020-06-30 at 5 19 47 PM](https://user-images.githubusercontent.com/7414889/86144600-2c873100-baf6-11ea-8db0-8ab6d56b3dce.png)

**Comment by tomasfrancomediamonks** [comment]
Facing the same issue, any news?

**Comment by MoOx** [comment]
We need to be careful with this situation as our apps made with RN might been perceived as "spying on their users" ([see tiktok/linkedin & friends reading clipboard on every keystroke](https://gigazine.net/gsc_news/en/20200703-linkedin-clipboard-keystroke/) visible thanks to this tiny notification - even if that's not on every keystroke for RN apps).

Anyway we know it's probably not a big deal on RN side for iOS: there is probably just an action that might happen too early instead of being done when really necessary.

My knowledge of RN internal made me unable to track where this happens but I have the feeling this can be easy to adjust (but I can be wrong).

**Comment by PeteTheHeat** [comment]
I think this might be an expo issue. (My expo-cli is borked right now so I can't debug it).

If I create a new RN app using `npx react-native init` I cannot repro the issue. Just to double check that my device was capable of repro'ing the issue, I added this small snippet to app delegate:

```
- (void)applicationDidBecomeActive:(UIApplication *)application
{
  UIPasteboard *pb = [UIPasteboard generalPasteboard];
  NSString *string = pb.string;
}
```

And was able to see the popup.

**Comment by tomasfrancomediamonks** [comment]
In our case we are experiencing this issue and not using Expo

**Comment by PeteTheHeat** [comment]
@tomasfrancomediamonks do you have any other custom ObjC code? 

Here's why I don't think this is an issue with React Native core:
RN core only has 3 callsites to `[UIPasteboard generalPasteboard]` (which is the only API that triggers this popup to my knowledge) :
1. RCTRedBox - Shouldn't be called unless redbox on screen.
2. RCTTextView - For the "copy" function, makes sense.
3. RCTClipboard - A native module to support getting & setting the clipboard, makes sense. 

Putting breakpoints in all of these^, none of them get hit on startup of a fresh RN app (created with `react-native init`).

**Comment by tomasfrancomediamonks** [comment]
@PeteTheHeat thanks for your support. We don't have custom ObjC code but I looked into our dependencies and the responsible is the FirebaseDynamicLinks Pod.

**Comment by MoOx** [comment]
(For my case, it can be the same, as I have an old version of react-native-firebase as a dependency.)

**Comment by ghobashy** [comment]
@MoOx was it solved when you updated react-native-firebase version?

**Comment by MoOx** [comment]
I didn't yet, but it doesn't seems to be a react-native issue from what I have found in RN codebase.

**Comment by ghobashy** [comment]
I will remove firebase from my project now, and see if it still happens or not. Thanks.

**Comment by PeteTheHeat** [comment]
Cool, so sounds like this is an issue with react-native-firebase. 

If updating that dep doesn't solve the problem, open an issue on that repo. Closing this out :)

**Comment by ghobashy** [comment]
If anyone facing the same issue, once i commented out Firebase/DynamicLinks dependency in my PodFile is went away.

![image](https://user-images.githubusercontent.com/7414889/87664414-7f532080-c765-11ea-801d-273775a236e5.png)

@tomasfrancomediamonks  Thank you.
