### ISSUE TITLE
Run signed release .APK on emulator. Crashes after open.

### ISSUE THREAD

**Issue by luizstacio** [facebook/react-native#29256]
## Description
I'm trying to run a signed release .apk on the Android emulator, and it crashes after open.

The same .apk works perfectly on a real device. But for the automated test workflow I'm working on I need to run the release .apk on the emulator.

To make sure it wasn't a project issue, I created an empty project using `npx react-native init AwesomeProject`, adding only the configuration to generate a signed apk and the problem exists too.

Using `adb logcat` I was able to get the following log: 
![Screen Shot 2020-06-30 at 15 24 44](https://user-images.githubusercontent.com/3941923/86162952-f5a91f00-bae5-11ea-8ac6-40b6dbb2d94b.png)
[complete log](https://gist.github.com/luizstacio/bb1fe7d2d53b81577ac3a398b44a0a14)

## React Native version:
```
System:
    OS: macOS 10.15.5
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 1.00 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
    Yarn: 1.19.1 - ~/.nvm/versions/node/v12.13.0/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v12.13.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6308749
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  npmPackages:
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    react-native-version: 4.0.0
    react-native: 0.61.4
```

## Steps To Reproduce
1. npx react-native init AwesomeProject
2. configure the setting to a signed apk, `signingConfigs.release` on `android/app/build.gradle`
3. cd android && ./gradlew assembleRelease 
4. install the apk on the emulator
5. open the app

**Comment by tobym** [comment]
Same problem for me. I am using the debug keystore with default credentials from `signingConfigs`, building through Android Studio. 

react-native info
```System:
    OS: macOS 10.15.5
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
    Memory: 141.59 MB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.2.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK: Not Found
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.2 - /Users/toby/.jenv/shims/javac
    Python: 3.7.3 - /usr/local/anaconda3/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found
```
