### ISSUE TITLE
Attempt to invoke virtual method 'double java.lang.Double.doubleValue()' on a null object reference

### ISSUE THREAD

**Issue by baharb** [facebook/react-native#29250]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

![Screenshot_2020-06-30-16-46-42-611](https://user-images.githubusercontent.com/12814020/86133865-b656e000-ba9d-11ea-930d-d3e9cef3a198.jpeg)

## React Native version:
Run `react-native info` in your terminal and copy the results here.
RN: 0.57.2

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. When I Click on rows of flatlist in my page. some times the red page is shown. I'm using react-native-udp, and every click is a send and response udp packet from server.
2. Some times when I move between pages in Application.

![Screenshot_2020-06-30-16-46-42-611](https://user-images.githubusercontent.com/12814020/86133781-a0491f80-ba9d-11ea-8ae2-f49b025f970b.jpeg)

**Comment by zwerg44** [comment]
Today, I investigated the similar traceback in my app.
I think this is the common issue, when you try to do something with native stuff of unmounted component.
So, whether this happens, try to check that you component is still mounted, and don't touch unmounted native stuff.
In my case I was calling method on the unmounted MapView in callback.
