### ISSUE TITLE
Component not work when open remote debugger in React Native v 0.62.2 

### ISSUE THREAD

**Issue by hariantara** [facebook/react-native#29253]
I have meet the problem on RN v 0.62.2 all the component not working when running remote debugger ( I use Android 10). 

## Description
First step, I run RN project (without remote debugger running), the apps run well, all component can be access.  When I run into remote debugger mode, my apps run well, but all the component cannot be access, example (text input, button or react navigation not working)

## React Native version:
RN Version 0.62.2

## Step to Fix it

1. run your app on real device or emulator
2. run the remote debugger
3. and see it will not work on your app when remote debugger open, and then try to config debug server host and port mode as you connection with the same IP in your laptop (use the same connection for your laptop and real device)
4. after step number 3, try go to setting on your device (phone or emulator), and disable all automatic time setting to manual time setting, when you try to setup time in your device or emulator, make sure you look time on your pc or laptop and set it up the same as your pc or laptop time to your device (phone or emulator) until the seconds part.
5. refresh your app on your phone or emulator.

**Comment by bneigher** [comment]
Yea this has really affected my android development.. seems the case since i've been on 0.62.2.  Can't debug anything if I cant do anything on my app lol

**Comment by hariantara** [comment]
@bneigher you can follow my way to solve that

**Comment by bneigher** [comment]
I checked, and the clocks are exactly in sync though..

**Comment by hariantara** [comment]
@bneigher please check hour, minute, and seconds, should be the same until the seconds part

**Comment by bneigher** [comment]
@hariantara right, what you're referring to is called the [clock](https://en.wikipedia.org/wiki/System_time), its the internal timekeeping mechanism for machines (android phone, laptop, ect.). I've checked if the clock is in sync (common issue for weird errors) and it is not the case, and this doesn't fix my issue.  Perhaps when you looked into your issue something else changed to get it to work? occasionally it works for me too, but it's inconsistent and unreliable, and mostly is not working.

has anyone else experienced this?

**Comment by hariantara** [comment]
@bneigher look on your phone time setting, disable all auto timezone or network time, and setup your phone time manually and follow base on your laptop or pc time until seconds part of your laptop or pc.

**Comment by m-jachym** [comment]
It doesn't fix the issue for me also :'(
