### ISSUE TITLE
Xcode Warnings on new Project

### ISSUE THREAD

**Issue by sp71** [facebook/react-native#29255]
## Description
When we create a new react project using the recommended [guidelines](https://reactnative.dev/docs/environment-setup) for a non-expo app, hundreds of Xcode warnings are created whenever someone opens the xcworkspace project in the ios directory. 

## React Native version:
```
System:
    OS: macOS 10.15.5
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
    Memory: 719.19 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.5.0 - ~/.nvm/versions/node/v13.5.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v13.5.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 19, 22, 23, 24, 25, 26, 27, 28
      Build Tools: 22.0.1, 26.0.3, 27.0.1, 27.0.3, 28.0.2, 28.0.3, 29.0.0, 29.0.0
      System Images: android-22 | Google APIs Intel x86 Atom, android-25 | Google APIs ARM EABI v7a, android-25 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_252 - /usr/bin/javac
    Python: 3.7.7 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. npx react-native init AwesomeProject
2. open ios/AwesomeProject.xcworkspace
3. Build Xcode Workspace

## Expected Results
* Xcode should not show hundreds of warnings

## Snack, code example, screenshot, or link to a repository:
![image](https://user-images.githubusercontent.com/6192130/86159545-5cffa880-babf-11ea-84d5-26464f3ade43.png)

## Solution
Updating the Podfile with the following snippet to be called in post_install loop resolves hundreds of Xcode warnings. What is everyone's thoughts on adding this to the default Podfile template? 

```
def min_OSTarget_post_install(installer)
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if Gem::Version.new('9.0') > Gem::Version.new(config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'])
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
  end
end
```

## Solution Screenshot

![image](https://user-images.githubusercontent.com/6192130/86159770-a3550780-babf-11ea-8235-85cad6b26229.png)

**Comment by PaulSzymanski** [comment]
Doesn't work. Still getting thounthands of errors

**Comment by PaulSzymanski** [comment]
This worked for me: https://stackoverflow.com/a/13209057
