### ISSUE TITLE
Warning: Encountered two children with the same key, %s. 

### ISSUE THREAD

**Issue by ShivamNamdeo** [facebook/react-native#29266]
Warning: Encountered two children with the same key, `%s`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.%s, 2jhW7D0lk2OxKnlzjyusFMgZaEs2,

**Comment by chrisbobbe** [comment]
This looks like the expected behavior, described at https://reactjs.org/docs/lists-and-keys.html#keys, I think?
