### ISSUE TITLE
Adding borderRadius to Image on Android pixelates the image

### ISSUE THREAD

**Issue by tautvilas** [facebook/react-native#29265]
Adding borderRadius to Image on Android pixelates the image. I am attaching example images and source code.

### Without border radius

`<Image style={} source={require('path/to/image')} />`

![Screenshot 2020-07-02 at 13 52 31](https://user-images.githubusercontent.com/1044090/86350474-69c0ff80-bc6b-11ea-880f-f5e4bc28f7a6.png)

### With border radius

`<Image style={{borderRadius: 8}} source={require('path/to/image')} />`

![Screenshot 2020-07-02 at 13 52 59](https://user-images.githubusercontent.com/1044090/86350479-6c235980-bc6b-11ea-8a0e-3ee56c041995.png)

This issue prevents me from displaying beautiful HD images for my customers on android. One workaround that I tried was to use container element with borderRadius and overflow: 'hidden', however that introduces jagged borders.

### With container border radius and overflow hidden

`<View style={{borderRadius: 8, overflow: 'hidden'}}><Image source={require('path/to/image')} /></View>`

![Screenshot 2020-07-02 at 13 56 18](https://user-images.githubusercontent.com/1044090/86350762-d6d49500-bc6b-11ea-9f50-3a95d036d74c.png)

## React Native version:
System:
    OS: macOS 10.15.5
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 246.72 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.18.0 - ~/.nvm/versions/node/v12.18.0/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v12.18.0/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.18.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 26, 27, 28
      Build Tools: 27.0.3, 28.0.3
      System Images: android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6308749
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.1 => 0.62.1
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by fabriziobertoglio1987** [comment]
https://github.com/facebook/react-native/pull/28881#issuecomment-656560980

**Comment by fabriziobertoglio1987** [comment]
we need more info.. 

Please post a reproducable example that I can easily set up for testing and let us now on which android api you experience this 

more info at https://github.com/facebook/react-native/pull/28881#issuecomment-656560980

I know this problem it is caused from https://developer.android.com/guide/topics/graphics/hardware-accel#unsupported

**Comment by fabriziobertoglio1987** [comment]
please provide the full test case including the image. I could not reproduce this bug, I tested in api 28, 29 and on read emulator.

**Comment by tautvilas** [comment]
I will try to create example project and will post a link to it

**Comment by tautvilas** [comment]
I have created a project with `react-native init` where the issue is visible. Here is the link:

https://github.com/tautvilas/ImagePixelationAndroid

I have noticed that adding borderRadius or borderWith to Image styles pixelates the images. Adding code and example screenshot as well.

<Image source={{uri: "https://i.imgur.com/aLVC6XS.png"}} style={{width: 300,height: 300}}/>

<Image source={{uri: "https://i.imgur.com/aLVC6XS.png"}} style={{width: 300,height: 300, borderRadius: 10, borderWidth: 1, borderColor: 'black'}}/>

<img width="311" alt="Screenshot 2020-07-13 at 12 33 17" src="https://user-images.githubusercontent.com/1044090/87289923-f9856a00-c505-11ea-8c3f-a2ba39bda5c2.png">

**Comment by fabriziobertoglio1987** [comment]
```javascript
import React from 'react';
import {
  ScrollView,
  Image,
} from 'react-native';

const App = () => {
  return (
    <ScrollView>
    <Image source={require("./image.png")} style={{ height: 900}} />
    <Image 
      source={require("./image.png")} 
      style={{ height: 900, borderRadius: 10, borderWidth: 1, borderColor: 'black'}} />
    </ScrollView>
  );
};

export default App;
```

I still can not reproduce this on Android API 28 emulator. I run it with OpelGL graphic accelleration.. 

![Screenshot_1594649505](https://user-images.githubusercontent.com/24992535/87314558-b2a66d00-c523-11ea-867e-8967a61705cb.png)


I can't fix a bug if I can not reproduce it, could depend on your local environment set up (if your emulator is using OpenGL) or depends on the device... 

![image](https://user-images.githubusercontent.com/24992535/87314619-cd78e180-c523-11ea-9190-dc977505c89d.png)

Sorry
Thanks for the help

**Comment by tautvilas** [comment]
Could you try it on a real device? I have reproduced this on Pixel 3 API 29 emulator (same OpenGL settings as you) and on real device OnePlus 6, Android 10, Oxygen OS 10.3.4

**Comment by fabriziobertoglio1987** [comment]
You could try fixing this by using prop rendertohardwaretextureandroid with value of `true`

 https://reactnative.dev/docs/view#rendertohardwaretextureandroid
 https://github.com/facebook/react-native/pull/28881#issuecomment-892404892

**Comment by xiangaoole** [comment]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/32730253/167602244-3ff6f5ce-f0b8-4c5a-bfb6-02714c6858ae.png">

reproduced on my pixel 4a real device.

**Comment by xiangaoole** [comment]
> You could try fixing this by using prop rendertohardwaretextureandroid with value of `true`
> 
> https://reactnative.dev/docs/view#rendertohardwaretextureandroid [#28881 (comment)](https://github.com/facebook/react-native/pull/28881#issuecomment-892404892)

Not working for this
