### ISSUE TITLE
Vendored frameworks iOS not getting linked automatically with >=0.61.5

### ISSUE THREAD

**Issue by mnive93** [facebook/react-native#29261]
## Description
Trying to install a standalone vendored framework in iOS using cocoapod. The POD is not included in the NPM registry. 
The react native project in XCode is unable to find the headers. 

## React Native version:
System:
    OS: macOS 10.15.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 81.66 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.17.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 26, 27, 28, 29
      Build Tools: 27.0.3, 28.0.3, 29.0.2, 29.0.3
      System Images: android-24 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.4 AI-183.5429.30.34.5452501
    Xcode: 11.3.1/11C505 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_252 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Created a new project in terminal with latest version 0.62.2.  
2.Added the pod to the podfile and did bundle exec pod install in terminal.
3. Pod is getting installed and added in PODS folder. Unable to reference anything in that pod in my .m files.

## Expected Results
Should be able to reference the headers in my react native project.

## Snack, code example, screenshot, or link to a repository:
<img width="702" alt="Screenshot 2020-07-01 at 4 05 00 PM" src="https://user-images.githubusercontent.com/1643482/86234497-a251d200-bbb4-11ea-86e2-108872db3173.png">

**Comment by chrisbobbe** [comment]
It looks like you might be missing some imports?

One thing I've found with ["autolinking"](https://github.com/react-native-community/cli/blob/master/docs/autolinking.md) is that it's easy to assume it'll take care of *everything* for you—but if there are additional steps beyond what was previously covered by `react-native link`, you still have to do those.
