### ISSUE TITLE
If the Class prefix is'RK', it will be is not undefined object an ('RKXXX.func' evaluating)

### ISSUE THREAD

**Issue by zimo888** [facebook/react-native#2927]
The class name is not correct? 'RK' prefix.

**Comment by hahaGitHub** [comment]
hi,i have the same question.Can you tell why?

**Comment by zimo888** [comment]
RK is short for "React Kit". [the same question link](https://github.com/facebook/react-native/issues/119)

**Comment by zimo888** [comment]
@hahaGitHub  RK is short for "React Kit". [the same question link](https://github.com/facebook/react-native/issues/119)

**Comment by hahaGitHub** [comment]
Thank you very much!!  i use the RCT and React, so i meet the question.

**Comment by hahaGitHub** [comment]
hi,i have another question.
pod react in my own project.i use the RCTRootView.by the url ,I can get the view.but i meet a problem.
it is a warning. could you tell me why? thank you very much.
[warn][tid:com.facebook.React.JavaScript] 'devtools socket errored', { [Error: The operation couldn’t be completed. Connection refused]
  line: 14510,
  column: 39,
  sourceURL: 'http://localhost/index.ios.bundle' }
