### ISSUE TITLE
Execution failed for task ':app:transformClassesWithMultidexlistForRelease'. 

### ISSUE THREAD

**Issue by AhamedEstiak** [facebook/react-native#29277]
## React Native version:
System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz
    Memory: 301.04 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.12.0 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.12.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 19, 23, 25, 26, 27, 28
      Build Tools: 23.0.1, 25.0.1, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.2, 28.0.3
      System Images: android-19 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.1 AI-173.4907809
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.1 => 0.61.1 
  npmGlobalPackages:
    react-native-cli: 2.0.1

## Steps To Reproduce

1. When building a release apk it apears

**Comment by AhamedEstiak** [comment]
I use latest version rn 0.61.1. Actually this issue solve after build
several times. I'm not sure why it appears and why it disappeared.

**Comment by leotm** [comment]
Getting similar on 61.5, but hangs forever instead, outputting a big `java_pidX.hprof`.
