### ISSUE TITLE
Unable to require(gif) on iOS

### ISSUE THREAD

**Issue by finom** [facebook/react-native#29283]
##  Description
The bundler is unable to resolve gifs. 

![image](https://user-images.githubusercontent.com/1082083/86597325-3ac8c780-bfa4-11ea-9369-82dc1ffd35ce.png)

## React Native version:
```
System:
    OS: macOS 10.15.5
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Memory: 452.52 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.10.1 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.7 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.4/11E146 - /usr/bin/xcodebuild
  npmPackages:
    react: ~16.13.1 => 16.13.1 
    react-native: ~0.61 => 0.61.5 
  npmGlobalPackages:
    react-native: 0.62.2
```

## Steps To Reproduce

1. `require('./some.png')` and it's going to work if the file exists.
2. `require('./some.gif')` I get the error even if the file exists.

Also tried with `import x from './some.gif'` and got same result. The file 100% exists, I've triple checked.

## Expected Results
The file should be imported as a module.

## Snack, code example, screenshot, or link to a repository:
I was unable to reproduce the issue on Snack, see https://snack.expo.io/@finom/upbeat-chocolates 
But I hope you can give an idea how can I solve that locally.

**Comment by finom** [comment]
Update: installed RN 0.62.2 but got the same problem. Please provide at least minimal information of how to debug that. The error blocks all my work.

**Comment by chrisglein** [comment]
Looking at the snack it doesn't produce an error on Web but also doesn't show the GIF (of the cat eating popcorn). On Android it does show, and eats popcorn. Worked in iOS too.

It's interesting because the docs say GIFs are not supported on Android:
https://reactnative.dev/docs/image.html#gif-and-webp-support-on-android

> You will need to add some optional modules in android/app/build.gradle, depending on the needs of your app.

Did you follow those steps? It's possible Snack is doing that for you.

**Comment by finom** [comment]
@chrisglein yes, I've followed these steps. After I've renamed the file to .png, everything started to work as expected. The problem isn't about gif support on given operating systems, the problem is that RN is unable to import .gif file as a module. That's RN side issue only which isn't about Android or iOS at all.

**Comment by panda0603** [comment]
i'm pretty sure .gif works because I am using it that way, for both iOS and android. There should be some steps that you should be missing

**Comment by chrisglein** [comment]
I looks like there might have been more stuff Expo had done to make this work: https://forums.expo.io/t/display-animated-gif/4940

> we add it so gifs just work out of the box, go ahead and use one!

Comment in the RN docs is ~3 years old. Possible things have shifted here.
