### ISSUE TITLE
TextInput with secureTextEntry and maxLength TalkBack error

### ISSUE THREAD

**Issue by enieber** [facebook/react-native#29284]
##  Description

I make some tests with TalkBack to read input, and text to make my app more accessible when I find this possible bug accessibility of TextInput. 

When I use the component `TextInput` with props `securreTextEntry` and `maxLength` defined the read screen TalkBack, read "max length input" when the maxLength is not hit.

## React Native version:

<details>
  <summary>react-native info </summary>

  ```sh
   System:
    OS: Linux 5.6 Manjaro Linux
    CPU: (4) x64 Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
    Memory: 192.16 MB / 11.59 GB
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 12.18.0 - /tmp/yarn--1594153519243-0.7951287599499737/node
    Yarn: 1.22.4 - /tmp/yarn--1594153519243-0.7951287599499737/yarn
    npm: 6.14.4 - /tmp/fnm-shell-6583485/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 1.8.0_252 - /usr/bin/javac
    Python: 3.8.3 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found
Done in 1.04s.
```
</details>

expo sdk: 38
react-native: 0.62

## Steps To Reproduce

1. To reproduce this possible bug is necessary run in android device with TalkBack active
2. Run the project with expo
3. Edit in TextInput

## Expected Results

The TalkBack only talks "max length input" when the max length of TextInput is hit.

## Snack, code example, screenshot, or link to a repository:

I am using expo and create an example of how to run this error:

https://snack.expo.io/@enieber/textinput

**Comment by amarlette** [comment]
@blavalla has not been able to reproduce this issue on the current RN version. Was this issue resolved by updates since the issue was created?

**Comment by blavalla** [comment]
Just as a note, if you can reproduce this still, could you let me know the version of Android, and the version of Talkback you are using? Thanks!
