### ISSUE TITLE
React native picker items doesn't align to right on RTL layout. (eg. Arabic layout)

### ISSUE THREAD

**Issue by vyshakh** [facebook/react-native#29281]
## Description
Picker items are not aligning to right on RTL layout

## React Native version:
    OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 28.14 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.14.1 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-28 | Google Play Intel x86 Atom, android-29 | Intel x86 Atom_64
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native: 0.61.5

## Steps To Reproduce

1. Add this code
```
<View style={{ width: 250 }}>
    <Picker mode="dropdown">
        <Picker.Item label="الإمارات العربية المتحدة" value="الإمارات العربية المتحدة" />
        <Picker.Item label="الإمارات العربية المتحدة" value="الإمارات العربية المتحدة" />
    </Picker>
</View>
```
2. Current result
## Current result
<img width="222" alt="actual" src="https://user-images.githubusercontent.com/2608067/86574095-59b86100-bf86-11ea-93b8-aa5a38ad76fc.png">

## Expected Results
<img width="216" alt="expected" src="https://user-images.githubusercontent.com/2608067/86574109-5e7d1500-bf86-11ea-9cc3-9dc6f4a2bc6e.png">

## Workaround I used
In res/values/styles.xml file, add
```
<!-- Base application theme. -->
<style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
		<!-- 
		... existing styles
		--->
        <item name="android:spinnerItemStyle">@style/SpinnerItem</item>
        <item name="android:spinnerDropDownItemStyle">@style/SpinnerDropDownItem</item>
 </style>
 ```
 Then define your styles below
 ```
 <style name="SpinnerItem" parent="Theme.AppCompat.Light.NoActionBar">
    <item name="android:textAlignment">gravity</item>
    <item name="android:gravity">start</item>
</style>
<style name="SpinnerDropDownItem" parent="Theme.AppCompat.Light.NoActionBar">
    <item name="android:textAlignment">gravity</item>
    <item name="android:gravity">start</item>
    <item name="android:padding">10dp</item>
</style> 
```

**Comment by chrisglein** [comment]
Picker has moved out of core and is now a community module: Note the deprecation on the main docs: https://reactnative.dev/docs/picker
I don't know if the issue repros there but you will want to try the community module and potentially make this report on that repo.
