### ISSUE TITLE
Text input dynamic change the text color 

### ISSUE THREAD

**Issue by haThaiHoang** [facebook/react-native#29286]
TextInput in React Native 0.62 still cannot dynamic change the text color when value have emoji and multiline.
This is issue just happen on ios, android works fine
Here is my example: [https://snack.expo.io/@jonlefcun/rn20131---textinput-dynamic-color](https://snack.expo.io/@jonlefcun/rn20131---textinput-dynamic-color)
Please help me with this. Thank you

**Comment by RichardFevrier** [comment]
Same behavior encountered 😌

**Comment by RichardFevrier** [comment]
\* react-native: 0.63.2

**Comment by marlti7** [comment]
Same behavior encountered

**Comment by Tymofiev** [comment]
+1

**Comment by yczeng** [comment]
I have the same problem.

**Comment by MykolaSauliak** [comment]
@haThaiHoang Have you tried using key prop somehow ?

**Comment by MykolaSauliak** [comment]
@haThaiHoang 
try changing text with setNativeProps, it works for me
preudo-code:
        if(platformSpecificTextColor && props.inputRef){
            // not to trigger render, need only for dynamic color changing
            props.inputRef?.current?.setNativeProps?.({'text': ''})
            setTimeout(() => {
                props.inputRef?.current?.setNativeProps?.({'text': props.text})
            })
        }
