### ISSUE TITLE
Text's numberOfLines doesn't work in iphone8P

### ISSUE THREAD

**Issue by spokeen** [facebook/react-native#29298]
Envirment:  Iphone8 plus

code
`
<Text numberOfLines={2} >
 2019年4月24日星期四 调整在途，少接飞刀 盘面观察周二A股延续弱势持续调整。从盘面看，两市股指低开后短暂上攻，但由于金融股和周期股表现不佳，大盘索性下台阶跌破3500点关口；午后市场有所回暖，
                </Text>
`

but it just shows one line. 
<img width="328" alt="765D0D28-D833-44AE-A780-570ACC1768F8" src="https://user-images.githubusercontent.com/16604744/86891480-7e9d0780-c131-11ea-9072-035338718490.png">

How can it show tow lines.

**Comment by hannojg** [comment]
`numberOfLines` is currently an android only prop!

**Comment by fabriziobertoglio1987** [comment]
I wanted to ask if you still experience this issue. 
I'm planning to do 1-2 months of opensource and I'm preparing a list of tasks.

I have been contributing to facebook/react-native for 4 years and I specialize on the Text/TextInput components.

Thanks a lot
