### ISSUE TITLE
Hermes engine does not support RegEx names capture groups

### ISSUE THREAD

**Issue by callaars** [facebook/react-native#29293]
## Description

When using a RegEx capture group like the following `/\b(?<testing>testing)\b/i` the Hermes engine throws an error: `error: Invalid regular expression: Quantifier has nothing to repeat` on the `:app:bundleReleaseJsAndAssets` task when building.

If you turn Hermes off, clean and recompile, it works perfectly.

## React Native version:
```
❯ react-native info
info Fetching system and libraries information...
System:
    OS: macOS 10.15.5
    CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
    Memory: 162.63 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.14.0 - ~/.nvm/versions/node/v12.14.0/bin/node
    Yarn: 1.22.0 - ~/.yarn/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.14.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /Users/joseph/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 27, 28, 29
      Build Tools: 23.0.1, 27.0.3, 28.0.2, 28.0.3, 29.0.0, 29.0.2, 30.0.0
      System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_201 - /Library/Java/JavaVirtualMachines/jdk1.8.0_201.jdk/Contents/Home/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Add the RegEx anywhere in the code where it is used, and it will fail.

## Expected Results
I expect capture groups to be supported, like without Hermes.

## Snack, code example, screenshot, or link to a repository:
I'll update the issue with an example.

**Comment by chrisglein** [comment]
For issues with the Hermes engine itself you'll want to file those against the Hermes repo:
https://github.com/facebook/hermes

This repo tracks issues with React Native and issues with how it integrates Hermes, but it seems here like you've found an issue with the engine itself. Please migrate your issue there.

**Comment by callaars** [comment]
Oh sorry, I will, thanks @chrisglein !

**Comment by samermurad** [comment]
@callaars did you create an issue by any chance? if so, would you please link it here?:D

**Comment by callaars** [comment]
I didn't create an issue as this is well documented on the Hermes branch, thanks!
