### ISSUE TITLE
Prevent packager from trying to resolve certain modules

### ISSUE THREAD

**Issue by Thegaram** [facebook/react-native#2929]
I'm trying to use Browserify for my React Native project. The idea is that I first bundle my sources together with Browserify, marking react-native as external and then use the React Native packager to bundle my bundle with React Native and serve it. It works, but the packager keeps printing errors for my modules:

```
'Unable to resolve module ../../myModule from index.ios.js'
```

Is there a way to tell the packager to ignore these modules?

**Comment by brentvatne** [comment]
Hi there,

This kind of question is best suited for StackOverflow -- we are here to help with bugs and feature requests :) Good luck!
