### ISSUE TITLE
Remove Ruby Dependency

### ISSUE THREAD

**Issue by UberMouse** [facebook/react-native#293]
I had issues generating a project because the init.sh script fails to run with the message 
```rbenv: no such command `exec'```
I had to rename the init.sh script under node_modules/react-native to init.rb and run it directly through rbenv (```rbenv exec node_modules/react-native/init.rb ProjectName```) to get it to work. 

I'm not sure if this is an rbenv issue or an issue with my configuration, has anyone else had issues running ```react-native init``` with rbenv installed?

**Comment by UberMouse** [comment]
A thought occurred to me that it might the rbenv bundler plugin. I ran ```rbenv bundler off``` to disable it and I was able to execute the init.sh script directly. Turning it back on with ```rbenv bundler on``` didn't cause the issue to come back so it might have just been rbenv in a bad state.

**Comment by amasad** [comment]
Reopening so we can get rid of ruby crap

**Comment by JoeStanton** [comment]
Closed by #440?

**Comment by amasad** [comment]
Yes, I think so.
