### ISSUE TITLE
Go to definition Component from Caches files not from node_modules project - 0.63?

### ISSUE THREAD

**Issue by anastely** [facebook/react-native#29316]
## Description
I upgrade project from 0.62.2 to 0.63 last version,
But I have a strange thing when I want to go through Definition for any comment like <Text> the normal it open the file inside node_modules in the project! right?
But in this version "0.63", It's going through Caches File in my files "system files"
Check this **[GIF](https://i.imgur.com/WSINWgY.mp4)** to understand what I mean.

And that's too happened to any new project I init new one and the same issue I got.

## React Native version:
```
System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i3-3110M CPU @ 2.40GHz
    Memory: 40.58 MB / 8.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 16, 23, 27, 28, 29
      Build Tools: 27.0.3, 28.0.3, 29.0.2
      System Images: android-16 | Intel x86 Atom, android-23 | Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.3.1/11C505 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_222 - /usr/bin/javac
    Python: 2.7.10 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.0 => 0.63.0 
  npmGlobalPackages:
    *react-native*: Not Found

```
### [GIF](https://i.imgur.com/WSINWgY.mp4)

**Comment by anastely** [comment]
Ok, I just delete Caches folder, But the new component `Pressable` it's faced the same issue as in GIF

**Comment by dburdan** [comment]
@anastely Types for 0.63.x aren't merged into the DefinitelyTyped repo yet so `Pressable` doesn't exist. See [here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/45963).
