### ISSUE TITLE
[Improvement] Show warning in case you overwrite Platform.OS by mistake.

### ISSUE THREAD

**Issue by cepem** [facebook/react-native#29318]
I believe it would be a good idea to let the user know if he accidentally overwrites Platform.OS.

We had a case where instead of doing `Platform.OS == 'ios' ?`  we did `Platform.OS = 'ios' ? ` by accident and it took us around 1.5 months to figure out why almost every library in the app was behaving in a weird way.

This bug was so hard to catch that we almost gave up on React Native. I believe there should be a warning in order to help users avoid accidents like this down the road.

**Comment by chrisbobbe** [comment]
I think a using a linter, like ESLint, would catch this nasty bug pretty quickly; maybe [this ESLint rule](https://eslint.org/docs/rules/no-multi-assign) in particular?

**Comment by cepem** [comment]
@chrisbobbe Unfortunately ESLint didn't catch this bug. That rule only seems to be applied to multiple variable assigns on one line, which doesn't apply here, since we were passing that value to an object property.
