### ISSUE TITLE
Single Frame GIF disappears (no rerender triggered) when modals and alerts are opened

### ISSUE THREAD

**Issue by kurnal** [facebook/react-native#29311]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description

I display various GIFs on my application of many different frame lengths; however, the single frame ones seem to be causing a huge problem for React Native. Whenever I enter this base64 string into the URI for the Image Component it shows up initially then disappears without triggering a re-render when an alert or modal is opened. An example is shown in the Snack below.

## React Native version:
version: 0.61.5

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. write a single frame base64 GIF and a multi-frame base64 GIF into two image components
2. put a button that opens an Alert and click it. the single frame GIF will disappear

## Expected Results
opening an alert makes a single frame GIF disappear

## Snack, code example, screenshot, or link to a repository:
https://snack.expo.io/@kurnal/disappearing-gif

**Comment by ikimiler** [comment]
same problem,please me

**Comment by domasn** [comment]
There is a way to fix this using idea suggested here https://github.com/facebook/react-native/issues/27032#issuecomment-667073239
> Also specify the "defaultSource" property in addition to the regular source property (works on ios only, but the bug is ios only anyway, so...). No flicker, image always showing and up-to-date! :)
