### ISSUE TITLE
Need Help: How to Integrate react-native to iOS with separate folders. (Not inside react root directory).

### ISSUE THREAD

**Issue by prakashRavi1990** [facebook/react-native#29322]
Hi,

I already have a project on iOS and Android. I would like to implement some new features in react-native. I have done integration in sample apps as well and its working like a charm. 

But my doubt is, this is working when I have iOS and Android code in react root directory. when I move the iOS and Android in a separate folder unable to install pod in ios. Getting error in "use_native_modules".

Working Folder Structure

Root
--iOS
-----xcworkspace
-----Podfile
-----Pods
--node_modules
--index.js
--App.js
etc.

But I need

iOS
--xcworkspace
--Podfile
--Pods
React
--node_modules
--index.js
--App.js
etc.

I have changed the path in Podfile pointing to the react directory. When I use 

require_relative '../ReactNative/node_modules/@react-native-community/cli-platform-ios/native_modules
use_native_modules!

I am unable to install the pods. getting 

[!] Invalid `Podfile` file: [!] /usr/local/bin/node -e try {console.log(require('@react-native-community/cli').bin);} catch (e) {console.log(require('react-native/cli').bin);}

internal/modules/cjs/loader.js:1032
  throw err;
  ^

Error: Cannot find module 'react-native/cli'
Require stack:
- /Users/user/Documents/Sample ReactNative Projects/SeperateFolders/iOS/[eval]
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at [eval]:1:87
    at Script.runInThisContext (vm.js:131:18)
    at Object.runInThisContext (vm.js:295:38)
    at Object.<anonymous> ([eval]-wrapper:10:26)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at evalScript (internal/process/execution.js:98:25) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/user/Documents/Sample ReactNative Projects/SeperateFolders/iOS/[eval]'
  ]
}
.

 #  from /Users/user/Documents/Sample ReactNative Projects/SeperateFolders/iOS/Podfile:48
 #  -------------------------------------------
 #    
 >    use_native_modules!
 #    
 #  -------------------------------------------

Also when I comment those 2 lines in pod file auto-linked pods are not getting installed. 
Is there any way to achieve this? 
or Is this the structure we need to follow?

Kindly help. 

Thanks in advance.

![CurentStructure](https://user-images.githubusercontent.com/24309606/87053723-f0ec1580-c21f-11ea-9bda-f9e97f1d6ff3.jpg)
![ExpectingStructure](https://user-images.githubusercontent.com/24309606/87053744-f6496000-c21f-11ea-9aed-0ac0cca26cb9.jpg)

**Comment by ed1son67** [comment]
I have the same puzzled too, at the very beginning, i think it may be a bug and takes me a lot of time to find a solution..

**Comment by baxsad** [comment]
> I have the same puzzled too, at the very beginning, i think it may be a bug and takes me a lot of time to find a solution..

How to solve it？

**Comment by michal-th** [comment]
did you find a working solution?
