### ISSUE TITLE
There is no  0.63 @types/react-native 

### ISSUE THREAD

**Issue by mym0404** [facebook/react-native#29328]
Is there any plan to support 0.63 Typescript? The latest version of `@types/react-native` is 0.62.17.
I think the `Pressable` or any other features in `0.63` is not inferred in Typescript.

`TS2305: Module '"react-native"' has no exported member 'Pressable'.`

**Comment by dburdan** [comment]
@mym0404 A PR for 0.63 is in progress on the DefinitelyTyped repo here https://github.com/DefinitelyTyped/DefinitelyTyped/pull/45963.

**Comment by mym0404** [comment]
Thank you for reply :)

**Comment by mym0404** [comment]
#1
