### ISSUE TITLE
const keyword not working on android

### ISSUE THREAD

**Issue by marek-** [facebook/react-native#2932]
Hi 

I am developing on linux and running app on android simulator.
when I use 'const' keyword in code the simulator goes blank, with var everything works.
when I try to debug I can see the ui displayed properly and app works normally.

**Comment by mkonicek** [comment]
I've seen this reported before. I use `var`. @ide Do you know if we support `const`? What determines if we do? Is it the version of Node or Babel we're using? I think Babel supports `const`?

**Comment by ide** [comment]
@marek- Try adding `{"whitelist": ["es6.constants"]}` to .babelrc in your project root.

@mkonicek This might have quietly worked on newer iOS versions that support `const` but the keyword was not transformed by Babel.

**Comment by mkonicek** [comment]
:+1: Thanks for the explanation @ide!
Would it make sense to create a default .babelrc file for all new projects?

**Comment by ide** [comment]
The packager should ship with good defaults. We could create an empty babelrc so people would know where to make changes, though.
