### ISSUE TITLE
We encountered an ANR when doLoadLibraryBySoName()

### ISSUE THREAD

**Issue by Zhijiang-Li** [facebook/react-native#29330]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
That is reported by user, we can't repro it.

## React Native version:
react-native version:0.61.5
soloader:0.6.0

## Steps To Reproduce
When running com.facebook.react.ReactInstanceManagerBuilder#getDefaultJSExecutorFactory, the users encounter ANR.

Here is the stack info.
"main" prio=5 tid=1 Waiting
  | group="main" sCount=1 dsCount=0 flags=1 obj=0x7247aa20 self=0xb255a000
  | sysTid=2838 nice=-10 cgrp=default sched=0/0 handle=0xb5ff54a4
  | state=S schedstat=( 8541554268 769683514 7014 ) utm=757 stm=97 core=4 HZ=100
  | stack=0xbe30d000-0xbe30f000 stackSize=8MB
  | held mutexes=
  at java.lang.Object.wait(Native method)
  - waiting on <0x08411f21> (a java.lang.Object)
  at java.lang.Thread.parkFor$(Thread.java:2137)
  - locked <0x08411f21> (a java.lang.Object)
  at sun.misc.Unsafe.park(Unsafe.java:358)
  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:868)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:900)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1223)
  at java.util.concurrent.locks.ReentrantReadWriteLock$WriteLock.lock(ReentrantReadWriteLock.java:950)
  at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:702)
  at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:591)
  - locked <0x0fbc7f46> (a java.lang.Object)
  at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:539)
  at com.facebook.soloader.DirectorySoSource.loadDependencies(DirectorySoSource.java:103)
  at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:73)
  at com.facebook.soloader.UnpackingSoSource.loadLibrary(UnpackingSoSource.java:465)
  - locked <0x082db507> (a java.lang.Object)
  at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:681)
  at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:591)
  - locked <0x03086634> (a java.lang.Object)
  at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:529)
  at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:484)
  at com.facebook.react.ReactInstanceManagerBuilder.getDefaultJSExecutorFactory(ReactInstanceManagerBuilder.java:290)
  at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:265)
We called ReactInstanceManagerBuilder.build()

Here is the log:
06-29 19:56:48.301 10060  4408  4408 D SoLoader: About to load: libjscexecutor.so
06-29 19:56:48.301 10060  4408  4408 D SoLoader: libjscexecutor.so found on /data/data/com.our.app/lib-main
06-29 19:56:48.306 10060  4408  4408 D SoLoader: Loading lib dependencies: [libdl.so, libfb.so, libreactnativejni.so, libjsc.so, libjsinspector.so, libfolly_json.so, libglog.so, libc++_shared.so, liblog.so, libc.so, libm.so]
06-29 19:56:48.306 10060  4408  4408 D SoLoader: About to load: libfb.so
06-29 19:56:48.307 10060  4408  4408 D SoLoader: libfb.so found on /data/data/com.our.app/lib-main
06-29 19:56:48.309 10060  4408  4408 D SoLoader: Loading lib dependencies: [libdl.so, libc++_shared.so, liblog.so, libandroid.so, libc.so, libm.so]
06-29 19:56:48.309 10060  4408  4408 D SoLoader: About to load: libc++_shared.so
06-29 19:56:48.309 10060  4408  4408 D SoLoader: libc++_shared.so found on /data/data/com.our.app/lib-main
06-29 19:56:48.311 10060  4408  4408 D SoLoader: Loading lib dependencies: [libc.so, libdl.so]
06-29 19:56:48.319 10060  4408  4408 D SoLoader: Loaded: libc++_shared.so
06-29 19:56:48.319 10060  4408  4408 D SoLoader: About to load: libandroid.so
06-29 19:56:48.319 10060  4408  4408 D SoLoader: libandroid.so not found on /data/data/com.our.app/lib-main
06-29 19:56:48.319 10060  4408  4408 D SoLoader: libandroid.so not found on /vendor/lib
06-29 19:56:48.320 10060  4408  4408 D SoLoader: libandroid.so found on /system/lib
06-29 19:56:48.320 10060  4408  4408 D SoLoader: libandroid.so loaded implicitly
06-29 19:56:48.320 10060  4408  4408 D SoLoader: Loaded: libandroid.so
06-29 19:56:48.324 10060  4408  4408 D SoLoader: About to load: libfb.so
06-29 19:56:48.324 10060  4408  4408 D SoLoader: libfb.so found on /data/data/com.our.app/lib-main
06-29 19:56:48.326 10060  4408  4408 D SoLoader: Loading lib dependencies: [libdl.so, libc++_shared.so, liblog.so, libandroid.so, libc.so, libm.so]
06-29 19:56:48.327 10060  4408  4408 I zygote  : Thread[1,tid=4408,Native,Thread*=0xb255a000,peer=0x7247aa20,"main"] recursive attempt to load library "/data/user/0/com.our.app/lib-main/libfb.so"
06-29 19:56:48.327 10060  4408  4408 D SoLoader: Loaded: libfb.so
06-29 19:56:48.328 10060  4408  4408 D SoLoader: Loaded: libfb.so
06-29 19:56:48.328 10060  4408  4408 D SoLoader: About to load: libreactnativejni.so
06-29 19:56:48.329 10060  4408  4408 D SoLoader: libreactnativejni.so found on /data/data/com.our.app/lib-main
06-29 19:56:48.332 10060  4408  4408 D SoLoader: Loading lib dependencies: [libdl.so, libglog_init.so, libyoga.so, libfb.so, libjsinspector.so, libfolly_json.so, libglog.so, libc++_shared.so, libandroid.so, liblog.so, libc.so, libm.so]
06-29 19:56:48.332 10060  4408  4408 D SoLoader: About to load: libglog_init.so
06-29 19:56:48.332 10060  4408  4408 D SoLoader: libglog_init.so found on /data/data/com.our.app/lib-main
06-29 19:56:48.334 10060  4408  4408 D SoLoader: Loading lib dependencies: [libdl.so, libglog.so, libc++_shared.so, liblog.so, libc.so, libm.so]
06-29 19:56:48.334 10060  4408  4408 D SoLoader: About to load: libglog.so
06-29 19:56:48.335 10060  4408  4408 D SoLoader: libglog.so found on /data/data/com.our.app/lib-main
06-29 19:56:48.336 10060  4408  4408 D SoLoader: Loading lib dependencies: [libdl.so, libc++_shared.so, libc.so, libm.so]
06-29 19:56:48.343 10060  4408  4408 D SoLoader: Loaded: libglog.so
06-29 19:56:48.345 10060  4408  4408 D SoLoader: Loaded: libglog_init.so
06-29 19:56:48.345 10060  4408  4408 D SoLoader: About to load: libyoga.so
06-29 19:56:48.346 10060  4408  4408 D SoLoader: libyoga.so found on /data/data/com.our.app/lib-main
06-29 19:56:48.348 10060  4408  4408 D SoLoader: Loading lib dependencies: [libdl.so, libfb.so, libc++_shared.so, libandroid.so, liblog.so, libc.so, libm.so]
06-29 19:56:48.353 10060  4408  4408 D SoLoader: Loaded: libyoga.so
06-29 19:56:48.353 10060  4408  4408 D SoLoader: About to load: libjsinspector.so
06-29 19:56:48.353 10060  4408  4408 D SoLoader: libjsinspector.so found on /data/data/com.our.app/lib-main
06-29 19:56:48.354 10060  4408  4408 D SoLoader: Loading lib dependencies: [libdl.so, libc++_shared.so, libc.so, libm.so]
06-29 19:56:48.357 10060  4408  4408 D SoLoader: Loaded: libjsinspector.so
06-29 19:56:48.358 10060  4408  4408 D SoLoader: About to load: libfolly_json.so
06-29 19:56:48.358 10060  4408  4408 D SoLoader: libfolly_json.so found on /data/data/com.our.app/lib-main
06-29 19:56:48.359 10060  4408  4408 D SoLoader: Loading lib dependencies: [libdl.so, libglog.so, libc++_shared.so, libc.so, libm.so]
06-29 19:56:48.365 10060  4408  4408 D SoLoader: Loaded: libfolly_json.so
06-29 19:56:48.382 10060  4408  4408 D SoLoader: Loaded: libreactnativejni.so
06-29 19:56:48.382 10060  4408  4408 D SoLoader: About to load: libjsc.so
06-29 19:56:48.383 10060  4408  4408 D SoLoader: libjsc.so not found on /data/data/com.our.app/lib-main
06-29 19:56:48.383 10060  4408  4408 D SoLoader: libjsc.so not found on /vendor/lib
06-29 19:56:48.383 10060  4408  4408 D SoLoader: libjsc.so not found on /system/lib
06-29 19:56:51.043 10060  4408  4418 I zygote  : Background concurrent copying GC freed 425085(17MB) AllocSpace objects, 30(1452KB) LOS objects, 51% free, 16MB/34MB, paused 540us total 205.646ms
06-29 19:56:51.774  1000  1392  1755 E TaskPersister: File error accessing recents directory (directory doesn't exist?).
06-29 19:56:55.198 10060  4408  4449 I DeviceLockScreenManager: ProcessId: 4408, Thread: DeviceStayActiveThread, Send Broadcast Action: com.our.app.ACTION_DEVICE_STAY_ACTIVE
06-29 19:56:55.200 10060  4408  4449 I ProximitySensorService: ProcessId: 4408, Thread: DeviceStayActiveThread, PSensor: Device near by, stay active broadcast sent.
06-29 19:56:57.021  1000  1392  1722 I chatty  : uid=1000(system) WifiScanningSer expire 4 lines
06-29 19:56:57.021  1000  2787  2787 W Settings: Setting device_provisioned has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
06-29 19:56:57.023  wifi   562  1898 E WifiHAL : Received UMAC message with insufficent length: 914
06-29 19:56:57.024  wifi   562  1898 E WifiHAL : Received UMAC message with insufficent length: 48
06-29 19:56:58.190  1000  1392  1406 W ActivityManager: Launch timeout has expired, giving up wake lock!
06-29 19:57:00.003 10027  1793  1793 D KeyguardUpdateMonitor: received broadcast android.intent.action.TIME_TICK
06-29 19:57:00.004 10027  1793  1793 D KeyguardUpdateMonitor: handleTimeUpdate
06-29 19:57:01.809  wifi   562  1898 E WifiHAL : Received UMAC message with insufficent length: 48
06-29 19:57:01.810  wifi   562  1898 E WifiHAL : Received UMAC message with insufficent length: 48
06-29 19:57:01.810  wifi   562  1898 E WifiHAL : Received UMAC message with insufficent length: 914
06-29 19:57:01.813  1000  1392  2868 I chatty  : uid=1000(system) Binder:1392_D expire 12 lines
06-29 19:57:01.815   gps  1072  1900 I LOWI-8.5.0.3.c: [LOWI-Scan] lowi_close_record:Scan completed in 687683ms and Recieved 7 APs scan results
06-29 19:57:01.818  wifi  1009  1009 I wificond: Enters wifigbk_ageOutHistory
06-29 19:57:01.819  wifi  1009  1009 I wificond: Enters wifigbk_ageOutHistory
06-29 19:57:10.019  1000  1392  1406 W BroadcastQueue: Timeout of broadcast BroadcastRecord{39fdf15 u-1 android.intent.action.TIME_TICK} - receiver=android.os.BinderProxy@a9aa590, started 10000ms ago
06-29 19:57:10.020  1000  1392  1406 W BroadcastQueue: Receiver during timeout of BroadcastRecord{39fdf15 u-1 android.intent.action.TIME_TICK} : BroadcastFilter{a029e8e u0 ReceiverList{faa8e89 4408 com..our.app/10060/u0 remote:a9aa590}}

**Comment by Zhijiang-Li** [comment]
Could you help us to find the root cause? Does it because the line702 in Soloader.java required a writelock and someplace already got a readlock that block it?

**Comment by Zhijiang-Li** [comment]
Does anybody here?

**Comment by OlivierFreyssinet** [comment]
Have an issue here that is somewhat similar, I don't have logs because it happens rarely and it's very hard to reproduce but here's the stacktrace of the main thread when it happens:
```
com.bllocosn.anrDetection.BllocAnrException: ANR detected
    at java.io.FileDescriptor.sync(FileDescriptor.java)
    at com.facebook.soloader.SysUtil.fsyncRecursive(SysUtil.java:192)
    at com.facebook.soloader.SysUtil.fsyncRecursive(SysUtil.java:185)
    at com.facebook.soloader.UnpackingSoSource$1.run(UnpackingSoSource.java:362)
    at com.facebook.soloader.UnpackingSoSource.refreshLocked(UnpackingSoSource.java:377)
    at com.facebook.soloader.UnpackingSoSource.prepare(UnpackingSoSource.java:420)
    at com.facebook.soloader.SoLoader.initSoSources(SoLoader.java:304)
    at com.facebook.soloader.SoLoader.init(SoLoader.java:181)
    at com.facebook.soloader.SoLoader.init(SoLoader.java:164)
    at com.facebook.soloader.SoLoader.init(SoLoader.java:190)
    at com.bllocosn.MainApplication.onCreate(MainApplication.java:146)
    at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6712)
    at android.app.ActivityThread.access$1300(ActivityThread.java:237)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:223)
    at android.app.ActivityThread.main(ActivityThread.java:7656)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
````

It seems like this happens when the app is killed by the system and then restarted (our app is a launcher so it's possible that its lifecycle is handled a bit differently by Android)

@Zhijiang-Li did you find a solution ? Maybe by upgrading RN (and the SoLoader) ?

**Comment by Zhijiang-Li** [comment]
> Have an issue here that is somewhat similar, I don't have logs because it happens rarely and it's very hard to reproduce but here's the stacktrace of the main thread when it happens:
> 
> ```
> com.bllocosn.anrDetection.BllocAnrException: ANR detected
>     at java.io.FileDescriptor.sync(FileDescriptor.java)
>     at com.facebook.soloader.SysUtil.fsyncRecursive(SysUtil.java:192)
>     at com.facebook.soloader.SysUtil.fsyncRecursive(SysUtil.java:185)
>     at com.facebook.soloader.UnpackingSoSource$1.run(UnpackingSoSource.java:362)
>     at com.facebook.soloader.UnpackingSoSource.refreshLocked(UnpackingSoSource.java:377)
>     at com.facebook.soloader.UnpackingSoSource.prepare(UnpackingSoSource.java:420)
>     at com.facebook.soloader.SoLoader.initSoSources(SoLoader.java:304)
>     at com.facebook.soloader.SoLoader.init(SoLoader.java:181)
>     at com.facebook.soloader.SoLoader.init(SoLoader.java:164)
>     at com.facebook.soloader.SoLoader.init(SoLoader.java:190)
>     at com.bllocosn.MainApplication.onCreate(MainApplication.java:146)
>     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
>     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6712)
>     at android.app.ActivityThread.access$1300(ActivityThread.java:237)
>     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
>     at android.os.Handler.dispatchMessage(Handler.java:106)
>     at android.os.Looper.loop(Looper.java:223)
>     at android.app.ActivityThread.main(ActivityThread.java:7656)
>     at java.lang.reflect.Method.invoke(Method.java)
>     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
>     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
> ```
> 
> It seems like this happens when the app is killed by the system and then restarted (our app is a launcher so it's possible that its lifecycle is handled a bit differently by Android)
> 
> @Zhijiang-Li did you find a solution ? Maybe by upgrading RN (and the SoLoader) ?

Hi, @OlivierFreyssinet , after I updated soloader to the latest version, I never got a similar report again.

**Comment by OlivierFreyssinet** [comment]
Ok thanks for the info!
