### ISSUE TITLE
TextInput textContentType not working with multiple inputs, depending on styles

### ISSUE THREAD

**Issue by KristinaHus** [facebook/react-native#29341]
## Description
I'm having issue with TextInput textContentType

When I'm trying to setup "Password Autofill" on iOS, it auto-fills only one field, on which I have taped. It happened when my form aligned in the middle of the screen (you can see it in my snippet, I activated it by adding paddingTop 170 to the View). But, if I change the paddingTop property to 40 for example, or 470 (to make it aligned not in the middle of the screen, but on top/bottom), it works like expected and fills both fields correct during usage of "Password Autofill". I've tried many different combinations to replace paddingTop with something else (like empty images, flex styles, non-visible elements). It doesn't matter what is above the form, the problem appears always when fields are in the middle.

Also one interesting thing. I've noticed that if the screen with inputs, is the first screen in the stack, it works correctly. I'm using react-navigation v2.0.0-rc.1

## React Native version:
System:
    OS: macOS 10.15.5
    CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
    Memory: 207.17 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.9.1 - /Users/kina/.rvm/gems/ruby-2.4.6/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  Languages:
    Java: 13.0.2 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.0 => 0.63.0 
  npmGlobalPackages:
    *react-native*: Not Found

## Expected Results
I expect that both fields will be auto-filled at one time, and it should not depend on inputs position on the screen. As it works now when inputs are moved to the top.

## Snack, code example, screenshot, or link to a repository:
Here is a code snippet 
```
<View style={{marginHorizontal: 15, paddingTop: 170}}>
        <TextInput
          textContentType='username'
          placeholder='Email'
          style={{
            minWidth: '100%',
            paddingVertical: 8,
            paddingHorizontal: 8,
            borderColor: '#D9D9D9',
            borderBottomWidth: 1,
            fontSize: 20,
            color: '#ffffff',
            ...Platform.select({
              ios: {
                marginBottom: 45,
              },
              android: {
                marginBottom: 35,
              },
            }),
          }}
        />
        <TextInput
          textContentType='password'
          placeholder='Password'
          style={{
            minWidth: '100%',
            paddingVertical: 8,
            paddingHorizontal: 8,
            borderColor: '#D9D9D9',
            borderBottomWidth: 1,
            fontSize: 20,
            color: '#ffffff',
            ...Platform.select({
              ios: {
                marginBottom: 45,
              },
              android: {
                marginBottom: 35,
              },
            }),
          }}
        />
      </View>
```

How it works now:

![ezgif-2-da5e155617a3](https://user-images.githubusercontent.com/7254847/87223661-7211ec80-c387-11ea-8d9a-6babf3f6d5cb.gif)

How it works if I move inputs to the top, and this is how I expect it to work in any inputs position:

![ezgif-2-24965fd4ebbc](https://user-images.githubusercontent.com/7254847/87223660-70e0bf80-c387-11ea-9f45-21aa95147ba9.gif)

**Comment by kikill95** [comment]
Hi, any updates on this?
I have the same issue. Found few similar (but not exact) things in other issues, but nothing helps

**Comment by stazrad** [comment]
weirdly enough I can only get `textContentType` to suggest autocompletes when i pass `multiline` to `<TextInput>`??

**Comment by famu1hundred** [comment]
I have the same issue on react-native 0.63

**Comment by aaptho** [comment]
> weirdly enough I can only get `textContentType` to suggest autocompletes when i pass `multiline` to `<TextInput>`??

This fixed a similar issue for me, where after replacing one `<TextInput textContentType="givenName">` with a different `<TexInput textContentType=“familyName”>`, it still wanted to autofill my first name.

**Comment by jr00n** [comment]
Any news? I have these problems on iOS with textContentType password , then there is a suggestion of email adres in the keyboard. Only on the second (confirm) password field in the form

**Comment by annaostapenko22** [comment]
Hello! Any updates here? I am facing the similar issue on react-native 0.65

**Comment by ShadReyes** [comment]
Any updates? I am facing a very similar problem in react-native 0.69.5
