### ISSUE TITLE
CreateStackNavigator doesn't work

### ISSUE THREAD

**Issue by Anisha961** [facebook/react-native#29345]
I have followed all the steps mentioned in official docs of react navigation but my createStackNavigator doesn't work. In my iphone simulator it shows the title but I don't see any bar. Also, in android it is completely white screen.
In my Main.js file I have used the word Hello inside Text , even that also is not displayed in screen.

I am attaching you the files please see that :

App.js

      import React from 'react';
      import { View } from 'react-native';
      import Navigation from './src/Navigation/Navigation';
      export default function App() {
      return (
     <View>
      <Navigation/>
    </View>
    );
   }

Navigation.js

     import React from 'react';
     import { createAppContainer } from 'react-navigation';
     import { createStackNavigator } from 'react-navigation-stack';
     import Main from '../screen/Main';
     const AppNavigator = createStackNavigator({
    Home: {
      screen: Main,
      navigationOptions: {
        headerTitle: 'Home',
        
      }
     },
    });
  
     export default createAppContainer(AppNavigator);

Main.js

    import React from 'react';
    import {View, Text, StyleSheet} from 'react-native';

    const Main = () => {

    return(
        <View style = {styles.container}w>
            <Text>hello</Text>
        </View>
      );
    }
    const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#fff',
      alignItems: 'center',
      justifyContent: 'center',
      },
     });
    export default Main;

package.json

      "dependencies": {
      "@react-native-community/masked-view": "^0.1.10",
       "expo": "~38.0.8",
       "expo-status-bar": "^1.0.2",
       "link": "^0.1.5",
       "react": "~16.11.0",
       "react-dom": "~16.11.0",
       "react-native": "https://github.com/expo/react- 
       native/archive/sdk-38.0.2.tar.gz",
      "react-native-gesture-handler": "^1.6.1",
     "react-native-reanimated": "^1.9.0",
    "react-native-safe-area-context": "~3.0.7",
    "react-native-screens": "^2.9.0",
    "react-native-web": "~0.11.7",
    "react-navigation": "^4.4.0",
    "react-navigation-stack": "^2.8.2"
     },
     "devDependencies": {
      "@babel/core": "^7.8.6",
      "babel-preset-expo": "~8.1.0"
      },
     "private": true
    }

**Comment by Anisha961** [comment]
> ⚠️	Missing Environment Information
> ℹ️	Your issue may be missing information about your development environment. You can obtain the missing information by running `react-native info` in a console.

<img width="412" alt="Screenshot 2020-07-12 at 5 57 13 AM" src="https://user-images.githubusercontent.com/67403954/87236261-9364ee00-c404-11ea-9a31-a2deb6d2b555.png">

**Comment by BenjaminCanape** [comment]
Hello,

 I can only talk  about Android because I can't test on iOS but I would say that you should not encapsulate your Navigation tag with the View tag in the App.js. Juste do  :

 return (
  <Navigation/>
);

And on Android the white screen should go away and let place to what you wanted to do

**Comment by Anisha961** [comment]
> Hello,
> 
> I can only talk about Android because I can't test on iOS but I would say that you should not encapsulate your Navigation tag with the View tag in the App.js. Just do :
> 
> return (<Navigation / >);
> 
> And on Android the white screen should go away and let place to what you wanted to do.
> Also, you should install and configure an Android SDK, the info you've send shows that you have not any one SDK for Android

It worked sir. Thank You so much
