### ISSUE TITLE
Plans for 3d touch APIs

### ISSUE THREAD

**Issue by mattapperson** [facebook/react-native#2934]
Is the current plan to support the new 3d touch APIs on iOS in core? Or would you rather see those in a plugin/module?

**Comment by ide** [comment]
This should likely go in core because it probably best interacts with the existing gesture system (haven't looked at the APIs but that's my current thinking).

cc @vjeux - we'll want to bump the min requirement to Xcode 7 for this.

**Comment by mattapperson** [comment]
1 PR made so far to add the APIs for UITouch https://github.com/facebook/react-native/pull/3055

**Comment by mattapperson** [comment]
I more then welcome feedback, ESP as it is my first PR to the project :) 

I will look at adding the other APIs in the next few days

**Comment by ptmt** [comment]
Looks like it could be closed now since https://github.com/facebook/react-native/commit/f685878938b59f858dc65b8e5e873045a25ccf79 has landed?
