### ISSUE TITLE
React-native 0.63 autolink and react-native-paper

### ISSUE THREAD

**Issue by JulienRaynal** [facebook/react-native#29349]
## Description
When doing an npm install react-native-vector-icons it doesn't autolink like it should and needs to be linked manually with react-native link react-native-vector-icons.
If it isn't linked manually the right icons don't appear on android (couldn't test iOS)

## React Native version:
System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
    Memory: 6.09 GB / 15.92 GB
  Binaries:
    Node: 14.5.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6392135
  Languages:
    Java: 1.8.0_211 - C:\Program Files\Java\jdk1.8.0_211\bin\javac.EXE
    Python: 2.7.17 - C:\Python27\python.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.0 => 0.63.0
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
1. install react-native-paper : run npm install react-native-vector-icons
2. install react-native-vector-icons : run react-native link react-native-vector-icons
3. if you add a Searchbar the icons doesn't display correctly

## Expected Results
A search Icon should appear in the Searchbar

## Snack, code example, screenshot, or link to a repository:
```javascript
import React from 'react';
import {StyleSheet, View} from 'react-native';
import {Searchbar} from "react-native-paper";

export default class App extends React.Component {
  render() {
    return (
      <View style={styles.mainContainer}>
        <Searchbar placeholder="Search"/>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
});
```

**Comment by exneval** [comment]
@JulienRaynal [if you read the documentation of the related package, you will able to handle the issue with the newer version](https://github.com/oblador/react-native-vector-icons#option-with-gradle-recommended)
