### ISSUE TITLE
Share Module Crashed on iOS 14 with EXC_BAD_ACCESS error

### ISSUE THREAD

**Issue by lkwjohn** [facebook/react-native#29347]
## Description
Run the app on iOS 14 Open, execute the Share function that call Share.share then the app crashed

## React Native version:
RN: 0.60.4
Xcode: 11.5

## Steps To Reproduce
1. Run the app on iOS 14 Open
2. Download image and store to tmp folder using RNFetchBlob 0.12
3. Execute the Share function that call Share.share and set the url as (example: "/var/mobile/Containers/Data/Application/A56D9C0C-B407-4250-9A6F-50D4210E9EA8/Documents/temp/share/<file-name>.jpeg") which the image have been saved on the tmp folder in step 2
4. then the app crashed with EXC_BAD_ACCESS (code=2, address=0x11b920038)

## Expected Results
I have the same setup that works for iOS13 and below. 

## Snack, code example, screenshot, or link to a repository:
<img width="1153" alt="Screenshot 2020-07-12 at 11 10 00 AM" src="https://user-images.githubusercontent.com/273127/87238090-a42b5900-c430-11ea-8ea5-875a686bbd35.png">

**Comment by pway123** [comment]
Went to dig deeper, the problem lies in the fishhook code where 0.60.4 still integrate with fishhook. upgraded RN to 0.60.6 and it works fine now. Closing this issue.

**Comment by lkwjohn** [comment]
Went to dig deeper, the problem lies in the fishhook code where 0.60.4 still integrate with fishhook. upgraded RN to 0.60.6 and it works fine now. Closing this issue.
