### ISSUE TITLE
New PlatformColor issue when used with a CSS-in-JS package

### ISSUE THREAD

**Issue by tomacotuna** [facebook/react-native#29343]
## Description
After upgrading to RN 63 and trying to make use of the new PlatformColor feature within my StyledComponents I encountered the following issues when the colour was getting parsed.

## React Native version:
System:
    OS: macOS 10.15.5
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 378.68 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.9.0 - /usr/local/bin/node
    Yarn: 1.6.0 - /usr/local/bin/yarn
    npm: 6.13.7 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 10.0.1 - /usr/bin/javac
    Python: 2.7.15 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.0 => 0.63.0
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Create RN project 
2. Add styled-components
3. Try to use PlatformControl values within CSS-In-JSS 

## Expected Results
The colour value should be parsed correctly and displayed as expected.

## Actual Result
![IMG_8CC32CF2D271-1](https://user-images.githubusercontent.com/22911685/87233155-faf74b00-c3bc-11ea-8869-1b3237f3438b.jpeg)

**Comment by TheSavior** [comment]
This seems like it is specific to styled-components. I'll close this in favor of an issue on their repo. Feel free to link to this issue from there.

If this isn't specific to styled-components, feel free to comment with more information and this can be re-opened
