### ISSUE TITLE
Unable to find a specification for `React-Core (= 0.63.0)` depended upon by `React`

### ISSUE THREAD

**Issue by waheedakhtar694** [facebook/react-native#29344]
I have upgraded my react-native version from `0.62.2` to `0.63.0` with [ upgrade helper](https://react-native-community.github.io/upgrade-helper/) but after that when I try to install pods getting this error.

```
[!] Unable to find a specification for `React-Core (= 0.63.0)` depended upon by `React`

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```
## React Native version:
System:
    OS: macOS 10.15.5
    CPU: (4) x64 Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
    Memory: 112.00 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.16.1 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 22, 23, 24, 25, 26, 27, 28, 29
      Build Tools: 23.0.1, 25.0.3, 26.0.2, 27.0.3, 28.0.3
      System Images: android-18 | Google APIs ARM EABI v7a, android-21 | Google APIs ARM EABI v7a, android-21 | Google APIs Intel x86 Atom, android-21 | Google APIs Intel x86 Atom_64, android-22 | Google APIs ARM EABI v7a, android-22 | Google APIs Intel x86 Atom, android-22 | Google APIs Intel x86 Atom_64, android-23 | Google APIs ARM EABI v7a, android-23 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-24 | Google APIs ARM EABI v7a, android-24 | Google APIs Intel x86 Atom, android-24 | Google APIs Intel x86 Atom_64, android-25 | Google APIs ARM 64 v8a, android-25 | Google APIs ARM EABI v7a, android-25 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom_64, android-25 | Google Play Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-29 | Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6308749
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_121 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: ^4.10.1 => 4.10.1 
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.0 => 0.63.0 
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Upgrade to react-native `0.63.0` and install pods

## Expected Results
The pods should install without any error.

**Comment by enaluz** [comment]
I'm getting the same issue, with a different resource.

```
[!] CocoaPods could not find compatible versions for pod "ReactCommon/callinvoker":
  In Podfile:
    ReactCommon/callinvoker (from `../node_modules/react-native/ReactCommon`)

None of your spec sources contain a spec satisfying the dependency: `ReactCommon/callinvoker (from `../node_modules/react-native/ReactCommon`)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```

**Comment by appify-waheed** [comment]
@enaluz I manage to fix this issue, Actually it was my bad, I missed to add `use_react_native!(:path => config["reactNativePath"])` in pod file.

**Comment by waheedakhtar694** [comment]
@enaluz If it is fix for you, can I close it?

**Comment by levantAJ** [comment]
I'm getting the same issue while integrating React Native to Swift project

```
[!] Unable to find a specification for `React-Core (= 0.63.2)` depended upon by `React`

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```

**Comment by PaulGoodDay** [comment]
> I'm getting the same issue while integrating React Native to Swift project
> 
> ```
> [!] Unable to find a specification for `React-Core (= 0.63.2)` depended upon by `React`
> 
> You have either:
>  * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
>  * mistyped the name or version.
>  * not added the source repo that hosts the Podspec to your Podfile.
> ```

Where you able to resolve this? I am getting the same error

**Comment by PaulGoodDay** [comment]
> use_react_native

Where does this go in the Podfile?

**Comment by SNikon** [comment]
@PaulGoodDay 
```
target 'YourProject do
   use_react_native!
   (...other stuff may be here)
end
```

**Comment by maiki11** [comment]
I have the same issue and add use_react_native! it doesnt work
Invalid `Podfile` file: undefined method `use_react_native!' for #<Pod::Podfile:0x00007fd8db4b9090>.

**Comment by khuongphp** [comment]
> @enaluz I manage to fix this issue, Actually it was my bad, I missed to add
> `use_react_native!(:path => config["reactNativePath"])` in pod file.

That should be right answer.
Thank you so much.

**Comment by prvaghela** [comment]
> @enaluz I manage to fix this issue, Actually it was my bad, I missed to add
> `use_react_native!(:path => config["reactNativePath"])` in pod file.

Where to add this line in podfile ?

**Comment by fairysspring** [comment]
it works
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'NumberTileGame' do
  config = use_native_modules!
....
