### ISSUE TITLE
TextInput Children on Androrid

### ISSUE THREAD

**Issue by mqtik** [facebook/react-native#29346]
We are building a WYSIWYG editor (ish) using **TextInput as the core** (_we didn't want to use WebView for this matter_).

The `value` property it's no use for this case, since **we need** to use **components as childrens**, like so:

```
<TextInput>
 <Text>...</Text>
</TextInput>
```

—to render bolds, italics, ...—
Turns out, **this works great on iOS**, but on Android _we're stuck_ in a bug.
![image](https://user-images.githubusercontent.com/42002579/87237124-ae197180-c3c8-11ea-9ca7-a70d37517a42.png)

We were wondering if this can be fixable, and if there's something we can do to help, to be able to render children in TextInputs using Android.

We also are getting this error (**this is a separate problem**):
![image](https://user-images.githubusercontent.com/42002579/87237137-ddc87980-c3c8-11ea-949b-b660668d1902.png)
But it's a separate problem. We've had cleaned the cache, gradle cache, reinstall modules, etc.
And it's still happening.
Seems to be random.

**Comment by fabriziobertoglio1987** [comment]
I suggest you to write your own module or use a library

**Comment by mqtik** [comment]
I believe this should be supported natively; it is supported on iOS; so it leads to inconsistency between platforms

**Comment by fabriziobertoglio1987** [comment]
I wanted to ask if you still experience this issue. 
I'm planning to do 1-2 months of opensource and I'm preparing a list of tasks.

I have been contributing to facebook/react-native for 4 years and I specialize on the Text/TextInput components.

Thanks a lot

**Comment by mqtik** [comment]
Well, Fabrizio, I ended up following your advice and build my own native library, TextInputs weren't cutting it so I had to resort to a native library and linking it, so now I have native WYSIWYG support. I have considered open sourcing it, but don't really have the time right now to maintain a library, if someone wants to co-maintain the boilerplate, I'm open to uploading it.
