### ISSUE TITLE
XCode archive failed with version 11.5

### ISSUE THREAD

**Issue by AlessioCamm** [facebook/react-native#29354]
Two days ago, I update XCode to 11.5, and now it gives error after try to Archive via XCode like below but it is working on simulator or my device.

```
Undefined symbols for architecture arm64:
"_RCTSharedApplication", referenced from:
-[FitnessHocamTests testRendersWelcomeScreen] in FitnessHocamTests.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

## React Native version:
OS: macOS 10.15.5
Platforms: iOS 13.5
API Levels: 28, 29
Build Tools: 28.0.3, 29.0.2
Android Studio: 3.5 AI-191.8026.42.35.6010548
Xcode: 11.5
react-native: 0.60.6

**Comment by umang-simform** [comment]
@AlessioCamm  I tried newer flipper 0.49 and got past this issue but then I was stuck with this open issue:https://github.com/react-native-community/upgrade-support/issues/87

**Comment by AlessioCamm** [comment]
> @AlessioCamm I tried newer flipper 0.49 and got past this issue but then I was stuck with this open issue:[react-native-community/upgrade-support#87](https://github.com/react-native-community/upgrade-support/issues/87)

@umang-simform Thanks but that not help me. I need to have react-native 0.60.6, I don't want' to downgrade my version or anything else. Before I upgrade XCode, everything work perfectly, but not now...

**Comment by oleksandr-dziuban** [comment]
I have same issue... And we already have raised same issue, but there is not response there yet...

**Comment by AlessioCamm** [comment]
@oleksandr-dziuban If you find a solution, can you forward me ? I'll do the same, obviously ;)

**Comment by oleksandr-dziuban** [comment]
@AlessioCamm Yes, workaround is here https://github.com/facebook/react-native/issues/29336

**Comment by AlessioCamm** [comment]
> @AlessioCamm Yes, workaround is here #29336

@oleksandr-dziuban this work for you ?

**Comment by AlessioCamm** [comment]
> @AlessioCamm Yes, workaround is here #29336

@oleksandr-dziuban I don't have this code :
`InitializeFlipper(application);`
I use react-native 0.60.6, not the 0.63 version

**Comment by oleksandr-dziuban** [comment]
@AlessioCamm Ah, OK, you have different issue then...

**Comment by AlessioCamm** [comment]
> @AlessioCamm Ah, OK, you have different issue then...

@oleksandr-dziuban what did you mean ? Did you have a solution for the problem ?

**Comment by AlessioCamm** [comment]
@oleksandr-dziuban I test your solution by update react-native to **0.63**, but this didn't work anymore
