### ISSUE TITLE
Styling `TextInput` toggles between default and applied font styling for CJK characters on iOS in RN 0.63

### ISSUE THREAD

**Issue by sebasthuis** [facebook/react-native#29363]
## Description

The `TextInput` text styling seems to be broken when it is used in conjunction with CJK (Japanese) characters on iOS. The text/font styling toggles on and off after every change in the `TextInput` field. Toggling between what seems to be the default styling of the native component and the applied styling specified via the `style` prop. I am sure that it affects both the `fontSize` and `fontWeight` property and only affects the CJK characters. If both latin characters and CJK characters are used in the same text input field, the styling only toggles for the CJK characters. The `fontStyle` and `color` are applied correctly. 

This issue does not occur on Android and React Native versions `0.62.2` (rough estimate) and lower. It is broken in `0.62.2` and `0.63.0`. Could not reproduce it in an Expo snack, possibly because the latest version of the Expo snack uses a RN version lower than `0.62.2`.

## React Native version:
```
System:
    OS: macOS 10.15.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 665.96 MB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.12.0 - ~/.nvm/versions/node/v13.12.0/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v13.12.0/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v13.12.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.3
      System Images: android-R | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_252 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.0 => 0.63.0 
  npmGlobalPackages:
    *react-native*: Not Found
```

### With repo
See [README](https://github.com/sebasthuis/react-native-textinput-cjk-bug) in repository.

### New Project

1. Create a new react-native project (`npx react-native init ExampleProject`).
2. Use the `TextInput` component in the `App.js`.
3. Apply `fontSize` and `fontWeight` styling on the `TextInput` component via the `style` prop.
4. Start the iOS simulator by running `npm run ios`.
5. Type or copy/paste Japanese characters (probably the same for Chinese).
6. Either through removing or adding characters (both Latin & CJK) the styling toggles between the default(?) and the specified styles applied before.

## Expected Results

I would expect that styling to be applied consistently and not toggled after every change in the text input field on iOS.

## Screenshots

When deleting characters:
![Deletion TextInput](https://user-images.githubusercontent.com/20427211/87406220-b6d49800-c5c0-11ea-899a-495989a0ab90.gif)

When adding characters:
![Kapture 2020-07-13 at 17 03 48](https://user-images.githubusercontent.com/20427211/87406334-dc61a180-c5c0-11ea-8109-c6ae1c1cef29.gif)

When combining Latin & CJK characters:
![Kapture 2020-07-13 at 17 05 04](https://user-images.githubusercontent.com/20427211/87406380-eaafbd80-c5c0-11ea-9e8d-360e62612d00.gif)

## Repo

https://github.com/sebasthuis/react-native-textinput-cjk-bug

**Comment by musicode** [comment]
@sebasbad 0.63.1 fixes it.

**Comment by marlti7** [comment]
> @sebasbad 0.63.1 fixes it.

i test it. not work just for ios.(chinese and japanese)

**Comment by fabriziobertoglio1987** [comment]
I wanted to ask if you still experience this issue. 
I'm planning to do 1-2 months of opensource and I'm preparing a list of tasks.

I have been contributing to facebook/react-native for 4 years and I specialize on the Text/TextInput components.

Thanks a lot
