### ISSUE TITLE
TextInput: Scrolling in to view not taking padding into consideration

### ISSUE THREAD

**Issue by mikefogg** [facebook/react-native#29366]
## Description
When using a multiline TextInput and writing content, the text itself will stay in view, but the padding below the content is not visible so the text is barely visible.

## React Native version:
    react: ^16.13.1 => 16.13.1
    react-native: ^0.63.0 => 0.63.0

## Steps To Reproduce

1. Create a `TextInput` component with `multiline={true}` and a fixed height so that it stays above the keyboard
2. Add a 40px padding to the TextInput 
2. Enter content that should overflow the visible area.
3. Watch as you get to the bottom and your padding disappears until you manually scroll

## Expected Results
It _should_ allow your padding (or some other value) to push the text further up into the text view so it's easier to see (see Notes, Mail, etc. apps for examples of what it should do).

## Snack, code example, screenshot, or link to a repository:
```
<TextInput style={{ height: 200, padding: 40 }} multiline={true} />
```

## Gif of the issue in action

![text-input-bug-two](https://user-images.githubusercontent.com/4834250/87422848-fa1e0f00-c59e-11ea-850c-2bccbbaf7a08.gif)

**Comment by chrisglein** [comment]
I can see what you want here, and I can also see how it's working correctly from a certain point of view. The scroll into view is based on the caret which never pushes down into that padding that you've provided. What you really want is for it to be scrolled additionally into view with some extra space. The question is whether that should happen at all points in the text or just at the end. This is tricky. I don't know if the padding should be included or if there is another path to get the larger scroll into view window.

**Comment by mikefogg** [comment]
Totally agree, it's doing what it should be in that it's keeping my text in view :)

On the other hand, it seems like there should be some way to add either additional vertical offset under the text so it's not tucked so close to the bottom, or that padding should be taken into consideration when scrolling down. I don't necessarily know the best way to handle it, and it may honestly end up as a feature request for a `verticalScrollOffset` or something along those lines if this is the intended behavior. Looking at most apps with full height text inputs (notes, mail, Notion, etc.) it seems like most of them have some sort of distance between the keyboard and the bottom of the text.

I tried every way I could think of to do that but couldn't find a way using TextInput.

**Comment by chrisglein** [comment]
@mikefogg was this behaving the same for you on Android and iOS? Trying to split out what's the native behavior here versus what RN should do.

**Comment by mikefogg** [comment]
Hey @chrisglein! Sorry about the delay there, unfortunately, I can't easily test it out on Android (my environment isn't set up for that quite yet). If this is waiting on me to get some more details on that, I'll prioritize and try and get it done.

I did manage to create the same type of experience on iOS and honestly, this seems like this is just "how it works" on iOS too... interesting. 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/4834250/88800539-f4fbbb00-d16d-11ea-9c61-b90accc24de5.gif)

**Comment by mikefogg** [comment]
Side note, the swift code for this is:
```
import SwiftUI

struct TextView: UIViewRepresentable {
    @Binding var text: String

    func makeUIView(context: Context) -> UITextView {
        var textView = UITextView()
        textView.textContainerInset = UIEdgeInsets(top: 20, left: 20, bottom: 20, right: 20)
        textView.backgroundColor = UIColor.init(red: 0.90, green: 0.90, blue: 0.90, alpha: 1.0)
        textView.font = UIFont.systemFont(ofSize: 20.0)
        return textView
    }

    func updateUIView(_ uiView: UITextView, context: Context) {
        uiView.text = text
    }
}

struct ContentView: View {
    @State var text = ""
    
    var body: some View {
        TextView(text: $text).frame(minWidth: 0, maxWidth: .infinity, minHeight: 0, maxHeight: .infinity)
    }
}

struct ContentView_Previews: PreviewProvider {
    static var previews: some View {
        ContentView()
    }
}
```

**Comment by fabriziobertoglio1987** [comment]
I wanted to ask if you still experience this issue. 
I'm planning to do 1-2 months of opensource and I'm preparing a list of tasks.

I have been contributing to facebook/react-native for 4 years and I specialize on the Text/TextInput components.

Thanks a lot
