### ISSUE TITLE
React Native 63 not showing remote or static images with iOS 14

### ISSUE THREAD

**Issue by abiespinal04** [facebook/react-native#29369]
## Description
I'm using react native 63 with Xcode Version 12.0 beta (12A6159) and iOS 14. I'm trying to use the react native image component. The simulator isn't showing any of my static image assets. Nor is it showing remote images. 

<Image source={require('../assets/img/cardsAdCardsVersion1.png')} style={{resizeMode:'cover', width, marginTop:1.5}} />

or 

<Image source={{uri: 'https://reactjs.org/logo-og.png'}} style={{width: 400, height: 400}} />

None of the Above show the image instead show an empty white background. Using iOS13 in the simulator shows the image. Problem is with iOS 14. 

## React Native version:
System:
    OS: macOS 10.15.5
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 2.70 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.5.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.5 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.7.5 - /usr/local/bin/pod
  SDKs:
    iOS SDK: Not Found
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_242 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.0 => 0.63.0 
  npmGlobalPackages:
    *react-native*: Not Found
## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Using react native Image component
2.  <Image source={require('../../../assets/img/cardsAdCardsVersion1.png')} style={{resizeMode:'cover', width, marginTop:1.5}} />
2. or <Image source={{uri: 'https://reactjs.org/logo-og.png'}} style={{width: 400, height: 400}} />

## Expected Results
Should show the image and instead shows a white background.

**Comment by abiespinal04** [comment]
Closing this issue. The solution that worked for me was https://github.com/facebook/react-native/issues/29279#issuecomment-658244428

**Comment by sobanarshad85** [comment]
Real solution 
https://github.com/facebook/react-native/issues/29279#issuecomment-658244428
