### ISSUE TITLE
TextInput: Multiline selection jumps to top or bottom

### ISSUE THREAD

**Issue by mikefogg** [facebook/react-native#29365]
## Description
When using a multiline TextInput and attempting to select the text above or below the visible screen content, the input itself will automatically "jump" to the top or bottom depending on which direction you're highlighting.

## React Native version:
    react: ^16.13.1 => 16.13.1
    react-native: ^0.63.0 => 0.63.0

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Create a `TextInput` component with `multiline={true}` and a fixed height so that it stays above the keyboard
2. Enter content that should overflow the visible area.
3. Highlight text in the middle, and drag to highlight above or below the screen content.

## Expected Results
It _should_ smoothly scroll upwards so you can continue to highlight the content just above your current selection, not all content (see Notes, Mail, etc. apps for examples of what it should do).

## Snack, code example, screenshot, or link to a repository:
```
<TextInput style={{ height: 200 }} multiline={true} />
```

## Gif of the issue in action
See how the textinput jumps from top to bottom and selects all content in between (so it's almost impossible to select just two paragraphs)

![textinput-bug](https://user-images.githubusercontent.com/4834250/87418400-3e0d1600-c597-11ea-9d4c-19fa916ade5d.gif)

**Comment by chrisglein** [comment]
Which platform is your capture from? Are you seeing the same behavior on both iOS and Android? Is the behavior different from the native control (i.e. without RN)? I'm wondering if this is a problem with the native control's behavior or with what RN brings to the table.

**Comment by chrisglein** [comment]
Attempted to reproduce in a Snack: https://snack.expo.io/@chrisglein/repro_29365_multiline_selection
Seeing that behavior on iOS but not Android. Also that would imply this isn't a new 0.63 issue, since I don't think Snack is on 0.63 yet.

**Comment by mikefogg** [comment]
Hey @chrisglein, thanks for looking into it! I noticed it on iOS but not Android as well, though I don't have my environment set up right now to test it again.

The video above was captured on an iPhone 11 Pro simulator. The same experience happens on a device as well (it was reported by users in my production app). It's definitely not a new issue, though I don't know how long it has been around. I was on 0.62 before when the issue was reported but updated to 0.63 to make sure I was on the latest version before creating a bug report.

Let me know if there's anything else I can do to help pinpoint the issue!

**Comment by chrisglein** [comment]
> Let me know if there's anything else I can do to help pinpoint the issue!

Probably the best thing would be to demonstrate that it doesn't happen with the plain native controls on iOS (aka, remove React Native from the picture). That'll clarify if this is an iOS issue or an issue in RN's iOS text selection (but not Android text selection).

**Comment by mikefogg** [comment]
@chrisglein just was able to reproduce this in Swift (taking RN out of the equation):

Here's the swift code used:
```
import SwiftUI

struct TextView: UIViewRepresentable {
    @Binding var text: String

    func makeUIView(context: Context) -> UITextView {
        var textView = UITextView()
        textView.textContainerInset = UIEdgeInsets(top: 20, left: 20, bottom: 20, right: 20)
        textView.backgroundColor = UIColor.init(red: 0.90, green: 0.90, blue: 0.90, alpha: 1.0)
        textView.font = UIFont.systemFont(ofSize: 20.0)
        return textView
    }

    func updateUIView(_ uiView: UITextView, context: Context) {
        uiView.text = text
    }
}

struct ContentView: View {
    @State var text = ""
    
    var body: some View {
        TextView(text: $text).frame(minWidth: 0, maxWidth: .infinity, minHeight: 0, maxHeight: .infinity)
    }
}

struct ContentView_Previews: PreviewProvider {
    static var previews: some View {
        ContentView()
    }
}
```

Attached a video so you can see it scrolling nicely when you hit the top/bottom of the UITextView.

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/4834250/88801187-eb268780-d16e-11ea-9954-3862590f428e.gif)

**Comment by mikefogg** [comment]
Hey @chrisglein, wanted to hop in and see if there was anything else I could do to move this one along? Thanks!

**Comment by chrisglein** [comment]
> Hey @chrisglein Chris Glein FTE, wanted to hop in and see if there was anything else I could do to move this one along? Thanks!

You've done a good job of highlighting the issue. It's been raised for core contributor attention but I don't think there's been anyone with bandwidth to dig in.

**Comment by mikefogg** [comment]
Hey guys, been a while on this one :) I know you're all really busy, is there any way someone could take a minute and just point me in the right direction on what _may_ be causing something like this? I'll spend some time digging into it and trying to see what I can figure out. Right off the bat, it seems like some sort of event is re-calculating the inset on the parent scrollview when the selection changes and the textview tries to scroll itself, but that's a shot in the dark.

**Comment by tarouboy** [comment]
> @chrisglein just was able to reproduce this in Swift (taking RN out of the equation):
> 
> Here's the swift code used:
> 
> ```
> import SwiftUI
> 
> struct TextView: UIViewRepresentable {
>     @Binding var text: String
> 
>     func makeUIView(context: Context) -> UITextView {
>         var textView = UITextView()
>         textView.textContainerInset = UIEdgeInsets(top: 20, left: 20, bottom: 20, right: 20)
>         textView.backgroundColor = UIColor.init(red: 0.90, green: 0.90, blue: 0.90, alpha: 1.0)
>         textView.font = UIFont.systemFont(ofSize: 20.0)
>         return textView
>     }
> 
>     func updateUIView(_ uiView: UITextView, context: Context) {
>         uiView.text = text
>     }
> }
> 
> struct ContentView: View {
>     @State var text = ""
>     
>     var body: some View {
>         TextView(text: $text).frame(minWidth: 0, maxWidth: .infinity, minHeight: 0, maxHeight: .infinity)
>     }
> }
> 
> struct ContentView_Previews: PreviewProvider {
>     static var previews: some View {
>         ContentView()
>     }
> }
> ```
> 
> Attached a video so you can see it scrolling nicely when you hit the top/bottom of the UITextView.
> 
> ![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/4834250/88801187-eb268780-d16e-11ea-9954-3862590f428e.gif)

I guess it is related to UITextView and iOS14 so you couldn't reproduce on SwiftUI
https://developer.apple.com/forums/thread/662056

**Comment by mikefogg** [comment]
I can certainly try! Once I figure out how to make a Native component :)

I will say though, this issue has been around for a long time, and definitely prior to iOS 14. I am able to reproduce in < iOS 14 on simulator as well. Only with the React Native TextInput, not with the Swift code above.

Since it's been about 9 months since this was reported (and I don't think it's a priority), so I'll try recreating my own Swift TextView to use in React Native.

**Comment by mikefogg** [comment]
Hey there, any update on this? It's been about a year and some change.

**Comment by safaiyeh** [comment]
Hey @mikefogg unfortunately most issues don't have active timelines or effort. The best way to move this along is to submit a PR or provide more investigation for someone to pick it up!

**Comment by fabriziobertoglio1987** [comment]
I wanted to ask if you still experience this issue. 
I'm planning to do 1-2 months of opensource and I'm preparing a list of tasks.

I have been contributing to facebook/react-native for 4 years and I specialize on the Text/TextInput components.

Thanks a lot

**Comment by vietdung97** [comment]
> I wanted to ask if you still experience this issue. I'm planning to do 1-2 months of opensource and I'm preparing a list of tasks.
> 
> I have been contributing to facebook/react-native for 4 years and I specialize on the Text/TextInput components.
> 
> Thanks a lot

I still encounter this problem. On Android, enable multiline TextInput and enter some long text and observe. It always scrolls to the bottom of the input, on the other hand, IOS scrolls to the top input
How you think about this issue?
Thanks a lot

Issues on Android
![image](https://github.com/facebook/react-native/assets/50390141/5eb8154e-cedd-46d4-b068-7cea7acfba3d)
Expected on Android (like IOS)
![image](https://github.com/facebook/react-native/assets/50390141/4b8daa0f-acb8-4428-aa88-0d57a139e9a7)
