### ISSUE TITLE
currentlyFocusedField is deprecated

### ISSUE THREAD

**Issue by gurtejsmartdata** [facebook/react-native#29367]
## Description
I have upgraded react native form 0.62.2 to 0.63 , and facing this issue
## React Native version:
System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 26.13 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.7.0 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.6 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.6 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.0 => 0.63.0 
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce

when I navigate from one page to another, I face this issue. I'm using react native router flux for navigation

## Expected Results
resolve "currentlyFocusedField is deprecated" issue

## Snack, code example, screenshot, or link to a repository:
![Simulator Screen Shot - iPhone 11 Pro - 2020-07-14 at 21 31 59](https://user-images.githubusercontent.com/38884969/87448665-c0d6b500-c619-11ea-8eb2-cf1c243db50c.png)

**Comment by chrisglein** [comment]
Is `currentlyFocusedField` used by your code or the community module you're depending on? Either way... if it's deprecated then as a result of your upgrade you'll need to resolve that.

**Comment by gurtejsmartdata** [comment]
@chrisglein router flux is using react-navigation , so problem is there. so how we can resolve that ?

**Comment by chrisglein** [comment]
Open an issue on the [react-navigation github](https://github.com/react-navigation/react-navigation/issues).
