### ISSUE TITLE
TextInput does not change the font (using custom fonts)

### ISSUE THREAD

**Issue by afouchet** [facebook/react-native#29375]
## Description
User has a button to put text in bold / not bold.
As my font is custom, I cannot use the "fontWeight" style, I have to change between font ('Rubik' for normal, 'Rubik-Bold' for bold)

The TextInput changes on first click, but not on second.
On the GIF, I put a \<Text\> Component that has same style -> Text component is working fine.
![font_text_input](https://user-images.githubusercontent.com/7079913/87522504-fc0ecd80-c685-11ea-91c2-ec7d5b7db39f.gif)

## React Native version:
info Fetching system and libraries information...
System:
    OS: Linux 4.15 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 2.81 GB / 15.48 GB
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 12.15.0 - /usr/bin/node
    Yarn: Not Found
    npm: 6.13.4 - /usr/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: Not Found
    Python: 2.7.17 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.0 => 0.63.0 
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Code to reproduce.
App.js:
`

> import React from 'react';
> import Test from './Components/Test'
> 
> const App: () => React$Node = () => {
>   return (
>     \<Test/\>
>   );
> };
> 
> 
> export default App;

`

Components/Test.js:
`

> import React from 'react'
> import { View, Text, TextInput, Button, StyleSheet } from 'react-native'
> 
> 
> class Test extends React.Component {
>   constructor(props) {
>     super(props)
>     this.state = {
>       bold: true,
>     }
>   }
> 
>   render() {
>     return (
>       <View style={ styles.main_container }>
>         <Text
>           style={ [styles.text, { fontFamily: this.state.bold ? 'Rubik' : 'Rubik-Bold' }] }
> 	>Hello world<\/Text>
>         <TextInput
>           style={ [styles.text, { fontFamily: this.state.bold ? 'Rubik' : 'Rubik-Bold' }] }
>           placeholder="Hello world"
> 	/>
>         <Button
>           title="Change font"
>           onPress={() => this.setState({ bold: !this.state.bold }) }
> 	/>
>       </View>
>     )
>   }
> 
> }
> 
> const styles = StyleSheet.create({
>   main_container: {
>     flex: 1,
>     alignItems: 'center',
>     justifyContent: 'center',
>   },
>   text: {
>     fontSize: 22,
>   }
> })
> 
> export default Test

`

**Comment by kelset** [comment]
Hello there 👋 this issue seems to have been inactive for the past few months. Because of this, it's likely that the issue is not a high priority anymore or it has been solved by OP; for these reasons, we'll close it.

But please, if it's actually still an issue with latest (RN64 at the time of writing) please comment below and we can reopen it or please send a Pull Request with a fix 😊
