### ISSUE TITLE
RN 0.63.1: ActivityIndicator disapearing

### ISSUE THREAD

**Issue by ptgamr** [facebook/react-native#29378]
## Description
With the default usage of `<ActivityIndicator />`, the indicators are all disappearing. But when I add the color prop, `<ActivityIndicator color="red" />`, I can then see the indicator again.

## React Native version:
System:
    OS: Linux 5.4 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
    Memory: 4.74 GB / 15.59 GB
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.14.1/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 23, 25, 26, 28
      Build Tools: 28.0.3, 29.0.2
      System Images: android-24 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 1.8.0_252 - /usr/bin/javac
    Python: 2.7.18 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.1 => 0.63.1 
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Any usage of `<ActivityIndicator />` inside the source code is not working. Can reproduce with the starter project: 

`npx react-native init RN063`

## Expected Results
The indicator should be visible with the default color if the `color` props is not specified

## Snack, code example, screenshot, or link to a repository:
N/A

**Comment by Ashoat** [comment]
Is this for iOS, Android, or both?

**Comment by ptgamr** [comment]
@Ashoat sorry I forgot to  mentioned in the description. It's happening only on Android.

**Comment by geniuscva** [comment]
having the same problem with RN 0.63.1

**Comment by hamaron** [comment]
Confirmed the same behavior on RN 0.63.2

**Comment by vamvoukas** [comment]
Confirmed the same behavior on RN 0.63.2

**Comment by mattijsf** [comment]
Even though it is a different component it feels somewhat related to https://github.com/facebook/react-native/issues/29412

**Comment by CDBridger** [comment]
I'm getting this as well (on android), additionally, when I do specify a colour, the component shows, but it is not animating, it just shows a static icon. I'm running 0.63.2, it worked fine when I was running 0.62.x

**Comment by nzjoel1234** [comment]
This is also happening on my S20 version 0.63.3

**Comment by jasperkuperus** [comment]
Indeed, same issue on Android 0.63.3. Thanks for the workaround with the `color` prop @ptgamr. That's a lifesaver 😊

**Comment by bidetaggle** [comment]
Apparently https://github.com/facebook/react-native/pull/29830 is the universal PR to fix this but it's been blocked since almost 2 months now.
Is there any way other than adding a color prop to each ActivityIndicator component sitting in my code to solve it before the PR get merged?

**Comment by niktechnopro** [comment]
adding <color> prop fixed the issue

**Comment by fabriziobertoglio1987** [comment]
the reason is explained here https://github.com/facebook/react-native/issues/29412#issuecomment-773412466
I will prepare a pull request and fix this. Thanks and sorry for the Bug :pray:

**Comment by bidetaggle** [comment]
> as explained in [#29412 (comment)](https://github.com/facebook/react-native/issues/29412#issuecomment-773412466) I believe pr #29830 would fix also #29412 Thanks

Thank you for your update @fabriziobertoglio1987 
Do you have any information regarding my https://github.com/facebook/react-native/issues/29378#issuecomment-719633752 ?

**Comment by AlexanderMelchers** [comment]
+1 on this issue: `ActivityIndicator` not showing up on Android without specifying the `color`-attribute.
