### ISSUE TITLE
fetch suddenly return TypeError: Network request failed

### ISSUE THREAD

**Issue by luiey** [facebook/react-native#29373]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Please provide a clear and concise description of what the bug is. Include screenshots if needed.
Please test using the latest React Native release to make sure your issue has not already been fixed: https://reactnative.dev/docs/upgrading.html

## React Native version:
System:
    OS: Windows 10 10.0.18362
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
    Memory: 1.28 GB / 7.68 GB
  Binaries:
    Node: 12.10.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.10.3 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 21, 22, 23, 25, 26, 27, 28, 29
      Build Tools: 23.0.3, 28.0.2, 28.0.3, 29.0.0, 29.0.2
      System Images: android-25 | Google APIs Intel x86 Atom, android-26 | Android TV Intel x86 Atom, android-26 | Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-28 | Android TV Intel x86 Atom, android-28 | Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6514223
  Languages:
    Java: 11.0.5
    Python: 3.6.1
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.
**This problem suddenly happen this week.**

1. On `await fetch(url)`, it jump straight to catch.
2. If I open another project, the fetch will failed too. If I run installed APK, it can fetch url. If I build assembleRelease and installed, fetch will failed again.

```
async function fetchParams(apiURL) {
    return new Promise(async (resolve, reject) => {
        try {
            const options = {
                method: "POST",
                headers: {
                    'Accept': 'application/json',
                    'Content-Type': 'application/json'
                },
            };
            console.log('URL: ' + apiURL + ', OPT: ' + JSON.stringify(options));
            const response = await fetch(apiURL, options);
            const responseStatus = response.status;
            const responseData = await response.json();
            if (response.status === 404) {
                console.warn('Fetch 404: ' + responseData);
                return reject(responseData);
            } else {
                console.log('Fetch response: ' + responseData);
                return resolve({ status: responseStatus, data: responseData });
            }
        }
        catch (error) {
            console.warn('Fetch catch: ' + error);
            return reject(error);
        }
    });
}

function HelloServer(url) {
    return new Promise(async (resolve, reject) => {
        await fetchParams(`${url}/helloserver`)
            .then((response) => {
                console.log('Fetch resolve: ' + response);
                setTimeout(function () {
                    resolve(response);
                }, 500)
            })
            .catch(e => {
                console.log('Fetch rejected: ' + e);
                setTimeout(function () {
                    reject(e);
                }, 500)
            });
    })
}
```
3. Tried axios to ensure what is the problem. Same thing happen, cannot connect to web api.
4. Postman return response.

## Expected Results
Fetch will return response.

## Snack, code example, screenshot, or link to a repository:
I also post my problem on [https://stackoverflow.com/questions/62907234/react-native-fetch-suddenly-return-typeerror-network-request-failed](https://stackoverflow.com/questions/62907234/react-native-fetch-suddenly-return-typeerror-network-request-failed)

I have run `adb logcat` and have below log before start fetching log written:-

```
07-08 17:09:05.209  2109  7288 E unknown:ReactContextBaseJavaModule: Unhandled SoftException
07-08 17:09:05.209  2109  7288 E unknown:ReactContextBaseJavaModule: java.lang.RuntimeException: Catalyst Instance has already disappeared: requested by WebSocketModule
07-08 17:09:05.209  2109  7288 E unknown:ReactContextBaseJavaModule:    at com.facebook.react.bridge.ReactContextBaseJavaModule.getReactApplicationContextIfActiveOrWarn(ReactContextBaseJavaModule.java:67)
07-08 17:09:05.209  2109  7288 E unknown:ReactContextBaseJavaModule:    at com.facebook.react.modules.websocket.WebSocketModule.sendEvent(WebSocketModule.java:62)
07-08 17:09:05.209  2109  7288 E unknown:ReactContextBaseJavaModule:    at com.facebook.react.modules.websocket.WebSocketModule.access$100(WebSocketModule.java:40)
07-08 17:09:05.209  2109  7288 E unknown:ReactContextBaseJavaModule:    at com.facebook.react.modules.websocket.WebSocketModule$1.onMessage(WebSocketModule.java:187)
07-08 17:09:05.209  2109  7288 E unknown:ReactContextBaseJavaModule:    at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:322)
07-08 17:09:05.209  2109  7288 E unknown:ReactContextBaseJavaModule:    at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:219)
07-08 17:09:05.209  2109  7288 E unknown:ReactContextBaseJavaModule:    at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:105)
07-08 17:09:05.209  2109  7288 E unknown:ReactContextBaseJavaModule:    at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:273)
07-08 17:09:05.209  2109  7288 E unknown:ReactContextBaseJavaModule:    at okhttp3.internal.ws.RealWebSocket$1.onResponse(RealWebSocket.java:209)
07-08 17:09:05.209  2109  7288 E unknown:ReactContextBaseJavaModule:    at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174)
07-08 17:09:05.209  2109  7288 E unknown:ReactContextBaseJavaModule:    at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
07-08 17:09:05.209  2109  7288 E unknown:ReactContextBaseJavaModule:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
07-08 17:09:05.209  2109  7288 E unknown:ReactContextBaseJavaModule:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
07-08 17:09:05.209  2109  7288 E unknown:ReactContextBaseJavaModule:    at java.lang.Thread.run(Thread.java:761)
```

**Comment by a7ul** [comment]
Hey @luiey  How did you solve this issue ?

**Comment by vajid-khan** [comment]
Facing same issue on iOS, any fixes?

**Comment by NanduKkd** [comment]
Hey @luiey it would have been very much helpful for all, if you had shared your solution before closing the issue. Please do that
