### ISSUE TITLE
React native app crashes in IOS 13 version devices

### ISSUE THREAD

**Issue by sankar9659** [facebook/react-native#29374]
I am working on react-native app. The app is running perfectly in android and IOS below 13 version. and it crashed in IOS 13 and above version devices. I can't get any error or warning while running in IOS 13 version device. I don't know which package does not supports with the IOS 13 version device. I am fully wasted 2 days for this issue. any body know the solution

Here is my package.json

<
{
  "name": "Reapp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint .",
    "build-release": "react-native run-android --variant=release && open android/app/build/outputs/apk/release",
    "reverse": "adb reverse tcp:8081 tcp:8081 && adb reverse tcp:9090 tcp:9090",
    "clean": "cd android && gradlew clean && cd ..",
    "cleanrun": "cd android && gradlew clean && cd .. && react-native run-android",
    "delbuild": "rmdir android\\app\\build /s /q",
    "tron-emulator": "node ReactotronEmulator.js",
    "tron-device": "node ReactotronDevice.js",
    "debug-build": "react-native bundle --dev false --platform android --entry-file index.js --bundle-output ./android/app/build/intermediates/assets/debug/index.android.bundle --assets-dest ./android/app/build/intermediates/res/merged/debug && cd android && gradlew assembleDebug && cd ..",
    "select": "node firebaseEnv"
  },
  "rnpm": {
    "assets": [
      "src/assets/fonts/"
    ]
  },
  "dependencies": {
    "@invertase/react-native-apple-authentication": "^1.1.2",
    "@react-native-community/async-storage": "^1.7.1",
    "@react-native-community/netinfo": "^4.7.0",
    "@react-native-community/push-notification-ios": "^1.0.5",
    "@react-native-community/viewpager": "^3.3.0",
    "@react-native-firebase/analytics": "^6.2.0",
    "@react-native-firebase/app": "^6.2.0",
    "@react-native-firebase/auth": "^6.2.0",
    "amazon-cognito-identity-js": "^4.2.1",
    "aws-amplify": "^3.0.8",
    "aws-appsync": "^3.0.2",
    "axios": "^0.19.0",
    "eslint": "^6.8.0",
    "geolib": "^3.2.0",
    "graphql-tag": "^2.10.0",
    "instabug-reactnative": "^9.0.1",
    "lodash": "^4.17.10",
    "moment": "^2.22.2",
    "prop-types": "^15.6.2",
    "react": "16.9.0",
    "react-apollo": "^2.3.3",
    "react-native": "0.61.5",
    "react-native-appstore-version-checker": "^2.7.2",
    "react-native-barcode-builder": "^1.0.5",
    "react-native-beacons-manager": "git://github.com/MacKentoch/react-native-beacons-manager.git#53c1bda",
    "react-native-bluetooth-status": "^1.3.0",
    "react-native-camera": "^3.15.0",
    "react-native-device-info": "^2.2.1",
    "react-native-easy-toast": "^1.2.0",
    "react-native-exit-app": "^1.0.0",
    "react-native-fbsdk": "^1.1.1",
    "react-native-floating-action": "^1.19.1",
    "react-native-geolocation-service": "^3.1.0",
    "react-native-gesture-handler": "^1.5.3",
    "react-native-image-picker": "^0.26.10",
    "react-native-image-placeholder": "^1.0.14",
    "react-native-immediate-phone-call": "^1.0.0",
    "react-native-in-app-utils": "^6.0.2",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-modal": "^6.5.0",
    "react-native-onesignal": "^3.6.1",
    "react-native-pdf": "^5.0.9",
    "react-native-pulse": "^1.0.7",
    "react-native-push-notification": "^3.1.9",
    "react-native-qr-generator": "^1.0.4",
    "react-native-reanimated": "^1.7.0",
    "react-native-responsive-screen": "^1.2.0",
    "react-native-splash-screen": "^3.2.0",
    "react-native-swiper": "^1.5.13",
    "react-native-system-setting": "^1.7.2",
    "react-native-tab-view": "^2.0.1",
    "react-native-text": "0.0.8",
    "react-native-vector-icons": "^6.6.0",
    "react-native-webview": "^8.0.2",
    "react-navigation": "^3.2.3",
    "react-redux": "^7.1.3",
    "redux": "^4.0.4",
    "redux-persist": "^6.0.0",
    "redux-saga": "^1.1.3",
    "rn-fetch-blob": "^0.10.16",
    "socket.io-client": "^2.2.0",
    "tipsi-stripe": "^7.5.1"
  },
  "devDependencies": {
    "@babel/core": "^7.6.2",
    "@babel/runtime": "^7.6.2",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.9.0",
    "eslint": "^6.5.1",
    "babel-eslint": "^8.2.6",
    "metro-react-native-babel-preset": "^0.56.0",
    "eslint-config-google": "^0.9.1",
    "eslint-plugin-babel": "^5.1.0",
    "eslint-plugin-flowtype": "^2.50.0",
    "eslint-plugin-react": "^7.10.0",
    "jest": "^24.9.0",
    "react-test-renderer": "16.9.0",
    "reactotron-react-native": "^2.1.0",
    "simple-plist": "^1.0.0"
  },
  "jest": {
    "preset": "react-native"
  }
}
>

**Comment by sankar9659** [comment]
<>
    OS: macOS 10.15.2
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 37.52 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 8.11.2 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    create-react-native-app: 1.0.0
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
<>



I got these details

**Comment by ktomi42** [comment]
I had problem after upgrade to 0.63.1, to me it seems problem was with following 
    "@react-native-firebase/analytics"
    "@react-native-firebase/app"
    "@react-native-firebase/auth"
    "@react-native-firebase/dynamic-links"

After i upgraded these packages to lates veriosn and cleared the iOS build folder and build it again than app booted okey, only but tested only on simulator though.

**Comment by tradebulls** [comment]
We tried creating a a new project with RN 0.66.1 and adding following libraries:
    "react": "17.0.2",
    "react-native": "0.66.1",
    "react-redux": "7.2.5",
    "redux": "4.1.1",
    "redux-thunk": "2.3.0"

When we try to run a debug build, it works fine but it crashes the app on launch in Release mode in iOS 13.5.1. It works fine in the latest version of IOS i.e 15.0.

We have tried many approaches and narrowed down that it's happening because of Redux.

Any help?
