### ISSUE TITLE
Upgrade 0.62.2 -> 0.63.1 ReactNativeJS: Invariant Violation: Module RCTDeviceEventEmitter is not a registered callable module (calling emit)

### ISSUE THREAD

**Issue by irekrog** [facebook/react-native#29386]
## Description
After upgrade from 0.62.2 to 0.63.1 Android app doesn't work. Whole time is white screen.

With `adb logcat` there is an error:

> ReactNativeJS: Invariant Violation: Module RCTDeviceEventEmitter is not a registered callable module (calling emit)

## React Native version:
System:
    OS: macOS 10.15.5
    CPU: (8) x64 Intel(R) Core(TM) i5-1030NG7 CPU @ 1.10GHz
    Memory: 512.32 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.16.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 14.0.1 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.1 => 0.63.1 
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Upgrade from 0.62.2 to 0.63.1
2. react-native run-android
3. Bundle has 100% but app doesn't work

## Expected Results
App should be work after upgrade.

**Comment by vitalyiegorov** [comment]
Having the same issue

**Comment by fattahmuhyiddeen** [comment]
same

**Comment by jjercx** [comment]
any workaround?

**Comment by rt012** [comment]
same problem here

**Comment by irekrog** [comment]
I tried upgrade to latest version **0.63.3** instead 0.63.1 and **it works** fine now
