### ISSUE TITLE
Help! I cant run my app. 

### ISSUE THREAD

**Issue by monkhsaikhan** [facebook/react-native#29384]
I can't run my app on ios simulator. It was working perfectly a few months ago. But now I have a problem. 
How to fix this error?
<img width="381" alt="Screen Shot 2020-07-16 at 00 07 29" src="https://user-images.githubusercontent.com/6801431/87570289-facbb800-c6fa-11ea-9534-1e5b1632e4d9.png">

I delete node_module and pod files. Then I reinstall. But not fixed.

**Comment by SConaway** [comment]
Add `--resetCache` to the start command to clear any caches
