### ISSUE TITLE
Link Assets 0.63.0 typescript template

### ISSUE THREAD

**Issue by farshidshahmoradi1996** [facebook/react-native#29385]
## Description
Hi, I create new RN Project with command  `npx react-native init AwesomeTSProject --template react-native-template-typescript` then add font in `src/assets/fonts` and want to link fonts with `npx react-native link`

## React Native version:
System:
    OS: Linux 5.4 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i5-2320 CPU @ 3.00GHz
    Memory: 362.99 MB / 7.76 GB
    Shell: 5.0.16 - /bin/bash
  Binaries:
    Node: 12.18.2 - ~/.nvm/versions/node/v12.18.2/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v12.18.2/bin/npm
    Watchman: 4.9.0 - /home/linuxbrew/.linuxbrew/bin/watchman
  SDKs:
    Android SDK:
      API Levels: 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.1
      System Images: android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 11.0.7 - /usr/bin/javac
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.0 => 0.63.0 
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce

1.init new project with `npx react-native init AwesomeTSProject --template react-native-template-typescript`
2.add fonts in src/assets/fonts
3.add `react-native.config.js` file with :
```
module.exports = {
  project: {
    ios: {},
    android: {}, // grouped into "project"
  },
  assets: ['./src/assets/fonts/'],
};
```
4. run `npx react-native link`

## Expected Results
Link font for android and ios 

## screenshot
![Screenshot from 2020-07-15 21-19-53](https://user-images.githubusercontent.com/37307562/87572534-f1cded00-c6e0-11ea-8f50-5ac17add425d.png)

**Comment by safaiyeh** [comment]
Hi @farshidshahmoradi1996 thank you for the issue.

This seems to be an issue with the react-native-template-typescript repo. Could you create an issue here: https://github.com/react-native-community/react-native-template-typescript?

I will close for now, if this issue exists on a new React Native project with the default template, I'd be happy to reopen.
