### ISSUE TITLE
Unclear error message when trying to render a Text element with an empty string

### ISSUE THREAD

**Issue by cosmith** [facebook/react-native#2938]
I spent a while debugging this, trying to find which part of my JSX was failing... I think we can improve the error messages.

Sample app here: https://rnplay.org/apps/6kbWOg

Failing code: 
```js
'use strict';

var React = require('react-native');
var {
  AppRegistry,
  Text,
  View,
} = React;

var SampleApp = React.createClass({
  getInitialState: function () {
  	return {empty: ""};
  },
  render: function() {
    return (
      <View>
        {this.state.empty && <Text>{this.state.empty}</Text>}
      </View>
    );
  }
});

AppRegistry.registerComponent('SampleApp', () => SampleApp);
```

This code fails on both iOS with the following message: `Raw text cannot be used outside of a <Text> tag. Not rendering string: ''`, and on Android with this message: `Trying to add unknown view tag: 5 detail: View tag: 1 children(0) [], viewsToAdd(1): [[0,5]],`.

I think it should probably work though, it only fails if you have the conditional part `{this.state.empty && ...}`

**Comment by cosmith** [comment]
Actually the proper way would have been to do `{!!this.state.empty && <Text>{this.state.empty}</Text>}` and then it doesn't fail. Not sure why it breaks with a falsey value.

**Comment by ide** [comment]
Your falsy value is a string so I believe this is working as intended and the error message explains that you're trying to render the empty string outside of Text.

**Comment by cosmith** [comment]
Ah yes it's rendering the first part of the expression. Thanks!

**Comment by raphaeleidus** [comment]
so I just ran into this error in my codebase. The error trace still doesn't really help find the source but...
if you do a regex file contents search for `{(?!(?:!|\(!)).*&&.*<Text` It should return all the likely culprits
