### ISSUE TITLE
Problem with File uploading while using Fetch or XHR

### ISSUE THREAD

**Issue by vikasg603** [facebook/react-native#29389]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
       
        var xhr = new XMLHttpRequest();
        xhr.onreadystatechange = () => {
            console.log(xhr.readyState);
        };

        xhr.open("POST", config.BaseURL + 'Profile/EditProfile');
        xhr.responseType = 'json';
        xhr.setRequestHeader("Content-Type", 'multipart/form-data');
        xhr.setRequestHeader("Authorization", Token);

        xhr.upload.onprogress = function(event) {
            console.log(`Uploaded ${event.loaded} of ${event.total} bytes`);
        };

        xhr.upload.loadstart = function(event) {
            console.log(event);
        };

        xhr.onerror = function(err) {
           console.log(err);
           reject(err);
        };

        xhr.onload = async function() {
            console.log(this.status);
        };
        xhr.send(formData);

When I try to upload a file using the code above where my formData is
        
        formData.append('Name', Name);
        formData.append('Email', Email);
        formData.append('About', About);
        formData.append('File', {uri: "ImagePath", name: "name.jpeg", type: "image/jpg"});
        formData.append('Address', Address);
        formData.append('City', City.value);
        formData.append('PinCode', PinCode);

React Native shows nothing in my console even not showing anything about load start or status change.
Even there is no log in my server about any request.

I tried the same using Fetch API but there also it's the same case, Every other API works perfectly but the issue comes when I have a file to upload, Before updating React Native It was working perfectly but then now it's not working.

## React Native version:
System:
    OS: macOS 10.15.5
    CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
    Memory: 101.85 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.6 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.2 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^16.13.1 => 16.13.1 
    react-native: ^0.63.1 => 0.63.1 
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. When Uploading any file using multipart Either using Fetch or XHR call

## Expected Results
It should work as it was working perfectly before  

## Snack, code example, screenshot, or link to a repository:
![code](https://user-images.githubusercontent.com/25488833/87596090-28216180-c70d-11ea-97fa-48b58342b41f.png)

**Comment by pedrohram** [comment]
This is likely caused by the Flipper plugin. Commenting the line 43 at android/app/src/debug/java/com/.../ReactNativeFlipper.java and building your app again might resolve the issue.

```java
new NetworkingModule.CustomClientBuilder() {
  @Override
    public void apply(OkHttpClient.Builder builder) {
      // builder.addNetworkInterceptor(new FlipperOkhttpInterceptor(networkFlipperPlugin));
    }
});
```

**Comment by safaiyeh** [comment]
Hello @vikasg603 thanks for the issue. We are tracking this here: https://github.com/facebook/react-native/issues/28551 closing as a duplicate.

**Comment by vikasg603** [comment]
I don't think it's duplicate as The issue which you have mentioned is for Android only and was happened with me too.

It got resolved when i updated flipper.
Also previously it was showing something like stream error.

But now there is no success or failure from fetch or even XHR.

This issue came when i updated React native from .62 to .63

**Comment by vikasg603** [comment]
Problem resolved It was rather Image Crop Picker issue,
The issue was I was using iOS simulator and was passing image path without file:///

Resolved using 
Platform.OS === 'ios' ?  "file:///" + response.path : response.path
