### ISSUE TITLE
[TextInput] Some properties and styles seems invalid

### ISSUE THREAD

**Issue by TooBug** [facebook/react-native#294]
```
<TextInput style={styles.input} placeholder="test" placeholderTextColor="#ffffff" />
```

```
input:{
    height:50,
    color:'#ffffff',
    textAlign:'center',
    backgroundColor:'#1D1F26',
    fontSize:20
  }, 
```

The `placeholderTextColor` and `textAlign` has no effect. Did I miss something?

**Comment by sahrens** [comment]
Currently we don't throw or even warn if you provide unsupported react props, we'll only tell you if you provide the wrong *type* for a propType that is declared. It would be nice to fix this somehow :\

**Comment by TooBug** [comment]
Thanks for explanation!

In my understanding, what you mean is: If I use something that is unsupported now, react-native may not give out a warning or an error.

But, both `placeholderTextColor` and `textAlign` are in the docs, but has no effect. So I'm not sure whether I have missed something. Quite confused.

**Comment by jaygarcia** [comment]
@sahrens , what @TooBug is referring to is the props docs: http://facebook.github.io/react-native/docs/textinput.html#props

```
placeholder string 

The string that will be rendered before text input has been entered

placeholderTextColor string 

The text color of the placeholder string
```

**Comment by TooBug** [comment]
Exactly! But has no effect.

**Comment by sahrens** [comment]
Those props should work - they are used in the Movies and UIExplorer example apps.

I was specifically referring to multi line support - I don't think that is working in OSS yet and might break things if you try to use it. 

-Spencer

**Comment by JonathanMatthey** [comment]
placeholderTextColor doesn't work :( 

also you can see that they're not used in the Movies or UIExplorer examples:

![image](https://cloud.githubusercontent.com/assets/548027/6887587/22f2cd74-d632-11e4-9e65-62610cdf9f08.png)

**Comment by wski** [comment]
I'm getting issues with placeholderTextColor as well 
![cd01781b867d36e88360b2ddd8c1609e](https://cloud.githubusercontent.com/assets/1770198/6888790/56a416b8-d656-11e4-996a-d8817d65c7b0.png)

**Comment by jlmitch5** [comment]
@wski looks like that prop is not being rendered...placeholderTextColor is not found in the render step.
https://github.com/facebook/react-native/blob/f3cd27cf483671b8821e4f50bfa7bb370893e59a/Libraries/Components/TextInput/TextInput.ios.js#L329-L346

**Comment by jlmitch5** [comment]
@wski PR submitted https://github.com/facebook/react-native/pull/467

**Comment by jlmitch5** [comment]
psych this doesn't fix it...closing PR :(

**Comment by darylrowland** [comment]
Should textAlign: 'center' work on a TextInput? It doesn't seem to be working for me?

**Comment by wski** [comment]
@darylrowland I suspect anything listed under props here should work: http://facebook.github.io/react-native/docs/textinput.html#props but I'm not sure. If that is the case I hope more is added later. It would be super nice to be able to only have a bottom border on inputs instead of a solid full wrapped border.

**Comment by jamalneufeld** [comment]
I'm also experiencing placeholderTextColor having no effect. It doesn't work in any of the scenarios below: 
```
<TextInput
    autoCapitalize="none"
    autoCorrect={false}
    onSubmitEditing={this.props.onSearch}
    placeholder="Search..."
    placeholderTextColor="#ffffff"
    style={styles.searchBarInput}
/>
```
```
<TextInput
    autoCapitalize="none"
    autoCorrect={false}
    onSubmitEditing={this.props.onSearch}
    placeholder="Search..."
    placeholderTextColor="white"
    style={styles.searchBarInput}
/>
```
```
<TextInput
    autoCapitalize="none"
    autoCorrect={false}
    onSubmitEditing={this.props.onSearch}
    placeholder="Search..."
    placeholderTextColor={styles.placeholder}
    style={styles.searchBarInput}
/>
...
var styles = StyleSheet.create({
...
    placeholder: {
        color: '#ffffff'
    }
...
});
```
Nothing seems to work.

**Comment by nicholasstephan** [comment]
I'm seeing this too.

**Comment by drkibitz** [comment]
It looks like `TextInout.js` assumes `placeholderTextColor` is handled on the native side, when it is clearly not. `placeholder` is a one to one mapping of the property on `UITextField`, but `placeholderTextColor` does not, most likely needs to be implmented using UITextField's attributedPlaceholder.

**Comment by MossP** [comment]
This appears to be working now?.. (Tested in v0.7.1) One to close @brentvatne

**Comment by luisfuertes** [comment]
textAlignVertical doesn't work for me with
``` 
    "react": "15.2.1",
    "react-native": "0.29.1",
``` 

How can i fix?
