### ISSUE TITLE
View a flashback

### ISSUE THREAD

**Issue by JonsonHI** [facebook/react-native#29404]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Please provide a clear and concise description of what the bug is. Include screenshots if needed.
Please test using the latest React Native release to make sure your issue has not already been fixed: https://reactnative.dev/docs/upgrading.html

## React Native version:
Run `react-native info` in your terminal and copy the results here.

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.RN 0.62.2    ios
2.View issue

code:
```
 return (
        <View style={{width:SCREEN_WIDTH,height:SCREEN_HEIGHT,backgroundColor:'red'}}>
            <View style={{height:40,width:40,backgroundColor:'blue'}}>

            </View>
        </View>
    );
```

picture:

![image](https://user-images.githubusercontent.com/18373125/87757406-3078ba00-c83d-11ea-85d7-493a7d46b20a.png)

**Please look at the code
Why is the Ui sequence loaded down below**

There's nothing wrong with Android

What is the setting of iOS?

**Comment by safaiyeh** [comment]
Hi @JonsonHI could you fill out all the sections on the issue template and provide a repro?

Also, what device & OS version is the issue happening on?
