### ISSUE TITLE
[iOS] Websocket doesn't using system proxy settings

### ISSUE THREAD

**Issue by bill2004158** [facebook/react-native#29408]
##  Description
Fetch/Ajax can connect to our server with system proxy settings.
however, websocket always connect fail.

## React Native version:
0.62

## Expected Results
websocket should connect servers like fetch/ajax using system proxy settings.

**Comment by bill2004158** [comment]
https://github.com/facebook/react-native/blob/master/Libraries/WebSocket/RCTSRWebSocket.m#L497
after created readStream,

then it should read system proxy settings:
`CFDictionaryRef proxySettings = CFNetworkCopySystemProxySettings();`

and apply to socket if has proxy:
`CFReadStreamSetProperty((CFReadStreamRef)readStream, kCFStreamPropertySOCKSProxy, (CFTypeRef)proxyToUse);`

**Comment by hanayashiki** [comment]
Any news on that?

**Comment by hanayashiki** [comment]
I don't why everybody doesn't need such a proxy, for me the following code works:

I edited https://github.com/facebook/react-native/blob/master/Libraries/WebSocket/RCTSRWebSocket.m#L497 as below

```
  CFStreamCreatePairWithSocketToHost(NULL, (__bridge CFStringRef)host, port, &readStream, &writeStream);
    
  CFDictionaryRef proxySettings = CFNetworkCopySystemProxySettings();
  
  if (CFDictionaryContainsKey(proxySettings, kCFStreamPropertySOCKSProxyHost)) {
    CFReadStreamSetProperty((CFReadStreamRef)readStream, kCFStreamPropertySOCKSProxy, (CFTypeRef)proxySettings);
    CFReadStreamSetProperty((CFReadStreamRef)writeStream, kCFStreamPropertySOCKSProxy, (CFTypeRef)proxySettings);
  }

  _outputStream = CFBridgingRelease(writeStream);
  _inputStream = CFBridgingRelease(readStream);
```

And it works like a charm. Little tips: For working with Charles proxy, you need to enable SOCKS Proxy which seems not enabled by default

![image](https://user-images.githubusercontent.com/26056783/109371754-32870a80-785b-11eb-9b08-4467d609fcb4.png)

**Comment by shaikhalid** [comment]
Hi everyone, I am facing this exact problem. I am using expo, and hence I created an issue on expo but @Kudo mentioned that once react-native integrates this fix to their SDK it should come to expo. 

Can someone please help me understand if there is any timelines for this.

**Comment by hanayashiki** [comment]
> Hi everyone, I am facing this exact problem. I am using expo, and hence I created an issue on expo but @Kudo mentioned that once react-native integrates this fix to their SDK it should come to expo.
> 
> Can someone please help me understand if there is any timelines for this.

no, there isn't. patch/fork your own version of react-native because facebook engineers don't have the time

**Comment by hanayashiki** [comment]
😄
