### ISSUE TITLE
Android emulator not displaying developer menu

### ISSUE THREAD

**Issue by ajfick** [facebook/react-native#29400]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Running `npx react-native run-android` builds the app and opens in the android emulator. It will display exceptions as it should in a dev build, but the app doesn't seem to connect to the package manager or allow use of the developer menu.

I have tried `adb shell input keyevent 82` as documented, `Cmd + M`, and shaking the device through the virtual sensors in emulator settings with no results. I also have run `adb reverse tcp:8081 tcp:8081` as mentioned in a few issues on stackoverflow.  The yellow warning and red error notification boxes still appear on this build, so it is a certainly a dev build.

This appears to have happened after an update to Android 28 with RN 0.59 and has followed my project on different machines including Windows and Mac.

## React Native version:
```
  React Native Environment Info:
    System:
      OS: macOS 10.15.5
      CPU: (8) x64 Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz
      Memory: 753.95 MB / 16.00 GB
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.5.0 - /usr/local/bin/node
      npm: 6.14.5 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6200805
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.9.0 => 16.13.1
      react-native: ^0.59.5 => 0.59.10
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Build app with `npx react-native run-android`
2. In emulator, try any of the documented methods to display the developer menu

## Expected Results
The developer menu should appear with one of the documented steps. However after update to Android 28 it does not.

## Snack, code example, screenshot, or link to a repository:
Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by fabriziobertoglio1987** [comment]
on latest master 
![Screenshot_1594968611](https://user-images.githubusercontent.com/24992535/87757235-98fa7380-c80a-11ea-9b75-24c6e53fb856.png)

**Comment by fabriziobertoglio1987** [comment]
True. I'll have a look tomorrow. Related https://github.com/facebook/react-native/pull/29204

**Comment by fabriziobertoglio1987** [comment]
The reality is that I never debug Java or JavaScript. I suggest you to use console.log in JavaScript and Log.w in Java, but I'll fix this as soon as I find a solution to https://github.com/facebook/react-native/issues/17530

**Comment by ajfick** [comment]
@fabriziobertoglio1987 I have used logcat in some cases for Android, but a related issue here is that I cannot reload the app from the metro bundler. So when I make changes to my react code, the only way I can reload is by quitting and restarting the app or reinstalling. Is there a better solution that I'm missing with regard to the built in Android Studio debugging tools perhaps?

**Comment by safaiyeh** [comment]
Hi @ajfick your React Native version is a bit old. Could you verify this still occurs in 0.63?

**Comment by rectified95** [comment]
@safaiyeh I've just verified this on 63.3 - can't pull up the dev menu while in the simulator.

**Comment by ajfick** [comment]
Version 0.63 fixed this issue for my team. @rectified95 Are you able to connect to Flipper? Once we got flipper working, we were able to use the dev tools correctly again by hitting "R,R" in the simulator.
