### ISSUE TITLE
Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.

### ISSUE THREAD

**Issue by kdrkrtin** [facebook/react-native#29405]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
I made all the necessary installations for react native in the windows operating system. Then I created my project with "npx react-native init project-name". Then I wanted to run my project with "npx react-native run-android" but I get an error.

## React Native version:
    "react": "16.13.1",
    "react-native": "0.63.1"

## Steps To Reproduce
The problem is most likely in the file "native.modules.gradle". But I couldn't understand what it was. The only thing I did was to do the necessary setups for react native, and then I ran the project, but I'm getting an error.

1.
2.

## Expected Results
My project should run smoothly with "npx react-native run-android" command

## Snack, code example, screenshot, or link to a repository:
![react-native](https://user-images.githubusercontent.com/62345273/87769742-b76e6800-c826-11ea-9ebd-131b3d239eea.png)

**Comment by EnzoPortela** [comment]
You solve this issue?

**Comment by dolphinflow86** [comment]
Same here

**Comment by Mingyang-Li** [comment]
@kdrkrtin Hey I know it's been a while, but how did you resolve this issue?

I ran into a conbination of problems including this one for my builds, here're a few things I tried: https://github.com/facebook/react-native/issues/29568#issuecomment-1123182619

**Comment by cortinico** [comment]
> @kdrkrtin Hey I know it's been a while, but how did you resolve this issue?

Closing as this issue is too old. Please open a new issue
