### ISSUE TITLE
Network Request fail while using fetch on http endpoints in expo

### ISSUE THREAD

**Issue by rajprakash00** [facebook/react-native#29410]
I am using expo and i don't have android and ios directory. How can i fix this issue.?
However, I am running it on lower version of API also but it is not working.

_Originally posted by @vickykeshri in https://github.com/facebook/react-native/issues/24408#issuecomment-532086793_

I've had a similar problem,can be soved by replacing `localhost:port` with `server IP adress:port`

**Comment by safaiyeh** [comment]
Hi @rajprakash00 you should file expo related issues on their repo https://github.com/expo/expo

Thanks!
