### ISSUE TITLE
Error while updating property 'nativeBackgroundAndroid' of a view managed by: RCTView

### ISSUE THREAD

**Issue by euthribeiro** [facebook/react-native#29414]
FATAL EXCEPTION: main
com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'nativeBackgroundAndroid' of a view managed by: RCTView
	at com.facebook.react.uimanager.b1$l.a()
	at com.facebook.react.uimanager.z0$c.a()
	at com.facebook.react.uimanager.z0.a()
	at com.facebook.react.uimanager.ViewManager.updateProperties()
	at com.facebook.react.uimanager.m.a()
	at com.facebook.react.uimanager.v0$e.execute()
	at com.facebook.react.uimanager.v0$j.c()
	at com.facebook.react.uimanager.v0$j.b()
	at com.facebook.react.uimanager.e.a()
	at com.facebook.react.modules.core.g$d.a()
	at com.facebook.react.modules.core.a$a$a.doFrame()
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:789)
	at android.view.Choreographer.doCallbacks(Choreographer.java:591)
	at android.view.Choreographer.doFrame(Choreographer.java:560)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:777)
	at android.os.Handler.handleCallback(Handler.java:730)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:176)
	at android.app.ActivityThread.main(ActivityThread.java:5419)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	... 24 more
Caused by: java.lang.VerifyError: com/facebook/react/views/view/c
	at com.facebook.react.views.view.ReactViewManager.setNativeBackground()

Devices info:

Galaxy s3
Test code
1

Screen size
720 × 1280

Test duration
300 seconds

Screen density (dpi)
320
Model name
Galaxy s3
RAM
1024 MB
Manufacturer
Samsung
OpenGL ES version
2.0
Android version
Android 4.3
Native platform
armeabi-v7a
Locality
pt_BR
CPU brand
Samsung
CPU model
Exynos 4412

Galaxy S3
Código de teste
1

Tamanho da tela
720 × 1280

Duração do teste
300 segundos

Densidade da tela (dpi)
320
Nome do modelo
Galaxy S3
RAM
1024 MB
Fabricante
Samsung
Versão OpenGL ES
2.0
Versão do Android
Android 4.3
Plataforma nativa
armeabi-v7a
Localidade
pt_BR
Marca da CPU
Samsung
Modelo de CPU
Exynos 4412

## Description
I'm having trouble uploading the app to the play store. The return to the Galaxy S3 device is the following error:
com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'nativeBackgroundAndroid' of a view managed by: RCTView

Don't know what to do to solve.

## React Native version:
System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
    Memory: 923.28 MB / 7.88 GB
  Binaries:
    Node: 14.5.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.0 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 23, 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.0
      System Images: android-28 | Google Play Intel x86 Atom, android-29 | Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6514223
  Languages:
    Java: 1.8.0_211
    Python: 3.8.4
  npmPackages:
    @react-native-community/cli: ^4.10.1 => 4.10.1
    react: 16.13.1 => 16.13.1
    react-native: 0.63.0 => 0.63.0
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

The error occurs as soon as you open the application, the logo cannot report a form of reproduction or error. This happens only in the production environment.
![1](https://user-images.githubusercontent.com/36652917/87830350-3aa7b200-c857-11ea-9b25-8e906d1294f1.png)
![Sem título](https://user-images.githubusercontent.com/36652917/87830353-3bd8df00-c857-11ea-9895-728ef6025518.png)

**Comment by dcboy** [comment]
watch this , is the same for me ,run on android emulator API 19 

`
System:
    OS: macOS 10.15.5
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 1.40 GB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.1 - /usr/local/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 15, 18, 20, 22, 23, 25, 26, 27, 28, 29
      Build Tools: 23.0.1, 23.0.2, 24.0.1, 25.0.0, 25.0.1, 25.0.3, 26.0.0, 26.0.2, 27.0.3, 28.0.2, 28.0.3, 29.0.0, 29.0.2, 29.0.3
      System Images: android-19 | Intel x86 Atom, android-22 | Intel x86 Atom_64, android-23 | Intel x86 Atom_64, android-25 | Intel x86 Atom_64, android-29 | Intel x86 Atom_64
      Android NDK: 21.3.6528147
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_192 - /usr/bin/javac
    Python: 2.7.17 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.2 => 0.63.2
  npmGlobalPackages:
    *react-native*: Not Found
`

![image](https://user-images.githubusercontent.com/3503568/88940743-b4f61e80-d2ba-11ea-885c-b0a84c9cd16a.png)

**Comment by liliangzdh** [comment]
watch this , is the same for me ,run on android emulator API 19。

I found use Button can Reproduce the problem。
<img width="547" alt="AE525236-4337-4C61-A640-4470BA52A8E3" src="https://user-images.githubusercontent.com/16744633/89994606-f3c4a500-dcba-11ea-807b-ad6a1841acef.png">
<img width="615" alt="5D50D6AF97E0BA5D53F070E19939AE40" src="https://user-images.githubusercontent.com/16744633/89994616-f626ff00-dcba-11ea-9c95-2e935ec0f45e.png">
![1544EF32313FF7C64B720BF99BDAA473](https://user-images.githubusercontent.com/16744633/89994706-135bcd80-dcbb-11ea-9dc0-d7622fb521ea.png)

**Comment by enjeyw** [comment]
We're having this issue too. Seems like it could be related to whatever caused the ripple issue? https://github.com/facebook/react-native/issues/9870

**Comment by kutaisan** [comment]
I've reproduced the issue. Android versions between 4.1 and 4.4 are crashing

**Comment by roman-gula** [comment]
I have same issue - `TouchableNativeFeedback` does't work on Android 4.x simulator
react-native ver. 0.63.2

Just run 

```
> react-native init newApp
``` 

and add `TouchableNativeFeedback` to the code.

**Comment by Makerhack** [comment]
I'm also having this issue with RN 0.63 and TouchableNativeFeedback in android 4.3

**Comment by safaiyeh** [comment]
Thanks for the issue @euthribeiro, could you provide a repro that demonstrates the crash?

**Comment by roman-gula** [comment]
@safaiyeh try to add into `TouchableNativeFeedback` **View** component:

```
<TouchableNativeFeedback>
   <View>
      <Text>{"test"}</Text>
   </View>
</TouchableNativeFeedback>
```

Also if remove View from React native `Button` component error will gone.

**Comment by huyhai** [comment]
same on RN 0.63.2

**Comment by euthribeiro** [comment]
@safaiyeh Sorry, I restructured the entire project. I had a deadline and I needed to finish. But I still don't know the cause of the problem.

**Comment by mans17** [comment]
> @safaiyeh try to add into `TouchableNativeFeedback` **View** component:
> 
> ```
> <TouchableNativeFeedback>
>    <View>
>       <Text>{"test"}</Text>
>    </View>
> </TouchableNativeFeedback>
> ```
> 
> Also if remove View from React native `Button` component error will gone.

Maybe open New issue with this ?

**Comment by roman-gula** [comment]
@safaiyeh It is the same problem, I just clarified where to look. `Button` uses `TouchableNativeFeedback`

**Comment by omer-to** [comment]
Hi,
I am using React Native 0.63.2, I have the same issue, and this is my code:

`import React, { Component } from 'react'
import { Text, View, StyleSheet, TouchableOpacity, Dimensions, Pressable } from 'react-native'
import { SafeAreaView } from 'react-native-safe-area-context'
import { StackNavigationProp } from '@react-navigation/stack'
import { TopScreenParams } from '../../types/screens'
import { TextLink } from './TextLink'
import { grantUserAccessToOnboarding } from '../../../store/user-info/actions'
import { connect } from 'react-redux'
import { Dispatch } from 'redux'

interface ConcessionProps {
	navigation: StackNavigationProp<TopScreenParams, 'ScreenIntroduction'>
	grantUserAccessToOnboarding: typeof grantUserAccessToOnboarding

}

class Concession extends Component<ConcessionProps> {

	onPress(): void {
		const { grantUserAccessToOnboarding } = this.props
		grantUserAccessToOnboarding()
	}

	render() {
		return (
			<SafeAreaView style={ s.safeArea }>
				<View style={ s.container }>
					<Text style={ s.header }>
Lorem Header
					</Text>
					<Text style={ s.paragraph }>
						Lorem Ipsum<TextLink text='Lorem' />.
					</Text>
					<Text style={ s.paragraph }>
						Lorem Ipsum <TextLink text='Some Text' />
					</Text>
					<TouchableOpacity style={ s.touchable } onPress={ this.onPress.bind(this) }>
						<Text style={ s.confirmText }>
							I have read and accepted.
						</Text>
					</TouchableOpacity>
				</View>

			</SafeAreaView>
		)
	}
}


const { width, height } = Dimensions.get('window')
const s = StyleSheet.create({
	safeArea: { flex: 1, backgroundColor: '#1273EB', alignItems: 'center' },
	container: {
		flex: 1,
		width: '88%',
		alignItems: 'center',
		paddingVertical: height * 0.07,
	},
	header: {
		fontSize: 20,
		color: 'white',
		marginBottom: height * 0.07,
		fontWeight: 'bold'
	},
	paragraph: {
		color: 'white',
		textAlign: 'center',
		fontSize: 14,
		marginBottom: height * 0.12,
		lineHeight: 25
	},
	confirmText: {
		color: '#1273EB',
		fontSize: 20
	},
	touchable: {
		justifyContent: 'center',
		alignItems: 'center',
		width: '100%',
		height: width * 0.18,
		bottom: height * 0.08,
		backgroundColor: 'white',
		marginTop: 20,
		borderRadius: 7,
	}
})

const mapDispatchToProps = (dispatch: Dispatch) => {
	return {
		grantUserAccessToOnboarding: () => dispatch(grantUserAccessToOnboarding())
	}
}
export default connect(null, mapDispatchToProps)(Concession)
`

**Comment by douglasrcjames** [comment]
Bump for RN v0.63.2, Android 4.4.2, Device model LG-D415

**Comment by mans17** [comment]
> Maybe open New issue with this ?

https://github.com/facebook/react-native/issues/29983

**Comment by HugoGresse** [comment]
Quick patch-package for this specific issue as it will not be fixed for the React Native 0.63.4 anyway. 
[react-native+0.63.4.patch.zip](https://github.com/facebook/react-native/files/6297033/react-native%2B0.63.4.patch.zip)

**Comment by lonecruisader** [comment]
<TouchableWithoutFeedback> was causing the issue. I replaced it TochableOpacity with activeOpacity={0.9} as a workaround

**Comment by lonecruisader** [comment]
<touchableWithoutFeedback> was causing the issue for me. I replaced it TochableOpacity with activeOpacity={0.9} as a workaround
