### ISSUE TITLE
[iOS][ActionSheetIOS] Url is not shared when share from copy

### ISSUE THREAD

**Issue by omuomugin** [facebook/react-native#29425]
## Description
Copy  option in `ActionSheetIOS#showShareActionSheetWithOptions()` won't share url and only share message when passing options with `url` and `message` .

<img src=https://user-images.githubusercontent.com/16621708/87867413-7f525b00-c9c7-11ea-9273-9bb9e94abc97.png />

when passing options like below

```
{
   url: "https://some.url.com",
   message: "message for share"
}
```

and click "Copy", it will only copy "message for share" and not including url.

This occurs every time in simulator (iOS13.5 iPhone11) and in real device under some condition (not sure the exact condition).

As document of `ActionSheetIOS#showShareActionSheetWithOptions()` (https://reactnative.dev/docs/actionsheetios) says 

> Display the iOS share sheet. The options object should contain one or both of message and url and can additionally have a subject or excludedActivityTypes:

I thought this would be a some kind of bug.
If not I want some link to document that describes this behavior.

## React Native version:
`0.61.4` 

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. use `ActionSheetIOS#showShareActionSheetWithOptions()`
2. pass options with `message` and `url`
3. click copy option
4. only message is copied to clip board

## Expected Results
Copied text is expected to be message and with url. 

## Snack, code example, screenshot, or link to a repository:

```
ActionSheetIOS.showShareActionSheetWithOptions(
  options,
  error => {
    // do some error handling
  },
  (success, activityType) => {
    // do some success option
  },
);
```

**Comment by dhirajj14** [comment]
So I was working on this issue and found out that the url is only copied when it has http:// or https: protocol. And I tried to reproduce the same bug using steps give by @omuomugin  but it worked for me https://snack.expo.io/@dhirajj75/actionsheetios

**Comment by omuomugin** [comment]
@dhirajj14 
did it worked on simulator too?

> found out that the url is only copied when it has http:// or https: protocol

Could you tell me where this implementation is?

**Comment by gedeagas** [comment]
Nice catch @dhirajj14. 

@omuomugin see here for the implementation https://github.com/facebook/react-native/blob/c8d678abcf93fd3f6daf4bebfdf25937995c1fdf/React/CoreModules/RCTActionSheetManager.mm#L169 as per @dhirajj14 statement. if the URL is malformed ( doesn't have the proper scheme as per https://tools.ietf.org/html/rfc2396 ) it will return nill thus the if check below would not passed. https://developer.apple.com/documentation/foundation/nsurl/1413146-init

**Comment by safaiyeh** [comment]
Appreciate the investigation and PR to the docs @gedeagas!

**Comment by omuomugin** [comment]
Thanks for resources and adding docs.

Really helped me!

**Comment by omuomugin** [comment]
Closing this issue.
