### ISSUE TITLE
Text font not change when system font changed(0.61,android)

### ISSUE THREAD

**Issue by goldrod** [facebook/react-native#29426]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description

Mobile system font size changes, app font is fixed，The test phone: 
1--Xiaomi MIUI 10.2 Redmi Pro
2--OPPO R9S ColorOS v3.0

## React Native version:
"react": "16.11.0",
"react-native": "0.61.0",
compileSdkVersion     29
buildToolsVersion      '29.0.3'
targetSdkVersion       29

## Snack, code example, screenshot, or link to a repository:
![3281595147496_ pic](https://user-images.githubusercontent.com/8717644/87871820-53929d80-c9e6-11ea-8c70-710c467d56ec.jpg)
![137251595151657_ pic](https://user-images.githubusercontent.com/8717644/87871918-111d9080-c9e7-11ea-8514-50bfc72393f2.jpg)

**Comment by safaiyeh** [comment]
Hi @goldrod could you test this on the latest React Native version and provide a repro with the issue either as a Snack or repo.

Does this issue only occur with the devices you listened or generally with Android devices?
