### ISSUE TITLE
Alert.alert title and button text are not visible on Android if the device is in dark mode

### ISSUE THREAD

**Issue by SMJ93** [facebook/react-native#29427]
## Description

We've just updated to 0.63.1 and the `Alert.alert` title and button text are not visible on Android if the device is in dark mode (both emulators and devices):

| Dark mode | Light mode |
|---|---|
| ![Screenshot_1595167045](https://user-images.githubusercontent.com/2145641/87876533-892c8c00-c9d0-11ea-8b21-ea99fa26a519.png) | ![Screenshot_1595167132](https://user-images.githubusercontent.com/2145641/87876538-96497b00-c9d0-11ea-9334-db7b540e1ded.png) |

## React Native version:
```
System:
    OS: macOS 10.15.5
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 197.20 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.9.1 - ~/.nvm/versions/node/v12.9.1/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v12.9.1/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.9.1/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_172 - /usr/bin/javac
    Python: 2.7.15 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.1 => 0.63.1
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Add the `Alert.alert` snippet from the [docs](https://reactnative.dev/docs/alert) to your code 
2. Trigger this alert on Android device in dark mode (occurs on both emulator and real device).

## Expected Results

I would expect to see the title and button text on a dark Alert.

## Snack, code example, screenshot, or link to a repository:

This is using the example snippet from the [docs](https://reactnative.dev/docs/alert):

```
    Alert.alert(
      "Alert Title",
      "My Alert Msg",
      [
        {
          text: "Cancel",
          onPress: () => console.log("Cancel Pressed"),
          style: "cancel"
        },
        { text: "OK", onPress: () => console.log("OK Pressed") }
      ],
      { cancelable: false }
    );
```

**Comment by SMJ93** [comment]
Ignore, local config was causing it.

We set the Android text colour to `#ffffff` if in dark mode using `values-night`.

There is still a bug as the Alert should be dark, but this has already been opened [here](https://github.com/facebook/react-native/issues/28502)

**Comment by hogrid** [comment]
In the Android folder go to **app > src > main > res > values > style.xml** and change or comment on the item “android: textColor”. This worked for me!
