### ISSUE TITLE
RN 63 Upgrade : Failed to connect to debugger!

### ISSUE THREAD

**Issue by shivaping** [facebook/react-native#29431]
Post upgrading to React Native 63, we are seeing the below error

## Description
Failed to connect to debugger!

Timeout while connecting to remote debugger

## React Native version:
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
    Memory: 13.89 GB / 31.81 GB
  Binaries:
    Node: 12.18.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.17.3 - D:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.5 - ~\AppData\Roaming\npm\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 26, 28, 29, 30
      Build Tools: 25.0.1, 26.0.1, 26.0.3, 28.0.3, 29.0.2, 30.0.0
      System Images: android-28 | Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6514223
  Languages:
    Java: 1.8.0_221
    Python: 3.8.3
  npmPackages:
    @react-native-community/cli: ^4.5.0 => 4.10.1
    react: 16.13.1 => 16.13.1
    react-native: 0.63.1 => 0.63.1

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.npx react-native run-android
2.Error is thrown in debugging mode 

## Expected Results
We should be able to debug the application in debug mode similar to RN 62
![image](https://user-images.githubusercontent.com/13598222/87908503-1e3c8d00-ca84-11ea-8770-956170a512af.png)

**Comment by karthikkoppa** [comment]
Even this issue is causing in IOS as well RN-0.63.

**Comment by divinghero** [comment]
same here, it only appear when android debug, how to fix it?

**Comment by divinghero** [comment]
In my case，I am solved it by doing this：find file at path android/build.gradle，delete code `resolutionStrategy.force 'com.squareup.okio:okio:1.13.0'` under allprojects -> repositories -> configurations.all
