### ISSUE TITLE
Metro Bundler won't distribute files to devices, but works on simulator

### ISSUE THREAD

**Issue by exotexot** [facebook/react-native#29433]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
While distributing my React Native project to my device using react-native run-ios --device, the application will fail to load. Most often this results in the "blank screen" bug and causes the application to crash. This does not only affect my production app, but also newly created apps with react-native init. I've tried different wifi networks to see if theres a problem, but the problem persisted. I've clear all the caches that I'm aware of, including removing node_modules folder and reinstalling several times. 

One attempt reveald the React native Debug Menu where I could configure the Metro Bundler. I've lauched the bundler using react-native start --port 8084 --reset-cache and checked wether the Bundler is accessible over the network. On my computer, in my browser, I've entered localhost:8084 and yes, I've get a message from the Metro Bundler. When entering the same address on my iPad and iPhone, I only see a loading bar which seems stuck and never fully loads.

![IMG_0264](https://user-images.githubusercontent.com/10153413/87925183-34e0e500-ca80-11ea-98d7-8bf768d46cf0.PNG)

Important mention: When building through Xcode directly, in Release Mode there is no issue at all, in Debug mode is quite often succeeds in building but the inital load time, after the app has been installed on the device, upon the first opening is quite execessive. No comparison to my previous experiences.

I have no idea what changes, a couple of days ago this issue wasnt there. I'm sure I didnt install any new critical packages. I'm just blown away by this bug...

## React Native version:
System:
    OS: macOS 10.15.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 1.08 GB / 32.00 GB
    Shell: 3.0.2 - /usr/local/bin/fish
  Binaries:
    Node: 13.8.0 - /usr/local/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.14.6 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_242 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: ^4.10.1 => 4.10.1
    react: 16.11.0 => 16.11.0
    react-native: ^0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. react-native init <name>
2. react-native run-ios --device 

## Expected Results
React Native App is expected to run on the plugged in device.

**Comment by exotexot** [comment]
This issue affects iDevices only. When running on Android, it still works. However, what scares me a bit, is that this also affects newly created project with react-native init... Mentro Bundler just won't connect with the device ... any ideas how I could debug this further?

**Comment by exotexot** [comment]
I even downgraded Xcode from 11.6 to 11.5, because this is the only indication that I have, that the problems began when I updated Xcode.

**Comment by pavelpashkovsky** [comment]
>I even downgraded Xcode
did it help? I have the same issue on 11.5

**Comment by exotexot** [comment]
Nope. But I could solve my problem by basically reversing all the steps mentioned here: https://reactnative.dev/docs/environment-setup

For my projects I'm using React Native CLI Quickstart (not Expo!) and i uninstalled node, watchman, and ios-deploy and reinstalled them through brew again. I also uninstalled cocoapods.

I don't know what caused my problem, but something fixed it.

**Comment by rananajam1** [comment]
Kindly review your .xcscheme file and check if the buildConfigurations are set to "Debug". If thats the case set the buildConfigurations to "Release".

**NOTE: In my case the Ad-hoc ipa was crashing as it was dependant on the bundler**

**Comment by derek-schultz** [comment]
Thanks @exotexot, uninstalling and reinstalling those three things worked for me and I'm pretty sure watchman was the issue.
