### ISSUE TITLE
[android] app development is completed, how to generate APK file? 

### ISSUE THREAD

**Issue by WG-Com** [facebook/react-native#2943]
app development is completed, how to generate APK file? i know nothing about that....

**Comment by mkonicek** [comment]
Good point! This is a known missing part in the documentation, we'll be adding it shortly.
For now please see this answer: http://stackoverflow.com/questions/32629379/how-to-build-react-native-android-app-for-production

**Comment by WG-Com** [comment]
```sh
$ cd your_project_dir
$ npm start  # start the packager if not started already
$ curl "http://localhost:8081/index.android.bundle?platform=android?dev=false" -o "android/app/src/main/assets/index.android.bundle"
```

I've done this before, but how to generate the APK file, please write it on your upcoming document, thank you

**Comment by yinzSE** [comment]
i have same question.
it's trouble me long time.

i don't know "index.android.bundle" how to use.
maybe i should to learn something about android.
