### ISSUE TITLE
[0.63.1] [TouchableOpacity] invalid children Text color change

### ISSUE THREAD

**Issue by likern** [facebook/react-native#29436]
## Description
After upgrading to `0.63.1` from `0.62.2` I see **invalid color changes** for `Text` component inside `TouchableOpacity`.
In `0.62.2` color changed from when pressed (with touchable opacity applied) to desired color.
In `0.63.3` color first changes to new color (with touchable opacity applied) and only then to desired color (without touchable opacity)

## React Native version:
```
System:
    OS: Linux 5.7 Fedora 32 (Workstation Edition) 32 (Workstation Edition)
    CPU: (8) x64 Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
    Memory: 1.22 GB / 15.56 GB
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.0.0 - ~/.nvm/versions/node/v14.0.0/bin/node
    Yarn: 1.22.0 - ~/.local/opt/node-v10.19.0-linux-x64/bin/yarn
    npm: 6.14.5 - ~/Breeffy/Feeve/node_modules/.bin/npm
    Watchman: 4.9.0 - /usr/bin/watchman
  SDKs:
    Android SDK:
      API Levels: 23, 25, 28, 29
      Build Tools: 25.0.3, 27.0.3, 28.0.3, 29.0.2, 29.0.3
      System Images: android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
      Android NDK: 21.0.6113669
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 1.8.0_252 - /usr/bin/javac
    Python: 3.8.3 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.1 => 0.63.1 
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce

1. Create component with `Text` inside `TouchableOpacity`
2. See the bug

```ts
const FilterButton = ({ style }: FilterButtonProps) => {
  const [isSelected, setSelected] = useState(false);
  const color = useMemo(() => {
    return isSelected ? 'rgba(45, 154, 252, 1)' : 'rgba(68, 82, 95, 0.4)';
  }, [isSelected]);
  const onPressCallback = useCallback(() => {
    setSelected((prev) => !prev);
  }, [setSelected]);
  return (
    <TouchableOpacity
      css={`
        height: 100%;
        flex-grow: 1;
        flex-direction: row;
        justify-content: center;
        align-items: center;
      `}
      style={style}
      onPress={onPressCallback}
    >
      <Text
        css={`
          font-family: Gilroy-SemiBold;
          font-size: 17px;
          line-height: 20.4px;
          text-align: left;
          text-align-vertical: center;
          margin-left: 4px;
        `}
        style={{ color }}
      >
        Button
      </Text>
    </TouchableOpacity>
  );
};
```

## Expected Results
Correct color change for `Text`

## Screenshots

<table>
  <tr>
    <td>React Native 0.63.1</td>
     <td>React Native 0.62.2</td>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/842306/87972639-ef4c0880-cacf-11ea-9daa-4c179cbc920a.gif" height=480></td>
    <td><img src="https://user-images.githubusercontent.com/842306/87973488-430b2180-cad1-11ea-9fe3-3f642ac9b83f.gif" height=480></td>
  </tr>
 </table>

**Comment by tuanlvntq** [comment]
the same issues with touchable library, ripple affect gone

**Comment by fabriziobertoglio1987** [comment]
I wanted to ask if you still experience this issue. 
I'm planning to do 1-2 months of opensource and I'm preparing a list of tasks.

I have been contributing to facebook/react-native for 4 years and I specialize on the Text/TextInput components.

Thanks a lot

**Comment by likern** [comment]
> I wanted to ask if you still experience this issue. I'm planning to do 1-2 months of opensource and I'm preparing a list of tasks.
> 
> I have been contributing to facebook/react-native for 4 years and I specialize on the Text/TextInput components.
> 
> Thanks a lot

I can't test, no longer use React Native.

**Comment by fabriziobertoglio1987** [comment]
why did you stop using react-native? thanks for the reply
