### ISSUE TITLE
Android: Async Storage is not accesible, when a background task is being handled in index.android.js

### ISSUE THREAD

**Issue by ravichandran18390** [facebook/react-native#29440]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Android: Async Storage is not accesible, when a background task is being handled in index.android.js
note* - no issue on messaging().setBackgroundMessageHandler, it brings out the remote message

snippet:

const retrieveEasDataMessage = async () => {
	try {
		const accName = await AsyncStorage.getItem("accountName");                
		const remoteMessage = await AsyncStorage.getItem(`${dataMsgKey}-${accName}`);
		if (remoteMessage !== null) {
                     console.log(`launch retrieveEasDataMessage remoteMessage : ${JSON.stringify(remoteMessage)}`);
		}
	} catch (err) {
              console.log(`launch retrieveEasDataMessage err : ${JSON.stringify(err)}`);
	}
};

//Quit state handler, once the app is quit, if the app receives an firebase data-message, below listener will be handling that
messaging().setBackgroundMessageHandler(async (remoteMessage) => {
	try {
		if (remoteMessage && remoteMessage !== null) {
			await retrieveEasDataMessage();
			console.log(`setBackgroundMessageHandler remoteMessage : ${JSON.stringify(remoteMessage)}`);
			await storeEasDataMessage(remoteMessage);
		}
	} catch (error) {
                console.log(`android setBackgroundMessageHandler error : ${JSON.stringify(error)}`);
	}
}) : () => {/**/ }

======

The above code will be executed when a data message is received, once the app is killed / quit state, there
const accName = await AsyncStorage.getItem("accountName");      
"accountName" is already set while foreground & background message handling but when quit state handling if we access it, this accName is always null

## React Native version:
Run `react-native info` in your terminal and copy the results here.

react-native info

warn Your project is using deprecated "rnpm" config that will stop working from next release. Please use a "react-native.config.js" file to configure the React Native CLI. Migration guide: https://github.com/react-native-community/cli/blob/master/docs/configuration.md
warn The following packages use deprecated "rnpm" config that will stop working from next release:

react-native-extra-dimensions-android: https://npmjs.com/package/react-native-extra-dimensions-android
Please notify their maintainers about it. You can find more details at https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide.
info Fetching system and libraries information...

System:
OS: macOS Mojave 10.14.5
CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
Memory: 34.23 MB / 16.00 GB
Shell: 3.2.57 - /bin/sh

Binaries:
Node: 10.18.0 - /usr/local/opt/node@10/bin/node
Yarn: 1.16.0 - /usr/local/bin/yarn
npm: 6.13.4 - /usr/local/opt/node@10/bin/npm
Watchman: 4.9.0 - /usr/local/bin/watchman

SDKs:

iOS SDK:
Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1

Android SDK:
API Levels: 23, 24, 25, 26, 27, 28
Build Tools: 25.0.0, 25.0.1, 25.0.2, 26.0.1, 26.0.2, 27.0.3, 28.0.0, 28.0.3, 29.0.2
System Images: android-23 | Intel x86 Atom_64, android-23 | Google APIs ARM EABI v7a, android-23 | Google APIs Intel x86 Atom_64, android-26 | Android TV Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom_64, android-26 | Google Play Intel x86 Atom, android-28 | Android TV Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64

IDEs:
Android Studio: 3.5 AI-191.8026.42.35.6010548
Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild

npmPackages:
react: 16.9.0 => 16.9.0
react-native: 0.61.1 => 0.61.1

npmGlobalPackages:
react-native-cli: 2.0.1
react-native-log-ios: 1.5.0

## Expected Results
React Native's AsyncStorage should be an accessible in the above scenario
Please share your idea to fix this
thanks folks

**Comment by safaiyeh** [comment]
Hi @ravichandran18390 this would be more appropriate for the async storage repo. Could you file an issue over at https://github.com/react-native-community/async-storage?

I'll close this for now. If this is an issue with React Native core, feel free to discuss! Thank you
