### ISSUE TITLE
IOS real machine cannot be debugged and reloaded

### ISSUE THREAD

**Issue by lilicoder** [facebook/react-native#29444]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Connect IOS real machine, Xcode run app, enter app, shake mobile phone after entering app, click reload or debug, there is no response, the mobile phone crashes, and the following error will appear later
<img width="224" alt="WX20200721-200909@2x" src="https://user-images.githubusercontent.com/24731304/88053258-12d58880-cb8e-11ea-930f-e3edf37fa1bf.png">

## React Native version:
0.59.9

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.Connect IOS real machine
2. Xcode run app, enter app
3.click reload or debug
4. the mobile phone crashes
## Expected Results
Describe what you expected to happen.
debug and reload like andriod real machine

## Snack, code example, screenshot, or link to a repository:
new a react native project

## version info
<img width="670" alt="WX20200722-142926@2x" src="https://user-images.githubusercontent.com/24731304/88142581-5aa8ee00-cc28-11ea-9848-e695051dc605.png">

**Comment by lilicoder** [comment]
<img width="224" alt="WX20200721-200909@2x" src="https://user-images.githubusercontent.com/24731304/88053641-b45cda00-cb8e-11ea-83f4-e15ca0530116.png">

**Comment by lilicoder** [comment]
<img width="670" alt="WX20200722-142926@2x" src="https://user-images.githubusercontent.com/24731304/88142638-6bf1fa80-cc28-11ea-8d5a-7413078d7f37.png">

**Comment by lilicoder** [comment]
<img width="670" alt="WX20200722-142926@2x" src="https://user-images.githubusercontent.com/24731304/88142682-8330e800-cc28-11ea-9965-486fa077935e.png">

**Comment by pavelpashkovsky** [comment]
same here, my system report:
System:
    OS: macOS 10.15.5
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 402.02 MB / 16.00 GB
    Shell: 3.1.0 - /usr/local/bin/fish
  Binaries:
    Node: 12.16.2 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild

**Comment by hashimalikhan-123** [comment]
I have same issue please suggest me the better solution.
Thanks.
