### ISSUE TITLE
TextInput hitSlop on Android

### ISSUE THREAD

**Issue by AdrianBordeianu** [facebook/react-native#29445]
What I want to do is to implement an input with a floating label and things work perfectly fine on iOS, but on Android it does not recognize the tapping area outside the actual input, which leads to bad UX.

## Description
What happens is that I want to have a design in which is a main container with a border and the floating label and the input inside. Considering that there's a border to my input, it means that the tapping area should be everywhere inside that border, but my container has two elements so I can only focus the input when tapping it. 

This **only applies to Android**, **on iOS hitSlop property works perfectly fine and the tapping area is all accross the container.**

In my example, the border of the input is only for the purpose of understanding the problem.

## React Native version:
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      Android NDK: 18.0.5002713
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.12.0 => 16.12.0 
    react-native: 0.61.5 => 0.61.5 

## Expected Results
hitSlop property should work on Android as well.

## Snack, code example, screenshot, or link to a repository:
https://snack.expo.io/@adrian.bordeianu/13c604

<img width="313" alt="Screenshot 2020-07-21 at 14 54 21" src="https://user-images.githubusercontent.com/37770519/88052719-5666cd00-cb63-11ea-86c2-f035d72353c6.png">

**Comment by chrisglein** [comment]
`hitSlop` has migrated from [here](https://reactnative.dev/docs/0.61/touchablewithoutfeedback#hitslop) to [here](https://reactnative.dev/docs/pressable#hitslop) on `pressable`. Not sure if the behavior has changed with the respect to platform compatibility.

**Comment by AdrianBordeianu** [comment]
I upgraded the version to react-native 0.63.2 and the problem still persists.
  react: 16.13.1 => 16.13.1 
  react-native: 0.63.2 => 0.63.2

**Comment by AdrianBordeianu** [comment]
Issue fixed. 

Used https://www.npmjs.com/package/react-native-floating-label-input

It was an zIndex problem and the usage of Animated API.
