### ISSUE TITLE
 How to map within this array of json objects and I want to display the image,title,quantity on the screen

### ISSUE THREAD

**Issue by satyadaraviteja** [facebook/react-native#29449]
import React from 'react';
import {StyleSheet,Text,View,TouchableWithoutFeedback,TouchableOpacity,ScrollView,SafeAreaView,Image,Dimensions} from 'react-native';
import { createBottomTabNavigator } from 'react-navigation-tabs';
import {createAppContainer} from 'react-navigation'
import Cart from '../tabnavigation/Cart'
import Market from '../tabnavigation/Market'
import Faq from '../tabnavigation/Faq'
import Account from '../tabnavigation/Account'
// import Category from '../components/Home/Category'

class Homescreen extends React.Component{
    constructor(props){
        super(props)
        this.state = {
            
             "categories": [
                {
                    "Leafy Greens":[
                        {
                            "productId":"1",
                            "categoryName":"Leafy Greens",
                            "title":"Spinach",
                            "quantity":"200 grams",
                            "image":'https://i.pinimg.com/236x/df/34/c7/df34c77539878cfbd00511bdcba5e58e.jpg'
                        },
                        {
                            "productId":"2",
                            "categoryName":"Leafy Greens",
                            "title":"Bok Choy",
                            "quantity":"200 grams",
                            'image':'https://i.pinimg.com/564x/b1/6f/ec/b16fecbab268ab15dd39d2152ef89f6e.jpg'
                        },
                        {
                            "productId":"3",
                            "categoryName":"Leafy Greens",
                            "title":"Brocoli",
                            "quantity":"200 grams",
                            'image':'https://i.pinimg.com/236x/c7/d1/3b/c7d13b3070921fb5c70e308d11461b8c.jpg'
                        }
                        
                    ]
                },
                {
                    "Micro Greens":[
                         
                            {
                                "productId":"4",
                                "categoryName":"Micro Greens",
                                "title":"Spinach",
                                "quantity":"100 grams",
                                'image':'https://i.pinimg.com/564x/bb/88/6d/bb886d5ddeb5a63c98e6877b57e6300b.jpg'
                            },
                            {
                                "productId":"5",
                                "categoryName":"Micro Greens",
                                "title":"Bok Choy",
                                "quantity":"100 grams",
                                'image':'https://i.pinimg.com/236x/88/98/a2/8898a2aabf90d3a16bac054651e082cc.jpg'
                            },
                            {
                                "productId":"6",
                                "categoryName":"Micro Greens",
                                "title":"Brocoli",
                                "quantity":"100 grams",
                                'image':'https://i.pinimg.com/564x/2b/41/0c/2b410c13c79c2c366bb0362a52e5a2e2.jpg' 
                            } 
                        
                    ]
                }

              ]
             
              
        }
        
      }

    
     
    
 render(){
     React.Children.toArray(
        this.state.categories.map((item,i)=>
       <Text key={i} value={item}>
            {item}
            
       </Text>)
   
   )

**Comment by ajd01** [comment]
Reading this could help you resolve your doubts.
https://reactjs.org/docs/lists-and-keys.html
