### ISSUE TITLE
[0.63.0][IOS] Modal onDismiss no longer working on IOS

### ISSUE THREAD

**Issue by raymochi** [facebook/react-native#29455]
## Description
On 0.62.2 onDismiss functions were called on modals being closed. After upgrading to 0.63.0, onDimiss functions are no longer called. This was working fine before upgrading from 62.2 to 63.

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Import { Modal } from react-native
2. Add modal to render with a function passed into onDismiss property

## Expected Results
onDimiss function should be called

**Comment by chrisglein** [comment]
Realize that 0.63 is new enough that you can't repro in a Snack, but it would help if you pointed to a Snack that shows this working pre-0.63.

**Comment by andres-torres-marroquin** [comment]
@chrisglein I made an example using Expo SDK 38.0.0, which shows that the behavior is correct in RN 0.62 https://snack.expo.io/@srpoder/excited-cheese

Also the RN Documentation specifies that onDismiss should be available on RN 0.63 https://reactnative.dev/docs/modal#ondismiss

**Comment by wincjh** [comment]
+1 onDismiss not called and not open second modal when i have closed fist modal and open second modal

**Comment by diolegend** [comment]
Same issue, i upgraded to 0.63 and now when i set the modal visible to false, it don't invoke onDismiss, but when i close the modal of react native navigation, it surprisingly invoke onDismiss, but i don't need when i close the modal of react native navigation. But i need as usual, invoked when i set to false the visible of react native modal.

Steps:
1. Navigation.showModal https://wix.github.io/react-native-navigation/api/modal/#showmodal
2. showModal react native
3. closeModal react native (set to false visible)
4. No invoke onDismiss
5. Navigation.dismissAllModals()
6. Surprisingly run onDismiss of react native modal

**Comment by kkoudev** [comment]
This fix in RN 0.62.1 doesn't seem to be in RN 0.63.
Is this the cause?
https://github.com/facebook/react-native/commit/27a3248a3b37410b5ee6dda421ae00fa485b525c

**Comment by bitcrumb** [comment]
We're seeing the same behavior. The onDismiss callback is never called when hiding the modal. I can also confirm the behavior as explained by @diolegend.

**Comment by imnotjames** [comment]
In case it helps - I cannot seem to get `onDismiss` to ever fire on the docs example expo snack using Android either.

**Comment by MichaelKim39** [comment]
Both onDismiss and onHideModal not working for me, tried using the expo snack and also did not work

**Comment by MichaelKim39** [comment]
Workaround is to use onSwipeComplete and onBackdropPress and add callbacks followed by toggle function

**Comment by mi-mazouz** [comment]
still have this issue with react native 0.63.3

**Comment by retyui** [comment]
Seem fix was added in 0.63.4 https://github.com/react-native-community/releases/issues/212#issuecomment-729651744

**Comment by ramakula** [comment]
I have upgraded to 0.63.4 and it is still not fired on iOS :(

**Comment by ramakula** [comment]
@retyui It is not part of 0.63.4 FYI..

<img width="634" alt="Screen Shot 2021-02-09 at 1 51 39 PM" src="https://user-images.githubusercontent.com/2745769/107433335-09861c00-6ade-11eb-813a-c64c4b48c93d.png">

**Comment by retyui** [comment]
But the issue already closed? but fix not released yet

**Comment by ramakula** [comment]
Yeah so weird @retyui . What I hear is this won't be backported to 63 because of significant changes happening in 64. We will have to wait to 64

**Comment by Harshitha91** [comment]
Any update about the issue?

**Comment by AlexandreHauber** [comment]
Still facing this issue RN 0.64.1

**Comment by afonsopbarros** [comment]
onDismiss was working on 0.63.4, not working on 0.64.2 now.
