### ISSUE TITLE
Invariant Violation:  _registerComponent(...): Target container is not a DOM element

### ISSUE THREAD

**Issue by achang28** [facebook/react-native#2945]
Right after installing JEST (```npm install jest-cli```), and then running my application, I get the following error.  Even though I uninstalled JEST cli, the error persists.  Switching to previous branches of my application doesn't help, either.  I didn't touch anything else after install JEST.  By any chance has anyone ever come across this issue?

I am currently running React Native 0.9.0...

<img width="600" alt="screen shot 2015-09-22 at 12 43 39 pm" src="https://cloud.githubusercontent.com/assets/3760499/10029701/46a46c2e-6128-11e5-9c8a-dd70f27203ee.png">

**Comment by achang28** [comment]
I upgraded from 0.9.0 to 0.11.0...

**Comment by Sunify** [comment]
Have same error with 0.15.0 and 0.16.0

**Comment by Sunify** [comment]
My fault, i am use react-redux instead of react-redux/native

**Comment by pewh** [comment]
Hi @Sunify 
How can you use react-redux in React 0.16?
As far as we know, React 0.16 use Babel 6. Latest version of react-redux (v4.x.x) doesn't contain `react-redux/native`. Only version 3.x.x contains `react-redux/native`, which is not compatible with Babel 6.
CMIIW, thanks.

**Comment by Sunify** [comment]
@pewh react-redux@3.1.1 and redux@3.0.5 is compatible with babel 6

**Comment by pewh** [comment]
@Sunify Oops, sorry for my fault. I've tested it & you right.

**Comment by ilansas** [comment]
I have this error too on 0.15

**Comment by edo1493** [comment]
Same here for 0.15.0 and 0.16.0.
