### ISSUE TITLE
KeyboardAvoidingView behaves differently in some circumstances

### ISSUE THREAD

**Issue by cinatic** [facebook/react-native#29467]
Hi,

i am using KeyboardAvoidingView inside a SafeView in a StackView of react-navigation-stack. While it works great on android, in iOS i notice differences between several iOS devices (iphone 11 & SE (1. gen)).

screen is structured like this:

```
<SaveAreaView>
    <KeyboardAvoidingView
        behavior={Platform.OS === 'ios' ? 'padding' : null}
        keyboardVerticalOffset={Header.HEIGHT}
    >
       <TextInput/>
    </KeyboardAvoidingView
<SaveAreaView>
```

I figured out that the following changes in KeyboardAvoidingView would fix my issue, why has this been reverted and is there maybe another workaround?

https://github.com/facebook/react-native/commit/a37e45a57ef508bf9b413b64d1324294cec5e478#diff-68fc16c983e5047f1dc94c5de9622326

## React Native version:
0.62.2

## Expected Results
same padding / distances cross different devices

![image](https://user-images.githubusercontent.com/2721787/88194907-a87d2080-cc3f-11ea-91ae-16d57006fd8e.png)

**Comment by chrisglein** [comment]
Differences between Android and iOS are expected, according to the docs: https://reactnative.dev/docs/keyboardavoidingview#behavior

> Android and iOS both interact with this prop differently. On both iOS and Android, setting `behavior` is recommended.

So, while I don't know the history of that, sounds like this is expected?
Pinging @TheSavior as he was on the PR for the commit you identified.

**Comment by immortalx** [comment]
This difference in padding happens on iOS < 13.

**Comment by cinatic** [comment]
@chrisglein 
Thanks for your effort. I mentioned that android is fine and yes the difference between iOS and android is a known and documented thing. Here the difference is visible when comparing **iPhone 11** with **iPhone SE** both on **iOS 13**

**Comment by immortalx** [comment]
@cinatic I'm testing on the simulators, there's two iPhone SE's. One is first generation with iOS 12.4 and the other is 2nd generation with iOS 13.6.
The padding issues in my case only happens on simulators with iOS 12.4 and also a real iPhone 5s with iOS 12.4.

**Comment by SimonHausdorf** [comment]
do you have autoFocus enabled on input? If yes, what is happening if you delay it by let's say 500ms with a timeout? Does the problem still occur?

**Comment by immortalx** [comment]
@SimonHausdorf  No. Turning on autoFocus would lead into another set of padding issues in the past, so it's always off for me.

**Comment by SimonHausdorf** [comment]
maybe to the issue I have in #29499 ?

**Comment by NguyenQuocAnDev27** [comment]
So my solution is not use "KeyboardAvoidingView". Instead, i get KeyBoardHeight and set position to my CustomInputView when Keyboard -> "show hide the bottom one and show the absolute position one " or "you can set position to move CustomInputView".

Typescript:
```
  const [keyboardHeight, setKeyboardHeight] = useState(0);

  useEffect(() => {
    function onKeyboardDidShow(e: KeyboardEvent) {
      setKeyboardHeight(e.endCoordinates.height);
    }

    function onKeyboardDidHide() {
      setKeyboardHeight(0);
    }

    const showSubscription = Keyboard.addListener('keyboardDidShow', onKeyboardDidShow);
    const hideSubscription = Keyboard.addListener('keyboardDidHide', onKeyboardDidHide);
    return () => {
      showSubscription.remove();
      hideSubscription.remove();
    };
  }, []);
```

Hope it helpful to you.
