### ISSUE TITLE
Could not get BatchedBridge, make sure your bundle is packaged correctly

### ISSUE THREAD

**Issue by RuthlessPotato** [facebook/react-native#29460]
We are now using react-native version 0.62 when we ran this app under dev model. The virtual environment of the mobile can run this app successfully. However, if when we ran this app under released model, the app will flash back. By using adb to check the log, which is as followings:

07-20 09:04:55.728 28992 29016 E AndroidRuntime: FATAL EXCEPTION: mqt_js
07-20 09:04:55.728 28992 29016 E AndroidRuntime: Process: com.github, PID: 28992
07-20 09:04:55.728 28992 29016 E AndroidRuntime: com.facebook.jni.CppException: Could not get BatchedBridge, make sure your bundle is packaged correctly
07-20 09:04:55.728 28992 29016 E AndroidRuntime:        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
07-20 09:04:55.728 28992 29016 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:883)
07-20 09:04:55.728 28992 29016 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:100)
07-20 09:04:55.728 28992 29016 E AndroidRuntime:        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
07-20 09:04:55.728 28992 29016 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)
07-20 09:04:55.728 28992 29016 E AndroidRuntime:        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
07-20 09:04:55.728 28992 29016 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:919)

**Comment by RuthlessPotato** [comment]
> ⚠️	Missing Environment Information
> ℹ️	Your issue may be missing information about your development environment. You can obtain the missing information by running `react-native info` in a console.

System:
    OS: Windows 10 10.0.17134
    CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
    Memory: 4.68 GB / 15.86 GB
  Binaries:
    Node: 10.20.1 - D:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.5 - D:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 27, 28, 29
      Build Tools: 28.0.3
      System Images: android-25 | Google APIs ARM 64 v8a, android-25 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-Q | Google APIs Intel x86 Atom
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
  npmGlobalPackages:
    react-native-cli: 2.0.1

**Comment by JB-CHAUVIN** [comment]
Same issue goes for me. Android release build crashes when using react-native 0.62.

**Comment by zentrails** [comment]
This seems to be related to `Hermes`. If I disable it, this error goes away. Unfortunately, I have no idea why.

Does disabling Hermes work for you also @RuthlessPotato ?

**Comment by abhaynpai** [comment]
I was facing a similar issue with `0.63.2`. Then I tried upgrading to `0.64.0`. Still no luck in resolving this issue 😢

**Comment by kyle-ssg** [comment]
Anyone find any info on this? I've recently hit this updating to 0.64, I cant disable hermes due to react-native-reanimated requiring it..

**Comment by mansdahlstrom1** [comment]
Started getting this after updating to RN `0.65.1`: I've disabled hermes for now to be able to build. Any updates on why this is happening?

**Comment by abram** [comment]
My app has the same issue running on iOS. After upgrading to 0.65.1, I decided to try Hermes. It works fine in dev mode (and does seem to improve performance), but I get the above error when trying to run a release build. I disabled Hermes and the problem went away, so this isn't blocking me for now, but I would like to be able to use Hermes in production.

**Comment by RuthlessPotato** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by hokimtam** [comment]
any idea ? bug is opening.

**Comment by RuthlessPotato** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by samih-sghier** [comment]
same here

**Comment by RuthlessPotato** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by KarlaCarvajal** [comment]
Hi there, I have the same issue did you find any solution for this?

```
FATAL EXCEPTION: mqt_js
                                                                                                    Process: , PID: 23087
                                                                                                    com.facebook.jni.CppException: Could not get BatchedBridge, make sure your bundle is packaged correctly
                                                                                                    	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:873)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
                                                                                                    	at android.os.Looper.loop(Looper.java:214)
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
                                                                                                    	at java.lang.Thread.run(Thread.java:764)
```

**Comment by RuthlessPotato** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by realabbas** [comment]
This issue is due to `react-native-reanimated` package, update to latest `2.14.0`

Run the app in RELEASE mode on XCODE to test

**Comment by RuthlessPotato** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by kelset** [comment]
it looks like the only reason this issue has been open so far is because of an auto-reply from the original author:

> This is the auto-recovery of your QQ mail box.
> I'm sorry, I've been on vacation recently, and I'm sorry for the inconvenience. After the end of the holiday period, I will be happy to return.

(google translated)

Since there's no clear repro, nor it looks like any actual leads on what this might be related, I'll close this one off. If you are affected by this specific problem, please open a new issue, make sure you are on a supported version, follow the template and provide a repro.
