### ISSUE TITLE
Cannot update a component from inside the function body off a different component

### ISSUE THREAD

**Issue by GanongLS** [facebook/react-native#29464]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

i'm doing like this tutorial exactly same 

https://www.youtube.com/watch?v=uLHFPt9B2Os
the differrence maybe only on version of react native i'm doing with v 0.63.0. 

and i get warning 

![Screenshot_20200722-132649](https://user-images.githubusercontent.com/39286664/88142138-2b41b380-cc1f-11ea-89db-e9281a1d5358.jpg)

## Description
it's clear

## React Native version:
v 0.63.0

## Steps To Reproduce
1. just do like the tutorial do

## Expected Results
CRUD happend like in the youtube. 

## Snack, code example, screenshot, or link to a repository:
not doing snack.

**Comment by franznkemaka** [comment]
Hello @GanongLS, could you send the link to the tutorial? The screenshot is unfortunately not enough as it looks good. I guess it is how you use **pressHandler** which causes the issue. 
I found this repo https://github.com/iamshaunjp/react-native-tutorial/tree/lesson-15. Is it what you are using? It uses Expo.

Thanks,
Franz

**Comment by jayan2019** [comment]
Hope this method will work without any warnings

```
 const pressHandler = (key: string) => {
    const filteredTodos = todos.filter((todo: any) => todo.key !== key);
    setTodos(filteredTodos);
  };
```

**Comment by konstantinmv** [comment]
I'm having this same exact issue after updating to 0.63.2 and React 16.13.1 with all dispatched redux actions related to a MapView from RNMaps lib, can't seem to find any reasonable explanation for this behaviour.

**Comment by kennetpostigo** [comment]
I'm running to this as well, with react `16.13.1`

**Comment by chrisglein** [comment]
For those of you who are hitting this, please provide a standalone repro (Snack ideally, or link to repro repo) to make sure this issue can be efficiently investigated. A link to a youtube tutorial is not going to meet the bar.
