### ISSUE TITLE
Image persists after deletion until restart

### ISSUE THREAD

**Issue by slxsh** [facebook/react-native#29465]
## Description
I have a folder that contains images in a sequence i.e. 0.jpg, 1.jpg, 2.jpg, and so on. I want to delete an image but maintain the sequence after deletion. So to achieve this I am first deleting the desired image. Then I am renaming the images which come after the deleted image.
For example, I have two images 0.jpg and 1.jpg. I am deleting the 0.jpg and then renaming the 1.jpg to 0.jpg. However, the issue is that I am seeing the old 0.jpg instead of the newly renamed 0.jpg. After I restart the app I see the expected result.
[Screenshot](https://imgur.com/hcOrnat) 0.jpg is '1' and 1.jpg is '2' in the screenshot.
I am using react-native-fs to delete and rename the images.
( I asked this at various places but didn't get any response in the past 4 days.)
## React Native version:
(The command was taking forever so I copied this from package.json)
 "react": "16.13.1",
 "react-native": "0.63.0",

## Steps To Reproduce
1. Take two images, say 'x' and 'y'. Delete 'x'.
2. Rename 'y' to 'x'

## Expected Results
The deleted image shouldn't be displayed. 
See the updated results without requiring a restart of the app.

## Snack, code example, screenshot, or link to a repository:
This is my delete function. It is working as expected if I restart the app.
```
function delPic(currentIndex) {  
        RNFS.unlink(RNFS.ExternalDirectoryPath+'/'+name+'/'+currentIndex+'.jpg')  // deleting the image
            .then(async () => {
                if(currentIndex != files.length - 1)
                    for(j = currentIndex+1; j < files.length; j++) { // renaming the remaining images
                       await RNFS.moveFile(RNFS.ExternalDirectoryPath+'/'+name+'/'+j+'.jpg', RNFS.ExternalDirectoryPath+'/'+name+'/'+(j-1)+'.jpg')
                    }
                setVisible(false)
                setReload(!reload) // this will trigger useEffect which reads the directory and updates the state
            })
            .catch(e => console.log(e))
    }
```

**Comment by huntie** [comment]
Hi @slxsh, this looks to be related to your logic rather than the implementation of `<Image />`.

It would be good to see your render code, but I think what is happening is that when your function modifies the intended files on the native filesystem, this all happens externally via react-native-fs and then isn't observed anywhere else. There isn't any input to tell `Image` that the underlying file for `0.jpg` has changed, and so the UI isn't updated.

I would suggest trying adding a `key` on each image element that will change, or using a different image naming strategy.

**Comment by slxsh** [comment]
@huntie Hello, my render code is pretty big but here's the relevant chunk. After you pointed out I gave a unique key (unlike the code below) but it didn't change anything.
```
files.map((val, i) => {  // removed inline styling for readability 
                                     return (
                                            <TouchableOpacity key={i} style={{  }} onPress={() => { setInd(i); setVisible(true) }}>
                                                <Image source={{ uri : val.uri }} style={{ }}/>
                                                <Text style={{ }}>{parseInt(val.name.slice(0, -4)) + 1}</Text> // removing '.jpg'
                                            </TouchableOpacity>
                                        )
                                })
```
I could use a different naming strategy but I am giving the user the ability to delete and rename folders( containing the images). It's kind of inevitable that the user deletes a folder and makes a new one and renames it back which results in seeing the deleted folder with all the deleted images ( until restart of course). It seems to me that files are still in memory( cache?) but I am still clueless.

**Comment by huntie** [comment]
@slxsh If the value supplied to `key` is based on the item index, the file name, or both, this may not be sufficient. In each case, the image at index 0 will be given `key={0} source={{ uri: '0.png' }}` both before and after the filesystem change. In total, it won't cause React to change the `Image` element that was already rendered at that part of the element tree. However, if the key is changed to something different, or the element is destroyed and recreated, this will definitely update.

In total, I would recommend a different naming strategy and have the UI update after something like the folder update you mention. Alternatively, you could try a `FlatList` and make use of `extraData` to track when there has been a filesystem update.

**Comment by slxsh** [comment]
@huntie I couldn't provide unique keys to the `Image` so I ended up changing the naming scheme. I will take your word that `key` was the cause. I was thinking it has something to do with cache or something. 
I added time of creation (up to milliseconds) as the suffix to the folders and images. So even with the rename of the initial part, the images have a unique string in their names.
