### ISSUE TITLE
[0.63.2][iOS] react-native-xcode.sh fails to create bundle

### ISSUE THREAD

**Issue by norbertschuler** [facebook/react-native#29479]
## Description
I tried to upgrade our project from 0.62.2 to 0.63.2, but when I try to archive the iOS project for a release, the script `react-native-xcode.sh` fails to build the bundle file as the resulting command fails with an error as described in https://github.com/Plant-for-the-Planet-org/treemapper/pull/25#issuecomment-662955973 - this happened as the command is now called from the `ios` folder caused by this change https://github.com/facebook/react-native/commit/a8e85026cfa60056b1bcbcd39cde789e4d65f9cb#diff-f1a28d5a04c65bf04339b2fd16a6f56f.

I am not sure if I missed to upgrade anything so this error happened.

## React Native version:
```
System:
    OS: macOS 10.15.5
    CPU: (4) x64 Intel(R) Core(TM) i5-6287U CPU @ 3.10GHz
    Memory: 18.00 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.13.1 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.7 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /Users/norbertschuler/.gem/ruby/2.3.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 25, 27, 28, 29
      Build Tools: 27.0.3, 28.0.3, 29.0.2
      System Images: android-25 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom
      Android NDK: 21.3.6528147
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_131 - /usr/bin/javac
    Python: 2.7.17 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
  npmGlobalPackages:
    *react-native*: Not Found

```
## Steps To Reproduce
You can check the build log in one of the actions run on the pull request, e.g. https://github.com/Plant-for-the-Planet-org/treemapper/runs/902263258?check_suite_focus=true - building this pull request always show the same error.

## Expected Results
The bundle should be build without a error as it does when calling the command from the project root.

**Comment by norbertschuler** [comment]
I helped myself by changing the build phase script in Xcode now to invoke `react-native-xcode.sh` from the project root path with https://github.com/Plant-for-the-Planet-org/treemapper/pull/25/commits/1a68eed0ddfc6e444cd6fcc09246bb9adb8a4e2a.

**Comment by safaiyeh** [comment]
Hi @norbertschuler, glad you figured out your issue.

For future upgrade related issues, head over to https://github.com/react-native-community/upgrade-support.
