### ISSUE TITLE
[0.63.2][Android] KeyboardAvoidingView doesn't work properly

### ISSUE THREAD

**Issue by lily-chenll** [facebook/react-native#29481]
## Description

`KeyboardAvoidingView` 's height is not calculated properly.

There is a signup screen in my app and it has a long form inside. And codes inside is like
```
<SafeAreaView style={{ flex: 1 }}>
    <KeyboardAvoidingView behavior='height' style={{ flex: 1 }}>
          <TouchableWithoutFeedback>
                <ScrollView>
                     ...
                </ScrollView>
          </TouchableWithoutFeedback>
    </KeyboardAvoidingView>
</SafeAreaView>
```

Before entering this screen, there's a signin screen with a short form. When I click `sign up` button in the sign in screen and enter the sign up screen, there are two bugs:

1. If the Keyboard doesn't dismiss in sign in screen, the keyboard will be dismissed automatically after entering sign up screen. And I tap a `TextInput` randomly, the KeyboardAvoidingView's height is around `screen height - 2 * keyboard's height`, which is very short and there is a big empty zone above the keyboard.

2. 1. If the Keyboard has been dismissed in sign in screen, the keyboard will be shown automatically after entering sign up screen. And I tap a `TextInput` randomly, the KeyboardAvoidingView's height is bigger than `screen height - keyboard's height`. So part of the form will be overlapped with the keyboard.

## React Native version:
react-native: 0.63.2 => 0.63.2
emulator: pixel 2XL with Android 10
Android phone: pixel 2xl with Android 10

## Expected Results
`KeyboardAvoidingView` 's height should always be `screen height - keyboard's height`.

## Assumptions
After reviewing `KeyboardAvoidingView` 's source codes, 
For the bug1, it seems like the `initialFrameHeight` is incorret when there's a keyboard initially.
For the bug 2, it seems like the keyboard's height` calculation is wrong.

**Comment by safaiyeh** [comment]
Hi @lily-chenll thanks for the issue!

Could you create a repro in a Snack so it is easier to visualize the issue you are having?

**Comment by lily-chenll** [comment]
> Hi @lily-chenll thanks for the issue!
> 
> Could you create a repro in a Snack so it is easier to visualize the issue you are having?

Hi @safaiyeh thank you for your reply. The problem cannot be reproduced. Previously it seems like the `Keyboard.dismiss` in `TouchableWithoutFeedback` doesn't work, now it works.
