### ISSUE TITLE
this issue with update react native version 0.61.2 to 0.63.2

### ISSUE THREAD

**Issue by CK1038** [facebook/react-native#29482]
Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
[Fri Jul 24 2020 19:36:19.371]  ERROR    TypeError: Super expression must either be null or a function
[Fri Jul 24 2020 19:36:19.372]  ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
[Fri Jul 24 2020 19:36:20.410]  ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)

when I update react native version 0.61.2 to 0.63.2, it will produce the issue, my god

**Comment by TianShun2018** [comment]
0.62.0升级到0.63.2同样的问题

**Comment by songxiaoliang** [comment]
如何解决呀？

**Comment by lengqingfeng** [comment]
me too

**Comment by baronhsiao** [comment]
me too
