### ISSUE TITLE
Flipper add build configurations in RN 0.63

### ISSUE THREAD

**Issue by kayzenkayzen** [facebook/react-native#29485]
## Description
In RN63 the build configurations for flipper doesn't appear in the podfile, just use_flipper! Until RN62.2 the flipper pods was on the podfile and I was able to change it there

The question is, how to add more build configurations than "Debug" and "Release" and how to setup its to flipper in RN63?

## React Native version:
System:
    OS: macOS Mojave 10.14.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 28.38 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.7.4 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 27.0.3, 28.0.2, 28.0.3, 29.0.1, 29.0.2
      System Images: android-28 | Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 11.2.1/11B53 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_212 - /usr/bin/javac
    Python: 2.7.10 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.0 => 0.63.0 
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
N/A

## Expected Results
I want to be able to add more build configurations than Release and Debug and set it up on flipper

**Comment by ObidosDev** [comment]
Same here. We are using Debug and DebugStage configurations, so with previous variant it was real to use it, now it is not

**Comment by pang0018** [comment]
+1, I have 12 different configurations in my iOS project. This new podfile change doesn't seem to allow for custom configurations.

**Comment by ObidosDev** [comment]
@kayzenkayzen maybe need to change the label? Add flipper label and so on

**Comment by ObidosDev** [comment]
Fixed by https://github.com/facebook/react-native/pull/29074

**Comment by chungweileong94** [comment]
> +1, I have 12 different configurations in my iOS project. This new podfile change doesn't seem to allow for custom configurations.

Before the fix available, what you do is to use back the old setup from 0.62, it will work just fine. 
Or you can apply the fix from this [PR](https://github.com/facebook/react-native/pull/29074) for now.

```
def use_flipper_custom!(versions = {}, configurations: ['Debug', 'Debug.dev', 'Debug.staging'])
    versions['Flipper'] ||= '~> 0.41.1'
    versions['Flipper-DoubleConversion'] ||= '1.1.7'
    versions['Flipper-Folly'] ||= '~> 2.2'
    versions['Flipper-Glog'] ||= '0.3.6'
    versions['Flipper-PeerTalk'] ||= '~> 0.0.4'
    versions['Flipper-RSocket'] ||= '~> 1.1'
    pod 'FlipperKit', versions['Flipper'], :configuration => configurations
    pod 'FlipperKit/FlipperKitLayoutPlugin', versions['Flipper'], :configuration => configurations
    pod 'FlipperKit/SKIOSNetworkPlugin', versions['Flipper'], :configuration => configurations
    pod 'FlipperKit/FlipperKitUserDefaultsPlugin', versions['Flipper'], :configuration => configurations
    pod 'FlipperKit/FlipperKitReactPlugin', versions['Flipper'], :configuration => configurations
    # List all transitive dependencies for FlipperKit pods
    # to avoid them being linked in Release builds
    pod 'Flipper', versions['Flipper'], :configuration => configurations
    pod 'Flipper-DoubleConversion', versions['Flipper-DoubleConversion'], :configuration => configurations
    pod 'Flipper-Folly', versions['Flipper-Folly'], :configuration => configurations
    pod 'Flipper-Glog', versions['Flipper-Glog'], :configuration => configurations
    pod 'Flipper-PeerTalk', versions['Flipper-PeerTalk'], :configuration => configurations
    pod 'Flipper-RSocket', versions['Flipper-RSocket'], :configuration => configurations
    pod 'FlipperKit/Core', versions['Flipper'], :configuration => configurations
    pod 'FlipperKit/CppBridge', versions['Flipper'], :configuration => configurations
    pod 'FlipperKit/FBCxxFollyDynamicConvert', versions['Flipper'], :configuration => configurations
    pod 'FlipperKit/FBDefines', versions['Flipper'], :configuration => configurations
    pod 'FlipperKit/FKPortForwarding', versions['Flipper'], :configuration => configurations
    pod 'FlipperKit/FlipperKitHighlightOverlay', versions['Flipper'], :configuration => configurations
    pod 'FlipperKit/FlipperKitLayoutTextSearchable', versions['Flipper'], :configuration => configurations
    pod 'FlipperKit/FlipperKitNetworkPlugin', versions['Flipper'], :configuration => configurations
    end

  use_flipper_custom!
```

**Comment by safaiyeh** [comment]
Closing as it was fixed with https://github.com/facebook/react-native/pull/29074
