### ISSUE TITLE
unable to resolve @react-native-community/hooks

### ISSUE THREAD

**Issue by mukeshkar** [facebook/react-native#29489]
undefined Unable to resolve module `@react-native-community/hooks` from `App.js`: @react-native-community/hooks could not be found within the project or in these directories:
  ..\node_modules\@react-native-community

**Comment by narutopden** [comment]
I am having the same problem can anyone help ?

**Comment by narutopden** [comment]
> undefined Unable to resolve module `@react-native-community/hooks` from `App.js`: @react-native-community/hooks could not be found within the project or in these directories:
> 
>   ..\node_modules\@react-native-community
> 
> 
> 
> 
> 
> 

Did the problem solved ?
