### ISSUE TITLE
Sticky header falls off after adding a new section to the SectionList

### ISSUE THREAD

**Issue by Omelyan** [facebook/react-native#29494]
## Description
Removing some section from SectionList's sections and adding another one to the top breaks a sticky header of the section with the same index as the removed one.
In other words, changing the SectionList data from _S1_ to _S2_ causes the section _A_ sticky header to fail.
`S1 = [{ key: 'A', data: ['a'] }, { key: 'B', data: ['b'] }, { key: 'C', data: ['c'] }];`
`S2 = [{ key: 'X', data: ['x'] }, { key: 'A', data: ['a'] }, { key: 'C', data: ['c'] }];`

As a workaround, disabling sticky headers and then enabling it again fixes the broken header.
Or do not use a key for sections so that it falls back to array indices. But as the doc says, you should use a key to keep track of section re-ordering.

## React Native version:
npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.2 => 0.63.2

## Steps To Reproduce
1. See the Snack example.

## Expected Results
After 2 seconds, the section _A_ header becomes always visible and cannot be pushed off by the next one.
This makes SectionList totally unusable with dynamic data and sticky headers.

## Snack, code example, screenshot, or link to a repository:
https://snack.expo.io/@omelyan/sectionlist-sticky-header-issue

**Comment by t-bonfill** [comment]
Hi @Omelyan, I'm experiencing the same right now with a dynamic "sections" property. Have you solved it ?
Thanks
