### ISSUE TITLE
ActivityIndicator not visible without color prop on Pixel 3a

### ISSUE THREAD

**Issue by emersonhsieh** [facebook/react-native#29495]
## Description
The ActivityIndicator is not visible without setting the color prop on Pixel 3a. Setting the animating prop to true does not work either. Running on the Expo snack displays a green ActivityIndicator without the color prop, which was how it behaved in React Native 0.62.2 on the Pixel 3a. I believe this is a device specific issue, but I'm not sure what the scope is.

## React Native version: 0.63.2

Device: Pixel 3a
Android version: 10 (QQ3A.200605.002)

`react-native info`:

```
daSystem:
    OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
    Memory: 110.00 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.2.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.4 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 26, 28, 29
      Build Tools: 26.0.2, 28.0.3, 29.0.1, 29.0.2
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.4/11E146 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_212 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Create a fresh React Native app with `npx react-native init test_app`
2. Replace `App.js` with the code below
3. Plug in Pixel 3a phone, run `npm run android`

## Expected Results

Displaying two green ActivityIndicators (both on Dark and Light modes)

## Snack, code example, screenshot, or link to a repository:

Initialize the app and replace `App.js` with the following. For me, the first is not visible, while the second is visible. 

```
import React from 'react';
import {ActivityIndicator} from 'react-native';

const App: () => React$Node = () => {
  return (
    <>
      <ActivityIndicator />
      <ActivityIndicator color="00ff00" />
    </>
  );
};

export default App;
```

**Comment by emersonhsieh** [comment]
Might be a duplicate of https://github.com/facebook/react-native/issues/29378

**Comment by Kreozot** [comment]
Same bug on OnePlus 5T

**Comment by AlexanderMelchers** [comment]
+1 on this issue: `ActivityIndicator` not showing up on Android without specifying the `color`-attribute.
