### ISSUE TITLE
Debug server host & port for device is unreadable

### ISSUE THREAD

**Issue by eqlion** [facebook/react-native#29497]
## Description
I've followed the guide [to run the app on Android device](https://reactnative.dev/docs/running-on-device#building-your-app-for-production), in the section describing how to connect to the dev server via Wi-Fi, you need to go to dev settings and enter server ip in order to connect. The menu is black in both the dark, and the light theme on the device, thus rendering the text unreadable.

## React Native version:
System:
    OS: Linux 5.4 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz
    Memory: 329.64 MB / 7.66 GB
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 10.19.0 - /tmp/yarn--1595841958926-0.862734453456218/node
    Yarn: 1.22.4 - /tmp/yarn--1595841958926-0.862734453456218/yarn
    npm: Not Found
    Watchman: 20200712.162157.0 - /usr/local/bin/watchman
  SDKs:
    Android SDK:
      API Levels: 23, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.1
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 1.8.0_252 - /usr/bin/javac
    Python: 2.7.18 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 

Phone: OnePlus 7 Pro GM1910, Android 10, Oxygen OS 10.3.3.GM21AA 

## Steps To Reproduce
Follow the [guide](https://reactnative.dev/docs/running-on-device#building-your-app-for-production) to connect to the dev server via Wi-Fi from Android device.
1. Shake the device to open the dev menu
2. Open dev settings
3. Go Debug server host & port for device

## Expected Results
The text should be white if the background is black and vice versa.

## Snack, code example, screenshot, or link to a repository:
![screenshot](https://i.imgur.com/2NNxx4E.jpg)

**Comment by joseluismurillorios** [comment]
Same issue here, hope it's just a glitch

**Comment by safaiyeh** [comment]
Ah this is an interesting bug. I do not have a physical Android device on me, I'll tag this appropriately

**Comment by joseluismurillorios** [comment]
Found my problem, it was simply a declaration on my android/app/src/main/res/values files:

colors.xml
```xml
<resources>
    <!-- Here was the problem -->
    <color name="app_bg">#000</color>
</resources>
```

styles.xml
```xml
<style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
    <!-- The background color was the same as the text color -->
    <item name="android:textColor">#000000</item>
    <item name="android:windowBackground">@color/app_bg</item>
</style>
```

**Comment by eqlion** [comment]
> Found my problem, it was simply a declaration on my android/app/src/main/res/values files:
> 
> colors.xml
> 
> ```
> <resources>
>     
>     <color name="app_bg">#000</color>
> </resources>
> ```
> 
> styles.xml
> 
> ```
> <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
>     
>     <item name="android:textColor">#000000</item>
>     <item name="android:windowBackground">@color/app_bg</item>
> </style>
> ```

Indeed, the issue was with the colours, thank you!
