### ISSUE TITLE
React Native Android needs to target API level 29 before November 2, 2020

### ISSUE THREAD

**Issue by amarjain07** [facebook/react-native#29496]
## Description
As per the new Google Play policy, all apps must target at least Android 10 (API 29) before November 2, 2020.

More info: https://developer.android.com/distribute/play-policies

React Native is targeting API 28 as of today(v0.63), are there any plans to update the target SDK version?

## React Native version:
v0.63

## Expected Results
React Native to target API 29 well before November 2020, so that all apps using React Native can adapt to it.

**Comment by Gustash** [comment]
I agree that it needs to be updated upstream, but I'm fairly sure you can update the API target and the build tool versions yourself. I've done it before on previous versions where my app had a higher API target and it worked just fine in production

**Comment by aklinker1** [comment]
Yup, you can just update it yourself while the upstream is updated. After making the change, run a gradle sync in Android Studio after doing the update to double check that everything went well.

```diff
android {
    defaultConfig {
        ...
-       targetSdkVersion 28
+       targetSdkVersion 29
        ...
    }
}
```

**Comment by Gustash** [comment]
Btw, I'm pretty sure 0.63.2 already targets API 29

**Comment by ayox** [comment]
> Yup, you can just update it yourself while the upstream is updated. After making the change, run a gradle sync in Android Studio after doing the update to double check that everything went well.
> 
> ```diff
> android {
>     defaultConfig {
>         ...
> -       targetSdkVersion 28
> +       targetSdkVersion 29
>         ...
>     }
> }
> ```

What about other properties, should they also be updated to 29 ?  
```
      { 
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 29
        supportLibVersion = "28.0.0"
    }
```

**Comment by Gustash** [comment]
> > Yup, you can just update it yourself while the upstream is updated. After making the change, run a gradle sync in Android Studio after doing the update to double check that everything went well.
> 
> > 
> 
> > ```diff
> 
> > android {
> 
> >     defaultConfig {
> 
> >         ...
> 
> > -       targetSdkVersion 28
> 
> > +       targetSdkVersion 29
> 
> >         ...
> 
> >     }
> 
> > }
> 
> > ```
> 
> 
> 
> What about other properties, should they also be updated to 29 ?  
> 
> ```
> 
>       { 
> 
>         buildToolsVersion = "28.0.3"
> 
>         minSdkVersion = 16
> 
>         compileSdkVersion = 28
> 
>         targetSdkVersion = 29
> 
>         supportLibVersion = "28.0.0"
> 
>     }
> 
> ```
> 
> 

Yes, except for `minSdkVersion`

**Comment by aklinker1** [comment]
@ayox If you do the gradle sync in android studio is should walk you though and give you warnings and versions to update them to.

**Comment by amarjain07** [comment]
@ayox @Gustash @aklinker1 
API 29 upgrade is not as straightforward as it seems, since it requires some specific handlings for permissions, storage, caching etc. 
The changes that may be required are listed in the following links:
[](https://developer.android.com/about/versions/10/behavior-changes-all)
[](https://developer.android.com/about/versions/10/behavior-changes-10)
[](https://developer.android.com/distribute/best-practices/develop/target-sdk)
[](https://developer.android.com/about/versions/10/privacy/changes )

**Comment by Gustash** [comment]
> @ayox @Gustash @aklinker1 
> 
> API 29 upgrade is not as straightforward as it seems, since it requires some specific handlings for permissions, storage, caching etc. 
> 
> The changes that may be required are listed in the following links:
> 
> [https://developer.android.com/about/versions/10/behavior-changes-all](https://developer.android.com/about/versions/10/behavior-changes-all)
> 
> [https://developer.android.com/about/versions/10/behavior-changes-all](https://developer.android.com/about/versions/10/behavior-changes-10)
> 
> [https://developer.android.com/about/versions/10/behavior-changes-all](https://developer.android.com/distribute/best-practices/develop/target-sdk)
> 
> [https://developer.android.com/about/versions/10/behavior-changes-all](https://developer.android.com/about/versions/10/privacy/changes )

I don't think any of these are used in the core. And again, 0.63.2 is already targeting API 29, so I don't even know why this issue is still open

**Comment by Gustash** [comment]
Check #29350

**Comment by amarjain07** [comment]
Hey @Gustash , I checked the build.gradle of v0.63.2 https://github.com/facebook/react-native/blob/v0.63.2/ReactAndroid/build.gradle
It shows the targetSDKVersion as 28. Could you help me how you came to know that 0.63.2 is targeting 29?

**Comment by Gustash** [comment]
Go to the [Upgrade Helper](https://react-native-community.github.io/upgrade-helper/?from=0.62.2&to=0.63.2) from 0.62 to 0.63 and check `android/build.gradle`.

You can also just run `npx react-native init TempProject` to start a brand new 0.63 project and you'll see it creates an `android/build.gradle` with API 29 as a target

**Comment by Gustash** [comment]
Also, [this](https://github.com/facebook/react-native/blob/v0.63.2/template) is what you should be checking for the files created on `react-native init`

**Comment by ibrahimyolbir** [comment]
Hi @Gustash I have a question. I dont want to upgrade my React native version 62.2 to 63.2. Is it enough if i just change android/build.gradle >  **targetSdkVersion = 28** to 29

**Comment by Gustash** [comment]
> Hi @Gustash I have a question. I dont want to upgrade my React native version 62.2 to 63.2. Is it enough if i just change android/build.gradle >  **targetSdkVersion = 28** to 29   
> 
> 

Yes, should be

**Comment by safaiyeh** [comment]
@amarjain07 have you had problems targeting SDK 29? Application SDK targets override any targets in Android dependencies. Otherwise, could you close this issue?

**Comment by Vasu1990** [comment]
I believe thumb rule is to have compileSdkVersion should be greater than or equal to the targetSdkVersion
Below is the setting I made for my App
    ext {
        buildToolsVersion = "29.0.2"
        minSdkVersion = 16
        compileSdkVersion = 29
        targetSdkVersion = 29
        excludeAppGlideModule = true
    }

**Comment by joaogabrieljs** [comment]
> I believe thumb rule is to have compileSdkVersion should be greater than or equal to the targetSdkVersion
> Below is the setting I made for my App
> ext {
> buildToolsVersion = "29.0.2"
> minSdkVersion = 16
> compileSdkVersion = 29
> targetSdkVersion = 29
> excludeAppGlideModule = true
> }

I just did it like @Vasu1990 and rebuild the project.

**Comment by amarjain07** [comment]
Closing the issue as it doesn't require any change in the library to support api 29.

**Comment by MarcoBrugali** [comment]
Hi, react native 60.5 support api 29?

**Comment by jessiealbarian** [comment]
Has anyone kept their project at RN 0.61 with SDK 29? 
I have a project that is unable to update RN right now, and I'm not able to build for release on iOS or Android with SDK 30.
