### ISSUE TITLE
Fails running on iPhone 4 with bad access

### ISSUE THREAD

**Issue by richardsabow** [facebook/react-native#295]
When i try to run any simple app on my iPhone 4, i get always an exception from `RCTConvert.m` in function `UIFont:withFamily:size:weight:style:` at this statement: `const RCTFontWeight RCTDefaultFontWeight = UIFontWeightRegular;` (currently line 542).
It fails with bad access exception. But in simulator it works well.
Any idea?

**Comment by noahlu** [comment]
I encounter the same problem, but it runs ok on iphone6.

**Comment by richardsabow** [comment]
Maybe an issue with iOS 7? Can it be solved somehow?

**Comment by ide** [comment]
Yeah, looks like it could be an iOS 7 issue although I'd expect the compiler to inline their values so it could be something else. What if you figure out what UIFontWeightRegular is equal to in iOS 8 and manually inline it on line 542?

```objc
UIKIT_EXTERN const CGFloat UIFontWeightUltraLight NS_AVAILABLE_IOS(8_2);
UIKIT_EXTERN const CGFloat UIFontWeightThin NS_AVAILABLE_IOS(8_2);
UIKIT_EXTERN const CGFloat UIFontWeightLight NS_AVAILABLE_IOS(8_2);
UIKIT_EXTERN const CGFloat UIFontWeightRegular NS_AVAILABLE_IOS(8_2);
UIKIT_EXTERN const CGFloat UIFontWeightMedium NS_AVAILABLE_IOS(8_2);
UIKIT_EXTERN const CGFloat UIFontWeightSemibold NS_AVAILABLE_IOS(8_2);
UIKIT_EXTERN const CGFloat UIFontWeightBold NS_AVAILABLE_IOS(8_2);
UIKIT_EXTERN const CGFloat UIFontWeightHeavy NS_AVAILABLE_IOS(8_2);
UIKIT_EXTERN const CGFloat UIFontWeightBlack NS_AVAILABLE_IOS(8_2);
```

**Comment by tundrax** [comment]
The constants are defined staring on line 456. But the condition ```#ifndef __IPHONE_8_2``` is not fulfilled.

**Comment by ide** [comment]
Might be a red herring then since that checks only the SDK version at compile time.

**Comment by sahrens** [comment]
I believe @nicklockwood has a fix for this.

**Comment by nicklockwood** [comment]
Yeah, I'd assumed that the constants would be compiled in but they weren't. I've changed up the logic to replace them with macros if you're targeting iOS 8.1 and earlier.

**Comment by internet5** [comment]
How to resolve it?

**Comment by hermanschaaf** [comment]
I can confirm that this is fixed in the latest master branch (I'm using React Native v0.3.11)

**Comment by brentvatne** [comment]
Looks like this has been fixed! Thanks for the report
