### ISSUE TITLE
Linked IN closes automatically

### ISSUE THREAD

**Issue by srinivasanBG** [facebook/react-native#29503]
## Description
LinkedIN webviewUI/Modal closes automatically

## React Native version:
System:
OS: macOS 10.15.5
CPU: (4) x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
Memory: 118.00 MB / 8.00 GB
Shell: 3.2.57 - /bin/bash
Binaries:
Node: 10.16.0 - /usr/local/bin/node
Yarn: 1.22.4 - ~/.yarn/bin/yarn
npm: 6.9.0 - /usr/local/bin/npm
Watchman: 4.9.0 - /usr/local/bin/watchman
SDKs:
iOS SDK:
Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
Android SDK:
Android NDK: 21.0.6113669
IDEs:
Android Studio: 3.6 AI-192.7142.36.36.6241897
Xcode: 11.6/11E708 - /usr/bin/xcodebuild
npmPackages:
react: 16.8.6 => 16.8.6
react-native: 0.60.5 => 0.60.5
npmGlobalPackages:
react-native-cli: 2.0.1

## Steps To Reproduce

1.Open the linked in modal
2.view automatically closes

## Expected Results
Webview should not close automatically

## Snack, code example, screenshot, or link to a repository:
Webview/Modal closes automatically

**Comment by safaiyeh** [comment]
Please open an issue with https://github.com/react-native-community/react-native-webview
