### ISSUE TITLE
Emoji does not enlarge on ios on textInput

### ISSUE THREAD

**Issue by Rutvik17** [facebook/react-native#29508]
## Description
When entering only emojis in react native text input the emojis dont enlarge even after a new font size has been applied. Expecting to enlarge when a new font size has been applied programmatically. 
Emojis enlarge as expected on android. 

`allowFontScaling={false}` or `allowFontScaling={true}` does not help at all

## React Native version: 
```
"react": "16.9.0",
    "react-native": "0.61.0",
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. On IOS enter emoji inside text input and if you are trying to enlarge them programmatically, they do not enlarge even after a new style is applied. 
2. Works fine on android.

## Expected Results
Expect font scaling on emojis to works on both android and ios.

`My code`

```
 onChangeText(text) {
    this.props.onTextChanged(text);
  }

<TextInput
        style={[
          styles.textInput,
          this.props.textInputStyle,
          AppUtil.isLargeEmojiFont(this.props.text)
            ? {
                fontSize: 26,
                height: this.props.composerHeight + Style.getHeight(13)
              }
            : {
                height: this.props.composerHeight,
                fontSize: isiPhoneSE ? 13 : 15
              }
        ]}
onChangeText={text => this.onChangeText(text)}
      />
```

`AppUtil.isLargeEmojiFont(this.props.text)` returns correct boolean.

I have also tried to set the styles into a state but that does not work as well.

### The work around is to add a setTimeout in `onChangeText` but that leads to a lot of timing issues

![Simulator Screen Shot - iPhone 8 - 2020-07-27 at 18 25 57](https://user-images.githubusercontent.com/19266929/88598214-cdee9d80-d036-11ea-8024-134dfe0e50db.png)
Please provide all the information requested. Issues that do not follow this format are likely to stall.

**Comment by Tymofiev** [comment]
+1
