### ISSUE TITLE
App crashes while trying to share url with image as base64 [iOS only]

### ISSUE THREAD

**Issue by krzysztofnowak** [facebook/react-native#29500]
Issue spotted on application that has 14k+ lines of source code and many dependencies, but check that clean project generated from react-native cli also has same issue.
Issue found in Share.share() function. When it contains image as base64. app crashes, when function is invoked.
Problem exists on iOS only

## Description
I made clean new projected using latest react-native-cli (https://reactnative.dev/docs/environment-setup)
As app body put example of sharing from (https://reactnative.dev/docs/share#share)
Changed the shared content. Something as simple as empty white box, provided as base64.

## React Native version:
System:
    OS: macOS 10.15.5
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 401.15 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
    Yarn: Not Found
    npm: 6.14.4 - ~/.nvm/versions/node/v12.16.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.2 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce

1. Run app.
2. Click on 'Share' CTA
3. Choose 'Save Image' option from select

## Expected Results
Screen with 'File manager' should be presented allowing to save image.

## Snack, code example, screenshot, or link to a repository:
```
import React from 'react';
import { Share, View, Button } from 'react-native';

const ShareExample = () => {
  const onShare = async () => {
    try {
      const result = await Share.share({
        url: `data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAAAAAA6fptVAAAACklEQVR4nGP6DwABBQECz6AuzQAAAABJRU5ErkJggg==`,
      });
      if (result.action === Share.sharedAction) {
        if (result.activityType) {
          // shared with activity type of result.activityType
        } else {
          // shared
        }
      } else if (result.action === Share.dismissedAction) {
        // dismissed
      }
    } catch (error) {
      alert(error.message);
    }
  };
  return (
      <View style={{ marginTop: 50 }}>
<Button onPress={onShare} title="Share" />
      </View>
);
};

export default ShareExample;
```

**Comment by krzysztofnowak** [comment]
@react-native-bot it is not Image component issue. Image renders base64 properly. It is Share component

**Comment by gedeagas** [comment]
Hi @krzysztofnowak, I can't seem to replicate the issue on my end. Did you enable the permission of your app to save images?. A snack or repo example would be very helpful

https://snack.expo.io/CVcVKraWV

**Comment by krzysztofnowak** [comment]
@gedeagas full example here: https://github.com/krzysztofnowak/rn-sandbox

**Comment by safaiyeh** [comment]
Thank you for the issue @krzysztofciombor.
Thanks for checking it out @gedeagas .

I ran your example locally and it is crashing. Might have been introduced in 0.63, Snack's are currently at 0.62.

**Comment by gedeagas** [comment]
interesting, I haven't tested it on react-native 63. will try to check again today.

**Comment by krzysztofnowak** [comment]
@safaiyeh @gedeagas I'll add that my main project is using RN@0.61.23 and I'm having same issue so it is not something new introduced in latest version

**Comment by PeteTheHeat** [comment]
Do you have the crash stack trace?

Also what is the ObjC file backing the share native module? From a quick search I couldn't find it 😕  Android is https://github.com/facebook/react-native/blob/96a6ffb3e8070dfc45c5cfb78963afe3422def37/ReactAndroid/src/main/java/com/facebook/react/modules/share/ShareModule.java

**Comment by gedeagas** [comment]
@PeteTheHeat iOS uses `RCTActionSheetManager` https://github.com/facebook/react-native/blob/c8d678abcf93fd3f6daf4bebfdf25937995c1fdf/React/CoreModules/RCTActionSheetManager.mm for the share native module. 

@krzysztofnowak interesting. can't seem to replicate it on my new project, will try to replicate this strange behaviour on RNTester.

**Comment by krzysztofnowak** [comment]
@gedeagas any chance you had time to replicate issue?
