### ISSUE TITLE
React Navigation 4.x Full screen Modal - Manual Close doesn't reset the modal state.

### ISSUE THREAD

**Issue by davStar** [facebook/react-native#29519]
## Description
I am using React Navigation 4.X. One nav icon open in a modal another Stack navigator. See the picture bellow (Code app.js available later on this description).
 
![image](https://user-images.githubusercontent.com/26174579/88723525-577e9800-d129-11ea-861d-a85757525e20.png)

The modal should provide a step by step formular. On the top right a cross icon should close the modal. 
<img width="268" alt="Screenshot 2020-07-28 at 23 25 14" src="https://user-images.githubusercontent.com/26174579/88724257-76315e80-d12a-11ea-911c-84472a9c91c5.png">

1. I m in step 2 or 3 where I ve checked some components (checkbox, button etc..) in Step 1 or 2 or 3. 
2. I close the modal via the cross button (I just use this.props.navigation.navigate('Home')).
3. I come back to the home page earlier. 
4. I re open the modal and all the value I have checked earlier in 1. are remained.  

Furthermore if I've closed the modal when I was in step 2 or 3. I will re open the modal and be placed to the last step I was.

## React Native version:
React Navigation 4.x
React Native 0.62
Module : react-native-progress-steps

## Steps To Reproduce
Simulation done on IOS and Android. 

## Expected Results
No state should be kept when I close a modal. 

## Snack, code example, screenshot, or link to a repository:
**app.js**  : 

```
`  const CivContainer = createStackNavigator({
  default : createMaterialBottomTabNavigator({
               
        SetbyStep: 
        {
        screen: StepbyStepStack,
        navigationOptions:{
          header: null,
          tabBarVisible: false,
          tabBarIcon: ({tintColor}) => (        
              <Icon style={[{color: tintColor}]}  size={25} family='AntDesign' name={'notification'}/>
               ),
        },      
        },
        Home:
        {
          screen: HomeScreen,
          navigationOptions:{
            header: false,
            tabBarIcon: ({tintColor}) => (
                <Icon style={[{color: tintColor}]}  size={25} family='AntDesign' name={'profile'}/>
            ),
          }
        },
        You:
        {
          screen: ProfileScreen,
          navigationOptions:{
            header: false,
            tabBarIcon: ({tintColor}) => (
                <Icon style={[{color: tintColor}]}  size={25} family='AntDesign' name={'smile-circle'}/>
            ),
          }
        },
      },
    {
      initialRouteName: 'Home',
      shifting: true,
      showLabel: false,
      barStyle:{ 
        backgroundColor: "white",     
        opacity: 0.3,
    },
      activeColor:'#161F3D',
      inactiveColor: '#8888C4',  
      navigationOptions: {
        header: false,
  
      },

    }  
    ),

  },
{
  mode: 'modal',
  headerMode: "none",
});  

const AppNavigator = createSwitchNavigator(
  {
  Auth: AuthStack,
  Steps: StepbyStepStack,
  Main: CivContainer,
  },
  {
    initialRouteName: 'Auth',
  
  }
);
const AppContainer = createAppContainer(AppNavigator);

    `
```

Then the StepbyStep.js, bellow the onRequestClose() function used when I close the cross icon. I tried to reinit all the variables of my different steps components even force to hook to the initial step... That's doesn't work too. See the code bellow: 

```
`  async onRequestClose()
{
        this.setState({
            activeStep: 0,
            categoryIndex:'',
            errors: true,
            isValid: true,
            press_tap: 0,
            signalisation_response: false,
            category:'',
            description:'',
            uri_photo1:'',
            uri_photo2:'',
            uri_photo3:'',
            uri_photo4:'',
            data:undefined,
            loading:false,
            loadervisible:false,
    })
        this.props.navigation.navigate('Home');
    }`
```

**Comment by safaiyeh** [comment]
Hi @davStar this issue is more appropriate to be opened in the react-navigation repo. Feel free to open the issue there!
