### ISSUE TITLE
I had this issue too, I'm not very familiar with XCode, but I opened the `.xcodeworkspace` file and then clicked build, which was successful!

### ISSUE THREAD

**Issue by hyisboy** [facebook/react-native#29512]
what is .xcodeworkspace ?

**Comment by dulmandakh** [comment]
Closing the issue because this issue tracker is intended to track React Native issues, but this looks like a support issue. Please see https://stackoverflow.com/questions/21631313/xcode-project-vs-xcode-workspace-differences
