### ISSUE TITLE
Status bar disappears on TextInput focus IOS

### ISSUE THREAD

**Issue by waheedakhtar694** [facebook/react-native#29520]
## Description
I just wanted to keep display my status bar on ios but whenever I focus TextInput my Status bar goes away.

## React Native version:
System:
    OS: macOS 10.15.5
    CPU: (4) x64 Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
    Memory: 220.59 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.16.1 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 22, 23, 24, 25, 26, 27, 28, 29
      Build Tools: 23.0.1, 25.0.3, 26.0.2, 27.0.3, 28.0.3
      System Images: android-18 | Google APIs ARM EABI v7a, android-21 | Google APIs ARM EABI v7a, android-21 | Google APIs Intel x86 Atom, android-21 | Google APIs Intel x86 Atom_64, android-22 | Google APIs ARM EABI v7a, android-22 | Google APIs Intel x86 Atom, android-22 | Google APIs Intel x86 Atom_64, android-23 | Google APIs ARM EABI v7a, android-23 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-24 | Google APIs ARM EABI v7a, android-24 | Google APIs Intel x86 Atom, android-24 | Google APIs Intel x86 Atom_64, android-25 | Google APIs ARM 64 v8a, android-25 | Google APIs ARM EABI v7a, android-25 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom_64, android-25 | Google Play Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-29 | Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6308749
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_121 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: ^4.10.1 => 4.10.1 
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.0 => 0.63.0 
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce

1. Just render TextInput in your index.js file 
2. focus that TextInput.

## Expected Results
The status bar should keep the display on focus or on clear Textinput

Note: I am not using any KeyboardAvoidingView I am just rendering TextInput in my index.js file of the Project.

Enabled from Xcode
<img width="411" alt="Screenshot 2020-07-29 at 3 28 43 AM" src="https://user-images.githubusercontent.com/45425486/88729118-9540e800-d14c-11ea-80da-c39b82db540f.png">

![keyboard](https://user-images.githubusercontent.com/45425486/88729245-d5a06600-d14c-11ea-83f5-6d00be8b7fb1.gif)

**Comment by safaiyeh** [comment]
@waheedakhtar694 thanks for the issue! Could you provide either a Snack or a repro of this? Thanks

**Comment by waheedakhtar694** [comment]
@safaiyeh I manage to fix this issue, actually, the bar was not hiding it was changing its color, there were few issues but the main issues were Webview changes the color of the bar when input becomes in focus, this solution worked for me 

https://github.com/react-native-community/react-native-webview/issues/735#issuecomment-570935900

**Comment by safaiyeh** [comment]
Glad you found a fix! @waheedakhtar694 that is odd behavior from WebView, should not be happening

**Comment by bockc** [comment]
I have the same issue but with KeyboardAvoidingView from react-native.
My StatusBar is set to `'dark-content'` in XCode, I even have a `StatusBar.setBarStyle('dark-content')` in index.ios.js.
Each time I focus a TextInput in a KeyboardAvoidingView, the StatusBar changes to `'light-content'`, and when I focus out it goes back to `'dark-content'`.
The only workaround I have right-now is to manually set the StatusBar style in a `onFocus` on KeyboardAvoidingViews, but it's pretty annoying.
Any idea ?
