### ISSUE TITLE
TextInput in a custom component rerenders when used with useState hook

### ISSUE THREAD

**Issue by ksi9302** [facebook/react-native#29522]
## Description
When a TextInput component triggers action such as in onChangeText or onKeyPress method which then triggers setState, the component will re render and lose focuse.

## React Native version:
0.62 (Unable to upgrade due to use of Expo)

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Create a Custom Wrapper Component simple like View (With In Parent Component)
2. Declare useStateHook
3. Pass TextInput to the Wrapper Component either by direct JSX or Custom Component
4. Bind setState function to any of event listeners of TextInput.
5. Try on Web or any device

## Expected Results
sets State but does not lose focus or re renders

## Snack, code example, screenshot, or link to a repository:

[Expo Example](https://snack.expo.io/@ksi9302/1f9369)

If not but and expected output of React, Please let me know and I'll close the ticket.
However, there seems to be an inconsistent issues when using custom components and children props.

-- Update --
I figured that declaring a wrapper component inside the parent component is causing the problem.
However, in my real project where this problem occurs, there's not just one simple wrapper but few other components declared inside the parent component which shares state and functions. To make this work, I will have to move all these components out of the parent component and pass down all the states and functions as props which will be a pain in the ass.
Is this a discouraged approach from the first place or is there a room for improvement on this?

**Comment by ksi9302** [comment]
Closed the ticket as I I think this is rather regarding an innate propety of React, not a bug really.
Otherwise, please reopen.

Thank you.

**Comment by shensven** [comment]
how did you solve this lost focus problem
