### ISSUE TITLE
[Modal][iOS] Can't Present Modal View Controller Without a Presenting View Controller

### ISSUE THREAD

**Issue by ppiekarczyk** [facebook/react-native#2952]
Hi guys, 

Setting `visible` to true inside of a modal will cause the error below. 
Changing the state of `visible` works fine, however.

I've stripped down `ModalExample.js` to demonstrate the bare minimum needed to recreate this issue.

**This Fails:**
```javascript
    return (
      <View>
        <Modal
          visible={true}>
        </Modal>
      </View>
    );
```

**This Works Fine:**
```javascript
    return (
      <View>
        <Modal
          visible={this.state.modalVisible}>
        </Modal>
        <Button onPress={this._setModalVisible.bind(this, true)}>
          Present
        </Button>
      </View>
    );
```

```error
Exception thrown while executing UI block: Can't present modal view controller without a presenting view controller
```

The error throws here:
https://github.com/facebook/react-native/blob/19067a8fbc627193fdd2ee89b69e19d73352adc8/React/Views/RCTModalHostView.m#L76

I would love to try and solve this myself with a little bit of guidance :+1:

**Comment by olofd** [comment]
+1

**Comment by biggie8199** [comment]
+1

**Comment by sowdri** [comment]
+1

**Comment by phongyewtong** [comment]
+ 1

**Comment by bright-sea** [comment]
+1

**Comment by debian789** [comment]
It appears that you're trying to display the modal with "true" load view,
Test initialized with "false" modal

**Comment by walter211** [comment]
@debian789 all false initilized still thrown error

**Comment by debian789** [comment]
@walter211  which react-native version of you?

**Comment by walter211** [comment]
@debian789 v0.11.0

**Comment by debian789** [comment]
@walter211  I tested with version 0.11.4

**Comment by JAStanton** [comment]
Not sure why this works but:
```jsx
class MyDialog extends React.Component {
  state = {visible: false};
  componentDidMount() {
   this.setState({visible: true});
  }
  render() {
    return <View><Modal visible={this.state.visble} /></View>
  }
}
```

**Comment by ide** [comment]
This doesn't directly fix the issue at hand but unless you're working on a legacy app you can use a navigator instead of Modal: http://browniefed.com/blog/2015/10/18/react-native-easy-overlay-modal-with-navigator/

**Comment by debian789** [comment]
constructor @JAStanton  

var React = require('react-native');

var {
  Modal,
  TouchableHighlight,
  Text,
} = React;

class MyDialog extends React.Component {
	constructor(props){
		super(props);
		this.state = {visible: false};
	}

  _modalVisible(visibleModal) {
    this.setState({visible: visibleModal});
  }

  componentDidMount() {
   //this.setState({visible: true});
  }

  render() {
    return <View>
    	<Modal visible={this.state.visble} >
    	<Text>Hello world !</Text>
    	</Modal>

		<TouchableHighlight  onPress={this._modalVisible.bind(this,true)} >
          <Text >Active Modal</Text>
        </TouchableHighlight>) 



    </View>
  }
}

**Comment by tokinonagare** [comment]
+1

**Comment by javache** [comment]
This is probably happening since you're trying to present a modal before the first view has gone on screen.

**Comment by niftylettuce** [comment]
@javache thanks for this!  that was my issue too.  I was trying to make the modal visible when it rendered :laughing:

**Comment by ktoh** [comment]
@javache I'm not sure this issue should be closed. You're probably right that the technical issue is rendering order, but one of the key abstractions of React design is that it allows developers to think in terms of state with the platform taking care of mutations. 

Forcing developers to set a `false` state on the modal and explicitly waiting for a render before setting the desired state to `true` runs counter to that principle. After all, folks don't have to explicitly manage rendering order for other container-containee components like listview, view, text, etc.

**Comment by ktoh** [comment]
@javache ah got it, thanks for the clarification! I see the commit comment now, will revert if it doesn't solve the issue

**Comment by javache** [comment]
Hi @ktoh, with https://github.com/facebook/react-native/commit/6ab2719bff9753f533d7bb91f848d59ddece3e75 pushed to master, the React rendering order should no longer matter and we solve this issue on the native side. Let me know if that doesn't work for you.

**Comment by backslash112** [comment]
+1
