### ISSUE TITLE
Infinite nw_socket_handle_socket_event error 

### ISSUE THREAD

**Issue by crystalneth** [facebook/react-native#29539]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Bug #21030 still occurs for me with RN 0.63.2

One of the fixes mentioned works, making this change in AppDelegate.m:

```
- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  NSURL *jsUrl = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
  [[RCTBundleURLProvider sharedSettings] setJsLocation:jsUrl.host];
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
...
```

## React Native version:
0.63.2

**Comment by safaiyeh** [comment]
Hi @crystalneth thanks for the issue. If one of the fixes worked, are you proposing the fix should be implemented in the template? If so, feel free to open a PR.

Otherwise, can we close this issue?
