### ISSUE TITLE
pod install not working

### ISSUE THREAD

**Issue by bhandaribhumin** [facebook/react-native#29535]
## Description
when I was install reactnavigation in my project and do a step (https://reactnavigation.org/docs/getting-started#installing-dependencies-into-a-bare-react-native-project) it will be shown error message.

## React Native version:

> System:
>     OS: macOS 10.15.5
>     CPU: (4) x64 Intel(R) Core(TM) M-5Y31 CPU @ 0.90GHz
>     Memory: 518.58 MB / 8.00 GB
>     Shell: 3.2.57 - /bin/bash
>   Binaries:
>     Node: 12.16.2 - /usr/local/bin/node
>     Yarn: 1.22.4 - ~/.yarn/bin/yarn
>     npm: 6.14.5 - ~/.npm-global/bin/npm
>     Watchman: 4.9.0 - /usr/local/bin/watchman
>   Managers:
>     CocoaPods: 1.9.3 - /usr/local/bin/pod
>   SDKs:
>     iOS SDK:
>       Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
>     Android SDK:
>       API Levels: 25, 26, 28, 29
>       Build Tools: 28.0.3, 29.0.3, 30.0.0
>       Android NDK: Not Found
>   IDEs:
>     Android Studio: 4.0 AI-193.6911.18.40.6514223
>     Xcode: 11.6/11E708 - /usr/bin/xcodebuild
>   Languages:
>     Java: 1.8.0_241 - /usr/bin/javac
>     Python: 3.7.6 - /Users/bhuminbhandari/opt/anaconda3/bin/python
>   npmPackages:
>     @react-native-community/cli: Not Found
>     react: 16.13.1 => 16.13.1 
>     react-native: 0.63.2 => 0.63.2 
>   npmGlobalPackages:
>     *react-native*: Not Found

## Expected Results
```

npx: installed 1 in 3.45s
Scanning for pods...
1.9.3
> pod install
Detected React Native module pods for RNCMaskedView, RNGestureHandler, RNReanimated, RNScreens, and react-native-safe-area-context

[!] Invalid `Podfile` file: undefined method `[]' for nil:NilClass.

 #  from /Users/bhuminbhandari/Desktop/Projects/react-native/businessBooks/ios/Podfile:9
 #  -------------------------------------------
 #  
 >    use_react_native!(:path => config["reactNativePath"])
 #  
 #  -------------------------------------------

Aborting run
An unexpected error was encountered. Please report it as a bug:
Error
    at CocoaPodsPackageManager._installAsync (/Users/bhuminbhandari/.npm/_npx/17801/lib/node_modules/pod-install/build/index.js:2:75999)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)


```

**Comment by EvanBacon** [comment]
Duplicate https://github.com/react-native-community/cli/issues/860 ?

**Comment by safaiyeh** [comment]
> Duplicate [react-native-community/cli#860](https://github.com/react-native-community/cli/issues/860) ?

@bhandaribhumin Did the resolution in this issue help you out?

**Comment by bhandaribhumin** [comment]
Yes bro

**Comment by bhandaribhumin** [comment]
Yes
