### ISSUE TITLE
React Native App ScrollView,Flatlist and Animation laggy on Android Version 9 and 10

### ISSUE THREAD

**Issue by vikil143** [facebook/react-native#29541]
I have a business app which builds on react-native technology on development time its version was compileSdkVersion and targetSdkVersion was 28(i.e. Android Version 8) so that I think it works fine below Android Version 9 device So now I need to solve that laggy issue is there any solution for this I tried changing complieSdkVersion to 29 but it's not working fine so please 
help to tackle  this issue I can provide APK for test also

## Environment Information
System:
    OS: Linux 5.4 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i5-2500 CPU @ 3.30GHz
    Memory: 1.65 GB / 15.47 GB
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 13.10.1 - ~/.nvm/versions/node/v13.10.1/bin/node
    npm: 6.14.5 - ~/.nvm/versions/node/v13.10.1/bin/npm
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
* android config
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
    }

## Expected Results
Smooth scrolling and animation please help me to achieve target audience in upgraded version

**Comment by pablogil** [comment]
I have the same problem. Flatlist stops for a couple of seconds when scrolling in Android, iOS flatlist component works pretty well.  

To replicate you can create an react-native from scratch and load a flatlist with 600+ items

Here is my env

System:
    OS: macOS 10.15.5
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 25.88 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.5 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3
      System Images: android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-R | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_221 - /usr/bin/javac
    Python: 3.7.3 - /Users/pablogil/anaconda3/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
  npmGlobalPackages:
    *react-native*: Not Found
