### ISSUE TITLE
Firebase support confirmation for react-native apps

### ISSUE THREAD

**Issue by tarunaahuja20** [facebook/react-native#29549]
## Description
I am building an application that has a requirement of using a firebase realtime database. I tried using this [library](https://rnfirebase.io/) but facing some issues. Can someone please confirm if react-native supports firebase totally or it supports with some known bugs.

## React Native version:
0.62.2

## Steps To Reproduce

1.  I created a react-native app. Now what I want is to stop the synchronization of the realtime database from the react-native application. So I used the property which is " keepSynced(false)" but it's not working as the expected behavior mentioned in the rnfirebase library. Also, there is another method named "setPersistenceEnabled(true)", this method is expected to return Promise but it is not doing so.
2. Need confirmation if this is a known bug and if there are some limitations in using firebase for react-native applications.

## Expected Results
I want to stop the synchronization of the offline stored data to the realtime firebase.

## Snack, code example, screenshot, or link to a repository:
const reference = database().ref('/');
reference.keepSynced(false);

 database().setPersistenceEnabled(true).then() ; // not working as expected, Promise type return is not working.

**Comment by safaiyeh** [comment]
Hi @tarunaahuja20 I would suggest creating an issue with react-native-firebase. Personally, I have used many of their modules, but it does take a bit of setup. Issues on this repo relate to React Native core, thanks!
