### ISSUE TITLE
modal change navigation bar color

### ISSUE THREAD

**Issue by maystrenkoYurii** [facebook/react-native#29543]
If use modal end custom bottom nav bar color https://www.npmjs.com/package/react-native-navigation-bar-color, color navigation bar reset to transparent, and show color from android theme style. Bug located in dialog theme styles modal

react: 16.13.1 => 16.13.1 
react-native: 0.63.2 => 0.63.2 

![IMG_20200731_161453](https://user-images.githubusercontent.com/23016311/89102467-25638380-d412-11ea-9799-6eca2882e78c.jpg)

**Comment by cbetori** [comment]
I am having the same issue.

**Comment by safaiyeh** [comment]
> @cbetori i fixed this issue oweride style FullscreenDialog
> ![Снимок](https://user-images.githubusercontent.com/23016311/90286043-af353700-de7d-11ea-9f5f-fbf994e99544.PNG)

Glad you found a fix!

**Comment by erkie** [comment]
Here it is typed out so it can be copy pasted:

```xml
<style name="Theme.FullScreenDialog">
  <item name="android:windowNoTitle">true</item>
  <item name="android:windowIsFloating">false</item>
  <item name="android:windowBackground">@android:color/transparent</item>
  <item name="android:statusBarColor">@android:color/transparent</item>
  <item name="android:navigationBarColor">@android:color/transparent</item>
</style>
```

**Comment by SarvaDev-123** [comment]
> @cbetori i fixed this issue oweride style FullscreenDialog
> ![Снимок](https://user-images.githubusercontent.com/23016311/90286043-af353700-de7d-11ea-9f5f-fbf994e99544.PNG)

but this code change to be 3 icon color also. How to change the 3 icon colors does not any effect on the android device.
