### ISSUE TITLE
Kotlin UI components not work with React-Native

### ISSUE THREAD

**Issue by whalemare** [facebook/react-native#29548]
When you try implement native view module written in Kotlin, it is not resolved in React-Native via `requireNativeComponent`

## Description
I have my own `ZoomView` implementation in native android part.
I was add this package as described in [docs](https://reactnative.dev/docs/native-components-android). When JS **debugger** connected to application, **module resolves correctly**, but when we run release version (or without attached debugger on JS side), it is not found. 

I research native part of `requireNativeComponent` and see, that my implementation was successfully founded in native, but not resolved in JS.

<img width="942" alt="Снимок экрана 2020-08-02 в 12 41 21" src="https://user-images.githubusercontent.com/9128731/89120246-01ba3f00-d4df-11ea-954d-152990f352e3.png">

When we change implementation of `ViewPackage` from Kotlin to Java, it is resolved via `UIManager`
```js
import { UIManager } from 'react-native'
console.log('UIManager[`ZoomView`] = ', UIManager['ZoomView']) // Kotlin implementation
console.log('UIManager[`ZoomViewJ`] = ', UIManager['ZoomViewJ']) // Java implementation
```
<img width="589" alt="Снимок экрана 2020-08-02 в 14 37 47" src="https://user-images.githubusercontent.com/9128731/89122148-44841300-d4ef-11ea-9ee5-b6754302e543.png">

## React Native version:
```
System:
    OS: macOS 10.15.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 232.72 MB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.18.1 - /var/folders/qp/3zxwn9r97fq7fd4wb0jfq5tm0000gn/T/yarn--1596368299776-0.8437399664033203/node
    Yarn: 1.22.4 - /var/folders/qp/3zxwn9r97fq7fd4wb0jfq5tm0000gn/T/yarn--1596368299776-0.8437399664033203/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v10.18.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.4 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 28.0.3, 29.0.0, 29.0.2, 29.0.3
      System Images: android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_232 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
1. Create react-native app
2. Add own implementation of UI module on Kotlin
3. Try to access it via `requireNativeComponent`
4. **Here you receive crash when try to use it view** 
```
Invariant Violation: requireNativeComponent: "ZoomViewJ" was not found in the UIManager.
```
5. Run debug mode via dev tools window in android emulator
6. Try to access this view again and crash disappear. 

## Expected Results
UI module written in Kotlin resolves correctly in step 4.

## Snack, code example, screenshot, or link to a repository:
https://github.com/whalemare/react-native-kotlin-modules

**Comment by whalemare** [comment]
@safaiyeh I was add repo with reproducible demo for this case.

Also, I was add some comments in application describes how to reproduce JS crash in runtime.
You need check `master` and then checkout to `feature/java`. So, just run application in android emulator and feel free to ask questions if needed.

**Comment by chrisglein** [comment]
If I'm reading this right (and let me know if I'm not), at this point this is less of a suspected issue with the platform and more of a question about how to do components with Kotlin. Given that, we try to forward that kind of question to StackOverflow and focus this repo on issues with the platform.
