### ISSUE TITLE
build React Native for android failed

### ISSUE THREAD

**Issue by gsxiang** [facebook/react-native#2954]
./gradlew --info build

Android NDK: Android.mk: Cannot find module with tag 'react' in import path
Android NDK: Are you sure your NDK_MODULE_PATH variable is properly defined ?
Android NDK: The following directories were searched:
Android NDK:
Android.mk:26: *** Android NDK: Aborting.    .  Stop.

**Comment by ppiekarczyk** [comment]
Hi gsxiang, 

do you mind providing more details in your approach? 
- Did you generate a project using `react-native init App`? 
- Are you using node v4?

**Comment by mkonicek** [comment]
Hey @gsxiang, are you building React Native itself?

    git clone ...
    cd react-native

See: https://github.com/facebook/react-native/blob/master/ReactAndroid/README.md

**Comment by gsxiang** [comment]
fixed, in windows it has errors in path, just replace "\" to "/" .

**Comment by mkonicek** [comment]
@gsxiang Awesome! Can you please send a pull request replacing the path?

**Comment by christopherdro** [comment]
@gsxiang There are various commits that fix this problem.
i.e
https://github.com/skillz/react-native/commit/ffd83f9cf07ba74891a2fe7011f2311c0c983733
https://github.com/Tinkerhq/react-native/commit/c3b85c6814aeb3656b98667a62541dd50abe7f88

Any chance you can send us an update on whether this issue has been resolved? Thanks!

**Comment by satya164** [comment]
Closing this issue as it seems to be resolved. Feel free to continue the discussion.

**Comment by Leo-Lang** [comment]
has any sloution for this problem?

**Comment by MITDelian** [comment]
I am also seeing this when I try to build `0.27.0` locally on osx
