### ISSUE TITLE
C++ ABI problems with JSI when JSError exceptions are thrown

### ISSUE THREAD

**Issue by trcoffman** [facebook/react-native#29558]
# Background

My team has been working on integrating JSI into react-native-webview's Android implementation.
We need a synchronous function call into JS in order to solve a bug we were experiencing in our app.
We adopted JSI as it seems like the only way to accomplish this. We are not using hermes, we are using JSC.

Some of the things I've observed with JSError exceptions thrown from libjscexecutor have me really confused and
worried about the soundness of our JSI setup.

# Environment Info
```
System:
    OS: macOS Mojave 10.14.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 614.16 MB / 32.00 GB
    Shell: 5.7.1 - /usr/local/bin/zsh
  Binaries:
    Node: 12.17.0 - /var/folders/zz/bd23sx2d6ssbtrctqgb18wk00000gp/T/yarn--1596497399010-0.6608888600082659/node
    Yarn: 1.19.2 - /var/folders/zz/bd23sx2d6ssbtrctqgb18wk00000gp/T/yarn--1596497399010-0.6608888600082659/yarn
    npm: 6.14.5 - ~/src/react-native-webview/node_modules/.bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /Users/tyler.coffman/.rvm/gems/ruby-2.6.3/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 25, 27, 28, 29
      Build Tools: 23.0.1, 23.0.2, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 27.0.3, 28.0.3, 29.0.2, 29.0.3
      System Images: android-28 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_212 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: ^4.8.0 => 4.8.0
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found
✨  Done in 3.79s.
```

# Our build setup for using JSI from react-native-webview

## Versions

react-native: 0.62.2
Android NDK: r19c

## Linking against libjscexecutor.so from react-native

Our library libreactnativecommunity-webview.so links against libjscexecutor.so in order to get all the symbols
we need to use JSI.
Before build, we have a gradle task that extracts libjsiexecutor.so from the react-native AAR

## Including our own patched <jsi/jsi.h> header

We took the jsi.h header from react-native 0.62.2 and copied it into our project, then we backported this fix into it:
<https://github.com/facebook/react-native/commit/e566c7ec7b0015e4e5e6ad92247a6357eb861d4f>

Without the declarations of the virtual destructors, we could not catch JSError exceptions.
They would fall through to the catch-all handler.

# Without the patched header, JSExceptions cannot be caught except by catch-all handler

When I began testing out error handling in our JSI C++ code, I was very surprised that the catch-all \`catch (&#x2026;)\`
handler was running instead of the \`} catch (const std::exception& e) {\` handler.
This led me to discovering that the lack of a virtual destructor declaration in jsi.h was making JSError non catchable
I suspect because libreactnativecommunity-webview.so had its own duplicate typeinfo for JSError. Declaring the virtual
destructors without providing an implementation I believe led to libreactnativecommunity-webview.so getting the typeinfo
and vtables from libjscexecutor.so.

The patched header let us at least catch JSError, but doesn't solve all issues, as the next section will discuss.

# JSError cannot be caught as std::exception!!!

The most concerning thing to me is that the JSError thrown by libjscexecutor.so cannot be caught as an std::exception
from libreactnativecommunity-webview.so. They are both set up to dynamically link the STL libc++<sub>shared.so</sub>, so I'm
completely flummoxed about why this doesn't work. These exceptions can only be caught with a \`catch (&#x2026;) \` handler.

Something seems off about how all these libraries are linked together if this isn't working.

# Building RN from source doesn't fix the problem

I tried building RN from source so that everything was built with the same exact NDK version, and I still couldn't
catch JSError as an std::exception.

# If NDK r21d NDK is used, the exceptions cannot be caught AT ALL. Immediate crash

Another problem I was running into is that if NDK 21.3 (r21d) was used, the JSError exception wasn't catchable even by 
the catch-all \`catch (&#x2026;)\` handler. The program would immediately terminate with a SIGABRT.
What's really strange is that even when building RN 0.62.2 from source with r21d, I'd still run into this issue. I'm really
confused by 2 .so libraries built with the same toolchain and flags not being able to throw exceptions from one binary to the other
without a SIGABRT happening, especially when this isn't an issue with earlier NDK versions&#x2026;

# Reproducing this issue

Check out this branch of react-native-webview and build the example app for android:
<https://github.com/appfolio/react-native-webview/tree/abi-issues>

When you click a link in the webview under the Alerts section, you'll see the app crash. If you look in logcat you'll see this:

```
2020-08-03 16:09:48.467 20685-20685/com.example E/AndroidRuntime: FATAL EXCEPTION: main
  Process: com.example, PID: 20685
  java.lang.Error: Unknown exception type
      at com.reactnativecommunity.webview.jsi.WebViewJsiInterface.onShouldStartLoadWithRequest(Native Method)
      at com.reactnativecommunity.webview.RNCWebViewManager$RNCWebViewClient.shouldOverrideUrlLoading(RNCWebViewManager.java:807)
      at com.reactnativecommunity.webview.RNCWebViewManager$RNCWebViewClient.shouldOverrideUrlLoading(RNCWebViewManager.java:838)
      at org.chromium.android<sub>webview.AwContentsClientBridge.shouldOverrideUrlLoading</sub>(chromium-TrichromeWebViewGoogle.aab-stable-1:16)
      at android.os.MessageQueue.nativePollOnce(Native Method)
      at android.os.MessageQueue.next(MessageQueue.java:336)
      at android.os.Looper.loop(Looper.java:197)
      at android.app.ActivityThread.main(ActivityThread.java:8016)
      at java.lang.reflect.Method.invoke(Native Method)
      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
```

The fact that we get the java.lang.Error instead of java.lang.RuntimeException indicates that the exception handler for std::exception did not execute.

**Comment by trcoffman** [comment]
> ⚠️	Missing Environment Information
> ℹ️	Your issue may be missing information about your development environment. You can obtain the missing information by running `react-native info` in a console.

I added my environment info

**Comment by mrousavy** [comment]
Hi! Sorry, I can't help you with your issue, but I wanted to ask you if you managed to "include" the RN JSI .aar in your .aar?

I'm creating a library which depends on another .aar (react-native JSI .aar, and react-native-reanimated .aar), and I'm not an Android export - but it seemed to me like it was impossible to include an .aar that lives on the end-user's machine in my .aar without me including a copy of the whole .aar in my .aar 🤔

**Comment by iamyellow** [comment]
@trcoffman I came across this issue since we're getting SIGABRT (on hermes/android) and SIGSEGV (on jsc/android) as soon as we throw a JSError from our jsi based library. Everything works on iOS, btw.
FTR, we're compiling using NDK r24 (since I'm on a Apple M1) linking against `jsi`, `fbjni` and `reactnativejni` shared libs extracted from RN 0.69.
Did you ever find a solution for this?

**Comment by iamyellow** [comment]
FTR the problem was compiling r24. prebuilt rn libs are compiled with r21. so always always always keep using the same version of ndk. actually is in the docs:
"All libraries should be generated with the same NDK version."
https://developer.android.com/ndk/guides/common-problems
