### ISSUE TITLE
Failure [INSTALL_FAILED_VERSION_DOWNGRADE] on Android

### ISSUE THREAD

**Issue by lisichka999** [facebook/react-native#29568]
## Description
I am getting Failure [INSTALL_FAILED_VERSION_DOWNGRADE] error when trying to install my application on device.
If I do clean install  and not upgrade the installation does succeeded, but I need to release new version for upgrade.

## React Native version:
61
## Platform
Android

## Steps To Reproduce
Not changes were made

**Comment by Krizzu** [comment]
This is not RN issue - more like mistake when versioning your app. [Here're docs about it](https://developer.android.com/studio/publish/versioning). (tl;dr: make sure you bump `versionCode` in `app/build.gradle` when doing a release - `versionCode` is to determine if app is newer than previous one.).

**Comment by raikk** [comment]
that's an issue that happened to me. Please check if you already have installed it and then trying to install an app of the same package name (e.g of com.rnexample).

Remove the previous app then install.

**Comment by Mingyang-Li** [comment]
@raikk I've been stuck on this for days, full error log here (expires in 6 days) - https://privatebin.at/?3589145cf3630d25#CEFYUMchDLVVJy1zFhPutVuCjz7mMMqTTLoFh8f5e93k

Methods tried but didn't resolve my issue
1. Restart PC
2. Re-installed node modules
3. Cleaned android build cache
4. Deleted .gradle folder and re-generated
5. Reinstalled android studio
6. Re-cloned repo
7. Changed android build version from 30 to 31
8. Removed `react-native-cli` from global using `npm uninstall react-native-cli -g`
9. Wiped all my emulators data
10. Added more memory to android virtual device

I didn't make any changes to the repo or local dev env, build fails simply began on a random day I started working...

It's driving me nuts, any direction / advice would be appreciated

**Comment by cortinico** [comment]
Closing as it's a stale issue + the `INSTALL_FAILED_VERSION_DOWNGRADE` is an Android problem and is unrelated to React Native per se.

The first answer on stackoverflow explains why this is happening:
https://stackoverflow.com/questions/13808599/android-emulator-installation-error-install-failed-version-downgrade

**Comment by LuizFBrisighello** [comment]
> that's an issue that happened to me. Please check if you already have installed it and then trying to install an app of the same package name (e.g of com.rnexample).
> 
> Remove the previous app then install.

Thanks! I have a product flavor using the same `applicationId`

**Comment by gersonmontenegro** [comment]
> I've been stuck on this for ages, full error log here (expires in 6 days) - https://privatebin.at/?3589145cf3630d25#CEFYUMchDLVVJy1zFhPutVuCjz7mMMqTTLoFh8f5e93k
> 
> Methods tried but didn't resolve my issue
> 
> 1. Restart PC
> 2. Ran `cd android` then `gradlew clean` / `gradlew cleanBuildCache`
> 3. Re-installed node modules
> 4. Cleaned android build cache
> 5. Deleted `/app/.gradle` folder and re-generated
> 6. Deleted `/app/build` folder and re-generated
> 7. Reinstalled android studio
> 8. Re-cloned repo
> 9. Changed android build version from 30 to 31
> 10. Removed `react-native-cli` from global using `npm uninstall react-native-cli -g`
> 11. Wiped all my emulators data
> 12. Added more memory to android virtual device
> 13. Reinstalled yarn
> 
> I didn't make any changes to the repo or local dev env, build fails simply began on a random day I started working...
> 
> It's driving me nuts, any direction / advice would be appreciated

I went just until step 6, and then it worked :-)

**Comment by alainib** [comment]
how to let `adb install -r -d abc.apk` be runned while doing  

`yarn run android:envdev-debugbuild --active-arch-only`
