### ISSUE TITLE
Build release app ios be struct.

### ISSUE THREAD

**Issue by lehuydev2203** [facebook/react-native#29565]
<img width="821" alt="Screen Shot 2020-08-04 at 11 06 51 PM" src="https://user-images.githubusercontent.com/41155784/89317146-311ba800-d6a7-11ea-953f-01d26362448a.png">

## Description
Build IOS Archive bi error warning in here...

## React Native version: 
System:
    OS: macOS 11.0
    CPU: (4) x64 Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
    Memory: 1.35 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.13.0 - /usr/local/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  Languages:
    Java: 13.0.1 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Product > Archive

**Comment by rectified95** [comment]
It'd be helpful if you provided more context, eg. the env info, the actual build command, some more of the build output etc..

**Comment by oleksandr-dziuban** [comment]
This is the reason: 
https://github.com/facebook/react-native/pull/29477
Pr is raised for this, we need to merge it ASAP
