### ISSUE TITLE
Network error: the network request failed on some phone brand and POST type requests

### ISSUE THREAD

**Issue by ththugues44** [facebook/react-native#29566]
## Description
Hello

Our application is in production and has problems for POST type requests. On some phone brands and all android versions (5, 6, 7,8,9,10). and on the other hand the Post type requests work very well on other phones and all android version (5,6,7,8,9,10)

The exact error produced is: Error · Error: Network error: Network request failed.

React native command result:

Different solutions already tested:

- By default, access to our backend is via https using cloudflare. I even thought that it could be an https certificate problem, I changed cloudflare to use a certificate from
 Let's Encryptletsencrypt, until then we have the same problem.

We figured this was a problem with the https protocol and decided on http and added to AndroidManifest.xml the directive:

```
<android application: usesCleartextTraffic = "true">
</application>
```

despite all this we have the same problem namely the POST type request are not functional on some brands of phone and any android version (5,6,7,8,9,10)

Thank you for any help in relation to this problem because at this time we already no longer block more than 1200 Registrations on our Mobile application.

## React Native version:
```
System:
    OS: Linux 4.19 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (4) x64 Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz
    Memory: 761.15 MB / 11.65 GB
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 10.15.2 - /usr/bin/node
    Yarn: 1.17.3 - /usr/bin/yarn
    npm: 6.14.5 - /usr/bin/npm
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-rename: 2.4.1
```

**Comment by chrisglein** [comment]
Related? #28551

**Comment by andresmtz98** [comment]
We have facing the same problem also using GET method. Some phones (Android e iOS) doesn't work.

**Comment by flyskywhy** [comment]
[fixed `TypeError: Network request failed` when upload file to http not https with Android debug builds](https://github.com/facebook/react-native/issues/33217#issuecomment-1159844475)
