### ISSUE TITLE
this._calllisteners.bind

### ISSUE THREAD

**Issue by AlessioCamm** [facebook/react-native#29561]
After I try to install unit test and babel, I got this error : 

![Screenshot_1596542817](https://user-images.githubusercontent.com/22292009/89291990-d315a300-d65b-11ea-8458-adb608a77223.png)

I also try `react-native start --reset-cache`, but not working...

### Informations
**System**:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
    Memory: 3.08 GB / 15.90 GB
**Binaries**:
    Node: 8.11.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
**SDKs**:
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28, 29
      Build Tools: 23.0.1, 23.0.2, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.2, 28.0.3, 29.0.0        
      System Images: android-22 | Google APIs Intel x86 Atom, android-24 | Google APIs Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-25 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, 
android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel 
x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
**IDEs**:
    Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6392135
**npmPackages**:
    react: ^16.9.0 => 16.12.0
    react-native: ^0.60.5 => 0.60.6

**Comment by riadhriadh** [comment]
this.callListeners.bind(this);

**Comment by AlessioCamm** [comment]
A simple `npm start --reset-cache` work for me
