### ISSUE TITLE
Type error problem after updating expo version from 36 to 38

### ISSUE THREAD

**Issue by HoWonJang** [facebook/react-native#29574]
I updated the expo version to 38. When I was 36, the app worked normally, but an error occurs in the image. I tried the npm intall and other methods, but they were not solved. How can I solve this problem?
![update error](https://user-images.githubusercontent.com/49952957/89507148-13fdeb00-d807-11ea-9c18-abc30cbb733a.jpg)
[my app file.zip](https://github.com/facebook/react-native/files/5033416/my.app.file.zip)
![info](https://user-images.githubusercontent.com/49952957/89510284-532e3b00-d80b-11ea-920c-480429f54ec4.PNG)

**Comment by HoWonJang** [comment]
![info](https://user-images.githubusercontent.com/49952957/89509324-24fc2b80-d80a-11ea-9fad-62aa7e714f98.PNG)

**Comment by safaiyeh** [comment]
Hi @HoWonJang for Expo related issues, please file an issue at their repo https://github.com/expo/expo. Thanks!
