### ISSUE TITLE
Upgrading to 0.63.1 version android app is lagging

### ISSUE THREAD

**Issue by MahmudHasanMenon** [facebook/react-native#29589]
I have recently upgraded my react-native project from 0.59 version to 0.63.1(latest) version. I have disabled hermes engine and configure everything as documented. My app is working fine on iOS but in android my app is performing slow. every UI event such as touch, navigation take 2s-3s delay on release build than before and lagging. Is there anyone who has faced same kind of issue? How you have solved this?
Note: I am using react-native-firebase for push notification and deep linking.

react-native: 0.63.1 
react: 16.3
react-navigation: v5 
Node.js: 12.3.1

**Comment by ahmaddehnavi** [comment]
first, check the FPS (from developer menu)
if you have a lot of FPS drop then you can use some tools like `rn-snoopy` to find the issue.
in my case, it was related to some usage of react-native-animatable and I had 30 PFS drop all the time on android and when I disable that animation it came back to 60PFS. I don't know why it causes a lot of FPS drop even with native animation driver

**Comment by mdfprod** [comment]
We're having the same problem and don't have any FPS drop, any other ideas how to solve this?

**Comment by rahamin1** [comment]
Has anybody found a solution?

**Comment by rahamin1** [comment]
> Has anybody found a solution?

Not me
