### ISSUE TITLE
Could not connect to development server

### ISSUE THREAD

**Issue by Derewith** [facebook/react-native#29587]
Hello there,
i can't understand why the MetroBundler it's not working.

## Description
As soon as i start the app, it throws me this error that won't let me connect to my metro bundler. I checked everything, from the port 8081 status and i don't understand why.
Via the simulator it's working, but with my real device it's not. 
_I have an iPhone XR with iOS 13.6_
## React Native version:
```
System:
    OS: macOS 10.15.5
    CPU: (4) x64 Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz
    Memory: 442.25 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.20.1 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.7 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 27.0.3, 28.0.3, 29.0.2, 29.0.3, 30.0.0, 30.0.1
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  Languages:
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.0 => 0.62.0 
  npmGlobalPackages:
    *react-native*: Not Found
```
## Steps To Reproduce
I tried this steps

1. yarn start --reset-cache
2. yarn start
3. cd ios && pod cache clean --all && pod deintegrate && rm Podfile.lock && pod install
4. rebuild from Xcode and clean the build folder
5. rm -rf node_modules and yarn to install the packages again

## Expected Results
The app should connect to the MetroBundler.

## Screenshot:
![IMG_7820](https://user-images.githubusercontent.com/2650542/89661801-6e647d80-d8d3-11ea-9dd5-1d91b2ffec49.PNG)

**The ip you see in the image is the right one.**

**Comment by safaiyeh** [comment]
Hi @Derewith is your physical device on the same network as where the metro server is running?

**Comment by Derewith** [comment]
Yeah it is on the same network

**Comment by jdegger** [comment]
Might be related to https://github.com/facebook/react-native/issues/29433 which is also unresolved

**Comment by riadhriadh** [comment]
checked info.plist

**Comment by Derewith** [comment]
@riadhriadh what do you mean?

**Comment by riadhriadh** [comment]
@Derewith cheked 
this issues https://stackoverflow.com/questions/38501012/is-it-safe-to-add-localhost-to-app-transport-security-ats-nsexceptiondomains

**Comment by Derewith** [comment]
<img width="282" alt="Schermata 2020-08-11 alle 09 42 00" src="https://user-images.githubusercontent.com/2650542/89870980-f76f0380-dbb6-11ea-9069-d761e2bfaa60.png">
@riadhriadh this is my info.plist and i think it's everything okay with it..

**Comment by riadhriadh** [comment]
https://stackoverflow.com/questions/42064283/could-not-connect-to-react-native-development-server-on-android

**Comment by Derewith** [comment]
@riadhriadh i'm on iOS so i'cant test on android what's going on

**Comment by Derewith** [comment]
Any updates?

**Comment by safaiyeh** [comment]
@Derewith can you provide a repro that consistently does this so I can take a look?

**Comment by timbielawski** [comment]
I was having similar issues, thought it must be cached versions 
so cleared everything

- rm -rf node_modules 
- rm -rf $TMPDIR/metro-* && rm -rf $TMPDIR/react-* && rm -rf $TMPDIR/haste-*
- watchman watch-del-all
- npm install
- npm start -- --reset-cache

It works!

**Comment by lorenzorheinicke** [comment]
> * rm -rf node_modules
> * rm -rf $TMPDIR/metro-* && rm -rf $TMPDIR/react-* && rm -rf $TMPDIR/haste-*
> * watchman watch-del-all
> * npm install
> * npm start -- --reset-cache

Thank you @timbielawski, this worked for. I also had to reset the iOS simulator in order to get it to work.

**Comment by my-name-is-nheo** [comment]
My devices are running on the same network as the metro bundler. Android connects well with it, but there is always an issue with iOS devices. I'm first building the app with XCode. XCode has its own output log, but I prefer to view the logs in one window.

**Comment by lukewlms** [comment]
This worked: Dev Menu in app -> Configure Bundler, and set to my Mac's specific address.

IP: 192.168.0.x
Port: 8081
Entrypoint: src/index (we have a custom path)

> Type into terminal `ifconfig` and under `en0` you will find your ipaddress next to `inet` (and before `netmask`).

Source: [this comment].

**Comment by marcosdourado** [comment]
There seems to be a problem with watchman, removing it I was able to connect.

**Comment by eyalyoli** [comment]
`npm start -- --reset-cache` helps!

**Comment by scgrossman** [comment]
> There seems to be a problem with watchman, removing it I was able to connect.

I did `brew uninstall watchman` and it resolved the issue, thanks @marcosdourado . I'm not quite sure why or how it resolved it. A mystery for another day.

**Comment by Gregoirevda** [comment]
I confirm `brew uninstall watchman` after a macOS update to Monterey worked

**Comment by perinp150363** [comment]
> I was having similar issues, thought it must be cached versions so cleared everything
> 
>     * rm -rf node_modules
> 
>     * rm -rf $TMPDIR/metro-* && rm -rf $TMPDIR/react-* && rm -rf $TMPDIR/haste-*
> 
>     * watchman watch-del-all
> 
>     * npm install
> 
>     * npm start -- --reset-cache
> 
> 
> It works!

This is it thanks so much,
Phil

**Comment by franekantoni** [comment]
> This worked: Dev Menu in app -> Configure Bundler, and set to my Mac's specific address.
> 
> IP: 192.168.0.x Port: 8081 Entrypoint: src/index (we have a custom path - just 'index' is more common)
> 
> > Type into terminal `ifconfig` and under `en0` you will find your ipaddress next to `inet` (and before `netmask`).
> 
> Source: [this comment].

Thank you! This is the only solution that worked for me.

**Comment by panda919** [comment]
> 

![image](https://user-images.githubusercontent.com/25161426/153501549-2d8acb21-4b33-47d3-8229-d16a5d1b0490.png)
Or I used this solution, and it worked for me .
