### ISSUE TITLE
Textinput dose not auto switch text direction RTL & LTR on ios

### ISSUE THREAD

**Issue by Abdullah-Shamhan** [facebook/react-native#29593]
Textinput doesn't change input direction based on keyboard language, instead it's based on system language.. 
It works fine on android ,the issue is on IOS only.

## Expected Results
Auto switch writing direction between RTL and LTR

react native 0.62.2

**Comment by aliraza-noon** [comment]
I am also facing this issue textinput placeholder always aligns to left even for rtl layout

**Comment by MusabBasheer** [comment]
I have the same problem
