### ISSUE TITLE
TextInput does not get fontSize and fontFamily styles when set a value for defaultValue prop

### ISSUE THREAD

**Issue by Anahita-Fakhravar** [facebook/react-native#29597]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
When I set a text for defaultValue or value props in textInput it does not get fontFamily and fontSize styles.

## System:
    OS: Windows 10 10.0.18362
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
    Memory: 1.72 GB / 7.88 GB
  Binaries:
    Node: 12.8.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.21.1 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      Android NDK: 21.0.6113669
  IDEs:
    Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6241897
  Languages:
    Java: Not Found
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
1. Create a textInput with fontSize and fotFamily styles
2. Set a value for DefaultValue

## Expected Results
When I set a default value for textInput the text style should be as I defined in style prop.

##  code example
    <TextInput
                        defaultValue={'my address is...'}
                        style={{fontSize:responsiveFontSize(1.5),fontFamily:myFontFamily.bold1}}
                        placeholder={Strings.addAddress}
                        autoCorrect={false}
                        underlineColorAndroid="transparent"
                        multiline={true}
                        maxLength={250}
                        blurOnSubmit={true}
                        onFocus={() => setFocus6(true)}
                        onBlur={() => setFocus6(false)}
                        ref={input => useRef.seven = input}
                        onChangeText={(value) => AddressDataModel.setAddress(value)}/>

**Comment by CXZ7720** [comment]
Did you solved the problem? I have same problem like this.
When I change the value prop dynamically, fontFamily reset to default and system font style overrides.
