### ISSUE TITLE
How to insert img between strings? 

### ISSUE THREAD

**Issue by ShumGG** [facebook/react-native#29600]
Hi, I'm new in react-native and I'm making a small notebloc to get started, the problem now is that I want to allow the user add an img while writing and then jump to the next line and continue to write, something like this:

![LywV0](https://user-images.githubusercontent.com/64358196/89744065-e4d3cc00-dadb-11ea-8c25-f8bb53ffb3d7.png)

For that I have this structure for now : 

```
add_Image = () => {
   this.setState({content: this.state.content + "\n"+ "\n"+ "\n"});
    const img = <Image source = {require("../img/ny.png")} style = {{width: 100, height: 100}}></Image>
    this.setState({img:img});
}
render() {
    return (
        <>
        <View> 
            <TextInput style = {this.styles.TextInput_title} placeholder = "Title" multiline = {true} maxLength = {80} value = {this.state.title} onChangeText = {title => this.setState({title: title})}></TextInput>
        </View>
        <View styles = {this.styles.View_text_input_content}>
            <TextInput style = {this.styles.TextInput_content}
            placeholder = "Content" multiline = {true} onChangeText = {content => this.setState({content: content})}>{this.state.content}
            <Text>{this.state.img}</Text>
            </TextInput>
           
        </View>
        <View style = {this.styles.View_add_save_buttons}>
            <Button title = "Add image" onPress = {this.add_Image}></Button>
            <Button title = "Save Changes" onPress = {this.save_Changes}></Button>
        </View>
        <View style = {this.styles.View_back_button}>
            <Button title = "Go back home" onPress = {() => this.props.navigation.navigate("Home")}></Button>
        </View>
        </>    
    );
}
```
The result is this:

![gz1iA](https://user-images.githubusercontent.com/64358196/89744217-67a95680-dadd-11ea-899e-e1be93e251e8.png)

So when I type this is how looks:

![rKaop](https://user-images.githubusercontent.com/64358196/89744231-890a4280-dadd-11ea-9f77-70b951a8a556.png)

For each char it comes with a zero, I know the way I'm doing this isn't the right way, but for the moment this is the only way that I could figure out, hope can help me :)

**Comment by riadhriadh** [comment]
one must use  flexDirection
https://reactnative.dev/docs/flexbox
