### ISSUE TITLE
Background process not work after app closed or kill from background or foregorund

### ISSUE THREAD

**Issue by vickypathak123** [facebook/react-native#29601]
react: 16.9.0 => 16.9.0 
react-native: 0.61.4 => 0.61.4 

For IOS :--

I'm use many library for Run background processing.

I'm create notification reminder features in my app.

like if i'm select 02:00 pm to 03:00 pm and 10 notification come in this time period but when app closed or remove from background and foreground notification not work properly.

Please message if any one know the solution.

Thank you

**Comment by riadhriadh** [comment]
use firebase cloud messaging
