### ISSUE TITLE
Keyboard keeps closing

### ISSUE THREAD

**Issue by troubleshootdev** [facebook/react-native#29619]
## Description
[https://media2.giphy.com/media/JqE49ekO0ftB7SFYSa/giphy.gif](url)
It exits the keyboard after 1 character is pressed.

## React Native version:
info Fetching system and libraries information...
System:
    OS: macOS 10.15.5
    CPU: (8) x64 Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz
    Memory: 19.68 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.13.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.12.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.4 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  Languages:
    Java: 13.0.2 - /usr/bin/javac
    Python: 2.7.15 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: ~16.11.0 => 16.11.0 
    react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found

## Steps to reproduce:
1. ios
2. Press register
3. Press Useless placeholder
4. Press a letter on the popup keyboard

## Expected Results
I want to enter as many characters as possible until I press enter on the keyboard.

## Snack
https://snack.expo.io/@troubleshootdev/d8dece

**Comment by chrisglein** [comment]
Well that's extremely obnoxious to use :O 

If you just extract that component out for a state-driven TextInput, it works fine. For example this:
```
function HomeScreen() {
  let [value, setValue] = React.useState('default');
  return (
    <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
      <TextInput style={{ height: 40, borderColor: 'gray', borderWidth: 1 }} value={value} onChangeText={(newValue => setValue(newValue))}></TextInput>
      <Home />
    </View>
  );
}
```
Something is different about the way that's hosted that causes the keyboard to flip out. Trying to get this to min-repro... what is it that triggers that keyboard closing behavior?

Of note, that Snack doesn't load in Android because you're hosting a whole component inside a Text. If I remove that <Text> wrapper it also works in iOS.

I think that's you're issue?

**Comment by troubleshootdev** [comment]
> Well that's extremely obnoxious to use :O
> 
> If you just extract that component out for a state-driven TextInput, it works fine. For example this:
> 
> ```
> function HomeScreen() {
>   let [value, setValue] = React.useState('default');
>   return (
>     <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
>       <TextInput style={{ height: 40, borderColor: 'gray', borderWidth: 1 }} value={value} onChangeText={(newValue => setValue(newValue))}></TextInput>
>       <Home />
>     </View>
>   );
> }
> ```
> 
> Something is different about the way that's hosted that causes the keyboard to flip out. Trying to get this to min-repro... what is it that triggers that keyboard closing behavior?
> 
> Of note, that Snack doesn't load in Android because you're hosting a whole component inside a Text. **If I remove that wrapper it also works in iOS. Does that unblock you?**
> 
> I think that's you're issue?

You're right. My Register function in 'My app.js' had a wrapped component like 
<Text><Register/></Text>.
I removed the <Text></Text> like you said and it fixed my keyboard issue for both iOS and Android! Thanks a lot!
