### ISSUE TITLE
Unable to find module for UIManager

### ISSUE THREAD

**Issue by LixingY** [facebook/react-native#29616]
Unable to find module for UIManager
Run this error
RN 0.62.2

**Comment by LixingY** [comment]
System:
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
Binaries:
    Node: 14.6.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.7 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman

**Comment by LixingY** [comment]
System:
CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
SDKs:
iOS SDK:
Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
Binaries:
Node: 14.6.0
Yarn: 1.22.4
npm: 6.14.7
Watchman: 4.9.0

**Comment by mrousavy** [comment]
Please give more information about your problem. Try running:

```sh
cd ios; pod install; cd ..
```

**Comment by safaiyeh** [comment]
Closing as empty template.

@LixingY if you still have an issue to file, please file a new one with all fields in the template filled out. Thanks!
