### ISSUE TITLE
App crashes in Samsung Galaxy J7 (SM-J700F)  /system/lib/libart.so (art_quick_imt_conflict_trampoline+7)

### ISSUE THREAD

**Issue by john1jan** [facebook/react-native#29620]
App crashes in Samsung Galaxy J7 (SM-J700F)  

## React Native version:
System:
    OS: macOS Mojave 10.14.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 8.93 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 13.10.1 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.7.5 - /Users/johnfrancis/.rvm/gems/ruby-2.4.2/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 23.0.1, 26.0.2, 28.0.3
      System Images: android-19 | Intel x86 Atom, android-19 | Google APIs ARM EABI v7a, android-19 | Google APIs Intel x86 Atom, android-21 | ARM EABI v7a, android-22 | Google APIs Intel x86 Atom, android-24 | ARM 64 v8a, android-25 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64
      Android NDK: 17.2.4988734
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_191 - /usr/bin/javac
    Python: 2.7.10 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
## Steps To Reproduce
Launch the app in Samsung Galaxy J7

`08-11 17:44:04.151 9439-9439/? A/libc: Fatal signal 11 (SIGSEGV), code 2, fault addr 0x3561d944 in tid 9439 (llion.groww.uat)
08-11 17:44:04.211 2173-2173/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
08-11 17:44:04.211 2173-2173/? A/DEBUG: Build fingerprint: 'samsung/j7eltexx/j7elte:6.0.1/MMB29K/J700FXXU4BRL2:user/release-keys'
08-11 17:44:04.211 2173-2173/? A/DEBUG: Revision: '0'
08-11 17:44:04.211 2173-2173/? A/DEBUG: ABI: 'arm'
08-11 17:44:04.211 2173-2173/? A/DEBUG: signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x3561d944
08-11 17:44:04.291 2173-2173/? A/DEBUG:     r0 70879784  r1 12f3ce20  r2 0025e79c  r3 f1369070
08-11 17:44:04.291 2173-2173/? A/DEBUG:     r4 0025e79c  r5 12f3ce20  r6 70878dd0  r7 710aaee0
08-11 17:44:04.291 2173-2173/? A/DEBUG:     r8 143458c0  r9 f4a76500  sl ffc57588  fp ffc574fc
08-11 17:44:04.291 2173-2173/? A/DEBUG:     ip f1369070  sp ffc57480  lr 745d8705  pc f46407f8  cpsr 000d0030
08-11 17:44:04.301 2173-2173/? A/DEBUG: backtrace:
08-11 17:44:04.301 2173-2173/? A/DEBUG:     #00 pc 000ea7f8  /system/lib/libart.so (art_quick_imt_conflict_trampoline+7)
08-11 17:44:04.301 2173-2173/? A/DEBUG:     #01 pc 02fd3703  /system/framework/arm/boot.oat (offset 0x2fa5000)
08-11 17:44:06.311 2618-3040/? E/NativeCrashListener: Exception dealing with report
    android.system.ErrnoException: read failed: EAGAIN (Try again)
        at libcore.io.Posix.readBytes(Native Method)
        at libcore.io.Posix.read(Posix.java:169)
        at libcore.io.BlockGuardOs.read(BlockGuardOs.java:230)
        at android.system.Os.read(Os.java:367)
        at com.android.server.am.NativeCrashListener.consumeNativeCrashData(NativeCrashListener.java:240)
        at com.android.server.am.NativeCrashListener.run(NativeCrashListener.java:138)
08-11 17:44:06.331 2173-2173/? A/DEBUG: Tombstone written to: /data/tombstones/tombstone_05
08-11 17:44:06.331 2173-2173/? E/DEBUG: AM write failed: Broken pipe
`

Attached detailed crash report
[SAMSUNCRASH.txt](https://github.com/facebook/react-native/files/5056872/SAMSUNCRASH.txt)

**Comment by safaiyeh** [comment]
Hi @john1jan we would need a bit more information about the crash. Could you provide a repro that demonstrates the issue you are having?

**Comment by riadhriadh** [comment]
you been using : react-native-mapbox-gl

**Comment by john1jan** [comment]
nope we are not using:  react-native-mapbox-gl

**Comment by john1jan** [comment]
Fixed it 
We had to enable 
`        android:hardwareAccelerated="true"
`
In application tag of AndroidManifest.xml
