### ISSUE TITLE
Error with @jest/core with no code change. Unable to resolve module `os` from `node_modules/@jest/core/build/SearchSource.js`

### ISSUE THREAD

**Issue by RG-404** [facebook/react-native#29628]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Error started occurring while testing the application on Android.
The development server returned response error code 500.
error: Error: Unable to resolve module `os` from `node_modules/@jest/core/build/SearchSource.js`: os could not be found within the project.

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules: rm -rf node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*

## React Native version:
System:
    OS: Linux 5.4 KDE neon 5.19
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
    Memory: 703.98 MB / 11.59 GB
    Shell: 5.4.2 - /bin/zsh
  Binaries:
    Node: 14.6.0 - /usr/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.14.6 - /usr/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.1
      System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 1.8.0_242-release - /usr/local/android-studio/jre/bin/javac
    Python: 2.7.17 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
  npmGlobalPackages:
    *react-native*: Not Found

## Snack, code example, screenshot, or link to a repository:
Link to  [repo](https://github.com/RG-404/Pharma-Seller/tree/72d1c2d622d0f01b558884b9e8f8fd06d4e26b52)

**Comment by safaiyeh** [comment]
Hi @RG-404 this might be an issue with Metro or Jest, could you create an issue in their repos? The issue board here deals with React Native core issues. Thanks!

**Comment by SINGHPRT** [comment]
Just in case, anybody looking for solution to this issue.
For me, it was due to auto-injection of  IMPORT Statement in my one of reactNative js file as follows:

import { SearchSource } from 'jest';

Not sure, what made it get inserted here, but it was absolutely not deliberately written and served no purpose but crashing the app.

Removing this line fixed the issue.

**Comment by enyawson** [comment]
@SINGHPRT  
Yeah, it worked.  For me, i had to remove an import statement;

import { run } from 'jest';
removing this fixed this.
