### ISSUE TITLE
Metro bundler wont connect after implementing a native module in android

### ISSUE THREAD

**Issue by AE0011** [facebook/react-native#29621]
## Description
I want to user this package https://github.com/FolioReader/FolioReader-Android in react native 
I did that by help of this guide https://reactnative.dev/docs/native-modules-android 
And got access to folioreader functions in js side but after i run project this error appears: (npm run android - debug mode)
![err](https://user-images.githubusercontent.com/37038198/89903887-77b85780-dbfd-11ea-8363-198ff75e055d.PNG)

## React Native version:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i7-4770T CPU @ 2.50GHz
    Memory: 3.06 GB / 15.89 GB
  Binaries:
    Node: 14.4.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.7 - C:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 21, 22, 23, 24, 25, 26, 27, 28, 29, 3, 4, 7, 8
      Build Tools: 19.1.0, 20.0.0, 21.1.2, 22.0.1, 23.0.1, 23.0.2, 23.0.3, 24.0.0, 24.0.1, 24.0.2, 24.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.1, 27.0.2, 27.0.3, 28.0.0, 28.0.1, 28.0.2, 28.0.3, 29.0.0, 29.0.1, 29.0.2, 29.0.3, 30.0.0, 30.0.0
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom_64, android-30 | Google Play Intel x86 Atom
      Android NDK: 16.1.4479499
  IDEs:
    Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6626763
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
  npmGlobalPackages:
    react-native-cli: 2.0.1

## Steps To Reproduce
1. add FolioReader-Android to your android dependencies base on guides 
2. run

**Comment by chrisglein** [comment]
Did you try any other native modules? Did all not work, or just this one?

**Comment by AE0011** [comment]
@chrisglein 

> Did you try any other native modules? Did all not work, or just this one?

Yes I tested another random package and it worked without any problem.

Then I test versions 61, 62 and 63 of react native but I had same problem.

It is weird because I did the same in macbook and it works fine just only this problem happen in windows system

**Comment by AE0011** [comment]
running this repo failed at windows system but worked on mac
https://github.com/Shaaraan/react-native-folioreader
```
git clone ...
yarn bootstrap
yarn example android
```

**Comment by chrisglein** [comment]
My understanding is that Android React Native on Windows definitely has some stability issues. Sometimes this is intermittent and goes away after a restart of the app/emulator and making sure that bundler is running (it could have crashed). May not be anything specific to this module. Is this still an issue for you?

**Comment by fabriziobertoglio1987** [comment]
I don't understand how implementing a native module relates to the Android Emulator connecting to the metro server running on localhost. Seems to me this is not a bug in react-native, but more of a troubleshooting issue. We experienced problems similar in other issues, but they are more appropriate to the repositories metro or react-native-community/cli where this functionalities are mantained, but make sure to write a minimum reproducible example which only uses that dependency before opening issue in those repos.. Thanks a lot :pray:

**Comment by Great-hijack** [comment]
I have same problem.
Recently I used the VGS(Very Good Security) SDK for my app and it works fine with iOS, but Android module doesn't work with Metro server.
This issue is also know for FullStory SDK.
![image](https://user-images.githubusercontent.com/57619523/159458475-9dcd23ce-5942-4914-aabf-1a647fa1716b.png)

Does someone have any solution or guide?
