### ISSUE TITLE
Android TextInput auto Dismiss Keyboard ( release )

### ISSUE THREAD

**Issue by riadhriadh** [facebook/react-native#29625]
Android TextInput auto Dismiss Keyboard

System:
OS: macOS 10.15.3
CPU: (4) x64 Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
Memory: 2.19 GB / 16.00 GB
Shell: 5.7.1 - /bin/zsh
Binaries:
Node: 10.19.0 - ~/.nvm/versions/node/v10.19.0/bin/node
Yarn: 1.22.0 - /usr/local/bin/yarn
npm: 6.13.4 - ~/.nvm/versions/node/v10.19.0/bin/npm
Watchman: 4.9.0 - /usr/local/bin/watchman
Managers:
CocoaPods: 1.9.3 - /usr/local/bin/pod
SDKs:
iOS SDK:
Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
Android SDK:
API Levels: 20, 21, 22, 23, 24, 25, 26, 27, 28, 29
Build Tools: 27.0.3, 28.0.0, 28.0.2, 28.0.3, 29.0.2, 29.0.3, 30.0.0, 30.0.1
System Images: android-24 | Google APIs Intel x86 Atom, android-27 | Android TV Intel x86 Atom, android-27 | Intel x86 Atom, android-27 | Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom_64
Android NDK: Not Found
IDEs:
Android Studio: 4.0 AI-193.6911.18.40.6514223
Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
Languages:
Java: 1.8.0_242 - /usr/bin/javac
Python: 2.7.16 - /usr/bin/python
npmPackages:
@react-native-community/cli: Not Found
react: 16.13.1 => 16.13.1
react-native: 0.63.2 => 0.63.2
npmGlobalPackages:
react-native: Not Found

**Comment by polarisdigitech** [comment]
> Android TextInput auto Dismiss Keyboard
> 
> System:
> OS: macOS 10.15.3
> CPU: (4) x64 Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
> Memory: 2.19 GB / 16.00 GB
> Shell: 5.7.1 - /bin/zsh
> Binaries:
> Node: 10.19.0 - ~/.nvm/versions/node/v10.19.0/bin/node
> Yarn: 1.22.0 - /usr/local/bin/yarn
> npm: 6.13.4 - ~/.nvm/versions/node/v10.19.0/bin/npm
> Watchman: 4.9.0 - /usr/local/bin/watchman
> Managers:
> CocoaPods: 1.9.3 - /usr/local/bin/pod
> SDKs:
> iOS SDK:
> Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
> Android SDK:
> API Levels: 20, 21, 22, 23, 24, 25, 26, 27, 28, 29
> Build Tools: 27.0.3, 28.0.0, 28.0.2, 28.0.3, 29.0.2, 29.0.3, 30.0.0, 30.0.1
> System Images: android-24 | Google APIs Intel x86 Atom, android-27 | Android TV Intel x86 Atom, android-27 | Intel x86 Atom, android-27 | Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom_64
> Android NDK: Not Found
> IDEs:
> Android Studio: 4.0 AI-193.6911.18.40.6514223
> Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
> Languages:
> Java: 1.8.0_242 - /usr/bin/javac
> Python: 2.7.16 - /usr/bin/python
> npmPackages:
> @react-native-community/cli: Not Found
> react: 16.13.1 => 16.13.1
> react-native: 0.63.2 => 0.63.2
> npmGlobalPackages:
> react-native: Not Found

Had this same issue some months ago, found a way around. Didn't occur to me to open an issue then, then I decided to do that today. Was literally about to open and issue then saw yours.

**Comment by riadhriadh** [comment]
@polarisdigitech if you have a solution share

**Comment by polarisdigitech** [comment]
It might depend on how your code is structured. Are you using a `FlatList`

**Comment by polarisdigitech** [comment]
For me, its was the `FlatList` that caused the issue. I switched to using just a `ScrollView`, and the issue stopped. Is your issue happening to only `TextInput`s close to the bottom of the screen?

**Comment by safaiyeh** [comment]
Hi @riadhriadh could you follow the issue template? Thank you

**Comment by glacjay** [comment]
I also have this issue:

```
                <Text style={{ marginRight: 5 }}>车辆编号</Text>
                <TextInput
                  keyboardType="numeric"
                  value={this.state.searchVehicleId}
                  onChangeText={(searchVehicleId) =>
                    this.setState({
                      searchVehicleId: searchVehicleId || null,
                    })
                  }
                  style={{ flex: 1, borderWidth: 1 }}
                />
```

react-native info: (0.61.5)

```
System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz
    Memory: 17.34 GB / 31.90 GB
  Binaries:
    Node: 12.10.0 - D:\temp\yarn--1597578708398-0.212657618420665\node.CMD
    Yarn: 1.22.4 - D:\temp\yarn--1597578708398-0.212657618420665\yarn.CMD
    npm: 6.14.0 - D:\tool\scoop\apps\nodejs-lts\current\bin\npm.CMD
```

![WeChat_20200816193715](https://user-images.githubusercontent.com/292719/90333597-c7ca5c00-dff9-11ea-8357-6cc7bef7fb71.gif)

**Comment by xfeng-github** [comment]
System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
    Memory: 8GB
  Binaries:
    Node: v12.18.2
    Yarn: 1.22.4
    npm: 6.14.5

出现场景是另一个页面goback()，以及选中TextView框后会弹出键盘，但紧接着键盘会自动关闭，出现第一次后第二将不会出现， 以及等待一会首次选中也不会出现

**Comment by riadhriadh** [comment]
@glacjay  @xfeng-github  @polarisdigitech  @safaiyeh 
maybe the problem in the react navigation dependence
https://github.com/react-navigation/react-navigation/issues/8525

**Comment by DonaldGuo** [comment]
> System:
> OS: Windows 10
> CPU: (4) x64 Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
> Memory: 8GB
> Binaries:
> Node: v12.18.2
> Yarn: 1.22.4
> npm: 6.14.5
> 
> 出现场景是另一个页面goback()，以及选中TextView框后会弹出键盘，但紧接着键盘会自动关闭，出现第一次后第二将不会出现， 以及等待一会首次选中也不会出现
> 
> 任意一个TextView都会发生，无关某个特定的TextView

@glacjay 
same issue. I listen the height of content view by onLayout, set a new height to container view by setState when the onLayout callback. If I remove this onLayout, the problem is solved.

**Comment by DonaldGuo** [comment]
> I also have this issue:
> 
> ```
>                 <Text style={{ marginRight: 5 }}>车辆编号</Text>
>                 <TextInput
>                   keyboardType="numeric"
>                   value={this.state.searchVehicleId}
>                   onChangeText={(searchVehicleId) =>
>                     this.setState({
>                       searchVehicleId: searchVehicleId || null,
>                     })
>                   }
>                   style={{ flex: 1, borderWidth: 1 }}
>                 />
> ```
> 
> react-native info: (0.61.5)
> 
> ```
> System:
>     OS: Windows 10
>     CPU: (4) x64 Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz
>     Memory: 17.34 GB / 31.90 GB
>   Binaries:
>     Node: 12.10.0 - D:\temp\yarn--1597578708398-0.212657618420665\node.CMD
>     Yarn: 1.22.4 - D:\temp\yarn--1597578708398-0.212657618420665\yarn.CMD
>     npm: 6.14.0 - D:\tool\scoop\apps\nodejs-lts\current\bin\npm.CMD
> ```
> 
> ![WeChat_20200816193715](https://user-images.githubusercontent.com/292719/90333597-c7ca5c00-dff9-11ea-8357-6cc7bef7fb71.gif)

@glacjay 
same issue. I listen the height of content view by onLayout, set a new height to container view by setState when the onLayout callback. If I remove this onLayout, the problem is solved.

**Comment by glacjay** [comment]
Sorry, solved my problem, by remove `Keyboard.dismiss()` in an event handler. Don't know why it's triggered yet but ...... good luck you guys
