### ISSUE TITLE
Fetching is slow suddenly in android only, working fine after killed application

### ISSUE THREAD

**Issue by rohitEST** [facebook/react-native#29624]
## Description
i am getting an issue in android version(not in iOS) while fetching data, getting proper response sometimes but suddenly data is unable to fetch for 2-4 minutes. Needs to kill the app and restart. Please help me with this, I already wasted 3-4 days.

## React Native version:
System:
    OS: Windows 10 10.0.18362
  Binaries:
    Node: 12.10.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files\nodejs\yarn.CMD
    npm: 6.10.3 - C:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 23, 28, 29
      Build Tools: 23.0.1, 28.0.3, 29.0.3
      System Images: android-27 | Google APIs Intel x86 Atom, android-28 | Intel x86 Atom, android-28 | Intel x86 Atom_64, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6392135
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5

**Comment by sawaca96** [comment]
I'm use ionic capacitor...and same situation ..😂😂😂😂

**Comment by JKKholmatov** [comment]
@rohitEST Did you finde any solution? I also having the same issue

**Comment by JKKholmatov** [comment]
@rohitEST @sawaca96 Did you finde any solution? I also having the same issue
