### ISSUE TITLE
getInitialURL truncates any additional query parameters beyond the first

### ISSUE THREAD

**Issue by jrobber** [facebook/react-native#29630]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Please provide a clear and concise description of what the bug is. Include screenshots if needed.
Please test using the latest React Native release to make sure your issue has not already been fixed: 

Given this url: `myscheme://user/verification?confirm=1596497089568&email=person@gmail.com`
getInitialURL gets a truncated path of `myscheme://user/verification?confirm=1596497089568`.

`Linking.addEventListener('url', (event)=> )` has this same problem.  The `event.url` is also truncated

## React Native version:
Run `react-native info` in your terminal and copy the results here.

System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 589.46 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.7.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.3 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1) Setup a basic app
2) Import Linking and log out results of `getInitialURL()`
3) Open the app with a deep link:
`xcrun simctl openurl booted SCHEME://PAGE?one=1&two=2`

## Expected Results
Describe what you expected to happen.

I should get the full url and not a truncated version.

## Snack, code example, screenshot, or link to a repository:

You can install the react-navigation sample application here:
https://github.com/react-navigation/react-navigation/tree/main/example

Then use this deep link: `xcrun simctl openurl booted rne://127.0.0.1:19000/--/simple-stack/Albums?one=1&two=2`

**Comment by safaiyeh** [comment]
Hi @jrobber thank you for filing the issue! I'll check out the example you linked

**Comment by jpaas** [comment]
This is a fairly serious issue for any apps that rely on deep links with more than one param. Any update on this? We can't release our app with this problem.

**Comment by secret0nodes** [comment]
We're also having this problem and it's a blocker for us.

**Comment by TikiTDO** [comment]
@jrobber Does it behave differently if you run `xcrun simctl openurl booted "rne://127.0.0.1:19000/--/simple-stack/Albums?one=1&two=2"` instead? I was having a similar problem on Android, and calling `adb` with the requested URL in quotes made it so I was getting the entire search string.

**Comment by jrobber** [comment]
@TikiTDO I'll have to test that command. The bigger problem is if someone clicks a link in an email to open it, it comes in truncated.  

We re-worked our endpoints and URLs to inline our parameters to work around this for now. 
IE - `myscheme://user/verification/1596497089568?email=person@gmail.com`

We ensure at most one query parameter is passed at a time

**Comment by safaiyeh** [comment]
That is annoying - I will check this out there shouldn't be constraints on the params

**Comment by safaiyeh** [comment]
@jrobber Could this be a an iOS specific limitation?

I debugged this for a couple hours and could not figure pinpoint the source of the bug. I noticed with `xcrun simctl openurl booted SCHEME://PAGE?one=1&two=2` command it truncates the query param on its own.

![Screen Shot 2021-01-16 at 12 03 17 PM](https://user-images.githubusercontent.com/8675043/104821782-140d0880-57f3-11eb-82c1-3184af5a8178.png)

**Comment by jeanregisser** [comment]
You have to quote the url, see https://askubuntu.com/questions/50898/how-to-skip-the-evaluation-of-ampersand-in-command-line

**Comment by Taylor123** [comment]
@safaiyeh As far as I've seen, it's an issue on Android and not iOS.

As a current work around, I've encoded the `&` for deep links we have control over and decode prior to handling. Still not ideal as it won't necessarily fix externally created deep links

**Comment by TikiTDO** [comment]
@PiPoutch How about if you try `npx uri-scheme open "http://anyurl.test/something?parameter1=1\&parameter2=2" --android` (with the escaped \&), DOES THAT MAKE A DIFFERENCE?

**Comment by PiPoutch** [comment]
@TikiTDO It does indeed, I get all parameters that way. Shouldn't characters in double quotes be interpreted as normal characters?

**Comment by TikiTDO** [comment]
@PiPoutch Most likely there's multiple levels of parsing happening. When you pass something in quotes your shell is going to pass that string as a single argv to the callee. However if the callee happens to use that as an argument into something else, such as if adb passes it to a phone as a shell command, then it may end up doing that entire process a second time based on how that call is implemented.

**Comment by PiPoutch** [comment]
considering uri-scheme is most likely aliasing to xcrun and adb, that's probably what it is indeed

**Comment by mihailapuste** [comment]
Anyone been able to find a viable work around or solution? Having issues with multiple parameters with React Navigation 5's deep linking feature.

**Comment by tr3v3r** [comment]
The same here. It's a huge problem for us

**Comment by MalinnaLeach** [comment]
We are having this problem on iOS, when listening for the 'url' event from Linking - really keen to see a fix released for this!

**Comment by redefinered** [comment]
then maybe string replace on android is the best solution as of now?

**Comment by hellogerard** [comment]
I have found that on Android, URLs with multiple query params work fine on a real device. I tested this by emailing myself a link and opening it on a phone. When testing from a shell using `adb`, you have to surround with double quotes _and_ escape the ampersands.

So this issue can probably be closed. Summarising:

- **On iOS,** when using `xcrun simctl openurl booted`, you need to surround URLs with double quotes. On a real device, URLs work fine.

- **On Android,** when using `adb shell am start`, you need to surround URLs with double quotes and escape the ampersands. On a real device, URLs work fine.
