### ISSUE TITLE
UIManager.measureInWindow on android not work as document

### ISSUE THREAD

**Issue by jinshiyi11** [facebook/react-native#29638]
## Description
UIManager.measureInWindow on android not work as document.
in _ReactAndroid/src/main/java/com/facebook/react/uimanager/UIManagerModule.java_
```
/**
   * Determines the location on screen, width, and height of the given view relative to the device
   * screen and returns the values via an async callback. This is the absolute position including
   * things like the status bar
   */
  @ReactMethod
  public void measureInWindow(int reactTag, Callback callback) {
    mUIImplementation.measureInWindow(reactTag, callback);
  }
```
it saids that 

> This is the absolute position including  things like the status bar

.But in _ReactAndroid/src/main/java/com/facebook/react/uimanager/NativeViewHierarchyManager.java
React Native version 0.60.5,it removes the status bar from the height
```
public synchronized void measureInWindow(int tag, int[] outputBuffer) {
    UiThreadUtil.assertOnUiThread();
    View v = mTagsToViews.get(tag);
    if (v == null) {
      throw new NoSuchNativeViewException("No native view for " + tag + " currently exists");
    }

    v.getLocationOnScreen(outputBuffer);

    // We need to remove the status bar from the height.  getLocationOnScreen will include the
    // status bar.
    Resources resources = v.getContext().getResources();
    int statusBarId = resources.getIdentifier("status_bar_height", "dimen", "android");
    if (statusBarId > 0) {
      int height = (int) resources.getDimension(statusBarId);
      outputBuffer[1] -= height;
    }

    // outputBuffer[0,1] already contain what we want
    outputBuffer[2] = v.getWidth();
    outputBuffer[3] = v.getHeight();
  }
```
and in lateset version ,it subtract visibleWindowCoords（the master version）
```
public synchronized void measureInWindow(int tag, int[] outputBuffer) {
    UiThreadUtil.assertOnUiThread();
    View v = mTagsToViews.get(tag);
    if (v == null) {
      throw new NoSuchNativeViewException("No native view for " + tag + " currently exists");
    }

    v.getLocationOnScreen(outputBuffer);

    // we need to subtract visibleWindowCoords - to subtract possible window insets, split screen or
    // multi window
    Rect visibleWindowFrame = new Rect();
    v.getWindowVisibleDisplayFrame(visibleWindowFrame);
    outputBuffer[0] = outputBuffer[0] - visibleWindowFrame.left;
    outputBuffer[1] = outputBuffer[1] - visibleWindowFrame.top;

    // outputBuffer[0,1] already contain what we want
    outputBuffer[2] = v.getWidth();
    outputBuffer[3] = v.getHeight();
  }
```

## React Native version:
React Native version 0.60.5

## Expected Results
absolute position including  things like the status bar

**Comment by gedeagas** [comment]
@safaiyeh just checked this on RNTester and it seems that the comment is wrong. On Android, the `measureInWindow` function does not include things like the status bar. 

The function will return `x:0 y:0` instead of `x:0 y:${px from statusbar}`. That said I don't know what the correct "behavior" is. 

haven't tested the behavior on iOS.

**Comment by gedeagas** [comment]
Related issue https://github.com/facebook/react-native/issues/19497

**Comment by gedeagas** [comment]
@safaiyeh Just confirmed there is a feature parity problem between iOS and Android. The ios return y with status bar height while the android implementation does not. This issue is first discovered on #19497 and mentioned on RN Issue Triage Group 2 https://github.com/facebook/react-native/issues/24029. 

I already make WIP PR on this but need a proper review from the React Native team. ( Multi Window problem, etc.,)

**Comment by safaiyeh** [comment]
@gedeagas appreciate the PR!

**Comment by phasjim** [comment]
Hey there!
I am running React Native 0.63.4 and noticing that `undefined` is still being returned on Android when using `measureInWindow`. This works fine on iOS. I looked at all the linked issues and tried their suggestions and to no avail. Wanted to bring this to your attention! Thanks

**Comment by cosmoyoung** [comment]
collapsable: false

**Comment by QuentinGprd** [comment]
> collapsable: false

Thanks! Indeed, `measureInWindow` return values on Android after adding `collapsable={false}` as a prop on the measured view.

See [https://reactnative.dev/docs/view#collapsable-android](https://reactnative.dev/docs/view#collapsable-android)

**Comment by tj-mc** [comment]
Confirming that `collapsable={false}` is working on `0.69` to make Android views report size from `measureInWindow`.

**Comment by bimix** [comment]
measureInWindow is returning undefined variables for me on the last item of the list.
