### ISSUE TITLE
DoubleConversion compile failed

### ISSUE THREAD

**Issue by karlgit** [facebook/react-native#29643]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
when i updated my Mac python environment, i find my react-native app can not run success! 
I can run success in xcode, but not in command.
clang-4.0: error: cannot specify -o when generating multiple output files

The following build commands failed:
	CompileC /Users/apple/Library/Developer/Xcode/DerivedData/myshukun-cvquunkxqcofpjahcojjokrghlpd/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/DoubleConversion.build/Objects-normal/x86_64/bignum.o /Users/apple/Documents/gitlab/myshukun-app/ios/Pods/DoubleConversion/double-conversion/bignum.cc normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/apple/Library/Developer/Xcode/DerivedData/myshukun-cvquunkxqcofpjahcojjokrghlpd/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/DoubleConversion.build/Objects-normal/x86_64/fast-dtoa.o /Users/apple/Documents/gitlab/myshukun-app/ios/Pods/DoubleConversion/double-conversion/fast-dtoa.cc normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/apple/Library/Developer/Xcode/DerivedData/myshukun-cvquunkxqcofpjahcojjokrghlpd/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/DoubleConversion.build/Objects-normal/x86_64/double-conversion.o /Users/apple/Documents/gitlab/myshukun-app/ios/Pods/DoubleConversion/double-conversion/double-conversion.cc normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/apple/Library/Developer/Xcode/DerivedData/myshukun-cvquunkxqcofpjahcojjokrghlpd/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/DoubleConversion.build/Objects-normal/x86_64/cached-powers.o /Users/apple/Documents/gitlab/myshukun-app/ios/Pods/DoubleConversion/double-conversion/cached-powers.cc normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/apple/Library/Developer/Xcode/DerivedData/myshukun-cvquunkxqcofpjahcojjokrghlpd/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/DoubleConversion.build/Objects-normal/x86_64/bignum-dtoa.o /Users/apple/Documents/gitlab/myshukun-app/ios/Pods/DoubleConversion/double-conversion/bignum-dtoa.cc normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/apple/Library/Developer/Xcode/DerivedData/myshukun-cvquunkxqcofpjahcojjokrghlpd/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/DoubleConversion.build/Objects-normal/x86_64/diy-fp.o /Users/apple/Documents/gitlab/myshukun-app/ios/Pods/DoubleConversion/double-conversion/diy-fp.cc normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/apple/Library/Developer/Xcode/DerivedData/myshukun-cvquunkxqcofpjahcojjokrghlpd/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/DoubleConversion.build/Objects-normal/x86_64/DoubleConversion-dummy.o /Users/apple/Documents/gitlab/myshukun-app/ios/Pods/Target\ Support\ Files/DoubleConversion/DoubleConversion-dummy.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/apple/Library/Developer/Xcode/DerivedData/myshukun-cvquunkxqcofpjahcojjokrghlpd/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/DoubleConversion.build/Objects-normal/x86_64/strtod.o /Users/apple/Documents/gitlab/myshukun-app/ios/Pods/DoubleConversion/double-conversion/strtod.cc normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler

## React Native version:
Run `react-native info` in your terminal and copy the results here.
System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
    Memory: 2.57 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.16.2 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.0 - /Users/apple/.rvm/rubies/ruby-2.6.3/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 22, 23, 24, 25, 26, 27, 28, 29
      Build Tools: 27.0.3, 28.0.3, 29.0.0, 29.0.2, 29.0.3
      System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
      Android NDK: 21.0.6113669
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_152-release - /usr/bin/javac
    Python: 2.7.15 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^16.11.0 => 16.13.1 
    react-native: ^0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.
1. run react-native run-ios
2.

**Comment by karlgit** [comment]
I have try to change the defalut shell to zsh, it work for me!
I do not know why, but maybe i change something i do not know careless.

**Comment by safaiyeh** [comment]
@karlgit glad you found a solution! Closing for now.

**Comment by Osamasomy** [comment]
I have same Question How to solve this problem?
