### ISSUE TITLE
 Error while updating property 'fontFamily' in shadow node of type: RCTText

### ISSUE THREAD

**Issue by 026binit** [facebook/react-native#29644]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description

i have got crash log from firebase . My app standalone apk is crashed in some device at startup but working fine in some other devices.
My standalone apk is working fine in Samsung Galaxy M11 
My standalone apk is crashing in Samsung Galaxy S9 Plus

Below is the crash log received from firbase crash log

```
Fatal Exception: java.lang.RuntimeException: Expo encountered a fatal error: Error while updating property 'fontFamily' in shadow node of type: RCTText
       at host.exp.exponent.experience.BaseExperienceActivity$2.run(BaseExperienceActivity.java:206)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7073)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
```

In my code i have written fontFamily like below in everywhere in my project :- 

```
 <Component
              style={
                Object {
                  "color": "#1087DD",
                  "fontFamily": "openSansRegular",
                  "fontSize": 16,
                }
              }
            >
              Don't have an account? Sign up for free!
  </Component>
```
is this correct format i have written fontFamily ? if this is ok then why this crash logs appear inside firebase crash logs

## React Native version:
Run `react-native info` in your terminal and copy the results here.

react: 16.11.0 => 16.11.0 
react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.
2.

## Expected Results
Describe what you expected to happen.

## Snack, code example, screenshot, or link to a repository:
Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by CurtisTD** [comment]
I am still having the same issue
