### ISSUE TITLE
Shadow in Android with React-Native

### ISSUE THREAD

**Issue by tirthjivani** [facebook/react-native#29648]
## Problem
I was trying to create <a href="https://miro.medium.com/max/3200/0*D64v9Py83jSkuBMn.png"><b>Neumorphism (Soft UI)</b></a> in Android but the idea is not working with the android part, I have seen that the props mentioned on https://reactnative.dev/docs/shadow-props are also mentioned for the only iOS and not for android. It is not a kind of bug but we can say there needs to be some solution to this problem. I have mentioned the slack link below.

## React Native version:
System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 57.71 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.5.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.7 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.2 => 0.63.2
 

## Expected Results
This thing works completely fine in the iOS.
![Image of result on Android](https://github.com/tirthjivani/Neumorphism-Soft-UI/blob/master/assets/ss.png?raw=true)

## Snack:
https://snack.expo.io/@tirthjivani/neumorphism-music-player

**Comment by safaiyeh** [comment]
@tirthjivani there is this shadow generator that might help you: https://ethercreative.github.io/react-native-shadow-generator/ let me know if it does!

**Comment by tirthjivani** [comment]
> @tirthjivani there is this shadow generator that might help you: https://ethercreative.github.io/react-native-shadow-generator/ let me know if it does!

Nope, this doesn't work, I have tried it earlier and even other 3 npm packages,
1. https://www.npmjs.com/package/react-native-simple-shadow-view
2. https://www.npmjs.com/package/@gfpacheco/react-native-shadow or https://github.com/879479119/react-native-shadow
3. https://stenbeck.io/styling-shadows-in-react-native-ios-and-android/

This last one works but a little change in the radius creates a mess. Also, one more issue was faced i.e. https://github.com/ConduitMobileRND/react-native-simple-shadow-view/issues/7

This is the output in Android with elevation, according to https://ethercreative.github.io/react-native-shadow-generator/ 
![WhatsApp Image 2020-08-15 at 17 37 05](https://user-images.githubusercontent.com/33369435/90311957-07237a80-df1e-11ea-89b4-59eb73608889.jpeg)

**Comment by pavi2410** [comment]
Shadow colors can't be changed on Android API below 28

Click on the link below to find a similar discussion on Compose channel
https://kotlinlang.slack.com/archives/CJLTWPH7S/p1594065063468800?thread_ts=1594065063.468800&cid=CJLTWPH7S

**Comment by tirthjivani** [comment]
Is there any way to add it in Android 29 or later?

T.

**Comment by pavi2410** [comment]
Yes, see [View#setOutlineAmbientShadowColor(int color)](https://developer.android.com/reference/android/view/View.html#setOutlineAmbientShadowColor(int)) and [View#setOutlineSpotShadowColor(int color)](https://developer.android.com/reference/android/view/View.html#setOutlineSpotShadowColor(int))

**Comment by tirthjivani** [comment]
Ok, let me give you an update soon. 👍🏻

**Comment by chrisglein** [comment]
Yeah, that's some different looking shadows for sure :o. Do you know how aligned the native layers are in capabilities here? How much can RN create a unified shadow experience versus is limited by what native can do. Shadows is one of those areas that's likely going to have some big differences under the hood (I'm thinking about what Windows would do here and, yeah, that's also going to be different from what we see above too).

**Comment by tirthjivani** [comment]
> Yeah, that's some different looking shadows for sure :o. Do you know how aligned the native layers are in capabilities here? How much can RN create a unified shadow experience versus is limited by what native can do. Shadows is one of those areas that's likely going to have some big differences under the hood (I'm thinking about what Windows would do here and, yeah, that's also going to be different from what we see above too).

Yess Chris indeed finding a way to bring this look. I have explored native layers but I don't think so it will work with this, instead, I'm trying to switch to Android 29 and try to implement this https://developer.android.com/reference/android/view/View#setOutlineSpotShadowColor(int).
Yeah, shadows will be an important key for UI in the future.

**Comment by alexco2** [comment]
As a workaround, do you think it is possible to just create a custom ui component in native android?
https://reactnative.dev/docs/native-components-android

**Comment by chrisglein** [comment]
If you can get the same look an feel with a custom Android component for now that seems like a good next step. Then that could be used as the basis for an implementation of these currently iOS-only shadow properties.

As for what to do with this issue, it seems like it's either going to be possible to replicate in Android, in which case file a PR (yay!). Or, the API needs to change to adopt >1 platform, in which case new/changed API proposals should go to the [discussions & proposals repo](https://github.com/react-native-community/discussions-and-proposals/).
