### ISSUE TITLE
Building and opening project on ios simulator with npx react-native run-ios takes too long

### ISSUE THREAD

**Issue by codeamo** [facebook/react-native#29659]
## Description
I have recently ejected my project from expo to bare react native and I have followed the document for smooth transition which was straight forward, but when I try to build my react-native project on the ios simulator is takes too long and never builds the app. here is a screen shot of my terminal building the app and I can't get past here as building process takes forever.

<img width="1433" alt="Screen Shot 2020-08-15 at 6 45 24 PM" src="https://user-images.githubusercontent.com/46251634/90321385-ca717680-df51-11ea-8aa8-6d896ab591e4.png">

## React Native version:
```
System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 98.73 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.6.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.6 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 29
      Build Tools: 29.0.2
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_265 - /usr/bin/javac
    Python: 3.7.6 - /Users/amiinamo/.pyenv/shims/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: ~16.11.0 => 16.11.0 
    react-native: ~0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
1. expo eject
2. pod install
3. npx react-native start
4. npx react-native run-ios

## Expected Results
I was expecting to see my app running in the iOS Simulator shortly but never happened.

**Comment by safaiyeh** [comment]
Hi @codeamo thanks for the issue. Expo initially comes with more dependencies than the React Native template, that could be a sign of the slowness. Also the resources on your machine.

Could you create an issue on the expo repo? They could help you out better.

**Comment by codeamo** [comment]
@safaiyeh ok that looks reasonable. I will create an issue on the expo repo. Thanks
