### ISSUE TITLE
TextInput placeholder is always multiline on Android

### ISSUE THREAD

**Issue by mrousavy** [facebook/react-native#29663]
## Description

On Android, the `<TextInput>`'s `placeholder` property always renders to multiple lines, whereas on iOS it trails the ending (like `ellipsizeMode="trail"`).

![Screenshot 2020-08-16 at 17 05 02](https://user-images.githubusercontent.com/15199031/90337460-dc4f2a00-dfe2-11ea-969a-735795be8430.png)
![Screenshot 2020-08-16 at 17 06 24](https://user-images.githubusercontent.com/15199031/90337461-dd805700-dfe2-11ea-961a-0b45ec7c8c0e.png)

## React Native version:

```
info Fetching system and libraries information...
System:
    OS: macOS 10.15.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 5.61 GB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.8.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.7 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 25, 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.0, 30.0.0, 30.0.0, 30.0.1
      System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: 21.2.6472646
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_265 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Create `<TextInput>` component
2. Set `placeholder` to anything long

## Expected Results

The placeholder should leave dots at the trail, so no line wraps.

## Snack, code example, screenshot, or link to a repository:

```tsx
<TextInput
	style={textInputStyle}
	placeholder={"This is a test placeholder which doesn't ellipzise with trailing dots"}
	placeholderTextColor="gray"
	value=""
/>

```

**Comment by gang544043963** [comment]
Is there any progress？ I met the same problem.

**Comment by InnaZakarzheeva** [comment]
maybe it's strange, but use
`flex: 1`
and placeholder will in one line

**Comment by Nualiian** [comment]
I am also still seeing this issue on `0.63.4`

**Comment by mrousavy** [comment]
I created a PR for this here: https://github.com/facebook/react-native/pull/29664

**Comment by wenchao0809** [comment]
Is there any progress？ I met the same problem.

**Comment by montoyadamien** [comment]
Still the problem here...

**Comment by bdtren** [comment]
Current workaround I can find for now is add `maxHeight: <fontsize + padding>` to style prop.

**Comment by SaphiraNgocThuy** [comment]
I got similar problem, up vote for a new prop `ellipsizeMode`

**Comment by minhchienwikipedia** [comment]
Same issue here

**Comment by Jungdaekyeom** [comment]
Still the problem here too...

**Comment by Svarto** [comment]
same issue here

**Comment by vinhthuy2** [comment]
same issue here

**Comment by nolife08021** [comment]
any solution or workaround this? facing same issue

**Comment by Altafk960** [comment]
Is the issue resolved yet?

**Comment by NidhiHub** [comment]
I am also facing same issue. Any solution?? Waiting for this issue to be fix.
@mrousavy Any update on your PR??

**Comment by alainib** [comment]
this issue is still there in 10/10/2023 !

**Comment by ryskin** [comment]
same issue here

**Comment by Tan2NT** [comment]
Same issue here, especially when changing the device font size

**Comment by irawel** [comment]
This is still happening on RN 0.73.4

**Comment by GrishovAleksei** [comment]
+

**Comment by Raiden-16F7** [comment]
Same issue on Expo SDK 51

**Comment by kkx64** [comment]
It's 2025 and still an issue

**Comment by yosukapro** [comment]
This issue still not fixed

**Comment by dkulakov** [comment]
I was able to add a workaround for this issue for an old architecture and created a module for it [https://github.com/dkulakov/react-native-input-placeholder-ellipsized](https://github.com/dkulakov/react-native-input-placeholder-ellipsized), any suggestions or improvements are welcome.
Just wanted to share this solution with others who might be struggling with the same problem. Feel free to check it out if you need a quick fix while waiting for an official solution!

**Comment by ugoi** [comment]
Still facing this issue. Why is it closed?

**Comment by tboba** [comment]
Still facing it on RN 0.79, Android 16 (Samsung's One UI) 🤕

**Comment by feidaZhang** [comment]
reopen reopen, fuck u

**Comment by vladimirevstratov** [comment]
still there is this issue

**Comment by elozino-eryk** [comment]
Issue still there.... Testing on a samsung device

**Comment by wahyutrading** [comment]
This issue still there..

**Comment by namdh03** [comment]
Still...

**Comment by ammoradi** [comment]
Still here in `"react-native": "0.85.3"`!!!

**Comment by sofizambrano** [comment]
Please fix this 🙏 I have the issue in `"react-native": "0.83.8"`

**Comment by oreis1991** [comment]
problema ainda persiste 08/07/2026 "react-native": "0.81.5"
