### ISSUE TITLE
react-native bundle how to specify top module path

### ISSUE THREAD

**Issue by plrthink** [facebook/react-native#2966]
I have changed default path from index.ios.js to app/index.ios.js. when I run `react-native bundle --minify` for generate an offline bundle but failed. I think its because packager doesn't the path of top module path.
So how I change the default path of it?

**Comment by mkonicek** [comment]
Hey @plrthink, what's the error?

**Comment by plrthink** [comment]
@mkonicek Here's the error:

```
/Users/plrthink/Work/mb-mobile/node_modules/react-native/node_modules/promise/lib/done.js:10
      throw err;
      ^
NotFoundError: Cannot find entry file index.ios.js in any of the roots: ["/Users/plrthink/Work/mb-mobile"]
    at DependencyGraph._getAbsolutePath (/Users/plrthink/Work/mb-mobile/node_modules/react-native/packager/react-packager/src/DependencyResolver/DependencyGraph/index.js:186:11)
    at /Users/plrthink/Work/mb-mobile/node_modules/react-native/packager/react-packager/src/DependencyResolver/DependencyGraph/index.js:141:28
    at tryCallOne (/Users/plrthink/Work/mb-mobile/node_modules/react-native/node_modules/promise/lib/core.js:37:12)
    at /Users/plrthink/Work/mb-mobile/node_modules/react-native/node_modules/promise/lib/core.js:103:15
    at flush (/Users/plrthink/Work/mb-mobile/node_modules/react-native/node_modules/promise/node_modules/asap/raw.js:50:29)
    at doNTCallback0 (node.js:407:9)
    at process._tickCallback (node.js:336:13)
```

I think it simply because I have changed the index.ios.js to ./app/index.ios.js and bundler doesn't know I did that. So is there some parameter that I can specify where my index.ios.js is?

**Comment by nsimmons** [comment]
`react-native bundle --root app --minify` should do the trick, assuming you have put all your JS files under the `app/` folder.

#2572 tries to address some of the confusion around the bundle command.

**Comment by plrthink** [comment]
@nsimmons thx, I think I should close this issue.
