### ISSUE TITLE
In FlastList, separators.updateProps("leading", {...}) won't work for the item at the index value of initialNumToRender

### ISSUE THREAD

**Issue by divonelnc** [facebook/react-native#29662]
## Description
Calling `separators.updateProps("leading", {...})` from the item at index `initialNumToRender` won't find the leading item.
For example, with `initialNumToRender=10`, calling `separators.updateProps("leading", {...})` from the item at index 10 of your Flatlist won't work.

From debugging, I found out that the issue comes from `VirtualizedList.js:842`. The loop restarts once this index is reached, setting the `prevCellKey` value to undefined. Without a proper `prevCellKey` value, the leading item won't be found in the `separators.updateProps` call.

## React Native version:
`react-native: 0.62.2`

## Steps To Reproduce

1. Create a Flatlist with more than 10 items, and set`initialNumToRender` props to 10 (or leave it as default)
2. In the renderItem, call separators.updateProps("leading", {...})
3. Notice that the `prevCellKey` props in updateProps is undefined.

## Expected Results
To be able to update the props for the leadingItem of every items in the list.

## Snack, code example, screenshot, or link to a repository:
https://snack.expo.io/@divone/no-leading-item-on-initialnumtorender-index

**Comment by Mostipan777** [comment]
The same problem.

**Comment by divonelnc** [comment]
This is still happening

**Comment by brianwachira** [comment]
same issue
