### ISSUE TITLE
Library not found for -lDoubleConversion Build failed

### ISSUE THREAD

**Issue by Osamasomy** [facebook/react-native#29661]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description

https://i.stack.imgur.com/8VbEV.png

**ALREADY TRY THIS**

>https://stackoverflow.com/questions/50562596/library-not-found-for-ldoubleconversion

>https://stackoverflow.com/questions/55239646/ld-library-not-found-for-ldoubleconversion-react-native-0-59

here is what i did

- I clean and rebuild
- rm -f ~/Library/Developer/Xcode/DerivedData/cache
- also add remove flags from **Other Linker Flags**
- also try to add .a file in Link Binary With library under **build phase**

**Still Not get Success**
 
## React Native version:
Run `react-native info` in your terminal and copy the results here.

System:
    OS: macOS 10.15.5
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 96.62 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.4.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 26, 27, 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3
      System Images: android-29 | Google APIs Intel x86 Atom, android-R | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_252 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. After Upgradtion (but Im able to run it but some how it crash I don't no why)

## Expected Results
Make successful Build

**Comment by safaiyeh** [comment]
Hi @Osamasomy upgrade issues have been moved to https://github.com/react-native-community/upgrade-support. Could you check out if this was solved or create a new issue there? Thanks!
