### ISSUE TITLE
[Android] Nested ScrollView won't scroll

### ISSUE THREAD

**Issue by mattds** [facebook/react-native#2967]
Hi team, it seems that a nested ScrollView won't scroll when running on Android but is able to scroll on iOS. On android it seems only possible to scroll the outer scrollview at the moment.

**Comment by andreicoman11** [comment]
KP, @krzysztof had some ideas about how this can be done.

**Comment by kmagiera** [comment]
ScrollView in JS just maps to a regular scroll view android component. Android by default doesn't support that. If you'd like to use that you'd need to wrap another android component that is capable of doing so: https://developer.android.com/reference/android/support/v4/widget/NestedScrollView.html
Here are some instructions on how to wrap custom components on android: http://facebook.github.io/react-native/docs/native-components-android.html#content

**Comment by mattds** [comment]
Thanks, I will use a wrapped NestedScrollView then as suggested.

**Comment by aferust** [comment]
to @kmagiera, @mattds : Could you please provide some example code for implementing NestedScrollView to react-native?

**Comment by ikhsanalatsary** [comment]
Because i'm not java programmer. For me, the solution is using this package https://www.npmjs.com/package/react-native-nested-scroll-view
and the example https://github.com/cesardeazevedo/react-native-collapsing-toolbar
