### ISSUE TITLE
org.slf4j.helpers.NOPLogger cannot be cast to org.gradle.api.logging.Logger

### ISSUE THREAD

**Issue by mehul76** [facebook/react-native#29676]
info Installing the app...
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

FAILURE: Build failed with an exception.

* What went wrong:
org.slf4j.helpers.NOPLogger cannot be cast to org.gradle.api.logging.Logger

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".

**Comment by dulmandakh** [comment]
Please make sure that you have proper Android environment, see error below.

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
