### ISSUE TITLE
Text Scroll Issue in TVOS

### ISSUE THREAD

**Issue by jasmeet447** [facebook/react-native#29672]
## Description
Hii, I've been trying to make a scrollable text component for tvos like the one we see in terms and conditions box in a lot of applications. The code works fine for android tv but the text doesn't scroll down in tvos.

## Steps To Reproduce
The code snippet is as follows:

<ScrollView style={
{
flex: 1,
paddingTop: getScaledValue(50)
}}
contentContainerStyle={{
alignItems: 'center',
justifyContent: 'center'
}}
removeClippedSubviews={false}

< Text style={styles.textH2} >
This is the text portion that needs to be scrolled .............

< /Text >
< /ScrollView >

## Expected Results - text should scroll down

Any Help will be appreciated

**Comment by safaiyeh** [comment]
Hi @jasmeet447 thank you for the issue. tvOS has been moved to this repo https://github.com/react-native-community/react-native-tvos

Please file an issue over there!
