### ISSUE TITLE
Exception '-[NSNull substringToIndex:]: unrecognized selector sent to instance 0x7fff8062d200' was thrown while invoking sendRequest on target Networking with params

### ISSUE THREAD

**Issue by hellochirag** [facebook/react-native#29677]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Please provide a clear and concise description of what the bug is. Include screenshots if needed.
Please test using the latest React Native release to make sure your issue has not already been fixed: https://reactnative.dev/docs/upgrading.html

## React Native version:
Run `react-native info` in your terminal and copy the results here.

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.
2.

## Expected Results
Describe what you expected to happen.

## Snack, code example, screenshot, or link to a repository:
Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

`Exception '-[NSNull substringToIndex:]: unrecognized selector sent to instance 0x7fff8062d200' was thrown while invoking sendRequest on target Networking with params (
        {
        data =         {
            formData =             (
                                {
                    fieldName = image;
                    headers =                     {
                        "content-disposition" = "form-data; name=\"image\"; filename=\"image[file]\"";
                        "content-type" = "image/jpeg";
                    };
                    name = "image[file]";
                    type = "image/jpeg";
                    uri = "<null>";
                }
            );
            trackingName = unknown;
        };
        headers =         {
            accept = "application/json";
            authorization = "Token ";
        };
        incrementalUpdates = 1;
        method = PUT;
        responseType = text;
        timeout = 0;
        url = "API URL";
        withCredentials = 1;
    },
    22879
)
callstack: (
	0   CoreFoundation                      0x00007fff23e39f0e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff50ad79b2 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23e5ac34 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff23e3e90c ___forwarding___ + 1436
	4   CoreFoundation                      0x00007fff23e40bf8 _CF_forwarding_prep_0 + 120
	5   SRVE Chef                           0x0000000102280c4d -[RCTHTTPFormDataHelper process:callback:] + 2989
	6   SRVE Chef                           0x0000000102286ea8 -[RCTNetworking processDataForHTTPQuery:callback:] + 4808
	7   SRVE Chef                           0x0000000102284f3d -[RCTNetworking buildRequest:completionBlock:] + 3773
	8   SRVE Chef                           0x000000010228c0cd -[RCTNetworking sendRequest:responseSender:] + 253
	9   CoreFoundation                      0x00007fff23e40e8c __invoking___ + 140
	10  CoreFoundation                      0x00007fff23e3e071 -[NSInvocation invoke] + 321
	11  CoreFoundation                      0x00007fff23e3e344 -[NSInvocation invokeWithTarget:] + 68
	12  SRVE Chef                           0x0000000102197944 -[RCTModuleMethod invokeWithBridge:module:arguments:] + 2660
	13  SRVE Chef                           0x000000010219bb11 _ZN8facebook5reactL11invokeInnerEP9RCTBridgeP13RCTModuleDatajRKN5folly7dynamicE + 801
	14  SRVE Chef                           0x000000010219b5e6 _ZZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEiENK3$_0clEv + 134
	15  SRVE Chef                           0x000000010219b54c ___ZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEi_block_invoke + 28
	16  libdispatch.dylib                   0x0000000104465f11 _dispatch_call_block_and_release + 12
	17  libdispatch.dylib                   0x0000000104466e8e _dispatch_client_callout + 8
	18  libdispatch.dylib                   0x000000010446d6fd _dispatch_lane_serial_drain + 788
	19  libdispatch.dylib                   0x000000010446e28f _dispatch_lane_invoke + 422
	20  libdispatch.dylib                   0x0000000104479b65 _dispatch_workloop_worker_thread + 719
	21  libsystem_pthread.dylib             0x00007fff51b37a3d _pthread_wqthread + 290
	22  libsystem_pthread.dylib             0x00007fff51b36b77 start_wqthread + 15
)

RCTFatal
facebook::react::invokeInner(RCTBridge*, RCTModuleData*, unsigned int, folly::dynamic const&)
facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int)::$_0::operator()() const
invocation function for block in facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int)
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_lane_serial_drain
_dispatch_lane_invoke
_dispatch_workloop_worker_thread
_pthread_wqthread
start_wqthread
`

**Comment by safaiyeh** [comment]
@hellochirag Thanks for the issue, could you please fill out all the fields in the template?
