### ISSUE TITLE
[Android] undefined is not an object (evaluating 'backandroid.addeventlistener')

### ISSUE THREAD

**Issue by luqin** [facebook/react-native#2968]

**Comment by mkonicek** [comment]
Hey @io3, can you please provide the code of your app so we can repro this?

**Comment by lifuzu** [comment]
+1, Hi @mkonicek Martin, I think you can use this repo to repro:
https://github.com/iSimar/HackerNews-React-Native.git
commit 5ce48838b6142c2956074bfe683be572c0f5b8fe

**Comment by marsprince** [comment]
I got the same problem by running hackews，as @lifuzu says

**Comment by ethaizone** [comment]
I got same problem too. I think it because react-native version because it work until I run "npm update" at my project. I saw package.json of react-native has version 0.11.2. I think it's has some update that break react-native.

**Comment by ethaizone** [comment]
I found temporary fix. Open this file in your project. ```node_modules/react-native/Libraries/react-native/react-native.js```

Find: ```AsyncStorage: require('AsyncStorage'),```
Add this line after: ```BackAndroid: require('BackAndroid'),```

Your app will run fine.

I can't create pull request because react native project is too large for me. I can't find commit that update 0.11.2.

**Comment by satya164** [comment]
#3080

**Comment by satya164** [comment]
This is fixed.
