### ISSUE TITLE
[Android] TextInput events inconsistent when using backspace key

### ISSUE THREAD

**Issue by SirhCloud** [facebook/react-native#29689]
## Description
Hi all, 

I have a use case where I am checking for a TextInput's value to be empty when using the backspace key. I have found a bug when using the backspace key on Android devices. The onChange, onChangeText and onKeyPress events fire at different intervals depending on the character being deleted. For example:

Removing a letter fires in this order:
1. onChange
2. onChangeText
3. onKeyPress

Removing a number, space or a symbol fires in this order:
1. onKeyPress
2. onChange
3. onChangeText

I have discovered on iOS devices it consistently fires in the order:
1. onKeyPress
2. onChange
3. onChangeText

Can we have Android devices fire in the same order as iOS devices when the backspace key is pressed?

## React Native version:
System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
    Memory: 3.35 GB / 15.96 GB
  Binaries:
    Node: 14.8.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.7 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 23, 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6392135
    Visual Studio: Not Found
  Languages:
    Java: 11.0.6 - C:\Program Files\Amazon Corretto\jdk11.0.6_10\bin\javac.EXE
    Python: 2.7.17 - C:\Python27\python.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.2 => 0.63.2
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Assuming you log which event fires in the TextInput

Letter Delete:
1. TextInput contains the letter 'a'
2. Press backspace on the keyboard which would make the TextInput empty
3. Check the loggers for the TextInput and you will see they fire in the order: onChange, onChangeText, onKeyPress

Number Delete:
1. TextInput contains the number '1'
2. Press backspace on the keyboard which would make the TextInput empty
3. Check the loggers for the TextInput and you will see they fire in the order: onKeyPress, onChange, onChangeText

Space Delete:
1. TextInput contains the space ' '
2. Press backspace on the keyboard which would make the TextInput empty
3. Check the loggers for the TextInput and you will see they fire in the order: onKeyPress, onChange, onChangeText

Symbol Delete:
1. TextInput contains the symbol '!'
2. Press backspace on the keyboard which would make the TextInput empty
3. Check the loggers for the TextInput and you will see they fire in the order: onKeyPress, onChange, onChangeText

## Expected Results
When I press the backspace button, I expect it to fire the events the same as iOS in the order: onKeyPress, onChange, onChangeText.

## Snack, code example, screenshot, or link to a repository:
https://github.com/SirhCloud/react-native-backspace-issue

**Comment by safaiyeh** [comment]
@SirhCloud I appreciate the issue, this is some odd behavior... I verified the logs. Could this be something you can look into>

![Screen Shot 2020-08-18 at 6 50 53 PM](https://user-images.githubusercontent.com/8675043/90582893-bf9e2800-e183-11ea-9643-4cf1d5eed9bf.png)

**Comment by SirhCloud** [comment]
@safaiyeh yeah, I can have a look and see what I can find thanks.

**Comment by vidmantas0010** [comment]
We are having this issue as well, and it causes a lot of troubles. 
https://reactnative.dev/docs/textinput#onkeypress
Documentation say "Fires before onChange callbacks".

**Comment by vidmantas0010** [comment]
Solved our issue deferring onChange event with lodash debounce to next javascript event loop cycle. 
setTimeout would also do the job.
`onChange = _.debounce((event) => {})`
