### ISSUE TITLE
getCurrentActivity sometimes null inside componentDidMount

### ISSUE THREAD

**Issue by jjhampton** [facebook/react-native#29699]
Duplicate of https://github.com/facebook/react-native/issues/18345

Please re-open this ticket. The original was closed by stale-bot, but it is still occurring as of React Native 0.60.5

Thank you.

**Comment by jjhampton** [comment]
bump

**Comment by SNWStaff** [comment]
We are also facing this issue, any news?

**Comment by Pranav-yadav** [comment]
@cortinico is this bug still valid today? if not should we close this ? No wonder, why bot didn't add stale label on this issue as well 🤔?

P.S. Landed here accidently :) Sorry for the ping. Also, whom should I ping if I land on similar (age old) issues with no stale labels?

**Comment by cortinico** [comment]
> why bot didn't add stale label on this issue as well 🤔?

That's because we have too many issues and the bot running out of quota, but will eventually get here. This is definitely stale though
