### ISSUE TITLE
unable to scroll in scrollView in Android

### ISSUE THREAD

**Issue by johnneuland** [facebook/react-native#29696]
## Description
I have a screen where I type in the input field and get search results accordingly. The list is rendered within a ScrollView but it still doesn't let me scroll when the keypad is open (in Android ). In iOS, it works fine.

I tried adding height: 80% to ```dropdown```, it's parent container view. This makes it possible to scroll a bit. However, when the keypad is open I can scroll but not till the end of the list. If I add height: 100%, I am not able to scroll at all. I am already using ```flex:1```in the scroll view as well as the parent view. 

## React Native version:
3.0.4

## Steps To Reproduce
```
  return (
    <>
      {addressesFound.length > 0 ? (
        <ScrollView
          style={styles.searchResultsContainer}
          keyboardShouldPersistTaps={'always'}
          keyboardDismissMode={'on-drag'}>
          {addressesFound.map((addressDetails: addressDetailsType) => {
            return (
              <View
                key={addressDetails.placeName}
                style={styles.resultContainer}>
                <Text
                  style={styles.text}>
                  {addressDetails.placeName}
                </Text>
              </View>
            );
          })}
        </ScrollView>
      ) : null}
    </>
  );
};
const styles = StyleSheet.create({
  searchResultsContainer: {
    width: moderateScale(400),
    paddingHorizontal: moderateScale(50),
    paddingRight: moderateScale(65),
    marginTop: moderateScale(10),
   flex:1,
  },
  resultContainer: {
    marginTop: moderateScale(10),
    borderBottomWidth: 1,
    borderBottomColor: 'grey',
  },
  text: {
    fontSize: moderateScale(15),
  },
});
```
This is where the above mentioned component is called:
```
 <View style={styles.dropdown}>
          <LocationsFound
            addressesFound={locations.addressesFoundList} />
....
  dropdown: {
    position: 'absolute',
    top: moderateScale(215),
    zIndex: moderateScale(10),
    backgroundColor: '#fff',
    flex: 1,
  },
```

## Expected Results
I should be able to scroll in Android too, till the end of the list when the keypad is open. 

## Snack, code example, screenshot, or link to a repository:
![new](https://user-images.githubusercontent.com/69582269/90664691-44a04480-e24b-11ea-8f8c-e9010bf6568d.png)

**Comment by danielhusar** [comment]
I have similar issue.
It only appear when `ScrollView` is in the tree that has position absolute.

**Comment by Ikalli** [comment]
Any solution?
Still same problem with `position: absolute` ScrollView.

**Comment by kmarple1** [comment]
Having the same issue in react-native v0.66.4. Any workarounds?

**Comment by Abhishek2250** [comment]
I'm also facing the same issue on android. Any solution?
