### ISSUE TITLE
SafeAreaView only shown at bottom

### ISSUE THREAD

**Issue by johnneuland** [facebook/react-native#29694]
## Description

The **SafeAreaView (red coloured)** works well on all screens except this one, even though I am using the same styling everywhere. It is supposed to be shown at the top and bottom both. Here it is only shown at the bottom and not at the top. In this case, it is being hidden by the **View (in pink).** 

I am afraid this could be because of how I navigate to this screen from the previous one. The navigation looks like:

How can I fix the SafeAreaView at the top? Why is it being overlapped by the View?

## React Native version:
3.0.4

## Steps To Reproduce

My react-native screen looks somewhat like this: 

```
export const JourneyResultScreen: React.FunctionComponent = () => {
  return (
    <SafeAreaView style={styles.safeAreaViewContainer}>
      <View style={styles.container}>
        <Text>HELO</Text>
      </View>
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  safeAreaViewContainer: { flex: 1, backgroundColor: 'red'},
  container: {  flex: 1, backgroundColor: 'pink'},
});
```

App.tsx:

```
                <NavigationStack.Screen
                  name="Journey"
                  component={JourneyScreenNavigation}
                  options={{
                    headerShown: false,
                    ...TransitionPresets.FadeFromBottomAndroid,
                  }}
                />
```

```
const NavigationStack = createStackNavigator();
const config = {
  animation: 'spring',
  config: {
    stiffness: 1000,
    damping: 500,
    mass: 3,
    overshootClamping: true,
    restDisplacementThreshold: 0.01,
    restSpeedThreshold: 0.01,
  },
};
...
export const JourneyScreenNavigation: React.FC = () => {
  return (
    <NavigationStack.Navigator initialRouteName="Journey" mode="modal">
      <NavigationStack.Screen
        name="Journey"
        component={JourneySearchScreen}
        options={{ headerShown: false }}
      />
      <NavigationStack.Screen
        name="JourneyMap"
        component={JourneyResultScreen}
        options={{
          headerShown: false,
          gestureEnabled: false,
          cardStyleInterpolator:
            CardStyleInterpolators.forFadeFromBottomAndroid,
        }}
      />
      <NavigationStack.Screen
        name="TripsNavigation"
        component={AvailableTripsNavigation}
        options={{
          gestureEnabled: false,
          headerShown: false,
          cardStyleInterpolator:
            CardStyleInterpolators.forFadeFromBottomAndroid,
        }}
      />
    </NavigationStack.Navigator>
  );
};
```

## Expected Results
SafeAreaView should be visible on top and bottom both. 

## Snack, code example, screenshot, or link to a repository:
<img width="321" alt="Screenshot 2020-08-14 at 10 42 03" src="https://user-images.githubusercontent.com/69582269/90632171-41459280-e224-11ea-8828-87ce5664a8d8.png">

**Comment by safaiyeh** [comment]
Hi @johnneuland could you provide a Snack that demonstrates this without react-navigation? My hunch is that react-navigation handles safe area views differently.

**Comment by johnneuland** [comment]
> Hi @johnneuland could you provide a Snack that demonstrates this without react-navigation? My hunch is that react-navigation handles safe area views differently.

If I create a separate screen, then this issue doesn't exist. Generally, on other screens too, the SafeAreaView works fine.

**Comment by safaiyeh** [comment]
This might be a bug with react-navigation could you a file an issue with them?
