### ISSUE TITLE
Metro bundler starts with release scheme xcode

### ISSUE THREAD

**Issue by Arjanvanmaren** [facebook/react-native#29695]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
XCode starts bundler while running an app via the release scheme.

## React Native version:
"react": "16.13.0",
"react-native": "0.61.5",

## Version XCode 
Version 11.6 (11E708)

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Set Run scheme to release
2. Generate a main.js bundle (react-native bundle --entry-file='./src/index.js' --bundle-output='./ios/IEP/main.jsbundle' --dev=false --platform='ios' --assets-dest='./ios/IEP/Bundle.assets' --sourcemap-output='./ios/IEP/main.jsbundle.map')=
3. add main.js bundle as target to the project

## Expected Results
Build a release app with xcode so the app is independent from the bundler.

**Comment by safaiyeh** [comment]
Hi @Arjanvanmaren I would need more details. Could you provide a video, a repro, or something that shows this happening? And verify it happens on 0.63

**Comment by Arjanvanmaren** [comment]
As we are not upgrading in the near future we can close this ticket for now. Thanks for your help
