### ISSUE TITLE
android 4.4 Application crash  react-native 6.2+

### ISSUE THREAD

**Issue by luyouwei66** [facebook/react-native#29718]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Create a new project of version 6.2 or higher without any components. I have not tried the version below 6.2. It should be the same in version 6.0 and above. After turning on multiDexEnabled true and implementation com.android.support:multidex:1.0.1, opening the app will Direct flashback

## React Native version:
react-native 6.3.2 react-native 6.2.0

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.Create a new project of version 6.2 or higher without any components
2.Enable multiDexEnabled true and implementation and com.android.support:multidex:1.0.1

## Expected Results
Android 4.4 starts the application normally

## Snack, code example, screenshot, or link to a repository:
java.lang.RuntimeException: Unable to get provider androidx.core.content.FileProvider: java.lang.ClassNotFoundException: Didn't find class "androidx.core.content.FileProvider" on path: DexPathList

**Comment by safaiyeh** [comment]
Hi @luyouwei66 thanks for the issue. Can you please fill out all the sections of the issue template? Thanks!

**Comment by dulmandakh** [comment]
React Native doesn’t include Multidex support, but you can add it just like native Android applications per Multidex documentation. Please refer to Multidex documentation.

Closing the issue because the issue tracker is intended for only tracking bug reports in React Native.
