### ISSUE TITLE
Android打包后TouchableOpacity点击延迟的问题

### ISSUE THREAD

**Issue by hou666** [facebook/react-native#29719]
如题，Android打包后某一个TouchableOpacity点击跳转的时候会延迟很久，无报错、跳转的时候并无请求接口，延迟20s+之后仍会跳转到指定页面，并请求页面上的数据，正常显示。
这个延迟很莫名，找不到原因。。。。
前提：模拟器、真机，在调试状态都是反应流畅，并无延迟。仅打包后会出先这个问题。
写法如下：
<TouchableOpacity onPress={() => { this.props.navigation.navigate("PageA") }}>

**Comment by safaiyeh** [comment]
Hi @hou666 can you fill out the template? thank you!
