### ISSUE TITLE
Malformed calls are different: field sizes are different.

### ISSUE THREAD

**Issue by shubuu97** [facebook/react-native#29720]
While scrolling down in a FlatList this error randomly shows up sometimes. It doesn't shows any meaningful error other than these numbers.

## React Native version:
System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
    Memory: 213.17 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.17.0 - ~/.nvm/versions/node/v12.17.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.7 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /Users/shubhamchitransh/.rvm/rubies/ruby-2.7.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2

## Steps To Reproduce
This error randomly shows up while scrolling items in FlatList.

## Expected Results

This warning shouldn't be displayed.

## Snack, code example, screenshot, or link to a repository:
![image](https://user-images.githubusercontent.com/33938128/90857077-fac97280-e3a0-11ea-9aa8-48a9415c17fe.png)

**Comment by safaiyeh** [comment]
Hi @shubuu97 could you provide. repro that demonstrates this error?

**Comment by SudoPlz** [comment]
I just posted a long answer here about what's happening and how to troubleshoot that: https://stackoverflow.com/a/67100389/1658268
