### ISSUE TITLE
Invalid hook call error after upgrading from 0.61.5 to 0.62.2 or further

### ISSUE THREAD

**Issue by MrtYlnzz** [facebook/react-native#29722]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
I have a yarn workspace monorepo project which contains a shared folder along with react-native and react projects. Before the upgrade I could build and run both native and web project with no issue. After upgrading to 0.62.2 or further versions I started getting invalid hook call error on both redux and react-navigation packages. 

## React Native version:
System:
    OS: macOS 10.15.1
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Memory: 3.64 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.12.0 - ~/.nvm/versions/node/v12.12.0/bin/node
    Yarn: 1.19.2 - /usr/local/bin/yarn
    npm: 6.11.3 - ~/.nvm/versions/node/v12.12.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  Languages:
    Java: 13.0.1 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce

1. Upgrade react-native version 0.62.2 or above while using monorepo.

## Expected Results
To build without any errors.

## Snack, code example, screenshot, or link to a repository:
![90789185-47fd0400-e30f-11ea-8a47-8a69f4d0b128](https://user-images.githubusercontent.com/6218537/90870099-cdc98f80-e3a1-11ea-91fc-75c4d702d9e1.png)
![90789515-afb34f00-e30f-11ea-8b61-5119cbb8afce](https://user-images.githubusercontent.com/6218537/90870120-d4580700-e3a1-11ea-9bc8-41aae6854775.png)

**Comment by safaiyeh** [comment]
Hi @MrtYlnzz thanks for the issue! To investigate, could you provide a repro that consistently throws this error? Thanks!

**Comment by MrtYlnzz** [comment]
Hello @safaiyeh here is a demo repo showing the said error. It's a simple setup of what I use. https://github.com/MrtYlnzz/rn-invalid-hook.git

**Comment by givethemheller** [comment]
Can confirm same issue. Fire up the CLI and build a TS project. Make a component with a hook. Consume it at app.tsx

regressing versions right now to confirm the roll back.

**Comment by safaiyeh** [comment]
@MrtYlnzz I checked the repo you provided, I do not see any usage of hooks? Could you point it out to me, I must be missing something.

**Comment by MrtYlnzz** [comment]
@safaiyeh That's actually what the issue is, react-navigation do use hooks inside their functions and whenever I import react-navigation it gives the mentioned error.

**Comment by safaiyeh** [comment]
Got it, could you make an issue with react-navigation? This should be a common problem they have seen they should have ways to help you.
