### ISSUE TITLE
Chinese dynamic style not working for TextInput 

### ISSUE THREAD

**Issue by marlti7** [facebook/react-native#29723]
I also have a question. if we remove `style={{ fontSize }}` in TextInput, the font size still change due to TextInput Ref. Why?

_Originally posted by @soqt in https://github.com/facebook/react-native/issues/26107#issuecomment-522822554_

**Comment by safaiyeh** [comment]
Hi @marlti7 could you fill out the issue template?

**Comment by marlti7** [comment]
> Hi @marlti7 could you fill out the issue template?

same with #26107

**Comment by marlti7** [comment]
> > Hi @marlti7 could you fill out the issue template?
> 
> same with #26107

just for ios, android is work

**Comment by wbq813** [comment]
same problem with me, number and english work for ios, chinese works for android

**Comment by safaiyeh** [comment]
@marlti7 closing, please create a new issue with the issue template filled out. It helps us start an investigation and triage the issues better.
