### ISSUE TITLE
[iOS] Crash in ARTNode setShadow

### ISSUE THREAD

**Issue by zhfwch** [facebook/react-native#29721]
## Description
setShadow

## React Native version:
0.62.2
Xcode Version 12.0 beta 3
iOS 14 beta

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. use ReactNativeART to set shadow
2. crash 

## Expected Results
Shadows show normally

## Snack, code example, screenshot, or link to a repository:
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0xb1e9fb56920)
    frame #0: 0x000000010e031788 libobjc.A.dylib`objc_release + 8
  * frame #1: 0x00000001030569b3 `__destructor_8_s24(dst=0x00007ffeee284df8) at ARTNode.m:48:1
    frame #2: 0x0000000103056cc7 `-[ARTNode renderContentTo:](self=0x00007ff248dd9950, _cmd="renderContentTo:", context=0x000060000316a700) at ARTNode.m:0
    frame #3: 0x0000000103056a98 `-[ARTNode renderTo:](self=0x00007ff248dd9950, _cmd="renderTo:", context=0x000060000316a700) at ARTNode.m:64:5
    frame #4: 0x0000000103057d0c `-[ARTRenderable renderTo:](self=0x00007ff248dd9950, _cmd="renderTo:", context=0x000060000316a700) at ARTRenderable.m:70:5
    frame #5: 0x0000000103056093 `-[ARTGroup renderLayerTo:](self=0x00007ff248dceb70, _cmd="renderLayerTo:", context=0x000060000316a700) at ARTGroup.m:20:5
    frame #6: 0x0000000103056ab0 `-[ARTNode renderTo:](self=0x00007ff248dceb70, _cmd="renderTo:", context=0x000060000316a700) at ARTNode.m:65:5
    frame #7: 0x0000000103058d22 `-[ARTSurfaceView drawRect:](self=0x00007ff248e9ab50, _cmd="drawRect:", rect=(origin = (x = 0, y = 0), size = (width = 260, height = 260))) at ARTSurfaceView.m:52:5
    frame #8: 0x0000000126f7d49d UIKitCore`-[UIView(CALayerDelegate) drawLayer:inContext:] + 625
    frame #9: 0x000000010bd936d5 QuartzCore`-[CALayer drawInContext:] + 288
    frame #10: 0x000000010bc50d1d QuartzCore`CABackingStoreUpdate_ + 190
    frame #11: 0x000000010bd9cd81 QuartzCore`invocation function for block in CA::Layer::display_() + 53
    frame #12: 0x000000010bd92f12 QuartzCore`-[CALayer _display] + 2111
    frame #13: 0x000000010bda66ef QuartzCore`CA::Layer::layout_and_display_if_needed(CA::Transaction*) + 463
    frame #14: 0x000000010bce7204 QuartzCore`CA::Context::commit_transaction(CA::Transaction*, double, double*) + 496
    frame #15: 0x000000010bd1ded3 QuartzCore`CA::Transaction::commit() + 783
    frame #16: 0x000000010bd1f08f QuartzCore`CA::Transaction::observer_callback(__CFRunLoopObserver*, unsigned long, void*) + 79
    frame #17: 0x0000000108d98cff CoreFoundation`__CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
    frame #18: 0x0000000108d93836 CoreFoundation`__CFRunLoopDoObservers + 487
    frame #19: 0x0000000108d93d67 CoreFoundation`__CFRunLoopRun + 1137
    frame #20: 0x0000000108d93542 CoreFoundation`CFRunLoopRunSpecific + 538
    frame #21: 0x0000000114acbdb3 GraphicsServices`GSEventRunModal + 139
    frame #22: 0x0000000126a2a14e UIKitCore`-[UIApplication _run] + 912
    frame #23: 0x0000000126a2f1b1 UIKitCore`UIApplicationMain + 101
    frame #24: 0x0000000101da1c2d `main(argc=1, argv=0x00007ffeee287d80) at main.m:16:16
    frame #25: 0x000000010f419411 libdyld.dylib`start + 1

**Comment by safaiyeh** [comment]
Hi @zhfwch thanks for the issue. Art was moved to a community for future maintenance please checkout https://github.com/react-native-community/art
