### ISSUE TITLE
Invalid `Podfile` file: cannot load such file -- /Users/trammbp/Downloads/react-native-develop/myproject/node_modules/@react-native-community/cli-platform-ios/native_modules.

### ISSUE THREAD

**Issue by tramnguyengh** [facebook/react-native#29730]
I tried to build a project from an existing source.
I go to the project folder and run _yarn install_, it throws errors:

 YN0001: │ HTTPError: @react-native-lightkits/android-keyboard-adjust@npm:^1.0.0: Response code 404 (Not Found)
    at s.<anonymous> (/Users/trammbp/.yarn/releases/yarn-2.1.1.cjs:23:36333)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
➤ YN0000: └ Completed in 1.61s
➤ YN0000: Failed with errors in 1.62s

To continue I run _pod install_, and get the error

[!] Invalid `Podfile` file: cannot load such file -- /Users/trammbp/Downloads/react-native-develop/myproject/node_modules/@react-native-community/cli-platform-ios/native_modules.

 #  from /Users/trammbp/Downloads/react-native-develop/myproject/ios/Podfile:2
 #  -------------------------------------------
 #  platform :ios, '9.0'
 >  require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
 #  
 #  -------------------------------------------

Can anyone help me?

**Comment by safaiyeh** [comment]
Hi @tramnguyengh could you fill out all the sections of the issue template? Thanks

**Comment by dulmandakh** [comment]
It looks like @react-native-lightkits/android-keyboard-adjust package is not found. See error below.

YN0001: │ HTTPError: @react-native-lightkits/android-keyboard-adjust@npm:^1.0.0: Response code 404 (Not Found)

**Comment by Dilip-lohar** [comment]
https://github.com/facebook/react-native/issues/29413
fixed using the command :  pod repo update
