### ISSUE TITLE
React Native Android Crashing

### ISSUE THREAD

**Issue by AlecStein44** [facebook/react-native#29734]
## Description
Android users randomly get the error "Attempt to invoke virtual method 'android.graphics.drawable.Drawable android.graphics.drawable.Drawable$ConstantState.newDrawable(android.content.res.Resources)' on a null object reference FATAL EXCEPTION: main Process: com.reloadingallday.RADD, PID: 13733 java.lang.RuntimeException: Expo encountered a fatal error: Attempt to invoke virtual method 'android.graphics.drawable.Drawable android.graphics.drawable.Drawable$ConstantState.newDrawable(android.content.res.Resources)' on a null object reference"

This happens very randomly and with certain phones such as a Pixel 4. I can't seem to get this crash or similar crash on IOS or my web browser.

## React Native version:
    "expo": "^38.0.0",
    "expo-font": "~8.2.1",
    "react": "16.11.0",
    "react-dom": "16.11.0",

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Tap Load Development.
2. Tap Create New Load Development.
3. Tap either Temperature Stability Test, OCW Test, Range Test, DOPE Chart, Seating Depth Test.
4. Insert numbers in the text boxes.
5. Scroll down hit save.
6. Repeat 3, 4, 5 until the app crashes.

## Expected Results
No crashing or errors.

## Snack, code example, screenshot, or link to a repository:
![androidBug](https://user-images.githubusercontent.com/45604055/90962299-f1550e80-e463-11ea-8c21-8a45c81b694e.PNG)

https://snack.expo.io/@alecstein44/androidbug1

**Comment by safaiyeh** [comment]
Hi @AlecStein44 thanks for the issue! For expo related issues, could you file an issue on the expo repo?

Thanks! https://github.com/expo/expo
