### ISSUE TITLE
getting error while starting react native

### ISSUE THREAD

**Issue by kanwar002** [facebook/react-native#29731]
Anyone can help me? I'm new in react native i'm trying to start server but it's throwing that error
![Screenshot (34)](https://user-images.githubusercontent.com/56306542/90953038-e1e6bd00-e485-11ea-8723-707fd1925c31.png)
`

**Comment by safaiyeh** [comment]
Hi @kanwar002 it seems like you are using Expo, could you submit an issue to them? https://github.com/expo/expo

Thanks!
