### ISSUE TITLE
iOS crashes in release version

### ISSUE THREAD

**Issue by 26903651** [facebook/react-native#29739]
## Description
In debug mode or release ad hoc mode, the app is fine, but when I uploaded a release version to the apple 
store, the reviewers reported that the app crashed, but I couldn’t figure out the problem at all. Below is the crash log they fed me back. I’ve symbolized it.
[crash.log](https://github.com/facebook/react-native/files/5115481/crash.log)
## React Native version:
System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz
    Memory: 530.47 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.17.0 - /usr/local/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.4 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.6 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2

**Comment by safaiyeh** [comment]
Thanks for the issue @26903651. Could you provide more information to where this is happening? What components or actions trigger this? Also a repro would be helpful

**Comment by 26903651** [comment]
I have no more information. I tried all the methods to test. The debug mode will not crash, the ad hoc installation will not crash, and it is normal to use testflight to install the release package, but Apple reviewers report that it will crash. , I don’t know how to find this problem, my only resource is the crash log they provide

**Comment by 26903651** [comment]
II don't know what component is wrong. This problem has troubled me for more than 2 months. I started to think it was a version problem of react native. So I updated react native from 0.60 to 0.62 and uploaded to the apple store. The same feedback was received.

**Comment by 26903651** [comment]
![image](https://user-images.githubusercontent.com/16937789/91008764-a24cdc00-e611-11ea-84cc-f11b83296745.png)

**Comment by 26903651** [comment]
I created a testflight invitation code, you can install the app use this testflight code : KNVFCHLD

**Comment by farad4y** [comment]
@26903651 You can try Crashlytics to find the problem.

**Comment by saachitech** [comment]
@26903651 You can try bugsnag to find out the error or open issue on StackOverflow because this seems to issue with your code not react-native.

**Comment by safaiyeh** [comment]
@26903651 if this is still an issue, providing more investigation is needed. the crash log looks like it mentions AVAudioSession which is not part of core, could you confirm?

**Comment by 26903651** [comment]
Thank you for your attention. This crash log is confusing. I finally found out that it was caused by the push system.
