### ISSUE TITLE
error iOS project folder not found. Are you sure this is a React Native project?. Run CLI with --verbose flag for more details.

### ISSUE THREAD

**Issue by snowleopardAlex** [facebook/react-native#29733]
XCODE version: 11.6 (recently upgraded)
REACT-NATIVE version: 0.63.2 (the latest) 

PROBLEM: npx react-native run-ios throws an **error iOS project folder not found. Are you sure this is a React Native project?. Run CLI with --verbose flag for more details.**

I know this issue was here a long time ago, but I didn't find a solution to my problem. 
I created a react project with npx react-native init project name, I installed watchman, homebrew, node. 

My computer is brand new though I don't think so this has some meaning. My old Macbook was throwing the same error. 

Can you please help?

**Comment by safaiyeh** [comment]
Hi @snowleopardAlex please fill out all the sections of the issue template.

**Comment by snowleopardAlex** [comment]
I will add the necessary templates.
