### ISSUE TITLE
Archive Failed; Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by Zakyyy** [facebook/react-native#29738]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
I was trying to archive my project and then I got an error in the tests' target that Undefined symbols for architecture arm64

## React Native version:
ystem:
    OS: macOS 10.15.5
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 1.06 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.12.0 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
    Watchman: 4.7.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.Open xcode
2.Product -> Archive

## Expected Results
Build got archived

## Snack, code example, screenshot, or link to a repository:
<img width="574" alt="Screen Shot 2020-08-23 at 2 39 52 PM" src="https://user-images.githubusercontent.com/25394763/90978479-83394600-e54e-11ea-9f5d-c8f8d6f3ef96.png">

**Comment by safaiyeh** [comment]
Hi @Zakyyy thanks for the issue. Could you verify this happens on the latest RN version? Also to better investigate could you provide a repro or some hint to why this may be happening.

**Comment by SConaway** [comment]
@Zakyyy what architectures are you building for? Open the project in Xcode, then open the target in the editor (double click it's name in the directory view on the left, then open the Build Settings Tab. Make sure all options are shown, then it's Architectures > Architectures. See the screenshot for clarification.
![CleanShot 2020-08-25 at 18 11 50](https://user-images.githubusercontent.com/20807660/91243406-cd612980-e6fe-11ea-9de5-4477203322c0.png)
