### ISSUE TITLE
Error during 'npx init react-native NameOfProject'

### ISSUE THREAD

**Issue by SeasonLeee** [facebook/react-native#29744]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
There are errors during command `npx init react-native NameOfProject`, as you can see from screenshot:
![image](https://user-images.githubusercontent.com/13610283/91033822-96274580-e636-11ea-9d82-69e82ddd985b.png)

## React Native version:
I assume it's the latest or whatsoever... I can't even init the project, MAN!!!

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

Simply `npx init react-native NameOfProject`

I think you think see...

## Expected Results
Project init successfully?

besides, my os is macOS 10.15.6, not sure if this is the problem, I also use sudo when I tried to execute the command...

And, both my node and npm should be quite new, I think:
node: v14.5.0
npm: 6.14.5

what on earth is going on??????

**Comment by safaiyeh** [comment]
Hi @SeasonLeee react-native-cli issue board could help you out better! Can you make an issue over at https://github.com/react-native-community/cli, thanks!
