### ISSUE TITLE
[IOS] ScrollView previous momentum not remove when another scrolling

### ISSUE THREAD

**Issue by jong-hui** [facebook/react-native#29743]
Thank you for creating a great framework.
My English is not good, so please take it into consideration.

## Description
![image](https://user-images.githubusercontent.com/42797995/91022229-d505cd00-e62f-11ea-824e-a58796170f77.png)

### When a new scroll starts, the momentum that started before does not stop.
Next is my problem scenario.
OverScrolling(up) in ScrollView and scrolling down immediately(a short delay), I was able to get unwanted results.
The screenshot is outputting the results of onScroll events.
"-188" is overScrolling(up). After that, I immediately scrolled down (onTouchStart).
After "+99" I took off my hand and started my momentum, but as you can see from the screen shot.
The momentum started in overScrolling(up) was not deleted, such as "-18, -11, -5, -1.5, 0, 0".

The difference between positive and negative values is large, causing bug in my app.
![2020-08-24 17-20-06 2020-08-24 17_23_32](https://user-images.githubusercontent.com/42797995/91025802-d38ad380-e634-11ea-91bd-91323199acb6.gif)

## React Native version:
System:
    OS: macOS 10.15.5
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 192.63 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  Languages:
    Java: javac 14 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.2 => 0.63.2
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. append ScrollView your App
2. overscrolling and immediately scrolling down
3. check your onScroll event's e.nativeEvent.contentOffset

## Expected Results
When scrolling, the momentum that was started before must be stopped.

## Snack, code example, screenshot, or link to a repository:
Please take a look my screen shot.
If it's not enough, I'll give an example.

Thank you.

**Comment by safaiyeh** [comment]
Hi @jong-hui I appreciate your effort in the issue. Could you provide a Snack that demonstrates your error? It is helpful to quickly see the issue. Thanks!

**Comment by jong-hui** [comment]
https://snack.expo.io/!SAgdJI88

I think it's my mistake. In the example above (https://snack.expo.io/!SAgdJI88). If you act like my gif, you can implement a problem case. However, if you delete "setState(false)" from "onTouchStart," it works the way I want it to.
The momentum is printed as if it were not deleted. This brought me confusion. You can check it on the console.
I'll close the issue.
