### ISSUE TITLE
App doesn’t start when there are more than one .e2e.js mock file

### ISSUE THREAD

**Issue by robto09** [facebook/react-native#29740]
Hellow! I have a file called actions.e2e.js which inside has some action(redux) mocked. I added another file called selectors.e2e.js which have 2 mock selector(redux) methods. Idea its to replace selectors.ts file in execution time. Issue is than when add the selector.e2e.js file with 2 mock selectors inside the app get stuck and dont start running..

Desktop OS/version used to run Appium: Catalina
Node.js version (unless using Appium.app|exe): 14.5.0
Npm or Yarn package manager: 6.14.8
Mobile platform/version under test: iOS
Real device or emulator/simulator: Simulator

My config:

```
const { sourceExts } = require('metro-config/src/defaults/defaults');


module.exports = {
  resolver: {
    get sourceExts() {
      const exts = process.env.RN_SRC_EXT
        ? process.env.RN_SRC_EXT.split(',').concat(sourceExts)
        : sourceExts;
      return exts;
    },
  },
  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: false,
      },
    }),
  },
};```

Envirommnet

```
System:
    OS: macOS 10.15.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 10.46 GB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.5.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 27, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.0
      System Images: android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  Languages:
    Java: 14.0.1 - /usr/local/opt/openjdk/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.9.0 => 16.9.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by safaiyeh** [comment]
Hi @robto09 thanks for the issue. Could you provide a repro that demonstrates this issue?

**Comment by robto09** [comment]
> Hi @robto09 thanks for the issue. Could you provide a repro that demonstrates this issue?

I can not provide a video in this moment because of copyright. What happens is that there is a file called actions.ts which inside has some methos for auth like to do login,logout,register, verify code etc from aws. And I need to mock that methods , for example in order to register a new user, I can not get a token from cognito each time I run the test to validate the user.. So there is an actions.e2e.js which inside has this same methods that actions.js but mocked, I mean just with function declaration and empty body or just with redux dispatch inside but without logic.. And its works fine when run ```RN_SRC_EXT=e2e.js react-native start ``` but if I create another file like lest say selectors.e2e.js in order to mock some selectors, when run the test the app get stuck and then test crash..

**Comment by safaiyeh** [comment]
This might be either a bundler issue which should be filed here https://github.com/facebook/metro

RN_SRC_EXT is a command from Detox. Closing as this isn't an issue for React Native core

**Comment by robto09** [comment]
This issue was fixed. Thanks
