### ISSUE TITLE
[Android] <Button /> crashing the app for Android API 16

### ISSUE THREAD

**Issue by akgunfu** [facebook/react-native#29747]
## Description
Using the button component crashes the app for android api 16. 

## React Native version:
```
System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.52 GB / 16.00 GB
    Shell: 5.0.11 - /usr/local/bin/bash
  Binaries:
    Node: 14.7.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.7 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0. - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 26, 27, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.1
      System Images: android-16 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0.1 4.0.1
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_222 - /Users/akgunfu/.jenv/shims/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
1. Create a test app `npx react-native init Test`
2. Modify App.js like following `const App: () => React$Node = () => {
  return <Button title={'test'}/>
};`

## Expected Results
Should render the button.

## Snack, code example, screenshot, or link to a repository:
<img width="719" alt="Screen Shot 2020-08-24 at 18 44 22" src="https://user-images.githubusercontent.com/11071496/91066012-d76d2480-e639-11ea-82a0-337c56b0953b.png">

**Comment by safaiyeh** [comment]
Thanks @akgunfu for the issue. That is unfortunate! Could you provide a repo that I could build?

**Comment by akgunfu** [comment]
Hi @safaiyeh, [Here](https://github.com/akgunfu/buttonCrashExample) is the basic example of the issue. 
Here are some things I noticed so far:
On android Button implements TouchableNativeFeedback and there it decides backgroundProp like following in **TouchableNativeFeedback.js:339**:
`const getBackgroundProp =
  Platform.OS === 'android'
    ? (background, useForeground) =>
        useForeground && TouchableNativeFeedback.canUseNativeForeground()
          ? {nativeForegroundAndroid: background}
          : {nativeBackgroundAndroid: background}
    : (background, useForeground) => null;`

Simply changing it to 
`const getBackgroundProp =
  Platform.OS === 'android'
    ? (background, useForeground) =>
        useForeground && TouchableNativeFeedback.canUseNativeForeground()
          ? {nativeForegroundAndroid: background}
          : Platform.Version >= 21 ? {nativeBackgroundAndroid: background} : null
    : (background, useForeground) => null;`
prevents crashes for android 4.x.x. But I have not checked for any side effects so I did not follow up

**Comment by gedeagas** [comment]
@akgunfu I created related pr about this here. https://github.com/facebook/react-native/pull/29752. I think there is no need to check again for `Platform.Version >= 21 ` because `nativeForegroundAndroid` can only support Android > M. Hence the existing canUseNativeForeground check should suffice.

https://github.com/facebook/react-native/blob/6d175f2c257fe1acb1c36b15bc97bdb77560885c/ReactAndroid/src/main/java/com/facebook/react/views/view/ReactViewManager.java#L167

**Comment by safaiyeh** [comment]
@gedeagas appreciate the PR!

**Comment by safaiyeh** [comment]
React Native master branch has been updated to only support  API >= 21 closing as this will not be supported anymore
