### ISSUE TITLE
Wrong width on text component with multiline content for Android

### ISSUE THREAD

**Issue by nicocolascrete** [facebook/react-native#29749]
## Description

A react-native Text component with multiline content should automatically scale the width of the longest line. It works fine on ios but not on Android.

## React Native version:
0.63.2

## Steps To Reproduce
- display Text component on one line -> auto-scaling width ok on ios and android
- display Text component with multiline -> auto-scaling width ok on ios and nut not on android

## Expected Results
The text component should automatically scale the width of the longest line.

## Snack, code example, screenshot, or link to a repository:
COMPONENT :
```bash
interface Props {
    label: string;
}

class ChatBubble extends Component<Props> {
    // --------------------------
    // RENDER
    // --------------------------
    render() {
        return (
            <View
                style={[
                    styles.root,
                    this.props.align === DisplayAlign.Left ? styles.borderLeft : styles.borderRight,
                ]}>
                    <Text
                        style={
                            styles.label
                        }>
                        {this.props.label}
                    </Text>
            </View>
        );
    }
}
export default ChatBubble;
```
STYLE:
```bash
import {Fonts} from 'addict-common';
import {StyleSheet, Dimensions} from 'react-native';
import storyStyles from '../../../../core/styles/StoryStyles';
import ScreenUtils from '../../../../utils/screen/ScreenUtils';

const styles = StyleSheet.create({
    root: {
        display: 'flex',
        maxWidth: '85%',
    },
    label: {
        fontFamily: Fonts.MONTSERRAT_MEDIUM,
        fontSize: ScreenUtils.getFontScale() * 16,
        color: 'white',
        backgroundColor: 'red',
    },
});
export default styles;
```
![android](https://user-images.githubusercontent.com/351794/91082884-56049a80-e617-11ea-8588-b03e52bac8c9.jpg)
![ios](https://user-images.githubusercontent.com/351794/91082895-5b61e500-e617-11ea-8d04-d7167cb350a2.jpg)

**Comment by safaiyeh** [comment]
Thanks for the issue @nicocolascrete, I notice the extra space in the Android screen shot. Your code snippet has some dependencies, could you reproduce this in a Snack so it is easier to check out.

**Comment by nicocolascrete** [comment]
Hello @safaiyeh,
I add snack example below. But the trouble is not visible in this case. Just when I build the project directly on an android divice ...

https://snack.expo.io/EQTVYTon8

**Comment by nicocolascrete** [comment]
This bug appear when you add padding to the container view. I add this snack example.
I fix it on my side by adding an intermediate view with no padding

**Comment by thijs-qv** [comment]
As a workaround: replace the padding of the container with a margin.

**Comment by nicocolascrete** [comment]
Thanks @thijs-qv but it not very helpfull for this bug :)
I just want no extra space on the right.

**Comment by RogerParis** [comment]
Any updates on this?

**Comment by JerakRus** [comment]
I am faced with the same problem, which makes the layout very difficult in some moments. React-native 0.63.3. Any fix planned?

**Comment by safaiyeh** [comment]
Appreciate the repro! It confirms the issue.

**Comment by nicocolascrete** [comment]
Did we have a fix soon?

**Comment by LoKiLyn** [comment]
Any update on this issue?

**Comment by ilhamtubagus** [comment]
Any update on this issue?

**Comment by fabriziobertoglio1987** [comment]
@nicocolascrete @LoKiLyn @ilhamtubagus Do you still experience this issue? If yes, I will publish the fix in the react-native-improved package https://github.com/fabriziobertoglio1987/react-native-improved. Thanks a lot
