### ISSUE TITLE
openDrawer and closeDrawer methods from DrawerLayoutAndroid are not working.

### ISSUE THREAD

**Issue by octaviotastico** [facebook/react-native#29755]
## Description
The _openDrawer_ and _closeDrawer_ method are not working.
When I include the DrawerLayoutAndroid on my project, I can open the drawer by grabbing it from the border of the screen, but I'm not able to get it open by a button using those two methods.
The error says:
**Cannot read property 'current' of undefined.**

These two are screens from my computer, but the same error displays on Snack too.
![image](https://user-images.githubusercontent.com/17755300/91114812-26798080-e65f-11ea-888c-9b06b8d96236.png)
![image](https://user-images.githubusercontent.com/17755300/91114831-2da08e80-e65f-11ea-849e-75e9f89ed525.png)

Snack error:
![image](https://user-images.githubusercontent.com/17755300/91114893-5032a780-e65f-11ea-91a4-04b32e2988e3.png)

## React Native version:
0.62.17 on my pc (I don't know what version snack uses, but it doesn't work there too)

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.
1. Import DrawerLayoutAndroid from react-native
2. Insert the function openDrawer inside a button
3. Press it.

## Expected Results
I expect that when I press a button that calls the function "openDrawer", the drawer gets opened.

## Snack, code example, screenshot, or link to a repository:
https://snack.expo.io/MPvVLadrx

**Comment by gedeagas** [comment]
Hey @octaviotastico, thanks for filling an issue but this is not a bug. You can't just call `openDrawer` like this `DrawerLayoutAndroid.prototype.openDrawer()`, you will need to use `ref`. 

Working example here.
https://snack.expo.io/YOUAYlOEe

I suggest you to read this https://reactjs.org/docs/refs-and-the-dom.html.

**Comment by safaiyeh** [comment]
Hi @octaviotastico thanks for the issue. This has been moved to a community repo here: https://github.com/react-native-community/react-native-drawer-layout

Future issues will be addressed on that repo. Thanks!
