### ISSUE TITLE
Load Dynamically generated js produced by Native application

### ISSUE THREAD

**Issue by ekrivopaltsev** [facebook/react-native#2975]
I have a question. I have an idea of generating ReactNative js on a fly by Native IOS application, but I did not find a way to load it. The AppDelegate examples use locallhost URL or offline bundle which contains a lot of "required" code generated by react-native CLI, is it anyway to create jsbundle by using a template or other mechanism ?

**Comment by matth3wga0** [comment]
I think you should download the js script, then try `eval` it, the same way as **webpack**'s [code splitting](https://webpack.github.io/docs/code-splitting.html) does

**Comment by cosmith** [comment]
@facebook-github-bot stack-overflow
