### ISSUE TITLE
Weird warning regarding style after upgrading to 0.63

### ISSUE THREAD

**Issue by tpakhoa1996** [facebook/react-native#29753]
## Description
Im getting this weird error:
 **ERROR    Warning: Failed prop type: Invalid prop `style` of type `object` supplied to `TextSectionHeader`, expected a single ReactElement type.**
![image](https://user-images.githubusercontent.com/10357532/91104395-0b376100-e6b1-11ea-9a2a-e868f600179c.png)
HeaderComponent
![image](https://user-images.githubusercontent.com/10357532/91104831-ee4f5d80-e6b1-11ea-808f-0ac4f3fbf89a.png)
TextSectionHeader
![image](https://user-images.githubusercontent.com/10357532/91104530-4e91cf80-e6b1-11ea-9dbd-d44f0039d413.png)

## React Native version:
react: "16.13.1",
react-native: "0.63.2"

**Comment by chequochuu** [comment]
I encountered the same issue. Do you have any solution yet?
