### ISSUE TITLE
after loading error Image does not show defaultSource and does not respect style

### ISSUE THREAD

**Issue by voxspox** [facebook/react-native#29765]
## Description
I want to use [Image](https://reactnative.dev/docs/image.html) to display a remote PNG. Therefore I setup the URL in the `source` prop. Before the image is ready to be displayed I want to show a placeholder image. I used the `defaultSource` to a local asset/image.

## React Native version:
0.63.2

#### basic setup:
`<Image source=... defaultSource=... />`
local = require('....image.png')
remote = { uri: ... }

#### cases:

source=local
-> ok, shows local image

source=remote
-> ok, shows local image

defaultSource=local
source=malformed remote
-> I expect to see the local image but there is nothing.
Additionally, I setup a border in `style` but also this border is not shown.
onError is called as expected.

### and the docs:

Also it is not clear to me what is the difference between the following props, because both talk about "loading"

`defaultSource`
A static image to display while loading the image source.

`loadingIndicatorSource`
...displayed until image is ready to be displayed, typically after when it got downloaded from network.

## Snack, code example, screenshot, or link to a repository:
N/A

**Comment by gedeagas** [comment]
Hi @voxspox, thanks for the issue. Could you provide a repo/snack example that I could build? and also please note that on Android, the default source prop is ignored on debug builds. https://reactnative.dev/docs/image.html#defaultsource

**Comment by safaiyeh** [comment]
Thanks for the repro @voxspox, could you provide a repro that demonstrates this error. Thanks!

**Comment by dulmandakh** [comment]
@voxspox did you see a small note on defaultSource documentation https://reactnative.dev/docs/image.html#defaultsource? On Android, defaultSource image won’t be shown on debug builds because all images are served from metro server which makes all of them remote. But will work on release builds. I hope this helps.

**Comment by syedhaider03** [comment]
Experiencing the same issue on android in release build on react native 0.63.2, default source prop is not working and sometimes giving image splash and becomes invisible again, plus the default source is also not respecting the image style.

**Comment by syedhaider03** [comment]
![ezgif com-gif-maker](https://user-images.githubusercontent.com/43629380/94932286-4e6fc580-04e2-11eb-8147-f650bce54a3c.gif)

**Comment by DracotMolver** [comment]
I facing the same issue with a **Release** mode. The image actually is displayed during a few seconds, but after I've got a success/failure response from the source prop loading an external image, in android, the defaultSource disappear
