### ISSUE TITLE
Start using Jest's "modern" fake-timer implementation.

### ISSUE THREAD

**Issue by chrisbobbe** [facebook/react-native#29767]
Recent improvements have been made to Jest's implementation of fake timers, on an opt-in basis, with a plan to make them the default in the future: https://github.com/facebook/jest/pull/7776.

Some prep work has been done toward this (https://github.com/facebook/react-native/pull/29011), but I don't find an existing issue for the actual change.

Simply flipping the switch to the "modern" implementation gives several test failures, likely due to some combination of 

- dependency on wrong semantics of the legacy implementation, and
- https://github.com/facebook/jest/issues/10221

I'm excited for `facebook/react-native`'s own tests to be made more correct, but I particularly hope to draw attention to the fact that React Native apps can't currently use the new implementation (https://github.com/facebook/jest/issues/10221, https://github.com/facebook/react-native/issues/29303, https://github.com/facebook/react-native/pull/29754). This is a problem for apps that can't use the legacy implementation either, because of its issues (not having `Date.now()` faked is a big one).

## React Native version:

v0.61.5. (See https://github.com/facebook/react-native/issues/29767#issuecomment-691334464, below, for more environment info.)

**Comment by chrisbobbe** [comment]
Ah, here's the missing environment info for the bot 🙂:

```
System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 2.87 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.12.1 - ~/.nvm/versions/node/v12.13.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.7, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 27.0.3, 28.0.3, 29.0.2
      System Images: android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.7/11E801a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5
```

**Comment by safaiyeh** [comment]
Hi @chrisbobbe thanks for the request & all the details. 

You opened a PR here: https://github.com/facebook/react-native/pull/29754/files

Would this resolve the Jest issue, if merged in?
