### ISSUE TITLE
react-native run-ios : build failed

### ISSUE THREAD

**Issue by MarcoDo99** [facebook/react-native#29766]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
When I try react-native run-ios the build fails.

When I try to build the xcodeproject in Xcode I get the error "module map file '/Users/myuser/Library/Developer/Xcode/DerivedData/myapp-ayblecstspgajagnjznbpmfzwnas/Build/Products/Debug-iphonesimulator/YogaKit/YogaKit.modulemap' not found"

However, when I try to build the xcodeworkspace the build succeeds and works as expected. 

By accident, I had moved the files main.jsbundle , AppDelegate.h, AppDelegate.m, Info.plist, and main.m from the xcodeproject to the trash earlier today which caused the build to fail afterwards, but since then I have recovered them and made the xcworkspace work again. 

## React Native version:
Run `react-native info` in your terminal and copy the results here.
System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 22.43 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
    Yarn: Not Found
    npm: 6.14.7 - ~/.nvm/versions/node/v12.18.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.1 - /usr/bin/javac
    Python: 2.7.16 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
  npmGlobalPackages:
    *react-native*: Not Found
## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. npx react-native run-ios

## Expected Results

Before  I had the accident with moving the files to the bin, everything worked fine.

**Comment by safaiyeh** [comment]
Hi @MarcoDo99, thank you for the issue, this would be more appropriate for StackOverflow. Issue board here is about problems with React Native itself.
