### ISSUE TITLE
PlatformColor does not work properly on Android

### ISSUE THREAD

**Issue by sallar** [facebook/react-native#29763]
## Description
`PlatformColor` documentation clearly says that if I want to use the values of `R.attr` in Android, I have to use `?attr/VALUE`, but when I use for example `?attr/textColorPrimary`, the app crashes on Android or throws an error.

https://developer.android.com/reference/android/R.attr#textColorPrimary

## React Native version:
```
System:
    OS: macOS 10.15.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 789.87 MB / 32.00 GB
    Shell: 5.8 - /usr/local/bin/zsh
  Binaries:
    Node: 12.14.1 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 26, 27, 28, 29
      Build Tools: 23.0.1, 27.0.3, 28.0.1, 28.0.3, 29.0.2
      System Images: android-25 | Google APIs ARM 64 v8a, android-25 | Google APIs ARM EABI v7a, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: 20.0.5594570
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_232 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce

1. Paste this into your code: `<Text style={{color: PlatformColor('?attr/textColorPrimary')}}>Test</Text>`
2. Run your code on Android

## Expected Results
The app should not crash.

## Snack, code example, screenshot, or link to a repository:

![image](https://user-images.githubusercontent.com/768052/91163770-c32b3500-e6d6-11ea-848e-958c0e9c3fa2.png)

**Comment by safaiyeh** [comment]
Hi @sallar thanks for the issue! Could you provide a Snack or repo that consistently shows the crash?

**Comment by sallar** [comment]
@safaiyeh I've created a repo for this. Uncomment line 21-23 of `App.js` and the app crashes on Android.
https://github.com/sallar/PlatformColorBugReproduce

**Comment by safaiyeh** [comment]
@sallar thanks for the repro. The crash is reproduced on my end.

Two things:
1. It should not crash when there is an invalid color attribute
2. textColorPrimary should be valid.

Narrowed it down to this file https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/bridge/ColorPropConverter.java

Maybe @tom-un could take a look?

**Comment by sallar** [comment]
@safaiyeh exactly. If the error happens on first render, the app crashes completely and exits. I had to film the screen and slow it down to see the error because it exits so fast.

**Comment by sallar** [comment]
No it has not been fixed.

**Comment by fabriziobertoglio1987** [comment]
I will take a look tomorrow 

@hank121314 wrote pr  https://github.com/facebook/react-native/pull/29830 that fixes other problems with Platform Color and may be interested in this issue as he know well the sourcecode.

Thanks a lot

**Comment by hank121314** [comment]
This issue seems to cause by `getIdentifier("textColorPrimary", ATRR, packageName)` return `0`.
At here:
https://github.com/facebook/react-native/blob/a65cd683aee40fbb0433f43e15b8366dc1fa02a4/ReactAndroid/src/main/java/com/facebook/react/bridge/ColorPropConverter.java#L113

This needs further investigation to identify why `getIdentifier("textColorPrimary", ATRR, packageName)` will return 0. 😢

**Comment by fabriziobertoglio1987** [comment]
thanks @hank121314 

The error says `ColorValue None of the paths in the resource paths array resolved to a color resource`

`resourceId = 0` is not an acceptable value for `theme.resolveAttribute(resourceId, outValue, true)` and returns false and this triggers the runtime at 

https://github.com/facebook/react-native/blob/a65cd683aee40fbb0433f43e15b8366dc1fa02a4/ReactAndroid/src/main/java/com/facebook/react/bridge/ColorPropConverter.java#L122

`getIdentifier` returns `0` if the resource was not found.

<image src="https://user-images.githubusercontent.com/24992535/110136431-f8c08180-7dcf-11eb-93e5-0603ae20ec91.png" height="80" /> 

https://developer.android.com/reference/android/content/res/Resources#getIdentifier(java.lang.String,%20java.lang.String,%20java.lang.String)

`colorPrimary` is part of `appcompat` android library

https://github.com/facebook/react-native/blob/fb974ced7d68aed498efdc1ecb45d736364b3373/ReactAndroid/build.gradle#L445
https://stackoverflow.com/a/63530665
https://developer.android.com/reference/android/R.attr#colorPrimary

we have the library installed and do not understand why `colorPrimary` is not available
I have been searching in https://github.com/androidx/androidx but don't have any idea right now

**Comment by wouterds** [comment]
Is anyone looking into this? Works nicely on iOS but on Android it crashes for most of the values.

**Comment by retyui** [comment]
issue reproduced in 0.72.3

**Comment by retyui** [comment]
.

**Comment by shubhamguptadream11** [comment]
@fabOnReact @hank121314 
I also faced this issue recently.
I digged down here by using the findings shared above and found that by replacing packageName with android it got resolved.
I am raising a PR for the same.

**Comment by shubhamguptadream11** [comment]
I observed that problem is not just with textPrimaryColor.
Here are few other examples where resourceID is coming as null.

```
textColorPrimary
textColorSecondary
windowBackground
navigationBarColor
statusBarColor
```
All these cases will be handled with packageName "android".

**Comment by shubhamguptadream11** [comment]
@cortinico Fix for this has been merged. We can close this ticket now.
Thanks everyone!
