### ISSUE TITLE
 navigate   pageA(rn)-->pageB(native)--->pageC(rn) 

### ISSUE THREAD

**Issue by hxzAugustinus** [facebook/react-native#29769]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
  navigate   pageA(rn)-->pageB(native)--->pageC(rn) 

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.   use `npx react-native init ` creat  project  and use  reactnavigation  as   route;
2.   use  react  native  create   PageA  and  PageC   and   use   native   create  PageB ;
3.   in  PageA  i  use  `NativeModules.xxx`  navigate  PageB ;
4.  so   can i   navigate  from  PageB  to PageC  ?  if  ok  , how  to  do  it ?

**Comment by listenzz** [comment]
You could use `react-native-navigation-hybrid` as Navigation.

**Comment by dulmandakh** [comment]
The issue tracker is intended for only tracking bug reports in React Native. Please refer to React Navigation documentation, and deep links might work for your case
