### ISSUE TITLE
Hi @caishi3hao Did you find any solution for this? Even I'm getting this issue.

### ISSUE THREAD

**Issue by andyhaha** [facebook/react-native#29760]
use app file storage instead of SD Card

**Comment by chrisbobbe** [comment]
It's not at all obvious what this issue is about; I suspect it will be closed by an admin soon, or immediately, with a request to make a new issue that follows the template.

**Comment by safaiyeh** [comment]
Hi @andyhaha not sure what this is about 😅. Closing, please use the issue template for future issues thanks!
