### ISSUE TITLE
com.facebook.react.bridge.JSApplicationCausedNativeException: Illegal node ID set as an input for Animated.Add node

### ISSUE THREAD

**Issue by lucasluca** [facebook/react-native#29768]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Im developing an app in react native 0.62, and im having this issue in some moments on my app especially when i focus on a input, i already tried to fix all Elements key on map iterario. And this problem just happends on Andrroid.

## React Native version:
0.62.0

## Steps To Reproduce
There is no a specific step, some times when i click on a TextInput it gives me this error

## Expected Results
Do not crash the app

## Snack, code example, screenshot, or link to a repository:
I already changed Keys values in the code

**Comment by rainWang1123** [comment]
I have encountered the same problem, have you solved it？

**Comment by jeremycod** [comment]
Anyone found solution for this problem?

**Comment by Ashoat** [comment]
I've noticed this issue occurring when using `autoFocus` on a `TextInput` that appears on a React Navigation modal. If you are seeing this issue, try to replace `autoFocus` with a ref that calls `focus()` after a short delay.

**Comment by meliodev** [comment]
Same ! Many of my app's users get app crash because of this error. 
react-native: 0.63.2
react: 16.13.1
