### ISSUE TITLE
facebook::react::Recoverable: Could not open file/data/user/0/com.xxx.yyy/files/rn/main.jsbundle: No such file or directory

### ISSUE THREAD

**Issue by andyhaha** [facebook/react-native#29761]
I meet with the problem of my release app on line. help!
the React Native version is 0.60.4

stacktraces as follows:

com.facebook.jni.CppException
facebook::react::Recoverable: Could not open file/data/user/0/com.xxx.yyy/files/rn/main.jsbundle: No such file or directory
1 com.facebook.react.bridge.CatalystInstanceImpl.jniLoadScriptFromFile(Native Method)
--
2 com.facebook.react.bridge.CatalystInstanceImpl.loadScriptFromFile(CatalystInstanceImpl.java:233)
3 com.facebook.react.bridge.JSBundleLoader$2.loadScript(JSBundleLoader.java:47)
4 com.facebook.react.bridge.CatalystInstanceImpl.runJSBundle(CatalystInstanceImpl.java:261)
5 com.facebook.react.k.a(ReactInstanceManager.java:1175)
6 com.facebook.react.k.a(ReactInstanceManager.java:125)
7 com.facebook.react.k$5.run(ReactInstanceManager.java:951)
8 java.lang.Thread.run(Thread.java:929)

**Comment by safaiyeh** [comment]
Hi @andyhaha could you follow the issue template and verify this happens on the latest version?

**Comment by andyhaha** [comment]
> Hi @andyhaha could you follow the issue template and verify this happens on the latest version?

It happens on version 0.60.4

**Comment by andyhaha** [comment]
> Hi @andyhaha could you follow the issue template and verify this happens on the latest version?

It happens on version 0.60.4, and it is a release js bundle.

**Comment by andyhaha** [comment]
Is there a solution？

**Comment by piccinnigius** [comment]
any update?

**Comment by andyhaha** [comment]
still no answer for my problem？

**Comment by cmdparkour** [comment]
no answer, no work, and go home

**Comment by desunbera** [comment]
I also have the same issue. I'm Using react-native 0.67.2

**Comment by luozhiran** [comment]
I have also the same issue . I'm Using react-native 0.67.3 

facebook::react::Recoverable: Could not open file/data/user/0/com.yaya.zone/files/rn-resource/RNBundle/index.android.bundle: No such file or directory

**Comment by BM-laoli** [comment]
AHA, I have the same problem

**Comment by BM-laoli** [comment]
AHA, I have the same problem

**Comment by BM-laoli** [comment]
Ha, guys, I found a way to deal with this
@safaiyeh @andyhaha 
React Native found in the C + + code, they are required to full amount of name, I suggest React Native to change the documentation!

         ((CatalystInstanceImpl)instance).loadScriptFromFile(filePath$Name,filePath$Name ,false);
         ((CatalystInstanceImpl)instance).loadSplitBundleFromFile( filePath$Name, filePath$Name);
         
        my filePath$Name like this  => ( /storage/emulated/0/Android/data/com.example.myapprnn/files/Bundle/staging/index.android.bundle  ) It comes from my File system in android

**Comment by shivam-gupta1996** [comment]
Any solution? Still facing the issue
react-native-code-push: 7.0.4
react-native: 0.68.6
