### ISSUE TITLE
[Android] overscroll issue for ScrollView with nestedScrollEnabled nested inside "inverted" FlatList

### ISSUE THREAD

**Issue by OlivierFreyssinet** [facebook/react-native#29776]
## Description
When nesting a ScrollView with the property `nestedScrollEnabled={true}` inside a FlatList that has the property `inverted={true}`, overscrolling the ScrollView makes the FlatList scroll in the opposite direction of where it is supposed to scroll.

[Illustrative video full res](https://github.com/OlivierFreyssinet/RNNestedScrollViewInvertedIssue/blob/master/docs/fullvid.mp4)

### Expected behaviour (happens in a non inverted FlatList)
FlatList not inverted: When the nested ScrollView is scrolled past its edges (overscroll), the FlatList scrolls in the correct direction
![gif of expected behaviour (not displayed for some reason)](http://github.com/OlivierFreyssinet/RNNestedScrollViewInvertedIssue/blob/master/docs/expected.gif)

### Buggy behaviour (happens in an inverted FlatList)
Flatlist inverted: When the nested ScrollView is scrolled past its edges (overscroll), the FlatList scrolls in the wrong direction
![gif of buggy behaviour](https://github.com/OlivierFreyssinet/RNNestedScrollViewInvertedIssue/blob/master/docs/expected.gif)

## React Native version:
```
System:
    OS: macOS Mojave 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
    Memory: 280.58 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 27, 28, 29
      Build Tools: 23.0.1, 27.0.3, 28.0.3, 29.0.0, 29.0.3
      System Images: android-28 | Google APIs Intel x86 Atom_64, android-29 | Intel x86 Atom_64
      Android NDK: 20.0.5594570
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6308749
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_212 - /usr/bin/javac
    Python: 2.7.10 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

## Snack, code example, screenshot, or link to a repository:
Full repro available here: https://github.com/OlivierFreyssinet/RNNestedScrollViewInvertedIssue

**Comment by OlivierFreyssinet** [comment]
Is there a way to at least disable this overscroll behaviour ? i.e. when the nested scrollview is overscrolled, don't scroll the parent view at all.

**Comment by Burzo** [comment]
I'm also facing this issue, didn't find a solution as of yet. Any help is appreciated.

**Comment by OlivierFreyssinet** [comment]
this issue has not been fixed
