### ISSUE TITLE
KeyboardAvoidingView animation doesn't match keyboard on iOS

### ISSUE THREAD

**Issue by JackShannon** [facebook/react-native#29772]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
The KeyboardAvoidingView animation doesn't match the keyboard on iOS. Here is a slow motion gif of it on an iPhone 6 to see clearly. I also get the same result in the iPhone 11 simulator on a Macbook.

![ezgif-7-166fc6bd6a6f](https://user-images.githubusercontent.com/865983/91291431-f4fed300-e78c-11ea-8a94-acbd553bf824.gif)

Either the start time of the animation is wrong (due to crossing the bridge?), or the easing curve doesn't match up.

## React Native version:
0.62
(Expo 38.0.0)

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Run the snack on an iPhone

## Expected Results
The pacing of the animation to be in sync with the keyboard.

Lots of iPhone apps get this animation right so it should be possible to get it matching up.

Would love to hear if there is a workaround that I can use.

## Snack, code example, screenshot, or link to a repository:
https://snack.expo.io/@jackshannon/keyboardavoidingview-example

**Comment by sammy-SC** [comment]
Hello @JackShannon 

thanks for the report.

As a workaround you can use [inputaccessoryview](https://reactnative.dev/docs/inputaccessoryview). There we leverage `[UITextField inputAccessoryView]` and animation should match the keyboard's animation.

Regarding fixing `KeyboardAvoidingView`. This is something that's planned for React Native's new renderer.
cc @JoshuaGross

**Comment by JackShannon** [comment]
Thanks for this @sammy-SC 

Works perfectly for a TextInput.

However, I also have screens in my app that require a sticky button. Is it possible to always show the button rather than it being hidden until the keyboard slides up?

**Comment by sammy-SC** [comment]
> However, I also have screens in my app that require a sticky button. Is it possible to always show the button rather than it being hidden until the keyboard slides up?

Hmn, InputAccessoryView won't work with a button unfortunately. 
 I don't have an alternative solution.

**Comment by JackShannon** [comment]
> > However, I also have screens in my app that require a sticky button. Is it possible to always show the button rather than it being hidden until the keyboard slides up?
> 
> Hmn, InputAccessoryView won't work with a button unfortunately.
> I don't have an alternative solution.

OK thanks for your help.
