### ISSUE TITLE
App lags on ScrollView, Flatlist and Animation on android version 9,10

### ISSUE THREAD

**Issue by vikil143** [facebook/react-native#29773]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
App lags on the Android version above 8(i.e API level 28). I am upgraded my react native version from 61.5 to the latest(63.2) to tackle the laggy issue it's not resolved 

## latest version config which I upgraded
Run `react-native info` in your terminal and copy the results here.
System:
    OS: Linux 5.4 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i5-2500 CPU @ 3.30GHz
    Memory: 2.29 GB / 15.47 GB
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 13.10.1 - ~/.nvm/versions/node/v13.10.1/bin/node
    Yarn: Not Found
    npm: 6.14.5 - ~/.nvm/versions/node/v13.10.1/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 1.8.0_265 - /usr/bin/javac
    Python: 2.7.17 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
  npmGlobalPackages:
    *react-native*: Not Found

## previous version config
System:
    OS: Linux 5.4 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i5-2500 CPU @ 3.30GHz
    Memory: 2.29 GB / 15.47 GB
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 13.10.1 - ~/.nvm/versions/node/v13.10.1/bin/node
    npm: 6.14.5 - ~/.nvm/versions/node/v13.10.1/bin/npm
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1

## Expected Results
is there any way to tackle the laggy issue and works smooth

**Comment by abtoma** [comment]
https://reactnative.dev/docs/optimizing-flatlist-configuration Please consider these steps once this will help you rectifying your lagging issue and probably if your JS thread is doing lot of work in rendering of list and all It will throw certain warnings Please do lookout for those and try to resolve them. I hope this helps you in achieving desired result
