### ISSUE TITLE
[androidTV] Scrollview still scrollable with dpad when scrollEnabled={false}

### ISSUE THREAD

**Issue by TheDuc** [facebook/react-native#29774]
## Description
A scrollview with the `scrollEnabled` prop set to `false` still scrolls on tv remote dpad input on androidTV.
Also onScroll events are fired when the list is scrolled this way.

## React Native version:
0.61.5

## Expected Results
The scrollview should not scroll when `scrollEnabled` is set to false, regardless of touch, mouse or dpad input.

**Comment by gedeagas** [comment]
@TheDuc can you confirm this behavior still exist on the latest react-native version? 

Support for handling DPAD is just recently cherrypicked to react-native version 63.2.
https://github.com/facebook/react-native/commit/00c8b3cd09526c4a8afd141344793151ccb9ea0c

**Comment by TheDuc** [comment]
@gedeagas Thanks for your comment, but that merge is also in the 0.61.5 release.
Currently the `executeKeyEvent` method is overridden, but that does not seem to work correctly.
I have overridden the `dispatchKeyEvent` method with the same code, and that seems to work, but needs more testing

**Comment by gedeagas** [comment]
yeah, @TheDuc just tested this out and found out that it's not working on latest master. Doing some digging and I found out that `dispatchKeyEvent` works perfectly.

**Comment by gedeagas** [comment]
yeah, I just try this out yesterday and can confirm that it's not working.  And changing `executeKeyEvent` `dispatchKeyEvent` fixes the problem.

@TheDuc can you make a pr about this on `ReactHorizontalScrollView` & `ReactScrollView`. And thx for making an issue.

**Comment by safaiyeh** [comment]
Thanks for the issue @TheDuc and thank you for investigating @gedeagas!

Accepting this as a valid issue.

**Comment by TheDuc** [comment]
any updates on this? I created this merge request quite a long time ago, and nothing has happened.
The issue still persists even with the latest React-Native version (0.63.3 as of now)

**Comment by safaiyeh** [comment]
Hi @TheDuc thanks for the PR. You might have an easier time merging into react-native-tvos as they maintain Android TV as well

**Comment by TheDuc** [comment]
@safaiyeh Thanks for the response, I will create a PR for react-native-tvos, however, the readme and the name clearly state that it is mainly Apple TV focused.
Moreover, may I hereby conclude that the react-native "Learn once, write anywhere" paradigm is completely abandoned, as far as tv's are concerned anyways?

**Comment by safaiyeh** [comment]
Yeah I talked to the maintainer of tvos today. They are working on renaming and making it clear they are maintaining AndroidTV.

Core RN is focused on Android and iOS. Other platforms are maintained by other folks but are still unified in your app's codebase. Creating all native components for platforms is a big task for 1 repo, so it's spread out amongst people who have a bigger stake in other platforms

**Comment by prakash-altair** [comment]
@TheDuc I tried with overriding dispatchKeyEvent but it dosen't work scroll view still scrolls
I have a Vertical ScrollView with scrollEnabled={false} and inside it have a multiple HorizontalScrollView with scrollEnabled={false}. When Dpad up down is presses HorizontalScrollview which is present inside Vertical ScrillView moves like listview
![Screenshot_1605201615](https://user-images.githubusercontent.com/6103142/98973403-b54cb980-2539-11eb-8a03-e7f94dfae7ef.png)

**Comment by TheDuc** [comment]
@prakash-altair Indeed, the fix is not working anymore since this PR https://github.com/facebook/react-native/pull/25105.
If you revert only those changes and apply my fix, it will work again.

**Comment by prakash-altair** [comment]
@TheDuc 
Just doing changes mentioned [here](https://github.com/react-native-tvos/react-native-tvos/issues/128#issuecomment-727546066) will solve the issue. No need of changes as mentioned in your PR

**Comment by TheDuc** [comment]
@prakash-altair Thanks for raising this issue in the react-native-tvos repository and for your efforts!
That change does solve other issues for me but unfortunately not the scrolling issue.
I have a list of items and I only want to programmatically scroll to the next (scrollToIndex) on arrow press.
The behaviour I still see is that on arrow press the list scrolls a little bit first, and after that calls scrollToIndex and correctly scrolls to the next item.

**Comment by prakashjais99** [comment]
@TheDuc have you set scrollEnabled={false} working great for me after setting this prop
