### ISSUE TITLE
Weird behaviour with selection on Android

### ISSUE THREAD

**Issue by luizaugustocs** [facebook/react-native#29780]
## Description
After reseting the selection on a text input, the input keep reseting the selection to the value, which makes the cursor flickering as the user types something. This happens only on android, on iOS it works fine

Similar issue: https://github.com/facebook/react-native/issues/26047

## React Native version:
System:
    OS: macOS 10.15
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 47.43 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.7.0 - ~/.nvm/versions/node/v14.7.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.7 - ~/.nvm/versions/node/v14.7.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.4 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28
      Build Tools: 23.0.1, 25.0.2, 26.0.1, 26.0.2, 27.0.3, 28.0.3, 29.0.2
      System Images: android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64, android-27 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 3.6
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_162 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.9.0 => 16.9.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce

1. Type something on the input
2. Click the button
3. Try to type something again on the input

## Expected Results
The cursor should behave normally

## Snack, code example, screenshot, or link to a repository:
https://snack.expo.io/@luizaugustocs/d51a28

**Comment by CirChmod** [comment]
I faced the same issue and got some ideas [here](https://github.com/facebook/react-native/issues/29063#issuecomment-658615266)

As a workaround
```
inputRef.current.setNativeProps({
  selection: { start: 0, end: 0},
});
setTimeout(() => {
  inputRef.current.setNativeProps({
    selection: null
  });
});
```
Reset the selection native props to null after a delay
