### ISSUE TITLE
Android App crash: Fatal signal 11 (SIGSEGV), code 1

### ISSUE THREAD

**Issue by BravenxX** [facebook/react-native#29783]
## Description

When I run the app:

`react-native run-android`

On physical devices the application sometimes (just sometimes) just closes itself without visible error.  while in Android Emulator it works okay.

In android studio Logcat, as error throws me this when the app crashes:

`2020-08-26 18:17:22.063 21369-21417/com.geslubapp A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 21417 (mqt_js), pid 21369 (com.geslubapp)`

![image](https://user-images.githubusercontent.com/43297929/91364912-c48b5900-e7cd-11ea-8779-d3b8b4f69b51.png)

## React Native version:

react-native: 0.62.2
react: 16.11.0

**Comment by BravenxX** [comment]
For me it was because Realm.js [Issue](https://github.com/realm/realm-js/issues/3177)

**Comment by wutiange** [comment]
How do you know it's not a react native problem。

**Comment by wutiange** [comment]
> For me it was because Realm.js [Issue](https://github.com/realm/realm-js/issues/3177)

How do you know it's not a react native problem。

**Comment by roots-ai** [comment]
How to debug such an error?
