### ISSUE TITLE
Unable to initialize app with verison 0.59.10

### ISSUE THREAD

**Issue by scobo** [facebook/react-native#29781]
## Description
Unable to initialize a new app using the latest 0.59.x version, 0.59.10 as of this report. Initializing any newer version works, e.g., `npx react-native init demo --version 0.60.0` does not have this problem.

## React Native version:
0.59.10

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. `npx react-native init demo --version 0.59.10`

> ✖ Copying template
error Error: Couldn't find the "/var/folders/tb/wx5d6rj53qjdg6sr4bmb1l840000gn/T/rncli-init-template-kgOXPd/node_modules/react-native/template.config.js file inside "react-native" template. Please make sure the template is valid. Read more: https://github.com/react-native-community/cli/blob/master/docs/init.md#creating-custom-template

## Expected Results
App is initialized successfully.

## Snack, code example, screenshot, or link to a repository:
<img width="966" alt="Screen Shot 2020-08-26 at 12 51 48" src="https://user-images.githubusercontent.com/424925/91349996-ee775800-e79a-11ea-8390-8d26f01fe0cd.png">

**Comment by scobo** [comment]
Tried this as a workaround:

```
npx react-native@0.59.10 init demo --version 0.59.10
```

…but it fails as well:

> command not found: react-native

<img width="332" alt="Screen Shot 2020-08-26 at 13 14 03" src="https://user-images.githubusercontent.com/424925/91351988-069ca680-e79e-11ea-897e-2efa477ae9e6.png">

**Comment by TheSavior** [comment]
Heya! Good to cross paths again!

You'll probably get more help on the CLI repo over here: https://github.com/react-native-community/cli

It looks like they have documentation for using init that does mention the approach you are taking only works for >60. They have a section for how to init older versions here. It's kinda similar to what you tried last. https://github.com/react-native-community/cli/blob/master/docs/init.md#for-older-react-native-versions

**Comment by scobo** [comment]
@TheSavior Hi! Thanks for the info and quick response. 🙂

**Comment by scobo** [comment]
Could that link be added to the [environment setup docs](https://reactnative.dev/docs/environment-setup) as a note? Would have saved us some time and frustration.
