### ISSUE TITLE
React Native Expo cannot load my javascript file locally in webview!!

### ISSUE THREAD

**Issue by LordMilan** [facebook/react-native#29785]
Basically instead of using url of the script, i want to be able to use that script  locally from my app's own resources. so that i dont need internet connection for my app to work!!!! 

Im trying to use pdf.min.js file:
WORKING EXAPMPLE:
<script src="https://cdn.jsdelivr.net/npm/pdfjs-dist@2.1.266/build/pdf.min.js"></script> (IF I DO THIS THEN THE SCRIPT IS WORKS)

NOT WORKING:
    <script src="./pdf.min.js"></script> (IF I USE TRY TO USE IT LOCALLY THEN IT WONT WORK)

HOW DO I MAKE IT WORK IN REACT NATIVE EXPO   !!!!!!!(Dont give me answers which only works for REACT NATIVE CLI)

PLEASE SOMEONE HELP ME! or Should i switch to react native cli?
P.S. im new in react but i do know that im not making any error in my codes!

**Comment by hamdikahloun** [comment]
Hi @LordMilan 

Are you sure about ./pdf.min.js path ?

**Comment by LordMilan** [comment]
> Hi @LordMilan
> 
> Are you sure about ./pdf.min.js path ?

YES IM 100% sure! My problem is similar to this :
https://stackoverflow.com/questions/5733883/loading-javascript-into-a-uiwebview-from-resources/5810930#5810930

Image loading works fine if i mention the path but trying with js file doesnt seem to work!
i just wanna know if theres a workaround for this...im new and ive already wasted 2 days for this!

**Comment by dulmandakh** [comment]
Closing the issue because WebView is removed from React Native a while ago, and it’s recommended to use https://github.com/react-native-community/react-native-webview/. Please refer to its documentation, and injectJavascript might help.
