### ISSUE TITLE
iOS use_frameworks! broken in v0.63.2

### ISSUE THREAD

**Issue by Kjens93** [facebook/react-native#29789]
## Description
Support for the `use_frameworks!` directive in iOS podfiles was [fixed](https://reactnative.dev/blog/2019/09/18/version-0.61#other-improvements) in v0.61, however it seems to be broken again as of version 0.63.2. This is inconvenient because it means that CocoaPods plugins like [cocoapods-binary](https://github.com/leavez/cocoapods-binary) can't be used to speed up build times (because it requires use_frameworks).

## React Native version:
```
System:
    OS: macOS 11.0
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 1.07 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.18.1 - /var/folders/xc/tfq34tzd54qgz7njmw2rvs3w0000gn/T/yarn--1598547526259-0.19992129118969015/node
    Yarn: 1.22.4 - /var/folders/xc/tfq34tzd54qgz7njmw2rvs3w0000gn/T/yarn--1598547526259-0.19992129118969015/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v12.18.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /Users/kjensen/.gem/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 20.0, macOS 11.0, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 29, 30
      Build Tools: 28.0.3, 30.0.1
      System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 RC 1 4.1 RC 1
    Xcode: 12.0/12A8189n - /usr/bin/xcodebuild
  Languages:
    Java: 14.0.1 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: ~16.13.1 => 16.13.1 
    react-native: ~0.63.2 => 0.63.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Run `npx react-native init MyApp --template react-native-template-typescript && cd MyApp` (or clone the example repository)
2. Add `use_frameworks!` to `ios/Podfile`
3. Run `(cd ios && pod install)`

## Expected Results
![image](https://user-images.githubusercontent.com/15389109/91474010-ea107500-e856-11ea-87d2-f71bee0070a3.png)

## Actual Results
![image](https://user-images.githubusercontent.com/15389109/91474057-f8f72780-e856-11ea-8419-bd6a40e9b5b5.png)

## Snack, code example, screenshot, or link to a repository:
https://github.com/Kjens93/react-native-issue-29789

**Comment by safaiyeh** [comment]
Hi @Kjens93 thanks for the issue.

@alloy could you check this out?

**Comment by alloy** [comment]
This is due to Flipper dependencies, as described in the template’s Podfile (of newer RN versions) https://github.com/facebook/react-native/blob/6d3dcc72c58758c8818b75720b8a37a730e8d485/template/ios/Podfile#L16-L19

As of recently we do [build libevent from source](https://github.com/facebook/react-native/blob/master/third-party-podspecs/libevent.podspec), for macOS/Hermes at least, so I imagine Flipper might be able to switch to that at some point, but that still leaves OpenSSL.

In any case, this isn’t a bug or unknown issue. It should probably be raised in the Flipper repo for any traction. /cc @passy @mweststrate

**Comment by chrmod** [comment]
Removing Flipper does not help to get use_frameworks! to work. 

@alloy do you mean that react-native dropped support for `use_frameworks!` in version 63? There was already similar issue in release 61. /cc @grabbou

**Comment by alloy** [comment]
No that’s not what I mean, it is only when you build Flipper—specifically due to its prebuilt (as static) openssl/libevent dependencies.

**Comment by chrmod** [comment]
If that helps I can provide a simpler react-native@63 repo that will fail to compile any packaged native module with `use_frameworks!` present.

**Comment by chrmod** [comment]
@alloy please be so kind and take a quick look.

Steps to reproduce:
* `git clone https://github.com/chrmod/ReactNative63UseFrameworks`
* `cd ReactNative63UseFrameworks`
* `cd ios`
* `pod install`
* `cd ..`
* `yarn ios`

Linking of packaged native modules fails as it cannot see ReactNative symbols. In this example `react-native-fs` fails with:
```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_RCTEventEmitter", referenced from:
      _OBJC_CLASS_$_RNFSManager in RNFSManager.o
  "_OBJC_METACLASS_$_RCTEventEmitter", referenced from:
      _OBJC_METACLASS_$_RNFSManager in RNFSManager.o
  "_RCTRegisterModule", referenced from:
      +[RNFSManager load] in RNFSManager.o
ld: symbol(s) not found for architecture x86_64
```

But every Native Module will fail differently based on its dependencies.

**Comment by alloy** [comment]
Looks like this might be related to https://github.com/facebook/react-native/issues/29633#issuecomment-694187116

**Comment by chrmod** [comment]
@alloy Yes, I can confirm that's the same issue. I've applied your solution and the problem got resolved. Thank you.
