### ISSUE TITLE
Fetch failures on Android

### ISSUE THREAD

**Issue by ambarc** [facebook/react-native#29782]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Fetch POST and PUT requests, to https endpoints, fail with "Network request failed", on android simulator. We're observing this after upgrading from 0.59.10 to 0.61.5. We can't upgrade further (yet) given other dependencies breaking.

Observation: Adding a [Header](https://developer.mozilla.org/en-US/docs/Web/API/Headers) object to these requests, as opposed to empty, or JS' empty object `{}`, leads to different behavior. All these requests work as-is on iOS. See simplified code samples.

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

```
// works on 0.59.10. doesn't work on 0.61.5
fetch('target-url', {
    method: 'POST'
    headers: { h1: 'val1' } // fails where it used to succeed. Network Request Failed.
})

let h =  new Headers()
h.set('h1', 'val1')
fetch('target-url', {
    method: 'POST'
    headers: h // strangely succeeds.
})
```

## Expected Results
Expect prior requests from 0.59.10, as described above, to work across iOS and Android.

## Snack, code example, screenshot, or link to a repository:
See above.

**Comment by therealansh** [comment]
Are you using a localhost api? If so try changing the target url to http://10.0.2.2 for android emulator and if you are trying it on a real device try changing the endpoints to your computer's local IP address. But it is strange that it used to work before v0.61.5

**Comment by ambarc** [comment]
Ty! No, this is for a hosted API, not on local, using https.

**Comment by safaiyeh** [comment]
Hi @ambarc thanks for the issue! Is it similar to this? https://github.com/facebook/react-native/issues/29608

**Comment by ambarc** [comment]
It's very similar, but I think that issue might be running into broader problems. I'm trying to keep this issue open and focused on the presence of `Headers` being the difference between pass / fail on Android.

**Comment by safaiyeh** [comment]
Hi @ambarc looks like the issue I linked is closed and the author provided a bunch of details to resolve it. Could you give that a shot?

**Comment by brian-nicholls** [comment]
> Are you using a localhost api? If so try changing the target url to http://10.0.2.2 for android emulator and if you are trying it on a real device try changing the endpoints to your computer's local IP address. But it is strange that it used to work before v0.61.5

A similar solution worked for my. My local Rails API was running on `127.0.0.1:4001`. I'm using Expo, which was running my app on `10.0.0.5:19000` (my Mac's local IP). I changed my API URL when starting the rails server using `rails s -b 10.0.0.5` to match Expo.

It now works on my Android emulator and device.

**Comment by vTrip** [comment]
Hey @ambarc, leaving a comment to say thank you for sharing this, after many long hours and testing of different RN versions to try and narrow my problem, this has solved it for me.

My research has found that my issue showed up with the upgrade of android SDK versions specified in the `android/gradle` file. Going from 28 -> 29.

Modifying my HTTP service to create the headers via `new Headers()` as opposed to plain JS `headers = {}` which previously worked with no issues for outgoing POST requests solved it for me.

I am really curious to know if this is purely a type error and why RN / fetch API throws an error for this so strictly.

Anyway, thanks for sharing, very grateful.

**Comment by SohaibKtb** [comment]
+1

**Comment by flyskywhy** [comment]
[fixed `TypeError: Network request failed` when upload file to http not https with Android debug builds](https://github.com/facebook/react-native/issues/33217#issuecomment-1159844475)
