### ISSUE TITLE
iOS Linking getInitialURL() Cannot read, copy or use the file in the url

### ISSUE THREAD

**Issue by luhahaha** [facebook/react-native#29788]
When the app is killed and I open the app sharing a file (a zip file) if I try to unzip the file or try to copy it goes in error.
Seems it doesn't have the permissions for that file.

If I get the URL with the app open through addEventListener('url') I can use the file.

## React Native version:
0.61.5

**Comment by douglasjunior** [comment]
Same here o version 0.74.

Any updates on this?
