### ISSUE TITLE
Double slashes instead of tripple

### ISSUE THREAD

**Issue by macci10** [facebook/react-native#29796]
## Description
App was opening fine with myapp:// scheme. Suddenly it stopped opening with myapp:// scheme. I called Linking.makeUrl() and it returned myapp:///. Now when i open myapp:/// scheme the app works fine. I can't seem to find any place where this change happened. I want to use double slashes in my deeplink. It's an Expo App and the only configuration i can find for deeplink is setting the scheme in app.json file like "scheme": "myapp".

## React Native version:
System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i7-3740QM CPU @ 2.70GHz
    Memory: 276.79 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.7.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.7 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 26.0.2, 27.0.3, 28.0.3, 29.0.2
      System Images: android-28 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_211 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: ~16.13.1 => 16.13.1 
    react-native: https://github.com/expo/react-native/archive/sdk-38.0.1.tar.gz => 0.62.2

## Expected Results
I want to open my app with myapp:// with double forward slashes

**Comment by safaiyeh** [comment]
Hi @macci10 could you create a repro without expo? To demonstrate this happens on a clean React Native template? Thanks, this would help us narrow down the issue.

**Comment by macci10** [comment]
@safaiyeh I have created a new project with npx react-native init. There is no issue there. So i think it's the issue with Expo.
