### ISSUE TITLE
Invariant violation: "display" is not a valid style property.

### ISSUE THREAD

**Issue by marclundgren** [facebook/react-native#298]
```javascript
var React = require('react-native');
var styleSheet = React.StyleSheet.create({
  container: {
    display: 'inline-block'
  }
};
```
I've used `display` as a propery in `React` projects before. Does `React.native` have an exception for `display`?

I also couldn't use `borderRadius`, `boxShadow`, `textShadow`, `transition`.

**Comment by ide** [comment]
Those are CSS properties. See https://facebook.github.io/react-native/docs/flexbox.html#content for the list of styles that React's layout system supports.

**Comment by jaygarcia** [comment]
This was a learning curve for me too.  React Native implements a light CSS -like system. Once you break your bond with CSS, it becomes easier to use RN's style sheets.  

JG


:: sent from my mobile device ::

**Comment by marclundgren** [comment]
thanks @ide :)

**Comment by vjeux** [comment]
You can use flex-wrap and flexDirection: row to achieve display: inline-block

**Comment by sahrens** [comment]
And borderRadius should work in React Native.
