### ISSUE TITLE
Graphic problems on official react native page

### ISSUE THREAD

**Issue by JoseMoreville** [facebook/react-native#29802]
Hello, i was taking a look on react native page since i want to use it for one of my project and i realized there are some problems with the front-end when you hover some brand icons.

I'm pretty sure it's the size, background color and border of the anchor tags `<a></a>`

I'm not 100% if this post belongs here but hopefully it does.

**Image to show the bug**
[http://prntscr.com/u7rhgn](http://prntscr.com/u7rhgn)

**Comment by safaiyeh** [comment]
Thanks @JoseMoreville for the issue. Send over your issue to https://github.com/facebook/react-native-website, this issue board deals with React Native core issue.
