### ISSUE TITLE
Modal opens and closes when I update a variable using useState

### ISSUE THREAD

**Issue by adriano461997** [facebook/react-native#29806]
## Description
Whenever my application opens a modal and I try to update a variable using useState the modal opens and closes alone, in my modal there is a Switch that when I change the value it has to change a variable but it happens that this variable I need to change with useState.

## React Native version:
System:
    OS: Windows 10 10.0.18363
    CPU: (2) x64 Intel(R) Pentium(R) CPU G2030 @ 3.00GHz
    Memory: 1.71 GB / 7.88 GB
  Binaries:
    Node: 12.10.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.10.3 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 25, 26, 27, 28, 29
      Build Tools: 27.0.3, 28.0.3, 29.0.2, 30.0.0
      System Images: android-14 | ARM EABI v7a, android-15 | ARM EABI v7a, android-15 | Intel x86 Atom, android-15 | Google APIs ARM EABI v7a, android-15 | Google APIs Intel x86 Atom, android-16 | ARM EABI v7a, android-16 | MIPS, andro
id-16 | Intel x86 Atom, android-16 | Google APIs ARM EABI v7a, android-16 | Google APIs Intel x86 Atom, android-17 | ARM EABI v7a, android-17 | MIPS, android-17 | Intel x86 Atom, android-17 | Google APIs ARM EABI v7a, android-17 | Goog
le APIs Intel x86 Atom, android-18 | ARM EABI v7a, android-18 | Intel x86 Atom, android-18 | Google APIs ARM EABI v7a, android-18 | Google APIs Intel x86 Atom, android-19 | ARM EABI v7a, android-19 | Intel x86 Atom, android-19 | Google
 APIs ARM EABI v7a, android-19 | Google APIs Intel x86 Atom, android-21 | Android TV Intel x86 Atom, android-21 | ARM EABI v7a, android-21 | Intel x86 Atom, android-21 | Intel x86 Atom_64, android-21 | Google APIs ARM EABI v7a, android
-21 | Google APIs Intel x86 Atom, android-21 | Google APIs Intel x86 Atom_64, android-22 | ARM EABI v7a, android-22 | Intel x86 Atom, android-22 | Intel x86 Atom_64, android-22 | Google APIs ARM EABI v7a, android-22 | Google APIs Intel
 x86 Atom, android-22 | Google APIs Intel x86 Atom_64, android-25 | Google APIs ARM EABI v7a, android-25 | Google Play Intel x86 Atom, android-26 | Intel x86 Atom, android-26 | Intel x86 Atom_64, android-26 | Google APIs Intel x86 Atom
, android-26 | Google APIs Intel x86 Atom_64, android-26 | Google Play Intel x86 Atom, android-27 | Intel x86 Atom, android-27 | Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, andro
id-28 | Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64, android-2
9 | Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64, android-R | G
oogle APIs Intel x86 Atom, android-R | Google APIs Intel x86 Atom_64, android-R | Google Play Intel x86 Atom, android-R | Google Play Intel x86 Atom_64
      Android NDK: 21.1.6352462
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6514223
    Visual Studio: Not Found
  Languages:
    Java: Not Found
    Python: 2.7.16 - C:\Python27\python.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.2 => 0.63.2
  npmGlobalPackages:
    *react-native*: Not Found

## Expected Results
Describe what you expected to happen.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/37088593/91636308-6b067280-e9f7-11ea-828c-505109dd3cbe.gif)

**Comment by myckhel** [comment]
can we see your codes on how you implemented your modal?

**Comment by adriano461997** [comment]
Yes.

`/* This is an Login Registration example from https://aboutreact.com/ */
/* https://aboutreact.com/react-native-login-and-signup/ */
import React, { useState, useEffect } from 'react';
import {
    ActivityIndicator,
    View,
    StyleSheet,
    Image,
    Text,
    StatusBar,
    FlatList,
    Alert,
    TouchableOpacity, TouchableHighlight, Modal, ScrollView, Linking, TextInput, Switch,
} from 'react-native';
import AsyncStorage from '@react-native-community/async-storage';
import Request, {ERROR_TYPE, VIEW_STATE} from '../wapangola/CustomRequest';
import {ListItem, Icon, Overlay, Button} from 'react-native-elements';
import estilo from '../wapangola/Styles';
import {Popup} from 'popup-ui';
import {TerminarSessao} from '../wapangola/Utils';
import {Grid} from 'react-native-easy-grid/index';
import Loader from '../wapangola/Loader';
import Cores from '../wapangola/Cores';


const Configuracoes = ({navigation}) => {

    let [nome, setNome] = useState('');
    let [puwas, setPuwas] = useState('');
    let [foto, setFoto] = useState('iu');
    let [modalPass, setModalPass] = useState(false);
    let [loader, setLoader] = useState(false);
    let [over, setOver] = useState(false);
    let [isEnabled, setIsEnabled] = useState(false);
    let pin1, pin2 = "";


    useEffect(() => {

        AsyncStorage.multiGet(["puwas","nome","foto","finger"]).then(response => {

            setPuwas("P$ "+response[0][1])
            setNome(response[1][1])
            setFoto(response[2][1]);

            if(response[3][0] === "finger") {

                let finger = response[3][1];

                if (finger != null) {
                    if (finger === "1") {
                        setIsEnabled(true);
                    } else {
                        setIsEnabled(false);
                    }
                }

            }

        });



    },[]);

    const list = [
        {
            id:1,
            title: 'Editar perfil',
            icon: 'edit',
            chevron: true,

        },{
            id:2,
            title: 'Configurações da conta',
            icon: 'cog',
            chevron: true,
        },
        {
            id:3,
            title: 'Código PIN',
            icon: 'unlock-alt',
            chevron: true,
        },
        {
            id:7,
            title: 'Impressão digital',
            icon: 'fingerprint',
            chevron: true,
        },
        {
            id:4,
            title: 'Enviar crítica',
            icon: 'warning',
            chevron: true,
        },{
            id:5,
            title: 'Sobre',
            icon: 'question-circle',
            chevron: true,
        },{
            id:6,
            title: 'Terminar sessão',
            icon: 'power-off',
            chevron: true,
        },
    ]

    const list2 = [
        {
            name: nome,
            avatar_url: foto,
            subtitle: 'Ver perfil'
        }
    ]

    function click(id){
        if(id === 1){
            Linking.openURL("https://m.social.wapangola.net/editarperfil");
        } else if(id === 2){
            Linking.openURL("https://m.social.wapangola.net/configuracoes");
        } else if(id === 3){

            //Código pin
            setModalPass(true);

        } else if(id === 4){
            Linking.openURL("https://m.social.wapangola.net/enviar_critica");
        } else if(id === 5){

            // Sobre o app
            navigation.navigate("Sobre");

        } else if(id === 6){

            Alert.alert(
                "Tens a certeza?",
                "Você realmente tens a certeza que queres sair ?",
                [
                    {
                        text: "Cancelar",
                        onPress: () => console.log("Cancel Pressed"),
                        style: "cancel"
                    },
                    { text: "Sim", onPress: () => {

                        setLoader(true);
                        TerminarSessao(function(data){

                            (async function(){

                                await AsyncStorage.removeItem("uid");
                                await AsyncStorage.removeItem("bid");

                                navigation.reset({
                                    index: 0,
                                    routes: [{ name: 'Login' }],
                                });

                                setLoader(false);

                            })();

                        }, function(){

                            setLoader(false);
                            Alert.alert("","Ocorreu um erro ao tentar terminar a sessão!");

                        });

                        } }
                ],
                { cancelable: false }
            );

            // Sair

        } else if(id === 7){
            setOver(true);
        }
    }

    async function setPin(){
        if(pin1 !== pin2){
            Alert.alert("","Os Pins não conciedem");
        } else {

            await AsyncStorage.setItem("pin", pin1);
            setModalPass(false);

        }
    }


    function ModalP(){

        return(

            <Modal
                visible={modalPass}
                transparent={true}
                animationType={'fade'}
                onRequestClose={()=> setModalPass(false)}
                statusBarTranslucent={true}
                backdropOpacity={0.3}>
                <View style={{flex: 1,
                    //backgroundColor: 'transparent',
                    backgroundColor: 'rgba(0,0,0,0.7)',
                    alignItems: 'center',
                    justifyContent: 'center', borderTopEndRadius:10}}>

                    <View style={{width:"80%", backgroundColor:"#ffffff", borderRadius:10, padding:10}}>

                        <Text style={{padding:10, color:"green", fontSize:17}}>
                            Alterar PIN do App sempre que abrires
                        </Text>

                        <TextInput
                            style={{ borderColor: '#ddd', borderWidth: 1, borderRadius:5, padding:12, fontSize:18 }}
                            placeholder={"Código PIN"}
                            maxLength={4}
                            secureTextEntry={true}
                            onChangeText={(text) => { pin1 = text }}
                        />

                        <TextInput
                            style={{ borderColor: '#ddd', borderWidth: 1, borderRadius:5, padding:12, fontSize:18, marginTop:10, marginBottom:10 }}
                            placeholder={"Reintroduz o código PIN"}
                            maxLength={4}
                            secureTextEntry={true}
                            onChangeText={(text) => { pin2 = text  }}
                        />

                        <TouchableOpacity
                            onPress={()=>{
                                setPin();
                            }}>
                            <Text style={estilo.btnPrimary}>Alterar PIN</Text>
                        </TouchableOpacity>


                    </View>



                </View>
            </Modal>

        );

    }

    function toggleSwitch(value) {

        setIsEnabled(previousState => !previousState);

        (async function(){

            if(value){
                await AsyncStorage.setItem("finger", "1");
            } else {
                await AsyncStorage.setItem("finger", "0");
            }

        })();
    }

    const OverLay = ()=> {

        return(

            <Overlay animated={true}
                     animationType={"fade"}
                     statusBarTranslucent={true}
                     isVisible={over}
                     hardwareAccelerated={true}
                     onBackdropPress={()=>setOver(false)}
                     overlayStyle={{width:"80%",padding:20}}>
					 
                    <Text style={{fontWeight:"bold", alignSelf:"center", fontSize:20, marginBottom:20}}>A impressão digital</Text>
                    <Text style={{fontSize:17}}>A impressão digital permite-te saltar o PIN e desbloquer o App com a tua impressão digital. A impressão digital só funciona caso
                        o teu smartphone suporte ou configuraste.
                    </Text>
                    <Switch
                        trackColor={{ false: "#ddd", true: Cores.primary }}
                        style={{alignSelf:"center", marginTop:10,marginBottom:20}}
                        thumbColor={isEnabled ? Cores.primary : "#ddd"}
                        ios_backgroundColor="#3e3e3e"
                        onValueChange={toggleSwitch}
                        value={isEnabled}
                    />
                        <Button
                            title="Fechar"
                            onPress={()=>{

                                setOver(false);

                            }}
                            buttonStyle={{borderColor:Cores.primary}}
                            titleStyle={{color:Cores.primary}}
                            type="outline"
                        />
            </Overlay>
        );

    }

    return (
        <>
            <OverLay/>
            <ScrollView>
        <View>

            <Loader loading={loader} />

            <ModalP/>

            <View>
                {
                    list2.map((l, i) => (
                        <ListItem
                            key={i}
                            leftAvatar={{ source: { uri: l.avatar_url } }}
                            title={l.name}
                            subtitle={l.subtitle}
                            bottomDivider
                         children={<Text>Wap</Text>}/>
                    ))
                }
            </View>

            {
                list.map((item, i) => (

                    <TouchableOpacity
                    onPress={()=>{
                        click(item.id);
                    }}>
                    <ListItem
                        key={item.id}
                        title={item.title}
                        leftIcon={<Icon type={ item.id === 7 ? "materialIcons": "font-awesome"} name={item.icon} color={"#777"} />}
                        bottomDivider
                        children={<Text>Wap</Text>}/>
                    </TouchableOpacity>

                ))
            }

        </View>
        </ScrollView>
            </>

    );
};


export default Configuracoes;

const styles = StyleSheet.create({
    container: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
    }
});
`

**Comment by myckhel** [comment]
maybe you need to move your `ModalP` function out of `Configuracoes`

maybe the reason is because your `ModalP` is being recreated every time `Configuracoes` renders
and animated component that is being recreated is likely to restart the show animation.

I suggest you practice more so you understand react better than.

I dont think it is a good practice to create react components inside react functional component without memoising it.
maybe it will cause the component to be recreated on every render.

**Comment by adriano461997** [comment]
I understand, the same error occurs in the FlatList when I try to use setState it renders the entire layout again, for example I give a scroll in the Flatlist but when I open a modal or do something else using seState the scroll goes back up and the whole layout restarts but not resetting the values of the variables.

So if I understand correctly when I create a modal, I should do this outside the mother function like this.

function MyModal (props) {

<Modal visible = 'props.visble'>
</Modal>

}

function main () {

let [visble, setVisible] = useState (false);

return (
<MyModal visible = 'visible' />
)

}

is that it?

**Comment by myckhel** [comment]
yes that is what i meant.
did you try it? and did you see changes?

**Comment by adriano461997** [comment]
Thank you very much it worked perfectly

**Comment by safaiyeh** [comment]
Thanks for filing the issue @adriano461997 and happy @myckhel was able to find a solution for you.

Closing, feel free to open another issue if the issue persists in a different way.
