### ISSUE TITLE
keyboardWillHide is not called with consistent value

### ISSUE THREAD

**Issue by yifeiyin** [facebook/react-native#29815]
## Description
`Keyboard.addListener('keyboardWillHide', callback)` does not get called with correct value for `event.endCoordinates.height` when keyboard is dismissed by tap.

## React Native version:
```
System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 300.07 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.4.0 - ~/.nvm/versions/node/v14.4.0/bin/node
    Yarn: Not Found
    npm: 6.14.5 - ~/.nvm/versions/node/v14.4.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6308749
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  Languages:
    Java: 14.0.1 - /usr/bin/javac
    Python: 3.8.2 - /Users/***/.pyenv/shims/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: ~16.11.0 => 16.11.0
    react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
1. Tap the text input to raise keyboard
2. Dismiss the keyboard by dragging on the scrollview
3. Tap the text input to raise keyboard
4. Dismiss the keyboard by tapping the scrollview

## Expected Results
The callback is called with consistent `endCoordinates` (69 in this case).

## Snack, code example, screenshot, or link to a repository:
https://snack.expo.io/@yifeiyin/keyboard-height-reproduce

Output for dismiss by dragging - final endCoordinate.height is 69
![s2](https://user-images.githubusercontent.com/13235149/91677714-8b2a5480-eb11-11ea-84a6-b5c83192179f.png)

Output for dismiss by tapping - final endCoordinate.height is 355 (which is the same as `endCoordinate.height` in `keyboardWillShow`!)
![s1](https://user-images.githubusercontent.com/13235149/91677683-71890d00-eb11-11ea-9453-1fe462b2bd54.png)

Additional note: `keyboardDidHide` yields the same result.

**Comment by panda0603** [comment]
I have the exact same problem. Weird that not many people are experiencing this? What version simulator are you using?

**Comment by yifeiyin** [comment]
> I have the exact same problem. Weird that not many people are experiencing this? What version simulator are you using?

@panda0603 
ikr. It was quite annoying since I wanted to animate certain things based on the coordinates.

I believe I ran it on the iOS 13.6 simulator and on physical device when this PR was opened. I don't have the exact simulator version at this point. But the I ran the Expo Snack once again using Expo SDK 40 (which in turn uses React Native 0.63) and the problem is still there.

**Comment by panda0603** [comment]
> > I have the exact same problem. Weird that not many people are experiencing this? What version simulator are you using?
> 
> @panda0603 
> ikr. It was quite annoying since I wanted to animate certain things based on the coordinates.
> 
> I believe I ran it on the iOS 13.6 simulator and on physical device when this PR was opened. I don't have the exact simulator version at this point. But the I ran the Expo Snack once again using Expo SDK 40 (which in turn uses React Native 0.63) and the problem is still there.

This did not happen in rn 0.61.5, since I upgraded from there. I'm trying this with different simulators, they give different values based on screen size and ios version

So did you manage to get a work around?

**Comment by yifeiyin** [comment]
> So did you manage to get a work around?

Not really unfortunately. I used a different UI design that avoided this entirely. It is theoretically possible to hard code the values by either testing it on every device or just have a guess on the values. I just didn't have the patient to do that.

**Comment by safaiyeh** [comment]
Thank you @yifeiyin & @panda0603 for the issue. The numbers should be consistent when dismissing the keyboard.

**Comment by panda0603** [comment]
@safaiyeh meaning this issue is still ongoing right and not fixed?

**Comment by safaiyeh** [comment]
Yup still ongoing. Most issues won't get personal attention. We rely on the community to solve specific bugs like this with a PR
