### ISSUE TITLE
change `../node_modules/react-native/packager/react-native-xcode.sh`

### ISSUE THREAD

**Issue by hueyAtFetchly** [facebook/react-native#29818]
change `../node_modules/react-native/packager/react-native-xcode.sh`
to `../node_modules/react-native/scripts/react-native-xcode.sh`

_Originally posted by @AndrewJack in https://github.com/facebook/react-native/issues/14935#issuecomment-314160539_

Seems this is a 0.63.x bug no? 

Being that we get this with entirely clean version of 0.63.2 (at least the version I am on), should this not be resolved elsewhere (as opposed to manually). Perhaps, I need to upgrade to another version? 

This has gotten 229+ thumbs up, so maybe this actually needs to be resolved somewhere in RN codebase as opposed to just on the comment thread. 

It is ok, if I am wrong here. Please include reference, me and at least 229 others have interest in this issue.

**Comment by ShawnCholeva** [comment]
Under Build Phases -> "Bundle React Native code and images", I currently have the following script

```
export NODE_BINARY=node
../node_modules/react-native/scripts/react-native-xcode.sh
```

And am still getting the error since upgrading to `0.63.2` from `0.62.0`

Error

```
echo 'error: File /Users/Shawn/Library/Developer/Xcode/DerivedData/MyApp-ffssiqgbutxzxgefnvjyeiwacrnd/Build/Intermediates.noindex/ArchiveIntermediates/MyApp.alpha/BuildProductsPath/Release-iphoneos/MyApp.app/main.jsbundle does not exist. This must be a bug with'
```

**Comment by hueyAtFetchly** [comment]
@ShawnCholeva Thanks, I can confirm the change is not working for me. Seems with a fresh build on RN 0.63.2 this should not be necessary "out-of-the-box"

**Comment by oleksandr-dziuban** [comment]
Hi, this PR fixes an issue
https://github.com/facebook/react-native/pull/29477

But community didn't merge it yet

**Comment by leonardoballand** [comment]
PR #29477 fixed the issue for me

**Comment by oleksandr-dziuban** [comment]
> PR #29477 fixed the issue for me

Yes, I also applied changes locally to test release bundle on CI.

Possibly this fix will be included to RN version 0.64+

**Comment by hemith** [comment]
Not exactly related, 

I also have IP address 172.16.0.2 on my mac lo0 interface with 127.0.0.1

I recently upgrade to RN63.3 from RN62.3.
metro bundler address is always http://172.16.0.2:8081/ on my real device at first debug install.
so iphone can not connect to metro bundler.
and metro bundler have no connected app.
http://172.16.0.2:8081/status  is ok on simulator, but real device (on same wifi network (192.168...)) is not ok.

correct bundler address on real device is ...
http://192.168.xx.xxx:8081/status -> (O)

please grep -v below private network 
20-bit block (172.16.0.0 – 172.31.255.255) 
* https://en.wikipedia.org/wiki/Private_network

related bash code lines are..
react-native/scripts/react-native-xcode.sh 15~26 lines
```bash
# Enables iOS devices to get the IP address of the machine running Metro
if [[ "$CONFIGURATION" = *Debug* && ! "$PLATFORM_NAME" == *simulator ]]; then
  IP=$(ipconfig getifaddr en0)
  if [[ -z "$IP" || -n "`ifconfig $value | grep 'baseT'`" ]]; then
    IP=$(ipconfig getifaddr en1)
  fi
  if [ -z "$IP" ]; then
    IP=$(ifconfig | grep 'inet ' | grep -v ' 127.' | grep -v ' 169.254.' | cut -d\   -f2  | awk 'NR==1{print $1}')
  fi

  echo "$IP" > "$DEST/ip.txt"
fi
```

**Comment by joebologna** [comment]
I've had a lot of problems with "Error: cannot find the node binary" because I need to use Node 12 for some things and Node 14 for others. Using nvm to switch works well, but it requires the $SHELL environment to be setup properly. Unfortunately all shells source some basic stuff, then stuff only for "login" or interactive shells. Xcode (for whatever reason) doesn't pick up the interactive shell stuff, which makes sense, but means when you do `which node` then run Xcode it will not see `which node` your are using in your interactive $SHELL.

Since Mac OS is depreciating BASH in favor of ZSH, things get really icky if you have a .bash_profile and .zprofile. Blah, blah.

I suggest making this change to the `Bundle React Native code and images` section of the .xcodproject generated by react-native:

```
bash -ls <<EOF
export NODE_BINARY=node
#export REACT_NATIVE_PACKAGER_HOSTNAME=10.0.0.5
../node_modules/react-native/scripts/react-native-xcode.sh
../node_modules/expo-updates/scripts/create-manifest-ios.sh
EOF

```

This solves 2 problems. First, it runs the script as if it were run from your Terminal. Second, it adds a comment suggesting the user uncomment `REACT_NATIVE_PACKAGER_HOSTNAME` in case the bundler doesn't figure out how to find the IP address of the host when the app runs on the phone. This happens sometimes and it really difficult to deal with.

**Comment by PauloYR** [comment]
> change `../node_modules/react-native/packager/react-native-xcode.sh`
> to `../node_modules/react-native/scripts/react-native-xcode.sh`
> 
> _Originally posted by @AndrewJack in [#14935 (comment)](https://github.com/facebook/react-native/issues/14935#issuecomment-314160539)_
> 
> Seems this is a 0.63.x bug no?
> 
> Being that we get this with entirely clean version of 0.63.2 (at least the version I am on), should this not be resolved elsewhere (as opposed to manually). Perhaps, I need to upgrade to another version?
> 
> This has gotten 229+ thumbs up, so maybe this actually needs to be resolved somewhere in RN codebase as opposed to just on the comment thread.
> 
> It is ok, if I am wrong here. Please include reference, me and at least 229 others have interest in this issue.

https://github.com/facebook/react-native/issues/28660#issuecomment-786325312

Look this

**Comment by jaamz** [comment]
> I've had a lot of problems with "Error: cannot find the node binary" because I need to use Node 12 for some things and Node 14 for others. Using nvm to switch works well, but it requires the $SHELL environment to be setup properly. Unfortunately all shells source some basic stuff, then stuff only for "login" or interactive shells. Xcode (for whatever reason) doesn't pick up the interactive shell stuff, which makes sense, but means when you do `which node` then run Xcode it will not see `which node` your are using in your interactive $SHELL.
> 
> Mac OS is depreciating BASH in favor of ZSH. If you switch to ZSH as your login shell, things get really icky if you have a .bash_profile and .zprofile.
> 
> I suggest making this change to the `Bundle React Native code and images` section of the .xcodproject generated by react-native:
> 
> ```
> $SHELL -ls <<EOF
> export NODE_BINARY=node
> ../node_modules/react-native/scripts/react-native-xcode.sh
> ../node_modules/expo-updates/scripts/create-manifest-ios.sh
> EOF
> ```
> 
> This runs the script as if it were run from your Terminal.

I have spent many hours digging through many different fixes and this finally ended up being the fix for me. Many thanks!
