### ISSUE TITLE
useEffect not update the redux value its return null but i make change and save its work. first time app loaded its not work.

### ISSUE THREAD

**Issue by vijay-mca** [facebook/react-native#29817]
if i run the app value not update in useEffect please help me

**Comment by dulmandakh** [comment]
Please provide more information and reproducible sample code so we can further investigate the issue. Thanks

**Comment by dulmandakh** [comment]
Sorry, closing this issue because this issue tracker is intended to track React Native issues, but this issue looks like an issue with your code or implementation.
