### ISSUE TITLE
toLocaleDateString() does not work in Android. The date format gets trimmed from 'yyyy' to 'yy' (iOS does work correctly)

### ISSUE THREAD

**Issue by RSP531** [facebook/react-native#29824]
## Description
When using Dates in React Native, the method toLocaleDateString() clips the date. Is there a work around for android?

## React Native version:
"react-native": "~0.62.2",

## Steps To Reproduce
In any component paste this code and you will see...

```
      let todaysDate = new Date();
      let [month, day, year] = todaysDate.toLocaleDateString().split("/")
      console.log('Year: ', year)
      //this was my workaround
      if (Platform.OS === 'android') {
        year = todaysDate.toString().slice(11, 15)
      }
      console.log('Year: ', year)
```

## Expected Results
The first year will log a 2 digit year: '20'. In iOS the year will log a 4 digit year: '2020'

## Snack, code example, screenshot, or link to a repository:
//sorry I do not have an open repo or snack

**Comment by chrisglein** [comment]
Put that in a Snack:
https://snack.expo.io/@chrisglein/repro29824

If you just want the year, `getFullYear` produces the 4 digit value. Parsing it out of `toLocaleDateString` is going to be dependent on the locale formatting per platform, which I guess is different on Android? Is this an RN issue or just a difference in Android/iOS defaults? (Web also displays the 4 digit value, like iOS)

**Comment by RSP531** [comment]
Maybe just an issue with Android/iOS defaults? I just noticed a difference on the two platforms, but couldn't find any information on RN or MDN to explain why the js function works differently on the platforms.

**Comment by 0916dhkim** [comment]
@RSP531 I found a StackOverflow thread related to this issue.
https://stackoverflow.com/questions/51399551/why-isnt-tolocaledatestring-working-in-react-native-android

>React Native used JavaScriptCore engine in non-debug mode & it doesn't work well with dates, but work during debug because it use chrome V8 engine while debugging.

**Comment by chrisglein** [comment]
I think this issue has been answered now between this and the StackOverflow thread. Closing this issue.

**Comment by VictorioMolina** [comment]
I am getting the same problem in development mode. Will this platform specific problem dissapear on production?
