### ISSUE TITLE
 iOS release build Error loading local images and icon 

### ISSUE THREAD

**Issue by MahmudHasanMenon** [facebook/react-native#29828]
After upgrading my RN version from 0.61.0 to 0.61.2 when i made a release build then it shows error saying that `No bundle url present`. then i delete my main.jsBundle from xcode and create that file again using that command
`react-native bundle --entry-file index.js --platform ios --dev false --bundle-output ios/main.jsbundle --assets-dest ios`
after release build 'No bundle Error' gone but in my release build there is no local images or icon.

Note: ios simulator everything works fine.

![image](https://user-images.githubusercontent.com/29507500/91938480-e62c9900-ed15-11ea-85af-65f0d7662ca5.png)
![image](https://user-images.githubusercontent.com/29507500/91938999-dc576580-ed16-11ea-9083-3ec59ef1ee8b.png)

## React Native version:
 `CPU: (4) x64 Intel(R) Core(TM) i5-3470S CPU @ 2.90GHz
    Memory: 4.19 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.15.0 - /usr/local/bin/node
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
  IDEs:
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.2 => 0.61.2 
  npmGlobalPackages:
    react-native-cli: 2.0.1.`

## Steps To Reproduce
1. In release build this issue happening
2. After archiving, generate a .ipa file.

## Expected Results
it must load all local images and icon
![image](https://user-images.githubusercontent.com/29507500/91939895-66ec9480-ed18-11ea-9cc4-76b1154d26f2.png)

## Snack, code example, screenshot, or link to a repository:
my ios folder in my root project
![image](https://user-images.githubusercontent.com/29507500/91939240-4bcd5500-ed17-11ea-9700-78f542540349.png)

**Comment by saachitech** [comment]
@MahmudHasanMenon Please post a reproducible snack or repo.

**Comment by MahmudHasanMenon** [comment]
@saachitech  this project is confidential, so sorry i can't provide the repo. i can provide the code file.
Also the codebase is huge and there is lot's of dependency

**Comment by safaiyeh** [comment]
@MahmudHasanMenon thanks for the issue!

I've noticed some issues popping up because of this:
https://github.com/facebook/react-native/issues/29813

There hasn't seemed to have a resolution for this. One thing that will be helpful is to generate a fresh project and demonstrate the issue you are having

**Comment by saachitech** [comment]
> @saachitech this project is confidential, so sorry I can't provide the repo. I can provide the code file.
> Also the codebase is huge and there is lot's of dependency

That's OK. A minimal code block or repo to reproduce the issue would be fine.

**Comment by safaiyeh** [comment]
Please check out my comment here: https://github.com/facebook/react-native/issues/29364#issuecomment-682276573

There are temporary work arounds to get images to load
