### ISSUE TITLE
XMLHttpRequest GET request fails on fresh RN project

### ISSUE THREAD

**Issue by bmbmjmdm** [facebook/react-native#29823]
## Description
Making a simple XMLHttpRequest GET request to "https://www.google.com" results in the request immediately updating with `request.status === 0`. Usually it will eventually go through after 2-3 minutes, sometimes it won't. After it goes through, future XMLHttpRequests resolve quickly. This failure can also be seen using `fetch` or `axios`.

## React Native version:
```System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Memory: 4.59 GB / 15.84 GB
  Binaries:
    Node: 10.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.13.0 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    Watchman: 4.9.4 - C:\Users\laplante\Desktop\Apps\watchman\watchman.EXE
  SDKs:
    Android SDK:
      API Levels: 21, 22, 23, 24, 25, 26, 27, 28, 29
      Build Tools: 23.0.1, 23.0.2, 26.0.2, 26.0.3, 28.0.2, 28.0.3, 29.0.0
      System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5522156
    Visual Studio: Not Found
  Languages:
    Java: Not Found
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.2 => 0.63.2
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce

1. Init a new react native project (not through expo)
2. Try to make an XMLHttpRequest using GET to 'https://www.google.com'
3. This was seen on 2 physical Android devices using `react-native run-android` running Android 6 and 10

## Expected Results
The request should succeed in a reasonable time

## Snack, code example, screenshot, or link to a repository:
Try out the following component: 
```import React from "react";
import { Alert, View } from 'react-native'

export default class AppContainer extends React.Component {
  constructor(props) {
    super(props)
    let xmlHttp = new XMLHttpRequest()
    let configUrl = "https://www.google.com"
    xmlHttp.onreadystatechange= function() {
      console.log(this.status)
      if (this.status == 200  && xmlHttp.readyState == 4) {
        try {
          Alert.alert("Success!")
          return
        }
        catch (e) { console.log(e) }
      }
      // dont alert if status is good but ready state not there yet
      else if (this.status === 200) return
      // alert if anything went wrong above
      Alert.alert("Something went wrong.")
    }
    xmlHttp.open( "GET", configUrl, true)
    xmlHttp.send()
  }

  render() {
      return (
        <View/>
      )
  }
}

**Comment by chrisglein** [comment]
There are all sorts of things that could go wrong with this, naturally. It'd be good to have more data about what you're seeing in networking logs, etc. However, this is plain JavaScript and doesn't have anything to do with particular React Native APIs. The behavior you're seeing is more tied to the native platform and the JavaScript engine. Do you have reason to suspect something about React Native is causing your problem?

**Comment by bmbmjmdm** [comment]
Do you know how to get those networking logs? I've tried digging through logcat and it haven't found much ("could not identify captive portal state" and "captive portal exception" were of note). I suspect it's related to RN simply because I'm seeing this behavior across phones/OSs (so it seems unlikely to be caused by the platform). The phones' are able to access webpages via a browser and those sites' use js requests successfully.

**Comment by bmbmjmdm** [comment]
I have reproduced this again on a different computer and different phone. New computer's environment: 
```System:
    OS: Windows 10 10.0.18362
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 8.17 GB / 15.93 GB
  Binaries:
    Node: 10.16.2 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      Android NDK: 21.0.6113669
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5692245
    Visual Studio: Not Found
  Languages:
    Java: Not Found
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.2 => 0.63.2
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by bmbmjmdm** [comment]
Reproduce with React Native 0.62 and 0.60 as well

**Comment by bmbmjmdm** [comment]
This was solved by resetting my router. I'll try to reproduce with wireshark to see what caused the packet failures. Regardless, this app was the only thing on the network failing (all computers/devices worked fine otherwise)

**Comment by chrisglein** [comment]
As for getting logs, in the past I've used [fiddler](https://www.telerik.com/fiddler) on desktop - I'm not at all up to date on what the mobile equivalent would be. And for all I know fiddler is ancient and behind the curve (and eclipsed by modern Chrome tools). You mention [wireshark](https://www.wireshark.org/), which looks cool.

It sounds like you're unblocked though, which is good. If it crops up again and you find a link to RN definitely raise the issue.
