### ISSUE TITLE
React Native Environment setup issue 

### ISSUE THREAD

**Issue by hariaravind10** [facebook/react-native#29836]
xxxx-MacBook-Pro-2:SampleApp xxxxx$ react-native run-ios
info Found Xcode project "SampleApp.xcodeproj"
info Building (using "xcodebuild -project SampleApp.xcodeproj -configuration Debug -scheme SampleApp -destination id=BDB7A3CA-20F5-4C22-B29B-C6B50C36F802")
...............
**[error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65](url
)**. To debug build logs further, consider building your app with Xcode.app, by opening SampleApp.xcodeproj. Run CLI with --verbose flag for more details.
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -project SampleApp.xcodeproj -configuration Debug -scheme SampleApp -destination id=BDB7A3CA-20F5-4C22-B29B-C6B50C36F802

note: Using new build system
note: Building targets in parallel
note: Planning build
note: Using build description from disk
PhaseScriptExecution Start\ Packager /Users/xxxxx/Library/Developer/Xcode/DerivedData/SampleApp-adshqmrqlnmgwzafnranhgtbyazh/Build/Intermediates.noindex/SampleApp.build/Debug-iphonesimulator/SampleApp.build/Script-FD10A7F022414F080027D42C.sh (in target 'SampleApp' from project 'SampleApp')
    cd /Users/suthra/Desktop/react/SampleApp/ios
    /bin/sh -c /Users/xxxxx/Library/Developer/Xcode/DerivedData/SampleApp-adshqmrqlnmgwzafnranhgtbyazh/Build/Intermediates.noindex/SampleApp.build/Debug-iphonesimulator/SampleApp.build/Script-FD10A7F022414F080027D42C.sh

CompileC /Users/xxxx/Library/Developer/Xcode/DerivedData/SampleApp-adshqmrqlnmgwzafnranhgtbyazh/Build/Intermediates.noindex/SampleApp.build/Debug-iphonesimulator/SampleApp.build/Objects-normal/x86_64/main.o /Users/xxxx/Desktop/react/SampleApp/ios/SampleApp/main.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'SampleApp' from project 'SampleApp')
    cd /Users/xxxxx/Desktop/react/SampleApp/ios
    export LANG=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -target x86_64-apple-ios10.0-simulator -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu99 -fobjc-arc -fmodules -gmodules -fmodules-cache-path=/Users/xxxx/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/xxxx/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wunreachable-code -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Wno-objc-interface-ivars -Werror=objc-root-class -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -DDEBUG=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.6.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -Wno-sign-conversion -Winfinite-recursion -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wno-semicolon-before-method-body -fobjc-abi-version=2 -fobjc-legacy-dispatch -index-store-path /Users/suthra/Library/Developer/Xcode/DerivedData/SampleApp-adshqmrqlnmgwzafnranhgtbyazh/Index/DataStore -iquote /Users/suthra/Library/Developer/Xcode/DerivedData/SampleApp-adshqmrqlnmgwzafnranhgtbyazh/Build/Intermediates.noindex/SampleApp.build/Debug-iphonesimulator/SampleApp.build/SampleApp-generated-files.hmap -I/Users/xxxxx/Library/Developer/Xcode/DerivedData/SampleApp-adshqmrqlnmgwzafnranhgtbyazh/Build/Intermediates.noindex/SampleApp.build/Debug-iphonesimulator/SampleApp.build/SampleApp-own-target-headers.hmap -I/Users/xxxxx/Library/Developer/Xcode/DerivedData/SampleApp-adshqmrqlnmgwzafnranhgtbyazh/Build/Intermediates.noindex/SampleApp.build/Debug-iphonesimulator/SampleApp.build/SampleApp-all-target-headers.hmap -iquote /Users/xxxx/Library/Developer/Xcode/DerivedData/SampleApp-adshqmrqlnmgwzafnranhgtbyazh/Build/Intermediates.noindex/SampleApp.build/Debug-iphonesimulator/SampleApp.build/SampleApp-project-headers.hmap -I/Users/xxxx/Library/Developer/Xcode/DerivedData/SampleApp-adshqmrqlnmgwzafnranhgtbyazh/Build/Products/Debug-iphonesimulator/include -I/Users/suthra/Library/Developer/Xcode/DerivedData/SampleApp-adshqmrqlnmgwzafnranhgtbyazh/Build/Intermediates.noindex/SampleApp.build/Debug-iphonesimulator/SampleApp.build/DerivedSources-normal/x86_64 -I/Users/xxxx/Library/Developer/Xcode/DerivedData/SampleApp-adshqmrqlnmgwzafnranhgtbyazh/Build/Intermediates.noindex/SampleApp.build/Debug-iphonesimulator/SampleApp.build/DerivedSources/x86_64 -I/Users/xxxxx/Library/Developer/Xcode/DerivedData/SampleApp-adshqmrqlnmgwzafnranhgtbyazh/Build/Intermediates.noindex/SampleApp.build/Debug-iphonesimulator/SampleApp.build/DerivedSources -F/Users/xxxxx/Library/Developer/Xcode/DerivedData/SampleApp-adshqmrqlnmgwzafnranhgtbyazh/Build/Products/Debug-iphonesimulator -MMD -MT dependencies -MF /Users/xxxx/Library/Developer/Xcode/DerivedData/SampleApp-adshqmrqlnmgwzafnranhgtbyazh/Build/Intermediates.noindex/SampleApp.build/Debug-iphonesimulator/SampleApp.build/Objects-normal/x86_64/main.d --serialize-diagnostics /Users/xxxxx/Library/Developer/Xcode/DerivedData/SampleApp-adshqmrqlnmgwzafnranhgtbyazh/Build/Intermediates.noindex/SampleApp.build/Debug-iphonesimulator/SampleApp.build/Objects-normal/x86_64/main.dia -c /Users/xxxxx/Desktop/react/SampleApp/ios/SampleApp/main.m -o /Users/xxxxxx/Library/Developer/Xcode/DerivedData/SampleApp-adshqmrqlnmgwzafnranhgtbyazh/Build/Intermediates.noindex/SampleApp.build/Debug-iphonesimulator/SampleApp.build/Objects-normal/x86_64/main.o
In file included from /Users/suthra/Desktop/react/SampleApp/ios/SampleApp/main.m:3:
/Users/suthra/Desktop/react/SampleApp/ios/SampleApp/AppDelegate.h:1:9: fatal error: 'React/RCTBridgeDelegate.h' file not found
#import <React/RCTBridgeDelegate.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

CompileC /Users/xxxx/Library/Developer/Xcode/DerivedData/SampleApp-adshqmrqlnmgwzafnranhgtbyazh/Build/Intermediates.noindex/SampleApp.build/Debug-iphonesimulator/SampleApp.build/Objects-normal/x86_64/AppDelegate.o /Users/suthra/Desktop/react/SampleApp/ios/SampleApp/AppDelegate.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'SampleApp' from project 'SampleApp')
    cd /Users/xxxx/Desktop/react/SampleApp/ios
    export LANG=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -target x86_64-apple-ios10.0-simulator -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu99 -fobjc-arc -fmodules -gmodules -fmodules-cache-path=/Users/xxxx/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/xxxx/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wunreachable-code -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Wno-objc-interface-ivars -Werror=objc-root-class -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -DDEBUG=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.6.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -Wno-sign-conversion -Winfinite-recursion -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wno-semicolon-before-method-body -fobjc-abi-version=2 -fobjc-legacy-dispatch -index-store-path /Users/xxxx/Library/Developer/Xcode/DerivedData/SampleApp-adshqmrqlnmgwzafnranhgtbyazh/Index/DataStore -iquote /Users/suthra/Library/Developer/Xcode/DerivedData/SampleApp-adshqmrqlnmgwzafnranhgtbyazh/Build/Intermediates.noindex/SampleApp.build/Debug-iphonesimulator/SampleApp.build/SampleApp-generated-files.hmap -I/Users/xxxx/Library/Developer/Xcode/DerivedData/SampleApp-adshqmrqlnmgwzafnranhgtbyazh/Build/Intermediates.noindex/SampleApp.build/Debug-iphonesimulator/SampleApp.build/SampleApp-own-target-headers.hmap -I/Users/xxxx/Library/Developer/Xcode/DerivedData/SampleApp-adshqmrqlnmgwzafnranhgtbyazh/Build/Intermediates.noindex/SampleApp.build/Debug-iphonesimulator/SampleApp.build/SampleApp-all-target-headers.hmap -iquote /Users/xxxx/Library/Developer/Xcode/DerivedData/SampleApp-adshqmrqlnmgwzafnranhgtbyazh/Build/Intermediates.noindex/SampleApp.build/Debug-iphonesimulator/SampleApp.build/SampleApp-project-headers.hmap -I/Users/suthra/Library/Developer/Xcode/DerivedData/SampleApp-adshqmrqlnmgwzafnranhgtbyazh/Build/Products/Debug-iphonesimulator/include -I/Users/xxxx/Library/Developer/Xcode/DerivedData/SampleApp-adshqmrqlnmgwzafnranhgtbyazh/Build/Intermediates.noindex/SampleApp.build/Debug-iphonesimulator/SampleApp.build/DerivedSources-normal/x86_64 -I/Users/xxxxx/Library/Developer/Xcode/DerivedData/SampleApp-adshqmrqlnmgwzafnranhgtbyazh/Build/Intermediates.noindex/SampleApp.build/Debug-iphonesimulator/SampleApp.build/DerivedSources/x86_64 -I/Users/xxxxx/Library/Developer/Xcode/DerivedData/SampleApp-adshqmrqlnmgwzafnranhgtbyazh/Build/Intermediates.noindex/SampleApp.build/Debug-iphonesimulator/SampleApp.build/DerivedSources -F/Users/suthra/Library/Developer/Xcode/DerivedData/SampleApp-adshqmrqlnmgwzafnranhgtbyazh/Build/Products/Debug-iphonesimulator -MMD -MT dependencies -MF /Users/xxxxx/Library/Developer/Xcode/DerivedData/SampleApp-adshqmrqlnmgwzafnranhgtbyazh/Build/Intermediates.noindex/SampleApp.build/Debug-iphonesimulator/SampleApp.build/Objects-normal/x86_64/AppDelegate.d --serialize-diagnostics /Users/xxxxx/Library/Developer/Xcode/DerivedData/SampleApp-adshqmrqlnmgwzafnranhgtbyazh/Build/Intermediates.noindex/SampleApp.build/Debug-iphonesimulator/SampleApp.build/Objects-normal/x86_64/AppDelegate.dia -c /Users/xxxx/Desktop/react/SampleApp/ios/SampleApp/AppDelegate.m -o /Users/xxxx/Library/Developer/Xcode/DerivedData/SampleApp-adshqmrqlnmgwzafnranhgtbyazh/Build/Intermediates.noindex/SampleApp.build/Debug-iphonesimulator/SampleApp.build/Objects-normal/x86_64/AppDelegate.o
In file included from /Users/xxxx/Desktop/react/SampleApp/ios/SampleApp/AppDelegate.m:1:
/Users/suthra/Desktop/react/SampleApp/ios/SampleApp/AppDelegate.h:1:9: fatal error: 'React/RCTBridgeDelegate.h' file not found
#import <React/RCTBridgeDelegate.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
warning: Could not read serialized diagnostics file: Cannot Load File: Failed to open diagnostics file (in target 'SampleApp' from project 'SampleApp')

** BUILD FAILED **

The following build commands failed:
	CompileC /Users/xxxx/Library/Developer/Xcode/DerivedData/SampleApp-adshqmrqlnmgwzafnranhgtbyazh/Build/Intermediates.noindex/SampleApp.build/Debug-iphonesimulator/SampleApp.build/Objects-normal/x86_64/main.o /Users/suthra/Desktop/react/SampleApp/ios/SampleApp/main.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
<img width="1280" alt="Screenshot 2020-09-03 at 12 06 31 AM" src="https://user-images.githubusercontent.com/34663118/92022752-5d474900-ed79-11ea-9692-872ca34f91f9.png">

**Comment by hariaravind10** [comment]
> You can obtain the missing information by running `react-native info` in a console.

info Fetching system and libraries information...
System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz
    Memory: 432.66 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.14.1 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3
      System Images: android-28 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_242 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: ~16.11.0 => 16.11.0 
    react-native: ~0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by hariaravind10** [comment]
Please any one help me

**Comment by chrisbobbe** [comment]
Did you run `npm install`, then run `pod install` from the `ios` directory?

**Comment by safaiyeh** [comment]
Hi @hariaravind10, there are tools to debug your environment like `npx react-native doctor` for additional environment help, we recommend using StackOverflow. 

If this is an issue of React Native core, please refill an issue with the issue template.
