### ISSUE TITLE
ScrollView not working in sample app on ios simulator

### ISSUE THREAD

**Issue by szewah** [facebook/react-native#29833]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Unable to do scroll view on react-native app in ios simulator

<img width="338" alt="Screen Shot 2020-09-02 at 10 40 50 AM" src="https://user-images.githubusercontent.com/32065713/91998065-c80c6c00-ed08-11ea-88aa-8dcaed445162.png">

## React Native version:
System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 813.22 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 20.0, macOS 11.0, tvOS 14.0, watchOS 7.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.0/12A8189h - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
1.npx react-native init MyTestApp
2. react-native run-ios

## Expected Results
Page scrolls downwards

**Comment by safaiyeh** [comment]
Hi @szewah thank you for the issue.

I notice you are using iOS 14, could you check if this occurs in the latest version of 13.x? There isn't official support for iOS 14 yet but we should start keeping track of the issues as iOS 14 is coming soon.

Also could you try using `npx react-native run-ios` to see if you get the same behavior? Thanks!

**Comment by szewah** [comment]
Hi @safaiyeh thanks for getting back to me. I'm unable to choose 13.x as that's not an option in the Xcode 12 simulator. I'll need to download the Xcode 11 beta to do that.

**Comment by chrisglein** [comment]
> Hi @safaiyeh thanks for getting back to me. I'm unable to choose 13.x as that's not an option in the Xcode 12 simulator. I'll need to download the Xcode 11 beta to do that.

Did you try the other suggestion above about `npx react-native run-ios`? (note the addition of `npx`)
