### ISSUE TITLE
fetch res.json() SyntaxError: Unexpected token ﻿ in JSON at position 0

### ISSUE THREAD

**Issue by rutvikrockers** [facebook/react-native#29844]
In iOS it works perfectly and get response in JSON. but in android throws an error unexpected token in JSON.I checked my postman response and also decoded JSON and it's perfect.Somehow in android only  it gave me an error. I am trying to solve this issue since 2 days but no luck.can anyone help me with this?it is urgent.please find below screenshot of my postman response.
1) I tried with **AXIOS** and it gives me an string response.and can't able to fetch data from it.
2)AXIOS response screenshot also attached.
![Screenshot 2020-09-03 at 11 55 14 AM](https://user-images.githubusercontent.com/31954734/92078712-5998de00-eddc-11ea-9ac2-d713766540ba.png)
![Screenshot 2020-09-03 at 11 49 23 AM](https://user-images.githubusercontent.com/31954734/92078907-b2687680-eddc-11ea-8f2e-57b760cb7752.png)

**Comment by myckhel** [comment]
Does other endpoints work correctly or same issue?

**Comment by rutvikrockers** [comment]
Other Base url(endpoints) Working and give me JSON response.but particularly one endpoint gave me this response in AXIOS.But in iOS it works perfectly.

**Comment by rutvikrockers** [comment]
hello is there any help please?

**Comment by arasrezaei** [comment]
i had similar issue ...

**Comment by arasrezaei** [comment]
https://github.com/facebook/react-native/issues/29267
