### ISSUE TITLE
[Tests][Help Wanted] We need more JS tests

### ISSUE THREAD

**Issue by ide** [facebook/react-native#2984]
After separating the RN JS, packager, and CLI tests it turns out we have only 14 tests for the JS code (not including React's tests though): https://travis-ci.org/facebook/react-native/jobs/81857944. There should be more unit tests for modules like InteractionManager, ListViewDataSource, JSTimers, WebSockets where we mock the native layer.

**Comment by nsimmons** [comment]
I have added quite a few tests for my CLI PRs, but have not had a look at other areas. I will have a look and see if I can add some.

**Comment by jsierles** [comment]
@ide In an effort to keep Github issues lean and focused on closeable issues/bugs, I'm closing this in favor of discussions on more specific PRs such as #3229. If you feel it should stay open for discussion, let's come up with a proposal for dealing with Github-based discussions on the core contributors FB group. Cheers!
