### ISSUE TITLE
iOS 14 system font weird rendering with small-caps

### ISSUE THREAD

**Issue by erazhapov** [facebook/react-native#29846]
Hi!

I'm using default **Text** component with these styles:

```
title_s: {
    fontFamily: 'System'
    fontSize: 16,
    lineHeight: 20,
    fontVariant: ['small-caps'],
    textTransform: 'lowercase'
}
```

Both labels has the same style, right have additional {  fontWeight: '500' }

It's works well on iOS 13.x, but looks weird (small-caps mode working incorrect with numbers) on iOS 14 beta 6. 

Here is how it looks like:
![Frame 1](https://user-images.githubusercontent.com/23643476/92101386-b5b43000-ede5-11ea-8571-5b5832a0b1cd.png)

I'm using 0.62 cause of using Expo SDK 38 (managed), but I didn't found anything relating to this in 0.63 changelog.

**Comment by erazhapov** [comment]
System:
    OS: macOS 10.15.5
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 100.96 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.3.0 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.8.4 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5977832
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  Languages:
    Java: 12.0.1 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: https://github.com/expo/react-native/archive/sdk-38.0.0.tar.gz => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by safaiyeh** [comment]
Hi @erazhapov thanks for the issue. Could you provide a repro with the latest version of RN with a fresh template without expo? This will narrow it down to if it is an issue purely with core.
