### ISSUE TITLE
After Upgrading to react native 63, The borderBottomWidth doesnot work in a view or any place

### ISSUE THREAD

**Issue by Sukumar-Abhijeet** [facebook/react-native#29852]
✋ To keep the backlog clean and actionable, issues will be
🚫 closed if they do not follow one of the issue templates:
👉 https://github.com/facebook/react-native/issues/new/choose

For Example :- I have a custom header component.
<View style={{borderBottomWidth:1 and borderBottomColor:'#ebebeb',width:''100%,height:50}} />
Previously Used RN 61.5 - Works fine
Upgraded to RN 63.2  - The bottomBorder is visible once and then gets hidden and never shows up again, 
while adding a borderWidth to it,  the border appears again but I dont want the border to all over the 4 sides.

Indivisually left/top/right/bottom for border is not working in RN63.2

**Comment by 452MJ** [comment]
It work fine for me.

**Comment by Sukumar-Abhijeet** [comment]
I had re setup the project and its working fine now.
I think there was some error with dependencies of other packages i have used
I am Closing this Issue.

**Comment by Mohammed-Salmeen** [comment]
can u explain what have u did for re setup
