### ISSUE TITLE
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object

### ISSUE THREAD

**Issue by borbhuiyagulsan** [facebook/react-native#29853]
I am using `Pressable` instead of Touchable opacity but I am getting the above mentioned error. I have tried all possible solutions in `import` & `export` but still I am getting the error.

`

    import React, { useState, useEffect } from 'react';
    import { StyleSheet,View,Dimensions,Image } from 'react-native';
    import Pressable from 'react-native';
    import MapView, { PROVIDER_GOOGLE, Marker } from 'react-native-maps';
    import * as Location from 'expo-location';
    import { Button } from 'react-native-paper';
    import { useSelector } from 'react-redux'
    import { location1 } from '../../src/store/action/location';
    import { connect } from "react-redux"

`

And here is my `pressable`

<img width="802" alt="Screenshot 2020-09-03 at 9 28 00 PM" src="https://user-images.githubusercontent.com/42679215/92138724-62b19b80-ee2c-11ea-8706-ca554e5202e3.png">

`export default connect(null, { location1 })(Home);
`

my package.json

`     "dependencies": {
    "@react-native-community/async-storage": "^1.11.0",
    "@react-native-community/masked-view": "^0.1.10",
    "axios": "^0.19.2",
    "expo": "~38.0.8",
    "expo-linear-gradient": "~8.2.1",
    "expo-location": "~8.2.1",
    "expo-status-bar": "^1.0.2",
    "react": "16.13.1",
    "react-dom": "~16.11.0",
    "react-native": "0.62.2",
    "react-native-animatable": "^1.3.3",
    "react-native-gesture-handler": "^1.6.0",
    "react-native-get-random-values": "^1.4.0",
    "react-native-google-places-autocomplete": "^1.8.0",
    "react-native-maps": "0.27.1",
    "react-native-maps-directions": "^1.8.0",
    "react-native-paper": "^4.0.1",
    "react-native-reanimated": "~1.9.0",
    "react-native-safe-area-context": "~3.0.7",
    "react-native-screens": "~2.9.0",
    "react-native-vector-icons": "^7.0.0",
    "react-native-web": "~0.11.7",
    "react-navigation": "^4.4.0",
    "react-navigation-stack": "^2.8.2",
    "react-redux": "^7.2.1",
    "redux": "^4.0.5",
    "redux-thunk": "^2.3.0"
  },`

Here is the error I am getting : -

![Simulator Screen Shot - iPhone 11 - 2020-09-03 at 21 15 52](https://user-images.githubusercontent.com/42679215/92139076-dd7ab680-ee2c-11ea-8df6-baf3447a8aa5.png)

**Comment by borbhuiyagulsan** [comment]
<img width="634" alt="Screenshot 2020-09-03 at 9 33 45 PM" src="https://user-images.githubusercontent.com/42679215/92139325-35b1b880-ee2d-11ea-8c16-ff463a6b3377.png">

**Comment by borbhuiyagulsan** [comment]
`
info Fetching system and libraries information...
System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 1.27 GB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.18.0 - /usr/local/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.4 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
  Languages:
    Java: 13.0.2 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found
`

**Comment by borbhuiyagulsan** [comment]
`

    const Home = ({ navigation, location1 }) => {



    const value = useSelector(state => state.location1.rValue)
    const cars = useSelector(state => state.location1.cars)
    //console.log(cars)

    const [location, setLocation] = useState({
        latitude: 0,
        longitude: 0,
        latitudeDelta: 0,
        longitudeDelta: 0,

    });
    const [errorMsg, setErrorMsg] = useState(null);

    const GOOGLE_MAPS_APIKEY = '..'';


    useEffect(() => {
        location1();

    }, [])


    useEffect(() => {
        (async () => {
            let { status } = await Location.requestPermissionsAsync();
            if (status !== 'granted') {
                setErrorMsg('Permission to access location was denied');
            }

            let location = await Location.getCurrentPositionAsync({});
            //console.log(location)
            setLocation({
                latitude: location.coords.latitude,
                longitude: location.coords.longitude,
                latitudeDelta: 0.045,
                longitudeDelta: 0.045

            });


        })();
    }

    );

    const [mapMargin, setMapMargin] = useState(1)
    const setMargin = () => {
        setMapMargin(0)
    }



    return (



        <View style={styles.container}>
            <View style={styles.mapStyle}>
                <MapView
                    style={{ ...styles.mapStyle, margin: mapMargin }}
                    provider={PROVIDER_GOOGLE}
                    showsCompass={true}
                    showsMyLocationButton={true}
                    showsUserLocation={true}
                    mapType={"standard"}
                    zoomEnabled={true}
                    initialRegion={location}
                    rotateEnabled={true}
                    onMapReady={setMargin}
                    loadingEnabled={true}
                    loadingIndicatorColor="#666666"
                    loadingBackgroundColor="#eeeeee"
                >





                    {cars ?
                        (
                            <View>
                                {
                                    cars.map((marker, index) => (

                                        <Marker
                                            coordinate={{
                                                latitude: marker.latitude,
                                                longitude: marker.longitude,
                                                key: marker._id

                                            }}
                                        >
                                            <Image source={{ uri: 'https://cdn2.iconfinder.com/data/icons/top-view-cars-1/50/48-512.png' }}
                                                style={{ flex: 1, width: 20, height: 25 }} />

                                        </Marker>

                                    ))
                                }
                            </View>
                        ) : null
                    }
                </MapView>
            </View>



            <View style={{ flex: 1,  justifyContent: 'space-between', width: '100%' , backgroundColor: '#f2f2f2' }}>

                

                <View style={{ flexDirection: 'row', justifyContent: 'center', flex:1, }}>

                    <View style={{ flex: 1, alignItems: 'flex-end', justifyContent: 'center'}}>
                        <Pressable style={({pressed}) => [styles.footer3, {margin: 20, backgroundColor: pressed? 'black' : 'blue'}]}>
                            <Image source={{ uri: 'https://d2gg9evh47fn9z.cloudfront.net/800px_COLOURBOX17665605.jpg' }}
                                style={{ width: 100, height: 70, borderRadius: 50 , }} />
                        </Pressable>

                    </View>


                    <View style={{ flex: 1, justifyContent: 'center', alignContent: 'center'}}>
                        <Pressable style={{  marginLeft: 10, backgroundColor: '#fff',borderRadius: 50, width: 69,borderColor:'grey', borderWidth:1 }}>






                            <Image source={{ uri: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTZ7lR3d9xMNy7sxJZEkCOtQ63uCB4GYxtSAw&usqp=CAU' }}

                                style={{  width: 65, height: 65 , marginBottom: 0, borderRadius: 25}} />


                        </Pressable>
                    </View>

                 

                </View>

                <View >

                    <Pressable


                        onPress={() => {
                            navigation.navigate('destinationOrigin',
                                { current: location })
                        }
                        }

                    >
                        <Button mode="contained" >
                            Where to go?
    </Button>
                    </Pressable>
                </View>


            </View>




        </View>






    );
    }



    export default connect(null, { location1 })(Home);


`

**Comment by chrisglein** [comment]
> My entire code looks like this !

I tried copying that into a Snack but there were quite a few dependencies. This was as far as I got: https://snack.expo.io/@chrisglein/repro29853
If you could get this into a reduced min repro it'd be easier to help you (a Snack or a link to a repo that's easy to evaluate).

**Comment by Pr0boszcz91** [comment]
I have the exact same issue, basically the problem is easy to reproduce:
1) create an expo project
2) import { Pressable } from "react-native";
3) use your <Pressable></Pressable> component in the return part
4) error appears

Apparently from what I've been able to find, the reason is that currently expo (SDK38) is React Native v0.62 and Pressable component has been added in React Native v0.63, so it does not yet exist in the current expo SDK version. (That is so unfortunate as I just started learning RN and was trying to use this Pressable component, but found out it's not yet available...)

**Comment by ashutosh-akss** [comment]
@ghost could you get this resolved? I am facing this issue?
