### ISSUE TITLE
Question: Crash Reporting for React Native apps

### ISSUE THREAD

**Issue by rahamin1** [facebook/react-native#29869]
I cannot find a better place to open this question.

In SO they close such questions, so I hope that this can stay open for few days, to get some opinions of experienced guys.

- Can you briefly share your experience with either or both of these tools, functionality-wise and pricing-wise?

- I read that Crashlytics doesn't provide crash reporting for js crashes. True?

- Any other significant limitation of any of the tools?

------

## React Native version:
react-native info
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 6.69 GB / 15.87 GB
  Binaries:
    Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28, 29
      Build Tools: 25.0.2, 28.0.3, 29.0.2, 29.0.3
      System Images: android-25 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Version  2.3.0.0 AI-162.3764568
  Languages:
    Java: 1.8.0_112-release
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2

**Comment by bneigher** [comment]
Sentry for react native is pretty good

**Comment by rahamin1** [comment]
> Sentry for react native is pretty good

Thanks Ben.
For how long have you been using it?
Can you elaborate a little bit on the way you are using it? Do you use it only for reporting crashes? For other reporting of what?
Any comments about pricing? Is it practical to use the free version for an app that has only hundreds of concurrent users?

**Comment by safaiyeh** [comment]
Hi @rahamin1 thanks for the issue. The issue board is for React Native core issues. Closing

**Comment by rahamin1** [comment]
I am using Sentry for several weeks. Works very well.
