### ISSUE TITLE
Build error with @react-native-firebase/dynamic-links v7.5.0 and above

### ISSUE THREAD

**Issue by tusharlock10** [facebook/react-native#29865]
## Description
I needed to add @react-native-firebase/dynamic-links to my project, I have added various other firebase services like auth, cloud messaging, and they are working fine on their latest version. But when I added @react-native-firebase/dynamic-links, it gave this build error and no information is available about it. I tried v7.5.1 and v7.5.2 and it still gave the same error. v7.4.3 working fine.
![Screenshot (69)](https://user-images.githubusercontent.com/36128584/92284243-45a9c500-ef1f-11ea-9e6f-f63066dfdd83.png)
![Screenshot (70)](https://user-images.githubusercontent.com/36128584/92284247-46daf200-ef1f-11ea-9ab0-bca9a00fffa0.png)
![Screenshot (71)](https://user-images.githubusercontent.com/36128584/92284249-47738880-ef1f-11ea-87dd-3dbce849f651.png)

## React Native version:
System:
    OS: Windows 10 10.0.19041
    CPU: (4) x64 Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz
    Memory: 371.12 MB / 7.89 GB
  Binaries:
    Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 28, 30
      Build Tools: 28.0.3, 30.0.2
      System Images: android-30 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6626763
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
  npmGlobalPackages:
    react-native-cli: 2.0.1

## Expected Results
v7.5.2 (latest) should not have this build error

Currently I am using v7.4.3 as its working for me. I would provide more details if required.

**Comment by safaiyeh** [comment]
Hi @tusharlock10 thanks for the issue. You should file an issue with  @react-native-firebase/dynamic-links, this issue board deals with React Native core issues

**Comment by tusharlock10** [comment]
Oh I didn't see that, sorry my mistake.
