### ISSUE TITLE
FlatList items with absolute position are not visible on Android

### ISSUE THREAD

**Issue by augustbjornberg** [facebook/react-native#29867]
## Description
Like the title says, FlatList items with absolute position are not visible on Android, but works as expected on iOS. 

I've tried every flex-, layout-, size- styling option under the sun on both the FlatList and items, results are always the same.

**Edit:** 

[What it looks like on iOS. Correct.](https://i.imgur.com/3OpEamo.png)
[What it looks like on Android. Incorrect.](https://i.imgur.com/ZoMwCw0.png)

**Edit 2:**

Reproduced bug in latest version of RN.

## React Native version:
System:
    OS: macOS 10.15.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 425.63 MB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.9.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.7 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.7, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 29, 30
      Build Tools: 29.0.2, 30.0.2
      System Images: android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 11.7/11E801a - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_265 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.2 => 0.63.2
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
1. Create Flatlist and render absolute positioned items.
2. Run on device: Items are visible on iOS but not Android.
3. Remove position: absolute, items appear on Android.

## Expected Results
I expect absolute positioned FlatList items to be visible on Android, just as they are on iOS.

## Code example

	render() {
		const items = [{id: 1, color: '#00ff00'}, {id: 2, color: '#0000ff'}]

		return (
			<FlatList
				style={{
					flex: 1,
					width: '100%',
					height: '100%',
					backgroundColor: '#ff0000'
				}}
				data={items}
				keyExtractor={item => item.id.toString()}
				renderItem={({item, index}) => (
					<View style={{position: 'absolute', top: 0, left: 0, width: 100, height: 100, backgroundColor: item.color}}/>
				)}
				showsHorizontalScrollIndicator={false}
				scrollEnabled={false}
			/>		
		)
	}

**Comment by safaiyeh** [comment]
Hi @augustbjornberg, sorry you are having issues. I appreciate the code snippet and screenshots, tagging this appropriately

**Comment by vitali-t-dev** [comment]
Hi @augustbjornberg. Faced with the same problem. Maybe you have found some workaround?

**Comment by DatNguyenCore** [comment]
i'm facing the same problem. In react-native: 0.63.2

**Comment by FlushNorris** [comment]
Ah... not the only one who is very frustrated about this very strange behavior. 
Using react-native: 0.63.3

UnitTest/UI-test before releasing a new version of React Native would be awesome... Getting tired of all these problems

**Comment by AugustGSP** [comment]
> Hi @augustbjornberg. Faced with the same problem. Maybe you have found some workaround?

Yes and no.
I "solved" it by using a regular View on Android. I don't have a ton of items in my list, so it didn't become that much of a performance issue. But addressing this strange bug to make it possible to use FlatList on both iOS and Android would definitely be ideal.

**Comment by mrtaiw** [comment]
> I've solved it by wrapping the FlatList into a SafeAreaView with the flex of 1 👌

i tried and failed, can you post sample code

**Comment by Stevemoretz** [comment]
> I was having the same problem. I found a workaround by setting on my FlatList:
> 
> `contentContainerStyle={{ flexGrow: 1, borderWidth: 1, borderColor: 'transparent' }}`
> 
> It's not necessary to set `borderColor`. Hope it serves as a temporary solution to others.

This works partially not very well though.

**Comment by Stevemoretz** [comment]
> I was having the same problem. I found a workaround by setting on my FlatList:
> 
> `contentContainerStyle={{ flexGrow: 1, borderWidth: 1, borderColor: 'transparent' }}`
> 
> It's not necessary to set `borderColor`. Hope it serves as a temporary solution to others.

Use this with in conjunction with putting your item in the header and use stickyHeaderIndices to make it stick to the top.

```ts
                contentContainerStyle={{ flexGrow: 1, borderWidth: 1, borderColor: 'transparent' }}
                stickyHeaderIndices={[0]}
                ListHeaderComponent={
                    absoluteViewStyle && (
                        <Moti.ViewV
                            style={{
                                position: "absolute",
                                backgroundColor: "#e0e0e0",
                                height: 100,
                                width: 100,
                            }}
                            animate={{
                                backgroundColor: "#e0e0e0",
                                width: dimensions?.[index]?.width || 0,
                                left: snaps?.[index] || 0,
                            }}
                        />
                    )
                }
```

**Comment by abhishek-pokhriyal** [comment]
Facing this issue! Did anyone figure out any workaround? Is this really a bug with react-native?

**Comment by PaulMetley** [comment]
Also interested in any solution about this

**Comment by Stevemoretz** [comment]
Yes my workaround is working fine in production, read a couple comments above.

**Comment by yusera-at-git** [comment]
> I've solved it by wrapping the FlatList into a SafeAreaView with the flex of 1 👌

yes, It worked for me as well..removed the view component and added SafeAreaView component. Thanks for the solution.

**Comment by Federico-Benitez** [comment]
> > I was having the same problem. I found a workaround by setting on my FlatList:
> > `contentContainerStyle={{ flexGrow: 1, borderWidth: 1, borderColor: 'transparent' }}`
> > It's not necessary to set `borderColor`. Hope it serves as a temporary solution to others.
> 
> Use this with in conjunction with putting your item in the header and use stickyHeaderIndices to make it stick to the top.
> 
> ```ts
>                 contentContainerStyle={{ flexGrow: 1, borderWidth: 1, borderColor: 'transparent' }}
>                 stickyHeaderIndices={[0]}
>                 ListHeaderComponent={
>                     absoluteViewStyle && (
>                         <Moti.ViewV
>                             style={{
>                                 position: "absolute",
>                                 backgroundColor: "#e0e0e0",
>                                 height: 100,
>                                 width: 100,
>                             }}
>                             animate={{
>                                 backgroundColor: "#e0e0e0",
>                                 width: dimensions?.[index]?.width || 0,
>                                 left: snaps?.[index] || 0,
>                             }}
>                         />
>                     )
>                 }
> ```

This worked for me, without SafeAreaView.  Thanks for the solution.

**Comment by sanchitos** [comment]
My items are visible, however you can't scroll. This happens only on Android. Search everything, even asked ChatGPT nothing seems to fix this problem.

**Comment by PaulLeymet** [comment]
@sanchitos 
If I remember correctly you can address this issue using the props :
  getItemLayout={(data, index) => (
    {length: ITEM_HEIGHT, offset: ITEM_HEIGHT * index, index}
  )}

**Comment by SP4CEBARsystems** [comment]
React Native likely thinks that the height of the contents is zero (because they are absolute), so on IOS it won't scroll (because it thinks there's nowhere to scroll), and on Android, it won't show anything, which probably has something to do with the lazy loading method that FlatLists use. By adding a footer with relative positions and a fixed height, this issue would go away... but then the items randomly disappear while scrolling, this is likely caused by React Native FlatList's lazy loading method being unable to determine when it's safe to unload those elements

**Comment by SP4CEBARsystems** [comment]
@Stevemoretz your approach of adding a sticky header solved it for me!

**Comment by sunilanumolu** [comment]
> My items are visible, however you can't scroll. This happens only on Android. Search everything, even asked ChatGPT nothing seems to fix this problem.

yes exactly, I also tried everything and still trying different ways.
@sanchitos if you have found solution for scroll issue, can you pls tell.

**Comment by sanchitos** [comment]
> 

I had to change the design approach, no floating elements.
