### ISSUE TITLE
RCT_EXPORT_METHOD : RCTResponseSenderBlock & RCTPromiseResolveBlock/RCTPromiseRejectBlock conflict

### ISSUE THREAD

**Issue by RichardFevrier** [facebook/react-native#29860]
## Description

On runtime, if we call a method exported with `RCTResponseSenderBlock` & `RCTPromiseResolveBlock/RCTPromiseRejectBlock` we are facing an error: `Error: Exception in HostFunction: Malformed calls from JS: field sizes are different.`

The [documentation](https://reactnative.dev/docs/native-modules-ios) does not talk about this conflict so I'm expecting this as a bug.

## React Native version:
`0.63.2`

## Snack, code example, screenshot, or link to a repository:
<img width="510" alt="Screen Shot 2020-09-04 at 11 57 05" src="https://user-images.githubusercontent.com/5154754/92227625-d1333f80-eea6-11ea-9694-afd550d4c50e.png">

**Comment by rectified95** [comment]
Please provide more information and a more concrete repro.
Also, can you check if this issue or the ones it links might help you: https://github.com/software-mansion/react-native-reanimated/issues/557
The error you're referencing seems to come up in google not necessarily as a result of an internal bug.

**Comment by oferRounds** [comment]
@RichardFevrier were you manage to solve the issue? Seeing what seems to be the same on my project. Using React Native 0.62.2

**Comment by RichardFevrier** [comment]
@oferRounds I didn't solve the issue, sorry

**Comment by charliecruzan-stripe** [comment]
Same issue with the latest version of RN (0.71.6): cannot call a native iOS method exported with _both_ `RCTResponseSenderBlock` & `RCTPromiseResolveBlock`/`RCTPromiseRejectBlock`

Reproducible by calling a native method with the signature:
```
RCT_EXTERN_METHOD(
                  myMethodName:(NSDictionary *)params
                  callback: (RCTResponseSenderBlock)myCallback
                  resolver: (RCTPromiseResolveBlock)resolve
                  rejecter: (RCTPromiseRejectBlock)reject
                  )
```

**Comment by amralaa-MSFT** [comment]
How to resolve this?
