### ISSUE TITLE
reactNativePath is not sent properly from config object in Podfile

### ISSUE THREAD

**Issue by aakashsigdel** [facebook/react-native#29873]
## Description
` use_react_native!` function is not called with proper arguments in Podfile.
After defining a custom `react-native.config.js` file in project root. It should be picked up in the Podfile and passed down to `use_react_native!`, but it is not.
Because of this `:path` key in options hash of `use_react_native!` is undefined.
From what little knowledge of ruby I have, this can be fixed by changing `reactNativePath` to a symbol:
Before:
```ruby
  use_react_native!(:path => config["reactNativePath"])
```
After:
```ruby
  use_react_native!(:path => config[:reactNativePath])
```
## React Native version:
```
System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 410.94 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.20.1 - ~/.nvm/versions/node/v10.20.1/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v10.20.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.4 - /usr/local/lib/ruby/gems/2.6.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 22, 23, 25, 26, 27, 28, 29
      Build Tools: 23.0.1, 27.0.3, 28.0.2, 28.0.3
      System Images: android-29 | Google Play Intel x86 Atom, android-Q | Android TV Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: 11.4/11E146 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_211 - /Library/Java/JavaVirtualMachines/jdk1.8.0_211.jdk/Contents/Home/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.2 => 0.63.2
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. add `react-native.config.js` file on project root with following contents 
```javascript
module.exports = {
  reactNativePath: '../node_modules/react-native',
};
```
2. add a `puts(config["reactNativePath"])` statement after the `config = use_native_modules!` call on `Podfile`
3. run pod install

## Expected Results
should print the value of the `reactNativePath` specified in `react-native.config.js` path

## Actual Results
it prints an empty line

## Possible solution (let me know if I should create a PR for this)
since `reactNativePath` is a symbol on the `config` hash, simply changing 
```ruby
  use_react_native!(:path => config["reactNativePath"])
```
to:
```ruby
  use_react_native!(:path => config[:reactNativePath])
```
should solve the issue.

Let me know if this is the correct way to do it and I will create a PR. 
I might need a little direction on where to start and look for the template that is being used to generate the project

**Comment by aakashsigdel** [comment]
this issue has been already fixed now. Closing this

**Comment by rafales** [comment]
@aakashsigdel how was this issue fixed? I just did a fresh install yesterday and I ran into the same problem.

**Comment by rafales** [comment]
@aakashsigdel nvm, I just found it's fixed on master but not released yet.
