### ISSUE TITLE
Invariant Violation: ListView has been removed from React Native

### ISSUE THREAD

**Issue by omarichatman** [facebook/react-native#29877]
## Description
I am getting the **"Invariant Violation: ListView has been removed from React Native"**, after I have run npm install and expo start. I do not have the ListView Component anymore and have **"deprecated-react-native-listview": "0.0.6"** instead as the Error Stack suggests using. I am assuming one or more of my dependencies are using it but I am not sure which one it is.

## React Native version:
Run `react-native info` in your terminal and copy the results here.
I am using **"expo": "^37.0.0"** and **"react-native": "https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz"**

## Steps To Reproduce
1. npm install
2. expo start

## Expected Results
Expo application loads with no issues.

## Snack, code example, screenshot, or link to a repository:
Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.

"dependencies": {
    "@mapbox/polyline": "^1.0.0",
    "accounting": "^0.4.1",
    "buffer": "^5.2.1",
    "cloc": "^2.4.0",
    "deprecated-react-native-listview": "0.0.6",
    "expo": "^37.0.0",
    "expo-asset": "~8.1.4",
    "expo-facebook": "^8.1.0",
    "expo-font": "~8.1.0",
    "expo-image-picker": "~8.1.0",
    "lottie-react-native": "~2.6.1",
    "moment": "^2.24.0",
    "moment-timezone": "^0.5.23",
    "react": "16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz",
    "react-native-calendars": "^1.21.0",
    "react-native-confirmation-code-input": "^1.0.4",
    "react-native-countdown-component": "^2.2.0",
    "react-native-credit-card-input": "^0.4.1",
    "react-native-datepicker": "^1.7.2",
    "react-native-dismiss-keyboard": "^1.0.0",
    "react-native-draggable": "^1.0.14",
    "react-native-dropdown": "0.0.6",
    "react-native-dropdown-menu": "^2.0.0",
    "react-native-dropdownalert": "^3.9.2",
    "react-native-elements": "^1.1.0",
    "react-native-fetch-polyfill": "^1.1.3",
    "react-native-gesture-handler": "~1.6.0",
    "react-native-google-places-autocomplete": "^1.3.9",
    "react-native-ios-picker": "^1.0.0",
    "react-native-keyboard-aware-scroll-view": "^0.7.4",
    "react-native-maps": "0.26.1",
    "react-native-modal": "^7.0.2",
    "react-native-modal-datetime-picker": "^6.0.0",
    "react-native-modal-dropdown": "^0.6.2",
    "react-native-open-maps": "^0.3.3",
    "react-native-paper": "^2.15.2",
    "react-native-picker-select": "^5.1.0",
    "react-native-reanimated": "^1.8.0",
    "react-native-screens": "~2.2.0",
    "react-native-simple-radio-button": "^2.7.3",
    "react-native-stars": "^1.1.5",
    "react-native-tab-view": "^2.14.0",
    "react-native-vector-icons": "^6.0.2",
    "react-native-viewpager": "^0.2.13",
    "react-native-webview": "^9.3.0",
    "react-navigation": "^3.0.9",
    "rn-placeholder": "^1.3.3",
    "rn-sliding-up-panel": "^2.2.0",
    "stripe-client": "^1.1.5"
  }

![Screenshot_20200905-180517_Expo](https://user-images.githubusercontent.com/15680300/92339383-c8e42b80-f083-11ea-94b7-0988853aaea5.jpg)

**Comment by rectified95** [comment]
Issues with library versions in Expo while using RN are typically a result of Expo problems. Consider filing an issue there.

See this - https://stackoverflow.com/questions/25997519/how-to-view-the-dependency-tree-of-a-given-npm-module - for how to generate a dependency tree.

**Comment by iambavith** [comment]
Try using Flatlist instead of List View [https://reactnative.dev/docs/flatlist#docsNav](Here)

**Comment by alihamza-datics** [comment]
@omarichatman  did you find an answer? please share I'm facing the same problem. I'm not using ListView in my project  but still I am facing this error

**Comment by aliustaoglu** [comment]
@alihamza-datics May be your dependencies use it. You can try below command (or similar if not in macOS) to find out if any of your dependencies use it. 

> mdfind "ListView" -onlyin "./node_modules"

... having said that I still have the same issue. I found some libraries using ListView upgraded them until I see above command returns nothing. But I still get this issue.

**Comment by alihamza-datics** [comment]
@aliustaoglu I solved my by upgrading these two packages
-react-native-modal-dropdown
-react-native-keyboard-aware-scroll-view
both of them uses ListView in older versions

**Comment by ShiarOs** [comment]
You can use FlatList

EX:
`import React, { Component } from 'react';

import { AppRegistry, StyleSheet, FlatList, Text, View, Alert, ActivityIndicator, Platform} from 'react-native';

export default class Project extends Component {
  
  constructor(props)
  {

    super(props);

    this.state = { 
    isLoading: true
  }
  }

  componentDidMount() {
    
       return fetch('https://yourDatalink')
         .then((response) => response.json())
         .then((responseJson) => {
           this.setState({
             isLoading: false,
             dataSource: responseJson
           }, function() {
             // In this block you can do something with new state.
           });
         })
         .catch((error) => {
           console.error(error);
         });
     }

FlatListItemSeparator = () => {
    return (
      <View
        style={{
          height: 1,
          width: "100%",
          backgroundColor: "#607D8B",
        }}
      />
    );
  }

  GetFlatListItem (email) {
   
  Alert.alert(email);

  }


  render() {

    if (this.state.isLoading) {
      return (
        <View style={{flex: 1, paddingTop: 20}}>
          <ActivityIndicator />
        </View>
      );
    }

    return (

<View style={styles.MainContainer}>
  
       <FlatList
       
          data={ this.state.dataSource }
          
          ItemSeparatorComponent = {this.FlatListItemSeparator}

          renderItem={({item}) => <Text style={styles.FlatListItemStyle} onPress={this.GetFlatListItem.bind(this, item.email)} > {item.id}</Text>}

          keyExtractor={(item, index) => index}
          
         />
    
    
</View>
            
    );
  }
}

const styles = StyleSheet.create({

MainContainer :{

justifyContent: 'center',
flex:1,
margin: 10,
paddingTop: (Platform.OS === 'ios') ? 20 : 0,

},

FlatListItemStyle: {
    padding: 10,
    margin: 10,
    backgroundColor: '#145996',
    color: '#fff',
    height: 44,
  },

});

AppRegistry.registerComponent('Project', () => Project);`
