### ISSUE TITLE
None of your spec sources contain a spec satisfying the dependency: `React/Core (from `../node_modules/react-native`)`.

### ISSUE THREAD

**Issue by xiaopindev** [facebook/react-native#29883]
How to integration with existing apps in the 0.63.2 version?

https://reactnative.dev/docs/integration-with-existing-apps
I was unable to successfully set up and install the development environment through the documentation process.

The "pod install" error info in iOS Application use Swift or Objective-C:
----------------
[!] CocoaPods could not find compatible versions for pod "React/Core":
  In Podfile:
    React/Core (from `../node_modules/react-native`)

None of your spec sources contain a spec satisfying the dependency: `React/Core (from `../node_modules/react-native`)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
------------------
I looked for a lot of methods on the Internet, see a lot of posts, still can't solve this problem. I request the authorities to solve this problem or provide a feasible solution.

**Comment by xiaopindev** [comment]
> ⚠️	Missing Environment Information
> ℹ️	Your issue may be missing information about your development environment. You can obtain the missing information by running `react-native info` in a console.

How to run 'react-native info' ?  It's print ‘zsh: command not found: react-native’ in console.

**Comment by chrisglein** [comment]
> How to run 'react-native info' ? It's print ‘zsh: command not found: react-native’ in console.

That information should be the same as your general setup that you did as part of [Getting Started](https://reactnative.dev/docs/environment-setup)

**Comment by felipe2g** [comment]
No solution for this? i'm updating a project from 0.59.1 to 0.60.0 and getting the same.

**Comment by xiaopindev** [comment]
> No solution for this? i'm updating a project from 0.59.1 to 0.60.0 and getting the same.

I have given up using RN because it has too many problems and there is no official solution！

**Comment by chrisglein** [comment]
> No solution for this? i'm updating a project from 0.59.1 to 0.60.0 and getting the same.

The current version is 0.64. 0.59 is 2 years old. You're going to get the best support apps by being updating to current versions. Since it seems like you're having an upgrade issue in which case the [upgrade helper](https://react-native-community.github.io/upgrade-helper/) is maybe more what you're looking for.
