### ISSUE TITLE
Static GIF will disappear and reappear when showing alert on iOS 

### ISSUE THREAD

**Issue by Rotemy** [facebook/react-native#29892]
Hello,

We are using the `Image` component to display images, but when we are displaying this [image](https://cloudfront.getselect.co/31f573b1-d61d-11ea-b2ae-724231592072.gif) the image will disappear and reappear randomly. [Here is a video](https://streamable.com/6xlyh8) to show the behavior.

We are using react-native-navigation to navigate between screens, but I highly doubt that it is related to the issue.

## React Native version:
```
System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.10 GB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.17.0 - ~/.nvm/versions/node/v10.17.0/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.11.3 - ~/.nvm/versions/node/v10.17.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3
      System Images: android-28 | Intel x86 Atom, android-28 | Intel x86 Atom_64, android-29 | Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
```

**Comment by rectified95** [comment]
Please provide a repro, ideally using an Expo Snack. Otherwise, it's difficult to investigate this issue.

**Comment by Rotemy** [comment]
Hi @rectified95, [here is Expo Snack](https://snack.expo.io/WROyWX7b_) that reproduces the issue - just tap the button to see the image disappears.

https://snack.expo.io/WROyWX7b_

**Comment by rectified95** [comment]
Confirming incorrect behavior - using a URL for different file formats, eg. JPEG works fine, while a GIF disappears after clicking an unrelated button. Flagging for triage meeting.

**Comment by BalaManikantaB** [comment]
Hi @Rotemy, were you able to find a fix for this issue?

**Comment by Rotemy** [comment]
> Hi @Rotemy, were you able to find a fix for this issue?

Nope, waiting for a fix or at least a patch.

**Comment by godot007** [comment]
@rectified95 were you able to find a fix for this issue?
