### ISSUE TITLE
Can't change text input style when an emoji is added to text

### ISSUE THREAD

**Issue by chahinaghrim** [facebook/react-native#29890]
I am currently building a text editor which allows the user to add multiple textsinputs which the user can customise.
I can successfully increase the font size, change the color, background color and so on. However, as soon as I add an emoji from the keyboard, the text input does not update when I change the style.

## React Native version:
0.62

## When there is no emoji, the entire text gets updated.
<img width="360" alt="Screenshot 2020-09-08 at 11 30 35" src="https://user-images.githubusercontent.com/65279833/92459241-b7576c80-f1c6-11ea-9fc5-7c30205e9af7.png">

### When there is an emoji, only the next coming letters get updated. Not the entire text anymore.
<img width="363" alt="Screenshot 2020-09-08 at 11 31 53" src="https://user-images.githubusercontent.com/65279833/92459386-ea99fb80-f1c6-11ea-98b0-e7a62f419872.png">

###  This is a small snapshot of my code:

<>
export default function App() {
   const [text, setText] = useState('');
       const [style, setStyle] = useState({
        fontFamily: 'Montserrat',
        fontSize: 20,
        textAlign: 'left',
        color: '#FFFFFF',
        backgroundColor: null,
    });

    useEffect(() => {
        //Update textInput properties
        setStyle({
            fontFamily: fontDataStyles[currentFontIndex],
            fontSize: currentFontSize,
            textAlign: fontAlignment[currentTextAlignIndex],
            color: colorData[currentColorIndex],
            backgroundColor: backgroundColorData[currentBackgroundColorIndex],
        });
 
    }, []);

  return (
    <View style={styles.container}>
      <TextInput
        ref={InputRef}
        key={props.index}
        onChangeText={(text) => setText(text)}
        style={style}
        defaultValue={text}
        autoFocus={true}
        placeholder={''}
        multiline={true}
        keyboardAppearance={'light'}
        allowFontScaling={true}
      />
    </View>
  );
}
<>

**Comment by milgner** [comment]
This issue had already been reported in #25874 but wasn't solved and closed due to inactivity. It still persists, though.

**Comment by RichardFevrier** [comment]
Also reported in #29286

**Comment by benjaminaudet** [comment]
Hey,

Have the same issue here, it's working on Android but not on iOS, could be cool to see it working on iOS soon.

**Comment by benjaminaudet** [comment]
OK, I've made a little hack to make it work. When I change the color of the textInput (or any style), I set the text of the TextInput to a space character, I change the style within a setTimeout of 1ms and I set back the previous text.
It works with a little blink but it make it works at least

**Comment by lokomass** [comment]
Same issue for me, any update ?

**Comment by chahinaghrim** [comment]
> OK, I've made a little hack to make it work. When I change the color of the textInput (or any style), I set the text of the TextInput to a space character, I change the style within a setTimeout of 1ms and I set back the previous text.
> It works with a little blink but it make it works at least

a good idea. I will try as well

**Comment by chahinaghrim** [comment]
Tried this solution , it works but it is not very user friendly. 
I found a workaround. Place a normal <Text></Text> on top of the textInput element and place in the value that has been changed from TextInput. Whatever style you wish to apply to the textInput, the text will render it. Make sure you hide the textInput tho. 
This works for me. 

But again, REACT NATIVE please enable us to apply the same transformation styles to the textInput as you already have for the normal text element!!!

**Comment by eylamf** [comment]
Not an ideal solution, but it worked for me - update the `key` of the TextInput based on some variable that updates the styling of the input. For example, in a task list where the `task.completed` field can be toggled:
```tsx
<TextInput
  key={`${task.id}_${task.completed}`}
  style={[styles.input, {textDecorationLine: task.completed ? 'line-through' : 'none'}]}
  ...
/>
```

**Comment by lokomass** [comment]
> 
> 
> Not an ideal solution, but it worked for me - update the `key` of the TextInput based on some variable that updates the styling of the input. For example, in a task list where the `task.completed` field can be toggled:
> 
> ```tsx
> <TextInput
>   key={`${task.id}_${task.completed}`}
>   style={[styles.input, {textDecorationLine: task.completed ? 'line-through' : 'none'}]}
>   ...
> />
> ```

Amazing work for me, thanks a lot man !

**Comment by RorschachPrime** [comment]
I am currently facing the same problem and this might be off topic but did you use any native code while building that text highlighter thing ? How if you didn't ?

**Comment by ktayah** [comment]
Also facing this issue, would like to see a fix.

**Comment by NongKaittong** [comment]
How to fix this solution ?

**Comment by jack-li-mox** [comment]
inputting Chinese also have this issue
>Not an ideal solution, but it worked for me - update the key of the TextInput based on some variable that updates the >styling of the input. For example, in a task list where the task.completed field can be toggled:

>```
><TextInput
>  key={`${task.id}_${task.completed}`}
>  style={[styles.input, {textDecorationLine: task.completed ? 'line-through' : 'none'}]}
>  ...
>/>
>```
the keyboard keep dismiss when the key getting update
for example i put `key={value.length}`

**Comment by AdamTyler** [comment]
It would be nice to have a real fix for this issue.

I'm using the text input inside a `KeyboardAvoidingView` and unfortunately the fix to adding the key will rerender the view causing it to pop up/down.

**Comment by Tymofiev** [comment]
+1, v. 0.63.4

**Comment by neomrc** [comment]
+1

**Comment by Foohx** [comment]
+1

**Comment by rsk7** [comment]
+1

**Comment by Nortrim** [comment]
I found a solution that works fine for me. Key changing dismisses the keyboard and makes my input unusable. I used react-native animations 

`
import { Animated, TextInput } from 'react-native';
import React, { useMemo } from 'react';

const AnimatedTextInput = Animated.createAnimatedComponent(TextInput);

const TextInputWrap: React.FC<IProps> = ({ value, onChangeText }) => {
  const animatedInputStyle = useMemo(
    () => ({
      fontSize: 30 - 4 * Math.floor(value.length / 30),
    }),
    [value],
  );

  return (
    <AnimatedTextInput
      style={animatedInputStyle}
      placeholder={'notePlaceholder'}
      value={value}
      onChangeText={onChangeText}
      maxLength={150}
      multiline
      autoFocus
    />
  );
};
`

**Comment by gregdburns** [comment]
Also experiencing this issue with a TextInput that has multiple text components (used for formatting within the text input).  Happens with both emoji and Chinese characters (assuming non-ASCII).

I tried both workarounds (updating the Key value and using Animated), however both of these solutions result in jittery text input, and cause other side effects when working with and manipulating the cursor position.

**Comment by see2ever** [comment]
any updates?
