### ISSUE TITLE
Could not install CocoaPods after upgrading to react-native 0.63

### ISSUE THREAD

**Issue by manastasiou** [facebook/react-native#29896]
After upgrading to react-native 0.63 i get the following error
The error message is from react-native 0.63.2 but i get the same error with 0.63
<img width="1326" alt="Screen Shot 2020-09-08 at 9 28 58 PM" src="https://user-images.githubusercontent.com/48202777/92514521-b51efd80-f21a-11ea-8d89-8b46dda23e1e.png">
I also tried to run pod update, with no luck

My environment is

> System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 22.29 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.8.4 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 11.2/11B44 - /usr/bin/xcodebuild
  Languages:
    Java: 13.0.2 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by evanwalsh** [comment]
Don't forget to check out the [upgrade tool for the latest Podfile](https://react-native-community.github.io/upgrade-helper/?from=0.62.2&to=0.63.2).

[The current template's Podfile looks like this](https://github.com/facebook/react-native/blob/67af6e54fcafed38c677206f81687b665ad2e3d7/template/ios/Podfile).

**Comment by manastasiou** [comment]
Thank you @evanwalsh
