### ISSUE TITLE
On iOS, changing the value of multiline when a TextInput is focused forces the keyboard to be dismissed.

### ISSUE THREAD

**Issue by divonelnc** [facebook/react-native#29907]
## Description
If you have a dynamic value for `multiline` on a TextInput, changing its value will cause the keyboard to get dismissed.
This makes it difficult to make a messenger-like input that is a single line when out of focus and multiline when focused.

Note that this does not happen on Android. It also does not happen if there is no way to manually blur the input (for example no scroll view that can be tapped on)

## React Native version:
```
  Binaries:
    Node: 10.15.3
    Yarn: 1.22.0
    npm: 6.14.5
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Create a component with a `TextInput` and a `ScrollView` (the text input does not need to be inside the view)
2. Make the multiline value of the TextInput change when it gets focused
3. You should notice that you have to tap the TextInput multiple times to keep the keyboard up

## Expected Results
The keyboard should stay visible without having to tap the input again. The way it does on Android.

## Snack, code example, screenshot, or link to a repository:
https://snack.expo.io/@divone/changing-multiline-removes-focus

**Comment by hank121314** [comment]
Maybe duplicated #29569?
And I had made a PR https://github.com/facebook/react-native/pull/29580.
Please check whether this pr is work for you 😄.

**Comment by divonelnc** [comment]
Hello! 
Unfortunately, I am using expo and I cannot change this part of the code :(

**Comment by hank121314** [comment]
> Hello!
> Unfortunately, I am using expo and I cannot change this part of the code :(

OK! I will try to test it.

**Comment by hank121314** [comment]
Unfortunately, It seems to be a different issue.
I will try to figure it out later, sorry.
