### ISSUE TITLE
[RFC] Add option to prevent renderRow from being called if interaction is in progress

### ISSUE THREAD

**Issue by brentvatne** [facebook/react-native#2990]
Diff: https://github.com/brentvatne/react-native/commit/83c1b4e7c2a6b089f8ec46d3d99801cc5ba20572

This allows me to render some initial X rows in a new scene, then trigger a fading animation to make it visible, during which no new rows will be rendered. Maybe useful in other cases too, eg: rows are being rendered while you start dragging something.

**Comment by ide** [comment]
One interesting thing about this approach is that it crudely approximates incremental rendering. Combined with `requestIdleCallback` this could be an interesting avenue to explore before React 2.
cc @sahrens

**Comment by brentvatne** [comment]
Forgot to mention in the initial post that @ide came up with this idea and I just tried it out :)

**Comment by brentvatne** [comment]
cc @vjeux

**Comment by vjeux** [comment]
@sahrens is looking at ListView right now

**Comment by jeanregisser** [comment]
I have been using https://github.com/brentvatne/react-native/commit/83c1b4e7c2a6b089f8ec46d3d99801cc5ba20572 for 2 weeks now and it has helped smoothing out animations tremendously.
My main use case was popups that were appearing animated (scale & fade) with a ListView inside.

Does it still have a chance to land?

**Comment by brentvatne** [comment]
@jeanregisser - I've since forked ListView into something I just called FeedView (because I use it in a feed :P) that has pretty much the same effect: https://gist.github.com/brentvatne/80675663483c2015bbe2

It also has a nice feature for infinite scrolling: if you set pageSize to 10, it will render these rows in interruptible chunks (using the same logic as Incremental / IncrementalPresenter discussed here: https://github.com/facebook/react-native/pull/4953) and only reveal the rows when all of them have rendered.

In my opinion, ListView should probably always work like this, cc @sahrens

**Comment by grabbou** [comment]
Is this still relevant given WindowedListView? https://github.com/facebook/react-native/blob/master/Libraries/Experimental/WindowedListView.js#L70

**Comment by sahrens** [comment]
WindowedListView is still very experimental, so I wouldn't rely on it yet.

Have you been using it in your apps? How has it been working out?

On Apr 25, 2016, at 10:48 AM, Mike Grabowski <notifications@github.com<mailto:notifications@github.com>> wrote:


Is this still relevant given WindowedListView? https://github.com/facebook/react-native/blob/master/Libraries/Experimental/WindowedListView.js#L70

**Comment by lacker** [comment]
Since this RFC has been stale a while I'm going to close the issue. Hope you got the comments you desired. :D
