### ISSUE TITLE
[TypeError: Network request failed] using fetch, iOS only issue

### ISSUE THREAD

**Issue by nikolai369** [facebook/react-native#29908]
## Description
I cant reach my API on iOS emulator. The same code runs perfectly on the Android emulator. I tried a couple of other APIs just to test and everything works as intended (JSONPlaceholder with HTTPS and some random one that uses HTTP. Both GET and POST work fine).

## React Native version:
System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 31.91 MB / 8.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 14.6.0 - ~/.nvm/versions/node/v14.6.0/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v14.6.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2
      System Images: android-29 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 11.3.1/11C505 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_265 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.2 => 0.63.2
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Expected Results
I would expect the same request to go through on both platforms as per usual.

## Code example and error screenshot:

```
const login = async (authData) => {
  console.log('fetching...');
  //Setting up the request
  //Select apropriate port 8515 | 8516
  const port = handlePortSelection(authData.username);
  const url = `http:\\xxx.xxx.xxx.xxx:${port}/api/Auth/LoginUser`;

  const headers = {'Content-Type': 'application/json; charset=UTF-8'};

  const body = JSON.stringify(authData);

  const requestOptions = {
    method: 'POST',
    headers: headers,
    body: body
  };

  try {
    //Call API
    const response = await fetch(url, requestOptions);

    const data = await response.json();

    setUserData(data);
  } catch (error) {
    console.error(error);
  }
};
```

![Simulator Screen Shot - iPhone 11 - 2020-09-09 at 12 13 21](https://user-images.githubusercontent.com/30172556/92586033-07513480-f296-11ea-8a6c-70568837e207.png)

## My Info.plist file: 

```
    <dict>
        <key>NSAllowsArbitraryLoads</key>
        <true/>
        <key>NSExceptionDomains</key>
        <dict>
            <key>localhost</key>
            <dict>
                <key>NSExceptionAllowsInsecureHTTPLoads</key>
                <true/>
            </dict>
        </dict>
    </dict>
```

**Comment by nikolai369** [comment]
> My POST request goes through on Android simulator but throws an error on iOS simulator. When fetching a GET response everything works as intended on both platforms.

Update
I have tested this with the JSONPlaceholder API and I am able to get a response from a POST request on iOS which is even more confusing now... Still can't get it to work with my API on iOS. Any clues would be greatly appreciated.

**Comment by vajid-khan** [comment]
I am facing similar issue on ios. My api calls fails randomly, same api call works one time, other time fails.
Using axios 0.19.2 tried fetch api but same result
Rn version 0.62.2.
On android its working fine.

**Comment by nikolai369** [comment]
> I am facing similar issue on ios. My api calls fails randomly, same api call works one time, other time fails.

Unfortunatley, my call never goes through on iOS, but always works on Android. Still having the same issue...

**Comment by AndreyTrembak** [comment]
Hi @nikolai369 
I have the same issue on IOS 14 only. On IOS 13 it works fine. 
Did you solve it? 

My error looks like this
`TypeError: Network request failed
    at fetch.umd.js:527
    at JSTimers.js:235
    at _callTimer (JSTimers.js:130)
    at Object.callTimers (JSTimers.js:383)
    at MessageQueue.__callFunction (MessageQueue.js:416)
    at MessageQueue.js:109
    at MessageQueue.__guard (MessageQueue.js:364)
    at MessageQueue.callFunctionReturnFlushedQueue (MessageQueue.js:108)
    at RNDebuggerWorker.js:2`

**Comment by youssef212** [comment]
same it works fine but randomly throws this on android it nearly doesn't happen at all , i am testing both on same network on different devices not just emulator ad in debug and release modes

**Comment by nikolai369** [comment]
I think I got it. Please correct me if I am wrong. I ran the nscurl command on a endpoint of my REST api with --ats-diagnostics flag and it failed every test. Example of the last test nscurl tried: 

> TLSv1.0 with PFS disabled and insecure HTTP allowed
ATS Dictionary:
{
    NSExceptionDomains =     {
        "xxx.xxx.xxx.xxx" =         {
            NSExceptionAllowsInsecureHTTPLoads = true;
            NSExceptionMinimumTLSVersion = "TLSv1.0";
            NSExceptionRequiresForwardSecrecy = false;
        };
    };
}
2020-12-05 17:15:10.167 nscurl[9040:230227] NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9836)
Result : FAIL
Error : Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={NSErrorFailingURLStringKey=https://xxx.xxx.xxx.xxx:<port>/api/Exam/GetUslugeIspita, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, _kCFStreamErrorDomainKey=3, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <2D6A72CC-E4E6-41C6-AD0D-931DACD56932>.<1>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <2D6A72CC-E4E6-41C6-AD0D-931DACD56932>.<1>"
), NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made., NSErrorFailingURLKey=https://xxx.xxx.xxx.xxx:<port>/api/Exam/GetUslugeIspita, NSUnderlyingError=0x7fd66ce72ff0 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, _kCFNetworkCFStreamSSLErrorOriginalValue=-9836, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9836}}, _kCFStreamErrorCodeKey=-9836}

So I am guessing it has something to do with me trying to call a server outside my LAN with a IP address. On the official Apple Developer docs about ATS I only found an example of using an IP address to access a local server: https://developer.apple.com/documentation/bundleresources/information_property_list/nsapptransportsecurity/nsallowslocalnetworking

Are you guys accessing your REST apis via domain name or IP address?

If that is the case, can I somehow bypass ATS completly or I have no other choice than to reconfigure my server.
As I said, I am kind of a noob and still learning all of this so please correct me if I am wrong.

Cheers!

**Comment by computerjazz** [comment]
This issue occurred when we would POST in response to a deeplink in a `Linking.addEventListener("url")` callback. It turned out the callback was firing before the app entered the "foreground" (checked via `AppState`), and apparently POST fails when the app is backgrounded (verified by setting a timeout on another POST and backgrounding the app before it fired -- same failure).

Our solution was to wait for the app to fully re-enter the foreground before triggering any POST requests.

**Comment by alihassan0** [comment]
@computerjazz Thanks a lot man <3. I have been spinning around trying to figure out why this happens for over 10 hours. 
This should be added to the docs.

**Comment by farzd** [comment]
@computerjazz thank, spent 2 days trying to figure this one out. Was only having problem on published app on test flight

**Comment by davidsalib** [comment]
@computerjazz how did you handle only making the request after the app is 'fully foregrounded'? Having the same issue with the deeplink.

**Comment by NilsBaumgartner1994** [comment]
I am facing this problem with only specific iOS versions, which annoys some of my users.

**Comment by farzd** [comment]
@NilsBaumgartner1994  please see @computerjazz response above

**Comment by NilsBaumgartner1994** [comment]
Yeah, that is not the same situation for me ... the app is already in foreground

**Comment by vicrac** [comment]
Same here: iPhone 11 - always throws `Network request failed`, but w.g. iPhone SE 2nd generation - works just fine 🤯

**Comment by sanampatel-drizly** [comment]
Same for me. I'm preventing requests when `AppState.currentState != "active"`. But I'm still getting `Network request failed` when a request is fired off right after the app comes into foreground. Sometimes even with a 5-10 second delay after "app will enter foreground".
