### ISSUE TITLE
[Style][iOS]The style lineHeight behaves not exactly same as CSS

### ISSUE THREAD

**Issue by cxfeng1** [facebook/react-native#2991]
I write a Text component whose style is：
```
text: {
    height: 60,
    fontSize: 12,
    width:50,
    padding:5,
    color: 'rgb(238, 238, 238)',
    fontFamily: 'Helvetica Neue',
    lineHeight: 50,
    backgroundColor: 'rgb(190, 173, 146)'
  },
```

It appears like this in iOS device :

<img width="53" alt="2015-09-23 9 33 12" src="https://cloud.githubusercontent.com/assets/1625893/10063736/9982dc7e-62a3-11e5-92f3-cd01f4347377.png">

But in Web,  it is supposed to be like :

<img width="51" alt="2015-09-23 9 38 05" src="https://cloud.githubusercontent.com/assets/1625893/10063606/74a55f5e-62a2-11e5-9d43-e419276c33c6.png">

The text should be vertically centered.

Is there any way to fix this ?  Some FE is used to use `lineHeight=height` to make the text vertically centered.

**Comment by cxfeng1** [comment]
In addition, the text height measured in RCTMeasure is also not exactly same as H5， about 1.5px smaller than H5's text height

**Comment by ide** [comment]
What is "H5"? Do you mean an `h5` element?

**Comment by cxfeng1** [comment]
@ide H5 = HTML5 = Web,   I used same CSS style in Web,  but behave differently

**Comment by ide** [comment]
OK. The centering behavior should probably be the same but I'm not sure about the text height. There are some things that iOS and Android and browsers all do differently and font rendering is one of them.

**Comment by timzaak** [comment]
I wrote a demo in https://rnplay.org/apps/mJMANg.
and the lineHeight has no effect on Android.
maybe. I should use marginTop/marginBottom instead of lineHeight.

**Comment by iplus26** [comment]
Does this issue have a good solution? 
I have the same problem and it cause a lot problems when typesetting.

**Comment by anderson916** [comment]
Same problem here.  I set lineHeight to 40, but the real effect is 40.975.

**Comment by xueduany** [comment]
Sure, I found this problem when I use line-height attribute ,hope that the text is is vertical align in the box,
but it is not.
