### ISSUE TITLE
TextInput wrong first focus and focus on Scroll (Android)

### ISSUE THREAD

**Issue by cheng500** [facebook/react-native#29911]
## Description
TextInput multiline Bugs:
1. First Touch onto `<TextInput multiline />` forces selection to be the last position no matter which position is clicked on
2. Scrolling `<TextInput multiline />` while it is not focused focuses, making keyboard appear

## React Native version:
System:
    OS: macOS 10.15.5
    CPU: (4) x64 Intel(R) Core(TM) i5-4308U CPU @ 2.80GHz
    Memory: 607.90 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.9.0 - ~/.nvm/versions/node/v14.9.0/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.9.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.4 - /Users/chengkuan/.rvm/rubies/ruby-2.6.3/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.7, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 26, 28
      Build Tools: 28.0.3, 29.0.0
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 11.7/11E801a - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_144 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.2 => 0.63.2
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. initiate a new project with `react-native init`
2. Replace content of `index.js` with the sample code below:

## Expected Results
1. First focus on `<TextInput multiline />` should focus on the clicked position
2. Scrolling shouldn't trigger focus of `<TextInput multiline />`
3. Build the app for Android
4. Trigger first click onto `<TextInput multiline />` to see focus bug
5. Click outside the `<TextInput multiline />`to blur
6. Try scrolling `<TextInput multiline />` to see keyboard popup

## Snack, code example, screenshot, or link to a repository:
```
import {name as appName} from './app.json'

import React from 'react'
import { AppRegistry, TextInput, TouchableWithoutFeedback, View } from 'react-native'

const text = 'Lorem ipsum dolor sit amet,\nconsetetur sadipscing elitr,\nsed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat,\nsed diam voluptua.\nAt vero eos et accusam et justo duo dolores et ea rebum.\nStet clita kasd gubergren,\nno sea takimata sanctus est Lorem ipsum dolor sit amet.\nLorem ipsum dolor sit amet,\nconsetetur sadipscing elitr,\nsed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat,\nsed diam voluptua.\nAt vero eos et accusam et justo duo dolores et ea rebum.\nStet clita kasd gubergren,\nno sea takimata sanctus est Lorem ipsum dolor sit amet.'

const App = function App() {
  const ref = React.useRef(null)

  return (
    <TouchableWithoutFeedback onPress={() => ref && ref.current && ref.current.blur()}>
      <View style={{ flex: 1, justifyContent: 'center' }}>
        <TextInput
          ref={ref}
          multiline
          style={{ height: 200, borderWidth: 1 }}
          value={text}
        />
      </View>
    </TouchableWithoutFeedback>
  )
}

AppRegistry.registerComponent(appName, () => App)
```

**Comment by kunsachdeva** [comment]
Was there any solution for this?

**Comment by fabriziobertoglio1987** [comment]
does not reproduce on API 30


**<details><summary>CLICK TO OPEN TESTS RESULTS</summary>**
<p>

| **AFTER** | 
|:-------------------------:|
| <img src="https://user-images.githubusercontent.com/24992535/109958274-57113580-7ce6-11eb-8000-be7fab5422c3.mp4" width="700" height="" /> |

</p>
</details>

**Comment by fabriziobertoglio1987** [comment]
as explained in https://github.com/facebook/react-native/issues/29308#issuecomment-790756840 

I suggest you to try to test this scenarios using react-native-gesture-handler components. Thanks

**Comment by fabriziobertoglio1987** [comment]
solved with https://github.com/facebook/react-native/issues/29308#issuecomment-792864162

**Comment by roman-r-m** [comment]
Had a look at the scrolling issue, compared with Android's native widget (which works correctly)

The reason it's scrolled seems to be due to this block in `android.widget.Editor#onFocusChanged` (sll code references are for Android API 29):
```
                // The DecorView does not have focus when the 'Done' ExtractEditText button is
                // pressed. Since it is the ViewAncestor's mView, it requests focus before
                // ExtractEditText clears focus, which gives focus to the ExtractEditText.
                // This special case ensure that we keep current selection in that case.
                // It would be better to know why the DecorView does not have focus at that time.
                if (((mTextView.isInExtractedMode()) || mSelectionMoved)
                        && selStart >= 0 && selEnd >= 0) {
                    /*
                     * Someone intentionally set the selection, so let them
                     * do whatever it is that they wanted to do instead of
                     * the default on-focus behavior.  We reset the selection
                     * here instead of just skipping the onTakeFocus() call
                     * because some movement methods do something other than
                     * just setting the selection in theirs and we still
                     * need to go through that path.
                     */
                    Selection.setSelection((Spannable) mTextView.getText(), selStart, selEnd);
                }
```

When using native Android TextView `mSelectionMoved` is false so this block is skipped, with RN however it's true and this is where the scrolling comes from.

Now, I've traced the difference in this field back to how text content is set to the widget. Android's TextView resets this flag in `android.widget.TextView#setText`:
```
            if (mMovement != null) {
                mMovement.initialize(this, (Spannable) text);

                /*
                 * Initializing the movement method will have set the
                 * selection, so reset mSelectionMoved to keep that from
                 * interfering with the normal on-focus selection-setting.
                 */
                if (mEditor != null) mEditor.mSelectionMoved = false;
            }

```

RN bypasses this method and uses a different way to set text in `com.facebook.react.views.textinput.ReactEditText#maybeSetText` and the `mSelectionMoved` is not cleared.

Hope this helps.

**Comment by Philipp91** [comment]
I assume you're referring to [this](https://github.com/facebook/react-native/blob/9e21d54cfcd5cdee9679f892cc1f54da30b10be4/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactEditText.java#L556), where `getText().replace()` is used instead of `setText()`.

**Comment by roman-r-m** [comment]
I think may be a workaround for this issue: add new `ReactPackage` with
```java
    @NonNull
    @Override
    public List<ViewManager> createViewManagers(@NonNull ReactApplicationContext reactContext) {
        return Collections.singletonList(new ReactTextInputManager() {
            @Override
            public void receiveCommand(ReactEditText reactEditText, String commandId, @Nullable ReadableArray args) {
                if ("focus".equals(commandId) || "focusTextInput".equals(commandId)) {
                    Selection.removeSelection(reactEditText.getText());
                }
                super.receiveCommand(reactEditText, commandId, args);
            }
        });
    }
```

**Comment by roman-r-m** [comment]
Positing a workaround I found in case someone will find it useful.
Add a package containing this to your `MainApplication`
```java
    @NonNull
    @Override
    public List<ViewManager> createViewManagers(@NonNull ReactApplicationContext reactContext) {
        return Collections.singletonList(new ReactTextInputManager() {
            @Override
            public void receiveCommand(ReactEditText reactEditText, String commandId, @Nullable ReadableArray args) {
                if ("focus".equals(commandId) || "focusTextInput".equals(commandId)) {
                    Selection.removeSelection(reactEditText.getText());
                }
                super.receiveCommand(reactEditText, commandId, args);
            }
        });
    }
```

**Comment by FrenchMajesty** [comment]
Any solutions for iOS?

I'm working on building a note-taking app. 80% of the UI screen is a `TextInput` that has user-written content. When I attempt to scroll through the notes, it forces a focus even though I don't necessarily want that.

**Comment by axq** [comment]
Not seeing this behavior on Android 2.10.8 anymore.  Opening a note shows the top, pressing the edit button still shows the top, tapping in the note places the cursor at the tap and brings up the keyboard.  Scrolling works reasonably well, too.  This is a huge usability improvement for Android.
