### ISSUE TITLE
Strange Behavior on Modal (Only in the ios)

### ISSUE THREAD

**Issue by pedrohcdo** [facebook/react-native#29929]
I noticed an error in Modal, the modal simply disappears a few times, the error only occurs if the "transparent" attribute is set to true. In the emulator it is easier to see it happen. 
I am using the latest version of React Native: 0.63.2

## Steps To Reproduce
1. Create an simple modal like (It is important that it is always visible and transparent):
```
<Modal
        transparent={true}
        visible={true}
      >
            <View style={{ flex: 1 }}> 
                <Text>I am the modal content!</Text> 
            </View>
</Modal>
```

2. Install in the ios emulator, check if you started with the modal open, now save the file where the modal is to cause an update in the app. Keep saving the file to force the app to update, in my emulator the Modal is disappearing and reappearing, with each save I give it disappears and in the next save it reappears.

## Expected Results
The expected results are that it will never be "gone". When I change the "transparent" attribute to "false", the error goes away.

**Comment by wilkuintheair** [comment]
@pedrohcdo The same thing happens to me, but slightly different scenario.
In my case it doesn't mind if the modal is transparent or not. It happens all the time when I just closed previous modal.
So it goes like this:
1. I have 2 modals in my render function, one of them is invisible.
2. When I close the first one it gets invisible, the second is now visible.
3. The expected behavior is that the second modal appears, but it's not.

When I'll have some more time I'll try to make some repro project.

**Comment by pedrohcdo** [comment]
> @pedrohcdo The same thing happens to me, but slightly different scenario.
> In my case it doesn't mind if the modal is transparent or not. It happens all the time when I just closed previous modal.
> So it goes like this:
> 
> 1. I have 2 modals in my render function, one of them is invisible.
> 2. When I close the first one it gets invisible, the second is now visible.
> 3. The expected behavior is that the second modal appears, but it's not.
> 
> When I'll have some more time I'll try to make some repro project.

Try the @miotplugin answer, 
Change this file React/Views/RCTModalHostViewManager.m  with this commit https://github.com/facebook/react-native/pull/29953/commits/47fd3489db3086d560209bd78641b45d74194200

**Comment by preflower** [comment]
> @pedrohcdo The same thing happens to me, but slightly different scenario.
> In my case it doesn't mind if the modal is transparent or not. It happens all the time when I just closed previous modal.
> So it goes like this:
> 
> 1. I have 2 modals in my render function, one of them is invisible.
> 2. When I close the first one it gets invisible, the second is now visible.
> 3. The expected behavior is that the second modal appears, but it's not.
> 
> When I'll have some more time I'll try to make some repro project.

i have the same error; but in my case, 2nd modal not appear if 2 modals set transparent, and if i set `transparent=false` is work;  and if i evoke 2nd modal use setTimeout(timeout = 0) is work...
is there any solution?

**Comment by iamrohitagg** [comment]
The same error occurs for me as well on iOS. The `Modal` is not visible if I have set `transparent` to `true`.
1. My first Modal is set to true and then to false, if any text is clicked
2. Second Modal is set to true when the first one is invisible.
Also the error occurs frequently for me. Any solution for this?

**Comment by iamrohitagg** [comment]
For me the this error was caused because i was having one modal visible and I was making another modal visible without closing the one.
