### ISSUE TITLE
Add es7.classProperties to Babel whitelist

### ISSUE THREAD

**Issue by idibidiart** [facebook/react-native#2992]
Need to be able to use fat arrow functions as class properties so it will auto-bind 
```
class MyComponent extends React.Component {  
  
 constructor(props) { ... }

  // this currently throws an Unknown token error 
  handler = (e) => { this.setState({blah: true}) }

  render() {
    return <TouchableHighlight onPress={this.handler}><Text>something</Text></TouchableHighlight>;
  }
}
```
// I find it silly to have to do this.handler = this.handler.bind(this) in the constructor ...

**Comment by ide** [comment]
We've been using this a ton along with decorators and it's quite good so far.

**Comment by idibidiart** [comment]
Hi, 

I just googled and come across this: 

https://www.npmjs.com/package/autobind-decorator 

I feel that using an @autobind decorator for every handler in a class is akin to a workaround, and I'm not sure why it's needed when fat arrow functions have lexical `this` scoping.

**Comment by ide** [comment]
Syntatically it's simpler when you can just write your whole class like this:

```js
class X extends React.Component {
  render() {}

  componentDidMount() {}

  @autobind
  _handlePress(event) {}
}
```

**Comment by idibidiart** [comment]
Hmm. You do have a point on the syntax, but in terms of the semantics I'd like to make use of the lexical `this` scoping in arrow functions because then it's obvious what `this` is without having to know what @autobind is doing.  

Anyways, it's probably subjective.

I think getting the most JS advances (anything that is not likely to change in syntax or semantics) with React Native out of the box would be really nice for those just getting into it. I just learned about .babelrc (there seems to be an issue with the packager cache when updating .babelrc but that's not a big deal I guess) and I'm just googling now to see where I should put my .babelrc. I guess in root folder of the project?   

Here is what I plan to put in there:

```
{
  "retainLines": true,
  "compact": true,
  "comments": false,
  "whitelist": [
    "es6.constants",
    "es6.modules",
    "es7.decorators",
    // default
    "es6.arrowFunctions",
    "es6.blockScoping",
    "es6.constants",
    "es6.classes",
    "es6.destructuring",
    "es6.parameters",
    "es6.properties.computed",
    "es6.properties.shorthand",
    "es6.spread",
    "es6.templateLiterals",
    "es7.asyncFunctions",
    "es7.trailingFunctionCommas",
    "es7.objectRestSpread",
    "es7.classProperties",
    "flow",
    "react",
    "regenerator"
  ],
  "sourceMaps": false
}
``` 

Maybe someone could tag this issue as Enhancement or feel free to close it. 

Thanks for sharing your view on syntax coherence.

**Comment by ide** [comment]
Yeah in the root of your project works. You might need to clear out the transform cache in `$TMPDIR/react-*` too. Babel will compose settings so you only need a handful of options. This is what I use:

```
{
  "whitelist": [
    "es6.constants",
    "es6.modules",
    "es7.classProperties",
    "es7.decorators",
    "es7.doExpressions",
  ]
}
```

**Comment by idibidiart** [comment]
Awesome.
