### ISSUE TITLE
Local images are not visible

### ISSUE THREAD

**Issue by Estebank94** [facebook/react-native#29924]
## Description

Hello,

I am having trouble displaying local images. They suddenly stopped displaying. Images from an URI still display correctly.

## React Native version:

System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
    Memory: 839.69 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.1 - /usr/local/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.7, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 24, 27, 28, 29
      Build Tools: 23.0.1, 25.0.0, 25.0.1, 25.0.2, 26.0.1, 26.0.2, 26.0.3, 28.0.2, 28.0.3, 29.0.1
      System Images: android-23 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 11.7/11E801a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    create-react-native-app: 1.0.0
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
    react-native-rename: 2.4.1

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Add an image to your assets folder
2. Import it
3. Try to display it

## Expected Results
The image should appear

## Code and Screenshots:

I have the following structure:

<img width="259" alt="Screen Shot 2020-09-10 at 16 30 28" src="https://user-images.githubusercontent.com/5116089/92791846-6a6cc500-f383-11ea-9b21-279eb48a4491.png">

And here is the code I use, I am omitting the parts that are not related to the image:

```
import React from 'react';
import {
  Image,
  ...
} from 'react-native';
const image = require('../../assets/images/home-1.jpg');
...

<SafeAreaView style={[styles.container, {margin: 0}]}>
        <Image source={image} style={styles.image} />
        <Animatable.View ref={this.view} style={styles.content}>
...

const styles = StyleSheet.create({
image: {
    backgroundColor: 'red',
    width: 300,
    height: 300,
  },
...
```

But the image does not display:

![DQzsL](https://user-images.githubusercontent.com/5116089/92791955-81abb280-f383-11ea-89ff-bcfc5083d44e.jpg)

**Comment by Lester016** [comment]
Do you have a running example for this using expo ?

**Comment by Estebank94** [comment]
No, I am not using Expo

**Comment by limerence819** [comment]
same issue！

**Comment by braincore** [comment]
Same. Also not using Expo. I suspect it may coincide with an update to XCode as I noticed the issue soon after restarting XCode.

**Comment by Estebank94** [comment]
Now that you mention it, I also updated XCode...

**Comment by braincore** [comment]
The issue is also being tracked here: https://github.com/facebook/react-native/issues/29968

The cited solution resolved the issue for me: https://github.com/facebook/react-native/issues/29279#issuecomment-658244428

**Comment by akinlekan28** [comment]
https://stackoverflow.com/questions/47035899/how-come-my-image-is-not-showing-react-native/64495360#64495360

That stackoverflow link solved it for me.
