### ISSUE TITLE
Uncaught crash in Android Env

### ISSUE THREAD

**Issue by mofmn** [facebook/react-native#29928]
While removing elements of an unnecessary framework i didn't want, i was accidentally left with some View elements that contained a flex boolean like so  `<View flex />`

This was fine on iOS, no error thrown, app continued to function fine, so i continued to test using an iOS VM and when i returned to test android i had moved on a bit, and this causes an immediately fatal crash to the app, so quickly that i had to screen record to read the error and understand why the crash was happening, there was no useful stack trace so i had to git bisect and hunt it down. If i was testing in Android immediately/regularly i admit the issue would have been easier to deal with, but it strikes me that if such a simple mistake requires a screen recording to see the error theres an issues. 
This is on React-native 0.63.2

The expected result is a sane error catch that gives you more than 50 mS to read it

**Comment by mofmn** [comment]
React-native info output :

System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 284.57 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.16.2 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  Languages:
    Java: 14.0.2 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by mofmn** [comment]
Oh, and i forgot to add the screenshot of the actual error. As i say this is taken from a video.
<img width="431" alt="Screenshot 2020-09-11 at 3 53 45 PM" src="https://user-images.githubusercontent.com/9949335/92878401-07446680-f447-11ea-9a23-d4fe0ffcd68e.png">

**Comment by safaiyeh** [comment]
Hi @mofmn thanks for the issue. https://reactnative.dev/docs/layout-props#flex flex requires a number, it is not a boolean value.

Closing as this is not an issue with the docs or core

**Comment by mofmn** [comment]
With all due respect, did you not read the issue?
