### ISSUE TITLE
use_native_modules!  is  error !

### ISSUE THREAD

**Issue by zxymgl** [facebook/react-native#29927]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
hi ! friends,
    My project  poding installed is  error !  
  this is  info .
[!] Invalid `Podfile` file: [!] /usr/local/bin/node -e try {console.log(require('@react-native-community/cli').bin);} catch (e) {console.log(require('react-native/cli').bin);}

internal/modules/cjs/loader.js:985
  throw err;
  ^

Error: Cannot find module 'react-native/cli'
Require stack:
- /Users/zhouxian/Desktop/TestDemoRN/[eval]
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at [eval]:1:87
    at Script.runInThisContext (vm.js:120:20)
    at Object.runInThisContext (vm.js:311:38)
    at Object.<anonymous> ([eval]-wrapper:10:26)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at evalScript (internal/process/execution.js:94:25) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/zhouxian/Desktop/TestDemoRN/[eval]' ]

This is my project directory ！ 
![image](https://user-images.githubusercontent.com/10022573/92846354-95562800-f41a-11ea-8342-e8e5166cf579.png)
this is my package.json 
{
    "name": "TestDemoRN",
    "version": "0.0.1",
    "private": true,
    "scripts": {
        "android": "react-native run-android",
        "ios": "react-native run-ios",
        "start": "react-native start",
        "test": "jest",
        "lint": "eslint ."
    },
    "dependencies": {
        "react": "16.13.1",
        "react-native": "0.63.2"
    },
    "devDependencies": {
        "@babel/core": "^7.11.6",
        "@babel/runtime": "^7.11.2",
        "@react-native-community/eslint-config": "^2.0.0",
        "babel-jest": "^26.3.0",
        "eslint": "^7.8.1",
        "jest": "^26.4.2",
        "metro-react-native-babel-preset": "^0.63.0",
        "react-test-renderer": "16.13.1"
    },
    "jest": {
        "preset": "react-native"
    }
}

this is my podfile !
# Uncomment the next line to define a global platform for your project
require_relative 'RN/node_modules/react-native/scripts/react_native_pods'
require_relative 'RN/node_modules/@react-native-community/cli-platform-ios/native_modules'
 platform :ios, '10.0'

target 'TestDemoRN' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  config = use_native_modules!
#  use_react_native!(:path => config[:reactNativePath])
  
  
  # Pods for TestDemoRN

  target 'TestDemoRNTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestDemoRNUITests' do
    # Pods for testing
  end

end

when I pod install , is  reported error !

**Comment by zxymgl** [comment]
this is environment !
 System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 158.47 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.1 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 22, 23, 24, 25, 26, 27, 28, 29
      Build Tools: 23.0.1, 23.0.2, 25.0.2, 26.0.2, 27.0.2, 27.0.3, 28.0.3
      System Images: android-23 | Intel x86 Atom, android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64, android-26 | Google Play Intel x86 Atom, android-27 | Google APIs Intel x86 Atom
      Android NDK: 20.0.5594570
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_91 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
    react-native-macos: Not Found
  npmGlobalPackages:

**Comment by safaiyeh** [comment]
Hi @zxymgl please use the issue template. You can either edit this one or close this and open a new one. Thanks!

**Comment by ed1son67** [comment]
same error

**Comment by lengqingfeng** [comment]
the same error  how to fix this error ？？

**Comment by guoliang1206** [comment]
same error, use_frameworks! makes project build failed
https://github.com/prscX/react-native-photo-editor/issues/160
