### ISSUE TITLE
HybridData.java:67 HybridData$Destructor holds ~30+% of app memory on Android

### ISSUE THREAD

**Issue by evelant** [facebook/react-native#29923]
## Description
HybridData.java:67 HybridData$Destructor -- doing a full heap dump in Android Studio profiler reveals that this destructor class is holding more memory than anything else in my app. I'm not sure if this is expected but it certainly seems suspicious. This is a project running ReactAndroid from source identical to the 0.63.2 tag but for one unrelated line change to work around a bug.

![image](https://user-images.githubusercontent.com/858965/92779961-80bd5580-f370-11ea-9160-aa014f949c98.png)

## React Native version:
```
System:
    OS: Windows 10 10.0.20206
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
    Memory: 36.13 GB / 63.93 GB
  Binaries:
    Node: 12.18.3 - ~\AppData\Local\Temp\yarn--1599761928638-0.7848026464037234\node.CMD
    Yarn: 1.22.4 - ~\AppData\Local\Temp\yarn--1599761928638-0.7848026464037234\yarn.CMD
    npm: 6.14.6 - C:\dev\tools\nodejs\npm.CMD
    Watchman: 4.9.4 - C:\dev\tools\watchman\watchman.EXE
  SDKs:
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.1, 30.0.2
      System Images: android-24 | Google Play Intel x86 Atom, android-25 | Google APIs ARM EABI v7a, android-25 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom_64, andro
id-R | Google Play Intel x86 Atom_64
      Android NDK: 21.0.6113669
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.6.30225.117 (Visual Studio Community 2019)
  Languages:
    Java: 12.0.2
    Python: 3.8.4
  npmPackages:
    @react-native-community/cli: ^4.10.1 => 4.13.0
    react: 16.13.1 => 16.13.1
    react-native: github:AndrewMorsillo/react-native#0.63-stable-opqueue-npe-fix => 0.63.2
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Take a full heap dump using Android Studio profiler of release build with `debuggable true` in app/build.gradle
2. Observe lots of memory being held by `HybridData$Destructor` at HybridData.java:67

## Expected Results
Objects holding memory should be recognizable. Others in this heap dump are as expected, bitmaps, strings, etc.

## Snack, code example, screenshot, or link to a repository:
Working on a minimal reproduction

**Comment by Edwardp17** [comment]
@AndrewMorsillo I'm seeing this as well and believe it may be significantly affecting performance in my android application - by any chance were you able to find out what was causing this?

**Comment by AndrewMorsillo** [comment]
I haven’t found out anything else, sorry. I don’t have the Android expertise or the time to dig in further at the moment.

**Comment by JoaoBGusmao** [comment]
Also an issue for me. HybridData$Destructor represents 80% of my entire heap dump

**Comment by mym0404** [comment]
What the hell is it

**Comment by Subv** [comment]
I saw this strange behavior on my app using RN 0.66.4 too, but I believe it is an artifact of how Android Studio calculates the Retained Size.

![image](https://user-images.githubusercontent.com/357072/148462381-76fb660b-4b76-4ede-bfaa-50359c1d9499.png)

HybridData$Destructor seems to be a linked list that holds a `next` pointer, and each instance only has a shallow size of 40 bytes, notice how the Retained Size of the next pointer is the same as the current instance's retained size - 40 bytes. I believe Android Studio is just (incorrectly) adding up all the Retained Sizes and giving us a very frightening false positive.

See https://stackoverflow.com/questions/57027001/why-is-the-retained-heap-size-of-the-finalizerreference-class-so-large-in-the-m for a similar problem
