### ISSUE TITLE
ScrollView is not redrawn if nested children is updated

### ISSUE THREAD

**Issue by likern** [facebook/react-native#29934]
## Description

If nested children elements of `ScrollView` are updated they are not shown - `ScrollView` is not redrawn.
When I reach the end of current `ScrollView` I add another (additional) elements to `children` (grouped by `Page` component).

Additional `Page` component is rendered, while it's children not.

Related issue software-mansion/react-native-reanimated#1216
### Screenshots

<table>
  <tr>
   <td><img src="https://user-images.githubusercontent.com/842306/92778780-280aae80-f3aa-11ea-83aa-124f8d071500.jpg" width=270 height=480></td>
    <td><img src="https://user-images.githubusercontent.com/842306/92778775-26d98180-f3aa-11ea-961f-defdaa969a42.jpg" width=270 height=480></td>
  </tr>
 </table>

We see that additional `View` was added and contains `Text` components as children. But it's not rendered on the screen.
<table>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/842306/92780508-f266c500-f3ab-11ea-8bff-c40157ceb4c9.png" width=270></td>
   <td><img src="https://user-images.githubusercontent.com/842306/92780501-f1ce2e80-f3ab-11ea-8117-425f3f138d3c.png" width=270></td>
  </tr>
 </table>

## Steps To Reproduce

Swipe down until additional page is added.

### Expected behavior

Children of all pages should be rendered correctly.

### Actual behavior

Only children of first page are rendered, while for other pages I see empty views.

## Snack or minimal code example

Here is a reproduction code https://gist.github.com/likern/466bd17a861a7a3839fabf5b0c6b1e30

## Package versions

- React: 16.11.0
- React Native: 0.62.2

## React Native version:
Run `react-native info` in your terminal and copy the results here.
```bash
[me@localhost Feeve]$ npx react-native info
info Fetching system and libraries information...
System:
    OS: Linux 5.8 Fedora 32 (Workstation Edition) 32 (Workstation Edition)
    CPU: (8) x64 Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
    Memory: 454.33 MB / 15.56 GB
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.0.0 - ~/.nvm/versions/node/v14.0.0/bin/node
    Yarn: 1.22.0 - ~/.local/opt/node-v10.19.0-linux-x64/bin/yarn
    npm: 6.14.5 - ~/Breeffy/Feeve/node_modules/.bin/npm
    Watchman: 4.9.0 - /usr/bin/watchman
  SDKs:
    Android SDK:
      Android NDK: 21.3.6528147
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 11.0.8 - /usr/bin/javac
    Python: 3.8.5 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by chrisglein** [comment]
This sounds familiar to a ScrollView issue where added items weren't seen. It might be [one of these](https://github.com/facebook/react-native/labels/Component%3A%20ScrollView) but I couldn't find it with a quick pass. You should do a pass over those to see if you see something similar.

Appreciate the gist. I tried dumping that in a Snack so I could quickly try it out, but it didn't plug in as easily as I would have liked ([Snack here](https://snack.expo.io/@chrisglein/repro29934)). If you can get this running in a sharable Snack that will help.
