### ISSUE TITLE
cant get expected output while re rendring

### ISSUE THREAD

**Issue by mauryashubhu** [facebook/react-native#29935]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
re rendring problem in functional components while uisng hooks

## React Native version:
Run `react-native info` in your terminal and copy the results here.
.63.2

## Steps To Reproduce

1.
![step1](https://user-images.githubusercontent.com/66897215/92926279-6612db80-f459-11ea-8c3c-5619cf86b8be.png)
![step2](https://user-images.githubusercontent.com/66897215/92926290-67dc9f00-f459-11ea-99f7-b517393e34be.png)

2.

## Expected Results
Describe what you expected to happen.

wanted to get item parameters in modalScreen function but i dont know why the whole js file re rendernig twice and in second rendering  i didn't get the result of model items in the last rendering.

![console screen](https://user-images.githubusercontent.com/66897215/92926771-2c8ea000-f45a-11ea-8d8a-2706aed97a06.png)

## Snack, code example, screenshot, or link to a repository:
Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow

.com/help/mcve

**Comment by hamdikahloun** [comment]
Hi @mauryashubhu 
Why you don't Remove item param from modal and add new hooks

```
const [item, setModalItem] = useState({});
setModalItem(item);
setModalVisible(true);
```

**Comment by safaiyeh** [comment]
Hi @mauryashubhu this is better suited for StackOverflow. I would recommend making a post there, thank you.

**Comment by mauryashubhu** [comment]
Ok👍
