### ISSUE TITLE
npx react-native start not working -- unrecognized command

### ISSUE THREAD

**Issue by harryasimon** [facebook/react-native#29938]
## Description
Recently bought a new macbook pro. Installing react native. 
running the command: npx react-native start
getting the error: error Unrecognized command "start".

## React Native version:
4.13.0

**Comment by safaiyeh** [comment]
CLI related issues should go to https://github.com/react-native-community/cli

**Comment by intelliot** [comment]
This error occurs if you're not in the root directory of a react native app. So if your app is called "App" you may need to do `cd App` before running `npx react-native start`.

```
% npx react-native start
error Unrecognized command "start".
info Run "react-native --help" to see a list of all available commands.
```

**Comment by donlevans29** [comment]
@intelliot  is correct. I was starting a project and notice that I was not in the root folder after I got into the root folder by selecting to open new folder then navigate to the folder named when I ran the command to start the project.
