### ISSUE TITLE
Android scrollView content flickering on scroll.

### ISSUE THREAD

**Issue by ACHP** [facebook/react-native#29932]
There is a bug on some android devices ( Xiaomi Mi9T, OnePlus 7 pro and maybe more) when scrolling in a *Scrollview*, the content randomly and partially disappears.
This bug seems to appear only when the "fullscreen mode" is enabled ( no navigation bar at the bottom, only gestures to navigate between screens and app).

<table>
     <thead>
            <tr>
                <th>The bug</th>
                <th>Expected behavior</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td><img width="320" src="https://raw.githubusercontent.com/ACHP/ReactNative-android-flickering-issue/master/gifs/initial%20bug.gif"/></td>
                <td>
<img width="320" src="https://raw.githubusercontent.com/ACHP/ReactNative-android-flickering-issue/master/gifs/expected%20behavior.gif"/>
</td>
            </tr>
        </tbody>
</table>

Note the "cheated with `#fffffe`" mention, there is no bug when the `header` use a different backgroundColor than the `wrapper`around it. Here, the backgroundColor of the wrapper was `#ffffff` so I used `#fffffe`to bypass the bug.

## Description
It seems to be related to the presence of another screen behind the visible one, so, this happens when using react-navigation (v4 in my case), but for the example I was able to reproduce it by simply using absolute positioning.

<img width="320" src="https://raw.githubusercontent.com/ACHP/ReactNative-android-flickering-issue/master/gifs/app.png"/>

The "HomeScreen" is a simple *View* with a translucent *StatusBar* and an *Image* component.
The "Buggy" Screen is a View containing another simple *View* (header) and a *ScrollView* (content)
```jsx
const HomeScreen = () => {
  return (
    <>
      <StatusBar
        backgroundColor="transparent"
        barStyle="dark-content"
        translucent={true}
      />
      <View style={{flex: 1}}>
        <View style={homeScreenStylesheet.imageWrapper}>
          <Image
            style={homeScreenStylesheet.image}
            source={{
              uri:
                'https://hatrabbits.com/wp-content/uploads/2017/01/random.jpg',
            }}
          />
        </View>
      </View>
    </>
  );
};
```

```jsx
const BuggyScreen = (_props) => {
  return (
    <View style={buggedScreenStylesheet.wrapper}>
      <View style={buggedScreenStylesheet.header} />
      <ScrollView style={buggedScreenStylesheet.content}>
        <Text>{text}</Text>
      </ScrollView>
    </View>
  );
};
```

**Full code is located [here](https://github.com/ACHP/ReactNative-android-flickering-issue/blob/master/App.js)**

The bug seems to be caused by the use of multiple style attribute, that makes it "simple" to bypass because we have a lot a parameters we can tweak to avoid it, but also hard to reproduce and understand.
I have annotated all the style props that seems to have an impact on the bug to distinguish them from the props that are here for UI purposes.

In the *HomeScreen* the importants props are : 
```javascript
const homeScreenStylesheet = StyleSheet.create({
  imageWrapper: {
    overflow: 'hidden', // bug
    borderRadius: 1, // bug
  },
  image: {
    width: 300,
    height: 300,
  },
});
```

In the *BuggyScreen* the importants props are : 
```javascript
const buggedScreenStylesheet = StyleSheet.create({
  wrapper: {
    flex: 1,
    backgroundColor: 'white', // bug if same as `header` background.
  },
  header: {
    position: 'relative', // bug if present
    shadowOpacity: 0.2, // bug
    width: 500, // bug if greater than x ( x = 93 in my case ...)
    backgroundColor: 'white', // bug if same as `wrapper` background.
    zIndex: 2, // bug if present
    height: 100,
    justifyContent: 'center',
  },
  content: {
    flex: 1,
    backgroundColor: 'red',
  },
});
```

I think this is a react native bug that may be caused by some kind of system optimisation.
*It appears on really strange circumstance.*
When headers background color is the same as the wrapper for example ...
<table>
     <thead>
            <tr>
                <th>Header with different color from `wrapper`</th>
                <th>with same color</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td><img width="320" src="https://raw.githubusercontent.com/ACHP/ReactNative-android-flickering-issue/master/gifs/red-green-colors.gif"/></td>
                <td>Same bug as mentioned before</td>
            </tr>
        </tbody>
</table>

Or depending on the header width ...
<table>
     <thead>
            <tr>
                <th>Header width < 93</th>
                <th>Header width > 93</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td><img width="320" src="https://raw.githubusercontent.com/ACHP/ReactNative-android-flickering-issue/master/gifs/width%2092.gif"/></td>
                <td>
                    <img width="320" src="https://raw.githubusercontent.com/ACHP/ReactNative-android-flickering-issue/master/gifs/width%2094.gif"/>
                    <p>Note how partially the bug appears on the screen</p>
                </td>
            </tr>
        </tbody>
</table>

I have more example in my test repo. (https://github.com/ACHP/ReactNative-android-flickering-issue)

## Layout inspection ##
Using the AndroidStudio layout inspector tools, we can't find any 'View' that would create a kind of mask above the screen ...

<img width="320" src="https://raw.githubusercontent.com/ACHP/ReactNative-android-flickering-issue/master/gifs/LayoutInspector.png"/> 

The Layout inspection file can be downloaded [Here](https://github.com/ACHP/ReactNative-android-flickering-issue/raw/master/gifs/com.bugrnnavflickering_2020.09.11_12.42.li) :

## React Native version:
```
System:
    OS: macOS 10.15.5
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 22.03 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.5.0 - ~/.nvm/versions/node/v14.5.0/bin/node
    Yarn: 1.21.1 - ~/.yarn/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v14.5.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.4 - /Users/alexischappron/.rvm/rubies/ruby-2.6.3/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  Languages:
    Java: 10.0.2 - /usr/bin/javac
    Python: 3.8.2 - /Users/alexischappron/.pyenv/shims/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.2 => 0.63.2
  npmGlobalPackages:
    *react-native*: Not Found
```

## Expected Results
The scrollView should scroll without flickering

## Snack, code example, screenshot, or link to a repository:
As it is really hard to reproduce, I have created a repository with the necessary code.
https://github.com/ACHP/ReactNative-android-flickering-issue

**Comment by ACHP** [comment]
**Update** :  I updated my xiaomi device to use the latest MIUI version (12) and the bug disapeared ...

So I unlocked it and downgrade it to MIUI 11 to be sure and here are the results :
![miuicomparison](https://user-images.githubusercontent.com/9294168/93381114-74e5fd80-f860-11ea-916c-f5077d21c154.gif)

**Comment by Ferb2012** [comment]
Just delete `overflow: 'hidden'` it will be ok, and I don't know why ...

**Comment by ShaoGongBra** [comment]
Is there no good solution to this problem so far? On most models of oppo, Huawei and vivo, there is still this problem

**Comment by csRajeshkumartl** [comment]
onScroll={(e) => {
        const {y} = e?.nativeEvent?.contentOffset;
        //console.log(y, x);
        if (Platform.OS === 'ios') {
          if (y > 0) {
            setShowHeader(false);
          } else {
            setShowHeader(true);
          }
        } else {
          if (y <= 0) {
            setShowHeader(true);
          }
        }
      }}
      onScrollEndDrag={(e) => {
        const {y} = e?.nativeEvent?.contentOffset;
        if (Platform.OS === 'android') {
          if (y > 0) {
            setShowHeader(false);
          }
        }
      }}
      
      This may fix your issue. For me the above work around fix the issue. Make use of it.

**Comment by andreshsingh** [comment]
this issue still persists, could we please reopen it ?
