### ISSUE TITLE
Linking custom fonts failed in react-native v0.61.2

### ISSUE THREAD

**Issue by MahmudHasanMenon** [facebook/react-native#29944]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
recently i have upgraded my react-native version from 0.61.0 to 0.61.2 . After that when i add custom font to assets and run
`npx react-native link` it says linking assets failed.

![image](https://user-images.githubusercontent.com/29507500/93093898-0cade500-f6c3-11ea-8fd6-dee75025fc40.png)

## React Native version:

System:
    OS: Windows 10 10.0.18362
    CPU: (4) x64 Intel(R) Core(TM) i5-4590T CPU @ 2.00GHz
    Memory: 4.36 GB / 15.89 GB
  Binaries:
    Node: 12.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
    Watchman: 20200816.222424.0 - C:\Users\menon\AppData\Local\watchman\watchman.EXE
  IDEs:
    Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5900203
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.2 => 0.61.2 
  npmGlobalPackages:
    react-native-cli: 2.0.1

**Comment by safaiyeh** [comment]
Hi @MahmudHasanMenon  for upgrade related issues make sure you use the upgrade support repro! Thanks
