### ISSUE TITLE
Packager doesn't seem to handle "export Thing from './Thing'"

### ISSUE THREAD

**Issue by nevir** [facebook/react-native#2994]
When doing the following:
```js
export Thing from './Thing';
```

You end up with an error like:
```
Requiring unknown module "./Thing". If you are sure the module is there, try restarting the packager."
```

It can be worked around via:
```js
import Thing from './Thing';
export { Thing };
```

**Comment by skevy** [comment]
There are PR's open for this here: https://github.com/facebook/react-native/pull/1940 and here: https://github.com/facebook/react-native/pull/1975

**Comment by nevir** [comment]
Ah, awesome!

**Comment by skevy** [comment]
This can be closed now as this is now merged: https://github.com/facebook/react-native/pull/3465
