### ISSUE TITLE
main.jsbundle doesn't exist in react-native app

### ISSUE THREAD

**Issue by khalil9615** [facebook/react-native#29945]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
CpResource /Users/apple/Desktop/SiceMeFullBuild-28456-react-native/packages/mobile/ios/main.jsbundle /Users/apple/Library/Developer/Xcode/DerivedData/SiceMeFullBuild-gifasvzewccpcmciihgioxqluwej/Build/Products/Debug-iphonesimulator/SiceMeFullBuild.app/main.jsbundle (in target 'SiceMeFullBuild' from project 'SiceMeFullBuild')
    cd /Users/apple/Desktop/SiceMeFullBuild-28456-react-native/packages/mobile/ios
    builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -resolve-src-symlinks /Users/apple/Desktop/SiceMeFullBuild-28456-react-native/packages/mobile/ios/main.jsbundle /Users/apple/Library/Developer/Xcode/DerivedData/SiceMeFullBuild-gifasvzewccpcmciihgioxqluwej/Build/Products/Debug-iphonesimulator/SiceMeFullBuild.app

error: /Users/apple/Desktop/SiceMeFullBuild-28456-react-native/packages/mobile/ios/main.jsbundle: No such file or directory (in target 'SiceMeFullBuild' from project 'SiceMeFullBuild')
## React Native version:
Run `react-native info` in your terminal and copy the results here.

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.yarn run compile && yarn run ios
2.xcode-workspace run
![Screenshot 2020-09-14 at 11 27 22 PM](https://user-images.githubusercontent.com/71267096/93121027-dd5aa080-f6e1-11ea-81b1-7d91ca4fcc19.png)

## Expected Results
Describe what you expected to happen.
xocde-12.4
react-native-61.3
typescript mention
Android-studio-4.0.1
yarn-1.3.2
My project structure is different, so the script don't have start here i run a command :yarn run compile && run ios for ios and for android yarn run compile run android. I have tried all github and stackover flow even i run on various system but unable to resolve this. So , please fix this issue.

**Comment by khalil9615** [comment]
It's a typescript based native as well as JS project but unable to run either one of the project. So, I am waiting for your feedback.

**Comment by safaiyeh** [comment]
Hi @khalil9615 I'm going to recommend asking this question on StackOverflow. This looks like a configuration issue. If you can reproduce this on a clean fresh template, feel free to create a new issue.
