### ISSUE TITLE
SyntaxError: use Typescript(4.1.0) Template literal types cannot have any substitution

### ISSUE THREAD

**Issue by anthinkingcoder** [facebook/react-native#29943]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Please provide a clear and concise description of what the bug is. Include screenshots if needed.
Please test using the latest React Native release to make sure your issue has not already been fixed: https://reactnative.dev/docs/upgrading.html

## React Native version:
Run `react-native info` in your terminal and copy the results here.

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. use typescript 4.1.0-dev.20200831
2. use typescript literal types (https://github.com/microsoft/TypeScript/pull/40336)

## Expected Results
Describe what you expected to happen.
![image](https://user-images.githubusercontent.com/17498633/93070862-fcd9d500-f6b1-11ea-8fa1-aa6b7cae47e0.png)

## Snack, code example, screenshot, or link to a repository:
Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by nandorojo** [comment]
I'm getting the same error:

```tsx
type Vertical = 'top' | 'bottom' | 'center'
type Horizontal = 'left' | 'right' | 'center'
type From = `${Vertical}-${Horizontal}`
```

<img width="1024" alt="Screen Shot 2020-10-29 at 3 58 52 PM" src="https://user-images.githubusercontent.com/13172299/97626002-aa553d80-19ff-11eb-9535-2c7264cff5a2.png">

**Comment by gusgard** [comment]
@anthinkingcoder did you figure out how to use TS 4.1 (Template literal types) on React Native?

**Comment by nandorojo** [comment]
I didn't come back to this specific issue, but have you tried updating to the latest beta of TypeScript?

**Comment by gusgard** [comment]
Yes, I'm using TS 4.1.2

**Comment by Ghanashri-m** [comment]
@nandorojo I'm getting the same error. Why was the issue closed?? Can anyone please help me with a solution??

**Comment by MohammedFaragallah** [comment]
same issue, any suggestions?

**Comment by nandorojo** [comment]
I stopped using template literals for now.

**Comment by MohammedFaragallah** [comment]
@nandorojo thank you I did the same and everything works fine now, I'll investigate more and hopefully find a solution.

**Comment by ryanjwessel** [comment]
I ran into the same issue, and we were able to fix it by upgrading our versions of [Babel to 7.12](https://babeljs.io/blog/2020/10/15/7.12.0#:~:text=7.12.-,0%20Released%3A%20TypeScript%204.1%2C%20strings%20as%20import%2Fexport,names%2C%20and%20class%20static%20blocks&text=We%20just%20published%20a%20new,key%20remapping%20in%20mapped%20types.) and [Prettier to 2.2](https://prettier.io/blog/2020/11/20/2.2.0.html).

**Comment by wcandillon** [comment]
For an expo project, I was able to use the 4.1 syntax using:

```
  "resolutions": {
    "@babel/core": "7.1.2"
  },
```

in package.json

**Comment by wcandillon** [comment]
For expo project see https://github.com/expo/expo/issues/11307#issuecomment-765890458

**Comment by wcandillon** [comment]
For expo projects see: https://github.com/expo/expo/issues/11307#issuecomment-765890458

**Comment by hadighattas** [comment]
One solution would be to change the resolution of `@babel/core` to `7.12.0` or later in your `package.json`
Something like this:
```json
"resolutions": {
  "@babel/core": "^7.12.3"
}
```
