### ISSUE TITLE
Cannot use fetch nor axios for file uploads. It gives Network Error even though the request is 200 (OK) ANDROID ONLY

### ISSUE THREAD

**Issue by dlogvin** [facebook/react-native#29947]
## Description
There is a Network Error that appears out from the nowhere when trying to upload an image.

## React Native version:
```
System:
    OS: macOS Mojave 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Memory: 340.52 MB / 8.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 14.5.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.7.5 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 19, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.1
      System Images: android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: 21.3.6528147
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  Languages:
    Java: 12.0.1 - /usr/bin/javac
    Python: 2.7.17 - /Users/user/opt/miniconda2/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.2 => 0.63.2
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```
## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Try to upload a file using axios (or fetch):
```js
async addTask() {
        this.setState({ secondaryLoader: true });
        const token = await AsyncStorage.getItem('access');
        const access = 'Bearer ' + token;
        const data = new FormData()
            data.append('subject_id', this.props.navigation.getParam('id'))
            data.append('name', this.state.title)
            data.append('progress', this.state.progress * 100)
            data.append('description', this.state.description)
            data.append('date', this.state.date)
            if(this.state.image != null){
                data.append('image', {
                    uri: this.state.image,
                    type: 'image/jpeg',
                    name: 'image'
                });
            }

            axios.post('https://mysite.example/api/auth/createTask', data, {
                headers: {
                    'Authorization': access,
                    "Content-Type": "multipart/form-data"
                },
            }).then(res => {
                this.setState({ secondaryLoader: false });
                this.props.navigation.navigate('ViewHW', { id: res.data.id })
            })
    }
```

## Expected Results
For the user to be redirected (`this.props.navigation.navigate('ViewHW', { id: res.data.id })`)

## Snack, code example, screenshot, or link to a repository:
Provided above.

**Needless to say, it is important to mention the following**

My server DOES accept CORS, I already tried commenting the line on `ReactNativeFlipper.java` (`builder.addNetworkInterceptor(new FlipperOkhttpInterceptor(networkFlipperPlugin));`), and I already tried to make a clean build. 

This is a problem that only happens on ANDROID, on iOS it works **_perfectly_**. I'm making use of the form in other parts of the app and by some reason IT WORKS, but on the screen it is located now, by some reason it does not.

**Comment by henbrand** [comment]
Hey! Are you using a debugger? For me the network error only appeared when I had the Network Inspect enabled. When it was off it worked fine. If not here is a similar issue: https://github.com/facebook/react-native/issues/28551

**Comment by dlogvin** [comment]
@henbrand Not using any sort of debugger. The app is affected in production too.

**Comment by safaiyeh** [comment]
Hi @dlogvin sorry you are having this issue. There are multiple work arounds mentioned in the issue @henbrand linked. I would like to keep the discussion in the issue. Closing, please try the solutions there and add your context. Thank you!

**Comment by dlogvin** [comment]
@safaiyeh I already tried everything there. I replied on that thread.

The only possible solution I see is to keep up with Flutter. I find it way too annoying for things like this to happen on react-native. They are essential, you know? I am not the type of person who is allowed to wait for updates to fix issues.

**Comment by safaiyeh** [comment]
Yeah I understand how frustrating it is. I am also trying to bring more attention to it. Hopefully a fix comes in soon

**Comment by safaiyeh** [comment]
cc @TheSavior

**Comment by aemre** [comment]
any update on this?
