### ISSUE TITLE
[Navigator] Separate Android and iOS navigation bar styles

### ISSUE THREAD

**Issue by ide** [facebook/react-native#2995]
Long story short, I want to use the iOS navigation bar styles on Android. Currently NavigatorNavigationBar.js requires NavigatorNavigationBarStyles.{ios,android}.js so the only ways to customize the navigation bar are either to fork react-native and use a single NavigatorNavigationBarStyles.js file, or to copy and paste NavigatorNavigationBar.js and NavigatorNavigationBarStyles.ios.js.

The best non-forking/copy-paste solution I have right now is for NavigatorNavigationBar to have a new prop called `transitionStyles` that defaults to NavigatorNavigationBarStyles. The NavigatorNavigationBarStyles files would be renamed NavigatorNavigationBarStylesIOS.js and NavigatorNavigationBarStylesAndroid.js, and NavigatorNavigationBarStyles.{ios,android}.js would be one-line files that require their respective style file. Then existing code would continue to work with no difference at all, but you could also write:
```js
<Navigator.NavigationBar
  transitionStyles={Navigator.NavigationBar.TransitionStylesIOS}
/>
```

cc @ericvicenti

**Comment by brentvatne** [comment]
:+1: this would also allow for better customization of the NavigationBar

**Comment by ericvicenti** [comment]
I think we should:

1. Move .android files to CustomComponents so that everything is next to eachother
2. Rename modules to be `NavigatorNavigationBarStylesAndroid` and `NavigatorNavigationBarStylesIOS`
3. Export the following from `Navigator.NavigationBar`

**Comment by ide** [comment]
@ericvicenti regarding (1) is this something that needs to happen on the fb side? I'll update my PR if it isn't -- just don't want to break the sync.

**Comment by ericvicenti** [comment]
Sorry, I edited my comment a bit. I assume you're referring to (2)

@vjeux, any thoughts on this? Is it ok if @ide moves the android navigator files to CustomComponents where they belong, and adds the other license to their headers?

**Comment by vjeux** [comment]
Adding files to CustomComponents is okay, it has a more restrictive license. Removing files from CustomComponents is not.

**Comment by ide** [comment]
@ericvicenti Cool -- my PR happened to mostly match your outline. Just needed to move the Android files into CustomComponents. Updated the PR at https://github.com/facebook/react-native/pull/3028.

**Comment by lxsameer** [comment]
Can any one please give me an example of `NavigatorNavigationBarStylesAndroid` ?
