### ISSUE TITLE
Failed prop type: Invaid props.style.key 'border' supplied to 'Image'

### ISSUE THREAD

**Issue by yarin177** [facebook/react-native#29952]
## Description
I'm trying to make a border around the image, and when the user clicks it, It will show the border.
my code is running and working on pc however I get this strange error when running on an Android device.

## React Native version:
0.62.2

my code:
`let stylereg_na = { border: '20px solid black', height: hp('7%'), width: wp('25%')};`
`<Image style={stylereg_na} source={na}/>`

**Comment by kartikey0806** [comment]
import * as React from 'react';
import { Text, View, StyleSheet, Image } from 'react-native';
import Constants from 'expo-constants';

export default class App extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.paragraph}>
          Change code in the editor and watch it change on your phone! .
        </Text>
        <Image source={require('./amazonLogo.jpg')} style={{borderWidth: 3, borderColor:'black', alignSelf:'center'}}/>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    paddingTop: Constants.statusBarHeight,
    backgroundColor: '#ecf0f1',
    padding: 8,
  },
  paragraph: {
    margin: 24,
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
  },
});

**Comment by yarin177** [comment]
> import * as React from 'react';
> import { Text, View, StyleSheet, Image } from 'react-native';
> import Constants from 'expo-constants';
> 
> export default class App extends React.Component {
> render() {
> return (
> 
> 
> Change code in the editor and watch it change on your phone! .
> 
> <Image source={require('./amazonLogo.jpg')} style={{borderWidth: 3, borderColor:'black', alignSelf:'center'}}/>
> 
> );
> }
> }
> 
> const styles = StyleSheet.create({
> container: {
> flex: 1,
> justifyContent: 'center',
> paddingTop: Constants.statusBarHeight,
> backgroundColor: '#ecf0f1',
> padding: 8,
> },
> paragraph: {
> margin: 24,
> fontSize: 18,
> fontWeight: 'bold',
> textAlign: 'center',
> },
> });

**That worked!** But I'm still having _problems_, I'm trying to show the border only when the user clicked the image..
Here's my code:
`const [regNA, setRegNAStatus] = useState(false);`
`let stylereg_na = { borderRadius: 3, height: hp('7%'), width: wp('25%')};`
`  if(regNA)
  {
    stylereg_na = {borderRadius: 3, height: hp('8%'), width: wp('26%')}
  }`
`        <Image style={stylereg_na} source={na} onClick={() => 
        {
          if(regNA)
            setRegNAStatus(false);
          else
          {
            setRegNAStatus(true);
          }
        }
        } />`

the border is not showing when I click the image in the device

**Comment by kartikey0806** [comment]
import React, { Component } from 'react';
import { StyleSheet, View, Image, Button, Platform, TouchableOpacity } from 'react-native';
 
export default class App extends Component{
  constructor(){
    super();
    this.state={
      imageURL : 'https://reactnativecode.com/wp-content/uploads/2017/10/Guitar.jpg',
      style: ({width: 300, height: 300, marginBottom: 20, })
    }
 
  }
 
  Load_New_Image=()=>{
    this.setState({
      style: ({borderWidth: 3, borderColor: 'red', width: 300, height: 300, marginBottom: 20,})
    })
  }
    
    render() {
      return (
        <View style={styles.MainContainer}>
          <TouchableOpacity onPress={this.Load_New_Image}>
          <Image 
            source = {{ uri: this.state.imageURL }}
            style = {this.state.style} />
          </TouchableOpacity>     
        </View>      
      );
    }
   }
    
  const styles = StyleSheet.create({  
   MainContainer :{ 
   justifyContent: 'center',
   alignItems: 'center',
   flex:1,
   paddingTop: (Platform.OS) === 'ios' ? 20 : 0,
   margin: 10 
   },
 
   imageStyle:{
 
    width: 200, 
    height: 300, 
    resizeMode: 'center'
 
   }
    
   });

**Comment by kartikey0806** [comment]
this will work definitely , the border Color will appear on the image when you will touch it .

**Comment by safaiyeh** [comment]
Hi @yarin177 the Image component does not have a `border` property. Check out the Image docs for more image style props: https://reactnative.dev/docs/image-style-props#props
