### ISSUE TITLE
Empty space above and below  🐛

### ISSUE THREAD

**Issue by patrickbattisti** [facebook/react-native#29954]
## Description
The application isn't running in full screen on Xiaomi devices, on other devices it's working as expected.

## React Native version:
targetSdkVersion: 29
react: 16.13.1 => 16.13.1 
react-native: 0.63.2 => 0.63.2

## Example
![Screenshot_2020-09-10-17-18-22-607](https://user-images.githubusercontent.com/35247414/93225193-dc6d5180-f769-11ea-88a6-25689daa4519.jpg)

**Comment by mohamadhamad300** [comment]
please show  the  code
