### ISSUE TITLE
Flatlist not showing all items on v 0.60.3

### ISSUE THREAD

**Issue by valevarela2612** [facebook/react-native#29956]
## Description
Using flatlist on v 0.60.3 is not rendering all items, the data passed to the flatlist has a length of 14 and only 12 are showing. Fixed with a ListFooterComponent with nothing inside

## React Native version:
v 0.60.3

## Steps To Reproduce
Created a simple flatlist passing an array of 14 items and only 12 are rendering.

## Code example:

![image](https://user-images.githubusercontent.com/27986756/93259158-c8c7e800-f775-11ea-91f8-77e69f0c4aa3.png)

**Comment by safaiyeh** [comment]
Hi @valevarela2612 thank you for the issue. v.60 is a bit old could you verify this happens on the lastest RN version. Also provide a Snack or repro of the issue.
