### ISSUE TITLE
Installing CocoaPods dependencies Error

### ISSUE THREAD

**Issue by hongmaoxiao** [facebook/react-native#29957]
```
cd ./app/ios && pod install

Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `Folly` from `../node_modules/react-native/third-party-podspecs/Folly.podspec`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
Downloading dependencies
Installing CocoaAsyncSocket (7.6.4)
Installing CocoaLibEvent (1.0.0)
Installing DoubleConversion (1.1.6)
Installing FBLazyVector (0.63.2)
Installing FBReactNativeSpec (0.63.2)
Installing Flipper (0.41.5)



[!] Error installing Flipper
[!] /usr/bin/git clone https://github.com/facebook/Sonar.git /var/folders/wm/q8vwfp7j57g6qm9s21lhdq7m0000gp/T/d20200916-37728-1u2ixqh --template= --single-branch --depth 1 --branch v0.41.0

Cloning into '/var/folders/wm/q8vwfp7j57g6qm9s21lhdq7m0000gp/T/d20200916-37728-1u2ixqh'...
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
```
## Description
Environment set up fail after retry installing for more than 20 times, every time I get stuck in Installing Flipper.

> IMO,  it seems that the repo name change from **Sonar** to **flipper** and the Podfile did not updated synchronous.

## Efforts
- update ruby  `brew upgrade ruby`
- reinstall CocoaPods  `sudo gem install -n /usr/local/bin cocoapods`
- Incrementing buffer size `git config --global http.postBuffer 524288000`
- Command line tool  `sudo xcode-select --switch /Applications/Xcode.app`

And so on, All the suggestions from google and github i had tried, but nothing help!

## React Native version:
```
npx react-native info

info Fetching system and libraries information...
System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i7-5650U CPU @ 2.20GHz
    Memory: 510.25 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
    Yarn: Not Found
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.7, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 11.7/11E801a - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
    Python: 3.8.3 - /Users/xhm/opt/anaconda3/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. npx react-native init app
2. cd ./app/ios && pod install

## Expected Results
Just want to see "Hello, World!" in react-native, Why is it so hard？

**Comment by hongmaoxiao** [comment]
#https://github.com/facebook/flipper/pull/1528

**Comment by hongmaoxiao** [comment]
react-native is great! like my lover.
But I feel like I'm losing my lover right now!
累觉不爱！

**Comment by chrisglein** [comment]
The environment info your provided listed "Not Found" for all the react native parts. Do you know what version you were targeting? It's possible your issue can be resolved by using a different version (older or newer, depending on what you're targeting now). The PR you linked has been merged, so it will show up in a future version.

**Comment by hongmaoxiao** [comment]
> The environment info your provided listed "Not Found" for all the react native parts. Do you know what version you were targeting? It's possible your issue can be resolved by using a different version (older or newer, depending on what you're targeting now). The PR you linked has been merged, so it will show up in a future version.

environment:
```
react: 16.13.1
react-native: 0.63.2
```

Anyway, the problem has been solved. But i don't know why! 
Maybe this problem is caused by the network
Seems `Sonar ` can redirect to `flipper` correctly!

Thanks!
