### ISSUE TITLE
[Andorid] Get activity from bridge module

### ISSUE THREAD

**Issue by NishanthShankar** [facebook/react-native#2996]
Is there a straight forward way to get a handle on the activity or activity context from the bridge module

**Comment by NishanthShankar** [comment]
I'm currently doing this by creating a static function in MainActivity. Please let me know if this is clean approach

**Comment by astreet** [comment]
In the future, please ask these questions on StackOverflow with the react-native tag so other RN developers can help out.

Generally, it is not good to make a static reference to an Activity as it will keep it from being garbage collected even after it has been destroyed. What you can do is create and use your own implementation of ReactPackage and pass an Activity to it via the constructor (and from there pass the Activity to your module via its constructor when you create it in createNativeModules). You should make sure you can't do what you want to do with an Application instance though, in which case you can use ReactContextBaseJavaModule and use getApplicationContext on the available ReactContext.

**Comment by marcshilling** [comment]
Thanks @astreet, good approach.

**Comment by mdp** [comment]
Just to help close the loop on this for future readers - http://stackoverflow.com/questions/32704336/how-to-access-activity-from-a-react-native-android-module
