### ISSUE TITLE
Flatlist item card getting hidden behind another card while scaling

### ISSUE THREAD

**Issue by saubhagya23** [facebook/react-native#29965]
**Description:**
I'm facing an issue with FlatList. In the application, I've to **scale or zoom my card on hover**. But when scaling, the cards does not overlap properly and the zoomed item gets behind the one next item in the list.

**ScreenShot:**
<img width="995" alt="Screenshot 2020-09-17 at 10 54 35 AM" src="https://user-images.githubusercontent.com/25630095/93424981-c6c96a80-f8d6-11ea-8e3c-8196140ebaa2.png">

**Expected Result:**
The scaled card should overlap the other cards on both sides. 

**RN version:** 0.61.2

Please suggest a solution for this problem.

**Comment by tj-mc** [comment]
Have you tried setting a `zIndex` property in the `style` attribute of each item? If you set that `zIndex` to change on hover, you can ensure that the hovered item is above all others.

**Comment by saubhagya23** [comment]
@tj-mc Yes I have tried that but it's not working.

**Comment by tj-mc** [comment]
It will be diffcult to make more suggestions without more details or a code example. Have you considered doing this without flatlist?

**Comment by PEZO19** [comment]
@saubhagya23 How are you implementing the hovering part?

**Comment by madarkalgaurav** [comment]
find any solution for this?

**Comment by likern** [comment]
I can confirm this bug. On React Native `0.66.0` on Android `zIndex` doesn't work.
I **can't make** right adjacent images to be _behind_ the left adjacent ones.

https://user-images.githubusercontent.com/842306/138356089-7fa38a47-c411-4966-af9c-8abd2b786527.mp4

From what I see `zIndex` is applied to `<View />` components which then embed `<Image />` as children.

![Снимок экрана от 2021-10-22 00-15-17](https://user-images.githubusercontent.com/842306/138357902-bced9085-4710-47aa-b68c-2dc7c680ef18.png)

Can it be related to some internals of `<ScrollView />`? I see some `Anonymous` component inside `<ScrollView />`, and only it contains `<View />` components.

![Снимок экрана от 2021-10-22 00-19-44](https://user-images.githubusercontent.com/842306/138358874-d6744977-f694-4437-a48a-6193b8d2f546.png)


Reproduction code will soon be available inside this application [React Native 0.66.0 App](https://github.com/breeffy/react-native-monorepo/tree/main/packages/example-mobile-0.66.0)

**Comment by ayusch-apps-curefit** [comment]
Did you manage to get it working with FlatList ? I'm having the same problem.
Using `elevation` didn't work too.

**Comment by likern** [comment]
@ayusch-apps-curefit Here the code https://github.com/breeffy/react-native-monorepo and example usage https://github.com/breeffy/react-native-monorepo/blob/main/packages/example-app/src/stories/CardPicker.stories.tsx

It works as shown in gif. For central card to be above left and right card - probably doesn't work.

**Comment by rhadamez** [comment]
Still happening in version 0.68.2.

**Comment by justinjaeger** [comment]
I found a workaround for myself, actually by accident. I have an absolutely-positioned dropdown on each item that should overlap all items in a vertical list when tapped. Tried to increment the item's z-index with no luck, as in the first image. I got it to work by **decrementing** the index instead. But you cannot use FlatList for some reason, so you can just map over your items like so:

`         <ScrollView
             style={{ flex: 1 }}
             contentContainerStyle={{ paddingBottom: 120 }}
         >
             {data.map((item, i) => (
                 <LineItem item={item} index={i} />
             ))}
         </ScrollView>`

Then each item would be like: 

`<View
            style={{
                backgroundColor: theme.colors.white,
                margin: 10,
                zIndex: -index,
                height: 30,
            }}
        >
            <View
                style={{
                    position: 'absolute',
                    height: 100,
                    backgroundColor: index % 2 ? 'red' : 'blue',
                    width: 100,
                }}
            />
        </View>`

![simulator_screenshot_88C55D47-0839-4453-A374-761B9D07B7D4](https://user-images.githubusercontent.com/66435161/225036361-281e625a-d7ea-4226-b751-c58734678092.png)

![simulator_screenshot_60A1072A-4637-4960-A074-3BD84517635A](https://user-images.githubusercontent.com/66435161/225036107-fca4c9f7-5a6d-4e02-8b93-98bbc5ea49f7.png)

**Comment by LucasCoelho** [comment]
any luck with this anyone?
