### ISSUE TITLE
iOS14 local image  network image not work

### ISSUE THREAD

**Issue by maoyuhu** [facebook/react-native#29968]
Xcode-12.0
iOS-14
react-native-0.62.1
react-16.11.0
node-12.6.1
npm-6.13.4
hey, author ,today,i upgrade my Xcode for 12.0,and my phone to 14,i found my app project that all image(loacl network) are not show,but other iOS version work well,what should I do, next step,thanks

**Comment by maoyuhu** [comment]
info Fetching system and libraries information...
System:
    OS: macOS 10.15.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
    Memory: 17.45 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.1 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 22, 23, 25, 26, 27, 28, 29
      Build Tools: 23.0.1, 23.0.3, 25.0.0, 26.0.2, 27.0.3, 28.0.2, 28.0.3, 29.0.2, 29.0.3
      System Images: android-25 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-28 | Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
      Android NDK: 21.2.6472646
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 12.0/12A7209 - /usr/bin/xcodebuild
  Languages:
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.1 => 0.62.1 
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by namitonefc** [comment]
This worked for me https://github.com/facebook/react-native/issues/29279#issuecomment-657201709

**Comment by weed-x** [comment]
how to fix it on iOS 13.5  and react-native 0.63.2

**Comment by weed-x** [comment]
network image does not show on iOS simulator 13.5 and react-native 0.63.2

**Comment by ChoiHyeongu** [comment]
network images and local images not shown on iOS simulator and test flight

- Xcode12
- react-native 0.62.2

**Comment by armandomendivil** [comment]
same issue
- Xcode 12
- react-native 0.62.2

**Comment by vauruk** [comment]
i'm the same error ! 
-> Xcode 12
-> react-native 0.62.2

**Comment by EQuimper** [comment]
https://github.com/facebook/react-native/issues/29968#issuecomment-694084303 this work

**Comment by JeremiahUL** [comment]
Same Error: 
I just upgraded to Xcode 12.0
All images, local and remote are no longer working

A hack I had to use is to download ```react-native-fast-image``` and use their image component instead

**Comment by cristianoccazinsp** [comment]
Same here, broken on both RN 0.62 and 0.63

**Comment by EQuimper** [comment]
This is the fix here. https://github.com/facebook/react-native/issues/29279#issuecomment-658244428 You can use `npx patch-package` to help you. Did get this issue this morning and this single else statement make it work

@cristianoccazinsp

**Comment by maoyuhu** [comment]
> same issue
> 
> * Xcode 12
> * react-native 0.62.2
