### ISSUE TITLE
Unable to resolve locally installed module 

### ISSUE THREAD

**Issue by duskload** [facebook/react-native#29977]
## Description
App breaks with error `Unable to resolve module `{moduleName}` from `{place}`: `{moduleName}` could not be found within the project` in case if installed module is local (not yet submitted to any repository). But after it was submitted to the repository, it works as expected.

Tried `watchman watch-del-all` `npm start --reset-cache`.

Also tried bundling module with webpack and rollup - results are the same

## React Native version:

System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 690.95 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.4.0 - ~/.nvm/versions/node/v14.4.0/bin/node
    Yarn: Not Found
    npm: 6.14.8 - ~/.nvm/versions/node/v14.4.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /Users/duskload/.rvm/gems/ruby-2.7.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.7, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 28, 29
      Build Tools: 28.0.3, 29.0.3
      System Images: android-23 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google X86_ARM Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.7/11E801a - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_252 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
1. Create local module. (you can take a module example from a link below)
2. Create simple react-native app with cli (react-native init TestApp)
3. Install local module to react-native app (`npm i --save ../local-module`)
4. Import something from local module to `App.js`

## Expected Results
Imported functios/constants etc work as intended

## Snack, code example, screenshot, or link to a repository:
Local module sample https://github.com/duskload/rn-test-module

**Comment by SeanDunford** [comment]
@duskload - I'm not sure why but i was able to get this wprking with yarn and not npm. 

When running `npm install --save ../` 

The changes to package.json appear as 

```
    "rn-test-module": "file:.."
```

When installing it with yarn 
```
watchman watch-del-all
rm -rf node_modules/react-native-platform-datasource package-lock.json yarn.lock
yarn add ../
```

The package.json diff looks like 
```
    "rn-test-module": "../"
```


Unfortunately using the above syntax with `package.json` but it provided the same error as you. Not sure if this is an npm issue or not but give yarn a try.

**Comment by marlene89** [comment]
> @duskload - I'm not sure why but i was able to get this wprking with yarn and not npm.
> 
> When running `npm install --save ../`
> 
> The changes to package.json appear as
> 
> ```
>     "rn-test-module": "file:.."
> ```
> 
> When installing it with yarn
> 
> ```
> watchman watch-del-all
> rm -rf node_modules/react-native-platform-datasource package-lock.json yarn.lock
> yarn add ../
> ```
> 
> The package.json diff looks like
> 
> ```
>     "rn-test-module": "../"
> ```
> 
> Unfortunately using the above syntax with `package.json` but it provided the same error as you. Not sure if this is an npm issue or not but give yarn a try.
same issue here. was able to get it to work with yarn instead of npm. Thanks for the tip :) been stuck on this for a week.

**Comment by duskload** [comment]
@SeanDunford @marlene89 with above changes it works well on yarn, thanks.

But it will be great if it would have been resolved on `npm`.

**Comment by marlene89** [comment]
@duskload I believe it's quite low on their list of priorities. no one from FB even commented on the issue since September :(

**Comment by ChinKX** [comment]
The following solution is working for me:
1. Generate the tar archive:
`npm pack /path/to/package`

2. Install it:
`npm install /path/to/file.tgz`

Note: It seems like running `npm install /path/to/package` command alone is not working most probably due to some symlinking issues [Inspiration from here](https://medium.com/@vcarl/problems-with-npm-link-and-an-alternative-4dbdd3e66811). Again, I might not be correct because I am not really experienced with npm and I am happy to listen to others' explanations. Thanks!

## Reference:
https://stackoverflow.com/a/69882320
https://medium.com/@vcarl/problems-with-npm-link-and-an-alternative-4dbdd3e66811

**Comment by AmeerAsif777** [comment]
I also came across this problem. After visit the below link, I came to know that  react- native does not support symlinks. [You can check here](https://github.com/facebook/metro/issues/1)

I have solved this by adding these lines in the metro.config.js file. Please replace `your_module` with your module name

```js 
const path = require('path');
const thirdPartyPath = path.resolve(
  __dirname + '/../your_module/',
);  // Path of your local module

const thirdParty= {
  'your_module': thirdPartyPath,
};
const watchFolders = [ thirdPartyPath];

module.exports = {
  resolver: {
    thirdParty,
  },
  watchFolders
};
```

**Comment by Mar1anne** [comment]
Came across this issue as well. Using `yarn` instead of `npm` did the trick. Thanks @SeanDunford

**Comment by neildevas** [comment]
I had success with [ChinKX's solution](https://github.com/facebook/react-native/issues/29977#issuecomment-1145550495) because I didn't want to switch from using `npm` to `yarn`
