### ISSUE TITLE
Typescript test bug

### ISSUE THREAD

**Issue by hosseinmd** [facebook/react-native#29972]
There is an error in type checking.
```
node_modules/@types/react-native/index.d.ts:1701:36 - error TS2694: Namespace 'React' has no exported member 'ElementRef'.  currentlyFocusedInput(): React.ElementRef<HostComponent<unknown>>;
```

This is likely due to an outdated version of @types/react. Try upgrading that version to last.

## React Native version:
"@types/react-native": "^0.63.18"

**Comment by safaiyeh** [comment]
Hi @hosseinmd thank you for the issue. This change is trivial, I would recommend just opening a PR for this in the repo.

I would appreciate if you can use the issue template when opening issues.

**Comment by hosseinmd** [comment]
Sorry about the template.
I don't think so, this change is not trivial, could you please fix this?

**Comment by chrisglein** [comment]
@hosseinmd Is this still an issue with latest? What is 0.63.18? What release are you using (see list [here](https://www.npmjs.com/package/react-native))? Can you run the environment command?

**Comment by chrisglein** [comment]
Oh, missed that was the version for the types library, not react-native. Can you provide your RN version as well?

**Comment by hosseinmd** [comment]
react-native version is 63.2, but my problem is types

**Comment by safaiyeh** [comment]
@hosseinmd could you check if your react version matches your types/react version
