### ISSUE TITLE
Fast refresh: the way to skip or force for a module

### ISSUE THREAD

**Issue by whitecolor** [facebook/react-native#29989]
## Description
This is not completely a bug but didn't find where to place it because for proposal it is probably quite a small scope.

Documentation states:
>If you edit a module that only exports React component(s), Fast Refresh will update the code only for that module, and re-render your component. You can edit anything in that file, including styles, rendering logic, event handlers, or effects.

But simple module looks like:
```ts
export const SomeFn = () => 1
```
Will be accepted and reloaded because RN considers `SomeFn` to be a React component. 
In case of such module:
```ts
export const someFn = () => 1
```
`someFn` is not considered to be a React component

So the points:

1) This should be probably explicitly reflected in RN docs, that such convention is used, which is currently not.
2) An second, as there is probably no good way to Define if the exported function is really a Component, it would be useful to introduce some comment for example `@refresh skip` to make this file not accepted while fast refresh.
3) Another case maybe one may want to enable fast refresh on a module that doesn't comply with the default convention, so it it would be useful to be possible to force refresh on such module with for example `@refresh force` comment.

**Comment by whitecolor** [comment]
react-native version 0.62.2

**Comment by chrisglein** [comment]
> This is not completely a bug but didn't find where to place it because for proposal it is probably quite a small scope.

As you'll note from the [issue template](https://github.com/facebook/react-native/issues/new/choose), proposals should go in a different discussions repo. This repo is for bug reports.

>  `someFn` is not considered to be a React component

Before posting there, however, is it intended that the only difference here is in the capitalization (camelCase vs. PascalCase)? Is that essential to the behavior difference?

Also, is this a React thing or a React Native thing? As in would your feedback be the same for plain React.js?

These are some questions you might anticipate before posting a proposal in the appropriate forum.

**Comment by ikara5** [comment]
> ⚠️	Missing Environment Information
> ℹ️	Your issue may be missing information about your development environment. You can obtain the missing information by running `react-native info` in a console.

#
