### ISSUE TITLE
React Native. "React.createElement: type is invalid -- expected a string"

### ISSUE THREAD

**Issue by ashpbrindle** [facebook/react-native#29982]
Hi I keep receiving this error when my app launches. I cant see any errors in the code. Although most fixes for this problem is to do with how I am importing my HomeScreen, However I Beleive this is being done correctly.

Here is the Code for my App.js

`import {createAppContainer} from 'react-navigation'
import {createStackNavigator} from 'react-navigation-stack'
import HomeScreen from './screens/HomeScreen'

const navigatior = createStackNavigator(
  {
    Home: {screen: HomeScreen}
  },
  {
    initialRouteName: "Home"
  }
)`

and here is the code for my HomeScreen.js:

`import {React, Component} from 'react';
import {Text, View} from 'react-native';

export default class HomeScreen extends Component {

  render() {
    return (
      <View>
        <Text>Hello</Text>
      </View>
    );
  }
}`

as you can see I am importing the HomeScreen correctly:

`import HomeScreen from" ./screens/HomeScreen"`

and am correctly exporting the Component

`export default class HomeScreen extends Component {`

Here are the errors produced
![dtKnB](https://user-images.githubusercontent.com/59151951/93651121-502c8a00-fa08-11ea-9775-cd820a5fed16.png)

Any help is appreciated, Thanks!

**Comment by gabts** [comment]
What is `Hello` in your HomeScreen render method?

If it's supposed to be a string you must wrap it in a React Native Text component.

If you're new to React Native and need guidance please read the [documentation](https://reactnative.dev/docs/getting-started) or find a [community](https://reactnative.dev/help), GitHub issues is not a support forum.
