### ISSUE TITLE
[Android] Border radius overflow + missing style support

### ISSUE THREAD

**Issue by mattds** [facebook/react-native#2998]
Hi team, would it be possible to support the styles borderTopLeftRadius, borderTopRightRadius, borderBottomLeftRadius and borderBottomRightRadius on Android as these don't seem to be supported at the moment and no mention is made of this in the documentation? Also at the moment overflow doesn't crop a view to within the border if a border radius is specified on android, an example of this is here, thanks: https://rnplay.org/apps/ktczIA

**Comment by mkonicek** [comment]
Hi @mattds, this is not supported on Android yet. Would be happy to review a pull request.

**Comment by kmagiera** [comment]
PR would be welcome. Good place to start looking would be https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/views/view/ReactViewBackgroundDrawable.java#L216 we can use `addRoundRect` method version with separate radius for each side. Note that `ImageView` has it's own logic for handling rounded borders.

**Comment by mattds** [comment]
Hi, I've submitted a pull request as suggested https://github.com/facebook/react-native/pull/3035. Please review when you have a chance to, thanks.

**Comment by kmagiera** [comment]
thanks to you @mattds ! Closing this and let's continue discussion on #3035

**Comment by uc-hus** [comment]
![image](https://cloud.githubusercontent.com/assets/12196308/18610236/41c7f8aa-7d34-11e6-9ed4-5879404a1023.png)
