### ISSUE TITLE
While loading new image from uri how to keep previous(old one) image in react native

### ISSUE THREAD

**Issue by NChandan** [facebook/react-native#29986]
I'm new to react native and I'm using image component to load the image from the uri and this image load from backend or ip webcam app for every 2 sec. Now I have facing the issue that when loading a new image, the old image get disappears and there will be white screen until it load new one, but for my project the old image shouldn't disappear until new image load from the uri completely.

react: "16.13.1"
react-native: "0.63.2",

Thanks in advance

**Comment by vuki656** [comment]
I think it's better to ask this question on StackOverflow. 

This is used for bug reporting.

**Comment by abtoma** [comment]
Instead of keeping the old image for placeholder and all. It will be better if you use blurRadius that is much better practice for showing something in meantime when something is loading.

**Comment by NChandan** [comment]
I have installed react native web view and now it's works fine
