### ISSUE TITLE
TextInput `accessibilityValue` is ignored on iOS

### ISSUE THREAD

**Issue by jychiao** [facebook/react-native#29981]
## Description
Using a `TextInput` with an `accessibilityValue` and `value`, I find that in iOS only the `value` is read aloud and `accessibilityValue` is ignored. For example:

`<TextInput accessibilityValue={text: "read me instead"} value={"value"}/>` would read "Value" instead of "Read me instead"

## React Native version:
0.63.2 

## Expected Results
I expect the `accessibilityValue` takes precedence, as I am able to do in other types of Views. I think I was able to see it behave as expected in Android, but it could've been coincidence.

**Comment by jeswinsimon** [comment]
This is working as intended. From the UIKit [Documentation](https://developer.apple.com/documentation/uikit/uitextfield#overview):

> Text fields are accessible by default. The default accessibility trait for a text field is User Interaction Enabled.

The accessibility values are automatically inferred as per the accessibility attributes for [UIControl](https://developer.apple.com/documentation/uikit/uicontrol).

**Comment by jychiao** [comment]
Sorry for my delayed response. I understand your point as to why the `value` is the default accessibility announcement for a text field. However, my understanding of `accessibilityValue` is as defined in the [RN documentation](https://reactnative.dev/docs/accessibility#accessibilityvalue), and it nicely provides another option for providing extra a11y information on your view. In our case we are trying to use it to announce if your input value has validations, since there is currently no more appropriate role available. 

We can easily work around this, but I am curious as to why this wouldn't be considered a bug when it conflicts with what is outlined in documentation (and behaves as I expected in Android).

**Comment by alexeykomov** [comment]
@jychiao

What worked for me is to patch `RCTUITextField.m` in this way:
```diff
diff --git a/node_modules/react-native/Libraries/Text/TextInput/Singleline/RCTUITextField.mm b/node_modules/react-native/Libraries/Text/TextInput/Singleline/RCTUITextField.mm
index 4d0afd9..8c59b3f 100644
--- a/node_modules/react-native/Libraries/Text/TextInput/Singleline/RCTUITextField.mm
+++ b/node_modules/react-native/Libraries/Text/TextInput/Singleline/RCTUITextField.mm
@@ -6,6 +6,7 @@
  */

 #import <React/RCTUITextField.h>
+#import <objc/runtime.h>

 #import <React/RCTBackedTextInputDelegateAdapter.h>
 #import <React/RCTTextAttributes.h>
@@ -47,6 +48,27 @@ - (void)setIsAccessibilityElement:(BOOL)isAccessibilityElement
   // inside the component.
 }

+- (NSDictionary<NSString *, id> *)accessibilityValueInternal
+{
+  return objc_getAssociatedObject(self, _cmd);
+}
+- (void)setAccessibilityValueInternal:(NSDictionary<NSString *, id> *)accessibilityValue
+{
+  objc_setAssociatedObject(
+      self, @selector(accessibilityValueInternal), accessibilityValue, OBJC_ASSOCIATION_RETAIN_NONATOMIC);
+}
+
+- (NSString *)accessibilityValue {
+    if (self.accessibilityValueInternal) {
+        id text = self.accessibilityValueInternal[@"text"];
+        if (text && [text isKindOfClass:[NSString class]]) {
+            return text;
+        }
+        return nil;
+    }
+    return nil;
+}
+
 #pragma mark - Properties

 - (void)setTextContainerInset:(UIEdgeInsets)textContainerInset

```
