### ISSUE TITLE
run-android has started taking very long ( > 20 mins )

### ISSUE THREAD

**Issue by purezen** [facebook/react-native#29996]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description

I have been working on react-native since more than a year now. The `run-android` command didn't use to take more than a couple of minutes. However, when I ran the command for a new projects initiated with the `init` command it took more than 20 minutes ( didn't check when it finished so not sure of total time ) for it to complete.

Also surprisingly there is hardly any CPU usage as well as can be seen.

Initially I used to execute the react-native command via `npx` but then I installed the cli globally but the issue still continues ( v. 4.13.0 )

## React Native version:
Run `react-native info` in your terminal and copy the results here.

Says `error Unrecognized command "info".`

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Initiate new project via `react-native init project`
2. Run `react-native run-android`

## Expected Results
Describe what you expected to happen.

It should have completed in a couple of minutes triggering CPU usage when ran

## Snack, code example, screenshot, or link to a repository:
![Screenshot from 2020-09-21 18-18-53](https://user-images.githubusercontent.com/3036093/93768451-05dd2000-fc37-11ea-9b81-a1628bbc1b6b.png)

**Comment by purezen** [comment]
![Uploading Screenshot from 2020-09-23 00-47-44.png…]()

**Comment by purezen** [comment]
@chrisglein as I mentioned I am unable to run `react-native info`
![Screenshot from 2020-09-23 00-47-44](https://user-images.githubusercontent.com/3036093/93927453-85054d80-fd36-11ea-94f0-0c02c8efbaa6.png)

**Comment by chrisglein** [comment]
What version of react-native do you believe you have? Your original bug report doesn't include the version. What is the output of the `help` command? I don't know how far back `info` goes, but it's been there a while. It sounds like you had some issues running react-native with npx and then shifted to a global install - that might be part of your problem?

**Comment by pedrocardoz0** [comment]
Have you tried to run `react-native info` at the **root** of your project?
