### ISSUE TITLE
How to Implement Android Live Data in React native

### ISSUE THREAD

**Issue by vick16ach** [facebook/react-native#29993]
I'm exploring React native and I came from Android Kotlin/Java background. In Android There is a feature called [LiveData][1]. 

It is very helpful that, Instead of updating the UI every time the app data changes, your observer can update the UI every time there's a change.

I mean when data changed in local database I don't need to explicitly update the UI. UI update will automatically takes place.

How to use `Android LiveData` in React native ?  I don't find a bit about this on internet.

  [1]: https://developer.android.com/topic/libraries/architecture/livedata

**Comment by LuckyLuke19** [comment]
I have done this in my app.
To begin with, create a native module which will notify JS when the value of the `LiveData` object changes.
[Here is an example of such a native module](https://gist.github.com/LuckyLuke19/edc86613b40490edf1aef26c16b2ed29). I have included comments and annotated the parts you will have to change if you copy-paste the code.

Then, naturally, you have to register the module as described [here](https://reactnative.dev/docs/native-modules-android#register-the-module).

After that you have to listen the event emitted from the native module in JS.
I have created an [example](https://gist.github.com/LuckyLuke19/cb6b34d61afb1e836d19e3284f9c50e4) which uses React hooks, but you could use traditional React class methods just as well.
In this example, you can use the return value of the `useLiveData` method (you can name it however you want) directly in your components, and it will update every time the value of the `LiveData` object updates.

Please let me know if you want any clarifications!

**Comment by dulmandakh** [comment]
I see that @LuckyLuke19 answered the question. So closing this issue. Thanks
