### ISSUE TITLE
After updated xcode 12 , Images are not are showing

### ISSUE THREAD

**Issue by johndig0027** [facebook/react-native#29990]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
I have updated my xcode to 12 and suddenly all images which is used in application is disappeared.  Dont know whats the , issue 

## React Native version:
System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 94.91 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.8.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.7 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 23, 26, 28, 29
      Build Tools: 28.0.3, 29.0.3
      System Images: android-27 | Google APIs Intel x86 Atom, android-R | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: 12.0/12A7209 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_251 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found
## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.
1.Run the project from xcode
2. When i run project from terminator it gives me following error 
/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

## Expected Results
it should run with all images and also run from terminal if i run command "react-native run-ios"

**Comment by plrdev** [comment]
This happens to me as well, images reserve their space in the layout, but nothing is shown. Running the same app in 13.5 simulator image has the images loading properly.

**Comment by SConaway** [comment]
You'll need to upgrade the react-native version to fix the images and the [`@react-native-community/cli`](https://github.com/react-native-community/cli#updating-the-cli) to solve the build issue.

**Comment by johndig0027** [comment]
> This happens to me as well, images reserve their space in the layout, but nothing is shown. Running the same app in 13.5 simulator image has the images loading properly.

**Comment by johndig0027** [comment]
> You'll need to upgrade the react-native version to fix the images and the [`@react-native-community/cli`](https://github.com/react-native-community/cli#updating-the-cli) to solve the build issue.

Update react-native should not be not solution, may be it will break some other feature ,We need to find out some other solution

**Comment by SConaway** [comment]
Sorry, but it's not. You can manually patch the package. Check out PR #29420 and issue #29279 for more details.

There's a reason upgrades are created: to solve bugs and to add features.

**Comment by johndig0027** [comment]
> Sorry, but it's not. You can manually patch the package. Check out PR #29420 and issue #29279 for more details.
> 
> There's a reason upgrades are created: to solve bugs and to add features.

Ok ....Thanks Team, I will try to update it

**Comment by ssenigl** [comment]
What if I am using last version and this still happens to me?

**Comment by cardiohelge** [comment]
Same to me. Since updating to ios14, _Print: Entry, ":CFBundleIdentifier", Does Not Exist_ occurs.

**Comment by plrdev** [comment]
> Same to me. Since updating to ios14, _Print: Entry, ":CFBundleIdentifier", Does Not Exist_ occurs.

Updating cli to 4.13.0 helped for me. How I did it was by removing references to the cli in packages json lock file and running npm install again.

**Comment by cardiohelge** [comment]
> > Same to me. Since updating to ios14, _Print: Entry, ":CFBundleIdentifier", Does Not Exist_ occurs.
> 
> Updating cli to 4.13.0 helped for me. How I did it was by removing references to the cli in packages json lock file and running npm install again.

Didnt fix it for me. However, I realized that xcode tried to access a non-existent path (depending on the scheme) So i changed the scheme in my npm run ios call. It works again but its kind of unsatisfactory

**Comment by SConaway** [comment]
@cardiohelge what was the specific error? Like the whole line?

**Comment by tolgaberk** [comment]
I can confirm that removing all references to cli in the `.lock` file and running `yarn install OR npm install` does resolve the issue.

**Comment by ssenigl** [comment]
It was happening for me after: "npm run ios"
I found another way how to deal with that 😄  😄 .
When I open NameOfMyApp.xcodeproj and run virtual machine from here it works and I can develop the app and see real-time results.

**Comment by cardiohelge** [comment]
> I can confirm that removing all references to cli in the `.lock` file and running `yarn install OR npm install` does resolve the issue.

I have to admit i did not try to rebuild my npm_modules. Might give that a shot. 👍

**Comment by tolgaberk** [comment]
> It was happening for me after: "npm run ios"
> I found another way how to deal with that 😄 😄 .
> When I open NameOfMyApp.xcodeproj and run virtual machine from here it works and I can develop the app and see real-time results.

In my case xcode was able to build also but the problem was when i try to build with yarn or npm the cli was crashing, but i rather build with cli then opening xcode every single time.

**Comment by prateekchitransh1907** [comment]
Didn't update React native library. In the file RCTUIImageViewAnimated.m
updated this function as mentioned in below link: 
 - (void)displayLayer:(CALayer *)layer 
 { 
  if (_currentFrame) {
    layer.contentsScale = self.animatedImageScale;
    layer.contents = (__bridge id)_currentFrame.CGImage;
  } else {
    [super displayLayer:layer];
  }
}

https://github.com/facebook/react-native/issues/29279#issuecomment-658244428

Hope this helps. :)

**Comment by trungnguyencmu** [comment]
I try deleted node_modules and package-lock.json, and npm install, but still got same problem :(

**Comment by oxbits** [comment]
https://developer.apple.com/forums/thread/662072

saw this comment _  i am gonna download xcode 12 xib from apple developer downloads, see if i can get ios 13 and see if that works _

https://developer.apple.com/download/more/

**Comment by oxbits** [comment]
https://developer.apple.com/forums/thread/662072

☝️ saw this comment _
• i had Version 12.0.1 (12A7300) from the app store

only ios 14 is available on simulators _ under PREFERENCES > COMPONENTS _ i am unable to download old ios versions
no images showed up in react native app
• i downloaded the xcode 12 xib from apple developer downloads Version 12.0 (12A7209),

https://developer.apple.com/download/more/
in xcode downloaded ios 13.5 under PREFERENCES > COMPONENTS
in simulator under FILE > OPEN SIMULATOR _ selected ios 13.5 device
images show up in my react native app again !!!! YAY !!!!
🌈😺 💚💛🧡❤️💜💙

** now i cannot figure out how to run it on ios 14.0 simulators _ whatevs _ i will work on that another day i guess _

**Comment by unicornRainbows** [comment]
👍  Here is the answer.. 👍 

Try this, Remove yarn lock file or package.lock file then delete pod lock file, install pod once again . your app should run now.

Referenced from here:
https://github.com/facebook/react-native/issues/30028#issuecomment-699862184

**Comment by VictorJonasson** [comment]
> Didn't update React native library. In the file RCTUIImageViewAnimated.m
> updated this function as mentioned in below link:
> 
> * (void)displayLayer:(CALayer *)layer
>   {
>   if (_currentFrame) {
>   layer.contentsScale = self.animatedImageScale;
>   layer.contents = (__bridge id)_currentFrame.CGImage;
>   } else {
>   [super displayLayer:layer];
>   }
>   }
> 
> [#29279 (comment)](https://github.com/facebook/react-native/issues/29279#issuecomment-658244428)
> 
> Hope this helps. :)

Works like a charm! Thanks

**Comment by machine-dev** [comment]
Upgrade react-native to the latest version.
This issue is part of 0.63.2.
I was using 0.63.0 and upgrading RN version solved this.

**Comment by Vanclief** [comment]
For anyone who gets late to this thread: 

You either
1. Update to 0.63.3
2. Patch the `react-native` package. This was my case, this guide was top notch for doing it "properly" https://jeffgukang.github.io/react-native-tutorial/docs/tips/image-error-ios14.html

**Comment by MartinArnautov** [comment]
prateekchitransh1907's answer is correct.
So when can release a new version of react native with the change?

**Comment by SConaway** [comment]
A new version wouldn't make sense since the patch was in 0.63.2. Are you still having issues @MartinArnautov ?

**Comment by martinredbullet** [comment]
Ok, @SConaway 
Thanks for your response.

**Comment by wulaizi** [comment]
> 没有更新React本机库。在文件RCTUIImageViewAnimated.m中
> 更新了此功能，如下面的链接所述：
> 
> * （void）displayLayer：（CALayer *）layer 
>   { 
>   if（_currentFrame）{ 
>   layer.contentsScale = self.animatedImageScale; 
>   layer.contents =（__bridge id）_currentFrame.CGImage; 
>   } else { 
>   [super displayLayer：layer]; 
>   } 
>   }
> 
> [＃29279（评论）](https://github.com/facebook/react-native/issues/29279#issuecomment-658244428)
> 
> 希望这可以帮助。:)

My react native version is 0.58.6 and I can’t find the file RCTUIImageViewAnimated.m. How can I solve this problem?

**Comment by SerotoninaAbad** [comment]
> > 没有更新React本机库。在文件RCTUIImageViewAnimated.m中
> > 更新了此功能，如下面的链接所述：
> > 
> > * （void）displayLayer：（CALayer *）layer
> >   {
> >   if（_currentFrame）{
> >   layer.contentsScale = self.animatedImageScale;
> >   layer.contents =（__bridge id）_currentFrame.CGImage;
> >   } else {
> >   [super displayLayer：layer];
> >   }
> >   }
> > 
> > [＃29279（评论）](https://github.com/facebook/react-native/issues/29279#issuecomment-658244428)
> > 希望这可以帮助。:)
> 
> My react native version is 0.58.6 and I can’t find the file RCTUIImageViewAnimated.m. How can I solve this problem?

Same here

**Comment by prateekchitransh1907** [comment]
> > > 没有更新React本机库。在文件RCTUIImageViewAnimated.m中
> > > 更新了此功能，如下面的链接所述：
> > > 
> > > * （void）displayLayer：（CALayer *）layer
> > >   {
> > >   if（_currentFrame）{
> > >   layer.contentsScale = self.animatedImageScale;
> > >   layer.contents =（__bridge id）_currentFrame.CGImage;
> > >   } else {
> > >   [super displayLayer：layer];
> > >   }
> > >   }
> > > 
> > > [＃29279（评论）](https://github.com/facebook/react-native/issues/29279#issuecomment-658244428)
> > > 希望这可以帮助。:)
> > 
> > 
> > My react native version is 0.58.6 and I can’t find the file RCTUIImageViewAnimated.m. How can I solve this problem?
> 
> Same here

Go to xcode, in file search type RCTUIImageViewAnimated.m and you will see the file. You can also search by CA Layer.

**Comment by s17084** [comment]
> > Same to me. Since updating to ios14, _Print: Entry, ":CFBundleIdentifier", Does Not Exist_ occurs.
> 
> Updating cli to 4.13.0 helped for me. How I did it was by removing references to the cli in packages json lock file and running npm install again.

@plrdev thank you so much, your solution worked for me perfectly. I've searched package-lock.json for "@react-native-community/cli*" and removed all occurrences - whole objects. Then after installing all dependencies (npm install) cli command "npx react-native run-ios" started working correctly again. So much time wasted for this problem...

**Comment by Yandamuri** [comment]
@Vanclief, @SConaway  I am in "react-native": "0.63.2" and still facing the issue. Do I have to do anything else besides RN.0.63.2?

**Comment by SConaway** [comment]
> @Vanclief, @SConaway  I am in "react-native": "0.63.2" and still facing the issue. Do I have to do anything else besides RN.0.63.2?

Try upgrading @react-native-community/cli by deleting your `yarn.lock` or `package-lock.json`.

**Comment by ksjmb** [comment]
> Didn't update React native library. In the file RCTUIImageViewAnimated.m
> updated this function as mentioned in below link:
> 
> * (void)displayLayer:(CALayer *)layer
>   {
>   if (_currentFrame) {
>   layer.contentsScale = self.animatedImageScale;
>   layer.contents = (__bridge id)_currentFrame.CGImage;
>   } else {
>   [super displayLayer:layer];
>   }
>   }
> 
> [#29279 (comment)](https://github.com/facebook/react-native/issues/29279#issuecomment-658244428)
> 
> Hope this helps. :)

Thank you for the solution, it was work like a **rocket**..!

**Comment by detodos** [comment]
> Didn't update React native library. In the file RCTUIImageViewAnimated.m
> updated this function as mentioned in below link:
> 
> * (void)displayLayer:(CALayer *)layer
>   {
>   if (_currentFrame) {
>   layer.contentsScale = self.animatedImageScale;
>   layer.contents = (__bridge id)_currentFrame.CGImage;
>   } else {
>   [super displayLayer:layer];
>   }
>   }
> 
> [#29279 (comment)](https://github.com/facebook/react-native/issues/29279#issuecomment-658244428)
> 
> Hope this helps. :)

It was an issue when I had updated Xcode to V12. Solved. Thanks.

**Comment by klever34** [comment]
Still facing this issue in `react-native: 0.63.4` `ios 14.5 XCode 12.5` and all the fixes above aren't working. Can someone suggest a fix?

**Comment by asmiddy** [comment]
make sure the following code is in your metro.config.js file

module.exports = {
    transformer: {
        assetPlugins: ['expo-asset/tools/hashAssetFiles']
    }
};

**Comment by gmonte** [comment]
> Still facing this issue in `react-native: 0.63.4` `ios 14.5 XCode 12.5` and all the fixes above aren't working. Can someone suggest a fix?

Do you find any solution?

**Comment by VictorJonasson** [comment]
> > Didn't update React native library. In the file RCTUIImageViewAnimated.m
> > updated this function as mentioned in below link:
> > 
> > * (void)displayLayer:(CALayer *)layer
> >   {
> >   if (_currentFrame) {
> >   layer.contentsScale = self.animatedImageScale;
> >   layer.contents = (__bridge id)_currentFrame.CGImage;
> >   } else {
> >   [super displayLayer:layer];
> >   }
> >   }
> > 
> > [#29279 (comment)](https://github.com/facebook/react-native/issues/29279#issuecomment-658244428)
> > Hope this helps. :)
> 
> Works like a charm! Thanks

**Comment by ejeanneaubc** [comment]
@gmonte Same here. Do you find a solution please ?

**Comment by cinder92** [comment]
> Still facing this issue in `react-native: 0.63.4` `ios 14.5 XCode 12.5` and all the fixes above aren't working. Can someone suggest a fix?

im getting this issue too. is so anoying that it was working on Xcode 12 and now is not on 12.5

**Comment by cinder92** [comment]
@ejeanneaubc did you find any solution?
