### ISSUE TITLE
Android: NativeAnimatedModule.startOperationBatch not found

### ISSUE THREAD

**Issue by lmarques6** [facebook/react-native#29999]
##  Description 
When starting up my android app using the commit https://github.com/facebook/react-native/commit/81c61705f78933ffd40731f2911aed1fb8415073, the app logs the error:

```
TypeError
NativeAnimatedModule.startOperationBatch is not a function

app:///index.android.bundle in Object.disableQueue at line 25351:2343
app:///index.android.bundle in TimingAnimation.__startNativeAnimation at line 53885:1346
app:///index.android.bundle in start at line 101261:3687
app:///index.android.bundle in TimingAnimation.start at line 101261:3876
app:///index.android.bundle in AnimatedValue.animate at line 42719:4871 
```

I believe the error comes from: https://github.com/facebook/react-native/blob/master/Libraries/Animated/NativeAnimatedHelper.js#L78

I added a log to inspect the `NativeAnimatedModule` object and can confirm that methods `startOperationBatch` and `finishOperationBatch` are not present.
![image](https://user-images.githubusercontent.com/29558407/93896957-8ba4ae00-fcbf-11ea-98c7-f926c7cc5188.png)

The reason I'm testing out the latest commit is to try to overcome constant android crashes from RN 0.63.2 (`IndexOutOfBoundsException`, `JSApplicationIllegalArgumentException` in animation handling), which I see an attempt to resolve at commit https://github.com/facebook/react-native/commit/81c61705f78933ffd40731f2911aed1fb8415073 

As a temporary solution I added this, which allows me to get past the calls:
![image](https://user-images.githubusercontent.com/29558407/93914331-62dae380-fcd4-11ea-9114-98a9e0a220fd.png)

Side note: commit mentioned above seems to have stabilized my android app, no crashes so far.

## React Native version:
System:
    OS: macOS 10.15.3
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 114.96 MB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.7.4 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      Android NDK: 20.0.5594570
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
  Languages:
    Java: 12.0.1 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: 4.12.0 => 4.12.0
    react: 16.13.1 => 16.13.1
    react-native: https://github.com/facebook/react-native#22b5f32f74bc99be5a4d2f0ea987fa1b08a1c901 => 1000.0.0
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Create a react-native app
2. Add the following component with an animation in componentDidMount:
```
import React from 'react';
import {Animated, Easing} from 'react-native';
import {observable, computed, action} from 'mobx';
import {observer} from 'mobx-react';

@observer
class MyComponent extends React.Component {
  @observable.ref dragY = new Animated.Value(0);

  componentDidMount() {
    // this animation causes the error
    Animated.timing(this.dragY, {
      toValue: 0,
      duration: 200,
      easing: Easing.inOut(Easing.exp),
      useNativeDriver: true,
    }).start(() => console.log('Animation done!'));
  }
}

export default MyComponent;
```

## Expected Results
Expect the animation to be handled and no exceptions to occur.

## Snack, code example, screenshot, or link to a repository:
![image](https://user-images.githubusercontent.com/29558407/93797990-f0520100-fc0a-11ea-8d28-a1a7e00e6a2e.png)

**Comment by codering** [comment]
1

**Comment by ospaarmann** [comment]
+1
