### ISSUE TITLE
Black bars on top and bottom of app - Strange Bug

### ISSUE THREAD

**Issue by mgecawicz** [facebook/react-native#29994]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Running the app from the terminal using `npx react-native run-ios` as well as running from Xcode produces black bars on the top and bottom of the screen. The app is working correctly but is not the correct size on the screen. Refer to the image below. This happened after a few days of debugging and after upgrading to the newest version of React-Native.

## React Native version:
System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz
    Memory: 336.83 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.9.1 - ~/emsdk/node/12.9.1_64bit/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.10.2 - ~/emsdk/node/12.9.1_64bit/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 12.0/12A7209 - /usr/bin/xcodebuild
  Languages:
    Java: 10.0.2 - /usr/bin/javac
    Python: 3.7.4 - /Users/michaelgecawicz/opt/anaconda3/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## My Info.plist ##

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>NSAppleMusicUsageDescription</key>
  <string>YOUR TEXT</string>
  <key>NSBluetoothAlwaysUsageDescription</key>
  <string>YOUR TEXT</string>
  <key>NSBluetoothPeripheralUsageDescription</key>
  <string>YOUR TEXT</string>
  <key>NSCalendarsUsageDescription</key>
  <string>YOUR TEXT</string>
  <key>NSCameraUsageDescription</key>
  <string>YOUR TEXT</string>
  <key>NSContactsUsageDescription</key>
  <string>YOUR TEXT</string>
  <key>NSFaceIDUsageDescription</key>
  <string>YOUR TEXT</string>
  <key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
  <string>YOUR TEXT</string>
  <key>NSLocationAlwaysUsageDescription</key>
  <string>YOUR TEXT</string>
  <key>NSLocationWhenInUseUsageDescription</key>
  <string>YOUR TEXT</string>
  <key>NSMicrophoneUsageDescription</key>
  <string>YOUR TEXT</string>
  <key>NSMotionUsageDescription</key>
  <string>YOUR TEXT</string>
  <key>NSPhotoLibraryUsageDescription</key>
  <string>YOUR TEXT</string>
  <key>NSRemindersUsageDescription</key>
  <string>YOUR TEXT</string>
  <key>NSSpeechRecognitionUsageDescription</key>
  <string>YOUR TEXT</string>
  <key>NSSiriUsageDescription</key>
  <string>YOUR TEXT</string>
	<key>CFBundleDevelopmentRegion</key>
	<string>en</string>
	<key>CFBundleDisplayName</key>
	<string>Bridge</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>$(PRODUCT_NAME)</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>1.0</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleVersion</key>
	<string>1</string>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
		<key>NSExceptionDomains</key>
		<dict>
			<key>localhost</key>
			<dict>
				<key>NSExceptionAllowsInsecureHTTPLoads</key>
				<true/>
			</dict>
		</dict>
	</dict>
	<key>NSLocationWhenInUseUsageDescription</key>
	<string></string>
	
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>

	<key>UIRequiredDeviceCapabilities</key>
	<array>
		<string>armv7</string>
	</array>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
	</array>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
</dict>
</plist>

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.
1. `npx react-native run-ios`
2. Xcode >> Run

## Expected Results
The app takes up the full height of the screen.

## Snack, code example, screenshot, or link to a repository:
![Simulator Screen Shot - iPhone 11 - 2020-09-20 at 19 07 12](https://user-images.githubusercontent.com/44035616/93724569-24c7ad80-fb76-11ea-9dd3-46d67178bc45.png)

**Comment by Shing-Ho** [comment]
@mgecawicz We need your JavaScript code of this page.

**Comment by JaapWeijland** [comment]
I'm experiencing the same in a release build. The debug build is behaving as normal.

I think it happened after I edited `SplashScreen.storyboard. Could that be related?

**Comment by KrisLau** [comment]
Experiencing the same thing. The screen looks fine on android but on iOS it is adding big black bars on the top and bottom

**Comment by tunm1228** [comment]
> Please provide all the information requested. Issues that do not follow this format are likely to stall.
> 
> ## Description
> Running the app from the terminal using `npx react-native run-ios` as well as running from Xcode produces black bars on the top and bottom of the screen. The app is working correctly but is not the correct size on the screen. Refer to the image below. This happened after a few days of debugging and after upgrading to the newest version of React-Native.
> 
> ## React Native version:
> System: OS: macOS 10.15.6 CPU: (4) x64 Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz Memory: 336.83 MB / 16.00 GB Shell: 5.7.1 - /bin/zsh Binaries: Node: 12.9.1 - ~/emsdk/node/12.9.1_64bit/bin/node Yarn: 1.13.0 - /usr/local/bin/yarn npm: 6.10.2 - ~/emsdk/node/12.9.1_64bit/bin/npm Watchman: 4.9.0 - /usr/local/bin/watchman Managers: CocoaPods: 1.9.1 - /usr/local/bin/pod SDKs: iOS SDK: Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0 Android SDK: Not Found IDEs: Android Studio: Not Found Xcode: 12.0/12A7209 - /usr/bin/xcodebuild Languages: Java: 10.0.2 - /usr/bin/javac Python: 3.7.4 - /Users/michaelgecawicz/opt/anaconda3/bin/python npmPackages: @react-native-community/cli: Not Found react: 16.13.1 => 16.13.1 react-native: 0.63.2 => 0.63.2 react-native-macos: Not Found npmGlobalPackages: _react-native_: Not Found
> 
> ## My Info.plist
> NSAppleMusicUsageDescription YOUR TEXT NSBluetoothAlwaysUsageDescription YOUR TEXT NSBluetoothPeripheralUsageDescription YOUR TEXT NSCalendarsUsageDescription YOUR TEXT NSCameraUsageDescription YOUR TEXT NSContactsUsageDescription YOUR TEXT NSFaceIDUsageDescription YOUR TEXT NSLocationAlwaysAndWhenInUseUsageDescription YOUR TEXT NSLocationAlwaysUsageDescription YOUR TEXT NSLocationWhenInUseUsageDescription YOUR TEXT NSMicrophoneUsageDescription YOUR TEXT NSMotionUsageDescription YOUR TEXT NSPhotoLibraryUsageDescription YOUR TEXT NSRemindersUsageDescription YOUR TEXT NSSpeechRecognitionUsageDescription YOUR TEXT NSSiriUsageDescription YOUR TEXT CFBundleDevelopmentRegion en CFBundleDisplayName Bridge CFBundleExecutable $(EXECUTABLE_NAME) CFBundleIdentifier $(PRODUCT_BUNDLE_IDENTIFIER) CFBundleInfoDictionaryVersion 6.0 CFBundleName $(PRODUCT_NAME) CFBundlePackageType APPL CFBundleShortVersionString 1.0 CFBundleSignature ???? CFBundleVersion 1 LSRequiresIPhoneOS NSAppTransportSecurity NSAllowsArbitraryLoads NSExceptionDomains localhost NSExceptionAllowsInsecureHTTPLoads NSLocationWhenInUseUsageDescription
> ```
> <key>UILaunchStoryboardName</key>
> <string>LaunchScreen</string>
> 
> <key>UIRequiredDeviceCapabilities</key>
> <array>
> 	<string>armv7</string>
> </array>
> <key>UISupportedInterfaceOrientations</key>
> <array>
> 	<string>UIInterfaceOrientationPortrait</string>
> </array>
> <key>UIViewControllerBasedStatusBarAppearance</key>
> <false/>
> ```
> 
> ## Steps To Reproduce
> Provide a detailed list of steps that reproduce the issue.
> 
> 1. `npx react-native run-ios`
> 2. Xcode >> Run
> 
> ## Expected Results
> The app takes up the full height of the screen.
> 
> ## Snack, code example, screenshot, or link to a repository:
> ![Simulator Screen Shot - iPhone 11 - 2020-09-20 at 19 07 12](https://user-images.githubusercontent.com/44035616/93724569-24c7ad80-fb76-11ea-9dd3-46d67178bc45.png)

Have you solved this error, please give me the solution?

**Comment by LeNgoc82** [comment]
I got the same issue :(

**Comment by LeNgoc82** [comment]
In my case I found that the problem is belong to splash screen. If we fix splash screen right, The black area in top and bottom will disappear.
