### ISSUE TITLE
If anyone can let me know how to fix it this bug!!!!!

### ISSUE THREAD

**Issue by bhathiyaamarasinghe** [facebook/react-native#30001]
✋ To keep the backlog clean and actionable, issues will be
🚫 closed if they do not follow one of the issue templates:
👉 https://github.com/facebook/react-native/issues/new/choose
info Starting JS server...
'adb' is not recognized as an internal or external command,
operable program or batch file.
info Launching emulator...
error Failed to launch emulator. Reason: No emulators found as an output of `emulator -list-avds`.
warn Please launch an emulator manually or connect a device. Otherwise app may fail to launch.
info Installing the app...

> Task :app:stripDebugDebugSymbols UP-TO-DATE
Compatible side by side NDK version was not found.

> Task :app:installDebug
11:30:54 V/ddms: execute: running am get-config
11:30:54 V/ddms: execute 'am get-config' on 'emulator-5554' : EOF hit. Read: -1
11:30:54 V/ddms: execute: returning
Installing APK 'app-debug.apk' on 'Nexus_5X_API_23(AVD) - 6.0' for app:debug
11:30:54 D/app-debug.apk: Uploading app-debug.apk onto device 'emulator-5554'
11:30:54 D/Device: Uploading file onto device 'emulator-5554'
11:30:54 D/ddms: Reading file permision of E:\ReactNative\UseMe_MobileApp\mobileApp\android\app\build\outputs\apk\debug\app-debug.apk as: rwx------
11:30:56 V/ddms: execute: running pm install -r -t "/data/local/tmp/app-debug.apk"
11:31:02 V/ddms: execute 'pm install -r -t "/data/local/tmp/app-debug.apk"' on 'emulator-5554' : EOF hit. Read: -1
11:31:02 V/ddms: execute: returning
11:31:02 V/ddms: execute: running rm "/data/local/tmp/app-debug.apk"
11:31:03 V/ddms: execute 'rm "/data/local/tmp/app-debug.apk"' on 'emulator-5554' : EOF hit. Read: -1
11:31:03 V/ddms: execute: returning
Installed on 1 device.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 33s
27 actionable tasks: 2 executed, 25 up-to-date
info Connecting to the development server...
warn Failed to connect to development server using "adb reverse": spawnSync adb ENOENT
info Starting the app...
'adb' is not recognized as an internal or external command,
operable program or batch file.
error Failed to start the app. Run CLI with --verbose flag for more details.
Error: Command failed: adb shell am start -n com.mobileapp/com.mobileapp.MainActivity
    at makeError (E:\ReactNative\UseMe_MobileApp\mobileApp\node_modules\execa\index.js:174:9)

**Comment by hemche** [comment]
`'adb' is not recognized as an internal or external command,`

Do you have ANDROID_HOME variable set up in path?

**Comment by narasimhauppala** [comment]
Put local.properties with your SDK path 
It helped me.

**Comment by bhathiyaamarasinghe** [comment]
@hemche  and @narasimhauppala Thank u for solutions

**Comment by Mactub07** [comment]
Starting with macOS Catalina, your Mac uses zsh as the default login shell and interactive shell. You can make zsh the default in earlier versions of macOS as well.
On your Mac:

Open your .zshrc file:
open ~/.zshrc
If .zshrc file not exist, you need to create one using touch & open.
touch ~/.zshrc

put to file
export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools

Save file and close
restart terminal
