### ISSUE TITLE
gradlew assembleRelease produces warnings for basic react-native app with enabled Hermes 

### ISSUE THREAD

**Issue by Merlier** [facebook/react-native#30005]
## Description
When I build APK with gradlew assembleRelease for the basic react-native app with enabled hermes, it produces some warnings during the task :app:bundleReleaseJsAndAssets. I have this output:

```
> Task :app:bundleReleaseJsAndAssets
warning: the transform cache was reset.
                 Welcome to React Native!
                Learn once, write anywhere


info Writing bundle output to:, /home/user/Projects/labapp/android/app/build/generated/assets/react/release/index.android.bundle
info Writing sourcemap output to:, /home/user/Projects/labapp/android/app/build/intermediates/sourcemaps/react/release/index.android.bundle.packager.map
info Done writing bundle output
info Done writing sourcemap output
info Copying 2 asset files
info Done copying assets
```
and then all of this warnings cut by some printed JS code:
`/home/user/Projects/labapp/android/app/build/generated/assets/react/release/index.android.bundle:13:134: warning: the variable "Promise" was not declared in function "isBoldTextEnabled"`
`/home/user/Projects/labapp/android/app/build/generated/assets/react/release/index.android.bundle:93:59152: warning: the variable "setTimeout" was not declared in function "ci"`
`/home/user/Projects/labapp/android/app/build/generated/assets/react/release/index.android.bundle:93:83915: warning: the variable "__REACT_DEVTOOLS_GLOBAL_HOOK__" was not declared in function "Ll"`
`/home/user/Projects/labapp/android/app/build/generated/assets/react/release/index.android.bundle:93:20994: warning: the variable "clearTimeout" was not declared in function " 249#"`
`/home/user/Projects/labapp/android/app/build/generated/assets/react/release/index.android.bundle:93:90529: warning: the variable "nativeFabricUIManager" was not declared in function " 287#"`
`/home/user/Projects/labapp/android/app/build/generated/assets/react/release/index.android.bundle:113:67: warning: the variable "fetch" was not declared in function " 393#"`
`/home/user/Projects/labapp/android/app/build/generated/assets/react/release/index.android.bundle:113:81: warning: the variable "Headers" was not declared in function " 393#"`
`/home/user/Projects/labapp/android/app/build/generated/assets/react/release/index.android.bundle:113:97: warning: the variable "Request" was not declared in function " 393#"`
`/home/user/Projects/labapp/android/app/build/generated/assets/react/release/index.android.bundle:113:114: warning: the variable "Response" was not declared in function " 393#"`
`/home/user/Projects/labapp/android/app/build/generated/assets/react/release/index.android.bundle:114:2045: warning: the variable "Blob" was not declared in function " 402#"`
`/home/user/Projects/labapp/android/app/build/generated/assets/react/release/index.android.bundle:114:2106: warning: the variable "FormData" was not declared in function " 402#"`
`/home/user/Projects/labapp/android/app/build/generated/assets/react/release/index.android.bundle:114:2179: warning: the variable "URLSearchParams" was not declared in function " 402#"`
`/home/user/Projects/labapp/android/app/build/generated/assets/react/release/index.android.bundle:114:7589: warning: the variable "XMLHttpRequest" was not declared in function " 409#"`
`/home/user/Projects/labapp/android/app/build/generated/assets/react/release/index.android.bundle:114:141: warning: the variable "self" was not declared in function "o 19#"`
`/home/user/Projects/labapp/android/app/build/generated/assets/react/release/index.android.bundle:135:177: warning: the variable "Worker" was not declared in function " 518#"`
`/home/user/Projects/labapp/android/app/build/generated/assets/react/release/index.android.bundle:202:106: warning: the variable "MessageChannel" was not declared in function " 719#"`
`/home/user/Projects/labapp/android/app/build/generated/assets/react/release/index.android.bundle:229:316: warning: the variable "document" was not declared in function " 843#"`
`/home/user/Projects/labapp/android/app/build/generated/assets/react/release/index.android.bundle:257:1243: warning: the variable "requestAnimationFrame" was not declared in function "value 316#"`
`/home/user/Projects/labapp/android/app/build/generated/assets/react/release/index.android.bundle:313:3162: warning: the variable "clearImmediate" was not declared in function " 1266#"`

## React Native version:
```
System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    Memory: 2.72 GB / 7.66 GB
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: v12.18.4
    Yarn: Not Found
    npm: 6.14.6
    Watchman: 4.9.0 - /home/linuxbrew/.linuxbrew/bin/watchman
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: Not Found
    Python: 2.7.18
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

## Gradlew version:
```
------------------------------------------------------------
Gradle 6.2
------------------------------------------------------------

Build time:   2020-02-17 08:32:01 UTC
Revision:     61d3320259a1a0d31519bf208eb13741679a742f

Kotlin:       1.3.61
Groovy:       2.5.8
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          11.0.8 (Ubuntu 11.0.8+10-post-Ubuntu-0ubuntu120.04)
OS:           Linux 5.4.0-48-generic amd64
```

## Steps To Reproduce

1. `$ npx react-native init labapp`
2. Edit   labapp/android/app/build.gradle and pass `enableHermes` to true
3. `$ cd labapp/android/ && ./gradlew clean && ./gradlew  assembleRelease`

Then warnings are displayed in the console and the APK is successfully build with enabled Hermes.

## Expected Results

I don't know if all of these warnings matter.
I would like to remove these warnings or at least know if I could just forget these.
 
If someone has an explanation or idea, it would be great!

Thanks

**Comment by JuriasuGit** [comment]
I have a very similiar setup and issue, except I'm on Windows 10. I also don't know if I have to worry about these warnings, but I would rather get none.

**Comment by batman-tdk** [comment]
getting the same error with hermes disabled in dev enabled variant

**Comment by freerk** [comment]
Just tried switching to hermesEnabled: true and seeing the same things.
the APK runs OK, but looks like this needs some investigation.

`System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz
    Memory: 184.67 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.20.1 - /usr/local/opt/node@12/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.10 - /usr/local/opt/node@12/bin/npm
    Watchman: 4.7.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 24, 27, 28, 29
      Build Tools: 27.0.3, 28.0.3, 29.0.2, 29.0.3
      System Images: android-17 | Google APIs Intel x86 Atom, android-22 | Google APIs Intel x86 Atom, android-24 | Intel x86 Atom, android-24 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.3/12C33 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_77 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found`

**Comment by messenja** [comment]
I have same issue. Herewith app is builded and works but some functionality does not work (hooks, fetching data)
Windows 10 x64
React Native 0.64.0
Gradle 6.7

**Comment by naishe** [comment]
Same here. Conf:

```
------------------------------------------------------------
Gradle 6.7
------------------------------------------------------------

Build time:   2020-10-14 16:13:12 UTC
Revision:     312ba9e0f4f8a02d01854d1ed743b79ed996dfd3

Kotlin:       1.3.72
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM:          1.8.0_151 (Oracle Corporation 25.151-b12)
OS:           Mac OS X 10.16 x86_64
```

Dependencies:

```
    "@react-native-async-storage/async-storage": "^1.15.2",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/native": "^5.9.4",
    "@react-navigation/stack": "^5.14.4",
    "i18next": "^20.2.1",
    "memoize-one": "^5.2.1",
    "react": "17.0.1",
    "react-i18next": "^11.8.12",
    "react-native": "0.64.0",
    "react-native-bootsplash": "^3.2.0",
    "react-native-fast-image": "^8.3.5",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-localize": "^2.0.2",
    "react-native-reanimated": "^2.1.0",
    "react-native-safe-area-context": "^3.2.0",
    "react-native-screens": "^3.0.0",
    "react-native-shimmer-placeholder": "^2.0.7",
    "react-native-svg": "^12.1.0",
    "tinycolor2": "^1.4.2"
```

Tested on `Node v14.17.0` and `v12.18.2`. Same result.

**Comment by jsjain** [comment]
Its been almost a year, still gettimg same warnings :(

**Comment by rassemdev** [comment]
I am also getting this error.

**Comment by lffloyd** [comment]
Same here on ```react-native==0.67.4```, ```hermes-engine==0.9.0``` and ```node==12.22.3```

**Comment by mohity777** [comment]
i am facing these warnings in release build after upgrading to 0.71.6
