### ISSUE TITLE
react-native0.62.0升级到0.63.2问题

### ISSUE THREAD

**Issue by TianShun2018** [facebook/react-native#30009]
React Native版本：
System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Memory: 56.49 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.4.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5977832
    Xcode: 12.0/12A7209 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
    react-native-macos: Not Found
-----------------------------------------------------------------------------------------------------------
描述
 Warning: Picker has been extracted from react-native core and will be removed in a future release. It can now be installed and imported from '@react-native-community/picker' instead of 'react-native'. See https://github.com/react-native-community/react-native-picker
[Wed Sep 23 2020 09:19:50.440]  ERROR    TypeError: Super expression must either be null or a function
[Wed Sep 23 2020 09:19:50.450]  ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
[Wed Sep 23 2020 09:19:50.460]  ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)

**Comment by TianShun2018** [comment]
> ⚠️	缺少环境信息
> ℹ️	您的问题可能缺少有关您的开发环境的信息。您可以通过`react-native info`在控制台中运行来获取缺少的信息。

System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Memory: 56.49 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.4.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5977832
    Xcode: 12.0/12A7209 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by songxiaoliang** [comment]
@TianShun2018 你好，请问如何解决呀？

**Comment by TianShun2018** [comment]
> @TianShun2018 你好，请问如何解决呀？

React Native Upgrade Helper
按照这里面改，改完之后删代码排除出来的问题，我的是ant-design的问题引起的，升级了之后补了几个依赖就好了

**Comment by songxiaoliang** [comment]
@TianShun2018 是由什么代码引起的？我这边依赖比较多

**Comment by TianShun2018** [comment]
> @TianShun2018 是由什么代码引起的？我这边依赖比较多

只能删代码自己排查了

**Comment by songxiaoliang** [comment]
@TianShun2018 太难了，也不知道RN官方有没有更好的办法来解决这个问题

**Comment by TianShun2018** [comment]
> @TianShun2018 太难了，也不知道RN官方有没有更好的办法来解决这个问题

没有，只能自己去排查

**Comment by songxiaoliang** [comment]
@TianShun2018 只要把所有 extends TouchableOpactity 这个换成 Component，就可以了吗？别的地方不需要改把？

**Comment by KDBINMC17** [comment]
same issue
