### ISSUE TITLE
Unresolved warning ITMS-90809: Deprecated API Usage for UIWebView on iOS with RN 0.6x

### ISSUE THREAD

**Issue by BinhTNT** [facebook/react-native#30006]
Hello,

I know i'm opening a duplicate issue that is because my case is different from other closed issues. I have followed the solutions from old issues but it did not help. I even removed the dependencies that are possible to cause the UIWebView warning from my project including  **react-native-fbsdk**,  **react-native-fbsdk**, **react-native-webview**.
Beside, when I tried to run: **"grep -r UIWebView node_modules/"**
it show me the result which looks like there is nothing related to UIWebView:

_node_modules//jsc-android/dist/include/JSContextPrivate.h:/*! @abstract The delegate the context will use when trying to load a module. Note, this delegate will be ignored for contexts returned by UIWebView. */
node_modules//ua-parser-js/test/browser-test.json:        "ua"      : "Mozilla/5.0 (iPhone; CPU iPhone OS 10_0_2 like Mac OS X) AppleWebKit/602.1.50 (KHTML, like Gecko) Mobile/14A456 QQ/6.5.3.410 V1_IPH_SQ_6.5.3_1_APP_A Pixel/1080 Core/UIWebView NetType/WIFI Mem/26",
node_modules//fbjs/lib/UserAgent.js.flow:   * - UIWebView
node_modules//fbjs/lib/UserAgent.js:   * - UIWebView
node_modules//create-react-class/node_modules/fbjs/lib/UserAgent.js.flow:   * - UIWebView
node_modules//create-react-class/node_modules/fbjs/lib/UserAgent.js:   * - UIWebView_

Also, by running **"grep -r UIWebView ios/Pods/**
I got no result for UIWebView in native libraries.

It's really weird in my case. Anyone could please help me!

Environment Information:
_System:
    OS: macOS 10.15.5
    CPU: (4) x64 Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
    Memory: 343.86 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.18.0 - /usr/local/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 23.0.1, 28.0.3, 29.0.2, 29.0.3
      System Images: android-22 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_211 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
  npmGlobalPackages:
    *react-native*: Not Found_

All my project's dependencies:

"@babel/plugin-proposal-decorators": "^7.10.4",
    "@bugfender/rn-bugfender": "^1.1.3",
    "@invertase/react-native-apple-authentication": "^1.1.2",
    "@react-native-community/art": "^1.2.0",
    "@react-native-community/async-storage": "^1.11.0",
    "@react-native-community/datetimepicker": "^2.6.0",
    "@react-native-community/google-signin": "^4.0.3",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-community/netinfo": "^5.9.5",
    "@react-native-community/picker": "^1.7.1",
    "@react-native-community/push-notification-ios": "^1.3.0",
    "@react-native-community/slider": "^3.0.3",
    "@react-native-firebase/analytics": "^7.3.1",
    "@react-native-firebase/app": "^8.2.0",
    "@react-native-firebase/crashlytics": "^8.1.2",
    "@react-native-firebase/messaging": "^7.4.2",
    "@react-native-firebase/remote-config": "^7.2.2",
    "@react-navigation/bottom-tabs": "^5.7.3",
    "@react-navigation/core": "^3.5.2",
    "@react-navigation/native": "^5.7.1",
    "@react-navigation/stack": "^5.8.0",
    "@youngtailors/react-native-spring-scrollview": "^2.1.0-rc.4",
    "axios": "^0.19.2",
    "base64-js": "^1.3.1",
    "crypto-js": "3.3.0",
    "d3-array": "^2.4.0",
    "d3-interpolate-path": "^2.2.1",
    "d3-scale": "^3.2.1",
    "d3-shape": "^1.3.7",
    "immutable": "^4.0.0-rc.12",
    "lodash": "^4.17.19",
    "lodash.get": "^4.4.2",
    "lodash.isequal": "^4.5.0",
    "qs": "^6.9.4",
    "react": "16.13.1",
    "react-native": "0.63.2",
    "react-native-android-location-enabler": "^1.2.1",
    "react-native-background-timer": "^2.2.0",
    "react-native-ble-plx": "^2.0.1",
    "react-native-circular-progress": "^1.3.6",
    "react-native-dark-mode": "^0.2.2",
    "react-native-device-info": "^5.6.2",
    "react-native-device-time-format": "^2.3.0",
    "react-native-fbsdk": "^2.0.0",
    "react-native-firebase-test-lab": "0.0.2",
    "react-native-fs": "^2.16.6",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-gps-state": "^2.0.3",
    "react-native-htmlview": "^0.15.0",
    "react-native-iphone-x-helper": "^1.2.1",
    "react-native-keep-awake": "^4.0.0",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-localization": "^2.1.6",
    "react-native-md5": "^1.0.0",
    "react-native-mixpanel": "^1.2.0",
    "react-native-modal": "^11.5.6",
    "react-native-modal-datetime-picker": "^8.7.1",
    "react-native-orientation": "^3.1.3",
    "react-native-progress": "^4.1.2",
    "react-native-push-notification": "^4.0.0",
    "react-native-reanimated": "^1.10.1",
    "react-native-safe-area-context": "^3.1.1",
    "react-native-screens": "^2.9.0",
    "react-native-snackbar-component": "^1.1.10",
    "react-native-svg": "^12.1.0",
    "react-native-unity-view-reinvented": "^1.4.2",
    "react-native-user-inactivity": "^1.1.0",
    "react-native-webview": "^10.3.3",
    "react-native-wheel-picker-android": "^2.0.6",
    "react-redux": "^7.2.0",
    "redux": "^4.0.5",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.3.0",
    "xdate": "^0.8.2"

Thanks,
Binh

**Comment by keremoge** [comment]
I'm facing the same problem

using RN **0.62.2**
