### ISSUE TITLE
Simulator can see image and Actual device can't see image in iOS 14

### ISSUE THREAD

**Issue by jhui134** [facebook/react-native#30016]
solved it through #29279 but it doesn't work in Actual device...

     <View style={{ flex: 1 }}>
                    <ImageBackground
                        source={require('App/Assets/Images/FriendInvite/topBanner.png')}
                        style={{ width: '100%', height: '100%' }}
                    >
                        <Text>hello</Text>
                    </ImageBackground>
     </View>

System:
    OS: macOS 10.15.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 3.73 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.5.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 27, 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3
      System Images: android-28 | Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-29 | Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 12.0/12A7209 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_252 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: 4.13.0 => 4.13.0 
    react: ^16.13.1 => 16.13.1 
    react-native: ^0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by Biplovkumar** [comment]
plz follow this link [https://github.com/facebook/react-native/issues/29279#issuecomment-658244428](url). for below 0.63 versions.
it is solved in react native 0.63 versions.

**Comment by hakkikonu** [comment]
upgrade to 0.63.2
