### ISSUE TITLE
CocoaPods could not find compatible versions for pod "Folly"

### ISSUE THREAD

**Issue by huynhbinh06** [facebook/react-native#30015]
Hi guys, I have the problem trying to run the command "pod install". This is my issue. Anyone help me? Thanks a lots!
![image](https://user-images.githubusercontent.com/56378921/94094923-de5ea100-fe4a-11ea-805a-fb7553d72c6d.png)

**Comment by s1ro6** [comment]
Try the code prompted by the pod.
`pod update Folly --no-repo-update`

**Comment by huynhbinh06** [comment]
> Try the code prompted by the pod.
> `pod update Folly --no-repo-update`
Thanks sir, worked!

**Comment by chrisglein** [comment]
You closed and reopened but based on your comment I assume this is resolved.

**Comment by subhani-ali** [comment]
> Try the code prompted by the pod.
> `pod update Folly --no-repo-update`

Thanks Issue resolved!

> after apply the code new error 
       'UMReactNativeAdapter/UMModuleRegistryAdapter.h' file not found
