### ISSUE TITLE
Background alpha in Android is not correct

### ISSUE THREAD

**Issue by maraujop** [facebook/react-native#3001]
In Android the text seems to be wrapped in a darker background, when using a background alpha. This works correctly in iOS but not in Android, see example app:
https://rnplay.org/apps/SQzlDw

**Comment by andreicoman11** [comment]
Good find! This was indeed a bug in our implementation of text and text input. There's a fix out for review, should be committed soon.

**Comment by maraujop** [comment]
Thanks @andreicoman11 happy to hear that

**Comment by andreicoman11** [comment]
Fixed in https://github.com/facebook/react-native/commit/3b6d029a55efe1ffa5afcafe60d2d2445aadd502
