### ISSUE TITLE
Unable to find a specification for `React-Core` depended upon by `RNPermissions`

### ISSUE THREAD

**Issue by Ashishlog9** [facebook/react-native#30018]
## Description
After running pod install i am getting this error .  Tried with pod update , pod repo update still no luck .
[!] Unable to find a specification for `React-Core` depended upon by `RNPermissions`

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

My pod file code 
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ESA' do
  pod 'AppCenter/Crashes', '~> 1.14.0'
  pod 'AppCenter/Analytics', '~> 1.14.0'
  pod 'AppCenterReactNativeShared', '~> 1.13.0'
  rn_path = '../node_modules/react-native'
  rn_maps_path = '../node_modules/react-native-maps'

  # See http://facebook.github.io/react-native/docs/integration-with-existing-apps.html#configuring-cocoapods-dependencies
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'CxxBridge',
    'RCTActionSheet',
    'DevSupport',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'ART'
  ]
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  #use_frameworks!

  # Pods for ESA
  # React Native third party dependencies podspecs
  pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
  pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"
  # If you are using React Native <0.54, you will get the following error:
  # "The name of the given podspec `GLog` doesn't match the expected one `glog`"
  # Use the following line instead:
  #pod 'GLog', :podspec => "#{rn_path}/third-party-podspecs/GLog.podspec"
  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"

  # react-native-maps dependencies
  pod 'react-native-maps', path: rn_maps_path
  pod 'react-native-google-maps', path: rn_maps_path  # Uncomment this line if you want to support GoogleMaps on iOS
  pod 'GoogleMaps'  # Uncomment this line if you want to support GoogleMaps on iOS
  pod 'Google-Maps-iOS-Utils' # Uncomment this line if you want to support GoogleMaps on iOS
  pod 'AdobeMobileSDK', '~> 4.14.1'
  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'

  #added
  permissions_path = '../node_modules/react-native-permissions/ios'

  pod 'Permission-Calendars', :path => "#{permissions_path}/Calendars.podspec"
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
  pod 'Permission-FaceID', :path => "#{permissions_path}/FaceID.podspec"
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways.podspec"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse.podspec"
  pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone.podspec"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary.podspec"
  pod 'Permission-SpeechRecognition', :path => "#{permissions_path}/SpeechRecognition.podspec"

  pod 'react-native-calendar-events', :path => '../node_modules/react-native-calendar-events'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'ReactNativeKeyboardManager', :path => '../node_modules/react-native-keyboard-manager'

  pod 'react-native-passkit-wallet', :path => '../node_modules/react-native-passkit-wallet'

  pod 'TouchID', :path => '../node_modules/react-native-touch-id'

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'
  
  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  pod 'RNReactNativeDocViewer', :path => '../node_modules/react-native-doc-viewer'

  pod 'NewRelicAgent', '~> 5.12.0'

  pod 'react-native-adjust', :path => '../node_modules/react-native-adjust'

  # pod 'react-native-config', :path => '../node_modules/react-native-config'

end
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'react-native-config'
      phase = target.project.new(Xcodeproj::Project::Object::PBXShellScriptBuildPhase)
      phase.shell_script = "cd ../../"\
                           " && RNC_ROOT=./node_modules/react-native-config/"\
                           " && export SYMROOT=$RNC_ROOT/ios/ReactNativeConfig"\
                           " && ruby $RNC_ROOT/ios/ReactNativeConfig/BuildDotenvConfig.ruby"

      target.build_phases << phase
      target.build_phases.move(phase,0)
    end
    if target.name == 'react-native-google-maps'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end
    if target.name == "React"
      target.remove_from_project
    end
    if target.name == "yoga"
      target.remove_from_project
    end
  end
end

## React Native version:
Run `react-native info` in your terminal and copy the results here.

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.
2.

## Expected Results
It should install pod library.

**Comment by Heru6664** [comment]
I've same issue

**Comment by Ashishlog9** [comment]
I am suffering from this issue since three days . its like hell

**Comment by deejayxd07** [comment]
Try adding this on your Podfile:

```
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
```

Like so:


```
target 'yourAppNameHere' do
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways.podspec"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse.podspec"

  target 'yourAppNameHereTests' do
    inherit! :complete
    # Pods for testing
  end

  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
end
```

**Comment by Ashishlog9** [comment]
After adding this i am getting syntax error ;

[!] Invalid `Podfile` file: syntax error, unexpected keyword_end, expecting end-of-input.

 #  from /Users/728583/Desktop/reactworkspace/MA_new326_1/ESA/ios/Podfile:124
 #  -------------------------------------------
 #  use_react_native!(:path => config[rn_path])
 >  end

**Comment by Ashishlog9** [comment]
See the error i got 
[!] Invalid `Podfile` file: undefined method `use_native_modules!' for #<Pod::Podfile:0x00007f9232beb970>
Did you mean?  use_modular_headers!.

Here is my POD file 
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ESA' do
  pod 'AppCenter/Crashes', '~> 1.14.0'
  pod 'AppCenter/Analytics', '~> 1.14.0'
  pod 'AppCenterReactNativeShared', '~> 1.13.0'
  rn_path = '../node_modules/react-native'
  rn_maps_path = '../node_modules/react-native-maps'

  # See http://facebook.github.io/react-native/docs/integration-with-existing-apps.html#configuring-cocoapods-dependencies
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'CxxBridge',
    'RCTActionSheet',
    'DevSupport',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'ART'
  ]
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  #use_frameworks!

  # Pods for ESA
  # React Native third party dependencies podspecs
  pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
  pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"
  # If you are using React Native <0.54, you will get the following error:
  # "The name of the given podspec `GLog` doesn't match the expected one `glog`"
  # Use the following line instead:
  #pod 'GLog', :podspec => "#{rn_path}/third-party-podspecs/GLog.podspec"
  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"

  # react-native-maps dependencies
  pod 'react-native-maps', path: rn_maps_path
  pod 'react-native-google-maps', path: rn_maps_path  # Uncomment this line if you want to support GoogleMaps on iOS
  pod 'GoogleMaps'  # Uncomment this line if you want to support GoogleMaps on iOS
  pod 'Google-Maps-iOS-Utils' # Uncomment this line if you want to support GoogleMaps on iOS
  pod 'AdobeMobileSDK', '~> 4.14.1'
  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'

  #added
  permissions_path = '../node_modules/react-native-permissions/ios'

  pod 'Permission-Calendars', :path => "#{permissions_path}/Calendars.podspec"
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
  pod 'Permission-FaceID', :path => "#{permissions_path}/FaceID.podspec"
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways.podspec"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse.podspec"
  pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone.podspec"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary.podspec"
  pod 'Permission-SpeechRecognition', :path => "#{permissions_path}/SpeechRecognition.podspec"

  pod 'react-native-calendar-events', :path => '../node_modules/react-native-calendar-events'


  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'ReactNativeKeyboardManager', :path => '../node_modules/react-native-keyboard-manager'

  pod 'react-native-passkit-wallet', :path => '../node_modules/react-native-passkit-wallet'

  pod 'TouchID', :path => '../node_modules/react-native-touch-id'

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'
  
  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  pod 'RNReactNativeDocViewer', :path => '../node_modules/react-native-doc-viewer'

  pod 'NewRelicAgent', '~> 5.12.0'

  pod 'react-native-adjust', :path => '../node_modules/react-native-adjust'

  # pod 'react-native-config', :path => '../node_modules/react-native-config'

end
config = use_native_modules!

use_react_native!(:path => config[rn_path])


post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'react-native-config'
      phase = target.project.new(Xcodeproj::Project::Object::PBXShellScriptBuildPhase)
      phase.shell_script = "cd ../../"\
                           " && RNC_ROOT=./node_modules/react-native-config/"\
                           " && export SYMROOT=$RNC_ROOT/ios/ReactNativeConfig"\
                           " && ruby $RNC_ROOT/ios/ReactNativeConfig/BuildDotenvConfig.ruby"

      target.build_phases << phase
      target.build_phases.move(phase,0)
    end
    if target.name == 'react-native-google-maps'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end
    if target.name == "React"
      target.remove_from_project
    end
    if target.name == "yoga"
      target.remove_from_project
    end
  end
end

**Comment by elabayoub** [comment]
No clue yet ?

**Comment by elabayoub** [comment]
Had similar issue : 

> [!] Unable to find a specification for `React-Core` depended upon by `react-native-config/App`

updated my package.json -] changed `"react-native-config": "github:luggit/react-native-config", TO "react-native-config": "1.0.0",`

And my Pod file :

`pod 'react-native-config', path: '../node_modules/react-native-config'`

Re-run `npm install `
Re-run `npm run ios:pod:install`

**Comment by ofgowtham** [comment]
I had to change `"react-native-permissions": "^2.0.0"` to `"react-native-permissions": "2.0.0"` in my package.json. And removed node_modules then npm install. I ran the pod install. It worked. 
PS: Make sure you have this `pod 'RNPermissions', :path => '../node_modules/react-native-permissions'` in your Podfile.

**Comment by ZakeryFyke** [comment]
I fixed this by opening the podspec file for react native permissions (in the node modules folder, under react-native-permissions, called RNPermissions.podspec) and replacing the line

`s.dependency       "React-Core"`

with

`s.dependency        "React/Core"`

**Comment by ketan-kumar** [comment]
Uninstalled node_modules and rebuilding pods worked for me.
