### ISSUE TITLE
react-native run-ios command not working after xcode Update 12

### ISSUE THREAD

**Issue by hussainahmad** [facebook/react-native#30028]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
When ever I try to run IOS App with command `react-native run-ios` it throwing error after updating xcode 12. before it was working fine. Only I can run app through xcode, with Xcode some time it doesn't reflect the updated code.

`Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier /Users/macbook/Library/Developer/Xcode/DerivedData/MyApplication-daaztfbfqwsmqcctibnckcnmctga/Build/Products/Debug-iphonesimulator/MyApplication.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist`

    at checkExecSyncError (child_process.js:630:11)
    at Object.execFileSync (child_process.js:648:15)
    at runOnSimulator (/Users/macbook/Desktop/hussain/MyApplication/node_modules/@react-native-community/cli-platform-ios/build/commands/runIOS/index.js:191:45)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Command.handleAction (/usr/local/lib/node_modules/@react-native-community/cli/build/cliEntry.js:160:7) 

## React Native version:
System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz
    Memory: 23.22 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.3 - /usr/local/bin/node
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 23, 24, 27, 28, 29, 30
      Build Tools: 23.0.1, 23.0.3, 24.0.1, 28.0.3, 29.0.0, 29.0.1, 29.0.2, 29.0.3
      System Images: android-23 | Intel x86 Atom, android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-28 | Android TV Intel x86 Atom, android-28 | Wear OS Intel x86 Atom, android-28 | Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-Q | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.0/12A7209 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.1 => 0.63.1 
  npmGlobalPackages:
    generator-react-native-ignite: 1.13.0
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
    react-native-ignite: 1.13.0

**Comment by bidetaggle** [comment]
Look similar to #29975, although I do not have any error but the app doesn't launch on device.

**Comment by Tyki** [comment]
Facing the same issue since the update to xCode

**Comment by worldzb** [comment]
you can try
`
yarn remove react-native
yarn add react-native
`
or remove yarn.lock and re-install dependencies

**Comment by nbastoWM** [comment]
Facing the same issue. 
I have RN 0.62.1 so If I remove and add react-native, the project doesn't run also because of the RN version incompatibility.
Tried to remove derived data, node_modules and yarn.lock but the error continues.
Also tried to clone again my project and reinstall pods and packages but with no success.

**Comment by sangameshrently** [comment]
@nbastoWM : Try this, Remove yarn lock file or package.lock file then delete pod lock file,  install pod once again . your app should run now.

**Comment by nbastoWM** [comment]
Of course, silly me, that's what I missed! 
I had to remove yarn.lock and do a pod-install AFTER!
That's working now, thanks!

**Comment by hussainahmad** [comment]
@nbastoWM Thanks Mate, Its working

**Comment by cvharris** [comment]
Still seeing the same issue, deleting the package.lock and Podfile.lock and reinstalling did not fix the issue.

**Comment by kierandesmond** [comment]
For me, when I publish a build, the images are missing on some devices. Very strange and frustrating as I'm sharing it with my team and they report that images are not loading. Trying the yarn.lock and pod install suggestion now.

**Comment by hussainahmad** [comment]
@kierandesmond please check #29990 , hope this will solve your issue
