### ISSUE TITLE
Android Studio, React Native, and Gradle: "Build failed with an exception." - java.lang.Exception (no error message)

### ISSUE THREAD

**Issue by Endarire** [facebook/react-native#30025]
## EDIT 9 28 20
I have updated the thread with comments below which are intended to aid in diagnosing and debugging.

## SITUATION
Greetings, all!

I am a coder for a startup company on a seemingly unannounced project; thus, this code base is private.  The previous people in charge of this code base left me with this code and assumed it would work for me.  It has not.

(Also, the GitHub Bot for this post had me use react-native info on my command line.  Doing so tells me info (and -info and --info) are unrecognized commands.)

## Description

I have tried researching this problem and others online, often asking for help in various places (Discord, Slack, Reddit, StackOverflow, and more) with varying degrees of success.  So far, this set of errors has stumped me.  I'm unsure if this is an error with React Native, since I've tried various things (altering the project structure settings, changing things around in code, starting over with an older version of the code base and experimenting, running this on a Mac, running this on another Mac, etc.) and I've frequently received errors about React Native.

## React Native Version
I also have Expo installed, but I'm unsure if our project uses it.

Expo: 3.27.4
React Native: 0.63.2
React Native CLI: 2.0.1

## Steps To Reproduce
1: Run my (ahem) private code base.
2: Witness the error message.

## Expected Results
I expected the code to run without an error (very preferably) OR the code to generate amply descriptive error/warning messages to aid my research (secondarily).

*What do the error messages in the log below mean and how should they be fixed?*

## Snack, code example, screenshot, or link to a repository:
Debug Error Log
https://docs.google.com/document/d/1r246_4jNP6FYzFbsEvRgLdbI9sJiktd5Y0N64O0-SGI/edit?usp=sharing

All confidential information from this log has been altered or removed.  The error messages are highlighted in red and info messages are highlighted in blue for ease of use.

## Finally for Now
Thankee for your aid!

**Comment by Endarire** [comment]
Updated.

**Comment by bidetaggle** [comment]
Hi,
If the output `react-native info` is exactly `unrecognized command`, I assume that react-native is simply not installed on your system.
Do you try to build it through Android Studio or a terminal command line? Did you `npm install` at the root of your project folder?

**Comment by Endarire** [comment]
I did npm i (AKA npm install) at the root of this project, as well as npm audit fix.  There was also a yarn lock, meaning I also installed yarn and ran yarn.

Using react-native -v in the project directory shows the appropriate versions (2.0.1 for RN CLI and 0.63.2 for RN).

**Comment by bidetaggle** [comment]
yarn and npm serve the same purpose, you should pick one and stick with it. Remove either `yarn.lock` or `package-lock.json` from your project depending on your choice.

Could you provide the command you use to build your project.

**Comment by Endarire** [comment]
As mentioned in the linked Google Doc, I used --scan --debug.  (I also ran this from Android Studio in Debug Mode; hence, the --debug.)

**Comment by bidetaggle** [comment]
> To clarify, this code base was given to me with yarn.lock and package-lock.json.

Probably multiple developers used both before and and didn't clean it up. It's better to use only one package manager if you don't want headache in the future.

As I can see, this path `F:\hornet\9-1-20\node_modules\react-native\node_modules\@react-native-community\cli\build\bin.js` looks wrong to me as you have the `node_modules` folder sitting in `node_modules\react-native`. This may explains the `Unexpected empty result` if the path is wrong.

`--scan` and `--debug` seem to be a command's parameters. I guess it is the output from Android Studio when you click on the build button. Did you try to run `npx react-native run-android` in the terminal from your project's root directory?
Sorry I'm not used to windows so I may not be able to help more than that.

**Comment by Endarire** [comment]
**NOTE**
I ran the suggested command (npx react-native run-android) from my Windows command prompt and received the below errors, regardless of whether I used the normal permissions or the superuser permissions, and regardless of where in the project I ran it.

**COMMAND EXECUTION AND ERROR MESSAGE**
F:\hornet\9-1-20>npx react-native run-androidnpx react-native run-android

error Failed to load configuration of your project. Run CLI with --verbose flag for more details.
TypeError: this.compile is not a function
    at module.exports.internals.Any.root.validate (F:\hornet\9-1-20\node_modules\@hapi\joi\lib\index.js:143:29)

**Comment by Endarire** [comment]
Something's also been amiss with my Gradle, since attempting to update versions from 6.0.1 to the latest (6.6.1d as of this writing) has resulted in more errors!  More details:

https://docs.google.com/document/d/1-2XdmzkUWHPprIXW4iTj27tW9bNCZruz3TdgJfNM5tU/edit?usp=sharing

Thankee for your aid!

**Comment by Endarire** [comment]
After deleting the node_modules directory and reinstalling the node modules via npm i.  The code builds now but hasn't run, perhaps due to depricated functionality or version differences.

https://docs.google.com/document/d/1mWprISb_XL-Q-2pKl9qKGK7BIi5ftyjQyP9XFyRNqbo/edit?usp=sharing

**Comment by Endarire** [comment]
@bidetaggle 
Thankee again for your previous assistance!

What new and relevant insights do you have regarding this situation?

**Comment by Endarire** [comment]
Today I mass replaced compile with api with these results:

https://docs.google.com/document/d/1SPi86a0KHIOCiKjK2WBU0ydsBSG3Nwzu1E7GqrZw6tk/edit?usp=sharing

**Comment by bidetaggle** [comment]
Hi mate,

I recommend you to copy/paste only the error using `markup language` and not the whole stack trace. You'll attract more easily views and potential solutions from other people that may have the answer.

A radical way to solve your problem could be to simply start a new app from scratch with `npx react-native init yourAppName` then make sure that it builds and run by going into the new `yourAppName` folder and launch `npx react-native run-android`.

Once this step is working, copy/paste the files from the legacy code you got into this fresh react-native folder. Also do not forget to replace the `package.json` file and give it a `npm install`

Once the app build but you're facing red background's errors on the running device, you'll be able to narrow down the different dependency and breaking change issues, until you finally see your app in action 👍

You can dm me, I'll be happy to help

**Comment by Endarire** [comment]
@bidetaggle 
Thankee!

Since you said directly messaging you was a handy way to contact you.  What are the best platforms to do this on?  What user names do you use per platform?

**Comment by bidetaggle** [comment]
Hello, you can send me a message on my profile's email bidetaggle@elektr.io , from there we can see if we need other means of communication to solve your problem :)

**Comment by chrisglein** [comment]
While I appreciate that you said you've tried reaching out in other forums and haven't had luck, this isn't the right venue for this discussion. This repo is for issues with core React Native. If you can reduce your private repo into a minimal repro that demonstrates an issue then that would be appropriate to log here.
