### ISSUE TITLE
[RN v0.63.2] Xcode keeps archiving old version.

### ISSUE THREAD

**Issue by tronxdev** [facebook/react-native#30024]
## Environment:

- React Native v0.63.2

- Xcode v11.6 (11E708)

- Mac OS Catalina v10.15.6

## Problem

I could see the current version when I built my app on Xcode(*.xcworkspace). Now I need to build .ipa file for test users. When I archived the project on Xcode(*.xcworkspace) and installed .ipa on my phone, the app was old version. I tried with Xcode v12.0 and had the same issue. 

## Question

- How can I stop Xcode from archiving old version app?

- How can I archive the current version?

**Comment by deejayxd07** [comment]
Hi @proIT324, have you tried cleaning your build?

On Xcode you can go to `Product -> Clean Build Folder` or just use the shortcut which is `cmd + shift +k`

**Comment by selimsevencan** [comment]
I encountered this problem too and I tried these ones =>

Add this one to the `package.json's scripts`

`"build:ios": " react-native bundle --entry-file index.js --platform ios --dev false --bundle-output ios/main.jsbundle --assets-dest ios"`

After that run it from the terminal. I hope it will work for you too.

**Comment by Anzormumladze** [comment]
delete Pods and podfile.lock then install pod
go on xcode and clean build folder,After that press  Product -> Achive

**Comment by macfam** [comment]
The solution from @selimsevencan worked for me. 

I added the new script, and ran:

`npm run build:ios` 

Thanks!

**Comment by duxetech** [comment]
I'm also facing the same issue.
I am running react native project on Xcode. It builds successfully on debug. However when I run on Release mode or archive it for submitting to appstore, it builds old version.
Xcode : 12, RN : 0.63.2
I tried all the options possible like clearing cache, deleting folders, starting from scratch, reinstalling etc. None of them worked!
Any other suggestion ?
