### ISSUE TITLE
Getting a weird number for timestamp in onTouchStart, onTouchMove, onTouchEnd events of View

### ISSUE THREAD

**Issue by jakallergis** [facebook/react-native#30023]
## Description
Consider the following code:
```tsx
const log = (e) => console.log(e.nativeEvent.timestmap, Date.now())
return (
    <View
        onTouchStart={onTouchStart}
        onTouchMove={onTouchMove}
        onTouchEnd={onTouchEnd}>
        {props.children}
    </View>
)
```

### Results:
- On iOS simulator (iOS 14) the event logged `192388424.34784204` while at the same point in time  `Date.now()` logged `1600799061368`.
- On an actual iPhone (iOS 14) the event logged `66961920.69195832` while at the same point in time `Date.now()` logged `1600795025203`
- On an actual Android device (Android 10, Xiaomi Mi A2) the event logged `262563274` while at the same point in time `Date.now()` logged `1600955638331`

### Questions
- What does the event's timestamp represent? It's clearly not an epoch timestamp. Right?
- Is it ticks? Doesn't seem to be ticks because none of the methods I found online to convert ticks to epoch dates worked.
- How can I get the event's timestamp `192388424.34784204` and know when in time this event happened?

## React Native version:
```sh
System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 297.70 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.1 - ~/.nvm/versions/node/v12.18.1/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v12.18.1/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v12.18.1/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0.1 4.0.1
    Xcode: 12.0/12A7209 - /usr/bin/xcodebuild
  Languages:
    Java: 14.0.1 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.2 => 0.63.2
  npmGlobalPackages:
    *react-native*: Not Found
```

PS: This also happens to a `0.62` react-native project. 

## Steps To Reproduce
1. Add a `View` component somewhere in any codebase
2. Use any the `onTouchStart`, `onTouchMove`, `onToucheEnd` props on that component
3. Log the `event.nativeEvent.timestamp` and a `Date.now()` in the callback.
4. Observe the difference in the numbers. `Date.now()` is clearly an epoch date - the other one isn't

## Expected Results
The `event.nativeEvent.timestamp` should be an epoch date or something that can be turned into an epoch date.

## Snack, code example, screenshot, or link to a repository:
```tsx
const log = (e) => console.log(e.nativeEvent.timestmap, Date.now())
return (
    <View
        onTouchStart={onTouchStart}
        onTouchMove={onTouchMove}
        onTouchEnd={onTouchEnd}>
        {props.children}
    </View>
)
```

**Comment by jakallergis** [comment]
Nope it hasn't been fixed

**Comment by sbearben** [comment]
I don't have an answer, but as far as I know here lies the Android code:
https://github.com/facebook/react-native/blob/4804e682388e40b82fb4a39fea256b3002a0aba6/ReactAndroid/src/main/java/com/facebook/react/uimanager/events/TouchesHelper.java#L67
https://github.com/facebook/react-native/blob/4804e682388e40b82fb4a39fea256b3002a0aba6/ReactAndroid/src/main/java/com/facebook/react/uimanager/events/Event.java#L110

**Comment by Jackman3005** [comment]
So what are these timestamps on iOS? What are they on Android now? I'm super confused...

**Comment by Jackman3005** [comment]
I want to know how to compare two different events timestamps to determine how much time has passed. How should I do this? On web, it's simple and uses the traditional epoch ms number. iOS shows some strange decimal format: `2829761.919135`...
