### ISSUE TITLE
TypeError: undefined is not an object (evaluating ...)

### ISSUE THREAD

**Issue by peterrz** [facebook/react-native#30038]
## Description
Passing data params to another components and unfortunately i face this error `TypeError: undefined is not an object (evaluating 'this.state.dataset.Image[0]')`, while i run ` console.log(this.state.dataset);` the data is there but i can't reach them.
I set a condition in render and it makes me access the data ` if (this.state.dataset && this.state.dataset)`,
would you please give me more info about this error. thanks

## React Native version:
System:
    OS: Linux 4.15 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i5-3570 CPU @ 3.40GHz
    Memory: 165.87 MB / 7.67 GB
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
    Yarn: Not Found
    npm: 6.14.8 - ~/react/SEC/node_modules/.bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 23, 28, 29
      Build Tools: 23.0.1, 28.0.3, 29.0.2, 29.0.3
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 1.8.0_252 - /usr/bin/javac
    Python: 2.7.17 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
1.`render() { 
console.log(this.state.dataset.Image[0].Src)
...} `

## Expected Results
accessing to data
## Extra information
the data JSON I passed is: 
`[
     {
"Available": true,
 "Discriptions": [[Object], [Object]], 
 "Image": [
                    {
                        "Src": "/Uploads/News/590068041036526-1599664273.jpg"
                    }
, "added_date": "2020-09-19T19:30:00.000Z"
   }
]
`
my components:
```
export default class Detail extends Component {
  constructor(props) {
    super(props);
    this.state = {
      dataset:'',
    }
        }     
  async componentDidMount(){

       this.setState({
        dataset: this.props.router.params.data,
             });
    
    }
    render() {
        console.log(this.state.dataset.Image[0].Src)
        .
        . 
        }
```

>  ERROR    TypeError: undefined is not an object (evaluating 'this.state.dataset.Image[0]')

Then I set this condition and I could access the data
` if (this.state.dataset && this.state.dataset){
        console.log(this.state.dataset.Image[0].Src)
        }`
I could not understand it.
```
export default class Detail extends Component {
  constructor(props) {
    super(props);
    this.state = {
      dataset:'',
    }
        }     
  async componentDidMount(){

       this.setState({
        dataset: this.props.router.params.data,
             });
    
    }
    render() {
    if (this.state.dataset && this.state.dataset){
        console.log(this.state.dataset.Image[0].Src)
        .
        . 
        }
```

**Comment by wmonecke** [comment]
This question is better suitable for StackOverflow instead of a react-native issue.
But looking at your code you are trying to access a string since when render is called this.state.dataset is `''` and you cant access `Image` of an empty string. componentDidMount runs after the initial render. That means your code is not even getting there.

**Comment by peterrz** [comment]
@wmonecke Thank you, my mind was around the condition.
