### ISSUE TITLE
Images don't display

### ISSUE THREAD

**Issue by davidarnaub7** [facebook/react-native#30030]
I have to modify RCTImageView Animated.m for displaying images. If I don't, images are not displayed.
This happens since I updated to ios 14.

Here is a post where explain how to correct the bug, but it is a temporally correction because each time I make a pod instalation the correction disappear going back to the original code.

I let the url: https://stackoverflow.com/questions/62612812/all-image-fast-image-in-react-native-app-not-working-on-ios-14-beta-and-xcode-12

**Comment by Ghulamhaider12** [comment]
System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 92.27 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.4.0 - /usr/local/bin/node
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 27, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.0
      System Images: android-30 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5

**Comment by Ghulamhaider12** [comment]
same issue i am facing

**Comment by Naturalclar** [comment]
seems like a duplicated issue of #29279
