### ISSUE TITLE
iOS 14 Picture does not show

### ISSUE THREAD

**Issue by luojiong** [facebook/react-native#30031]
System:
    OS: Windows 7 6.1.7601
    CPU: (4) x64 Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
    Memory: 6.04 GB / 15.97 GB
  Binaries:
    Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Users\Administrator\AppData\Roaming\npm\yarn.CMD
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 22, 25, 27, 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3
      System Images: android-28 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5977832
  Languages:
    Java: Not Found
    Python: 2.7.12
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by dantereve** [comment]
Check this issue, you can apply a patch to make this works again on iOS 14 : #29279

**Comment by luojiong** [comment]
@dantereve    Thanks for your quick answer, I will try now

**Comment by MarcosSarges** [comment]
this bug is only caused in development mode in Xcode 12, look for the latest version of RN 0.63.1, there is one I did just for that.

Nesse link tem a correção: https://github.com/facebook/react-native/issues/29279#issuecomment-658244428

**Comment by luojiong** [comment]
if (_currentFrame) {
layer.contentsScale = self.animatedImageScale;
layer.contents = (__bridge id)_currentFrame.CGImage;
} else {
[super displayLayer:layer];
}

in : /node_modules/react-native/Libraries/Image/RCTUIImageViewAnimated.m

**Comment by sobanarshad85** [comment]
https://github.com/facebook/react-native/issues/29279#issuecomment-658244428
