### ISSUE TITLE
Podspecs are breaking with nightly build version in package.json

### ISSUE THREAD

**Issue by patrick-agency73** [facebook/react-native#30036]
When using a nightly, the pods fail to build. The podspecs look for the version in package.json. Package.json in master uses "100.00" as version, but the nightlies use a version that the podspecs can't recognize.

Podspec sample
```
if version == '1000.0.0'
  # This is an unpublished version, use the latest commit hash of the react-native repo, which we’re presumably in.
  source[:commit] = `git rev-parse HEAD`.strip
else
  source[:tag] = "v#{version}"
end
```
Should be
```
if version == '1000.0.0' || version.include? "0.0.0-"
  # This is an unpublished version, use the latest commit hash of the react-native repo, which we’re presumably in.
  source[:commit] = `git rev-parse HEAD`.strip
else
  source[:tag] = "v#{version}"
end
```

## React Native version:
```
System:
    OS: macOS 10.15.5
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 2.14 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.2.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 28, 29
      Build Tools: 26.0.3, 27.0.3, 28.0.3, 29.0.2, 29.0.3, 30.0.0
      System Images: android-25 | Google APIs ARM 64 v8a, android-28 | Google Play Intel x86 Atom, android-R | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_192 - /Users/patrickmcwilliams/.jenv/shims/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.0.0-c3ab2a254 => 0.63.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
1.  Include a nightly as the react-native package in your project
2. run ```npx pod-install```

## Expected Results
Pods should be properly. Instead it throws errors.

## Errors
```
>npx pod-install
npx: installed 1 in 1.499s
Scanning for pods...
1.9.3
> pod install
Adding a custom script phase for Pod RNFBApp: [RNFB] Core Configuration
Auto-linking React Native modules for target `moishemobile`: RNCMaskedView, RNCPushNotificationIOS, RNDeviceInfo, RNFBAnalytics, RNFBApp, RNGestureHandler, RNImageCropPicker, RNReanimated, RNSVG, RNScreens, RNVectorIcons, ReactNativeFabric, react-native-safe-area-context, react-native-version-check, react-native-version-number, react-native-webview, and react-native-zendesk-support
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
[!] The `FBLazyVector` pod failed to validate due to 1 error:
    - ERROR | version: The version of the spec should be higher than 0.



Aborting run
An unexpected error was encountered. Please report it as a bug:
Error
    at CocoaPodsPackageManager._installAsync (/Users/patrickmcwilliams/.npm/_npx/94893/lib/node_modules/pod-install/build/index.js:2:85721)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async CocoaPodsPackageManager.installAsync (/Users/patrickmcwilliams/.npm/_npx/94893/lib/node_modules/pod-install/build/index.js:2:85121)
    at async runAsync (/Users/patrickmcwilliams/.npm/_npx/94893/lib/node_modules/pod-install/build/index.js:2:12925)
    at async /Users/patrickmcwilliams/.npm/_npx/94893/lib/node_modules/pod-install/build/index.js:2:13011
```

**Comment by alloy** [comment]
@tom-un and I just realized this the other day. We concluded the version used should change, rather than updating CocoaPods to support v0.0.0, but I don’t recall where we left the discussion wrt what to use as the version.

**Comment by patrick-agency73** [comment]
@alloy for what its worth when i changed the version to something like 
```0.63.2-c3ab2a254-NIGHTLY```
It still worked

**Comment by tom-un** [comment]
The react-native-macos nightly builds are broken in exactly the same way (still).   

In the react-native-macos builds, the Azure DevOps publish yaml script for canary builds invokes:
```yaml
          script: node scripts/bump-oss-version.js --nightly`
```
(https://github.com/microsoft/react-native-macos/blob/master/.ado/publish.yml#L64)

and the that script renames the version to 
```js
  version = `0.0.0-${currentCommit.slice(0, 9)}`;
```
(https://github.com/microsoft/react-native-macos/blob/master/scripts/bump-oss-version.js#L43)

Is there a reason the nightly builds in both react-native and the out-of-tree platforms just be `1000.0.0-HASH` ?

**Comment by alloy** [comment]
@acoates-ms Had done this work, but it didn’t appear to be for any specific reason, so let’s just standardize on 1000 to mean `master` and builds from `master`?

**Comment by acoates-ms** [comment]
Yeah, The `0.0.0-commitid` format was chosen purely to align with the version scheme used by react.  If it's not compatible with react-native, then we should use a different format.

We use 1000.0.0-canary.xxx for react-native-windows.

**Comment by alloy** [comment]
I’ll do this work 👍

**Comment by alloy** [comment]
(I’ll be doing this work firs on our macOS fork, as it will be easier for me to test changes.)

**Comment by alloy** [comment]
As discussed [here](https://github.com/microsoft/react-native-macos/issues/620#issuecomment-714489545), I’ll be looking at update CocoaPods instead.

**Comment by alloy** [comment]
PR created https://github.com/CocoaPods/Core/pull/657

**Comment by SConaway** [comment]
Just gonna resurrect this OLD issue to see what's going on with it (so: non-RN maintainers who are following this issue still: sorry for the notification). I'm still getting this issue with plain `react-native` and the same error as the original message. 

I'm running the latest `pod` binary but it still happens so I'm wondering if there's another underlying issue. Please let me know if there's any way I can help. Thanks!
