### ISSUE TITLE
Dismiss keyboard will fire keyboardWillShow on iOS 14

### ISSUE THREAD

**Issue by lovejaco** [facebook/react-native#30037]
## Description
Look similar to #18003

## React Native version:
```shell
System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 156.31 MB / 16.00 GB
    Shell: 5.8 - /usr/local/bin/zsh
  Binaries:
    Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 28, 30
      Build Tools: 28.0.3, 30.0.1, 30.0.2
      System Images: android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_265 - /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home//bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```
## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.  Play with iOS 14 (it works fine on iOS 12 and iOS 13)
2. Focus on TextInput  and keyboard show up
3. `<Button onPress={()=>{Keyboard.dismiss()}}`
4. click to TextInput (will keyboardWillShow event fire)
5.  pressed keyboard return key (keyboardWillShow event will not fire)
## Expected Results
Only keyboardWillHide(keyboardDidHide) will be fired.

## Snack, code example, screenshot, or link to a repository:
![sfsf](https://user-images.githubusercontent.com/1255212/94344568-484d9500-005b-11eb-90f1-6ef3930320d8.gif)

**Comment by Tieler91** [comment]
Hey, I've got a similar issue. Keyboard hidden is shown twice. 

You can see this behavior also in the example snack (iOS) in the documentation
[https://snack.expo.io/?&iframeId=5kxl55mlft&preview=true&platform=web&supportedPlatforms=ios,android,web&name=Keyboard%20Function%20Component%20Example&description=Example%20usage&theme=light&waitForData=true](url)

iOS 14.0.1
react-native-cli: 2.0.1
react-native: 0.63.4

**Comment by bemaverick** [comment]
I found very similar bug.
keyboardWillShow fires when user blurs TextInput. In my case this happens only when user change text in the input

iOS 13.5
react-native: 0.59.10

![Screen Recording 2021-04-16 at 19 22 03](https://user-images.githubusercontent.com/25745362/115055489-2843cd00-9eea-11eb-839b-5cdb62500c72.gif)
