### ISSUE TITLE
RN v63.2 IOS Library path issue when Building

### ISSUE THREAD

**Issue by maestrolsj** [facebook/react-native#30040]
## Description
I upgraded react native version  ( 0.61.5 > **0.63.2** ) according to upgrade-helper
**Android works well** but **IOS had a building issue regarding library path.**

Xcode : Version 11.6 (11E708)

I tried this
- https://blog.cpming.top/p/react-native-0-62-undefined-symbol
- https://github.com/facebook/react-native/issues/28483
- I tried Library Search Paths **without** double quotation("") 
 
![image](https://user-images.githubusercontent.com/16445243/94348724-d23b3500-003e-11eb-8ad4-185d0746779f.png)

## React Native version:
System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 525.88 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.8.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.7 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28, 29
      Build Tools: 26.0.3, 27.0.3, 28.0.2, 28.0.3, 29.0.2
      System Images: android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_181 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Not needed

## Expected Results
Build success

## Snack, code example, screenshot, or link to a repository:
Not needed

**Comment by deejayxd07** [comment]
Hi @maestrolsj, were you able to run `cd ios/ && pod install` before this?

**Comment by maestrolsj** [comment]
@deejayxd07  Thank you for your comment.  There was no error when I install ### pod

 `
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'RankFromUs' do
  
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  target 'RankFromUsTests' do
    inherit! :complete
    # Pods for testing
  end

 

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!

 
end
# if you see errors about React duplicate definitions, this fixes it. The same works for yoga.
post_install do |installer|
  flipper_post_install(installer)
  installer.pods_project.targets.each do |target|
    targets_to_ignore = %w(React yoga)

    if targets_to_ignore.include? target.name
      target.remove_from_project
    end
  end
end`
