### ISSUE TITLE
Can not run react-native app in Xcode emulator

### ISSUE THREAD

**Issue by JoaoMartins1930** [facebook/react-native#30048]
Hello!!

Since new Xcode version was released, I have been having some issues launching my app. First I could not use my terminal to run the app in iOS devices, but by searching and trying some solution, that issue was fixed and now I CAN run it with the terminal on both iOS and android ("react-native run-ios" and "react-native run-android"), but I CAN'T run using Xcode and the problem is in the package "@react-native-community/datetimepicker". There's a lot of errors coming because of this one and if I uninstall it, the app can be launched with no problems. I tried a lot of solutions like remove and add the packages again, switch versions, clear all packages and cache but nothing makes this to work again.

This are the erros that are comming:

<img width="1792" alt="RNDateTimePickerManager_m" src="https://user-images.githubusercontent.com/46728603/94418225-01ee5800-0179-11eb-819c-9364038cbb27.png">

<img width="250" alt="RNDateTimePickerManager_m-2" src="https://user-images.githubusercontent.com/46728603/94418257-0d418380-0179-11eb-811e-f5e41785cbb2.png">

## React Native version:
System:
    OS: macOS 10.15.7
  Binaries:
    Node: 10.20.1 - /var/folders/4m/r9j__9zs3qjbd2xl_f79_fqc0000gn/T/yarn--1601285913249-0.4841088215484062/node
    Yarn: 1.22.4 - /var/folders/4m/r9j__9zs3qjbd2xl_f79_fqc0000gn/T/yarn--1601285913249-0.4841088215484062/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v10.20.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.4 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 23, 28, 29
      Build Tools: 23.0.1, 27.0.3, 28.0.3, 29.0.2, 29.0.3
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_232 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

Thanks for helping me!

**Comment by lucianomlima** [comment]
@JoaoMartins1930 what are you did change to run on terminal?
Here I'm get this error:
```sh
error Failed to launch the app on simulator, An error was encountered processing the command (domain=FBSOpenApplicationServiceErrorDomain, code=4):
The request to open "com.example.app" failed.
Underlying error (domain=FBSOpenApplicationErrorDomain, code=4):
	The operation couldn’t be completed. Application info provider (FBSApplicationLibrary) returned nil for "com.example.app"
```
