### ISSUE TITLE
Dimensions not getting updated in LandscapeMode Android

### ISSUE THREAD

**Issue by ims7inc** [facebook/react-native#30045]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Please provide a clear and concise description of what the bug is. Include screenshots if needed.
Please test using the latest React Native release to make sure your issue has not already been fixed: https://reactnative.dev/docs/upgrading.html

## React Native version: 0.63.2
Run `react-native info` in your terminal and copy the results here.
System:
    OS: macOS 10.15.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 366.32 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.7.5 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3
      System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_242 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Add Dimesions.addEventListener in componentDidMount and change orientation to LandscapeMode for Android
2. Dimensions.get('window') not updating width in Android

## Expected Results
Dimensions should change with respect to orientation

## Snack, code example, screenshot, or link to a repository:
`componentDidMount() {
        Dimensions.addEventListener("change", this.handleOrientationChange);
    }`

`handleOrientationChange = (e: any) => {
        const { width } = e.window; // width not updating in Android
        this.setState({ width });
}`

**Comment by CmerCy132** [comment]
Any updates on this issue?

**Comment by ims7inc** [comment]
Same issue with the react native 0.63.2

**Comment by oleksandr-dziuban** [comment]
Same issue from v0.63.2+

**Comment by oleksandr-dziuban** [comment]
@react-native-bot This is the really critical issue which breaks all Android orientation related styling in apps. When this can be reviewed by maintainers? Thanks...

**Comment by safaiyeh** [comment]
@ims7inc closing, please follow the issue template in a new issue.

**Comment by Naturalclar** [comment]
You can use useWindowDimensions for width and height and it will be updated on orientation change
