### ISSUE TITLE
Android 11 update brakes Keyboard - Keyboard won’t stay open.

### ISSUE THREAD

**Issue by wmonecke** [facebook/react-native#30041]
### BUG

Since Android 11 many of my users have reported that the Keyboard is not staying open when you enter a screen where it automatically opens.

I am using a `KeyboardAvoidingView` and users have been telling me the keyboard shows for a couple of seconds but then quickly hides. Anyone else facing this issue?

### INFO

`````
System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 7.63 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 8.9.4 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.4 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 26.0.2, 26.0.3, 27.0.2, 27.0.3, 28.0.2, 28.0.3, 29.0.2
      System Images: android-28 | Google Play Intel x86 Atom, android-P | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_172 - /usr/bin/javac
    Python: 2.7.14 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
  npmGlobalPackages:
    *react-native*: Not Found
`````

**Comment by ravirajn22** [comment]
Can you reproduce the issue in Android 11 emulator?

**Comment by wmonecke** [comment]
@ravirajn22  Yes, just try using a KeyboardAvoidingView on and Android Emulator with Android 11 and then on one with Android 10.

**Comment by safaiyeh** [comment]
Hi @wmonecke could you provide a repo that demonstrates the issue?

**Comment by MayoudP** [comment]
I'm also getting issues with user on Android 11, some of the concerned view using KeyboardAvoidingView but some others not... 
However, it's working well on my emulator android 11.

**Comment by wmonecke** [comment]
@MayoudP I just created a KAV HOC (in case any future releases need me to change a prop for a specific platform) with these props:

````
<KeyboardAvoidingView 
    enabled
    style={styles.flex1} 
    behavior={'padding'}
  >
`````

No issues reported so far.

Specs: 

`````
"react": "16.13.1",
"react-native": "0.63.2",
``````

**Comment by MayoudP** [comment]
> @MayoudP I just created a KAV HOC (in case any future releases need me to change a prop for a specific platform) with these props:
> 
> ```
> <KeyboardAvoidingView 
>     enabled
>     style={styles.flex1} 
>     behavior={'padding'}
>   >
> ```

You mean adding behavior=`padding` basically fixed the issue ?

**Comment by wmonecke** [comment]
@MayoudP Basically.

But again, this might be just my current configuration. If I upgrade RN I could break it.

**Comment by lucasluca** [comment]
I'm having the same problem here.

**Comment by chrisglein** [comment]
If I'm reading the thread correctly it sounds like @wmonecke has determined a workaround here of adding `behavior={'padding'}` and is unblocked. Is that correct?
@lucasluca If you are also hitting this issue can you confirm with your environment information and perhaps a link to a Snack with your repro to see if it's different?

**Comment by gcosta-proxet** [comment]
Some feedback in 2022?
