### ISSUE TITLE
How to know if all the elements of a flatList have been loaded, bug?

### ISSUE THREAD

**Issue by tastafur** [facebook/react-native#30043]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
I have the case in an app that I have to wait for a list of elements to be loaded to scroll, I can't find a way to do it apart from using a setTimeout and I have tried everything

## React Native version:
System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 18.90 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.0 - ~/.nvm/versions/node/v12.16.0/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3
      System Images: android-23 | Google APIs Intel x86 Atom_64, android-28 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.0/12A7209 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_242 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
I have a flatlist with header, footer and separator and a list of 10 items, the 10 elements are loaded dynamically, at first they are not, an effect calls au api and brings them and when they are loaded, after they have been rendered I try scroll to the first element, impossible I have looked at all the methods and possible combinations, only the setTimeout trick works

## Expected Results
A way to scroll a list when the elements of the list have been rendered.

## Snack, code example, screenshot, or link to a repository:
``` javascript
useEffect(() => {
    if (typeof innerRef === 'object' && innerRef.current) {
      if (
        comments.length > 0 &&
        moveToComments &&
        needShowComments &&
        postHeight > 0 &&
        numberLayoutRenders.current === 2
      ) {
        setNeedShowComments(false);
        numberLayoutRenders.current = numberLayoutRenders.current - 1;
        console.log('postHeight', postHeight);
        setTimeout(() =>
          innerRef.current.scrollToOffset({animated: true, offset: postHeight}),
        );
      }
    }
  }, [
    numberLayoutRenders,
    comments,
    innerRef,
    moveToComments,
    postHeight,
    needShowComments,
    setNeedShowComments,
  ]);
```

**Comment by DevineDecrypter** [comment]
have the same issue and got nothing besides timeout to make it work :(
