### ISSUE TITLE
ActivityIndicator works only on iOS

### ISSUE THREAD

**Issue by rodrigofbm** [facebook/react-native#30056]
## Description
I'm using RN  0.63.2 and the ActivityIndicator appears on iOS but not on Android

## React Native version:
```
System:
    OS: Linux 5.8 Fedora 32 (KDE Plasma) 32 (KDE Plasma)
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
    Memory: 3.62 GB / 11.48 GB
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 12.18.4 - /usr/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 6.14.6 - /usr/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 23, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2
      System Images: android-27 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
  Languages:
    Java: Not Found
    Python: 3.8.5 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce

1. call `<ActivityIndicator />`

## Expected Results
Show the ActivityIndicator also on Android

**Comment by jayshah123** [comment]
You have to explicitly give `color` on Android for an ActivityIndicator, default `color` no longer works. I am raising a PR for fixing this soon.

**Comment by rodrigofbm** [comment]
> You have to explicitly give `color` on Android for an ActivityIndicator, default platform color no longer works. I am raising a PR for fixing this soon.

lol it works, thks!

**Comment by fabriziobertoglio1987** [comment]
PR https://github.com/facebook/react-native/pull/29830 fixes this issue
