### ISSUE TITLE
Alert.alert() colour

### ISSUE THREAD

**Issue by chai86** [facebook/react-native#30058]
How do I change the background colour and text colour of the Alert.alert() box for iOS in react native?

environment: React-native v0.59.10

**Comment by wmonecke** [comment]
You cant. Please dont open an issue for there kind of questions. Stackoverflow is better.

**Comment by pedrocardoz0** [comment]
You should close this issue.

**Comment by flexbox** [comment]
Hey @chai86 
Can you please close your issue if your problem is solved 🙏 ?

**Comment by chai86** [comment]
No it’s not yet resolved.
