### ISSUE TITLE
<Image> don't work when RCTEnableTurboModule is enabled

### ISSUE THREAD

**Issue by fahelmoreira** [facebook/react-native#30068]
## Description
when enable RCTEnableTurboModule(YES) the <Image> tag stop to display local image from assets-library: or ph:

## React Native version:
version 0.63.2

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Enable turbo modules

2 .Update any component in the example project (eg ./Example/src/App.js/MainScreen component and attempt to render an image using assets-library://asset or ph://

3. Observe runtime error and image not displayed.

<img width="845" alt="Screen Shot 2020-09-29 at 12 13 44 PM" src="https://user-images.githubusercontent.com/39835527/94578588-4e579780-024e-11eb-87ed-91221dc6fac2.png">

![93393687-e1fe9080-f86a-11ea-98cc-18b5566d78ff](https://user-images.githubusercontent.com/39835527/94578510-3122c900-024e-11eb-8658-3be9f45c8896.jpeg)

![93393682-e0cd6380-f86a-11ea-9f42-8313b089dbcc](https://user-images.githubusercontent.com/39835527/94578523-36801380-024e-11eb-8186-5856bf1e0f76.jpeg)

## Expected Results
Image display as normal

**Comment by mrousavy** [comment]
I just created a PR in react-native-cameraroll to add custom Image URL loaders for `ph://` and `asset-library://` assets. https://github.com/react-native-cameraroll/react-native-cameraroll/pull/632

So if you install react-native-cameraroll, `ph://` assets can be loaded again in `<Image>` components on new arch/Fabric 🎉🥳
