### ISSUE TITLE
Android shows uncorrect size

### ISSUE THREAD

**Issue by storm52** [facebook/react-native#30078]
## before update (0.60.0)
<img src="https://user-images.githubusercontent.com/8487187/94704680-c0c19800-0372-11eb-8e1e-3462a8194cb3.jpeg" width="400" height="800">

## after(0.63.3)
<img src="https://user-images.githubusercontent.com/8487187/94704702-c61ee280-0372-11eb-8e33-416717ced19c.jpeg" width="400" height="800">

## Description
After I update react-native from 0.60.0 to 0.63.3.iOS is all normal.But android shows became this .This is probably not a universal bug。Hopefully,I can get some help can resolve this situation,thank you.

我把react-native库从0.60.0升级到0.63.3后，我的安卓显示变成这样了，应该不是一个共性的bug，只希望有遇见过同样问题的或者有点思路的，可以给点帮助，谢谢

## React Native version:
0.63.3

## Expected Results
安卓内容显示正常

**Comment by fabriziobertoglio1987** [comment]
https://github.com/facebook/react-native/issues/27231 and https://github.com/facebook/react-native/issues/29323
