### ISSUE TITLE
Library react-native-ble-manager not working in Android 10 devices

### ISSUE THREAD

**Issue by abhinavsiotech** [facebook/react-native#30077]
I am using this library for discovering BLE devices. In our company we have people with devices that are high end, that is Android 10, where the application is installed and using your library, we are unable to discover devices. In contrast we get devices discovered in Android 8.0 or Oreo.

It is the request that for every library you use, please mention which OS version whether in iOS and Android those libraries will work or not work.

This is a request because this discovery that you library will not work has wasted 1 and a half month of our labor.

**Comment by ravirajn22** [comment]
@abhinavsiotech this is not react-native-ble-manager library repo this is react-native repo, raise issue in their repo.

**Comment by abhinavsiotech** [comment]
react-native info
info Fetching system and libraries information...
(node:6348) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Memory: 47.28 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.8.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.7 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 23, 29, 30
      Build Tools: 23.0.1, 28.0.3, 29.0.2, 29.0.3, 30.0.1
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_265 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by abhinavsiotech** [comment]
> @abhinavsiotech this is not react-native-ble-manager library repo this is react-native repo, raise issue in their repo.

Please Sir, don't say that FaceBook dosn't command over react-native and co-dependencies. At least they can check what their libraries are doing!

**Comment by ravirajn22** [comment]
Sorry to tell, but you'r wasting time here. No one will respond for a react-native library issue. You have a chance of getting a solution when you post it directly in the libraries issues page.

**Comment by abhinavsiotech** [comment]
Okay, have a great day!

**Comment by gedeagas** [comment]
@abhinavsiotech please make an issue here https://github.com/innoveit/react-native-ble-manager. As @ravirajn22 says, this is react-native repository. react-native-ble-manager is a third party plugin.

**Comment by abhinavsiotech** [comment]
Done already thanks.
