### ISSUE TITLE
React Native 0.63 and Xcode12 building issues "Undefined symbol: __swift_FORCE_LOAD"

### ISSUE THREAD

**Issue by rnnyrk** [facebook/react-native#30079]
## Description
After upgrading to Xcode12 and the latest iOS, my project won't build anymore. I got 3 errors which I can't seem to fix. Updated to latest React Native as well, since the changelog mentioned "Support Swift based libraries using Xcode 12’s build system.", so I was hoping it would solve this issue (but unfortunately not). 

<img width="497" alt="Screenshot 2020-09-30 at 23 01 58" src="https://user-images.githubusercontent.com/4519142/94739322-1b59f480-0371-11eb-9e2c-5335395e07ae.png">

Can't find antything related to this error via Google as well, so trying here now. Any suggestions?

## React Native version:
```
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 2.16 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.11.1 - ~/.nvm/versions/node/v12.11.1/bin/node
    Yarn: 1.3.2 - /usr/local/bin/yarn
    npm: 6.11.3 - ~/.nvm/versions/node/v12.11.1/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.1
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
  Languages:
    Java: 10.0.1 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.3 => 0.63.3
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Updating to latest React Native
2. Updating to Xcode12
3. Removed pods and reinstalled
4. Reinstalled NPM packages
5. Build project

## Expected Results
Project should build as before with iOS11 and Xcode 11

**Comment by maoster** [comment]
Have you try added an empty swift file? I think I had the same issue before and I fixed by adding an empty swift file to the project folder. If you add the swift file through Xcode, it will prompt you if you are going to save it as bridging file and answer yes to the prompt.

**Comment by rnnyrk** [comment]
@maoster Super weird, I had an birdging header. After re-adding it, it works again. Thanks.

**Comment by LichKing-2234** [comment]
The same issue, RN(>0.62.0) project support swift default. After I create an empty swift file, I notice this change in my `project.pbxproj`. So I think the project does not support the new swift migration.
![image](https://user-images.githubusercontent.com/9312526/96449471-77fd5080-1247-11eb-9d9a-e9c96e0e0047.png)
