### ISSUE TITLE
Remove default delayPressIn from TouchableWithoutFeedback, the same affecting TouchableOpacity.

### ISSUE THREAD

**Issue by iiagodias** [facebook/react-native#30070]
## Description
The TouchableOpacity by default is delayed due to the delayPressIn, we need a response when pressing.

## React Native version:
 npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.2 => 0.63.2
    react-native-windows: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Create the component and press

## Expected Results
Trigger the event without delay.

**Comment by ravirajn22** [comment]
Try version 0.63.3, they have fixed it.

**Comment by iiagodias** [comment]
It was resolved in version 0.63.3
