### ISSUE TITLE
Got DOWN touch before receiving UP or CANCEL from last gesture

### ISSUE THREAD

**Issue by yevhenlv** [facebook/react-native#30080]
Got next error in ReactNative (android)

E unknown:ReactNative: Got DOWN touch before receiving UP or CANCEL from last gesture
PowerWrap: PowerHal_TouchBoost
Screen doesn't react on touch events and looks like freezing, but all background tasks running with success result and debugger doesn't show other errors.

RN 0.63.3 RN-navigation 7.0.0

System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 33.66 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.0 - /usr/local/bin/node
    Yarn: 1.19.0 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0. - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 12.0/12A7209 - /usr/bin/xcodebuild
  Languages:
    Java: javac 13 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by penchef** [comment]
experiencing the same issue (``` "react-native": "0.63.2",```) on android emulator in debug mode only.

**Comment by spacesuitdiver** [comment]
@penchef are you using rn-navigation?

**Comment by penchef** [comment]
@spacesuitdiver  yes ``` "react-native-navigation": "^6.7.1",```

**Comment by yevhenlv** [comment]
RNN version 7.0
I don't know is it correct, but I found solution on rnn docs:

https://wix.github.io/react-native-navigation/docs/installing

app/build.gradle

dependencies {
    ...
    implementation 'com.android.support:design:25.4.0'
    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
}

Adding this two dependencies solved problem.

**Comment by penchef** [comment]
ditto with RNN 7.0.0 / 7.1.0 / 6.7.1 ...

**Comment by yevhenlv** [comment]
I think it depends on warnings on screen (after opening one of them I got this error again).

**Comment by DanielJanke** [comment]
Same issue here

**Comment by DanielJanke** [comment]
@penchef @spacesuitdiver  Did you find a solution?

**Comment by Joshuapwilley** [comment]
Chiming in to say I'm experiencing the same issue.

react-native: 0.63.3
react-native-navigation: 7.1.0

Experiencing the error on real device & emulator. Only occurs in debug mode on Android. Release builds do not have this issue.
Also - I am completely unable to use the app at all in debug mode on Android. No touch events register at all.

**Comment by penchef** [comment]
@DanielJanke no solution. 

The issue seems to be Android 11 related. 

**WORKAROUND** 
* add a non-android 11 device for debugging

P.S. RNN came out with a [7.2.0 release yesterday](https://github.com/wix/react-native-navigation/releases/tag/7.2.0). Worth giving a shot ¯\_(ツ)_/¯

**Comment by safaiyeh** [comment]
Is this issue specific to RNN? Could someone provide a small repro of this issue, to debug further?

**Comment by Joshuapwilley** [comment]
I am not sure if this issue is related to RN or RNN, but for anyone who comes across this issue without resolution, I can confirm downgrading to the following versions resolved the issue for me:

react-native: 0.61.5
react-native-navigation: 6.7.5

Obviously this solution will not work for those who want to be on RN 0.63+ and RNN 7+, but I couldn't spend the time troubleshooting this issue so the version downgrade was a welcome compromise.

**Comment by Frank1234** [comment]
The view intercepting the touch is a fullscreen ReactRootView, I believe a LogBox (it’s from the LogBox JSModule). Instead of one, there are two ReactRootViews in my application; one empty fullscreen RootView covers the normal UI and intercepts touches.

**Comment by Frank1234** [comment]
The LogBox Dialog is picking up (part of) the touches. You can see this when you add a breakpoint to View.dispatchTouchEvent at the places where it returns "true": the ReactRootView from LogBox takes the touch.
If you open "LogBoxModule.java" you will see that it creates a ReactRootView, and adds it to a Dialog. This apparently invisible dialog blocks the UI. 

The cause: someone is calling "show()" from Javascript, and nothing shows but an empty dialog. I'm done with debugging. Working around the problem for now, by adding my own LogBoxModule implementation, that does not call `super.show()` and implements `canOverrideExistingModule` to true. The downside of this is that the app will not show the fullscreen LogBox, only the toasts.

**Comment by DanielJanke** [comment]
@Frank1234 Could you share some code or some useful links for creating own module implementations? I'm still facing this issue.

**Comment by penchef** [comment]
**UPDATE**

#kudos to @risland for isolating the issue! 

We've been able to create a [(minimal??) reproducible repo](https://github.com/penchef/android-debug-nuisance/blob/main/index.js#L17):

As @yevhenlv and @Frank1234 were suspecting, the issue seems to be with some empty error dialog popping up over everything else. 

In our case the issue was an [`Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)`](https://github.com/facebook/react-native/issues/26687) caused by the `Navigation.registerComponent` call *inside* the `persistStore` callback.

Moving the `Navigation.registerComponent` outside solved the issue (for us).

```javascript
import {persistStore, persistReducer} from 'redux-persist';
import {Navigation} from 'react-native-navigation';
import {combineReducers, createStore, compose} from 'redux';

import AsyncStorage from '@react-native-community/async-storage';

import React from 'react';
import {SafeAreaView, StatusBar, Button, Alert} from 'react-native';

// DOES WORK HERE!
Navigation.registerComponent('foo.bar', () => App);

const store = configureStore();

persistStore(store, null, () => {
  // DOES NOT WORK HERE!
  // Navigation.registerComponent('foo.bar', () => App);

  Navigation.setRoot({
    root: {
      stack: {
        children: [
          {
            component: {
              name: 'foo.bar',
            },
          },
        ],
      },
    },
  });
});

...
```

Good luck everyone out there!
