### ISSUE TITLE
About RefreshControl under SafeAreaView

### ISSUE THREAD

**Issue by thongncvn** [facebook/react-native#30089]
## Description
Somehow `RefreshControl` doesn't appear initially if wrapped under a root `SafeAreaView`. It works if wrapped by `View` instead.

## React Native version:
```
  Binaries:
    Node: 12.18.4 - /var/folders/sn/d8n67b5d7k9_hdtdxmmmvjf00000gn/T/yarn--1601576743381-0.6289225478665288/node
    Yarn: 1.22.5 - /var/folders/sn/d8n67b5d7k9_hdtdxmmmvjf00000gn/T/yarn--1601576743381-0.6289225478665288/yarn
    npm: 6.14.6 - /usr/local/opt/node@12/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
  Languages:
    Java: 14.0.1 - /usr/local/opt/openjdk/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: ^0.63.2 => 0.63.2
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Expected Results
The RefreshControl appears according to the value passed to `refreshing` props.

## Snack, code example, screenshot, or link to a repository:
Please visit this snack: https://snack.expo.io/aMGMTElFA

**Comment by fierysolid** [comment]
I have this same issue

**Comment by fierysolid** [comment]
I fixed this by using useSafeAreaInsets from react-native-safe-area-context and applying the insets as padding to the screens containing view instead of using SafeAreaView

**Comment by marcshilling** [comment]
That's a valid workaround but no reason that this shouldn't work with SafeAreaView...
