### ISSUE TITLE
TurboModules / CallInvoker are not ABI safe

### ISSUE THREAD

**Issue by asklar** [facebook/react-native#30086]
it looks like TurboModules are currently coupled to STL types which makes the APIs non ABI-safe, thus hindering reuse-via-binary, are there plans to address this?

_Originally posted by @asklar in https://github.com/facebook/react-native/issues/28128#issuecomment-702006201_

**Comment by asklar** [comment]
CC @TheSavior

**Comment by dulmandakh** [comment]
Please read https://github.com/react-native-community/discussions-and-proposals/issues/257
