### ISSUE TITLE
'Flipper/FlipperCertificateExchangeMedium.h' file not found

### ISSUE THREAD

**Issue by wem2017** [facebook/react-native#30090]
Can't build when upgrade react native 0.63.2 to 0.63.3 
guide: https://github.com/react-native-community/rn-diff-purge
## React Native version:
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 388.30 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.2 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.5 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.0
      System Images: android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_242-release - /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
![Screen Shot 2020-10-02 at 06 19 49](https://user-images.githubusercontent.com/58833808/94873002-48dd9580-0478-11eb-9a77-789d8c6ded53.png)

## Podfile
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'listar' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'
end

**Comment by pedrocardoz0** [comment]
maybe this issue could help you, [https://github.com/facebook/flipper/issues/976](url). Few months ago i had the same issue, but the reason was because of my podfile structure, maybe react-native 0.63 does not support this structure.

**Comment by wem2017** [comment]
Thanks for suggestion, but your link not found

**Comment by wem2017** [comment]
Thanks for suggestion, but your link not found

**Comment by pedrocardoz0** [comment]
> Thanks for suggestion, but your link not found

Yeah, I have fixed try to check it out

**Comment by pedrocardoz0** [comment]
> Thanks for suggestion, but your link not found

There's something else that you can do, open your xCode go to Product >> Clear Build Folder, and then try to build your app inside the XCode

**Comment by chenop** [comment]
Have you figure this out?

**Comment by showarm** [comment]
> Have you figure this out?

https://github.com/facebook/flipper/tree/v0.75.1/xplat/Flipper, check if there is a 'FlipperCertificateExchangeMedium.h' file on your Flipper version tag. if not , try another version Flipper. If it does have, do the following clean:

1. cd ios/  &&  pod cache clean --all
2. rm -rf ~/.cocoapods/repos/
3. then 'pod update' in ios/  while your network is very well.
