### ISSUE TITLE
[Question  Component ]is there a method like "viewdidappear" in swift?

### ISSUE THREAD

**Issue by nice2mu** [facebook/react-native#3009]
I  have  a ProfileView  and  because  I haven't login  so  it  shows  default avatar and  a   login button  linked  to  LoginView.

I type  my  id and  password   and  login  , success  ,then  back to ProfileView.

so, now I need to   update  the   view,   how to ?      

the  componentWilMount   didn't work.

is there  a  method   like  "viewdidappear" in swift?

**Comment by ide** [comment]
You can listen to the "didfocus" event on a Navigator's NavigationContext. There is no viewDidAppear method.
