### ISSUE TITLE
Time out waiting for modules to be invalidated

### ISSUE THREAD

**Issue by lucasjohnston** [facebook/react-native#30099]
## Description
I'm randomly getting crashes with the error `Module AppRegistry is not a registered callable module (calling runApplication)`. 

There are a few StackOverflow posts and an existing issue (#15941) relating to this, which point to the `letterSpacing` variable on "non english characters" being the issue or `display: none;` causing it. Given our app's only in english and doesn't use the display style property, I'm presuming the error is due to emojis/escape codes being displayed (we have pretty error codes ✨) as they're not latin characters. That's a total guess though.

In any case, a fatal crash shouldn't occur without explanation - especially not due to a style property 🙂

## React Native version:
```
System:
    OS: macOS 11.0
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 23.91 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.18.1 - ~/.nvm/versions/node/v12.18.1/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v12.18.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3
      System Images: android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 12.0/12A7209 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_251 - /Users/lucas/.jenv/shims/javac
    Python: 3.8.5 - /usr/local/opt/python/libexec/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
It occurs randomly, so am unable to reproduce per se.

## Expected Results
No fatal error.

## Snack, code example, screenshot, or link to a repository:
Again, hard to point this down to a specific line of code as module invalidation happens outside of my control :)

**Comment by siyayang0420** [comment]
This happened to me so many times, one thing that works for me is to delete the node_modules folder and use npm install to reinstall it and in the Xcode clean build again. Hope this helps.

**Comment by tolgaberk** [comment]
I mostly get this error when metro bundler cannot figure out which module to load at first. Almost all the time it is caused by circular dependencies in my case.

**Comment by sirajalam049** [comment]
Ensure if your mobile and laptop connected over same network. Explaied it [here](https://garbagevalue.com/blog/timeout-waiting-for-modules-to-be-invalidated).
