### ISSUE TITLE
Error: Activity class {com.myapp/com.myapp.MainActivity} does not exist.

### ISSUE THREAD

**Issue by aprilmintacpineda** [facebook/react-native#30092]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Please provide a clear and concise description of what the bug is. Include screenshots if needed.
Please test using the latest React Native release to make sure your issue has not already been fixed: https://reactnative.dev/docs/upgrading.html

## React Native version:
Run `react-native info` in your terminal and copy the results here.

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. I was making my app run on multiple environments (local, staging, production), on android I followed the [Configure build variants guide](https://developer.android.com/studio/build/build-variants.html#product-flavors) and ended up with the following:

```
flavorDimensions "version"
productFlavors {
    local {
        applicationIdSuffix ".local"
    }
    staging {
        applicationIdSuffix ".staging"
    }
    production {}
}
```

I also added `resValue "string", "build_config_package", "com.myapp"` on the `defaultConfig` block. Then created `android/app/src/local/res/values/strings.xml` with the following:

```
<resources>
    <string name="app_name">My App LOC</string>
</resources>
```

and also `android/app/src/staging/res/values/strings.xml` with the same content only `STG` instead of `LOC`.

2. I tried running `npm run android -- --variant=localDebug` and it successfully builds and installs BUT it can't start the app automatically saying the following:

```
BUILD SUCCESSFUL in 10s
199 actionable tasks: 2 executed, 197 up-to-date
info Connecting to the development server...
info Starting the app on "emulator-5554"...
Starting: Intent { cmp=com.myapp/.MainActivity }
Error type 3
Error: Activity class {com.myapp/com.myapp.MainActivity} does not exist.
```

When I manually open the app on my emulator, it works as expected, the only problem is that it doesn't start automatically. I've seen the other opened issues with the same topic but didn't find any actual explanation / solution that works. I've tried doing `./gradlew clean` and `./gradlew assembleLocalDebug` both ran successfully but no good results. I experienced this on Version 0.63.3

I noticed that this only happens when I run `npm run android -- --variant=localDebug` and `npm run android -- --variant=stagingDebug`, but when I run `npm run android -- --variant=productionDebug`, it works well and outputs the following:

```
BUILD SUCCESSFUL in 17s
27 actionable tasks: 27 executed
info Connecting to the development server...
info Starting the app on "emulator-5554"...
Starting: Intent { cmp=com.multi_build/.MainActivity }
```

## Expected Results

`npm run android --variant=localDebug` should run successfully and be able to automatically open the app.

## Snack, code example, screenshot, or link to a repository:
Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

Here's the repo https://github.com/aprilmintacpineda/react-native-multiple-build-environments-example

**Comment by Olgagr** [comment]
I have the same issue. The build is successful, the app installs on the simulator/physical device but it fails to start.

```
System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 11.92 GB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.4 - ~/n/bin/node
    Yarn: 1.19.2 - ~/Documents/projects/twipe-app-v4/node_modules/.bin/yarn
    npm: 6.14.6 - ~/n/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2
      System Images: android-29 | Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6858069
    Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
  npmPackages:
    @react-native-community/cli: ^2.9.0 => 2.9.0 
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.0 => 0.60.0
```

**Comment by adambeck7** [comment]
Same exact behavior as @aprilmintacpineda but on react-native 0.63.4. I don't experience when switching back to our branch running 0.61.5 on the same local machine.

**Comment by gabrielmoncea** [comment]
Same problem here for 0.64

**Comment by swizes** [comment]
This issue needs attention. It does not allows us to release for staging and testing

**Comment by Shivangi2909** [comment]
I am also facing similar issue where I am trying to run it for 3 different environments viz.. development, staging, production

**Comment by Shivangi2909** [comment]
@aprilmintacpineda @swizes @gabrielmoncea  My issue was just the app was getting installed as per 3 environments and taking variables as well correctly just the app was not getting launch and showing above error.
For that I just needed to add **appIdSuffix** in my script to run app as well inside `package.json` like below and it worked, remember to use same **appIdSuffix** as used inside **productFlavors** in app/**build.gradle**:

```
"scripts": {
    "android": "react-native run-android",  
    "ios": "react-native run-ios",  
    "start": "react-native start",  
    "test": "jest",  
    "lint": "eslint .",  
    "android:staging": "react-native run-android --variant=stagingdebug --appIdSuffix 'stage'",  
    "android:staging-release": "react-native run-android --variant=stagingrelease --appIdSuffix 'stage'",  
    "android:dev": "react-native run-android --variant=developmentdebug --appIdSuffix 'dev'",  
    "android:dev-release": "react-native run-android --variant=developmentrelease --appIdSuffix 'dev'",  
    "android:prod": "react-native run-android --variant=productiondebug",  
    "android:prod-release": "react-native run-android --variant=productionrelease",  
    "ios:production": "react-native run-ios --scheme 'ReactNativeStrucure'",  
    "ios:development": "react-native run-ios --scheme 'ReactNativeStrucureDev'",  
    "ios:staging": "react-native run-ios --scheme 'ReactNativeStrucureStage'"  
 },
```

**Comment by gabrielmoncea** [comment]
That is true! You have to add appIDSuffix for this to work, otherwise the cli will try to open the app without the bundle id suffix

**Comment by aprilmintacpineda** [comment]
> @aprilmintacpineda @swizes @gabrielmoncea My issue was just the app was getting installed as per 3 environments and taking variables as well correctly just the app was not getting launch and showing above error.
> For that I just needed to add **appIdSuffix** in my script to run app as well inside `package.json` like below and it worked, remember to use same **appIdSuffix** as used inside **productFlavors** in **app/build.gradle**:
> 
> ```
> "scripts": {
>     "android": "react-native run-android",  
>     "ios": "react-native run-ios",  
>     "start": "react-native start",  
>     "test": "jest",  
>     "lint": "eslint .",  
>     "android:staging": "react-native run-android --variant=stagingdebug --appIdSuffix 'stage'",  
>     "android:staging-release": "react-native run-android --variant=stagingrelease --appIdSuffix 'stage'",  
>     "android:dev": "react-native run-android --variant=developmentdebug --appIdSuffix 'dev'",  
>     "android:dev-release": "react-native run-android --variant=developmentrelease --appIdSuffix 'dev'",  
>     "android:prod": "react-native run-android --variant=productiondebug",  
>     "android:prod-release": "react-native run-android --variant=productionrelease",  
>     "ios:production": "react-native run-ios --scheme 'ReactNativeStrucure'",  
>     "ios:development": "react-native run-ios --scheme 'ReactNativeStrucureDev'",  
>     "ios:staging": "react-native run-ios --scheme 'ReactNativeStrucureStage'"  
>  },
> ```
> 
> Hope it helps!

Ahhh I see. But personally, I think the cli should use what's specified on the gradle files.
