### ISSUE TITLE
Unable to resolve module error on Windows 

### ISSUE THREAD

**Issue by aljosazidan** [facebook/react-native#30096]
## Description
I can't compile the app on Windows, althrough it can be normally compiled on MacOS. The dev env on the Windows computer is set up and if I init a new react native project I can normaly compile it. I have tried quite a few things but it looks like it is a bug. Its not connected with the code on the project because if i delet the modules that are cousing the problem, new ones appear.

I would greatly appreciate any help.

## React Native version:
System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-3740QM CPU @ 2.70GHz
    Memory: 4.68 GB / 15.89 GB
  Binaries:
    Node: 12.18.4 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2
      System Images: android-29 | Android TV Intel x86 Atom, android-29 | Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom_64, android-30 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
    Windows SDK:
      AllowAllTrustedApps: Disabled
      Versions: 10.0.17763.0
  IDEs:
    Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6626763
    Visual Studio: Not Found
  Languages:
    Java: 1.8.0_262
    Python: 3.8.6
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.3 => 0.63.3
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce

1. npm install
2. npx react-native start
3. npx react-native run-android

## Expected Results
The app should normaly compile and start.

## Snack, code example, screenshot, or link to a repository:

[Mon Sep 28 2020 09:21:11.628]  BUNDLE  ./index.js 

error: Error: Unable to resolve module `../components/input/Input` from `pages/ResetPasswordChange.js`: 

None of these files exist:
  * components/input/Input(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * components/input/Input/index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
    at ModuleResolver.resolveDependency (/home/aljosa/hometown/ipark/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:163:15)
    at ResolutionRequest.resolveDependency (/home/aljosa/hometown/ipark/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (/home/aljosa/hometown/ipark/node_modules/metro/src/node-haste/DependencyGraph.js:287:16)
    at Object.resolve (/home/aljosa/hometown/ipark/node_modules/metro/src/lib/transformHelpers.js:267:42)
    at /home/aljosa/hometown/ipark/node_modules/metro/src/DeltaBundler/traverseDependencies.js:434:31
    at Array.map (<anonymous>)
    at resolveDependencies (/home/aljosa/hometown/ipark/node_modules/metro/src/DeltaBundler/traverseDependencies.js:431:18)
    at /home/aljosa/hometown/ipark/node_modules/metro/src/DeltaBundler/traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/home/aljosa/hometown/ipark/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)

![Screenshot_20201002-154849](https://user-images.githubusercontent.com/21339432/94931720-620e3280-04c8-11eb-850f-6ec5fe5fc8d0.jpg)

![Screenshot_20201002-154854](https://user-images.githubusercontent.com/21339432/94931707-5f134200-04c8-11eb-9538-571bc3201b61.jpg)

**Comment by ps0305** [comment]
@aljosazidan please try theses command:
```
rm -rf node_modules
npm install
npx jetify
cd android && ./gradlew clean && cd ..
```

**Comment by aljosazidan** [comment]
@ps0305 thank you. This solved the problem.

**Comment by putrantoz** [comment]
@ps0305 thank you. my problem solved too
