### ISSUE TITLE
[SectionList]  stickyHeaderIndices doesn't stick the list header component

### ISSUE THREAD

**Issue by IoanaBdn** [facebook/react-native#30108]
### Description

The SectionList component does have a prop called `stickyHeaderIndices` that says that do that: 

> An array of child indices determining which children get docked to the top of the screen when scrolling. For example, passing stickyHeaderIndices={[0]} will cause the first child to be fixed to the top of the scroll view. This property is not supported in conjunction with horizontal={true}.

But it seems like is doing nothing from what it's says to do. I tryed to used `ListHeaderComponent` to render the section list header and expected to  dock it by using `stickyHeaderIndices={[0]}`.

### Reproduction Steps and Sample Code

Snack: https://snack.expo.io/@ioanab/sticky-horizontal-menu-

### Additional Information

- react-native-cli: 2.0.1

- react-native: 0.63.2
- Platform: both

### Environment Information

```
System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 196.19 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.17.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
  Languages:
    Java: 13.0.2 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by lunaleaps** [comment]
@IoanaBdn I see that the `stickyHeaderIndices` is on [ListView](https://reactnative.dev/docs/listview#stickyheaderindices) rather than [SectionList](https://reactnative.dev/docs/sectionlist) which might be why it's not working. Have you tried using a ListView instead?

**Comment by fengbujue2022** [comment]
same issue while use ScrollView with horizontal={true} , stickyHeaderIndices does not working.
