### ISSUE TITLE
<Image loadingIndicatorSource={{uri: base64Image}}> doesn't load

### ISSUE THREAD

**Issue by devonkoch** [facebook/react-native#30110]
## Description
Title describes it. While trying to use a data/base64 image type in the `loadingIndicatorSource` prop, the image doesn't load. The image loads in the `source` prop. I am explicitly specifying the `width` and `height` in the `style` prop.

To get around it, I'm using an `<ImageBackground />`

```
const base64loaderGif = "data:image/gif;base64,R0lGODlhIAAg..."

return (
  <ImageBackground
    source={{ uri: base64loaderGif }}
    style={styles.myImageStyle}
  >
    <Image
      style={styles.myImageStyle}
      source={{ uri: myNetworkedImage }}
    />
  </ImageBackground>
)
```
## React Native version:
React Native v39.0.0

**Comment by dulmandakh** [comment]
It only supports local file path, sorry.
