### ISSUE TITLE
Need help with React-Native version 0.57.8 compatibility with Xcode version 11 or latest

### ISSUE THREAD

**Issue by fransjesky** [facebook/react-native#30118]
Hello!

I have a 2 years old react native project which using react native version 0.57.8. I've tried to run it from my IDE terminal using `npx react-native run-ios` and it throws an error like this

<img width="1640" alt="Screen Shot 2020-10-07 at 09 54 23" src="https://user-images.githubusercontent.com/52071677/95283248-829e0a00-0885-11eb-9108-e1845443591e.png">

The problem is i already have iPhone X simulator installed on my Xcode and i've tested it by creating a new RN project and run it using npx react-native run-ios and it worked on the iPhone X simulator. I've tried to open it directly from Xcode version 11 and 12, but it failed to build with an error message:

<img width="1399" alt="Screen Shot 2020-10-07 at 10 10 44" src="https://user-images.githubusercontent.com/52071677/95283197-639f7800-0885-11eb-82bb-42de83d22a9f.png">

I tried to run the project using Xcode 10.1 and it worked even there is a lot of issues listed. So, what i wanted to ask is, will i be able to run and build my project on Xcode version 11 or latest if i upgrade my project react-native version?

## React Native version:
React Native Environment Info:
    System:
      OS: macOS 10.15.7
      CPU: x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
      Memory: 30.63 MB / 8.00 GB
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.10.0 - ~/.nvm/versions/node/v14.10.0/bin/node
      Yarn: 1.22.5 - /usr/local/bin/yarn
      npm: 6.14.8 - ~/.nvm/versions/node/v14.10.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
    npmPackages:
      @storybook/react-native: ^3.4.10 => 3.4.10 
      react: 16.6.3 => 16.6.3 
      react-native: 0.57.8 => 0.57.8 
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Git cloned the project
2. Download and install all the dependecies using `yarn install`
3. Tried to run the app using `npx react-native run-ios`
4. Failed to run and build the app

## Expected Results
The expected result is able to run and build the RN project app from terminal, shown the app is working on any iOS devices simulator and on latest version of Xcode.

**Comment by ravirajn22** [comment]
I don't see why it won't work. Upgrade to latest version of react-native which supports xcode 12 and migrate your swift 3 to 5 (I don't know how to do that, but should be straightforward). Upgrade your dependencies. You should be good to go.
