### ISSUE TITLE
URL polyfill doesn't throw error with invalid urls

### ISSUE THREAD

**Issue by martinheidegger** [facebook/react-native#30116]
## Description

The `URL` class in Browsers/Node is expected to throw an error if the given URL is invalid. This is a simple trick used also by library developers ([is-url-superb](https://github.com/sindresorhus/is-url-superb/blob/master/index.js)) to validated if a URL is valid or not. However the `URL` polyfill used in react-native doesn't throw an error, breaking this use.

## React Native version:

<details><summary>version output</summary>
<p>

```
System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i7-6660U CPU @ 2.40GHz
    Memory: 23.29 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: Not Found
    npm: 6.14.8 - ~/.nvm/versions/node/v12.16.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 24, 25, 28, 29
      Build Tools: 28.0.3, 29.0.0
      System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64
      Android NDK: 20.0.5594570
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  Languages:
    Java: 14.0.1 - /usr/local/opt/openjdk/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

</p>
</details>

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Setup react-native runtime
2. run `new URL('hello')`

## Expected Results

```
TypeError: Failed to construct 'URL': Invalid URL
```

## Snack:

https://snack.expo.io/@consento/lonely-beef-jerky

**Comment by newyankeecodeshop** [comment]
I recommend using https://github.com/charpeni/react-native-url-polyfill to get a proper `URL` implementation if you have code that depends on it. The `URL` implementation in React Native is just there to facilitate the `Blob` implementation AFAIK.

**Comment by martinheidegger** [comment]
Thank you for this workaround hint. Does that mean that it is expected/planned for API's in react-native to not be compatible with standards?
