### ISSUE TITLE
Android Native UI Components - How to get Activity from reactContext

### ISSUE THREAD

**Issue by marcshilling** [facebook/react-native#3013]
I'm relatively new to Android development so forgive me if I'm missing something here, but I'm trying to bridge over a bunch of native UI components to React Native, and the biggest thing I'm lacking is access to an `Activity`...

Some use cases:
- I need an `Activity` to call `.getFragmentManager()` to be able to add a `Fragment` to my view.
- I need an `Activity` to call `.getWindow()` to be able to add the `FLAG_KEEP_SCREEN_ON` to disable the screen idle timer. 

Everything I've read online mentions getting access to the `Activity` by casting your context like so:
```FragmentManager fragmentManager = ((Activity) mContext).getFragmentManager();```

However, `com.facebook.react.uimanager.ThemedReactContext cannot be cast to android.app.Activity`

How can I get an `Activity` in a native UI component bridge? Or am I thinking about this the wrong way?

**Comment by astreet** [comment]
See https://github.com/facebook/react-native/issues/2996

**Comment by xuebinliu** [comment]
please use ThemedReactContext class instance to invoke getCurrentActivity function to get the Activity.

best regard
