### ISSUE TITLE
Failing to connect to Metro on iOS 14 and Big Sur

### ISSUE THREAD

**Issue by lucasjohnston** [facebook/react-native#30139]
## Description
My RN app sometimes decides to connect to Metro, sometimes not and still works (but with incredibly long load times), and sometimes it just crashes - it's totally random. Same when using `react-native run ios --device` and Xcode (it's definitely in the Debug scheme). I suspect it has something to do with iOS 14 permissioning - when it does work, it happens after clicking Allow to accessing other network devices and force quit/opening the app. 
I've looked through console logs and am not closer to figuring out why this is happening.

Running iOS 14.0.1, macOS 11 beta 8 (20A5374i).

## React Native version:
For some reason `react-native` isn't recognising my local settings, so also attached an excerpt of my package.json.
```
  "dependencies": {
    "react": "16.13.1",
    "react-native": "0.63.3",
  },
```
```
System:
    OS: macOS 11.0
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 741.13 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.18.1 - ~/.nvm/versions/node/v12.18.1/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v12.18.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3
      System Images: android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 12.0/12A7209 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_251 - /Users/lucas/.jenv/shims/javac
    Python: 3.8.5 - /usr/local/opt/python/libexec/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Again, this is hard to do as it's a random occurrence.

## Expected Results
The app not to crash.

## Snack, code example, screenshot, or link to a repository:
Again, this is hard to do as it's a random occurrence.

**Comment by 471595249** [comment]
+1 The problem arises in my project

**Comment by amazing-space-invader** [comment]
I think I have same issue when I enable debug. If debug disabled everything seems OK

**Comment by oromis300** [comment]
I have the same problem. How do you disable debug ?

**Comment by yoavapi** [comment]
Any update on this with Big Sur 11.1?

**Comment by firofame** [comment]
same problem with Catalina. iPad OS 14,

**Comment by natezmatthews** [comment]
Same problem here: Big Sur 11.1, XCode 12.1, React Native 0.63.4

**Comment by AWDGroup** [comment]
In my case, the issue was Watchman not responding and I was able to fix it after following these instructions:
https://github.com/facebook/watchman/issues/376#issuecomment-254017620

**Comment by surajprasad13** [comment]
i have same issue a brand new laptop of mac updating bigsur i created a bare project after all things installing but it is howing IPHONE_DEPLOYMENT_TARGET issue

**Comment by praveenpaliBB** [comment]
not working

> I think I have same issue when I enable debug. If debug disabled everything seems OK

I have debug disabled but getting same 'metro and the client are out of sync reload to rconnect'

**Comment by rikur** [comment]
I was stuck for hours, failing to load anything from the packager. What fixed it for me was:
```
sudo sysctl -w kern.maxfiles=10485760
sudo sysctl -w kern.maxfilesperproc=1048576
```
found at https://facebook.github.io/watchman/docs/install.html

Kindly note that there are instructions on how to persist the settings over reboots on the same link.
