### ISSUE TITLE
Denial of Service vulnerabilities with npm

### ISSUE THREAD

**Issue by kockok** [facebook/react-native#30134]
## Description
3 vulnerabilities raised by npm and could not be fixed by running `npm audit fix`

## React Native version:
"react-native": "0.63.3",
-> As I could hardly remember, there's no vulnerabilities in 0.62

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. npm audit
2.npm audit fix

## Expected Results
no vulnerabilities

## Snack, code example, screenshot, or link to a repository:
![Screenshot 2020-10-08 at 5 49 08 PM](https://user-images.githubusercontent.com/232541/95443042-aa2cc980-098e-11eb-8e7c-cfc74f08ac61.png)

**Comment by ravirajn22** [comment]
These libraries are used by `react-native-community/cli` (from screenshots) which is in turn used only during development. So you can safely ignore Denial of Service warnings.

**Comment by kockok** [comment]
If the collaborators think that it's trivial, please close this issue.

**Comment by nickyout** [comment]
Looks like an upgrade to `fbjs@2` would solve the issue. It changes the dependency to `cross-fetch`. Their latest version `3.0.6` uses `node fetch@2.6.1`.
