### ISSUE TITLE
Images are not loading in react native Ios but loading in android??

### ISSUE THREAD

**Issue by palavelli57** [facebook/react-native#30132]
## Description
previously I used test images that are working in both ios and android. (image size 80 to 160 kb)
Later changes to real images, which are about size 160 to 220 kb. Now these updated images loading in android but not in ios.
Please help me. I am not getting any errors.

λ react-native --version
react-native-cli: 2.0.1
react-native: 0.61.5

**Comment by timomeara** [comment]
if you're building on OSX w/ xCode 12.0.1 you'll need to upgrade to RN 0.63.3 to fix this
 see #29279
