### ISSUE TITLE
[ios][master] RCTConvert fails to convert NSNumber to NSString in debug scheme, works fine in release

### ISSUE THREAD

**Issue by chirag04** [facebook/react-native#3014]
I'm trying to pass color string from js to objective-c. But seems like color processing was moved to js recently which broke RCTConvert in debug mode. 

I can bring it down to these lines:
https://github.com/facebook/react-native/blob/master/React/Base/RCTConvert.m#L36-L50

In release mode it works fine, in debug mode it always errors out.

Here is the eg code for replicating:
```js
<DashedBorder
    color={processColor('#FF0000')}
    style={styles.badgeContainer}
    lineDashPattern={[4,4]}>
        <Text style={styles.badge}>{this.state.badge}</Text>
</DashedBorder>
```

In objective-c 
```
- (void)setColor:(NSNumber *)color
{
  _border.strokeColor = [RCTConvert UIColor:color].CGColor;
}
```

RCTConvert fails in objective-c above.

cc @nicklockwood  since your commit(https://github.com/facebook/react-native/commit/0487c55c254e765e97379300b6efb3a7ee22916b) seems to affect this

**Comment by ide** [comment]
Why are you using `color={processColor('#FF0000')}` instead of `color="#FF0000"`?

**Comment by chirag04** [comment]
Because color processing was moved to js recently(https://github.com/facebook/react-native/commit/9a2d05d9b2aea459ef3b3e92376cf15bca4d17fa). RCTConvert only accepts Number for UIColor conversion now.

**Comment by PhilippKrone** [comment]
Same issue here, currently not able to convert from Number to UIColor

**Comment by chirag04** [comment]
@PhilippKrone It works for me in release mode. just a headsup. Still a valid bug though.

**Comment by ide** [comment]
@nicklockwood might be out right now. If this is important to you send a PR.

**Comment by chirag04** [comment]
@PhilippKrone is the component you using open sourced?

**Comment by PhilippKrone** [comment]
@chirag04 No its no real component, just something I use internally. But taking a look at your code from above, it's pretty much the same.

**Comment by chirag04** [comment]
So, It seems you need to change the parameter to ``NSNumber`` on the objective-c side. As for me i did change it in ``.m`` file but forgot to change it in the viewManager header file where it is exported.

Not sure if it's the same problem for you @PhilippKrone . Closing it for now. 
Thanks @ide for the motivation. ;)
