### ISSUE TITLE
SecureTextEntry prop is not working in android with all the keyboard types.

### ISSUE THREAD

**Issue by mobhupath** [facebook/react-native#30148]
Issue: Toggling secureTextEntry prop works fine in iOS not in Android, in android for the password text field the initial value for secureTextEntry is set to true, it toggles the first time, but i don't see it toggled next time, this issue is seen in real device, it works fine in Android Emulator though, anyone still facing the same issue?
RN Version: 0.59.10

_Originally posted by @pedreviljoen in https://github.com/facebook/react-native/issue_comments/403732197_

**Comment by timomeara** [comment]
it looks like 0.63.3 re-introduced a number of issues around secureTextEntry that were resolved years ago.
i'm dealing with a font issue that comes up when secureTextEntry=true
#30123

**Comment by mobhupath** [comment]
hey @timomeara, i was going through the change log of react native https://github.com/react-native-community/releases/blob/master/CHANGELOG.md#v0633, i don't see anything related to secureTextEntry prop not working in android or anything similar to this issue.

**Comment by timomeara** [comment]
> hey @timomeara, i was going through the change log of react native https://github.com/react-native-community/releases/blob/master/CHANGELOG.md#v0633, i don't see anything related to secureTextEntry prop not working in android or anything similar to this issue.

there are quite a few issues around the secureTextEntry prop, keyboard types and font styles
i have not tried toggling the secureTextEntry values, so i can't speak to that... my problem was with placeholder styles not working

the title of this issue appears to be a documented known issue
[https://reactnative.dev/docs/textinput#known-issues
](https://reactnative.dev/docs/textinput#known-issues)


regardless, the history of TextInput and secureTextEntry is long and sordid
#23059
#22781
#22210
#7936
#6564
#6149
#5859
#5710
#5478
#4600
#4435
#3742

**Comment by mobhupath** [comment]
> > hey @timomeara, i was going through the change log of react native https://github.com/react-native-community/releases/blob/master/CHANGELOG.md#v0633, i don't see anything related to secureTextEntry prop not working in android or anything similar to this issue.
> 
> there are quite a few issues around the secureTextEntry prop, keyboard types and font styles
> i have not tried toggling the secureTextEntry values, so i can't speak to that... my problem was with placeholder styles not working
> 
> the title of this issue appears to be a documented known issue
> [https://reactnative.dev/docs/textinput#known-issues ](https://reactnative.dev/docs/textinput#known-issues)
> 
> regardless, the history of TextInput and secureTextEntry is long and sordid
> #23059
> #22781
> #22210
> #7936
> #6564
> #6149
> #5859
> #5710
> #5478
> #4600
> #4435
> #3742

It won't work even if i use keyboard types other than keyboardType="email-address" or keyboardType="phone-pad"

**Comment by timomeara** [comment]
> > > hey @timomeara, i was going through the change log of react native https://github.com/react-native-community/releases/blob/master/CHANGELOG.md#v0633, i don't see anything related to secureTextEntry prop not working in android or anything similar to this issue.
> > 
> > 
> > there are quite a few issues around the secureTextEntry prop, keyboard types and font styles
> > i have not tried toggling the secureTextEntry values, so i can't speak to that... my problem was with placeholder styles not working
> > the title of this issue appears to be a documented known issue
> > [https://reactnative.dev/docs/textinput#known-issues ](https://reactnative.dev/docs/textinput#known-issues)
> > regardless, the history of TextInput and secureTextEntry is long and sordid
> > #23059
> > #22781
> > #22210
> > #7936
> > #6564
> > #6149
> > #5859
> > #5710
> > #5478
> > #4600
> > #4435
> > #3742
> 
> It won't work even if i use keyboard types other than keyboardType="email-address" or keyboardType="phone-pad"

"it won't work"... do you mean toggling the prop value?
did you try playing with this?
https://reactnative.dev/docs/textinput#keyboardtype 
visible-password (android only)

**Comment by Anzormumladze** [comment]
upgrade to 61.0 version

**Comment by Rafatcb** [comment]
I was having this problem too. Tried to reproduce on a Snack, but it seems to be working there.

So I tried to stop using my customized `TextInput` and replaced with the default one from `react-native`, without any styling, and it worked. Then I replaced it by my `TextInput` and... it kept working.

Maybe it has something to do with `fontFamily`? I tried to reproduce the problem again but wasn't able to.

Btw, my `TextInput` is just the default one with some styles, default props, animation and text handling in state.

**Comment by padil** [comment]
use `default`, working for me ;)

**Comment by SawRosetngg** [comment]
secureTextEntry works if you set autoCapitalize={'none'}.

**Comment by fantasyado** [comment]
> secureTextEntry works if you set autoCapitalize={'none'}.

This works for me.   But how can come up with this fix...

**Comment by marcosnataqs** [comment]
Nothing works for me yet! Someone have another solution for this problem?

**Comment by onurtsc** [comment]
> secureTextEntry works if you set autoCapitalize={'none'}.

This worked on my code!

**Comment by shrawanfv** [comment]
secureTextEntry works if you set autoCapitalize={'none'}. not working
![WhatsApp Image 2023-08-08 at 18 48 29](https://github.com/facebook/react-native/assets/139120753/55fd80ad-cbdc-482a-9a74-eb5aedd0980e)

**Comment by TheRealMikeD** [comment]
I have a sign-up screen with a TextInput for password, and another to confirm the password.  They have identical properties.  The first TextInput hides the text as expected.  The second does not.  I have tried a lot of suggestions from this issue, and various StackOverflow issues.  None have worked so far.
react: 18.2.0
react-native: 0.72.6
expo: 49.0.0

Only fails on Android (works as expected on iOS). Testing on physical device.

**Comment by timoisalive** [comment]
For me `keyboardType="default"` worked.

I don't quite understand the difference between the Android only  `keyboardType="visible-password"` and `secureTextEntry` properties. Wouldn't it be enough to control visibility with the latter only...? 🤷

**Comment by TheRealMikeD** [comment]
Still not working for me.
react: 18.2.0
react-native: 0.74.2
expo: 51.0.14

**Comment by arsalannury** [comment]
> secureTextEntry works if you set autoCapitalize={'none'}.

This works also for me thank you.

**Comment by arsalannury** [comment]
> Still not working for me. react: 18.2.0 react-native: 0.74.2 expo: 51.0.14

Try this structure please. this works for me with
React 18.3
ReactNative 0.74.5
expo 51.0.31
