### ISSUE TITLE
Confusing `ensureNullTerminated` in NSDataBigString 

### ISSUE THREAD

**Issue by sueLan** [facebook/react-native#30145]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description

There is an expensive copy operation for data buffer when loading and parsing JS Bundle in RN.  In my case, I have a `4.8` MB JS bundle. The instrument shows it takes 15.81 MB in `NSData mutableCopyWithZone`,  which happens in  `ensureNullTerminated` in NSDataBigString. 

![image](https://user-images.githubusercontent.com/7471672/95567635-d1020300-0a55-11eb-83d9-cf72ae2b7305.png)

I followed the backtrace showing in the instrument. Saw that the brief process for RCTBridge loading JS bundle is like this: 
![image](https://user-images.githubusercontent.com/7471672/95567835-0b6ba000-0a56-11eb-86a6-674343863943.png)

Initially, I thought it has to treat data buffer in a contiguous region of memory as a [null-terminated byte string (NTBS)](https://en.cppreference.com/w/c/string/byte#:~:text=A%20null%2Dterminated%20byte%20string,(the%20terminating%20null%20character).&text=For%20example%2C%20the%20character%20array,%22cat%22%20in%20ASCII%20encoding.) .  In Objective-C, NSData is an immutable object. In order to add the `Null` byte, firstly, it has to copy the original immutable NSData object and construct a mutable object.  

But when I deleted these mutable copy and return the data directedly. Seems my app works fine. So does the `RNTester` . 

So I am confused now: 

- Is this code necessary? What is it for? 
- If it is necessary,  why doesn't the RN packager add `Null` to the bundle as its last byte to align the behavior of iOS lib? 
-  Does Android have a similar process to copy bundle? 

 

## React Native version:
Run `react-native info` in your terminal and copy the results here.
react-native: v0.63.3
device: iPhone 5s 
OS version: 12.4.8 

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. open `RNTester` in `react-native` repo. `react-native/packages/rn-tester`
2. find `ensureNullTerminated`  and set a breakpoint there 
3. run the `RNTester` 

## Expected Results
Describe what you expected to happen.

- remove this expensive copy operation or show us a way to avoid it, like building a JS bundle and add `Null` previously

## Snack, code example, screenshot, or link to a repository:

![image](https://user-images.githubusercontent.com/7471672/95569097-add85300-0a57-11eb-845f-a500a33019bd.png)

**Comment by kelset** [comment]
Really interesting finding, let me try to surface this to the FB team 👍

(and sorry, I'm just finding out about this now)

**Comment by PeteTheHeat** [comment]
Interesting find!! 

How do we know that creating a mutable copy is expensive?

Using the instruments memory profiler is probably not the tool we'd need here. Creating a copy and appending null shouldn't take up more space unless both data objects are retained. (Are they?)

We'd probably want to use the time profiler and measure the current impl vs. replacing `m_data = ensureNullTerminated(data);` with `m_data = data;`

**Comment by sueLan** [comment]
>  Using the instruments memory profiler is probably not the tool we'd need here. Creating a copy and appending null shouldn't take up more space unless both data objects are retained. (Are they?)

Yes. Both `data` object actually are different kinds of Class; different objects. 
![image](https://user-images.githubusercontent.com/7471672/112173233-5823eb80-8c30-11eb-81a2-8a90b9aea6ed.png)
The copied `data` object is about  ` 5058038 bytes` when using Xcode debugger to check it. 
```
(lldb) frame variable data 
(NSConcreteMutableData *) data = 0x0000600003a35fe0 5058038 bytes
```

**Comment by sueLan** [comment]
Env: 
- device: iPhone X 
- iOS 14.0
- Xcode Version 12.4
Project: 
- `rn-tester`
- building scheme: 
    -  Debug. 
    -  I tried to use release build, `source` is `nill` in this function in `release build` in `rn-tester`.
- bundle size: about  `4.8` MB 
For the time cost, I actually add some code to measure the diff
```
static NSData *ensureNullTerminated(NSData *source)
{
  if (!source || source.length == 0) {
    return nil;
  }

  NSUInteger sourceLength = source.length;
  unsigned char lastByte;
  [source getBytes:&lastByte range:NSMakeRange(sourceLength - 1, 1)];

  // TODO: bundles from the packager should always include a NULL byte
  // or we should we relax this requirement and only read as much from the
  // buffer as length indicates
  if (lastByte == '\0') {
    return source;
  } else {
    struct timeval val;
    gettimeofday(&val, NULL);
    int32_t t = val.tv_sec * 1000000 + val.tv_usec;
    
    NSMutableData *data = [source mutableCopy];
    unsigned char nullByte = '\0';
    [data appendBytes:&nullByte length:1];
    
    struct timeval tv;
    gettimeofday(&tv, NULL);
    int32_t t2 = tv.tv_sec * 1000000 + tv.tv_usec;
    printf("[ry]  copy diff %d \n", t2 - t);

    return data;
  }
}
```
| Num  | time diff (micro second) |
| ---- | ------------------------ |
| 1    | **1636**                 |
| 2    | **1351**                 |
| 3    | **5238**                 |
| 4    | **1249**                 |
| 5    | **2082**                 |

**Comment by PeteTheHeat** [comment]
> I tried to use release build, source is nill in this function in release build in rn-tester

Interesting. I took a quick look at the [bridge](https://github.com/facebook/react-native/blob/master/React/CxxBridge/RCTCxxBridge.mm#L1498) and had thought that this codepath would get hit in release build, but I never tested anything. 

If this only affects debug builds, probably not worth worrying about, right?

**Comment by sueLan** [comment]
> > I tried to use release build, source is nill in this function in release build in rn-tester
> 
> Interesting. I took a quick look at the [bridge](https://github.com/facebook/react-native/blob/master/React/CxxBridge/RCTCxxBridge.mm#L1498) and had thought that this codepath would get hit in release build, but I never tested anything.
> 
> If this only affects debug builds, probably not worth worrying about, right?

Hi, my bad. tried again. will hit  `ensureNullTerminated` `rn-tester` .

**Comment by sueLan** [comment]
So the impact is 
-   this copy operation will create a tmp object to obtain `mutable` data  to append `\0` . The memory cost of the object is related to the js bundle size. 
-    time cost looks like minor according to the tests i made. 

To my understanding,  `ensuring null` seems make no sense here.  
-   You got size of the data in  [NSDataBigString](https://github.com/sueLan/react-native/blob/master/React/CxxBridge/NSDataBigString.mm#L38)
 -  In `evaluateJavaScript` phase,  you will convert `NSDataBigString`
    to  [BigStringBuffer](https://github.com/sueLan/react-native/blob/3bbb0a43c2e84991f70ad7b15741ecac5d31ba66/ReactCommon/jsiexecutor/jsireact/JSIExecutor.h#L56); got its valid [size](https://github.com/sueLan/react-native/blob/3bbb0a43c2e84991f70ad7b15741ecac5d31ba66/ReactCommon/jsiexecutor/jsireact/JSIExecutor.h#L60)
    -  the final `JSStringRef` to `JSEvaluateScript` also uses the [size](https://github.com/sueLan/react-native/blob/3bbb0a43c2e84991f70ad7b15741ecac5d31ba66/ReactCommon/jsi/JSCRuntime.cpp#L417)
    
    Please correct me if i am wrong
