### ISSUE TITLE
reactnative从0.62.2升级到0.62.3，ios打包报错

### ISSUE THREAD

**Issue by TianShun2018** [facebook/react-native#30159]
![image](https://user-images.githubusercontent.com/45053600/95717483-968ba680-0c9f-11eb-80c4-fcb9eaa10114.png)

## React原生版本:
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Memory: 79.95 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.4.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5977832
    Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by zhuiye** [comment]
删除derivedData/your_app ，重新打包一次试试看

**Comment by TianShun2018** [comment]
> 删除derivedData/your_app ，重新打包一次试试看

我试试，谢谢

**Comment by TianShun2018** [comment]
> 删除derivedData/your_app ，重新打包一次试试看

没用。。我觉得就是少了包，。。加进去又找不到。。。。

**Comment by zhuiye** [comment]
> > 删除derivedData/your_app ，重新打包一次试试看
> 
> 没用。。我觉得就是少了包，。。加进去又找不到。。。。
https://github.com/react-native-community/upgrade-support/issues/24

**Comment by TianShun2018** [comment]
> > > 删除derivedData/your_app ，重新打包一次试试看
> > 
> > 
> > 没用。。我觉得就是少了包，。。加进去又找不到。。。。
> > 试下这个链接里面的方案,如果不行，在issue 里面搜搜
> > [react-native-community/upgrade-support#24](https://github.com/react-native-community/upgrade-support/issues/24)
> > https://github.com/react-native-community/upgrade-support/issues

我看了好多解决办法，都没解决问题，不知道哪里的问题，能加个微信麻烦帮我看看吗

**Comment by qinkangwu** [comment]
为什么要升级啊，小版本升级有必要吗？
