### ISSUE TITLE
Android and iOS use different user agent string for networking image requests

### ISSUE THREAD

**Issue by pke** [facebook/react-native#30163]
## Description

Network requests are performed under iOS using a default user agent that includes the app name like "appname/version ..." whereas Android only includes the version of the "okhttp" client but not the appname/version.
This can easily lead to bugs in apps when the endpoint/proxy expects a certain user-agent.

While there are ways to set the user agent for `fetch` requests this is not not so easily done globally for requests performed by the `Image` component.

## React Native version:

System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 563.72 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.3.0 - ~/.nvm/versions/node/v14.3.0/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v14.3.0/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v14.3.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /Users/user/.gem/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.8 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Request a remove image using `<Image source={{ uri: "some/remote/url"}}/>`

## Expected Results

The request `Image` performs should always have the same user agent on iOS and Android.

**Comment by dulmandakh** [comment]
Please feel free to open PR, and I would be happy to review it. Thanks
