### ISSUE TITLE
double-quoted include "YGMacros.h" in framework header, expected angle-bracketed instead

### ISSUE THREAD

**Issue by anutting** [facebook/react-native#30166]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Experiencing this error when building on Xcode 12:

node_modules/react-native/ReactCommon/yoga/yoga/YGEnums.h:10:10: double-quoted include "YGMacros.h" in framework header, expected angle-bracketed instead

## React Native version:
Run `react-native info` in your terminal and copy the results here.
react: ^16.13.1 => 16.13.1 
react-native: 0.63.2 => 0.63.2

**Comment by jbachand** [comment]
@anutting I had the same issue and the pre-released version of cocoapods fixes this. I'm not sure what caused it to break on older xcode versions.

Just run this before doing the next pod install and it clears it up:
`gem install cocoapods --pre`

Also see for reference: https://stackoverflow.com/questions/63951540/googledatatransport-is-throwing-double-quoted-include-in-framework-header-expect

**Comment by anutting** [comment]
Thanks for your quick response, that did work!

**Comment by Watersdr** [comment]
If anyone happens to come here because they're having this issue with their Appcenter builds, I added the line from @jbachand 's comment to my `appcenter-pre-build.sh` and it worked like a charm!

Thanks!
