### ISSUE TITLE
TextInput in Text component auto dismiss keyboard / cause crash when type keystroke in iOS

### ISSUE THREAD

**Issue by DdanhDao97** [facebook/react-native#30168]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
TextInput in Text component auto dismiss keyboard when update keystorke in iOS. In case of multiple TextInput, there is one TextInput component that when update cause app crash. (debugging in XCode shows error: Attempt to get layout metrics from dirtied Yoga node.)

## React Native version:
System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i3-8100B CPU @ 3.60GHz
    Memory: 1.16 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.4 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.6 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
  Languages:
    Java: 14.0.2 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Init a new Project
2. In App.js, add Text component inside View to replicate 'display:inline' of web
3. Add TextInput with View
4. Run ios project
5. Click on all TextInput field and start typing

## Expected Results
All text inputs works correctly

## Snack, code example, screenshot, or link to a repository:
[App.txt](https://github.com/facebook/react-native/files/5376468/App.txt) (app crash example)
[keyboard_close.txt](https://github.com/facebook/react-native/files/5376474/keyboard_close.txt) (keyboard auto dismiss example)

**Comment by rectified95** [comment]
Please format your repro in an Expo Snack - it'll make it easier to verify.

**Comment by fabriziobertoglio1987** [comment]
Do you still experience this issue? 

I have four years of experience maintaining facebook/react-native and I specialize in the Text and TextInput components. I currently have 58 [facebook/react-native PRs](https://github.com/facebook/react-native/pulls?q=is%3Apr+author%3Afabriziobertoglio1987+). 

If you still experience this issue, I will prepare a patched release with the fix.

Thanks a lot
