### ISSUE TITLE
Expo App crashes with TextInput

### ISSUE THREAD

**Issue by lahiru28** [facebook/react-native#30167]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
The web view works fine but the Expo android app crashes after building the javascript bundle.

## React Native version:
info Fetching system and libraries information...
(node:17996) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz
    Memory: 3.07 GB / 11.81 GB
  Binaries:
    Node: 14.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: Not Found
  Languages:
    Java: 11.0.8 - /c/Program Files/Common Files/Oracle/Java/javapath/javac
    Python: 2.7.18 - /c/Python27/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: https://github.com/expo/react-native/archive/sdk-39.0.2.tar.gz => 0.63.2
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce

1.add a TextInput field inside a view tag
2.run the project

## Expected Results
Should run fine in both mobile an web views

## Snack, code example, screenshot, or link to a repository:
![Bug](https://user-images.githubusercontent.com/41519945/95947813-07040600-0e0d-11eb-8360-561eff37c2bb.PNG)

**Comment by Simek** [comment]
Hi @lahiru28, I think you should report this issue in the [Expo repository](https://github.com/expo/expo).
