### ISSUE TITLE
[Android] How to build the ReactAndroid project on every "react-native run-android" ?

### ISSUE THREAD

**Issue by BerndWessels** [facebook/react-native#3017]
Hello

I want the `ReactAndroid` project to be rebuild whenever I run `react-native run-android` in my project.

How to do that, what needs to be installed?

Thank you
Bernd

**Comment by chirag04** [comment]
@ide @mkonicek should we publish android source(ReactAndroid) to npm just like we do with ios? It can be handy at times to change RN source while debugging.

[side-note] We can probably take out example dir on npm

**Comment by ide** [comment]
@chirag04 Yes, here is a PR: https://github.com/facebook/react-native/pull/3019

I also believe the build process could be significantly improved... right now it takes over a minute on a cold build and still takes 8-20 seconds on warm builds to compile & launch on device or simulator. Our goal should be ~3 seconds on a high-end Mac.

**Comment by chirag04** [comment]
Awesome.

Yup, we def need to make a better build system. I din't get enough time to look into buck. Like you said, buck could def. help here.

**Comment by darkyen** [comment]
@ide ~3 seconds on a high end mac would come to about 25 seconds on an avg machine :-| maybe have a switch ?

`react-native run-android --compile` ? maybe ?

**Comment by mkonicek** [comment]
If you want to test your changes to React Native you can do that inside the UIExplorer sample app. You can make it build RN from source on every change like this:
https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/android/app/build.gradle#L34

We need to document that better.

**Comment by satya164** [comment]
Docs have been added for this - https://facebook.github.io/react-native/docs/android-building-from-source.html#content

**Comment by benadamx** [comment]
@satya164 a note: react-native   has some dependency mismatches with current version of android ndk (android-ndk-r11*)  (arm-linux-androideabi-4.8 / arm-linux-androideabi-4.9), I had to dig up a copy of android-ndk-r10e to get this to work.

**Comment by seanbutler-truckulus** [comment]
is there a straightforward way to make homebrew install r10e?

**Comment by christopherdro** [comment]
https://github.com/facebook/react-native/blob/31bb85a210e8a6edba4f59df6eb36ccc5cc58d9e/docs/AndroidBuildingFromSource.md#download-links-for-android-ndk
