### ISSUE TITLE
[!] CocoaPods could not find compatible versions for pod "ReactCommon/callinvoker"

### ISSUE THREAD

**Issue by ProBobo** [facebook/react-native#30173]
[!] CocoaPods could not find compatible versions for pod "ReactCommon/callinvoker":
  In Podfile:
    ReactCommon/callinvoker (from `../node_modules/react-native/ReactCommon`)

None of your spec sources contain a spec satisfying the dependency: `ReactCommon/callinvoker (from `../node_modules/react-native/ReactCommon`)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

From:
Xcode 12.0.1
react-native@0.63.3
react@16.13.1

**Comment by soznanov** [comment]
I have the same issue

```
System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 335.30 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.13.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /Users/georgiyovechkin/.gem/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3
      System Images: android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_265 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by SErvin4390-joinpapa** [comment]
Seconding that comment above: I took 
`pod 'ReactCommon/callinvoker', :path => "../node_modules/react-native/ReactCommon"
`
and replaced it with 
`  pod 'React-callinvoker', :path => "../node_modules/react-native/ReactCommon/callinvoker"
`
It solved my problem! 


> 解决方法：
> pod 'ReactCommon/callinvoker', :path => "../node_modules/react-native/ReactCommon"
> pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
> 修改为
> pod 'React-callinvoker', :path => "../node_modules/react-native/ReactCommon/callinvoker"
> pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"

**Comment by natanloterio** [comment]
> Seconding that comment above: I took
> `pod 'ReactCommon/callinvoker', :path => "../node_modules/react-native/ReactCommon" `
> and replaced it with
> ` pod 'React-callinvoker', :path => "../node_modules/react-native/ReactCommon/callinvoker"`
> It solved my problem!
> 
> > 解决方法：
> > pod 'ReactCommon/callinvoker', :path => "../node_modules/react-native/ReactCommon"
> > pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
> > 修改为
> > pod 'React-callinvoker', :path => "../node_modules/react-native/ReactCommon/callinvoker"
> > pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"

If someone else is getting this problem even after this solution, pay attention to keep using single quotes instead of double quotes. That was my problem.
