### ISSUE TITLE
Invalid JSON response decoding on iOS

### ISSUE THREAD

**Issue by developius** [facebook/react-native#30181]
# Description
Sending requests using `apisauce`/`axios` results in invalid JSON data on iOS.
The data appears incorrect with seemingly random characters present. It changes every response and I can't identify any kind of pattern.

This is happening both on physical devices and in the simulator. I cannot reproduce on Android.

<img width="728" alt="Screen Shot 2020-10-15 at 3 03 11 PM" src="https://user-images.githubusercontent.com/5836587/96068150-c634eb80-0ef7-11eb-993c-b34f5fb71d05.png">

## React Native version:
```
System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz
    Memory: 689.28 MB / 24.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.19.0 - ~/.nvm/versions/node/v10.19.0/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v10.19.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /Users/finnian/.rvm/gems/ruby-2.7.1/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.7, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 11.7/11E801a - /usr/bin/xcodebuild
  Languages:
    Java: 12.0.2 - /Users/finnian/.jenv/shims/javac
    Python: 2.7.10 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 (also happened on 0.61.5)
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Call an endpoint - I can't really identify why it's only _some_ endpoints and not others. Maybe something to do with the response size - bigger responses seem to hit the error more often.

1. `const response = await this.apisauce.get('https://...')`

## Expected Results
I expect the response to be valid JSON.

Example of response headers:
```
{
  "access-control-expose-headers": "Request-Context",
  "cache-control": "no-cache",
  "content-length": "6634",
  "content-type": "application/vnd.api+json",
  "date": "Thu, 15 Oct 2020 02:14:51 GMT",
  "expires": "-1",
  "pragma": "no-cache",
  "request-context": "appId=cid-v1:<uuid>",
  "server": "Microsoft-IIS/10.0",
  "x-aspnet-version": "4.0.30319",
  "x-powered-by": "ASP.NET"
}
```

## Snack, code example, screenshot, or link to a repository:

||||
|-|-|-|
|<img width="300" src="https://user-images.githubusercontent.com/5836587/96067845-1b243200-0ef7-11eb-8b8a-943976b67c42.png">|<img width="300" src="https://user-images.githubusercontent.com/5836587/96067855-1eb7b900-0ef7-11eb-84d5-c228bc47b986.png">|<img width="300" src="https://user-images.githubusercontent.com/5836587/96067856-1fe8e600-0ef7-11eb-9df8-c3cb3436643c.png">|
|<img width="300" src="https://user-images.githubusercontent.com/5836587/96067857-20817c80-0ef7-11eb-9b9f-976071e25c9d.png">|<img width="300" src="https://user-images.githubusercontent.com/5836587/96067861-211a1300-0ef7-11eb-8e7d-721ef06246e4.png">| |

There are many other issues referencing very similar problems:
#29908 #29698 #29196 #27857

**Comment by developius** [comment]
I think this (and maybe the other issues) might be related to this: https://github.com/axios/axios/pull/2419
Looks like my response has a BOM character in it, which is throwing off JSON.parse in the axios library.
They have merged the patch but it's not been released yet. We're using [apisauce](https://github.com/infinitered/apisauce) so a bit of dependency hell.

**Comment by jasonsaayman** [comment]
Hi,

Version 0.21.0 has been released 🎉 please use that and let us know if that solves your issue.

Thanks

**Comment by safaiyeh** [comment]
Thanks for the issue @developius this seems to be an axios specific issue, closing as you can follow the progress there.
