### ISSUE TITLE
TintColor style isn't correctly applied when changed on Android on an Image

### ISSUE THREAD

**Issue by eliaslecomte** [facebook/react-native#30183]
## Description
When repeatedly changing the tintColor style on an image, it's not applied again on Android.

## React Native version:
System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 366.38 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.2 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /Users/elias.lecomte/.rvm/gems/ruby-2.6.3/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 26.0.3, 27.0.0, 27.0.3, 28.0.3, 29.0.0, 29.0.1, 29.0.2, 29.0.3, 30.0.0
      System Images: android-24 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom, android-25 | Google Play Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: 21.3.6528147
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_242-release - /usr/bin/javac
    Python: 3.7.4 - /usr/local/opt/python/libexec/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Apply a tintStyle
2. Apply no tintStyle
3. Apply a tintStyle

## Expected Results
TintColor style is correctly applied on every rerender.

## Snack, code example, screenshot, or link to a repository:
Repository: https://github.com/eliaslecomte/react-native-tintcolor-bug
Movie showing the bug: https://github.com/eliaslecomte/react-native-tintcolor-bug/blob/master/Screen%20Recording%202020-10-15%20at%2009.30.19.mov

**Comment by hank121314** [comment]
Hi @eliaslecomte .
I think this issue is related to #29717.
And I had made a pr #29830 .
Could you help me to test it?
