### ISSUE TITLE
Every fetch request gets stuck in Pending mode (iOS)

### ISSUE THREAD

**Issue by jonasgroendahl** [facebook/react-native#30187]
## Description
Every-time I try to do an HTTP request on iOS, the request gets stuck in pending mode and nothing happens. It works fine on android and it previously also worked for iOS but then I bundled up the android app for play store and now iOS is randomly broken...

I installed a library even to visually show that's stuck:

<img width="459" alt="Screen Shot 2020-10-15 at 9 42 25 PM" src="https://user-images.githubusercontent.com/23399953/96178508-cc46be80-0f2f-11eb-8c75-4f2cceb03a7d.png">

I have tried to ping different API's but every Fetch request just fails. The metro bundler has also become slower and the startup of the app is also slower than before. To me it's seems like a XCODE/iOS simulator issue perhaps?

## React Native version:
System:
    OS: macOS 10.15.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 781.70 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.10.1 - ~/.nvm/versions/node/v14.10.1/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.10.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.3 - /Users/dkjogrpe/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 23, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_222 - /usr/bin/javac
    Python: 3.7.1 - /Users/dkjogrpe/.pyenv/shims/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Released an android version and then suddenly iOS broken, seems like a random occurence

## Expected Results
I expected iOS to work as before

## Snack, code example, screenshot, or link to a repository:
I can send over the repo, it's currently private and it's not possible to make a minimal viable example since it's just all of a sudden happened. It could be a problem with the iOS simulator/XCODE though or something in the iOS setup, I have tried to roll back a bunch of commits and even on an old version, the problem is still there

**Comment by jonasgroendahl** [comment]
Did some more digging,

It works everywhere else but the iOS simulator. As a result i tried to reinstall XCode with the newest version but still same issue :(

**Comment by Desintegrator** [comment]
Has same issue, but its work well on ios (both simulator and real device), but in one of my Android app which is in store and hasn't been updated some of requests suddenly stopped receive answers

**Comment by jonasgroendahl** [comment]
For those people with similar problem, Temporarily solved this my opening Xcode and running the simulator from there. Everything updated to latest version.

Maybe close this issue

**Comment by safaiyeh** [comment]
Hi @jonasgroendahl appreciate investigating and sharing your solution. I'll close for now as it seemed to be an environment issue.

**Comment by adam-risberg** [comment]
I had this exact issue where fetch requests would simply not complete on mac in the ios simulator. I tried everything: updating npm packages, clearing all caches, creating a new react native app using the cli, rebooting my computer, pulling out my hair. What finally resolved it was updating osx from catalina to big sur. Now xcode wont start but my app works.

**Comment by adam-risberg** [comment]
The issue returned. Found [this issue](https://github.com/facebook/react-native/issues/20405), removing @babel/plugin-proposal-class-properties ultimately resolved the issue for me.
