### ISSUE TITLE
How to create more than one instance of a Native UI component?

### ISSUE THREAD

**Issue by caiphaav** [facebook/react-native#30190]
RN 0.63.3
Tried to create recyclerview native module and use it multiple times in the tabview
I showed export on the screenshot below
![Screen Shot 2020-10-16 at 12 49 52](https://user-images.githubusercontent.com/53155258/96249899-3140f980-0fae-11eb-8402-729ba96ea7cf.png)
 But each time its the same instance of UI component
Maybe I do something wrong?

**Comment by rectified95** [comment]
Sorry to hear your problem, but this is not a regression in RN. You should seek help in the open source community to address this problem.
