### ISSUE TITLE
Documentation for style properties

### ISSUE THREAD

**Issue by tjwudi** [facebook/react-native#302]
It is stated that not CSS properties are supported by StyleSheet API. So is there any documentation of all supported properties?

For example, `border` is not supported, but `borderWidth` is supported.

**Comment by ide** [comment]
The list at https://facebook.github.io/react-native/docs/flexbox.html#content gives a quick overview. i also find reading the code to work really well.

**Comment by tjwudi** [comment]
Well, thanks @ide . Really hard to find :) But I believe this is not a comprehensive list, because there is no `color`, `borderColor` etc.

**Comment by jrowny** [comment]
Yea, that's just the styles for Flexbox, but the styles are pretty succint.

Image styles: https://github.com/facebook/react-native/blob/72d3d724a3a0c6bc46981efd0dad8f7f61121a47/Libraries/Image/ImageStylePropTypes.js
Text styles: https://github.com/facebook/react-native/blob/72d3d724a3a0c6bc46981efd0dad8f7f61121a47/Libraries/Text/TextStylePropTypes.js
View styles: https://github.com/facebook/react-native/blob/72d3d724a3a0c6bc46981efd0dad8f7f61121a47/Libraries/Components/View/ViewStylePropTypes.js

**Comment by tjwudi** [comment]
Thanks @jrowny , I think I can send in a PR enhancing documenting that.

**Comment by tjwudi** [comment]
Closed, see #469
