### ISSUE TITLE
[Layout] Labels and image views baseline alignment support

### ISSUE THREAD

**Issue by zackhsuan** [facebook/react-native#3020]
Hi all,

Flexbox natively supports baseline alignment, but it seems like react-native has not implemented this yet. 
I am looking for any possibilities that I can align controls like labels or image views in baseline mode since the native auto layout tech supports baseline alignment. 

Anyone could help? Many thanks

**Comment by ide** [comment]
Could you open an issue over at the https://github.com/facebook/css-layout repo?

**Comment by zackhsuan** [comment]
Done it. Thanks

**Comment by mangogogos** [comment]
@ide is it possible to get a comment on this issue? Nothing has come of the issue on the css-layout repo

**Comment by ide** [comment]
I don't have an update here. As a general note, if a bug or feature is important to one of the Facebook apps, the chance it will get fixed is much, much higher than if it doesn't affect Facebook. So I'm assuming this issue hasn't affected fb and maybe hasn't affected anyone else enough to put together a set of high-quality PRs and tests.
