### ISSUE TITLE
iOS 14 TextInput jumping and auto-scrolling on tap

### ISSUE THREAD

**Issue by nfjones87** [facebook/react-native#30207]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Brand new build, nothing except the code below. Xcode version 12.0.1 iOS 14. RN 0.63.3. scrolling and tapping makes TextInput jump to random places. Happening on iPhone 11 Pro both simulator and device.

## React Native version:
System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 973.16 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.3 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Simply have a basic TextInput with enough text to produce a vertical scrollbar, then scroll and tap.

## Expected Results
The tap should place cursor at tapped position, and not autoscroll the TextInput to the wrong place. 

## Snack, code example, screenshot, or link to a repository:

```
export default class TextField extends Component {

   constructor(){
     super();
     this.state={textInput: ''}
   }

  handleChangeText = (textInput) => {
    this.setState({ textInput });
  }

    return (
        <View style={{flex: 1, backgroundColor: 'blue'}}>
           <TextInput 
            style={{marginTop: 100, height: 300, backgroundColor: 'white'}}
            value={this.state.textInput}
            multiline={true}
            onChangeText={this.handleChangeText}
          ></TextInput>     
        </View>
    )
}
```

![scrollbugg](https://user-images.githubusercontent.com/27112675/96520509-1972ab00-1224-11eb-80f8-dbf208adb080.gif)

**Comment by nfjones87** [comment]
Further information:

if I change the render to

`  render(){
    return (
      <ScrollView>
        <TextInput
          value={this.state.textInput}
          multiline={true}
          onChangeText={this.handleChangeText}
        />
      </ScrollView>
    );
  }`

the issue is resolved in every phone i have tested EXCEPT the iPhone 11 Pro. (works with iPhone 11 and iPhone 11 Pro Max). 

The issue on iPhone 11 Pro becomes that one cannot scroll the TextInput beyond the device's height unless I add a height to the TextInput. However, adding a height brings back the initial bug.

**Comment by safaiyeh** [comment]
Hi @nfjones87 appreciate the investigation. Definitely odd behavior, what would cause the iPhone 11 Pro to have different behavior?

**Comment by nfjones87** [comment]
Hi @safaiyeh , thanks for commenting. I really don't know what could cause the iPhone 11 Pro to have different behavior. I am simply toggling between different simulators, and it works on all except iPhone 11 pro. For whatever reason the iPhone 11 Pro needs the TextInput to have a set height or else it cannot scroll. However, setting a height produces the bug. 

To clarify, the bug in the gif above is reproducible on all phones, however it can be fixed on all phones except the iPhone 11 Pro.

**Comment by nfjones87** [comment]
Bump, anyone else experiencing this?

**Comment by RichardFevrier** [comment]
Sure @nfjones87 😌

**Comment by foloinfo** [comment]
I'm facing the same issue.
It happens when I specify the height of the TextInput.

I ended up avoiding this behavior by removing the `height` of TextInput and setting the height to the parent ScrollView (like in the comment above) and setting `scrollEnabled` to `false`

```
<ScrollView style={{ height: 300 }}>
  <TextInput
    scrollEnabled={false}
    style={{
      minHeight: 300,
    }}
  />
</ScrollView>
```

It still randomly scrolls when I tap the text but at least the cursor is pointed at where it should be so works a little better than setting the height directly, or maybe not.

**Comment by cenaHara** [comment]
hi @nfeignon Have you solved this problem yet?

**Comment by cenaHara** [comment]
> I'm facing the same issue.
> It happens when I specify the height of the TextInput.
> 
> I ended up avoiding this behavior by removing the `height` of TextInput and setting the height to the parent ScrollView (like in the comment above) and setting `scrollEnabled` to `false`
> 
> ```
> <ScrollView style={{ height: 300 }}>
>   <TextInput
>     scrollEnabled={false}
>     style={{
>       minHeight: 300,
>     }}
>   />
> </ScrollView>
> ```
> 
> It still randomly scrolls when I tap the text but at least the cursor is pointed at where it should be so works a little better than setting the height directly, or maybe not.

Yes, you can see the position cursor but the scroll view cannot automatically scroll

**Comment by ThanhNghia944** [comment]
It's an OS bug, I tried opening the app message from my phone, and it got the same

**Comment by YohanesFrangky** [comment]
hey, @nfjones87 have you fix this yet? i tried several open-source react native app, and try their textinput, and the bug is occured in all of them.

**Comment by tarouboy** [comment]
Have to rollback to RN0.61.5 because of this...

**Comment by tkharuk** [comment]
Experiencing the same issue.
Also, if I try to use "space" press to scroll select, Input goes wild and just blinks and flashes :(
This basically means users can not use scrollable editable content at all!

Any working workarounds to cover all platforms/versions?

@safaiyeh any plans from your side? I feel like this is a major one.

**Comment by YohanesFrangky** [comment]
> Tried to rollback to 0.61.5 and problem persists on iOS 14+.
> 
> Tried to wrap the TextInput ( scrollEnabled=false ) with ScrollView, now I can tap on anywhere to edit, which is good.
> However, I found two problems if wrapped by ScrollView:
> 
> 1. ScrollView won't scroll if you highlight the text and move upward/downward
> 2. Pressing "Enter" on the keyboard won't scroll to the newline unless you type something ( it's very confusing )

yes I have tried that, but I got a problem with newline as well, so I can't use that approach

**Comment by efstathiosntonas** [comment]
Experiencing the same, here's a duplicate issue: https://github.com/facebook/react-native/issues/30748

**Comment by efstathiosntonas** [comment]
It seems that the `animated:NO` causes the issue, setting it to `animated:YES` fixes it partially.

https://github.com/facebook/react-native/blob/896baf79d56e402cb1b0d3ca0eb5bd34e57d103b/Libraries/Text/TextInput/Multiline/RCTUITextView.m#L185-L190

Tested against iPhone 11 simulator and iPhone XS. 

But pressing space and moving up-down it's a bit jerky.

**Comment by tarouboy** [comment]
> **Update**: Removing completely the above lines seems to improve up-down carret movement. i do not know what side effects this might cause though.

It seems to be fixed about the jumpy behaviours. 

However, it will stay at the current position and won't scroll to the caret position after entering something new at the end of the textInput.

**Comment by iKoru** [comment]
hello, @tarouboy and everyone.
I'm experiencing the same issue and want to fix it. 
I tried @tarouboy 's solution and it seems the cursor is going to the right position but scroll effect is still the problem (goes to wrong place). 
any idea to fix this?

**Comment by tarouboy** [comment]
> hello, @tarouboy and everyone.
> I'm experiencing the same issue and want to fix it.
> I tried @tarouboy 's solution and it seems the cursor is going to the right position but scroll effect is still the problem (goes to wrong place).
> any idea to fix this?

Mine is working fine. At least no more users are reporting the same issue.
Not sure about your case without further information.

**Comment by fabriziobertoglio1987** [comment]
Do you still experience this issue? 

I have four years of experience maintaining facebook/react-native and I specialize in the Text and TextInput components. I currently have 58 [facebook/react-native PRs](https://github.com/facebook/react-native/pulls?q=is%3Apr+author%3Afabriziobertoglio1987+). 

If you still experience this issue, I will prepare a patched release with the fix.

Thanks a lot
