### ISSUE TITLE
Switch Component animation not working when using react-navigation on Android

### ISSUE THREAD

**Issue by Rafatcb** [facebook/react-native#30203]
## Description
Switch animation is not working on toggle inside a screen using `react-navigation` on Android.

I'm not sure if this is the right place to report this problem (if the issue is in the Switch component code or React Navigation lib). I tried to take a look at the Switch code but I didn't even find where the animation occurs. I already created an Issue in https://github.com/react-navigation/react-navigation/issues/8658 (July 30), but still without a response.

## React Native version:
I'm using Expo, so `npx react-native info` result is:
```
System:
    OS: Windows 10 10.0.18362
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
    Memory: 2.10 GB / 7.88 GB
  Binaries:
    Node: 12.14.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6821437
    Visual Studio: Not Found
  Languages:
    Java: Not Found
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

And `expo diagnostics`:
```
  Expo CLI 3.28.0 environment info:
    System:
      OS: Windows 10 10.0.18362
    Binaries:
      Node: 12.14.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6821437
    npmPackages:
      expo: ^39.0.0 => 39.0.3
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2
      react-native-web: ~0.13.7 => 0.13.16
    Expo Workflow: managed
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Create a Screen using React Navigation lib.
2. Create a Switch
3. Toggle Switch

## Expected Results
I expect Switch animation to work properly on toggle when using `react-navigation`.

## Snack, code example, screenshot, or link to a repository:

| [Snack with navigation (bug)](https://snack.expo.io/@rafatcb/switch-animation-bug-with-navigation) | [Snack without navigation (ok)](https://snack.expo.io/@rafatcb/switch-animation-without-navigation) |
| ------------------------------ | --------------------------- |
| ![Switch not animating on toggle](https://user-images.githubusercontent.com/26308880/88975091-04732500-d290-11ea-9a3b-1cf72048f85f.gif) | ![Switch animating on toggle](https://user-images.githubusercontent.com/26308880/88975116-0c32c980-d290-11ea-8517-89113ad747ee.gif) |

**Comment by SrBrahma** [comment]
Same issue here

**Comment by rectified95** [comment]
Sorry to hear you're facing this. However, this doesn't look like a regression in React Native - you're saying that without the extra library, the core component behaves as you'd expect. I encourage you to follow up with the library's maintainer, possibly give them a ping on Discord/Twitter.

**Comment by Rafatcb** [comment]
Ok. Anyway, thanks for the guidance  :smiley:

**Comment by SrBrahma** [comment]
Hmmm.... I am using the React Navigation in my App, but I ain't using it where the switch animation is not working. I change the value, and there is no animation.

I won't be able to fill the issue now as I am filled with work, but this looks like (also?) a RN issue.
