### ISSUE TITLE
FlatList onPress function rerender causes lag after usestate update

### ISSUE THREAD

**Issue by Acetyld** [facebook/react-native#30216]
## Description
So we have a flat list with roughly 200/300 buttons These buttons get passed a function that shows a ad after 5 clicks. So we used useState to count the click.

But.. because we update the count inside the function, it calls it selfs again and it rerenders all flatlist items/buttons and causes lag/delay.

**_"What do you mean with lag?"_** For example normally you can spam click the button and its all fine, but when the `setCount(prev => prev +1)` is uncommented it just slowly freeze and falls behind

## React Native version:
`
System:
    OS: Windows 10 10.0.19041
    CPU: (16) x64 AMD Ryzen 7 2700X Eight-Core Processor
    Memory: 15.91 GB / 31.94 GB
  Binaries:
    Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 23, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.0
      System Images: android-28 | Google Play Intel x86 Atom
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6514223
    Visual Studio: Not Found
  Languages:
    Java: Not Found
    Python: 3.8.6 - C:\Users\diong\.windows-build-tools\python27\python.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.2 => 0.63.2
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

`

## Steps To Reproduce
1. Make a new react-native project
2. Change ur app.js to this.

```js

import React, {useCallback, useState} from 'react';
import {TouchableOpacity,FlatList, View, Text} from 'react-native';

const data = ['IMAGINE 200 items here.']

const test = () => {
    const [count, setCount] = useState(0);

    const TestFunction = useCallback(async () => {
        setCount(prev => prev + 1);

        if (count === 5) {
            /*for example show a add*/
            showAd();
        }
    }, [count]);


    return (
        <View>
            <FlatList data={data} renderItem={() => React.useMemo(<TouchableOpacity onPress={TestFunction}>
                <Text>Test</Text>
            </TouchableOpacity>)}>

            </FlatList>
        </View>
    );
};


const showAd = () => {
    /*for example show a add*/
};


```
## Expected Results
No lags. Just good results =)

## Snack, code example, screenshot, or link to a repository:
`Code example is stated in the "reproduce" section

**Comment by FilipMaslovaric** [comment]
Why are you using an anonymous function in `renderItem`?
https://reactnative.dev/docs/optimizing-flatlist-configuration#avoid-anonymous-function-on-renderitem

**Comment by TaylorDale** [comment]
That would be an improvement, but I don't think it will fix OP's problem.

**Comment by SIRMED** [comment]
I'm facing the same issue. If any one found the solution, help would be appreciated.
