### ISSUE TITLE
Layout Animation Not Working in Docs, Is This Feature No Longer Supported?

### ISSUE THREAD

**Issue by danielstern** [facebook/react-native#30214]
## Description
Calling the LayoutAnimation API before calling a render seems to do nothing, on all devices.

## React Native version:
0.62.

## Steps To Reproduce
1. Go to the React Native docs: https://reactnative.dev/docs/layoutanimation
2. Try the examples in Snack, using Web, IOS, or Android.
3. Click the button that updates the view.

## Expected Results
Square should animate across the screen. Just teleports instead.

## Snack, code example, screenshot, or link to a repository:
https://snack.expo.io/?&preview=true&platform=web&iframeId=ku46vvkor5&supportedPlatforms=android,ios&name=LayoutAnimation&description=Example%20usage&waitForData=true

## Side Note
Could note get LayoutAnimation to work locally regardless of setup. Can someone share a link to a working Gist / SNACK of LayoutAnimation?

**Comment by brentvatne** [comment]
it appears to work as expected in https://reactnative.dev/docs/layoutanimation as far as i can tell?

![Screen Recording 2020-10-24 at 9 52 23 AM](https://user-images.githubusercontent.com/90494/97087419-f7d84180-15de-11eb-8793-b4b3acc4816c.gif)
