### ISSUE TITLE
ImageBackground doesn't re-render the image inside, on Orientation-Change & resizeMode='repeat'

### ISSUE THREAD

**Issue by kojow7** [facebook/react-native#30212]
## Previous Bug

This bug was [previously reported](https://github.com/facebook/react-native/issues/23675) about a year and a half ago by @xstable  with an older version of React Native and still exists in the latest version.

## Description

When using ImageBackground with resizeMode='repeat' the image does not get updated on an orientation change.

## React Native version:

"react": "16.13.1",
"react-native": "0.63.2",

## Steps To Reproduce

1. Insert an ImageBackground
2. Set the width and height
3. Run: react-native run-android
4. Rotate the screen

## Expected Results

I would expect the background image to continue to fill the entire screen when using repeat.

## Code Examples

The following code has the problems:

```
     <View
        style={{flex: 1, backgroundColor: 'green'}}>
        <ImageBackground
          style={{
            flex: 1,
            width: '100%',
            height: '100%',
          }}
          imageStyle={{resizeMode: 'repeat'}}
          source={require('../assets/images/my_background.jpg')}>
          <View>
            <Text>.... Other code here....</Text>
          </View>
        </ImageBackground>
      </View>
```

When rotated I end up seeing the green background on part of the screen and the actual background image no longer fills the entire screen.

I have also tried setting up the width and height in state so that a re-render is forced, but still it does not solve the problem. The following code does not work either:

```
<View
  onLayout={event => this.mylayoutchange(event)}
  style={{ flex: 1, backgroundColor: 'green' }}
>
  <ImageBackground
    style={{ flex: 1, width: this.state.width, height: this.state.height }}
    imageStyle={{ resizeMode: 'repeat' }}
    source={require('../assets/images/my_background.jpg')}
  >
    <View>
      <Text>.... Other code here....</Text>
    </View>
  </ImageBackground>
</View>
```

**Comment by jurica-penjgusic** [comment]
If anyone is looking  hacky solution, we have solved by having two url of same image pattern. 
When orientation or width is changed then just simply swap images.
It works as a charm.

Happy coding!

**Comment by jurica-penjgusic** [comment]
If anyone is looking hacky solution, we have solved by having two url of same image pattern.
When orientation or width is changed then just simply swap images.
It works as a charm.

Happy coding!
