### ISSUE TITLE
fetch issue on Android (can not receive response of some requests)

### ISSUE THREAD

**Issue by Desintegrator** [facebook/react-native#30229]
## Description

App which is currently in store and hasn't been updated for a long time (as well as backend) suddenly broke. Starting from September 21, Android version (ios keep working great) is not able to receive answers from some fetch requests and stuck into waiting for response (an ordinary requests with some data). It's neither resolving nor rejecting, just waiting (if disable internet on device its rejecting).

As we can see it in backend's (nginx) logs -- server make its work and send answer without any errors. (Remind that ios version works great at the same app version and with same backend)

## React Native version:

"react-native": "^0.61.5"

## Steps To Reproduce

1. send fetch request (some always works, some always not)

## Expected Results

1. Receiving answer

**Comment by euharrison** [comment]
@Desintegrator maybe it's not related with your issue, but about 2 years ago I had a similar problem and went deep into it, then I realised it was a problem with the networking resolving the DNS for api url and something with the OkHttp(?) lib

But happy part of story is that I just used axios lib with an explicit timeout property and it solved the problem

I also suggest you to try with different urls to debug

**Comment by Desintegrator** [comment]
@euharrison yeah, i think you're about right. i'm didn't dig such deep, but when we changed api url to another one, with completely same backend code, it's get fixed (magic).

Anyway, its most likely not related to react-native
Close the issue
