### ISSUE TITLE
FlatList: Unexpected onEndReached when updating contentContainerStyle

### ISSUE THREAD

**Issue by okwast** [facebook/react-native#30228]
## Description

Hey there 👋 
I recently discovered that when the `contentContainerStyle` of a FlatList changes this can result in unexpected calls of the `onEndReached` callback.

### Additional notes
I discovered that the behavior changes based on what is in the provided style.
E.g. in our application our style only contained a `paddingTop`.
With that I was only able to discover the unexpected calls to `onEndReached` on Android.

Additionally when increasing the amount of dummy data to 200 entries the issue seems to disappear.

### My thoughts

I wouldn't call this a huge bug, but it is an unexpected behavior.
And at least for us it caused a bug, where clearing our list caused our app to load the next page of it 🙈 

## React Native version:
Reproducible in Expo Snack.

We discovered it in
```
npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.2 => 0.63.2
```

## Steps To Reproduce

I created an [Expo Snack](https://snack.expo.io/@baumstumpf/onendreacheddifference) demoing the issue.
**Please note the issue does not occur in React Native Web, so please don't test with the web version in the snack**
The link: https://snack.expo.io/@baumstumpf/onendreacheddifference

1. Switch to either iOS or Android (**The web version works as expected**)
2. See a list of 50 elements being rendered.
3. Go to the logs
4. See in the console that onEndReached is being called without any scrolling, just by updating the style every second.

## Expected Results
I would expect that `onEndReached` is only called when I get close to the end.

## Snack, code example, screenshot, or link to a repository:
The snack link is: https://snack.expo.io/@baumstumpf/onendreacheddifference

## FYI

I changed the logic of our app to not update the style and the issue was gone.
So I don't urgently need a fix here, however I thought it is worth creating an issue here for further discussions and investigation and as it behaves as expected in Expo Web I would say it is a difference that is not really needed.

Thank you for your time 🙏

**Comment by cristianc-infocorp** [comment]
Also, with the **ListFooterComponent** property update, the same thing happens: the onEndReached event is logged twice.

```
 npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
```

code example:

`ListFooterComponent={isLoading ? ListFooterLoadingComponent : ListFooterComponent}`
