### ISSUE TITLE
react-native link not copying ttf fonts into expected locations

### ISSUE THREAD

**Issue by kyleschlosser** [facebook/react-native#30224]
# Description

`react-native link` command does not install fonts into ios and android project directories. 

I was following https://medium.com/@mehrankhandev/ultimate-guide-to-use-custom-fonts-in-react-native-77fcdf859cf4 which seems to indicate that `react-native link` will copy the fonts into the os specific directories and update and config files. I have created a new react-native project, copied ttf files into `src/assets/fonts` directory, created a configuration file named `react-native.config.js` in the project root, and then executed `react-native-link` but I cannot access the fonts and I do not see them in the ios or android directories. 

## React Native version:
System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
    Memory: 392.91 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.10.1 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.1, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2
      System Images: android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6858069
    Xcode: 12.1/12A7403 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_265 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.3 => 0.63.3
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce

Provide a detailed list of steps that reproduce the issue.

1. git clone https://github.com/kyleschlosser/react-native-fonts
2. cd react-native-fonts && yarn install
3. npx react-native link
4. find . -name "*".ttf
./src/assets/fonts/Heebo.ttf

## Expected Results
Expecting Info.plist to be updated and fonts copied into ios and android dirs

## Snack, code example, screenshot, or link to a repository:

https://github.com/kyleschlosser/react-native-fonts

**Comment by gokhandoslu** [comment]
Hi @kyleschlosser 
It was about assets configuration in react-native.config.js. https://github.com/kyleschlosser/react-native-fonts/pull/1

react-native.config.js content after update
```
module.exports = {
  project: {
    ios: {},
    android: {},
  },
  assets: ['./src/assets/fonts/'],
}
```
Linking:
```bash
npx react-native link  
info Linking assets to ios project
warn Group 'Resources' does not exist in your Xcode project. We have created it automatically for you.
info Linking assets to android project
success Assets have been successfully linked to your project
``` 
Result

```bash
find . -name "*".ttf
./android/app/src/main/assets/fonts/Heebo.ttf
./src/assets/fonts/Heebo.ttf
```

Info.plist updated

<img width="607" alt="Screen Shot 2020-10-29 at 00 31 18" src="https://user-images.githubusercontent.com/25434433/97498934-14c59980-197e-11eb-9851-9367a05fc2a0.png">

**Comment by szymonrybczak** [comment]
I think we can close this issue :) cc. @cortinico
