### ISSUE TITLE
Artifacts appear in images on Android devices with low screen resolutions

### ISSUE THREAD

**Issue by pranko17** [facebook/react-native#30230]
## Description
If you add a borderRadius on Android devices with a low screen resolution, artifacts appear on the images. Especially visible in images with text.

## React Native version:
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.0
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_252 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
## Device info
Android X
Default screen resolution: 2340 x 1080
Screen resolution set in device settings: 1560 x 720

## Example
```
import React from 'react';
import { View, Image, StyleSheet } from 'react-native';

export default class Example extends React.PureComponent {
  render() {
    return (
      <View style={styles.container}>
        <Image source={{ uri: this.props.uri }} style={styles.image} />
        <Image source={{ uri: this.props.uri }} style={[styles.image, styles.corners]} />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    backgroundColor: '#fff',
    marginHorizontal: 20,
  },
  image: {
    width: 'auto',
    height: 'auto',
    aspectRatio: 1035 / 675,
  },
  corners: {
    borderRadius: 15,
  },
});
```
![Screenshot_20201022_125656_com_habio](https://user-images.githubusercontent.com/37386099/96857365-9477d380-1467-11eb-9944-821f14e5b246.jpg)

The screenshot shows how, after adding the borderRadius, a ladder and irregularities appeared on the objects in the picture.

**Comment by fabriziobertoglio1987** [comment]
thanks for the issue. Can you provide us the image so we can try to reproduce this issue?
Could you also give us a step by step on how to set the emulator to reproduce this? Thanks a lot

**Comment by Skarabei007** [comment]
> thanks for the issue. Can you provide us the image so we can try to reproduce this issue?
> Could you also give us a step by step on how to set the emulator to reproduce this? Thanks a lot

It was possible to reproduce this only on physical Android devices. For example Huawei P20 has the ability to switch the resolution. At 2244x1080, everything is fine, and at 1496x720, artifacts appear in the images if add the border radius to them.

In this image, you can see that the edges of objects on it have become curves.
![96857365-9477d380-1467-11eb-9944-821f14e5b246](https://user-images.githubusercontent.com/37386099/109273716-9c83bd80-7823-11eb-8bf2-2a249a94fe49.jpg)
