### ISSUE TITLE
React-Native new setup causing problem with old projects

### ISSUE THREAD

**Issue by AliRehman7141** [facebook/react-native#30239]
## Description
I have flowed the instruction for react-native setup on macbook air. new projects are working fine but the old projects are not loading the images(assets like png icons) on simulator.

## React Native version:
OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-4250U CPU @ 1.30GHz
    Memory: 85.96 MB / 4.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.14.0 - /usr/local/bin/node
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 30
      Build Tools: 30.0.2
      System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6858069
    Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1

## Steps To Reproduce

1. Open old project in xcode or go to project directory in terminal
2. run project from xcode or run the command in terminal "react-native run-ios"

**Comment by crherman7** [comment]
@AliRehman7141 since you are running `react-native` version `0.61.5` on Xcode 12 and iOS 14 - please check this fix: https://github.com/facebook/react-native/issues/29279#issuecomment-658244428

**Comment by AliRehman7141** [comment]
@crherman7 Thanks, buddy It works for me

it works on different project with these two solutions:

/node_modules/react-native/Libraries/Image/RCTUIImageViewAnimated.m
Update this file like:

- (void)displayLayer:(CALayer *)layer
{
  if (_currentFrame) {
    layer.contentsScale = self.animatedImageScale;
    layer.contents = (__bridge id)_currentFrame.CGImage;
  } else {
+++    [super displayLayer:layer];
  }
}

----------------------------------- OR --------------------------

- (void)displayLayer:(CALayer *)layer
{
  if (_currentFrame) {
    layer.contentsScale = self.animatedImageScale;
    layer.contents = (__bridge id)_currentFrame.CGImage;
  } else {
+++    _currentFrame = self.image;
  }
}
