### ISSUE TITLE
RN 0.63.3 is adding some gray backgrounds in Android.

### ISSUE THREAD

**Issue by fervailanti** [facebook/react-native#30232]
## Description

Automatically after updating to RN `0.63.3` I had a problem with some gray colors in android (only Android, iOS works fine). It seems that some styles are being injected at some point in the build process, in addition, the logbox seems to be being modified as well (with same gray background). I can ensure that those styles are not being applied from the JavaScript code.

Any help can be useful. At the end you will find some screenshots.

## React Native version:
````
System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 841.49 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.13.1 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.1, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-R | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.1/12A7403 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_222 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.14.0 => 16.14.0 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
````

## Steps To Reproduce

1. Upgrade to React Native `v0.63.3`.
2. Run `react-native start`.
3. Run `react-native run-android`.

## Expected Results
Colors should look right.

## Snack, code example, screenshot, or link to a repository:

<img src="https://user-images.githubusercontent.com/54537095/96932165-d8cd9880-1494-11eb-9b0c-35a8ae33f0c8.png" width="250" align="left"/>

<img src="https://user-images.githubusercontent.com/54537095/96932587-79bc5380-1495-11eb-815d-a901d6e145ee.png" width="250" align="left"/>

**Comment by cecodor** [comment]
I am having the same issue with version 0.63.2

**Comment by alegadpen-iu** [comment]
Same issue v0.63.3 plus <Text /> nodes in android are getting clipped at the last line, upon my research this has something to be with lineHeight calculation.

**Comment by mariano-schemmari** [comment]
Same issue with version 0.63

**Comment by fervailanti** [comment]
For now I was able to consistently identify the problem with all `FlatList` and `Text` components and the LogBox mentioned before. `FatList` are rendered with a gray background and `Text` appear cut off at the bottom, as @alegadpen-iu says.

<img width="418" alt="Captura de Pantalla 2020-10-23 a la(s) 11 52 00" src="https://user-images.githubusercontent.com/54537095/97582148-2df93500-19d4-11eb-8945-0232e7ffea2d.png">

**Comment by cecodor** [comment]
The problem is also related with ScrollView, if I remove the ScrollView component from a View the problem disappear for that View, but not using ScrollView is not an option.

Anyone has a solution for this?

**Comment by fervailanti** [comment]
> The problem is also related with ScrollView, if I remove the ScrollView component from a View the problem disappear for that View, but not using ScrollView is not an option.
> 
> Anyone has a solution for this?

The workaround i found for `FlatList` for now is with `contentContainerStyle` prop but not really scalable.

**Comment by safaiyeh** [comment]
Thanks for the issue @fervailanti could you create a repro that demonstrates this issue so we can investigate?

**Comment by cecodor** [comment]
@fervailanti have you found a solution? I am still stuck with this, I have tried several things and i can't find what is causing this issue. I have another similar project and the colors are working fine on android (they both use the same react native version).

Maybe can you share with me the dependencies of your project to compare them with mine?

**Comment by fervailanti** [comment]
> @fervailanti have you found a solution? I am still stuck with this, I have tried several things and i can't find what is causing this issue. I have another similar project and the colors are working fine on android (they both use the same react native version).
> 
> 
> 
> Maybe can you share with me the dependencies of your project to compare them with mine?

I am in same situation, te problem is related to that specific project. We can't share the full project because of privacy reasons, but I decided with my teammates to share a copy of our project but only with an empty screen showing the issue (keeping all dependencies).

Probably we will be sharing this on monday. If it doesn't help or its imposible to reproduce the issue, then we could continue on private and see if we can get a solution together comparing projects 👍

**Comment by cecodor** [comment]
Hi, I was able to solve it! In my case the issue was with the library "@blackbox-vision/react-native-mercadopago-px", by removing it the problem got fixed. 

I created a new react native project and everything looked fine with all the default configuration, but when I installed all the dependencies from the problematic project (just copying the package.json), the new project started to have the problem with the styles too. So I removed the dependencies one by one and when removed the mercadopago library the problem with the colors got fixed.

I still don't known exactly what was causing the problem, but apparently was some type of incompatibility. I wasn't using it anyways so I don't have any problem by removing it 👍

**Comment by jmlacruz** [comment]
I have the same problem with the package @blackbox-vision/react-native-mercadopago-px and I still can't solve it. I suspect it's a package conflict between react-native or react-navigation, in some update of those packages they conflict.

What version of those packages do you have?

**Comment by chrisglein** [comment]
Still looking for a standalone repro here. If the issues is caused by another package then perhaps open an issue on that specific package? Is anyone hitting this and not depending on the above packages?

**Comment by fervailanti** [comment]
@cecodor @jmlacruz @chrisglein Hi, in my project I don't have `@blackbox-vision/react-native-mercadopago-px`, but I have [mercadopago/px-android](https://github.com/mercadopago/px-android) as android native module, and the library `@blackbox-vision/react-native-mercadopago-px` does something similar inside, they use [mercadopago/px-android](https://github.com/mercadopago/px-android), so, probably the issue should be on the original `mercadopago/px-android` android module.

**Comment by chrisglein** [comment]
@fervailanti Thanks for the clarification. Can you open an issue on that module's repo?
