### ISSUE TITLE
Undefined symbols for architecture x86_64:   "___darwin_check_fd_set_overflow", referenced from:       _RAND_poll in libcrypto.a(rand_unix.o)

### ISSUE THREAD

**Issue by EhsanSarshar** [facebook/react-native#30231]
after upgrading from `react-native:0.63.2 to react-native:0.63.3`
this error occurs.

```
_Undefined symbols for architecture x86_64:
  "___darwin_check_fd_set_overflow", referenced from:
      _RAND_poll in libcrypto.a(rand_unix.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)_
```

```
react-native:0.63.3
xcode:11.3.1
```

```
System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
    Memory: 49.35 MB / 8.00 GB
    Shell: 3.1.2 - /usr/local/bin/fish
  Binaries:
    Node: 12.13.0 - /usr/local/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.6 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.4 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 25, 27, 28, 29
      Build Tools: 27.0.3, 28.0.3, 29.0.2
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3.1/11C505 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_202-release - /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/javac
    Python: 2.7.10 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by yogieeka** [comment]
i solved problem with
1. comment all flipper function in podfile
2. remove flipperInit in appDelegate
3. remove openSSl in podfile.lock
4. pod install, 
5. clean project
6. run again,

**Comment by EhsanSarshar** [comment]
@yogieeka can you explain why ?

**Comment by varmab** [comment]
Same issue happening for me also and to colleague.

**Comment by Sbarcenas** [comment]
I have the same issue, when I trying to  build a project.

**Comment by EhsanSarshar** [comment]
one workaround That I found is updating xcode version from 11.3 to 11.7 or 12. but I haven't test it yet.

**Comment by EhsanSarshar** [comment]
@youngjl1 

> i solved problem with
> 
> 1. comment all flipper function in podfile
> 2. remove flipperInit in appDelegate
> 3. remove openSSl in podfile.lock
> 4. pod install,
> 5. clean project
> 6. run again,

Thanks a lot your solution also worked for me. but It's cost is not being able to use flipper. and also I don't know what will happen by disabling openssl

**Comment by safaiyeh** [comment]
Hello @EhsanSarshar thanks for the issue. For upgrade issues, head over to upgrade-support. 

Check out this issue: https://github.com/react-native-community/upgrade-support/issues/72

**Comment by EhsanSarshar** [comment]
@safaiyeh ok thanks. I reopen it in [upgrade-support](https://github.com/react-native-community/upgrade-support/issues/119). and also it seems a different issue as the one you point

**Comment by willymulyana** [comment]
I get this issue on Xcode 11.3.1, but it's not happen on Xcode 11.6.

**Comment by maulikdhameliya** [comment]
> i solved problem with
> 
> 1. comment all flipper function in podfile
> 2. remove flipperInit in appDelegate
> 3. remove openSSl in podfile.lock
> 4. pod install,
> 5. clean project
> 6. run again,

I tried this and it worked it's a temporary solution if you don't want to upgrade Xcode. 
Upgrading Xcode will also solve this.

**Comment by DaggieBlanqx** [comment]
I have just encountered this error.
I am new to the iOS side of reactnative.
Where do I find appDelegate .
Could you please guide me using/with screenshots?
Thank you.

> > i solved problem with
> > 
> > 1. comment all flipper function in podfile
> > 2. remove flipperInit in appDelegate
> > 3. remove openSSl in podfile.lock
> > 4. pod install,
> > 5. clean project
> > 6. run again,
> 
> I tried this and it worked it's a temporary solution if you don't want to upgrade Xcode.
> Upgrading Xcode will also solve this.

**Comment by adityatandon007** [comment]
@DaggieBlanqx You will find AppDelegate file under `ios/yourproject/AppDelegate.m`. You can either remove the entire function or simply comment the line as shown screenshot
![Screen Shot 2020-11-12 at 6 36 31 PM](https://user-images.githubusercontent.com/25108385/98943832-1febfe00-2516-11eb-9222-7675c1271de4.png)

**Comment by Ajithmanali** [comment]
> i solved problem with
> 
> 1. comment all flipper function in podfile
> 2. remove flipperInit in appDelegate
> 3. remove openSSl in podfile.lock
> 4. pod install,
> 5. clean project
> 6. run again,

Thanks @yogieeka

**Comment by djnewage** [comment]
This issue still persist for me on xcode 11.3.1

**Comment by sorakrisc** [comment]
downgrading  flipper-folly and openssl-universal in Podfile.lock worked for me

```
- Flipper-Folly (2.2.0):
    - boost-for-react-native
    - CocoaLibEvent (~> 1.0)
    - Flipper-DoubleConversion
    - Flipper-Glog
    - OpenSSL-Universal (= 1.0.2.19)

- OpenSSL-Universal (1.0.2.19):
    - OpenSSL-Universal/Static (= 1.0.2.19)
  - OpenSSL-Universal/Static (1.0.2.19)
```

**Comment by Dror-Bar** [comment]
> downgrading flipper-folly and openssl-universal in Podfile.lock worked for me
> _note im using xcode 11.3.1 and I cant upgrade it_
> 
> ```
> - Flipper-Folly (2.2.0):
>     - boost-for-react-native
>     - CocoaLibEvent (~> 1.0)
>     - Flipper-DoubleConversion
>     - Flipper-Glog
>     - OpenSSL-Universal (= 1.0.2.19)
> 
> - OpenSSL-Universal (1.0.2.19):
>     - OpenSSL-Universal/Static (= 1.0.2.19)
>   - OpenSSL-Universal/Static (1.0.2.19)
> ```

This solution worked for me as well (I also have Xcode 11.3.1).
Seems to be a far better solution than deleting those libraries outright.

**Comment by deep11chan** [comment]
> downgrading flipper-folly and openssl-universal in Podfile.lock worked for me
> _note im using xcode 11.3.1 and I cant upgrade it_
> 
> ```
> - Flipper-Folly (2.2.0):
>     - boost-for-react-native
>     - CocoaLibEvent (~> 1.0)
>     - Flipper-DoubleConversion
>     - Flipper-Glog
>     - OpenSSL-Universal (= 1.0.2.19)
> 
> - OpenSSL-Universal (1.0.2.19):
>     - OpenSSL-Universal/Static (= 1.0.2.19)
>   - OpenSSL-Universal/Static (1.0.2.19)
> ```

Thanks , It seems proper solution rather than removing whole flipper code...

**Comment by DaggieBlanqx** [comment]
> @DaggieBlanqx You will find AppDelegate file under `ios/yourproject/AppDelegate.m`. You can either remove the entire function or simply comment the line as shown screenshot
> ![Screen Shot 2020-11-12 at 6 36 31 PM](https://user-images.githubusercontent.com/25108385/98943832-1febfe00-2516-11eb-9222-7675c1271de4.png)

Thank you so much!!

**Comment by Krutika-chotara** [comment]
I don't use flipper still i am getting this error.
Undefined symbols for architecture x86_64:
  "___darwin_check_fd_set_overflow", referenced from:
      _RAND_poll in NodeMediaClient(rand_unix.o)
      _kmp_read in NodeMediaClient(kmp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by EhsanSarshar** [comment]
@Krutika-chotara update your `Xcode`

**Comment by Manish2612** [comment]
> downgrading flipper-folly and openssl-universal in Podfile.lock worked for me
> _note im using xcode 11.3.1 and I cant upgrade it_
> 
> ```
> - Flipper-Folly (2.2.0):
>     - boost-for-react-native
>     - CocoaLibEvent (~> 1.0)
>     - Flipper-DoubleConversion
>     - Flipper-Glog
>     - OpenSSL-Universal (= 1.0.2.19)
> 
> - OpenSSL-Universal (1.0.2.19):
>     - OpenSSL-Universal/Static (= 1.0.2.19)
>   - OpenSSL-Universal/Static (1.0.2.19)
> ```

Thanks, it worked for me. This one makes more sense rather than removing entire pod.

**Comment by rahult-sdei** [comment]
Hello guys this solution worked for me

**Comment by rahult-sdei** [comment]
Hello guys this solution worked for me
https://punjabicoder.medium.com/undefined-symbol-darwin-check-fd-set-overflow-2d75e752a850

**Comment by certilremy** [comment]
> i solved problem with
> 
> 1. comment all flipper function in podfile
> 2. remove flipperInit in appDelegate
> 3. remove openSSl in podfile.lock
> 4. pod install,
> 5. clean project
> 6. run again,

This Solution worked for me, thanks
