### ISSUE TITLE
iOS won't build in fresh typescript template project? 

### ISSUE THREAD

**Issue by anastely** [facebook/react-native#30249]
I'm creating a new project using a TypeScript template

`npx react-native init MyApp --template react-native-template-typescript`

## Description
when i want to run the app in iOS i got these errors
```
 Undefined symbols for architecture x86_64:
   "___darwin_check_fd_set_overflow", referenced from:
       _RAND_poll in libcrypto.a(rand_unix.o)
 ld: symbol(s) not found for architecture x86_64
 clang: error: linker command failed with exit code 1 (use -v to see invocation)
 
 warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 6.0, but the range of supported deployment target versions is 8.0 to 13.2.99. (in target 'OpenSSL-Universal' from project 'Pods')
 warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 5.0, but the range of supported deployment target versions is 8.0 to 13.2.99. (in target 'CocoaAsyncSocket' from project 'Pods')
 warning: no rule to process file '/Volumes/MyApp/ios/Pods/Flipper-RSocket/rsocket/benchmarks/CMakeLists.txt' of type 'text' for architecture 'x86_64' (in target 'Flipper-RSocket' from project 'Pods')
 warning: no rule to process file '/Volumes/MyApp/ios/Pods/Flipper-RSocket/rsocket/benchmarks/README.md' of type 'net.daringfireball.markdown' for architecture 'x86_64' (in target 'Flipper-RSocket' from project 'Pods')
 warning: no rule to process file '/Volumes/MyApp/ios/Pods/Flipper-RSocket/rsocket/README.md' of type 'net.daringfireball.markdown' for architecture 'x86_64' (in target 'Flipper-RSocket' from project 'Pods')
 
 ** BUILD FAILED **
 
 The following build commands failed:
         Ld /Users/Dev/Library/Developer/Xcode/DerivedData/MyApp-dgilcklgcpooacebeomueapxefkf/Build/Products/Debug-iphonesimulator/MyApp.app/MyApp normal x86_64
 (1 failure)
```
## React Native version:

```
System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i3-3110M CPU @ 2.40GHz
    Memory: 19.87 MB / 8.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 14.5.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 11.3.1/11C505 - /usr/bin/xcodebuild
  Languages:
    Java: 14.0.1 - /usr/bin/javac
    Python: 2.7.10 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
1. `npx react-native init MyApp --template react-native-template-typescript`
2. npx react-native run-ios

## Expected Results
work project well in iOS!

## Snack, code example, screenshot, or link to a repository:
https://github.com/anastely/MovieDay

**Comment by safaiyeh** [comment]
Hi @anastely could you try using the latest Xcode version?

**Comment by anastely** [comment]
> Hi @anastely could you try using the latest Xcode version?

Sadly I have Mojave right now so I can't install Xcode 12.* :/
I'm searching if I can solve this issue without doing upgrading to my system.

**Comment by gokhandoslu** [comment]
Hi @anastely, could you try this solution => https://github.com/facebook/react-native/issues/30231#issuecomment-715198875

**Comment by anastely** [comment]
@gokhandoslu yes it's work, but as @EhsanSarshar said https://github.com/facebook/react-native/issues/30231#issuecomment-715578688 i can't able to use Flipper in this case!

**Comment by anastely** [comment]
After upgrade Xcode to 11.7, the issue solved :)

**Comment by aamnah** [comment]
happening on Xcode 12.4 for me 

```
System:
    OS: macOS 11.2.3
    CPU: (8) arm64 Apple M1
    Memory: 120.25 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
    Yarn: 2.4.0 - ~/.nvm/versions/node/v14.16.0/bin/yarn
    npm: 7.6.0 - ~/.nvm/versions/node/v14.16.0/bin/npm
    Watchman: 4.9.0 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.3
      System Images: android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_282 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Got rid of the `IPHONEOS_DEPLOYMENT_TARGET` error by setting it for all pods in `Podfile`. Still getting _architecture 'arm64'_ related errors..

```
warning: no rule to process file '/ios/Pods/Flipper-RSocket/rsocket/benchmarks/README.md' of type 'net.daringfireball.markdown' for architecture 'arm64' (in target 'Flipper-RSocket' from project 'Pods')
```

**Comment by findthemax** [comment]
> happening on Xcode 12.4 for me
> 
> ```
> System:
>     OS: macOS 11.2.3
>     CPU: (8) arm64 Apple M1
>     Memory: 120.25 MB / 16.00 GB
>     Shell: 5.8 - /bin/zsh
>   Binaries:
>     Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
>     Yarn: 2.4.0 - ~/.nvm/versions/node/v14.16.0/bin/yarn
>     npm: 7.6.0 - ~/.nvm/versions/node/v14.16.0/bin/npm
>     Watchman: 4.9.0 - /opt/homebrew/bin/watchman
>   Managers:
>     CocoaPods: 1.10.1 - /usr/local/bin/pod
>   SDKs:
>     iOS SDK:
>       Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
>     Android SDK:
>       API Levels: 29, 30
>       Build Tools: 28.0.3, 29.0.2, 30.0.3
>       System Images: android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
>       Android NDK: Not Found
>   IDEs:
>     Android Studio: 4.1 AI-201.8743.12.41.7042882
>     Xcode: 12.4/12D4e - /usr/bin/xcodebuild
>   Languages:
>     Java: 1.8.0_282 - /usr/bin/javac
>     Python: 2.7.16 - /usr/bin/python
>   npmPackages:
>     @react-native-community/cli: Not Found
>     react: 16.13.1 => 16.13.1 
>     react-native: 0.63.3 => 0.63.3 
>     react-native-macos: Not Found
>   npmGlobalPackages:
>     *react-native*: Not Found
> ```
> 
> Got rid of the `IPHONEOS_DEPLOYMENT_TARGET` error by setting it for all pods in `Podfile`. Still getting _architecture 'arm64'_ related errors..
> 
> ```
> warning: no rule to process file '/ios/Pods/Flipper-RSocket/rsocket/benchmarks/README.md' of type 'net.daringfireball.markdown' for architecture 'arm64' (in target 'Flipper-RSocket' from project 'Pods')
> ```

Same situation, 

I tried to rollback Xcode but get the following

warning: no rule to process file '/ios/Pods/Flipper-RSocket/rsocket/benchmarks/CMakeLists.txt' of type 'text' for architecture 'x86_64' (in target 'Flipper-RSocket' from project 'Pods')
warning: no rule to process file '/ios/Pods/Flipper-RSocket/rsocket/benchmarks/README.md' of type 'net.daringfireball.markdown' for architecture 'x86_64' (in target 'Flipper-RSocket' from project 'Pods')
warning: no rule to process file '/ios/Pods/Flipper-RSocket/rsocket/README.md' of type 'net.daringfireball.markdown' for architecture 'x86_64' (in target 'Flipper-RSocket' from project 'Pods')

**Comment by heysailor** [comment]
Also on Xcode 12.4 with error as below:

```
warning: no rule to process file '/ios/Pods/Flipper-RSocket/rsocket/benchmarks/CMakeLists.txt' of type 'text' for architecture 'x86_64' (in target 'Flipper-RSocket' from project 'Pods')
warning: no rule to process file '/ios/Pods/Flipper-RSocket/rsocket/benchmarks/README.md' of type 'net.daringfireball.markdown' for architecture 'x86_64' (in target 'Flipper-RSocket' from project 'Pods')
warning: no rule to process file '/ios/Pods/Flipper-RSocket/rsocket/README.md' of type 'net.daringfireball.markdown' for architecture 'x86_64' (in target 'Flipper-RSocket' from project 'Pods')
```

**Comment by aamnah** [comment]
I was able to get rid of these warnings by doing a bunch of things. 

Firstly, you can remove the `.md` and `.txt` files from _Compile Sources_ and that gets rid of the _no rule to process file .._ warnings. But these are just warnings, they don't cause the build to fail. 

<img width="906" alt="Screenshot 2021-03-13 at 11 27 00 PM" src="https://user-images.githubusercontent.com/1043670/111040534-1dae9780-8455-11eb-8781-309fbed00eb3.png">

There were also a bunch of other errors that i was able to get rid of by [upgrading Flipper](https://fbflipper.com/docs/getting-started/react-native#using-the-latest-flipper-sdk). The one that comes with react native was kinda outdated (`0.54.0` when the latest was `0.79.1`. they updated the version to `0.75.1` in yesterday's release btw, latest as of this writing is `0.80.0`)

Thirdly, i had to run Xcode using Rosetta, that was the last thing that made it run for me after having fixed all the other warnings and errors

**Comment by heysailor** [comment]
Excellent... thanks for that, [upgrading Flipper](https://fbflipper.com/docs/getting-started/react-native#using-the-latest-flipper-sdk) as you said worked perfectly.

**Comment by mdehghani65** [comment]
I suddenly encountered a similar situation after updating to xcode 12.5. downgrading to Xcode 12.4 solved the problem
