### ISSUE TITLE
NSURLSessionDownloadTask: 65 — Null passed to a callee that requires a non-null argument

### ISSUE THREAD

**Issue by StefanWallin** [facebook/react-native#3024]
Initial generation is all dandy. When I came back to the app a couple of days later this happens, doing Build -> Clean and then Build again does not alleviate the issue. This somehow seems to be a continuation of issue #1955.

![react_nativ_download_task_error](https://cloud.githubusercontent.com/assets/457653/10095868/2bebd57e-636d-11e5-9aae-9f3bcae51253.png)

![react_native_download_task_bug](https://cloud.githubusercontent.com/assets/457653/10095609/45d91e76-636b-11e5-853b-a5c50404621c.png)

I use the following software

Xcode: Version 7.0 (7A220)
```
"dependencies": {
    "react-native": "^0.11.0",
    "merge": "*",
    "reflux": "*",
    "superagent": "^1.3.0"
  }
```

What can be done to alleviate this issue?

**Comment by ide** [comment]
Clear your node_modules and run npm install again. RCTDownloadTaskWrapper doesn't exist anymore.
