### ISSUE TITLE
iOS Image->gif can't stop

### ISSUE THREAD

**Issue by xiaolu8866** [facebook/react-native#30244]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
iOS Image->gif can't stop

## React Native version:
"react-native": "0.63.3"

## Steps To Reproduce
Image->source
1. set a png
2. then set a gif
3. then set a png
Image is also play gif

## Expected Results
Image change to png

## Snack, code example, screenshot, or link to a repository:
```
render() {
        let image = null;
        if (this.state.isGIf) {
            image = require('./image/gif.gif') :
        } else {
            image = require('./image/img.png');
        }
        return (
            <View>
                <Image
                    source={image}
                    resizeMode={'contain'}
                />
            </View>
        );
    }

//isGIf default is flase

this.setState({isGIf: false});
this.setState({isGIf: true});
this.setState({isGIf: false});
```

reason is
iOS-> RCTImageView.mm
```
- (void)setImage:(UIImage *)image
{
  image = image ?: _defaultImage;
  if (image != self.image) {
    [self updateWithImage:image];
  }
}
```
if (image != self.image) {        Wrong judgment

My solution
RCTUIImageViewAnimated.m

```
- (void)setImage:(UIImage *)image
{
  if (self.image == image) {
    return;
  }
......
```
change to
```
- (void)setImage:(UIImage *)image
{
  if (self.image == image) {
    return;
  } else {
      super.image = nil;
  }
......
```

Looking forward to better solutions

**Comment by ravirajn22** [comment]
Does changing to image of type png work instead of gif ? like.
```
if (this.state.isGIf) {
            image = require('./image/anotherImage.png') ; // Use png image instead of gif to debug
        } else {
            image = require('./image/img.png');
        }
```

**Comment by xiaolu8866** [comment]
> Does changing to image of type png work instead of gif ? like.
> 
> ```
> if (this.state.isGIf) {
>             image = require('./image/anotherImage.png') ; // Use png image instead of gif to debug
>         } else {
>             image = require('./image/img.png');
>         }
> ```

There is no problem with two PNG images，
But my usage scenario is not like this
