### ISSUE TITLE
In Ios, custom component renders two borders

### ISSUE THREAD

**Issue by ImPDP** [facebook/react-native#30241]
## Description
I've created a custom text input component for my react native app. It has no issues in the android build. But In IOS, the custom component draws a border around its view.

## React Native version:
   OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
    Memory: 1.07 GB / 7.86 GB
  Binaries:
    Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5977832
  Languages:
    Java: 1.8.0_231 - /c/Program Files/Java/jdk1.8.0_231/bin/javac
    Python: 3.8.0 - /c/Users/PRADEEP A/AppData/Local/Programs/Python/Python38/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.2 => 0.63.2

## How it looks
<img width="166" alt="st" src="https://user-images.githubusercontent.com/39610823/97102397-174c9880-16cb-11eb-969c-d1bb101bd559.PNG">

## Expected Results
<img width="164" alt="sto" src="https://user-images.githubusercontent.com/39610823/97102409-33503a00-16cb-11eb-92bb-9c49f69e5efc.PNG">

MyInput.js

```
import React, {useState, useRef, useEffect} from 'react';
import {
  Animated,
  Text,
  ActivityIndicator,
  TouchableOpacity,
} from 'react-native';
const {View, TextInput, StyleSheet} = require('react-native');

const MyInput = (props) => {
  const [hide, makeHide] = useState(false);
  const [phAanimatedValue] = useState(new Animated.Value(0));
  const [labelAanimatedValue] = useState(new Animated.Value(0));
  const [overflow, setOverflow] = useState('hidden');

  const movePlaceHolderLeft = phAanimatedValue.interpolate({
    inputRange: [0, 1],
    outputRange: [0, -10],
  });

  const moveLabelRight = labelAanimatedValue.interpolate({
    inputRange: [0, 1],
    outputRange: [-10, 0],
  });

  const animatePlaceHolder = (v, hide) => {
    Animated.timing(phAanimatedValue, {
      toValue: v,
      duration: 50,
      useNativeDriver: true,
    }).start(() => {
      makeHide(hide);
      animateLabel(v);
    });
  };

  const animateLabel = (v) => {
    setOverflow('visible');
    Animated.timing(labelAanimatedValue, {
      toValue: v,
      duration: 50,
      useNativeDriver: true,
    }).start();
  };

  return (
    <View
      style={[
        styles.input,
        {
          overflow: overflow,
          borderColor:props.error?"#ff0033":"#e5deda",

        },
      ]}>
      <TextInput
        onFocus={() => {
          animatePlaceHolder(1, true);
        }}
        ref={props.cref}
        value={props.value}
        onChangeText={(v) => props.onChangeText(v)}
        style={{paddingStart: 25}}
        onBlur={() => {
          if (props.value.length > 0) {
            makeHide(true);
          } else {
            animatePlaceHolder(0, false);
          }
        }}
      />
      {!hide ? (
        <Animated.Text
          onPress={() => props.cref.current.focus()}
          style={{
            position: 'absolute',
            transform: [{translateX: movePlaceHolderLeft}],
            height: '100%',
            fontFamily: 'Muli-Regular',
            width: '100%',
            marginStart: 20,
            paddingVertical:15,
            color: props.error ? '#ff0033' : '#a6a6a6',
            textAlignVertical: 'center',
          }}>
          {props.label}
        </Animated.Text>
      ) : (
        <Animated.Text
          onPress={() => props.cref.current.focus()}
          style={{
            position: 'absolute',
            transform: [{translateX: moveLabelRight}],
            marginTop: -10,
            zIndex:1000,
            backgroundColor: 'white',
            color:props.error?'red':'#e5deda',
            marginStart: 20,
            fontFamily: 'Muli-Regular',
            paddingHorizontal: 5,
            textAlignVertical: 'top',
          }}>
          {props.label}
        </Animated.Text>
      )}
    </View>
  );
};


const styles = StyleSheet.create({
  input: {
    borderWidth: 2,
    borderColor: '#e5deda',
    backgroundColor: 'white',
    fontSize: 14,
    color: '#353839',
    paddingVertical:15,
    marginHorizontal: 20,
    lineHeight: 18,
    fontFamily: 'Muli-Regular',
    fontWeight: '600',
    borderRadius: 100,
  },
});

export default MyInput;

```

Usage :

```
<MyInput
          value={value}
          onChangeText={(v)=>
          {
          setValue(v)
          setError(true)
          }}
          cref={postalRef}
          error={error}
          label="Postal Code"
        />
```

I have already asked [this question](https://stackoverflow.com/questions/64512399/custom-textinput-shows-border-around-itself-in-ios-react-native), no responses so far...

**Comment by SConaway** [comment]
How are you rendering this component? Are you sure you're not applying any styles elsewhere? If not, I'd start by removing complexity: comment out the label and other things.

**Comment by ImPDP** [comment]
I'm Rendering the component like this,
```
 <MyInput
          value={value}
          onChangeText={(v) => {
            setValue(v);
            checkPostalCodeAvailability(v);
          }}
          error={error}
          progress={progress}
          cref={postalRef}
          returnKeyType="search"
          onSubmitEditing={checkPostalCodeAvailability}
          maxLength={6}
          label="Postal Code"
        />
```

**Comment by ravirajn22** [comment]
Your code has lot of unwanted lines, post your issue using a snack with minimal code to debug.

**Comment by ImPDP** [comment]
Here is the snack Demo with minimal code AMAP... https://snack.expo.io/@pdp1124/expo-playground

**Comment by ImPDP** [comment]
Check that in android - no issues. But in iOS, the label goes behind the border and on error, a square border is created around it.

**Comment by ravirajn22** [comment]
Looks like there is some issue in dynamically changing `overflow` with border radius set. You can check that without style `overflow` it works properly. For now temporarily avoid using `overflow` and achieve that through other means. Someone debugging the exact cause and fixing it might take some time.

**Comment by ImPDP** [comment]
> Looks like there is some issue in dynamically changing `overflow` with the border-radius set. You can check that without style `overflow` it works properly. For now, temporarily avoid using `overflow` and achieve that through other means. Someone debugging the exact cause and fixing it might take some time.
> 
> EDIT 1: One workaround will be to wrap this whole `View` in another `View` and set your `overflow: overflow` to that (removing it from inner View).

Thanks for the response, Ravi. It's working without overflow. I don't know why. It is creating a duplicate border when overflow is set visible.
