### ISSUE TITLE
Xcode doesn`t build archive

### ISSUE THREAD

**Issue by ksielyov** [facebook/react-native#30242]
Go to Product->Archive, get this error:
fatal error: module map file '/Users/mbp/Library/Developer/Xcode/DerivedData/NeighboursClub-djpattgykclauafuaiyagpbcgubx/Build/Intermediates.noindex/ArchiveIntermediates/NeighboursClub/BuildProductsPath/Release-iphoneos/YogaKit/YogaKit.modulemap' not found

**Comment by ksielyov** [comment]
info Fetching system and libraries information...
System:
    OS: macOS 10.15.6
    CPU: (2) x64 Intel(R) Core(TM)2 Duo CPU     P8600  @ 2.40GHz
    Memory: 27.51 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.1 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by safaiyeh** [comment]
Hi @ksielyov please open a new issue with the issue template.
