### ISSUE TITLE
Timezone conversion is not working properly on iOS 14

### ISSUE THREAD

**Issue by enrickdl** [facebook/react-native#30245]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Hello Guys, I've noticed and I been receiving users feedbacks that all dates and other functions related to dates (like local push notifications, reminders, and others) are wrong on the latest iOS 14 on my app.

Basically, the app/system is not being able to convert the timestamp that we get from our back-end (it's on UTC0) to the user timezone. So, for example, I'm on UTC -3 and all timestamps on the app are being presented to me 3 hours later.

The odd thing about this is that is only happening with iOS 14 users. I use the same codebase and test it out on iOS 14 devices, <= iOS 13 devices, Android Devices with different android versions, and the only one that presents the issue was the devices with the newer iOS 14.

I've been searching for answers or fixes related to that for the past couple of weeks and so far I wasn't able to fix that, so at least I wanted to know if this is a React Native issue or an Apple issue or maybe both? This app is live for quite some time now and this logic as well, I really didn't want to refactor the whole timezone logic. (and even don't know if I can afford the time spent).

Any help would be awesome! 

## React Native version:
```
System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
    Memory: 22.51 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.4
    Yarn: 1.22.5
    npm: 6.14.6 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.1, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2
      System Images: android-23 | Google APIs Intel x86 Atom, android-25 | Google Play Intel x86 Atom, android-29 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 
    Xcode: 12.1- /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_265 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.0 => 0.63.0 
    react-native-macos: Not Found
```

## Steps To Reproduce
It's pretty much explained in the description, I don't believe that is a code issue, at least for now.

## Expected Results
Users should be able to get the correct timestamp on their apps on the iOS14.

**Comment by ravirajn22** [comment]
How do you set local push notification, reminders etc (If you are using some library check that libraries internal). What method do you use to convert UTC to users timezone (do you use library like moment), try to log that in iOS 13 and 14. Without showing some code its near impossible to identify the issue. I don't think any react-native API does timezone conversion.

**Comment by enrickdl** [comment]
@ravirajn22  I'm not using any kind of library to handle timezone in this case since I'm saving the date string on UTC0 and reading on UTC0. So at least for this part of the logic, I'm not converting timezones.

However, I just found out that whenever I use `new Date()`, this method returns a Date value + adding the timezone offset (in my case is 3 more hours).

i.e:

original date: 
`2020-10-26T20:14:00.000Z`

original date after use new Date():
`2020-10-26T23:14:00.000Z`

 Not even going to question why this is happening at the moment! I'm just going to compare and validate those dates for iOS14 users and hopefully found a workaround for that 😄

**Comment by safaiyeh** [comment]
Hey @enrickdl thanks for the issue! Could you create a Snack or provide a repro that demonstrates the issue?

**Comment by enrickdl** [comment]
@safaiyeh Yeah, let me give you guys an example of one of the parts of the code.

Basically what I could found is that when `new Date()` is being called, it's adding the timezone offset to the final Date value, so I have this code to schedule local push notifications:

```
export const scheduleReminderNotification = (reminder: IReminder, index: number) => {
  PushNotification.localNotificationSchedule({
    message: reminder.notes
    title: reminder.title
    date: new Date(reminder.start_date),
    number: `${index + 1}`, // offset the index
    userInfo: { ...reject(isNil, reminder), isReminder: true },
    largeIcon: 'ic_launcher_new_round',
    smallIcon: 'ic_notification',
  })
}
```

the `reminder.start_date` string value that I receive from the backend is `2020-10-27T13:19`

and the Date value that I receive after this line `date: new Date(reminder.start_date)` is `2020-10-27T16:19:00.000Z`

As you can tell, the Date value returned with 3 hours added, which is currently my timezone offset from UTC. 

This behaviour is only happening on iOS14, that same line `date: new Date(reminder.start_date)` returns the correct time in other iOS and Android versions. (i.e: in this case, it would be `2020-10-27T13:19:00.000Z`)

I've never seen that before, so I assume that somehow, the timezone is kind of off/broken on iOS 14 and this issue is happening.

**Comment by ravirajn22** [comment]
https://stackoverflow.com/a/13363791/1250311

This answer pretty clearly solves your problem and tells why iOS 14 way of handling date/time string without timezone is correct according to new es5 javascript spec matching ISO 8601.

Post here if you have any doubts.

**Comment by enrickdl** [comment]
@ravirajn22 Thank you so much for your help. I didn't know about that situation with date strings and the StackOverflow link help me out to find a solution! Basically, I'm checking the date sting and adding the "Z" to the end. Now, iOS 14 is able to show and understand the right date on my app. cheers 👍

**Comment by safaiyeh** [comment]
> https://stackoverflow.com/a/13363791/1250311
> 
> Also read this Date.parse which it uses, https://tc39.es/ecma262/#sec-date.parse
> 
> The above links pretty clearly solves your problem and tells why iOS 14 way of handling date-time string without timezone is correct according to new es5 javascript spec matching ISO 8601.
> 
> Post here if you have any doubts.

Thanks for the solution! We should update this in the docs for people who come across this. Do you mind making a PR for that?

**Comment by ravirajn22** [comment]
This is an issue of javascript not reactnative it would be maintenace headache for documenting these things. Better if it was included in MDN docs. In fact poor apple has not documented this change in javascriptcore changelog from what i know.

**Comment by safaiyeh** [comment]
Interesting, thanks for providing all the info again! I'll close this, hopefully people with the same issue land on this.

**Comment by Desintegrator** [comment]
faced same issue, fixed it with "Z", thanks
