### ISSUE TITLE
Tests are failing on master 

### ISSUE THREAD

**Issue by grabbou** [facebook/react-native#30257]
## Description

Right now, `yarn install` is failing silently https://app.circleci.com/pipelines/github/facebook/react-native/6828/workflows/93bf3792-da93-4824-9a36-40511cc86b84/jobs/173433/parallel-runs/0/steps/0-104 

As a result, it doesn't run `build` script in `react-native-codegen`. That leads to a missing `FBReactNativeSpec.h` file (that is autogenerated in that phase) and results in a failing build.

https://app.circleci.com/pipelines/github/facebook/react-native/6828/workflows/93bf3792-da93-4824-9a36-40511cc86b84/jobs/173433

**Comment by grabbou** [comment]
This fixes it partially https://github.com/facebook/react-native/commit/6f78e16c011180ba3cda72427e37b4b4b68fc193 by building `react-native-codegen` directly, which is fine, but again, we should fix the main `yarn` command.

CC: @hramos

**Comment by KingAmo** [comment]
i have an error run `yarn install` in `node_modules/react-native-codegen 
```
/node`Error: Cannot find module '/Users/qinshuai/Documents/ReactNativeProj/fandeng/lingyue/node_modules/react-native-codegen/scripts/build.js'
```

**Comment by tido64** [comment]
> i have an error run `yarn install` in `node_modules/react-native-codegen
> 
> ```
> /node`Error: Cannot find module '/Users/qinshuai/Documents/ReactNativeProj/fandeng/lingyue/node_modules/react-native-codegen/scripts/build.js'
> ```

You need to add `react-native-codegen` to your `package.json`. Please see [React Native Upgrade Helper](https://react-native-community.github.io/upgrade-helper/?from=0.63.4&to=0.64.0-rc.2) for more details.

**Comment by KingAmo** [comment]
> @KingAmo
> 
> > i have an error run `yarn install` in `node_modules/react-native-codegen
> > ```
> > /node`Error: Cannot find module '/Users/qinshuai/Documents/ReactNativeProj/fandeng/lingyue/node_modules/react-native-codegen/scripts/build.js'
> > ```
> 
> You need to add `react-native-codegen` to your `package.json`. Please see [React Native Upgrade Helper](https://react-native-community.github.io/upgrade-helper/?from=0.63.4&to=0.64.0-rc.2) for more details.

hi @tido64 ,thanks a lot, follow the [upgrade helper](https://react-native-community.github.io/upgrade-helper/?from=0.64.0-rc.1&to=0.64.0-rc.2) solved my issue
