### ISSUE TITLE
Why does Alert on Android not support the list option?

### ISSUE THREAD

**Issue by kevgrig** [facebook/react-native#30253]
## Description

Alert [documents](https://reactnative.dev/docs/alert.html):

> On Android at most three buttons can be specified.

However, the Android AlertDialog API supports [lists of selections](https://developer.android.com/guide/topics/ui/dialogs#AddingAList) (plain, radio, or checkbox).

> There are three kinds of lists available with the AlertDialog APIs:
> * A traditional single-choice list
> * A persistent single-choice list (radio buttons)
> * A persistent multiple-choice list (checkboxes)
> ![dialog_list](https://user-images.githubusercontent.com/6432587/97261153-7d284580-17db-11eb-9ae4-36e7e19a0a34.png)

It would be really nice if RN's Alert supported lists so that there would be an option for parity with RN's [ActionSheetIOS](https://reactnative.dev/docs/actionsheetios.html).

It seems like the current Android alternatives are all non-native such as [react-native-action-sheet](https://github.com/expo/react-native-action-sheet), [react-native-reanimated-bottom-sheet](https://github.com/osdnk/react-native-reanimated-bottom-sheet), [react-native-raw-bottom-sheet](https://github.com/nysamnang/react-native-raw-bottom-sheet), [react-native-bottom-sheet](https://github.com/gorhom/react-native-bottom-sheet), and [React Native Elements Bottom Sheet](https://reactnativeelements.com/docs/bottomsheet/).

Is this just a matter of someone needing to create a PR or is there a reason it's not implemented?

**Comment by kevgrig** [comment]
```
$ react-native info
info Fetching system and libraries information...
System:
    OS: Linux 5.8 Fedora 32 (Workstation Edition) 32 (Workstation Edition)
    CPU: (4) x64 Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz
    Memory: 816.45 MB / 15.51 GB
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 12.18.3 - /usr/bin/node
    Yarn: 1.21.1 - /usr/bin/yarn
    npm: 6.14.6 - /usr/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 1.8.0_265 - /usr/bin/javac
    Python: 3.8.6 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2 
  npmGlobalPackages:
    *react-native*: Not Found
$ expo diagnostics

  Expo CLI 3.28.2 environment info:
    System:
      OS: Linux 5.8 Fedora 32 (Workstation Edition) 32 (Workstation Edition)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 12.18.3 - /usr/bin/node
      Yarn: 1.21.1 - /usr/bin/yarn
      npm: 6.14.6 - /usr/bin/npm
    npmPackages:
      expo: ^39.0.0 => 39.0.3 
      react: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2 
    npmGlobalPackages:
      expo-cli: 3.27.4
    Expo Workflow: managed
```

**Comment by chrisglein** [comment]
> Is this just a matter of someone needing to create a PR or is there a reason it's not implemented?

I'm not sure if it's intentional. If it's not a PR would be the right way to proceed. At least from my perspective, looking at the API docs you've linked it seems reasonable that Alert on Android would also grow to support more options since that's what the native API supports... although there seems to be a definite pivot in the meaning from the 3 button (must be positive/neutral/negative) to the list of N items (no inferred meaning). I don't know if that would be jarring.

**Comment by DomVinyard** [comment]
This would be great

**Comment by dalton-adrift** [comment]
Check out the response here https://stackdev.space/questions/what-is-the-best-way-to-retrieve-the-selected-list-from-an-android-dialog-presented-to-users
