### ISSUE TITLE
device height calculation for android punch hole devices is coming incorrect in FlatList

### ISSUE THREAD

**Issue by kunalsolanki1992** [facebook/react-native#30256]
Following is the requested information

## Description
Using FlatList with pagingEnabled in react-native where all the elements are of full screen height and width, the calculation of device height (or snapping to offset of next element) is calculated incorrectly for punch hole devices. This happens only on android and works correctly on iOS. Please see below screenshots.
![1](https://user-images.githubusercontent.com/52502554/97296327-86b2bb80-1876-11eb-96cf-3a0753ce8456.png)
![2](https://user-images.githubusercontent.com/52502554/97296332-887c7f00-1876-11eb-9ca2-797571eb5b2a.png)
![3](https://user-images.githubusercontent.com/52502554/97296333-89adac00-1876-11eb-9d08-5624db446c8a.png)
![4](https://user-images.githubusercontent.com/52502554/97296336-8a464280-1876-11eb-8196-51dc93ff2630.png)

In screenshot 1, the item is correct in whole full screen.
In screenshot 2, approx 1 pixel of previous element's part is visible from top.
In screenshot 3, a little more portion of previous element's part is visible from top.
In screenshot 4, same thing with little more portion.

The background color has been set to red for even index element and green for odd index element. And this increase in portion of previous element's part increases with index (e.g. if on index 1 it is showing 1px, then on index 10 it might be showing 20 px, on 20th index may be 40pixel.

## React Native version:
System:
    OS: macOS 10.15.1
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Memory: 59.88 MB / 12.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.13.1 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.7 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.4 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6308749
    Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.5 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Here's the android build for same.
https://drive.google.com/file/d/1Cjwa30iESiXRCON-Q7m5zopTyZozg-T9/view?usp=sharing

## Expected Results
The part of previous element shouldn't be coming and scrolling should work as per screen size.

**Comment by mjmasn** [comment]
Hey @kunalsolanki1992 you might be seeing this rounding bug - https://github.com/facebook/react-native/issues/21441 - there's some workarounds on the issue. Does the android device have a non-integer height?

**Comment by kunalsolanki1992** [comment]
Hey @mjmasn , yes the device has non-integer height. I will check the solution mentioned in https://github.com/facebook/react-native/issues/21441#issuecomment-566987535

**Comment by kunalsolanki1992** [comment]
Thank you @mjackson .. this worked like a charm!
