### ISSUE TITLE
[ios] Non-Debug configuration always in Release mode 

### ISSUE THREAD

**Issue by tomlagier** [facebook/react-native#30251]
## Description
We have a separate `Local` and `Debug` configuration, we use `Debug` to test against a deployed database and `Local` to run against a local firebase emulator. When running with `Local` configuration (`react-native run-ios --configuration Local`), the deployed image is in `Release` mode - debug menu does not exist and the packager cannot reload the code.

I spent a while poking around the internals of React Native and `react-native-cli` and I couldn't find the bit that determines whether to add the additional debug instrumentation or not. I'm happy to explore a PR if someone can point me towards that code.

## React Native version:
```
System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 101.49 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.22.1 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.6 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /Users/tomlagier/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.1, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 12.1/12A7403 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: ~16.9.0 => 16.9.0 
    react-native: ~0.61.5 => 0.61.5 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Create a new `react-native` project.
2. Open XCode, duplicate `Debug` configuration to `Local`.
3. Run ios simulator with `Local` configuration: `react-native run-ios --configuration Local`
4. Observe that fast refresh and developer menu are not active.

## Expected Results
Fast refresh and developer menu should be available, or there should be a flag to enable them on non-Debug configurations.

## Snack, code example, screenshot, or link to a repository:
Repository: https://github.com/tomlagier/react-ios-configuration-fast-refresh-bug

1. Clone, `yarn`, run `react-native run-ios --configuration Local`.
2. Press `r` in the spawned packager terminal.

Bundler outputs:
```
warn No apps connected. Sending "reload" to all React Native apps failed. Make sure your app is running in the simulator or on a phone connected via USB.
```

**Comment by ravirajn22** [comment]
react-native-cli deals with these, make an issue in their repo. They will handle it better. Also search in their issues page. Looks like this problem should have already been faced by community and solved.
https://github.com/react-native-community/cli
