### ISSUE TITLE
Turbo Module SoundManager test

### ISSUE THREAD

**Issue by gengjiawen** [facebook/react-native#30261]
I want to try this feature (Mainly want to debug turbo module tbh), but neither do I find documentation nor import it works.

@mdvacca @fkgozali

**Comment by fkgozali** [comment]
What didn't work for you? Did you mean RNTester Android/iOS example isn't working?

**Comment by gengjiawen** [comment]
> What didn't work for you? Did you mean RNTester Android/iOS example isn't working?

Yeap. RNTester import {  SoundManager } from 'react-native' is undefined.

**Comment by fkgozali** [comment]
That's because SoundManager was never exposed to https://github.com/facebook/react-native/blob/master/index.js - try something like:

```
import SoundManager from 'react-native/Libraries/Components/Sound/SoundManager';
```

or import NativeSoundManager directly:

```
import NativeSoundManager from 'react-native/Libraries/Components/Sound/NativeSoundManager';
```

**Comment by gengjiawen** [comment]
This worked. Thanks. I used `import SoundManager from 'react-native/Libraries/Components/Sound/SoundManager';
` yesterday, but not worked, I must forget to reload or something.
