### ISSUE TITLE
can not fetch on android 10

### ISSUE THREAD

**Issue by 2821998** [facebook/react-native#30269]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Please provide a clear and concise description of what the bug is. Include screenshots if needed.
Please test using the latest React Native release to make sure your issue has not already been fixed: https://reactnative.dev/docs/upgrading.html

## React Native version:
Run `react-native info` in your terminal and copy the results here.

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.
2.

## Expected Results
Describe what you expected to happen.

## Snack, code example, screenshot, or link to a repository:
Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by vidaljose** [comment]
I had the same problem, make sure you are connected to the same network hahaha

anyway i show you my code

`let postData = async() =>{
          try{
            await fetch('http://192.168.0.245/api_cell',{
              method:'POST',
              headers:{
                "Content-Type": "multipart/form-data",
                "Accept": "application/json"
              },
              body: JSON.stringify([{
                datos: 380,
                
              }])
            })
          }catch(e){
            console.log(e);
          }
        } 
        postData();`

my code (AndroidManifest.xml) looks like this

`<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools">

    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>

    <application android:usesCleartextTraffic="true" tools:targetApi="28" tools:ignore="GoogleAppIndexingWarning" xmlns:tools="http://schemas.android.com/tools"/>
</manifest>`


good luck
