### ISSUE TITLE
[packager] Configuration file for bundle command

### ISSUE THREAD

**Issue by matth3wga0** [facebook/react-native#3026]
Hello,

Any idea about loading the default configuration js/json file while running `react-native bundle`, maybe even wrap the config into `package.json` like [.babelrc](https://babeljs.io/docs/usage/babelrc/) does.

```json
{
    "dev": false,
    "minify": true,
    "url": {
        "ios": "/index.ios.bundle",
        "android": "/index.android.bundle"
    },
    "output": {
        "ios": "ios/main.jsbundle",
        "android": "android/app/src/main/assets/index.android.bundle"
    }
}
```

**Comment by bluedaniel** [comment]
I think this is a great idea

**Comment by stereodenis** [comment]
:+1:

**Comment by jsierles** [comment]
@matth3wga0 This looks like a great idea - could you submit a PR or post on [Product Pains](https://productpains.com/product/react-native)? Given the massive growth of React Native, we're trying to keep issues focused on bugs. Thanks!
