### ISSUE TITLE
FrescoModule doesn't check if there's already a Fresco initialised outside of the library

### ISSUE THREAD

**Issue by helenaford** [facebook/react-native#30276]
## Description
The [FrescoModule](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/modules/fresco/FrescoModule.java)  doesn't check if another Fresco has already been initialised natively by the app, and this causes a log message 
`Fresco: Fresco has already been initialized! `Fresco.initialize(...)` should only be called 1 single time to avoid memory leaks!`
which has a knock on effect producing another log message: `Fresco: Finalized without closing: (type = com.facebook.imagepipeline.image.CloseableStaticBitmap).`

## React Native version:
```
System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 2.19 GB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.16.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 19, 23, 24, 25, 26, 27, 28, 29
      Build Tools: 24.0.1, 24.0.3, 26.0.3, 27.0.3, 28.0.3, 29.0.2, 29.0.3, 30.0.0
      System Images: android-19 | Google APIs ARM EABI v7a, android-19 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-R | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
```

## Steps To Reproduce
1. Native Android code initialises Fresco
```js
if (!Fresco.hasBeenInitialized()) {
          Fresco.initialize(ContextHolder.getApplicationContext());
}
```
2. React Native FrescoModule continues to initialize Fresco, despite one already there
```js
  @Override
  public void initialize() {
     // ...

    if (!hasBeenInitialized()) {
     // ...
      Fresco.initialize(context, mConfig);
      sHasBeenInitialized = true;
     // ...
  }
```
## Expected Results
React Native to not to initialise the fresco module if there's already one there. Or, provide a way to use the FrescoModule outside of React Native if possible.  

Maybe the logs are harmless, but would love to get some input on this.

**Comment by helenaford** [comment]
Added react-native info

**Comment by helenaford** [comment]
Hi, this issue has nothing to do with the version. It's what's on the master branch regarding the fresco.

**Comment by chrisglein** [comment]
Is there any behavior you're experiencing as a result of this or are you trying to get rid of the log message?

**Comment by dulmandakh** [comment]
It seems that you are writing native code, and having issue. You can use **Fresco.getImagePipeline()** to get Fresco ImagePipeline and use it.
