### ISSUE TITLE
<Text /> nodes clip last line on Android

### ISSUE THREAD

**Issue by alegadpen-iu** [facebook/react-native#30272]
## Description
<Text /> nodes are getting their last line clipped in RN 0.63.3 
This issue, as far as I researched, has something to do with how Android interprets lineHeight and where there component ends, if I increase lineHeight the last line is not clipped if I decrease it, it starts showing some clipping on the last line. 

## React Native version:
```
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 47.84 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.1.0 - /usr/local/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.12.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.4 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.1, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 28
      Build Tools: 28.0.3
      System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5977832
    Xcode: 12.1/12A7403 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_252 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.14.0 => 16.14.0 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Upgrade from RN 0.62 to RN 0.63.3
2. Run on android emulator
2. On a <Text /> with multiple lines, modify lineHeight to visually check this issue 

## Expected Results
<Text /> shouldn't clip last line no matter what lineHeight value it has. 

## Snack, code example, screenshot, or link to a repository:
![image](https://user-images.githubusercontent.com/45769612/97585126-8e3da600-19d7-11eb-845d-2800f70d5035.png)

**Comment by fervailanti** [comment]
Same issue here in RN 0.63.3.

**Comment by fabriziobertoglio1987** [comment]
Do you still experience this issue? 

I have four years of experience maintaining facebook/react-native and I specialize in the Text and TextInput components. I currently have 58 [facebook/react-native PRs](https://github.com/facebook/react-native/pulls?q=is%3Apr+author%3Afabriziobertoglio1987+). 

If you still experience this issue, I will prepare a patched release with the fix.

Thanks a lot
