### ISSUE TITLE
【Crash】:facebook::jsc::JSCRuntime::createValue(OpaqueJSValue const*) const (JSCRuntime.cpp:0)

### ISSUE THREAD

**Issue by zdmjerry** [facebook/react-native#30281]
There have been a lot of crashes in my app recently

## Description
There have been a lot of crashes in my app recently as follows
`facebook::jsc::JSCRuntime::createValue(OpaqueJSValue const*) const (JSCRuntime.cpp:0)`

Crash Log:

>  libsystem_kernel.dylib          __pthread_kill + 8

1   libsystem_pthread.dylib         pthread_kill$VARIANT$mp + 380
2   libsystem_c.dylib               abort + 140
3  test                       facebook::jsc::JSCRuntime::createValue(OpaqueJSValue const*) const (JSCRuntime.cpp:0)
4   test                       facebook::jsc::JSCRuntime::getProperty(facebook::jsi::Object const&, facebook::jsi::String const&) (JSCRuntime.cpp:809)
5   test                       facebook::jsi::dynamicFromValue(facebook::jsi::Runtime&, facebook::jsi::Value const&) (jsi.h:990)
6   test                       facebook::jsi::dynamicFromValue(facebook::jsi::Runtime&, facebook::jsi::Value const&) (dynamic-inl.h:1018)
7   test                       facebook::jsi::dynamicFromValue(facebook::jsi::Runtime&, facebook::jsi::Value const&) (dynamic-inl.h:1018)
8   test                       facebook::jsi::dynamicFromValue(facebook::jsi::Runtime&, facebook::jsi::Value const&) (dynamic-inl.h:1018)
9   test                       facebook::jsi::dynamicFromValue(facebook::jsi::Runtime&, facebook::jsi::Value const&) (dynamic-inl.h:1018)
10  test                       facebook::jsi::dynamicFromValue(facebook::jsi::Runtime&, facebook::jsi::Value const&) (dynamic-inl.h:1018)
11  test                       facebook::jsi::dynamicFromValue(facebook::jsi::Runtime&, facebook::jsi::Value const&) (dynamic-inl.h:1018)
12  test                       facebook::jsi::dynamicFromValue(facebook::jsi::Runtime&, facebook::jsi::Value const&) (dynamic-inl.h:1018)
13  test                       facebook::jsi::dynamicFromValue(facebook::jsi::Runtime&, facebook::jsi::Value const&) (dynamic-inl.h:1018)
14  test                       facebook::jsi::dynamicFromValue(facebook::jsi::Runtime&, facebook::jsi::Value const&) (dynamic-inl.h:1018)
15  test                       facebook::jsi::dynamicFromValue(facebook::jsi::Runtime&, facebook::jsi::Value const&) (dynamic-inl.h:1018)
16  test                       facebook::react::JSIExecutor::callNativeModules(facebook::jsi::Value const&, bool) (JSIExecutor.cpp:288)
17  test                       std::__1::__function::__func<facebook::react::JSIExecutor::loadApplicationScript(std::__1::unique_ptr<facebook::react::JSBigString const, std::__1::default_delete<facebook::react::JSBigString const> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)::$_1, std::__1::allocator<facebook::react::JSIExecutor::loadApplicationScript(std::__1::unique_ptr<facebook::react::JSBigString const, std::__1::default_delete<facebook::react::JSBigString const> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)::$_1>, facebook::jsi::Value (facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long)>::operator()(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*&&, unsigned long&&) (jsi.h:1126)
18  test                       std::__1::function<facebook::jsi::Value (facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long)>::operator()(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long) const (functional:1913)
19  test                       facebook::jsc::JSCRuntime::createFunctionFromHostFunction(facebook::jsi::PropNameID const&, unsigned int, std::__1::function<facebook::jsi::Value (facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long)>)::HostFunctionMetadata::call(OpaqueJSContext const*, OpaqueJSValue*, OpaqueJSValue*, unsigned long, OpaqueJSValue const* const*, OpaqueJSValue const**) (JSCRuntime.cpp:1101)
20  JavaScriptCore                  JSC::JSCallbackObject<JSC::JSDestructibleObject>::call(JSC::ExecState*) + 352
21  JavaScriptCore                  JSC::LLInt::setUpCall(JSC::ExecState*, JSC::CodeSpecializationKind, JSC::JSValue, JSC::LLIntCallLinkInfo*) + 428

**Comment by Maxoos** [comment]
We are seeing the same issue

**Comment by TYRONEMICHAEL** [comment]
We are also experiencing this issue. We are not on the latest version of RN. Our current version is 0.61.2.

**Comment by luco** [comment]
Not sure if my issue #30462 is related. Seems to.

**Comment by xwartz** [comment]
this issue still exists. are there any solutions?
