### ISSUE TITLE
ios app crash on launch 

### ISSUE THREAD

**Issue by avbeladiya** [facebook/react-native#30287]
hello
my app was working fine before xcode update,after updating it to 12.0.1, application is crashing after launch on every device below ios 14, it only works on ios 14.

package.json

> "@invertase/react-native-apple-authentication": "^2.0.2",
    "@react-native-community/async-storage": "^1.7.0",
    "@react-native-community/google-signin": "^3.0.4",
    "@react-native-community/netinfo": "^5.0.0",
    "@react-native-community/toolbar-android": "0.1.0-rc.2",
    "@react-native-community/viewpager": "^3.2.0",
    "@react-native-firebase/app": "^8.4.6",
    "@react-native-firebase/auth": "^9.3.1",
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-branch": "^5.0.0",
    "react-native-fbsdk": "^1.1.1",
    "react-native-gesture-handler": "^1.5.2",
    "react-native-keyboard-aware-scroll-view": "^0.9.1",
    "react-native-offline-api": "^2.3.0",
    "react-native-onesignal": "^3.6.0",
    "react-native-paper": "^3.4.0",
    "react-native-reanimated": "^1.4.0",
    "react-native-screens": "^2.0.0-alpha.20",
    "react-native-share": "^2.0.0",
    "react-native-snap-carousel": "^3.8.4",
    "react-native-splash-screen": "^3.2.0",
    "react-native-svg": "^10.0.0",
    "react-native-translucent-modal": "^1.1.0",
    "react-native-vector-icons": "^6.6.0",
    "react-native-webview": "^7.6.0",
    "react-navigation": "^4.0.10",
    "react-navigation-drawer": "^2.3.3",
    "react-navigation-redux-helpers": "^4.0.1",
    "react-redux": "^7.1.3",
    "redux": "^4.0.5",
    "redux-logger": "^3.0.6",
    "redux-saga": "^1.1.3",

react-native info

> info Fetching system and libraries information...
(node:71363) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
System:
    OS: macOS 10.15.7
    CPU: (6) x64 Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
    Memory: 353.49 MB / 24.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.2.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6858069
    Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-rename: 2.4.1

log : [crash log](https://prnt.sc/va940l)

i tried removing firebase lib and pod(thinking that could be issue), but didnt worked , not sure if its library issue or xcode config

**Comment by yum650350** [comment]
Have you tried cleaning the project?

ref: [Xcode Quick Fix - Clear Cache](https://developerinsider.co/clean-xcode-cache-quick-fix/)

**Comment by avbeladiya** [comment]
@yum650350 clearing cache didnt help

error logs shows "Image not found"
is there any way i can find the file or cause and manually fix it?

**Comment by avbeladiya** [comment]
after xcode update, to solve [this issue](https://developer.apple.com/forums/thread/655438) , i'd added libSwiftWebKit.tbd., this fixed the issue on ios 14 , but it was giving error on ios 13 or every device below 14 "Image not found". 

solution : 
lib status should be optional (which works in all devices)

**Comment by SamiChab** [comment]
@avbeladiya what do you mean when saying `lib status should be optional (which works in all devices)` ?

**Comment by markymc** [comment]
@SamiChab I think he means this

<img width="676" alt="Screen Shot 2021-10-12 at 13 07 43" src="https://user-images.githubusercontent.com/346952/136889819-1c3d1e8f-0eda-4d73-a83e-a7b1cdef386b.png">
