### ISSUE TITLE
Android. The size of SO binary libraries are doubled by bumping min SDK to 23

### ISSUE THREAD

**Issue by Gark** [facebook/react-native#30284]
## Description
By bumping a version of minSDK from 21 to 23. The size of the APK is doubled. Inspector says that all binaries became heavier. Is there any idea why it could happen?

## React Native version:
"react-native": "0.63.2"
hermes is ON

## Steps To Reproduce
assembleRelease command with min SDK 21 and 23 generates APKs with unexpectable results of file size. 
49.6Mb and 88.9MB

## Expected Results
The size should be quite the same.

## Snack, code example, screenshot, or link to a repository:
![so_problem](https://user-images.githubusercontent.com/1929368/97690248-03bf7a00-1a9d-11eb-8cc9-e9f833d3b847.png)

Thanks.

**Comment by cortinico** [comment]
This is the expected behavior. The explanation of why this is happening can be found here https://stackoverflow.com/a/63417612
