### ISSUE TITLE
StatusBar translucent = true, Sometimes invalid when opening app

### ISSUE THREAD

**Issue by caijiami** [facebook/react-native#30282]
StatusBar translucent = true, Sometimes invalid when opening app

info Fetching system and libraries information...
System:
    OS: Windows Server 2016 10.0.14393
    CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
    Memory: 7.74 GB / 15.93 GB
  Binaries:
    Node: 12.18.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 21, 22, 23, 24, 25, 26, 27, 28, 29
      Build Tools: 20.0.0, 21.1.2, 23.0.1, 23.0.2, 23.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3,
26.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.1, 27.0.2, 27.0.3, 28.0.0, 28.0.1, 28.0.2, 28.
0.3, 29.0.0, 29.0.1, 29.0.2, 29.0.3
      System Images: android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Inte
l x86 Atom, android-28 | Android TV Intel x86 Atom, android-28 | China version of Wear OS I
ntel x86 Atom, android-28 | Wear OS Intel x86 Atom, android-28 | Intel x86 Atom, android-28
 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Int
el x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86
 Atom_64, android-29 | Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google
APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play I
ntel x86 Atom, android-29 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6514223
  Languages:
    Java: 1.8.0_201
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.0 => 0.62.0
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by caijiami** [comment]
@mojodna @jsierles @imownbey @augustl We've been having this problem with Android bangs

**Comment by caijiami** [comment]
> ⚠️	缺少环境信息
> ℹ️	您的问题可能缺少有关您的开发环境的信息。您可以通过`react-native info`在控制台中运行来获取缺少的信息。

OS: Windows Server 2016 10.0.14393
CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
Memory: 7.74 GB / 15.93 GB
Binaries:
Node: 12.18.2 - C:\Program Files\nodejs\node.EXE
Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
Watchman: Not Found
SDKs:
Android SDK:
API Levels: 21, 22, 23, 24, 25, 26, 27, 28, 29
Build Tools: 20.0.0, 21.1.2, 23.0.1, 23.0.2, 23.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3,
26.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.1, 27.0.2, 27.0.3, 28.0.0, 28.0.1, 28.0.2, 28.
0.3, 29.0.0, 29.0.1, 29.0.2, 29.0.3
System Images: android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Inte
l x86 Atom, android-28 | Android TV Intel x86 Atom, android-28 | China version of Wear OS I
ntel x86 Atom, android-28 | Wear OS Intel x86 Atom, android-28 | Intel x86 Atom, android-28
| Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Int
el x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86
Atom_64, android-29 | Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google
APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play I
ntel x86 Atom, android-29 | Google Play Intel x86 Atom_64
Android NDK: Not Found
IDEs:
Android Studio: Version 4.0.0.0 AI-193.6911.18.40.6514223
Languages:
Java: 1.8.0_201
Python: Not Found
npmPackages:
@react-native-community/cli: Not Found
react: 16.11.0 => 16.11.0
react-native: 0.62.0 => 0.62.0
npmGlobalPackages:
react-native: Not Found

**Comment by yz1311** [comment]
call `StatusBar.setTranslucent(true);` when appState is active

**Comment by caijiami** [comment]
this._navListener = this.props.navigation.addListener('didFocus', () => {
      StatusBar.setTranslucent(true)
      StatusBar.setBarStyle('dark-content')
      StatusBar.setBackgroundColor('transparent')
    })

The above code is added to each page, but after exiting the APP, the navigation bar is displayed when you re-enter

**Comment by caijiami** [comment]
> `StatusBar.setTranslucent(true);`当appState处于活动状态时调用

I set it but it didn't work. Thank you

**Comment by yz1311** [comment]
```
componentDidMount() {
    Platform.OS === 'android' && AppState.addEventListener('change', this._onStateChange);
}

componentWillUnmount() {
   Platform.OS === 'android' && AppState.removeEventListener('change', this._onStateChange);
}

 _onStateChange = () => {
    //在android下有个bug，app呆在后台一段时候后，返回到前台，状态栏会变成半透明
    //并且将内容向下顶下去，该处就是修复该问题
    StatusBar.setTranslucent(true);
  };

```

**Comment by caijiami** [comment]
> ```
> componentDidMount() {
>     Platform.OS === 'android' && AppState.addEventListener('change', this._onStateChange);
> }
> 
> componentWillUnmount() {
>    Platform.OS === 'android' && AppState.removeEventListener('change', this._onStateChange);
> }
> 
>  _onStateChange = () => {
>     //在android下有个bug，app呆在后台一段时候后，返回到前台，状态栏会变成半透明
>     //并且将内容向下顶下去，该处就是修复该问题
>     StatusBar.setTranslucent(true);
>   };
> ```
I've set this up on every page but it works for the first download, it doesn't work when you exit the APP and re-enter it

**Comment by yz1311** [comment]
You do not need to  set it in every page, just in the root page,such as app.js.

**Comment by caijiami** [comment]
> 您无需在每个页面（仅在根页面）中进行设置，例如app.js。



> 您无需在每个页面（仅在根页面）中进行设置，例如app.js。

I also imported this method on the root page, but it still doesn't work

**Comment by caijiami** [comment]
<application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:theme="@style/AppTheme"
      android:usesCleartextTraffic="true"
      android:requestLegacyExternalStorage="true"
      android:banner="@drawable/tv_banner"
      tools:replace="android:allowBackup"
    >
      <activity
        android:name=".MainActivity"
        android:resizeableActivity="true"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode"
        android:launchMode="singleTask"
        android:theme="@style/Theme.ReactNative.AppCompat.Light.NoActionBar.FullScreen"
        android:windowSoftInputMode="adjustPan">

This is my permission file

**Comment by caijiami** [comment]
This is my permission file

 <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:theme="@style/AppTheme"
      android:usesCleartextTraffic="true"
      android:requestLegacyExternalStorage="true"
      android:banner="@drawable/tv_banner"
      tools:replace="android:allowBackup"
    >
      <activity
        android:name=".MainActivity"
        android:resizeableActivity="true"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode"
        android:launchMode="singleTask"
        android:theme="@style/Theme.ReactNative.AppCompat.Light.NoActionBar.FullScreen"
        android:windowSoftInputMode="adjustPan">

**Comment by caijiami** [comment]
这是我的权限文件
![Uploading image.png…]()

**Comment by caijiami** [comment]
> You do not need to set it in every page, just in the root page,such as app.js.

Only reload will take effect

**Comment by yz1311** [comment]
A walkaround is to kill app when press back button.

**Comment by caijiami** [comment]
> 一种解决方法是按后退按钮杀死应用程序。

Killing processes does work, but is there a better way to do it

**Comment by caijiami** [comment]
> A walkaround is to kill app when press back button.

How to kill APP process, thank you

**Comment by yz1311** [comment]
> > A walkaround is to kill app when press back button.
> 
> How to kill APP process, thank you

https://github.com/wumke/react-native-exit-app
