### ISSUE TITLE
TextInput's selectionColor doesn't style Android's selection handles 

### ISSUE THREAD

**Issue by adamsoutar** [facebook/react-native#30283]
## Description

Using `selectionColor` on iOS styles the selection, as well as the 'handles' on either side of it:

![iOS Selection](https://user-images.githubusercontent.com/26578100/97688241-c5708d80-1a91-11eb-9002-3fbcd23fc498.png)

However, on Android these handles are _green_, which also happens to be the default `selectionColor` if you don't override it. I feel that these should go along with what iOS does (turn pink in this example).

![Android Selection](https://user-images.githubusercontent.com/26578100/97688336-e802a680-1a91-11eb-8037-1f2c5379e64f.png)

Another example (where it should also be pink):

![Second Android example](https://user-images.githubusercontent.com/26578100/97689067-f2717000-1a92-11eb-885d-5c98392f74a2.png)

## React Native version:
```
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 21.14 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.11.0 - ~/.nvm/versions/node/v14.11.0/bin/node
    Yarn: Not Found
    npm: 6.14.8 - ~/.nvm/versions/node/v14.11.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.1, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.1/12A7403 - /usr/bin/xcodebuild
  Languages:
    Java: javac 15 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.3 => 0.63.3
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Create a TextInput and set its `selectionColor` prop to something
2. Run in the iOS or Android simulators, make a selection, and check the handle colours

## Expected Results

The selection drag handles should be coloured by `selectionColor` on Android.

## Snack, code example, screenshot, or link to a repository:

[Snack](https://snack.expo.io/8JwZq6wrg)

**Comment by finghtingjie** [comment]
i have the same problem with you. and i tried to config some android xml files and turn out  not work at all.

**Comment by yibingxiong** [comment]
I also meet this problem. Do you know the solutions now? @adamsoutar

**Comment by charles-goode** [comment]
I'm pretty sure this problem has been around for a year at least. Ideally the prop should work cross-platform. Worst-case the docs should be updated to reflect that this is an iOS-only prop...

**Comment by fabriziobertoglio1987** [comment]
Related https://github.com/facebook/react-native/issues/22762#issuecomment-646055030, I summarize https://github.com/facebook/react-native/issues/22762#issuecomment-772634690 limitations given by the Android Sdk API 28 (Pie) do not allow us to change the cursor color

you can change the cursor color on the other APIs with [`selectionColor`](https://reactnative.dev/docs/next/textinput#selectioncolor) prop. Thanks :peace_symbol: :pray:
