### ISSUE TITLE
[Text] Text component does not highlight

### ISSUE THREAD

**Issue by ide** [facebook/react-native#303]
Text components with onPress handlers don't highlight. The RCTIsHighlightedAttributeName attribute is set on the attributed string but it is unused afterwards.

See the "Touchable* and onPress" demo in the UIExplorer for a test case.

**Comment by sahrens** [comment]
Yup, I think this only work in our internal text component - hopefully we can get this working soon in OSS.

**Comment by facebook-github-bot-3** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by ide** [comment]
This has been fixed in master.
