### ISSUE TITLE
No GLSurfaceView support for Android

### ISSUE THREAD

**Issue by aylarov** [facebook/react-native#3030]
Hi, there is no support for GLSurfaceView component in the current version, it's important for rendering video (for example).

**Comment by astreet** [comment]
We accept pull requests :)

**Comment by aylarov** [comment]
Ok, let us check what we can make with it

**Comment by christopherdro** [comment]
Hey there! Closing this issue since it's a feature request and not a bug.
We are trying to keep GitHub issues strictly for bugs. 

Here is a great library you can try for videos.
https://github.com/brentvatne/react-native-video

Hope this helps.
