### ISSUE TITLE
Hermes throws Error instead of SyntaxError 

### ISSUE THREAD

**Issue by grabbou** [facebook/react-native#30304]
## Bug Description

When working on React Native, one of the test cases started to fail. It checks whether an underlying JS engine throws a `SyntaxError` when there is an actual syntax issue.

The error is:

> Error: Exception in HostFunction: Compiling JS failed: 1:2:'}' expected at end of block

Instead of a `SyntaxError`.

The code is:

```js
global.globalEvalWithSourceUrl('{');
```

Note from @Huxpro:

> It's kinda related to a known problem that is complex and not going to be resolved anytime soon. It's complex since it's not so much of Hermes but the way we are building and linking our apps. I think we can leave the code this way for now and file an issue against the Hermes repo so we can track it down later.

^ The discussion and test case are here: https://github.com/facebook/react-native/pull/29914#discussion_r514925674

---

Hermes version: 0.7.2
React Native version (if any): Not released yet, currently master. 
Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64): iPhone Simulator

**Comment by neildhar** [comment]
This should be fixed in new versions of RN.
