### ISSUE TITLE
Keep the Integer type in ReadableMap conversion to Bundle

### ISSUE THREAD

**Issue by octavianvoloaca-tremend** [facebook/react-native#30309]
https://github.com/facebook/react-native/blob/21349d63f9ba40c4928b62f01a69b4668a7968c5/ReactAndroid/src/main/java/com/facebook/react/bridge/Arguments.java#L395

- we need to keep the type of numbers, if it's integer it's should call putInt() method, there are native methods that requires data as integer

**Comment by dulmandakh** [comment]
JS has only number type, and it's best represented by Double in Java. If you want to consume ReadableMap you can cast it in your code.
