### ISSUE TITLE
DrawerLayoutAndroid:- undefined is not an object (evaluating DrawerLayoutAndroid.positions )

### ISSUE THREAD

**Issue by kishanj918** [facebook/react-native#3031]
I am using DrawerLayoutAndroid's example code.. Some how it's giving me above mentioned error...
```
var React = require('react-native');
var {
        AppRegistry,
        Text,
        DrawerLayoutAndroid,
        }= React

var AwesomeProject = React.createClass({
    render: function () {
        var navigationView = (
            <Text style = {{margin: 10, fontSize: 15, textAlign: 'left'}}>I'm in the Drawer!</Text> );
        return (<DrawerLayoutAndroid drawerWidth = {300} drawerPosition = {DrawerLayoutAndroid.positions.Left}
                                     renderNavigationView = {() => navigationView}> <Text
            style = {{margin: 10, fontSize: 15, textAlign: 'right'}}>Hello</Text> <Text
            style = {{margin: 10, fontSize: 15, textAlign: 'right'}}>World!</Text> </DrawerLayoutAndroid> );
    },
});
AppRegistry.registerComponent('AwesomeProject', () => AwesomeProject);
```

**Comment by NishanthShankar** [comment]
Try using
`DrawerLayoutAndroid = require('DrawerLayoutAndroid');`
Most Android modules have to be imported this way. I'm not sure why

**Comment by kishanj918** [comment]
@NishanthShankar Thanks. That worked!

**Comment by brentvatne** [comment]
You shouldn't use `var DrawerLayoutAndroid = require('DrawerLayoutAndroid');` because that is an un

**Comment by brentvatne** [comment]
Confirmed that this is not happening: https://rnplay.org/apps/XDP9Tg 

Please make sure you're using `DrawerLayoutAndroid` correctly :)

**Comment by NishanthShankar** [comment]
Oh.. But the examples use it as var AndoridComponent = require(AndoridComponent)

https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/ToolbarAndroidExample.android.js

https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/ProgressBarAndroidExample.android.js

**Comment by chourobin** [comment]
Encountering the same issues. Only `var DrawerLayoutAndroid = require('DrawerLayoutAndroid');` works.

**Comment by brentvatne** [comment]
@NishanthShankar - those are inside of the repo itself, that's a little bit confusing indeed.. Notice that throughout all of the codebase `require('X')` rather than `require('../SomeDirectory/X')` are used - this is because of how Facebook uses `@providesModule` internally.

@chourobin - if you copy the exact code from the above rnplay link I provided and run that locally, do you also get errors?

**Comment by chourobin** [comment]
@brentvatne thanks for clarifying.

I got it solved! My problem was that the packager was bombing out -- my project folder path had spaces in it. I was manually starting the server in my project directory using `npm start`.

Fixing the folder name got the package launcher working properly and everything else worked.

Thanks!

**Comment by chourobin** [comment]
@brentvatne sorry I spoke too soon, I do run into issues with the copy pasted code in a fresh project.

**Comment by brentvatne** [comment]
@chourobin - with the exact code from the example? That's weird! Can you upload a repo with it and include the node_modules directory too? Thanks!

**Comment by chourobin** [comment]
@brentvatne - Hey Brent, sure here it is: https://github.com/chourobin/AndroidDrawer. Fresh project, copy pasted code & renamed SampleApp -> AndroidDrawer. Unfortunately it only works when I explicitly include 'DrawerLayoutAndroid'.

**Comment by Tjorriemorrie** [comment]
Also having this issue from AwesomeProject, only works if drawer is required.

**Comment by Tjorriemorrie** [comment]
I can't duplicate it on that [playground](https://rnplay.org/apps/yb98aw) but I'm not sure if I'm seeing it either. Maybe this is a version issue. Used default nexus5 device config.
```
CPU/ABI: Intel Atom (x86)
Target: Android 6.0 (API level 23)
```
<img width="647" alt="screen shot 2015-09-27 at 20 44 34" src="https://cloud.githubusercontent.com/assets/1099093/10124593/b7ef9fd2-6558-11e5-9f7b-7f719114a9bc.png">

@brentvatne What information do you need?

**Comment by satya164** [comment]
What's your `react-native` version? I'm also getting such errors with `0.11.2` when I try to use any Android native components like `BackAndroid`, `TouchableNativeFeedback` etc. Downgrading to `0.11.2` seems to resolve the issue.

I checked `https://github.com/facebook/react-native/blob/master/Libraries/react-native/react-native.js` in `0.11.2` and the Android modules were absent.

I did a diff between the current master version of the file and the `0.11.2` version, and this is the output.

```diff
--- react-native.js.a	2015-09-28 04:44:07.000000000 +0530
+++ react-native.js.b	2015-09-25 00:13:56.000000000 +0530
@@ -21,7 +21,6 @@
   // Components
   ActivityIndicatorIOS: require('ActivityIndicatorIOS'),
   DatePickerIOS: require('DatePickerIOS'),
-  DrawerLayoutAndroid: require('DrawerLayoutAndroid'),
   Image: require('Image'),
   ListView: require('ListView'),
   MapView: require('MapView'),
@@ -29,20 +28,15 @@
   Navigator: require('Navigator'),
   NavigatorIOS: require('NavigatorIOS'),
   PickerIOS: require('PickerIOS'),
-  ProgressBarAndroid: require('ProgressBarAndroid'),
   ProgressViewIOS: require('ProgressViewIOS'),
   ScrollView: require('ScrollView'),
   SegmentedControlIOS: require('SegmentedControlIOS'),
   SliderIOS: require('SliderIOS'),
-  SwitchAndroid: require('SwitchAndroid'),
   SwitchIOS: require('SwitchIOS'),
   TabBarIOS: require('TabBarIOS'),
   Text: require('Text'),
   TextInput: require('TextInput'),
-  ToastAndroid: require('ToastAndroid'),
-  ToolbarAndroid: require('ToolbarAndroid'),
   TouchableHighlight: require('TouchableHighlight'),
-  TouchableNativeFeedback: require('TouchableNativeFeedback'),
   TouchableOpacity: require('TouchableOpacity'),
   TouchableWithoutFeedback: require('TouchableWithoutFeedback'),
   View: require('View'),
@@ -56,7 +50,6 @@
   AppRegistry: require('AppRegistry'),
   AppStateIOS: require('AppStateIOS'),
   AsyncStorage: require('AsyncStorage'),
-  BackAndroid: require('BackAndroid'),
   CameraRoll: require('CameraRoll'),
   Dimensions: require('Dimensions'),
   Easing: require('Easing'),
@@ -78,7 +71,6 @@
   NativeAppEventEmitter: require('RCTNativeAppEventEmitter'),
   NativeModules: require('NativeModules'),
   Platform: require('Platform'),
-  processColor: require('processColor'),
   requireNativeComponent: require('requireNativeComponent'),
 
   // Prop Types
```

As you can see, all the Android modules are absent.

Also, I noticed that [0.11.0.tgz](https://registry.npmjs.org/react-native/-/react-native-0.11.0.tgz) is **33M**, [0.11.1.tgz](https://registry.npmjs.org/react-native/-/react-native-0.11.1.tgz) is **622K** and [0.11.2.tgz](https://registry.npmjs.org/react-native/-/react-native-0.11.2.tgz) is **715K**. Weird.

**Comment by Tjorriemorrie** [comment]
Yes, it works if I revert back to 0.11.0. Don't you use deployment tests?

**Comment by ide** [comment]
Android is currently not tested in the open-source repo.

**Comment by brentvatne** [comment]
Android is tested now, this should work!
