### ISSUE TITLE
Alert RTL aligment wont work

### ISSUE THREAD

**Issue by razdahan** [facebook/react-native#30318]
## Description
I am trying to pop up an alert for the user, the app langugae is hebrew therfore I use I18nManager.forceRTL(true);  to force my app to be RTL but for some reason, the alert is not affected by this.
![image](https://user-images.githubusercontent.com/29332762/98133875-cad13c00-1ec6-11eb-8c23-ca1d1678e277.png)

## React Native version:
```
System:
    OS: Windows 10 10.0.18362
    CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
    Memory: 3.04 GB / 15.94 GB
  Binaries:
    Node: 12.16.3 - D:\NodeJS\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.4 - D:\NodeJS\npm.CMD
  IDEs:
    Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6200805
  npmPackages:
    react: ~16.9.0 => 16.9.0
    react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

## Steps To Reproduce

`
I18nManager.forceRTL(true);
Alert.alert(
      'אימות',
     'האם הינך מעוניין/ת לצאת מהאפליקציה?',
    [
      {text: 'אישור', onPress: () => BackHandler.exitApp()},
      {text: 'ביטול', style: 'cancel'},
    ],
);
`
Sorry but I didnt manage to format the code block correctly....
## Expected Results
The header should be aligned to the right side of the box and the buttons should be aligned to the buttom left side of the box.

This is a duplicate of #25948 which is closed due to lack of info\inactivity

**Comment by paperbackdragon** [comment]
Also running into this issue.

**Comment by alexg-93** [comment]
anyone have fixed it??? it's opened almost 3 years ago 
and its still not fixed??

**Comment by Ozaoujal** [comment]
09/11/2023, still no solution

**Comment by GaryGiebler** [comment]
Feb 1, 2024 We are seeing the same issue - still not resolved.

**Comment by omerts** [comment]
this still happens with react native 0.76.5

**Comment by Jamal-Ud-Din-hub** [comment]
Still not supporting RTL
