### ISSUE TITLE
Spamming The TextInput while spamming the button doesn't always clear the input.

### ISSUE THREAD

**Issue by SupertigerDev** [facebook/react-native#30319]
## Description
So, I'm creating a chat app using react native but have encountered this small bug. When spam sending messages while clicking the send button at the same time, the input field does not get cleared sometimes before sending the message which makes the old message add on to the new one.

I have only tested this on android. 

## React Native version:
```
System:
    OS: Windows 10 10.0.19041
    CPU: (4) x64 AMD Ryzen 3 2300U with Radeon Vega Mobile Gfx
    Memory: 1.10 GB / 6.92 GB
  Binaries:
    Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 30.0.0, 30.0.2
      System Images: android-Q | Android TV Intel x86 Atom
      Android NDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      Versions: 10.0.17763.0
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6858069
    Visual Studio: 15.9.28307.1234 (Visual Studio Community 2017)
  Languages:
    Java: 1.8.0_262
    Python: 2.7.18
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.3 => 0.63.3
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Spam on the keyboard and at the same time, spam on the send button

## Expected Results
The input box should clear out before sending the message. My guess is that the `onChangeText` event is changing the state faster than the `onPress` event which is making it re-enter the old value in the state and then appending it to the list.

## Snack, code example, screenshot, or link to a repository:
I have recreated this bug in a fresh minimal app: https://github.com/supertiger1234/React-Native-Bug-Recreation.
Here is also the link to the video of the bug: https://youtu.be/yGR7V7iQ-p8

## Code
```jsx
import React, {useState} from 'react';
import {
  StyleSheet,
  View,
  Text,
  TextInput,
  ScrollView,
  Button,
} from 'react-native';

const App = () => {
  const [messages, setMessages] = useState(['Message 1']);
  const [input, setInput] = useState('');
  return (
    <View style={styles.conatiner}>
      <ScrollView style={styles.scrollView}>
        {messages.map((message, i) => (
          <Text key={i}>{message}</Text>
        ))}
      </ScrollView>
      <View style={styles.messageArea}>
        <TextInput
          value={input}
          onChangeText={(text) => setInput(text)}
          style={styles.textInput}
          placeholder="Message"
          underlineColorAndroid="black"
        />
        <Button
          title="Send"
          onPress={() => {
            setMessages([input, ...messages]);
            setInput('');
          }}
        />
      </View>
    </View>
  );
};

const styles = StyleSheet.create({
  conatiner: {
    flex: 1,
  },
  textInput: {
    flex: 1,
  },
  messageArea: {
    flexDirection: 'row',
  },
});

export default App;
```

**Comment by fabriziobertoglio1987** [comment]
Do you still experience this issue? 

I have four years of experience maintaining facebook/react-native and I specialize in the Text and TextInput components. I currently have 58 [facebook/react-native PRs](https://github.com/facebook/react-native/pulls?q=is%3Apr+author%3Afabriziobertoglio1987+). 

If you still experience this issue, I will prepare a patched release with the fix.

Thanks a lot

**Comment by SupertigerDev** [comment]
Yes I still have this issue, for example when spamming letters in the textarea while clicking on a send button for example, it doesn't clear the input field. I only tested on android.

**Comment by SupertigerDev** [comment]
Forgot to mention that I haven't updated my react native version for about 8 months so it might be already fixed on the latest
