### ISSUE TITLE
The README file in this repo has a bad link - [404:NotFound]

### ISSUE THREAD

**Issue by MrCull** [facebook/react-native#30311]
## Description
The README file in this repo has a bad link - [404:NotFound]

Status code [404:NotFound] - Link: https://reactnative.dev/en/help

## React Native version:
n/a

## Steps To Reproduce
Click the link via the readme

## Expected Results
Link should work

## Snack, code example, screenshot, or link to a repository:
![image](https://user-images.githubusercontent.com/16634034/98023988-90e93280-1dff-11eb-9e20-ccb98484f318.png)

This was found by an new experimental hobby project that I have just created: https://github.com/MrCull/GitHub-Repo-ReadMe-Dead-Link-Finder
If this has been in any way helpful then please consider giving the above Repo a Star.

**Comment by cpojer** [comment]
Fixed in https://github.com/facebook/react-native/pull/30313.
