### ISSUE TITLE
[ TextInput ][ Android ] Bold text cropped on left for long strings

### ISSUE THREAD

**Issue by Anton-Petrovskyi** [facebook/react-native#30317]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
I am using TextInput with flexible width (depending on input length) with property `fontWeight:'bold'`. For iOS, the size of TextInput is calculated correctly, but for Android, I see left cropping of symbols on the left side.  I tried to use a custom font which is bold by default (without `fontWeight` property specified) but the problem remains. It seems that TextInput width is calculated for default font and setting bold to it makes this width invalid. The more symbols I type the bigger crop on the left (which approves my guess). 

## React Native version:
  Binaries:
    Node: 12.6.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.13.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.1, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 23, 25, 27, 28, 29
      Build Tools: 27.0.3, 28.0.3, 29.0.1, 29.0.2
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce

1. Create TextInpu with style={{fontWeight: 'bold', flex: 1}} 
2. Start typing the input value. After 5-10 symbols the first letter becomes cropped (Android only)

![image](https://user-images.githubusercontent.com/8090141/98131800-509fb800-1ec4-11eb-8fcc-9ecb8b006f33.png)

Without `fontWeight:'bold'` property:

![image](https://user-images.githubusercontent.com/8090141/98134112-14218b80-1ec7-11eb-8fa5-d64397fe1ff1.png)

## Expected Results
I can scroll to see the cutted-off string, but I would like to see it without scrolling unless there is no more space to grow.

## Snack, code example, screenshot, or link to a repository:

`<TextInput style={{  flex:1,  fontWeight: 'bold' }} value={this.state.value} onChangeText={this._onChangeText} maxLength={150} />`

**Comment by JCcastagne** [comment]
This is not stale. This is still an ongoing issue!

**Comment by dppo** [comment]
same issue!

**Comment by dppo** [comment]
same issue

**Comment by fabriziobertoglio1987** [comment]
Do you still experience this issue? 

I have four years of experience maintaining facebook/react-native and I specialize in the Text and TextInput components. I currently have 58 [facebook/react-native PRs](https://github.com/facebook/react-native/pulls?q=is%3Apr+author%3Afabriziobertoglio1987+). 

If you still experience this issue, I will prepare a patched release with the fix.

Thanks a lot
