### ISSUE TITLE
Missing 'Space' key event from external keyboard/barcode scanner after updating to 0.60+ version. Instead, Space event invokes onPress method of TouchableOpacity.

### ISSUE THREAD

**Issue by athul-sensehawk** [facebook/react-native#30322]
## Description
After updating react-native to above 0.60 version, event for 'Space' button not firing on Android. Other keyboard events work as usual.
This only happens if there is any Touchable React native element (like _TouchableOpacity_, _TouchableHighlight_) in the render method of the component. When space button event occurs the _TouchableOpacity_ `onPress` is getting called. 
## React Native version:
```
System:
OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 465.31 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 23, 26, 28, 29
      Build Tools: 23.0.1, 28.0.3, 29.0.1, 29.0.2, 29.0.3
      System Images: android-25 | Google APIs Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_212 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```
## Steps To Reproduce

1. Add listener for keyboard events.
2. In React Native component render method add _TouchableOpacity_ react native element.
2. Scan a barcode or enter a string or `adb` a string with _space_ keyCode (eg: `adb shell input text "a%sbc"` )

## Expected Results
input: `adb shell input text "a%sbc"` or Keyboard Input `a bc`
Expected Result : `a bc`
Event of 'Space' button works as usually before updating to above 0.60 a version of react native (Tested and confirmed in version 0.59.9).

## Snack, code example, screenshot, or link to a repository:
MainActivity.java
```
public class MainActivity extends ReactActivity {
      @Override
       public boolean onKeyUp(int keyCode, KeyEvent event) {
            Log.i("Debug", "onKeyUp   " + keyCode);
            return super.onKeyUp(keyCode, event);
       }
}
```

App.js 

```
import React from 'react';
import {
  View,
  TouchableOpacity,
  SafeAreaView,
  Text,
  StatusBar,
} from 'react-native';

const App: () => React$Node = () => {
  return (
    <>
      <StatusBar barStyle="dark-content" />
      <SafeAreaView>
        <View
          style={{
            width: '100%',
            height: '100%',
            backgroundColor: 'red',
          }}>
          <TouchableOpacity
            style={{
              alignItems: 'center',
              backgroundColor: '#42a7ea',
              padding: 10,
            }}
            onPress={() => console.warn('Button Clicked')}>
            <Text>Test Button</Text>
          </TouchableOpacity>
        </View>
      </SafeAreaView>
    </>
  );
};

export default App;
```

**Input**:
`adb shell input text "a%sbc"` or Keyboard input `a bc`

**Current Output:** 

**`As per the logs below the keyCode 62 of Space button is missing`**

<img width="578" alt="Screenshot 2020-11-05 at 10 22 43 PM" src="https://user-images.githubusercontent.com/59190639/98271012-7e185e80-1fb5-11eb-87ab-fe6ee9c9ab95.png">

**Expected Output:**

<img width="593" alt="Screenshot 2020-11-05 at 10 22 14 PM" src="https://user-images.githubusercontent.com/59190639/98271039-84a6d600-1fb5-11eb-9b49-a32cfe27b6a6.png">

**Comment by somasekharkakarla** [comment]
OnKeyUp is still having the issue in 0.60+.  instead, we can use:
`**dispatchKeyEvent**`
In MainActivity.java to handle this issue, Until the keyUp issue is fixed

**Example:**
```
 @Override
  public boolean dispatchKeyEvent(KeyEvent event) {
    int keyEvent = event.getAction();
    if(keyEvent == KeyEvent.ACTION_UP){
      KeyEventModule.getInstance().onKeyUpEvent(event.getKeyCode(), event);
    }
    return super.dispatchKeyEvent(event);
  }
```
