### ISSUE TITLE
Text numberOfLines={2} and other than ellipsizeMode="tail" breaks on Android

### ISSUE THREAD

**Issue by cristianc-infocorp** [facebook/react-native#30326]
Line constraint with ellipsizeMode set on a text component cannot perform any truncation on Android when numberOfLines is greater than 1 and ellipsizeMode other than 'tail'.

This fails: `<Text numberOfLines={2} ellipsizeMode="middle" >Some long text</Text>`
This works: `<Text numberOfLines={1} ellipsizeMode="middle" >Some long text</Text>`

Problem simile to [#19117](https://github.com/facebook/react-native/issues/19117) 

## React Native version:
System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 5.91 GB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.7.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.7 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.1, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 27, 28, 29
      Build Tools: 27.0.3, 28.0.3, 29.0.3, 30.0.0
      System Images: android-28 | Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-R | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.1/12A7403 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_252 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
On Android, combination of numberOfLines={2} and ellipsizeMode="middle" on a Text component fails to truncate the text and no ellipses are visible. When I remove ellipsizeMode it defaults to tail and it truncates the text without issue.

Code Snippet
```
//...
const lorem = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.';
//...
<Text numberOfLines={2} ellipsizeMode={'middle'}>
  {lorem}
</Text>
//...
```
## Expected Results
I expect Android should have the same functionality as iOS

Correct iOS Screenshot
![Screen Shot 2020-11-06 at 11 57 29](https://user-images.githubusercontent.com/34348834/98380453-5cf05600-2027-11eb-98f7-0ed6497d2a77.png)

## Actual Behavior
I have been working on this within my app and below is a screenshot of the section of my app where this is used.

Incorrect Android Screenshot
![Screen Shot 2020-11-06 at 11 57 21](https://user-images.githubusercontent.com/34348834/98380543-7b565180-2027-11eb-86e3-0120ab087ec1.png)

**Comment by fabriziobertoglio1987** [comment]
It is not supported by the androidsdk when using `setMaxLines > 1`. I will update the react-native docs

https://github.com/aosp-mirror/platform_frameworks_base/blob/523e3b9b7922685cff53d046884e0037004dcea7/core/java/android/widget/TextView.java#L10372-L10375

```java
     * If {@link #setMaxLines} has been used to set two or more lines,
     * only {@link android.text.TextUtils.TruncateAt#END} and
     * {@link android.text.TextUtils.TruncateAt#MARQUEE} are supported
     * (other ellipsizing types will not do anything).
     *
     * @attr ref android.R.styleable#TextView_ellipsize
     */
    public void setEllipsize(TextUtils.TruncateAt where) {
        // TruncateAt is an enum. != comparison is ok between these singleton objects.
        if (mEllipsize != where) {
            mEllipsize = where;

            if (mLayout != null) {
                nullLayouts();
                requestLayout();
                invalidate();
            }
        }
    }
```

**Comment by lpasquini** [comment]
This is still happening on RN 0.64.0.

**Comment by fabriziobertoglio1987** [comment]
Do you still experience this issue? 

I have four years of experience maintaining facebook/react-native and I specialize in the Text and TextInput components. I currently have 58 [facebook/react-native PRs](https://github.com/facebook/react-native/pulls?q=is%3Apr+author%3Afabriziobertoglio1987+). 

If you still experience this issue, I will prepare a patched release with the fix.

Thanks a lot
