### ISSUE TITLE
Add to the documentation how to publish an Android app to the google-play store

### ISSUE THREAD

**Issue by infowaybs** [facebook/react-native#3034]
Hello,

Show in the documentation an "oficial" way to publish an Android app to the google-play store. Look at this [stackoverflow question](http://stackoverflow.com/questions/32783344/deploy-publish-android-app-made-with-react-native).

Thanks.

**Comment by satya164** [comment]
I just sent a pull request to add the docs on this - https://github.com/facebook/react-native/pull/3061

**Comment by satya164** [comment]
This is already merged.
