### ISSUE TITLE
Top/bottom percentage margins on Text cause crash when within horizontal scrollview on iOS

### ISSUE THREAD

**Issue by dhruska** [facebook/react-native#30353]
## Description
When within a `ScrollView` with the prop `horizontal` set to `true`, certain variations of percentage margin on `Text` components cause crashes on iOS.

## React Native version:
`0.63.2`

## Steps To Reproduce
This can be reproduced by setting a top or bottom percentage margin on a `Text` component within a horizontal `ScrollView`. I've included some variations and links to Snack below.

## Expected Results
I would expect the app to not crash, and the margin to be applied.

## Snack, code example, screenshot, or link to a repository:
- [Left/right percentage margins](https://snack.expo.io/@donald/text,-left-right-percent-margin) - works
- [Top percentage margin](https://snack.expo.io/@donald/text,-top-percent-margin) - doesn't work
- [Bottom percentage margin](https://snack.expo.io/@donald/text,-bottom-percent-margin) - doesn't work

**Comment by TheRafaelFarias** [comment]
On Android is crashing too

**Comment by jduhking** [comment]
I am getting this same error whenever I try to apply a percentage margin between items in a horizontal flatlist
