### ISSUE TITLE
Android 4.4 (API 19) - Network Request Failed

### ISSUE THREAD

**Issue by vladislav-puzyrev** [facebook/react-native#30356]
##  Description
In android 4.4 (api 19 kitkat with google play), the Internet does not work in a newly created app **npx react-native init AwesomeProject** but it works on android 10 (api 30). 

An interesting observation, although network requests do not work, but sites open without problems via WebView.

## React Native version:
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
    Memory: 692.99 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
    Yarn: 1.22.5 - ~/.nvm/versions/node/v12.18.3/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v12.18.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 14.1, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 7, 8, 9
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2
      System Images: android-16 | Intel x86 Atom, android-19 | Google APIs Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Android TV Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.1/12A7403 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
  npmGlobalPackages:
    react-native: 0.60.5

## Steps To Reproduce
1. Create a new project - **npx react-native init AwesomeProject**
2. Replace the code App.js with this
```javascript
const App = () => {
  const [text, setText] = useState('load');

  useEffect(() => {
    fetch('https://jsonplaceholder.typicode.com/posts/1')
      .then((res) => res.json())
      .then((json) => setText(json.title));
  });

  return (
    <SafeAreaView>
      <Text>{text}</Text>
    </SafeAreaView>
  );
};
```
3. Run on the Android 4.4 emulator (API 19)

## Expected Results
The fetch request should return data from the server

## Snack, code example, screenshot, or link to a repository:
Demonstration repository - https://github.com/vladislav-puzyrev/react-native-network-error

**Comment by ravirajn22** [comment]
Support for android 19 is dropped so you have to probably debug it yourself and might expect lot of issues supporting older versions.

**Comment by vladislav-puzyrev** [comment]
Three days later, I found a solution. The problem was in TLS. This answer on StackOverflow helped me!
https://stackoverflow.com/questions/54110962/how-enable-tls-1-1-and-1-2-in-react-native-android/55365033#55365033
