### ISSUE TITLE
Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication) upgrading from 0.60.5 to 0.63.3

### ISSUE THREAD

**Issue by ZaidTryngo** [facebook/react-native#30357]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
I am facing issues in upgrading from the 
![Screenshot 2020-11-10 at 3 43 36 PM](https://user-images.githubusercontent.com/72140864/98675528-32cacb00-237c-11eb-8262-c07455f8e452.png)
`0.60.5 to  0.63.3` version. the app is stuck and not running.  Error is  

> Invariant Violation: Native modules cannot be null. 
> 
> Invariant Violation: Module AppRegistry is not a registered callable
> module (calling run application).

## React Native version:
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 822.18 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.3 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.6 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 23, 25, 27, 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3
      System Images: android-25 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_242 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: ^0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.
2.

## Expected Results
Describe what you expected to happen.

## Snack, code example, screenshot, or link to a repository:
Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by xtealer** [comment]
There is not release `0.63.5`, lastest version is `0.63.3`. Check on https://react-native-community.github.io/upgrade-helper/ for changes to be made in order for the update to be completed successfully.

**Comment by baronhsiao** [comment]
same issue

**Comment by jcerrutti** [comment]
I'm having the same issue, but only on android platform

**Comment by chgsilva** [comment]
same issue here, any help?

**Comment by chgsilva** [comment]
There was another exception during my inicialization an it was preventing the AppRegistry to load itself. Once I clear other exceptions, this one disappear.

**Comment by andrewdazs** [comment]
This is happening with me too, upgrading RN from `0.60.4` to `0.63.3` and I don't know what is going on:

<img width="1251" alt="Screen Shot 2020-12-09 at 9 34 18 AM" src="https://user-images.githubusercontent.com/21009570/101630543-c3d7a500-3a01-11eb-9c8d-fac8b853d5b0.png">

**Comment by vishaldhanotiya** [comment]
Same issue facing when trying to upgrade react-native version 0.55 to 0.63.4

**Comment by marwan2** [comment]
Same issue, stupid buggy React Native
