### ISSUE TITLE
Support for hot module replacement

### ISSUE THREAD

**Issue by lemonmade** [facebook/react-native#3036]
As we're working on React Native apps at Shopify, we're finding that the full app reload on file changes leads to frustratingly long cycles, particularly for simpler changes. The way this is solved on the web side is with hot module replacement, most commonly achieved with a few [Webpack+Babel-related plugins](https://github.com/gaearon/react-transform-hmr).

I've read as much of the discussion on [Packager vs Webpack](https://github.com/facebook/react-native/issues/5) as I could find in the issues, and progress on this front seems to have stalled. There is a [Webpack dev server that works with React Native](https://github.com/mjohnston/react-native-webpack-server), but we are worried about jumping into something not supported directly by Facebook given the speed of changes to React Native.

Do you plan to integrate hot module replacement (or a plugin architecture that would allow others to support it) at some point? If not, what is the recommended way to deal with the need to recreate state/ navigate back to parts of the application after every reload?

cc/ @gaearon, since it seems like you likely have some opinions/ insight on this :)

**Comment by astreet** [comment]
cc @tadeuzagallo who was thinking about this

**Comment by gaearon** [comment]
It would be awesome if Packager supported [HMR](http://webpack.github.io/docs/hot-module-replacement.html). Webpack has it, [there's an HMR plugin for Browserify now too](https://github.com/AgentME/browserify-hmr), and even if the API is not perfect, it's nice to be able to reuse parts of the ecosystem, e.g. this lets [react-transform-hmr](https://github.com/gaearon/react-transform-hmr/) enable hot reloading both for Webpack and Browserify.

**Comment by gaearon** [comment]
More on HMR: http://webpack.github.io/docs/hot-module-replacement-with-webpack.html

**Comment by brentvatne** [comment]
> There is a Webpack dev server that works with React Native, but we are worried about jumping into something not supported directly by Facebook given the speed of changes to React Native.

@lemonmade - just throwing it out there, perhaps this is something that Shopify could take lead on? It would be an incredible contribution

**Comment by lemonmade** [comment]
What would the ideal solution look like from your perspective? From the previous discussion it looks to be that Packager has to stay around for the RN code, so would there ideally be a HMR mechanism built into Packager?

**Comment by brentvatne** [comment]
cc @amasad @vjeux

**Comment by amasad** [comment]
It's definitely something we're interested in. The only issue I see with committing to Webpack's HMR is that it dictates what the final shape of our bundles should be. There are perf-related opportunities in bundling that we'd like to explore. For example [React recently started bundling into a flat file](https://github.com/facebook/react/pull/4230 ) (i.e. no module boundaries) and got 30% perf win and 15% in filesize reduction.

**Comment by brentvatne** [comment]
This is in progress: https://github.com/facebook/react-native/commit/4ffb24164712c0f0cafc7c097a0cdbc80e2c04d1 -- should be in OSS very soon! @martinbigio can you close this when it's ready? :)

**Comment by martinbigio** [comment]
Sure :)

**Comment by mmeineke** [comment]
Hello everyone.
How is the progress on this? I see that something is already implemented in the packager but can't find any infos how to use it. Does it already work standalone in react-native? Or is something like react-transform-hmr still needed?

**Comment by martinbigio** [comment]
@mmeineke we haven't officially release it though many people are using it at exponentjs and facebook. At the moment it only works for React components (no support for modules that export functions nor redux stores). It works standalone in `react-native`, `react-transform-hmr` is used under the hood ;)

**Comment by aleclarson** [comment]
@martinbigio I'm curious, what changes/additions are needed to support redux stores?

**Comment by martinbigio** [comment]
I had to implement webpack's accept algorithm that walks through the dependency tree trying to accept HRM updates. If a module cannot be self accepted we need to look if all it's parents can accept it. Need to do this recursively until the HMR update can be accepted.

On the redux store, you'd simply have to implement the accept HMR function as you'd do on a React (web) app:

```
import { createStore, applyMiddleware, compose } from 'redux';
import thunk from 'redux-thunk';
import reducer from '../reducers';

export default function configureStore(initialState) {
  const store = createStore(
    reducer,
    initialState,
    applyMiddleware(thunk),
  );

  if (module.hot) {
    // Enable Webpack hot module replacement for reducers
    module.hot.accept(() => {
      const nextRootReducer = require('../reducers/index').default;
      store.replaceReducer(nextRootReducer);
    });
  }

  return store;
};
```

**Comment by martinbigio** [comment]
(the code inside the `if (module.hot) {` is the important part)

**Comment by respectTheCode** [comment]
Any progress on this?

**Comment by martinbigio** [comment]
Yup, it's ready on 0.22rc.

**Comment by ptomasroos** [comment]
Awesome news @martinbigio

**Comment by jsierles** [comment]
Closing this issue as HMR is implemented in the upcoming release of React Native 0.22.
