### ISSUE TITLE
How to improve flatlist speed

### ISSUE THREAD

**Issue by muhammadwafa** [facebook/react-native#30360]
I have a chat app, which the messages are encrypted, and when I load them to the flatlist it works too slow. blank area and unresponsive.

I used any tricks on the internet but still is slow. what Can I do help please

**Comment by myckhel** [comment]
I suggest you try out this library 
https://github.com/Flipkart/recyclerlistview
Its a life saver.

I got to to a point whereby i couldn't optimize flatlist again 
But after using the library i was satisfied with the performance.

**Comment by muhammadwafa** [comment]
@myckhel thank you, Yeah I used it, but it has some shifting problem as my list items height is not same. there is dynamic height.

**Comment by myckhel** [comment]
I believe that shouldn't be a problem with recycler. 
It could be the way you have configured it.
You could have asked for assistance on the problems you faced rather than giving up on it.

**Comment by m4rcoperuano** [comment]
Maybe this could help: https://dev.to/m4rcoperuano/react-native-best-practices-when-using-flatlist-or-sectionlist-4j41

I wrote this a while ago, though it should still be relevant. Hopefully it can help!

**Comment by muhammadwafa** [comment]
@m4rcoperuano, @myckhel  thank you
