### ISSUE TITLE
require_relative '../xxx/node_modules/@react-native-community/cli-platform-ios/native_modules'

### ISSUE THREAD

**Issue by lengqingfeng** [facebook/react-native#30369]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
0.63.3 pod not work path ../xx/node_modules

## React Native version:
0.63.3

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. pod install

## Expected Results
[!] Invalid `Podfile` file: [!] /usr/local/bin/node -e try {console.log(require('@react-native-community/cli').bin);} catch (e) {console.log(require('react-native/cli').bin);}

internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'react-native/cli'
Require stack:
- /Users/lsr/Documents/GJProject/cstore-iOS/[eval]
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at [eval]:1:87
    at Script.runInThisContext (vm.js:132:18)
    at Object.runInThisContext (vm.js:309:38)
    at internal/process/execution.js:77:19
    at [eval]-wrapper:6:22
    at evalScript (internal/process/execution.js:76:60) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/lsr/Documents/GJProject/cstore-iOS/[eval]' ]
}

pod path 
require_relative '../CStoreReactNative/node_modules/react-native/scripts/react_native_pods'
require_relative '../CStoreReactNative/node_modules/@react-native-community/cli-platform-ios/native_modules'

**Comment by popejrh19** [comment]
Stop

William Pope Jr

**Comment by popejrh19** [comment]
Unsubscribe

William Pope Jr
