### ISSUE TITLE
Please do not recommend installing `nvm` with homebrew

### ISSUE THREAD

**Issue by ljharb** [facebook/react-native#3037]
Per http://facebook.github.io/react-native/docs/getting-started.html#requirements - "Homebrew is the recommended way to install nvm" this is not the case. I'm the maintainer of `nvm`, and I do not in any way support or recommend installing nvm with homebrew. (See https://github.com/creationix/nvm/issues/850#issuecomment-143236495 for some background)

Please either:
 1) use the `curl` command in the readme on http://nvm.sh to install nvm, which is currently the sole recommended way to install it.
or
 2) change the documentation to indicate that Facebook recommends it but `nvm` does not, so that a support burden is not created for me by users who expect that `brew install nvm` should work properly.

Thanks!

**Comment by ide** [comment]
I'll update this since I added the nvm mention in the first place (previously it suggested installing Node via brew but nvm is a winner in my eyes - so thanks for that).

**Comment by ljharb** [comment]
Thanks, much obliged!
