### ISSUE TITLE
Inverted FlatList accessibility order

### ISSUE THREAD

**Issue by zarubond** [facebook/react-native#30373]
## Description
In normal FlatList the accessibility focus order is from top to bottom but applying inverted property makes the order swap to bottom to top. This breaks the accessibility navigation flow as it is assumed that it should go from top of the screen to the bottom.

## React Native version:
RN 0.63 and Android 9 with enabled TalkBack

## Steps To Reproduce
Use FlatList component like 

<FlatList ... inverted={ true } />

## Expected Results
The order of items should stay inverted but the accessibility order should be maintained top to bottom.

## Snack, code example, screenshot, or link to a repository:
Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by teod** [comment]
are there any updates for this ticket ?

**Comment by grgr-dkrk** [comment]
I had the same problem.

The VirtualizedList implementation seems to styling `transform: [{scaleY: -1}]` to reverse the order.
This does not guarantee the reading order of the screen reader as it only changes the visual order.
https://github.com/facebook/react-native/blob/b28fa2dae061cff829e00afec565fe8a05ef0a5a/Libraries/Lists/VirtualizedList.js#L864-L868

I don't understand the implementation context, but changing this to `flexDirection: column-reverse` seems to solve it.
Is it impossible?

**Comment by mallenexpensify** [comment]
We're interested in getting this issue fixed and willing to compensate to do so. View issue https://github.com/Expensify/Expensify.cash/issues/1341

**Comment by sfuqua** [comment]
Is it possible to add the "Accessibility" tag to this issue? Not sure how closely the [task board](https://github.com/facebook/react-native/projects/15) is still being tracked but this is a pretty fundamental issue for Android in an important control.

This breaks Android screen reader support in any inverted list which is common e.g. for chat scenarios.

**Comment by MaksimDiubo** [comment]
I had the same problem. Are there any updates for this ticket ?

**Comment by fabriziobertoglio1987** [comment]
One possible solution would be not using [transform](https://github.com/facebook/react-native/blob/873ff0c13b33d03af3060ecfc8fc9d31e0c5f589/Libraries/Lists/VirtualizedList.js#L2173-L2178) to invert the list, but actually inverting it.
The solution may create some regression in other functionalities, but also fix existing issues https://github.com/facebook/react-native/issues/17553#issuecomment-617233282 (using transform causes un-expected behavior for ex. showing activity indicator at the bottom instead of top of the flatlist).

- [ ] using existing native Android/iOS API to reverse the ScrollView
- [ ]  inverting the order of the list (in [Java](https://duckduckgo.com/?t=ffab&q=Collections.reverse&ia=web), objc or Javascript) ==> May be relatively complex to handle all the use cases

**Comment by fabriziobertoglio1987** [comment]
<details><summary>The accessibility focus order is from top to bottom, but applying FlatList inverted property makes the order swap to bottom to top.</summary>
<p>

Example
https://snack.expo.dev/@fabrizio.bertoglio/inverted-flatlist

<details><summary>Inverted set to false</summary>
<p>


<video src="https://user-images.githubusercontent.com/24992535/177082524-e1510eec-4bf8-441f-a569-8f88e52ebcfe.mp4" width="200" />







</p>
</details>



<details><summary>Inverted set to true</summary>
<p>

<video src="https://user-images.githubusercontent.com/24992535/177082531-3e42b2b9-f8a7-4fa0-8ef6-d376449a1639.mp4" width="200" />


</p>
</details>


</p>
</details>

**Comment by fabriziobertoglio1987** [comment]
<details><summary>Evaluate the performance implications of using transform vs JavaScript vs Native Solution.</summary>
<p>

**Transform** 
The implementation of [transform][1] includes:
- Fabric C++ logic included in the [Transform.cpp][2] class (for ex. the implementation of [Translate][3])
- iOS implementation - [Transform.m][6]
- Android implementation - [BaseViewManager#setTransformProperty][5] and [TransformHelper#processTransform][4] 


</p>
</details>

[1]: https://reactnative.dev/docs/0.68/transforms#transform "reactnative transform documentation"
[2]: https://github.com/facebook/react-native/blob/873ff0c13b33d03af3060ecfc8fc9d31e0c5f589/ReactCommon/react/renderer/graphics/Transform.cpp "fabric c++ transform logic"
[3]: https://github.com/facebook/react-native/blob/873ff0c13b33d03af3060ecfc8fc9d31e0c5f589/ReactCommon/react/renderer/graphics/Transform.cpp#L58 "translate implementation in fabric c++"
[4]: https://github.com/facebook/react-native/blob/873ff0c13b33d03af3060ecfc8fc9d31e0c5f589/ReactAndroid/src/main/java/com/facebook/react/uimanager/TransformHelper.java#L94 "TransformHelper#processTransform is responsible for applying the tranlateX and translateY effects"
[5]: https://github.com/facebook/react-native/blob/873ff0c13b33d03af3060ecfc8fc9d31e0c5f589/ReactAndroid/src/main/java/com/facebook/react/uimanager/BaseViewManager.java#L447 "BaseViewManager#setTransformProperty"
[6]: https://github.com/facebook/react-native/blob/873ff0c13b33d03af3060ecfc8fc9d31e0c5f589/React/Views/RCTConvert+Transform.m#L14

**Comment by fabriziobertoglio1987** [comment]
<details><summary>implement scroll to top optimization for inverted FlatList</summary>
<p>

The normal FlatList keeps the first initialNumToRender items always rendered (first page) and immediately renders the items starting at this initial index. The same optimization needs to be implemented for inverted FlatList.

https://github.com/fabriziobertoglio1987/react-native/commit/28aaa8880809bb25db2a6c51fedf01a82064965c

>== [Lists] Add initialScrollIndex prop

>Makes it easy to load a VirtualizedList at a location in the middle of the content without
wasting time rendering initial rows that aren't relevant, for example when opening an infinite calendar
view to "today".

>**Test Plan: **
>With debug overlay, set `initialScrollIndex={52}` prop in `FlatListExample` and
and see it immediately render a full screen of items with item 52 aligned at the top of the screen. Note
no initial items are mounted per debug overlay. Scroll around a bunch and everything else seems to work
as normal.

>No SectionList impl since `getItemLayout` isn't easy to use there.

</p>
</details>

**Comment by fabriziobertoglio1987** [comment]
<details><summary>how initialScrollIndex changes the items rendered on the screen</summary>
<p>


`initialScrollIndex` is used to calculate `this.state.first` and `last`.
- `first` is either item index 0 or `initialScrollIndex`
- `last` is `first + 10`

https://github.com/facebook/react-native/blob/873ff0c13b33d03af3060ecfc8fc9d31e0c5f589/Libraries/Lists/VirtualizedList.js#L719-L729

the items between first and last are added in the cells variables which is called on render

https://github.com/facebook/react-native/blob/873ff0c13b33d03af3060ecfc8fc9d31e0c5f589/Libraries/Lists/VirtualizedList.js#L816-L846

</p>
</details>

**Comment by fabriziobertoglio1987** [comment]
<details><summary>use initialScrollIndex to start from bottom, but keep scrollToBottom optimization</summary>
<p>

the android ScrollView widget method fullScroll allow to start the ScrollView from the Button

https://stackoverflow.com/a/30224427/7295772
https://github.com/aosp-mirror/platform_frameworks_base/blob/19e53cfdc8a5c6ef45c0adf2dd239576ddce5822/core/java/android/widget/ScrollView.java#L1187

my current solution uses `this.scrollToEnd({animated: false})`, as [initialScrollIndex](https://reactnative.dev/docs/0.68/flatlist#initialscrollindex) requires a static layout.

The best solution is changing `state.first` to be `data.length - 1 - initialNumToRenderOrDefault(this.props.initialNumToRender)` if inverted prop is true

https://github.com/facebook/react-native/blob/3da3d82320bd035c6bd361a82ea12a70dba4e851/Libraries/Lists/VirtualizedList.js#L720


</p>
</details>

**Comment by fabriziobertoglio1987** [comment]
<details><summary>main branch - scrollToEnd does not work for nested FlatList with different orientations (horizontal/vertical)</summary>
<p>

In the example above the FlatList is not inverted. 
- Expected Result: the [last page](https://user-images.githubusercontent.com/24992535/177899515-ecb62f30-b02f-46b8-adad-b62a27d9327a.png) is displayed.
- Actual Result: the [first page](https://user-images.githubusercontent.com/24992535/177899635-f92e4dee-738f-458e-8526-2bd2561cabb8.png) is displayed.

<details><summary>SourceCode of the example</summary>
<p>

```javascript
/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @flow strict-local
 * @format
 */
import React from 'react';
import {
  SafeAreaView,
  View,
  FlatList,
  StyleSheet,
  Text,
  StatusBar,
} from 'react-native';

const DATA = [
  {
    id: 'bd7acbea-c1b1-46c2-aed5-3ad53abb28ba',
    title: 'First Item',
  },
  {
    id: '3ac68afc-c605-48d3-a4f8-fbd91aa97f63',
    title: 'Second Item',
  },
  {
    id: '58694a0f-3da1-471f-bd96-145571e29d72',
    title: 'Third Item',
  },
  {
    id: 'bd7acbea-c1b1-46c2-aed5-3ad53abb8bbb',
    title: 'Fourth Item',
  },
  {
    id: '3ac68afc-c605-48d3-a4f8-fbd91aa97676',
    title: 'Fifth Item',
  },
  {
    id: '58694a0f-3da1-471f-bd96-145571e27234',
    title: 'Sixth Item',
  },
  {
    id: '58694a0f-3da1-471f-bd96-145571e29234',
    title: 'Seven Item',
  },
  {
    id: '58694a0f-3da1-471f-bd96-145571429234',
    title: 'Eight Item',
  },
  {
    id: '58694a0f-3da1-471f-bd96-115571429234',
    title: 'Nine Item',
  },
  {
    id: '58694a0f-3da1-471f-bd96-1155h1429234',
    title: 'Ten Item',
  },
];

const Item = ({title}) => (
  <Text style={[styles.item, styles.title]}>{title}</Text>
);

const renderItem = ({item}) => <Item title={item.title} />;
const ITEM_HEIGHT = 50;

const renderFlatList = ({item}) => <NestedFlatList item={item} />;

function NestedFlatList(props) {
  let flatlist = React.useRef(0);
  React.useEffect(() => {
    // flatlist.scrollToOffset({offset: 697.5, animated: false});
    flatlist.scrollToEnd({animated: false});
  }, []);
  return (
    <View>
      <Text>Flatlist {props.item}</Text>
      <FlatList
        // inverted={true}
        ref={ref => (flatlist = ref)}
        renderItem={renderItem}
        data={DATA}
      />
    </View>
  );
}

const FlatList_nested = () => {
  let flatlist = React.useRef(0);
  React.useEffect(() => {
    // flatlist.scrollToOffset({offset: 1300, animated: false});
    // flatlist.scrollToEnd({animated: false})
  }, []);
  return (
    <FlatList
      ref={ref => (flatlist = ref)}
      data={[1]}
      horizontal
      inverted={false}
      renderItem={renderFlatList}
      keyExtractor={item => item.toString()}
    />
  );
};

const styles = StyleSheet.create({
  item: {
    backgroundColor: '#f9c2ff',
    padding: 20,
    marginVertical: 8,
    marginHorizontal: 16,
  },
  title: {
    fontSize: 16,
  },
});

export default ({
  title: 'Nested',
  name: 'nested',
  description: 'Test inverted prop on FlatList',
  render: () => <FlatList_nested />,
}: RNTesterModuleExample);
```

</p>
</details>

<video src="https://user-images.githubusercontent.com/24992535/177899159-bd699ffd-c3f3-4d93-817e-99c42a430dab.mov" width="1000" />

</p>
</details>

**Comment by fabriziobertoglio1987** [comment]
<details><summary>Main - Normal FlatList behaviour scroll position adding new items</summary>
<p>

<details><summary>sourcecode example</summary>
<p>

```javascript
*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @flow strict-local
 * @format
 */
import React from 'react';
import {
  SafeAreaView,
  View,
  FlatList,
  StyleSheet,
  Text,
  StatusBar,
  Button,
} from 'react-native';

const Item = ({title}) => (
  <Text style={[styles.item, styles.title]}>{title}</Text>
);

const renderItem = ({item}) => <Text style={styles.item}>{item.title}</Text>;
const ITEM_HEIGHT = 50;

const renderFlatList = ({item}) => <NestedFlatList item={item} />;

const FlatList_nested = () => {
  let flatlist = React.useRef(null);
  const [items, addItem] = React.useState(DATA);
  return (
    <>
      <Button
        title="add an item"
        onPress={() => addItem([...items, {title: 'new item'}])}
      />
      <FlatList
        // inverted={true}
        horizontal
        onContentSizeChange={() => flatlist.scrollToEnd()}
        ref={ref => (flatlist = ref)}
        renderItem={renderItem}
        data={items}
      />
    </>
  );
};

const styles = StyleSheet.create({
  item: {
    backgroundColor: '#f9c2ff',
    padding: 20,
    marginVertical: 8,
    marginHorizontal: 16,
  },
  title: {
    fontSize: 16,
  },
});

export default ({
  title: 'Nested',
  name: 'nested',
  description: 'Test inverted prop on FlatList',
  render: () => <FlatList_nested />,
}: RNTesterModuleExample);

const DATA = [
  {
    id: 'bd7acbea-c1b1-46c2-aed5-3ad53abb28ba',
    title: 'First Item',
  },
  {
    id: '3ac68afc-c605-48d3-a4f8-fbd91aa97f63',
    title: 'Second Item',
  },
  {
    id: '58694a0f-3da1-471f-bd96-145571e29d72',
    title: 'Third Item',
  },
  {
    id: 'bd7acbea-c1b1-46c2-aed5-3ad53abb8bbb',
    title: 'Fourth Item',
  },
  {
    id: '3ac68afc-c605-48d3-a4f8-fbd91aa97676',
    title: 'Fifth Item',
  },
  {
    id: '58694a0f-3da1-471f-bd96-145571e27234',
    title: 'Sixth Item',
  },
  {
    id: '58694a0f-3da1-471f-bd96-145571e29234',
    title: 'Seven Item',
  },
  {
    id: '58694a0f-3da1-471f-bd96-145571429234',
    title: 'Eight Item',
  },
  {
    id: '58694a0f-3da1-471f-bd96-115571429234',
    title: 'Nine Item',
  },
  {
    id: '58694a0f-3da1-471f-bd96-1155h1429234',
    title: 'Ten Item',
  },
];
```
</p>
</details>

<video src="https://user-images.githubusercontent.com/24992535/177915166-4908935c-7703-43d6-8cbc-6efd75ffe156.mov" width="1000" />

</p>
</details>

<details><summary>Main - Inverted FlatList behaviour scroll position adding new items</summary>
<p>

<details><summary>sourcecode example</summary>
<p>

```javascript
*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @flow strict-local
 * @format
 */
import React from 'react';
import {
  SafeAreaView,
  View,
  FlatList,
  StyleSheet,
  Text,
  StatusBar,
  Button,
} from 'react-native';

const Item = ({title}) => (
  <Text style={[styles.item, styles.title]}>{title}</Text>
);

const renderItem = ({item}) => <Text style={styles.item}>{item.title}</Text>;
const ITEM_HEIGHT = 50;

const renderFlatList = ({item}) => <NestedFlatList item={item} />;

const FlatList_nested = () => {
  let flatlist = React.useRef(null);
  const [items, addItem] = React.useState(DATA);
  return (
    <>
      <Button
        title="add an item"
        onPress={() => addItem([...items, {title: 'new item'}])}
      />
      <FlatList
        inverted={true}
        horizontal
        onContentSizeChange={() => flatlist.scrollToEnd()}
        ref={ref => (flatlist = ref)}
        renderItem={renderItem}
        data={items}
      />
    </>
  );
};

const styles = StyleSheet.create({
  item: {
    backgroundColor: '#f9c2ff',
    padding: 20,
    marginVertical: 8,
    marginHorizontal: 16,
  },
  title: {
    fontSize: 16,
  },
});

export default ({
  title: 'Nested',
  name: 'nested',
  description: 'Test inverted prop on FlatList',
  render: () => <FlatList_nested />,
}: RNTesterModuleExample);

const DATA = [
  {
    id: 'bd7acbea-c1b1-46c2-aed5-3ad53abb28ba',
    title: 'First Item',
  },
  {
    id: '3ac68afc-c605-48d3-a4f8-fbd91aa97f63',
    title: 'Second Item',
  },
  {
    id: '58694a0f-3da1-471f-bd96-145571e29d72',
    title: 'Third Item',
  },
  {
    id: 'bd7acbea-c1b1-46c2-aed5-3ad53abb8bbb',
    title: 'Fourth Item',
  },
  {
    id: '3ac68afc-c605-48d3-a4f8-fbd91aa97676',
    title: 'Fifth Item',
  },
  {
    id: '58694a0f-3da1-471f-bd96-145571e27234',
    title: 'Sixth Item',
  },
  {
    id: '58694a0f-3da1-471f-bd96-145571e29234',
    title: 'Seven Item',
  },
  {
    id: '58694a0f-3da1-471f-bd96-145571429234',
    title: 'Eight Item',
  },
  {
    id: '58694a0f-3da1-471f-bd96-115571429234',
    title: 'Nine Item',
  },
  {
    id: '58694a0f-3da1-471f-bd96-1155h1429234',
    title: 'Ten Item',
  },
];
```
</p>
</details>

<video src="https://user-images.githubusercontent.com/24992535/177915518-35e44f8e-4ff0-42ed-85c7-1a843f1bdc84.mov" width="1000" />

</p>
</details>

**Comment by fabriziobertoglio1987** [comment]
<details><summary>Testing TalkBack navigation in an inverted nested Flatlist</summary>
<p>

<details><summary>sourcecode example</summary>
<p>

```javascript
import React from "react";
import {
  SafeAreaView,
  View,
  FlatList,
  StyleSheet,
  Text,
  StatusBar,
  Button,
} from "react-native";

const DATA = [
  {
    id: "bd7acbea-c1b1-46c2-aed5-3ad53abb28ba",
    title: "First Item",
  },
  {
    id: "3ac68afc-c605-48d3-a4f8-fbd91aa97f63",
    title: "Second Item",
  },
  {
    id: "58694a0f-3da1-471f-bd96-145571e29d72",
    title: "Third Item",
  },
  {
    id: "bd7acbea-c1b1-46c2-aed5-3ad53abb8bbb",
    title: "Fourth Item",
  },
  {
    id: "3ac68afc-c605-48d3-a4f8-fbd91aa97676",
    title: "Fifth Item",
  },
  {
    id: "58694a0f-3da1-471f-bd96-145571e27234",
    title: "Sixth Item",
  },
  {
    id: "58694a0f-3da1-471f-bd96-145571e29234",
    title: "Seven Item",
  },
  {
    id: "58694a0f-3da1-471f-bd96-145571429234",
    title: "Eight Item",
  },
  {
    id: "58694a0f-3da1-471f-bd96-115571429234",
    title: "Nine Item",
  },
  {
    id: "58694a0f-3da1-471f-bd96-1155h1429234",
    title: "Ten Item",
  },
];

const Item = ({ title }) => (
  <Text style={[styles.item, styles.title]}>{title}</Text>
);

const renderItem = ({ item }) => <Item title={item.title} />;
const ITEM_HEIGHT = 50;

const renderFlatList = ({ item }) => (
  <NestedFlatList item={item} />
);

function NestedFlatList(props) {
  const [items, setItems] = React.useState(DATA);
  return (
    <View>
      <Button
      title="add an item"
      onPress={() => setItems([...items, {title: 'new item'}])}
      />
      <Button
        title="remove an item"
        onPress={() => {
          const newItems = [...items];
          newItems.splice(items.length - 1, 1)
          setItems(newItems);
        }}
      />
      <Text>Flatlist</Text>
      <FlatList
        style={{height: 400}}
        inverted={true}
        renderItem={renderItem} data={items} />
    </View>
  )
}

const FlatList_nested = () => {
  let flatlist = React.useRef(0);
  return (
    <FlatList
      ref={(ref) => flatlist = ref}
      data={[1,2,3]}
      horizontal
      renderItem={renderFlatList}
      keyExtractor={(item) => item.toString()}
    />
  );
};

const styles = StyleSheet.create({
  item: {
    backgroundColor: "#f9c2ff",
    padding: 20,
    marginVertical: 8,
    marginHorizontal: 16,
  },
  title: {
    fontSize: 16,
  },
});

export default ({
  title: 'Nested',
  name: 'nested',
  description: 'nested FlatList',
  render: () => <FlatList_nested />,
}: RNTesterModuleExample);

```

</p>
</details>


<video src="https://user-images.githubusercontent.com/24992535/177933773-0236064f-6830-465b-89ae-5c304dbcd588.mov" width="1000" />



</p>
</details>

**Comment by fabriziobertoglio1987** [comment]
https://user-images.githubusercontent.com/24992535/178217173-25c4fabd-d93e-42ea-98c3-62e4f66ae69b.mp4

**Comment by fabriziobertoglio1987** [comment]
<details><summary>Planning and Designing the Solution</summary>
<p>

- [x] Create an initial [example](https://snack.expo.dev/@fabrizio.bertoglio/manually-inverting-flatlist) of the solution with Expo.
- [x] inverting the order of the list in Javascript
        for ex. [1,2,3].reverse() ==> [3,2,1]
                    [{ key: 1, text: "1"}, { key: 2, text: "2"}, { key: 3, text: "3"}] => 
                    [{ key: 3, text: "3"}, { key: 2, text: "2"}, { key: 1, text: "1"}]
- [x] starting position needs to be the end of the FlatList ([initialScrollIndex](https://reactnative.dev/docs/0.68/flatlist#initialscrollindex))

</p>
</details>

**Comment by fabriziobertoglio1987** [comment]
<details><summary>children should not be inverted if nested in a FlatList with prop inverted</summary>
<p>

<video src="https://user-images.githubusercontent.com/24992535/178280235-53972249-d832-42e8-8a4a-1d6faa95803e.mov" width="1000" />

</p>
</details>

**Comment by fabriziobertoglio1987** [comment]
<details><summary>main - FlatList does not scroll after appending new items</summary>
<p>

<video src="https://user-images.githubusercontent.com/24992535/178517801-aa78ecb9-a89a-4991-b919-afc09c5e0210.mov" width="1000" />

</p>
</details>

**Comment by fabriziobertoglio1987** [comment]
>when items are appended to the end of the list, the view needs to stay in the same position

Related to https://github.com/facebook/react-native/pull/34141#issuecomment-1183209028

Option 1) 
- [ ] Find out the Android Java code responsible for triggering the scroll to the Top when items are appended (prepended in a not inverted list)
- [ ] disable this behaviour

Option 2) Find the x/y coordinate and scroll to that position after item is appended
- [ ] first, last could be used to restore the FlatList at a previous position
- [ ] find out first coordinate
- [ ] trigger a scroll to that coordinate

This can not be done without using getItemLayout (fixed height and width for each item)

Option 3) [Support for ScrollView.maintainVisibleContentPosition on Android](https://github.com/facebook/react-native/pull/29466/files#)

**Comment by fabriziobertoglio1987** [comment]
<details><summary>Option 2) Find the x/y coordinate and scroll to that position after the item is appended</summary>
<p>

>when items are appended to the end of the list, the view needs to stay in the same position (javascript draft solution)

Draft solution only using JavaScript. It is not optimized but will be useful to implement the solution in Java/Javascript step by step.

<details><summary>click to open sourcecode of the example</summary>
<p>

```javascript
/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @flow strict-local
 * @format
 */
import * as React from 'react';
import {useState, useRef} from 'react';
import type {RNTesterModuleExample} from '../../types/RNTesterTypes';
import {
  SafeAreaView,
  View,
  FlatList,
  StyleSheet,
  Text,
  StatusBar,
  Button,
} from 'react-native';

const DATA = [
  {
    id: 'bd7acbea-c1b1-46c2-aed5-3ad53abb28ba',
    title: 'First Item',
  },
  {
    id: '3ac68afc-c605-48d3-a4f8-fbd91aa97f63',
    title: 'Second Item',
  },
  {
    id: '58694a0f-3da1-471f-bd96-145571e29d72',
    title: 'Third Item',
  },
  {
    id: 'bd7acbea-c1b1-46c2-aed5-3ad53abb8bbb',
    title: 'Fourth Item',
  },
  {
    id: '3ac68afc-c605-48d3-a4f8-fbd91aa97676',
    title: 'Fifth Item',
  },
  {
    id: '58694a0f-3da1-471f-bd96-145571e27234',
    title: 'Sixth Item',
  },
  {
    id: '58694a0f-3da1-471f-bd96-145571e29234',
    title: 'Seven Item',
  },
  {
    id: '58694a0f-3da1-471f-bd96-145571429234',
    title: 'Eight Item',
  },
  {
    id: '58694a0f-3da1-471f-bd96-115571429234',
    title: 'Nine Item',
  },
  {
    id: '58694a0f-3da1-471f-bd96-1155h1429234',
    title: 'Ten Item',
  },
];

const Item = ({title}) => (
  <Text style={[styles.item, styles.title]}>{title}</Text>
);

const renderItem = ({item}) => <Item title={item.title} />;
const ITEM_HEIGHT = 50;

const renderFlatList = ({item}) => <NestedFlatList item={item} />;

function NestedFlatList(props) {
  let flatlist = useRef(null);
  let bottomY;
  const [previousPosition, setPreviousPosition] = useState(undefined);
  const [height, setHeight] = useState(undefined);
  const [items, setItems] = useState(DATA);
  const [disabled, setDisabled] = useState(false);
  const [index, setIndex] = useState(DATA.length + 1);
  const [resetScrollPosition, setResetScrollPosition] = useState(false);
  React.useEffect(() => {
    if (resetScrollPosition && previousPosition && flatlist) {
      setTimeout(
        function (flatlist, height, previousPosition) {
          flatlist.scrollToOffset({
            offset: height - previousPosition,
            animated: false,
          });
        },
        0,
        flatlist,
        height,
        previousPosition,
      );
      setResetScrollPosition(false);
    }
  }, [resetScrollPosition, previousPosition, height]);
  return (
    <View>
      <Button
        title="append an item"
        onPress={() => {
          setPreviousPosition(bottomY);
          setItems([...items, {title: `new item ${index}`}]);
          setIndex(index + 1);
        }}
      />
      <Button
        title="prepend an item"
        onPress={() => {
          setItems([{title: `new item ${index}`}, ...items]);
          setIndex(index + 1);
        }}
      />
      <Button
        title="remove an item"
        onPress={() => {
          const newItems = [...items];
          newItems.splice(items.length - 1, 1);
          setItems(newItems);
        }}
      />
      <Text>Flatlist</Text>
      <FlatList
        ref={ref => (flatlist = ref)}
        inverted
        style={{height: 400}}
        renderItem={renderItem}
        data={items}
        onScroll={e => {
          console.log('TESTING:: ' + 'onScroll');
          const scrollY = e.nativeEvent.contentOffset.y;
          const height = e.nativeEvent.contentSize.height;
          bottomY = height - scrollY;
        }}
        onScrollToIndexFailed={() => console.log('scrollToIndex failed')}
        onContentSizeChange={(width, height) => {
          console.log('TESTING:: ' + 'onContentSizeChange');
          setHeight(height);
          setResetScrollPosition(true);
        }}
      />
    </View>
  );
}

const FlatList_nested = (): React.Node => {
  return <NestedFlatList />;
};

const styles = StyleSheet.create({
  item: {
    backgroundColor: '#f9c2ff',
    padding: 20,
    marginVertical: 8,
    marginHorizontal: 16,
  },
  title: {
    fontSize: 16,
  },
});

export default ({
  title: 'Inverted',
  name: 'inverted',
  description: 'Test inverted prop on FlatList',
  render: () => <FlatList_nested />,
}: RNTesterModuleExample);
```

</p>
</details>

<details><summary>video of the test case</summary>
<p>

<video src="https://user-images.githubusercontent.com/24992535/179153617-d7ac2333-9e48-499b-939d-005667582cf6.mov" width="1000" />

</p>
</details>

- [x] calculate offset correctly for inverted flastlist (using distance from the bottom instead of top)
```
// onScroll callback we save bottomY variable
const scrollY = e.nativeEvent.contentOffset.y;
const height = e.nativeEvent.contentSize.height;
bottomY = height - scrollY; 
```
- [x] trigger a scroll to that coordinate
- [ ] implement the solution in VirtualizedList
- [ ] add optimization in ReactAndroid

</p>
</details>

**Comment by fabriziobertoglio1987** [comment]
- [x] trigger a scroll to that coordinate
- [x] fix issue no initial scroll sets bottomY value
- [x] test solution with pre-pending items
- [x] implement the solution in VirtualizedList
- [ ] add check isScreenreaderEnabled and Platform Android
- [ ] adapt solution to horizontal flatlist
- [ ] adapt solution to use with initialIndex
- [ ] add a summary to Pull Request explaining the changes
- [ ] add links to relevant tests in the Pull Request summary
- [ ] prepending item - scrolls down to show the new item (use scrollToEnd, but after _contentViewChange is called)
- [ ] review PR and move to READY FOR REVIEW
- [ ] (OPTIONAL) improve solution using _scrollMetrics and existing virtlist APIs
- [ ] (OPTIONAL) add optimization in ReactAndroid to cache onScroll calculation on the native side

**Comment by fabriziobertoglio1987** [comment]
@mallenexpensify 

I quote Eric Rozell https://github.com/facebook/react-native/pull/34141#issuecomment-1180556939

> @fabriziobertoglio1987 In case you're interested, I recently worked on a fix for react-native-windows list inversion. It uses the `flexDirection: "column-reverse"` approach described here: [#30373 (comment)](https://github.com/facebook/react-native/issues/30373#issuecomment-774488236)
> 
> Here is the PR: [microsoft/react-native-windows#8440](https://github.com/microsoft/react-native-windows/pull/8440)
> 
> The PR for Windows also addresses the issues with infinite scroll and virtualization described here: [#30373 (comment)](https://github.com/facebook/react-native/issues/30373#issuecomment-774988315)
> 
> I wrote up a more detailed requirement for the platform requirements and what they map to on Windows here: https://gist.github.com/rozele/47a2ad44f6d44561da1d293454ae8418
> 
> The most important bits are the view and edge anchoring behaviors, i.e., when a new item is prepended to the list, the ScrollView should synchronously scroll it into view (i.e., drawn to view port and scrolled to bottom in same frame), and when items are appended to the end of the list, the view needs to stay in the same position. Windows has specific features to implement these behaviors, but I imagine it's possible to achieve this in Android with something like the maintainVisibleContentPosition API (which there is a WIP draft for Android): #29466

Now that PR *Add fabric support for maintainVisibleContentPosition on Android* #35994 is merged, I can build the above functionalities for the inverted flatlist.

Issues https://github.com/Expensify/App/issues/1341 and https://github.com/Expensify/App/issues/3381 were closed. 
Should I restart working on this issue? Thanks
