### ISSUE TITLE
Switching from Wifi to LTE results in permanent "Network Request Error"

### ISSUE THREAD

**Issue by vijaykumartrd** [facebook/react-native#30370]
## Description
When the app is connected to both Wifi and LTE, switching off the Wifi results in the app going offline.
All subsequent requests return "Network Request Error" even when the device is still connected to the Internet over LTE.
Even though the issue is not consistent, it can be frequently reproduced and is currently hampering our product in production. Hence, any resolution or guidance in the correct direction would be appreciated.

## React Native version:
System:
    OS: Windows 10 10.0.18362
    CPU: (4) x64 Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz
    Memory: 747.63 MB / 5.86 GB
  Binaries:
    Node: 12.18.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.12.3 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6858069
    Visual Studio: 16.6.30204.135 (Visual Studio Community 2019)
  Languages:
    Java: Not Found
    Python: 3.6.3
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.3 => 0.63.3
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

Note: The issue was first noted in App running on version 62.2 across multiple devices with Android OS (7, 10 and 11) and has replicated with the latest version in the sample repo. The specs shared above are from the sample repo (simple_fetch)

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.
1. Enable both Wifi and LTE
2. Run the app
3. Switch off wifi
4. Make a fetch request (Press the ping button in the sample app to make a HEAD request to https://google.com)
5. If cannot replicate, retry steps 1-4
6. If you can replicate the issue, wait for 20-30 seconds to allow the device to connect (in case there is some delay).
7. Continue to retry. The issue will persist.

## Expected Results
A change in network connection from Wifi to LTE should not stop the app from being able to use the internet.

## Sample Repo
We have created multiple samples to test this, including implementations from external libraries. The first repo (simple_fetch) should be enough to replicate the issue.
https://github.com/vijaykumartrd/simple_fetch
https://github.com/vijaykumartrd/simple_offline_manual
https://github.com/vijaykumartrd/simple_offline

Please let me know if any more information is required.

Thanks in advance.

**Comment by bnussman** [comment]
I'm having a similar issue on Android. On android, if user goes fully offline and a fetch is made, any fetch made when back online loads for a long time and does not error out or resolve.

**Comment by dmregister** [comment]
@vijaykumartrd Were you ever able to track down this issue? We are facing something very similar to this when we enable hermes on iOS. 

I would be able to provide a minimal productions with screen recordings showing the issues if that would help in getting the issue more visibility.

**Comment by popejrh19** [comment]
Unsubscribe

William Pope Jr

**Comment by cortinico** [comment]
Closing as stale
