### ISSUE TITLE
RCTRedBox crash

### ISSUE THREAD

**Issue by aksonov** [facebook/react-native#3038]
After some JS runtime error (with red box shown) and fixing JS code and press Cmd+R to refresh, iOS app crashes within simulator. It was OK with React Native 0.10 version
<img width="1043" alt="2015-09-25 5 25 54 pm" src="https://cloud.githubusercontent.com/assets/1321329/10104612/d6c30962-63aa-11e5-9b25-6c44cf20a26e.png">

**Comment by cgarvis** [comment]
I get the same on all my projects now.

**Comment by aksonov** [comment]
Any response? It is really annoying and makes development much slow. I have to use previous version (0.10) to avoid this.

**Comment by jaygarcia** [comment]
This was happening earlier in the life of React Native, it seemed to have gone away and made an appearance again :(

**Comment by aksonov** [comment]
Solved temporarily just by commented that line ([self resignFirstResponder]). I don't understand why staff doesn't respond...

**Comment by browniefed** [comment]
Can you let me know if this is still happening? We're now 12 versions newer.

**Comment by aksonov** [comment]
Seems no, you thanks!
