### ISSUE TITLE
[Android] Text numberOfLines prop clips text smaller than the largest Text child

### ISSUE THREAD

**Issue by john-irby** [facebook/react-native#30389]
## Description
When rendering multiple nested `Text` components inside of a parent with `numberOfLines={1}`, the visible text will be "clipped" based on the size of the largest child `Text` component. e.g.

```
    <View>
      <Text numberOfLines={1}>
        <Text style={{ fontSize: 10 }}>This is the visible text that will be truncated</Text>
        <Text style={{ fontSize: 20 }}>ABC</Text>
        <Text style={{ fontSize: 30 }}>ABC</Text>
        <Text style={{ fontSize: 40 }}>ABC</Text>
      </Text>
    </View>
```

This results in no visible `Text` being rendered on the device. Note that this is only present on Android.

## React Native version:
0.63.2

## Steps To Reproduce
1. Render a `Text` component with `numberOfLines={1}`
2. Render child `Text` components with a fixed `fontSize` to the point that the text is truncated to a single line
3. Render an additional child `Text` component with a larger `fontSize` that is part of the truncated portion of the text
4. Observe that the text is cut off and is not visible

## Expected Results
Text present on the first line (i.e. not truncated by the ellipses) should be visible.

## Snack, code example, screenshot, or link to a repository:
https://snack.expo.io/9e01t4!s9 (see the modified AssetExample.js)

**Comment by fabriziobertoglio1987** [comment]
Do you still experience this issue? 

I have four years of experience maintaining facebook/react-native and I specialize in the Text and TextInput components. I currently have 58 [facebook/react-native PRs](https://github.com/facebook/react-native/pulls?q=is%3Apr+author%3Afabriziobertoglio1987+). 

If you still experience this issue, I will prepare a patched release with the fix.

Thanks a lot
