### ISSUE TITLE
Error: Text strings must be rendered within a component.

### ISSUE THREAD

**Issue by rajAmukhliS** [facebook/react-native#30386]
Error: Text strings must be rendered within a component.

This error is located at:
    in EnsureSingleNavigator (at BaseNavigationContainer.tsx:407)
    in ForwardRef(BaseNavigationContainer) (at NavigationContainer.tsx:91)
    in ThemeProvider (at NavigationContainer.tsx:90)
    in ForwardRef(NavigationContainer) (at App.js:54)
    in App (at renderApplication.js:45)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:106)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:132)
    in AppContainer (at renderApplication.js:39)
[Fri Nov 13 2020 11:30:09.503]  ERROR    Error: Text strings must be rendered within a component.

This error is located at:
    in EnsureSingleNavigator (at BaseNavigationContainer.tsx:407)
    in ForwardRef(BaseNavigationContainer) (at NavigationContainer.tsx:91)
    in ThemeProvider (at NavigationContainer.tsx:90)
    in ForwardRef(NavigationContainer) (at App.js:54)
    in App (at renderApplication.js:45)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:106)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:132)
    in AppContainer (at renderApplication.js:39)
[Fri Nov 13 2020 11:30:09.504]  ERROR    Error: Text strings must be rendered within a component.

This error is located at:
    in EnsureSingleNavigator (at BaseNavigationContainer.tsx:407)
    in ForwardRef(BaseNavigationContainer) (at NavigationContainer.tsx:91)
    in ThemeProvider (at NavigationContainer.tsx:90)
    in ForwardRef(NavigationContainer) (at App.js:54)
    in App (at renderApplication.js:45)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:106)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:132)
    in AppContainer (at renderApplication.js:39)
[Fri Nov 13 2020 11:30:19.383]  BUNDLE  ./index.js

[Fri Nov 13 2020 11:30:24.222]  LOG      Running "stacklerning" with {"rootTag":111}
[Fri Nov 13 2020 11:30:24.225]  ERROR    Error: Text strings must be rendered within a <Text> component.       

This error is located at:
    in EnsureSingleNavigator (at BaseNavigationContainer.tsx:407)
    in ForwardRef(BaseNavigationContainer) (at NavigationContainer.tsx:91)
    in ThemeProvider (at NavigationContainer.tsx:90)
    in ForwardRef(NavigationContainer) (at App.js:54)
    in App (at renderApplication.js:45)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:106)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:132)
    in AppContainer (at renderApplication.js:39)
[Fri Nov 13 2020 11:30:24.226]  ERROR    Error: Text strings must be rendered within a <Text> component.       

This error is located at:
    in EnsureSingleNavigator (at BaseNavigationContainer.tsx:407)
    in ForwardRef(BaseNavigationContainer) (at NavigationContainer.tsx:91)
    in ThemeProvider (at NavigationContainer.tsx:90)
    in ForwardRef(NavigationContainer) (at App.js:54)
    in App (at renderApplication.js:45)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:106)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:132)
    in AppContainer (at renderApplication.js:39)
[Fri Nov 13 2020 11:30:24.228]  ERROR    Error: Text strings must be rendered within a <Text> component.       

This error is located at:
    in EnsureSingleNavigator (at BaseNavigationContainer.tsx:407)
    in ForwardRef(BaseNavigationContainer) (at NavigationContainer.tsx:91)
    in ThemeProvider (at NavigationContainer.tsx:90)
    in ForwardRef(NavigationContainer) (at App.js:54)
    in App (at renderApplication.js:45)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:106)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:132)
    in AppContainer (at renderApplication.js:39)

**Comment by shockdesign** [comment]
@rajAmukhliS 

Have a look at where you're printing your text strings and make sure they consist of text and not a null or undefined?
