### ISSUE TITLE
[HELP] Error: Failed to install the app.

### ISSUE THREAD

**Issue by sleaper** [facebook/react-native#30388]
When I write"react-native run-android", I have an error

## Description
![image](https://user-images.githubusercontent.com/19505081/99079182-deb02880-25bf-11eb-96fa-3945e1c99884.png)

## React Native version:
info Fetching system and libraries information...
(node:10788) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
System:
    OS: Windows 10 10.0.17763
    CPU: (16) x64 AMD Ryzen 7 2700X Eight-Core Processor
    Memory: 8.67 GB / 15.95 GB
  Binaries:
    Node: 15.1.0 - E:\Program Files (x86)\node\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.8 - E:\Program Files (x86)\node\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 29.0.2, 30.0.0, 30.0.2
      System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
    Windows SDK:
      AllowAllTrustedApps: Enabled
      AllowDevelopmentWithoutDevLicense: Enabled
      Versions: 10.0.17763.0, 10.0.18362.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.7.30523.141 (Visual Studio Community 2019)
  Languages:
    Java: 1.8.0_272 - C:\Program Files\OpenJDK\openjdk-8u272-b10\bin\javac.EXE
    Python: 3.8.5 - C:\Python38\python.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.3 => 0.63.3
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Expected Results
React-native app shoud start with android emulator

**Comment by yonureker** [comment]
Did you follow the instructions [here](https://reactnative.dev/docs/environment-setup) for Windows / Android and setup the development environment?

**Comment by BenJeau** [comment]
It may be related to the fact that you have non ASCII characters in your path, https://stackoverflow.com/questions/46145053/react-native-run-android-in-emulator-throws-erro?

**Comment by sleaper** [comment]
Proble was in the wrong path to ^Error: Cannot find module 'D:\programovÃ¡nÃ\react\mobileApp\node_modules\react-native\node_modules\@react-native-community\cli\build\bin.js'. I just had to reinstall @react-native-community with `npm i @react-native-community/cli`
