### ISSUE TITLE
Using initialScrollIndex with Flatlist will cause missing items with react native web.

### ISSUE THREAD

**Issue by divonelnc** [facebook/react-native#30387]
## Description
When using `initialScrollIndex` with react native web, the first few items in the dataset will not get rendered. It is impossible to see these items, even by scrolling back up.

## React Native version:
react-native: https://github.com/expo/react-native/archive/sdk-39.0.0.tar.gz => 0.63.2

## Steps To Reproduce
1. Create a Flalist with more than 20 items
2. Set the `initialScrollIndex` value to something above 0
3. The first items are not getting rendered

## Expected Results
You should be able to scroll back to the first items in the dataset.

## Snack, code example, screenshot, or link to a repository:
https://snack.expo.io/@divone/initialscrollindex-does-not-show-all-items

**Comment by divonelnc** [comment]
Any chance that this issue can get looked at? It is really easy to repro and makes `initialScrollIndex` unusable.

**Comment by jdlk07** [comment]
Hey, not sure if this will be of any help but I was having the same issue with an expo managed react-native app after upgrading from React Navigation 5.X to 6.X. 

The `initialScrollIndex` was working fine but after upgrading React Navigation to 6.X, setting the `initialScrollIndex` would cause the list items above the set scrollIndex to be blank.

I downgraded to 5.X and everything was working fine again.

**Comment by mihaibulic2** [comment]
Can we reopen this — this is still an issue
