### ISSUE TITLE
TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by nurmohammed840** [facebook/react-native#30382]
Got this message.

## Description
I just creact fresh new project.Build it then got this error.I dont even touch a single line of code 

## React Native version:
System:
    OS: Windows 10 10.0.20201
    CPU: (2) x64 Intel(R) Celeron(R) N4000 CPU @ 1.10GHz
    Memory: 1021.89 MB / 3.83 GB
  Binaries:
    Node: 14.8.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6308749
  Languages:
    Java: 11.0.6
    Python: 2.7.17
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.3 => 0.63.3
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. npx react-native init Info
2. cd Info
3. npx react-native run-android
4. npx react-native start 

## Expected Results
Welcome page 

## Got
```
error: TypeError: Cannot read property 'map' of undefined
    at resolveDependencies (e:\Info\node_modules\metro\src\DeltaBundler\traverseDependencies.js:431:18)
    at e:\Info\node_modules\metro\src\DeltaBundler\traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (e:\Info\node_modules\metro\src\DeltaBundler\traverseDependencies.js:87:24)
    at _next (e:\Info\node_modules\metro\src\DeltaBundler\traverseDependencies.js:107:9)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[Fri Nov 13 2020 05:20:14.913]  BUNDLE  ./index.js
```

**Comment by yonureker** [comment]
Take a look here #23356, error looks similar.

**Comment by nurmohammed840** [comment]
Thanks my issue resolved by cleaning `C:\Users\<YourName>\AppData\Local\Temp`.
