### ISSUE TITLE
How to get distance from camera to object in React Native?

### ISSUE THREAD

**Issue by HarryBuiDev** [facebook/react-native#30398]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
I'd love to get the distance from the camera to the object in React Native.
I dug several packages but cannot find the answer.
Please help!

**Comment by HideoDev** [comment]
Hey @dulmandakh 
What's the solution?
Why did you close the issue?

**Comment by dulmandakh** [comment]
@HideoDev Sorry, this issue tracker is for tracking RN issues not for developer support. I closed this because RN doesn't have camera feature. So I would like to recommend you to search for third party modules, please see https://reactnative.directory.
