### ISSUE TITLE
FlatList always resetting scroll position when there's onLayout on the other components

### ISSUE THREAD

**Issue by justinushermawan** [facebook/react-native#30391]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
I have a Screen that consists of buttons and one `FlatList` below them. The buttons have `onLayout()` listener to measure their `borderRadius` which has a dynamic value depends on their widths.
But, apparently this `onLayout` listener affecting `FlatList`'s scroll state that causes it resetting the scroll position every time I do the scrolling.

## React Native version:
0.63.3

## Expected Results
The `FlatList` keeps its latest scroll position.

## Snack, code example, screenshot, or link to a repository:
```
const [buttonFilterStyle, setButtonFilterStyle] = useState({});
const buttonFilterOnLayout = (event) => {
  const {width} = event.nativeEvent.layout;
  const style = {borderRadius: width / 2};
  setButtonFilterStyle(style);
};
const TabScene = () => (
  <View style={{flex: 1, paddingHorizontal: 12, paddingTop: 12}}>
    <View style={{flexDirection: 'row', paddingVertical: 12}}>
      <Button
        onLayout={buttonFilterOnLayout}
        mode="contained"
        style={[
          styles.buttonFilter,
          styles.buttonFilterActive,
          buttonFilterStyle,
          {marginRight: 8},
        ]}
        contentStyle={{padding: 10}}
        labelStyle={[styles.buttonFilterLabel, {color: colors.primary}]}
        uppercase={false}>
        Belum Terbayar
      </Button>
    </View>
    <FlatList
      showsVerticalScrollIndicator={false}
      data={dummyData}
      renderItem={renderItem}
      keyExtractor={(item, index) => `${index}`}
    />
  </View>
);
```

**Comment by camuenho123** [comment]
Em sáb, 14 de nov de 2020 15:37, Justinus Hermawan <notifications@github.com>
escreveu:
