### ISSUE TITLE
this.setState not being batched inside a synthetic event on Web build, but works fine on the android.

### ISSUE THREAD

**Issue by blackstormx** [facebook/react-native#30392]
## Description
setState is not being batched inside a synthetic event on the Web build, but works fine on the android.

Example:

```
<View style={main.drawButton}>
                    <Pressable
                        onPressIn={(e) => {
                            //comment 2 lines below and uncomment 3rd line to see the difference(Which should not exist)
                            this.setBackgroundColor($gray900);
                            this.setButtonColor($gray100);
                            // this.setColors($gray100, $gray900);
                        }}
```

```
    setButtonColor = (newColor) => {
        this.setState({ buttonColor: newColor });
    };
    setBackgroundColor = (newColor) => {
        this.setState({ backgroundColor: newColor });
    };
```

[Example on snack, latest version everything](https://snack.expo.io/FzOO2eLK!)

![image](https://user-images.githubusercontent.com/22796372/99171376-ee478280-2721-11eb-885a-0205e420d211.png)

## Expected Results
Should behave same on both platforms. setState should be batched into a single call.

Environment:
1. Probably doesn't matter, since it doesn't work even on snack.

```
  "dependencies": {
    "expo": "~39.0.2",
    "expo-status-bar": "~1.0.2",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-39.0.4.tar.gz",
```

Windows10, google chrome latest

**Comment by dulmandakh** [comment]
Sorry, this issue tracker is only for RN, not web. Please file the issue to Expo.

**Comment by blackstormx** [comment]
@dulmandakh 

Web build is part of React-native.

I used react native to build my app on web.

Its react-native error, this can't be Expo's problem. Expo doesn't decide how state will be batched.

**Comment by dulmandakh** [comment]
Currently, React Native core supports only Android and iOS. But there are other project that add web, windows, Mac and other platform supports.
