### ISSUE TITLE
Could not connect to development server. Ensure node server is running

### ISSUE THREAD

**Issue by lealife** [facebook/react-native#304]
I run the 2048 example on Xcode and run the IOS simulator, an error occurs:
![image](https://cloud.githubusercontent.com/assets/1699428/6861597/bfe7f458-d473-11e4-97fb-145835c011e6.png)

**Comment by amasad** [comment]
Did you try running `npm start` from react-native directory?

**Comment by tehfailsafe** [comment]
I get this error as well when I try to run on real ios device through xcode. Is that expected?

**Comment by tjwudi** [comment]
Run `npm start` on local machine to start the development server. React Native relies on a development server to communicate with the app running in the simulator.

**Comment by lealife** [comment]
Ok, I will try it, I see the AppDelegate.m :
```
 // Loading JavaScript code - uncomment the one you want.

  // OPTION 1
  // Load from development server. Start the server from the repository root:
  //
  // $ npm start
  //
  // To run on device, change `localhost` to the IP address of your computer, and make sure your computer and
  // iOS device are on the same Wi-Fi network.
```
Maybe you should write in a wiki. It's easy to freshman.

**Comment by jaichandra** [comment]
I see this error even after running 'npm start'. Do I need to make any changes to AppDelegate.m file?

**Comment by jaichandra** [comment]
OK. fixed the issue. I had to change the port from 8081 to 8881 as the default port is used by another process on my mac. Modifying AppDelegate.m to point to the new port worked.

```
  // OPTION 1
  // Load from development server. Start the server from the repository root:
  //
  // $ npm start
  //
  // To run on device, change `localhost` to the IP address of your computer, and make sure your computer and
  // iOS device are on the same Wi-Fi network.
  jsCodeLocation = [NSURL URLWithString:@"http://localhost:8881/index.ios.bundle"];
```

**Comment by ikallen** [comment]
where is react-native directory?

**Comment by brownieboy** [comment]
@ikallen 

The "react-native directory" refers to the folder where your own source-code is located.

**Comment by wongzigii** [comment]
I think `react-native root` within the  error could be more clear which just as @brownieboy  said, refers to the folder where the source code located.

**Comment by MilanPalSingh** [comment]
It worked for me -> open the APP folder in the terminal and running "react-native start". Here you can also check on which port it is running and set the same.

**Comment by jamesfzhang** [comment]
I can load this URL just fine in my browser: http://localhost:8081/index.ios.bundle?platform=ios&dev=true but I still get this error.

<img width="904" alt="screen shot 2015-12-08 at 5 22 32 pm" src="https://cloud.githubusercontent.com/assets/2057670/11673771/4b9a39ea-9dd0-11e5-88a6-13ad4bf29a85.png">

**Comment by jamesfzhang** [comment]
In iOS 9.0+ Apple by default blocks non secure (https) requests. I had to add this to my Info.plist 
<img width="488" alt="screen shot 2015-12-08 at 6 32 20 pm" src="https://cloud.githubusercontent.com/assets/2057670/11674908/0bb684c8-9dda-11e5-8655-5ab694b959e9.png">

**Comment by adamsythe** [comment]
James I have the same issue as you, I dont understund, how do you add that to plist?  Is plist not a text file?

**Comment by adamsythe** [comment]
jamesfzhang I am having the same error as you, 

Currently that part of my plist looks as follows 

<key>NSAppTransportSecurity</key>
  <dict>

    
    <key>NSAllowsArbitraryLoads</key>
    <true/>
  </dict>

I tried changing it to

<key>NSAppTransportSecurity</key>
  <dict>
	<key>NSExceptionDomains</key>
	  <dict>
	    <key>localhost</key>
	    <dict>
	      
	      <key>NSIncludesSubdomains</key>
	      <true/>
	      
	      <key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
	      <true/>
	      
	    </dict>
	  </dict>
  </dict>


But I am still getting the same error.  Any ideas?

**Comment by adamsythe** [comment]
I also tried this but the error survived yet again

<key>NSAppTransportSecurity</key>
  <dict>
    
    <key>NSAllowsArbitraryLoads</key>
    <true/>
  </dict>
  <key>NSAppTransportSecuritySetting</key>
  	<dict>
  		<key>NSExceptionDomains</key>
  			<dict>
    			<key>localhost</key>
    				<dict>
    					<key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
     						<true/>
     				</dict>
     		</dict>
     </dict>

**Comment by adamsythe** [comment]
Jamesfzhang I am having the same error as you, what is the full name of the boolean you added at the end?  

And does the app transport security settings dictionary live in the information list dictionary?

Thanks

**Comment by jamesfzhang** [comment]
@adamsythe The boolean is `YES`, and yes this is in the information list dictionary.

```xml
```

**Comment by adamsythe** [comment]
Thanks my error disappeared when I updated my operating system :)

**Comment by Kim-Andersen** [comment]
I can also load the dev server resource in my browser, and also updated my info.plist as jamesfzhang suggested. But I'm still getting the red screen connection error message.

Now I tried to to access the dev server resource (http://[my ip]:8081/index.ios.bundle?platform=ios&dev=true ) through a browser on my device, and that page doesn't load. I'm sure my workstation and device is on the same network. Could this be a closed port issue?

**Comment by Pungsnigel** [comment]
Getting the exact same error. No problem loading from browser, can't fetch from simulator. tried @jamesfzhang solution, but still having same error. Anyone found a solution?

**Comment by Kim-Andersen** [comment]
I had to change the address of the dev server in the following file as well:

Libraries/RTCWebSocket.xcodeproj/RTCWebSocketExecutor.m

Pungsnigel, can you load the dev server resource from a browser in your device?

**Comment by futurefeeling** [comment]
I fixed this with using `npm start` in my project directory

**Comment by jamesfzhang** [comment]
Have you tried adding your IP to list of `NSExceptionDomains`?

**Comment by tkfeng** [comment]
@jamesfzhang Following your instruction, I was finally able to resolve the "Could not connect to development server" issue on the simulator.  Thanks!

**Comment by jamesfzhang** [comment]
@tkfeng Great, no problem!

**Comment by phoenixbox** [comment]
I had two problems, solutions below:

1: Could not Connect to development Server
2: Could not start server due to missing dependencies

#### Problem 1: 
`Could not Connect to development Server`
#### Solution 
Adding this to your xcode project plist.
```
<key>NSAppTransportSecurity</key>
    <dict>
        <key>NSExceptionDomains</key>
        <dict>
            <key>localhost</key>
            <dict>
                <key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
                <true/>
            </dict>
        </dict>
    </dict>
```

#### Problem 2: 
`Could not start server due to missing dependencies`
#### Solution 
For some reason `npm install` was not installing the submodule dependencies for the react native package. So I ran npm install from the root of the `react-native` package which was inside my `node_modules` dir

```
$ cd node_modules/react-native
$ npm install
```

Then when running `npm start` from the root of my new react native project directory I got the following output:

```
===============================================================
 |  Running packager on port 8081.
 |  Keep this packager running while developing on any JS
 |  projects. Feel free to close this tab and run your own
 |  packager instance if you prefer.
 |
 |     https://github.com/facebook/react-native
 |
 ===============================================================

Looking for JS files in
   /Users/user/Dev/examples/react-native/new-react-project


React packager ready.
```

Note: make sure the the port from this line:
`Running packager on port 8081.`
matches the port referenced in your app delegate
`jsCodeLocation = [NSURL URLWithString:@"http://localhost:8081/index.ios.bundle"];`

**Comment by ghamaide** [comment]
@jamesfzhang I added localhost to my list of exceptions and it runs well on the simulator. I also added my local IP address 192.168.XXX.XXX but I can't get it to work on my device. Any thoughts ?

**Comment by liyang1988** [comment]
I also had this problem ,but I had more question ,
![2016-01-19 11 11 42](https://cloud.githubusercontent.com/assets/12080346/12422497/365316e4-bf02-11e5-92c7-49739cd0c971.png)
anyone can help me?

**Comment by tdugger** [comment]
I also had this problem (where I could access the URL from the browser on the device fine, but the app could not).  I tried adding the solution 1 mentioned in @phoenixbox (originally suggested by @jamesfzhang) but that didn't work.  Then I instead of using localhost as jamesfzhang suggested, I engered my IP address and put my IP in the jsCodeLocation line in AppDelegate.m and then it worked.

**Comment by ghamaide** [comment]
Upgrading to RN 0.18 fixed this for me...

**Comment by jcsjohnson** [comment]
I am getting this error on only one of my projects. I loaded the project on to my phone yesterday and today I am getting the error for only this one project. My other projects do not get this error. The odd thing is that the power went out last night and my computer restarted while the project in question was running. Has anyone heard of anything like this happening?

React-native - 0.21.0
NPM 3.8.0

I've checked my info.plist and it is accurate and same as my other projects. It was working fine from last night and nothing changed from then until when I tried today..... so confusing.

![simulator screen shot 11 mar 2016 7 18 23 pm](https://cloud.githubusercontent.com/assets/16730553/13699073/c9cf72de-e7c3-11e5-8283-e99268a1076e.png)

**Comment by fakefish** [comment]
@jcsjohnson so am I !!

**Comment by jcsjohnson** [comment]
@fakefish are you running on iPhone or simulator?

**Comment by fakefish** [comment]
@jcsjohnson on simulator

**Comment by jcsjohnson** [comment]
@fakefish pressuming you have used iPhone at some point then the fix may have to do with the port you have set in appDelegate.m file. For me for some reason when the power went out the port changed.

**Comment by sritharIOS** [comment]
I had run npm start command on the example directory.
Then enabled App Transport Security in info.plist.

**Comment by imarco** [comment]
Just shut your firewall or add an exception rule for tcp port 8080 (which is the default port setting in `./server/server.js`) or for your terminal app.

My problem solved, you can just have a try.

**Comment by dropfen** [comment]
If somebody else is running into this issue on a *device*, there are two places where you have to replace `localhost` with the IP packager is running on

1. in the ios/<project_name>/AppDelegate.m (which is documented)
AND
2. in ios/<project_name>/Libraries/WebSocket/RCTWebSocketExecutor.m#L54 

The error massage sucks, because its saying that 192.168.XX.XX is not reachable, but it is actually requesting `localhost` for some debugger stuff

connect with #883

**Comment by PhillippOhlandt** [comment]
Hey,

I have the same problem when using the emulator. Tried everything from this thread but still getting the stupid error.

**Comment by PhillippOhlandt** [comment]
I got it!

For everyone else, here is what I did:

Instead of allowing my specific IP address, I disabled the NSAppTransportSecurity feature.

```
<key>NSAppTransportSecurity</key>
<dict>
        <key>NSAllowsArbitraryLoads</key>
        <true/>
</dict>
```

**Comment by dropfen** [comment]
Thanks @PhillippOhlandt now I am able to test on simulator and device at the same time!

**Comment by rickycpadilla** [comment]
@PhillippOhlandt I am new to xcode, where should I put that code? Thanks!

**Comment by mombi93** [comment]
@rickycpadilla you put that in your_project_name/ios/your_project_name/info.plist. I also got this problem, but what I did  to solve the issue were run `npm start` on root directory of my project and then run `react-native run-ios` on a separate tab.

**Comment by robert-spurrier** [comment]
I had the same error as @jcsjohnson, and unfortunately none of the suggestions in this thread did anything for me. I completely wiped my machine's npm/node installation and every module folder I could find. After I reinstalled the necessary react-native dependencies, the skeleton app booted up in the iOS simulator with no other modifications necessary.
 
OSX 10.11.2
Xcode 7.3.1
npm 2.14.12
node v4.3.0

**Comment by PepperYan** [comment]
Same problem here, um, I've checked every solutions mentioned before, but none of them work for me. What I have done is init a project with react-native and react-native run-ios, that's all! I've already upgraded my node from 5.6.0 to 6.2.2. Have any other solutions?

OSX 10.11.1
Xcode 7.3.1
npm v3.9.5
node v6.2.2

**Comment by PepperYan** [comment]
@robert-spurrier seemed to be the same problem to yours

**Comment by PepperYan** [comment]
@robert-spurrier everything works fine after I update my system to 10.11.5

**Comment by dvabolta** [comment]
"Could not connect to development server", Android, 4.2.2
Server is running, http://localhost:8081/index.android.bundle?platform=android returns a bundle, a device (not an emulator) is online and is visible for my computer when I type in command line "adb devices".

Have the solutions?

**Comment by dvabolta** [comment]
At this time I found the solution here: http://stackoverflow.com/a/37188827/5149064
**ngrok** allows to run an application, but still I have not found the normal solution. The question is still opened.

**Comment by Surreal9** [comment]
After having success launching my AwesomeProject in the simulator, it was annoying seeing this red error when trying to launch on iPad. I tried adding my MBP's IP to the info.plist under NSExceptionDomains however had no success. The only thing that appears to work for me is https://github.com/facebook/react-native/issues/304#issuecomment-222639207

**Comment by dvabolta** [comment]
What is an analogue for ```NSAppTransportSecurity``` on Windows? How I can disable such security on it?

**Comment by mschipperheyn** [comment]
I try to connect to my local developer server: www.dev.ology.com.br which is linked to localhost through a hosts file, and fail: "The resource could not be loaded because the App Transport Security policy requires the use of a secure connection."

<img width="602" alt="screen shot 2016-08-04 at 14 05 58" src="https://cloud.githubusercontent.com/assets/384959/17411003/9f6b3e78-5a4c-11e6-977b-29c29016dc2d.png">

**Comment by afeiship** [comment]
Check your hosts file:
127.0.0.1 localhost

**Comment by jvvinoth** [comment]
I fixed this with using npm start in my project directory

**Comment by fud** [comment]
Is anyone getting this again with Xcode 8.0 + iOS 10.0? I've modified RTWebsocketExecutor.m with something like,

```
- (void)setUp
{
  if (!_url) {
    NSUserDefaults *standardDefaults = [NSUserDefaults standardUserDefaults];
    NSInteger port = [standardDefaults integerForKey:@"websocket-executor-port"] ?: 8081;
    NSString *host = [[_bridge bundleURL] host];
    
#if TARGET_IPHONE_SIMULATOR
    host = @"localhost";
#else
    host = @"10.0.0.29";
#endif

    NSLog(@"Setting host to: %@", host);
    NSString *URLString = [NSString stringWithFormat:@"http://%@:%zd/debugger-proxy?role=client", host, port];
    _url = [RCTConvert NSURL:URLString];
    
    NSLog(@"url is %@", _url);
  }
```

I've also set exceptions in my Info.plist

```
  <key>NSAppTransportSecurity</key>
        <dict>
                <key>NSAllowsArbitraryLoads</key>
                <true/>
                <key>NSExceptionDomains</key>
                <dict>
                        <key>10.0.0.29</key>
                        <dict>
                                <key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
                                <true/>
                        </dict>
                        <key>10.0.0.60</key>
                        <dict>
                                <key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
                                <true/>
                        </dict>
                        <key>localhost</key>
                        <dict>
                                <key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
                                <true/>
                        </dict>
                </dict>
        </dict>
```

But on my phone I *never* hit my package server. I know it responds at that ip:port as I can hit my machine in a chrome browser on the phone and it responds and I can see that it hits in the log on the package server.

**Comment by dazziola** [comment]
Thank you so much @PhillippOhlandt! Why I need to do this on one computer and not the other baffles me, but it works!

**Comment by PhillippOhlandt** [comment]
@dazziola yeah, after some time, it worked even without that.

**Comment by fud** [comment]
Putting this here for others. 

If you're debugging on a physical phone and trying to connect to the local network the xip.io domain *must* be DNS resolvable. Turns out my modem, a Fritzbox, blocks such DNS lookups for local domain ip addresses and I had to add an exception in my modem settings. Now I can reach my dev server on my laptop.

To test if you have such a problem - dig <your wifi ip>.xio.ip if it time's out you have an issue.

More information in this script, https://github.com/facebook/react-native/blob/master/packager/react-native-xcode.sh#L83

Also if you're running on a phone, you'll see in that script that NSTemporaryExceptionAllowsInsecureHTTPLoads are added for your test domain also - so you don't need to manually add them.

**Comment by Hkmu** [comment]
check your `hosts` file if it lost a line `127.0.0.1   localhost`

**Comment by JamesTheHacker** [comment]
I have had this problem all day using the simulator. Can not find a solution. I've tried every recommendation in this thread and it's still happening. I've even checked out what's going on with Wireshark and I'm stumped!

I can navigate in the browser, but the simulator can't connect. The host, and port are the same. I've modified AppDelegate with the correct information. I've modified the plist file. No firewall.

Absolutely stumped here.

**Comment by JamesTheHacker** [comment]
Fixed. In `AppDelegate.m` find:

    jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index.ios" fallbackResource:nil];

And replace with:

    jsCodeLocation = [NSURL URLWithString:@"http://127.0.0.1:8006/index.ios.bundle"];

Note the `127.0.0.1` instead of `localhost`.

I'm not sure if this is the correct way to do this, but it's the only way to solve my issue. No idea why because the locahost issue is a bug from an older XCode, but I'm using 8.0.

**Comment by kadzier** [comment]
Getting same error as @jamesfzhang on the simulator too; RN 0.39 and Xcode 8.1.  Tried everything here but nothing seems to be working.  The packager is running but when I try to start the app through Xcode or react-native run-ios I still end up with the error.  @JamesTheHacker I tried your method with both port 8081 (my default) and 8006 but not working either.  Been stuck on this all day; any other options?

**Comment by JamesTheHacker** [comment]
@kadzier did you change `localhost` to `127.0.0.1` in `AppDelegate.m`. That's what fixed it for me.

**Comment by kadzier** [comment]
@JamesTheHacker no dice.  Still got the exact same error.  Ended up completely uninstalling the react native cli and watchman, as well as also uninstalling npm AND node, deleting the references everywhere I could find them as per http://stackoverflow.com/questions/11177954/how-do-i-completely-uninstall-node-js-and-reinstall-from-beginning-mac-os-x  and completely starting over from the beginning.  After reinstalling everything fresh that seems to have fixed the problem as I'm no longer getting this issue.   I cannot even fathom what was going wrong but my guess was some sort of weird unintended dependency I created was messing things up.

**Comment by toanfet** [comment]
@dvabolta How to you fix isssue by ngrok? Could you please guide me step by step?

**Comment by flybayer** [comment]
@toanfet I just got dev bundles loading over ngrok at a coffee shop by temporarily modifying this line in `AppDelegate.m` like so:
```objc
  //jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index.ios" fallbackResource:nil];
  jsCodeLocation = [NSURL URLWithString:@"https://4af8888.ngrok.io/index.ios.bundle"];
```

**Comment by yunmenggyy** [comment]
thanks everyone

**Comment by Kaberi-Basu** [comment]
@lealife your solution saved me from night stay at office 💃 . Thankx a lot.
It worked for me after hours of unsuccessful attempts.

**Comment by PARAGJYOTI** [comment]
Here's the simple command 
go tho the directory     ~/android/sdk/platform-tools and run 
     adb reverse tcp:8081 tcp:8081

**Comment by lenhathuy** [comment]
@PhillippOhlandt
Could not connect to development server ! Tried everything from this thread but still getting the stupid error. Can you help me solved my problem?

**Comment by shanshah-ali** [comment]
Thank

**Comment by bighitbiker3** [comment]
I got this error when trying to run on my device.  Fought it for 6+ hours and tried EVERYTHING.  Turns out the wifi on my phone was off.  Feel like a _huge_ idiot but MAKE SURE YOUR WIFI IS ON ON YOUR DEVICE!!

**Comment by rajathithan** [comment]
This can be resolved by the dev settings inside the android emulator , please visit my site for more information,

http://gadoth.com/react-native-series-post-1-installation-setup/

**Comment by mohammed1955** [comment]
@bighitbiker3 
in **AppDelegate.m** file find this code line:

> jsCodeLocation = [NSURL URLWithString:@"http://**localhost**:8081/index.ios.bundle?platform=ios&dev=true"];

change the **localhost ** to your ip address ,if you have mac run Network Utility App and find your IP Address .
Be Sure your Computer And Device Use same Network .

**Comment by berkansahin** [comment]
Device is not connect to 8081 port server.  

How can be fix ?

![screen shot 2017-10-15 at 01 07 12](https://user-images.githubusercontent.com/4026967/31579744-5c3f3b76-b145-11e7-8dd3-aab7364d9782.png)

**Comment by PARAGJYOTI** [comment]
Go to android/sdk/platform-tools and try running
adb reverse tcp:8081 tcp:8081 . If it works , set your platform-tools directory in environment variables so that you can run adb command from anywhere.

**Comment by Pranit-Harekar** [comment]
If you are trying to run on a device, then change the URL from `localhost` to your computer's IP address, like this `http://xxx.xxx.xxx.xxx:8081/index.bundle?platform=ios`.
On mac find IP by running command `ifconfig | grep "inet " | grep -v 127.0.0.1` or find manually in network preferences. Hope that helps!

**Comment by ramsunvtech** [comment]
We faced this issue, In order to fix this, solution is dead simple is below.

 1. Cancel the current process of“react-native run-android” by CTRL + C
    or CMD + C
 2. Close metro bundler window command line which opened
    automatically.
 3. Run the command again, “react-native run-android”.

> Basically this error tells that your current build got failed due to reasons like Code issue or dependency issue.

[Click here for more details][1]


  [1]: https://medium.com/error-healer/react-native-could-not-connect-to-development-server-2b39c7f15ddc

**Comment by Young-Je** [comment]
yes, you should change 127.0.0.1 to your real computer ip like 192.168.1.121. this will work as a magic on your real device, 127.0.0.1 works on your simulator only.

**Comment by Arshiamidos** [comment]
it depends on some point
1- kill terminal and simulator and `react-native run-ios` again
**if error again**  
2- 
![screen shot - - at](https://user-images.githubusercontent.com/6451804/37228660-9725a24c-23f6-11e8-9b3c-385c9e04f1e8.png)
if error like that just check out `app.json` may be you mistakly copy your source code and forgot to change name ,display name instade app.json and it show this error 
**if error show again**  
3-may be your reacyt native confused !!! BTW  download [this packages](https://pan.baidu.com/s/1geLl5tT)  remove  `rm -rf ~/.rncache`  and unzip to ~/.rncache
**if error again :|**
4-some times is i face restart my computer works :) because if your computer runs day after days this may RN make  dumb to process
**if error exist**
5- create new project , npm install all pakckages ,relink all dependecies , copy source code be ware off app.json
