### ISSUE TITLE
JavaOnlyMap and ReadableNativeMap harmonization about key presence

### ISSUE THREAD

**Issue by MichaelBorde** [facebook/react-native#30409]
`JavaOnlyMap` implementation behaves differently than `ReadableNativeMap` implementation about key presence.

## Description
If you try to get a missing key in a `ReadableNativeMap`, It throws a `NoSuchKeyException` whereas It just returns `null` for `JavaOnlyMap` implementation.

Though my code is tested when I convert data sent over bridge, I came accross a bug on a real device.

I know I made a false assumption about key presence and there is a method to check if map includes a key but I felt confident because of my unit tests.

I think `JavaOnlyMap` implementation should throw a `NoSuchKeyException` if key is missing when trying to get a value.

## React Native version:
`0.63.3` but not specific to this version.

**Comment by dulmandakh** [comment]
This is fixed in https://github.com/facebook/react-native/commit/1015194ba1a81eab99000d589914100e4b9ea037, and will be releases in 0.63.4 and 0.64. Thanks
