### ISSUE TITLE
FlatList re-creates child items when numColumns > 1

### ISSUE THREAD

**Issue by asymptotik** [facebook/react-native#30407]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description

When adding items to a FlatList where numColumns > 1 I see behavior where existing list items are unmounted and replaced by new ones. This was discovered when trying to animate (fade in) new list items to a FlatList with 2 columns. 

This was first reported and closed due to not being verified in the latest version here: https://github.com/facebook/react-native/issues/23066

## React Native version:
System:
    OS: macOS 10.15.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 1.33 GB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.14.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.7 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /Users/rick/.rvm/gems/ruby-2.6.5/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.1, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 26, 27, 28, 29, 30
      Build Tools: 27.0.3, 28.0.3, 29.0.2
      System Images: android-23 | Google APIs Intel x86 Atom_64, android-24 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom_64, android-26 | Google APIs Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-30 | Google Play Intel x86 Atom
      Android NDK: 21.3.6528147
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6858069
    Xcode: 12.1/12A7403 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_241 - /Library/Java/JavaVirtualMachines/jdk1.8.0_241.jdk/Contents/Home/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce

In the snack given below we have a FlatList with numColumns > 1 and a button to add list items. Notice that when data is added for a component list item, and it's positions is to be in the second column, the component item in the first column is unmounted and destroyed and a new item is created and mounted.

## Expected Results
I expect, that when I add new data to a FlatList, and there is previous data that has not changed (data or key), those Component items that existed before the data is updated, remain mounted. This appears to work as expected when numColumns is not set, or set to 1.

## Snack, code example, screenshot, or link to a repository:

https://snack.expo.io/@asymptotik/flatlist-enthusiastic-item-construction

**Comment by webtaculars** [comment]
This issue has been reported multiple times(#23066, #25548, #19426) but have been closed everytime without a solution. I hope this gets resolved this time.

**Comment by Codelica** [comment]
People must not be using `numColumns` much :(  

Seeing this as well with a 2 column list for tablets.  Adding one new item will trigger the re-render 40+ items per my settings.  Moving it to 1 column just renders the new addition as expected.  

Since flexWrap "wrap" can't be used with VirtualizedList, and my items are (unfortunately) a little to heavy for low end tablets to re-render in mass, it's unusable currently.

Hope there is a hero out there. :)

**Comment by Dylan0916** [comment]
Has anyone solved this problem?

**Comment by NiccoloCase** [comment]
still an issue!
