### ISSUE TITLE
`color` property in styles of button component doesn't change the font color

### ISSUE THREAD

**Issue by ahtrahdis7** [facebook/react-native#30402]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## React Native version:
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 216.61 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.15.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK: Not Found
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.1 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: https://github.com/expo/react-native/archive/sdk-39.0.4.tar.gz => 0.63.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce

1. Use `<Button />`  component and set `styles={styles.button}`
2. ` const styles = Stylesheet.create({ button : { color: 'black' } }) `

## Expected Results
Button label color must be set to the specified color i.e. **black**

**Comment by arthurgeron-work** [comment]
All text should be inside a `Text` component, if you look into React Native's types you'll see the `Button` component does not   have a property called `style`. For buttons you can you use components like `Pressable` or `TouchableOpcaity`.

**Comment by ahtrahdis7** [comment]
Then, How is one supposed to change the styling of a `Button` component, especially the font of the label.

**Comment by arthurgeron-work** [comment]
I don't think you're supposed to use the default `Button` export from React Native, as it's basically a re-export of React's original Button component.

If you are going to make buttons use components [Pressable](https://reactnative.dev/docs/pressable) or [TouchableOpacity](https://reactnative.dev/docs/touchableopacity).

**Comment by arthurgeron-work** [comment]
I think this can be closed now

**Comment by ahtrahdis7** [comment]
Thanks for the info. It was helpful. Still, I wonder about the use of `Button` component then.

**Comment by arthurgeron-work** [comment]
> Thanks for the info. It was helpful. Still, I wonder about the use of `Button` component then.

I'm not sure why it is even exported to be honest, I admit it is misleading.

**Comment by ahtrahdis7** [comment]
Sure thing

Sidhartha Mallick
