### ISSUE TITLE
Android support for borderTopLeftRadius, etc.

### ISSUE THREAD

**Issue by swathysubhash** [facebook/react-native#3040]
borderRadius works in iOS. But borderTopLeftRadius, borderTopRightRadius is not working.
borderRadius itself is not working in android.

Kindly see this
https://rnplay.org/apps/Ujw1mA

**Comment by astreet** [comment]
borderRadius et al are only a supported property on View.

borderTopLeftRadius, etc. haven't been implemented on Android yet

**Comment by mikeljames** [comment]
I've found the borders to blur... 

https://rnplay.org/apps/mGNsBQ 
![image](https://cloud.githubusercontent.com/assets/2983327/11426191/1c842666-9452-11e5-806b-8e5d18581216.png)

RN version:14.2

**Comment by bodyflex** [comment]
+1

**Comment by dangnelson** [comment]
+1

**Comment by Roconda** [comment]
+1

**Comment by pickhardt** [comment]
I think, in general, if a feature is supported on iOS but not yet on Android, it should throw a not implemented exception when you try to use it on Android. Otherwise, it can be really confusing trying to figure out what the problem is.

**Comment by qpowell** [comment]
+1

**Comment by export-mike** [comment]
@pickhardt this feature is broken on both platforms.

**Comment by s7song** [comment]
+1

**Comment by s7song** [comment]
borderTopLeftRadius, borderTopRightRadius, +2 counter parts seems to be broken again on Android. Is anyone doing a PR for this?

Thanks

**Comment by BigPun86** [comment]
+1

**Comment by creeperyang** [comment]
+1 not work with `<Text>` on **iOS**.

Specify one of `borderBottomLeftRadius / borderBottomRightRadius / borderTopLeftRadius / borderTopRightRadius` does not work.

Specify `borderRadius` works.

RN version: `0.23.1`

**Comment by Tenkir** [comment]
Also not working with `<TextInput>`.

**Comment by realjamie** [comment]
+1

**Comment by eladgel** [comment]
borderBottomLeftRadius / borderBottomRightRadius / borderTopLeftRadius / borderTopRightRadius Also not working in Image

**Comment by wyamei** [comment]
borderRadius works with <View> on Android.
borderBottomLeftRadius / borderBottomRightRadius / borderTopLeftRadius / borderTopRightRadius is not working

**Comment by logicalicy** [comment]
+1 On Android, RN 0.25.0, `borderRadius` works but `borderBottomRightRadius`, etc. don't have any effect.

**Comment by huangbong** [comment]
+1. Broken on <Image> on iOS and Android RN 0.29.0. borderRadius itself works fine.

**Comment by nalwayaabhishek** [comment]
+1 Same for me. Broken on iOS and Android RN 0.30.0.

**Comment by irfanlone** [comment]
+1

**Comment by aashna208** [comment]
+1

**Comment by stanleycyang** [comment]
+1

**Comment by ilyaivjev** [comment]
Broken on iOS RN 0.34.0-rc.0.

**Comment by a11y1337** [comment]
+1

**Comment by Nicomalacho** [comment]
Broken on iOS RN 0.37

**Comment by michaelasper** [comment]
borderTopLeftRadius and all variants still not working. iOS RN 0.37

**Comment by ethanshar** [comment]
+1, not working for Text on iOS

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.

**Comment by davidgoli** [comment]
+1. These properties are still in the docs. If they're not going to be supported, they should be removed altogether.
