### ISSUE TITLE
"Crawling File System" of packager insanely slow

### ISSUE THREAD

**Issue by nevir** [facebook/react-native#3041]
I'm seeing it take upwards of 1.5 mins on a very basic project. From poking around the packager, it appears to be crawling every directory of my project root (all files under `.git`, `node_modules`, `Pods`, etc).

I'm not seeing a good way of configuring the `ignoreFilePath` callback (nor its `blacklistRE`).

Am I doing something wrong w/ the configuration/layout of my project?

**Comment by boourns** [comment]
@nevir When you run `watchman -v` from console, what version is reported?  This is usually due to watchman being out of date. I, for example, am using version 3.3.0.

https://facebook.github.io/watchman/docs/install.html for instructions on installing newer watchman releases.

**Comment by nevir** [comment]
Aha! No global instance of watchman installed, at all. After installing it, the crawl time is down to about a second.  Much better, thanks!

**Comment by JoshYuJump** [comment]
How about windows 10, there's no watchman on windows 10.

**Comment by lester-s** [comment]
Same here. On windows 10 the file system crawling is awfully long. Is there a way to improve that ?
