### ISSUE TITLE
[ListView] Rendering new rows while scrolling can cause the underlying ScrollView to scroll back up

### ISSUE THREAD

**Issue by brentvatne** [facebook/react-native#3042]
See: https://www.youtube.com/watch?v=_8Wkf6SmuLQ for a demo
And: https://github.com/brentvatne/ListViewRenderScrollingError for an example.

It's sometimes hard to reproduce - scroll up a bit and then back down to the bottom, and if the timing is right then when you hit the bottom of the scroll view it will smooth scroll back up.

**Comment by brentvatne** [comment]
cc @mkonicek @kmagiera

**Comment by satya164** [comment]
It also happens when I scroll very fast and it hasn't finished rendering the rows yet.

**Comment by kmagiera** [comment]
That's a known problem. JS listview dynamically adds rows while fling animation is going on. Apparently there is a bug in android scrollview fling animation which doesn't take into account that the height of the scrollview may change while in the meantime. Because it's using hidden API on android there is no good way to workaround this problem. We're working on an alternative implementation that would use native list view instead and should address this problem

**Comment by brentvatne** [comment]
Great, thanks for the update @kmagiera!

**Comment by Sherlock92** [comment]
@kmagiera can this issue also manifest in IOS ?

**Comment by brentvatne** [comment]
@Sherlock92 - nope

**Comment by mkonicek** [comment]
@kmagiera Since `RecyclerViewBackedScrollView` fixes this should we use it everywhere by default on Android and close this?

**Comment by kmagiera** [comment]
We're still experimenting with performance there. This should be done this week. Then we can switch `<ListView>` over to it on android

**Comment by mkonicek** [comment]
:+1:

**Comment by tUrG0n** [comment]
@brentvatne @kmagiera  any updates on this

**Comment by brentvatne** [comment]
@tUrG0n - there is a patched ScrollView for Android that fixes this, open source licensing around that is being investigated cc @vjeux

**Comment by kmagiera** [comment]
@tUrG0n RecyclerViewBackedScrollView landed a while ago and it's ready to be used. You can use
`<RecyclerViewBackedScrollView>` the same way as you use `<ScrollView>`. If you're using `ListView` component you can pass `renderScrollComponent={props => <RecyclerViewBackedScrollView {...props} />}` as a prop to the `ListView` component in order for it to use recycler view as a backend

**Comment by brentvatne** [comment]
`RecyclerViewBackedScrollView` doesn't fix this issue but it does help a lot with scrolling perf. I'll try to open source the `BugFixScrollView` soon!

**Comment by AlexeyToksarov** [comment]
Looks like `RecyclerViewBackedScrollView ` fixes the same issue for me (at least on Android)

**Comment by ramilushev** [comment]
@brentvatne Any update on the `BugFixScrollView`?

**Comment by saoasuna** [comment]
also interested on the fix - my app has several long `ListView`s in it and i can't smoothly fling through them unless i initialize the list to be the whole thing right off the bat 
Slightly unrelated, but `RecyclerViewBackedScrollView` doesn't seem to be working for me as well; it gives an "IndexOutOfBoundsException: Inconsistency detected. Invalid item position" error

**Comment by astuetz** [comment]
+1

**Comment by knowbody** [comment]
Seems like I get similar errors on Android (RN 0.28), stack trace:

```
Fatal Exception: java.lang.IndexOutOfBoundsException: Invalid index 55, size is 41
       at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
       at java.util.ArrayList.get(ArrayList.java:308)
       at com.facebook.react.views.recyclerview.RecyclerViewBackedScrollView$ScrollOffsetTracker.getTopOffsetForItem(RecyclerViewBackedScrollView.java:169)
       at com.facebook.react.views.recyclerview.RecyclerViewBackedScrollView$ReactListAdapter.getTopOffsetForItem(RecyclerViewBackedScrollView.java:310)
       at com.facebook.react.views.recyclerview.RecyclerViewBackedScrollView.calculateAbsoluteOffset(RecyclerViewBackedScrollView.java:325)
       at com.facebook.react.views.recyclerview.RecyclerViewBackedScrollView.onScrollChanged(RecyclerViewBackedScrollView.java:344)
```

not sure if it's a bug or if I'm doing something wrong?

**Comment by ide** [comment]
Closing due to https://github.com/facebook/react-native/commit/36ca1a078acbaba770c196847254e7a6e80c6918

**Comment by tlcheah2** [comment]
Is the IndexOutOfBoundsException issue resolved as well ? I still experiencing it with RN 0.35 in Android.

**Comment by messense** [comment]
Still experiencing `IndexOutOfBoundsException` with RN 0.39 on Android.

**Comment by guiherzog** [comment]
Still experiencing IndexOutOfBoundsException with RN 0.40 on Android.

**Comment by awitherow** [comment]
Still experiencing this with `"react-native": "0.41.2"`. Wanted to implement the 

```renderScrollComponent={props => <RecyclerViewBackedScrollView {...props} />}``` as recommended in the documentation, but apparently this is deprecated.

**Comment by awitherow** [comment]
Currently solution for my team is just to pass in the initialListSize to equal the listItems.length. Luckily our list is only around 50 items long with no graphics.

**Comment by bhanuprakashsharma** [comment]
What is the solution of this bug can any body please tell me about this
