### ISSUE TITLE
ThumbColor of Switch not working when switch is true when running app on Web.

### ISSUE THREAD

**Issue by Piet-G** [facebook/react-native#30429]
## Description

The provided thumbColor of the Switch component is not visible when the switch is true on the web. It does work properly on Android and IOS

`<Switch thumbColor={"blue"} value={isEnabled} onValueChange={setEnabled}/>` 

Switch value is true:

 ![image](https://user-images.githubusercontent.com/7482073/99678593-457b8900-2a7b-11eb-9a7e-b03fd8c66b74.png)

Switch value is false:

![image](https://user-images.githubusercontent.com/7482073/99678445-1cf38f00-2a7b-11eb-8673-e71818d121f2.png)
## React Native version:

System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
    Memory: 1.14 GB / 7.74 GB
  Binaries:
    Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.7.30523.141 (Visual Studio Community 2019)
  Languages:
    Java: Not Found
    Python: 3.8.5
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce

1. Create a `Switch `component from react-native and provide it a `thumbColor`
2. Run the app on the web and see that the color is not visible when the value of the switch is true.

## Expected Results

The provided thumbColor should be visible when the switch is enabled. Not only when it is disabled.

## Snack, code example, screenshot, or link to a repository:

https://snack.expo.io/BY!WFj97J

**Comment by bouaoud** [comment]
Hello,

I am having same issue when running on web using react-native-web, my thumbColor='white' is not applied when switch is on

**Comment by rickyplouis** [comment]
I ran into the same issue and found out that on react-native-web the Switch component has an activeThumbColor prop that is not in react native. Defer to the react native web docs below for implementation.

http://necolas.github.io/react-native-web/docs/?path=/docs/components-switch--active-thumb-color

**Comment by bouaoud** [comment]
Thanks for your response. I am using styled component to import Switch, how can i do to personnalise my Switch (to look like iOS switch) and change thumbColor when disabled?

here is my source code : 

1- const SwitchComponent = styled.Switch`
    padding-vertical: 14.5px;
    padding-horizontal: 3px;
    justify-content: center
    width: 43px
    height: 19.5px
`

result:
![Capture d’écran 2021-01-13 à 11 56 45](https://user-images.githubusercontent.com/1932365/104443363-9ea4fc00-5596-11eb-86e7-a17de2006841.png)
 
expected :
![Capture d’écran 2021-01-13 à 11 57 16](https://user-images.githubusercontent.com/1932365/104443423-b0869f00-5596-11eb-8b01-b74d303b5c46.png)

I dont know why it is so difficult to personnalise the Switch to look like iOS switch in react native (web version).

2- how to change thumbColor using styled-components/native (Switch) when disabled ?

<SwitchComponent
                thumbTintColor={'red'}  // (props.isOn ? 'activeColor : 'inactif color') does not work
                trackColor={props.trackColorValues}
                onValueChange={() => props.setValue && props.setValue(props.value)}
                value={props.value}
            />


Thanks for your help

**Comment by timoteialbu** [comment]
Having the same issue here as @Piet-G. As opposed to the other posters, I am not able to use react-native-web in this instance since the Switch component I use is wrapped by https://www.npmjs.com/package/react-native-gesture-handler.

**Comment by fuelkoy** [comment]
This problem can be fixed `activeThumbColor ` prop which @rickyplouis pointed out. Set inactive thumbColor in `thumbColor` prop and active thumbColor  in `activeThumbColor` prop.

Code:
`thumbColor={ !active ? 'yellow' : undefined}
 //@ts-expect-error type
activeThumbColor={'red'}`

@ts-expect-error is there because prop is not recognized even it works.

Here are pictures of given props in action
in active:
![Sieppaa](https://user-images.githubusercontent.com/65889813/169229929-2a483a3b-4e89-4eaf-83e1-8fafd611f316.PNG)
active:
![Sieppaa2](https://user-images.githubusercontent.com/65889813/169229937-f906a041-1e94-4a23-b8fc-5db24c112e71.PNG)

**Comment by marctorsoc** [comment]
if someone comes here looking for a solution, I ended up using 
```
// web
          activeThumbColor={
            readingMode ? GlobalStyles.colors.accent : "#f4f3f4"
          }
          // android
          thumbColor={
            readingMode ? GlobalStyles.colors.accent : "#f4f3f4"
          }
```

not sure if best solution, but works 🤷‍♂️
