### ISSUE TITLE
[Android] Long press on TextInput do not showing context menu(copy/paste) inside ViewPagerAndroid on first load.

### ISSUE THREAD

**Issue by darron1217** [facebook/react-native#30438]
From https://github.com/facebook/react-native/issues/28099

## Description
I'm currently using ViewPager through `@react-navigation/material-top-tabs` package.

I created `TextInput` on the Tab.
And tried to paste some texts from clipboard. But even after long long press, the `TextInput` does not showing any context or cursor.
But after I put some texts in it, then it started to work again.

## React Native version:
```
System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz
    Memory: 79.00 MB / 24.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.3 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.8 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Create `TextInput` inside `AndroidViewPager`
2. Do long press on the `TextInput`
3. shows nothing.

## Expected Results
Show context menu to paste some text in it!

**Comment by JoshuaGross** [comment]
Can you try on master? This should have been fixed in October 2020:

https://github.com/facebook/react-native/commit/12a50c0a442b78d9095398d955bec307cfcb0f69

**Comment by darron1217** [comment]
@JoshuaGross Does that means upgrading `0.63.3` to `0.63.4` can fix this issue?

**Comment by JoshuaGross** [comment]
@darron1217 i think so. It is expected to be fixed if you upgrade to a version with that change.

**Comment by fabriziobertoglio1987** [comment]
Do you still experience this issue? 

I have four years of experience maintaining facebook/react-native and I specialize in the Text and TextInput components. I currently have 58 [facebook/react-native PRs](https://github.com/facebook/react-native/pulls?q=is%3Apr+author%3Afabriziobertoglio1987+). 

If you still experience this issue, I will prepare a patched release with the fix.

Thanks a lot
