### ISSUE TITLE
[Android] Textinput placeholder does not respect numberOfLines prop

### ISSUE THREAD

**Issue by akshitrcrm** [facebook/react-native#30437]

**Comment by akshitrcrm** [comment]
System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 133.70 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.8.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.7 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.1, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.1/12A7403 - /usr/bin/xcodebuild
  Languages:
    Java: 14.0.2 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by boerdjamin** [comment]
+1

**Comment by chrisglein** [comment]
Can you provide more detail on your repro? I tried this out in a [snack](https://snack.expo.io/@chrisglein/repro30437). On Android `numberOfLines` does provides a minimum amount of space that the `TextInput` takes up, but does not truncate the text length, either for the placeholder or for typed text. On Web it provides a fixed line height. The behavior on iOS is actually mostly similar to Android - it doesn't seem to provide a maximum. Is there difference in what the native controls offer as far as a `numberOfLines` property? It doesn't look like this is Android specific. The behavior of [numberOfLines](https://reactnative.dev/docs/next/textinput#numberoflines) in the RN docs isn't terribly well defined.

**Comment by akshitrcrm** [comment]
For iOS, placeholder text is truncated properly
![Simulator Screen Shot - iPhone 11 - 2021-08-10 at 17 54 35](https://user-images.githubusercontent.com/69840129/128866463-ea3edf5e-0a71-4d35-b875-6d85c8bb318a.png)

For Android, it isn't
![Screenshot_20210810-175547](https://user-images.githubusercontent.com/69840129/128866612-c2fca3f5-f0b8-49c1-818b-807e8532e9f6.png)

```<TextInput
          style={styles.searchinput}
          ref={searchRef}
          placeholder='This placeholder does not show truncating text on android'
          placeholderTextColor={colors.placeholderText}
          value={keyword}
          onChangeText={onChangeText}
          returnKeyType="search"
          autoCapitalize="none"
          autoCorrect={false}
          allowFontScaling={false}
          numberOfLines={1}
        />
        
  searchinput: {
    fontSize: 16,
    marginLeft: 5,
    flex: 1,
    backgroundColor: 'yellow',
    color: colors.textGray
  }

```

**Comment by safaiyeh** [comment]
Thanks for the follow up @akshitrcrm, makes sense they should have the same behavior.

**Comment by cristianc-infocorp** [comment]
This also happens with the `value` property, it does not respect `numberOfLines`

**Comment by fabriziobertoglio1987** [comment]
Do you still experience this issue? 

I have four years of experience maintaining facebook/react-native and I specialize in the Text and TextInput components. I currently have 58 [facebook/react-native PRs](https://github.com/facebook/react-native/pulls?q=is%3Apr+author%3Afabriziobertoglio1987+). 

If you still experience this issue, I will prepare a patched release with the fix.

Thanks a lot

**Comment by irawel** [comment]
@fabOnReact Yes, this is still happening on 0.73.4

**Comment by aviktius** [comment]
The same behavior when passing the `selectable` prop alongside the `numberOfLines`. 


```<Text selectable numberOfLines={1} />```

<img width="286" alt="Screenshot 2024-08-01 at 14 07 50" src="https://github.com/user-attachments/assets/a6b5a3b3-85a0-4dc0-b1ae-ce4d920cc132">

https://github.com/user-attachments/assets/f7848265-7425-4ce0-bc27-e7aa8c0e031b



```<Text numberOfLines={1} />```
<img width="286" alt="Screenshot 2024-08-01 at 14 06 52" src="https://github.com/user-attachments/assets/0cd0bd0e-cff8-4838-b9fd-2ad49a60e4e8">


iOS:
```<Text selectable numberOfLines={1} />```

<img width="229" alt="Screenshot 2024-08-01 at 14 10 30" src="https://github.com/user-attachments/assets/366abc7c-4f77-46d7-8e5e-c20992be8241">

**Comment by BorislavStefanov31** [comment]
The behavior still persists.

`				<TextInput
					ref={inputRef}
					returnKeyType={'done'}
					style={[styles.input, inputStyle]}
					placeholder={placeholder}
					autoCapitalize={autoCapitalize || 'sentences'}
					placeholderTextColor={Colors.text.placeholder}
					value={searchInputValue}
					onBlur={onBlur}
					editable={editable}
					numberOfLines={1}
					onChangeText={onTextChange}
					onPressIn={onPressInHandler}
					autoFocus={autoFocus}
					autoCorrect={false}
					underlineColorAndroid={'transparent'}
				/>`

![Image](https://github.com/user-attachments/assets/33d6070d-40d1-4cdf-9204-d2ed771d98b7)

**Comment by jonuorah26** [comment]
Has this been fixed yet?
