### ISSUE TITLE
packager FATAL ERROR: JavaScript heap out of memory

### ISSUE THREAD

**Issue by nazaninsaba** [facebook/react-native#30433]
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

## Description
Hi, I'm using react-native for developing an app with tensorflow models using `react-native-tensorflow` package
I add model to app assets successfully with `.pb` extention that I added to `metro.config.js`. when app start running metro start bundling files but in last percents stop working and threw an exception from node.js v8 engine as below. one point that should be possible reason for this crash is my model is about 100 MB.

How can I fix this?

## React Native version:
System:
    OS: Windows 10 10.0.19041
    CPU: (4) x64 Intel(R) Core(TM) i3-2350M CPU @ 2.30GHz
    Memory: 3.62 GB / 7.94 GB
  Binaries:
    Node: 14.7.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 23, 27, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.1
      System Images: android-24 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6858069
    Visual Studio: Not Found
  Languages:
    Java: 1.8.0_262 - C:\Program Files\OpenJDK\openjdk-8u262-b10\bin\javac.EXE
    Python: 2.7.18 - C:\Python27\python.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.3 => 0.63.3
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Snack, code example, screenshot, or link to a repository:
```
transform[stderr]:
transform[stderr]: <--- Last few GCs --->
transform[stderr]:  m[12204:000001D57DB1FE80]
transform[stderr]:   73685 ms: Mark-sweep (reduce) 2051.5 (2057.4) -> 2051.5 (2058.4) MB, 2175.8 / 0.0 ms  (+ 166.0 ms in 15 steps since start of marking, biggest step 24.1 ms, walltime since start of marking 2350 ms) (average mu = 0.116, current m[12204:000001D57DB1FE80]    76048 ms: Mark-sweep (reduce) 2052.5 (2055.4) -> 2052.5 (2057.4) MB, 2199.3 / 0.0 ms  (+ 153.6 ms in 16 steps since start of marking, biggest step 33.9 ms, walltime since start of marking 2364 ms) (average mu = 0.063, current m
transform[stderr]: 
transform[stderr]:
transform[stderr]: <--- JS stacktrace --->
transform[stderr]:
transform[stderr]: FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
transform[stderr]:  1: 00007FF7A6C603EF napi_wrap+110031
transform[stderr]:  2: 00007FF7A6C06106 v8::internal::OrderedHashTable<v8::internal::OrderedHashMap,2>::NumberOfElementsOffset+33350
transform[stderr]:  3: 00007FF7A6C06ED6 v8::internal::OrderedHashTable<v8::internal::OrderedHashMap,2>::NumberOfElementsOffset+36886
transform[stderr]:  4: 00007FF7A74B9F7E v8::Isolate::ReportExternalAllocationLimitReached+94
transform[stderr]:  5: 00007FF7A749ED1D v8::SharedArrayBuffer::Externalize+781
transform[stderr]:  6: 00007FF7A735D02C v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1516
transform[stderr]:  7: 00007FF7A736838A v8::internal::Heap::ProtectUnprotectedMemoryChunks+1258
transform[stderr]:  8: 00007FF7A7365549 v8::internal::Heap::PageFlagsAreConsistent+2457
transform[stderr]:  9: 00007FF7A735A0D1 v8::internal::Heap::CollectGarbage+2033
transform[stderr]: 10: 00007FF7A73582C5 v8::internal::Heap::AllocateExternalBackingStore+1365
transform[stderr]: 11: 00007FF7A737A931 v8::internal::Factory::NewJSArrayWithUnverifiedElements+305
transform[stderr]: 12: 00007FF7A737A7DF v8::internal::Factory::NewJSArrayWithElements+31
transform[stderr]: 13: 00007FF7A707C150 v8::internal::DeclarationScope::was_lazily_parsed+4608
transform[stderr]: 14: 00007FF7A707FF96 v8::sampler::Sampler::IsActive+4950
transform[stderr]: 15: 00007FF7A7542B5D v8::internal::SetupIsolateDelegate::SetupHeap+463949
transform[stderr]: 16: 00007FF7A759273A v8::internal::SetupIsolateDelegate::SetupHeap+790570
transform[stderr]: 17: 00007FF7A7533952 v8::internal::SetupIsolateDelegate::SetupHeap+401986
transform[stderr]: 18: 00007FF7A74DB542 v8::internal::SetupIsolateDelegate::SetupHeap+40498
transform[stderr]: 1
transform[stderr]: 9: 00007FF7A74DB542 v8::internal::SetupIsolateDelegate::SetupHeap+40498
transform[stderr]: 20: 00007FF7A74DB542 v8::internal::SetupIsolateDelegate::SetupHeap+40498
transform[stderr]: 21: 00007FF7A74DB542 v8::internal::SetupIsolateDelegate::SetupHeap+40498
transform[stderr]: 22: 00007FF7A750AB4F v8::internal::SetupIsolateDelegate::SetupHeap+234559
transform[stderr]: 23: 00007FF7A74DB542 v8::internal::SetupIsolateDelegate::SetupHeap+40498
transform[stderr]: 24: 00007FF7A750AB4F v8::internal::SetupIsolateDelegate::SetupHeap+234559
transform[stderr]: 25: 00007FF7A74DB542 v8::internal::SetupIsolateDelegate::SetupHeap+40498
transform[stderr]: 26: 00007FF7A74DB542 v8::internal::SetupIsolateDelegate::SetupHeap+40498
transform[stderr]: 27: 00007FF7A74D5179 v8::internal::SetupIsolateDelegate::SetupHeap+14953
transform[stderr]: 28: 00007FF7A74DB542 v8::internal::SetupIsolateDelegate::SetupHeap+40498
transform[stderr]: 29: 00007FF7A74DB542 v8::internal::SetupIsolateDelegate::SetupHeap+40498
transform[stderr]: 30: 00007FF7A750AB4F v8::internal::SetupIsolateDelegate::SetupHeap+234559
transform[stderr]: 31: 00007FF7A74DB542 v8::internal::SetupIsolateDelegate::SetupHeap+40498
transform[stderr]: 32: 00007FF7A74DB542 v8::internal::SetupIsolateDelegate::SetupHeap+40498
transform[stderr]: 33: 00007FF7A74DB542 v8::internal::SetupIsolateDelegate::SetupHeap+40498
transform[stderr]: 34: 00007FF7A7582D00 v8::internal::SetupIsolateDelegate::SetupHeap+726512
transform[stderr]: 35: 00007FF7A74D744A v8::internal::SetupIsolateDelegate::SetupHeap+23866
transform[stderr]: 36: 00007FF7A75C0FE3 v8::internal::SetupIsolateDelegate::SetupHeap+981203
transform[stderr]: 37: 00007FF7A74DB542 v8::internal::SetupIsolateDelegate::SetupHeap+40498
transform[stderr]: 38: 00007FF7A74DB542 v8::internal::SetupIsolateDelegate::SetupHeap+40498
transform[stderr]: 39: 00007FF7A74DB542 v8::internal::SetupIsolateDelegate::SetupHeap+40498
transform[stderr]: 40: 00007FF7A750AB4F v8::internal::SetupIsolateDelegate::SetupHeap+234559
transform[stderr]: 41: 00007FF7A74DB542 v8::internal::SetupIsolateDelegate::SetupHeap+40498
transform[stderr]: 42: 00007FF7A74DB542 v8::internal::SetupIsolateDelegate::SetupHeap+40498
transform[stderr]: 43: 00007FF7A74DB542 v8::internal::SetupIsolateDelegate::SetupHeap+40498
transform[stderr]: 44: 00007FF7A7582D00 v8::internal::SetupIsolateDelegate::SetupHeap+726512
transform[stderr]: 45: 00007FF7A74D744A v8::internal::SetupIsolateDelegate::SetupHeap+23866
transform[stderr]: 46: 00007FF7A75C0FE3 v8::internal::SetupIsolateDelegate::SetupHeap+981203
transform[stderr]: 47: 00007FF7A74DB542 v8::internal::SetupIsolateDelegate::SetupHeap+40498
transform[stderr]: 48: 00007FF7A74D5179 v8::internal::SetupIsolateDelegate::SetupHeap+14953
transform[stderr]: 49: 00007FF7A74DB542 v8::internal::SetupIsolateDelegate::SetupHeap+40498
transform[stderr]: 50: 00007FF7A74D5179 v8::internal::SetupIsolateDelegate::SetupHeap+14953
transform[stderr]: 51: 00007FF7A74DB542 v8::internal::SetupIsolateDelegate::SetupHeap+40498
transform[stderr]: 52: 00007FF7A74DB542 v8::int
transform[stderr]: ernal::SetupIsolateDelegate::SetupHeap+40498
transform[stderr]: 53: 00007FF7A74DB542 v8::internal::SetupIsolateDelegate::SetupHeap+40498
transform[stderr]: 54: 00007FF7A74DB542 v8::internal::SetupIsolate
transform[stderr]: Delegate::SetupHeap+40498
transform[stderr]: 55: 00007FF7A74DB542 v8::internal::SetupIsolateDelegate::SetupHeap+40498
transform[stderr]: 56: 00007FF7A74DB542 v8::internal::SetupIsolateDelegate::SetupHeap+40498
transform[stderr]: 57: 00007FF7A74D5179 v8::internal::S
transform[stderr]: etupIsolateDelegate::SetupHeap+14953
transform[stderr]: 58: 00007FF7A74DB542 v8::internal::SetupIsolateDelegate::SetupHeap+40498
transform[stderr]: 59: 00007FF7A74DB542 v8::internal::SetupIsolateDelegate::SetupHeap+40498
transform[stderr]: 60: 00007FF7A74D91FE v8::internal::SetupIsolateDelegate::SetupHeap+31470
transform[stderr]: 61: 00007FF7A74D8DEC v8::internal::SetupIsolateDelegate::SetupHeap+30428
transform[stderr]: 62: 00007FF7A73BD149 v8::internal::Execution::CallWasm+1657
transform[stderr]: 63: 00007FF7A73BC9AF v8::internal::Execution::Call+191
transform[stderr]: 64: 00007FF7A74941A7 v8::Function::Call+615
transform[stderr]: 65: 00007FF7A6C83C8D node::CallbackScope::~CallbackScope+861
transform[stderr]: 66: 00007FF7A6C83FCB n
transform[stderr]: ode::CallbackScope::~CallbackScope+1691
transform[stderr]: 67: 00007FF7A6C7C034 v8::internal::compiler::Operator::EffectOutputCount+228
transform[stderr]: 68: 00007FF7A6B2ED23 v8::internal::Isolate::isolate_root_bias+13459
transform[stderr]: 69: 00007FF7A6B2F8A7 v8::internal::Isolate::isolate_root_bias+16407
transform[stderr]: 70: 00007FF7A6B2A509 v8::internal::Debug::break_frame_id+1257
transform[stderr]: 71: 00007FF7A6CA59F2 uv_thread_self+2946
transform[stderr]: 72: 00007FF7A6CA5A67 uv_thread_self+3063
transform[stderr]: 73: 00007FF7A6CA879F uv_pipe_pending_type+3343
transform[stderr]: 74: 00007FF7A6CB36AC uv_loop_init+860
transform[stderr]: 75: 00007FF7A6CB39AA uv_run+202
transform[stderr]: 76: 00007FF7A6BBFB25 v8::internal::OrderedHashTable<v8::internal::OrderedHashSet,1>::NumberOfBuc
transform[stderr]: ketsOffset+9477
transform[stderr]: 77: 00007FF7A6C33C70 node::Start+288
transform[stderr]: 78: 00007FF7A6A9678C RC4_options+339596
transform[stderr]: 79: 00007FF7A7A1FEFC v8::internal::compiler::RepresentationChanger::Uint32OverflowOperatorFor+156316
transform[stderr]: 80: 00007FFBE0A07034 BaseThreadInitThunk+20
transform[stderr]: 81: 00007FFBE13FCEC1 RtlUserThreadStart+33
transform[stderr]:
transform[stderr]: <--- Last few GCs --->
transform[stderr]:  =[16036:000001696CD351A0]    25694 ms: Mark-sweep (reduce)
transform[stderr]:  2048.1 (2054.1) -> 2048.0 (2054.9) MB, 2038.3 / 0.0 ms  (+ 0.0 ms in 13 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 2045 ms) (average mu = 0.283, current mu =[16036:000001696CD351A0]    28431 ms: Mark-sweep (reduce) 2049.0 (2051.9) -> 2049.0 (2053.9) MB, 2729.1 / 0.0 ms  (+ 0.0 ms in 12 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 2736 ms) (average mu = 0.134, current mu =
```

**Comment by sangameshrently** [comment]
first Run 
export NODE_OPTIONS=--max_old_space_size=8192

then run your app.
Hope that works

**Comment by shafqatbari** [comment]
transform[stderr]:
transform[stderr]: <--- Last few GCs -
transform[stderr]: -->
transform[stderr]:
transform[stderr]: [512:000002133B263810]   511765 ms: Mark-sweep (reduce) 2019.6 (2082.3) -> 2019.4 (2083.3) MB, 3344.5 / 0.0 ms  (average mu = 0.111, current mu = 0.001) allocation failure scavenge might not succeed
transform[stderr]: [512:000002133B263810]   517237 ms: Mark-sweep (reduce) 2020.4 (2083.3) -> 2020.2 (2084.0) MB, 5469.6 / 0.1 ms  (average mu = 0.050, current mu = 0.000) allocation failure scavenge might not succeed
transform[stderr]:
transform[stderr]:
transform[stderr]: <--- JS stacktrace --->
transform[stderr]:
transform[stderr]: FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
transform[stderr]:  1: 00007FF6A70433EF v8::
transform[stderr]: internal::Isolate::ArchiveSpacePerThread+4447
transform[stderr]:  2: 00007FF6A6FDDEA6 v8::internal::MicrotaskQueue::GetMicrotasksScopeDepth+65030
transform[stderr]:  3: 00007FF6A6FDEDA6 node::OnFatalError+294
transform[stderr]:  4: 00007FF6A78D9FEE v8::Isolate::ReportExternalAllocationLimitReached+94
transform[stderr]:  5: 00007FF6A78BE6FD v8::SharedArrayBuffer::Externalize+781
transform[stderr]:  6: 00007FF6A775814C v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1468
transform[stderr]:  7: 00007FF6A7763831 v8::internal::Heap::ProtectUnprotectedMemoryChunks+1281
transform[stderr]:  8: 00007FF6A77607F9 v8::internal::Heap::PageFlagsAreConsistent+2377
transform[stderr]:  9: 00007FF6A7755371 v8::internal::Heap::CollectGarbage+1969
transform[stderr]: 10: 00007FF6A7753605 v8::internal::Heap::AllocateExternalBackingStore+1493
transform[stderr]: 11: 00007FF6A7775690 v8::internal::Factory::NewFillerObject+192
transform[stderr]: 12: 00007FF6A749B94A v8::internal::interpreter::JumpTableTargetOffsets::iterator::operator=+1386
transform[stderr]: 13: 00007FF6A79612BD v8::internal::SetupIsolateDelegate::SetupHeap+456685
transform[stderr]: 14: 0000019B33EA985C

**Comment by shafqatbari** [comment]
> transform[stderr]:
> transform[stderr]: <--- Last few GCs -
> transform[stderr]: -->
> transform[stderr]:
> transform[stderr]: [512:000002133B263810] 511765 ms: Mark-sweep (reduce) 2019.6 (2082.3) -> 2019.4 (2083.3) MB, 3344.5 / 0.0 ms (average mu = 0.111, current mu = 0.001) allocation failure scavenge might not succeed
> transform[stderr]: [512:000002133B263810] 517237 ms: Mark-sweep (reduce) 2020.4 (2083.3) -> 2020.2 (2084.0) MB, 5469.6 / 0.1 ms (average mu = 0.050, current mu = 0.000) allocation failure scavenge might not succeed
> transform[stderr]:
> transform[stderr]:
> transform[stderr]: <--- JS stacktrace --->
> transform[stderr]:
> transform[stderr]: FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
> transform[stderr]: 1: 00007FF6A70433EF v8::
> transform[stderr]: internal::Isolate::ArchiveSpacePerThread+4447
> transform[stderr]: 2: 00007FF6A6FDDEA6 v8::internal::MicrotaskQueue::GetMicrotasksScopeDepth+65030
> transform[stderr]: 3: 00007FF6A6FDEDA6 node::OnFatalError+294
> transform[stderr]: 4: 00007FF6A78D9FEE v8::Isolate::ReportExternalAllocationLimitReached+94
> transform[stderr]: 5: 00007FF6A78BE6FD v8::SharedArrayBuffer::Externalize+781
> transform[stderr]: 6: 00007FF6A775814C v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1468
> transform[stderr]: 7: 00007FF6A7763831 v8::internal::Heap::ProtectUnprotectedMemoryChunks+1281
> transform[stderr]: 8: 00007FF6A77607F9 v8::internal::Heap::PageFlagsAreConsistent+2377
> transform[stderr]: 9: 00007FF6A7755371 v8::internal::Heap::CollectGarbage+1969
> transform[stderr]: 10: 00007FF6A7753605 v8::internal::Heap::AllocateExternalBackingStore+1493
> transform[stderr]: 11: 00007FF6A7775690 v8::internal::Factory::NewFillerObject+192
> transform[stderr]: 12: 00007FF6A749B94A v8::internal::interpreter::JumpTableTargetOffsets::iterator::operator=+1386
> transform[stderr]: 13: 00007FF6A79612BD v8::internal::SetupIsolateDelegate::SetupHeap+456685
> transform[stderr]: 14: 0000019B33EA985C

facing this issue on windows
