### ISSUE TITLE
Detecting android user using third party keyboard

### ISSUE THREAD

**Issue by notmez49** [facebook/react-native#30430]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Trying to detect and warn android user of using any third party keyboard might cause sensitive data to be captured, misused, and leaked. But i cant find any solution online.

## React Native version:
0.59.1

## Expected Results
Detection of android user using third party keyboard.

**Comment by dulmandakh** [comment]
Sorry, this issue tracker intended for RN issues only, not developer support. Also I'm afraid that RN doesn't have such feature, and you might need to write custom native module for that.
