### ISSUE TITLE
React Native 0.63.3 app doesn't install on Android 4.1

### ISSUE THREAD

**Issue by RobinBobin** [facebook/react-native#30439]
## Description
I created an app with `npx react-native init Test41 --version 0.63.3`. I'm using Oracle Java version 15.0.1, and I had to set gradle to 6.5 in my `gradle.properties` and use version 4.1.0 of the gradle plugin as the app failed to build otherwise. I didn't change anything else.  I have

    minSdkVersion = 16
    compileSdkVersion = 29
    targetSdkVersion = 29

in my `android/build.gradle`. It runs fine on Android 9, but doesn't install on a client's device, which is Samsung Galaxy S II, running Android 4.1. My client copies the apk on his phone, launches the installer, allows to use internet (the basic RN android.permission.INTERNET) and then he is presented with a screen, just saying the app isn't installed.

## React Native version:
I have both Android Studio and Android SDK installed. I carefully followed the [setup guide](https://reactnative.dev/docs/environment-setup) and I can't understand why they aren't found.

System:
    OS: Linux 5.8 Ubuntu 20.10 (Groovy Gorilla)
    CPU: (4) x64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
    Memory: 1006.61 MB / 5.70 GB
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.15.0 - ~/.nvm/versions/node/v14.15.0/bin/node
    Yarn: Not Found
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.0/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 15.0.1 - /usr/lib/jvm/jdk-15.0.1/bin/javac
    Python: 3.8.6 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Just create a new app with `npx react-native init Test41 --version 0.63.3`, build release and try to install on Android 4.1

## Expected Results
The app is installed on Android 4.1.

## Snack, code example, screenshot, or link to a repository:
[repo](https://github.com/RobinBobin/test41)

**Comment by Goldziher** [comment]
For me the app immediately crashes when i use the android gradle plugin 4.1.1 + gradle 6.5 or 6.7. The error it gives me is that my app is not bundled for release and requires the metro server - this is in a production build. It seems whatever gradle settings I use do not change this at all. I had to revert back to using the android gradle plugin 3.5.3 for this to work.

**Comment by RobinBobin** [comment]
> For me the app immediately crashes when i use the android gradle plugin 4.1.1 + gradle 6.5 or 6.7. The error it gives me is that my app is not bundled for release and requires the metro server - this is in a production build. It seems whatever gradle settings I use do not change this at all. I had to revert back to using the android gradle plugin 3.5.3 for this to work.

And you managed to install it on Android 4.1?

**Comment by viky293** [comment]
I am facing the same issue on
Android 9 - Have already been struggling for 3 days, all I got was frustrating posts on git about react-native. 

Any help appreciated.
Gradle Plugin Version 4.1.1
Gradle Version 6.8-milestone-3
Tried with other versions too, deleted node_modules, upgraded all packages. 

App works fine in debug mode and doesn't work in release bundle, possibly something wrong with the bundling. While bundling process I can see that index.android.bundle is generated. Validated the file exists. It had references to the IP and localhost not sure if that's how the bundle should be in release variant.

**Comment by RobinBobin** [comment]
I use `./gradlew assembleRelease && jarsigner ...` **twice** to build the release version. That is, after the release is successfully built and signed, I repeat the process. Otherwise the release is outdated.

**Comment by Goldziher** [comment]
I am able to build successfully, and the apk is signed. The problem though is that the app is not bundled correctly - or more precisely - the android.bundle.js file is generated, but it still isn't picked up. I therefore get the error telling me to start the metro server or bundle my app correctly. I believe there is some incompatibility between the RN gradle script and the new version, but I haven't delved too deeply into it.

**Comment by viky293** [comment]
Day 4 seems to be wasted again, yes this is not a productive comment, but I am feeling same for the RN at the moment.

**Comment by ravirajn22** [comment]
@RobinBobin your case is app not getting installed on device with android version v16, officially support for less than v21 dropped. So don't expect any support.

@Goldziher your problem is quite different check your android logcat, because your app crashes.

@viky293 what error are you getting? without any details its near to impossible to debug.

**Comment by LeeKyungJoon** [comment]
I have the same problem, but the version is a little different. I'm using "com.android.tools.build:gradle:4.1.1" and "react-native 63.2".
Builds are good in Samseong A51 using android 10, but if you install release app and run the app, there will be an app crash occurs.
What should I do?

**Comment by arcsoftanil** [comment]
I am also facing the same app is not install in version < 5.1.0. Any luck
