### ISSUE TITLE
Cannot see red error screen in case of javascript errors

### ISSUE THREAD

**Issue by kaushikwavhal** [facebook/react-native#30447]
I am in the processing of migrating our app from v0.59.9 to v0.63.3. While i got other things migrated successfully, i noticed that javascript (non-fatal) errors that used to be thrown in a red screen earlier are not reported the same way. For basic javascript errors like `undefined is not a method`, the app crashes and then i have to check `adb log cat` and then de-obfuscate them using `metro-symbolicate` to see what the error is. I am tried running the app with `--variant=debug` without success. Is there a better way to see these errors without this cumbersome process?

https://i.stack.imgur.com/QhTSw.png

**Comment by dulmandakh** [comment]
Hermes currently doesn't fully support ES6, and it might be a cause especially with react-native-firebase. in 0.64, Hermes will support almost all ES6. Please use JSC until then. Thanks

**Comment by Huxpro** [comment]
> Hermes currently doesn't fully support ES6

@dulmandakh emm I'm not sure if that is the root cause. Isn't ES6+ JavaScript source code going through Babel transformations (via Metro) anyways? cc @motiz88 

> in 0.64, Hermes will support almost all ES6.

Also, this is not true. Please see <https://github.com/facebook/hermes/blob/master/doc/Features.md> for the ES features coverage.

**Comment by kaushikwavhal** [comment]
> @kaushikwavhal are you using some of the Proxy-based libraries e.g. react-native-firebase or MobX?

@Huxpro No, i am not using these libraries. I went on fixing each errors from the log cat and now the app does not crash but i still see the errors in `adb log cat` instead of the red screen.

Here's one latest example. Not sure how i should trace that.
![image](https://user-images.githubusercontent.com/3597513/100051230-593f3a80-2e41-11eb-8070-f04498fe9de7.png)


> Please use JSC until then

@dulmandakh When i disable hermes and enable jsc, i am perpetually getting the React native version mismatch error. I even grep'd the whole code base to see if the older version is left somewhere but no success.

**Comment by kaushikwavhal** [comment]
edit:
Even with Hermes disabled, all the javascript errors are logged in `adb log cat` and i can't see the red error screen. Also, i can't happen to open the developer menu any way even when the debug apk is installed through `react-native run-android`

**Comment by kaushikwavhal** [comment]
i was able to get the developer menu working by removing this from MainApplication.java:
`import com.facebook.react.BuildConfig`.

Re: https://github.com/facebook/react-native/issues/26417

**Comment by kaushikwavhal** [comment]
This worked after removing` import com.facebook.react.BuildConfig` and `android:usesCleartextTraffic="true"`. Never been more happy to see an error screen.
