### ISSUE TITLE
Network request failed for pre-bundled main.jsbundle

### ISSUE THREAD

**Issue by t100n** [facebook/react-native#3044]
I'm loading the Javascript code from a pre-bundled file on disk (by react-native bundle --minify) and changing the appropriate lines (I believe) in AppDelegate.m:
```
jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
```

Whenever I lose connection to the Internet the application throws this error:
```
[tid:com.facebook.React.JavaScript] 'Error: Network request failed\n stack:
onload          main.jsbundle:6
value           main.jsbundle:6
value           main.jsbundle:6
value           main.jsbundle:5
<unknown>       main.jsbundle:5
applyWithGuard  main.jsbundle:1
value           main.jsbundle:4
value           main.jsbundle:3
<unknown>       main.jsbundle:3
 _               main.jsbundle:3
<unknown>       main.jsbundle:3
<unknown>       main.jsbundle:3
perform         main.jsbundle:3
batchedUpdates  main.jsbundle:6
i               main.jsbundle:3
<unknown>       main.jsbundle:3
 _               main.jsbundle:3
value           main.jsbundle:3
URL: file:///Users/X/Library/Developer/CoreSimulator/Devices/X/data/Containers/Bundle/Application/X/X.app/main.jsbundle
line: 6
message: Network request failed'
```

Since I'm loading it from the device I would expect it to keep on living without throwing any kind of errors. If I set the deploy to release then the app just crashes because of this unhandled exception.

Am I missing something?

**Comment by t100n** [comment]
After some testing I found that the culprit was the "Fetch" module.
I tried using superagent and I no longer get that issue.

Still I would like to understand what the issue with Fetch is or if I'm missing something while using it that triggers this issue.

**Comment by icefoggy** [comment]
I also get this problem on android

**Comment by MossP** [comment]
+1 Getting this also on RN 0.13.0-rc

**Comment by MossP** [comment]
I believe the xcode.proj has the wrong path in my case which is strange as it's the virgin file.

**Comment by MossP** [comment]
I lied. It's the correct path. Something else causing it. How did you fix it @t100n ? I don't think I understand what you've done?

**Comment by t100n** [comment]
I was doing requests to my server using the https://facebook.github.io/react-native/docs/network.html#fetch module, which causes the behaviour described. I switched to  http://visionmedia.github.io/superagent and the issue went away.
Don't know if the other example in the docs (XMLHttpRequest) works, but since it sits on top of the networking apis of the device there's a chance it may also blow up.

```
var request = require('superagent');
request.post(REQUEST_URL).send(PARAMS).set(HEADERS).end(function(err, res) {
});
```

**Comment by MossP** [comment]
I see. Thanks for the heads up :)

**Comment by idibidiart** [comment]
Can anyone else confirm this problem exists with Fetch and or XMLHttpRequest in React Native?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/network-request-failed-for-pre-bundled-mainjsbundle

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
