### ISSUE TITLE
Text Input Sms code is showing on every input, and its showing already read codes.

### ISSUE THREAD

**Issue by branislavantic87** [facebook/react-native#30442]
Two different text inputs on different screens, second screen receive code via sms and we can populate code we get from message with textContentType="oneTimeCode", next step login everything ok. But

If I kill the app and start it again on first screen where I've declared textContentType="none", or what ever else, keyboard will always offer me last sms code received as sms and also on the second screen until new one is received. 

Is there a way to prevent this behaviour? I mean the real stuff would be to read just last message and present code to populate. I would call this a bug on textContentType prop.

**Comment by sangameshrently** [comment]
Don't pass textContentType prop to first screen text input

**Comment by branislavantic87** [comment]
> Don't pass textContentType prop to first screen text input

Tried, does not help.

**Comment by dulmandakh** [comment]
Sorry, RN issue tracker is not intended for developer support, but for RN issues
