### ISSUE TITLE
error reading node_modules/react-native/ReactCommon/yoga/yoga/Utils.cpp

### ISSUE THREAD

**Issue by Keith503** [facebook/react-native#30450]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Ran 'npx react-native init MatchStrat'. Sample application loaded correctly. Ran 'npx react-native run-ios' Unchanged sample application works correctly. Opened Xcode and tried to build app. Application failed with message: 

error reading '/Users/keithmoore/Desktop/MatchStrat/node_modules/react-native/ReactCommon/yoga/yoga/Utils.cpp

Deleted and reinstalled react-native and Xcode multiple times. Deleted Pods under IOS directory and reinstalled Pods. No success.  

 application Please provide a clear and concise description of what the bug is. Include screenshots if needed.
Please test using the latest React Native release to make sure your issue has not already been fixed: https://reactnative.dev/docs/upgrading.html

## React Native version:
Run `react-native info` in your terminal and copy the results here.
info Fetching system and libraries information...
(node:8301) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz
    Memory: 283.31 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 15.2.1 - /usr/local/bin/node
    Yarn: Not Found
    npm: 7.0.10 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    Android SDK:
      API Levels: 28, 30
      Build Tools: 30.0.1
      System Images: android-28 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 12.2/12B45b - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_265 - /usr/bin/java
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. npx react-native init MatchStrat
2. cd MatchStrat
3. npx react-native run-ios.      ---> Works correctly 
4. Start Xcode 
5. File Open - MatchStrat/iOS/MatchStrat.xcworkspace
6. Run Build                                ---> Build Fails 

error: error reading '/Users/keithmoore/Desktop/MatchStrat/node_modules/react-native/ReactCommon/yoga/yoga/Utils.cpp'
1 error generated. 

## Expected Results
Describe what you expected to happen.
Sample program to build and run in simulator like it does under 

## Snack, code example, screenshot, or link to a repository:
Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by ravirajn22** [comment]
Tested it as you said. It builds successfully using xcode. Post more info or search it online.

**Comment by dibyendu** [comment]
@Keith503 it looks like a permission issue.  `Security & Privacy` -> `Full Disk Access` -> Add Xcode to the list
