### ISSUE TITLE
Conflicting libc++_shared.so with 3rd party SDK causing crash on Android

### ISSUE THREAD

**Issue by chichoch** [facebook/react-native#30459]
## Description
I have an app using React native in which I added a 3rd party SDK: ArcGIS. 
They don't have a SDK for RN, so I'm using their native SDK's for iOS and Android. 

However, on RN 63.3, I get `assertion "terminating with uncaught exception of type std::bad_cast: std::bad_cast" failed` on Android when rendering the native View. 

In order to rule out any other cause, I've created a simple app using `react-native init`, installed the ArcGIS SDK for Android, 
added a simple implementation of the native `ViewManager` and imported it using Native UI-principles. 

I have tried the following without success:

- Removing Flipper
- Different options for packagingOptions in android/app/build.gradle (merge, pickFirst, exclude)
- Adding the flag android.bundle.enableUncompressedNativeLibs=false in gradle.properties
- Adding implementation 'com.facebook.soloader:soloader:0.9.0+' in app/build.gradle

## React Native version:

```
System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 83.60 MB / 32.00 GB
    Shell: 3.0.2 - /usr/local/bin/fish
  Binaries:
    Node: 12.9.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.10.2 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6858069
    Xcode: 12.2/12B45b - /usr/bin/xcodebuild
  Languages:
    Java: javac 14 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.3 => 0.63.3
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce

1. Create new react native app using `react-native init MyApp`
2. Add the following in `android/build.gradle`:

```
allprojects {
  ...
  repositories {
    ...
    // *** ADD ***
    maven {
      url 'https://esri.bintray.com/arcgis'
    }
```
3. Add implementation for ArcGIS in `android/app/build.gradle`

```
dependencies {
  ...
  // *** ADD ***
  implementation 'com.esri.arcgisruntime:arcgis-android:100.9.0'
```
4. Update the android manifest to indicate the app uses OpenGL 2.0 or above. In `android/app/src/main/AndroidManifest.xml` add the following:
```
<uses-permission android:name="android.permission.INTERNET" />
<uses-feature android:glEsVersion="0x00020000" android:required="true" />
```
5. Add the following files in `android/app/src/main/java/com/myapp/`: 

ESRIMapViewManager.java:

```
package com.myapp;

import android.util.Log;

import com.esri.arcgisruntime.mapping.ArcGISMap;
import com.esri.arcgisruntime.mapping.Basemap;
import com.esri.arcgisruntime.mapping.view.MapView;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.uimanager.SimpleViewManager;
import com.facebook.react.uimanager.ThemedReactContext;

public class ESRIMapViewManager extends SimpleViewManager<MapView> {
    public ESRIMapViewManager(ReactApplicationContext reactContext) {
    }

    @Override
    public String getName() {
        return "ESRIMapView";
    }

    @Override
    protected MapView createViewInstance(ThemedReactContext reactContext) {
        Log.i(getName(), "createViewInstance");

        MapView mapView = new MapView(reactContext); // TODO: or reactContext?
        createMap(mapView);
        return mapView;
    }

    private void createMap(MapView mapView) {
        Basemap.Type basemapType = Basemap.Type.STREETS_VECTOR;
        double latitude = 34.0270;
        double longitude = -118.8050;
        int levelOfDetail = 13;
        ArcGISMap map = new ArcGISMap(basemapType, latitude, longitude, levelOfDetail);
        
        mapView.setMap(map);
    }
}
```

ESRIMapViewModule.java:
```
package com.myapp;

import android.util.Log;

import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.bridge.ReactContextBaseJavaModule;
import com.facebook.react.bridge.ReactMethod;

public class ESRIMapViewModule extends ReactContextBaseJavaModule {
    private static ReactApplicationContext reactContext;

    ESRIMapViewModule(ReactApplicationContext context) {
        super(context);
        reactContext = context;
    }

    @Override
    public String getName() {
        return "ESRIMapView";
    }

    @ReactMethod
    public void boo(String message) {
        Log.i("ESRIMapView", message);
    }
}
```

ESRIMapViewPackage.java: 
```
package com.myapp;

import com.facebook.react.ReactPackage;
import com.facebook.react.bridge.NativeModule;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.uimanager.ViewManager;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public class ESRIMapViewPackage implements ReactPackage {
    @Override
    public List<ViewManager> createViewManagers(ReactApplicationContext reactContext) {
        List<ViewManager> viewManagers = new ArrayList<>();
        viewManagers.add(new ESRIMapViewManager(reactContext));
        return viewManagers;
    }

    @Override
    public List<NativeModule> createNativeModules(ReactApplicationContext reactContext) {
        return Collections.emptyList();
    }
}
```

6. Now we create a `ESRIMapView.js` in the root folder with the following content:
```
import { requireNativeComponent } from "react-native";

module.exports = requireNativeComponent("ESRIMapView");
```

7. Replace `App.js` with the following content: 

```
import React from 'react';
import {StyleSheet, View} from 'react-native';
import ESRIMapView from './ESRIMapView';

export default function App() {
  return (
    <View style={styles.container}>
      <ESRIMapView
        style={{
          ...StyleSheet.absoluteFillObject,
          height: undefined,
        }}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```

7. If we try to run the project now in Android studio, we get `More than one file was found with OS independent path 'lib/x86/libc++_shared.so'`, so we can add the following to `android/app/build.gradle`:

```
android {
    compileSdkVersion rootProject.ext.compileSdkVersion

    packagingOptions {
        pickFirst '**/libc++_shared.so' // Also tested merge 
    }
```

## Expected Results
The app shouldn't crash, but instead show a simple Map. 

## Snack, code example, screenshot, or link to a repository:
https://github.com/chichoch/testarcgis <- A repo containing all the changes from the description above.

**Comment by murtazabeans** [comment]
@chichoch Is there any update on this issue? Did you get the fix. I am also using a third party library and it is crashing with libc++.shared.so

**Comment by chernandezq** [comment]
I have the same issue, any updates?

**Comment by chichoch** [comment]
@murtazabeans @chernandezq I haven't tried it yet, but upgrading to react-native v0.64.0 and ArcGIS SDK v100.10.0 seems to fix the problem. (See https://github.com/facebook/react-native/issues/29377)

**Comment by chernandezq** [comment]
@chichoch I was testing upgrading to the latest version of RN but Here maps SDK don't work

**Comment by Zshay2203** [comment]
Hi @chichoch 
Yesterday I posted a suggested workaround in https://github.com/facebook/react-native/issues/29377 for the crashes/failures that are caused under versions >= 0.62 of React Native.
In order to test it, I downloaded your sample project from https://github.com/chichoch/testarcgis and tested it.

Putting the call: System.loadLibrary( "c++_shared"); at the first line of onCreate(), in class com.arcgisreactnative.MainApplication avoids the crash, which happens without it.

Will it be possible for you to review that?
Thanks
Shay

**Comment by chichoch** [comment]
Upgrading `react-native` to v0.64.1 (with help from https://react-native-community.github.io/upgrade-helper/) and upgrading the 3rd party to v100.10.0 was successful.

**Comment by Zshay2203** [comment]
> Upgrading `react-native` to v0.64.1 (with help from https://react-native-community.github.io/upgrade-helper/) and upgrading the 3rd party to v100.10.0 was successful.

Hi,
Not in the case of our product, which uses the same version of React Native.
Thanks
Shay

**Comment by chichoch** [comment]
@Zshay2203 
Sorry to hear that! 

I was hoping that `ndkVersion = "20.1.5948944"` that was added to `android/build.gradle` was a fix for this kinds of problems, but I haven't look into it deeper. 

I don't know what `System.loadLibrary("c++_shared")` really does, but I will keep it in mind if it's needed in future versions!

But I'll keep this issue closed for now, since the bug can't be reproduced with the latest versions of `react-native` and ArcGIS SDK.

**Comment by Zshay2203** [comment]
Hi @chichoch,

The call System.loadLibrary("c++_shared") issues a request to the JVM to explicitly  load the Native Shared Library libc++_shared.so to the app's memory.
This library, which holds the C++ code that fails and causes the exception/failures is usually loaded to the app's memory by the React code during its initialization phase.
My assumption is that the preliminary load of the library avoids the the changes RN's code does in library's code/data.

Thanks
Shay
