### ISSUE TITLE
Text ellipsizeMode="tail" break on iOS

### ISSUE THREAD

**Issue by 0x11-dev** [facebook/react-native#30458]
## React Native version:
System:
    OS: macOS 10.15.5
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 1.00 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.15.1 - ~/.nvm/versions/node/v14.15.1/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.1/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.9.0 - /Users/levin/.rvm/gems/ruby-2.6.3/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28, 29
      Build Tools: 23.0.1, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 27.0.3, 28.0.3, 29.0.2
      System Images: android-23 | Google APIs Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-Q | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 12.2/12B45b - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_131 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.3 => 0.63.3
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

```jsx
<Text numberOfLines={3} ellipsizeMode={'tail'}>
              {
                'Hello, world! 123123123\nHello, world!\nHello, world!\nHello, world!\nHello, world!\nHello, world!\n'
              }
</Text>
```
<img src="https://user-images.githubusercontent.com/7822875/99978404-dedece00-2de0-11eb-8043-38d1a8263079.png"  width=400/>

## Expected Results

Show ellip(…) after 3rd line like swift ui or android.

<img src="https://user-images.githubusercontent.com/7822875/99977838-2153db00-2de0-11eb-9932-8555a5dad273.png" width=400 />

## Snack, code example, screenshot, or link to a repository:

https://snack.expo.io/kYjuKbCh8

**Comment by 0x11-dev** [comment]
@shergin needs help here.

**Comment by kushagra21** [comment]
Happening for me too. Texts with line breaks are not being handled properly.

**Comment by fabriziobertoglio1987** [comment]
Do you still experience this issue? 

I have four years of experience maintaining facebook/react-native and I specialize in the Text and TextInput components. I currently have 58 [facebook/react-native PRs](https://github.com/facebook/react-native/pulls?q=is%3Apr+author%3Afabriziobertoglio1987+). 

If you still experience this issue, I will prepare a patched release with the fix.

Thanks a lot
