### ISSUE TITLE
How to pass and use data from react native to native android or ios?

### ISSUE THREAD

**Issue by hanaechahid** [facebook/react-native#30455]
Hello everyone, I want to pass some data form react native component to native module for both android and ios.

How can I do that?

thank you,

## Development environment
React Native Environment Info:
    System:
      OS: macOS 10.15.4
      CPU: (4) x64 Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz
      Memory: 348.31 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.18.1 - /usr/local/opt/node@10/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/opt/node@10/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
      Android SDK:
        API Levels: 23, 25, 26, 27, 28, 29
        Build Tools: 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.3, 29.0.2
        System Images: android-28 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.0 => 0.59.0

**Comment by ravirajn22** [comment]
Check articles under section https://reactnative.dev/docs/native-modules-android and https://reactnative.dev/docs/native-modules-ios

**Comment by hanaechahid** [comment]
hey @ravirajn22, I already checked this, I know how to pass data from native module to react native but from react native to native module no, is not described on the doc

**Comment by ravirajn22** [comment]
Export a native method which takes the data you want from JS. Call that method from JS.

Do whatever you want to do with the data inside your native method.
