### ISSUE TITLE
Text component is cutting of text with custom font [IOS]

### ISSUE THREAD

**Issue by furkanuzundev** [facebook/react-native#30463]
Hello, the custom font I added to my application does not give the output I want in IOS.The custom font is 'Futura Std Medium"

## React Native version:
 "react-native": "0.63.3",

<img width="114" alt="Screen Shot 2020-11-24 at 01 56 20" src="https://user-images.githubusercontent.com/30953070/100024848-a1863a80-2df8-11eb-84d9-c23f3ac44ee4.png">

**Comment by ravirajn22** [comment]
Add a simple github project that can reproduce this issue.

**Comment by MoOx** [comment]
You probably need to just augment line-height.

**Comment by Nargle30** [comment]
Hello, after react-native update from 0.61.0 to 0.63.4 some of my texts look the same (cropped on the bottom).
Increasing line-height helps.

**Comment by furkan-uzun** [comment]
Hello, when we use a custom text, this problem usually occurs. It seems that there is no solution other than using 'line-height'.

**Comment by fabriziobertoglio1987** [comment]
Do you still experience this issue? 

I have four years of experience maintaining facebook/react-native and I specialize in the Text and TextInput components. I currently have 58 [facebook/react-native PRs](https://github.com/facebook/react-native/pulls?q=is%3Apr+author%3Afabriziobertoglio1987+). 

If you still experience this issue, I will prepare a patched release with the fix.

Thanks a lot
