### ISSUE TITLE
Keyboard focus (from a physical keyboard) won't enter TextInput fields on Tab/Shift+Tab in Android

### ISSUE THREAD

**Issue by NatPri** [facebook/react-native#30464]
## Description
On Android devices, when other focusable controls (such as Buttons) are adjacent to a TextInput component, and a physical keyboard is used to interact with the app (e.g. via bluetooth or USB connection), keyboard focus will stop at the focusable element before the TextInput when tabbing or at the one after the TextInput when shift-tabbing.

## React Native version:
```
System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
    Memory: 13.44 GB / 31.94 GB
  Binaries:
    Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowAllTrustedApps: Enabled
  IDEs:
    Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6626763
    Visual Studio: 15.9.28307.518 (Visual Studio Enterprise 2017)
  Languages:
    Java: Not Found
    Python: 2.7.11 - C:\Python27\python.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: https://github.com/expo/react-native/archive/sdk-39.0.4.tar.gz => 0.63.2
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Using the Snack below under Android (tested on Pixel 3 with Android 11)

1. Connect a physical keyboard to the Android device, either using USB or Bluetooth. If using an emulator, you may need to configure it to send keyboard shortcuts to the virtual device; I've had better luck reproing on physical devices, though.
2. Press Tab and Shift+Tab to move the focus between the Buttons and TextInput
3. Observe that pressing Tab when focused on the element before the TextInput or Shift+Tab on the element after the TextInput does not move the focus to the TextInput. Additionally, if you tap to activate the TextInput, you cannot press Tab/Shift+Tab to leave the TextInput.

## Expected Results
The TextInput should participate in the keyboard tab order. Users may use a physical keyboard for accessibility reasons.

## Snack, code example, screenshot, or link to a repository:
https://snack.expo.io/dg2qxBBue

**Comment by NatPri** [comment]
This has been sitting for a few months now, is there anyone that can comment on what sort of timeline we could expect on this bug?

**Comment by fabriziobertoglio1987** [comment]
https://developer.android.com/training/keyboard-input/navigation#Tab

>All interactive widgets provided by the Android framework (such as Button and EditText) are focusable. This means users can navigate with control devices such as a D-pad or keyboard and each widget glows or otherwise changes its appearance when it gains input focus.

https://reactnative.dev/docs/building-for-tv
>InputText components do not work for now (i.e. they cannot receive focus).

The reason here
https://github.com/facebook/react-native/pull/16500#issuecomment-629285638

>EDIT: It is possible to wrap inputs in Touchable elements and do onFocus={() => textInputRef.current.focus()}

which means you need to add the implementation explained here https://reactnative.dev/docs/building-for-tv
and wrap you TextInput in touchables

**Comment by kriti18singh** [comment]
@NatPri Were you able to get this working? I tried the workaround but the onFocus does not fire while tabbing when the TextInput is wrapped in a Touchable.

**Comment by kriti18singh** [comment]
@NatPri were you able to get this working?

**Comment by kriti18singh** [comment]
@fabriziobertoglio1987 the workaround does not seem to work. Wrapping the TextInput in a Touchable and then tabbing never fires the onFocus of the touchable. Tried this a couple of times but it didn't work. onPress of the TouchableHighlight and TouchableNativeFeedback is fired but never onFocus. Also, I have a button below the text input, if the current keyboard focus is on the button - doing shift + tab does not take it back to the input (touchable wrapped input did not work here). Are you aware of any other workarounds?

**Comment by msgharpu** [comment]
> Input in a



> @fabriziobertoglio1987 the workaround does not seem to work. Wrapping the TextInput in a Touchable and then tabbing never fires the onFocus of the touchable. Tried this a couple of times but it didn't work. onPress of the TouchableHighlight and TouchableNativeFeedback is fired but never onFocus. Also, I have a button below the text input, if the current keyboard focus is on the button - doing shift + tab does not take it back to the input (touchable wrapped input did not work here). Are you aware of any other workarounds?

Can we add a dummy button and a textinput within the Touchable wrapper? May be focus is not happening as TextInput is the only control within wrapper and for that taking focus is explicitly disbaled [here](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactEditText.java#L271)

**Comment by RyanCommits** [comment]
I found a workaround for my project:

Create a new `InputField` component that wraps the existing input field with a `Pressable`. This will allow you to focus on the input if the user hits `Enter` on their keyboard. `Pressable` is invisible to the user, and at least in our application, has the exact same experience when using touch interactions.

Next, only render this solution on Android.

Not the exact same interaction because the user needs one extra interaction to focus on the input, but at least they can get through our application now.
```
export const InputField = forwardRef<TextInput>((props, ref) => {
  const inputRef = useRef<TextInput>(null);

  ref = ref || inputRef;

  return (
    <Pressable
      onPress={() => {
        if (ref && typeof ref !== 'function' && ref.current) {
          ref.current.focus();
        }
      }}
    >
      <InputFieldIOS ref={ref} {...props} />
    </Pressable>
  );
});
```

```
import { InputField as InputFieldIos } from './InputField.ios';
import { InputField as InputFieldAndroid } from './InputField.android';

export const InputField = Platform.select({
  ios: InputFieldIos,
  android: InputFieldAndroid,
})!;
```

**Comment by kriti18singh** [comment]
@RyanCommits Can you shift+tab from button to textinput as well? meaning backward navigation

**Comment by Jokerwolf** [comment]
Hey everyone, this issue is still repro unfortunately. It seems like there is no other way, but wrapping TextInput and handling press events. Could you please give us some feedback or estimations please?

**Comment by ShivamJoker** [comment]
I am also having the same issue can't focus on text input

**Comment by nedgip** [comment]
Hey everyone, 

I just wanted to add some extra feedback for this issue as it is still a real problem for the team that I'm working with, who are trying to build accessible, WCAG compliant forms using React Native that work on Android.

Wrapping the `<TextInput>` in a `<Pressable>` does not work well for people who use a screen reader and an external keyboard together. 

From our experience, to make that combination work you need to add an `accessibilityLabel` to the `<Pressable>` wrapping the `<TextInput>`, which then adds a redundant focus point for screen reader users who don't use a keyboard and navigate by swipe or by touch. Has anyone else noticed this and found a good solution for it?

A lot of auditors would fail this against 2.4.3 Focus order, as the redundant, additional focus point seems unnecessary / illogical if you don't know the reasons for it being there. It would also fail 4.1.2 Name, Role, Value as the `<Pressable>` is focusable and interactive but doesn't have an `accessibilityRole`. If you add `accessibilityRole="button"` to it you're going to have a button wrapping a text field which is not great.

Most developers probably won't even realise it's an issue though, and will miss adding an `accessibilityLabel` to it completely, in which case they'll have a critical issue causing screen reader users who use an external keyboard to not hear anything when the `<Pressable>` receives focus using the keyboard.

Another issue with the Pressable work around is that the `<TextInput>` is only keyboard accessible using arrow keys and not the Tab key which is standard keyboard navigation. I wouldn't fail that against 2.1.1 Keyboard but it is unexpected and may cause some confusion, arrow keys are fairly discoverable but most keyboard users expect to be able to focus using the Tab key.

Is anyone working on a fix for the keyboard accessibility of the `<TextInput>` component on Android?

**Comment by pandu-supriyono** [comment]
> I found a workaround for my project:
> 
> Create a new `InputField` component that wraps the existing input field with a `Pressable`. This will allow you to focus on the input if the user hits `Enter` on their keyboard. `Pressable` is invisible to the user, and at least in our application, has the exact same experience when using touch interactions.
> 
> Next, only render this solution on Android.
> 
> Not the exact same interaction because the user needs one extra interaction to focus on the input, but at least they can get through our application now.
> 
> ```
> export const InputField = forwardRef<TextInput>((props, ref) => {
>   const inputRef = useRef<TextInput>(null);
> 
>   ref = ref || inputRef;
> 
>   return (
>     <Pressable
>       onPress={() => {
>         if (ref && typeof ref !== 'function' && ref.current) {
>           ref.current.focus();
>         }
>       }}
>     >
>       <InputFieldIOS ref={ref} {...props} />
>     </Pressable>
>   );
> });
> ```
> 
> ```
> import { InputField as InputFieldIos } from './InputField.ios';
> import { InputField as InputFieldAndroid } from './InputField.android';
> 
> export const InputField = Platform.select({
>   ios: InputFieldIos,
>   android: InputFieldAndroid,
> })!;
> ```

Hi @RyanCommits, have you tested how this translates for users dependent on screen readers?

**Comment by RyanCommits** [comment]
@pandu-supriyono I'm no longer working on the application that had this issue, and haven't looked at it for a while. Best of luck, this is a tough one.

**Comment by ArturKalach** [comment]
> > I found a workaround for my project:
> > Create a new `InputField` component that wraps the existing input field with a `Pressable`. This will allow you to focus on the input if the user hits `Enter` on their keyboard. `Pressable` is invisible to the user, and at least in our application, has the exact same experience when using touch interactions.
> > Next, only render this solution on Android.
> > Not the exact same interaction because the user needs one extra interaction to focus on the input, but at least they can get through our application now.
> > ```
> > export const InputField = forwardRef<TextInput>((props, ref) => {
> >   const inputRef = useRef<TextInput>(null);
> > 
> >   ref = ref || inputRef;
> > 
> >   return (
> >     <Pressable
> >       onPress={() => {
> >         if (ref && typeof ref !== 'function' && ref.current) {
> >           ref.current.focus();
> >         }
> >       }}
> >     >
> >       <InputFieldIOS ref={ref} {...props} />
> >     </Pressable>
> >   );
> > });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > import { InputField as InputFieldIos } from './InputField.ios';
> > import { InputField as InputFieldAndroid } from './InputField.android';
> > 
> > export const InputField = Platform.select({
> >   ios: InputFieldIos,
> >   android: InputFieldAndroid,
> > })!;
> > ```
> 
> Hi @RyanCommits, have you tested how this translates for users dependent on screen readers?

Hello @pandu-supriyono 
I would say it's a good solution, but....
If I remember properly there still can be a problem with pressing `shift+tab` when you focused.

For old arch I hacked this by overriding `ReactEditText`:

```
///RCTEditText.java

public class RCTEditText extends ReactEditText {
    static final int ENTER_KEY_CODE = KeyEvent.KEYCODE_ENTER;
    static final int MULTILINE_TYPE = EditorInfo.TYPE_TEXT_FLAG_MULTI_LINE;

    public RCTEditText(Context context) {
        super(context);
    }

    private boolean isKeyHandled(int keyCode) {
        boolean isMultiline = (this.getInputType() & MULTILINE_TYPE) == 0;
        return keyCode != ENTER_KEY_CODE
                || !isMultiline
                || !this.getBlurOnSubmit();
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (this.isKeyHandled(keyCode)) {
            return super.onKeyDown(keyCode, event);
        }
        return false;
    }

    @Override
    public boolean onKeyUp(int keyCode, KeyEvent event) {
        if (this.isKeyHandled(keyCode)) {
            return super.onKeyUp(keyCode, event);
        }
        return false;
    }

    @Override
    public boolean requestFocus(int direction, Rect previouslyFocusedRect) {
        if (direction == View.FOCUS_FORWARD || direction == View.FOCUS_BACKWARD) {
            this.requestFocusFromJS();
        }
        return super.requestFocus(direction, previouslyFocusedRect);
    }
}

```

Extending

```
class RCTEditTextManager extends ReactTextInputManager {
    // Copied react native text input manager, just copy pasted
    @Override
    public ReactEditText createViewInstance(ThemedReactContext context) {
        //Changed this line
        ReactEditText editText = new RCTEditText(context);
        int inputType = editText.getInputType();
        editText.setInputType(inputType & -131073);
        editText.setReturnKeyType("done");
        return editText;
    }
}
```
And declare
```
public class RCTEditTextPackage implements ReactPackage {
    @NonNull
    @Override
    public List<NativeModule> createNativeModules(@NonNull ReactApplicationContext reactContext) {
        return Collections.emptyList();
    }

    @NonNull
    @Override
    public List<ViewManager> createViewManagers(@NonNull ReactApplicationContext reactContext) {
        List<ViewManager> viewManagers = new ArrayList<>();
        viewManagers.add(new RCTEditTextManager());
        return viewManagers;
    }
}

```

And don't forget to add

```
//MainApplication.java|

        @Override
        protected List<ReactPackage> getPackages() {
          @SuppressWarnings("UnnecessaryLocalVariable")
          List<ReactPackage> packages = new PackageList(this).getPackages();
            packages.add(new RCTEditTextPackage());

```
This way we fixed it from native side overiding origin RN TextEdit.
Sorry for sharing it a little bit late(

**Comment by nedgip** [comment]
> Hi @RyanCommits, have you tested how this translates for users dependent on screen readers?

Hi @pandu-supriyono

 I've tested the recommended workaround (wrap the text input in a pressable and then set focus on it) with TalkBack.

When using TalkBack, navigating by swiping left and right, there is no real difference from navigating a native android text field. So all good there, it works as expected. 

However, for external keyboard users, who also use a screen reader there is a problem, in that focus moves to the pressable and nothing is announced. 

To address this, we had to add an accessibilityLabel as well as the value and associated accessibilityHint text to the pressable, so that it mirrors the announcement of the <TextInput>. This way, external keyboard users who also screen reader can navigate the fields and hear equivalent information. 

When you add the accessibilityLabel to the pressable it makes it discoverable to screen reader users. So each field effectively receives focus twice when swiping with TalkBack. It's an annoying trade off, but we felt the additional focus points were a less critical issue than the label and value of the field not being announced at all.

**Comment by ArturKalach** [comment]
There are a tricky fix from the native side: https://github.com/ArturKalach/react-native-a11y/blob/master/docs/AndroidInput.md

![android-example](https://user-images.githubusercontent.com/112642862/235889721-ff5b208f-9562-44c4-9973-91b4d51f1f34.gif)
