### ISSUE TITLE
Crash: RN 0.60:  Maximum call stack size exceeded

### ISSUE THREAD

**Issue by jaspreet11** [facebook/react-native#30460]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Getting a crash with logs as follows:
com.facebook.react.common.c: Maximum call stack size exceeded, stack:
10-29 null:null:null.624 16721 16888 E AndroidRuntime: /Users/builduser/myagent/_work/36/s/Shared/kaizalaS/node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-prod.js:1862:length
10-29 null:null:null.624 16721 16888 E AndroidRuntime: /Users/builduser/myagent/_work/36/s/Shared/kaizalaS/node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-prod.js:1852:null
10-29 null:null:null.624 16721 16888 E AndroidRuntime: /Users/builduser/myagent/_work/36/s/Shared/kaizalaS/node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-prod.js:5182:scheduleCallbackForRoot
10-29 null:null:null.624 16721 16888 E AndroidRuntime: /Users/builduser/myagent/_work/36/s/Shared/kaizalaS/node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-prod.js:6814:callback
10-29 null:null:null.624 16721 16888 E AndroidRuntime: /Users/builduser/myagent/_work/36/s/Shared/kaizalaS/node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-prod.js:7011:uninitializedFiber
10-29 null:null:null.624 16721 16888 E AndroidRuntime: /Users/builduser/myagent/_work/36/s/Shared/kaizalaS/node_modules/react-native/Libraries/ReactNative/renderApplication.js:65:d
10-29 null:null:null.624 16721 16888 E AndroidRuntime: /Users/builduser/myagent/_work/36/s/Shared/kaizalaS/node_modules/react-native/Libraries/ReactNative/AppRegistry.js:111:componentProvider
10-29 null:null:null.624 16721 16888 E AndroidRuntime: /Users/builduser/myagent/_work/36/s/Shared/kaizalaS/node_modules/react-native/Libraries/ReactNative/AppRegistry.js:212:setActiveScene
10-29 null:null:null.624 16721 16888 E AndroidRuntime: /Users/builduser/myagent/_work/36/s/Shared/kaizalaS/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:391:null
10-29 null:null:null.624 16721 16888 E AndroidRuntime: /Users/builduser/myagent/_work/36/s/Shared/kaizalaS/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:109:null
10-29 null:null:null.624 16721 16888 E AndroidRuntime: 

The issue is being seen on Android version <= 9.0.

## React Native version:
RN 0.60

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.
Not reproducible locally on debug build. Lots of crashes seen on customer side.

## Expected Results
No crash should be seen.

## Snack, code example, screenshot, or link to a repository:
Can not be provided

**Comment by ravirajn22** [comment]
Near impossible to debug with the stack trace you provided.

One of the reasons why `Maximum call stack size exceeded` happens is when there is infinite loop call. Check your methods and render functions, if there might be any case for the same. Looks more of a logic within your app or third party library you use.

**Comment by dulmandakh** [comment]
Sorry, the issue seems to be caused by your code or third-party modules you use.
