### ISSUE TITLE
App freezes when coming from background in RN 0.63.3

### ISSUE THREAD

**Issue by luco** [facebook/react-native#30462]
I'm trying to debug this app for days and can't get an answer. The current behavior is this:

 1. I launch the app, the app works smoothly. 
2. I put the app on the background. 
3. After 5-10 minutes, after switching with other apps, I get back to the app, but now when I try to change the tabs and etc, it freezes.

**NOTE**: ScrollViews still working when the rest of the app is frozen.

When the app is frozen, the CPU usage goes to ~100-130%. I managed to find that is the javascript:

[![enter image description here][1]][1]

Things I already tried:

1 - Profile the app through Instruments (can't find an answer):

[![enter image description here][2]][2]

2 - Removing several code to check.
3 - Removing a few modules.

I can't figure out what is freezing the app. Any help is welcome.

Thanks!

  [1]: https://i.stack.imgur.com/CZM4Z.png
  [2]: https://i.stack.imgur.com/aqlBF.png

**Comment by luco** [comment]
System:
    OS: macOS 10.15.7
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Memory: 108.77 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.22.1 - /usr/local/opt/node@10/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.6 - /usr/local/opt/node@10/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6858069
    Xcode: 12.2/12B45b - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.1 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.3 => 0.63.3
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by luco** [comment]
Last Instruments call:
![image](https://user-images.githubusercontent.com/246373/100016595-6bc16180-2db8-11eb-90ca-0ae2f6aa1e33.png)

**Comment by fangasvsass** [comment]
same issues ， Have you found a solution ?@luco

**Comment by luco** [comment]
@fangasvsass Not yet. I'm rebuilding the app from the ground trying to find the issue. :/

**Comment by chrisglein** [comment]
@luco and @fangasvsass Can either of you share the app source as a means to share a repro? Getting a repro for this is going to be the key next step for it to become actionable by anyone else.

Is this on Android, iOS, or both?

**Comment by fangasvsass** [comment]
> @luco and @fangasvsass Can either of you share the app source as a means to share a repro? Getting a repro for this is going to be the key next step for it to become actionable by anyone else.
> 
> Is this on Android, iOS, or both?

iOS ,  certain chance to happen , Especially when the network is slow, maybe the Image request caused  maybe not

**Comment by luco** [comment]
Managed to found the issue. It was a function that handled Apollo subscriptions that I made.

**Comment by remcoabalain** [comment]
> Managed to found the issue. It was a function that handled Apollo subscriptions that I made.

@luco seems that we encountering the same issue, and we're using apollo as well. Could you enlighten what you fixed with the function which handled Apollo Subs?

**Comment by franck-nadeau** [comment]
> Managed to found the issue. It was a function that handled Apollo subscriptions that I made.

We are seeing this issue in our app too. 

@luco can you please elaborate on what you had to do in order to fix this?

**Comment by luco** [comment]
@remcoabalain @franck-nadeau Yes, sorry guys. I was using a hook to manage the Apollo Subscriptions whenever users come from background, but it was trying to refetch all the queries in the same time, causing the UI laggy performance.

So I decided to try a different solution:

```
export default function useReconnectingSubscription(query, variables) {

  const [retrySwitch, setRetrySwitch] = useState(true);
  const [data, setData] = useState();
  const client = useApolloClient();
  
  useEffect(() => {

    const observer = client.subscribe({
      query, 
      variables,
      fetchPolicy: 'no-cache',
    });

    const subscription = observer.subscribe(
      ({ data }) => {
        setData(data ? data : undefined);
      },
      (error) => {
        if (error && subscription.closed) {
          setTimeout(() => {
            // retry subscription connection after 10s
            setRetrySwitch(!retrySwitch);
          }, 10000);
        }
      },
    );
    return () => subscription.unsubscribe();

  }, [retrySwitch]);

  return data;
}
```

In this case, the hook tries to reconnect every 10 seconds. You should set it as you need.
