### ISSUE TITLE
Problems with rendering of the screens

### ISSUE THREAD

**Issue by franklinbinauraldev** [facebook/react-native#30476]
Best regards

## Description
The next problem is a bad rendering, at a visual level it is quite remarkable, I realized that it only happens when requests are made to bring the images, if I remove the Image component, no such thing happens. It only happens with Android.

## React Native version:
```
npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2
```

## Steps To Reproduce
- The instant you access a screen
- An image component is called and makes the request

## Expected Results
Rendering the normal views
![screenshot-2020-11-25_15 35 18 945](https://user-images.githubusercontent.com/69120282/100273898-eb277000-2f33-11eb-8613-6044ae0e3f04.png)

## Snack, code example, screenshot, or link to a repository:
Update the project from 0.62 to 0.63 I have to mention. 
Apparently the previous view also overlaps
As you can see 
![screenshot-2020-11-25_15 34 46 478](https://user-images.githubusercontent.com/69120282/100273833-cd5a0b00-2f33-11eb-97ae-115ba15c41d4.png)

**Comment by pedrocardoz0** [comment]
Hello Frank, could you link your code? Just to make sure that you are using correctly all the components.

**Comment by riadhriadh** [comment]
be careful if you have to use  position absolute
