### ISSUE TITLE
FlatList is empty when using removeClippedSubviews

### ISSUE THREAD

**Issue by nimabrownlee** [facebook/react-native#30473]
## Description
When using `removeClippedSubviews` `FlatList` is empty after the first render. So lets say I navigate to another screen and go back to the `FlatList` screen it shows up as empty until touched/scrolled.

## React Native version:
```
System:
    OS: macOS 11.0.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 55.80 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.5.0 - ~/.nvm/versions/node/v14.5.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v14.5.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6858069
    Xcode: 12.2/12B45b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.7 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: ~0.63.3 => 0.63.3 
    react-native-macos: Not Found

```

## Steps To Reproduce
Its easily reproduced by just adding `removeClippedSubviews` to `FlatList`.

## Expected Results
It should not be empty. I've looked at similar issues and some has used `initialNumToRender` or `extraData` but neither has worked out for me. Also I think this is a bug when using **react-navigation** but I am not sure where the root cause of the issue is. 

## Snack, code example, screenshot, or link to a repository:
It's easily reproduced so I'll leave this empty.

**Comment by aweffr** [comment]
I have this issue too

**Comment by douglasrosa0110** [comment]
I have this issue too but **JUST on IOs in RELEASE profile**.
IOs 13.6, iPhone 7, react-native 0.61.5

**Comment by popejrh19** [comment]
Unsubscribe

William Pope Jr
