### ISSUE TITLE
StyleSheet.create

### ISSUE THREAD

**Issue by yuriiKluban** [facebook/react-native#30471]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
I'm trying to use StyleSheet.create with typescript.  I want to see error if using incorrect styles. 
My code example: 
[https://prnt.sc/vpo1uq](url)

As you can see i didn't get any error when i used TextStyle inside ViewStyle object;
When I went to the file with the typing of the create method, I saw that it returns no specific type T, but one of ... because of this, we do not receive typing errors.
[https://prnt.sc/vpo4hx](url)

## React Native version:
"react-native": "0.62.2"

## Expected Results
error like this
[https://prnt.sc/vpo7kw](url)

**Comment by dulmandakh** [comment]
@types/react-native is separate project at https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-native, and please make sure that you install same version as your RN app
