### ISSUE TITLE
If anyone is facing the same issue, because of the "http" just add `android:usesCleartextTraffic="true"` to the Manifest, and you should be good.

### ISSUE THREAD

**Issue by tirthpatel1** [facebook/react-native#30474]
If anyone is facing the same issue, because of the "http" just add `android:usesCleartextTraffic="true"` to the Manifest, and you should be good.

_Originally posted by @gabrielrra in https://github.com/facebook/react-native/issues/24361#issuecomment-530605230_

**Comment by kaushikwavhal** [comment]
This should be true by default when you create a new project with react-native-cli so that this upgrade helper will include it.
https://react-native-community.github.io/upgrade-helper/?from=0.59.9&to=0.63.3

**Comment by dulmandakh** [comment]
It's enabled in Debug mode, but not in Release. I must say that not everyone is facing the issue, and secure by default should be the principle.
