### ISSUE TITLE
react-native info; SDK location not found, but it exists in the path

### ISSUE THREAD

**Issue by anilsamuel** [facebook/react-native#30487]
This issue (https://github.com/facebook/react-native/issues/21105) been reported earlier but closed due to inctivity

## Description
[anthos@Rennys-MBP] ␉uname -a && env | grep -i android && react-native  info
Darwin Rennys-MBP 20.1.0 Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:11 PDT 2020; root:xnu-7195.50.7~2/RELEASE_X86_64 x86_64
ANDROID_HOME=/Users/anthos/Library/Android/sdk
PATH=/Users/anthos/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/anthos/Library/Android/sdk/emulator:/Users/anthos/Library/Android/sdk/tools:/Users/anthos/Library/Android/sdk/platform-tools:/Users/anthos/Library/Python/2.7/bin
info Fetching system and libraries information...
(node:91735) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
System:
    OS: macOS 11.0.1
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 199.08 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 15.2.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.0.10 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.2/12B45b - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.1 - /Users/anthos/bin/javac
    Python: 3.7.9 - /Users/anthos/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## React Native version:
Run `react-native info` in your terminal and copy the results here.
See above

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.
See above

## Expected Results
Android SDK: /Users/anthos/Library/Android/sdk

## Snack, code example, screenshot, or link to a repository:
N/A

**Comment by dulmandakh** [comment]
Hey, RN needs your help in finding Android SDK and it's done by setting ANDROID_HOME environment variable. Please see https://developer.android.com/studio/command-line/variables

**Comment by anilsamuel** [comment]
You missed the fact that it is set as

ANDROID_HOME=/Users/anthos/Library/Android/sdk

**Comment by anilsamuel** [comment]
Please reopen if it's still an issue

**Comment by dulmandakh** [comment]
Also it looks like an Expo project, please file an issue at their tracker
