### ISSUE TITLE
react-native init> yarn add expo> expo start issues

### ISSUE THREAD

**Issue by anilsamuel** [facebook/react-native#30486]
I am a newbie with react native; trying to setup a react native project with expo.

## Description
After init, both run-ios and run-android worked as expected.
Added expo using yarn; expo start failed and prompted to add .expo to app.json.
Subsequent expo start failed with '"main" has not been registered' error; executed 'expo upgrade'
Subsequent expo start report no error but the app is showing a white screen on both simulator and device.

## React Native version:
Run `react-native info` in your terminal and copy the results here.
info Fetching system and libraries information...
(node:89924) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
System:
    OS: macOS 11.0.1
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 358.12 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 15.2.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.0.10 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.2/12B45b - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.1 - /Users/anthos/bin/javac
    Python: 3.7.9 - /Users/anthos/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. react-native init HelloWorld
2. react-native run-ios
3. react-native run-android
4. yarn add expo
5. expo start >> '"main" has not been registered' error
6. expo upgrade
7. expo start >> no errors reported but only a white screen

## Expected Results
The default app screen created by react-native init

## Snack, code example, screenshot, or link to a repository:
https://snack.expo.io/@asamuel_arcl/fascinated-chocolate

**Comment by dulmandakh** [comment]
It looks like an Expo issue, please file an issue at Expo.
