### ISSUE TITLE
Appearance issue

### ISSUE THREAD

**Issue by chukhlov** [facebook/react-native#30484]
React-native Appearance has some issue on background mode.
Here is an video example how to reproduce the bug in the app [https://ru.files.fm/u/x5uzfjqtb#/view/swr72wr5p](https://ru.files.fm/u/x5uzfjqtb#/view/swr72wr5p)

Appearance listener will change the colorScheme value to "light" when app is in background mode and never back to dark.

```
useEffect(() => {
    const listener = ({colorScheme}: any) => {
      setIsDarkMode(colorScheme === 'dark');
    };
    Appearance.addChangeListener(listener);

    return () => {
      Appearance.removeChangeListener(listener);
    };
  }, []);
```

**Comment by Belgin-Android** [comment]
@chukhlov  More Information Needed

**Comment by jason0x43** [comment]
I have experience something similar using RN 0.63.4 on iOS 14.4. The problem appears to be with the value passed to the Appearance listener.

This is unreliable for me on iOS; the change listener will sometimes receive the incorrect color scheme when the app is restored from background mode, such as by tapping the "back" link in the upper left of the screen:

```js
useEffect(() => {
    const listener = ({colorScheme}: any) => {
      setIsDarkMode(colorScheme === 'dark');
    };
    Appearance.addChangeListener(listener);

    return () => {
      Appearance.removeChangeListener(listener);
    };
  }, []);
```

This, however, always seems to work:

```js
useEffect(() => {
    const listener = () => {
      setIsDarkMode(Appearance.getColorScheme() === 'dark');
    };
    Appearance.addChangeListener(listener);

    return () => {
      Appearance.removeChangeListener(listener);
    };
  }, []);
```

The `useColorScheme` hook also seems to work reliably (and generally simpler to use than a manually managed Appearance listener).

**Comment by 1111mp** [comment]
I also encountered the same problem.
```
React.useEffect(() => {
    const _subscription = ({colorScheme}: Appearance.AppearancePreferences) => {
      console.log(colorScheme);
      console.log(Appearance.getColorScheme());
      stores.userStore.setAppTheme(colorScheme!);
    };

    Appearance.addChangeListener(_subscription);

    return () => {
      Appearance.removeChangeListener(_subscription);
    };
  }, []);
```
The phone is set to dark mode. When my app switches to the background, it will trigger a listener.The colorScheme parameter of the listener method prints light, while the one obtained by Appearance.getColorScheme() is dark.
https://user-images.githubusercontent.com/31227919/117095257-771dad80-ad98-11eb-97d8-929b15d8f611.mov

**Comment by ouabing** [comment]
Same issue like what @1111mp described. `Appearance.addChangeListener` will receive a wrong theme when app goes back to foreground.

react-native: 0.64.1

**Comment by ThanhNguyen140797** [comment]
> Same issue like what @1111mp described. `Appearance.addChangeListener` will receive a wrong theme when app goes back to foreground.
> 
> react-native: 0.64.1

same issue
