### ISSUE TITLE
TextInput - How can I change the keyboard language dynamically

### ISSUE THREAD

**Issue by AliRehman7141** [facebook/react-native#30482]
I want to change the keyboard language on TextInput focus change

## Description
I have two TextInput fields one for the username that must be in English and the second input is for the name that will take the name in Arabic so here I need to switch the keyboard language according to the focused input.

## React Native version:
System:
    OS: macOS 11.0.1
    CPU: (4) x64 Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
    Memory: 138.66 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.18.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.0.10 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    Android SDK:
      API Levels: 23, 26, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2
      System Images: android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.2/12B45b - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_275 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by dulmandakh** [comment]
Sorry, this issue tracker is for RN issues, not developer support. Please see https://reactnative.dev/docs/handling-text-input and https://reactnative.dev/docs/textinput. Or you can create a PR to add this feature if possible.

**Comment by Spark-Cybel** [comment]
@AliRehman7141 Did you found any way to do that?

**Comment by AliRehman7141** [comment]
@Spark-Cybel No, I didn't get any solution for this.
