### ISSUE TITLE
Linking does not work on Android 11

### ISSUE THREAD

**Issue by cx5168** [facebook/react-native#30497]
environment：
System:
    OS: Windows 10 10.0.17134
    CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
    Memory: 8.88 GB / 15.93 GB
  Binaries:
    Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.12.3 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 23.0.1, 23.0.3, 25.0.1, 25.0.2, 26.0.1, 26.0.3, 27.0.3, 28.0.1, 28.0.2, 28.0.3, 29.0.2, 29.0.3, 30.0.2
      System Images: android-23 | Intel x86 Atom, android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-25 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom_64, android-26 | Intel x86 Atom, android-26 | Intel x86 Atom_64, android-26 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom_64, android-26 | Google Play Intel x86 Atom, android-27 | Intel x86 Atom, android-27 | Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.4 => 0.61.4
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native: 0.63.3

source:
Linking.canOpenURL(url).then((supported) => {
      if (supported) {
        return Linking.openURL(url);
      }
    }).catch();

question:
Does not work on Android 11

help:
Any way solve it?

**Comment by TheGameNewWorldOrder** [comment]
Same issue, canOpenURL returns false

**Comment by cx5168** [comment]
Linking.canOpenURL well done on react-native0.59.9, react-native0.63.4.
react-native0.61.4 have a bug.

**Comment by nlaitanatix** [comment]
I have react-native@0.63.4 and still not working

**Comment by tudormarze** [comment]
As I've seen the answer [here](https://stackoverflow.com/questions/64699801/linking-canopenurl-returning-false-when-targeting-android-30-sdk-on-react-native) and documentation [here](https://developer.android.com/training/package-visibility/declaring), starting with Android 11 we need to specify the apps that we want to use.

Adding this to the manifest fixed it for me:

```
<queries>
      <intent>
          <action android:name="android.intent.action.VIEW" />
          <data android:scheme="http" />
      </intent>
      <intent>
          <action android:name="android.intent.action.VIEW" />
          <data android:scheme="https" />
      </intent>
 </queries>
```

**Comment by ArGeoph** [comment]
> As I've seen the answer [here](https://stackoverflow.com/questions/64699801/linking-canopenurl-returning-false-when-targeting-android-30-sdk-on-react-native) and documentation [here](https://developer.android.com/training/package-visibility/declaring), starting with Android 11 we need to specify the apps that we want to use.
> 
> Adding this to the manifest fixed it for me:
> 
> ```
> <queries>
>       <intent>
>           <action android:name="android.intent.action.VIEW" />
>           <data android:scheme="http" />
>       </intent>
>       <intent>
>           <action android:name="android.intent.action.VIEW" />
>           <data android:scheme="https" />
>       </intent>
>  </queries>
> ```

This worked, thanks a lot! 

Please note that you'll also need to update `gradle` to version not lower than 4.1.1 in `android/build.gradle` file and gradle plugin to version not lower than 6.5 in `android/gradle/wrapper/gradle-wrapper.properties` file. Hope it'll safe somebody some time on debugging 😃
