### ISSUE TITLE
Deep Linking issue in iOS

### ISSUE THREAD

**Issue by HCLThiruG** [facebook/react-native#30499]
We are using the **HTTPS** URL in Depp Linking for both iOS and Android, but Android working fine, iOS not working. In iOS always its a redirect to the browser, but using custom schema like **"myapp"** works fine.

**https://example.app.io - not working
myapp://examople.app.io - working** 

so please help us how to use http or https URL  in **iOS** deep Linking.

**Comment by krudos** [comment]
you need to setup universal link on your http server
it should handle

https://example.app.io/apple-app-site-association

https://medium.com/@ankitsaxena21/what-is-an-aasa-apple-app-site-association-file-5dd6b87e0beb

**Comment by rmacuna** [comment]
Hi everyone

I have the same issue. I'm trying to open an in-app link in the application with `Linking.openURL(url)` but only works on Android. On IOS is always opening Safari. 

If I switch the link and replace the HTTP with the myapp:// works good. 

Did someone found how to handle this problem?
Thank you!

**Comment by HCLThiruG** [comment]
Hi rmacuna,

We are not possible to use directly for HTTP or HTTPS protocol in iOS Deep Linking. It only possible to use in Android but we able to do it through Universal Linking for iOS.

We Need to create AASA file and upload to your server root directory and add your server URL in associated Domain option into the XCode. 

Please get more information from below Link.

https://blog.branch.io/how-to-setup-universal-links-to-deep-link-on-apple-ios/
