### ISSUE TITLE
Buck build broken for rn-tester

### ISSUE THREAD

**Issue by rectified95** [facebook/react-native#30507]
## Description

Instructions in  `packages/rn-tester/README.md` say to run `buck install -r rntester` in order to build the app.
Currently this fails with the following error:
`No build file at packages/rn-tester/android/app/BUCK when resolving target //packages/rn-tester/android/app:app.`
This seems to happen because the relevant buck file is named `_BUCK`, rather than `BUCK`.
Indeed, removing the underscore moves the build forward. However, once the command can properly run, the actual build fails with the below errors (at the same time, I am able to run rn-tester from Android Studio):

![Screenshot from 2020-11-30 18-03-28](https://user-images.githubusercontent.com/12816515/100688125-72128900-3336-11eb-874c-6cc8c39f407a.png)

## React Native version:
info Fetching system and libraries information...
System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
    Memory: 1.12 GB / 11.70 GB
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 15.3.0 - /usr/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 7.0.14 - /usr/bin/npm
    Watchman: 20201120.183554.0 - /usr/local/bin/watchman
  SDKs:
    Android SDK:
      API Levels: 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom
      Android NDK: 19.2.5345600
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 1.8.0_275 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: ^5.0.1-alpha.0 => 5.0.1-alpha.0 
    react: 17.0.1 => 17.0.1 
    react-native: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
```
./gradlew :ReactAndroid:packageReactNdkLibsForBuck 
buck fetch rntester
buck install -r rntester
```

## Expected Results
Building rn-tester with Buck should work.

**Comment by dulmandakh** [comment]
Please see CI configuration because CI uses buck and CI is green now. Please feel free to create a PR to fix documentation.

**Comment by rectified95** [comment]
I've looked at the .circleci/config.yml and can see that in the case of Android, Buck is only used to build the framework:
```
# Build and compile
      - run:
          name: Build Android App
          command: |
            buck build ReactAndroid/src/main/java/com/facebook/react
            buck build ReactAndroid/src/main/java/com/facebook/react/shell
```
but it looks like the rest is still built using Gradle.
Which leads me to believe that the CI does not test building rn-tester with Buck.
