### ISSUE TITLE
React Native ignores aspectRatio on Video elements

### ISSUE THREAD

**Issue by yolpsoftware** [facebook/react-native#30501]
## Description
Please have a look at this snack:

https://snack.expo.io/@yolpsoftware/groaning-nachos

Please open the snack in a separate window (link to the right of the “Web” tab in the right sidebar).

When you resize the window a bit, you’ll notice some strange behavior:

* Even though both the `<Video>` and their direct parents have `width: 100%` and `aspectRatio: 1.333`, the height of the `<Video>` elements always stays the same. The aspectRatio prop is not respected:
![image](https://user-images.githubusercontent.com/1302357/100587504-f17d6980-32f0-11eb-881b-12d5066edcfd.png)

* (might be an error in Snack) When the window is big enough for the two videos to fit in, their parents get a height of 0, so they are rendered on top of each other. As soon as you make the window smaller, this behavior disappears.

Why is that so?

## React Native version:
React Native 0.63
Expo SDK Version: 39
Platforms(Android/iOS/web/all): web / iOS (Android not tested)

## Steps To Reproduce
https://snack.expo.io/@yolpsoftware/groaning-nachos

## Expected Results
I want the video elements to fill the width of their parent, but their height should be set according to the aspectRatio prop.

## Snack, code example, screenshot, or link to a repository:
https://snack.expo.io/@yolpsoftware/groaning-nachos

**Comment by Baran212134** [comment]
com

**Comment by yolpsoftware** [comment]
> com

com?

**Comment by dulmandakh** [comment]
Sorry, RN doesn't have Video component. Please file an issue to Expo.
