### ISSUE TITLE
Updating snapToOffsets property of FlatList causes app crash on Android

### ISSUE THREAD

**Issue by rosskhanas** [facebook/react-native#30502]
## Description
Android app crashes when updating `snapToOffsets` prop.

> Error while updating property 'snapToOffsets' of a view managed by: AndroidHorizontalScrollView Value for snapToOffsets cannot be cast from Double to ReadableArray

## React Native version:
System:
    OS: macOS 11.0.1
    CPU: (4) x64 Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
    Memory: 86.06 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 13.12.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.6 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.2/12B45b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.9 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce

1. Render a component: `<FlatList snapToOffsets={isSnap ? items.map((_, index) => index * itemWidth) : undefined} />`. The `isSnap` value is `true`.
2. Change `isSnap` value to `false`.

## Expected Results
FlatList re-renders correctly and there is no snap behavior anymore.

**Comment by katiecarter** [comment]
I'm experiencing this crash as well when updating snapToOffsets from a defined array to undefined.

**Comment by maxoumime** [comment]
👋 PR #31681 fixes this issue.

**Comment by LuuchoRocha** [comment]
Why is this closed?
