### ISSUE TITLE
PLEASE HELP! - React Native version mismatch. (Android) (JavaScript version: 0.59.9 - Native version: 0.63.3)

### ISSUE THREAD

**Issue by MedyxDev** [facebook/react-native#30505]
## Description
I get a version mismatch on react native (android). 
- The build works as expected when running: react-native run-android
- The build works as described in this issue when running through Android Studio.
Please let me know what else I can try, or what might cause the issue.

## React Native version:
0.63.3

## Expected Results
The app running as expected

## What have I tried to resolve the issue
- Clearing caches
- Forcing versions through build.gradle (https://stackoverflow.com/questions/47763824/react-native-version-mismatch)
- Going back in history through git
- Reinstalling / trying other emulator versions
- Remove node_modules and reinstall
- Tried react-native-clean-project (https://github.com/pmadruga/react-native-clean-project)
- Uninstalling the app from the emulator manually
- Was building with SDK Tools 29, also tried with 30 (was working with 29 before)
- Tried different versions of Android Studio (4.1, 4.0, 4.1.1. (current)
- Tried downgrading to RN 0.62.2
- Tried upgrading to RN 0.63.4

## Snack, code example, screenshot, or link to a repository:
![image](https://user-images.githubusercontent.com/75259405/100618693-7631ad00-331c-11eb-93e7-8b18001315c1.png)
![Screenshot_1607086112](https://user-images.githubusercontent.com/75259405/101165779-8527a080-3637-11eb-8571-c1445a845f72.png)

**Comment by MedyxDev** [comment]
Issue remains, if additional information is needed please let me know!

**Comment by MedyxDev** [comment]
Updated the "What have I tried to resolve the issue" chapter with everything else I have tried.

**Comment by MedyxDev** [comment]
Tried to downgrade to RN 0.62.2, same issue different version.

**Comment by MedyxDev** [comment]
Tried upgrading to RN 0.63.4, issue remains. 
Also updated the initial post with this.

**Comment by mandhu** [comment]
close metro and start again

**Comment by dulmandakh** [comment]
Please restart metro or packager.
