### ISSUE TITLE
[Android] Pointer location incorrect

### ISSUE THREAD

**Issue by xinthink** [facebook/react-native#3050]
Hi,
It seems like pointer location on Android is relative to the screen, instead of the element? 
I'm listening to pointer events, found `locationX` & `locationY` incorrect.
The same code works fine on iOS.

demo reproducing the issue: https://rnplay.org/apps/3nN_Aw

**Comment by astreet** [comment]
Thanks for the report! This does indeed look incorrect. Krzysztof, I think you had worked on this pointer transformation (raw vs non-raw coords), can you take a look?

**Comment by gre** [comment]
also experimenting `location{X,Y}` issues with inconsistencies across Android / iOS implementations

**Comment by satya164** [comment]
It should be fixed in recent versions.
