### ISSUE TITLE
Intl.RelativeTimeFormat is undefined even if jscFlavor includes intl

### ISSUE THREAD

**Issue by SrBrahma** [facebook/react-native#30506]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
console.log(Intl.RelativeTimeFormat) outputs `undefined` even if I define in my app/build.gradle the `jscFlavor = 'org.webkit:android-jsc-intl:+'`. The jscFlavor partially works because I can use the `Intl.DateTimeFormat` with some options that weren't working before the flavor change.

## React Native version:
0.63.2

## Expected Results
Intl.RelativeTimeFormat should be usable

**Comment by SrBrahma** [comment]
bump

**Comment by podenborg** [comment]
I'm having the same issue

**Comment by podenborg** [comment]
For anyone else having this issue, I was able to get it to work by installing the following poyfills:
`yarn add @formatjs/intl-locale @formatjs/intl-relativetimeformat`

And then in the entry point for my app I added the following:
```typescript
import { registerRootComponent } from 'expo'
import { Platform } from 'react-native'
import App from './App'

if (Platform.OS === 'android') {
  require('@formatjs/intl-locale/polyfill')
  require('@formatjs/intl-relativetimeformat/polyfill')
  require('@formatjs/intl-relativetimeformat/locale-data/en') // locale-data for en
}

registerRootComponent(App)
```
You will need to follow these steps _**after**_ you change the jsc flavor in the app gradle to use the `'org.webkit:android-jsc-intl:+'` flavor.

**Comment by cortinico** [comment]
Thanks for sharing @podenborg 

Closing as a workaround was suggested 👍

**Comment by vberezkin** [comment]
This solution works fine only for english language
