### ISSUE TITLE
Android device overrides font in the app

### ISSUE THREAD

**Issue by janamineur** [facebook/react-native#30515]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
When I give an array of styles to a Text component, Android overrides my font family.

## React Native version:
react: 16.13.1 => 16.13.1 
react-native: 0.63.3 => 0.63.3 

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Add some Text components.
2. Add styles to the Text components, also an array of styles so you can see the difference.
3. Change your font on your device.

## Expected Results
The font family in the app **should not** be override by device font.

## Snack, code example, screenshot, or link to a repository:
```
     <View style={styles.line}>
        <Text style={styles.text}>
          This text is not override by device font
        </Text>
        <Text
          style={[
            styles.text,
            styles.bold,
          ]}>This text is override</Text>
     </View>
     <View style={styles.line}>
        <Text style={styles.text}>This text is not override</Text>
        <Text style={[styles.text, styles.bold]}>this text is</Text>
     </View>
```

```
const styles = StyleSheet.create({
  text: {
    fontSize: 14,
    fontFamily: 'INTER-REGULAR',
    color: 'gray',
  },
  bold: {
    fontWeight: 'bold',
  },
  line: {
    flexDirection: 'row',
  },
});
```

![font bug](https://user-images.githubusercontent.com/28523667/100854070-ccbbfa00-3488-11eb-8fb3-f9d3bbc9674f.jpg)

**Comment by MoOx** [comment]
Does your font have all the necessary variant? You cannot expect a font with a given weight to auto adjust. A unique font file is probably not enough, you should check that.

**Comment by KyawSoeHein** [comment]
it also happens to me on OPPO and VIVO phones. System font is taking over my custom font family, is there any fix for this? Other phone brands are working fine.

**Comment by MoOx** [comment]
@KyawSoeHein Did you had a look to https://github.com/facebook/react-native/issues/25481 (and discussion in this thread?) - it might be related to font weight.

**Comment by KyawSoeHein** [comment]
@MoOx , I don't think so because I didn't use font weight for the specific Text componenet that has been overridden.

`   style={{
                    fontSize: this.kycStatusSize,
                    color: "#5E5F5E",
                    paddingTop: 9,
                    fontFamily: !isEng
                      ? "Pyidaungsu"
                      : isIos
                      ? "SFUIText-Medium"
                      : "SF-UI-Text_medium",
                  }}`

**Comment by ghousesaqlain** [comment]
Any one have solution for this?

**Comment by fabriziobertoglio1987** [comment]
Do you still experience this issue? 

I have four years of experience maintaining facebook/react-native and I specialize in the Text and TextInput components. I currently have 58 [facebook/react-native PRs](https://github.com/facebook/react-native/pulls?q=is%3Apr+author%3Afabriziobertoglio1987+). 

If you still experience this issue, I will prepare a patched release with the fix.

Thanks a lot

**Comment by ghousesaqlain** [comment]
@fabriziobertoglio1987 
Yeah, Still the issue persists, it would be really helpful if you do so.

Thank you.

**Comment by marcell6** [comment]
@fabOnReact so how to fix it sir?
especially occurred on Samsung devices :')

**Comment by arnabadhikari2009** [comment]
@fabOnReact  hello, I have the same issue.can you provide the solution?

**Comment by nagatich** [comment]
it's still an issue on samsung devices. when i set non-default font style on the device, font in the app changes from bold to normal
