### ISSUE TITLE
How to show only alpha-numeric characters in keypad for Textinput in React Native?

### ISSUE THREAD

**Issue by sivaperumaljeyaraj** [facebook/react-native#30510]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Please provide a clear and concise description of what the bug is. Include screenshots if needed.
Please test using the latest React Native release to make sure your issue has not already been fixed: https://reactnative.dev/docs/upgrading.html

## React Native version:
Run `react-native info` in your terminal and copy the results here.

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.
2.

## Expected Results
Describe what you expected to happen.

## Snack, code example, screenshot, or link to a repository:
Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by VictorAugustoDn** [comment]
Use the prop "keyboardType", read the docs, its there for you.

**Comment by sivaperumaljeyaraj** [comment]
I tried the following values in "keybaoardType" prop.

default
number-pad
decimal-pad
numeric
email-address
phone-pad

ascii-capable
numbers-and-punctuation
url
name-phone-pad
twitter
web-search

visible-password


All the above values shows special characters keys in the keyboard.

Please help with this.

**Comment by dulmandakh** [comment]
Sorry, this issue tracker is intended to track RN issues, but not developer support. RN exposed what native platforms features. If you find this feature is available in native platform, and missing in RN, then please feel free to create a PR to add it. I would love to help with PR. Thanks
