### ISSUE TITLE
Control scroll animation duration for Android is not available

### ISSUE THREAD

**Issue by nicocolascrete** [facebook/react-native#30517]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
The scroll animation for android still not worked. In the documentation there is a param duration for config this but it's not present in the source code.
Documentation:
https://reactnative.dev/docs/scrollview#scrolltoend
Pull request: ( merge and after revert )
https://github.com/facebook/react-native/pull/22884

## React Native version:
reacrt-native 0.63.4

## Steps To Reproduce
this._scroller.scrollToEnd({animated: true, duration: 800});

## Expected Results
The scrollview need to scroll to end with a duration of 800 ms.

## Snack, code example, screenshot, or link to a repository:
I think the behaviour it's clear without example. There is trouble between source code and documentation.

**Comment by nicocolascrete** [comment]
Any informations about this?
Another possibility to set duration on android scroll?

**Comment by nicocolascrete** [comment]
Any update?

**Comment by nicocolascrete** [comment]
Nobody can help us on this issue?

**Comment by Abhinandan-Kushwaha** [comment]
Any update on this? PR https://github.com/facebook/react-native/pull/22884 was closed citing this broke some internal callsites (https://github.com/facebook/react-native/pull/22884#issuecomment-458765608)
@fkgozali @osdnk any plans to resurrect this?
