### ISSUE TITLE
How to Regenerate Android and IOS Folder ?

### ISSUE THREAD

**Issue by vaibhavgadekar** [facebook/react-native#30521]
**Hello my Android and IOS folders are deleted, am trying to regerate Android and IOS folder. `"react-native eject"` & `"react-native upgrade"` are no longer available**

## React Native version:
   OS: Windows 10 10.0.18363
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.33 GB / 7.85 GB
  Binaries:
    Node: 14.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6308749
    Visual Studio: Not Found
  Languages:
    Java: Not Found
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: ~0.63.3 => 0.63.4
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. `"react-native eject"`
2. `"react-native upgrade"`

## Expected Results
Generate Android and IOS Folders

**Comment by ravirajn22** [comment]
Create a new react-native project with same name and just copy your javascript files to that.

Start using `git` going forward.

**Comment by dulmandakh** [comment]
Hope that @ravirajn22 answered your question
