### ISSUE TITLE
[iOS 14.2] - TextInput component suggests a Strong Password

### ISSUE THREAD

**Issue by MrRizton** [facebook/react-native#30528]
## Description
Issue is reproducible on iOS 14+ when using several TextInput components with `textContentType="oneTimeCode"` and `secureTextEntry` properties. TextInput in this case turns on the "Strong password suggestion" feature. On iOS 13+ this issue is not reproducible with the same options. The issue was reproduced on two different apps with different React Native versions.

## React Native version:
**First app:**
* react: "~16.11.0",
* react-native: "~0.62.2"

**Second app:**
* react: "16.13.1",
* react-native: "0.63.3"

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Create 3 TextInputs, 2 of which are with `secureTextEntry` and `textContentType="oneTimeCode"` properties and the other one is without them;
2. Chain them to be focused on submitting of the previous field;
3. Focus on the TextInput without `secureTextEntry` and `textContentType="oneTimeCode"`;
4. Press "Next" button on the keyboard to focus on the next TextInput with `secureTextEntry` and `textContentType="oneTimeCode"`.

## Expected Results
The desirable result is for TextInput to not suggest Strong Password, which blocks the input.

## Snack, code example, screenshot, or link to a repository:
```
import React, {useRef, useState} from 'react';
import {ScrollView, TextInput} from 'react-native';
import styles from './styles';

const LoginScreen: React.FC = () => {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const passwordRef = useRef<TextInput>(null);
  const confirmRef = useRef<TextInput>(null);

  return (
    <ScrollView>
      <TextInput
        placeholder="Email"
        value={email}
        keyboardType="email-address"
        textContentType="emailAddress"
        returnKeyType="next"
        onChangeText={setEmail}
        autoCapitalize="none"
        onSubmitEditing={() => passwordRef.current?.focus()}
        style={{height: 40, color: 'white'}}
        placeholderTextColor="white"
      />
      <TextInput
        ref={passwordRef}
        placeholder="Password"
        value={password}
        textContentType="oneTimeCode"
        returnKeyType="next"
        onSubmitEditing={() => confirmRef.current?.focus()}
        onChangeText={setPassword}
        autoCapitalize="none"
        secureTextEntry
        style={{height: 40, color: 'white'}}
        placeholderTextColor="white"
      />
      <TextInput
        ref={confirmRef}
        textContentType="oneTimeCode"
        placeholder="Confirm Password"
        value={confirmPassword}
        returnKeyType="done"
        onChangeText={setConfirmPassword}
        autoCapitalize="none"
        secureTextEntry
        style={{height: 40, color: 'white'}}
        placeholderTextColor="white"
      />
    </ScrollView>
  );
};

export default LoginScreen;
```

**Screen Record of the app on iOS 13.7**
![ezgif com-gif-maker](https://user-images.githubusercontent.com/35537705/101042725-2e15c300-3586-11eb-8e06-85f9147edebb.gif)

**Screen Record of the app on iOS 14.2**
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/35537705/101042976-6fa66e00-3586-11eb-9031-9de3860f09b1.gif)

**Comment by luco** [comment]
Duplicate of #21911

**Comment by alielmajdaoui** [comment]
https://github.com/facebook/react-native/issues/21911#issuecomment-831607710
