### ISSUE TITLE
[iOS] keyboardShouldPersistTaps not working when the input is not visible

### ISSUE THREAD

**Issue by gotvitch** [facebook/react-native#30538]
## Description
In a scroll view with the props `keyboardShouldPersistTaps` set to `handled ` (or `always`), the `onPress` event on the child view element of the scrollview is not trigger when the focus is set on a `TextInput` and this input is outside of the visible part of the scrollview (it work when the input is visible). The issue is only affecting iOS and I was only able to reproduce on real device but not in the simulator. I tested on multiple device (iPhone 12, iPhone 11, iPhone 8) and on different version of iOS14.  

## React Native version:
```
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 27.05 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.15.1 - ~/.nvm/versions/node/v14.15.1/bin/node
    Yarn: Not Found
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.2/12B45b - /usr/bin/xcodebuild
  Languages:
    Java: javac 15 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: https://github.com/expo/react-native/archive/sdk-39.0.4.tar.gz => 0.63.2
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.
1. Open the example
2. Click on the input
3. Scroll to the links at the bottom (the input need to be no longer visible)
4. Click on the link, the first press won't work and it will scroll up to the input
5. Press again and it will work

## Expected Results
The first press should works.

## Snack
https://snack.expo.io/nWFY1lnit

## Screen recording
Video link: https://share.vidyard.com/watch/XnNPqBptAzSvwaJqJ1mjVw?

![image](https://user-images.githubusercontent.com/902588/101242722-8c17e700-36fb-11eb-8727-7e9bb20e9de4.png)

## Code example
```ts
import React from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';

export default function App() {
  return (
    <ScrollView
      keyboardShouldPersistTaps="handled"
      style={styles.scrollView}
    >
      <View style={ styles.scrollViewContent }>
        <TextInput style={ styles.textInput } />
        <Text onPress={ () => { Alert.alert( "text pressed" ) } } style={ styles.text }>
          Text Click here works
        </Text>
        <Pressable onPress={ () => { Alert.alert( "pressable pressed" ) } }>
          <Text style={ styles.text }>Pressable Click here works</Text>
        </Pressable>
        <View style={ styles.spacer } />
        <Text onPress={ () => { Alert.alert( "text pressed" ) } } style={ styles.text }>Click here doesn't works on the first press</Text>
        <Pressable onPress={ () => { Alert.alert( "pressable pressed" ) } }>
          <Text style={ styles.text }>Pressable Click here works</Text>
        </Pressable>
        <View style={ styles.spacer } />
      </View>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  scrollView: {
    flex: 1,
    backgroundColor: '#fff',
  },
  scrollViewContent: {
    paddingVertical: 100,
    paddingHorizontal: 20,
  },
  textInput: {
    borderColor: "#ddd",
    borderWidth: 2,
    fontSize: 24,
    padding: 5,
  },
  spacer: {
    backgroundColor: "blue",
    height: 700,
  },
  text: {
    alignSelf: "center",
    backgroundColor: "#dddddd",
    fontSize: 20,
    padding: 5,
    marginVertical: 15,
  },
});

```

**Comment by yurakurets** [comment]
have the same issue with react-native-keyboard-aware-scroll-view

**Comment by yurakurets** [comment]
found such solution:
<KeyboardAwareScrollView
                keyboardDismissMode="on-drag"
                enableResetScrollToCoords={false}>
                ...
                set enableResetScrollToCoords={false} to avoid twitch after hiding keyboard

**Comment by fabriziobertoglio1987** [comment]
Do you still experience this issue? 

I have four years of experience maintaining facebook/react-native and I specialize in the Text and TextInput components. I currently have 58 [facebook/react-native PRs](https://github.com/facebook/react-native/pulls?q=is%3Apr+author%3Afabriziobertoglio1987+). 

If you still experience this issue, I will prepare a patched release with the fix.

Thanks a lot
