### ISSUE TITLE
Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 11891 (mqt_js), pid 11641

### ISSUE THREAD

**Issue by Marinaarimany** [facebook/react-native#30530]
Hello, 
I am using react-native version 0.63.3 in my video application where I use the react-native-jitsi-meet 2.1.1 library. when I get to the video visio part, the application crashes with this error message 

Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 11891 (mqt_js), pid 11641

It's been several weeks where I am blocked and I do not know what to do, do you have any ideas to solve this if you need more information do not hesitate. 

Thank you Best regards

**Comment by cdunkel** [comment]
@Marinaarimany, were you ever able to find a solution to this issue?

**Comment by Marinaarimany** [comment]
Hello @cdunkel, 
I no longer have this problem, I updated the sdk natively. 
Thank you
