### ISSUE TITLE
Can I use the same library on both native and react-native sides?

### ISSUE THREAD

**Issue by CMLCNL** [facebook/react-native#30542]
I wrote some parts in the application android native. The web rtc module I use on the android native side and the webrtc module I use on the react native side conflict. How can I use the same library on both sides?

System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
    Memory: 8.63 GB / 15.95 GB
  Binaries:
    Node: 10.18.0 - C:\Program Files\nodejs\node.EXE    
    Yarn: Not Found
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD       
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version  3.5.0.0 AI-191.8026.42.35.6010548
    Visual Studio: 16.5.30011.22 (Visual Studio Community 2019)
  Languages:
    Java: 11.0.2 - /c/jdk-11.0.2/bin/javac
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.63.4 => 0.63.4
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by dulmandakh** [comment]
Sorry, this issue tracker is intended to track RN issues, but not developer support. You can expose native module functionality to JS using own custom module.
