### ISSUE TITLE
Error: Unable to resolve module `./debugger-ui/debuggerWorker.aca173c4.js` from ``: 

### ISSUE THREAD

**Issue by simbathesailor** [facebook/react-native#30541]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description

I am trying to add a babel plugin for react native project generated from react native starter. The babel plugin works fine on react project (generated from cra) and also on electron app using react . But it doesn't work as expected on react-native one. The required manipulated(from babel-plugin) code , I can see in sources panel in browser debugger. but due to following error, the app doesnot run.

Error: Unable to resolve module `./debugger-ui/debuggerWorker.aca173c4.js` from ``: 

The moment I remove the comment which causes the babel plugin to manipulate the code. everything works fine.

Here is the repo, which reproduces the issue. 
https://github.com/simbathesailor/react-native-babel-plugin-example

Link to babel plugin which i want to add : https://github.com/simbathesailor/babel-plugin-use-what-changed

![Screenshot 2020-12-07 at 2 34 12 PM](https://user-images.githubusercontent.com/5938110/101331411-f797bb00-3899-11eb-8ee9-e69e7adcacd5.png)

I have tried following links without resolution.
https://github.com/facebook/react-native/issues/28844

## React Native version:
Run `react-native info` in your terminal and copy the results here.

System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 186.49 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.10.0 - ~/.nvm/versions/node/v12.10.0/bin/node
    Yarn: 1.17.3 - ~/.nvm/versions/node/v12.10.0/bin/yarn
    npm: 6.10.3 - ~/.nvm/versions/node/v12.10.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.1, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.1/12A7403 - /usr/bin/xcodebuild
  Languages:
    Java: 13.0.1 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
## Steps To Reproduce

1. Clone the repository https://github.com/simbathesailor/react-native-babel-plugin-example

2. Run 

```
yarn
npx react-native start --reset-cache
npx react-native run-ios     

```

You can run even for android, using:

npx react-native run-android.

it fails for it also.

## Expected Results
The app should render properly without errors

## Snack, code example, screenshot, or link to a repository:

https://github.com/simbathesailor/react-native-babel-plugin-example

https://github.com/simbathesailor/babel-plugin-use-what-changed

**Comment by efstathiosntonas** [comment]
duplicate https://github.com/facebook/react-native/issues/28844

**Comment by simbathesailor** [comment]
> duplicate #28844

@efstathiosntonas :I already tried the steps mentioned in #28844. I have mentioned in the issue  description. So this does not look the exact duplicate of that issue. 
Thanks

**Comment by Mohammed-Q96** [comment]
I have the same issue

**Comment by Seamus1989** [comment]
+1

**Comment by FLB-daniel** [comment]
+1

**Comment by methineeinkan** [comment]
+1

**Comment by simbathesailor** [comment]
Any updates on the issue ?

**Comment by JB-CHAUVIN** [comment]
Any updates ? I got the same problem : 
![Uploading image.png…]()

**Comment by MayoudP** [comment]
Same here

**Comment by mogarick** [comment]
I'm using Expo and I'm also having this problem. 
My RN versión is 0.63.2 from Expo 40

**Comment by abhiscripts** [comment]
using react native version -> react-native: 0.65.1
I am facing the similar issue.
Error: Unable to resolve module ./debugger-ui/debuggerWorker.aca173c4

**Comment by wcldyx** [comment]
Same here

**Comment by alfredomarqueza** [comment]
same issue : RN 0.66.1

**Comment by electricfeel1979** [comment]
same with me here issue on RN 0.66.1

**Comment by yashpalraj** [comment]
Same Issue. RN:0.66.3
Any Solution?

**Comment by pratikadh** [comment]
@simbathesailor what did you do to fix this issue?

**Comment by pratikadh** [comment]
@simbathesailor did you fix this issue?

**Comment by pratikadh** [comment]
@simbathesailor did you find any solution to this issue?

**Comment by simbathesailor** [comment]
No

**Comment by yashpalraj** [comment]
Hello All,

I recently Solved This Issue.

React Navigation for Drawer requires  react-native-reanimated package.

In my case, I was using react-native-reanimated version 1.x.x. When I upgrade it to 2.x.x. It started giving me this error.

They have mentioned it in Documentation. 
Link: https://docs.swmansion.com/react-native-reanimated/docs/2.1.0/#known-problems-and-limitations

Also, React Navigation -> Drawer Documnetation has also mentioned the same.
https://reactnavigation.org/docs/drawer-navigator/#uselegacyimplementation

So, downgrade react-native-reanimated back to 1.x.x works for me.

Or as per documentation, you can use Flipper.

Thank You.
