### ISSUE TITLE
PermissionsAndroid.request() no longer adheres to Google Play requirements

### ISSUE THREAD

**Issue by Datagrdn** [facebook/react-native#30540]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
I am submitting an app to the Play Store that requires user location, however the app is rejected because of a new policy requiring a prominent dialogue to the user clearly stating why the app requires this permission. Seems like PermissionsAndroid.request() is the best way to do this, however the rationale is only displayed after a user refuses permission. Thus Google rejects the app.

## React Native version:
0.63

## Expected Results
Prominently display PermissionsAndroid.request() rationale before the native dialogue each time, not only after a user refuses permission.

**Comment by D4nt4lion** [comment]
Same issue.
