### ISSUE TITLE
Appearance.addChangeListener() does nothing

### ISSUE THREAD

**Issue by olive007** [facebook/react-native#30553]
## Description

I am writing my first react-native app and would like to switch themes, **without restarting the app;** like GMail does.  
Indeed GMail get darker colors when we change the theme mode, or set automatic dark theme during nights, into the phone settings.
So I try to implement the `Appearance.addChangeListener` as explained in the doc but unfortunately the feature doesn't work.

## React Native version:
- System:
  - OS: Linux 5.4 Linux Mint 20 (Ulyana)
  - CPU: (12) x64 Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
  - Memory: 23.42 GB / 31.29 GB
  - Shell: 5.0.17 - /bin/bash
- Binaries:
  - Node: 14.15.1 - /usr/bin/node
  - Yarn: Not Found
  - npm: 6.14.9 - /usr/bin/npm
  - Watchman: 20200920.192359.0 - /usr/local/bin/watchman
- SDKs:
  - Android SDK: Not Found
- IDEs:
  - Android Studio: Not Found
- Languages:
  - Java: 14.0.2 - /usr/bin/javac
  - Python: Not Found
- npmPackages:
  - @react-native-community/cli: Not Found
  - react: 16.13.1 => 16.13.1 
  - react-native: 0.63.3 => 0.63.3 
- npmGlobalPackages:
  - *react-native*: Not Found

## Steps To Reproduce

1. Create an application implementing `Appearance.addChangeListener`
2. Launch the application
3. Switch to split screen with the settings
4. Change theme
5. Notice that the application doesn't change.
6. Try with GMail to see that the feature work with other apps.

## Expected Results

When the user change phone theme setting the `addChangeListener` should call the function pass in argument.

## Snack, code example, screenshot, or link to a repository:

``` lang-js
useEffect(() => {
    dispatch(changeTheme(Appearance.getColorScheme()));
    Appearance.addChangeListener(onThemeChange);

    return () => Appearance.removeChangeListener(onThemeChange);
}, []);

// This function is never call
const onThemeChange = ({ colorScheme }) => {
    console.log("onThemeChange", colorScheme)
    dispatch(changeTheme(colorScheme));
}
```
Also reported on [StackOverflow](https://stackoverflow.com/questions/65188658/react-native-appearance-addchangelistener-does-nothing)

**Comment by samuelhnrq** [comment]
This issue is quite old and not sure if the same problem, but on my Galaxy Note 10+ with one UI 3.1 (android 11) the listener for the color scheme doesn't work, the color scheme detection only works after restarting the app.

**Comment by DiegoBM** [comment]
Same here, fresh react native project created today, and the listener  never gets called, neither on the android emulator nor on my actual device. Also the typescript types for addChangeListener are outdated

**Comment by DiegoBM** [comment]
Will this ever get fixed?
