### ISSUE TITLE
TextInput text style changes if secureTextEntry is true on Android

### ISSUE THREAD

**Issue by RKuerten** [facebook/react-native#30558]
## Description
In Android, the placeholder and text style doesn't match any font style changes (such as `fontWeight: "bold"`) if secureTextEntry is true.

## React Native version:
System:
      OS: Windows 10 10.0.18363
Binaries:
      Node: 12.18.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
npmPackages:
      expo: ^39.0.0 => 39.0.5
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2
Expo Workflow: managed

## Steps To Reproduce

1. Create two equal TextInput components, with at least `fontWeight: "bold"` as part of the style.
2. Add the `secureTextEntry={true}` prop to the second one.

## Expected Results
The placeholder and text style of the second input shouldn't change.

## Snack, code example, screenshot, or link to a repository:
Snack: https://snack.expo.io/@r_kuerten/textinput
Image: 
![image](https://user-images.githubusercontent.com/30464993/101641862-0d7bbc00-3a11-11eb-8e8b-5553c26713c1.png)

**Comment by rolivegab** [comment]
Hi!
Looks that it has been fixed on react-native 0.63.4.
Changelog: https://github.com/react-native-community/releases/blob/master/CHANGELOG.md#v0634

**Comment by alexco2** [comment]
Hello. I added a Hide/ Unhide feature to my Passoword Textinput, that toggles the secureTextEntry. The Font is resetted when switching from `secureTextEntry={true}` to `secureTextEntry={false}`

**Comment by longb1997** [comment]
For anyone who comes here, it's fixed (again) in 0.64.2:
https://github.com/react-native-community/releases/blob/master/CHANGELOG.md#v0642
