### ISSUE TITLE
Flatlist Container BorderRadius is not applied on Android

### ISSUE THREAD

**Issue by mikeymop** [facebook/react-native#30550]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
If you look at [this comment](https://github.com/facebook/react-native/issues/24207#issuecomment-480547586) on #24207 an example of the issue is demonstrated on in a snack.

## React Native version:
Run `react-native info` in your terminal and copy the results here.
```
System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 359.05 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.22.0 - ~/.nvm/versions/node/v10.22.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v10.22.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    Android SDK:
      API Levels: 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6858069
    Xcode: 12.2/12B45b - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_242-release - /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.4 => 0.63.4
```
## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. The issue can still be reproduced with the [snack](https://snack.expo.io/@jkcooper/rn24207---flatlist-border-radius) from above
2. Run the snack on Android, and use the mouse to scroll beyond the bounds of the flatlist and observe the Android overflow animation.
3. The corners of the overflow animation will not have the borderradius that is set to either the flatlist style or contentContainer

<img src="https://user-images.githubusercontent.com/4002969/101403962-f7042200-38a3-11eb-90c8-510fc992c09c.png" width="500"></img>

If a content header is used that has a border radius, the content of the flastlist will 'peek' over the corner of the flatlist.

<img src="https://user-images.githubusercontent.com/4002969/101404181-45192580-38a4-11eb-9947-163bb37ebbcd.png" width="500"></img>

## Expected Results

I expect the flatlist borderradius to affect the content in the virtual scrollview so that if there is a content header with 

## Snack, code example, screenshot, or link to a repository:

https://snack.expo.io/@jkcooper/rn24207---flatlist-border-radius

**Comment by aJieBai** [comment]
I also have the same problem. I set the borderRadius, but the item will slide out of the border(Only Android)

**Comment by iospixbrand** [comment]
Any updates on this?
