### ISSUE TITLE
GestureResponderEvent Accessing Target Component

### ISSUE THREAD

**Issue by NateAGeek** [facebook/react-native#30559]
Introduction/Details
Currently the GestureResponderEvent provides a target that is a node id, however, trying to find the referenced component and the subsequent props is not possible. There use to be the getInstanceFromNode from the ReactNativeComponentTree, but this was a private method and also is no longer in the source(rightfully due to Fabric). Should we update the GestureResponderEvent target to return a component reference or make component info/props easily accessible with node ids?

React Native version:
0.63.4

Discussion points
Change GestureResponderEvent target to component reference
Make Native Tree Components more accessible via node id's

**Comment by 20547** [comment]
.  
  

-  
Sent from [MailTime](http://www.mailtime.com) for Android
