### ISSUE TITLE
Azure Media Service Videos are not working on Android and iOS Real Devices React Native

### ISSUE THREAD

**Issue by Nauman-Asghar** [facebook/react-native#30552]
Azure Media Service Videos are not working on Android and iOS Real Devices React Native

## Description
I have embed Azure Media Player in WebView. Its working fine on android emulator and iOS simulator. Its also working fine on android real device in debug but its not working on android devices in release version. For iOS its not working on real devices in debug and release version.

## React Native version:
0.63.4

## Steps To Reproduce
Embed Azure Media Player in WebView and run on real device(iOS debug and android release).

## Expected Results
Azure Media Service videos should work on real devices as it works fine on emulator and simulator.

## Snack, code example, screenshot, or link to a repository:
Here is code sample

```<html lang="en">
  <head>
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://amp.azure.net/libs/amp/2.3.6/skins/amp-default/azuremediaplayer.min.css" rel="stylesheet">
    <script src="https://amp.azure.net/libs/amp/2.3.6/azuremediaplayer.min.js"></script>
  </head>
  <body>
  <video id="azuremediaplayer" class="azuremediaplayer amp-default-skin amp-big-play-centered" tabindex="0"></video>
    <script>
        var myOptions = {
          "nativeControlsForTouch": false,
          controls: true,
          autoplay: true,
          width:1000,
          height: "1000",
        }
        myPlayer = amp("azuremediaplayer", myOptions);
        myPlayer.src([
            {
                "src": "https://amssamples.streaming.mediaservices.windows.net/3b970ae0-39d5-44bd-b3a3-3136143d6435/AzureMediaServicesPromo.ism/manifest",
                "type": "application/vnd.ms-sstr+xml"
            }
        ]);
    </script>
  </body>
  </html>;

  return (
          <WebView
            source={{ html: htmlContent }}
          />
    )
```

**Comment by dulmandakh** [comment]
Please use react-native-webview and file an issue if you experience issues with it. WebView in React Native is deprecated a long ago.
