### ISSUE TITLE
Creating react-native project with typescript template fails.

### ISSUE THREAD

**Issue by DevHabit** [facebook/react-native#30557]
## Description

I tried to create new react-native project with typescript template.
But after running `npx react-native init Sample --template react-native-template-typescript` command, it failed.

## React Native version:
`0.63`

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Run the following command in the terminal.
`npx react-native init Sample --template react-native-template-typescript`

## Expected Results
Create a new react-native project with typescript template.

## Snack, code example, screenshot, or link to a repository:
```
Arguments: 
  /usr/local/Cellar/node/15.3.0/bin/node /usr/local/Cellar/yarn/1.22.10/libexec/bin/yarn.js add react-native-template-react-native-template-typescript

PATH: 
  /Volumes/Data/WORK/devHabit/AAAAA/node_modules/.bin:/Volumes/Data/WORK/devHabit/node_modules/.bin:/Volumes/Data/WORK/node_modules/.bin:/Volumes/Data/node_modules/.bin:/Volumes/node_modules/.bin:/node_modules/.bin:/usr/local/Cellar/node/15.3.0/bin:/Volumes/Data/WORK/devHabit/node_modules/.bin:/Volumes/Data/WORK/node_modules/.bin:/Volumes/Data/node_modules/.bin:/Volumes/node_modules/.bin:/node_modules/.bin:/usr/local/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/node-gyp-bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/topmaster/Library/Android/sdk/emulator:/Users/topmaster/Library/Android/sdk/tools:/Users/topmaster/Library/Android/sdk/tools/bin:/Users/topmaster/Library/Android/sdk/platform-tools

Yarn version: 
  1.22.10

Node version: 
  15.3.0

Platform: 
  darwin x64

Trace: 
  Error: https://registry.yarnpkg.com/react-native-template-react-native-template-typescript: Not found
      at Request.params.callback [as _callback] (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:66988:18)
      at Request.self.callback (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:140749:22)
      at Request.emit (node:events:376:20)
      at Request.<anonymous> (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:141721:10)
      at Request.emit (node:events:376:20)
      at IncomingMessage.<anonymous> (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:141643:12)
      at Object.onceWrapper (node:events:482:28)
      at IncomingMessage.emit (node:events:388:22)
      at endReadableNT (node:internal/streams/readable:1294:12)
      at processTicksAndRejections (node:internal/process/task_queues:80:21)
```

**Comment by giangdinh** [comment]
@DevHabit it's yarn bug, sometimes it can not found packages. Please try this: https://github.com/yarnpkg/yarn/issues/5865

**Comment by DevHabit** [comment]
> @DevHabit it's yarn bug, sometimes it can not found packages. Please try this: [yarnpkg/yarn#5865](https://github.com/yarnpkg/yarn/issues/5865)

I think so.
But as you can see from log - it is finding ` react-native-template-react-native-template-typescript` package.

**Comment by DevHabit** [comment]
I could clone `typescript template` project by using command `npx react-native init <PROJECT_NAME> --template typescript`

**Comment by giangdinh** [comment]
I use `npx react-native init <PROJECT_NAME> --template react-native-template-typescript` and it works. I think s we do not have template typescript.
