### ISSUE TITLE
React Native NativeEventEmitter is not working in Release apk

### ISSUE THREAD

**Issue by benj-spectory** [facebook/react-native#30556]
## Description
I'm using the react native's event emitter (NativeEventEmitter) to send events from native to JS. This thing is working absolutely fine on the DEBUG version. I'm able to send events with data from the native side to JS, but this is not working in the final RELEASE APK!

Basically, I'm trying to send a String from the native side to JS

## React Native version:
System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz
    Memory: 816.23 MB / 15.27 GB
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 10.14.2 - ~/.asdf/shims/node
    Yarn: Not Found
    npm: 6.4.1 - ~/.asdf/shims/npm
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 1.8.0_275 - /usr/bin/javac
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
  npmGlobalPackages:
    *react-native*: Not Found

phone: Samsung a71
model numbe: SM-A715F

## Steps To Reproduce
1. Send an event with some data from the native side using event emitter.
2. Add listener in JS side and try to fetch the results from this native event.
3. create Release APK and inatall it
3. Works fine in DEBUG and RELEASE build variants, but now try generating an APK(RELEASE)
We don't get events data in release APK!

## Expected Results
I'm expecting that my listener at the JS side should listen to the event and get data!

## Snack, code example, screenshot, or link to a repository:
JAVA:
`public void sendName() {
   WritableMap resultData = new WritableNativeMap();
   resultData.putString("name", "Example Name");
   sendEvent("EventName_Name",resultData);
}

public void sendEvent(String eventName, @Nullable WritableMap params) {
   getReactApplicationContext().getJSModule(RCTNativeAppEventEmitter.class).emit(eventName, params);
}`
* it doesn't matter if I send with params or null

JS:
`import {NativeEventEmitter, NativeModules} from 'react-native';

const nameModule = NativeModules.RNNameModule;
const nameManagerEmitter = new NativeEventEmitter(nameModule);

nameManagerEmitter.addListener("EventName_Name", (data) => { console.log(data) });`

the addListener noes not "listen" to the emit action in release APK.

**Comment by dulmandakh** [comment]
You must use RCTDeviceEventEmitter.class, instead of RCTNativeAppEventEmitter.class. Please see https://reactnative.dev/docs/native-modules-android#sending-events-to-javascript.
