### ISSUE TITLE
Permissions in Android  incomplete

### ISSUE THREAD

**Issue by lybrooks** [facebook/react-native#30569]
no  'android.permission.REQUEST_INSTALL_PACKAGES'  in PermissionsAndroid.js, so that i cant check this Permssions on android

**Comment by lybrooks** [comment]
react-native 0.61.5
react-native 0.63.3

**Comment by dulmandakh** [comment]
To install packages from RN you need to implement custom native module, and it might be best to implement permission request there. But you can still create a PR to add missing permissions.
