### ISSUE TITLE
a weird layout problem, the subview exceeds the superview

### ISSUE THREAD

**Issue by YaoHuiJi** [facebook/react-native#30562]
## Description
I met a very weird layout problem. I don't know how to describe it, but the code is pretty simple,just few lines. the question is why does the red view box go out of the  black view box？

https://snack.expo.io/@yaohj/out-of-box
```
import React from 'react';
import { Text, View, StyleSheet } from 'react-native';

export default function App() {
  return (
    <View style={{top: 50, height: 300}}>
      <View style={{alignItems: 'center', borderWidth: 1,borderColor: 'black'}}>
        <View style={{borderColor: 'green', borderWidth: 1, height: 30, width: 30}} />
        <View>
          <View style={{flex: 1, borderWidth: 1, borderColor: 'blue', width: 30}}/>
          <View style={{flex: 2, borderWidth: 1, borderColor: 'red', width: 30}}/>
        </View>
      </View>
    </View>
  );
}
```

it happens on simulator, real iPhone and expo(ios&android)

![截屏2020-12-10 16 48 42](https://user-images.githubusercontent.com/741543/101748504-9aa13c80-3b07-11eb-8206-b91916075e77.png)

![截屏2020-12-10 16 20 00](https://user-images.githubusercontent.com/741543/101743169-9e33c400-3b05-11eb-8f85-e91a5047cc84.png)

![截屏2020-12-10 16 18 53](https://user-images.githubusercontent.com/741543/101743238-a25fe180-3b05-11eb-983e-96c59e951849.png)

## React Native version:
react: 16.13.1 => 16.13.1 
react-native: ^0.63.2 => 0.63.2 

## Steps To Reproduce
You can try it online [https://snack.expo.io/@yaohj/out-of-box](https://snack.expo.io/@yaohj/out-of-box)
or 
Run this piece of code:

```
import React from 'react';
import { Text, View, StyleSheet } from 'react-native';

export default function App() {
  return (
    <View style={{top: 50, height: 300}}>
      <View style={{alignItems: 'center', borderWidth: 1,borderColor: 'black'}}>
        <View style={{borderColor: 'green', borderWidth: 1, height: 30, width: 30}} />
        <View>
          <View style={{flex: 1, borderWidth: 1, borderColor: 'blue', width: 30}}/>
          <View style={{flex: 2, borderWidth: 1, borderColor: 'red', width: 30}}/>
        </View>
      </View>
    </View>
  );
}
```

## Expected Results
hi box,just stay where you should be

## Snack, code example, screenshot, or link to a repository:
https://snack.expo.io/@yaohj/out-of-box

**Comment by ravirajn22** [comment]
The expo web shows it correctly, so this is some layout bug.

But you can make it work the way you want by properly transferring `flex` to child views when the child views themselves don't have fixed height. In your case both parent and child views don't have fixed height and the parent view does not have flex set. Hence child views `flex` wont work and only their borders will drawn like in the Web.


Play with `flex`

**Comment by YaoHuiJi** [comment]
> The expo web shows it correctly, so this is some layout bug.
> 
> But you can make it work the way you want by properly transferring `flex` to child views when the child views themselves don't have fixed height. In your case both parent and child views don't have fixed height and the parent view does not have flex set. Hence child views `flex` wont work and only their borders will drawn like in the Web.
> 
> Play with `flex`

You are right, it's ok on expo web. That is  a minimal piece of code to reproduce the issue, it's not very had to solve it,but I'm just worried that if this is a bug, it might cause some other potential problems that we didn't anticipate, hope It is useful for the community to improve RN
