### ISSUE TITLE
Fetch upload file not work when debug opening

### ISSUE THREAD

**Issue by m-korkut** [facebook/react-native#30566]
this error exists on both ios  and android.does not work when sending images with debug mode on.Image sends null when debug mode is on.Android works when debug mode is off ios doesn't work.iOS does not go to endopoints at all when debug mode is off.

  "react-native": "0.63.2",

  let formData = new FormData();

  for (let index in imageList) {
      let files = {
        uri:
          Platform.OS === 'android'
            ? imageList[index]?.uri
            : imageList[index]?.uri?.replace('file://', ''),
        type: imageList[index]?.type,
        name: imageList[index]?.uri?.split('/').pop(),
      };
      formData.append('images', files);
    }

    let apiAddress = `http:/localhost/api/students/file/upload`;
 
    fetch(apiAddress, {
      method: 'POST',
      headers: {
        Authorization:'Bearer  token”,
       body: formData,
    })

**Comment by dzpt** [comment]
got the same issue on ios, with or without debugging mode.
this is `fetch` error on RN
