### ISSUE TITLE
Invalid behavior Pressable in ScrollView

### ISSUE THREAD

**Issue by jfrolich** [facebook/react-native#30563]
## Description
The `delayPressIn` was set to 0 in this commit. https://github.com/facebook/react-native/commit/86ffb9c41e033f59599e01b7ad016706b5f62fc8. This removes the delay for pressing a button. This is fine if the button is not in a `ScrollView` but this delay is designed to not trigger `pressIn` while scrolling (see native iOS touchables). So basically every `Pressable` that's being used in a `ScrollView` has invalid behavior.

## React Native version:
0.63.4

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Put a pressable in a `ScrollView`
2. Try to scroll above a button
3. The button triggers

## Expected Results
There should be a way to set this delay (it is `delayPressIn` is not available on the `Pressable` component). I think it best to:

- Set the default back to 130ms
- make the delay configurable on the `Pressable` component

This is because in my experience most Pressables are part of a ScrollView, and if they're not part of a `ScrollView`, the small delay is unnoticeable (it might even be the same for native controls). If a delay of 130ms is not acceptable (perhaps in a game scenario or something like that) it can be configured.

**Comment by Firesoul18** [comment]
Does anyone have answer for this problem. I have a Pressable in ScrollView, but the pressable doesn't let me scroll because the scroll trigers the press event

**Comment by GaylordP** [comment]
Hello @Firesoul18 , @jfrolich :)

I have exactly the same problem ([I've already asked the question here, but no relevant answer](https://stackoverflow.com/questions/78706007/conflict-when-using-pressable-in-scrollview-on-ios)). Have you found a solution?

**Comment by pranshuchittora** [comment]
Hey, I just stumbled upon the same issue I have a `Pressable` (a big one) inside a `ScrollView` and whenever I try to scroll by starting my gesture on the `Pressable` it triggers the click action. 

The way I fixed this is by changing the press action handler from `onPressIn` to `onPress`.
Hope this helps.
