### ISSUE TITLE
when run "npm install -g react-native", stop at "react-tools → aft"

### ISSUE THREAD

**Issue by jjjjjjas** [facebook/react-native#3056]
run:

    npm install -g react-native

stop at:
    
    loadDep:react-tools → aft ▐           ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟

hang long long time.

system:
MacBook-Pro, Darwin Kernel Version 14.0.0
node: v4.0.0
npm: v3.3.4

**Comment by ide** [comment]
npm 3 is not supported right now and is known to be slow. Also make sure you have a clear internet connection to npm and github.

**Comment by jjjjjjas** [comment]
@ide thanks, i switch npm to v2.14.6, the problem is solution.

**Comment by yinzSE** [comment]
I also met the same problem,
and i change to v2.14.6, but it's still no use;
