### ISSUE TITLE
[IOS] Compatibility with Oracle Responsys

### ISSUE THREAD

**Issue by tony-tsx** [facebook/react-native#30574]
## Description
Problems with the integration with Oracle Responsys and React Native, I looked for many solutions but none worked, for example using use_frameworks! however when I use it it conflicts with use_flipper! in Podfile, I also checked if it was a header problem in the framework but also. So I started another project from scratch using just the xcode quick start and then I did the integration and it worked, but not with react-native.

I also tried to use boost-for-react-native, but the error remains.

I followed the documentation step by step, but as Oracle Responsys does not support cross platform tools, there is no point in using them.

Another situation is also that I made the integration for Android and everything worked, the problem is really in IOS.

#### Error message:

Undefined symbols for architecture x86_64:
  "boost::re_detail_106300::perl_matcher<char const*, std::__1::allocator<boost::sub_match<char const*> >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::find()", referenced from:
      bool boost::regex_search<char const*, std::__1::allocator<boost::sub_match<char const*> >, char, boost::regex_traits<char, boost::cpp_regex_traits<char> > >(char const*, char const*, boost::match_results<char const*, std::__1::allocator<boost::sub_match<char const*> > >&, boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, boost::regex_constants::_match_flags, char const*) in libFlipper-Folly.a(Uri.o)
  "boost::re_detail_106300::perl_matcher<char const*, std::__1::allocator<boost::sub_match<char const*> >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::match()", referenced from:
      bool boost::regex_match<char const*, std::__1::allocator<boost::sub_match<char const*> >, char, boost::regex_traits<char, boost::cpp_regex_traits<char> > >(char const*, char const*, boost::match_results<char const*, std::__1::allocator<boost::sub_match<char const*> > >&, boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, boost::regex_constants::_match_flags) in libFlipper-Folly.a(Uri.o)
  "folly::detail::crc32c_combine_hw(unsigned int, unsigned int, unsigned long)", referenced from:
      folly::crc32c_combine(unsigned int, unsigned int, unsigned long) in libFlipper-Folly.a(Checksum.o)
  "folly::detail::crc32c_combine_sw(unsigned int, unsigned int, unsigned long)", referenced from:
      folly::crc32c_combine(unsigned int, unsigned int, unsigned long) in libFlipper-Folly.a(Checksum.o)
  "folly::detail::crc32c_hw(unsigned char const*, unsigned long, unsigned int)", referenced from:
      folly::crc32c(unsigned char const*, unsigned long, unsigned int) in libFlipper-Folly.a(Checksum.o)
  "yarpl::credits::add(long long, long long)", referenced from:
      yarpl::flowable::details::EmiterSubscription<long long>::request(long long) in libFlipper-RSocket.a(Flowables.o)
      yarpl::flowable::details::EmiterSubscription<rsocket::Payload>::request(long long) in libFlipper-RSocket.a(RequestResponseThroughputTcp.o)
      yarpl::flowable::details::EmiterSubscription<rsocket::Payload>::request(long long) in libFlipper-RSocket.a(StreamThroughputMemory.o)
      yarpl::flowable::details::EmiterSubscription<rsocket::Payload>::request(long long) in libFlipper-RSocket.a(StreamThroughputTcp.o)
  "yarpl::credits::consume(long long&, long long)", referenced from:
      yarpl::flowable::details::TrackingSubscriber<long long>::onNext(long long) in libFlipper-RSocket.a(Flowables.o)
      yarpl::flowable::details::TrackingSubscriber<rsocket::Payload>::onNext(rsocket::Payload) in libFlipper-RSocket.a(RequestResponseThroughputTcp.o)
      yarpl::flowable::details::TrackingSubscriber<rsocket::Payload>::onNext(rsocket::Payload) in libFlipper-RSocket.a(StreamThroughputMemory.o)
      yarpl::flowable::details::TrackingSubscriber<rsocket::Payload>::onNext(rsocket::Payload) in libFlipper-RSocket.a(StreamThroughputTcp.o)
  "folly::init(int*, char***, bool)", referenced from:
      _main in libFlipper-RSocket.a(Benchmarks.o)
  "boost::re_detail_106300::verify_options(unsigned int, boost::regex_constants::_match_flags)", referenced from:
      boost::re_detail_106300::perl_matcher<std::__1::__wrap_iter<char const*>, std::__1::allocator<boost::sub_match<std::__1::__wrap_iter<char const*> > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::find_imp() in libFlipper-Folly.a(Benchmark.o)
  "boost::re_detail_106300::put_mem_block(void*)", referenced from:
      boost::re_detail_106300::perl_matcher<std::__1::__wrap_iter<char const*>, std::__1::allocator<boost::sub_match<std::__1::__wrap_iter<char const*> > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::unwind_extra_block(bool) in libFlipper-Folly.a(Benchmark.o)
      boost::re_detail_106300::save_state_init::~save_state_init() in libFlipper-Folly.a(Benchmark.o)
  "boost::re_detail_106300::get_default_error_string(boost::regex_constants::error_type)", referenced from:
      boost::re_detail_106300::cpp_regex_traits_implementation<char>::error_string(boost::regex_constants::error_type) const in libFlipper-Folly.a(Benchmark.o)
  "___darwin_check_fd_set_overflow", referenced from:
      _RAND_poll in libcrypto.a(rand_unix.o)
  "folly::detail::crc32_combine_hw(unsigned int, unsigned int, unsigned long)", referenced from:
      folly::crc32_combine(unsigned int, unsigned int, unsigned long) in libFlipper-Folly.a(Checksum.o)
  "folly::detail::crc32_combine_sw(unsigned int, unsigned int, unsigned long)", referenced from:
      folly::crc32_combine(unsigned int, unsigned int, unsigned long) in libFlipper-Folly.a(Checksum.o)
  "boost::re_detail_106300::cpp_regex_traits_implementation<char>::transform_primary(char const*, char const*) const", referenced from:
      boost::cpp_regex_traits<char>::transform_primary(char const*, char const*) const in libFlipper-Folly.a(Benchmark.o)
  "boost::re_detail_106300::cpp_regex_traits_implementation<char>::transform(char const*, char const*) const", referenced from:
      boost::cpp_regex_traits<char>::transform(char const*, char const*) const in libFlipper-Folly.a(Benchmark.o)
  "boost::re_detail_106300::perl_matcher<char const*, std::__1::allocator<boost::sub_match<char const*> >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::construct_init(boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, boost::regex_constants::_match_flags)", referenced from:
      boost::re_detail_106300::perl_matcher<char const*, std::__1::allocator<boost::sub_match<char const*> >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::perl_matcher(char const*, char const*, boost::match_results<char const*, std::__1::allocator<boost::sub_match<char const*> > >&, boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, boost::regex_constants::_match_flags, char const*) in libFlipper-Folly.a(Uri.o)
  "boost::re_detail_106300::get_mem_block()", referenced from:
      boost::re_detail_106300::perl_matcher<std::__1::__wrap_iter<char const*>, std::__1::allocator<boost::sub_match<std::__1::__wrap_iter<char const*> > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::extend_stack() in libFlipper-Folly.a(Benchmark.o)
      boost::re_detail_106300::save_state_init::save_state_init(boost::re_detail_106300::saved_state**, boost::re_detail_106300::saved_state**) in libFlipper-Folly.a(Benchmark.o)
  "boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::do_assign(char const*, char const*, unsigned int)", referenced from:
      boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::assign(char const*, char const*, unsigned int) in libFlipper-Folly.a(Benchmark.o)
      boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::assign(char const*, char const*, unsigned int) in libFlipper-Folly.a(Uri.o)
  "boost::re_detail_106300::raise_runtime_error(std::runtime_error const&)", referenced from:
      void boost::re_detail_106300::raise_error<boost::regex_traits_wrapper<boost::regex_traits<char, boost::cpp_regex_traits<char> > > >(boost::regex_traits_wrapper<boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, boost::regex_constants::error_type) in libFlipper-Folly.a(Benchmark.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

#### Print error:
![image](https://user-images.githubusercontent.com/45977425/101945531-1d3fff80-3bcd-11eb-9e43-a7b9bf35915e.png)

## React Native version:
info Fetching system and libraries information...
System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i3-8100B CPU @ 3.60GHz
    Memory: 2.65 GB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.15.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.2/12B45b - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_272 - /usr/local/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Start React Native IOS project.
2. Try integration with Oracle Reponsys only SDK
3. Try to run app in IOS simulador

## Expected Results
Compile successfully

## Snack, code example, screenshot, or link to a repository:
Oracle Responsys documentation step by step: https://docs.oracle.com/en/cloud/saas/marketing/responsys-develop-mobile/ios/step-by-step/
Oracle Responsys SDK: https://www.oracle.com/downloads/applications/cx/responsys-mobile-sdk.html

**Comment by liangjianyu** [comment]
same problem，i want to know

**Comment by BooYeu** [comment]
same problem

**Comment by BooYeu** [comment]
I just update the 
 react-native-camera               ^3.42.3  →  ^3.43.0     
 react-native-gesture-handler      ^1.10.2  →  ^1.10.3     
 react-native-reanimated           ^1.13.2  →   ^2.0.0     
 react-native-screens              ^2.17.1  →  ^2.18.1     
 react-native-vector-icons          ^8.0.0  →   ^8.1.0     
 @babel/core                       ^7.13.1  →  ^7.13.8     
 @babel/runtime                    ^7.13.2  →  ^7.13.9     
 eslint                            ^7.20.0  →  ^7.21.0     
 metro-react-native-babel-preset   ^0.65.1  →  ^0.65.2     
 react-test-renderer 
then I can't run the project in iOS

**Comment by tony-tsx** [comment]
The official integration of oracle responsys for react-native has been released, so there is no longer a need for this compatibility to be done manually. I will be closing this issue because of that.

Look:
[Official Website](https://docs.oracle.com/en/cloud/saas/marketing/responsys-develop-mobile/react/react.htm#ReactNativePlugin)
[Repository](https://github.com/oracle/pushiomanager-react-native)
