### ISSUE TITLE
FlatList 2 items grid with odd items count gets out of bounds error

### ISSUE THREAD

**Issue by sergeymild** [facebook/react-native#30570]
## Description

For example i have a FlatList with `numColumns` 2
and items array with length of 7
when i am using Mobx it complains that FlatList trying get out of bounds element
thats because in FlatList.js in mehtod `_getItem` on line 485 no check out of bounds before get from array.
So i think need make something like this:
```
const itemIndex = index * numColumns + kk;
if (itemIndex > data.lenght - 1) continue;
const item = data[itemIndex];
```

## React Native version:
react: 16.13.1 => 16.13.1 
react-native: 0.63.3 => 0.63.3

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Create Mobx store with observable array with 7 items in it
2. show FlatList with numColumns 2 and pass as items Mobx observable items array
3. The error with be displayed

**Comment by kopylash** [comment]
Any updates on this? We have the same issue. I can provide more details if needed

**Comment by kopylash** [comment]
Probably related to https://github.com/facebook/react-native/issues/15167
FlatList requires plain JS array, but in our case we pass ObservableArray from Mobx

**Comment by sergeymild** [comment]
Any updates on this?
