### ISSUE TITLE
numberOfLines prop has no effect on multiline TextInput ?

### ISSUE THREAD

**Issue by a-eid** [facebook/react-native#30584]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
when providing a numberOfLines prop to `multiline` `TextInput` it has no effect.

## React Native version:
Run `react-native info` in your terminal and copy the results here.

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.
```tsx

<TextInput multiLine scrollEnabled numberOfLines={4} />

```

## Expected Results

TextInput should not exceed 4 lines.

## Snack, code example, screenshot, or link to a repository:

```tsx

<TextInput multiLine scrollEnabled numberOfLines={4} />

```

**Comment by ravirajn22** [comment]
Create an expo snack that reproduces this issue.

**Comment by a-eid** [comment]
snack: 

https://snack.expo.dev/@aeid/arrogant-french-fries

**Comment by hannojg** [comment]
On which OS are you seeing this issue? `numberOfLines` is currently an android only prop

**Comment by a-eid** [comment]
@hannojg actually I don't remember, it's been a while.
