### ISSUE TITLE
[iOS] selectTextOnFocus won't work after upgrading from 0.61 to 0.62

### ISSUE THREAD

**Issue by ikotsov** [facebook/react-native#30585]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
If you include a `TextInput` in a page and set the props `autoFocus` and `selectTextOnFocus` to be true then the text inside the input (provided the fact that there is a value for the input on mount) the text inside the input is not selected. This happens only in iOS. In Android it works correctly. 

It works as expected in 0.61 version but for some reason after the upgrade to 0.62 it does not. The aformentioned props can be found [here](https://reactnative.dev/docs/0.62/textinput#selecttextonfocus).

## React Native version:
```
info Fetching system and libraries information...
System:
    OS: macOS 11.0.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 167.37 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.5.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.7, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.1
      System Images: android-29 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 11.7/11E801a - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_262 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: ^0.62.2 => 0.62.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
1. Include a `<TextInput autofocus selectTextOnFocus value="myValue" />` in a screen
2. The text will not be selected (highlighted)

## Expected Results
I expected the text to be selected inside the input on mount.

## Snack, code example, screenshot, or link to a repository:
```
   <View>
      {Platform.OS === 'ios' && ( // FIXME: This is a hack to make `selectTextOnFocus` work, otherwise it won't. Probably because of the upgrade to 0.62.
        <TextInput style={{ display: 'none' }} autoFocus selectTextOnFocus />
      )}
      <TextInput
        style={styles.input}
        onChangeText={text => onChangeText(text)}
        value={value}
        placeholder={inputLabel}
        autoFocus
        selectTextOnFocus
      />
   </ View>
```

The first `<TextInput />` has been added as a workaround. I noticed that this fixes the issue BUT it is really weird. The behavior is not the one expected.

**Comment by grifotv** [comment]
I'm having this issue in iOS with RN `0.62.2` only when the `value` prop is defined in the `TextInput`. As a workaround I'm considering controlling the value with `setNativeProps` https://reactnative.dev/docs/direct-manipulation#setnativeprops-to-clear-textinput-value

@ikotsov Wondering if you found any other workaround.

**Comment by grifotv** [comment]
Also noticed that when `multiline` is set, the `selectTextOnFocus` prop works as expected. Hence this PR https://github.com/facebook/react-native/pull/29847

**Comment by ikotsov** [comment]
> I'm having this issue in iOS with RN `0.62.2` only when the `value` prop is defined in the `TextInput`.
> 
> As a workaround I'm considering controlling the value with `setNativeProps` https://reactnative.dev/docs/direct-manipulation#setnativeprops-to-clear-textinput-value
> 
> @ikotsov Wondering if you found any other workaround?

Nope, no other than the one mentioned in the description. Also the `multiline` workaround does not work in my case 😕

**Comment by flogy** [comment]
Not working for me as well using `react-native@0.63.4` and testing with an `iPhone 11` using `iOS 14.4.2`...

**Comment by owencraston** [comment]
Having the same issue  on iOS with `"react-native": "0.66.3",`.
- adding `multiline` fixes the issue but in my case we can't have the input be multiline.
- This occurred when putting the TextInput field inside a [reanimated view](https://github.com/software-mansion/react-native-reanimated).

**Comment by owencraston** [comment]
> Having the same issue on iOS with `"react-native": "0.66.3",`.
> 
> * adding `multiline` fixes the issue but in my case we can't have the input be multiline.
> * This occurred when putting the TextInput field inside a [reanimated view](https://github.com/software-mansion/react-native-reanimated).

I was able to fix this with the following ugly code
```
  InteractionManager.runAfterInteractions(() => {
    // Needed to manually selectTextOnFocus on iOS
    // https://github.com/facebook/react-native/issues/30585
    if (inputRef.current && autocompleteValue) {
      inputRef.current.setNativeProps({
        selection: { start: 0, end: autocompleteValue.length },
      });
    }
  });
```
where `autocompleteValue` is the local input state that is set in `value={autocompleteValue}` and changed with `onChangeText={setAutocompleteValue}`.
`inputRef` is defined as `const inputRef = useRef<TextInput | null>(null);`

**Comment by jwueller** [comment]
Also doesn't work on Android with 0.68.2.

**Comment by pascallapointe** [comment]
This issue still present in "react-native": "0.70.4".

Found on iOS, didn't test on android.

`selectTextOnFocus` work only if `multiline` is set to `TRUE`, which is a problem.

Tried without any other props or handler, the issue remain.

In the meantime, here my workaround using the `onFocus` property:

```typescript
    
    onFocus={e => 
         // Workaround for selectTextOnFocus={true} not working
         e.currentTarget.setNativeProps({
             selection: { start: 0, end: _value?.length },
         });
    }

```
Where `_value` is the text input state controlled through `onChangeText`.

**Comment by Relax594** [comment]
Using RN 0.70.9

This is only an issue on iOS. Android is working as expected.

**Comment by Stephen-Song** [comment]
> Using RN 0.70.9
> 
> This is only an issue on iOS. Android is working as expected.

how are u passing the props to textinput, i found that it 's not working on android as expected.

**Comment by rozhkovs** [comment]
I'm facing this on Android.

**Comment by cortinico** [comment]
Closing as this version of React Native is several years old. Please re-open a new issue against the latest stable if the issue persists
