### ISSUE TITLE
Cannot pass callback function or Promise to RCTUIManager.dispatchViewManagerCommand 

### ISSUE THREAD

**Issue by mrousavy** [facebook/react-native#30587]
## Description

Native Modules can export native methods using `RCT_EXPORT_METHOD` (or `RCT_EXTERN_METHOD`). Using this, we can pass functions as arguments so the native method can call back to JS (`RCTResponseSenderBlock`/`RCTResponseErrorBlock`). Alternatively, we can also use Promises (`RCTPromiseResolveBlock`/`RCTPromiseRejectBlock`).

While this works great for normal methods, this somehow does not work for instance-specific methods (`UIManager.dispatchViewManagerCommand`).

#### Normal arguments:

```objc
RCT_EXTERN_METHOD(
  someFuncOnMyViewManager:(nonnull NSNumber *)node
  count:(nonnull NSNumber *)count
)
```

Works ✅ 

#### Promises:

```objc
RCT_EXTERN_METHOD(
  someFuncOnMyViewManager:(nonnull NSNumber *)node
  resolve:(RCTPromiseResolveBlock)resolve
  reject:(RCTPromiseRejectBlock)reject
)
```

Doesn't work ❌ 

(Error: Malformed JS sizes/`"JS Field sizes are different"`)

#### Callbacks:

```objc
RCT_EXTERN_METHOD(
  someFuncOnMyViewManager:(nonnull NSNumber *)node
  onSuccess:(RCTResponseSenderBlock)onSuccess
  onError:(RCTResponseErrorBlock)onError
)
```

Doesn't work ❌ 

(Error: `[...., [<< Function >>, << Function >>]] cannot be used as a native method argument`)

#### Background

As you probably noticed from the use of `RCT_EXTERN_METHOD`, I am using Swift. Not sure if that makes a difference though.

Also, this is what I tried from JS:

```js
  updateNative = () => {
    UIManager.dispatchViewManagerCommand(
      findNodeHandle(this.ref),
      UIManager["SomeNativeView"].Commands.someFuncOnMyViewManager,
      [(x) => console.log(x), (e) => console.error(e)]
    );
  }
```

and

```js
  const onSuccess = (x) => console.log(x)
  const onError = (e) => console.error(e)
  updateNative = () => {
    UIManager.dispatchViewManagerCommand(
      findNodeHandle(this.ref),
      UIManager["SomeNativeView"].Commands.someFuncOnMyViewManager,
      [onSuccess, onError]
    );
  }
```

and

```js
  return new Promise((resolve, reject) => {
    updateNative = () => {
      UIManager.dispatchViewManagerCommand(
        findNodeHandle(this.ref),
        UIManager["SomeNativeView"].Commands.someFuncOnMyViewManager,
        [resolve, reject]
      );
    }
  });
```

## React Native version:

0.63.4

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Create ViewManager + Native Module
2. Create functions with syntax above
3. Call that from JS

## Expected Results

I expect methods from the ViewManager to be able to use Callbacks or Promises.

**Comment by milesziemer** [comment]
@mrousavy I'm having the same issue, did you ever solve this?

**Comment by OlegDeg** [comment]
> Yes, just don't use UIManager.dispatchViewManagerCommand. Create it as a normal method, pass node ID as argument.

@mrousavy Can you provide the code please?

**Comment by aiyuchen** [comment]
@mrousavy same question, I used `RCTUIManager.dispatchViewManagerCommand` to trigger `RCT_EXPORT_METHOD`，and add `@property` to `RCTDirectEventBlock` handle React props

**Comment by kesha-antonov** [comment]
> @milesziemer Yes, just don't use `UIManager.dispatchViewManagerCommand`. Create it as a normal method, pass node ID as argument.

Could you give example please?
