### ISSUE TITLE
Picture in picture using native module in android

### ISSUE THREAD

**Issue by AswathiRevathi** [facebook/react-native#30582]
Picture in picture using native module in android not triggering onPictureInPictureModeChanged callback
## Description
I am using native module to implement picture in picture mode for my app.App is going to picture in picture mode correctly but the callback  onPictureInPictureModeChanged is not triggering.Since this call back is not working,i couldn't check whether the app is in pip mode or not from native module side.I need to emit an event to react native when the pip window exits.This thing can be done if onPictureInPictureModeChanged is working.Or is there anyother options to do this
## React Native version:
0.63.2
## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.Create a native module 
2.OnHostPause calling enterPictureInPicture.onPictureInPictureModeChanged is getting triggered

## Expected Results
onPictureInPictureModeChanged should get called
## Snack, code example, screenshot, or link to a repository:
Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by dulmandakh** [comment]
Your module must implement LifecycleEventListener, then register itself as event listener. Please read https://reactnative.dev/docs/native-modules-android#listening-to-lifecycle-events
