### ISSUE TITLE
Container is falsy in LayoutAnimation

### ISSUE THREAD

**Issue by RobbyWH** [facebook/react-native#30581]
## Description
I have upgraded RN 0.63.2 to 0.64.0-rc.1, but getting error Container is falsy in LayoutAnimation, but when i upgrade from new project, it is working fine. 

## React Native version:
System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 3.09 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.18.3 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.6 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.1, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.1
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.1/12A7403 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_262 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.0-rc.1 => 0.64.0-rc.1
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
1. Follow the step in https://react-native-community.github.io/upgrade-helper/?from=0.63.2&to=0.64.0-rc.1
2. Build & Clean the project
3. Build success
4. Error Container is Falsy in LayoutAnimation

## Expected Results
No Error Container is Falsy in LayoutAnimation

## Snack, code example, screenshot, or link to a repository:
<img width="428" alt="Screen Shot 2020-12-08 at 14 14 35" src="https://user-images.githubusercontent.com/11469477/102024348-14fde500-3dc4-11eb-80e4-c01929a58a19.png">

**Comment by madox2** [comment]
I am facing the same problem upgrading from 0.60.4 to 0.64.0-rc.1.

**Comment by renopp** [comment]
@RobbyWH @RobbyWH 

This error caused by optional chaining, you can fix it by patch LayoutAnimation.js and remove optional chaining 
or
You can add babel plugin proposal optional chaining at your babelrc

**Comment by renopp** [comment]
@madox2 @RobbyWH 
This error caused by optional chaining, you can fix it by patch LayoutAnimation.js and remove optional chaining
or
You can add babel plugin proposal optional chaining at your babelrc

**Comment by piaskowyk** [comment]
Thanks @renopp 🙌
It works for me after update to 0.64.0-rc.2

**Comment by javiercr** [comment]
I'm having the same problem but I don't understand why do we need to that extra plugin manually. I thought that was added by RN itself here (since 0.56):
https://github.com/facebook/react-native/commit/aa6f394c4236e5a4998c3be8ed61ec1bab950775

**Comment by javiercr** [comment]
Adding the plugin manually doesn't fix the problem for us. Is there a way to debug what plugins are being used by babel?

**Comment by javiercr** [comment]
The only workaround we've found is to manually remove all optional chaining from LayoutAnimation.js.

To do so we've created a patch:
https://gist.github.com/javiercr/6359af65d8578568d4bc7ed159744464

It can be automatically applied using [patch-package](https://www.npmjs.com/package/patch-package) (store it on `./patches/react-native+0.64.patch`).

**Comment by habovh** [comment]
This seems to stem from [metro-react-native-babel-preset](https://github.com/facebook/metro/tree/master/packages/metro-react-native-babel-preset) not adding properly the [@babel/plugin-syntax-optional-chaining](https://babeljs.io/docs/en/babel-plugin-proposal-optional-chaining) plugin.

I'll report the issue on [metro](https://github.com/facebook/metro)'s repo.

You may fix this by adding the `@babel/plugin-syntax-optional-chaining` in your dev dependencies and as a plugin in your `.babelrc` config instead of using `patch-package`. Although I'm not sure of the consequences if you're building for Hermes engine, since this specific transform seems to be disabled by `metro-react-native-babel-preset` when Hermes is enabled.

**Comment by computerjazz** [comment]
I had this issue after upgrading my project from 0.63.3 -> 0.64.1 and was able to fix it without any patches or extra plugins.

After deleting my `yarn.lock` and reinstalling, the error went away, suggesting a stale dependency somewhere. Obviously deleting `yarn.lock` isn't the actual solution, so I reinstated my `yarn.lock`, then manually ran `yarn upgrade metro-react-native-babel-preset` and saw a bunch of changes in the lockfile, even though I had manually specified `"metro-react-native-babel-preset": "^0.64.0"` before running `yarn` originally.  I then relaunched the packager and the app loaded without issue.

Possibly related to the semver "magic 0" case, where 0.x.x deps don't follow the same rules as others? https://dev.to/malykhinvi/semver-0-x-x-46e7

**Comment by christopherdro** [comment]
@computerjazz `yarn upgrade metro-react-native-babel-preset` resolved the issue for me. Thanks! 😄
