### ISSUE TITLE
Issue Running React Native project on simulator on apple silicon m1

### ISSUE THREAD

**Issue by vivekvt** [facebook/react-native#30599]
I am facing issue while running react native project on my MacBook Pro M1

**com.facebook.react.JavaScript (11): EXC_BREAKPOINT (code=EXC_I386_BPT, subcode=0x0)**

<img width="1439" alt="Screenshot 2020-12-16 at 2 29 20 AM" src="https://user-images.githubusercontent.com/50275510/102340772-c11e0800-3f4b-11eb-8a7b-8e6a7e48a39e.png">

## React Native version:
**% react-native info**
info Fetching system and libraries information...
(node:8776) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
System:
    OS: macOS 11.1
    CPU: (8) x64 Apple M1
    Memory: 50.04 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.1 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    Android SDK:
      API Levels: 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.2/12B45b - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_275 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by Mhmetengineer** [comment]
same problem..  +1

**Comment by Elderkly** [comment]
+1

**Comment by zombie6888** [comment]
the same issue here, there is discussion on this issue at apple community forum https://discussions.apple.com/thread/252137682?answerId=254248231022#254248231022

**Comment by skullet** [comment]
+1 This is happening for me with Xcode 12.4

**Comment by jackdewhurst** [comment]
Same problem, anything below iOS 14 simulator crashes on launch with this error

**Comment by francoserio** [comment]
I have this very same problem with iOS 12 simulators only. Any update on this?

**Comment by kilimchoi** [comment]
any workaround?
