### ISSUE TITLE
$ react-native -v

### ISSUE THREAD

**Issue by youjiaqi421** [facebook/react-native#30608]
$ react-native -v
react-native-cli: 0.1.10
react-native: 0.21.0-rc

$ react-native run-android
Starting JS server...
Building and installing the app on the device (cd android && ./gradlew installDebug)...

FAILURE: Build failed with an exception.
- What went wrong:
  A problem occurred configuring project ':app'.
  
  > Could not resolve all dependencies for configuration ':app:_debugCompile'.
  > Could not resolve com.facebook.react:react-native:0.19.+.
  >  Required by:
  >      Mad:app:unspecified
  > Could not resolve com.facebook.react:react-native:0.19.+.
  >      > Failed to list versions for com.facebook.react:react-native.
  >         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/facebook/react/react-native/maven-metadata.xml.
  >            > Could not GET 'https://jcenter.bintray.com/com/facebook/react/react-native/maven-metadata.xml'.
  >               > Connection to https://jcenter.bintray.com refused
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4 mins 15.891 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

_Originally posted by @Heaven1619 in https://github.com/facebook/react-native/issues/5884#issuecomment-187205618_

**Comment by luco** [comment]
https://stackoverflow.com/questions/35394570/react-native-build-failed-with-an-exception
