### ISSUE TITLE
xcode12.3  'libjpush-ios-3.2.8' is missing

### ISSUE THREAD

**Issue by lihua123569** [facebook/react-native#30601]
xcode12.3  'libjpush-ios-3.2.8' is missing
## React Native version:
rn 0.57.8

## Steps To Reproduce
1.xcode启动ios
2.

## Expected Results
xcode12.3  'libjpush-ios-3.2.8' is missing

**Comment by dulmandakh** [comment]
Please test your code with latest version of RN, 0.57 is too old and unmaintained.
