### ISSUE TITLE
React Native suddenly stops firing fetch requests to server

### ISSUE THREAD

**Issue by petter-kaspersen** [facebook/react-native#30604]
## Description
When starting the app everything works fine, networks requests are being fired, and data is being loaded. At certain (unknown) conditions the app suddenly stops loading new data, and most of the time doesn't even send data to the remote server. Instead it gets the mystical error "Network Request Failed".

## React Native version:

info Fetching system and libraries information...
System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 3.66 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
       NOT RELEVANT
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.0/12A7209 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_265 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: ~16.11.0 => 16.11.0 
    react-native: ^0.62.2 => 0.62.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    react-native: Not Found

## Steps To Reproduce

1. Fire working fetch request 
2. Fetch request suddenly stops sending to the server.

## Expected Results
Fetch request should fire normally

## Snack, code example, screenshot, or link to a repository:
There's not too much to it, it's a simple GET request with no headers.

**Comment by Findiglay** [comment]
Also experiencing this today with 0.64 and xcode 12 🤔

**Comment by favorie** [comment]
I'm suffering from same issue. Typically it works fine, but sometimes fetch start to throws "Network request failed" error before communicate with server. App termination and restart doesn't work, but reconnect to router or internet connection make it work. Any one have solution?

**Comment by dzpt** [comment]
i'm suffering the same issue on ios.
this is stupid and critical error.
fetch is the main lib is required to function almost all react apps.

**Comment by petter-kaspersen** [comment]
So a small update on this:

I was able to circumvent the issue by deploying a small proxy backend, so basically instead of communicating directly with the backend I deployed a small DigitalOcean Node.js/Express server that just mirrors the requests to the actual backend. This solved the problem for me. Trying to figure out why.

**Comment by diegolmello** [comment]
@petter-kaspersen were you able to find the reason?

**Comment by Nader-CS** [comment]
anyone solves this
