### ISSUE TITLE
FlatList in KeyboardAvoidingView ignores keyboard's height

### ISSUE THREAD

**Issue by zfanta** [facebook/react-native#30619]
## Description

`FlatList` in `KeyboardAvoidingView` ignores keyboard's height and `renderItem`s at bottom of `FlatList` are hidden. If I use `inverted` property in `FlatList` it works as I expected.

## React Native version:

```
System:
    OS: macOS 11.0.1
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 2.28 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.18.2 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 26.0.2, 27.0.3, 28.0.2, 28.0.3
      System Images: android-23 | Google APIs Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1.1 4.1.1
    Xcode: 12.2/12B45b - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_66 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.3 => 0.63.3
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce

1. Open project https://snack.expo.io/@zfanta/flat-list in iOS device
2. Touch text input in bottom of screen to show keyboard

## Expected Results

Items at bottom are hidden.

https://user-images.githubusercontent.com/6619332/102712475-f38d8380-4304-11eb-9a45-e18881f2c45c.MP4

If I use `inverted` property Items at bottom are not hidden.

https://user-images.githubusercontent.com/6619332/102712477-fb4d2800-4304-11eb-8a70-4c6f8837eb82.MP4

## Snack, code example, screenshot, or link to a repository:

https://snack.expo.io/@zfanta/flat-list

**Comment by rgbedin** [comment]
Any workarounds/updates on this issue? Thank you.

**Comment by timabilov** [comment]
+

**Comment by FrankyCTY** [comment]
Any one find a solution, or everyone moved to flutter?

**Comment by abehan7** [comment]
why don't you reverse your array with FlatList in inverted true?

i also got that problem but i found solution from inverted true


and this is my code 

`
const ChatScreen: FC = () => {
  const [input, setInput] = useState<string>("");
  const [messages, setMessages] = useState<IMessage[]>(dummy.reverse());
  const { params } = useRoute();
  const onPress = () => {};
  const sendMessage = () => {};
  const navigation = useNavigation();

  useLayoutEffect(() => navigation.setOptions({ headerShown: false }), []);

  const renderItem = ({ item: message }: { item: IMessage }) =>
    message?.uid === user.uid ? (
      <SenderMessage key={message.id} text={message.text} />
    ) : (
      <ReceiverMessage
        key={message.id}
        text={message.text}
        photoURL={user.photoURL}
      />
    );

  return (
    <SafeAreaView style={tw`flex-1`}>
      <Header title={user.name} callEnabled={true} />
      <KeyboardAvoidingView style={tw`flex-1`}>
        <TouchableWithoutFeedback onPress={Keyboard.dismiss}>
          <FlatList
            data={messages}
            style={tw`pl-4`}
            keyExtractor={(message) => message.id}
            renderItem={renderItem}
            inverted={true}
          />
        </TouchableWithoutFeedback>

        <View
          style={tw`flex-row bg-white justify-between items-center border-t border-gray-200 px-5 py-2`}
        >
          <TextInput
            style={tw`h-10 text-lg`}
            placeholder="Sned a Message..."
            onChangeText={setInput}
            value={input}
            onSubmitEditing={sendMessage}
          />
          <Button title="Send" color="#FF5864" onPress={onPress} />
        </View>
      </KeyboardAvoidingView>
    </SafeAreaView>
  );
};
`

**Comment by yasinized** [comment]
This worked for me `<FlatList onLayout={() => flatListRef.current.scrollToEnd({ animated: false })} ... />`

**Comment by gshoanganh** [comment]
you can do:

```
<KeyboardAvoidingView behavior='position' 
...  >
```

**Comment by sdavid501** [comment]
Here's a workaround, I had to use inverted with flex-direction:'column-reverse' in order to keep the order.

`<SafeAreaView style={{flex: 1}}>
      <KeyboardAvoidingView
        style={{flex: 1}}
        keyboardVerticalOffset={90}
        behavior={Platform.OS === 'ios' ? 'padding' : 'height'}>
           <FlatList 
               scrollEnabled={true} 
                inverted={true} 
                 contentContainerStyle={{flexGrow: 1, flexDirection: 'column-reverse'}} .../>
......
`

**Comment by griffinbaker12** [comment]
<KeyboardAvoidingView style={{ flex: 1 }} behavior="padding" >
            {isLoading ? <Text>Loading...</Text> :
                <View style={{
                    flex: 1
                }}>

                    <AnimatedFlashList
                        ListHeaderComponent={listHeader}
                        onScroll={onScroll}
                        scrollEventThrottle={16}
                        ref={flashListRef}
                        data={data}
                        estimatedItemSize={100}
                        onLayout={() => flashListRef?.current?.scrollToEnd({ animated: true })}
                        estimatedFirstItemOffset={100}
                        // extraData={dataUpdatedAt}
                        renderItem={renderItem}
                        contentContainerStyle={{ paddingTop: 120, paddingBottom: insets.bottom }}
                        showsVerticalScrollIndicator={false}
                        onEndReachedThreshold={0.7}
                        keyExtractor={keyExtractor}
                        onEndReached={fetchNextPage}
                    />
                </View>

            }
            <InputToolbar statusId={id} />
        </KeyboardAvoidingView >
    );
    
    worked for me

**Comment by hems** [comment]
I'm still having same issues in 2025 : D

anyone found an elegant solution?

**Comment by Iuriy-Budnikov** [comment]
lol 5 years :)

**Comment by KristijanKocev** [comment]
very lol haha still having this issue

**Comment by KristijanKocev** [comment]
> ```
>   <KeyboardAvoidingView style={{ flex: 1 }} behavior="padding" >
>         {isLoading ? <Text>Loading...</Text> :
>             <View style={{
>                 flex: 1
>             }}>
> 
>                 <AnimatedFlashList
>                     ListHeaderComponent={listHeader}
>                     onScroll={onScroll}
>                     scrollEventThrottle={16}
>                     ref={flashListRef}
>                     data={data}
>                     estimatedItemSize={100}
>                     onLayout={() => flashListRef?.current?.scrollToEnd({ animated: true })}
>                     estimatedFirstItemOffset={100}
>                     // extraData={dataUpdatedAt}
>                     renderItem={renderItem}
>                     contentContainerStyle={{ paddingTop: 120, paddingBottom: insets.bottom }}
>                     showsVerticalScrollIndicator={false}
>                     onEndReachedThreshold={0.7}
>                     keyExtractor={keyExtractor}
>                     onEndReached={fetchNextPage}
>                 />
>             </View>
> 
>         }
>         <InputToolbar statusId={id} />
>     </KeyboardAvoidingView >
> );
> 
> worked for me
> ```

This worked for me too
