### ISSUE TITLE
When Hermes is Enabled, Generated .abb release build Crashes After installed 

### ISSUE THREAD

**Issue by Joshmatjjen** [facebook/react-native#30617]
## Description
My App Crashes after Immidiately after lunch. Any time i enable Hermes,  and run:
**cd android && ./gradlew bundleRelease && cd ..**.  It Upload and .aab file. The when it is uploaded to playstore, installed and then when lunch, App Crash.  
After Logging crash, i got an error:  **"unable to load script make sure you are either running a metro server or that your bundle "index.android.bundle" is packaged correctly for release"**

## React Native version:
System:
    OS: Linux 4.15 Ubuntu 18.04.5 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i5-3360M CPU @ 2.80GHz
    Memory: 349.88 MB / 15.60 GB
    Shell: 5.4.2 - /bin/zsh
  Binaries:
    Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v12.13.0/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v12.13.0/bin/npm
    Watchman: 4.9.0 - /home/linuxbrew/.linuxbrew/bin/watchman
  SDKs:
    Android SDK:
      API Levels: 21, 22, 23, 24, 25, 26, 27, 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3
      System Images: android-24 | Google APIs Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-25 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-R | Google APIs Intel x86 Atom, android-R | Google APIs Intel x86 Atom_64, android-R | Google Play Intel x86 Atom, android-R | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 15.0.1 - /home/linuxbrew/.linuxbrew/opt/openjdk/bin/javac
    Python: 2.7.17 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.
0.  Enable hermes
1.  cd android && ./gradlew bundleRelease && cd ..
2.  upload generated .aab file to playstore or Extract with bundletool for apks
3.  Install apk (apk installed successfully)
4.  App Crash immediately after lunch

## Expected Results
     1. After Enabling Hermes
     2. Run bundleRelease
     3. Upload Generated .aab file to Google Play Store
     4  App lunch without crashing

```
     project.ext.react = [
    entryFile: "index.js",
    enableHermes: true,  // clean and rebuild if changing
    // extraPackagerArgs: [ '--minify=false' ],
    // bundleInRelease: true,
    // resourcesDirRelease: "src/main/res",
    // resourcesDirRelease: "src/release/res",
    // jsBundleDirRelease: "$buildDir/intermediates/merged_assets/release/out",
    // // bundleCommand: "ram-bundle", // open If hermes is false
    // // extraPackagerArgs: ["--indexed-ram-bundle"], // open If hermes is false
    // hermesCommand: "../../node_modules/hermes-engine/%OS-BIN%/hermes",
]

apply from: "../../node_modules/react-native/react.gradle"

def enableSeparateBuildPerCPUArchitecture = true

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = true
```

**Comment by DeniferSantiago** [comment]
same issue here

**Comment by Joshmatjjen** [comment]
@DeniferSantiago  try this : 

attach the line below to your package.json
and run "yarn release-aab"

"release-aab": "react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/build/intermediates/res/merged/release/ && rm -rf android/app/src/main/res/drawable-* && rm -rf android/app/src/main/res/raw/* && cd android && ./gradlew bundleRelease && cd ..",


if it fixed your error let me know.. if not, i can tell you another trick

**Comment by bansalakshay8** [comment]
Same issue with me as well. .aab is crashing from playstore. 

What the reason behind this ? Is it something related to gradle version?

**Comment by DeniferSantiago** [comment]
thanks for answering @Joshmatjjen , i have tried you but even when i run:
npx react-native run-android --variant release
the application closes after the splashscreen

**Comment by Joshmatjjen** [comment]
@DeniferSantiago  
Also, you should check your Gradle version
* First run: `**cd android && ./gradlew clean && cd ..** `
* Thhen check if drawable folders are in 'android/src/main/res'. if it exist, delete them all and also 'raw folder'
* Then: **`cd android && ./gradlew bundleRelease && cd ..`**
 and it work fine

**This is mine below (android/build.grade)**

> buildscript {
>      ext {
>         buildToolsVersion = "29.0.3"
>         // minSdkVersion = 16
>         minSdkVersion = 19
>         compileSdkVersion = 29
>         targetSdkVersion = 29
>         // FOr React-Native-IAP
>         androidXAnnotation = "1.1.0"
>         androidXBrowser = "1.0.0"
>         // Put here other AndroidX dependencies
>      }
>     repositories {
>         google()
>         jcenter()
>     }
>     dependencies {
>         classpath("com.android.tools.build:gradle:3.5.4")
>         // classpath("com.android.tools.build:gradle:4.1.0")
>         classpath 'com.google.gms:google-services:4.3.4'
>         // NOTE: Do not place your application dependencies here; they belong
>         // in the individual module build.gradle files
>     }
> }


**This is also my implementation of 'android/app/build.gradle'**

> project.ext.react = [
>     entryFile: "index.js",
>     enableHermes: true,  // clean and rebuild if changing
> ]
> 
> apply from: "../../node_modules/react-native/react.gradle"

> def enableSeparateBuildPerCPUArchitecture = true

> def enableProguardInReleaseBuilds = true

> def enableHermes = project.ext.react.get("enableHermes", false);


Hope it helps 🙂 👍

**Comment by unit-002** [comment]
>     * Thhen check if drawable folders are in 'android/src/main/res'. if it exist, delete them all and also 'raw folder'

I have the same issue but if I do your suggestion here and delete these folders then all my app icon and notification icon which is located on that folder will be gone

**Comment by PhamChien226** [comment]
hi @Joshmatjjen [Joshmatjjen](https://github.com/Joshmatjjen) 
not relevant 
but can you tell me how to log error in production 
my app it crashes on start to
i want to know what happens with my app
thank you so much
