### ISSUE TITLE
IOS Autocorrect bubble will not fire the TextInput onChangeText

### ISSUE THREAD

**Issue by plus-** [facebook/react-native#30614]
<img width="323" alt="Screenshot 2020-12-18 at 15 42 14" src="https://user-images.githubusercontent.com/841776/102627114-fee78000-4147-11eb-88e8-9ff388155eed.png">

## Description
Clicking the top bubble to correct the word will not work (text input value doesn't change), clicking the bottom predictive suggestion works properly (it will update the text input value).

## React Native version:
info Fetching system and libraries information...
(node:32782) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
System:
    OS: macOS 11.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 48.64 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.15.1 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3
      System Images: android-R | Google APIs Intel x86 Atom
      Android NDK: 22.0.6917172-beta1
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.3/12C33 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_222 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by plus-** [comment]
So I found it was because `contextMenuHidden` was true on that TextInput.

I'm not sure if this is intended or a bug. You can close this if this is intended.

**Comment by leonid-shevtsov** [comment]
Our issue has been resolved in RN 0.66.4
