### ISSUE TITLE
Android release APK is being crashed in react native 0.63.4. with error (com.facebook.react.common.JavascriptException: TypeError: null is not an object (evaluating 'l.setTimeout'), stack: ) debug build is working fine 

### ISSUE THREAD

**Issue by manpreetsingh3215** [facebook/react-native#30622]
## Description
FATAL EXCEPTION: mqt_native_modules
    Process: com.someName.prod, PID: 6280
    com.facebook.react.common.JavascriptException: TypeError: null is not an object (evaluating 'l.setTimeout'), stack:
    value@390:1391
    setTimeout@20:3277
    <unknown>@475:32851
## React Native version:
System:
    OS: macOS 11.0.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 354.21 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.9.0 - /usr/local/bin/node
    Yarn: 1.21.1 - ~/.yarn/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.2/12B45b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.8 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by manpreetsingh3215** [comment]
anyone please help, its been 3 days since i stuck here
package.json file seems :--->  
"dependencies": {
    "@codler/react-native-keyboard-aware-scroll-view": "^1.0.1",
    "@onfido/react-native-sdk": "^1.3.2",
    "@react-native-community/art": "^1.2.0",
    "@react-native-community/async-storage": "^1.7.1",
    "@react-native-community/clipboard": "^1.2.3",
    "@react-native-community/datetimepicker": "^2.6.2",
    "@react-native-community/geolocation": "^2.0.2",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-community/netinfo": "5.0.0",
    "@react-native-community/slider": "^3.0.3",
    "@react-native-firebase/app": "^10.2.0",
    "@react-native-firebase/auth": "^10.2.0",
    "@react-native-firebase/crashlytics": "^10.2.0",
    "@react-native-firebase/database": "^10.2.0",
    "@react-native-firebase/dynamic-links": "^10.2.0",
    "@react-native-firebase/firestore": "^10.2.0",
    "@react-native-firebase/iid": "^10.2.0",
    "@react-native-firebase/messaging": "^10.2.0",
    "@react-native-firebase/perf": "^10.2.0",
    "@react-native-firebase/storage": "^10.2.0",
    "axios": "^0.21.0",
    "crypto-js": "3.1.9-1",
    "encodeurl": "^1.0.2",
    "events": "^3.1.0",
    "hermes-engine": "^0.5.2-rc1",
    "install": "^0.13.0",
    "js-sha256": "^0.9.0",
    "libphonenumber-js": "^1.9.6",
    "lodash": "^4.17.15",
    "mobx": "^4.3.1",
    "mobx-react": "^5.2.3",
    "moment": "^2.22.1",
    "npm": "^6.14.5",
    "os": "^0.1.1",
    "prop-types": "^15.6.2",
    "react": "16.13.1",
    "react-dom": "^16.7.0-alpha.0",
    "react-native": "0.63.4",
    "react-native-actionsheet": "^2.4.2",
    "react-native-animatable": "^1.3.2",
    "react-native-app-intro-slider": "^3.0.0",
    "react-native-audio-recorder-player": "^2.5.1",
    "react-native-biometrics": "^1.7.0",
    "react-native-check-box": "^2.1.7",
    "react-native-code-push": "^6.4.0",
    "react-native-country-picker-modal": "^0.8.0",
    "react-native-crypto-js": "^1.0.0",
    "react-native-datepicker": "^1.7.2",
    "react-native-device-info": "^5.5.6",
    "react-native-dialog": "^5.6.0",
    "react-native-document-picker": "^4.0.0",
    "react-native-drawer": "^2.5.1",
    "react-native-elements": "^1.2.7",
    "react-native-file-viewer": "^2.0.2",
    "react-native-fix-image": "^2.0.1",
    "react-native-fs": "^2.16.6",
    "react-native-gallery-swiper": "^1.25.2",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-get-random-values": "^1.3.1",
    "react-native-hyperlink": "0.0.19",
    "react-native-image-base64": "^0.1.4",
    "react-native-image-crop-picker": "^0.34.1",
    "react-native-image-picker": "^0.27.2",
    "react-native-image-zoom-viewer": "^3.0.1",
    "react-native-interactable": "^2.0.1",
    "react-native-jitsi-meet": "^2.1.1",
    "react-native-keyboard-accessory": "^0.1.10",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-microphone-stream": "git://github.com/chadsmith/react-native-microphone-stream.git",
    "react-native-modal": "^11.5.6",
    "react-native-paper": "^4.1.0",
    "react-native-permissions": "^2.1.4",
    "react-native-phone-input": "^0.2.4",
    "react-native-picker-select": "^6.3.0",
    "react-native-popover-tooltip": "^1.1.4",
    "react-native-popup-menu": "^0.15.7",
    "react-native-progress": "^4.1.2",
    "react-native-reanimated": "^1.9.0",
    "react-native-redux-toast": "^1.0.3",
    "react-native-responsive-fontsize": "^0.4.3",
    "react-native-responsive-screen": "^1.4.0",
    "react-native-screens": "^2.9.0",
    "react-native-scrollable-tab-view": "^1.0.0",
    "react-native-sensitive-info": "^5.5.1",
    "react-native-sha256": "^1.3.6",
    "react-native-size-matters": "^0.1.4",
    "react-native-skeleton-content": "^1.0.18",
    "react-native-sound": "^0.11.0",
    "react-native-splash-screen": "^3.0.6",
    "react-native-star-rating": "^1.1.0",
    "react-native-swipeout": "^2.3.6",
    "react-native-vector-icons": "6.6.0",
    "react-native-video": "^4.4.5",
    "react-native-walkthrough-tooltip": "^1.1.11",
    "react-native-webview": "^10.9.2",
    "react-navigation": "^3.11.1",
    "react-navigation-backhandler": "^1.3.2",
    "react-navigation-tabs": "^2.7.0",
    "react-redux": "^5.1.0",
    "redux": "^3.7.2",
    "redux-logger": "^3.0.0",
    "redux-persist": "^6.0.0",
    "redux-thunk": "^2.3.0",
    "rn-fetch-blob": "^0.12.0",
    "rn-nodeify": "^6.0.1",
    "trusona-server-sdk": "^1.4.0",
    "uninstall": "0.0.0",
    "url": "^0.11.0"
  },

**Comment by sunilMamaearth** [comment]
I also face same issue with version
"react": "16.11.0",
 "react-native": "0.62.2",
But still I am not find solution.

**Comment by sunilMamaearth** [comment]
I find same issue with version
"react": "16.11.0",
  "react-native": "0.62.2",

please help me if any solution.

**Comment by manpreetsingh3215** [comment]
@sunilMamaearth 
it was coming , because i was using the code push and jitsi meet in the project and both had different bundleAssetName 

this issue was related to this in my case 

https://github.com/skrafft/react-native-jitsi-meet/issues/94

i hope this would be helpful if anyone have this one due to the specific reason
Thanks

**Comment by hanifmhd** [comment]
> @sunilMamaearth
> it was coming , because i was using the code push and jitsi meet in the project and both had different bundleAssetName
> 
> this issue was related to this in my case
> 
> [skrafft/react-native-jitsi-meet#94](https://github.com/skrafft/react-native-jitsi-meet/issues/94)
> 
> i hope this would be helpful if anyone have this one due to the specific reason
> Thanks

thanks bro i have been searching for 3 days and you save my life
