### ISSUE TITLE
File uploading failed using FormData API Request on Expo ejected Project with React-Native Version 0.63.4

### ISSUE THREAD

**Issue by tee4tayyab** [facebook/react-native#30623]
## Description
I have ejected the expo-cli SDK 39 Project to React-Native-Cli project.
 Everything is working except File uploading using FormData Api request with Axios/Fetch using Content-Type: "multipart/form-data". I have implemented all the available solutions but only FormData is not sent using network request.
I have tested the same code with many other projects having same or different versions of react native. and this code is working fine. but this issue is specific to this expo-ejected Project of React Native Cli.

## React Native version:
"react": 16.13.1,
"react-native": 0.63.4,
"axios": "^0.20.0",
"expo": "~39.0.2",
"expo-image-picker": "^8.4.0",

## Screenshot of the Code:
<img width="581" alt="Screenshot 2020-12-21 at 12 33 38 PM" src="https://user-images.githubusercontent.com/29449625/102751895-80c6eb80-438a-11eb-9eca-2d15ca02072f.png">

## Note

All other network request are working fine as desired. Only formData with header is not working.

**Comment by dzpt** [comment]
i'm suffering the same issue on ios

**Comment by rahulnainwal107** [comment]
I am getting same error.

**Comment by hoangtrieukd** [comment]
i have same issue

**Comment by xiaoliuxiansheng** [comment]
i have same issue
