### ISSUE TITLE
ios  react-native run-ios  

### ISSUE THREAD

**Issue by kingzeng** [facebook/react-native#30628]
![IMG_0285](https://user-images.githubusercontent.com/15261181/102872432-a2070500-447a-11eb-8aa3-67a3d1379e4b.png)
![截屏2020-12-22 下午5 24 38](https://user-images.githubusercontent.com/15261181/102872464-ab906d00-447a-11eb-9896-9c34a5097474.png)
![截屏2020-12-22 下午5 26 27](https://user-images.githubusercontent.com/15261181/102872564-d5e22a80-447a-11eb-842c-6ad0910c3fcf.png)
System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 158.61 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.2 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /Users/king.zeng/.rvm/gems/ruby-2.6.3/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 28.0.3, 29.0.3
      System Images: android-28 | Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6858069
    Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_131 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.0 => 0.63.0 
    react-native-macos: Not Found
  npmGlobalPackages:

**Comment by luism3861** [comment]
thanks for this issue @kingzeng did you try delete `node_modules` and reset cache `npm start -- --reset-cache`
