### ISSUE TITLE
Flatlist only renders items when horizontal is not set to "true"

### ISSUE THREAD

**Issue by ismaelbarry** [facebook/react-native#30621]
## Description

The FlatList component does not render items when the "horizontal" prop is set to true. I've tested this with and without the prop activated. I've gotten photos rendered when the prop is not set and no photos rendered when the prop is set to true. 

## React Native version:

Currently, running React Native version 0.63.4.

## Expected Results

I expected the photos to render horizontally and to also be scrollable. However, no photos were rendered.

## Snack, code example, screenshot, or link to a repository:

I've included code and screenshots of the result for when the prop is active and inactive.

Below is the code--as well as a screenshot--when the FlatList doesn't have the "horizontal" prop set to true. As mentioned, the photos render correctly.:

```
<FlatList
            data={this.state.activitiesArray}
            pagingEnabled={true}
            showsHorizontalScrollIndicator={false}
            onScroll={this.onScroll}
            keyExtractor={(item, index) => item.id.toString()}
            getItemLayout={(data, index) => ({
              length: 480,
              offset: 480 * index,
              index,
            })}
            renderItem={({ item }) => (
              <Cover>
                <Image
                  source={{ uri: item.photo }}
                  style={{
                    width: "100%",
                    height: "100%",
                    resizeMode: "cover",
                  }}
                />
              </Cover>
            )}
          />
```

![IMG_4338](https://user-images.githubusercontent.com/13290756/102726673-bae2af80-42ee-11eb-9d5e-246963aaf0e5.PNG)

Here's the code when the FlatList "horizontal" prop is set to true. You'll notice from the screenshot that the photos do not render.

```
<FlatList
            style={{ flexDirection: "row" }}
            data={this.state.activitiesArray}
            horizontal={true}
            pagingEnabled={true}
            showsHorizontalScrollIndicator={false}
            onScroll={this.onScroll}
            keyExtractor={(item, index) => item.id.toString()}
            getItemLayout={(data, index) => ({
              length: 480,
              offset: 480 * index,
              index,
            })}
            renderItem={({ item }) => (
              <Cover>
                <Image
                  source={{ uri: item.photo }}
                  style={{
                    width: "100%",
                    height: "100%",
                    resizeMode: "cover",
                  }}
                />
              </Cover>
            )}
          />
```

![IMG_4339](https://user-images.githubusercontent.com/13290756/102726682-cc2bbc00-42ee-11eb-8154-fdf7466d2c01.PNG)

**Comment by dan714** [comment]
Having this issue as well...

**Comment by dan714** [comment]
Figured out the issue for me:

The Image width being set to `100%` was the culprit...

Think there is some auto-resize occurring when horizontal is enabled and was resetting width to 0 for me.

**Comment by vamper424** [comment]
Hi happy new year Friends and followsme greats un this nigth un this day, wath the love forever at's You. Associattes. Good bye

**Comment by vamper424** [comment]
I'm this men now. 
![16410189943693027606675371702086](https://user-images.githubusercontent.com/72722013/147845274-9178482f-d7f5-4430-8ad8-b41df21b758a.jpg)

**Comment by vamper424** [comment]
Ando this mi grandmom greats happy new 2022. 
![Uploading 16410190449006617035011532623698.jpg…]()

**Comment by vamper424** [comment]
Saludos en el año próximo nos toca subir más flujo de trabajo solamente el 45% descansen mucho yo me conectaré empezando el año dentro de una semana próximamente.

**Comment by vamper424** [comment]
![Uploading 16410192248124132028071436889544.jpg…]()

**Comment by cortinico** [comment]
@ismaelbarry I'm closing this issue as it was marked as stale. Feel free to comment if the issue is still unsolved.
