### ISSUE TITLE
ld: library not found for -lCocoaAsyncSocket clang: error: linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by kingzeng** [facebook/react-native#30627]
![截屏2020-12-22 上午10 12 55](https://user-images.githubusercontent.com/15261181/102840705-68180d80-443e-11eb-87e5-366fe3879054.png)
![截屏2020-12-22 上午10 12 47](https://user-images.githubusercontent.com/15261181/102840707-6b12fe00-443e-11eb-9644-260a206319a6.png)
![截屏2020-12-22 上午10 12 25](https://user-images.githubusercontent.com/15261181/102840712-6e0dee80-443e-11eb-9186-727e49b927f8.png)
![截屏2020-12-22 上午10 33 02](https://user-images.githubusercontent.com/15261181/102842125-33f21c00-4441-11eb-8dae-109950094076.png)

**Comment by kingzeng** [comment]
![截屏2020-12-22 上午10 33 02](https://user-images.githubusercontent.com/15261181/102842098-263c9680-4441-11eb-832f-69f272c575e7.png)

**Comment by memosize** [comment]
be quick to resolve.can't run in M1
