### ISSUE TITLE
module map file '/Users/hosein/Library/Developer/Xcode/DerivedData/Sporty-ficshtjjzxcsgkaohfxowaxpyivr/Build/Products/Debug-iphonesimulator/YogaKit/YogaKit.modulemap' not found

### ISSUE THREAD

**Issue by admin2684** [facebook/react-native#30632]
Hi
I bought the new MacBook Air m1 and install Xcode 12 on that and I try to run my React Native project on that but I could run normally on intel base MacBook (my old macbook).
I face with some error in my new MacBook.

I see this errors:

1- building for iOS Simulator, but linking in object file built for iOS, file '/Users/hosein/Desktop/sporty-app/ios/Pods/OpenSSL-Universal/ios/lib/libcrypto.a' for architecture arm64
 I fixed this with adding the arm64 on Excluded Architectures

2- module map file '/Users/hosein/Library/Developer/Xcode/DerivedData/Sporty-ficshtjjzxcsgkaohfxowaxpyivr/Build/Products/Debug-iphonesimulator/YogaKit/YogaKit.modulemap' not found

I get number 2 when I want run app on simulator but when I run on real device I don't have any errors.

How can I fix this error (number 2)?

Note: I am running the xxxx.xcworkspace and my target iOS version in pod and general in Xcode is 10.0

**Comment by bensonnn7** [comment]
same issue here

**Comment by Elderkly** [comment]
+1

**Comment by rizwanellahi** [comment]
+1

**Comment by RaviVaranasi** [comment]
+1

**Comment by fatihyildizhan** [comment]
+1

**Comment by estevg** [comment]
+1

**Comment by atasmohammadi** [comment]
+1

**Comment by mafiusu** [comment]
It is due to the incorrect installation of Homebrew. Homebrew is not yet fully supported for the ARM processors. However, there are workarounds and tutorials on how to install it natively.

**Comment by valerijaDimova** [comment]
Has anyone find a solution for this problem?

**Comment by 2m-hanif** [comment]
module map file '/Users/2minfotech/Library/Developer/Xcode/DerivedData/helloApp-dawyzoqjvyrzpqanzadnuxtwqyjg/Build/Products/Debug-iphonesimulator/YogaKit/YogaKit.modulemap' not found
1 error generated.
anyone find a solution for this problem?

**Comment by ZakZheng** [comment]
Try set "Open using Rosetta" open your Xcode, this worked for me

**Comment by balsloev** [comment]
Opening Xcode with Rosetta worked for me too. 

This is how to open apps with Rosetta on Mac with Silicon (M1):
https://support.apple.com/en-us/HT211861

**Comment by 2m-hanif** [comment]
thanks, dear friend @balsloev  and @ZakZheng
