### ISSUE TITLE
maxRedirects: 0 not working with axios 

### ISSUE THREAD

**Issue by niwla23** [facebook/react-native#30630]
## Description

I have this code (see code example). The endpoint responds with a 301 redirect. On server-side this code worked, but in react native it does not.
It follows the redirect instead of giving me the response of the first request. This is for a scrapping project so I have no control
over the server and a proxy server would kill the idea of doing it locally since passwords are sent to this server.

## React Native version:
```
System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i5-3570 CPU @ 3.40GHz
    Memory: 4.06 GB / 15.58 GB
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.15.1 - /usr/local/bin/node
    Yarn: 1.22.10 - node_modules/.bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
  Languages:
    Java: Not Found
    Python: 2.7.18 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
  npmGlobalPackages:
    *react-native*: Not Found

```

## Steps To Reproduce
Try the code  in description and it will follow the redirect

## Expected Results
I expect to get the result of the 301

## Snack, code example, screenshot, or link to a repository:
```
      axios({
        method: 'post',
        url: `${this.url}/app/login`,
        maxRedirects: 0,
        validateStatus: function(status) {
          return status >= 200 && status < 400;
        },
        data: querystring.stringify({
          _username: this.user,
          _password: this.password,
        }),
      })
```

**Comment by Niwla23** [comment]
Why platform iOS? I am only developing for android
