### ISSUE TITLE
FlatList blanks  screen when scrolled quickly (on large dataset)

### ISSUE THREAD

**Issue by SarvaDev-123** [facebook/react-native#30636]
Contents of FlatList disappear upon quick scrolling.

To Reproduce
When a FlatList is scrolled with a pull to refresh and goes through multiple pages, and then scrolled up quickly, the content disappears.
Scroll down FlatList, going through multiple Pull to refresh instances until you have sufficiently large list. Then scroll up quickly, and the content disappears and does not come back. This behavior sometimes happens when you scroll down quickly as well.

**Comment by gabrieldonadel** [comment]
Could you please fill in the template @SarvaDev-123 ?

**Comment by SarvaDev-123** [comment]
@gabrieldonadel  see here same issue but still get no solution  https://github.com/facebook/react-native/issues/23442

**Comment by camilaazuma** [comment]
Same here. Any solution?

**Comment by PedroMeirelesInspira** [comment]
Same here; Any suggestion or solution for this issue?

**Comment by SarvaDev-123** [comment]
still get no solution @react-native-bot

**Comment by kyoz** [comment]
Have found many solution for this, but FlatList just disappointed me. Jumping from other platform to React Native because it `Native` feature but then i found out there are a lots of performance issues.. :cry: 

For this issue, i end up using this, to prevent user scroll so fast. Add this to your FlatList:

```
decelerationRate={0}
```

But it seem just work on Android, i haven't test it on iOS

**Comment by pxmage** [comment]
Same here.
Now I am using ScrollView :( with bad performance.
![blank](https://user-images.githubusercontent.com/52536798/114721352-6cf52a00-9d6b-11eb-80c1-ffa97c23ec7e.gif)

**Comment by gabrieldonadel** [comment]
> Same here.
> ![blank](https://user-images.githubusercontent.com/52536798/114721352-6cf52a00-9d6b-11eb-80c1-ffa97c23ec7e.gif)
> 
> I now have to use ScrollView :( with its bad performance.

Make sure you are using a unique key for each item @pxmage

**Comment by Asadi123** [comment]
Try disableVirtualization = {false}, the blank screen does not come anymore but please note that it is memory expensive. I don't use this option personally and still trying to look for better solution.

**Comment by SarvaDev-123** [comment]
@KyawSoeHein yes it's resolved the issue.

**Comment by KyawSoeHein** [comment]
yes, I solved it with this one. When I used these together, blank screen is gone. Maybe that is because I created windows more than enough.

` const windowSize =
      this.state.searchContactList.length > 0
        ? this.state.searchContactList.length / 4
        : 100;   
maxToRenderPerBatch={windowSize}
            windowSize={windowSize}`

it is similar to disableVirtualization = {true} but with this one we have a slight control over how much memory we will use.

**Comment by SarvaDev-123** [comment]
@KyawSoeHein  Thanks bro it's also working.

**Comment by SarvaDev-123** [comment]
@KyawSoeHein  Please have a look similar type issue https://github.com/Flipkart/recyclerlistview/issues/622  I have not found any solution for this as well.

**Comment by SarvaDev-123** [comment]
> yes, I solved it with this one. When I used these together, blank screen is gone. Maybe that is because I created windows more than enough.
> 
> ` const windowSize = this.state.searchContactList.length > 50 ? this.state.searchContactList.length / 4 : 21; maxToRenderPerBatch={windowSize} windowSize={windowSize}`
> 
> it is similar to disableVirtualization = {true} but with this one we have a slight control over how much memory we will use. More conditioning will be needed.

Some flatlist it will work and some flatlist still shows blanks screen.

**Comment by KyawSoeHein** [comment]
@SarvaDev-123 , then change dividing by 4 into something that is more appropriate like 3 or 2 depending on your data count. You can also tune it for better performance. Use more conditioning.

**Comment by trithien98** [comment]
> > yes, I solved it with this one. When I used these together, blank screen is gone. Maybe that is because I created windows more than enough.
> > ` const windowSize = this.state.searchContactList.length > 50 ? this.state.searchContactList.length / 4 : 21; maxToRenderPerBatch={windowSize} windowSize={windowSize}`
> > it is similar to disableVirtualization = {true} but with this one we have a slight control over how much memory we will use. More conditioning will be needed.
> 
> Some flatlist it will work and some flatlist still shows blanks screen.

Can u relsove it , because im still facing the problem like you , when fast scroll up in list , the blank screen will appear

**Comment by rochapablo** [comment]
https://stackoverflow.com/questions/68654630

**Comment by Nitish111** [comment]
I am also facing this issue in RLV Flipkart

**Comment by Baloc22m** [comment]
> <img alt="@SarvaDev-123" width="40" height="40" src="https://avatars.githubusercontent.com/u/69505492?s=88&amp;v=4">

Thank you! This works great

**Comment by luism3861** [comment]
> yes, I solved it with this one. When I used these together, blank screen is gone. Maybe that is because I created windows more than enough.
> 
> 
> 
> ` const windowSize =
> 
>       this.state.searchContactList.length > 50
> 
>         ? this.state.searchContactList.length / 4
> 
>         : 21;   
> 
> maxToRenderPerBatch={windowSize}
> 
>             windowSize={windowSize}`
> 
> 
> 
> it is similar to disableVirtualization = {true} but with this one we have a slight control over how much memory we will use. More conditioning will be needed.
> 
> 

Thanks¡

**Comment by sudharsanvishnu** [comment]
> yes, I solved it with this one. When I used these together, blank screen is gone. Maybe that is because I created windows more than enough.
> 
> ` const windowSize = this.state.searchContactList.length > 50 ? this.state.searchContactList.length / 4 : 21; maxToRenderPerBatch={windowSize} windowSize={windowSize}`
> 
> it is similar to disableVirtualization = {true} but with this one we have a slight control over how much memory we will use. More conditioning will be needed.

this is a better solution compared other sources

**Comment by Gattupatel05** [comment]
can you give me one example 
I have same issue [here](https://stackoverflow.com/questions/75037577/when-i-scroll-fast-in-contact-app-then-sometime-data-come-after-a-second-in-reac)
Please help me help me otherwise give me a simple example ??

**Comment by arslanafzal077** [comment]
I'm also facing this issue with SectionList

**Comment by Nader-CS** [comment]
until now this issue exist

**Comment by MohanGupta-CMD** [comment]
> yes, I solved it with this one. When I used these together, blank screen is gone. Maybe that is because I created windows more than enough.
> 
> ` const windowSize = this.state.searchContactList.length > 50 ? this.state.searchContactList.length / 4 : 21; maxToRenderPerBatch={windowSize} windowSize={windowSize}`
> 
> it is similar to disableVirtualization = {true} but with this one we have a slight control over how much memory we will use. More conditioning will be needed.

it is good when you have limited items but when you have more then 50 items into your flatlist then it can cause performance issue in low end devices
