### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'process.version.split')

### ISSUE THREAD

**Issue by bn185068** [facebook/react-native#30654]
Looks like this same issue was encountered and opened back in June at #29095, but ignored because it did not follow the proper issue templating. I hope I can resolve the templating issues here.

## Description
After installing packages and running metro bundler, I get a 100% successful build but this error in the android emulator.

![image](https://user-images.githubusercontent.com/66647580/103238536-06adde00-4919-11eb-8ab8-19087f694289.png)
![image](https://user-images.githubusercontent.com/66647580/103238479-d9613000-4918-11eb-88a7-0bd15b8bf447.png)

## React Native version:
System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 548.32 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.3 - /usr/local/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 6.14.9 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.3/12C33 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.4 => 0.61.4

## Steps To Reproduce
For context, I am required to use another port because 8081 is running other OS critical software controlled by sys admins that cannot be stopped/killed.

1. npx react-native init AwesomeProject --version 0.61.4
2. npx react-native start --port=8999 --reset-cache
3. npx react-native run-android --port=8999

## Expected Results
Expected to see the working example app.

## Snack, code example, screenshot, or link to a repository:
Here is the repo with my app code: https://github.com/bn185068/rn-awesome-project.

**Comment by tuantvk** [comment]
@bn185068 in **node_modules\readable-stream\lib\ _stream_writable.js** add line:
```js
/*<replacement>*/
var process = require("process");   // THIS LINE
var pna = require('process-nextick-args');
/*</replacement>*/
```
maybe help you

**Comment by bn185068** [comment]
@tuantvk this appears to have worked! Thank you!

**Comment by dulmandakh** [comment]
process variable is available in nodejs, but not in React Native runtime. Please make sure that third-party JS module compatible with RN.
