### ISSUE TITLE
FlatList initialNumToRender appears to have no effect 

### ISSUE THREAD

**Issue by kp72-dev** [facebook/react-native#30651]
I want to display only 10 items in list
after providings its property for 10 item max to render or initial number still its rendering more than 10
i have go through many solution here is one last ref i tried too
System:
    OS: macOS 10.15.2
    CPU: (4) x64 Intel(R) Core(TM) i3-7100 CPU @ 3.90GHz
    Memory: 64.39 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.7.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.13.6 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 11.3.1/11C505 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

https://github.com/facebook/react-native/issues/15807

```
<FlatList
                                    initialNumToRender={10}
                                    maxToRenderPerBatch={10}
                                    windowSize={2}
                                    data={files}
                                    contentContainerStyle={{ marginHorizontal: 10 }}
                                    keyExtractor={item => item.id}
                                    style={{ marginTop: Platform.isPad ? 5 : 0 }}
                                    renderItem={(item, index) => this.renderlist(item, index)}
                                />
```

**Comment by kp72-dev** [comment]
here my system  configuration
System:
    OS: macOS 10.15.2
    CPU: (4) x64 Intel(R) Core(TM) i3-7100 CPU @ 3.90GHz
    Memory: 64.39 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.7.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.13.6 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 11.3.1/11C505 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

https://github.com/facebook/react-native/issues/15807

```
<FlatList
                                    initialNumToRender={10}
                                    maxToRenderPerBatch={10}
                                    windowSize={2}
                                    data={files}
                                    contentContainerStyle={{ marginHorizontal: 10 }}
                                    keyExtractor={item => item.id}
                                    style={{ marginTop: Platform.isPad ? 5 : 0 }}
                                    renderItem={(item, index) => this.renderlist(item, index)}
                                />
```

**Comment by Monir-Shembesh** [comment]
@kp72-dev  from what I understand you are trying to render only 10 items in the `flatlist`. nothing less nothing more right? well both  `initialNumToRender={10}` and `maxToRenderPerBatch={10}` wont satisfy your needs heres why. 

`initialNumToRender={10}` basically tells the `flatlist` how many items it should render in the first render.
`maxToRenderPerBatch={10}` basically tells the `flatlist` how many new items to render on the next patch render when you scroll and reach the end of your list. 

now since you only want to render 10 Items in the `flatlist`, why dont you just pass 10 items?

**Comment by kp72-dev** [comment]
thats good but is there any prop that decide to limit render items ??
@Monir-Shembesh Monir-Shembesh

**Comment by Monir-Shembesh** [comment]
@kp72-dev Not really I dont think so. The point of `flatlist` is to render a huge set of data. So it just take the data you want to render it doesnt really modify it. It could be added if you play with library code after forking but I suggest that you just pass an `array` of 10 items inside it and thats it.

**Comment by kp72-dev** [comment]
Thank you sir!
Its cleared me what it will do 
and also understood how should i work on my logics.
Thank you again and sorry if i bother you.

**Comment by Monir-Shembesh** [comment]
its ok no bother at all and happy coding!
