### ISSUE TITLE
React Native Version Mismatch Issue 

### ISSUE THREAD

**Issue by rakeshsag123** [facebook/react-native#30665]
## Description
I'm getting the version mismatch issue, When I upgrade the react native version to `0.63.4`
```
Error stack trace: (Check the below attached link)
Console.error: React Native version mismatch
Javascript version: 0.63.4
Native version: 0.61.5
```
I have tried following commands but still nothing is working.
```
- yarn reset cache
- react-native start --reset-cache
```
Mismatch error screenshot: https://lh3.googleusercontent.com/-biYjYzw-R0o/X-2aje1Q_LI/AAAAAAAAAIA/XKuz7ix-Q4cTUuDWQbNznS9e00eI82cXQCK8BGAsYHg/s512/2020-12-31.jpg

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.
1. react-native run-android
2. react-native start

## Expected Results
It should work properly without the version mismatch error.

## Snack, code example, screenshot, or link to a repository:
Package.json file:
```
{
    "name": "test-mobile",
    "version": "0.0.1",
    "scripts": {
      "android": "react-native run-android",
      "ios": "react-native run-ios",
      "start": "react-native start",
      "test": "jest",
      "lint": "eslint . --ext .js,.jsx,.ts,.tsx",
      "jetify": "jetify"
    },
    "dependencies": {
      "@emotion/core": "^10.0.28",
      "@emotion/native": "^10.0.27",
      "@react-native-community/async-storage": "^1.7.1",
      "@react-native-community/masked-view": "^0.1.6",
      "@react-native-community/netinfo": "^5.3.3",
      "@react-native-firebase/analytics": "^10.3.1",
      "@react-native-firebase/app": "^10.3.0",
      "@react-native-firebase/messaging": "^10.3.1",
      "@sentry/react-native": "^1.2.2",
      "axios": "^0.19.2",
      "eslint-plugin-react": "^7.19.0",
      "formik": "^2.1.3",
      "google-libphonenumber": "^3.2.6",
      "jwt-decode": "^2.2.0",
      "lodash": "4.17.16",
      "moment": "^2.24.0",
      "native-base": "^2.13.8",
      "phone": "^2.4.4",
      "react": "16.13.1",
      "react-dom": "16.13.1",
      "react-native": "0.63.4",
      "react-native-config": "^0.12.0",
      "react-native-device-info": "^5.5.3",
      "react-native-emoji": "^1.8.0",
      "react-native-gesture-handler": "~1.5.0",
      "react-native-image-crop-picker": "0.35.2",
      "react-native-intercom": "^13.2.0",
      "react-native-keyboard-aware-scroll-view": "^0.9.1",
      "react-native-linear-gradient": "^2.5.6",
      "react-native-modal": "^11.5.3",
      "react-native-pdf": "^6.2.2",
      "react-native-reanimated": "^1.7.0",
      "react-native-responsive-fontsize": "^0.4.2",
      "react-native-responsive-screen": "^1.3.1",
      "react-native-safe-area-context": "^0.6.4",
      "react-native-screens": "^2.0.0-alpha.34",
      "react-native-splash-screen": "^3.2.0",
      "react-native-swiper": "^1.6.0-rc.3",
      "react-native-vector-icons": "6.6.0",
      "react-native-web": "~0.11.7",
      "react-native-webview": "^8.0.6",
      "react-navigation": "^4.1.0",
      "react-navigation-stack": "^2.1.1",
      "react-navigation-tabs": "^2.7.0",
      "rn-fetch-blob": "^0.12.0",
      "styled-components": "^5.0.0",
      "tiny-emitter": "^2.1.0",
      "unstated": "^2.1.1",
      "unstated-next": "^1.1.0",
      "yup": "^0.28.1"
    },
    "devDependencies": {
      "@babel/core": "^7.6.2",
      "@babel/runtime": "^7.6.2",
      "@react-native-community/eslint-config": "^0.0.5",
      "@types/jest": "^24.0.24",
      "@types/react-native": "^0.62.1",
      "@types/react-test-renderer": "16.9.1",
      "@typescript-eslint/eslint-plugin": "^2.12.0",
      "@typescript-eslint/parser": "^2.12.0",
      "babel-jest": "^24.9.0",
      "babel-plugin-module-resolver": "^4.0.0",
      "eslint": "^6.5.1",
      "get-yarn-workspaces": "^1.0.2",
      "jest": "^25.1.0",
      "metro-react-native-babel-preset": "^0.59.0",
      "react-test-renderer": "16.13.1",
      "typescript": "^3.7.3"
    },
    "jest": {
      "preset": "react-native",
      "moduleFileExtensions": [
        "ts",
        "tsx",
        "js",
        "jsx",
        "json",
        "node"
      ]
    }
  }
```

**Comment by jamsch** [comment]
You need to run `react-native run-android` (or `react-native run-ios`) to install the newer version of the app with the appropriate version of React Native.

**Comment by rakeshsag123** [comment]
@jamsch I'm already doing this :)

**Comment by dulmandakh** [comment]
This issue tracker is intended for RN issues only, not developer support. But I would remove **node_modules** and run npm or yarn again, then run **./gradlew clear** in android directory to clear up build cache.

**Comment by irohitb** [comment]
@dulmandakh facing the same issue on ios. ./gradlew clear should be for Android? I understand the issue board isn't meant for dev support but I think you should take common issues.
`Native version` is still understandable but what is `JavaScript version`?

**Comment by dulmandakh** [comment]
RN consists of JS + Native code, and versions must match. But sometimes you have native build cache from previous version, thus causing the issue. You need to clear native build cache to fix the issue

**Comment by progerchai** [comment]
`./gradlew clear` seems only work for android ,but how to fix it in ios
![image](https://user-images.githubusercontent.com/31467572/108681577-444e7200-752a-11eb-9753-ed56188f0310.png)

**Comment by iKronyck** [comment]
I have the same issue but with this version, android launch this error, I already cleaned the cache of watchman, npm, yarn and clean the wipe data of my virtual devices.

![image](https://user-images.githubusercontent.com/12678606/128246940-886ba286-ff45-489a-98d2-12bb00a21393.png)

on iOS working fine.

![Screen Shot 2021-08-04 at 14 02 50](https://user-images.githubusercontent.com/12678606/128247207-a283ffa0-345f-4237-aa67-82d5c4880920.png)

Does anyone know how to fix it?
