### ISSUE TITLE
SafeAreaView on iOS renders without safe area insets then rapidly updates with safe area insets

### ISSUE THREAD

**Issue by gabrielbull** [facebook/react-native#30668]
## Description
In some cases, 1 frame (out of 60fps) will render without the safe area insets causing a visible "flash".

## React Native version:

```
System:
    OS: macOS 11.1
    CPU: (16) x64 Intel(R) Xeon(R) W-2140B CPU @ 3.20GHz
    Memory: 3.61 GB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.4.0 - ~/.nvm/versions/node/v14.4.0/bin/node
    Yarn: 2.4.0 - ~/.nvm/versions/node/v14.4.0/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v14.4.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /Users/gabriel/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
      Android NDK: 21.3.6528147
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 12.3/12C33 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_222 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: ^0.63.4 => 0.63.4
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce

This issue happens more often if there are a lot of children inside the SafeAreaView but will happen even with one children only. When reproducing the issue, you have to refresh a couple of time to see the issue because it does not happen every time.

## Expected Results

I expect the SafeAreaView to render correctly immediately.

## Snack, code example, screenshot, or link to a repository:
```
    <SafeAreaView style={{ flex: 1 }}>
      <View style={{ flex: 1, backgroundColor: 'blue' }} />
    </SafeAreaView>
```

This example will produce the problem shown in the screenshots below. You have to have a good eye to catch it. Using QuickTime, you can record your screen and replay the issue frame by frame.

![ ](https://user-images.githubusercontent.com/671923/103425289-63aacd80-4b7f-11eb-94d5-5436070a16fa.png)

**Comment by safaiyeh** [comment]
@gabrielbull thanks for the issue! Does this affect apps in production? Does this flash cause bad UX

**Comment by gabrielbull** [comment]
@safaiyeh It does create a visible "flash" and does cause a bad UX, even on production apps. It is visible on all React Native apps using SafeAreaView and is a tell-tale sign that an app is using React Native. Is is especially more visible when the SafeAreaView is inside a UINavigationController or UITabBarController as those will increase the safe area insets and make the flash even more obvious. Here is a recording, slowed down to 12% to clearly see the problem, of a React Native app launch.

![Sans titre2 2021-01-10 16_12_53](https://user-images.githubusercontent.com/671923/104135524-0bce4c80-535f-11eb-93a5-2d12cb3af5d9.gif)

**Comment by rgbedin** [comment]
Hi! Any workarounds for this issue?

**Comment by gabrielbull** [comment]
No workarounds, this is an issue with the way react native renders native view so the solution is not quite simple.

**Comment by fiznool** [comment]
Try https://github.com/th3rdwave/react-native-safe-area-context, it has solved this issue for me.

**Comment by billythegoat356** [comment]
I still get this issue with `SafeAreaView`
I've switched to a normal view with manually added padding with `useSafeAreaInsets`.
It fixed it.

It seems like `SafeAreaView` has to do some recomputing whereas `useSafeAreaInsets` just uses the one from the provider.
