### ISSUE TITLE
Unable to view components in the component tree in React-devtools when hermes is enabled

### ISSUE THREAD

**Issue by mr-moto** [facebook/react-native#30669]
## Description
Not sure if im missing something or if this is expected behavior but when hermes is enabled, im unable to view component information in the component tree in react devtools. Everytime I try clicking on a component in devtools, it throws an error ( screenshot below )

works fine when hermes is disabled

## React Native version:
```
System:
    OS: Windows 10 10.0.19041
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 3.04 GB / 15.95 GB
  Binaries:
    Node: 12.19.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD      
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6626763   
    Visual Studio: Not Found
  Languages:
    Java: 14.0.2
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
1. fresh react native install
2. enable hermes
3. run react-devtools and click on component

## Expected Results
To be able to view component information

## Snack, code example, screenshot, or link to a repository:
![Screenshot 2020-12-31 224410](https://user-images.githubusercontent.com/24904987/103435232-d2f4e180-4bc0-11eb-8975-7b17bf45a40b.png)

**Comment by safaiyeh** [comment]
Hi @mr-moto there is some set up to inspect Hermes in dev tools. Check this out: https://reactnative.dev/docs/hermes#debugging-js-on-hermes-using-google-chromes-devtools 

Let me know if this helps.

**Comment by mr-moto** [comment]
hey @safaiyeh thanks for the response
I've looked through the docs you linked me to but it still doesn't address the issue of being able to see the component tree and its information.  chrome devtools only provides - Profiles, Console, Sources and Memory

**Comment by helixbass** [comment]
I am also running into this

I opened https://github.com/facebook/flipper/issues/1897 and https://github.com/facebook/react/issues/20884 but not sure where the right place to track it is?

If it's helpful this is a fresh React Native + Typescript project with Hermes enabled where I'm able to reproduce the issue (using React DevTools v4.10.1-3a8c04e3b2): https://github.com/helixbass/HermesDevToolsIssueExample

**Comment by chrisglein** [comment]
There was a ton of work done on Hermes support in 0.64. You should re-validate this on latest to see if this still reproduces.

**Comment by helixbass** [comment]
@chrisglein ok I just tested with a React Native app running 0.64.0, it's still happening (I guess technically I think it's a slightly different error message, I'm seeing `[TypeError: Cannot read property 'forEach' of undefined]` when trying to click a component in React-devtools, but same basic issue behavior-wise)

**Comment by vonovak** [comment]
I was having this issue on ios as well and resolved it as explained in https://gist.github.com/bvaughn/4bc90775530873fdf8e7ade4a039e579#flipper
