### ISSUE TITLE
Cannot run Emulator with react-native run-android if Spaces in Path 

### ISSUE THREAD

**Issue by nabond251** [facebook/react-native#30664]
## Description
I cannot get `npx react-native run-android` to open the Android emulator if there is a space in the username folder and the Android SDK is installed in the default `%USERPROFILE%\AppData\Local\Android\Sdk` directory.  So for example if my username is `That Guy` and I run `npx react-native run-android` I get several lines with `'C:\Users\That' is not recognized as an internal or external command` etc.  What is going on under the hood is `run-android` attempting to start the emulator, but it is not very clear that this is what is failing.

## React Native version:
```
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.19041
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
    Memory: 2.85 GB / 11.87 GB
  Binaries:
    Node: 15.3.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 7.0.14 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 27, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: 21.3.6528147
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6953283
    Visual Studio: 16.7.30503.244 (Visual Studio Community 2019)
  Languages:
    Java: Not Found
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.3 => 0.63.3
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
1.  Log into Windows account with space in username folder, e.g. `C:\Users\That Guy`
2.  Install Android SDK in standard location, `%USERPROFILE%\AppData\Local\Android\Sdk`
3.  `npx react-native init AwesomeProject`
4.  `cd AwesomeProject`
5.  `npx react-native run-android`

## Expected Results
Emulator starts without space in Windows username folder causing `react-native run-android` to fail.  This would simply be a matter of surrounding the emulator path with spaces in the call site.

## Temporary Workaround
I moved the `Android` folder from `%USERPROFILE%\AppData\Local` to `C:\` and updated my `ANDROID_HOME` environment variable accordingly.  This causes `react-native run-android` to work as expected, but I would think having spaces in the username folder is a fairly common situation (e.g. first and last name), it is not exactly a trivial change to remove the spaces (nor desirable when it is only for the sake of a single build tool), and it would be ideal to have the Android SDK in the standard location (e.g. not need to modify environment instructions for this case).

**Comment by maxymczech** [comment]
Still an issue for Windows users

**Comment by cortinico** [comment]
Closing as stale + this is a CLI issue so should eventually be opened against the CLI issue tracker
