### ISSUE TITLE
FormData ignores Non-Ascii characters on filename

### ISSUE THREAD

**Issue by darron1217** [facebook/react-native#30660]
## Description
https://github.com/jaydenseric/apollo-upload-client/issues/244
Uploading file using FormData works well on Web.

But on React Native, it keep ignores Non-Ascii characters on filename.

How can I send filename properly?
I created file object like below
```
  const nativeFile ={
    uri: file.url,
    type: file.mime,
    name: file.name,
  };
```
And passed it like below
```
const formData = new FormData();
formData.append('file', nativeFile);
```

`console.log(filename)` before upload
```
이름변경-2.jpg
```

after upload
```
-2.jpg
```

(Edit)
Server Log (nodejs with Koa)
```
  {
    filename: '-2.jpg',
    mimetype: 'image/jpeg',
    encoding: '7bit',
    createReadStream: [Function: createReadStream]
  }
```

I had to send formData without `content-type` header.
Does this can cause problem?

## React Native version:
```
System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz
    Memory: 329.11 MB / 24.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.3 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.2/12B45b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.8 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Create FormData object like above
2. append file
3. send it to nodejs based server (like Koa.js)

## Expected Results
Same result with Web's FormData

**Comment by SriSamVictor** [comment]
> System

**Comment by SriSamVictor** [comment]
### React Version

**Comment by zatakiyanarendra12** [comment]
Is there any update on this?

**Comment by vladimirevstratov** [comment]
Any update? RN 0.70 still has this issue

**Comment by PatoSala** [comment]
Is there any update?

**Comment by manosKas** [comment]
+1

**Comment by cAstraea** [comment]
You need to urlencode on the client side. Seems like it' a ISO thing 🤷
