### ISSUE TITLE
Keyboard listener returns wrong keyboard height in ios

### ISSUE THREAD

**Issue by panda0603** [facebook/react-native#30674]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
On ios, keyboard listener returns wrong keyboard height on ios (android is fine). I have also tested this on freshly created rn version 0.63.4.

Upon keyboardDidHide, the keyboard height should be 0, but the height seems to be 69 (only when dismiss keyboard on tap in scrollview or using cmd+k in simulator, not by changing screen). I have no idea where height of 69 came from. I did not install react-navigation. Also for keyboardDidShow, height of 69 seems to be added to the original keyboard height. 

![image](https://user-images.githubusercontent.com/34116285/103471919-f0e16280-4dc9-11eb-8206-19fede367740.png)

## React Native version:
react-native : 0.63.4
react : 16.13.1

## Steps To Reproduce
Below is the code I used: 
```
const Keyboards = () => {
  function onKeyboardDidShow(e) {
    console.log(e);
  }

  function onKeyboardDidHide(e) {
    console.log(e);
  }

  useEffect(() => {
    Keyboard.addListener('keyboardDidShow', onKeyboardDidShow);
    Keyboard.addListener('keyboardDidHide', onKeyboardDidHide);
    return () => {
      Keyboard.removeListener('keyboardDidShow', onKeyboardDidShow);
      Keyboard.removeListener('keyboardDidHide', onKeyboardDidHide);
    };
  }, []);

  return (
    <View style={styles.container}>
      <TextInput style={{borderWidth: 1, width: 100, height: 20}} />
    </View>
  );
};

export default Keyboards;

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
});
```
## Expected Results
Returns correct height of keyboard.

**Comment by yifeiyin** [comment]
Duplication of #29815, which also has an expo snack demo: https://snack.expo.io/@yifeiyin/keyboard-height-reproduce
