### ISSUE TITLE
removeClippedSubviews={true} in scrollview - view not visible when changed tab

### ISSUE THREAD

**Issue by krunalbad** [facebook/react-native#30671]
`removeClippedSubviews={true}` in scrollview - view not visible when changed tab

When launched an app for the first time the scroll view is visible
but when I change the tab i.e. perform any navigation the scroll view is not visible until it is scrolled

`removeClippedSubviews={true}` using this as `true` makes my scroll view perform faster the only issue is that the view gets hidden sometimes on the navigation

FYI: `removeClippedSubviews={false}` doesn't reproduce the hidden issue but degrades the performance

Any idea how to fix hidden issue while having `removeClippedSubviews={true}` ?

**Comment by krunalbad** [comment]
![Screenshot 2021-01-02 at 12 46 32 PM](https://user-images.githubusercontent.com/45413622/103452740-a04e0480-4cf8-11eb-97ad-79901d0758c4.png)

**Comment by safaiyeh** [comment]
@krunalbad thank you for the issue. Can you make sure to follow the template and provide a repro of the issue. Closing for now.

**Comment by Orange9000** [comment]
FYI, if you search the issue history, this is _atleast_ 4 year old react-native bug.
