### ISSUE TITLE
Is it possible to animate views with tabBarIOS component 

### ISSUE THREAD

**Issue by antigirl** [facebook/react-native#3067]
Is it possible to have sliding transitions, where the slide happens over the previous view. As the state changes the re-render seems to clean the slate and it doesn't seem possible without much hacking 

Good example of this is the airbnb app

**Comment by brentvatne** [comment]
Hi there! Please post this kind of question on StackOverflow or Slack, as per our [Getting Help](https://github.com/facebook/react-native#getting-help) guide, thanks!

One alternative you could look at is [react-native-tab-navigator](https://github.com/exponentjs/react-native-tab-navigator) which is a pure JS implementation of a tab bar.
