### ISSUE TITLE
[WebSocket] WebSocket does not call the onClose handler when a connection fails

### ISSUE THREAD

**Issue by mcgsoftware** [facebook/react-native#3068]
https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_client_applications#Connection_errors

States that when a connect fails, it calls onerror() handler and onclose(). It seems to call only the onerror().

The reason it matters is re-connect code uses the onclose() for connections that break as well as connections that fail to connect the first time.

**Comment by christopherdro** [comment]
Duplicate #4803

**Comment by christopherdro** [comment]
It appears the native implementations aren't checking if  a connections fails when calling `RCTWebSocketModule.connect `.

@nicklockwood 
I looked over [Handling Stream Error] (https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/Streams/Articles/HandlingStreamError.html) and am wondering if we need something like this?

@mkonicek 
Should we be closing OkHttpClient client [here](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/modules/websocket/WebSocketModule.java#L93-L95)?

**Comment by nicklockwood** [comment]
@christopherdro SRWebSocket is a 3rd party library, so I'm not too clear on the details of its implementation. If it's not handling the error case though, we should probably patch our fork, and maybe submit a PR to the original project as well so we don't diverge too much.

**Comment by satya164** [comment]
@mcgsoftware Are you talking about Android or iOS? In any case, should be easy to fix, just need to dispatch the close event from Native side after failure.
