### ISSUE TITLE
Crash  YGVLog(YGConfig*, YGNode*, YGLogLevel, char const*, char*)

### ISSUE THREAD

**Issue by scutliyizhen** [facebook/react-native#30687]
Please provide all the information requested. Issues that do not follow this format are likely to stall.
## Description
**remark:** the crash function stack  is same with https://github.com/n4kz/react-native-material-textfield/issues/178

OS Version: iOS 14.0 (18A373)
Report Version: 104

Exception Type: EXC_CRASH (SIGABRT)
Crashed Thread: 38

Application Specific Information:
enceTypeAA0cde9Protocol_f1_jK0_pSgvpMV >
Can't not diagnosize the reason.

Thread 38 Crashed:
0   libsystem_kernel.dylib          0x370a5a95c         __pthread_kill  + 8
1   libsystem_pthread.dylib         0x3a69189e8         pthread_kill  + 211
2   libsystem_c.dylib               0x32d09f934         abort  + 99
3   discover                        0x2058ff0fc         YGVLog(YGConfig*, YGNode*, YGLogLevel, char const*, char*)   (Yoga.cpp:4210)
4   discover                        0x2058fb810         YGLog   (Yoga.cpp:4228)
5   discover                        0x2058ff86c         YGBaseline(YGNode*)   (Yoga.cpp:1083)
6   discover                        0x2058ff910         YGBaseline(YGNode*)   (Yoga.cpp:1115)
7   discover                        0x2058fce04         YGNodelayoutImpl(YGNode*, float, float, YGDirection, YGMeasureMode, YGMeasureMode, float, float, bool, YGConfig*, YGMarkerLayoutData&)   (Yoga.cpp:2561)
8   discover                        0x2058fb470         YGLayoutNodeInternal(YGNode*, float, float, YGDirection, YGMeasureMode, YGMeasureMode, float, float, bool, char const*, YGConfig*, YGMarkerLayoutData&)   (Yoga.cpp:3861)
9   discover                        0x205900350         YGNodeComputeFlexBasisForChild(YGNode*, YGNode*, float, YGMeasureMode, float, float, float, YGMeasureMode, YGDirection, YGConfig*, YGMarkerLayoutData&)   (Yoga.cpp:1428)
10  discover                        0x2058fc284         YGNodelayoutImpl(YGNode*, float, float, YGDirection, YGMeasureMode, YGMeasureMode, float, float, bool, YGConfig*, YGMarkerLayoutData&)   (Yoga.cpp:1938)
11  discover                        0x2058fb470         YGLayoutNodeInternal(YGNode*, float, float, YGDirection, YGMeasureMode, YGMeasureMode, float, float, bool, char const*, YGConfig*, YGMarkerLayoutData&)   (Yoga.cpp:3861)
12  discover                        0x205900350         YGNodeComputeFlexBasisForChild(YGNode*, YGNode*, float, YGMeasureMode, float, float, float, YGMeasureMode, YGDirection, YGConfig*, YGMarkerLayoutData&)   (Yoga.cpp:1428)
13  discover                        0x2058fc284         YGNodelayoutImpl(YGNode*, float, float, YGDirection, YGMeasureMode, YGMeasureMode, float, float, bool, YGConfig*, YGMarkerLayoutData&)   (Yoga.cpp:1938)
14  discover                        0x2058fb470         YGLayoutNodeInternal(YGNode*, float, float, YGDirection, YGMeasureMode, YGMeasureMode, float, float, bool, char const*, YGConfig*, YGMarkerLayoutData&)   (Yoga.cpp:3861)
15  discover                        0x205900350         YGNodeComputeFlexBasisForChild(YGNode*, YGNode*, float, YGMeasureMode, float, float, float, YGMeasureMode, YGDirection, YGConfig*, YGMarkerLayoutData&)   (Yoga.cpp:1428)
16  discover                        0x2058fc284         YGNodelayoutImpl(YGNode*, float, float, YGDirection, YGMeasureMode, YGMeasureMode, float, float, bool, YGConfig*, YGMarkerLayoutData&)   (Yoga.cpp:1938)
17  discover                        0x2058fb470         YGLayoutNodeInternal(YGNode*, float, float, YGDirection, YGMeasureMode, YGMeasureMode, float, float, bool, char const*, YGConfig*, YGMarkerLayoutData&)   (Yoga.cpp:3861)
18  discover                        0x205900350         YGNodeComputeFlexBasisForChild(YGNode*, YGNode*, float, YGMeasureMode, float, float, float, YGMeasureMode, YGDirection, YGConfig*, YGMarkerLayoutData&)   (Yoga.cpp:1428)
19  discover                        0x2058fc284         YGNodelayoutImpl(YGNode*, float, float, YGDirection, YGMeasureMode, YGMeasureMode, float, float, bool, YGConfig*, YGMarkerLayoutData&)   (Yoga.cpp:1938)
20  discover                        0x2058fb470         YGLayoutNodeInternal(YGNode*, float, float, YGDirection, YGMeasureMode, YGMeasureMode, float, float, bool, char const*, YGConfig*, YGMarkerLayoutData&)   (Yoga.cpp:3861)
21  discover                        0x205900350         YGNodeComputeFlexBasisForChild(YGNode*, YGNode*, float, YGMeasureMode, float, float, float, YGMeasureMode, YGDirection, YGConfig*, YGMarkerLayoutData&)   (Yoga.cpp:1428)
22  discover                        0x2058fc284         YGNodelayoutImpl(YGNode*, float, float, YGDirection, YGMeasureMode, YGMeasureMode, float, float, bool, YGConfig*, YGMarkerLayoutData&)   (Yoga.cpp:1938)
23  discover                        0x2058fb470         YGLayoutNodeInternal(YGNode*, float, float, YGDirection, YGMeasureMode, YGMeasureMode, float, float, bool, char const*, YGConfig*, YGMarkerLayoutData&)   (Yoga.cpp:3861)
24  discover                        0x205900350         YGNodeComputeFlexBasisForChild(YGNode*, YGNode*, float, YGMeasureMode, float, float, float, YGMeasureMode, YGDirection, YGConfig*, YGMarkerLayoutData&)   (Yoga.cpp:1428)
25  discover                        0x2058fc284         YGNodelayoutImpl(YGNode*, float, float, YGDirection, YGMeasureMode, YGMeasureMode, float, float, bool, YGConfig*, YGMarkerLayoutData&)   (Yoga.cpp:1938)
26  discover                        0x2058fb470         YGLayoutNodeInternal(YGNode*, float, float, YGDirection, YGMeasureMode, YGMeasureMode, float, float, bool, char const*, YGConfig*, YGMarkerLayoutData&)   (Yoga.cpp:3861)
27  discover                        0x2058fd3c8         YGNodelayoutImpl(YGNode*, float, float, YGDirection, YGMeasureMode, YGMeasureMode, float, float, bool, YGConfig*, YGMarkerLayoutData&)   (Yoga.cpp:3124)
28  discover                        0x2058fb470         YGLayoutNodeInternal(YGNode*, float, float, YGDirection, YGMeasureMode, YGMeasureMode, float, float, bool, char const*, YGConfig*, YGMarkerLayoutData&)   (Yoga.cpp:3861)
29  discover                        0x2058fd3c8         YGNodelayoutImpl(YGNode*, float, float, YGDirection, YGMeasureMode, YGMeasureMode, float, float, bool, YGConfig*, YGMarkerLayoutData&)   (Yoga.cpp:3124)
30  discover                        0x2058fb470         YGLayoutNodeInternal(YGNode*, float, float, YGDirection, YGMeasureMode, YGMeasureMode, float, float, bool, char const*, YGConfig*, YGMarkerLayoutData&)   (Yoga.cpp:3861)
31  discover                        0x2058fd3c8         YGNodelayoutImpl(YGNode*, float, float, YGDirection, YGMeasureMode, YGMeasureMode, float, float, bool, YGConfig*, YGMarkerLayoutData&)   (Yoga.cpp:3124)
32  discover                        0x2058fb470         YGLayoutNodeInternal(YGNode*, float, float, YGDirection, YGMeasureMode, YGMeasureMode, float, float, bool, char const*, YGConfig*, YGMarkerLayoutData&)   (Yoga.cpp:3861)
33  discover                        0x2058fd3c8         YGNodelayoutImpl(YGNode*, float, float, YGDirection, YGMeasureMode, YGMeasureMode, float, float, bool, YGConfig*, YGMarkerLayoutData&)   (Yoga.cpp:3124)
34  discover                        0x2058fb470         YGLayoutNodeInternal(YGNode*, float, float, YGDirection, YGMeasureMode, YGMeasureMode, float, float, bool, char const*, YGConfig*, YGMarkerLayoutData&)   (Yoga.cpp:3861)
35  discover                        0x2058fd3c8         YGNodelayoutImpl(YGNode*, float, float, YGDirection, YGMeasureMode, YGMeasureMode, float, float, bool, YGConfig*, YGMarkerLayoutData&)   (Yoga.cpp:3124)
36  discover                        0x2058fb470         YGLayoutNodeInternal(YGNode*, float, float, YGDirection, YGMeasureMode, YGMeasureMode, float, float, bool, char const*, YGConfig*, YGMarkerLayoutData&)   (Yoga.cpp:3861)
37  discover                        0x2058fd3c8         YGNodelayoutImpl(YGNode*, float, float, YGDirection, YGMeasureMode, YGMeasureMode, float, float, bool, YGConfig*, YGMarkerLayoutData&)   (Yoga.cpp:3124)
38  discover                        0x2058fb470         YGLayoutNodeInternal(YGNode*, float, float, YGDirection, YGMeasureMode, YGMeasureMode, float, float, bool, char const*, YGConfig*, YGMarkerLayoutData&)   (Yoga.cpp:3861)
39  discover                        0x2058fd3c8         YGNodelayoutImpl(YGNode*, float, float, YGDirection, YGMeasureMode, YGMeasureMode, float, float, bool, YGConfig*, YGMarkerLayoutData&)   (Yoga.cpp:3124)
40  discover                        0x2058fb470         YGLayoutNodeInternal(YGNode*, float, float, YGDirection, YGMeasureMode, YGMeasureMode, float, float, bool, char const*, YGConfig*, YGMarkerLayoutData&)   (Yoga.cpp:3861)
41  discover                        0x2058fe090         YGNodelayoutImpl(YGNode*, float, float, YGDirection, YGMeasureMode, YGMeasureMode, float, float, bool, YGConfig*, YGMarkerLayoutData&)   (Yoga.cpp:3473)
42  discover                        0x2058fb470         YGLayoutNodeInternal(YGNode*, float, float, YGDirection, YGMeasureMode, YGMeasureMode, float, float, bool, char const*, YGConfig*, YGMarkerLayoutData&)   (Yoga.cpp:3861)
43  discover                        0x2058fd3c8         YGNodelayoutImpl(YGNode*, float, float, YGDirection, YGMeasureMode, YGMeasureMode, float, float, bool, YGConfig*, YGMarkerLayoutData&)   (Yoga.cpp:3124)
44  discover                        0x2058fb470         YGLayoutNodeInternal(YGNode*, float, float, YGDirection, YGMeasureMode, YGMeasureMode, float, float, bool, char const*, YGConfig*, YGMarkerLayoutData&)   (Yoga.cpp:3861)
45  discover                        0x2058fd3c8         YGNodelayoutImpl(YGNode*, float, float, YGDirection, YGMeasureMode, YGMeasureMode, float, float, bool, YGConfig*, YGMarkerLayoutData&)   (Yoga.cpp:3124)
46  discover                        0x2058fb470         YGLayoutNodeInternal(YGNode*, float, float, YGDirection, YGMeasureMode, YGMeasureMode, float, float, bool, char const*, YGConfig*, YGMarkerLayoutData&)   (Yoga.cpp:3861)
47  discover                        0x2058fd3c8         YGNodelayoutImpl(YGNode*, float, float, YGDirection, YGMeasureMode, YGMeasureMode, float, float, bool, YGConfig*, YGMarkerLayoutData&)   (Yoga.cpp:3124)
48  discover                        0x2058fb470         YGLayoutNodeInternal(YGNode*, float, float, YGDirection, YGMeasureMode, YGMeasureMode, float, float, bool, char const*, YGConfig*, YGMarkerLayoutData&)   (Yoga.cpp:3861)
49  discover                        0x2058fd3c8         YGNodelayoutImpl(YGNode*, float, float, YGDirection, YGMeasureMode, YGMeasureMode, float, float, bool, YGConfig*, YGMarkerLayoutData&)   (Yoga.cpp:3124)
50  discover                        0x2058fb470         YGLayoutNodeInternal(YGNode*, float, float, YGDirection, YGMeasureMode, YGMeasureMode, float, float, bool, char const*, YGConfig*, YGMarkerLayoutData&)   (Yoga.cpp:3861)
51  discover                        0x2058fd3c8         YGNodelayoutImpl(YGNode*, float, float, YGDirection, YGMeasureMode, YGMeasureMode, float, float, bool, YGConfig*, YGMarkerLayoutData&)   (Yoga.cpp:3124)
52  discover                        0x2058fb470         YGLayoutNodeInternal(YGNode*, float, float, YGDirection, YGMeasureMode, YGMeasureMode, float, float, bool, char const*, YGConfig*, YGMarkerLayoutData&)   (Yoga.cpp:3861)
53  discover                        0x2058fd3c8         YGNodelayoutImpl(YGNode*, float, float, YGDirection, YGMeasureMode, YGMeasureMode, float, float, bool, YGConfig*, YGMarkerLayoutData&)   (Yoga.cpp:3124)
54  discover                        0x2058fb470         YGLayoutNodeInternal(YGNode*, float, float, YGDirection, YGMeasureMode, YGMeasureMode, float, float, bool, char const*, YGConfig*, YGMarkerLayoutData&)   (Yoga.cpp:3861)
55  discover                        0x2058feac8         YGNodeCalculateLayout   (Yoga.cpp:4096)
56  discover                        0x202928d18         -[RCTShadowView layoutWithMinimumSize:maximumSize:layoutDirection:layoutContext:]   (RCTShadowView.m:275)
57  discover                        0x20291dd7c         -[RCTRootShadowView layoutWithAffectedShadowViews:]   (RCTRootShadowView.m:34)
58  discover                        0x2029414b0         -[RCTUIManager uiBlockWithLayoutUpdateForRootView:]   (RCTUIManager.m:479)
59  discover                        0x202945478         -[RCTUIManager _layoutAndMount]   (RCTUIManager.m:1074)
60  discover                        0x2028df2d0         __32-[RCTCxxBridge batchDidComplete]_block_invoke   (RCTCxxBridge.mm:1337)
61  libdispatch.dylib               0x31b08e298         _dispatch_call_block_and_release  + 23
62  libdispatch.dylib               0x31b08f280         _dispatch_client_callout  + 15
63  libdispatch.dylib               0x31b06b4fc         _dispatch_lane_serial_drain$VARIANT$armv81  + 567
64  libdispatch.dylib               0x31b06bfe8         _dispatch_lane_invoke$VARIANT$armv81  + 403
65  libdispatch.dylib               0x31b075808         _dispatch_workloop_worker_thread  + 691
66  libsystem_pthread.dylib         0x3a69195a4         _pthread_wqthread  + 272

## React Native version:
0.59.20

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

## Expected Results
Describe what you expected to happen.

## Snack, code example, screenshot, or link to a repository:
Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by dulmandakh** [comment]
@scutliyizhen could you please upgrade to latest supported version of RN, and provide reproducible demo code as @rectified95 suggested. I would propose to close the issue until we have reproducible demo code.
