### ISSUE TITLE
Text Component not showing when use numberOfLines and text dir changed

### ISSUE THREAD

**Issue by ebeliejinfren** [facebook/react-native#30683]
Hello
Text Component not showing when i use **numberOfLines** prop for it and text content direction changed
if i have below code and change "TextContent" instantly by change app language (i18next) and if the **direction** of the language be different, **Text Not Shown**
_different between direction like : from english (ltr) to arabic (rtl) or Conversely_
also this issue not appear by re-render or new render and after re-render (or new render) it's work fine. it just happened when in current screen, the text content direction changed.

`<Text numberOfLines={1} ellipsizeMode={'tail'} style={{color: '#ffffff'}}>TextContent</Text>`

## React Native version:
react: 16.13.1 => 16.13.1
react-native: 0.63.2 => 0.63.2

**Comment by chrisglein** [comment]
I'm seeing other issues logged against `numberOfLines`. Related to #30437?
