### ISSUE TITLE
Text in android put a scroll when use selectable={true}, numberOfLines={2} and not work ellipsizeMode property

### ISSUE THREAD

**Issue by r41d0n** [facebook/react-native#30684]
## Description
When you can use the` <Text/>` component in android. If you use ellipsizeMode property with selectable={true} and numberOfLines={2}. The component put a scrollable area. 

## React Native version:
System:
    OS: macOS 11.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 978.42 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.1 - ~/.nvm/versions/node/v14.15.1/bin/node
    Yarn: Not Found
    npm: 6.14.9 - ~/.nvm/versions/node/v14.15.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.1
      System Images: android-16 | Google APIs Intel x86 Atom, android-19 | Google APIs Intel x86 Atom, android-22 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-24 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.3/12C33 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_265 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.4 => 0.63.4
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
To reproduce the error you can copy the code below

```
<Text selectable={true} numberOfLines={2} style={styles.sectionDescription}>
    Edit to change this screen and then come back to see your edits.
    Edit to change this screen and then come back to see your edits.
    Edit to change this screen and then come back to see your edits.
</Text>

```
## Expected Results
![image](https://user-images.githubusercontent.com/19432280/103556896-32891080-4e91-11eb-8812-33b25029ea9c.png)

## Actual Behavior:
![image](https://user-images.githubusercontent.com/19432280/103556816-15544200-4e91-11eb-8770-c66e2c84b058.png)

**Comment by pedrocardoz0** [comment]
I think you can edit this style at the native modules.
> _You can take a look at [Scrollview](https://reactnative.dev/docs/using-a-scrollview)_

**Comment by chrisglein** [comment]
Maybe related: #30437

**Comment by rectified95** [comment]
Can confirm, using `selectable` along with `ellipsideMode` breaks ellipsis.

**Comment by fabriziobertoglio1987** [comment]
https://reactnative.dev/docs/text#ellipsizemode the text should not be cut and display as `"...wxyz"`?

**Comment by fabriziobertoglio1987** [comment]
https://github.com/facebook/react-native/issues/30326

**Comment by fabriziobertoglio1987** [comment]
@r41d0n @rectified95 Do you still experience this issue? If yes, I will publish the fix in the react-native-improved package https://github.com/fabriziobertoglio1987/react-native-improved. Thanks a lot

**Comment by fabriziobertoglio1987** [comment]
The issue will be marked as resolved and it will not be possible to comment anymore in this issue.
