### ISSUE TITLE
React Native Builds not visible in App Store Connect

### ISSUE THREAD

**Issue by Ponniy2016** [facebook/react-native#30697]
I would like to submit my React Native APP to Apple store. I've uploaded my app through Xcode and also with "Transporter" App. App shows that the build uploaded successfully. But when i checked with my App store account no builds available for submitting my APP for review.

Environment Info:
System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
    Memory: 109.43 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.14.1 - /usr/local/opt/node@12/bin/node
    npm: 6.13.6 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    Android SDK:
      API Levels: 21, 22, 23, 24, 25, 26, 27, 28, 29
      Build Tools: 28.0.0, 28.0.1, 28.0.2, 28.0.3, 29.0.2, 29.0.3, 30.0.2
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 12.2/12B45b - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.0 => 0.60.0

Thanks in advance.

**Comment by Frans-L** [comment]
Appstore processes uploaded apps around 30 minutes before you can see them appear in Appstore Connect.
Could this be the case? :)

**Comment by rahulson** [comment]
@Ponniy2016 
Please check your mail linked with developer account. You will receive an email about the state of your build submitted.
Hope you will get proper info about the disappearance of you build from appstore connect

**Comment by Ponniy2016** [comment]
> Appstore processes uploaded apps around 30 minutes before you can see them appear in Appstore Connect.
> Could this be the case? :)

**Comment by Ponniy2016** [comment]
Thanks @rahulson and @Frans-L. Actually I am using the API call from HTTP not from HTTPS after I changed the API URL to HTTPS. Its working fine.

Thanks Guys.

**Comment by dulmandakh** [comment]
Closing this because its not related to RN but AppStore.
