### ISSUE TITLE
TextInput clears laggy with much content on screen

### ISSUE THREAD

**Issue by andrepinkman** [facebook/react-native#30692]
## Description

I have an issue that when I spam typing in a TextInput and click a button on to submit and clear the text it becomes laggy and it doesn't clear the text in the TextInput right away. This happens when I have a lot of content within the Screen (like Lorem Ipsum text).

This is a problem for me, because I am developing a chat app and whenever the chat log is large and the users types and submits the message fast it won't get cleared immediately and will still remain in the TextInput, which is bad usability. I tried it with ref and controlled TextInput (no difference).

You can see the issue in my gif:

![stackk](https://user-images.githubusercontent.com/58225896/103716839-4719f580-4fc4-11eb-9ce3-f7542af84489.gif)

## React Native version:

Expo CLI 4.0.13 environment info:
System:
OS: macOS 10.15.7
Shell: 5.7.1 - /bin/zsh
Binaries:
Node: 14.13.1 - /usr/local/bin/node
npm: 6.14.8 - /usr/local/bin/npm
SDKs:
iOS SDK:
Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
IDEs:
Android Studio: 4.1 AI-201.8743.12.41.6953283
Xcode: 12.3/12C33 - /usr/bin/xcodebuild
npmPackages:
expo: ~40.0.0 => 40.0.0
react: 16.13.1 => 16.13.1
react-dom: 16.13.1 => 16.13.1
react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2
react-native-web: ~0.13.12 => 0.13.18
npmGlobalPackages:
expo-cli: 4.0.13
Expo Workflow: managed

## Expected Results
The TextInput should clear right away after submitting the value and clearing it.

## Snack, code example, screenshot, or link to a repository:
https://snack.expo.io/s22hVf140

**Comment by dulmandakh** [comment]
This issue tracker is intended for RN issues only, not developer support. But I would pass **text** as value to TextInput and submit would setText("")

```jsx
import React, { useRef } from "react";
import { useState } from "react";
import { Button, TextInput, View } from "react-native";

const MyTextInput = ({ addMessage }) => {
  const [text, setText] = useState("");
  const myRef = useRef();
  const submit = () => {
    setText("");
    addMessage(text);
  };

  return (
    <View>
      <TextInput
        ref={myRef}
        style={{
          width: "100%",
          height: 50,
          backgroundColor: "lightgrey",
          marginTop: 50,
        }}
        onChangeText={(text) => setText(text)}
        value={text}
      ></TextInput>
      <Button title="submit" onPress={submit}></Button>
    </View>
  );
};

export default MyTextInput;
```

**Comment by andrepinkman** [comment]
why did you close it? I also tried it with using text as a value without a difference, that's why I wrote: I tried it with ref and controlled TextInput (no difference).
It also doesn't make a difference if I put it in production.

It's obviously a bug, since my code is really minimal.

**Comment by rozele** [comment]
This looks like a dupe of https://github.com/facebook/react-native/issues/30319 anyway
