### ISSUE TITLE
[Android] custom ViewGroup run into NullPointerException at ReactViewBackgroundDrawable.drawRoundedBackgroundWithBorders

### ISSUE THREAD

**Issue by xinthink** [facebook/react-native#3069]
Hi, I wrote a simple native UI component, but it failed to draw with the follow error:
```
E/AndroidRuntime(14469): java.lang.NullPointerException: Attempt to read from field 'boolean android.graphics.Path.isSimplePath' on a null object reference
E/AndroidRuntime(14469): 	at android.view.GLES20Canvas.drawPath(GLES20Canvas.java:796)
E/AndroidRuntime(14469): 	at com.facebook.react.views.view.ReactViewBackgroundDrawable.drawRoundedBackgroundWithBorders(ReactViewBackgroundDrawable.java:187)
E/AndroidRuntime(14469): 	at com.facebook.react.views.view.ReactViewBackgroundDrawable.draw(ReactViewBackgroundDrawable.java:91)
```

The view do nothing but intercept the touch events:
```java
public class CustomViewGroup extends ReactViewGroup {

    @Nonnull
    private final OnInterceptTouchEventListener onInterceptTouchEventListener;

    public CustomViewGroup(Context context,
                       @Nonnull OnInterceptTouchEventListener touchEventListener) {
        super(context);
        this.onInterceptTouchEventListener = touchEventListener;
    }

    @Override
    public boolean onInterceptTouchEvent(MotionEvent ev) {
        return this.onInterceptTouchEventListener.onInterceptTouchEvent(this, ev)
                || super.onInterceptTouchEvent(ev);
    }
}
```

```jsx
<CustomViewGroup style={{
  backgroundColor: 'blue',
  borderRadius: 2,
  ...
}}
/>
```

**Comment by astreet** [comment]
Can you verify that setting a border width fixes this issue? I wouldn't think that this has anything to do with you using a custom view.

**Comment by xinthink** [comment]
No, I didn't set a borderWidth.
What I want is a borderless rounded-corner rectangle, setting the borderRadius is a pattern works on Web and iOS. And there's no document telling us that we can use `borderRadius` only if the `borderWidth` is larger than zero. 
I think many developers will be happy to see RN for Android supporting this feature.

And the null-checking code working fine in my project:
![0](https://cloud.githubusercontent.com/assets/390805/10137861/3a870b58-662e-11e5-8b1f-fedf7cc88c1d.png)

**Comment by astreet** [comment]
Ah sorry, I misinterpretted what you were trying to do, yes that behavior should work. I'm not able to repro this on my setup so I think there's something we must be missing. Can you share the exact code? Does it not repro with View?

In the meantime, looking at the framework code, we would get this issue if updatePath never created a path, which means mNeedUpdatePathForBorderRadius was false, which can happen if onBoundsChange is never called. It seems like we should be setting it to true on setRadius anyway which might be the actual bug.

**Comment by xinthink** [comment]
Thanks for the quick replying. I'll try to put a demo on rnplay.org reproducing the problem.

**Comment by kmagiera** [comment]
Can you try this on an ImageView component? There will still be a difference in behavior between iOS and android as on android we don't actually clip the content of the view to the bounds of the rounded parent as it's a very inefficient operation on that platform. We'd still need to figure sth out to be fully compatible in the case of rounded borders.

**Comment by xinthink** [comment]
Yes, of course. I'll try it in the nex few days

**Comment by xinthink** [comment]
I found the way reproducing the problem, it did relate to `ImageView` like @kmagiera mentioned, here's the code:

```jsx

var RippleView = React.createClass({
  getInitialState: function() {
    return {width: 0, height: 0};
  },
  componentDidMount: function() {
    requestAnimationFrame(this._doMeasurement);
  },
  _doMeasurement: function() {
    this.refs.container.measure((x, y, width, height) => {
      this.setState({
        width,
        height,
      });
    });
  },
  render: function() {
    console.log('rippleView dimes:', this.state);
    return (
      <View ref="container"
            style={[this.props.style, {
              backgroundColor: '#3F51B5',
              borderRadius: 2,
            }]}
            pointerEvents="box-only"
        >
        {this.props.children}
        <View
          ref="mask"
          style={{
            position: 'absolute',
            backgroundColor: 'rgba(255,255,255,.75)',
            width: this.state.width,
            height: this.state.height,
            borderRadius: 2,
          }}
          />
      </View>
    );
  }
});

var RNSample = React.createClass({
  render: function() {
    return (
      <View style={styles.container}>
        <RippleView style={{
            width: 64,
            height: 64,
          }}
          >
          <Image source={require('image!plus_white')} />
        </RippleView>
      </View>
    );
  }
});
```

NPE occurs when an `Image` inside a container, whose size is zero, but with a `borderRadius` > 0, however, the same code works fine on iOS.

In the above example, I made a absolute positioned *mask* layer (shown on top of the content view), whose size is determined at runtime, with an initial size of zero, which cause the NPE.

Any thoughts? Should I just make it with any initial size > 0, or the framework should be more robust to tolerate such a situation?

**Comment by satya164** [comment]
Is this still an issue?

**Comment by xinthink** [comment]
Not sure, I've been using my workaround for a while.
But I think it's better to allow a zero initial size (while a borderRadius is given).

**Comment by xinthink** [comment]
Tested with RN 0.17.0, looks like it's working fine. 
Closing this issue, thanks for fixing it!
