### ISSUE TITLE
TextInput clear() not working for number_pad keyboard type

### ISSUE THREAD

**Issue by srkela** [facebook/react-native#30702]
## Description
TextInput `clear()` method is not working when keyboard type is set to `number_pad` in react-native v0.63.4

## React Native version:
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 256.52 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.14.2 - ~/.nvm/versions/node/v10.14.2/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.14.2/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /Users/srdjandjenader/.rvm/gems/ruby-2.7.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.3/12C33 - /usr/bin/xcodebuild
  Languages:
    Java: 12.0.2 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
After upgrading to latest version of react-native `clear()` method is not working any longer when keyboard type is set to `number_pad`. `focus()` and `blur()` work as expected. 

When change keyboard type to `numeric`, `clear()` works as expected

**Comment by fabriziobertoglio1987** [comment]
would be helpful having a reproducible example to quickly troubleshoot the issue.
Also not clear to me if this issue is for Android, iOS or both platform. Thanks

**Comment by srkela** [comment]
Ok, I figured what was this about. Looks like that was not RN, but React issue. Since in the project I have  React `17.0.1` and  currently Expo is with`16.x.x` I cannot reproduce
It is about class component, and am using `ref` to call `clear()` method.

This is not working:
```

triggerClear = () ={
   
   this.clearInput()
}

 clearInput = () => {
     this.inputRef.clear()
 }

...

render() {
   return(
        <TextInput
          keyboardType={"numeric"}
          ref={input => {
            this.inputRef = input;
          }}
          onChangeText={(num) => this.changeInputText(num)}
        />
   )
}
```
When I add early exit and timeout in `clearInput()` method, everything works fine

```
  clearInput = () => {
    if (!this.inputRef) return null
    setTimeout(() => {
      this.inputRef.clear()
    })
  }
```
For some reason, that happened when we upgraded RN and React to latest versions on both platforms. 
Worked fine before on IOS and Android.
