### ISSUE TITLE
onPress function does not working on TouchableOpacity, Pressable, Button components inside a PanResponder handler

### ISSUE THREAD

**Issue by RichardRNStudio** [facebook/react-native#30704]
## Description
I've found a lot of similar issues with different solutions, but none of them worked so the problem is still exists. I'm aware of the following situation: When I import the `TouchableOpacity` from the `react-native-gesture-handler` package then it's working. But I'm working on a new NPM package, so I wouldn't like to install a new dependency instead of pure `react-native` components.

## React Native version:
0.63.4

## Steps To Reproduce
1. Create a `TouachableOpacity` inside a `View`.
2.
`<TouchableOpacity onPress={() => Linking.openURL("https://reactnative.dev/")}>`
      `<Text>https://reactnative.dev/</Text>`
`</TouchableOpacity>`

## Expected Results
It should open a browser and navigate to the link, but nothing happens.

**Comment by moniquealtero** [comment]
Same here

**Comment by safaiyeh** [comment]
Hi @RichardRNStudio thanks for issue. Could you provide a Snack or Repro that demonstrates the issue so it is easier to debug the problem you are facing?

**Comment by RichardRNStudio** [comment]
Hi @safaiyeh, I've investigated again the issue, and I wrote a new NPM package. There is a `TouchableOpacity` inside a `PanResponder`. When I test my package as seperated then it's working. I've recognized something: after I installed it on my application which includes react-navigation `NavigationContainer` then the `onPress` function does not working. I've found a new solution: use `TouchableWithoutFeedback` from `react-native-gesture-handler` and use `onPressIn` instead of `onPress` . Sorry I can't share my repositories with you, because all of them are private. 

One more thing, this is my `PanResponder` settings: 
`
const panResponderItem = PanResponder.create({
      onStartShouldSetPanResponder: () => false,
      onMoveShouldSetPanResponder: (_, gestureState) => {
        return gestureState.dx != 0 && gestureState.dy != 0; // handle the gesture whether is click or drag event
      },
      onMoveShouldSetPanResponderCapture: (_, gestureState) => {
        return gestureState.dx != 0 && gestureState.dy != 0;
      },
      onStartShouldSetPanResponderCapture: () => false,
      onPanResponderMove: (_, gesture) => {
        ... handle Gesture event ...
      },
      onPanResponderRelease: (_, gesture) => {
        ... handle Gesture event ...
      },
    });
`

Does my description make sense?

Thanks, Richárd

**Comment by safaiyeh** [comment]
For `react-native-gesture-handler` you should file an issue here: https://github.com/software-mansion/react-native-gesture-handler

**Comment by silenteyesoncode** [comment]
I'm facing the same issue with IOS 


Here is my Pan
```
 const panResponder = useRef(
    PanResponder.create({

      onMoveShouldSetPanResponderCapture: (evt, gestureState) => {
        return gestureState.dx != 0 && gestureState.dy != 0;
      },
      onStartShouldSetPanResponder: (evt, gestureState) => true,
      onMoveShouldSetPanResponder: () => true,
      onPanResponderGrant: () => {

        var PanMin = pan.y._value;
        const halfBox_Area1 = -(Math.abs(b - b/3));
        const halfBox_Area2 = -(Math.abs(b + b/3));
        // console.log(halfBox_Area1 , halfBox_Area2, 'half Offset')

        if (  PanMin >= Iphone_waale ) {
          pan.setOffset({y : Iphone_waale})
        }
        if (  PanMin <= halfBox_Area1 && PanMin > halfBox_Area2 ) {
          pan.setOffset({y : -b})
        }
        if (  PanMin < -e ) {
          pan.setOffset({y : -e})
        }
        else{
          pan.setOffset({
            // x: pan.x._value,
            // y: pan.y._value,
            y: PanMin
          });
        }
        // console.log(PanMin, 'granasat');
      },

      onPanResponderMove: Animated.event([
              null,
              {
                dy: pan.y,
              },
            ],
            { listener: (_ , gestureState) =>  {
              pan.y.setValue(gestureState.dy)
              // console.log('dyy', gestureState.dy , "\n", "Mypan" , pan)
            }}

          ),
      onPanResponderRelease: () => {
        pan.flattenOffset();

        const pan_pos = pan.y._value;
        // console.log(pan_pos, 'pos')
        const halfBox_Area1 = -(Math.abs(b - b/3));
        const halfBox_Area2 = -(Math.abs(b + b/3));
        // console.log(halfBox_Area1 , halfBox_Area2, 'half')

        if (pan_pos > Iphone_waale) {
          pan.y.setValue(Iphone_waale)
        }
        if ( pan_pos < halfBox_Area1 && pan_pos > halfBox_Area2) {
          pan.y.setValue(-b)
        }
    
        if ( pan_pos < -e) {
          pan.y.setValue(-e)
        }
    
        pan.flattenOffset();
        
      }
    })
  ).current;
```

Here IS the Markup
```
 <Animated.View
    {...panResponder.panHandlers}
      style={[
          styles.greBox,
          {transform: [{ translateY: pan.y }]}
        ]}
    >
     <Pressable
                onPress={() => {
                  props.onRcChange(1);
                  console.log(e);
                }}
                style={styles._____}
              >
              </Pressable>
<Animated.View>
```
