### ISSUE TITLE
How to change port on RN 61 for IOS?

### ISSUE THREAD

**Issue by filipemerker** [facebook/react-native#30708]
## Description
Ok, I know that, [in the official docs](https://reactnative.dev/docs/troubleshooting) it says I have to use the `port` parameter.

But it also says that for IOS:

> [...] update occurrences of 8081 to your chosen port in the *node_modules/react-native/React/React.xcodeproj/project.pbxproj* file

The problem is that [here](https://reactnative.dev/blog) it says RN 60 **removes** "React.xcodeproj".

My question is, then: **What is the new way of changing ports, whitout React.xcodeproj**?

I'm running bundler and `react-native run-ios` with `--port=9000` but, of course, I'm getting this error:

> An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2): Failed to install the requested application An application bundle was not found at the provided path.

Because somewhere, port :8081 is still hardcoded.

And *no* I can't just kill what's on port 8081. This is a corporate computer that has McAffee running on 8081 and this process won't shut down :(

## React Native version:
"react": "16.9.0",
"react-native": "0.61.2"

macOS Catalina 10.15.7
Xcode 11.5

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. `react-native start --port=9000`
2. `react-native run-ios --port 9000`

## Expected Results
`An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist
error Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier
Print: Entry, ":CFBundleIdentifier", Does Not Exist`

**Comment by safaiyeh** [comment]
@filipemerker Thanks for the issue! I tried the commands locally on fresh React Native project and it seems to be working properly.

Could you provide a repro that consistently shows this issue?

**Comment by pachuka** [comment]
@safaiyeh - This isn't working for me on `react-native` 0.64.0. via the `--port=8082` flag specifically for the ios build.

```bash
react-native start --port=8082  // bundler appears to properly start on port 8082
react-native run-ios --port=8082  // doesn't work
react-native run-android --port=8082 // works fine
```

Looks like the issue for iOS stems from `RCTDefines.h` in `node_modules/react-native/React/Base/RCTDefines.h`

![image](https://user-images.githubusercontent.com/3280602/112772901-680d4800-9001-11eb-8a50-ce3cbe12c084.png)

If I update the port here to `8082` then run the ios command, then things work properly on the custom port, but that kind of defeats the purpose of having the cli argument if we still need to manually edit files to get it to work.

**Comment by jzxchiang1** [comment]
> @safaiyeh - This isn't working for me on `react-native` 0.64.0. via the `--port=8082` flag specifically for the ios build.
> 
> ```shell
> react-native start --port=8082  // bundler appears to properly start on port 8082
> react-native run-ios --port=8082  // doesn't work
> react-native run-android --port=8082 // works fine
> ```
> 
> Looks like the issue for iOS stems from `RCTDefines.h` in `node_modules/react-native/React/Base/RCTDefines.h`
> 
> ![image](https://user-images.githubusercontent.com/3280602/112772901-680d4800-9001-11eb-8a50-ce3cbe12c084.png)
> 
> If I update the port here to `8082` then run the ios command, then things work properly on the custom port, but that kind of defeats the purpose of having the cli argument if we still need to manually edit files to get it to work.

I can confirm this fixed it for me, and the `--port` flag in `run-ios` did nothing. Really confusing.

**Comment by thisisgit** [comment]
I'm seeing the same issue in `0.66.4`.

**Comment by leepowellnbs** [comment]
I have a temp fix (I'm not a Ruby dev so there's probably a better way of doing this):

1) Update Podfile to 
```
post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)

    # Port fix
    installer.pods_project.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'].insert(0, "RCT_METRO_PORT=${RCT_METRO_PORT}")
    end
end
```

2) Run `pod install` again

**Comment by andidev** [comment]
I can confirm this is still an issue in 0.66.4 and that leepowellnbs solution together with `npx react-native run-ios --port=8083 seems to make it work again. Super thanks @leepowellnbs !
