### ISSUE TITLE
Libraries folder empty after cloning my app repo

### ISSUE THREAD

**Issue by rodrigofbm** [facebook/react-native#30700]
![Problem](https://user-images.githubusercontent.com/14153439/103947321-aab43800-5116-11eb-8095-ef649acf45d7.jpeg)

Hello guys. My Libraries folder is empty. I need to link the libs but it's not showing up. 
**I already ran pod install and npx react-native link and I got no errors.** 
This App I've run a few times without a problem, but I changed my machine and cloned the repo and now I'm facing this problems because the libraries I have linked are gone.

# Environment
"react": "16.13.1",
"react-native": "0.63.2"

MacOS Catalina 15.5.5
NodeJS: 14.15.4 LTS
Xcode: 12.3

**Comment by dulmandakh** [comment]
Sorry the issue is not related to RN, but the way you manage the code.
