### ISSUE TITLE
Hooks do not work in Headless JS

### ISSUE THREAD

**Issue by SamuelBrucksch** [facebook/react-native#30707]
## Description
I tried to reuse code from our App in a Headless JS implementation. The code in the app uses Hooks like useState and everything works fine. However when i run parts of the app code in a Headless JS task, i get an error like this:

```
2021-01-07 20:38:52.130 12444-12569/xxxxxxxx E/ReactNativeJS: { [Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
    1. You might have mismatching versions of React and the renderer (such as React DOM)
    2. You might be breaking the Rules of Hooks
    3. You might have more than one copy of React in the same app
    See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.]
      line: 5774,
      column: 24,
      sourceURL: 'http://localhost:8081/index.bundle?platform=android&dev=true&minify=false' }
```

## React Native version:`
```
> react-native info

info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.18363
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 15.74 GB / 31.71 GB
  Binaries:
    Node: 12.14.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6953283
    Visual Studio: Not Found
  Languages:
    Java: 15.0.1
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: ^0.63.2 => 0.63.2
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
index.ts:
```
import { AppRegistry } from 'react-native';
import App from './src/App';
import VerySimpleApp from './src/domain/MainPage/headless';

AppRegistry.registerComponent('App', () => App);
AppRegistry.registerHeadlessTask('HeadlessService', () => VerySimpleApp); // headless service for android
```

headless.ts:
```
async function VerySimpleApp() {
  console.log('Headless JS started');
  const [count, setCount] = useState(0);

  console.log('Count: ' + count);

  setCount(count + 1);

  console.log('Count: ' + count);
}
```

When i do not use `useState` everything works fine. Then the task runs and i get all tge logging and no errors.

## Expected Results
Hooks should work in Headless JS like in the app so we can reuse some parts of the logic.

## Snack, code example, screenshot, or link to a repository:
See steps to reproduce

There are also other people, that ran into this problem:
https://stackoverflow.com/questions/57708197/how-to-use-hooks-in-headless-js-function-with-react-native-firebase

**Comment by dulmandakh** [comment]
Please look into https://reactnative.dev/docs/headless-js-android, and you'll see that Headless JS is Android Service thus you cannot run UI code or React.

**Comment by SamuelBrucksch** [comment]
Hi @dulmandakh 

thanks for your answer. This is a bit unexpected, as hooks can also used without UI elements. I was not aware, that hooks itself also count as UI, thats why i opened the issue.

Thanks for clarification.

BR
Samuel
