### ISSUE TITLE
How can i upload File to server from React-native 

### ISSUE THREAD

**Issue by subbareddyandr** [facebook/react-native#30703]
Hi , Please Help me to upload file from react-native to node server
  
const image =  { uri: response.uri, type: response.type, name: response.fileName }
**Note : {response} from image-picker**
let data = new FormData();
data.append('file', image);
  fetch(url , {
                 method:"post",
                 body:data,
                 headers:{"content-type":"multipart/form-data"}
         }).then(res=>console.log(res));
as mentioned above  i am sending file from react-native , but i am not receving file  at server side  ,

app.post("/uploadfile",upload.single("file"), (req, res) => {
    **console.log(req.file)    // getting undifined**
  **console.log(req.body.file)   // '[object Object]'**
    if (req.file) {
     
    }
})

Help me to solve this problem 
Thanks in advance

**Comment by memosize** [comment]
it's not react native issues ,it's your issues

**Comment by dulmandakh** [comment]
This issue tracker is intended to track React Native issue, not developer support. Closing this.
