### ISSUE TITLE
react-native init AwesomeProject fails on Windows 10 :'(

### ISSUE THREAD

**Issue by subtleGradient** [facebook/react-native#3071]
```
PS C:\Users\Thomas> npm install -g react-native-cli
C:\Users\Thomas\AppData\Roaming\npm\react-native -> C:\Users\Thomas\AppData\Roaming\npm\node_modules\react-native-cli
\index.js
react-native-cli@0.1.4 C:\Users\Thomas\AppData\Roaming\npm\node_modules\react-native-cli
â””â”€â”€ prompt@0.2.14 (revalidator@0.1.8, pkginfo@0.3.0, read@1.0.7, winston@0.8.3, utile@0.2.1)

PS C:\Users\Thomas> react-native init AwesomeProject
This will walk you through creating a new React Native project in C:\Users\Thomas\AwesomeProject
react-native : events.js:141
At line:1 char:1
+ react-native init AwesomeProject
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (events.js:141:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
      throw er; // Unhandled 'error' event
      ^
Error: spawn npm ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:429:9)
    at process._tickCallback (node.js:343:17)
    at Function.Module.runMain (module.js:477:11)
    at startup (node.js:117:18)
    at node.js:951:3
```

**Comment by BBLN** [comment]
https://github.com/facebook/react-native/issues/2681

Anyway, you can replace npm with npm.cmd for now.

```
run('npm install --save react-native'
```
(react-native-cli/index.js)

**Comment by adaojunior** [comment]
@subtleGradient I was having the same problem and this is how I solved.
```
> npm install -g react-native-cli
> mkdir AwesomeProject && cd AwesomeProject
```

add `package.json`
```
{
  "name": "AwesomeProject",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "sh ./node_modules/react-native/packager/packager.sh"
  },
  "dependencies": {
    "react-native": "0.12.0-rc"
  }
}
``` 

```
> npm install
> react-native android
```

Ooookay by now you should have a project estructure, now just start the `packager`
```
> npm start // supposed to work but didnt for me
> sh ./node_modules/react-native/packager/packager.sh // now this is working
```

Now just be sure to have a phone connected or a emulator running and `> react-native run-android`

Let me know if this works for you.

**Comment by yeso126** [comment]
> sh ./node_modules/react-native/packager/packager.sh 

That partr doesn't work for me :(

**Comment by adaojunior** [comment]
@yeso126 what happens? any logs?
Do you have your ANDROID_HOME set?

**Comment by BBLN** [comment]
Follow this: https://gist.github.com/mqli/e1e6576e9838d885a43a

Seems to be resolved.

**Comment by yeso126** [comment]
Yeah, I didn't had the ANDROID_HOME set I'm such a noob in these things thanks, now I did it and I'm getting the following error:
> Execution failed for task ':app:compileDebugJavaWithJavac'. 

C:\Users\yeso1\Documents\PROJECTS\react-native\foodlistr\android\app\src\main\java\com\facebook\react\sample\MainActivity.java:44: error: cannot find symbol
                .setUseDeveloperSupport(BuildConfig.DEBUG)
                                        ^
  symbol:   variable BuildConfig
  location: class MainActivity
1 error
:app:compileDebugJavaWithJavac FAILED

**Comment by mkonicek** [comment]
Yes, Windows is not supported but the community is working on Windows support. As a workaround you can use https://gist.github.com/mqli/e1e6576e9838d885a43a

**Comment by dentrite** [comment]
The problem can be solved by rolling react-native-cli back to 0.1.7 if you are using 0.1.8.
http://stackoverflow.com/questions/34639911/react-native-windows-spawn-npm-enoent-error/34645696

**Comment by topgun743** [comment]
I am still having this weird error when I am trying to do `react-native init App`
I tried uninstalling from latest version of react-native-cli back to @0.1.7 but still the nasty error showing.

What to do now guys? I am frustrated.

Here is my console output

```
D:\ReactNative>react-native init App
This will walk you through creating a new React Native project in D:\ReactNative\App
Installing react-native package from npm...
Setting up new React Native app in D:\ReactNative\App
(node:5896) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
(node:5896) DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.
Installing React...
Installing Jest...
App@0.0.1 D:\ReactNative\App
`-- react@15.3.2

npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN prefer global marked@0.3.6 should be installed with -g
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: This socket is closed
    at WriteStream.Socket._writeGeneric (net.js:683:19)
    at WriteStream.Socket._write (net.js:734:8)
    at doWrite (_stream_writable.js:334:12)
    at writeOrBuffer (_stream_writable.js:320:5)
    at WriteStream.Writable.write (_stream_writable.js:247:11)
    at WriteStream.Socket.write (net.js:661:40)
    at WriteStream.stream.write (D:\ReactNative\App\node_modules\ansi\lib\newlines.js:36:21)
    at Console.warn (console.js:51:16)
    at child.log (D:\ReactNative\App\node_modules\yeoman-environment\lib\util\log.js:72:21)
    at child.end (D:/ReactNative/App/node_modules/react-native/local-cli/generator-ios/index.js:51:10)
```

**Comment by topgun743** [comment]
Seems like react-native devs aren't going to make life easy for other devs using their library. Guess they are more interested in just IOS. On windows lots of complains on different forums. Why cant they solve issues for windows?
