### ISSUE TITLE
Fonts sometimes not showing on iOS release

### ISSUE THREAD

**Issue by sofianegargouri** [facebook/react-native#30712]
## Description

When I run my app on my device with the following configuration in xCode:
- Scheme Build Configuration is in Release
- Debug Executable is disabled

*Sometimes* the text doesn't not load the custom font. It can have a different behavior on the same screen.
Example:
- I go to my "Settings" screen, text is in the right font
- I go back and unmount the screen
- I go back the the "Settings" screen, text is in iOS basic font. Happens randomly.

I could reproduce this on 5 of the apps I have on my laptop.

No problem on android when running with `--variant=release`. 
No problem when the app is archived, uploaded on TestFlight and then downloaded on the same device.

## React Native version:

```
System:
    OS: macOS 11.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 294.66 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.3 - ~/.nvm/versions/node/v14.15.3/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.9 - ~/.nvm/versions/node/v14.15.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /Users/sofiane/.rvm/gems/ruby-2.7.1/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.3/12C33 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_265 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.2 => 0.63.2
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce

1. Go to xCode, select your Scheme, edit it
2. In "Run", put "Build Configuration" to "Release"
3. Disable "Debug executable"
4. Run the app on a physical device
5. Disconnect your device from your computer
6. Start your app, use it a bit

## Expected Results

Custom fonts should load properly

**Comment by safaiyeh** [comment]
Hi @sofianegargouri thank you for the issue! Sorry you are having problems with the fonts in production.

Could you provide a bare minimum repro that I could run locally to test the issues you are seeing.

**Comment by sofianegargouri** [comment]
Found a solution:
I linked my fonts manually, by adding them to my XCode Project, instead of using the `react-native.config.js`. Once I did the same steps but with that script, everything started working again smoothly. No idea why though, but at least it works 🤷
