### ISSUE TITLE
Setting StatusBar as "hidden" prevents onLayout being called and causes bad behaviour on ScrollView

### ISSUE THREAD

**Issue by yalcinozer** [facebook/react-native#30713]
## Description
Setting StatusBar as "hidden" prevents onLayout being called and causes bad behavior on ScrollView. 

## React Native version:
System:
    OS: Linux 5.4 Ubuntu 18.04.5 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 1.42 GB / 15.51 GB
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 14.15.4 - /usr/bin/node
    Yarn: Not Found
    npm: 6.14.10 - /usr/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 23, 25, 27, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2
      System Images: android-24 | Google APIs Intel x86 Atom, android-25 | Google Play Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-27 | Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64, android-29 | Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 1.8.0_275 - /usr/bin/javac
    Python: 2.7.17 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Place a ScrollView and add some components in it to make its height more than screen height.  
2. If StatusBar is visible, when you tap on TextInput (and Keyboard will appear) ScrollView will still work flawlessly.
3. If you set StatusBar hidden, onLayout prop will not be called when keyboard did show/hide. Also ScrollView will show a limited area.

## Expected Results
StatusBar visibility shouldn't change ScrollView behavior.

## Snack, code example, screenshot, or link to a repository:

`<View style={{flex: 1}}>
<StatusBar hidden={true}/>
<ScrollView style={{flex: 1}}>
<Text>Start</Text>
<View style={{height: 900}}/>
<TextInput placeholder={'12123'}/>
<Text>End</Text>
</ScrollView>
</View>`

**Comment by safaiyeh** [comment]
@yalcinozer I checked out your code snippet and I could not identify the issue you are trying to demostrate.

Could you create a Snack and point exactly the issue you are seeing. I ran the snippet locally on my iOS simulator and the behavior seems to be consistent with hidden true & false. I might be missing something in the setup

**Comment by yalcinozer** [comment]
> @yalcinozer I checked out your code snippet and I could not identify the issue you are trying to demostrate.
> 
> Could you create a Snack and point exactly the issue you are seeing. I ran the snippet locally on my iOS simulator and the behavior seems to be consistent with hidden true & false. I might be missing something in the setup

Hi, I was not using Snack for a long time. So I test my code on both android and ios. Android on Snack does the exact same thing what I see on my emulator. I also see ios on Snack also has problems with these codes

I'm sharing the Snack link.
[Snack ScrolView-StatusBar link](https://snack.expo.io/Gx3fjhPlr)

**Comment by safaiyeh** [comment]
If you wrap the view with `KeyboardAvoidingView` you could get the behavior you need. Does this work for you?

```javascript
<KeyboardAvoidingView
      behavior={Platform.OS === "ios" ? "padding" : "height"}
       style={{ flex: 1 }}
    >
    <View style={{ flex: 1 }}>
      <StatusBar hidden={true} />
      <ScrollView style={{ flex: 1 }}>
        <Text>Start</Text>
        <View style={{ height: 700,backgroundColor:"red" }} />
        <TextInput placeholder={'12123'} />
        <View style={{ height: 700,backgroundColor:"red" }} />
        <Text style={{height:40}}>TRY TO SEE THIS TEXT WHEN KEYBOARD VISIBLE</Text>
      </ScrollView>
    </View>
</KeyboardAvoidingView>
```

**Comment by yalcinozer** [comment]
> If you wrap the view with `KeyboardAvoidingView` you could get the behavior you need. Does this work for you?
> 
> ```js
> <KeyboardAvoidingView
>       behavior={Platform.OS === "ios" ? "padding" : "height"}
>        style={{ flex: 1 }}
>     >
>     <View style={{ flex: 1 }}>
>       <StatusBar hidden={true} />
>       <ScrollView style={{ flex: 1 }}>
>         <Text>Start</Text>
>         <View style={{ height: 700,backgroundColor:"red" }} />
>         <TextInput placeholder={'12123'} />
>         <View style={{ height: 700,backgroundColor:"red" }} />
>         <Text style={{height:40}}>TRY TO SEE THIS TEXT WHEN KEYBOARD VISIBLE</Text>
>       </ScrollView>
>     </View>
> </KeyboardAvoidingView>
> ```

Hey thanks. I tried your code block. It runs good on Snack IOS but still have issues on Snack Android and emulator on my PC.
To get a consistent behaviour, I probably will avoid using ScollView and hidden StatusBar together.

I'm sharing a screen record. KeyboardAvoidingView behaves different depending on the input position when pressed. Final part is the result I wanted to have. I decided to keep StatusBar visible all the times :-) 

https://user-images.githubusercontent.com/48597826/104819800-f4043600-5840-11eb-8dcd-1a30b5b27be2.mp4

**Comment by safaiyeh** [comment]
> > If you wrap the view with `KeyboardAvoidingView` you could get the behavior you need. Does this work for you?
> > ```js
> > <KeyboardAvoidingView
> >       behavior={Platform.OS === "ios" ? "padding" : "height"}
> >        style={{ flex: 1 }}
> >     >
> >     <View style={{ flex: 1 }}>
> >       <StatusBar hidden={true} />
> >       <ScrollView style={{ flex: 1 }}>
> >         <Text>Start</Text>
> >         <View style={{ height: 700,backgroundColor:"red" }} />
> >         <TextInput placeholder={'12123'} />
> >         <View style={{ height: 700,backgroundColor:"red" }} />
> >         <Text style={{height:40}}>TRY TO SEE THIS TEXT WHEN KEYBOARD VISIBLE</Text>
> >       </ScrollView>
> >     </View>
> > </KeyboardAvoidingView>
> > ```
> 
> Hey thanks. I tried your code block. It runs good on Snack IOS but still have issues on Snack Android and emulator on my PC.
> To get a consistent behaviour, I probably will avoid using ScollView and hidden StatusBar together.
> 
> I'm sharing a screen record. KeyboardAvoidingView behaves different depending on the input position when focused. Final part is the result I wanted to have. I decided to keep StatusBar visible all the times :-)
> 
>  snack_test.mp4

Ah thank you for the video, now I see it.
