### ISSUE TITLE
Error: Failed to install CocoaPods dependencies for iOS project, which is required by this template

### ISSUE THREAD

**Issue by lancejpollard** [facebook/react-native#30718]
I posted in detail what the bug is I got at [SO](https://stackoverflow.com/questions/65659473/error-failed-to-install-cocoapods-dependencies-for-ios-project-which-is-requir?noredirect=1#comment116089557_65659473).

I am getting this when trying to install React Native for MacOS.

    $ npx react-native init myproject
    ld: warning: dylib (/usr/local/opt/llvm/lib/libc++.dylib) was built for newer macOS version (10.15) than being linked (10.13)
    ld: warning: dylib (/usr/local/opt/llvm/lib/libunwind.dylib) was built for newer macOS version (10.15) than being linked (10.13)
    ld: warning: dylib (/usr/local/opt/llvm/lib/libunwind.dylib) was built for newer macOS version (10.15) than being linked (10.13)
    ld: warning: dylib (/usr/local/opt/llvm/lib/libc++.dylib) was built for newer macOS version (10.15) than being linked (10.13)
    ld: warning: dylib (/usr/local/opt/llvm/lib/libunwind.dylib) was built for newer macOS version (10.15) than being linked (10.13)
    ld: warning: dylib (/usr/local/opt/llvm/lib/libunwind.dylib) was built for newer macOS version (10.15) than being linked (10.13)
    ...
    ✔ Downloading template
    ✔ Copying template
    ✔ Processing template
    ✖ Installing CocoaPods dependencies (this may take a few minutes)
    ✖ Installing CocoaPods dependencies (this may take a few minutes)
    error Error: Failed to install CocoaPods dependencies for iOS project, which is required by this template.
    Please try again manually: "cd ./myproject/ios && pod install".
    CocoaPods documentation: https://cocoapods.org/
    $ cd ./myproject/ios && pod install
    Analyzing dependencies
    Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
    Fetching podspec for `Folly` from `../node_modules/react-native/third-party-podspecs/Folly.podspec`
    Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
    Downloading dependencies
    Installing CocoaAsyncSocket (7.6.5)
    Installing CocoaLibEvent (1.0.0)
    Installing DoubleConversion (1.1.6)
    Installing FBLazyVector (0.63.4)
    Installing FBReactNativeSpec (0.63.4)
    Installing Flipper (0.54.0)
    Installing Flipper-DoubleConversion (1.1.7)
    Installing Flipper-Folly (2.3.0)
    Installing Flipper-Glog (0.3.6)
    [!] /bin/bash -c
    set -e
    #!/bin/bash
    # Copyright (c) Facebook, Inc. and its affiliates.
    #
    # This source code is licensed under the MIT license found in the
    # LICENSE file in the root directory of this source tree.

    set -e

    PLATFORM_NAME="${PLATFORM_NAME:-iphoneos}"
    CURRENT_ARCH="${CURRENT_ARCH}"

    if [ -z "$CURRENT_ARCH" ] || [ "$CURRENT_ARCH" == "undefined_arch" ]; then
        # Xcode 10 beta sets CURRENT_ARCH to "undefined_arch", this leads to incorrect linker arg.
        # it's better to rely on platform name as fallback because architecture differs between simulator and device

        if [[ "$PLATFORM_NAME" == *"simulator"* ]]; then
            CURRENT_ARCH="x86_64"
        else
            CURRENT_ARCH="armv7"
        fi
    fi

    export CC="$(xcrun -find -sdk $PLATFORM_NAME cc) -arch $CURRENT_ARCH -isysroot $(xcrun -sdk $PLATFORM_NAME --show-sdk-path)"
    export CXX="$CC"

    # Remove automake symlink if it exists
    if [ -h "test-driver" ]; then
        rm test-driver
    fi

    ./configure --host arm-apple-darwin

    # Fix build for tvOS
    cat << EOF >> src/config.h
    /* Add in so we have Apple Target Conditionals */
    #ifdef __APPLE__
    #include <TargetConditionals.h>
    #include <Availability.h>
    #endif
    /* Special configuration for AppleTVOS */
    #if TARGET_OS_TV
    #undef HAVE_SYSCALL_H
    #undef HAVE_SYS_SYSCALL_H
    #undef OS_MACOSX
    #endif
    /* Special configuration for ucontext */
    #undef HAVE_UCONTEXT_H
    #undef PC_FROM_UCONTEXT
    #if defined(__x86_64__)
    #define PC_FROM_UCONTEXT uc_mcontext->__ss.__rip
    #elif defined(__i386__)
    #define PC_FROM_UCONTEXT uc_mcontext->__ss.__eip
    #endif
    EOF

    # Prepare exported header include
    EXPORTED_INCLUDE_DIR="exported/glog"
    mkdir -p exported/glog
    cp -f src/glog/log_severity.h "$EXPORTED_INCLUDE_DIR/"
    cp -f src/glog/logging.h "$EXPORTED_INCLUDE_DIR/"
    cp -f src/glog/raw_logging.h "$EXPORTED_INCLUDE_DIR/"
    cp -f src/glog/stl_logging.h "$EXPORTED_INCLUDE_DIR/"
    cp -f src/glog/vlog_is_on.h "$EXPORTED_INCLUDE_DIR/"

    checking for a BSD-compatible install... /usr/bin/install -c
    checking whether build environment is sane... yes
    checking for arm-apple-darwin-strip... no
    checking for strip... strip
    checking for a thread-safe mkdir -p... ./install-sh -c -d
    checking for gawk... no
    checking for mawk... no
    checking for nawk... no
    checking for awk... awk
    checking whether make sets $(MAKE)... yes
    checking whether make supports nested variables... yes
    checking for arm-apple-darwin-gcc... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -arch armv7 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.3.sdk
    checking whether the C compiler works... no
    /Users/lancepollard/Library/Caches/CocoaPods/Pods/Release/Flipper-Glog/0.3.6-1dfd6/missing: Unknown `--is-lightweight' option
    Try `/Users/lancepollard/Library/Caches/CocoaPods/Pods/Release/Flipper-Glog/0.3.6-1dfd6/missing --help' for more information
    configure: WARNING: 'missing' script is too old or missing
    configure: error: in `/Users/lancepollard/Library/Caches/CocoaPods/Pods/Release/Flipper-Glog/0.3.6-1dfd6':
    configure: error: C compiler cannot create executables
    See `config.log' for more details

A snippet from `config.log` says:

    clang: error: argument to '-V' is missing (expected 1 value)
    clang: error: no input files
    configure:3685: $? = 1
    configure:3674: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -arch armv7 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.3.sdk -qversion >&5
    clang: error: unknown argument '-qversion'; did you mean '--version'?
    clang: error: no input files
    configure:3685: $? = 1
    configure:3705: checking whether the C compiler works
    configure:3727: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -arch armv7 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.3.sdk  -I/usr/local/opt/llvm/include -L/usr/local/opt/llvm/lib conftest.c  >&5
    ld: in '/usr/local/opt/llvm/lib/libunwind.dylib', building for iOS-armv7 but attempting to link with file built for macOS-x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    configure:3731: $? = 1
    configure:3769: result: no
    configure: failed program was:
    ...
    configure: exit 77

My Mac version is Catalina 10.15.7 (19H2). XCode is version 12.

[![enter image description here][1]][1]

I tried everything from https://stackoverflow.com/questions/58934022/react-native-error-failed-to-install-cocoapods-dependencies-for-ios-project-w, but nothing worked. I invoked `brew install cocoapods` as well.

Any ideas how to get past this? Could it be something to do with the fact that I have a `node_modules` folder higher up in the directory structure (above where I am running the commands)? I don't know what this error means.

Here is also output from the `missing` command:

    $ /Users/lancepollard/Library/Caches/CocoaPods/Pods/Release/Flipper-Glog/0.3.6-1dfd6/missing --help
    /Users/lancepollard/Library/Caches/CocoaPods/Pods/Release/Flipper-Glog/0.3.6-1dfd6/missing [OPTION]... PROGRAM [ARGUMENT]...

    Handle `PROGRAM [ARGUMENT]...' for when PROGRAM is missing, or return an
    error status if there is no known handling for PROGRAM.

    Options:
      -h, --help      display this help and exit
      -v, --version   output version information and exit
      --run           try to run the given command, and emulate it if it fails

    Supported PROGRAM values:
      aclocal      touch file `aclocal.m4'
      autoconf     touch file `configure'
      autoheader   touch file `config.h.in'
      autom4te     touch the output file, or create a stub one
      automake     touch all `Makefile.in' files
      bison        create `y.tab.[ch]', if possible, from existing .[ch]
      flex         create `lex.yy.c', if possible, from existing .c
      help2man     touch the output file
      lex          create `lex.yy.c', if possible, from existing .c
      makeinfo     touch the output file
      tar          try tar, gnutar, gtar, then tar without non-portable flags
      yacc         create `y.tab.[ch]', if possible, from existing .[ch]

    Send bug reports to <bug-automake@gnu.org>.

  [1]: https://i.stack.imgur.com/jiHi0.png

**Comment by lancejpollard** [comment]
```System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i5-1030NG7 CPU @ 1.10GHz
    Memory: 611.49 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.3.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.5 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 12.3/12C33 - /usr/bin/xcodebuild
  Languages:
    Java: 14.0.1 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found```

**Comment by xjord** [comment]
@lancejpollard did you manage to solve this? I'm having the some issue and can't find anything online

**Comment by lancejpollard** [comment]
@xjord not sure if you found it already but it was because of some compiler flags left in some random file, it's in here in some thread somewhere I just don't remember where! Some LLVM flags.

**Comment by lancejpollard** [comment]
https://stackoverflow.com/a/65660622/169992

**Comment by xjord** [comment]
> @xjord not sure if you found it already but it was because of some compiler flags left in some random file, it's in here in some thread somewhere I just don't remember where! Some LLVM flags.

Thanks @lancejpollard, I was able to fix it with `git config --global core.autocrlf false`. I found out that git config core.autocrlf  should be set to false otherwise git checkout will often try to turn LF line endings into CRLF, which can easily break fragile files.

**Comment by miidx** [comment]
This error happened to me as well. It was because of old CocoaPods version. I used version 1.8.0. After upgrading it to 1.10.1, the error was gone

**Comment by naishe** [comment]
> This error happened to me as well. It was because of old CocoaPods version. I used version 1.8.0. After upgrading it to 1.10.1, the error was gone

I can confirm that @miidx solution works.

On OS X, I updated with 
```bash
sudo gem install cocoapods
```

Then ran `pod install`, which threw this error:

```bash
$ pod install
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `RCT-Folly` from `../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
[!] CocoaPods could not find compatible versions for pod "FlipperKit/FlipperKitHighlightOverlay":
  In Podfile:
    FlipperKit/FlipperKitHighlightOverlay (~> 0.75.1)

None of your spec sources contain a spec satisfying the dependency: `FlipperKit/FlipperKitHighlightOverlay (~> 0.75.1)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```

Which got resolved by updating pod repo

```bash
$ pod repo update
Updating spec repo `trunk`
```

**Comment by joaolfr** [comment]
`brew install cocoapods`

worked for me like a charm after try every possible solution, I have a M1 2020, hope it helps

**Comment by asilolcu** [comment]
> `brew install cocoapods`
> 
> worked for me like a charm after try every possible solution, I have a M1 2020, hope it helps

Thank you, installing with brew worked for me too on my M1.

**Comment by joaolfr** [comment]
> > `brew install cocoapods`
> > worked for me like a charm after try every possible solution, I have a M1 2020, hope it helps
> 
> Thank you, installing with brew worked for me too on my M1.

After this issue I have a arm4 problem when run npx react-native run-ios. 

Solved adding arm64 in excluded architectures of the project and pod in Xcode build settings.

**Comment by Ponevejski** [comment]
> > > `brew install cocoapods`
> > > worked for me like a charm after try every possible solution, I have a M1 2020, hope it helps
> > 
> > 
> > Thank you, installing with brew worked for me too on my M1.
> 
> After this issue I have a arm4 problem when run npx react-native run-ios.
> 
> Solved adding arm64 in excluded architectures of the project and pod in Xcode build settings.

Hello! Could you please describe how you did it? ( i'm new to rn )

**Comment by joaolfr** [comment]
> > > > `brew install cocoapods`
> > > > worked for me like a charm after try every possible solution, I have a M1 2020, hope it helps
> > > 
> > > 
> > > Thank you, installing with brew worked for me too on my M1.
> > 
> > 
> > After this issue I have a arm4 problem when run npx react-native run-ios.
> > Solved adding arm64 in excluded architectures of the project and pod in Xcode build settings.
> 
> Hello! Could you please describe how you did it? ( i'm new to rn )

I followed this instructions: 
[https://stackoverflow.com/a/65399525/15801029](url)
If u still have problems, this answer is more complete
[https://khushwanttanwar.medium.com/xcode-12-compilation-errors-while-running-with-ios-14-simulators-5731c91326e9](url)

**Comment by mmmohajer** [comment]
> 
> 
> > > `brew install cocoapods`
> > > worked for me like a charm after try every possible solution, I have a M1 2020, hope it helps
> > 
> > 
> > Thank you, installing with brew worked for me too on my M1.
> 
> After this issue I have a arm4 problem when run npx react-native run-ios.
> 
> Solved adding arm64 in excluded architectures of the project and pod in Xcode build settings.

Thanks, this worked for me as well on my Mac Pro M1

**Comment by gazirahman** [comment]
> > @xjord not sure if you found it already but it was because of some compiler flags left in some random file, it's in here in some thread somewhere I just don't remember where! Some LLVM flags.
> 
> Thanks @lancejpollard, I was able to fix it with `git config --global core.autocrlf false`. I found out that git config core.autocrlf should be set to false otherwise git checkout will often try to turn LF line endings into CRLF, which can easily break fragile files.

This resolved my issue as well. Thanks so much!

**Comment by SGarcia710** [comment]
> `brew install cocoapods`
> 
> worked for me like a charm after try every possible solution, I have a M1 2020, hope it helps

Worked on M1 Pro 14"

**Comment by Sannnao** [comment]
> > @xjord not sure if you found it already but it was because of some compiler flags left in some random file, it's in here in some thread somewhere I just don't remember where! Some LLVM flags.
> 
> Thanks @lancejpollard, I was able to fix it with `git config --global core.autocrlf false`. I found out that git config core.autocrlf should be set to false otherwise git checkout will often try to turn LF line endings into CRLF, which can easily break fragile files.

Thanks! Fixed for me
