### ISSUE TITLE
Height and width in the documentation example does not produce the same absolute millimetre size across devices

### ISSUE THREAD

**Issue by jimothyhalpert7** [facebook/react-native#30716]
## Description
We're simply trying to get the same millimetre (or as close as possible) sized object, across different devices.

## React Native version:
0.63.3

## Steps To Reproduce
1. Open the Snack example at: https://reactnative.dev/docs/height-and-width on an
2. iPhone SE
3. Samsung Galaxy S8
4. iPad Pro (11-inch)

## Expected Results
Squares should be the exact same size in human millimetres, measured by a ruler and an eye.
The difference between the iPhone and iPad is half a centimetre.

## Snack, code example, screenshot, or link to a repository:
https://snack.expo.io/@jimothyhalpert7/height-and-width

Any workaround also welcome.

**Comment by jimothyhalpert7** [comment]
Version is 0.63.3, expo version 40
Not sure what other env variables are needed - it's a Snack from the example.

**Comment by brentvatne** [comment]
this is not something that react-native aims to solve for you out of the box. the unit used for "width" and "height" is "points", and there is no consistent conversion between points physical measurements like inches.

you can learn more about how this works by reading more about pixel density, i recommend this article https://medium.com/@peternowell/pixel-density-demystified-a4db63ba2922

**Comment by jimothyhalpert7** [comment]
@brentvatne makes sense, it's a difficult task from what I'm learning.

But then maybe the docs shouldn't have this line:

> Setting dimensions this way is common for components that should always render at exactly the same size, regardless of screen dimensions.

https://reactnative.dev/docs/height-and-width
