### ISSUE TITLE
com.facebook.react.common.JavascriptException: ReferenceError: Can't find variable: typeAnnotation

### ISSUE THREAD

**Issue by redencion** [facebook/react-native#30711]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Thanks for your help
After I got build apk without error runnig my emulator to check it out but it fail with emulator, it doesnt work. But it success when I build apk debug. 

## React Native version:
``
System:
    OS: Linux 4.19 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (4) x64 Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
    Memory: 299.07 MB / 11.64 GB
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 14.8.0 - ~/.nvm/versions/node/v14.8.0/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 6.14.7 - ~/.nvm/versions/node/v14.8.0/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 28.0.3, 29.0.0
      System Images: android-29 | Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
  Languages:
    Java: 11.0.9.1 - /usr/bin/javac
    Python: 3.7.3 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: ^4.9.0 => 4.13.1 
    react: 16.9.0 => 16.9.0 
    react-native: ^0.62.2 => 0.62.2 
``

## Steps To Reproduce

1. react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/build/intermediates/res/merged/release/ && rm -rf android/app/src/main/res/drawable-* && rm -rf android/app/src/main/res/raw/* && cd android && ./gradlew assembleRelease

2. get apk on android/app/build/outputs/apk/release 

## Expected Results
It should be working as fine as apk.debug but it is not.

## Snack, code example, screenshot, or link to a repository:
``com.facebook.react.common.JavascriptException: ReferenceError: Can't find variable: typeAnnotation, stack:
    <unknown>@1478:17088
    v@2:1473
    <unknown>@1477:425
    v@2:1473
    <unknown>@1476:339
    v@2:1473
    <unknown>@1469:6338
    v@2:1473
    <unknown>@1468:122
    v@2:1473
    <unknown>@1443:700
    v@2:1473
    <unknown>@1088:278
    v@2:1473
    <unknown>@591:251
    v@2:1473
    <unknown>@406:297
    v@2:1473
    <unknown>@6:57
    v@2:1473
    d@2:875
    global code@2026:3
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:79)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:214)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:919) ``

<a href="https://imgur.com/ebDS9mf"><img src="https://i.imgur.com/ebDS9mf.png" title="source: imgur.com" /></a>

  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },

  "dependencies": {
    "@react-native-community/async-storage": "^1.8.1",
    "@react-native-community/cameraroll": "^1.8.1",
    "@react-native-community/cli": "^4.9.0",
    "@react-native-community/cli-platform-ios": "^4.9.0",
    "@react-native-community/geolocation": "^2.0.2",
    "@react-native-community/image-editor": "^2.3.0",
    "@react-native-community/masked-view": "^0.1.7",
    "@react-native-community/viewpager": "^3.3.0",
    "@react-native-firebase/app": "^8.2.0",
    "@react-native-firebase/auth": "^8.2.0",
    "@react-native-firebase/firestore": "^7.4.3",
    "@react-native-firebase/messaging": "^7.6.1",
    "@react-native-firebase/storage": "^7.3.1",
    "axios": "^0.19.2",
    "d3-scale": "^3.2.2",
    "d3-shape": "^2.0.0",
    "i18n-js": "^3.5.1",
    "immutable": "^4.0.0-rc.12",
    "metro": "^0.59.0",
    "prop-types": "^15.7.2",
    "react": "16.9.0",
    "react-native": "^0.62.2",
    "react-native-add-calendar-event": "^3.0.1",
    "react-native-apple-sign-in": "git+https://github.com/SystangoTechnologies/react-native-apple-sign-in.git",
    "react-native-autocomplete-input": "^4.2.0",
    "react-native-calendar-events": "^1.7.3",
    "react-native-camera": "^3.21.0",
    "react-native-card-flip": "^1.0.6",
    "react-native-contacts": "^5.1.0",
    "react-native-customized-image-picker": "^0.1.11",
    "react-native-datepicker": "^1.7.2",
    "react-native-device-info": "^5.5.3",
    "react-native-document-picker": "^3.3.2",
    "react-native-elements": "^1.2.7",
    "react-native-fast-image": "^8.1.5",
    "react-native-file-picker": "0.0.19",
    "react-native-fs": "^2.16.6",
    "react-native-geocoder": "^0.5.0",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-gifted-chat": "^0.16.3",
    "react-native-google-places-autocomplete": "^1.4.2",
    "react-native-google-signin": "^2.1.1",
    "react-native-image-picker": "git+https://github.com/zipline/react-native-image-picker.git",
    "react-native-image-resizer": "^1.2.0",
    "react-native-image-rotate": "^2.1.0",
    "react-native-languages": "^3.0.2",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-local-authenticate": "^1.0.1",
    "react-native-localize": "^1.3.4",
    "react-native-maps": "^0.26.1",
    "react-native-orientation-locker": "^1.1.8",
    "react-native-paper": "^4.0.1",
    "react-native-read-more-text": "^1.1.2",
    "react-native-reanimated": "^1.7.1",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-screens": "^2.4.0",
    "react-native-share": "^3.7.0",
    "react-native-simple-dialogs": "^1.2.1",
    "react-native-svg": "^12.0.3",
    "react-native-svg-charts": "^5.4.0",
    "react-native-swipe-list-view": "^2.5.0",
    "react-native-swiper": "^1.6.0-nightly.5",
    "react-native-thumbnail": "git+https://github.com/phuochau/react-native-thumbnail.git",
    "react-native-vector-icons": "^6.6.0",
    "react-native-video": "^4.4.5",
    "react-navigation": "^4.2.2",
    "react-navigation-drawer": "^2.4.9",
    "react-navigation-stack": "^2.3.9",
    "react-navigation-tabs": "^2.8.9",
    "react-redux": "^7.2.0",
    "redux": "^4.0.5",
    "redux-logger": "^3.0.6",
    "redux-persist": "^6.0.0",
    "redux-saga": "^1.1.3",
    "url": "^0.11.0"
  },
  "devDependencies": {
    "@babel/core": "7.8.7",
    "@babel/runtime": "7.8.7",
    "@react-native-community/eslint-config": "0.0.5",
    "babel-jest": "24.9.0",
    "eslint": "6.8.0",
    "jest": "24.9.0",
    "metro-react-native-babel-preset": "0.56.4",
    "react-test-renderer": "16.9.0"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Comment by redencion** [comment]
thanks for your help, I can`t show you source code because of copyrigth. I would like if this is enought to check error.

**Comment by safaiyeh** [comment]
@redencion Could you reproduce this issue on a brand new template?

**Comment by redencion** [comment]
thanks for you help @safaiyeh. I don't get it. What do you mean with brand a new template?

**Comment by chrisglein** [comment]
> thanks for you help @safaiyeh. I don't get it. What do you mean with brand a new template?

I think he means like with a brand new app (just the default app template). Note the bot comment above with some helpful links:

> ⚠️	Missing Reproducible Example
> ℹ️	It looks like your issue is missing a reproducible example. Please provide a [Snack](https://snack.expo.io) or a repository that demonstrates the issue you are reporting in a [minimal, complete, and reproducible](https://stackoverflow.com/help/minimal-reproducible-example) manner.
