### ISSUE TITLE
Secure WebSocket not working on iOS

### ISSUE THREAD

**Issue by antoinerousseau** [facebook/react-native#30727]
## Description
We built a chat feature using [WebSockets](https://reactnative.dev/docs/network#websocket-support).
The WebSocket server is powered by [Ratchet](http://socketo.me/) 0.4.3.
When using a `new WebSocket("ws://mywebsite.com")` it all works well on both Android an iOS.
Now the server has a Nginx proxy config to accept incoming SSL connections, and redirect the path `/wss` to the WebSocket server.
Which means I write `new WebSocket("wss://mywebsite.com/wss")` and it works, both on Android and in Chrome.
But on iOS, it immediately closes with the code `1001` and the message `Stream end encountered`.
The problem happens in both development and production builds.

Also, the [websocat](https://github.com/vi/websocat) utility has troubles connecting, too:

```
$ websocat wss://mywebsite.com/wss -v
[INFO  websocat::lints] Auto-inserting the line mode
[INFO  websocat::ws_client_peer] get_ws_client_peer
websocat: WebSocketError: WebSocket protocol error
websocat: error running
```

The server supports TLS 1.2 and 1.3, but not 1.1 not 1.0.

I get a little more info in Xcode debug, but not much:

```
2021-01-08 13:40:23.450766+0100 MyApp[11682:225729] [connection] nw_socket_handle_socket_event [C8.1:1] Socket SO_ERROR [61: Connection refused]
2021-01-08 13:40:23.458355+0100 MyApp[11682:225729] [connection] nw_socket_handle_socket_event [C8.2:1] Socket SO_ERROR [61: Connection refused]
2021-01-08 13:40:23.459156+0100 MyApp[11682:225798] [connection] nw_connection_get_connected_socket [C8] Client called nw_connection_get_connected_socket on unconnected nw_connection
2021-01-08 13:41:08.494458+0100 MyApp[11682:224261] [native] SocketRocket: In debug mode.  Allowing connection to any root cert
```

## React Native version:
```
System:
    OS: macOS 11.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 737.04 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.1 - ~/.nvm/versions/node/v14.15.1/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 27.0.3, 28.0.3, 29.0.1, 29.0.2
      System Images: android-27 | Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 12.3/12C33 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_202 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.63.4 => 0.63.4
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Bootstrap a new RN app
2. Bootstrap a WebSocket server accessible behind an Nginx proxy (let me know if I should share the config)
3. Connect to it in your JavaScript code with:

```js
const ws = new WebSocket("wss://yourserver.com");
ws.onopen = () => {
  console.log("WS open")
}
ws.onclose = (ev) => {
  console.log("WS closed with code", ev.code, ev.reason)
}
```

## Expected Results
```
WS open
```

## Actual Results
```
WS closed with code 1001 Stream end encountered
```

## Snack, code example, screenshot, or link to a repository:
The server is private so I can't

**Comment by chrisglein** [comment]
Does the exact same code, but pointed at another endpoint, show the same issue? As in can we narrow this down to something in the config that's affecting iOS WebSockets all up or a combination of iOS WebSocket plus that endpoint?

I don't have the answer to this, but it does seem like a very relevant question:
> The server supports TLS 1.2 and 1.3, but not 1.1 not 1.0.
Could that be the issue? How can I have more debugging infos?

I don't know what iOS native API RN's WebSocket is wrapping, but the other thing to check would be if that API (whatever it is) worked without RN in the picture against that endpoint.

**Comment by antoinerousseau** [comment]
Sorry I should have added that I tried with `wss://echo.websocket.org/` and it works well, so it's really specific to my client's endpoint...

Also I set `NSExceptionMinimumTLSVersion` to `TLSv1.2` in my `Info.plist`,  although it seems to be the default value.
I also tried with `NSExceptionRequiresForwardSecrecy` set to NO.

Thanks for the help anyway!

**Comment by antoinerousseau** [comment]
Ok, we finally resolved it, the client informed us that incoming connections without a `User-Agent` header were being blocked (I didn't realize default RN WebSocket didn't set a UA)!

So I added the header like this:

```js
const ws = new WebSocket(WEBSOCKET_URL, null, {
  headers: {
    "User-Agent": "react-native",
  },
})
```

And it works! 🥳 

Also I had to send a ping every few seconds otherwise Nginx would close the connection, fyi.
