### ISSUE TITLE
Android activity started from RN closes when application reopened by clicking the application icon

### ISSUE THREAD

**Issue by Odrin** [facebook/react-native#30726]
## Description
If RN application were minimized by Android "Home" button and reopened by clicking the application icon on home screen/app list, then any previously started activity (started from RN module) is closed and application restarts from `MainActivity`. At the same time, reopening application from "Recent applications" screen works as expected.

## React Native version:
```
System:
  OS: Windows 8.1 6.3.9600
  CPU: (8) x64 Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz
  Memory: 2.93 GB / 7.89 GB
Binaries:
  Node: 12.18.3 - E:\Soft\NodeJS\node.EXE
  Yarn: Not Found
  npm: 6.14.8 - E:\Soft\NodeJS\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK:
    API Levels: 10, 19, 20, 21, 23, 25, 28, 29
    Build Tools: 20.0.0, 21.1.2, 23.0.1, 23.0.2, 23.0.3, 28.0.3, 29.0.2, 30.0.2
    System Images: android-19 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64
    Android NDK: Not Found
  Windows SDK: Not Found
IDEs:
  Android Studio: Not Found
  Visual Studio: 16.0.28803.202 (Visual Studio Community�2019)
Languages:
  Java: 1.8.0_121 - C:\Program Files\Java\jdk1.8.0_121\bin\javac.EXE
  Python: Not Found
npmPackages:
  @react-native-community/cli: Not Found
  react: 16.13.1 => 16.13.1
  react-native: 0.63.3 => 0.63.3
  react-native-windows: Not Found
npmGlobalPackages:
  *react-native*: Not Found
```

## Steps To Reproduce
1. Start RN application by `react-native run-android` or by installing release apk
2. Start Android activity (`TestActivity`) from RN module
2. Press Android "Home" button
3. Click the application icon on home screen/app list
4. Application starts from `MainActivity`, `TestActivity` is closed.

## Expected Results
Started activity is shown, application resumes to work exactly the same way as if it were opened from "Recent applications" screen.

## Snack, code example, screenshot, or link to a repository:
https://github.com/Odrin/RN-ActivityTestProject
https://user-images.githubusercontent.com/1961250/104294101-d7c66900-54cf-11eb-806b-15e678bb25d6.mp4

**Comment by chrisglein** [comment]
Not at all an Android expert here, but have you checked any of the other native activation/entry callbacks to see what's getting re-invoked when you re-launch the app? My uniformed guess is that the lifetime of that Activity object is tied to things that are getting unloaded/reloaded, but I don't know what's expected to be reused.

**Comment by dulmandakh** [comment]
This is expected and default behavior of Android, when you tap on app icon Android will restart the default activity or MainActivity. It was same with RN a while ago, then we changed Activity launchMode to singleTask.

I'm closing the issue because it's not a RN issue, but Android specifically your activity. Please refer to Activity launchMode documentation.
