### ISSUE TITLE
Undecipherable Hermes Inspector crash

### ISSUE THREAD

**Issue by gilbertl** [facebook/react-native#30738]
We're receiving crash reports related to Hermes; we can't understand the stack trace and need some help.

## Description
Here's the first few lines of the crash. Attached is the full stack trace.

`facebook::hermes::inspector::Inspector::logOnExecutor(facebook::hermes::inspector::ConsoleMessageInfo, std::__1::shared_ptr<folly::Promise<folly::Unit> >) (Inspector.cpp:641)
11   Shuffle                                  0x102629344     void folly::detail::function::FunctionTraits<void ()>::callSmall<facebook::hermes::inspector::Inspector::logMessage(facebook::hermes::inspector::ConsoleMessageInfo)::$_7>(folly::detail::function::Data&) (Function.h:392)`

[Crash#2761.txt](https://github.com/facebook/react-native/files/5813297/Crash.2761.txt)

## React Native version:
0.64-rc2

## Steps To Reproduce
Based on our data, the crash is happening in various parts of the app, with no obvious repeatable steps.

## Expected Results
No Crash

## Snack, code example, screenshot, or link to a repository:
N/A

**Comment by safaiyeh** [comment]
@gilbertl thanks for the issue - it is a bit hard to decipher what is going on. Escalating to the issue manager team to see the best direction for this.
