### ISSUE TITLE
Default .gitignore generated by react-native init has overly aggressive excludes for Android/IntelliJ project files

### ISSUE THREAD

**Issue by chrisbartley** [facebook/react-native#30735]
## Description
Generating a new project with the `npx react-native init` command creates a `.gitignore` file which excludes the following file types under the **Android/IntelliJ** heading

```
# Android/IntelliJ
#
build/
.idea
.gradle
local.properties
*.iml
```

Excluding the entire `.idea` directory is incorrect.  In some cases, excluding all `.iml` files is incorrect.  See https://intellij-support.jetbrains.com/hc/en-us/articles/206544839-How-to-manage-projects-under-Version-Control-Systems

## React Native version:
```
$ npx react-native info
info Fetching system and libraries information...
System:
    OS: macOS 11.1
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
    Memory: 113.26 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.15.3 - ~/n/bin/node
    Yarn: Not Found
    npm: 6.14.11 - ~/n/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.9.1 - /Users/chris/.rvm/rubies/ruby-2.7.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.3, 30.0.3
      System Images: android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.3/12C33 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_275 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.
1. Generate a new project with `npx react-native init`, for example `npx react-native init ReactNativeHello`
2. Look at the generated `.gitnore` file

## Expected Results
Should only exclude files as recommended by JetBrains at: https://intellij-support.jetbrains.com/hc/en-us/articles/206544839-How-to-manage-projects-under-Version-Control-Systems

For example, JetBrains says:

> Here is what you need to share:
> * All the files under the `.idea` directory in the project root except the 
> `workspace.xml`, `usage.statistics.xml`, and `tasks.xml` files and the shelf 
> directory which store user-specific settings
> * All the .iml module files that can be located in different module directories (applies to IntelliJ IDEA)

The current generated `.gitnore` excludes the entire `.idea` directory and `.iml` files, both of which are incorrect according to the above.  

Also, for anyone choosing the legacy IntelliJ project format (.ipr/.iml/.iws files), then excluding `.iml` is incorrect:

> Share the project `.ipr` file and all the `.iml` module files, don't share the `.iws` file as it stores user specific settings

**Comment by safaiyeh** [comment]
@chrisbartley This is a very opinionated issue, it depends on the community to decided the best route. I would propose to start a thread in discussions & proposals https://github.com/react-native-community/discussions-and-proposals

Closing for now until a decision is made in the proposals.

**Comment by chrisbartley** [comment]
Opinionated?  So your opinion is that JetBrains' recommendation about their own product is wrong?

**Comment by chrisbartley** [comment]
FWIW, this is still wrong in React Native v0.66.4.

**Comment by cortinico** [comment]
@chrisbartley You're right. We should not exclude all the `.idea` directory completely as there are some files that are project specific and can be shared. I would be fine having something like this: https://github.com/cortinico/kotlin-android-template/blob/7713a023a38a2f8a967b5d97066e2a40a13adbc3/.gitignore#L44-L54

Don't you mind sending a PRs to update the `.gitignore` in the template and I can bring this up internally?

**Comment by chrisbartley** [comment]
I'd favor just going with JetBrains' suggestions:

https://intellij-support.jetbrains.com/hc/en-us/articles/206544839-How-to-manage-projects-under-Version-Control-Systems

That page also links to a sample .gitignore as a starting point:

https://github.com/github/gitignore/blob/master/Global/JetBrains.gitignore

My main issue with React Native's current .gitignore is  that it excludes .iml files. Which, for the older .ipr/.iml/.iws project format, is simply wrong.  For the .idea directory-based project settings format, excluding .iml files is only a "may want to", and that's for Gradle or Maven based projects.

**Comment by cortinico** [comment]
> For the .idea directory-based project settings format, excluding .iml files is only a "may want to", and that's for Gradle or Maven based projects

Following up here, we intentionally want to exclude `.iml` files as this is a Gradle based project and those files will be recreated by the auto-import (that's also what's mentioned in the JB documentation).

Why do you need to share them instead? If this is specific to your use case, maybe it makes sense that you edit the `.gitignore` for your specific project.

**Comment by chrisbartley** [comment]
The Android portion is gradle-based, but the project itself very much is not.  If you want to exclude `.iml` files for everything under the `android` directory, then fine, but I don't understand the rationale for doing so for the entire generated React Native project.

Where are the `.iml` files you're wanting to exclude anyway? My project contains zero under  the `android` directory, and zero in general, save for the one IntelliJ IDEA created for me (i.e. intentionally created by me, not a gradle artifact) when I brought the project into IntelliJ IDEA.

**Comment by cortinico** [comment]
> Where are the `.iml` files you're wanting to exclude anyway?

I'm talking about the `.iml` files inside the `.idea` folder:
```
.idea/modules
├── ReactAndroid
│   └── react-native-github.ReactAndroid.iml
├── packages
│   ├── react-native-codegen
│   │   ├── android
│   │   │   └── react-native-github.packages.react-native-codegen.android.iml
│   │   └── react-native-github.packages.react-native-codegen.iml
│   ├── react-native-github.packages.iml
│   ├── react-native-gradle-plugin
│   │   └── react-native-gradle-plugin.iml
│   └── rn-tester
│       ├── android
│       │   ├── app
│       │   │   └── react-native-github.packages.rn-tester.android.app.iml
│       │   └── react-native-github.packages.rn-tester.android.iml
│       └── react-native-github.packages.rn-tester.iml
└── react-native-github.iml
```

**Comment by chrisbartley** [comment]
Not everyone uses the `.idea` format.  The .ipr/.iml/.iws format is older, but still 100% valud.  If you want to exclude just .iml files under the .idea directory, then fine, but write the .gitignore accordingly.  Don't just blindly exclude .iml.

**Comment by cortinico** [comment]
> but write the .gitignore accordingly. Don't just blindly exclude .iml.

Don't you mind sending a PR to update it?
