### ISSUE TITLE
Remote Debugger not working in RN 0.63.2

### ISSUE THREAD

**Issue by davidsalib** [facebook/react-native#30730]
## Description
When on RN 0.61, I could run the app in debug and use the debugger and reload the code. After upgrading to 0.63, the app builds, but it doesn't connect to the debugger to update the code when it changes. When I open the developer menu and press "debug", I get an error about the IP (see attached). However, if I switch back to 0.61, there is no IP error. Not sure why upgrading the RN version is affecting the debugger's connection.

Note, I can build a release version of the app and everything works fine.

## React Native version:
System:
    OS: macOS 10.15.5
    CPU: (4) x64 Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz
    Memory: 1001.80 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.18.2 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.5 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 12.3/12C33 - /usr/bin/xcodebuild
  Languages:
    Java: 14.0.1 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Open app with React Native 0.62
2. Press Debug in the developer menu

## Expected Results
I expect to see the JS debugger and see app changes based on code changes. This works fine with 0.61, but when I get to 0.63, it doesn't work.

![image](https://user-images.githubusercontent.com/10209934/104420137-6c1fe280-5547-11eb-992a-cffe64b7c216.png)

**Comment by safaiyeh** [comment]
Seems to be a duplicate of these issues: 

https://github.com/facebook/react-native/issues/14186
https://github.com/facebook/react-native/issues/7685

They seem to allude to checking your network - let me know if these issues do not help.

**Comment by davidsalib** [comment]
Thanks for those links @safaiyeh - I did look at the network. 
The odd part is, with no network changes, if I just switch back to 0.61, the debugger works fine. 
Then I switch to 0.63.2, and it stops working. Same wifi, no network changes at all.

**Comment by iqqmuT** [comment]
@davidsalib Which debugger and version of it are you using?

**Comment by safaiyeh** [comment]
@davidaurelio could you verify this on the latest React Native version and provide a repro of it happening thanks!
