### ISSUE TITLE
changing focus on inputs in a scrollview scrolls the previous input to the top of the screen

### ISSUE THREAD

**Issue by megantaylor** [facebook/react-native#30736]
## Description

this bug only occurs on iOS devices (have tested on iPhoneX and iPhoneSE (2nd gen)) and has not been reproducible in simulators

problem: in a scrollview with lots of text inputs, changing focus on inputs scrolls the previous input to the top of the screen

i have tried this with and without a KeyboardAvoidingView and it doesn't appear to make a difference

## React Native version:

System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Memory: 54.23 MB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.10.1 - /var/folders/1d/q81r_4ns49s0ydl_w32ygtp00000gn/T/yarn--1610578038462-0.5607966698572866/node
    Yarn: 1.22.5 - /var/folders/1d/q81r_4ns49s0ydl_w32ygtp00000gn/T/yarn--1610578038462-0.5607966698572866/yarn
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.3/12C33 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: ~0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce

1. tap the first input
2. scroll down so that input is no longer visible 
3. tap some other input

## Expected Results

input is focused, no scrolling occurs

## Actual Results

scrollview seems to scroll itself so that initially focused input is perfectly aligned to the top of the view

## Snack, code example, screenshot, or link to a repository:

https://snack.expo.io/@reachvote/rebellious-yogurt

**Comment by safaiyeh** [comment]
@megantaylor thank you for the issue! Appreciate the example - definitely seems odd that this only happens in release. Accepting it as a bug

**Comment by spaceye** [comment]
It would be great to be able to completely disable this functionality. Say, when custom scroll position is computed in response to a TextInput receiving focus. Typical scenario would include a ScrollView with inputs and a floating button atop it. The default scroll would take place but the button would be obscuring the underlying input.

**Comment by cokepizza** [comment]
same here, I have a touchableWithoutFeedback in a scrollView and a lot of views and textInputs in it to delete the focus of the textInput when the background is pressed. However, when I scroll down and touch it, it scrolls with the previously selected textInput. This is a very strange behavior. The conditions under which the problem situation occurs are:

1. If you touch multiple times within a fixed screen without scrolling, there is no problem.
2. If the scroll moves even a little after touching any textInput, the next touch scrolls up or down to the previously selected textInput. (If the next touch after scrolling is textInput, it does not occur. In the case of a view or touch button, abnormal behavior occurs identically)

**Comment by cokepizza** [comment]
While testing to solve this, I found interesting results. This bug does not occur when textInput is multiline=true. Maybe I could make a hack using a little tricky method, but since this is a fundamental problem with the textInput in the scrollView itself, I hope that this problem will be solved in the next version.

For reference), my RN version is 0.63.4 and my React version is 16.13.0, and I have confirmed that the same problem occurs in the latest version. And also, there is no problem in the simulator, and the problem only occurs when testing with the device.

**Comment by RavindraChherke** [comment]
+1

This is a really annoying bug. We planned to rebuild the app and chose react native. We have many long forms in the app and already spent last 2-3 days on this issue. Thankfully found this thread. Hopefully somebody can help on this.

```
"react": "17.0.1",
"react-native": "0.64.0",

```

**Comment by spaceye** [comment]
> This is a really annoying bug. We planned to rebuild the app and chose react native. We have many long forms in the app and already spent last 2-3 days on this issue. Thankfully found this thread. Hopefully somebody can help on this.

Keep references to your inputs, use `onFocus` to set currently active input by ref and implement your own scroll to it. And yes, you'd have to use the ugly `setTimeout` to set the focus again after the current bugged behaviour would try to set focus to the previously focused input. That's how I did it and it works just fine.

**Comment by RavindraChherke** [comment]
> > This is a really annoying bug. We planned to rebuild the app and chose react native. We have many long forms in the app and already spent last 2-3 days on this issue. Thankfully found this thread. Hopefully somebody can help on this.
> 
> Keep references to your inputs, use `onFocus` to set currently active input by ref and implement your own scroll to it. And yes, you'd have to use the ugly `setTimeout` to set the focus again after the current bugged behaviour would try to set focus to the previously focused input. That's how I did it and it works just fine.

Thanks You @spaceye for your suggestion. I am new to react native. I am going to try it but would it not cause flickering. Currently, I tap on first TextInput on top and then tap on last TextInput at the bottom. The ScrollView moves all the way back to first TextInput automatically. If I add this solution then scrollview would move to top automatically and then move back to bottom onFocus.

I tried `multiline=true` as suggested by @cokepizza and it works fine. I tried `scrollEnabled={false}` with multiline on TextInput then issue comes back. `multiline` will do the job for me. I don't see we would have a proper fix unit next release which may be in next 3 months.

**Comment by DesertStrom16** [comment]
@cokepizza Thank you, thank you, thank you. I too just spent the last 3 days fighting this random bug and was about to accept that I genuinely had no clue. You really saved my bacon man, huge props I mean it. For anyone reading, as of May 2021 this solution is still working. multiline={true} and scrollEnabled={true}. Like he said it is somewhat hacky but appears to be the only present solution for this bug.

**Comment by haujs** [comment]
Hi all. Any update for this issue? Thanks

**Comment by oneHamidreza** [comment]
+1

**Comment by ggchicote** [comment]
Hi everybody. Is there any update for this issue? I have the same problem using **tcomb-form-native** library within numerical inputs. I don't know how to avoid this behavior on iOS devices. Thanks!!

**Comment by beterfysiek** [comment]
same issue still

**Comment by richlewis14** [comment]
> > This is a really annoying bug. We planned to rebuild the app and chose react native. We have many long forms in the app and already spent last 2-3 days on this issue. Thankfully found this thread. Hopefully somebody can help on this.
> 
> Keep references to your inputs, use `onFocus` to set currently active input by ref and implement your own scroll to it. And yes, you'd have to use the ugly `setTimeout` to set the focus again after the current bugged behaviour would try to set focus to the previously focused input. That's how I did it and it works just fine.

Apologies if i have missed something, but where can i find the solution to this issue please?

**Comment by richlewis14** [comment]
> this

Are you setting multiLine={true} and scrollEnabled={true} on each of your form inputs for this to work?

**Comment by jimfoambox** [comment]
+1

**Comment by hungnm-kaopiz** [comment]
Here is my workaround
```
import { useEffect, useRef } from 'react'
import { Keyboard, Platform, ScrollView } from 'react-native'

export const useKeyboardAwareScroll = () => {
  const scrollViewRef = useRef<ScrollView>(null)
  const inputRefs = useRef<Map<string, any>>(new Map())

  useEffect(() => {
    if (Platform.OS !== 'ios') return

    const keyboardWillShow = Keyboard.addListener('keyboardWillShow', (e) => {
      setTimeout(() => {
        if (scrollViewRef.current) {
          scrollViewRef.current.scrollToEnd({ animated: true })
        }
      }, 100)
    })

    const keyboardWillHide = Keyboard.addListener('keyboardWillHide', () => {
      setTimeout(() => {
        if (scrollViewRef.current) {
          scrollViewRef.current.scrollTo({ y: 0, animated: true })
        }
      }, 100)
    })

    return () => {
      keyboardWillShow.remove()
      keyboardWillHide.remove()
    }
  }, [])

  return { scrollViewRef, inputRefs }
}
```
