### ISSUE TITLE
The Android APK does not display images

### ISSUE THREAD

**Issue by liuyunqiang** [facebook/react-native#30733]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
The Android APK does not display images
![截屏2021-01-13 下午5 04 22](https://user-images.githubusercontent.com/17231906/104430351-872f3880-55c1-11eb-9b97-11001accb299.png)

## React Native version:
  OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-4260U CPU @ 1.40GHz
    Memory: 25.53 MB / 4.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 15.5.1 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 7.3.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0. - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    Android SDK:
      API Levels: 21, 23, 24, 25, 26, 27, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.2/12B45b - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_92 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.3 => 0.63.3
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by GeronimoKTT** [comment]
Hey, can you try doing the following:

1. `rm -r node_modules ; cd android/app/ ; rm -r build ; cd ../.. ; yarn install ; npx react-native link`
2. Then run your usual `npx react-native run-android`

**Comment by chang-ke** [comment]
try add file:// prefix on local image path. it maybe helps you
