### ISSUE TITLE
[0.64.0-rc.2] Re-Focusing on TextInput Does Not Open Android's Soft Keyboard

### ISSUE THREAD

**Issue by McAJBen** [facebook/react-native#30746]
## Description
When a TextInput is in focus and Android's soft keyboard is closed, tapping on the TextInput should re-open the soft keyboard but currently it does not. This has been broken somewhere between 0.63.4 and 0.64.0-rc.2.

## React Native version:
System:
    OS: macOS 11.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 303.47 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.10 - ~/.nvm/versions/node/v12.16.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 21, 23, 26, 27, 28, 29, 30
      Build Tools: 27.0.0, 27.0.3, 28.0.3, 29.0.1, 29.0.2, 29.0.3, 30.0.0, 30.0.0, 30.0.1
      System Images: android-23 | Google APIs ARM EABI v7a, android-23 | Google APIs Intel x86 Atom, android-25 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.3/12C33 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_221 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.0-rc.2 => 0.64.0-rc.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Install a React-Native 0.64.0-rc.2 app with a TextInput on an Android device
2. Tap on the TextInput
3. (Android's soft keyboard should appear and the TextInput should be in focus)
4. Dismiss the Keyboard by pressing the down arrow at the bottom of the screen
5. (Android's soft keyboard should disappear and the TextInput should still be in focus)
6. Tap on the TextInput

## Expected Results
Android's soft keyboard should be brought up so the user can enter text into the TextInput.

## Actual Results
Nothing happens and the user can't type into the TextInput.

## Snack, code example, screenshot, or link to a repository:
```
function App() {
    return (
        <TextInput />
    );
}
```

**Comment by safaiyeh** [comment]
@McAJBen does this happen in release? I've had issues where the keyboard does not pop up in dev mode and I just force it open. Let me know

**Comment by McAJBen** [comment]
@safaiyeh This happens in both debug and release, although we first noticed it in release mode.

**Comment by safaiyeh** [comment]
@McAJBen thanks! Could you reference this issue on this thread: https://github.com/react-native-community/releases/issues/214

**Comment by mayconline** [comment]
Same problem here.

**Comment by fabriziobertoglio1987** [comment]
Do you still experience this issue? 

I have four years of experience maintaining facebook/react-native and I specialize in the Text and TextInput components. I currently have 58 [facebook/react-native PRs](https://github.com/facebook/react-native/pulls?q=is%3Apr+author%3Afabriziobertoglio1987+). 

If you still experience this issue, I will prepare a patched release with the fix.

Thanks a lot
