### ISSUE TITLE
iOS | RN 0.62.2 | The text in the Multiline TextInput starts "jerking" when moving the cursor over it with a long press on the spacebar

### ISSUE THREAD

**Issue by artyom4ek** [facebook/react-native#30748]
## Description
**On iOS devices**, if you add a lot of lines to a multi-line TextInput and then hold down the space bar and try to move the cursor to the desired point, the text starts jerking.

## React Native version:
RN: 0.62.2 (also reproducible in 0.63.3)
Tested on iPhone 12 pro max (14.3), iPad Pro 9.7 (13.7) and simulators

## Steps To Reproduce
1. Create multi-line TextInput field
2. Add a lot of lines
3. **On iOS devices** hold down the space bar and try to move **the cursor** to the desired point in the text
4. The text starts jerking, it is impossible to move **the cursor** to the desired point in the text

## Expected Results
**On iOS devices** in a multi-line TextInput user should be able to move the cursor to the desired point in the text.

## Snack, code example, screenshot, or link to a repository:
```
render() {
    return (
      <View
        style={{
          flex: 1,
          flexDirection: 'column',
          paddingTop: 70,
          paddingHorizontal: 20,
          alignItems: 'center',
          justifyContent: 'center',
        }}
      >
        <Text style={{ fontSize: 22, fontWeight: '600', marginBottom: 10 }}>
          Multiline TextInput iOS test
        </Text>
        <TextInput
          style={{
            height: 150,
            fontSize: 16,
            width: '90%',
            borderColor: 'gray',
            borderWidth: 1,
            paddingLeft: 5,
            paddingRight: 5,
          }}
          placeholder="Type multiline text here..."
          multiline
        />
      </View>
    );
  }
```
![Screen Recording 2021-01-15 at 23 09 13 (1)](https://user-images.githubusercontent.com/10499697/104786464-a67ebf00-5795-11eb-8736-b6aea4e4d297.gif)

**Comment by safaiyeh** [comment]
@artyom4ek Thanks for the issue! I'm not sure if TextInput manages this iOS gesture correctly - will need some community investigation & support.

**Comment by artyom4ek** [comment]
@safaiyeh Thanks for your reply. Do you know a workaround for solving this problem on iOS devices?

**Comment by artyom4ek** [comment]
@safaiyeh Thanks for your reply. Do you know a temporary workaround for solving this problem on iOS devices?

**Comment by efstathiosntonas** [comment]
Any updates in this one?

**Comment by efstathiosntonas** [comment]
It seems that the `animated:NO` causes the issue, setting it to `animated:YES` fixes it partially.

https://github.com/facebook/react-native/blob/896baf79d56e402cb1b0d3ca0eb5bd34e57d103b/Libraries/Text/TextInput/Multiline/RCTUITextView.m#L185-L190

Tested against iPhone 11 simulator and iPhone XS. 

But pressing space and moving up-down it's a bit jerky.

**Comment by xiankuncheng** [comment]
Hi @artyom4ek, I've raised [this PR](https://github.com/facebook/react-native/pull/32179) to fix this issue. I've tried on iOS 14 (device), iOS 13 (simulator), and seems to be fixed. Would love your help to verify it if possible 🙏.

Also huge thanks for @efstathiosntonas, the PR created based on your suggestion and investigation ❤️

**Comment by efstathiosntonas** [comment]
@xiankuncheng great job, thank you. It’s really weird that this issue was under estimated for so long, users were complaining on a daily basis.
