### ISSUE TITLE
On Android, the onKeyPress callback returns the wrong key value when the TextInput has the maxLength property

### ISSUE THREAD

**Issue by javiercsd** [facebook/react-native#30747]
## Description
In Android, when a TextInput with the maxLength property is "full"(that is, the length of the input is equal to the maximum), the onKeyPress event will return the last character in the input.

## React Native version:
0.63.3

## Steps To Reproduce

1. Create a TextInput component with maxLength=1, and an onKeyPress handler
2. Type multiple different characters into the TextInput
3. Observe that event.nativeEvent.key in the onKeyPress callback is always the first character that was entered into the TextInput

## Expected Results
onKeyPress should return the key that was actually pressed.

This behaviour only happens in Android, and can be seen in the following snack:
https://snack.expo.io/PuyXgucEf

**Comment by safaiyeh** [comment]
@javiercsd Thank you for the issue! I noticed the issue in your snack - kinda  annoying. Labeled it as a bug for people to check out.

**Comment by sbueno-bemobile** [comment]
Hi!

same issue here on 2023

not resolved yet?

**Comment by veliseev93** [comment]
The same issue 2024
