### ISSUE TITLE
Bug: [reactdev tools][react native] Bridge was already shutdown. Inspection is broken

### ISSUE THREAD

**Issue by resting** [facebook/react-native#30757]
Try debugging in vanilla react native project.
Install reactdev-tools: `npm i -D reactdev-tools`
Start react native app in iOS or Android.
Start `reactdev-tools`
Enable debug mode.
Try to inspect element.
Observe that there's a warning `Bridge was already shutdown`.
The inspect mode doesn't connect to it.

Update:
Some how it connects, when devtools window is not in view. Then stop and start debug again.

Expected:
Inpection should connect to reactdev-tools instead of in app

reactdev-tools: 4.10.1
RN: 0.63.3
R: 16.13.1

Demo
![2020-12-12_17-19-44](https://user-images.githubusercontent.com/350530/101980661-f0115100-3ca1-11eb-99fe-7d63e9aebee4.gif)

**Comment by rickhanlonii** [comment]
I believe this is an issue with React Native's integration with DevTools so I've moved this issue to the React Naive repo.

**Comment by sschottler** [comment]
I had the same issue and documented a workaround to get inspector working:

https://gist.github.com/sschottler/7771dc034d38b89d9d587dc5d358c386
