### ISSUE TITLE
TypeError: e.isPersistent is not a function.

### ISSUE THREAD

**Issue by LavinLv** [facebook/react-native#30759]
## Description

I collected a crash log in my app

Content:

Exception Reason:Unhandled JS Exception: 
TypeError: e.isPersistent is not a function. (In 'e.isPersistent()', 'e.isPersistent' is undefined), 
 
...
scrollResponderHandleScrollBeginDrag@335:2652 
scrollResponderHandleScrollBeginDrag@(null):(null) 
...

Component: Animated.FlatList

## React Native version:
"react-native": "0.63.3"

**Comment by dulmandakh** [comment]
This tracker is intended to track RN issues, but not developer support. It looks like an issue in your code or third-party module you use, because RN doesn't have isPersistent method.

**Comment by chrisbobbe** [comment]
> This tracker is intended to track RN issues, but not developer support. It looks like an issue in your code or third-party module you use, because RN doesn't have isPersistent method.

https://github.com/facebook/react-native/blob/v0.64.2/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js#L597
