### ISSUE TITLE
Question : Following the guide from reactnative native modules for Android throws error

### ISSUE THREAD

**Issue by gs-akhan** [facebook/react-native#3075]
Hi devs.
In process of creating Native modules for Android (Following what is mentioned in https://facebook.github.io/react-native/docs/native-modules-android.html#content)

I get this error while app compilation .

..src/main/java/com/azharapp/AnExampleReactPackage.java:15:error: AnExampleReactPackage is not abstract and does not override abstract method createViewManagers(ReactApplicationContext) in ReactPackage

Thanks.

**Comment by gs-akhan** [comment]
And also please tell us where to write the Java files for the native modules. Can they be siblings to MainActivity.java..  ?

Thanks

**Comment by satya164** [comment]
You need to implement the `createViewManagers` method and `createJSModules`. The package file will be something like this,

```java
class AnExampleReactPackage implements ReactPackage {
    @Override
    public List<NativeModule> createNativeModules(ReactApplicationContext reactContext) {
        return Arrays.<NativeModule>asList(
                new WebSocketModule(reactContext),
                new IntentModule(reactContext)
        );
    }

    @Override
    public List<Class<? extends JavaScriptModule>> createJSModules() {
        return Collections.emptyList();
    }

    @Override
    public List<ViewManager> createViewManagers(ReactApplicationContext reactContext) {
        return Arrays.asList();
    }
```

I don't think the package for the native modules really matters. As long as you can access the package class in the `MainActivity`, you should be good to go.

**Comment by gs-akhan** [comment]
Worked Perfectly .. Thank you very much !!
Closing.

**Comment by gopidon** [comment]
For those, visiting this link for similar issues, some more info. I realised that your react package should be added in addition to the MainReactPackage. So it goes like this

mReactInstanceManager = ReactInstanceManager.builder()
                .setApplication(getApplication())
                .setBundleAssetName("index.android.bundle")
                .setJSMainModuleName("index.android")
                .addPackage(new MainReactPackage())
                .addPackage(new AwesomeReactPackage())
                .setUseDeveloperSupport(BuildConfig.DEBUG)
                .setInitialLifecycleState(LifecycleState.RESUMED)
                .build();

**Comment by raihanabbas232** [comment]
well i am getting "

> method does not override from its superclass

" error while implementing ReactPackage interface... ReactPackage does not contain such method I've seen
