### ISSUE TITLE
Android application becomes super slow on startup after enabling Hermes 

### ISSUE THREAD

**Issue by marudy** [facebook/react-native#30750]
## Description
After enabling Hermes on my Android app in order to gain performance, the app becomes super slow. Specifically the startup time increases by 50%. 

In my case startup time for the native thread sky rockets to 25.5 seconds from 17 seconds before. I am using @axemclion [package](http://blog.nparashuram.com/2018/11/react-native-performance-playbook-part-i.html) to measure Android performance as mentioned in #26870 from @TheSavior . I am including logs and some initial troubleshooting below.

## React Native version:
0.64.0-rc2 for me but this is the first version I was ever able to activate Hermes without issues as we use mobx symbols and 0.63.x did not work for me.

I suspect though this is something happening since Hermes was introduced as there are other issues as well complaining about performance being affected with Hermes enabled or disabled.

## Steps To Reproduce
Not easy to provide that. Providing logs and traces though below.

## Expected Results
I'm expecting actually to gain the same 50% that somehow is introduced with the use of Hermes instead of adding it as a delay :) 

## Snack, code example, screenshot, or link to a repository:
So I am using @axemclion package to trace as mentioned before. That being said I am attaching the `TTI_COMPLETE` id over the View's container that lands first over my app. This remains stable as I'm enabling / disabling Hermes. I'm acquiring the traces from the JS thread and more specifically from the `AXE_PERFLOGGER` that the package attaches over `global` variable.

I'm proving these trace logs over the 2 files attached below named `marudy-0.64.0-rc2-hermes-disabled.log` & `marudy-0.64.0-rc2-hermes-enabled.log` respectively.

I'm also providing an excel file where I pasted these logs and started working my way of investigating where the extra time is introduced. This can be found [here](https://docs.google.com/spreadsheets/d/14IXva-zmeugNhe6ijkgerzej8DH39tQgBBQwTy4G4yQ/edit?usp=sharing). I'm conditionally showing with red background all the processes that take more than half a second to execute. The excel contains both of the runs and all the tasks executed; the first 566 lines are for the run with hermes disabled while the rest below for the run with hermes enabled.

As also mentioned in issue #26870 I have identified some initial observations from the logs provided:
- So far I am seeing that the major delay is being caused by the processes with name `GET_CONSTANTS_START`. There are around 50 of them being executed in my case and until the `TTI_COMPLETE` event. Over the run without hermes ALL of them execute within the same ms or the very next one. Over the run with hermes enabled i'm suddenly seeing numbers all the way from 1-6ms which are the fastest ones up to 1121 , 2034 , 3707 ms. This is a huge increase as we can see and these are causing the biggest part of the delay.
- On a 2nd note the process with name `CHANGE_THREAD_PRIORITY` also takes double the time it was occupying before. In my case from 567ms all the way up to 1132ms.
- On a 3rd note the process with name `CREATE_CATALYST_INSTANCE_END` takes now 2034ms while before it was accounting for 26ms only.

[marudy-0.64.0-rc2-hermes-disabled.log](https://github.com/facebook/react-native/files/5824874/marudy-0.64.0-rc2-hermes-disabled.log)
[marudy-0.64.0-rc2-hermes-enabled.log](https://github.com/facebook/react-native/files/5824875/marudy-0.64.0-rc2-hermes-enabled.log)

**Comment by dulmandakh** [comment]
@marudy I noticed that performance of debug build is somewhat decreased, but it was so fast in production build. Could you please check production build performance.

**Comment by marudy** [comment]
@dulmandakh yes i can confirm this in an issue for release type builds. But then again i am noticing 50% startup time increase which a lot regardless if you are in debug or release :) .

The reason why I went to troubleshoot and debug is because my production build startup time went from 11.5 seconds to 21 seconds which is close to double. This very measurement comes from release type APK (`./gradlew assembleRelease -x bundleReleaseJsAndAssets --max-workers 2`).

You see I am trying to improve Android performance of our product for quite some tine now. And we have managed to pull improvements here and there but now with Hermes we have an extra ~ 50% startup time in production at least. Some measurements go even more.

**Comment by diranolaleye** [comment]
I'm using react-native-cli: 2.0.1 and react-native: 0.63.4 and still having the same issue with android - very slow.
@TheSavior: Please re-open the issue ticket

**Comment by diranolaleye** [comment]
> I'm using react-native-cli: 2.0.1 and react-native: 0.63.4 and still having the same issue with android - very slow.
> @TheSavior: Please re-open the issue ticket

A solution: https://reactnative.dev/docs/hermes

**Comment by seanim0920** [comment]
> > I'm using react-native-cli: 2.0.1 and react-native: 0.63.4 and still having the same issue with android - very slow.
> > @TheSavior: Please re-open the issue ticket
> 
> A solution: https://reactnative.dev/docs/hermes

Hermes is the subject of this issue.

**Comment by AndresAltomobile** [comment]
Same here, Android is very slow with hermes enabled. 

Any update?

**React Native version**: 0.64.0

**Comment by TheSavior** [comment]
For people where this is slow, does the bundle you are executing contain JavaScript or is it bytecode? If it is JavaScript, then we'd expect that to be 2-5x slower, and probably means something is broken. When using Hermes the tooling should be creating bytecode bundles.

**Comment by marudy** [comment]
@TheSavior thanks for the feedback. 

I found out that my release variant bundle is indeed JS and not bytecode. But this is only a side effect of having seperated the JS bundle build from the APK / AAB generation because of a quite common issue of having task `./gradlew bundleReleaseJsAndAssets` returning 137 error code. 

I was able to generate bytecode and actually run a proper release APK and see the gains over my app (`~ 60% startup time) but still haven't found any concrete way to solve the CI issue and opt in Hermes there. Hints / tips on how to solve this would be welcome. I have searched and tried multiple things already but nothing that actually works yet.

**Comment by jslok** [comment]
> For people where this is slow, does the bundle you are executing contain JavaScript or is it bytecode? If it is JavaScript, then we'd expect that to be 2-5x slower, and probably means something is broken. When using Hermes the tooling should be creating bytecode bundles.

How do I check if the bundle contains js or bytecode? Thanks

**Comment by imranMnts** [comment]
@jslok you can unzip (or use apktool) to look in your apk.
The bundle is in the `assets/` folder, you can directly open it and check if it contains js or bytecode.

**Comment by sbearben** [comment]
> I was able to generate bytecode and actually run a proper release APK and see the gains over my app (`~ 60% startup time) but still haven't found any concrete way to solve the CI issue and opt in Hermes there. Hints / tips on how to solve this would be welcome. I have searched and tried multiple things already but nothing that actually works yet.

@marudy can you explain how you were able to generate bytecode? I'm inspecting my app's bundle after building with hermes both on and off. Looks like it's always JS code.

**Comment by AndresAltomobile** [comment]
I found out that my release variant bundle is JS and not bytecode.

Is there a way to generate a release variant with bytecode instead JS?

**Comment by amantrigunait** [comment]
Similar issue being faced. Release variant is JS and not bytecode.  Any help to generate bytecode variant would be really helpful.

**Comment by sbearben** [comment]
Make sure your gradle file is configured correctly. This line runs the react-native gradle plugin, which among other things, compiles the bundle to bytecode: https://github.com/facebook/react-native/blob/main/template/android/app/build.gradle#L84.

On our end the problem was two-fold:

1. Someone had moved that line above where we set:

```groovy
project.ext.react = [
    enableHermes: true,  // clean and rebuild if changing
]
```
Which meant the gradle plugin ran before enableHermes was set to true.

2. Our CI build process had a manual task to create the JS bundle, and omitted bytecode compilation (shouldn't be an issue for most).

**Comment by tapz** [comment]
Can I somehow disable hermes for debug builds and only use it in release? The debug builds have been super slow for the past couple of years and looks like this will never be fixed.

**Comment by cortinico** [comment]
Closing as this was fixed by updating the Hermes compilation flags.
You should be able to use Hermes without any regressions. If so open a new issue please.
