### ISSUE TITLE
[iOS] RCTAssert RCTFormatError 165 ReferenceError: Can't find variable: typeAnnotation

### ISSUE THREAD

**Issue by AliRehman7141** [facebook/react-native#30760]
## Description
[iOS] app is working fine on simulator or device when I run it directly, But when I generate an archive it's crashing. 
With the help of Crashlytics, I found the issue here
```
Fatal Exception: RCTFatalException: Unhandled JS Exception: ReferenceError: Can't find variable: typeAnnotation
Unhandled JS Exception: ReferenceError: Can't find variable: typeAnnotation, stack: <unknown>@1383:17088 v@2:1473 <unknown>@1382:425 v@2:1473 <unknown>@1381:339 v@2:1473 <unknown>@1374:6338 v@2:1473 <unknown>@1373:303 v@2:1473 <unknown>@650:7881 v@2:1473 <unknown>@437:237 v@2:1473 <unknown>@408:255 v@2:1473 <unknown>@6:57 v@2:1473 d@2:875 global code@1711:3
```

```
RCTAssert.m - Line 165
RCTFormatError + 165
```
## React Native version:
```
System:
    OS: macOS 11.0.1
    CPU: (4) x64 Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
    Memory: 21.23 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.12.0 - ~/.nvm/versions/node/v12.13.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    Android SDK:
      API Levels: 23, 26, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2
      System Images: android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.2/12B45b - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_275 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```
![Screen Shot 2021-01-19 at 6 34 07 PM](https://user-images.githubusercontent.com/33172988/105041563-f2c34b00-5a84-11eb-9ba7-c6df1ecf65e9.png)

**Comment by AliRehman7141** [comment]
Any update?

**Comment by mustymustafa** [comment]
hello Ali. please have you been able to find a solution. thank you

**Comment by AliRehman7141** [comment]
Not yet!
I have created a new project an copy the src folder in that It's working
without navigation enabled. But when I change the default App.js route to
my App.js the routing is enabled and it's crashing again.

**Comment by AliRehman7141** [comment]
@mustymustafa check the auto imported thing

It is fixed by adding 
```import 'react-native-gesture-handler';```
to the index.js

Secondly, I removed an auto imported thing from babel which is causing the crash. 
- removed this ```import { cloneDeep } from '@babel/types';```

Auto import from babel is the main crash.

**Comment by prvaghela** [comment]
@AliRehman7141 - import 'react-native-gesture-handler'; -> Do we need to put in project's main index.js or in the react-native-gesture-handler folder one?

**Comment by AliRehman7141** [comment]
@prvaghela Sorry for the late response!
Yes! it is required for me but maybe not for you.

**Comment by RahulRijhwani** [comment]
@AliRehman7141 at what place you remove import { cloneDeep } from '@babel/types' this import ?

**Comment by prvaghela** [comment]
I have removed one import in one of my JS having from '@babel/types'. Now it is working fine

**Comment by AliRehman7141** [comment]
> @AliRehman7141 at what place you remove import { cloneDeep } from '@babel/types' this import ?

Somewhere in my components

**Comment by BLOCKMATERIAL** [comment]
I had the same problem.
I found the import files from the **'@babel/types'** library cut them out and **updated all the dependencies** and the application ran.
