### ISSUE TITLE
add or update keyboard events to relay if keyboard was opened from the current app

### ISSUE THREAD

**Issue by chrisdrackett** [facebook/react-native#30762]
> moved from (https://github.com/react-native-community/discussions-and-proposals/issues/320) due to recommendation of @kelset

when using an iOS app on an iPad with split screen its possible that the other open app invoked the keyboard. The issue is that right now to a react native app there is no way to know if the keyboard was opened from your app or another app. Apple provides keyboardIsLocalUserInfoKey for determining this and there might be something similar on android.

**Comment by safaiyeh** [comment]
According to this comment https://github.com/react-native-community/discussions-and-proposals/issues/320#issuecomment-763042568 the resolution was for a PR to be opened, closing for now.

**Comment by chrisdrackett** [comment]
@safaiyeh I'm so confused. Is there now way for this issue/feature request to be tracked other than someone fixing themselves? It is currently beyond my ability to fix, but someone else looking for things to add to react native could pick it up. Seems like there is no current way to track this kind of feature request in react native right now unless I'm missing something.
