### ISSUE TITLE
Metro bundle window lock RN project files on Windows 10

### ISSUE THREAD

**Issue by lisichka999** [facebook/react-native#30773]
## Description
I am facing some problem with RN windows 10 environment.
During build process it failed to delete/create some folders and files and  the following errors appear:

Execution failed for task ':some-package:compileDebugJavaWithJavac'.
> java.io.IOException: Unable to delete directory 'MyProject\node_modules\cp-ssl-pinning\android\build\intermediates\javac\debug\compileDebugJavaWithJavac\classes'

There any many errors of this type.

I notice if I run the app from android studio(run app) and don’t open metro window the build is succeeded, but of course not copied to the device.
Looks like metro lock files of the project, and this is what I understand from google, but didn’t find any solution for it.

## React Native version:
61

## Steps To Reproduce

1. Set up windows environment
2. run npx react-native run-android

**Comment by safaiyeh** [comment]
Hi @lisichka999 thank you for the issue! For environment issues, it is best to ask StackOverflow
