### ISSUE TITLE
Possible regression on #29292 

### ISSUE THREAD

**Issue by andres-torres-marroquin** [facebook/react-native#30770]
## Description

The issue #29292 makes a regression on the `keyboardDidHide` behavior for the
Android platform, if it happens that you have multiple `ReactRootView`s on the
same application at once, the `keyboardDidHide` event happens for every `ReactRootView`
and the last event data  will prevail.

## Steps To Reproduce
Having multiple `ReactRootView`s is specially common using `react-native-navigation`,
in this example we provide two `ReactRootView`, one as main canvas (in red) and one on the
top right screen border (in blue), the event `keyboardDidHide` is triggered twice,
where in the first trigger it sends the "right" value, because it is being triggered
by the main canvas (in red), and on the second trigger it sends the "wrong" value, since
it is being triggered by the top right screen view (in blue).

Comparing this behavior with the iOS counterpart the event is triggered only once
and it sends the right value, for this exact same code.

## Snack, code example, screenshot, or link to a repository:
https://github.com/andres-torres-marroquin/RN29292

**Comment by safaiyeh** [comment]
@fabriziobertoglio1987 could you take a look at this? The issue is referencing a PR you a made a while ago.

**Comment by fabriziobertoglio1987** [comment]
@safaiyeh thanks. Yes, I will reproduce the issue and try to find a solution during the weekend. Thanks a lot :pray: :peace_symbol:

**Comment by fabriziobertoglio1987** [comment]
Thanks a lot @andres-torres-marroquin 
My observations are the following

- my commit was introduced in [0.63.3](https://github.com/react-native-community/releases/blob/master/CHANGELOG.md#fixed-1)
- I tested your example on both 0.63.4 and 0.63.2 and can not see any (visual) difference in behaviour in the KeyboardDidHide functionality
- Unluckily I do not know or contribute to react-native-navigation
- Seems to me that the functionality behaves in the same way with/out react-native-navigation

I tested in my [repo](https://github.com/fabriziobertoglio1987/react-native-issue-30770) with react-native 0.63.2. My commit was introduced with [0.63.3](https://github.com/react-native-community/releases/blob/master/CHANGELOG.md#fixed-1)

| **Full Screen** | **After Keyboard Did Hide** |
|:-------------------------:|:-------------------------:|
|  <img src="https://user-images.githubusercontent.com/24992535/106175432-686e9b80-6196-11eb-86fc-dc429f0afad6.png"  width="300" height="" />| <img src="https://user-images.githubusercontent.com/24992535/106175435-6a385f00-6196-11eb-9d0b-411421ef40fc.png"  width="300" height="" />|

The results of the tests from your [repo](https://github.com/andres-torres-marroquin/RN29292)

| **Full Screen** | **After Keyboard Did Hide** |
|:-------------------------:|:-------------------------:|
|  <img src="https://user-images.githubusercontent.com/24992535/106175919-f5195980-6196-11eb-9af7-e80cb1c230cb.png"  width="300" height="" />| <img src="https://user-images.githubusercontent.com/24992535/106175921-f5b1f000-6196-11eb-8658-f784597dec0f.png"  width="300" height="" />|

I remain available and I'm sorry if I misunderstood or ignore this issue. I am willing to work during the weekends to fix this regression. Thanks a lot :pray: Fabrizio

**Comment by andres-torres-marroquin** [comment]
Hi @fabriziobertoglio1987, thanks for you reply.

Unfortunately, both examples don't show `keyboardDidHide`, they do show `keyboardDidShow`.

**Full Screen**

<img alt="" width="300" height="" src="https://user-images.githubusercontent.com/546253/106617196-04502c80-6534-11eb-87de-7b5b176ddd98.jpg">

**keyboardDidShow**
<img alt="" width="300" height="" src="https://user-images.githubusercontent.com/546253/106617201-04e8c300-6534-11eb-9e81-5fcd0c262617.jpg">

**keyboardDidHide**
<img alt="" width="300" height="" src="https://user-images.githubusercontent.com/546253/106617204-05815980-6534-11eb-9061-fb243a0a0d29.jpg">


I also emphasize that it happens when you have more than one ReactRootView on Android, on my repo there are two, the red one and the blue one. It won't happen on your repo since there you have only one ReactRootView.

**Comment by fabriziobertoglio1987** [comment]
Thanks @andres-torres-marroquin 

can you override in the 2nd child ReactRootView?

https://github.com/facebook/react-native/blob/41b6884a1bdfceddb04c43c55714c04578c351ac/ReactAndroid/src/main/java/com/facebook/react/ReactRootView.java#L755-L785

with

https://github.com/facebook/react-native/blob/98309fa7fce9e7d72416c76a25dc0f759f46c3e8/ReactAndroid/src/main/java/com/facebook/react/ReactRootView.java#L667-L697

**Comment by andres-torres-marroquin** [comment]
I cannot override that 2nd view, that is handled by `react-native-navigation` under the hood.

**Comment by fabriziobertoglio1987** [comment]
I'll send pr to override `onMeasure` in `ReactView`, if those are the views used for this scenario. 

```java
public class ReactView extends ReactRootView implements IReactView, Renderable {


	private final ReactInstanceManager reactInstanceManager;
	private final String componentId;
	private final String componentName;
	private boolean isAttachedToReactInstance = false;
    private final JSTouchDispatcher jsTouchDispatcher;


    public ReactView(final Context context, ReactInstanceManager reactInstanceManager, String componentId, String componentName) {
		super(context);
		this.reactInstanceManager = reactInstanceManager;
		this.componentId = componentId;
		this.componentName = componentName;
		jsTouchDispatcher = new JSTouchDispatcher(this);
	}


    @Override
    protected void onAttachedToWindow() {
        super.onAttachedToWindow();
        start();
    }
 }
```

https://github.com/wix/react-native-navigation/blob/15c7a7e799f3cff9ad83b782dccc92aa1fe8a523/lib/android/app/src/main/java/com/reactnativenavigation/react/ReactView.java#L23-L43

onMeasure should look like this

https://github.com/facebook/react-native/blob/98309fa7fce9e7d72416c76a25dc0f759f46c3e8/ReactAndroid/src/main/java/com/facebook/react/ReactRootView.java#L667-L697

hopefully it will work, otherwise will think about something else. Thanks

**Comment by andres-torres-marroquin** [comment]
@fabriziobertoglio1987 this has become suddenly really important, since there is a bug for uploading files in 0.63.2 for iOS, so we either downgrade even further than 0.62.2, or compile the iOS app with 0.63.4 and the Android app with 0.63.2.

How can this issue get more attention?

**Comment by fabriziobertoglio1987** [comment]
https://github.com/sponsors/fabriziobertoglio1987 Thanks a lot :peace_symbol: :pray:

**Comment by carlosalbertm** [comment]
It's seems that guy doesn't want to help to the community, what a shame

**Comment by fabriziobertoglio1987** [comment]
You can fix your own bugs, I'm blocking both of you.

I ask for contributions because I contributing full time to facebook/react-native.

**Comment by fabriziobertoglio1987** [comment]
- I specialize on **ReactAndroid**
- this issue is a react-native-navigation which inherits from [**ReactRootView**](https://github.com/wix/react-native-navigation/blob/15c7a7e799f3cff9ad83b782dccc92aa1fe8a523/lib/android/app/src/main/java/com/reactnativenavigation/react/ReactView.java#L23-L43)
- I don't and will not contribute to other opensource projects (ex. react-native-camera or react-native-navigation)
- I contribute to opensource fulltime now, while in my last job I was paid 8 euros per hour and lasted 7 months.
I can not afford to contribute to 1000s opensource projects that get deprecated and my knowledge/time is lost. 
- You can publish PR to revert this change
- I don't have a better solution
- I have solution to other issues, so do not spam me as I have limited amount of time and I can use it to try to improve ReactAndroid.
- If Core or Other Contributors will contact me and ask to change this PR, I will publish a change (maybe a revert to this solution) as I don't know any other way to fix this (except changing react-native-navigation, but I don't contribute to other projects).

Thanks :peace_symbol: :pray: :heart:

**Comment by safaiyeh** [comment]
@carlosalbertm comments like that aren't appreciated. @fabriziobertoglio1987 has been an amazing contributor to many React Native issues, help on issues like this would be appreciated from anyone including you 😁

@andres-torres-marroquin i would suggest speaking to the react-native-navigation team for more context! They are very responsive especially in their discord cc @guyca

**Comment by guyca** [comment]
Hey guys, sorry for the inconvenience. This issue is caused by RNN, not by React Native, and will be resolved by https://github.com/wix/react-native-navigation/pull/7022.

We can safely close this issue. Also, thanks @fabriziobertoglio1987 for all your hard work ❤️
