### ISSUE TITLE
Developer menu unusable until simulator restart if actived while 'Slow Animations' is enabled

### ISSUE THREAD

**Issue by fredemmott** [facebook/react-native#3077]
I guess I accidentally hit command-T...

1. Turn on slow animations in 'Debug' menu
2. open react developer menu with command T
3. clicking does nothing, regardless of if it's on the options or outside - afaict it's impossible to close this menu now
4. disable slow animations
5. clicking still does nothing. Hitting command-D also does nothing

To fix: restart simulator with slow animations still disabled.

**Comment by ram535ii** [comment]
+1

**Comment by eadz** [comment]
Wow. I just thought my app was broken. The old Cmd+T...

The fact that the debug menu doesn't work when slow animations is on is surely a bug though. But maybe in the simulator rather than RN?

**Comment by sairion** [comment]
I have not actiavted cmd + T mode but it is slow.

**Comment by tjlav5** [comment]
:+1:  This was really frustrating me for the past hour

**Comment by aleclarson** [comment]
+1

**Comment by christopherdro** [comment]
There is now a log in Xcode that lets you know if Slow animations have been turned on.
I'm not noticing any issues with the dev menu in this mode though.

Closing this for now. Feel free to re-open it if the problem persists.

**Comment by BenGale** [comment]
This is terribly frustrating, it made the debug menu completely unusable for me.

**Comment by cpsubrian** [comment]
I got bit by this hehe, at least google got me here 😢
