### ISSUE TITLE
ld: library not found for -lAppAuth

### ISSUE THREAD

**Issue by reposocial** [facebook/react-native#30787]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
please help what happen this.

![Screen Shot 2021-01-21 at 16 30 03](https://user-images.githubusercontent.com/34335974/105702161-f26ff780-5f3d-11eb-9dc3-b0516a96ee62.png)

i was try to fix this with another case and documentations like this :
https://stackoverflow.com/questions/63136505/react-native-0-63-2-ios-build-error-with-ld-library-not-found-for-lappauth
https://stackoverflow.com/questions/62409358/xcode-11-clang-error-linker-command-failed-with-exit-code-1-use-v-to-see-in
https://github.com/FormidableLabs/react-native-app-auth/issues/118
https://github.com/react-native-community/upgrade-support/issues/52

but still NOT SOLVED

## React Native version:
0.63.4

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. updgrade some pacakge
2. run on xcode

## Expected Results
Describe what you expected to happen.

## Snack, code example, screenshot, or link to a repository:
Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by dulmandakh** [comment]
Please make sure to run **pod install** in **ios** folder.
