### ISSUE TITLE
PanResponder does not work on Android for views absolutely positioned outside of parent boundaries.

### ISSUE THREAD

**Issue by widelec2** [facebook/react-native#30782]
On Android PanResponder does not work on parts of View which is absolutely positioned outside of boundaries of it parent containter. However on iOS it works properly.

Blue rectangle is a parent container which stores two child views. One of them (full green) is fully in boundaries of its parent and other one is partly inside and partly outside (green/red). Both of them have PanResponder attached which works only for green areas and does not on red one which is outside of parent's boundary.

![Screenshot 2021-01-23 at 18 22 52](https://user-images.githubusercontent.com/75758694/105609229-3630f880-5da8-11eb-8575-eaef207142cd.png)

Here is the link to [SNACK](https://snack.expo.io/@widelec2/android_pan_responder)

When user clicks on green areas, there is confirmation message showed above in the yellow rectangle notifying GRANT state of PanResponder, however clicking on red square does not trigger PanResponder at all.

**Comment by safaiyeh** [comment]
@widelec2 Thank you for the issue, I've seen common issues like this: https://github.com/facebook/react-native/pull/26374

The example was helpful in demonstrating the bug, accepting this as a bug.

**Comment by MickeyMouse623** [comment]
> @ widelec2谢谢您的问题，我已经看到过类似的常见问题：[＃26374](https://github.com/facebook/react-native/pull/26374)
> 
> 该示例有助于演示该错误，并将其接受为错误。

请问这个问题啥时候修复？我也遇到这样的问题
![image](https://user-images.githubusercontent.com/18524460/108984039-74cd1200-76ca-11eb-86e7-fa049e99ff3b.png)

绿色按钮超出元素的部分不响应 ```PanResponder```
