### ISSUE TITLE
SectionList's header unmounts with empty list of sections

### ISSUE THREAD

**Issue by dani-mp** [facebook/react-native#30784]
## Description
In the context of a simple section list with a header on iOS, going from an empty list of sections to a non-empty one, and vice-versa, makes the section list's header unmount. If we keep at least one section in the list, even if it's a fake element not meant to be shown, the header doesn't unmount.

The bug is not reproducible on Android.

## React Native version:
Run `react-native info` in your terminal and copy the results here.
```
System:
    OS: macOS 11.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 213.70 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
    Yarn: 1.13.0 - ~/dev/project/app/scripts/yarn
    npm: 7.0.14 - /usr/local/bin/npm
    Watchman: 4.7.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 22, 23, 25, 26, 27, 28, 29
      Build Tools: 21.1.2, 22.0.1, 23.0.1, 23.0.3, 25.0.0, 25.0.2, 26.0.1, 26.0.2, 27.0.1, 27.0.3, 28.0.2, 28.0.3, 29.0.2
      System Images: android-22 | Google APIs Intel x86 Atom, android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64, android-25 | Google Play Intel x86 Atom, android-27 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 12.3/12C33 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_152-release - /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/javac
    Python: 3.7.3 - /Users/Daniel/.pyenv/shims/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
You can check the snack https://snack.expo.io/@danielmartin/479f65, running on an iOS device/simulator.
1. An alert is shown when the header unmounts.
2. Tapping on the first button shows the bug.
2. Tapping on the second button shows a workaround for the bug and the expected behavior.

## Expected Results
The section list's header doesn't unmount when the first button is tapped.

## Snack, code example, screenshot, or link to a repository:
https://snack.expo.io/@danielmartin/479f65

**Comment by gabriel-moresco** [comment]
hello @dani-mp, how did you handle with this problem? it's happening to me too.

**Comment by dani-mp** [comment]
> hello @dani-mp, how did you handle with this problem? it's happening to me too.

Please, read the issue and the attached snack.
