### ISSUE TITLE
Nested text with different lineHeight are cropped on Android

### ISSUE THREAD

**Issue by Mighty683** [facebook/react-native#30794]
## Description
If we nest text element inside text element with different heights eg: lineHeight 20 inside lineHeight 30 output on android will be cropped, the bigger difference the bigger crop is. It looks like parent `Text` element takes child `Text` lineHeight.

I have found workaround by wrapping child `Text` element by `View` element first to break `Text` styles inheritance.

## React Native version:
```
npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Expected Results
Text should be displayed the same way on Android and on iOS

### Minimal App to show bug:
```
import React from 'react';
import { StyleSheet, View, Text } from 'react-native';


const styles = StyleSheet.create({
  text1: {
    fontSize: 20,
    lineHeight: 30,
    fontWeight: 'bold',
  },
  text2: {
    fontSize: 10,
    lineHeight: 20,
  },
  container: {
    padding: 50,
    backgroundColor: 'white',
    height: '100%',
  },
});

const App = () => {

  return (
    <View style={styles.container}>
      <Text style={styles.text1}>TEXT 1 <Text style={styles.text2}>TEXT 2</Text></Text>
    </View>
  );
};

export default App;
```
###  Screenshot Android:
![Screenshot_20210126_073844_com appjobs rewards](https://user-images.githubusercontent.com/22498910/105809320-c5592e80-5fa9-11eb-8fd9-a24d0800b24c.jpg)
### Screenshot iOS:
![Simulator Screen Shot - iPhone 11 - 2021-01-26 at 07 39 39](https://user-images.githubusercontent.com/22498910/105809338-ce4a0000-5fa9-11eb-96c6-7a99ed083c99.png)

**Comment by Mighty683** [comment]
Seems to be old bug:
https://github.com/facebook/react-native/issues/13126

**Comment by yahacom** [comment]
looks like there no solution/fix yet.I catch the same behaviour at RN 0.66.2

**Comment by fabriziobertoglio1987** [comment]
Do you still experience this issue? 

I have four years of experience maintaining facebook/react-native and I specialize in the Text and TextInput components. I currently have 58 [facebook/react-native PRs](https://github.com/facebook/react-native/pulls?q=is%3Apr+author%3Afabriziobertoglio1987+). 

If you still experience this issue, I will prepare a patched release with the fix.

Thanks a lot

**Comment by ktroitsky** [comment]
+1

**Comment by LegendEffects** [comment]
I have just encountered this, tracking it down to was a pain and to find that there's no fix is even more of a pain.

**Comment by julian-gargicevich** [comment]
Same issue

**Comment by SimranDev** [comment]
Facing it in 2025.

**Comment by szado** [comment]
Same issue here.

**Comment by watuLammini** [comment]
Any updates?
