### ISSUE TITLE
Bold custom font not apply on Android 11

### ISSUE THREAD

**Issue by seosd97** [facebook/react-native#30793]
## Description
It's only reproduced on Android 11.
The custom fonts were working well until now, that seems can't find a bold font file after upgrade to Android 11.
So currently, my device's system font is overriding my app's bold text.

My font files are in the `./android/app/src/main/asset/fonts` and names are `*_bold.ttf`.
(I tried manually set the `Text`'s `fontFamily` as a "*_bold", it also didn't work)

## React Native version:
"react-native": "0.63.4"

## Images
<img width="201" alt="스크린샷 2021-01-26 오후 3 34 01" src="https://user-images.githubusercontent.com/50171785/105808918-0bcf7d00-5fec-11eb-8dd3-c2c98a3ab9d0.png">

The text in the black square is `normal` text, it's applied custom font. The text in the red square is `bold` text, it's not applied custom font, that's override by system font. It's working before upgrade to Android 11.

**Comment by dorthwein** [comment]
I'm also running into this issue.  Also breaks icons.
