### ISSUE TITLE
Setting some 1 sided styling props on TextInput does not work correctly. An update since issue #7070.

### ISSUE THREAD

**Issue by CostachescuCristinel** [facebook/react-native#30809]
## Description
This is a bug-update report, following a previously opened issue.

React Native's TextInput docs present a warning on the `style` prop indicating an incomplete list of 1 sided stylings that will not work on TextInput. They still reference [this old 2016 thread: issue #7070](https://github.com/facebook/react-native/issues/7070) which was simply locked with this warning on the docs, and no real resolution.

I am posting such that, hopefully, some RN devs can look again into the issue, and maybe give us a clear understanding on what works, what doesn't - and maybe the TextInput style warning can be given more info as well...?

To help out, I have tested this myself. My methodology is by far not the best, but I think it covers some of the most frequent use cases. If it is of any relevance, I am testing trough Expo (SDK 40).
All presented issues can be reproduced on Snack.

## React Native version:
```
% npx react-native info
info Fetching system and libraries information...
System:
    OS: macOS 11.1
    CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
    Memory: 266.61 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.18.2 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK:
      Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 12.3/12C33 - /usr/bin/xcodebuild
  Languages:
    Java: 14.0.1 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Start a new blank project, import TextInput, and apply any combination of the styling props described in the list below. Test on iOS and Android at the same time.

List of tested styling props:
- **1 sided border width**
`borderTopWidth, borderBottomWidth, borderLeftWidth, borderRightWidth`
- **1 sided border colors**
`borderTopColor, borderBottomColor, borderLeftColor, borderRightColor`
- **1 sided (cornered) border radiuses**
`borderTopLeftRadius, borderTopRightRadius, borderBottomLeftRadius, borderBottomRightRadius`
- **1 sided margins**
`marginTop, marginBottom, marginLeft, marginRight`
- **1 sided paddings**
`paddingTop, paddingBottom, paddingLeft, paddingRight`
- **shadows**
`elevation, shadowOffset, shadowOpacity, shadowRadius`

## Expected Results
As of the time of this post and react-native version `0.63.2`, only the following (out of the tested) styling props seem NOT to work as intended.
**All issues are only present on Android, iOS works correctly in all (tested) cases**.

- `borderLeftColor` and `borderRightColor`
These styling props work correctly as long as there is no `borderColor` styling prop. Doesn't matter the order in which they appear in the styling object(s), `borderColor` will override their values.

- All 1 sided border width styling props: `borderTopWidth, borderBottomWidth, borderLeftWidth, borderRightWidth`
Borders should never overlap with the content area, or the padding area. See the [W3schools CSS Box Model](https://www.w3schools.com/css/css_boxmodel.asp) for reference.
However, all 1 sided border props will draw within the content box of the TextInput, with borders being visible under the text. They also affect the 1 sided paddings, effectively cancelling out their respective `paddingXxx` prop
The all sided `padding` prop seems NOT to be affected by this.

All other tested 1 sided styling props seem to work fine both on iOS and Android, including shadow/elevation, single-line and multi-line input variants. See the snack and screenshots in further sections.

## Snack, code example, screenshot, or link to a repository:
**Snack**
https://snack.expo.io/@cristian-nxtl/textinput---testing-which-1-sided-styling-props-are-not-working

**Screenshots**
Screenshots have been taken on Simulator/Emulator for convenience, tested on real devices as well, see below.

iOS Simulator: iPhone 11 Pro Max | iOS 14.2
Tested on real device: iPhone SE 1st gen | iOS 14.3
![Simulator Screen Shot - iPhone 11 Pro Max - 2021-01-28 at 17 14 50](https://user-images.githubusercontent.com/52235106/106158036-fb560880-618b-11eb-9f68-741c41d9a80e.png)

Android Emulator: Pixel 3A | Android 10
Tested on real device: Samsung Galaxy A5 2016 (SM-A510F) | Android 10 (Lineage OS 17.1)

![Screenshot_1611846893](https://user-images.githubusercontent.com/52235106/106158015-f5602780-618b-11eb-9f74-613a928a6ca7.png)

**Comment by fabriziobertoglio1987** [comment]
Do you still experience this issue? 

I have four years of experience maintaining facebook/react-native and I specialize in the Text and TextInput components. I currently have 58 [facebook/react-native PRs](https://github.com/facebook/react-native/pulls?q=is%3Apr+author%3Afabriziobertoglio1987+). 

If you still experience this issue, I will prepare a patched release with the fix.

Thanks a lot
