### ISSUE TITLE
Accessibility Focus Issue

### ISSUE THREAD

**Issue by abhay-sqh** [facebook/react-native#30802]
## Description
In Case of Accessibility Enabled when user navigate from One screen to another(using react-navigation for screen navigation), **accessibility focus is not behaving properly**, In many Cases focus moves to any random component and announcing that content, In some case focus persist the instance of any component from previous screen and announcing that content which is not visible on current screen.(i.e. Empty focus block is showing on screen and announcing the content of previous screen)

## React Native version:
react: 16.11.0 => 16.11.0 
react-native: 0.62.2 => 0.62.2 

## Steps To Reproduce

1. Enable the Accessibility(Majorly in iOS Platform, Sometimes in Android as well)
2. Enable focus on any component of screen.
3. Navigate to another screen(Used react-navigation)
4. Either focus persist the instance of previous screen's component or it goto the any random component.
5. Announcing content of component from previous screen.

## Expected Results
On Navigating from One screen to another, focus should goto the first component of Next Screen(i.e. Back Button) and should announce the content of that component.

**Comment by safaiyeh** [comment]
Hello @abhay-sqh thank you for the issue. This seems to be an issue with `react-navigation`, please open a new issue with them. If it turns out React native could help address it, feel free to open a new issue.
