### ISSUE TITLE
React Native TextInput the input text is not displayed

### ISSUE THREAD

**Issue by yoyo0427** [facebook/react-native#30801]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
React Native When I input TextInput, the input text is not displayed. This is an accidental situation. How can I solve this problem?

## React Native version:
"react-native": "0.59.5"

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.This is an accidental situation
2.
<TextInput
  style={styles.text_input}
  placeholder={'请填写注册时的手机号'}
  underlineColorAndroid='transparent'
  returnKeyType ='done'
  onChangeText={(text)=> {
     this.setState({
       phoneNumber: text
     });
  }}
/>
3.
text_input: {
  fontSize: 14,
  height: 40,
  color:Colors.FontBlackColor
}

## Expected Results
the input text is display

## Snack, code example, screenshot, or link to a repository:
![1611726131007](https://user-images.githubusercontent.com/12933263/105950810-fd479b00-60a9-11eb-89be-1260f2b15089.gif)

**Comment by rashidmakki** [comment]
> Please provide all the information requested. Issues that do not follow this format are likely to stall.
> 
> ## Description
> React Native When I input TextInput, the input text is not displayed. This is an accidental situation. How can I solve this problem?
> 
> ## React Native version:
> "react-native": "0.59.5"
> 
> ## Steps To Reproduce
> Provide a detailed list of steps that reproduce the issue.
> 
> 1.This is an accidental situation
> 2.
> <TextInput
> style={styles.text_input}
> placeholder={'请填写注册时的手机号'}
> underlineColorAndroid='transparent'
> returnKeyType ='done'
> onChangeText={(text)=> {
> this.setState({
> phoneNumber: text
> });
> }}
> />
> 3.
> text_input: {
> fontSize: 14,
> height: 40,
> color:Colors.FontBlackColor
> }
> 
> ## Expected Results
> the input text is display
> 
> ## Snack, code example, screenshot, or link to a repository:
> ![1611726131007](https://user-images.githubusercontent.com/12933263/105950810-fd479b00-60a9-11eb-89be-1260f2b15089.gif)

value={phoneNumber} as a props for TextInput
E.g 
<TextInput
style={styles.text_input}
value={phoneNumber}     
placeholder={'请填写注册时的手机号'}
underlineColorAndroid='transparent'
returnKeyType ='done'
onChangeText={(text)=> {
this.setState({
phoneNumber: text
});
}}
/>
