### ISSUE TITLE
iOS 14 email sharesheet subject disappears

### ISSUE THREAD

**Issue by hewseph** [facebook/react-native#30804]
## Description
OS: iOS 14
device: iPhone 12

The subject line for an email disappears when an app uses react-natives share-sheet to share via native mail app, delete draft, then click share via the mail app again. Also- the subject line will never appear when using the Gmail app from the App Store.

## React Native version:
0.63.2

## Steps To Reproduce
To reproduce Bug 1:

1. Execute react-natives Share.share method to open the share-sheet
2. Open native email app (subject line appears here)
3. Cancel email an click Delete Draft
4. Share-sheet menu is still open (only happens on iOS 14). Click native email app again.
5. The subject line is now empty

To reproduce Bug 2:

1. Execute react-natives Share.share method to open the share-sheet
2. Open Gmail app from app store
3. The subject line is empty

## Expected Results
I expect the email subject line to persist.

## Snack, code example, screenshot, or link to a repository:
<details>
<summary><strong>Screen recording of bug</strong></summary>
<br>
<img src="https://user-images.githubusercontent.com/69801422/106023399-c3b86500-6094-11eb-8c46-ba1e52a8e3d9.gif">
</details>

Code implementation:
```
Share.share({
      message: // we use logic here to determine the device/platform to format mesage
      url,
      title: subject,
    }, {
      dialogTitle,
      excludedActivityTypes,
      subject,
    });
```

**Comment by safaiyeh** [comment]
Hi @hewseph react-native-share support is officially outside the core library. Please file an issue with https://github.com/react-native-share/react-native-share if it is an issue still with the external library.

**Comment by hewseph** [comment]
Moved the issue:
https://github.com/react-native-share/react-native-share/issues/961
