### ISSUE TITLE
NSException *	"Could not load NIB in bundle: 'NSBundle <path to app> (loaded)' with name 'LaunchScreen'"

### ISSUE THREAD

**Issue by ThinkSalat** [facebook/react-native#30800]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
My app is building from running react-native android just fine, however iOS is building, but crashing on the launchscreen with the following error
`
Exception	NSException *	"Could not load NIB in bundle: 'NSBundle <path to app> (loaded)' with name 'LaunchScreen"
`
I just upgraded from 0.62.2 to 0.63.4, using the [upgrade helper tool](https://react-native-community.github.io/upgrade-helper/?from=0.62.2&to=0.63.4), since the automatic tool didn't work. 

## React Native version:
System:
    OS: macOS 11.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 132.11 MB / 16.00 GB
    Shell: 3.0.0 - /usr/local/bin/fish
  Binaries:
    Node: 14.15.1 - ~/.nvm/versions/node/v14.15.1/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 26.0.3, 28.0.3, 29.0.2
      System Images: android-23 | Google APIs Intel x86 Atom_64, android-24 | Google Play Intel x86 Atom, android-26 | Google APIs Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.2 AI-181.5540.7.32.5056338
    Xcode: 12.3/12C33 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_191 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. upgrade from 0.62.2 to 0.62.4 (must not automatically upgrade using `npx react-native upgrade`)
2. use react native upgrade tool helper to manually copy merge code.
3. 

## Expected Results
The app should start up, as it works fine on android.

## Snack, code example, screenshot, or link to a repository:
![image](https://user-images.githubusercontent.com/31082405/105896909-4f19f380-5fcc-11eb-91dd-a21dc364b9f2.png)
![image](https://user-images.githubusercontent.com/31082405/105896929-55a86b00-5fcc-11eb-9bf0-b946b787ed2d.png)

**Comment by safaiyeh** [comment]
Hi @ThinkSalat thanks for filing the issue. For upgrade related issues head over to https://github.com/react-native-community/upgrade-support!

A quick check there seems to be a solution there as well: https://github.com/react-native-community/upgrade-support/issues/115
