### ISSUE TITLE
 StatusBar.setHidden crashes when passed undefined on Android

### ISSUE THREAD

**Issue by ShaneMcNamara** [facebook/react-native#30818]
## Description
StatusBar.setHidden crashes on Android when passed undefined. e.g. `StatusBar.setHidden(undefined)`. I would expect this to have been evaluated as falsy, which seems to be the case in iOS. Looks like it also happens with `null`.

## React Native version:
`info Fetching system and libraries information...
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 1.09 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.2 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.3 - /Users/ShaneMcNamara/.rvm/gems/ruby-2.2.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6821437
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_222 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: https://github.com/expo/react-native/archive/sdk-39.0.2.tar.gz => 0.63.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
`

## Steps To Reproduce
Put this code in App.js: `StatusBar.setHidden(undefined)`
https://snack.expo.io/@ontraccr/grumpy-chocolates

**Comment by cortinico** [comment]
Closing as stale
