### ISSUE TITLE
React Native Android needs to target API level 30 before August 2021

### ISSUE THREAD

**Issue by imshreyansh** [facebook/react-native#30814]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
As per the new Google Play policy, all apps must target at least Android 11 (API 30) before August 2021.

More info: https://developer.android.com/distribute/play-policies

React Native is targeting API 29 as of today(v0.61.5), are there any plans to update the target SDK version?

--

## React Native version:
0.61.5

## Expected Results
React Native to target API 30 well before August 2021, so that all apps using React Native can adapt to it.

**Comment by dulmandakh** [comment]
SDK targeting will be updated in future versions, maybe in 0.65 or in patch update to 0.64. Thanks

**Comment by imshreyansh** [comment]
@dulmandakh And how can we update the target API level being on RN version 0.61.5 ?

**Comment by dulmandakh** [comment]
You can update it in your build.gradle file, but I won't recommend it because it may cause more pain than gain. IIRC, some libraries lacked support for SDK 29+ in RN 0.63 then we updated them in RN 0.63.4.

**Comment by imshreyansh** [comment]
@dulmandakh Is there any possible way to get the changelog or list of libraries updated for 0.63.4 ?

**Comment by dulmandakh** [comment]
it's not easy, but you can look into commits https://github.com/facebook/react-native/commits/master/ReactAndroid

**Comment by imshreyansh** [comment]
@dulmandakh I am trying to upgrade from 0.61 to 0.63 but it keeps on failing, i don't know why

**Comment by nemesisridiculii** [comment]
@imshreyansh I'm commig to this a bit late so hopefully you've already found it, but I have found the [React Native Upgrade Helper](https://react-native-community.github.io/upgrade-helper/) very useful. It will give you the diff in the template project between any two versions of react native.

**Comment by mandeep115** [comment]
@imshreyansh  the way i upgrade from any old version of RN is like this:
1) Create new app using RN cli

- Rename the app name and package name using `react-native-rename` 
2) Install latest version of all the packages

- Do Pod install and any other configurations
3) Copy res from android folder and any changes to build.gradle file to new app
4) Copy index.js and src folder to new app

- I have all the tsx/jsx  or ts/js files in a src folder.
Done!

**Important**
5) Rewrite the code with breaking changes

**Comment by loikfb** [comment]
@mandeep115 I think your way is better if you want to upgrade from a very old version of RN because your native iOS/Android projects will have more diff than a more recent one. This is why it's much straightforward to use [RN Upgrade helper](https://react-native-community.github.io/upgrade-helper/) for a project you want to regularly keep up to date and therefore target the latest sdk version.

**Comment by gustavolsilvano** [comment]
I upgraded my react native to version 0.64.1, but in my build.gradle the targetSdkVersion and compileSdkVersion was still 29. Do I need to manually change them to 30 in order to fullfil the requirement of API level 30?

**Comment by dulmandakh** [comment]
You can change the value

**Comment by rewieer** [comment]
Is this solved ? Because I still have this problem after upgrading to `0.64.2`. More precisely :
```
     Caused by: java.lang.IllegalStateException: Expected Android API level 21+ but was 30
        at okhttp3.internal.platform.AndroidPlatform.buildIfSupported(AndroidPlatform.java:238)
        at okhttp3.internal.platform.Platform.findPlatform(Platform.java:202)
        at okhttp3.internal.platform.Platform.<clinit>(Platform.java:79)
        at okhttp3.internal.platform.Platform.get(Platform.java:85) 
        at okhttp3.OkHttpClient.newSslSocketFactory(OkHttpClient.java:263) 
        at okhttp3.OkHttpClient.<init>(OkHttpClient.java:229) 
        at okhttp3.OkHttpClient$Builder.build(OkHttpClient.java:1015) 
        at com.facebook.react.devsupport.DevServerHelper.<init>(DevServerHelper.java:132) 
        at com.facebook.react.devsupport.DevSupportManagerBase.<init>(DevSupportManagerBase.java:171) 
        at com.facebook.react.devsupport.DevSupportManagerImpl.<init>(DevSupportManagerImpl.java:72) 
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343) 
        at com.facebook.react.devsupport.DevSupportManagerFactory.create(DevSupportManagerFactory.java:80) 
        at com.facebook.react.ReactInstanceManager.<init>(ReactInstanceManager.java:237) 
        at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:280) 
        at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:87) 
        at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:39) 
        at com.facebook.react.ReactDelegate.loadApp(ReactDelegate.java:104) 
        at com.facebook.react.ReactActivityDelegate.loadApp(ReactActivityDelegate.java:90) 
        at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:85) 
        at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:45) 
        at com.wekolo.MainActivity.onCreate(MainActivity.java:19) 
        at android.app.Activity.performCreate(Activity.java:8000) 
        at android.app.Activity.performCreate(Activity.java:7984) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
```

Is there something to update related to OKHTTP in RN ?
Here is my `build.gradle` file

```
apply plugin: "com.android.application"

project.ext.vectoricons = [
    iconFontNames: [ 'Entypo.ttf', 'FontAwesome.ttf', 'Ionicons.ttf' ]
]

apply from: "../../node_modules/react-native-vector-icons/fonts.gradle"

import com.android.build.OutputFile

project.ext.react = [
    entryFile: "index.js",
    enableHermes: true,
]

apply from: "../../node_modules/react-native/react.gradle"
apply from: "../../node_modules/@sentry/react-native/sentry.gradle"
apply from: "../../node_modules/react-native-code-push/android/codepush.gradle"

def enableSeparateBuildPerCPUArchitecture = false
def enableProguardInReleaseBuilds = false
def jscFlavor = 'org.webkit:android-jsc:+'
def enableHermes = project.ext.react.get("enableHermes", false);

android {
    ndkVersion rootProject.ext.ndkVersion
    compileSdkVersion rootProject.ext.compileSdkVersion
    buildToolsVersion rootProject.ext.buildToolsVersion

    dexOptions {
        javaMaxHeapSize "3g"
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        vectorDrawables.useSupportLibrary = true
        applicationId "com.wekolo"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 250
        versionName "6.3.0"
        multiDexEnabled true
        manifestPlaceholders = [
            appAuthRedirectScheme: 'app-mobile.wekolo.com'
        ]
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "x86", "x86_64", "armeabi-v7a", "arm64-v8a"
        }
    }
    signingConfigs {
            release {
                if (project.hasProperty('MYAPP_UPLOAD_STORE_FILE')) {
                    storeFile file(MYAPP_UPLOAD_STORE_FILE)
                    storePassword MYAPP_UPLOAD_STORE_PASSWORD
                    keyAlias MYAPP_UPLOAD_KEY_ALIAS
                    keyPassword MYAPP_UPLOAD_KEY_PASSWORD
                }
            }
        debug {
            if (project.hasProperty('MYAPP_UPLOAD_STORE_FILE')) {
                storeFile file(MYAPP_UPLOAD_STORE_FILE)
                storePassword MYAPP_UPLOAD_STORE_PASSWORD
                keyAlias MYAPP_UPLOAD_KEY_ALIAS
                keyPassword MYAPP_UPLOAD_KEY_PASSWORD
            }
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
        }
        debug {
            signingConfig signingConfigs.debug
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            // Example: versionCode 1 will generate 1001 for armeabi-v7a, 1002 for x86, etc.
            def versionCodes = ["armeabi-v7a": 1, "x86": 2, "arm64-v8a": 3, "x86_64": 4]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        defaultConfig.versionCode * 1000 + versionCodes.get(abi)
            }
        }
    }
}

dependencies {
    implementation project(':appcenter-crashes')
    implementation project(':appcenter-analytics')
    implementation project(':appcenter')

    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.facebook.react:react-native:+"  // From node_modules
    implementation 'com.facebook.android:facebook-android-sdk:4.34.0'
    implementation "com.google.android.gms:play-services-base:16.1.0"
    implementation 'me.leolin:ShortcutBadger:1.1.21@aar'
    implementation 'com.android.support:multidex:1.0.3'
    implementation 'androidx.appcompat:appcompat:1.1.0-rc01'
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0-alpha02'
    implementation 'com.facebook.fresco:animated-gif:2.0.0'
    implementation "com.facebook.fresco:animated-base-support:1.3.0"

    if (enableHermes) {
        def hermesPath = "../../node_modules/hermes-engine/android/";
        debugImplementation files(hermesPath + "hermes-debug.aar")
        releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
        implementation jscFlavor
    }
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)
apply plugin: 'com.google.gms.google-services'
```

**Comment by co-de** [comment]
> I upgraded my react native to version 0.64.1, but in my build.gradle the targetSdkVersion and compileSdkVersion was still 29. Do I need to manually change them to 30 in order to fullfil the requirement of API level 30?

@gustavolsilvano was it fixed with 0.64 upgrade. did it work after changing the sdk versions to 30?

**Comment by mowais-ac** [comment]
Help required, please let us know is it okay to change the version manually from 29 to 30?

**Comment by saadelsabahy** [comment]
app crash and metro bundler not loaded after upgrading targetsdk to 30

**Comment by mowais-ac** [comment]
after following the commit guide RN Upgrade helper, started receiving the following errors on building app for simulator
```
Execution failed for task ':app:mergeDebugNativeLibs'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform react-native-reanimated-65-jsc.aar (project :react-native-reanimated) to match attributes {artifactType=android-java-res}.

```

**Comment by rkostrab** [comment]
> after following the commit guide RN Upgrade helper, started receiving the following errors on building app for simulator
> 
> ```
> Execution failed for task ':app:mergeDebugNativeLibs'.
> > Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
>    > Failed to transform react-native-reanimated-65-jsc.aar (project :react-native-reanimated) to match attributes {artifactType=android-java-res}.
> ```
> 
> **Package.json**
> 
> ```
> "react": "17.0.2",
> "react-native": "0.65.0-rc.3",
> ```

The same problem. I've already [posted that to stackoverflow](https://stackoverflow.com/questions/68663941/react-native-0-65-targetsdk-30-android-build-is-failing-because-of-react-nativ)

**Comment by mowais-ac** [comment]
@rkostrab unfortunately not yet

**Comment by olegario96** [comment]
What is the target date to have this issue fixed?

**Comment by rkostrab** [comment]
> @rkostrab unfortunately not yet
> 
> do you have any idea, what will happen if we revert back to original and just change the
> 
> ```
> compileSdkVersion = 30 <- instead 29
> targetSdkVersion = 30 <- instead 29
> ```

I've already done that as a workaround and it's working fine.  See my stackoverflow post in "edit" part.

**Comment by NdaJunior** [comment]
@rkostrab I am thinking of making the same change. So to make sure I understand correctly, did you change both targetSdkVersion and compileSdkVersion both to 30 ? What about buildToolsVersion ?

**Comment by rkostrab** [comment]
@NdaJunior edit this block in project level gradle file like this
```
ext {
  buildToolsVersion = "30.0.2"
  minSdkVersion = 21
  compileSdkVersion = 30
  targetSdkVersion = 30
  ndkVersion = "20.1.5948944"
}
```

**Comment by NdaJunior** [comment]
@olegario96 I'm curious, why the thumbs down ?

**Comment by olegario96** [comment]
@NdaJunior because it's not working. I can't install the the app in a real device with that config.

**Comment by rkostrab** [comment]
@olegario96 I made these changes using version RN `0.64.1`. What version are you using now and number changes not working? Thanks

**Comment by NdaJunior** [comment]
@olegario96 @rkostrab I also made these changes using RN `0.64.0` and everything seems okay for me right now

**Comment by ttlenell** [comment]
@rkostrab curious if you did anything else than in the SO-post, I followed your steps and the app still crashes on launch for me. I'm on RN `0.64.2`

**Comment by rkostrab** [comment]
@ttlenell I am sorry but as you can see, some people can run it this way and some not. But you tried that using RN 0.64.2 - maybe this is why it's not working, I really don't know. Btw, in my case, I initiated my project purely right on version 0.64.1.

**Comment by ttlenell** [comment]
@rkostrab Hmm yes I do use moment, I have version 2.22.2 installed. Do you remember what version that worked for you?

**Comment by rkostrab** [comment]
For me `"moment": "2.18.1"` is working

**Comment by ttlenell** [comment]
@rkostrab No luck for me.. Guess I'll wait for stable 0.65 release :)

**Comment by JerichoGragasin** [comment]
Man, I don really want to necrobump but Im new to react-native and Im dealin with this issue right now :(

**Comment by dishantwalia** [comment]
https://github.com/facebook/react-native/issues/31725#issuecomment-901682370

**Comment by jeffngugi** [comment]
To solve this problem, you do not need to upgrade to the latest react-native version. For me I just edited file **android/build.gradle**

Change the files as below 
`buildscript {
    ext {
        buildToolsVersion = "30.0.2"
        minSdkVersion = 21
        compileSdkVersion = 30
        targetSdkVersion = 30
    }
......
`

This should work fine

**Comment by Michaelvons** [comment]
> To solve this problem, you do not need to upgrade to the latest react-native version. For me I just edited file **android/build.gradle**
> 
> Change the files as below `buildscript { ext { buildToolsVersion = **"30.0.2"**//this minSdkVersion = 21 compileSdkVersion = **30** this targetSdkVersion = **30** //this } ...... `
> 
> This should work fine

Very Correct !. Works like charm

**Comment by lomudev** [comment]
> To solve this problem, you do not need to upgrade to the latest react-native version. For me I just edited file **android/build.gradle**
> 
> Change the files as below `buildscript { ext { buildToolsVersion = **"30.0.2"**//this minSdkVersion = 21 compileSdkVersion = **30** this targetSdkVersion = **30** //this } ...... `
> 
> This should work fine

in my react native 0.63.3, there are some devices that can and some don't, most android 11 experience a force close when they first open apps, has anyone experienced the same thing?

**Comment by jamesholcomb** [comment]
@lomudev If you are still targeting 0.63, make sure to upgrade  to 0.63.4 (see comment from maintainer above).  This fixed the app closing on launch for me in release.

**Comment by anggraito** [comment]
> @NdaJunior edit this block in project level gradle file like this
> 
> ```
> ext {
>   buildToolsVersion = "30.0.2"
>   minSdkVersion = 21
>   compileSdkVersion = 30
>   targetSdkVersion = 30
>   ndkVersion = "20.1.5948944"
> }
> ```

i have been follow this instruction but still not run, then i put the local.properties in the ./android folder. Thats works for me without any exception. Thanks Nda

**Comment by whackur** [comment]
In my case, 

### android/build.gradle
```
    ext {
        buildToolsVersion = "30.0.2"
        minSdkVersion = 21
        compileSdkVersion = 30
        targetSdkVersion = 30
        ndkVersion = "20.1.5948944"
    }
```

### android/app/build.gradle
add 'okhttp' line in dependencies block 
```
dependencies {
    ........
    implementation"com.squareup.okhttp3:okhttp:4.9.0"
    ........
}
```

It works.

**Comment by pfreire013** [comment]
> #31725 (comment)

what's your RN version ?

**Comment by whackur** [comment]
> 

0.64.2

**Comment by jorgequintt** [comment]
If someone's still having problem with the app crashing on launch after changing targetSdkVersion and compileSdkVersion to 30, even after adding `implementation"com.squareup.okhttp3:okhttp:4.9.0"` in build.gradle dependencies, I found my app was crashing with this error

`Fatal Exception: java.lang.AssertionError: Method getAlpnSelectedProtocol not supported for object SSL socket over 'Socket'`

Adding this line below the `implementation"com.squareup.okhttp3:okhttp:4.9.0"` line fixed it:

`implementation "io.grpc:grpc-okhttp:1.32.2"`
