### ISSUE TITLE
Pushing to navigator from a child component

### ISSUE THREAD

**Issue by JosephShering** [facebook/react-native#3081]
I have a ListItem component that I would like to press and perform a push to navigator. How would I go about doing such a thing?
I tried passing navigator to child components but my memory usage spikes when I do so.

**Comment by brentvatne** [comment]
Hi there! Please post this kind of question on StackOverflow or Slack, as per our [Getting Help](https://github.com/facebook/react-native#getting-help) guide, thanks!
