### ISSUE TITLE
The spacing between lines within the same <Text> tag is not the same on ios

### ISSUE THREAD

**Issue by TranManhThang96** [facebook/react-native#30813]
When I use a japanese font, the spacing between lines within the same <Text> tag is not the same on ios. But on android, the spacing between lines is the same. Please help me.

Here is the snack link: https://snack.expo.io/@bochip96/github.com-tranmanhthang96-react-native-font-family

Here is my code:

``` <Text style={styles.boxNotificationTitle}>{item.title}</Text>```

```
boxNotificationTitle: {
    fontSize: 12,
    color: colors.colorTextFirst,
    lineHeight: 19,
    textAlign: 'justify',
  },
```

![Screen Shot 2021-01-29 at 11 05 35](https://user-images.githubusercontent.com/32483289/106230511-43276f00-6222-11eb-9da8-b20a0e87df3f.png)
![Screen Shot 2021-01-29 at 11 05 45](https://user-images.githubusercontent.com/32483289/106230515-4589c900-6222-11eb-9b56-c72f18b11039.png)

**Comment by ecreeth** [comment]
Maybe this can help you
![image](https://user-images.githubusercontent.com/20761166/106284103-23d81400-6219-11eb-8428-a4b5b6af6569.png)

**Comment by safaiyeh** [comment]
@TranManhThang96 thank you for the issue. Could you create a Snack that demonstrates the bug so it is easier to debug. Thanks!

**Comment by TranManhThang96** [comment]
> ⚠️	Missing Reproducible Example
> ℹ️	It looks like your issue is missing a reproducible example. Please provide a [Snack](https://snack.expo.io) or a repository that demonstrates the issue you are reporting in a [minimal, complete, and reproducible](https://stackoverflow.com/help/minimal-reproducible-example) manner.

This is link Snack: https://snack.expo.io/@bochip96/github.com-tranmanhthang96-react-native-font-family

**Comment by TranManhThang96** [comment]
> @TranManhThang96 thank you for the issue. Could you create a Snack that demonstrates the bug so it is easier to debug. Thanks!

This is link Snack: https://snack.expo.io/@bochip96/github.com-tranmanhthang96-react-native-font-family

**Comment by safaiyeh** [comment]
Thanks for the repo @TranManhThang96. I can notice the spacing on iOS significantly.

**Comment by fabriziobertoglio1987** [comment]
Do you still experience this issue? 

I have four years of experience maintaining facebook/react-native and I specialize in the Text and TextInput components. I currently have 58 [facebook/react-native PRs](https://github.com/facebook/react-native/pulls?q=is%3Apr+author%3Afabriziobertoglio1987+). 

If you still experience this issue, I will prepare a patched release with the fix.

Thanks a lot
