### ISSUE TITLE
Version code

### ISSUE THREAD

**Issue by wontone18** [facebook/react-native#30820]
I am facing a problem. Major issue is i am unable to trace this issue. Yesterday i released one version where my gradle version was 6.5 but that was crashing my app after releasing its version.

From my backup with gradlew 6.3 every thing working fine and when i am uploading a new version i am getting this error.

I already updated my version no and version code in build.gradle file.

![error](https://user-images.githubusercontent.com/10259774/106393557-c82aa800-641d-11eb-9407-d51093576042.png)

**Comment by dulmandakh** [comment]
This issue tracker is intended to track RN issues, not developer support. Please see details on Google Play then fix your app.
