### ISSUE TITLE
YogaKit/YogaKit.modulemap' not found Xcode 12.4

### ISSUE THREAD

**Issue by kubilaytural** [facebook/react-native#30821]
Description

I create a new app using react native. When I try to run the archive using Xcode I get the following error and the app doesn't archive.

 module map file '/Users/kubilaytural/Library/Developer/Xcode/DerivedData/passerMobileApp-fhpbfuxtqdjloddnafpzbplvrsxk/Build/Intermediates.noindex/ArchiveIntermediates/passerMobileApp/BuildProductsPath/Release-iphoneos/YogaKit/YogaKit.modulemap' not found

I have tried to google this but have been unable to find a way to fix it, is there any way this can be fixed?

(I have this problem with all my projects. Possibly related to Xcode)

    "react": "16.13.1",
    "react-native": "0.63.4",
    "react-native-navigation": "^7.8.4"

System:
macOS version: Big Sur 11.1
**Xcode version:** 12.4

<img width="867" alt="Screen Shot 2021-01-31 at 22 29 49" src="https://user-images.githubusercontent.com/23127307/106395550-db387a80-6413-11eb-89d7-15276692826f.png">

<img width="605" alt="Screen Shot 2021-01-31 at 22 30 52" src="https://user-images.githubusercontent.com/23127307/106395577-002ced80-6414-11eb-95e2-7891e91dc3ad.png">

**Comment by Vivek1907** [comment]
I think you get this issue when you are using a m1 mac. Are you using a M1 Mac?

**Comment by kubilaytural** [comment]
@Vivek1907 No. I'm not using M1 Mac.

**System**
<img width="292" alt="Screen Shot 2021-02-02 at 12 03 46" src="https://user-images.githubusercontent.com/23127307/106576903-bbf23800-654e-11eb-9bde-4877e3ea01e0.png">

**Comment by kubilaytural** [comment]
@Vivek1907 No. I'm not using M1 Mac.

<img width="243" alt="Screen Shot 2021-02-02 at 12 04 53" src="https://user-images.githubusercontent.com/23127307/106577005-e3490500-654e-11eb-9697-223fe0e3dc48.png">

**Comment by oliversieto** [comment]
Hi @kubilaytural

Try open the file *.xcworkspace instead *.xcodeproj, it worked for me.

**Comment by MaarioSevilla** [comment]
Tengo el mismo problema que tu, de momento no he encontrado soluciones, pensaba que quizá era error de node, de watchman pero no, en fin como solución temporal te sugiero compilar utilizando el SDK de ANDROID y su emulador o algún dispositivo móvil android, espero que este sea un error de Xcode y se solucione en futuras versiones.

**Comment by kubilaytural** [comment]
I was able to solve my problem by synchronizing the xcode development target and pod target version.
