### ISSUE TITLE
Fetch Request not working on android, but working on IOS

### ISSUE THREAD

**Issue by DylanRiden** [facebook/react-native#30827]
## Description
Hi, I have been developing with react native for awhile with Ios, but when it came to testing on android I get a "TypeError: Network request failed "error when trying to connect to my API, other APIs work but I just can't get mine to work, I raised an issue with expo and they couldn't figure it out and said it was probably an upstream react-native issue.

They thought it may be down to an Alt-Svc header

See https://github.com/expo/expo/issues/11679 for original issue 

Thanks In Advance :)

## React Native version:
Expo SDK 40

## Steps To Reproduce

1. Run this https://snack.expo.io/@dylander/7cfe32 on android
2. The request is inside AssetExample to my API that is failing
3. If you type the url to my API you will see the expected response

## Expected Results
The request response would outputted in the console, the catch runs and the error is outputted as an alert

## Snack, code example, screenshot, or link to a repository:
In steps to reproduce

**Comment by Aparus** [comment]
I faced the same issue. On web i handled it with installing 'cors' extension -- now it works on web.
But on android expo client I even doesn't see any error, though I use try/catch. I tried with promise, with async await, with fetch and axios. Nothing is working :(

**Comment by DylanRiden** [comment]
Hmm, the person trying in the other issue thought it could be to do with the "Alt-Svc" header, do you think it could be due to this??

**Comment by Aparus** [comment]
> Hmm, the person trying in the other issue thought it could be to do with the "Alt-Svc" header, do you think it could be due to this??

I don't know what to set for 'alt-svc'? I found one example `'alt-svc':''http/1.1= "http2.example.com:8001"; ma=7200' ` and tried it, but it doesn't help me. 

I have added to my api some headers, like 
```
("Access-Control-Allow-Origin: *");
("Access-Control-Allow-Methods: PUT, GET, POST");
("Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept");
```
And now fetch works in web without any chrome extensions for 'cors'.

**Comment by DylanRiden** [comment]
How do you host your api?? From your local network or a provider ?

**Comment by Aparus** [comment]
> How do you host your api?? From your local network or a provider ?

both. I have next.js server, on local for dev, and on vercel for production. They both are working well on web emulator. But doesn't work on expo android client (even without any error message, while I use `try{}catch(err){}`.  I also tried github public api. The same behavior.

**Comment by SohaibKtb** [comment]
this is happening for me also when calling https request, the cert is form goddady and my server is hosted on digital ocean cloud.

react-native: 0.63.4

**Comment by sc-mudsat** [comment]
Hi, any luck?
Facing the same issue, the app working fine on IOS but fetch fails in android giving "[TypeError: Network request failed]" error.

**Comment by Aparus** [comment]
> Hi, any luck? Facing the same issue, the app working fine on IOS but fetch fails in android giving "[TypeError: Network request failed]" error.

I didn't remember exactly what I did to solve, :) I suggest it was different headers of client request, and server response. 
Also I had some link at resource, that used something like geo position, and there was an error from different clients because of their settings.

**Comment by flyskywhy** [comment]
[fixed `TypeError: Network request failed` when upload file to http not https with Android debug builds](https://github.com/facebook/react-native/issues/33217#issuecomment-1159844475)

**Comment by ibraispotato** [comment]
i got the same issus did anyone got it?

**Comment by Tinkerstem** [comment]
Same issue here. Surprisingly it works on web perfectly, but not on mobile devices. Any success?
