### ISSUE TITLE
[TabBarIOS] Inactive tintColor

### ISSUE THREAD

**Issue by jsonmaur** [facebook/react-native#3083]
Would love the ability to customize the TabBar icon's inactive color from the default gray, similar to how you can set tintColor on TabBarIOS. Or even the ability to enable ```UIImageRenderingModeAlwaysOriginal``` on an image would be better than nothing. For a current workaround, I'm manually setting ```Render As: Original Image``` for each image set in ```Images.xcassets``` directly in Xcode.

**Comment by austin94** [comment]
@jdmaurer @christopherdro Is this feature still not implemented?  I'd be willing to take a shot at it if so.

**Comment by h3l** [comment]
I have find a way to solve this.
first, In js TabBarIOS.Item component, add the selectedIcon like this
`selectedIcon={require("image!tabbar_ic_massage_selected")}`

second, search RCTTabBarItem.m in Xcode,
change line 54 from 
`UIImage *image = [RCTConvert UIImage:_icon];`
to
`UIImage *image = [[RCTConvert UIImage:_icon] imageWithRenderingMode:UIImageRenderingModeAlwaysOriginal];`

i have some problem so i did not update to 0.19, i just in 0.13.2.

in the new version, it seems just change file RCTTabBarItem.m line 87 from
`self.barItem.image = _icon;`
to 
`self.barItem.image = [_icon imageWithRenderingMode:UIImageRenderingModeAlwaysOriginal];`
but i did not try it.

**Comment by atlas1119** [comment]
I'm manually setting Render As: Original Image for each image set in Images.xcassets directly in Xcode, But not become effective, why?

**Comment by urbanvikingr** [comment]
+1

**Comment by bsinc** [comment]
+1

**Comment by urbancvek** [comment]
I've created a Pull request that solves this problem right here #7264.

**Comment by urbancvek** [comment]
This issue is now resolved as my PR got accepted so it should probably be closed now.

**Comment by janicduplessis** [comment]
Thanks @urbancvek !
