### ISSUE TITLE
android: react native does not modify changes or react native does not update changes

### ISSUE THREAD

**Issue by adammartiniri** [facebook/react-native#30838]
this is my system info 

react native info
![react native info](https://user-images.githubusercontent.com/71458713/106788179-e08d0380-6665-11eb-99a0-226cc4c765ae.PNG)

system variable
![variable](https://user-images.githubusercontent.com/71458713/106788218-ebe02f00-6665-11eb-9619-b0e66409fa6d.PNG)

sdk platforms and sdk tools
![sdk-platforms](https://user-images.githubusercontent.com/71458713/106788275-fd293b80-6665-11eb-850f-7c1ce6be6d20.PNG)
![sdk-tools](https://user-images.githubusercontent.com/71458713/106788285-ff8b9580-6665-11eb-958e-61c9a3a82c8f.PNG)

my package.json
![pakage-json](https://user-images.githubusercontent.com/71458713/106788344-13cf9280-6666-11eb-81a7-5643ffe47916.PNG)

I downloaded react native a few time this 2 days and every times I came to this issues.

## first issue
i needed to change gradle in order to work 
in directory
android/gradle/wrapper/gradle-wrapper.properties
from: 
 distributionUrl=https\://services.gradle.org/distributions/gradle-6.2-all.zip
to:
distributionUrl=https\://services.gradle.org/distributions/gradle-6.3-all.zip
## not relaoding and changing 
after doing first step I could run react native in an emulator but no thing is ment to be changed so after digging in it , I found out that  i should make directory  named assets:
android/app/src/main/assets
then running this command  in command line:
npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/

to create  index.android.bundle in assets dir
after evey change I Should restart app and do that  in order to work

please help if you can

**Comment by ShahrozTanveer** [comment]
@adammartiniri did you managed to solve this problem?

**Comment by adammartiniri** [comment]
i do flutter it's nicer and less buggy .
