### ISSUE TITLE
Cant build react native from box in XCode: 'event2/event-config.h' file not found

### ISSUE THREAD

**Issue by 0xmikko** [facebook/react-native#30836]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Try to build clear image on iOS using XCode (Version 12.4 (12D4e)).

## React Native version:
"react-native": "0.63.4", also try 0.63.3

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Create an app using npx: `npx react-native init mob4 --template react-native-template-typescript`
2. Install pods: `cd ios && pod install`
3. Open XCode and press `Build`

## Expected Results
Normal stub app

## Snack, code example, screenshot, or link to a repository:
![Screenshot 2021-02-03 at 13 47 17](https://user-images.githubusercontent.com/26343374/106736359-67ba8700-6626-11eb-89bd-684bf6879b69.png)

**Comment by wooller** [comment]
Exact same for me

**Comment by k001** [comment]
same from my side:
```bash
ios/Pods/Headers/Public/libevent/event.h:44:10: 'event2/event-config.h' file not found

#include <event2/event-config.h>
```

**Comment by BG687** [comment]
Same for me

**Comment by ndevienne** [comment]
same for me. this morning, it was ok. but this evening, after "pod install" on an existing project, I had this line : "removing cocoalibevent" and build failed...

**Comment by oliversieto** [comment]
Same for me. I needed to enable google maps on iOS, I run pod install and I can't build anymore.

**Comment by Jorge-Luis-Rangel-Peralta** [comment]
Same here for me

**Comment by michaelvitello** [comment]
Same for me too

**Comment by Jorge-Luis-Rangel-Peralta** [comment]
Not even reverting to legacy build system or re-installing pods worked for me

**Comment by blaur** [comment]
Experiencing this exact error on our end.

**Comment by blaur** [comment]
For me I could get around it by:

1.  remove ios/Pods
2. cd ios && pod repo update
3. sudo gem install cocoapods
4. npx pod-install

**Comment by ahmetcbk** [comment]
By disabling Flipper in my Podfile it's worked !

**Comment by Jorge-Luis-Rangel-Peralta** [comment]
Disabling Flipper works like a charm.

Go to ios/Podfile

And comment this lines:

`
# Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
`

Then remove Pods and re-install them

**Comment by michaelvitello** [comment]
Hi all, I think all you are all doing for now is just deactivating Flipper... But what if you need it? I am trying a few things atm but it seems a lot of Flipper pod files include event.h from libevent. Its header files say that event.h from v1 is deprecated since libevent 2.0. We need to use include <event2/event.h> in all the Flipper dependencies using the libevent it seems. I will see if this may work and update here.

**Comment by Jorge-Luis-Rangel-Peralta** [comment]
The update is indeed needed to re-activate Flipper, if you do not require it then disable it, if you require it you will have to wait for the update

**Comment by michaelvitello** [comment]
Yes, that's the probably the best for now indeed

**Comment by meirinaldojunior** [comment]
Exact same for me :/

**Comment by michaelgmcd** [comment]
This issue is caused by an update to the "Flipper-Folly" pod-spec. If you'd like to keep Flipper enabled, you can override the version in your Podfile:
```
use_flipper!({ 'Flipper-Folly' => '2.3.0' })
```

**Comment by LuizFelipeh** [comment]
Thanks, Michael! That was exactly the issue (:

**Comment by meirinaldojunior** [comment]
Thanks! @michaelgmcd ! That's work for me.

**Comment by stothet** [comment]
@michaelgmcd that worked for me too!

If you're using configurations, this is what I did
`use_flipper!({ 'Flipper-Folly' => '2.3.0' }, configurations: ['Debug', 'Staging'])`

**Comment by Amanek93** [comment]
> This issue is caused by an update to the "Flipper-Folly" pod-spec. If you'd like to keep Flipper enabled, you can override the version in your Podfile:
> 
> ```
> use_flipper!({ 'Flipper-Folly' => '2.3.0' })
> ```

working, thanks!

**Comment by fakenickels** [comment]
Changing the iOS version under Deployment Info to 12.1 worked for me. Disabling Flipper (removing it from Podfile and from AppDelegate.m) works too.
![image](https://user-images.githubusercontent.com/1283200/106806870-3dc58c80-6647-11eb-8be8-560f6faa486d.png)

**Comment by BadtzMaru** [comment]
> This issue is caused by an update to the "Flipper-Folly" pod-spec. If you'd like to keep Flipper enabled, you can override the version in your Podfile:
> 
> ```
> use_flipper!({ 'Flipper-Folly' => '2.3.0' })
> ```

thanks, You did me a big favor!

**Comment by appasaheb4** [comment]
> This issue is caused by an update to the "Flipper-Folly" pod-spec. If you'd like to keep Flipper enabled, you can override the version in your Podfile:
> 
> ```
> use_flipper!({ 'Flipper-Folly' => '2.3.0' })
> ```

o great working thanks man.

**Comment by deepakverma4** [comment]
i'm facing ```library not found for -lPods-AppName``` error after updating "Flipper-Folly" pod-spec. Can anyone help me in resolving this please?

**Comment by pranathadoddy** [comment]
> This issue is caused by an update to the "Flipper-Folly" pod-spec. If you'd like to keep Flipper enabled, you can override the version in your Podfile:
> 
> ```
> use_flipper!({ 'Flipper-Folly' => '2.3.0' })
> ```

Thank you @michaelgmcd

**Comment by Theofilos-Chamalis** [comment]
I confirm the same problem as well. It is annoying how RN breaks every once in a while and small hacks like this are needed.

Thank you @michaelgmcd !

**Comment by oliveiraamanda91** [comment]
Thanks for the help!

**Comment by Cookizza** [comment]
I am using bare expo and none of the above is working for me.. where would i put this use_flipper command - anywhere in my podfile seems to break it

**Comment by itayseer** [comment]
regardless of the way you are registering the flipper 
either
```
def add_flipper_pods!(versions = {})
  versions['Flipper'] ||= '~> 0.37.0'
  versions['DoubleConversion'] ||= '1.1.7'
  versions['Flipper-Folly'] ||= '~> **2.3.0'**
```
or
`use_flipper!({ 'Flipper-Folly' => '**2.3.0**' })
`

**Comment by itayseer** [comment]
regardless of the way you are registering the flipper-folly just force this version 2.3.0
either
```
def add_flipper_pods!(versions = {})
  versions['Flipper-Folly'] ||= '~> 2.3.0'
```
or
`use_flipper!({ 'Flipper-Folly' => '2.3.0' })
`

**Comment by maxckelly** [comment]
> regardless of the way you are registering the flipper-folly just force this version 2.3.0
> either
> 
> ```
> def add_flipper_pods!(versions = {})
>   versions['Flipper-Folly'] ||= '~> 2.3.0'
> ```
> 
> or
> `use_flipper!({ 'Flipper-Folly' => '2.3.0' }) `

I'm getting the below when I try 

> ```
> def add_flipper_pods!(versions = {})
>   versions['Flipper-Folly'] ||= '~> 2.3.0'
> ```

```
[!] CocoaPods could not find compatible versions for pod "Flipper-Folly":
  In Podfile:
    Flipper-Folly (~> 2.3.0)

    FlipperKit/FBCxxFollyDynamicConvert (~> 0.33.1) was resolved to 0.33.1, which depends on
      Flipper-Folly (~> 2.1)

    FlipperKit/FlipperKitNetworkPlugin (~> 0.33.1) was resolved to 0.33.1, which depends on
      FlipperKit/Core (= 0.33.1) was resolved to 0.33.1, which depends on
        Flipper (~> 0.33.1) was resolved to 0.33.1, which depends on
          Flipper-RSocket (~> 1.0) was resolved to 1.3.0, which depends on
            Flipper-Folly (~> 2.5)

Specs satisfying the `Flipper-Folly (~> 2.3.0), Flipper-Folly (~> 2.1), Flipper-Folly (~> 2.5)` dependency were found, but they required a higher minimum deployment target.
```

**Comment by mitchldtn** [comment]
In PodFile comment out:

```
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
```

Save. Then `pod deintegrate` and `pod install`. 

Worked for me. If you need to use Flipper, people are having success in changing versions above.

**Comment by luiss2113-dev** [comment]
Mi solución fue dentro de la carpeta ios del proyecto ejecutar:

*Pod update.

Este removió la librería que al parecer genera problemas y procedí a compilar.

**Comment by HongYeseul** [comment]
> In PodFile comment out:
> 
> ```
>   use_flipper!
>   post_install do |installer|
>     flipper_post_install(installer)
>   end
> ```
> 
> Save. Then `pod deintegrate` and `pod install`.
> 
> Worked for me. If you need to use Flipper, people are having success in changing versions above.

Finally! It worked for me thank you!!

**Comment by 99uno** [comment]
Finally, I found the solution! [https://stackoverflow.com/a/66071245](url)

use_flipper!({ 'Flipper' => '0.74.0' })

**Comment by aprilmintacpineda** [comment]
I followed this https://fbflipper.com/docs/getting-started/react-native/, and it worked like a charm

**Comment by flutterq** [comment]
[[Solved] ‘event2/event-config.h’ file not found in React-Native](https://exerror.com/event2-event-config-h-file-not-found/)

**Comment by LonelyCpp** [comment]
upgrading flipper to `v0.74.0` fixed this issue for me 

```ruby
use_flipper!('Flipper' => '0.74.0')
```

**Comment by errorsolve** [comment]
[[Solved] ‘event2/event-config.h’ file not found in React-Native
](https://exerror.com/event2-event-config-h-file-not-found/)

**Comment by MrQureshi** [comment]
fixed this issue for me
`add_flipper_pods!('Flipper' => '0.74.0')`

**Comment by MrQureshi** [comment]
fixed this issue for me
`add_flipper_pods!('Flipper' => '0.74.0')`

**Comment by MrQureshi** [comment]
fixed this issue for me
`add_flipper_pods!('Flipper' => '0.74.0')`

**Comment by bansalakshay8** [comment]
> This issue is caused by an update to the "Flipper-Folly" pod-spec. If you'd like to keep Flipper enabled, you can override the version in your Podfile:
> 
> ```
> use_flipper!({ 'Flipper-Folly' => '2.3.0' })
> ```

That worked like a charm . Thanks.

**Comment by izooto-mobile-sdk** [comment]
I have facing this issue couple of day ,I got the solution 
remove the flipper from pod file or comment out 
use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
again pod install 
its working .

**Comment by sotomaque** [comment]
this works for me, but then after i add any packages to my project i face this problem all over again!

**Comment by sotomaque** [comment]
any suggestions?

**Comment by sotomaque** [comment]
specifically after installing react-native-vector-icons

**Comment by Cookizza** [comment]
@sotomaque

Update your `ios/Podfile` to target the specific version. Not in the lockfile but the actual Podfile.

`versions['Flipper-Folly'] ||= '2.3'`

Then run from main directory

`npx pod-install --repos-update && npm run start -- --reset-cache`

Then clean and rebuild from xcode.

**Comment by spyrado** [comment]
- go to your project folder
- open the ios folder
- open Podfile
     comment these lines:
```
use_flipper!
post_install do |installer|
  flipper_post_install(installer)
end
```

- go to the ios folder in the terminal and type pod update
- return to your project folder and type react-native start
- open a new terminal and type react-native run-ios
- that's it :)
          
  example below:
  
<img width="912" alt="Screen Shot 2021-02-18 at 03 30 56" src="https://user-images.githubusercontent.com/29312375/108315224-e02e5580-7199-11eb-93bc-0917f4603f85.png">


thanks @Jorge-Luis-Rangel-Peralta you helped a lot

**Comment by toxicsebastian** [comment]
> This issue is caused by an update to the "Flipper-Folly" pod-spec. If you'd like to keep Flipper enabled, you can override the version in your Podfile:
> 
> ```
> use_flipper!({ 'Flipper-Folly' => '2.3.0' })
> ```

Awesome, thanks!

**Comment by mgwedd** [comment]
> This issue is caused by an update to the "Flipper-Folly" pod-spec. If you'd like to keep Flipper enabled, you can override the version in your Podfile:
> 
> ```
> use_flipper!({ 'Flipper-Folly' => '2.3.0' })
> ```

This fix worked for me. Thanks!

**Comment by hbsaint** [comment]
> > This issue is caused by an update to the "Flipper-Folly" pod-spec. If you'd like to keep Flipper enabled, you can override the version in your Podfile:
> > ```
> > use_flipper!({ 'Flipper-Folly' => '2.3.0' })
> > ```
> 
> This fix worked for me. Thanks!

Also, remove `Pods/` & `Podfile.locl`, then run `npx pod-install`

**Comment by KotoriK** [comment]
For **Apple Silicon** users,
simply install ```libevent``` then add ```CPLUS_INCLUDE_PATH=/usr/local/``` before the start command.(if your homebrew is installed in x86_64 prefix) will solve this problem.

**Comment by studiocodeur** [comment]
> upgrading flipper to `v0.74.0` fixed this issue for me
> 
> ```ruby
> use_flipper!('Flipper' => '0.74.0')
> ```
> 
> this is also somehow related to cocoapods version. cocoapods version `1.10.1` + seems to solve most problems while lower versions install flipper dependencies incorrectly

This works for me!

**Comment by DanielWFrancis** [comment]
This breaks the [env setup here](https://reactnative.dev/docs/environment-setup) for me btw

**Comment by nntai** [comment]
Should read setup from flipper here and update to new version could fix this issue: https://fbflipper.com/docs/getting-started/react-native-ios

**Comment by dig9074vijay** [comment]
**For Apple Silicon (M1 Chips):**
This issue is caused by an update to the "Flipper-Folly" pod-spec. If you'd like to keep Flipper enabled, you can override the version in your Podfile:

use_flipper!({ 'Flipper-Folly' => '2.3.0' })
This fix worked for me. Thanks!
Also, remove Pods/ & Podfile.lock, then run npx pod-install
<img width="439" alt="Screenshot 2021-02-28 at 6 51 13 PM" src="https://user-images.githubusercontent.com/55308273/109419934-f0de9700-79f5-11eb-8219-fa1448e21929.png">

**Comment by iamnadhu** [comment]
> use_flipper!({ 'Flipper-Folly' => '2.3.0' })

Thanks @michaelgmcd, that worked fine!

**Comment by LTespoelstra** [comment]
> upgrading flipper to `v0.74.0` fixed this issue for me
> 
> ```ruby
> use_flipper!('Flipper' => '0.74.0')
> ```
> 
> this is also somehow related to cocoapods version. cocoapods version `1.10.1` + seems to solve most problems while lower versions install flipper dependencies incorrectly

0.75.1 is out now with some additional libevent fixes, and pinning to that in the Podfile worked, while letting the `npx react-native init` figure out the right/latest version wasn't pulling a newer version for the Podfile and I was stuck with 0.58 or whatever was baked into an old version of the template.

**Comment by nkigen** [comment]
Upgrading flipper to v0.78.0 worked for me (react-native 0.62.2)

**Comment by marengga** [comment]
In my case, I solved this by upgrading Flipper to v0.78.0

1. Made this change on ios/Podfile
`use_flipper!({'Flipper' => '0.78.0'})`
2. Make sure installed pods are up-to-date
`pod repo update`
`pod cd ios && pod install && cd ..`
3. Re-run application
`npx react-native run-ios`

**Comment by JiaoQiLong** [comment]
in my case, i also solved this problem by upgrading Flipper to v0.78.0
1. cd ios/Podfile 
   replace use_flipper! by use_flipper!({'Flipper' => '0.78.0'}) then pod install ,yarn ios ,it works!

**Comment by Kolvin** [comment]
Upgrading Flipper to v0.78.0 fixed my case too :+1:

**Comment by jeafgilbert** [comment]
> This issue is caused by an update to the "Flipper-Folly" pod-spec. If you'd like to keep Flipper enabled, you can override the version in your Podfile:
> 
> ```
> use_flipper!({ 'Flipper-Folly' => '2.3.0' })
> ```

After upgraded from 0.62.2 to 0.63.4, I got this issue. Fixed by upgrading Flipper-Folly to 2.3.0 in `ios/Podfile`. Thank you 🙏 

![image](https://user-images.githubusercontent.com/1263134/110249311-2bbd6d80-7fa8-11eb-8586-10710e984107.png)

**Comment by laogui** [comment]
Just update flipper is work.
`use_flipper!({'Flipper' => '0.79.0'})`

**Comment by parkcoop** [comment]
`use_flipper!({'Flipper' => '0.78.0'})` did work, but also updating Ruby to latest (3.0.0p0 (2020-12-25 revision 95aff21468)) and updating cocoapods made it so I didn't have to continue to repeat these above steps. Something to consider if your Ruby version is fairly old (mine was running on a 2019 build)

**Comment by rochapablo** [comment]
All attempts of change to `use_flipper!({'Flipper' => '*.*.*'})` did not work for me. It always fail the build with the same error https://github.com/facebook/react-native/issues/31181#issuecomment-801802805

**Comment by ssthil** [comment]
It worked for me.

My environment is:

"react": "16.13.1",
 "react-native": "0.63.2",

Update this change on ios/Podfile
use_flipper!({'Flipper' => '0.79.0'})

Make sure installed pods are up-to-date
```
pod repo update
cd ios && pod install && cd ..
```

And build it through Xcode -> Product -> Build

**Comment by SachinRajyaguru** [comment]
> For me I could get around it by:
> 
> 1. remove ios/Pods
> 2. cd ios && pod repo update
> 3. sudo gem install cocoapods
> 4. npx pod-install

this is not working

**Comment by SachinRajyaguru** [comment]
> It worked for me.
> 
> My environment is:
> 
> "react": "16.13.1",
> "react-native": "0.63.2",
> 
> Xcode: "12.4"
> 
> Update this change on ios/Podfile
> use_flipper!({'Flipper' => '0.79.0'})
> 
> Make sure installed pods are up-to-date
> 
> ```
> pod repo update
> cd ios && pod install && cd ..
> ```
> 
> And build it through Xcode -> Product -> Build

### this idea is working for me

**Comment by flutterq** [comment]
[[Solved] ‘event2/event-config.h’ file not found in React-Native
](https://exerror.com/event2-event-config-h-file-not-found/)

**Comment by mdlivingston** [comment]
I was able to fix this by updating all npm packages to their latest build with 'yarn upgrade --latest' and deleting the pods folder and reinstalling.

use_flipper! worked just fine after that.

**Comment by aswinaryal** [comment]
> This issue is caused by an update to the "Flipper-Folly" pod-spec. If you'd like to keep Flipper enabled, you can override the version in your Podfile:
> 
> ```
> use_flipper!({ 'Flipper-Folly' => '2.3.0' })
> ```
Hi, i am getting this issue while trying to update flipper-folly inside Podfile

[!] CocoaPods could not find compatible versions for pod "Flipper-Folly":
  In Podfile:
    Flipper-Folly (= 2.3.0)

    FlipperKit/Core (~> 0.75.1) was resolved to 0.75.1, which depends on
      Flipper (~> 0.75.1) was resolved to 0.75.1, which depends on
        Flipper-Folly (~> 2.5)

Specs satisfying the `Flipper-Folly (= 2.3.0), Flipper-Folly (~> 2.5)` dependency were found, but they required a higher minimum deployment target.

XCode: 12.5
React-Native: 0.64.0

**Comment by mattyx96** [comment]
> > This issue is caused by an update to the "Flipper-Folly" pod-spec. If you'd like to keep Flipper enabled, you can override the version in your Podfile:
> > ```
> > use_flipper!({ 'Flipper-Folly' => '2.3.0' })
> > ```
> 
> Hi, i am getting this issue while trying to update flipper-folly inside Podfile
> 
> [!] CocoaPods could not find compatible versions for pod "Flipper-Folly":
> In Podfile:
> Flipper-Folly (= 2.3.0)
> 
> ```
> FlipperKit/Core (~> 0.75.1) was resolved to 0.75.1, which depends on
>   Flipper (~> 0.75.1) was resolved to 0.75.1, which depends on
>     Flipper-Folly (~> 2.5)
> ```
> 
> Specs satisfying the `Flipper-Folly (= 2.3.0), Flipper-Folly (~> 2.5)` dependency were found, but they required a higher minimum deployment target.
> 
> XCode: 12.5
> React-Native: 0.64.0

same here

**Comment by ynoval** [comment]
Using latest versions works for me  
use_flipper!({'Flipper' => '0.91.1', 'Flipper-Folly' => '2.6.7', 'Flipper-RSocket' => '1.4.3'})

**Comment by amnbhr** [comment]
> Using latest versions works for me
> use_flipper!({'Flipper' => '0.91.1', 'Flipper-Folly' => '2.6.7', 'Flipper-RSocket' => '1.4.3'})

it's work for me

**Comment by shrmaky** [comment]
It worked for me with the latest flipper
use_flipper!({ 'Flipper' => '0.95.1', 'Flipper-Folly' => '2.6.7', 'Flipper-RSocket' => '1.4.3'  })

**Comment by dehengxu** [comment]
I meet this issue on 0.63.4 , and I fix it by setting up 'System header search path'  on some targets : FlipperKit, Flipper, Fliiper-Folly with value: "$(PODS_ROOT)/libevent/include" no-recursive
Another method you could upgrade to 0.64

**Comment by dehengxu** [comment]
Choose to use ReactNative you'd better master iOS/Android native development, cause RN is not stable at least development environment.

**Comment by riku99** [comment]
It worked for me.

use_flipper!({ 'Flipper' => '0.122.0' })
pod install --repo-update
