### ISSUE TITLE
Local Image can't load on iOS 14.* after archive

### ISSUE THREAD

**Issue by oliversieto** [facebook/react-native#30831]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
When I build in development mode all images are loaded, but when I upload app to TestFlight, my app does not show any local image. I already try on iOS simulators and physical device too, both load all images. I tried some solutions like: 

- patch-package
- [This Solution](https://github.com/facebook/react-native/issues/29279#issuecomment-658244428) - But the file is ok.

## React Native version:
System:
    OS: macOS 11.1
    CPU: (4) x64 Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz
    Memory: 189.65 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.14.10 - ~/.nvm/versions/node/v14.15.4/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2
      Android NDK: Not Found
  IDEs:
    Android Studio: 1.4 AI-141.2288178
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_73 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: ~0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Archive the app on app store
2. Release app to test on TestFlight
3. Local Images not loaded

## Expected Results
I wanted to see all local images loaded on iOS, because on Android works.

## screenshot:
On simulator
![Simulator Screen Shot - iPhone 11 - 2021-02-02 at 13 44 46](https://user-images.githubusercontent.com/29523854/106641372-8143cc00-655d-11eb-9572-b1bc2a613b2a.png)

On device development mode
![IMG_B6BFF093493D-1](https://user-images.githubusercontent.com/29523854/106642954-67a38400-655f-11eb-9c9d-0fddd6bf5fb8.jpeg)

On device TestFlight
![IMG_0114](https://user-images.githubusercontent.com/29523854/106641500-aa645c80-655d-11eb-84e5-0f78483a059b.PNG)

**Comment by pontusab** [comment]
Duplicated https://github.com/facebook/react-native/issues/30831
