### ISSUE TITLE
ActionSheetIOS.showShareActionSheetWithOptions options missing anchor in option type

### ISSUE THREAD

**Issue by rraczae** [facebook/react-native#30833]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
When calling `ActionSheetIOS.showShareActionSheetWithOptions` on an iPad I expect to pass an anchor to position the sheet. The type `ShareActionSheetIOSOptions` is missing that field, however if you pass it still uses it:

https://github.com/facebook/react-native/blob/0f4f91766339f2cf4189446d7d575493d33b4009/React/CoreModules/RCTActionSheetManager.mm#L236

It works but, I believe the type should be updated (or stated why it's not used).

## React Native version:
info Fetching system and libraries information...
System:
OS: macOS 10.15.6
CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Memory: 3.66 GB / 16.00 GB
Shell: 5.7.1 - /bin/zsh
Binaries:
Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
Yarn: 1.22.5 - /usr/local/bin/yarn
npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm
Watchman: 4.9.0 - /usr/local/bin/watchman
Managers:
CocoaPods: 1.9.3 - /usr/local/bin/pod
SDKs:
iOS SDK:
Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
Android SDK:
NOT RELEVANT
IDEs:
Android Studio: 4.0 AI-193.6911.18.40.6626763
Xcode: 12.0/12A7209 - /usr/bin/xcodebuild
Languages:
Java: 1.8.0_265 - /usr/bin/javac
Python: 2.7.16 - /usr/bin/python
npmPackages:
@react-native-community/cli: Not Found
react: ~16.11.0 => 16.11.0
react-native: ^0.62.2 => 0.62.2
react-native-macos: Not Found
npmGlobalPackages:
react-native: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. add a button
2. click on it and maintain get the node id of the event
3. pass it:

```
ActionSheetIOS.showShareActionSheetWithOptions(
  {
    url: uri,
    anchor: Number(e.nativeEvent.target),
  },
  (error: Error) => {
    console.log(error);
  },
  (success: boolean, shareMethod: string) => {
    console.log(success ? 'Succeeded! ' : 'Failed! ' && shareMethod);
  }
);
```
4. the sheet is anchored to the button

## Expected Results
I expect that anchor is part of the options interface and the documentation.

## Snack, code example, screenshot, or link to a repository:
-

**Comment by cortinico** [comment]
Closing as stale
