### ISSUE TITLE
[Android] setTimeout, setImmediate, requestAnimationFrame don't do anything

### ISSUE THREAD

**Issue by gilbox** [facebook/react-native#3084]
This is really weird, am I doing something wrong?

![android-timing](https://cloud.githubusercontent.com/assets/2136203/10127433/79ce8dd2-6556-11e5-8638-8072c663b728.gif)

This happens if I create a fresh project with `react-native init`

**Comment by ide** [comment]
The REPL is not a reliable way to schedule code since it doesn't pump the event loop. Can you try putting these same commands in your JS file (ex: index.js) and running them?

**Comment by gilbox** [comment]
Ah ok. I resorted to the console because my code wasn't executing. Now I added it to the render function of a fresh project:

```
var Foo = React.createClass({
  render: function() {
    
    console.log('rendering...')
    setTimeout(() => console.log('foo'), 10);
    setImmediate(() => console.log('bar'));
    requestAnimationFrame(() => console.log('baz'));

    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          Welcome to React Native!
        </Text>
        <Text style={styles.instructions}>
          To get started, edit index.android.js
        </Text>
        <Text style={styles.instructions}>
          Shake or press menu button for dev menu
        </Text>
      </View>
    );
  }
});
```

and in the console i get:

```
rendering...
bar
```

**Comment by ide** [comment]
Thanks for verifying!

**Comment by satya164** [comment]
Such code in console only seem to be executing when I interact with the app.

**Comment by ide** [comment]
Right... use the console to read output but not for input unless you can figure a clean way to pump the event loop (need the Chrome debugger to send a signal back to RN when the REPL receives input).

**Comment by antoaravinth** [comment]
@ide I couldn't able to understand why one needs to pump the event loop manually when running in debugger!
