### ISSUE TITLE
Android: Live regions

### ISSUE THREAD

**Issue by amarlette** [facebook/react-native#30857]
## Description
- This seems to exist as a prop, but is not functioning properly according to the documentation. 
- It only seems to exist on <View> and only seems to announce changes to the View's accessibilityLabel, not its descendant elements.

## React Native version:
v0.63

**Comment by blavalla** [comment]
I can no longer reproduce the issue here, this property seems to be functioning correctly.
Snack example link - https://snack.expo.io/9nyaxiJSK

I think we can close this one out.
