### ISSUE TITLE
Android: Position change (scroll)

### ISSUE THREAD

**Issue by amarlette** [facebook/react-native#30858]
## Description
THIS ISSUE IS DEPENDENT ON OTHER ISSUES & DOES NOT NEED TO BE WORKED ON INDIVIDUALLY

Dependent on these issues being closed:
- [ ] #30977 
- [x] #30839 

No components can be set as any collection role. 

## React Native version:
v0.63

**Comment by blavalla** [comment]
@amarlette, I think this task is sort of a no-op, as solving both #30977 and #30839 would resolve this automatically.

Basically, any view with the proper list role (added in #30839), and with collection info (added in #30977) will announce its position change on scroll automatically.

**Comment by amarlette** [comment]
Hmm I feel like keeping it open until those two are solved may be best since this functionality won't operate correctly til those are addressed so I don't feel I can close it.

I'll add language above that it is dependent on those issues but does not need to be worked on.

**Comment by fabriziobertoglio1987** [comment]
TalkBack support for ScrollView accessibility announcements (list and grid) [#33180](https://github.com/facebook/react-native/pull/33180) initially landed on 20th April 2022. Java API relanded with commit [a7bb9664009](https://github.com/facebook/react-native/commit/105a2397b6b187a9669ba1c028508a7bb9664009). JavaScript API relanded with commit [cbf53bcaf0c](https://github.com/facebook/react-native/commit/463af237539b98289c88e5b491c85cbf53bcaf0c), but reverted with commit [c2169c776e271ea](https://github.com/facebook/react-native/commit/3f8071d638d7c9cd25c0eb7f6c2169c776e271ea).
