### ISSUE TITLE
Android: Error state change (text inputs)

### ISSUE THREAD

**Issue by amarlette** [facebook/react-native#30859]
## Description
Error text not supported. 

Errors for form fields, while they can be displayed visually in many unique ways, need to have a strong association with the problematic field itself for accessibility.  Otherwise, any users who can't visually see the relation of the error to the field won't necessarily know which field is the problem.

This issue requires #30848 to be implemented first, and may get solved as part of that implementation.

## React Native version:
v0.63

## Expected Behavior
On focus of a form field with an error, the error will be announced by the screen reader after the field contents.  Upon changing a field and putting it into an error state, the error will immediately be announced by the screen reader.

## Android Details
On Android, this behavior is dictated by the "error" property of TextView.  It can be set with the `setError(errorString)` method, which will both visually display the error, as well as set up the right properties for accessibility.  

https://developer.android.com/reference/android/widget/TextView#setError(java.lang.CharSequence)

On the accessibility side, what is technically happening is that the "error" and "contentInvalid" properties of the AccessibilityNodeInfo is being set, and an accessibility event is being fired when the component goes into this error state.  Code pointer for the Android implementation here:

AccessibilityNodeInfo properties:
https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/widget/TextView.java;l=11887-11888?q=setError

Accessibility event firing: https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/widget/TextView.java;l=7284?q=setError

**Comment by blavalla** [comment]
@kacieb , just a heads up as it looks like you're working on #30848. This can likely be solved as part of that task (at least on Android), as this behavior should work automatically if you set the error prop on the TextView class.

For iOS this may require making a custom VoiceOver announcement when we get into an error state, and will likely require setting the error text in something like the AccessibilityValue to get it to read it upon focus of the input.

cc @gioneill for iOS specifics

**Comment by fabriziobertoglio1987** [comment]
I'm working on this issue https://github.com/facebook/react-native/issues/30848#issuecomment-1073659762

**Comment by fabriziobertoglio1987** [comment]
<details><summary>iOS - announce lastChar (not entire text) onChangeText and avoid multiple announcements (Fabric)</summary>
<p>

Commit https://github.com/fabriziobertoglio1987/react-native/commit/b53ed9d633d05699095bd917b531bc522243da91 fixes the following issues on iOS Fabric (apply [solution](https://github.com/facebook/react-native/pull/33468/commits/582b1e81177a114fb313b381a892f4fb6d430833) from Paper)

1)The error is announced, but not with the character onChangeText
2)The error is announced multiple times

Related https://github.com/fabriziobertoglio1987/react-native-notes/issues/12#issuecomment-1155982650 https://github.com/fabriziobertoglio1987/react-native-notes/issues/12#issuecomment-1154720995

<details><summary>sourcecode</summary>
<p>

```javascript
function AccessibilityErrorWithButtons(): React.Node {
  const [text, setText] = React.useState('');
  const [error, setError] = React.useState(null);
  const [accessibilityInvalid, setAccessibilityInvalid] = React.useState(false);
  return (
    <View>
      <RNTesterBlock>
        <TextInput
          accessibilityErrorMessage={error}
          accessibilityInvalid={accessibilityInvalid}
          onChangeText={newText => {
            if (newText === 'Error') {
              setError('this is the error');
              setAccessibilityInvalid(true);
            } else {
              setError('');
              setAccessibilityInvalid(false);
            }
            setText(newText);
          }}
          value={text}
          style={styles.default}
        />
        <Button
          onPress={() => {
            setError('This error is set with Button onPress callback');
          }}
          title="Press to set an accessibilityErrorMessage to a non-empty value"
        />
        <Button
          onPress={() => setAccessibilityInvalid(!accessibilityInvalid)}
          title={`Press to set accessibilityInvalid to ${
            accessibilityInvalid ? 'false' : 'true'
          }`}
        />
        <Button
          onPress={() => setError('')}
          title={`Press to set an empty error message`}
        />
      </RNTesterBlock>
    </View>
  );
}
```

</p>
</details>

<video src="https://user-images.githubusercontent.com/24992535/174241935-6d6e9a67-de99-4fc3-a30a-0d27f594a875.mp4" width="200" />

</p>
</details>

**Comment by fabriziobertoglio1987** [comment]
<details><summary>iOS - announces or does not announce the accessibilityError through Button onPress (not onChangeText) (Fabric)</summary>
<p>

<details><summary>sourcecode</summary>
<p>

```javascript
function AccessibilityErrorWithButtons(): React.Node {
  const [text, setText] = React.useState('');
  const [error, setError] = React.useState(null);
  const [accessibilityInvalid, setAccessibilityInvalid] = React.useState(false);
  return (
    <View>
      <RNTesterBlock>
        <TextInput
          accessibilityErrorMessage={error}
          accessibilityInvalid={accessibilityInvalid}
          onChangeText={newText => {
            if (newText === 'Error') {
              setError('this is the error');
              setAccessibilityInvalid(true);
            } else {
              setError('');
              setAccessibilityInvalid(false);
            }
            setText(newText);
          }}
          value={text}
          style={styles.default}
        />
        <Button
          onPress={() => {
            setError('This error is set with Button onPress callback');
          }}
          title="Press to set an accessibilityErrorMessage to a non-empty value"
        />
        <Button
          onPress={() => setAccessibilityInvalid(!accessibilityInvalid)}
          title={`Press to set accessibilityInvalid to ${
            accessibilityInvalid ? 'false' : 'true'
          }`}
        />
        <Button
          onPress={() => setError('')}
          title={`Press to set an empty error message`}
        />
      </RNTesterBlock>
    </View>
  );
}
```

</p>
</details>

<video src="https://user-images.githubusercontent.com/24992535/174289539-8c239a74-19af-405b-9152-034d3d8bd0c4.mp4" width="200" />



</p>
</details>

**Comment by fabriziobertoglio1987** [comment]
<details><summary>iOS - the error is announced with accessibilityInvalid true and does not clear after typing text (onChangeText) (Fabric)</summary>
<p>

<details><summary>sourcecode</summary>
<p>

```javascript
function AccessibilityErrorDoesNotClear(): React.Node {
  const [text, setText] = React.useState('');
  const [error, setError] = React.useState('');
  const [accessibilityInvalid, setAccessibilityInvalid] = React.useState(false);
  return (
    <View>
      <RNTesterBlock title="TextView without label">
        <Text>Set an error, change textinput value and then announce it.</Text>
        <TextInput
          accessibilityErrorMessage={error}
          accessibilityInvalid={accessibilityInvalid}
          value={text}
          onChangeText={newText => setText(newText)}
          style={styles.default}
        />
        <Text>
          The value of the accessibilityErrorMessage prop is{' '}
          {error.length > 0 ? error : 'empty error'}
        </Text>
        <Button
          onPress={() => {
            setError('This is an error');
          }}
          title="sets accessibilityErrorMessage to 'This is an error'"
        />
        <Button
          onPress={() => setAccessibilityInvalid(!accessibilityInvalid)}
          title={`Press to set accessibilityInvalid to ${
            accessibilityInvalid ? 'false' : 'true'
          }`}
        />
      </RNTesterBlock>
    </View>
  );
}
```

</p>
</details>

<video src="https://user-images.githubusercontent.com/24992535/174289754-168b7cb2-0520-4660-82a6-cbad5afc22d2.mp4" width="200" />

</p>
</details>

**Comment by fabriziobertoglio1987** [comment]
#### Android - TalkBack error does not clear error on the next typed character when using onChangeText
- The user types the word `erro` in the TextInput field. 
- The user then types the last character `r` , the JavaScript component triggers the error with the prop `accessibilityErrorAndroid`
- TalkBack announces the error `r, End of Field. Error: The new text is error`.
- The user types the next character `e` (errore) in the TextInput field. 

**Expected Result**:
Talkback announces `e, End of Field.`.

**Actual Result**:
TalkBack announces the error `e, Invalid input: the newText is error`

<details><summary>technical details of the solution</summary>
<p>

1) The method `maybeSetAccessibilityError` receives updates from fabric (c++).
     - The method is called when the prop screenreaderErrorAndroid is updated in the TextInput onChangeText callback
     - The method triggers the event `TYPE_WINDOW_CONTENT_CHANGED`

https://github.com/fabriziobertoglio1987/react-native-notes/blob/0513007362b419c8762a0ba9b954c231d6cb595b/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactEditText.java#L546-L555

2) `requestSendAccessibilityEvent` is invoked to fix the Issue [TalkBack error announcement done on next typed character with onChangeText][6], avoiding to announce the error message twice (on text "error" and next character "errore").

[6]: https://github.com/fabriziobertoglio1987/react-native-notes/issues/12#issuecomment-1096086753

https://github.com/fabriziobertoglio1987/react-native-notes/blob/0513007362b419c8762a0ba9b954c231d6cb595b/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactEditText.java#L164-L173

The solution is taken from the [TextView#setError][7] method which calls `notifyViewAccessibilityStateChangedIfNeeded`. I remain available to do further improvements. :pray: 

[7]: https://github.com/aosp-mirror/platform_frameworks_base/blob/1ac46f932ef88a8f96d652580d8105e361ffc842/core/java/android/widget/TextView.java#L7284-L7285

</p>
</details>

[1]: https://github.com/fabriziobertoglio1987/react-native/blob/994089cfbe106ac839a07b90cb4e851a3f0aa7e3/ReactCommon/react/renderer/components/textinput/androidtextinput/react/renderer/components/androidtextinput/AndroidTextInputShadowNode.cpp#L118 "fabric updateStateIfNeeded" 
[2]: https://user-images.githubusercontent.com/24992535/162907581-c03239e7-233a-4e24-b4e6-fbf493a69040.png "state update"
[3]: https://user-images.githubusercontent.com/24992535/162907581-c03239e7-233a-4e24-b4e6-fbf493a69040.png "screenshot -  the state sent from fabric"
[4]: https://user-images.githubusercontent.com/24992535/162907091-f2e779fe-91ea-45c8-b83f-ccc50af0a361.png "screenshot - the ScreenReader announcement is done before receiving state update from fabric"
[5]: https://user-images.githubusercontent.com/24992535/162903238-48a7eb45-74ff-460a-b9a8-29256347a2b1.png "screenshot - after receiving the state update from fabric"

<details><summary>click to open code used in the test</summary>
<p>

```javascript
function ErrorExample(): React.Node {
  const [text, setText] = React.useState('');
  const [error, setError] = React.useState(null);
  return (
    <>
      <Button onPress={() => setError('button')} title="Press to set error" />
      <Text>
        Type error in the below TextInput to display an error message.
      </Text>
      <TextInput
        screenreaderErrorAndroid={error}
        onBlur={() => setError('onBlur')}
        onEndEditing={() => setError('onEndEditing')}
        onChangeText={newText => {
          setText(newText);
          if (newText === 'error') {
            setError('the newText is: ' + newText);
          } else if (newText === 'empty') {
            setError('');
          } else if (newText === 'null') {
            setError(null);
          } else if (error !== 'onBlur') {
            setError(null);
          }
        }}
        value={text}
        style={styles.default}
      />
    </>
  );
}
```
</p>
</details>

<details><summary>video test case - error is announced on the next character - FAIL</summary>
<p>

<video src="https://user-images.githubusercontent.com/24992535/162851364-88c02366-0bbf-4174-bf5b-359c3247ab20.mp4" width="1000" />

</p>
</details>

<details><summary>video test case - error is announced 1 time - SUCCESS</summary>
<p>

<video src="https://user-images.githubusercontent.com/24992535/164378203-38cd5b01-c203-4ddc-abb0-124b2f4d7dd0.mp4" width="1000" />

</p>
</details>

**Comment by fabriziobertoglio1987** [comment]
<details><summary>iOS - </summary>
<p>

<details><summary>Sourcecode of example</summary>
<p>

```javascript
function AccessibilityErrorWithButtons(): React.Node {
  const [text, setText] = React.useState('');
  const [error, setError] = React.useState(null);
  const [accessibilityInvalid, setAccessibilityInvalid] = React.useState(false);
  return (
    <View>
      <RNTesterBlock>
        <TextInput
          accessibilityErrorMessage={error}
          accessibilityInvalid={accessibilityInvalid}
          onChangeText={newText => {
            setText(newText);
            if (newText === 'Error') {
              setError('the newText is: ' + newText);
              setAccessibilityInvalid(true);
            } else if (newText === 'null') {
              setAccessibilityInvalid(false);
            }
          }}
          value={text}
          style={styles.default}
        />
        <Button
          onPress={() => {
            setError('This error is set with Button onPress callback');
          }}
          title="Press to set an accessibilityErrorMessage to a non-empty value"
        />
        <Button
          onPress={() => setAccessibilityInvalid(!accessibilityInvalid)}
          title={`Press to set accessibilityInvalid to ${
            accessibilityInvalid ? 'false' : 'true'
          }`}
        />
        <Button
          onPress={() => setError('')}
          title={`Press to set an empty error message`}
        />
      </RNTesterBlock>
    </View>
  );
}
```
</p>
</details>

https://drive.google.com/file/d/1k8ex9CVOrAYyLKv3k5ZzTokerhVGnvbo/view?usp=sharing

</p>
</details>

**Comment by fabriziobertoglio1987** [comment]
<details><summary>CLICK TO OPEN TESTS RESULTS</summary>
<p>

<details><summary>Sourcecode of example</summary>
<p>

```javascript
function AccessibilityErrorWithButtons(): React.Node {
  const [text, setText] = React.useState('');
  const [error, setError] = React.useState(null);
  const [accessibilityInvalid, setAccessibilityInvalid] = React.useState(false);
  return (
    <View>
      <RNTesterBlock>
        <TextInput
          accessibilityErrorMessage={error}
          accessibilityInvalid={accessibilityInvalid}
          onChangeText={newText => {
            setText(newText);
            if (newText === 'Error') {
              setError('the newText is: ' + newText);
              setAccessibilityInvalid(true);
            } else if (newText === 'null') {
              setAccessibilityInvalid(false);
            }
          }}
          value={text}
          style={styles.default}
        />
        <Button
          onPress={() => {
            setError('This error is set with Button onPress callback');
          }}
          title="Press to set an accessibilityErrorMessage to a non-empty value"
        />
        <Button
          onPress={() => setAccessibilityInvalid(!accessibilityInvalid)}
          title={`Press to set accessibilityInvalid to ${
            accessibilityInvalid ? 'false' : 'true'
          }`}
        />
        <Button
          onPress={() => setError('')}
          title={`Press to set an empty error message`}
        />
      </RNTesterBlock>
    </View>
  );
}
```
</p>
</details>

https://drive.google.com/file/d/1kAHHrYKXP6tRFf7w1_rcxOFp3cCa2L_C/view?usp=sharing

</p>
</details>

**Comment by fabriziobertoglio1987** [comment]
<details><summary>iOS - accessibilityValue announces correctly with/out errorMessage set with onChangeText or with outside event (Fabric)</summary>
<p>

<details><summary>Sourcecode of example</summary>
<p>

```javascript
function AccessibilityErrorWithButtons(): React.Node {
  const [text, setText] = React.useState('');
  const [error, setError] = React.useState(null);
  const [accessibilityInvalid, setAccessibilityInvalid] = React.useState(false);
  return (
    <View>
      <RNTesterBlock>
        <TextInput
          accessibilityErrorMessage={error}
          accessibilityInvalid={accessibilityInvalid}
          onChangeText={newText => {
            setText(newText);
            if (newText === 'Error') {
              setError('the newText is: ' + newText);
              setAccessibilityInvalid(true);
            } else if (newText === 'null') {
              setAccessibilityInvalid(false);
            }
          }}
          value={text}
          style={styles.default}
        />
        <Button
          onPress={() => {
            setError('This error is set with Button onPress callback');
          }}
          title="Press to set an accessibilityErrorMessage to a non-empty value"
        />
        <Button
          onPress={() => setAccessibilityInvalid(!accessibilityInvalid)}
          title={`Press to set accessibilityInvalid to ${
            accessibilityInvalid ? 'false' : 'true'
          }`}
        />
        <Button
          onPress={() => setError('')}
          title={`Press to set an empty error message`}
        />
      </RNTesterBlock>
    </View>
  );
}
```
</p>
</details>



</p>
</details>

**Comment by fabriziobertoglio1987** [comment]
I moved PR https://github.com/facebook/react-native/pull/33468 Ready for Review. 
I remain available for any improvement. Thanks

**Comment by fabriziobertoglio1987** [comment]
PR was not merged. Could add this task to my todo
