### ISSUE TITLE
Android: High contrast text

### ISSUE THREAD

**Issue by amarlette** [facebook/react-native#30869]
## Description
Building any UI that has custom text rendering (graphs, charts, image composition, etc.) should respect the contrast of the text, which currently can't be detected.

## React Native version:
v0.63

**Comment by blavalla** [comment]
Google doesn't provide an API for this, so while it's technically possible to query using something like reflection, I don't think it's worth adding the hacky code required to the codebase, especially given its relatively limited use cases.

Closing out.
