### ISSUE TITLE
Android: Touch and hold delay

### ISSUE THREAD

**Issue by amarlette** [facebook/react-native#30867]
## Description
Building any UI that has a custom long-press gesture (not the standard system on) should use this setting to determine the proper length to wait to be considered pressed.

## React Native version:
v0.63

**Comment by blavalla** [comment]
Google doesn't provide an API for this, so while it's technically possible to query using something like reflection, I don't think it's worth adding the hacky code required to the codebase, especially given its relatively limited use cases.

Closing out.
