### ISSUE TITLE
Android: Cursor dwell timing

### ISSUE THREAD

**Issue by amarlette** [facebook/react-native#30868]
## Description
Apps don't often need to know whether or not auto-click is enabled, and its timing settings, unless they are building some fairly complex UI (common in games, or other totally custom experiences likely not build in React Native).

## React Native version:
v0.63

**Comment by blavalla** [comment]
Google doesn't provide an API for this, so while it's technically possible to query using something like reflection, I don't think it's worth adding the hacky code required to the codebase, especially given its relatively limited use cases.

Closing out.
