### ISSUE TITLE
Integrating with Existing Apps

### ISSUE THREAD

**Issue by sany620** [facebook/react-native#3086]
Install React Native Using CocoaPods ,
(JS_DIR=`pwd`/ReactComponent; cd Pods/React; npm run start -- --root $JS_DIR)
 Run error: cannot find XXX,index.ios.js,help!

**Comment by brentvatne** [comment]
Hi there! Please post this to StackOverflow -- it is not a bug as this works for many people, so you are likely just missing something :)
