### ISSUE TITLE
FlatList scrollToOffset not working when animated is false

### ISSUE THREAD

**Issue by arosisi** [facebook/react-native#30878]
## Description
I'm using a **FlatList** to implement a carousel of pages. I have quite a number of pages to show (40). I also implement a scrollable pagination bar with buttons for the pages that allows the user to click any button to go to the corresponding page. The bug I'm seeing is that if I'm at say page 40 and click the button for page 1, using `scrollToOffset({ offset: 0, animated: false })` does scroll to page 1 but page 1 is not rendered. Only when I drag the blank page slightly, page 1 is shown.

Here is a gif of an snack (link below) that has the bug. You can see that after I click the button on page 20 to go back to page 1, I see a blank page. Only when I slightly drag it, page 1 appears.

<img src="https://user-images.githubusercontent.com/19678855/106835156-d4547680-6664-11eb-8870-2c85f6c62958.gif" alt="scrollToOffset not working with no animation" width="200"/>

## React Native version:
I'm using expo v40.0.0, so React Native v0.63.3.

## Steps To Reproduce
I have reproduced the bug with the following snack:
[https://snack.expo.io/@arosisi/scrolltooffset-not-working-with-no-animation](https://snack.expo.io/@arosisi/scrolltooffset-not-working-with-no-animation)

## Expected Results
The page scrolled to is shown.

## Snack, code example, screenshot, or link to a repository:
[https://snack.expo.io/@arosisi/scrolltooffset-not-working-with-no-animation](https://snack.expo.io/@arosisi/scrolltooffset-not-working-with-no-animation)

**Comment by kenkirito** [comment]
can i work on this issue

**Comment by cortinico** [comment]
Closing as stale
