### ISSUE TITLE
Android: TextInput editable prop

### ISSUE THREAD

**Issue by amarlette** [facebook/react-native#30876]
## Description
editable="false" does not disable editing when Talkback is enabled, could cause security issues if apps are relying upon disabled inputs to not allow certain data to be changed.

## React Native version:
v0.63

**Comment by kacieb** [comment]
I actually wasn't able to reproduce this locally. This seems to work fine for me on both Android and iOS. 

Related issue (you can use the same component I linked in this issue to try to reproduce): https://github.com/facebook/react-native/issues/30938

**Comment by kacieb** [comment]
Assigning to @blavalla Who can maybe help with finding repro steps for this! I suppose it's possible this was fixed in between the time when you audited and now?

**Comment by kacieb** [comment]
This could also be a device specific issue or Android version specific issue - I tried and could not reproduce on a Samsung Galaxy S10 running Android version 10.

**Comment by blavalla** [comment]
I can also no longer reproduce this issue, so this may have been an issue that was fixed on Talkback's side, or may have been a mistake during the audit.  Either way, it seems to be working as intended.

From looking at the implementation on the Android side, everything seems correct (we are calling view.setEnabled(false) when editable={false}).
