### ISSUE TITLE
the color parser goes wrong

### ISSUE THREAD

**Issue by timzaak** [facebook/react-native#3088]
I use color '#FF434D' as  a view backgroundColor/borderColor/color, But it becomes '#FB686E' in the phone and simulator. Is there something wrong?

**Comment by astreet** [comment]
What platform? How are you verifying that it becomes #FB686E? Can you publish a sample app with repro to https://rnplay.org?

**Comment by timzaak** [comment]
I am sorry, I have made
```html
<TabBarIOS style={{opacity:0.8}}>
  <!--<View backgroundColor='...' ></View>-->
</TabBarIOS>
```
then, all the color changed.
