### ISSUE TITLE
Some vulnerabilities require your attention to resolve

### ISSUE THREAD

**Issue by ghadeeraqraa1992** [facebook/react-native#30881]
## Description
Node Fetch did not honor the size option after following a redirect, which means that when a content size was over the limit, a FetchError would never get thrown and the process would end without failure.

For most people, this fix will have a little or no impact. However, if you are relying on node-fetch to gate files above a size, the impact could be significant, for example: If you don't double-check the size of the data after fetch() has completed, your JS thread could get tied up doing work on a large file (DoS) and/or cost you money in computing.
Remediation
Upgrade to version 2.6.1 or 3.0.0-beta.9
Resources
https://github.com/node-fetch/node-fetch/security/advisories/GHSA-w7rc-rwvf-8q5r

all details under :https://www.npmjs.com/advisories/1556
## React Native version:
 react-native: 0.63.4 => 0.63.4 

## Steps To Reproduce
run npm command

## Expected Results
shouldn't see any severity vulnerabilities which is related to react-native or @react-native-community/cli 

## Screenshot:
<img width="591" alt="Screen Shot 2021-02-14 at 11 07 13 AM" src="https://user-images.githubusercontent.com/65596246/107872776-4757bb80-6eb5-11eb-82ec-723b25f8d3b5.png">

**Comment by safaiyeh** [comment]
Hi @ghadeeraqraa1992 please follow the issue template. Thanks!

**Comment by ghadeeraqraa1992** [comment]
> Hi @ghadeeraqraa1992 please follow the issue template. Thanks!
done

**Comment by chrisglein** [comment]
Has this been bumped in 0.64? I was looking at my 0.64 app and the lockfile was on 2.6.1.
