### ISSUE TITLE
Linking dependencies warning

### ISSUE THREAD

**Issue by rveruna** [facebook/react-native#30884]
## Description
Hi, 
I just updated to react 17.0.1 and I get a warning when running yarn 
 react-native@0.63.4" has incorrect peer dependency "react@16.13.1"
 
 My code is running fine, but I thought I let you know. Sorry if this is not allowed first time poster to issues here.

## React Native version:
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Memory: 3.37 GB / 15.79 GB
  Binaries:
    Node: 14.8.0 - C:\Users\VERONI~1\AppData\Local\Temp\yarn--1612454602387-0.51036183083059\node.CMD
    Yarn: 1.22.5 - C:\Users\VERONI~1\AppData\Local\Temp\yarn--1612454602387-0.51036183083059\yarn.CMD
    npm: 6.14.7 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 23, 25, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3
      System Images: android-29 | Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6953283
    Visual Studio: 16.7.30523.141 (Visual Studio Professional 2019)
  Languages:
    Java: 1.8.0_262 - /c/Program Files/OpenJDK/openjdk-8u262-b10/bin/javac
    Python: 2.7.18 - /c/Python27/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.1 => 17.0.1
    react-native: ^0.63.4 => 0.63.4
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
Done in 5.12s.

## Expected Results
I expect no warnings

**Comment by safaiyeh** [comment]
Hi @rveruna React 17 is not officially supported until 0.64, and at the time of writing this it is still in RC.
