### ISSUE TITLE
fetch() will send cookies even if told not to

### ISSUE THREAD

**Issue by iairsalem** [facebook/react-native#30885]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
This issue Tries to resurface issue #12956 
https://github.com/facebook/react-native/issues/12956#issuecomment-392775218
That seems to be happening even today.

You have to explicitly clear the cookies every time to avoid them being sent (even on the first request)

Even with credential: 'omit' header

## React Native version:
System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 1.55 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.19.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.7, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 27, 28, 29, 30
      Build Tools: 28.0.2, 28.0.3, 29.0.2, 29.0.3, 30.0.0, 30.0.2
      System Images: android-25 | Google APIs ARM 64 v8a, android-28 | Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
      Android NDK: 22.0.7026061
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 11.7/11E801a - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_275 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.0 => 17.0.0 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. send a fetch request, include credentials: 'omit' in the headers.
2. sit back and watch getting different results from what you tested before with postman....

## Expected Results
There should be away of making sure we a fetch request does not send any cookies.
(REST, stateless=no cookies)

## Snack, code example, screenshot, or link to a repository:

` 
                    let response = await fetch(ROUTES.serverURL + ROUTES.token.login, {
                        headers: {
                            "Authorization": "Basic " + base64.encode(username + ":" + password)
                        },
                        credentials: 'omit',
                        method: 'POST',
                    })
`

I feel that having to resort to:
`
CookieManager.clearAll()
`
is proof enough to make it an issue worth fixing.

Thanks!!

**Comment by safaiyeh** [comment]
Hi @iairsalem thanks for the issue. I agree, cookie support in core RN is missing a bunch of features. I help maintain react-native-cookies, let me know how the package can be improved.

**Comment by cortinico** [comment]
Closing as stale
