### ISSUE TITLE
Estou com um problema quando tento rodar npx react-native run-android no linux fiz todas as instalações dezenas de vezes

### ISSUE THREAD

**Issue by thiagobonfim0310** [facebook/react-native#30894]
Esse é o erro que aparece não consigo rodar nem no emulador nem no dispositivo fisico

info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 967 file(s) to forward-jetify. Using 8 workers...
info JS server already running.
info Installing the app...

FAILURE: Build failed with an exception.

* What went wrong:
Could not initialize class org.codehaus.groovy.runtime.InvokerHelper

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 492ms

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

npm ERR! code 1
npm ERR! path /home/thiago/Documentos/Test
npm ERR! command failed
npm ERR! command sh -c react-native "run-android"

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/thiago/.npm/_logs/2021-02-05T04_14_22_970Z-debug.log

**Comment by safaiyeh** [comment]
Hi @thiagobonfim0310 thanks for the issue. This seems to be an environment issue, checkout this Stackoverflow answer https://stackoverflow.com/questions/35000729/android-studio-could-not-initialize-class-org-codehaus-groovy-runtime-invokerhel if this does not work, I recommend opening another question
