### ISSUE TITLE
iOS: Support for “Large Content” Image Viewer

### ISSUE THREAD

**Issue by amarlette** [facebook/react-native#30892]
## Description
Referring to the [iOS Large Content Viewer](https://developer.apple.com/videos/play/wwdc2019/261/):
iOS Tab Bars can't grow with dynamic text, but the Large Content Viewer helps them to be seen by people with low vision.

## React Native version:
0.63

## Expected Results

In theory, there could be an image class, either a specific view/component or even possible within standard image views, that would correctly respond to the user's settings and invoke the content viewer under the correct circumstances.

## Android Details

There is no corollary for this feature on Android.

## iOS Details

There are several protocols related to the feature. The primary one to adopt would be the [UILargeContentViewerItem protocol](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjZ76GG9YPvAhWiJDQIHRXwCUEQFjAAegQIAhAD&url=https%3A%2F%2Fdeveloper.apple.com%2Fdocumentation%2Fuikit%2Fuilargecontentvieweritem&usg=AOvVaw36i9JGXbY3GQxVjpje3wn1)

**Comment by charlespowell1973** [comment]
Help
