### ISSUE TITLE
where android open source?

### ISSUE THREAD

**Issue by mickshu** [facebook/react-native#309]
where android open source?

**Comment by ericvicenti** [comment]
The Android project isn't as mature as iOS, and it is still very tightly integrated with FB's Android codebase.

We plan on releasing on Android later this year, so stay tuned!

http://facebook.github.io/react-native/

**Comment by mickshu** [comment]
expect

**Comment by vjeux** [comment]
Give us 6 months. http://facebook.github.io/react/blog/#when-is-react-native-android-coming

**Comment by Rudolph-Miller** [comment]
can't wait! :smile:

**Comment by ieugen** [comment]
+1, I hope it comes out soon :)

**Comment by vjeux** [comment]
Someone even made a countdown out of it :p
http://www.reactnativeandroid.com/

**Comment by Rudolph-Miller** [comment]
:laughing:
