### ISSUE TITLE
jcenter is shutting down which would fail android

### ISSUE THREAD

**Issue by pythys** [facebook/react-native#30902]
## Description
As [JFRog blog](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/) mentions jcenter which is the repository android is using is shutting down on May 1st and would stop accepting new versions soon. This means all react native versions old and new would crash and stop working.

## React Native version:
All Versions

## Steps To Reproduce
edit `android/build.gradle` and change `jcenter()` to any repository like `mavenCentral()`

## Expected Results
build should succeed,  however it fails because of missing dependencies.

**Comment by safaiyeh** [comment]
Thanks for the issue @pythys, this issue is better for https://github.com/react-native-community/discussions-and-proposals.

I believe @kelset did an initial investigation for the needs when Center goes down. Closing this issue for now.

**Comment by kelset** [comment]
The specific issue is this -> https://github.com/react-native-community/discussions-and-proposals/issues/331
