### ISSUE TITLE
Linking not working

### ISSUE THREAD

**Issue by Chandra-react** [facebook/react-native#30909]
I'm using react-native 0.63.3 version. Linking.canOpenURL("whatsapp://send?text=hello") not working.

if we try to open the above url its shows package is not install even though it is installed
this issue is only in android 30
<img width="295" alt="Screenshot 2021-02-08 at 12 04 38 PM" src="https://user-images.githubusercontent.com/60378569/107184915-77134900-6a07-11eb-9da6-bdd5b7d31ddb.png">
<img width="307" alt="Screenshot 2021-02-08 at 12 01 52 PM" src="https://user-images.githubusercontent.com/60378569/107184920-78dd0c80-6a07-11eb-90e0-ce14456f33f6.png">
<img width="315" alt="Screenshot 2021-02-08 at 12 01 34 PM" src="https://user-images.githubusercontent.com/60378569/107184924-7aa6d000-6a07-11eb-9690-6df6e81f99e2.png">

**Comment by franznkemaka** [comment]
Hello @chandrashekarioolabs.

I just try to reproduce the issue but it was working perfectly. 

### Attempt to reproduce

Create a default React Native app from scratch 
`
npx react-native init example
`

Update package.json to your current version
```diff
-"react-native": "0.63.4"
+"react-native": "0.63.3"
```

Open Android SDK Google Pixel 2 with WhatsApp installed.

Start app
`
yarn start
`

### Conclusion
The issue is not related to React Native directly as you can see. So please send us a link to a repo/ steps to reproduce.

Best regards!

**Comment by chandrashekarioolabs** [comment]
> Hello @chandrashekarioolabs.
> 
> I just try to reproduce the issue but it was working perfectly.
> 
> ### Attempt to reproduce
> Create a default React Native app from scratch
> `npx react-native init example`
> 
> Update package.json to your current version
> 
> ```diff
> -"react-native": "0.63.4"
> +"react-native": "0.63.3"
> ```
> 
> Open Android SDK Google Pixel 2 with WhatsApp installed.
> 
> Start app
> `yarn start`
> 
> ### Conclusion
> The issue is not related to React Native directly as you can see. So please send us a link to a repo/ steps to reproduce.
> 
> Best regards!
please try this part of code Linking.openURL("whatsapp://send?text=hello") in android 11. 

expected result it should open the what's app,

**Comment by franznkemaka** [comment]
Exactly @chandrashekarioolabs
I tested this using the following Android Simulator:
```
Pixel 2 API 30
Android 11.0 (Google Play)
```

**Comment by chandrashekarioolabs** [comment]
> Exactly @chandrashekarioolabs
> I tested this using the following Android Simulator:
> 
> ```
> Pixel 2 API 30
> Android 11.0 (Google Play)
> ```

Linking. canOpenURL("whatsapp://send?text=hello")

sorry can test this method once. I think openURL is working fine but before that if we try to check whether the app is installed or not using the above line of code then its returning false

**Comment by franznkemaka** [comment]
Hi @chandrashekarioolabs 

I just tried 

```js
if(Linking.canOpenURL("whatsapp://send?text=hello")){
     console.log("WhatsApp is installed and should work!")
}
```
And it works perfectly. 

I think what you should do is to create a repo/something with Expo Snack that can reproduce the issue. Unless it won't be easy to find out the real issue.

Have you tried running this on a real device with WhatsApp installed?

**Comment by chandrashekarioolabs** [comment]
> Hi @chandrashekarioolabs
> 
> I just tried
> 
> ```js
> if(Linking.canOpenURL("whatsapp://send?text=hello")){
>      console.log("WhatsApp is installed and should work!")
> }
> ```
> 
> And it works perfectly.
> 
> I think what you should do is to create a repo/something with Expo Snack that can reproduce the issue. Unless it won't be easy to find out the real issue.
> 
> Have you tried running this on a real device with WhatsApp installed?

thanks franznkemaka for your reply.
 onWhatsPress= async ()=>{
const res = await  Linking.canOpenURL("whatsapp://send?text=hello")
if(res){
console.log("WhatsApp is installed and should work!")
}else{
console.log("not working")
}
}

please check this part of code

**Comment by chandrashekarioolabs** [comment]
> > Hi @chandrashekarioolabs
> > I just tried
> > ```js
> > if(Linking.canOpenURL("whatsapp://send?text=hello")){
> >      console.log("WhatsApp is installed and should work!")
> > }
> > ```
> > 
> > 
> > And it works perfectly.
> > I think what you should do is to create a repo/something with Expo Snack that can reproduce the issue. Unless it won't be easy to find out the real issue.
> > Have you tried running this on a real device with WhatsApp installed?
> 
> thanks franznkemaka for your reply.
> onWhatsPress= async ()=>{
> const res = await Linking.canOpenURL("whatsapp://send?text=hello")
> if(res){
> console.log("WhatsApp is installed and should work!")
> }else{
> console.log("not working")
> }
> }
> 
> please check this part of code

**Comment by franznkemaka** [comment]
Hi @chandrashekarioolabs

I'm keen to know how you finally solved this!

**Comment by chandrashekarioolabs** [comment]
r

**Comment by franznkemaka** [comment]
ok I will test it async and let you know

**Comment by franznkemaka** [comment]
HI @chandrashekarioolabs 

I just tested what you suggested and it works perfectly fine.

Here are some suggestions to fix this issue ASAP!

1. Try to create a repo here on GitHub where you can reproduce the issue. If you can't reproduce the issue then it would be difficult for the collaborators of RN to find it either.

2. Try to run your app on a real device and find out if it works or not

3. Share your build.gradle & app/build.gradle to find out how your app is configured

Step 1 is very important!

Hope it helps!

**Comment by ausshadu** [comment]
For me,

`Linking.canOpenURL(url)` is returning false for all `tel:` and `mailto:` urls.

Android 11
ReactNative: 0.63.4

**Comment by tankers746** [comment]
https://stackoverflow.com/questions/62535856/intent-resolveactivity-returns-null-in-api-30

**Comment by tankers746** [comment]
This is to do with the new package visibility rules in Android 11.
You'll need to add <queries> to your AndroidManifest.xml

https://medium.com/androiddevelopers/package-visibility-in-android-11-cc857f221cd9

**Comment by franznkemaka** [comment]
@chandrashekarioolabs @ausshadu  What are you guys **android/build.gradle** ?

**Comment by franznkemaka** [comment]
Hello @chandrashekarioolabs @ausshadu,

I just checked it on Android SDK 30 and it doesn't work.
You guys didn't specify that. 

So the issue is related to Android SDK 30

**Comment by franznkemaka** [comment]
# Solution 

Add the following in your **android/app/src/main/AndroidManifest.xml**

```diff
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="com.example">

    <uses-permission android:name="android.permission.INTERNET" />

+    <queries>
+     <package android:name="com.whatsapp" />
+   </queries>

...
```


@tankers746 is of course right! 

Hope it works. @chandrashekarioolabs @ausshadu can you check it out?

**Comment by grit96** [comment]
This appears to be related to a new requirement when targeting Android SDK 30 - fixable by https://developer.android.com/training/basics/intents/package-visibility-use-cases#check-browser-available

**Comment by pushkar8723** [comment]
I also faced the same issue. However, found an alternative for WhatsApp. Instead of using `whatsapp://` URL, I used web URL `https://wa.me/?text=<url encoded text>`. In this case, user is prompted to select Whatsapp / Chrome to open the URL. However, even if the user selects Chrome, he is automatically redirected to WhatsApp (if WhatsApp is installed on the device) or is asked to download Whatsapp.

**Comment by kylanhurt** [comment]
For the record I had this issue when upgrading from API 29 to 30. I fixed it by using the following values in `android/build.gradle`:
```
    ext {
        buildToolsVersion = "30.0.2"
        minSdkVersion = 21
        compileSdkVersion = 30
        targetSdkVersion = 30
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:3.5.4")
        classpath('com.google.gms:google-services:4.3.8')
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.7.1'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
    ```
    
    Then adding the following clause to `android/app/src/main/AndroidManifest.xml`, as mentioned in an earlier comment:
    ```
    <queries>
      <package android:name="com.mydomain.myapp" />
    </queries>
    ```

As a Javascript developer this sort of stuff is confusing but I'm happy to be past the issue.

**Comment by Waqas-Jani** [comment]
I'm facing same issue for mailto and tel in android 11 (30). 
for whatsapp i added  
  <queries>
     <package android:name="com.whatsapp" />
  </queries>
in AndroidManifest.xml  file, and whatsapp working.
how does tel and mailto working for andorid 11 (30)?

**Comment by Waqas-Jani** [comment]
@franznkemaka what are the queries for tel and mailto in AndroidManifest.xml ?

**Comment by Waqas-Jani** [comment]
i found solution for tel and mailto for android 11
add this in AndroidManifest.xml file between "queries" tags
  <package android:name="com.google.android.gm" />
   <package android:name="com.google.android.dailer" />
  
working for gmail and google dailer app.

**Comment by veraldo** [comment]
> i found solution for tel and mailto for android 11 add this in AndroidManifest.xml file between "queries" tags package android:name="com.google.android.gm" package android:name="com.google.android.dialer" package write in tag
> 
> working for gmail and google dailer app.

Btw in order to avoid having to specify the email and dial apps, you can declare the intents instead:
```
      <intent>
        <action android:name="android.intent.action.SENDTO" />
        <data android:scheme="mailto" />
      </intent>
      <intent>
        <action android:name="android.intent.action.DIAL" />
      </intent>
```

**Comment by linhvovan29546** [comment]
My case Linking. canOpenURL("viber://chat?number=+380633639080"), it doesn't work on Samsung s10(android 11) device, it works fine on other android devices, for whatsapp it works fine. 
I also added  <package android:name="com.viber.voip" /> but it still doesn't work.
<img width="403" alt="image" src="https://user-images.githubusercontent.com/84692183/153341040-6f630cf6-913e-4c57-84af-e6f29338ba3c.png">
Someone please help me

**Comment by TatianaMatumoto** [comment]
If someone  can't insert this solution because after that android doesn't compile anymore: 

> # Solution
> Add the following in your **android/app/src/main/AndroidManifest.xml**
> 
> ```diff
> <manifest xmlns:android="http://schemas.android.com/apk/res/android"
>   package="com.example">
> 
>     <uses-permission android:name="android.permission.INTERNET" />
> 
> +    <queries>
> +     <package android:name="com.whatsapp" />
> +   </queries>
> 
> ...
> ```
> 
> @tankers746 is of course right!
> 
> Hope it works. @chandrashekarioolabs @ausshadu can you check it out?

Try upgrading _gradle_ like this: https://stackoverflow.com/a/67820136
Just upgrading _gradle_ i made that _queries_ work. 
i hope i saved you a few hours and stress in debugging 🥰

**Comment by iway1** [comment]
For expo users add this in `app.json`:

```
{
  android: {
    intentFilters: [
      {
        action: 'SENDTO',
        data: [
          {
            scheme: 'mailto',
          },
        ],
      },
      {
        action: 'DIAL',
      },
    ]
  }
}
```

**Comment by iway1** [comment]
here's an expo config plugin that does what @veraldo mentioned:

```js
// eslint-disable-next-line @typescript-eslint/no-var-requires
const { withAndroidManifest } = require('@expo/config-plugins')

function addIntentToQuery({ mod, intent }) {
  const r = { ...mod }
  if (!r.modResults.manifest.queries) {
    r.modResults.manifest.queries = [
      {
        intent: [],
      },
    ]
  } else if (!r.modResults.manifest.queries[0].intent?.[0]) {
    r.modResults.manifest.queries[0].intent = []
  }

  r.modResults.manifest.queries[0].intent.push({
    action: [
      {
        $: {
          'android:name': intent.actionName,
        },
      },
    ],
    ...(intent.dataScheme && {
      data: [
        {
          $: { 'android:scheme': intent.dataScheme },
        },
      ],
    }),
  })
  return r
}

const withAndroidMailPhoneQueries = (config) => {
  const r = withAndroidManifest(config, (mod) => {
    let modified = addIntentToQuery({
      mod,
      intent: {
        actionName: 'android.intent.action.SENDTO',
        dataScheme: 'mailto',
      },
    })
    modified = addIntentToQuery({
      mod,
      intent: {
        actionName: 'android.intent.action.DIAL',
      },
    })
    return modified
  })
  return r
}

module.exports = withAndroidMailPhoneQueries
```

then add in your `app.json` or `app.config.js`:

```js
  plugins: ['./config-plugins/withAndroidMailPhoneQueries']
```

**Comment by saddamhussaints392** [comment]
Modify this file **android/app/src/main/AndroidManifest.xml** file

<manifest ...>
    <queries>
        <intent>
            <action android:name="android.intent.action.VIEW" />
            <data android:scheme="https"/>
        </intent>
    </queries>
</manifest>

**Comment by AnshIcode** [comment]
hi @pushkar8723 @geraintwhite @kylanhurt @ausshadu @iway1 
I am using the react native version 0.71.3 and android v 14.0 , i am using Linking.openURL to open the terms and privacy policy in my app in android but it not working in android 14 but working fine in android v 11. any suggestions?? how can i fix it? if anyone can help me out this?
Thnks.
