### ISSUE TITLE
TextInput textContentType, autoCompleteType, autofill_hint inconsistencies

### ISSUE THREAD

**Issue by nasmuris** [facebook/react-native#30903]
## Description
There are two "autofill" text input fields, one for each platform, furthermore android is using exposed `autoCompleteType` which is quite limited now, not exposing all the native `AUTOFILL_HINTs` and internally is partially handled as `textContentType`
```
@ReactProp(name = "autoCompleteType")
--
658 | public void setTextContentType(ReactEditText view, @Nullable String autoCompleteType)

```
I took a look at both platforms and while there are some differencies, most of the autofill types can be used on both platforms.
Wouldn't be usefull to create a new field `autofillType` or use existing `textContentType` for both platforms (as this one supports all the iOS `UITextContentTypes` already and is not used on android therefore shouldn't cause any big difficulties/problems
### Overview of possibilies

iOS - UITextContentType | explanationIOS | textContentType | Android - HintConstants | explanationAndroid | autoCompleteType | Used HintConstant
-- | -- | -- | -- | -- | -- | --
URL | The expectation that a text input area specifies a URL. | URL |   |   |   |  
address |   |   | AUTOFILL_HINT_POSTAL_ADDRESS | autofilled with a postal address. | street-address |  
addressCity | The expectation that a text input area specifies a city name. | addressCity | AUTOFILL_HINT_POSTAL_ADDRESS_LOCALITY | autofilled with an address locality (city/town). |   |  
addressCityAndState | The expectation that a text input area specifies a city name with a state name. | addressCityAndState |   |   |   |  
addressExtended |   |   | AUTOFILL_HINT_POSTAL_ADDRESS_EXTENDED_ADDRESS | autofilled with auxiliary address details. |   |  
addressState | The expectation that a text input area specifies a state name. | addressState | AUTOFILL_HINT_POSTAL_ADDRESS_REGION | autofilled with a region/state. |   |  
countryName | The expectation that a text input area specifies a country or region name. | countryName | AUTOFILL_HINT_POSTAL_ADDRESS_COUNTRY | autofilled with a country name/code. |   |  
creditCardNumber | The expectation that a text input area specifies a credit card number. | creditCardNumber | AUTOFILL_HINT_CREDIT_CARD_NUMBER | autofilled with a credit card number. | cc-number |  
creditCardExpirationDate |   |   | AUTOFILL_HINT_CREDIT_CARD_EXPIRATION_DATE | autofilled with a credit card expiration date. | cc-exp |  
creditCardExpirationDay |   |   | AUTOFILL_HINT_CREDIT_CARD_EXPIRATION_DAY | autofilled with a credit card expiration day. |   |  
creditCardExpirationMonth |   |   | AUTOFILL_HINT_CREDIT_CARD_EXPIRATION_MONTH | autofilled with a credit card expiration month. | cc-exp-month |  
creditCardExpirationYear |   |   | AUTOFILL_HINT_CREDIT_CARD_EXPIRATION_YEAR | autofilled with a credit card expiration year. | cc-exp-year |  
creditCardSecurityCode |   |   | AUTOFILL_HINT_CREDIT_CARD_SECURITY_CODE | autofilled with a credit card security code. | cc-csc |  
emailAddress | The expectation that a text input area specifies an email address. | emailAddress | AUTOFILL_HINT_EMAIL_ADDRESS | autofilled with an email address. | email |  
familyName | The expectation that a text input area specifies a family name. | familyName | AUTOFILL_HINT_PERSON_NAME_FAMILY | autofilled with a person's last/family name. |   |  
fullStreetAddress | The expectation that a text input area specifies a street address that fully identifies a location. | fullStreetAddress |   |   |   |  
givenName | The expectation that a text input area specifies a first name. | givenName | AUTOFILL_HINT_PERSON_NAME_GIVEN | autofilled with a person's first/given name. |   |  
jobTitle | The expectation that a text input area specifies a job title. | jobTitle |   |   |   |  
location | The expectation that a text input area specifies a location such as a point of interest, an address, or another way to identify a location. | location |   |   |   |  
middleName | The expectation that a text input area specifies a middle name. | middleName | AUTOFILL_HINT_PERSON_NAME_MIDDLE | autofilled with a person's middle name. |   |  
middleNameInitial |   |   | AUTOFILL_HINT_PERSON_NAME_MIDDLE_INITIAL | autofilled with a person's middle initial. |   |  
name | The expectation that a text input area specifies a name. | name | AUTOFILL_HINT_PERSON_NAME | autofilled with a person's full name. | name | AUTOFILL_HINT_NAME (Obsolete)
namePrefix | The expectation that a text input area specifies a prefix or title, such as Dr. | namePrefix | AUTOFILL_HINT_PERSON_NAME_PREFIX | autofilled with a person's name prefix. |   |  
nameSuffix | The expectation that a text input area specifies a suffix, such as Jr. | nameSuffix | AUTOFILL_HINT_PERSON_NAME_SUFFIX | autofilled with a person's name suffix. |   |  
nickname | The expectation that a text input area specifies a nickname. | nickname |   |   |   |  
organizationName | The expectation that a text input area specifies an organization name. | organizationName |   |   |   |  
postalCode | The expectation that a text input area specifies a postal code. | postalCode | AUTOFILL_HINT_POSTAL_CODE | autofilled with a postal code. | postal-code |  
postalCodeExtended |   |   | AUTOFILL_HINT_POSTAL_ADDRESS_EXTENDED_POSTAL_CODE | autofilled with an extended ZIP/POSTAL code. |   |  
streetAddressLine1 | The expectation that a text input area specifies the first line of a street address. | streetAddressLine1 | AUTOFILL_HINT_POSTAL_ADDRESS_STREET_ADDRESS | autofilled with a street address. |   |  
streetAddressLine2 | The expectation that a text input area specifies the second line of a street address. | streetAddressLine2 |   |   |   |  
sublocality | The expectation that a text input area specifies a sublocality. | sublocality |   |   |   |  
telephoneNumber | The expectation that a text input area specifies a telephone number. | telephoneNumber | AUTOFILL_HINT_PHONE_NATIONAL | autofilled with a phone number without country code. |   |  
telephoneNumberFull |   |   | AUTOFILL_HINT_PHONE_NUMBER | autofilled with the user's full phone number with country code. | tel | AUTOFILL_HINT_PHONE (Obsolete)
telephoneNumberCountryCode |   |   | AUTOFILL_HINT_PHONE_COUNTRY_CODE | autofilled with a phone number's country code. |   |  
telephoneNumberDevice |   |   | AUTOFILL_HINT_PHONE_NUMBER_DEVICE | autofilled with the current device's phone number usually for Sign Up / OTP flows. |   |  
  |   |   |   |   |   |  
username | The expectation that a text input area specifies an account or login name. | username | AUTOFILL_HINT_USERNAME | autofilled with a username. | username |  
newUsername |   |   | AUTOFILL_HINT_NEW_USERNAME | interpreted as a newly created username for save/update. |   |  
password | The expectation that a text input area specifies a password. | password | AUTOFILL_HINT_PASSWORD | autofilled with a password. | password |  
newPassword | The expectation that a text input area specifies a new password. | newPassword | AUTOFILL_HINT_NEW_PASSWORD | interpreted as a newly created password for save/update. |   |  
oneTimeCode | The expectation that a text input area specifies a one-time code for delivery over SMS. | oneTimeCode | AUTOFILL_HINT_SMS_OTP | autofilled with a SMS One Time Password (OTP). |   |  
gender |   |   | AUTOFILL_HINT_GENDER | autofilled with a gender. |   |  
birthdayDay |   |   | AUTOFILL_HINT_BIRTH_DATE_DAY | autofilled with a birth day(of the month). |   |  
birthdayFull |   |   | AUTOFILL_HINT_BIRTH_DATE_FULL | autofilled with a full birth date. |   |  
birthdayMoth |   |   | AUTOFILL_HINT_BIRTH_DATE_MONTH | autofilled with a birth month. |   |  
birthdayYear |   |   | AUTOFILL_HINT_BIRTH_DATE_YEAR | autofilled with a birth year. |   |  

## React Native version:
0.63.4

**Comment by safaiyeh** [comment]
Thanks for the issue @nasmuris I have a PR open to address adding in the missing Android autofill types here: https://github.com/facebook/react-native/pull/28008, not ready for review yet tho.

The platform disparity between iOS and Android types should be looked at.

**Comment by nasmuris** [comment]
Hi @safaiyeh
I've managed to check out your PR finally and it looks fine, aside from [missing AUTOFILL_HINT_PERSON_NAME_FAMILY](https://github.com/facebook/react-native/pull/28008#issuecomment-683733888) is BUCK the only problem to solve before it's ready for review? 
How about the platform disparity, shouldn't this be solved by that PR too? From my point of view it's like more consistent to make those changes at once, not sure what would be the ideal solution tho, wether to bring up new prop, keep one of the existing 🤔

**Comment by safaiyeh** [comment]
@nasmuris yeah the BUCK issue is the last issue for it be ready for review. I haven’t had time to figure out the issue. I wouldn’t mind some help on that. And yeah it should be part of that PR

**Comment by vennila-dhanasekaran** [comment]
textContentType = "creditCardNumber" is not working in ios. Do we need to use some other value for ios ?

**Comment by safaiyeh** [comment]
Closing as the PR was merged in. @vennila-dhanasekaran please open a new issue with repro to get it looked at
