### ISSUE TITLE
SIGSEGV: Crash due to signal: SIGSEGV(SEGV_MAPERR)

### ISSUE THREAD

**Issue by gilbertl** [facebook/react-native#30901]
## Description
We're seeing several crash reports come in from our users via Instabug reporting. See attached

[Crash#2978.txt](https://github.com/facebook/react-native/files/5936408/Crash.2978.txt)

I understand the problem is hard to debug without some repro steps. For now, we'd just want to get some clues as to whether this might be

1/ an IOS issue
2/ a React Native issue
or
3/ an issue with our code

Thanks.

## React Native version:
System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.57 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.19.0 - /var/folders/45/g30y1xtj3xvd8k4lw2k3s0f80000gn/T/yarn--1612594678392-0.15728363453312966/node
    Yarn: 1.18.0 - /var/folders/45/g30y1xtj3xvd8k4lw2k3s0f80000gn/T/yarn--1612594678392-0.15728363453312966/yarn
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 12.3/12C33 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.8 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.0-rc.2 => 0.64.0-rc.2
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Frankly, I don't know how to reproduce it. We do not see any consistent patterns as to when the users are seeing this crash.

## Expected Results
Not crashing.

## Snack, code example, screenshot, or link to a repository:
N/A

**Comment by safaiyeh** [comment]
Hey @gilbertl thanks for the issue. We would need more information about the crash. Could you provide a repo or more information about how/when this happens

**Comment by jean-marc-cp** [comment]
I'm also seeing this it's a start up crash.
