### ISSUE TITLE
Setting opacity on Android causes underlying components to be visible

### ISSUE THREAD

**Issue by alex-mironov** [facebook/react-native#30904]
When opacity is used on the parent component, the underlying components inherit it and get semitransparent as well:

<img width="375" alt="Screenshot 2021-02-06 at 17 33 34" src="https://user-images.githubusercontent.com/2544767/107122642-8d06f980-68a1-11eb-9ed8-64cffdb49654.png">

Here is how components are getting composed: 
```
Container = styled.View`
  background-color: #fff;
  opacity: 0.5;
`

LineVertical = styled.View`
  background-color: #000;
  width: 2px;
  position: absolute;
  left: 18px;
  top: 0;
  bottom: 0;
`

DateIconContainer = styled.View`
  background-color: #fff;
`

<Container>
  <LineVertical />

  {/* ... */}

  <DateIconContainer />
</Container>
```
Is there any way to fix it? I saw in similar issues people reference to `needsOffscreenAlphaCompositing` but I'm rather confused by its vague description and cannot figure out where to put it. 

RN:
```
    "react-native": "0.61.4",
```

**Comment by safaiyeh** [comment]
Hey @alex-mironov thanks for the issue. Can you provide a repro of this bug on the latest RN version and from a scratch RN template

**Comment by huzaifaaak** [comment]
I encountered this issue aswell workaround for this would be to pass in the opacity in rgba and the child won't inherit the opacity.

**Comment by huzaifaaak** [comment]
Snack: https://snack.expo.io/DfvJ-4-i9
