### ISSUE TITLE
npx react-native run-ios and npx react-native run-android failed to compile

### ISSUE THREAD

**Issue by toscanoGithub** [facebook/react-native#30917]
After launching the iphone simulator and spinning the Building app... for few minutes 
I got this error at the end:
The following build commands failed:
        CompileC /Users/aitassouabdelkader/Library/Developer/Xcode/DerivedData/testApp-bcxbxzasgqtpznfdifpglceihhbg/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/Flipper.build/Objects-normal/x86_64/FlipperRSocketResponder.o /Users/aitassouabdelkader/Downloads/_clever-programmer/_projects/_react_projects/_mes_projets/testApp/ios/Pods/Flipper/xplat/Flipper/FlipperRSocketResponder.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Here is a a complete log :
0 verbose cli [
0 verbose cli   '/usr/local/bin/node',
0 verbose cli   '/usr/local/lib/node_modules/npm/bin/npm-cli.js',
0 verbose cli   'exec',
0 verbose cli   '--',
0 verbose cli   'react-native',
0 verbose cli   'run-ios'
0 verbose cli ]
1 info using npm@7.5.2
2 info using node@v14.15.4
3 timing config:load:defaults Completed in 2ms
4 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 1ms
5 timing config:load:builtin Completed in 1ms
6 timing config:load:cli Completed in 2ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:/Users/aitassouabdelkader/Downloads/_clever-programmer/_projects/_react_projects/_mes_projets/socialMedia/.npmrc Completed in 1ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:/Users/aitassouabdelkader/.npmrc Completed in 1ms
11 timing config:load:user Completed in 1ms
12 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 1ms
17 timing config:load:setEnvs Completed in 0ms
18 timing config:load Completed in 9ms
19 verbose npm-session f851aed9bb473f1b
20 timing npm:load Completed in 18ms
21 timing command:exec Completed in 15519ms
22 verbose stack Error: command failed
22 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
22 verbose stack     at ChildProcess.emit (events.js:315:20)
22 verbose stack     at maybeClose (internal/child_process.js:1048:16)
22 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
23 verbose pkgid socialMedia@0.0.1
24 verbose cwd /Users/aitassouabdelkader/Downloads/_clever-programmer/_projects/_react_projects/_mes_projets/socialMedia
25 verbose Darwin 20.3.0
26 verbose argv "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/bin/npm-cli.js" "exec" "--" "react-native" "run-ios"
27 verbose node v14.15.4
28 verbose npm  v7.5.2
29 error code 1
30 error path /Users/aitassouabdelkader/Downloads/_clever-programmer/_projects/_react_projects/_mes_projets/socialMedia
31 error command failed
32 error command sh -c react-native "run-ios"
33 verbose exit 1

I tried many things like checking if npm is up to date, removed node_modules, npm install and cd ios pod install
cleared the cache... all failed

Please help and thank you

**Comment by Xhuangniu** [comment]
I had the same problem

**Comment by Xhuangniu** [comment]
` npx react-native init AwesomeProject --version 0.62.0` Working for me
Look here: https://stackoverflow.com/questions/66062663/react-native-npx-react-native-run-ios-doesnt-work-after-initializing-the-proj

**Comment by slonv23** [comment]
I have just created a new project using `npx react-native init AwesomeProject` and have this issue

**Comment by Xhuangniu** [comment]
> I have just created a new project using `npx react-native init AwesomeProject` and have this issue

hi,Please specify the react-native version as 0.62.0

**Comment by erkanbaran** [comment]
> `npx react-native init AwesomeProject --version 0.62.0` Working for me
> Look here: https://stackoverflow.com/questions/66062663/react-native-npx-react-native-run-ios-doesnt-work-after-initializing-the-proj

It works for me! Thanks.

**Comment by ajay-bsoft** [comment]
No need to downgrade to 0.62.0 version. Check the solution at https://stackoverflow.com/a/66130332/3574669
