### ISSUE TITLE
Cannot create new project with react native cli

### ISSUE THREAD

**Issue by pulpfree** [facebook/react-native#30923]
## Description
When attempting to create a fresh react native project I'm unable to run the project from either Xcode or with the react native cli. The error I receive when running `npx react-native run-ios` is: 
`The following build commands failed:
	CompileC /Users/rondyck/Library/Developer/Xcode/DerivedData/client-budrlbueixzfnqhhsjuyaeanzjlx/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/Flipper-RSocket.build/Objects-normal/x86_64/TcpDuplexConnection.o /Users/rondyck/Sites/Universal/appv3.2/client/ios/Pods/Flipper-RSocket/rsocket/transports/tcp/TcpDuplexConnection.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)`

## React Native version:
System:
    OS: macOS 11.2
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 4.56 GB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.5.0 - ~/.nvm/versions/node/v12.5.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v12.5.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6821437
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.4 => 0.63.4
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce

1. `npx react-native init AwesomeProject`
2. `cd AwesomeProject && npx react-native start`

## Expected Results
I've run the `pod install` command in the ios directory with the following results

`cd ios
➜  ios pod install
Ignoring ffi-1.12.2 because its extensions are not built. Try: gem pristine ffi --version 1.12.2
Analyzing dependencies
Downloading dependencies
Generating Pods project
Integrating client project
Pod installation complete! There are 47 dependencies from the Podfile and 38 total pods installed.`

I'm running xcode v12.4 on OSX 11.2

This seems very unusual, I'm able to run my other RN apps created from previous versions of RN successfully and so I'm assuming my environment is properly setup.

Any help is appreciated.

Thanks,
Ron

**Comment by ryanoillataguerre** [comment]
I solved this by removing the flipper section from the Podfile in the starter project. I don't use Flipper, so worked perfectly for me after that.

**Comment by pulpfree** [comment]
Thanks @rachelnabors, I did discover that later, as well as installing (or re-installing) the pod gem. Unfortunately the typescript template still doesn’t compile, but I suppose I can work around that for now and will close this ticket.

**Comment by jonathans199** [comment]
Thank you this worked for me, however, might need to reopen this issue.  

Anyone creating a brand new `react-native` app with npx is encountering this issue.
