### ISSUE TITLE
[Docs] Create docs for capturing systrace traces for android

### ISSUE THREAD

**Issue by astreet** [facebook/react-native#3092]
Necessary to help people debug performance.

**Comment by brentvatne** [comment]
@astreet :+1: this would be great to see. I just merged a first pass on a performance guide (https://github.com/facebook/react-native/pull/3145) so we could either link to it from there or add it to the end of it

**Comment by astreet** [comment]
This will be live at https://facebook.github.io/react-native/docs/android-ui-performance.html in a few minutes (see https://github.com/facebook/react-native/commit/d2c50451f96f4ba80488ed1cb03e5823e7fb734e)

**Comment by ide** [comment]
Very helpful. Thanks @astreet!
