### ISSUE TITLE
Impossible to build archive xcode

### ISSUE THREAD

**Issue by FindelFof** [facebook/react-native#30932]
## Description

For some time now, I can not produce any archive I have encountered this eureur: File /Users/cynomedia/Library/Developer/Xcode/DerivedData/JDC-eeyocjvmxpowxzefeuzauukdrpgo/Build/Intermediates.noindex/ArchiveIntermuates/ProductsBathiveBathiveBath -iphoneos / jdc.app / main.jsbundle does not exist. This must be a bug with ', all my research to resolve this error has been unsuccessful. if anyone has ever had this problem help me

## My conf
System:
    OS: macOS 11.2.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 175.37 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.18.4 - /opt/local/bin/node
    Yarn: 1.22.5 - /opt/local/bin/yarn
    npm: 6.14.10 - /usr/local/bin/npm
    Watchman: 4.9.0 - /opt/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 14.0.2 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: ~0.63.4 => 0.63.4

**Comment by FindelFof** [comment]
Solved after performing nodejs update

**Comment by jacquesdev** [comment]
@FindelFof what did you upgrade it to?I have a similar nodejs version as you, so would love to know what ended up working for you.

I recently upgraded to npm7 and was wondering if it was related to that, but I noticed that you hadn't done that yet, so probably not that, but instead node.

**Comment by jacquesdev** [comment]
Turns out for me it was npm7, I guess because of how it is now very strict with dependencies.

**Comment by FindelFof** [comment]
> Turns out for me it was npm7, I guess because of how it is now very strict with dependencies. Going to wait a bit before upgrading

I switched to node 14.15 and npm install and it worked
