### ISSUE TITLE
No address associated with hostname

### ISSUE THREAD

**Issue by JF-23** [facebook/react-native#30931]
## Description
When I connect to a network though my app on Android 11 I seem to break the network connection of my app. This does not happen if I connect to said network using phone settings.

## React Native version:
62 and 63

## Steps To Reproduce
1. Connect to IoT device network from my rn app (IoT network has no internet connection)
2. Reconnect to WiFi access point automatically by disconnecting from IoT through app
3. Fetch and Axios requests fail by giving `No address associated with hostname` error until I forcefully restart app

## Expected Results
I should be able to connect to IoT device network and come back to WAP network and successfully make requests.

**Comment by Rekha16** [comment]
Hi I got same issue Unable to resolve host \"hostname\": No address associated with hostname in react native android device. help me to resolve it

**Comment by tnghia944** [comment]
.

**Comment by wesvh** [comment]
.
