### ISSUE TITLE
App keep closing on ios simulator after building successfully on Apple m1 chip

### ISSUE THREAD

**Issue by NicolasStuff** [facebook/react-native#30933]
## Description
Hi!

I recently ejected my app from expo to react-native-cli and i'm trying to run it on ios simulator but the app keep closing after splashscreen.

<img width="1013" alt="Capture d’écran 2021-02-10 à 18 35 49" src="https://user-images.githubusercontent.com/47270925/107548721-4d0c8300-6bcf-11eb-867a-bc28237f566c.png">

## React Native version:

System:
    OS: macOS 11.2.1
    CPU: (8) arm64 Apple M1
    Memory: 358.08 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.8.0 - /opt/homebrew/bin/node
    Yarn: Not Found
    npm: 6.14.11 - ~/Documents/Consultaway/Consultaway/node_modules/.bin/npm
    Watchman: 4.9.0 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_282 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: ~0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. eject expo app 
2. run it on ios simulator

**Comment by worldzb** [comment]
+1

**Comment by VadymBatryn** [comment]
+1
