### ISSUE TITLE
Picker Component doesn't disable click functionality when disabled

### ISSUE THREAD

**Issue by amarlette** [facebook/react-native#30946]
## Description
When using a screen reader the Picker component doesn't disable click functionality. Picker's own "enabled" property works correctly here.

This issue is covered in-depth by parent issue #30840, please check there for more details.

## React Native version:
0.63

**Comment by fabriziobertoglio1987** [comment]
Picker is deprecated https://reactnative.dev/docs/picker

**Comment by amarlette** [comment]
Closing this issue because the component has been deprecated.

Issue opened with respective repository react-native-picker/picker#215
