### ISSUE TITLE
Slider Component doesn't disable click functionality when disabled

### ISSUE THREAD

**Issue by amarlette** [facebook/react-native#30945]
## Description
When using a screen reader the Slider component doesn't disable click functionality. Also, if the slider's disabled prop is also set, it actually reverses it and enables it again!

This issue is covered in-depth by parent issue #30840, please check there for more details.

## React Native version:
0.63

**Comment by fabriziobertoglio1987** [comment]
Slider is deprecated https://reactnative.dev/docs/slider

**Comment by amarlette** [comment]
Thank you @fabriziobertoglio1987. Checking to see if this can be closed due to it being a deprecated component.

**Comment by amarlette** [comment]
Closing this issue because the component has been deprecated
