### ISSUE TITLE
Pressable Component doesn't disable click functionality when disabled

### ISSUE THREAD

**Issue by amarlette** [facebook/react-native#30949]
## Description
When using a screen reader the Pressable component doesn't disable click functionality

## React Native version:
0.63

**Comment by kacieb** [comment]
Resolved by [this commit](https://github.com/facebook/react-native/commit/1c7d9c8046099eab8db4a460bedc0b2c07ed06df).

**Comment by huzaifaaak** [comment]
@kacieb does this fix it for other components that are using pressable under the hood.

**Comment by kacieb** [comment]
> @kacieb does this fix it for other components that are using pressable under the hood.

Hey @huzaifaaak! Yes it should fix it as long as the component is correctly passing in Pressable's `disabled` prop when the component is disabled.
