### ISSUE TITLE
Fails to start default IOS project

### ISSUE THREAD

**Issue by blerimj** [facebook/react-native#3094]
I updated all the libraries to the most recent stable version and the app won't run in xCode IOS emulator.
Screenshot:
![image](https://cloud.githubusercontent.com/assets/182351/10136369/6594ac7c-65f4-11e5-81c7-0dd376409515.png)
Console:
Sep 28 15:19:35  OpenPropertyFinder[1807] <Error>: CGContextSaveGState: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Sep 28 15:19:35  OpenPropertyFinder[1807] <Error>: CGContextTranslateCTM: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Sep 28 15:19:35  OpenPropertyFinder[1807] <Error>: CGContextRestoreGState: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
2015-09-28 15:19:35.863 [error][tid:com.facebook.React.JavaScript] 'Error: undefined is not an object (evaluating \'require(\'NativeModules\').UIManager.AndroidDrawerLayout.Constants\')\n stack: \n  <unknown>  index.ios.bundle:23977\n  require    index.ios.bundle:254\n  <unknown>  index.ios.bundle:1472\n  require    index.ios.bundle:254\n  <unknown>  index.ios.bundle:1401\n  require    index.ios.bundle:254\n  require    index.ios.bundle:200\n  <unknown>  index.ios.bundle:52314\n URL: http://localhost:8081/index.ios.bundle\n line: 23977\n message: undefined is not an object (evaluating \'require(\'NativeModules\').UIManager.AndroidDrawerLayout.Constants\')'
2015-09-28 15:19:35.954 [info][tid:com.facebook.React.JavaScript] 'Running application "OpenPropertyFinder" with appParams: {"rootTag":1,"initialProps":{}}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF'
2015-09-28 15:19:35.957 [error][tid:com.facebook.React.JavaScript] 'Error: Invariant Violation: Application OpenPropertyFinder has not been registered. This is either due to a require() error during initialization or failure to call AppRegistry.registerComponent.\n stack: \n  runApplication  index.ios.bundle:45072\n  __callFunction  index.ios.bundle:5563\n  <unknown>       index.ios.bundle:5499\n  guard           index.ios.bundle:5452\n  <unknown>       index.ios.bundle:5499\n  <unknown>       index.ios.bundle:5496\n  perform         index.ios.bundle:7041\n  batchedUpdates  index.ios.bundle:16526\n  batchedUpdates  index.ios.bundle:6344\n  <unknown>       index.ios.bundle:5495\n  guard           index.ios.bundle:5452\n  processBatch    index.ios.bundle:5494\n URL: http://localhost:8081/index.ios.bundle\n line: 2023\n message: Invariant Violation: Application OpenPropertyFinder has not been registered. This is either due to a require() error during initialization or failure to call AppRegistry.registerComponent.'

**Comment by ptmt** [comment]
Same here. I just made temporary rollback to 0.11.2

**Comment by pennsong** [comment]
@ptmt Same here too, but could you please tell me how to rollback to 0.11.2 ? thanks in advance

**Comment by bichotll** [comment]
Same over here! I could not solve it doing the rollback in my case though. 
*Or at least the way I've done it.

**Comment by twalling** [comment]
Update `package.json` in your project so that the react-native dependency is 0.11.2.

`"react-native": "0.11.2"`

Then run `npm install`.

**Comment by twalling** [comment]
@bichotll how did you rollback? It worked for me and you can double check that it actually rolled back to 0.11.2 by checking `node_modules/react-native/package.json`. It should read `"version": "0.11.2"` up at the top of the file.

**Comment by bichotll** [comment]
Solved. I didn't delete node_modules folder.

tnx @twalling !

**Comment by BuNAZz** [comment]
how to solved this :(

**Comment by theodorton** [comment]
```
# In your app folder
$ npm install react-native@0.11.2 --save
```

**Comment by blerimj** [comment]
Thanks @twalling. Thanks @theodorton

**Comment by BuNAZz** [comment]
thank you so much @theodorton

**Comment by tigershen23** [comment]
same issue :/ thanks @theodorton!

**Comment by tmaximini** [comment]
here too this error with 0.11.3

**Comment by philikon** [comment]
Seems like the packager isn't being called with the right (or any, for that matter) parameter to set the correct module blacklist: https://github.com/facebook/react-native/blob/master/packager/packager.js#L293

**Comment by philikon** [comment]
@mkonicek How is the `.android.js` vs. `.ios.js` blacklist supposed to work in the OSS port? Am I missing something or is it simply not hooked up?

**Comment by theodorton** [comment]
@philikon `.android.js` and `.ios.js` works out of the box here on 0.11.2

**Comment by ide** [comment]
DrawerLayoutAndroid.ios.js and friends exist in master but didn't get copied over to 0.11-stable. I'll give it another shot.

**Comment by philikon** [comment]
That would do it! Hah, it didn't occur to me to check the 0.11-stable branch for those files.

**Comment by ide** [comment]
0.11.4 is out.

**Comment by philikon** [comment]
(FWIW, this is now the second time that I can remember where a freshly baked RN release wouldn't produce a compileable/runnable new project. In this case it even broke existing projects. The thing is, it's not 100% straightforward to test this from a GitHub checkout. So I think if we could add an option to `react-native init` that would allow us to specify a non-npm source for the `react-native` module, it'd be trivial to test the first setup experience every time, even automate it in CI...)

**Comment by ide** [comment]
Yeah that'd be really helpful. Some env var like `REACT_NATIVE_PACKAGE_ID` that can be set to `facebook/react-native@0.11-stable` (just gets passed to `npm install`) could work. Opened https://github.com/facebook/react-native/issues/3102.

**Comment by ide** [comment]
@blerimj could you try 0.11.4? Sorry for the issue!

**Comment by blerimj** [comment]
@ide Thanks!

**Comment by tmaximini** [comment]
@ide thanks, it works fine with 0.11.4

**Comment by yelled3** [comment]
@ide I'm using `0.11.4` and I'm still getting:
```
Sep 29 11:49:18  Grove[68919] <Error>: CGContextSaveGState: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Sep 29 11:49:18  Grove[68919] <Error>: CGContextTranslateCTM: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Sep 29 11:49:18  Grove[68919] <Error>: CGContextRestoreGState: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
```

when I set `CG_CONTEXT_SHOW_BACKTRACE` on, I get:

```
Sep 29 11:52:42  Grove[69049] <Error>: CGContextSaveGState: invalid context 0x0. Backtrace:
	  <-[UIStatusBarItemView updateContentsAndWidth]+33>
	   <-[UIStatusBarItemView initWithItem:data:actions:style:]+477>
	    <+[UIStatusBarItemView createViewForItem:withData:actions:foregroundStyle:]+134>
	     <-[UIStatusBarLayoutManager _createViewForItem:withData:actions:]+163>
	      <-[UIStatusBarLayoutManager _prepareEnabledItemType:withEnabledItems:withData:actions:itemAppearing:itemDisappearing:]+36
	       <-[UIStatusBarLayoutManager prepareEnabledItems:withData:actions:]+92>
	        <-[UIStatusBarForegroundView _setStatusBarData:actions:animated:]+797>
	         <-[UIStatusBarForegroundView setStatusBarData:actions:animated:]+332>
	          <__51-[UIStatusBar _prepareToSetStyle:animation:forced:]_block_invoke+360>
	           <+[UIView(Animation) performWithoutAnimation:]+65>
	            <-[UIStatusBar _prepareToSetStyle:animation:forced:]+866>
	             <-[UIStatusBar _requestStyleAttributes:animationParameters:forced:]+391>
	              <-[UIStatusBar requestStyle:animationParameters:forced:]+437>
	               <-[UIStatusBar requestStyle:animated:forced:]+90>
	                <-[UIStatusBar _evaluateServerRegistration]+250>
	                 <__45-[UIView(Hierarchy) _postMovedFromSuperview:]_block_invoke+590>
	                  <-[UIView(Hierarchy) _postMovedFromSuperview:]+544>
	                   <-[UIView(Internal) _addSubview:positioned:relativeTo:]+1967>
	                    <-[UIStatusBarWindow setStatusBar:]+288>
	                     <-[UIApplication _createStatusBarWithRequestedStyle:orientation:hidden:]+340>
	                      <-[UIApplication _runWithMainScene:transitionContext:completion:]+950>
	                       <-[UIApplication workspaceDidEndTransaction:]+188>
	                        <-[FBSSerialQueue _performNext]+192>
	                         <-[FBSSerialQueue _performNextFromRunLoopSource]+45>
	                          <__CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__+17>
	                           <__CFRunLoopDoSources0+556>
	                            <__CFRunLoopRun+867>
	                             <CFRunLoopRunSpecific+488>
	                              <-[UIApplication _run]+402>
	                               <UIApplicationMain+171>
	                                <main+111>
	                                 <start+1>
Sep 29 11:52:42  Grove[69049] <Error>: CGContextTranslateCTM: invalid context 0x0. Backtrace:
	  <-[UIStatusBarItemView updateContentsAndWidth]+33>
	   <-[UIStatusBarItemView initWithItem:data:actions:style:]+477>
	    <+[UIStatusBarItemView createViewForItem:withData:actions:foregroundStyle:]+134>
	     <-[UIStatusBarLayoutManager _createViewForItem:withData:actions:]+163>
	      <-[UIStatusBarLayoutManager _prepareEnabledItemType:withEnabledItems:withData:actions:itemAppearing:itemDisappearing:]+36
	       <-[UIStatusBarLayoutManager prepareEnabledItems:withData:actions:]+92>
	        <-[UIStatusBarForegroundView _setStatusBarData:actions:animated:]+797>
	         <-[UIStatusBarForegroundView setStatusBarData:actions:animated:]+332>
	          <__51-[UIStatusBar _prepareToSetStyle:animation:forced:]_block_invoke+360>
	           <+[UIView(Animation) performWithoutAnimation:]+65>
	            <-[UIStatusBar _prepareToSetStyle:animation:forced:]+866>
	             <-[UIStatusBar _requestStyleAttributes:animationParameters:forced:]+391>
	              <-[UIStatusBar requestStyle:animationParameters:forced:]+437>
	               <-[UIStatusBar requestStyle:animated:forced:]+90>
	                <-[UIStatusBar _evaluateServerRegistration]+250>
	                 <__45-[UIView(Hierarchy) _postMovedFromSuperview:]_block_invoke+590>
	                  <-[UIView(Hierarchy) _postMovedFromSuperview:]+544>
	                   <-[UIView(Internal) _addSubview:positioned:relativeTo:]+1967>
	                    <-[UIStatusBarWindow setStatusBar:]+288>
	                     <-[UIApplication _createStatusBarWithRequestedStyle:orientation:hidden:]+340>
	                      <-[UIApplication _runWithMainScene:transitionContext:completion:]+950>
	                       <-[UIApplication workspaceDidEndTransaction:]+188>
	                        <-[FBSSerialQueue _performNext]+192>
	                         <-[FBSSerialQueue _performNextFromRunLoopSource]+45>
	                          <__CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__+17>
	                           <__CFRunLoopDoSources0+556>
	                            <__CFRunLoopRun+867>
	                             <CFRunLoopRunSpecific+488>
	                              <-[UIApplication _run]+402>
	                               <UIApplicationMain+171>
	                                <main+111>
	                                 <start+1>
Sep 29 11:52:42  Grove[69049] <Error>: CGContextRestoreGState: invalid context 0x0. Backtrace:
	  <-[UIStatusBarItemView updateContentsAndWidth]+33>
	   <-[UIStatusBarItemView initWithItem:data:actions:style:]+477>
	    <+[UIStatusBarItemView createViewForItem:withData:actions:foregroundStyle:]+134>
	     <-[UIStatusBarLayoutManager _createViewForItem:withData:actions:]+163>
	      <-[UIStatusBarLayoutManager _prepareEnabledItemType:withEnabledItems:withData:actions:itemAppearing:itemDisappearing:]+36
	       <-[UIStatusBarLayoutManager prepareEnabledItems:withData:actions:]+92>
	        <-[UIStatusBarForegroundView _setStatusBarData:actions:animated:]+797>
	         <-[UIStatusBarForegroundView setStatusBarData:actions:animated:]+332>
	          <__51-[UIStatusBar _prepareToSetStyle:animation:forced:]_block_invoke+360>
	           <+[UIView(Animation) performWithoutAnimation:]+65>
	            <-[UIStatusBar _prepareToSetStyle:animation:forced:]+866>
	             <-[UIStatusBar _requestStyleAttributes:animationParameters:forced:]+391>
	              <-[UIStatusBar requestStyle:animationParameters:forced:]+437>
	               <-[UIStatusBar requestStyle:animated:forced:]+90>
	                <-[UIStatusBar _evaluateServerRegistration]+250>
	                 <__45-[UIView(Hierarchy) _postMovedFromSuperview:]_block_invoke+590>
	                  <-[UIView(Hierarchy) _postMovedFromSuperview:]+544>
	                   <-[UIView(Internal) _addSubview:positioned:relativeTo:]+1967>
	                    <-[UIStatusBarWindow setStatusBar:]+288>
	                     <-[UIApplication _createStatusBarWithRequestedStyle:orientation:hidden:]+340>
	                      <-[UIApplication _runWithMainScene:transitionContext:completion:]+950>
	                       <-[UIApplication workspaceDidEndTransaction:]+188>
	                        <-[FBSSerialQueue _performNext]+192>
	                         <-[FBSSerialQueue _performNextFromRunLoopSource]+45>
	                          <__CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__+17>
	                           <__CFRunLoopDoSources0+556>
	                            <__CFRunLoopRun+867>
	                             <CFRunLoopRunSpecific+488>
	                              <-[UIApplication _run]+402>
	                               <UIApplicationMain+171>
	                                <main+111>
	                                 <start+1>

```

**Comment by yelled3** [comment]
@ide this seems to be related to https://forums.developer.apple.com/thread/13683

**Comment by ide** [comment]
It's a bug on Apple's side. Just ignore it or turn on UIViewController based status bar appearance if it bothers you (but will break StatusBarIOS which is why we are leaving it on).

**Comment by Code-DJ** [comment]
I am still getting this error. Changed mine to "react-native": "^0.11.4"
rm -rf node_modules
npm install
Verified in node_modules/react-native/package.json "version": "0.11.4"

What am I missing? Thanks!

**Comment by Code-DJ** [comment]
See the following error in debugger:

Error: Cannot read property 'Constants' of undefined
 stack: 
  <unknown>  index.bundle:24621
  require    index.bundle:254
  <unknown>  index.bundle:2135
  require    index.bundle:254
  <unknown>  index.bundle:1399
  require    index.bundle:254
  require    index.bundle:200
  <unknown>  index.bundle:53232

RCTNetworking.sendRequest was called with 6 arguments, but expects 2

**Comment by jaygarcia** [comment]
^---- sometimes this is the best solution. :( 

I went from the  0.6.0 project structure to 0.11.4 and completely started from scratch and hand-migrated my artifacts. Works like a champ.
