### ISSUE TITLE
TouchableOpacity Component doesn't disable click functionality when disabled

### ISSUE THREAD

**Issue by amarlette** [facebook/react-native#30951]
## Description
When using a screen reader the TouchableOpacity component doesn't disable click functionality.

This issue is covered in-depth by parent issue #30840, please check there for more details.

## React Native version:
0.63

**Comment by chakrihacker** [comment]
I would like to pick this

**Comment by amarlette** [comment]
Thank you @chakrihacker for your contribution to improving React Native Accessibility!
