### ISSUE TITLE
TouchableHighlight Component doesn't disable click functionality when disabled

### ISSUE THREAD

**Issue by amarlette** [facebook/react-native#30950]
## Description
When using a screen reader the TouchableHighlight component doesn't disable click functionality.

This issue is covered in-depth by parent issue #30840, please check there for more details.

## React Native version:
0.63

**Comment by Naturalclar** [comment]
I'd like to work on this issue :)

**Comment by amarlette** [comment]
Thank you @Naturalclar for contributing! We appreciate your help in making React Native more accessible for everyone!

**Comment by amarlette** [comment]
Closed by the PR #31135. Thank you @Naturalclar!
