### ISSUE TITLE
DrawerLayoutAndroid.ios.js missing from npm package

### ISSUE THREAD

**Issue by chrisnojima** [facebook/react-native#3096]
The npm package for 0.11.3 (http://registry.npmjs.org/react-native/-/react-native-0.11.3.tgz) does not have DrawerLayoutAndroid.ios.js included (
https://github.com/facebook/react-native/blob/master/Libraries/Components/DrawerAndroid/DrawerLayoutAndroid.ios.js) which causes builds to fail on ios

**Comment by albinekb** [comment]
@chrisnojima do you have a temporary solution for this?

**Comment by chrisnojima** [comment]
just doing an npm install https://github.com/facebook/react-native.git (you can pass in the tag/commit if you want)

**Comment by albinekb** [comment]
Cool!

**Comment by kagha** [comment]
I believe your issue is related to this one: https://github.com/facebook/react-native/issues/3094

**Comment by chrisnojima** [comment]
Yup fixed in 11.4 tnx!
