### ISSUE TITLE
Entrance/exit from collection Not supported by Flatlist

### ISSUE THREAD

**Issue by amarlette** [facebook/react-native#30964]
## Description
Entrance/exit from collection Not supported by Flatlist. No components can be set as any collection role. With support for "List" or "Grid" roles would these would likely work as expected.

This issue is covered in-depth by parent issue #30861, please check there for more details.

## React Native version:
0.63

**Comment by anaskhraza** [comment]
Hi @amarlette, I would like to contribute to this issue, can you please assign this to me?

**Comment by amarlette** [comment]
Thank you @anaskhraza for taking on this issue. I look forward to seeing your pull request!

**Comment by gabrieldonadel** [comment]
@amarlette https://github.com/facebook/react-native/pull/31630 was merged a while ago, can we close this issue?
