### ISSUE TITLE
Collection Name not supported by Flatlist

### ISSUE THREAD

**Issue by amarlette** [facebook/react-native#30968]
## Description
Collection Name not supported by Flatlist. No components can be set as any collection role. With support for "List" or "Grid" roles would these would likely work as expected.

This issue is covered in-depth by parent issue #30972, please check there for more details.

## React Native version:
v0.63

**Comment by MarufSharifi** [comment]
Hi @amarlette,  i wanna solve this issue, could you assign it to me.

**Comment by react-one** [comment]
Hi @elamarlette, i would like to start working on this issue, would you assign it to me please ?

**Comment by Fannolo** [comment]
Hi can I work on it? Do I need to be assigned in order to work on it or can I just open a PR linked to this issue?

**Comment by blavalla** [comment]
This was fixed in #31630 and verified here https://github.com/facebook/react-native/issues/30972#issuecomment-1192399980
