### ISSUE TITLE
Entrance/exit from collection not supported by VirtualizedList 

### ISSUE THREAD

**Issue by amarlette** [facebook/react-native#30966]
## Description
Entrance/exit from collection not supported by VirtualizedList. No components can be set as any collection role. With support for "List" or "Grid" roles would these would likely work as expected.

This issue is covered in-depth by parent issue #30861, please check there for more details.

## React Native version:
0.63

**Comment by sidverma32** [comment]
Hi @amarlette , I would like to pick this up. Let me know if this is resolved or still open issue?

**Comment by fabriziobertoglio1987** [comment]
https://github.com/facebook/react-native/pull/34267
