### ISSUE TITLE
Entrance/exit from collection not supported by SectionList

### ISSUE THREAD

**Issue by amarlette** [facebook/react-native#30965]
## Description
Entrance/exit from collection not supported by SectionList. No components can be set as any collection role. With support for "List" or "Grid" roles would these would likely work as expected.

This issue is covered in-depth by parent issue #30861, please check there for more details.

## React Native version:
0.63

**Comment by mateoguzmana** [comment]
Hi @amarlette, I'd like to give this a try. Could you assign it to me? Thanks!

**Comment by gabrieldonadel** [comment]
@amarlette I believe https://github.com/facebook/react-native/pull/31630 fixed this, can we close this issue?

**Comment by XantreGodlike** [comment]
I think this issue. Can be closed cause [#31630](https://github.com/facebook/react-native/pull/31630#issue-906528271) it added to examples.
![image](https://user-images.githubusercontent.com/57757211/209408536-8c3497d6-a7e0-45ff-9766-a145d50a24e3.png)

**Comment by fabriziobertoglio1987** [comment]
video test case included here https://github.com/facebook/react-native/pull/34267

**Comment by kingdutch001** [comment]
TalkBack support for ScrollView accessibility announcements (list and grid)
#33180 <https://github.com/facebook/react-native/pull/33180> initially
landed on 20th April 2022. Java API relanded with commit a7bb9664009
<https://github.com/facebook/react-native/commit/105a2397b6b187a9669ba1c028508a7bb9664009>.
JavaScript API relanded with commit cbf53bcaf0c
<https://github.com/facebook/react-native/commit/463af237539b98289c88e5b491c85cbf53bcaf0c>,
but reverted with commit c2169c776e271ea
<https://github.com/facebook/react-native/commit/3f8071d638d7c9cd25c0eb7f6c2169c776e271ea>
.
