### ISSUE TITLE
FlatList getting greyed out when using with LayoutAnimation

### ISSUE THREAD

**Issue by williamgurzoni** [facebook/react-native#30979]
## Description

FlatList getting greyed out when using with LayoutAnimation
PS. Seems an Android issue only

## React Native version:
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 56.23 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.2.0 - /var/folders/mf/rjybpq0x1d5f05hy4kmy4pz80000gn/T/yarn--1613012655622-0.7237216406452947/node
    Yarn: 1.22.4 - /var/folders/mf/rjybpq0x1d5f05hy4kmy4pz80000gn/T/yarn--1613012655622-0.7237216406452947/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.1, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 25, 26, 28, 29
      Build Tools: 25.0.3, 28.0.3, 29.0.3
      System Images: android-21 | Google APIs Intel x86 Atom_64, android-25 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.1/12A7403 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_251 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.4 => 0.63.4
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce

1. Create a populated FlatList (optionally rendered by state)
2. Use LayoutAnimation before making the FlatList visible as documented [here](https://reactnative.dev/docs/layoutanimation#example)
3. Move the items during the animation
4. Some items get greyed out

## Expected Results

All items visible after the animation.

## Snack, code example, screenshot, or link to a repository:

https://snack.expo.io/@gurzoni/issue-flatlist-vs-layoutanimation (Please try on Android)

https://user-images.githubusercontent.com/12538626/107599324-00837f00-6c85-11eb-85d3-fba72743fbcb.mp4

**Comment by WouterVanHecke** [comment]
I'm having the same issue, some items show up with lesser opacity. Some items in rare cases don't even show up

**Comment by andidev** [comment]
@williamgurzoni @WouterVanHecke 
I just remembered that there is a workaround for this issue. Not sure if it works for all cases but it works for the example.
Maybe this workaround can give a hint for the solution to solve this issue as well.

workaround is to set `removeClippedSubviews={false}` on flatlist. It is true by default for android and not ios for some reason.
