### ISSUE TITLE
Collection Name not supported by VirtualizedList

### ISSUE THREAD

**Issue by amarlette** [facebook/react-native#30970]
## Description
Collection Name not supported by VirtualizedList. No components can be set as any collection role. With support for "List" or "Grid" roles would these would likely work as expected.

This issue is covered in-depth by parent issue #30972, please check there for more details.

## React Native version:
v0.63

**Comment by mdaj06** [comment]
Hey! @amarlette can i have a look at this issue?

**Comment by blavalla** [comment]
This was fixed in #31630 and verified here https://github.com/facebook/react-native/issues/30972#issuecomment-1192399980
