### ISSUE TITLE
Collection Name not supported by ScrollView 

### ISSUE THREAD

**Issue by amarlette** [facebook/react-native#30971]
## Description
Collection Name not supported by ScrollView. No components can be set as any collection role. With support for "List" or "Grid" roles would these would likely work as expected.

This issue is covered in-depth by parent issue #30972, please check there for more details.

## React Native version:
v0.63

**Comment by Vatsal-Srivastava** [comment]
I am new to open source and I don't understand this issue. Can I get a hint how should I start.

**Comment by daisuke0715** [comment]
Hi @amarlette, I'd like to contribute on this issue, could you please assign me?

**Comment by blavalla** [comment]
This was fixed in #31630 and verified here https://github.com/facebook/react-native/issues/30972#issuecomment-1192399980
