### ISSUE TITLE
Position in Collection not supported by ScrollView  

### ISSUE THREAD

**Issue by amarlette** [facebook/react-native#30976]
## Description
Position in Collection not supported by ScrollView. No components can be set as any collection role. With support for "List" or "Grid" roles would these would likely work as expected.

This issue is covered in-depth by parent issue #30977, please check there for more details.

## React Native version:
0.63

**Comment by wedonotcodeanymore** [comment]
Hi, I'd like to contribute on this issue, could you please assign me?

**Comment by amarlette** [comment]
Thank you for taking this on @wedonotcodeanymore, I've moved this into the "In Progress" column!

**Comment by wedonotcodeanymore** [comment]
Could you please assign me? @amarlette

**Comment by Yogita98** [comment]
Hey @wedonotcodeanymore 
Are you still interested in working on this? If not, I can pick it up

**Comment by wedonotcodeanymore** [comment]
Hey @Yogita98 ,
Yes I'm interested but kinda stuck. I'd be glad if we have a change to work together. 
I do not mind if you want to pick it up by the way. What do you say?

**Comment by mdaj06** [comment]
hey @wedonotcodeanymore!  if you're still working on this, im more than happy to collaborate!

**Comment by larry-cherry** [comment]
@amarlette I know there has been a few pull posting about this issue but I would be willing to give this a try. Been using React Native for coming up on 3 years now and would love to have the opportunity to contribute back to it.

**Comment by wedonotcodeanymore** [comment]
@amarlette Hey, sorry for late response. You can assign the issue to @larry-cherry .

**Comment by larry-cherry** [comment]
Thank you @wedonotcodeanymore

**Comment by larry-cherry** [comment]
I looked into this issue and there looks like there is already a [pull request](https://github.com/facebook/react-native/pull/31666) for it. It is not finished yet but looks like it is close to being finished.

**Comment by mdaj06** [comment]
@larry-cherry are you still working on this?

**Comment by billp72** [comment]
Hello. I'm throwing my hat in the ring for this if you haven't already selected someone to work on it. Thanks in advance.

**Comment by adi-ydv-1** [comment]
Hey, I am a newbie to open source contribution and I am looking for a good first issue so can I take this...

**Comment by Wafa9** [comment]
HI @amarlette ,I would like to work on this issue if it still exists

**Comment by fabriziobertoglio1987** [comment]
https://github.com/facebook/react-native/pull/34267

**Comment by fabriziobertoglio1987** [comment]
TalkBack support for ScrollView accessibility announcements (list and grid) [#33180](https://github.com/facebook/react-native/pull/33180) initially landed on 20th April 2022. Java API relanded with commit [a7bb9664009](https://github.com/facebook/react-native/commit/105a2397b6b187a9669ba1c028508a7bb9664009). JavaScript API relanded with commit [cbf53bcaf0c](https://github.com/facebook/react-native/commit/463af237539b98289c88e5b491c85cbf53bcaf0c), but reverted with commit [c2169c776e271ea](https://github.com/facebook/react-native/commit/3f8071d638d7c9cd25c0eb7f6c2169c776e271ea).

**Comment by banshee** [comment]
> TalkBack support for ScrollView accessibility announcements (list and grid) [#33180](https://github.com/facebook/react-native/pull/33180) initially landed on 20th April 2022. Java API relanded with commit [a7bb9664009](https://github.com/facebook/react-native/commit/105a2397b6b187a9669ba1c028508a7bb9664009). JavaScript API relanded with commit [cbf53bcaf0c](https://github.com/facebook/react-native/commit/463af237539b98289c88e5b491c85cbf53bcaf0c), but reverted with commit [c2169c776e271ea](https://github.com/facebook/react-native/commit/3f8071d638d7c9cd25c0eb7f6c2169c776e271ea).

Given all that, should this still have the "good first issue" tag?
