### ISSUE TITLE
React native build failed for init RN 0.63.4 xcode 12.4 RN 0.61.5 working fine

### ISSUE THREAD

**Issue by RejoV** [facebook/react-native#30991]
System:
OS: macOS 11.2.1
CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
Memory: 1.70 GB / 16.00 GB
Shell: 5.8 - /bin/zsh
Binaries:
Node: 14.15.1 - /usr/local/bin/node
Yarn: 1.22.10 - /usr/local/bin/yarn
npm: 6.14.8 - /usr/local/bin/npm
Watchman: 4.9.0 - /usr/local/bin/watchman
Managers:
CocoaPods: 1.10.1 - /usr/local/bin/pod
SDKs:
iOS SDK:
Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
Android SDK: Not Found
IDEs:
Android Studio: 4.1 AI-201.8743.12.41.7042882
Xcode: 12.4/12D4e - /usr/bin/xcodebuild
Languages:
Java: 15.0.1 - /usr/bin/javac
Python: 3.7.6 - /Users/xxxx/opt/anaconda3/bin/python
npmPackages:
@react-native-community/cli: Not Found
react: 16.13.1 => 16.13.1
react-native: 0.63.4 => 0.63.4
react-native-macos: Not Found
npmGlobalPackages:
react-native: Not Found

Error shown

The following build commands failed:
CompileC /Users/xxxx/Library/Developer/Xcode/DerivedData/testProj-gttdtokougyaeyaukpnbpyhshzvf/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/Flipper.build/Objects-normal/x86_64/FlipperRSocketResponder.o /Users/xxxx/Dafidy/Testing/testProj/ios/Pods/Flipper/xplat/Flipper/FlipperRSocketResponder.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

getting error by doing
react-native init testProj
cd testProj
npx react-native run-ios

**Comment by zizouvb** [comment]
You may want to check this issue https://github.com/facebook/react-native/issues/30836

**Comment by RejoV** [comment]
> You may want to check this issue #30836
> and especially this comment : [#30836 (comment)](https://github.com/facebook/react-native/issues/30836#issuecomment-772830882)

I replaced <use_flipper!> with <use_flipper!({ 'Flipper-Folly' => '2.3.0' })> still problem exists

**Comment by DKolev** [comment]
Hi, I'm having the same problem.

After migrating to RN 0.63.4 from 0.61.5, I can't build my project. For the past 2 days, I'm researching for a solution but still no luck.

I tried to comment out the flipper related code in the Podfile and this works on a **freshly init RN project**. My team still don't use Flipper so for the moment this would be sufficient.

But, when I comment the flipper related code **in my work project**, I get the following build error:
`ld: warning: directory not found for option '-L-L/Users/dimitar.kolev/Library/Developer/Xcode/DerivedData/cc-avxgovnmtpzxrcfkmekdjdlsmxlz/Build/Products/Debug-iphoneos/DoubleConversion'
ld: library not found for -lDoubleConversion
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

Any suggestions?

**Comment by Ppang0405** [comment]
@DKolev Same as you. I feed no hope right now.

**Comment by ivanmoskalev** [comment]
Flipper is absolutely not the cause here. The issue happens because of `RCT-Folly` lib. 

Issue on the Folly repo: [https://github.com/facebook/folly/issues/1527](Folly#1527)

**Comment by marcoisgood** [comment]
@Ppang0405 Dude, I feel hopeless either. after tried every each solution, issue is still fucking there.

**Comment by varwasabi** [comment]
For anyone having this issue. Disabling hermes on iOS and commenting out flipper in the Podfile will remove the error until there's a fix released.

**Comment by Daavidaviid** [comment]
what is weird is that I was able to make it work and then it stopped working for a reason i still ignore

**Comment by tubo-15** [comment]
is this solved

**Comment by codr36** [comment]
Still having the same issue. Driving me crazy.
