### ISSUE TITLE
Network Request  Fail on Android

### ISSUE THREAD

**Issue by ahtisham09** [facebook/react-native#30992]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

Hello Everyone i hope you guys doing well i got error an on Android i tried many things but result is same on IOS app is working fine  

System:
    OS: macOS 11.1
    CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
    Memory: 27.81 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 8.17.0 - ~/.nvm/versions/node/v8.17.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v8.17.0/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v8.17.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_282 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by hamdikahloun** [comment]
Maybe its [Network security configuration](https://developer.android.com/training/articles/security-config#CleartextTrafficPermitted), you can fix it by adding `android:usesCleartextTraffic="true"` to your `AndroidManifest.xml` in `android/app/src/main`
```
<?xml version="1.0" encoding="utf-8"?>
<manifest ...>
    <uses-permission android:name="android.permission.INTERNET" />
    <application
        ...
        android:usesCleartextTraffic="true"
        ...>
        ...
    </application>
</manifest>
```

**Comment by ahtisham09** [comment]
Network request Fail issue is resolve is found issue with my SSL 
Thanks
