### ISSUE TITLE
'React/RCTBridgeModule.h' file not found in custom library

### ISSUE THREAD

**Issue by devhappy15** [facebook/react-native#30999]
![Screen Shot 2021-02-16 at 3 19 21 AM](https://user-images.githubusercontent.com/69013092/107985817-c9ef9080-7005-11eb-9e21-1849029c84d3.png)
I am using a custom native library called RNSuperpowered. I manually linked this to the XCode project but I couldn't fix this error. 
React Native Version: 0.63.4

**Comment by TommyLeong** [comment]
Can you check if [this](https://stackoverflow.com/a/58398989/4311268) will help you?

**Comment by guxuloop** [comment]
+1
