### ISSUE TITLE
NavigatorIOS: Accessing onRightButtonPress from within child component

### ISSUE THREAD

**Issue by nick** [facebook/react-native#31]
I'm creating a [TodoList example](https://github.com/nick/react-native/tree/master/Examples/ToDoList) app using Flux. Right now I have three components: [TodoListApp](https://github.com/nick/react-native/blob/master/Examples/ToDoList/js/TodoListApp.js), [TodoItems](https://github.com/nick/react-native/blob/master/Examples/ToDoList/js/components/TodoItems.js) and [AddItem](https://github.com/nick/react-native/blob/master/Examples/ToDoList/js/pages/AddItem.js). TodoListApp is simply a NavigatorIOS component which shows TodoItems by default and a method to push the AddItem page to the navigator stack when the user taps the '+' button.

My question is: is there a way for my AddItem component (child of NavigatorIOS) to handle the onRightButtonPress event? Right now I've had to put in a bunch of hacks to accommodate adding a todo item when the user taps the 'Save' button from the AddItem page.

**Comment by ReadingSteiner** [comment]
@ericvicenti Is there any docs about `EventEmitter`?

**Comment by ReadingSteiner** [comment]
@ericvicenti  Is there any documentation about `EventEmitter`?

**Comment by ericvicenti** [comment]
`Subscribable.Mixin` is something we use internally to make sure nobody forgets to unsubscribe to an emitter from a component on unmount. The mixin will automatically remove subscriptions added with `this.addListenerOn`. We are currently phasing it out, though, because we will be transitioning to observables in an upcoming version of React.

For more info on the existing EventEmitter, see the github project here: https://github.com/facebook/emitter

**Comment by ReadingSteiner** [comment]
@ericvicenti  
Thanks a lot for ur reply :)

**Comment by backslash112** [comment]
checkout this demo:[react-native_flux_demo]( https://github.com/backslash112/react-native_flux_demo)

**Comment by teebolt** [comment]
Flux being the only solution for this isn't ideal.

**Comment by backslash112** [comment]
@teebolt
I agree with you, because I met a new problem when I trying to use Flux:
I created a TodoItems app too, When I succeeded in pushing a notification to the child component, and the child component will save the new item to the db, after this, the child component will push another notification to the list component for reload the list, the problem is, there are two dispatches in this process and it will cause a error: `Invariant Violation: Dispatch.dispatch(...): Cannot dispatch in the middle of a dispatch.`

**Comment by teebolt** [comment]
I was able to solve this using a simple event emitter. I can post more details if anyone needs.

**Comment by backslash112** [comment]
@teebolt Please post more details about simple event emitter, thank you.

**Comment by teebolt** [comment]
@backslash112 Here is how I was able to have the "onRightButtonPress" trigger a function in the sub-component.

The only dependency I used is https://github.com/Olical/EventEmitter  which can be added:
`var EventEmitter = require('wolfy87-eventemitter');`
 
In my main file (index.io.js) I created a new event emitter outside of the class:
`var rightButtonHandler = new EventEmitter();`

Then, inside the class I created a method to be called when the button is pressed:
`  handleSaveButton() {
    rightButtonHandler.emitEvent('saveButtonPressed');
  }`

And right below that I am passing the event emitter as a property to the sub-component:
`passProps: {
                  events: rightButtonHandler
                }`

Now, switching to the sub-component class, add this or update your componentDidMount method:
`componentDidMount() {
  this.props.events.addListener('saveButtonPressed', this.saveConcert.bind(this));
}`

The above will be calling this saveConcert:
`saveConcert() {
/// This is now called when the navigatorIOS right button is pressed.
}
`

Hope this helps!

**Comment by backslash112** [comment]
@teebolt 
Thank you very much, it works.
But, if you want to start another `dispatch` in a `listener` that is triggered by `emitChange()` of a `Store`, you will get the same error like I said above: `Invariant Violation: Dispatch.dispatch(...): Cannot dispatch in the middle of a dispatch.`

**Comment by chetankothari** [comment]
@ericvicenti I tried the approach you mentioned in one of the replies. Just wanted to check if the same holds true now or is there another way of solving it in a better way. If so could you please help me out with that. 

Thanks.

**Comment by ericvicenti** [comment]
These days I would just go with a redux-style control flow, but its not too easy to pass props down into the inside of NavigatorIOS scenes. But it can probably be done with a redux provider, and that would be  a much cleaner solution

**Comment by chetankothari** [comment]
@ericvicenti Thanks for the prompt response. Will try out getting redux-style control flow.

**Comment by littlehome-eugene** [comment]
@ericvicenti @chetankothari 
Can you elaborate what you mean by redux-style control flow?

Notify the click event through redux state?
