### ISSUE TITLE
Trigger error if styles are not defined

### ISSUE THREAD

**Issue by montogeek** [facebook/react-native#310]
Currently if you use styles and those are not defined there is not error, warning or something similar showing up

**Comment by jsierles** [comment]
Stylesheets are light wrappers around basic objects, and there's no standard way to tell if a key exists in one.

If this is a big problem, you might call your stylesheet from a wrapper method to check for the keys existence, or keep styles short and close to your component for reference.

**Comment by ide** [comment]
Additionally, it is a feature of the `style` prop that you can pass it null/falsy values so you can write code like this:
```js
<View style={someCondition && styles.conditionalStyle} />
```

The solution to detecting undeclared property access is to use a type checker like flow.
