### ISSUE TITLE
[Android] Cannot convert argument of type class com.facebook.react.bridge.ReadableNativeArray

### ISSUE THREAD

**Issue by chirag04** [facebook/react-native#3101]
Trying to build a dbmanager kind of stuff and it seems ``getArray`` of ``writableArray`` returns an instance of ``ReadableNativeArray`` which cannot be sent to a callback as argument.

Not sure if this is a bug or desired outcome. Below is the skeleton code.

```java
private WritableArray runQuery(String queryString) {
   WritableArray result = Arguments.createArray();
   WritableArray rows = Arguments.createArray();
    ......
    ......
    result.pushNull();
    result.pushArray(rows);
   return result;
}
```

```java
@ReactMethod
  public void getCourses(final Callback callback) {
    new GuardedAsyncTask<Void, Void>(getReactApplicationContext()) {
      @Override
      protected void doInBackgroundGuarded(Void... params) {
        String query = "......................";
        WritableArray result = runQuery(query);
        if(result.isNull(0)) {
          callback.invoke(null, result.getArray(1));        <---- error out here
        } else {
           //error
        }
      }
    }.execute();
  }
```

cc @mkonicek @andreicoman11 @kmagiera

**Comment by kmagiera** [comment]
The following types can be sent to JS (through JS module or callback):
 - primitives
 - String
 - WritableArray
 - WritableMap

In this case you're trying to send `ReadableArray` (note that `getArray` is in fact a method of `ReadableArray` which `WritableArray` extends and it returns an instance of `ReadableArray`) which is not on the list.

In your code: do you send `result` to some other callback? It seems like what you actually want is to either just call `callback` passing `result` (which will work as `result` is a `WritableArray`) or you want your `runQuery` to return regular java array (list?) of "writable*" types then extract those objects from the place where you call `runQuery`

**Comment by chirag04** [comment]
Thanks @kmagiera. So using a HashMap worked for me. I was just trying to create a function ``runQuery`` which returns a List/Map of error and data after executing the query.

Here what i ended up doing:
```java
        HashMap result = runQuery(query, args);
        if(result.get("error") != null) {
          String err = (String) result.get("error");
          callback.invoke(err, null);
        } else {
          WritableArray data = (WritableArray) result.get("data");
          callback.invoke(null, data);
        }
```

Happy to hear if there is a better way or any problems in this approach.

Closing for now.

**Comment by harshalkd** [comment]
@chirag04 in above solution what is runQuery method? can you explain it?
