### ISSUE TITLE
unable to build android please help me to solve this

### ISSUE THREAD

**Issue by tawhidislam** [facebook/react-native#31019]
please help me to solve this
    

- [x] @@##****
![Screenshot 2021-02-20 at 9 53 35 AM](https://user-images.githubusercontent.com/50069858/108604239-87a9b480-7361-11eb-88bd-3c7437f6fe46.png)

**Comment by hamdikahloun** [comment]
Can you check please your installed `Android SDK` in Android Studio :

![image](https://user-images.githubusercontent.com/32666446/108621797-218e6180-7435-11eb-988b-83ea9bd23dc3.png)
