### ISSUE TITLE
autoCapitalize not working on iOS 14

### ISSUE THREAD

**Issue by chrisdrackett** [facebook/react-native#31015]
## Description

When using `autoCapitalize` on a text input the field does not auto capitalize text when run on iOS 14. I've tested it on iOS 13 and iOS 14 and it seems that in iOS 14 this prop just has no effect.

## React Native version:

```
System:
    OS: macOS 11.3
    CPU: (8) x64 Apple M1
    Memory: 160.77 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.4 - /var/folders/vr/lwvvgqr9747_mfbnzq31bkt40000gn/T/yarn--1613691060613-0.6912695660388344/node
    Yarn: 1.22.10 - /var/folders/vr/lwvvgqr9747_mfbnzq31bkt40000gn/T/yarn--1613691060613-0.6912695660388344/yarn
    npm: 6.14.10 - ~/.nvm/versions/node/v14.15.4/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: 0.63.2 => 0.63.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce

- add a `TextInput`
- make sure autoCapitalize is set to `sentences` (this should be the default
- type text on iOS 14, notice sentences are not capitalized 

## Expected Results

TextInput should capitalize sentences when the user types.

## Snack, code example, screenshot, or link to a repository:

https://snack.expo.io/@tiltshift/autocap-test

**Comment by janziemba** [comment]
@chrisdrackett Could you please share your solution?

**Comment by tautvilas** [comment]
I don't think this is solved, I experience the same issue

**Comment by isotopeee** [comment]
I can replicate this issue as well.

**Comment by biancadragomir** [comment]
hi, this is not fixed. works on Android, but it doesn't on iOS
