### ISSUE TITLE
Appstate returns UncaughtError  

### ISSUE THREAD

**Issue by Bharanitharan06** [facebook/react-native#31017]
HI, Am using Appstate for deeplinking. But when ever minimize or maximize the App it returns Error and when i click double time for back button it return Error click or App will be crash
 `   
            
           Constructor(props){
             
             super(props);
                  
          this.state={
          
          appstate:AppState.currentState
    }
    
      }

    componentDidMount() {
     AppState.addEventListener("change", this.handleAppState());
    Linking.addEventListener('url', event => {
            if (event.url !== null && !this.state.initialised) {
                this.props.navigation.navigate('Signup')

            }
        });

      }
 
          componentWillUnmount() {
  
               AppState.removeEventListener("change", this.handleAppState());
       
              Linking.removeEventListener('url', this.handleAppState());
            BackHandler.removeEventListener('hardwareBackPress', this.handleBackPress);

         }

           handleAppState = async (nextAppState) => {
        console.warn(">>>>>>>>>>>initialised11", this.state.appstate)
           const url = await Linking.getInitialURL();
        if (url !== null && !this.state.initialised) {
                this.props.navigation.navigate('Signup')
            this.setState({ appstate:nextAppState })

        }
    }`

The  Error which am getting is `uncaughterror:handler is not a function.(in 'handler(appstatedata.app_state)',handler' is an instance of promise` please tell me how to sole it and how to handle Appstate without any error or app crash

**Comment by hamdikahloun** [comment]
`handler' is an instance of promise` caused by the `async` keyword.

See [appstate](https://reactnative.dev/docs/appstate)

Can you try this : 
```
handleAppState = (nextAppState) => {
    console.warn(">>>>>>>>>>>initialised11", this.state.appstate)
    this.handleInitialURL(nextAppState);
}

handleInitialURL = async (nextAppState) => {
    const url = await Linking.getInitialURL();
    if (url !== null && !this.state.initialised) {
        this.props.navigation.navigate('Signup')
        this.setState({
            appstate: nextAppState
        })
    }
}
```

**Comment by Bharanitharan06** [comment]
Thanks @hamdikahloun  my issue is fixed.
