### ISSUE TITLE
Unable to build React Native project with RN 0.63.4

### ISSUE THREAD

**Issue by zhonggithub** [facebook/react-native#31021]
1, npx react-native init MyTestApp
2, cd ios & pod install
3, npm run ios
i get this error：The following build commands failed:
	CompileC /Users/zz/Library/Developer/Xcode/DerivedData/MyTestApp-bcovgvwujwzfviepvvjzpgtonphc/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/Flipper-Folly.build/Objects-normal/x86_64/SSLSessionImpl.o /Users/zz/workspace/dev/react-native/MyTestApp/ios/Pods/Flipper-Folly/folly/ssl/detail/SSLSessionImpl.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
![image](https://user-images.githubusercontent.com/17545551/108615059-25bd7d80-743b-11eb-822d-07564fb133cd.png)

mac os:  big sur 11.2.1
xcode version: 12.4
react-native version: 0.63.4

**Comment by hamdikahloun** [comment]
Maybe can help : https://github.com/facebook/react-native/issues/26118#issuecomment-525085809
