### ISSUE TITLE
Releasing first build after code changes always gives old codes

### ISSUE THREAD

**Issue by bhrugu09** [facebook/react-native#31028]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
When i do changes in js side of the code and build android app with any means it will give apk or aab with old code only. After the first build i rebuild the release and it will contain all my updated code . Tried with cleaning the cache and all things.

## React Native version:
React native .63.2

## Steps To Reproduce
Update code and release the android app with android build>generate signed version

## Expected Results
Updated codes should be there in new release

**Comment by toprockdk** [comment]
i have the same issue

React native 0.63.3 
Apple mac mini M1
