### ISSUE TITLE
Failed to compile C in react-native run-ios

### ISSUE THREAD

**Issue by lucasdferro** [facebook/react-native#31023]
info Fetching system and libraries information...
System:
    OS: macOS 11.2.1
    CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
    Memory: 167.75 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.9.0 - /var/folders/3f/blmqd2ps4415tfgt9ffghcth0000gn/T/yarn--1613943704944-0.15182780489913972/node
    Yarn: 1.22.10 - /var/folders/3f/blmqd2ps4415tfgt9ffghcth0000gn/T/yarn--1613943704944-0.15182780489913972/yarn
    npm: 7.5.3 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 13.0.1 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
✨  Done in 37.31s.

**Comment by lucasdferro** [comment]
This is the error: The following build commands failed:
	CompileC /Users/lucasdouradoferro/Library/Developer/Xcode/DerivedData/TESTE-gmieklczzmjvswbhgblayseaytef/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/Flipper.build/Objects-normal/x86_64/FlipperRSocketResponder.o /Users/lucasdouradoferro/Desktop/React\ Native\ Projects/TESTE/ios/Pods/Flipper/xplat/Flipper/FlipperRSocketResponder.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

**Comment by Spring-Listening** [comment]
The following build commands failed:
        CompileC /Users/zouchunwen/Library/Developer/Xcode/DerivedData/AwesomeProject-aezsyvsfbghkdfgxemyrdvrlcuki/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/Flipper.build/Objects-normal/x86_64/FlipperRSocketResponder.o /Users/zouchunwen/Documents/AwesomeProject/ios/Pods/Flipper/xplat/Flipper/FlipperRSocketResponder.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

**Comment by Spring-Listening** [comment]
resolved!!!
ios -> Podfile -> use_flipper!  replace `use_flipper!({ 'Flipper' => '0.74.0' })`

**Comment by cortinico** [comment]
Closing as stale
