### ISSUE TITLE
main.jsbundle does not exist. This must be a bug with "react-native": "0.63.4"

### ISSUE THREAD

**Issue by SohaibKtb** [facebook/react-native#31025]
I figured out `main.jsbundle does not exist. This must be a bug with` issue after upgrading react native from 0.63.3 to 0.63.4 and it was solved,

but now when I tried to Archive a build the same error appears.

when I tried to see the **main.jsbundle** file from the path generated using archive build using cmd to see if it's exist, the path is true, but the file doesn't exist.

I thought that I did a wrong thing in my project, by adding a wrong code or something else in Xcode, then I created a new react-native project and tried to Archive a build, but the same error appears.
here is the system info:

```System:
    OS: macOS 11.2.1
    CPU: (8) arm64 Apple M1
    Memory: 126.23 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.7.0 - /opt/homebrew/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 7.4.3 - /opt/homebrew/bin/npm
    Watchman: 4.9.0 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 23, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.3
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_275 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

thanks 🙏

**Comment by teamzz111** [comment]
May you try with this?

#29351 (comment)

**Comment by SohaibKtb** [comment]
@teamzz111, yes I tried it, the same error

**Comment by dezudas** [comment]
@teamzz111, same for me too tried #29351 (comment) too still no change :(

**Comment by teamzz111** [comment]
Are you using TS?

May you check your Bundle Config in Xcode -> BuildPhases - Bundle React Native Code

<img width="1959" alt="Captura de Pantalla 2021-03-01 a la(s) 12 06 05 a  m" src="https://user-images.githubusercontent.com/37392536/109454310-edf99b80-7a21-11eb-882e-c623b003a53c.png">

**Comment by SohaibKtb** [comment]
@teamzz111 no I am using JS

**Comment by appcoders** [comment]
We have the same issue. A regular build works, an archive build fails.

**Comment by 29er** [comment]
same here. regular build works, archive fails !
main.jsbundle does not exist. This must be a bug with'
Please help : )

**Comment by awinograd** [comment]
I ran into this in a mono-repo setting. The solution I found is here https://github.com/react-native-community/cli/issues/656#issuecomment-601097688

**Comment by jsamr** [comment]
See https://github.com/facebook/react-native/issues/31094#issuecomment-796743154

**Comment by rabahaldoori** [comment]
any update goes same thinks
