### ISSUE TITLE
Build filled in xcode 12.4 Print: Entry, ":CFBundleIdentifier", Does Not Exist

### ISSUE THREAD

**Issue by rajeevverma076** [facebook/react-native#31038]
✋ To keep the backlog clean and actionable, issues will be
🚫 closed if they do not follow one of the issue templates:
👉 https://github.com/facebook/react-native/issues/new/choose
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist
error Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier DerivedData/Build/Products/Debug-iphonesimulator/InSiteUI.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist
. Run CLI with --verbose flag for more details.
Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier DerivedData/Build/Products/Debug-iphonesimulator/InSiteUI.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

    at checkExecSyncError (child_process.js:630:11)
    at Object.execFileSync (child_process.js:648:15)
    at runOnSimulator (node_modules/@react-native-community/cli-platform-ios/build/commands/runIOS/index.js:189:45)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Command.handleAction (/node_modules/@react-native-community/cli/build/cliEntry.js:160:7)

**Comment by vijaychouhan-rails** [comment]
Any new on it?

**Comment by rajeevverma076** [comment]
No update

**Comment by rajeevverma076** [comment]
> Any update on it?

**Comment by rajeevverma076** [comment]
> Any update on it?

No update

**Comment by tiyunchen** [comment]
your react-native info

**Comment by rajeevverma076** [comment]
info Fetching system and libraries information...
System:
    OS: macOS 11.1
    CPU: (4) x64 Intel(R) Core(TM) i3-1000NG4 CPU @ 1.10GHz
    Memory: 439.13 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.18.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.11.3 - ~/Rajeev/workspace/insiteui-upgrade-rn60/node_modules/.bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 19, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.0
      System Images: android-30 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  npmPackages:
    react: ^16.8.6 => 16.9.0 
    react-native: 0.60.4 => 0.60.4 
  npmGlobalPackages:
    react-native-git-upgrade: 0.2.7

**Comment by rajeevverma076** [comment]
> your react-native info

info Fetching system and libraries information...
System:
    OS: macOS 11.1
    CPU: (4) x64 Intel(R) Core(TM) i3-1000NG4 CPU @ 1.10GHz
    Memory: 439.13 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.18.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.11.3 - ~/Rajeev/workspace/insiteui-upgrade-rn60/node_modules/.bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 19, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.0
      System Images: android-30 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  npmPackages:
    react: ^16.8.6 => 16.9.0 
    react-native: 0.60.4 => 0.60.4 
  npmGlobalPackages:
    react-native-git-upgrade: 0.2.7

**Comment by el-lsan** [comment]
I'm having the same issue.

**Comment by super-maoMao** [comment]
I'm having the same issue too.

**Comment by theNinthDay** [comment]
I'm having the same issue.

react-native: 0.61.5

since upgrade macOS Big Sur and xcode 12.4

**Comment by verajeevverma** [comment]
> your react-native info

info Fetching system and libraries information...
System:
OS: macOS 11.1
CPU: (4) x64 Intel(R) Core(TM) i3-1000NG4 CPU @ 1.10GHz
Memory: 439.13 MB / 8.00 GB
Shell: 5.8 - /bin/zsh
Binaries:
Node: 12.18.0 - /usr/local/bin/node
Yarn: 1.22.5 - /usr/local/bin/yarn
npm: 6.11.3 - ~/Rajeev/workspace/insiteui-upgrade-rn60/node_modules/.bin/npm
Watchman: 4.9.0 - /usr/local/bin/watchman
SDKs:
iOS SDK:
Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
Android SDK:
API Levels: 19, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30
Build Tools: 28.0.3, 29.0.2, 30.0.0
System Images: android-30 | Google Play Intel x86 Atom
IDEs:
Android Studio: 4.0 AI-193.6911.18.40.6514223
Xcode: 12.4/12D4e - /usr/bin/xcodebuild
npmPackages:
react: ^16.8.6 => 16.9.0
react-native: 0.60.4 => 0.60.4
npmGlobalPackages:
react-native-git-upgrade: 0.2.7


Please help me out

**Comment by brunaschneiders** [comment]
Any update on it?

**Comment by GreatAuk** [comment]
same issue

**Comment by edgaraskazlauskas** [comment]
Same issue macOS Big Sur, react-native 0.61.5

**Comment by theNinthDay** [comment]
> Same issue macOS Big Sur, react-native 0.61.5

It can't run with terminal,   react-native run-ios

but  it works if  build and run with xcode

**Comment by GreatAuk** [comment]
> Same issue macOS Big Sur, react-native 0.61.5

It's work for me: https://github.com/facebook/react-native/issues/31038#issuecomment-840389818

**Comment by phuongit0301** [comment]
@GreatAuk 
I have followed above but not work for me. Anyone help me resolve it?

System:
    OS: macOS 11.4
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 853.09 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.3 - ~/.nvm/versions/node/v14.17.3/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.17.3/bin/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.3/bin/npm
    Watchman: 2021.06.07.00 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 29.0.2, 30.0.3, 31.0.0
      System Images: android-30 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7351085
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5

**Comment by el-lsan** [comment]
@phuongit0301 this worked for me:

Try adding following to your podfile under `post_install do |installer|`:

```
    ## Fix for XCode 12.5
    find_and_replace("../node_modules/react-native/React/CxxBridge/RCTCxxBridge.mm",
        "_initializeModules:(NSArray<id<RCTBridgeModule>> *)modules", "_initializeModules:(NSArray<Class> *)modules")
        find_and_replace("../node_modules/react-native/ReactCommon/turbomodule/core/platform/ios/RCTTurboModuleManager.mm",
        "RCTBridgeModuleNameForClass(module))", "RCTBridgeModuleNameForClass(Class(module)))")
```

and following to the end of your Podfile

```
def find_and_replace(dir, findstr, replacestr)
  Dir[dir].each do |name|
      text = File.read(name)
      replace = text.gsub(findstr,replacestr)
      if text != replace
          puts "Fix: " + name
          File.open(name, "w") { |file| file.puts replace }
          STDOUT.flush
      end
  end
  Dir[dir + '*/'].each(&method(:find_and_replace))
end
```
then run pod install again, open the `xcworkspace` of your project and do a clean build.

**Comment by phuongit0301** [comment]
Still error @el-lsan . I have updated to 0.62 and it's work for now. If you have other solutions. Can you put a comment at here?
Thanks so much @el-lsan

**Comment by hello-ccchen** [comment]
any update about this?

**Comment by EdenDadou** [comment]
Same issue there

**Comment by MarcosWillianR** [comment]
I know this is a old issue but i had a similar situation and for me it's because i was working on appcenter and i accidentaly removed appcenter plist config, sometimes is harder to debug without any code, native errors on RN are better for debug on IDE's such as Xcode and Android Studio.

If you have any code example i would be happy to help you!
