### ISSUE TITLE
ACTIVITY_RECOGNITION permission not present under PermissionsAndroid for Android 10(Q) and above

### ISSUE THREAD

**Issue by saudahmed** [facebook/react-native#31031]
## Description
Since the Android Q release google introduced 'android.permission.ACTIVITY_RECOGNITION' a run time permission. (https://developer.android.com/about/versions/10/privacy/changes#physical-activity-recognition). React Native permission(https://reactnative.dev/docs/permissionsandroid) should support this new permission. Currently, it is absent. 

## React Native version:
System:
    OS: macOS 11.2
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 274.50 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.10.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30
      Build Tools: 22.0.1, 25.0.2, 25.0.3, 26.0.2, 26.0.3, 27.0.0, 27.0.1, 27.0.3, 28.0.3, 29.0.2
      System Images: android-22 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-25 | Google APIs ARM EABI v7a, android-25 | Google APIs Intel x86 Atom, android-25 | Google Play Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_192 - /usr/bin/javac
    Python: 2.7.15 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Check **PermissionsAndroid** in react-native package.
2. **'android.permission.ACTIVITY_RECOGNITION'** is missing under **export type Permission**

## Expected Results
**'android.permission.ACTIVITY_RECOGNITION'** must be present and fully supported by **PermissionsAndroid** in react-native package. On Android Q, physical data types are not readable. See this 

https://developers.google.com/fit/android/authorization#requesting_android_permissions

**Comment by chrisglein** [comment]
Yeah, I'm not seeing ACTIVITY_RECOGNITION in [this list](https://reactnative.dev/docs/permissionsandroid#permissions-that-require-prompting-the-user). I don't know much about the API but you're expecting it to be in that set, yes? Seems like it's likely this is just a gap where the new API wasn't added. I'd assume that a PR would be accepted to add that to the list.

**Comment by jeswinsimon** [comment]
@chrisglein I had opened a PR for this a while back https://github.com/facebook/react-native/pull/28244

**Comment by saudahmed** [comment]
@chrisglein yes, you are right it needs to be in that list. @jeswinsimon had a pull request ready for it but it never merged.

**Comment by DanielCarrascoFalcon** [comment]
There is something new with this issue? is really necesary this permission!
