### ISSUE TITLE
When upgrading to 0.64-rc3, error: Cycle in dependencies between targets 'FBReactNativeSpec'

### ISSUE THREAD

**Issue by esilverberg** [facebook/react-native#31034]
## Description
When upgrading to 0.64-rc3, I was stuck for many hours today on this compliation error:

`Cycle in dependencies between targets 'BVLinearGradient' and 'FBReactNativeSpec'.`

The initial target is irrelevant; if I removed `BVLinearGradient` it would still happen for many different native libraries and `FBReactNativeSpec`. 

## React Native version:
0.64-rc3 on iOS

## Steps To Reproduce
Repro was consistent in my project. Maybe has something to do with the fact that I use `use_frameworks!`, and in the latest sample Podfile React Native does not include this directive.

## Workaround
I was able to workaround this issue (and thus want to document it here for others who may get stuck) by:

Navigating to the `FBReactNativeSpec` target in the Pods project and deleting `[CP-User] Generate Specs` step.

I then navigated in the terminal to:

`<project>/node_modules/react-native/scripts`

And I manually ran from the terminal:

`./generate-specs.sh`

**Comment by paulxuca** [comment]
Make sure to update all your dependencies that rely on `React` as a dependency in podspec to a version that relies on `React-Core`. (Just ran into this issue a few hours ago)

**Comment by esilverberg** [comment]
I am pretty confident this is not an upgrade issue. Every single time I run `pod install`, I see `[CP-User] Generate Specs` re-added to `FBReactNativeSpec` and I must delete it each time to ensure the build does not fail with this message.

**Comment by schmidan** [comment]
I seem to be running into the same issue.  
The workaround by @esilverberg does work but needs to be done after every `pod install`.

```
Showing All Messages
Cycle inside FBReactNativeSpec; building could produce unreliable results. This usually can be resolved by moving the shell script phase '[CP-User] Generate Specs' so that it runs before the build phase that depends on its outputs.
Cycle details:
→ Target 'FBReactNativeSpec' has link command with output '/Users/schmidi/Library/Developer/Xcode/DerivedData/xx-gvguladiqholtqeybzaixjacqpek/Build/Products/Debug-iphoneos/FBReactNativeSpec/FBReactNativeSpec.framework/FBReactNativeSpec'
○ Target 'FBReactNativeSpec' has compile command with input '/Users/schmidi/Projects/git/xx-12/code/ios/Pods/Target Support Files/FBReactNativeSpec/FBReactNativeSpec-dummy.m'
○ That command depends on command in Target 'FBReactNativeSpec': script phase “[CP-User] Generate Specs”
○ Target 'FBReactNativeSpec' has copy command from '/Users/schmidi/Projects/git/xx-12/code/node_modules/react-native/React/FBReactNativeSpec/FBReactNativeSpec/FBReactNativeSpec.h' to '/Users/schmidi/Library/Developer/Xcode/DerivedData/xx-gvguladiqholtqeybzaixjacqpek/Build/Products/Debug-iphoneos/FBReactNativeSpec/FBReactNativeSpec.framework/Headers/FBReactNativeSpec.h'
○ That command depends on command in Target 'FBReactNativeSpec': script phase “[CP-User] Generate Specs”


Raw dependency cycle trace:

target:  ->

node: <all> ->

command: <all> ->

node: /Users/schmidi/Library/Developer/Xcode/DerivedData/xx-gvguladiqholtqeybzaixjacqpek/Build/Products/Debug-iphoneos/FBReactNativeSpec/FBReactNativeSpec.framework/FBReactNativeSpec ->

command: target-FBReactNativeSpec-596df37657fef3d87ef16631abbc611bd8e73feadee6a8e5c14524fc300acaed-:Debug:Ld /Users/schmidi/Library/Developer/Xcode/DerivedData/xx-gvguladiqholtqeybzaixjacqpek/Build/Products/Debug-iphoneos/FBReactNativeSpec/FBReactNativeSpec.framework/FBReactNativeSpec normal ->

node: /Users/schmidi/Library/Developer/Xcode/DerivedData/xx-gvguladiqholtqeybzaixjacqpek/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/FBReactNativeSpec.build/Objects-normal/arm64/FBReactNativeSpec-dummy.o ->

command: target-FBReactNativeSpec-596df37657fef3d87ef16631abbc611bd8e73feadee6a8e5c14524fc300acaed-:Debug:CompileC /Users/schmidi/Library/Developer/Xcode/DerivedData/xx-gvguladiqholtqeybzaixjacqpek/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/FBReactNativeSpec.build/Objects-normal/arm64/FBReactNativeSpec-dummy.o /Users/schmidi/Projects/git/xx-12/code/ios/Pods/Target Support Files/FBReactNativeSpec/FBReactNativeSpec-dummy.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler ->

node: <target-FBReactNativeSpec-596df37657fef3d87ef16631abbc611bd8e73feadee6a8e5c14524fc300acaed--phase1--cp-user--generate-specs> ->

command: Gate target-FBReactNativeSpec-596df37657fef3d87ef16631abbc611bd8e73feadee6a8e5c14524fc300acaed--phase1--cp-user--generate-specs ->

node: /Users/schmidi/Library/Developer/Xcode/DerivedData/xx-gvguladiqholtqeybzaixjacqpek/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/FBReactNativeSpec.build/DerivedSources/codegen-FBReactNativeSpec.log ->

command: target-FBReactNativeSpec-596df37657fef3d87ef16631abbc611bd8e73feadee6a8e5c14524fc300acaed-:Debug:PhaseScriptExecution [CP-User] Generate Specs /Users/schmidi/Library/Developer/Xcode/DerivedData/xx-gvguladiqholtqeybzaixjacqpek/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/FBReactNativeSpec.build/Script-1E8DC3BEC0135B5B2A4A2B289C3C530F.sh ->

node: /Users/schmidi/Library/Developer/Xcode/DerivedData/xx-gvguladiqholtqeybzaixjacqpek/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/FBReactNativeSpec.build/Script-1E8DC3BEC0135B5B2A4A2B289C3C530F.sh ->

command: target-FBReactNativeSpec-596df37657fef3d87ef16631abbc611bd8e73feadee6a8e5c14524fc300acaed-:Debug:WriteAuxiliaryFile /Users/schmidi/Library/Developer/Xcode/DerivedData/xx-gvguladiqholtqeybzaixjacqpek/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/FBReactNativeSpec.build/Script-1E8DC3BEC0135B5B2A4A2B289C3C530F.sh ->

node: <target-FBReactNativeSpec-596df37657fef3d87ef16631abbc611bd8e73feadee6a8e5c14524fc300acaed--phase0-copy-headers> ->

command: Gate target-FBReactNativeSpec-596df37657fef3d87ef16631abbc611bd8e73feadee6a8e5c14524fc300acaed--phase0-copy-headers ->

node: /Users/schmidi/Library/Developer/Xcode/DerivedData/xx-gvguladiqholtqeybzaixjacqpek/Build/Products/Debug-iphoneos/FBReactNativeSpec/FBReactNativeSpec.framework/Headers/FBReactNativeSpec.h ->

command: target-FBReactNativeSpec-596df37657fef3d87ef16631abbc611bd8e73feadee6a8e5c14524fc300acaed-:Debug:CpHeader /Users/schmidi/Projects/git/xx-12/code/node_modules/react-native/React/FBReactNativeSpec/FBReactNativeSpec/FBReactNativeSpec.h /Users/schmidi/Library/Developer/Xcode/DerivedData/xx-gvguladiqholtqeybzaixjacqpek/Build/Products/Debug-iphoneos/FBReactNativeSpec/FBReactNativeSpec.framework/Headers/FBReactNativeSpec.h ->

node: /Users/schmidi/Projects/git/xx-12/code/node_modules/react-native/React/FBReactNativeSpec/FBReactNativeSpec/FBReactNativeSpec.h/ ->

directoryTreeSignature: � ->

directoryContents: /Users/schmidi/Projects/git/xx-12/code/node_modules/react-native/React/FBReactNativeSpec/FBReactNativeSpec/FBReactNativeSpec.h ->

node: /Users/schmidi/Projects/git/xx-12/code/node_modules/react-native/React/FBReactNativeSpec/FBReactNativeSpec/FBReactNativeSpec.h ->

command: target-FBReactNativeSpec-596df37657fef3d87ef16631abbc611bd8e73feadee6a8e5c14524fc300acaed-:Debug:PhaseScriptExecution [CP-User] Generate Specs /Users/schmidi/Library/Developer/Xcode/DerivedData/xx-gvguladiqholtqeybzaixjacqpek/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/FBReactNativeSpec.build/Script-1E8DC3BEC0135B5B2A4A2B289C3C530F.sh

```

**Comment by maestor** [comment]
don't know if related, but I had similar problems and workaround works. but my issue was related to thing that I started ios build with yarn. it's related somehow to the fact that this Generate Specs is npm script and won't execute correctly if you run with yarn.  after I tried just `npx react-native run-ios` from manual -> build success.

**Comment by billnbell** [comment]
This is not resolved. Still happens on 0.64.x

**Comment by marf** [comment]
Same problem here.

**Comment by paulxuca** [comment]
We've fixed this by moving the build phase that react native adds before the headers phase (It is added after by default)

**Comment by billnbell** [comment]
Is there a release ?

**Comment by JB-CHAUVIN** [comment]
Same problem goes for me, what is the solution ?



> We've fixed this by moving the build phase that react native adds before the headers phase (It is added after by default)

How did you do that ?

**Comment by paulxuca** [comment]
@JB-CHAUVIN 

Click on the Pods project on the left sidebar
Go under Build Phases
Make sure [CP-User] Generate Specs is before Headers

**Comment by marf** [comment]
Is there a permanent patch for this? Because the fix works the problem is that we have to re-do it every time we run `pod install`

**Comment by esilverberg** [comment]
We should probably ask FB to re-open this issue, since it seems clear that it is affecting multiple people and is not resolved in the release version.

**Comment by JB-CHAUVIN** [comment]
> @JB-CHAUVIN
> 
> Click on the Pods project on the left sidebar
> Go under Build Phases
> Make sure [CP-User] Generate Specs is before Headers

Thanks for your reply,

I do not find this step :( 

![image](https://user-images.githubusercontent.com/8957878/112506965-89b2c900-8d8e-11eb-9f21-c152f501e4d5.png)

**Comment by tushar-singhal** [comment]
<img width="161" alt="Screenshot 2021-03-25 at 16 23 40" src="https://user-images.githubusercontent.com/20724829/112507355-78fe5500-8d86-11eb-8c7b-0ddb50bbabea.png">
@JB-CHAUVIN  when you select pods on left sidebar, select `FBReactNativeSpec ` and then you will see this

**Comment by JB-CHAUVIN** [comment]
Great thanks for the replies,

I can confirm that @tushar-singhal @paulxuca solution is working.

And I can confirm that we need a permanent fix for this problem !

**Comment by pan-pawel** [comment]
Workaround works but doing it each time we use `pod install` wasn't a solution.
In our case only getting rid of `use_frameworks!` helped. Luckily, it turned out that we don't need it anymore

**Comment by esilverberg** [comment]
Here is a proposed solution from @gmapnl in the `react-native-screens` project:

https://github.com/software-mansion/react-native-screens/issues/842#issuecomment-812543933

```
post_install do |installer|
  react_native_post_install(installer)
  
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
    end
    
    if (target.name&.eql?('FBReactNativeSpec'))
      target.build_phases.each do |build_phase|
        if (build_phase.respond_to?(:name) && build_phase.name.eql?('[CP-User] Generate Specs'))
          target.build_phases.move(build_phase, 0)
        end
      end
    end
  end
end
```

**Comment by nnaren1902** [comment]
@esilverberg  recommended fix works perfectly well. No need to for any more manual steps. 

But still the underlying issue must be fixed in RN!

**Comment by SudoPlz** [comment]
The fix is not working for us in github actions... Not sure why.

Does anyone know if that's already fixed in any of the nightly builds?

**Comment by edwardlafoy** [comment]
Any updates on this? Just ran into this issue on `0.64.2`.

**Comment by MoOx** [comment]
If you have the issue with `BVLinearGradient`, this fix is in https://github.com/react-native-linear-gradient/react-native-linear-gradient/pull/500 but has not been released yet. You should specify `react-native-linear-gradient` version from git like this

`package.json`

```
  "react-native-linear-gradient": "https://github.com/react-native-linear-gradient/react-native-linear-gradient#0e3af58",
```

It's not a react native issue per se.

If you have a cycle issue that is mentioning another lib, you should update the lib or open an issue for the lib (and/or patch the lib by replacing in dependency React to React-Core like in the PR above (use https://www.npmjs.com/package/patch-package if needed).

If you have the cycle issue without any explicit deps except `FBReactNativeSpec`, you might need to have a look to https://github.com/facebook/react-native/issues/31149 where you will find a workaround.

**Comment by ArTM96** [comment]
> @JB-CHAUVIN
> 
> Click on the Pods project on the left sidebar Go under Build Phases Make sure [CP-User] Generate Specs is before Headers

If anyone finds that this fix doesn't work, deleting the [CP-User] Generate spec completely worked for me. App complies/runs as expected.

**Comment by cormacncheese** [comment]
This helped me

```
sudo arch -x86_64 gem install ffi
arch -x86_64 pod install
```
