### ISSUE TITLE
Status bar content color in IOS (dark mode)

### ISSUE THREAD

**Issue by frodoe7** [facebook/react-native#31039]
## Description
Status bar content color is white in the app in IOS (dark mode)
I set the configurations in XCode for status bar to be hidden and with light and dark theme and both did not work
When the status bar have a white content , the clock / battery info and these stuff looks hidden (white color on white background)

info.plist file

	```<key>UIStatusBarHidden</key>
	<true/>
	<key>UIStatusBarStyle</key>
	<string>UIStatusBarStyleDefault</string>```

reference to similar issues

[26619](https://github.com/facebook/react-native/issues/26619)

## React Native version:
```System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 1.23 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.1 - ~/.nvm/versions/node/v10.15.1/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.9 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.4 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 20.0, macOS 11.0, tvOS 14.0, watchOS 7.0
    Android SDK:
      Android NDK: 20.0.5594570
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.0/12A8189h - /usr/bin/xcodebuild
  Languages:
    Java: 9.0.1 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^16.13.1 => 16.14.0 
    react-native: ^0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found```

## Expected Results
I want the status bar to have a dark content (dark text color)

## Snack, code example, screenshot, or link to a repository:

**Comment by chrisglein** [comment]
There was a suggestion change in the issue you linked [here](https://github.com/facebook/react-native/issues/26619#issuecomment-536191518). Did you try that? Did it work?

**Comment by frodoe7** [comment]
> There was a suggestion change in the issue you linked [here](https://github.com/facebook/react-native/issues/26619#issuecomment-536191518). Did you try that? Did it work?
> 
> It'd be helpful to have more detail on your repro.

I tried to try it , I got this RCTStatusBarManager.m file , but it was in a different location and the Swift codes are different from the codes which inside the comment (looks because of a change in react-native version)

To reproduce the issue
just create a new project with react-native: 0.63.4 and make your status bar light
then test it on IOS device (with iOS version more than 13 and enable the dark mode)

**Comment by kbihani** [comment]
We too are facing the same issue.
The solution shared doesn't work as the filepath has changed.
Any help would be great!
