### ISSUE TITLE
uncaugh Error: java.net.ConnectException: Failed to connect to 192.168.1.75:19000

### ISSUE THREAD

**Issue by vinothkumark** [facebook/react-native#31035]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
When I run scan and run sample new application I am getting the above error in Android phone
https://reactnative.dev/docs/upgrading.html

## React Native version:
Run `react-native info` in your terminal and copy the results here.
react-native --version
4.13.1

**Comment by rahulreddytillu** [comment]
click 'npm start', open the browser where your application is running, and on the bottom left corner u will find the QR code, above the QR code, three options will be displayed saying 'Connection: Tunnel | LAN | Local' which is defaulted to 'LAN'. Just change it to 'Local'. Your application will run on the android device Expo Go.
