### ISSUE TITLE
Deep Linking Crash on M1 Chip while running on IOS simulator

### ISSUE THREAD

**Issue by NicolasStuff** [facebook/react-native#31036]
## Description

The command : npx uri-scheme open consultaway://app/Profile --ios  crash at start on IOS Simulator. (using M1)

## React Native version:

![Capture d’écran 2021-02-23 à 10 55 05](https://user-images.githubusercontent.com/47270925/108827516-fedf8280-75c5-11eb-9fad-e45af66608e4.png)

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Create a new app with RN-Cli on M1
2. Use the command : '   npx uri-scheme open consultaway://app/Profile --ios   '  after starting the app on IOS simulator

## Expected Results
It is suppose to redirect the app on profile screen

**Comment by chrisglein** [comment]
Do you have any stack trace or other crash diagnostics from this?
Does deep linking for a non-RN app work fine on the M1?

**Comment by NicolasStuff** [comment]
the StackTrace : 

`0 verbose cli [
0 verbose cli   '/opt/homebrew/Cellar/node/15.8.0/bin/node',
0 verbose cli   '/opt/homebrew/lib/node_modules/npm/bin/npm-cli.js',
0 verbose cli   'exec',
0 verbose cli   '--',
0 verbose cli   'uri-scheme',
0 verbose cli   'open',
0 verbose cli   'consultaway://app/Profile',
0 verbose cli   '--ios'
0 verbose cli ]
1 info using npm@7.5.0
2 info using node@v15.8.0
3 timing config:load:defaults Completed in 0ms
4 timing config:load:file:/opt/homebrew/lib/node_modules/npm/npmrc Completed in 1ms
5 timing config:load:builtin Completed in 1ms
6 timing config:load:cli Completed in 1ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:/Users/nicolasivorra/Documents/Consultaway/Consulaway-Cli/Consultaway/.npmrc Completed in 1ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:/Users/nicolasivorra/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/opt/homebrew/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 4ms
19 verbose npm-session 99b67abe240bb333
20 timing npm:load Completed in 8ms
21 http fetch GET 304 https://registry.npmjs.org/uri-scheme 1086ms (from cache)
22 timing arborist:ctor Completed in 1ms
23 timing arborist:ctor Completed in 0ms
24 timing arborist:ctor Completed in 0ms
25 timing arborist:ctor Completed in 0ms
26 timing command:exec Completed in 1984ms
27 verbose stack Error: command failed
27 verbose stack     at ChildProcess.<anonymous> (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
27 verbose stack     at ChildProcess.emit (node:events:378:20)
27 verbose stack     at maybeClose (node:internal/child_process:1067:16)
27 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
28 verbose pkgid Consultaway@0.0.1
29 verbose cwd /Users/nicolasivorra/Documents/Consultaway/Consulaway-Cli/Consultaway
30 verbose Darwin 20.3.0
31 verbose argv "/opt/homebrew/Cellar/node/15.8.0/bin/node" "/opt/homebrew/lib/node_modules/npm/bin/npm-cli.js" "exec" "--" "uri-scheme" "open" "consultaway://app/Profile" "--ios"
32 verbose node v15.8.0
33 verbose npm  v7.5.0
34 error code 1
35 error path /Users/nicolasivorra/Documents/Consultaway/Consulaway-Cli/Consultaway
36 error command failed
37 error command sh -c uri-scheme "open" "consultaway://app/Profile" "--ios"
38 verbose exit 1
`

I'm only working on a React Native app for the moment so I don't know sorry :/
