### ISSUE TITLE
How to build 24 hours to false in JAPAN locale RCTDatePicker IOS

### ISSUE THREAD

**Issue by JungYongYou** [facebook/react-native#31043]
✋ To keep the backlog clean and actionable, issues will be
🚫 closed if they do not follow one of the issue templates:
👉 https://github.com/facebook/react-native/issues/new/choose

i'm in iOS build.
I set locale ko, ja, en, ch etc..
but in ja locale there is no AM/PM button but 24 hours format is on.

```
const RCTDatePickerIOS = requireNativeComponent('RNDatePicker');

<RCTDatePickerIOS
  ref={picker => {
    this._picker = picker;
  }}
  style={styles.datePickerIOS}
  date={
    props.date
      ? props.date.getTime?.()?? props.date
      : props.initialDate
      ? props.initialDate.getTime()
      : undefined
    }
  locale={props.locale ? props.locale : undefined}
  maximumDate={
    props.maximumDate ? props.maximumDate.getTime() : undefined
  }
  minimumDate={
    props.minimumDate ? props.minimumDate.getTime() : undefined
  }
  mode={props.mode}
  minuteInterval={props.minuteInterval}
  timeZoneOffsetInMinutes={props.timeZoneOffsetInMinutes}
  onChange={this._onChange}
  onStartShouldSetResponder={() => true}
  onResponderTerminationRequest={() => false}
  textColor={props.textColor}
/>
```

![Simulator Screen Shot - iPhone 11 - 2021-02-24 at 13 02 33](https://user-images.githubusercontent.com/14883134/108945907-5a376200-7612-11eb-9821-a2a2392b1440.png)
ja ( there is no AM/PM button )
![Simulator Screen Shot - iPhone 11 - 2021-02-24 at 11 27 51](https://user-images.githubusercontent.com/14883134/108945890-4e4ba000-7612-11eb-8565-402cfd7b8627.png)
ko
![Simulator Screen Shot - iPhone 11 - 2021-02-24 at 11 27 15](https://user-images.githubusercontent.com/14883134/108945860-3c69fd00-7612-11eb-8e87-063e4098ec69.png)
en

**Comment by cortinico** [comment]
Closing as stale
