### ISSUE TITLE
RCTWebSocketModule sends a nil object in sendEventWithName

### ISSUE THREAD

**Issue by umarniz** [facebook/react-native#31048]
## Description
RCTWebSocketModule.mm at line 169 on version 0.63.3 calls `sendEventWithName` and 1 of the values passed to this is null.

This issue is not reproducible but is reported in our Crashlytics by < 0.1% of the users.

Source: https://github.com/facebook/react-native/blob/v0.63.3/React/CoreModules/RCTWebSocketModule.mm#L164

These are reports from our production Crashlytics instance and are not very easy to reproduce but the issue can be traced by dry reading the code.

The crash reports point to (for v0.63.3).

```
RCTWebSocketModule.mm - Line 169
-[RCTWebSocketModule webSocket:didFailWithError:] + 169
```

```
RCTSRWebSocket.m - Line 619
__33-[RCTSRWebSocket _failWithError:]_block_invoke_2 + 619
```

I can see that we expect `error.localizedDescription` and `socketID` to not be null when calling `sendEventWithName`.

I can see in the trace the parent invocation is from `_failWithError` in `RCTSRWebSocket.m`.

The issue is either happening because `socketID` is null in `RCTWebSocketModule webSocket:didFailWithError` when calling `sendEventWithName`

or the issue is happening because one of the cases `safeHandleEvent` in `RCTSRWebSocket.m` is return a nil object int he `localizedDescription` of `streamError`.

## React Native version:
Run `react-native info` in your terminal and copy the results here.

<details>

```
System:
    OS: macOS 11.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 6.05 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.7.0
    Yarn: 1.22.0 
    npm: 6.14.5
    Watchman: 4.9.0 
  Managers:
    CocoaPods: 1.8.4
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 12.4/12D4e 
  Languages:
    Java: 11.0.10 
    Python: 3.9.1 
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.3 => 0.63.3
    react-native-macos: Not Found
```

</details>

## Steps To Reproduce
Uncertain how to reproduce the issue, the traces are found via production crashlytics.

Will report back if we find reproducible steps.

## Expected Results
The app should not crash.

**Comment by cortinico** [comment]
Closing as stale
