### ISSUE TITLE
java.lang.RuntimeException : android.os.TransactionTooLargeException

### ISSUE THREAD

**Issue by ericV-li** [facebook/react-native#31058]
Intent will report without any data java.lang.RuntimeException : android.os.TransactionTooLargeException : data parcel size 655692 bytes

**Comment by ericV-li** [comment]
The current page data is more than 2 megabytes

**Comment by ericV-li** [comment]
The current page data is more than 2 megabytes, and the startacitvity Android page is downloaded from the current page

**Comment by DeebanT2S** [comment]
If we avoid passing the bulk data via params while navigating to the other screen we can reduce this kind of crashes
