### ISSUE TITLE
[LayoutAnimation] Success callback not firing

### ISSUE THREAD

**Issue by brentvatne** [facebook/react-native#3106]
See: https://rnplay.org/apps/RabPgA

`alert('opened')` is never called on completion

**Comment by alinz** [comment]
+1

Should we expect this one to be merged in any time soon? This is a critical bug which prevents all LayoutAnimation success callback to be called.

**Comment by alinz** [comment]
@brentvatne the PR from @kujohn seems working on iOS. However we have a serious problem in Android. We don't even pass the `success` or `failed` callbacks to any underneath methods [from here](https://github.com/facebook/react-native/blob/v0.17.0/ReactAndroid/src/main/java/com/facebook/react/uimanager/UIImplementation.java#L499-L504) to [here](https://github.com/facebook/react-native/blob/v0.17.0/ReactAndroid/src/main/java/com/facebook/react/uimanager/UIViewOperationQueue.java#L623-L628). 

Any thoughts on this?

**Comment by satya164** [comment]
@alinz LayoutAnimation is experimental on Android. Please file any issues you find.
