### ISSUE TITLE
react native app is stuck on port 80:81 and won't load anything, only a green bar appears on top of the view

### ISSUE THREAD

**Issue by nishant-k1** [facebook/react-native#31076]
After running the command "react-native run-android" I get this output on the terminal

----
BUILD SUCCESSFUL in 59s
46 actionable tasks: 2 executed, 44 up-to-date
info Connecting to the development server...
8081
info Starting the app on "emulator-5554"...
Starting: Intent { cmp=com.shoppinglist/.MainActivity }
----

But the app gets stuck on localhost: 8081 and I tried entering the IP address with port 8081 manually by going into the settings and editing the "debug server host & port for the device" option as well. But still, it gets the same issue again and again. 

![image](https://user-images.githubusercontent.com/26035708/109563114-54a3b580-7b05-11eb-9df4-2ceee39dee1b.png)

![Screenshot-20210301133246-348x793](https://user-images.githubusercontent.com/26035708/109562931-10b0b080-7b05-11eb-8edd-039d56ea0a82.png)

**Comment by nishant-k-290195** [comment]
![image](https://user-images.githubusercontent.com/26035708/109563060-43f33f80-7b05-11eb-9984-0a23f40155ea.png)
