### ISSUE TITLE
[Windows] Process 'command 'E:\android-ndk-r10e\ndk-build.cmd'' finished with non-zero exit value 2

### ISSUE THREAD

**Issue by zhupengGitHub** [facebook/react-native#3107]
Error:Execution failed for task ':ReactAndroid:buildReactNdkLib'.
> Process 'command 'E:\android-ndk-r10e\ndk-build.cmd'' finished with non-zero exit value 2

**Comment by foghina** [comment]
It looks like you're trying to build the platform on Windows. This is not supported yet. Assigning to @mkonicek as he knows more about this.

**Comment by zhupengGitHub** [comment]
Thank you, but I heard that the react - native Windows platform is currently supported
@mkonicek  did you know?

**Comment by ck227** [comment]
i have meet the same problem

**Comment by JimmyStavros** [comment]
Is Windows still not supported? Having the same issue here.

**Comment by ck227** [comment]
@JimmyStavros  i change the ndk to r9, solve the problem

**Comment by JimmyStavros** [comment]
@ck227 Were you trying to compile the examples too? That's what I've been trying to do all night.

**Comment by ck227** [comment]
@JimmyStavros  yes,i spent a lot of time ti run the UIExporer but failed this the issue blow https://github.com/facebook/react-native/issues/6331#issuecomment-195156759  ,

i found the solution the, https://github.com/facebook/react-native/pull/6260 
but i cant understand it well,so i give up with the demos.

**Comment by JimmyStavros** [comment]
@ck227 shame, guess I should just make my life easier and develop on an ubuntu image until they roll out some serious windows support. :(

**Comment by ck227** [comment]
@JimmyStavros  we should develop on a mac , windows support is really a piece of shit

**Comment by JimmyStavros** [comment]
@ck227 it's kind of frustrating that Windows has partial support, I was able to breeze through the getting started tutorial. Thought I'd be able to make the examples compiles somehow...

**Comment by ck227** [comment]
@JimmyStavros  can u help me out with this issue? https://github.com/facebook/react-native/issues/6331#issuecomment-195156759 
really want to solve it since i have already spent lots of time.

**Comment by JimmyStavros** [comment]
@ck227 I can look, though don't know how much help I can be. Looks like your ndk solution worked for me; waiting to see if I hit the same hurdle now.

**Comment by ck227** [comment]
@JimmyStavros thx, hope u will, ahahaha :-D

**Comment by mkonicek** [comment]
Windows support is community responsibility as people on the RN team at fb don't have Windows machines. Developing RN apps on Windows should work now but I don't know the status of building React Native itself. Thanks for understanding that.

If someone can figure out a fix for this and share it or send a pull request that would be awesome.

**Comment by mkonicek** [comment]
> can u help me out with this issue? #6331 (comment) 

Looking at comments on #6311 there might already be a fix in https://github.com/facebook/react-native/pull/6260, merged 6 days ago. This means it will be part of RN 0.23.0-rc which will be released next week.

**Comment by mkonicek** [comment]
For the Gradle error:

> Process 'command 'E:\android-ndk-r10e\ndk-build.cmd'' finished with non-zero exit value 2

You'll need to look at what's printed before to see the actual error message from Gradle.

**Comment by satya164** [comment]
Closing this since there has been no response from the author regarding more details. Please try with latest version as we've better windows support now. Let's reopen if this issue still exists.
