### ISSUE TITLE
Invalid prop `width` supplied to `Image`.

### ISSUE THREAD

**Issue by MickeyMouse623** [facebook/react-native#31074]
```javascript
// 同比缩放
this[`node_${item.id}_scale`] = new Animated.ValueXY({
  x: item.style.width,
  y: item.style.height,
});

<Image
    source={{uri: item.imgSrc}}
    style={{
      width: this[`node_${item.id}_scale`].x,
      height: this[`node_${item.id}_scale`].y,
    }}
  />
```

ERROR：
```bad
Warning: Failed prop type: Invalid prop `width` supplied to `Image`.
Bad object: {
  "width": 60,
  "height": 60
}
```
![image](https://user-images.githubusercontent.com/18524460/109479203-1ed6e080-7ab5-11eb-99c9-4301616295b6.png)

===============================================

## 使用 ```scale``` 是可以的

```javascript
// 同比缩放
this[`node_${item.id}_scale`] = new Animated.Value(1);

<Image
    source={{uri: item.imgSrc}}
    style={{transform: [{ scale: this[`node_${item.id}_scale`]} ]}}
  />
```

已解决
使用 ```Animated.Image``` 就可以了

**Comment by chrisglein** [comment]
A standalone repro would be helpful, as it's not clear what context your code snippets are run in. Try to create a Snack?
I'm not positive you're assigning the animated values to your Image correctly. Check out the docs for [Animated.ValueXY](https://reactnative.dev/docs/animatedvaluexy).

**Comment by oguzturker8** [comment]
Can you try with <Animated.Image /> . If it fails again try wrapping Image with <Animated.View /> it will probably work.
