### ISSUE TITLE
Init Application from Docs Not Working

### ISSUE THREAD

**Issue by ahmednkhan24** [facebook/react-native#31086]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
React native setup from [documentation](https://reactnative.dev/docs/environment-setup) fails on my machine.

### Background
* I have been using the expo cli to create and develop react-native projects.
* The command I use to generate a new expo react-native project is: `npx expo-cli init demo`
* I am now trying to replace expo with the react-native cli.

### Software Versions
* Using a MacBook Pro 2015 running MacOS 11.1
* Using an iPhone 11 simulator running iOS 14.4 that I've used with my expo apps in the past.
* Homebrew (3.0.4)
* Node (15.10.0)
* Watchman (4.9.0)
* Xcode (12.4)
* XCode command line tools (12.4)
* cocoapods (1.10.1)

### Steps that Work
* I am able to successfully create an application using `npx react-native init AwesomeProject`
* I am able to start Metro in one terminal window using `npx react-native start`

### Steps that Fail
* I try running my application on my iOS simulator using `npx react-native run-ios`
* Which then starts the build
```
info Found Xcode workspace "AwesomeProject.xcworkspace"
info Building (using "xcodebuild -workspace AwesomeProject.xcworkspace -configuration Debug -scheme AwesomeProject -destination id=8E8DFEC9-403B-4486-A5E0-F9A715CB8FFC")
⠴ Building the app.........
```
* Then a giant log of errors is output. The log is so long I am unable to scroll up to the first line of the error.
* Navigate to the /Users/username/.npm/_logs/... file, the error output is:

```
19 verbose npm-session ac762135a77a2325
20 timing npm:load Completed in 20ms
21 timing command:exec Completed in 142599ms
22 verbose stack Error: command failed
22 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
22 verbose stack     at ChildProcess.emit (node:events:378:20)
22 verbose stack     at maybeClose (node:internal/child_process:1067:16)
22 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
23 verbose pkgid AwesomeProject@0.0.1
24 verbose cwd /Users/ahmedkhan/Documents/AwesomeProject
25 verbose Darwin 20.2.0
26 verbose argv "/usr/local/Cellar/node/15.10.0_1/bin/node" "/usr/local/lib/node_modules/npm/bin/npm-cli.js" "exec" "--" "react-native" "run-ios"
27 verbose node v15.10.0
28 verbose npm  v7.5.3
29 error code 1
30 error path /Users/ahmedkhan/Documents/AwesomeProject
31 error command failed
32 error command sh -c react-native "run-ios"
33 verbose exit 1
```

## Expected Results
You should see your new app running in the iOS Simulator shortly.

**Comment by rashidul0405** [comment]
facing same error, same output as #31055
