### ISSUE TITLE
BackHandler and DeepLink working at the same time will destroy the route.

### ISSUE THREAD

**Issue by mofengfs** [facebook/react-native#31096]
## Description

Before configuring `deeplink`, `BackHandler` works normally and can return to the previous screen normally. Similarly, before using `BackHandler`, `DeepLink` works fine. 【**When both work at the same time**】, when open the app normally (important: not through deeplink. Many people mistakenly think that I use deeplink to open the app) .No matter which screen I go to, When I click the android back button, it exit the app directly, instead of returning to the previous screen. 

## React Native version:
![image](https://user-images.githubusercontent.com/16655229/109932984-e0843000-7d05-11eb-9892-dceca98900be.png)

## Steps To Reproduce
 
1. Open the app manually and enter the other screen
2. Click the android backbutton

## Expected Results
I want to back to the previous screen instead of exiting the app directly.
If I have already back to the "HomeScreen", I am prompted whether to exit the app.
E.g I jumped from `HomeScreen` to `TestScreen`, when I click the android backbutton, I want to back to `HomeScreen` instead of prompting to exit the app.

## Snack, code example, screenshot, or link to a repository:
https://github.com/mofengfs/mofengfs-1.git

**Comment by fabcall** [comment]
Actually, this is not an error. Think about your stack navigator like a deck of cards. When you navigate through the screens, the cards (screens) are stacked one above the other. So, when you open your app through deeplink, there isnt indeed a previous card.

My suggestion would be to handle the back press on the deeplinked screen. To also keep the default behavior, you can do this:

```
const {canGoBack} = props.navigation

if (!canGoBack()) {
    navigation.replace(YOUR-HOME-HERE)
    return true
}
```

Anyways, this is not related to react native itself, but to react mavigation.

**Comment by mofengfs** [comment]
@fabcall 
Yes, I can use `npx uri-scheme open a08://test/123 --android` to open the test screen. Without `BackHandler`, everything works fine. But I only used `BackHandler` in the top screen - `HomeScreen`. So, when I manually open the app to enter any page, and then click the backbutton, I will encounter the situation I said.

**Comment by fabcall** [comment]
@mofengfs have just tried your repo and it worked with no flaws. When I pressed the back button, it displayed the prompt accordingly.

**Comment by mofengfs** [comment]
@fabcall 
![image](https://user-images.githubusercontent.com/16655229/110052143-0c4cf780-7d92-11eb-8914-ffd81a8ea546.png)

**Comment by mofengfs** [comment]
@fabcall 
![image](https://user-images.githubusercontent.com/16655229/110052367-782f6000-7d92-11eb-9bbd-cc4aba87db4b.png)

**Comment by mofengfs** [comment]
The problem has been resolved, I close this Issue
