### ISSUE TITLE
React-Native App crashes on start without errors after upgrading to version 0.60.6

### ISSUE THREAD

**Issue by fabioplaka** [facebook/react-native#31093]
I wanted to upgrade React-Native version from 0.59.10 to 0.60.6. I changed all files manually based on this: https://react-native-community.github.io/upgrade-helper/?from=0.59.10&to=0.60.6

But after upgrade the application crashes on start.

This is my package.json

         {
            "version": "0.1.1",
            "private": true,
            "scripts": {
            "start": "react-native start",
            "test": "jest"
         },
        "dependencies": {
            "@react-native-community/async-storage": "^1.11.0",
            "@react-native-community/cameraroll": "^4.0.0",
            "@react-native-community/datetimepicker": "^3.0.9",
            "@react-native-community/netinfo": "^5.7.1",
            "@react-native-community/toolbar-android": "0.1.0-rc.2",
            "@react-native-picker/picker": "^1.9.10",
            "babel-preset-expo": "^5.0.0",
            "base64-js": "^1.3.0",
            "crypto-js": "^3.1.9-1",
            "dateformat": "^3.0.3",
            "formik": "^1.5.1",
            "i18n-js": "^3.1.0",
            "json2csv": "^4.3.3",
            "lodash": "^4.17.19",
            "mime": "^2.4.0",
            "moment": "^2.23.0",
            "native-base": "^2.15.2",
            "prop-types": "^15.6.2",
            "react": "16.8.6",
            "react-native": "0.60.6",
            "react-native-action-button": "^2.7.0",
            "react-native-awesome-alerts": "^1.3.2",
            "react-native-charts-wrapper": "^0.5.7",
            "react-native-connectycube": "^3.0.1",
            "react-native-document-picker": "^2.1.0",
            "react-native-drawer": "^2.3.0",
            "react-native-elements": "^1.1.0",
            "react-native-exit-app": "^1.0.0",
            "react-native-file-picker": "0.0.12",
            "react-native-file-viewer": "^2.0.0",
            "react-native-firebase": "^5.6.0",
            "react-native-fs": "^2.15.2",
            "react-native-gesture-handler": "^1.10.3",
            "react-native-google-drive-api": "^1.0.22",
            "react-native-google-drive-api-wrapper": "^1.3.0",
            "react-native-google-signin": "^2.0.0",
            "react-native-html-to-text": "0.0.5",
            "react-native-image-crop-picker": "^0.21.3",
            "react-native-image-picker": "^0.26.3",
            "react-native-incall-manager": "^3.2.7",
            "react-native-keyboard-aware-scroll-view": "^0.7.2",
            "react-native-languages": "^3.0.2",
            "react-native-loading-spinner-overlay": "^0.5.2",
            "react-native-modal": "^9.0.0",
            "react-native-modal-datetime-picker": "^9.1.0",
            "react-native-modal-filter-picker": "^1.3.4",
            "react-native-onesignal": "^4.0.4",
            "react-native-pdf": "^5.0.11",
            "react-native-permissions": "^2.1.5",
            "react-native-pie": "^0.4.0",
            "react-native-popup-dialog": "^0.17.0",
            "react-native-qrcode-svg": "^6.0.6",
            "react-native-reanimated": "^1.13.2",
            "react-native-screens": "^2.18.1",
            "react-native-selectme": "^1.2.3",
            "react-native-sensor-manager": "^0.1.10",
            "react-native-simple-radio-button": "^2.7.4",
            "react-native-simple-toast": "0.0.8",
            "react-native-sound": "^0.11.0",
            "react-native-spinkit": "^1.5.0",
            "react-native-step-indicator": "0.0.9",
            "react-native-svg": "^12.1.0",
            "react-native-svg-transformer": "^0.14.3",
            "react-native-tags": "^2.0.0",
            "react-native-timeago": "^0.4.0",
            "react-native-typography": "^1.4.0",
            "react-native-vector-icons": "^6.2.0",
            "react-native-view-shot": "^3.1.2",
            "react-native-webrtc": "^1.87.1",
            "react-native-webview": "^10.3.2",
            "react-navigation": "^3.8.1",
            "react-navigation-redux-helpers": "^3.0.0",
            "react-redux": "^5.0.7",
            "realm": "^10.2.0",
            "redux": "^4.0.0",
            "redux-thunk": "^2.3.0",
            "rn-fetch-blob": "^0.12.0",
            "shortid": "^2.2.15",
            "uuid": "^3.3.3",
            "validate-model": "0.0.2",
             "yup": "^0.26.10"
        },
        "devDependencies": {
              "@babel/core": "^7.6.2",
              "@babel/runtime": "^7.6.2",
              "babel-jest": "^24.7.1",
              "babel-plugin-transform-property-literals": "^6.9.4",
              "babel-preset-react-native": "4.0.1",
              "schedule": "^0.4.0",
              "jest": "^24.9.0",
              "metro-react-native-babel-preset": "^0.56.0",
              "react-test-renderer": "16.8.6"
         },
        "jest": {
              "preset": "react-native",
              "moduleFileExtensions": [
              "js",
              "json",
              "es6",
              "ios.js",
              "android.js"
         ]
       }
     }

Any idea why gives the crash at start?

Thanks in advance

**Comment by fabioplaka** [comment]
Is this issue related to realm or is something else?

**Comment by samithaf** [comment]
Would you be able to share the App logs?

**Comment by cortinico** [comment]
Closing as stale
