### ISSUE TITLE
Platform-specific images require extension-less base image since v0.62

### ISSUE THREAD

**Issue by sonicdoe** [facebook/react-native#31099]
## Description

According to the [Images](https://reactnative.dev/docs/images) docs, React Native supports platform-specific images:

> If you have `my-icon.ios.png` and `my-icon.android.png`, the bundler will pick the correct file for the platform.

However, since React Native v0.62, the base image `my-icon.png` is required as well. Otherwise, the bundler is unable to resolve the image. This regression is most likely due to the upgrade of Metro from v0.56.4 to v0.59.0.

## Steps to reproduce

1. Create two platform-specific images (like `foo.ios.png` and `foo.android.png`)
2. Reference the image using `<Image>` (for example, `<Image source={require('./foo.png')} />`)

With React Native v0.63.4, the bundler will throw the following error:

```
error: Error: Unable to resolve module ./foo.png from …:

None of these files exist:
  * foo.png
  * foo.png/index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
```

## Expected results

The bundler is able to resolve platform-specific images, even without an extension-less base image.

## Example repository

You can find an example at [kontist/react-native-platform-specific-image-regression](https://github.com/kontist/react-native-platform-specific-image-regression). In particular, [this diff](https://github.com/kontist/react-native-platform-specific-image-regression/compare/d8baa7bade352c313ecb0a52f8c8eb45231f3c0b...main) shows all changes—apart from initializing the projects with `react-native init`.

If you run `react-native run-android` from the `0.61.5` directory, you should see a gray image with the text “Android”. In contrast, if you run `react-native run-android` from the `0.63.4` directory, the bundler should fail with an “Unable to resolve module ./image.png” error.

**Comment by iggyfisk** [comment]
Just ran into this after moving from RN 0.63.3 to 0.64.0, looking in `yarn.lock` the installed Metro went from 0.58.0 to 0.64.0 and now we need dummy images for our platform-specific assets.

**Comment by alexissilva** [comment]
The same problem here. I glad not to be alone in this

**Comment by Javi** [comment]
Lord, this bug had me tearing my hair out. I would have never thought that adding a dummy file would work. It was breaking my upgrade and preventing me from going to 0.64, it should be a high priority issue!

**Comment by kasl** [comment]
we got the answer to this issue in https://github.com/facebook/metro/issues/676#issuecomment-866712819
