### ISSUE TITLE
RN 0.63.4 main.jsbundle does not exist. This must be a bug with'

### ISSUE THREAD

**Issue by ColtraneNadler** [facebook/react-native#31094]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
App won't build for release scheme, therefore won't archive.
I have watchman installed. I can build for debug, just not release. 

## React Native version:
`0.63.4`
Node version is `v14.15.5`

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Build for Release scheme

## Expected Results
For the build to succeed

## Snack, code example, screenshot, or link to a repository:
During the build process..

```
BUNDLE_FILE=/Users/coltrane/Library/Developer/Xcode/DerivedData/mobile-dsdtbnudpwicuuckveptihmuzeuy/Build/Products/Release-iphonesimulator/mobile.app/main.jsbundle
+ /usr/local/bin/node /Users/coltrane/Documents/Apps/Storyboard/social/mobile/node_modules/react-native/cli.js bundle --entry-file index.js --platform ios --dev false --reset-cache --bundle-output /Users/coltrane/Library/Developer/Xcode/DerivedData/mobile-dsdtbnudpwicuuckveptihmuzeuy/Build/Products/Release-iphonesimulator/mobile.app/main.jsbundle --assets-dest /Users/coltrane/Library/Developer/Xcode/DerivedData/mobile-dsdtbnudpwicuuckveptihmuzeuy/Build/Products/Release-iphonesimulator/mobile.app
warning: the transform cache was reset.
                 Welcome to React Native!
                Learn once, write anywhere


events.js:292
      throw er; // Unhandled 'error' event

Error: EMFILE: too many open files, watch
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:178:28)
Emitted 'error' event on NodeWatcher instance at:
    at NodeWatcher.checkedEmitError (/Users/coltrane/Documents/Apps/Storyboard/social/mobile/node_modules/sane/src/node_watcher.js:143:12)
    at FSWatcher.emit (events.js:315:20)
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:184:12) {
  errno: -24,
  syscall: 'watch',
  code: 'EMFILE',
  filename: null
}
+ [[ false != true ]]
+ [[ ! -f /Users/coltrane/Library/Developer/Xcode/DerivedData/mobile-dsdtbnudpwicuuckveptihmuzeuy/Build/Products/Release-iphonesimulator/mobile.app/main.jsbundle ]]
echo 'error: File /Users/coltrane/Library/Developer/Xcode/DerivedData/mobile-dsdtbnudpwicuuckveptihmuzeuy/Build/Products/Release-iphonesimulator/mobile.app/main.jsbundle does not exist. This must be a bug with'

```

In my build phases, I have it set to 
```
export NODE_BINARY=$(which node)
../node_modules/react-native/scripts/react-native-xcode.sh
```

I've tried:
```
cd $PROJECT_DIR/..
export NODE_BINARY=node
./node_modules/react-native/scripts/react-native-xcode.sh
```
and other variations of the solutions on issue #29351 which didn't work either.

Please help!

**Comment by ColtraneNadler** [comment]
Bump here

**Comment by safaiyeh** [comment]
@ColtraneNadler could you check out this issue: https://github.com/facebook/create-react-app/issues/4540#issuecomment-393268543

to see if it solves your problem

**Comment by jsamr** [comment]
@safaiyeh Not the OP, but facing the same issue (RN 0.63.4) and I already have the latest version of watchman installed from brew (4.9.0_5). I'm on an Apple Silicon macbook 2020. 

<details>
<summary>React Native Info</summary>
<pre>
System:
    OS: macOS 11.2.2
    CPU: (8) arm64 Apple M1
    Memory: 409.72 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.9.0 - /opt/homebrew/bin/node
    Yarn: 2.4.0 - /opt/homebrew/bin/yarn
    npm: 7.5.3 - /opt/homebrew/bin/npm
    Watchman: 4.9.0 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
</pre>
</details>

### References

- Looks very much like #31025.
- Looks exactly like the issue related in this PR #29477 which has landed in 0.63.3 (I checked the git file history, and this script has not changed since then).

### Reproduction

I tried to reproduce the issue in a blank project, but unfortunately, archiving from XCode requires a provisioning profile which can be granted with an Apple developer license, which I don't have.

**Comment by jsamr** [comment]
I managed to fix the issue on my Macbook M1 by compiling watchman from source. The brew formulae is pretty much outdated, and [there seems to be a status-quo preventing any update to ship via homebrew](https://github.com/Homebrew/homebrew-core/pull/60693#issuecomment-700524777).

Here are the steps:

```
v2021.03.01.00-macos
```

**Comment by jsamr** [comment]
I found the issue on my end. It was because of my `$PATH` environment variable, which was set to `/opt/homebrew/bin` for zsh, but not configured for `/bin/sh`.  This path is used by the metro bundler to identify the presence of watchman; that's why the reported error was symptomatic of a missing watchman install! (thanks @safaiyeh ).

### I. Generic solution with `path_helper`

`path_helper` is a very handy utility shipped with MacOS to construct the `PATH` environment for any shell, and it's the Apple recommended way to share a path globally. To add a path, you just need to create a new file under `/etc/paths.d/` with one or more lines containing each a path:

```sh
sudo -s 'echo "/opt/homebrew/bin" > /etc/paths.d/200-homebrew'
```
Unfortunately, XCode doesn't follow Apple `path_helper` standard, but we can force this behavior by prepending the shell script. Add these lines in "Bundle React native code and images" build phase script:

```sh
if [ -x /usr/libexec/path_helper ]; then
    eval `/usr/libexec/path_helper -s`
fi
```

### II. Quick and dirty fix

An alternative is to hardcode the homebrew path in the shell script. I find it less generic but certainly straightforwards.
Add this line in "Bundle React native code and images" build phase script:

```
export PATH="$PATH:/opt/homebrew/bin"
```

**Comment by IacoCesar** [comment]
same here

**Comment by Fortidude** [comment]
Above "II. Quick and dirty fix" :

```
export PATH="$PATH:/opt/homebrew/bin"
export NODE_BINARY=node
...
```

did the job in my case. 

I have this issue from time to time, but only when running `archive`. Sometimes it's working for a few days, and then I have to reinstall node, watchmen, brew, switch between node versions (10-15) and sometimes it just `click` and works. and than - after next 1-3 weeks it doesn't work once again :) 

I think somehow sometimes Xcode CLI when building archive can't run watchman. Buildng debug on simulator/physical works fine, only the `archive` is problematic.

**Comment by nitaking** [comment]
I work it:
```
touch ios/main.jsbundle
```

**Comment by bAngerman** [comment]
I was able to get this to work by editing `/node_modules/react-native/scripts/react-native-xcode.sh`.

`BUNDLE_FILE="$DEST/main.jsbundle"` toward the end of the file...
was modified to reflect what actually was created in that folder.
I changed the value to the Display Name shown on the "General" tab in Xcode.

Whack

**Comment by javioli-devbase** [comment]
I have the same issue with RN 0.63.3 , I tried all solutions here, but nothing worked , Can anyone help me?

**Comment by ithustle** [comment]
I ran Metro bundle with sudo and Build was successful.
Why is that? Because every time the process was near to end, the Metro lose connection to watchman and build fall

**Comment by OtavioBraga** [comment]
> I found the issue on my end. It was because of my `$PATH` environment variable, which was set to `/opt/homebrew/bin` for zsh, but not configured for `/bin/sh`. This path is used by the metro bundler to identify the presence of watchman; that's why the reported error was symptomatic of a missing watchman install! (thanks @safaiyeh ).
> 
> ### I. Generic solution with `path_helper`
> `path_helper` is a very handy utility shipped with MacOS to construct the `PATH` environment for any shell, and it's the Apple recommended way to share a path globally. To add a path, you just need to create a new file under `/etc/paths.d/` with one or more lines containing each a path:
> 
> ```shell
> sudo -s 'echo "/opt/homebrew/bin" > /etc/paths.d/200-homebrew'
> ```
> 
> Unfortunately, `/bin/sh` run from XCode 12.4 doesn't seem to source `/etc/profile` which in turns should call `path_helper`, but we can force this behavior by sourcing it ourselves. Add these lines in the very beginning of "Bundle React native code and images" build phase script:
> 
> ```shell
> if [ -f /etc/profile ]; then
>     . /etc/profile
> fi
> export NODE_BINARY=node
> ...
> ```
> 
> ### II. Quick and dirty fix
> An alternative is to hardcode the homebrew path in the shell script. I find it less generic but certainly straightforwards.
> Add this line in the very beginning of "Bundle React native code and images" build phase script:
> 
> ```
> export PATH="$PATH:/opt/homebrew/bin"
> export NODE_BINARY=node
> ...
> ```

Worked like a charm for me!

**Comment by priyankaEdufund** [comment]
> I found the issue on my end. It was because of my `$PATH` environment variable, which was set to `/opt/homebrew/bin` for zsh, but not configured for `/bin/sh`. This path is used by the metro bundler to identify the presence of watchman; that's why the reported error was symptomatic of a missing watchman install! (thanks @safaiyeh ).
> 
> ### I. Generic solution with `path_helper`
> `path_helper` is a very handy utility shipped with MacOS to construct the `PATH` environment for any shell, and it's the Apple recommended way to share a path globally. To add a path, you just need to create a new file under `/etc/paths.d/` with one or more lines containing each a path:
> 
> ```shell
> sudo -s 'echo "/opt/homebrew/bin" > /etc/paths.d/200-homebrew'
> ```
> 
> Unfortunately, `/bin/sh` run from XCode 12.4 doesn't seem to source `/etc/profile` which in turns should call `path_helper`, but we can force this behavior by sourcing it ourselves. Add these lines in the very beginning of "Bundle React native code and images" build phase script:
> 
> ```shell
> if [ -f /etc/profile ]; then
>     . /etc/profile
> fi
> export NODE_BINARY=node
> ...
> ```
> 
> ### II. Quick and dirty fix
> An alternative is to hardcode the homebrew path in the shell script. I find it less generic but certainly straightforwards. Add this line in the very beginning of "Bundle React native code and images" build phase script:
> 
> ```
> export PATH="$PATH:/opt/homebrew/bin"
> export NODE_BINARY=node
> ...
> ```

YOU SAVED MY LIVE <3
Thank you soo much! :)

**Comment by liqiankl** [comment]
> I have the same issue with RN 0.63.3 , I tried all solutions here, but nothing worked , Can anyone help me?

I've been facing this issue lately was there any fix to this, seem like its been a while

**Comment by nguyenvanphuc2203** [comment]
> I found the issue on my end. It was because of my `$PATH` environment variable, which was set to `/opt/homebrew/bin` for zsh, but not configured for `/bin/sh`. This path is used by the metro bundler to identify the presence of watchman; that's why the reported error was symptomatic of a missing watchman install! (thanks @safaiyeh ).
> 
> ### I. Generic solution with `path_helper`
> `path_helper` is a very handy utility shipped with MacOS to construct the `PATH` environment for any shell, and it's the Apple recommended way to share a path globally. To add a path, you just need to create a new file under `/etc/paths.d/` with one or more lines containing each a path:
> 
> ```shell
> sudo -s 'echo "/opt/homebrew/bin" > /etc/paths.d/200-homebrew'
> ```
> 
> Unfortunately, `/bin/sh` run from XCode 12.4 doesn't seem to source `/etc/profile` which in turns should call `path_helper`, but we can force this behavior by sourcing it ourselves. Add these lines in the very beginning of "Bundle React native code and images" build phase script:
> 
> ```shell
> if [ -f /etc/profile ]; then
>     . /etc/profile
> fi
> export NODE_BINARY=node
> ...
> ```
> 
> ### II. Quick and dirty fix
> An alternative is to hardcode the homebrew path in the shell script. I find it less generic but certainly straightforwards. Add this line in the very beginning of "Bundle React native code and images" build phase script:
> 
> ```
> export PATH="$PATH:/opt/homebrew/bin"
> export NODE_BINARY=node
> ...
> ```

YOU SAVED MY LIFE <3
Thank you soo much! :)

**Comment by codesalley** [comment]
Open project ios folder in Xcode, goto `build phases` in `Copy Bundle Resources ` tab remove `main.jsbundle`
![Screenshot 2022-06-16 at 5 36 39 PM](https://user-images.githubusercontent.com/32754058/174132903-91dd39fd-30b8-4f2d-87da-8bfcab3e4c8d.png)

**Comment by mungbeans2** [comment]
Hello, I don't understand the description of

> I found the issue on my end. It was because of my `$PATH` environment variable, which was set to `/opt/homebrew/bin` for zsh, but not configured for `/bin/sh`. This path is used by the metro bundler to identify the presence of watchman; that's why the reported error was symptomatic of a missing watchman install! (thanks @safaiyeh ).
> 
> ### I. Generic solution with `path_helper`
> `path_helper` is a very handy utility shipped with MacOS to construct the `PATH` environment for any shell, and it's the Apple recommended way to share a path globally. To add a path, you just need to create a new file under `/etc/paths.d/` with one or more lines containing each a path:
> 
> ```shell
> sudo -s 'echo "/opt/homebrew/bin" > /etc/paths.d/200-homebrew'
> ```
> 
> Unfortunately, `/bin/sh` run from XCode 12.4 doesn't seem to source `/etc/profile` which in turns should call `path_helper`, but we can force this behavior by sourcing it ourselves. Add these lines in the very beginning of "Bundle React native code and images" build phase script:
> 
> ```shell
> if [ -f /etc/profile ]; then
>     . /etc/profile
> fi
> export NODE_BINARY=node
> ...
> ```
> 
> ### II. Quick and dirty fix
> An alternative is to hardcode the homebrew path in the shell script. I find it less generic but certainly straightforwards. Add this line in the very beginning of "Bundle React native code and images" build phase script:
> 
> ```
> export PATH="$PATH:/opt/homebrew/bin"
> export NODE_BINARY=node
> ...
> ```

Hello, I don't understand the description of the issue and the fix.  The problem is described as "but not configured for /bin/sh". So if the path isn't configured for /bin/sh then why is the (quick and dirty) solution configuring homebrew/bin and not configuring /bin/sh?

**Comment by jjrise** [comment]
I'd imagine for most users who still can't solve this with any of the above steps have an issue with their javascript. I had a package/dependency issue and that solved it.

**Comment by JuxhinB** [comment]
> NODE_BINARY

this actually works, archive doesn't

**Comment by rasheedk** [comment]
Change 
export NODE_BINARY=$(command -v node)
to
export NODE_BINARY=/usr/local/opt/node/bin/node

in the .xcode.env file

**Comment by andyngojs** [comment]
> I found the issue on my end. It was because of my `$PATH` environment variable, which was set to `/opt/homebrew/bin` for zsh, but not configured for `/bin/sh`. This path is used by the metro bundler to identify the presence of watchman; that's why the reported error was symptomatic of a missing watchman install! (thanks @safaiyeh ).
> 
> ### I. Generic solution with `path_helper`
> `path_helper` is a very handy utility shipped with MacOS to construct the `PATH` environment for any shell, and it's the Apple recommended way to share a path globally. To add a path, you just need to create a new file under `/etc/paths.d/` with one or more lines containing each a path:
> 
> ```shell
> sudo -s 'echo "/opt/homebrew/bin" > /etc/paths.d/200-homebrew'
> ```
> 
> Unfortunately, `/bin/sh` run from XCode 12.4 doesn't seem to source `/etc/profile` which in turns should call `path_helper`, but we can force this behavior by sourcing it ourselves. Add these lines in the very beginning of "Bundle React native code and images" build phase script:
> 
> ```shell
> if [ -f /etc/profile ]; then
>     . /etc/profile
> fi
> export NODE_BINARY=node
> ...
> ```
> 
> ### II. Quick and dirty fix
> An alternative is to hardcode the homebrew path in the shell script. I find it less generic but certainly straightforwards. Add this line in the very beginning of "Bundle React native code and images" build phase script:
> 
> ```
> export PATH="$PATH:/opt/homebrew/bin"
> export NODE_BINARY=node
> ...
> ```

I had fixed this error by the way tried use "II. Quick and dirty fix". 
Thank you so much!

**Comment by mungbeans2** [comment]
> > I found the issue on my end. It was because of my `$PATH` environment variable, which was set to `/opt/homebrew/bin` for zsh, but not configured for `/bin/sh`. This path is used by the metro bundler to identify the presence of watchman; that's why the reported error was symptomatic of a missing watchman install! (thanks @safaiyeh ).
> > ### I. Generic solution with `path_helper`
> > `path_helper` is a very handy utility shipped with MacOS to construct the `PATH` environment for any shell, and it's the Apple recommended way to share a path globally. To add a path, you just need to create a new file under `/etc/paths.d/` with one or more lines containing each a path:
> > ```shell
> > sudo -s 'echo "/opt/homebrew/bin" > /etc/paths.d/200-homebrew'
> > ```
> > 
> 
> I had fixed this error by the way tried use "II. Quick and dirty fix". Thank you so much!

I don't understand what you are saying - this new file that gets created under `/etc/paths.d/` what should it be called? It can be called anything? And what should it contain? You're implying it should contain the line sudo -s 'echo "/opt/homebrew/bin" > /etc/paths.d/200-homebrew' ? 
So that does mean you've named your file 200-homebrew, and then that file contains a line of sudo -s 'echo "/opt/homebrew/bin" > /etc/paths.d/200-homebrew' So its self referential?

**Comment by popking5466** [comment]
> sudo -s 'echo "/opt/homebrew/bin" > /etc/paths.d/200-homebrew'

piccolo@Piccolos-MacBook-Pro ios % sudo -s 'echo "/opt/homebrew/bin" > /etc/paths.d/200-homebrew'
Password:
zsh:1: no such file or directory: echo "/opt/homebrew/bin" > /etc/paths.d/200-homebrew

I create an empy file named 200-homebrew in /etc/paths.d/ but still not work. Can you help me?

**Comment by vishalenrique** [comment]
> I found the issue on my end. It was because of my `$PATH` environment variable, which was set to `/opt/homebrew/bin` for zsh, but not configured for `/bin/sh`. This path is used by the metro bundler to identify the presence of watchman; that's why the reported error was symptomatic of a missing watchman install! (thanks @safaiyeh ).
> 
> ### I. Generic solution with `path_helper`
> `path_helper` is a very handy utility shipped with MacOS to construct the `PATH` environment for any shell, and it's the Apple recommended way to share a path globally. To add a path, you just need to create a new file under `/etc/paths.d/` with one or more lines containing each a path:
> 
> ```shell
> sudo -s 'echo "/opt/homebrew/bin" > /etc/paths.d/200-homebrew'
> ```
> 
> Unfortunately, `/bin/sh` run from XCode 12.4 doesn't seem to source `/etc/profile` which in turns should call `path_helper`, but we can force this behavior by sourcing it ourselves. Add these lines in the very beginning of "Bundle React native code and images" build phase script:
> 
> ```shell
> if [ -f /etc/profile ]; then
>     . /etc/profile
> fi
> export NODE_BINARY=node
> ...
> ```
> 
> ### II. Quick and dirty fix
> An alternative is to hardcode the homebrew path in the shell script. I find it less generic but certainly straightforwards. Add this line in the very beginning of "Bundle React native code and images" build phase script:
> 
> ```
> export PATH="$PATH:/opt/homebrew/bin"
> export NODE_BINARY=node
> ...
> ```

Can someone please explain why the above solution works?

**Comment by penghaogit** [comment]
export PATH="$PATH:/opt/homebrew/bin"
export NODE_BINARY=node
../node_modules/react-native/scripts/react-native-xcode.sh

This solved my problem

**Comment by PriyaBapodra** [comment]
@OtavioBraga Your solution worked for me ! Thanks !
