### ISSUE TITLE
RCTWebSocketExecutor refers to `localhost`

### ISSUE THREAD

**Issue by ckknight** [facebook/react-native#311]
In RCTWebSocketExecutor.m:
    - (instancetype)init
    {
      return [self initWithURL:[NSURL URLWithString:@"http://localhost:8081/debugger-proxy"]];
    }

This prevents remote debugging. If I manually change it to my computer's IP, I am able to debug with the Chrome inspector.

**Comment by jsierles** [comment]
Follow the discussion on configuring IP/port here: #1429

**Comment by brentvatne** [comment]
@jsierles #fridaytriage :smile:
