### ISSUE TITLE
KeyboardAvoidingView makes screen to 'jump and flicker'

### ISSUE THREAD

**Issue by codeLearnerrr** [facebook/react-native#31104]
## Description

The screen is wrapped in `<KeyboardAvoidingView/>` and it's behavior was disabled. The issue happens when the keyboard shows up and the screen 'flickers and jumps'. This happened in both real devide and simulator. The tests happened using android. 

## React Native version:

```
System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
    Memory: 2.14 GB / 7.91 GB
  Binaries:
    Node: 15.2.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.5.4 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 23, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.3
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6953283
    Visual Studio: 16.8.30907.101 (Visual Studio Community 2019)
  Languages:
    Java: 1.8.0_275
    Python: 2.7.15
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.4 => 0.63.4
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce

1. Wrapp some views inside `<KeyboardAvoidingView/>`
2. Inside `<KeyboardAvoidingView/>` set `enable={false}`

## Expected Results

It is expected from the app to be overlayed by the system keyboard without bugs in the User Interface (UI).

## Snack, code example, screenshot, or link to a repository:

link to [repository](https://github.com/codeLearnerrr/KeyBoardAvoidingViewIssue)

https://user-images.githubusercontent.com/44307139/110183813-7eebc080-7dee-11eb-8b28-2c312a6f2652.mp4

**Comment by johnpawl** [comment]
Help !!!

I want to get back to android activity from react-native activity using backkey .


**MainActivity.java**


    public class MainActivity extends AppCompatActivity {

    Button button;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        button = (Button) findViewById(R.id.button);
        button.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                startRNPage();
            }
        });
    }

    private void startRNPage() {
        Intent intent = new Intent(this, ReactNativeActivity.class);
        startActivity(intent);
        finish();
    }
    }

**ReactNativeActivity.java**



    public class ReactNativeActivity extends AppCompatActivity {
    private ReactRootView mReactRootView;
    private ReactInstanceManager mReactInstanceManager;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        SoLoader.init(this, false);

        mReactRootView = new ReactRootView(this);
        List<ReactPackage> packages = new PackageList(getApplication()).getPackages();
        // Packages that cannot be autolinked yet can be added manually here, for example:
        // packages.add(new MyReactNativePackage());
        // Remember to include them in `settings.gradle` and `app/build.gradle` too.

        

        mReactInstanceManager = ReactInstanceManager.builder()
        .setApplication(getApplication())
        .setCurrentActivity(this)
        .setBundleAssetName("index.android.bundle")
        .setJSMainModulePath("index")
        .addPackages(packages)
        .setUseDeveloperSupport(BuildConfig.DEBUG)
        .setInitialLifecycleState(LifecycleState.RESUMED)
        .build();
        // The string here (e.g. "MyReactNativeApp") has to match
        // the string in AppRegistry.registerComponent() in index.js
        mReactRootView.startReactApplication(mReactInstanceManager, "firstpro", null);

        setContentView(mReactRootView);
        }
    @Override
    public void onBackPressed() {
        if (mReactInstanceManager != null) {
            mReactInstanceManager.onBackPressed();
        } else {
          super.onBackPressed();
        }
    }
    }


I also tried the following code in ReactNativeActivity.java

    public void onBackPressed() {
        if (mReactInstanceManager != null) {
            mReactInstanceManager.onBackPressed();
        } else {
            Intent intent = new Intent(this, MainActivity.class);
            startActivity(intent);
        }
    }



If I pressed the back button it didn't get back to android activity.

How can I get back to android activity from react-native activity using backkey?
