### ISSUE TITLE
ANDROID: undefined is not an object (evaluating 'Dimensions.get' ) 

### ISSUE THREAD

**Issue by anthonywebb** [facebook/react-native#3110]
I have some code that works fine in the barebones android sample app.

var Dimensions = require('Dimensions');
var height = (Dimensions.get('window').height;

Problem is when I use the same code in one of my components inside another file, the "undefined is not an object" error happens.  

I am running the latest 0.11.4 react native, any ideas?

**Comment by leoabacade** [comment]
same issue here, mine is running on 0.11.0. 
the android SDK build tool is 23.0.1
running on device 'Nexus 6 - 5.0.1'

I have included var Dimensions = require('Dimensions'); but still got undefined is not an object (evaluating 'Dimensions.get' )

the iOS build is just ok and working every time without including var Dimensions = require('Dimensions');

**Comment by ide** [comment]
Try `var { Dimensions } = require('react-native')`, which is the only supported way of requiring Dimensions. You should write only `require('react-native')`.

**Comment by anthonywebb** [comment]
I tried `var { Dimensions } = require('react-native')` to no avail.  Worth nothing that this only happens when you try to create a component from within a component.

**Comment by anthonywebb** [comment]
@ide I thought about passing the width/height down from app.js to all my subcomponents but there are a lot of them and it would be a fairly major overhaul. Also, if including "Dimensions" in this manner is problematic in sub components, I imagine other Libraries I include will have similar issues, so it would probably be better for me to wait for a fix.  If you need help in testing or replicating the issue please let me know.

**Comment by ide** [comment]
I expect this will be fixed in the next release (I haven't encountered this issue while using `master`).

**Comment by brentvatne** [comment]
Indeed this should be working on master, so I'm going to close this issue. If it persists on the newest version then ping @ide and myself and we can reopen!
