### ISSUE TITLE
I cant connect via wifi React Native

### ISSUE THREAD

**Issue by Husdady** [facebook/react-native#31105]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Hello programmers, I am new to RN, I have a problem that I cannot solve. I am trying to connect via wifi, my react project from my pc with the app generated on my phone.

I have followed the steps in the documentation but still cannot solve it: https://reactnative.dev/docs/running-on-device...
When I enter the development menu within the application, I go to the configuration and I enter debug server and port for device and I assign the ip of my computer and port 8081, it returns, "Could not connect to development server" and when I use ngrok, it returns me, '' Invalid URL port: '-1' "

I must clarify that I am using the react version 0.63 and my phone is android version 10, Samsung Galaxy A11 and i use window
![157439582_3749920775126460_8504866976268023236_n](https://user-images.githubusercontent.com/76859196/110187524-a8a0e980-7de6-11eb-872c-c5a3cbed1133.jpg)
![157603829_4209973549036663_1781613050716477561_n](https://user-images.githubusercontent.com/76859196/110187526-a9d21680-7de6-11eb-848e-e97f07a09d81.jpg)

.
![157204157_941912049949981_2788395090109343481_n](https://user-images.githubusercontent.com/76859196/110187668-24029b00-7de7-11eb-8cce-3fdadd229ffc.jpg)
![Uploading 157344196_446898970076810_5610527788702357108_n.jpg…]()

I need help to solve this as setting react native is very tedious and I am newbie. Thanks a lot !

## React Native version:
Run `react-native info` in your terminal and copy the results here.
React version 16.13.1
React Native version 0.63.4

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Open the in-app Developer menu.
2. Go to Dev Settings → Debug server host & port for device.
3. Type in your machine's IP address and the port of the local dev server (e.g. 10.0.1.1:8081).
4. Go back to the Developer menu and select Reload JS.

## Expected Results
Connect desktop rn project to the application generated on phone

**Comment by Eronred** [comment]
It would be better to open this **_ERROR_** on Stackoverflow because this React native issue page to solve or let the team knows about a bug/issue. The error you got has a solution on Stackoverflow.

[You can ask here](https://stackoverflow.com/search?q=React+Native+)

**Comment by Husdady** [comment]
sorry, but i searched all over stackoverflow and i can't find an answer to help me

**Comment by samithaf** [comment]
Latest Android could be blocking the request. Add the following configuration and see if that works. 

IP address 192.168.1.105 is a sample one and just add machine IP address. 

create a file, **network_security_config.xml** more details can be found [here](https://developer.android.com/training/articles/security-config)

```
<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="true">192.168.1.105</domain>
        <domain includeSubdomains="true">localhost</domain>
        <trust-anchors>
            <certificates src="system" />
            <certificates src="user" />
        </trust-anchors>
    </domain-config>
</network-security-config>
```

**Comment by Husdady** [comment]
> Latest Android could be blocking the request. Add the following configuration and see if that works.
> 
> IP address 192.168.1.105 is a sample one and just add machine IP address.
> 
> create a file, **network_security_config.xml** more details can be found [here](https://developer.android.com/training/articles/security-config)
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> <network-security-config>
>     <domain-config cleartextTrafficPermitted="true">
>         <domain includeSubdomains="true">192.168.1.105</domain>
>         <domain includeSubdomains="true">localhost</domain>
>         <trust-anchors>
>             <certificates src="system" />
>             <certificates src="user" />
>         </trust-anchors>
>     </domain-config>
> </network-security-config>
> ```

I tried it and it keeps giving the error: 'Could not connect to development server'
![Sin títuklo](https://user-images.githubusercontent.com/76859196/110227284-b036c000-7ec4-11eb-9604-5747357f6fb3.png)

**Comment by samithaf** [comment]
try the following IP address since you are using an emulator, 10.0.2.2

**Comment by Husdady** [comment]
With the emulator I don't have the connection problem, it works fine for me.

Only for a physical device it doesn't work for me.

My pc is low-resource, so the use of an emulator is not recommended. So I want to use my phone instead of an emulator, I have investigated and with 'adb connect IP_PHONE' it seems to work, the problem that only works with rooted phones and mine is not

**Comment by samithaf** [comment]
You don't need a rooted phone. Did you ran `adb reverse tcp:8081 tcp:8081` ? I am debugging the App in Samsung S10 runs on latest Android without any rooting.

**Comment by Husdady** [comment]
> You don't need a rooted phone. Did you ran `adb reverse tcp:8081 tcp:8081` ? I am debugging the App in Samsung S10 runs on latest Android without any rooting.

I tried it but it keeps giving the error. First I connect my phone to my pc and check if it is linked with `adb devices`, then I add the command you tell me and it returns `8081` in cmd, I start the project with `react-native run-android` and it follows the same problem with the ip and port from my pc: `192.168.1.36:8081`

![Sinadda tíadtulo](https://user-images.githubusercontent.com/76859196/110264801-218b7700-7f88-11eb-8f2c-bd446167b952.png)

**Comment by samithaf** [comment]
It's worth to try wireless Debugging as well and it's really easy to setup. Give it a try and see. https://developer.android.com/studio/command-line/adb

**Comment by Husdady** [comment]
> It's worth to try wireless Debugging as well and it's really easy to setup. Give it a try and see. https://developer.android.com/studio/command-line/adb
> 
> Also see the device logs in Android Studio. Hopefully it will print an error and tell why it can't speak to the metro server


Thank you very much samithaf !!!
![158985303_3680306445417730_8220382074743914199_n](https://user-images.githubusercontent.com/76859196/110385073-7b457d00-802c-11eb-9779-32816ec59d2e.jpg)
, I solved the problem by following the steps in the adb documentation.

The problem was that the IP of my cell phone is wrong when using adb connect IP-phone.

To solve this problem, follow these steps: Connect your cell phone to your pc through a usb cable, open cmd and enter adb devices to see if the phone is connected. Then write `adb tcpip 5555`, this number can be whatever you like. Now unplug your cable. Find your phone's ip in `Settings` -----> `About Phone` -----> `Status` -----> `IP Address`.
After looking for your ip, type in cmd `adb connect IP PHONE`. Ready you can now `run react-native run-android`. Note: do not use Debug Server Host and Port, leave it empty. If it is busy with an ip and port, remove it and rerun `react-native run-android`

**Comment by samithaf** [comment]
That's cool. Probably you can close the defect. :)
