### ISSUE TITLE
'gradlew.bat' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by walmac** [facebook/react-native#31103]
## Description
Please provide a clear and concise description of what the bug is. Include screenshots if needed.
Please test using the latest React Native release to make sure your issue has not already been fixed: https://reactnative.dev/docs/upgrading.html

When trying to run npx react-native run-android the console says :

```
'gradlew.bat' is not recognized as an internal or external command
error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.
Error: spawn gradlew.bat ENOENT
    at notFoundError (c:\curso\React Native\nav2\node_modules\cross-spawn\lib\enoent.js:6:26)
npm ERR! code 1
npm ERR! path c:\curso\React Native\nav2
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c react-native run-android

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\wal\AppData\Local\npm-cache\_logs\2021-03-04T23_14_03_908Z-debug.log
```

## React Native version:
$ react-native info                                                     
info Fetching system and libraries information...                       
System:                                                                 
    OS: Windows 10 10.0.19041                                           
    CPU: (8) x64 Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz              
    Memory: 6.56 GB / 15.82 GB                                          
  Binaries:                                                             
    Node: 15.8.0 - C:\Program Files\nodejs\node.EXE                     
    Yarn: 1.22.10 - C:\Program Files\nodejs\yarn.CMD                    
    npm: 7.5.1 - C:\Program Files\nodejs\npm.CMD                        
    Watchman: Not Found                                                 
  SDKs:                                                                 
    Android SDK:                                                        
      API Levels: 28, 29                                                
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 31.0.0                       
      Android NDK: Not Found                                            
    Windows SDK: Not Found                                              
  IDEs:                                                                 
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7042882          
    Visual Studio: Not Found                                            
  Languages:                                                            
    Java: 14.0.2                                                        
    Python: 2.7.18                                                      
  npmPackages:                                                          
    @react-native-community/cli: Not Found                              
    react: 16.13.1 => 16.13.1                                           
    react-native: 0.63.1 => 0.63.1                                      
    react-native-windows: Not Found                                     
  npmGlobalPackages:                                                    
    *react-native*: Not Found                                           
                                                                        

## Steps To Reproduce
run react-native init awesomeproject
cd awesomeproject
npx react-native run-android

## Expected Results
I expected the app to start, I tried using the --version modificator in init and sometimes worked but not always with version 0.63.2
<img width="955" alt="gradlew" src="https://user-images.githubusercontent.com/667026/110045255-2dc5c900-7d29-11eb-97e1-79ae2cd54c33.png">

## Snack, code example, screenshot, or link to a repository:
Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by androiddream** [comment]
shit，they didn't repair this bug

**Comment by babysharkhaha** [comment]
shit too,they didn't repair this but

**Comment by cortinico** [comment]
Closing as this is stale. Please re-open a new issue and provide your environment if the issue persists 👍
