### ISSUE TITLE
PanResponder view suddenly disappears

### ISSUE THREAD

**Issue by AnasAlamin** [facebook/react-native#31117]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
i have touchable inside a view that is a PanResponder , but after few presses the view completely disappears

## React Native version:
  Binaries:
    Node: 14.16.0 - C:\Program Files\nodejs\node.EXE     
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD        
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD       
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowAllTrustedApps: Disabled
      Versions: 10.0.18362.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: Not Found
  Languages:
    Java: Not Found
    Python: 3.9.2
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
just follow the exact tutorial react-native documentations have for PanResponder, and use Touchables a child element. 

## Expected Results
view must be always displayed and available for user to drag

**Comment by chrisglein** [comment]
Something weird with your environment info above. Looks like version 0.63.2 but the rest of the info didn't resolve. Try again?

This sounds like a Snack-able issue. Can you help out by creating an Expo snack for the exact issue you're seeing?

**Comment by AnasAlamin** [comment]
> Something weird with your environment info above. Looks like version 0.63.2 but the rest of the info didn't resolve. Try again?
> 
> This sounds like a Snack-able issue. Can you help out by creating an Expo snack for the exact issue you're seeing?

i have created a snack and the problem is still occurring, to get the error keep expanding and collapsing multiple times and it will happen eventually 

https://snack.expo.io/@antorin/moody-candy

**Comment by AnasAlamin** [comment]
i'm wondering why no one is trying to solve this issue right here :/

**Comment by chrisglein** [comment]
> i have created a snack and the problem is still occurring, to get the error keep expanding and collapsing multiple times and it will happen eventually
> 
> https://snack.expo.io/@antorin/moody-candy

Thanks for providing a Snack! After playing around with it for quite a while I was able to repro once on iOS. I'm still trying to get it to happen another time. Do you have a feel for what sequence causes it to happen? I did notice sometimes it would "jump" sometimes vertically up/down away from my finger. Were you seeing that? Maybe when it disappears it's when it's jumping but it jumps offscreen?

**Comment by chrisglein** [comment]
I've been able to reproduce it a few more times now. I don't know if I ever got it to happen in the middle of the screen, but if you bump it right to the top and start getting fast/swipey with your gestures then it's easier to get it to happen.

You could see if that hypothesis is correct by adding more aggressive checking/clamping on the values you get out of the PanResponder before applying them to your y offset.
