### ISSUE TITLE
React native takes impossibly long to build on android

### ISSUE THREAD

**Issue by marlenekoh** [facebook/react-native#31127]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Recently ejected from expo and now running react-native run-android. It's been 30 minutes and the app is still not running.

## React Native version:
Run `react-native info` in your terminal and copy the results here.
```
System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 289.24 MB / 7.89 GB
  Binaries:
    Node: 15.11.0 - ~\AppData\Local\Temp\yarn--1615379944516-0.24172967762751196\node.CMD
    Yarn: 1.22.5 - ~\AppData\Local\Temp\yarn--1615379944516-0.24172967762751196\yarn.CMD
    npm: 7.6.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.3
      System Images: android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7042882
    Visual Studio: Not Found
  Languages:
    Java: 10.0.2 - C:\Program Files\Java\jdk-10.0.2\bin\javac.EXE
    Python: 3.7.1 - C:\Users\ASUS\AppData\Local\Programs\Python\Python37\python.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: ~0.63.4 => 0.63.4
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
Done in 26.79s.
```
## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.
2.

## Expected Results
Describe what you expected to happen.
It should take 5 mins tops to get the app started.

## Snack, code example, screenshot, or link to a repository:
![image](https://user-images.githubusercontent.com/28558150/110630517-67427c80-81e0-11eb-918c-f20f4d717b9d.png)

**Comment by xenburn** [comment]
I'm not sure about the specific issue that you're having but I've had luck backing up my project and then clearing all the temp files, cache files, and node_modules and reinstalling to fix similar issues. 

Another time I had the android build hang i had to update my gradle-wrapper.properties

**Comment by satish-rajnale** [comment]
yes it takes more time as each time it build js bundles.
I am using expo and sometimes it crashes and i have to restart it and it bundles js code each time.
You can try using expo but i should say it still is in initial stages and has bugs.

**Comment by cortinico** [comment]
Closing as stale
