### ISSUE TITLE
Creating a new React-Native project does not create a buildable project - FlipperRSocket build errors

### ISSUE THREAD

**Issue by azav** [facebook/react-native#31120]
Multiple FlipperRSocket build errors prevent a new React-Native project from building on iOS.

## Description
Text files are added to build phases along with other issues in FlipperRSocket.

https://reactnative.dev/docs/upgrading.html

## React Native version:
4.14.0

## Steps To Reproduce
0. After installing React-Native as per here: https://reactnative.dev/docs/environment-setup using React Native CLI Quickstart.
1. In the Terminal, create a new project with npx react-native init MyApp
2. Compile it with npx react-native run-ios

## Expected Results
A successful build.

## Results
Multiple build errors and missing files in the build with the Flipper pod.
Open MyApp.xcworkspace and in the Pods project, locate the Build Phases for the Flipper-RSocket.a Target.  Note that within the Compiled Sources, Readme.md is added twice along with other files that should not be compiled.
Even after removing these files, multiple Flipper build errors are present.

**Comment by chrisglein** [comment]
Can you share your full environment info as well as the build errors you see?

**Comment by Schr3da** [comment]
Hey, 
you can try to modify the Podfile of your ios Project by adding a fixed version for Flipper. Please see the snippet below. 

`  use_flipper!({ 'Flipper' => '0.74.0' })`

Next ensure to delete the Podfile.lock and Pods folder.
Afterwards run 

`pod install `

to install all dependencies and try to run the project again.

regards
Schr3da

**Comment by azav** [comment]
Added the line to the pod file in the /ios directory.

Pod install returns these errors.

[!] There are duplicate dependencies on `FlipperKit/SKIOSNetworkPlugin` in `Podfile`:

- FlipperKit/SKIOSNetworkPlugin (= 0.74.0)
- FlipperKit/SKIOSNetworkPlugin (~> 0.54.0)

[!] There are duplicate dependencies on `FlipperKit/FlipperKitUserDefaultsPlugin` in `Podfile`:

- FlipperKit/FlipperKitUserDefaultsPlugin (= 0.74.0)
- FlipperKit/FlipperKitUserDefaultsPlugin (~> 0.54.0)

[!] There are duplicate dependencies on `FlipperKit/FlipperKitReactPlugin` in `Podfile`:

- FlipperKit/FlipperKitReactPlugin (= 0.74.0)
- FlipperKit/FlipperKitReactPlugin (~> 0.54.0)

[!] There are duplicate dependencies on `Flipper` in `Podfile`:

- Flipper (= 0.74.0)
- Flipper (~> 0.54.0)

[!] There are duplicate dependencies on `FlipperKit/Core` in `Podfile`:

- FlipperKit/Core (= 0.74.0)
- FlipperKit/Core (~> 0.54.0)

[!] There are duplicate dependencies on `FlipperKit/CppBridge` in `Podfile`:

- FlipperKit/CppBridge (= 0.74.0)
- FlipperKit/CppBridge (~> 0.54.0)

[!] There are duplicate dependencies on `FlipperKit/FBCxxFollyDynamicConvert` in `Podfile`:

- FlipperKit/FBCxxFollyDynamicConvert (= 0.74.0)
- FlipperKit/FBCxxFollyDynamicConvert (~> 0.54.0)

[!] There are duplicate dependencies on `FlipperKit/FBDefines` in `Podfile`:

- FlipperKit/FBDefines (= 0.74.0)
- FlipperKit/FBDefines (~> 0.54.0)

[!] There are duplicate dependencies on `FlipperKit/FKPortForwarding` in `Podfile`:

- FlipperKit/FKPortForwarding (= 0.74.0)
- FlipperKit/FKPortForwarding (~> 0.54.0)

[!] There are duplicate dependencies on `FlipperKit/FlipperKitHighlightOverlay` in `Podfile`:

- FlipperKit/FlipperKitHighlightOverlay (= 0.74.0)
- FlipperKit/FlipperKitHighlightOverlay (~> 0.54.0)

[!] There are duplicate dependencies on `FlipperKit/FlipperKitLayoutTextSearchable` in `Podfile`:

- FlipperKit/FlipperKitLayoutTextSearchable (= 0.74.0)
- FlipperKit/FlipperKitLayoutTextSearchable (~> 0.54.0)

[!] There are duplicate dependencies on `FlipperKit/FlipperKitNetworkPlugin` in `Podfile`:

- FlipperKit/FlipperKitNetworkPlugin (= 0.74.0)
- FlipperKit/FlipperKitNetworkPlugin (~> 0.54.0)

A build still reports many FlipperKit errors.  Is there a reason why this unstable project is in a default React-Native project setup?

**Comment by chrisglein** [comment]
> It might be a good idea to make sure that the default project setup has the proper version of use_flipper in the pod file so others don't run in to this too.

I don't think the long term goal would to be on a fixed version of flipper. I think this is just a temporary incompatibility? Let me know if I'm reading it wrong. Sounds like you're unblocked (yay!), so closing.
