### ISSUE TITLE
Diff in Podfile.lock when runs in different machines

### ISSUE THREAD

**Issue by franciscomorais** [facebook/react-native#31121]
## Description

When we run `pod install` we have different hashes in `FBReactNativeSpec`. This is because I think the building scripts are using full paths to generate the hash. For example, on the same machine if we rename the project directory, the hash will be different.

I think the PR that injects this bug is [this](https://github.com/facebook/react-native/pull/30792/files#diff-adcf572f001c2b710d14f409c14763f1a50b08369b3034548f1602685d21f6).

## Steps To Reproduce
1 - install node dependencies: `yarn`
2 - install ios pods dependencies: `pod install`
3 - create a commit in git: `git commit -m "whatever your want"`
4 - rename project folder: `cd ../.. && mv projectSample projectSample2 && cd projectSample2/ios`
5 - runs again pods installation command: `pod install`

## Expected Results
Podfile.lock doesn't have diffs after run `pod install --repo-update`.

## Founded Results
```diff
   ...
   FBLazyVector: 5776f027522ce1b2415982c48c8407c95966c60f
-  FBReactNativeSpec: 162f37a35ac13f9ef7ef0a77973a21393ba0dbab
+  FBReactNativeSpec: 7594b4ffdc73f2695967c9f7c766cf3c26da86a8
   Flipper: d3da1aa199aad94455ae725e9f3aa43f3ec17021
   ...
```

## React Native version:
| Module | Version |
| - | - |
| react | 17.0.1 |
| react-native | 0.64.0-rc.4 |

**Comment by madandrija** [comment]
We have the same problem, each machine generates a different `FBReactNativeSpec` hash. @franciscomorais, please add your system info, here's mine

```
System:
    OS: macOS 11.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 1.99 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.4 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.10 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_282 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.0-rc.4 => 0.64.0-rc.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by franciscomorais** [comment]
System info:

```
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-9700F CPU @ 3.00GHz
    Memory: 7.74 GB / 64.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.20.0 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.5 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.0-rc.4 => 0.64.0-rc.4
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by mlazari** [comment]
I think the issue comes from here: https://github.com/facebook/react-native/blob/00bc09c8f76879eb1f9a92a6a643191da9355de8/scripts/react_native_pods.rb#L191

The object assigned to `spec.script_phase` contains some absolute paths (for example in `srcs_dir`), which I think affects the hash in `Podfile.lock` for `FBReactNativeSpec`. The issue was probably introduced even earlier, in this commit: https://github.com/facebook/react-native/commit/c901c1fbce080c6e9b6ed56dbccaa7f2fa0571b2#diff-43504ce3403645032fd1e42a7fe7a52171a9fbd0946229948e2c6abff3681120R58

**Comment by martintreurnicht** [comment]
The root cause of this is absolute pathing in script_phase, you can inspect the resolved spec file by running:
```shell
pod ipc spec node_modules/react-native/React/FBReactNativeSpec/FBReactNativeSpec.podspec
```

**Comment by martintreurnicht** [comment]
I've created a patch file that seems to solve the problem, i might have missed something but it seems to be working great for me and builds are passing, i had a look at the generated code output too and it seems to all be there. Could be cleaned up a bit but the main issue with the current approach is that `$PODS_TARGET_SRCROOT` is not accessible from `prepare_command` so the logic will have to be split for `script_phase` and `prepare_command`, but the good news si that the working directory for `prepare_command` is that of the pod, so it's pretty safe to just assume the relative path for that.
 
```diff
diff --git a/node_modules/react-native/scripts/react_native_pods.rb b/node_modules/react-native/scripts/react_native_pods.rb
index 2a8affb..a807b2b 100644
--- a/node_modules/react-native/scripts/react_native_pods.rb
+++ b/node_modules/react-native/scripts/react_native_pods.rb
@@ -149,7 +149,7 @@ def use_react_native_codegen!(spec, options={})
   return if ENV['DISABLE_CODEGEN'] == '1'

   # The path to react-native (e.g. react_native_path)
-  prefix = options[:path] ||= File.join(__dir__, "..")
+  prefix = options[:path] ||= '$PODS_TARGET_SRCROOT/../../'

   # The path to JavaScript files
   srcs_dir = options[:srcs_dir] ||= File.join(prefix, "Libraries")
@@ -192,10 +192,12 @@ def use_react_native_codegen!(spec, options={})
     :name => 'Generate Specs',
     :input_files => [srcs_dir],
     :output_files => ["$(DERIVED_FILE_DIR)/codegen-#{codegen_modules_library_name}.log"].concat(generated_files),
-    :script => "set -o pipefail\n\nbash -l -c '#{env_vars} CODEGEN_MODULES_LIBRARY_NAME=#{codegen_modules_library_name} #{File.join(__dir__, "generate-specs.sh")}' 2>&1 | tee \"${SCRIPT_OUTPUT_FILE_0}\"",
+    :script => "set -o pipefail\n\nbash -l -c \"#{env_vars} CODEGEN_MODULES_LIBRARY_NAME=#{codegen_modules_library_name} #{File.join("$PODS_TARGET_SRCROOT/../../scripts", "generate-specs.sh")}\" 2>&1 | tee \"${SCRIPT_OUTPUT_FILE_0}\"",
     :execution_position => :before_compile,
     :show_env_vars_in_log => true
   }

-  spec.prepare_command = "#{mkdir_command} && touch #{generated_files.reduce() { |str, file| str + " " + file }}"
+
+
+  spec.prepare_command = "#{mkdir_command.sub prefix, '../../'} && touch #{generated_files.reduce() { |str, file| (str.sub prefix, '../../') + " " + (file.sub prefix, '../../') }}"
 end

```

**Comment by thaapasa** [comment]
I have encountered this same problem and reported it here: https://github.com/facebook/react-native/issues/31193 (sorry, I did not find this issue report before). For me fixing the prefix in `react_native_pods.rb` works.

**Comment by habovh** [comment]
I'm encountering a a similar behaviour with `glog` and `DoubleConversion`. It seems their checksums also change when running `pod install` on a different machine. Both of these pods are also included in React Native, but are they all related to the `FBReactNativeSpec`? If not I can open a separate issue, but I thought it would make sense to mention it here anyway.

```diff
diff --git a/ios/Podfile.lock b/ios/Podfile.lock
index a27ec70a8..8ff577408 100644
--- a/ios/Podfile.lock
+++ b/ios/Podfile.lock
@@ -673,7 +673,7 @@ SPEC CHECKSUMS:
   boost-for-react-native: 39c7adb57c4e60d6c5479dd8623128eb5b3f0f2c
   BVLinearGradient: 0d985ec461359c82bc254f26d11008bdae50d17a
   CocoaAsyncSocket: 065fd1e645c7abab64f7a6a2007a48038fdc6a99
-  DoubleConversion: cde416483dac037923206447da6e1454df403714
+  DoubleConversion: 5805e889d232975c086db112ece9ed034df7a0b2
   FBLazyVector: 7b423f9e248eae65987838148c36eec1dbfe0b53
   FBReactNativeSpec: 976b4f05ee6cfd75377064c69875f5dd09bb992d
   FBSDKCoreKit: 4afd6ff53d8133a433dbcda44451c9498f8c6ce4
@@ -686,7 +686,7 @@ SPEC CHECKSUMS:
   Flipper-PeerTalk: 116d8f857dc6ef55c7a5a75ea3ceaafe878aadc9
   Flipper-RSocket: 127954abe8b162fcaf68d2134d34dc2bd7076154
   FlipperKit: 8a20b5c5fcf9436cac58551dc049867247f64b00
-  glog: 40a13f7840415b9a77023fbcae0f1e6f43192af3
+  glog: 1f3da668190260b06b429bb211bfbee5cd790c28
   libevent: 4049cae6c81cdb3654a443be001fb9bdceff7913
   libwebp: 946cb3063cea9236285f7e9a8505d806d30e07f3
   OneSignal: fa98eaa90372bb367b6a4a1c1622ffb9832c7600
```

**Comment by mlazari** [comment]
@habovh I use `"react-native": "0.64.2"` and only have this issue with `FBReactNativeSpec`.

The versions in `Podfile.lock` are:
```
- FBReactNativeSpec (0.64.2):

- DoubleConversion (1.1.6):

- glog (0.3.5)
```

**Comment by habovh** [comment]
@mlazari so my discrepancy probably comes from something else, I'll keep investigating. Thanks for making sure this issue was not related!

**Comment by sonicdoe** [comment]
@habovh I’ve been seeing `DoubleConversion` and `glog` in my diffs as well, which seems to be due to stale pods in the `Pods` directory. Removing them (`rm -rf ios/Pods/{DoubleConversion,glog}`) and re-running `pod install` resolves that issue for me.

**Comment by habovh** [comment]
@sonicdoe I've come to the same conclusion. However I fixed it by running `pod update glog` and `pod update DoubleConversion`, which then fetches the podspec from the React Native node_modules directory! A bit quicker than removing the whole Pods folder :)

**Comment by gaberogan** [comment]
@chrisglein What's the status on this?

Our team has been running into this issue, constantly ping-ponging `Podfile.lock` changes to each other. I realize users have submitted patch-package fixes but we would appreciate if these changes could actually be merged. Thanks

**Comment by chrisglein** [comment]
> @chrisglein Chris Glein FTE What's the status on this?

No status drive by me - I've just been helping tag issues. I have no iOS expertise myself. But since there are a number of people hitting this let me see if I can flag the right folks to take a look.

**Comment by mattijsf** [comment]
Our team has it too. I haven't tried the patch-package from above yet assuming it would be patched pretty soon by the team (as it is so easy to reproduce).

I hope this can be solved soon with a proper fix 🤞

**Comment by jaredly** [comment]
thanks @martintreurnicht , that worked for me! I applied it to the 0.64.2 release here, in case it helps anyone else. I'll probably make a PR against master soon. https://github.com/Khan/react-native/tree/fix-abspath

**Comment by poiley** [comment]
@jaredly any plans to open that PR soon? Sorry to nag -- this issue is blocking me on some personal projects.

**Comment by mlazari** [comment]
> @jaredly any plans to open that PR soon? Sorry to nag -- this issue is blocking me on some personal projects.

If you can update RN to 0.65.1, this issue seems to be fixed in that version.

**Comment by shamilovtim** [comment]
Still experiencing this

**Comment by shamilovtim** [comment]
Fixed on 0.65.1, after `rm -rf /Pods`, `pod cache clean --all` and `bundle exec pod install`

**Comment by chamaldesilva** [comment]
0.64.2 still same issue

**Comment by mcarlson** [comment]
0.66.4 same issue

**Comment by mattgabor** [comment]
Still an issue with 0.66.2

**Comment by dark1451** [comment]
0.64.2 same issue, Need to upgrade my react native version?

**Comment by AdamGerthel** [comment]
Just upgraded to `0.64.3` (latest Expo-compatible version) and got this issue.

**Comment by MalinnaLeach** [comment]
Still an issue with 0.67.2, and the patch above is out of date for this version

**Comment by Mass812** [comment]
Having this issue as well 0.64.2

**Comment by harryt04** [comment]
This issue makes it so that I can't cache my pods folder on Azure pipelines because the computed hash of my `podfile.lock`  file at the end of the build is different than when it started.

**Comment by eliw00d** [comment]
I still get this from time to time and a "pod deintegrate" followed by a "pod install" usually fixes it for me. It's usually some combination of glog, RCT-Folly, and/or DoubleConversion.

**Comment by mjfruits1** [comment]
In my case, there's a difference in authors' values.
Here is the diff:
![screen_shot_2022-07-18_at_6 42 09_pm](https://user-images.githubusercontent.com/109121852/179867259-a5cfe2ab-df57-48e4-b12f-3a619b1c3cc4.png)

Did you see it? One is a string, and another is an object. This difference in JSON makes a difference in the checksum.

**Comment by ukasiu** [comment]
For us it was the node minor version mismatch. Upgrading to newest node minor fixed the problem.

**Comment by jaredly** [comment]
fwiw this is fixed for me on react-native 0.66.4

**Comment by mlazari** [comment]
@sregg Which one is the version of that 1 dev, the red or the green one? I use RN 0.71.3, I have the values on the right (green):
```
DoubleConversion: 5189b271737e1565bdce30deb4a08d647e3f5f54
glog: 04b94705f318337d7ead9e6d17c019bd9b1f6b1b
```

**Comment by sregg** [comment]
> @sregg Which one is the version of that 1 dev, the red or the green one? I use RN 0.71.3, I have the values on the right (green):
> 
> ```
> DoubleConversion: 5189b271737e1565bdce30deb4a08d647e3f5f54
> glog: 04b94705f318337d7ead9e6d17c019bd9b1f6b1b
> ```

That 1 dev is the one on the right. Everyone else is on the left 🤔

**Comment by vpetrykov** [comment]
experiencing exactly the same issue with the 1:1 checksums differences

**Comment by sregg** [comment]
We never understood why that one dev had different checksums.

**Comment by AndreasLS** [comment]
@vpetrykov @sregg I don't know if this is still an issue for you, but the problem is an update on the podspec files for glog and DoubleConversion that happened last year [here](https://github.com/facebook/react-native/blob/d9f7c4c189cf6d2ccd4b6641599b5e46898f7d0d/packages/react-native/third-party-podspecs/glog.podspec#L36).

The content have changed, but the version kept the same. Cocoapods caches those files when it resolves them from podspecs to Specifications (aka *.podspec.json). Your cache holds the old version copy of the transformed file (referencing iOS 11) and the other machine uses the new version (referencing iOS 12.4).

To fix this, you need to run a `pod cache clean --all` (or clean just those two dependencies like `pod cache clean glog` and removing all listed versions) and then running a `pod install --repo-update`. After doing this, if your repo holds the old versions hashes, upload your updated Podfile.lock.

**Comment by vpetrykov** [comment]
@AndreasLS , thanks for the suggestion about clearing caches ;) @sregg you can try to fix it in a similar way by cleaning pods caches

**Comment by Shahaed** [comment]
This specific issue should have been resolved with this commit: https://github.com/facebook/react-native/commit/751708d7798b57c9548684d152d5a3ccaf75b381

The issue could be closed.

**Comment by Reeywhaar** [comment]
Has the same three packages: DoubleConversion, boost and glog which differ on m1 and intel procs

<img width="501" alt="image" src="https://github.com/facebook/react-native/assets/884649/a4bd6ceb-cd3e-4531-bb81-2583f40a127c">

**Comment by mlazari** [comment]
@Reeywhaar If you try to remove pod caches and reinstall pods on both computers, does it fix the issue?
```
mihai@Mihais-Mac-mini ios % rm -rf ~/Library/Caches/CocoaPods
mihai@Mihais-Mac-mini ios % rm -rf ~/.cocoapods
mihai@Mihais-Mac-mini ios % rm -rf Pods                              
mihai@Mihais-Mac-mini ios % pod install

**Comment by Reeywhaar** [comment]
Nope, no luck, tried updating said pods, install with repo-update, update with repo-update, cleaning cache with `pod cache clean %podname% --all`.

**Comment by Reeywhaar** [comment]
I've also found someone in google with exact same hashes for boost, glog and DoubleConversion:
https://gitlab.ow2.org/RocketChat/Rocket.Chat.ReactNative/-/blob/5e8e359fa8d9f48d9207c2256fff9524aa231e74/ios/Podfile.lock which means it is not some per-machine hash

**Comment by mlazari** [comment]
@Reeywhaar I have the same hashes as the green ones in your screenshot on my Mac Mini with M1:
```
boost: 57d2868c099736d80fcd648bf211b4431e51a558
DoubleConversion: 5189b271737e1565bdce30deb4a08d647e3f5f54
glog: 04b94705f318337d7ead9e6d17c019bd9b1f6b1b
```

**Comment by Reeywhaar** [comment]
Indeed! Updating pods on m1 resolved the issue. Now I have correct hashes (e.g `57d286` for `boost`). My problem was because I thought hashes on m1 were correct because I did install there last. @mlazari  Thank you for the enlightenment!

**Comment by stianjensen** [comment]
The general problem with glog, DoubleConversion etc. is simply that their podspecs are often updated without bumping the version number at the same time. The hashes in your podfile is a checksum of that package's podspec file, which cocoapods only expects to change when its version number changes. This confuses cocoapods, so you need to explicitly update these packages to be able to get the correct new hash when updating react-native.

In our project we just have a permanent list of some packages to always call update on when resolving new versions (just make sure to also not run this update command on CI, where you want to only install from your lockfile).

---
Our Makefile pod install target is basically this:
```
ifeq ($(CI), true)
  POD_INSTALL_ARGS := --deployment
endif

install:
  ifneq ($(CI),true)
      cd ios && bundle exec pod update glog RCT-Folly DoubleConversion boost hermes-engine
  endif
      cd ios && bundle exec pod install ${POD_INSTALL_ARGS}
```

**Comment by jnak** [comment]
For those running into an issue with boost today, the jfrog mirror is currently down -> https://github.com/boostorg/boost/issues/842

**Comment by danidaryaweesh** [comment]
@jnak I'm running into the issue today after upgrading cocoaPods to the latest version. So we only have to wait for them to fit? or what can we do, appreciate your help here.

**Comment by jnak** [comment]
@danidaryaweesh If you have access to the filesystem , you can update the podspec file to point at Sourceforge

<img width="946" alt="Screenshot 2023-12-31 at 2 34 36 PM" src="https://github.com/facebook/react-native/assets/569169/56175e70-4874-4eea-88b8-9ad8d4deab3a">

**Comment by sanduluca** [comment]
> @danidaryaweesh If you have access to the filesystem , you can update the podspec file to point at Sourceforge
> 
> <img alt="Screenshot 2023-12-31 at 2 34 36 PM" width="946" src="https://private-user-images.githubusercontent.com/569169/293520595-56175e70-4874-4eea-88b8-9ad8d4deab3a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MjYzMTUsIm5iZiI6MTcwNDcyNjAxNSwicGF0aCI6Ii81NjkxNjkvMjkzNTIwNTk1LTU2MTc1ZTcwLTQ4NzQtNGVlYS04OGI4LTlhZDhkNGRlYWIzYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOFQxNTAwMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYjlkOGFiZGYwYTU0OTY1Nzk0MjUyM2QwZmNlNjAyNTJhY2U0MTk3OTM0ZTM0NGQ3NjdiMGZjZDkyYTZhNWU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BxPa9cF0VGcx8e10kyrZxTFmA-pzw1kNdpft2q_iYYQ">

Where is the file ?

**Comment by danidaryaweesh** [comment]
@sanduluca If you have the node_modules installed, you should find it under this path: /node_modules/react-native/third-party-podspecs/boost.podspec

**Comment by jordiepasman** [comment]
Boost looks fixed I think with the new RN versions, but I currently have the following issue that seems related or similar to the error message. 

I try to upgrade an app from 0.71.8 to 0.73.2, i get this issue.
Maybe someone have any idea what causes this issue and if there is a way to solve it? 

```
Adding spec repo `trunk` with CDN `https://cdn.cocoapods.org/`
Verifying no changes
[!] There were changes to the lockfile in deployment mode:
SPEC CHECKSUMS:
  glog:
    New Lockfile: ..........
    Old Lockfile: ..........
```

**Comment by mlazari** [comment]
@jordiepasman Did you try this https://github.com/facebook/react-native/issues/31121#issuecomment-1825568692 ?

**Comment by storm2513** [comment]
I'm upgrading an app from 0.72.9 to 0.73.2 and also get `glog` checksum issue on CI:
```
[!] There were changes to the lockfile in deployment mode:
SPEC CHECKSUMS:
  glog:
    New Lockfile: 035f1e36e53b355cf70f6434d161b36e7d21fecd
    Old Lockfile: c5d68082e772fa1c511173d6b30a9de2c05a69a2
```

I've tried https://github.com/facebook/react-native/issues/31121#issuecomment-1825568692, result is the same

**Comment by stianjensen** [comment]
> I'm upgrading an app from 0.72.9 to 0.73.2 and also get glog checksum issue on CI:

You have to run `pod update glog` once locally before committing changes to your Pod lockfile. The reason is that react-native keeps changing the contents of the glog podspec file (which the checksum is computed from), without changing its version number at the same time. This confuses cocoapods.

Check the history here where you see that the contents of the podspec is changed, but there version number is not (not even for the next release of react-native):
https://github.com/facebook/react-native/commits/fd0ca4dd6209d79ac8c93dbffac2e3dca1caeadc/packages/react-native/third-party-podspecs/glog.podspec

By explicitly calling `pod update glog` (or `bundle exec pod repo update` if you don't have a global cocoapods install), you're forcing it to 'pull the latest version' (only from your node_modules though, so you do get the version you want anyway). This way you should get the same version as a fresh box on your CI, instead of a stale version from your local cache (which cocoapods thinks is valid since they have the same version number).

**Comment by storm2513** [comment]
Running `pod update glog` (and `bundle exec pod repo update`) doesn't lead to changes to Podfile.lock, `glog` checksum stays the same.

Using Xcode 14.3.1 instead of Xcode 14.2 on CI helped though.

**Comment by mlazari** [comment]
@storm2513 I think the checksum in your Podfile.lock file is correct, I have the same one in my projects (`glog: c5d68082e772fa1c511173d6b30a9de2c05a69a2`), that's why it doesn't changes. Probably it was some caching issue on CI.

**Comment by stianjensen** [comment]
> Using Xcode 14.3.1 instead of Xcode 14.2 on CI helped though.

Tracked down the reason why you get different checksums for `glog`depending on Xcode version if you use a mix of pre-14.3 and newer versions:
https://github.com/facebook/react-native/blob/1387725aabd42e02646899a36a2f76731268191c/packages/react-native/third-party-podspecs/glog.podspec#L41-L42

These lines cause `DEFINES_MODULE` to flip between YES and NO in the generated podspec, which results in different checksums for the file.

I don't think cocoapods has a good general answer to having lockfiles shared between Xcode versions (at least not with the level of dynamic code in podspec files that react-native – necessarily – uses).
