### ISSUE TITLE
[iOS] Playing videos in webView

### ISSUE THREAD

**Issue by NishanthShankar** [facebook/react-native#3112]
It is currently not possible to play videos in a video tag from a web view

On further research in stackoverflow
This is a bug with iOS in general and can be solved by adding the 
`webview.allowsInlineMediaPlayback = YES;`

http://stackoverflow.com/questions/17922017/display-video-inside-the-uiwebview-not-in-device-full-screen

**Comment by jaygarcia** [comment]
Thanks for the PR @crash--!  @NishanthShankar , once this PR is accepted, this should probably  be closed.

**Comment by deminoth** [comment]
This should be closed.
