### ISSUE TITLE
TextInput autoCompleteType="off" does not turn off keyboard auto complete

### ISSUE THREAD

**Issue by andersonvom** [facebook/react-native#31132]
## Description
When using the `<TextInput autoCompleteType="off">` option, the android keyboard continues to offer text suggestions and auto complete bar. See https://snack.expo.io/8tU_odH5h for reproducible example.

## React Native version:
```
System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 118.00 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.20.1 - ~/.nodenv/versions/10.20.1/bin/node
    Yarn: 1.22.10 - ~/.nodenv/versions/10.20.1/bin/yarn
    npm: 6.14.4 - ~/.nodenv/versions/10.20.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /Users/amesquita/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.3/12C33 - /usr/bin/xcodebuild
  Languages:
    Java: 13.0.2 - /usr/bin/javac
    Python: 3.9.0 - /Users/amesquita/.pyenv/shims/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.4 => 0.63.4
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce

1. Add `<TextInput secureTextEntry={true} autoCompleteType="off">` and type something in the box
2. keyboard **will not** display auto complete bar, offer suggestions or save the typed text
3. Add `<TextInput secureTextEntry={false} autoCompleteType="off">` (so that you can view the password) and type something in the box
4. keyboard **will** display auto complete bar, offer suggestions or save the typed text

| autocomplete is off as expected | autocomplete should be off, but it's not |
----------------------------------|----------------------------------------
| ![autocomplete-off](https://user-images.githubusercontent.com/69922/110684473-32680280-81ab-11eb-8f4a-b34852441560.png) | ![autocomplete-not-off](https://user-images.githubusercontent.com/69922/110684472-32680280-81ab-11eb-9335-5a5587ecfd6e.png) |

## Expected Results
In both cases, the android keyboard should _not_ display the auto complete bar.

## Snack, code example, screenshot, or link to a repository:
See snack.expo here: https://snack.expo.io/8tU_odH5h

**Comment by andersonvom** [comment]
Friendly bump on this issue

**Comment by cortinico** [comment]
Closing as stale

**Comment by fabriziobertoglio1987** [comment]
Do you still experience this issue? 

I have four years of experience maintaining facebook/react-native and I specialize in the Text and TextInput components. I currently have 58 [facebook/react-native PRs](https://github.com/facebook/react-native/pulls?q=is%3Apr+author%3Afabriziobertoglio1987+). 

If you still experience this issue, I will prepare a patched release with the fix.

Thanks a lot

**Comment by AnuragTiwari1** [comment]
I am still facing this issue, I am on react native 0.70.6 and cannot upgrade to latest version, please suggest

**Comment by pvev** [comment]
I found a workaround by using: 

```
keyboardType={isPasswordVisible ? 'visible-password' : 'default'}
secureTextEntry={!isPasswordVisible}
```

with this, you should remove the autofill and even better avoid your password to get saved as a potential suggestion (that was happening when using Swiftkey and you used an special character at the end of the password).

**Comment by ashfaqdevdksa** [comment]
Still facing this issue on `react-native: 0.75.4`.
