### ISSUE TITLE
cli.js bundle command fails, as bundle is an unrecognized command

### ISSUE THREAD

**Issue by Twisterking** [facebook/react-native#31139]
So ... I tried pretty much everything ... different XCode versions, different RN versions, I ALWAYS end up with the same error: 
```
main.jsbundle does not exist. This must be a bug with
```

I then checked the logs and found the bundle command:
```
node /Users/patrick/dev/orderlion/orderlion_react_native/node_modules/react-native/cli.js bundle --entry-file index.js --platform ios --dev false --reset-cache --bundle-output [...]
```

I then tried to call the command myself and always end up with the same error: `error Unrecognized command "bundle"``

Running `node /Users/patrick/dev/orderlion/orderlion_react_native/node_modules/react-native/cli.js --help` only returns 2 commands: 
```
Commands:
  init [options] <projectName>  Initialize a new React Native project named <projectName> in a directory of the same name.
  doctor [options]              [EXPERIMENTAL] Diagnose and fix common Node.js, iOS, Android & React Native issues.
```

WTF is going on? I lost hours and hours now and I can't figure out what is happening here. A coworker of mine with pretty much the same setup can run the cmd no problem and `bundle` is a defined cmd for `cli.js`. Please help!

**Comment by jsamr** [comment]
@Twisterking Can you check which version of `@react-native-community/cli` is resolved? If you are using yarn, `yarn why @react-native-community/cli`

**Comment by jsamr** [comment]
@Twisterking Also posting the result of `npx react-native info` would help.

**Comment by cortinico** [comment]
Closing as stale
