### ISSUE TITLE
Bundle React Native code and images fail IOS

### ISSUE THREAD

**Issue by maartenvr98** [facebook/react-native#31138]
Bundle React Native code and images fail on IOS build with fastlane

``
error: File /Users/maarten/Library/Developer/Xcode/DerivedData/Project-goqststbbvdtjwabhzbxwjkowsrn/Build/Intermediates.noindex/ArchiveIntermediates/BetuweZorg/BuildProductsPath/Release-iphoneos/BetuweZorg.app/main.jsbundle does not exist. This must be a bug with

    no rule to process file '/Users/maartem/WebstormProjects/betuwezorg-nieuw/ios/Pods/Flipper-RSocket/rsocket/benchmarks/CMakeLists.txt' of type 'text' for architecture 'arm64' (in target 'Flipper-RSocket' from project 'Pods')
    no rule to process file '/Users/maarten/WebstormProjects/Project-nieuw/ios/Pods/Flipper-RSocket/rsocket/benchmarks/README.md' of type 'net.daringfireball.markdown' for architecture 'arm64' (in target 'Flipper-RSocket' from project 'Pods')
    no rule to process file '/Users/maarten/WebstormProjects/Project-nieuw/ios/Pods/Flipper-RSocket/rsocket/README.md' of type 'net.daringfireball.markdown' for architecture 'arm64' (in target 'Flipper-RSocket' from project 'Pods')
``

Anyone any ideas how to fix this?

React native version: 0.63.2
XCode version 12.0

**Comment by jsamr** [comment]
@maartenvr98 Could be duplicate of #31094 (see my fix: https://github.com/facebook/react-native/issues/31094#issuecomment-796743154); or #29477, which has been fixed in RN 0.63.3

**Comment by maartenvr98** [comment]
I reinstalled all pods and reinitialized fastlane and now my build succeeded. Don't now how and why but I'm happy 😀
