### ISSUE TITLE
When SectionList scrollToLocation function not working

### ISSUE THREAD

**Issue by elemanhillary-zz** [facebook/react-native#31136]
Say you have a SectionList Nested in a SrollView e.g

```
<ScrollView>
  <SectionList />
<ScrollView>
```

and you want to scroll to a specific section in the SectionList using scrollToLocation function, it wont work. Any help please

**Comment by lafiosca** [comment]
This might be the same problem as #25295 which was never addressed

**Comment by lafiosca** [comment]
Specifically, the error looks like this for me:

![image](https://user-images.githubusercontent.com/9442662/128268387-15e950ec-f962-4c9f-8869-e6d19f7c57f6.png)

**Comment by ralppppy** [comment]
Any update on this?

**Comment by mustafaskyer** [comment]
@roryabraham not working
