### ISSUE TITLE
[Android] ART for Android

### ISSUE THREAD

**Issue by DaleJefferson** [facebook/react-native#3114]
Are there any plans to bring ART to Android?

**Comment by astreet** [comment]
Yep, it's in our list of views we hope to release in the future: https://facebook.github.io/react-native/docs/known-issues.html#content

**Comment by dapetcu21** [comment]
Hi. Is there an rough ETA on this? I'm planning to use ART in an app for a client and he will eventually want an Android port.

**Comment by sospartan** [comment]
+1

**Comment by aexmachina** [comment]
Yes I'm also curious to know an ETA on this.

**Comment by mbrgm** [comment]
Same here ;)

**Comment by bongole** [comment]
+1

**Comment by maxs15** [comment]
+1

**Comment by maraujop** [comment]
0.18 adds Android support for ART, see commit:
https://github.com/facebook/react-native/commit/27ac04742ab4665cd529fe63fd68a30db9293b76

Although documentation is pretty much inexistent
