### ISSUE TITLE
0.64 stable new template fails when using use_frameworks!

### ISSUE THREAD

**Issue by Qwin** [facebook/react-native#31149]
Getting an error when I take the default template using "npx react-native init" and then changing Podfile to use "use_frameworks!". (removed flipper)

**Cycle inside FBReactNativeSpec; building could produce unreliable results. This usually can be resolved by moving the shell script phase '[CP-User] Generate Specs' so that it runs before the build phase that depends on its outputs.**
Cycle details:
→ Target 'FBReactNativeSpec' has link command with output '/Users/robertalmalak/Library/Developer/Xcode/DerivedData/testreact-derxgqraechlsxbpbivbctupykqo/Build/Products/Debug-iphonesimulator/FBReactNativeSpec/FBReactNativeSpec.framework/FBReactNativeSpec'
○ Target 'FBReactNativeSpec' has compile command with input '/Users/robertalmalak/testreact/testreact/ios/Pods/Target Support Files/FBReactNativeSpec/FBReactNativeSpec-dummy.m'
○ That command depends on command in Target 'FBReactNativeSpec': script phase “[CP-User] Generate Specs”
○ Target 'FBReactNativeSpec' has copy command from '/Users/robertalmalak/testreact/testreact/node_modules/react-native/React/FBReactNativeSpec/FBReactNativeSpec/FBReactNativeSpec.h' to '/Users/robertalmalak/Library/Developer/Xcode/DerivedData/testreact-derxgqraechlsxbpbivbctupykqo/Build/Products/Debug-iphonesimulator/FBReactNativeSpec/FBReactNativeSpec.framework/Headers/FBReactNativeSpec.h'
○ That command depends on command in Target 'FBReactNativeSpec': script phase “[CP-User] Generate Specs”

**Comment by Qwin** [comment]
well I found a workaround, but I am not sure why this works or if it has any side effect but my app has started working:
![image](https://user-images.githubusercontent.com/1026038/111041177-48b4cf00-83f4-11eb-89a6-9847e3f84259.png)

**Comment by Qwin** [comment]
found another workaround instead of skipping it like above you can also just change the build phase order where the Generate Specs is above the headers step:
![image](https://user-images.githubusercontent.com/1026038/111041616-43588400-83f6-11eb-87af-218c25ab3079.png)

**Comment by Qwin** [comment]
I also noticed after researching the react code that the podspec file has a environment var "DISABLE_CODEGEN=1" which disables this build phase all together. 

so to put it simply:
export DISABLE_CODEGEN="1"
pod install 

You will notice that the build phase Generate Specs will be gone. I can't imagine anyone using that build step as of now as I am thinking its only used for the new architecture of react native... this makes me wonder why its not disabled by default.

**Comment by maestor** [comment]
I had issues also with clean installation and without use_frameworks!, iOS didn't built. 

Don't know if related, but my issue was related to thing that I started ios build with yarn. It's related somehow to the fact that this Generate Specs is npm script and won't execute correctly if you run with yarn.  After I tried just `npx react-native run-ios` from manual -> build success.

**Comment by Fawxy** [comment]
Having the same issue here with an existing project and with a fresh template.

**Comment by martintreurnicht** [comment]
> found another workaround instead of skipping it like above you can also just change the build phase order where the Generate Specs is above the headers step:
> ![image](https://user-images.githubusercontent.com/1026038/111041616-43588400-83f6-11eb-87af-218c25ab3079.png)

I just moved it above headers build phase and used `patch-package` for now, i see no reason why moving that script can't be the permanent fix

**Comment by martintreurnicht** [comment]
It's a bit of a hack, but it will fix the issue while waiting for an official fix from RN, add this to your `Podfile`:

```ruby
# need to move 'Generate Specs' build_phase to be first for FBReactNativeSpec
post_install do |installer|
    installer.pods_project.targets.each do |target|
      if (target.name&.eql?('FBReactNativeSpec'))
        target.build_phases.each do |build_phase|
          if (build_phase.respond_to?(:name) && build_phase.name.eql?('[CP-User] Generate Specs'))
            target.build_phases.move(build_phase, 0)
          end
        end
      end
    end
```

**Comment by lloydsheng** [comment]
@marcelkalveram Thanks you, the fix works!

**Comment by mikehardy** [comment]
indeed - combo of use_frameworks and react-native 0.64.0 needs @martintreurnicht fix above, I cross-linked a commit implementing it in a repo I maintain to demonstrate successful builds for the react-native-firebase repo

You can use that script as a reproducible example if you like - the sed line included (which slices in Martin's fix) can be toggled on or off to reproduce the failure, but the repo starts from scratch with a clean react-native template so hopefully it's useful.

**Comment by mikehardy** [comment]
Just a note for everyone that this is still an unresolved issue for iOS users with static_frameworks as far as I know?
It was linked to the 0.64.2 cherrypicks discussion but is listed as unresolved.

Unsure on status for 0.65 but I imagine it is not resolved there as I see no related PR linked or commit reference

I'm still using the Podfile hack above successfully when instructing others how to build

**Comment by billnbell** [comment]
what is the status of this one?

**Comment by mikehardy** [comment]
This is related to react-native 0.64 which is so long ago that in the meantime building for macCatalyst broke complete, then was fixed, and then was fixed for use_frameworks ;-). I don't anticipate any motion on this one. I'm focused on react-native 0.70 cherry-picks, happy to see the CI matrix expanded to check use_frameworks to prevent regression in future (https://github.com/facebook/react-native/pulls?q=is%3Apr+matrix+sort%3Aupdated-desc ) and examining the 0.71 release when it comes out.

**Comment by mikehardy** [comment]
Irony (?), I just realized this is still live in my make-demo.sh script and just copy-pasted it in to my Podfile, but I'm not sure if it's strictly required or not. It was actually building correctly without it (react-native 0.69.5 + react-native-firebase@current), but I fear taking it out at the moment as I'm struggling with enough things that this one - which at worst should do no harm - seems okay to keep for a bit until I can test taking it out more thoroughly

Maybe others on this issue have more concrete info / experience

**Comment by ZXY101** [comment]
Just chipping in, I used your `make-demo.sh` script as reference to get a new project working with RNFB and managed to get it building without the above fix, `react-native: 0.70.2` + `@react-native-firebase/app: ^15.7.0`

**Comment by mikehardy** [comment]
Thanks, happy to hear a success report on current stable, I'll remove this baggage from my script and see how it goes

**Comment by cortinico** [comment]
Closing as all the use_frameworks! issues have been resolved in the latest stable of RN
