### ISSUE TITLE
ReAnimated Not Working Properly in /new React Native Version

### ISSUE THREAD

**Issue by FaizyQadri** [facebook/react-native#31147]
✋ To keep the backlog clean and actionable, issues will be
🚫 closed if they do not follow one of the issue templates:
👉 https://github.com/facebook/react-native/issues/new/choose

ReAnimated not working properly in new React native updates whenever we try to create new projects n use reanimated its creating bugs

**Comment by chakrihacker** [comment]
Provide more details like a reproducible repo or snack

**Comment by efstathiosntonas** [comment]
Reanimated v1 or v2? What is the bug?

**Comment by chrisbobbe** [comment]
- When you say "ReAnimated", are you talking about the ["react-native-reanimated" NPM package](https://www.npmjs.com/package/react-native-reanimated)?
- Does that package advertise support for the new React Native version?
- Have you filed an issue in the issue tracker for that package, and did the discussion there lead to any particular changes you think should be made in React Native?

**Comment by mayank-budhiraja** [comment]
> ✋ To keep the backlog clean and actionable, issues will be
> 🚫 closed if they do not follow one of the issue templates:
> 👉 https://github.com/facebook/react-native/issues/new/choose
> 
> ReAnimated not working properly in new React native updates whenever we try to create new projects n use reanimated its creating bugs

@FaizyQadri  there are many issues with the latest version of react-native. I got pods errors as well. I simply used the last stable build available.

**Comment by cortinico** [comment]
Closing as stale
