### ISSUE TITLE
Linking requires platform specific format if multiple parameters used with deeplink

### ISSUE THREAD

**Issue by samOpenforce** [facebook/react-native#31143]
## Description
I am seeing an issue where when trying to use a deep link with multiple parameters in a query string I have to use a different link format for Android than iOS.

## React Native version:
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 508.66 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.2.0 - ~/.nvm/versions/node/v14.2.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v14.2.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 20.0, macOS 11.0, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 23, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-28 | Google Play Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.0/12A8189h - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_222 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce

- Setup eventListener for deeplink opening app from cold
- Use getInitialUrl for deeplink opening app whilst already running
- Log out received URL in both cases

(See implementation below in Code Example)

then:

iOS - works using link in following format:
```
npx uri-scheme open 'myUriScheme://login/?token=MY_TOKEN&domain=MY_DOMAIN' --ios

// result: myUriScheme://login/?token=MY_TOKEN&domain=MY_DOMAIN
// result if this link format used with --android flag: myUriScheme://login/?token=MY_TOKEN

```
Android - only works if using link in following format (notice escaped `&` for second parameter)

```
npx uri-scheme open 'myUriScheme://login/?token=MY_TOKEN\&domain=MY_DOMAIN' --android

```

## Expected Results
Would expect same link format to return same URL on both platforms

## Code example
```
 useEffect(() => {
    Linking.addEventListener('url', (event) => {
      console.log('EVENT', event);
      console.log(`${Platform.OS} DEEP LINK WHEN APP RUNNING`, event.url);
    });
    AppState.addEventListener('change', handleAppStateChange);

    if (initialising) {
      authorize();
    }
    return () => {
      AppState.removeEventListener('change', handleAppStateChange);
      Linking.removeEventListener('url');
    };
  }, []);

  const handleAppStateChange = async (nextAppState) => {
    appState.current = nextAppState;
    console.log('AppState', appState.current);
    const url = await Linking.getInitialURL();
    if (url !== null) {
      console.log(`${Platform.OS} DEEP LINK WHEN APP BOOTS`, url);
    }
  };
  
  ```

Happy to supply more detail if required.

**Comment by bachhuberdesign** [comment]
Saw this GitHub issue when searching for something else, and I figured I would clear this up. This actually has nothing to do with React Native and is just an issue/quirk with `adb` itself. The `&` character is not automatically escaped before it is passed to Java. You would notice the exact same issue by running

```
adb shell am start -W -a android.intent.action.VIEW -d "myUriScheme://login/?token=MY_TOKEN&domain=MY_DOMAIN"
```

(Just as a note, uri-scheme is just a fancy wrapper around `adb` for Android and `xcrun` for iOS, see: https://github.com/expo/expo-cli/blob/master/packages/uri-scheme/src/Android.ts)
