### ISSUE TITLE
react-native and axios close debugger mode get error:  Possible Unhandled Promise Rejection (id: 0): TypeError: adapter is not a function. (In 'adapter(config)', 'adapter' is undefined)

### ISSUE THREAD

**Issue by labike** [facebook/react-native#31142]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
in react-native project, i use axios http request, i find open debugger mode http request is ok, but close debugger mode and get the error:

Possible Unhandled Promise Rejection (id: 0):
TypeError: adapter is not a function. (In 'adapter(config)', 'adapter' is undefined)
dispatchRequest@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:126295:19
tryCallOne@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:27056:16
http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:27157:27
_callTimer@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:30596:17
_callImmediatesPass@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:30635:17
callImmediates@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:30852:33
__callImmediates@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:2736:35
http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:2522:34
__guard@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:2719:15
flushedQueue@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:2521:21
flushedQueue@[native code]
callFunctionReturnFlushedQueue@[native code]
Done in 3497.10s.

look at the error like axiso error, but why debugger mode no error, close debugger mode ge thie error.  when i close debugger mode and remove axios in package.json, repeat  once 'yarn add axios' the http request is ok.

## React Native version:
"react": "16.13.1",
 "react-native": "0.63.4",

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.
2.

## Expected Results
i don't know the error in where

## Snack, code example, screenshot, or link to a repository:
![error](https://img.os4team.cn/react-native-axios-adpater.gif)

**Comment by wcldyx** [comment]
I also encountered this problem. The Promise exception could not be located. Is there a solution
