### ISSUE TITLE
Error: Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.      Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

### ISSUE THREAD

**Issue by riskymirza50** [facebook/react-native#31148]
I have an error;  Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.     
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

### **The environmental path is correctly set up. but the app is not installing on the virtual device.** I need your help. Thanks

**Comment by boonook** [comment]
I ran into the same problem

**Comment by fahadjabbar8** [comment]
having same issue

**Comment by im-subash** [comment]
Hi I ran into same problem. But i got a solution by changing the React-native > Packager: Port to **8081**.
Previously i changed to different port following old videos, now I'm able to launch the emulator. Hope this works fine for you too.

**Comment by IliaGromovCodenCare** [comment]
having the same issue, any fixes?

**Comment by Mingyang-Li** [comment]
@im-subash How did you change the package manager port? That `>` doesn't give us any context to your solution, pls elaborate

**Comment by Mingyang-Li** [comment]
@fahadjabbar8 @boonook It could've been a lot more helpful if you guys provide methods you tried to resolve this issue, rather than spamming ppl with `same issue here`... doesn't do the universe any good.

For e.g: I ran into a conbination of problems including this one for my builds, here're a few things I tried: https://github.com/facebook/react-native/issues/29568#issuecomment-1123182619

**Comment by cortinico** [comment]
Closing as this issue is not following the issue template and there is nothing really actionable to do here
