### ISSUE TITLE
Error in Cocoa pods while creating a new project in RN 0.64

### ISSUE THREAD

**Issue by vaibhavpadalia** [facebook/react-native#31156]
## Description

While creating a new project "Installing CocoaPods dependencies" fails. And on manually running "pod install" inside the iOS folder it gives a runtime error.

## React Native version:

System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
    Memory: 364.07 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.3 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.6 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.1, 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.3/12C33 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.8 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.0 => 0.64.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. npx react-native init projectName
2. cd projectName/ios && pod install

## Expected Results

Pods should get installed successfully.

## Snack, code example, screenshot, or link to a repository:

On project init:

![1](https://user-images.githubusercontent.com/23230806/111072708-c0245480-8501-11eb-992a-da083c196364.png)

On executing pod install:

![2](https://user-images.githubusercontent.com/23230806/111072710-c3b7db80-8501-11eb-87df-64a587375a66.png)

**Comment by nelsonchen5** [comment]
+1

**Comment by Qwin** [comment]
Update cocoapods to latest version (1.10.1) that should make it work.

**Comment by akimabs** [comment]
+1

**Comment by akimabs** [comment]
just install manually in folder ios, this is work for me

**Comment by vaibhavpadalia** [comment]
> Update cocoapods to latest version (1.10.1) that should make it work.

Thanks @Qwin.

All I had to do was upgrade ruby's version to 3.0 and then update my cocoapods to 1.10.1. 
And it worked.  🙌

![image](https://user-images.githubusercontent.com/23230806/111154841-aa726600-85b9-11eb-8211-01efa681eac4.png)

**Comment by kenjichanhkg** [comment]
I already have cocoapods 1.10.1.
![image](https://user-images.githubusercontent.com/7701160/111203897-8423e900-8600-11eb-8a8b-9eb4cb03be71.png)

when I do pod install, I see this:
![image](https://user-images.githubusercontent.com/7701160/111204131-c9e0b180-8600-11eb-8ed8-458e7319a6c1.png)

**Comment by kenjichanhkg** [comment]
I tried this:
sudo arch -x86_64 gem install ffi
arch -x86_64 pod install
but then I see different errors
![image](https://user-images.githubusercontent.com/7701160/111204992-ae29db00-8601-11eb-89fd-769a44a72242.png)

**Comment by kenjichanhkg** [comment]
I solved that problem after "brew install watchman"

But I still can't compile the newly init project
![image](https://user-images.githubusercontent.com/7701160/111210103-cac91180-8607-11eb-8184-c4a91aea0e9e.png)

**Comment by 452MJ** [comment]
> I solved that problem after "brew install watchman"
> 
> But I still can't compile the newly init project
> ![image](https://user-images.githubusercontent.com/7701160/111210103-cac91180-8607-11eb-8184-c4a91aea0e9e.png)

Version 0.64 has this problem on M1 machines

**Comment by liukefu2050** [comment]
Version 0.64 has this problem on M1 machines
+1

**Comment by kadiryaka** [comment]
In my case; Cocoapods could not find Flipper files.

![error](https://user-images.githubusercontent.com/5338363/111420914-1d382a00-86fd-11eb-90b8-b0a66222f4df.png)

And my solution;
`pod repo update`

and 

and ruby upgrade 3.0.0
`\curl -sSL https://get.rvm.io | bash -s stable`

maybe can help someone.

**Comment by moneyjain21** [comment]
> > Update cocoapods to latest version (1.10.1) that should make it work.
> 
> Thanks @Qwin.
> 
> All I had to do was upgrade ruby's version to 3.0 and then update my cocoapods to 1.10.1.
> And it worked. 
> 
> ![image](https://user-images.githubusercontent.com/23230806/111154841-aa726600-85b9-11eb-8211-01efa681eac4.png)

This works for me. Thanks a lot @vaibhavpadalia

**Comment by cortinico** [comment]
Closing as this version of React Native is several years old. Please re-open a new issue against the latest stable if the issue persists
