### ISSUE TITLE
[iOS] ScrollView not working smoothly on Apple M1 chip

### ISSUE THREAD

**Issue by gorhom** [facebook/react-native#31155]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description

I tried to run a new `react-native` project on `Apple M1` chip and it seems the `ScrollView` not working smoothly as it is with `Intel` chips.

The issue also appears on `v0.63.x`.

## React Native version:

```
System:
    OS: macOS 11.2.3
    CPU: (8) arm64 Apple M1
    Memory: 4.10 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.11.0 - /opt/homebrew/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 7.6.0 - /opt/homebrew/bin/npm
    Watchman: 4.9.0 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.0 => 0.64.0
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce

1. Use Apple Mac Mini 2020 with M1 Chip
2. Initialise a new `react-native` project
3. Run the iOS project

## Expected Results
Describe what you expected to happen.

## Snack, code example, screenshot, or link to a repository:

https://github.com/gorhom/react-native-m1-issue

https://user-images.githubusercontent.com/4061838/111070977-fba42c00-84cb-11eb-88a5-3e1f3367460c.mov

**Comment by gorhom** [comment]
running the simulator in Rosetta solved the issue 

https://stackoverflow.com/a/65511051

**Comment by DracotMolver** [comment]
if you don't wanna use Rosetta, maybe you can change or remove the x86 architecture from the configuration on xcode? that would be a nice test.
