### ISSUE TITLE
i have installed react native 64 and getting this error

### ISSUE THREAD

**Issue by kaneki666** [facebook/react-native#31154]
## Description
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'islameralo'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve org.checkerframework:checker-qual:2.8.1.
     Required by:
         project : > com.android.tools.build:gradle:4.1.0 > org.tensorflow:tensorflow-lite-metadata:0.1.0-rc1
      > Could not resolve org.checkerframework:checker-qual:2.8.1.
         > Could not load module metadata from C:\Users\User\.gradle\caches\modules-2\metadata-2.96\descriptors\org.checkerframework\checker-qual\2.8.1\edb68b65d2dd9b547bbf59d703899938\descriptor.bin
   > Could not resolve org.checkerframework:checker-qual:2.8.1.
     Required by:
         project : > com.android.tools.build:gradle:4.1.0 > com.android.tools.build:aaptcompiler:4.1.0 > com.google.guava:guava:28.1-jre
      > Could not resolve org.checkerframework:checker-qual:2.8.1.
         > Could not load module metadata from C:\Users\User\.gradle\caches\modules-2\metadata-2.96\descriptors\org.checkerframework\checker-qual\2.8.1\edb68b65d2dd9b547bbf59d703899938\descriptor.bin

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

## React Native version:
"react": "17.0.1",
 "react-native": "0.64.0",
 "react-native-reanimated": "^2.0.0"

## Steps To Reproduce
I havent changed anything in code just run react-native run-android and i get this error.. old version working fine

**Comment by kaneki666** [comment]
i have changed the build tools in build.gradle
 classpath("com.android.tools.build:gradle:4.1.0") to
   classpath("com.android.tools.build:gradle:3.5.3")

its working now! it would be nice if i could know why this happens? do i have to upgrade build tools sdk?
btw love the new dark mode?
is there new dos for this?

**Comment by marcocesarato** [comment]
I had the same issue, solved replacing on `android/build.gradle` the line `google()` with 
```
 maven {
     url "https://maven.aliyun.com/repository/google"
 }
```
and the line `jcenter()` with:
```
 maven {
     url "https://maven.aliyun.com/repository/jcenter"
 }
```

**Comment by rectified95** [comment]
@kaneki666 Following the comment above - is this still an issue for you?

**Comment by kaneki666** [comment]
> @kaneki666 Following the comment above - is this still an issue for you?

I have downgraded the gradle version it's working fine now! But default 4.1 doesn't work!
