### ISSUE TITLE
v0.64.0 - Number.toLocaleString() does not work in iOS when Hermes is enabled

### ISSUE THREAD

**Issue by corasan** [facebook/react-native#31152]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
When formatting a number using `toLocaleString` it does not work.

```javascript
(1234.12).toLocaleString('en-US', {
  style: 'currency',
  currency: 'USD',
})
// expected output: $1,234.12
// actual output: 1234.12
```

## React Native version:
Run `react-native info` in your terminal and copy the results here.
```
System:
    OS: macOS 11.2.3
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 2.69 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.8.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.9 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /Users/henry/.rvm/gems/ruby-3.0.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 14.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.0 => 0.64.0
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

```
## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Format a number inside  `<Text>` component.

```javascript
const FormattedNumber = () => {
  const formattedNumber = (1234.12).toLocaleString('en-US', {
    style: 'currency',
    currency: 'USD',
  })

  return <Text>{formattedNumber}</Text>
}
```

## Expected Results
Expected the number to be formatted in USD

## Snack, code example, screenshot, or link to a repository:
Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by kuasha420** [comment]
Hermes doesn't have [intl](https://github.com/facebook/hermes/issues/23) yet. You'll need a polyfill
