### ISSUE TITLE
[Text] Highlight Text on Press

### ISSUE THREAD

**Issue by satya164** [facebook/react-native#3116]
I'm working on a chat application. The messages can have links, and I need to parse the text to identify the links.

By nesting `Text` components, I'm able to give the links a blue color, and handle press on the link to open it in the browser. But it's missing one important element, it doesn't give any feedback when the link is pressed (I'm on Android).

The `TouchableHighlight` component seem to be only working for views and not for text. So I cannot use it, as the links need to be inline with the rest of the text.

Are there any plans for providing a `TouchableTextHighlight` or something like that? Or maybe even support `Text` components with `TouchableHighlight`?

Maybe my approach is all wrong. If so, is there another preferred method of handling such scenario? Maybe I could use `setNativeProps` somehow?

**Comment by brentvatne** [comment]
On iOS this is supported - nested Text with an onPress is highlighted with a grey background (as per default iOS behaviour when you touch a link within Safari) when it is touched. We should have parity for this feature on Android. What is the default behaviour on Android?

**Comment by satya164** [comment]
@brentvatne On android nothing happens. No feedback :(

**Comment by brentvatne** [comment]
@satya164 - within React Native yeah, what about within Chrome when you press on a link, what is the default behaviour? Does this seem like a reasonable effect to use?

**Comment by satya164** [comment]
@brentvatne I don't think there is any background color change unless you do it with CSS. I've never tried a web page without CSS though, but I think it's just darkening of the link.

I'll try a plain web page and reply back.

**Comment by corbt** [comment]
This is in the latest Chrome for Android:

#### Unstyled link:
![device-10-06-15 13 34 29](https://cloud.githubusercontent.com/assets/176426/10308831/77003674-6c30-11e5-8af8-c28b57af79d6.png)

#### Link OnPress:
![device-10-06-15 13 34 29](https://cloud.githubusercontent.com/assets/176426/10308869/ce66b636-6c30-11e5-847a-76262c87604c.png)

#### Visited Link (RN wouldn't implement this, just included for completeness):
![device-10-06-15 13 34 29](https://cloud.githubusercontent.com/assets/176426/10308811/4e6ddbc6-6c30-11e5-822a-30466b483539.png)

I'm happy to take a look at getting this implemented if that would be helpful.

**Comment by ssomnoremac** [comment]
@corbt Would very much like to see this implemented on Android as any serious reading application in RN would require textural interactions.

**Comment by corbt** [comment]
@ssomnoremac unfortunately at the moment I'm busy with other stuff, but I do hope someone takes this on.

**Comment by sodik82** [comment]
maybe also related to this issue - on android it is much "harder" to trigger onPress than on iOS. 

on iOS I can see highlight area around text itself and whole this area seems to respond to press event. 
on android I can quite easily touch touchablehighlight with text - but it is quite hard when I have just "inline" text with onPress.
is it possible or is it just my "wrong impression"?

**Comment by DmytroT** [comment]
on Android inline text onPress event often doesn't work
@sodik82 did you have a chance to find a solution/workaround?

**Comment by sodik82** [comment]
unfortunately not yet. as kind of workaround I have additional touchablehighlight under the text itself (in my case "tag list") - but it is not real solution to that problem.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/text-highlight-text-on-press

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
