### ISSUE TITLE
Received status code 502 from server when run react-native run-android

### ISSUE THREAD

**Issue by Rananjaya** [facebook/react-native#31166]
Could not HEAD 'https://jcenter.bintray.com/org/webkit/android-jsc/maven-metadata.xml'. Received status code 502 from server: Bad Gateway when running react-native run-android

**Comment by arwysyah** [comment]
https://github.com/react-native-community/discussions-and-proposals/issues/331


https://github.com/microsoft/react-native-test-app/pull/278#issuecomment-773198619

**Comment by arwysyah** [comment]
> [react-native-community/discussions-and-proposals#331](https://github.com/react-native-community/discussions-and-proposals/issues/331)
> 
> [microsoft/react-native-test-app#278 (comment)](https://github.com/microsoft/react-native-test-app/pull/278#issuecomment-773198619)

**Comment by 452MJ** [comment]
Try to replace `google()` & `jcenter()` with `maven { url 'https://maven.aliyun.com/repository/google' }` & `maven { url 'https://maven.aliyun.com/repository/jcenter' }`

**Comment by Rananjaya** [comment]
ok thank you
