### ISSUE TITLE
rn64 run react-native init projectName fail and run pod install fail too

### ISSUE THREAD

**Issue by liukefu2050** [facebook/react-native#31169]
Please provide all the information requested. Issues that do not follow this format are likely to stall.
    "react": "17.0.1",
    "react-native": "0.64.0"
system:mac os M1

## Description
Please provide a clear and concise description of what the bug is. Include screenshots if needed.
Please test using the latest React Native release to make sure your issue has not already been fixed: https://reactnative.dev/docs/upgrading.html

## React Native version:
info Fetching system and libraries information...
(node:39919) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
System:
    OS: macOS 11.2.3
    CPU: (8) x64 Apple M1
    Memory: 824.80 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 23, 28, 29, 30
      Build Tools: 23.0.1, 28.0.3, 29.0.2, 30.0.2
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.3/12C33 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_271 - /Library/Java/JavaVirtualMachines/jdk1.8.0_271.jdk/Contents/Home/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.0 => 0.64.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.react-native init projectName
2.cd ios run pod install

## Expected Results
Describe what you expected to happen.

## Snack, code example, screenshot, or link to a repository:
(node:39316) UnhandledPromiseRejectionWarning: Error: Failed to install CocoaPods dependencies for iOS project, which is required by this template.
Please try again manually: "cd ./xiushangApp/ios && pod install".
CocoaPods documentation: https://cocoapods.org/
    at runPodInstall (/Users/liukefu/Desktop/exampleRN/xiushangApp/node_modules/@react-native-community/cli/build/tools/installPods.js:98:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async installPods (/Users/liukefu/Desktop/exampleRN/xiushangApp/node_modules/@react-native-community/cli/build/tools/installPods.js:226:5)
    at async generateProject (/Users/liukefu/Desktop/exampleRN/xiushangApp/node_modules/@react-native-community/cli/build/commands/init/initCompat.js:136:5)
    at async Object.initCompat (/Users/liukefu/Desktop/exampleRN/xiushangApp/node_modules/@react-native-community/cli/build/commands/init/initCompat.js:105:3)
(node:39316) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

**Comment by jesper-bylund** [comment]
Why was this closed @liukefu2050 ? I just had this same issue.

**Comment by Satishpethani92** [comment]
Still, facing the same issue is there any solution for the same?
