### ISSUE TITLE
Problem when adding React Navigation Drawer - TurboModuleRegistry.getEnforcing(..)

### ISSUE THREAD

**Issue by alokPatel7** [facebook/react-native#31167]
I'm having a problem when adding a Drawer Navigator, with the 'react navigation' package.

What I have already tried:

  Tripled checked the packages listed on the documentation of React Navigation
  Re-created the project from scratch
  Installed the react-native reanimated package according to the docs on its page.
  Cleared the cache from npm and react-native.
  
Tried only with Stack Navigator, it works, the problem only appears when using Drawer Navigator

## Description
error :  Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'NativeReanimated' could not be found. Verify that a module by this name is registered in the native binary.
Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)

## React Native version:
"@react-native-community/art": "^1.2.0",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/bottom-tabs": "^5.11.8",
    "@react-navigation/drawer": "^5.12.4",
    "@react-navigation/native": "^5.9.3",
    "@react-navigation/stack": "^5.14.3",
    "react": "16.13.1",
    "react-native": "0.63.4",
    "react-native-elements": "^3.3.1",
    "react-native-floating-label-input": "^1.3.4",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-indicator": "^1.2.2",
    "react-native-material-textfield": "^0.16.1",
    "react-native-paper": "^4.7.2",
    "react-native-reanimated": "^2.0.0",
    "react-native-safe-area-context": "^3.2.0",
    "react-native-screens": "^2.18.1",
    "react-native-vector-icons": "^8.1.0"

**Comment by nazrdogan** [comment]
i think you need to use renanimated v1 , v2 not supported yet. https://github.com/react-navigation/react-navigation/issues/9423

**Comment by satya164** [comment]
Closing since this is not an issue in React Native. See https://github.com/software-mansion/react-native-reanimated/issues/1798
