### ISSUE TITLE
SectionList jumps when using `getItemLayout`

### ISSUE THREAD

**Issue by chrisdrackett** [facebook/react-native#31163]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description

We're trying to create a section list that allows the user to jump to various sections. We have it setup and have also attempted to figure out the correct format for `getItemLayout`. We're not running into issues but only with the second half of the list. Here is a snack with the approximate code we're using: https://snack.expo.io/@tiltshift/sectionlist-jumping

Note that for some reason the snack seems to perform *slightly* better than our actual code, but does still have issues when jumping to the second half of sections (in this example `p`, `o`, `s` and `f`). Also when scrolling at the bottom of the list there seems to be lag and jumping that occurs that we do not see at the top of the list.

These issues only seem to show up when not rendering the entire list at once. If we update `initialNumToRender` to render everything (say `300`) everything works great.

Also no matter where you are in the list the scrollbar seems to jump around as if the size keeps changing.
 

## React Native version:
0.63

## Steps To Reproduce

1. load up the snack (https://snack.expo.io/@tiltshift/sectionlist-jumping) and press the `f` square at the top
2. if you aren't seeing flags, scroll down till you are in the flag section
3. scroll around in the flag section
4. press `o` to go to the object section

## Expected Results

1. pressing `f` should jump to the flag section, but often takes you further up the list
2. scrolling in the second half of the list should be smooth
3. scrollbar should be steady and consistent, but it jumps around

## Snack, code example, screenshot, or link to a repository:
https://snack.expo.io/@tiltshift/sectionlist-jumping

**Comment by chrisglein** [comment]
Repro'd with your Snack. Sometimes it works fine, other times it jumps to the section and then has some additional chunky scrolling where it overshoots. Some error in the list virtualization? There doesn't seem to be any docs on [getItemLayout](https://reactnative.dev/docs/virtualizedlist#getitemlayout) to help understand dos/don'ts.

**Comment by chrisdrackett** [comment]
yep, I think its worse in our actual code, but I couldn't say why. Maybe memory related? I'm half getting around this by loading basically the entire list asap:

```
        initialNumToRender={20}
        maxToRenderPerBatch={50}
        updateCellsBatchingPeriod={10}
        windowSize={300}
```

honestly the above might be incorrect—I'm by no means an expert at using virtual lists, and this does mean if you open the list and immediately press the flag section it won't scroll all the way there. The other thing that works, but feels like a worse UX, is loading the full list on the get-go. This can be done by just not using a virtual list at all, but does cause the initial load to take longer than I would like.

**Comment by Elabar** [comment]
Having the same problem in 0.64. Any workaround without loading everything upfront?

**Comment by aitorct** [comment]
We are facing the very same problem implementing an emoji picker as well.

**Comment by Elabar** [comment]
Give [recyclerlistview](https://github.com/Flipkart/recyclerlistview) a try. It's performance is even better than flatlist in my project.

**Comment by glenne** [comment]
I had the same problem till I discovered the index passed also included the 'footer' for each section.   For example, if your data[] for each section had two rows, you would have indexes like the following:
`
0: Item0Header
1: Item0Row0
2: Item0Row1
3:Item0Footer
4: Item1Header
5: Item1Row0
6: Item1Row1
7:item1Footer
`

Things will appear to work normally for some scrolling but when new elements are created on the fly the offsets do not align properly and the list appears to 'jump' crazily if you don't account for the footer.  It can return { offset, length:0, index } if a footer is not visible.

**Comment by RaphBlanchet** [comment]
I also did the same "discovery" as @glenne , but I was still having "jumps" when using `getItemLayout` and `initialScrollIndex`. 

The problem was in my calculations of `getItemLayout`. I was considering the last `ItemSeparatorComponent` of a section as part of the last item's length, but the space was in fact created by my SectionHeader. This caused my SectionFooter to be slightly offset, which explained why my list jumped 5-6 times before going to the expected position. My length were good, but my offset weren't.

Since I had a rough time figuring all this, I decided to create a gist that could help some people in figuring out how to correctly use `initialScrollIndex` with `getItemLayout` : https://gist.github.com/RaphBlanchet/472ed013e05398c083caae6216b598b5

Hope it helps!

**Comment by ShepelE** [comment]
> I had the same problem till I discovered the index passed also included the 'footer' for each section. For example, if your data[] for each section had two rows, you would have indexes like the following: `0: Item0Header 1: Item0Row0 2: Item0Row1 3:Item0Footer 4: Item1Header 5: Item1Row0 6: Item1Row1 7:item1Footer`
> 
> Things will appear to work normally for some scrolling but when new elements are created on the fly the offsets do not align properly and the list appears to 'jump' crazily if you don't account for the footer. It can return { offset, length:0, index } if a footer is not visible.

Thanks you! I found https://medium.com/@jsoendermann/sectionlist-and-getitemlayout-2293b0b916fb this article and used react-native-section-list-get-item-layout module. It's really easy and works well! But we use reselect and it woks faster if to count all heights and offsets in selector and use those ready memoized values.
