### ISSUE TITLE
Token超期并未处理检测超期异常并处理

### ISSUE THREAD

**Issue by 13867859445** [facebook/react-native#31160]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Please provide a clear and concise description of what the bug is. Include screenshots if needed.
Please test using the latest React Native release to make sure your issue has not already been fixed: https://reactnative.dev/docs/upgrading.html

## React Native version:
Run `react-native info` in your terminal and copy the results here.

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.
2.

## Expected Results
Describe what you expected to happen.

## Snack, code example, screenshot, or link to a repository:
Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by 13867859445** [comment]
使用JWT令牌，前端有明确指出登录状态已过期，确没有在后台发现处理JWT超期的拦截机制或者，检测超期的异常处理。

**Comment by 452MJ** [comment]
这不是react-native的问题吧

**Comment by 13867859445** [comment]
找到原因了，在登录时设置了token的过期时间，并在redis维护了过期时间，在过滤器中会进行解析token，token解析超期会主动抛出过期异常，配置了认证异常处理类就会主动丢出401异常。
