### ISSUE TITLE
Could not resolve org.webkit:android-jsc:+.    when building and installing for android

### ISSUE THREAD

**Issue by Suzuhana** [facebook/react-native#31161]
## Description

I am getting this error "Could not resolve org.webkit:android-jsc:+." when trying to run "npm run android" this morning. It was working on Friday. Full detail below:
```
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve org.webkit:android-jsc:+.
     Required by:
         project :app
      > Failed to list versions for org.webkit:android-jsc.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/org/webkit/android-jsc/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/org/webkit/android-jsc/maven-metadata.xml'.
               > Read timed out
```

**********************
I started a new project from scratch using ``npx react-native init AwesomeProject`` it failed with same error.

I have another project on older version of RN at 0.63.2, which can build as expected. These ones which are having issues are on 0.63.4 and 0.64.0

Seems like remote artifact repo is down to me..

## React Native version:
Run `react-native info` in your terminal and copy the results here.

System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 33.99 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.15.0 - ~/.nvm/versions/node/v12.15.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.10 - ~/.nvm/versions/node/v12.15.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 11.3.1/11C505 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.6 - /Library/Java/JavaVirtualMachines/jdk-11.0.6.jdk/Contents/Home/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. npm run android

## Expected Results
Describe what you expected to happen.
 
It should build correctly without the issue.

**Comment by Snupas** [comment]
https://status.bintray.com/

Jcenter downloads are down at the moment.

**Comment by nyoung697** [comment]
I am getting a similar error using a fresh initialization of react native: `npx react-native init NewProject`

This is what pops up in my console when I try to run it on Android:

```
* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.facebook.flipper:flipper:0.75.1.
     Required by:
         project :app
      > Skipped due to earlier error
   > Could not resolve com.facebook.flipper:flipper-network-plugin:0.75.1.
     Required by:
         project :app
      > Skipped due to earlier error
   > Could not resolve com.facebook.flipper:flipper-fresco-plugin:0.75.1.
     Required by:
         project :app
      > Skipped due to earlier error
   > Could not resolve org.webkit:android-jsc:+.
     Required by:
         project :app
      > Failed to list versions for org.webkit:android-jsc.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/org/webkit/android-jsc/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/org/webkit/android-jsc/maven-metadata.xml'.
               > Read timed out
   > Could not resolve com.squareup.okio:okio:1.17.5.
     Required by:
         project :app > com.facebook.react:react-native:0.64.0
      > Skipped due to earlier error
   > Could not resolve com.squareup.okio:okio:1.17.5.
     Required by:
         project :app > com.facebook.react:react-native:0.64.0 > com.squareup.okhttp3:okhttp:3.12.12
      > Skipped due to earlier error
```

I recall in v0.63.x I was having issues with Flipper and had to use an earlier version.  Not sure if Flipper is causing issues again in v0.64.  It is working fine on iOS.

**Comment by Suzuhana** [comment]
@Snupas Thanks for the info.. minutes ago the page was not updated I guess :(

**Comment by ajparrah** [comment]
@Suzuhana I was getting the same error today and i knew that i did not make anything on my project. You can try to disconnect your internet... It worked for me

**Comment by Suzuhana** [comment]
I just tried again and it worked for me. closing this issue.

**Comment by ranrolls** [comment]
Getting same issue today!

**Comment by kkureli** [comment]
same issue...

**Comment by jeliel-augusto** [comment]
same issue...

**Comment by fede9612** [comment]
Same issue... help please!

**Comment by enigmablue** [comment]
+

**Comment by cristobal2323** [comment]
Same issue

**Comment by ww8007** [comment]
same issue

**Comment by QasimJaffry** [comment]
same issue

**Comment by kkureli** [comment]
can not export apk and abb because of this error

**Comment by Sbenitez-Ideas** [comment]
I think for now we just have to wait

**Comment by FarooqAlamRN** [comment]
I also have this issue, what solution right now, I have to give apk to my client asap

**Comment by antoinmaged** [comment]
Same issue, when can we now that the servers are up ?

**Comment by walidmh** [comment]
Same issue, any future solution ?

**Comment by awmoreira** [comment]
?

**Comment by FarooqAlamRN** [comment]
well, I just want to know why this error occur because last week my app runs fine but after getting GitHub pull it shows this error.......
anybody know about it?

**Comment by monddelrosario** [comment]
temporary workaround on this issue 
Check this link: https://stackoverflow.com/a/69205725

**Comment by porfidev** [comment]
Disable Wifi, actually works fine.

Tested on RN 0.63.4 on Mac M1

**Comment by ASchwad** [comment]
jcenter seems to be up again - Had the issue yesterday, but some minutes ago the app built successfully without applying any of the fixes.

**Comment by FarooqAlamRN** [comment]
hey guys! again jcenter seems to be down......
is anyone face this issues
