### ISSUE TITLE
Gradle's copyDownloadableDepsToLibs is broken, thus a buck based android build fails

### ISSUE THREAD

**Issue by farcaller** [facebook/react-native#31174]
## Description

Following the `_BUCK` header docs from a fresh react-native template fails to copy any libs into `libs` via `./gradlew :app:copyDownloadableDepsToLibs`. The project is freshly created from `npx react-native init gradletest --template react-native-template-typescript`

## React Native version:
```
System:
    OS: Linux 4.19 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor
    Memory: 18.31 GB / 50.14 GB
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.9.0 - /tmp/yarn--1615972262648-0.7182059958157456/node
    Yarn: 1.22.5 - /tmp/yarn--1615972262648-0.7182059958157456/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.9.0/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 1.8.0_282 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.0 => 0.64.0 
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Follow the `_BUCK` header comment and run `./gradlew :app:copyDownloadableDepsToLibs`

## Expected Results

Gradle copies deps to libs.

## Actual results

Gradle finds no sources to copy:

```
> Task :app:copyDownloadableDepsToLibs NO-SOURCE
Task :app:copyDownloadableDepsToLibs in app Starting
Skipping task ':app:copyDownloadableDepsToLibs' as it has no source files and no previous output files.
Task :app:copyDownloadableDepsToLibs in app Finished
:app:copyDownloadableDepsToLibs (Thread[Execution worker for ':',5,main]) completed. Took 0.005 secs.
```

**Comment by farcaller** [comment]
Also confirmed it's broken in the same way with the default (js) template

**Comment by Zeus-Syed** [comment]
@farcaller what is the solution for this issue? i am facing the same issue.

**Comment by farcaller** [comment]
@Zeus-Syed I just moved on with my life, but I'm not sure that's a proper technical solution to the problem. Unfortunately the answer seems to be "no one cares" and "it's too much hassle to support it".

**Comment by cortinico** [comment]
I'm closing this as this logic was completely removed and cleaned up in 0.71 on exactly to avoid problems like the one you're facing.
