### ISSUE TITLE
Android: auto trigger Backspace key event when numeric TextInput gets focus or blur with sogou input method.

### ISSUE THREAD

**Issue by StoneOfThree** [facebook/react-native#31175]
## Description
Android mobile Phone with Android version 10, the input method is Sogou input method. The Sogou input method has two type modes: letter mode and word mode. 

I use `<TextInput>` to create a numeric input box, switch Sogou input method's type mode to word mode. When the input box gets focus or blur, it will auto trigger Backspace key event, but i didn't type Backspace key. It is normal in letter mode.
![switch input method mode](https://user-images.githubusercontent.com/43463534/111446035-ef77d300-8746-11eb-9eeb-480c7739b139.jpg)

## React Native version:
System:

  OS: macOS 10.15.7

  CPU: (12) x64 Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz

  Memory: 94.03 MB / 16.00 GB

  Shell: 5.7.1 - /bin/zsh

 Binaries:

  Node: 12.4.0 - /usr/local/bin/node

  Yarn: 1.16.0 - /usr/local/bin/yarn

  npm: 6.9.0 - /usr/local/bin/npm

  Watchman: 4.9.0 - /usr/local/bin/watchman

 SDKs:

  iOS SDK:

   Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1

 IDEs:

  Android Studio: 3.6 AI-192.7142.36.36.6200805

  Xcode: 11.3.1/11C505 - /usr/bin/xcodebuild

 npmPackages:

  react: 16.9.0 => 16.9.0 

  react-native: 0.61.4 => 0.61.4 

 npmGlobalPackages:

  react-native-cli: 2.0.1

## Steps To Reproduce
1. Android mobile phone with Sogou input method, switch the input method to word mode;
2. Use `<TextInput>` to create a numeric input box and use onKeyPress to monitor keyboard event;
3. When the input box gets focus or blur, onKeyPress will get Backspace key event.

## Expected Results
When Sogou input method is in word mode and the numeric input box gets focus or blur, onKeyPress shouldn't get any key event.

## Snack, code example, screenshot, or link to a repository:
```react
onKeyPress = (event) => {
    console.log('onKeyPress keyValue ====> ' + event.nativeEvent.key);
}
<TextInput
    value={value}
    maxLength={1000}
    onChangeText={value => {
        this.setState({value});
    }}
    keyboardType={'numeric'}
    onKeyPress={this.onKeyPress}
/>
```

**Comment by 996321301** [comment]
I got the same problem
