### ISSUE TITLE
Axios Request to local server getting [Network Error]

### ISSUE THREAD

**Issue by mahiraltinkaya** [facebook/react-native#31178]
## Description
I simply get the [Error: Network Error] error when I want to send a request to a local server with AXIOS or FETCH.
I'm running my work on the Remote Phone. My server is NGINX local and its IP is 192.168.1.102. Application IP address 192.168.1.100. 

```

    android:usesCleartextTraffic="true"
    android:networkSecurityConfig="@xml/network_security_config"
```

```

<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="false">localhost</domain>
        <domain includeSubdomains="false">10.0.2.2</domain>
        <domain includeSubdomains="false">10.0.3.2</domain>
        <domain includeSubdomains="false">192.168.1.102</domain>
    </domain-config>
</network-security-config>
```

![image](https://user-images.githubusercontent.com/25014707/111496477-674afb00-8751-11eb-82e1-4ebfabb11f19.png)

![image](https://user-images.githubusercontent.com/25014707/111496563-7762da80-8751-11eb-87c1-d9b613cc73e1.png)

![image](https://user-images.githubusercontent.com/25014707/111496703-93ff1280-8751-11eb-812d-603669f3cb8e.png)

![image](https://user-images.githubusercontent.com/25014707/111496886-b729c200-8751-11eb-9cb6-d232122483d3.png)

## React Native version:
"react-native": "~0.63.4",

**Comment by emuter** [comment]
i figured still some people are struggling with this issue.
here's what you could do in windows environment.

1. create a local domain.
2. put the created domain name in etc host file.
3. point the created domain to your pc in your network router ( better with internet connection )
4. point the domain in your local dev server vhost file.
