### ISSUE TITLE
Firebase.app is not a function

### ISSUE THREAD

**Issue by satish-rajnale** [facebook/react-native#31172]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
As working on my app the firebase is connected and running properly but after sometime it suddenly throws some error.

## React Native version:
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@react-navigation/native": "^5.9.3",
    "@react-navigation/stack": "^5.14.3",
    "expo": "~40.0.0",
    "expo-status-bar": "~1.0.3",
    "firebase": "^8.3.0",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz",
    "react-native-elements": "^3.3.1",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-web": "~0.13.12"
  },
  "devDependencies": {
    "@babel/core": "~7.9.0"
  },
  "private": true
}

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. if i change something in my firebase file and run again sometimes it throws errors each time being different one.
2.And if I remove firebase and reinstall it , it works but i want to know why it happens

## Expected Results
Describe what you expected to happen.
expected to connect to firebase and get user info and messages

## Snack, code example, screenshot, or link to a repository:
satish-rajnale/Signal-app-2.0

**Comment by chrisbobbe** [comment]
Could you talk more about why you suspect this is an issue with React Native, and not with something else, such as Firebase, Expo, or your own project's code? 🙂

**Comment by satish-rajnale** [comment]
So as i was working today building a signal clone app i by mistake put (firebase.apps.length===0) where it should have been (firebase.app.length===0) but the whole period working on my chat screen i didnt get an error.
At one point i got stuck at a minor issue so i just restarted metro bundler to see if that solves the issue but instead it showed me that firebase.apps is not a function. So okay i got it my mistake. 
But when i corrected it , there was another issue coming up again with the firebase calling could not find firebase.app in module node_modules/firebase/app/firebase.js 
So i think my firebase module files got deleted or something but i think its a problem with react native or expo because on my other projects with reactjs & firebase i never got this problem.
