### ISSUE TITLE
0.64 with Hermes debugger unusuably unstable and buggy on iOS

### ISSUE THREAD

**Issue by canpoyrazoglu** [facebook/react-native#31188]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
After upgrading to RN 0.64 from 0.63.x, I tried to use Hermes and debugger isn't working with it. In addition, everything, especially logging to the debugger console is considerably slower. Logging to debugger works but breakpoints aren't working. 

## React Native version:
System:
    OS: macOS 11.2.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 18.65 GB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.9.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.7 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      Android NDK: 17.2.4988734
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6858069
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 10.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.1 => 17.0.1 
    react-native: 0.64 => 0.64.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Upgrade to React Native 0.64
2. Enable Hermes support in Podfile with `:hermes_enabled => true` in `use_react_native` call.
3. Install pods and run the project on iOS device (iOS version and device doesn't seem to change anything, tried different combinations)
4. Try to debug your app. Nothing happens (my debugger is ready to attach as usual). Picking Open Debugger from developer menu does nothing.

## Expected Results
App should debug correctly like the old Chrome debugger.

## Snack, code example, screenshot, or link to a repository:
Setting `:hermes_enabled => false` and reinstalling pods fixes the issue by removing Hermes, and I verify that I can debug my application correctly again. Also, when using Hermes, I've realized that logging anything to the debugger console with regular `console.log` is much more slower than using the old debugger. (it's just extra info; the bug that I described exists regardless of the console logging)

**Comment by oleksandr-dziuban** [comment]
Hello @canpoyrazoglu , you can’t debug Hermes JS code because you need Flipper debug tool should be installed. Open debugger opens the Flipper app with Source tab and you can debug everything. Works fine, just tested on my projects

**Comment by cavalos0086** [comment]
@canpoyrazoglu  
You can't debug Hermes JS code the way it used to work before. Here is the link on how to do it https://reactnative.dev/docs/hermes

**Comment by IbrahimCanKALYA** [comment]
same problem i can't debug ios with hermes 

i made all steps on this link  and still won't work :(
https://reactnative.dev/docs/hermes

**Comment by cortinico** [comment]
Closing as this version of React Native is several years old. Please re-open a new issue against the latest stable if the issue persists
