### ISSUE TITLE
RN 0.64 SectionList stickySectionHeadersEnabled with different heights

### ISSUE THREAD

**Issue by m4tkv** [facebook/react-native#31183]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
When I use SectionList with stickySectionHeadersEnabled and some headers are larger than others, then the larger header appears below the smaller one. This was not the case in the previous version.

## React Native version:
0.64.0

## Steps To Reproduce
1) Create a project
2) add SectionList with stickySectionHeadersEnabled
3) The first heading should be larger than the rest
4) scroll until the first heading starts hiding under the second
5) The larger heading is visible under the small

## Expected Results
Any previous heading should not be shown in the next section

## Snack, code example, screenshot, or link to a repository:
![image](https://user-images.githubusercontent.com/43599677/111591957-30b8c300-87d9-11eb-9e91-75e26d2f7371.png)
![image](https://user-images.githubusercontent.com/43599677/111591983-3adac180-87d9-11eb-8a8d-7ab584873c03.png)
![image](https://user-images.githubusercontent.com/43599677/111592018-46c68380-87d9-11eb-8444-b167d998fe24.png)
![image](https://user-images.githubusercontent.com/43599677/111592037-50e88200-87d9-11eb-8cbc-45a1d97550b8.png)

**Comment by cheeeke12** [comment]
Similarly

**Comment by demchenkoalex** [comment]
have the same problem, on 0.63.4 everything was good, the problem is not in the different heights of the header, the problem is that the header is not being pushed off the screen, they are just stack on top of each other. I have a shadow on a header and I can see that all the headers are in one place since the shadow becomes darker and darker with each section. Tried to find the commit which caused this, but wasn't able to do it in a reasonable time 😕

**Comment by Bardiamist** [comment]
Same issue

**Comment by m4tkv** [comment]
> have the same problem, on 0.63.4 everything was good, the problem is not in the different heights of the header, the problem is that the header is not being pushed off the screen, they are just stack on top of each other. I have a shadow on a header and I can see that all the headers are in one place since the shadow becomes darker and darker with each section. Tried to find the commit which caused this, but wasn't able to do it in a reasonable time 😕

If u find solution add patch-package commit or fork please

**Comment by Bardiamist** [comment]
Want to say about iOS: `stickySectionHeadersEnabled` also works not good. It broken in 10-30%. Only app relaunch helping.

As I remember on iOS it was and in on 0.63.4.
On Android broken in 0.64.0.

**Comment by m4tkv** [comment]
I found a temporary solution. In any case, edits from the developers are needed.

RN 0.64.1

use patch-package

`
diff --git a/node_modules/react-native/Libraries/Components/ScrollView/ScrollViewStickyHeader.js b/node_modules/react-native/Libraries/Components/ScrollView/ScrollViewStickyHeader.js
index 8d53db0..ce4b525 100644
--- a/node_modules/react-native/Libraries/Components/ScrollView/ScrollViewStickyHeader.js
+++ b/node_modules/react-native/Libraries/Components/ScrollView/ScrollViewStickyHeader.js
@@ -16,7 +16,7 @@ import StyleSheet from '../../StyleSheet/StyleSheet';
 import View from '../View/View';
 import Platform from '../../Utilities/Platform';
 
-import type {LayoutEvent} from '../../Types/CoreEventTypes';
+import type { LayoutEvent } from '../../Types/CoreEventTypes';
 
 const AnimatedView = AnimatedImplementation.createAnimatedComponent(View);
 
@@ -60,11 +60,11 @@ class ScrollViewStickyHeader extends React.Component<Props, State> {
   // Fabric-only:
   _timer: ?TimeoutID;
   _animatedValueListenerId: string;
-  _animatedValueListener: (valueObject: $ReadOnly<{|value: number|}>) => void;
+  _animatedValueListener: (valueObject: $ReadOnly<{| value: number |}>) => void;
   _debounceTimeout: number = Platform.OS === 'android' ? 15 : 64;
 
   setNextHeaderY(y: number) {
-    this.setState({nextHeaderLayoutY: y});
+    this.setState({ nextHeaderLayoutY: y });
   }
 
   UNSAFE_componentWillReceiveProps(nextProps: Props) {
@@ -77,10 +77,7 @@ class ScrollViewStickyHeader extends React.Component<Props, State> {
     }
   }
 
-  updateTranslateListener(
-    translateY: AnimatedImplementation.Interpolation,
-    isFabric: boolean,
-  ) {
+  updateTranslateListener(translateY: AnimatedImplementation.Interpolation, isFabric: boolean) {
     if (this._translateY != null && this._animatedValueListenerId != null) {
       this._translateY.removeListener(this._animatedValueListenerId);
     }
@@ -107,7 +104,7 @@ class ScrollViewStickyHeader extends React.Component<Props, State> {
       //    your finger, the hit-detection moves from the Android
       //    platform to JS, so we need the ShadowTree to have knowledge
       //    of the current position.
-      this._animatedValueListener = ({value}) => {
+      this._animatedValueListener = ({ value }) => {
         // When the AnimatedInterpolation is recreated, it always initializes
         // to a value of zero and emits a value change of 0 to its listeners.
         if (value === 0 && !this._haveReceivedInitialZeroTranslateY) {
@@ -129,9 +126,7 @@ class ScrollViewStickyHeader extends React.Component<Props, State> {
     if (this.state.translateY !== 0 && this.state.translateY != null) {
       this._haveReceivedInitialZeroTranslateY = false;
     }
-    this._animatedValueListenerId = translateY.addListener(
-      this._animatedValueListener,
-    );
+    this._animatedValueListenerId = translateY.addListener(this._animatedValueListener);
   }
 
   _onLayout = event => {
@@ -167,100 +162,90 @@ class ScrollViewStickyHeader extends React.Component<Props, State> {
   render(): React.Node {
     // Fabric Detection
     // eslint-disable-next-line dot-notation
-    const isFabric = !!(
-      this._ref && this._ref['_internalInstanceHandle']?.stateNode?.canonical
-    );
+    const isFabric = !!(this._ref && this._ref['_internalInstanceHandle']?.stateNode?.canonical);
 
     // Initially and in the case of updated props or layout, we
     // recreate this interpolated value. Otherwise, we do not recreate
     // when there are state changes.
-    if (this._shouldRecreateTranslateY) {
-      const {inverted, scrollViewHeight} = this.props;
-      const {measured, layoutHeight, layoutY, nextHeaderLayoutY} = this.state;
-      const inputRange: Array<number> = [-1, 0];
-      const outputRange: Array<number> = [0, 0];
 
-      if (measured) {
-        if (inverted) {
-          // The interpolation looks like:
-          // - Negative scroll: no translation
-          // - `stickStartPoint` is the point at which the header will start sticking.
-          //   It is calculated using the ScrollView viewport height so it is a the bottom.
-          // - Headers that are in the initial viewport will never stick, `stickStartPoint`
-          //   will be negative.
-          // - From 0 to `stickStartPoint` no translation. This will cause the header
-          //   to scroll normally until it reaches the top of the scroll view.
-          // - From `stickStartPoint` to when the next header y hits the bottom edge of the header: translate
-          //   equally to scroll. This will cause the header to stay at the top of the scroll view.
-          // - Past the collision with the next header y: no more translation. This will cause the
-          //   header to continue scrolling up and make room for the next sticky header.
-          //   In the case that there is no next header just translate equally to
-          //   scroll indefinitely.
-          if (scrollViewHeight != null) {
-            const stickStartPoint = layoutY + layoutHeight - scrollViewHeight;
-            if (stickStartPoint > 0) {
-              inputRange.push(stickStartPoint);
-              outputRange.push(0);
-              inputRange.push(stickStartPoint + 1);
-              outputRange.push(1);
-              // If the next sticky header has not loaded yet (probably windowing) or is the last
-              // we can just keep it sticked forever.
-              const collisionPoint =
-                (nextHeaderLayoutY || 0) - layoutHeight - scrollViewHeight;
-              if (collisionPoint > stickStartPoint) {
-                inputRange.push(collisionPoint, collisionPoint + 1);
-                outputRange.push(
-                  collisionPoint - stickStartPoint,
-                  collisionPoint - stickStartPoint,
-                );
-              }
+    const { inverted, scrollViewHeight } = this.props;
+    const { measured, layoutHeight, layoutY, nextHeaderLayoutY } = this.state;
+    const inputRange: Array<number> = [-1, 0];
+    const outputRange: Array<number> = [0, 0];
+
+    if (measured) {
+      if (inverted) {
+        // The interpolation looks like:
+        // - Negative scroll: no translation
+        // - `stickStartPoint` is the point at which the header will start sticking.
+        //   It is calculated using the ScrollView viewport height so it is a the bottom.
+        // - Headers that are in the initial viewport will never stick, `stickStartPoint`
+        //   will be negative.
+        // - From 0 to `stickStartPoint` no translation. This will cause the header
+        //   to scroll normally until it reaches the top of the scroll view.
+        // - From `stickStartPoint` to when the next header y hits the bottom edge of the header: translate
+        //   equally to scroll. This will cause the header to stay at the top of the scroll view.
+        // - Past the collision with the next header y: no more translation. This will cause the
+        //   header to continue scrolling up and make room for the next sticky header.
+        //   In the case that there is no next header just translate equally to
+        //   scroll indefinitely.
+        if (scrollViewHeight != null) {
+          const stickStartPoint = layoutY + layoutHeight - scrollViewHeight;
+          if (stickStartPoint > 0) {
+            inputRange.push(stickStartPoint);
+            outputRange.push(0);
+            inputRange.push(stickStartPoint + 1);
+            outputRange.push(1);
+            // If the next sticky header has not loaded yet (probably windowing) or is the last
+            // we can just keep it sticked forever.
+            const collisionPoint = (nextHeaderLayoutY || 0) - layoutHeight - scrollViewHeight;
+            if (collisionPoint > stickStartPoint) {
+              inputRange.push(collisionPoint, collisionPoint + 1);
+              outputRange.push(collisionPoint - stickStartPoint, collisionPoint - stickStartPoint);
             }
           }
+        }
+      } else {
+        // The interpolation looks like:
+        // - Negative scroll: no translation
+        // - From 0 to the y of the header: no translation. This will cause the header
+        //   to scroll normally until it reaches the top of the scroll view.
+        // - From header y to when the next header y hits the bottom edge of the header: translate
+        //   equally to scroll. This will cause the header to stay at the top of the scroll view.
+        // - Past the collision with the next header y: no more translation. This will cause the
+        //   header to continue scrolling up and make room for the next sticky header.
+        //   In the case that there is no next header just translate equally to
+        //   scroll indefinitely.
+        inputRange.push(layoutY);
+        outputRange.push(0);
+        // If the next sticky header has not loaded yet (probably windowing) or is the last
+        // we can just keep it sticked forever.
+        const collisionPoint = (nextHeaderLayoutY || 0) - layoutHeight;
+        if (collisionPoint >= layoutY) {
+          inputRange.push(collisionPoint, collisionPoint + 1);
+          outputRange.push(collisionPoint - layoutY, collisionPoint - layoutY);
         } else {
-          // The interpolation looks like:
-          // - Negative scroll: no translation
-          // - From 0 to the y of the header: no translation. This will cause the header
-          //   to scroll normally until it reaches the top of the scroll view.
-          // - From header y to when the next header y hits the bottom edge of the header: translate
-          //   equally to scroll. This will cause the header to stay at the top of the scroll view.
-          // - Past the collision with the next header y: no more translation. This will cause the
-          //   header to continue scrolling up and make room for the next sticky header.
-          //   In the case that there is no next header just translate equally to
-          //   scroll indefinitely.
-          inputRange.push(layoutY);
-          outputRange.push(0);
-          // If the next sticky header has not loaded yet (probably windowing) or is the last
-          // we can just keep it sticked forever.
-          const collisionPoint = (nextHeaderLayoutY || 0) - layoutHeight;
-          if (collisionPoint >= layoutY) {
-            inputRange.push(collisionPoint, collisionPoint + 1);
-            outputRange.push(
-              collisionPoint - layoutY,
-              collisionPoint - layoutY,
-            );
-          } else {
-            inputRange.push(layoutY + 1);
-            outputRange.push(1);
-          }
+          inputRange.push(layoutY + 1);
+          outputRange.push(1);
         }
       }
-
-      this.updateTranslateListener(
-        this.props.scrollAnimatedValue.interpolate({
-          inputRange,
-          outputRange,
-        }),
-        isFabric,
-      );
     }
 
+    this.updateTranslateListener(
+      this.props.scrollAnimatedValue.interpolate({
+        inputRange,
+        outputRange,
+      }),
+      isFabric,
+    );
+
     const child = React.Children.only(this.props.children);
 
     // TODO T68319535: remove this if NativeAnimated is rewritten for Fabric
     const passthroughAnimatedPropExplicitValues =
       isFabric && this.state.translateY != null
         ? {
-            style: {transform: [{translateY: this.state.translateY}]},
+            style: { transform: [{ translateY: this.state.translateY }] },
           }
         : null;
 
@@ -273,11 +258,10 @@ class ScrollViewStickyHeader extends React.Component<Props, State> {
         style={[
           child.props.style,
           styles.header,
-          {transform: [{translateY: this._translateY}]},
+          { transform: [{ translateY: this._translateY ?? 0 }] },
         ]}
-        passthroughAnimatedPropExplicitValues={
-          passthroughAnimatedPropExplicitValues
-        }>
+        passthroughAnimatedPropExplicitValues={passthroughAnimatedPropExplicitValues}
+      >
         {React.cloneElement(child, {
           style: styles.fill, // We transfer the child style to the wrapper.
           onLayout: undefined, // we call this manually through our this._onLayout
diff --git a/node_modules/react-native/scripts/.packager.bat b/node_modules/react-native/scripts/.packager.bat
new file mode 100644
index 0000000..e89260e
--- /dev/null
+++ b/node_modules/react-native/scripts/.packager.bat
@@ -0,0 +1 @@
+set RCT_METRO_PORT=8081
\ No newline at end of file

`

**Comment by mattg95** [comment]
@m4tkV could you format that patch to the same standards as the base file, or provide the line that's changed? It's hard to read that diff as it has lots of formatting changes

**Comment by m4tkv** [comment]
> @m4tkv could you format that patch to the same standards as the base file, or provide the line that's changed? It's hard to read that diff as it has lots of formatting changes

Sorry I lost this file. 1 more way is to update React Native version, if u use 0.64

**Comment by mattg95** [comment]
I did, thanks, although the file looks different than the example due to the fact I'm using React Native 0.66.1

**Comment by m4tkv** [comment]
> I did, thanks, although the file looks different than the example due to the fact I'm using React Native 0.66.1

this patch only for 0.64.
We havent got problems on 0.66.1.
Try red RN changelog, I dont remember version in witch it fixed

**Comment by mattg95** [comment]
> 

Ok. I am seeing the following bug in 0.66.1. The dates to the side are sectionListHeaders that are not stacking correctly on Android only. I'm not sure if this is the same bug or needs a new thread.

https://user-images.githubusercontent.com/45606434/175011563-69f89bae-5746-4197-91d2-4e80c6581c35.mov

**Comment by m4tkv** [comment]
> > 
> 
> Ok. I am seeing the following bug in 0.66.1. The dates to the side are sectionListHeaders that are not stacking correctly on Android only. I'm not sure if this is the same bug or needs a new thread.
> 
>  section-list-bug-cropped.2.mov
 
I think u can resolve this behaviour, if add white background between dates. Bottom dates will be layered
