### ISSUE TITLE
Empty demo ('react-native init Demo') shows console log.errors under iOS 9 

### ISSUE THREAD

**Issue by aksonov** [facebook/react-native#3118]
<Error>: CGContextSaveGState: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.

**Comment by ide** [comment]
This is a bug in iOS 9. You can suppress the warnings by turning on UIViewController-based status bar appearance in the Info.plist but do note this will break StatusBarIOS. Otherwise ignore it, it doesn't seem to break anything.
