### ISSUE TITLE
Border dont work in react native in release ipa sometime for iphones 

### ISSUE THREAD

**Issue by ShubhamC78** [facebook/react-native#31184]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Sometime the react native style dont work in iOS Devices in my case border is not working  beacuse of it entire UI is not looking  good kindly help to fix this .

## React Native version:
System:
    OS: macOS 11.2.3
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 75.96 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 30.0.3
      System Images: android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.2/12B45b - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_271 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: ^0.63.2 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

Expected :- <img width="322" alt="Screen Shot 2021-03-18 at 1 54 39 PM" src="https://user-images.githubusercontent.com/46701268/111595153-d9731c80-87f1-11eb-9a61-732766d06d47.png">
<img width="329" alt="Screen Shot 2021-03-18 at 1 53 41 PM" src="https://user-images.githubusercontent.com/46701268/111595126-ceb88780-87f1-11eb-8af4-85b196e86e71.png">

Result in iphone XR (Also sometime in any iphone device ): - 
<img width="315" alt="MicrosoftTeams-image (1)" src="https://user-images.githubusercontent.com/46701268/111595335-0a535180-87f2-11eb-931d-2fc3bb928807.png">

<img width="309" alt="MicrosoftTeams-image" src="https://user-images.githubusercontent.com/46701268/111595365-117a5f80-87f2-11eb-971c-02e37b202209.png">

Style for container (Code): 
tilesContainer: {
        flex: 0.5,
        borderRadius: 15,
        margin: 6,
        backgroundColor: colorCode.BACKGROUND_WHITE,
        height: 175,
        margin: (height > 593) ? 9 : 8,
        shadowColor: colorCode.BLACK,
        shadowOffset: {
            width: 0,
            height: 1,
        },
        shadowOpacity: 0.1,
        shadowRadius: 2,
        elevation: 2,
        borderWidth: 1,
    }

## Expected Results
This border should always be there in both android and ios all phones

**Comment by cortinico** [comment]
Closing as stale
