### ISSUE TITLE
[TEXT] interaction on each word, longPress to highlight the Text.

### ISSUE THREAD

**Issue by sangolariel** [facebook/react-native#31187]
## Description
I have a future that handles by text, I want users can interact with each word, my app will show a modal to note comments for this word and this word will be a highlight. And I can know the position of this word for some handle. please see the image below:

## React Native version:
0.63

## Steps To Reproduce
- Make a Text In React Native.

## Expected Results
- Users can interact with each word. and highlight it when select.

Thanks!

![Screen Shot 2021-03-18 at 17 06 07](https://user-images.githubusercontent.com/53005814/111609512-f49f5580-880c-11eb-993e-bf038eb679a1.png)

**Comment by cortinico** [comment]
Closing as stale

**Comment by fabriziobertoglio1987** [comment]
Do you still experience this issue? 

I have four years of experience maintaining facebook/react-native and I specialize in the Text and TextInput components. I currently have 58 [facebook/react-native PRs](https://github.com/facebook/react-native/pulls?q=is%3Apr+author%3Afabriziobertoglio1987+). 

If you still experience this issue, I will prepare a patched release with the fix.

Thanks a lot
