### ISSUE TITLE
[iOS] Unable to find a specification for `RCT-Folly (= 2020.01.13.00)` depended upon by `FBReactNativeSpec`

### ISSUE THREAD

**Issue by CoderYLZhang** [facebook/react-native#31185]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Please provide a clear and concise description of what the bug is. Include screenshots if needed.
Please test using the latest React Native release to make sure your issue has not already been fixed: https://reactnative.dev/docs/upgrading.html

## React Native version: 
Run `react-native info` in your terminal and copy the results here.

System:
    OS: macOS 11.2.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 479.55 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.12.0 - /usr/local/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.10.1 - /Users/zhangyinlong/.rvm/rubies/ruby-3.0.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.0 => 0.64.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

![image](https://user-images.githubusercontent.com/13221319/111602908-cae72e00-880e-11eb-8e2a-52e003d94443.png)

1. react-native 0.63.4 -> 0.64.0
2. pod install
3. 
![image](https://user-images.githubusercontent.com/13221319/111603107-f8cc7280-880e-11eb-8288-27c169cea99d.png)
4. `pod repo update` not help

## Expected Results
Describe what you expected to happen.

## Snack, code example, screenshot, or link to a repository:
Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by milesj** [comment]
@CoderYLZhang Running into this as well, what was the fix?

**Comment by CoderYLZhang** [comment]
> @CoderYLZhang Running into this as well, what was the fix?
change
`pod 'Folly', :podspec => './node_modules/react-native/third-party-podspecs/Folly.podspec'`
to
`pod 'RCT-Folly', :podspec => './RN/node_modules/react-native/third-party-podspecs/RCT-Folly.podspec'`

**Comment by CoderYLZhang** [comment]
> @CoderYLZhang Running into this as well, what was the fix?

change
`pod 'Folly', :podspec => './node_modules/react-native/third-party-podspecs/Folly.podspec'`
to
`pod 'RCT-Folly', :podspec => './RN/node_modules/react-native/third-party-podspecs/RCT-Folly.podspec'`

**Comment by milesj** [comment]
@CoderYLZhang Awesome thanks, will try.

**Comment by dvetal** [comment]
@CoderYLZhang appreciate the suggestion but it does not fix for me.

**Comment by AayushiT** [comment]
@CoderYLZhang Thanks, but same issue I am facing

**Comment by infostreams** [comment]
@dvetal @AayushiT the path in that new line is weird. What worked for me is the following:

change

    pod 'Folly', :podspec => './node_modules/react-native/third-party-podspecs/Folly.podspec'

to

    pod 'RCT-Folly', :podspec => '../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec'
