### ISSUE TITLE
build error raised with RN0.64

### ISSUE THREAD

**Issue by kockok** [facebook/react-native#31198]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
I got this when building via XCode 12.4:
```
ld: warning: Could not find or use auto-linked library 'swiftWebKit'
Undefined symbols for architecture arm64:
  "__swift_FORCE_LOAD_$_swiftWebKit", referenced from:
      __swift_FORCE_LOAD_$_swiftWebKit_$_lottie_react_native in liblottie-react-native.a(ContainerView.o)
      __swift_FORCE_LOAD_$_swiftWebKit_$_lottie_react_native in liblottie-react-native.a(AnimationViewManagerModule.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftWebKit_$_lottie_react_native)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

It seems to be a problem with `liblottie-react-native`, I then removed the package and I finally got `Command PhaseScriptExecution failed with a nonzero exit code` error.

## React Native version:

```
Binaries:
    Node: 15.11.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 7.6.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: ^0.64.0 => 0.64.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. run build in Xcode
2. The error barred the app from building.

## Expected Results
 the app builds normally

## Snack, code example, screenshot, or link to a repository:
I also got `[!] FBReactNativeSpec has added 1 script phase. Please inspect before executing a build. See `https://guides.cocoapods.org/syntax/podspec.html#script_phases` for more information.` from `pod install`

**Comment by giona69** [comment]
I solved commenting flipper pods intallation in Podfile

**Comment by ralph-dev** [comment]
@giona69 Is your flipper updated to the Latest Version, Trying to force it to the latest version that could be why.
  use_flipper!({ 'Flipper' => '0.74.0' })

**Comment by cortinico** [comment]
Hey,
We're cleaning up the React Native issue tracker to make sure we focus on the most important issues first.

I'm closing this one because it's stale and related to a version of React Native we no longer support. If the issue persists on the latest version, please re-open a new issue and reference this one.

Thank you.
