### ISSUE TITLE
用MacBookAir 构建项目时，运行ios错误 IOS error running while building project with MacBookAir

### ISSUE THREAD

**Issue by MaxCode-fan** [facebook/react-native#31208]
因为学习需要，我购买了一个信息mac笔记本，当我根据文档进行初始化项目时，运行失败了
我是一个新手，我不能够理解这是怎么了，希望能给出一个详细的解决方案，非常感谢
Because of the study needs, I bought an information Mac notebook, and when I initialized the project according to the document, it failed to run
I am a novice, I can not understand what is going on here, I hope you can give me a detailed solution, thank you very much

以下是我的运行环境信息
The following is the information about my running environment
![image](https://user-images.githubusercontent.com/57091336/111945119-05551180-8b14-11eb-855f-e08080991c92.png)
![image](https://user-images.githubusercontent.com/57091336/111945137-14d45a80-8b14-11eb-8996-ed3d4858ca93.png)

这个是我初始化的项目
This is the project that I initialized
![image](https://user-images.githubusercontent.com/57091336/111945062-efdfe780-8b13-11eb-843a-2786af6a6531.png)

当我运行的时候出现了这个问题
This problem occurs when I run it
![image](https://user-images.githubusercontent.com/57091336/111945439-b3f95200-8b14-11eb-9565-06f6ef73a2ab.png)

我开始尝试修复它，然后再次尝试运行，依然无法解决
I started trying to fix it, then tried to run it again, still couldn't fix it
![image](https://user-images.githubusercontent.com/57091336/111945598-f589fd00-8b14-11eb-90f0-d84b9176461f.png)

我是一个新手，我不知道应该怎么做才能修复，我需要一个详细的操作步骤，非常感谢
I am a novice, I do not know what to do to repair, I need a detailed operation steps, thank you very much

**Comment by MaxCode-fan** [comment]
补充一个react native 的信息
Added a React Native message
![image](https://user-images.githubusercontent.com/57091336/111946287-2c144780-8b16-11eb-8ace-12b9e6ad06ed.png)

**Comment by Arkkeeper** [comment]
I faced the same issue. In Xcode, open the project (not the target, the whole project), go to the Build Settings tab and search for the "Library Search Paths". If there is a "swift-5.0", change it to the "swift-5.2".

<img width="980" alt="swift52" src="https://user-images.githubusercontent.com/20115419/111953833-358eb700-8af8-11eb-9de3-db35e8ea7f08.png">

**Comment by MaxCode-fan** [comment]
> 我遇到了同样的问题。在Xcode中，打开项目（不是目标，是整个项目），转到“构建设置”选项卡并搜索“库搜索路径”。如果有“ swift-5.0”，请将其更改为“ swift-5.2”。
> 
> <img alt="迅捷52" width="980" src="https://user-images.githubusercontent.com/20115419/111953833-358eb700-8af8-11eb-9de3-db35e8ea7f08.png">

Thank you very much, but I've already returned my Mac, which makes me feel like I'm wearing a mask of pain in LOL, which makes me feel like it doesn't deserve me. I'm going to use Windows to develop my Android first, let iOS see God, I'll think about it later

**Comment by punszeto** [comment]
你这台机器是M1芯片的?

**Comment by cortinico** [comment]
Hi,
In this issue tracker we accept only issues that are in English.
I'm closing this for now, please consider translating it to English and reopening it.
Thanks.
