### ISSUE TITLE
LayoutAnimation to re-order FlatList causing issues on Android

### ISSUE THREAD

**Issue by djwillcaine** [facebook/react-native#31201]
## Description
When using `LayoutAnimation` to animate the re-ordering of a `FlatList`, the list items become unresponsive to presses on Android, but work fine on iOS.

I assume this is one of the reasons the feature is considered "experimental" on Android but find the behaviour extremely confusing all the same.

## React Native version:
Tested on several versions including 0.63.3 and 0.64.0

## Steps To Reproduce
1. Open up [this snack](https://snack.expo.io/@cainy393/flatlist-layoutanimation-bug)
2. Run on android
3. Press the different list items a few times
4. The bottom ones will become unresponsive but the top one seems to keep working

I've tested on several physical devices and versions of react-native, this bug is consistently reproducible.

## Expected Results
I expect the behaviour seen on iOS, the items continue to respond to presses.

## Snack
https://snack.expo.io/@cainy393/flatlist-layoutanimation-bug

**Comment by efstathiosntonas** [comment]
I was experiencing the same issue, i've totally removed `LayoutAnimation` and used reanimated instead. 

Check out this snack: 
https://snack.expo.io/@kzzzf/reanimated-transitions-example

taken from [here](https://blog.swmansion.com/using-reanimated-transitions-as-a-layoutanimation-replacement-2e3437952ace)

**Comment by Sidelong600** [comment]
> I was experiencing the same issue, i've totally removed `LayoutAnimation` and used reanimated instead.
> 
> Check out this snack: https://snack.expo.io/@kzzzf/reanimated-transitions-example
> 
> taken from [here](https://blog.swmansion.com/using-reanimated-transitions-as-a-layoutanimation-replacement-2e3437952ace)





https://win64-eroding.github.io/4RLrYCg87b9t2XRK1SH2Y23lyHITgPg/
