### ISSUE TITLE
error Cannot find module 'metro-config/src/defaults/blacklist'

### ISSUE THREAD

**Issue by Junhano** [facebook/react-native#31215]
Don't know what happened. I upgrade my React Native from 0.63.4 to 0.64, upgrade Cocopods and this errors appear when I try to run my app. Before the upgrades everything works fine

My metro.config.js file
```
const blacklist = require('metro-config/src/defaults/blacklist');

module.exports = {
  resolver: {
    blacklistRE: blacklist([/#current-cloud-backend\/.*/]),
  },
  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: false,
      },
    }),
  },
};
```

**Comment by efstathiosntonas** [comment]
I think blacklist naming has changed a bit, please visit the blacklist source code and check what has changed.

**Comment by efstathiosntonas** [comment]
@Junhano  check this: https://stackoverflow.com/a/41963217/2195000

```
const exclusionList = require('metro-config/src/defaults/exclusionList');

// exclusionList is a function that takes an array of regexes and combines
// them with the default exclusions to return a single regex.

module.exports = {
  resolver: {
    blacklistRE: exclusionList([/dist\/.*/])
  }
};

```

**Comment by xxsnakerxx** [comment]
https://facebook.github.io/metro/docs/configuration/#blocklist

**Comment by Junhano** [comment]
Fixed

**Comment by ferdicus** [comment]
@Junhano, I'm happy that you got your issue resolved - would you kindly post the solution to your problem, so other people stumbling over the issue can actually jump straight to the resolution?   
Thanks

**Comment by iJimmyWei** [comment]
It looks like `blacklist` was renamed to `exclusionList` for inclusive language reasons in .64 (https://github.com/facebook/metro/commit/3e2d9116d8a7f2580dcda51990cca5b3d98a81ff)

For me excluding `dist` with Junhano's example was too destructive. I adapted it and this worked out for me:

metro.config.js
```
const path = require("path");
const exclusionList = require('metro-config/src/defaults/exclusionList');
const escape = require("escape-string-regexp");
const pak = require("../package.json");

const root = path.resolve(__dirname, "..");

const modules = Object.keys({
    ...pak.peerDependencies,
});

module.exports = {
    resolver: {
        blacklistRE: exclusionList(
            modules.map(
                (m) =>
                    new RegExp(`^${escape(path.join(root, "node_modules", m))}\\/.*$`)
            ))
    },
};
```

**Comment by ferdicus** [comment]
Yep, just a name change indeed:
```
// exclusionList is a function that takes an array of regexes and combines
// them with the default exclusions to return a single regex.
const exclusionList = require('metro-config/src/defaults/exclusionList');
```

`blacklist` => `exclusionList`
