### ISSUE TITLE
ERROR   Network request failed  Android

### ISSUE THREAD

**Issue by phanidharmot** [facebook/react-native#31213]
## Description

Unable to make any fetch requests. Getting `Network request failed` Error on Android. Works fine on iOS. Tried various solutions from other threads and issues. Nothing helped. Any help appreciated!

## React Native version:
Run `react-native info` in your terminal and copy the results here.
0.63.1

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Make a remote https fetch request on emulator Android 10.0 Google API 29 

## Expected Results
Describe what you expected to happen.
Successful request with data.

**Comment by quachdev** [comment]
Getting this error now on Android on v0.64.2.

**Comment by flyskywhy** [comment]
[fixed `TypeError: Network request failed` when upload file to http not https with Android debug builds](https://github.com/facebook/react-native/issues/33217#issuecomment-1159844475)
