### ISSUE TITLE
Device agnostic components coming?

### ISSUE THREAD

**Issue by pickhardt** [facebook/react-native#3122]
I have an iOS app that uses DatePickerIOS and TabBarIOS, and am trying to get it working with Android currently. I'm curious - are device agnostic components coming soon e.g. DatePicker or TabBar (that uses either the iOS or Android version)?  Also if they are, maybe you can put a notice on the documentation pages (https://facebook.github.io/react-native/docs/datepickerios.html#content) that they're planned for an upcoming version?

**Comment by ide** [comment]
I wrote a tab navigator implementation that works on Android (actively using it): https://github.com/exponentjs/react-native-tab-navigator

**Comment by astreet** [comment]
We are currently erring on the side of not doing this much as we don't want to encourage lowest common denominator 'write once, run anywhere' apps. To build the best apps for both platforms, design should actively be considered separately for each platform. As examples with the components you mentioned, tab bars on iOS and android are similar, but the standard design guidelines for android discourage use of tab bars for top level navigation, instead encouraging the use of action bars and drawers. For DatePicker, on on iOS it's full on inline component, whereas on Android it's a modal dialog that needs to be triggered. Something like Switch, on the other hand, is probably safer to wrap.

I don't doubt that someone will come out with a library that wraps some of these common components -- use it with care when it does come.
