### ISSUE TITLE
Differences between Navigator and NavigatorIOS?

### ISSUE THREAD

**Issue by pickhardt** [facebook/react-native#3123]
Might be good to write out in the documentation some bullet points for why someone would prefer NavigatorIOS over Navigator.

Is there a plan to deprecate NavigatorIOS in favor of Navigator? I'm not sure if this is possible but it seems like the extra functionality could be options for Navigator. Then it'd be easier to know which one to use, since there'd only be one choice.

**Comment by christopherdro** [comment]
You can take a look here:
https://facebook.github.io/react-native/docs/navigator-comparison.html#content

**Comment by pickhardt** [comment]
Nice... I didn't realize that page existed. You should link to it from the component doc pages.  Sounds like NavigatorIOS should be removed from the list of officially documented components, from the looks of it.

**Comment by christopherdro** [comment]
Hopefully the link helped answer some of your questions. Could you please close the issue? Thanks
