### ISSUE TITLE
React native track player

### ISSUE THREAD

**Issue by nagaraj95** [facebook/react-native#31233]
Describe the bug
I am using the react-native-trackplayer as an audio model in my app. I am having the feature of repeating the songs with the help of Trackplayer event listener , at some point of view I can't able to get the callback from the event listener. So, I can't able to perform some actions in my app. The problem appears in Android OS.

To Reproduce
Not able to reproduce the way while in production mode the bug arises.

Please post some solution for this. Thanks in advance

**Comment by ralph-dev** [comment]
@nagaraj95 This is the React Native Repository, can you please post your issue in the react-native-trackplayer's Library's Repository so the right person can assist you.

**Comment by cortinico** [comment]
As mentioned, please open this issue here: https://github.com/doublesymmetry/react-native-track-player/issues
