### ISSUE TITLE
Please update react 17.0.1 to 17.0.2

### ISSUE THREAD

**Issue by Romick2005** [facebook/react-native#31231]
Can you please change 
```
  "devDependencies": {
    "flow-bin": "^0.147.0",
    "react": "17.0.1"
  },
```
to
```
  "devDependencies": {
    "flow-bin": "^0.147.0",
    "react": "^17.0.1"
  },
```

![image](https://user-images.githubusercontent.com/17779660/112340945-b18c2900-8cc9-11eb-91fc-1cd551d41586.png)

**Comment by HarshalRohit** [comment]
Any updates on this?? I am facing issues with react-native-unimodules because of this!!

**Comment by cortinico** [comment]
Closing as React is now at 18.2.0
