### ISSUE TITLE
Upgraded to 0.63.4 and LogBox does not even function

### ISSUE THREAD

**Issue by HugoChengMyC** [facebook/react-native#31241]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Please provide a clear and concise description of what the bug is. Include screenshots if needed.
Please test using the latest React Native release to make sure your issue has not already been fixed: https://reactnative.dev/docs/upgrading.html

## React Native version:
Run `react-native info` in your terminal and copy the results here.
System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 89.91 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.0.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.12.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /Users/hugocheng/.rvm/rubies/ruby-2.6.3/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    Android SDK:
      API Levels: 22, 23, 26, 27, 28, 29, 30
      Build Tools: 27.0.3, 28.0.3, 29.0.2
      System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.2/12B45b - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_202-ea - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.3.1 => 16.3.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.npx react-native run-ios
2.app boots up
3. app crashes with error

## Expected Results
Describe what you expected to happen.
To at least be able to start up with the app, if there is a error, display error properly
<img width="344" alt="Screen Shot 2021-03-25 at 8 59 50 PM" src="https://user-images.githubusercontent.com/36966848/112575309-55023a00-8dad-11eb-8e26-42a3d7b504ec.png">

package.json
```
{
  "name": "redacted",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "@babel/core": "~7.8.4",
    "@babel/runtime": "^7.8.4",
    "@react-native-community/eslint-config": "^1.1.0",
    "babel-jest": "^25.1.0",
    "eslint": "7.14.0",
    "enzyme": "^3.11.0",
    "enzyme-adapter-react-16": "^1.15.5",
    "enzyme-to-json": "^3.3.4",
    "jest": "^25.1.0",
    "jest-enzyme": "^6.0.1",
    "jest-expo": "^37.0.0",
    "jest-react-hooks-shallow": "^1.4.1",
    "jest-serializer-enzyme": "^1.0.0",
    "jetifier": "^1.6.5",
    "metro-react-native-babel-preset": "^0.59.0",
    "react-dom": "16.9.0",
    "react-native": "0.63.4",
    "react-native-mock": "^0.3.1",
    "react-native-scripts": "1.14.0",
    "react-native-unimodules": "~0.9.1",
    "react-test-renderer": "^16.3.1",
    "sinon": "^5.0.10"
  },
  "scripts": {
    "postinstall": "jetify",
    "startTest": "npm test; expo start",
    "start": "react-native start",
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "test": "jest"
  },
  "jest": {
    "preset": "jest-expo",
    "transformIgnorePatterns": [
      "node_modules/(?!(jest-)?react-native|react-clone-referenced-element|@react-native-community|expo(nent)?|@expo(nent)?/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base|@sentry/.*|react-native-modal-dropdown|deprecated-react-native-listview)"
    ],
    "snapshotSerializers": [
      "enzyme-to-json/serializer"
    ],
    "setupFilesAfterEnv": [
      "./__mocks__/react-hook-jest"
    ],
    "automock": false
  },
  "dependencies": {
    "@babel/core": "7.12.9",
    "@babel/runtime": "^7.12.5",
    "@expo/vector-icons": "^10.0.0",
    "@react-native-async-storage/async-storage": "^1.14.1",
    "@react-native-community/checkbox": "^0.5.5",
    "@react-native-community/datetimepicker": "^3.0.2",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/drawer": "^5.7.5",
    "@react-navigation/native": "^5.4.0",
    "@react-navigation/stack": "^5.3.7",
    "amplitude-js": "^7.4.2",
    "babel-core": "^7.0.0-bridge.0",
    "babel-jest": "^23.6.0",
    "d3": "^4.13.0",
    "deprecated-react-native-listview": "^0.0.5",
    "expo": "^37.0.8",
    "expo-asset": "^8.1.5",
    "expo-constants": "^9.2.0",
    "expo-font": "~8.1.0",
    "expo-notifications": "^0.7.2",
    "expo-permissions": "~8.1.0",
    "expo-secure-store": "~8.1.0",
    "expo-splash-screen": "^0.2.3",
    "expo-updates": "0.2.1",
    "jsdom": "^11.11.0",
    "metro-react-native-babel-preset": "^0.58.0",
    "moment": "^2.27.0",
    "moment-timezone": "^0.5.32",
    "prop-types": "^15.6.1",
    "react": "16.3.1",
    "react-dom": "~16.9.0",
    "react-native-calendar-picker": "^7.0.2",
    "react-native-chip-view": "0.0.11",
    "react-native-codegen": "0.0.7",
    "react-native-dash": "0.0.9",
    "react-native-device-info": "^8.0.1",
    "react-native-elements": "^1.1.0",
    "react-native-extended-stylesheet": "^0.10.0",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-material-tabs": "^3.8.1",
    "react-native-modal": "^11.5.6",
    "react-native-modal-datetime-picker": "9.0.0",
    "react-native-modal-dropdown": "git+https://github.com/siemiatj/react-native-modal-dropdown.git",
    "react-native-picker-dropdown": "^0.1.2",
    "react-native-pinch-zoom-view": "^0.2.0",
    "react-native-progress": "^4.1.2",
    "react-native-progress-circle": "^2.0.0",
    "react-native-reanimated": "^1.7.1",
    "react-native-render-html": "^3.10.0",
    "react-native-safe-area-context": "^1.0.2",
    "react-native-screens": "^2.2.0",
    "react-native-simple-radio-button": "^2.7.1",
    "react-native-svg": "^11.0.1",
    "react-native-svg-transformer": "^0.14.3",
    "react-native-swipe-gestures": "^1.0.2",
    "react-native-switch": "^1.5.0",
    "react-native-tag-autocomplete": "^1.0.21",
    "react-native-timeline-listview": "^0.2.3",
    "react-native-timeline-theme": "0.0.9",
    "react-native-unimodules": "^0.9.1",
    "react-native-vector-icons": "^6.3.0",
    "react-native-web": "~0.11.7",
    "react-navigation": "^2.18.3",
    "whatwg-fetch": "^2.0.4"
  },
  "resolutions": {
    "deprecated-react-native-listview": "0.0.6"
  },
  "rnpm": {
    "assets": [
      "./app/assets/fonts"
    ]
  }
}

```

**Comment by raajnadar** [comment]
Did you try clearing the cache `npx react-native start` & `npx react-native run-ios`?

**Comment by cortinico** [comment]
Hey,
We're cleaning up the React Native issue tracker to make sure we focus on the most important issues first.

I'm closing this one because it's stale and related to a version of React Native we no longer support. If the issue persists on the latest version, please re-open a new issue and reference this one.

Thank you.
