### ISSUE TITLE
Alert shows navigation bar in immersive mode

### ISSUE THREAD

**Issue by jp928** [facebook/react-native#31242]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
The navigation bar show up when Alert prompts even using API **setSystemUiVisibility** set the full screen mode.

## React Native version:
0.64.

## Steps To Reproduce
1. Call the following code in MainActivity.java: onCreate to enter immersive mode on Android 9.
```
 UiThreadUtil.runOnUiThread(new Runnable() {
                @Override
                public void run() {
                    getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY
            | View.SYSTEM_UI_FLAG_LAYOUT_STABLE
            | View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION
            | View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN
            | View.SYSTEM_UI_FLAG_HIDE_NAVIGATION
            | View.SYSTEM_UI_FLAG_FULLSCREEN;
                }
            });
```

2. Inside the App call
```
Alert.alert('test')
```

3. The navigation bar will appear like the screenshot.
![Screen Shot 2021-03-26 at 3 33 37 pm](https://user-images.githubusercontent.com/659612/112577567-aad7f000-8e48-11eb-882c-a9cdbdd98456.png)

## Expected Results
The dialog should detect the parent view system ui visibility and apply accordingly.

**Comment by Morritz** [comment]
Any workaround available?
