### ISSUE TITLE
java.lang.RuntimeException: Duplicate class com.facebook.jni.CppException found in modules classes.jar and fbjni-java-only-0.0.3.jar

### ISSUE THREAD

**Issue by junlengnyp** [facebook/react-native#31240]
Hi there, I am having an error when trying to implement react-native with flipper (PyTorch and PyTorch TorchVision are used as dependencies as shown)

dependencies {
implementation fileTree(dir: "libs", include: ["*.jar"])
implementation "com.facebook.react:react-native:+" // From node_modules
implementation "org.pytorch:pytorch_android:1.5.0"
implementation "org.pytorch:pytorch_android_torchvision:1.5.0" }

The error being shown is:
Duplicate class com.facebook.jni.CppException found in modules classes.jar (com.facebook.react:react-native:0.61.5) and fbjni-java-only-0.0.3.jar (com.facebook.fbjni:fbjni-java-only:0.0.3)
Duplicate class com.facebook.jni.CppSystemErrorException found in modules classes.jar (com.facebook.react:react-native:0.61.5) and fbjni-java-only-0.0.3.jar (com.facebook.fbjni:fbjni-java-only:0.0.3)
Duplicate class com.facebook.jni.DestructorThread found in modules classes.jar (com.facebook.react:react-native:0.61.5) and fbjni-java-only-0.0.3.jar (com.facebook.fbjni:fbjni-java-only:0.0.3)
Duplicate class com.facebook.jni.DestructorThread$1 found in modules classes.jar (com.facebook.react:react-native:0.61.5) and fbjni-java-only-0.0.3.jar (com.facebook.fbjni:fbjni-java-only:0.0.3)
Duplicate class com.facebook.jni.DestructorThread$Destructor found in modules classes.jar (com.facebook.react:react-native:0.61.5) and fbjni-java-only-0.0.3.jar (com.facebook.fbjni:fbjni-java-only:0.0.3)
Duplicate class com.facebook.jni.DestructorThread$DestructorList found in modules classes.jar (com.facebook.react:react-native:0.61.5) and fbjni-java-only-0.0.3.jar (com.facebook.fbjni:fbjni-java-only:0.0.3)
Duplicate class com.facebook.jni.DestructorThread$DestructorStack found in modules classes.jar (com.facebook.react:react-native:0.61.5) and fbjni-java-only-0.0.3.jar (com.facebook.fbjni:fbjni-java-only:0.0.3)
Duplicate class com.facebook.jni.DestructorThread$Terminus found in modules classes.jar
(com.facebook.react:react-native:0.61.5) and fbjni-java-only-0.0.3.jar (com.facebook.fbjni:fbjni-java-only:0.0.3)
Duplicate class com.facebook.jni.HybridClassBase found in modules classes.jar (com.facebook.react:react-native:0.61.5) and fbjni-java-only-0.0.3.jar (com.facebook.fbjni:fbjni-java-only:0.0.3)
Duplicate class com.facebook.jni.HybridData found in modules classes.jar (com.facebook.react:react-native:0.61.5) and fbjni-java-only-0.0.3.jar (com.facebook.fbjni:fbjni-java-only:0.0.3)
Duplicate class com.facebook.jni.HybridData$Destructor found in modules classes.jar (com.facebook.react:react-native:0.61.5) and fbjni-java-only-0.0.3.jar (com.facebook.fbjni:fbjni-java-only:0.0.3)
Duplicate class com.facebook.jni.IteratorHelper found in modules classes.jar (com.facebook.react:react-native:0.61.5) and fbjni-java-only-0.0.3.jar (com.facebook.fbjni:fbjni-java-only:0.0.3)
Duplicate class com.facebook.jni.MapIteratorHelper found in modules classes.jar (com.facebook.react:react-native:0.61.5) and fbjni-java-only-0.0.3.jar (com.facebook.fbjni:fbjni-java-only:0.0.3)
Duplicate class com.facebook.jni.NativeRunnable found in modules classes.jar (com.facebook.react:react-native:0.61.5) and fbjni-java-only-0.0.3.jar (com.facebook.fbjni:fbjni-java-only:0.0.3)
Duplicate class com.facebook.jni.ThreadScopeSupport found in modules classes.jar (com.facebook.react:react-native:0.61.5) and fbjni-java-only-0.0.3.jar (com.facebook.fbjni:fbjni-java-only:0.0.3)
Duplicate class com.facebook.jni.UnknownCppException found in modules classes.jar (com.facebook.react:react-native:0.61.5) and fbjni-java-only-0.0.3.jar (com.facebook.fbjni:fbjni-java-only:0.0.3)

Is there any solution for this?

**Comment by d4vidi** [comment]
Try to use a version for your AGP (Android Gradle Plugin) that's older than `3.5.0`, for example: `3.4.2`.

**Comment by cortinico** [comment]
This is now fixed in React Native 0.72
