### ISSUE TITLE
Xcode error: building for iOS Simulator, but linking in object file built for iOS on new MacBook M1

### ISSUE THREAD

**Issue by jocoders** [facebook/react-native#31248]
## Description
Build failed on Macbook Air M1, Xcode 12.4, React Native app from scratch, was made a few days ago and was launching with out any troubles until today. Get the error after Xcode build:

> /Users/userName/Projects/MyApp/ios/Pods/OpenSSL-Universal/ios/lib/libcrypto.a(cryptlib.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/userName/Projects/MyApp/ios/Pods/OpenSSL-Universal/ios/lib/libcrypto.a' for architecture arm64clang: error: linker command failed with exit code 1 (use -v to see invocation)

## React Native version:
react-native 0.63.4

## Steps To Reproduce
Xcode => Build => get error Build error
This error indicates that OpenSSL is built containing the simulator slice (x86_64) with the iOS device slice (arm64). Combining device and simulator into a single binary file is not a supported build configuration, and never has been. With the introduction of M1 Macs, where the simulator is also arm64 now, Xcode is looking for a arm64 slice intended for the simulator, but finding one only valid for use on a device, and letting you know of this issue.

The solution is to rebuild OpenSSL. If you intend to use it as a a pre-built binary, rather than compiling from source during your app's build, it needs to be inside of an XCFramework. XCFrameworks are purposefully designed to separate device and simulator builds into separate files and avoid this class of error.

## Expected Results
The build on Xcode is successful. 

Guys can you tell me please why OpenSSL is built containing the simulator slice (x86_64) in React Native? And how to rebuild OpenSSL? And how do you solve it in your project?

**Comment by Arkkeeper** [comment]
What is your OpenSSL version in ios/Podfile.lock?

**Comment by jocoders** [comment]
> What is your OpenSSL version in ios/Podfile.lock?

OpenSSL-Universal/Static (1.0.2.20)

**Comment by Arkkeeper** [comment]
I'd suggest you upgrade RN to 0.64 and Flipper to 0.80 or newer, you'll get newer OpenSSL with xcframework support and this issue will be gone.
