### ISSUE TITLE
shared_timed_mutex' is unavailable: introduced in iOS 10.0

### ISSUE THREAD

**Issue by msageryd** [facebook/react-native#31250]
## Description
I upgraded my RN project from 0.63.2 to 0.64 with `react-native upgrade` 

After the upgrade I'm not able to build the project anymore. I get 6 errors in RCTTurboModuleManager. All 6 says the same thing.

![image](https://user-images.githubusercontent.com/4483085/112652900-31430080-8e4e-11eb-8f22-4d0beb9973e8.png)

## Tried stuff..

I have tried the following:
- `rm -rf node_modules && npm install`
- `rm -rf ios/Pods`
- `rm Podfiles.lock`
- `pod install`
- `watchman watch-del-all && rm -rf $TMPDIR/react-* && rm -rf $TMPDIR/metro-* && rm -rf $TMPDIR/haste-*`
- Clean Bulld Folder from XCode

My build target is 10.0, but I also tried to bump it to 11.0. This disn't work either.

## React Native version:
System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 1.24 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.21.0 - ~/.nvm/versions/node/v12.21.0/bin/node
    Yarn: Not Found
    npm: 6.14.11 - ~/.nvm/versions/node/v12.21.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: javac 15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.0 => 0.64.0
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by msageryd** [comment]
Sorry for bothering with my issue. It turned out that I was responsible for this, not RN. Closing this.

I had an old manual fix in my Podfiles to fix some pods not wanting to be "No bitcode". In the same code I had hard coded the target.

``` 
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['ENABLE_BITCODE'] = 'NO'
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
```

**Comment by nevin22** [comment]
> Sorry for bothering with my issue. It turned out that I was responsible for this, not RN. Closing this.
> 
> I had an old manual fix in my Podfiles to fix some pods not wanting to be "No bitcode". In the same code I had hard coded the target.
> 
> ```
>     installer.pods_project.targets.each do |target|
>       target.build_configurations.each do |config|
>         config.build_settings['ENABLE_BITCODE'] = 'NO'
>           config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
>       end
>     end
> ```
hey man.. i'm actually having the same issue while upgrading from rn 0.61 to 0.65 and i don't even have that enable_bitcode

**Comment by blobrfish** [comment]
I'm seeing the same error. Have someone solved this since it was posted?

**Comment by msageryd** [comment]
@denisprado @blobrfish @nevin22 
I'm guessing that your project has target < 10 somewhere. I think there are two different places to specify target in the project. And if you, like me, are manually setting the target in your Podfile this might be the place to update.

**Comment by MGalym** [comment]
same here, updating from 0.61 to 0.65

**Comment by thisisgit** [comment]
I also had this issue while upgrading from `0.63.4` to `0.66.4`
Resolved it by setting `config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'`
```
post_install do |installer|
  react_native_post_install(installer)
  __apply_Xcode_12_5_M1_post_install_workaround(installer)

  # This is to resolve "'shared_timed_mutex' is unavailable: introduced in iOS 10.0" error
  installer.pods_project.targets.each do |t|
    t.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
    end
  end
end
```
