### ISSUE TITLE
Autolink dependency of dependency

### ISSUE THREAD

**Issue by sandeeppatel88** [facebook/react-native#31266]
## React Native version:
Run `react-native info` in your terminal and copy the results here.
System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
    Memory: 827.51 MB / 7.88 GB
  Binaries:
    Node: 14.5.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - C:\Program Files\nodejs\yarn.CMD
    npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7042882
    Visual Studio: Not Found
  Languages:
    Java: javac 15
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.0 => 0.64.0
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.I have created library with create-react-native-library
2.I have react-native-webview dependency and its got installed in node_modules but autolink is not happening  for react-native-webview

What is the solution for autolink of dependency of dependency

**Comment by cortinico** [comment]
This is not currently supported, and is related to the CLI (hence I'm closing it)

There is an ongoing effort to support it here:
- https://github.com/react-native-community/cli/pull/2054
