### ISSUE TITLE
Dangerous Permissions are granted by default in android in RN 0.64.0

### ISSUE THREAD

**Issue by gresi29** [facebook/react-native#31278]
## Description
Dangerous(runtime) permissions like READ_CALENDAR, WRITE_CALENDAR, CAMERA, READ_CONTACTS, WRITE_CONTACTS, RECORD_AUDIO, READ_PHONE_NUMBERS, CALL_PHONE, ANSWER_PHONE_CALLS, SEND_SMS, RECEIVE_SMS, READ_SMS etc. always granted when i install app in device. this permissions are not granted by default in React-Native(0.63.4) but when i create project with latest version(0.64.0),  permissions are always granted without asking users.

## React Native version:
System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i5-4440S CPU @ 2.80GHz
    Memory: 851.22 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.15.3 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.9 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 17, 19, 23, 24, 25, 26, 27, 28, 29, 30
      Build Tools: 23.0.1, 26.0.2, 27.0.3, 28.0.0, 28.0.3, 29.0.0, 29.0.1, 29.0.2, 29.0.3
      System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 12.3/12C33 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_221 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.0 => 0.64.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
1. create react native project with latest version (0.64.0)
2. add runtime permissions in AndroidManifest.xml file
3. run application using npx react-native run-android command

## Expected Results
runtime permissions should not be granted by default

## Snack, code example, screenshot, or link to a repository:
![Screenshot_2021-03-31-11-53-49-569_com google android permissioncontroller](https://user-images.githubusercontent.com/54353829/113099657-efcc9f80-9217-11eb-9f0a-ef710e071ac3.jpg)

**Comment by HectorRicardo** [comment]
Hey @gresi29 , I just created a new project from scratch on Android Studio. I ran the "installDebug" task for the app, so it got installed on my phone but it didn't run automatically. I checked the Permissions page on the Settings in my phone, and very surprisingly I found that permissions were already given !! 

I am using Android 10. I think this is not a RN bug, but rather an Android bug.

**Comment by eliaslecomte** [comment]
Call logs, microphone and Telephone should definitely not be included in a vanilla hello world app.
They only appear there if they are added to the AndroidManifest. They may be added via dependencies.
Where are these coming from???

**Comment by anonymous33999** [comment]
Hey, @gresi29 I also created a new rn project, and all my dangerous permissions are also granted by default. I degraded to rn 0.63 also but then also permissions are granted automatically.

**Comment by sandan10** [comment]
This looks like a problem with the gradle-plugin, check  [this link](https://issuetracker.google.com/issues/172112073).
I tested `4.0.0` with `6.1.1` and `4.2.0-rc01` with `6.7.1`, and those work as expected.

**Comment by anonymous33999** [comment]
@sandan10 Thanks a lot. It was gradle-plugin problem. Resolved it and now I am getting permission dialog box for android dangerous permission.

**Comment by jzxchiang1** [comment]
What an insane bug. I downgraded my gradle version to 4.0.2 from 4.1.2 and now this issue is gone.

Just change `classpath("com.android.tools.build:gradle:4.0.2")` in `android/build.gradle`. Amazing.

**Comment by safaiyeh** [comment]
What a crazy bug... the default template now uses `com.android.tools.build:gradle:4.2.1` is this still an issue for that version?

**Comment by felansu** [comment]
+1

**Comment by cortinico** [comment]
As we're on AGP 7.0.x now, can someone give it a try on RN-Tester and report if this is still an issue?

**Comment by Yandamuri** [comment]
Changing from `classpath com.android.tools.build:gradle:4.1.0` to `classpath com.android.tools.build:gradle:4.2.1` worked for me.

BTW, I am using `distributionUrl=https\://services.gradle.org/distributions/gradle-6.9-all.zip`

**Comment by cortinico** [comment]
Closing as this issue is not relevant anymore for RN 0.71+
