### ISSUE TITLE
Error: Text strings must be rendered within a <Text> component.

### ISSUE THREAD

**Issue by darda-ergo** [facebook/react-native#31273]
![image](https://user-images.githubusercontent.com/61325474/112969121-c60b6e00-916e-11eb-8846-0d6b91a894e0.png)

**Comment by darda-ergo** [comment]
Solved. need to use ternary operator

**Comment by ezranbayantemur** [comment]
Hello, looks like you found the solution!
Can you close the issue if you done with it?

**Comment by anhkieet** [comment]
use !!imageUri &&

**Comment by chrisbobbe** [comment]
Looks like the string it's complaining about is the empty string at `imageUri`.

**Comment by karlhorky** [comment]
Seems like they do not cause issues anymore with React Native 0.70.1:

I just started a new React Native app just now (`npx react-native init` with `react-native@0.70.1`) to verify this and confirmed empty strings outside of `<Text>` components do not cause this error:

<img width="986" alt="Screen Shot 2022-10-04 at 13 10 49" src="https://user-images.githubusercontent.com/1935696/193805232-0147a7b0-9618-42be-b8d6-2baabc2b2e50.png">

Whereas a string with content in it does:

<img width="971" alt="Screen Shot 2022-10-04 at 13 14 34" src="https://user-images.githubusercontent.com/1935696/193805265-55c9c43d-59fb-4a63-99c2-5eaeab25c98c.png">

- Repo: https://github.com/karlhorky/react-native-empty-string-outside-text-component
- Tweet: https://twitter.com/karlhorky/status/1577257935796740096

**Comment by karlhorky** [comment]
Empty strings indeed no longer cause errors (if you use React 18+):

- https://github.com/facebook/react-native/issues/35002

**Comment by fabriziobertoglio1987** [comment]
Do you still experience this issue? 

I have four years of experience maintaining facebook/react-native and I specialize in the Text and TextInput components. I currently have 58 [facebook/react-native PRs](https://github.com/facebook/react-native/pulls?q=is%3Apr+author%3Afabriziobertoglio1987+). 

If you still experience this issue, I will prepare a patched release with the fix.

Thanks a lot
