### ISSUE TITLE
Fatal Exception: java.lang.NoSuchMethodError: no non-static method "Lcom/facebook/react/turbomodule/core/CallInvokerHolderImpl

### ISSUE THREAD

**Issue by anandchakru** [facebook/react-native#31277]
## Description
App works fine in development, but crashes in Android (production), see below for crashlytics stacktrace:  

## React Native version:
```sh
System:
    OS: macOS 11.2.3
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 400.78 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.11.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.6.0 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.10.1 - /Users/anand/.gem/ruby/2.6.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 29, 30
      Build Tools: 29.0.2, 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: 23.0.7196353-beta2
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.10 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.0 => 0.64.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Build app for production
2. Release in Google play store
3. Open the app after installing from play store

## Expected Results
App should work without crashing

## Snack, code example, screenshot, or link to a repository:

```java
Fatal Exception: java.lang.NoSuchMethodError: no non-static method "Lcom/facebook/react/turbomodule/core/CallInvokerHolderImpl;.<init>(Lcom/facebook/jni/HybridData;)V"
       at com.facebook.react.bridge.CatalystInstanceImpl.getJSCallInvokerHolder(CatalystInstanceImpl.java)
       at com.facebook.react.bridge.CatalystInstanceImpl.getJSCallInvokerHolder(CatalystInstanceImpl.java)
       at com.swmansion.reanimated.NativeProxy.<init>(NativeProxy.java:7)
       at com.swmansion.reanimated.NodesManager.initWithContext(NodesManager.java:2)
       at com.swmansion.reanimated.ReanimatedJSIModulePackage.getJSIModules(ReanimatedJSIModulePackage.java:12)
       at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:104)
       at com.facebook.react.ReactInstanceManager.access$1100(ReactInstanceManager.java)
       at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:68)
       at java.lang.Thread.run(Thread.java:923)
```

**Comment by anandchakru** [comment]
Trial-n-error'd it. Turns out, [react-native-reanimated](https://docs.swmansion.com/react-native-reanimated/docs/installation/#android) was the issue

Reverting `MainApplication.java` fixed the issue.

**Comment by PrimulaX** [comment]
Same problem, debug works well, release variant crashes immediately.
Logcat:
`2021-04-04 00:38:55.903 7424-7450/? E/AndroidRuntime: FATAL EXCEPTION: create_react_context
    Process: com.dmncnt, PID: 7424
    java.lang.NoSuchMethodError: no non-static method "Lcom/facebook/react/turbomodule/core/CallInvokerHolderImpl;.<init>(Lcom/facebook/jni/HybridData;)V"
        at com.facebook.react.bridge.CatalystInstanceImpl.getJSCallInvokerHolder(Native Method)
        at com.facebook.react.bridge.CatalystInstanceImpl.getJSCallInvokerHolder(Unknown Source:0)
        at com.swmansion.reanimated.NativeProxy.<init>(Unknown Source:7)
        at com.swmansion.reanimated.c.v(Unknown Source:2)
        at com.swmansion.reanimated.d.getJSIModules(Unknown Source:12)
        at com.facebook.react.o.p(Unknown Source:104)
        at com.facebook.react.o.c(Unknown Source:0)
        at com.facebook.react.o$e.run(Unknown Source:68)
        at java.lang.Thread.run(Thread.java:923)`

**Comment by PrimulaX** [comment]
> Reverting `MainApplication.java` fixed the issue.

What do you mean by reverting?

**Comment by PrimulaX** [comment]
Turned out it was problem with proguard.
Noted [here](https://github.com/software-mansion/react-native-reanimated/pull/1329)

**Comment by bachbonglong** [comment]
> Turned out it was problem with proguard.
> Noted [here](https://github.com/software-mansion/react-native-reanimated/pull/1329)
> 
> proguard rule
> `-keep class com.facebook.react.turbomodule.** { *; }`

RN : 0.55.4

Not work with me. Here my Proguard-rule 

# Add project specific ProGuard rules here.
# By default, the flags in this file are appended to flags specified
# in /usr/local/Cellar/android-sdk/24.3.3/tools/proguard/proguard-android.txt
# You can edit the include path and order by changing the proguardFiles
# directive in build.gradle.
#
# For more details, see
#   http://developer.android.com/guide/developing/tools/proguard.html

# Add any project specific keep options here:

# If your project uses WebView with JS, uncomment the following
# and specify the fully qualified class name to the JavaScript interface
# class:
#-keepclassmembers class fqcn.of.javascript.interface.for.webview {
#   public *;
#}

# Disabling obfuscation is useful if you collect stack traces from production crashes
# (unless you are using a system that supports de-obfuscate the stack traces).

# React Native

# Keep our interfaces so they can be used by other ProGuard rules.
# See http://sourceforge.net/p/proguard/bugs/466/
-keep,allowobfuscation @interface com.facebook.proguard.annotations.DoNotStrip
-keep,allowobfuscation @interface com.facebook.proguard.annotations.KeepGettersAndSetters
-keep,allowobfuscation @interface com.facebook.common.internal.DoNotStrip

# Do not strip any method/class that is annotated with @DoNotStrip
-keep @com.facebook.proguard.annotations.DoNotStrip class *
-keep @com.facebook.common.internal.DoNotStrip class *
-keepclassmembers class * {
    @com.facebook.proguard.annotations.DoNotStrip *;
    @com.facebook.common.internal.DoNotStrip *;
}

-keepclassmembers @com.facebook.proguard.annotations.KeepGettersAndSetters class * {
  void set*(***);
  *** get*();
}

-keep class * extends com.facebook.react.bridge.JavaScriptModule { *; }
-keep class com.facebook.react.turbomodule.** { *; }
-keep class * extends com.facebook.react.bridge.NativeModule { *; }
-keepclassmembers,includedescriptorclasses class * { native <methods>; }
-keepclassmembers class *  { @com.facebook.react.uimanager.UIProp <fields>; }
-keepclassmembers class *  { @com.facebook.react.uimanager.annotations.ReactProp <methods>; }
-keepclassmembers class *  { @com.facebook.react.uimanager.annotations.ReactPropGroup <methods>; }


-keep class com.facebook.react.cxxbridge.ModuleRegistryHolder { *; }
-keep class com.facebook.react.bridge.ExecutorToken { *; }
-keep class com.facebook.react.bridge.CatalystInstanceImpl { *; }
-keep class com.facebook.react.bridge.JavaScriptExecutor { *; }
-keep class com.facebook.react.bridge.queue.NativeRunnable { *; }
-keep class com.facebook.react.bridge.ReadableType { *; }

-dontwarn com.facebook.react.**

# TextLayoutBuilder uses a non-public Android constructor within StaticLayout.
# See libs/proxy/src/main/java/com/facebook/fbui/textlayoutbuilder/proxy for details.
-dontwarn android.text.StaticLayout

# okhttp

-keepattributes Signature
-keepattributes *Annotation*
-keep class okhttp3.** { *; }
-keep interface okhttp3.** { *; }
-dontwarn okhttp3.**

# okio

-keep class sun.misc.Unsafe { *; }
-dontwarn java.nio.file.*
-dontwarn org.codehaus.mojo.animal_sniffer.IgnoreJRERequirement
-dontwarn okio.**
-keep class io.invertase.firebase.** { *; }
-dontwarn io.invertase.firebase.**

**Comment by PrimulaX** [comment]
@bachbonglong if you're unable to find exact rule, try to turn it off completely.

**Comment by bachbonglong** [comment]
> @bachbonglong if you're unable to find exact rule, try to turn it off completely.

Yes, Im try to turn it off but still not work

**Comment by PrimulaX** [comment]
> Yes, Im try to turn it off but still not work

So then that's not caused by proguard.
Try checking logcat logs.

**Comment by chilarai** [comment]
Thanks @PrimulaX, I did turned off my proguard in `android/app/build.gradle` and  it  worked
```
def enableProguardInReleaseBuilds = false
```

**Comment by noway** [comment]
Proguard rule change worked for me. In my case it was coming from reanimated though. This helped me: 
```
# prevent reanimated from crashing
-keep class com.swmansion.reanimated.layoutReanimation.** { *; }
```
