### ISSUE TITLE
Spell checking doesn't work on iOS

### ISSUE THREAD

**Issue by anhkieet** [facebook/react-native#31270]
## Description
Spell checking doesn't work (red underline) when typing on iOS. It worked fine on Android.

Further testing:
- Spell checking only works if there is **multiline** prop
- Or no **value** prop provided

## React Native version:
Expo SDK 40. RN 0.63.4

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Open App
2. Input text

## Expected Results
Spell checking should work

## Snack, code example, screenshot, or link to a repository:
https://snack.expo.io/sbVOzooBV

**Comment by mahadevsempires** [comment]
Same issue any update?

**Comment by fabriziobertoglio1987** [comment]
Do you still experience this issue? 

I have four years of experience maintaining facebook/react-native and I specialize in the Text and TextInput components. I currently have 58 [facebook/react-native PRs](https://github.com/facebook/react-native/pulls?q=is%3Apr+author%3Afabriziobertoglio1987+). 

If you still experience this issue, I will prepare a patched release with the fix.

Thanks a lot
