### ISSUE TITLE
Autofill section overlaps with KeyboardAvoidingView

### ISSUE THREAD

**Issue by nicolas-amabile** [facebook/react-native#31289]
## Description
On Android, the autofill section (on top of the keyboard) overlaps with the `KeyboardAvoidingView` component.

## React Native version:
```
System:
    OS: macOS 10.15.5
    CPU: (4) x64 Intel(R) Core(TM) i5-4288U CPU @ 2.60GHz
    Memory: 192.47 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.22.0 - ~/.nvm/versions/node/v12.22.0/bin/node
    Yarn: 1.19.0 - /usr/local/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v12.22.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.1
      System Images: android-22 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5
```

## Steps To Reproduce

On the [Expo Snack example](https://snack.expo.io/@nico-amabile/autofill-and-keyboardavoidingview) (make sure you select Android platform), tap on the field. If the `TextInput` has a value there is no problem, but if it's empty, the autofill section overlaps with the content.

## Expected Results
The `KeyboardAvoidingView` should be aware of that extra space.

## Snack, code example, screenshot, or link to a repository:
Snack: https://snack.expo.io/@nico-amabile/autofill-and-keyboardavoidingview

![demo](https://user-images.githubusercontent.com/8633440/113354723-f4777d80-9315-11eb-9df9-68cc8f00a66a.gif)

**Comment by fflach** [comment]
I have the same Issue. Any news on this one?
