### ISSUE TITLE
Cannot display JPEG images on iOS side decoding failure

### ISSUE THREAD

**Issue by jianglingzhi666** [facebook/react-native#31280]
react native:0.63.4
`<Image
          onError={(err) => {
            console.log(err.nativeEvent.error);
          }}
          style={{width: 22, height: 22}}
          source={{
            uri:
              'http://1300865537.vod2.myqcloud.com/96b73a68vodcq1300865537/464668ed5285890814015119948/5285890814015119949.jpeg',
          }}
        />`

**Comment by mikehardy** [comment]
What error is logged?
Do you have a minimal reproducible example you could post on github based off the template so people could easily clone something and run it with one command (e.g. `yarn  && yarn run-ios` or similar) 
You may have a much speedier resolution if you can reproduce it while using a react-native built from source so you can trace into the Image library and see exactly what's going on `../node_modules/react-native/Libraries/Image/` is where all the iOS image code lives I think?

**Comment by jianglingzhi666** [comment]
> 这样人们可以轻松地克隆某些东西并使用一

https://github.com/jianglingzhi666/IOSImageIssues

**Comment by tuantvk** [comment]
@jianglingzhi666 i build your project [https://github.com/jianglingzhi666/IOSImageIssues](https://github.com/jianglingzhi666/IOSImageIssues) on iOS but it working.
<img width="1390" alt="screen_shot" src="https://user-images.githubusercontent.com/30563960/113242357-ff60ec80-92da-11eb-9041-6c3f9af139f4.png">

**Comment by jianglingzhi666** [comment]
> @ jianglingzhi666我在iOS上构建您的项目https://github.com/jianglingzhi666/IOSImageIssues，但是它可以正常工作。
> <img alt="截屏" width="1390" src="https://user-images.githubusercontent.com/30563960/113242357-ff60ec80-92da-11eb-9041-6c3f9af139f4.png">

ios 13.5 system

**Comment by jianglingzhi666** [comment]
> @jianglingzhi666 i build your project https://github.com/jianglingzhi666/IOSImageIssues on iOS but it working.
> <img alt="screen_shot" width="1390" src="

> https://user-images.githubusercontent.com/30563960/113242357-ff60ec80-92da-11eb-9041-6c3f9af139f4.png

">



> @ jianglingzhi666我在iOS上构建您的项目https://github.com/jianglingzhi666/IOSImageIssues，但是它可以正常工作。
> <img alt="截屏" width="1390" src="https://user-images.githubusercontent.com/30563960/113242357-ff60ec80-92da-11eb-9041-6c3f9af139f4.png">

![企业微信截图_5b9362c9-f1a1-4aa7-9b52-3ca306a7f8f9](https://user-images.githubusercontent.com/54497817/113243261-4522b280-92e5-11eb-9668-1f4e54fa716d.png)
