### ISSUE TITLE
[Packager] Resolve assets based on platform.

### ISSUE THREAD

**Issue by chirag04** [facebook/react-native#3128]
So i have image named ``js_l1_icon`` on ios and android. While loading the image on ios, it is picked up the same image from android which is having a different height, width than what i expect on ios.

I just added a console.log ``generateAssetModule_DEPRECATED`` from Bundler and the path seems to be of android.

{ __packager_asset: true,
 isStatic: true,
 path: '/Users/chirag/Desktop/lrn/lrn/android/app/src/main/res/drawable-hdpi/js_l1_icon.png',
 uri: 'js_l1_icon',
 width: 72,
 height: 72,
 deprecated: true }

cc @amasad (going by commits in bundler/index.js)

**Comment by mkonicek** [comment]
I think this should to be fixed when we ship the new asset system.

**Comment by chirag04** [comment]
FYI, I'm using the master branch. Any ETA for the new asset system to land on master?

**Comment by mkonicek** [comment]
No ETA yet but it's being worked on :)

**Comment by chirag04** [comment]
Haha..can't believe i really asked for an ETA here. I guess i just wanted to ask casually. Thanks for the reply. I will wait for it.

**Comment by mkonicek** [comment]
:)

**Comment by chirag04** [comment]
@frantic closing this one in favor of the new asset system.
