### ISSUE TITLE
[0.64.0] archive fails for release due to invalid check for custom ENTRY_FILE

### ISSUE THREAD

**Issue by Johan-dutoit** [facebook/react-native#31282]
## Description
I have a monorepo setup (using nrwl), that specifies a custom ENTRY_FILE that is used within `react-native-xcode.sh` script.

This was working fine on 0.63.4, but started failing on 0.64.0.
After further inspection, I found this new check added 

https://github.com/facebook/react-native/blob/master/scripts/react-native-xcode.sh#L80-L83

It's not running in the correct context, removing it and everything works fine again.

## React Native version:
System:
    OS: macOS 11.2.3
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 2.06 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.10.1 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 23, 26, 27, 28, 29, 30
      Build Tools: 23.0.1, 28.0.3, 29.0.2, 29.0.3, 30.0.0, 30.0.1, 30.0.3
      System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: 22.0.6917172-beta1
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_181 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.0 => 0.64.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Have a monorepo setup (or custom entry file)
2. Attempt to create an iOS archive 

## Expected Results
To archive successfully.

**Comment by Johan-dutoit** [comment]
or potentially revert this PR: https://github.com/facebook/react-native/pull/29012/files

**Comment by grabbou** [comment]
The check itself seems quite helpful. Can you share the way you specify your entry file as well as your folder structure and where is the react-native-xcode.sh located in your tree? We will try to update the script to work in this manner.

**Comment by Johan-dutoit** [comment]
I totally agree that the check is useful.  Is it being run from a different directory compared to where it's actually used?
When I comment out the check, the archive works fine and my bundle is generated as expected, which leads me to believe the context. is different.

As requested

`ENTRY_FILE=./apps/mobile/src/main.tsx`

Structure
```
- root (node_modules lives here along with package.json)
   - libs
     - ...
   - apps
     - ...
     - mobile
       - src
```

**Comment by Johan-dutoit** [comment]
@grabbou  I totally agree that the check is useful.  Is it being run from a different directory compared to where it's actually used?
When I comment out the check, the archive works fine and my bundle is generated as expected, which leads me to believe the context. is different.

As requested

`ENTRY_FILE=./apps/mobile/src/main.tsx`

Structure
```
- root (node_modules lives here along with package.json)
   - libs
     - ...
   - apps
     - ...
     - mobile
       - src
```

**Comment by chasepoirier** [comment]
@Johan-dutoit I was facing the same issue the other day in my monorepo. What ended up working for me was to modify my `Bundle React Native code and images` build phase to look like this:

```bash
export NODE_BINARY=node
export EXTRA_PACKAGER_ARGS="--entry-file frontend/mobile-app/index.js"
../../../node_modules/react-native/scripts/react-native-xcode.sh frontend/mobile-app/index.js
```

This worked without any modifications to the `react-native-xcode.sh` script

**Comment by Johan-dutoit** [comment]
Thanks @chasepoirier , will give it a go!
The patch-package solution I setup has worked so far, but don't like the idea of modifying the script.

**Comment by sobernaut** [comment]
I had the same issue after upgrading react native to version 0.64.1 in a project with monorepo setup. I had the same error message as @Johan-dutoit. I managed to make it work after following exactly what the message said making following changes.

export NODE_BINARY=node
export ENTRY_FILE=mobile/index.tsx
../../node_modules/react-native/scripts/react-native-xcode.sh

I hope this helps.

**Comment by nitaliano** [comment]
This worked for me in a monorepo

```
export NODE_BINARY=node
export EXTRA_PACKAGER_ARGS="--entry-file index.js"

if [[ "$CONFIGURATION" = *Release* ]]; then
  export ENTRY_FILE=<path to index.js from monorepo root>
fi

# Go to monorepo root
cd <mono repo path>

# Run from root
./node_modules/react-native/scripts/react-native-xcode.sh
```

**Comment by samih7** [comment]
> Thanks @chasepoirier , will give it a go! The patch-package solution I setup has worked so far, but don't like the idea of modifying the script.

@Johan-dutoit Did you give it a go in the end? I am also using a nwrl monorepo and the provided solutions do not seem to help.
