### ISSUE TITLE
[TurboModules/RNTester]: Remote Debugging and Fast Refresh broken on RNTester

### ISSUE THREAD

**Issue by henrymoulton** [facebook/react-native#31299]
## Description

Making changes/debugging the RNTester app right now is difficult as Remote Debugging and Fast Refresh is broken.

This makes for a bad developer experience when trying to make contributions to React Native.

Is this because TurboModules was turned on since 0.64?

## React Native version:

```
System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 65.82 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.20.2 - ~/.nvm/versions/node/v12.20.2/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v12.20.2/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v12.20.2/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 26, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.3
      System Images: android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_242-release - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: ^5.0.1-alpha.0 => 5.0.1-alpha.0 
    react: 17.0.1 => 17.0.1 
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Clone `facebook/react-native/`
2. Setup RNTester
3. Try and make changes

## Expected Results

Either documentation on how to disable TurboModules, or options inside the repo to turn on/off when installing, similar to Fabric and Hermes.

## Screenshots

![image](https://user-images.githubusercontent.com/30093692/113568638-d7d69080-9608-11eb-9c11-0a4b862d3ad9.png)

![image](https://user-images.githubusercontent.com/30093692/113568694-eb81f700-9608-11eb-8d0d-c773afd81a80.png)

**Comment by henrymoulton** [comment]
https://github.com/react-native-community/discussions-and-proposals/issues/40#issuecomment-813684618

**Comment by projectnetworld** [comment]
same here please help with this issue its very annoying

**Comment by projectnetworld** [comment]
> [react-native-community/discussions-and-proposals#40 (comment)](https://github.com/react-native-community/discussions-and-proposals/issues/40#issuecomment-813684618)

it was not helpful at all
