### ISSUE TITLE
Animated.timing performance issues

### ISSUE THREAD

**Issue by sergeymorkovkin** [facebook/react-native#31292]
## Description
Animated.timing has some serious performance issues when starting animation with useNativeDriver=true and duration values greater than, let say, 1000ms. The higher this duration value, the larger the message for startAnimatingNode that needs to encode, pass through the bridge and decode on the UI thread. In our tests we were getting 6Kb of space-free JSON for only 5 seconds of easing output data. As a result, animation start is getting notably delayed. Especially when there are multiple animation start commands getting queued. Issue can be easily reproduced on the lower-end Androids.

Currently we're solving this by creating our own custom animation driver. This should improve after shifting to JSI, but unfortunately, there are no anticipated deadlines for it.

## React Native version:
System:
    OS: macOS 11.1
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Memory: 114.11 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.4 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.10 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 28
      Build Tools: 28.0.3
      Android NDK: 20.1.5948944
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7199119
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_252 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.1 => 17.0.1 
    react-native: ^0.64.0 => 0.64.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Create a basic RN app using Animated.timing
2. Specify useNativeDriver: true
3. Specify duration: 20000
4. Measure time taken for starting animation
5. Measure time between calling Animated.timing({...}).start() and first animated value change (https://reactnative.dev/docs/animatedvalue#addlistener)

## Expected Results
Expect animation start performance would not depend on the duration value. Or, at least, there is a way to preinitialize animation, so that calling start() call would not delay animation start.

**Comment by nkoudelia** [comment]
Looks like this issue makes any continuous animation make the CPU cooler sound like a vacuum cleaner.
Here's is one example affected by this problem: https://callstack.github.io/react-native-paper/activity-indicator.html
