### ISSUE TITLE
'memory' file not found

### ISSUE THREAD

**Issue by tapz** [facebook/react-native#31303]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

After upgrading to 0.64 Xcode build once again does not work. Here are all "Not found" and "Could not build" errors:

```
'exception' file not found
'memory' file not found
'functional' file not found
Could not build module 'React'

#include <memory>
#import <React/RCTEventDispatcher.h>
#import <React/RCTEventEmitter.h>
etc.
```

## Description
Please provide a clear and concise description of what the bug is. Include screenshots if needed.
Please test using the latest React Native release to make sure your issue has not already been fixed: https://reactnative.dev/docs/upgrading.html

## React Native version:
Run `react-native info` in your terminal and copy the results here.

```
info Fetching system and libraries information...
(node:23675) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
System:
    OS: macOS 11.2.3
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Memory: 68.66 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.10.1 - /usr/local/opt/node@14/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 7.5.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 30
      Build Tools: 29.0.3, 30.0.2
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7199119
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 14.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.64.0 => 0.64.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Start build in Xcode

## Expected Results
Describe what you expected to happen.

Successful build

## Snack, code example, screenshot, or link to a repository:
Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by tapz** [comment]
Removing `use_frameworks!` from the `podfile` helps, but one of the pods cannot be found anymore. I have basically removed `use_frameworks!` in every other RN version and added it again in every other. Would be nice to have some consistency for this between versions.

`No such module 'react_native_orientation_locker'`

**Comment by tapz** [comment]
Looks to me that `hermes_enabled => true` and `use_frameworks! `do not work together.

**Comment by CoderYLZhang** [comment]
I have the exact same problem

**Comment by skdev24** [comment]
Having the same problem after updating to V0.64.

**Comment by geroale** [comment]
Same issue here
