### ISSUE TITLE
Include of non-modular header inside framework module 'React.HermesExecutorFactory'

### ISSUE THREAD

**Issue by tapz** [facebook/react-native#31302]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Please provide a clear and concise description of what the bug is. Include screenshots if needed.
Please test using the latest React Native release to make sure your issue has not already been fixed: https://reactnative.dev/docs/upgrading.html

Build fails in Xcode:

`Include of non-modular header inside framework module 'React.HermesExecutorFactory'`

## React Native version:
Run `react-native info` in your terminal and copy the results here.

```
info Fetching system and libraries information...
(node:13053) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
System:
    OS: macOS 11.2.3
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Memory: 760.74 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.10.1 - /usr/local/opt/node@14/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 7.5.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 30
      Build Tools: 29.0.3, 30.0.2
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7199119
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 14.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.64.0 => 0.64.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Build app in Xcode

## Expected Results
Describe what you expected to happen.

Successful build

## Snack, code example, screenshot, or link to a repository:
Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by PhungVanHoa** [comment]
Same problem if i enable Hermes and use use_frameworks!

**Comment by bhattanmol101** [comment]
Same issue as @PhungVanHoa. Please provide a solution to this issue.

**Comment by evanjmg** [comment]
use_frameworks! :linkage => :static and I get this issue with hermes_enabled => true

**Comment by evanjmg** [comment]
@tapz  found a workaround 
`post_install do |installer|
  installer.pods_project.build_configuration_list.build_configurations.each do |configuration|
    configuration.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
  end
end`

**Comment by JB-CHAUVIN** [comment]
Same issue goes for me, Hermes enabled + use_framework are making the build fail on 0.64.
Everything is working without hermes...

`❌  /Users/jbchauvin/Maiia/Mobile/maiia-frontend/node_modules/react-native/ReactCommon/hermes/executor/HermesExecutorFactory.h:10:10: include of non-modular header inside framework module 'React.HermesExecutorFactory': '/Users/jbchauvin/Maiia/Mobile/maiia-frontend/packages/mobile/ios/Pods/Headers/Public/hermes-engine/hermes/hermes.h' [-Werror,-Wnon-modular-include-in-framework-module]

#include <hermes/hermes.h>
                                        ^



❌  /Users/jbchauvin/Maiia/Mobile/maiia-frontend/packages/mobile/ios/Pods/Headers/Public/hermes-engine/hermes/hermes.h:11:10: 'exception' file not found

#include <exception>
         ^



❌  /Users/jbchauvin/Maiia/Mobile/maiia-frontend/node_modules/react-native/ReactCommon/jsiexecutor/jsireact/JSINativeModules.h:10:10: 'memory' file not found

#include <memory>
         ^~~~~~~~~~~



❌  /Users/jbchauvin/Maiia/Mobile/maiia-frontend/node_modules/react-native/ReactCommon/cxxreact/CxxModule.h:10:10: 'functional' file not found

#include <functional>
         ^~~~~~~~



❌  /Users/jbchauvin/Maiia/Mobile/maiia-frontend/node_modules/react-native/ReactCommon/jsinspector/InspectorInterfaces.h:10:10: 'functional' file not found

#include <functional>
         ^~~~~~~~~~~~



❌  /Users/jbchauvin/Maiia/Mobile/maiia-frontend/node_modules/@react-native-community/toolbar-android/ios/RNCToolbarAndroid.h:3:9: could not build module 'React'

#import "RCTBridgeModule.h"`

**Comment by JB-CHAUVIN** [comment]
> pod 'React-Core/Hermes', :path => "#{prefix}/", :modular_headers => true

What did you patch ?

**Comment by JB-CHAUVIN** [comment]
> @tapz found a workaround
> patch-package and add ` pod 'React-Core/Hermes', :path => "#{prefix}/", :modular_headers => true` to the script

What did you patch ?

**Comment by Ghya** [comment]
Exact same problem here ... :/

**Comment by Aurelienlajoinie** [comment]
> > @tapz found a workaround
> > patch-package and add ` pod 'React-Core/Hermes', :path => "#{prefix}/", :modular_headers => true` to the script
> 
> What did you patch ?

I think it is the ruby script `node_modules/react-native/scripts/react_native_pods.rb` but adding `:modular_headers => true` didn't solve the issue for me :s

```
  if hermes_enabled
    pod 'React-Core/Hermes', :path => "#{prefix}/", :modular_headers => true 
    pod 'hermes-engine', '~> 0.7.2'
    pod 'libevent', '~> 2.1.12'
  end
  ```
