### ISSUE TITLE
React Native App runs using Metro instead of regular React Native

### ISSUE THREAD

**Issue by notakamihe** [facebook/react-native#31307]
So I was in the middle of working on my React Native project and received this when I re-ran my project:

[![enter image description here][1]][1]

The terminal indicated that it was running on Metro. This was extremely weird to me because for half of my project, I had been receiving the usual:

[![enter image description here][2]][2]

  [1]: https://i.stack.imgur.com/rmbCy.png
  [2]: https://i.stack.imgur.com/Mz59J.png

I was fine with this at first until I discovered that I couldn't fast refresh. This meant that when I saved or made changes to my project, it wouldn't reflect on my emulator. Additionally, certain packages that were installed just fine in React Native could not be installed successfully in Metro.

I spent hours troubleshooting and configuring in order to restore React Native to its previous state. I tried clearing cache and node modules, creating a new project, uninstalling React Native globally and even reinstalling npm. They all failed. 

Help.

**Comment by a-dev1** [comment]
I am struggling with the same problem. did you find a way to fix this?

**Comment by a-dev1** [comment]
I am also getting these errors :-
![image](https://user-images.githubusercontent.com/66349352/113703397-68d86500-96f8-11eb-8ee2-ee852906a86b.png)

**Comment by notakamihe** [comment]
Had the same error too in my original project. What I did was keep the project as is, create a brand new React Native project and put all the code from the old project into the new one. My statement about fast refresh was false. Make sure fast refresh is enabled. Also, with enough trial and error, you can install the packages you need into the project. With enough effort is was able to restore my project in the Metro Bundle.

You CAN develop in this new Metro Bundle. Make sure you run your android/ios folder in their respective IDEs beforehand. The commands for running your code on the emulator are the same (`react-native run-android` or `react-native run-ios`). I suggest starting by replacing everything in App.js with a simple hello world, test if the refresh is responsive, and build from there to restore your project.

As for Metro, I'm still going to have to wait and see and communicate more until this matter receives more attention. I'm pretty sure we are not the only ones dealing with this issue. I tried to run RN apps on two other computers, including one which never had npm installed. I still got the same result. As for now, I guess we'll have to deal with Metro being the new way to run projects.

**Comment by a-dev1** [comment]
Thanks a lot for your answer notakmihe

**Comment by johnpawl** [comment]
I want to get back to android activity from react-native activity using backkey .


**MainActivity.java**


    public class MainActivity extends AppCompatActivity {

    Button button;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        button = (Button) findViewById(R.id.button);
        button.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                startRNPage();
            }
        });
    }

    private void startRNPage() {
        Intent intent = new Intent(this, ReactNativeActivity.class);
        startActivity(intent);
        finish();
    }
    }

**ReactNativeActivity.java**



    public class ReactNativeActivity extends AppCompatActivity {
    private ReactRootView mReactRootView;
    private ReactInstanceManager mReactInstanceManager;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        SoLoader.init(this, false);

        mReactRootView = new ReactRootView(this);
        List<ReactPackage> packages = new PackageList(getApplication()).getPackages();
        // Packages that cannot be autolinked yet can be added manually here, for example:
        // packages.add(new MyReactNativePackage());
        // Remember to include them in `settings.gradle` and `app/build.gradle` too.

        

        mReactInstanceManager = ReactInstanceManager.builder()
        .setApplication(getApplication())
        .setCurrentActivity(this)
        .setBundleAssetName("index.android.bundle")
        .setJSMainModulePath("index")
        .addPackages(packages)
        .setUseDeveloperSupport(BuildConfig.DEBUG)
        .setInitialLifecycleState(LifecycleState.RESUMED)
        .build();
        // The string here (e.g. "MyReactNativeApp") has to match
        // the string in AppRegistry.registerComponent() in index.js
        mReactRootView.startReactApplication(mReactInstanceManager, "firstpro", null);

        setContentView(mReactRootView);
        }
    @Override
    public void onBackPressed() {
        if (mReactInstanceManager != null) {
            mReactInstanceManager.onBackPressed();
        } else {
          super.onBackPressed();
        }
    }
    }


I also tried the following code in ReactNativeActivity.java

    public void onBackPressed() {
        if (mReactInstanceManager != null) {
            mReactInstanceManager.onBackPressed();
        } else {
            Intent intent = new Intent(this, MainActivity.class);
            startActivity(intent);
        }
    }



If I pressed the back button it didn't get back to android activity.

How can I get back to android activity from react-native activity using backkey?
