### ISSUE TITLE
ScrollViewClass must not be undefined

### ISSUE THREAD

**Issue by prasad456** [facebook/react-native#31310]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
unable to load the screen with basic ui and doesn't add any functionality
<img width="1026" alt="Screenshot 2021-04-06 at 11 42 20 AM" src="https://user-images.githubusercontent.com/6705718/113666615-277e9000-96cd-11eb-8c70-26fc06fe6b8c.png">

## React Native version:
System:
    OS: macOS 11.0.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Memory: 71.36 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.16.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.11 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 13.0.1 - /Library/Java/JavaVirtualMachines/jdk-13.0.1.jdk/Contents/Home/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.0 => 0.64.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Login screen created and cloned for signup screen
2. After completing design with common custom components which is used for login, throwing issue

## Expected Results
Has to load signup screen like login.

**Comment by prasad456** [comment]
@augustl 
Can you help me out

**Comment by cortinico** [comment]
Closing as stale + no reproduce was provided
