### ISSUE TITLE
[Fatal] Update -[RCTBatchedBridge loadSource:] in Xcode 7 iOS 9 

### ISSUE THREAD

**Issue by eshwartm** [facebook/react-native#3131]
I install the environment for react-native, and try to get AwesomeProject running.

On the terminal that opens, I get a SyntaxError: Use of const in strict mode pointing to the line:

const babel = require('babel-core'); ^^^^^

And this exception:

'NSInternalInconsistencyException', reason: 'It looks like the implementationof __DEV__ has changed. Update -[RCTBatchedBridge loadSource:].'

Is the new version of Xcode and build target being iOS 9, the problem? Or something else?

**Comment by ide** [comment]
What version of Node are you running? Please check that it is 4+.

**Comment by eshwartm** [comment]
`node --version` is v4.1.1

**Comment by ide** [comment]
Hm.. not sure what's going on then.

**Comment by corymsmith** [comment]
I just got the same after updating my RN to 0.14-stable and my node version is 4.0.0

**Comment by corymsmith** [comment]
This was fixed by adding &dev=true to the bundle query string as I had created this app many versions of RN ago when that wasn't included in the generated project.

http://localhost:8081/index.ios.bundle?platform=ios&dev=true

**Comment by jadsonlourenco** [comment]
@corymsmith Thank you, this works fine.

**Comment by ide** [comment]
This should be fixed in master: https://github.com/facebook/react-native/commit/500ffa9b763d03e759e9b2897da7f4f7904934cf

**Comment by yychun1217** [comment]
I encountered the same problem as well. 
I hvae the correct path (http://localhost:8081/index.ios.bundle?platform=ios&dev=true)

any hints?

**Comment by nosensezzz** [comment]
I encountered the same problem while running on a device.

my simulator runs well.

My environment is ios 9.1, xcode 7.1.
