### ISSUE TITLE
[a11y] [ios] Text components do not respect accessibilityRole radiogroup

### ISSUE THREAD

**Issue by ksheppar** [facebook/react-native#31315]
## Description
Text components do not read the `accessibilityRole` `'radiogroup'`.

## React Native version:
```
System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 53.16 MB / 32.00 GB
    Shell: 5.1.4 - /usr/local/bin/bash
  Binaries:
    Node: 12.20.2 - ~/.nvm/versions/node/v12.20.2/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v12.20.2/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 29, 30
      Build Tools: 29.0.2, 30.0.1, 30.0.3
      System Images: android-29 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_282 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.2 => 0.63.2
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```
## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.
1. Create a `Text` component
2. Provide an `accessibilityRole` of `'radiogroup'`
3. Use a screenreader and focus on the component

## Expected Results
AccessibilityRole will be read aloud, same as android.

## Snack, code example, screenshot, or link to a repository:
```
const radioGroupA11yProps = {
  accessible: true,
  accessibilityRole: 'radiogroup'
};
const a11yHiddenElementRendered = (
  <Text style={[{height: 0.5}]} {...radioGroupA11yProps} />
);
return (
  a11yHiddenElementRendered
);
```

**Comment by fabriziobertoglio1987** [comment]
Do you still experience this issue? 

I have four years of experience maintaining facebook/react-native and I specialize in the Text and TextInput components. I currently have 58 [facebook/react-native PRs](https://github.com/facebook/react-native/pulls?q=is%3Apr+author%3Afabriziobertoglio1987+). 

If you still experience this issue, I will prepare a patched release with the fix.

Thanks a lot

**Comment by ksheppar** [comment]
@fabriziobertoglio1987 I haven't worked with a11y anymore so I can't say, but it seemed like a similar issue was experienced by someone else more recently here: #34635
