### ISSUE TITLE
SectionList -> SectionListModern: Refactor to functional component 

### ISSUE THREAD

**Issue by lunaleaps** [facebook/react-native#31322]
## Description
React Native team is modernizing their core APIs and components. Part of this work is refactoring components to be [functional](https://reactjs.org/docs/components-and-props.html#function-and-class-components) to make it easier to reason about side effects. This issue details the work to refactor SectionList into a functional component. 

We'll need to place this work behind an experiment so there will be a little coordination needed where the type interface of the two versions should be equivalent and an injection will be needed similar to: https://github.com/facebook/react-native/blob/fda1acec51c2cb744f3ae5a24594495b010d234f/Libraries/Lists/VirtualizedSectionListInjection.js#L16

To get started on this issue, first focus on creating a SectionListModern.js that can be substituted in RNTester examples

## Expected Results
Create a functional SectionList (SectionListModern.js) using hooks: https://reactjs.org/docs/hooks-intro.html with the same type interface as present day SectionList.js

### [Internal FB] Note upon completion
* Close T88479799 if complete

**Comment by lucasraziel** [comment]
can It be assigned to me?

**Comment by lunaleaps** [comment]
Hey @lucasraziel! Sorry we have someone internally who expressed interest already! @madhavgharmalkar (https://github.com/madhavgharmalkar) -- not sure why Github isn't allowing me to tag/assign them yet.

But keep your eyes peeled! We will have more issues like these coming soon! We should think about setting up a label for this kind of work or project board cc @kacieb, @nadiia

**Comment by lucasraziel** [comment]
> Hey @lucasraziel! Sorry we have someone internally who expressed interest already! @madhavgharmalkar (https://github.com/madhavgharmalkar) -- not sure why Github isn't allowing me to tag/assign them yet so I've just assigned it to myself for now to be clear.
> 
> But keep your eyes peeled! We will have more issues like these coming soon! We should think about setting up a label for this kind of work or project board cc @kacieb, @nadiia

Thks, @lunaleaps , I will look for another Issue that has the "good first issue" label.
