### ISSUE TITLE
Hermes iOS app size

### ISSUE THREAD

**Issue by ReyhanFabianto** [facebook/react-native#31324]
## Description
No issues when upgrading to 0.640. However, I noticed when setting `:hermes_enabled => true` in Podfile, my app size increased a lot. To be exact, running `react-native run-ios --configuration Release` installs a **90mb~** app to my device, whilst with hermes enabled, the app size grows to an enormous **985mb**.

## React Native version:
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 328.59 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.10 - ~/.nvm/versions/node/v14.15.4/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3
      System Images: android-23 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_275 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: ^0.64.0 => 0.64.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Run `react-native run-ios --configuration Release` with hermes enabled on iOS, then go to Settings, General, iPhone Storage to compare app sizes.

## Expected Results
To be honest I'm not sure if this is expected, but I'm concerned about the increase, as I don't think this happens on Android with Hermes enabled.

## Snack, code example, screenshot, or link to a repository:

**Comment by sayem314** [comment]
I have uploaded a new app on TestFlight yesterday with Hermes enabled and the app size is reasonable although more than JSC. Another thing with Hermes pod is that it's huge, around 480 MB or something last I checked.

<img src="https://user-images.githubusercontent.com/14138401/114021187-3febd780-9892-11eb-8da1-7fecda3a643b.png " alt="testflight app with hermes" width="450"/>

**Comment by ReyhanFabianto** [comment]
Hello @sayem314, thanks for the info. Would you mind explaining how your build managed to stay at 13.8mb if your Pods are at hundreds of mb? I have not reached an actual release so my knowledge regarding TestFlight is quite minimal.

**Comment by sayem314** [comment]
Total pod size doesn't have anything to do with the final app size. Your archived IPA will be around 80-100MB tho, after uploading to AppStore, it will be compressed splitting multi-arch that's built into one single file. Btw, can you share a screenshot of your app from Settings > General > Storage like this?

<img src="https://user-images.githubusercontent.com/14138401/114138321-4714f300-992f-11eb-952c-2ea6b810a0c5.png" alt="" width="450">

And also snippets of your `package.json`?

**Comment by ReyhanFabianto** [comment]
Hi @sayem314, here is the screenshot, and my full package.json :

![Screenshot](https://user-images.githubusercontent.com/32318552/114187454-376ace00-9972-11eb-95f9-540cab898260.jpg)

```
{
  "name": "-",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "ios": "react-native run-ios",
    "android": "react-native run-android"
  },
  "dependencies": {
    "@gorhom/bottom-sheet": "^3.6.3",
    "@react-native-community/async-storage": "^1.12.1",
    "@react-native-community/blur": "^3.6.0",
    "@react-native-community/clipboard": "^1.5.1",
    "@react-native-community/google-signin": "^5.0.0",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-community/picker": "^1.8.1",
    "@react-native-firebase/app": "11.2.0",
    "@react-native-firebase/messaging": "11.2.0",
    "@react-navigation/bottom-tabs": "^5.11.9",
    "@react-navigation/native": "^5.9.4",
    "@react-navigation/stack": "^5.14.4",
    "axios": "^0.21.1",
    "bson": "^4.3.0",
    "lottie-ios": "3.1.8",
    "lottie-react-native": "git+https://github.com/lottie-react-native/lottie-react-native.git",
    "moment": "^2.29.1",
    "react": "17.0.2",
    "react-native": "^0.64.0",
    "react-native-bootsplash": "^3.2.0",
    "react-native-calendars": "1.1254.0",
    "react-native-camera": "^3.43.3",
    "react-native-document-picker": "^5.0.3",
    "react-native-draggable-flatlist": "^2.5.4",
    "react-native-fast-image": "^8.3.4",
    "react-native-geolocation-service": "5.2.0",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-haptic-feedback": "^1.11.0",
    "react-native-image-crop-picker": "^0.36.0",
    "react-native-maps": "^0.28.0",
    "react-native-modal": "^11.7.0",
    "react-native-permissions": "^3.0.1",
    "react-native-qrcode-scanner": "^1.5.3",
    "react-native-qrcode-svg": "^6.1.1",
    "react-native-reanimated": "^2.1.0",
    "react-native-safe-area-context": "^3.2.0",
    "react-native-screens": "^3.1.0",
    "react-native-share": "^5.1.7",
    "react-native-shared-element": "^0.7.0",
    "react-native-svg": "^12.1.0",
    "react-native-svg-charts": "^5.4.0",
    "react-native-webview": "^11.3.2",
    "react-native-youtube-iframe": "^2.0.1",
    "react-navigation-shared-element": "5.0.0-alpha1",
    "react-redux": "^7.2.3",
    "redux": "^4.0.5",
    "redux-persist": "^6.0.0",
    "socket.io-client": "2.4.0"
  },
  "devDependencies": {
    "@babel/core": "^7.13.14",
    "@babel/runtime": "^7.13.10",
    "metro-react-native-babel-preset": "^0.65.2"
  }
}
```

**Comment by PunainenAurinko** [comment]
I also experience the same thing. My app bundle size for iOS is ~24MB. When enabling Hermes in RN v0.64 app bundle size becomes 566MB on iOS. I think this should be looked into for the next RN version patch.

**Comment by surethink** [comment]
same issue, When my rn version is0.63.4, I compile with xcode and install to my iphone 7p, in  Settings > General > Storage the size is about 116M, after I upgrade to 0.64 and set hermes_enabled => true.  now the size is 555.4M

**Comment by surethink** [comment]
> same issue, When my rn version is0.63.4, I compile with xcode and install to my iphone 7p, in Settings > General > Storage the size is about 116M, after I upgrade to 0.64 and set hermes_enabled => true. now the size is 555.4M

set hermes_enabled => false, the size is 124.8M, this is acceptable, the size increase may be caused by my updating some dependencies

**Comment by nadimahamad** [comment]
Following solution for hermes enabled and RN 0.64.2.
1.Need to do bitcode enabled - Yes at Build setting tab in xcode.
2.Need to choose deployment target version above ios 13.1
Then once do clean & build and then archive. your .ipa file size will be reduce.
