### ISSUE TITLE
[RN 0.64 - iOS] Cannot call Websocket close() with custom code

### ISSUE THREAD

**Issue by markoj3s** [facebook/react-native#31326]
## Description
When calling ws.close() with a custom code (e.g. `ws.close(4000)`), the close code passed to ws.onclose would always be 1001. (On Android, I would successfully get 4000).

## React Native version:
react: 17.0.1
react-native: 0.64.0 (was happening with 0.63.2 as well)

## Steps To Reproduce
1. Connect to a ws endpoint.
2. Call ws.close(4000)
3. Check `e.code` inside `ws.onclose = (e) => {};`

## Expected Results
I should get `4000` on iOS (like it is currently the case with Android).

**Comment by cortinico** [comment]
Closing as this version of React Native is several years old. Please re-open a new issue against the latest stable if the issue persists
