### ISSUE TITLE
FlatList crash after scrolling fastly

### ISSUE THREAD

**Issue by iamvucms** [facebook/react-native#31336]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Please provide a clear and concise description of what the bug is. Include screenshots if needed.
Please test using the latest React Native release to make sure your issue has not already been fixed: https://reactnative.dev/docs/upgrading.html

## React Native version:
Run `react-native info` in your terminal and copy the results here.
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-4900MQ CPU @ 2.80GHz
    Memory: 130.19 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.15.4 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.10 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 29, 30
      Build Tools: 29.0.3, 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.3/12C33 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_275 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.4 => 0.63.4
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Create a Flatlist with load more item when scrolldown
2. Scroll this list fastly until crashing appeared
![image](https://user-images.githubusercontent.com/17398401/114294866-92fc9f00-9acb-11eb-97c9-86c1d7e51aa6.png)
![image](https://user-images.githubusercontent.com/17398401/114294868-9a23ad00-9acb-11eb-9677-ab6756a83d12.png)

I tried to log below VirtualizedList.js:1094:
![image](https://user-images.githubusercontent.com/17398401/114294896-cdfed280-9acb-11eb-84fc-6e6f82892fea.png)
And here is what I got 
![image](https://user-images.githubusercontent.com/17398401/114294905-e40c9300-9acb-11eb-864c-b4cc93dbef2f.png)

Here is my flatlist code, my list doesn't have duplicate key 
![image](https://user-images.githubusercontent.com/17398401/114294936-09999c80-9acc-11eb-9a9b-bdbc719ec4de.png)

## Expected Results
Crashing not appear when scrolling fastly on Flatlist

**Comment by jchavezjs** [comment]
It seems to happen only in dev. When I create the release build the bug doesn't show, but I am not 100% sure that is always the case.
