### ISSUE TITLE
Alert.alert() not showing after calling Share.share()

### ISSUE THREAD

**Issue by taeh98** [facebook/react-native#31339]
## Description
I am having issues showing alerts after sharing text. I am using Share.share() to share text and then creating alerts with Alert.alert(), called in a then() method after calling Share.share(). The alert shows after only the first time Share.share() is called (by pressing a button). Subsequent button presses trigger the sharing mechanism but no alerts are shown.

With the code I provided in the gist linked below, the same behaviour arises when using an equivalent await on Share.share() in an async function instead of using then() methods. All the console.debug() statements in the then methods print as would be expected - so the code in the then() methods is executed but, for some reason, the alerts in that code don't show after the first time the code is executed. When you remove the call to Share.share() and take the calls to Alert.alert() out of the then() methods after calling Share.share(), the alerts show each time - as would be expected. This is why I think this issue is due to some interaction between Share.share() and Alert.alert(). I observed this behaviour running the code locally on an Android device with Expo over Wifi.

## React Native version:
I am using expo version 40.0.1, which includes react-native version 0.63.2, and react version 16.13.1.

Running "react-native info" gave the following output:
npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2

## Steps To Reproduce
1. Download this gist containing the source code I was running to try and debug the issue: https://gist.github.com/taeh98/d26b3a33c22d44f0634295547c72fd7d
2. Integrate this file into an Expo TypeScript project (see https://docs.expo.io/guides/typescript/#starting-from-scratch-using-a-typescript-template) as App.tsx
3. Ensure package.json has the same versions of expo, react, and react-native as listed above
4. Run locally on an Android device with Expo ("expo start --android") and scan the QR code on the landing page from the Expo Go app on an Android device
5. Try pressing the button multiple times; the Alert(s, with a second alert triggered by the callback parameter also failing to display) should only show after the first time the button is pressed - not after subsequent presses

## Desired Results
The alerts show after each time the button is pressed.

## Actual Results
The alerts show after only the first time the button is pressed.

## Snack, code example, screenshot, or link to a repository:
GitHub gist: https://gist.github.com/taeh98/d26b3a33c22d44f0634295547c72fd7d

**Comment by passionInfinite** [comment]
Any updates on this? Facing the same issue.
