### ISSUE TITLE
Convert SafeAreaView to ES Module 

### ISSUE THREAD

**Issue by lunaleaps** [facebook/react-native#31330]
## Description
SafeAreaView is currently using CommonJS export, we'd like to update this to use ES modules. You can find more about the differences here: https://irian.to/blogs/what-are-cjs-amd-umd-and-esm-in-javascript/

## Expected Results
A default exported SafeAreaView module and relevant updates from `require` to `import` (caveat: inline requires, which will should be updated to `require(...).default`.
You can use `flow` to catch any callsites missed. 

## Note
* Please assign yourself if interested! I believe you might need to comment on the issue before you can assign yourself? Otherwise please let me know so I can assign to you!

**Comment by franzon** [comment]
Hey! I'm a brazilian student and interested in starting contributing to open source software. I use React Native every day, so I think that it would be a good project to start.

Can I start working on this issue?

**Comment by lunaleaps** [comment]
Yes! Thank you for offering! Just assigned! Question: were you not able to assign yourself? (Just trying to understand if I should change my issue description)

**Comment by franzon** [comment]
Thank you! I was not able to assign myself.

**Comment by kacieb** [comment]
Looks like this is done, feel free to reopen if not!

**Comment by johnpawl** [comment]
I want to get back to android activity from react-native activity using backkey .


**MainActivity.java**


    public class MainActivity extends AppCompatActivity {

    Button button;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        button = (Button) findViewById(R.id.button);
        button.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                startRNPage();
            }
        });
    }

    private void startRNPage() {
        Intent intent = new Intent(this, ReactNativeActivity.class);
        startActivity(intent);
        finish();
    }
    }

**ReactNativeActivity.java**



    public class ReactNativeActivity extends AppCompatActivity {
    private ReactRootView mReactRootView;
    private ReactInstanceManager mReactInstanceManager;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        SoLoader.init(this, false);

        mReactRootView = new ReactRootView(this);
        List<ReactPackage> packages = new PackageList(getApplication()).getPackages();
        // Packages that cannot be autolinked yet can be added manually here, for example:
        // packages.add(new MyReactNativePackage());
        // Remember to include them in `settings.gradle` and `app/build.gradle` too.

        

        mReactInstanceManager = ReactInstanceManager.builder()
        .setApplication(getApplication())
        .setCurrentActivity(this)
        .setBundleAssetName("index.android.bundle")
        .setJSMainModulePath("index")
        .addPackages(packages)
        .setUseDeveloperSupport(BuildConfig.DEBUG)
        .setInitialLifecycleState(LifecycleState.RESUMED)
        .build();
        // The string here (e.g. "MyReactNativeApp") has to match
        // the string in AppRegistry.registerComponent() in index.js
        mReactRootView.startReactApplication(mReactInstanceManager, "firstpro", null);

        setContentView(mReactRootView);
        }
    @Override
    public void onBackPressed() {
        if (mReactInstanceManager != null) {
            mReactInstanceManager.onBackPressed();
        } else {
          super.onBackPressed();
        }
    }
    }


I also tried the following code in ReactNativeActivity.java

    public void onBackPressed() {
        if (mReactInstanceManager != null) {
            mReactInstanceManager.onBackPressed();
        } else {
            Intent intent = new Intent(this, MainActivity.class);
            startActivity(intent);
        }
    }



If I pressed the back button it didn't get back to android activity.

How can I get back to android activity from react-native activity using backkey?
