### ISSUE TITLE
npx react-native run-ios --configuration Release error if :hermes_enabled => true

### ISSUE THREAD

**Issue by FelipeSSantos1** [facebook/react-native#31342]
## Description
If we activate Hermes for iOS `:hermes_enabled => true` after clean up pod folder, delete Podfile.lock and run again pod install. If we try to run `npx react-native run-ios --configuration Release` we get the issue bellow, everything works in debug mode and also everything works if we `:hermes_enabled => false`.

![Screen Shot 2021-04-12 at 2 44 49 PM](https://user-images.githubusercontent.com/10479750/114445706-62d20080-9b9e-11eb-9e34-07163d1f65a8.png)

## React Native version:
```
System:
    OS: macOS 11.2.3
    CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
    Memory: 62.48 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.18.4 - /usr/local/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 6.14.6 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /Users/felipesantos/.rvm/gems/ruby-2.7.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 22, 23, 25, 26, 27, 29
      Build Tools: 23.0.1, 24.0.1, 25.0.0, 25.0.2, 26.0.2, 26.0.3, 27.0.2, 27.0.3, 28.0.1, 28.0.2, 28.0.3, 29.0.0, 29.0.2, 29.0.3, 30.0.2
      System Images: android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64, android-26 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_265 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.0 => 0.64.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce

1. upgrade to RN 0.64.0
2. delete `node_modules` and `Pod` folder, delete `Podfile.lock` and `yarn.lock` files
3. execute `yarn install`
4. execute pod install
5. open xcode and Clean Build Folder
6. build app on xcode
7. if previous steps was successfully executable run `npx react-native run-ios --configuration Release`

## Expected Results
1. Build successfully
2. A `Library/Developer/Xcode/DerivedData/something/Build/Products/Release-iphonesimulator` folder, should be created with a `file.app` on it. That file is a release variant and we can drag and drop it on a simulator.

## Snack, code example, screenshot, or link to a repository:
N/A

**Comment by felipemillhouse** [comment]
Maybe we have to add hermes engine into the `*-Bridging-Header.h` file?

**Comment by rectified95** [comment]
Does this also occur on 0.63, or is the problem with Hermes new to 0.64?

**Comment by felipemillhouse** [comment]
> Does this also occur on 0.63, or is the problem with Hermes new to 0.64?

It's happening only with Hermes new to 0.64... Also if we deactivate Hermes on 0.64 it works fine

**Comment by eyale** [comment]
i have longer time to build release in Jenkins up to 56 minutes per build, with Hermes enabled and RN 0.64

**Comment by AlphaJuliettOmega** [comment]
> > Does this also occur on 0.63, or is the problem with Hermes new to 0.64?

iOs only got Hermes support in .64 https://reactnative.dev/docs/hermes#ios
