### ISSUE TITLE
[RN 0.64] Image component is not able to find images marked as .android.png & .ios.png

### ISSUE THREAD

**Issue by irodeanu** [facebook/react-native#31348]
**As per react-native documentation**

> The image name is resolved the same way JS modules are resolved. In the example above, the bundler will look for my-icon.png in the same folder as the component that requires it. Also, if you have my-icon.ios.png and my-icon.android.png, the bundler will pick the correct file for the platform.

**Folder Structure**

```
 assets
     add.android.png
     add@2x.android.png
     add@3x.android.png
     add.ios.png
     add@2x.ios.png
     add@3x.ios.png
```

**Code:**

> <Image source={require('./add.png')} />

    
**Error:**

> Unable to resolve module add.png from AwesomeProject/App.js: add.png could not be found within the project or in these directories:
>   node_modules

**Comment by tijs** [comment]
I have the exact same issue and have no been able to resolve this. The asset resolution in metro seems to have changed considerably. Have downgraded back to 0.63.4 for now as i see no resolution for this (and sadly many other) issues

**Comment by t-fritsch** [comment]
Same here 😢 
The only temporary fix I found for now is to manually require the two images and chose the right one on runtime 😬 
I'm lucky I dont have so many images that differs from one platform to another, and that images are so small that the extra weight is not a problem... 
```jsx
const icons = {
	// share: require('../images/picto-share.png'),
	share_android: require('../images/picto-share.android.png'),
	share_ios: require('../images/picto-share.ios.png'),
};
// ...
<Image source={icons['share_' + Platform.OS]} />
```

**Comment by tplorts** [comment]
@irodeanu I was having this problem too.  I ended up finding (just by tinkering around) that requiring images with these platform-specific extensions works fine if I just provide a default file.

So in your case, since you have `add.ios.png` & `add.android.png`, try also picking one to version to be your default and copy it into `add.png`.  I would be curious to know if that ends up working for you (and any others here that have experience this problem).

If this is now the intended requirement for platform-specific image files, then perhaps it would be helpful to add a note to https://reactnative.dev/docs/images
Right now it just says
> Also, if you have my-icon.ios.png and my-icon.android.png, the bundler will pick the correct file for the platform.

So something like "you must also provide a default image file my-icon.png"

**Comment by rpotato** [comment]
Same issue, even using 0.63.4. It should be a problem introduced by any tool change. 

Here is the env info.

```bash
→ npx react-native info
info Fetching system and libraries information...
System:
    OS: macOS 11.3
    CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
    Memory: 86.06 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.3.0 - ~/.nvm/versions/node/v14.3.0/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 7.9.0 - ~/.nvm/versions/node/v14.3.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /Users/hlli/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 23, 26, 27, 28, 29
      Build Tools: 21.1.2, 22.0.1, 23.0.1, 23.0.3, 25.0.3, 26.0.3, 27.0.3, 28.0.3, 29.0.2, 29.0.3, 30.0.3
      System Images: android-23 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_181 - /usr/bin/javac
    Python: 3.6.5 - /usr/local/anaconda3/bin/python
  npmPackages:
    @react-native-community/cli: ^4.13.1 => 4.14.0
    react: 16.13.1 => 16.13.1
    react-native: 0.63.4 => 0.63.4
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by kasl** [comment]
we got the answer to this issue in https://github.com/facebook/metro/issues/676#issuecomment-866712819
