### ISSUE TITLE
React Native 0.64.0, iOS application build issue.

### ISSUE THREAD

**Issue by TiksGanesh** [facebook/react-native#31354]
## Description
After creating successful react native project and tried to run on iPhone simulator but it throws compilation error. Here is logcat from terminal.

warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'Yoga' from project 'Pods')
warning: None of the architectures in ARCHS (i386, x86_64) are valid. Consider setting ARCHS to $(ARCHS_STANDARD) or updating it to include at least one value from VALID_ARCHS (i386, x86_64) which is not in EXCLUDED_ARCHS (x86_64). (in target 'Yoga' from project 'Pods')
warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'React-RCTSettings' from project 'Pods')
warning: None of the architectures in ARCHS (i386, x86_64) are valid. Consider setting ARCHS to $(ARCHS_STANDARD) or updating it to include at least one value from VALID_ARCHS (i386, x86_64) which is not in EXCLUDED_ARCHS (x86_64). (in target 'React-RCTSettings' from project 'Pods')
warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'RCTTypeSafety' from project 'Pods')
warning: None of the architectures in ARCHS (i386, x86_64) are valid. Consider setting ARCHS to $(ARCHS_STANDARD) or updating it to include at least one value from VALID_ARCHS (i386, x86_64) which is not in EXCLUDED_ARCHS (x86_64). (in target 'RCTTypeSafety' from project 'Pods')
warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'React-runtimeexecutor' from project 'Pods')
warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'react-native-safe-area-context' from project 'Pods')
warning: None of the architectures in ARCHS (i386, x86_64) are valid. Consider setting ARCHS to $(ARCHS_STANDARD) or updating it to include at least one value from VALID_ARCHS (i386, x86_64) which is not in EXCLUDED_ARCHS (x86_64). (in target 'react-native-safe-area-context' from project 'Pods')
warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'glog' from project 'Pods')
warning: None of the architectures in ARCHS (i386, x86_64) are valid. Consider setting ARCHS to $(ARCHS_STANDARD) or updating it to include at least one value from VALID_ARCHS (i386, x86_64) which is not in EXCLUDED_ARCHS (x86_64). (in target 'glog' from project 'Pods')
warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'Flipper-RSocket' from project 'Pods')
warning: None of the architectures in ARCHS (i386, x86_64) are valid. Consider setting ARCHS to $(ARCHS_STANDARD) or updating it to include at least one value from VALID_ARCHS (i386, x86_64) which is not in EXCLUDED_ARCHS (x86_64). (in target 'Flipper-RSocket' from project 'Pods')
warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'DoubleConversion' from project 'Pods')
warning: None of the architectures in ARCHS (i386, x86_64) are valid. Consider setting ARCHS to $(ARCHS_STANDARD) or updating it to include at least one value from VALID_ARCHS (i386, x86_64) which is not in EXCLUDED_ARCHS (x86_64). (in target 'DoubleConversion' from project 'Pods')
warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'React-RCTBlob' from project 'Pods')
warning: None of the architectures in ARCHS (i386, x86_64) are valid. Consider setting ARCHS to $(ARCHS_STANDARD) or updating it to include at least one value from VALID_ARCHS (i386, x86_64) which is not in EXCLUDED_ARCHS (x86_64). (in target 'React-RCTBlob' from project 'Pods')
warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'React-jsiexecutor' from project 'Pods')
warning: None of the architectures in ARCHS (i386, x86_64) are valid. Consider setting ARCHS to $(ARCHS_STANDARD) or updating it to include at least one value from VALID_ARCHS (i386, x86_64) which is not in EXCLUDED_ARCHS (x86_64). (in target 'React-jsiexecutor' from project 'Pods')
warning: Capabilities for Signing & Capabilities may not function correctly because its entitlements use a placeholder team ID. To resolve this, select a development team in the test editor. (in target 'test' from project 'test')
warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'test' from project 'test')
warning: None of the architectures in ARCHS (i386, x86_64) are valid. Consider setting ARCHS to $(ARCHS_STANDARD) or updating it to include at least one value from VALID_ARCHS (i386, x86_64) which is not in EXCLUDED_ARCHS (x86_64). (in target 'test' from project 'test')
warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'Pods-test' from project 'Pods')
warning: None of the architectures in ARCHS (i386, x86_64) are valid. Consider setting ARCHS to $(ARCHS_STANDARD) or updating it to include at least one value from VALID_ARCHS (i386, x86_64) which is not in EXCLUDED_ARCHS (x86_64). (in target 'Pods-test' from project 'Pods')
warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'Flipper-PeerTalk' from project 'Pods')
warning: None of the architectures in ARCHS (i386, x86_64) are valid. Consider setting ARCHS to $(ARCHS_STANDARD) or updating it to include at least one value from VALID_ARCHS (i386, x86_64) which is not in EXCLUDED_ARCHS (x86_64). (in target 'Flipper-PeerTalk' from project 'Pods')
warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'FlipperKit' from project 'Pods')
warning: None of the architectures in ARCHS (i386, x86_64) are valid. Consider setting ARCHS to $(ARCHS_STANDARD) or updating it to include at least one value from VALID_ARCHS (i386, x86_64) which is not in EXCLUDED_ARCHS (x86_64). (in target 'FlipperKit' from project 'Pods')
warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'Flipper-DoubleConversion' from project 'Pods')
warning: None of the architectures in ARCHS (i386, x86_64) are valid. Consider setting ARCHS to $(ARCHS_STANDARD) or updating it to include at least one value from VALID_ARCHS (i386, x86_64) which is not in EXCLUDED_ARCHS (x86_64). (in target 'Flipper-DoubleConversion' from project 'Pods')
warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'RNScreens' from project 'Pods')
warning: None of the architectures in ARCHS (i386, x86_64) are valid. Consider setting ARCHS to $(ARCHS_STANDARD) or updating it to include at least one value from VALID_ARCHS (i386, x86_64) which is not in EXCLUDED_ARCHS (x86_64). (in target 'RNScreens' from project 'Pods')
warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'React-RCTLinking' from project 'Pods')
warning: None of the architectures in ARCHS (i386, x86_64) are valid. Consider setting ARCHS to $(ARCHS_STANDARD) or updating it to include at least one value from VALID_ARCHS (i386, x86_64) which is not in EXCLUDED_ARCHS (x86_64). (in target 'React-RCTLinking' from project 'Pods')
warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'React-RCTText' from project 'Pods')
warning: None of the architectures in ARCHS (i386, x86_64) are valid. Consider setting ARCHS to $(ARCHS_STANDARD) or updating it to include at least one value from VALID_ARCHS (i386, x86_64) which is not in EXCLUDED_ARCHS (x86_64). (in target 'React-RCTText' from project 'Pods')
warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'ReactCommon' from project 'Pods')
warning: None of the architectures in ARCHS (i386, x86_64) are valid. Consider setting ARCHS to $(ARCHS_STANDARD) or updating it to include at least one value from VALID_ARCHS (i386, x86_64) which is not in EXCLUDED_ARCHS (x86_64). (in target 'ReactCommon' from project 'Pods')
warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'boost-for-react-native' from project 'Pods')
warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'React-RCTImage' from project 'Pods')
warning: None of the architectures in ARCHS (i386, x86_64) are valid. Consider setting ARCHS to $(ARCHS_STANDARD) or updating it to include at least one value from VALID_ARCHS (i386, x86_64) which is not in EXCLUDED_ARCHS (x86_64). (in target 'React-RCTImage' from project 'Pods')
warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'libevent' from project 'Pods')
warning: None of the architectures in ARCHS (i386, x86_64) are valid. Consider setting ARCHS to $(ARCHS_STANDARD) or updating it to include at least one value from VALID_ARCHS (i386, x86_64) which is not in EXCLUDED_ARCHS (x86_64). (in target 'libevent' from project 'Pods')
warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'RNGestureHandler' from project 'Pods')
warning: None of the architectures in ARCHS (i386, x86_64) are valid. Consider setting ARCHS to $(ARCHS_STANDARD) or updating it to include at least one value from VALID_ARCHS (i386, x86_64) which is not in EXCLUDED_ARCHS (x86_64). (in target 'RNGestureHandler' from project 'Pods')
warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'React-Core-AccessibilityResources' from project 'Pods')
warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'React-cxxreact' from project 'Pods')
warning: None of the architectures in ARCHS (i386, x86_64) are valid. Consider setting ARCHS to $(ARCHS_STANDARD) or updating it to include at least one value from VALID_ARCHS (i386, x86_64) which is not in EXCLUDED_ARCHS (x86_64). (in target 'React-cxxreact' from project 'Pods')
warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'React-jsi' from project 'Pods')
warning: None of the architectures in ARCHS (i386, x86_64) are valid. Consider setting ARCHS to $(ARCHS_STANDARD) or updating it to include at least one value from VALID_ARCHS (i386, x86_64) which is not in EXCLUDED_ARCHS (x86_64). (in target 'React-jsi' from project 'Pods')
warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'React' from project 'Pods')
warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'Flipper-Folly' from project 'Pods')
warning: None of the architectures in ARCHS (i386, x86_64) are valid. Consider setting ARCHS to $(ARCHS_STANDARD) or updating it to include at least one value from VALID_ARCHS (i386, x86_64) which is not in EXCLUDED_ARCHS (x86_64). (in target 'Flipper-Folly' from project 'Pods')
warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'React-CoreModules' from project 'Pods')
warning: None of the architectures in ARCHS (i386, x86_64) are valid. Consider setting ARCHS to $(ARCHS_STANDARD) or updating it to include at least one value from VALID_ARCHS (i386, x86_64) which is not in EXCLUDED_ARCHS (x86_64). (in target 'React-CoreModules' from project 'Pods')
warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'RCTRequired' from project 'Pods')
warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'RNReanimated' from project 'Pods')
warning: None of the architectures in ARCHS (i386, x86_64) are valid. Consider setting ARCHS to $(ARCHS_STANDARD) or updating it to include at least one value from VALID_ARCHS (i386, x86_64) which is not in EXCLUDED_ARCHS (x86_64). (in target 'RNReanimated' from project 'Pods')
warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'React-RCTAnimation' from project 'Pods')
warning: None of the architectures in ARCHS (i386, x86_64) are valid. Consider setting ARCHS to $(ARCHS_STANDARD) or updating it to include at least one value from VALID_ARCHS (i386, x86_64) which is not in EXCLUDED_ARCHS (x86_64). (in target 'React-RCTAnimation' from project 'Pods')
warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'React-Core' from project 'Pods')
warning: None of the architectures in ARCHS (i386, x86_64) are valid. Consider setting ARCHS to $(ARCHS_STANDARD) or updating it to include at least one value from VALID_ARCHS (i386, x86_64) which is not in EXCLUDED_ARCHS (x86_64). (in target 'React-Core' from project 'Pods')
warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'RCT-Folly' from project 'Pods')
warning: None of the architectures in ARCHS (i386, x86_64) are valid. Consider setting ARCHS to $(ARCHS_STANDARD) or updating it to include at least one value from VALID_ARCHS (i386, x86_64) which is not in EXCLUDED_ARCHS (x86_64). (in target 'RCT-Folly' from project 'Pods')
warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'React-RCTNetwork' from project 'Pods')
warning: None of the architectures in ARCHS (i386, x86_64) are valid. Consider setting ARCHS to $(ARCHS_STANDARD) or updating it to include at least one value from VALID_ARCHS (i386, x86_64) which is not in EXCLUDED_ARCHS (x86_64). (in target 'React-RCTNetwork' from project 'Pods')
warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'Flipper' from project 'Pods')
warning: None of the architectures in ARCHS (i386, x86_64) are valid. Consider setting ARCHS to $(ARCHS_STANDARD) or updating it to include at least one value from VALID_ARCHS (i386, x86_64) which is not in EXCLUDED_ARCHS (x86_64). (in target 'Flipper' from project 'Pods')
warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'CocoaAsyncSocket' from project 'Pods')
warning: None of the architectures in ARCHS (i386, x86_64) are valid. Consider setting ARCHS to $(ARCHS_STANDARD) or updating it to include at least one value from VALID_ARCHS (i386, x86_64) which is not in EXCLUDED_ARCHS (x86_64). (in target 'CocoaAsyncSocket' from project 'Pods')
warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'FBLazyVector' from project 'Pods')
warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'React-RCTActionSheet' from project 'Pods')
warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'Flipper-Glog' from project 'Pods')
warning: None of the architectures in ARCHS (i386, x86_64) are valid. Consider setting ARCHS to $(ARCHS_STANDARD) or updating it to include at least one value from VALID_ARCHS (i386, x86_64) which is not in EXCLUDED_ARCHS (x86_64). (in target 'Flipper-Glog' from project 'Pods')
warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'React-RCTVibration' from project 'Pods')
warning: None of the architectures in ARCHS (i386, x86_64) are valid. Consider setting ARCHS to $(ARCHS_STANDARD) or updating it to include at least one value from VALID_ARCHS (i386, x86_64) which is not in EXCLUDED_ARCHS (x86_64). (in target 'React-RCTVibration' from project 'Pods')
warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'React-callinvoker' from project 'Pods')
warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'React-jsinspector' from project 'Pods')
warning: None of the architectures in ARCHS (i386, x86_64) are valid. Consider setting ARCHS to $(ARCHS_STANDARD) or updating it to include at least one value from VALID_ARCHS (i386, x86_64) which is not in EXCLUDED_ARCHS (x86_64). (in target 'React-jsinspector' from project 'Pods')
warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'React-perflogger' from project 'Pods')
warning: None of the architectures in ARCHS (i386, x86_64) are valid. Consider setting ARCHS to $(ARCHS_STANDARD) or updating it to include at least one value from VALID_ARCHS (i386, x86_64) which is not in EXCLUDED_ARCHS (x86_64). (in target 'React-perflogger' from project 'Pods')
warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'OpenSSL-Universal' from project 'Pods')
warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'FBReactNativeSpec' from project 'Pods')
warning: None of the architectures in ARCHS (i386, x86_64) are valid. Consider setting ARCHS to $(ARCHS_STANDARD) or updating it to include at least one value from VALID_ARCHS (i386, x86_64) which is not in EXCLUDED_ARCHS (x86_64). (in target 'FBReactNativeSpec' from project 'Pods')

** BUILD FAILED **

The following build commands failed:
        PhaseScriptExecution [CP]\ Copy\ XCFrameworks /Users/dhananjaytikone/Library/Developer/Xcode/DerivedData/test-ebmczwjmnbcljhapdtbnzhbwsfuv/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/OpenSSL-Universal.build/Script-239320555926E0CD72D979B69B4A8ECC.sh

## React Native version:
System:
    OS: macOS 11.0.1
    CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
    Memory: 77.53 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 13.12.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 7.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 26, 27, 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3
      System Images: android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_242-release - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.0 => 0.64.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
build application and try to run on iPhone Simulator
1. fired command in Terminal,  npx react-native init iPhoneTest
2. after project created successfully, cd iPhoneTest/ios
3. fire command in Terminal, pod install 
4. navigate to parent directory, cd..
5. run project, React-native run-ios

## Expected Results
It should build application and run on iPhone Simulator or it should throw error for deployment issue because of signing certificate.

**Comment by Asinox** [comment]
Maybe https://stackoverflow.com/questions/50768723/what-does-warning-mapping-architecture-arm64-to-x86-64-mean

**Comment by jonrigerths2** [comment]
I'm having the exact same issue. I noticed you're on XCode 11, so am I. I have a hunch that this is the reason, especially because XCode gives a version error when attempting to open the xcode project.

Are you able to update to XCode 12 by chance and try again? I'm stuck on Mojave at the moment (long story) so can't update yet :)

**Comment by rossedwardsus** [comment]
Same problem.  No xcode involved.  Created a new project, ran npx react-native start in one terminal and npx react-native run-ios in another, and this same error was thrown.

Any fixes for this?

**Comment by TiksGanesh** [comment]
> I'm having the exact same issue. I noticed you're on XCode 11, so am I. I have a hunch that this is the reason, especially because XCode gives a version error when attempting to open the xcode project.
> 
> Are you able to update to XCode 12 by chance and try again? I'm stuck on Mojave at the moment (long story) so can't update yet :)

After few checks, I felt same that due to older version of XCode, I am running into this issue. I upgraded XCode to latest and tried once again but no success.

**Comment by rossedwardsus** [comment]
What about using a previous version of react native?

**Comment by TiksGanesh** [comment]
> What about using a previous version of react native?

Already on older version 0.62.2

**Comment by rossedwardsus** [comment]
Are you getting the same error or a different one.  There apparently is a bug in older versions of react native but there is a fix for it.

**Comment by rossedwardsus** [comment]
I am running 0..63.4.  But you have to change a line in Podfile or else it crashes.

**Comment by jonrigerths2** [comment]
After days of fighting with this, I finally have v64 running! Hopefully this helps someone...

I do think XCode 12 is required to run this project (even if you are not using the XCode app, I believe iOS still builds via the XCode dev tools). This was obvious when attempting to open the .xcworkspace/.xcodeproj files and getting an error that the version was not compatible. The RN CLI environment setup says XCode 10 but maybe that needs to be updated.

So this is what I did:

1. You need to be on Catalina or higher to get XCode 12. I can't go to Big Sur yet due to company policy, so first step was updating to Catalina
2. After updating to Catalina, install XCode 12.4 (I believe this is the latest you can get with Catalina): https://developer.apple.com/download/more/?=xcode
3. After it finishes (this took 6-8 hours for me), open it up, go to Preferences > Locations, make sure XCode 12.4 is selected for Command Line Tools (Note: I installed the command line tools before the full XCode package, I'm not sure if that is necessary or not. If 12.4 doesn't show up then you may have to download separately and select it here - I'm not much of an XCode user)
4. I installed Node 14 (using `nvm`), just in case, I'm not sure what version is actually required
5. Updated cocoapods (`brew install cocoapods`). This gave me some simlink errors, I deleted the old directories that it recommended removing and ran `brew link cocoapods`
6. At this point, I could finally run the project via the XCode app, but not through terminal, but this ended up being an `nvm` issue. I kept getting an `nvm is not compatible with the "npm_config_prefix" environment variable` error. I ran `nvm unalias default`, then installed the latest `nvm`, then ran `nvm alias default 14`. This appears to have fixed the problem

Good luck to anyone else having these issues 😄

**Comment by Chi-AnTai** [comment]
> After days of fighting with this, I finally have v64 running! Hopefully this helps someone...
> 
> I do think XCode 12 is required to run this project (even if you are not using the XCode app, I believe iOS still builds via the XCode dev tools). This was obvious when attempting to open the .xcworkspace/.xcodeproj files and getting an error that the version was not compatible. The RN CLI environment setup says XCode 10 but maybe that needs to be updated.
> 
> So this is what I did:
> 
> 1. You need to be on Catalina or higher to get XCode 12. I can't go to Big Sur yet due to company policy, so first step was updating to Catalina
> 2. After updating to Catalina, install XCode 12.4 (I believe this is the latest you can get with Catalina): https://developer.apple.com/download/more/?=xcode
> 3. After it finishes (this took 6-8 hours for me), open it up, go to Preferences > Locations, make sure XCode 12.4 is selected for Command Line Tools (Note: I installed the command line tools before the full XCode package, I'm not sure if that is necessary or not. If 12.4 doesn't show up then you may have to download separately and select it here - I'm not much of an XCode user)
> 4. I installed Node 14 (using `nvm`), just in case, I'm not sure what version is actually required
> 5. Updated cocoapods (`brew install cocoapods`). This gave me some simlink errors, I deleted the old directories that it recommended removing and ran `brew link cocoapods`
> 6. At this point, I could finally run the project via the XCode app, but not through terminal, but this ended up being an `nvm` issue. I kept getting an `nvm is not compatible with the "npm_config_prefix" environment variable` error. I ran `nvm unalias default`, then installed the latest `nvm`, then ran `nvm alias default 14`. This appears to have fixed the problem
> 
> Good luck to anyone else having these issues 😄

Thank! Since I had both Xcode 11 and 12, this command line select really saved me.

**Comment by TiksGanesh** [comment]
> After days of fighting with this, I finally have v64 running! Hopefully this helps someone...
> 
> I do think XCode 12 is required to run this project (even if you are not using the XCode app, I believe iOS still builds via the XCode dev tools). This was obvious when attempting to open the .xcworkspace/.xcodeproj files and getting an error that the version was not compatible. The RN CLI environment setup says XCode 10 but maybe that needs to be updated.
> 
> So this is what I did:
> 
> 1. You need to be on Catalina or higher to get XCode 12. I can't go to Big Sur yet due to company policy, so first step was updating to Catalina
> 2. After updating to Catalina, install XCode 12.4 (I believe this is the latest you can get with Catalina): https://developer.apple.com/download/more/?=xcode
> 3. After it finishes (this took 6-8 hours for me), open it up, go to Preferences > Locations, make sure XCode 12.4 is selected for Command Line Tools (Note: I installed the command line tools before the full XCode package, I'm not sure if that is necessary or not. If 12.4 doesn't show up then you may have to download separately and select it here - I'm not much of an XCode user)
> 4. I installed Node 14 (using `nvm`), just in case, I'm not sure what version is actually required
> 5. Updated cocoapods (`brew install cocoapods`). This gave me some simlink errors, I deleted the old directories that it recommended removing and ran `brew link cocoapods`
> 6. At this point, I could finally run the project via the XCode app, but not through terminal, but this ended up being an `nvm` issue. I kept getting an `nvm is not compatible with the "npm_config_prefix" environment variable` error. I ran `nvm unalias default`, then installed the latest `nvm`, then ran `nvm alias default 14`. This appears to have fixed the problem
> 
> Good luck to anyone else having these issues 😄

This resolved my issue, Thanks

**Comment by Itsindigo** [comment]
If you've followed @jonrigerths2's steps and you're still running into the same issue, you can also delete the contents of `node_modules/react-native/scripts/find-node.sh`, this will however stop working each time you reinstall your dependencies.

**Comment by AyoubAtba** [comment]
> After days of fighting with this, I finally have v64 running! Hopefully this helps someone...
> 
> I do think XCode 12 is required to run this project (even if you are not using the XCode app, I believe iOS still builds via the XCode dev tools). This was obvious when attempting to open the .xcworkspace/.xcodeproj files and getting an error that the version was not compatible. The RN CLI environment setup says XCode 10 but maybe that needs to be updated.
> 
> So this is what I did:
> 
> 1. You need to be on Catalina or higher to get XCode 12. I can't go to Big Sur yet due to company policy, so first step was updating to Catalina
> 2. After updating to Catalina, install XCode 12.4 (I believe this is the latest you can get with Catalina): https://developer.apple.com/download/more/?=xcode
> 3. After it finishes (this took 6-8 hours for me), open it up, go to Preferences > Locations, make sure XCode 12.4 is selected for Command Line Tools (Note: I installed the command line tools before the full XCode package, I'm not sure if that is necessary or not. If 12.4 doesn't show up then you may have to download separately and select it here - I'm not much of an XCode user)
> 4. I installed Node 14 (using `nvm`), just in case, I'm not sure what version is actually required
> 5. Updated cocoapods (`brew install cocoapods`). This gave me some simlink errors, I deleted the old directories that it recommended removing and ran `brew link cocoapods`
> 6. At this point, I could finally run the project via the XCode app, but not through terminal, but this ended up being an `nvm` issue. I kept getting an `nvm is not compatible with the "npm_config_prefix" environment variable` error. I ran `nvm unalias default`, then installed the latest `nvm`, then ran `nvm alias default 14`. This appears to have fixed the problem
> 
> Good luck to anyone else having these issues 😄

I'm facing the same problem with Xcode 12

**Comment by ildaneta** [comment]
I had to update my xcode to the version 12.2 and my problem was resolved.

**Comment by Thembelani** [comment]
> After days of fighting with this, I finally have v64 running! Hopefully this helps someone...
> 
> I do think XCode 12 is required to run this project (even if you are not using the XCode app, I believe iOS still builds via the XCode dev tools). This was obvious when attempting to open the .xcworkspace/.xcodeproj files and getting an error that the version was not compatible. The RN CLI environment setup says XCode 10 but maybe that needs to be updated.
> 
> So this is what I did:
> 
> 1. You need to be on Catalina or higher to get XCode 12. I can't go to Big Sur yet due to company policy, so first step was updating to Catalina
> 2. After updating to Catalina, install XCode 12.4 (I believe this is the latest you can get with Catalina): https://developer.apple.com/download/more/?=xcode
> 3. After it finishes (this took 6-8 hours for me), open it up, go to Preferences > Locations, make sure XCode 12.4 is selected for Command Line Tools (Note: I installed the command line tools before the full XCode package, I'm not sure if that is necessary or not. If 12.4 doesn't show up then you may have to download separately and select it here - I'm not much of an XCode user)
> 4. I installed Node 14 (using `nvm`), just in case, I'm not sure what version is actually required
> 5. Updated cocoapods (`brew install cocoapods`). This gave me some simlink errors, I deleted the old directories that it recommended removing and ran `brew link cocoapods`
> 6. At this point, I could finally run the project via the XCode app, but not through terminal, but this ended up being an `nvm` issue. I kept getting an `nvm is not compatible with the "npm_config_prefix" environment variable` error. I ran `nvm unalias default`, then installed the latest `nvm`, then ran `nvm alias default 14`. This appears to have fixed the problem
> 
> Good luck to anyone else having these issues 😄

I have this issue with xcode 13

**Comment by Prince-Hamza** [comment]
I have same problem with xcode 13.0. Is there anyway to solve it?
