### ISSUE TITLE
[RN 0.64.0] `pod lib lint` stopped working

### ISSUE THREAD

**Issue by teodorciuraru** [facebook/react-native#31359]
## Description
I'm developing a react native native module. Building the module, building the example app and running `pod lib lint` worked on 0.63.4. After upgrading to 0.64.0 by integrating the changes via the RN upgrade helper, `pod lib lint` fails with `.../ios/Pods/Headers/Private/RCT-Folly/folly/math.h:26:10: 'limits' file not found`.

## React Native version:
System:
    OS: macOS 11.2.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
    Memory: 1.50 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v10.15.3/bin/yarn
    npm: 7.5.2 - ~/.nvm/versions/node/v10.15.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      Android NDK: 21.1.6352462
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 13.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.64.0 => 0.64.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
1. `yarn`
2. `cd ios; pod install`
3. `pod lib lint --allow-warnings --verbose --no-clean`

## Expected Results
Pod linting passes just like in 0.63.4.

## Podfile

```ruby
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'ADEUMReactNative' do
  config = use_native_modules!
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
  end
end
```

## Podspec:

```rb

  ...

  s.source_files = "ios/ADEUMReactNative.m", "ios/ADEUMReactNative.h"
  s.vendored_framework = "ios/ADEUMInstrumentation.framework"
  
  s.dependency "React"

  s.user_target_xcconfig = {     
    'HEADER_SEARCH_PATHS' => "'#{__dir__}/ios/Pods/Headers/**'",
    "CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES" => TRUE
  }
  
  s.pod_target_xcconfig = { 
    'HEADER_SEARCH_PATHS' => "'#{__dir__}/ios/Pods/Headers/**'",
    "EXCLUDED_ARCHS[sdk=iphonesimulator*]" => 'arm64'
  }
```
## Podlib lint project building (debug or release)
<img width="352" alt="Screenshot 2021-04-14 at 19 06 20" src="https://user-images.githubusercontent.com/7328298/114743351-46c48f80-9d55-11eb-82f5-b286c8e2b923.png">

It seems that `.../ios/Pods/Headers/Private/Yoga/yoga/Yoga.h:11:10: Non-portable path to file '<Math.h>'; specified path differs in case from file name on disk` this might affect somehow. I'm estimating that something changed in the react-native pod when upgrading.

**Comment by cortinico** [comment]
Hey,
We're cleaning up the React Native issue tracker to make sure we focus on the most important issues first.

I'm closing this one because it's stale and related to a version of React Native we no longer support. If the issue persists on the latest version, please re-open a new issue and reference this one.

Thank you.
