### ISSUE TITLE
[Packager] Development server not auto starting from Xcode

### ISSUE THREAD

**Issue by pangers** [facebook/react-native#3135]
I am trying to run the react native application through Xcode, however, the development server does not seem to get started automatically. I must always type npm start at the project root before running in Xcode. Where am I going wrong?

**Comment by antoaravinth** [comment]
What version of xcode are you running?

**Comment by pangers** [comment]
I am running Xcode 7

**Comment by brentvatne** [comment]
Hi @pangers! That's unfortunate. Did you try rebooting your machine? And close any existing terminal window with the dev server running?

**Comment by jaygarcia** [comment]
This could be a path issue somewhere. Is NPM installed properly? is it globally accessible?

**Comment by pangers** [comment]
@brentvatne Yep just restarted my machine, with no terminal windows open and I must still run npm start manually before building with Xcode.

@jaygarcia I seem to be able to type npm -v in any directory of my computer so I assume it is globally accesible

**Comment by grabbou** [comment]
There's been also an issue regarding that but I can't find it. Are you running `xcodeproj` or `xcworkspace` with Pods? I am on XCode 7 and everything works properly. With Pods, it looks like you may need to copy one script that's responsible for packager to your build settings.

Please check if you have it under Build Phases -> Run Script.
<img width="1102" alt="screen shot 2015-10-01 at 10 28 39" src="https://cloud.githubusercontent.com/assets/2464966/10216146/38a65e4c-6827-11e5-8afb-820207817b52.png">

**Comment by pangers** [comment]
I discovered the problem. One of the directories that the project folder was in had a space in its name. As soon as I removed the space, hitting command + R automatically ran the npm server!

**Comment by kostiakoval** [comment]
Yes I had faced the same issue. It's because of space in the directory name

"The file /Users/konstantin/Desktop/Test One/TestMe/node_modules/react-native/React/One/TestMe/node_modules/react-native/packager/launchPackager.command does not exist.
Can't start packager automatically
"

**Comment by S-YOU** [comment]
May be add double quotes to this line https://github.com/facebook/react-native/blob/91e6c98ecdf5c9116bd894475ce3f3ed601fc5bc/React/React.xcodeproj/project.pbxproj#L576

`"$SRCROOT/../packager/launchPackager.command"`

**Comment by mroswald** [comment]
+1
