### ISSUE TITLE
text.replaceAll don't active in react native 0.63, crash app in android but ios active - bug when run release

### ISSUE THREAD

**Issue by nnhunguet** [facebook/react-native#31360]
My app crash when i build release in android app if i use replaceAll(). Help me !! 
![Screen Shot 2021-04-15 at 00 36 10](https://user-images.githubusercontent.com/52577080/114754261-953c5300-9d82-11eb-93b0-94d162af901e.png)

![Screen Shot 2021-04-15 at 00 34 17](https://user-images.githubusercontent.com/52577080/114754030-51e1e480-9d82-11eb-8c14-79fdbc903990.png)
![Screen Shot 2021-04-15 at 00 34 45](https://user-images.githubusercontent.com/52577080/114754091-61f9c400-9d82-11eb-8ca6-f93c7998de33.png)

**Comment by nnhunguet** [comment]
Help me ? I don't know it bug :(

**Comment by Bang9** [comment]
https://github.com/facebook/hermes/issues/381

**Comment by nnhunguet** [comment]
Thank you. I don't use replaeAll, instead i use replace and regex ! 
Thank you everryone !
