### ISSUE TITLE
[Packager] watcher.watchProjectInfo equals null

### ISSUE THREAD

**Issue by aleclarson** [facebook/react-native#3136]
At first, there seemed to be something causing the packager to stall when crawling the filesystem.

But after a second look, I had to add a `done()` call to the `Promise` returned by `DependencyGraph.prototype.load` to even find the error. This part is fixed by #2956.

Now I can see that [this line](https://github.com/facebook/react-native/blob/master/packager/react-packager/src/DependencyResolver/crawlers/index.js#L16) fails because `watcher.watchProjectInfo` equals `null`.

What should I do, @amasad?

**Comment by rjoonas** [comment]
Seems like a duplicate of https://github.com/facebook/react-native/issues/2231?

**Comment by aleclarson** [comment]
Oh, yep. Nice find @rjoonas.
