### ISSUE TITLE
TextInput selection inconsistent on iOS

### ISSUE THREAD

**Issue by flextremedev** [facebook/react-native#31364]
## Description
The TextInput selection behaves inconsistently. 
When I set selection prop to `{start: 0, end: value.length }` the value is not always selected.

## React Native version:
0.63.2

## Steps To Reproduce
Visit https://snack.expo.io/H1O7BgsXg
1. Run on android device/emulator.
2. Click on the right half of the right "0".

## Expected Results
I expect "00" to be selected.

## Snack, code example, screenshot, or link to a repository:
https://snack.expo.io/H1O7BgsXg

This might be caused by the mouse click however I don't have the possibility to test it on an iPhone.

**Comment by kyoz** [comment]
Confirm. Also setNativeProps position doesn't work too.

**Comment by cortinico** [comment]
Closing as stale + duplicate of https://github.com/facebook/react-native/issues/31353
