### ISSUE TITLE
Getting "EISDIR: illegal operation on a directory" error when turning on debugger mode on Version RN 0.64

### ISSUE THREAD

**Issue by vyshakh** [facebook/react-native#31366]
## Description
Getting "EISDIR: illegal operation on a directory" error when turning on debugger mode on Version RN 0.64

<img width="1101" alt="metro error after update" src="https://user-images.githubusercontent.com/2608067/114840677-1aa61e80-9de8-11eb-944a-5eaba22df0a3.png">

## React Native version:
System:
    OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 188.03 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.16.1 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.12 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.4 - /usr/local/bin/pod
  SDKs:
    iOS SDK: Not Found
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3
      System Images: android-28 | Google Play Intel x86 Atom, android-29 | Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_242 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.0 => 0.64.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. react-native init testproject
2. react-native run-android

## Expected Results
Expecting metro console without error

**Comment by vyshakh** [comment]
Looks like there is already a fix for this issue. https://github.com/facebook/metro/pull/567 
[Fix is here](https://github.com/facebook/metro/commit/1e6cec8d869319f72e8b681267a3db5f6f92ce4d#diff-2f53e5bf01c9458b9add1455fb7683f15e2b506f4603d9936160443699198f5a)

**Comment by bibinprathap** [comment]
when turning on debugger mode on Version RN 0.64 getting the same error on Windows OS  also.
I think this error is related to the following  warning message showing on the google chrome console

DevTools failed to load SourceMap: Could not load content for http://localhost:8081/debugger-ui/debuggerWorker.aca173c4.js.map: Fetch through target failed: Target not supported; Fallback: HTTP error: status code 500, net::ERR_HTTP_RESPONSE_CODE_FAILURE 

![image](https://user-images.githubusercontent.com/17843160/116965815-c217c200-acbf-11eb-9852-8ae25798697b.png)

**Comment by cheese-git** [comment]
Same problem here.

**Comment by vyshakh** [comment]
I had a global react-native cli which caused the issue. Try running  ```npx react-native run-android```

**Comment by egueiros** [comment]
Sorry, this issue was closed without any pointers to what the ultimate solution is. We're in the process of upgrading from 0.63.3 to 0.64.2 and running into the same issue.

**Comment by vyshakh** [comment]
> Sorry, this issue was closed without any pointers to what the ultimate solution is. We're in the process of upgrading from 0.63.3 to 0.64.2 and running into the same issue.
> 
> If I turn off soureMaps in Dev Tools, the error goes away, but my application never loads (blank screen). Something is off.

I'm not getting blank screen but still getting Getting "EISDIR: illegal operation on a directory" error when turning on debugger on Version RN 0.64.2 as well.  I closed the issue by mistake,  Re-opening the issue

**Comment by egueiros** [comment]
@vyshakh thanks for your reply. There might be a chance the EISDIR error and the blank screen is unrelated. I'll update the thread with my findings.

**Comment by cyqasim** [comment]
+1
