### ISSUE TITLE
iOS app using a different language than primary language on the phone

### ISSUE THREAD

**Issue by varungupta85** [facebook/react-native#31368]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
I am having a very strange issue in my iOS app. I recently converted my app to use a mono-repo structure using yarn-workspaces and also upgrade to react-native 0.64.0. After performing these steps, iOS is either picking up a secondary language or Spanish as the language due to which all the native strings are in those languages. I have also posted this on stackoverflow here https://stackoverflow.com/questions/67114740/ios-app-picks-up-secondary-language-or-spanish-as-the-main-language-even-though

I am reposting the screenshots here:

Below it is showing the months in Hindi language which the second preferred language on the phone shown in the next screenshot
![IMG_0028](https://user-images.githubusercontent.com/7475133/114937621-a73df480-9e5b-11eb-92d8-5ccc3051fbf7.PNG)

![IMG_0029](https://user-images.githubusercontent.com/7475133/114937698-bde44b80-9e5b-11eb-8cf1-9b1690b7a3ce.PNG)

After I removed Hindi from the languages and have only English as the language on the phone, the months are appearing in Spanish. The same is true for other alerts shown native by the OS such as permission alerts etc.

![IMG_0031](https://user-images.githubusercontent.com/7475133/114937795-e704dc00-9e5b-11eb-8614-eb8ee690b011.PNG)

![IMG_0030](https://user-images.githubusercontent.com/7475133/114937811-ebc99000-9e5b-11eb-967e-5d4b35d5efc8.PNG)

I wanted to share this here also as my release has been stuck due to this for almost a week and I haven't been able to find anything. My app in production using react-native 0.63.4 runs fine. I haven't found anything that could explain the problem yet.

## React Native version:
System:
    OS: macOS 11.0.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 801.23 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.10.1 - /Users/varungupta/.rvm/rubies/ruby-2.4.1/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    Android SDK:
      API Levels: 21, 23, 24, 25, 26, 27, 28, 29, 30
      Build Tools: 23.0.1, 25.0.0, 26.0.1, 26.0.2, 27.0.1, 27.0.3, 28.0.3, 29.0.2
      System Images: android-26 | Google APIs Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-S | Google APIs Intel x86 Atom_64, android-S | Google Play Intel x86 Atom_64
      Android NDK: 15.2.4203891
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.2/12B45b - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_144 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: 0.64.0 => 0.64.0
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Expected Results
The strings should appear in English which is the primary language of the phone.

**Comment by varungupta85** [comment]
Just wanted to share that the problem is not limited to the date picker. It is with any native dialogs such as the permission dialog etc.

Please let me know if you could shed any light on what may cause it.

**Comment by MPuzio15** [comment]
hi, i still have the same problem, have you solved it?

**Comment by Veshurik** [comment]
Insane help, guys, no one helped :(

**Comment by zanlucathiago** [comment]
> Insane help, guys, no one helped :(

This worked for me
https://github.com/react-native-webview/react-native-webview/issues/2061#issuecomment-2753476415
