### ISSUE TITLE
IOS app in simulator can't connect to metro bundler

### ISSUE THREAD

**Issue by ravi-poonia** [facebook/react-native#31369]
Using the new m1 mac, the app is building successfully but getting stuck on the splash screen, I can't open the Dev menu. The metro bundler is started but the bundling is never started even after the app is installed in the simulator. I have tried 3 different apps. It started working one day for one of the apps, no idea why. The other 2 apps are still stuck on the splash screen.

## React Native version:
System:
    OS: macOS 11.2
    CPU: (8) arm64 Apple M1
    Memory: 607.53 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.11.0 - ~/.nvm/versions/node/v15.11.0/bin/node
    Yarn: Not Found
    npm: 7.6.0 - ~/.nvm/versions/node/v15.11.0/bin/npm
    Watchman: 4.9.0 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.64.0 => 0.64.0
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by ravi-poonia** [comment]
It was an issue with react-native-splash-screen package. It was not working the new ios version. It's resolved now. Thx

**Comment by victoriaSh** [comment]
@ravi-poonia Thank you! You just saved me a lot of time. Had the similar issue with "expo-splash-screen".

**Comment by ravi-poonia** [comment]
@victoriaSh I decided to switch to `react-native-bootsplash`
