### ISSUE TITLE
Keyboard not showing in the TextInput when pressing back button 

### ISSUE THREAD

**Issue by DOCSPLOIT** [facebook/react-native#31374]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description

Keyboard appear first time and then if we press back button, the keyboard goes as usual but it will not shows up if i press again

![Alt Text](https://media2.giphy.com/media/dxgNih92bjfLvInwqy/giphy.gif)

## React Native version:
.
react: 17.0.1 => 17.0.1 
    react-native: 0.64.0 => 0.64.0 
## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.import TextInput from 'react-native' and use it
2.

## Expected Results
Describe what you expected to happen.

## Snack, code example, screenshot, or link to a repository:
Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by Aletagro** [comment]
I have the same problem. Android 8 and earlier

**Comment by DOCSPLOIT** [comment]
Tested in Android 7 and 9 . Both have same problem

**Comment by Aletagro** [comment]
There is a very ugly but working solution. Use onPressIn. In which to do blur first, and then focus immediately.

But of course I want something better

**Comment by DOCSPLOIT** [comment]
It works great!, but sometimes it has performance issues. Hope the next version will resolve this.

**Comment by mayconline** [comment]
same problem with react-native: 0.64.x =/

**Comment by mayconline** [comment]
still unresolved at 0.65 =/

**Comment by mayconline** [comment]
> There is a very ugly but working solution. Use onPressIn. In which to do blur first, and then focus immediately.
> 
> But of course I want something better

as a temporary solution, it works

**Comment by henrineken** [comment]
Still unresolved at 0.66.3 on android 6, 7, 8

**Comment by henrineken** [comment]
I tested 0.63.4 and it works fine on all Android versions

**Comment by sanchez-cristian** [comment]
Still unresolved at 0.68.2 on Android 11.0

**Comment by psionic12** [comment]
Still unresolved at 0.68.1, but only happens on Android 7, this can be easily reproduced in rn_tester

**Comment by rikian** [comment]
u can try this

`import { useState, useEffect, useRef } from "react";
import { Keyboard, TextInput, View } from "react-native";

export default function TextInputC(): JSX.Element {
    const [keyboardStatus, setKeyboardStatus] = useState('');
    useEffect(() => {
        const showSubscription = Keyboard.addListener('keyboardDidShow', () => setKeyboardStatus('display'));
        const hideSubscription = Keyboard.addListener('keyboardDidHide', () => setKeyboardStatus('none'));
        return () => {
            showSubscription.remove();
            hideSubscription.remove();
        };
    }, []);
    const textInputRef = useRef<TextInput>(null);
    const checkKeyboards = () => {
        if(keyboardStatus === "none") textInputRef.current?.blur()
        
        return true
    };

    return(
        <View style={{backgroundColor:"grey", borderRadius:5}}>
            <TextInput
                ref={textInputRef}
                onPressIn={checkKeyboards}
                placeholder='What do you think about this...'
                placeholderTextColor={"white"}
                multiline={true}
                style={{backgroundColor:"grey",margin:5,height:100,textAlignVertical:"top",color:"white"}}
            />
        </View>
    )
}`

**Comment by rikian** [comment]
u can try tgis

```javascript
import { useState, useEffect, useRef } from "react";
import { Keyboard, TextInput, View } from "react-native";

export default function TextInputC(): JSX.Element {
    const [keyboardStatus, setKeyboardStatus] = useState('');
    useEffect(() => {
        const showSubscription = Keyboard.addListener('keyboardDidShow', () => setKeyboardStatus('display'));
        const hideSubscription = Keyboard.addListener('keyboardDidHide', () => setKeyboardStatus('none'));
        return () => {
            showSubscription.remove();
            hideSubscription.remove();
        };
    }, []);
    const textInputRef = useRef<TextInput>(null);
    const checkKeyboards = () => {
        if(keyboardStatus === "none") textInputRef.current?.blur()
        
        return true
    };

    return(
        <View style={{backgroundColor:"grey", borderRadius:5}}>
            <TextInput
                ref={textInputRef}
                onPressIn={checkKeyboards}
                placeholder='What do you think about this...'
                placeholderTextColor={"white"}
                multiline={true}
                style={{backgroundColor:"grey",margin:5,height:100,textAlignVertical:"top",color:"white"}}
            />
        </View>
    )
}
```

**Comment by fabriziobertoglio1987** [comment]
Do you still experience this issue? 

I have four years of experience maintaining facebook/react-native and I specialize in the Text and TextInput components. I currently have 58 [facebook/react-native PRs](https://github.com/facebook/react-native/pulls?q=is%3Apr+author%3Afabriziobertoglio1987+). 

If you still experience this issue, I will prepare a patched release with the fix.

Thanks a lot

**Comment by ANTH0RNY** [comment]
## Description
Keyboard appear first time and then if we press back button, the keyboard goes as usual but it will not shows up if i press again

## Steps to reproduce
https://github.com/facebook/react-native/assets/101851338/519602a7-c213-44c8-b0a6-2a8b5266b2c2

## Code Example
```
import { View, TextInput} from "react-native";
import { useState } from "react";

export default function SearchInput() {
  const [input, setInput] = useState('')
  return (
    <View style={styles.container}>
     
      <TextInput
        value={input}
        onChangeText={(text) => setInput(text)}
        placeholder="Ask me anything..."
      />
    </View>
  )
}
```
## expected outcome
The keyboard to be displayed when the user taps on it regardless of if its the first time or not

**Comment by aysrox** [comment]
Was someone able to find the cause and fix of this problem, it would be great if you share here!!

**Comment by andreweinhorn** [comment]
Here's how I got it to work:

```
const inputRef = useRef(null); // Attach a ref to the TextInput

// Delay the focus by 50ms to allow modal to complete its render
useFocusEffect(() => {
    setTimeout(() => inputRef.current?.focus(), 50)  
})

return (
    <TextInput
       ref={inputRef} // Attach ref
       autoFocus={false}  // Set autoFocus to false 
    />
)
```

I'm not sure if this is the correct way to do it, but it seems that the modal animation in some way interferes with the keyboard showing. So delaying the TextInput focus slightly allows the keyboard to render without hindrance. 

Note:  This does not negatively impact iOS rendering in any way.

More discussion here:  [stackoverflow](https://stackoverflow.com/questions/59809296/keyboard-doesnt-show-up-on-focus-textinput-android/79232858#79232858)

**Comment by Rufai-Ahmed** [comment]
Still not fixed in 2025 latest Expo version
