### ISSUE TITLE
Fetching API using fetch and axios slow only in iOS Production - expo

### ISSUE THREAD

**Issue by nurma-larasati** [facebook/react-native#31373]
**Description**

The app is running well in development stage for both Android and iOS. When it's set to production, only the iOS app is running very slow when fetching API. It takes more than 60 seconds to get just a simple test API. I tried changing to Axios with no effect. Strangely, it works well if I open the API in in-app browser or web view.

Production server and development server is in different IP address but under the same domain name. The development is the subdomain address. Both using the same wildcard SSL. 

No error in the log either.

We are at loss whether the issue is at Front End level, Back End level, or server configuration.

**Expo Version**
SDK Version: 40 (Upgrading to 41 doesn't resolve the issue)
Platform: iOS - Production only

**Steps to Reproduce**
1. (Production) Calling API via Fetch or Axios 
2. (Production) Calling API via WebView, in-app browser, and web browser
3. (Development) Calling API via Fetch/Axios/Webview/Browser

**Results**
1. API response more than 60 seconds (slow)
2. API response less than 2 seconds (fast)
3. API response less than 2 seconds (fast)

**Attemps tried**
1. Commenting all console log
2. Upgrading to SDK 41 from SDK 40

**Trying right now**
1. Setting IPv6 to the domain address (but this can't be done ASAP, and not sure why this could be the reason)
2. Installing frisbee

Hopefully we could find some solution or direction where else to look. Thank you beforehand.

**Comment by NickNish09** [comment]
Any news on this issue?
I'm having the same problem with react native 0.64 on android

**Comment by mskarimi** [comment]
i have same problem with react native 0.66.3 on android

**Comment by Seibold** [comment]
I experience the same issue.

Axios Version [0.24.0]
OS: [Android 11]
Additional Library Versions [e.g. React 17.0.2, React Native 0.66.3]
