### ISSUE TITLE
App Crash when debug is enabled on android

### ISSUE THREAD

**Issue by dejawho** [facebook/react-native#31379]
Hi, I'm using react native 0.64, sdk version 29, I can run my app with npx react-native run-android but if I enable the debug the app start to crash with the error

`react native no source url loaded have you initialize the instance?`

on metro bundler I got this error

`Error: Unable to resolve module ./debugger-ui/debuggerWorker.aca173c4.js from C:\Users\Marco\git\myapp/.:`

My platform is Windows 10 with a Xiaomi Redmi phone, but I tested both with the android emulator and MacOS and the problem is always the same

I googled and I seems an error that was known on expo, but I'm not using expo, this is my configuration:

package.json

```
{
  "name": "youcoach2",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@eva-design/eva": "^2.1.0",
    "@fortawesome/fontawesome-free": "^5.15.3",
    "@fortawesome/fontawesome-pro": "^5.15.3",
    "@fortawesome/fontawesome-svg-core": "^1.2.35",
    "@fortawesome/free-brands-svg-icons": "^5.15.3",
    "@fortawesome/free-regular-svg-icons": "^5.15.3",
    "@fortawesome/free-solid-svg-icons": "^5.15.3",
    "@fortawesome/pro-light-svg-icons": "^5.15.3",
    "@fortawesome/pro-regular-svg-icons": "^5.15.3",
    "@fortawesome/pro-solid-svg-icons": "^5.15.3",
    "@fortawesome/react-native-fontawesome": "^0.2.6",
    "@react-native-community/async-storage": "^1.12.1",
    "@react-native-community/blur": "^3.6.0",
    "@react-native-community/datetimepicker": "^3.4.6",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/native": "^5.9.4",
    "@ui-kitten/components": "^5.0.0",
    "add": "^2.0.6",
    "axios": "^0.21.1",
    "immutable": "^4.0.0-rc.12",
    "react": "17.0.1",
    "react-native": "0.64.0",
    "react-native-calendars": "^1.1255.0",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-image-crop-picker": "^0.36.0",
    "react-native-keychain": "^7.0.0",
    "react-native-push-notification": "^7.2.3",
    "react-native-reanimated": "^2.1.0",
    "react-native-responsive-dimensions": "^3.1.1",
    "react-native-safe-area-context": "^3.2.0",
    "react-native-screens": "^3.1.1",
    "react-native-svg": "^12.1.1",
    "react-native-webview": "^11.4.0",
    "react-navigation": "^4.4.4",
    "react-navigation-backhandler": "^2.0.1",
    "react-navigation-drawer": "^2.7.0",
    "react-redux": "^7.2.3",
    "redux": "^4.0.5",
    "redux-persist": "^6.0.0",
    "xdate": "^0.8.2",
    "yarn": "^1.22.10"
  },
  "devDependencies": {
    "@babel/core": "^7.13.15",
    "@babel/runtime": "^7.13.10",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "^7.24.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.65.2",
    "react-test-renderer": "17.0.1"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

build.gradle

```
buildscript {
    ext {
        googlePlayServicesVersion = "+" // default: "+"
        firebaseMessagingVersion = "+" // default: "+"
        buildToolsVersion = "29.0.3"
        minSdkVersion = 21
        compileSdkVersion = 29
        targetSdkVersion = 29
        ndkVersion = "20.1.5948944"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:4.1.0")
        classpath('com.google.gms:google-services:4.3.3')
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        google()
        jcenter()
        maven { url 'https://www.jitpack.io' }
    }
}

```

**Comment by warrence** [comment]
Have you found any fix on this? im having the similar issue now

**Comment by dejawho** [comment]
Sadly not, I'm debugging with console log for now because everything I tried ends up with this crash

**Comment by radko93** [comment]
I think it's related to reanimated, I removed the dependency and then it works.

**Comment by radko93** [comment]
AS answered on Reanimated page: reanimated v2 does not support Chrome debugger because of TurboModules.

**Comment by sathishk2030** [comment]
any work around or fix, without removing react-native-reanimated ?

**Comment by bombillazo** [comment]
Any fix for this?

**Comment by Caundy** [comment]
@sathishk2030 @bombillazo 
As per rn-reanimated's installation docs at https://docs.swmansion.com/react-native-reanimated/docs/2.2.0/installation#installing-the-package: "Please note that Reanimated 2 doesn't support remote debugging, only Flipper can be used for debugging.", so give Flipper a go :)

**Comment by joeyfigaro** [comment]
Oy. I just removed Flipper because it was causing similar fatal errors and just wasn't worth the headache.

**Comment by Bayramito** [comment]
on     "react-native-reanimated": "^2.3.0-alpha.2" debug with chrome should be fixed please check release notes.
[https://github.com/software-mansion/react-native-reanimated/releases](url)

**Comment by AMINEDGE** [comment]
Hello I have the same problem with react-native run android and the app is blank  screen without any  errors, and when I enable debug, the app crashes and I can't launch it again unless I uninstall and install it again

react-native info:

System:
    OS: macOS 12.1
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Memory: 158.62 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.3.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.2 - /usr/local/bin/npm
    Watchman: 2021.12.27.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 23, 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 31.0.0
      System Images: android-29 | Intel x86 Atom_64, android-30 | Google Play Intel x86 Atom, android-Sv2 | Google APIs Intel x86 Atom_64
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7935034
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: ^6.3.1 => 6.3.1 
    react: 17.0.2 => 17.0.2 
    react-native: ^0.66.4 => 0.66.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by vkononov** [comment]
Upgrading `react-native-reanimated` to `2.4.1` fixed the issue for me.

**Comment by KonstantinZhukovskij** [comment]
I have react-native-reanimated 2.4.1, but I'm having the similar issue now

**Comment by guinduarte** [comment]
> Upgrading `react-native-reanimated` to `2.4.1` fixed the issue for me.

locking to `2.4.1` it's works! 

package.json
```
"react-native-reanimated": "2.4.1"
```

yarn.lock
```
react-native-reanimated@2.4.1:
  version "2.4.1"
  resolved "https://registry.yarnpkg.com/react-native-reanimated/-/react-native-reanimated-2.4.1.tgz#4e33876fba525ce60ac13ab3c81fc3a9f8b132fe"
  integrity sha512-kvf7ylGlwa5hxMQ+wpPFjQrI2c6eexf53/xRo+dvXBNefGmSYaYR5sFtD0XMMzIPQlkCB9tJ0Pu9+2WCQUY7Cg==
  dependencies:
    "@babel/plugin-transform-object-assign" "^7.10.4"
    "@types/invariant" "^2.2.35"
    invariant "^2.2.4"
    lodash.isequal "^4.5.0"
    mockdate "^3.0.2"
    react-native-screens "^3.4.0"
    string-hash-64 "^1.0.3"
```

**Comment by jafar-jabr** [comment]
this seems to be one of react native permanent issues.
