### ISSUE TITLE
Inflexible Text makes inflexible parent View "flexible"

### ISSUE THREAD

**Issue by mgmolisani** [facebook/react-native#31385]
## Description
An inflexible `View` row with an inner inflexible `Text` node results in the inflexible `View` remaining flexible. When attempting to animate a wrapping `View`, I was surprised to see `onLayout` for a completely inflexible child view was being called and returning different widths when containing a `Text` node. The `Text` node itself did not change its width or report a change in the `onLayout` callback. This behavior difference from web is easy to observe via the emulator.

## React Native version:
See snack

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Create an inflexible `View` row and insert a `Text` node with the equivalent `flex: none;` properties.
2. Wrap this inflexible `View` in another "inflexible" `View` row that will have its width changed via the width property.
3. Add an `onLayout` callback to the inner inflexible inner `View` for convenience to observe width changes in the console.
4. Change the width of the outer `View` to near 0 and much wider than the inner view, notice that `onLayout` returns varied results.

## Expected Results
If a `View` is declared as inflexible and has entirely inflexible children, its layout should not change when its parent's layout changes.

## Snack, code example, screenshot, or link to a repository:
Adjust the width setting on line 45 to observe changes in the console result. Notice on web, the value does not change and returns the intrinsic max-content size of the text. On mobile, however, it will vary as the size changes linearly in a specific range until it clamps. It should behave like the web version.

https://snack.expo.io/jEz52Flvr

The following video is my use case. I measure the inflexible `View` to get my "auto" size and apply that as padding to the `ScrollView` content as the left most chip is elevated and changes width as the `ScrollView` is scrolled. Notice at a certain point, a feedback loop occurs where the "auto" width changes which changes the padding which changes the content offset which changes the width of the parent which is subsequently affecting the children incorrectly. The ideal scenario is two separate loops where changes to the content offset change the width of the parent. And changes to "auto" width of the inner child (addition of text like "Filters (NUMBER_OF_APPLIED_FILTERS)") affect only the padding of the scroller. Since the views become disjoint for width due to flex properties, there should be no feedback.

https://user-images.githubusercontent.com/37375674/115252423-737ffa80-a0f9-11eb-81fc-43f0dc001e76.mov

Current workaround: Completely eliminate the frustration the outer container is imposing on the inflexible children by utilizing `position: absolute` and passing the single inflexible child's width and height explicitly to the parent. This results in the child being truly inflexible and utilizes the max-content sizing model always. This is only convenient here as I was already using animated views. This certainly loses value when you do not want to spend a single layout measuring children to update parent components implicitly.

**Comment by mgmolisani** [comment]
Any update on this? Still an issue.

**Comment by mgmolisani** [comment]
Almost been a full year with no update on this.

**Comment by fabriziobertoglio1987** [comment]
Do you still experience this issue? 

I have four years of experience maintaining facebook/react-native and I specialize in the Text and TextInput components. I currently have 58 [facebook/react-native PRs](https://github.com/facebook/react-native/pulls?q=is%3Apr+author%3Afabriziobertoglio1987+). 

If you still experience this issue, I will prepare a patched release with the fix.

Thanks a lot
