### ISSUE TITLE
Link to React Native Testing is broken

### ISSUE THREAD

**Issue by sangeethaKP** [facebook/react-native#31386]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
The URL for testing in React Native Readme is broken

## React Native version:
0.63.4 and all versions

## Steps To Reproduce
The link to Testing is broken [here](https://github.com/facebook/react-native/tree/master/ReactAndroid)

## Expected Results
The link to Testing should take user to https://github.com/facebook/react-native/wiki/Tests#writing-tests

**Comment by cortinico** [comment]
Closing as the linked file does not exist anymore
