### ISSUE TITLE
The following build commands failed: 	CompileC /Users/agungs1709/Library/Developer/Xcode/DerivedData/hadirkoe2-cglqvmppzcgxnecipjvwlwxuhkuu/Build/Intermediates.noindex/Pods.build/Release-iphonesimulator/RCT-Folly.build/Objects-normal/i386/Rcu.o /Users/agungs1709/Documents/Projects/new/hadirkoe.react.native/ios/Pods/RCT-Folly/folly/synchronization/Rcu.cpp normal i386 c++ com.apple.compilers.llvm.clang.1_0.compiler (1 failure)

### ISSUE THREAD

**Issue by agungs17** [facebook/react-native#31388]
I'm a newbie in rn, I tried to build a release on the IOS platform using the react-native run-ios --configuration Release command and found an error like that (The following build commands failed: CompileC /Users/agungs1709/Library/Developer/Xcode/DerivedData/hadirkoe2-cglqvmppzcgxnecipjvwlwxuhkuu/Build/Intermediates.noindex/Pods.build/Release-iphonesimulator/RCT-Folly.build/Objects-normal/i386/Rcu.o /Users/agungs1709/Documents/Projects/new/hadirkoe.react.native/ios/Pods/RCT-Folly/folly/synchronization/Rcu.cpp normal i386 c++ com.apple.compilers.llvm.clang.1_0.compiler (1 failure)) but if I try to build it in xcode it doesn't show up. What is wrong?

my podfile : 

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'
inhibit_all_warnings!

target 'hadirkoe2' do
  config = use_native_modules!

  use_react_native!(
	:path => config["reactNativePath"],
	:hermes_enabled => true
  )

  target 'hadirkoe2Tests' do
    inherit! :complete
  end

  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'hadirkoe2-tvOS' do

  target 'hadirkoe2-tvOSTests' do
    inherit! :search_paths
  end
end

I tried to remove flipper from pod but the error still appears.
I'm using React Native version 0.64.

**Comment by wy10** [comment]
请问你这个问题解决了吗

**Comment by cortinico** [comment]
Closed as invalid (not following the issue template)
