### ISSUE TITLE
iOS  hermes_enable = true, ipa size increases a lot

### ISSUE THREAD

**Issue by CoderYLZhang** [facebook/react-native#31390]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
HermeEnable = true, ipa size increases a lot = true, ipa size increases a lot
![image](https://user-images.githubusercontent.com/13221319/115347126-9b4b8d00-a1e3-11eb-8adf-6275d3a7b828.png)

Check out the IPA content to see that the increase in size comes mainly from hermes
![image](https://user-images.githubusercontent.com/13221319/115347706-5116db80-a1e4-11eb-8465-36f4f9337b5a.png)

hermes macho:
![image](https://user-images.githubusercontent.com/13221319/115347479-05fcc880-a1e4-11eb-9c87-8f032d7aa88c.png)

## React Native version:
System:
    OS: macOS 11.2.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 1.22 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.12.0 - /usr/local/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.10.1 - /Users/zhangyinlong/.rvm/rubies/ruby-3.0.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.0 => 0.64.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.
2.

## Expected Results
Will it be optimized in the future 
Or what I can do for it

**Comment by CoderYLZhang** [comment]
> Please provide all the information requested. Issues that do not follow this format are likely to stall.
> 
> ## Description
> HermeEnable = true, ipa size increases a lot = true, ipa size increases a lot
> ![image](https://user-images.githubusercontent.com/13221319/115347126-9b4b8d00-a1e3-11eb-8adf-6275d3a7b828.png)
> 
> Check out the IPA content to see that the increase in size comes mainly from hermes
> ![image](https://user-images.githubusercontent.com/13221319/115347706-5116db80-a1e4-11eb-8465-36f4f9337b5a.png)
> 
> hermes macho:
> ![image](https://user-images.githubusercontent.com/13221319/115347479-05fcc880-a1e4-11eb-9c87-8f032d7aa88c.png)
> 
> ## React Native version:
> System:
> OS: macOS 11.2.3
> CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
> Memory: 1.22 GB / 16.00 GB
> Shell: 5.8 - /bin/zsh
> Binaries:
> Node: 12.12.0 - /usr/local/bin/node
> Yarn: 1.22.5 - ~/.yarn/bin/yarn
> npm: 6.11.3 - /usr/local/bin/npm
> Watchman: Not Found
> Managers:
> CocoaPods: 1.10.1 - /Users/zhangyinlong/.rvm/rubies/ruby-3.0.0/bin/pod
> SDKs:
> iOS SDK:
> Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
> Android SDK: Not Found
> IDEs:
> Android Studio: Not Found
> Xcode: 12.4/12D4e - /usr/bin/xcodebuild
> Languages:
> Java: Not Found
> npmPackages:
> @react-native-community/cli: Not Found
> react: 17.0.1 => 17.0.1
> react-native: 0.64.0 => 0.64.0
> react-native-macos: Not Found
> npmGlobalPackages:
> _react-native_: Not Found
> 
> ## Steps To Reproduce
> Provide a detailed list of steps that reproduce the issue.
> 
> 
> ## Expected Results
> Will it be optimized in the future
> Or what I can do for it
> 
> ## Snack, code example, screenshot, or link to a repository:

**Comment by surethink** [comment]
same issue, react native 0.64. 
when hermes_enabled => false, the number of tasks built with xcode is about 1800, the size in my iphone storage is  124.6M ,
when set true, the number of built tasks is about 3200, the size is 567.5M

**Comment by nadimahamad** [comment]
Following solution for hermes enabled and RN 0.64.2.
1.Need to do bitcode enabled - Yes at Build setting tab in xcode.
2.Need to choose deployment target version above ios 13.1
Then once do clean & build and then archive. your .ipa file size will be reduce.
