### ISSUE TITLE
KeyboardAvoidingView does not work well with ScrollView's keyboardDismissMode set to interactive

### ISSUE THREAD

**Issue by bjornlll** [facebook/react-native#31394]
![Screencast](https://s3.gifyu.com/images/2021-04-21-07.04.55.gif)

**Components used**: 
- `ScrollView` with `keyboardDismissMode` set to `interactive`
- `InputAccessoryView` for the sticky toolbar on top of the keyboard
- `KeyboardAvoidingView` wrapped around the `ScrollView`, behavior set to `position`

**Expected**: As I scroll to gradually dismiss the keyboard, the `KeyboardAvoidingView` gradually adjusts the position of `ScrollView`. See WhatsApp or Telegram for proper implementation of what I'm trying to achieve. 

**What really happens**: `KeyboardAvoidingView` does not gradually update the position of `ScrollView`. Instead, you get one position when we've half-dismissed the keyboard resulting in a rather unsmooth user experience.

This issue has previously been covered #13073 but the issue was closed since, for the author's purpose, his problem had been solved. The root cause - this - however, is not solved.

**Telegram's implementation** (what I want to achieve)
[![2021-04-21-14.23.12.gif](https://s3.gifyu.com/images/2021-04-21-14.23.12.gif)](https://gifyu.com/image/tWOK)

**Comment by bjornlll** [comment]
It seems, if I understand this correctly, that the reason it's difficult to build a `KeyboardAvoidingView` that reacts to changes in height of the keyboard's position is that the events triggered by `Keyboard` do not provide granular enough feedback ([see here](https://rn.wlfcss.com/react-native/blog/2018/03/22/building-input-accessory-view-for-react-native.html#pitfalls:~:text=An%20initial%20idea%20for%20building%20this,of%20bugs%20that%20manifest%20like%20this%3A)).

**Comment by mrousavy** [comment]
see https://github.com/facebook/react-native/pull/31402

**Comment by bjornlll** [comment]
> see #31402

That's amazing @mrousavy! Thanks. I'll put that to use straight away.

**Comment by johnpawl** [comment]
I want to get back to android activity from react-native activity using backkey .


**MainActivity.java**


    public class MainActivity extends AppCompatActivity {

    Button button;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        button = (Button) findViewById(R.id.button);
        button.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                startRNPage();
            }
        });
    }

    private void startRNPage() {
        Intent intent = new Intent(this, ReactNativeActivity.class);
        startActivity(intent);
        finish();
    }
    }

**ReactNativeActivity.java**



    public class ReactNativeActivity extends AppCompatActivity {
    private ReactRootView mReactRootView;
    private ReactInstanceManager mReactInstanceManager;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        SoLoader.init(this, false);

        mReactRootView = new ReactRootView(this);
        List<ReactPackage> packages = new PackageList(getApplication()).getPackages();
        // Packages that cannot be autolinked yet can be added manually here, for example:
        // packages.add(new MyReactNativePackage());
        // Remember to include them in `settings.gradle` and `app/build.gradle` too.

        

        mReactInstanceManager = ReactInstanceManager.builder()
        .setApplication(getApplication())
        .setCurrentActivity(this)
        .setBundleAssetName("index.android.bundle")
        .setJSMainModulePath("index")
        .addPackages(packages)
        .setUseDeveloperSupport(BuildConfig.DEBUG)
        .setInitialLifecycleState(LifecycleState.RESUMED)
        .build();
        // The string here (e.g. "MyReactNativeApp") has to match
        // the string in AppRegistry.registerComponent() in index.js
        mReactRootView.startReactApplication(mReactInstanceManager, "firstpro", null);

        setContentView(mReactRootView);
        }
    @Override
    public void onBackPressed() {
        if (mReactInstanceManager != null) {
            mReactInstanceManager.onBackPressed();
        } else {
          super.onBackPressed();
        }
    }
    }


I also tried the following code in ReactNativeActivity.java

    public void onBackPressed() {
        if (mReactInstanceManager != null) {
            mReactInstanceManager.onBackPressed();
        } else {
            Intent intent = new Intent(this, MainActivity.class);
            startActivity(intent);
        }
    }



If I pressed the back button it didn't get back to android activity.

How can I get back to android activity from react-native activity using backkey?
