### ISSUE TITLE
Unhandled JS Exception: Requiring unknown module "1". If you are sure the module exists, try restarting Metro. You may also want to run `yarn` or `npm install`.

### ISSUE THREAD

**Issue by beqramo** [facebook/react-native#31407]
## Description
Hi I'm using react-native 0.64 version and there is a problem with metro bundler, it appears that when I add a file in the project and import it and sometimes when I remove or add a hook. 

![image](https://user-images.githubusercontent.com/40486471/115688943-a978e500-a36c-11eb-84d2-4de5a4b131db.png)

## React Native version:
```
  OS: macOS 11.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 169.38 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.10.1 - /usr/local/bin/node
    Yarn: 1.22.10 - ~/Projects/mobile/GeraldWallet/node_modules/.bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 23, 25, 27, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.1
      System Images: android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_265 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.0 => 0.64.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

```
## Steps To Reproduce
init project and try to add files and import it in the project and it will create this error. 

## Expected Results
should rerender without an error

**Comment by swrobel** [comment]
This happens all of the time when doing local development in the simulator when I introduce errors into my code. Instead of reloading, sometimes it just seems to break the connection with Metro and require me to restart it. Supremely annoying.

React Native 0.66.0-rc.4
Hermes enabled

**Comment by swrobel** [comment]
Still an issue on 0.66.4

**Comment by alexfov** [comment]
I ran into this issue after enabling hermes on IOS. Its annoying to clear cache all the time.
