### ISSUE TITLE
[TexInput][Android]: Not exposing the entered text value to assistive technologies 

### ISSUE THREAD

**Issue by IshaTyagi** [facebook/react-native#31405]
## Description: TexInput(in Android) is not exposing the entered text value to assistive technologies.

https://accessibilityinsights.io/info-examples/android/edit-text-value/

## React Native version:
React-native : 0.63.3

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.
1. Install Accessibility Insights for Android 
2. Use the tool to verify

## Expected Results
It should expose the entered text value to assistive technologies 
##Screenshot

![image](https://user-images.githubusercontent.com/30119136/115681987-ab45a700-a372-11eb-9054-223910a43ee2.png)

![image](https://user-images.githubusercontent.com/30119136/115682027-b39de200-a372-11eb-9126-a7effd6fee3a.png)

## Snack, code example, screenshot, or link to a repository:
![image](https://user-images.githubusercontent.com/30119136/115682373-08d9f380-a373-11eb-9481-5e18f38bdc06.png)

**Comment by fabriziobertoglio1987** [comment]
Do you still experience this issue? 

I have four years of experience maintaining facebook/react-native and I specialize in the Text and TextInput components. I currently have 58 [facebook/react-native PRs](https://github.com/facebook/react-native/pulls?q=is%3Apr+author%3Afabriziobertoglio1987+). 

If you still experience this issue, I will prepare a patched release with the fix.

Thanks a lot
