### ISSUE TITLE
TouchableOpacity not calling onPress

### ISSUE THREAD

**Issue by CDBridger** [facebook/react-native#31403]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
I have a touchable opacity which onPress triggers an animation. Currently the onPress function gets called SPORADICALLY time BUT I can see the opacity of the touchable opacity changing EVERY time.

Running this on the iPad Air simulator

## React Native version:
System:
    OS: macOS 11.2.3
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 196.27 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.8.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.5.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.3
      System Images: android-28 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_252 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Expected Results
Every time the button is pressed the function gets triggered. 

### The Function
``` 
const toggleMenuHelp = (currentState: boolean) => () => {
        console.log('Toggling menu, from state hidden: ', currentState);
        setHelpMenuHidden((x) => !x);
        if (currentState) {
            return new Promise<boolean>((resolve) => {
                Animated.parallel([
                    Animated.timing(menuHelpTextWidth, { toValue: 1, useNativeDriver: false }),
                    Animated.sequence([
                        Animated.delay(200),
                        Animated.timing(menuHelpTextOpacity, { toValue: 1, useNativeDriver: true })
                    ])
                ]).start(() => resolve(true));
            });
        } else {
            return new Promise<boolean>((resolve) => {
                Animated.parallel([
                    Animated.timing(menuHelpTextOpacity, { toValue: 0, useNativeDriver: true }),
                    Animated.sequence([
                        Animated.delay(200),
                        Animated.timing(menuHelpTextWidth, { toValue: 0, useNativeDriver: false })
                    ])
                ]).start(() => resolve(true));
            });
        }
    };
```

I tried different things, initially the function was a use callback, with the parameter passed as a dependency instead. Neither that or the current way of currying the function seemed to work.
    
### The Button
```
<AnimatedButton
        iconName="Help"
        disabled={hideMenu}
        onPress={toggleMenuHelp(helpMenuHidden)}
        scale={menuHelpScale}
        buttonStyle={{
            ...styles.SubMenuButton,
            backgroundColor: Colours.Purple,
            position: 'absolute',
            right: 0
        }}
        iconStyle={styles.MenuIcon}
/>
```

```
import React from 'react';
import { Animated, TouchableOpacity, ViewStyle } from 'react-native';

import { STANDARD_ICON_SIZE, Styles } from '@COMPANY_NAME_REDACTED/ui-native';

import { CustomIcon, IconName } from './custom-icon';

type Props = {
    disabled: boolean;
    scale: Animated.Value;
    iconName: IconName;
    onPress: any;
    buttonStyle?: ViewStyle;
    iconStyle?: any;
};

export const AnimatedButton: React.FC<Props> = ({
    scale,
    iconName,
    buttonStyle,
    iconStyle,
    disabled,
    onPress
}: Props) => {
    return (
        <TouchableOpacity disabled={disabled} onPress={onPress}>
            <Animated.View
                style={{
                    ...Styles.CircularButton,
                    ...buttonStyle,
                    transform: [{ scale: scale }]
                }}>
                <CustomIcon name={iconName} size={STANDARD_ICON_SIZE} color="white" style={iconStyle} />
            </Animated.View>
        </TouchableOpacity>
    );
};
```

## The Result

[Mega Link To Recording (.mov file)](https://mega.nz/file/KwsknRAC#oyH8TF_S3uTlGLA1qpDgNNUYIAI3vvFpaTeWC4kGs2I)

I can also see that the console logs aren't running indicating its not just the animations not running.

**Comment by aneeskhan47** [comment]
from RN docs:

If you're looking for a more extensive and future-proof way to handle touch-based input, check out the [Pressable ](https://reactnative.dev/docs/pressable)API.

**Comment by CDBridger** [comment]
Thanks but that doesn't really have anything to do with my problem. I still want the visual look of the touchable opacity
