### ISSUE TITLE
Pod Install error, if the project is in a directory with spaces.

### ISSUE THREAD

**Issue by ignitebhdeveloper** [facebook/react-native#31409]
## Description
Need to escape strings if the project is in a folder name with spaces.

## React Native version:
`System:
    OS: macOS 11.2.3
    CPU: (6) x64 Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz
    Memory: 104.42 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.14.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.7.6 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3
      System Images: android-24 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7199119
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_282 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found`

## Steps To Reproduce
1 - create/use a folder with the name "Some Folder (Name)".
2 - initiate or install the project into that directory.

`Installing FBReactNativeSpec 0.64.0
[!] /bin/bash -c 
set -e
mkdir -p /Users/ig-16/Dropbox (ig)/development/www/TestApp/node_modules/react-native/scripts/../React/FBReactNativeSpec/FBReactNativeSpec && touch /Users/ig-16/Dropbox (ig)/development/www/TestApp/node_modules/react-native/scripts/../React/FBReactNativeSpec/FBReactNativeSpec/FBReactNativeSpec.h /Users/ig-16/Dropbox (ig)/development/www/TestApp/node_modules/react-native/scripts/../React/FBReactNativeSpec/FBReactNativeSpec/FBReactNativeSpec-generated.mm

/bin/bash: -c: line 2: syntax error near unexpected token ('`

**Comment by MoronovArt** [comment]
same issue

**Comment by ShahidIqbal452** [comment]
Same issue. Any solution to this except removing spaces from folder names because it will have consequences for other projects.

**Comment by prodev-alt** [comment]
Any update?

**Comment by JaapWeijland** [comment]
Same!

**Comment by Douglasgomes027** [comment]
Same!

**Comment by NiteshBehal** [comment]
Facing same issue.. Please suggest some solution.

**Comment by joseub71** [comment]
I found a solution for me, so I was investigating the error occurs for the 0.64 version of react native that causes an error with the directory you need cocoapods to do its work, I spent two days trying to solve it I hope it works for you too

this is bash, https://github.com/facebook/react-native/issues/31193#issuecomment-802714508

`OS=`uname`

echo "Fixing RN 0.64.0 bugs:"
cd node_modules/react-native/scripts
echo "- unset PREFIX in find-node.sh"
if [ `cat find-node.sh | grep 'unset PREFIX' | wc -l` -lt 1 ]
then
  cp find-node.sh tmp
  head -n 1 tmp >find-node.sh
  echo "unset PREFIX" >>find-node.sh
  tail -n +2 tmp >>find-node.sh
  rm tmp
fi

if [ "$OS" = 'Darwin' ]
then
  # for MacOS; cannot install Pods on Win/Linux
  echo "- switch to relative paths in react_native_pods.rb "
  sed -i '' -e "s/File[.]join[(]__dir__, \"[.][.]\"[)]/\"..\/..\/node_modules\/react-native\"/" react_native_pods.rb
  sed -i '' -e "s/#{File[.]join[(]__dir__, \"generate-specs.sh\"[)]}/..\/..\/node_modules\/react-native\/scripts\/generate-specs.sh/" react_native_pods.rb
  sed -i '' -e "s/spec[.]prepare_command = \"#/spec.prepare_command = \"cd ..\/.. \&\& #/" react_native_pods.rb
fi

cd - >/dev/null`
