### ISSUE TITLE
[XMLHttpRequest] RCTHTTPRequest  result in crash  on  iphone6( iOS9.0.1)  react-native 0.11.0

### ISSUE THREAD

**Issue by fsp1990** [facebook/react-native#3141]
Below is the stack info:

libobjc.A.dylib	0x000000019873dbd0	objc_msgSend (hash) + 16
1	Foundation	0x00000001849a9148	-[NSConcreteMapTable rehashAround:] + 480
2	batiaoyuappios	0x00000001002b23d8	-[RCTHTTPRequestHandler URLSession:task:didCompleteWithError:] (RCTHTTPRequestHandler.m:107)
3	CFNetwork	0x00000001833631e8	___51-[NSURLSession delegate_task:didCompleteWithError:]_block_invoke170 + 72
4	Foundation	0x0000000184a5b82c	___NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 16
5	Foundation	0x00000001849ae6c0	-[NSBlockOperation main] + 96
6	Foundation	0x000000018499e918	-[__NSOperationInternal _start:] + 604
7	Foundation	0x0000000184a5dc20	___NSOQSchedule_f + 224
8	libdispatch.dylib	0x0000000198f25770	__dispatch_client_callout + 16
9	libdispatch.dylib	0x0000000198f3175c	__dispatch_queue_drain + 864
10	libdispatch.dylib	0x0000000198f29274	__dispatch_queue_invoke + 464
11	libdispatch.dylib	0x0000000198f3362c	__dispatch_root_queue_drain + 728
12	libdispatch.dylib	0x0000000198f3334c	__dispatch_worker_thread3 + 112
13	libsystem_pthread.dylib	0x0000000199139478	_pthread_wqthread + 1084

**Comment by brentvatne** [comment]
@fsp1990 - can you post the code that caused this?

**Comment by mschwartz** [comment]
I can confirm this.

After upgrading to El Capitan and Xcode 7.0.1, the iOS9 simulators crash if the nsUrl is not localhost:8081.

The request for index.ios.js never reaches the development server.

See the bolded text in the stack trace above!

**Comment by mschwartz** [comment]
So what does work is to download the 8.4 simulators in Xcode settings -> downloads and use those.

**Comment by mschwartz** [comment]
nsUrl of my server IP works on my iOS 9 iPhone.

**Comment by PhilippKrone** [comment]
Is this the same as my issue? https://github.com/facebook/react-native/issues/3174

**Comment by Crash--** [comment]
1/Do you call an IPv4 address or a domain name? 
2/Are you using El Capitan?

**Comment by mschwartz** [comment]
El Capitain

http://192.168.0.14:8081

**Comment by Crash--** [comment]
It's the same issue than #3174. I found [this](http://stackoverflow.com/questions/32732924/nsurlsession-fails-when-attempting-to-us-assigned-ip-instead-of-localhost-or-hom) but didn't find any solution to bypass.

**Comment by satya164** [comment]
You guys still facing the issue?

**Comment by satya164** [comment]
Closing since no response. Let's re-open if you're still having the issue.

**Comment by karkb** [comment]
Hi guys, this issue still exist on iOS9.0.
RN: 0.33
Xcode: 8.0
El Capitan: 10.11.6
