### ISSUE TITLE
Could not find generated setter for class com.facebook.react.views....

### ISSUE THREAD

**Issue by shivam-S-bisht** [facebook/react-native#31416]
## React Native version:
react-native: 0.64.0 => 0.64.0

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. success in building debug apk.
2. success in building release apk.
3. release apk is not showing screens/tab screens/home screen after a custom splash screen.
4. The whole app is working fine in debug.apk but not in release.

## Expected Results
I am expecting that relase apk must work fine like as debug apk.

## Screen show of the error in adb logcat:
![image](https://user-images.githubusercontent.com/47574164/115878264-fa203900-a465-11eb-909a-3b642b41bcd2.png)

## dependencies:
![image](https://user-images.githubusercontent.com/47574164/115878758-8c284180-a466-11eb-95ff-7f9efce73ac2.png)

**Comment by joeyfigaro** [comment]
@shivam-S-bisht what happened here? did you fix the issue?

**Comment by shivam-S-bisht** [comment]
yes, actually the api calls must be done with secure servers like https i.e. with secure shell encryption. 

And in production mode react native or we can say android restrict any non secure api calls i.e. http. 

android give the liberty to make any api calls in debug apk but in release apk api calls must follow http protocol over secure shell (i.e. https). 

So i just did the ssl on api calls over remote servers, which resolved my issue.

**Comment by shivam-S-bisht** [comment]
in my case i have problem with api calls and making secure calls make the app run just fine.
