### ISSUE TITLE
Build failed after update Xcode 12.5 beta Cannot initialize a parameter of type 'NSArray<id<RCTBridgeModule>> *' with an rvalue of type 'NSArray<Class> *'

### ISSUE THREAD

**Issue by artyom-developer** [facebook/react-native#31412]
## Description

i updated xcode 11.* to xcode 12.5 beta and after update i build app iOS but report error ==> _**Cannot initialize a parameter of type 'NSArray<id<RCTBridgeModule>> *' with an rvalue of type 'NSArray<Class> *'**_

i think it's is fix the issue and try but not fixed
https://github.com/facebook/react-native/issues/28405#issuecomment-779382959

## Environment

System:
    OS: macOS 11.2.3
    CPU: (4) x64 Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
    Memory: 293.65 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.18.2 - /usr/local/bin/node
    npm: 6.14.5 - /usr/local/bin/npm
    Watchman: 4.7.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1

**Comment by ltankey** [comment]
I had the same issue with an older RN (`0.60.3`) tha was previously building fine, before XCode upgraded to 12.5

I added the post-install [here](https://github.com/facebook/react-native/issues/28405#issuecomment-779382959) and am surprised to say it works fine now.

Was your issue coming from the `React-core` library at build?

**Comment by artyom-developer** [comment]
> I had the same issue with an older RN (`0.60.3`) tha was previously building fine, before XCode upgraded to 12.5
> 
> I added the post-install [here](https://github.com/facebook/react-native/issues/28405#issuecomment-779382959) and am surprised to say it works fine now.
> 
> Was your issue coming from the `React-core` library at build?

https://github.com/facebook/react-native/issues/28405#issuecomment-827424477

**Comment by infinitbility** [comment]
Check the below article to solve the build update issue in code 12.5

https://infinitbility.com/build-failed-after-update-xcode-12.5

**Comment by ajith-ab** [comment]
This isssue is resolved when you update react native version but if you want to solve on your current version then you have add below code on your Podfile.

```
post_install do |installer|
    ## Fix for XCode 12.5
    find_and_replace("../node_modules/react-native/React/CxxBridge/RCTCxxBridge.mm",
    "_initializeModules:(NSArray<id<RCTBridgeModule>> *)modules", "_initializeModules:(NSArray<Class> *)modules")
    find_and_replace("../node_modules/react-native/ReactCommon/turbomodule/core/platform/ios/RCTTurboModuleManager.mm",
        "RCTBridgeModuleNameForClass(module))", "RCTBridgeModuleNameForClass(Class(module)))")
end
```

Add below code on your end of Podfile

```
def find_and_replace(dir, findstr, replacestr)
  Dir[dir].each do |name|
      text = File.read(name)
      replace = text.gsub(findstr,replacestr)
      if text != replace
          puts "Fix: " + name
          File.open(name, "w") { |file| file.puts replace }
          STDOUT.flush
      end
  end
  Dir[dir + '*/'].each(&method(:find_and_replace))
end
```

**Comment by hermann-etech** [comment]
if you don't want to upgrade, just replace

`- (NSArray<RCTModuleData *> *)_initializeModules:(NSArray<id<RCTBridgeModule>> *)modules`

with :

`- (NSArray<RCTModuleData *> *)_initializeModules:(NSArray<id> *)modules`

in file named **RCTCxxBridge.mm** at line 770

**Comment by russmenum** [comment]
This is all back again in XCODE 13.2.1; is there a fix for XCODE 13?
