### ISSUE TITLE
Build Release TypeScript Project -> `\index.js` was not found

### ISSUE THREAD

**Issue by AliRezaBeigy** [facebook/react-native#31421]
## Description
When i try to assemble release react native 0.64 project with enable Hermes, build failed with the following error

```shell
> Task :app:bundleReleaseJsAndAssets
warning: the transform cache was reset.
error The resource `C:\XXXX\YYYYMobileApplication\index.js` was not found.
Error: The resource `C:\XXXX\YYYYMobileApplication\index.js` was not found.
    at C:\XXXX\YYYYMobileApplication\node_modules\metro\src\IncrementalBundler.js:457:26
    at gotStat (fs.js:1864:21)
    at callback (C:\XXXX\YYYYMobileApplication\node_modules\graceful-fs\polyfills.js:299:20)
    at FSReqCallback.oncomplete (fs.js:183:21)
info Run CLI with --verbose flag for more details.

> Task :app:bundleReleaseJsAndAssets FAILED

FAILURE: Build failed with an exception.
```

I don't have index.js, we develop project with typescript, i think it should looking for index.tsx 
## React Native version:
```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Memory: 3.03 GB / 15.81 GB
  Binaries:
    Node: 14.15.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.9 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      Versions: 10.0.18362.0
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7199119
    Visual Studio: 16.8.30717.126 (Visual Studio Enterprise 2019)
  Languages:
    Java: 1.8.0_212 - /c/Program Files/Java/jdk1.8.0_212/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.64.0 => 0.64.0
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by Agupane** [comment]
I'm having the same issue with typescript and ios. I'm trying to make the build and I'm getting the same error:

Seems that the error is on the build from the CLI is using `index.js` instead of `index.ts`
```
node /***/node_modules/react-native/cli.js bundle --entry-file index.js --platform ios --dev true --reset-cache --bundle-output /***/Library/Developer/Xcode/DerivedData/***/Build/Products/Debug-iphoneos/main.jsbundle --assets-dest /**/Library/Developer/Xcode/DerivedData/***/Build/Products/Debug-iphoneos/***.app
```

**Comment by FedeMadoery** [comment]
A quick way to solve it, could be:

* IOs Build:

    Go to -> `node_modules/react-native/scripts/react-native-xcode.sh:74`
    And change _index.js_ to _index.tsx_

* Android Build:

   Go to -> `/node_modules/react-native/react.gradle:21`
   And change _index.js_ to _index.tsx_

**Comment by vickz84259** [comment]
I encountered this while building for iOS via CI, and going through the `node_modules/react-native/scripts/react-native-xcode.sh` I realised that you can override the entry file by setting the environment variable: `ENTRY_FILE`.

So, having the environment variable: `ENTRY_FILE=index.tsx` set fixed it for me.

**Comment by yangm97** [comment]
I wonder if this (`$ENTRY_FILE`) could become a config option...

**Comment by pstanton** [comment]
I've got 2 projects in different directories but with the same name. This is because I've been having a complete %-$* of a time upgrading to XCode 13 + rn 0.65 and have had to re-build my project from scratch instead due to all of the ridiculous issues.

Long story short, I think I'm almost there but because I have 2x xcode projects named `proj` with the same name, for some STUPID reason when I run my newer version which is in ~/proj2 it finds the index.js in ~/proj. I've stepped through `react-native-xcode.sh` and it passes "index.js" to the node command and at that point the working directory is correct (`proj2`) however I can edit/remove ~/proj/index.js and it causes errors in my execution.

I've even deleted Xcode/DerivedData and not opened `proj/ios/proj` since.

How can force react / xcode to use the correct project?

**Comment by tezqa** [comment]
A clean workaround is to update the "Bundle React Native code and images" build phase in Xcode to include the correct index filename:

```
export NODE_BINARY=node
../node_modules/react-native/scripts/react-native-xcode.sh index.tsx
```

**Comment by meth0xy** [comment]
> A clean workaround is to update the "Bundle React Native code and images" build phase in Xcode to include the correct index filename:
> 
> ```
> export NODE_BINARY=node
> ../node_modules/react-native/scripts/react-native-xcode.sh index.tsx
> ```

This one worked for me thanks!

**Comment by pengcy** [comment]
Adding this to the /android/app/build.gradle resolved the issue for me for Android build
```
project.ext.react = [
    entryFile: "index.js"
]
```

**Comment by namnh240795** [comment]
> Adding this to the /android/app/build.gradle resolved the issue for me for Android build
> 
> ```
> project.ext.react = [
>     entryFile: "index.js"
> ]
> ```

i think this issue should be close with this hint, we need to put in the right path for the entry file.

**Comment by liltrendi** [comment]
Renaming my entry file (``index.tsx``) to ``index.js`` (and removing the now defunct TypeScript code within the file, fixed it for me.

**Comment by ghorbani-m** [comment]
> A clean workaround is to update the "Bundle React Native code and images" build phase in Xcode to include the correct index filename:
> 
> ```
> export NODE_BINARY=node
> ../node_modules/react-native/scripts/react-native-xcode.sh index.tsx
> ```

Thanks, It solved my issue.

**Comment by nangbanmai1907** [comment]
> Adding this to the /android/app/build.gradle resolved the issue for me for Android build
> 
> ```
> project.ext.react = [
>     entryFile: "index.js"
> ]
> ```

It's work for me
project.ext.react = [
    entryFile: "index.tsx"
]
