### ISSUE TITLE
Flatlist scroll gets slow after going back from other screen

### ISSUE THREAD

**Issue by bvmy** [facebook/react-native#31433]
Flatlist scroll gets slow after going back from other screen. 
After I went to the right buttom tab screen which just got data from state managed by redux, the home screen couldn't scroll as before. 
Any ideas? Thanks in advance.
![ezgif com-gif-maker(1)](https://user-images.githubusercontent.com/50758994/116041930-6a1a0380-a6a0-11eb-9ba7-9bce7255d251.gif)

**Comment by cortinico** [comment]
Closed as invalid (not following the issue template)
