### ISSUE TITLE
TextInput's onKeyPress and onChangeText order of execution is inconsistent across platforms - iOS and Android

### ISSUE THREAD

**Issue by yuliankarapetkov** [facebook/react-native#31436]
## Description
`onKeyPress` is being called before `onChangeText` on iOS and after it on Android.

## React Native version:
0.63 (Expo SDK 41) - [see Snack](https://snack.expo.io/Saui0uYTL)

## Expected Results
Order of execution should be the same across platforms, e.g. `onKeyPress` should always occur first, regardless of the OS.

## Snack, code example, screenshot, or link to a repository:
[Snack example](https://snack.expo.io/Saui0uYTL)

![image](https://user-images.githubusercontent.com/6671521/116096131-b15cc000-a6b1-11eb-940c-4fea55c0a59c.png)

**Comment by bychung** [comment]
Same issue here.

**Comment by ngasull** [comment]
Still an issue in react-native 0.64.3 with expo 43.

This really surprises me because it makes many editing behaviors basically impossible with react native like having a multiline input with custom behavior when pressing return.

Does anybody have more insight or a real workaround for this?

**Comment by jbrowning** [comment]
Still an issue on react-native 0.67.3

**Comment by landabaso** [comment]
Still an issue on react-native 0.69.

As a workaround you can defer the call for the next execution thread:
```javascript
<TextInput>
    onChangeText={text => {
      setTimeout(() => onChangeText(text), 0);
    }}
</TextInput>
````

**Comment by longb1997** [comment]
> Do you still experience this issue?
> 
> I have four years of experience maintaining facebook/react-native and I specialize in the Text and TextInput components. I currently have 58 [facebook/react-native PRs](https://github.com/facebook/react-native/pulls?q=is%3Apr+author%3Afabriziobertoglio1987+).
> 
> If you still experience this issue, I will prepare a patched release with the fix.
> 
> Thanks a lot

i still see it, please update a patch
Thank you
