### ISSUE TITLE
Apple rejects React Native build with "ITMS-90338: Non-public API usage"

### ISSUE THREAD

**Issue by itsmistad** [facebook/react-native#31437]
## Description
Submitting a React Native app build to the Apple App Store results in a rejection email regarding "Non-public API usage".

## React Native version:
```
System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 194.50 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.16.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.11 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 24, 25, 26, 27, 28, 29, 30
      Build Tools: 29.0.3, 30.0.3
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_275 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.0 => 0.64.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
1. Follow the setup instructions for a new templatized app [here](https://reactnative.dev/docs/environment-setup) for macOS -> iOS.
2. Execute the following commands in the root of the project, replacing `<APP>` with the name of the test app:
```
xcodebuild clean -workspace <APP>.xcworkspace -scheme <APP>
xcodebuild archive -workspace <APP>.xcworkspace -scheme <APP> -archivePath archives/<APP>.xcarchive -configuration Release > /dev/null
xcodebuild -exportArchive -archivePath archives/<APP>.xcarchive -exportPath exports -exportOptionsPlist <APP>/ExportOptions.plist > /dev/null
```
3. Upload the resulting .ipa file to App Store Connect via Transporter (available on the Apple App Store)
4. Receive an email from apple that the build was rejected.

## Expected Results
The build should show in the App Store Connect portal under its build version.

## Snack, code example, screenshot, or link to a repository

Here is the content of the rejection email I received:
![image](https://user-images.githubusercontent.com/34288132/116098966-1e9c3100-a671-11eb-8603-82fa397bc712.png)

Although it lists many selectors, I've only found the following in React/React Native:
```
_isKeyDown, _modifiedInput, _modifierFlags, handleNotification:, onSuccess:, setCategoryID:
```

These selectors are disabling the ability to upload to the app store.

**Comment by skay97** [comment]
@itsmistad I'm having the same issue with my app. Were you able to figure how to resolve the issue?

**Comment by archcorsair** [comment]
I'm currently experiencing the same issue. I've been able to build on 0.64 before, but today I was unable to push a new build up to AppStore.

**Comment by itsmistad** [comment]
Make sure that you are archiving as Release and not Debug, that was the issue I was facing. The DEBUG flag was defined, causing the listed selectors to appear in the app.

**Comment by archcorsair** [comment]
> Make sure that you are archiving as Release and not Debug, that was the issue I was facing. The DEBUG flag was defined, causing the listed selectors to appear in the app.

This solved my problem!

**Comment by haitaox** [comment]
I know that archiving as release solves the issue, but we also need to release debug build on TestFlight. and this is blocking us releasing debug builds.

**Comment by itsmistad** [comment]
@haitaox 
The principle here is to never upload a build to TestFlight that's been archived as debug. Instead, these builds should be production-ready in that they can be directly published to the app store from App Store Connect, immediately after your testing has completed in TestFlight.

What's the circumstance you're tied up in that requires it to be a debug-archived build?

**Comment by haitaox** [comment]
@itsmistad we have both debug and release builds on TestFlight. debug builds are for QA/manager/marketing people. debug build has dev tools for testing/debugging. release build will be the last build to test before final release.
