### ISSUE TITLE
iOS won't build on fresh project with latest MacOS 11.3 and Xcode 12.5

### ISSUE THREAD

**Issue by yeong0809** [facebook/react-native#31441]
## Description
Fresh new project won't build in MacOS 11.3 and Xcode 12.5.

## React Native version:
"react": "17.0.1",
"react-native": "0.64.0"

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. create new project
2. react-native run-ios

## Expected Results
App run normally

## Snack, code example, screenshot, or link to a repository:
<img width="261" alt="Screenshot 2021-04-27 at 5 42 47 PM" src="https://user-images.githubusercontent.com/31876283/116221218-fd763600-a77f-11eb-9cb8-494f182f34bf.png">

**Comment by dejolt** [comment]
TEMPORARY SOLUTION!

I got around the error by commenting out **use_flipper!()** in the pod file, and run pod install. Seems to be a flipper issue. Give it a try see if it works while there's a better solution.

**Comment by iaroslav-ternovyi** [comment]
try [this](https://github.com/facebook/react-native/issues/28405#issuecomment-827570553)

**Comment by robbiemccorkell** [comment]
Similar to @iaroslav-ternovyi's comment. This patch worked for me as a temporary solution: https://github.com/facebook/flipper/issues/2215#issuecomment-827422023

You'll need to go into the Filipper-Folly dependancy in the Pods directory and apply the following diff to the file:

`{project-name}/ios/Pods/Flipper-Folly/folly/synchronization/DistributedMutex-inl.h`

![](https://user-images.githubusercontent.com/45052513/116209991-a9158b00-a76c-11eb-8ca6-7a7b8bcc5ca0.png)

https://github.com/facebook/folly/commit/8477e25603f131c0400b6964609c76b438826788#diff-65ad309ca9c636ba81eb7953fce06e6963c51296a60dc25eb4a5b1463482c6da

It seems like we might need to wait for a new version of Flipper-Folly for this to be fixed.

**Comment by danyasnov** [comment]
it's time to install xcode not from the AppStore

**Comment by AlexHooperDev** [comment]
>Similar to @iaroslav-ternovyi's comment. This patch worked for me as a temporary solution: facebook/flipper#2215 (comment)
You'll need to go into the Filipper-Folly dependancy in the Pods directory and apply the following diff to the file:

This fixed the issue for `flipper-folly` however it just causes the same CompileC error on another flipper pod `FlipperRSocketResponder`.

globally disabling flipper also doesn't work, and instead causes the following CompileC error to happen:
```CompileC /Users/alex.hooper/Library/Developer/Xcode/DerivedData/Espresso-brgntaoyjolqyfdzcsunjlqtzzum/Build/Intermediates.noindex/Espresso.build/Debug-iphoneos/Espresso.build/Objects-normal/arm64/AppDelegate.o /Users/alex.hooper/Documents/figloo-bank-mobile/ios/Espresso/AppDelegate.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler```

**Comment by SevrainChea** [comment]
Commenting use_flipper() in the Podfile fixed the issue for me, waiting for them to fix it to uncomment it !

**Comment by kelset** [comment]
hey folks looks like this was already reported here: https://github.com/facebook/react-native/issues/31179 so for the sake of having one place where the conversation will proceed forward I'll close this as duplicate, please post your comments in the other issue :)

**Comment by sarafhbk** [comment]
@robbiemccorkell the solution is working for me. Could you please help me doing the Flipper-Folly patch package

**Comment by webmasterdevlin** [comment]
I just want to share this link https://developer.apple.com/download/more/?=xcode. Downgrading to a lower version of XCode is okay if the latest features of XCode 12.5 are not crucial in your project.

**Comment by archcorsair** [comment]
Can confirm 0.64.1 fixes this for me!

**Comment by kelset** [comment]
I'm going to lock this since now there's -> https://github.com/facebook/react-native/issues/31480
