### ISSUE TITLE
iOS Text ellipsizeMode = 'tail' doesn't work when text ends with '\n' 

### ISSUE THREAD

**Issue by macartigan** [facebook/react-native#31449]
## Description

    use Text, set props numberOfLines={4}

<Text numberOfLines={4}>
line 1
line 2
line 3
line 4
line 5
line 6
</Text>

Describe what you expected to happen:
the missing text at the end of the line is indicated by an ellipsis glyph, not '\n'

## React Native version:
0.64.0

nb : bug is only on ios

related issue: https://github.com/facebook/react-native/issues/27452

**Comment by huanguolin** [comment]
same issue here.

**Comment by mzyisbest** [comment]
me too

**Comment by fabriziobertoglio1987** [comment]
Do you still experience this issue? 

I have four years of experience maintaining facebook/react-native and I specialize in the Text and TextInput components. I currently have 58 [facebook/react-native PRs](https://github.com/facebook/react-native/pulls?q=is%3Apr+author%3Afabriziobertoglio1987+). 

If you still experience this issue, I will prepare a patched release with the fix.

Thanks a lot
