### ISSUE TITLE
0.64.0 pod install failed

### ISSUE THREAD

**Issue by sw517227087** [facebook/react-native#31440]
pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
#        pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
        pod 'FBReactNativeSpec', :path => "../node_modules/react-native/React/FBReactNativeSpec"
        pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
        pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
        pod 'React', :path => '../node_modules/react-native/'
        pod 'React-Core', :path => '../node_modules/react-native/'
        pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
        pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
        pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
        pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
        pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
        pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
        pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
        pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
        pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
        pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
        pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
        pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

        pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
        pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
        pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
        pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
#        pod 'ReactCommon/callinvoker', :path => "../node_modules/react-native/ReactCommon"
        pod 'React-callinvoker', :path => "../node_modules/react-native/ReactCommon/callinvoker"
        pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
        #这里perflogger 手动添加
        pod 'React-perflogger', :path => '../node_modules/react-native/ReactCommon/reactperflogger'
        #这里runtimeexecutor 手动添加
        pod 'React-runtimeexecutor', :path => '../node_modules/react-native/ReactCommon/runtimeexecutor'
        pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

        pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
        pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
#        pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
        pod 'RCT-Folly', :podspec => '../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec'

**Comment by chrisbobbe** [comment]
Please post the exact error output you're seeing with the failure.

**Comment by mattchatterley** [comment]
I have the same error, occuring thus:

Matts-MBP:ios mattc$ pod install

Auto-linking React Native modules for target `Freer`: BVLinearGradient, RNCPushNotificationIOS, RNDateTimePicker, RNGestureHandler, RNSVG, RNVectorIcons, ReactNativeGetLocation, react-native-maps, and react-native-webview

Analyzing dependencies

Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`

[!] No podspec found for `FBReactNativeSpec` in `../node_modules/react-native/Libraries/FBReactNativeSpec`

**Comment by rdforte** [comment]
are there any updates on this error? I am getting the same error as @mattchatterley

**Comment by rajatgyl** [comment]
Not able to create a new project using 'npx react-naitve init project_name'

There is a pod error and it asks to install pod manually by cd project_name and then cd ios and after that pod install but getting error in pod install.

![Screenshot 2021-05-14 at 2 32 24 PM](https://user-images.githubusercontent.com/48783158/118248292-c616c180-b4c1-11eb-9d25-37fe81e91d3c.png)

**Comment by whysetiawan** [comment]
any update on this?

**Comment by sw517227087** [comment]
try this 
![image](https://user-images.githubusercontent.com/5086901/119334752-0e9e5e00-bcbe-11eb-9c8c-73341ebd7df6.png)

**Comment by charleston10** [comment]
> try this
> ![image](https://user-images.githubusercontent.com/5086901/119334752-0e9e5e00-bcbe-11eb-9c8c-73341ebd7df6.png)

Worked... tks

**Comment by follyxing** [comment]
Copy -> Paste -> 🎉

```ruby

  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/React/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'React-callinvoker', :path => "../node_modules/react-native/ReactCommon/callinvoker"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'RCT-Folly', :podspec => '../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec'

  pod 'React-perflogger', :path => '../node_modules/react-native/ReactCommon/reactperflogger'
  pod 'React-runtimeexecutor', :path => '../node_modules/react-native/ReactCommon/runtimeexecutor'



```

**Comment by follyxing** [comment]
Since the **0.64.0** version, some module paths have changed, the Podfile file of this document cannot be used.
fix: [31440](https://github.com/facebook/react-native/issues/31440)

**Comment by dittoalvarez** [comment]
![Screen Shot 2021-10-20 at 3 45 54 PM](https://user-images.githubusercontent.com/76958831/138050165-779a96f9-9e7e-4e15-b266-5dba7379f0a5.png)

**Comment by lavanyasundararajan** [comment]
[!] Unable to find a specification for `React-logger (= 0.66.4)` depended upon by `ReactCommon/turbomodule/core`

any clue how to resolve this

**Comment by ThalKod** [comment]
@lavanyasundararajan I'm having the same issue, did you find a way to fix this ?

**Comment by lavanyasundararajan** [comment]
Hi ,

  Go back to RN 62 or 63 versions

Thanks,
Lavanya

**Comment by eduzatoni** [comment]
`pod 'React-logger', :podspec => '../node_modules/react-native/ReactCommon/logger'`

**Comment by lindenberg** [comment]
change: 
pod 'RCT-Folly', :podspec => "../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec" 

to: 
pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'


works for me.

**Comment by JJalit** [comment]
I worked it.

arch -x86_64 pod install

**Comment by zhouhao27** [comment]
> try this ![image](https://user-images.githubusercontent.com/5086901/119334752-0e9e5e00-bcbe-11eb-9c8c-73341ebd7df6.png)

Got the following error:

> Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
[!] Unable to find a specification for `React-utils` depended upon by `React-Core`
