### ISSUE TITLE
TextInput accepts formatted text on paste, shows formatting in the TextInput but gives plain text from callback

### ISSUE THREAD

**Issue by vaibhavs2** [facebook/react-native#31442]
## Description
TextInput accepting rich(formatted) text on paste. all colors, fontSize, spacings are maintained and showing up in TextInput but  `onTextChange` not giving any information about formatting, it just giving out plain texts.

## React Native version:

  Binaries:
    Node: 14.15.4 - ~/node/bin/node
    Yarn: 1.22.10 - ~/node/bin/yarn
    npm: 7.9.0 - ~/node/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 23, 27, 28, 29
      Build Tools: 28.0.3, 29.0.1, 29.0.2
      System Images: android-23 | Intel x86 Atom_64, android-27 | Intel x86 Atom_64, android-27 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: javac 9-internal - /usr/bin/javac
    Python: 3.8.5 - /home/war/anaconda3/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
0. Use Android OS
1. Use TextInput in components
2. Copy rich(formatted) text from any webpage in you mobile browser
3. Paste that copied rich text in the TextInput
4. looks at the text you got from `onTextChange`
4. Don't do like copy rich text from browser on Desktop and paste that in emulator, it will not reproduce.
5. Copy from Mobile's bowser and paste in the same mobile's new react-native App's TextInput

## Expected Results
TextInput should show the same plain text that we are getting from `onChangeText`, or `onChangeText` should give us information about formatting with Pasted text.

##  screenshot :

<img src="https://user-images.githubusercontent.com/31806059/116220313-2e4b7080-a76a-11eb-92b7-1aecde86e745.gif" height="480" />

#### `message` contains the plain text I am getting from `onChangeText`

![state](https://user-images.githubusercontent.com/31806059/116220359-3c998c80-a76a-11eb-821e-3b72613c0419.png)

**Comment by vlesu** [comment]
As a temporary solution for clean up formatting from pasted text, I use

```
<TextInput value={this.state.myText}
    onChangeText={(newText) => {
      if (Math.abs(this.state.myText.length - newText.length)<=1) { // type in
        this.setState({myText: newText});
      } else { // paste
        this.setState({myText: ' '+newText}, ()=>{
            this.setState({myText: newText});
        });
      }
    }}
/>
```

**Comment by betoharres** [comment]
I'm also facing this issue; any progress on this?

**Comment by Rishabh20051997** [comment]
This issue occurs due to some invisible characters like `https://www.compart.com/en/unicode/U+FFFC` also getting copied.

This code resolved the issue of copied images for me

<TextInput
....
onChangeText={(content) => {
          let finalResult = content.replace(/￼/g, '')
          this.setState({
            descriptionValue: finalResult,
         })
        }}
/>
