### ISSUE TITLE
'folly/dynamic.h' file not found

### ISSUE THREAD

**Issue by enderlabo** [facebook/react-native#31452]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Hi comunity, after updated big Sur 11.3, my project made on React Native don't work, by xCode said: 'folly/dynamic.h' file not found and on the terminal said: error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening navigatorapp.xcodeproj.

## React Native version:
System:
    OS: macOS 11.3
    CPU: (8) x64 Intel(R) Core(TM) i3-10100 CPU @ 3.60GHz
    Memory: 214.07 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.10.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.3
      System Images: android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7199119
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_242-release - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.0 => 0.64.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.
2.

## Expected Results
can open my project of RN on iOS Emulator

## Snack, code example, screenshot, or link to a repository:
https://imgur.com/a/ofhztde

**Comment by jonasostrom** [comment]
+1

**Comment by luisnunes111** [comment]
+1

**Comment by luisnunes111** [comment]
I fixed it by cleaning up all the packages and caches, I'm currently using React Native 0.64 and XCode 12.5.
These are the commands that I used:
```
rm -rf node_modules
rm -rf ios/Pods
rm ios/Podfile.lock 
rm -rf ~Library/Developer/Xcode/DerivedData
```

**Comment by enderlabo** [comment]
> ~Library/Developer/Xcode/DerivedData

don't work for me.

**Comment by luisnunes111** [comment]
> > ~Library/Developer/Xcode/DerivedData
> 
> don't work for me.

Sorry it had a typo, try it this way `rm -rf ~/Library/Developer/Xcode/DerivedData`

**Comment by harbolaez** [comment]
Getting the same thing too, at the latest. Any update on this? Here is an example of the Podfile, I'm doing a manual link since is a bridge. 

```
source 'https://github.com/facebook/react-native.git'
    source 'https://github.com/CocoaPods/Specs.git'
    rn_path = '~/.cocoapods/repos/facebook'

    pod 'React', :path => "#{rn_path}/"
    pod 'React-Core', :path => "#{rn_path}/"
    pod 'React-Core/DevSupport', :path => "#{rn_path}/"
    pod 'React-Core/RCTWebSocket', :path => "#{rn_path}/"
    pod 'React-jsi', :path => "#{rn_path}/ReactCommon/jsi"
    pod 'React-RCTBlob', :path => "#{rn_path}/Libraries/Blob"
    pod 'React-RCTText', :path => "#{rn_path}/Libraries/Text"
    pod 'React-RCTImage', :path => "#{rn_path}/Libraries/Image"
    pod 'RCTRequired', :path => "#{rn_path}/Libraries/RCTRequired"
    pod 'Yoga', :path => "#{rn_path}/ReactCommon/yoga/yoga.podspec"
    pod 'React-RCTNetwork', :path => "#{rn_path}/Libraries/Network"
    pod 'RCTTypeSafety', :path => "#{rn_path}/Libraries/TypeSafety"
    pod 'React-cxxreact', :path => "#{rn_path}/ReactCommon/cxxreact"
    pod 'FBLazyVector', :path => "#{rn_path}/Libraries/FBLazyVector"
    pod 'React-CoreModules', :path => "#{rn_path}/React/CoreModules"
    pod 'React-RCTSettings', :path => "#{rn_path}/Libraries/Settings"
    pod 'React-RCTLinking', :path => "#{rn_path}/Libraries/LinkingIOS"
    pod 'React-RCTVibration', :path => "#{rn_path}/Libraries/Vibration"
    pod 'ReactCommon/turbomodule/core', :path => "#{rn_path}/ReactCommon"
    pod 'React-jsiexecutor', :path => "#{rn_path}/ReactCommon/jsiexecutor"
    pod 'React-jsinspector', :path => "#{rn_path}/ReactCommon/jsinspector"
    pod 'React-callinvoker', :path => "#{rn_path}/ReactCommon/callinvoker"
    pod 'React-RCTAnimation', :path => "#{rn_path}/Libraries/NativeAnimation"
    pod 'FBReactNativeSpec', :path => "#{rn_path}/React/FBReactNativeSpec"
    pod 'React-RCTActionSheet', :path => "#{rn_path}/Libraries/ActionSheetIOS"
    # 3rd
    pod 'RCT-Folly', :path => "#{rn_path}/third-party-podspecs/RCT-Folly.podspec"
    pod 'React-perflogger', :path => "#{rn_path}/ReactCommon/reactperflogger/React-perflogger.podspec"
    pod 'React-runtimeexecutor', :path => "#{rn_path}/ReactCommon/runtimeexecutor/React-runtimeexecutor.podspec"

    pod 'RNInAppBrowser', :git => "https://github.com/proyecto26/react-native-inappbrowser.git", :tag => 'v3.5.1'
    pod 'react-native-netinfo', :git => "https://github.com/react-native-community/react-native-netinfo.git", :tag => 'v5.9.10'
    pod 'react-native-safe-area-context', :git => "https://github.com/th3rdwave/react-native-safe-area-context.git", :tag => 'v3.2.0'
    pod 'react-native-webview', :git => 'https://github.com/react-native-community/react-native-webview.git', :tag => 'v10.9.1'
    pod 'react-native-restart', :git => 'https://github.com/avishayil/react-native-restart.git', :tag => '0.0.20'
    # TODO: disabled rollbar for now, in RN
    # pod 'RollbarReactNative', :git => 'https://github.com/rollbar/rollbar-react-native.git', :tag => 'v0.9.2'
    pod 'rn-fetch-blob', :git => 'https://github.com/joltup/rn-fetch-blob.git', :tag => 'v0.12.0'

    # Reanimated and gesture handle for react-native-navigation
    pod 'RNGestureHandler', :git => "https://github.com/software-mansion/react-native-gesture-handler.git", :tag => '1.9.0'
    pod 'RNReanimated', :git => "https://github.com/software-mansion/react-native-reanimated.git", :tag => '1.13.2'
```
![Screen Shot 2021-05-06 at 8 21 54 AM](https://user-images.githubusercontent.com/13140872/117323861-1f3c8080-ae44-11eb-8f7c-cef32146a57a.png)

**Comment by enderlabo** [comment]
don't work for me.

**Comment by harbolaez** [comment]
any idea?

**Comment by enderlabo** [comment]
> Removing of cocoapods cache helped me
> rm -rf ~/Library/Caches/CocoaPods

same error, error 65 when i build app, so.. don't work for me, i'll migrate to Flutter.

**Comment by GittiMcHub** [comment]
Had the same issue after I checked out my Repo and tried to build it first time on Windows instead of Ubuntu.

Solved it by just stopping Metro, then:
```
cd android
gradlew clean
cd app
..\gradlew clean
```

And finally start Metro again with: `npx react-native start --reset-cache`

**Comment by abheesree** [comment]
> Folly

did you find any solution ?

**Comment by sandeeprana011** [comment]
> Getting the same error, with the latest RN version. Here is an example of the Podfile, I'm doing a manual link since is a bridge.
> 
> This only happens when i'm using https://github.com/leavez/cocoapods-binary library
> 
> ```
> source 'https://github.com/facebook/react-native.git'
>     source 'https://github.com/CocoaPods/Specs.git'
>     rn_path = '~/.cocoapods/repos/facebook'
> 
>     pod 'React', :path => "#{rn_path}/"
>     pod 'React-Core', :path => "#{rn_path}/"
>     pod 'React-Core/DevSupport', :path => "#{rn_path}/"
>     pod 'React-Core/RCTWebSocket', :path => "#{rn_path}/"
>     pod 'React-jsi', :path => "#{rn_path}/ReactCommon/jsi"
>     pod 'React-RCTBlob', :path => "#{rn_path}/Libraries/Blob"
>     pod 'React-RCTText', :path => "#{rn_path}/Libraries/Text"
>     pod 'React-RCTImage', :path => "#{rn_path}/Libraries/Image"
>     pod 'RCTRequired', :path => "#{rn_path}/Libraries/RCTRequired"
>     pod 'Yoga', :path => "#{rn_path}/ReactCommon/yoga/yoga.podspec"
>     pod 'React-RCTNetwork', :path => "#{rn_path}/Libraries/Network"
>     pod 'RCTTypeSafety', :path => "#{rn_path}/Libraries/TypeSafety"
>     pod 'React-cxxreact', :path => "#{rn_path}/ReactCommon/cxxreact"
>     pod 'FBLazyVector', :path => "#{rn_path}/Libraries/FBLazyVector"
>     pod 'React-CoreModules', :path => "#{rn_path}/React/CoreModules"
>     pod 'React-RCTSettings', :path => "#{rn_path}/Libraries/Settings"
>     pod 'React-RCTLinking', :path => "#{rn_path}/Libraries/LinkingIOS"
>     pod 'React-RCTVibration', :path => "#{rn_path}/Libraries/Vibration"
>     pod 'ReactCommon/turbomodule/core', :path => "#{rn_path}/ReactCommon"
>     pod 'React-jsiexecutor', :path => "#{rn_path}/ReactCommon/jsiexecutor"
>     pod 'React-jsinspector', :path => "#{rn_path}/ReactCommon/jsinspector"
>     pod 'React-callinvoker', :path => "#{rn_path}/ReactCommon/callinvoker"
>     pod 'React-RCTAnimation', :path => "#{rn_path}/Libraries/NativeAnimation"
>     pod 'FBReactNativeSpec', :path => "#{rn_path}/React/FBReactNativeSpec"
>     pod 'React-RCTActionSheet', :path => "#{rn_path}/Libraries/ActionSheetIOS"
>     # 3rd
>     pod 'RCT-Folly', :path => "#{rn_path}/third-party-podspecs/RCT-Folly.podspec"
>     pod 'React-perflogger', :path => "#{rn_path}/ReactCommon/reactperflogger/React-perflogger.podspec"
>     pod 'React-runtimeexecutor', :path => "#{rn_path}/ReactCommon/runtimeexecutor/React-runtimeexecutor.podspec"
> 
>     pod 'RNInAppBrowser', :git => "https://github.com/proyecto26/react-native-inappbrowser.git", :tag => 'v3.5.1'
>     pod 'react-native-netinfo', :git => "https://github.com/react-native-community/react-native-netinfo.git", :tag => 'v5.9.10'
>     pod 'react-native-safe-area-context', :git => "https://github.com/th3rdwave/react-native-safe-area-context.git", :tag => 'v3.2.0'
>     pod 'react-native-webview', :git => 'https://github.com/react-native-community/react-native-webview.git', :tag => 'v10.9.1'
>     pod 'react-native-restart', :git => 'https://github.com/avishayil/react-native-restart.git', :tag => '0.0.20'
>     # TODO: disabled rollbar for now, in RN
>     # pod 'RollbarReactNative', :git => 'https://github.com/rollbar/rollbar-react-native.git', :tag => 'v0.9.2'
>     pod 'rn-fetch-blob', :git => 'https://github.com/joltup/rn-fetch-blob.git', :tag => 'v0.12.0'
> 
>     # Reanimated and gesture handle for react-native-navigation
>     pod 'RNGestureHandler', :git => "https://github.com/software-mansion/react-native-gesture-handler.git", :tag => '1.9.0'
>     pod 'RNReanimated', :git => "https://github.com/software-mansion/react-native-reanimated.git", :tag => '1.13.2'
> ```
> 
> ![Screen Shot 2021-05-06 at 8 21 54 AM](https://user-images.githubusercontent.com/13140872/117323861-1f3c8080-ae44-11eb-8f7c-cef32146a57a.png)

Same Happening with me

**Comment by quentingirard** [comment]
Hello everyone

I solved it by

```
rm -rf Gemfile.lock
bundle install
```

And next
```
cd android
gradlew clean
```

I hope it could help !

**Comment by beta3-z** [comment]
I had bit similar issue, but with missing `folly/synchronization/RelaxedAtomic.h` and `/synchronization/SanitizeThread.h` header files.

Copying the *.h files from the official [folly github repo](https://github.com/facebook/folly) to `./ios/Pods/RTC-Folly/synchronization/*` worked for me.

P.S. Also, I tried to clean known caches and libraries, but it didn't help:
```sh
rm -rf ./node_modules
npm install
rm -rf ./ios/Pods
rm ./ios/Podfile.lock
rm -rf ~/Library/Developer/Xcode/DerivedData
rm -rf ~/Library/Caches/CocoaPods
pod cache clean --all
pod repo update
npx expo run:ios --device
```
