### ISSUE TITLE
Can't get hermes to work with android RN:`0.64.0`

### ISSUE THREAD

**Issue by huzaifaaak** [facebook/react-native#31453]
## Hermes is not working on android.

I have followed all the steps on the Hermes [documentation](https://reactnative.dev/docs/hermes). I have tried cleaning the gradle. The app builds and runs fine but `const isHermes = () => !!global.HermesInternal;` keeps on returning `null` 

<img width="699" alt="Screenshot 2021-04-29 at 1 33 41 am" src="https://user-images.githubusercontent.com/52660166/116546147-b23c5e80-a90a-11eb-934d-206428020377.png">

## React Native version:

> System:
>     OS: macOS 10.15.5
>     CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
>     Memory: 28.91 MB / 16.00 GB
>     Shell: 3.2.57 - /bin/bash
>   Binaries:
>     Node: 14.9.0 - ~/.nvm/versions/node/v14.9.0/bin/node
>     Yarn: 1.12.3 - /usr/local/bin/yarn
>     npm: 7.11.1 - ~/.nvm/versions/node/v14.9.0/bin/npm
>     Watchman: 4.9.0 - /usr/local/bin/watchman
>   Managers:
>     CocoaPods: 1.10.1 - /usr/local/bin/pod
>   SDKs:
>     iOS SDK:
>       Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
>     Android SDK:
>       API Levels: 21, 23, 25, 26, 27, 28, 29, 30
>       Build Tools: 23.0.1, 25.0.0, 25.0.1, 26.0.1, 26.0.2, 26.0.3, 27.0.2, 27.0.3, 28.0.2, 28.0.3, 29.0.2
>       System Images: android-26 | Google Play Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom
>       Android NDK: 17.2.4988734
>   IDEs:
>     Android Studio: 4.1 AI-201.8743.12.41.7042882
>     Xcode: 12.4/12D4e - /usr/bin/xcodebuild
>   Languages:
>     Java: 1.8.0_191 - /usr/bin/javac
>   npmPackages:
>     @react-native-community/cli: Not Found
>     react: 17.0.1 => 17.0.1 
>     react-native: 0.64.0 => 0.64.0 
>     react-native-macos: Not Found
>   npmGlobalPackages:
>     *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Setup Hermes on android
2. Run it on android and it does not work

## Expected Results
It should work on android

**Comment by glennweb** [comment]
Not sure if this is related. But found this item that saved my life. 

https://stackoverflow.com/questions/66189325/xcode-throws-atomic-notify-oneunsigned-long-is-unavailable

**Comment by huzaifaaak** [comment]
I belive this was issue due to incomplete `react-native-reanimated@2.1.0` setup. Herme's is giving random crashes on both ios and android for me. I have just disabled it for now
