### ISSUE TITLE
[Style] Default style has int64 color code instead of string. 0.12.0-rc is failing on it.

### ISSUE THREAD

**Issue by dsandor** [facebook/react-native#3146]
I am attempting to port my iOS app in react-native to Android.  I am experiencing a bunch of issues surrounding colors and default styles.  I am getting TypeError: expected dynamic type 'string', but had type 'int64'.

Attached the debugger to the processes and I am seeing calls to the following code in CatalystStylesDiffMap.class:

```
public String getString(String name) {
        return this.mBackingMap.getString(name);
    }
```
Examining the values I see the color property is an int64.  

```
{ CatalystStylesDiffMap: { NativeMap: {"textAlign":"center","fontWeight":"bold","fontSize":17,"fontFamily":".HelveticaNeueInterface-MediumP4","color":-16745729,"isHighlighted":false,"accessible":true,"allowFontScaling":true} } }
```

Have I done something wrong or is this a bug in 0.12.0-rc?

**Comment by brentvatne** [comment]
cc @mkonicek @kmagiera seems related to moving color processing to JS

**Comment by dsandor** [comment]
I think I figured this out.  It looks like my application (even when `init`ing a fresh app) was importing java libraries for 0.11 dependencies:
```
compile 'com.facebook.react:react-native:0.11.+'
```

I verified my installed version of `react-native`

```
MacBook-Pro:test dsandor$ which react-native
/usr/local/bin/react-native
MacBook-Pro:test dsandor$ ls -la /usr/local/bin/react*
lrwxr-xr-x  1 root  admin  45 Sep 14 07:51 /usr/local/bin/react-native -> ../lib/node_modules/react-native-cli/index.js

MacBook-Pro:test dsandor$ cat /usr/local/lib/node_modules/react-native/package.json
{
  "name": "react-native",
  "version": "0.12.0-rc",
```

init'ed a new project and looked at the `build.gradle` file to see it is 0.11+.

Checked the `node_modules/react-native/Libraries/StyleSheet` to see 0.11 files (0.12+ has a new processColor.js file in it as seen by recent commits.)

```
MacBook-Pro:inittest dsandor$ ls node_modules/react-native/Libraries/StyleSheet/
EdgeInsetsPropType.js	StyleSheet.js		StyleSheetValidation.js	precomputeStyle.js
LayoutPropTypes.js	StyleSheetPropType.js	TransformPropTypes.js	styleDiffer.js
PointPropType.js	StyleSheetRegistry.js	flattenStyle.js
```

So to make this work I changed the build.gradle to 0.12+, and ran `npm i react-native@0.12.0-rc` to force the correct android libraries and the correct react-native module.  Now the app works.

Is this my machine or npm cache that is horked up or is it an npm install problem with the 0.12.0-rc?  I also noticed that none of the files in the $PROJECTDIR$/android folder get updated when doing an `npm i` or `npm update` which leaves the native app setting behind in version.
