### ISSUE TITLE
React Native's NEW architecture

### ISSUE THREAD

**Issue by CuriousBlueCat** [facebook/react-native#31469]
Hi everybody! 😃
Does anyone know if React Native's NEW architecture is a real thing to come true or a wish that will never come true?
Some developers mentioned about that in 2018, 2019 and it supposed to came out last year, but... nothing.

When will it release as a RN version in public?

Thanks 🙏

![react-nativ-architecture](https://user-images.githubusercontent.com/37933500/116824533-a8249500-ab82-11eb-9b9e-640047262351.png)

![react-native-new-architecture](https://user-images.githubusercontent.com/37933500/116824535-a8bd2b80-ab82-11eb-8244-a0357014b13f.png)

**Comment by tabfed** [comment]
I think the new architecture failed

**Comment by leogentleman** [comment]
I also want to know the progress, now the progress of rn is much slower than flutter.

**Comment by IronTony** [comment]
Yeah! This is an awesome question. There is no infos about it!
I think that would be nice having some more info from the RN developers

**Comment by beqramo** [comment]
looking forward to answer

**Comment by CuriousBlueCat** [comment]
@grabbou @kelset @shergin @mdvacca @JoshuaGross @yungsters - can you assist here please?   

In other forums, I read that (many) developers think Facebook gave up RN, while Flutter gets full support from Google.
People wonder if all the beautiful presentations and articles about the new architecture from 2019 will come true and when.

I am concerned that the massive project that I invested a lot of time and money will go down the drain in a few years as there is no good support anymore for future improvements.

In that case, I may need to decide to move to Flutter or native.

All projects in RN are at risk as long as there is no clear roadmap and the future of RN base on wishes. Facebook may abandon RN sooner or later, and RN will die slowly - this is exactly what I hear from RN developers.

Although some code is here https://github.com/facebook/react-native 

There is zero progress about the new architecture here -
https://github.com/facebook/react-native/releases/tag/v0.64.0

I would like to understand where the new architecture is right now (May 2021) and if it has a promising future? And when?

Thank you all 🙏🏻

**Comment by beqramo** [comment]
as I remember the company that can abandon and forget projects like this big is Google not FB and I think that will be a really bad tone for FB if they did this, they like to do Maximum in almost everything and I know that RN has huge potential and that will be really sad from FB.

Also, Software Mansion is doing a great job in optimizing and making RN as perfect as possible even today and I hope that Fb is doing a really big update in the background or something.

**Comment by yungsters** [comment]
We absolutely are still working on this and have not lost any momentum. I apologize that we haven’t continuously communicated progress.

I wanted I quickly share this tidbit and to appreciate you for raising the concerns. I’ll work with the team to respond with more of the juicy details after this comment.

**Comment by CuriousBlueCat** [comment]
What makes me worried - the last conferences FB/React native did was in 2019! 😢 
While Google/Flutter launched recently a big online event about the next version: Flutter 2. 

![Conferences](https://user-images.githubusercontent.com/37933500/116921371-ca361a00-ac4b-11eb-9e42-f4e73a42d526.jpg)

**Comment by kelset** [comment]
Thanks @yungsters for the update; I'll close this issue in favour of the dedicated ones there are around the new architecture over here:
* https://github.com/react-native-community/discussions-and-proposals/issues/4
* https://github.com/react-native-community/discussions-and-proposals/issues/91
* https://github.com/react-native-community/discussions-and-proposals/issues/40
