### ISSUE TITLE
Command (⌘)-R is now recording the simulator in addition to reloading JS (Xcode 12.5)

### ISSUE THREAD

**Issue by ferrannp** [facebook/react-native#31467]
## Description

Looks like the CMD-R mapping is taken now in XCode 12.5:

<img width="236" alt="Screenshot 2021-05-01 at 19 51 29" src="https://user-images.githubusercontent.com/774577/116790816-a2fa1400-aab6-11eb-8ed6-33a2c96f1bd8.png">

## React Native version:
N/A.

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Open simulator in XCode 12.5
2. Press CMD-R to reload JS, the simulator will start recording the screen

I did not find a way to prevent this. Should we map reloading JS to different keys?

**Comment by dulmandakh** [comment]
Double R 👍

**Comment by anhtuank7c** [comment]
@dulmandakh It'll record the screen then reload the JS 😢

**Comment by dulmandakh** [comment]
Just Double R, no command key

**Comment by ernestasgobionis** [comment]
Double R doesn't work on iOS simulator, I think that only works for Android

**Comment by ferrannp** [comment]
Hey @dulmandakh ! Double R does not work on iOS simulator. And even if you could... When you were focus in some TextInput, that wouldn't work I guess.

As an alternative:

- R key in the terminal running the packager
- CMD+D and Reload as @ernestasgobionis suggested

But I am hoping we can map another CMD+ something in the simulator because I am recording ALL THE TIME by mistake 😂 .

**Comment by jonstuebe** [comment]
This is my work around: https://twitter.com/jonstuebe/status/1390384513927184385

**Comment by RodolfoGS** [comment]
## How to remapping simulator screen record shortcut

First, open system preferences and open the Keyboard area.

![image](https://user-images.githubusercontent.com/870365/117540039-e1219700-afd2-11eb-8eaf-1c81cc482290.png)


Next:
1. Click on Shortcuts
2. Click App Shortcuts
3. Click the plus button

![image](https://user-images.githubusercontent.com/870365/117540045-e67ee180-afd2-11eb-952b-95ef95a36342.png)

1. Select Other
2. Shift + Cmd + G
3. Enter in /Applications/Xcode.app/Contents/Developer/Applications/
4. Select Simulator App
5. Enter for Menu Title: "Record Screen"
6. Click into the keyboard shortcut box and press your desired shortcut (Ex: Cmd + Shift + R)

![image](https://user-images.githubusercontent.com/870365/117540061-f26aa380-afd2-11eb-97a4-62d83ab53aa7.png)

---
Source: https://twitter.com/jonstuebe/status/1390384513927184385
Thanks @jonstuebe

**Comment by CaiYiLiang** [comment]
Thanks @jonstuebe 
Works for me

**Comment by grackanil** [comment]
Thanks @jonstuebe

**Comment by JeffreyLeeDave** [comment]
That stops the whole command + R from recording for me, but I still can't refresh with command + R

**Comment by ValterSantosMatos** [comment]
@JeffreyLeeDave, not exactly the same, but I added  a shortcup on "command + R" to "Shake" the phone (so it opens the menu)

**Comment by nysamnang** [comment]
**Short Answer:**

We can remap simulator screen record shortcut following the steps below:

1. Open Simulator
2. Right click the icon in the tray
3. Select Options > Show in Finder
4. Copy Simulator.app to your /Applications directory
5. Open System Preferences > Keyboard > Shortcuts
6. Click App Shortcuts > add [+]
7. Select the Simulator.app from the list
8. Enter Menu Title `Record Screen` (or other name of the Simulator's Shortcut)
9. Enter Keyboard Shortcut whatever you want
10. Click Add
11. Delete Simulator.app from /Applications
12. Done! The shortcut will still be changeable.

**Comment by tijs** [comment]
While workarounds are nice this is still a valid issue. So I hope the reload keyboard shortcut will be change in upcoming react native versions?

**Comment by dnlgrgly** [comment]
@jonstuebe since Elon broke Twitter, non-users (including me) cannot see your actual solution 😢
Could you please share it here? :)

<img width="670" alt="image" src="https://github.com/facebook/react-native/assets/22714514/e2933fab-0e28-48c3-8625-cb00d2afea5f">

**Comment by liamjones** [comment]
@dnlgrgly it's the instructions in the comment two posts below Jon's: https://github.com/facebook/react-native/issues/31467#issuecomment-835352650
