### ISSUE TITLE
Screen recording on refresh

### ISSUE THREAD

**Issue by jonathanroze** [facebook/react-native#31472]
Hi,

I'm using RN 0.63 and I update Xcode and simulators to the latest version, with simulator screen recording by pressing cmd + r.

But, cmd + r is also used to refresh react-native app. 

Is there a way to change key mapping to refreshing app ? 

Thanks

**Comment by Dag0n** [comment]
This is the same as is reported here: https://github.com/facebook/react-native/issues/31467

You can reload by pressing R, R on the metro window.
