### ISSUE TITLE
RN0.64.0 Dimensions.get('screen') and screen property of Dimensions eventlistener does not reflect device orientation

### ISSUE THREAD

**Issue by ws333** [facebook/react-native#31474]
RN0.64.0 Dimensions.get('screen') and screen property of Dimensions eventlistener does not reflect device orientation. Works as expected with RN0.63.4

Edit: It seems like the window property also is affected by this bug.

## React Native version:
System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 AMD Ryzen 5 4600H with Radeon Graphics
    Memory: 10.49 GB / 31.36 GB
  Binaries:
    Node: 14.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
    Watchman: 20201115.021953.0 - C:\ProgramData\chocolatey\bin\watchman.EXE
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7199119
    Visual Studio: 16.8.30717.126 (Visual Studio Community 2019)
  Languages:
    Java: 11.0.9.1 - C:\Program Files\AdoptOpenJDK\jdk-11.0.9.101-hotspot\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.0 => 0.64.0
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce

1. Set up a new React Native project with npx react-native init AwesomeTSProject --template react-native-template-typescript
2. Add eventlistener in App.tsx:

```
 useEffect(() => {
    function handleDimensionsChange({
      window,
      screen,
    }: {
      window: ScaledSize;
      screen: ScaledSize;
    }) {
      console.log("Dimensions.get('screen'):", Dimensions.get('screen'));
      console.log('handleDimensionsChange -> window', window);
      console.log('handleDimensionsChange -> screen', screen);
    }
    Dimensions.addEventListener('change', handleDimensionsChange);

    return () => {
      Dimensions.removeEventListener('change', handleDimensionsChange);
    };
  }, []);
```

## Expected Results
That the height and width of screen property reflect the device orientation like with RN0.63.4.

**Comment by 0rsa** [comment]
Same issue here using 0.64.0
I confirm that this is working fine with 0.63.4

I add this strange behaviour using 0.64.0 :
- Kill your app
- Launch your app in landscape mode
- Change device orientation to portrait mode
-> Dimensions event is correctly fired with correct dimensions, just one time, then this is broken and it will never fire again. It does not work at all if you launch your app using portait mode first.

**Comment by ws333** [comment]
Fixed in [RN0.64.2](https://github.com/facebook/react-native/releases/tag/v0.64.2)
