### ISSUE TITLE
Build failing for cocopods installation

### ISSUE THREAD

**Issue by jitunayak** [facebook/react-native#31478]
Hi Team,
<img width="1228" alt="Screenshot 2021-05-04 at 11 05 10 PM" src="https://user-images.githubusercontent.com/35754866/117045538-3e94ba00-ad2d-11eb-85c4-c639082fa4ef.png">

I am experiencing above error for couple of days while creating app using react-native-cli. If you see the error, it says target is set to 8.0 where as my podfile has version 10.0

I tried upgrading through cocopods upgrade command. Still no help!.

My PodFile has below versions 

```
Installing CocoaAsyncSocket (7.6.5)
Installing DoubleConversion (1.1.6)
Installing FBLazyVector (0.64.0)
Installing FBReactNativeSpec (0.64.0)
Installing Flipper (0.75.1)
Installing Flipper-Boost-iOSX (1.76.0.1.10)
Installing Flipper-DoubleConversion (1.1.7)
Installing Flipper-Fmt (7.1.7)
Installing Flipper-Folly (2.6.7)
Installing Flipper-Glog (0.3.6)
Installing Flipper-PeerTalk (0.0.4)
Installing Flipper-RSocket (1.4.3)
Installing FlipperKit (0.75.1)
Installing OpenSSL-Universal (1.1.180)
Installing RCT-Folly (2020.01.13.00)
Installing RCTRequired (0.64.0)
Installing RCTTypeSafety (0.64.0)
Installing React (0.64.0)
Installing React-Core (0.64.0)
Installing React-CoreModules (0.64.0)
Installing React-RCTActionSheet (0.64.0)
Installing React-RCTAnimation (0.64.0)
Installing React-RCTBlob (0.64.0)
Installing React-RCTImage (0.64.0)
Installing React-RCTLinking (0.64.0)
Installing React-RCTNetwork (0.64.0)
Installing React-RCTSettings (0.64.0)
Installing React-RCTText (0.64.0)
Installing React-RCTVibration (0.64.0)
Installing React-callinvoker (0.64.0)
Installing React-cxxreact (0.64.0)
Installing React-jsi (0.64.0)
Installing React-jsiexecutor (0.64.0)
Installing React-jsinspector (0.64.0)
Installing React-perflogger (0.64.0)
Installing React-runtimeexecutor (0.64.0)
Installing ReactCommon (0.64.0)
Installing Yoga (1.14.0)
Installing YogaKit (1.18.1)
Installing boost-for-react-native (1.63.0)
Installing glog (0.3.5)
Installing libevent (2.1.12)
Installing razorpay-pod (1.1.12)
Installing react-native-razorpay (2.2.4)
```

### React nativer version 4.13.0
Mac OS 11.2.3
npm - 7.11.2
node - v14.4.0

Any help is appreciated

**Comment by mevluttuna** [comment]
Change that first in PodFile:

`use_flipper!()` to
`use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })`

Then change it end of the PodFile: 
`post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
        react_native_post_install(installer)
      end
    end
  end`

After this process: 
`cd ios`
`pod cache clean`
`pod install --repo-update`
`cd .. && yarn start --reset-cache`

**Comment by jitunayak** [comment]
> Change that first in PodFile:
> 
> `use_flipper!()` to
> `use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })`
> 
> Then change it end of the PodFile:
> `post_install do |installer| installer.pods_project.targets.each do |target| target.build_configurations.each do |config| config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0' react_native_post_install(installer) end end end`
> 
> After this process:
> `cd ios`
> `pod cache clean --all`
> `pod install --repo-update`
> `cd .. && yarn start --reset-cache`

I am very grateful for your comment. Thank you so much! it worked for me
