### ISSUE TITLE
Android treating DateTime strings without timezone information as UTC.  iOS treats as Local.

### ISSUE THREAD

**Issue by badbod99** [facebook/react-native#31483]
## Description

When creating a DateTime object using a string without timezone information (e.g. taking a user entered date and/or time), Android treats the passed string as UTC, iOS treats the passed string as local.  This results in difficulty managing user entered dates and times consistently between platforms.

This works correctly in a Web Browser on both Android and iOS devices.

Same issue occurs when using other timezones (e.g. IST, +5.30).  Android treats the DateTime string as UTC, iOS treats the string as local.

## Devices tested with

iPhone 12 (iOS 14)
Huawei P20 Pro (Android 10)

## React Native version:

System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Memory: 3.63 GB / 15.92 GB
  Binaries:
    Node: 14.15.2 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.9 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.8.31019.35 (Visual Studio Professional 2019), 15.9.28307.812 (Visual Studio Professional 2017)
  Languages:
    Java: Not Found
    Python: 3.9.1
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Use an Android device with timezone set to BST (British Summer Time).
2. Create a simple DateTime object with a date time string without timezone information within summer time (e.g. 2021-06-05T13:55)
3. Show the date using .toISOString().
4. Perform the same steps on Apple iPhone device.

## Expected Results

Created DateTime object to represent passed DateTime string as local on both Android and iOS.  This is the same as JavaScript handles these strings in the browser (Chrome on Android, Safari on iOS).

## Actual Results

Created DateTime object on Android treats passed value as UTC.  I.e. 2021-06-05T13:55:00.000Z
Created DateTime object on iPhone treats passed value as Local (BST). I.e. 2021-06-05T12:55:00.000Z

Created 

## Snack, code example, screenshot, or link to a repository:

https://snack.expo.io/@badbod99/petrified-bananas

**Comment by ravirajn22** [comment]
Duplicate of https://github.com/facebook/react-native/issues/30245

**Comment by badbod99** [comment]
@ravirajn22 - I don't this is a duplicate really.  That issue has been closed without any resolution.  As mentioned in my issue above, this works correctly on the web browser on both iOS and Android, but not in React Native, so this is something wrong with React Native javascript usage for Android.

**Comment by omonk** [comment]
@badbod99 - Did you work this out?

**Comment by DevWarr** [comment]
I can confirm I'm getting the same issue as @badbod99. I can't confirm any correct formatting on browser or iOS, but on Android I'm seeing the same invalid date format.

Using:

expo: "~47.0.9"
react-native: "0.70.8"

I did note - it looks like `toLocaleDateString()` works well, but `.toLocaleString()` and `toLocaleTimeString()` do not.

Code example:
```ts
const dateFormatOptions: Intl.DateTimeFormatOptions = {
  year: "2-digit",
  month: "2-digit",
  day: "2-digit",
  hour: "2-digit",
  minute: "2-digit",
}

const date = new Date("2023-04-21T02:31:22.267Z")
console.log(date.toLocaleString("en-US", dateFormatOptions))      // → Thu Apr 20 21:31:22 2023
console.log(date.toLocaleDateString("en-US", dateFormatOptions))  // → 04/20/23
console.log(date.toLocaleTimeString("en-US", dateFormatOptions))  // → 21:31:22
```

**Comment by Robin-JW** [comment]
```
const dateIn = '2027-10-13T23:59:59';
const date = new Date(dateIn);
console.debug(`[0.63.5] ${Platform.OS}  dateIn:   ${dateIn}`);
console.debug(`[0.63.5] ${Platform.OS}  date:     ${date}`);
console.debug(`[0.63.5] ${Platform.OS}  timstamp: ${date.getTime()}`);
```

output
```
[0.63.5] android  dateIn:   2027-10-13T23:59:59
[0.63.5] android  date:     Thu Oct 14 2027 07:59:59 GMT+0800 (CST)
[0.63.5] android  timstamp: 1823471999000
[0.63.5] ios  dateIn:   2027-10-13T23:59:59
[0.63.5] ios  date:     Wed Oct 13 2027 23:59:59 GMT+0800 (中国标准时间)
[0.63.5] ios  timstamp: 1823443199000

[0.70.1] ios  dateIn:   2027-10-13T23:59:59
[0.70.1] ios  date:     Wed Oct 13 2027 23:59:59 GMT+0800
[0.70.1] ios  timstamp: 1823443199000
[0.70.1] android  dateIn:   2027-10-13T23:59:59
[0.70.1] android  date:     Wed Oct 13 2027 23:59:59 GMT+0800
[0.70.1] android  timstamp: 1823443199000

```
