### ISSUE TITLE
Typo on TouchableHighlight page

### ISSUE THREAD

**Issue by pwnsdx** [facebook/react-native#315]
Hi there,

https://facebook.github.io/react-native/docs/touchablehighlight.html#content

TouchableHighlight tag is not closed properly.

Cordially,
S.

**Comment by sahrens** [comment]
Feel free to send a PR :)

**Comment by pwnsdx** [comment]
No problem! ;)

**Comment by pwnsdx** [comment]
While looking in PRs, I just saw that there is already one about this: https://github.com/facebook/react-native/pull/292 so you just have to accept it

**Comment by spicyj** [comment]
Closing for #292.
