### ISSUE TITLE
0.64-stable/Libraries/FBReactNativeSpec NotFound?

### ISSUE THREAD

**Issue by Jorgezz** [facebook/react-native#31511]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Please provide a clear and concise description of what the bug is. Include screenshots if needed.
Please test using the latest React Native release to make sure your issue has not already been fixed: https://reactnative.dev/docs/upgrading.html

## React Native version:
Run `react-native info` in your terminal and copy the results here.

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.
https://github.com/facebook/react-native/tree/0.64-stable/Libraries/FBReactNativeSpec
1. ROOT yarn install
2. packages/rn-tester yarn install && bundle exec pod install --repo-update
3. you will found Pods folders no  FBReactNativeSpec source code has been generated.

tempory solution:
1. copy 0.63-stable Libraries/FBReactNativeSpec directory to 0.64-stable or 0.65-stable directory;
2. if encounter a error : $HOME/.nvm/nvm.sh return staus 3 ,then try #source "$RN_DIR/scripts/find-node.sh" delete check of nvm in generate-specs.sh file;
3. retry and good luck !

## Expected Results
Describe what you expected to happen.

## Snack, code example, screenshot, or link to a repository:
Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by Jorgezz** [comment]
alraedy resolved by run `sh $HOME/.nvm/nvm.sh | echo $?` and return status 0.

**Comment by Jorgezz** [comment]
https://github.com/nvm-sh/nvm/issues/1985

> alraedy resolved by run `sh $HOME/.nvm/nvm.sh | echo $?` and return status 0.

**Comment by charleston10** [comment]
instead
`pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"`
to
`pod 'FBReactNativeSpec', :path => "../node_modules/react-native/React/FBReactNativeSpec"`
