### ISSUE TITLE
Cant use react-native run-ios --device to run app on a real ios device 

### ISSUE THREAD

**Issue by EatherToo** [facebook/react-native#31514]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Cant use react-native run-ios --device to run app on a real ios device.
**but there is a device have already connected to my mac**.
![image](https://user-images.githubusercontent.com/22785612/117934317-21677900-b335-11eb-97c7-733543816783.png)

## React Native version:
```shell
info Fetching system and libraries information...
System:
    OS: macOS 11.2.3
    CPU: (8) x64 Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz
    Memory: 1.84 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.17.0/bin/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 26, 28, 29, 30
      Build Tools: 26.0.0, 28.0.3, 29.0.2, 29.0.3, 30.0.2, 31.0.0
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6858069
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_272 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.1 => 0.64.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

```
xcode version: 12.5

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. create a react-native project
2. use command `npx react-native run-ios --device` to run app on a device

## Expected Results
Cant use react-native run-ios --device to run app on a real ios device.
display `error Could not find a device named: "iPhone11". Available devices:`

## Snack, code example, screenshot, or link to a repository:
![image](https://user-images.githubusercontent.com/22785612/117934317-21677900-b335-11eb-97c7-733543816783.png)

**Comment by 1280103995** [comment]
Try  to run ```yarn ios --device```

**Comment by EatherToo** [comment]
> Try to run `yarn ios --device`

had tried, also useless

**Comment by b3coded** [comment]
@EatherToo you can try the solution described here: https://github.com/react-native-community/cli/issues/1404#issuecomment-829496819

it worked for me
