### ISSUE TITLE
FlatList getItemLayout scroll jumps with dynamic heights

### ISSUE THREAD

**Issue by rrebase** [facebook/react-native#31510]
## Description
Implemented `getItemLayout` for a large list with dynamic heights in order to scroll outside of the render window with `scrollToIndex`, but the scrolling starts jumping when scrolling past the midpoint of a large list.

Likely related if the issue is with `VirtualizedList`: https://github.com/facebook/react-native/issues/31163

Seems like a 🐛 as the small amount of docs that exist for `getItemLayout` suggest that this is a valid use case.

## React Native version:
```
"react-native": "0.64.1"
```

## Steps To Reproduce
1. Create a `FlatList` with `getItemLayout` that has dynamic heights & a large amount of rows
2. Scroll to the bottom part of the list until you see the scroll position unexpectedly jump back to the top part of the list

## Expected Results
Scrolling the list past the 300th row in the Snack on iOS device does not jump back to 150th row & there's no flickering.

## Snack:
https://snack.expo.io/HQaYpJjAn (100% reproducable on iOS device)

**Comment by heyItsRDomi** [comment]
I've encountered the same issue (IOS and Android).

React Native Version: 0.66.5

**Comment by agunbuhori** [comment]
> ## Description
> Implemented `getItemLayout` for a large list with dynamic heights in order to scroll outside of the render window with `scrollToIndex`, but the scrolling starts jumping when scrolling past the midpoint of a large list.
> 
> Likely related if the issue is with `VirtualizedList`: #31163
> 
> Seems like a 🐛 as the small amount of docs that exist for `getItemLayout` suggest that this is a valid use case.
> 
> ## React Native version:
> ```
> "react-native": "0.64.1"
> ```
> 
> ## Steps To Reproduce
> 1. Create a `FlatList` with `getItemLayout` that has dynamic heights & a large amount of rows
> 2. Scroll to the bottom part of the list until you see the scroll position unexpectedly jump back to the top part of the list
> 
> ## Expected Results
> Scrolling the list past the 300th row in the Snack on iOS device does not jump back to 150th row & there's no flickering.
> 
> ## Snack:
> https://snack.expo.io/HQaYpJjAn (100% reproducable on iOS device)

only works for static heights, and is problematic if each items height is different
