### ISSUE TITLE
Build failing randomly

### ISSUE THREAD

**Issue by slxsh** [facebook/react-native#31515]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
My project was working fine last time I checked. However, I am unable to build it now and I don't think I changed anything in my project. This is the error message
* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all dependencies for configuration ':app:debugRuntimeClasspath'.
   > Problems reading data from Binary store in C:\Users\abcd\AppData\Local\Temp\gradle3330051715056052591.bin offset 88368 exists? true

I looked at similar questions on StackOverflow and couldn't find anything useful except that this happens randomly.
A few days ago the build started failing (something about mergeDexDebug) randomly and restarting the computer somehow fixed it.

## React Native version:
System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 8.66 GB / 15.85 GB
  Binaries:
    Node: 12.13.0 - C:\Program Files\nodejs\node.EXE      
    Yarn: Not Found
    npm: 7.5.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 14, 26, 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: Not Found
  Languages:
    Java: Not Found
    Python: 3.8.0 - C:\Users\abcd\AppData\Local\Programs\Python\Python38-32\python.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.4 => 0.63.4
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
I am not sure how this can be reproduced because it was working just fine.

## Expected Results
Build should not fail

## Snack, code example, screenshot, or link to a repository:
-

**Comment by slxsh** [comment]
Ok, so I was able to build successfully by changing `firebaseMessagingVersion = "+"` to `firebaseMessagingVersion = "21.1.0"` in `android/build.gradle` but I still don't understand how this was working all along and stopped today. Also, I have `googlePlayServicesVersion = "+"` this in build.gradle. Should I change this one too?

**Comment by MatthiasDh** [comment]
@slxsh we had a similar issue in our project. firebase messaging got a breaking change and because you have '+' it auto updated firebase messaging. By doing this you probably installed the new update of firebase messaging that has breaking changes.

**Comment by bpsourav21** [comment]
```
* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all dependencies for configuration ':app:debugCompileClasspath'.
   > Problems reading data from Binary store in C:\Users\sourav\AppData\Local\Temp\gradle7627481342141045842.bin offset 125802 exists? true
 ```
I am getting this error from yesterday and It is barely building my app. I am using `gradle-6.2-all.zip`

here is my `..\android\build.gradle` file
```
buildscript {
    ext {
        buildToolsVersion = "29.0.3"
        minSdkVersion = 21
        compileSdkVersion = 29
        targetSdkVersion = 29

        googlePlayServicesIidVersion = "16.0.1"
        firebaseMessagingVersion = "21.1.0"
        playServicesVersion = "17.0.0" 
        androidMapsUtilsVersion = "2.2.1"
    }
    repositories {
        google()
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:3.5.4")
        classpath('com.google.gms:google-services:4.3.3')
    }
}

allprojects {
    repositories {
        mavenLocal()
        maven {
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        google()
        jcenter()
        maven { url 'https://www.jitpack.io' }
    }
}
```
Anyone can suggest how can I fix my build issue and what might be the problem here?
