### ISSUE TITLE
[!] No podspec found for `React-DevSupport` in `../node_modules/react-native/`

### ISSUE THREAD

**Issue by gmartpad** [facebook/react-native#31519]
## Description
After "npm install", I went to the ios folder and executed "pod install" and this happened:

![image](https://user-images.githubusercontent.com/44455190/118025494-50cab580-b336-11eb-8f01-5a67822050dd.png)

## React Native version:
"react-native": "^0.64.0"

## Steps To Reproduce
 1. > on the project's folder, execute "npm install"
 2. > go to the "ios" folder
 3. > execute "pod install"

## Expected Results
a successful pod install.

## Snack, code example, screenshot, or link to a repository:

- package.json 

`
{
  "name": "blandAppName",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "@react-native-community/async-storage": "^1.12.1",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-community/progress-bar-android": "^1.0.4",
    "@react-native-community/progress-view": "^1.2.3",
    "@react-native-community/viewpager": "^3.3.0",
    "@react-native-picker/picker": "^1.15.0",
    "@types/react-navigation": "^2.0.23",
    "axios": "^0.21.1",
    "base-64": "^0.1.0",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-react-native": "^3.3.0",
    "he": "^1.2.0",
    "immutable": "^3.8.2",
    "linkify-it": "^3.0.2",
    "moment": "^2.22.2",
    "native-base": "^2.8.1",
    "prop-types": "^15.6.2",
    "react": "^16.12.0",
    "react-dom": "^15.6.2",
    "react-native": "^0.64.0",
    "react-native-calendars": "^1.21.0",
    "react-native-camera": "3.43.6",
    "react-native-css-vh-vw": "^1.0.5",
    "react-native-device-info": "^5.3.1",
    "react-native-dropdown-picker": "4.0.9",
    "react-native-fast-image": "^8.3.4",
    "react-native-firebase": "5.5.6",
    "react-native-gesture-handler": "^1.4.0",
    "react-native-hyperlink": "0.0.19",
    "react-native-keyboard-aware-scroll-view": "^0.8.0",
    "react-native-masked-text": "^1.9.1",
    "react-native-pdf": "^5.1.7",
    "react-native-reanimated": "1.10.1",
    "react-native-render-html": "^5.1.0",
    "react-native-safe-area-context": "^3.1.9",
    "react-native-screens": "2.0.0",
    "react-native-vector-icons": "6.5.0",
    "react-native-view-pdf": "^0.10.2",
    "react-native-webview": "^8.2.1",
    "react-navigation": "^4.4.3",
    "react-navigation-drawer": "^2.6.0",
    "react-navigation-stack": "^2.10.2",
    "react-number-format": "^4.0.8",
    "react-redux": "^5.0.7",
    "react-timer-mixin": "^0.13.4",
    "redux": "^4.0.0",
    "redux-saga": "^0.16.0",
    "rn-fetch-blob": "0.10.15",
    "styled-components": "^5.2.1"
  },
  "devDependencies": {
    "@babel/core": "^7.4.5",
    "@babel/runtime": "^7.4.5",
    "babel-eslint": "^10.0.1",
    "babel-jest": "^24.8.0",
    "eslint": "^5.6.1",
    "eslint-plugin-babel": "^5.2.1",
    "eslint-plugin-jsx-a11y": "^6.1.1",
    "eslint-plugin-react": "^7.11.1",
    "jest": "^24.8.0",
    "jetifier": "^1.6.6",
    "metro-react-native-babel-preset": "^0.54.1",
    "react-test-renderer": "16.8.3"
  },
  "jest": {
    "preset": "react-native"
  }
}

`
- Podfile

`
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '9.0'

target 'blandAppName' do

  config = use_native_modules!
  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false
  )

  rn_path = '../node_modules/react-native'
  rn_maps_path = '../node_modules/react-native-maps'

  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-DevSupport', :path => '../node_modules/react-native/'
  pod 'React-fishhook', :path => '../node_modules/react-native/Libraries/fishhook'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-RCTWebSocket', :path => '../node_modules/react-native/Libraries/WebSocket/'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  
  pod 'Yoga', path: "#{rn_path}/ReactCommon/yoga"
  pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
  pod 'RCT-Folly', :podspec => "#{rn_path}/third-party-podspecs/RCT-Folly.podspec"
  pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"
  

  
  pod 'Firebase'
  pod 'GoogleAppMeasurement', '= 5.4.0'
  pod 'FirebaseAnalytics', '= 5.4.0'
  pod 'Firebase/Core'
  pod 'Firebase/Database', '= 5.15.0'
  pod 'Firebase/Messaging'
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'
  
  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'
  
  pod 'RNCMaskedView', :path => '../node_modules/@react-native-community/masked-view'
  
  pod 'react-native-viewpager', :path => '../node_modules/@react-native-community/viewpager'
  
  pod 'react-native-camera', :path => '../node_modules/react-native-camera'
  
  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
  
  pod 'RNFastImage', :path => '../node_modules/react-native-fast-image'
  
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
  
  pod 'react-native-pdf', :path => '../node_modules/react-native-pdf'
  
  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'
  
  pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'
  
  pod 'RNScreens', :path => '../node_modules/react-native-screens'
  
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  
  pod 'RNPDF', :path => '../node_modules/react-native-view-pdf'
  
  pod 'react-native-webview', :path => '../node_modules/react-native-webview'
  
  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'
  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == "React"
        target.remove_from_project
      end
      if target.name == 'yoga'
        target.remove_from_project
        target.build_configurations.each do |config|
            config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
            config.build_settings['GCC_WARN_64_TO_32_BIT_CONVERSION'] = 'NO'
        end
      end
    end
  end

end
`

- Podfile.lock

`
PODS:
  - boost-for-react-native (1.63.0)
  - DoubleConversion (1.1.6)
  - Firebase (5.15.0):
    - Firebase/Core (= 5.15.0)
  - Firebase/Core (5.15.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (= 5.4.0)
  - Firebase/CoreOnly (5.15.0):
    - FirebaseCore (= 5.1.10)
  - Firebase/Database (5.15.0):
    - Firebase/CoreOnly
    - FirebaseDatabase (= 5.0.4)
  - Firebase/Messaging (5.15.0):
    - Firebase/CoreOnly
    - FirebaseMessaging (= 3.2.2)
  - FirebaseAnalytics (5.4.0):
    - FirebaseCore (~> 5.1)
    - FirebaseInstanceID (~> 3.3)
    - GoogleAppMeasurement (= 5.4.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 5.2)
    - GoogleUtilities/MethodSwizzler (~> 5.2)
    - GoogleUtilities/Network (~> 5.2)
    - "GoogleUtilities/NSData+zlib (~> 5.2)"
    - nanopb (~> 0.3)
  - FirebaseAnalyticsInterop (1.5.0)
  - FirebaseAuthInterop (1.1.0)
  - FirebaseCore (5.1.10):
    - GoogleUtilities/Logger (~> 5.2)
  - FirebaseDatabase (5.0.4):
    - FirebaseAuthInterop (~> 1.0)
    - FirebaseCore (~> 5.1)
    - leveldb-library (~> 1.18)
  - FirebaseInstanceID (3.3.0):
    - FirebaseCore (~> 5.1)
    - GoogleUtilities/Environment (~> 5.3)
    - GoogleUtilities/UserDefaults (~> 5.3)
  - FirebaseMessaging (3.2.2):
    - FirebaseAnalyticsInterop (~> 1.1)
    - FirebaseCore (~> 5.1)
    - FirebaseInstanceID (~> 3.0)
    - GoogleUtilities/Environment (~> 5.2)
    - GoogleUtilities/Reachability (~> 5.2)
    - Protobuf (~> 3.1)
  - FLAnimatedImage (1.0.12)
  - Folly (2018.10.22.00):
    - boost-for-react-native
    - DoubleConversion
    - glog
  - glog (0.3.5)
  - GoogleAppMeasurement (5.4.0):
    - GoogleUtilities/AppDelegateSwizzler (~> 5.2)
    - GoogleUtilities/MethodSwizzler (~> 5.2)
    - GoogleUtilities/Network (~> 5.2)
    - "GoogleUtilities/NSData+zlib (~> 5.2)"
    - nanopb (~> 0.3)
  - GoogleUtilities/AppDelegateSwizzler (5.8.0):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
  - GoogleUtilities/Environment (5.8.0)
  - GoogleUtilities/Logger (5.8.0):
    - GoogleUtilities/Environment
  - GoogleUtilities/MethodSwizzler (5.8.0):
    - GoogleUtilities/Logger
  - GoogleUtilities/Network (5.8.0):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (5.8.0)"
  - GoogleUtilities/Reachability (5.8.0):
    - GoogleUtilities/Logger
  - GoogleUtilities/UserDefaults (5.8.0):
    - GoogleUtilities/Logger
  - leveldb-library (1.22)
  - libwebp (1.1.0):
    - libwebp/demux (= 1.1.0)
    - libwebp/mux (= 1.1.0)
    - libwebp/webp (= 1.1.0)
  - libwebp/demux (1.1.0):
    - libwebp/webp
  - libwebp/mux (1.1.0):
    - libwebp/demux
  - libwebp/webp (1.1.0)
  - nanopb (0.3.9011):
    - nanopb/decode (= 0.3.9011)
    - nanopb/encode (= 0.3.9011)
  - nanopb/decode (0.3.9011)
  - nanopb/encode (0.3.9011)
  - Protobuf (3.14.0)
  - React (0.59.9):
    - React/Core (= 0.59.9)
  - react-native-camera (3.0.0):
    - React
    - react-native-camera/RCT (= 3.0.0)
    - react-native-camera/RN (= 3.0.0)
  - react-native-camera/RCT (3.0.0):
    - React
  - react-native-camera/RN (3.0.0):
    - React
  - react-native-fast-image (5.4.2):
    - FLAnimatedImage (~> 1)
    - React
    - SDWebImage/Core (~> 4)
    - SDWebImage/GIF (~> 4)
    - SDWebImage/WebP (~> 4)
  - react-native-pdf (5.0.9):
    - React
  - react-native-safe-area-context (3.1.9):
    - React/Core
  - react-native-viewpager (3.3.0):
    - React
  - react-native-webview (8.2.1):
    - React
  - React/Core (0.59.9):
    - yoga (= 0.59.9.React)
  - React/CxxBridge (0.59.9):
    - Folly (= 2018.10.22.00)
    - React/Core
    - React/cxxreact
    - React/jsiexecutor
  - React/cxxreact (0.59.9):
    - boost-for-react-native (= 1.63.0)
    - DoubleConversion
    - Folly (= 2018.10.22.00)
    - glog
    - React/jsinspector
  - React/DevSupport (0.59.9):
    - React/Core
    - React/RCTWebSocket
  - React/fishhook (0.59.9)
  - React/jsi (0.59.9):
    - DoubleConversion
    - Folly (= 2018.10.22.00)
    - glog
  - React/jsiexecutor (0.59.9):
    - DoubleConversion
    - Folly (= 2018.10.22.00)
    - glog
    - React/cxxreact
    - React/jsi
  - React/jsinspector (0.59.9)
  - React/RCTActionSheet (0.59.9):
    - React/Core
  - React/RCTAnimation (0.59.9):
    - React/Core
  - React/RCTBlob (0.59.9):
    - React/Core
  - React/RCTGeolocation (0.59.9):
    - React/Core
  - React/RCTImage (0.59.9):
    - React/Core
    - React/RCTNetwork
  - React/RCTLinkingIOS (0.59.9):
    - React/Core
  - React/RCTNetwork (0.59.9):
    - React/Core
  - React/RCTSettings (0.59.9):
    - React/Core
  - React/RCTText (0.59.9):
    - React/Core
  - React/RCTVibration (0.59.9):
    - React/Core
  - React/RCTWebSocket (0.59.9):
    - React/Core
    - React/fishhook
    - React/RCTBlob
  - rn-fetch-blob (0.10.6):
    - React/Core
  - RNCAsyncStorage (1.7.1):
    - React
  - RNCMaskedView (0.1.10):
    - React
  - RNDeviceInfo (5.4.1):
    - React
  - RNFirebase (5.5.0):
    - Firebase/Core
    - React
  - RNGestureHandler (1.4.0):
    - React
  - RNPDF (0.10.1):
    - React
  - RNReanimated (1.10.0):
    - React
  - RNScreens (2.0.0):
    - React
  - RNVectorIcons (6.6.0):
    - React
  - SDWebImage/Core (4.4.8)
  - SDWebImage/GIF (4.4.8):
    - FLAnimatedImage (~> 1.0)
    - SDWebImage/Core
  - SDWebImage/WebP (4.4.8):
    - libwebp (< 2.0, >= 0.5)
    - SDWebImage/Core
  - yoga (0.59.9.React)

DEPENDENCIES:
  - DoubleConversion (from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`)
  - Firebase
  - Firebase/Core
  - Firebase/Database (= 5.15.0)
  - Firebase/Messaging
  - FirebaseAnalytics (= 5.4.0)
  - Folly (from `../node_modules/react-native/third-party-podspecs/Folly.podspec`)
  - glog (from `../node_modules/react-native/third-party-podspecs/glog.podspec`)
  - GoogleAppMeasurement (= 5.4.0)
  - react-native-camera (from `../node_modules/react-native-camera`)
  - react-native-fast-image (from `../node_modules/react-native-fast-image`)
  - react-native-pdf (from `../node_modules/react-native-pdf`)
  - react-native-safe-area-context (from `../node_modules/react-native-safe-area-context`)
  - "react-native-viewpager (from `../node_modules/@react-native-community/viewpager`)"
  - react-native-webview (from `../node_modules/react-native-webview`)
  - React/Core (from `../node_modules/react-native`)
  - React/CxxBridge (from `../node_modules/react-native`)
  - React/DevSupport (from `../node_modules/react-native`)
  - React/RCTActionSheet (from `../node_modules/react-native`)
  - React/RCTAnimation (from `../node_modules/react-native`)
  - React/RCTGeolocation (from `../node_modules/react-native`)
  - React/RCTImage (from `../node_modules/react-native`)
  - React/RCTLinkingIOS (from `../node_modules/react-native`)
  - React/RCTNetwork (from `../node_modules/react-native`)
  - React/RCTSettings (from `../node_modules/react-native`)
  - React/RCTText (from `../node_modules/react-native`)
  - React/RCTVibration (from `../node_modules/react-native`)
  - React/RCTWebSocket (from `../node_modules/react-native`)
  - rn-fetch-blob (from `../node_modules/rn-fetch-blob`)
  - "RNCAsyncStorage (from `../node_modules/@react-native-community/async-storage`)"
  - "RNCMaskedView (from `../node_modules/@react-native-community/masked-view`)"
  - RNDeviceInfo (from `../node_modules/react-native-device-info`)
  - RNFirebase (from `../node_modules/react-native-firebase/ios`)
  - RNGestureHandler (from `../node_modules/react-native-gesture-handler`)
  - RNPDF (from `../node_modules/react-native-view-pdf`)
  - RNReanimated (from `../node_modules/react-native-reanimated`)
  - RNScreens (from `../node_modules/react-native-screens`)
  - RNVectorIcons (from `../node_modules/react-native-vector-icons`)
  - yoga (from `../node_modules/react-native/ReactCommon/yoga`)

SPEC REPOS:
  trunk:
    - boost-for-react-native
    - Firebase
    - FirebaseAnalytics
    - FirebaseAnalyticsInterop
    - FirebaseAuthInterop
    - FirebaseCore
    - FirebaseDatabase
    - FirebaseInstanceID
    - FirebaseMessaging
    - FLAnimatedImage
    - GoogleAppMeasurement
    - GoogleUtilities
    - leveldb-library
    - libwebp
    - nanopb
    - Protobuf
    - SDWebImage

EXTERNAL SOURCES:
  DoubleConversion:
    :podspec: "../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec"
  Folly:
    :podspec: "../node_modules/react-native/third-party-podspecs/Folly.podspec"
  glog:
    :podspec: "../node_modules/react-native/third-party-podspecs/glog.podspec"
  React:
    :path: "../node_modules/react-native"
  react-native-camera:
    :path: "../node_modules/react-native-camera"
  react-native-fast-image:
    :path: "../node_modules/react-native-fast-image"
  react-native-pdf:
    :path: "../node_modules/react-native-pdf"
  react-native-safe-area-context:
    :path: "../node_modules/react-native-safe-area-context"
  react-native-viewpager:
    :path: "../node_modules/@react-native-community/viewpager"
  react-native-webview:
    :path: "../node_modules/react-native-webview"
  rn-fetch-blob:
    :path: "../node_modules/rn-fetch-blob"
  RNCAsyncStorage:
    :path: "../node_modules/@react-native-community/async-storage"
  RNCMaskedView:
    :path: "../node_modules/@react-native-community/masked-view"
  RNDeviceInfo:
    :path: "../node_modules/react-native-device-info"
  RNFirebase:
    :path: "../node_modules/react-native-firebase/ios"
  RNGestureHandler:
    :path: "../node_modules/react-native-gesture-handler"
  RNPDF:
    :path: "../node_modules/react-native-view-pdf"
  RNReanimated:
    :path: "../node_modules/react-native-reanimated"
  RNScreens:
    :path: "../node_modules/react-native-screens"
  RNVectorIcons:
    :path: "../node_modules/react-native-vector-icons"
  yoga:
    :path: "../node_modules/react-native/ReactCommon/yoga"

SPEC CHECKSUMS:
  boost-for-react-native: 39c7adb57c4e60d6c5479dd8623128eb5b3f0f2c
  DoubleConversion: bb338842f62ab1d708ceb63ec3d999f0f3d98ecd
  Firebase: 8bb9268bff82374f2cbaaabb143e725743c316ae
  FirebaseAnalytics: c06f9d70577d79074214700a71fd5d39de5550fb
  FirebaseAnalyticsInterop: 3f86269c38ae41f47afeb43ebf32a001f58fcdae
  FirebaseAuthInterop: a0f37ae05833af156e72028f648d313f7e7592e9
  FirebaseCore: 35747502d9e8c6ee217385ad04446c7c2aaf9c5c
  FirebaseDatabase: 0621689f77528d62b47e1c06ca737c4c19275d1a
  FirebaseInstanceID: e2fa4cb35ef5558c200f7f0ad8a53e212215f93e
  FirebaseMessaging: b412996f6a09337d232bb3a6676ce4d1f353d024
  FLAnimatedImage: 4a0b56255d9b05f18b6dd7ee06871be5d3b89e31
  Folly: de497beb10f102453a1afa9edbf8cf8a251890de
  glog: aefd1eb5dda2ab95ba0938556f34b98e2da3a60d
  GoogleAppMeasurement: 98b71f5e04142793729a5ef23e5b96651ff4b70f
  GoogleUtilities: 04fce34bcd5620c1ee76fb79172105c74a4df335
  leveldb-library: 55d93ee664b4007aac644a782d11da33fba316f7
  libwebp: 946cb3063cea9236285f7e9a8505d806d30e07f3
  nanopb: 18003b5e52dab79db540fe93fe9579f399bd1ccd
  Protobuf: 0cde852566359049847168e51bd1c690e0f70056
  React: a86b92f00edbe1873a63e4a212c29b7a7ad5224f
  react-native-camera: fa20f6aa54ce4a84c47e38a2d63dc0f3c18dccf9
  react-native-fast-image: 7278563726f2455ed3ba6e04dea472345173278c
  react-native-pdf: 4a73d6c72ccbc6317df4726f6892b2404c02ff21
  react-native-safe-area-context: 0a52d6d0fd7b5e2250532f648be3d311940f77d0
  react-native-viewpager: 118e65d8c65c56fe48d12a35cdcf1fe7e027a366
  react-native-webview: d3cf75764f98fd433f1222f5a7ca8e355ada2a15
  rn-fetch-blob: 766f85cabd2992300dfa1be2bc9e4e258abc6f04
  RNCAsyncStorage: 8539fc80a0075fcc9c8e2dff84cd22dc5bf1dacf
  RNCMaskedView: f5c7d14d6847b7b44853f7acb6284c1da30a3459
  RNDeviceInfo: 54556486cd02538dbef727f39292d096abe0cf0e
  RNFirebase: d0dfd323dbf52e669dbda8fa86bea8912540f13f
  RNGestureHandler: 71871d4792db2a73f70204483d30350ec9384cbd
  RNPDF: 8a40fafbed2714e7e8fe4e7c9f6f9815f52a939c
  RNReanimated: 347ecd4322f7a5da4c523d289150022433095b9e
  RNScreens: 7704297930777dae13b88bb9f999db17a39bbdf1
  RNVectorIcons: 0bb4def82230be1333ddaeee9fcba45f0b288ed4
  SDWebImage: 783af2c3fa36291a250030c4752ee370a9a51d13
  yoga: 03ff42a6f223fb88deeaed60249020d80c3091ee

PODFILE CHECKSUM: e50848ee04d0edb9ec28bfb0f35255367acd7fec

COCOAPODS: 1.10.1

`

**Comment by rdobda-gaia** [comment]
Wow after making like 20 changes of the various tutorials over the last 5 years that have changed over and over to integrate react native into an existing iOS project (starting with the official obsolete doc and moving through various other 3rd party tutorials over the years with differing nuance) , i reached this one and am blocked. Would be nice if there was an up to date tutorial on how to add react native to an existing ios project that was straightforward.

**Comment by ThalKod** [comment]
@gmartpad Was you able to fix that error ? i'm having the same issue after trying to update a project to react nnative 0.70...

**Comment by MrAdeelBaig** [comment]
delete podfile.lock and then again run yarn and then cd ios && pod install
