### ISSUE TITLE
flatlist horizontal scrollable area height

### ISSUE THREAD

**Issue by nachiketnkulkarni** [facebook/react-native#31527]
After adding flatlist there is some remains space between scrollable container and scrollbar. How to remove it?
![Screenshot 2021-05-15 at 10 25 21 AM](https://user-images.githubusercontent.com/72228360/118337842-c1591880-b568-11eb-8ac2-ab8984754289.png)

expo snack [expo](https://snack.expo.io/@nachiketkulkarni/e9862b)

**Comment by oguzturker8** [comment]
FlastList has default flexGrow: 1 property. You can give flexGrow: 0 to FlatList or just wrap it with plain View.

  <View style={styles.container}>
   <View>
      <FlatList 
         ... 
      />
      </View>
      <Text>Hello</Text>
    </View>
