### ISSUE TITLE
Create new project not run in ios

### ISSUE THREAD

**Issue by iwmdipak** [facebook/react-native#31520]
System:
    OS: macOS 11.3.1
    CPU: (4) x64 Intel(R) Core(TM) i5-4260U CPU @ 1.40GHz
    Memory: 45.98 MB / 4.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.1.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.12.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7322048
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 12.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: ^0.64.1 => 0.64.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

Showing Recent Messages
bash: Native/*******/node_modules/react-native/scripts/../Libraries: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code

![Screenshot 2021-05-13 at 1 22 17 AM](https://user-images.githubusercontent.com/48380809/118036241-f8250800-b389-11eb-903b-7c43bac40c1c.png)

**Comment by chrisozgo99** [comment]
Experiencing same issue with app initialization in xcode

**Comment by iwmdipak** [comment]
@chrisozgo99 
This happened also to me upgrading from 0.63 to 0.64. After trying all solutions with no luck, I found that moving the folder to a directory where the path contain no spaces works and build the app successfully.

**Comment by chrisozgo99** [comment]
@iwmdipak yes I had the same solution. Weird why that is the breaking error but I'm now in a path with no spaces and working fine.
