### ISSUE TITLE
TypeError: Cannot read property 'position' of undefined

### ISSUE THREAD

**Issue by cengoist** [facebook/react-native#31536]
![IMG_3558](https://user-images.githubusercontent.com/46006061/118490042-3160cd80-b726-11eb-9ac9-80fdadfad299.PNG)

Hello, nice software developers. I am developing an application for react native and I get such an error. It does not open on ios and android devices "react-native": "0.61.1", I am using version and "react-navigation": "^ 4.0.8", "react-navigation-stack": "^ 1.9.0", "react-navigation-tabs": "^ 2.11.1", in my versions of Navigation, can anyone help me know their solution?**

**Comment by sanu23kumar** [comment]
Please add your tab navigator code here

**Comment by cengoist** [comment]
`import React from 'react';
import {createAppContainer} from 'react-navigation';
import {Image} from 'react-native';
import { createBottomTabNavigator } from 'react-navigation-tabs';
import routerCars from '../Cars/routerCars';
import routermap from '../map/routermap';
import routerReports from '../reports/routerReports';
import routerSettings from '../setting/routerSettings';
//import * as Animatable from 'react-native-animatable';
// import routerSupport from '../Support/routerSupport';

import {
  learnColour,
  learnColour1,
  learnColour2,
  learnColour3,
  learnColour4,
  learnColour5,
} from './tabbarIcon/images';
// import routerCampaing from '../Cars/routerCampaing';
const TabNavigator = createBottomTabNavigator(
  {
    Motorlar: {
      screen: routerCars,
      path: '/',
      navigationOptions: {
        showLabel: false,
        tabBarIcon: (
          <Image style={{width: 25, height: 25}} source={learnColour} />
        ),
        showIcon: true,
      },
    },
    Harita: {
      screen: routermap,
      path: '/',
      navigationOptions: {
        showLabel: false,
        tabBarIcon: (
          <Image style={{width: 20, height: 20}} source={learnColour1} />
        ),
        showIcon: true,
      },
    },
    Raporlar: {
      screen: routerReports,
      path: '/',
      navigationOptions: {
        showLabel: false,
        tabBarIcon: (
          <Image style={{width: 20, height: 20}} source={learnColour2} />
        ),
        showIcon: true,
      },
    },
   
    Ayarlar: {
      screen: routerSettings,
      path: '/',
      navigationOptions: {
        showLabel: false,
        tabBarIcon: (
          <Image style={{width: 20, height: 20}} source={learnColour3} />
        ),
        showIcon: true,
      },
    },
   
  },
  {
    animationEnabled: true,
    tabBarOptions: {
      style: 'orange',
      indicatorStyle: {
        height: 0,
      },
      activeTintColor: '#f55524',
      tabStyle: {
        backgroundColor: '#f2f2f2',
      },
    },
  },
);
export default createAppContainer(TabNavigator);`

**Comment by cengoist** [comment]
import React from 'react';
       import {createAppContainer} from 'react-navigation';
        import {Image} from 'react-native';
        import {createBottomTabNavigator} from 'react-navigation-tabs';
        import routerCars from '../Cars/routerCars';
        import routermap from '../map/routermap';
        import routerReports from '../reports/routerReports';
        import routerSettings from '../setting/routerSettings';


        import {
        learnColour,
        learnColour1,
        learnColour2,
       learnColour3,
       learnColour4,
      learnColour5,
     } from './tabbarIcon/images';

     const TabNavigator = createBottomTabNavigator(  
     {

     Motorlar: {
      screen: routerCars,
      path: '/',
      navigationOptions: {
        showLabel: false,
        tabBarIcon: (
          <Image style={{width: 25, height: 25}} source={learnColour} />
        ),
        showIcon: true,
      },
    },
    
     Harita: {
      screen: routermap,
      path: '/',
      navigationOptions: {
        showLabel: false,
        tabBarIcon: (
          <Image style={{width: 20, height: 20}} source={learnColour1} />
        ),
        showIcon: true,
      },
    },
    
    Raporlar: {
      screen: routerReports,
      path: '/',
      navigationOptions: {
        showLabel: false,
        tabBarIcon: (
          <Image style={{width: 20, height: 20}} source={learnColour2} />
        ),
        showIcon: true,
      },
    },

    Ayarlar: {
      screen: routerSettings,
      path: '/',
      navigationOptions: {
        showLabel: false,
        tabBarIcon: (
          <Image style={{width: 20, height: 20}} source={learnColour3} />
        ),
        showIcon: true,
      },

    },

  },


  {
          animationEnabled: true,
          tabBarOptions: {
            style: 'orange',
             indicatorStyle: {
              height: 0,
              },
             activeTintColor: '#f55524',
             tabStyle: {
             backgroundColor: '#f2f2f2',
             },
             },
             },
             );
            export default createAppContainer(TabNavigator);

**Comment by cengoist** [comment]
**I redirect from this page, this page works after the user logs in to all pages. When I run this page, I get that error. When I run the pages it redirects one by one, I don't get any errors.**
