### ISSUE TITLE
android Unknown (SIGSEGV) issue 

### ISSUE THREAD

**Issue by ghadeeraqraa1992** [facebook/react-native#31533]
## Description
I got  Unknown (SIGSEGV) issue on my production version installed from google play.

## React Native version:
 OS: macOS 11.2.2
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 171.89 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.14.1 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 23.0.1, 25.0.2, 28.0.3, 29.0.2, 29.0.3, 30.0.0
      System Images: android-28 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_231 - /usr/bin/javac
    Python: 2.7.15 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found

## logs from sentry 
OS Version: Android 10 (AL2522-Merlin-V101-Q-0223)
Report Version: 104

Exception Type: Unknown (SIGSEGV)

Application Specific Information:
Segfault

Thread 0 Crashed:
0   libjsc.so                       0x72950c9748        <unknown> + 492126902088
1   libjsc.so                       0x7295115fec        <unknown> + 492127215596
2   libjsc.so                       0x72951010ac        <unknown> + 492127129772
3   libjsc.so                       0x729510b488        <unknown> + 492127171720
4   libjsc.so                       0x729510b010        <unknown> + 492127170576
5   libjsc.so                       0x72951cd9c8        <unknown> + 492127967688
6   libjsc.so                       0x72951cae94        <unknown> + 492127956628
7   libjsc.so                       0x72951cb6c0        <unknown> + 492127958720
8   libjsc.so                       0x72951b61a4        <unknown> + 492127871396
9   libjsc.so                       0x72955e91f0        <unknown> + 492132274672
10  libjsc.so                       0x72955e9954        <unknown> + 492132276564
11  libjsc.so                       0x72955dfe80        <unknown> + 492132236928
12  libjsc.so                       0x72955ed088        <unknown> + 492132290696
13  libjsc.so                       0x7295618dcc        <unknown> + 492132470220
14  libc.so                         0x738d140618        <unknown> + 496288138776
15  libc.so                         0x738d0e1e9c        <unknown> + 496287751836
16  <unknown>                       0x0                 <unknown>

## Steps To Reproduce
no steps 

## Expected Results
no issues

**Comment by ghadeeraqraa1992** [comment]
any updates ?

**Comment by JackClown** [comment]
+1

**Comment by cortinico** [comment]
Coud you provide a reproducer of any form? If not, we would have to close this as it's essentially impossible to debug.
