### ISSUE TITLE
[Android] Fetch takes so much time to call simple api

### ISSUE THREAD

**Issue by pqminh** [facebook/react-native#31539]
## Description
Fetch takes so much time to call simple api. Over 60s

<img width="746" alt="Screen Shot 2021-05-17 at 23 24 25" src="https://user-images.githubusercontent.com/13993984/118523218-1febe580-b767-11eb-8a85-1216a681a830.png">
<img width="300" alt="Screen Shot 2021-05-17 at 23 22 43" src="https://user-images.githubusercontent.com/13993984/118523225-224e3f80-b767-11eb-84ef-7de816e82e0f.png">

## React Native version:
react: 17.0.1 => 17.0.1 
react-native: 0.64.0 => 0.64.0 
Android 10 (debug & release mode)

## Steps To Reproduce
let startTime = new Date();
      console.log('startTime', startTime.toLocaleString());
      fetch('https://reactnative.dev/movies.json')
        .then(response => response.json())
        .then(json => {
          let endTime = new Date();
          console.log('endTime', endTime.toLocaleString());
          console.log('duration', endTime - startTime);
          return json.movies;
        })
        .catch(error => {
          console.error(error);
        });

I also try to use axios, xhr but still got this issue. Please help!
repo: https://github.com/pqminh/android-takes-much-time-to-call-api

**Comment by sanu23kumar** [comment]
You are not writing fetch as intended in your repo.
Please write your fetch logic in a useEffect(() => {//your code}, [])
In the App function above the return statement and post your results again.

**Comment by pqminh** [comment]
Only for demo. Pls check App.js file.
TKS!!

**Comment by sanu23kumar** [comment]
I did @pqminh, that's why I requested you to move it to the correct place. Right now I've no idea what lifecycle your code is going to follow outside of the app function. It needs to be inside the app function.

**Comment by pqminh** [comment]
Tks for your reply!
This issue was gone!
Maybe due to my network or datetime sync macos & android
