### ISSUE TITLE
ToolbarAndroid and Navigator

### ISSUE THREAD

**Issue by gebhart** [facebook/react-native#3153]
Hi,

I want to use the Navigator with a NavigationBar with native look and feel on Android. I haven chosen ToolbarAndroid as NavigationBar. Is this the right way to combine Navigator with ToolbarAndroid? Or is it only possible to choose either or? 

Regards,

Michael

**Comment by satya164** [comment]
There is `Navigator.NavigationBar`.

**Comment by brentvatne** [comment]
Hi there! This kind of question is best suited for StackOverflow -- unless you determine that there is a bug then we try to direct questions over there because we have limited resources to spend on issues.

**Comment by alvaromb** [comment]
Related question in SO: http://stackoverflow.com/questions/33808922/react-native-using-toolbarandroid-with-navigators-navigationbar
