### ISSUE TITLE
Text Strings must be rendered within a <Text> component

### ISSUE THREAD

**Issue by dhillm920** [facebook/react-native#31534]
![Screenshot (20)](https://user-images.githubusercontent.com/71113936/118394827-55011680-b647-11eb-95aa-5f538e67aa25.png)

**Comment by DOCSPLOIT** [comment]
Check that you're imported the right Text component.

`import {Text} from 'react-native'`

**Comment by sanu23kumar** [comment]
Your emulator error is because of you deleting the Subslide file.

**Comment by eqlion** [comment]
Apart from advices above, make sure you don't have any `{" "}` or `{"\n"}` in the JSX you return in your components. They may appear after VSCode autoformatting.

**Comment by sangameshrently** [comment]
Can you post exact component ?
