### ISSUE TITLE
PermissionsAndroid don't show custom title and message .

### ISSUE THREAD

**Issue by Saurabhreactninja** [facebook/react-native#31547]
In react version 0.62 
I am calling PermissionsAndroid with custom message and title but app just show the default message. I am using the code given below.
const requestLocationPermission = async () => {
  try {
    const granted = await PermissionsAndroid.request(
      PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION,
      {
        title: "LocationPermission",
        message:
          "Our app need to access your location" +
          "so that we can use to separate photo on asset .",
        buttonNeutral: "Ask Me Later",
        buttonNegative: "Cancel",
        buttonPositive: "OK"
      }
    );
    if (granted === PermissionsAndroid.RESULTS.GRANTED) {
      console.log("You can use the location");
    } else {
      console.log("Location permission denied");
    }
  } catch (err) {
    console.warn(err);
  }
};

**Comment by Saurabhreactninja** [comment]
I am using react native version 0.64. If you want to check than please check this offical code https://reactnative.dev/docs/permissionsandroid with ACCESS_FINE_LOCATION instead of CAMERA. When you use camera as a permission it show custom message and title but as soon you replace the CAMERA permission with ACCESS_FINE_LOCATION than it start showing default message.  https://reactnative.dev/docs/permissionsandroid

**Comment by chrisglein** [comment]
Replicated your sample code in a snack here: https://snack.expo.io/6nm5IVhYY

With that I see a different message for camera vs. location. Is there more to your repro I'm missing that I didn't capture in the Snack?
