### ISSUE TITLE
Android SyntaxError: Unexpected token ﻿ in JSON at position 0 

### ISSUE THREAD

**Issue by MrQureshi** [facebook/react-native#31553]
suddenly API response failed with SyntaxError: Unexpected token ﻿ in JSON at position 0

## Description
response of all APIs is failed. 
in Fetch call res.json() failed
can't use JSON.parse() in axios. 

## React Native version:
System:
    OS: macOS 11.3.1
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 44.68 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.4.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.0.15 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 23, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2
      System Images: android-30 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.4 => 0.61.4

## Steps To Reproduce

1. API response failed all over the app
2. actual response is JSON but I get this JSON in string

## Expected Results
I want to get my API response successful 

<img width="876" alt="Screenshot 2021-05-19 at 7 20 33 PM" src="https://user-images.githubusercontent.com/30835780/118829273-66f8e880-b8d7-11eb-9bfb-81758f8ff00f.png">

**Comment by cortinico** [comment]
We can't help further without a reproducer.
You're most likely attempting to JSON parse a string that is not a valid JSON string (it could be HTML, like a redirect/proxy page or so)
