### ISSUE TITLE
[docs] Document measure()

### ISSUE THREAD

**Issue by corbt** [facebook/react-native#3155]
I'm trying to get the calculated width/height of a view using the syntax found in #953, using RN 0.11 on Android. Is this implemented?

I have a component with a `<View ref="test">...</View>` and the following `componentDidMount()` block:

```javascript
  componentDidMount() {
    this.refs.test.measure((ox, oy, width, height, px, py) => {
      console.log("measured", ox, oy, width, height, px, py);
    });
  }
```

Which does successfully call the callback inside `measure`, but only prints

`measured undefined undefined undefined undefined undefined undefined`.

**Comment by ide** [comment]
This isn't a direct answer to your question, but have you looked into the `onLayout` prop?

**Comment by corbt** [comment]
Thanks @ide, the `onLayout` prop does work correctly on Android and lets me get done what I was trying to accomplish, although `measure` still isn't working properly.

**Comment by ide** [comment]
cc @mkonicek @kmagiera

**Comment by mkonicek** [comment]
I remember using `measure` but always did that from `requestAnimationFrame`. The issue might be that in `componentDidMount` the views haven't been measured yet, don't remember why.

Let's figure out why that is and document this well in JS docs for `measure`.

**Comment by corbt** [comment]
Hmm. If the component isn't measured yet, I feel like the expected behavior should be that the measure callback isn't run until the measurement has actually taken place. But yeah, if that's not the case we should document correct usage somewhere.

**Comment by mkonicek** [comment]
I believe that React calls `render` and `componentDidMount` and only then we update the native view hierarchy.

**Comment by mkonicek** [comment]
The fact the callback would never be called might be confusing too. It's more explicit to call back and say "the values are not available yet" which is what you are seeing.

**Comment by corbt** [comment]
No, I'm saying that the callback should still fire, but not until the measurements are available, at whatever stage that is.

**Comment by astreet** [comment]
Yeah, this isn't correct behavior and we should fix it. A workaround for now is calling measure in a requestAnimationFrame callback.

What's going on here is that componentDidMount is called after view commands have been sent to native, but before the end of the 'batch' of native commands. We only calculate layout and truly dispatch view updates on the native side at the end of each of these batches so that we don't show partial transactions (since a view transaction can occur over the course of many frames). The end result here is that measure is being executed after we've queued up the view commands on the native side, but before we've started to commit the transaction.

**Comment by corbt** [comment]
Alternatively, for the "I want to know the dimensions of this view ASAP" use case, the `onLayout` prop mentioned above works just fine, and is a more natural fit than calling `measure` on a `ref` inside `componentDidMount`. So even just documenting both those options in the same place with a short explanation of the differences between them may be 80% of the way there.

**Comment by astreet** [comment]
Using an `onLayout` listener from `componentDidMount` is also a good solution. I'll update the docs to mention this issue until we get it fixed.

**Comment by mkonicek** [comment]
@astreet I don't see a good place in the docs where to summarize `measure`, `onLayout`.

`measure` is defined here: https://github.com/facebook/react-native/blob/master/Libraries/ReactIOS/NativeMethodsMixin.js but doesn't have docs. @corbt Would you be up for adding the docs there?

**Comment by corbt** [comment]
Yeah it looks like none of those native methods have documentation (`focus`, `blur`, `measureLayout`, `measure`), and it would probably be useful to document all of them. And I can mention the issue with calling `measure` too early and point to `onLayout` as an alternative.

Where would this go in the docs? I'm thinking maybe a new page under **APIs** called "Refs" (those mixins are all called on `ref`s, right?) but maybe there's a better place.

**Comment by mkonicek** [comment]
You could add comprehensive docs to [`NativeMethodsMixin`](https://github.com/facebook/react-native/blob/master/Libraries/ReactIOS/NativeMethodsMixin.js) and all its methods and add it to APIs here:
https://github.com/facebook/react-native/blob/master/website/server/extractDocs.js#L219

To run the website locally to see how it renders you can do:

     cd website
     npm install
     npm start

React has documentation on refs: https://facebook.github.io/react/docs/more-about-refs.html

There's really good documentation on `findNodeHandle` here:
https://github.com/facebook/react-native/blob/master/Libraries/ReactNative/findNodeHandle.js

**Comment by mkonicek** [comment]
Adding some examples to the docs to make it clear these are the methods you would call on refs would be cool too.

Specifically, you can call this on components that include `mixins: [NativeMethodsMixin]`.

**Comment by corbt** [comment]
Ok, I should be able to get to this today.

**Comment by corbt** [comment]
Closing because NativeMethodsMixin documentation PR has been accepted.

**Comment by mkonicek** [comment]
:+1: Thanks!
