### ISSUE TITLE
RN 0.64: Scrollview StickyHeaderIndicies do not adjust when direct siblings' height changes

### ISSUE THREAD

**Issue by rraczae** [facebook/react-native#31556]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
We have a scrollview with sticky elements where the height of certain items can change.

[StickyItem]
[NonStickyItem - height can change]
[StickyItem]
[NonStickyItem - height can change]

On version 0.63.4 this was working fine, however on 0.64 when the height of a non sticky item increases from 1X to 2X the sticky header gets pushed off the screen as if it was still 1X. Downgrading to version 0.63.4 fixes the issue.

## React Native version:
System:
    OS: macOS 11.3.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 9.26 GB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.14.0 - ~/.nvm/versions/node/v14.14.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.14.0/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.14.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.0, 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_282 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: ^0.64.0 => 0.64.0
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. create a ScrollView with sticky & regular elements
2. change the height of the regular elements
3. observe sticky headers scroll out before they should

## Expected Results
It works like in RN 0.63.4

**Comment by cortinico** [comment]
Closing as this version of React Native is several years old. Please re-open a new issue against the latest stable if the issue persists
