### ISSUE TITLE
IOS build analyze Permission-BluetoothPeripheral new is unavailable

### ISSUE THREAD

**Issue by naresh-ziraff** [facebook/react-native#31568]
I am trying to analyze my IOS app got an Permission-BluetoothPeripheral issue **"new" is unavailable**, with iphone 11 version build and analyze got success but when i select **Any IOS Device** getting issue. flipper is disabled in my code.
xcode version :12.5, react-native version: 0.63.2

![image](https://user-images.githubusercontent.com/84566657/119145619-74dd7380-ba67-11eb-8b42-5cfe8d4a89eb.png)

**Comment by b3coded** [comment]
@naresh-ziraff maybe [this issue](https://github.com/zoontek/react-native-permissions/issues/590) can help you
