### ISSUE TITLE
border/jagged edges only on the iPhone 12 series device

### ISSUE THREAD

**Issue by aTreey** [facebook/react-native#31560]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Please provide a clear and concise description of what the bug is. Include screenshots if needed.
Please test using the latest React Native release to make sure your issue has not already been fixed: https://reactnative.dev/docs/upgrading.html

border on background: #006FFF and the circle background: white.
Suspect it to be antialiasing issue, as some color look blurish while some are not as follow.
Do note that for the red circle, the white text inside also appear to be very blur to an extent that it is almost unreadable

## React Native version:
Run `react-native info` in your terminal and copy the results here.
React native version: "react-native": "0.63.4"
Device:  iPhone 12 series device, but Android device is OK!

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Create a main background of backgroundColor: #006FFF;

2. Circle is produced by View with styles

## Expected Results
Describe what you expected to happen.
The circle produce with view should look smooth for all color on all device.

## Snack, code example, screenshot, or link to a repository:
Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by JNUfeatherwit** [comment]
+1
