### ISSUE TITLE
This is not a BUG

### ISSUE THREAD

**Issue by MaxCode-fan** [facebook/react-native#31561]
Can existing Modal add gesture closing?

**Comment by MaxCode-fan** [comment]
Or will this capability be improved in a later version?

**Comment by ezranbayantemur** [comment]
I think not. You should use [community package](https://github.com/react-native-modal/react-native-modal) for customization

**Comment by ezranbayantemur** [comment]
@MaxCode-fan Can you close the issue if your problem solved?
