### ISSUE TITLE
error: node_modules/react-native/Libraries/Components/Touchable/TouchableHighlight.js: /Users/sanjayjangid/Desktop/Projects/3sigma-app-new/node_modules/react-native/Libraries/Components/Touchable/TouchableHighlight.js: Cannot read property 'end' of null

### ISSUE THREAD

**Issue by skjangid** [facebook/react-native#31570]
error: node_modules/react-native/Libraries/Components/Touchable/TouchableHighlight.js: /Users/sanjayjangid/Desktop/Projects/3sigma-app-new/node_modules/react-native/Libraries/Components/Touchable/TouchableHighlight.js: Cannot read property 'end' of null

package.json : 

"private": true,
    "scripts": {
        "android": "react-native run-android",
        "ios": "react-native run-ios",
        "start": "react-native start",
        "test": "jest",
        "lint": "eslint ."
    },
    "dependencies": {
        "@heap/react-native-heap": "^0.14.0",
        "@invertase/react-native-apple-authentication": "^2.1.0",
        "@react-native-community/async-storage": "^1.12.1",
        "@react-native-community/clipboard": "1.5.0",
        "@react-native-community/datetimepicker": "3.0.2",
        "@react-native-community/masked-view": "0.1.10",
        "@react-native-community/netinfo": "5.9.7",
        "@react-native-community/push-notification-ios": "1.7.3",
        "@react-native-firebase/app": "8.4.5",
        "@react-native-firebase/auth": "9.2.7",
        "@react-native-firebase/crashlytics": "10.0.0",
        "@react-native-firebase/in-app-messaging": "10.1.0",
        "@react-native-firebase/messaging": "7.9.2",
        "@react-native-firebase/perf": "10.1.0",
        "@react-native-firebase/storage": "7.4.9",
        "@react-navigation/bottom-tabs": "^5.11.7",
        "@react-navigation/material-top-tabs": "^5.3.13",
        "@react-navigation/native": "5.7.3",
        "@react-navigation/stack": "5.9.0",
        "@redux-offline/redux-offline": "2.6.0-native.0",
        "@sentry/react-native": "2.0.0",
        "@twotalltotems/react-native-otp-input": "^1.3.11",
        "add": "2.0.6",
        "axios": "0.20.0",
        "moment": "2.29.1",
        "path": "^0.12.7",
        "react": "16.13.1",
        "react-native": "0.63.2",
        "react-native-calendars": "1.403.0",
        "react-native-call-log": "^2.1.2",
        "react-native-card-stack-swiper": "1.2.5",
        "react-native-circular-progress": "^1.3.6",
        "react-native-contacts": "5.2.7",
        "react-native-country-picker-modal": "2.0.0",
        "react-native-datepicker": "1.7.2",
        "react-native-document-picker": "4.0.0",
        "react-native-elements": "^3.4.1",
        "react-native-extended-stylesheet": "0.12.0",
        "react-native-fbsdk": "2.0.0",
        "react-native-flash-message": "0.1.16",
        "react-native-fs": "2.16.6",
        "react-native-gesture-handler": "1.8.0",
        "react-native-get-random-values": "1.5.0",
        "react-native-google-places-autocomplete": "2.1.1",
        "react-native-google-signin": "2.1.1",
        "react-native-iap": "^5.2.0",
        "react-native-image-crop-picker": "0.35.0",
        "react-native-linear-gradient": "2.5.6",
        "react-native-maps": "0.27.1",
        "react-native-material-buttons": "0.6.0",
        "react-native-neu-element": "1.1.9",
        "react-native-offline": "5.7.0",
        "react-native-otp-verify": "^1.0.3",
        "react-native-paper": "^3.6.0",
        "react-native-phone-input": "0.2.2",
        "react-native-push-notification": "^7.3.1",
        "react-native-razorpay": "^2.2.4",
        "react-native-reanimated": "^1.13.2",
        "react-native-safe-area-context": "3.1.7",
        "react-native-screens": "2.10.1",
        "react-native-shadow": "1.2.2",
        "react-native-share": "4.0.2",
        "react-native-svg": "11.0.1",
        "react-native-swiper": "1.6.0",
        "react-native-switch": "2.0.0",
        "react-native-tab-view": "^2.15.2",
        "react-native-vector-icons": "7.0.0",
        "react-native-webview": "10.9.2",
        "react-navigation": "4.4.0",
        "react-navigation-stack": "2.8.2",
        "react-navigation-transitions": "1.0.12",
        "react-redux": "7.2.2",
        "recyclerlistview": "3.0.0",
        "redux": "4.0.5",
        "rn-fetch-blob": "0.12.0",
        "socket.io-client": "2.3.1",
        "uuid": "8.3.1",
        "yarn": "1.22.5"
    },
    "devDependencies": {
        "@babel/core": "7.8.4",
        "@babel/runtime": "7.8.4",
        "@react-native-community/eslint-config": "1.1.0",
        "babel-jest": "25.1.0",
        "eslint": "6.5.1",
        "jest": "25.1.0",
        "metro-react-native-babel-preset": "0.59.0",
        "react-native-dotenv": "^2.5.0",
        "react-test-renderer": "16.13.1"
    },
    "jest": {
        "preset": "react-native"
    }

![image](https://user-images.githubusercontent.com/4602467/119157030-5fba1200-ba72-11eb-99bb-d92c6f69518a.png)

**Comment by codercodingthecode** [comment]
Similar error in both android and ios  [macos]
![image](https://user-images.githubusercontent.com/20182536/120758395-68313480-c4d7-11eb-86a6-015f6fa9a220.png)

**Comment by Necromant1k** [comment]
@codercodingthecode @skjangid I've noticed you use `heap`. Try upgrading to 0.17-alpha. issue gone for me after upgrade

**Comment by codercodingthecode** [comment]
> @codercodingthecode @skjangid I've noticed you use `heap`. Try upgrading to 0.17-alpha. issue gone for me after upgrade

my solution at the time was to roll back to a stable version.
