### ISSUE TITLE
React native's Modal not getting dismissed in iOS

### ISSUE THREAD

**Issue by hk22sync** [facebook/react-native#31578]
Using ActivityIndicator inside Modal.

<Modal
      transparent={true}
      animationType={'none'}
      visible={this.props.loading}
      onRequestClose={() => {}}
    >
 <View>
    <ActivityIndicator animating={this.props.loading} size={'large'} />
 </View>
</Modal>

Steps on the use case:
1. loading prop is set to true --> Modal opens
2. API call is made
3. loading prop is set to false --> Modal stays on the screen

react version: 16.9.0,
react-native version: 0.61.2,
iOS version: iPadOS 13.5.1

**Comment by oguzturker8** [comment]
Seems screen won't refresh after this.prop.loading is set to false. How do you update `this.props.loading` ? You need to change it in parent

**Comment by hk22sync** [comment]
> Seems screen won't refresh after this.prop.loading is set to false. How do you update `this.props.loading` ? You need to change it in parent

I have a parent component where I maintain the state: **loading**: false
I change this state to true before the API call and set it back to false after that.

**Comment by tanoto-the-explorer** [comment]
@hk22sync how did you fix it?
