### ISSUE TITLE
iOS upgrade to 0.64.1 from 0.63.3 - can't archive, stuck on Bundle React Native code and images

### ISSUE THREAD

**Issue by ofri-7chairs** [facebook/react-native#31574]
before upgrade rn version, I was on 0.63.3 and it worked fine.

currently it runs:
export NODE_BINARY=node
../node_modules/react-native/scripts/react-native-xcode.sh

tried also:
export NODE_BINARY=$(which_node)
without success

node: 12.18.0
npm: 6.14.4
xcode: 12.4

**Comment by ofri-7chairs** [comment]
open the issue in
https://github.com/react-native-community/upgrade-support/issues/165

**Comment by giuthub** [comment]
Facebook App [canhbui](https://reactnative.dev).vn(rét
