### ISSUE TITLE
Are we going to support outlineStyle style prop?

### ISSUE THREAD

**Issue by dotku** [facebook/react-native#31576]
I found set TextInput {outlineStyle: "none"} can resolve the outline display, but it seems not support by react native yet. Any plan to add it?

**Comment by safaiyeh** [comment]
Would this help you https://reactnative.dev/docs/view-style-props#borderstyle?

**Comment by dotku** [comment]
@safaiyeh I found Mobile doesn't have the border issue, but web has the issue, and IDE promoted says that outlineStyle doesn't work yet.
