### ISSUE TITLE
Crashlytics Crash at RCTUtils.m - Line 751

### ISSUE THREAD

**Issue by qburst-subins** [facebook/react-native#31579]
Getting crash on iOS device 
iOS versions 14.4+.
![Screenshot 2021-05-24 at 20 06 25](https://user-images.githubusercontent.com/8746256/119364229-50360580-bccc-11eb-989a-7243eedf4dd0.png)

![Screenshot 2021-05-24 at 20 16 44](https://user-images.githubusercontent.com/8746256/119364923-0e598f00-bccd-11eb-8f85-b1fbc2837645.png)
It shows that it was caused by memory leaks.

 React Native version:
  "react": "16.11.0",
  "react-native": "0.62.2",

Crashed: com.apple.main-thread
0  libsystem_kernel.dylib         0x1d1629414 __pthread_kill + 8
1  libsystem_pthread.dylib        0x1ef184b50 pthread_kill + 272
2  libsystem_c.dylib              0x1acb07b74 abort + 104
3  libsystem_malloc.dylib         0x1b34e349c _malloc_put + 558
4  libsystem_malloc.dylib         0x1b34e367c malloc_report + 64
5  libsystem_malloc.dylib         0x1b34d7f68 free + 532
6  libcache.dylib                 0x1ef00816c cache_set_name + 36
7  CoreFoundation                 0x1a35e5bb0 -[NSCache setName:] + 208
8  CoreUI                         0x1afbde62c -[CUICatalog negativeCache] + 148
9  CoreUI                         0x1afbdb570 -[CUICatalog _private_resolvedRenditionKeyFromThemeRef:withBaseKey:scaleFactor:deviceIdiom:deviceSubtype:displayGamut:layoutDirection:sizeClassHorizontal:sizeClassVertical:memoryClass:graphicsClass:graphicsFallBackOrder:deviceSubtypeFallBackOrder:localizationIdentifier:adjustRenditionKeyWithBlock:] + 752
10 CoreUI                         0x1afbdb25c -[CUICatalog _resolvedRenditionKeyFromThemeRef:withBaseKey:scaleFactor:deviceIdiom:deviceSubtype:displayGamut:layoutDirection:sizeClassHorizontal:sizeClassVertical:memoryClass:graphicsClass:graphicsFallBackOrder:deviceSubtypeFallBackOrder:adjustRenditionKeyWithBlock:] + 364
11 CoreUI                         0x1afbd49b0 -[CUICatalog _imageWithName:scaleFactor:deviceIdiom:deviceSubtype:displayGamut:layoutDirection:sizeClassHorizontal:sizeClassVertical:memoryClass:graphicsClass:appearanceIdentifier:graphicsFallBackOrder:deviceSubtypeFallBackOrder:] + 272
12 CoreUI                         0x1afbd4b5c -[CUICatalog imageWithName:scaleFactor:deviceIdiom:deviceSubtype:displayGamut:layoutDirection:sizeClassHorizontal:sizeClassVertical:memoryClass:graphicsClass:appearanceIdentifier:graphicsFallBackOrder:deviceSubtypeFallBackOrder:] + 228
13 CoreUI                         0x1afbd44c0 -[CUICatalog imageWithName:scaleFactor:deviceIdiom:deviceSubtype:displayGamut:layoutDirection:sizeClassHorizontal:sizeClassVertical:appearanceName:] + 344
14 UIKitCore                      0x1a5c58de8 __39-[UIImageAsset imageWithConfiguration:]_block_invoke + 144
15 UIKitCore                      0x1a5c5a300 __89-[UIImageAsset _lookUpRegisteredObjectForTraitCollection:withAccessorWithAppearanceName:]_block_invoke + 84
16 UIKitCore                      0x1a5c8e568 -[UITraitCollection _enumerateThemeAppearanceNamesForLookup:] + 256
17 UIKitCore                      0x1a5c5a1e0 -[UIImageAsset _lookUpRegisteredObjectForTraitCollection:withAccessorWithAppearanceName:] + 252
18 UIKitCore                      0x1a5c58840 -[UIImageAsset imageWithConfiguration:] + 704
19 UIKitCore                      0x1a5c5aabc -[_UIPathLazyImageAsset imageWithConfiguration:] + 420
20 UIKitCore                      0x1a5c43880 +[UIImage imageNamed:inBundle:withConfiguration:] + 716
21 IKONIK                         0x1027a3674 RCTImageFromLocalAssetURL + 751 (RCTUtils.m:751)
22 IKONIK                         0x1027e4e7c __119-[RCTLocalAssetImageLoader loadImageForURL:size:scale:resizeMode:progressHandler:partialLoadHandler:completionHandler:]_block_invoke + 58 (RCTLocalAssetImageLoader.mm:58)
23 IKONIK                         0x1027a1954 RCTExecuteOnMainQueue + 255 (RCTUtils.m:255)
24 IKONIK                         0x1027e4cdc -[RCTLocalAssetImageLoader loadImageForURL:size:scale:resizeMode:progressHandler:partialLoadHandler:completionHandler:] + 71 (RCTLocalAssetImageLoader.mm:71)
25 IKONIK                         0x1027d9d54 -[RCTImageLoader _loadImageOrDataWithURLRequest:size:scale:resizeMode:attribution:progressBlock:partialLoadBlock:completionBlock:] + 483 (RCTImageLoader.mm:483)
26 IKONIK                         0x1027db8bc -[RCTImageLoader loadImageWithURLRequest:size:scale:clipped:resizeMode:attribution:progressBlock:partialLoadBlock:completionBlock:] + 750 (RCTImageLoader.mm:750)
27 IKONIK                         0x1027e2710 -[RCTImageView reloadImage] + 324 (RCTImageView.mm:324)
28 IKONIK                         0x1027e339c -[RCTImageView reactSetFrame:] + 411 (RCTImageView.mm:411)
29 IKONIK                         0x1027998e8 __51-[RCTUIManager uiBlockWithLayoutUpdateForRootView:]_block_invoke.214 + 675 (RCTUIManager.m:675)
30 IKONIK                         0x10279d130 __44-[RCTUIManager flushUIBlocksWithCompletion:]_block_invoke + 1180 (RCTUIManager.m:1180)
31 IKONIK                         0x10279d22c __44-[RCTUIManager flushUIBlocksWithCompletion:]_block_invoke.417 + 1204 (RCTUIManager.m:1204)
32 libdispatch.dylib              0x1a32cc24c _dispatch_call_block_and_release + 32
33 libdispatch.dylib              0x1a32cddb0 _dispatch_client_callout + 20
34 libdispatch.dylib              0x1a32db7ac _dispatch_main_queue_callback_4CF + 836
35 CoreFoundation                 0x1a365511c __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
36 CoreFoundation                 0x1a364f120 __CFRunLoopRun + 2508
37 CoreFoundation                 0x1a364e21c CFRunLoopRunSpecific + 600
38 Foundation                     0x1a48fddf0 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 232
39 Foundation                     0x1a48fdcbc -[NSRunLoop(NSRunLoop) runUntilDate:] + 92
40 IKONIK                         0x1028e3a80 +[RNSplashScreen show] + 31 (RNSplashScreen.m:31)
41 IKONIK                         0x102538e5c -[AppDelegate application:didFinishLaunchingWithOptions:] + 92 (AppDelegate.m:92)
42 UIKitCore                      0x1a608b228 -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 360
43 UIKitCore                      0x1a608d290 -[UIApplication _callInitializationDelegatesWithActions:forCanvas:payload:fromOriginatingProcess:] + 5136
44 UIKitCore                      0x1a6092cec -[UIApplication _runWithMainScene:transitionContext:completion:] + 1244
45 UIKitCore                      0x1a56e8c74 -[_UISceneLifecycleMultiplexer completeApplicationLaunchWithFBSScene:transitionContext:] + 152
46 UIKitCore                      0x1a5c56f9c _UIScenePerformActionsWithLifecycleActionMask + 112
47 UIKitCore                      0x1a56e980c __101-[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:]_block_invoke + 224
48 UIKitCore                      0x1a56e9214 -[_UISceneLifecycleMultiplexer _performBlock:withApplicationOfDeactivationReasons:fromReasons:] + 300
49 UIKitCore                      0x1a56e961c -[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:] + 768
50 UIKitCore                      0x1a56e8e58 -[_UISceneLifecycleMultiplexer uiScene:transitionedFromState:withTransitionContext:] + 340
51 UIKitCore                      0x1a56f13a4 __186-[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:]_block_invoke + 196
52 UIKitCore                      0x1a5b6360c +[BSAnimationSettings(UIKit) tryAnimatingWithSettings:actions:completion:] + 892
53 UIKitCore                      0x1a5c6f6c4 _UISceneSettingsDiffActionPerformChangesWithTransitionContext + 272
54 UIKitCore                      0x1a56f109c -[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:] + 384
55 UIKitCore                      0x1a55185a0 __64-[UIScene scene:didUpdateWithDiff:transitionContext:completion:]_block_invoke + 776
56 UIKitCore                      0x1a5516f14 -[UIScene _emitSceneSettingsUpdateResponseForCompletion:afterSceneUpdateWork:] + 256
57 UIKitCore                      0x1a55181c8 -[UIScene scene:didUpdateWithDiff:transitionContext:completion:] + 248
58 UIKitCore                      0x1a6090e8c -[UIApplication workspace:didCreateScene:withTransitionContext:completion:] + 572
59 UIKitCore                      0x1a5b8ce38 -[UIApplicationSceneClientAgent scene:didInitializeWithEvent:completion:] + 388
60 FrontBoardServices             0x1b34423bc -[FBSScene _callOutQueue_agent_didCreateWithTransitionContext:completion:] + 432
61 FrontBoardServices             0x1b346dd04 __94-[FBSWorkspaceScenesClient createWithSceneID:groupID:parameters:transitionContext:completion:]_block_invoke.200 + 128
62 FrontBoardServices             0x1b34514a0 -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:] + 240
63 FrontBoardServices             0x1b346d9c8 __94-[FBSWorkspaceScenesClient createWithSceneID:groupID:parameters:transitionContext:completion:]_block_invoke + 372
64 libdispatch.dylib              0x1a32cddb0 _dispatch_client_callout + 20
65 libdispatch.dylib              0x1a32d1738 _dispatch_block_invoke_direct + 268
66 FrontBoardServices             0x1b3496250 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 48
67 FrontBoardServices             0x1b3495ee0 -[FBSSerialQueue _targetQueue_performNextIfPossible] + 448
68 FrontBoardServices             0x1b3496434 -[FBSSerialQueue _performNextFromRunLoopSource] + 32
69 CoreFoundation                 0x1a365576c __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28
70 CoreFoundation                 0x1a3655668 __CFRunLoopDoSource0 + 208
71 CoreFoundation                 0x1a3654960 __CFRunLoopDoSources0 + 268
72 CoreFoundation                 0x1a364ea8c __CFRunLoopRun + 824
73 CoreFoundation                 0x1a364e21c CFRunLoopRunSpecific + 600
74 GraphicsServices               0x1bb218784 GSEventRunModal + 164
75 UIKitCore                      0x1a608eee8 -[UIApplication _run] + 1072
76 UIKitCore                      0x1a609475c UIApplicationMain + 168
77 IKONIK                         0x1025395f4 main + 7 (main.m:7)
78 libdyld.dylib                  0x1a330e6b0 start + 4

**Comment by subinsuresh** [comment]
Any Updates on this?

**Comment by kissifrot** [comment]
We are having the same errors here, without any clue on what could be the cause :(

**Comment by cortinico** [comment]
Hey,
We're cleaning up the React Native issue tracker to make sure we focus on the most important issues first.

I'm closing this one because it's stale and related to a version of React Native we no longer support. If the issue persists on the latest version, please re-open a new issue and reference this one.

Moreover, we generally can't fix issues just by looking at a stacktrace reported from your crash reporting platform. Please provide a reproducer in your future reports.

Thank you.
