### ISSUE TITLE
Brand new project fails to run on iOS or Android

### ISSUE THREAD

**Issue by anarchicknight** [facebook/react-native#3158]
"dependencies": {
    "react-native": "^0.11.4"
  }

react-native init Test

Once scripts have finished running run the app via Xcode 7 for iOS8.4 or iOS9
or
Start up genymotion and run 'react-native run-android'

In both cases the following error is shown

Invariant Violation: Application Test has not been registered. This is either due to a require() error during initialization or failure to call AppRegistry.registerComponent.

**Comment by grabbou** [comment]
When running from Xcode, do you get additional terminal popping up when running? This is packager that should build & server your app. There are some issues it does not start on Xcode 7.

Also, in some cases, refreshing / reloading is just enough because initially the app starts faster than the packager.

**Comment by anarchicknight** [comment]
Yeah I get the extra terminal window appear. I have no issues with an existing app on 0.11.2 running through xcode 7 or on android.

I have replicated this on 3 different new projects on 0.11.4 just to make sure I did not have some weird issue happen as a one off.

Is no one else getting this?

**Comment by brentvatne** [comment]
It seems like you have a packager server running for a different project - it's looking for for the application named "Test" but if you have another packager running then you probably have a different name registered for AppRegistry. Make sure you close your packager and start it again in the new project. Going to close this issue but ping me if this persists and I can reopen if it's a bug!

**Comment by anarchicknight** [comment]
Top work brent - that looks like what it could have been.

Made sure everything was closed down today and created a brand new project again - ran on Android & iOS with no issues. Thanks
