### ISSUE TITLE
[Android][borderStyle] borderStyle dashed does not work without borderRadius being set.

### ISSUE THREAD

**Issue by chirag04** [facebook/react-native#3159]
dashed border does not work if borderRadius is not set.

cc @kmagiera @mkonicek

**Comment by Taakn** [comment]
This is still not working as of 0.19

**Comment by mkonicek** [comment]
Image fading doesn't work either, there's some bug with borderRadius: https://github.com/facebook/react-native/issues/5545

Anyone with Android experience up for sending a fix?

**Comment by glued** [comment]
Setting border to a specific edge like `borderBottomWidth` also breaks even with `borderRadius` set.

**Comment by sjmueller** [comment]
Support for `borderBottomWidth` is broken on iOS as well.

**Comment by ms88privat** [comment]
:+1: 
I get the warning `Unsupported dashed / dotted border style` when I try this on a View on iOS:

```js
borderBottomWidth: 1,
borderBottomColor: '#e6e5e5',
borderStyle: 'dashed',
```

on Android I see a border (not dashed) without any warnings

**Comment by satya164** [comment]
Is this still an issue?

**Comment by sarovin** [comment]
Yes, i have a same problem of ms88privat

**Comment by ms88privat** [comment]
@satya164 I'm on 0.21.0 and it is not working. Not sure about newer Versions

**Comment by Kerumen** [comment]
I have the same problem here on 0.22 and on iOS: `Unsupported dashed / dotted border style`.

**Comment by liuhong1happy** [comment]
I have the same problem here on 0.24.1 and on Android: `Unsupported dashed / dotted border style`.

**Comment by yaofly2012** [comment]
It did not work when  try this on View ? 
`borderBottomWidth: 1,
borderStyle: 'dashed',`

**Comment by ajoshdee** [comment]
Same here

**Comment by chirag04** [comment]
@yaofly2012 did you set the border Color?

**Comment by ajoshdee** [comment]
I already set the color on mine, but still would not appear

**Comment by ajoshdee** [comment]
It works on `borderWidth` but not on specific borders like `borderTopWidth`

**Comment by idris** [comment]
@samerce why is this issue closed?  As @ajoshdee mentioned, it still does not work on specific borders like `borderTopWidth`

**Comment by awitherow** [comment]
Again, why is this closed? It does not work as expected.

**Comment by baires** [comment]
Im on RN `0.38.0` and still cant apply style on specific borders.

**Comment by Mr-Hero** [comment]
Why issue is closed? it doesn't been fixed

**Comment by satya164** [comment]
@idris @Mr-Hero this issue only said that it doesn't work without border radius. what you are describing is a different issue. Please file a new bug report for that.

**Comment by huangming1994** [comment]
@yaofly2012 l got the same issue

**Comment by xahon** [comment]
Why it is closed. Still not working on android

**Comment by xahon** [comment]
Neither dotted nor dashed

**Comment by Kerumen** [comment]
@hramos Can you reopen please? The issue is not fixed. Even on latest RN.

**Comment by hramos** [comment]
Instead of re-opening a stale issue, I suggest opening a new issue and filling out the template.

**Comment by maraujop** [comment]
Don't forget that this issue is tracked first in search engines, SEO is important

**Comment by xahon** [comment]
I think this issue will never be resolved by facebook. Waiting for PRs

**Comment by divyanshu013** [comment]
Can confirm `borderStyle` is not working w/o `borderRadius` (v0.49 on Android)

**Comment by icaromagalhaes** [comment]
Still not working, why its closed?

**Comment by denny64** [comment]
+1 not working

**Comment by timhorwood** [comment]
This still isn't working.

**Comment by vnd-ranga** [comment]
This still isn't working.

**Comment by AgNm** [comment]
same issue, any solution?

**Comment by weslley39** [comment]
This still isn't working.

**Comment by finkbit** [comment]
This is still not working `"react-native": "^0.55.2"`.

**Comment by lewisflude** [comment]
This isn't working for me either, should this be reopened?

**Comment by lewisflude** [comment]
Will be watching this issue in any case

**Comment by Phongtlam** [comment]
Why closing this issue? This is not solved in any way.

**Comment by thomazchamberlain** [comment]
Will creating a new issue help?

**Comment by thomazchamberlain** [comment]
so where's the new issue?
