### ISSUE TITLE
Require function whitespace problem.

### ISSUE THREAD

**Issue by Zapix** [facebook/react-native#316]
Hello. 

When it try to get module with require `require("react-native")` everything is ok. 
But when I wrap module name with whitespace `require( "react-native" )` I've got an error:

```
Invariant Violation: Application
``` 
I have this problem on OS X 10.10 with node 0.12.0

**Comment by vjeux** [comment]
cc @amasad, would be nice to make this error message better

**Comment by amasad** [comment]
it'd be better to fix it :)

**Comment by daviskoh** [comment]
Came across this issue as well :/ It seems that the **id** arg passed into the require func defined in **require.js** is incorrect when spaces are used in calling the require func. 

require( "react-native" )
![wrong](https://cloud.githubusercontent.com/assets/5395403/6873095/3ca929b6-d484-11e4-9078-efca9fa1359d.png)

require("react-native")
![correct](https://cloud.githubusercontent.com/assets/5395403/6873094/3ca765c2-d484-11e4-964c-cffea5469db7.png)

**Comment by amasad** [comment]
If someone wants to take a stab at fixing this:

look here https://github.com/facebook/react-native/blob/master/packager/react-packager/src/DependencyResolver/haste/DependencyGraph/index.js#L603
and here https://github.com/facebook/react-native/blob/master/packager/react-packager/src/DependencyResolver/haste/index.js#L28
