### ISSUE TITLE
Remove defaultProps in DrawerLayoutAndroid

### ISSUE THREAD

**Issue by lunaleaps** [facebook/react-native#31606]
See parent issue #31601 

## Expected Results
`defaultProps` are removed in [DrawerLayoutAndroid](https://github.com/facebook/react-native/blob/dc80b2dcb52fadec6a573a9dd1824393f8c29fdc/Libraries/Components/DrawerAndroid/DrawerLayoutAndroid.android.js#L164)

**Comment by Setito** [comment]
Hello there, I'm able to take this one  :)

**Comment by udit512** [comment]
Hey, if this issue is available i would like to take it

**Comment by mdaj06** [comment]
@lunaleaps can i take this up?

**Comment by lunaleaps** [comment]
Oh yes. Apologies! I missed this comment. Yea feel free to make a PR @mdaj06

**Comment by mdaj06** [comment]
Sure thanks @lunaleaps !

**Comment by genos186** [comment]
@lunaleaps can I try to fix this up too?

**Comment by mdaj06** [comment]
hey @genos186 i have started  some work on this issue and wold be raising a PR soon

**Comment by yashu2001** [comment]
Can I take this up @lunaleaps ?
