### ISSUE TITLE
Remove defaultProps from StatusBar

### ISSUE THREAD

**Issue by lunaleaps** [facebook/react-native#31607]
See parent issue #31601 

## Expected Result
`defaultProps` removed from [StatusBar](https://github.com/facebook/react-native/blob/0afd71a18d19edef3d6603cabd2672ffde5ba30e/Libraries/Components/StatusBar/StatusBar.js#L387)

**Comment by Fannolo** [comment]
Hi can I take this issue?

**Comment by lunaleaps** [comment]
@Fannolo assigned!

**Comment by yasirunilan** [comment]
Is the development still happening? if not can I work on this

**Comment by Fannolo** [comment]
> Is the development still happening? if not can I work on this

Hi @yasirunilan, sorry for the late reply, the development is actually completed, I am doing some additional checks before asking @lunaleaps to merge it

**Comment by Fannolo** [comment]
@lunaleaps can we close this issue? 😄

**Comment by lunaleaps** [comment]
Thanks for the reminder!
