### ISSUE TITLE
Remove defaultProps in SegmentedControlIOS

### ISSUE THREAD

**Issue by lunaleaps** [facebook/react-native#31604]
See parent issue #31601

## Expected Results
`defaultProps` are removed in [SegmentedControlIOS](https://github.com/facebook/react-native/blob/dc80b2dcb52fadec6a573a9dd1824393f8c29fdc/Libraries/Components/SegmentedControlIOS/SegmentedControlIOS.ios.js#L79)

**Comment by kerm1it** [comment]
Can I take this issue?

**Comment by lunaleaps** [comment]
@kerm1it assigned! Please set me as a reviewer on your pull request and thank you for your help in making RN better!

**Comment by joxw1** [comment]
If it is ok I would like to take this issue 😄  I already created a [pull request](https://github.com/facebook/react-native/pull/31804) 🚀

**Comment by lunaleaps** [comment]
@joxw1, I'll let @kerm1it comment on whether they're okay with this change or if they already have work in progress. If I don't hear a response in 2 days (July 9, 2021) then I can assign to you

**Comment by kerm1it** [comment]
I don't recommend to start this before https://github.com/facebook/react-native/pull/31644 has not yet been resolved thoroughly.

**Comment by lunaleaps** [comment]
> I don't recommend to start this before #31644 has not yet been resolved thoroughly.
Hmm @kerm1it what do you mean? That issue has been resolved.

**Comment by kerm1it** [comment]
OK，you can assign this to @joxw1 , I'm so busy recently.
