### ISSUE TITLE
Remove defaultProps from Picker

### ISSUE THREAD

**Issue by lunaleaps** [facebook/react-native#31603]
See parent issue: #31602 

## Expected Results
`defaultProps` is removed from [Picker](https://github.com/facebook/react-native/blob/0afd71a18d19edef3d6603cabd2672ffde5ba30e/Libraries/Components/Picker/Picker.js#L143)

**Comment by kerm1it** [comment]
Can I take this issue?

**Comment by lunaleaps** [comment]
@kerm1it assigned, thanks for working on this! Please set me as a reviewer for your pull request!

**Comment by lunaleaps** [comment]
@kerm1it oh no! I didn't realize! Is there anyway for you to request a reviewer?
