### ISSUE TITLE
Remove defaultProps from our core components

### ISSUE THREAD

**Issue by lunaleaps** [facebook/react-native#31601]
## Description
defaultProps makes it difficult for us to migrate components to functional. This will be the global issue tracking removing defaultProps from our codebase. 

## Tasks
**Note:**
This issue is purely for tracking the following issues. If you want to work on any of the following, please comment on the issue and I will assign it to you if it's not already claimed - thank you!
- [x] FlatList #31602 
- [x] Picker #31603
- [x] SegmentedControlIOS #31604
- [x] DatePickeriOS #31605
- [x] DrawerLayoutAndroid #31606
- [x] StatusBar #31607

**Comment by yashu2001** [comment]
@lunaleaps  anyone working on this?
If not I'd like to take it up

**Comment by priyang12** [comment]
I would like to work on this issue @lunaleaps

**Comment by lunaleaps** [comment]
@priyang12 I think this issue has been completed! Sorry I forgot to update. You can find a lot of other great issues to pick up via the "Good first issue" label or perhaps one from the accessibility project board: https://github.com/facebook/react-native/projects/15
