### ISSUE TITLE
Remove defaultProps in FlatList

### ISSUE THREAD

**Issue by lunaleaps** [facebook/react-native#31602]
See parent issue #31601 

## Expected Results
`defaultProps` are removed from [FlatList](https://github.com/facebook/react-native/blob/dc80b2dcb52fadec6a573a9dd1824393f8c29fdc/Libraries/Lists/FlatList.js#L279)

**Comment by Fannolo** [comment]
Hi can I also take this issue while I wait for #31607 to be merged? I saw that @oguzturker8 changed more than one file in his PR, please let me know if I can take it. Thanks!

**Comment by joxw1** [comment]
If it is ok I would like to take over this issue.
I already submitted a pull-request.

**Comment by oguzturker8** [comment]
@joxw1 
Sorry was super busy these days. You can take it. Thanks

**Comment by lunaleaps** [comment]
Since I haven't seen a PR from @Fannolo, I'm good with this! @Fannolo please reply to this issue within the next 2 days if you're still interested in this issue or would like to pass it on. I will check in 2 days and if not I'll assign to @joxw1

Thanks everyone for your help!

**Comment by Fannolo** [comment]
Hi @lunaleaps yes it's fine since @joxw1 already submitted a pr you can assign this task to him! Thank you!

**Comment by joxw1** [comment]
> Hi @lunaleaps yes it's fine since @joxw1 already submitted a pr you can assign this task to him! Thank you!

Thank you!

**Comment by joxw1** [comment]
@lunaleaps Can this be closed now? ☺️
