### ISSUE TITLE
Can not setup environment to run react android on window

### ISSUE THREAD

**Issue by toiyeugiadinh92** [facebook/react-native#3162]
Can you for me a example - from setup environment to HelloWorld Project android.

**Comment by satya164** [comment]
The docs have everything to get you started - https://facebook.github.io/react-native/docs/getting-started.html

`react-native init` generates a `HelloWorld` project. To add Android to existing iOS project, use `react-native android`.

**Comment by satya164** [comment]
#2780

**Comment by satya164** [comment]
Also see https://gist.github.com/davidgilbertson/9bee68548037fe00f2a8

**Comment by toiyeugiadinh92** [comment]
Thank you.

**Comment by toiyeugiadinh92** [comment]
I saw someone who show screen emulator run react android on windows. It is real or fake.

**Comment by ide** [comment]
It's probably real, just not supported.

**Comment by satya164** [comment]
Check the link I posted. It has some set up instructions for Windows. I
haven't tried it as I'm on OS X.

**Comment by toiyeugiadinh92** [comment]
![capture](https://cloud.githubusercontent.com/assets/7263857/10214807/b23e6e70-6845-11e5-9169-f24fc5250c1c.PNG)


Error when I try to init project android on windows.

**Comment by abdelouahabb** [comment]
@toiyeugiadinh92 it worked here (win 7), I just followed this https://gist.github.com/davidgilbertson/9bee68548037fe00f2a8
