### ISSUE TITLE
My app is working fine in local on both simulator and physical devices. But, app can't launch when put to the TestFlight.

### ISSUE THREAD

**Issue by endlesstech** [facebook/react-native#31638]
I search in Xcode organizer, it shows an error at 

void RCTFatal(NSError *error)
{
  _RCTLogNativeInternal(RCTLogLevelFatal, NULL, 0, @"%@", error.localizedDescription);

  RCTFatalHandler fatalHandler = RCTGetFatalHandler();
  if (fatalHandler) {
    fatalHandler(error);
  } else {
    @try {
      NSString *name = [NSString stringWithFormat:@"%@: %@", RCTFatalExceptionName, error.localizedDescription];

      // Truncate the localized description to 175 characters to avoid wild screen overflows
      NSString *message = RCTFormatError(error.localizedDescription, error.userInfo[RCTJSStackTraceKey], 175);

      // Attach an untruncated copy of the description to the userInfo, in case it is needed
      NSMutableDictionary *userInfo = [error.userInfo mutableCopy];
      [userInfo setObject:RCTFormatError(error.localizedDescription, error.userInfo[RCTJSStackTraceKey], -1)
                   forKey:RCTUntruncatedMessageKey];

      // Expected resulting exception information:
      // name: RCTFatalException: <underlying error description>
      // reason: <underlying error description plus JS stack trace, truncated to 175 characters>
      // userInfo: <underlying error userinfo, plus untruncated description plus JS stack trace>
      @throw [[NSException alloc] initWithName:name reason:message userInfo:userInfo];
    } @catch (NSException *e) {
    }
  }
}

**Comment by uday-brainium** [comment]
This issue may be causing because of the SSL and Flipper so the easy solution worked for me is to update Xcode version and try again. 
or enable Flipper and SSL in your project

**Comment by pavelprudnikov** [comment]
I have the same issue, @endlesstech did you solve it?

**Comment by francisco-ss-dev** [comment]
can some one help?
same case here...

**Comment by Navjot125** [comment]
Make sure in Target's Build phase => Bundle React Native code and images => for install build only is false
