### ISSUE TITLE
RCTImageLoader crashes （RN 0.63.3）

### ISSUE THREAD

**Issue by chengfang1103** [facebook/react-native#31640]
✋ To keep the backlog clean and actionable, issues will be
🚫 closed if they do not follow one of the issue templates:
👉 https://github.com/facebook/react-native/issues/new/choose

caused by:Application received signal 11
--
1 | callStackSymbols: {
2 | 0   libobjc.A.dylib                 0x0000000182a56b30 objc_msgSend + 16
3 | 1 CoreFoundation 0x0000000182c12dbc -[NSArray sortedArrayFromRange:options:usingComparator:] (in CoreFoundation) + 1084
4 | 2 DocPlatform 0x00000001008ee54c -[RCTImageLoader imageDataDecoderForData:] (in DocPlatform) (RCTImageLoader.mm:0)
5 | 3 DocPlatform 0x00000001008f242c -[RCTImageLoader decodeImageData:size:scale:clipped:resizeMode:completionBlock:] (in DocPlatform) (RCTImageLoader.mm:0)
6 | 4 DocPlatform 0x00000001008f1bd8 __140-[RCTImageLoader loadImageWithURLRequest:size:scale:clipped:resizeMode:priority:attribution:progressBlock:partialLoadBlock:completionBlock:]_block_invoke_2 (in DocPlatform) (RCTImageLoader.mm:0)
7 | 5 libdispatch.dylib 0x00000001829fd9a8 0x00000001829fd9a8
8 | 6 libdispatch.dylib 0x00000001829fe524 0x00000001829fe524
9 | 7 libdispatch.dylib 0x00000001829a6b54 _dispatch_sema4_timedwait (in libdispatch.dylib) + 40
10 | 8 libdispatch.dylib 0x00000001829b3438 _dispatch_async_and_wait_invoke (in libdispatch.dylib) + 92
11 | 9 libdispatch.dylib 0x00000001829b3bf8 _dispatch_async_and_wait_invoke_and_complete_recurse (in libdispatch.dylib) + 152
12 | 10  libsystem_pthread.dylib         0x0000000182a4fb38 _pthread_wqthread + 212

**Comment by chengfang1103** [comment]
caused by:Application received signal 11
--
1 | callStackSymbols: {
2 | 0   libobjc.A.dylib                 0x0000000182a56b30 objc_msgSend + 16
3 | 1 CoreFoundation 0x0000000182c12dbc -[NSArray sortedArrayFromRange:options:usingComparator:] (in CoreFoundation) + 1084
4 | 2 DocPlatform 0x00000001008ee54c -[RCTImageLoader imageDataDecoderForData:] (in DocPlatform) (RCTImageLoader.mm:0)
5 | 3 DocPlatform 0x00000001008f242c -[RCTImageLoader decodeImageData:size:scale:clipped:resizeMode:completionBlock:] (in DocPlatform) (RCTImageLoader.mm:0)
6 | 4 DocPlatform 0x00000001008f1bd8 __140-[RCTImageLoader loadImageWithURLRequest:size:scale:clipped:resizeMode:priority:attribution:progressBlock:partialLoadBlock:completionBlock:]_block_invoke_2 (in DocPlatform) (RCTImageLoader.mm:0)
7 | 5 libdispatch.dylib 0x00000001829fd9a8 0x00000001829fd9a8
8 | 6 libdispatch.dylib 0x00000001829fe524 0x00000001829fe524
9 | 7 libdispatch.dylib 0x00000001829a6b54 _dispatch_sema4_timedwait (in libdispatch.dylib) + 40
10 | 8 libdispatch.dylib 0x00000001829b3438 _dispatch_async_and_wait_invoke (in libdispatch.dylib) + 92
11 | 9 libdispatch.dylib 0x00000001829b3bf8 _dispatch_async_and_wait_invoke_and_complete_recurse (in libdispatch.dylib) + 152
12 | 10  libsystem_pthread.dylib         0x0000000182a4fb38 _pthread_wqthread + 212

**Comment by maojunlong** [comment]
I meet it, too

**Comment by cortinico** [comment]
Closed as invalid (not following the issue template)
