### ISSUE TITLE
iOS 14+ `<Image />` only showing first frame of WebP animations

### ISSUE THREAD

**Issue by btroia** [facebook/react-native#31654]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description

The latest RN [documentation](https://github.com/facebook/react-native-website/pull/2418) indicates full support for WebP images on iOS "out of the box" - however, it only appears to load static WebP's - animated WebP's do not play (only first frame is shown).

## React Native version:

0.63 (Expo), 0.64 (native)

## Steps To Reproduce

1. On iOS 14+, create an `<Image />` that loads animated WebP image uri, i.e.: [https://storage.googleapis.com/downloads.webmproject.org/webp/images/dancing_banana2.lossless.webp](https://storage.googleapis.com/downloads.webmproject.org/webp/images/dancing_banana2.lossless.webp)
2. Only the first frame is shown (no animation plays - see snack below)
3. Note that the animation *does* play when viewed in Safari (outside of RN)

## Expected Results

Animated WebP should play.

## Snack, code example, screenshot, or link to a repository:

Working example showing the issue:

https://snack.expo.io/@btroia/disrespectful-celery

(choose the iOS preview tab to view - notice only a static WebP image loads)

Should also update documentation at https://github.com/facebook/react-native-website/pull/2418 to clarify that WebP is not yet "fully" supported on iOS

**Comment by zerobertelprivat** [comment]
Any Nnews here? I also cannot make animated webp images work on IOS, on Android they work with enhancing the gradle file following the descriptions on https://reactnative.dev/docs/next/image#gif-and-webp-support-on-android

thanks in advance
