### ISSUE TITLE
Error: Workspace integrity - Could not opent workspace when try open RN project 0.64 by xcode 11.3.1 Macos Mojave

### ISSUE THREAD

**Issue by dungnguyentri3110** [facebook/react-native#31657]
Hi guys. I have problem with my project. I clone my project from my company and it build by RN version 0.64.1. Then i catch this error:
![z2533368001836_2e35163a64d90ada709685e86d903e4a](https://user-images.githubusercontent.com/54011066/120836466-cd486100-c58f-11eb-9475-16a9004f4f00.jpg)
I could not open my project also pod file.  Help me! and thanks you

**Comment by cortinico** [comment]
Closing as this version of React Native is several years old. Please re-open a new issue against the latest stable if the issue persists
