### ISSUE TITLE
Building with Hermes Enabled for iOS on RN 0.64.2 Hangs

### ISSUE THREAD

**Issue by vcellu** [facebook/react-native#31658]
## Description
Building in release mode, with Hermes enabled in iOS in XCODE 12.5 hangs Xcode

## React Native version:
System:
    OS: macOS 11.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 2.57 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.5 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.11 - /usr/local/bin/npm
    Watchman: 2021.05.31.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /Users/vel/.rvm/gems/ruby-2.6.6/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.3
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom_64, android-S | Google APIs ARM 64 v8a, android-S | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7199119
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_242-release - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.2 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. run npx react-native init SomeProject
2. enable hermes in podfile
3. rm -rf node_modules
4. rm -rf ios/pods
5. yarn
6. cd ios
7. pod install
8. open Xcode workspace
9. change scheme to build in release mode with debug executable off

Result:
There is a bunch of "The variable 'XXX' was not declared in anonymous function" messages and Xcode hangs and never completes.  I have to Force Quit Xcode

## Expected Results
I expect the project to build and run

## Snack, code example, screenshot, or link to a repository:
Just run npx react-native init WhatEver
![image](https://user-images.githubusercontent.com/42212158/120837120-5762dc00-c534-11eb-9b60-d87d3bc72df5.png)

**Comment by mmehmetAliIzci** [comment]
Might be related to https://github.com/facebook/react-native/issues/31480

**Comment by vcellu** [comment]
> Might be related to https://github.com/facebook/react-native/issues/31480

Hello, thanks for the reply.  However, this is not the same issue.  The issue referenced fails to link.   In this issue it actually builds and links and it is successful if Hermes is not enabled in iOS.

**Comment by jeffbonasso-ambifi** [comment]
Same issue for me. We have a very large project so most likely running out of memory. I tried one workaround trying to increase memory putting this in Build Phases->Bundle React Native code and images, and still hanging.

export NODE_BINARY=node
export NODE_ARGS="--max_old_space_size=8192"
../node_modules/react-native/scripts/react-native-xcode.sh

Anyone know other workarounds?

**Comment by vcellu** [comment]
this seems to have been fixed in lates 0.65.1 release.
