### ISSUE TITLE
XMLHttpRequest Keeps Failing In React Native 0.64.0

### ISSUE THREAD

**Issue by thecodecafe** [facebook/react-native#31653]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Since I upgraded to RN 0.64.0 Ajax a lot of the times fail to make a successful connection to my API, I'm currently using Axios and have two different versions installed on two separate RN 0.64.0 projects and they both behave the same way, a new project is using Axios 0.21.1 while an old one using Axios 0.19.2, I've been facing this issue for the past 4 weeks and have not been able to figure out what's going on or maybe I don't know where to look, please can anyone help with either a debugging technique or if they've experienced this and have a solution, share it here? This happens on both iOS and Android.
I'm also thinking this might be related to Flipper but I'm not sure, have removed all installations and initialization of Flipper in the project but the issue persists.

## React Native version:
```text
System:
    OS: macOS 11.3
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Memory: 33.72 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.16.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 23, 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3
      System Images: android-24 | Google Play Intel x86 Atom, android-25 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7322048
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_242 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.0 => 0.64.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Setup a fresh React Native 0.64.0 project.
2. Install Axios.
3. Try making multiple requests to a functioning API.

## Expected Results
Expected the network request to always go through so long as the API is running, but a lot of the times I keep getting a Network Error message although Axios shows this when it cannot connect to the server you are calling. This wasn't the case when I was on RN 0.62

## Snack, code example, screenshot, or link to a repository:
```javascript
import Axios from 'axios';
...
Axios.get('/a/functioning/url').then(handleSuccess).catch(handleError)
...
```

**Comment by iMJumpmxn** [comment]
Same here

**Comment by thecodecafe** [comment]
This went away without any update of any kind, the issue came from my internet service provider, I will be closing this for now.
If you experience this try doing the following.

1. Try a different internet service provider.
2. If you tried 1 and it doesn't work check that you're not connected to a sub-ISP, some ISPs are actually Sub-ISPs that are connected to the same ISP. **[ISP = Internet Service Provider, Sub-ISP = Sub Internet Service Provider]**.
3. If you are connecting through a VPN or have any network configuration other than your network password try turning it off.

Hope this helps.

cc @iMJumpmxn
