### ISSUE TITLE
Document setNativeProps for property "color"

### ISSUE THREAD

**Issue by PhilippKrone** [facebook/react-native#3166]
Hi,

using current master, it's no longer possible to use 
````javascript 
setNativeProps({color: '#FFFFFF'})
`````

as you'll get a redbox telling you that a conversion of the JSON '#FFFFFF' is not possible. Modifying the code to 
````javascript 
setNativeProps({color: React.processColor('#FFFFFF')});
````
works.

Might be useful to note that in a release note or somewhere similar.

Regards
Philipp

**Comment by PhilippKrone** [comment]
@chirag04 that was one part of my issue the other day.
@brentvatne Could you add this to the docs somewhere? Or tell me where it should be added and I'll prepare a PR :)

**Comment by mkonicek** [comment]
Yes, this behavior is going to change in 0.12. Adding this to release notes for 0.12 sounds like a good idea, thanks @PhilippKrone!

**Comment by PhilippKrone** [comment]
@mkonicek OK :) Btw. I was talking about iOS and not android, but shouldnt matter :)

**Comment by mkonicek** [comment]
OK, thanks for clarifying.
