### ISSUE TITLE
React native not launch package manager after upgrading from v0.59.2 to v0.64.1, which causes "timed out waiting module" error on real device

### ISSUE THREAD

**Issue by thainquet** [facebook/react-native#31676]
## Description
After upgrading from v0.59.2, my project stops launching metro in terminal.

## React Native version:
System:
    OS: macOS 11.2.3
    CPU: (8) arm64 Apple M1
    Memory: 602.81 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.3.0 - /opt/homebrew/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 7.15.1 - /opt/homebrew/bin/npm
    Watchman: 2021.05.31.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 29, 30
      Build Tools: 29.0.2, 30.0.3
      System Images: android-30 | Google APIs ARM 64 v8a, android-30 | Google APIs Intel x86 Atom, android-S | Google APIs ARM 64 v8a, android-S | Google Play ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7351085
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.1 => 0.64.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
1. Clone my own upgraded repo from github
2. run ```yarn``` and ```npx pod-install```
3. Open myproj.xcworkspace in xcode, then press ```Run```
4. If target device is simulator, then everything works fine. A new terminal will launch and metro start.
5. If i connect my iPhone and switch target to my iPhone, then press ```run``` again, xcode shows me that build successfully, but no terminal launched yet, then i can not open debugger or reload code. After a while of blank screen, my app on device shows me that ```Timeout waiting for modules to be invalidated```

Please note that:
- This problem only occurs on my project which is upgraded from v0.59.2 to v0.64.1. If i init a new project (in v0.64) or run my project before upgrading (in v0.59), nothing works wrong.
- I am sure that my iPhone is connected to my Macbook, and both of them are on a same wifi.
- I dont use any lines of code like ```display:none``` in my repo so other issues with that typos are not the reason of this error
- When upgrading to 0.64, i follow step by step of this helper: https://react-native-community.github.io/upgrade-helper/?from=0.59.2&to=0.64.1
- This problem only happens on real device connected to Macbook. On simulator it works fine.
## Expected Results
Metro should run in new terminal, my app should not hung in blank screen.

## Snack, code example, screenshot, or link to a repository:
None

**Comment by cortinico** [comment]
Hey,
We're cleaning up the React Native issue tracker to make sure we focus on the most important issues first.

I'm closing this one because it's stale and related to a version of React Native we no longer support. If the issue persists on the latest version, please re-open a new issue and reference this one.

Thank you.
