### ISSUE TITLE
`npx react-native run-ios` fails if the project dir contains a space

### ISSUE THREAD

**Issue by spikesagal** [facebook/react-native#31670]
## Description
The build step fails because of a faulty generated shell script:

FBReactNativeSpec.build/Script-CA3B037230D24B8B9510291201FA6A38.sh
bash: Projects/RNTestProject/node_modules/react-native/scripts/../Libraries: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code

The directory this refers to is actually named "Software Projects". Looking into the script, the command clearly does not account for spaces in the path name:
`bash -l -c 'SRCS_DIR=/Users/[redacted]/Software Projects/RNTestProject/node_modules/react-native/scripts/../Libraries CODEGEN_MODULES_OUTPUT_DIR=/Users/[redacted]/Software Projects/RNTestProject/node_modules/react-native/scripts/../React/FBReactNativeSpec/FBReactNativeSpec CODEGEN_MODULES_LIBRARY_NAME=FBReactNativeSpec /Users/[redacted]/Software Projects/RNTestProject/node_modules/react-native/scripts/generate-specs.sh' 2>&1 | tee "${SCRIPT_OUTPUT_FILE_0}"`

## React Native version:
System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
    Memory: 270.16 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 16.2.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 7.13.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.1 => 0.64.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
1. Initiate a react-native project inside a directory that contains one or more space.
2. Run Metro with `npx react-native start`
3. Build and run the app with `npx react-native run-ios`

## Expected Results
Build succeeds and iOS app starts.

**Comment by reimertz** [comment]
I symlink local files into ios iCloud `Mobile Documents` which causes triggers this issue. This happened around 2019 and was fixed. seems to be happening again.
