### ISSUE TITLE
npx runs an alpha build of react-native by default

### ISSUE THREAD

**Issue by spikesagal** [facebook/react-native#31671]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
`npx react-native --version` -> 5.0.1-alpha.2

## React Native version:
System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
    Memory: 523.71 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 16.2.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 7.13.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.1 => 0.64.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Run `npx react-native --version` from the command line.

## Expected Results
Should return a stable build.

**Comment by kelset** [comment]
👋 there - that's actually the expected behaviour as the version is the current latest for the CLI :) https://github.com/react-native-community/cli/releases
