### ISSUE TITLE
[Android] RCTNetInfo missing

### ISSUE THREAD

**Issue by mattds** [facebook/react-native#3168]
Hi, is determining reachability possible on Android using NetInfo? There are methods e.g. isConnectionMetered that seem to suggest it is, however RCTNetInfo seems to be missing in the code.

**Comment by mkonicek** [comment]
Hi @mattds, thanks for reporting! This module hasn't been open sourced yet, see https://facebook.github.io/react-native/docs/known-issues.html

**Comment by mkonicek** [comment]
We probably shouldn't have `isConnectionMetered` in JS. This will get resolved though once we open source the module.
