### ISSUE TITLE
Suddenly RN application build for Android broken

### ISSUE THREAD

**Issue by pyro366** [facebook/react-native#31693]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Please provide a clear and concise description of what the bug is. Include screenshots if needed.
Please test using the latest React Native release to make sure your issue has not already been fixed: https://reactnative.dev/docs/upgrading.html

Suddenly, without any relevant change, build for Android is broken:
_FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.facebook.react:react-native:+.
     Required by:
         project :app
         project :app > project :react-native-immediate-phone-call
         project :app > project :react-native-community_async-storage
         project :app > project :react-native-community_checkbox
         project :app > project :react-native-community_masked-view
         project :app > project :react-native-community_picker
         project :app > project :react-native-camera
         project :app > project :react-native-gesture-handler
         project :app > project :react-native-permissions
         project :app > project :react-native-safe-area-context
         project :app > project :react-native-screens
         project :app > project :react-native-splash-screen
         project :app > project :react-native-svg
      > Failed to list versions for com.facebook.react:react-native.
         > Unable to load Maven meta-data from https://nexus.pentaho.org/content/groups/omni/com/facebook/react/react-native/maven-metadata.xml.
            > Could not HEAD 'https://nexus.pentaho.org/content/groups/omni/com/facebook/react/react-native/maven-metadata.xml'.
               > Read timed out_

## React Native version:
Run `react-native info` in your terminal and copy the results here.

System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 9.66 GB / 31.85 GB
  Binaries:
    Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.11 - ~\AppData\Roaming\npm\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 19, 26, 27, 28, 29
      Build Tools: 28.0.3, 29.0.2, 30.0.2
      System Images: android-26 | Google Play Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: 22.1.7171670
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version  4.2.0.0 AI-202.7660.26.42.7351085
    Visual Studio: 16.6.30225.117 (Visual Studio Professional 2019)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.2 => 17.0.2
    react-native: ^0.64.2 => 0.64.2
    react-native-windows: ^0.64.11 => 0.64.11

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Run _react-native run-android_ or _gradlew assembleRelease_ in Android folder

## Expected Results
Describe what you expected to happen.

Aplication sucessfully built.

**Comment by Seanmclem** [comment]
any solution? sudden build broken for me for no reason

**Comment by cortinico** [comment]
> Read timed out_

This build failed due to a network issue. Specifically when trying to contact a nexus instance at nexus.pentaho.org. I'm unsure why this was needed but most likely related to a custom configuration of the build from @pyro366.

I suppose this is now resolved as it was a network timeout hence I'm closing it. Feel free to re-open if this is not the case.
@Seanmclem please open a separate issue.

**Comment by Seanmclem** [comment]
> > Read timed out_
> 
> This build failed due to a network issue. Specifically when trying to contact a nexus instance at nexus.pentaho.org. I'm unsure why this was needed but most likely related to a custom configuration of the build from @pyro366.
> 
> I suppose this is now resolved as it was a network timeout hence I'm closing it. Feel free to re-open if this is not the case.
> @Seanmclem please open a separate issue.

I solved my issue by updating my Braintree drop-in-UI library to the latest version. Thanks!
