### ISSUE TITLE
React Native build not working from command line 

### ISSUE THREAD

**Issue by migg19** [facebook/react-native#31700]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Please provide a clear and concise description of what the bug is. Include screenshots if needed.
Please test using the latest React Native release to make sure your issue has not already been fixed: https://reactnative.dev/docs/upgrading.html

## React Native version:
ystem:
    OS: macOS 11.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 234.38 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.18.3 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.6 - /usr/local/bin/npm
    Watchman: 2021.06.07.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 14.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.2 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. I am able to run my app from xcode in my iPhone but I am not able to run it from rect-native command line on my iphone
2. I am able to run it from rect-native command line on simulator
3. I used this comment npx react-native run-ios --device 
4. 

I am getting below error 

ailed to build iOS project. We ran "xcodebuild" command but it exited with error code 70. To debug build logs further, consider building your app with Xcode.app, by opening Locker.xcworkspace.
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -workspace Locker.xcworkspace -configuration Debug -scheme Locker -destination id=00008030-0001604936D3802E

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES

xcodebuild: error: Unable to find a destination matching the provided destination specifier:
                { id:00008030-0001604936D3802E }

        The requested device could not be found because no available devices matched the request.

        Available destinations for the "Locker" scheme:
                { platform:iOS Simulator, id:F366E23E-A297-483E-90DE-784BB4412177, OS:14.5, name:iPad (8th generation) }
                { platform:iOS Simulator, id:D868968A-C73C-4F6E-AE5A-B09414F2DF8B, OS:14.5, name:iPad Air (4th generation) }
                { platform:iOS Simulator, id:519DFBD1-8D27-4659-98CA-6FB0430F7C8F, OS:14.5, name:iPad Pro (9.7-inch) }
                { platform:iOS Simulator, id:65E1B5A6-2E59-45FA-9749-AC298494F944, OS:14.5, name:iPad Pro (11-inch) (3rd generation) }
                { platform:iOS Simulator, id:4B614FEC-F232-4B5B-B426-F85E13896906, OS:14.5, name:iPad Pro (12.9-inch) (5th generation) }
                { platform:iOS Simulator, id:FD60CB25-4EB6-4F8B-88A9-7604C78B6CF7, OS:14.5, name:iPhone 8 }
                { platform:iOS Simulator, id:D5DE06F9-F9D3-4BE6-B291-6D09944BD4DF, OS:14.5, name:iPhone 8 Plus }
                { platform:iOS Simulator, id:04638EDA-BC2A-4D76-91C3-9716E1CADAEC, OS:14.5, name:iPhone 11 }
                { platform:iOS Simulator, id:81EE5688-6845-4918-B890-C8B8DD610E1A, OS:14.5, name:iPhone 11 Pro }
                { platform:iOS Simulator, id:AA2359E7-6E8F-4885-8A8A-2B968B4837C4, OS:14.5, name:iPhone 11 Pro Max }
                { platform:iOS Simulator, id:18F4D9A4-FAA1-41FD-8447-CF11D8E9B8ED, OS:14.5, name:iPhone 12 }
                { platform:iOS Simulator, id:2C53A6DB-EB18-4D05-B350-83B08EDD1508, OS:14.5, name:iPhone 12 Pro }
                { platform:iOS Simulator, id:44D22FB2-BF14-4FA8-A828-549B6CEC00CE, OS:14.5, name:iPhone 12 Pro Max }
                { platform:iOS Simulator, id:B9AF26F5-9325-47CE-B245-BFA4EC6D9E11, OS:14.5, name:iPhone 12 mini }
                { platform:iOS Simulator, id:CA90276F-CC2F-43C0-9BE6-1C88C75253F0, OS:14.5, name:iPhone SE (2nd generation) }
                { platform:iOS Simulator, id:07DE7D9C-7000-4D93-92C8-1960EEEC66C8, OS:14.5, name:iPod touch (7th generation) }

        Ineligible destinations for the "Locker" scheme:
                { platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
                { platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }

info Run CLI with --verbose flag for more details.
## Expected Results
Describe what you expected to happen.

**Comment by cortinico** [comment]
Hey,
We're cleaning up the React Native issue tracker to make sure we focus on the most important issues first.

I'm closing this one because it's stale and related to a version of React Native we no longer support. If the issue persists on the latest version, please re-open a new issue and reference this one.

Thank you.
