### ISSUE TITLE
FlatList with column does not display completely the last item of each row

### ISSUE THREAD

**Issue by AlexandreGdl** [facebook/react-native#31706]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
My issue is that I have a screen with margin on each size (about 24). The screen contain a FlatList with 3 columns,
each items have a size of `Dimensions.get('screen').width / 3` and a height of 105. And the box in an item have a size of 105 on 105.
I have 2 same flatlist with a view between them to separate (design issue). 
On android it fit perfectly but on some iOS device the last item of each row is cropped.
![image](https://user-images.githubusercontent.com/46439935/121651137-9647e300-ca9a-11eb-9d5a-b44498f37bdd.png)
![image](https://user-images.githubusercontent.com/46439935/121652550-0c991500-ca9c-11eb-9f7a-299907887142.png)

## React Native version:
System:
    OS: macOS 11.2.3
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 1.03 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.13.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7351085
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.0 => 0.64.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce

1. Create a flatlist
2. Set each item width to Dimensions.get('screen').width / 3 and a height of 105
3. Set a child in the item with a size of 105/105

## Expected Results
I would like the last box of each row to be perfectly displayed on Iphone 12 emulator

## Snack, code example, screenshot, or link to a repository:
The render for the flatlist look like this :
```tsx
<View style={{ width: Dimensions.get('screen').width, height: 105 }}>
    <View style={{ width: 105, height: 105 }}>
    </View>
 </View>
```

The FLatList have no style only the `col={3}` props and keyExtractor.

**Comment by jamesxabregas** [comment]
The reason you are having issues is because you are using defined widths and different devices are going to have different widths. You should use [Layout with Flexbox](https://reactnative.dev/docs/flexbox) attributes instead.
