### ISSUE TITLE
Why is react native not upgrading the NDK version to the supported type?

### ISSUE THREAD

**Issue by murtazabeans** [facebook/react-native#31701]
## Description
I am trying to create a react native application and I am using a third party sdk package. The NDK version of latest react native is 20.1.5948944 which is marked as [Unsupported NDK Page](https://developer.android.com/ndk/downloads/older_releases) and due to the different underlying NDK versions the libc++_shared file is throwing exceptions. Please refer to the following bug for the exception:

https://github.com/facebook/react-native/issues/29377

Is there any update from the react native team to update the NDK? There are couple of work arounds we are trying but they are not the best. We are either linking the libraries statically or fetching them at runtime so that it overrides the RN one.

**Comment by safaiyeh** [comment]
You can find the NDK version here: https://github.com/facebook/react-native/blob/1465c8f3874cdee8c325ab4a4916fda0b3e43bdb/gradle.properties#L7

**Comment by maueli** [comment]
I have the same problem. Why is closed this issue?.... Change manually is not an option....
