### ISSUE TITLE
Android Release Build Crash Fatal libc : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 12702 (mqt_js)

### ISSUE THREAD

**Issue by roots-ai** [facebook/react-native#31710]
## Release build crashes on starting the app with the following error log, works well without a crash in the debug mode.

`libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 13856 (mqt_js)`

## React Native Info
System:
    OS: macOS 11.5
    CPU: (4) x64 Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
    Memory: 51.27 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.10.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.7.0 - /usr/local/bin/npm
    Watchman: 4.6.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.4 - /Users/II/.rvm/gems/ruby-2.4.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28, 29
      Build Tools: 23.0.1, 23.0.3, 25.0.0, 25.0.2, 25.0.3, 26.0.0, 26.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.2, 27.0.3, 28.0.0, 28.0.1, 28.0.2, 28.0.3, 29.0.3, 30.0.2
      System Images: android-23 | Intel x86 Atom, android-23 | Intel x86 Atom_64, android-27 | Android TV Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Android TV Intel x86 
Atom, android-28 | Wear OS Intel x86 Atom, android-28 | Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-
28 | Google Play Intel x86 Atom_64
      Android NDK: 18.1.5063045
  IDEs:
    Android Studio: 2.3 AI-162.4069837
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_222 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.2 => 17.0.2 
    react-native: ^0.64.2 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. rm android/app/src/main/assets/index.android.bundle
2. react-native bundle --platform android --dev false --entry-file index.android.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
3. abuild --variant=release 
4. Crashes on the app start.

## Expected Results
Should either throw a proper error why the issue happens even in the debug mode or should work without crashing.

**Comment by roots-ai** [comment]
Can someone please help? @shergin @mdvacca @JoshuaGross @RSNara @hramos

**Comment by octocat01** [comment]
any update on this @roots-ai  ??

**Comment by roots-ai** [comment]
> any update on this @roots-ai ??

Upgrading the entire package.json resolved that issue, but this new issue came up https://github.com/facebook/react-native/issues/32250
