### ISSUE TITLE
New project on React Native 0.64.2 is not building via Xcode 12.5.

### ISSUE THREAD

**Issue by therealkh** [facebook/react-native#31715]
## Description
New clear project is not running on physical device via Xcode. 

But npx react-native run-ios works perfect. issue is only with Xcode when trying to build and test in physical device.

Physical device: iPhone 8 Plus iOS 14.6

## Screenshot
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/65399389/121796567-697b0380-cc33-11eb-9928-a69661c8f432.png">

Getting this error:
cp: /Users/uktamhamidov/Library/Developer/Xcode/DerivedData/SQRE-arjlqbohgbkkananywponwudfhts/Build/Products/Debug-iphoneos/main.jsbundle: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code

## React Native version:
System:
    OS: macOS 11.4
    CPU: (8) x64 Apple M1
    Memory: 640.37 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.13 - /usr/local/bin/npm
    Watchman: 2021.06.07.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom, android-S | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7231092
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.2 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
1. npx react-native init ProjectName
2.open ProjectName.xcworkspace in iOS folder in project folder
3.try to build

**Comment by Makc0809** [comment]
Такая же проблема.

**Comment by hipages-ligang** [comment]
same problem

**Comment by carlg0020** [comment]
Same problem here

**Comment by d-garcia-air** [comment]
Any luck here? I have been stuck for over a week now.  I can take the same command and run it and it does generate the file correctly, just doesn't do it when its run via xcode or via run-ios

**Comment by crazydavy** [comment]
Any luck here? Been stuck on this.  I can take the command and run it via the command line and it does generate the bundle, but not when run via xcode or run-ios

**Comment by NaranjargalXD** [comment]
same
