### ISSUE TITLE
Could not GET 'https://dl.bintray.com/umsdk/release/com/facebook/react/react-native/maven-metadata.xml'

### ISSUE THREAD

**Issue by iamfindingway** [facebook/react-native#31719]
If someone meet this problem, please let me know how to solve it. Thank you

**Comment by iamfindingway** [comment]
If someone encounters this problem, please let me know how to solve it. Thank you

**Comment by matteodanelli** [comment]
I have it. Not solved yet.

**Comment by HaddyYang** [comment]
I solved it: in ```android/bulid.gradle``` file:
change ```maven { url "https://maven.google.com" }``` 
to ```maven { url "https://dl.google.com/dl/android/maven2/" }```

**Comment by vamper424** [comment]
Ok thanks. Ser You latter.
![Uploading 16410344906719078629862935114059.jpg…]()

**Comment by cortinico** [comment]
Closing as the solution was provided

> It's probably caused by the dependencies (umsdk) which look for something under jcenter (which is deprecated and seems offline for some packages)

You're trying to download `umsdk` from bintray which is going to be deprecated. You should update the `repositories{}` block in your `build.gradle` to don't include `jcenter()` but other repositories
