### ISSUE TITLE
Cannot find module 'node_modules/metro/src/JSTransformer/worker.js'

### ISSUE THREAD

**Issue by EdDevs2503** [facebook/react-native#31712]
## Description
For a few days I have had a series of problems with react-native that do not let me advance. I tried restarting my whole environment and when I install the error persists. It doesn't matter if I change branches, the project keeps giving the same error.

The error is basically that when compiling (IOS) on my device it drops the capture error. A curiosity is that in the IOS Simulator everything works fine, Android on physical devices also works correctly, this problem is exclusive to react-native on IPhone.

By the way, my physical device is IPhone 11 with IOS 14.6 and the xcode version is 12.5

## React Native version:
System:
    OS: macOS 11.4
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 214.85 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.3.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.15.1 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7351085
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: ^0.64.0 => 0.64.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Open xcode with the IOS Project of the react native project.
2. Compile the app with the device connected
3.  When it compile, open the app and the error will display after try build (it never change of 0%)

## Expected Results
I hope to compile my application and build the package to 100% and load the debug application version.

## Snack, code example, screenshot, or link to a repository:

![WhatsApp Image 2021-06-12 at 5 03 42 PM](https://user-images.githubusercontent.com/45980184/121789012-3b98af00-cba0-11eb-893c-e9d98c6574ee.jpeg)

![WhatsApp Image 2021-06-12 at 9 15 19 AM](https://user-images.githubusercontent.com/45980184/121789015-40f5f980-cba0-11eb-9472-867a9918c210.jpeg)

**Comment by thomasviaud** [comment]
Hello I had the same issue as you describe. I fixed it by reinstalling `node_modules` and running : `npx react-native start --reset-cache`

**Comment by broskees** [comment]
did you find a solution to this? I'm having the same issue. The above solution did not work for me.

**Comment by EdDevs2503** [comment]
> did you find a solution to this? I'm having the same issue. The above solution did not work for me.

Uninstall metro and try again. Metro already exist as dependency of react-native module. I installed metro 0.63.0 with RN 0.64.0 that diff is the problem.
