### ISSUE TITLE
New app does not work from react-native-cli but does work from expo-cli in iOS Simulator

### ISSUE THREAD

**Issue by MaazF94** [facebook/react-native#31721]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
I was trying to create a new react native app with the react-native-cli and ran the command "npx react-native init awesomeProject". The new project is created properly but, when I run the app using the iOS simulator, I get inconsistent build errors. If I create a new app with expo init awesomeProject and use "bare", it does run in the iOS simulator. 

Here is an example of the build error:
`The following build commands failed:
        CompileC /Users/maazfitter/Library/Developer/Xcode/DerivedData/testRnApp-bjcqqcgksnwejcbdxsuwrkdxxjfa/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-RCTSettings.build/Objects-normal/x86_64/RCTSettingsManager.o /Users/maazfitter/VS\ Code\ Projects/testRnApp/node_modules/react-native/Libraries/Settings/RCTSettingsManager.mm normal x86_64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)`

This error is inconsistent and sometimes shows "glog-dummy" files instead of "RCTSettingsManager".

## React Native version:
`System:
    OS: macOS 11.4
    CPU: (8) x64 Apple M1
    Memory: 41.10 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.3.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 7.0.14 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7199119
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.9.1 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: ~0.63.3 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found`

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. npx react-native init AwesomeProject
2. npx react-native run-ios

## Expected Results
The application should run without build errors

**Comment by themohitkhandal** [comment]
> Please provide all the information requested. Issues that do not follow this format are likely to stall.
> 
> ## Description
> I was trying to create a new react native app with the react-native-cli and ran the command "npx react-native init awesomeProject". The new project is created properly but, when I run the app using the iOS simulator, I get inconsistent build errors. If I create a new app with expo init awesomeProject and use "bare", it does run in the iOS simulator.
> 
> Here is an example of the build error: `The following build commands failed: CompileC /Users/maazfitter/Library/Developer/Xcode/DerivedData/testRnApp-bjcqqcgksnwejcbdxsuwrkdxxjfa/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-RCTSettings.build/Objects-normal/x86_64/RCTSettingsManager.o /Users/maazfitter/VS\ Code\ Projects/testRnApp/node_modules/react-native/Libraries/Settings/RCTSettingsManager.mm normal x86_64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (1 failure)`
> 
> This error is inconsistent and sometimes shows "glog-dummy" files instead of "RCTSettingsManager".
> 
> ## React Native version:
> `System: OS: macOS 11.4 CPU: (8) x64 Apple M1 Memory: 41.10 MB / 8.00 GB Shell: 5.8 - /bin/zsh Binaries: Node: 15.3.0 - /usr/local/bin/node Yarn: Not Found npm: 7.0.14 - /usr/local/bin/npm Watchman: 4.9.0 - /usr/local/bin/watchman Managers: CocoaPods: 1.10.1 - /usr/local/bin/pod SDKs: iOS SDK: Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4 Android SDK: Not Found IDEs: Android Studio: 4.1 AI-201.8743.12.41.7199119 Xcode: 12.5/12E262 - /usr/bin/xcodebuild Languages: Java: 11.0.9.1 - /usr/bin/javac Python: 2.7.16 - /usr/bin/python npmPackages: @react-native-community/cli: Not Found react: 16.13.1 => 16.13.1 react-native: ~0.63.3 => 0.63.4 react-native-macos: Not Found npmGlobalPackages: *react-native*: Not Found`
> 
> ## Steps To Reproduce
> Provide a detailed list of steps that reproduce the issue.
> 
> 1. npx react-native init AwesomeProject
> 2. npx react-native run-ios
> 
> ## Expected Results
> The application should run without build errors

Same Issue

**Comment by cortinico** [comment]
Closing as the version of React Native is too old and is not actionalbe for us
