### ISSUE TITLE
App Store-ITMS-90338: Non-public API usage《_isKeyDown, _modifiedInput, _modifierFlags, currentSession， handleNotification:, onSuccess:, setCategoryID:》

### ISSUE THREAD

**Issue by siwei123** [facebook/react-native#31726]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
![image](https://user-images.githubusercontent.com/17057163/122035966-9da61e00-ce05-11eb-9e91-38a4912407eb.png)
以上图中部分api的使用被苹果认为是私有api，不允许通过

## React Native version:
0.64.1

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.使用RN0.64.1的iOS版本打包上传至苹果商店，即可复现
2.

## Expected Results
希望可以正常通过苹果的审核，进行上线发布

## Snack, code example, screenshot, or link to a repository:
Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by cortinico** [comment]
Closing as issue is stale + not in English
In this issue tracker we accept only issues that are in English.
Please consider translating it to English and reopening it.
Thanks.
