### ISSUE TITLE
in jsi file 'cassert' file not found 

### ISSUE THREAD

**Issue by wulongwang** [facebook/react-native#31734]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
in the demo project 'AwesomeProject', AppDelegate.m  '#import <jsi/jsi.h>' then cmd + B, the result is   'cassert' file not found 

## React Native version:
System:
    OS: macOS 11.3.1
    CPU: (8) x64 Apple M1
    Memory: 117.88 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.16.0 - /usr/local/bin/npm
    Watchman: 2021.06.07.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7351085
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.2 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.  AppDelegate.m  #import <jsi/jsi.h>
2. cmd + B

## Expected Results
in the AppDelegate.m  I can #import <jsi/jsi.h> 

## Snack, code example, screenshot, or link to a repository:
![image](https://user-images.githubusercontent.com/3376097/122341038-9dc52b80-cf75-11eb-90fb-8d55b06cc88c.png)
![image](https://user-images.githubusercontent.com/3376097/122341168-c1887180-cf75-11eb-837f-0eb7ad6141fe.png)
![image](https://user-images.githubusercontent.com/3376097/122341210-cea56080-cf75-11eb-92c4-51e8dbc43993.png)

**Comment by briantanabe** [comment]
Running into this as well, did you find a fix @wulongwang

**Comment by Pingou** [comment]
@briantanabe Same issue here, which version of RN do you use? I use 0.70.8

**Comment by briantanabe** [comment]
I'm using expo 48 and react-native 71.8

**Comment by briantanabe** [comment]
Has anyone managed to solve this? @Pingou @wulongwang

**Comment by luisflorido** [comment]
I was trying to update from SDK 45 to 49 and had this exactly issue, after running the project in xcode and not from expo saw the issue in my case was with `expo-gl`, just reinstalled the package and removed `expo-gl-cpp` (probably the main issue), I got more errors but with [react native upgrade tool](https://react-native-community.github.io/upgrade-helper/) fixed all the issues
