### ISSUE TITLE
Android. Black background instead of all images

### ISSUE THREAD

**Issue by Desintegrator** [facebook/react-native#31730]
## Description
after upgrading RN version from 0.59.9 to 0.64.2 all images disappeared in production apk build. Developing version works fine. I investigated that images present at apk sources but all is blank. How is it possible and how to fix it?
![image](https://user-images.githubusercontent.com/17068034/122086183-e74e3300-ce1c-11eb-87d5-01caad25762d.png)

## React Native version:
```
System:
    OS: macOS 11.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 1.58 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.15.1 - /usr/local/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 6.14.9 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: Not Found
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.9.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.1 => 17.0.2 
    react-native: ^0.64.2 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce

1. upgrade RN version
2. build production apk

## Expected Results
 i should see all images

**Comment by Desintegrator** [comment]
I've created simplified copy of our project here: https://github.com/Desintegrator/images_bug
And updated React / RN versions.
To reproduce you need to download project, install packages, configure signing (not able to provide production keys) and make production release with `./gradlew assembleRelease`

**Comment by Desintegrator** [comment]
Here are production (broken) and development (working) builds screens
![telegram-cloud-photo-size-2-5267377604854396376-y](https://user-images.githubusercontent.com/17068034/130370008-8f8d8aaa-1e9d-4439-8cea-c7608d943380.jpg)
![telegram-cloud-photo-size-2-5267377604854396377-y](https://user-images.githubusercontent.com/17068034/130370010-85f1885f-3432-40a2-ac98-15f4af7f4ad0.jpg)

**Comment by s5unanow** [comment]
@Desintegrator , hey, did you managed to solve the issue?

**Comment by Desintegrator** [comment]
@s5unanow Hey, as i can remember (for now this issue avoid me) i was need to build app, unarchive it, replace broken assets with normal and then again pack it, optimise with zipalign, and sign

**Comment by s5unanow** [comment]
Hey @Desintegrator , thanks for your reply! 
In my case Proguard blocked copying, so I had to modify keep.xml and put my images into whitelist.
