### ISSUE TITLE
React Native run-android error in emulator "Could not get BatchedBridge, make sure your bundle is packaged correctly"

### ISSUE THREAD

**Issue by ShivamS136** [facebook/react-native#31735]
## Description
I am using Android Studio Emulator and configured `react-native-web` support as per [this doc][1] as well. But Whenever I run `npm run android` it gets the below error:

[![Error Screenshot][2]][2]

**"Could not get BatchedBridge, make sure your bundle is packaged correctly"**

I tried many solutions out there like:
- Delete `node_modules` and re install
- Clear cache in `react-native start --reset-cache`
- Run `react-native start` before `run-android`
- check `.npmrc`

But no solution yet. There is no error in `metro` terminal as well.

Below is my `package.json`

```json
{
  "name": "shipdemo",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start --reset-cache",
    "test": "jest",
    "lint": "eslint .",
    "web": "webpack serve -d source-map --mode development --config \"./web/webpack.config.js\" --inline --color --hot",
    "build:web": "webpack --mode production --config \"./web/webpack.config.js\" --hot"
  },
  "dependencies": {
    "react": "17.0.1",
    "react-dom": "^17.0.2",
    "react-native": "0.64.2",
    "react-native-web": "^0.16.5"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "babel-loader": "^8.2.2",
    "babel-plugin-module-resolver": "^4.1.0",
    "babel-plugin-react-native-web": "^0.16.5",
    "eslint": "7.14.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.64.0",
    "react-test-renderer": "17.0.1",
    "url-loader": "^4.1.1",
    "webpack": "^5.39.0",
    "webpack-cli": "^4.7.2",
    "webpack-dev-server": "^3.11.2"
  },
  "jest": {
    "preset": "react-native-web"
  }
}
```

  [1]: https://dev.to/shivams136/create-react-native-app-for-android-ios-and-web-without-expo-48lc
  [2]: https://i.stack.imgur.com/Hrj2C.png

## React Native version:
```sh
System:
    OS: Windows 10 10.0.19042
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
    Memory: 607.87 MB / 7.87 GB
  Binaries:
    Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 29, 30
      Build Tools: 29.0.2, 30.0.3
      System Images: android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: Not Found
  Languages:
    Java: 1.8.0_292 - C:\Program Files\OpenJDK\openjdk-8u292-b10\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.2 => 0.64.2
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Start Emulator from Android studio.
![image](https://user-images.githubusercontent.com/32218762/122351711-08716980-cf6c-11eb-841e-b6bf5c839d8b.png)

2. Run emulator.
3. run `npx react-native run-android` or `npm run android`

## Expected Results
The basic App created should be visible in the emulator.

## Snack, code example, screenshot, or link to a repository:
https://snack.expo.io/2DGiPiVW4 
Screenshot is attached above.

**Comment by ShivamS136** [comment]
### UPDATE:

After enabling [Pause on Caught Exception](https://stackoverflow.com/questions/2233339/javascript-is-there-a-way-to-get-chrome-to-break-on-all-errors/17324511#17324511), I got below in the dev tools.

![image](https://user-images.githubusercontent.com/32218762/122354398-951d2700-cf6e-11eb-83be-fa752c74eca7.png)

**Comment by ShivamS136** [comment]
At the same time, Now I got an error in `metro` as well
![image](https://user-images.githubusercontent.com/32218762/122354816-fc3adb80-cf6e-11eb-87f7-fd7423c8b768.png)

**Comment by cortinico** [comment]
Hey,
We're cleaning up the React Native issue tracker to make sure we focus on the most important issues first.

I'm closing this one because it's stale and related to a version of React Native we no longer support. If the issue persists on the latest version, please re-open a new issue and reference this one.

Thank you.
