### ISSUE TITLE
Elements getting cut off on Android

### ISSUE THREAD

**Issue by danlupascu** [facebook/react-native#31738]
## Description
Part of the screen is getting cut off on Android.  

We have a screen that has a chat and a live video. The video has some controls buttons that appear on tap. The problem is that sometimes the buttons would get cut off. It happens randomly. Check the screenshot below and you'll see that the top "Back" button is not visible at all, while the "Chat" button is cut off. Also, not only the elements from our app are cut off - even the native layout bounds we enabled from developer options are getting cut off.

However, the video is still visible for some reason.

## React Native version:
```
System:
    OS: macOS 11.4
    CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
    Memory: 155.33 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 6.12.0 - ~/.nvm/versions/node/v12.13.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28, 29
      Build Tools: 23.0.1, 25.0.2, 26.0.1, 26.0.2, 27.0.3, 28.0.2, 28.0.3, 29.0.2, 29.0.3
      System Images: android-27 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7199119
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_161 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.0 => 0.64.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Unfortunately haven't found a way to reproduce this. It looks like it's random.

## Expected Results
Check the screenshots

### Here is how it should look like (note the back button and the chat button)
<img src="https://imgshare.org/i/V3t82251.jpeg" alt="good" width="400" />

### Here is how it actually looks like (note that the back button is missing, the chat button is cut off, and the native layout bounds are also cut off)

<img src="https://imgshare.org/i/0eT62252.jpeg" alt="bad" width="400" />

### A link to a recording
https://drive.google.com/file/d/11vjPC4GD1r-9y81JmrmV5A6qbQttQZYK/view?usp=sharing

**Comment by cortinico** [comment]
Closing as all the links are broken and this issue is probably stale.
Please reopne against the latest stable if the issue persists
