### ISSUE TITLE
El capitan: No such file or directory

### ISSUE THREAD

**Issue by PhilippKrone** [facebook/react-native#3174]
Since upgrading to El Capitan, I cannot connect to the react packager when using a local IP (e.g. 192.168.178.26), however it's working with "localhost".
**Please note:** It's only not working when using an iOS 9.0 simulator. The 8.x simulators are working quite fine.
Not working:

````javascript
jsCodeLocation = [NSURL URLWithString:@"http://192.168.178.26:8081/index.ios.bundle?platform=ios"];
````

Working:
````javascript
jsCodeLocation = [NSURL URLWithString:@"http://localhost:8081/index.ios.bundle?platform=ios"];
````

I get the following redbox:
![simulator screen shot 01 10 2015 13 31 17](https://cloud.githubusercontent.com/assets/11861008/10219615/bae86a94-6840-11e5-8d25-94c18aac44c3.png)

**Comment by mschwartz** [comment]
I have the same issue.

The problem exists in the iIOS9 simulator for Xcode.  You can install the iOS 8.4 simulator in Xcode and that one works.

**Comment by sergiou87** [comment]
Same problem here with React and any other `NSURLSessionDataTask`.

**Comment by prenaux** [comment]
Same here.

**Comment by jaygarcia** [comment]
Silly Question to you guys? does "ping localhost" resolve itself? Maybe it was removed from etc/hosts?  

I purposely have not upgraded to the latest OS X so that I don't have to deal w/ issues like this (yet)

**Comment by renatomcamilio** [comment]
Same for me. The problem only occurs on simulator, it works fine on the device itself running iOS 9.

**Comment by PhilippKrone** [comment]
yep, exactly!

**Comment by renatomcamilio** [comment]
So, turns out to be something expected from iOS 9. Take a look here: https://developer.apple.com/news/?id=08282015a   
Suggestion: keep it mapped on /etc/hosts to the desired IP and it should be fine.

**Comment by sergiou87** [comment]
If I understood, that doesn't mean this issue is expected (if it were… why did it work on iOS 9 or tvOS 9 simulators on Yosemite?). That just means that you shouldn't rely on IPv4 addresses (specially if you hardcode them) because at some point only IPv6 addresses will be valid. But right now `127.0.0.1` works, and other IPs in the same LAN work, it's just the LAN IP of the machine running the code the one that doesn't work :confused:

**Comment by jsierles** [comment]
If you're always running the simulator on localhost and only need the IP for devices, this might help:

```
#if TARGET_IPHONE_SIMULATOR

// point to localhost here

#else

// point to fixed IP

#endif
```

**Comment by mschwartz** [comment]
The #if is a compile time option.  It would be ideal to have the startup code detect device or simulator and choose between two addresses that way.

**Comment by dbankier** [comment]
I think it is a networking issue in the simulators. See: https://github.com/dbankier/TiShadow/issues/458#issuecomment-146097477.

We applied a similar work around to @jsierles in the TiShadow project.

**Comment by sergiou87** [comment]
According to Xcode 7.1 beta 3 release notes: http://adcdownload.apple.com/Developer_Tools/Xcode_7.1_beta_3/Xcode_7.1_beta_3_Release_Notes.pdf

It's a known issue. Hopefully it'll be fixed in 7.1 beta 4 and 7.0.2 :smile: 
![image](https://cloud.githubusercontent.com/assets/1083228/10345350/5949328a-6d29-11e5-89e5-ed2d5804f2a1.png)

**Comment by ilake** [comment]
Same here.

**Comment by aleclarson** [comment]
:+1:

**Comment by mozillo** [comment]
Same problem

**Comment by alidawud** [comment]
Same here.

**Comment by ninamanalo** [comment]
in simulator, how about running it with option 2 (bundle)?

**Comment by fibbers** [comment]
If you have an IPv6 address, that seems to work both on the simulator and device (iOS 9.1):

- you get your IPv6 address with: `ifconfig | grep inet6 | grep -v fe80::`
- in `AppDelegate.m` surround it with brackets, so that:

```objective-c
jsCodeLocation = [NSURL URLWithString:@"http://[abab:1234:1234:abab:aaaa:bbbb:1111:2222]:8081/index.ios.bundle?platform=ios&dev=true"];
```

**Comment by jsierles** [comment]
@facebook-github-bot answered
