### ISSUE TITLE
Scrolling Issue with React Native Web Build 

### ISSUE THREAD

**Issue by sinhapaurush** [facebook/react-native#31744]
In React native's web build I am unable to fix any of View and even Image Background, I want my background to be fixed but it's getting scrolled when page is scrolled.

I am using EXPO CLI, I guess it's an bug in web build.

**Comment by safaiyeh** [comment]
Hi @sinhapaurush please file an issue with either react-native-web or expo. This repo is for issues with core React Native, iOS and Android.
