### ISSUE TITLE
KeyboardAvoidingView changes vertical offset when writing text in TextInput

### ISSUE THREAD

**Issue by BeeMargarida** [facebook/react-native#31746]
## Description

In Android, when using `KeyboardAvoidingView`(with any behaviour) with a `View` with an input and some padding located at the end of the screen, when writing something, the offset used in the `KeyboardAvoidingView` is lost. The keyboardVerticalOffset is already an hardcoded value that doesn't make much sense, but it should be maintained while writing. 
Using `android:windowSoftInputMode="adjustPan"`.

Things tested:
1. Tried without `SafeAreaView`: same problem
2. Using `android:windowSoftInputMode="adjustResize"` solves the problem but it might not be a usable solution for other situations (having a navbar, for example)

Also tested in physical device, the problem remains.

## React Native version:
0.64.1 (also tested with 0.64.2, the problem remains)
Devices:
* Emulator: Pixel 2 API 29 - Android 10
* Xiaomi Redmi 8 - Android 10

## Steps To Reproduce
Something like: 
```
<SafeAreaView style={{ flex: 1, paddingBottom: 0 }}>
       <KeyboardAvoidingView
               behavior={"position"}
               style={{ flex: 1, height: "100%", justifyContent: "flex-end", backgroundColor: "blue" }}
               keyboardVerticalOffset={-245}
       >
               <View style={{ paddingVertical: 8, backgroundColor: "yellow" }}>
                        <TextInput style={{ paddingVertical: 4, backgroundColor: "green" }} />
               </View>
       </KeyboardAvoidingView>
</SafeAreaView>
```

## Expected Results
The input should maintain its position when typing.

## Snack, code example, screenshot, or link to a repository:
![bug_android](https://user-images.githubusercontent.com/25725586/122550864-21d9ea80-d02c-11eb-98ef-8b3e09cdb6e3.gif)

However, in this snack, the problem does not happen: https://snack.expo.io/zqADtx3Ur

**Comment by tomtargosz** [comment]
I'm seeing the same issue, also using `android:windowSoftInputMode="adjustPan"`

**Comment by MarcosPrata** [comment]
Same here...

**Comment by OrianFrenchAppWeb** [comment]
same here,

**Comment by domenicoprestia** [comment]
Yep also here we got the same problem

**Comment by prince-sugarfit** [comment]
If you are using `android:windowSoftInputMode="adjustPan"`, keyboard by default scrolls to the current text of input.

Here is the workaround to solve it..
Set paddingBottom (around 8~10 px) to your input style.

This doesn't solve problem 100%, but it avoids keyboard to completely touch the text.

**Comment by mihailapuste** [comment]
Currently experiencing this on react-native 0.77.0 on android with newarch disabled

**Comment by jcqlfh** [comment]
This approach works for me:

```
import React, { ReactNode, useEffect, useState } from 'react';
import { SafeAreaProvider, SafeAreaView } from 'react-native-safe-area-context';
import { Dimensions, Keyboard } from 'react-native';

interface AppProvidersProps {
    children: ReactNode;
}

const AppProviders: React.FC<AppProvidersProps> = ({ children }) => {
    const [value, setValue] = useState({} as SuggestionContextValueType);
    const [height, setHeight] = useState(Dimensions.get('window').height);

    useEffect(() => {
        const keyboardShown = Keyboard.addListener('keyboardDidShow', e => {
            setHeight(
                Dimensions.get('window').height - e.endCoordinates.height,
            );
        });
        const keyboardHidden = Keyboard.addListener('keyboardDidHide', () => {
            setHeight(Dimensions.get('window').height);
        });
        const dimensionChanged = Dimensions.addEventListener('change', () => {
            setHeight(Dimensions.get('window').height);
        });

        return () => {
            keyboardShown.remove();
            keyboardHidden.remove();
            dimensionChanged.remove();
        };
    });

    return (
        <SafeAreaProvider>
            <SafeAreaView style={{ height: height }}>
                ...
            </SafeAreaView>
        </SafeAreaProvider>
    );
};

export default AppProviders;
```
