### ISSUE TITLE
npx react-native init does not work properly

### ISSUE THREAD

**Issue by MenaiAla** [facebook/react-native#31749]
## Description

I want to create a new project using this command :

`npx react-native init project-name but it freezes on this line : 

`⸨⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⸩ ⠇ rollbackFailedOptional: verb npm-session 08fef662d42ce334`

I've reinstalled `node`,`npm` but nothing has changed. 

To verify if the problem is related to `npx` or no, I tried to run `npx create-react-app project-name` and it works very well.

## React Native version:

I tried to run `npx react-native info` but it displays : 

`⸨⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⸩ ⠇ rollbackFailedOptional: verb npm-session ba05e90f993d0941`

## Expected Results

Created react-native project.

## Snack, code example, screenshot, or link to a repository:

<img width="1194" alt="Screen Shot 2021-06-19 at 4 17 48 PM" src="https://user-images.githubusercontent.com/20143684/122654975-d5370200-d146-11eb-8725-59cfd19ddd19.png">

**Comment by SConaway** [comment]
Try clearing your `npx` cache by running these steps: https://stackoverflow.com/a/66019858

**Comment by safaiyeh** [comment]
This issue should be posted in @react-native-community/cli
