### ISSUE TITLE
Add items to Top or Bottom in the FlatList is causing the scroll the position of screen. which is an unusual behavior

### ISSUE THREAD

**Issue by AwaisIbrar8** [facebook/react-native#31747]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
When I am adding new items to the data of flat list screen position is changing but I need that If I add Items on the Top or Bottom of the flat list it should not scroll. It should remain in the previous screen position. 

I also used this props as well but not working 

` maintainVisibleContentPosition={{
            minIndexForVisible: 0,
         }}`

## React Native version:
System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
    Memory: 48.07 MB / 8.00 GB
    Shell: 3.1.2 - /usr/local/bin/fish
  Binaries:
    Node: 14.14.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6858069
    Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
  Languages:
    Java: 14.0.1 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.2 => 17.0.2 
    react-native: 0.63.2 => 0.63.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. I am implementing chat using chat so I added previous messages in the data of flat list it's moving up and down.
2. When I am adding a message at the end It scrolls to the bottom is correct but adding items on the top is also moving the screen but should not move.

## Expected Results
When I add new items on the top of the data array its should not scroll even bottom or top.

## Snack, code example, screenshot, or link to a repository:
You can check the React Native Gifted Chat Library which is using a flat list for rendering messages.
Here is the link
https://www.npmjs.com/package/react-native-gifted-chat/v/next

**Comment by suwu150** [comment]
any update?
