### ISSUE TITLE
how can i build a Simulator build for iOS ? 

### ISSUE THREAD

**Issue by AmirDoreh** [facebook/react-native#31765]
## Description
i want to build a simulator build for sending to facebook review, but whatever i did , did not do the trick , how should i build a simulator build which will work ?

## React Native version:
 OS: macOS 11.4
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Memory: 707.47 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.3.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.15.1 - /usr/local/bin/npm
    Watchman: 2021.06.07.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 31.0.0
      System Images: android-27 | Google APIs Intel x86 Atom, android-28 | Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: 23.0.7272597-beta3
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_291 - /usr/bin/javac
  npmPackages:

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.  go to schema and edit it to release then build 
2. go to the build folder and try run it through ios-sim launch /path/to/app.app

## Expected Results
run smoothly on emulator

## Description:
i tried to convert the plist to binary and still i got the same problem and app stopped on launch and got the same error:

```
An error was encountered processing the command (domain=FBSOpenApplicationServiceErrorDomain, code=1):
The request to open "app.app.co" failed.
The request was denied by service delegate (SBMainWorkspace) for reason: Unspecified ("null").
Underlying error (domain=FBSOpenApplicationErrorDomain, code=1):
	The operation couldn’t be completed. (null)
	(null)
app.app.co: -1
/usr/local/Cellar/ios-sim/9.0.0/libexec/lib/node_modules/ios-sim/node_modules/bplist-parser/bplistParser.js:55
    throw new Error("Invalid binary plist. Expected 'bplist' at offset 0.");
          ^

Error: Invalid binary plist. Expected 'bplist' at offset 0.
    at exports.parseBuffer (/usr/local/Cellar/ios-sim/9.0.0/libexec/lib/node_modules/ios-sim/node_modules/bplist-parser/bplistParser.js:55:11)
    at tryParseBuffer (/usr/local/Cellar/ios-sim/9.0.0/libexec/lib/node_modules/ios-sim/node_modules/bplist-parser/bplistParser.js:28:18)
    at /usr/local/Cellar/ios-sim/9.0.0/libexec/lib/node_modules/ios-sim/node_modules/bplist-parser/bplistParser.js:46:7


```

**Comment by xiongemi** [comment]
pass in -sdk iphonesimulator like `xcodebuild -workspace App.xcworkspace -scheme App -configuration Debug -sdk iphonesimulator -derivedDataPath ./build -quiet`

**Comment by cortinico** [comment]
Hey,
We're cleaning up the React Native issue tracker to make sure we focus on the most important issues first.

I'm closing this one because it's stale and related to a version of React Native we no longer support. If the issue persists on the latest version, please re-open a new issue and reference this one.

Thank you.
