### ISSUE TITLE
Error due to RegEx Lookbehind: Invalid regular expression: invalid group specifier name

### ISSUE THREAD

**Issue by chriswayg** [facebook/react-native#31767]
## Description

The following regex code runs fine in node.js, but causes an error in React Native:

```
mdText = mdText.replace(/(?<!^)[ ]*\n/gm, '  \n');
```

![image](https://user-images.githubusercontent.com/13681327/123110767-f7928d80-d46e-11eb-8a1b-21b76d1ef8b1.png)

## Environment:
System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
    Memory: 1.19 GB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.17.0 - ~/.nodenv/versions/14.17.0/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 6.14.13 - ~/.nodenv/versions/14.17.0/bin/npm
    Watchman: 2021.06.07.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 28, 29, 30
      Build Tools: 28.0.2, 28.0.3, 29.0.2
      System Images: android-23 | Google APIs Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7322048
    Xcode: 11.3.1/11C505 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.8 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce

This issue has been brought up at least twice before:

Example: https://github.com/facebook/react-native/issues/22222

**Comment by Einere** [comment]
RN v0.63.2 occur same error when using positive lookbehind `/(?<=\s)/`
