### ISSUE TITLE
react-native run-ios does not work | build failed | ....

### ISSUE THREAD

**Issue by rockstar00711** [facebook/react-native#31763]
## Description

First error: 
error Failed to build iOS project. We ran “xcodebuild” command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening awesome.xcworkspace.

couple of warnings: 
warning: Mapping architecture arm64 to x86_64. Ensure that this target’s Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target ‘React-jsiexecutor’ from project ‘Pods’)
warning: None of the architectures in ARCHS (i386, x86_64) are valid. Consider setting ARCHS to $(ARCHS_STANDARD) or updating it to include at least one value from VALID_ARCHS (i386, x86_64) which is not in EXCLUDED_ARCHS (x86_64). (in target ‘React-jsiexecutor’ from project ‘Pods’)

last error: 
The following build commands failed:
	PhaseScriptExecution [CP]\ Copy\ XCFrameworks /Users/user/Library/Developer/Xcode/DerivedData/awesome-fgqovmpltvmybwfboirbhkzybyqx/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/OpenSSL-Universal.build/Script-329FE3CB18B30DBF34BE47031BE8F397.sh
(1 failure)

## React Native version:
OS: macOS 10.15
  CPU: (6) x64 Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
  Memory: 321.19 MB / 16.00 GB
  Shell: 5.7.1 - /bin/zsh
 Binaries:
  Node: 14.17.0 - /usr/local/bin/node
  Yarn: 1.22.10 - /usr/local/bin/yarn
  npm: 6.14.13 - /usr/local/bin/npm
  Watchman: 4.9.0 - /usr/local/bin/watchman
 Managers:
  CocoaPods: 1.10.1 - /usr/local/bin/pod
 SDKs:
  iOS SDK:
   Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  Android SDK:
   API Levels: 30
   Build Tools: 30.0.3, 31.0.0
   System Images: android-29 | Android TV Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
   Android NDK: Not Found
 IDEs:
  Android Studio: 4.2 AI-202.7660.26.42.7351085
  Xcode: 11.2/11B52 - /usr/bin/xcodebuild
 Languages:
  Java: 1.8.0_292 - /usr/bin/javac
 npmPackages:
  @react-native-community/cli: Not Found
  react: 17.0.1 => 17.0.1 
  react-native: 0.64.2 => 0.64.2 
  react-native-macos: Not Found
 npmGlobalPackages:
  *react-native*: Not Found

## Steps To Reproduce
What I did: 
- remove react-native cli globally and reinstall it.
- delete pods and pod lock files and reinstall pods
- commented some lines in pod file such as use_flipper!()
- deleted build directory
- ...

## Expected Results
react native run ios command line works properly.

## Snack, code example, screenshot, or link to a repository:
Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by lsbyerley** [comment]
I am seeing this same error, any suggestions for fixing?

I am on react-native `0.64.2` as well

```
PhaseScriptExecution [CP]\ Copy\ XCFrameworks /Library/Developer/Xcode/DerivedData/myNativeApp-czfxrkkwqvkhqefqkufpfwozvtex/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/OpenSSL-Universal.build/Script-329FE3CB18B30DBF34BE47031BE8F397.sh (in target 'OpenSSL-Universal' from project 'Pods')
```

**Comment by FerminIriarte-0324** [comment]
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'ProjectName' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'ProjectNameTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
  end
end






Please check your pod file. my pod file is something like above.
I cannot remember how to fix that but hope this help to you.

**Comment by FerminIriarte-0324** [comment]
if this not work then please build app on xcode.

**Comment by FerminIriarte-0324** [comment]
if also error exists, please let me know about that. I really don't remember now. :D
