### ISSUE TITLE
main.jsbundle is not getting updated

### ISSUE THREAD

**Issue by deepakverma4** [facebook/react-native#31784]
I was getting ``` cannot find main.jsbundle``` error. 

so i manually created bundle using 
```react-native bundle --entry-file='index.js' --bundle-output='./ios/main.jsbundle' --dev=false --platform='ios' --assets-dest='./ios/'```

now again i was getting same error, so i manually added the ```main.jsbundle``` file via ```Add files to project``` option and now my build was successful but i am missing back button icon. also ```the main.jsbundle``` is not getting modified when is creating archive. 

Someone please help me solve this issue.

**Comment by liqiankl** [comment]
Hey @deepakverma4 have you solved this issue ?

**Comment by bdtren** [comment]
Hi,
In my case, I replicated 2 issues:

- First issue is the development build cannot connect with metro. It working after called the command above but change the `--dev` to true. Full command:
```
npx react-native bundle --entry-file index.js --platform ios --dev true --bundle-output ios/main.jsbundle --assets-dest ios
```

- Second issue is like above, the archived build not have the updated data. I fixed it by go to  XCode > project name > Build Phases > Bundle React Native code and images and replace the shell code with this:

```
set -e

WITH_ENVIRONMENT="../node_modules/react-native/scripts/xcode/with-environment.sh"
REACT_NATIVE_XCODE="../node_modules/react-native/scripts/react-native-xcode.sh"

/bin/sh -c "$WITH_ENVIRONMENT $REACT_NATIVE_XCODE"

```

**Comment by cortinico** [comment]
Closing as stale and not following the issue template
