### ISSUE TITLE
Renaming `master` branch to `main`

### ISSUE THREAD

**Issue by yungsters** [facebook/react-native#31788]
As a part of a broad effort to avoid insensitive terminology in our software, we are renaming our default branch from `master` to `main`. We recognize that this is only a small step, but it is an opportunity to make our project and community more welcoming to historically marginalized communities.

### How does this impact my development process?
There should be very little impact. GitHub will surface the branch name change in your fork, if you have one. For new forks, you will automatically have `main` as the default branch.

We encourage the use of feature branches for local development. The only change in practice is changing which branch your feature branch is started from. When sending Pull Requests on GitHub, the target will default to our `main` branch, so there are no changes to make there.

### I have a lot of tools that depend on `master` being the upstream branch name. How can I fix that?
`master` has always been only a default value and a number of projects have used other names for their primary development branch for years. We encourage updating your tooling to instead dynamically determine the branch to use. [This article](https://aj.codes/post/branch-agnostic-git-aliases/) provides insight into how you can do that. Additionally, you can always set up a branch locally of any name to track our `main` branch.

### I'd like to do this for my own projects, do you have any documentation on how this works?
[GitHub has published a guide documenting their tooling.](https://github.com/github/renaming) We recommend reading that and the accompanying documentation.

If you're a Facebook employee looking to do this for a project you maintain, please reach out to the Open Source Team.

**Comment by yungsters** [comment]
I'll be updating this comment with a list of existing references to `master` in the React Native repository.

**Comment by yungsters** [comment]
Here are Facebook repositories specific to React Native that we will also eventually update.

- [facebook/hermes](https://github.com/facebook/hermes)
- [facebook/metro](https://github.com/facebook/metro)
- [facebook/react-native-website](https://github.com/facebook/react-native-website)

**Comment by TheSavior** [comment]
Are there references in the [React Native CLI](https://github.com/react-native-community/cli) or [releases](https://github.com/react-native-community/releases) repo that might need to get updated? Both have scripts that might references the main branch of React Native

**Comment by ljharb** [comment]
Another tip: if you replace "master" in any URL with "HEAD", github will redirect properly, even if you change to something other than "main" now or in the future.

**Comment by yungsters** [comment]
> Another tip: if you replace "master" in any URL with "HEAD", github will redirect properly, even if you change to something other than "main" now or in the future.

Thanks, @ljharb! I will definitely make use of your suggestion for any URLs.

**Comment by yungsters** [comment]
This is now in progress. The `master` branch has been renamed to `main`.

Contributors will probably want to update local clones following the steps documented here: https://docs.github.com/en/github/administering-a-repository/managing-branches-in-your-repository/renaming-a-branch#updating-a-local-clone-after-a-branch-name-changes

```
$ git branch -m master main
$ git fetch origin
$ git branch -u origin/main main
$ git remote set-head origin -a

# Optional, removes tracking references to `master`.
$ git remote prune origin
```

The bot that syncs code between Facebook's internal repository and GitHub has been paused until all configuration changes have been landed. Then I will re-enable the bot and we'll see what needs attention after that.

**Comment by yungsters** [comment]
Actually, contributors will want to just go into the GitHub settings of their fork and rename `master` to `main`. Then navigate to your fork and you'll see the commands to run locally to update your fork checkout.

**Comment by yungsters** [comment]
Go to: https://github.com/{{YOUR-USERNAME}}/react-native/settings/branches

![CleanShot 2021-07-15 at 12 11 31](https://user-images.githubusercontent.com/55161/125844187-6518d528-b86b-47b7-9d46-e7e412eb4f23.png)

**Comment by NullPainter2** [comment]
Do You have a study which proves that "master" vs "main" is an actual problem and not a made up one?

Also, don't You think that maybe fixing some of thousands of bugs RN has would make it more friendly for new people? Like for example right now RN does not even run in new Xcode :D

**Comment by yungsters** [comment]
This change reflects the React Native team's commitment to a respectful and welcoming project for everyone, including underrepresented groups. It is also aligned with changes [happening in the Git ecosystem](https://sfconservancy.org/news/2020/jun/23/gitbranchname/).

I do acknowledge that we have quite a backlog to work through, and we have plans to make progress there in the coming months. If you are still running into trouble with Xcode 12.5, please take a look at and chime in on https://github.com/facebook/react-native/issues/31480.

**Comment by yungsters** [comment]
Closing this PR because the branch rename was completed last week.

**Comment by NullPainter2** [comment]
Do I understand it correctly that You can't give me proof because there is none? No study. No research.
