### ISSUE TITLE
Task 'installDebug' not found in project ':app'.

### ISSUE THREAD

**Issue by PulasthiAbey** [facebook/react-native#31803]
`info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 1190 file(s) to forward-jetify. Using 4 workers...
info JS server already running.
/bin/sh: 1: /home/darkpheonix/Android/Sdk/platform-tools/adb: not found
info Launching emulator...
error Failed to launch emulator. Reason: No emulators found as an output of `emulator -list-avds`.
warn Please launch an emulator manually or connect a device. Otherwise app may fail to launch.
info Installing the app...

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.8/userguide/command_line_interface.html#sec:command_line_warnings

FAILURE: Build failed with an exception.

* What went wrong:
Task 'installDebug' not found in project ':app'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Task 'installDebug' not found in project ':app'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s

    at makeError (/media/darkpheonix/dptech/Projects/refactored-invention/tiny-app/node_modules/execa/index.js:174:9)
    at /media/darkpheonix/dptech/Projects/refactored-invention/tiny-app/node_modules/execa/index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async runOnAllDevices (/media/darkpheonix/dptech/Projects/refactored-invention/tiny-app/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:94:5)
    at async Command.handleAction (/media/darkpheonix/dptech/Projects/refactored-invention/tiny-app/node_modules/@react-native-community/cli/build/index.js:186:9)
info Run CLI with --verbose flag for more details.
`

## React Native version:
info Fetching system and libraries information...
(node:82061) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
System:
    OS: Linux 5.8 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i3-6100U CPU @ 2.30GHz
    Memory: 149.45 MB / 7.67 GB
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
    Yarn: Not Found
    npm: 7.19.0 - ~/.nvm/versions/node/v14.17.0/bin/npm
    Watchman: 4.9.0 - /usr/bin/watchman
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: ^0.64.2 => 0.64.2 
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
1. Use this [link](https://github.com/PulasthiAbey/refactored-invention) to clone the repo
2. Pres code and copy & paste the link to the terminal in `git clone <link>`
3. check the `tiny-app` folder for the source code

## Expected Results
It shows the above issue in the terminal and keeps outdating the issue in this repo called 
`FAILURE: Build failed with an exception.

* What went wrong:
Task 'installDebug' not found in project ':app'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
`

## Screenshot & link repository:
[GitHub Repository](https://github.com/PulasthiAbey/refactored-invention)
![errors](https://user-images.githubusercontent.com/50553343/124271904-af085d80-db5b-11eb-8009-5a4948696da5.png)

**Comment by cortinico** [comment]
Closing as you're on a old version of React Native, which we don't offer support for. If you're still having this problem, please open a new issue.
