### ISSUE TITLE
[Android] Problems with Fetching JS bundle

### ISSUE THREAD

**Issue by satya164** [facebook/react-native#3180]
This problem happens randomly. Sometimes, the app keeps getting reloaded even if I didn't change anything (I have auto-reload on change turned on).

And there are lots of reloads at a single time, with lots of "Fetching JS bundle" dialogs stacked on top of each other. There is no way to stop this madness. If I try to close the app by pressing the back button, the app goes away, but the dialog still remains. There is no way to close the never ending dialog, as I cannot even access the recent menu as the dialog is overlayed over everything.

My only bet is to shut down my phone :(

Here is a screenshot,

![screenshot_2015-10-01-15-54-51](https://cloud.githubusercontent.com/assets/1174278/10234132/42acba9c-68b0-11e5-8d2b-11a60908a07c.png)

Android 5.1
Mac OS X Yosemite (10.10.5)
Node 4.1.1
React Native 0.11.4
Watchman 3.8.0

**Comment by mkonicek** [comment]
Thanks for reporting! Is the packager running? Do you have some process (e.g. `git pull`) changing files frequently?

**Comment by satya164** [comment]
Yes, the packager running.

No. There is no other process running which would change the files.

**Comment by mkonicek** [comment]
Do you have a consistent repro?

**Comment by satya164** [comment]
Not really. I'll try to investigate the exact scenario in which this
happens, and report back.

Even then, maybe we should fix the multiple dialogs problem. If one request
is already in progress, and 3 new requests came, they should be reduced to
one and scheduled to be run after the current request.

And the dialog should be within the app. There is no reason it should be on
the screen after closing the app.


Satyajit Sahoo
UX Designer
Behance Profile <https://www.behance.net/satyajitha28c7>

We're all stories, in the end. Just make it a good one, eh? — The Doctor,
Season 5, Episode 13.

**Comment by satya164** [comment]
Okay, so seems that this happens when the debugger gets disconnected for some reason. It happens randomly after the debugger was disconnected.

**Comment by satya164** [comment]
Hmm... Seems it's not the case. I was just working, din't even have debugger, and this happened.

![heyneighbor react packager node terminal today at 1 08 56 am](https://cloud.githubusercontent.com/assets/1174278/10264785/b47df78c-6a34-11e5-9333-f74a37a0612d.png)

**Comment by bobbobb2118** [comment]
It's an impersonation pf me
I didn't put it ip
I can't get them to take it down

**Comment by bobbobb2118** [comment]
It came out in court that joe fall posted it but he wasn't ordered to take
it down
Facebook won't respond

**Comment by foghina** [comment]
FWIW it's not necessary to shut down the phone. Remember, Android is basically Linux, so you can do:

    $ adb shell ps | grep <your-package-name>

This will give you the PID of your process in the second column. Now you can do:

    $ adb kill <PID>

This is far from ideal of course, but a better solution than restarting the phone / emulator.

**Comment by satya164** [comment]
@foghina Doesn't that re

**Comment by foghina** [comment]
@satya164 listing and killing user processes should not require root (it doesn't on most Linux flavors). It also works in Genymotion without using `su`.

Of course, on my Samsung device I can't use `kill`, I get `Operation not permitted`. I'm guessing other manufacturers will do this as well. Pity.

**Comment by satya164** [comment]
@foghina Ah. Okay. I asked coz I though I think saw in someone saying that
it requires root in some stackoverflow thread.

I'll try that next time though. Fortunately I've a Moto and not a Samsung.
Glad I got rid of the Samsung. Thanks :D

Satyajit Sahoo
UX Designer
Behance Profile <https://www.behance.net/satyajitha28c7>

We're all stories, in the end. Just make it a good one, eh? — The Doctor,
Season 5, Episode 13.

**Comment by satya164** [comment]
Haven't encountered this in a while. Will reopen if I do.
