### ISSUE TITLE
Dark mode: useColorScheme() always returns light on Android

### ISSUE THREAD

**Issue by chipmunkcode** [facebook/react-native#31806]
Hey there,

on my Xiaomi Pocophone F1 with Android version 10 and MIUI Version 12.0.3 the dark mode is not working. 
When setting it up in the settings it is kind of dark, not black, but grey instead. When I want to get the current theme, with  
`useColorScheme()` it always returns `light`. I am no expert with Android but why could that issue happen? Does Xiaomi have some built-in dark mode instead of using the dark mode of the apps individually?

UPDATE: It also doesn't work on Galaxy A9. It also always returns "light"

**Comment by yeaFern** [comment]
This is happening to me too on my Pixel 4 XL. I am using Expo, SDK version 42.
In my `app.json` file I have;
```
{
  "expo": {
    ...
    "userInterfaceStyle": "dark",
    ...
  }
}
```
On top of that, my device is set to dark mode too, however `useColorScheme()` is only returning `light`.

**Comment by chipmunkcode** [comment]
I tried it with a new project and it happens for me too again. It always returns `light` on Android.
That is my code:

```js
import React from 'react';
import { useColorScheme } from "react-native";

export default function App() {
  const theme = useColorScheme();
  alert("your color scheme is: " + theme); // always "light" on Android
  return null;
}

```

My app.json:

```json
{
  "expo": {
    "name": "darkmode",
    "slug": "darkmode",
    "version": "1.0.0",
    "orientation": "portrait",
    "userInterfaceStyle": "automatic",
    "icon": "./assets/icon.png",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true
    },
    "android": {
      "adaptiveIcon": {
        "foregroundImage": "./assets/adaptive-icon.png",
        "backgroundColor": "#FFFFFF"
      },
    },
    "web": {
      "favicon": "./assets/favicon.png"
    }
  }
}

```

and my npm packages:

```json
  "dependencies": {
    "expo": "~42.0.0",
    "expo-status-bar": "~1.0.4",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz",
    "react-native-web": "~0.13.12"
  },
```

**Comment by chipmunkcode** [comment]
I figured it out. It was not enough to just put `"userInterfaceStyle": "automatic"` in app.json root, I had to define it for iOS and Android individually too:

**app.json:** 

    {
      "expo": {
        "userInterfaceStyle": "automatic",
        "ios": {
          "userInterfaceStyle": "automatic"
        },
        "android": {
          "userInterfaceStyle": "automatic"
        }
      }
    }

**Comment by vahdet** [comment]
It should be rather about expo. Check the issue here: https://github.com/expo/expo/issues/13488

**Comment by marioposada** [comment]
you can try this!

export default function App() {
  const theme = useColorScheme();
  return (
    <View>
      <Text>useColorScheme(): {theme}</Text>
    </View>
  );
};

**Comment by Dob6458** [comment]
Have you tried disabling a **debug remote** because it prevents making the app theme dark. 
That's what I tried on my side and it worked.

![Screenshot_20220730-030254_Expo Go](https://user-images.githubusercontent.com/35851048/181864294-4642516c-4a9c-429f-8d49-1b5cb6678e46.jpg)

**Comment by Biensothearith** [comment]
[tamdaz](https://github.com/tamdaz) work for me

**Comment by th3f0r3ign3r** [comment]
> I figured it out. It was not enough to just put `"userInterfaceStyle": "automatic"` in app.json root, I had to define it for iOS and Android individually too:
> 
> **app.json:**
> 
> ```
> {
>   "expo": {
>     "userInterfaceStyle": "automatic",
>     "ios": {
>       "userInterfaceStyle": "automatic"
>     },
>     "android": {
>       "userInterfaceStyle": "automatic"
>     }
>   }
> }
> ```

thanks for the answer it help me a lot

@th3f0r31gn3r

**Comment by malko** [comment]
> Have you tried disabling a **debug remote** because it prevents making the app theme dark. That's what I tried on my side and it worked.
> 
> ![Screenshot_20220730-030254_Expo Go](https://user-images.githubusercontent.com/35851048/181864294-4642516c-4a9c-429f-8d49-1b5cb6678e46.jpg)

For those who struggle on how to access this menu, just type "m" in your CLI and it will make the aforementioned menu to appear on your device.

**Comment by LeslieOA** [comment]
> I figured it out. It was not enough to just put `"userInterfaceStyle": "automatic"` in app.json root, I had to define it for iOS and Android individually too:
> 
> **app.json:**
> 
> ```
> {
>   "expo": {
>     "userInterfaceStyle": "automatic",
>     "ios": {
>       "userInterfaceStyle": "automatic"
>     },
>     "android": {
>       "userInterfaceStyle": "automatic"
>     }
>   }
> }
> ```

I'm currently shaking my head at myself after 30mins, thinking I was going bonkers, not realising I'd set this to "light".

🥲

**Comment by Proman4713** [comment]
> > I figured it out. It was not enough to just put `"userInterfaceStyle": "automatic"` in app.json root, I had to define it for iOS and Android individually too:
> > **app.json:**
> > ```
> > {
> >   "expo": {
> >     "userInterfaceStyle": "automatic",
> >     "ios": {
> >       "userInterfaceStyle": "automatic"
> >     },
> >     "android": {
> >       "userInterfaceStyle": "automatic"
> >     }
> >   }
> > }
> > ```
> 
> I'm currently shaking my head at myself after 30mins, thinking I was going bonkers, not realising I'd set this to "light".
> 
> 🥲

@LeslieOA don't worry, this is the default setting for the app.json file, I found mine to be `"light"` as well. what's weird though is that you need to set it up individually for both ios and android, i thought expo would rather automatically set both if i have that one value outside of both platforms
