### ISSUE TITLE
Android elevation value doesn't put effect after upgrading to 0.64.2

### ISSUE THREAD

**Issue by MadCoderme** [facebook/react-native#31808]
## Description
Elevation value doesn't put effect even if it is increased to a large value. I just upgraded from 0.61 to 0.64, no code change, it suddenly stopped working.

Here is the change compared:
![20210704_192825](https://user-images.githubusercontent.com/63955762/124386850-1fe77b00-dcfe-11eb-8798-5196e8fa7b6c.jpg)
![Screenshot_2021-07-04-19-27-08-97](https://user-images.githubusercontent.com/63955762/124386852-2118a800-dcfe-11eb-9546-0684258f85e8.jpg)

## React Native version:
0.64.2 Latest version

## Expected Results
It should stay like before, as you can see in my screenshot

## Snack, code example, screenshot, or link to a repository:
Screenshot attached above

**Comment by AronBe** [comment]
It seems elevation property now gets **overridden by other shadow properties you probably initially aimed for iOS only.** I am utilizing styled-components and after making `box-shadow` iOS specific, elevation started working again as before 👍 

```
 Platform.select({
      ios: css`
        box-shadow: ${({ theme }) => theme.boxShadow[boxShadow]};
      `,
 ```
 
 I guess it is linked to the new [shadow color](https://reactnative.dev/docs/shadow-props#shadowcolor) support on Android?

**Comment by MadCoderme** [comment]
Reading @AronBe  's comment, I found that elevation works if I remove ``shadowColor`` property.
Thanks!

**Comment by thainm80** [comment]
> Reading @AronBe 's comment, I found that elevation works if I remove `shadowColor` property.
> Thanks!

Dear Madcoderme, it using rn 0.64.2 and elevation not work for android. Please help me. Thanks

**Comment by MadCoderme** [comment]
> > Reading @AronBe 's comment, I found that elevation works if I remove `shadowColor` property.
> > Thanks!
> 
> Dear Madcoderme, it using rn 0.64.2 and elevation not work for android. Please help me. Thanks

Did you try what solved for me? Removing `shadowColor`?

**Comment by thainm80** [comment]
I removed but not work. I found but not solution.

**Comment by AronBe** [comment]
@thainm80 maybe you are using any of these properties?
https://reactnative.dev/docs/shadow-props

anyway, you should share your element code/styles if still not finding a help

**Comment by MadCoderme** [comment]
> I removed but not work. I found but not solution.

As @AronBe said, please share your code so we can check for possible solutions

**Comment by thainm80** [comment]
<img width="576" alt="Untitled" src="https://user-images.githubusercontent.com/18556235/132007649-ba58e0b6-4659-47dd-956f-ec1022ef123d.png">

<View style={styles.navBarButton}>
                  <IconButton style={styles.navBarButtonIcon}
                    icon="phone-log-outline" accessibilityLabel="Liên Hệ"
                    color="#54a53f" size={MisoSize(28)} onPress={() => navigation.navigate('Contact')} />
                  <Text style={styles.navBarButtonText}>Liên Hệ</Text>
</View>

const styles = StyleSheet.create({
navBarButton: {
    flex: 1,
    flexDirection: "column",
    alignItems:"center",
    marginLeft: MisoSize(10),
    marginRight: MisoSize(10)
  },
  navBarButtonIcon: {
    borderColor: "#50b848",
    backgroundColor: "#fafafa",
    color: "#50b848",     
    borderWidth: 0, 
    shadowColor: "#999999",
    shadowOffset: {
      width: 0,
      height: 2
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5
  },
  navBarButtonText: {
    alignSelf: "center",
    fontSize:MisoSize(13),
    fontWeight: "normal",
    color: "#686f74",
    alignSelf:"center"  
  },
})

I run on RN 0.61 normally. After upgrading to 0.64.2, the shadow is lost. Please help me.

**Comment by MadCoderme** [comment]
You didn't remove these shadow props from navBarButtonIcon style @thainm80 

```
shadowColor: "#999999",
shadowOffset: {
width: 0,
height: 2
},
shadowOpacity: 0.25,
shadowRadius: 4,
elevation: 5
```
If you only target android, remove them directly.
(RECOMMENDED) If you target IOS too, use platform specific code. Read about it here: https://reactnative.dev/docs/platform-specific-code

**Comment by thainm80** [comment]
I found the cause of the error. 
 **In Android->app->Androidmanifest.xml** I added "**android:hardwareAccelerated="false"** to prevent the app from crashing.If I remove it, Shadow is normal.But if I remove "android:hardwareAccelerated="false" the app crashes.

 <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:windowSoftInputMode="adjustResize"
        android:screenOrientation="portrait"
        android:launchMode="singleTask" 
        android:hardwareAccelerated="false"
        >
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />

   
 Is there a way to replace android:hardwareAccelerated="false" . Please help guide me

**Comment by thainm80** [comment]
"
 <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:windowSoftInputMode="adjustResize"
        android:screenOrientation="portrait"
        android:launchMode="singleTask" 
        android:hardwareAccelerated="false"
        >
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
"

**Comment by thainm80** [comment]
<img width="576" alt="Untitled2" src="https://user-images.githubusercontent.com/18556235/132017543-12a9e366-444a-4222-b3a2-7e0f5b38fde9.png">

**Comment by MadCoderme** [comment]
I am quite confused at this point.
When does it crash?
Did you check adb log?

**Comment by thainm80** [comment]
I use **@react-navigation/bottom-tabs**, when I open the **details page** and -> scroll to the middle of the page -> **back** it crashes

**Comment by MadCoderme** [comment]
> I use **@react-navigation/bottom-tabs**, when I open the **details page** and -> scroll to the middle of the page -> **back** it crashes

This is really weird, can you check adb log?
You need to run `adb logcat` in terminal for this

**Comment by thainm80** [comment]
I run adb with logcat error: 
"Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x1c in tid 1022 (RenderThread), pid 979"

**Comment by MadCoderme** [comment]
Are you using a real device?

**Comment by thainm80** [comment]
I using simulator Nexux X5. It also crash on real devices. In IOS is not Crash

**Comment by MadCoderme** [comment]
Can you try putting back the settings of hardwareaccelerated value and removing shadow props entirely?

I am not an experienced android developer but if it happened to me I would try that too

**Comment by thainm80** [comment]
Can you give me an example here?
"removing shadow props(except elevation) entirely"

**Comment by MadCoderme** [comment]
From
```
shadowColor: "#999999",
shadowOffset: {
width: 0,
height: 2
},
shadowOpacity: 0.25,
shadowRadius: 4,
elevation: 5
```
To
```
elevation:5
```
(for testing)

**Comment by thainm80** [comment]
I have also tried this, but it still doesn't work.

**Comment by MadCoderme** [comment]
No shadow appears?

**Comment by MadCoderme** [comment]
If the shadow doesn't appear (with hardwareaccelerated prop set), i can't find any other solution rn.

You can create another issue or possibly reopen this issue.

Another hacky solution is to use a circular icon component instead of view component. Icons support all text shadow props.

**Comment by thainm80** [comment]
That's right. I tried many ways without showing shadow if hardwareaccelerated prop set

**Comment by thainm80** [comment]
Thanks everyone. I fixed this error (Crash by Webview and navigation) 
  Just add attribute **androidHardwareAccelerationDisabled={true}** to webview
