### ISSUE TITLE
Universal Deeplink params doesnot detect in app but working from browser 

### ISSUE THREAD

**Issue by ahsanparacha02** [facebook/react-native#31817]
**test://test.com/?user=test&password=test**

Here is deeplink url, i want to open other application from my app and bind **username** and **password** field in login form but the problem that i m facing is that when i used deeplink on click event using **Linking.openURL(test://test.com/?user=test&password=test)**, it can opens the app but credentials not bind with login form.

Solution worked with, when i open this url from browser then it worked.

Please help me to fixed this issue

Thanks

**Comment by bobsany16** [comment]
@ahsanparacha02 Have you tried passing the link to `encodeURIcomponent`? Refer [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent)

I had the same issue for a while specifically for Android when using special characters like `&` and I found that `test://test.com/\?user\=test\&password\=test` works.
