### ISSUE TITLE
[XMLHttpRequest] onprogress callback

### ISSUE THREAD

**Issue by jamesfzhang** [facebook/react-native#3181]
`XMLHttpRequest` currently doesn't support the `onprogress` callback for non-uploads. Any other way to estimate the progress of a GET request?

**Comment by mkonicek** [comment]
Good question! I don't think there is one currently.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/xmlhttprequest-onprogress-callback

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.

**Comment by mkonicek** [comment]
@facebook-github-bot answered

**Comment by Lichwa** [comment]
Is there any update on this?
According to [this example](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/XHRExample.android.js#L203) `xhr.upload.onprogress` callback can be defined but the problem is that `xhr.upload` is left undefined.

**Comment by ryanlntn** [comment]
I'm seeing the same thing. Not really sure how to work around it.

**Comment by ahanriat** [comment]
Having the same issue, any update ?

**Comment by ryanlntn** [comment]
@ahanriat There were a lot of updates to xhr in the 0.26 release. I'm in the process of updating right now and hoping that will fix it.

**Comment by ahanriat** [comment]
Thanks for the heads up @ryanlntn !! I'll try it :)

**Comment by GeoffreyPlitt** [comment]
I'm on RN=0.42 and using XHR with a Content-Length set before uploading begins. I'm seeing the progress events, but no bytesSent or length or anything else that I can use to compute a progress%. Anybody else have luck with this?

**Comment by butchmarshall** [comment]
I'm also seeing total, but no loaded progress on both RN=0.42 and RN=0.46.4

**Comment by butchmarshall** [comment]
I have a workaround for it at least.

Created a pull request [here](https://github.com/facebook/react-native/pull/16371)

In `Libraries/Network/XMLHttpRequest.js`

Change:

```

  __didReceiveIncrementalData(
    requestId: number,
    responseText: string,
    progress: number,
    total: number
  ) {
    if (requestId !== this._requestId) {
      return;
    }
    if (!this._response) {
      this._response = responseText;
    } else {
      this._response += responseText;
    }

    XMLHttpRequest._interceptor && XMLHttpRequest._interceptor.dataReceived(
      requestId,
      responseText);

    this.setReadyState(this.LOADING);
    this.__didReceiveDataProgress(requestId, progress, total);
  }
```

To
```

  __didReceiveIncrementalData(
    requestId: number,
    responseText: string,
    progress: number,
    total: number
  ) {
    if (requestId !== this._requestId) {
      return;
    }
    if (!this._response) {
      this._response = responseText;
    } else {
      this._response += responseText;
    }
    progress = this._response.length;

    XMLHttpRequest._interceptor && XMLHttpRequest._interceptor.dataReceived(
      requestId,
      responseText);

    this.setReadyState(this.LOADING);
    this.__didReceiveDataProgress(requestId, progress, total);
  }
```
