### ISSUE TITLE
0.64.2 TypeError: Cannot use 'in' operator

### ISSUE THREAD

**Issue by Maty0712** [facebook/react-native#31815]

**Comment by jenskuhrjorgensen** [comment]
I had to change `blacklist` to `blockList` in `metro.config.js` when updating from RN 0.63 to 0.64. 

See the documentation:

https://reactnative.dev/docs/0.63/ram-bundles-inline-requires#updating-the-metroconfigjs
vs
https://reactnative.dev/docs/0.64/ram-bundles-inline-requires#updating-the-metroconfigjs

**Comment by Sourishh** [comment]
Any other solutions? the version for RN is 0.63 only
