### ISSUE TITLE
Inaccurate colors displaying on Android.

### ISSUE THREAD

**Issue by herbievine** [facebook/react-native#31814]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
I have a simple text component which doesn't display certain colors. Black rendered as white, blue as light purple. Green and red work fine though.

 `<Text style={{ color: '#111111' }}>Black text not working</Text>`

## React Native version:
```
System:
    OS: OS X Yosemite 10.10.5
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 282.84 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.17.0 - /var/folders/wj/j9ys71617dl6z_d88qqbgq1h0000gn/T/yarn--1625471333251-0.33904908366693487/node
    Yarn: 1.22.10 - /var/folders/wj/j9ys71617dl6z_d88qqbgq1h0000gn/T/yarn--1625471333251-0.33904908366693487/yarn
    npm: 6.14.13 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK: Not Found
    Android SDK:
      API Levels: 29, 30
      Build Tools: 29.0.2
      System Images: android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7351085
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.1 => 0.64.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
✨  Done in 3.40s.
```

## Steps To Reproduce
`git clone -b color-issue https://github.com/herbievine/semeru`
`yarn`
`yarn android`

## Expected Results
The Text component's style (located at `./src/pages/chats.tsx`) should be updated with the theme

## Snack, code example, screenshot, or link to a repository:
https://github.com/herbievine/semeru
https://stackoverflow.com/questions/68247588/react-native-stylesheet-not-updating-on-value-change
![ezgif-4-f912f20ddb52](https://user-images.githubusercontent.com/41120535/124437669-94123500-dd77-11eb-8be1-9069e17e87d1.gif)

**Comment by jacquesdev** [comment]
Could this be related to dark/light mode on Android?
