### ISSUE TITLE
My bug is simple. PanResponder does not listen to state changes in useState Hook. 

### ISSUE THREAD

**Issue by Irongade** [facebook/react-native#31812]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
This is mostly an observed bug. it can be reproduced very easily and very locally
The bug is simple, PanResponder does not listen to state changes in useState Hook. If you passed a state into any of the panResponder functions for example (onPanResponderMove). it only keeps a record of the initial state and uses that state through out the lifecycle. Any update to that state variable will not be picked up by panResponder.create() method config object functions.

## React Native version:
"react": "17.0.1",
"react-native": "0.64.1",

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Copy code below, 
2. Run react native android/ios. then swipe to the left or right.

## Expected Results
I expected that for each swipe, the currentScreen state prop should increment or decrement to a max number of 4 and a min number of 1

## Snack, code example, screenshot, or link to a repository:

import React, {useState, useRef, useEffect} from 'react';
import {
     StyleSheet,
     View,
     ImageBackground,
     TouchableOpacity, Animated,
     Platform,
     PanResponder
 } from 'react-native';
  
  //components
import AppText from "../components/AppText"
import Container from "../components/Container";
import ButtonItem from "../components/ButtonItem";
 
 const OnboardingScreen = ({navigation}) => {

     const [currentScreen, setCurrentScreen] = useState(1)

     const goToLogin = () => {
        navigation.navigate("Login")
    }

    const incrementScreen = () => {
        let nextScreen;
        if(currentScreen > 3){
            nextScreen =  4
        } else{
            nextScreen =  currentScreen + 1
        }

        setCurrentScreen(nextScreen);
    }

    const decrementScreen = () => {
        let prevScreen;
        if(currentScreen > 1){
            prevScreen = currentScreen - 1
        } else{
            prevScreen =  1
        }

        setCurrentScreen(prevScreen);
    }

    const pan = useRef(new Animated.ValueXY()).current;

    const panResponder = useRef(
      PanResponder.create({
        onMoveShouldSetPanResponder: () => true,
        onPanResponderGrant: (e, gesture) => {
            return false;
        },
        onPanResponderMove: () => {
            return false
        },
        onPanResponderRelease: (e, gesture) => {
            if (String(gesture.dx).includes('-') && parseInt(gesture.dx) < -80.0 ) {
                incrementScreen();
            }
            if (!String(gesture.dx).includes('-') && parseInt(gesture.dx) > 80.0 ) {
                decrementScreen()
            }
        }
      })
    ).current;

**Comment by francislow** [comment]
I am facing the same issue, cant seem to find any workarounds
