### ISSUE TITLE
Native modules cannot be null. React-native iOS

### ISSUE THREAD

**Issue by SuhailBt** [facebook/react-native#31825]
Adding screenshot of error.

I am not using push notifications in my project.

<img width="381" alt="Screenshot 2021-07-07 at 7 17 44 PM" src="https://user-images.githubusercontent.com/65166275/124772669-dd21df00-df59-11eb-9912-3251c5cedfd0.png">

**Comment by SuhailBt** [comment]
I was using expo but ejected long back. It is working fine for android but not for iOS

**Comment by cortinico** [comment]
Closing as invalid (you provided no information to help us support you in any form)
