### ISSUE TITLE
Opacity in nested components doesn't work as expected

### ISSUE THREAD

**Issue by JakeRawr** [facebook/react-native#3183]
I'm trying to set a 0.1 opacity of a black background with a 1 opacity text

```
<View style={{backgroundColor: 'black', opacity: 0.1, ... }}>
  <Text style={{color: white, opacity: 1, ... }}>{$25}</Text>
</View>
```
and i got the following:

![screen shot 2015-10-01 at 3 12 17 pm](https://cloud.githubusercontent.com/assets/7199499/10235163/dbd8d582-684e-11e5-9195-16ddf06fad88.png)

Is this expected?

**Comment by ide** [comment]
Yes, this is expected. Opacity is multiplied through the view hierarchy. My suggestion for you now is to use an rgba background color, like this: `rgba(0, 0, 0, 0.1)`.

**Comment by JakeRawr** [comment]
Thanks
