### ISSUE TITLE
Configure project :react-native-webview Adding a Configuration as a dependency is a confusing behavior which isn't recommended. This behaviour has been deprecated and is scheduled to be removed in Gradle 8.0. 

### ISSUE THREAD

**Issue by sumeetghimire** [facebook/react-native#31831]
Fail to generate bundleRelease apk or assembleRelease at First, I got deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0. Use '--warning-mode all' to show the individual deprecation warnings. 

and when I did gradlew --warning-mode all I got the following details about the error anyone helps me out I am newbie

**Comment by sumeetghimire** [comment]
Fail to generate bundleRelease apk or assembleRelease when I did gradlew --warning-mode all I got the following details about the error anyone help me out I am newbiew

**Comment by cortinico** [comment]
Closing as you're on a old version of React Native, which we don't offer support for. If you're still having this problem, please open a new issue.
