### ISSUE TITLE
WebSockets are not working in AppClips

### ISSUE THREAD

**Issue by ex3ndr** [facebook/react-native#31848]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Running React Native app as Apple App Clip causes websocket to not work in app code and in dev server

## React Native version:
0.64

## Steps To Reproduce
Add App Clip target and try to run on device (not simulator)

## Expected Results
WebSockets to work

**Comment by kuznetsov-from-wonderland** [comment]
Can you please share the manual you've used to run App Clip with RN?

**Comment by ex3ndr** [comment]
I have not: just create new target for AppClip and replace native files (*.m/h and images) by the one from main app. Works flawlessly! Just the issue with WebSocket since it is allowed only to use NSUrlSession API.
