### ISSUE TITLE
Crashed: com.google.firebase.crashlytics.ios.exception SIGABRT ABORT 0x00000001d715d334

### ISSUE THREAD

**Issue by harleenarora** [facebook/react-native#31844]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
I have got a Crashed: com.google.firebase.crashlytics.ios.exception 
SIGABRT ABORT 0x00000001d715d334

## Expected Results
![screenshot-2021 07 10-16_21_52](https://user-images.githubusercontent.com/18188411/125160595-71c74f80-e19b-11eb-95e3-3830a78b9069.png)

**Comment by safaiyeh** [comment]
Closing as this is just a crash log dump. Please follow the issue template and fill out each section so collaborators can help you get to a solution.
