### ISSUE TITLE
DevMenu differences iOS/Android

### ISSUE THREAD

**Issue by henrymoulton** [facebook/react-native#31849]
## Bug Description

When using Hermes, iOS has a different DevMenu to Android:

## iOS:

<img width="261" alt="image" src="https://user-images.githubusercontent.com/30093692/123788201-a6055b00-d8d3-11eb-818c-2595d94502e4.png">

## Android:

<img width="350" alt="image" src="https://user-images.githubusercontent.com/30093692/123787267-83267700-d8d2-11eb-8fab-5c7c6cbf9a24.png">

This is important, when clicking `Debug` the Android app will crash if using Reanimated 2 "As the library uses JSI for synchronous native methods access, remote debugging is no longer possible. You can use Flipper for debugging your JS code, however connecting debugger to JS context which runs on the UI thread is not currently supported."

Hermes version: `- hermes-engine (0.7.2)` (Android I assume same version)
React Native version (if any): `"react-native": "0.64.1",`
OS version (if any): Android 10, iOS 14.4, OSX Catalina

## Steps To Reproduce

1. Open debugger menu using iOS and Hermes
2. Open debugger menu using Android and Hermes 
3. See the difference

## The Expected Behavior

The same debug menu should be shown on Android. Open Debugger should open Flipper.

**Comment by Jorgezz** [comment]
not same red box display condition, in Android OS, the getDevSupportEnable in develop mode is open, then the error will show red box, but in iOS, not in release mode, the red box will show.

**Comment by cortinico** [comment]
cc @huntie Closing as this is not relevant anymore (the clicking on "Debug" + Reanimated), but we do have the menu divergence under our radar
