### ISSUE TITLE
Passing zero from a native module doesn't work

### ISSUE THREAD

**Issue by edward-a** [facebook/react-native#31855]
nativeEvent receives EMPTY_NATIVE_EVENT value in case nativeEventParam is zero. See the code excerpt below

function _receiveRootNodeIDEvent(rootNodeID, topLevelType, nativeEventParam) **{
  var nativeEvent = nativeEventParam || EMPTY_NATIVE_EVENT;**

EDIT:
https://snack.expo.io/tm8iWEvIQ

**Comment by rectified95** [comment]
Please provide a more detailed repro, preferably using an Expo snack.

**Comment by edward-a** [comment]
> 
> 
> Please provide a more detailed repro, preferably using an Expo snack.

Added a snack link.
