### ISSUE TITLE
Android app/build.gradle error

### ISSUE THREAD

**Issue by lincdh** [facebook/react-native#31852]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
The issue is related to react-native@0..64.2 with the error message of **_cannot resolve symbol 'build'_** in _app/build.gradle_, which happens when I upgrade to 0.64.2. My previous version is 0.64.0 does not have that.
## React Native version:
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-5700HQ CPU @ 2.70GHz
    Memory: 5.03 GB / 15.92 GB
  Binaries:
    Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      Versions: 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: 4.1.3
    Visual Studio: 16.10.31410.357 (Visual Studio Community 2019)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: ^0.64.2 => 0.64.2
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Upgrade to react-native@0.64.2
2. Re-sync app/build.gradle

## Expected Results
Describe what you expected to happen.
Upgrade to react-native@0.64.2 should show no error

## Snack, code example, screenshot, or link to a repository:
![image](https://user-images.githubusercontent.com/21136244/125325970-bdc8ee80-e36b-11eb-8dab-5d930644e7d4.png)

**Comment by saremeskandary** [comment]
notice: with using **Avatar.Image** from [react native paper](https://callstack.github.io/react-native-paper/avatar-image.html) it work!

**Comment by youcef-zaidi** [comment]
i think that's because you don't have an Android SDK installed
