### ISSUE TITLE
ScrollView ref.scrollTo is not working in Android real device

### ISSUE THREAD

**Issue by dika4152** [facebook/react-native#31851]
## Description
When i am using ScrollView ref for trigger the UI to scroll to certain content, it works well on iOS real device. but unfortunately it is not working on Android real device, iOS Simulator, and Android Simulator. I've already try in Android 10 and Android 11.

## React Native version:
System:
    OS: macOS 11.2.3
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 24.74 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.15.0 - ~/.nvm/versions/node/v12.15.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v12.15.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7351085
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 13.0.2 - /Users/qubisagml/.sdkman/candidates/java/current/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.1 => 0.64.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
1. I make a state for certain content's y number.
2. I get the certain content position with onLayout and set the y number into a state.
3. I get the ScrollView ref with useRef
4. When the state is updated, i call the ScrollView scrollTo method and passing the state into it.

## Expected Results
The screen automatically scroll down to the wanted certain content's position.

## Snack, code example, screenshot, or link to a repository:
```
import React, { useState, useEffect } from 'react';
import { ScrollView } from 'react-native';

export default function App() {
  const [yIndex, setYIndex] = useState(0);
  const scrollViewRef = useRef();

  useEffect(() => {
    if (scrollViewRef.current) {
      scrollViewRef.current.scrollTo({ y: yIndex });
    }
  }, [yIndex, scrollViewRef]);

  return (
    <ScrollView
      ref={scrollViewRef}>
      <View />
      <View />
      <View />
      <View
        onLayout={(event) => {
          setYIndex(event.nativeEvent.layout.y);
        }}
      />
      <View />
    </ScrollView>
  )
};
```

**Comment by rectified95** [comment]
I created the following Snack to reproduce it:
https://snack.expo.io/wai1EMhQE
Looks like it does work on both the Android and iOS simulators.
Can you try the above Snack on your device and see if it fails as you described above?

**Comment by luis-tc** [comment]
This bug persists, https://snack.expo.dev/nPYnQCzUl0
