### ISSUE TITLE
How can I add inner shadow to the component

### ISSUE THREAD

**Issue by Maty0712** [facebook/react-native#31868]
I'm using react-native-shadow to add shadows to the components. All the outer shadows are added. I want to know how can I add inner shadows to the components?

**Comment by SusulAdam** [comment]
Shouldn't this question be asked here: https://github.com/879479119/react-native-shadow/issues ? In "pure" react native without any libraries there is no way to add inner shadows to the components.  The only props about shade in "pure" react native can be found here: https://reactnative.dev/docs/view-style-props#elevation-android, https://reactnative.dev/docs/shadow-props
