### ISSUE TITLE
Android android_hyphenationFrequency in text does not work in react-native 0.64.2

### ISSUE THREAD

**Issue by evd1ser** [facebook/react-native#31878]
## Description
I'm trying to add soft hyphenation to app using [android_hyphenationFrequency](https://reactnative.dev/docs/text#android_hyphenationfrequency-android) but it doesn't work.

try on new clean app
## React Native version:
```
{
  "name": "TestTestWrapp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "react": "17.0.1",
    "react-native": "0.64.2"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "7.14.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.64.0",
    "react-test-renderer": "17.0.1"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

## Steps To Reproduce
1. create new app
2. add some text like `WillHaveAnHyphenWhenBreakingForNewLine`
2.1 for example I use three text with different symbol
2.2 `WillHave\u00ADAnHyphen\u00ADWhen\u00ADBreaking\u00ADForNew\u00ADLine` - in this [issue](https://github.com/facebook/react-native/issues/28279) written that it doesn't work for android
2.3 `WillHave\u200BAnHyphen\u200BWhen\u200BBreaking\u200BForNew\u200BLine` - wrap for android
3. add maxWidth to container - example 300
4. add text props android_hyphenationFrequency with any value
5. run on android device example: emulator Pixel 4 API 30

## Expected Results
To see the result like in this request - https://github.com/facebook/react-native/pull/29157

but I don't see anything like it

## Snack, code example, screenshot, or link to a repository:
code example:
<img width="100%" alt="Снимок экрана 2021-07-19 в 13 20 26" src="https://user-images.githubusercontent.com/15332093/126145583-662ea201-5fa3-4e98-bca0-2c009f9cd621.png">
result example:
<img width="320" alt="Screenshot_1626690040" src="https://user-images.githubusercontent.com/15332093/126145632-596a8d11-ded4-4659-8354-f119f906f4a5.png">

text wrap with `\u200B` but no hyphenation symbol

repository with example - https://github.com/evd1ser/test-rn-andoid-text-hyphenation

**Comment by yanel777** [comment]
+ 1

**Comment by lpatrun** [comment]
It doesn't work on 0.64.1 as well.
I tried on emulator and real device, both being android 8.0 and higher.
I just added android_hyphenationFrequency prop to Text component and tried with 'full', 'balanced', 'high' but it made no difference.

**Comment by LukaZagar1995** [comment]
+1

**Comment by fabriziobertoglio1987** [comment]
seems to me that you are using `textBreakStrategy`.
Can you reproduce this error without that prop? 

the result should be something like 



| **AFTER** | 
|:-------------------------:|
|  <img src="https://user-images.githubusercontent.com/24992535/84919245-f8f1e300-b0c1-11ea-8a33-f30d0c9a75b7.png"  width="300" height="" />| 


https://github.com/facebook/react-native/pull/29157#issue-435944114

**Comment by yanel777** [comment]
> seems to me that you are using `textBreakStrategy`.
> Can you reproduce this problem without that prop?
> 
> the result should be something like
> 
> https://github.com/facebook/react-native/pull/29157/files?file-filters%5B%5D=.js#diff-1654e2fe87ee923670e15697f1556521bb5565e04d6bc2d306c5204f6b5ef4beR211-R232
> 
> **AFTER**
> <img alt="" width="300" height="" src="https://user-images.githubusercontent.com/24992535/84919245-f8f1e300-b0c1-11ea-8a33-f30d0c9a75b7.png">
> [#29157 (comment)](https://github.com/facebook/react-native/pull/29157#issue-435944114)

textBreakStrategy = any value or undefined -  reproduce this problem

**Comment by evd1ser** [comment]
> seems to me that you are using `textBreakStrategy`.
> Can you reproduce this problem without that prop?

@fabriziobertoglio1987
I'm try without textBreakStrategy too result:

<img width="1073" alt="Снимок экрана 2021-08-03 в 16 31 02" src="https://user-images.githubusercontent.com/15332093/128024020-c09c9f00-6b2b-4f4b-8cb3-1a8ca9f154d4.png">
<img width="542" alt="Снимок экрана 2021-08-03 в 16 24 56" src="https://user-images.githubusercontent.com/15332093/128024061-a9f03cc7-b68b-4ab0-b30f-3b6314b9c5a6.png">
example repo: https://github.com/evd1ser/test-rn-andoid-text-hyphenation

**Comment by TheRealMikeD** [comment]
I hope this doesn't make things worse, but I was trying to use a value of "balanced" and I got an error:
`Invalid android_hyphenationFrequency: balanced`
According to the RN docs for RN 0.67 and later, "balanced" is no longer a valid value: [https://reactnative.dev/docs/0.67/text#android_hyphenationfrequency-android](https://reactnative.dev/docs/0.67/text#android_hyphenationfrequency-android)

That said, I concur with the original poster that none of the values seem to do anything, as far as I can see.
Using RN 0.69.6

**Comment by fabriziobertoglio1987** [comment]
https://github.com/fabriziobertoglio1987/react-native/commit/a0d30b848a07480d0fccec608a62a505c71f8cac

**Comment by Shai69bb** [comment]
Help
