### ISSUE TITLE
Paste not working in IOS simulator with react native apps

### ISSUE THREAD

**Issue by vishnuc** [facebook/react-native#31874]
Hi , I am using ios simulator 12.5.1

If I paste with other apps in simulator , like reminder app , I can select all text -> copy -> paste and it works fine.

But in react native apps I am able to copy , but when i click paste its always empty.

I am using TextInput

```
 <TextInput
                placeholderTextColor={"#818284"}
                placeholder="Your Username"
              />
```

**Comment by safaiyeh** [comment]
@vishnuc thanks for the issue! Looks like an annoying bug, could you follow the issue template and provide all the information we need for investigation.

**Comment by FernandoJMedina** [comment]
This happens with my M1, not in intel ones.

also related: https://github.com/flutter/flutter/issues/74970

**Comment by vishnuc** [comment]
hope It will be solved in next xcode.

**Comment by arunim2405** [comment]
I am still facing this issue in xcode 13 and ios 15

**Comment by doublethefish** [comment]
I believe this refers to #18926 which seems to imply that `removeClippedSubviews` in the BottomTabNavigator is to blame; there are also links to hacky workarounds to resize the TextInput with timers.

You can see the issue (I hope) on [this snack](https://snack.expo.dev/-ub7Yl48k). Note that this only seems to affect runs on the iOS simulator.

The snack, linked above, simply has :

1. An extra `<TextInput .. >` from "react-native-gesture-handler"
2. with `multilne` set
3. within a `BottomTabNavigator`

So if the snack-link above fails you can repro it with any BottomTabNavigator demo e.g. [this one](https://snack.expo.dev/@aboutreact/bottom-navigation-example), and just add a TextInput.

It works on device (possibly just in release builds), just not in the simulator...

**Comment by arunim2405** [comment]
I am pretty sure it is because I was running the simulator (and xcode ) and my react native node server via rosetta 2. Once I upgraded to rn 0.66.3 and shifted everything to native, the copy-paste and the document picker/gallery picker started to work automatically.

**Comment by ddikodroid** [comment]
> Hi , I am using ios simulator 12.5.1
> 
> If I paste with other apps in simulator , like reminder app , I can select all text -> copy -> paste and it works fine.
> 
> But in react native apps I am able to copy , but when i click paste its always empty.
> 
> I am using TextInput
> 
> ```
>  <TextInput
>                 placeholderTextColor={"#818284"}
>                 placeholder="Your Username"
>               />
> ```

if you are on xcode 14
you can add 
```
<key>com.apple.security.app-sandbox</key>
<true/>
```
to info.plist
