### ISSUE TITLE
Infinite layout loop from when views of a certain size's layouts are used to position parent

### ISSUE THREAD

**Issue by iway1** [facebook/react-native#31876]
## Description
If you create a component with a view that centers its children using absolute positioning based on the layout of a child view containing the children, and then you set a child view to specific sizes it will cause an infinite layout loop. Clearly, layout behavior shouldn't change based on the dimensions of the View.

## React Native version:
Tested 0.63 and 0.64.

## Steps To Reproduce
Do this

```js
import React from 'react';
import { View } from 'react-native';
import { useState } from 'react';


var i =0;

export function CenteredView({origin, children }) {
  const [layout, setLayout] = useState({ width: 0, height: 0 });
  return (
    <View
      style={{
        width: 0, height: 0,
        left: origin.x, top: origin.y,
        position: 'absolute',
      }}
    >
      <View
        onLayout={(e) => {
          setLayout(e.nativeEvent.layout);
          console.log(i++)
        }}
        style={{
          position: 'absolute',
          left: -layout.width/2,
          top: -layout.height/2,
        }}
      >
        {children}
      </View>
    </View>
  )
}

export default function App() {
  return (
    <CenteredView
      origin={{
        x: 50, y: 50
      }}
    >
      <View
        style={{
          width: 571.3133640552995, // If you change this to another number, the infinite loop will not occur
          height: 100,
        }}
      />
    </CenteredView>
  );
}
```

## Expected Results
`onLayout` should only run once. With the specified width, it will run infinitely. Note that if you change the width to some other number, such as `width: 100`, onLayout will only be called a single time.

## Snack, code example, screenshot, or link to a repository:
https://snack.expo.io/@iway1/tactless-cake

**Comment by Bardiamist** [comment]
Faced with it

**Comment by Bardiamist** [comment]
Still an issue

**Comment by jyaconelli** [comment]
This is still an issue in react native 0.73.4
