### ISSUE TITLE
ActionSheetIOS showShareActionSheetWithOptions() throws error and crashes app on close save to files

### ISSUE THREAD

**Issue by Srh07** [facebook/react-native#31879]
## Description
When using the share functionality for iOS the app crashes because of an uncaught error: 
_"No callback found with cbID 16565 and callID 8282 for  ActionSheetManager.showShareActionSheetWithOptions - most likely the callback was already invoked. Args: '[false,null]'"

I found similar issues in react-native-share but these are closed or solved: https://github.com/react-native-share/react-native-share/pull/584

Note: the fix they provided seems to work. 

This issue also occurs in the share() method as it seems to depend on ActionSheetIOS functionality. 

## React Native version:
0.63.3 and later

## Steps To Reproduce
1. implement a share function with ActionSheetIOS.showShareActionSheetWithOptions()
2. pass an url through options and pass a function for both failureCallback and successCallback
3. pass a base64 pdf string as url
3. implement a button to call the share function
4. run on iPad or iPhone simulator (not in snack)
5. click the button so the share sheet opens
6. click Save to Files
7. click Cancel (do not save)
8. If you catch the error in the failureCallback function the Save to Files modal will close, else the app will crash
9. If not yet crashed, close the share sheet (modal)
10. The app will crash now with the error described above.

## Expected Results
All modals should close correctly without crashing the app.

## Snack, code example, screenshot, or link to a repository:
The code I used (in expo Go it doesn't crash): 
https://snack.expo.io/@sarah.b/shareios

**Comment by safaiyeh** [comment]
@Srh07 thank you for the report! For some reason your links are not working. Could you fix those and I can check out the issues?

**Comment by Srh07** [comment]
Thank you for replying! I fixed the links, so they should work. Could you please check if it's okay now?

**Comment by mattpilleul** [comment]
Hello ! No news ?

**Comment by hernan-clicoh** [comment]
Is there a solution in works?
