### ISSUE TITLE
No broadcastPermission for the Broadcast receiver in class DevSupportManagerBase

### ISSUE THREAD

**Issue by erich04** [facebook/react-native#31870]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
No permission for broadcast receiver

## React Native version:
Run `react-native info` in your terminal and copy the results here.

![image](https://user-images.githubusercontent.com/12180239/125921197-adcdf88f-1117-4350-b403-189cf0031e57.png)

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

```java
  private void reload() {
    UiThreadUtil.assertOnUiThread();

    // reload settings, show/hide debug overlay if required & start/stop shake detector
    if (mIsDevSupportEnabled) {
      // update visibility of FPS debug overlay depending on the settings
      if (mDebugOverlayController != null) {
        mDebugOverlayController.setFpsDebugViewVisible(mDevSettings.isFpsDebugEnabled());
      }

      // start shake gesture detector
      if (!mIsShakeDetectorStarted) {
        mShakeDetector.start(
            (SensorManager) mApplicationContext.getSystemService(Context.SENSOR_SERVICE));
        mIsShakeDetectorStarted = true;
      }

      // register reload app broadcast receiver
      if (!mIsReceiverRegistered) {
        IntentFilter filter = new IntentFilter();
        filter.addAction(getReloadAppAction(mApplicationContext));
        mApplicationContext.registerReceiver(mReloadAppBroadcastReceiver, filter);   // No broadcastPermission
        mIsReceiverRegistered = true;
      }
 ... 
}
```

## Expected Results
Describe what you expected to happen.

Need to  vertify the permission for the intentfilter before handling data in the method onReceive

## Snack, code example, screenshot, or link to a repository:

**Comment by samarderbali1234** [comment]
Barri zamri

**Comment by cortinico** [comment]
Closing as we implemented the mandatory permissions flag for Broadcast Receiver in RN 0.73 which will be out in the next days.
