### ISSUE TITLE
Keyboard Avoiding Multiple TextInput

### ISSUE THREAD

**Issue by AmirDoreh** [facebook/react-native#31881]
i am using KeyboardAvoidingView with multiple text input inside it, in android i solve this issue by adding `android:windowSoftInputMode="adjustResize"` to my AndroidManifest , any idea/solution for this isse on ios ? 

https://user-images.githubusercontent.com/45465967/126307653-9ddfed83-5377-4b91-9e0b-50060d2c4a74.mov

**Comment by safaiyeh** [comment]
Can you check out this thread to see if it solves ur problems? https://github.com/facebook/react-native/issues/8855
