### ISSUE TITLE
"npm install" on example results in "npm ERR! Error: failed to fetch from registry: absolute-path/0.0.0"

### ISSUE THREAD

**Issue by jonchui** [facebook/react-native#3188]
If you follow the readme.md for the example:

- `git clone https://github.com/facebook/react-native.git`
- `cd react-native && npm install`

I get:

npm http GET https://registry.npmjs.org/yeoman-generator/0.20.3
npm ERR! Error: failed to fetch from registry: absolute-path/0.0.0
npm ERR!     at /usr/local/lib/node_modules/npm/lib/utils/npm-registry-client/get.js:139:12
npm ERR!     at cb (/usr/local/lib/node_modules/npm/lib/utils/npm-registry-client/request.js:32:9)
npm ERR!     at Request._callback (/usr/local/lib/node_modules/npm/lib/utils/npm-registry-client/request.js:137:18)
npm ERR!     at Request.callback (/usr/local/lib/node_modules/npm/node_modules/request/main.js:118:22)
npm ERR!     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/main.js:194:58)
npm ERR!     at Request.emit (events.js:88:20)
npm ERR!     at ClientRequest.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/main.js:337:12)
npm ERR!     at ClientRequest.emit (events.js:67:17)
npm ERR!     at HTTPParser.onIncoming (http.js:1226:11)
npm ERR!     at HTTPParser.onHeadersComplete (http.js:102:31)
npm ERR! You may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
npm ERR! 
npm ERR! System Darwin 14.0.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /CODE/react-native/React
npm ERR! node -v v0.6.1
npm ERR! npm -v 1.1.2
npm ERR! message failed to fetch from registry: absolute-path/0.0.0
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /CODE/react-native/React/npm-debug.log
npm not ok

**Comment by ide** [comment]
You're using a super old version of Node. Make sure you're on 4.0+.
