### ISSUE TITLE
React-native (Signed) release apk keeps stopping (android version)

### ISSUE THREAD

**Issue by somchithCom2** [facebook/react-native#31897]
React-native (Signed) release apk keeps stopping (android version)

The application working fine with debug mod both emulator and physical devices. For release version, building apk process is success and the installation in physical device as well. But when try to open application, it keeps stopping 

I have try to build application by Android Studio but got error: Caused by: com.facebook.jni.CppException: Invalid unicode escape in identifier: '\u0eaa\u0eb3\u0ea1\u0eb0\u0ec2\u0e99\u0e84\u0ebb'

Tried so many solution from git still not working.
Thanks a lot for help.

Error from emulator when build by Android studio and from physical device with release build:
![WhatsApp Image 2021-07-24 at 14 55 16](https://user-images.githubusercontent.com/42641807/126863994-aaa31008-4bb9-44d8-91d5-08b1a62c3652.jpeg)

Error from Android Studio Logcat:
![WhatsApp Image 2021-07-24 at 15 01 06](https://user-images.githubusercontent.com/42641807/126864068-a2236b35-b751-4f92-a13c-94387599a883.jpeg)

**Comment by boaracer** [comment]
Did you solve the problem? Thank you.
