### ISSUE TITLE
Useless Errors

### ISSUE THREAD

**Issue by timothyerwin** [facebook/react-native#31894]
React Native is an amazing development platform don't get me wrong...but the LogBox and debugging is almost completely useless and amounts to putting console statements everywhere. i.e. `console.log('hey, here...1');`

Seriously it's one of the worst debugging experiences ever. The call stack is worthless and the errors are so vague and don't show where it happened, etc.

**Comment by chrisbobbe** [comment]
Can you provide more details and suggestions for improvement?

Do you use remote JS debugging? https://reactnative.dev/docs/debugging

**Comment by timothyerwin** [comment]
Here is a simple example that shows in a nutshell all that is wrong with the errors in general. It's like it was designed by an internal React Native developer to figure out internal issues but is practically useless for end developers who need to see their own code. Same with the call stack. It's like 50 internal React Native functions instead of showing my code it always shows 1000 lines of React Native code.

<img width="561" alt="Screen Shot 2021-07-29 at 11 28 44 AM" src="https://user-images.githubusercontent.com/2653209/127546349-847bc9dd-80c7-4024-a8ad-4943ad23c87a.png">

**Comment by chybisov** [comment]
I feel your pain. Today I'm trying to debug where this error comes from and no luck. I have around 100 places where it might be and it's very frustrating to check them all. 
![image](https://user-images.githubusercontent.com/18644653/127665397-3683af1b-ed90-4b56-85db-8c9a3e804229.png)

**Comment by timothyerwin** [comment]
Exactly....tell me you guys haven't seen this callstack...I mean, I can't step through my code without the debugger jumping 30 levels into some framework code somewhere.

<img width="568" alt="Screen Shot 2021-07-30 at 6 57 47 PM" src="https://user-images.githubusercontent.com/2653209/127725347-1ee5fa10-f056-4fda-a7c3-6973927391b4.png">

**Comment by safaiyeh** [comment]
Thanks for the issue, and I agree I have not had a good experience with the errors. This issue would be better to open at the metro repo https://github.com/facebook/metro.
