### ISSUE TITLE
[iOS] TextInput not behaves properly with keyboard when multiline is enabled.

### ISSUE THREAD

**Issue by Gokul9995** [facebook/react-native#31911]
## Description
Need to disable suggestions for the multiline input text box. But for some specific iOS device it is not working. Still able to see the password as suggestions even if handled for disable suggestions.

## React Native version:
"react": "16.13.1",
 "react-native": "0.63.3"

## Steps To Reproduce
1. Try to enter any text in **TextInput** with **multiline** as _true_

Try this step in the below mentioned devices to reproduce the issue.

-  iPhone 8 version 14.6

- iOS 6S

## Expected Results
Suggestions should not show.

![Withoutmultiline](https://user-images.githubusercontent.com/74865437/127162789-ba514285-ca1d-4e3d-b020-41528897e20b.png)

## Actual Results
Showing suggestion as password

![WithMultilineEnabled](https://user-images.githubusercontent.com/74865437/127162778-dd34071f-169a-44b4-b705-f9389d0a4e5f.png)

## Snack, code example, screenshot, or link to a repository:

```
<TextInput
 value={defMessage}
 onChangeText={(value) => {
 setMessage(value);
 }}
 placeholder="Enter a message"
 maxLength={8000}
 autoCorrect={false}
 multiline={true}
 numberOfLines={2}
 style={CustomStyles.text_input_with_multiLine}
 autoCompleteType="off"
 textContentType='oneTimeCode'
 />
```

**Comment by GhalyahFA** [comment]
Hi @Gokul9995 ,is AutoFill turned on in the device settings? If so,try disabling autofill in the device : Settings → Passwords & Accounts → toggle "Off" the AutoFill Passwords.

Check the bit about [ios passwords](https://reactnative.dev/docs/textinput#textcontenttype)
