### ISSUE TITLE
Hermes Sampling Profiler does not produce line/column information if bundleInDebug is true (Android)

### ISSUE THREAD

**Issue by felixSchl** [facebook/react-native#31914]
## Description

Profiles recorded with the Sampling Profiler for Hermes on Android do not include line/column information when bundling JS in debug builds. I am interested in profiling the application start up with Hermes and thus would like to get to close to the release version as possible while still being able to run the sampling profiler. I am using these settings in my `android/app/build.gradle` file:

```
project.ext.react = [
    enableHermes: true,
    bundleInDebug: true,
    devDisabledInDebug: true,
    hermesFlagsDebug: ["-output-source-map", "-Og"],
]
```

## React Native version:

```
System:
    OS: macOS 11.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 1.14 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - /var/folders/4s/nd9gdf3s6fn48ncybxm7cbzw0000gn/T/yarn--1627437024838-0.5842697790609319/node
    Yarn: 1.22.10 - /var/folders/4s/nd9gdf3s6fn48ncybxm7cbzw0000gn/T/yarn--1627437024838-0.5842697790609319/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7351085
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.3 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: ~0.63.4 => 0.63.4
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Configure gradle to `bundleInDebug: true` (see description above for all settings I used)
2. Profile app using the sampling profiler options from developer menu
3. Collect report using `react-native profile-hermes`
4. The report does not contain line/column information required for determining source locations via the source map

## Expected Results
I expected to get source information for each captured frame as I would if I ran the sampling profiler without bundling first.

**Comment by cortinico** [comment]
Hey,
We're cleaning up the React Native issue tracker to make sure we focus on the most important issues first.

I'm closing this one because it's stale and related to a version of React Native we no longer support. If the issue persists on the latest version, please re-open a new issue and reference this one.

Thank you.
