### ISSUE TITLE
ReactNative is giving error on Images with uppercase extension E.g. - .JPG or .PNG (Android)

### ISSUE THREAD

**Issue by RahulSChauhan50** [facebook/react-native#31925]
## Description
When loading Image assets using require or uri as source it gives error in Images containing uppercase file extensions, Images with lowercase extension are showing fine.

## React Native version:
System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 3.28 GB / 7.91 GB
  Binaries:
    Node: 14.17.3 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version  4.2.0.0 AI-202.7660.26.42.7486908
    Visual Studio: Not Found
  Languages:
    Java: 13.0.1 - C:\Program Files\Java\jdk-13.0.1\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.1 => 0.64.1
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
1.Import Image from 'react-native' and in source pass require('image.PNG')
2.use any image with uppercase extension like .JPG or .PNG

## Expected Results
None of these files exist:
  * assets\image.JPG(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * assets\image.JPG\index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
>64 |         />
  65 |         <Image
  66 |           source={require('../../image.JPG')}
     |                            ^
  67 |           style={{width: '100%', height: 200}}
  68 |           resizeMode="contain"
  69 |         />

### Working : 
`<Image
          source={require('../../image.jpg')}
          style={{width: '100%', height: 200}}
          resizeMode="contain"
        />`
### Not Working
`<Image
          source={require('../../image.JPG')}
          style={{width: '100%', height: 200}}
          resizeMode="contain"
        />`

### Screenshot of error
![Screenshot_1627625559](https://user-images.githubusercontent.com/60318300/127611321-0e37fdaf-991b-44ce-a1ee-dd8e0dc944a4.png)

**Comment by safaiyeh** [comment]
hm interesting @RahulSChauhan50 is there a reason why uppercase is necessary and not converting the file type to lowercase?

**Comment by RahulSChauhan50** [comment]
> 
> 
> hm interesting @RahulSChauhan50 is there a reason why uppercase is necessary and not converting the file type to lowercase?

The Images are coming from backend and some of them extensions are in uppercase.

**Comment by safaiyeh** [comment]
Gotcha, and in iOS the capital file types are accepted?

**Comment by RahulSChauhan50** [comment]
> 
> 
> Gotcha, and in iOS the capital file types are accepted?

I did't try it in ios.For now the issue is happening in android.

**Comment by safaiyeh** [comment]
Can you try adding this to your `metro.config.js` file?

```javascript
const defaultAssetExts = require("metro-config/src/defaults/defaults").assetExts;

module.exports = {
  resolver: {
    assetExts: [
      ...defaultAssetExts,
      "JPG",
    ]
  }
};
```

Metro has a list of [accepted file types](https://github.com/facebook/metro/blob/af23a1b27bcaaff2e43cb795744b003e145e78dd/packages/metro-config/src/defaults/defaults.js#L15) and it might be case sensitive.

**Comment by RahulSChauhan50** [comment]
> 
> 
> Can you try adding this to your `metro.config.js` file?
> 
> ```js
> const defaultAssetExts = require("metro-config/src/defaults/defaults").assetExts;
> 
> module.exports = {
>   resolver: {
>     assetExts: [
>       ...defaultAssetExts,
>       "JPG",
>     ]
>   }
> };
> ```
> 
> Metro has a list of [accepted file types](https://github.com/facebook/metro/blob/af23a1b27bcaaff2e43cb795744b003e145e78dd/packages/metro-config/src/defaults/defaults.js#L15) and it might be case sensitive.

Didn't work still getting error
![Screenshot_1627807156](https://user-images.githubusercontent.com/60318300/127764881-165084a2-8948-4647-870a-32d8f8d286d9.png)

**Comment by safaiyeh** [comment]
Ah, thought that would be a quick fix. Thanks for going back and forth with me.

Next steps can you file an issue with metro at https://github.com/facebook/metro. This is where asset resolution is handled; will close this issue in favor of that one.
