### ISSUE TITLE
Wrong Text bounds when Text is close to a new line

### ISSUE THREAD

**Issue by gre** [facebook/react-native#3192]
Proof: https://rnplay.org/apps/wZ0Ivw

<img width="191" alt="screen shot 2015-10-02 at 10 32 32" src="https://cloud.githubusercontent.com/assets/211411/10242415/ebe1cc5c-68f0-11e5-8170-4c8dd6429f05.png">

Expected result (photoshopped):

<img width="191" alt="screen shot 2015-10-02 at 10 32 32_" src="https://cloud.githubusercontent.com/assets/211411/10242465/4e3da6dc-68f1-11e5-8e28-3cec73f1c059.png">

**Comment by gre** [comment]
:up: do you confirm this to be a bug? do you think this is a RN bug at all, or it is how iOS native Text returns?

Mesuring the height of multi-line text is an important use-case I have, and we currently can't trust Text measure.

**Comment by brentvatne** [comment]
cc @nicklockwood

**Comment by nicklockwood** [comment]
Sounds like it could be the same issue as https://github.com/facebook/react-native/pull/2838 that we closed earlier today. Can you confirm if it's still happening?

**Comment by brentvatne** [comment]
Thanks @nicklockwood! @gre - feel free to close this if you verify that it has been resolved

**Comment by gre** [comment]
Unfortunately on `0.13.1` I'm now experimenting the same bug but "reversely": the text now tends to overflow it's bound..
so we moved from a version where the bound is "pessimist" (tends to think text overflow to new line where it doesn't) to a version where it's "optimist" (tends to think the text does not overflow to new line where it does).

**Comment by gre** [comment]
looks like this bug is gone
