### ISSUE TITLE
Flash of white LaunchScreen.xib after splash screen (iOS) 

### ISSUE THREAD

**Issue by saurabh874** [facebook/react-native#31923]
// Place this code after "[self.window makeKeyAndVisible]" and before "return YES;"
  UIStoryboard *sb = [UIStoryboard storyboardWithName:@"LaunchScreen" bundle:nil];
  UIViewController *vc = [sb instantiateInitialViewController];
  rootView.loadingView = vc.view;
  
  this code is not working at all.
  please help me out if anybody have solution to resolve this.
  
 "react-native": "0.64.1",
 "react": "17.0.1",

**Comment by Humad** [comment]
Also having the same issue
