### ISSUE TITLE
react-native run-android error 

### ISSUE THREAD

**Issue by notrachelchen** [facebook/react-native#31927]
when i run react-native run-android it says command 'run-android' unrecognized. Make sure that you have run 'npm install' and that you are inside a react native project. However, I already installed npm.

**Comment by Njinou** [comment]
You might not be in the right directory if you had just created the project or if the project already existed on your local. But if you had cloned a repo then you need to run either npm install or yarn after installing react-native-cli (of course)

**Comment by GhostCode47** [comment]
Just use command  'npm run android' or  'npx react-native run-android' that's work for me

**Comment by notrachelchen** [comment]
> Just use command 'npm run android' or 'npx react-native run-android' that's work for me

I just tried it and it still says that the command run android is not recognized.

**Comment by notrachelchen** [comment]
> react-native-cli



> You might not be in the right directory if you had just created the project or if the project already existed on your local. But if you had cloned a repo then you need to run either npm install or yarn after installing react-native-cli (of course)

Hi I'm new to coding so I'm not sure what you mean by directory. Would you mind elaborating?

**Comment by GhostCode47** [comment]
Are you had execute command 'npm start'  before you execute command 'npm run android'?
