### ISSUE TITLE
KeyboardAvoidingView covers the whole view which is wrapped in it on Android

### ISSUE THREAD

**Issue by rubina-shakhkyan** [facebook/react-native#31922]
## Description
`KeyboardAvoidingView` covers content on Android.

**iOS:**

<img width="438" alt="Screen Shot 2021-07-29 at 16 08 37" src="https://user-images.githubusercontent.com/64727687/127506846-d00d05e3-b212-4f48-90fa-c37b99717ad4.png">

**Android:**

<img width="438" alt="Screen Shot 2021-07-29 at 16 07 18" src="https://user-images.githubusercontent.com/64727687/127506635-1c2da94e-401f-4ade-b28f-a3cedaec95ce.png">

## React Native version:
0.63.3

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Wrap stack navigator in `KeyboardAvoidingView' with `style={{flex:1}}` and any behavior ("padding", "height", "position")
2. Close and reopen app several times, then dismiss the keyboard
3. `KeyboardAvoidingView` covers the whole view wrapped inside

## Expected Results
View is not expected to cover the whole screen, but has to only add some padding on bottom when keyboard is open

## Snack, code example, screenshot, or link to a repository:
In this repo we can see the result attached in pictures(iOS is perfect, Android is buggy). `KeyboardAvoidingView` has a blue background and the wrapped content has yellow background to make it more visible.
This result is visible in a plain app, but in the actual app, this happens after minimizing and reopening app several times.
https://github.com/rubina-shakhkyan/buggyApp

**Comment by Munir-Hassan** [comment]
Has anyone found the solution yet? This same problem is also occuring to mine as we
![Screenshot_1636649809](https://user-images.githubusercontent.com/23612265/141337906-ede376cb-77a2-4927-b7f7-c903bf941977.png)
ll

**Comment by kevinwaelkens** [comment]
Seems like the `behaviour="padding"` property breaks it on Android. Right now I've tackled it by implementing:
```js
behavior={Platform.OS === 'ios' ? 'padding' : undefined}
```

**Comment by tmorganPDC** [comment]
31922

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by rubina-shakhkyan** [comment]
I solved it by implementing `KBAvoiding` view manually, but the issue is still there. Behavior `height`/`position` doesn't add this extra white space, but also doesn't add the required offset from the bottom.

**Comment by svenlombaert** [comment]
> Seems like the `behaviour="padding"` property breaks it on Android. Right now I've tackled it by implementing:
> 
> ```js
> behavior={Platform.OS === 'ios' ? 'padding' : undefined}
> ```

More info on this (we're colleagues): not setting the behaviour seems to work from Android 11 and onwards. But for Android 10, none of the behaviors seem to actually work or they behave inconsistently.`padding` has the result from OP, 50% of the time, `height` doesn't let me scroll to the end of the list and `position` renders completely blank. 

I don't understand how something this blocking and important has been so buggy throughout the years. I'd like to help fix this problem but I have no clue where to start.
