### ISSUE TITLE
Vulnerability issue

### ISSUE THREAD

**Issue by Babar-Memon** [facebook/react-native#31935]
Hi I'm facing a High risk warning issue when i tested my app for vulnerability scan and that issue is occur in every React native app. Is there anyone who solved this issue thanks.

Description:
The mobile application uses weak hashing algorithms. Weak hashing algorithms (e.g. MD2, MD4, MD5 or SHA-1) can be
vulnerable to collisions and other security weaknesses, and should not be used when reliable hashing of data is required.

**Comment by chrisbobbe** [comment]
Could you please paste an exact copy of the output you're concerned about?

**Comment by Babar-Memon** [comment]
@chrisbobbe can you please elaborate that what are the further steps you need.

**Comment by cortinico** [comment]
Closing as stale
