### ISSUE TITLE
`npx react-native init MyApp` creates App and Section components with the `Node` type in a `.js` file.

### ISSUE THREAD

**Issue by gjstreicher** [facebook/react-native#31936]
## Description
The standard `react-native init MyApp` shouldn't generate TypeScript types and syntax in what is supposed to be a pure `.js` file. This occurs with the `App.js` file.

## React Native version:
Most likely version 0.64. I run it via `npx`, so I'm not exactly sure.

## Steps To Reproduce
1. `npx react-native init MyApp`

## Expected Results
I expect there to be no types and TypeScript syntax in the `App.js` file.

## Resulting code in App.js
```
import type {Node} from 'react';
// ...

const Section = ({children, title}): Node => {
// ...
}

const App: () => Node = () => {
// ...
}
```

**Comment by safaiyeh** [comment]
I agree with not having TypeScript in the template. Since there is a maintained typescript project for it. I'm not too aware of the decision here maybe someone else has context.

Maybe @kelset ?

**Comment by kylemccurley** [comment]
Receiving the same issue with the same steps to reproduce

**Comment by ybf970928** [comment]
You may need npm uninstall -g react-native-cli

**Comment by kelset** [comment]
Is that type Node even TS? Isn't it from Flow? 🤔

What's the big problem with this btw? It's just placeholder code

**Comment by kelset** [comment]
Closing, same reasoning as https://github.com/facebook/react-native/issues/31952#issuecomment-1087317439
