### ISSUE TITLE
iOS App of react-native takes infinite time to build.

### ISSUE THREAD

**Issue by RakshithaAcharya** [facebook/react-native#31939]
I created the sample application with the react version of 17.0.1 and react-native version of 0.64.2. However the iOS application takes infinite building time.

Below is the package.json of sample application
`{
  "name": "MyTestApp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "react": "17.0.1",
    "react-native": "0.64.2"
  },
  "devDependencies": {
    "@babel/core": "7.14.8",
    "@babel/runtime": "7.14.8",
    "@react-native-community/eslint-config": "2.0.0",
    "babel-jest": "26.6.3",
    "eslint": "7.14.0",
    "jest": "26.6.3",
    "metro-react-native-babel-preset": "0.64.0",
    "react-test-renderer": "17.0.1"
  },
  "jest": {
    "preset": "react-native"
  }
}
`
## React Native version:
Below is the info about react on running **react-native info**
`info Fetching system and libraries information...
(node:13631) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
System:
    OS: macOS 11.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 871.96 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.3 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.9 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /Users/rakshitha/.rvm/rubies/ruby-2.7.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.2 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found`

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.
1. Run the empty react native sample application  and the app fails to launch.

## Solutions tried
1.Tried with different version of react-native(i.e 0.63.4)
2. Deleted the derived data
3.Restarted the machine.

## Expected Results
Application must launch and run.

**Comment by valeriashpiner** [comment]
I am experiencing the same issue. I rolled back to 0.63.2.
