### ISSUE TITLE
react native 0.64.2 (iOS) fetch Network request failed

### ISSUE THREAD

**Issue by hiephuynhFDS** [facebook/react-native#31940]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
using fetch to request network

## React Native version:
0.64.2

## Steps To Reproduce
init a new react native project then in the useEffect i use bellow codes: 
React.useEffect(() => {
        fetch({
            url: 'https://reqres.in/api/users?page=2',
            method: 'GET',
            headers: {
                Accept: 'application/json',
                'Content-Type': 'application/json'
            }
        }).then(response => {
            console.log(response)
        }).catch(e => console.log(e))
    }, []);

**Comment by hiephuynhFDS** [comment]
My ios info.plist config: <key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
		<key>NSExceptionDomains</key>
		<dict>
			<key>localhost</key>
			<dict>
				<key>NSExceptionAllowsInsecureHTTPLoads</key>
				<true/>
			</dict>
		</dict>
	</dict>

**Comment by Bardiamist** [comment]
Same issue

**Comment by nickwelp** [comment]
Can you confirm whethee it works on Android?

**Comment by nickwelp** [comment]
I've moved on to replacing fetch react-native-fetch-blob which has a drop in replacement for Fetch

**Comment by Bardiamist** [comment]
> Can you confirm whethee it works on Android?

I tried hiephuynhFDS's example and its not work on Android also
