### ISSUE TITLE
Broken Query String Parsing in URL Library

### ISSUE THREAD

**Issue by CrshOverride** [facebook/react-native#31956]
## Description
The current implementation of the `URL` library improperly parses URLs that include a query string.

## React Native version:
```
info Fetching system and libraries information...
System:
    OS: Linux 5.11 Pop!_OS 21.04
    CPU: (32) x64 AMD Ryzen 9 3950X 16-Core Processor
    Memory: 37.21 GB / 62.81 GB
    Shell: 3.3.1 - /usr/bin/fish
  Binaries:
    Node: 14.16.1 - ~/.asdf/installs/nodejs/14.16.1/bin/node
    Yarn: 1.22.10 - ~/.asdf/installs/nodejs/14.16.1/.npm/bin/yarn
    npm: 6.14.12 - ~/.asdf/installs/nodejs/14.16.1/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7486908
  Languages:
    Java: 1.8.0_232 - /home/justin/.asdf/shims/javac
    Python: 2.7.18 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Add a simple call to create a new URL instance: `let url = new URL('https://google.com/search?q=test');`
2. Log the parsed url using `console.log(url.href)`.
3. Notice that the url is now `https://google.com/search?q=test/` (with a new trailing / appended).
4. Verify that `[...url.searchParams]` is an empty Array.

## Expected Results
1. Once constructed, the URL should be properly parsed (including the query string).
2. `url.href` should return `https://google.com/search?q=test`.
3. `[...url.searchParams]` should be `[ [ 'q', 'test' ] ]`.

## Snack, code example, screenshot, or link to a repository:
https://snack.expo.dev/JdnvjROHO

**Comment by chrisbobbe** [comment]
There's `react-native-url-polyfill`, but I think RN should either
- promote that more prominently, or
- not default to an implementation that's full of really glaring bugs

See also https://github.com/facebook/react-native/issues/16434#issuecomment-580094423.

**Comment by safaiyeh** [comment]
@chrisbobbe agreed the solution should have a clean default for good third party possibilities or fix the issue.

**Comment by CrshOverride** [comment]
@safaiyeh @chrisbobbe Unfortunately this becomes awkward for library authors. The only reason I found this issue was that somebody installed my library in their application and it broke. I really don't like having to tell them to install another third party library just to fix the issue. My PR fixes query param parsing but doesn't address the rest of the features that aren't currently implemented.
