### ISSUE TITLE
Migrating the RN template to Typescript

### ISSUE THREAD

**Issue by kelset** [facebook/react-native#31952]
This issue wants to coordinate the conversation around the existing default template that is used when doing `npx react-native init`.

### Context

It seems that the "inciting incident" for this conversation was a report by someone about the fact that the current templates "contains" some Flow typing https://github.com/facebook/react-native/issues/31936.

Flow is the JS typing of choice at FB, but not as much used anymore in the broader community. This has led @safaiyeh to offer to remove them, which evolved in a conversation which led to this issue.

### Current status

Currently, the React Native CLI command `init` uses by default the template found in this repo ([here](https://github.com/facebook/react-native/tree/main/template)) as blueprint to generate the project. As indicated above, it indeeds contains [some Flow typing](https://github.com/facebook/react-native/blob/a8a85034e1cc23a144e58a9fb3215afbaebedb19/template/App.js#L10).

There is an optional template for Typescript already maintained in the RNC github org: https://github.com/react-native-community/react-native-template-typescript which is also [documented](https://reactnative.dev/docs/typescript) in the docs.

That said, the TS typings are maintained separately in the [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-native) repo. We are not aware (as of now) of any one specific person maintaining them.

### Proposal

Given how Typescript is [very widely used](https://npmcharts.com/compare/flow,typescript) in the Javascript world, it was proposed to replace the existing template with the ts-based one. Which should basically boil down to
- add a tsconfig
- add the typescript dependency to package.json
- add a dependency on @types/react and @types/react-native

We can do these and leave the file extension as .js, which makes it easy for both vanilla JS users and TS users.

This would mean that, by default (in an hypothetical future, >= 0.66) folks doing `npx react-native init` would get newly generated projects already set up for Typescript.

It would also mean (I think?) that the separate repo would get discontinued in favour of the folder within the main react-native repo (this one).

### Concern

In discussing this option, one main concern surfaced: `@types/react-native` is currently not maintained in sync with the core repo. In particular, typings live in an external repo outside of the monorepo requires waiting for someone else to review to land.

That said:
* it should(could?) be addressable
* There is some longer term work to generate the TS typings dynamically, which would remove the need for someone to manually put in effort to update them.
* currently the template is not tested (AFAIK) in any CI, so there's no actual blocker to day-to-day development, it would only be a "manual" effort to update the types during a release process
* it looks like it should be possible to have some test/pre-release types being set up if the template would start to be tested on CI
* as per mention above, making the TS template the default would "add work" to the [release process](https://github.com/react-native-community/releases/blob/master/docs/release-process.md) in the RC phase. (but it sounds reasonable to have to handle it)

---

pinging folks who were involved in the earlier conversations: @NickGerleman, @acoates-ms, @safaiyeh, @radko93, @satya164, @TheSavior

**Comment by ravirajn22** [comment]
Why can't we just make the init template pure JS, let the consumer decide later what he wants, typescript or flow or pure JS. Why do we want to complicate stuffs?

**Comment by satya164** [comment]
@ravirajn22 if you don't want to use TS you can simply not care about the extra config file and typescript. It complicates nothing for people who don't want to use TS.

**Comment by ravirajn22** [comment]
Extra config file, extra dependencies and probably TS warnings the very first time you open app.js file. If you plan to convert this file to app.tsx, then unfamiliar syntax to developers who does not know TS. When there is a simple alternative, I feel its a burden for both react-native template maintainers and consumers.

Anyways I am not maintaining any of these so just my opinion, its up to you people.

**Comment by bell-steven** [comment]
When I was a beginner, I found it very confusing when I came across a file written in ts.  I believe that it makes react-native more difficult to use for beginners.

**Comment by kelset** [comment]
@bell-steven the App.js file itself will stay in plain js. The only change is that the template will be configured to be "out of the box" ready to accept TS/TSX files.

**Comment by safaiyeh** [comment]
Thanks for setting up the issue. I'll be looking into this the next couple of days to propose a change to the template.

**Comment by chrisbobbe** [comment]
We at [Zulip Mobile](https://github.com/zulip/zulip-mobile) strongly appreciate Facebook's development of Flow, and React Native's support for it. We're happy to say more about why we prefer Flow, here or somewhere else (maybe on a video call if you'd prefer that). 🙂

That said, it sounds like there might be a reasonable way to lower barriers for TypeScript users, while still offering Flow support for current and new projects that prefer it. Making the template-app App.js into plain JS sounds pretty small and reasonable to me. If doing so, I suggest adding a code comment or a note in a doc saying that people can set up Flow very easily if they want. (And, if you like, saying that TypeScript's initial setup is easy, too, I guess, for the benefit of people who'd prefer that. 😉)

**Comment by kelset** [comment]
I'm going to close this off as the conversation basically ended up being to just rely on the separate template https://github.com/react-native-community/react-native-template-typescript
