### ISSUE TITLE
Module Build Failed PhaseScriptExecution (in target OpenSSL-Universal)

### ISSUE THREAD

**Issue by lsbyerley** [facebook/react-native#31951]
## Description

Initiated a new project with `npx react-native init myApp` does not build. This is a barebones project, no other changes have been made after the initial project init command

## React Native version:
System:
    OS: macOS 10.15.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 9.05 GB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
    Yarn: Not Found
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
    Watchman: 2021.06.07.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.7, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 11.7/11E801a - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_111 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.2 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. `npx react-native init myApp`
2. `cd myApp`
3. `npx react-native run-ios`

## Expected Results
App builds correctly and runs in simulator

## Module Build Results

```
warning: Mapping architecture arm64 to x86_64. Ensure that this target’s Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target ‘OpenSSL-Universal’ from project ‘Pods’)

PhaseScriptExecution [CP]\ Copy\ XCFrameworks /Users/user/Library/Developer/Xcode/DerivedData/myApp-aakpxxhjqpcszlbvctrmbeunxdrq/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/OpenSSL-Universal.build/Script-BD3BB04C9F7F7A61D27919A0454E6173.sh (in target ‘OpenSSL-Universal’ from project ‘Pods’)
```

**Comment by safaiyeh** [comment]
Refer to this guide for M1 issues. https://github.com/facebook/react-native/issues/31941

**Comment by lsbyerley** [comment]
@safaiyeh I'm not on an M1 man that doesn't help me

**Comment by lsbyerley** [comment]
If anyone comes across this.. I needed to be on xcode 12.4 to run react-native 0.64

**Comment by dellwatson** [comment]
same issue, not M1 and cannot run 0.64, I do able to run 0.63
