### ISSUE TITLE
/node_modules/react-native/ReactCommon/cxxreact/JSDeltaBundleClient.h: No such file or directory (in target 'React-cxxreact' from project 'Pods')

### ISSUE THREAD

**Issue by rush86999** [facebook/react-native#31954]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Fresh install on a bare react-native init project shows this error in xcode
```
/Users/xxxx/projects/xxxx/node_modules/react-native/ReactCommon/cxxreact/JSDeltaBundleClient.h: No such file or directory (in target 'React-cxxreact' from project 'Pods')
```

## React Native version:
Run `react-native info` in your terminal and copy the results here.
```
System:
    OS: macOS 11.5.1
    CPU: (4) x64 Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz
    Memory: 244.80 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.20.3 - ~/projects/fire-app/FireApp/node_modules/.bin/npm
    Watchman: 2021.06.07.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6308749
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 9.0.4 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.2 => 0.64.2
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```
## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. react-native init and follow instructions for a fresh install
2. installed also react-native-unimodules and expo modules as well as other ones.

## Expected Results
No errors in Xcode.
<img width="899" alt="Screen Shot 2021-08-04 at 2 52 03 PM" src="https://user-images.githubusercontent.com/16848240/128238902-883d69f1-b527-4a65-a681-42b688c120a7.png">

## Snack, code example, screenshot, or link to a repository:
Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by Noshaid** [comment]
error: .../node_modules/react-native/ReactCommon/cxxreact/JSDeltaBundleClient.h: No such file or directory

What's the use of this file?

**Comment by Air-Craft** [comment]
+1
