### ISSUE TITLE
How to get iOS app to push up layout like Android

### ISSUE THREAD

**Issue by KrisLau** [facebook/react-native#31959]
## Description
On iOS when I have a text input inside an overlay, I have no way of getting it to avoid the keyboard even when wrapping the screen or the overlay with a `KeyboardAvoidingView` or even with `KeyboardAwareScrollView`. In Android, it is not a problem because it automatically pushes up the layout but in iOS, the layout does not change when the keyboard appears so it often blocks the input.

So far the only library I have had luck with is [react-native-keyboard-spacer](https://github.com/Andr3wHur5t/react-native-keyboard-spacer) which works but produces many errors and has long been dropped by the dev.

## React Native version:
```
System:
    OS: Windows 10 10.0.19043
    CPU: (4) x64 Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz
    Memory: 2.05 GB / 15.89 GB
  Binaries:
    Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.18.1 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7199119
    Visual Studio: Not Found
  Languages:
    Java: 11.0.10
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.2 => 17.0.2
    react-native: ^0.64.2 => 0.64.2
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Put a text input inside an Overlay
2. Open it on both iOS and Android

## Expected Results
For the keyboard to push up the layout on iOS (like how it does in Android)

## Snack, code example, screenshot, or link to a repository:
Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by KrisLau** [comment]
Ended up using `@react-native-community/hooks` to get the keyboard height and created my own keyboard spacer.

**Comment by princefishthrower** [comment]
This is ridiculous... there are hundreds of open issues having to do with non-functionality related to `KeyboardAvoidingView` yet all labeled with 'needs repro' 'needs triage' 'needs feedback' - isn't the fact that this component is clearly broken enough?

Its a mess, there are like 100 versions of a keyboard spacer out in the community, none less of a hack than the next...

**Comment by KrisLau** [comment]
@princefishthrower It works for the most part except with an overlay which is the part that sucks but I understand why it's taking so long considering how many more pressing issues are open. The workaround is a hack but it works for now. I'm sure they'll get to this eventually.

**Comment by gus-delpino** [comment]
@KrisLau  Out of curiosity, what's the "workaround" you are talking about? I'm seeing inconsistent behavior between different screens and for the life of me cannot figure out how to get it to work well without passing different values of keyboardVerticalOffset to each screen for no reason

**Comment by KrisLau** [comment]
@gus-delpino https://github.com/facebook/react-native/issues/31959#issuecomment-894524336
