### ISSUE TITLE
Local Images are not showing after building the IPA file Xcode - 12, IOS -14

### ISSUE THREAD

**Issue by snevula123456** [facebook/react-native#31968]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
I am facing an  Local Image not loading  on the Screens Issue after building the IPA file on Xcode - 12, IOS - 14 versions.
Local Images are showing while Development on the simulator.

## React Native version:
react-native : 0.64.2,
Xcode Version :  12.0.1 (12A7300),

## Steps To Reproduce
1. Ejected Expo react-native app.
2. updated the pod install
3. open .xcodeWorkspace file and then try to archive.
4. open the app in the Iphone
5. Local asset images are not showing.

## Expected Results

It should display the all the local images on the screen, after building the app.

## Debugging Links Followed

1 . Tried to https://stackoverflow.com/questions/35354998/react-native-ios-app-not-showing-static-assets-images-after-deploying solutions but still no use.

2. Tried https://github.com/facebook/react-native/issues/29279 solutions but still no luck.
3.  
![image](https://user-images.githubusercontent.com/25643849/128386520-987c609e-02f8-447b-b71b-b0d3f327dc46.png)
The Above Screenshot code is already available in the file.

## Snack, code example, screenshot, or link to a repository:
![image](https://user-images.githubusercontent.com/25643849/128387588-fbcb08db-d437-4327-bfbf-90958aafc0b0.png)

![image](https://user-images.githubusercontent.com/25643849/128386270-2865b19a-367f-4ee5-80b6-4ba8400a4ab9.png)

Thanks In Advance.

**Comment by ianberryman** [comment]
Same issue here on RN 0.63.4 and XCode 12.5.1. Recommend fixes don't work. Local images work in simulator but not on physical devices.

**Comment by cristianoccazinsp** [comment]
Something similar happens with `defaultSource` and local images. RN 0.65.1

**Comment by talaikis** [comment]
`<Image onError={...} source={require(xxx)} />` gives `appName.app/assets/assets/xxx` not available.

**Comment by robertqin86** [comment]
I'm unfortunately experiencing this issue. It seems to be introduced with the upgrade to `0.64.2`. My local image works fine in development but not when I package a release build.

**Comment by borg** [comment]
Still an issue on RN ```0.65.1```

Tried all those steps @talaikis, even cleaned my room, no dice.

It' s odd because compiler doesn't complain about missing images, and when adding to ```build phase``` assets are clearly embedded, which makes me suspect it is more a debug/release path difference issue. Works in debug, not in release. Reverting to use ```Images.xcassets``` until this is solved.

**Comment by talaikis** [comment]
> Still an issue on RN `0.65.1`
> Tried all those steps @talaikis, even cleaned my room, no dice.

I had a lot of old bundle issues on Xcode, went to build an app on fastlane and all them seems solved, at least for now. Not even try tp launch Xcode.

**Comment by vuletuanbt** [comment]
> Still an issue on RN `0.65.1`
> 
> Tried all those steps @talaikis, even cleaned my room, no dice.
> 
> It' s odd because compiler doesn't complain about missing images, and when adding to `build phase` assets are clearly embedded, which makes me suspect it is more a debug/release path difference issue. Works in debug, not in release. Reverting to use `Images.xcassets` until this is solved.

I'm facing it. How do you resolve it?

**Comment by DeltaCap019** [comment]
This solution works for me [images not showing up on release build](https://stackoverflow.com/a/69901102/1206052)

**Comment by henrique-in** [comment]
Anyone managed to find a solution, I'm having the same problem in react native 0.63.4

**Comment by cristianoccazinsp** [comment]
Try with RN 0.67.x

**Comment by henrique-in** [comment]
Solved the problem by adding this to metro.config.js

  transformer: {
         
      assetPlugins: ['expo-asset/tools/hashAssetFiles'],
      },

**Comment by LkyYuen** [comment]
any updates??

**Comment by pedrilla** [comment]
да, any updates?

**Comment by JohnEmanuel** [comment]
Hi guys this worked for me:
https://github.com/facebook/react-native/issues/26699#issuecomment-547715502

**Comment by wfrsnk** [comment]
be sure of using latin alphabet in name of image, this typo killed a lot of time for me  :/
