### ISSUE TITLE
creating a new app witho expo is giving error

### ISSUE THREAD

**Issue by adarsh-gupta101** [facebook/react-native#31963]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
New app couldnt be created due to some error in Scroll view

Failed building JavaScript bundle.
node_modules\react-native\Libraries\Components\ScrollView\ScrollView.js: Property body[42] of BlockStatement expected node to be of a type ["Statement"] but instead got "AssignmentExpression"

## React Native version:
~42.0.0

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.expo init
2.expo start

## Expected Results
metro bundler is not starting

**Comment by kelset** [comment]
see https://github.com/facebook/react-native/issues/31960
