### ISSUE TITLE
iOS app crash on manual reload while using a ScrollView and the remote debugger

### ISSUE THREAD

**Issue by wemow** [facebook/react-native#31980]
A recurring bug on multiple projects, every time I use a ScrollView and the remote debugger at the same time, after a while, the app crash when I manually reload without any message besides 

```
Invalidating <RCTCxxBridge: 0x7f8386606680> (parent: <RCTBridge: 0x6000005aa530>, executor: RCTWebSocketExecutor)
/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:48 [React DevTools] Connection to RN closed

```

https://user-images.githubusercontent.com/18286671/128574008-9c7c8ff1-eb2f-487d-b481-ec1331ce2b3b.mp4

React Native version: 0.64.2
Platform: iOS 13.7 Simulator

## Steps To Reproduce
1. Add a ScrollView to any app
2. Launch in on ios simulator
2. Enable the Chrome debugger
4. Work on the app, for a few minutes
3. Reload manually

## Expected Results
App reload without crashing

**Comment by chrisglein** [comment]
Do you have the full callstack for the crash?

**Comment by yemd** [comment]
I've got nothing, the only message I have in the console before the app closing is 
`Invalidating <RCTCxxBridge: 0x7fc24861a2d0> (parent: <RCTBridge: 0x600002c0e7d0>, executor: RCTWebSocketExecutor)
`

**Comment by yemd** [comment]
> ⚠️	Missing Environment Information
> ℹ️	Your issue may be missing information about your development environment. You can obtain the missing information by running `react-native info` in a console.

info Fetching system and libraries information...
(node:56764) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
System:
    OS: macOS 11.5.2
    CPU: (8) x64 Apple M1
    Memory: 66.04 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.8.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.9 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.10 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.2 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:
