### ISSUE TITLE
Please report: Excessive number of pending callbacks: 501.

### ISSUE THREAD

**Issue by JustCunn** [facebook/react-native#31988]
## Description
I'm trying to loop over a set of data that I have from Firebase and display it as a list. When a user clicks an item in that list, a modal appears with more detailed information about that item. But when I load the main component (`seeFaults`), I quickly get a warning saying:
```javascript
Please report: Excessive number of pending callbacks: 501. Some pending callbacks that might have leaked by never being called from native code: 
{"1590":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"1816":{},"1817":{},"1818":{},"1819":{},"1820":{},"1821":{},"1822":{},"1823":{},"1824":{},"1825":{},"1826":
{},"1827":{},"1828":{},"1829":{},"1830":{},"1831":{},"1832":{},"1833":
{},"1834":{},"1835":{},"1836":{},"1837":{},"1838":{},"1839":{},"1840":
{},"1841":{},"1842":{},"1843":{},"1844":{},"1845":{},"1846":
{},"1847":{},"1848":{},"1849":{},"1850":{},"1851":{},"1852":{},"1853":
{},"1854":{},"1855":{},"1856":{},"1857":{},"1858":{},"1859":
{},"1860":{},"1861":{},"1862":{},"1863":{},"1864":{},"...(truncated keys)...":451} 
```

But this only started appearing after I started to try to download images from Firebase and had an await in a for loop like:
```javascript
for (const img in images) {
    await storage().ref('/' + faults[i].images.img).getDownloadURL()
        .then( (url) => imageSet.push(url) );
}
```

When I commented all of this out, the warning kept appearing with each render, despite the code being identical to how it was before I started writing the image downloading code
## React Native version:
System:
    OS: macOS 11.0
    CPU: (8) x64 VirtualApple @ 2.50GHz processor
    Memory: 52.70 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.4 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.14 - /usr/local/bin/npm
    Watchman: 2021.06.07.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 23, 29, 30
      Build Tools: 29.0.2, 30.0.3
      System Images: android-29 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-31 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: javac 16 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.2 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Unfortunately, since I'm using a Firebase database I cannot make a reproducible sandbox or easily say how to replicate this without giving my database url away.

## Expected Results
For the component to render without the warning.

## Code
```javascript
export const FaultItem = (props) => {
    const [modalVisible, setModalVisible] = useState(null);

    return (<>
            <FaultModal modalVisible={modalVisible} setModalVisible={setModalVisible} text={props.fault_desc}/>
            <TouchableOpacity onPress={() => setModalVisible(!modalVisible)}>
                <Text>{props.fault_desc}</Text>
                <View>
                    <Text>{props.type}</Text>
                    <Text>{props.date}</Text>
                </View>
            </TouchableOpacity>
            </>
            )
}

export const FaultModal = (props) => {
    return (
        <Modal
            animationType='fade'
            transparent={true}
            visible={props.modalVisible}
            onRequestClose={() => {
            Alert.alert("Modal has been closed.");
            props.setModalVisible(!props.modalVisible);
            }}>
            <View>
                <View>
                    <ScrollView}>
                        <Text>{props.text}</Text>
                    </ScrollView>
                    <TouchableOpacity onPress={() => props.setModalVisible(!props.modalVisible)}>
                        <Text>Close</Text>
                    </TouchableOpacity>
                </View>
            </View>
        </Modal>
    )
}

export default function seeFaults() { //Main Component

    const [foremanSite, setForemanSite] = useState(null);
    const [rows, setRows] = useState([]);
    const [imageSet, setImageSet] = useState([]);

    useEffect(() => {
        const userId = auth().currentUser.uid;
        const dataBase = firebase.app().database(/*my firebase database url*/);
        dataBase.ref(`/users/${userId}/`).once('value').then(snapshot => setForemanSite(snapshot.val().foreman_site));
        dataBase.ref(`/sites/${foremanSite}/faults`).once('value').then(snapshot => {
            getFaults(snapshot.val());
        });
    }, [getFaults])

    function getFaults(faults) {
        for (const item in faults) {
            rows.push({
                fault_desc: faults[i].fault_description,
                owner: faults[i].owner,
                date: faults[i].date,
                type: faults[i].fault_type,
            });
        }
    }

    return (
        <SafeAreaView>
            <ScrollView>
                {rows.map( (item, i) => {return <FaultItem key={i} fault_desc={item.fault_desc} 
                owner={item.owner} date={item.date} type={item.type} /*images={item.images_uri}*//> })}
            </ScrollView>
        </SafeAreaView>
    )
}
```

**Comment by chrisbobbe** [comment]
https://github.com/facebook/react-native/issues/31830 looks similar; do you find clues there? Maybe the two issues can be consolidated.

**Comment by JustCunn** [comment]
I think the issue was that I was setting (or rather resetting) state within a for loop and then pushing all that to another state object and that was causing issues. Instead I updated a local variable and pushed that all to my state at the end of the loop.

Basically it was an excessive use of state and resolved it by using normal variables where possible.

Thanks for your help though @chrisbobbe :)
