### ISSUE TITLE
Hermes release build is only slow when installed from the Play Store

### ISSUE THREAD

**Issue by feiyingx** [facebook/react-native#31999]
## Description
We have a React Native Android app with Hermes enabled. We are seeing a huge performance issue with our app when it is downloaded through the Play Store (7s+ boot time). The same build runs very fast when installing the APK directly on the device (<2s boot time). This issue does not exist when the app does not have Hermes enabled.

Has anyone experienced this before? What are some factors that causes this discrepancy between the Play Store installation vs direct APK installation of the same build.

## React Native version:
System:
    OS: macOS 11.2.3
    CPU: (8) x64 Apple M1
    Memory: 23.96 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 10.19.0 - ~/.nvm/versions/node/v10.19.0/bin/node
    Yarn: 1.22.0 - ~/.nvm/versions/node/v10.19.0/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v10.19.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 23, 28, 29, 30
      Build Tools: 29.0.2, 30.0.2, 30.0.3
      System Images: android-23 | ARM EABI v7a, android-23 | Intel x86 Atom_64, android-23 | Google APIs ARM EABI v7a, android-23 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-24 | ARM 64 v8a, android-25 | Google APIs ARM 64 v8a, android-30 | Google APIs Intel x86 Atom, android-S | Google Play ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7351085
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.4 => 0.63.4
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Enable Hermes
2. `enableSeparateBuildPerCPUArchitecture = true`, `enableProguardInReleaseBuilds = false`
3. Create a release build `./gradlew :app:assembleRelease`
4. Install the release APK directly on device and record boot time
5. Upload the same release APK to Google Play, wait for it to be reviewed and published
6. Install the build from the Play Store and record boot time. Note the performance difference

## Expected Results
Installing the release build from the Play Store should have the same performance as installing the build APK directly.

**Comment by umang-simform** [comment]
@feiyingx  Have you been able to fix the issue or what? I think I am also facing a similar issue
