### ISSUE TITLE
App center Issue

### ISSUE THREAD

**Issue by Wright-Media** [facebook/react-native#31991]
I am trying to build my app on appcenter , but it always fails. It says react-native pods are not present even though everything is there. Please help.

Please provide any solution. 

![Uploading Screen Shot 2021-08-09 at 11.30.58 AM.png…]()

**Comment by laocunzhang98** [comment]
You can try to perform:
rm -rf node_modules && yarn install
cd ios && pod deintegrate && pod install && cd ..
