### ISSUE TITLE
Compliance with Apple policy

### ISSUE THREAD

**Issue by orktes** [facebook/react-native#320]
Hi!

Do you have any information if using React Native (JavascriptCore) and Option 1 (https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/UIExplorer/AppDelegate.m#L34) type approach where you download the files from an external server before constructing the UI is in compliance with Apple's policies if used in a live application. I.e have you had any luck in finding out if Apple considers JavascriptCore to be a part of the "WebKit framework" mentioned in the program requirements. 

```
3.3.2 An Application may not download or install executable code.
Interpreted code may only be used in an Application if all scripts, code and
interpreters are packaged in the Application and not downloaded. The only
exception to the foregoing is scripts and code downloaded and run by Apple's
built-in WebKit framework, provided that such scripts and code do not change the
primary purpose of the Application by providing features or functionality that are
inconsistent with the intended and advertised purpose of the Application as
submitted to the App Store. 
```

**Comment by drkibitz** [comment]
Although the verbiage is important...

What would prevent us from having an off screen WKWebView, and a JSContext within that, doing the exact same thing the JSContext in JSCore is doing here?

**Comment by ericvicenti** [comment]
Unfortunately, we can't really discuss legal matters or Apple's policies on Github.

For what it's worth, I think you're quoting an old version of that document.

**Comment by orktes** [comment]
It's the latest revision I could find. Hopefully you are able to provide this information soon before people start submitting/designing apps that require the JS to be loaded from a remote server.

**Comment by tobyhughes** [comment]
I imagine that the JS will be bundled into the application when you submit it to the App Store, not running on a remote server.

**Comment by orktes** [comment]
@tobyhughes Yep but the api doesn't limit you to do so. The ability to update code (without the user updating the app and you going thought the release process) on the fly is something that is a powerful feature that people doing web are used to.

**Comment by orktes** [comment]
Imagine pushing a bug fix to your CDN and having a push server to notify the clients to download and reload. And compare that to a two week release process and then waiting for the users to update the app.

**Comment by mikemintz** [comment]
@orktes That is awesome. Do you know of any examples or documentation relevant for updating JS code on the fly? I'm not familiar with how react native stores and loads JS assets.

**Comment by orktes** [comment]
@mikemintz In abstract the functionality would not be that different compared to the way react native currently reloads the application in the simulator. Application could just check if a new version is available by for example comparing the E-tag of the HEAD request to the JS file stored in CDN and the invoke a function on the native side to reload. JS can even be downloaded on the background to reduce UX impact. Of course persisting ui state before reloading and reanimation has to be handled in the application (js code) it self. For easier state management and consistent UX the reloading could be initiated only when most of the UI would either way be changed. For example when navigating to a new route in the Navigator component. But even without actual "on the fly" reloading the ability to load new updated JS when the application (re)starts comes with huge benefits.

**Comment by orktes** [comment]
Seems that apple has revised their agreement to include JavascriptCore some time ago. So we should be fine.

**Comment by ssssssssssss** [comment]
@orktes Where is the revised agreement? Is there any other none-FB app been approved by Apple?

**Comment by orktes** [comment]
@ssssssssssss you can see it in your apple developer portal. I don't currently have any knowledge about apps that are doing this.

**Comment by hfossli** [comment]
So downloading javascript is fine? This is a major feature and win for React Native IMO! This was the main thing holding me back from using React Native. 

There really should be some paragraphs about this in the README.md and there should be a complete guide for how to acheive this. 

[Here](https://developer.apple.com/programs/ios/information)'s the latest
```
3.3.2 An Application may not download or install executable code. Interpreted
code may only be used in an Application if all scripts, code and interpreters are
packaged in the Application and not downloaded. The only exception to the
foregoing is scripts and code downloaded and run by Apple's built-in WebKit
framework or JavascriptCore, provided that such scripts and code do not change
the primary purpose of the Application by providing features or functionality that are
inconsistent with the intended and advertised purpose of the Application as
submitted to the App Store.
```

**Comment by brentvatne** [comment]
@hfossli - yup that is fine, we do it in https://itunes.apple.com/us/app/react-native-playground/id1002032944?mt=8

If you'd like to add something to the README I can review and merge, just ping me on the pull request!

**Comment by hfossli** [comment]
Here https://github.com/facebook/react-native/pull/2097

**Comment by hfossli** [comment]
What about Android? Same policy there?
