### ISSUE TITLE
Peer dependencies takes precedence over manually installed CLI tools version

### ISSUE THREAD

**Issue by xRiot** [facebook/react-native#32002]
## Description
We've ran into a (resolved) issue which caused our iPhone devices to not be detected by `yarn react-native run-ios` (https://github.com/react-native-community/cli/issues/1404). We wanted to solve this by just updating the CLI tools. However, `react-native@0.64.1` package's peer dependencies doesn't respect manually installed version of CLI tools (`@react-native-community/cli@5.0.1`, `@react-native-community/cli-tools@5.0.1`, `@react-native-community/cli-platform-ios@5.0.2`) and this is probably still the case with latest release (0.64.2):

```bash
% yarn add @react-native-community/cli@5.0.1 @react-native-community/cli-tools@5.0.1 @react-native-community/cli-platform-ios@5.0.2 --dev
% yarn why @react-native-community/cli-platform-ios
=> Found "@react-native-community/cli-platform-ios@5.0.2"
info Has been hoisted to "@react-native-community/cli-platform-ios"
info This module exists because it's specified in "devDependencies".
info Disk size without dependencies: "584KB"
info Disk size with unique dependencies: "7.07MB"
info Disk size with transitive dependencies: "9.62MB"
info Number of shared dependencies: 30
=> Found "react-native#@react-native-community/cli-platform-ios@5.0.1-alpha.2"
info This module exists because "react-native" depends on it.
info Disk size without dependencies: "316KB"
info Disk size with unique dependencies: "6.81MB"
info Disk size with transitive dependencies: "9.36MB"
info Number of shared dependencies: 30
✨  Done in 1.29s.
```

```bash
% xcrun xctrace list devices
== Devices ==
Admin’s MacBook Pro (D9ED0917-5469-56FB-A99C-A7EF4F3B6CE5)
Admin’s iPhone (13.6.1) (00008030-00065540028B802E)
```

```bash
% yarn react-native run-ios --device "Admin’s iPhone"
info Found Xcode workspace "Project.xcworkspace"
error Could not find a device named: "Admin’s iPhone". Available devices:
✨  Done in 33.89s.
```

**react-native command doesn't actually use the latest installed CLI tools but instead the peer dependency version**. This seems rather counterintuitive and could be problematic in the future when such issue happens again.

## React Native version:
0.64.1 in the reproduction example but the issue itself isn't version dependent

## Steps To Reproduce
One way to try this is to use 0.64.1 with latest CLI tools, react-native will fallback to peer dependency version (`@react-native-community/cli-platform-ios@5.0.1-alpha.2`) which doesn't support xCode 12.5.1 and thus the physical device wont be found.

1. `yarn add 0.64.1`
2. `yarn add @react-native-community/cli@5.0.1 @react-native-community/cli-tools@5.0.1 @react-native-community/cli-platform-ios@5.0.2 --dev`
3. `yarn react-native run-ios --device "Username’s iPhone"`

## Expected Results
Manually installed CLI tools version to be used instead of the version included in react-native's peer dependencies.

**Comment by liamjones** [comment]
I _think_ you've just hit this due to the way the yarn.lock and the node module resolution strategy works (e.g. there may not be anything RN specific going on here).

As a test, now you've got all those dependencies in your package.json, if you were to delete your yarn.lock and `yarn` again to regenerate it, do those instances of the CLI package then converge to one version?

**Comment by xRiot** [comment]
> I think you've just hit this due to the way the yarn.lock and the node module resolution strategy works (e.g. there may not be anything RN specific going on here).

@liamjones Thanks for the quick reply! It boggles my mind that Yarn 1.x would act this way although it's not impossible (haven't tried Yarn 2.x yet)

> As a test, now you've got all those dependencies in your package.json, if you were to delete your yarn.lock and `yarn` again to regenerate it, do those instances of the CLI package then converge to one version?

For context, all our packages in package.json are pinned to exact version numbers. I tried deleting `yarn.lock` as well as `node_modules` and then `$ yarn install` but the issue still persists (it still executes the peer dependency instead of manually installed version). Thanks for the tip though 👍

**Comment by liamjones** [comment]
>It boggles my mind that Yarn 1.x would act this way although it's not impossible (haven't tried Yarn 2.x yet)

It can happen. For example, if I have a dependency that needs `^1.0.0` of something installed and that pulled `1.0.3` because that was the only version out at the time and then later I add a dependency that needs `^1.0.5` of the same package yarn 1 will not go "oh, both of those could be the same version as long as it's ^1.0.5+!". It'd leave the existing one pinned to 1.0.3 and would add a second version for the ^1.0.5. [yarn-deduplicate](https://github.com/atlassian/yarn-deduplicate) can help resolve this.

>For context, all our packages in package.json are pinned to exact version numbers.

That's fine, it's just I was looking at 0.64.1's package.json dependency on the CLI and it's `^5.0.1-alpha.0` so both it and your manual specification of cli being `5.0.1` should converge to the same version if there's nothing locking one to be earlier... (see https://semver.npmjs.com/).

Oh, I may have just noticed your issue? You seem to be using a global `react-native` command, run it via `yarn react-native`, does that work correctly? I believe the global install of the CLI is no longer recommended nowadays.

I've just tried a from scratch 64.1 project and it seems to work fine:

```
 ~/code  npx react-native init TestRNProject --version 0.64.1
...
 ~/code  cd TestRNProject
 ~/code/TestRNProject  yarn add @react-native-community/cli@5.0.1 @react-native-community/cli-tools@5.0.1 @react-native-community/cli-platform-ios@5.0.2 --dev                                                                                                    ∞
yarn add v1.22.11
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "react-native > react-native-codegen > jscodeshift@0.11.0" has unmet peer dependency "@babel/preset-env@^7.1.6".
warning "@react-native-community/eslint-config > @typescript-eslint/eslint-plugin > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
success Saved 0 new dependencies.
✨  Done in 2.65s.
 ~/code/TestRNProject  yarn list @react-native-community/cli-platform-ios                                                                                                                                                                                         ∞
yarn list v1.22.11
warning Filtering by arguments is deprecated. Please use the pattern option instead.
└─ @react-native-community/cli-platform-ios@5.0.2
✨  Done in 0.45s.
```

There is only a single version, 5.0.2 displaying in the list when I'm finished.

**Comment by xRiot** [comment]
> Oh, I may have just noticed your issue? You seem to be using a global react-native command, run it via yarn react-native, does that work correctly? I believe the global install of the CLI is no longer recommended nowadays.

Nice catch @liamjones! We store that command in package.json and it's automatically prefixed with yarn when you execute it, I did a poor job at pasting it here, my bad. I updated the original post.

> It can happen. For example, if I have a dependency that needs ^1.0.0 of something installed and that pulled 1.0.3 because that was the only version out at the time and then later I add a dependency that needs ^1.0.5 of the same package yarn 1 will not go "oh, both of those could be the same version as long as it's ^1.0.5+!". It'd leave the existing one pinned to 1.0.3 and would add a second version for the ^1.0.5. yarn-deduplicate can help resolve this.

Awesome find! This worked great for us:
```bash
% yarn list @react-native-community/cli-platform-ios           
yarn list v1.22.10
warning Filtering by arguments is deprecated. Please use the pattern option instead.
├─ @react-native-community/cli-platform-ios@5.0.2
└─ react-native@0.64.1
   └─ @react-native-community/cli-platform-ios@5.0.1-alpha.2
✨  Done in 2.06s.
```
