### ISSUE TITLE
PanResponder's nativeEvent Touch Location Differs on Android/iOS

### ISSUE THREAD

**Issue by marcshilling** [facebook/react-native#3201]
I'm running the same app side by side on both platforms and logging the native touch event. On iOS, the x/y touch location returned is the location WITHIN the component's own bounds (as I would expect). On Android, it appears to be returning the touch location within the screen bounds.

Anyone else experiencing this?

**Comment by corymsmith** [comment]
I'm also seeing this while trying to get my fork of react-native-slider working on Android (https://github.com/corymsmith/react-native-slider).

**Comment by marcshilling** [comment]
@corymsmith that's exactly where I discovered it haha

**Comment by satya164** [comment]
This should be fixed in recent versions.
