### ISSUE TITLE
Generate sourcemaps from CLI

### ISSUE THREAD

**Issue by benvinegar** [facebook/react-native#3202]
It would be handy if we the CLI `bundle` command would also let us write the accompanying source map to a file somewhere.

e.g. something like:

```
$ react-native bundle --include-sourcemap
```

... would write both `main.jsbundle` and `index.ios.map`.

Unless I'm mistaken (likely), it seems the only way for me to get the source map is to manually start the packager server, curl the bundle endpoint, write that to disk, then stop the server.

**Comment by dcramer** [comment]
@vjeux psst we want to launch some cool react-native stuff, is there a way we can help push this through?

**Comment by vjeux** [comment]
@martinbigio is this something you can help with?

**Comment by martinbigio** [comment]
Looks good, Thanks!

**Comment by martinbigio** [comment]
@reactjs-bot shipit

**Comment by benvinegar** [comment]
https://github.com/facebook/react-native/pull/3204

**Comment by benvinegar** [comment]
@martinbigio – Sorry, I wasn't referencing the PR correctly. Please take another look?
