### ISSUE TITLE
Could not find react-native-0.64.2.jar

### ISSUE THREAD

**Issue by cw-dos** [facebook/react-native#32022]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
When I try to build my project from Android Studio, I get the error `Could not find react-native-0.64.2.jar` for roughly 19 different packages.

`Execution failed for task ':react-native-vector-icons:compileDebugJavaWithJavac'.`

`Could not resolve all files for configuration ':react-native-vector-icons:debugCompileClasspath'.`

`Failed to transform react-native-0.64.2.jar (com.facebook.react:react-native:0.64.2) to match attributes {artifactType=android-classes-jar, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-api}.`

`Could not find react-native-0.64.2.jar (com.facebook.react:react-native:0.64.2).`

`node_modules/react-native/android/com/facebook/react/react-native/0.64.2/react-native-0.64.2.jar`

## React Native version:
`"react-native": "^0.64.2"`

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Simply build the project from Android Studio
2. The build used to work and now it does not

## Expected Results
The app to build on an Android device, connected or emulator.

## Snack, code example, screenshot, or link to a repository:

<img width="1860" alt="build" src="https://user-images.githubusercontent.com/45541155/129620354-48995ab9-9d2d-4557-8ead-369fca3f3317.png">

<img width="1833" alt="sync" src="https://user-images.githubusercontent.com/45541155/129620356-517399d2-9e09-4d20-83a1-d3f7a05d6206.png">

**Comment by cw-dos** [comment]
Workaround is to upgrade to RN -v 65.

**Comment by cortinico** [comment]
Closing as this is resolved

**Comment by cw-dos** [comment]
Update: The workaround I mentioned above to upgrade to RN -v 65 did not actually solve the issue.

The reason the upgrade appeared to work is because I followed the steps below in the process of trying to resolve the issue while simultaneously upgrading RN; which gave the impression that the new RN version resolved the issue.

If you come across `jar` or `jsc` errors in android when syncing or bundling try the following:

1. delete your node modules folder
2. clean the project from Android Studio
3. If on iOS `./gradlew clean` inside the Android folder in your project
4. Shut down Android Studio
5. npm install
6. Open Android Studio, sync and rebuild
