### ISSUE TITLE
Use of undeclared identifier 'YGPositionTypeStatic'

### ISSUE THREAD

**Issue by petermason** [facebook/react-native#32020]
https://github.com/facebook/react-native/blob/ecd6927b9aac5fe05256b6e9dfa16e10a4d89e5c/React/Base/RCTConvert.m#L1145

Currently has the following issue:

Use of undeclared identifier 'YGPositionTypeStatic'; did you mean 'YGPositionTypeRelative'?

**Comment by petermason** [comment]
Mistake, issue with local config!

**Comment by mkchetan25** [comment]
Hi,

How did u fix this? I'm facing the same.
