### ISSUE TITLE
"Could not get BatchedBridge, make sure your bundle is packaged correctly" since react-native 0.65 using Release schema

### ISSUE THREAD

**Issue by DennisSnijder** [facebook/react-native#32028]
## Description
Since upgrading to react-native version 0.65, whenever building and starting the app on IOS, I receive an error saying "Could not get BatchedBridge, make sure your bundle is packaged correctly".  Whenever running on the Debug schema, the app successfully starts. 

## React Native version:
```
System:
    OS: macOS 11.4
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Memory: 60.82 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.19.0 - ~/.nvm/versions/node/v12.19.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v12.19.0/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v12.19.0/bin/npm
    Watchman: 2021.06.07.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.2.2 4.2.2
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 14.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.2 => 17.0.2 
    react-native: ^0.65.0 => 0.65.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Upgrade to react-native 0.65
2. Build IOS app with Release schema
3. Start the app and wait for it to crash on startup

## Notes
- Hermes is enabled in the Podfile

**Comment by mustafauyysl** [comment]
Same issue +

**Comment by irmakcosarsahna** [comment]
Same problem

**Comment by alexanderoskin** [comment]
Same problem +

But the app successfully starts with :hermes_enabled => false in the Podfile

**Comment by SkySails** [comment]
Was just going to report this as well, can confirm what @alexanderoskin already stated. Turning off hermes brings the app back to a working state.

**Comment by DennisSnijder** [comment]
> Same problem +
> 
> But the app successfully starts with :hermes_enabled => false in the Podfile. With enabled Hermes release schema crashes.

Sweet! That worked! However... I want to use Hermes 😢

**Comment by iMJumpmxn** [comment]
Same problem

**Comment by truongngodang** [comment]
same problem

**Comment by lukasa1993** [comment]
any love for use ? this makes this basically unable this is not only from xCode run same thing happens when you archive and which makes impossible to rlease it

**Comment by captainDuckay** [comment]
Same

**Comment by hinciler** [comment]
@irmakcosarsahna @mustafauyysl did you fix the problem.

**Comment by lukasa1993** [comment]
one observation is when i create `npx react-native init AwesomeProject` it doesn't have same problem so its either some library problem or some hidden config which i cant find yet

**Comment by captainDuckay** [comment]
Another observation
I realised my ios device and macbook was on different network subnets, and the ios device wasn't able to reach metro. 
Once i made sure they could reach each other, the problem went away. 
So it might be something to do with the initial load from xcode, that isn't bundled correctly? And once the ios device grabs a hold on Metro, then it grabs the newest correctly bundled code?

**Comment by lukasa1993** [comment]
> Another observation
> I realised my ios device and macbook was on different network subnets, and the ios device wasn't able to reach metro.
> Once i made sure they could reach each other, the problem went away.
> So it might be something to do with the initial load from xcode, that isn't bundled correctly? And once the ios device grabs a hold on Metro, then it grabs the newest correctly bundled code?

that doesn't explain why it doesn't bundle when built with archive from xcode

**Comment by raeez** [comment]
Hit the same error as OP, but after upgrading react-native-reanimated to version `2.3.0-alpha.2` we found the error went away, in lieu of a new one

```
2021-08-20 08:28:02.407342-0400 Persona[649:30893] [javascript] TypeError: Cannot read property 'Constants' of undefined, js engine: hermes
2021-08-20 08:28:02.407942-0400 Persona[649:30893] [javascript] Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect. 
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes
2021-08-20 08:28:02.407988-0400 Persona[649:30880] [native] Unhandled JS Exception: TypeError: Cannot read property 'Constants' of undefined, js engine: hermes
2021-08-20 08:28:02.462333-0400 Persona[649:30880] *** Terminating app due to uncaught exception 'RCTFatalException: Unhandled JS Exception: TypeError: Cannot read property 'Constants' of undefined, js engine: hermes', reason: 'Unhandled JS Exception: TypeError: Cannot read property 'Constants' of undefined, js engine: hermes, stack:
anonymous@244588:28
loadModuleImplementation@183:13
guardedLoadModule@104:37
metroRequire@41:91
anonymous@244360:32
loadModuleImplementation@183:13
guardedLoadModule@104:37
metroRequire@41:91
anonymous@244343:32
loadModuleImplementation@183:13
guardedLoadModule@104:37
metroRequire@41:91
anonymous@244307:24
loadModuleImplementation@183:13
guardedLoadModule@104:37
metroRequire@41:91
anonymous@144288:47
loadModuleImplementation@183:13
guardedLoadModule@104:37
metroRequire@41:91
anonymous@88896:62
loadModuleImplementation@183:13
guardedLoadModule@104:37
metroRequire@41:91
anonymous@88217:62
loadModuleImplementation@183:13
guardedLoadModule@104:37
metroRequire@41:91
anonymous@87327:57
loadModuleImplementation@183:13
guardedLoadModule@104:37
metroRequire@41:91
anonymous@66578:55
loadModuleImplementation@183:13
guardedLoadModule@104:37
metroRequire@41:91
anonymous@44380:57
loadModuleImplementation@183:13
guardedLoadModule@104:37
metroRequire@41:91
anonymous@44283:56
loadModuleImplementation@183:13
guardedLoadModule@104:37
metroRequire@41:91
anonymous@800:47
loadModuleImplementation@183:13
guardedLoadModule@96:46
metroRequire@41:91
global@265250:3
'
*** First throw call stack:
(0x19ae0a5b4 0x1af8897a8 0x100d9d7c0 0x100e1d5f0 0x100e1df54 0x19ae0f874 0x19ace2ba4 0x19ace31a8 0x100dcfd08 0x100dd22a4 0x100dd1ec8 0x19a9f5a54 0x19a9f77ec 0x19a9fefd4 0x19a9ffbd0 0x19aa0a48c 0x1e68267a4 0x1e682d74c)
libc++abi: terminating with uncaught exception of type NSException

```

Still working on understanding what's going on here; unclear if it's an issue with reanimated, or some other lib that's only uncovered after the upgrade

**Comment by truongngodang** [comment]
I investigated, This problem is caused by react-native-reanimated@2.2.0

**Comment by lukasa1993** [comment]
> I investigated, This problem is caused by react-native-reanimated@2.2.0

any work around ?

**Comment by DennisSnijder** [comment]
> Upgraded react-native-reanimated from 2.2.0 to 2.3.0-alpha.2 worked for me

Can confirm this works for me, closing the issue since there's an issue live @ react-native-reanimated about this issue.
https://github.com/software-mansion/react-native-reanimated/issues/2313

**Comment by Victoriaidunorba** [comment]
React-native reanimated just got upgraded about 2 weeks ago to 2.9.1.
I had this exact problem while using 2.2 
so you should do this: npm install react-native-reanimated@2.9.1

**Comment by TomNes94** [comment]
I still get this issue, even though we do not depend on react-native-reanimated. Disabling hermes works, but that is not the ideal situation. RN version 0.68.1.

**Comment by leofelix077** [comment]
@TomNes94 I could not yet find out where the issue is originating from, but by setting all libraries to static, I was able to have hermes enabled. I just saw that the issue was originating from dylib. we do have some older libraries that might be causing the issue

`use_frameworks! :linkage => :static`

```
installer.pod_targets.each do |pod|
        def pod.build_type;
          # Uncomment the line corresponding to your CocoaPods version
          Pod::BuildType.static_library # >= 1.9
          # Pod::Target::BuildType.static_library # < 1.9
      end
    end
```

**Comment by nickdebaise** [comment]
@TomNes94 Have you found a solution to this?
