### ISSUE TITLE
Unable to create new project using npx command on 0.65.0

### ISSUE THREAD

**Issue by kuldeepworkid** [facebook/react-native#32034]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Im creating fresh project using command `npx react-native init MyTestApp`  after 0.65.0 stable release. 
But i'm getting npm install error. See the below image.
<img width="614" alt="Screenshot 2021-08-18 at 12 56 15 PM" src="https://user-images.githubusercontent.com/64519426/129858120-2fc8df93-0d93-4ce8-b3f2-d26595978dea.png">

But when i'm running `npx react-native init AwesomeProject --version 0.64.2` , i'm not getting any error and the project created successfully.

## React Native version:
System:
    OS: macOS 11.5.2
    CPU: (8) arm64 Apple M1
    Memory: 141.88 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.4.0 - /opt/homebrew/bin/node
    Yarn: Not Found
    npm: 7.18.1 - /opt/homebrew/bin/npm
    Watchman: 2021.06.07.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.3
      System Images: android-25 | Google APIs ARM 64 v8a, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7583922
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_302 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Run `npx react-native init MyTestApp` on your terminal.

## Expected Results
Fresh new project should be successfully created with latest verison of react-native(0.65.0)

**Comment by kelset** [comment]
I just tried and it works fine on my machine - I wonder if it's because I'm still on npm v6? 🤔

**Comment by smartameer** [comment]
Tried the same, not failing but its giving old version

`npx react-native init AwesomeProject` is giving package.json having `react-native` version as `0.64.1`
`npx react-native init AwesomeProject --version 0.65.0` is giving package.json having `react-native` version as `0.64.1`

**Comment by efefurkankarakaya** [comment]
Same. I solved that problem with manually install dependencies with --legacy-peer param.

**Comment by kuldeepworkid** [comment]
> Same. I solved that problem with manually installing dependencies with `--legacy-peer-deps` param.

Can you please share the steps, how to resolve it.

**Comment by efefurkankarakaya** [comment]
> > Same. I solved that problem with manually installing dependencies with `--legacy-peer-deps` param.
> 
> Can you please share the steps, how to resolve it.

Of course.

1) `npx react-native init MyProject`
2) (Get the error and let it break installation)
3) cd MyProject
4) `npm install --legacy-peer-deps`
5) `npx react-native start`
6) `npx react-native run-android`

and it's done.

**Comment by kuldeepworkid** [comment]
> 4\. npm install --legacy-peer-deps

Thank you @efefurkankarakaya now i'm able to create new project with the steps you have mentioned.
Their is one more issue that my .xcworkspace is not generating now in 0.65.0

**Comment by kuldeepworkid** [comment]
Thank you @efefurkankarakaya now i'm able to create new project with the steps you have mentioned.
Their is one more issue that my .xcworkspace is not generating automatically now in 0.65.0. I have to generate it manually.

**Comment by efefurkankarakaya** [comment]
> Thank you @efefurkankarakaya now i'm able to create new project with the steps you have mentioned.
> Their is one more issue that my .xcworkspace is not generating automatically now in 0.65.0. I have to generate it manually.

You're welcome.
