### ISSUE TITLE
React native 0.64.2 Can not support Android Studio 2020.3.1

### ISSUE THREAD

**Issue by shrenikTrukky** [facebook/react-native#32039]
I upgrade my android studio and my android build got failed.

A problem occurred evaluating project ':app'.
> Could not get unknown property 'compile' for configuration container of type org.gradle.api.internal.artifacts.configurations.DefaultConfigurationContainer.

**Comment by cortinico** [comment]
Closing as this has already been addressed in #32030 :+1:
