### ISSUE TITLE
React Native | Android Studio

### ISSUE THREAD

**Issue by vickkeshri** [facebook/react-native#32043]
I have upgraded my android studio to arctic fox and after that i am unable to run project. 

## Description
When I try running the application from terminal it got build, but when I open the application, it got crash without any error logs.

## React Native version:
System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
    Memory: 22.54 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.6.1 - /usr/local/bin/node
    Yarn: Not Found
    npm: 7.20.3 - /usr/local/bin/npm
    Watchman: 2021.06.07.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK: Not Found
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7583922
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Java: 16.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.2 => 0.64.2 

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Upgrade android studio to Arctic Fox
2. Create react native project
3. Write native modules package and class in android studio
4. From react native call native module package on press of button or Touchable opacity
5. Build and run the project either from react native terminal or android studio
6. Application with build, when you open - it will crash

## Expected Results
Application should open and should behaves in the same fashion

**Comment by FadiAboMsalam** [comment]
I have the same issue after upgrading my app from RN 064.2 to 0.65 
iOS is working fine but on android, i had to upgrade android studio to Arctic Fox | 2020.3.1 Patch 1 

I think this may be related to using react-native-config  since the error is as follows 

```
* What went wrong:
Execution failed for task ':app:generateDebugBuildConfig'.
> The value for property 'buildConfigFields' is final and cannot be changed any further.

BUILD FAILED in 6s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
```

this [issue](https://github.com/luggit/react-native-config/issues/567) on react-native-config might be related

**Comment by octsiri** [comment]
@FadiAboMsalam someone has suggested a [PR](https://github.com/luggit/react-native-config/pull/609) to fix this issue. He removes the `task.doFirst()` on `dotenv.gradle`. Take a look a second for detail

**Comment by cortinico** [comment]
> I think this may be related to using react-native-config since the error is as follows

@vickkeshri Can you confirm that you're actually using `react-native-config` in your project? If so we can close this issue as it's unrelated to react-native.
