### ISSUE TITLE
MapView Android exists? No ViewManager defined for class RCTMap

### ISSUE THREAD

**Issue by subtleGradient** [facebook/react-native#3205]
I'm using version 0.11.0 on replay.org if that matters.
I couldn't find any reference to Android support or non-support for MapView.

**Comment by christopherdro** [comment]
@subtleGradient Did you mean rnplay.org?

Doesn't look like MapView is currently supported with Android.

**Comment by adaojunior** [comment]
Yeah same message here, I'm using 0.12-rc.
```
No ViewManager defined for class RCTMap
```

**Comment by mkonicek** [comment]
`<MapView>` hasn't been open sourced on Android yet but we're working on it: https://facebook.github.io/react-native/docs/known-issues.html

**Comment by Pajn** [comment]
MapView isn't mentioned on that page, will it come anyway or is it iOS only forever?

**Comment by ide** [comment]
@pajn "Maps" is under the View section on that page.

**Comment by Pajn** [comment]
Oh, I'm sorry. I visually searched for MapView so Maps was too short for me to notice.
