### ISSUE TITLE
Transform rotate style not resulting in pure rotation, it is also displacing with rotation(follows circular path)

### ISSUE THREAD

**Issue by vaibhavs2** [facebook/react-native#32058]
## Description

`const rotate = () => {
    rotateAnim.setValue(0);
    Animated.timing(rotateAnim, {
      toValue: 1,
      duration: 5000,
      useNativeDriver: true,
      easing: Easing.linear,
    }).start(() => {});
  };`

`  <AnimatedIcon
          style={{
            transform: [
              {
                rotate: rotateAnim.interpolate({
                  inputRange: [0, 1],
                  outputRange: ['0deg', '360deg'],
                }),
              },
            ],
          }}
          name="refresh-circle"
          size={50}
          color="white"
        />`

I am using Animated API from react native to animate an Icon, used react-native-vector-icons library for the Icon.
Created a animated component ` const AnimatedIcon = Animated.createAnimatedComponent(Ionicons);`  and I need to rotate this AnimatedIcon on an event. I am expecting pure rotation without any displacement, AnimatedIcon component is not rotating on its fixed axis.

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.Please refer to Snack example given below.

## Expected Results
AnimatedIcon should rotate on its fixed axis without any displacement.

## Snack, code example, screenshot, or link to a repository:
[Here is the repro on snack.expo.dev](https://snack.expo.dev/@vaibhavs/rotation)

#### This is when style={[...aboveStyle_in_AnimatedIcon, {width:20, height:20}]}
![rotating](https://user-images.githubusercontent.com/31806059/130315041-2f12cbc0-4073-4d57-85ac-afb22a0bebae.gif)
#### Without any style constraints
![wrongrotation](https://user-images.githubusercontent.com/31806059/130315047-c421c80a-6005-4a73-a5b1-d5bc3c530fcb.gif)

**Comment by yousseftarekkh** [comment]
@vaibhavs2 There are two potential fixes to the issue you submitted.
Both of them follow the same logic to solve the orientation of your component and render a more centered one.
1. wrap the `AnimatedIcon` inside a 
     ```tsx
     <View style={{ alignItems: 'center' }}>
       {/* your animated component */}
     </View >
     ```
2. add an `alignSelf: 'center'` to the `style` prop of your `AnimatedIcon`

Both of these will solve the circular path that is applied to your icon.

**Comment by vaibhavs2** [comment]
@yousseftarekkh!
The solution you mentioned didn't work, It surely is not following a circular path as before because I think after applying the style you mentioned, the component doesn't have enough space to revolve around but still, it is slightly displacing.

![displace](https://user-images.githubusercontent.com/31806059/130365439-a3ed803c-aec1-4837-a77b-3fd107592fc3.gif)
![displace](https://user-images.githubusercontent.com/31806059/130366223-5ab13eb9-ce3e-4287-88ce-23acc3b322a6.gif)
