### ISSUE TITLE
React Native build failed on react-navigation core from ResourceSavingSceneView

### ISSUE THREAD

**Issue by sk92129** [facebook/react-native#32057]
## Description
My react native project was building file for the android and ios.  But after Aug 13, something broke inside of the node_modules.

error Unable to resolve module @react-navigation/core from /Users/sean/git/pipeline/develop/myapp-mobile/node_modules/@react-navigation/native/lib/module/ResourceSavingSceneView.js: @react-navigation/core could not be found within the project or in these directories:

5 | import * as React from 'react';
   6 | import { Platform, StyleSheet, View } from 'react-native';
>  7 | import { SceneView } from '@react-navigation/core';
     |                            ^
   8 | const FAR_FAR_AWAY = 3000; // this should be big enough to move the whole view out of its container
   9 |
  10 | class ResourceSavingSceneView extends React.PureComponent {

## React Native version:
Run `react-native info` in your terminal and copy the results here.
info Fetching system and libraries information...
(node:96345) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
System:
    OS: macOS 11.3.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 1.24 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.6.2 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.20.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 27, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3
      System Images: android-24 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7486908
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.2 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. rm -rf node_modules
2. rm -rf package-lock.json
3. npm install --force
4. npx jetifier
5. cd android
6. ./gradlew app:assembleRelease

## Expected Results
Normally the app-release.apk is generated.

## Snack, code example, screenshot, or link to a repository:

error Unable to resolve module @react-navigation/core from /Users/sean/git/pipeline/develop/myapp-mobile/node_modules/@react-navigation/native/lib/module/ResourceSavingSceneView.js: @react-navigation/core could not be found within the project or in these directories:
Error: Unable to resolve module @react-navigation/core from /Users/sean/git/pipeline/develop/myapp-mobile/node_modules/@react-navigation/native/lib/module/ResourceSavingSceneView.js: @react-navigation/core could not be found within the project or in these directories:
  node_modules/@react-navigation/native/node_modules
  node_modules/@react-navigation/native/node_modules
  node_modules

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
  node_modules

 2. Delete node_modules and run yarn install
If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
 4. Remove the cache: rm -rf /tmp/metro-*
   5 | import * as React from 'react';
   6 | import { Platform, StyleSheet, View } from 'react-native';
>  7 | import { SceneView } from '@react-navigation/core';
     |                            ^
   8 | const FAR_FAR_AWAY = 3000; // this should be big enough to move the whole view out of its container
   9 |
  10 | class ResourceSavingSceneView extends React.PureComponent {
    at ModuleResolver.resolveDependency (/Users/sean/git/pipeline/develop/myapp-mobile/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:234:15)
    at DependencyGraph.resolveDependency (/Users/sean/git/pipeline/develop/myapp-mobile/node_modules/metro/src/node-haste/DependencyGraph.js:413:43)
    at Object.resolve (/Users/sean/git/pipeline/develop/myapp-mobile/node_modules/metro/src/lib/transformHelpers.js:317:42)
    at resolve (/Users/sean/git/pipeline/develop/myapp-mobile/node_modules/metro/src/DeltaBundler/traverseDependencies.js:629:33)
    at /Users/sean/git/pipeline/develop/myapp-mobile/node_modules/metro/src/DeltaBundler/traverseDependencies.js:645:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (/Users/sean/git/pipeline/develop/myapp-mobile/node_modules/metro/src/DeltaBundler/traverseDependencies.js:644:33)
    at /Users/sean/git/pipeline/develop/myapp-mobile/node_modules/metro/src/DeltaBundler/traverseDependencies.js:329:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/sean/git/pipeline/develop/myapp-mobile/node_modules/metro/src/DeltaBundler/traverseDependencies.js:137:24)
   5 | import * as React from 'react';
   6 | import { Platform, StyleSheet, View } from 'react-native';
>  7 | import { SceneView } from '@react-navigation/core';
     |                            ^
info Run CLI with --verbose flag for more details.
   8 | const FAR_FAR_AWAY = 3000; // this should be big enough to move the whole view out of its container
   9 |
  10 | class ResourceSavingSceneView extends React.PureComponent {.

> Task :app:bundleReleaseJsAndAssets FAILED

**Comment by abarisic86** [comment]
@sk92129 any resolution to this?
