### ISSUE TITLE
new NativeEventEmitter() was called with a non-null argument without the required `addListener` method.

### ISSUE THREAD

**Issue by projectnetworld** [facebook/react-native#32051]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
when I open the app after upgraded to RN 0.65 I get 2 warnings 

## React Native version:
0.65

## Snack, code example, screenshot, or link to a repository:

 WARN  `new NativeEventEmitter` was called with a non-null argument without the required `addListener` method.
 WARN  `new NativeEventEmitter` was called with a non-null argument without the required `removeListeners` method.
 LOG  Reactotron Configured
 LOG  Running "PnwApp" with {"rootTag":21}
 LOG  Skipping setJSExceptionHandler: Reason: In DEV mode and allowedInDevMode = false
 WARN  `new NativeEventEmitter` was called with a non-null argument without the required `addListener` method.
    at PageSplashScreen 
    at RCTView
    at View
    at RootNavigation 
    at EnsureSingleNavigator 
    at BaseNavigationContainer 
    at ThemeProvider 
    at NavigationContainer 
    at RCTView
    at View
    at RCTView
    at View
    at MenuProvider 
    at RCTView
    at View
    at SafeAreaView 
    at Provider 
    at App 
    at RCTView
    at View
    at RCTView
    at View
    at AppContainer 
    at PnwApp 
 WARN  `new NativeEventEmitter` was called with a non-null argument without the required `removeListeners` method.
    at PageSplashScreen 
    at RCTView
    at View
    at RootNavigation 
    at EnsureSingleNavigator 
    at BaseNavigationContainer 
    at ThemeProvider 
    at NavigationContainer 
    at RCTView
    at View
    at RCTView
    at View
    at MenuProvider 
    at RCTView
    at View
    at SafeAreaView 
    at Provider 
    at App 
    at RCTView
    at View
    at RCTView
    at View
    at AppContainer 
    at PnwApp

**Comment by mikehardy** [comment]
So this should be in the react-navigation repo, right? But even then it is probably from reanimated, it's probably this: https://github.com/software-mansion/react-native-reanimated/issues/2297

For future people - this is not a react-native **issue**. This is new react-native behavior **exposing an issue in a module**

Example PR to fix, in a native module: https://github.com/invertase/react-native-firebase/pull/5616

**Comment by elashpear** [comment]
Could the docs be updated to include this? I was implementing a brand new android module and couldn't figure out why I was getting this error because it wasn't mentioned at all in https://reactnative.dev/docs/native-modules-android#sending-events-to-javascript

**Comment by projectnetworld** [comment]
> So this should be in the react-navigation repo, right? But even then it is probably from reanimated, it's probably this: [software-mansion/react-native-reanimated#2297](https://github.com/software-mansion/react-native-reanimated/issues/2297)
> 
> For future people - this is not a react-native **issue**. This is new react-native behavior **exposing an issue in a module**
> 
> Example PR to fix, in a native module: [invertase/react-native-firebase#5616](https://github.com/invertase/react-native-firebase/pull/5616)

yes indeed true! thx for the link :)

**Comment by pke** [comment]
I have to agree with @elashpear here, the docs should be updated when such a warning is introduced.

Furthermore it would be really nice if RN warnings/errors would give more context in general. I often see them and all they provide is a (mangled) stack trace often not really related to the problem (ie. rendering `0` without `Text` wrapping caused by `||` conditional rendering).

In that case it would be really nice to print out the **name** of the `nativeModule` in question. But it seems `nativeModule` does not contain such information. Where could the name/module be looked up to improve the error reporting?

**Comment by mikehardy** [comment]
All the native modules actually have names internally, it's how they register with the react-native JS/native bridge (by name) into the NativeModules array that's available on the JS side for lookup by name
