### ISSUE TITLE
SectionList Sticky Headers don't take into account the offset of the iOS translucent header

### ISSUE THREAD

**Issue by pouyarezvani** [facebook/react-native#32063]
## Description
When using [React-Native-Screeens](https://github.com/software-mansion/react-native-screens) navigation library and we pass the option of `headerTranslucent={true}` in the `ScreenOptions` of the `StackNavigator`, it causes the `sectionList` Sticky headers to not stick to the header anymore. They start to go under the navigation header as a result. 

It was recommended in the `react-native-screens` GitHub by @WoLewicki in this [comment](https://github.com/software-mansion/react-native-screens/issues/542#issuecomment-671835098) that the issue is with `scrollViewStickyHeaders` not being able to take into account the offset of the iOS translucent header when calculating the start of the "stickiness"

Here is a video of the problem as also linked in the expo snack below : 

https://user-images.githubusercontent.com/32917154/130368617-28a11d9c-90ad-4747-940b-76cbb5365652.mp4

[snack of the issue](https://snack.expo.dev/@invoiss/sectionlist-with-translucent-header)

## React Native version:
This issue is reproducible in the Expo SDK 42 Which is using react native version 0.63.  

## Steps To Reproduce

1. Install `react-native-screens`, 
2. set up a stack navigator and set `headerTranslucent={true}`
3. import `sectionList` and set the sticky headers to true. 
4. you will notice that when the stack navigator has a translucent header to be true, the sticky headers start going under the header. 

## Expected Results
The expected behavior is that the sticky headers should be sticking normally just below the stack navigator header even when the translucent header is set to be true. 
You can see this feature in the iOS Safari app/Contacts App. Where when you are searching for something, the header is translucent and the sticky headers 
Here is a video of the expected behavior as demonstrated in the iOS safari search tab, as you can see the header is translucent and the sticky headers stick to the right offset : 

https://user-images.githubusercontent.com/32917154/130368602-4f08faa7-ce87-453c-a67a-fb36b55c6bd4.mov

## Snack, code example, screenshot, or link to a repository:
[Here is a snack that can reproduce the Issue](https://snack.expo.dev/@invoiss/sectionlist-with-translucent-header)

It would be awesome, to see if there is any way we can find a solution to this issue, or if anyone has done that on their own already. 
Thanks.

**Comment by ArekChr** [comment]
bump
