### ISSUE TITLE
setNativeProps does not work with text property on Text component in RN 0.65.0

### ISSUE THREAD

**Issue by npjoge** [facebook/react-native#32067]
### Environment
React Native Environment Info:
    System:
      OS: macOS 10.14.1
      CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
      Memory: 123.34 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.11.3 - /usr/local/bin/node
      Yarn: 1.10.1 - ~/.yarn/bin/yarn
      npm: 5.6.0 - ~/n/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 24, 26, 27, 28, 29, 30
        Build Tools: 23.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.0, 28.0.0, 28.0.1, 28.0.2, 28.0.3
        System Images: android-27 | Google Play Intel x86 Atom
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 17.0.2
      react-native: 0.65.0
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      generator-module-react-native: 0.0.2
      react-native-cli: 2.0.1
      react-native-create-bridge: 1.2.1
      react-native-create-library: 3.1.2
      react-native-git-upgrade: 0.2.7

### Description
setNativeProps does not work with text property on Text component in 0.65.0

**Comment by npjoge** [comment]
@tychota #22855 Your solutions not working in 0.65.0, because structure of Text.js in Library has change.

**Comment by QureshiFaizan** [comment]
@tychota even I am facing the same issue. Any help will be appreciated

**Comment by tradebulls** [comment]
+1
