### ISSUE TITLE
React Native run ios simulator failed (M1)

### ISSUE THREAD

**Issue by ksielyov** [facebook/react-native#32069]
## React Native version:
System:
    OS: macOS 11.5.2
    CPU: (8) arm64 Apple M1
    Memory: 130.20 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.7.0 - /opt/homebrew/bin/node
    Yarn: Not Found
    npm: 7.20.3 - /opt/homebrew/bin/npm
    Watchman: 2021.08.02.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.10.2 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.65.1 => 0.65.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. npx react-native init anyapp
2. npx react-native run-ios

## Expected Results
App successfully ran on simulator

## Error

CompileC /Users/mikhailkiselyov/Library/Developer/Xcode/DerivedData/untitled-bbuurbgocmoxxkglqycxlaquymfk/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/glog.build/Objects-normal/arm64/vlog_is_on.o /Users/mikhailkiselyov/WebstormProjects/untitled/ios/Pods/glog/src/vlog_is_on.cc normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'glog' from project 'Pods')
    cd /Users/mikhailkiselyov/WebstormProjects/untitled/ios/Pods
    export LANG\=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c++ -target arm64-apple-ios11.0-simulator -fmessage-length\=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -std\=gnu++14 -stdlib\=libc++ -fmodules -fmodules-cache-path\=/Users/mikhailkiselyov/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -fmodules-prune-interval\=86400 -fmodules-prune-after\=345600 -fbuild-session-file\=/Users/mikhailkiselyov/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror\=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror\=return-type -Wdocumentation -Wunreachable-code -Werror\=deprecated-objc-isa-usage -Werror\=objc-root-class -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wno-newline-eof -Wno-c++11-extensions -DPOD_CONFIGURATION_DEBUG\=1 -DDEBUG\=1 -DCOCOAPODS\=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk -fstrict-aliasing -Wdeprecated-declarations -Winvalid-offsetof -g -Wno-sign-conversion -Winfinite-recursion -Wmove -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wrange-loop-analysis -Wno-semicolon-before-method-body -Wunguarded-availability -index-store-path /Users/mikhailkiselyov/Library/Developer/Xcode/DerivedData/untitled-bbuurbgocmoxxkglqycxlaquymfk/Index/DataStore -I/Users/mikhailkiselyov/Library/Developer/Xcode/DerivedData/untitled-bbuurbgocmoxxkglqycxlaquymfk/Build/Products/Debug-iphonesimulator/glog/include -I/Users/mikhailkiselyov/WebstormProjects/untitled/ios/Pods/Headers/Private -I/Users/mikhailkiselyov/WebstormProjects/untitled/ios/Pods/Headers/Private/glog -I/Users/mikhailkiselyov/WebstormProjects/untitled/ios/Pods/Headers/Public -I/Users/mikhailkiselyov/WebstormProjects/untitled/ios/Pods/Headers/Public/glog -I/Users/mikhailkiselyov/WebstormProjects/untitled/ios/Pods/glog/src -I/Users/mikhailkiselyov/Library/Developer/Xcode/DerivedData/untitled-bbuurbgocmoxxkglqycxlaquymfk/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/glog.build/DerivedSources-normal/arm64 -I/Users/mikhailkiselyov/Library/Developer/Xcode/DerivedData/untitled-bbuurbgocmoxxkglqycxlaquymfk/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/glog.build/DerivedSources/arm64 -I/Users/mikhailkiselyov/Library/Developer/Xcode/DerivedData/untitled-bbuurbgocmoxxkglqycxlaquymfk/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/glog.build/DerivedSources -F/Users/mikhailkiselyov/Library/Developer/Xcode/DerivedData/untitled-bbuurbgocmoxxkglqycxlaquymfk/Build/Products/Debug-iphonesimulator/glog -Wno-shorten-64-to-32 -include /Users/mikhailkiselyov/WebstormProjects/untitled/ios/Pods/Target\ Support\ Files/glog/glog-prefix.pch -MMD -MT dependencies -MF /Users/mikhailkiselyov/Library/Developer/Xcode/DerivedData/untitled-bbuurbgocmoxxkglqycxlaquymfk/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/glog.build/Objects-normal/arm64/vlog_is_on.d --serialize-diagnostics /Users/mikhailkiselyov/Library/Developer/Xcode/DerivedData/untitled-bbuurbgocmoxxkglqycxlaquymfk/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/glog.build/Objects-normal/arm64/vlog_is_on.dia -c /Users/mikhailkiselyov/WebstormProjects/untitled/ios/Pods/glog/src/vlog_is_on.cc -o /Users/mikhailkiselyov/Library/Developer/Xcode/DerivedData/untitled-bbuurbgocmoxxkglqycxlaquymfk/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/glog.build/Objects-normal/arm64/vlog_is_on.o

CompileC /Users/mikhailkiselyov/Library/Developer/Xcode/DerivedData/untitled-bbuurbgocmoxxkglqycxlaquymfk/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/glog.build/Objects-normal/arm64/utilities.o /Users/mikhailkiselyov/WebstormProjects/untitled/ios/Pods/glog/src/utilities.cc normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'glog' from project 'Pods')
    cd /Users/mikhailkiselyov/WebstormProjects/untitled/ios/Pods
    export LANG\=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c++ -target arm64-apple-ios11.0-simulator -fmessage-length\=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -std\=gnu++14 -stdlib\=libc++ -fmodules -fmodules-cache-path\=/Users/mikhailkiselyov/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -fmodules-prune-interval\=86400 -fmodules-prune-after\=345600 -fbuild-session-file\=/Users/mikhailkiselyov/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror\=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror\=return-type -Wdocumentation -Wunreachable-code -Werror\=deprecated-objc-isa-usage -Werror\=objc-root-class -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wno-newline-eof -Wno-c++11-extensions -DPOD_CONFIGURATION_DEBUG\=1 -DDEBUG\=1 -DCOCOAPODS\=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk -fstrict-aliasing -Wdeprecated-declarations -Winvalid-offsetof -g -Wno-sign-conversion -Winfinite-recursion -Wmove -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wrange-loop-analysis -Wno-semicolon-before-method-body -Wunguarded-availability -index-store-path /Users/mikhailkiselyov/Library/Developer/Xcode/DerivedData/untitled-bbuurbgocmoxxkglqycxlaquymfk/Index/DataStore -I/Users/mikhailkiselyov/Library/Developer/Xcode/DerivedData/untitled-bbuurbgocmoxxkglqycxlaquymfk/Build/Products/Debug-iphonesimulator/glog/include -I/Users/mikhailkiselyov/WebstormProjects/untitled/ios/Pods/Headers/Private -I/Users/mikhailkiselyov/WebstormProjects/untitled/ios/Pods/Headers/Private/glog -I/Users/mikhailkiselyov/WebstormProjects/untitled/ios/Pods/Headers/Public -I/Users/mikhailkiselyov/WebstormProjects/untitled/ios/Pods/Headers/Public/glog -I/Users/mikhailkiselyov/WebstormProjects/untitled/ios/Pods/glog/src -I/Users/mikhailkiselyov/Library/Developer/Xcode/DerivedData/untitled-bbuurbgocmoxxkglqycxlaquymfk/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/glog.build/DerivedSources-normal/arm64 -I/Users/mikhailkiselyov/Library/Developer/Xcode/DerivedData/untitled-bbuurbgocmoxxkglqycxlaquymfk/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/glog.build/DerivedSources/arm64 -I/Users/mikhailkiselyov/Library/Developer/Xcode/DerivedData/untitled-bbuurbgocmoxxkglqycxlaquymfk/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/glog.build/DerivedSources -F/Users/mikhailkiselyov/Library/Developer/Xcode/DerivedData/untitled-bbuurbgocmoxxkglqycxlaquymfk/Build/Products/Debug-iphonesimulator/glog -Wno-shorten-64-to-32 -include /Users/mikhailkiselyov/WebstormProjects/untitled/ios/Pods/Target\ Support\ Files/glog/glog-prefix.pch -MMD -MT dependencies -MF /Users/mikhailkiselyov/Library/Developer/Xcode/DerivedData/untitled-bbuurbgocmoxxkglqycxlaquymfk/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/glog.build/Objects-normal/arm64/utilities.d --serialize-diagnostics /Users/mikhailkiselyov/Library/Developer/Xcode/DerivedData/untitled-bbuurbgocmoxxkglqycxlaquymfk/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/glog.build/Objects-normal/arm64/utilities.dia -c /Users/mikhailkiselyov/WebstormProjects/untitled/ios/Pods/glog/src/utilities.cc -o /Users/mikhailkiselyov/Library/Developer/Xcode/DerivedData/untitled-bbuurbgocmoxxkglqycxlaquymfk/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/glog.build/Objects-normal/arm64/utilities.o
/Users/mikhailkiselyov/WebstormProjects/untitled/ios/Pods/glog/src/utilities.cc:254:17: warning: 'syscall' is deprecated: first deprecated in iOS 10.0 - syscall(2) is unsupported; please switch to a supported interface. For SYS_kdebug_trace use kdebug_signpost(). [-Wdeprecated-declarations]
    pid_t tid = syscall(__NR_gettid);
                ^
In file included from /Users/mikhailkiselyov/WebstormProjects/untitled/ios/Pods/glog/src/utilities.cc:32:
In file included from /Users/mikhailkiselyov/WebstormProjects/untitled/ios/Pods/glog/src/utilities.h:82:
In file included from /Users/mikhailkiselyov/WebstormProjects/untitled/ios/Pods/Headers/Private/glog/glog/logging.h:47:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/usr/include/unistd.h:742:6: note: 'syscall' has been explicitly marked deprecated here
int      syscall(int, ...);
         ^
1 warning generated.

CompileC /Users/mikhailkiselyov/Library/Developer/Xcode/DerivedData/untitled-bbuurbgocmoxxkglqycxlaquymfk/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/glog.build/Objects-normal/arm64/symbolize.o /Users/mikhailkiselyov/WebstormProjects/untitled/ios/Pods/glog/src/symbolize.cc normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'glog' from project 'Pods')
    cd /Users/mikhailkiselyov/WebstormProjects/untitled/ios/Pods
    export LANG\=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c++ -target arm64-apple-ios11.0-simulator -fmessage-length\=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -std\=gnu++14 -stdlib\=libc++ -fmodules -fmodules-cache-path\=/Users/mikhailkiselyov/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -fmodules-prune-interval\=86400 -fmodules-prune-after\=345600 -fbuild-session-file\=/Users/mikhailkiselyov/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror\=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror\=return-type -Wdocumentation -Wunreachable-code -Werror\=deprecated-objc-isa-usage -Werror\=objc-root-class -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wno-newline-eof -Wno-c++11-extensions -DPOD_CONFIGURATION_DEBUG\=1 -DDEBUG\=1 -DCOCOAPODS\=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk -fstrict-aliasing -Wdeprecated-declarations -Winvalid-offsetof -g -Wno-sign-conversion -Winfinite-recursion -Wmove -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wrange-loop-analysis -Wno-semicolon-before-method-body -Wunguarded-availability -index-store-path /Users/mikhailkiselyov/Library/Developer/Xcode/DerivedData/untitled-bbuurbgocmoxxkglqycxlaquymfk/Index/DataStore -I/Users/mikhailkiselyov/Library/Developer/Xcode/DerivedData/untitled-bbuurbgocmoxxkglqycxlaquymfk/Build/Products/Debug-iphonesimulator/glog/include -I/Users/mikhailkiselyov/WebstormProjects/untitled/ios/Pods/Headers/Private -I/Users/mikhailkiselyov/WebstormProjects/untitled/ios/Pods/Headers/Private/glog -I/Users/mikhailkiselyov/WebstormProjects/untitled/ios/Pods/Headers/Public -I/Users/mikhailkiselyov/WebstormProjects/untitled/ios/Pods/Headers/Public/glog -I/Users/mikhailkiselyov/WebstormProjects/untitled/ios/Pods/glog/src -I/Users/mikhailkiselyov/Library/Developer/Xcode/DerivedData/untitled-bbuurbgocmoxxkglqycxlaquymfk/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/glog.build/DerivedSources-normal/arm64 -I/Users/mikhailkiselyov/Library/Developer/Xcode/DerivedData/untitled-bbuurbgocmoxxkglqycxlaquymfk/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/glog.build/DerivedSources/arm64 -I/Users/mikhailkiselyov/Library/Developer/Xcode/DerivedData/untitled-bbuurbgocmoxxkglqycxlaquymfk/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/glog.build/DerivedSources -F/Users/mikhailkiselyov/Library/Developer/Xcode/DerivedData/untitled-bbuurbgocmoxxkglqycxlaquymfk/Build/Products/Debug-iphonesimulator/glog -Wno-shorten-64-to-32 -include /Users/mikhailkiselyov/WebstormProjects/untitled/ios/Pods/Target\ Support\ Files/glog/glog-prefix.pch -MMD -MT dependencies -MF /Users/mikhailkiselyov/Library/Developer/Xcode/DerivedData/untitled-bbuurbgocmoxxkglqycxlaquymfk/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/glog.build/Objects-normal/arm64/symbolize.d --serialize-diagnostics /Users/mikhailkiselyov/Library/Developer/Xcode/DerivedData/untitled-bbuurbgocmoxxkglqycxlaquymfk/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/glog.build/Objects-normal/arm64/symbolize.dia -c /Users/mikhailkiselyov/WebstormProjects/untitled/ios/Pods/glog/src/symbolize.cc -o /Users/mikhailkiselyov/Library/Developer/Xcode/DerivedData/untitled-bbuurbgocmoxxkglqycxlaquymfk/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/glog.build/Objects-normal/arm64/symbolize.o

CompileC /Users/mikhailkiselyov/Library/Developer/Xcode/DerivedData/untitled-bbuurbgocmoxxkglqycxlaquymfk/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/glog.build/Objects-normal/arm64/signalhandler.o /Users/mikhailkiselyov/WebstormProjects/untitled/ios/Pods/glog/src/signalhandler.cc normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'glog' from project 'Pods')
    cd /Users/mikhailkiselyov/WebstormProjects/untitled/ios/Pods
    export LANG\

**Comment by dulmandakh** [comment]
Did you see https://github.com/facebook/react-native/issues/31941?

**Comment by ksielyov** [comment]
> Вы видели [№ 31941](https://github.com/facebook/react-native/issues/31941) ?

It helped me, thanks. But it must work without doing these instructions, from scratch

**Comment by ksielyov** [comment]
But I am getting this on my projects ran earlier on Apple Silicon
/Users/mikhailkiselyov/WebstormProjects/GrafClubNew/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.5.99. (in target 'react-native-payments' from project 'Pods')
/Users/mikhailkiselyov/WebstormProjects/GrafClubNew/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.5.99. (in target 'react-native-text-input-mask' from project 'Pods')
/Users/mikhailkiselyov/WebstormProjects/GrafClubNew/ios/GrafClubNew.xcodeproj: error: The linked library 'libPods-GrafClubNew.a' is missing one or more architectures required by this target: arm64. (in target 'GrafClubNew' from project 'GrafClubNew')
/Users/mikhailkiselyov/WebstormProjects/GrafClubNew/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.5.99. (in target 'react-native-google-maps' from project 'Pods')
/Users/mikhailkiselyov/WebstormProjects/GrafClubNew/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.5.99. (in target 'Braintree-Braintree-Drop-In-Localization' from project 'Pods')
/Users/mikhailkiselyov/WebstormProjects/GrafClubNew/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.5.99. (in target 'react-native-maps' from project 'Pods')
/Users/mikhailkiselyov/WebstormProjects/GrafClubNew/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.5.99. (in target 'boost-for-react-native' from project 'Pods')
/Users/mikhailkiselyov/WebstormProjects/GrafClubNew/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.5.99. (in target 'Braintree' from project 'Pods')


objc[6352]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libauthinstall.dylib (0x1f7dabad8) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1219c82b8). One of the two will be used. Which one is undefined.
objc[6352]: Class AMSupportURLSession is implemented in both /usr/lib/libauthinstall.dylib (0x1f7dabb28) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1219c8308). One of the two will be used. Which one is undefined.
** BUILD FAILED **

**Comment by mikehardy** [comment]
> It helped me, thanks. But it must work without doing these instructions, from scratch

Looking forward to your feedback testing this then: https://github.com/facebook/react-native/commit/d583c2f154e9588b4183117f6358483045d7ebb7

Please test it and let us know how it goes @ksielyov

**Comment by ksielyov** [comment]
> > It helped me, thanks. But it must work without doing these instructions, from scratch
> 
> Looking forward to your feedback testing this then: [d583c2f](https://github.com/facebook/react-native/commit/d583c2f154e9588b4183117f6358483045d7ebb7)
> 
> Please test it and let us know how it goes @ksielyov

Same

**Comment by mikehardy** [comment]
@ksielyov you misunderstand: You need to test it. We need feedback and you appear to be an affected person. Please test it and report how it went with the library flags set like that.
