### ISSUE TITLE
An empty `Text` elements causes its parent to span vertically, printing a "ghost line"

### ISSUE THREAD

**Issue by jsamr** [facebook/react-native#32062]
## Description

This snippet:

```jsx
<View
  style={{
    backgroundColor: "black",
  }}>
  <Text />
</View>
```

will render as:

![screenshot-2021-08-22_16 52 59 65](https://user-images.githubusercontent.com/3646758/130368396-8596adc6-b230-4512-b79f-e52add2fcd40.png)

Also note that the height of this spanning behavior is not influenced by `lineHeight` style.

## Discussion

One would expect that an empty `Text` element has a zero-width and height, similarly to an empty `<span>` element in HTML. I would expect instead the below snippet to render as seen in the attached screenshot:

```jsx
<View
  style={{
    backgroundColor: "black",
  }}>
  <Text>{"\n"}</Text>
</View>
```
Instead, this latter snippet renders visually like 2 lines.

## React Native version:

```
info Fetching system and libraries information...
System:
    OS: Linux 5.13 Manjaro Linux
    CPU: (8) x64 Intel(R) Core(TM) i7-8809G CPU @ 3.10GHz
    Memory: 1.25 GB / 31.28 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.4 - /usr/bin/node
    Yarn: 1.22.11 - /usr/bin/yarn
    npm: 7.20.6 - /usr/bin/npm
    Watchman: 4.9.0 - /usr/bin/watchman
  SDKs:
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.0, 29.0.2, 29.0.3, 30.0.0, 30.0.1, 30.0.2, 30.0.3, 31.0.0, 31.0.0, 31.0.0
      System Images: android-22 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom_64, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7486908
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.65.1 => 0.65.1 
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Render an empty `Text` element inside a `View`;
2. Observe the `View` spanning somewhere around 20px in height.

## Expected Results

The parent `View` should have a zero height.

## Snack, code example, screenshot, or link to a repository:

https://github.com/jsamr/react-native-empty-text-spans-bug

**Comment by jsamr** [comment]
It is still requiring attention, stale bot.

**Comment by fredmulligan** [comment]
Still no good?
