### ISSUE TITLE
[Android] Selectable Text ellipsize is not working

### ISSUE THREAD

**Issue by Mighty683** [facebook/react-native#32075]
## Description
When `Text` component is `selectable={true}`. On Android only `ellipsizeMode="tail"` works fine.

## React Native version:
```
    react: 17.0.2 => 17.0.2 
    react-native: 0.65.1 => 0.65.1 
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Create Text component add `numberOfLines={1}` `selectable={true}` props
2. Set `ellipsizeMode={head}`
3. On android ellipsize won't work.

## Expected Results
Ellipsize should work with all modes on android.

## Snack, code example, screenshot, or link to a repository:
https://snack.expo.dev/YiPFFMQ4q

**Comment by weijintao92** [comment]
有2种解决方式：
第一种：
<Text selectable={true} key={Math.random()}>
   {text}
</Text>‘


备用方法2：FlatList 设置  removeClippedSubviews={false}
