### ISSUE TITLE
[Android] FabricViewStateManager: setState called without a StateWrapper

### ISSUE THREAD

**Issue by KingAmo** [facebook/react-native#32070]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
i have no idea what is wrong , but i app get stuck and logcat  print `FabricViewStateManager: setState called without a StateWrapper`  repeatedly

## React Native version:
Run `react-native info` in your terminal and copy the results here.
```
System:
    OS: macOS 11.5.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 2.38 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.19.0 - /usr/local/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 7.19.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 21, 23, 25, 26, 27, 28, 29, 30
      Build Tools: 23.0.1, 26.0.1, 26.0.2, 27.0.3, 28.0.3, 29.0.2
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7621141
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_212 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.2 => 17.0.2
    react-native: ^0.64.1 => 0.64.1
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```
## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.
2.

## Expected Results
Describe what you expected to happen.

## Snack, code example, screenshot, or link to a repository:
Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by KingAmo** [comment]
![image](https://user-images.githubusercontent.com/29938227/130439198-2ef3bb0e-8cf3-4d85-b612-bf891180059e.png)

**Comment by efstathiosntonas** [comment]
same here on 0.65, error is incredibly crypted, google returns really few results.

**Comment by gigadeplex** [comment]
Yeah, I had this problem too. I downgraded to 0.64.2 and it stopped crashing. :) Don't know what's wrong with the 65 though, I liked it a lot until it started crashing.

**Comment by efstathiosntonas** [comment]
@gigadeplex it's not only on 0.65.x, it happened to me on 0.64.x too

**Comment by cloudychen** [comment]
same here

**Comment by Dsantacruz** [comment]
The same thing just happened to me, after installing drawer and reanimated 2, now the app crashes and the screen goes blank, help me

**Comment by aliraza-noon** [comment]
facing the same issue can someone help please

**Comment by Dsantacruz** [comment]
I solved it by migrating my logic to a new project of react native 0.65.1 with the latest versions of react navigation

**Comment by Daha62** [comment]
same issue

**Comment by kuenyu40** [comment]
same here

**Comment by Levin-nik** [comment]
same here

**Comment by thijs-qv** [comment]
> I solved it by migrating my logic to a new project of react native 0.65.1 with the latest versions of react navigation

Which versions did you update to? I'm on RN 0.65.1 with [the latest versions](https://github.com/react-navigation/react-navigation#package-versions) of react-navigation, but I'm still getting a blank screen after reloading my StackNavigator.

**Comment by maaliHasan** [comment]
same here!

**Comment by mwegener-com** [comment]
same problem

**Comment by Bayramito** [comment]
Just import the hooks from the navigation/native not from the core. Like useRoute, useNavigation, usScrollToTop

**Comment by mwegener-com** [comment]
> Just import the hooks from the navigation/native not from the core. Like useRoute, useNavigation, usScrollToTop

Which hooks? All my used useState Hooks?

**Comment by zrina1314** [comment]
same problem

**Comment by tonyjaimep** [comment]
I got the same both on Android and iOS, the "solution" I had was to call `console.log` close to where the error was raised, somehow that works 🤔

**Comment by jqn** [comment]
For me this error shows up when I import a TextInput component. I'm on RN version 0.67.0

**Comment by jqn** [comment]
Ok, my issue wasn't the same as this one please view https://github.com/facebook/react-native/issues/31572 for a workaround

**Comment by feiyin0719** [comment]
it seem that it happened when ReactScrollView updateStateOnScroll

**Comment by 000xuandu** [comment]
`"react-native": "0.66.4"`

The error message will show when scrolling Flatlist.

**Comment by vr0707** [comment]
This same error to showed my logcat. But I worked on Curved navigation bar, after routing not worked...

**Comment by pritam-digichal** [comment]
any progress in this issue?

**Comment by andvalsol** [comment]
I'm also experiencing the same issue, after debugging, here's the flow that originates the issue:
1) `NativeViewHierarchyManager` gets called on the method `createView()` which passes the stateWrapper as `null`
2)  The call from 1) calls `createView()` from `ViewManager` (with a null stateWrapper).
3)  The call from 2) calls `onCreateViewInstance` which has the following logic:
```
if (stateWrapper != null) {
      Object extraData = updateState(view, initialProps, stateWrapper);
      if (extraData != null) {
        updateExtraData(view, extraData);
      }
    }
```

Because the `stateWrapper` is null, the `ViewManager` 's `updateState()` won't be called. 

4) On `ReactSrollView` `OnLayout()` function calls `reactScrollTo()`
5) `reactScrollTo()` function calls `updateStateOnScroll()` which has the following logic:
```

mFabricViewStateManager.setState(
        new FabricViewStateManager.StateUpdateCallback() {
          @Override
          public WritableMap getStateUpdate() {

            WritableMap map = new WritableNativeMap();
            map.putDouble(CONTENT_OFFSET_LEFT, PixelUtil.toDIPFromPixel(scrollX));
            map.putDouble(CONTENT_OFFSET_TOP, PixelUtil.toDIPFromPixel(scrollY));
            return map;
          }
        });
``` 
6) The `setState()`function has the following logic:
```
if (stateWrapper == null) {
      FLog.e(TAG, "setState called without a StateWrapper");
      return;
    }
```
This is the flow that I've seen in a project I'm working on. I have the following questions:
* Should the initial  `createView()` must set `stateWrapper` to null at first?
* If the answer to the first question is yes, at what stage does the `stateWrapper` gets updated?

**Comment by a728384698** [comment]
same issue. resolved?

**Comment by rateshb** [comment]
Any update on this issue? I can run my app of the Expo platform without any issues, however when I am running it on the emulator it starts throwing this error and app stops working properly. Stuck for a few days, please help.

**Comment by Kstar0722** [comment]
any updates on this issue?

**Comment by abbasmashaddy72** [comment]
Any Update on This Issue, It Still Occurs from Me Also

**Comment by fogg4444** [comment]
This is happening for me, seeing the error `unknown:FabricViewStateManager: setState called without a StateWrapper` when clicking on a TextInput field on Android. Works just find on iOS. The keyboard closes immediately and that's the tell that there's something wrong.

**Comment by garrett-gottlieb** [comment]
Happening for me `"react-native-reanimated": "2.3.1",`

**Comment by hamdidamar** [comment]
same here, any update?

**Comment by suwu150** [comment]
same here, any update?

**Comment by techgerm** [comment]
This is happening to us as well - we have the following dependencies that may be relevant:
```
"react-native": "0.66.4",
"react-native-reanimated": "2.13.0",
"@react-native-masked-view/masked-view": "^0.2.8",
"@react-navigation/bottom-tabs": "6.4.0",
"@react-navigation/drawer": "6.5.0",
"@react-navigation/native": "6.0.13",
"@react-navigation/native-stack": "6.9.1",
```

**Comment by gaberogan** [comment]
According to [this](https://github.com/software-mansion/react-native-reanimated/issues/2573#issuecomment-953697909), it looks like react-native-reanimated is not adding support for Fabric until v3.

Not sure if that's what is behind all this but it could be. Does this issue go away for anyone when they disable Fabric (aka the new architecture)?

**Comment by herujest** [comment]
any update on this?
it's happen in `"react-native": "0.66.4"`. 
I also have this that might be relevant:
```
"react-native-reanimated": "^3.2.0",
"react-native-safe-area-context": "^4.3.1",
"@react-navigation/bottom-tabs": "^6.0.3",
"@react-navigation/native": "^6.0.2",
"@react-navigation/stack": "^6.0.4",
"react-native-screens": "^3.13.1",
```

**Comment by vreoo** [comment]
I ma facing the same issue. Any Update?

I am using:
```json
"react-native": "0.66.5",
"react-native-gesture-handler": "2.9.0",
"react-native-reanimated": "^3.3.0",
"react-native-safe-area-context": "^4.5.3",
"@react-navigation/bottom-tabs": "^6.4.1",
"@react-navigation/compat": "^5.3.20",
"@react-navigation/drawer": "^6.4.4",
"@react-navigation/native": "^6.0.12",
"@react-navigation/stack": "^6.2.3",
```

**Comment by ravindraguptacapgemini** [comment]
@cortinico Are you guys looking into this issue, as this still happening on latest 0.72.1 with android.

**Comment by vreoo** [comment]
The issue is not yet resolved! It shouldn't be closed as it's still happening and we didn't get any explanation for the behaviour at all.

**Comment by cortinico** [comment]
> @cortinico The issue is not yet resolved! It shouldn't be closed as it's still happening and we didn't get any explanation for the behaviour at all.

Please open a new issue and provide a valid reproducer, then we can look into it 👍
We also need to make sure the issue still happens on 0.73.x or not

**Comment by vreoo** [comment]
> > @cortinico The issue is not yet resolved! It shouldn't be closed as it's still happening and we didn't get any explanation for the behaviour at all.
> 
> Please open a new issue and provide a valid reproducer, then we can look into it 👍 We also need to make sure the issue still happens on 0.73.x or not

Fair enough, I totally agree with you. But It's very hard to reproduce this since it's only happening on production track + it happens with some users only (not all of them). We only get reports from the Google play console about the crashes with stack trace of the crash (along with device model and brand).

The only pattern I've noticed in my case, is that it happens only with the newest Android APIs (30 up to 34) not lower.

I was trying to reproduce this on my own many times, But I don't know where to start debugging for the issue or what to expect and what not or where to look and focus. In many cases the App is stuck on Splash screen after fresh install, or it opens then immediately crashes and never opens again. which doesn't happen to me at all when I try it myself (I tried many devices, but no luck).

**Comment by AsteriskZuo** [comment]
The above problem is related to `ScrollView`.
![fbd01f03f3fd1393701a5f824092aea9](https://github.com/user-attachments/assets/5cf99cd0-7233-4c21-baee-fecbc558056b)
![e11211aac76ae0a4f9d7001f5fffb120](https://github.com/user-attachments/assets/b969fca1-6f96-4262-954d-a15440e6a86a)
