### ISSUE TITLE
onBlur of TextInput is not called when we click on any other control

### ISSUE THREAD

**Issue by vishnu2410** [facebook/react-native#32076]
On Android, if TextInput control is in editing mode and we click on other control (say, Button), onBlur is not called and the soft keyboard remains opened. So even after switching to a different screen users can still type in the TextInput.

**Comment by yousseftarekkh** [comment]
@vishnu2410 This behavior is mainly happening because clicking on a `Button` does not `blur` a `TextInput` as you can see. Furthermore, the `Drawer` is not considered a new screen as your main screen is still rendered completely but just shadowed by this `Drawer` component. If you do navigate to a different screen, this will trigger the component to `blur` and unmount.

#### Conclusion
For this specific use case, you could change the `onPress` method for your button to the following.
```tsx
import { Keyboard } from 'react-native';

const onOpenDrawer = () => {
  Keyboard.dismiss();
  /* rest of your code */
};

return <Button onPress={onOpenDrawer} />
```

But as a generic implementation and mainly solve this issue check this [Hide keyboard in react-native - stackoverflow](https://stackoverflow.com/a/34779467/7729332)

**Comment by vishnu2410** [comment]
OnBlur is not called even if the button brings you to a different screen. That is, in fact, one of the use cases we have in our application. Instead of a new screen, I added a drawer for simple repro.
Furthermore, if we use Keyboard.dismiss(), the problem remains because whatever text the user has entered in the textInput box thus far, will not be committed.

**Comment by yousseftarekkh** [comment]
@vishnu2410 I understand the struggle, as `Keyboard.dismiss()` is not actually blurring the component.
I have developed a package which is not production ready yet but you can check the logic behind the handling of such issue. Also feel free to use it if you want. Here's the link [react-native-focal](https://github.com/yousseftarekkh/react-native-focal).

**Comment by vishnu2410** [comment]
Need attention to this bug as it is causing a lot of behavioral issues in our app.

**Comment by AlexandruCalinica** [comment]
I also cannot make onBlur fire in any way. I'm developing a form management library that depends on the 'onBlur' event for TextInput to work and currently related logic like setting that TextInput value in state, or revalidation , etc, is just unreachable. Any updates on this?

**Comment by alickcai** [comment]
don't know why Facebook hasn't fixed this bug, it's a generic function that any App needs...

**Comment by hussainali003** [comment]
i have the same problem but in my case , i click on free space keyboard was not close but when i used the back button on mobile 
keyboard was gone but input field was focus. no matter where i click the input field was not blur .

**Comment by hussainali003** [comment]
i find the quick fix for me , i don't know it work on you but here it is . i use scroll view for my application then i see the bug was gone automatic , then i try more and see the scroll view fix this bug . i don't know why and i don't know, if it work for u but it work  that's why i share .

**Comment by kawpuh** [comment]
I was able to solve this by adding an event listener on "KeyboardDidHide" that calls `Keyboard.dismiss()`.
https://reactnative.dev/docs/keyboard

**Comment by famdude** [comment]
:/
why?! isn't it obvious and necessary for a react input component to be blured, or un-focued, whe we touch any area of screen outside the  input?!
