### ISSUE TITLE
Buttons or TouchableOpacity are not clickable inside a header with ImageBackground in the android

### ISSUE THREAD

**Issue by SyedShehrozSohail** [facebook/react-native#32071]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
In my application there is a header with ImageBackground. When I use TouchableOpacity or Button inside it, it is not clickable. I tried wrapping it with a view and tried giving it a zIndex as well. But none working.
## React Native version:
    "react": "17.0.1",
    "react-native": "0.64.2",
## Steps To Reproduce (Code Example)
`import React from 'react';
import { TouchableOpacity, ImageBackground, Alert, Text } from 'react-native';

const CustomHeader = () => {
  return (
    <ImageBackground style={{ flex: 1 }}
      source={require('../../Assets/Images/app-bg.png')}
      resizeMode={'cover'}
    >
      <TouchableOpacity
        style={{
          height: 25,
          marginHorizontal: 20,
          marginTop: 10,
        }}
        onPress={() => Alert.alert("You clicked me")}
      >
        <Text>Click Me</Text>
      </TouchableOpacity>
    </ImageBackground>
  );
}

export default CustomHeader;
`
## Expected Results
Ideally the button should be clickable with ImageBackground. But when I remove the ImageBackground, only then the button is clickable.

**Comment by DanielSuarezDev** [comment]
ya intentaste agregar un width

**Comment by SyedShehrozSohail** [comment]
Where should I provide the width?

**Comment by DanielSuarezDev** [comment]
Puedes poner algo como:

`
//el touchable     
   <TouchableOpacity
//el onpress
          onPress={(): void => {}}
// ideal agregar un estilo aparte
          style={styles.touchable}
> // aqui acaba la primera parte del touchable

// dentro del touchable ponees la imagen
          <Image
            source={require('')}
            resizeMode="contain"
            style={styles.image}
          />
//puedes poner un vie y dentro un text
          <View>
            <Text >my text</Text>
          </View>
        </TouchableOpacity>`

**Comment by SyedShehrozSohail** [comment]
Yes, it worked

**Comment by huang-ju** [comment]
```
<Pressable onPress={onPressFunction}>
  <Text>I'm pressable!</Text>
</Pressable>
```
