### ISSUE TITLE
FTP connection with react native for IOS 14.x

### ISSUE THREAD

**Issue by Shubhangigovil** [facebook/react-native#32087]
I have an app that needs to connect to an FTP server. I used react-native-ftp for android but this package doesn't work for IOS. I want to know how do I connect ftp with my ios app. As I see there is no npm package available, Can I get help with someone writing native module code for connecting FTP with the latest ios version(14.x)?

**Comment by Yali07** [comment]
I'm also facing the same problem. Are you resolved this issue?

**Comment by vikramsinh-iottive** [comment]
I hope this message finds you well. I am currently working on a React Native project that is functioning perfectly on Android. However, I am facing challenges while creating an iOS build. Despite multiple attempts, I haven’t been able to resolve the issue.

Here are some details about my setup and the problem:

React Native Version: 0.71
Node.js Version: 18.x
MacOS Version: sequoia 15.1
Xcode Version: 16.2

I have already tried the following steps without success:

- cd ios && pod install.
- Verified that the ios/ folder contains the correct configurations.
- Cleaned the build folder and cleared caches.

I suspect the issue could be related to dependency incompatibility, a configuration mismatch, or a missing iOS-specific setup.

Could you please provide guidance or point me to any resources that could help resolve this issue? I’d greatly appreciate any support or advice you can offer.

Thank you for your time and assistance.

Best regards,
Vikram
