### ISSUE TITLE
[Android] Cannot select text in TextInput

### ISSUE THREAD

**Issue by satya164** [facebook/react-native#3208]
Long press on text in a `TextInput` does nothing. The `Paste` option appears when I click on empty area. But the selection handles don't appear when pressing the text. Which makes it impossible to select/copy/cut text.

**Comment by satya164** [comment]
May be we can do something like this http://stackoverflow.com/questions/24338972/show-copy-paste-context-menu-on-text-using-code-android

**Comment by andreicoman11** [comment]
Fixed in https://github.com/facebook/react-native/commit/c456accbeda8b6c3aa01a0d713cd9998eef2c61b
