### ISSUE TITLE
react native share promise resolves before user shares + android

### ISSUE THREAD

**Issue by nwabdou85** [facebook/react-native#32083]
## Description
I use react native share to share text, the bug is that share resolve even before the user share 

## React Native version:
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (4) x64 Intel(R) Core(TM) i5-2557M CPU @ 1.70GHz
      Memory: 27.14 MB / 4.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.1.0 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/nom
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 23, 26, 27, 28, 29
        Build Tools: 23.0.1, 27.0.3, 28.0.3, 29.0.2, 29.0.3
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: ^0.59.8 => 0.59.8 
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-cli: 2.0.1
      react-native-rename: 2.4.1

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Link a button a share function (the same function on react native web site)
2.  Press the button 

## Expected Results
I expect that share function resolve only when share or dismiss 

## Snack, code example, screenshot, or link to a repository:
    try {
      const result = await Share.share({
        message: 
       `bla bla bla   `,
      });

      if (result.action === Share.sharedAction) {
        if (result.activityType) {
          // shared with activity type of result.activityType
        } else {
          // shared
        }
      }

**Comment by AlvinSreng** [comment]
Any update on this?
