### ISSUE TITLE
fetch don't call then/catch in android release bundler

### ISSUE THREAD

**Issue by dingziqi** [facebook/react-native#32080]
## Description

when i rewrite `global.console` to a new object, fetch won't call `.then()` or `.catch()` in release bundle at android, but it's ok in debug or ios.

## React Native version:

System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 345.55 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.22.0 - ~/.nvm/versions/node/v10.22.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v10.22.0/bin/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v10.22.0/bin/npm
    Watchman: 2021.06.07.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.3/12C33 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.4 => 0.63.4
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. just add following code to your project
```js
global.console = {
  info: () => {},
  log: () => {},
  warn: () => {},
}
```
2. change to this way is ok
```js
global.console.info = () => {};
global.console.log = () => {};
global.console.warn = () => {};
```

## Expected Results
Describe what you expected to happen.

## Snack, code example, screenshot, or link to a repository:
Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by 452MJ** [comment]
```
global.console = {
  info: () => {},
  log: () => {},
  warn: () => {},
}
```
global.console里面有asset()方法，所以如果你使用上面的写法，会使global.console.asset()为undefined，要么补全方法，要不一个个来覆盖

```
global.console = {
  ...global.console,
  info: () => {},
  log: () => {},
  warn: () => {},
}
```

**Comment by dingziqi** [comment]
> ```
> global.console = {
>   info: () => {},
>   log: () => {},
>   warn: () => {},
> }
> ```
> 
> global.console里面有asset()方法，所以如果你使用上面的写法，会使global.console.asset()为undefined，要么补全方法，要不一个个来覆盖
> 
> ```
> global.console = {
>   ...global.console,
>   info: () => {},
>   log: () => {},
>   warn: () => {},
> }
> ```

已经解决了，是在做版本升级的时候遇到的，旧版本没有这个问题，网上也没查到相似问题，所以发出来记录下，免得其它人也踩坑了。
