### ISSUE TITLE
iOS build fails for RN upgrade 0.64.2 -> 0.65.1

### ISSUE THREAD

**Issue by sethrandallavant** [facebook/react-native#32097]
## Description
I went through the upgrade helper for RN version 0.64.2 -> 0.65.1. Android build successful but iOS cannot build.
![failed-build](https://user-images.githubusercontent.com/85895234/131012481-b5d94307-4a32-4ce9-a1cd-16a895857fe8.jpg)
![RCTViewRegistry](https://user-images.githubusercontent.com/85895234/131012499-efa801ef-9d55-435f-9130-86958309b806.jpg)

## React Native version:
![rn-info](https://user-images.githubusercontent.com/85895234/131013474-68d9efa5-0d51-4b6d-bb65-887836c3d2b9.jpg)

## Steps To Reproduce
I ran the following commands:
1. `npx react-native upgrade`
2. `npx react-native start`
3. `npx react-native run-ios`

## Expected Results
iOS should build successfully.

## Snack, code example, screenshot, or link to a repository:
I ran the following commands:
1. `npx react-native upgrade`
2. `npx react-native start`
3. `npx react-native run-ios`

**Comment by 452MJ** [comment]
Try follow the upgrade-helper to manual upgrade, [https://react-native-community.github.io/upgrade-helper/?from=0.64.2&to=0.65.1](https://react-native-community.github.io/upgrade-helper/?from=0.64.2&to=0.65.1)

**Comment by sethrandallavant** [comment]
@452MJ I am getting this error after both the react native upgrade command and using the manual. They both end up with this error.

**Comment by 452MJ** [comment]
I upgrade successfully from 0.64.0 to 0.65.1 by using the manual😅

**Comment by danielrhodes** [comment]
Having a similar issues with this upgrade on iOS

```
ld: warning: directory not found for option '-L/Users/xxxxxxxxxxx/Library/Developer/Xcode/DerivedData/app-agsgroevmbnujndpymeffqqnblvx/Build/Intermediates.noindex/ArchiveIntermediates/app/BuildProductsPath/Release-iphoneos/React-CoreModules'`
ld: library not found for -lReact-CoreModules
```

But only during archiving. When I look inside the build intermediates folder, the React-CoreModules folder is not there (as the warning suggests).

I have tried doing things like a clean and removing the `Pods` folder and then running `pod install`

**Comment by sethrandallavant** [comment]
@452MJ After upgrading manually did you run any commands like ```pod install``` or ```yarn```?

**Comment by 452MJ** [comment]
> @452MJ After upgrading manually did you run any commands like `pod install` or `yarn`?

Just run `pod install` for iOS. Android will be linked automatically.
In order to ensure that dependence can be upgraded correctly, you can delete `ios/Podfile.lock` & `yarn.lock`

**Comment by TheRogue76** [comment]
> Having a similar issues with this upgrade on iOS
> 
> ```
> ld: warning: directory not found for option '-L/Users/xxxxxxxxxxx/Library/Developer/Xcode/DerivedData/app-agsgroevmbnujndpymeffqqnblvx/Build/Intermediates.noindex/ArchiveIntermediates/app/BuildProductsPath/Release-iphoneos/React-CoreModules'`
> ld: library not found for -lReact-CoreModules
> ```
> 
> But only during archiving. When I look inside the build intermediates folder, the React-CoreModules folder is not there (as the warning suggests).
> 
> I have tried doing things like a clean and removing the `Pods` folder and then running `pod install`
> 
> **UPDATE**
> 
> I have resolved this. In the `Podfile`, the minimum iOS target version in 0.65 is upped to `11.0`, but my XCode project was still at `10.0`. When I changed this to match what was in Cocoapods, the linking step worked and things archived successfully. Hope that helps somebody with a similar issue.

Bless you @danielrhodes! I have a native swift module in my project and i was 90% convinced it was the root cause of this mess. It was such a pain

**Comment by Deodes** [comment]
@452MJ Did you try to update exactly from **0.64.2** to 0.65.1. And could you please explain, how you upgrade manually, i mean what did you do after changing files (did you change project.pbxproj file too?), which commands used?

**Comment by 452MJ** [comment]
> Try follow the upgrade-helper to manual upgrade, https://react-native-community.github.io/upgrade-helper/?from=0.64.2&to=0.65.1

@Deodes After modifying the corresponding files, delete `Podfile.lock` and `yarn.lock`, and then reinstall the third-party library. (There may be third-party libraries that are compatible with 0.65.1, you will need to update them as well)

**Comment by Deodes** [comment]
@452MJ Thank you so much, what about the file project.pbxproj(it is very difficult to edit). Are you changing it too?

**Comment by 452MJ** [comment]
@Deodes Never changing it

**Comment by ashok-sl** [comment]
RN 0.65.1
Apple M1 

```
ld: building for iOS Simulator, but linking in object file built for iOS, file App/ios/Pods/GoogleMaps/Maps/Frameworks/GoogleMapsCore.framework/GoogleMapsCore' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by Jayachandran369** [comment]
> RN 0.65.1 Apple M1
> 
> ```
> ld: building for iOS Simulator, but linking in object file built for iOS, file App/ios/Pods/GoogleMaps/Maps/Frameworks/GoogleMapsCore.framework/GoogleMapsCore' for architecture arm64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> ```

Did you find any fix @ashok-sl ,am facing same issue
