### ISSUE TITLE
[TextInput] Add autoGrow support

### ISSUE THREAD

**Issue by satya164** [facebook/react-native#3209]
Auto-growing `TextInput` is useful as the input doesn't have to take too much space, and the user can still see all the text if he enters multiple lines, especially in chat applications.

Currently I can auto grow it by adding a invisible `Text` element with exact same content, measuring it's height on the `onLayout` event and setting height of the `TextInput` element. But it doesn't feel natural, as the height doesn't change instantly.

**Comment by christopherdro** [comment]
There's currently two PR's that are trying to address this. #3097 #1229

**Comment by satya164** [comment]
Unfortunately, both seem to be iOS only :(

**Comment by christopherdro** [comment]
Sorry, didn't know you were referring to android. Could you possibly update the issue title to specify android?

**Comment by satya164** [comment]
@christopherdro I was referring to both iOS and Android.

**Comment by mikearmstrong001** [comment]
cc @andreicoman11

**Comment by brentvatne** [comment]
@satya164 - I created an issue for this on Product Pains! [See it here](https://productpains.com/post/react-native/add-support-for-automatically-resizing-multiline-textinput-based-on-content/). Go ahead and upvote it -- this is our new way of prioritizing non-trivial issues ([details here](https://github.com/facebook/react-native/issues/41#issuecomment-157540064)).

**Comment by satya164** [comment]
@brentvatne Thanks. Done.
