### ISSUE TITLE
Is it possible to get the top and left  position of an parent element / component in children component?

### ISSUE THREAD

**Issue by chetandhembre** [facebook/react-native#3210]
Usecase (IOS):

On button press I want to create overlay on entire screen. 

Problem is my button component is in component whose position is {top : 100, left: 100}. So when i try to set style of my component (overlay) to {position: 'absolute', top: 0, left: 0, height : height, width : width}. It render my component in inside my parent component.

![simulator screen shot 03-oct-2015 6 25 36 pm](https://cloud.githubusercontent.com/assets/1058442/10263018/5f13b2ba-69fc-11e5-8121-150560aa9253.png)

![simulator screen shot 03-oct-2015 6 25 45 pm](https://cloud.githubusercontent.com/assets/1058442/10263013/402dd326-69fc-11e5-9a7d-e6f2863e71df.png)

How can I may my overlay component to cover all my screen (green background)?

**Comment by bobbobb2118** [comment]
Vould not download: file supporyef

**Comment by chirag04** [comment]
Is this what you need: https://github.com/brentvatne/react-native-overlay?

**Comment by chetandhembre** [comment]
@chirag04 Thanks for link. 
I looked into this project. Kind of heavy for my requirement. I would like to find solution which will work for both in IOS and android.

**Comment by chirag04** [comment]
Ok. I think you need to move your overlay view out of the button view. Not sure if this will solve it but your hierarchy should look something like this:
```
<View style={green}>
    <View style={button} />
</View>
<View style={overlay} />
```

**Comment by chetandhembre** [comment]
Basically I am building component so my current hierarchy look like this


```
<View style={green}>
   <Overlay>
         <View style={button} />
  </Overlay>
</View>
```
and `Overlay` component is defined as below

```
<View>
    { 
        clicked ?
         <View style={overlay}/>
        : this.props.children
    }

</View>
```

Hope you understand what I want to say ?

**Comment by chetandhembre** [comment]
@chirag04 here is my code https://rnplay.org/apps/_HswdA

Help me if you can :)
