### ISSUE TITLE
Task :app:checkDebugAarMetadata FAILED

### ISSUE THREAD

**Issue by maqib4988** [facebook/react-native#32104]
✋ To keep the backlog clean and actionable, issues will be
🚫 closed if they do not follow one of the issue templates:
👉 https://github.com/facebook/react-native/issues/new/choose
After installing "npm install react-native-gesture-handler react-native-reanimated" these two libraries  I can't run my project.it shows me the error message "> Task :app:checkDebugAarMetadata FAILED " and "error Failed to install the app."
How can I resolve this issue?

**Comment by gabrieldonadel** [comment]
You need to enable Hermes on Android in order to use `react-native-reanimated` v2

**Comment by b3coded** [comment]
@maqib4988 Reanimated with version between 2.0 and 2.2.0 does not support React Native 0.65.x
see here:
https://github.com/software-mansion/react-native-reanimated/issues/2290

**Comment by maqib4988** [comment]
> You need to enable Hermes on Android in order to use `react-native-reanimated` v2

I anabled hermes and now I am getting this error bro...
![image](https://user-images.githubusercontent.com/33662050/131298454-fa11b705-b16a-4710-b6c8-66b0e4428696.png)

**Comment by maqib4988** [comment]
> @maqib4988 Reanimated with version between 2.0 and 2.2.0 does not support React Native 0.65.x
> see here:
> [software-mansion/react-native-reanimated#2290](https://github.com/software-mansion/react-native-reanimated/issues/2290)

I have upgraded reanimated version to ("react-native-reanimated": "^2.3.0-alpha.2") and still  I am facing problem bro

**Comment by 0nlyDev** [comment]
> > @maqib4988 Reanimated with version between 2.0 and 2.2.0 does not support React Native 0.65.x
> > see here:
> > [software-mansion/react-native-reanimated#2290](https://github.com/software-mansion/react-native-reanimated/issues/2290)
> 
> I have upgraded reanimated version to ("react-native-reanimated": "^2.3.0-alpha.2") and still I am facing problem bro

Same here, i am on 2.3.0-alpha.2 and i get the property 'shouldBeUseWeb' doesn't exist in node_m...\src\reanimated2\cire.ts:25:38

Any suggestions?

**Comment by 452MJ** [comment]
Add Reanimated's babel plugin to your babel.config.js. @0nlyDev 

https://docs.swmansion.com/react-native-reanimated/docs/installation#babel-plugin
