### ISSUE TITLE
Can't change TextInput style when an emoji is added to text

### ISSUE THREAD

**Issue by annucy** [facebook/react-native#32113]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
I am currently building a TextInput in react-native where I would like to change the TextInput style dynamically like changing the fontSize, text color etc based on conditions. It works fine but once emoji's are added to the text value in TextInput, this does not work. The issue is only with IOS and android works fine.

## React Native version:
0.62.0

## Steps To Reproduce
1. Create a TextInput and change TextInput style dynamically like changing the fontSize, text color etc based on conditions.
2. Enter some text and emojis

## Expected Results
The style of text value in TextInput should change accordingly

## Snack, code example, screenshot, or link to a repository:
<img width="268" alt="Screenshot 2021-08-30 at 4 40 29 PM" src="https://user-images.githubusercontent.com/35170424/131330617-e96862a8-459d-490e-959f-0b05d6449e1b.png">

**Comment by annucy** [comment]
Any updates on this?

**Comment by Tymofiev** [comment]
+1, v. 0.63.4

**Comment by lunaleaps** [comment]
I can't reproduce this anymore on 0.73.5 
![simulator_screenshot_97587C2A-D436-4130-A5C8-3F48AD63CAA5](https://github.com/facebook/react-native/assets/1309636/320ff844-01fc-4d94-a408-74326eb8795b)

Closing
