### ISSUE TITLE
 ReferenceError: Property 'shouldBeUseWeb' doesn't exist, js engine: hermes  ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication).

### ISSUE THREAD

**Issue by maqib4988** [facebook/react-native#32111]
I am getting this error(Error SS is attached below) after I declare "const Drawer = createDrawerNavigator();" this variable.
i am using ("react-native": "0.65.1",)        ("react-native-reanimated": "^2.3.0-alpha.2",) and i have also enabled hermes.

![image](https://user-images.githubusercontent.com/33662050/131299696-fb7cd797-b851-4d74-9afc-450fcebf3dee.png)

![image](https://user-images.githubusercontent.com/33662050/131330335-e2773cca-7039-425d-a54b-a7b96caa4cf3.png)

**Comment by ingvardm** [comment]
This happens after installing react-native-reanimated v2.3.0-alpha.2

**Comment by markl-vesper** [comment]
same as you @ingvardm but its happening on ios. did you have same issue on ios? any tips?

I've got same packages as you

```
"react-native": "0.65.1",
"@react-navigation/drawer": "6.1.4",
"react-native-reanimated": "^2.3.0-alpha.2",
```

Am wondering if its anything to do with -> https://github.com/software-mansion/react-native-reanimated/blob/2.0.0-alpha.4/docs/docs/installation.md#ios

and the changes required to AppDelegate?

**Comment by ingvardm** [comment]
@markl-vesper  
Turns out i didn't have reanimated 2.x installed  via pods, just the one from previous installation which was 1.8
I cleaned everything and installed 2.3.0-alpha.2 and.... (drum roll....) it still works...
Maybe you can try adding this to your podfile
```
post_install do |installer|
   installer.pods_project.targets.each do |target|
       target.build_configurations.each do |config|
           config.build_settings['OTHER_CPLUSPLUSFLAGS'] = '-DDONT_AUTOINSTALL_REANIMATED'
       end
   end
end
```
and see if it help.

**Comment by laurpantelimon** [comment]
Any update on this? I also have this issue.
