### ISSUE TITLE
Custom font is not working on android platform.

### ISSUE THREAD

**Issue by mobcoder-shyama** [facebook/react-native#32126]
Actually i try to implement the Arabic font on React-Native in 0.63.3 version but it was not working on android & doesn't showing any errors.I tried all the ways to implement the font but result is same not working.

This is what I tried:

Creating react-native.config.js file on root project with the following code:

module.exports = {
    project: {
      ios: {},
      android: {},
    },
    assets: ['./src/assets/fonts']
  };
  
  
Running react-native link: This didnt give me any errors:

info Linking assets to ios project
info Linking assets to android project
success Assets have been successfully linked to your project

<Text style={[styles.signText,{fontFamily:'AvenirArabic-book'}]}>{strings.signin_text}</Text>

Note :- Working perfectly in iOS platform

**Comment by 452MJ** [comment]
In Android, you need to put fonts to `android/app/src/maim/assets/fonts` folder
