### ISSUE TITLE
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

### ISSUE THREAD

**Issue by gagan72** [facebook/react-native#32122]
C:\Users\Manu\Desktop\mobile\hello>npx react-native run-android
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 875 file(s) to forward-jetify. Using 4 workers...

FAILURE: Build failed with an exception.
> Evaluating settingsITIALIZING [79ms]
* Where:
Build file 'C:\Users\Manu\Desktop\mobile\hello\android\build.gradle' line: 39

* What went wrong:
A problem occurred evaluating root project 'hello'.
> Could not find method android() for arguments [build_7rxodrum8w7uer3ztokk6r5ir$_run_closure2@3d3dd050] on root project 'hello' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\Manu\Desktop\mobile\hello\android\build.gradle' line: 39

* What went wrong:
A problem occurred evaluating root project 'hello'.
> Could not find method android() for arguments [build_7rxodrum8w7uer3ztokk6r5ir$_run_closure2@3d3dd050] on root project 'hello' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

    at makeError (C:\Users\Manu\Desktop\mobile\hello\node_modules\execa\index.js:174:9)
    at C:\Users\Manu\Desktop\mobile\hello\node_modules\execa\index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (C:\Users\Manu\Desktop\mobile\hello\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:106:5)
    at async Command.handleAction (C:\Users\Manu\Desktop\mobile\hello\node_modules\@react-native-community\cli\build\index.js:186:9)
info Run CLI with --verbose flag for more details.

**Comment by MohitPrakashSharma** [comment]
I  have the same issue. How we can fix that?


While running the react-native run-android cmd getting the failed build.

```
* Get more help at https://help.gradle.org

BUILD FAILED in 2s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
```

Here Have some environment Details react-native info

```
System:
    OS: Linux 5.4 Ubuntu 18.04.5 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i3-10100 CPU @ 3.60GHz
    Memory: 200.08 MB / 7.64 GB
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 12.22.5 - ~/.nvm/versions/node/v12.22.5/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 7.22.0 - ~/.nvm/versions/node/v12.22.5/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
    Python: 2.7.17 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by cortinico** [comment]
> Could not find method android() for arguments [build_7rxodrum8w7uer3ztokk6r5ir$_run_closure2@3d3dd050] on root project 'hello' of type org.gradle.api.Project.

This issue is most likely related to a wrong configuration inside the `android{}` block of your `build.gradle` file. Can you share that section of your Gradle file?

**Comment by cortinico** [comment]
Closing as it looks like the issue was solved. Feel free to reopen if the issue persists and share the requested info.
