### ISSUE TITLE
Programmatically focusing a touchable works on web, not on Android

### ISSUE THREAD

**Issue by JerryBels** [facebook/react-native#32121]
## Description
When trying to focus a touchable using `touchableRef.current?.focus()` in a `useEffect`, it works on the web but not on Android.

## React Native version:
{ last version available on snack }

## Steps To Reproduce
1. define a touchable in your render
2. try to focus it in a useEffect

## Expected Results
The pressable should be focused on Android like it is on the Web.

## Snack, code example, screenshot, or link to a repository:
https://snack.expo.dev/@jerrybels/frisky-waffle

**Comment by VijayentKohli** [comment]
Have you tried using this `setaccessibilityfocus` ? 
refer - https://reactnative.dev/docs/accessibilityinfo#setaccessibilityfocus

**Comment by JerryBels** [comment]
> Have you tried using this `setaccessibilityfocus` ? refer - https://reactnative.dev/docs/accessibilityinfo#setaccessibilityfocus

Already tried it, and here you go with a modified snack using it : https://snack.expo.dev/@jerrybels/vigorous-cereal still doesn't work on Android.
