### ISSUE TITLE
[Animated] spring.onComplete function?

### ISSUE THREAD

**Issue by phongyewtong** [facebook/react-native#3212]
If there is a callback for on spring animation complete will be great.

**Comment by browniefed** [comment]
```
this.animateValue.spring({}).start(function onComplete() {})
```
The start call takes a function that is called on complete.

**Comment by ide** [comment]
Thanks @browniefed 😀

**Comment by nthtran** [comment]
Document this?

**Comment by creeperyang** [comment]
Found documention here <https://facebook.github.io/react-native/docs/animated.html#working-with-animations>.

However, it's not easy to discover immdiately. I found it after I found this issue.
