### ISSUE TITLE
When will the @ReactProp Annotation be available?

### ISSUE THREAD

**Issue by lalith26** [facebook/react-native#3214]
Hello

I see that the source code showing the usage of @ReactProp annotation in Managers while exposing Native UI components to re render when there is a change in props. I am using react-native 0.11.4. This annotation is yet not available in  'com.facebook.react.uimanager' package. Will there be a separate release of react-native to support this?

**Comment by chirag04** [comment]
@lalith26 you can build from source till then i guess. support for it just landed on master.

**Comment by mikearmstrong001** [comment]
@lalith26 are you able to close this now ?

**Comment by lalith26** [comment]
@mikearmstrong001 I am still using the updateView method(). So, it should be fine for now.
