### ISSUE TITLE
App crash when launch on Android

### ISSUE THREAD

**Issue by daiquangduy** [facebook/react-native#32141]
System:
    OS: macOS 11.2.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
    Memory: 64.13 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 15.14.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 7.7.6 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 23, 26, 28, 29, 30
      Build Tools: 23.0.1, 23.0.3, 25.0.3, 26.0.1, 26.0.2, 28.0.3, 29.0.2, 29.0.3, 30.0.2
      System Images: android-28 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_242 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.2 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
    
    
    
    "@react-navigation/bottom-tabs": "^6.0.0",
    "@react-navigation/material-top-tabs": "^6.0.0",
    "@react-navigation/native": "^6.0.0",
    "@react-navigation/stack": "^6.0.0",
    "react-native-gesture-handler": "^1.10.3",
    
    FATAL EXCEPTION: mqt_native_modules
    Process: xx.xx.xx, PID: 24717
09-03 08:46:22.801 24717 24770 E AndroidRuntime: com.facebook.react.bridge.UnexpectedNativeTypeException: Value for right cannot be cast from String to Double
09-03 08:46:22.801 24717 24770 E AndroidRuntime: 	at com.facebook.react.bridge.ReadableNativeMap.checkInstance(ReadableNativeMap.java:4)
09-03 08:46:22.801 24717 24770 E AndroidRuntime: 	at com.facebook.react.bridge.ReadableNativeMap.getValue(ReadableNativeMap.java:5)
09-03 08:46:22.801 24717 24770 E AndroidRuntime: 	at com.facebook.react.bridge.ReadableNativeMap.getDouble(ReadableNativeMap.java:1)
09-03 08:46:22.801 24717 24770 E AndroidRuntime: 	at com.swmansion.gesturehandler.react.RNGestureHandlerModule.handleHitSlopProperty(RNGestureHandlerModule.java:14)
09-03 08:46:22.801 24717 24770 E AndroidRuntime: 	at com.swmansion.gesturehandler.react.RNGestureHandlerModule.access$000(RNGestureHandlerModule.java:1)
09-03 08:46:22.801 24717 24770 E AndroidRuntime: 	at com.swmansion.gesturehandler.react.RNGestureHandlerModule$d.b(RNGestureHandlerModule.java:6)
09-03 08:46:22.801 24717 24770 E AndroidRuntime: 	at com.swmansion.gesturehandler.react.RNGestureHandlerModule$g.f(RNGestureHandlerModule.java:1)
09-03 08:46:22.801 24717 24770 E AndroidRuntime: 	at com.swmansion.gesturehandler.react.RNGestureHandlerModule$g.b(RNGestureHandlerModule.java:1)
09-03 08:46:22.801 24717 24770 E AndroidRuntime: 	at com.swmansion.gesturehandler.react.RNGestureHandlerModule.createGestureHandler(RNGestureHandlerModule.java:9)
09-03 08:46:22.801 24717 24770 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-03 08:46:22.801 24717 24770 E AndroidRuntime: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:18)
09-03 08:46:22.801 24717 24770 E AndroidRuntime: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:2)
09-03 08:46:22.801 24717 24770 E AndroidRuntime: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
09-03 08:46:22.801 24717 24770 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
09-03 08:46:22.801 24717 24770 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
09-03 08:46:22.801 24717 24770 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:1)
09-03 08:46:22.801 24717 24770 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
09-03 08:46:22.801 24717 24770 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:8)
09-03 08:46:22.801 24717 24770 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:919)

**Comment by 452MJ** [comment]
`Value for right cannot be cast from String to Double`

Check to see if this line of `right: '100'` is written in your style

**Comment by daiquangduy** [comment]
> `Value for right cannot be cast from String to Double`
> 
> Check to see if this line of `right: '100'` is written in your style

Thank you for response.
But I don't have any line has value of right is string.
It working on iOS and just crash on Android

**Comment by OkancanCosar** [comment]
09-03 08:46:22.801 24717 24770 E AndroidRuntime: com.facebook.react.bridge.UnexpectedNativeTypeException: Value for right cannot be cast from String to Double
should give you a clue

**Comment by daiquangduy** [comment]
> 09-03 08:46:22.801 24717 24770 E AndroidRuntime: com.facebook.react.bridge.UnexpectedNativeTypeException: Value for right cannot be cast from String to Double
> should give you a clue

I aslo hope that.
But I can't find any style has value of right is string :(

**Comment by OkancanCosar** [comment]
In such cases, it may be more useful to move delete component one by one.

**Comment by cortinico** [comment]
Closing as it's impossible to reproduce without a reproducer. Feel free to reopen if the issue persists.
