### ISSUE TITLE
<TextInput /> break line without focus on IOS after defined characters

### ISSUE THREAD

**Issue by rybyakovigor** [facebook/react-native#32150]
## Description
If there are more characters in the <TextInput /> than can be displayed on the screen and there are characters in the line: dot, forward slash, backslash or space, then if the focus is lost, the field will transfer all characters to a new line.

## React Native version:
System:
    OS: macOS 11.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 404.05 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.22.1 - ~/.nvm/versions/node/v12.22.1/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 6.14.12 - ~/.nvm/versions/node/v12.22.1/bin/npm
    Watchman: 2021.08.02.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 29, 30, 31
      Build Tools: 29.0.2, 31.0.0
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7583922
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce

https://user-images.githubusercontent.com/55053069/132096846-0150a393-0ab6-4d47-b1a1-bb36df16e23d.mp4

**Comment by ArtKuz** [comment]
Problem unsolved

**Comment by HacerBusraKILIC** [comment]
I have same problem with Text component in IOS. Android continues on the same line. Any solution?
