### ISSUE TITLE
Does this template bundle Flipper in release? 

### ISSUE THREAD

**Issue by henrymoulton** [facebook/react-native#32153]
https://github.com/react-native-community/react-native-template-typescript/blob/master/template/ios/HelloWorld/AppDelegate.m#L7

https://github.com/react-native-community/react-native-template-typescript/blob/master/template/ios/HelloWorld/AppDelegate.m#L7

In the main docs the #ifdef FB_SONARKIT_ENABLED is wrapped with #if DEBUG

https://fbflipper.com/docs/getting-started/react-native-ios#initialization

**Comment by safaiyeh** [comment]
I raised a PR for this in the past https://github.com/facebook/react-native/pull/29646

Conclusion is that we dont want to add if DEBUG, best to add it yourself if you need it

**Comment by cortinico** [comment]
> Conclusion is that we dont want to add if DEBUG, best to add it yourself if you need it

Thanks for the clarification. Can we close this issue and the related PR #29646 then @safaiyeh ?

**Comment by henrymoulton** [comment]
I agree with the principle (maybe it can be refactored) but disagree with this conclusion, cc @alloy, I think we should try to align with the Flipper docs first and foremost, if the Flipper team think there should be changes (cc @mweststrate) they will be in the best place to make sure the RN template and the Flipper guidance is aligned.

**Comment by mweststrate** [comment]
I think `FB_SONARKIT_ENABLED` should already be only set in DEBUG, but allows for more fine grained control then just DEBUG? But tbh I'm not sure where FB_SONARKIT_ENABLED is defined atm inside React Native :)
