### ISSUE TITLE
Can't find node binary because we don't  have $RN_DIR at version 0.65

### ISSUE THREAD

**Issue by listenzz** [facebook/react-native#32168]
Something wrong in `react-native-xcode.sh`.

## Description
Can't find node binary because we don't  have $RN_DIR definition in  `react-native-xcode.sh`

## React Native version:
0.65 or 0.65.1

## Snack, code example, screenshot, or link to a repository:

```sh
# Find path to Node
# shellcheck source=/dev/null
source "$RN_DIR/scripts/find-node.sh"

# check and assign NODE_BINARY env
# shellcheck source=/dev/null
source "$REACT_NATIVE_DIR/scripts/node-binary.sh"
```

Replace $RN_DIR with $REACT_NATIVE_DIR, everything is OK.

**Comment by DanijelBojcic** [comment]
I had the same issue,I have updated react-native like a week ago, and it was working, Today ios build suddenly started to fail.

The problem is that `$RN_DIR` variable doesn't exist in `node_modules/react-native/scripts/react-native-xcode.sh`, so it fails to read a path.

As a **workaround** you can add the following line to `Build Phases`-> `Bundle React Native code and images`:
```
export RN_DIR="$(cd "./node_modules/react-native" && pwd)" // <-- add this
./node_modules/react-native/scripts/react-native-xcode.sh
```

**Comment by gabrielmoncea** [comment]
This worked for me too.
I've replaced `$RN_DIR` with `$REACT_NATIVE_DIR` and also removed `export NODE_BINARY=node` from `Build Phases` -> `Bundle React Native code and images`

**Comment by botevst** [comment]
```
--- ./node_modules/react-native/scripts/react-native-xcode.sh	2021-10-09 02:10:24.000000000 +0200
+++ ./node_modules/react-native/scripts/react-native-xcode.sh	2021-10-09 02:32:09.000000000 +0200
@@ -81,7 +81,7 @@
 
 # Find path to Node
 # shellcheck source=/dev/null
-source "$RN_DIR/scripts/find-node.sh"
+source "$REACT_NATIVE_DIR/scripts/find-node.sh"
 
 # check and assign NODE_BINARY env
 # shellcheck source=/dev/null

```
