### ISSUE TITLE
TypeError: expected dynamic type double but had type string react native

### ISSUE THREAD

**Issue by pickhardt** [facebook/react-native#3216]
This issue seems like https://github.com/facebook/react-native/issues/2983 and https://github.com/facebook/react-native/issues/2855 however it's slightly different wording.

I've read both of those issues now and can't understand what the fix is. For instance, the fix says to move a folder called ReactAndroid into your project folder and adding it to settings.gradle. But where is this ReactAndroid folder? I don't see it.

I am on React Native 0.11.4 and can't simply use 0.12.0-rc (assuming that would fix it...) because upgrading to -rc breaks other libraries (I get errors like "Peer react-native-fbsdklogin@0.0.4 wants react-native@>=0.8.0")

![TypeError: expected dynamic type double but had type string react native](https://cloud.githubusercontent.com/assets/610082/10265428/ad9f1932-69e4-11e5-8770-eadb0d00f673.png)

**Comment by satya164** [comment]
Closing this. Let's reopen if this still happens.

**Comment by julesmoretti** [comment]
Getting same error on Android with:
```
    "react": "16.0.0-alpha.6",
    "react-native": "^0.44.0"
``` 

The elements I have tied to my app are:
```
  StyleSheet,
  View,
  Text,
  PanResponder,
  Animated,
  Dimensions,
  ScrollView,
  TouchableOpacity,
```

**Comment by julesmoretti** [comment]
Seems to be specific to `TouchableOpacity`

**Comment by hzyIO** [comment]
@julesmoretti @satya164 

I'm actually getting this error as well, but its for an Animation. Working great on iOS.
![image](https://user-images.githubusercontent.com/192363/29640945-1f7eab02-8816-11e7-9556-7c892ba66228.png)

**Comment by kantharia** [comment]
@hzyIO - I am having same issue; works on iOS but giving error on Android

**Comment by natakina** [comment]
I have the same error. It happens when I rotate elements and then click on them. One element is the switcher of camera (react-native-camera), another one - go back arrow from react-navigation.

**Comment by adesmet** [comment]
Also experiencing this issue, seems to be on this line:

        StaticTransformConfig transformConfig = new StaticTransformConfig();
        transformConfig.mProperty = property;
        transformConfig.mValue = transformConfigMap.getDouble("value");

When fetching a rotation value, it fails because the rotation value is a string (like '10deg') instead of a double.

Still thinking about a solution that doesn't involve changing react-native itself.

**Comment by natakina** [comment]
Wrap the element in a View and rotate this view, not element.

**Comment by adesmet** [comment]
@natakina you are a god among men, it works perfectly.

**Comment by cihanbas** [comment]
@natakina  yes all Right thank you for perfect answer

**Comment by ahmad2smile** [comment]
These sort of discontinuous implementations is really annoying when you develop iOS firs then check on Android.

**Comment by ahmad2smile** [comment]
These sort of incoherent implementations is really annoying when you develop iOS firs then check on Android.
