### ISSUE TITLE
Mixpanel iphone native modules not registered error

### ISSUE THREAD

**Issue by tehong** [facebook/react-native#3217]
I've encountered the following run-time error when trying to port the mixpanel-iPhone (https://github.com/mixpanel/mixpanel-iphone.git) code by wrapping that in an objective-C class:

**Error: Invariant Violation: Application RNMixpanel has not been registered. This is either due to a require() error during initialization or failure to call AppRegistry.registerComponent.**

I don't know much of Objective-C but creating a wrapper seemed simple enough so I wanted a give it a try (I've already successfully coded against Mixpanel HTTP API in React Native JS but I would like to get the mixpanel native module working since that gives me much more data) .   

So here are the .h and .m files of my wrapper:

------ RNMixpanel.h  
```
#import  "RCTBridge.h"
@interface RNMixpanel : NSObject <RCTBridgeModule>
@end
```

------ RNMixpanel.m

```
#import "RNMixpanel.h"
#import "Mixpanel.h"

@implementation RNMixpanel

// Expose this module to the React Native bridge
RCT_EXPORT_MODULE(RNMixpanel)
// I also tried RCT_EXPORT_MODULE() and RCT_EXPORT_MODULE("RNMixpanel") as well and resulted in the same error

// sharedInstanceWithToken
RCT_EXPORT_METHOD(sharedInstanceWithToken:(NSString *)apiToken) {
  NSLog(@"%@ %@", NSStringFromClass([self class]), NSStringFromSelector(_cmd));
}

// sharedInstance
RCT_EXPORT_METHOD(sharedInstance) {
  NSLog(@"%@ %@", NSStringFromClass([self class]), NSStringFromSelector(_cmd));
}

// track event
RCT_EXPORT_METHOD(track:(NSString *)event) {
  NSLog(@"%@ %@", NSStringFromClass([self class]), NSStringFromSelector(_cmd));
}

// track event with properties
RCT_EXPORT_METHOD(track:(NSString *)event properties:(NSDictionary *)properties) {
  NSLog(@"%@ %@", NSStringFromClass([self class]), NSStringFromSelector(_cmd));
}

static Mixpanel *mixpanel = nil;

+ (RNMixpanel *)sharedInstanceWithToken:(NSString *)apiToken
{
  return (RNMixpanel *) [Mixpanel sharedInstanceWithToken:apiToken];
}

+ (RNMixpanel *)sharedInstance
{
  mixpanel = [Mixpanel sharedInstance];
  return (RNMixpanel *)mixpanel;
}

+ (void)track:(NSString *)event
{
  [mixpanel track:event];
}

+ (void)track:(NSString *)event properties:(NSDictionary *)properties
{
  [mixpanel track:event properties:properties];
}

@end
```

And here is the start of my index.ios.js file:

------ index.ios.js

```
var React = require('react-native');
var Mixpanel = require('react-native').NativeModules.RNMixpanel;

var {
  Text,
  View,
  TouchableHighlight,
  AppRegistry,
  StyleSheet,
} = React;

var StopWatch = React.createClass({
.
.
.

AppRegistry.registerComponent('stopwatch', () => StopWatch);

```

Everything compiled fine.  The error only showed up at the run time.

It is not clear to me what I did wrong in the .h and .m files but the RNMixpanel is not registered as Native Component correctly.

**Comment by satya164** [comment]
Is the app registered with `AppRegistry.registerComponent`?

**Comment by tehong** [comment]
You're talking about the AppRegistry in the index.ios.js file, right?  This is a simple stopwatch app that is working with Mixpanel HTTP API already.  I am trying to convert to calling Mixpanel Obj-C code as RN Native Component.  I have the AppRegistry code at the bottom of my app in the index.ios.js file:

```
AppRegistry.registerComponent('stopwatch', () => StopWatch);

```

**Comment by tehong** [comment]
OK.  I've started from scratch and created a new RN project and then put the Mixpanel code in.  The error went away.  So it maybe that when I experimented with the mixpanel code, I screwed up something.  In any case, I've got is working with this revise RNMixpanel.m:

```
#import "RNMixpanel.h"
#import "Mixpanel.h"

@implementation RNMixpanel

Mixpanel *mixpanel = nil;
 
// Expose this module to the React Native bridge
RCT_EXPORT_MODULE(RNMixpanel)

// sharedInstanceWithToken
RCT_EXPORT_METHOD(sharedInstanceWithToken:(NSString *)apiToken) {
  
  NSLog(@"%@ %@", NSStringFromClass([self class]), NSStringFromSelector(_cmd));
  
  [Mixpanel sharedInstanceWithToken:apiToken];
  mixpanel = [Mixpanel sharedInstance];

}


// track

RCT_EXPORT_METHOD(track:(NSString *)event) {
  
  NSLog(@"%@ %@", NSStringFromClass([self class]), NSStringFromSelector(_cmd));
  [mixpanel track:event];
  [mixpanel flush];
  
}

// track with properties

RCT_EXPORT_METHOD(trackWithProperties:(NSString *)event properties:(NSDictionary *)properties) {
  
  NSLog(@"%@ %@", NSStringFromClass([self class]), NSStringFromSelector(_cmd));
  [mixpanel track:event properties:properties];
  [mixpanel flush];
  
}
```

**Comment by tehong** [comment]
There are few things that needed attention as well:

1. You need to import the libicucore.tbd in the your target "Build Phases" by doing "Build Phases" => "Link Binary With Libraries" => + => and type in the libicucore and then select "libicucore.tbd".

2. It seems that [mixpanel flush] is needed in the code or else "code '1001' reason 'Stream end encountered" will stop the mixpanel data from sending out.  It seems that that Mixpanel's delayed flush with interval would encounter some empty buffer and causes this problem.

3. The mixpanel can work on both iOS simulator and the device but to run on the device, the usual artifacts of running on device needed to be taken care of such as:
   a. Need to modify the localhost in the AppDelegte.m's "jsCodeLocation" to your PC's IP address.
   b. To debug in Chrome's DevTool, you also need to modify the hardcoded "localhost" in RCTWebSocketExecutor.m as seen here: https://github.com/facebook/react-native/issues/883.

4. Sample usages in index.ios.js:

// import the RNMixpanel native modules
var Mixpanel = require('react-native').NativeModules.RNMixpanel;

// Your Mixpanel token is here
var MP_TOKEN = 'YOUR_MIXPANEL_TOKEN_HERE';

// init the Mixpanel
Mixpanel.sharedInstanceWithToken(MP_TOKEN);

// track Mixpanel event
Mixpanel.track('App Launch');

/./ track mixpanel event with properties
Mixpanel.trackWithProperties(
      'App Launch',
      { 'App': 'App Launch' }
    );
