### ISSUE TITLE
Cryptic clang errors and linking complaints when compiling existing and working app for first time on iOS

### ISSUE THREAD

**Issue by Ben-Owen-3183** [facebook/react-native#32173]
So I have an app that I have been working on for a far few months now. I developed it on Ubuntu and tested on my android phone and tablet. The app is setup using the basic react native library and I also added in expo later on for some little thing expo had that I needed. I am now trying to get the app built on **iOS** for the first time.

It has been nearly a week now and I just cannot move past this error (see bottom) (or variations of what seem to be the same/similar errors). I can build a fresh app on this mac so everything is there to build react native apps. I have tried: Deleting pod and and running

`pod install`

running
`
pod deintegrate && pod install`

deleting node modules and running

`npm install`

Initially I had an error complaining that some libraries were manually linked and this was bad so I unlinked them which I thought was a 6.0> that thing, but I am on 5.0.1

`npx react-native run-ios` results in the same errors as xcode build

Using different simulators makes no difference...not sure if it is even getting that far in the build process for that to matter. I think this has something to do with the linking of RN libraries and this new auto link thing. Any thoughts? There are loads of posts with this error (or close to) that have all sorts of 'solutions', but none seem to make a difference. Overwhelmingly peoples solve this by pod install after deleting pod folder or running the `pod deintegrate` command. 

**Error:**
```
Undefined symbols for architecture x86_64:
  "_OBJC_METACLASS_$_UMAppDelegateWrapper", referenced from:
      _OBJC_METACLASS_$_AppDelegate in AppDelegate.o
  "_OBJC_CLASS_$_UMAppDelegateWrapper", referenced from:
      _OBJC_CLASS_$_AppDelegate in AppDelegate.o
  "_OBJC_CLASS_$_UMModuleRegistryProvider", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_UMModuleRegistryAdapter", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Also, my library folder is empty. I noticed other RN projects are not when looking at screen grabs. Possible problem?

podfile (think this could also be source) **https://pastebin.com/5J7BbG2Q**

I am seriously looking for some help to get this app built in iOS.

**Comment by Panda-ref** [comment]
Most likely, the issue comes from Expo unimodules check their GH

**Comment by Ben-Owen-3183** [comment]
> Most likely, the issue comes from Expo unimodules check their GH

GH?

**Comment by Panda-ref** [comment]
Sorry, GitHub. Check https://github.com/expo/expo/issues
