### ISSUE TITLE
[FormData] formdata object could not destructuring

### ISSUE THREAD

**Issue by KingAmo** [facebook/react-native#32182]
## Description

follow the [example](https://github.com/facebook/react-native/blob/1465c8f3874cdee8c325ab4a4916fda0b3e43bdb/Libraries/Network/FormData.js#L32)
```
 var photo = {
      uri: uriFromCameraRoll,
     type: 'image/jpeg',
     name: 'photo.jpg',
   };
 
   var formData = new FormData();
   formData.append('authToken', 'secret');
   formData.append('photo', photo);
   formData.append('title', 'A beautiful photo!');
 ```
and when i use it like this:
```
    fetch('https://example.upload', {
      body: {...formData, customValue: 123},
      method: 'POST',
    });
```

upload failed, and Charles shows the request Content-Length is `0`

i change to use it like this:
```
    formData.customValue = 123;
    fetch('https://example.upload', {
      body: formData,
      method: 'POST',
    });
```
upload success! Charles show correct Content-Length
## React Native version:
Run `react-native info` in your terminal and copy the results here.
```
System:
    OS: macOS 11.5.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 37.87 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.19.0 - /usr/local/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 7.22.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 21, 23, 25, 26, 27, 28, 29, 30
      Build Tools: 23.0.1, 26.0.1, 26.0.2, 27.0.3, 28.0.3, 29.0.2
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7678000
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_212 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.2 => 17.0.2
    react-native: ^0.64.1 => 0.64.1
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.
2.

## Expected Results

formdata can be destructuring

## Snack, code example, screenshot, or link to a repository:
Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by b3coded** [comment]
@KingAmo if you want to send an custom value using FormData, you should use `formData.append('customValue', 123)`

About the spread operator [check this response](https://stackoverflow.com/a/58058608/11686634) on StackOverflow
