### ISSUE TITLE
Error: could not find 'adb'. Specifically, 'which adb' was empty.

### ISSUE THREAD

**Issue by hepalem** [facebook/react-native#32187]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Error: could not find 'adb'. Specifically, 'which adb' was empty.

## React Native version:
v0.65.1

**Comment by cortinico** [comment]
> Error: could not find 'adb'. Specifically, 'which adb' was empty.

Closing as this is not related to React Native.

We have a guide on how to setup the Android SDK here https://reactnative.dev/docs/environment-setup#installing-dependencies

You anyway need to have `adb` inside your `PATH` to be able to build a React Native project.
