### ISSUE TITLE
AwesomeProject not working on Apple M1

### ISSUE THREAD

**Issue by nachocifu** [facebook/react-native#32188]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
New Apple M1 unboxed today has issues with cocopoads.

## React Native version:
System:
    OS: macOS 11.5.2
    CPU: (8) arm64 Apple M1
    Memory: 545.78 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.9.0 - /opt/homebrew/bin/node
    Yarn: Not Found
    npm: 7.21.1 - /opt/homebrew/bin/npm
    Watchman: 2021.08.30.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.65.1 => 0.65.1
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.
Followed the steps to create AwesomeProject. https://reactnative.dev/docs/environment-setup

1. brew install node
2. brew install watchman
3. sudo gem install cocoapods
4. 4. npx react-native init AwesomeProject

## Expected Results
Success creating awesome project.

## Snack, code example, screenshot, or link to a repository:
<img width="765" alt="image" src="https://user-images.githubusercontent.com/9084141/132991541-057b2a95-ee56-45ed-aeb9-cebc42d70518.png">
When manually executing `pod install` I get the following result followed by a stack trace.
<img width="873" alt="image" src="https://user-images.githubusercontent.com/9084141/132991661-12079beb-cf29-4f85-9afa-617182ef7698.png">

**Comment by wasteCleaner** [comment]
The same problem
stupid bullshit like: `sudo xcode-select --switch /Applications/Xcode.app` - doesn't help

**Comment by Navipro70** [comment]
Maybe this link helps https://dev.to/staceypyee/installing-cocoapods-on-m1-macbook-air-big-sur-h0l
