### ISSUE TITLE
Examples - Movies thumbnails are not changed on filter

### ISSUE THREAD

**Issue by cupofjoakim** [facebook/react-native#322]
When using the filter/search in the examples app, the thumbnail icons aren't correct. After selecting a movie to see the details, the image is however correct. This inconsistency makes the example feel broken, which leads to the framework looking iffy.

![screen shot 2015-03-27 at 09 31 49](https://cloud.githubusercontent.com/assets/2109753/6864597/2f6ba06e-d464-11e4-9845-77d733ee42be.png)
![screen shot 2015-03-27 at 09 32 05](https://cloud.githubusercontent.com/assets/2109753/6864596/2f6b1342-d464-11e4-8c86-8a7f8ec45a71.png)

**Comment by vjeux** [comment]
cc @a2

**Comment by brentvatne** [comment]
Dup of #89
