### ISSUE TITLE
 EventEmitter.removeListener('change', ...): Method has been deprecated. Please instead use `remove()` on the subscription returned by `EventEmitter.addListener`. 

### ISSUE THREAD

**Issue by gerfisher** [facebook/react-native#32203]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Please provide a clear and concise description of what the bug is. Include screenshots if needed.
Please test using the latest React Native release to make sure your issue has not already been fixed: https://reactnative.dev/docs/upgrading.html

## React Native version:
Run `react-native info` in your terminal and copy the results here.

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.
2.

## Expected Results
Describe what you expected to happen.

## Snack, code example, screenshot, or link to a repository:
Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by kkkorez** [comment]
after upgrading "@react-navigation/native" to "5.9.8" the issue was resolved. Please check the issue you are getting from which package it is, and then try to update the package to see if the issue is fixed.

**Comment by yehyaumar** [comment]
I'm still facing this issue. My @react-navigation/native version is "^6.0.4". I don't know what's causing it?

**Comment by ca057** [comment]
@yehyaumar Check if you’re using something like `AppState` or `BackHandler` somewhere in your app and change it so it uses the new `remove`-method on the returned subscription-object (https://reactnative.dev/docs/appstate#removeeventlistener).

**Comment by bradzickafoose** [comment]
I was having a similar issue, however, whenever I updated my side effects to use the `.remove()` method, TypeScript says, 
> Property 'remove' does not exist on type 'void'.ts(2339)

<img width="810" alt="Screen Shot 2021-09-29 at 11 51 47 AM" src="https://user-images.githubusercontent.com/4572314/135304760-27a5114d-dd1d-48af-8ca3-cde0116bc7ad.png">

Any idea of what I can do to make TS happy?

**Comment by ca057** [comment]
> I was having a similar issue, however, whenever I updated my side effects to use the `.remove()` method, TypeScript says,
> 
> > Property 'remove' does not exist on type 'void'.ts(2339)
> 
> <img alt="Screen Shot 2021-09-29 at 11 51 47 AM" width="810" src="https://user-images.githubusercontent.com/4572314/135304760-27a5114d-dd1d-48af-8ca3-cde0116bc7ad.png">
> 
> Any idea of what I can do to make TS happy?

Have you updated to the latest types of React Native? `@types/react-native@0.65.1` works for me.

**Comment by bradzickafoose** [comment]
@ca057 That fixed it. Thanks for the help!

**Comment by douglowder** [comment]
The `Appearance` module in 0.66.3 seems to also be calling the deprecated method.

**Comment by DeepBlueDevOps** [comment]
Any status on a fix/patch? I am having the same issue. Deprecated call coming from both Appearance.js and Dimensions.js. React-native ver is: 0.67.2

**Comment by AhmedAbuelenin** [comment]
Having the same warning in react-native 0.67.3

**Comment by rlam3** [comment]
> > I was having a similar issue, however, whenever I updated my side effects to use the `.remove()` method, TypeScript says,
> > > Property 'remove' does not exist on type 'void'.ts(2339)
> > 
> > 
> > <img alt="Screen Shot 2021-09-29 at 11 51 47 AM" width="810" src="https://user-images.githubusercontent.com/4572314/135304760-27a5114d-dd1d-48af-8ca3-cde0116bc7ad.png">
> > Any idea of what I can do to make TS happy?
> 
> Have you updated to the latest types of React Native? `@types/react-native@0.65.1` works for me.

I'm curious to know if you were able to unit test this? It seems like there is no straightforward way to simulate a user changing state from foreground to background.
