### ISSUE TITLE
Upgrading to RN 0.65.1 causes Jest to fail with TypeError: _reactNative.Keyboard.emit is not a function

### ISSUE THREAD

**Issue by sabun123** [facebook/react-native#32217]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
After upgrading to React Native 0.65.1, Jest fails with tests that use certain React Native functionality. The errors it throws when failing:
```JavaScript
 TypeError: _reactNative.Keyboard.emit is not a function
```
```JavaScript
 TypeError: _reactNative.AppState.removeEventListener is not a function
```

Additionally, other tests are now suddenly failing with the following as well:
```JavaScript
thrown: "Exceeded timeout of 5000 ms for a hook.
Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."
```

## React Native version:
0.65.1 (coming from 0.64.2)

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Come from React Native 0.64.2 and upgrade to RN 0.65.1
2. Run Jest and use functionality from the React Native package
3. Watch Jest fail being unable to identify the React Native functionality 

## Expected Results
These Jest tests worked and all PASS in 0.64.2. The only change is upgrading to 0.65.1 to cause this to fail.

## Unit test Jest code example
```JavaScript
import { render } from '@testing-library/react-native';
import React from 'react';
import { Keyboard } from 'react-native';
import TestComponent from '../TestComponent';

describe('screens/testscreen/TestComponent', () => {
 it('renders correctly', () => {
    const setup = render(<TestComponent />);
    expect(setup).toBeTruthy();
    
    act(() => {
      Keyboard.emit('keyboardDidShow', {});
      Keyboard.emit('keyboardDidHide', {});
    });
  });
});
```

What can I try to get this working again, or is React Native 0.65.1 broken in this regard?

**Comment by sabun123** [comment]
This looks like an issue brought on by the fact that both `Keyboard` and `AppState` have been fundamentally changed in React Native. This is a breaking change, whereby they no longer inherit from `NativeEventEmitter` causing a loss of functionality, for the sake of simplification.

![image](https://user-images.githubusercontent.com/3523483/134292726-3a4d71d6-629c-44f9-945a-6b6c30384f3c.png)

This is definitely going to break other libraries that depend on this, I foresee `react-native-background-timer` will break in RN 0.65 onwards due to this as well.

How do we go about testing `Keyboard` without the ability to emit?

**Comment by sabun123** [comment]
Hey @yungsters, since you worked on this change do you have any propositions for those of us who need the emit functionality whilst jest testing our apps?

**Comment by yungsters** [comment]
I apologize for this undocumented breaking change. Thanks for reporting it.

In Jest tests, can you instead emit the event on `RCTDeviceEventEmitter`? This would be closer to mocking behavior from the native platform in production. (Ideally, we would have better facilities or mocking platform behaviors in Jest.) Let me know if that works.

`AppState.removeEventListener` should still exist, though. It is deprecated, but it has not been removed, yet.

**Comment by yungsters** [comment]
Thanks for the detailed summary, @sabun123!

I do wonder why `AppState.removeEventListener` isn’t working for you, though. Hmm…

Nonetheless, best to migrate away from it since it is deprecated and will be removed in the future.
