### ISSUE TITLE
After upgrading to v0.65.1 i get the following warning on iOS. EventEmitter.removeListener('url', ...): Method has been deprecated. Please instead use `remove()` on the subscription returned by `EventEmitter.addListener`. 

### ISSUE THREAD

**Issue by kkkorez** [facebook/react-native#32216]
## Description
This warning appeared after upgrading from react native 0.64.2 to 0.65.1

## React Native version:
```
info Fetching system and libraries information...
System:
    OS: macOS 11.5.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 50.48 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
    Yarn: 1.19.1 - ~/.yvm/versions/v1.19.1/bin/yarn
    npm: 6.12.1 - ~/.nvm/versions/node/v12.13.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 23, 26, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2
      System Images: android-26 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_212 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: 5.0.1 => 5.0.1
    react: 17.0.2 => 17.0.2
    react-native: 0.65.1 => 0.65.1
    react-native-macos: Not Found
  npmGlobalPackages:

```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. create a debug build
2. run the app on simulator
3. enable debug mode

## Expected Results
Not throw any warning

## Snack, code example, screenshot, or link to a repository:
![Screenshot 2021-09-15 at 6 14 56 PM](https://user-images.githubusercontent.com/72015937/133460843-cb9109d8-027b-4735-9c36-071d9ee2a5fd.png)

**Comment by vinitsood** [comment]
I am experiencing this too. Here is how my Simulator looks whenever I refresh 
![Screenshot 2021-09-17 at 13 21 18](https://user-images.githubusercontent.com/1384560/133774385-88940748-11fb-403b-a850-87a4be22f2d1.png)

**Comment by DrOverbuild** [comment]
The API for EventEmitter has changed. `addListener` will now return a subscription object. And when you are removing the listener, you will call `remove()` on the returned subscription object. An example of this usage is in [AppState](https://reactnative.dev/docs/appstate#addeventlistener). This is a new change in 0.65.

This is how it is used now:

```javascript
useEffect(() => {
  const subscription = AppState.addEventListener("change", nextAppState => { ... });
      
  return () => {
    subscription.remove();
  };
}, []);
```

**Comment by zuccha** [comment]
> ```js
> ppState.addEventListener
> ```

Yet the method signature for `AppState.addEventListener` has `void` as return type.

**Comment by DrOverbuild** [comment]
> Yet the method signature for `AppState.addEventListener` has `void` as return type.

@zuccha [This line](https://github.com/facebook/react-native/blob/88021894f2645266d7e1b0a2e61a737b1590d039/Libraries/EventEmitter/NativeEventEmitter.js#L77) in the source code shows that the method signature in `EventEmitter` has been updated to reflect the changes.

And if you're using Typescript, [this line](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/819ab78209056a8aca6de8df70b87d3b761d19a3/types/react-native/index.d.ts#L198) in the type declarations shows that it's been updated too. You may want to check that the types declarations are updated.

**Comment by kkkorez** [comment]
@DrOverbuild As I can see from the logs this is happening due to react-navigation package, on my code I have commented all the addEventListener/removeListener methods and I still get the warning. I can see many issues open on react-navigation related to this issue, does anyone else has the same problem?

https://github.com/react-navigation/react-navigation/issues/9894
https://github.com/react-navigation/react-navigation/issues/9803

**Comment by kkkorez** [comment]
after upgrading "@react-navigation/native" to "5.9.8" the issue resolved

**Comment by yehyaumar** [comment]
I'm still facing this issue. My @react-navigation/native version is "^6.0.4". I don't know what's causing it?

**Comment by hadrienl** [comment]
Same error on BottomTabBar. I've patched it with patch-package : 
[react-navigation-tabs+2.11.1.patch](https://github.com/facebook/react-native/files/7258565/react-navigation-tabs%2B2.11.1.patch.txt)

**Comment by 1280103995** [comment]
> > 然而，方法签名`AppState.addEventListener`具有`void`作为返回类型。
> 
> @zuccha 源代码中的[这一行](https://github.com/facebook/react-native/blob/88021894f2645266d7e1b0a2e61a737b1590d039/Libraries/EventEmitter/NativeEventEmitter.js#L77)显示方法签名`EventEmitter`已更新以反映更改。
> 
> 如果您使用的是 Typescript，则类型声明中的[这一行](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/819ab78209056a8aca6de8df70b87d3b761d19a3/types/react-native/index.d.ts#L198)表明它也已更新。您可能需要检查类型声明是否已更新。

He indicated that it was the ```AppState``` class, not the ```NativeEventEmitter```class.
