### ISSUE TITLE
VirtualizedList: You have a large list that is slow to update - make sure your renderItem function renders components that follow React performance best practices like PureComponent, shouldComponentUpdate, etc.

### ISSUE THREAD

**Issue by angganix** [facebook/react-native#32222]
Please help, i have RN Application that fetch data to server paginately, every time scroll has end to bottom i call getMore function and get next offset to server then result of next offset i've been merged with list state 

1. On FlatList i've implement React PureComponent on Rendering ListItem but always have notice **VirtualizedList: You have a large list that is slow to update - make sure your renderItem function renders components that follow React performance best practices like PureComponent, shouldComponentUpdate, etc.**
2. I've implement any other performance options but nothing change
3. My data list scenario is fetching to api server that give partial or limit rows using cursor pagination by PRISMA JS, every i got EndReach bottom i call function **getMore** that will trigger to change cursor state and load more data from server then i merge that result on existing list

## Expected Results
How i can remove that warning ? 

`
          
    const Tags = () => {
    const navigation = useNavigation();
    const mounted = useRef(false);
    const [loader, setLoader] = useState(false);
    const [cursor, setCursor] = useState(0);
    const [list, setList] = useState([]);
    const renderItem = ({item}) => <ListItem title={item.tag} />;

    const getMore = () => {
        setCursor(list[list.length - 1].id);
    };

    useEffect(() => {
        mounted.current = true;

        const getList = async () => {
            try {
                setLoader(true);
                const data = await fetchList({cursor});
                setList(prevState => [...prevState, ...data]);
            } catch (error) {
                ToastAndroid.showWithGravity(error, 3000, ToastAndroid.BOTTOM);
            } finally {
                setTimeout(() => {
                    if (mounted.current) {
                        setLoader(false);
                    }
                }, 1000);
            }
        };

        getList();
    
        return () => {
          mounted.current = false;
        };
    }, [cursor]);

      return (
        <View style={styles.container}>
          <FlatList
            refreshing={loader}
            data={list}
            renderItem={renderItem}
            keyExtractor={item => item.id}
            ListEmptyComponent={NoData}
            showsVerticalScrollIndicator={false}
            ListFooterComponent={loader ? <MoreLoader /> : null}
            ItemSeparatorComponent={ListSeparator}
            onEndReachedThreshold={0.5}
            onEndReached={getMore}
          />
          <AddButton />
        </View>
      );
    };
    
    // List Component
     class ListItem extends PureComponent {
        render() {
          const {title} = this.props;
          return (
            <Pressable style={styles.container} android_ripple={rippleConfig}>
              <View style={styles.listIconWrapper}>
                <AntIcon name="folder1" style={styles.listIcon} />
              </View>
              <View style={styles.listContentWrapper}>
                <Text numberOfLines={2} ellipsizeMode="tail">
                  {title}
                </Text>
              </View>
            </Pressable>
          );
        }
      }

**Comment by NoerNova** [comment]
Any update on this?
I face the same issue similarly.

```javascript
const RenderCategoriesMenu = React.memo(({item}: {item: category}) => {
    return (
      <Menu.Item
        onPress={() => {}}
        title={item.categoryName}
        style={[
          styles.categoryItemContainer,
          {
            backgroundColor: colors.primary_light,
            borderColor: colors.primary_dark,
          },
        ]}
        titleStyle={[styles.categoryTitleStyle, {color: colors.text}]}
        contentStyle={styles.categoryItemContent}
      />
    );
  });
```

- **_quite sure this function is not over re-render_**

- **_warning does not show on comment/un-use this component, so the warning came from this component?_**

- **_My list contains about 20+ items, no performance issue found_**

**Comment by a-eid** [comment]
@NoerNova `React.memo` could be ( and most probably is ) useless the way you're using it, 

```tsx
const RenderCategoriesMenu = React.memo(({categoryName,categoryItemContent }: {categoryName: string, categoryItemContent: string}) => {
    return (
      <Menu.Item
        onPress={() => {}}
        title={categoryName}
        style={[
          styles.categoryItemContainer,
          {
            backgroundColor: colors.primary_light,
            borderColor: colors.primary_dark,
          },
        ]}
        titleStyle={[styles.categoryTitleStyle, {color: colors.text}]}
        contentStyle={categoryItemContent}
      />
    );
  });
```

**Comment by NoerNova** [comment]
Thank you very much @a-eid , I wrote a bunch of code like this, but now I remaking understand for best practices and fixed them, anyway **the warning is still there _but on IOS only_**, did I still miss something about this?

**Comment by a-eid** [comment]
> Thank you very much @a-eid , I wrote a bunch of code like this, but now I remaking understand for best practices and fixed them, anyway **the warning is still there _but on IOS only_**, did I still miss something about this?

sorry I totally didn't see you comment, you need to pass only `numbers` `strings` `booleans` to the component.

if you wanna pass an object you would need to implement the second argument to `React.memo` which compare the props.

**Comment by alielmajdaoui** [comment]
@a-eid @NoerNova please check https://github.com/facebook/react-native/issues/32924

**Comment by lfrallon** [comment]
Facing the same issue.

react-native: 0.69.4
react: 18.2.0

**Comment by Simba-Mupfunya** [comment]
Still no movement on this issue

**Comment by yourjhay** [comment]
I face this issue when there's an image inside my renderItem component even i'm using memo.

**Comment by pblab-dev** [comment]
updates?

**Comment by simoazzo** [comment]
> I face this issue when there's an image inside my renderItem component even i'm using memo.

Same here

**Comment by NoerNova** [comment]
> Any update on this? I face the same issue similarly.
> 
> ```js
> const RenderCategoriesMenu = React.memo(({item}: {item: category}) => {
>     return (
>       <Menu.Item
>         onPress={() => {}}
>         title={item.categoryName}
>         style={[
>           styles.categoryItemContainer,
>           {
>             backgroundColor: colors.primary_light,
>             borderColor: colors.primary_dark,
>           },
>         ]}
>         titleStyle={[styles.categoryTitleStyle, {color: colors.text}]}
>         contentStyle={styles.categoryItemContent}
>       />
>     );
>   });
> ```
> 
> * **_quite sure this function is not over re-render_**
> * **_warning does not show on comment/un-use this component, so the warning came from this component?_**
> * **_My list contains about 20+ items, no performance issue found_**


further looking back at my code, I found this component is defined inside another arrow function and it is the root cause of the warning.
Each time, when the parent component renders, a new instance of this function is created, and that throws the warning (I thought).

Instead of that, I split the code out and call like this

```javascript
const RenderCategoriesMenu = React.memo(({ item }) => {
  return <CategoryItem categoryName={item.categoryName} />;
});
```

and the warning's gone. ***It's been years for my case, but hope this may be helpful for anyone facing a situation like this***

**Comment by Rajsolanki7695** [comment]
still  show log same

**Comment by noahbuilds** [comment]
Facing similar issue

**Comment by noahbuilds** [comment]
> Facing similar issue

I just found a way around it, if you"re using a functional component, when exporting this component, wrap it inside React memo. What this does is that we are creating memoized functional components that bailout rendering unnecessary updates using shallow comparison of props.

**Comment by Rajsolanki7695** [comment]
can u explain code

**Comment by janusqa** [comment]
I just ran into this issue. I'm not using classes but functions so I opted to use memo.

My initial class looked like 
```ts
interface Props {
  prop1: MyShallowObject;
  prop2: string;
  prop3:string
}
const myComponent = ({prop1, prop2, prop3}:Props) => {
//
}
export default myComponent
```
In order for memo not to complain about display name I changed it to this, a regular non arrow function

```ts
interface Props {
  prop1: MyShallowObject;
  prop2: string;
  prop3:string
}
const myComponent = function myComponent({prop1, prop2, prop3}:Props)  {
//
}
export default myComponent
```

Then I memoized it using the memo second argument which is a comparison function that should return true if new props are the same as the old props

```ts
interface Props {
  prop1: MyShallowObject;
  prop2: string;
  prop3:string
}
const myComponent = memo(function myComponent({prop1, prop2, prop3}:Props)  {
//
}, 
(oldProps, newProps)=> (oldProps.prop2 === newProps.prop2 && oldProps.prop3 === newProps.prop3 && JSON.stringify(prop1) === JSON.stringify(newProps.prop1))

Some things to note
1. I do not like using memo often as it has it's own set of tradeoffs one of which is it takes resources to manage and track memos
2. without the second memo arg, the func if any of your props is an object then comparison will be done based on if the both objects have the same reference and not on the contents of the object. That may not work out too well for you.
3. I got around 2 by using the second argument to memo and by stringifying the object
4. In my case I had a simple object so I expect stringify to be fast.  The more complex the object the less performant stringify may be.

All in all the warning below has disappeared for me. (I am half expecting it to come back)
```
VirtualizedList: You have a large list that is slow to update - make sure your renderItem function renders components that follow React performance best practices like PureComponent, shouldComponentUpdate, etc.
```
)
export default myComponent
```

**Comment by SHYDEV-KR** [comment]
hi, any updates?

**Comment by ngminhkhoa** [comment]
Iust simple text and calculate margin and padding for ItemRow,maybe 400 items and I got this problem , imagine if i got a comlex layout ItemRow, that will be a nightmare for user, it appear when item up to 150 and above

**Comment by SKhun** [comment]
I solved this issue probably. The hint is official documents [here](https://reactnative.dev/docs/optimizing-flatlist-configuration#use-memo). My example code is above. Finally, all of movements were so smoothly changed. In my case, I use `React.memo` and `arePropsEqual`(2nd parameter). 

https://react.dev/reference/react/memo#reference


```
import { isSameDay } from 'date-fns';

...
const MemoList = React.memo(
  ({
    info,
    viewSize,
  }: {
    info: ListRenderItemInfo<Date>;
    viewSize: ViewSize;
  }) => <ListContainer itemInfo={info} viewSize={viewSize} />,
  (prevProps, nextProps) => isSameDay(prevProps.info.item, nextProps.info.item) // The type of item is Date.
);
```

```

<FlatList
    ...
    renderItem={(info: ListRenderItemInfo<Date>) => (
      <MemoList info={info} viewSize={viewSize} />
    )}
/>

```

**Comment by angganix** [comment]
> I solved this issue probably. The hint is official documents [here](https://reactnative.dev/docs/optimizing-flatlist-configuration#use-memo). My example code is above. Finally, all of movements were so smoothly changed. In my case, I use `React.memo` and `arePropsEqual`(2nd parameter).
> 
> https://react.dev/reference/react/memo#reference
> 
> ```
> import { isSameDay } from 'date-fns';
> 
> ...
> const MemoList = React.memo(
>   ({
>     info,
>     viewSize,
>   }: {
>     info: ListRenderItemInfo<Date>;
>     viewSize: ViewSize;
>   }) => <ListContainer itemInfo={info} viewSize={viewSize} />,
>   (prevProps, nextProps) => isSameDay(prevProps.info.item, nextProps.info.item) // The type of item is Date.
> );
> ```
> 
> ```
> 
> <FlatList
>     ...
>     renderItem={(info: ListRenderItemInfo<Date>) => (
>       <MemoList info={info} viewSize={viewSize} />
>     )}
> />
> ```

Hi, i solved the problem with similar resolution using **memo** and give second parameter with (prevProps, nextProps) to be compared. here is my working code.

```jsx
// this is where I solved the problem
const ProgramItem = memo(({ item }) => {
    const theme = useTheme();
    const navigation = useNavigation();
    return (
        <Pressable onPress={() => navigation.push("DetailProgram", { ...item })}>
            <Card style={{ ...styles.itemCard, backgroundColor: theme.colors.primary }}>
                <Card.Cover source={{ uri: item?.image }} style={styles.itemImage} />
                <Card.Content style={{ ...styles.itemContentWrapper, backgroundColor: theme.colors.primary }}>
                    <Text style={styles.itemTitle} numberOfLines={1} ellipsizeMode='tail'>{item?.title}</Text>
                    <Text style={styles.itemContent} numberOfLines={3} ellipsizeMode='tail'>{item?.content}</Text>
                </Card.Content>
            </Card>
        </Pressable>
    );
}, (prevProps, nextProps) => { // and here is what i didn't notice before.
    return prevProps.item === nextProps.item;
});

const ProgramList = () => {
    const [data, setData] = useState([]);
    const [loading, setLoading] = useState(true);
    const controller = useRef(new AbortController());

    const getData = async () => {
        try {
            const { signal } = controller.current;
            const res = await fetch(`https://jsonplaceholder.org/posts`);
            const list = await res.json();

            if (!signal.aborted) {
                setData(list);
                setLoading(false);
            }
        } catch (error) {
            if (!controller.current.signal.aborted) {
                if (process.env.NODE_ENV !== "production") {
                    console.log(error);
                }
            }
        }
    }

    useEffect(() => {
        getData();

        return () => {
            controller.current.abort();
        }
    }, []);

    return (
        <>
            <View style={styles.sectionTitleWrapper}>
                <Text style={styles.sectionTitle}>Program Unggulan</Text>
            </View>
            {loading ? (
                <View style={{ flexDirection: 'row', paddingHorizontal: 8 }}>
                    {[1, 2].map(item => (
                        <ShimmerPlaceHolder
                            key={item}
                            style={{ height: 280, width: 310, margin: 8, borderRadius: 8 }}
                        />
                    ))}
                </View>
            ) : (
                <FlatList
                    data={data}
                    keyExtractor={(item) => item?.id.toString()} // Corrected keyExtractor
                    horizontal
                    renderItem={({ item }) => <ProgramItem item={item} />}
                    contentContainerStyle={{ paddingHorizontal: 8 }}
                />
            )}
        </>
    )
}
```

**Comment by DarshanS162** [comment]
facing same issue 
any update

**Comment by a-eid** [comment]
@DarshanS162 use legend list or flashlist

**Comment by ngminhkhoa** [comment]
> [@DarshanS162](https://github.com/DarshanS162) use legend list or flashlist

They will not work

**Comment by a-eid** [comment]
> > [@DarshanS162](https://github.com/DarshanS162) use legend list or flashlist
> 
> They will not work

why not ?
