### ISSUE TITLE
[Android] ScrollView momentum not stopping when calling scrollTo programmatically

### ISSUE THREAD

**Issue by chr-sk** [facebook/react-native#32235]
## Description
When scrolling down a long ScrollView or FlatList on Android and calling `scrollTo` programmatically while the ScrollView's momentum is still going, the momentum does not stop and the resulting scrolling is stuttering and simply wrong.

## React Native version / Platform
0.65.1 / Android

With 0.63.4, this bug was not yet present.

## Steps To Reproduce
1. Render a ScrollView (or FlatList) with long content and a button with `onPress={() => scrollViewRef.scrollTo({ y: 0, animated: true })}`.
2. Scroll quickly down with your finger so that a momentum occurs.
3. Press the button while the momentum is still going.

## Expected Results
The momentum should stop and the ScrollView should scroll to its beginning.

## Possible reason
It seems that the reason for this bug lies in the following commit: https://github.com/facebook/react-native/commit/10314fe621e1649654e83df197adf657e0ca8363

**Comment by yiuyiu** [comment]
Running into the same issue.

**Comment by RosCoder** [comment]
React Native 0.70.6. The same issue..

**Comment by bolan9999** [comment]
Any update? fk rn

**Comment by moremorefun** [comment]
`scrollViewRef.scrollTo({ y: xxx, animated: false})`

Nor did it move to the specified location, the new target location did not overwrite the old target location

**Comment by halftheopposite** [comment]
This is also something we are facing, and for a little bit more context:

1. Scroll down fast
2. `onScroll` reports normal scrolling values (ex: 1200, 1220, 1240, etc.)
3. Trigger a `scrollTo` to `y: 0` with an outside action
4. `onScroll` correctly reports a scroll of `y: 0` once, but then continues with its momentum (ex: 1240, 0, 1260, 1280, etc.)

**Comment by moremorefun** [comment]
> This is also something we are facing, and for a little bit more context:
> 
> 
> 
> 1. Scroll down fast
> 
> 2. `onScroll` reports normal scrolling values (ex: 1200, 1220, 1240, etc.)
> 
> 3. Trigger a `scrollTo` to `y: 0` with an outside action
> 
> 4. `onScroll` correctly reports a scroll of `y: 0` once, but then continues with its momentum (ex: 1240, 0, 1260, 1280, etc.)

same issue

**Comment by tomekzaw** [comment]
The issue still persists on 0.71.2.

I've made a repro: https://github.com/tomekzaw/Issue32235

I will investigate this issue further.
