### ISSUE TITLE
Generate empty project, and it don't work. Got error with FBReactNativeSpec

### ISSUE THREAD

**Issue by mrhitman** [facebook/react-native#32242]
Generate empty project with react-native init or npx react-native init 
after initialisation try to run it  by
npx react-native run-ios or yarn ios got:
```sh
 ................................................................ very long error log
    export XPCSERVICES_FOLDER_PATH\=/XPCServices
    export YACC\=yacc
    export arch\=undefined_arch
    export variant\=normal
    /bin/sh -c /Users/user/Library/Developer/Xcode/DerivedData/OneMemoryTrainer-anzcpjajptojuucqsghepeaylias/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FBReactNativeSpec.build/Script-337605CB7CDF90939BEBF863ED22C375.sh
Command PhaseScriptExecution failed with a nonzero exit code

/Users/user/projects/my/OneMemoryTrainer/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.0.99. (in target 'boost-for-react-native' from project 'Pods')
warning: Capabilities for Signing & Capabilities may not function correctly because its entitlements use a placeholder team ID. To resolve this, select a development team in the OneMemoryTrainer editor. (in target 'OneMemoryTrainer' from project 'OneMemoryTrainer')
/Users/user/projects/my/OneMemoryTrainer/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.4, but the range of supported deployment target versions is 9.0 to 15.0.99. (in target 'Flipper-PeerTalk' from project 'Pods')
/Users/user/projects/my/OneMemoryTrainer/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.0.99. (in target 'Flipper-Glog' from project 'Pods')
/Users/user/projects/my/OneMemoryTrainer/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.0.99. (in target 'YogaKit' from project 'Pods')

** BUILD FAILED **


The following build commands failed:
	PhaseScriptExecution [CP-User]\ Generate\ Specs /Users/user/Library/Developer/Xcode/DerivedData/OneMemoryTrainer-anzcpjajptojuucqsghepeaylias/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FBReactNativeSpec.build/Script-337605CB7CDF90939BEBF863ED22C375.sh (in target 'FBReactNativeSpec' from project 'Pods')
(1 failure)
```
```sh
react-native -v
react-native-cli: 2.0.1
react-native: 0.65.1
```
macOS 11.6 BigSur
xed version 13.0

**Comment by mrhitman** [comment]
For android app launched successfully

**Comment by melero2000** [comment]
Same problem, a temporary solution is to downgrade to React Native version `0.64.2`

But be careful, if you use a targetSdkVersion = 30 in android and you use react native `0.64.2` when launching the app on a device with Android 11 the app won't work... at least in my case.

**Comment by melero2000** [comment]
This has worked for me: https://github.com/facebook/react-native/issues/31180#issuecomment-822069355

**Comment by ztolley** [comment]
Same issue. Create a fresh project and try to run it.

```
ld: warning: Could not find or use auto-linked library 'swift_Concurrency'
ld: warning: Could not find or use auto-linked library 'swiftFileProvider'
ld: warning: Could not find or use auto-linked library 'swiftDataDetection'
Undefined symbols for architecture x86_64:
  "__swift_FORCE_LOAD_$_swiftDataDetection", referenced from:
      __swift_FORCE_LOAD_$_swiftDataDetection_$_YogaKit in libYogaKit.a(YGLayoutExtensions.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftDataDetection_$_YogaKit)
  "__swift_FORCE_LOAD_$_swiftFileProvider", referenced from:
      __swift_FORCE_LOAD_$_swiftFileProvider_$_YogaKit in libYogaKit.a(YGLayoutExtensions.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftFileProvider_$_YogaKit)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

/Users/ztolley/development/SmartSail/AwesomeProject/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.0.99. (in target 'boost-for-react-native' from project 'Pods')
/Users/ztolley/development/SmartSail/AwesomeProject/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.4, but the range of supported deployment target versions is 9.0 to 15.0.99. (in target 'Flipper-PeerTalk' from project 'Pods')
/Users/ztolley/development/SmartSail/AwesomeProject/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.0.99. (in target 'Flipper-Glog' from project 'Pods')

```

**Comment by mattwoberts** [comment]
Same here, my computer has updated to xcode 13.0, and the app I've been working on the last year now won't build:

```
ld: warning: Could not find or use auto-linked library 'swift_Concurrency'
ld: warning: Could not find or use auto-linked library 'swiftFileProvider'
ld: warning: Could not find or use auto-linked library 'swiftDataDetection'
Undefined symbols for architecture x86_64:
  "__swift_FORCE_LOAD_$_swiftDataDetection", referenced from:
      __swift_FORCE_LOAD_$_swiftDataDetection_$_YogaKit in libYogaKit.a(YGLayoutExtensions.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftDataDetection_$_YogaKit)
  "__swift_FORCE_LOAD_$_swiftFileProvider", referenced from:
      __swift_FORCE_LOAD_$_swiftFileProvider_$_YogaKit in libYogaKit.a(YGLayoutExtensions.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftFileProvider_$_YogaKit)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by mattwoberts** [comment]
> Same issue. Create a fresh project and try to run it.
> 
> ```
> ld: warning: Could not find or use auto-linked library 'swift_Concurrency'
> ld: warning: Could not find or use auto-linked library 'swiftFileProvider'
> ld: warning: Could not find or use auto-linked library 'swiftDataDetection'
> Undefined symbols for architecture x86_64:
>   "__swift_FORCE_LOAD_$_swiftDataDetection", referenced from:
>       __swift_FORCE_LOAD_$_swiftDataDetection_$_YogaKit in libYogaKit.a(YGLayoutExtensions.o)
>      (maybe you meant: __swift_FORCE_LOAD_$_swiftDataDetection_$_YogaKit)
>   "__swift_FORCE_LOAD_$_swiftFileProvider", referenced from:
>       __swift_FORCE_LOAD_$_swiftFileProvider_$_YogaKit in libYogaKit.a(YGLayoutExtensions.o)
>      (maybe you meant: __swift_FORCE_LOAD_$_swiftFileProvider_$_YogaKit)
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> 
> /Users/ztolley/development/SmartSail/AwesomeProject/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.0.99. (in target 'boost-for-react-native' from project 'Pods')
> /Users/ztolley/development/SmartSail/AwesomeProject/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.4, but the range of supported deployment target versions is 9.0 to 15.0.99. (in target 'Flipper-PeerTalk' from project 'Pods')
> /Users/ztolley/development/SmartSail/AwesomeProject/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.0.99. (in target 'Flipper-Glog' from project 'Pods')
> ```

I too am having this issue, although I don't think it's the same as the original issue being reported (since that's talking about FBReactNativeSpec).

**Comment by mattwoberts** [comment]
For my issue, I was able to make things work again by following these instructions:

https://github.com/lottie-react-native/lottie-react-native/issues/739#issuecomment-801850269

Specifically, in my project, I created a new swift file. After naming the file, Xcode asked me if I wanted to create a bridging header. I said yes, built the app, and now all is good again. 🤷‍♂️
