### ISSUE TITLE
The document of PushNotificationIOS enhancement

### ISSUE THREAD

**Issue by oney** [facebook/react-native#3224]
If I miss anything, please correct me.
I try to use PushNotificationIOS, and I face many problems. Now, I resolve these problems.

1. I have to add `RCTPushNotification.xcodeproj` to Libraries and add `libRCTPushNotification.a` to `Link Binary with Libraries`. Otherwise, I will get error `RCTPushNotificationManager is undefined` in `PushNotificationIOS.js`

2. I have to add these code to `AppDelegate.m`
```objective-c
#import "RCTPushNotificationManager.h"
...
- (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken {
  [RCTPushNotificationManager application:application didRegisterForRemoteNotificationsWithDeviceToken:deviceToken];
}
- (void)application:(UIApplication *)application didRegisterUserNotificationSettings:(UIUserNotificationSettings *)notificationSettings {
  [RCTPushNotificationManager application:application didRegisterUserNotificationSettings:notificationSettings];
}
- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo {
  [RCTPushNotificationManager application:application didReceiveRemoteNotification:userInfo];
}
```
Otherwise, this listener will be never called.
```javascript
PushNotificationIOS.addEventListener('register', function(token){
});
```
However, these things are not mentioned in the document. Can you add it to the document? It will be helpful. Or, it is in the document, and I miss it?

**Comment by satya164** [comment]
If it's not in the docs, may be you can send a pull request?

**Comment by oney** [comment]
OK, I'll try :smirk:
