### ISSUE TITLE
[Android] Any plans on making Android equivalent of  "Modal"  & "AlertiOS"  ??

### ISSUE THREAD

**Issue by VansonLeung** [facebook/react-native#3225]
I am sticking on making my own Modal + AlertiOS modules, but that would become a third-party solution. Just curious if there is any plans on developing official equivalent.

**Comment by lwansbrough** [comment]
https://facebook.github.io/react-native/docs/known-issues.html

**Comment by brentvatne** [comment]
As @lwansbrough pointed out, the roadmap for Android is in the known issues @VansonLeung :)

**Comment by VansonLeung** [comment]
Pretty much thanks :)
