### ISSUE TITLE
[iOS] Upgraded from 0.64.2 to 0.65.1 - RTC-Folly failed build

### ISSUE THREAD

**Issue by dougg0k** [facebook/react-native#32253]
After I made the migration, I am getting this error in the ios build.

```
** BUILD FAILED **


The following build commands failed:
	CompileC /Users/username/Library/Developer/Xcode/DerivedData/AppName-ajqemcdetclskwggzeuetwuikmht/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RCT-Folly.build/Objects-normal/x86_64/VirtualEventBase.o /Users/username/projects/appname/ios/Pods/RCT-Folly/folly/io/async/VirtualEventBase.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```

After trying to run the build for the second or third time, I get this

```
** BUILD FAILED **


The following build commands failed:
	CompileC /Users/username/Library/Developer/Xcode/DerivedData/AppName-ajqemcdetclskwggzeuetwuikmht/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RCT-Folly.build/Objects-normal/x86_64/TimeoutManager.o /Users/username/projects/appname/ios/Pods/RCT-Folly/folly/io/async/TimeoutManager.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```

Anything that can be done?

Edit: I did while upgrading other packages, but now, downgraded back to `0.64.2` and only had to downgrade `react-native-reanimated` back to `2.2.0` and that was enough to get it back working.

Btw, I am on a M1 Macbook, but build is happening on AppCenter. Got the error in both locally and there.

**Comment by Navipro70** [comment]
@dougg0k 
Replace your post_install function in Podfile with: 

```
 post_install do |installer|
    react_native_post_install(installer)

    # Apple Silicon builds require a library path tweak for Swift library discovery or "symbol not found" for swift things
    installer.aggregate_targets.each do |aggregate_target| 
      aggregate_target.user_project.native_targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['LIBRARY_SEARCH_PATHS'] = ['$(SDKROOT)/usr/lib/swift', '$(inherited)']
        end
      end
      aggregate_target.user_project.save
    end

     # Flipper requires a crude patch to bump up iOS deployment target, or "error: thread-local storage is not supported for the current target"
    # I'm not aware of any other way to fix this one other than bumping iOS deployment target to match react-native (iOS 11 now)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
       end
    end

    # ...but if you bump iOS deployment target, Flipper barfs again "Time.h:52:17: error: typedef redefinition with different types"
    # We need to make one crude patch to RCT-Folly - set `__IPHONE_10_0` to our iOS target + 1
    # https://github.com/facebook/flipper/issues/834 - 84 comments and still going...
    `sed -i -e  $'s/__IPHONE_10_0/__IPHONE_12_0/' #{installer.sandbox.root}/RCT-Folly/folly/portability/Time.h`
  end
```

And also check [this guide](https://github.com/facebook/react-native/issues/31480) for setup build environment on Mac m1

**Comment by dougg0k** [comment]
@Navipro70 Thanks, it worked.

**Comment by kshitej** [comment]
Tried the fix mentioned in this thread and it didn't work for 
```
CompileC /Users/username/Library/Developer/Xcode/DerivedData/projectName-awyiegslnefckyesnveuttxiurbm/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RCT-Folly.build/Objects-normal/arm64/SysUio.o /Users/username/Desktop/Personal/Personal\ Projects/projectName/ios/Pods/RCT-Folly/folly/portability/SysUio.cpp normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'RCT-Folly' from project 'Pods')
(1 failure)
```
React Native version : 0.67
XCode version : 13

**Comment by pratius** [comment]
> Tried the fix mentioned in this thread and it didn't work for
> 
> ```
> CompileC /Users/username/Library/Developer/Xcode/DerivedData/projectName-awyiegslnefckyesnveuttxiurbm/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RCT-Folly.build/Objects-normal/arm64/SysUio.o /Users/username/Desktop/Personal/Personal\ Projects/projectName/ios/Pods/RCT-Folly/folly/portability/SysUio.cpp normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'RCT-Folly' from project 'Pods')
> (1 failure)
> ```
> 
> React Native version : 0.67 XCode version : 13

I'm facing a same issue

**Comment by lundjrl** [comment]
> Tried the fix mentioned in this thread and it didn't work for
> 
> ```
> CompileC /Users/username/Library/Developer/Xcode/DerivedData/projectName-awyiegslnefckyesnveuttxiurbm/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RCT-Folly.build/Objects-normal/arm64/SysUio.o /Users/username/Desktop/Personal/Personal\ Projects/projectName/ios/Pods/RCT-Folly/folly/portability/SysUio.cpp normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'RCT-Folly' from project 'Pods')
> (1 failure)
> ```
> 
> React Native version : 0.67 XCode version : 13
Also using RN: 0.67
Xcode: 13.4.1

This worked for me by setting RCT-Folly to IPHONEOS_DEPLOYMENT_TARGET = '9.0'
