### ISSUE TITLE
[Android] XMLHttpRequest response doesn't return response headers

### ISSUE THREAD

**Issue by Sh3rawi** [facebook/react-native#3226]
While writing the android code for the app, the XHR is sent to the server and returned successfully, with the correct response text. However, there are no response headers. 
I've been using XHR directly, and i checked this by using the superagent library and it yields the same result. 
Both methods work correctly in the iOS app with headers and everything.

**Comment by satya164** [comment]
I've a pull request open for this - https://github.com/facebook/react-native/pull/3062
