### ISSUE TITLE
Upgrade 0.61 -> 0.64.2 error

### ISSUE THREAD

**Issue by thiennt6** [facebook/react-native#32261]
Pod File 

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Demo1' do
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'

  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'Demo1Tests' do
    inherit! :complete
  end

  use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })
  post_install do |installer|
    react_native_post_install(installer)
  end
end

target 'Demo1-tvOS' do

  target 'Demo1-tvOSTests' do
    inherit! :search_paths
  end
end

Error
![Screen Shot 2021-09-25 at 11 10 02](https://user-images.githubusercontent.com/58576835/134757421-6b027731-8425-45a0-9166-908573b5722f.png)

Help me !!!

**Comment by kelmants** [comment]
Hi bro, I had the same problem and you can fix it by commenting on these lines
#pod 'GoogleMaps'
#pod 'Google-Maps-iOS-Utils'

and add hermes_enabled into use_react_native, 
and remove arguments in use_flipper function
```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Demo1' do
rn_maps_path = '../node_modules/react-native-maps'
pod 'react-native-google-maps', :path => rn_maps_path
#pod 'GoogleMaps' <--- this
#pod 'Google-Maps-iOS-Utils' <--- this

config = use_native_modules!

####### and add hermes in false value 
 - use_react_native!(:path => config["reactNativePath"])
 + use_react_native!(
 +   :path => config[:reactNativePath],
 +  # to enable hermes on iOS, change `false` to `true` and then install pods
 +  :hermes_enabled => false
 + )

target 'Demo1Tests' do
inherit! :complete
end

 - use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })
 + use_flipper!()
post_install do |installer|
react_native_post_install(installer)
end
end

target 'Demo1-tvOS' do

target 'Demo1-tvOSTests' do
inherit! :search_paths
end
end
```

**Comment by thiennt6** [comment]
> Hi bro, I had the same problem and you can fix it by commenting on these lines
> #pod 'GoogleMaps'
> #pod 'Google-Maps-iOS-Utils'
> 
> and add hermes_enabled into use_react_native,
> and remove arguments in use_flipper function
> 
> ```
> require_relative '../node_modules/react-native/scripts/react_native_pods'
> require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
> 
> platform :ios, '10.0'
> 
> target 'Demo1' do
> rn_maps_path = '../node_modules/react-native-maps'
> pod 'react-native-google-maps', :path => rn_maps_path
> #pod 'GoogleMaps' <--- this
> #pod 'Google-Maps-iOS-Utils' <--- this
> 
> config = use_native_modules!
> 
> ####### and add hermes in false value 
>  - use_react_native!(:path => config["reactNativePath"])
>  + use_react_native!(
>  +   :path => config[:reactNativePath],
>  +  # to enable hermes on iOS, change `false` to `true` and then install pods
>  +  :hermes_enabled => false
>  + )
> 
> target 'Demo1Tests' do
> inherit! :complete
> end
> 
>  - use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })
>  + use_flipper!()
> post_install do |installer|
> react_native_post_install(installer)
> end
> end
> 
> target 'Demo1-tvOS' do
> 
> target 'Demo1-tvOSTests' do
> inherit! :search_paths
> end
> end
> ```

I stiil error
<img width="1439" alt="Screen Shot 2021-09-27 at 15 51 56" src="https://user-images.githubusercontent.com/58576835/134876194-8e7495b5-6ffb-4c7d-bf73-5607c876ba14.png">
r 
i updated podfile
![Screen Shot 2021-09-27 at 15 53 58](https://user-images.githubusercontent.com/58576835/134876510-818086a6-606e-4452-b642-b9561a88412c.png)

**Comment by kelmants** [comment]
And I've forgotten to tell you to upgrade the version support from 10.0 to 11.0 and you should create a new Swift file and a Brigde headed.
1) File -> New -> File
![step_one_swift](https://user-images.githubusercontent.com/25611270/135769533-9b1168d6-43a6-466b-8b66-1a4c60f0cee5.jpeg)

2) Select Swift File
<img width="736" alt="step_two_swift" src="https://user-images.githubusercontent.com/25611270/135769551-1adbf290-98f1-47fd-981d-6e972ba3423a.png">

3) Confirm Create Bridging Header
<img width="590" alt="step_three_swift" src="https://user-images.githubusercontent.com/25611270/135769544-4136f8f4-025f-4312-bfac-ea854c632a7b.png">
4) clean your Podfile.lock , Pods folder and clean your folder build 
5) pod install back.
