### ISSUE TITLE
Image component can't show image from URI link react native ANDROID

### ISSUE THREAD

**Issue by ginxx009** [facebook/react-native#32264]
## Description

Hi guys it's pretty weird for me right now because I can't display a specific URI

## React Native version:

"react": "17.0.1",
"react-native": "0.64.2",

## Steps To Reproduce
1. Add an Image Component then paste a URI link
2. then npx react-native run-android

## Expected Results
I need to display the image from the image link

here's the code

`
<View style={{flex:1}}>
    <Image source={{uri: 'https://lh3.googleusercontent.com/a/AATXAJyUhn33Tg8pem-F50kJuK7gAfpJsX0TOAsmv0f5=s96-c'}} style={{width:200, height:200}} />
</View> 
`

**Comment by slolkunchik** [comment]
any solutions? I have the same problem for that url https://www.njconsumeraffairs.gov/Pages/PageNotFoundError.aspx?requestUrl=https://www.njconsumeraffairs.gov/_catalogs/ just for Android, Ios is working fine.
