### ISSUE TITLE
Android Studio is not being detected..

### ISSUE THREAD

**Issue by Abdullah-Shamhan** [facebook/react-native#32278]
When I run `npx react-native doctor` everything seems ok except that it's not recognizing Android studio 

![image](https://user-images.githubusercontent.com/55408692/134944829-a3d504fb-8758-48d7-8dd6-15dcc3597129.png)

I have the latest Android studio arctic fox installed and I have tried to run the project using Android Studio and it was working.. but when I run the project using `npx react-native run-android` It fails because of the Android environment..

**Comment by sayanarijit** [comment]
Facing the same issue.

```
➜  ReactNativeApp git:(main) ✗ npx react-native --version
5.0.1
➜  ReactNativeApp git:(main) ✗ which android-studio
/var/lib/snapd/snap/bin/android-studio
➜  ReactNativeApp git:(main) ✗ which sdkmanager
/home/sayanarijit/Android/Sdk/tools/bin/sdkmanager
➜  ReactNativeApp git:(main) ✗ which java
/home/sayanarijit/jdk-11/bin/java
```

**Comment by sayanarijit** [comment]
More info:

```
System:
    OS: Linux 5.14 Manjaro Linux
    CPU: (8) x64 AMD Ryzen 7 4700U with Radeon Graphics
    Memory: 1.54 GB / 7.15 GB
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.11.0 - /usr/bin/node
    Yarn: 1.22.15 - ~/.nix-profile/bin/yarn
    npm: 8.0.0 - /usr/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 30, 31
      Build Tools: 29.0.3, 30.0.2, 31.0.0
      System Images: android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: javac 11 - /home/sayanarijit/jdk-11/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.3 => 0.64.3
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by sayanarijit** [comment]
Not sure if it's related, but also see https://github.com/facebook/react-native/issues/32043 and https://github.com/facebook/react-native/issues/28480

**Comment by sayanarijit** [comment]
So far, I manager to track down the issue to `envinfo` (a dependency of https://github.com/react-native-community/cli) not being able to get the Android Studio from `ANDROID_HOME` env var.

```
➜  ReactNativeApp git:(main) ✗ yarn run envinfo
yarn run v1.22.15
$ /home/sayanarijit/Documents/GitHub/ReactNativeApp/node_modules/.bin/envinfo

  System:
    OS: Linux 5.14 Manjaro Linux
    CPU: (8) x64 AMD Ryzen 7 4700U with Radeon Graphics
    Memory: 233.16 MB / 7.15 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 14.18.0 - /tmp/yarn--1636772333935-0.5573534728655647/node
    Yarn: 1.22.15 - /tmp/yarn--1636772333935-0.5573534728655647/yarn
    npm: 8.0.0 - /usr/bin/npm
  Managers:
    Cargo: 1.57.0 - ~/.cargo/bin/cargo
    Gradle: 7.2 - ~/.nix-profile/bin/gradle
    Maven: 3.8.2 - ~/.nix-profile/bin/mvn
    pip3: 20.3.4 - /usr/bin/pip3
    RubyGems: 3.2.21 - /usr/bin/gem
  Utilities:
    CMake: 3.21.3 - /usr/bin/cmake
    Make: 4.3 - /usr/bin/make
    GCC: 11.1.0 - /usr/bin/gcc
    Git: 2.33.0 - /home/sayanarijit/.nix-profile/bin/git
    Clang: 12.0.1 - /usr/bin/clang
    Ninja: 1.10.2 - /usr/bin/ninja
    Mercurial: 5.9.2 - /usr/bin/hg
    FFmpeg: 4.4 - /home/sayanarijit/.nix-profile/bin/ffmpeg
  Servers:
    Nginx: 1.20.1 - /usr/bin/nginx
  Virtualization:
    Docker: 20.10.9 - /usr/bin/docker
    VirtualBox: 6.1.26 - /usr/bin/vboxmanage
  SDKs:
    Android SDK:
      API Levels: 30, 31
      Build Tools: 29.0.3, 30.0.2, 31.0.0
      System Images: android-30 | Google Play Intel x86 Atom
  IDEs:
    Nano: 5.9 - /usr/bin/nano
    VSCode: 1.62.2 - /var/lib/snapd/snap/bin/code
    Vim: 8.2 - /home/sayanarijit/.nix-profile/bin/vim
  Languages:
    Bash: 5.1.8 - /usr/bin/bash
    Go: 1.17.1 - /usr/bin/go
    Java: javac 11 - /home/sayanarijit/jdk-11/bin/javac
    Perl: 5.34.0 - /usr/bin/perl
    Protoc: 3.17.3 - /usr/bin/protoc
    Python: 3.9.7 - /usr/bin/python
    Python3: 3.9.7 - /usr/bin/python3
    Ruby: 3.0.2 - /usr/bin/ruby
    Rust: 1.58.0 - /home/sayanarijit/.cargo/bin/rustc
  Databases:
    PostgreSQL: 13.4 - /usr/bin/postgres
    SQLite: 3.36.0 - /home/sayanarijit/.nix-profile/bin/sqlite3
  Browsers:
    Brave Browser: 95.1.31.91
    Chromium: 94.0.4606.81
    Firefox: 94.0.1

Done in 3.38s.
```

**Comment by sayanarijit** [comment]
More related issues: https://github.com/react-native-community/cli/issues/858

**Comment by sayanarijit** [comment]
Found the [actual issue](https://github.com/tabrindle/envinfo/issues/211). But I'm not sure if it's solvable. Why does react-native need to parse the info so critically? Isn't the binary location all it should need?

**Comment by birdofpreyru** [comment]
+1. I've just bumped into this issue while installing RN dev environment on a new Ubuntu machine. A good solution would be to update RN documentation & RN doctor tool error message to say that Android Studio must be installed into `/opt/android-studio`.

**P.S.:** I actually suspect that technically it may live in different locations as well &mdash; on my other machine RN environment worked fine with Android Studio installed at `$HOME/android-studio`, but it is anyway annoying seeing the error in RN doctor and wasting time to just figure out it was all because of the Android Studio location, nobody warned you about.

**Comment by zedtux** [comment]
Moving Android Studio to `/opt` makes `doctor` green, thank you @sayanarijit!

**Comment by farishan** [comment]
Ubuntu 22.04

+1, moving Android Studio to `/opt` makes `doctor` green

**Comment by alordiel** [comment]
After unzipping the tar file into `android-studio` and installing the studio I've to move the `android-studio` folder into `/opt/` folder. Only then it all worked.

**Comment by birdofpreyru** [comment]
As said above, Android Studio does not have to be installed into `/opt`; RN will find it and SDK in different locations as long as you have followed [Environment Setup](https://reactnative.dev/docs/environment-setup) correctly, setting the `ANDROID_HOME` environment variable, and adding **emulator** and **platform-tools** paths to `PATH`.

The **doctor** can't find it wrongly, because, if I recall correctly, it relies on a 3rd party dependency to find software installed on the system, and that 3rd party dependency just looks for Android studio and SDK at the static location in `/opt`, and does not check environment variables RN actually depends on.

**Comment by crowwa** [comment]
Faced the same problem, the Android SDK is being detected but not the Android Studio. I found the Android Studio is not installed in default path and C:/, and reinstalled in defalut path solved this problem

**Comment by naagaraa** [comment]
same problem, in linux. is work if android-studio in /opt folder. in case i installed android studio using snap.

`
npx react-native doctor
Common
 ✓ Node.js - Required to execute JavaScript code
 ✓ npm - Required to install NPM dependencies
 ✓ Metro - Required for bundling the JavaScript code

Android
 ✓ Adb - Required to verify if the android device is attached correctly
 ✓ JDK - Required to compile Java code
 ✖ Android Studio - Required for building and installing your app on Android
 ✓ ANDROID_HOME - Environment variable that points to your Android SDK installation
 ✓ Gradlew - Build tool required for Android builds
 ✓ Android SDK - Required for building and installing your app on Android

Errors:   1
`

this working :


1. check apps install on snap. "snap list". 
2. go to /snap/android-studio "/snap/bin/android-studio" 
3. check folder again "ls -l"
4. result like this

`
total 0
drwxr-xr-x 9 root root 246 Mar  1 17:07 150
lrwxrwxrwx 1 root root   3 Mar 17 21:01 current -> 150

`

5. copy current to dir /opt
6. "sudo cp -dR /snap/android-studio/current/* /opt/android-studio"
7. go to dir /opt/android-studio, "cd /opt/android-studio " check that's copy like this


`
ls
bin        Install-Linux-tar.txt  lib      LICENSE.txt  NOTICE.txt  product-info.json
build.txt  jbr                    license  meta         plugins     snap
`

8. run again "npx react-native doctor"

`
npx react-native doctor
Common
 ✓ Node.js - Required to execute JavaScript code
 ✓ npm - Required to install NPM dependencies
 ✓ Metro - Required for bundling the JavaScript code

Android
 ✓ Adb - Required to verify if the android device is attached correctly
 ✓ JDK - Required to compile Java code
 ✓ Android Studio - Required for building and installing your app on Android
 ✓ ANDROID_HOME - Environment variable that points to your Android SDK installation
 ✓ Gradlew - Build tool required for Android builds
 ✓ Android SDK - Required for building and installing your app on Android

Errors:   0
Warnings: 0
`

**Comment by fetche12345** [comment]
I have faced the same issue. To fix it i just created a symlink in `/opt` pointing to `~/.local/share/JetBrains/Toolbox/apps/android-studio`
