### ISSUE TITLE
Dependency resolution failure does not cause the packager to fail

### ISSUE THREAD

**Issue by evansolomon** [facebook/react-native#3227]
Trying to require a module that the packager can't resolve (e.g. `require('madeupmodule...')`) apparently doesn't throw an error/exit/whatever. Instead it prints [this "unable to resolve..."](https://github.com/facebook/react-native/blob/3cdd8d032060c46740bb92f8152c6fdd3a4e1862/packager/react-packager/src/DependencyResolver/DependencyGraph/ResolutionRequest.js#L72-L76) warning, continues working, then announces "Build complete".

It does end up producing a bundle, but one that it knows is going to be broken. It seems like it would make sense to treat this as an error and exit the command with some non-zero code. Is there a reason not to that would be a bad idea?

**Comment by satya164** [comment]
It'll be tedious to manually start the packager again each time. Right now, it's just fix the typo and save.

We'll see the error in the app anyways, so we'll know that the bundle is broken.

**Comment by evansolomon** [comment]
In a scenario where the packager is running that makes sense, but when you are just creating a static bundle (e.g. running `react-native bundle`) it's exiting anyway. Exiting with some non-zero code would be more standard.

**Comment by satya164** [comment]
Yes, for bundles it makes sense.

**Comment by mkonicek** [comment]
I agree this could be nice to have (cc @martinbigio for opinions). Would you be up for submitting a pull request?

**Comment by martinbigio** [comment]
We've already addressed this on 793c3564ffb0c2b66abae0a5aa7997e2a9e4869c. It's currently only enabled for ios react-native apps
