### ISSUE TITLE
[PickerIOS] Impossible to center

### ISSUE THREAD

**Issue by edo1493** [facebook/react-native#3228]
After updating Xcode with iOS 9.0, the behaviour of PickerIOS has changed. I am not able to center it anymore, but it sits on the left of the screen. 

Everything was fine before, so I don't think my code has any related problems. What I have noticed is that with the simulator for 4s and 5s, I can get the PickerIOS width to be full screen (which is what I want). 

As you can see from the screenshot, the Picker is on the left. I have also tried to place a background color just to see if it fits the whole width and it does, so I can't manage to figure out why it is there. 

I have tried to place it to the center of the screen with alignSelf or alignItem with a wrapper, but it doesn't work. 

At the moment, my Picker is using a wrapper View of this kind: 
```
mask1: {
    height:120,
    overflow:'hidden',
    justifyContent:'space-around',
    marginTop:50
  },
```

At first I thought it was a styling issue, but it seems to be a bug, even though I am not totally sure. I have posted the mask, but even without it, the Picker doesn't do what it is supposed to. 

![screen shot 2015-10-04 at 19 23 04](https://cloud.githubusercontent.com/assets/2309030/10269363/62125c9c-6acd-11e5-8eb4-fe1303fd192a.png)

![screen shot 2015-10-04 at 20 44 53](https://cloud.githubusercontent.com/assets/2309030/10269822/00630922-6ad9-11e5-8dd1-5781c8bfaf25.png)

**Comment by kujohn** [comment]
Seems kind of tricky to get it center aligned. I think the actual Date Picker component is placed within another view. Setting a small width (like 100) to the component cuts off the Date Picker without the text getting centered. Here is a working combination that I have tried:
```
container: {
  flex: 1,
  justifyContent: 'space-around',
  alignItems: 'center'
},
datePicker: {
  width: 300
}
```
Tested on iPhone 4, 6, 6plus.

![iphone4](https://cloud.githubusercontent.com/assets/1356936/10297887/6ac4ed4e-6b8d-11e5-87b9-5328974a4302.png)
![iphone6plus](https://cloud.githubusercontent.com/assets/1356936/10297888/6ac7c122-6b8d-11e5-89ea-adcf72930d77.png)

**Comment by chenkun24** [comment]
@kujohn But in this way the PickerItems are not in the center.

**Comment by edo1493** [comment]
My workaround was to add some left and right margin, but as @chenkun24 points out, even in my way, the items are not in the center.

**Comment by chenkun24** [comment]
I found out that PickerIOS only worked well in NavigatorIOS.

**Comment by eyaleizenberg** [comment]
Related issue with the date picker. I can center it by wrapping it in a view with alignSelf: 'center'. However, it doesn't stretch all the way on iphone 6. On iPhone 5, it's width is the entire width of the screen.
![screen shot 2015-10-08 at 14 22 28](https://cloud.githubusercontent.com/assets/1061345/10364933/1d290d58-6dc8-11e5-951b-e74368fbc191.png)

**Comment by mikemonteith** [comment]
From the iOS9 release notes: 

>UIPickerView and UIDatePicker are now resizable and adaptive—previously, these views would enforce  a default size even if you attempted to resize them. These views also now default to a width of 320 points on all devices, instead of to the device width on iPhone.
Interfaces that rely on the old enforcement of the default size will likely look wrong when compiled for iOS 9. Any problems encountered can be resolved by fully constraining or sizing picker views to the desired size instead of relying on implicit behavior

https://developer.apple.com/library/prerelease/ios/releasenotes/General/RN-iOSSDK-9.0/

**Comment by edo1493** [comment]
Same issue on an iPad Pro simulator, even by setting the width. The interesting bit is that from time to time, the Picker goes full width and center itself. 

If I place a view around with alignItems:'center', it just disappears. 

As @mikemonteith said, the problem is 9 related, cause I wasn't having this sort of issues before. 

![screen shot 2015-11-15 at 11 41 15](https://cloud.githubusercontent.com/assets/2309030/11168594/cc906e5c-8b8d-11e5-994b-b4733ce3477e.png)

**Comment by edo1493** [comment]
The solution seems to be to set the width as 320 and then a wrapper view with alignItems:center, anything else creates problems. This a bit annoying on an iPad though : (

**Comment by jihopark** [comment]
yeah solved with @edo1493 's solution above... but still not so good :(

**Comment by jihopark** [comment]
with the same flex style as @edo1493 's solution above, iOS8 and 9 in iPhone 6 are different. I cannot get it centered in iphone6 ios8 ..... :-1:

**Comment by license2e** [comment]
Note: If you need the picker centered inside a modal that isn't the full 320 width, just wrap it inside a View, and set overflow: 'hidden' on the View.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/pickerios-impossible-to-center

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
