### ISSUE TITLE
Fetch working fine on Android emulator but not working on real device

### ISSUE THREAD

**Issue by RyadhB2** [facebook/react-native#32289]
I'l having trouble while using an api, with the post method. It works just fine on the android emulator ( also fine on ios simulator ) but I'm getting error 400 when using a real device .
env : 
Android : Any version .
React native : 0.63.3

Any suggestions please ?

**Comment by gabrielyoto** [comment]
you must run the `adb reverse` command to tell your device that it should use your computer's port not its.

**Comment by RyadhB2** [comment]
solved, there was a problem with the backend.
