### ISSUE TITLE
Failed to transform react-native-reanimated-66-jsc.aar

### ISSUE THREAD

**Issue by Xplosive06** [facebook/react-native#32293]
## Description
Build not working on Android and Ios

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugAssets'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform react-native-reanimated-66-jsc.aar (project :react-native-reanimated) to match attributes {artifactType=android-assets}.
      > Execution failed for JetifyTransform: /Users/mike/Documents/GitHub/seeed-realm/seeed/node_modules/react-native-reanimated/android/react-native-reanimated-66-jsc.aar.
         > Transform's input file does not exist: /Users/mike/Documents/GitHub/seeed-realm/seeed/node_modules/react-native-reanimated/android/react-native-reanimated-66-jsc.aar. (See https://issuetracker.google.com/issues/158753935)

## React Native version:
System:
    OS: macOS 11.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 544.87 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.3.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.23.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 27, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2
      System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7322048
    Xcode: 13.0/13A233 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_275 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: ^5.0.1-alpha.2 => 5.0.1 
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.0-rc.3 => 0.66.0-rc.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Upgrade react-native from 0.65.1 to 0.66.0-rc.3

"react-native-reanimated": "^2.2.2"

## Expected Results
Build succeed

**Comment by chungweileong94** [comment]
I think the reanimated team is the one responsible get this fix, not a react-native team. If you are trying to use a pre-release version of RN together with reanimated, you are most likely going to hit a similar issue. 

FYI, https://github.com/software-mansion/react-native-reanimated/issues/2452

**Comment by mikehardy** [comment]
I just successfully tested react-native 0.66.0-rc.4 and reanimated 2.3.0-beta.2, everything seems to work.
Be careful to make sure you have followed their instructions for install though!
Otherwise it won't work and you'll waste time like me. Don't be like me ;-) 
https://github.com/software-mansion/react-native-reanimated/pull/2462#issuecomment-931615100
