### ISSUE TITLE
`StatusBarIOS` removed but `statusBarFrameWillChange` event not yet available in `StatusBar`

### ISSUE THREAD

**Issue by danielgindi** [facebook/react-native#32297]
### Version

0.66.0-rc.4

### Build Target(s)

iOS 15

### Developer Environment

iOS / Xcode

### Issue and Reproduction Steps

Previously we could have done this:
```js
StatusBarIOS.addListener('statusBarFrameWillChange', ...)
StatusBarIOS.addListener('statusBarFrameDidChange', ...)
```
To get status bar frame change events on iOS.
Now the event still exists - in native code - but not accessible anymore as it has not migrated when deprecating `StatusBarIOS`.

So this is not only a breaking change, but a breaking change without an alternative.

**Comment by lunaleaps** [comment]
@danielgindi `StatusBarIOS` is a lean-core component that has been slotted for removal for some time and to be replaced with StatusBar. Is your issue here that [StatusBar](https://reactnative.dev/docs/statusbar) does not have the same listener?

**Comment by A-Tokyo** [comment]
@lunaleaps This has been blocking us from upgrading for quite a while! ( : Is there a way we can get around this temporarily till a solution is out?
