### ISSUE TITLE
unknown:ReactNative

### ISSUE THREAD

**Issue by luozhiran** [facebook/react-native#32295]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
there’s an issue that I can’t figure out, there is no error while compiling the release app, none error, the –variant=release works! but after downloaded it from the store the app just crashes on the first launch, the only errors that I can see with AndroidStudio and logcat are these, but I don’t know if this log is just something normal on the launch, the thing is can’t figure out from where start to fix this.
## React Native version:
Run `react-native info` in your terminal and copy the results here.
System:
    OS: macOS 11.3.1
    CPU: (8) arm64 Apple M1
    Memory: 565.69 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.6.1 - /opt/homebrew/bin/node
    Yarn: 1.22.11 - /opt/homebrew/bin/yarn
    npm: 7.21.1 - ~/javabyte/ddxq-rn-webstom/reactnative/node_modules/.bin/npm
    Watchman: 2021.06.07.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.10.2 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 25, 26, 28, 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0
      System Images: android-30 | Google Play ARM 64 v8a, android-S | Google Play ARM 64 v8a
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7583922
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Android studio log
2021-02-20 10:28:52.020 5922-5968/com.c******* E/unknown:ReactNative:
ReactInstanceManager.createReactContext: mJSIModulePackage null
2021-02-20 10:28:52.023 5922-5973/com.c******* E/ReactNativeJNI: logMarker CREATE_REACT_CONTEXT_END
2021-02-20 10:28:52.098 5922-5973/com.c******* E/ReactNativeJNI: logMarker RUN_JS_BUNDLE_START
2021-02-20 10:28:52.112 5922-5974/com.c******* E/unknown:ReactNative: ReactInstanceManager.attachRootViewToInstance()
2021-02-20 10:28:52.696 5922-5974/com.c******* E/unknown:ReactRootView: runApplication: call
AppRegistry.runApplication
2021-02-20 10:28:54.143 5922-5922/com.c******* E/unknown:ReactNative: Unable to launch logbox because react was
unable to create the root view
2021-02-20 10:28:54.707 5922-5973/com.c******* E/ReactNativeJNI: logMarker RUN_JS_BUNDLE_END

**Comment by jschenkDD** [comment]
Some issue and log entries

**Comment by jschenkDD** [comment]
Upgrade to React Native v0.66.4 fixed this
