### ISSUE TITLE
Linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by TasbeelZahid** [facebook/react-native#32294]
Linker command failed with exit code 1 (use -v to see invocation)
<img width="1440" alt="Screenshot 2021-09-29 at 1 33 31 PM" src="https://user-images.githubusercontent.com/47120106/135233101-67c5d0a8-ccec-4c40-b6cf-852ba6ae12f9.png">

## Description
Ld /Users/Tasbeel/Library/Developer/Xcode/DerivedData/DMSUniverse-byyafnfuuenzwzfhdstvaznyoumm/Build/Products/Debug-iphonesimulator/DMSUniverse.app/DMSUniverse normal x86_64
    cd /Users/Tasbeel/Documents/Projects/MyProjects/mobile-cd-ci/ios
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target x86_64-apple-ios11.0-simulator -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk -L/Users/Tasbeel/Library/Developer/Xcode/DerivedData/DMSUniverse-byyafnfuuenzwzfhdstvaznyoumm/Build/Products/Debug-iphonesimulator -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-5.0/iphonesimulator -L -L/Users/Tasbeel/Library/Developer/Xcode/DerivedData/DMSUniverse-byyafnfuuenzwzfhdstvaznyoumm/Build/Products/Debug-iphonesimulator/Base64 -L/Users/Tasbeel/Library/Developer/Xcode/DerivedData/DMSUniverse-byyafnfuuenzwzfhdstvaznyoumm/Build/Products/Debug-iphonesimulator/CodePush -L/Users/Tasbeel/Library/Developer/Xcode/DerivedData/DMSUniverse-byyafnfuuenzwzfhdstvaznyoumm/Build/Products/Debug-iphonesimulator/DoubleConversion -L/Users/Tasbeel/Library/Developer/Xcode/DerivedData/DMSUniverse-byyafnfuuenzwzfhdstvaznyoumm/Build/Products/Debug-iphonesimulator/FBReactNativeSpec -L/Users/Tasbeel/Library/Developer/Xcode/DerivedData/DMSUniverse-byyafnfuuenzwzfhdstvaznyoumm/Build/Products/Debug-iphonesimulator/Google-Maps-iOS-Utils -L/Users/Tasbeel/Library/Developer/Xcode/DerivedData/DMSUniverse-byyafnfuuenzwzfhdstvaznyoumm/Build/Products/Debug-iphonesimulator/JWT -L/Users/Tasbeel/Library/Developer/Xcode/DerivedData/DMSUniverse-byyafnfuuenzwzfhdstvaznyoumm/Build/Products/Debug-iphonesimulator/RCT-Folly -L/Users/Tasbeel/Library/Developer/Xcode/DerivedData/DMSUniverse-byyafnfuuenzwzfhdstvaznyoumm/Build/Products/Debug-iphonesimulator/RCTTypeSafety -L/Users/Tasbeel/Library/Developer/Xcode/DerivedData/DMSUniverse-byyafnfuuenzwzfhdstvaznyoumm/Build/Products/Debug-iphonesimulator/RNCAsyncStorage -L/Users/Tasbeel/Library/Developer/Xcode/DerivedData/DMSUniverse-byyafnfuuenzwzfhdstvaznyoumm/Build/Products/Debug-iphonesimulator/RNCMaskedView -L/Users/Tasbeel/Library/Developer/Xcode/DerivedData/DMSUniverse-byyafnfuuenzwzfhdstvaznyoumm/Build/Products/Debug-iphonesimulator/RNCPicker -L/Users/Tasbeel/Library/Developer/Xcode/DerivedData/DMSUniverse-byyafnfuuenzwzfhdstvaznyoumm/Build/Products/Debug-iphonesimulator/RNDateTimePicker -L/Users/Tasbeel/Library/Developer/Xcode/DerivedData/DMSUniverse-byyafnfuuenzwzfhdstvaznyoumm/Build/Products/Debug-iphonesimulator/RNDeviceInfo -L/Users/Tasbeel/Library/Developer/Xcode/DerivedData/DMSUniverse-byyafnfuuenzwzfhdstvaznyoumm/Build/Products/Debug-iphonesimulator/RNFS -L/Users/Tasbeel/Library/Developer/Xcode/DerivedData/DMSUniverse-byyafnfuuenzwzfhdstvaznyoumm/Build/Products/Debug-iphonesimulator/RNFastImage -L/Users/Tasbeel/Library/Developer/Xcode/DerivedData/DMSUniverse-byyafnfuuenzwzfhdstvaznyoumm/Build/Products/Debug-iphonesimulator/RNFileViewer -L/Users/Tasbeel/Library/Developer/Xcode/DerivedData/DMSUniverse-byyafnfuuenzwzfhdstvaznyoumm/Build/Products/Debug-iphonesimulator/RNGestureHandler -L/Users/Tasbeel/Library/Developer/Xcode/DerivedData/DMSUniverse-byyafnfuuenzwzfhdstvaznyoumm/Build/Products/Debug-iphonesimulator/RNImageCropPicker -L/Users/Tasbeel/Library/Developer/Xcode/DerivedData/DMSUniverse-byyafnfuuenzwzfhdstvaznyoumm/Build/Products/Debug-iphonesimulator/RNPDF -L/Users/Tasbeel/Library/Developer/Xcode/DerivedData/DMSUniverse-byyafnfuuenzwzfhdstvaznyoumm/Build/Products/Debug-iphonesimulator/RNReanimated -L/Users/Tasbeel/Library/Developer/Xcode/DerivedData/DMSUniverse-byyafnfuuenzwzfhdstvaznyoumm/Build/Products/Debug-iphonesimulator/RNSVG -L/Users/Tasbeel/Library/Developer/Xcode/DerivedData/DMSUniverse-byyafnfuuenzwzfhdstvaznyoumm/Build/Products/Debug-iphonesimulator/RNScreens -L/Users/Tasbeel/Library/Developer/Xcode/DerivedData/DMSUniverse-byyafnfuuenzwzfhdstvaznyoumm/Build/Products/Debug-iphonesimulator/RNVectorIcons -L/Users/Tasbeel/Library/Developer/Xcode/DerivedData/DMSUniverse-byyafnfuuenzwzfhdstvaznyoumm/Build/Products/Debug-iphonesimulator/React-Core -L/Users/Tasbeel/Library/Developer/Xcode/DerivedData/DMSUniverse-byyafnfuuenzwzfhdstvaznyoumm/Build/Products/Debug-iphonesimulator/React-CoreModules -L/Users/Tasbeel/Library/Developer/Xcode/DerivedData/DMSUniverse-byyafnfuuenzwzfhdstvaznyoumm/Build/Products/Debug-iphonesimulator/React-RCTAnimation -L/Users/Tasbeel/Library/Developer/Xcode/DerivedData/DMSUniverse-byyafnfuuenzwzfhdstvaznyoumm/Build/Products/Debug-iphonesimulator/React-RCTBlob -L/Users/Tasbeel/Library/Developer/Xcode/DerivedData/DMSUniverse-byyafnfuuenzwzfhdstvaznyoumm/Build/Products/Debug-iphonesimulator/React-RCTImage -L/Users/Tasbeel/Library/Developer/Xcode/DerivedData/DMSUniverse-byyafnfuuenzwzfhdstvaznyoumm/Build/Products/Debug-iphonesimulator/React-RCTLinking -L/Users/Tasbeel/Library/Developer/Xcode/DerivedData/DMSUniverse-byyafnfuuenzwzfhdstvaznyoumm/Build/Products/Debug-iphonesimulator/React-RCTNetwork -L/Users/Tasbeel/Library/Developer/Xcode/DerivedData/DMSUniverse-byyafnfuuenzwzfhdstvaznyoumm/Build/Products/Debug-iphonesimulator/React-RCTSettings -L/Users/Tasbeel/Library/Developer/Xcode/DerivedData/DMSUniverse-byyafnfuuenzwzfhdstvaznyoumm/Build/Products/Debug-iphonesimulator/React-RCTText -L/Users/Tasbeel/Library/Developer/Xcode/DerivedData/DMSUniverse-byyafnfuuenzwzfhdstvaznyoumm/Build/Products/Debug-iphonesimulator/React-RCTVibration -L/Users/Tasbeel/Library/Developer/Xcode/DerivedData/DMSUniverse-byyafnfuuenzwzfhdstvaznyoumm/Build/Products/Debug-iphonesimulator/React-cxxreact -L/Users/Tasbeel/Library/Developer/Xcode/DerivedData/DMSUniverse-byyafnfuuenzwzfhdstvaznyoumm/Build/Products/Debug-iphonesimulator/React-jsi -L/Users/Tasbeel/Library/Developer/Xcode/DerivedData/DMSUniverse-byyafnfuuenzwzfhdstvaznyoumm/Build/Products/Debug-iphonesimulator/React-jsiexecutor -L/Users/Tasbeel/Library/Developer/Xcode/DerivedData/DMSUniverse-byyafnfuuenzwzfhdstvaznyoumm/Build/Products/Debug-iphonesimulator/React-jsinspector -L/Users/Tasbeel/Library/Developer/Xcode/DerivedData/DMSUniverse-byyafnfuuenzwzfhdstvaznyoumm/Build/Products/Debug-iphonesimulator/React-perflogger -L/Users/Tasbeel/Library/Developer/Xcode/DerivedData/DMSUniverse-byyafnfuuenzwzfhdstvaznyoumm/Build/Products/Debug-iphonesimulator/ReactCommon -L/Users/Tasbeel/Library/Developer/Xcode/DerivedData/DMSUniverse-byyafnfuuenzwzfhdstvaznyoumm/Build/Products/Debug-iphonesimulator/SDWebImage -L/Users/Tasbeel/Library/Developer/Xcode/DerivedData/DMSUniverse-byyafnfuuenzwzfhdstvaznyoumm/Build/Products/Debug-iphonesimulator/SDWebImageWebPCoder -L/Users/Tasbeel/Library/Developer/Xcode/DerivedData/DMSUniverse-byyafnfuuenzwzfhdstvaznyoumm/Build/Products/Debug-iphonesimulator/SSZipArchive -L/Users/Tasbeel/Library/Developer/Xcode/DerivedData/DMSUniverse-byyafnfuuenzwzfhdstvaznyoumm/Build/Products/Debug-iphonesimulator/TOCropViewController -L/Users/Tasbeel/Library/Developer/Xcode/DerivedData/DMSUniverse-byyafnfuuenzwzfhdstvaznyoumm/Build/Products/Debug-iphonesimulator/Yoga -L/Users/Tasbeel/Library/Developer/Xcode/DerivedData/DMSUniverse-byyafnfuuenzwzfhdstvaznyoumm/Build/Products/Debug-iphonesimulator/appcenter-analytics -L/Users/Tasbeel/Library/Developer/Xcode/DerivedData/DMSUniverse-byyafnfuuenzwzfhdstvaznyoumm/Build/Products/Debug-iphonesimulator/appcenter-core -L/Users/Tasbeel/Library/Developer/Xcode/DerivedData/DMSUniverse-byyafnfuuenzwzfhdstvaznyoumm/Build/Products/Debug-iphonesimulator/appcenter-crashes -L/Users/Tasbeel/Library/Developer/Xcode/DerivedData/DMSUniverse-byyafnfuuenzwzfhdstvaznyoumm/Build/Products/Debug-iphonesimulator/glog -L/Users/Tasbeel/Library/Developer/Xcode/DerivedData/DMSUniverse-byyafnfuuenzwzfhdstvaznyoumm/Build/Products/Debug-iphonesimulator/libwebp -L/Users/Tasbeel/Library/Developer/Xcode/DerivedData/DMSUniverse-byyafnfuuenzwzfhdstvaznyoumm/Build/Products/Debug-iphonesimulator/react-native-document-picker -L/Users/Tasbeel/Library/Developer/Xcode/DerivedData/DMSUniverse-byyafnfuuenzwzfhdstvaznyoumm/Build/Products/Debug-iphonesimulator/react-native-google-maps -L/Users/Tasbeel/Library/Developer/Xcode/DerivedData/DMSUniverse-byyafnfuuenzwzfhdstvaznyoumm/Build/Products/Debug-iphonesimulator/react-native-maps -L/Users/Tasbeel/Library/Developer/Xcode/DerivedData/DMSUniverse-byyafnfuuenzwzfhdstvaznyoumm/Build/Products/Debug-iphonesimulator/react-native-netinfo -L/Users/Tasbeel/Library/Developer/Xcode/DerivedData/DMSUniverse-byyafnfuuenzwzfhdstvaznyoumm/Build/Products/Debug-iphonesimulator/react-native-onesignal -L/Users/Tasbeel/Library/Developer/Xcode/DerivedData/DMSUniverse-byyafnfuuenzwzfhdstvaznyoumm/Build/Products/Debug-iphonesimulator/react-native-pager-view -L/Users/Tasbeel/Library/Developer/Xcode/DerivedData/DMSUniverse-byyafnfuuenzwzfhdstvaznyoumm/Build/Products/Debug-iphonesimulator/react-native-safe-area-context -L/Users/Tasbeel/Library/Developer/Xcode/DerivedData/DMSUniverse-byyafnfuuenzwzfhdstvaznyoumm/Build/Products/Debug-iphonesimulator/react-native-splash-screen -L/Users/Tasbeel/Library/Developer/Xcode/DerivedData/DMSUniverse-byyafnfuuenzwzfhdstvaznyoumm/Build/Products/Debug-iphonesimulator/react-native-video -L/Users/Tasbeel/Library/Developer/Xcode/DerivedData/DMSUniverse-byyafnfuuenzwzfhdstvaznyoumm/Build/Products/Debug-iphonesimulator/react-native-webview -F/Users/Tasbeel/Library/Developer/Xcode/DerivedData/DMSUniverse-byyafnfuuenzwzfhdstvaznyoumm/Build/Products/Debug-iphonesimulator -F/Users/Tasbeel/Documents/Projects/MyProjects/mobile-cd-ci/ios/Pods/AppCenter/AppCenter-SDK-Apple -F/Users/Tasbeel/Documents/Projects/MyProjects/mobile-cd-ci/ios/Pods/AppCenterReactNativeShared/AppCenterReactNativeShared -F/Users/Tasbeel/Documents/Projects/MyProjects/mobile-cd-ci/ios/Pods/GoogleMaps/Base/Frameworks -F/Users/Tasbeel/Documents/Projects/MyProjects/mobile-cd-ci/ios/Pods/GoogleMaps/Maps/Frameworks -F/Users/Tasbeel/Documents/Projects/MyProjects/mobile-cd-ci/ios/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework -F/Users/Tasbeel/Library/Developer/Xcode/DerivedData/DMSUniverse-byyafnfuuenzwzfhdstvaznyoumm/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/AppCenter -F/Users/Tasbeel/Library/Developer/Xcode/DerivedData/DMSUniverse-byyafnfuuenzwzfhdstvaznyoumm/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/AppCenterAnalytics -F/Users/Tasbeel/Library/Developer/Xcode/DerivedData/DMSUniverse-byyafnfuuenzwzfhdstvaznyoumm/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/AppCenterCrashes -F/Users/Tasbeel/Library/Developer/Xcode/DerivedData/DMSUniverse-byyafnfuuenzwzfhdstvaznyoumm/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/AppCenterReactNativeShared -filelist /Users/Tasbeel/Library/Developer/Xcode/DerivedData/DMSUniverse-byyafnfuuenzwzfhdstvaznyoumm/Build/Intermediates.noindex/DMSUniverse.build/Debug-iphonesimulator/DMSUniverse.build/Objects-normal/x86_64/DMSUniverse.LinkFileList -Xlinker -rpath -Xlinker /usr/lib/swift -Xlinker -rpath -Xlinker @executable_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/Tasbeel/Library/Developer/Xcode/DerivedData/DMSUniverse-byyafnfuuenzwzfhdstvaznyoumm/Build/Intermediates.noindex/DMSUniverse.build/Debug-iphonesimulator/DMSUniverse.build/Objects-normal/x86_64/DMSUniverse_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fobjc-link-runtime -ObjC -lc++ -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/Tasbeel/Library/Developer/Xcode/DerivedData/DMSUniverse-byyafnfuuenzwzfhdstvaznyoumm/Build/Intermediates.noindex/DMSUniverse.build/Debug-iphonesimulator/DMSUniverse.build/DMSUniverse.app-Simulated.xcent -lBase64 -lPods-DMSUniverse -Xlinker -dependency_info -Xlinker /Users/Tasbeel/Library/Developer/Xcode/DerivedData/DMSUniverse-byyafnfuuenzwzfhdstvaznyoumm/Build/Intermediates.noindex/DMSUniverse.build/Debug-iphonesimulator/DMSUniverse.build/Objects-normal/x86_64/DMSUniverse_dependency_info.dat -o /Users/Tasbeel/Library/Developer/Xcode/DerivedData/DMSUniverse-byyafnfuuenzwzfhdstvaznyoumm/Build/Products/Debug-iphonesimulator/DMSUniverse.app/DMSUniverse

## React Native version:
System:
    OS: macOS 11.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 90.41 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.5 - /usr/local/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 6.14.14 - /usr/local/bin/npm
    Watchman: 2021.08.02.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 31.0.0
      System Images: android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7583922
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_301 - /Library/Java/JavaVirtualMachines/jdk1.8.0_301.jdk/Contents/Home/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.64.2 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
**Package.Json**
  "dependencies": {
    "@react-native-async-storage/async-storage": "^1.15.5",
    "@react-native-community/datetimepicker": "^3.5.2",
    "@react-native-community/masked-view": "0.1.11",
    "@react-native-community/netinfo": "^6.0.0",
    "@react-native-picker/picker": "^1.16.1",
    "@react-navigation/material-top-tabs": "^5.3.15",
    "@react-navigation/native": "^5.9.4",
    "@react-navigation/stack": "^5.14.4",
    "appcenter": "4.2.0",
    "appcenter-analytics": "4.2.0",
    "appcenter-crashes": "4.2.0",
    "axios": "^0.21.1",
    "laravel-echo": "^1.11.0",
    "moment": "^2.29.1",
    "nanoid": "^3.1.23",
    "react": "17.0.2",
    "react-content-loader": "^6.0.3",
    "react-moment": "^1.1.1",
    "react-native": "0.64.2",
    "react-native-code-push": "^7.0.2",
    "react-native-collapsible": "^1.6.0",
    "react-native-country-picker-modal": "^2.0.0",
    "react-native-device-info": "^8.1.3",
    "react-native-document-picker": "^5.2.0",
    "react-native-elements": "^3.4.2",
    "react-native-fast-image": "^8.3.4",
    "react-native-file-viewer": "^2.1.4",
    "react-native-fs": "^2.18.0",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-gifted-chat": "^0.16.3",
    "react-native-hide-with-keyboard": "^1.2.1",
    "react-native-image-crop-picker": "^0.36.2",
    "react-native-image-zoom-viewer": "^3.0.1",
    "react-native-keyboard-aware-scroll-view": "^0.9.4",
    "react-native-map-clustering": "^3.4.2",
    "react-native-maps": "^0.28.0",
    "react-native-onesignal": "^3.9.3",
    "react-native-openanything": "0.0.6",
    "react-native-pager-view": "^5.2.1",
    "react-native-popup-menu": "^0.15.11",
    "react-native-reanimated": "1.13.3",
    "react-native-safe-area-context": "^3.2.0",
    "react-native-screens": "^3.4.0",
    "react-native-size-matters": "^0.4.0",
    "react-native-smooth-pincode-input": "^1.0.9",
    "react-native-snap-carousel": "^3.9.1",
    "react-native-splash-screen": "^3.2.0",
    "react-native-svg": "^12.1.1",
    "react-native-tab-view": "2.15.2",
    "react-native-vector-icons": "^8.1.0",
    "react-native-video": "^5.1.1",
    "react-native-video-controls": "^2.8.1",
    "react-native-view-pdf": "^0.11.0",
    "react-native-webview": "^11.6.4",
    "react-navigation-header-buttons": "^7.0.1",
    "react-redux": "^7.2.4",
    "redux": "^4.1.0",
    "redux-thunk": "^2.3.0",
    "socket.io-client": "^4.1.2",
    "validator": "^13.6.0"
  },
  "devDependencies": {
    "@babel/core": "^7.14.3",
    "@babel/plugin-proposal-decorators": "^7.14.3",
    "@babel/plugin-transform-flow-strip-types": "^7.14.3",
    "@babel/runtime": "^7.14.3",
    "@react-native-community/eslint-config": "^3.0.0",
    "@testing-library/jest-native": "^4.0.1",
    "@testing-library/react-native": "^7.2.0",
    "@types/jest": "^26.0.23",
    "babel-jest": "^27.0.2",
    "enzyme": "^3.11.0",
    "enzyme-adapter-react-16": "^1.15.6",
    "enzyme-to-json": "^3.6.2",
    "eslint": "^7.30.0",
    "identity-obj-proxy": "^3.0.0",
    "jest": "^27.0.2",
    "metro-react-native-babel-preset": "^0.66.1",
    "react-test-renderer": "17.0.2"
  }

**Comment by higoramp** [comment]
Same problem here, after updating from ReactNative 0.62 to 0.66

**Comment by JoshAntBrown** [comment]
Having a very similar problem here - but only when building by running `xcodebuild -destination 'generic/platform=iOS' ...` in the CLI and not targeting the simulator 🤔 

The app does build when running in xcode and targeting the simulator for me though.
