### ISSUE TITLE
React Native loading status bar almost hidden if Hide Status Bar is checked in XCode

### ISSUE THREAD

**Issue by ilyakar** [facebook/react-native#32290]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description

See this screenshot of the app loading. Notice how the react native loading info is cut off?

![IMG_57E30B6C69A0-2](https://user-images.githubusercontent.com/1760709/135181993-87a4230d-bf22-42b9-9da1-7fa765c9a33c.jpeg)

Issue came up after upgrading from React Native 0.63.x to 0.65.1.

It seems the bug occurs when you set Hide Status Bar for iPhone/iPad.
![image](https://user-images.githubusercontent.com/1760709/135182081-8b442658-a253-4b09-83ec-2393d1a80730.png)

Tested on a fresh install of React Native 0.65.1 with a dummy project. Same bug.

## React Native version:
System:
    OS: macOS 11.6
    CPU: (8) x64 Apple M1
    Memory: 43.03 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.19.0 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.2 - /Users/ilyakar/.gem/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 13.0/13A233 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.65.1 => 0.65.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
See above.

**Comment by ajnozari** [comment]
I'm having this issue on a new app as well.  Also using an M1 Mac.
