### ISSUE TITLE
React Native 0.65 - Xcode 13 - Release Schema is not compiling

### ISSUE THREAD

**Issue by nithinyell** [facebook/react-native#32301]
## Description
Tried upgrading to `react-native 0.65` with `Xcode 13`; able to compile in **debug mode but fails in release**.

## React Native version:
```
System:
    OS: macOS 11.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 48.90 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.12.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 13.0/13A233 - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.65.1 => 0.65.1
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```
## Steps To Reproduce
1. On the above environment setup, `run react-native init sampleApp`
2. Open Xcode and change schema to 'Release'
3. Run app, and you see the below error
<img width="1792" alt="Screenshot 2021-09-30 at 7 55 41 PM" src="https://user-images.githubusercontent.com/18254027/135474065-6635f1da-7d64-4083-bb2b-2c8c556ef1e6.png">

## Expected Results
App should compile in release schema

**Comment by mikehardy** [comment]
This is a known issue. It is resolved already.
@nithinyell please search for the string "thread-local" in this Podfile workaround snippet, it will get you moving

https://github.com/facebook/react-native/issues/31480#issuecomment-902912841
