### ISSUE TITLE
This section is no longer available Android toast issue

### ISSUE THREAD

**Issue by muhamedzeema** [facebook/react-native#32302]
Hello,
we do face some weird toast on android when opening our app from on devices (Samsung / Oppo), we made sure that we don't trigger any native android toasts / or any alerts from our backend. after searching for solution we found many cases for this but no one suggest a solution or something. 
1- [https://www.reddit.com/r/samsungs10/comments/phztw3/this_section_is_no_longer_available/](https://www.reddit.com/r/samsungs10/comments/phztw3/this_section_is_no_longer_available/)
2- [https://r2.community.samsung.com/t5/Galaxy-M/Why-this-msg-comes-on-the-screen-quot-this-section-is-no-longer/td-p/9478473](https://r2.community.samsung.com/t5/Galaxy-M/Why-this-msg-comes-on-the-screen-quot-this-section-is-no-longer/td-p/9478473)
please check the attached image.
Thank you

## React Native version:
System:
    OS: macOS 11.2.3
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 23.70 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.5 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.14 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.1, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 23, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.1, 30.0.2, 30.0.3
      System Images: android-26 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 12.1/12A7403 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_265 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: ^0.63.3 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
1. close the app 
2. open the app

## Expected Results
No toasts should be triggered.

## Snack, code example, screenshot, or link to a repository:
here is a screenshot 
![Screenshot_20210930-172425_Breadfast](https://user-images.githubusercontent.com/71822189/135485742-64a2a01e-2ef5-4cb8-a710-96706d22a8fe.jpg)

**Comment by vriksh-pillow** [comment]
How did you fix this?
