### ISSUE TITLE
`npx react-native init` new application won't run (React Native 0.66, macOS 11.6, Xcode 13.0)

### ISSUE THREAD

**Issue by madebyew** [facebook/react-native#32323]
## Description
** BUILD FAILED **
The following build commands failed:
CompileC /Users/my-username/Library/Developer/Xcode/DerivedData/AwesomeProject-gosjsvksbvgusscazfjiagvwmfqy/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RCT-Folly.build/Objects-normal/x86_64/FileUtil.o /Users/my-username/AwesomeProject/ios/Pods/RCT-Folly/folly/FileUtil.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'RCT-Folly' from project 'Pods')
(1 failure)

## React Native version:
System:
    OS: macOS 11.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 365.40 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.19.0 - ~/.nvm/versions/node/v12.19.0/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v12.19.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: 13.0/13A233 - /usr/bin/xcodebuild
  Languages:
    Java: 14.0.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.66.0 => 0.66.0
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
1. Run the following commands as shown on the Get Started page of the docs, to create a new application:
- `npx react-native init AwesomeProject`
- `cd AwesomeProject`
- `npx react-native start`
2. In a new terminal while Metro is running, run the following command: 
- `npx react-native run-ios`

## Expected Results
Expect the application to run on the simulator successfully.

**Comment by OmarJay1** [comment]
I had a similar problem and the following got the app to run:

1. cd ios, pod install.
2. Start an IPhone 12 simulator before running.

I'm finding XCode 13 a bit treacherous at this point, but it seems a simple react-native init app will run.

**Comment by madebyew** [comment]
@OmarJay1 Unfortunately your suggestion did not resolve the issue.

**Comment by neketabrain** [comment]
i have same issue

**Comment by azzastudios** [comment]
I have the same issue

**Comment by dawinValenzuela** [comment]
I have the same issue.

**Comment by azzastudios** [comment]
Has anyone found a solution or a work around to start a project?

**Comment by conzidev** [comment]
Not sure which step solves the issue, but I was able to run the project successfully by using these steps:

1.  Update Node to latest version (v16.10.0)
2. Update XCode build system from "Legacy" to "New Build System".
3. Delete Pods and run "pod install" afterwards (must be in ios folder).
4. Run npm install.
5. Then finally run Metro bundler "npx react-native start" and  App "npx react-native run-ios."

**Comment by dawinValenzuela** [comment]
Hello. I found a way to fix it. do the steps @conzidev mentioned but using the node version 14.17.0. I hope this can help.

**Comment by madebyew** [comment]
@OmarJay1 I can't see that it gives me any more info about the error. Regarding `pod install`, I don't actually seem to need to run this, as I think this is done automatically as part of `npx react-native init (app_name)`.

@dawinValenzuela Thanks for the suggestion. Although I still can't get a new app running, I seem to get fewer errors using Node 14.17.0 than any other version I have tried.

I have now tried various versions of Node (using `nvm`) but still cannot get a new app running.

The constants are:
- macOS 11.6
- Xcode 13.0

I have changed Xcode > Preferences > Locations > "Command line tools" from Xcode 13 to Xcode 12.5.1 but this doesn't resolve the issue so I have changed it back to 13.

Typically the steps I take are simply the following, as per the documentation:
- `npx react-native init AwesomeProject`
- `cd AwesomeProject`
- `npx react-native run-io`

It's at this point I get the build failure error(s). I have noticed the errors do not seem to be consistent, though the usually related to `RCT-Folly`. The most recent time I followed these steps I got the following error (which is different to other times):

```
The following build commands failed:

CompileC /Users/(my-username)/Library/Developer/Xcode/DerivedData/AwesomeProject-gosjsvksbvgusscazfjiagvwmfqy/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RCT-Folly.build/Objects-normal/x86_64/SysUio.o /Users/(my-username)/AwesomeProject/ios/Pods/RCT-Folly/folly/portability/SysUio.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'RCT-Folly' from project 'Pods')

CompileC /Users/(my-username)/Library/Developer/Xcode/DerivedData/AwesomeProject-gosjsvksbvgusscazfjiagvwmfqy/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RCT-Folly.build/Objects-normal/x86_64/NetOps.o /Users/(my-username)/AwesomeProject/ios/Pods/RCT-Folly/folly/net/NetOps.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'RCT-Folly' from project 'Pods')

(2 failures)
```

The running the exact same command again gives this:

```
The following build commands failed:

CompileC /Users/ed/Library/Developer/Xcode/DerivedData/AwesomeProject-gosjsvksbvgusscazfjiagvwmfqy/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RCT-Folly.build/Objects-normal/x86_64/SysUio.o /Users/ed/Repositories/Tasks\ by\ Striketype/AwesomeProject/ios/Pods/RCT-Folly/folly/portability/SysUio.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'RCT-Folly' from project 'Pods')

(1 failure)
```

I appreciate the suggestions so far and would welcome any other ideas.

**Comment by robertthecoder** [comment]
hi! were you able to find a solution to this error?

**Comment by robertthecoder** [comment]
I was able to get past this error by creating a new RN project inside a different parent folder

**Comment by robertthecoder** [comment]
No problem!I feel the same way about it and was surprised the folder name could cause this but at least it works now haha. 

If anyone figures out why this happens, please let me know :)

**Comment by madebyew** [comment]
I don’t think it will be the path name for me, as the path which doesn’t work now definitely used to work (and it has no unusual characters in it). I was thinking it might be because a previous version of something has been installed at that location (maybe to do with pods)?

**Comment by jimbo23** [comment]
After few hours of searching online, finally it works. 
Changing the parent directory does help to build the ios!

**Comment by anhnmVSII** [comment]
does anyone know why changing the parent directory helps?
