### ISSUE TITLE
Can't define color of ProgressBarAndroid

### ISSUE THREAD

**Issue by davidgilbertson** [facebook/react-native#3232]
I would like to be able to define the color of the `ProgressBarAndroid` component (the default spinner).

I notice in the facebook ads manager app it is a nice blue, was this done with a style in JS or down in Java somewhere?

**Comment by mkonicek** [comment]
I just grepped the fb codebase and don't see color for `ProgressBarAndroid` being set.

I don't think it's exposed? cc @andreicoman11

**Comment by mikearmstrong001** [comment]
The progress bar makes use of the apps theme. Ads Manager's theme has a blue accent which alters the look of the progress bar.

**Comment by andreicoman11** [comment]
It hasn't been exposed yet, but feel free do add it!
Color can be added as a property and then set on the progressBar itself in the following way: `progressBar.getIndeterminateDrawable().setColorFilter(color, PorterDuff.Mode.SRC_IN);`

**Comment by davidgilbertson** [comment]
@andreicoman11 could you point me in the right direction? Where do I get a reference to the progressBar to be able to call `getIndeterminateDrawable`?

Keep in mind I don't know Java or Android development.

**Comment by mrcasals** [comment]
I'm having the same issue. Current docs say the color can be set through the `color` property, but it doesn't seem to work:

https://github.com/facebook/react-native/blob/a797be6ffdd8fd9107cd8654b0c0d7c46ee2c6bb/Libraries/Components/ProgressBarAndroid/ProgressBarAndroid.android.js#L68

I've tried the following, but none seems to work:

```
<ProgressBarAndroid color"white" />
<ProgressBarAndroid color"#ffffff" />
```

**Comment by andreicoman11** [comment]
Fixed in https://github.com/facebook/react-native/commit/a797be6ffdd8fd9107cd8654b0c0d7c46ee2c6bb
