### ISSUE TITLE
[Android] TextView doesn't support letter spacing and padding

### ISSUE THREAD

**Issue by xinthink** [facebook/react-native#3233]
1.  `padding` of a TextView is ineffective, the dimension seems right, but the content is not placed correctly
2. the text (not the TextView) 'inherits' the background color, so it looks like there's an overlapped layer

![_2015-10-05_ 7_53_46](https://cloud.githubusercontent.com/assets/390805/10271080/78e60e18-6b37-11e5-8b9f-09cbdb86c3b0.png)

it should look like this:
![2015-10-05 7 49 50](https://cloud.githubusercontent.com/assets/390805/10271182/4bdcb0c2-6b3a-11e5-82ee-b1941d23264c.png)
- RN v0.11.4
- Android 5.1.1

code:

```
    <Text style={{
        backgroundColor: 'rgba(100,230,100,.7)',
        padding: 25,
        color: 'white',
        fontWeight: 'bold',
      }}
      >
      Hello
    </Text>
```

**Comment by andreicoman11** [comment]
Issue 2. has been fixed in https://github.com/facebook/react-native/commit/3b6d029a55efe1ffa5afcafe60d2d2445aadd502
I think @kmagiera has more context for issue 1.

**Comment by PhilippKrone** [comment]
@kmagiera Any idea what the reason for issue 1 could be?

**Comment by kmagiera** [comment]
Have you tried this on iOS by any chance. This is related to the fact that padding is implemented in layout algorithm by shifting children of the element by the value of padding. It means that it won't work by default on non View components. It shouldn't be that difficult to implement it, so PRs are welcome!

also cc @vjeux who may know if we support this on Text elements on iOS

**Comment by PhilippKrone** [comment]
@kmagiera It is supported on Text elements. See https://facebook.github.io/react-native/docs/text.html#content: Text has all properties of View, which again has the Flexbox properties, which includes padding :) It is working in iOS. I'm currently porting my app to android and found this issue as well, thats why I was asking for a solution in here.

**Comment by kmagiera** [comment]
In that case this piece is missing on android. It shouldn't be that difficult to add. One would need to update ReactTextShafiwNode to calculate padding into the result of measure, then expose setters for padding props in ReactTextManager and forward it to the view with setPadding.

We do sth similar for EditText as far as I remember.

If this is blocking you, you may try wrapping Text component in a View with padding

**Comment by richarddewit** [comment]
Any news on this?

**Comment by patoroco** [comment]
@richarddewit we're workaround padding issue wrapping `Text` in a `View`, and applying margin to it.

Margin seems to be work for both platforms.

**Comment by satya164** [comment]
Any updates on this?

**Comment by xinthink** [comment]
Tested on RN 0.17.0, the background issue is fixed, but the padding is still ineffective.

**Comment by kkgelu** [comment]
You can't image how surprised I was when first firing up my 'fine tuned' iOS version on Android...

**Comment by liamzebedee** [comment]
Anyone against adding this to the Known Issues page?

**Comment by A1ex5andr** [comment]
Have same issue with padding for android platform, 
no problems with iOS in the same time! Any chances to get that fixed soon?

**Comment by A1ex5andr** [comment]
The only "workaround" I found is to wrap <Text> into <View>.

**Comment by fab1an** [comment]
I think the only backwards compatible way to get proper tracking/letter-spacing on Android is using a wrapper like this, which inserts spaces between letters: http://stackoverflow.com/questions/1640659/how-to-adjust-text-kerning-in-android-textview/16429758#16429758

Please don't abuse `textScaleX` for it ;)

**Comment by GantMan** [comment]
Anyone know if this is gonna happen?  Padding sure would be nice.

**Comment by rburgst** [comment]
I would like to split this issue, since padding and letter spacing don't really have anything to do with each other. Padding should be easily fixable regardless of the letter spacing issue (which is much harder to fix).

**Comment by fab1an** [comment]
Actually letter-spacing could be trivially implemented with a component that splits the text by letters, creates a TextView for every letter and uses `scaleX` on the spaces only.

**Comment by rburgst** [comment]
Good luck implementing proper word wrapping with such an approach. At any rate, the solution for spacing will be probably quite different from the padding solution/fix.

**Comment by fab1an** [comment]
From a design point-of-view letter spacing ('tracking') is mainly used to make   A L L  C A P S  headlines more readable.

**Comment by dbuarque** [comment]
+1

**Comment by mquandalle** [comment]
I think point 1. was fixed in c3f2bba834a5ffcc42352bb738132baceafce76d.

**Comment by maraujop** [comment]
For those interested there is a new PR that fixes letter spacing in Android https://github.com/facebook/react-native/pull/9420 /cc @rburgst

**Comment by irfanayazfm** [comment]
@patoroco @A1ex5andr @kmagiera Can any of you guys explain how to get letter spacing by wrapping text inside a view? a code snippet would be of great help. Thanks

**Comment by teodors** [comment]
Here is a workaround in the meanwhile. 
http://stackoverflow.com/questions/38451278/letter-spacing-on-react-native-android

**Comment by dannycochran** [comment]
https://github.com/facebook/react-native/issues/3233#issuecomment-269200404 helps with letter spacing but not padding.

the workaround for putting the <Text> element inside a <View>, and applying padding to the <View> doesn't work if the <Text> is already nested within other <Text> elements. any chance this is something that could be fixed in Android? @andreicoman11

**Comment by jerolimov** [comment]
See also #13199

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/android-textview-doesnt-support-letter-spacing-and-padding

**Comment by zeh** [comment]
FWIW this is now being tracked as #17398 and waiting for review.
