### ISSUE TITLE
Sematic Issue Xcode 13

### ISSUE THREAD

**Issue by zoolle** [facebook/react-native#32330]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Please provide a clear and concise description of what the bug is. Include screenshots if needed.
Please test using the latest React Native release to make sure your issue has not already been fixed: https://reactnative.dev/docs/upgrading.html

Created a fresh new project using  `npx react-native init myproject` and opened the `myproject.xcworkspace` in Xcode 13. While Swift Conversion to Swift 5 I get Semantic Issue in RCT-Folly as follow: `Typedef redefinition with different types ('uint8_t' (aka 'unsigned char') vs 'enum clockid_t')` inside Time.h file

## React Native version:
Run `react-native info` in your terminal and copy the results here.

`System:
    OS: macOS 12.0
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 45.39 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.14.0 - ~/.nvm/versions/node/v15.14.0/bin/node
    Yarn: 1.23.0-20200928.1349 - ~/.yarn/bin/yarn
    npm: 7.7.6 - ~/.nvm/versions/node/v15.14.0/bin/npm
    Watchman: 2021.06.07.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 13.0/13A233 - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.0 => 0.66.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found`

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. npx react-native init myproject
2. open myproject.xcworkspace in Xcode 13 and start the conversion to Swift 5

## Expected Results
Describe what you expected to happen.

Convert the project

## Snack, code example, screenshot, or link to a repository:
Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by jeveloper** [comment]
@zoolle Thanks for filing this. I am seeing this as well. Curious if you're aware of how to prevent this from happening? 
Is swift 5 conversion necessary or can be disabled through flags?
Thanks

**Comment by jeveloper** [comment]
@zoolle Xcode 13.1 is about to get released to support ios 15.1 although does not guarantee this will work. 
FYI I am not bothering with changing everything (including appdelegate, etc) into swift although that is documented at this point.

**Comment by cuttlas** [comment]
Still happening in Xcode 13.1 and react-native 0.66

**Comment by keith212005** [comment]
You are a life saver! Thank you for the solution!
