### ISSUE TITLE
Build freezes on iOS device on release build when upgrading to 65 or 66

### ISSUE THREAD

**Issue by Vednus** [facebook/react-native#32348]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
When I upgrade to react native 65 or 66, and build my app, everything is fine on the simulator or device if running in debug mode, but when running in production on my ios device, the app freezes on the splash screen and gives an `(lldb)` error. And XCode highlights the line `return plain_.symbolToString(sym);` here: https://github.com/facebook/react-native/blob/1465c8f3874cdee8c325ab4a4916fda0b3e43bdb/ReactCommon/jsi/jsi/decorator.h#L187

## React Native version:
```
System:
    OS: macOS 11.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 396.09 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.7.0 - /usr/local/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 7.20.3 - /usr/local/bin/npm
    Watchman: 2021.08.02.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    Android SDK:
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7583922
    Xcode: 13.0/13A233 - /usr/bin/xcodebuild
  Languages:
    Java: javac 11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: ^0.66.0 => 0.66.0
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. build in xcode for device with release schema
2. app builds successfully but freezes on splash screen and xcode shows `lldb` in console.

## Expected Results
App moves on from splash screen

## Snack, code example, screenshot, or link to a repository:
![image](https://user-images.githubusercontent.com/2602014/136309135-f772bb93-1ccf-4964-a958-de381ad8ea4f.png)

Sorry for the vagueness. Just not much to go on and I've been stuck on it for a few days.

**Comment by crazySadSoul** [comment]
> The Same Problem. app builds successfully but freezes on splash screen.
> 
> it worked success on xcode12.5. but not work on xcode13.
> 
> anyone help me ?

did you fix? i have same problem

**Comment by Vednus** [comment]
Anyone figure this out?

**Comment by Vednus** [comment]
So, this one took me forever to figure out. `expo-gl` seems to be the culprit. I'm not actually using it, I had added it because I wanted to replace an older package with it, but never got around to it. So, I just removed it. Seems like this is already being looked at here: https://github.com/expo/expo/issues/16057 . I also upgraded expo from unimodules, so that could have helped as well.
