### ISSUE TITLE
[Windows] Add Hyper-V Android Emulator to react-native documentation.

### ISSUE THREAD

**Issue by BerndWessels** [facebook/react-native#3234]
A lot of developers, especially in the enterprise space are using Hyper-V on their machines. Unfortunately the default Android Emulator cannot be hardware accelerated if Hyper-V is turned on and turning it off is often not an option.

Fortunately there is a great and free android emulator that uses Hyper-V.

The [Visual Studio Emulator for Android](https://www.visualstudio.com/en-us/features/msft-android-emulator-vs.aspx). The [standalone download link](http://aka.ms/vscomemudownload) is at the bottom of that page. It doesn't require you to install Visual Studio at all.

It is free, very powerful, fast and you don't have to turn off your Hyper-V to use the default Android Emulator.

I think this information and the following instruction should make it into the official `react-native` `getting started guide`.

To use it with react-native you just have to add a key and value to your registry:

HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Android SDK Tools

String Value:
Name: Path
Value: C:\Program Files\Android\sdk

Obviously the path value might be different on your machine.

This emulator also need the `adb reverse tcp:8081 tcp:8081` command executed once before starting.

Then restart the emulator and when it is running you can just do `react-native run-android` as usual.

![visual studio emulator regedit](https://cloud.githubusercontent.com/assets/1776695/10271350/345ee936-6b69-11e5-8d64-165943d578a5.png)

**Comment by mikearmstrong001** [comment]
Thank you for the information you've provided

**Comment by satya164** [comment]
@BerndWessels Can you send a pull request to add this to the doc?

**Comment by BerndWessels** [comment]
@satya164 Happy New Year.
I added [this PR here](https://github.com/facebook/react-native/pull/5117).
Cheers
Bernd

**Comment by satya164** [comment]
@BerndWessels Thanks a lot. I've reviewed it. Let's get it merged soon :)

**Comment by BerndWessels** [comment]
@satya164 Great, looking forward to it.
I try to pave the way to get react and react-native into more enterprise companies which are (at least in NZ and DE) still mostly Windows and C# shops.
So everything that makes react easier to use on windows will increase its uptake hugely I believe.
Cheers
Bernd

**Comment by sinujohn** [comment]
Is this no longer supported? I can see this is removed in version 0.29

**Comment by faisal-nstu** [comment]
I cannot open the Dev Menu in VS Emulator for android. Any idea?

**Comment by ksk438** [comment]
Does Android Studio have to be installed in order to use  Visual Studio Emulator for react native?
