### ISSUE TITLE
[ios 15][xcode 13] error: index.js: Transformer is not a constructor

### ISSUE THREAD

**Issue by marcsumilang** [facebook/react-native#32342]
### Version

0.66.0

### Build Target(s)

ios simulator and real device issue

### Developer Environment

**### React-native info**
System:
    OS: macOS 11.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
    Memory: 184.68 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.10 - ~/.nvm/versions/node/v14.15.4/bin/npm
    Watchman: 2021.08.30.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: 13.0/13A233 - /usr/bin/xcodebuild
  Languages:
    Java: 14.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: ^5.0.1 => 5.0.1
    react: 17.0.2 => 17.0.2
    react-native: 0.66.0 => 0.66.0
    react-native-macos: ^0.63.14 => 0.63.38
  npmGlobalPackages:
    *react-native*: Not Found

### I have also done cleanup but the issue persists: 
watchman watch-del-all;
rm -rf yarn.lock;
rm -rf node_modules;
rm -rf $TMPDIR/react-*
rm -rf $TMPDIR/npm-*
cd ios
rm -rf Pods;
rm -rf Podfile.lock;
rm -rf build;
yarn cache clean
pod cache clean --all
cd ../android
rm -rf build
rm -rf ~/Library/Developer/Xcode/DerivedData

yarn install;
pod install;

### Issue: 
error: index.js: Transformer is not a constructor
I encounter this on both my simulator (iPhone 13  - ios 15) real device (iPhone 12 - ios 15)
i am using code 13

![image](https://user-images.githubusercontent.com/47217877/136134171-172d788d-6729-4e0e-8063-d0663c45b024.png)

### Issue and Reproduction Steps

react-native run-ios

**Comment by pep108** [comment]
this worked for me: https://albertoammar.medium.com/fix-index-js-transformer-is-not-a-constructor-in-react-native-0-6-e5b23c4bc998
