### ISSUE TITLE
> Transform's input file does not exist: myapp\node_modules\react-native-reanimated\android\react-native-reanimated-66-hermes.aar.  in v2.3.0-beta.2 (@next) on RN 0.66.0

### ISSUE THREAD

**Issue by coolusaHD** [facebook/react-native#32359]
Please provide all the information requested. Issues that do not follow this format are likely to stall.
-This is my first issue so if I can provide any more information just let me know

## Description
When I build my app for android it failed after installing react-native-reanimated v2.3.0-beta.2 
The main error line is ``> Transform's input file does not exist: C:\Users\alber\Desktop\app\myApp\node_modules\react-native-reanimated\android\react-native-reanimated-66-hermes.aar.``

## React Native version:
Run `react-native info` in your terminal and copy the results here.
System:
    OS: Windows 10 10.0.19043
    CPU: (20) x64 Intel(R) Core(TM) i9-10850K CPU @ 3.60GHz
    Memory: 10.44 GB / 31.81 GB
  Binaries:
    Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 7.24.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: Not Found
  Languages:
    Java: javac 17
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.66.0 => 0.66.0
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Installed @react-navigation/drawer so for dependencies also installed **react-native-reanimated**
2. re build the app with errors

## Expected Results
Describe what you expected to happen.
start the app normally

## code example, screenshot, or link to a repository:
```
> MyApp@0.0.1 android
> react-native run-android

info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 1046 file(s) to forward-jetify. Using 20 workers...
info JS server already running.
Der Befehl "adb" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
info Launching emulator...
error Failed to launch emulator. Reason: No emulators found as an output of `emulator -list-avds`.
warn Please launch an emulator manually or connect a device. Otherwise app may fail to launch.
info Installing the app...
> Task :app:checkDebugAarMetadata FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/7.0.2/userguide/command_line_interface.html#sec:command_line_warnings
13 actionable tasks: 2 executed, 11 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform react-native-reanimated-66-hermes.aar (project :react-native-reanimated) to match attributes {artifactType=android-aar-metadata}.
      > Execution failed for JetifyTransform: C:\Users\alber\Desktop\app\myApp\node_modules\react-native-reanimated\android\react-native-reanimated-66-hermes.aar.
         > Transform's input file does not exist: C:\Users\alber\Desktop\app\myApp\node_modules\react-native-reanimated\android\react-native-reanimated-66-hermes.aar. (See https://issuetracker.google.com/issues/158753935)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform react-native-reanimated-66-hermes.aar (project :react-native-reanimated) to match attributes {artifactType=android-aar-metadata}.
      > Execution failed for JetifyTransform: C:\Users\alber\Desktop\app\myApp\node_modules\react-native-reanimated\android\react-native-reanimated-66-hermes.aar.
         > Transform's input file does not exist: C:\Users\alber\Desktop\app\myApp\node_modules\react-native-reanimated\android\react-native-reanimated-66-hermes.aar. (See https://issuetracker.google.com/issues/158753935)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s

    at makeError (C:\Users\alber\Desktop\app\myApp\node_modules\@react-native-community\cli-platform-android\node_modules\execa\index.js:174:9)
    at C:\Users\alber\Desktop\app\myApp\node_modules\@react-native-community\cli-platform-android\node_modules\execa\index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async runOnAllDevices (C:\Users\alber\Desktop\app\myApp\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:106:5)
    at async Command.handleAction (C:\Users\alber\Desktop\app\myApp\node_modules\@react-native-community\cli\build\index.js:192:9)
info Run CLI with --verbose flag for more details.

```

So the part where I think the problems happens that it cant find the react-native-reanimated-66-jsc.aar file.

I looked up in the folder and also cant find them.
![image](https://user-images.githubusercontent.com/56646413/136552701-57f63b98-dfc8-4884-933f-f4a6273aad34.png)

## What I already did

I updated everything.
I deleted the node_modules folder and installed again
I also cleared cache and biuld again
I searched for other issues but all I found was about the react-native-reanimated-**65**-jsc.aar file which I have.
I checked package.json for the correct version

I also installed the react-native-reanimated package like it was described in the docs on https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation

Can someone help me how to add this file ?

Sincerly

**Comment by coolusaHD** [comment]
> didn't help me. did `npm install react-native-reanimated@next`
> 

You need the beta.2 version
@next dont install the newest one in that case

**Comment by valery-lavrik** [comment]
is this a react-native problem or a reanimator?

**Comment by coolusaHD** [comment]
this is a react-native-reanimated issue and i already created an issue on their repo
