### ISSUE TITLE
[Android] <TextInput> can't set border's style.

### ISSUE THREAD

**Issue by yinzSE** [facebook/react-native#3237]
Hi, How to set `<TextInput>` style ?

`borderColor` seems no effect, and how to remove default bottom border?

**Comment by chirag04** [comment]
related discussion here: https://github.com/facebook/react-native/issues/3182

**Comment by andreicoman11** [comment]
The default bottom border cannot be removed, you can make it transparent though (by setting underlineTextColor).
Borders are currently not supported on TextInputs, bout you can wrap your TextInput in a View and add borders to that component.

**Comment by brentvatne** [comment]
@andreicoman11 - could you add that to the known issues docs?

**Comment by andreicoman11** [comment]
https://github.com/facebook/react-native/blob/master/docs/KnownIssues.md#text-input-border

**Comment by yinzSE** [comment]
got it

**Comment by jainmitesh09** [comment]
Set  multiline={true} in the text input properties

**Comment by mdamien** [comment]
Previous given link is now broken.

solution is to use `underlineColorAndroid="transparent"` on the `TextInput`

source: https://facebook.github.io/react-native/releases/0.26/docs/known-issues.html#text-input-border ([archive](https://archive.fo/ZUZd7))
