### ISSUE TITLE
Could not build module "CoreFoundation" in RNCallKeep

### ISSUE THREAD

**Issue by SidMalladi** [facebook/react-native#32389]
### Version

0.66.0

### Build Target(s)

iOS Simulator/Phone

### Developer Environment

MacOS 15. XCode 12.

### Issue and Reproduction Steps

This issue bugged me a lot for the last 2 days and there didn't seem to be any open/closed previous issues regarding this.

#21482 briefly mentioned this issue, but its an older release and the solutions listed did not help me at all.

Answer/Solution: 
**You go to your respective project folder -> node_modules -> react-native call-keep -> iOS -> open the workspace file.**

Go to the build settings and under the "Library Header Files"... add the following and save it:

$(SRCROOT)/../../../ios/Pods/Headers/Public/React-Core
[](url)
$(SRCROOT)/../../react-native/React

$(SRCROOT)/../../react-native/React-Core

$(SRCROOT)/../../react-native/ReactCommon

$(SRCROOT)/../../react-native/ReactComponent

**Comment by lunaleaps** [comment]
Can you provide a stack trace? Currently, this issue doesn't offer much information about the error or steps for reproduction. Please re-open with more information
