### ISSUE TITLE
Docs update: Load Android Activity (Fragment) inside RN Native Component

### ISSUE THREAD

**Issue by wilsolutions** [facebook/react-native#32414]
## Description
I have a RN Native Component and I would like to load the Android Activity inside of it.

From the RN Docs I see that there is a way to load the RN App inside an Android Native App, I need the other way around and looks likes there are a bunch of other people looking for this, would be nice to update the docs with such info.

I know that is not possible to load the Activity inside the RN Native Component but do you know any workaround? 
Maybe using an Android Fragment? Convert the Activity code into a Fragment?
Thoughts?

## React Native version:
0.64

## Steps To Reproduce
1. Create a RN Native Component
2. Try to load an Native Android Activity inside the new RN Native Component.

## Expected Results
The Activity is initialized and displayed inside the Native Component or inside a RN View.

## Snack, code example, screenshot, or link to a repository:
https://stackoverflow.com/questions/69562692/display-android-native-activity-into-react-native-view

**Comment by ammarahm-ed** [comment]
> Yep, that's the direction I'm taking however how can developers proceed? 
> Do we convert the Activity to Fragment? 
> What are things that one should keep an eye on during the process?
> 
> Such information is not available in the docs, and per what I've seen there is a bunch of people looking for this.

You should look at the docs, how Native Components are built in android and iOS. Use that instead of an Activity.
