### ISSUE TITLE
FBReactNativeSpec failure

### ISSUE THREAD

**Issue by lunaleaps** [facebook/react-native#32417]
### Version

0.67.0-rc.0

### Build Target(s)

iOS simulator 

### Developer Environment

Xcode: 12.5
debug, jsc

## Error

```
PhaseScriptExecution [CP-User]\ Generate\ Specs /Users/luwe/Library/Developer/Xcode/DerivedData/RNTestProject-fuvojyehejebtlcjemnkidsxlmcl/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FBReactNativeSpec.build/Script-5F4C70EF7D90A5A5BDAEB404279F232A.sh (in target 'FBReactNativeSpec' from project 'Pods')
```
## Steps to reproduce
Follow pre-reqs, steps in release-testing wiki up to step 3: 
https://github.com/facebook/react-native/wiki/Release-Testing#steps

Then go through template testing flow in `./scripts/test-manual-e2e.sh`, basically you can probably run the script starting from [here](https://github.com/facebook/react-native/blob/0.67-stable/scripts/test-manual-e2e.sh#L104) and comment out all the RNTester testing logic before. 

Running template Android app works, but once the script prompts you to open Xcode and hit build I get the above error in the `FBReactNativeSpec` build step.

**Comment by 39otrebla** [comment]
@lunaleaps did you solve it? We have exactly the same issue, although we performed the steps required for migrating from RN 0.66.3 to 0.67.0-rc4

**Comment by lunaleaps** [comment]
Can you open an issue here: https://github.com/facebook/react-native/issues/new?assignees=&labels=Needs%3A+Triage+%3Amag%3A%2CType%3A+Upgrade+Issue&template=upgrade-regression-form.yml

**Comment by kopax-polyconseil** [comment]
I have the same issue here, where is the new issue ?

**Comment by kesha-antonov** [comment]
Same issue

**Comment by lunaleaps** [comment]
If folks are experiencing a build regression or issue, please file a new issue as this one is closed. Locking issue
