### ISSUE TITLE
Add images of native components

### ISSUE THREAD

**Issue by austinlyons** [facebook/react-native#3242]
It would be nice to have a screenshot of what each component looks like when it's rendered. I'm new to native app development, so when I'm skimming the docs and come across a component like [StatusBarIOS](https://facebook.github.io/react-native/docs/statusbarios.html) I'm not 100% what it is without an image.

**Comment by chirag04** [comment]
+1

**Comment by ide** [comment]
Have you seen the UIExplorer? It is a better version of what you are looking for since you can use the components and understand their behavior too.

**Comment by chirag04** [comment]
UIExplorer is great but can be broken on master. I couldn't get it to work on android the other day. I just wanted to see what ProgressBarAndroid was. I did figure out after some googling but experience could have been much better with just a screenshot tho.

**Comment by ide** [comment]
The important thing is the cost of maintenance. If someone can commit the time to keep the images up-to-date then I will stamp the PR.

**Comment by chirag04** [comment]
Agreed. Cost of maintenance would be crazy. Only if we could figure out an automated way of doing it. 
Every component/module corresponds to an UIExplorer demo and the screenshot automatically while building the docs.

**Comment by austinlyons** [comment]
I had not seen UIExplorer. [This](http://www.reactnative.com/uiexplorer/) is pretty awesome, it's UIExplorer runnable in your browser. Not sure about your thoughts on whether it's OK to link to this third party site, but that could be helpful. Or even just being more explicit about UIExplorer example in the React Native docs.

**Comment by ide** [comment]
Yeah, I think the UIExplorer should be made a lot more prominent. We deleted the Sample App and tell people to run the UIExplorer instead, but it's hard to get set up on Android. It's the best app to start with, though, because you can browse through it for components you want and then read the source code to learn how to use them. Myself and a couple other people started off that way and found more success than reading docs, I recommend it.

**Comment by austinlyons** [comment]
:+1: thanks
