### ISSUE TITLE
Weird build failure on Xcode after updating to RN 0.66.1

### ISSUE THREAD

**Issue by gabimoncha** [facebook/react-native#32432]
## Description
After updating RN from 0.65.1 to 0.66.1, my iOS builds were failing with the following errors.

<img width="497" alt="Screenshot 2021-10-18 at 17 15 49" src="https://user-images.githubusercontent.com/39256258/137748781-0f51b876-c215-43c9-8671-4edb2bd9cf8b.png">

I thought one of the libraries I'm using is not compatible with the new version, so I've started a new project from the typescript template and added them one by one.
I turned out that that every time I add a new library with a native change, I get this error message and the only way to bypass it is by cleaning the project and restarting it with the following commands.

`rm -rf node_modules ios/build ios/Pods ios/Podfile.lock && yarn cache clean`
`yarn && cd ios && pod install && cd ../`
`yarn start --reset-cache`

## React Native version:
```
System:
    OS: macOS 11.6
    CPU: (8) arm64 Apple M1
    Memory: 353.69 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.9.1 - /opt/homebrew/bin/node
    Yarn: 1.22.11 - /opt/homebrew/bin/yarn
    npm: 7.21.1 - /opt/homebrew/bin/npm
    Watchman: 2021.09.13.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 29, 30, 31
      Build Tools: 29.0.2, 30.0.2, 31.0.0
      System Images: android-31 | ARM 64 v8a, android-31 | Google APIs ARM 64 v8a, android-31 | Google Play ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 13.0/13A233 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.1 => 0.66.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
1. Init a new project (I tested only on Typescript)
2. Install dependencies, build from Xcode
3. Install a library any native change so that you can pod install after too (I guarantee it works with the following: react-native-svg + react-native-svg-transformer, react-native-reanimated, react-native-device-info, react-native-dotenv, react-native-file-logger, react-native-safe-area-context)
4. Restart metro and rebuild from Xcode

## Expected Results
App should build successfully as it normally does.

**Comment by gabrielmoncea** [comment]
@lunaleaps I don't think this issue should be closed and I'm not sure if this is an upgrade issue.

**Comment by pratibhashali** [comment]
HI @facebook, Thank you for wasting 6hr of my day.

> @J6ey @askndaer1 Hello, i want to share this even though i am in total disbelief that i could get it working because of this.
> 
> I had to make sure to place the project (so when i type `npx react-native init AppName`) in a folder route that must not include any spaces.
> 
> This will cause errors `~ cd Desktop/this\ wont\ work && npx react-native init AppName` This will work flawlessly `~ cd Desktop/this-will/ && npx react-native init AppName`
> 
> Some info about my config:
> 
> * I have installed pod (v 1.11.2) through `sudo gem install cocoapods` and i also had to install ffi, with the same command, since it is recommended for mac M1 users.
> * Latest node version, through homebrew `brew install node`
> * Xcode 13.1
> 
> Please let me know if your issues can be solved by checking this painfully simple thing.

The above worked.

**Comment by den666** [comment]
> HI @facebook, Thank you for wasting 6hr of my day.
> 
> > @J6ey @askndaer1 Hello, i want to share this even though i am in total disbelief that i could get it working because of this.
> > I had to make sure to place the project (so when i type `npx react-native init AppName`) in a folder route that must not include any spaces.
> > This will cause errors `~ cd Desktop/this\ wont\ work && npx react-native init AppName` This will work flawlessly `~ cd Desktop/this-will/ && npx react-native init AppName`
> > Some info about my config:
> > 
> > * I have installed pod (v 1.11.2) through `sudo gem install cocoapods` and i also had to install ffi, with the same command, since it is recommended for mac M1 users.
> > * Latest node version, through homebrew `brew install node`
> > * Xcode 13.1
> > 
> > Please let me know if your issues can be solved by checking this painfully simple thing.
> 
> The above worked.

8 hours for me, and it still doesn't work

**Comment by Fedeorlandau** [comment]
Same thing happening to me :(

**Comment by Dovydastc** [comment]
Upgrading react-native to 0.61.3 fixed an issue for me!

**Comment by Fedeorlandau** [comment]
Upgrading to the latest RN version fixed it. 0.66.3

**Comment by chengsam** [comment]
> > > HI @facebook, Thank you for wasting 6hr of my day.
> > > > @J6ey @askndaer1 Hello, i want to share this even though i am in total disbelief that i could get it working because of this.
> > > > I had to make sure to place the project (so when i type `npx react-native init AppName`) in a folder route that must not include any spaces.
> > > > This will cause errors `~ cd Desktop/this\ wont\ work && npx react-native init AppName` This will work flawlessly `~ cd Desktop/this-will/ && npx react-native init AppName`
> > > > Some info about my config:
> > > > 
> > > > * I have installed pod (v 1.11.2) through `sudo gem install cocoapods` and i also had to install ffi, with the same command, since it is recommended for mac M1 users.
> > > > * Latest node version, through homebrew `brew install node`
> > > > * Xcode 13.1
> > > > 
> > > > Please let me know if your issues can be solved by checking this painfully simple thing.
> > > 
> > > 
> > > The above worked.
> > 
> > 
> > 8 hours for me, and it still doesn't work
> 
> not work for me. any idea?

As mentioned by others, upgrading your react native version should work.

**Comment by habiiev** [comment]
We tried to upgrade from `0.64.2` to `0.68.1` and started getting this issue

<img width="568" alt="Screenshot 2022-04-26 at 11 45 12" src="https://user-images.githubusercontent.com/31899678/165260841-557ba62d-a4f4-430b-89e3-006d283771c4.png">

Tried to:
- Install the latest version of `cocoapods` and `ffi` (also 1.11.2 as mention in the comment)
- Different versions of node (14, 15, 16)

Nothing helped

The project path doesn't have any spaces inside of it
XCode version 13.3.1

**Comment by adnansudozai** [comment]
> @Deepacks I had the same issue on "react-native": "0.66.1" Changing back to "react-native": "0.65.1" in the package.json, then `npm install`, `pod update`, `pod install` fixed it for me!
> 
> Also be sure to comment out `__apply_Xcode_12_5_M1_post_install_workaround(installer)`

Thanks its work for me

**Comment by alerighi** [comment]
I have the same issue on a Mac M1. Is this issue caused by the ARM architecture? Is there a workaround for it, or do I need to downgrade to Expo 44?

**Comment by WNemencha** [comment]
I'm on an Intel mac so not linked to M1

**Comment by alerighi** [comment]
I've tried on a Intel MAC and the build is successful. To give some context, I'm using fastlane to build the application (the M1 Mac is used for the CI process). I really have no idea on how to solve the issue, I've tried everything.

**Comment by alerighi** [comment]
It seem to generate some files but are in a directory out/ inside the directory where the file would normally be placed.

I have node installed with brew rather than with nvm. Can it be a problem since I'm using a arm version of node?

**Comment by alerighi** [comment]
Finaly found the issue! I traced it down to a difference in how cp command from GNU Coreutils and the BSD one in MacOS works. The `cp -R` command is used in the last phase of the script that script_phase.sh, that copies the files from a temporary directory (`out/`) to the final destination launched this command:

```bash
cp -R "build/generated/ios/out/" "build/generated/ios"
``` 

GNU Coreutils cp interpret this as copy the directory `build/generated/ios/out/` to `build/generated/ios/out`, which are the same file, and thus the command fails, while BSD interpret this as copy `build/generated/ios/out/*` to `build/generated/ios/` (by the way, it's not clear to me what behavior is POSIX compliant, it seem to me the second one).

By removing the GNU Coreutils from the PATH it works as expected (I did have them in PATH since I mainly use Linux and I'm used to them). A mystery solved.

**Comment by suyashvash** [comment]
> @Deepacks I had the same issue on "react-native": "0.66.1" Changing back to "react-native": "0.65.1" in the package.json, then `npm install`, `pod update`, `pod install` fixed it for me!
> 
> Also be sure to comment out `__apply_Xcode_12_5_M1_post_install_workaround(installer)`

Dude, you saved my day. Literally worked just by doing these changes. I was struggling with it for days. Thanks, buddy.

**Comment by rrameshbtech** [comment]
Tried most. But none of the solution works. Its brand new solution after `npx react-native init`. not sure how to continue.

**Comment by Joshuapwilley** [comment]
> Finaly found the issue! I traced it down to a difference in how cp command from GNU Coreutils and the BSD one in MacOS works. The `cp -R` command is used in the last phase of the script that script_phase.sh, that copies the files from a temporary directory (`out/`) to the final destination launched this command:
> 
> ```shell
> cp -R "build/generated/ios/out/" "build/generated/ios"
> ```
> 
> GNU Coreutils cp interpret this as copy the directory `build/generated/ios/out/` to `build/generated/ios/out`, which are the same file, and thus the command fails, while BSD interpret this as copy `build/generated/ios/out/*` to `build/generated/ios/` (by the way, it's not clear to me what behavior is POSIX compliant, it seem to me the second one).
> 
> By removing the GNU Coreutils from the PATH it works as expected (I did have them in PATH since I mainly use Linux and I'm used to them). A mystery solved.

For anyone else experiencing this issue, another solution is to use patch-package to patch this file:
`node_modules/react-native/scripts/react_native_pods_utils/script_phases.sh`

Change this line:
`cp -R "$TEMP_OUTPUT_DIR/" "$RCT_SCRIPT_OUTPUT_DIR" || exit 1`

To this:
`cp -R "$TEMP_OUTPUT_DIR/." "$RCT_SCRIPT_OUTPUT_DIR/." || exit 1`

This change should make this work with GNU and BSD.

**Comment by kelset** [comment]
@Joshuapwilley anything preventing the change you are suggesting to be submitted as a PR? Is there one out already?

**Comment by acshi** [comment]
For anyone else reading this. The only thing I have had success with was using:
`RCT_NEW_ARCH_ENABLED=1 pod install` or rather `RCT_NEW_ARCH_ENABLED=1 arch -x86_64 pod install` on my M1 Mac, as the  `cp -R "$TEMP_OUTPUT_DIR/." "$RCT_SCRIPT_OUTPUT_DIR/." || exit 1` change did nothing for me.

**Comment by shreeve** [comment]
@Joshuapwilley - https://github.com/facebook/react-native/pull/35382 has this merged.

```diff
    # Copy all output to output_dir
-   cp -R "$TEMP_OUTPUT_DIR/" "$RCT_SCRIPT_OUTPUT_DIR" || exit 1
+   cp -R "$TEMP_OUTPUT_DIR/." "$RCT_SCRIPT_OUTPUT_DIR" || exit 1
```

This *one* byte commit (the "/." wasn't needed on the destination directory above) fixes the issues for our team (which is using the GNU coreutils version of the `cp` command).

Thanks for doing the hard work of finding this sucker.

**Comment by shreeve** [comment]
I made a little visual to show the difference in the `cp` command based on BSD (default on macOS) and GNU (Linux, likely Windows, and also used commonly on macOS). 

https://github.com/facebook/react-native/pull/35382#issuecomment-1325655433

**Comment by aramyesildeniz** [comment]
For me it was also the wrong `cp` command.
Only the BSD worked.

You can also change cp version Instead of changing `script_phases.sh`.

First check cp version with `which cp`:
```
/usr/local/bin/cp --> thats GNU
```
The BSD version is in
`/bin/cp`

Change with:
```
export PATH=/bin:$PATH
```
