### ISSUE TITLE
Release build stuck at app:bundleReleaseJsAndAssets [Android]

### ISSUE THREAD

**Issue by nitish1099** [facebook/react-native#32442]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
When making the release build the process gets stuck at app:bundleReleaseJsAndAssets

[Screenshot](https://snipboard.io/WufrGv.jpg)

## React Native version:
`System:
    OS: macOS 11.6
    CPU: (8) arm64 Apple M1
    Memory: 42.98 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
    npm: 6.12.1 - ~/.nvm/versions/node/v12.13.1/bin/npm
    Watchman: 2021.09.27.00 - /opt/homebrew/bin/watchman
  SDKs:
    Android SDK:
      API Levels: 29, 31
      Build Tools: 28.0.3, 31.0.0
      System Images: android-29 | Intel x86 Atom, android-29 | Intel x86 Atom_64, android-31 | Google APIs ARM 64 v8a
  IDEs:
    Xcode: /undefined - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.0 => 0.60.0`
  
## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. cd in to the project
2. npx react-native run-android --variant=release

## Expected Results
build successful

**Comment by cortinico** [comment]
Have you tried to `./gradlew --stop`, kill all the `java` processes and invoke the build again?
