### ISSUE TITLE
[bug][ios] main.jsbundle Invalid regular expression: Quantifier has nothing to repeat

### ISSUE THREAD

**Issue by aprilmintacpineda** [facebook/react-native#32453]
### Description

running in ios results to this error: `main.jsbundle Invalid regular expression: Quantifier has nothing to repeat`

It's referring to this:

```js
var matches = /(?<colorString>[a-f\d]{6}|[a-f\d]{3})/i.exec(hex.toString(16));
```

I found that there are 2 packages that has this code:

```
node_modules/pretty-format/node_modules/ansi-styles/index.js
node_modules/expect/node_modules/ansi-styles/index.js
```

https://github.com/chalk/ansi-styles/blob/main/index.js#L132

I have tried all that I can but can't find a way to fix this.

### Version

0.66.1

### Output of `react-native info`

```
System:
    OS: macOS 11.6
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Memory: 439.20 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.11.1 - /var/folders/zg/f6_98ss10lj5b841clyhsxlh0000gn/T/yarn--1634821924400-0.18107403147458956/node
    Yarn: 1.22.16 - /var/folders/zg/f6_98ss10lj5b841clyhsxlh0000gn/T/yarn--1634821924400-0.18107403147458956/yarn
    npm: 8.0.0 - ~/.nvm/versions/node/v16.11.1/bin/npm
    Watchman: 2021.10.11.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.2 - /Users/aprilmintacpineda/.rvm/gems/ruby-3.0.2/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 24, 26, 28, 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2
      System Images: android-24 | Google Play Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 13.0/13A233 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.66.1 => 0.66.1
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

build on ios

**Comment by aprilmintacpineda** [comment]
I found the following packages using `pretty-format`:

```
node_modules/jest-matcher-utils/package.json:    "pretty-format": "^27.3.1"
node_modules/react-native/package.json:    "pretty-format": "^26.5.2",
node_modules/jest-circus/package.json:    "pretty-format": "^27.3.1",
node_modules/@typescript-eslint/scope-manager/package.json:    "pretty-format": "*",
node_modules/@react-native-community/cli/package.json:    "pretty-format": "^26.6.2",
node_modules/@react-native-community/cli-server-api/package.json:    "pretty-format": "^26.6.2",
node_modules/jest-leak-detector/package.json:    "pretty-format": "^27.3.1"
node_modules/jest-snapshot/package.json:    "pretty-format": "^27.3.1",
node_modules/jest-message-util/package.json:    "pretty-format": "^27.3.1",
node_modules/jest-validate/package.json:    "pretty-format": "^27.3.1"
node_modules/jest-each/package.json:    "pretty-format": "^27.3.1"
node_modules/metro-config/node_modules/jest-validate/package.json:    "pretty-format": "^26.6.2"
node_modules/metro-config/package.json:    "pretty-format": "^26.5.2",
node_modules/jest-jasmine2/package.json:    "pretty-format": "^27.3.1",
node_modules/jest-diff/package.json:    "pretty-format": "^27.3.1"
node_modules/jest-config/package.json:    "pretty-format": "^27.3.1"
```

and these packages using expect:

```
node_modules/fast-glob/node_modules/glob-parent/package.json:    "expect": "^1.20.2",
node_modules/glob-parent/package.json:    "expect": "^26.0.1",
node_modules/jest-circus/package.json:    "expect": "^27.3.1",
node_modules/jest-jasmine2/package.json:    "expect": "^27.3.1",
node_modules/jest-snapshot/package.json:    "expect": "^27.3.1",
```

Which, consequently uses `ansi-styles`

**Comment by aprilmintacpineda** [comment]
Found it, damn, it was the autocomplete, it imported `import { validate } from 'jest-validate';` instead of a local file.

**Comment by yberstad** [comment]
@aprilmintacpineda, I'm experiencing the same issue now. 

I did not quite get how you solved it? Could you please give me a hint? 

Thanks in advance!

**Comment by yberstad** [comment]
I found a solution, but probably not optimal, anyway here it goes...
 
I have considered the following:
- One suggestion I found was to disable hermes in Podfile for development, but I want have the same environment while developing as in production, so that was no option. 
- Use patch-package, but since there where so many other dependencies and different versions of `ansi-styles` I thought that would be a hassle to configure.
- I found it strange that the main.jsbundle would include all npm dev dependencies, but building for production was not an option.

I used the following two other questions to be able to exclude the `ansi-styles` package from main.jsbundle:
https://github.com/facebook/react-native/issues/14400#issuecomment-387017917
https://github.com/facebook/metro/issues/519#issuecomment-862073446

My metro.config.js:

```const OriginalResolver = require("metro-resolver");
const path = require("path");

const blacklistedModules = ["ansi-styles"];

module.exports = {
  transformer: {
    babelTransformerPath: require.resolve("react-native-typescript-transformer"),
  },
  resolver: {
    resolveRequest: (context, moduleName, platform) => {
      if (blacklistedModules.includes(moduleName)) {
        return {
          filePath: path.resolve(__dirname + "/shim-module.js"),
          type: "sourceFile"
        };
      } else {
        return OriginalResolver.resolve(
          { ...context, resolveRequest: undefined },
          moduleName,
          platform
        );
      }
    }
  }
};
```
 And then add `export BUNDLE_CONFIG=./metro.config.js` to `Bundle React Native code and images`.

**Comment by hatem-72** [comment]
Thanks @yberstad for your temporary fix! You saved my day.

To dig a bit this error is caused by [Hermes not supporting _Named capture groups_](https://github.com/facebook/hermes/blob/main/doc/RegExp.md). So basically for me both IOS and Android **release builds** are failing as Hermes is configured on both platforms.
In my case it happened just after setting up [react-native-gesture-handler](https://github.com/software-mansion/react-native-gesture-handler) in my RN 0.66.3 app.

Question is: why is this _ansi-styles_ suddenly embedded into release builds ?

**Comment by yberstad** [comment]
Hi @hatem-72!

Good to know!

I have also enabled Hermes for Android, but I did not get the same error there? I thought it was only and iOS issue, but when I think of it, I probably should have gotten an error on Android as well. Strange.

I'm also using  "react-native-gesture-handler": "1.10.3".

build.gradle:
```
project.ext.react = [
    entryFile: "index.android.js",
    enableHermes: true,  // clean and rebuild if changing,
    bundleInRelease: true
]
```

**Comment by bombillazo** [comment]
Hey @hatem-72 , @yberstad , I was able to build my app on Android by disabling Hermes. Previously, I was always able to build no problems but something happened in the repo that now fails any build due to this very line:
```js
var matches = /(?<colorString>[a-f\d]{6}|[a-f\d]{3})/i.exec(hex.toString(16));
```
Did any of you resolve the issue? any clue on how to use turn back on Hermes with RN without getting this error?

**Comment by Spoutnik97** [comment]
@aprilmintacpineda could you help us by sharing your fix please?

**Comment by aprilmintacpineda** [comment]
> Found it, damn, it was the autocomplete, it imported `import { validate } from 'jest-validate';` instead of a local file.

This was it in my case, I imported the wrong module.

**Comment by bombillazo** [comment]
Hello again, for those looking for a temporary fix, I ended up using [`patch-package`](https://www.npmjs.com/package/patch-package) and have [this change](https://github.com/chalk/ansi-styles/pull/78/files) done to my dependencies. Now it builds with Hermes!

Hopefully, they merge PR https://github.com/chalk/ansi-styles/pull/80 soon so the library works again without this patch.

**Comment by jahglow** [comment]
resolved this so far by adding resolution in `package.json`, probably not the best way, but the least troublesome. for some reason patch-package was complaining for me because it uses the same package
```json
  "resolutions": {
     "ansi-styles": "^4.3.0"
  }
```

**Comment by danilobuerger** [comment]
Hi, there is another solution by @neildhar: 

```bash
yarn add --dev @babel/plugin-transform-named-capturing-groups-regex
```

Modify your `babel.config.js` like so:

```diff
diff --git a/babel.config.js b/babel.config.js
index f842b77..d855f9b 100644
--- a/babel.config.js
+++ b/babel.config.js
@@ -1,3 +1,4 @@
 module.exports = {
+  plugins: ['@babel/plugin-transform-named-capturing-groups-regex'],
   presets: ['module:metro-react-native-babel-preset'],
 };
```

If you try out this solution could you please report back if that works for you and your setup?

**Comment by gpbaculio** [comment]
> Hi, there is another solution by @neildhar:
> 
> ```shell
> yarn add --dev @babel/plugin-transform-named-capturing-groups-regex
> ```
> 
> Modify your `babel.config.js` like so:
> 
> ```diff
> diff --git a/babel.config.js b/babel.config.js
> index f842b77..d855f9b 100644
> --- a/babel.config.js
> +++ b/babel.config.js
> @@ -1,3 +1,4 @@
>  module.exports = {
> +  plugins: ['@babel/plugin-transform-named-capturing-groups-regex'],
>    presets: ['module:metro-react-native-babel-preset'],
>  };
> ```
> 
> If you try out this solution could you please report back if that works for you and your setup?

This worked for me

**Comment by rranjan14** [comment]
I upgraded from 0.67.4 to 0.70.0. I tried this solution as well for android. Din't work for me.

**Comment by daileytj** [comment]
I upgraded to RN 0.70.0 and this doesn't work for me. I also tried to use `core-js` RegExp polyfill, but haven't found success there either.
