### ISSUE TITLE
Gradle sync failed: Cause: error=2, No such file or directory

### ISSUE THREAD

**Issue by josetech2logics** [facebook/react-native#32469]
### Description

![image](https://user-images.githubusercontent.com/90614765/138652581-bc37aa5e-4021-4442-b993-fd25e1e4ffca.png)

### Version

 react-native: 0.66.0 => 0.66.0

### Output of `react-native info`

OS: Linux 5.4 Linux Mint 19.3 (Tricia)
    CPU: (4) x64 Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz
    Memory: 1.37 GB / 11.57 GB
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 12.22.6 - /usr/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 6.14.15 - /usr/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.0 => 0.66.0 
  npmGlobalPackages:

### Steps to reproduce

Open react-native in android studio, Unable to run. Showing error .

### Snack, code example, screenshot, or link to a repository

![image](https://user-images.githubusercontent.com/90614765/138653765-fd639123-5adb-48ac-8484-ab0d0135d5ea.png)

**Comment by cortinico** [comment]
Have you tried to run Gradle from the terminal? What's the output?
