### ISSUE TITLE
[0.66.1] NativeAnimatedModule.getValue is not a function

### ISSUE THREAD

**Issue by lfoliveir4** [facebook/react-native#32464]
### Description

I currently have an expo project on a monorepo. When I upgraded React Native to version 0.66.1, when I build the app, it crashes the Animation API.

### Version

0.66.1

### Output of `react-native info`

![image](https://user-images.githubusercontent.com/32423942/138534013-2cd778d4-bfb5-4539-ad21-01e6f05df972.png)

### Steps to reproduce

At startup of my application running `yarn start`

**Comment by Pikazza** [comment]
@lfoliveir4 I fixed my issue. I used "react-native": "^0.66.1", but Expo SDK 42 support "react-native": "^0.63.0", So i just downgraded my ReactNative version. Now it's working fine.

**Comment by Bharanitharan06** [comment]
@lfoliveir4  I fixed my issue. I used "react-native": "^0.66.1", but Expo SDK 42 support "react-native": "^0.63.0", So i just downgraded my ReactNative version. Now it's working fine.

**Comment by avac-porch** [comment]
I will be out office until November 2.

**Comment by M-Ahmad-Asghar** [comment]
> I will be out office until November 2.

No worries
