### ISSUE TITLE
App shows blank white screen after being opened from background after a long period of time.

### ISSUE THREAD

**Issue by zaura-payments** [facebook/react-native#32475]
### Description

Hello, I am running into an issue with my React-Native app. The issue is present on both iOS and Android after building to a device. The issue isn't present during testing in Expo and there are no crashes or errors when this issue arises. 

My application opens fine and loads correctly the first time however if I leave my app in the background for a long period of time and then open it again, I am presented with a blank white screen. This only happens if the app is left in the background and then brought to the foreground and not when it is first launched. 

I should note I am using Sentry and it has not picked up any errors when this bug happens.

### Version

0.63

### Output of `react-native info`

System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
    Memory: 10.61 GB / 15.96 GB
  Binaries:
    Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7199119
    Visual Studio: Not Found
  Languages:
    Java: javac 16
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: ^0.63.1 => 0.63.4
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

This bug seems to be completely time orientated because if I leave the app in the background for 20 minutes and then open it, the bug is not present. However leaving it overnight or for long periods of time, the bug crops up.

- Run expo build:ios OR expo build:android
- Upload your build to Google Play Store or TestFlight
- Launch the app (works fine and loads)
- Dismiss the app/minimize (don't kill it)
- Leave the app in the background for a long period of time (est 8+ hours). 
- Open the app from the background and you are presented with a blank white screen.
- If you kill the app completely here and reopen then it will load properly.

**Comment by churchnotesapp** [comment]
Hey - did you manage to solve this bug? Any recommendations

**Comment by GaganBhakhar** [comment]
I am also facing the same issue, any updates?
