### ISSUE TITLE
Custom Dev Option `Debug` does not change to `Stop Debugging`

### ISSUE THREAD

**Issue by 4332weizi** [facebook/react-native#32487]
### Description

When the user toggles debugging mode, The Custom Dev Option `Debug` will not change to `Stop Debugging` until the `ReactNativeHost `is recreated.

### Version

0.66.1

### Output of `react-native info`

```
~/Projects/Android/taro-playground v1.2.0*
▶︎ yarn react-native info
yarn run v1.22.10
$ /Users/Victor/Projects/Android/taro-playground/node_modules/.bin/react-native info
info Fetching system and libraries information...
System:
    OS: macOS 11.6
    CPU: (8) arm64 Apple M1
    Memory: 116.27 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.12.0 - /var/folders/zy/4llfjccn18b91xnb2vb61f680000gn/T/yarn--1635392861139-0.36886178182733675/node
    Yarn: 1.22.10 - /var/folders/zy/4llfjccn18b91xnb2vb61f680000gn/T/yarn--1635392861139-0.36886178182733675/yarn
    npm: 7.6.3 - ~/.nvm/versions/node/v15.12.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7784292
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.12 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.2 => 17.0.2
    react-native: ^0.66.1 => 0.66.1
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
✨  Done in 9.76s.
```

### Steps to reproduce

run react-native demo project, toggle debugging mode

### Snack, code example, screenshot, or link to a repository

https://github.com/wuba/taro-playground/

https://github.com/facebook/react-native/commit/5f2fae0c2d96d5ed56b7f77338e67d3a8b76cf8d

**Comment by Off2Race** [comment]
I'm experiencing a similar issue with RN 0.66.4 on Android.

I created a brand new app that has nothing but the "Welcome to React Native" screen and console.log statements. If I run the app in the Android emulator and bring up the debug menu, I can see the "Debug" item. If I select it, the React Native Debugger in Chrome will activate and I can console messages. If I bring up the debug menu again, the "Debug" item is still there. If I select it, the app will refresh and debugging will stop (no more console messages). I can toggle back and forth this way but the name of the menu item will never change. It always says "Debug."

If I leave the app in a state where debugging is "on," shut down the app, and restart from the command line, the debug menu will change to "Stop Debugging" but never update after that. I can continue to toggle the debugging on and off but the name of the menu item will never change.

Originally, my test app had Hermes on, so I thought that might be the cause but I turned it off and still see the same thing. I validated this in another non-Hermes app and it does the same thing.

No issues on iOS.

**Comment by samleemcknight** [comment]
I'm experiencing this same problem just with the android build. Is there any update on this issue? This is my environment info:

```bash
System:
    OS: macOS 11.6.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 1.28 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.6 - ~/.nvm/versions/node/v14.17.6/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.17.6/bin/npm
    Watchman: 2022.02.07.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 28, 29, 30, 32
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 32.0.0, 32.1.0
      System Images: android-28 | Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-29 | Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-32 | Google Play ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8139111
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.14 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.2 => 0.67.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by SteveChina** [comment]
Hi, any update? Have any solution?
