### ISSUE TITLE
Unable to resolve module ./Libraries/Components/Picker/Picker

### ISSUE THREAD

**Issue by TamasFarago** [facebook/react-native#32485]
### Description

I upgraded React Native from 0.64 to 0.66 and after launching the app it gives me the following error

Unable to resolve module ./Libraries/Components/Picker/Picker

attached screenshot

### Version

0.66.1

### Output of `react-native info`

info Fetching system and libraries information...
(node:69495) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
System:
    OS: macOS 12.0.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 131.07 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.1 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.13 - /usr/local/bin/npm
    Watchman: 2021.09.13.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 23, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3
      System Images: android-28 | Intel x86 Atom_64, android-29 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7351085
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: ^0.66.0 => 0.66.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

upgrade to 0.66

### Snack, code example, screenshot, or link to a repository
![Simulator Screen Shot - iPhone 13 - 2021-10-27 at 15 41 35](https://user-images.githubusercontent.com/67281301/139077560-60e19453-e7f4-4cb0-848c-aa6a00c7b34c.png)

**Comment by nkvch** [comment]
Did you solve this? I have similar problem

**Comment by Marinaarimany** [comment]
Hello, I have the same problem now, can you help me please

**Comment by TamasFarago** [comment]
I downgraded to 0.65

**Comment by Marinaarimany** [comment]
> I downgraded to 0.64


Ah damn :/ Thank you for your solution

**Comment by shashinbhayani** [comment]
try `npx react-native start --reset-cache`

**Comment by lunaleaps** [comment]
Closing. We removed Picker in 0.66 and for versions > 0.66, you'll need to use a community supported Picker component as mentioned: https://reactnative.dev/docs/next/datepickerios
