### ISSUE TITLE
the npx react-native run-android is not working 

### ISSUE THREAD

**Issue by Moniem-JamSam** [facebook/react-native#32493]
### Description

hello , i move my project to my github account to work on it . after that the project doesn't work on github but it work in local project . 
i tried to clean the gradlew but that doesn't work with me if any one can help i will thankful 

 

### Version

0.65.1

### Output of `react-native info`

System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 2.51 GB / 15.85 GB
  Binaries:
    Node: 14.17.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.19.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7199119
    Visual Studio: Not Found
  Languages:
    Java: 11.0.2
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.65.1 => 0.65.1
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

in github desktop after i open  Visual Studio and run  react-native run-android  it become and the project not working but the emulator is working but with white screen 

### Snack, code example, screenshot, or link to a repository

 C:\Users\90505\Documents\GitHub\knowledgeHub> npx react-native run-android
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 985 file(s) to forward-jetify. Using 12 workers...
info Starting JS server...
warn Failed to automatically start the packager server. Please run "react-native start" manually. Error details: ENOENT: no such file or directory, open 'C:\Users\90505\Documents\GitHub\knowledgeHub\node_modules\react-native\scripts\.packager.bat'
* daemon not running; starting now at tcp:5037
* daemon started successfully
info Launching emulator...
info Successfully launched emulator.
info Installing the app...
Downloading https://services.gradle.org/distributions/gradle-6.9-all.zip
..............10%..............20%...............30%..............40%..............50%...............60%..............70%...............80%..............90%..............100%

Welcome to Gradle 6.9!

Here are the highlights of this release:
 - This is a small backport release.
 - Java 16 can be used to compile when used with Java toolchains
 - Dynamic versions can be used within plugin declarations
 - Native support for Apple Silicon processors

For more details see https://docs.gradle.org/6.9/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
Gradle could not start your build.
> Could not create service of type CrossBuildFileHashCache using BuildSessionServices.createCrossBuildFileHashCache().
   > Failed to create parent directory 'C:\Users\90505\Documents\GitHub\knowledgeHub\android\.gradle' when creating directory 'C:\Users\90505\Documents\GitHub\knowledgeHub\android\.gradle\6.9\fileHashes'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 4s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

* What went wrong:
Gradle could not start your build.
> Could not create service of type CrossBuildFileHashCache using BuildSessionServices.createCrossBuildFileHashCache().
   > Failed to create parent directory 'C:\Users\90505\Documents\GitHub\knowledgeHub\android\.gradle' when creating directory 'C:\Users\90505\Documents\GitHub\knowledgeHub\android\.gradle\6.9\fileHashes'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 4s

    at makeError (C:\Users\90505\Documents\GitHub\knowledgeHub\node_modules\execa\index.js:174:9)
    at C:\Users\90505\Documents\GitHub\knowledgeHub\node_modules\execa\index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async runOnAllDevices (C:\Users\90505\Documents\GitHub\knowledgeHub\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:106:5)
    at async Command.handleAction (C:\Users\90505\Documents\GitHub\knowledgeHub\node_modules\@react-native-community\cli\build\index.js:186:9)

**Comment by cortinico** [comment]
> Error details: ENOENT: no such file or directory, open 'C:\Users\90505\Documents\GitHub\knowledgeHub\node_modules\react-native\scripts.packager.bat'

That's the root of the problem. That file is missing. 
This is most likely unrelated to React Native. You should follow the instructions provided here: https://reactnative.dev/docs/environment-setup and your environment should be good to go.

**Comment by Moniem-JamSam** [comment]
> > Error details: ENOENT: no such file or directory, open 'C:\Users\90505\Documents\GitHub\knowledgeHub\node_modules\react-native\scripts.packager.bat'
> 
> That's the root of the problem. That file is missing. This is most likely unrelated to React Native. You should follow the instructions provided here: https://reactnative.dev/docs/environment-setup and your environment should be good to go.

but i already have a project and it work fine in my pc but in github vs not working , and i tried npm install and like that and it didn't work . and i i dont use EXPO

**Comment by cortinico** [comment]
> github vs

Do you mean Github Codespaces?
