### ISSUE TITLE
TextInput's onSelectionChange errantly reports selection index on iOS

### ISSUE THREAD

**Issue by rjohndean** [facebook/react-native#32499]
### Description

**Issue**
On iOS, the TextInput's onSelectionChange errantly reports a selection start of 1 if the user enters input rapidly.

**Effect**
If I rely on onSelectionChange to help me manage the input's selection cursor, the cursor will move to the beginning of the input mid-typing if the user is inputting too fast. This creates a broken user experience where midway through typing a string the user's cursor is reset to the beginning of the string.

**Expected Result**
The onSelectionChange event should accurately report the cursor position as the user is typing.

### Version

0.63.4

### Output of `react-native info`

System:
    OS: macOS 11.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 2.55 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.22.3 - /usr/local/opt/node@12/bin/node
    Yarn: Not Found
    npm: 6.14.13 - /usr/local/opt/node@12/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 30.0.2, 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7486908
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_302 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Please see snack below for a minimum repro.

### Snack, code example, screenshot, or link to a repository

https://snack.expo.dev/@rjohndean/ios-onselectionchange-bug-example

**Comment by rjohndean** [comment]
bump

**Comment by hebingchang** [comment]
same here. any updates?

**Comment by rjohndean** [comment]
bump

**Comment by zhangzhengqiqi** [comment]
the same question, [IOS] ,use selection and onSelectionChange in textInput ,  the cursor will jump to position '0' as long as user input anything.
