### ISSUE TITLE
Nested ScrollView inside paginated FlatList not snapping (Android)

### ISSUE THREAD

**Issue by MishaFrenkman** [facebook/react-native#32495]
### Description

Usecase: Nesting a ScrollView inside a paginating FlatList. Something like a Feed with Text Components that needs scrolling.

Problem: Using `nestedScrollEnabled` prop for Android for the inner ScrollView to work at all. But when scrolling it to the end, the panResponder changes to the outer FlatList like it should, but it's disregarding the `pagingEnabled` prop and just scrolls regularly without snapping to previous or next item of the FlatList.

This issue occurs only on Android, iOS works as expected.

### Version

0.64.2

### Output of `react-native info`

System:
    OS: macOS 11.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 2.93 GB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.17.0/bin/yarn
    npm: 7.20.2 - ~/.nvm/versions/node/v14.17.0/bin/npm
    Watchman: 2021.09.13.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7784292
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.9.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.2 => 0.64.2
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

```js

const data = [
  {
    color: '#f00',
  }, {
    color: '#0f0',
  }, {
    color: '#00f',
  }
]

export default function App() {

  const { height } = Dimensions.get('screen');
  const renderItem = ({ item, idx }) => {
    return (
      <View style={{ backgroundColor: item.color, height, width: '100%' }}>
        <ScrollView nestedScrollEnabled>
          <Text>
           input long text here...
          </Text>
        </ScrollView>
      </View>
    )
  }

  return (
    <FlatList data={data} renderItem={renderItem} pagingEnabled />
  );
}
```

**Comment by Yonom** [comment]
Possibly related commit https://github.com/facebook/react-native/commit/4ad4426daf51903574f81aff1b773645a16831e0 from @JoshuaGross 

I just tested your code in RN 0.66 (with the commit above applied), the issue is definitely still there, but it happens less frequently
