### ISSUE TITLE
How to vertical center and horizontal center  <Text>xxx/<Text> ?

### ISSUE THREAD

**Issue by KJlmfe** [facebook/react-native#325]
I write code as below:

alignSelf: 'center',
height: 100,
lineHeight: 100

But it's not work for vertical center.

**Comment by dbanck** [comment]
Use flexbox for the surrounding view:
```
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
```
This will center any content.

**Comment by KJlmfe** [comment]
justifyContent: 'center', 
    alignItems: 'center' 

It's works!

**Comment by milkers** [comment]
For me I also needed to update lineHeight according to the fontSize.

**Comment by brunoreis** [comment]
It seems that on iOS you need to:
```
justifyContent:'center',
lineHeight:13,
fontSize:13
```
Android seems to center align by default.

**Comment by pacozaa** [comment]
https://github.com/react-native-community/react-native-svg/issues/308

Useful link is here!

**Comment by rainbowhat** [comment]
{{alignSelf: "center"}}

**Comment by AishwaryaSurana** [comment]
If the `<Text>` is multilined than none of the above things work
```

<View style = {{
    justifyContent: 'center',
    alignItems: 'center'}}>
          <Text style={{alignSelf:'center',fontSize:20,justifyContent:'center',alignItems:'center'}}>
             A very big multiline text that can not be accumulated in a single line is shown here with all the attributes trying to center it</Text>
        </View>
        
```

**Comment by Suraj-Tiwari** [comment]
@AishwaryaSurana I didn't tested your code but this one will be the easiest solution. Not just text you can align any content in `<View>`  tag. This will work with Everything.

`<View style={{justifyContent: 'center', flex: 1}}>
                    <Text style={{textAlign: 'center'}}>A very big multiline text that can not be accumulated in a single line is shown here with all the attributes trying to center it</Text>
                </View>`

**Comment by bezsinnyidmytro** [comment]
I don't sure that everyone understand the problem, encounered this issue many times. You have View which must have fixed width, height (circle for example: square with rounded corners 50%). This block can't have flex property, cause width or height (depending on flexDirection) wont work. You need to vertically and horizontaly align text of <Text> component inside this NON-flex block, textAlign will do horizontal alignment, lineHeight might do vertical alignment, but lineHeight on Android produces not the same result as on iOS...

**Comment by jfajardo** [comment]
Is magic!
`textAlign: 'center'`

**Comment by MacKentoch** [comment]
Talking about **vertical alignment**: sometimes on iOS and Android you may encounter a different behaviour.

In case you have a 
- `<Text/>` 
- surounded by a rounded `<View style={styles.roundedContainer} />` as a container 

when you apply a `borderWidth`fix iOS vertical alignment **by setting the paddingTop to this borderWith**, illustration:

```javascript
{
  roundedContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    height: 120,
    width: 120,
    borderRadius: 60,

    // iOS fix vertical alignment due to borderWidth:
    borderWidth: 15,
    ...Platform.select({ ios: { paddingTop: 15 }, android: {} }),

  }
}
```

I'm using a recent RN (0.51) and this may not be an issue due to RN but native behaviour (*I suppose didn't take time to check sources*).

**Comment by sumanpula** [comment]
Simple use this,

const styles = {
  textStyle: {
    fontSize: 18,
    alignSelf: 'center'
  }
};

**Comment by joeyespo** [comment]
The following worked for me (on RN `0.55.2`)

```
text: {
  fontSize: 24,
  textAlign: 'center',
  textAlignVertical: 'center',
},
```

Worked for both cases I needed - `<Text>` with `flex: 1` and when manually setting the height of the `<Text>` component.
