### ISSUE TITLE
DebugComponentOwnershipModule package error

### ISSUE THREAD

**Issue by liaohuqiu** [facebook/react-native#3250]
Should in `com.facebook.react.uimanager.debug;`

**Comment by ide** [comment]
@mkonicek should @liaohuqiu submit https://github.com/liaohuqiu/react-native/commit/2e7aa3afb4823a16800c434f4ed3b1ba5dacd7b1 as a PR? not sure if this a bug or not.

**Comment by mkonicek** [comment]
Fixed in https://github.com/facebook/react-native/commit/2944c665bfd030ecbdb624d67b67f3ccd2a85623
