### ISSUE TITLE
LogBox.ignoreLogs still prints to the console and causes a slowdown

### ISSUE THREAD

**Issue by Yonom** [facebook/react-native#32506]
### Description

Beginning with RN 0.65, `EventEmitter.removeListener` has been deprecated. 
Many libraries still use this deprecated API and it causes a ton of logs to be printed, to the point that app becomes laggy due to the massive amount of logs generated.

In RN 0.65, we solved this slowdown problem by ignoring these logs via `LogBox.ignoreLogs`. However, in RN 0.66.1 we are seeing the ignored logs messages still be printed to the console (but no longer appear in app if they are ignored via ignoreLogs). This is not ideal because it slows down the debugging experience significantly.

### Version

0.66.1

### Output of `react-native info`

System:
    OS: macOS 11.6
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Memory: 115.01 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - /var/folders/4l/5q_1bbc93mb221kpmsz41jth0000gn/T/yarn--1635663992158-0.4245439288517565/node
    Yarn: 1.22.17 - /var/folders/4l/5q_1bbc93mb221kpmsz41jth0000gn/T/yarn--1635663992158-0.4245439288517565/yarn
    npm: 8.1.0 - /usr/local/Cellar/node@16/16.13.0/bin/npm
    Watchman: 2021.10.18.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 23, 24, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 31.0.0, 31.0.0, 31.0.0, 31.0.0
      System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7784292
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.2 => 17.0.2 
    react-native: ^0.66.1 => 0.66.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. create a new project from template (using RN 0.66.1)
2. ignore EventEmitter.removeListener logs
```
LogBox.ignoreLogs([
  "EventEmitter.removeListener('",
]);
```
3. use the deprecated API and check the metro console

NOK: the ignored logs still appear in the console (this is a change in behavior from 0.65, where the logs were ignored in the metro console as well)

**Comment by arneson** [comment]
@Yonom Did you get anywhere with this? Experiencing the same thing over here.

**Comment by OneHatRepo** [comment]
same issue

**Comment by Yonom** [comment]
Problem is resolved for us in RN 0.66.4
