### ISSUE TITLE
No statusText returned on fetch/axios/XMLHTTPRequest (iOS)

### ISSUE THREAD

**Issue by harmenx** [facebook/react-native#32513]
### Description

After creating a new project, when doing any type of request that uses XMLHTTPRequest, statusText will come back as undefined. Strangely when making a request through React Native Debugger with "Enable Network inspect" enabled - the status text will be returned which indicates a possible issue in the networking layer. 

It seems this issue has been around for awhile as incidated here - https://github.com/facebook/react-native/issues/4184

### Version

0.63.2

### Output of `react-native info`

System:

    OS: macOS 11.2.3

    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz

    Memory: 774.47 MB / 32.00 GB

    Shell: 3.2.57 - /bin/bash

  Binaries:

    Node: 14.18.1 - /usr/local/bin/node

    Yarn: 1.22.10 - /usr/local/bin/yarn

    npm: 6.14.15 - /usr/local/bin/npm

    Watchman: Not Found

  Managers:

    CocoaPods: Not Found

  SDKs:

    iOS SDK:

      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2

    Android SDK: Not Found

  IDEs:

    Android Studio: Not Found

    Xcode: 12.4/12D4e - /usr/bin/xcodebuild

  Languages:

    Java: 16.0.1 - /usr/bin/javac

    Python: 2.7.16 - /usr/bin/python

  npmPackages:

    @react-native-community/cli: Not Found

    react: 16.13.1 => 16.13.1

    react-native: https://github.com/expo/react-native/archive/sdk-40.0.0.tar.gz => 0.63.2

    react-native-macos: Not Found

  npmGlobalPackages:

    *react-native*: Not Found

### Steps to reproduce

Create a new react-native project
implement a request that uses fetch to any API that returns statusText

**Comment by fonov** [comment]
some issue

**Comment by Luftzig** [comment]
Same, but happening on android.
