### ISSUE TITLE
Failed to load flowtype plugin

### ISSUE THREAD

**Issue by Romick2005** [facebook/react-native#32528]
### Description

After updating eslint from ver 7.32.0 to 8.1.0. I got this error:
`Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Failed to load plugin 'flowtype' declared in '--config » @react-native-community/eslint-config#overrides[0]': Package subpath './lib/rules/no-unused-expressions' is not defined by "exports" in /app/node_modules/eslint/package.json`

### Version

0.66.1

### Output of `react-native info`

System:
    OS: macOS 12.0.1
    CPU: (8) arm64 Apple M1
    Memory: 138.23 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.6.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 7.24.0 - /usr/local/bin/npm
    Watchman: 2021.09.27.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 31.0.0
      System Images: android-31 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7678000
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.2 => 17.0.2 
    react-native: ^0.66.1 => 0.66.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Just install latest eslint

**Comment by realkimmy** [comment]
Same issue.

**Comment by daniel-sullivan** [comment]
For anyone else with the same issue who is also completely new to React Native, changing "eslint": "8.2.0" as generated by the creation script to "eslint": "7.32.0" and then running "yarn install" seems to fix this issue.

**Comment by Romick2005** [comment]
The problem here that 
@react-native-community/eslint-config uses old version of
```
    "@typescript-eslint/eslint-plugin": "^4.22.1",
    "@typescript-eslint/parser": "^4.22.1",
```
but it should be updated to the latest 5.3.0

**Comment by Bardiamist** [comment]
Still actual in react-native 0.67.0

**Comment by mchasaegh** [comment]
> The problem here that @react-native-community/eslint-config uses old version of
> 
> ```
>     "@typescript-eslint/eslint-plugin": "^4.22.1",
>     "@typescript-eslint/parser": "^4.22.1",
> ```
> 
> but it should be updated to the latest 5.3.0

Right. Found issue opened here #33169

**Comment by Pat-Gekoski** [comment]
> For anyone else with the same issue who is also completely new to React Native, changing "eslint": "8.2.0" as generated by the creation script to "eslint": "7.32.0" and then running "yarn install" seems to fix this issue.

Thanks....this worked for me too

**Comment by idc77** [comment]
package.json
```
{
  "name": "blogs",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-keycloak/native": "^0.6.0",
    "react": "17.0.2",
    "react-native": "0.68.0",
    "react-native-inappbrowser-reborn": "^3.6.3"
  },
  "devDependencies": {
    "@babel/core": "^7.17.8",
    "@babel/runtime": "^7.17.8",
    "@react-native-community/eslint-config": "^3.0.1",
    "babel-jest": "^27.5.1",
    "eslint": "^8.12.0",
    "jest": "^27.5.1",
    "metro-react-native-babel-preset": "^0.70.0",
    "react-test-renderer": "17.0.2"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Failed to load plugin 'flowtype' declared in '.eslintrc.js » @react-native-community/eslint-config#overrides[0]': Package subpath './lib/rules/no-unused-expressions' is not defined by "exports" in /home/darko/WebstormProjects/react-native/blogs/node_modules/eslint/package.json

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Failed to load plugin 'flowtype' declared in '.eslintrc.js » @react-native-community/eslint-config#overrides[0]': Package subpath './lib/rules/no-unused-expressions' is not defined by "exports" in /home/darko/WebstormProjects/react-native/blogs/node_modules/eslint/package.json
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:453:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:731:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/darko/WebstormProjects/react-native/blogs/node_modules/eslint-plugin-flowtype/dist/rules/noUnusedExpressions.js:7:28)
Process finished with exit code -1
```

**Comment by Gujejiani** [comment]
wi

> For anyone else with the same issue who is also completely new to React Native, changing "eslint": "8.2.0" as generated by the creation script to "eslint": "7.32.0" and then running "yarn install" seems to fix this issue.

thanks man

**Comment by maximfreerider** [comment]
> > For anyone else with the same issue who is also completely new to React Native, changing "eslint": "8.2.0" as generated by the creation script to "eslint": "7.32.0" and then running "yarn install" seems to fix this issue.
> 
> Thanks....this worked for me too

thx a lot

**Comment by benomatis** [comment]
Upgrading `@react-native-community/eslint-config` to `^3.2.0` with eslint 8 should clear this error (`3.0.0` did not).

**Comment by Bardiamist** [comment]
My temp workaround:
1. Change `@react-native-community/eslint-config` to `2.0.0`
2. `yarn`
3. Change `@react-native-community/eslint-config` back to latest version
