### ISSUE TITLE
xcode13 ios15 freezing on the splash screen when running on the real phone

### ISSUE THREAD

**Issue by crazySadSoul** [facebook/react-native#32537]
### Description

ios14.x is working.
ios15 & xcode13 ,build success, but its freezing on the splash screen , its not console any error log.

please help, my friend!!!!!!!

### Version

0.60.4

### Output of `react-native info`

there are no error to console

### Steps to reproduce

xcode13 -> build on the real phone -> build success -> freezing on the splash screen

**Comment by 2sem** [comment]
Check if your iPhone use same WiFi to your Mac's.
Or.. just wait, sometimes it takes long time

**Comment by crazySadSoul** [comment]
> Check if your iPhone use same WiFi to your Mac's. Or.. just wait, sometimes it takes long time

it seems like a bug, i was wait it beafore.

**Comment by crazySadSoul** [comment]
![1636297293793](https://user-images.githubusercontent.com/26052793/140650687-c8109ee5-4dba-4ff9-b5ee-c17c9e19cc83.jpg)
