### ISSUE TITLE
IOS - Typedef redefinition with different types ('uint8_t' (aka 'unsigned char') vs 'enum clockid_t')

### ISSUE THREAD

**Issue by ayanmurad987** [facebook/react-native#32539]
### Description

**Error**
<img width="781" alt="Screenshot 2021-11-04 at 3 32 23 PM" src="https://user-images.githubusercontent.com/41545001/140298931-348661dc-abcc-4d76-93b8-6248416286f6.png">

**Podfile**
<img width="676" alt="Screenshot 2021-11-04 at 3 33 40 PM" src="https://user-images.githubusercontent.com/41545001/140299099-a109b91b-99d8-4a65-a38b-44eff869c7f8.png">

### Version

0.66.1

### Output of `react-native info`

System:
    OS: macOS 11.6
    CPU: (8) arm64 Apple M1
    Memory: 145.58 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.0.1 - /opt/homebrew/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.1.0 - /opt/homebrew/bin/npm
    Watchman: 2021.10.18.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7678000
    Xcode: 13.0/13A233 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.1 => 0.66.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

npx react-native init AwesomeProject
cd ios
pod install
npx react-native run-ios

**Comment by 2sem** [comment]
you should read this https://stackoverflow.com/questions/63376471/react-native-build-error-on-ios-typedef-redefinition-with-different-types-ui

**Comment by ayanmurad987** [comment]
**Fixed**
<img width="869" alt="Screenshot 2021-11-04 at 4 14 46 PM" src="https://user-images.githubusercontent.com/41545001/140304336-5c5de0e3-9a2f-4aac-82eb-d08aad83374f.png">
