### ISSUE TITLE
Android Fragment: not being displayed

### ISSUE THREAD

**Issue by wilsolutions** [facebook/react-native#32532]
### Description

I've create a simple module to experiment using an Android Fragment in React Native, everything is fine, I can see the Fragment in the "Layout Inspector" but it does not display the data and it appear in the very back of the Views hierarchy.

I have added to this repo for better visualization:
https://github.com/wilsolutions/react-native-experiments 

I have also added to StackOverflow:
https://stackoverflow.com/questions/69771856/android-fragment-not-displayed-in-react-native-app

Screenshot of the Views, also available in the link above:
https://i.stack.imgur.com/XEbVb.png

### Version

0.66.0

### Output of `react-native info`

**Please note that this an example project create with `npx create-react-native-library` but I have created a project with RN 0.66 as well.**

System:
    OS: macOS 11.5.2
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 116.01 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.7.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: Not Found
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /Users/wils/.rvm/rubies/ruby-2.6.6/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 23, 28, 29, 30
      Build Tools: 23.0.1, 24.0.0, 26.0.1, 26.0.2, 27.0.1, 27.0.3, 28.0.0, 28.0.1, 28.0.3, 29.0.2, 29.0.3, 30.0.1, 30.0.2
      System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7784292
    Xcode: 13.0/13A233 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_181 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Please checkout the example:
https://github.com/wilsolutions/react-native-experiments 
Then run the `yarn boostrap` followed by `yarn example android`

When the App launches it should display the Android Fragment but it is not.

### Snack, code example, screenshot, or link to a repository

Repo: 
https://github.com/wilsolutions/react-native-experiments 

Screenshot and more info: 
https://stackoverflow.com/questions/69771856/android-fragment-not-displayed-in-react-native-app

**Comment by wilsolutions** [comment]
Pls, any thoughts?

**Comment by wilsolutions** [comment]
Fixed with a doc update.

**Comment by arjun1194** [comment]
can you please at-least post the updated doc link ?? or a PR to the changes, im really confused what has changed please!!

**Comment by wilsolutions** [comment]
> can you please at-least post the updated doc link ?? or a PR to the changes, im really confused what has changed please!!

Hey, sure, I was not 100% sure if I could link the docs here or not, there we go:
https://github.com/facebook/react-native-website/issues/2838

**Comment by jamninetyfive** [comment]
same here @wilsolutions For me, it is to embed the react native page into Android. Now get a white screen, but views hierarchy is fine... any idea for me
