### ISSUE TITLE
Multiple nested RTCViews in demo app

### ISSUE THREAD

**Issue by QuantumInformation** [facebook/react-native#3254]
I just created an new app with the cli but when I inspect the view I see multiple RTCViews. Is this normal behaviour?

![image](https://cloud.githubusercontent.com/assets/216566/10319659/43248d64-6c67-11e5-91b5-c158ae3e6fb3.png)

**Comment by ide** [comment]
Yes, each View produces an RCTView.

**Comment by QuantumInformation** [comment]
But in the demo app that was created there is only 1 view with several text components. Perhaps it is now compiling properly and the actual app running is a different one that was precompiled.

**Comment by ide** [comment]
The two extra views are created here: https://github.com/facebook/react-native/blob/master/Libraries/ReactIOS/renderApplication.ios.js#L52. I just verified with a new sample app and see three views as expected.
