### ISSUE TITLE
Can not use Hermes Debugger when enabled hermes Android

### ISSUE THREAD

**Issue by kyunkakata** [facebook/react-native#32553]
### Description

I cannot use Hermes Debugger on the Flipper and Chrome Inspect doesn't show React Native Hermes app.
The Metro is running in port 9039 and localhost:9039/json returns an empty array.
 I have already followed Troubleshooting Issues I don't see the 'React Native' device:
 
`yarn why @react-native-community/cli`
```
=> Found "@react-native-community/cli@6.1.0"
info Reasons this module exists
   - "react-native" depends on it
   - Hoisted from "react-native#@react-native-community#cli"
info Disk size without dependencies: "1016KB"
info Disk size with unique dependencies: "10.3MB"
info Disk size with transitive dependencies: "62.35MB"
info Number of shared dependencies: 167
```
But it doesn't resolve the problem.
I was enableHermes in app/build.gradle
And sure that Hermes is enabled correctly: https://imgur.com/g7Rk9HF

Additional info:
My Flipper when it was connected with my basic test app was shown like this.
https://imgur.com/KIQM8GG
It is a basic app created by `react-native init TestProject`

### Version

0.66.2

### Output of `react-native info`

System:
    OS: macOS 12.0.1
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 386.70 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.9.1 - /usr/local/bin/node
    Yarn: 1.10.1 - ~/.yarn/bin/yarn
    npm: 7.21.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK: Not Found
    Android SDK:
      API Levels: 23, 25, 26, 28, 29, 30
      Build Tools: 28.0.1, 28.0.2, 28.0.3, 29.0.2, 29.0.3, 30.0.1, 30.0.2
      System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7678000
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_281 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.2 => 0.66.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

- Create a basic app by `react-native init TestProject`
- enabled Hermes for Android.
- run react-native android and react-native start --port=9039
- Change port to port 9039 in the DevMenu

**Comment by kyunkakata** [comment]
Can someone suffers the same problem and get the solution? We update the newest react-native version and use JSI in the application so that Remote Debugger is not available anymore. Without Hermes Debugger, debugging is like hell with default Flipper Native Logs. :(

**Comment by quocvu12345** [comment]
+1

**Comment by kyunkakata** [comment]
Does no one suffer from this problem? Only us?

**Comment by danlugo92** [comment]
+1

**Comment by aymkin** [comment]
In my case I wanted to use Reanimated 2, that is why the Hermes was enabled. That was not required, but I enabled it for iOS as well.

As a result:
- can run the iOS app and debug it with a remote debugger (Flipper)
- can't run the Android app with the debugger, only without

Launching Android app without debugger results  call`const isHermes = () => !!global.HermesInternal;` to be `true`. However, enabling debug will result `isHermes()` to `false`

## `react-native info`

```System:
    OS: macOS 11.6.5
    CPU: (8) x64 Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
    Memory: 82.78 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.18 - ~/.yarn/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
    Watchman: 2022.03.21.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/lib/ruby/gems/3.1.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 23, 28, 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 31.0.0, 33.0.0
      System Images: android-28 | Intel x86 Atom_64, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-31 | Google APIs Intel x86 Atom_64, android-Tiramisu | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: Bumblebee 2021.1.1 Patch 2 Bumblebee 2021.1.1 Patch 2
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.14.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.65.2 => 0.65.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found```

**Comment by kkureli** [comment]
> In my case I wanted to use Reanimated 2, that is why the Hermes was enabled. That was not required, but I enabled it for iOS as well.
> 
> As a result:
> 
> * can run the iOS app and debug it with a remote debugger (Flipper)
> * can't run the Android app with the debugger, only without
> 
> Launching Android app without debugger results call`const isHermes = () => !!global.HermesInternal;` to be `true`. However, enabling debug will result `isHermes()` to `false`
> 
> ## `react-native info`
> ```shell
> System:
>     OS: macOS 11.6.5
>     CPU: (8) x64 Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
>     Memory: 82.78 MB / 16.00 GB
>     Shell: 5.8 - /bin/zsh
>   Binaries:
>     Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
>     Yarn: 1.22.18 - ~/.yarn/bin/yarn
>     npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
>     Watchman: 2022.03.21.00 - /usr/local/bin/watchman
>   Managers:
>     CocoaPods: 1.11.3 - /usr/local/lib/ruby/gems/3.1.0/bin/pod
>   SDKs:
>     iOS SDK:
>       Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
>     Android SDK:
>       API Levels: 23, 28, 29, 30, 31
>       Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 31.0.0, 33.0.0
>       System Images: android-28 | Intel x86 Atom_64, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-31 | Google APIs Intel x86 Atom_64, android-Tiramisu | Google APIs Intel x86 Atom_64
>       Android NDK: Not Found
>   IDEs:
>     Android Studio: Bumblebee 2021.1.1 Patch 2 Bumblebee 2021.1.1 Patch 2
>     Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
>   Languages:
>     Java: 11.0.14.1 - /usr/bin/javac
>   npmPackages:
>     @react-native-community/cli: Not Found
>     react: 17.0.2 => 17.0.2 
>     react-native: 0.65.2 => 0.65.2 
>     react-native-macos: Not Found
>   npmGlobalPackages:
>     *react-native*: Not Found```
> ```

Hi, did you find solution for "can't run the Android app with the debugger, only without"?
