### ISSUE TITLE
TextInput wrapped in Text is not being displayed.

### ISSUE THREAD

**Issue by VitaliyGaliy** [facebook/react-native#32552]
### Description

TextInput wrapped in Text is not being displayed.

    <Text>111<TextInput value='222'/>333</Text>

### Version

0.64.2

### Output of `react-native info`

"dependencies": {
    "@expo/vector-icons": "^12.0.0",
    "@react-navigation/bottom-tabs": "^6.0.5",
    "@react-navigation/native": "^6.0.2",
    "@react-navigation/native-stack": "^6.1.0",
    "expo": "~43.0.0",
    "expo-asset": "~8.4.3",
    "expo-constants": "~12.1.2",
    "expo-font": "~10.0.3",
    "expo-linking": "~2.4.2",
    "expo-splash-screen": "~0.13.3",
    "expo-status-bar": "~1.1.0",
    "expo-web-browser": "~10.0.3",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-native": "0.64.2",
    "react-native-safe-area-context": "3.3.2",
    "react-native-screens": "~3.8.0",
    "react-native-web": "0.17.1"
  },

### Snack, code example, screenshot, or link to a repository

<img width="1077" alt="Снимок экрана 2021-11-06 в 19 30 23" src="https://user-images.githubusercontent.com/24389083/140618550-197d8305-f12c-4684-9ffa-640c1518c013.png">

**Comment by dotfelixb** [comment]
That is the expected behaviour for Text component you might want to considere
`<View>
    <Text>111</Text>
    <TextInput value="222"/>
    <Text>333</Text>
</View>`
