### ISSUE TITLE
Callback not firing in Android Native Module

### ISSUE THREAD

**Issue by madwed** [facebook/react-native#3255]
I've written a native module with the method 
```
@ReactMethod
  public void getModel(Callback cb) {
    try{
      String model = Build.MODEL;
      cb.invoke(model);
    }catch (Exception e){
      cb.invoke("err");
    }
  }
```

But when I invoke in JS with 
```
MyNativeModule.getModel(function (data) {
  console.log(data, "data");
});
```

I get nothing back.  No errors, no logs, nothing.
I've tried logging from Java with System.out, but that doesn't log anything.

Any ideas?
Thanks in advance!

**Comment by satya164** [comment]
Any errors you see in debugger?

**Comment by madwed** [comment]
No errors

**Comment by brentvatne** [comment]
@madwed - are you sure that `Build.MODEL` is evaluating to anything? If you add a log message inside of `getModel` does it show it as being called? What if you just change it to `cb.invoke("hi there!")`?

**Comment by madwed** [comment]
@brentvatne Unfortunately neither adding a log message in the callback like ```console.log("hello")``` nor changing it to ```cb.invoke("hi there!")``` works. Nothing is called. :/

**Comment by kmagiera** [comment]
@madwed sorry for not getting back to you earlier. Glad to hear the issue has been resolved.
