### ISSUE TITLE
App wont install on IOS

### ISSUE THREAD

**Issue by ZanaNabaz** [facebook/react-native#32569]
### Description

Im getting a bug in react native when I try to run on a IOS device. The problem appears when I use the command : npx react-native run-ios --device using Visual Studio Code.

The error I am getting is :

success: Successfully built the app

error: "Couldn't find "PLATFORM_NAME" variable in xcodebuild output. Please report this"

It works when I build from xcode, but not from Visual Studio Code.

I have googled and tried to find a solution, but I can't find anything.

the workaround i've found so far is:
1. run from xcode
2. run the command "npx react-native run-ios --device" after xcode build

### Version

0.66.1

### Output of `react-native info`

System:
    OS: macOS 11.3.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 316.93 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.2.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 7.13.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 29, 30
      Build Tools: 29.0.2, 30.0.3
      System Images: android-29 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7486908
    Xcode: 13.0/13A233 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: ^0.66.1 => 0.66.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. Open project in Visual Stuido Code
2. Run the command : "npx react-native run-ios --device"

**Comment by GabrielShaad** [comment]
I'm going through the same issue, running on a MacBook Air M1.

**Comment by DBalls93** [comment]
I am getting the same issue, running on a Macbook Pro.

**Comment by absingh927** [comment]
Also ran into the same issue with MacBook Pro M1, tried the workaround (run in Xcode and then `npx react-native run-ios`) and it worked fine after that.

**Comment by DBalls93** [comment]
I did what @absingh927 did and it worked for me. Every once in a while it will go out of action and I will need to do the same thing. Not sure what is causing it to happen though.

**Comment by ZanaNabaz** [comment]
> I did what @absingh927 did and it worked for me. Every once in a while it will go out of action and I will need to do the same thing. Not sure what is causing it to happen though.

Exactly the same thing happens to me. I want to find a solution. I found out that I have to reconfigure my IP and port every time I'm on a new network.

**Comment by Slexom** [comment]
RN 0.66.4 on MacBook Pro M1, same issue.
```
** BUILD SUCCEEDED **


success Successfully built the app
error Couldn't find "PLATFORM_NAME" variable in xcodebuild output. Please report this issue and run your project with Xcode instead.
```
Also, the proposed workaround not work.

**Comment by svobik7** [comment]
This approach works for me https://stackoverflow.com/a/71045413/4610318

**Comment by riverbookstudio** [comment]
[svobik7](https://github.com/svobik7) Yes, this worked for me as well!

**Comment by ZanaNabaz** [comment]
That's basically the same as my workaround, however this  is not a solution. At least not for me, it's a temporary fix and the issue will come back.

**Comment by jasonrwagner** [comment]
Here's another workaround that works for our team.  If you have an Intel MBP uncheck the For install builds only.  M1 check the checkbox.

![Screen Shot 2022-06-09 at 9 43 45 AM](https://user-images.githubusercontent.com/2029498/172862283-6649bf6b-827f-4b4b-93f2-7682a89b5958.png)

**Comment by ZanaNabaz** [comment]
This issue is still persistent, I have checked "For install builds only". Does anyone have a fix?

**Comment by Ambryhill** [comment]
I have been facing the same issue for the last 6 months. I have a Macbook Pro with Apple M1 Pro chip. 
Tried many solutions but failed to run the iOS app via Visual studio code. 
Can run the app via SUDO command but unable to find it on simulator. 
Please help me. This is a serious issue.
