### ISSUE TITLE
Android - Crash obtaining RCTDeviceEventEmitter from ReactContext

### ISSUE THREAD

**Issue by marcshilling** [facebook/react-native#3256]
I'm following the docs (https://facebook.github.io/react-native/docs/native-modules-android.html#sending-events-to-javascript) to send native events to JavaScript.

I've implemented a native module. I save the `ReactApplicationContext` passed to the constructor as a local variable `private ReactApplicationContext mContext;`

Then, I try to access the `RCTDeviceEventEmitter` like so:
```java
DeviceEventManagerModule.RCTDeviceEventEmitter emitter =  mContext.getJSModule(DeviceEventManagerModule.RCTDeviceEventEmitter.class);
```

This line crashes with the error: `Method threw 'java.lang.AssertionError' exception. Cannot evaluate $Proxy4.toString()`

**Comment by marsprince** [comment]
same error! How to solve it?

**Comment by marsprince** [comment]
Oh,I solved it by a function sendEvent like docs show,but why?

**Comment by marcshilling** [comment]
@marsprince can you explain further how you did this?

**Comment by marsprince** [comment]
@marcshilling I just copied codes in docs and it worked it.I am confused too.

**Comment by kocyigityunus** [comment]
i'm having the same issue. with 0.19 

Method threw 'java.lang.AssertionError' exception. Cannot evaluate $Proxy3.toString()

**Comment by soxunyi** [comment]
have same issue with 0.20 
Method threw 'java.lang.AssertionError' exception. Cannot evaluate $Proxy9.toString()

**Comment by VonD** [comment]
I think this is because the context received in your module's constructor is of type `ReactApplicationContext `. If you cast it to `ReactContext`, it should be ok. The method does so, which is why it works.

**Comment by VonD** [comment]
@facebook-github-bot answered

**Comment by grabbou** [comment]
I don't think it's really a solution - I am calling `getJSModule` on a applicationContext and there are no crashes. In fact, it's a subclass, so casting should have no effect.

Can anyone provide a better stack trace and their full example of passing context, assigning and sending an event?

**Comment by satya164** [comment]
Are you using it inside the constructor? Can you post a full example?

**Comment by satya164** [comment]
Closing this since there are no details available regarding the issue, and it's not actionable. Please try with latest version of React Native and see if this still happens. Let's reopen if it's still an issue and we have more details.
