### ISSUE TITLE
react native upgrade 0.64.2 to 0.66.1

### ISSUE THREAD

**Issue by malikhautumn** [facebook/react-native#32561]
### New Version

0.66.1

### Old Version

0.64.2

### Build Target(s)

buildToolsVersion = "30.0.2" compileSdkVersion = 30  targetSdkVersion = 30

### Output of `react-native info`

> Task :app:checkDevDebugAarMetadata FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.9/userguide/command_line_interface.html#sec:command_line_warnings
187 actionable tasks: 180 executed, 7 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDevDebugAarMetadata'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
   > The minCompileSdk (31) specified in a
     dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
     is greater than this module's compileSdkVersion (android-30).
     Dependency: androidx.core:core:1.7.0.
     AAR metadata file: /Users/malikhezretov/.gradle/caches/transforms-3/8dffba8f50f81940e51ed01576f31fbd/transformed/core-1.7.0/META-INF/com/android/build/gradle/aar-metadata.properties.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 31s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDevDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDevDebugAarMetadata'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
   > The minCompileSdk (31) specified in a
     dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
     is greater than this module's compileSdkVersion (android-30).
     Dependency: androidx.core:core:1.7.0.
     AAR metadata file: /Users/malikhezretov/.gradle/caches/transforms-3/8dffba8f50f81940e51ed01576f31fbd/transformed/core-1.7.0/META-INF/com/android/build/gradle/aar-metadata.properties.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 31s

    at makeError (/Users/malikhezretov/autumn-frontend-mobile/node_modules/execa/index.js:174:9)
    at /Users/malikhezretov/autumn-frontend-mobile/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (/Users/malikhezretov/autumn-frontend-mobile/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:106:5)
    at async Command.handleAction (/Users/malikhezretov/autumn-frontend-mobile/node_modules/react-native/node_modules/@react-native-community/cli/build/index.js:192:9)
info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### Issue and Reproduction Steps

Upgrade react native version manually using React Native Upgrade Helper from 0.64.2 to 0.66.1.
Updated files

<img width="1636" alt="Screenshot 2021-11-09 at 11 48 18 AM" src="https://user-images.githubusercontent.com/65154231/140858656-f9ba7735-a4e6-47fe-adc9-b97014b538e1.png">
<img width="1649" alt="Screenshot 2021-11-09 at 11 48 32 AM" src="https://user-images.githubusercontent.com/65154231/140858674-45379b3d-93a6-4ac0-9183-cc63d1044e1a.png">
<img width="1672" alt="Screenshot 2021-11-09 at 11 49 12 AM" src="https://user-images.githubusercontent.com/65154231/140858677-56fb57e3-5ce6-4ba6-8995-36492471216a.png">
<img width="1632" alt="Screenshot 2021-11-09 at 11 49 21 AM" src="https://user-images.githubusercontent.com/65154231/140858680-b0999a11-b142-45bf-8b6e-cd457df4d962.png">

1. yarn
2. yarn android

**Comment by malikhautumn** [comment]
No luck so far @kabus202

**Comment by kabus202** [comment]
@malikhautumn  this worked for me:

```
rm -r $HOME/.gradle/caches/
cd android
./gradlew cleanBuildCache
./gradlew clean; cd .. 
rm -rf node_modules; yarn;
npx react-native run-android 
```

**Comment by malikhautumn** [comment]
I still get this error @kabus202, the minCompileSdk=31 still in this file /Users/malikhezretov/.gradle/caches/transforms-3/8dffba8f50f81940e51ed01576f31fbd/transformed/core-1.7.0/META-INF/com/android/build/gradle/aar-metadata.properties.

**Comment by rustysnail26** [comment]
To get a successful build for compileSdkVersion 30, just change the minCompileSdk to 30 (set **minCompileSdk=30**) on the aar-metadata.properties.

**Comment by zenkriztao** [comment]
- [ ] cd android
- [ ] ./gradlew cleanBuildCache
- [ ] ./gradlew clean
- [ ] cd .. 
- [ ] rm -rf node_modules
- [ ] yarn install
- [ ] yarn start

**Comment by zenkriztao** [comment]
1. cd android
2. ./gradlew cleanBuildCache
3. ./gradlew clean; cd .. 
4. rm -rf node_modules; yarn;

**Comment by zenkriztao** [comment]
> 1. cd android
> 2. ./gradlew cleanBuildCache
> 3. ./gradlew clean; cd ..
> 4. rm -rf node_modules; yarn;

**Comment by zenkriztao** [comment]
```
cd android
./gradlew cleanBuildCache
./gradlew clean
cd .. 
rm -rf node_modules
yarn install
yarn react-native run-android
```

**Comment by DanielMSnack** [comment]
Getting the same here after upgrading from v0.60 to v0.64

**Comment by medonagy45** [comment]
same issue here

**Comment by tututututututu** [comment]
same issue here

**Comment by 0xsail** [comment]
I didn't upgrade but I have this problem too
