### ISSUE TITLE
library not found for -lFolly

### ISSUE THREAD

**Issue by PhilippLeh21** [facebook/react-native#32572]
### New Version

0.66.3

### Old Version

0.61.1

### Build Target(s)

iPhone 13

### Output of `react-native info`

System:
    OS: macOS 11.5.2
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Memory: 73.12 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 8.1.0 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 29
      Build Tools: 28.0.3, 29.0.2, 31.0.0
      System Images: android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7784292
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: ^6.1.0 => 6.1.0 
    react: 17.0.2 => 17.0.2 
    react-native: ^0.66.3 => 0.66.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Issue and Reproduction Steps

When running react-native run-ios in cli an error occurs when building the project. The -lFolly library could not be found and linked. See screenshot:

**Comment by PhilippLeh21** [comment]
This issue was not a bug in React Native. In Xcode, under App > Targets > Build Phases > Link Binary With Libraries, there were links to the Folly library, which no longer existed. By removing this and a few other libraries and updating dependent packages in the package.json file, we got the app working again.

**Comment by Yandamuri** [comment]
@PhilippLeh21 I am facing same error. I tried apply your solution. But I didn't find any library with the name `Folly` in `Link Binary With Libraries`.

Can you please let me know what should nee done to get rid of this error.

**Comment by Yandamuri** [comment]
@PhilippLeh21 Can you please respond on this, If you have time?

> @PhilippLeh21 I am facing same error. I tried apply your solution. But I didn't find any library with the name `Folly` in `Link Binary With Libraries`.
> 
> Can you please let me know what should nee done to get rid of this error?

**Comment by PhilippLeh21** [comment]
Sorry, I somehow missed your message. As explained above I only deleted the library containing 'folly'.

**Comment by Yandamuri** [comment]
I found solution [here](https://stackoverflow.com/questions/69665207/library-not-found-for-lfolly/72829394#72829394)
