### ISSUE TITLE
React-Native 0.59 targetSDK 30 issue

### ISSUE THREAD

**Issue by teriologia** [facebook/react-native#32573]
### Description

hello everyone
I've some problem my company's app not working on android 11

I just changed target SDK from 29 to 30, because google not allow to publish target SDK version under 30
I tested a lot of emulator android 6 to 11 everything works fine but today comes some issue like 'app not working on android 11'
I realize this happen only real devices and target sdk causes this issue when I rollback to targetSDK = 29 everythings works fine again but I don't publish my app right now 

I already try this solutions: 
-try to upgrade RN-60+ but A a lot of issue comes up with this especially realm I need to change whole app
-Added to ./app/build.gradle 
  implementation("com.squareup.okhttp3:okhttp:4.9.1")
  implementation("com.squareup.okhttp3:okhttp-urlconnection:4.9.1")

    "react": "16.8.6",
    "react-native": "0.59.9",

    buildToolsVersion = "29.0.2"
    minSdkVersion = 18
    compileSdkVersion = 30
    targetSdkVersion = 30
    supportLibVersion = "29.0.0" // already try to change 30.0.0
    googlePlayServicesLocationVersions = "16.0.0"
    multiDexEnabled = true

### Version

0.59.0

### Output of `react-native info`

  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (12) x64 Intel(R) Core(TM) i5-10500 CPU @ 3.10GHz
      Memory: 3.10 GB / 15.83 GB
    Binaries:
      Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7199119

### Steps to reproduce

target SDK changed from 29 to 30
assembleRelease and get APK
install on android 11 real device

**Comment by tdimitrova** [comment]
Hi @teriologia, I have the same problem and the application does not want to install on android 11 after changing targetSDK to 30. The problem was that the apk was not signed as android expected. In device log, I had this line: `No signature found in package of version 2 or newer for package`. 
I had to sign the application with apk signer above v2.

**Comment by teriologia** [comment]
> Hi @teriologia, I have the same problem and the application does not want to install on android 11 after changing targetSDK to 30. The problem was that the apk was not signed as android expected. In device log, I had this line: `No signature found in package of version 2 or newer for package`. I had to sign the application with apk signer above v2.

thanks for reply I'll try this
