### ISSUE TITLE
iOS app stuck on "Loading from Metro..." in debug mode

### ISSUE THREAD

**Issue by jlipps** [facebook/react-native#32583]
### Description

I recently upgraded from RN 0.62 to RN 0.66.3. After going through all the update diffs and applying the necessary changes, my RN app builds and launches successfully on both iOS and Android. However, on an iOS simulator, while on the launch screen, the app's home view never loads and instead there is a debug notice at the top stuck at "Loading from Metro...". (The app works fully as expected on Android).

The Metro bundler is running, and launching the iOS app causes the bundler to build the bundle to 100%. No further logs are shown from the bundler. If I hit "r" in the Metro console it will show this message:

```
warn No apps connected. Sending "reload" to all React Native apps failed. Make sure your app is running in the simulator or on a phone connected via USB.
info Reloading app...
```

However it seems the app was connected, since it did trigger the Metro build...?

I don't have a real iOS device handy so I'm not sure if the issue is isolated to a simulator.

### Version

0.66.3

### Output of `react-native info`

System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
    Memory: 930.38 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 17.0.1 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.0 - /usr/local/bin/npm
    Watchman: 2021.10.18.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/lib/ruby/gems/3.0.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 28, 30, 31
      Build Tools: 28.0.3, 30.0.2, 31.0.0, 32.0.0
      System Images: android-30 | Google Play Intel x86 Atom, android-31 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7678000
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_144 - /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.66.3 => 0.66.3
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

After cloning the linked repo:

```
yarn install
cd ios
pod install
cd ..
yarn ios
```

### Snack, code example, screenshot, or link to a repository

https://github.com/appium-pro/the-app

**Comment by jlipps** [comment]
I also checked the simulator system log to see if there was anything interesting there, but I couldn't see anything related to the issue at hand.

**Comment by luism3861** [comment]
> there

That's a huge upgraded and you have a recent node versión try to use another node js version

**Comment by jlipps** [comment]
I discovered the problem. It didn't have to do with Node version. I am using ReactNativeNavigation, and apparently I needed to add this to my AppDelegate implementation:

```objc
- (NSArray<id<RCTBridgeModule>> *)extraModulesForBridge:(RCTBridge *)bridge {
  return [ReactNativeNavigation extraModulesForBridge:bridge];
}
```

**Comment by elsurudo** [comment]
This was also my issue, so thanks for the tip! Can I ask how you debugged this and found the solution? I wasn't able to see any logs or errors, so I don't know how I would have arrived at this... This might be useful because the metro packager often causes me grief
