### ISSUE TITLE
[Android]: Linking incompatible target in debug mode on Manjaro Linux

### ISSUE THREAD

**Issue by Nawbc** [facebook/react-native#32595]
### Description

The main error log

#### On Manjaro Linux 

![](https://user-images.githubusercontent.com/45007226/141926738-9ad040d6-8c4f-49bc-a196-5ab84439590c.png)

### Version

main branch

### Output of `react-native info`
   System:
    OS: Linux 5.15 Manjaro Linux
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
    Memory: 348.26 MB / 15.41 GB
    Container: Yes
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v14.16.1/bin/yarn
    npm: 6.14.12 - ~/.nvm/versions/node/v14.16.1/bin/npm
  Utilities:
    Make: 4.3 - /usr/bin/make
    GCC: 11.1.0 - /usr/bin/gcc
    Git: 2.34.0 - /usr/bin/git
    FFmpeg: 4.4.1 - /usr/bin/ffmpeg
  Servers:
    Apache: 2.4.51 - /usr/bin/apachectl
  IDEs:
    Android Studio: AI-203.7717.56.2031.7784292
    Nano: 5.9 - /usr/bin/nano
    VSCode: 1.62.3 - /usr/bin/code
    Vim: 8.2 - /usr/bin/vim
  Languages:
    Bash: 5.1.8 - /usr/bin/bash
    Java: 11.0.13 - /usr/bin/javac
    Perl: 5.34.0 - /usr/bin/perl
    Protoc: 3.17.3 - /usr/bin/protoc
    Python: 3.9.7 - /usr/bin/python
    Python3: 3.9.7 - /usr/bin/python3
  Databases:
    SQLite: 3.36.0 - /usr/bin/sqlite3
  Browsers:
    Firefox: 94.0.2

### Steps to reproduce

1. Run gradle task `externalNativeBuildDebug`

**Comment by cortinico** [comment]
I've just tested locally on a plain template and it works fine for me. I suspect there is something dirty in your build fonder (inside `node_modules/react-native/ReactAndroid/build/*`) that could be causing this.

Could you provide:
1. A reproducer on a empty template
2. A Gradle scan. You can get it by firing: `cd android && ./gradlew :ReactAndroid:externalNativeBuildDebug --scan` (it will take some time to run but you'll end up having a link that you can share about your build output).

**Comment by Nawbc** [comment]
@cortinico I tried again and failed with the same error. what os you are using, my system is windows 11, I guess is the reason for the system. 


on windows, part `so` has been generated.
![image](https://user-images.githubusercontent.com/45007226/141923972-4b34197e-e3a9-4400-92b6-11e4f17212ba.png)

then i tried on the Manjaro Linux but got another error
![image](https://user-images.githubusercontent.com/45007226/141926738-9ad040d6-8c4f-49bc-a196-5ab84439590c.png)

**Comment by Nawbc** [comment]
@cortinico Cloud you please push your test to a temp repo? 😀

**Comment by cortinico** [comment]
> @cortinico Cloud you please push your test to a temp repo? 😀

Yup here it is https://github.com/cortinico/RnReproducer32595
