### ISSUE TITLE
XCode 13 can not link/find third party .a when build with simulator

### ISSUE THREAD

**Issue by Symous** [facebook/react-native#32596]
### Description

I recently moved a old project from macbook pro 2017 to an Apple M1 chip Mac Mini XCode13. When I build my project with simulator it failed and error occurs:
`clang: error: no such file or directory: '/Users/symous/Library/Developer/Xcode/DerivedData/symousReact-hgljttfucnynuifixuyfjnjgdbct/Build/Products/Debug-iphonesimulator/libRNBackgroundTimer.a'
clang: error: no such file or directory: '/Users/symous/Library/Developer/Xcode/DerivedData/symousReact-hgljttfucnynuifixuyfjnjgdbct/Build/Products/Debug-iphonesimulator/libRCTImageMarker.a'
clang: error: no such file or directory: '/Users/symous/Library/Developer/Xcode/DerivedData/symousReact-hgljttfucnynuifixuyfjnjgdbct/Build/Products/Debug-iphonesimulator/libNfcManager.a'
clang: error: no such file or directory: '/Users/symous/Library/Developer/Xcode/DerivedData/symousReact-hgljttfucnynuifixuyfjnjgdbct/Build/Products/Debug-iphonesimulator/libBleManager.a'
clang: error: no such file or directory: '/Users/symous/Library/Developer/Xcode/DerivedData/symousReact-hgljttfucnynuifixuyfjnjgdbct/Build/Products/Debug-iphonesimulator/libReactNativeAudioToolkit.a'
clang: error: no such file or directory: '/Users/symous/Library/Developer/Xcode/DerivedData/symousReact-hgljttfucnynuifixuyfjnjgdbct/Build/Products/Debug-iphonesimulator/libART.a'
clang: error: no such file or directory: '/Users/symous/Library/Developer/Xcode/DerivedData/symousReact-hgljttfucnynuifixuyfjnjgdbct/Build/Products/Debug-iphonesimulator/libRCTAnimation.a'
clang: error: no such file or directory: '/Users/symous/Library/Developer/Xcode/DerivedData/symousReact-hgljttfucnynuifixuyfjnjgdbct/Build/Products/Debug-iphonesimulator/libRCTActionSheet.a'
clang: error: no such file or directory: '/Users/symous/Library/Developer/Xcode/DerivedData/symousReact-hgljttfucnynuifixuyfjnjgdbct/Build/Products/Debug-iphonesimulator/libRCTGeolocation.a'
clang: error: no such file or directory: '/Users/symous/Library/Developer/Xcode/DerivedData/symousReact-hgljttfucnynuifixuyfjnjgdbct/Build/Products/Debug-iphonesimulator/libRCTImage.a'
clang: error: no such file or directory: '/Users/symous/Library/Developer/Xcode/DerivedData/symousReact-hgljttfucnynuifixuyfjnjgdbct/Build/Products/Debug-iphonesimulator/libRCTLinking.a'
clang: error: no such file or directory: '/Users/symous/Library/Developer/Xcode/DerivedData/symousReact-hgljttfucnynuifixuyfjnjgdbct/Build/Products/Debug-iphonesimulator/libRCTNetwork.a'
clang: error: no such file or directory: '/Users/symous/Library/Developer/Xcode/DerivedData/symousReact-hgljttfucnynuifixuyfjnjgdbct/Build/Products/Debug-iphonesimulator/libRCTSettings.a'
clang: error: no such file or directory: '/Users/symous/Library/Developer/Xcode/DerivedData/symousReact-hgljttfucnynuifixuyfjnjgdbct/Build/Products/Debug-iphonesimulator/libRCTText.a'
clang: error: no such file or directory: '/Users/symous/Library/Developer/Xcode/DerivedData/symousReact-hgljttfucnynuifixuyfjnjgdbct/Build/Products/Debug-iphonesimulator/libRCTVibration.a'
clang: error: no such file or directory: '/Users/symous/Library/Developer/Xcode/DerivedData/symousReact-hgljttfucnynuifixuyfjnjgdbct/Build/Products/Debug-iphonesimulator/libRCTWebSocket.a'
Command Ld failed with a nonzero exit code`

it seems like that some of my third party .a lib can not be linked/found, but all is working fine when I build with physical device and archive.

I have searched lots of related issue and guess that's maybe an issue of architecture settings, I have configured:
![image](https://user-images.githubusercontent.com/13534034/141778550-93694540-b56f-4caf-9fbf-2a6cdd0b9985.png)

### Version

0.59.0

### Output of `react-native info`

  React Native Environment Info:
    System:
      OS: macOS 12.0.1
      CPU: (8) x64 Apple M1
      Memory: 21.61 MB / 16.00 GB
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.18.0 - /usr/local/bin/node
      npm: 6.14.15 - /usr/local/bin/npm
      Watchman: 2021.10.04.00 - /opt/homebrew/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
      Android SDK:
        API Levels: 25, 26, 27, 28, 29, 31
        Build Tools: 25.0.2, 28.0.3, 29.0.2, 29.0.3, 31.0.0
        System Images: android-25 | Google APIs ARM 64 v8a, android-29 | Google APIs ARM 64 v8a, android-31 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7678000
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.8.3 => 16.8.3 
      react-native: ^0.59.0 => 0.59.0 

### Steps to reproduce

just like below.

**Comment by Lacerda53** [comment]
Im have the same problem with xcode 13 in my mac pro m1

**Comment by skibaalex** [comment]
Same issue here.
@Lacerda53  @Symous did you guys found a solution?

**Comment by Lacerda53** [comment]
The temporary solution to the problem was to downgrade Xcode to version 12.5.1, forcing its execution.
the steps are:

- Download xcode 12.5.1

- Move xocde 12.5.1 to your macOS application folder

- Drag and drop xcode into the terminal and concatenate the commands:

/Contents/MacOS/Xcode

EX:

/Applications/Xcode-12.5.1.app/Contents/MacOS/Xcode

It will open Xcode 12.5.1 and you can run the project

**Comment by Symous** [comment]
@Lacerda53 That isn't a final solution since that impossible for us to keep XCode12.

**Comment by Symous** [comment]
@Lacerda53 @skibaalex Just have found that we need to do nothing except use rosetta to run Xcode.
1. view XCode in finder.
2. right click and get info.
3. check "open using rosetta"

restart XCode. :)

**Comment by Lacerda53** [comment]
> @ Lacerda53 Essa não é uma solução definitiva já que é impossível para nós manter o XCode12.

Good job, the solution I proposed was just a temporary solution in urgent cases, but your solution was final, thank you

**Comment by vrgimael** [comment]
Well, although it works, running Xcode on Rosetta doesn't seem like a "final" solution - anyone managed to get RN running on a simulator on M1?
