### ISSUE TITLE
[Android] VirtualizedList: Encountered an error while measuring a list's offset from its containing VirtualizedList.

### ISSUE THREAD

**Issue by qhoarau** [facebook/react-native#32590]
### Description

After upgrading from expo SDK 39 (react native 0.63.3) to expo SDK 43 (react native 0.64.3), my nested flatList is not showing.

I have a parent vertical flatlist with an horizontal tab view child (using react-native-tab-view), and each tab view has a vertical flatlist but they are not displayed and error "VirtualizedList: Encountered an error while measuring a list's offset from its containing VirtualizedList." is shown. Worked fine before upgrade

Before upgrade : react-native 0.63.3, react-native-tab-view : 2.15.3
After upgrade : react-native 0.64.3, react-native-tab-view : 3.1.1

### Version

0.64.3

### Output of `react-native info`

System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 6.69 GB / 15.95 GB
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 26, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.3, 32.0.0
      System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7784292
    Visual Studio: Not Found
  Languages:
    Java: 1.8.0_312 - C:\Program Files\OpenJDK\openjdk-8u312-b07\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.3 => 0.64.3
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. Create parent vertical FlatList
2. Add horizontal ViewPagerAndroid (for tabs) using react-native-tab-view
3. Each tab has a vertical FlatList

**Comment by GFean** [comment]
any updates on this ? Having the same issue..

**Comment by NoahGiesel** [comment]
I don't think this has already been fixed, but a solution worth trying is to replace inside  FlatList "keyExtractor" with "listKey",
take a read here for more [informations ](https://stackoverflow.com/questions/49276526/nested-flat-list-invariant-violation-a-virtualizedlist-contains-a-cell-which-it)

**Comment by Alex1899** [comment]
any updates? Experiencing the same issue.

**Comment by qhoarau** [comment]
Apparently it comes from react-native-tab-view migrating to ViewPager library (previously using react-native-reanimated and react-native-gesture-handler) since version 3.0.0

The only workaround I've found is to just downgrade react-native-tab-view to version 2.16.0

**Comment by emekaokoli** [comment]
I have this issue and I am not using react-native-tab-view
