### ISSUE TITLE
[DevMenu] Reload shortcut does not work with alternative keyboard layouts

### ISSUE THREAD

**Issue by alisnic** [facebook/react-native#326]
I am a Colemak user, cmd-R does not reload the app within the simulator. If I switch to QWERTY, the shortcut works.

**Comment by vjeux** [comment]
Thanks for flagging. cmd+R support is using some trickery already. I'm unsure if it's even possible to detect different keyboard layouts and change the shortcut accordingly :x

**Comment by tehfailsafe** [comment]
Does disabling the menu item `Hardware > Keyboard > iOS uses same layout as OSX` fix it while keeping the layout?

**Comment by alisnic** [comment]
@tehfailsafe nope, but shake gesture as a workaround is pretty nice, since its shortcut (cmd-ctrl-z) works on any layout

**Comment by bradediger** [comment]
This works properly if you change the iOS hardware keyboard layout:

Home > Settings > General > Keyboard > Hardware Keyboard > English > (your layout)

iOS then passes the hardware keyboard events correctly. This is now working for me using Dvorak.

**Comment by brentvatne** [comment]
Thanks @bradediger :smile: :rocket:

**Comment by feifanzhou** [comment]
I am using Dvorak. Cmd-R doesn't work, but Cmd-P (where R would be in QWERTY) does work.
