### ISSUE TITLE
[Android] Systrace module out of date?

### ISSUE THREAD

**Issue by arbesfeld** [facebook/react-native#3260]
I am unable to compile the Android master branch. it seems like some files like [SystractRequestListener](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/modules/fresco/SystraceRequestListener.java#L12) are using a newer version of Systrace than the open-sourced one [here](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/systrace/Systrace.java).

**Comment by mikearmstrong001** [comment]
Thanks for raising this, it should now be resolved

**Comment by arbesfeld** [comment]
Hmm, another regression it seems? [OnLoad.cpp](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/jni/react/jni/OnLoad.cpp) references "ReactNativeArray.h" which is not on the master tree.

@mikearmstrong001
