### ISSUE TITLE
Incorrect Android APIs in README requirements. react-native 0.64

### ISSUE THREAD

**Issue by CyxouD** [facebook/react-native#32618]
### Description

When a developer opens 0.64 stable build at https://github.com/facebook/react-native/tree/0.64-stable, he sees that React Native apps may target iOS 10.0 and Android 4.1 (API 16) or newer. However, API 16-20 are dropped in 0.64 according to https://reactnative.dev/blog/2021/03/12/version-0.64 and minSdkVersion in build.gradle file https://github.com/facebook/react-native/blob/0.64-stable/ReactAndroid/build.gradle 
![image](https://user-images.githubusercontent.com/17162008/142376604-d1af1422-8b2c-493e-b936-2d80919c7176.png)

Previously, I've incorrectly added this issue to react-native-website https://github.com/facebook/react-native-website/issues/2851

### Version

0.64 stable

### Steps to reproduce

1. Open https://github.com/facebook/react-native/tree/0.64-stable
2. See that "React Native apps may target iOS 10.0 and Android 4.1 (API 16) or newer." in requirements

**Comment by cortinico** [comment]
I'm unsure what we want to do here. The README was not updated before releasing `0.64`, that's unfortunate. However I think the number of people that are effectively checking the README file from a previous revision is limited + having a blogpost for the release that clearly states the version bump should be enough to clarify any doubts.

I think we can close this but I'm curious to hear if there are other opinions against it.

**Comment by CyxouD** [comment]
In my case, I had been checking the last RN version which supported Android API 16-20 with GitHub's tags, so I started the project with react-native `0.64`. Hopefully, quickly after that, I tried to build an app on Android API 16 and got error. That's why I had to restart react-native `0.63` project.
Another case, which I didn't encounter, but I hope can be possible. If developer updates to RN `0.64` and it is important for him to support Android API 16-20 or/and iOS 10, then he will be required to reverse commit/discard changes/downgrade after he founds out it. 

I agree that most RN updates happen with blogpost's reading, so I think that my case is more probable than the update case (another case).

**Comment by cortinico** [comment]
> I agree that most RN updates happen with blogpost's reading, so I think that my case is more probable than the update case (another case).

You meant "less probable" or I misunderstood your question?

**Comment by CyxouD** [comment]
I meant that it is "more probable"  in my case to make the same mistake with choosing the correct RN version. However, probably it is really "less probable" that updates happen without blogpost :)

**Comment by CyxouD** [comment]
I see that this was fixed in https://github.com/facebook/react-native/pull/32620, so it can be closed
