### ISSUE TITLE
RNTester: Text elements with custom accessibility actions don't work on iOS

### ISSUE THREAD

**Issue by amgleitman** [facebook/react-native#32616]
### Description

RNTester's accessibility page shows an example where you can add custom accessibility actions to text elements. However, this doesn't appear to work. Running RNTester on iOS causes and opening the Accessibility API page shows a red box error like this:

-[RCTTextView setOnAccessibilityAction:]: unrecognized selector sent to instance 0x7f9fdcd49c90

The error appears to come from the `RNTesterBlock` on this line: https://github.com/facebook/react-native/blob/d29f3d2a6b84c17ad057f4e9c8dc35b3fe16fb19/packages/rn-tester/js/examples/Accessibility/AccessibilityExample.js#L720

Looking through things, it appears that `onAccessibilityAction` belongs to `RCTView`, which `RCTTextView` does not inherit from.

If `<Text>` elements are supposed to support custom accessibility actions like this, then we should refactor things accordingly (one idea might be having `RCTTextView` inherit from `RCTView` instead of `UIView`). Otherwise, we should probably remove this example from RNTester.

### Version

0.66-stable

### Output of `react-native info`

Not sure if this is fully relevant, since this is all contained within the repo itself. That being said, I'm using whatever config settings RNTester is set to run.

### Steps to reproduce

1. Build and run RNTester.
2. Open the Accessibility item under APIs.

Expected: Everything works as normal.

Actual: A red box error appears as described above.

**Comment by lindboe** [comment]
We also encountered this on an app using RN 0.66.1. We wanted to use accessibilityActions to work around issues with links nested in text blocks, which works well on Android, but iOS has this error.

**Comment by lindboe** [comment]
I went through and tested those props on Text, and checked onAccessibilityAction on TextInput as well, and this problem is fixed in the New Architecture version of these components, for what it's worth.

**Comment by zfrankdesign** [comment]
Trying to use the `onAccessibilityTap` prop on a TextInput

![Screenshot 2023-11-01 at 2 25 52 PM](https://github.com/facebook/react-native/assets/870737/d2802ced-4281-42c6-b2f3-088bf2dd6241)
