### ISSUE TITLE
App crash when start debugging with chrome. rn version 0.66.3

### ISSUE THREAD

**Issue by Abakanmeister** [facebook/react-native#32622]
### Description

I setup clean app via react-native init and app crash when start debugging with chrome.
Error: 
Error: Unable to resolve module ./debugger-ui/debuggerWorker.aca173c4 from /Users/***/reactNativeFun/app/.:
None of these files exist:
  * debugger-ui/debuggerWorker.aca173c4(.native|.native.js|.js|.native.json|.json|.native.ts|.ts|.native.tsx|.tsx)
  * debugger-ui/debuggerWorker.aca173c4/index(.native|.native.js|.js|.native.json|.json|.native.ts|.ts|.native.tsx|.tsx)

### Version

0.66.3

### Output of `react-native info`

info Fetching system and libraries information...
(node:6038) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 17.77 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 8.1.3 - ~/.nvm/versions/node/v16.13.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 23, 25, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2
      System Images: android-19 | Google APIs Intel x86 Atom, android-21 | Intel x86 Atom, android-21 | Google APIs Intel x86 Atom_64, android-22 | Google APIs Intel x86 Atom, android-22 | Google APIs Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom, android-26 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2.1 4.2.1
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_265 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.66.3 => 0.66.3
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Setup project via react-native init and run "debugging with chrome"

**Comment by vyshakh** [comment]
@Abakanmeister I had similar issue, and I found out that react-native-reanimated caused the issue for.   
**Please note that Reanimated 2 doesn't support remote debugging, only Flipper can be used for debugging.**
https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation/

**Comment by Abakanmeister** [comment]
> @Abakanmeister I had similar issue, and I found out that react-native-reanimated caused the issue. **Please note that Reanimated 2 doesn't support remote debugging, only Flipper can be used for debugging.** https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation/

Oh i got it. Thank you)
