### ISSUE TITLE
mac m1 build android BUILD SUCCESSFUL in 2h 7m 54s

### ISSUE THREAD

**Issue by tiankun** [facebook/react-native#32626]
### Description

mac m1 build android BUILD SUCCESSFUL in 2h 7m 54s

### Version

0.63.2

### Output of `react-native info`

 BUILD SUCCESSFUL in 2h 7m 54s

### Steps to reproduce

mac m1 build android BUILD SUCCESSFUL in 2h 7m 54s

**Comment by davidnotes** [comment]
The time your RN compilation depends on ur code base and network env. The msg you provide does no help to solve the problem, pls show more.

**Comment by cortinico** [comment]
Please share a Gradle Scan, otherwise we can't help you further: https://scans.gradle.com/
