### ISSUE TITLE
AppState is not changes when I pull down the notifications bar (RN 0.66, Android 12, Pixel 4a)

### ISSUE THREAD

**Issue by danilminibaev** [facebook/react-native#32628]
### Description

The AppState is not changing when I pull down the notifications bar

Previously described here, but was fixed in RN 0.60 (and now back again):

https://github.com/facebook/react-native/issues/24149
https://github.com/facebook/react-native/issues/24149#issuecomment-941379854
![output](https://user-images.githubusercontent.com/38855613/142621842-78b159f4-5d3e-4b47-841b-900d37b67d39.gif)

### Version

0.66.3

### Output of `react-native info`

```
System:
    OS: macOS 11.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 284.98 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.16.1/bin/yarn
    npm: 6.14.12 - ~/.nvm/versions/node/v14.16.1/bin/npm
    Watchman: 2021.11.01.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7784292
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.3 => 0.66.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1) Open App on device
2) Pull down notification bar (turn GPS on/off etc)

AppState doesn't changes

### Expected Behavior

AppState listener emits `change` event

### Snack, code example, screenshot, or link to a repository

https://snack.expo.dev/@danilm/appstate-function-component-example

**Comment by askumar1** [comment]
Unsubscribe

**Comment by idanlevi1** [comment]
@danilminibaev  Any update?
