### ISSUE TITLE
Method addObserver must be called on the main thread

### ISSUE THREAD

**Issue by edpapyan902** [facebook/react-native#32630]
### Description

I'm going to build share to snapchat app with snapchat creative kit. But I can't run app. I've tested with creating new latest project, but same result.
When I run example react-native project in snapchat integration, it works well.

### Version

0.63.4

### Output of `react-native info`

info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.19042
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
    Memory: 6.64 GB / 15.94 GB
  Binaries:
    Node: 16.4.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.24.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7784292
    Visual Studio: 16.10.31410.357 (Visual Studio Community 2019)
  Languages:
    Java: 13.0.2 - C:\Program Files\Java\jdk-13.0.2\bin\javac.EXE
    Python: 3.9.2 - C:\Python39\python.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: ~0.63.4 => 0.63.4
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

When I run app, I can't open.

### Snack, code example, screenshot, or link to a repository

https://github.com/nano5319/react-native-snapchat-share
![image](https://user-images.githubusercontent.com/84326188/142709675-e674e3b9-117f-485b-8985-47730d155ab0.png)
I've followed all steps in [document](https://kit.snapchat.com/docs/creative-kit-react-native)

It's error when I run app.
![image](https://user-images.githubusercontent.com/84326188/142709708-a2eaf37a-ffa9-4f7f-a5d6-e1a8542e2173.png)

**Comment by A000ANB** [comment]
Same issue for Login KIT

**Comment by vamper424** [comment]
Yhea happy new year. Friend.
