### ISSUE TITLE
YogaKit.modulemap not found when archiving with Xcode 13

### ISSUE THREAD

**Issue by tscharke** [facebook/react-native#32643]
### Description

- Update an existing Project to React-Native 0.66.3
- Running on iOS-Simulator (Simulate an iPhone 11 Pro Max)…
  - via the RN-cli -> works perfect👌
  - via Xcode 13.1 -> works perfect👌

Trying to create a Release via Xcode (archive for `Any iOS Devices (arm64, armv7)`) crashes in seconds with this error:

`error: module map file '/Library/Developer/Xcode/DerivedData/RNApp-epyvuwhzrqjwdbfenwzxjehsdrpn/Build/Intermediates.noindex/ArchiveIntermediates/RNApp/BuildProductsPath/Release-iphoneos/YogaKit/YogaKit.modulemap' not found`

### Version

0.66.3

### Output of `react-native info`

System:
    OS: macOS 11.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
    Memory: 1.27 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.4.0 - ~/.nvm/versions/node/v16.4.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.4.0/bin/yarn
    npm: 7.19.0 - ~/.nvm/versions/node/v16.4.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - ~/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 16, 23, 24, 25, 26, 27, 28, 29, 30
      Build Tools: 28.0.3, 29.0.0, 29.0.2
      System Images: android-16 | Intel x86 Atom, android-24 | Intel x86 Atom_64, android-27 | Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_60 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.3 => 0.66.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

- Run npx react-native init projectname
- Open the xcodeproj file in xcode
- Choose `Any iOS Devices (arm64, armv7)` as emulator
- Select "Product" -> "Archive" from the Xcode-menu

**Comment by tscharke** [comment]
This [answer](https://github.com/facebook/react-native/issues/28503#issuecomment-609048885) of @apostopher in this [ticket](https://github.com/facebook/react-native/issues/28503) has inspired me and I've found a **solution**.

In my *Podfile* I set/referenced `platform :ios, '11.0'` which does not correspond to the setting in Xcode.
So I changed the **Deployment Info** in Xcode to the latest major-version (`11.4`) and it **works** 💪

**Comment by spokeen** [comment]
Maybe u can open xxx.xcworkspace instead of xxx. xcodeproj

**Comment by showtan001** [comment]
Set "iOS Deployment Target: 11.0" in "info".

**Comment by karatekid430** [comment]
On Apple arm64 Mac, you can fix this by adding to Podfile and doing `npx pod-install`:

```
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["ONLY_ACTIVE_ARCH"] = 'NO'
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = 'arm64'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0' // Set to whatever your target in Xcode and Podfile is set to
      end
    end
  
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["ONLY_ACTIVE_ARCH"] = 'NO'
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = 'arm64'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0' // Set to whatever your target in Xcode and Podfile is set to
    end
  end
```

You also need to make sure each target in Xcode has Active Arch Only = No and excluded arch for "Any iOS Simulator SDK" to be "arm64". This will unfortunately require you to install Rosetta-2 to work.

**Comment by thanhdevapp** [comment]
same problem because i using DevCLeaner for Xcode. before my project run ok !
