### ISSUE TITLE
RCTUIImageViewAnimated crash in iOS 15

### ISSUE THREAD

**Issue by weiningtry7** [facebook/react-native#32651]
### Description

In release environment，we found lots crash log in iOS15.0。

#20 Thread

SIGTRAP

解析原始
0
CoreFoundation
_CFDataGetBytes + 156
4
UIKitCore
0x0000000183616000 + 7801553968560722160
5
HWY
facebook::react::JSIExecutor::defaultTimeoutInvoker(std::__1::function<void ()> const&, std::__1::function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > ()>) + 12773936425746362616
6
HWY
__44-[RCTUIImageViewAnimated displayDidRefresh:]_block_invoke (RCTUIImageViewAnimated.m:0)
7
Foundation
___NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 24
19
libsystem_pthread.dylib
_pthread_wqthread + 7728848212416528612

### Version

0.61

### Output of `react-native info`

System:
    OS: macOS 11.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5575R CPU @ 2.80GHz
    Memory: 33.16 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.7.0 - ~/.nvm/versions/node/v16.7.0/bin/node
    Yarn: 1.22.0-20191211.0843 - ~/.yarn/bin/yarn
    npm: 7.20.3 - ~/.nvm/versions/node/v16.7.0/bin/npm
    Watchman: 4.5.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
  IDEs:
    Xcode: 13.0/13A233 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.223 => 0.61.223

### Steps to reproduce

It's not always happened. 

### Snack, code example, screenshot, or link to a repository

It‘s  similar to SDWebImage isuure： https://github.com/SDWebImage/SDWebImage/issues/3273
but in the master of SDWebImage commit was to revert, so i don't the commit with CFRetaion(imageSource) is correct or not
please focus on it and give  the correct practice

**Comment by tomsemi** [comment]
how to fix

**Comment by weiningtry7** [comment]
a similar issure https://github.com/onevcat/Kingfisher/issues/1844
but still not have accurate response

**Comment by lbyzju** [comment]
any ideas？

**Comment by weiningtry7** [comment]
According to this issure https://github.com/SDWebImage/SDWebImage/issues/3273
```
static NSLock *kRCTAnimatedImageLock = nil;

- (UIImage *)animatedImageFrameAtIndex:(NSUInteger)index
{
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        kRCTAnimatedImageLock = [[NSLock alloc] init];
    });
    [kRCTAnimatedImageLock lock];
    CGImageRef imageRef = CGImageSourceCreateImageAtIndex(_imageSource, index, NULL);
    if (!imageRef) {
        [kRCTAnimatedImageLock unlock];
        return nil;
    }
    UIImage *image = [[UIImage alloc] initWithCGImage:imageRef scale:_scale orientation:UIImageOrientationUp];
    CGImageRelease(imageRef);
    [kRCTAnimatedImageLock unlock];
    return image;
}
```
this crash was not found after adding these code，But it was never the official solution， hope to userful

**Comment by rush397** [comment]
Hi everyone,

We have encountered similar issue, with approximately 50 crashes occurring daily in our production environment.

We have managed to reproduce the issue consistently. Here are the steps to reproduce:

1. Add a new demo in RNTester with the following code:

```
const styles = StyleSheet.create({
  gif: {
    flex: 1,
    height: 200,
  },
});

const gifLinks = [
  "https://media.giphy.com/media/5GoVLqeAOo6PK/giphy.gif",
  "https://media.giphy.com/media/26BRBupa9s7s0sU7G/giphy.gif",
  "http://assets.sbnation.com/assets/2512203/dogflops.gif",
  "https://media.giphy.com/media/l0HlQ7LRal8K3kS3K/giphy.gif",
  "https://media.giphy.com/media/3o6ZtpxSZbQRRnwCKQ/giphy.gif",
  "https://raw.githubusercontent.com/liyong03/YLGIFImage/master/YLGIFImageDemo/YLGIFImageDemo/joy.gif",
  "https://media.giphy.com/media/l0HlLwQO6uV6nXH6U/giphy.gif",
  "https://media.giphy.com/media/3oz8xKaR836UJOYeOc/giphy.gif",
  "https://media.giphy.com/media/l0HlKq0Zzq5q6X8gE/giphy.gif",
  "https://media.giphy.com/media/3oEjHGrVGrqgFFknfO/giphy.gif",
  "https://media.giphy.com/media/3oEjHGrVGrqgFFknfO/giphy.gif",
  "https://media.giphy.com/media/l0HlMUbP2e4cE5kVG/giphy.gif",
  "https://media.giphy.com/media/3o7aD2saalBwwftBIY/giphy.gif",
];

const examples = [];

for (let i = 0; i < 20; i++) {
  const example = {
    title: `Animated GIF${i}`,
    render: function (): React.Node {
      const [uri, setUri] = React.useState(0);
      const list = gifLinks;

      setTimeout(() => {
        setUri(uri + 1);
      }, 1000);

      return (
        <View>
          <Image
            style={styles.gif}
            source={{
              uri: list[uri % list.length],
            }}
          />
        </View>
      );
    },
    platform: 'ios',
  };
  examples.push(example);
}

exports.examples = examples;
```

3. Launch the app and let it sit idle for around 3 minutes, after which it crashes.
To address this, we referred to the solution from [SDWebImage](https://github.com/SDWebImage/SDWebImage/pull/3425/files)([issue](https://github.com/SDWebImage/SDWebImage/issues/3273)) and modified the implementation of animatedImageFrameAtIndex in RCTAnimatedImage as follows:

```
// This strip the un-wanted CGImageProperty, like the internal CGImageSourceRef in iOS 15+
// However, CGImageCreateCopy still keep those CGImageProperty, not suit for our use case
static CGImageRef __nullable SDCGImageCreateMutableCopy(CGImageRef cg_nullable image, CGBitmapInfo bitmapInfo) {
    if (!image) return nil;
    size_t width = CGImageGetWidth(image);
    size_t height = CGImageGetHeight(image);
    size_t bitsPerComponent = CGImageGetBitsPerComponent(image);
    size_t bitsPerPixel = CGImageGetBitsPerPixel(image);
    size_t bytesPerRow = CGImageGetBytesPerRow(image);
    CGColorSpaceRef space = CGImageGetColorSpace(image);
    CGDataProviderRef provider = CGImageGetDataProvider(image);
    const CGFloat *decode = CGImageGetDecode(image);
    bool shouldInterpolate = CGImageGetShouldInterpolate(image);
    CGColorRenderingIntent intent = CGImageGetRenderingIntent(image);
    CGImageRef newImage = CGImageCreate(width, height, bitsPerComponent, bitsPerPixel, bytesPerRow, space, bitmapInfo, provider, decode, shouldInterpolate, intent);
    return newImage;
}

static inline CGImageRef __nullable SDCGImageCreateCopy(CGImageRef cg_nullable image) {
    if (!image) return nil;
    return SDCGImageCreateMutableCopy(image, CGImageGetBitmapInfo(image));
}

- (UIImage *)animatedImageFrameAtIndex:(NSUInteger)index
{
  CGImageRef imageRef = CGImageSourceCreateImageAtIndex(_imageSource, index, NULL);
  if (!imageRef) {
    return nil;
  }
    // iOS 15+, CGImageRef now retains CGImageSourceRef internally. To workaround its thread-safe issue, we have to strip CGImageSourceRef, using Force-Decode (or have to use SPI `CGImageSetImageSource`), See: https://github.com/SDWebImage/SDWebImage/issues/3273
    if (@available(iOS 15, tvOS 15, *)) {
        if (imageRef) {
            CGImageRef newImageRef = SDCGImageCreateCopy(imageRef);
            CGImageRelease(imageRef);
            imageRef = newImageRef;
        }
    }
  UIImage *image = [[UIImage alloc] initWithCGImage:imageRef scale:_scale orientation:UIImageOrientationUp];
  CGImageRelease(imageRef);
  return image;
}
```

After applying this change, the issue was resolved. However, this approach seems to have some performance drawbacks. Could anyone advise if this solution is feasible?

Additionally, it appears that this issue has persisted in iOS versions 15 and above. Are there any plans to address this in the near future?
