### ISSUE TITLE
onPanResponderTerminationRequest never called in Android

### ISSUE THREAD

**Issue by tushar04** [facebook/react-native#32654]
### Description

Hello,
I'm trying to achieve card swipe swipe ui similar to Tinder. But the variation is that I have scrollview inside a card. So basically scroll-view inside pan responder view. So on android after pan gesture is triggered scrollview takes over and `onPanResponderTerminate` is called but `onPanResponderTerminationRequest false` is not respected.
`onPanResponderTerminationRequest` is never gets triggered. I belive this is the issue with React Native `PanResponder`. It will be very helpful if this gets addressed.

### Version

0.64.0

### Output of `react-native info`

System:
    OS: macOS 11.6
    CPU: (8) x64 Apple M1
    Memory: 22.01 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.1 - /usr/local/bin/node
    Yarn: Not Found
    npm: 7.11.2 - /usr/local/bin/npm
    Watchman: 2021.06.07.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 28, 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0
      System Images: android-31 | Google Play ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7583922
    Xcode: 13.0/13A233 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: ^0.64.2 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Have a `ScrollView` insider a `View` with `PanResponder` handlers and try moving View in (try swipe right/left). 
Pan gesture is triggered but immediately interrupted which cause `onPanResponderTerminate`  to trigger. As scrollview takes over and becomes a responder now

**Comment by zichengbohan** [comment]
HI,  was it resolved with this question ? And I have this question, need your help

**Comment by tushar04** [comment]
> HI, was it resolved with this question ? And I have this question, need your help

Unfortunately not.

**Comment by Gregoirevda** [comment]
`onPanResponderTerminationRequest` is not called on Android so setting:
`onPanResponderTerminationRequest: () => false` will only call `onPanResponderTerminate` in Android.
You could have similar logic between `onPanResponderRelease` and `onPanResponderTerminate`

**Comment by zewt** [comment]
Can confirm this bug too.  onResponderTerminationRequest (and onPanResponderTerminationRequest) aren't called on Android when a scroller wants to become the responder, so when you're trying to respond to drags that overlap with scrollers, the drag gets stolen from your responder without asking.  This is a problem for card-style UIs, where you do want to allow scrolling, but trigger a different gesture if the user drags down while the scroller is already at the top.

PanResponder's onShouldBlockNativeResponder seems to have no effect on this, and the documentation doesn't mention it either.

**Comment by sleeper-andrew** [comment]
strangely, i have found that wrapping the view and applying the pan handlers to an `Animated.View` (instead of a standard `View`) actually prevents the `ScrollView` from taking over.

**Comment by zewt** [comment]
Why even bother reporting bugs?

**Comment by rohitx15** [comment]
I am running into this as well. Did anyone find a solution?

**Comment by song06971** [comment]
same issue here. ... any update on this?
