### ISSUE TITLE
"RCTActivityIndicatorView" was not found in the UIManager.

### ISSUE THREAD

**Issue by SHIVAJIKUMAR007** [facebook/react-native#32668]
### Description

Activity indicator giving me error 

Invariant Violation: requireNativeComponent: "RCTActivityIndicatorView" was not found in the UIManager.

This error is located at:
    in RCTActivityIndicatorView (at ActivityIndicator.js:118)
    in RCTView (at View.js:32)
    in View (at ActivityIndicator.js:108)
    in ActivityIndicator (at Home2.js:150)
    in RCTView (at View.js:32)
    in View (at Home2.js:149)
    in RCTView (at View.js:32)
    in View (at Home2.js:135)
    in RCTView (at View.js:32)
    in View (at Home2.js:65)
    in Home2 (at SceneView.tsx:126)
    in StaticContainer
    in EnsureSingleNavigator (at SceneView.tsx:118)
    in SceneView (at useDescriptors.tsx:210)
    in RCTView (at View.js:32)
    in View (at Screen.tsx:63)
    in RCTView (at View.js:32)
    in View (at Background.tsx:13)
    in Background (at Screen.tsx:58)
    in Screen (at BottomTabView.tsx:129)
    in RCTView (at View.js:32)
    in View (at ResourceSavingView.tsx:42)
    in RCTView (at View.js:32)
    in View (at ResourceSavingView.tsx:37)
    in ResourceSavingScene (at ScreenFallback.tsx:44)
    in MaybeScreen (at BottomTabView.tsx:122)
    in RCTView (at View.js:32)
    in View (at ScreenFallback.tsx:31)
    in MaybeScreenContainer (at BottomTabView.tsx:93)
    in RNCSafeAreaProvider (at SafeAreaContext.tsx:76)
    in SafeAreaProvider (at SafeAreaProviderCompat.tsx:46)
    in SafeAreaProviderCompat (at BottomTabView.tsx:92)
    in BottomTabView (at createBottomTabNavigator.tsx:116)
    in Unknown (at createBottomTabNavigator.tsx:115)
    in BottomTabNavigator (at Navigator.js:60)
    in EnsureSingleNavigator (at BaseNavigationContainer.tsx:430)
    in BaseNavigationContainer (at NavigationContainer.tsx:132)
    in ThemeProvider (at NavigationContainer.tsx:131)
    in NavigationContainerInner (at Navigator.js:53)
    in Navigator (at App.js:49)
    in ThemeProvider (at App.js:46)
    in ThemeProvider (at Provider.tsx:83)
    in RCTView (at View.js:32)
    in View (at PortalHost.tsx:125)
    in Portal.Host (at Provider.tsx:81)
    in Provider (at App.js:45)
    in ThemeWraper (at App.js:27)
    in Provider (at App.js:26)
    in App (at renderApplication.js:50)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:92)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:119)
    in AppContainer (at renderApplication.js:43)
    in LaCasa(RootComponent) (at renderApplication.js:60)
 ERROR  Invariant Violation: requireNativeComponent: "RCTScrollContentView" was not found in the UIManager.

This error is located at:
    in RCTScrollContentView (at ScrollView.js:1674)
    in RCTScrollView (at ScrollView.js:1792)
    in ScrollView (at ScrollView.js:1818)
    in ScrollView (at LogBoxInspectorCodeFrame.js:58)
    in RCTView (at View.js:32)
    in View (at LogBoxInspectorCodeFrame.js:57)
    in RCTView (at View.js:32)
    in View (at LogBoxInspectorCodeFrame.js:56)
    in RCTView (at View.js:32)
    in View (at LogBoxInspectorSection.js:30)
    in RCTView (at View.js:32)
    in View (at LogBoxInspectorSection.js:25)
    in LogBoxInspectorSection (at LogBoxInspectorCodeFrame.js:55)
    in LogBoxInspectorCodeFrame (at LogBoxInspector.js:117)
    in RCTScrollContentView (at ScrollView.js:1674)
    in RCTScrollView (at ScrollView.js:1792)
    in ScrollView (at ScrollView.js:1818)
    in ScrollView (at LogBoxInspector.js:116)
    in LogBoxInspectorBody (at LogBoxInspector.js:77)
    in RCTView (at View.js:32)
    in View (at LogBoxInspector.js:70)
    in LogBoxInspector (at LogBoxInspectorContainer.js:27)
    in RCTView (at View.js:32)
    in View (at LogBoxInspectorContainer.js:26)
    in _LogBoxInspectorContainer (at LogBoxData.js:432)
    in LogBoxStateSubscription (at renderApplication.js:50)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:92)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:119)
    in AppContainer (at renderApplication.js:43)
    in LogBox(RootComponent) (at renderApplication.js:60)
 ERROR  Invariant Violation: An error was thrown when attempting to render log messages via LogBox.

requireNativeComponent: "RCTScrollContentView" was not found in the UIManager.

This error is located at:
    in RCTScrollContentView (at ScrollView.js:1674)
    in RCTScrollView (at ScrollView.js:1792)
    in ScrollView (at ScrollView.js:1818)
    in ScrollView (at LogBoxInspectorCodeFrame.js:58)
    in RCTView (at View.js:32)
    in View (at LogBoxInspectorCodeFrame.js:57)
    in RCTView (at View.js:32)
    in View (at LogBoxInspectorCodeFrame.js:56)
    in RCTView (at View.js:32)
    in View (at LogBoxInspectorSection.js:30)
    in RCTView (at View.js:32)
    in View (at LogBoxInspectorSection.js:25)
    in LogBoxInspectorSection (at LogBoxInspectorCodeFrame.js:55)
    in LogBoxInspectorCodeFrame (at LogBoxInspector.js:117)
    in RCTScrollContentView (at ScrollView.js:1674)
    in RCTScrollView (at ScrollView.js:1792)
    in ScrollView (at ScrollView.js:1818)
    in ScrollView (at LogBoxInspector.js:116)
    in LogBoxInspectorBody (at LogBoxInspector.js:77)
    in RCTView (at View.js:32)
    in View (at LogBoxInspector.js:70)
    in LogBoxInspector (at LogBoxInspectorContainer.js:27)
    in RCTView (at View.js:32)
    in View (at LogBoxInspectorContainer.js:26)
    in _LogBoxInspectorContainer (at LogBoxData.js:432)
    in LogBoxStateSubscription (at renderApplication.js:50)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:92)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:119)
    in AppContainer (at renderApplication.js:43)
    in LogBox(RootComponent) (at renderApplication.js:60)

### Version

0.66.0

### Output of `react-native info`

 npx react-native info
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz     
    Memory: 2.75 GB / 7.89 GB
  Binaries:
    Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6392135
    Visual Studio: Not Found
  Languages:
    Java: 1.8.0_251 - C:\Program Files\Java\jdk\bin\javac.EXE 
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.0 => 0.66.0 
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

i was working on my project and i run npx react-native link @react-native-picker/picker and after that this error started to showing me.

### Snack, code example, screenshot, or link to a repository

Invariant Violation: requireNativeComponent: "RCTActivityIndicatorView" was not found in the UIManager.

This error is located at:
    in RCTActivityIndicatorView (at ActivityIndicator.js:118)
    in RCTView (at View.js:32)
    in View (at ActivityIndicator.js:108)
    in ActivityIndicator (at Home2.js:150)
    in RCTView (at View.js:32)
    in View (at Home2.js:149)
    in RCTView (at View.js:32)
    in View (at Home2.js:135)
    in RCTView (at View.js:32)
    in View (at Home2.js:65)
    in Home2 (at SceneView.tsx:126)
    in StaticContainer
    in EnsureSingleNavigator (at SceneView.tsx:118)
    in SceneView (at useDescriptors.tsx:210)
    in RCTView (at View.js:32)
    in View (at Screen.tsx:63)
    in RCTView (at View.js:32)
    in View (at Background.tsx:13)
    in Background (at Screen.tsx:58)
    in Screen (at BottomTabView.tsx:129)
    in RCTView (at View.js:32)
    in View (at ResourceSavingView.tsx:42)
    in RCTView (at View.js:32)
    in View (at ResourceSavingView.tsx:37)
    in ResourceSavingScene (at ScreenFallback.tsx:44)
    in MaybeScreen (at BottomTabView.tsx:122)
    in RCTView (at View.js:32)
    in View (at ScreenFallback.tsx:31)
    in MaybeScreenContainer (at BottomTabView.tsx:93)
    in RNCSafeAreaProvider (at SafeAreaContext.tsx:76)
    in SafeAreaProvider (at SafeAreaProviderCompat.tsx:46)
    in SafeAreaProviderCompat (at BottomTabView.tsx:92)
    in BottomTabView (at createBottomTabNavigator.tsx:116)
    in Unknown (at createBottomTabNavigator.tsx:115)
    in BottomTabNavigator (at Navigator.js:60)
    in EnsureSingleNavigator (at BaseNavigationContainer.tsx:430)
    in BaseNavigationContainer (at NavigationContainer.tsx:132)
    in ThemeProvider (at NavigationContainer.tsx:131)
    in NavigationContainerInner (at Navigator.js:53)
    in Navigator (at App.js:49)
    in ThemeProvider (at App.js:46)
    in ThemeProvider (at Provider.tsx:83)
    in RCTView (at View.js:32)
    in View (at PortalHost.tsx:125)
    in Portal.Host (at Provider.tsx:81)
    in Provider (at App.js:45)
    in ThemeWraper (at App.js:27)
    in Provider (at App.js:26)
    in App (at renderApplication.js:50)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:92)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:119)
    in AppContainer (at renderApplication.js:43)
    in LaCasa(RootComponent) (at renderApplication.js:60)
 ERROR  Invariant Violation: requireNativeComponent: "RCTScrollContentView" was not found in the UIManager.

This error is located at:
    in RCTScrollContentView (at ScrollView.js:1674)
    in RCTScrollView (at ScrollView.js:1792)
    in ScrollView (at ScrollView.js:1818)
    in ScrollView (at LogBoxInspectorCodeFrame.js:58)
    in RCTView (at View.js:32)
    in View (at LogBoxInspectorCodeFrame.js:57)
    in RCTView (at View.js:32)
    in View (at LogBoxInspectorCodeFrame.js:56)
    in RCTView (at View.js:32)
    in View (at LogBoxInspectorSection.js:30)
    in RCTView (at View.js:32)
    in View (at LogBoxInspectorSection.js:25)
    in LogBoxInspectorSection (at LogBoxInspectorCodeFrame.js:55)
    in LogBoxInspectorCodeFrame (at LogBoxInspector.js:117)
    in RCTScrollContentView (at ScrollView.js:1674)
    in RCTScrollView (at ScrollView.js:1792)
    in ScrollView (at ScrollView.js:1818)
    in ScrollView (at LogBoxInspector.js:116)
    in LogBoxInspectorBody (at LogBoxInspector.js:77)
    in RCTView (at View.js:32)
    in View (at LogBoxInspector.js:70)
    in LogBoxInspector (at LogBoxInspectorContainer.js:27)
    in RCTView (at View.js:32)
    in View (at LogBoxInspectorContainer.js:26)
    in _LogBoxInspectorContainer (at LogBoxData.js:432)
    in LogBoxStateSubscription (at renderApplication.js:50)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:92)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:119)
    in AppContainer (at renderApplication.js:43)
    in LogBox(RootComponent) (at renderApplication.js:60)
 ERROR  Invariant Violation: An error was thrown when attempting to render log messages via LogBox.

requireNativeComponent: "RCTScrollContentView" was not found in the UIManager.

This error is located at:
    in RCTScrollContentView (at ScrollView.js:1674)
    in RCTScrollView (at ScrollView.js:1792)
    in ScrollView (at ScrollView.js:1818)
    in ScrollView (at LogBoxInspectorCodeFrame.js:58)
    in RCTView (at View.js:32)
    in View (at LogBoxInspectorCodeFrame.js:57)
    in RCTView (at View.js:32)
    in View (at LogBoxInspectorCodeFrame.js:56)
    in RCTView (at View.js:32)
    in View (at LogBoxInspectorSection.js:30)
    in RCTView (at View.js:32)
    in View (at LogBoxInspectorSection.js:25)
    in LogBoxInspectorSection (at LogBoxInspectorCodeFrame.js:55)
    in LogBoxInspectorCodeFrame (at LogBoxInspector.js:117)
    in RCTScrollContentView (at ScrollView.js:1674)
    in RCTScrollView (at ScrollView.js:1792)
    in ScrollView (at ScrollView.js:1818)
    in ScrollView (at LogBoxInspector.js:116)
    in LogBoxInspectorBody (at LogBoxInspector.js:77)
    in RCTView (at View.js:32)
    in View (at LogBoxInspector.js:70)
    in LogBoxInspector (at LogBoxInspectorContainer.js:27)
    in RCTView (at View.js:32)
    in View (at LogBoxInspectorContainer.js:26)
    in _LogBoxInspectorContainer (at LogBoxData.js:432)
    in LogBoxStateSubscription (at renderApplication.js:50)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:92)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:119)
    in AppContainer (at renderApplication.js:43)
    in LogBox(RootComponent) (at renderApplication.js:60)

**Comment by vaibhav834** [comment]
same issue

**Comment by Saad9624** [comment]
same issue with React native video in android.

**Comment by alihaydar56** [comment]
same problem.does anybody solve the issue?

**Comment by mahaahaadi** [comment]
same here also somebody please help

**Comment by Saad9624** [comment]
ANY UPDATE WITH THIS ISSUE?

**Comment by kavicastelo** [comment]
same issue

**Comment by serhii-kucherenko** [comment]
same issue: "RCTActivityIndicatorView" was not found in the UIManager

**Comment by rajputrj** [comment]
You can try using this command, and hopefully it will work for you.
npm install @react-native-community/activitiyindicator
