### ISSUE TITLE
can't find variable:document

### ISSUE THREAD

**Issue by zhangyanni666** [facebook/react-native#32669]
### Description

I need to use a third-party library to use document, run on the web side can show, run on a phone or tablet when react-native error, prompt **_can't find variable:document_**

### Version

0.63.4

### Output of `react-native info`

warn Package @types/jest has been ignored because it contains invalid configuration. Reason: Package subpath './package.json' is not defined by "exports" in /home/yanni/leadgen/project/leadgen-hdmap-tools/nativeViewer/node_modules/@types/jest/package.json
info Fetching system and libraries information...
(node:1232953) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
System:
    OS: Linux 5.11 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11700F @ 2.50GHz
    Memory: 2.75 GB / 15.44 GB
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.13.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/bin/watchman
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: Not Found
    Python: 2.7.18 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: ~0.63.4 => 0.63.4 
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

ReferenceError: Can't find variable: document

This error is located at:
    in RMap (at ol.js:41)
    in RCTSafeAreaView (at SafeAreaView.js:51)
    in ForwardRef(SafeAreaView) (at ol.js:40)
    in MyOpenLayers (at map.js:377)
    in RCTView (at View.js:34)
    in View (at map.js:375)
    in RCTView (at View.js:34)
    in View (at map.js:371)
    in RCTView (at View.js:34)
    in View (at map.js:319)
    in MapComponent (at SceneView.tsx:126)
    in StaticContainer
    in StaticContainer (at SceneView.tsx:119)
    in EnsureSingleNavigator (at SceneView.tsx:118)
    in SceneView (at useDescriptors.tsx:209)
    in RCTView (at View.js:34)
    in View (at DebugContainer.native.tsx:27)
    in DebugContainer (at NativeStackView.native.tsx:71)
    in MaybeNestedStack (at NativeStackView.native.tsx:228)
    in MaybeFreeze (at src/index.native.tsx:229)
    in RNSScreen (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at src/index.native.tsx:208)
    in Screen (at NativeStackView.native.tsx:175)
    in SceneView (at NativeStackView.native.tsx:276)
    in RNSScreenStack (at src/index.native.tsx:160)
    in ScreenStack (at NativeStackView.native.tsx:267)
    in NativeStackViewInner (at NativeStackView.native.tsx:321)
    in RNCSafeAreaProvider (at SafeAreaContext.tsx:76)
    in SafeAreaProvider (at SafeAreaProviderCompat.tsx:38)
    in SafeAreaProviderCompat (at NativeStackView.native.tsx:320)
    in NativeStackView (at createNativeStackNavigator.tsx:67)
    in NativeStackNavigator (at App.js:34)
    in EnsureSingleNavigator (at BaseNavigationContainer.tsx:429)
    in ForwardRef(BaseNavigationContainer) (at NavigationContainer.tsx:132)
    in ThemeProvider (at NavigationContainer.tsx:131)
    in ForwardRef(NavigationContainerInner) (at App.js:33)
    in App (created by ExpoRoot)
    in ExpoRoot (at renderApplication.js:45)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:106)
    in DevAppContainer (at AppContainer.js:121)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:132)
    in AppContainer (at renderApplication.js:39)
at node_modules/@react-navigation/bottom-tabs/src/views/Badge.tsx:35:16 in Badge
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:171:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at http://192.168.10.25:19000/index.bundle?platform=ios&dev=true&hot=false&minify=false:269904:27 in _callee$

### Snack, code example, screenshot, or link to a repository

import {
    Text,
    StyleSheet,
    View,
    SafeAreaView
} from 'react-native';
import React, { Component, useState, useRef } from 'react';
import { fromLonLat } from 'ol/proj';
import { Point } from 'ol/geom';
// import 'ol/ol.css';
import { RMap, ROSM, RLayerVector, RFeature, ROverlay, RStyle } from 'rlayers';
import locationIcon from '../assets/svg/location.svg'
import { WebView } from 'react-native-webview'
class MyOpenLayers extends Component {

    constructor(props) {
        super(props);
        this.state = {
            isLoading: true
        };
        this.center = fromLonLat([116.38, 39.9]);
    }
    componentDidMount() {
        setTimeout(() => {
            this.setState({
                isLoading: false,
            });
        }, 3000);

    }

    render() {
        if (this.state.isLoading) {
            return (
                <Text>Loading...</Text>
            );
        }

        return (
            <SafeAreaView>
                <RMap width={'100%'} height={'100%'} initial={{ center: this.center, zoom: 11 }}>
                    <ROSM />
                    <RLayerVector zIndex={10}>
                        <RStyle.RStyle>
                            <RStyle.RIcon src={locationIcon} anchor={[0.5, 0.8]} />
                        </RStyle.RStyle>

                        <RFeature
                            geometry={new Point(fromLonLat([116.38, 39.9]))}
                            onClick={(e) => {
                                e.map.getView().fit(e.target.getGeometry().getExtent(),
                                    {
                                        duration: 250,
                                        maxZoom: 15
                                    })
                            }}>
                            <ROverlay className='example-overlay'>
                                天安门
                                <br />
                                <em>&#11017; click to zoom</em>
                            </ROverlay>
                        </RFeature>
                    </RLayerVector>
                </RMap>
            </SafeAreaView>
        );
    }
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#F5FCFF',

    },
})

export default MyOpenLayers;

**Comment by zhangyanni666** [comment]
I very much look forward to the resolution and response of this issue~~~

**Comment by enzzoperez** [comment]
In mobile native development you dont have a `document` or `$` for example, if you want to integrate a web lib it has to have a mobile integration

**Comment by safaiyeh** [comment]
As @enzzoperez said, the library needs to build react native support. Open this issue with that library.

**Comment by zhangyanni666** [comment]
I wonder if react native has any plans to support the addition of document on the mobile side. @safaiyeh @react-native-bot
