### ISSUE TITLE
[Android]: get unknown property configureNdkBuildDebug

### ISSUE THREAD

**Issue by Nawbc** [facebook/react-native#32661]
### Description

[https://github.com/facebook/react-native/blob/00ac034353cbc867991bf79cb1dd103353f47126/ReactAndroid/build.gradle#L408](https://github.com/facebook/react-native/blob/00ac034353cbc867991bf79cb1dd103353f47126/ReactAndroid/build.gradle#L408)

A problem occurred configuring project ':ReactAndroid'.
> Could not get unknown property 'configureNdkBuildDebug' for project ':ReactAndroid' of type org.gradle.api.Project.

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Exception is:
org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':ReactAndroid'.
	at org.gradle.configuration.project.LifecycleProjectEvaluator.wrapException(LifecycleProjectEvaluator.java:75)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.addConfigurationFailure(LifecycleProjectEvaluator.java:68)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.access$400(LifecycleProjectEvaluator.java:51)
	at org.gradle.configuration.project.LifecycleProjectEvaluator$NotifyAfterEvaluate.run(LifecycleProjectEvaluator.java:195)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
	at org.gradle.internal.operations.DefaultBuild

### Version

main branch

### Output of `react-native info`

  System:
    OS: Linux 5.15 Manjaro Linux
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
    Memory: 366.98 MB / 15.41 GB
    Container: Yes
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v14.16.1/bin/yarn
    npm: 6.14.12 - ~/.nvm/versions/node/v14.16.1/bin/npm
  Utilities:
    Make: 4.3 - /usr/bin/make
    GCC: 11.1.0 - /usr/bin/gcc
    Git: 2.34.0 - /usr/bin/git
    FFmpeg: 4.4.1 - /usr/bin/ffmpeg
  Servers:
    Apache: 2.4.51 - /usr/bin/apachectl
  SDKs:
    Android SDK:
      API Levels: 28, 29, 30, 31
      Build Tools: 30.0.2, 31.0.0
      Android NDK: 21.4.7075529
  IDEs:
    Android Studio: AI-203.7717.56.2031.7784292
    Nano: 5.9 - /usr/bin/nano
    VSCode: 1.62.3 - /usr/bin/code
    Vim: 8.2 - /usr/bin/vim
  Languages:
    Bash: 5.1.8 - /usr/bin/bash
    Java: 11.0.13 - /usr/bin/javac
    Perl: 5.34.0 - /usr/bin/perl
    Protoc: 3.17.3 - /usr/bin/protoc
    Python: 3.9.7 - /usr/bin/python
    Python3: 3.9.7 - /usr/bin/python3
  Databases:
    SQLite: 3.32.2 - /home/nawbc/Android/Sdk/platform-tools/sqlite3
  Browsers:
    Firefox: 94.0.2

### Steps to reproduce

android studio sync

**Comment by Nawbc** [comment]
@Dulmandakh

**Comment by cortinico** [comment]
> main branch

What are you trying to do? Are you building this project? or are you using react-native from source?

**Comment by Nawbc** [comment]
> > main branch
> 
> What are you trying to do? Are you building this project? or are you using react-native from source?

yup

**Comment by cortinico** [comment]
> yup

what?

**Comment by Nawbc** [comment]
Sorry, what I mean was 'yes'. In my impression, yup means yes.  I am not very good at English. 
I am building from the source.

**Comment by cortinico** [comment]
> This commit is 2 days ago, and I successfully integrated 3 days ago by main branch

You need to bump AGP to 7.x in your project, otherwise you won't be able to build from source anymore.
Find the `classpath("com.android.tools.build:gradle:...")` dependency in your code and bump it to:

```
classpath("com.android.tools.build:gradle:7.0.1")
```

**Comment by Nawbc** [comment]
@cortinico Ok, thank you
