### ISSUE TITLE
main.jsbundle does not exist. This must be a bug with + echo 'React Native - getting this error while archiving the builds.

### ISSUE THREAD

**Issue by priyankaEdufund** [facebook/react-native#32670]
### Description

 echo 'error: File /Users/lassie/Library/Developer/Xcode/DerivedData/EduFund-bucqbjbvceebshdrsgccwdmntmhd/Build/Intermediates.noindex/ArchiveIntermediates/APP-NAME/BuildProductsPath/Release-iphoneos/APPNAME.app/main.jsbundle does not exist. This must be a bug with'
error: File /Users/lassie/Library/Developer/Xcode/DerivedData/APPNAME-bucqbjbvceebshdrsgccwdmntmhd/Build/Intermediates.noindex/ArchiveIntermediates/APP-NAME/BuildProductsPath/Release-iphoneos/APPNAME.app/main.jsbundle does not exist. This must be a bug with
+ echo 'React Native, please report it here: https://github.com/facebook/react-native/issues'
React Native, please report it here: https://github.com/facebook/react-native/issues
+ exit 2
                 Welcome to React Native!
                Learn once, write anywhere

events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: EMFILE: too many open files, watch
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:178:28)
Emitted 'error' event on NodeWatcher instance at:
    at NodeWatcher.checkedEmitError (/Users/lassie/Documents/APP-FOLDER-PATH/PROJECT-NAME/node_modules/sane/src/node_watcher.js:143:12)
    at FSWatcher.emit (events.js:314:20)
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:184:12) {
  errno: -24,
  syscall: 'watch',
  code: 'EMFILE',
  filename: null
}
Command /bin/sh emitted errors but did not return a nonzero exit code to indicate failure

### Version

react-native-cli: 2.0.1 react-native: 0.63.4

### Output of `react-native info`

react-native-cli: 2.0.1
react-native: 0.63.4

### Steps to reproduce

.

**Comment by EdwardCKF** [comment]
I have this bug too

**Comment by shan-github** [comment]
In xcode just rename the main target to something else Eg. Myapp -> Myapp-new.
