### ISSUE TITLE
[Releases] Update test-manual-e2e.sh to accept configurations for ios, android, hermes, jsc, etc.

### ISSUE THREAD

**Issue by lunaleaps** [facebook/react-native#32679]
Roughly speaking, want to update this script to prompt someone like this:
```
$ ./scripts/test-manual-e2e.js
> What platform do you want to test?
   * Android
   * iOS
> What VM are you test?
   * Hermes
   * JSC
```

Please comment below if you have more questions -- this issue isn't super descriptive

**Comment by vicente-s** [comment]
Hoping I can take this issue 😬

**Comment by vicente-s** [comment]
Have you tried running [expo start](https://docs.expo.dev/get-started/create-a-new-app/) when starting the development server to open the app on an Android device or IOS simulator?

I'm not sure about the Virtual Machine but I think React Native runs on [JavaScript Core](https://reactnative.dev/docs/javascript-environment) but here's some help on how to [enable Hermes](https://reactnative.dev/docs/hermes).

Here's what I found on [End-to-End Tests](https://reactnative.dev/docs/testing-overview#end-to-end-tests), maybe looking at tools like [Detox](https://wix.github.io/Detox/docs/introduction/getting-started/) or [Appium](https://appium.io) are worth reading about.

I'm just sharing some documentation I ended up reading so please feel free to share more information.

**Comment by lunaleaps** [comment]
@vicente-s So this issue is about improving this file: https://github.com/facebook/react-native/blob/main/scripts/test-manual-e2e.sh

Which currently goes through a sequence of testing:
1. RNTester on iOS with JSC
2. RNTester on iOS with Hermes
2. RNTester on Android with JSC
3. RNTester on Android with Hermes
3. a new RN app using the template for iOS with JSC
4. A new RN app using the template for Android with JSC

The script goes through the sequence in that order and as you see it's not testing the RN new app template with Hermes. This issue is about modifying `test-manual-e2e.sh` to allow a user to select which scenario to test rather than us having to run them all in order.

Additionally, it'd be great if we could add support for a new RN app for iOS/Android with Hermes as well but that can be a follow-up. Does that make sense? Is this something you'd be interested in?

It'd most likely be playing with yargs to modify the script

**Comment by lunaleaps** [comment]
Re: the point about adding a Hermes test for a new app template project, the script currently uses the `react-native-cli` to generate a new react native app. We might be able to modify `react-native-cli` to support a flag option for Hermes or if anyone else has another idea, please feel free to do that! 

See this issue where i proposed adding a `--hermes` flag: https://github.com/react-native-community/cli/issues/1470

**Comment by gabrieldonadel** [comment]
Hey @lunaleaps I've just opened a PR tackling this, please let me know if that addresses this issue or if you would prefer me to rewrite the `test-manual-e2e` script in Javascript using yargs
