### ISSUE TITLE
[Releases] Create CircleCI build tests for RNTester

### ISSUE THREAD

**Issue by lunaleaps** [facebook/react-native#32676]
Right now CircleCI has tests for building an app from the template. These tests run on every pull request and commit merged.

See the tests for [building Android template app](https://app.circleci.com/pipelines/github/facebook/react-native/11939/workflows/83c07cf5-b6a8-4022-b2c3-286ceb5cd53d/jobs/233445), [building iOS template app](https://app.circleci.com/pipelines/github/facebook/react-native/11939/workflows/83c07cf5-b6a8-4022-b2c3-286ceb5cd53d/jobs/233448).

and here is where those tests are configured [for Android](https://github.com/facebook/react-native/blob/main/.circleci/config.yml#L567), [and for iOS](https://github.com/facebook/react-native/blob/main/.circleci/config.yml#L594).

We should also add these 4 cases:
* build RNTester iOS w/JSC
* build RNTester iOS w/Hermes
* build RNTester Android w/Hermes
* build RNTester Android w/JSC

Luckily this matrix of instructions live in [`test-manual-e2e.sh`](https://github.com/facebook/react-native/blob/main/scripts/test-manual-e2e.sh) script -- you can try running it yourself (if you run into issues, try running it off a release branch - ex. `0.67-stable`, `0.68-stable`)

This issue is about leveraging the `test-manual-e2e.sh` script to add a CircleCI job for the 4 test cases listed above.

This is a mind-dump, feel free to ask me if anything is unclear!

**Comment by gabrieldonadel** [comment]
Hi @lunaleaps, what would be the requirements for this issue? Should we just add a workflow that builds RNTester? I'm wondering if I could work on it this week.

**Comment by lunaleaps** [comment]
Yea! I've just updated the issue description, feel free to ask away if there any clarifications!
