### ISSUE TITLE
Unable to archive build in real device and all device(arm64)

### ISSUE THREAD

**Issue by yg-yash** [facebook/react-native#32689]
### Description

When running app using react-native run-ios app is working and if i run in xcode in simulators app is also running with those except my phone selection and all device selection

but while archiving always getting this error

Stripped /Users/desktopName/Library/Developer/Xcode/DerivedData/projectName-eqvegcfcvrduuugaqflgmbsotplx/Build/Intermediates.noindex/ArchiveIntermediates/projectName/InstallationBuildProductsLocation/Applications/projectName.app/Frameworks/OpenSSL.framework/OpenSSL of architectures: armv7 armv7s arm64e
Code Signing /Users/desktopName/Library/Developer/Xcode/DerivedData/projectName-eqvegcfcvrduuugaqflgmbsotplx/Build/Intermediates.noindex/ArchiveIntermediates/projectName/InstallationBuildProductsLocation/Applications/projectName.app/Frameworks/OpenSSL.framework with Identity Apple Development: username (U234D58BKT9U)
/usr/bin/codesign --force --sign F3FABC35788EC6A82B61769F55D43AD2F1565A74  --preserve-metadata=identifier,entitlements '/Users/desktopName/Library/Developer/Xcode/DerivedData/projectName-eqvegcfcvrduuugaqflgmbsotplx/Build/Intermediates.noindex/ArchiveIntermediates/projectName/InstallationBuildProductsLocation/Applications/projectName.app/Frameworks/OpenSSL.framework'
Warning: unable to build chain to self-signed root for signer "Apple Development: --------"
/Users/desktopName/Library/Developer/Xcode/DerivedData/projectName-eqvegcfcvrduuugaqflgmbsotplx/Build/Intermediates.noindex/ArchiveIntermediates/projectName/InstallationBuildProductsLocation/Applications/projectName.app/Frameworks/OpenSSL.framework: errSecInternalComponent
Command PhaseScriptExecution failed with a nonzero exit code

i tried many things

1.Locking and unlocking keychain 
2. cleaning pod and reinstall 

nothing worked

 

### Version

0.64.2

### Output of `react-native info`

System:
    OS: macOS 11.6
    CPU: (8) arm64 Apple M1
    Memory: 333.75 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.0 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.2 => 17.0.2 
    react-native: 0.64.2 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1.Select your device in Xcode
2.Clean Build
3.Archive

**Comment by raldred** [comment]
We're getting this with xcode 13 archiving for iOS 15

**Comment by yg-yash** [comment]
@raldred 
i am getting this xcode 15 archiving for iOS 13


did you get any lead?

**Comment by danilosetubal** [comment]
Same here with Xcode 13.4 for iOS 11
