### ISSUE TITLE
Programatic refresh of empty FlatList on iOS does not show indicator

### ISSUE THREAD

**Issue by upngo** [facebook/react-native#32688]
### New Version

0.66.3

### Old Version

0.64.2

### Build Target(s)

iOS

### Output of `react-native info`

System:
    OS: macOS 11.6
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Memory: 25.39 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.2.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 7.13.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.0, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0
      System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.2 => 17.0.2 
    react-native: 0.66.3 => 0.66.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Issue and Reproduction Steps

Flatlist refresh indicator does not show when programatically refreshing if there are no elements currently in the list on iOS.
It shows the indicator if you 'pull to refresh', are on android, or have items in your flatlist.

While it's refreshing, if you scroll at all you can see that the indicator is in fact present, but not visible.

I saw this issue which is similar, but manually applying these commits didn't help.
[PR #27397 ](https://github.com/facebook/react-native/pull/27397)

**Comment by ravirajn22** [comment]
@upngo is your problem solved? From which version did you start to have this bug? I am checking which commit introduced this bug, since after updating from 63.3 to 67.3 I am also seeing this bug. This might fix it. 
https://github.com/facebook/react-native/pull/32607

**Comment by ravirajn22** [comment]
@janicduplessis can you please help on this.

**Comment by upngo** [comment]
I updated from 0.64.2 to 0.66.3 and the problem presented
