### ISSUE TITLE
[Releases] Auto-label pull requests on release branches to have "Pick Request"

### ISSUE THREAD

**Issue by lunaleaps** [facebook/react-native#32692]
I looked into whether we can do this via react-native-bot but it seems like the candidates for the bot is based on Github search: https://github.com/hramos/react-native-bot/blob/master/lib/bot/pullrequests.rb#L48

So I think this might need to be a Github action. 

Release branches should follow the form: 
`{major}.{minor}-stable`

**Comment by daschaa** [comment]
I would like to take this issue😌

**Comment by gabrieldonadel** [comment]
@lunaleaps would it be fine to use something like https://github.com/marketplace/actions/label-regex or would it be necessary developing a custom action for this?

**Comment by cortinico** [comment]
> @lunaleaps would it be fine to use something like [github.com/marketplace/actions/label-regex](https://github.com/marketplace/actions/label-regex) or would it be necessary developing a custom action for this?

My 2 cents here: this can be easily implemented in Danger. We already have a dangerfile here https://github.com/facebook/react-native/blob/main/bots/dangerfile.js with Danger already configured. We would just need to add a rule that checks if base branch != `main` -> apply the `Pick Request` label.

**Comment by gabrieldonadel** [comment]
@cortinico any suggestions on how to test the danger bot? I've made the changes but I'm not sure how to test it

**Comment by lunaleaps** [comment]
cc @hramos as well if you have any context here about testing with danger bot

**Comment by gabrieldonadel** [comment]
According to the `bots/README.md` testing should be done by running the following

```
DANGER_GITHUB_API_TOKEN=[ENV_ABOVE] yarn danger pr https://github.com/facebook/react-native/pull/1234
```

But I'll probably not be able to create/add a label using my token due to permission constraints

**Comment by gabrieldonadel** [comment]
Just a quick follow-up, I was able to test it through my fork of the repo and everything worked great. 
Here's the PR https://github.com/facebook/react-native/pull/32917

**Comment by cortinico** [comment]
> Just a quick follow-up, I was able to test it through my fork of the repo and everything worked great.

Great stuff, thanks for doing it 👍
