### ISSUE TITLE
[Releases] Only label "version: XX" labels for issues tagged with `pre-release`

### ISSUE THREAD

**Issue by lunaleaps** [facebook/react-native#32691]
We had an action that would automatically label all issues with `Version: XX` but this was too aggressive. 

We want to create a clear signal when someone files a release blocking issue (re: [this form](https://github.com/facebook/react-native/issues/new?assignees=&labels=Needs%3A+Triage+%3Amag%3A%2CType%3A+Upgrade+Issue&template=upgrade-regression-form.yml)) it gets labelled appropriately about what version it's about. That way [release supporters](https://github.com/facebook/react-native/wiki/Release-Roles-and-Responsibilities#release-supporter-responsibilities) can monitor for appropriate issues for a certain version. 

@lucasbento had a Github action that did this (see https://github.com/facebook/react-native/pull/32565) but it needs iteration. 

I think the ideal approach here is:
* Forking luca's work: https://github.com/lucasbento/core-workflow-apply-version-label, iterating on it to support to only act on issues with the `pre-release` label
* Update this repo to use that github action

If we do that, let's have the fork transferred to [react-native-community](https://github.com/react-native-community) (with proper attribution to @lucasbento's work).

**Comment by gabrieldonadel** [comment]
Hi @lunaleaps, could you detail this a little bit more? I was planning on tackling it this night if possible

**Comment by lunaleaps** [comment]
@gabrieldonadel Updated! Let me know if you have any questions! Happy to support this!

**Comment by gabrieldonadel** [comment]
Hi @lunaleaps, I've just opened a PR tackling this. There is just only thing that I'm not really sure how to accomplish,  transferring [core-workflow-apply-version-label](https://github.com/gabrieldonadel/core-workflow-apply-version-label) to [react-native-community](https://github.com/react-native-community), do you mind helping me with that?

**Comment by cortinico** [comment]
> transferring [core-workflow-apply-version-label](https://github.com/gabrieldonadel/core-workflow-apply-version-label) to [react-native-community](https://github.com/react-native-community), do you mind helping me with that?

@lunaleaps should be able to add you to that ORG and give you the rights to create a new repository. Once that is done, you should have a "Transfer Ownership" button inside the settings of your repo 👍

**Comment by lunaleaps** [comment]
@gabrieldonadel Just invited you! Let me know if you have issues transferring

**Comment by gabrieldonadel** [comment]
Hi @lunaleaps I've accepted your invite but when I try transferring it I get the following error 
![image](https://user-images.githubusercontent.com/11707729/151447155-fcd40adf-9043-4614-b8d5-71c758da0a5a.png)

**Comment by lunaleaps** [comment]
@gabrieldonadel Okay I've updated permissions, can you try again?

**Comment by gabrieldonadel** [comment]
@lunaleaps thanks for your help, I've just transferred it and I've also updated this PR https://github.com/facebook/react-native/pull/32979 to use the new `react-native-community/actions-apply-version-label` action pointing to the [new repo](https://github.com/react-native-community/actions-apply-version-label)

![image](https://user-images.githubusercontent.com/11707729/151460400-8fe93c0c-a258-40e8-9b49-0d91abcd82f1.png)
