### ISSUE TITLE
[ART] Get width of rendered Text component

### ISSUE THREAD

**Issue by shripadk** [facebook/react-native#3270]
I'm using ReactNativeART to build dynamic graphs and i'm having trouble figuring out how to get the width of the rendered Text. The use case is for building a responsive Axis component where one can transform/hide the Text component(s) depending on the device orientation or viewport size.

While searching through the docs (as well as similar issues posted by other users here) I came across some suggesting to use measure/measureLayout for getting the computed box size of rendered components. I tried the former by modifying ReactNativeART.js to see if I can use it to measure the width of the NativeText component. Unfortunately it's only picking up the ox and oy co-ordinates correctly but width and height are turning out to be 0.

Here are the relevant changes I made to ReactNativeART.js to test this functionality:

    var Text = React.createClass({

      componentDidMount() {
        this._text.measure((ox, oy, width, height, px, py) => {
          console.log(ox, oy, width, height, px, py);
        });
      },

      render: function() {
        var props = this.props;
        var textPath = props.path ? new Path(props.path).toJSON() : null;
        var textFrame = extractFontAndLines(
          props.font,
          childrenAsString(props.children)
        );
        return (
          <NativeText
            ref={component => this._text = component}
            fill={extractBrush(props.fill, props)}
            opacity={extractOpacity(props)}
            stroke={extractColor(props.stroke)}
            strokeCap={extractStrokeCap(props.strokeCap)}
            strokeDash={props.strokeDash || null}
            strokeJoin={extractStrokeJoin(props.strokeJoin)}
            strokeWidth={extractNumber(props.strokeWidth, 1)}
            transform={extractTransform(props)}

            alignment={extractAlignment(props.alignment)}
            frame={textFrame}
            path={textPath}
          />
        );
      }

    });

Any idea why this is happening? Am I doing something wrong?

**Comment by ide** [comment]
@sebmarkbage do you know if text is measurable in iOS ART?

**Comment by sebmarkbage** [comment]
It is not in ART. It is designed to be cross-platform compatible with VML, SVG, Canvas and possibly other platforms where text measurement is hard/expensive. Measuring ART is unsupported. The `ox` and `oy` shouldn't even work ideally. That's an implementation detail that is unsupported and likely to go away.

The platform specific way to solve this is using native `<Text />` outside of ART, and inside regular `<View />`s.

(I am working on a more integrated text layout solution that would make it easier to do custom layout models like this, however, that's not near ready yet.)

**Comment by shripadk** [comment]
@sebmarkbage Understood. Using the native Text component instead of ART's Text component does solve the issue. I'm currently handling these text components in a separate layer. Getting it to synchronise with changes to the Axis component is my next challenge. Would love to try out your integrated text layout solution when it's ready!

Closing this.
