### ISSUE TITLE
IOS crashes in release on importing js files with 500 exports

### ISSUE THREAD

**Issue by Ali72** [facebook/react-native#32705]
### Description

When I try importing a file to App.js with about 500 `export const` commands, the app will crash in release mode for IOS devices.
This is a new crash that didn't exist one month ago, and it only happens for the IOS release.(Android platforms is ok)

```2021-12-04 17:46:26.346838+0330 AwesomeProject[3615:509916] [native] Running application AwesomeProject ({
    initialProps =     {
    };
    rootTag = 1;
})
2021-12-04 17:46:26.563594+0330 AwesomeProject[3615:510119] [javascript] RangeError: Maximum call stack size exceeded.
2021-12-04 17:46:26.565002+0330 AwesomeProject[3615:510118] [native] Unhandled JS Exception: RangeError: Maximum call stack size exceeded.
2021-12-04 17:46:26.566365+0330 AwesomeProject[3615:510119] [javascript] Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
2021-12-04 17:46:26.567843+0330 AwesomeProject[3615:510118] *** Terminating app due to uncaught exception 'RCTFatalException: Unhandled JS Exception: RangeError: Maximum call stack size exceeded.', reason: 'Unhandled JS Exception: RangeError: Maximum call stack size exceeded., stack:
loadModuleImplementation@183:13
<unknown>@43432:34
loadModuleImplementation@183:13
<unknown>@797:55
loadModuleImplementation@183:13
guardedLoadModule@96:46
global code@44935:3
'
*** First throw call stack:
(0x181371cac 0x1983e0758 0x1024a567c 0x1025245c0 0x102524f1c 0x1813008e0 0x18131c5b8 0x18135081c 0x1024d8680 0x1024dac94 0x1024da8c4 0x102c6c94c 0x102c6e1c8 0x102c75358 0x102c75fe0 0x102c81630 0x1daceaf38 0x1daceaaa4)
libc++abi: terminating with uncaught exception of type NSException
dyld4 config: DYLD_LIBRARY_PATH=/usr/lib/system/introspection DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib
terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'RCTFatalException: Unhandled JS Exception: RangeError: Maximum call stack size exceeded.', reason: 'Unhandled JS Exception: RangeError: Maximum call stack size exceeded., stack:
loadModuleImplementation@183:13
<unknown>@43432:34
loadModuleImplementation@183:13
<unknown>@797:55
loadModuleImplementation@183:13
guardedLoadModule@96:46
global code@44935:3
'
(lldb)
 ```

### Version

0.66.3

### Output of `react-native info`

yarn run v1.22.10
$ /Users/ali/Documents/Projects/javascript/AwesomeProject/node_modules/.bin/react-native info
info Fetching system and libraries information...
System:
    OS: macOS 11.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 920.57 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.5.0 - /var/folders/n6/7xhlkzpd6rq7bj5gfmydgdf80000gn/T/yarn--1638628012957-0.5051654245209243/node
    Yarn: 1.22.10 - /var/folders/n6/7xhlkzpd6rq7bj5gfmydgdf80000gn/T/yarn--1638628012957-0.5051654245209243/yarn
    npm: 7.19.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /opt/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 19, 23, 24, 26, 28, 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0
      System Images: android-24 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7351085
    Xcode: 13.0/13A233 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: ^6.2.0 => 6.2.0 
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.3 => 0.66.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
Done in 3.47s.

### Steps to reproduce

1. Create a new project.
2. Create a js file with the 500 `export const` command.
3. Import one of them into App.js
4. Run the app in release mode on a real IOS device.

**Comment by dlebedynskyi** [comment]
look like same issue as https://github.com/facebook/react-native/issues/32672

**Comment by nucleartux** [comment]
It is not stale, it is still actual

**Comment by dlebedynskyi** [comment]
Was there any fixe on this issue? It does seem to be actual still.
