### ISSUE TITLE
fresh install processDebugMainManifest FAILED

### ISSUE THREAD

**Issue by artstylee** [facebook/react-native#32739]
### Description

hello. ive followed the instructions https://reactnative.dev/docs/environment-setup
installed java17 and edit the gradle wrapper properties
installed studio and added a virual device

may this issue be tied with java version 17 ?

### Error

```
* What went wrong:
Execution failed for task ':app:processDebugMainManifest'.
> Unable to make field private final java.lang.String java.io.File.path accessible: module java.base does not "opens java.io" to unnamed module @35da6e6b

```

### Version

"0.66.4"

### Output of `react-native info`

no cli installed due to instructions

### Steps to reproduce

fresh java 17 install
add ```distributionUrl=https\://services.gradle.org/distributions/gradle-7.3.1-bin.zip```
to gradle/wrapper/properties

### Snack, code example, screenshot, or link to a repository

![Снимок](https://user-images.githubusercontent.com/56781292/145702505-33576859-2be5-4c94-adbc-e07edf1c8c65.JPG)

**Comment by artstylee** [comment]
fixed with downgrade to JDK 15

**Comment by msarfrazanwar** [comment]
downgrade is not a fix. I own an M1 Mac and its only supports JDK 17 natively so downgrading is not an option

**Comment by cortinico** [comment]
The issue arises as you're using a version of Gradle which is not compatible with Java 17. The earliest version of Gradle compatible is 7.3 https://docs.gradle.org/7.3/release-notes.html

> installed java17 and edit the gradle wrapper properties installed studio and added a virual device
> may this issue be tied with java version 17 ?

To update the Gradle version you must run:

```
cd android && ./gradlew wrapper --gradle-version=7.3.3
```

Please note that this command **can't** be executed on JDK 17 (you need a lower version).

I'm closing as we updated the Gradle version and will be at least 7.3.3 in the upcoming version of RN (0.68.x)
