### ISSUE TITLE
[Bridge] Dispatcher does not send events when phone is locked.

### ISSUE THREAD

**Issue by jamesfzhang** [facebook/react-native#3273]
I'm working on an app that plays music, and when one song ends the next one starts. The audio player is a bridged Native Module. A song's `onStop` callback triggers an event that `RCTEventDispatcher` sends. This is fine when the app is in the foreground or background. **When the screen is locked, the event is lost somewhere between the dispatcher and the receiver**.

When the phone is locked, only "sent!" is logged:

```objc
// AudioPlayer.m

- (void)audioPlayer:(STKAudioPlayer *)player stateChanged:(STKAudioPlayerState)state previousState:(STKAudioPlayerState)previousState
{
  if (state == STKAudioPlayerStateStopped) {
    NSLog(@"sent!");
    [self.bridge.eventDispatcher sendAppEventWithName:@"AudioPlayerEvent"
                                                 body:@{@"name": @"onStop"}];
}
```

```js
// Receiver.js

NativeAppEventEmitter.addListener('AudioPlayerEvent', (event) => {
  console.log('received!');
});
```

Is there a setting that must be enabled to accommodate the dispatcher while the phone is locked?

**Comment by jamesfzhang** [comment]
Anyone care to take a look at this, please? :)

**Comment by ide** [comment]
If you encounter an issue the best way to get it fixed is to submit a PR with the right solution. There are only a handful of people working on RN and over 500 open issues and many PRs so high-quality PRs that are easy to maintain will get more attention.

**Comment by jaygarcia** [comment]
I've run into this personally.  The solution i've found is to call an execution block when the phone is brought alive to update the state of the UI.  However ALL -- absolutely ALL of the audio controls are routed through objc.

**Comment by jaygarcia** [comment]
@ide  one issue with suggesting PRs is that someone can spend hours on a PR only for it to get rejected and/or ignored, even if it's a good solution. For example, I've submitted a PR allowing web views to cache contents -- something that is almost expected.  That PR was ignored.

**Comment by mintuz** [comment]
This is a duplicate, the information provided here may help you. https://github.com/facebook/react-native/issues/1282

**Comment by jamesfzhang** [comment]
Thanks @mintuz
