### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by lucas-goldner** [facebook/react-native#32742]
### Description

When I want to build my app on a local device or archive it I always receive the following error:

```
../node_modules/react-native/scripts/react-native-xcode.sh: line 164: 50404 Trace/BPT trap: 5       
"$NODE_BINARY" $NODE_ARGS "$CLI_PATH" $BUNDLE_COMMAND $CONFIG_ARG --entry-file 
"$ENTRY_FILE" --platform "$BUNDLE_PLATFORM" --dev 
$DEV --reset-cache --bundle-output "$BUNDLE_FILE" --assets-dest 
"$DEST" $EXTRA_ARGS $EXTRA_PACKAGER_ARGS 
```

When I build in in the simulator there is no such issue

### Version

0.66.4

### Output of `react-native info`

OS: macOS 12.0.1
    CPU: (8) x64 Apple M1
    Memory: 22.28 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 6.14.15 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7199119
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_282 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.4 => 0.66.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

- Create a fresh project with npx react-native init AwesomeProject

**Comment by barakoles** [comment]
I'm getting the same!

**Comment by TarikFojnica** [comment]
Getting the same error on M1.

**Comment by RageOfJustice** [comment]
Hey. Found a solution [here](https://developer.apple.com/forums/thread/123790?login=true)
Before that solution I tried same but without 4th step. Now it works.
```
1- Delete your Podfile.lock (I like to use the command '-rm -rf Podfile.lock' on the terminal for this)

2- Delete your Pods folder (I like to use the command '-rm -rf Pods' in the terminal for this)

3- Delete your .xcworkspace

4- Pod install

5- Clear your project into XCode> Product> Clean Build Folder

```

PS: I have been installing different RN versions with different templates via `npx react-native init ...` and nothing was working.

**Comment by bozaigao** [comment]
My computer has an M1 chip，I tried everything. The most important changes are as follows:
nvm unalias default
nvm alias default node
