### ISSUE TITLE
[iOS] Support Custom Views for Data Input

### ISSUE THREAD

**Issue by idibidiart** [facebook/react-native#3274]
I need to implement a custom-styled numeric keyboard that is basically a set of touchable views (the number keys) that would send their value (or a delete-from-current-position instruction for the delete key) to the TextInput where the user should be able to position the cursor by hand when editing the entered value.

Problem is when TextInput is in focus the iOS keyboard will slide up. 

I would like to avoid wrapping the iOS keyboard and making it customizable from React Native as that seems like a lot of work to someone who's just starting to use Objective-C and it may be something the React Native team or some advanced user could take on? For my use case, it would be awesome if there was a way for the TextInput to have focus/cursor but not bring up the native keyboard.

I tried wrapping TextInput in a View and use onStartShouldSetResponderCapture with a handler that returns `true` but that had the funny effect of preventing input from the native keyboard, as opposed to preventing the native keyboard from activating on touching the textInput.

I apologize if there is a known solution to this and I just couldn't find it. I am thinking that we need a new feature in TextInput like having a property e.g. disableKeyboard={true}

**Comment by ide** [comment]
I believe you can't render a cursor and prevent the keyboard from showing up. We could consider adding support for it if you have a small UIKit demo that achieves this without crazy hacks.

**Comment by chirag04** [comment]
Heres one crazy idea:  Use a ``<Text>`` component instead of TextInput. listen for onFous of Text to show your keyboard Add border around ``Text`` to make it look like a TextInput. Adding cursor would be crazy like this though.

**Comment by ide** [comment]
I think a cursor wouldn't be too bad to implement if it's non-interactive. By that I mean you would not support moving the cursor around and instead would render a blinking View at the end of your Text.

**Comment by idibidiart** [comment]
@Ide yes, I'm starting from here:

https://developer.apple.com/library/ios/documentation/StringsTextFonts/Conceptual/TextAndWebiPhoneOS/InputViews/InputViews.html#//apple_ref/doc/uid/TP40009542-CH12
 
React Native needs a way for developers to build keyboards with specific functionality and custom style to enhance their apps. 

@ide that was and remains my fallback option (re: faking cursor and using Text box) but native behavior of cursor during editing is something that is really needed for native UX

**Comment by ide** [comment]
I get that, though I believe that truly native means always displaying the keyboard when a text field is focused unless a hardware keyboard is attached. RN exposes most of the keyboard configuration properties that are available. If there is something not yet exposed, it's especially helpful if you can point out the corresponding API calls in the iOS/Android docs or describe a small code sample for features that aren't as simple as calling one function.

**Comment by ide** [comment]
@idibidiart are you referring to the `inputView` property?

**Comment by idibidiart** [comment]
Originally, I asked about preventing the keyboard from showing up only because I thought I needed to build a custom keyboard as a React component -- as a table of RN views (each being a number key, plus `delete` and `.`)   

But then I realized that I needed to find a way to provide a custom input view for TextInput.

So yes I believe inputView (or whatever property refers to the custom keyboard view we want to use for the input element) would have to be a property on TextInput so we could specify a custom React component as our keyboard. 

I couldn't find any such property on TextInput, at least as far as the docs go.

**Comment by idibidiart** [comment]
Update:

I read a little more about custom views for the system keyboard and it looks like this is something I could set up in the App Delegate and it would modify the keyboard view for the whole app.

So I'm closing this (unless someone disagrees with the above conclusion.)

Sorry for any distraction. Will research stuff more in the future. :/

@ide ^^
