### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by awerudev** [facebook/react-native#32741]
### Description

I have tried to build the React Native project in Xcode 13.1, but getting the following error.
Checked the several answers, but nothing helped me.

### Version

0.65.1

### Output of `react-native info`

![TrueLuck xcworkspace 2021-12-12 10-56-06](https://user-images.githubusercontent.com/22884168/145719503-0114a1ce-1ed4-4e21-90ef-da39f08431bf.png)

### Steps to reproduce

> npx yarn install
> cd ios
> pod install
> npx react-native run-ios --simulator="iPhone 11"

**Comment by Siliconvelly** [comment]
I think i got the solution for it is:
where your project stored containing folder not having space (whitespace) or any special character also if possible make it in home or admin dir also the path of the project dir should not contains any special character or space in folder name

**Comment by oleksiizhuk** [comment]
i have the same problem

**Comment by bozaigao** [comment]
My computer has an M1 chip，I tried everything. The most important changes are as follows:
nvm unalias default
nvm alias default node
