### ISSUE TITLE
Can not download template with npx react-native init when creating a new app

### ISSUE THREAD

**Issue by tiavina-mika** [facebook/react-native#32743]
### Description

I've install the environment described here: https://reactnative.dev/docs/environment-setup

but when I run npx react-native init AwesomeTSProject --template react-native-template-typescript I got this error:
```
✖ Downloading template
error Error: Command failed: yarn init -y
warning The yes flag has been set. This will automatically answer yes to all questions, which may have security implications.
warning ..\..\..\..\package.json: No license field
error An unexpected error occurred: "Cannot create property 'org' on string ''".
yarn init v1.22.17
info If you think this is a bug, please open a bug report with the information provided in "C:\\Users\\ASUS\\AppData\\Local\\Temp\\rncli-init-template-ncXdhF\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/init for documentation about this command.
```

### Version

6.3.1

### Output of `react-native info`

System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz
    Memory: 4.49 GB / 15.95 GB
  Binaries:
    Node: 14.15.4 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.20.1 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 27, 28, 29
      Build Tools: 28.0.3, 29.0.3, 32.0.0
      System Images: android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7935034
    Visual Studio: Not Found
  Languages:
    Java: 11.0.2 - C:\Users\ASUS\AppData\Local\jdk-11.0.2\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

- run: `npx react-native init AwesomeTSProject --template react-native-template-typescript`, it only create an empty directory "AwesomeTSProject"

**Comment by metalfingers** [comment]
Same issue. If I wait long enough, I'll see this error:
`error Error: Failed to install CocoaPods dependencies for iOS project, which is required by this template.
Please try again manually: "cd ./AwesomeTSProject/ios && pod install".`

Looks like there's a missing cocopod called Boost. After ding a `pod install`, I get thanother error:
```
[!] Error installing boost
[!] /Users/<MY_USER>/anaconda3/bin/curl -f -L -o /var/folders/08/b96tq0t13ll6hc1zmnjtq6pm0000gp/T/d20211215-22324-n3tyda/file.tbz https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.bz2 --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.11.2 cocoapods-downloader/1.5.1'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  1  104M    1 1749k    0     0   3529      0  8:39:51  0:08:27  8:31:24     0
curl: (56) OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 54
```

**Comment by alexindigo** [comment]
Same here. RN version 6.3.1.
And `react-native info` doesn't work:

```
$ npx react-native info
error Unrecognized command "info".
info Run "react-native --help" to see a list of all available commands.
```

**Comment by cortinico** [comment]
@tiavina-mika You should ideally open an issue on https://github.com/react-native-community/react-native-template-typescript/ as it seems like it's a problem related to that specific template.

Closing as I believe is not directly related to RN, but feel free to reopen if this is not the case.

> And react-native info doesn't work:

@alexindigo That's unrelated to this problem, but you're most likely running an older version of react-native that you installed globally. You can check it with: `npm info react-native version`
