### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'InnerNativeModule.installCoreFunctions')

### ISSUE THREAD

**Issue by Wellers0n** [facebook/react-native#32758]
### Description

This error only happens on Android 

<img width="1377" alt="Screen Shot 2021-12-14 at 16 34 59" src="https://user-images.githubusercontent.com/39449389/146067151-411c67ca-00ef-4c55-9bbf-8d28456f2d83.png">

![Screen Shot 2021-12-14 at 16 35 54](https://user-images.githubusercontent.com/39449389/146067291-286f3d51-df0f-4d27-a555-c82d99e45aad.png)

### Version

0.66.3

### Output of `react-native info`

 ERROR  TypeError: undefined is not an object (evaluating 'InnerNativeModule.installCoreFunctions')

 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.

 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.

### Steps to reproduce

I installed react navigation (stack and drawer)

I following this documentation: [link](https://reactnavigation.org/docs/getting-started/)

## Install

`yarn add @react-navigation/native`

`yarn add react-native-screens react-native-safe-area-context`

`yarn add @react-navigation/drawer`

`yarn add react-native-gesture-handler react-native-reanimated`

---

## Import and config

I putting this import in index.js `import 'react-native-gesture-handler';`

and I did this config in `MainActivity.java`

add this method 
```java 
@Override
protected void onCreate(Bundle savedInstanceState) {
  super.onCreate(null);
}
```

and this import in MainActivity.java: `import android.os.Bundle;`

**Comment by Wellers0n** [comment]
this issue helped me https://github.com/software-mansion/react-native-reanimated/issues/846#issuecomment-943267584

**Comment by algoace123** [comment]
Whats the solution?

**Comment by musaatalay1** [comment]
> Whats the solution?

Try this: https://github.com/software-mansion/react-native-reanimated/issues/846#issuecomment-943267584

**Comment by DevHamzaShahid** [comment]
> this issue helped me [software-mansion/react-native-reanimated#846 (comment)](https://github.com/software-mansion/react-native-reanimated/issues/846#issuecomment-943267584)

thanks it help me alot , i spent a whole day finding that error then i read your comment, thanks alot

**Comment by AppDevloper23** [comment]
this worked ofr me
https://stackoverflow.com/questions/70968067/typeerror-undefined-is-not-an-object-evaluating-innernativemodule-installcore
