### ISSUE TITLE
[Android] OnLoad.cpp does not compile on master

### ISSUE THREAD

**Issue by arbesfeld** [facebook/react-native#3276]
[OnLoad.cpp](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/jni/react/jni/OnLoad.cpp) references "ReadableNativeArray.h" which is not on the master tree.

@mikearmstrong001

**Comment by ox7** [comment]
./OnLoad.cpp:17:33: fatal error: ReadableNativeArray.h: No such file or directory

**Comment by luisbebop** [comment]
+1

**Comment by chirag04** [comment]
+1

**Comment by mikearmstrong001** [comment]
Thank you will investigate

**Comment by mikearmstrong001** [comment]
Thanks again for the quick issues. we've determined why this file didn't sync through. I'll leave you to close when the file is in master

**Comment by chirag04** [comment]
:+1: desperately waiting for the file to sync. need to test build from source.

**Comment by fengcunhan** [comment]
+1

**Comment by southerneer** [comment]
+1

**Comment by mikearmstrong001** [comment]
Still waiting on getting it through, can only apologise

**Comment by ide** [comment]
This was added in https://github.com/facebook/react-native/commit/fffae394c79e312c56aa7850cd4b8096d593d224. Closing this out. Thanks @mikearmstrong001.
