### ISSUE TITLE
Error while updating property 'source' of a view managed by: FastImageView

### ISSUE THREAD

**Issue by kanghari78** [facebook/react-native#32767]
### Description

![2번오류](https://user-images.githubusercontent.com/71427773/146218530-43b39ed3-0622-444b-a5b7-3cd4f28b5f03.jpg)

reacr native앱에서 로그인 진행 시 galaxy fold에서 접거나 펼칠 때 발생하고 있습니다.

### Version

android 11

### Output of `react-native info`

12-15 19:11:17.950: E/Adjust(7523): Adjust already initialized
12-15 19:11:17.957: E/[MCF_DS]_HandoffProvider(10108): call - HandoffHandler is not started.
12-15 19:11:18.062: E/unknown:ViewManager(7523): Error while updating prop source
12-15 19:11:18.062: E/unknown:ViewManager(7523): java.lang.reflect.InvocationTargetException
12-15 19:11:18.062: E/unknown:ViewManager(7523): 	at java.lang.reflect.Method.invoke(Native Method)
12-15 19:11:18.062: E/unknown:ViewManager(7523): 	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:87)
12-15 19:11:18.062: E/unknown:ViewManager(7523): 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:136)
12-15 19:11:18.062: E/unknown:ViewManager(7523): 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:56)
12-15 19:11:18.062: E/unknown:ViewManager(7523): 	at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:49)
12-15 19:11:18.062: E/unknown:ViewManager(7523): 	at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:290)
12-15 19:11:18.062: E/unknown:ViewManager(7523): 	at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:188)
12-15 19:11:18.062: E/unknown:ViewManager(7523): 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1103)
12-15 19:11:18.062: E/unknown:ViewManager(7523): 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1074)
12-15 19:11:18.062: E/unknown:ViewManager(7523): 	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
12-15 19:11:18.062: E/unknown:ViewManager(7523): 	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
12-15 19:11:18.062: E/unknown:ViewManager(7523): 	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
12-15 19:11:18.062: E/unknown:ViewManager(7523): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1008)
12-15 19:11:18.062: E/unknown:ViewManager(7523): 	at android.view.Choreographer.doCallbacks(Choreographer.java:809)
12-15 19:11:18.062: E/unknown:ViewManager(7523): 	at android.view.Choreographer.doFrame(Choreographer.java:740)
12-15 19:11:18.062: E/unknown:ViewManager(7523): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
12-15 19:11:18.062: E/unknown:ViewManager(7523): 	at android.os.Handler.handleCallback(Handler.java:938)
12-15 19:11:18.062: E/unknown:ViewManager(7523): 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-15 19:11:18.062: E/unknown:ViewManager(7523): 	at android.os.Looper.loop(Looper.java:247)
12-15 19:11:18.062: E/unknown:ViewManager(7523): 	at android.app.ActivityThread.main(ActivityThread.java:8656)
12-15 19:11:18.062: E/unknown:ViewManager(7523): 	at java.lang.reflect.Method.invoke(Native Method)
12-15 19:11:18.062: E/unknown:ViewManager(7523): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
12-15 19:11:18.062: E/unknown:ViewManager(7523): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
12-15 19:11:18.062: E/unknown:ViewManager(7523): Caused by: java.lang.IllegalArgumentException: Must not be null or empty
12-15 19:11:18.062: E/unknown:ViewManager(7523): 	at com.bumptech.glide.util.Preconditions.checkNotEmpty(Preconditions.java:37)
12-15 19:11:18.062: E/unknown:ViewManager(7523): 	at com.bumptech.glide.load.model.GlideUrl.<init>(GlideUrl.java:56)
12-15 19:11:18.062: E/unknown:ViewManager(7523): 	at com.dylanvann.fastimage.FastImageSource.getGlideUrl(FastImageSource.java:110)
12-15 19:11:18.062: E/unknown:ViewManager(7523): 	at com.dylanvann.fastimage.FastImageViewManager.setSrc(FastImageViewManager.java:75)
12-15 19:11:18.062: E/unknown:ViewManager(7523): 	... 23 more
12-15 19:11:18.063: E/unknown:ReactNative(7523): Exception in native call
12-15 19:11:18.063: E/unknown:ReactNative(7523): com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'source' of a view managed by: FastImageView
12-15 19:11:18.063: E/unknown:ReactNative(7523): 	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:102)
12-15 19:11:18.063: E/unknown:ReactNative(7523): 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:136)
12-15 19:11:18.063: E/unknown:ReactNative(7523): 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:56)
12-15 19:11:18.063: E/unknown:ReactNative(7523): 	at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:49)
12-15 19:11:18.063: E/unknown:ReactNative(7523): 	at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:290)
12-15 19:11:18.063: E/unknown:ReactNative(7523): 	at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:188)
12-15 19:11:18.063: E/unknown:ReactNative(7523): 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1103)
12-15 19:11:18.063: E/unknown:ReactNative(7523): 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1074)
12-15 19:11:18.063: E/unknown:ReactNative(7523): 	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
12-15 19:11:18.063: E/unknown:ReactNative(7523): 	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
12-15 19:11:18.063: E/unknown:ReactNative(7523): 	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
12-15 19:11:18.063: E/unknown:ReactNative(7523): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1008)
12-15 19:11:18.063: E/unknown:ReactNative(7523): 	at android.view.Choreographer.doCallbacks(Choreographer.java:809)
12-15 19:11:18.063: E/unknown:ReactNative(7523): 	at android.view.Choreographer.doFrame(Choreographer.java:740)
12-15 19:11:18.063: E/unknown:ReactNative(7523): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
12-15 19:11:18.063: E/unknown:ReactNative(7523): 	at android.os.Handler.handleCallback(Handler.java:938)
12-15 19:11:18.063: E/unknown:ReactNative(7523): 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-15 19:11:18.063: E/unknown:ReactNative(7523): 	at android.os.Looper.loop(Looper.java:247)
12-15 19:11:18.063: E/unknown:ReactNative(7523): 	at android.app.ActivityThread.main(ActivityThread.java:8656)
12-15 19:11:18.063: E/unknown:ReactNative(7523): 	at java.lang.reflect.Method.invoke(Native Method)
12-15 19:11:18.063: E/unknown:ReactNative(7523): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
12-15 19:11:18.063: E/unknown:ReactNative(7523): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
12-15 19:11:18.063: E/unknown:ReactNative(7523): Caused by: java.lang.reflect.InvocationTargetException
12-15 19:11:18.063: E/unknown:ReactNative(7523): 	at java.lang.reflect.Method.invoke(Native Method)
12-15 19:11:18.063: E/unknown:ReactNative(7523): 	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:87)
12-15 19:11:18.063: E/unknown:ReactNative(7523): 	... 21 more
12-15 19:11:18.063: E/unknown:ReactNative(7523): Caused by: java.lang.IllegalArgumentException: Must not be null or empty
12-15 19:11:18.063: E/unknown:ReactNative(7523): 	at com.bumptech.glide.util.Preconditions.checkNotEmpty(Preconditions.java:37)
12-15 19:11:18.063: E/unknown:ReactNative(7523): 	at com.bumptech.glide.load.model.GlideUrl.<init>(GlideUrl.java:56)
12-15 19:11:18.063: E/unknown:ReactNative(7523): 	at com.dylanvann.fastimage.FastImageSource.getGlideUrl(FastImageSource.java:110)
12-15 19:11:18.063: E/unknown:ReactNative(7523): 	at com.dylanvann.fastimage.FastImageViewManager.setSrc(FastImageViewManager.java:75)
12-15 19:11:18.063: E/unknown:ReactNative(7523): 	... 23 more
12-15 19:11:18.064: E/Netd(791): getNetworkForDns: getNetId from enterpriseCtrl is netid 0
12-15 19:11:18.079: E/AppsEdge.Theme(6687): Attempt to invoke virtual method 'java.lang.String java.lang.String.concat(java.lang.String)' on a null object reference
12-15 19:11:18.136: E/WallpaperEventNotifier(2029): registerCallback: Object tried to add another callback com.android.systemui.wallpaper.WallpaperEventNotifier.registerCallback:236
12-15 19:11:18.136: E/WallpaperEventNotifier(2029): registerCallback: Object tried to add another callback com.android.systemui.wallpaper.WallpaperEventNotifier.registerCallback:236
12-15 19:11:18.180: E/SharedPreferencesImpl(6687): Couldn't create directory for SharedPreferences file /data/user/0/com.samsung.android.app.appsedge/shared_prefs/themePreference.xml
12-15 19:11:18.206: E/CocktailBarContainerView(6687): updateContainerVisibility: 
12-15 19:11:18.213: E/Netd(791): getNetworkForDns: getNetId from enterpriseCtrl is netid 0
12-15 19:11:18.268: E/AbstractCocktailPanelView(6687): notifyPanelVisibilityChanged: cocktail already destroyed 2com.samsung.android.app.cocktailbarservice.ui.panel.CocktailPortraitRemotePanelView{7449762 V.E...... ......ID 0,0-414,265}
12-15 19:11:18.378: E/Netd(791): getNetworkForDns: getNetId from enterpriseCtrl is netid 0
12-15 19:11:19.550: E/Netd(791): getNetworkForDns: getNetId from enterpriseCtrl is netid 0
12-15 19:11:19.553: E/Netd(791): getNetworkForDns: getNetId from enterpriseCtrl is netid 0
12-15 19:11:19.680: E/Netd(791): getNetworkForDns: getNetId from enterpriseCtrl is netid 0
12-15 19:11:19.686: E/Netd(791): getNetworkForDns: getNetId from enterpriseCtrl is netid 0
12-15 19:11:19.949: E/Netd(791): getNetworkForDns: getNetId from enterpriseCtrl is netid 0
12-15 19:11:20.949: E/anychat.lamp.g(7523): Invalid ID 0x00000000.
12-15 19:11:20.951: E/ReactNative(7523): [CodePush] Exception
12-15 19:11:20.951: E/ReactNative(7523): com.microsoft.codepush.react.CodePushUnknownException: Error in getting binary resources modified time
12-15 19:11:20.951: E/ReactNative(7523): 	at com.microsoft.codepush.react.CodePush.getBinaryResourcesModifiedTime(CodePush.java:207)
12-15 19:11:20.951: E/ReactNative(7523): 	at com.microsoft.codepush.react.CodePushNativeModule$3.doInBackground(CodePushNativeModule.java:289)
12-15 19:11:20.951: E/ReactNative(7523): 	at com.microsoft.codepush.react.CodePushNativeModule$3.doInBackground(CodePushNativeModule.java:284)
12-15 19:11:20.951: E/ReactNative(7523): 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
12-15 19:11:20.951: E/ReactNative(7523): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
12-15 19:11:20.951: E/ReactNative(7523): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-15 19:11:20.951: E/ReactNative(7523): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-15 19:11:20.951: E/ReactNative(7523): 	at java.lang.Thread.run(Thread.java:923)
12-15 19:11:20.951: E/ReactNative(7523): Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x0
12-15 19:11:20.951: E/ReactNative(7523): 	at android.content.res.Resources.getText(Resources.java:512)
12-15 19:11:20.951: E/ReactNative(7523): 	at android.content.res.Resources.getString(Resources.java:605)
12-15 19:11:20.951: E/ReactNative(7523): 	at com.microsoft.codepush.react.CodePush.getBinaryResourcesModifiedTime(CodePush.java:204)
12-15 19:11:20.951: E/ReactNative(7523): 	... 7 more
12-15 19:11:21.559: E/Netd(791): getNetworkForDns: getNetId from enterpriseCtrl is netid 0
12-15 19:11:21.563: E/Netd(791): getNetworkForDns: getNetId from enterpriseCtrl is netid 0
12-15 19:11:21.703: E/Netd(791): getNetworkForDns: getNetId from enterpriseCtrl is netid 0
12-15 19:11:21.707: E/Netd(791): getNetworkForDns: getNetId from enterpriseCtrl is netid 0

### Steps to reproduce

1. 로그인 / 회원가입 화면
2. galaxy fold를 접거나 펼 때
3. 오류발생(로그인 후에는 발생하지 않습니다.)

**Comment by gilsonviana-modus** [comment]
This an issue with the fast-image package itself. My workaround this was creating an image component wrapper that will fallback to a placeholder in case fastimage failed to load the source image. So you would have to play with the ‘onError’ property.

**Comment by tmorganPDC** [comment]
Snack shack...@![image](https://user-images.githubusercontent.com/75138753/146641078-1b0a156a-8dfd-4c68-a48b-3c439d9ee1dd.png)
