### ISSUE TITLE
DoubleConversion latest version upgradation.

### ISSUE THREAD

**Issue by Mob-Dev-2** [facebook/react-native#32773]
### Description

The react-native's latest version 0.66 uses 1.1.6 DoubleConversion version where as the latest DoubleConversion version is 3.1.6. Is there any plan of upgrading to latest double conversion version.

### Version

0.65.1 

### Output of `react-native info`

System:
    OS: macOS 12.0.1
    CPU: (8) x64 Apple M1
    Memory: 32.21 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.5 - /usr/local/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 6.14.14 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_131 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.65.1 => 0.65.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

In double conversion podspec the version is 1.1.6

**Comment by cortinico** [comment]
> The react-native's latest version 0.66 uses 1.1.6 DoubleConversion version where as the latest DoubleConversion version is 3.1.6. Is there any plan of upgrading to latest double conversion version.

Closing as this is a question.

To answer you: no. There are no immediate plans in bumping this dependency, unless there is a valid use case or a security patch that requires a bump.
