### ISSUE TITLE
ExceptionsManagerModule.java line 83 com.facebook.react.modules.core.ExceptionsManagerModule.reportException

### ISSUE THREAD

**Issue by TeamKiko** [facebook/react-native#32778]
### Description

Hi,

In Android the app randomly crashing with the following error being caught by firebase Crashlytics

ExceptionsManagerModule.java line 83
com.facebook.react.modules.core.ExceptionsManagerModule.reportException

Fatal Exception: com.facebook.react.common.JavascriptException
TypeError: undefined is not an object (evaluating 'o.length'), stack: validate@3959:1786 onPress@3959:5380 value@212:7691 value@212:6947 onResponderRelease@212:5668 f@91:184 v@91:327 y@91:381 k@91:676 Ce@91:13197 forEach@-1 Y@91:5349 <unknown>@91:13545 xe@91:92704 Re@91:12995 ze@91:13384 receiveTouches@91:14177 value@42:3492 <unknown>@42:747 value@42:2538 value@42:719 value@-1

React Native version:
0.64.0
React Native Firebase library version:
12.1.0

### Version

0.64.0

### Output of `react-native info`

Fatal Exception: com.facebook.react.common.JavascriptException
TypeError: undefined is not an object (evaluating 'o.length'), stack: validate@3959:1786 onPress@3959:5380 value@212:7691 value@212:6947 onResponderRelease@212:5668 f@91:184 v@91:327 y@91:381 k@91:676 Ce@91:13197 forEach@-1 Y@91:5349 <unknown>@91:13545 xe@91:92704 Re@91:12995 ze@91:13384 receiveTouches@91:14177 value@42:3492 <unknown>@42:747 value@42:2538 value@42:719 value@-1

### Steps to reproduce

Got it in Firebase Crashlytics.

**Comment by govind1530** [comment]
any soultion?

**Comment by khichis** [comment]
Any solution so far?

**Comment by daheeahn** [comment]
any solution?

**Comment by Deep-CB** [comment]
I am facing the same issue
Any solution for this ?
![Screen Shot 2022-01-27 at 1 18 32 pm](https://user-images.githubusercontent.com/73906746/151314408-db14b1e9-3859-4951-9273-059d0d915770.png)

**Comment by ellysmoore** [comment]
Anyone find a solution yet ?

**Comment by lailton-b** [comment]
I am facing the same issue after updating react-native from 0.62.0 to 0.65.0

**Comment by Mindbowser** [comment]
Any updates here? Did anyone found any workaround?

**Comment by gautam-ndk** [comment]
Is there any update on this issue? We started seeing this error even without any recent updates to react-native. Any pointers here will be appreciated!

**Comment by dieptang** [comment]
Same here!

**Comment by anasalsaadi14** [comment]
Same here!

**Comment by RaviDhakadDoodle** [comment]
Same here!

**Comment by shatas** [comment]
Any news on this topic?

**Comment by admin0319** [comment]
Same here! using react-native 0.66

**Comment by nimeshpoudel7** [comment]
IS THIS ISSUE SOLVED?

**Comment by ShubhamBathe-KM** [comment]
Any updates on the issue. My app is getting a lot of crashes on production because of this bug. Someone please provide any solution to the problem. Thanks.

<img width="1147" alt="Screenshot 2022-04-27 at 7 25 03 PM" src="https://user-images.githubusercontent.com/67695272/165535850-7ad66867-4776-4467-9571-5228c468cc98.png">

**Comment by raquel-nobre** [comment]
Any updates on the issue?

**Comment by kiennd-miichisoft** [comment]
I also got the same error

**Comment by ShubhamBathe-KM** [comment]
Hello guys, this isn't a react native issue. This exception usually occurs because of some third party npm packages that we use in our project. In my case it was due to this package:- 

**react-native-otp-verify**

I removed the package from my project and this fixed my issue. My crash count significantly decreased after this. So I will suggest you to figure out which npm causing the issue in your case. If it's not because of any third party npm package, it might be due to some unhandled null pointer in your code base.

Hope this helps.

**Comment by nmanvitha** [comment]
I also got the same error. Any updates on this issue?

**Comment by RaviDhakadDoodle** [comment]
I also got the same issue.
ExceptionsManagerModule.java line 83
com.facebook.react.modules.core.ExceptionsManagerModule.reportException 

Any updates on this issue?

**Comment by govarthananve** [comment]
I am also getting this error

ExceptionsManagerModule.java line 83
com.facebook.react.modules.core.ExceptionsManagerModule.reportException

Logs also not showing properly 

Fatal Exception: com.facebook.react.common.c
TypeError: s is not a function. (In 's()', 's' is undefined), stack: onPress@1105.js:1:15506 value@191.js:1:7704 value@191.js:1:6960 onResponderRelease@191.js:1:5675 o@77.js:1:150 h@77.js:1:293 g@77.js:1:347 b@77.js:1:642 xe@77.js:1:13181 forEach@-1 H@77.js:1:5333 <unknown>@77.js:1:13529 ke@77.js:1:93290 _e@77.js:1:12979 Re@77.js:1:13368 receiveTouches@77.js:1:14167 value@41.js:1:3469 <unknown>@41.js:1:662 value@41.js:1:2459 value@41.js:1:634 value@-1

"react-native": "0.64.2"

Any update on this?

**Comment by MMasterson** [comment]
oh look, it's not just me...

seeing this issue as well. Any update?

**Comment by tuliosciotta** [comment]
Same here...

**Comment by Gajendra-Gupta** [comment]
I am getting same issue. Do you have any update about it.

**Comment by ali-soltanii** [comment]
Disable the proguard and see if it works.
We had this issue too. I disabled the proguard and now we don't have this issue anymore
Some 3rd party libraries don't support proguard.

**Comment by Robiullah2244** [comment]
I am facing the same issue. Any solution?

**Comment by princeKasodariya** [comment]
also got the same issue.

ExceptionsManagerModule.java line 83
com.facebook.react.modules.core.ExceptionsManagerModule.reportException

react-native 0.64.2
Any updates on this issue?

**Comment by Phector27** [comment]
Same here on 0.64.3 RN --v

Play console shows this error not debuggeable in app on some devices (not all):

```
Exception com.facebook.react.common.JavascriptException:
  at com.facebook.react.modules.core.ExceptionsManagerModule.reportException (ExceptionsManagerModule.java:83)
  at java.lang.reflect.Method.invoke
  at com.facebook.react.bridge.JavaMethodWrapper.invoke (JavaMethodWrapper.java:372)
  at com.facebook.react.bridge.JavaModuleWrapper.invoke (JavaModuleWrapper.java:151)
  at com.facebook.react.bridge.queue.NativeRunnable.run
  at android.os.Handler.handleCallback (Handler.java:938)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage (MessageQueueThreadHandler.java:27)
  at android.os.Looper.loopOnce (Looper.java:210)
  at android.os.Looper.loop (Looper.java:299)
  at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run (MessageQueueThreadImpl.java:226)
  at java.lang.Thread.run (Thread.java:1012)
```

**Comment by iranaahsanali** [comment]
I am facing same issue.
