### ISSUE TITLE
Android Text components do not ellipsize when height-constrained

### ISSUE THREAD

**Issue by TheAlmightyBob** [facebook/react-native#32771]
### Description

If the amount of text in a Text component exceeds the `numberOfLines` property and `ellipsizeMode` is set, it will be ellipsized as expected on iOS on Android.

On iOS, if the the height of the component does not allow the text to fit the specified `numberOfLines`, it will only display as many lines as can fit and ellipsize properly.

![image](https://user-images.githubusercontent.com/7707864/146295415-2d65273f-43f5-42f6-a925-74e0a7e194f2.png)

On Android, however, it will ignore the height of the component.

![image](https://user-images.githubusercontent.com/7707864/146295494-d99375a2-34a9-488f-9efb-ab490941bc12.png)

(`numberOfLines` is set to `3` in this example)

(the `adjustsFontSizeToFit` feature _does_ respect the component height... but ellipsizing does not)

(while this example may seem a bit contrived, this is very easy to run into with users changing font sizes on their devices)

### Version

0.63.4 - 0.64.3 (the latest supported by Expo Snack at this time)

### Output of `react-native info`

System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 331.92 MB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 17.0.1 - /var/folders/z5/t5b4f6k55bn7jh37yv_2581w0000gp/T/yarn--1639621319313-0.8783069057767894/node
    Yarn: 1.22.17 - /var/folders/z5/t5b4f6k55bn7jh37yv_2581w0000gp/T/yarn--1639621319313-0.8783069057767894/yarn
    npm: 8.1.0 - /usr/local/bin/npm
    Watchman: 2021.10.18.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 31.0.0
      System Images: android-27 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7199119
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_242-release - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Create a Text component with a lot of text, set `numberOfLines` to >1 and `ellipsizeMode` to `tail`, place it in an outer `View` with `maxHeight` set to fit less then the specified `numberOfLines`.
(or just check out the Snack)

When run on iOS, the text will have a tailing ellipsis. On Android it will not.

### Snack, code example, screenshot, or link to a repository

https://snack.expo.dev/zCq-Iv9Yd

**Comment by Zmwang622** [comment]
I have this issue as well

**Comment by TheAlmightyBob** [comment]
@Zmwang622 Unfortunately not. This is still a bug for us.

**Comment by LudoLamerre** [comment]
Always an issue on RN 0.70.5. No one has come up with a solution for this rather restrictive problem?
