### ISSUE TITLE
Transparent Image in Text component has white background

### ISSUE THREAD

**Issue by vladinko0** [facebook/react-native#32780]
### Description

I have problem with displaying image in Text component.

As you can see in the picture below, top image is placed in Text component and below is outside it.

### Version

0.61.2

### Output of `react-native info`

System:
    OS: macOS 12.0.1
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 127.22 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.0.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.10.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.3
      System Images: android-28 | Android TV Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7199119
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild

### Steps to reproduce

I am using this code:
```
<Text style={{ fontSize: 24 }}>
    <Image
        source={{ uri: "https://someaddress...png" }}
        style={{ width: 180, height: 180 }}
    />
</Text>

<Image source={{ uri: "https://someaddress...png" }}
    style={{ width: 180, height: 180, top: 100 }}
/>
```

I have this issue on iPhone XR (15.0). Is there any solution, how to display image in Text correctly?

### Snack, code example, screenshot, or link to a repository

![Snímka obrazovky 2021-12-17 o 14 14 05](https://user-images.githubusercontent.com/16008547/146567603-0bdc5d20-f51a-4e44-9a75-1a10da16d4c7.png)

**Comment by gilsonviana-modus** [comment]
I have successfully add a .svg icon as a text children. I’m not sure about images. Can you convert this image and use it as an icon instead?

**Comment by vladinko0** [comment]
Unfortunately, I am not able to change image to .svg, it is coming from CMS.
