### ISSUE TITLE
 onViewableItemsChanged in flatlist don't working when item 3 =>4, 6=>7 ..... android

### ISSUE THREAD

**Issue by vuongmt2000** [facebook/react-native#32785]
### Description

i use onViewableItemsChanged in flatlist and don't working when item 3 =>4, 6=>7 ..... android

### Version

0.66.3

### Output of `react-native info`

when I swipe to item 4 onViewableItemsChanged don't working

### Steps to reproduce

  const onViewRef = React.useRef((viewableItems) => {
    console.log(viewableItems)
    setIndexView(viewableItems.viewableItems[0].index)
  })

return ...
<FlatList
          data={data}
          horizontal
          onViewableItemsChanged={onViewRef.current}
          showsHorizontalScrollIndicator={false}
          onScroll={Animated.event(
            [{ nativeEvent: { contentOffset: { x: animatedValue } } }],
            { useNativeDriver: false },
          )
          }
          pagingEnabled={true}
          keyExtractor={(_, index) => index.toString()}
          renderItem={renderItem}
        />

**Comment by oimolab** [comment]
I got same problem and could solve by changing view width from odd numbers(295px) to even numbers(296px). I found this problem happened on only android API 23 and 26. But on API 30, it worked. I guess depending on the API version, layout calculation is little bit different and the only 1px prevented the recognition of scroll finish.
I'm not sure this can be help for you, but hope good luck.

**Comment by vuongmt2000** [comment]
but I am not using android api 23 or 26. I am using android api 28 29 30.

**Comment by vuongmt2000** [comment]
moreover I tried changing view then item were overflow view

**Comment by oimolab** [comment]
FlatList need to be wrapped by view. The views I changed were both inner view and outer view.

**Comment by vuongmt2000** [comment]
oke thanks bro
