### ISSUE TITLE
Android Custom View causes cast errors

### ISSUE THREAD

**Issue by TAMHAN** [facebook/react-native#3278]
Hello,
please permit me to report an oddity. I am trying to wrap a button as an example, but it simply does not work. First of all, the code of the button class:

```
public class ButtonClass extends SimpleViewManager<Button>{
    @UIProp(UIProp.Type.STRING)
    public static final String DENGBRODENGDENG = "dengbro";

    @Override
    public String getName() {

        return "HeiseButton";
    }

    @Override
    protected Button createViewInstance(ThemedReactContext reactContext) {
        //ViewGroupManager<LinearLayout> myLayoutMater;
        //LinearLayout myLayout=new LinearLayout(reactContext);
        Button newButton= new Button(reactContext);
        newButton.setMinimumHeight(150);
        newButton.setMinimumWidth(400);
        newButton.setText("Hallo React!");
        //myLayout.addView(newButton);
        return newButton;
    }
}
```
Sadly, running this on Android leads to an error of the type android.widget.Button cannot be cast to android.view.ViewGroup, which is emitted from manageChildren line 262 in NativeViewHierarchyManager. Changing ButtonClass to return a LinearLayout, instrad, leads to an error on line 263.

I already added all kinds of properties to the JavaScript, which looks like this:
```js
var iface = { 
	name: 'HBTNView',
	propTypes:{dengbro:"brodengdeng"}
};
var HeiseButton=React.requireNativeComponent("HeiseButton",iface);
var HeiseSample = React.createClass({
  render: function() {
    return (
      <View style={styles.container}>
        <HeiseButton>Muss Da Sein!</HeiseButton>
      </View>
    );
  }
});
```
Please let me know if you need further info re the issue at hand.

All the best
Tam

**Comment by TAMHAN** [comment]
Update: This version works
```
var HeiseButton=React.requireNativeComponent("HeiseButton",null);
var HeiseSample = React.createClass({
  render: function() {
    return (
    	<View style={{flexDirection: 'row', height: 100, padding: 20}}>
    	<HeiseButton style={{ flex: 0.3}}/> 
    	</View>
    
      
    );
  }
});
```

**Comment by mikearmstrong001** [comment]
You would need to pass the text in as an attribute. 
With your first version the JSX transform would expand the text to a createElement, a child of HeiseButton. However HeiseButton does not support child views as it does not inherit from a native ViewGroup

**Comment by TAMHAN** [comment]
Hello,
big thanks for your help!

Tam
