### ISSUE TITLE
www.react-native.cn assets not found

### ISSUE THREAD

**Issue by RedContritio** [facebook/react-native#32791]
### Description

when I visit [React Native 中文网](https://www.react-native.cn/docs/getting-started), it show incorrect styles and some assets not found.
Including these:
https://www.react-native.cn/docs/assets/css/styles.f1cae8c4.css
https://www.react-native.cn/docs/assets/js/runtime~main.a68af0f2.js
https://www.react-native.cn/docs/assets/js/main.8cbc7157.js
https://api.amplitude.com/

and others.

When I visited them, they told me:
> Page Not Found
We could not find what you were looking for.
> 
> Please contact the owner of the site that linked you to the original URL and let them know their link is broken.

So I think maybe that it's a shall way to report it here.

### Version

None

### Output of `npx react-native info`

None

### Steps to reproduce

Visit [React Native CN](https://www.react-native.cn/docs/getting-started)

**Comment by likeSo** [comment]
React Native CN is not an official website of RN.
React Native 中文网不是RN的官方中文网站，它有自己的GitHub。

Hope React Team can attach importance to the Chinese market anyway.
不管咋说，还是希望RN能更重视中国市场
