### ISSUE TITLE
DeviceEventEmitter.addListener not working in Release apk

### ISSUE THREAD

**Issue by yehyaumar** [facebook/react-native#32792]
### Description

I'm using RCTDeviceEventEmitter.class to send events from android native code to react native but DeviceEventEmitter.addListener is not listening in Release Apk. It is working perfectly fine in Debug Apk. I tested this on multiple devices.

### Version

0.66.3

### Output of `npx react-native info`

System:
    OS: macOS 12.0.1
    CPU: (8) arm64 Apple M1
    Memory: 179.14 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.0.1 - /usr/local/bin/node
    Yarn: 1.22.17 - ~/Documents/graphicweave/orion/node_modules/.bin/yarn
    npm: 8.1.0 - /opt/homebrew/bin/npm
    Watchman: 2021.10.18.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /Users/yehyaumar/.rvm/gems/ruby-3.0.2/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 28, 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0
      System Images: android-30 | Google APIs ARM 64 v8a, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 13.0/13A233 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: ^0.66.3 => 0.66.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Here is my native side method to send event:
```
private void sendEvent(String eventName, WritableMap params) {
        Log.v("Events", "DEBUG: Sending event from android to react" + ' ' + eventName + " " + params.toString());

        ReactInstanceManager reactInstanceManager = getReactNativeHost().getReactInstanceManager();
        ReactContext reactContext = reactInstanceManager.getCurrentReactContext();

        if(reactContext != null) {
            Log.v("Events", "DEBUG: not null" + reactContext);
            reactContext
                .getJSModule(DeviceEventManagerModule.RCTDeviceEventEmitter.class)
                .emit(eventName, params);
        } else {
            Log.v("Events", "DEBUG: null: adding listened" + reactContext);
            reactInstanceManager.addReactInstanceEventListener(new ReactInstanceManager.ReactInstanceEventListener() {
                @Override
                public void onReactContextInitialized(ReactContext context) {
                    Log.v("Events", "DEBUG: inside listener" + context);
                    context
                        .getJSModule(DeviceEventManagerModule.RCTDeviceEventEmitter.class)
                        .emit(eventName, params);
                    reactInstanceManager.removeReactInstanceEventListener(this);
                }
            });
        }
    }
```

And in React Native app.js file

```
DeviceEventEmitter.addListener('accept', (event) => {
      //Do something
    });
```

### Snack, code example, screenshot, or link to a repository

Check steps to reproduce

**Comment by NikTheGeek1** [comment]
I am stuck here as well
