### ISSUE TITLE
Attempted to remove more RCTLinkingManager listeners than added

### ISSUE THREAD

**Issue by mehmetcansahin** [facebook/react-native#32804]
### New Version

0.66.4

### Old Version

0.66.1

### Build Target(s)

ios simulator

### Output of `react-native info`

System:
    OS: macOS 12.0.1
    CPU: (8) arm64 Apple M1
    Memory: 803.86 MB / 16.00 GB
    Shell: 3.3.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 17.0.1 - /opt/homebrew/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.1.0 - /opt/homebrew/bin/npm
    Watchman: 2021.10.18.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 26, 28, 29, 30, 31
      Build Tools: 29.0.2, 30.0.2, 31.0.0
      System Images: android-31 | Google Play ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7784292
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.10 - /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.1 => 0.66.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Issue and Reproduction Steps

When I upgrade from react native version 0.66.1 to 0.66.4 I get the error "Attempted to remove more RCTLinkingManager listeners than added". This error causes the application to crash. I downgrade the application, the problem is solved.

**Comment by mansdahlstrom1** [comment]
I'm also getting the error on React Native 0.66.1.

**Comment by fatih18** [comment]
I'm also getting this when i try to use react-native-gifted-chat

**Comment by olcaneristi** [comment]
I'm also getting this error on React Native 0.66.4. Does anyone have a solution for that problem?

**Comment by davydspotnana** [comment]
I think you use amplify-js? if yes here is an issue: 

https://github.com/aws-amplify/amplify-js/issues/9492

**Comment by olcaneristi** [comment]
nope, I'm not using Amplify. :(

**Comment by olcaneristi** [comment]
> I think you use amplify-js? if yes here is an issue:
> 
> [aws-amplify/amplify-js#9492](https://github.com/aws-amplify/amplify-js/issues/9492)

nope, I'm not using Amplify. :(

**Comment by AkshatSharda** [comment]
I am also facing the same issue after upgrading to react-native v0.66.4  and not using amplify-js as well.

**Comment by Nishit-Chauhan** [comment]
i am also facing the same issue after upgrading from 0.61.5 to 0.66.4 and not using amplify-js as well.

**Comment by beisert1** [comment]
Want to add that I updated to latest 0.67.3 in hopes it would not have this issue but unfortunately it does. It appears this error is happening since version 0.66.0

**Comment by beisert1** [comment]
For anyone struggling with this issue please check react-navigation, we are on an old fork of v2 react-navigation and I was able to apply something similar to this solution that resolved this error: https://github.com/react-navigation/react-navigation/issues/9894

**Comment by nica0012** [comment]
> For anyone struggling with this issue please check react-navigation, we are on an old fork of v2 react-navigation and I was able to apply something similar to this solution that resolved this error: https://github.com/react-navigation/react-navigation/issues/9894

Can you please share how you went about solving this?

Do you need to apply those edits every time you run yarn / npm install?

**Comment by yasodha-r** [comment]
This issue exist in 0.68 as well. Any fix/workaround available?

**Comment by brysonjonesy** [comment]
Still happening in 0.70.3

**Comment by gern132** [comment]
appeared after upgrading the RN from 61 to 69

**Comment by aurangs7** [comment]
still getting this error in react-native 0.71.4

**Comment by AngCosmin** [comment]
Still happening in RN 0.71.4

**Comment by benmoumen** [comment]
Still happening in RN 0.77.1 (new architecture)

**Comment by Lakston** [comment]
still hapenning on 79.5 (old arch)
