### ISSUE TITLE
Error when separating android project from React Native: Cannot find module 'react-native/cli'Require stack:-/home/usr/react_demo/android/[eval]

### ISSUE THREAD

**Issue by SherMish** [facebook/react-native#32807]
### Description

I`ve created a standard React Native project with the following structure: 
```
react_demo  |__ AwesomeProject |__ android/
                               |__ index.js
                               |__ package.json
                               |__ node_modules/
```
It works as expected.

And I`m trying to seperate the Android project, like this: 
```
react_demo  |__ android/
            |__ AwesomeProject |__ index.js  
                               |__ package.json    
                               |__ node_modules/
```

I followed the following tutorial: [Separate your Android of React Native](https://developers.ascendcorp.com/integrate-react-native-into-an-existing-android-project-with-separated-repositories-b445c09e0d10). Unfortunately the project throws an error when building. Full error:
```
:ReactNative:Unexpected empty result of running '[node, -e, console.log(require('react-native/cli').bin);]' command.
:ReactNative:Running '[node, -e, console.log(require('react-native/cli').bin);]' command failed.

FAILURE: Build failed with an exception.

* Where:
Script '/home/usr/react_demo/AwesomeProject/node_modules/@react-native-community/cli-platform-android/native_modules.gradle' line: 213

* What went wrong:
A problem occurred evaluating script.
> node:internal/modules/cjs/loader:936  throw err;  ^Error: Cannot find module 'react-native/cli'Require stack:- /home/usr/react_demo/android/[eval]    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)    at Function.Module._load (node:internal/modules/cjs/loader:778:27)    at Module.require (node:internal/modules/cjs/loader:999:19)    at require (node:internal/modules/cjs/helpers:102:18)    at [eval]:1:13    at Script.runInThisContext (node:vm:129:12)    at Object.runInThisContext (node:vm:305:38)    at node:internal/process/execution:75:19    at [eval]-wrapper:6:22    at evalScript (node:internal/process/execution:74:60) {  code: 'MODULE_NOT_FOUND',  requireStack: [ '/home/usr/react_demo/android/[eval]' ]}Node.js v17.3.0
```
Already tried: 1.Deleting node_modules and running npm install, 2. running npm i react-native-cli. Nothing helped. Thank you

### Version

0.66.4

### Output of `npx react-native info`

System:
    OS: Linux 5.11 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 5.01 GB / 15.36 GB
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 17.3.0 - /usr/bin/node
    Yarn: 1.22.17 - /usr/bin/yarn
    npm: 8.3.0 - /usr/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 21, 23, 27, 28, 29, 30, 31
      Build Tools: 28.0.3, 29.0.0, 29.0.2, 31.0.0
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 11.0.13 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.0 => 17.0.0 
    react-native: ^0.66.4 => 0.66.4 
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

I changed all the paths in the android project successfully: 
1.settings.gradle:
```

include ':app'
rootProject.name = "AccessApp"
apply from: file("../AwesomeProject/node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
//                ^^Modified

```

2.build.gradle:

```
allprojects {
    repositories {
        maven {
            url "/home/usr/react_demo/AwesomeProject/node_modules/react-native/android"
        }
        maven {
            url("/home/usr/react_demo/AwesomeProject/node_modules/jsc-android/dist")
        }
        google()
        jcenter()
    }
}
```

3.build.gradle:app
`
apply from: file("/home/usr/react_demo/AwesomeProject/node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)
`

Also, I`ve changed the path in React Native by creating react-native.config.js in root folder:

react-native.config.js:

```
module.exports = {
    project: {
      android: {
        sourceDir: '../android',
      },
    },
  };

```
And then I ran: `npx react-native config`.

**Comment by HacerBusraKILIC** [comment]
Hello @SherMish I got the same error. Did you solve the problem?

**Comment by HacerBusraKILIC** [comment]
https://github.com/facebook/react-native/issues/31203#issuecomment-1022531387 I solved with this comment

**Comment by liusunmiao** [comment]
你好关于这个问题怎弄，我按照弄了还是一直报错
