### ISSUE TITLE
Crash on iOS -[RCTModuleMethod invokeWithBridge:module:arguments:] + 587

### ISSUE THREAD

**Issue by kevinxie120** [facebook/react-native#32801]
### Description

it cause random crash when app start in 1-2s.

FireBase show two error key: 
1.Corrupt NSInvocation detected. Pointer authentication.
2.EXC_BREAKPOINT.

XXX represent appp name and stack trace as follow,:

Crashed: com.facebook.react.JavaScript
0  CoreFoundation                 0x16ff64 _NSIPoisoned + 16
1  CoreFoundation                 0xa21e8 -[NSInvocation setArgument:atIndex:] + 596
2  CoreFoundation                 0x769c4 -[NSInvocation invokeWithTarget:] + 64
3  XXX                        0x46f874 -[RCTModuleMethod invokeWithBridge:module:arguments:] + 587 (RCTModuleMethod.mm:587)
4  XXX                        0x471bcc facebook::react::invokeInner(RCTBridge*, RCTModuleData*, unsigned int, folly::dynamic const&, int, (anonymous namespace)::SchedulingContext) + 208 (RCTNativeModule.mm:208)
5  XXX                        0x47186c invocation function for block in facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int) + 404 (Optional.h:404)
6  XXX                        0x471698 facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int) + 129 (RCTNativeModule.mm:129)
7  XXX                        0x50c650 facebook::react::JsToNativeBridge::callNativeModules(facebook::react::JSExecutor&, folly::dynamic&&, bool) + 1633 (iterator:1633)
8  XXX                        0x518424 facebook::react::JSIExecutor::callNativeModules(facebook::jsi::Value const&, bool) + 370 (dynamic-inl.h:370)
9  XXX                        0x5185c0 facebook::react::JSIExecutor::invokeCallback(double, folly::dynamic const&) + 263 (JSIExecutor.cpp:263)
10 XXX                        0x50d854 std::__1::__function::__func<facebook::react::NativeToJsBridge::runOnExecutorQueue(std::__1::function<void (facebook::react::JSExecutor*)>)::$_8, std::__1::allocator<facebook::react::NativeToJsBridge::runOnExecutorQueue(std::__1::function<void (facebook::react::JSExecutor*)>)::$_8>, void ()>::operator()() + 1732 (functional:1732)
11 XXX                        0x45a344 facebook::react::tryAndReturnError(std::__1::function<void ()> const&) + 1885 (functional:1885)
12 XXX                        0x466758 facebook::react::RCTMessageThread::tryFunc(std::__1::function<void ()> const&) + 68 (RCTMessageThread.mm:68)
13 XXX                        0x46650c invocation function for block in facebook::react::RCTMessageThread::runAsync(std::__1::function<void ()>) + 45 (RCTMessageThread.mm:45)
14 CoreFoundation                 0x729d4 __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 28
15 CoreFoundation                 0x738d0 __CFRunLoopDoBlocks + 412
16 CoreFoundation                 0xbc30 __CFRunLoopRun + 1728
17 CoreFoundation                 0x1f468 CFRunLoopRunSpecific + 600
18 XXX                        0x44fcc4 +[RCTCxxBridge runRunLoop] + 266 (RCTCxxBridge.mm:266)
19 Foundation                     0x6840c __NSThread__start__ + 808
20 libsystem_pthread.dylib        0x19a4 _pthread_start + 148
21 libsystem_pthread.dylib        0xea0 thread_start + 8

### Version

0.63.3

### Output of `npx react-native info`

System:
    OS: macOS 11.6.1
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
    Memory: 343.13 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.21.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.11 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.2 - /Users/xichen/.rvm/gems/ruby-2.7.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

it cause random crash when app start in 1-2s.

**Comment by kevinxie120** [comment]
> ⚠️	Missing Environment Information
> ℹ️	Your issue may be missing information about your development environment. You can obtain the missing information by running `react-native info` in a console.

System:
OS: macOS 11.6.1
CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
Memory: 343.13 MB / 16.00 GB
Shell: 5.8 - /bin/zsh
Binaries:
Node: 12.21.0 - /usr/local/bin/node
Yarn: 1.22.10 - /usr/local/bin/yarn
npm: 6.14.11 - /usr/local/bin/npm
Watchman: 4.9.0 - /usr/local/bin/watchman
Managers:
CocoaPods: 1.10.2 - /Users/xichen/.rvm/gems/ruby-2.7.0/bin/pod
SDKs:
iOS SDK:
Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
Android SDK: Not Found
IDEs:
Android Studio: 4.0 AI-193.6911.18.40.6514223
Xcode: 12.4/12D4e - /usr/bin/xcodebuild
Languages:
Java: 11.0.11 - /usr/bin/javac
Python: 2.7.16 - /usr/bin/python
npmPackages:
@react-native-community/cli: Not Found
react: 16.13.1 => 16.13.1
react-native: 0.63.3 => 0.63.3
react-native-macos: Not Found
npmGlobalPackages:
react-native: Not Found

**Comment by starFelix** [comment]
I met this crash also. Anyone can help me?

**Comment by chengshiliang** [comment]
I met this crash also. Anyone can help me?

**Comment by PengQ1** [comment]
I met this crash also. Anyone can help me?

**Comment by aitreya** [comment]
I am also facing the same issue while creating appClip with react native can anyone help with this?
