### ISSUE TITLE
ERROR in ./node_modules/react-native/index.js: Module parse failed: Unexpected token

### ISSUE THREAD

**Issue by belaziv** [facebook/react-native#32819]
### Description

I'm trying to use some UI library for my react native WEB app
I run it with `webpack` + `babel` but I get the following error:
```
ERROR in ./node_modules/react-native/index.js 14:7
Module parse failed: Unexpected token (14:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
| // Components
> import typeof AccessibilityInfo from './Libraries/Components/AccessibilityInfo/AccessibilityInfo';
| import typeof ActivityIndicator from './Libraries/Components/ActivityIndicator/ActivityIndicator';
| import typeof Button from './Libraries/Components/Button';
 @ ./node_modules/react-native-paper/lib/module/styles/shadow.js 2:0-40 6:27-41 11:19-33
 @ ./node_modules/react-native-paper/lib/module/index.js 7:0-52 7:0-52
 @ ./src/App.tsx 19:0-63 20:0-45 31:42-55 33:38-45
 @ ./src/index.tsx 15:0-24 17:9-12
```

### Version

`^0.66.4`

### Output of `npx react-native info`

```
System:
    OS: Linux 5.11 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 893.15 MB / 15.36 GB
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.13.1 - /usr/local/bin/node
    Yarn: 1.22.15 - /snap/bin/yarn
    npm: 8.1.2 - /usr/local/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.2 => 17.0.2 
    react-native: ^0.66.4 => 0.66.4 
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

This happens with every UI library I'm trying to use 
see https://github.com/akveo/react-native-ui-kitten/issues/1569

### Snack, code example, screenshot, or link to a repository
https://github.com/belaziv/RN-WEB-EX

**Comment by belaziv** [comment]
I tried to do it with `vite`, but got the same error:
```
belaziv@belaziv-Vostro-5402:~/projects/vite-project$ npm run dev

> vite-project@0.0.0 dev
> vite

Pre-bundling dependencies:
  react-native
  react
  react/jsx-dev-runtime
(this will be run only when your dependencies or config have changed)
 > node_modules/react-native/index.js:14:7: error: Unexpected "typeof"
    14 │ import typeof AccessibilityInfo from './Libraries/Components/AccessibilityInfo/AccessibilityInfo';
       ╵        ~~~~~~

error when starting dev server:
Error: Build failed with 1 error:
node_modules/react-native/index.js:14:7: error: Unexpected "typeof"
```

**Comment by Jacknes** [comment]
> I tried to do it with `vite`, but got the same error:
> 
> ```
> belaziv@belaziv-Vostro-5402:~/projects/vite-project$ npm run dev
> 
> > vite-project@0.0.0 dev
> > vite
> 
> Pre-bundling dependencies:
>   react-native
>   react
>   react/jsx-dev-runtime
> (this will be run only when your dependencies or config have changed)
>  > node_modules/react-native/index.js:14:7: error: Unexpected "typeof"
>     14 │ import typeof AccessibilityInfo from './Libraries/Components/AccessibilityInfo/AccessibilityInfo';
>        ╵        ~~~~~~
> 
> error when starting dev server:
> Error: Build failed with 1 error:
> node_modules/react-native/index.js:14:7: error: Unexpected "typeof"
> ```

You need to alias react-native to react-native-web
```
export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      'react-native': 'react-native-web',
    },
  },
});
```

**Comment by visormatt** [comment]
@Jacknes were you able to get this to work?

**Comment by Mister-CK** [comment]
I am also getting this same error when running storybook. I run it with metro and babel, I already have
```
    alias: {
      'react-native': 'react-native-web',
    },
```
in my babel.config

**Comment by yairopro** [comment]
install `react-native-web` & `@types/react-native`
and set in the vite config
```javascript
export default defineConfig({
  // ....
  resolve: {
    alias: {
      'react-native': 'react-native-web',
    },
  },
});
```
