### ISSUE TITLE
No such module 'ExpoModulesCore'

### ISSUE THREAD

**Issue by darrensw777** [facebook/react-native#32818]
### Description

When building a basic react native app with XCode, it gives the error:

No such module 'ExpoModulesCore'

XCode version 13.2.1

### Version

0.64.3

### Output of `npx react-native info`

System:
    OS: macOS 12.1
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 663.30 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.15.4 - /usr/local/bin/node
    Yarn: 1.22.17 - ~/.npm-global/bin/yarn
    npm: 6.14.10 - /usr/local/bin/npm
    Watchman: 2021.12.27.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 27, 28
      Build Tools: 28.0.3
      System Images: android-27 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_201 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.3 => 0.64.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Create simple react-native app, build with XCode

**Comment by greenafrican** [comment]
Try opening project.xcworkspace (and not project.xcodeproj) in Xcode and run via simulator.
