### ISSUE TITLE
Height of View from onLayout doesn't match with style prop on Pixel 3a

### ISSUE THREAD

**Issue by Waltari10** [facebook/react-native#32814]
### Description

I am trying to make an element of height 30 in React Native. However on Android Pixel 3a the height of the element resolves close to 30, but not quite 30.

The following code snippet results in every other element having height of 29.81818199157715 and 30.18181800842285 for every other. It seems to only happen on on Pixel 3a. Both on emulator and on real device (tested on Browserstack)

### Version

0.66.4

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 11.6
    CPU: (8) x64 Apple M1
    Memory: 33.65 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.5 - /usr/local/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 6.14.14 - /usr/local/bin/npm
    Watchman: 2021.11.08.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 24, 25, 26, 27, 28, 29, 30, 31
      Build Tools: 30.0.2, 31.0.0
      System Images: android-23 | Google APIs ARM EABI v7a, android-24 | ARM EABI v7a, android-24 | Google APIs ARM 64 v8a, android-25 | Google APIs ARM 64 v8a, android-26 | Intel x86 Atom, android-26 | Intel x86 Atom_64, android-29 | Google APIs ARM 64 v8a, android-30 | Google APIs ARM 64 v8a, android-31 | Google APIs ARM 64 v8a, android-32 | Google APIs ARM 64 v8a, android-32 | Google Play ARM 64 v8a, android-32 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7784292
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.4 => 0.66.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Run this code snippet on Pixel 3a (emulator or real device).

EDIT: actually looks like it's happening on almost all Pixel phones.

```
import React from 'react';
import {View} from 'react-native';

export default () => (
  <View
    onLayout={layout => {
      console.log('appText height', layout.nativeEvent.layout.height); // Should be 30, but says 30.18181800842285
    }}
    style={{
      height: 30,
    }}
  />
);

```

### Snack, code example, screenshot, or link to a repository

Link to repo: https://github.com/Waltari10/scrollviewbugreactnative

**Comment by Waltari10** [comment]
I did some testing on different element heights on different devices

**iPhone 13, iPhone 13 mini, pixelRatio is 3**
everything exact

**iphone 8, pixelRatio is 2**
everything exact

**3.4 WQVGA_API_32, pixel ratio is 0.75**
exact: 24, 28, 32

**5.4 mdpi, pixel ratio: 1**
exact: 28, 29, 30, 31

**Pixel XL, 560 DPI, pixel ratio is 3.5**
exact: 24, 26, 28

**Pixel 5, 440dpi, pixel ratio: 2,75**
exact: 32, 28, 24
not exact: 33, 31, 30, 29

**Pixel 3a ratio is 2.75, xxhdpi, 440dpi**
exact: 12, 16, 20, 24, 28, 32, 36, 40, 44, 48
Not exact: 30, 31, 32,33,34

**Galaxy nexus ratio is 2, xhdpi, 440dpi**
exact: 12 - 20
not exact: ???

**8 Fold-Out API 31, 2200 x 2480dpi, xxhdpi, ratio is 2.625**
exact: 16, 24, 32, 40
not exact: 14, 15, 17, 18, 19, 20, 21, 22, 23, 25, 26, 27, 28, 29, 30, 31

**3.7 FWVA slider API 29, hdpi, 480 x 854, ratio is 1.5**
exact: 40, 38, 36, 34, 33
not exact: 39, 37, 35

**Comment by vamper424** [comment]
Well si one process dificultad Bad not insussesfool si congruentt and You need realised one configuración in the software, and in the compatibilities available's.

**Comment by vamper424** [comment]
Y reinicia el sistema operativo. Y ya puedes usarlo siempre.
