### ISSUE TITLE
BigInt on android returns `object` data type instead of `bigint`

### ISSUE THREAD

**Issue by Balanced02** [facebook/react-native#32820]
### Description

Using BigInteger on android on either release build or without debugging mode enabled, the type of data returned is `object` but with debugger, the data type is `bigint`.

Using `BigInt` on iOS returns `bigint` data on either of the environments.

Versions: 

### Version

0.65.1, 0.66.4

### Output of `npx react-native info`

System:
    OS: macOS 12.0.1
    CPU: (8) x64 Apple M1
    Memory: 41.32 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.4.0 - ~/.nvm/versions/node/v12.4.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v12.4.0/bin/npm
    Watchman: 2021.10.18.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /Users/danielayomide/.rvm/gems/ruby-2.7.3/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 23, 26, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0
      System Images: android-25 | Google APIs ARM 64 v8a, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play ARM 64 v8a, android-31 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: javac 16 - /Users/danielayomide/.sdkman/candidates/java/current/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.65.1 => 0.65.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

https://github.com/Balanced02/BigIntIssue
I replicated this issue on a fresh react-native project with more details on the README.

### Snack, code example, screenshot, or link to a repository

https://github.com/Balanced02/BigIntIssue

**Comment by ManuGowda** [comment]
We need resolution to fix the android production release https://github.com/LiskHQ/lisk-mobile/issues/1176

**Comment by irfanayaz** [comment]
We are having the same issue. BigInt on android is returning object instead of the type bigint
