### ISSUE TITLE
Text show a incomplete string if enable Hermes Engine in some android phone and react-native >= 0.66.x

### ISSUE THREAD

**Issue by vibexie** [facebook/react-native#32829]
### Description

react-native >= 0.66.x, Text show a incomplete string if enable Hermes Engine in some android phone, if disable Hermes Engine, Text works well

### Version

0.66.x

### Output of `npx react-native info`

There are no related logs info

### Steps to reproduce

1. react-native >= 0.66.x
2. enable Hermes Engine
3. some android phones like xiaomi 8

### Snack, code example, screenshot, or link to a repository
![screenshot example](https://gohttpserver.devops.shundaojia.com/github_facebook_react_native_issue.png)
#### The time texts in the screenshot should be right 18:00-19:00, 19:00-20:00 etc.

**Comment by cortinico** [comment]
> screenshot example

Please link to a public image. This link requires an authentication which is far from ideal.

**Comment by vibexie** [comment]
> > screenshot example
> 
> Please link to a public image. This link requires an authentication which is far from ideal.



> 

Ok，I changed the screenshot url
