### ISSUE TITLE
onKeyDown is not handled in the (Android) Modal component.  At all.

### ISSUE THREAD

**Issue by DaveWelling** [facebook/react-native#32827]
### Description

If you add Java code to your application's ReactActivity like this:
```
public class MainActivity extends ReactActivity {

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (keyCode == KEYCODE_BUTTON_16) {
            rfidScanning.startScanning();
            return true;
        } else {
            return super.onKeyDown(keyCode, event);
        }
    }
```
It won't fire if you have a Modal open.  However onKeyUp will.  It's easy to see the bug in the code here:
https://github.com/facebook/react-native/blob/b531612b2c917e1f2bd6bb37bf854fe51e658b36/ReactAndroid/src/main/java/com/facebook/react/views/modal/ReactModalHostView.java#L220-L247

There's a handler for KeyEvent.ACTION_UP, passing it back into the activity, but not one for KeyEvent.ACTION_DOWN.  It's just swallowed.

### Version

0.66.0

### Output of `npx react-native info`

System:
    OS: Windows 10 10.0.19042
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
    Memory: 11.97 GB / 31.92 GB
  Binaries:
    Node: 16.6.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 7.19.1 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: Not Found
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.2 => 0.64.2
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

You can probably just see the bug in the code I referenced above without having to reproduce.  It's super obvious.  But if you need a reproduction, just create an onKeyUp and onKeyDown handler in your 'MainActivity" ReactActivity in your Java.  Then add a visible modal to your app with a TextInput.
Put breakpoints in both, run the app and type anything into the TextInput.  You'll see the bug.

**Comment by DaveWelling** [comment]
bump

**Comment by acaraty** [comment]
up

**Comment by tomasgarba** [comment]
Facing the same issue... `onKeyDown` events are swallowed by Modal.
