### ISSUE TITLE
Expo local notification not working in android when time format 12 hour

### ISSUE THREAD

**Issue by souravpradhan980** [facebook/react-native#32825]
### Description

This is My Code: hear trigger is 24-hour format but my android is 12-hour format it is not working Please give the solution -- is there any option to enter trigger with 12-hour format? Please help me

### Version

0.66

### Output of `npx react-native info`

Not coming local notification from expo app when android in 12-hour format

### Steps to reproduce

import { StatusBar } from 'expo-status-bar';
import React, { useEffect, useState } from 'react';
import { StyleSheet, Text, Button, View } from 'react-native';
import * as Notifications from 'expo-notifications';
import * as Permissions from 'expo-permissions';

//import notifee from '@notifee/react-native';
Notifications.setNotificationHandler({
    handleNotification: async () => {
        return {
            shouldShowAlert: true,
            shouldPlaySound: true
        }
    }
});

export default function App() {
    useEffect(() => {
        Permissions.getAsync(Permissions.NOTIFICATIONS).then((object) => {
            if (object.status != "granted") {
                return Permissions.askAsync(Permissions.NOTIFICATIONS);
            }
            return object;
        }).then((object) => {
            if (object.status != 'granted') {
                alert("Now Can not Send any Notification");
                return;
            }
        });
    }, []);
    const [notification, setNotification] = useState(false);
    useEffect(() => {
        const backgroundSubscription = Notifications.addNotificationResponseReceivedListener((response) => {
            //console.log(response);
        });
        const forgroundSubscription = Notifications.addNotificationReceivedListener((obj) => {
            console.log(obj);
            // if (count == 1) {
            //     console.log("running2");
            //     reapetNotification();
            // }
            reapetNotification();

        });
        //alert('hello');
        return () => {
            backgroundSubscription.remove();
            forgroundSubscription.remove();

        };
    }, []);
    const reapetNotification = () => {

        var notificationIdReapet = Notifications.scheduleNotificationAsync({
            content: {
                title: "My First Notification",
                body: "This is local notification Sending"
            },
            trigger: {
                seconds: 3

            }
        });

    }
    const triggerNotificationHandaler = () => {
        // let timestamp = new Date();
        // timestamp.setHours(21);
        // timestamp.setMinutes(24);

        var notificationId = Notifications.scheduleNotificationAsync({
            content: {
                title: "My First Notification",
                body: "This is local notification Sending"
            },
            trigger: {
                hour: 13,
                minute: 13,

                repeats: true
            }
        });
        // console.log(notificationId);
        setNotification(notificationId);
        //Notifications.dismissAllNotificationsAsync();
        //Notifications.cancelScheduledNotificationAsync(notificationId);

    };
    const cancelNotification = () => {
        Notifications.cancelAllScheduledNotificationsAsync();
        //triggerNotificationHandaler();
    }

    return (
        <View style={styles.container}>
            <View>
                <Button title="Trigure Notification" onPress={triggerNotificationHandaler} />
                <Button title="Cancel Notification" style={{ marginTop: 10 }} onPress={cancelNotification} />
            </View>
            <StatusBar style="auto" />
        </View>
    );
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#fff',
        alignItems: 'center',
        justifyContent: 'center',
    },
});

### Snack, code example, screenshot, or link to a repository

![local-notification-issue](https://user-images.githubusercontent.com/68933126/147902542-7fbdbaf9-c48f-4e22-950c-69b66d495bac.PNG)

**Comment by giautm** [comment]
You should move this issue to @expo/expo project

**Comment by cortinico** [comment]
> You should move this issue to [expo/expo](https://github.com/expo/expo) project

As @giautm correctly suggested, this issue should be moved. I'm closing it.
