### ISSUE TITLE
Cannot update a component when using useContext

### ISSUE THREAD

**Issue by zandvakiliramin** [facebook/react-native#32837]
### Description

I am developing an App with React-native and Expo and I am using a Context variable. The context is defined in the `XContext` component:

```javascript
import React, { useState } from "react";

const XContext = React.createContext({
  x: "",
  onChangeX: (newX) => {},
});

export const XContextProvider = (props) => {
  const [x, setX] = useState("");

  const xChangeHandler = (newX) => {
    setX(newX);
  };
  return (
    <XContext.Provider
      value={{ x, onChangeX: xChangeHandler }}
    >
      {props.children}
    </XContext.Provider>
  );
};

export default XContext;
```
I want all parts of the app to be able to use this context variable, so I wrapped my stack navigator, in the component Navigation, with XContextProvider.

```javascript
import { XContextProvider } from "./context/x-context";
import Navigation from "./navigation";

const App = () => {
  return (
    <XContextProvider>
        <Navigation />
    </XContextProvider>
  );
};

export default App;
```

I am developing an App with React-native and I am using a Context variable. The context is defined in this component:

```javascript
import React, { useState } from "react";

const XContext = React.createContext({
  x: "",
  onChangeX: (newX) => {},
});

export const XContextProvider = (props) => {
  const [x, setX] = useState("");

  const xChangeHandler = (newX) => {
    setX(newX);
  };
  return (
    <XContext.Provider
      value={{ x, onChangeX: xChangeHandler }}
    >
      {props.children}
    </XContext.Provider>
  );
};

export default XContext;
```

I want all parts of the app to be able to use this context variable, so I wrapped my stack navigator, in the component Navigation, with XContextProvider.

```javascript
import { XContextProvider } from "./context/x-context";
import Navigation from "./navigation";

const App = () => {
  return (
    <XContextProvider>
        <Navigation />
    </XContextProvider>
  );
};

export default App;
```

`YScreen` is the first screen in my stack navigator:

```javascript
import React, { useContext } from "react";
import XContext from "the path it is located in";

const CreateDataScreen = () => {

  const ctx = useContext(XContext);
  ctx.onChangeX("test context");
  console.log(ctx.x);

  return (
    <View>
      <Text>
        Test Context
      </Text>
    </View>
  );
};

export default YScreen;
```

Now when I run my app I get a warning telling me

>Warning: Cannot update a component (XContextProvider) while rendering a different component (YScreen). To locate the bad setState() call inside YScreen, follow the stack trace as described in https://reactjs.org/link/setstate-in-render.

I looked into the link above, but could not find the any solutions for this problem.

### Version

0.64.3

### Output of `npx react-native info`

System:
    OS: macOS 11.6.2
    CPU: (4) x64 Intel(R) Core(TM) i5-4308U CPU @ 2.80GHz
    Memory: 6.16 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.1 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 6.14.15 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7784292
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.3 => 0.64.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

- I have described how to do this in the description part.

**Comment by SparkTech-BSS** [comment]
I have the same problem
