### ISSUE TITLE
LinkingIOS url fragment truncation 

### ISSUE THREAD

**Issue by ghostsnstuff** [facebook/react-native#3283]
##### _Issue_: url fragment is being truncated. 

Env: RN 0.11.4

For example ...

```
LinkingIOS.openUrl('https://en.m.wikipedia.org/wiki/Binary_number#Counting_in_binary');
```

Url resolves to `https://en.m.wikipedia.org/wiki/Binary_number`.

Using Chrome dev tools - all ios devices resolve the url with it's fragment. 

I haven't looked through the objective-c code thoroughly (I can); want to see if folks with more objective-c and ios experience have input first. 

Here's an example (RNP): https://rnplay.org/apps/4K1CAA 
Gist: https://gist.github.com/ghostsnstuff/f0231f045af96800b391   
LinkingIOS Bridge `openUrl` (obviously js code invokes this): https://github.com/facebook/react-native/blob/304989e3b8cec800bc42c7f7210bc286d5c0b4b0/Libraries/LinkingIOS/RCTLinkingManager.m#L58#L62

**Comment by christopherdro** [comment]
This works for me with both device and simulator but not through rnplay. I can however scan the qr code and then have it work fine from phone.

I'm thinking that the issue is unrelated to react native and maybe specific to appetize.io

Have you tried this on a actual device as well?
