### ISSUE TITLE
Unexpected token '.' when using eval with optional chaining operator

### ISSUE THREAD

**Issue by hufftheweevil** [facebook/react-native#32859]
### Description

`SyntaxError: Unexpected token '.'` when using the optional chaining operator in `eval()`.

Note I am using Expo SDK 44. Does anyone know if this would have anything to do with it? Should I be reporting it in the Expo repo instead?

### Version

0.64.3

### Output of `npx react-native info`

```
System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz
    Memory: 16.94 GB / 31.81 GB
  Binaries:
    Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.15 - ~\Documents\Projects\project_name\node_modules\.bin\npm.CMD      
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowAllTrustedApps: Disabled
      Versions: 10.0.17763.0, 10.0.19041.0
  IDEs:
    Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7935034       
    Visual Studio: Not Found
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.3 => 0.64.3
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

Example code
```
let someObject = { propertyMayOrMayNotExist: { deeper: 'test' } }
eval('someObject.propertyMayOrMayNotExist?.deeper')
```

Running that code in Node or the browser works just fine.

But running that code in a React Native project generates an error: `SyntaxError: Unexpected token '.'`

If you change the second line to:
`console.log(someObject.propertyMayOrMayNotExist?.deeper)`
or
`eval('someObject.propertyMayOrMayNotExist.deeper')`
then it works.

**Comment by guicompeng** [comment]
Same problem here, with react native 0.63.4.
I init  a new project  in version 0.63.4 and gave this problem too
