### ISSUE TITLE
Views in View have unknown white line

### ISSUE THREAD

**Issue by ww8007** [facebook/react-native#32852]
### Description

I have problem with unknown white line in views in view
Just Android in real device has problem or eas build with PIXEL 4 API 31 Android 12.0

Like under image i didn't purpose to have white line for each view render but it have problem
![image](https://user-images.githubusercontent.com/54137044/148629697-0f593e0a-c131-433e-934a-a27675cafccb.png)

### Version

0.64.3

### Output of `npx react-native info`

System:
    OS: macOS 12.1
    CPU: (8) x64 Apple M1
    Memory: 41.71 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.4 - ~/.nvm/versions/node/v14.17.4/bin/node
    Yarn: 1.22.15 - ~/.yarn/bin/yarn
    npm: 6.14.14 - ~/.nvm/versions/node/v14.17.4/bin/npm
    Watchman: 2021.12.20.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /Users/ww8007/.gem/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 30, 31
      Build Tools: 29.0.2, 31.0.0
      System Images: android-29 | Google APIs ARM 64 v8a, android-30 | Google APIs ARM 64 v8a, android-30 | Google Play ARM 64 v8a, android-31 | ARM 64 v8a, android-31 | Google APIs ARM 64 v8a, android-31 | Google Play ARM 64 v8a, android-32 | Google APIs ARM 64 v8a, android-32 | Google Play ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.3 => 0.64.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Views in View have problem 
just in real android device and specific android simulator version like image
![image](https://user-images.githubusercontent.com/54137044/148629685-945babd9-7004-4de7-ac37-2960e4bfc2f5.png)

### Snack, code example, screenshot, or link to a repository

```js
import React from 'react';
import { StyleSheet, View } from 'react-native';

import { Colors } from 'react-native-paper';

export default function App() {
	return (
		<View style={styles.container}>
			<View style={{ flexDirection: 'row', flex: 1 }}>
				<View style={{ flex: 1, padding: 0, flexDirection: 'column' }}>
					<View style={styles.largeView}>
						<View style={styles.smallView} />
						<View style={styles.smallView} />
						<View style={styles.smallView} />
						<View style={styles.smallView} />
						<View style={styles.smallView} />
					</View>
					<View style={styles.largeView}>
						<View style={styles.smallView} />
						<View style={styles.smallView} />
						<View style={styles.smallView} />
						<View style={styles.smallView} />
						<View style={styles.smallView} />
					</View>
					<View style={styles.largeView}>
						<View style={styles.smallView} />
						<View style={styles.smallView} />
						<View style={styles.smallView} />
						<View style={styles.smallView} />
						<View style={styles.smallView} />
					</View>
					<View style={styles.largeView}>
						<View style={styles.smallView} />
						<View style={styles.smallView} />
						<View style={styles.smallView} />
						<View style={styles.smallView} />
						<View style={styles.smallView} />
					</View>
					<View style={styles.largeView}>
						<View style={styles.smallView} />
						<View style={styles.smallView} />
						<View style={styles.smallView} />
						<View style={styles.smallView} />
						<View style={styles.smallView} />
					</View>
					<View style={styles.largeView}>
						<View style={styles.smallView} />
						<View style={styles.smallView} />
						<View style={styles.smallView} />
						<View style={styles.smallView} />
						<View style={styles.smallView} />
					</View>
					<View style={styles.largeView}>
						<View style={styles.smallView} />
						<View style={styles.smallView} />
						<View style={styles.smallView} />
						<View style={styles.smallView} />
						<View style={styles.smallView} />
					</View>

					<View style={styles.largeView}>
						<View style={styles.smallView} />
						<View style={styles.smallView} />
						<View style={styles.smallView} />
						<View style={styles.smallView} />
						<View style={styles.smallView} />
					</View>
					<View style={styles.largeView}>
						<View style={styles.smallView} />
						<View style={styles.smallView} />
						<View style={styles.smallView} />
						<View style={styles.smallView} />
						<View style={styles.smallView} />
					</View>
					<View style={styles.largeView}>
						<View style={styles.smallView} />
						<View style={styles.smallView} />
						<View style={styles.smallView} />
						<View style={styles.smallView} />
						<View style={styles.smallView} />
					</View>
				</View>
			</View>
		</View>
	);
}

const styles = StyleSheet.create({
	container: {
		flex: 1,
		backgroundColor: '#fff',
	},
	smallView: {
		flex: 1,
		backgroundColor: Colors.black,
	},
	largeView: {
		flex: 1,
		borderColor: Colors.yellow600,
		borderWidth: 0.3,
	},
});
```

**Comment by desmondmc** [comment]
I'm having the same issue. It's been brought up a couple times. Seems to be a problem with Android not supporting floating point position of views but yoga does.

Haven't found a good fix for this yet. Seems like a pretty big deal, and something that the framework should address 🤷‍♂️

https://github.com/facebook/react-native/issues/29010
https://stackoverflow.com/questions/42565184/react-native-unexplainable-spacea-white-line-between-two-views

**Comment by ww8007** [comment]
> ### Description
> I have problem with unknown white line in views in view Just Android in real device has problem or eas build with PIXEL 4 API 31 Android 12.0
> 
> Like under image i didn't purpose to have white line for each view render but it have problem ![image](https://user-images.githubusercontent.com/54137044/148629697-0f593e0a-c131-433e-934a-a27675cafccb.png)
> 
> ### Version
> 0.64.3
> 
> ### Output of `npx react-native info`
> System: OS: macOS 12.1 CPU: (8) x64 Apple M1 Memory: 41.71 MB / 16.00 GB Shell: 5.8 - /bin/zsh Binaries: Node: 14.17.4 - ~/.nvm/versions/node/v14.17.4/bin/node Yarn: 1.22.15 - ~/.yarn/bin/yarn npm: 6.14.14 - ~/.nvm/versions/node/v14.17.4/bin/npm Watchman: 2021.12.20.00 - /opt/homebrew/bin/watchman Managers: CocoaPods: 1.11.2 - /Users/ww8007/.gem/bin/pod SDKs: iOS SDK: Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3 Android SDK: API Levels: 30, 31 Build Tools: 29.0.2, 31.0.0 System Images: android-29 | Google APIs ARM 64 v8a, android-30 | Google APIs ARM 64 v8a, android-30 | Google Play ARM 64 v8a, android-31 | ARM 64 v8a, android-31 | Google APIs ARM 64 v8a, android-31 | Google Play ARM 64 v8a, android-32 | Google APIs ARM 64 v8a, android-32 | Google Play ARM 64 v8a Android NDK: Not Found IDEs: Android Studio: Not Found Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild Languages: Java: 1.8.0_292 - /usr/bin/javac npmPackages: @react-native-community/cli: Not Found react: 17.0.1 => 17.0.1 react-native: 0.64.3 => 0.64.3 react-native-macos: Not Found npmGlobalPackages: _react-native_: Not Found
> 
> ### Steps to reproduce
> Views in View have problem just in real android device and specific android simulator version like image ![image](https://user-images.githubusercontent.com/54137044/148629685-945babd9-7004-4de7-ac37-2960e4bfc2f5.png)
> 
> ### Snack, code example, screenshot, or link to a repository
> ```js
> import React from 'react';
> import { StyleSheet, View } from 'react-native';
> 
> import { Colors } from 'react-native-paper';
> 
> export default function App() {
> 	return (
> 		<View style={styles.container}>
> 			<View style={{ flexDirection: 'row', flex: 1 }}>
> 				<View style={{ flex: 1, padding: 0, flexDirection: 'column' }}>
> 					<View style={styles.largeView}>
> 						<View style={styles.smallView} />
> 						<View style={styles.smallView} />
> 						<View style={styles.smallView} />
> 						<View style={styles.smallView} />
> 						<View style={styles.smallView} />
> 					</View>
> 					<View style={styles.largeView}>
> 						<View style={styles.smallView} />
> 						<View style={styles.smallView} />
> 						<View style={styles.smallView} />
> 						<View style={styles.smallView} />
> 						<View style={styles.smallView} />
> 					</View>
> 					<View style={styles.largeView}>
> 						<View style={styles.smallView} />
> 						<View style={styles.smallView} />
> 						<View style={styles.smallView} />
> 						<View style={styles.smallView} />
> 						<View style={styles.smallView} />
> 					</View>
> 					<View style={styles.largeView}>
> 						<View style={styles.smallView} />
> 						<View style={styles.smallView} />
> 						<View style={styles.smallView} />
> 						<View style={styles.smallView} />
> 						<View style={styles.smallView} />
> 					</View>
> 					<View style={styles.largeView}>
> 						<View style={styles.smallView} />
> 						<View style={styles.smallView} />
> 						<View style={styles.smallView} />
> 						<View style={styles.smallView} />
> 						<View style={styles.smallView} />
> 					</View>
> 					<View style={styles.largeView}>
> 						<View style={styles.smallView} />
> 						<View style={styles.smallView} />
> 						<View style={styles.smallView} />
> 						<View style={styles.smallView} />
> 						<View style={styles.smallView} />
> 					</View>
> 					<View style={styles.largeView}>
> 						<View style={styles.smallView} />
> 						<View style={styles.smallView} />
> 						<View style={styles.smallView} />
> 						<View style={styles.smallView} />
> 						<View style={styles.smallView} />
> 					</View>
> 
> 					<View style={styles.largeView}>
> 						<View style={styles.smallView} />
> 						<View style={styles.smallView} />
> 						<View style={styles.smallView} />
> 						<View style={styles.smallView} />
> 						<View style={styles.smallView} />
> 					</View>
> 					<View style={styles.largeView}>
> 						<View style={styles.smallView} />
> 						<View style={styles.smallView} />
> 						<View style={styles.smallView} />
> 						<View style={styles.smallView} />
> 						<View style={styles.smallView} />
> 					</View>
> 					<View style={styles.largeView}>
> 						<View style={styles.smallView} />
> 						<View style={styles.smallView} />
> 						<View style={styles.smallView} />
> 						<View style={styles.smallView} />
> 						<View style={styles.smallView} />
> 					</View>
> 				</View>
> 			</View>
> 		</View>
> 	);
> }
> 
> const styles = StyleSheet.create({
> 	container: {
> 		flex: 1,
> 		backgroundColor: '#fff',
> 	},
> 	smallView: {
> 		flex: 1,
> 		backgroundColor: Colors.black,
> 	},
> 	largeView: {
> 		flex: 1,
> 		borderColor: Colors.yellow600,
> 		borderWidth: 0.3,
> 	},
> });
> ```

**Comment by ww8007** [comment]
I tried that to my project but when i made timetable i have the same issue 🥲
So i find solution for that 
The solution is set backgroundColor for parent view then White line is not show again!!!
