### ISSUE TITLE
Build failed after update Xcode 13.2.1 beta Cannot initialize a parameter of type 'NSArray<id<RCTBridgeModule>> *' with an rvalue of type 'NSArray<Class> *'

### ISSUE THREAD

**Issue by russmenum** [facebook/react-native#32870]
### New Version

0.62.2

### Old Version

0.62..

### Build Target(s)

iOS

### Output of `react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 11.6.2
    CPU: (6) x64 Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz
    Memory: 118.82 MB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.6.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 7.4.0 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: ~16.11.0 => 16.11.0 
    react-native: ~0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found

### Issue and Reproduction Steps

Upgraded to XCODE 13.2.1 from XCODE 12.x; now can not build for iOS.

ERROR
```

Showing Recent Errors Only
../node_modules/react-native/React/CxxBridge/RCTCxxBridge.mm:331:34: Cannot initialize a parameter of type 'NSArray<id<RCTBridgeModule>> *' with an rvalue of type 'NSArray<Class> *'

Showing Recent Errors Only
../node_modules/react-native/React/CxxBridge/RCTCxxBridge.mm:776:79: Cannot initialize a parameter of type 'NSArray<Class> *' with an lvalue of type 'NSArray<id<RCTBridgeModule>> *__strong'

Showing Recent Errors Only
../node_modules/react-native/React/CxxBridge/RCTCxxBridge.mm:827:69: Cannot initialize a parameter of type 'NSArray<id<RCTBridgeModule>> *' with an lvalue of type 'NSArray<Class> *__strong'

```

I patched the flipper error by commenting out
```
#add_flipper_pods!

# post_install do |installer|
  #   flipper_post_install(installer)
# end
```

But the ```find_and_replace()``` patch I can find for NSArray that was for 12.5 [here](https://github.com/facebook/react-native/issues/31412) is not working for XCODE 13.2.1.

The goal is to get this app to at least build again.

**Comment by yishunhuafeng** [comment]
1. Add below code on your Podfile.

```
post_install do |installer|
    ## Fix for XCode 12.5
    find_and_replace("../node_modules/react-native/React/CxxBridge/RCTCxxBridge.mm",
    "_initializeModules:(NSArray<id<RCTBridgeModule>> *)modules", "_initializeModules:(NSArray<Class> *)modules")
    find_and_replace("../node_modules/react-native/ReactCommon/turbomodule/core/platform/ios/RCTTurboModuleManager.mm",
        "RCTBridgeModuleNameForClass(module))", "RCTBridgeModuleNameForClass(Class(module)))")
end
```

2.Add below code on your end of Podfile

```
def find_and_replace(dir, findstr, replacestr)
  Dir[dir].each do |name|
      text = File.read(name)
      replace = text.gsub(findstr,replacestr)
      if text != replace
          puts "Fix: " + name
          File.open(name, "w") { |file| file.puts replace }
          STDOUT.flush
      end
  end
  Dir[dir + '*/'].each(&method(:find_and_replace))
end
```
3.Please update metro-react-native-babel-preset  to 0.59.0.

- package.json
```
  "devDependencies": {
    "@babel/core": "^7.16.5",
    "@babel/runtime": "^7.16.5",
    "metro-react-native-babel-preset": "^0.59.0",
  },
```

- update babel.config.js
```
module.exports = {
       presets: [['module:metro-react-native-babel-preset', {
            unstable_disableES6Transforms: true
        }]],
    };
```
4. npx react-native start --reset-cache

**Comment by 0906014109** [comment]
"react-native": "^0.57.5"
macos version：12.1
Xcode：13.2.1
遇到了楼上一样的问题，怎么解决？
<img width="879" alt="截屏2022-01-21 上午10 59 58" src="https://user-images.githubusercontent.com/38975345/150458159-942cca34-60ba-4f69-a217-7a8d00e490c2.png">

**Comment by WNemencha** [comment]
I'm having the same exact issue actually, RN 0.61, XCode 13

**Comment by reynerdev** [comment]
> @WNemencha After applying your script , I get   AppDelegate.h:13:48: Declaration of 'RCTBridgeDelegate' must be imported from module 'UMReactNativeAdapter.UMReactNativeEventEmitter' before it is required. I'm using react native 0.61. and Xcode 13 Any suggestion how to fix that?

**Comment by WNemencha** [comment]
@reynerdev not sure what the error is, here's some hint maybe => https://github.com/unimodules/react-native-unimodules/issues/119 ?

**Comment by reynerdev** [comment]
> @reynerdev not sure what the error is, here's some hint maybe => [unimodules/react-native-unimodules#119](https://github.com/unimodules/react-native-unimodules/issues/119) ?

![image](https://user-images.githubusercontent.com/58928047/184811760-008cd3b7-a05e-42df-af81-e2f0497480f5.png)

@WNemencha I got this error which is on the AppDelegate file. Thanks for replying

**Comment by WNemencha** [comment]
@reynerdev found this commit which seems to be applying a fix for that issue, maybe that can work for you? https://github.com/SConaway/rnfb-test/commit/c18f6ef60665309d2fcaaa2b2bce6a38056c48de#diff-38815643e00eb093e4d4a9babd3aabd4739ea2503025bdb7d1a5a7e48d757614R2
