### ISSUE TITLE
[Error: Netrwork Error] Image Upload Issue sometime it upload sometime it fails

### ISSUE THREAD

**Issue by atul-0113** [facebook/react-native#32879]
### Description

while uploading Image from Android i am facing an issue of Network Error very often sometimes it get uploaded sometime it fails..
I have tried to downgrade React Native version and it worked fine.

React native Version :  "react-native": "0.66.4",
Axios Version : "axios": "^0.24.0",

![Error code](https://user-images.githubusercontent.com/85641533/149284204-fe256aa9-d010-4d89-a9e8-4d8b57aa5728.png)

### Version

0.66.0 , 0.65.0

### Output of `npx react-native info`

![image](https://user-images.githubusercontent.com/85641533/149285251-bfb7ac29-782d-4837-a281-9e34409125a0.png)

### Steps to reproduce

1. create a POST request with Form-Data to upload Image(Android Only)
2. try to Upload Image 
3. it will get failed with Network Error most of the time

**Comment by flyskywhy** [comment]
[fixed `TypeError: Network request failed` when upload file to http not https with Android debug builds](https://github.com/facebook/react-native/issues/33217#issuecomment-1159844475)

**Comment by camboYY** [comment]
happen at first time

**Comment by pramancodes** [comment]
image upload using fetch fails only at first time while in subsequent requests it works, what could be the possible reason?
