### ISSUE TITLE
Unhandled JS Exception: Unexpected token Expected a ')' or a ' after a parameter declaration.

### ISSUE THREAD

**Issue by trabk1992** [facebook/react-native#32875]
### Description

after delete file yarn.lock and yarn install 
then build app , that error occur 
![error](https://user-images.githubusercontent.com/12109690/149080331-f59017df-b1f1-4725-b2ff-00f628638cdd.jpeg)

### Version

0.60.6

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 11.6
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Memory: 218.86 MB / 20.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.3.0 - /usr/local/bin/node
    Yarn: 1.22.17 - ~/Documents/RabilooWorkSpace/yakuodo_app_mobile/node_modules/.bin/yarn
    npm: 7.15.1 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7351085
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.6 => 0.60.6

### Steps to reproduce

step 1:  delete file yarn.lock and Podfile.lock 
step 2: run 'yarn install'
step 3:   run 'cd ios and Pod install'
step 4: build app 
after show splash screen , app show error 

![error](https://user-images.githubusercontent.com/12109690/149080395-80781e96-18a6-4485-bd9e-7f4fe17aaa08.jpeg)

**Comment by Satur-nity** [comment]
Facing the same error.

can anyone help?

**Comment by soleilpqd** [comment]
I'm working on project with RN 0.61.5 too.
Monday, I finished my task and did git commit at end of the day.
Yesterday, I added a dependency into package.json and did `npm install`, then got this error.
I tried git checkout to restore everything back to monday, delete lock file, `node_modules`, `~/npm`. Nothing could help resolve the error.
I got same error on other (unmodified) projects using RN 0.61.5.
Lost 2 days and my work is still same as monday :(

**Comment by LavanyaMacha2412** [comment]
I'm facing the same issue. Working with RN 0.61.5 
Monday i could build my app and everything was working as expected, But since yesterday morning i'm facing the same issue, no matter how many times i retry. Nothing could resolve it.

**Comment by LavanyaMacha2412** [comment]
Facing the same issue on RN 0.61.5

**Comment by joshua-davis-rose** [comment]
Same issue here with RN 0.63.4. Was working fine yesterday.

**Comment by JoseLuizJunior** [comment]
It's an error in react-native class -> node_modules/react-native/Libraries/Blob/URL.js

For some reason inside the class they are having to type as variables in a .js file
If you remove everything like typing, it works again.
 
Example:
To alter
append(key: string, value: string) -> append(key, value)

**Comment by joshua-davis-rose** [comment]
FWIW, the issue doesn't appear to be happening in RN 0.66.x

**Comment by joshua-davis-rose** [comment]
> It's an error in react-native class -> node_modules/react-native/Libraries/Blob/URL.js
> 
> For some reason inside the class they are having to type as variables in a .js file If you remove everything like typing, it works again.
> 
> Example: To alter append(key: string, value: string) -> append(key, value)

For 0.63.x at least, that file hasn't changed in almost 2 years so it shouldn't suddenly be breaking now. There must be another dependency that has changed recently that is causing this error.

**Comment by fabio-jreis** [comment]
> It's an error in react-native class -> node_modules/react-native/Libraries/Blob/URL.js
> 
> For some reason inside the class they are having to type as variables in a .js file If you remove everything like typing, it works again.
> 
> Example: To alter append(key: string, value: string) -> append(key, value)

doesn't work for me 😭

**Comment by joshua-davis-rose** [comment]
This appears related to babel, not react-native. I believe the issue is "@babel/traverse" 7.16.8: https://github.com/babel/babel/issues/14139

**Comment by joshua-davis-rose** [comment]
I finally got it to work by setting explicit versions and resolutions in my devDependencies and resolutions. I also needed to delete my node_modules and yarn.lock, but YMMV. I went back to 7.16.5 since it was the upgrade to 7.16.7 that I first saw the issue, but the latter may be safe. YMMV.

```
"devDependencies": {
    "@babel/core": "7.16.5",
    "@babel/preset-flow": "7.16.5",
    "@babel/runtime": "7.16.5"
}
"resolutions": {
    "@babel/traverse": "7.16.5"
}
````

**Comment by qcmoke** [comment]
Facing the same issue on RN 0.62.2

**Comment by quyle1222** [comment]
> I finally got it to work by setting explicit versions in my devDependencies and resolutions. I also needed to delete my node_modules and yarn.lock, but YMMV. I went back to 7.16.5 since it was the upgrade to 7.16.7 that I first saw the issue, but the latter may be safe.
> 
> ```
> "devDependencies": {
>     "@babel/core": "7.16.5",
>     "@babel/preset-flow": "7.16.5",
>     "@babel/runtime": "7.16.5"
> }
> "resolutions": {
>     "@babel/traverse": "7.16.5"
> }
> ```

Don't work for me

**Comment by trabk1992** [comment]
now, i fixed this issue . 
my solution : 
"devDependencies": {
    "@babel/core": "7.16.5",
    "@babel/preset-flow": "7.16.5",
    "@babel/runtime": "7.16.5",
    "@babel/traverse": "7.16.5"
}

**Comment by qianqiang2017** [comment]
Facing the same issue on RN 0.59.9

**Comment by kerm1it** [comment]
https://github.com/babel/babel/issues/14139#issuecomment-1011836916

**Comment by Satur-nity** [comment]
> [babel/babel#14139 (comment)](https://github.com/babel/babel/issues/14139#issuecomment-1011836916)

it works for me.

Thanks

**Comment by kurashiva11** [comment]
same error with 
     RN: 0.62.2
    "@babel/core": "7.16.5",
    "@babel/runtime": "7.16.5",
    "@babel/traverse": "7.16.5",
    "@babel/preset-flow": "7.16.5",
    "babel-jest": "24.9.0",
    "metro-react-native-babel-preset": "0.59.0"
    
I have uninstalled node_modules, cleaned Gradle build, re-installed everything and started the app. but still, it is showing the same error.

**Comment by kerm1it** [comment]
> same error with RN: 0.62.2 "@babel/core": "7.16.5", "@babel/runtime": "7.16.5", "@babel/traverse": "7.16.5", "@babel/preset-flow": "7.16.5", "babel-jest": "24.9.0", "metro-react-native-babel-preset": "0.59.0"
> 
> I have uninstalled node_modules, cleaned Gradle build, re-installed everything and started the app. but still, it is showing the same error.

try `yarn start --reset-cache` to start app，maybe the error build cache is exist.

**Comment by fabio-jreis** [comment]
> [babel/babel#14139 (comment)](https://github.com/babel/babel/issues/14139#issuecomment-1011836916)

works here!

**Comment by nicolo-ribaudo** [comment]
If the solution in the Babel repository doen't work for someone, we will need a repository that we can use to reproduce the bug.

**Comment by milkcask** [comment]
Drop-in replacement `metro-react-native-babel-preset`, and running `npx react-native start --reset-cache` work for me.

**Comment by Hello-Alex-Cheng** [comment]
babel.config.js

```js
presets: [[
    'module:metro-react-native-babel-preset',
    {
      unstable_disableES6Transforms: true
    }
  ]],
```

**Comment by Hello-Alex-Cheng** [comment]
change your babel.config.js file

```js
presets: [[
    'module:metro-react-native-babel-preset',
    {
      unstable_disableES6Transforms: true
    }
]],
```

**Comment by ahmedelsayed11** [comment]
> Monday

What to make in that file ?

**Comment by hzburki** [comment]
None of the above fixes work for me :( 

**package.json**
```json
    "react": "16.8.6",
    "react-native": "0.60.3",
    "devDependencies": {
        "@babel/core": "^7.16.5",
        "@babel/preset-flow": "7.16.5",
        "@babel/runtime": "^7.16.5",
        "metro-react-native-babel-preset": "^0.59.0",
    },
    "resolutions": {
        "@babel/traverse": "7.16.7"
     },
```

**babel.config.js**
```js
module.exports = {
  presets: [['module:metro-react-native-babel-preset', {
       unstable_disableES6Transforms: true
   }]],
};
```

**Comment by SyedSaifAli** [comment]
> change your babel.config.js file
> 
> ```js
> presets: [[
>     'module:metro-react-native-babel-preset',
>     {
>       unstable_disableES6Transforms: true
>     }
> ]],
> ```

Not working with this change as well.

**Comment by HeyShinner** [comment]
> [babel/babel#14139 (comment)](https://github.com/babel/babel/issues/14139#issuecomment-1011836916)

It works!!

**Comment by bsdaoquang** [comment]
> It's an error in react-native class -> node_modules/react-native/Libraries/Blob/URL.js
> 
> For some reason inside the class they are having to type as variables in a .js file If you remove everything like typing, it works again.
> 
> Example: To alter append(key: string, value: string) -> append(key, value)

Thank you so much, it fixed this error

**Comment by kelokchan** [comment]
I can confirm after bumping `metro-react-native-babel-preset` to `0.59.0` and running `npx react-native start --reset-cache` everything works again
