### ISSUE TITLE
I keep getting the old version of the app when running xcode app

### ISSUE THREAD

**Issue by es6Test** [facebook/react-native#3287]
I have run `npm start` in my react native project (based on the starter project in the cli) but I am still getting the initial version of the app when the simulator runs.

How to fix?

**Comment by brentvatne** [comment]
Hi there! Please post this to StackOverflow, this is not an actual bug but likely just something wrong with your configuration. For example, maybe you switched your AppDelegate.m to use the bundled JS rather than point to the development server. Good luck!

**Comment by es6Test** [comment]
Ok thanks, the reason I posted on here was because I didn't change those things, I expected the default template the cli provided would have updated the program itself by default. I will try again with a fresh project.
