### ISSUE TITLE
FlatList with multiple columns

### ISSUE THREAD

**Issue by Majiedo** [facebook/react-native#32885]
### Description

Hey i was trying to make reanimated layout animation with flatlist it works just fine with numColumns 1 but if i try 2 or more than 1 it doesn't work anymore when i delete item or add new one the whole flatlist re render which not happening when numColumns set to 1

I think the problem is when the numColumns > 1 it re render when the data changes? 

### Version

0.64.3

### Output of `npx react-native info`

System:
    OS: macOS 12.1
    CPU: (8) x64 Apple M1
    Memory: 41.59 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.13 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 13.0/13A233 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: ^0.64.3 => 0.64.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

https://user-images.githubusercontent.com/70872870/149495472-d8cae651-1405-4cb8-9fe8-7eae03bd3bf9.mov

https://user-images.githubusercontent.com/70872870/149495481-9a727401-421d-4043-a02f-242b50f3d497.mov

### Snack, code example, screenshot, or link to a repository

Flatlist -:

```
<Animated.FlatList
          key={columns ? "oneRow" : "twoRow"}
          data={Tasks.data}
          numColumns={columns ? 1 : 2}
          showsVerticalScrollIndicator={false}
          itemLayoutAnimation={Layout}
          style={styles.Wrapper}
          renderItem={({ item, index }) => (
            <List
              key={index}
              index={index}
              item={item}
              DeleteHanlder={DeleteHanlder}
            />
          )}
        />
```

item itself -:

```
<Animated.View
        entering={FadeInDown.springify().delay(index * 150)}
        exiting={FadeOutUp.springify()}
        .....

```

**Comment by Sven2219** [comment]
I don't see that you have define keyExtractor property. If adding keyExtractor doesn't help, try wrapping your List component with React.memo()
Example: `export default React.memo(List,(curr,next)=>curr.index===next.index)`

**Comment by Majiedo** [comment]
> I don't see that you have define keyExtractor property. If adding keyExtractor doesn't help, try wrapping your List component with React.memo() Example: `export default React.memo(List,(curr,next)=>curr.index===next.index)`

thank you for responding!

i already define the keyExtractor property but still didn't work, but i don't know what you mean by wrapping my List component with react.memo()? can you provide an full example?

**Comment by Sven2219** [comment]
You can extract List component into another file and then export it in the following way export default React.memo(List,(curr,next)=>curr.index===next.index). 
This will definitely prevent your items from being re-created unnecessarily.
Read more about how it works [here](https://ordinarycoders.com/blog/article/react-memo)
If this doesn't help please create a repository on github or create example on code sandbox so I can investigate it. 

Simple example would be

```
import React from 'react'
const List = ({index}) => {
  return (
    <Animated.View
      entering={FadeInDown.springify().delay(index * 150)}
      exiting={FadeOutUp.springify()}
      .......
    />
  );
};

export default React.memo(List, (curr, next) => curr.index === next.index)

```

**Comment by axelmarciano** [comment]
Same problem here !

**Comment by cortinico** [comment]
Closing as stale
