### ISSUE TITLE
Example applications crashing on android 

### ISSUE THREAD

**Issue by seand88** [facebook/react-native#3289]
Tested With Device Nexus 6, running android lollipop
Tested with Emulator Nexus 5, running lollipop

Followed instructions to run movie app example. Installs on device fine.
When loading the js bundle for android the device crashes stating "Unfortunately, MoviesApp has stopped."

Same exact scenario for UIExplorer Example

Request to packager as follows.

[1:12:39 PM] <START> request:/Examples/Movies/MoviesApp.android.bundle?platform=android
[1:12:39 PM] <START> find dependencies
[1:12:40 PM] <END>   find dependencies (448ms)
[1:12:40 PM] <START> transform
transforming [========================================] 100% 329/329
[1:12:40 PM] <END>   transform (95ms)
[1:12:40 PM] <END>   request:/Examples/Movies/MoviesApp.android.bundle?platform=android (564ms)
::ffff:127.0.0.1 - - [Thu, 08 Oct 2015 18:12:41 GMT] "GET /flow/ HTTP/1.1" 404 - "-" "okhttp/2.4.0"

**Comment by southerneer** [comment]
Seeing the same over here. Testing on an emulated Nexus 5 with API 23 on Intel Atom x86. And here's the red screen stack trace when I try to run the Movies example app...

![screen shot 2015-10-09 at 1 16 14 pm](https://cloud.githubusercontent.com/assets/3681859/10404496/fd7486e8-6e87-11e5-97b0-0fa037795137.png)

**Comment by ide** [comment]
Movies app works in master when building from source. We should have this fixed in the next release.
![screenshot_2015-10-09-13-44-03](https://cloud.githubusercontent.com/assets/379606/10405267/abef0b7c-6e8c-11e5-815b-4971fed3f38e.png)

**Comment by flyher** [comment]
@ide
i'm looking forware to the new version.
