### ISSUE TITLE
How to use Chrome Developer Tools to debug?

### ISSUE THREAD

**Issue by KJlmfe** [facebook/react-native#329]
I want to see console.log data in chrome and debug step by step.

**Comment by alisnic** [comment]
Same here, saw the debugger on the main site screenshots, but was unable to find how to setup it.

**Comment by zetachang** [comment]
`Ctrl + Cmd+ Z` to toggle the menu. You will find debug option there.

**Comment by danharper** [comment]
Didn't know about that menu - thanks.

`Cmd + D` will open debugger too.

**Comment by KJlmfe** [comment]
thanks @zetachang

**Comment by xiongjiabin** [comment]
please check http://stackoverflow.com/questions/29314839/cant-launch-chrome-devtools-in-ios-simulator,
fix my debug problem.
