### ISSUE TITLE
Apple M1: Folly errors "can't modify frozen String (FrozenError)" 

### ISSUE THREAD

**Issue by mjstelly** [facebook/react-native#32908]
### Description

# Report

### System info
Important info: 
```
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro18,1
  Chip:	Apple M1 Pro
```

## What did you do?

Run `pod install` from `/ios` folder of my react native project

## What did you expect to happen?

```
Fetching podspec for `Folly` from `../node_modules/react-native/third-party-podspecs/Folly.podspec`
Installing Folly (2018.10.22.00)
```

## What happened instead?
```
Fetching podspec for `Folly` from `../node_modules/react-native/third-party-podspecs/Folly.podspec`
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface/error_report.rb:34:in `force_encoding': can't modify frozen String (FrozenError)
```

## Stack

```
   CocoaPods : 1.11.2
        Ruby : ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.x86_64-darwin21]
    RubyGems : 3.0.3.1
        Host : macOS 12.0.1 (21A559)
       Xcode : 13.2.1 (13C100)
         Git : git version 2.32.0 (Apple Git-132)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
platform :ios, '11.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

install! 'cocoapods',
         :deterministic_uuids => false

target 'App' do
  # Pods for App
  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/React/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'AppCenter/Push'
  pod 'AppCenter/Crashes'
  pod 'AppCenter/Analytics'
  pod 'AppCenterReactNativeShared'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  target 'AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  use_native_modules!
end

target 'App-tvOS' do
  # Pods for App-tvOS

  target 'App-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

## Project that demonstrates the issue
relates only to installation

### Version

0.64.1

### Output of `npx react-native info`

System:
    OS: macOS 12.0.1
    CPU: (10) x64 Apple M1 Pro
    Memory: 1.16 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.1/bin/yarn
    npm: 6.14.15 - ~/Documents/sams-fresh-app-reactnative/node_modules/.bin/npm
    Watchman: 2022.01.03.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7935034
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.13 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

From the project root, `cd ios && pod install`

**Comment by mjstelly** [comment]
Since npm isn't installed globally, is the `npmPackages` output for `react-native info` valid?

**Comment by JovialDeveloper** [comment]
Happening for me on non-M1 device also.

**Comment by kunalketanshah** [comment]
I can see the same error on a non-M1 device.

**Comment by cyberdude** [comment]
Getting this error too (m1)

**Comment by knlshh** [comment]
I resolved this on a non-M1 Mac by replacing:

```
pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
```

with 

```
pod 'RCT-Folly', :podspec => "../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec"
```

Depending on your React Native version (mine is the latest i.e. `0.67.1`), the `Podfile` needs to be updated. If you're following https://reactnative.dev/docs/integration-with-existing-apps like me, the `Configuring CocoaPods dependencies` section mentions that "The `Podfile` version changes depending on your version of `react-native`". What I did was create a new React Native project built for `0.67.1` and saw its `Podfile` and cherry-picked whatever was needed into my existing iOS project's `Podfile`.

Hope this helps!

**Comment by ViktorLnt** [comment]
I had the same issue, and solved it like @knlshh .
I would like to add that I did the cherry-picking part looking at my node_modules/react-native/third-party-podsecs structure.

**Comment by azazel404** [comment]
this issue already solve ?
because i get same issue like this
using Macbook M1

**Comment by azazel404** [comment]
> I resolved this on a non-M1 Mac by replacing:
> 
> ```
> pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
> ```
> 
> with
> 
> ```
> pod 'RCT-Folly', :podspec => "../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec"
> ```
> 
> Depending on your React Native version (mine is the latest i.e. `0.67.1`), the `Podfile` needs to be updated. If you're following https://reactnative.dev/docs/integration-with-existing-apps like me, the `Configuring CocoaPods dependencies` section mentions that "The `Podfile` version changes depending on your version of `react-native`". What I did was create a new React Native project built for `0.67.1` and saw its `Podfile` and cherry-picked whatever was needed into my existing iOS project's `Podfile` and then continued from the `pod install` step.
> 
> Hope this helps!

im try but , make a new , see the picture
<img width="1001" alt="Screen Shot 2022-02-25 at 22 57 03" src="https://user-images.githubusercontent.com/25822411/155746465-d359c4ea-5a79-4b21-9abe-95253a406f46.png">

**Comment by zhuliminl** [comment]
You may need to change your ios project fold name to ios, not you target name! it worked for me.

**Comment by shivam-rallyhealth** [comment]
Solved it by the suggestion given by @knlshh. However I didn't see any such thing while going to https://react-native-community.github.io/upgrade-helper/?from=0.68.2&to=0.69.0-rc.2 

All I see in the podfile is totally dirrect files: 
```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.4'
install! 'cocoapods', :deterministic_uuids => false

target 'RnDiffApp' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'RnDiffAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
```

**Comment by iMateo** [comment]
Well, this works for me:
Reinstall (update) Cocoapods.
`sudo gem install cocoapods`

**Comment by rahulpahuja** [comment]
Try sudo gem update xcodeproj or sudo gem update for all gems. Worked for me.

Original Blogpost from https://stackoverflow.com/questions/74137282/pod-init-error-force-encoding-cant-modify-frozen-string-frozenerror-at

**Comment by rahulpahuja** [comment]
i think this would work and then you can close this issue
