### ISSUE TITLE
Help with Bug, error message -> ReferenceError: Can't find variable: document 

### ISSUE THREAD

**Issue by brysonbw** [facebook/react-native#32912]
### Description

I'm trying to run my project but getting this error: . I tried searching the whole folder but can't find any use of document. What is causing this issue?

### Version

0.63.2

### Output of `npx react-native info`

System:
    OS: macOS 12.1
    CPU: (4) x64 Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz
    Memory: 2.61 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.2.0 - /usr/local/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 7.13.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
    Python: 2.7.18 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.2 => 17.0.2
    react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2
    react-native-macos: Not Found
  npmGlobalPackages:
    react-native: Not Found

### Steps to reproduce

N/A

**Comment by cortinico** [comment]
> I'm trying to run my project but getting this error: . I tried searching the whole folder but can't find any use of document. What is causing this issue?

What is the error message? Where are you seeing it? Could you provide a reproducer?
