### ISSUE TITLE
[0.67.1] Switch set thumbColor from color to undefined throws error

### ISSUE THREAD

**Issue by coolguy001tv** [facebook/react-native#32913]
### Description

When using Switch component, if I set thumbColor from any color like 'yellow' to undefined, there is a red screen error:
`
Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
`
I found that if set thumbColor from any color to color, it's ok, and   if set thumbColor to undefined(never change it), it's still ok.

### Version

"react-native": "0.67.0-rc.6" / "0.67.1" 
(0.67.0 is ok)

### Output of `npx react-native info`

System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 Intel(R) Core(TM) i5-10500 CPU @ 3.10GHz
    Memory: 3.67 GB / 15.83 GB
  Binaries:
    Node: 12.22.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7678000
    Visual Studio: Not Found
  Languages:
    Java: 11.0.10 - C:\Program Files\Android\Android Studio\jre\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.67.0-rc.6 => 0.67.0-rc.6
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

just using the latest rn like `npx react-native init fatboy --version 0.67.0-rc.6`, then using the code below, when click the Switch will occur the error
```js
import React,{useState} from 'react';
import {
  SafeAreaView,
    Switch,
} from 'react-native';


const App = () => {

  const [v, setV] = useState(true);

  return (
    <SafeAreaView>

      <Switch
          thumbColor={v?'yellow':undefined}
          value={v} onValueChange={()=>setV(value=>!value)}/>
    </SafeAreaView>
  );
};
export default App;
```

### Snack, code example, screenshot, or link to a repository

here's the error screen.
![e48ad0652b951f582e2d6020def89a3](https://user-images.githubusercontent.com/936825/149913651-3758faea-0c25-4d3b-97b5-eef22ceb3bb7.jpg)

And besides, i create a snack [here](https://snack.expo.dev/@coolguy/rn-switch-test), but the result differs.
In expo, when set thumbColor from yellow to undefined, it shows no error but it's still not right, it shows transparent button.( The right display is that when using undefined, thumbColor should be the default system color circle button).

**Comment by coolguy001tv** [comment]
After upgrading to 0.67.0, this bug disappears, so I close it.

**Comment by coolguy001tv** [comment]
Sadlly enough, this is happening in 0.67.1, so I reopen it.

**Comment by arpitBhalla** [comment]
Facing similar issue
