### ISSUE TITLE
Direct local hermes-release.aar file dependencies are not supported when building an AAR

### ISSUE THREAD

**Issue by ikimiler** [facebook/react-native#32919]
### Description

Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be packaged in the resulting AAR. Previous versions of the Andr
oid Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The following direct local .aar file dependencies of the :ReactNative project caused this error: D:\works\HAssistant\HzgClientHUAZHU\node_modules\hermes-engine\android\hermes-release.aar

### Version

0.62.2

### Output of `npx react-native info`

System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 AMD Ryzen 5 PRO 4650G with Radeon Graphics
    Memory: 3.21 GB / 15.38 GB
  Binaries:
    Node: 14.17.5 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.11 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.14 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6858069
    Visual Studio: Not Found
  Languages:
    Java: 1.8.0_242-release
    Python: 3.10.1
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

the build.gradle:

if (enableHermes) {
        def hermesPath = "../../node_modules/hermes-engine/android/";
        debugImplementation files(hermesPath + "hermes-debug.aar")
        releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
        implementation 'org.webkit:android-jsc:+'
    }

**Comment by cortinico** [comment]
> Direct local .aar file dependencies are not supported when building an AAR.

You should not need to bundle `hermes-release.aar` if you're trying to build an AAR (a library). It should be up to final consumer (the app) to decide which JS engine to use.

Please let me know if I'm missing something on your setup

**Comment by zabojad** [comment]
@wilsolutions I have several modules with aar files and I run into this issue. Did you find a way to include aar files in react native modules without getting this issue?

By the way, I'm having it only when assembling the release bundle, not when running `npx react-native run-android`...

**Comment by cortinico** [comment]
Please check my answer here: 
- https://github.com/facebook/react-native/issues/33062#issuecomment-1032706806

> However what about a React Native Module that contains 2 .arr libs and it fails if we pass the --deviceId flag?
> Would you have any insight about this?

I don't understand how the `--deviceId` flag is related to this in any form.

**Comment by wilsolutions** [comment]
> @wilsolutions I have several modules with aar files and I run into this issue. Did you find a way to include aar files in react native modules without getting this issue?
> 
> By the way, I'm having it only when assembling the release bundle, not when running `npx react-native run-android`...

Hey, I needed to put this on hold given other priorities but I will need to revisit at certain point before releasing the App.

Have you found a solution?

Ty

**Comment by cortinico** [comment]
> Hey, I needed to put this on hold given other priorities but I will need to revisit at certain point before releasing the App.

I'm closing this as it's stale + the issue you're havign @wilsolutions it's different from the root issues. Feel free to open a new issue with reproducer once you have time 👍
