### ISSUE TITLE
npx react-native init AwesomeProject

### ISSUE THREAD

**Issue by LZHD** [facebook/react-native#32927]
### Description

Debugging in development mode is normal. After packaging, the installation and startup flash back.

Update from 0.66.4 to 0.67.0 had the same problem.

### Version

0.67.0

### Output of `npx react-native info`

System:
    OS: Linux 4.15 Ubuntu 16.04.7 LTS (Xenial Xerus)
    CPU: (4) x64 Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz
    Memory: 1.30 GB / 7.70 GB
    Shell: 4.3.48 - /bin/bash
  Binaries:
    Node: 12.22.7 - ~/.nvm/versions/node/v12.22.7/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v12.22.7/bin/yarn
    npm: 8.3.0 - ~/.nvm/versions/node/v12.22.7/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 28, 29, 30, 31
      Build Tools: 23.0.1, 27.0.3, 28.0.3, 29.0.2, 30.0.2, 31.0.0
      System Images: android-29 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 1.8.0_201 - /home/lzhd/software/jdk1.8.0_201/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.0 => 0.67.0 
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

```sh
npx react-native init AwesomeProject
cd AwesomeProject
cd android && ./gradlew assembleRelease
```
After the package is successfully installed, the application starts to flash back.

**Comment by LZHD** [comment]
The test phone is Redmi Note 8 Pro

**Comment by cortinico** [comment]
> After packaging, the installation and startup flash back

Can I ask you to clarify what "flash back" means in this context?

**Comment by kelset** [comment]
I can confirm that this issue is reproducible on a fresh project - there's also another issue opened about this that has a few more insights. So let's move the conversation there: https://github.com/facebook/react-native/issues/32928
