### ISSUE TITLE
Library not found for -lFolly

### ISSUE THREAD

**Issue by Yandamuri** [facebook/react-native#32929]
### Description

I am trying to migrate from `"react-native": "0.63.2"` to `"react-native": "0.64.3"`. I am facing following error,

<img width="894" alt="150070051-6845a17b-4fad-457a-822a-c22c205ede5c" src="https://user-images.githubusercontent.com/31983789/150175488-52e5759c-1511-4ecb-a82f-76f314f3cec0.png">

As a part of this migration I have done following upgrade too

      from  "react":  "16.13.1"  to "react": "17.0.1"
       

### Version

"react-native": "0.64.3"

### Output of `npx react-native info`

        System:
            OS: macOS 11.6
            CPU: (8) x64 Apple M1
            Memory: 24.38 MB / 8.00 GB
            Shell: 5.8 - /bin/zsh
        Binaries:
             Node: 14.0.0 - /usr/local/bin/node
            Yarn: Not Found
            npm: 6.14.4 - /usr/local/bin/npm
            Watchman: Not Found
       Managers:
           CocoaPods: 1.11.2 - /usr/local/bin/pod
       SDKs:
           iOS SDK:
           Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
           Android SDK: Not Found
      IDEs:
            Android Studio: 4.2 AI-202.7660.26.42.7351085
            Xcode: 13.0/13A233 - /usr/bin/xcodebuild
      Languages:
            Java: 11.0.10 - /usr/bin/javac
      npmPackages:
           @react-native-community/cli: Not Found
           react: 17.0.1 => 17.0.1 
           react-native: 0.64.3 => 0.64.3 
           react-native-macos: Not Found
      npmGlobalPackages:
           *react-native*: Not Found

### Steps to reproduce

Please do the migration as shown below,

 from `"react-native": "0.63.2"` to `"react-native": "0.64.3"`

  from  `"react":  "16.13.1"`  to `"react": "17.0.1"`

**Comment by aysberna** [comment]
I faced with the same problem upgrade from "react-native": "0.60.1" to "react-native": "0.66.4" and I deleted libFolly.a file from Xcode>Targets>General and cleaned DerivedData, run again. Maybe you can face with other problems but if you don't use folly file in your pods it will work. I hope it works for you too.

<img width="676" alt="Screen Shot 2022-01-21 at 10 55 37" src="https://user-images.githubusercontent.com/4121960/150512311-21c12738-1613-4855-8962-7de7de6e4bfe.png">

**Comment by Yandamuri** [comment]
@aysberna Than you for your response.

I do not use `Folly` in my `pod file` and there is file with name `libFolly.a` in `Frameworks, Libraries, and Embedded Content`. But still I am getting this error.

How can I get rid of this error? OR At least may I know the root cause behind this issue?

**Comment by aysberna** [comment]
> @aysberna Than you for your response.
> 
> I do not use `Folly` in my `pod file` and there is file with name `libFolly.a` in `Frameworks, Libraries, and Embedded Content`. But still I am getting this error.
> 
> How can I get rid of this error? OR At least may I know the root cause behind this issue?

I don't know what it does but I guess old version of projects has needed Folly file but new version not. So I deleted libFolly.a from targets (`Frameworks, Libraries, and Embedded Content`) and it solved. You can try to delete `libFolly.a`. Also you can delete Xcode DerivedData and reopen your xcworkspace file and build again.

**Comment by Yandamuri** [comment]
@aysberna Sorry it's my typo...There is no file with name `libFolly.a` in `Frameworks, Libraries, and Embedded Content`.

Is there any other area(or folders) where I need to delete files related to `Folly`?

**Comment by aysberna** [comment]
> @aysberna Sorry it's my typo...There is no file with name `libFolly.a` in `Frameworks, Libraries, and Embedded Content`.
> 
> Is there any other area(or folders) where I need to delete files related to `Folly`?

No problem. If you have Folly folder in your project> ios> Target Support Files you can delete it. If that doesn't work, I don't know what to do, I am sorry.

**Comment by Yandamuri** [comment]
@aysberna I didn't find any `Folly` folders in this location => ` project> ios> Target Support Files`. But I found inside `pods` folder. Even though I delete them, they are getting created after `pod install`. 

Is it possible to prevent them from not getting created when `pod install` is done?

**Comment by Yandamuri** [comment]
I found solution [here](here)
