### ISSUE TITLE
APK size got increased almost double after upgrading to RN 0.66.4

### ISSUE THREAD

**Issue by qilovehua** [facebook/react-native#32933]
### Description

I just migrate RN from 0.61.5 to 0.66.4, and find APK size almost double.
There are much more *.so files than 0.61.5

Analyze APK 0.61.5:
<img width="907" alt="0 61 5" src="https://user-images.githubusercontent.com/12076175/150331635-c977ff46-0f48-495c-8907-258e0bd05645.png">

Analyze APK 0.66.4:
![0 66 4-f](https://user-images.githubusercontent.com/12076175/150331711-3f9c99e2-2def-4780-a6e4-14dfe8c232da.jpeg)

### Version

0.66.4

### Output of `npx react-native info`

System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 60.55 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.22.8 - ~/.nvm/versions/node/v12.22.8/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 8.3.0 - ~/react/app/node_modules/.bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.1, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 23, 28, 30, 31
      Build Tools: 23.0.1, 28.0.3, 29.0.3, 30.0.2
      System Images: android-27 | Google Play Intel x86 Atom, android-28 | Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7935034
    Xcode: 12.1/12A7403 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_201 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.4 => 0.66.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

./gradlew assembleRelease

**Comment by mathews-p** [comment]
If Gradle build tools version 4 or higher, adding android:extractNativeLibs="true" to application as per android documentation, may solve the issue. This will reduce the apk size.

https://developer.android.com/studio/releases/gradle-plugin#extractNativeLibs

**Comment by qilovehua** [comment]
> If Gradle build tools version 4 or higher, adding android:extractNativeLibs="true" to application as per android documentation, may solve the issue. This will reduce the apk size.
> 
> https://developer.android.com/studio/releases/gradle-plugin#extractNativeLibs

It works, thank you very much.
