### ISSUE TITLE
Flatlist width height onLayout, incorrectly calculated?

### ISSUE THREAD

**Issue by tamis-laan** [facebook/react-native#32943]
### Description
Not sure if this is a bug, I'm trying to build a vertical carousel that can be inserted as a child in any view and will scale accordingly. To do this I'm using the `onLayout` prop to derive the width and height of the carousel and pass this onto the children:

``` javascript
<FlatList
	style={styles.FlatList}
	contentContainerStyle={styles.FlatListContainer}
	onLayout={ e => {
		const {width,height} = e.nativeEvent.layout
		setWidth(width)
		setHeight(height)
		console.log(width,height)
	}}
        data={myData}
        renderItem={ ({item}) => (<Item style={{width,height}} data={item} />) }
/>
```
I'm using the following style to fit the `FlatList` component inside it's parent component:

``` javascript
// Styles
const styles = StyleSheet.create({
	FlatList: {
		flexGrow:1,
	},
	FlatListContainer: {
		flex:1,
	},
})
```
The problem is that the derived `Item` is set to large causing the carousel to be misaligned. If however is set the width and height of the `FlatList` to be 200x200 then everything works fine.

### Version

42.0.0

### Output of `npx react-native info`

  Binaries:
    Node: 16.11.1 - /tmp/yarn--1642800594989-0.03596368942784878/node
    Yarn: 1.22.17 - /tmp/yarn--1642800594989-0.03596368942784878/yarn
    npm: 8.1.3 - /usr/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  Languages:
    Java: 17.0.1 - /usr/bin/javac
    Python: 3.9.7 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

See description above

**Comment by a-eid** [comment]
you might wanna supply a `getItemLayout` prop to your `FlatList`.

**Comment by tamis-laan** [comment]
> you might wanna supply a `getItemLayout` prop to your `FlatList`.

Could you elaborate a little bit more?

**Comment by tamis-laan** [comment]
If I print out the information derived from `onLayout`:
``` javascript
onLayout={ e => {
    console.log(e.nativeEvent.layout)
}}
```
I get back:
``` json
{
  "height": 843.6363525390625,
  "width": 392.7272644042969,
  "x": 0,
  "y": 0,
}
```
This is wrong given that the `FlatList` component is underneath another component so I would expect `x > 0`.
Also a height of `843.6363525390625` is to big.
