### ISSUE TITLE
Does react-native support jdk 17?

### ISSUE THREAD

**Issue by kartik30369** [facebook/react-native#32948]
### Description

So i using the jdk 17 with react native and it's not working out. And I was told by someone that jdk 17 is not supported. This is the error it gives me:

`
> Task :app:processDebugMainManifest FAILED
11 actionable tasks: 2 executed, 9 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugMainManifest'.
> Unable to make field private final java.lang.String java.io.File.path accessible: module java.base does not "opens java.io" to unnamed module @7ec6bc9b

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights. 

* Get more help at https://help.gradle.org

BUILD FAILED in 20s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

* What went wrong:
Execution failed for task ':app:processDebugMainManifest'.
> Unable to make field private final java.lang.String java.io.File.path accessible: module java.base does not "opens java.io" to unnamed module @7ec6bc9b

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights. 
* Get more help at https://help.gradle.org

BUILD FAILED in 20s

    at makeError (C:\Users\karti\Desktop\ShoppingList\node_modules\execa\index.js:174:9)
    at C:\Users\karti\Desktop\ShoppingList\node_modules\execa\index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (C:\Users\karti\Desktop\ShoppingList\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid    at async Command.handleAction (C:\Users\karti\Desktop\ShoppingList\node_modules\@react-native-community\cli\build\index.js:192:9)
info Run CLI with --verbose flag for more details.
`

### Version

0.67.1

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.19043
    CPU: (4) x64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
    Memory: 647.66 MB / 7.71 GB
  Binaries:
    Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 30, 31, 32
      Build Tools: 29.0.2, 30.0.2, 30.0.3, 32.0.0
      System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: Not Found
  Languages:
    Java: 17.0.1 - C:\Program Files\Common Files\Oracle\Java\javapath\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.67.1 => 0.67.1
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

install react-native and jdk 17.
create a new project and launch android emulator.
run react-native run-android.

**Comment by Ppang0405** [comment]
No, because Android development do not support JDK 17 yet. JDK 11 is latest supported in Android Studio version >= 4.2. https://developer.android.com/studio/releases#4.2-bundled-jdk-11

**Comment by cortinico** [comment]
The recommended version of JDK to use is 11 (see https://reactnative.dev/docs/next/environment-setup)

> So i using the jdk 17 with react native and it's not working out. And I was told by someone that jdk 17 is not supported. This is the error it gives me:

Technically you could JDK 17 to build an Android App from the command line and still produce an artifact that is JDK11 compatible. However, you need to be on Gradle 7.3.x. The upcoming version of React Native (0.68.x) will ship with that Gradle version so you should be able to create a new project from there and run it with JDK 17 out of the box.

If you already have a project, you would need to update the Gradle version in your `./android/gradle/wrapper/gradle-wrapper.properties` file in order for it to be executed on JDK 17.

**Comment by marcpope** [comment]
I am using Java 17 on a M1 Mac Mini, here's how I got it to work:

**in android/gradle/wrapper change the distributionUrl to v7.3:**
`distributionUrl=https\://services.gradle.org/distributions/gradle-7.3-all.zip`

**in android/gradle.properties, add this line at the end:**
`org.gradle.jvmargs=-Xmx1536M --add-exports=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-exports=jdk.unsupported/sun.misc=ALL-UNNAMED`

after this, you can run: `npx react-native run android`

Here's my info for reference:

```
info Fetching system and libraries information...
System:
    OS: macOS 12.0.1
    CPU: (8) x64 Apple M1
    Memory: 32.70 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.0.1 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 2021.11.08.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 29, 30, 31
      Build Tools: 30.0.2, 32.0.0, 32.1.0
      System Images: android-29 | ARM 64 v8a, android-29 | Intel x86 Atom_64, android-29 | Google Play ARM 64 v8a, android-31 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8139111
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.4 => 0.66.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by xAirx** [comment]
Hi Mark, Im facing the same issue as you, I would like to hear if I can contact you on discord or talk to you somehow, I would like to know which version of the android gradle you are using and more.
