### ISSUE TITLE
ERROR  Invariant Violation: Module AppRegistry is not a registered callable module ( React native V6)

### ISSUE THREAD

**Issue by cmschandan** [facebook/react-native#32952]
### Description

 ERROR  TypeError: undefined is not an object (evaluating 'Object.keys(o)')
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.

### Version

0.67

### Output of `npx react-native info`

BUNDLE  ./index.js 

 ERROR  TypeError: undefined is not an object (evaluating 'Object.keys(o)')
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
[Info] Stopping Packager

### Steps to reproduce

Whenever i am adding StackNavigator code in my App.js then showing above issue..
I tried all possible solution to resolve it. but it's showing same bug again and again.

### Snack, code example, screenshot, or link to a repository

**App.js** 
`import {NavigationContainer} from '@react-navigation/native';
import React from 'react';
import 'react-native-gesture-handler';
import {createStackNavigator} from 'react-navigation-stack';
import Home from './Home';

const Stack = createStackNavigator();
const SectionListBasics = () => {
  return (
    <>
      <NavigationContainer>
        <Stack.Navigator initialRouteName="Home" headerMode="Screen">
          <Stack.Screen
            name="Home"
            options={{
              headerShown: false,
            }}>
            {props => <Home {...props} username="Sports Fan" />}
          </Stack.Screen>
        </Stack.Navigator>
      </NavigationContainer>
    </>
  );
};

export default SectionListBasics;
`

**package.json**
`{
  "name": "AwesomeProject",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-community/masked-view": "^0.1.11",
    "@react-navigation/bottom-tabs": "^6.0.9",
    "@react-navigation/drawer": "^6.1.8",
    "@react-navigation/native": "^6.0.6",
    "react": "17.0.2",
    "react-native": "0.67.1",
    "react-native-gesture-handler": "^2.2.0",
    "react-native-reanimated": "^2.2.4",
    "react-native-safe-area-context": "^3.3.2",
    "react-native-screens": "^3.10.2",
    "react-native-vector-icons": "^9.0.0",
    "react-navigation-stack": "^2.10.4"
  },
  "devDependencies": {
    "@babel/core": "7.16.10",
    "@babel/runtime": "7.16.7",
    "@react-native-community/eslint-config": "2.0.0",
    "babel-jest": "26.6.3",
    "eslint": "7.14.0",
    "jest": "26.6.3",
    "metro-react-native-babel-preset": "0.66.2",
    "react-test-renderer": "17.0.2"
  },
  "jest": {
    "preset": "react-native"
  }
}
`

**Comment by phanithken** [comment]
This is issue is mostly happen when `node_modules` folder has been changed by installing new library or some sort of reason. Please try removing cache and node_modules and doing `yarn install` or `npm install` again

```bash
$ npx react-native-clean-project
$ yarn install
```

**Comment by puniker** [comment]
Try to add this line in the file where you add the navigation:
```js
import * as React from 'react';
```
this has worked for me.

**Comment by prokkyb** [comment]
This is happening for me and none of the solutions online work. Any suggestions?

**Comment by pardeep90snow** [comment]
Error: Creating a navigator doesn't take an argument. Maybe you are trying to use React Navigation 4 API? See https://reactnavigation.org/docs/hello-react-navigation for the latest API and guides.
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.

**Comment by Xplosive06** [comment]
This worked for me:

```terminal
npm start -- --reset-cache
npx react-native start --reset-cache
```

**Comment by Apol0x** [comment]
> This worked for me:
> 
> ```
> npm start -- --reset-cache
> npx react-native start --reset-cache
> ```

After having done that I have a problem because a lot of files were updated, do you had this problem?

**Comment by SyedSaifAli** [comment]
having the same problem in ios. Tried the above workaround, but doesn't work for me.

**Comment by autonauta** [comment]
Im having the same problem, tried react-native-cleanproject and cache reset but nothing

**Comment by arrluubuutee** [comment]
I'm also having the same problem in version 0.68.2 without using hermes. When I run react-native packager, I got the follow error messages.
``` 
ERROR  TypeError: undefined is not an object (evaluating '_react.PropTypes.array')
ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
```

Output of `npx react-native info`
```
System:
    OS: macOS 12.4
    CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
    Memory: 759.54 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.13.2 - ~/.nvm/versions/node/v16.15.1/bin/npm
    Watchman: 2022.06.20.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 13.4/13F17a - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/local/opt/openjdk@11/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: ^0.68.2 => 0.68.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by pardeep90snow** [comment]
Ok app registry working thank alot

**Comment by Hisham546** [comment]
> > This worked for me:
> > ```
> > npm start -- --reset-cache
> > npx react-native start --reset-cache
> > ```
> 
> @Xplosive06 After having done that I have a problem because a lot of files were updated, do you had this problem?



> > This worked for me:
> > ```
> > npm start -- --reset-cache
> > npx react-native start --reset-cache
> > ```
> 
> @Xplosive06 After having done that I have a problem because a lot of files were updated, do you had this problem?

Thanks Finally this methods worked for me too

**Comment by arrluubuutee** [comment]
> > > @autonauta @arrluubuutee Have you added `metro.config.js` file in your project? I was having the same problem, and what worked for me was I added this file with the code:
> > > ```
> > >  * Metro configuration for React Native
> > >  * https://github.com/facebook/react-native
> > >  *
> > >  * @format
> > >  */
> > > 
> > > module.exports = {
> > >   transformer: {
> > >     getTransformOptions: async () => ({
> > >       transform: {
> > >         experimentalImportSupport: false,
> > >         inlineRequires: true,
> > >       },
> > >     }),
> > >   },
> > > };
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > also, add this in your `babel.config.js` file
> > > ```
> > > module.exports = {
> > >   presets: ['module:metro-react-native-babel-preset'],
> > > };
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Keep your `devDependencies` in `package.json` like this
> > > ```
> > > "devDependencies": {
> > >     "@babel/core": "7.17.5",
> > >     "@babel/plugin-external-helpers": "7.0.0",
> > >     "@babel/preset-env": "^7.18.6",
> > >     "@babel/preset-react": "^7.18.6",
> > >     "metro-react-native-babel-preset": "^0.66.2",
> > >   }
> > > ```
> > 
> > 
> > Hi, I've done just like what you recommend above, but still facing the same issue, do you have any additional info related to this? thank you @SyedSaifAli
> 
> Can you make sure that your `babel.config.json` and `metro.config.json` is created in parallel to `node_modules/` folder. Also after applying these changes, remove `node_modules`, reinstall(`npm install`) and run `npx start --reset-cache`.

I already have the `metro.config.js` file in the project. I would like to show `metro.config.js` and `babel.config.js`.

**metro.config.js**
```javascript
/**
 * Metro configuration for React Native
 * https://github.com/facebook/react-native
 *
 * @format
 */

module.exports = {
	transformer: {
		getTransformOptions: async () => ({
			transform: {
				experimentalImportSupport: false,
				inlineRequires: true
			}
		}),
		assetPlugins: ['expo-asset/tools/hashAssetFiles']
	}
};
```
**babel.config.js**
```javascript
module.exports = {
	presets: ['module:metro-react-native-babel-preset', '@babel/preset-flow'],
	env: {
		production: {
			plugins: ['transform-remove-console']
		}
	},
	plugins: [
		['module:react-native-dotenv'],
		[
			'babel-plugin-inline-import',
			{
				extensions: ['.svg']
			}
		],
		'react-native-reanimated/plugin'
	]
};
```

But these issues are still happening in version 0.68.2.

**Comment by agrittiwari** [comment]
I was having the issue, but resolved after discarding the changes. dropping back to ` "react-native": "0.64.2"`

**Comment by Judefabi** [comment]
You are probably facing this issue after some changes in your app. I solved it in mine by going to the android folder and running 
**.gradlew clean** 
then running 
**npm ci**
from the app folder

**Comment by Priyanka072** [comment]
> Error: Creating a navigator doesn't take an argument. Maybe you are trying to use React Navigation 4 API? See https://reactnavigation.org/docs/hello-react-navigation for the latest API and guides. ERROR Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.

**Comment by arrluubuutee** [comment]
I have been solved issue(https://github.com/facebook/react-native/issues/32952#issuecomment-1175782321) by exported `ViewPropTypes` from `deprecated-react-native-prop-types` in some packages like below.

The problem is some of node dependencies are export `ViewPropTypes` from `react-native`, not export `deprecated-react-native-prop-types`. 
 - [react-native-snap-carousel](https://github.com/meliorence/react-native-snap-carousel)
   - https://github.com/meliorence/react-native-snap-carousel/issues/923
   - https://github.com/meliorence/react-native-snap-carousel/issues/928
   - https://github.com/meliorence/react-native-snap-carousel/issues/930
   - https://github.com/meliorence/react-native-snap-carousel/issues/933

- [react-native-dash](https://github.com/obipawan/react-native-dash)
   - [import { View, StyleSheet, ViewPropTypes } from 'react-native'](https://github.com/obipawan/react-native-dash/blob/302aaaff49172915779ae52057716af44f5304be/Dash.js#L9)

**Comment by lucasaclima03** [comment]
> I have been solved issue([#32952 (comment)](https://github.com/facebook/react-native/issues/32952#issuecomment-1175782321)) by exported `ViewPropTypes` from `deprecated-react-native-prop-types` in some packages like below.
> 
> The problem is some of node dependencies are export `ViewPropTypes` from `react-native`, not export `deprecated-react-native-prop-types`.
> 
> * [react-native-snap-carousel](https://github.com/meliorence/react-native-snap-carousel)
>   
>   * [ViewPropTypes will be removed from React Native. Migrate to ViewPropTypes exported from 'deprecated-react-native-prop-types'. meliorence/react-native-snap-carousel#923](https://github.com/meliorence/react-native-snap-carousel/issues/923)
>   * [ViewPropTypes has been removed from React Native. Migrate to ViewPropTypes exported from 'deprecated-react-native-prop-types meliorence/react-native-snap-carousel#928](https://github.com/meliorence/react-native-snap-carousel/issues/928)
>   * [deprecated-react-native-prop-types meliorence/react-native-snap-carousel#930](https://github.com/meliorence/react-native-snap-carousel/issues/930)
>   * [ViewPropTypes Deprecated meliorence/react-native-snap-carousel#933](https://github.com/meliorence/react-native-snap-carousel/issues/933)
> * [react-native-dash](https://github.com/obipawan/react-native-dash)
>   
>   * [import { View, StyleSheet, ViewPropTypes } from 'react-native'](https://github.com/obipawan/react-native-dash/blob/302aaaff49172915779ae52057716af44f5304be/Dash.js#L9)


Thank you! This worked for me too!

**Comment by spaceod** [comment]
npx react-native start --reset-cache 🎉

**Comment by Manil-SoftNEP** [comment]
Un-installing the app and re-building it using `npx react-native run-android` did the job for me.

**Comment by SherifSamir5** [comment]
"this solved my issue when I was running from Xcode"

1-close Xcode, and the ios simulator
2-in your app `cd ios`  then  `pod install`
3-clean build folder then try to rerun the app

**Comment by yourjhay** [comment]
I'm facing this on expo-go (IOS ) but runninf on android :(

**Comment by Joyin2** [comment]
`npx expo start -c`
this worked in expo

**Comment by likeSo** [comment]
I had a similar problem:
`
 ERROR  Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes
`

`npx expo start -c` can not resolve this problem...

**Comment by faizantariq1** [comment]
I have changed the name of the main folder now receiving this error in ios.
can not resolve this problem... any help?

**Comment by tanaynaik2001** [comment]
The issue still persists

**Comment by funfake** [comment]
same issue here

**Comment by leonardoGasperin** [comment]
nothing working

**Comment by faizantariq1** [comment]
facing this issue on ios. i have changed the simulator or also you can select simulator > Device > "Eraze All Content and Settings" > Erase. After that it's going to work fine for me.

**Comment by leonardoGasperin** [comment]
People for site, it's can bê alot cases, but, to me I extensa a class with React.Component but i write like it 'React.Component()' when i fiz this miss spell all back to work.

**Comment by urolovshohruh** [comment]
Error: Reanimated 2 failed to create a worklet, maybe you forgot to add Reanimated's babel plugin?
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.

**Comment by urolovshohruh** [comment]
![image](https://user-images.githubusercontent.com/94061669/210971418-24f50d73-ed32-403c-aea9-0449c1c7d062.png)

**Comment by DanielFelipeAgMo** [comment]
hi, in my case I have the same issues but i dont understond why persist if I have everything dependencies installed.
I really appreciate if you can help me, these are the screenshots of the error and the json package.

 
![packagejson](https://user-images.githubusercontent.com/81480211/214162201-53907b7a-e351-418b-aa32-75a45cdf62ba.png)

**Comment by ahan-p** [comment]
> 

I am getting same error in react native expo, app works perfectly on expo go app but after generating apk the app is crashing on physical device

**Comment by gabimoncha** [comment]
> This issue is mostly happen when `node_modules` folder has been changed by installing new library or some sort of action. Please try removing cache and do `yarn install` or `npm install` again
> 
> ```shell
> $ npx react-native-clean-project
> $ yarn install
> ```

Even though this works for me its annoying that everytime I change something in the project I have to go to the same process again. It's like hot reload is not working anymore

**Comment by hailie-rei** [comment]
In my case the problem was the following. After refactoring and removing some of my styles files I forgot to remove the calling of removed file:

```
import React from 'react';
import PropTypes from 'prop-types';
import {Text, View, StyleSheet} from 'react-native';
import styleDeckItem from '../../../../styles/deck/item'; - THIS FILE DOESN'T EXIST ANYMORE

const styles = StyleSheet.create({
    item: styleDeckItem.container,
});

export default function Item(props) {
    return (
        <View style={styles.item}>
            <Text>{props.term}</Text>
        </View>
    );
}
```

I received the same error that is described here, but before it I had a message related to that:

```
 ERROR  ReferenceError: Property 'styleDeckItem' doesn't exist, js engine: hermes
 ERROR  Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes
```

So my idea is to check any errors that come before the Invariant Violation error message and try to fix them. In my case I even tried to clear all the cache and build but it didn't help. Then I noticed that I have a reference error as well. >.<

**Comment by DFRZ7** [comment]
Hi, I'm still getting this issue:
 ERROR  Invariant Violation: Your JavaScript code tried to access a native module that doesn't exist. 

If you're trying to use a module that is not supported in Expo Go, you need to create a development build of your app. See https://docs.expo.dev/development/introduction/ for more info.
 ERROR  Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.

Tried clearing cache, but nothing.
Also, it is strange that it works in Android and not iOS, not sure if anyone has any other recommendation? Thank you. 

System:
    OS: macOS 13.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.49 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.19 - ~/Documents/Programming/frontend/node_modules/.bin/yarn
    npm: 7.24.2 - ~/Documents/Programming/frontend/node_modules/.bin/npm
    Watchman: 2023.01.16.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.5 => 0.70.5 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by NimsDiamonds** [comment]
simple solution that worked for me, make sure your project is clean. if your project is clean and it didn't work? have a glass of water  and "relax".....visit each folder, remove unnecessary libraries that you have added or imports* in each  screen (only have what your using*)  also use import * as React from 'react';

**Comment by dr1verrr** [comment]
That was worked for me finally. Add a few lines in MainApplication.java from this file
https://github.com/software-mansion-labs/reanimated-2-playground/blob/master/android/app/src/main/java/com/reanimated2playground/MainApplication.java

Add imports at top level.
`import com.facebook.react.bridge.JSIModulePackage;
import com.swmansion.reanimated.ReanimatedJSIModulePackage;`

Also add this method in ReactNativeHostWrapper
` protected JSIModulePackage getJSIModulePackage() {
          return new ReanimatedJSIModulePackage();
        }`

**Comment by izuutech** [comment]
> I had a similar problem: `ERROR Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter. A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes`
> 
> `npx expo start -c` can not resolve this problem...

were you able to solve your issue

**Comment by joaolvcas** [comment]
Try run `yarn` and after `yarn start`.

**Comment by oleandrosiq** [comment]
in my case it was the incompatibility of the react-native library with my animation library (react-native-reanimated), check if it gives a warning in your terminal when running the project, in my case it was giving this warning: 

**"Some dependencies are incompatible with the installed expo version:
   react-native@0.70.5 - expected version: 0.70.8
   react-native-reanimated@3.0.2 - expected version: ~2.12.0
Your project may not work correctly until you install the correct versions of the packages.
Install individual packages by running npx expo install react-native@0.70.8 react-native-reanimated@~2.12.0"**


 all I had to do was run the command: 
 ```npx expo install react-native@0.70.8 react-native-reanimated @~2.12.0``` 
 that worked 🚀

**Comment by mateusmatosleonardo** [comment]
estou recebendo o mesmo error :(

**Comment by developeromI89** [comment]
Getting same for crashlytics 
RN Version : 0.70
installing firebase crashlytics 
import crashlytics from '@react-native-firebase/crashlytics';

but as soon as trying to call any method like 
crashylytics().crash()
 its gives below error

Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.

**Comment by galdinoramon** [comment]
In my case, I declared a enum in a reducer and imported it to use in a service file ... so when try reading the enum atribute thrown and exception due to this undefined value. The service files runs before the react component, so thats the problem.

**Comment by ndpiparava** [comment]
> This issue is mostly happen when `node_modules` folder has been changed by installing new library or some sort of action. Please try removing cache and do `yarn install` or `npm install` again
> 
> ```shell
> $ npx react-native-clean-project
> $ yarn install
> ```

I would ask my self wtf do I need to re-install again if the error is in code, I would say this should have better resolution then re-installing all packages again

**Comment by LucasEdu10** [comment]
I'm having the same error:

```
[08:50:48] Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes
at node_modules\react-native\Libraries\Core\ExceptionsManager.js:null in reportException
at node_modules\react-native\Libraries\Core\ExceptionsManager.js:null in handleException
- ... 7 more stack frames from framework internals

[08:50:48] Invariant Violation: Your JavaScript code tried to access a native module that doesn't exist.

If you're trying to use a module that is not supported in Expo Go, you need to create a development build of your app. See https://docs.expo.dev/development/introduction/ for more info., js engine: hermes
at node_modules\react-native\Libraries\Core\ExceptionsManager.js:null in reportException
at node_modules\react-native\Libraries\Core\ExceptionsManager.js:null in handleException
at node_modules\react-native\Libraries\Core\setUpErrorHandling.js:null in handleError
at node_modules\expo\build\errors\ExpoErrorManager.js:null in createErrorHandler
at node_modules\expo\build\errors\ExpoErrorManager.js:null in <anonymous>
at node_modules\@react-native\js-polyfills\error-guard.js:null in ErrorUtils.applyWithGuard
at node_modules\metro-runtime\src\polyfills\require.js:null in guardedLoadModule
```
for Android it works, but for IOS it gives this error

My package.json:
```
{
  "name": "app",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@expo/vector-icons": "^13.0.0",
    "@react-native-async-storage/async-storage": "1.18.2",
    "@react-native-firebase/auth": "^18.6.0",
    "@react-navigation/drawer": "^6.6.6",
    "@react-navigation/native": "^6.1.9",
    "@react-navigation/stack": "^6.3.20",
    "expo": "~49.0.15",
    "expo-status-bar": "~1.6.0",
    "firebase": "^10.5.2",
    "react": "18.2.0",
    "react-native": "0.72.6",
    "react-native-reanimated": "~3.3.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "metro-react-native-babel-preset": "^0.66.2"
  },
  "private": true
}
```
