### ISSUE TITLE
Forcing React Native v0.65.x to use OkHttp 3

### ISSUE THREAD

**Issue by tai-nguyen175** [facebook/react-native#32958]
### Description

Since React Native 0.65.x, OkHttp has been bumped up from v3->v4. Due to some reasons, we're not able to upgrade OkHttp on our native Android app. So we're forcing React Native 0.65.2 to use OkHttp v3.13.9 and has not faced any issue so far with the networking module.

Has anyone tried the same approach and faced any issues?

### Version

0.65.2

### Output of `npx react-native info`

System:
OS: macOS 11.4
CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
Memory: 67.71 MB / 16.00 GB
Shell: 5.8 - /bin/zsh
Binaries:
Node: 15.6.0 - /usr/local/bin/node
Yarn: 1.22.10 - /usr/local/bin/yarn
npm: 7.4.0 - /usr/local/bin/npm
Watchman: 4.9.0 - /usr/local/bin/watchman
Managers:
CocoaPods: 1.10.1 - /usr/local/bin/pod
SDKs:
iOS SDK:
Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
Android SDK:
API Levels: 28, 29, 30
Build Tools: 28.0.3, 29.0.2, 30.0.3, 31.0.0
System Images: android-28 | Google APIs Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
Android NDK: 22.1.7171670
IDEs:
Android Studio: 4.2 AI-202.7660.26.42.7351085
Xcode: 12.5/12E262 - /usr/bin/xcodebuild
Languages:
Java: 1.8.0_275 - /usr/bin/javac
npmPackages:
@react-native-community/cli: Not Found
react: 17.0.2=> 17.0.1
react-native: 0.65.2 => 0.65.2
react-native-macos: Not Found
npmGlobalPackages:
react-native: Not Found

### Steps to reproduce

Add dependencies to **gradle.build(app)** to force runtime classpath to resolve conflicts from the transitive OkHttp dependencies of react-native on your native Android app

```
implementation "com.squareup.okhttp3:okhttp:3.14.9"
implementation "com.squareup.okhttp3:okhttp-urlconnection:3.14.9"
```

**Comment by mrousavy** [comment]
> Due to some reasons

![🤨](https://i.kym-cdn.com/entries/icons/original/000/039/073/one_eyebrow_raised.jpg)

**Comment by tai-nguyen175** [comment]
> > Due to some reasons
> 
> ![🤨](https://camo.githubusercontent.com/4acb5498ffbc97db17395bb0820fc08217d7139b0bdb467a3c1b629af1ada61c/68747470733a2f2f692e6b796d2d63646e2e636f6d2f656e74726965732f69636f6e732f6f726967696e616c2f3030302f3033392f3037332f6f6e655f65796562726f775f7261697365642e6a7067)

Mate, the dependencies of the native Android app is not in our control

**Comment by cortinico** [comment]
> Has anyone tried the same approach and faced any issues?

Closing as this is not an issue. For discussions, you should either use StackOverflow or the github.com/react-native-community/discussions-and-proposals repo 👍

**Comment by kgsachinthaudara** [comment]
I am also facing same issue, need to have some proper solution
