### ISSUE TITLE
`await Linking.canOpenURL("https://...")` yields `false` on Android

### ISSUE THREAD

**Issue by jsamr** [facebook/react-native#32960]
### Description

The expression below yields `false` on Android Emulator with API 30 (Android 11):

```js
await Linking.canOpenURL("https://google.com/")
```
While it should yield `true`. In the same application, `Linking.openURL("https://google.com/")` does indeed open a new page in the system browser or WebView.

**Related issue**: #32311 (was closed due to stale).

### Version

0.67.1

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: Linux 5.10 Manjaro Linux
    CPU: (8) x64 Intel(R) Core(TM) i7-8809G CPU @ 3.10GHz
    Memory: 1.08 GB / 31.28 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.2 - /usr/bin/node
    Yarn: 1.22.17 - /usr/bin/yarn
    npm: 8.3.0 - /usr/bin/npm
    Watchman: 4.9.0 - /usr/bin/watchman
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: AI-203.7717.56.2031.7935034
  Languages:
    Java: 11.0.13 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.1 => 0.67.1 
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Execute the below code snippet in a React Native app on Android, API 11:

```js
const canOpen = await Linking.canOpenURL("https://google.com/");
console.info(canOpen); // prints "false"
```

### Snack, code example, screenshot, or link to a repository

https://github.com/jsamr/react-native-canopenurl-bug

**Comment by Adnan-Bacic** [comment]
does this help: https://github.com/facebook/react-native/issues/30497#issuecomment-866855993

basically go to `android/app/src/main/AndroidManifest.xml` and paste this in:

```
<queries>
 <intent>
  <action android:name="android.intent.action.VIEW" />
  <data android:scheme="https"/>
 </intent>
</queries>
```

**Comment by jsamr** [comment]
@Adnan-Bacic Good catch. I shall close then!
