### ISSUE TITLE
 Unhandled JS Exception: Unexpected identifier '_classCallCheck'. import call expects exactly one argument. no stack

### ISSUE THREAD

**Issue by mojvan** [facebook/react-native#32974]
> I have a similar issue: Unhandled JS Exception: Unexpected identifier '_classCallCheck'. import call expects exactly one argument. no stack Please helps me ![Simulator Screen Shot - iPhone 13 - 2022-01-18 at 13 12 40](https://user-images.githubusercontent.com/63491016/149881059-5c0b169f-65b9-41ec-9f41-21d9d1ede65b.png)

I have this issue too and my package.json is:
```
{
  "main": "index.js",
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "web": "expo start --web",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "@mohamadkh75/react-native-jalali-datepicker": "^1.1.1",
    "@react-native-async-storage/async-storage": "^1.15.17",
    "@react-native-community/slider": "^4.2.0",
    "@react-native-masked-view/masked-view": "^0.2.6",
    "@react-navigation/bottom-tabs": "^6.0.9",
    "@react-navigation/drawer": "^6.1.8",
    "@react-navigation/native": "^6.0.6",
    "@react-navigation/stack": "^6.0.11",
    "expo": "~38.0.1",
    "expo-splash-screen": "~0.4.0",
    "expo-status-bar": "^1.0.0",
    "expo-updates": "~0.2.10",
    "pushe-react-native": "^2.5.0",
    "react": "~16.11.0",
    "react-dom": "~16.11.0",
    "react-native": "0.64.2",
    "react-native-adtrace": "^1.2.3",
    "react-native-camera": "^4.2.1",
    "react-native-chart-kit": "^6.11.0",
    "react-native-elements": "^3.4.2",
    "react-native-geolocation-service": "^5.3.0-beta.4",
    "react-native-gesture-handler": "~1.6.0",
    "react-native-image-picker": "^4.7.1",
    "react-native-maps": "^0.30.1",
    "react-native-paper": "^4.11.2",
    "react-native-qrcode-scanner": "^1.5.4",
    "react-native-reanimated": "~1.9.0",
    "react-native-safe-area-context": "^3.3.2",
    "react-native-screens": "~2.9.0",
    "react-native-snap-carousel": "^3.9.1",
    "react-native-svg": "^12.1.1",
    "react-native-swiper": "^1.6.0",
    "react-native-unimodules": "~0.10.1",
    "react-native-vector-icons": "^9.0.0",
    "react-native-web": "~0.11.7",
    "react-navigation": "^4.4.4",
    "react-redux": "^7.2.6",
    "redux": "^4.1.2",
    "redux-logger": "^3.0.6",
    "redux-persist": "^6.0.0",
    "redux-saga": "^1.1.3"
  },
  "devDependencies": {
    "@babel/core": "~7.9.0",
    "babel-jest": "~25.2.6",
    "jest": "~25.2.6",
    "react-test-renderer": "~16.11.0"
  },
  "jest": {
    "preset": "react-native"
  },
  "private": true
}
```
what is _classCallCheck and how it works?
please help??

**Comment by marciodajr** [comment]
[#32888 ](https://github.com/facebook/react-native/issues/32888#issuecomment-1024901374)

**Comment by mojvan** [comment]
> [#32888 ](https://github.com/facebook/react-native/issues/32888#issuecomment-1024901374)

thank you but it not works for this error

**Comment by marciodajr** [comment]
> > [#32888 ](https://github.com/facebook/react-native/issues/32888#issuecomment-1024901374)
> 
> thank you but it not works for this error

I haven't tested it with expo. And using React Native CLI in my case eslint and metro-react-native-babel-preset were out of the compatible version with react-native

**Comment by mojvan** [comment]
> > > [#32888 ](https://github.com/facebook/react-native/issues/32888#issuecomment-1024901374)
> > 
> > 
> > thank you but it not works for this error
> 
> I haven't tested it with expo. And using React Native CLI in my case eslint and metro-react-native-babel-preset were out of the compatible version with react-native

This is an amazing error because I added expo to the project and I had no problem but after shutting down my laptop and turn on it, this error appeared in running app

**Comment by vivek-y** [comment]
Facing the same problem and cant find a fix. @mojvan any luck?

**Comment by mojvan** [comment]
> Facing the same problem and cant find a fix. @mojvan any luck?

I think it appears becuase of classes are'nt called in right places but I'm not sure

**Comment by micahgoodman** [comment]
@mojvan and @vivek-y -- this was linked in a similar thread and worked for me https://github.com/babel/babel/issues/14139#issuecomment-1011836916 (specifically, the part about updating my `babel.config.js`)

**Comment by xhirazi** [comment]
@micahgoodman  Thanks man.

**Comment by mojvan** [comment]
> @mojvan and @vivek-y -- this was linked in a similar thread and worked for me [babel/babel#14139 (comment)](https://github.com/babel/babel/issues/14139#issuecomment-1011836916) (specifically, the part about updating my `babel.config.js`)

thank you but I'm using babel-preset-expo in babel.config.js instead metro-react-native-babel-preset and these solutions are not ok for my case.
please help

**Comment by micahgoodman** [comment]
@mojvan sorry I unfortunately don't know how to help in that case. Have you tried updating your babel.config.js as shown in the linked comment, even though you're using babel-preset-expo?

**Comment by mojvan** [comment]
@micahgoodman updating versions in this case is not right solution. tnx

**Comment by younasm** [comment]
> > > > [#32888 ](https://github.com/facebook/react-native/issues/32888#issuecomment-1024901374)
> > > 
> > > 
> > > thank you but it not works for this error
> > 
> > 
> > I haven't tested it with expo. And using React Native CLI in my case eslint and metro-react-native-babel-preset were out of the compatible version with react-native
> 
> This is an amazing error because I added expo to the project and I had no problem but after shutting down my laptop and turn on it, this error appeared in running app

Same error it was ok but the next day when I open my project and run `expo start` showing the same error didn't find any solution yet. any help!

**Comment by younasm** [comment]
> > I have a similar issue: Unhandled JS Exception: Unexpected identifier '_classCallCheck'. import call expects exactly one argument. no stack Please helps me ![Simulator Screen Shot - iPhone 13 - 2022-01-18 at 13 12 40](https://user-images.githubusercontent.com/63491016/149881059-5c0b169f-65b9-41ec-9f41-21d9d1ede65b.png)
> 
> I have this issue too and my package.json is:
> 
> ```
> {
>   "main": "index.js",
>   "scripts": {
>     "android": "react-native run-android",
>     "ios": "react-native run-ios",
>     "web": "expo start --web",
>     "start": "react-native start",
>     "test": "jest"
>   },
>   "dependencies": {
>     "@mohamadkh75/react-native-jalali-datepicker": "^1.1.1",
>     "@react-native-async-storage/async-storage": "^1.15.17",
>     "@react-native-community/slider": "^4.2.0",
>     "@react-native-masked-view/masked-view": "^0.2.6",
>     "@react-navigation/bottom-tabs": "^6.0.9",
>     "@react-navigation/drawer": "^6.1.8",
>     "@react-navigation/native": "^6.0.6",
>     "@react-navigation/stack": "^6.0.11",
>     "expo": "~38.0.1",
>     "expo-splash-screen": "~0.4.0",
>     "expo-status-bar": "^1.0.0",
>     "expo-updates": "~0.2.10",
>     "pushe-react-native": "^2.5.0",
>     "react": "~16.11.0",
>     "react-dom": "~16.11.0",
>     "react-native": "0.64.2",
>     "react-native-adtrace": "^1.2.3",
>     "react-native-camera": "^4.2.1",
>     "react-native-chart-kit": "^6.11.0",
>     "react-native-elements": "^3.4.2",
>     "react-native-geolocation-service": "^5.3.0-beta.4",
>     "react-native-gesture-handler": "~1.6.0",
>     "react-native-image-picker": "^4.7.1",
>     "react-native-maps": "^0.30.1",
>     "react-native-paper": "^4.11.2",
>     "react-native-qrcode-scanner": "^1.5.4",
>     "react-native-reanimated": "~1.9.0",
>     "react-native-safe-area-context": "^3.3.2",
>     "react-native-screens": "~2.9.0",
>     "react-native-snap-carousel": "^3.9.1",
>     "react-native-svg": "^12.1.1",
>     "react-native-swiper": "^1.6.0",
>     "react-native-unimodules": "~0.10.1",
>     "react-native-vector-icons": "^9.0.0",
>     "react-native-web": "~0.11.7",
>     "react-navigation": "^4.4.4",
>     "react-redux": "^7.2.6",
>     "redux": "^4.1.2",
>     "redux-logger": "^3.0.6",
>     "redux-persist": "^6.0.0",
>     "redux-saga": "^1.1.3"
>   },
>   "devDependencies": {
>     "@babel/core": "~7.9.0",
>     "babel-jest": "~25.2.6",
>     "jest": "~25.2.6",
>     "react-test-renderer": "~16.11.0"
>   },
>   "jest": {
>     "preset": "react-native"
>   },
>   "private": true
> }
> ```
> 
> what is _classCallCheck and how it works? please help??

my Error gone by updating 

`"babel-preset-expo": "~8.1.0",`
to
`"babel-preset-expo": "~8.3.0",`

then run
`expo start -c`

Happy Coding!

**Comment by abdouakhad** [comment]
Yes changing this
`"babel-preset-expo": "~8.1.0",
`
to 
`"babel-preset-expo": "~8.3.0"`

works for me

**Comment by mojvan** [comment]
Thank you for your solutions

**Comment by ksd711** [comment]
Yes changing this
"babel-preset-expo": "~8.1.0",
to
"babel-preset-expo": "~8.3.0"

works for me also 
Thanks
