### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code 

### ISSUE THREAD

**Issue by hellforever** [facebook/react-native#32984]
### Description

I followed the instructions from `https://reactnative.dev/docs/environment-setup`

`npx react-native init AwesomeProject`
`npm install` then cd to ios directory and run
`pod install`
then opened the project with Xcode and trigged build. But the build failed and the error is 
`Command PhaseScriptExecution failed with a nonzero exit code`
The project could run properly via the command `npx react-native run-ios`, but could not be built on Xcode, I tried on two different Macbook and got the same error.

### Version

0.67.1

### Output of `npx react-native info`

System:
    OS: macOS 11.6.2
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 126.16 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.3 - ~/.nvm/versions/node/v14.18.3/bin/node
    Yarn: 1.22.15 - /opt/local/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.3/bin/npm
    Watchman: 2022.01.24.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7784292
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.13 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.67.1 => 0.67.1
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

`npx react-native init AwesomeProject`
`npm install` then cd to ios directory and run
`pod install`
then opened the project with Xcode and trigged build

### Snack, code example, screenshot, or link to a repository

![image](https://user-images.githubusercontent.com/5683380/151473710-79201193-6e9c-4006-9a3c-8479a22bb1af.png)

**Comment by dehlen** [comment]
Seeing the sample problem. Seems like this run script phase fails due to the latest changes made in RCTActionSheetIOS:
```
/Users/<redacted>/Developer/app.git-worktrees/feature/branch_name/node_modules/react-native/React/CoreModules/RCTActionSheetManager.mm:98:35: No member named 'cancelButtonTintColor' in 'JS::NativeActionSheetManager::SpecShowActionSheetWithOptionsOptions'
```
When I look at the FBReactNativeSpec header indeed the new property `cancelButtonTintColor` is missing.

**Comment by tpedersen123** [comment]
I had this issue when installing react-native globally.
Switching to npx react-native fixed it :-)

**Comment by JonnyLinja** [comment]
I'm having what appears to be the same issue. Looks to be the same issue as https://github.com/facebook/react-native/issues/32951 which shows other people have it too.

I looked into but didn't get anywhere. Putting what I did find below.

---

I tried running the generated script `/Users/<username>/Library/Developer/Xcode/DerivedData/<nameofproject>/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FBReactNativeSpec.build/Script-<random>.sh` directly in terminal. I just had to copy paste the exports first. I then added echo statements to the shell scripts to figure out where it stopped working. As far as I can tell, on my computer it:

- executes the generated script until the `source` line. `source` basically runs `node_modules/react-native/scripts/find-node.sh`
- `find-node.sh` executes until it reaches `$HOME/.nvm/nvm.sh`, which it then runs
- `nvm.sh` runs but it fails at some point that I can't tell

Interestingly, if I run `find-node.sh` by just entering the filename in terminal, it executes successfully. However if I run `sh find-node.sh` in terminal, it does not finish the script and exits prematurely.

---

I'm wondering if it's a node setup issue. On my computer I:

- deleted the local `node` that `Homebrew` installed
- have` nvm` set to `16.13.2` and uninstalled all other versions other than system
- symlinked the local `node` to `nvm` so Xcode targets the correct one. I used `ln -s $(which node) /usr/local/bin/node`

This setup works fine for `RN 0.66.1`, which has a different `FBReactNativeSpec` build script as it does not write any `yaml` headers or `hmap` files or generate a script.

**Comment by JonnyLinja** [comment]
I had what appears to be the same issue. Looks to be the same issue as #32951 which shows other people have it too. I am also attempting to run the project via Xcode directly.

https://github.com/facebook/react-native/pull/32712 solved it for me, which is slated for the 0.68 release. For now I patch-package'd the relevant changes to `find-node` to get 0.67.1 running.

**Comment by hellforever** [comment]
@dehlen @JonnyLinja 
This solution works for me:
https://stackoverflow.com/questions/66742033/phasescriptexecution-cp-user-error-in-react-native/70104375#70104375

**Comment by dehlen** [comment]
I do not use nvm but asdf-vm to manage my node versions. What worked for me was to have a look at the `node_modules/react-native/scripts/find-node.sh` script and to make sure that the script can find my current node version. None of the both paths for asdf were available on my machine which is why I had this error. Once I symlinked my asdf.sh from  `. /usr/local/opt/asdf/libexec/asdf.sh` to `$HOME/.asdf/asdf.sh` the build started to work for me.

**Comment by krlol** [comment]
Cleaning the project and re-running worked for me

**Comment by vaughnkoch** [comment]
@dehlen, @krlol, @JonnyLinja agreed that cleaning & rebuilding works at least to solve the cancelButtonTintColor issue - it looks like FBReactNativeSpec.h is generated on the fly. Cleaning the build regenerated that file for me.

**Comment by pedrorenan** [comment]
For me works with:

![image](https://user-images.githubusercontent.com/923983/154140325-cdd83aa0-d646-45c1-b7e2-9d9eb010c8f8.png)

![image](https://user-images.githubusercontent.com/923983/154140389-78c7297e-60e2-43ea-b5a1-f1d56a8d7af2.png)

**Comment by aramyesildeniz** [comment]
After trying out all suggestions and different versions of tools such as XCode, nvm, yarn, node, etc., the only thing that worked for me was to downgrade react native.

In package.json:

`"react-native": "0.66.4"`

**Comment by surajSanwal** [comment]
This worked for me

https://stackoverflow.com/a/71392772/4030220

**Comment by Amr1440** [comment]
Same issue for 1 week now i couldn't resolve it

**Comment by surajSanwal** [comment]
> https://stackoverflow.com/a/71392772/4030220

@Amr1440  have you checked my comments, after 2-3 days work i got the solution, issue may be due to scheme name includes special char or need a change in react-native load script.

**Comment by pedrolopes10** [comment]
after some hours, uninstall node from brew and installed directly from node website and worked!

**Comment by Jafferson1** [comment]
This worked for me:
I changed MyProject/index.tsx to MyProject/index.js

**Comment by iqorlobanov** [comment]
Which version of `node` you are using?
You can use `nvm` for switching node versions. 
For example: `nvm use 14.19.0` 
This version successfully runs a typescript template

**Comment by chenweigh** [comment]
### Problem
```
Showing All Errors Only

Build target FBReactNativeSpec of project Pods with configuration Debug

PhaseScriptExecution [CP-User]\ Generate\ Specs /Users/chen/Library/Developer/Xcode/DerivedData/NativeWithReactNativeDemo-cyjlnvbefgrdcbcnrhsxpweyuumx/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FBReactNativeSpec.build/Script-5F4C70EF7D90A5A5BDAEB404279F232A.sh (in target 'FBReactNativeSpec' from project 'Pods')
    cd /Users/chen/working/NativeWithReactNativeDemo/Pods
Command PhaseScriptExecution failed with a nonzero exit code

Build failed    2022/4/28, 6:12 PM    40.7 seconds

```

### Podfile
```
def myRNNewPod
  pod 'YogaKit', '12.3.5.2'
  
  react_native_path = '../react-native-67/react-native'
  
  pod 'FBLazyVector', :path => "#{react_native_path}/Libraries/FBLazyVector"
  pod 'RCTRequired', :path => "#{react_native_path}/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "#{react_native_path}/Libraries/TypeSafety"
  pod 'React-Core', :path => "#{react_native_path}/"
  pod 'React-Core/DevSupport', :path => "#{react_native_path}/"
  pod 'React-RCTActionSheet', :path => "#{react_native_path}/Libraries/ActionSheetIOS"
  
  pod 'React', :path => "#{react_native_path}/"
  pod 'React-CoreModules', :path => "#{react_native_path}/React/CoreModules"
  pod 'React-RCTAnimation', :path => "#{react_native_path}/Libraries/NativeAnimation"
  pod 'React-RCTBlob', :path => "#{react_native_path}/Libraries/Blob"
  pod 'React-RCTImage', :path => "#{react_native_path}/Libraries/Image"
  pod 'React-RCTLinking', :path => "#{react_native_path}/Libraries/LinkingIOS"
  pod 'React-RCTNetwork', :path => "#{react_native_path}/Libraries/Network"
  pod 'React-RCTSettings', :path => "#{react_native_path}/Libraries/Settings"
  pod 'React-RCTVibration', :path => "#{react_native_path}/Libraries/Vibration"

  pod 'React-RCTText', :path => "#{react_native_path}/Libraries/Text"
  pod 'React-Core/RCTWebSocket', :path => "#{react_native_path}/"

  pod 'React-cxxreact', :path => "#{react_native_path}/ReactCommon/cxxreact"
  pod 'React-jsi', :path => "#{react_native_path}/ReactCommon/jsi"
  pod 'React-jsiexecutor', :path => "#{react_native_path}/ReactCommon/jsiexecutor"
  pod 'React-jsinspector', :path => "#{react_native_path}/ReactCommon/jsinspector"
  pod 'React-callinvoker', :path => "#{react_native_path}/ReactCommon/callinvoker"
  pod 'Yoga', :path => "#{react_native_path}/ReactCommon/yoga"
  
  pod 'boost', :podspec => "#{react_native_path}/third-party-podspecs/boost.podspec"
  pod 'DoubleConversion', :podspec => "#{react_native_path}/third-party-podspecs/DoubleConversion.podspec"
  pod 'glog', :podspec => "#{react_native_path}/third-party-podspecs/glog.podspec"
  pod 'RCT-Folly', :podspec => "#{react_native_path}/third-party-podspecs/RCT-Folly.podspec"
  
  pod 'ReactCommon/turbomodule/core', :path => "#{react_native_path}/ReactCommon"
#  pod 'FBReactNativeSpec', :path => "#{react_native_path}/Libraries/FBReactNativeSpec"
  pod 'FBReactNativeSpec', :path => "#{react_native_path}/React/FBReactNativeSpec"

  pod 'React-perflogger', :path => "#{react_native_path}/ReactCommon/reactperflogger"
  pod 'React-runtimeexecutor', :path => "#{react_native_path}/ReactCommon/runtimeexecutor"
  pod 'React-logger', :path => "#{react_native_path}/ReactCommon/logger"
  
end
```

How to fix it? 
I need help.

**Comment by boma25** [comment]
I had my root folder name "REACT NATIVE", changing it to "REACT_NATIVE" fixed the error as the folder that contains your react native project cannot contain white spaces

**Comment by thaitd0396** [comment]
> I had my root folder name "REACT NATIVE", changing it to "REACT_NATIVE" fixed the error as the folder that contains your react native project cannot contain white spaces

It worked for me, thank bro

**Comment by daaanigm** [comment]
My problem was that I renamed the index.js root file to index.tsx, if you rename it to index.js it works. 👍

**Comment by edinpuzic** [comment]
I also confirm if you change index.ts to index.js it works

**Comment by bozaigao** [comment]
My computer has an M1 chip，I tried everything. The most important changes are as follows:
nvm unalias default
nvm alias default node

**Comment by sajjad-karimi** [comment]
this work form me with nvm: 

first you should uninstall local node :

`brew uninstall node`

and then install the latest version of node with nvm :

`nvm install node`

and now if you run `which node` the location should be something like this:

`/Users/<user-name>/.nvm/versions/node/v<installed-version>/bin/node`

and then you should set the installed version to default version to do this first clear current default with:

`nvm unalias default`

and then set the new default : 

`nvm alias default <installed-version>`     example => `nvm alias default 14.17.3`

and the last is link the node location to `/usr/local/bin/node` :

`% which node`

**`/Users/<user-name>/.nvm/versions/node/v<installed-version>/bin/node`**

put the printed address :

`sudo ln -s **/Users/<user-name>/.nvm/versions/node/v<installed-version>/bin/node**  /usr/local/bin/node`

**Comment by jjrise** [comment]
> 

brilliant, after trying a million different suggestions this is the one that worked for me.... thanks!

**Comment by jjrise** [comment]
> This worked for me: I changed MyProject/index.tsx to MyProject/index.js


brilliant, after trying a million different suggestions this is the one that worked for me.... thanks!

**Comment by hienbv1312** [comment]
> If you're getting this with an error about setting the node path, this should fix it.
> 
> `sudo ln -s $(which node) /usr/local/bin/node`
Thanks bro, you saved my life 💯

**Comment by Bittersweet-Chocolate** [comment]
> this work form me with nvm:
> 
> 这项工作形成了我与 nvm:
> 
> first you should uninstall local node :
> 
> 首先卸载本地节点:
> 
> `brew uninstall node`
> 
> 酿造卸载节点
> 
> and then install the latest version of node with nvm :
> 
> 然后使用 nvm 安装最新版本的节点:
> 
> `nvm install node`
> 
> 安装节点
> 
> and now if you run `which node` the location should be something like this:
> 
> 现在如果运行哪个节点，位置应该是这样的:
> 
> `/Users/<user-name>/.nvm/versions/node/v<installed-version>/bin/node`
> 
> /Users/< user-name >/. nvm/version/node/v < install-version >/bin/node
> 
> and then you should set the installed version to default version to do this first clear current default with:
> 
> 然后，您应该将安装的版本设置为默认版本，以便首先清除当前默认值:
> 
> `nvm unalias default`
> 
> Nvm unalias 默认值
> 
> and then set the new default :
> 
> 然后设置新的默认值:
> 
> `nvm alias default <installed-version>` example => `nvm alias default 14.17.3`
> 
> Nvm alias default < install-version > example = > nvm alias default 14.17.3
> 
> and the last is link the node location to `/usr/local/bin/node` :
> 
> 最后是将节点位置链接到/usr/local/bin/node:
> 
> `% which node`
> 
> % 哪个节点
> 
> **`/Users/<user-name>/.nvm/versions/node/v<installed-version>/bin/node`**
> 
> /Users/< user-name >/. nvm/version/node/v < install-version >/bin/node
> 
> put the printed address :
> 
> 列印地址:
> 
> `sudo ln -s /Users/<user-name>/.nvm/versions/node/v<installed-version>/bin/node /usr/local/bin/node`
> 
> Sudo ln-s/Users/< user-name >/. nvm/version/node/v < install-version >/bin/node/usr/local/bin/node

thank bro，it worked for me

**Comment by Garamani** [comment]
In my case, the problem was related to **Not having enough space** on my mac.

**Comment by Solaimanx** [comment]
unsetting the default alias fixed my issue.

`$ nvm unalias default`

clean the build folder then rebuild the project.

note : I'm using Xcode 14.0.1

https://stackoverflow.com/a/70944459/15266718

**Comment by hengkx** [comment]
I've tried it all and still have problems.
react native 0.70.3

**Comment by pachun** [comment]
I use an M2 Mac Air w/ home-brew (but node installed via asdf) and @ksealey 's answer worked for me:

```
sudo ln -s $(which node) /usr/local/bin/node
```

Except, I had to make the directory first since it didn't exist - but it definitely worked:

```
sudo mkdir /user/local/bin
```

**Comment by avinashsahoo** [comment]
> I had my root folder name "REACT NATIVE", changing it to "REACT_NATIVE" fixed the error as the folder that contains your react native project cannot contain white spaces

Great. It worked. But surprisingly it happened only with newer version of React Native. Earlier it used work in that way.

**Comment by Talhafayyaz11** [comment]
I am facing the same issue with node version 19 and i deleted the nvm also but none of the solution worked for me.

**Comment by ZohaibAhmad786** [comment]
> If you're getting this with an error about setting the node path, this should fix it.
> 
> `sudo ln -s $(which node) /usr/local/bin/node`

you saved my days thanks

**Comment by Waryen** [comment]
I'v got this issue after I've uninstalled my node binary installed by brew because I use volta's node binary.
Apparently Xcode disliked that, I had too reinstall node via brew `brew install node@16` BUT didn't updated my path so that I still use my volta's node binary in the terminal.

**Comment by Aakash9721** [comment]
> sudo ln -s $(which node) /usr/local/bin/node

This worked for me removing the space in the name of the root directory worked for me

**Comment by dungnguyentri3110** [comment]
> > https://stackoverflow.com/a/71392772/4030220
> 
> @Amr1440 have you checked my comments, after 2 to 3 days of work I got the solution, the issue may be due to scheme name including special char or need a change in the react-native load script.

Thank you so much. this solution help me out this issue after 1 week stuck

**Comment by manuarya** [comment]
Target > General > Supported Destinations - Remove Mac

**Comment by zartabkhalil** [comment]
permission issue on the mac machine.sudo chown -R  $(whoami)  /path/to/project  solved for me

**Comment by DiorAbjalilov** [comment]
react-native-rncore:error
![image](https://github.com/facebook/react-native/assets/78947884/34772ad9-491b-477e-8209-07d7e9a50279)

There should be no empty space in the names of folders managing the project.

**Comment by kigh143** [comment]
> If you're getting this with an error about setting the node path, this should fix it.
> 
> `sudo ln -s $(which node) /usr/local/bin/node`

This solution worked for me. Initially, I was using Node installed via Brew, but I recently switched to using NVM. That's when I started encountering this issue. However, after running this command, it's now building fine.

**Comment by congshengwu** [comment]
I resolved the issue in this way, and I am using nvm to manage nodes.

execute `sudo ln -s $(which node) /usr/local/bin/node`
command line tools say: **ln: /usr/local/bin/node: File exists**
execute `sudo rm /usr/local/bin/node`
execute `sudo ln -s $(which node) /usr/local/bin/node` again.

Then no error when I run build on Xcode.

**Comment by turtle-evolution** [comment]
For me, I find .xcode.env.local and edit version npm for them.
Step 1: which node => get node version ex: v18.14.2
Step 2: versions/node/v16.16.2/bin/node => versions/node/v18.14.2/bin/node
Step 3: run again.
I hope it will help you resolve the issue.

**Comment by AdamLee321** [comment]
For me it was the parent folder I had my project in. The parent folder name had a space ("Parent Folder") and once I renamed it to ("ParentFolder") the project built successfully.

**Comment by Oladapodaniel** [comment]
This fixed it for me
[](https://stackoverflow.com/a/67289307)

**Comment by KAMRONBEK** [comment]
> If you're getting this with an error about setting the node path, this should fix it.
> 
> `sudo ln -s $(which node) /usr/local/bin/node`

its giving me error `ln: /usr/local/bin/node: File exists`

**Comment by shabbir-hussain-git** [comment]
For me : 

Showing Recent Issues
[Warning] You need to configure your node path in the `".xcode.env" file` environment.  You can set it up quickly by running:  `echo export NODE_BINARY=$(command -v node) > .xcode.env`  in the ios folder. This is needed by React Native to work correctly.  We fallback to the DEPRECATED behavior of finding `node`. This will be REMOVED in a future version.  You can read more about this here: https://reactnative.dev/docs/environment-setup#optional-configuring-your-environment

echo export NODE_BINARY=$(command -v node) > .xcode.env <--  this works rn version 0.75

**Comment by davitdarsalia** [comment]
> sudo ln -s $(which node) /usr/local/bin/node

That magically helped me. RN version 0.75.

**Comment by neiracausevic1** [comment]
If anyone has this issue in RN version 0.73.0:

I did everything written in this thread but it only started working when I **downgraded to 0.72.17**

**Comment by migueldaipre** [comment]
Fixed as mentioned [here](https://github.com/facebook/react-native/issues/47211#issuecomment-2438971826).
