### ISSUE TITLE
Running `test-manual-e2e.sh` results in `./gradlew: No such file or directory` error depending on the current path

### ISSUE THREAD

**Issue by gabrieldonadel** [facebook/react-native#32999]
### Description

Running `test-manual-e2e.sh` from any folder other than the repo root results in errors regarding the current path. 
When testing Android the following error is shown `./gradlew: No such file or directory`.
A similar error happens when selecting iOS
```
../../scripts/test-manual-e2e.sh: line 83: cd: packages/rn-tester: No such file or directory 

The file /Users/gabriel/Workspace/react-native/packages/rn-tester/packages/rn-tester/RNTesterPods.xcworkspace does not exist.
``` 

Ideally we should de able to run this script from any folder 

### Version

0.67.1

### Output of `npx react-native info`

System:
    OS: macOS 12.0.1
    CPU: (8) arm64 Apple M1
    Memory: 112.09 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.10.0 - ~/.volta/tools/image/node/16.10.0/bin/node
    Yarn: 1.22.11 - ~/.volta/tools/image/yarn/1.22.11/bin/yarn
    npm: 7.24.0 - ~/.volta/tools/image/node/16.10.0/bin/npm
    Watchman: 2021.09.27.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 13.0.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. Clone this repo
2. Navigate to the rn-tester folder `cd packages/rn-tester/`
3. Run `../../scripts/test-manual-e2e.sh`
4. Select RNTester, Android and Hermes

### Snack, code example, screenshot, or link to a repository

https://user-images.githubusercontent.com/11707729/151727453-e4c4428a-10f6-404a-bf6c-a12d774977b2.mov

**Comment by cortinico** [comment]
That's a vaid issue, thanks for reporting @gabrieldonadel 

Also saw your fix here: #33000
Ideally we should instead adapt the whole script to use `popd` and `pushd` (and `dirs` if needed). The reason is that we should not manipulate the current working directory directly with `cd` (or at least we should restore it correctly to the status it was before the script was invoked).
