### ISSUE TITLE
Platform.OS == 'ios' is not working

### ISSUE THREAD

**Issue by vishnusurabhirao** [facebook/react-native#32991]
### Description

Platform.OS is not working for iOS

### Version

0.63.3

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 12.1
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 388.05 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.11 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7935034
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.10 - /usr/bin/javac
    Python: 2.7.15 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

if(Platform.OS === 'ios') console.log(Platform.OS)

**Comment by mkrishnacarnow** [comment]
Yes , Platform.OS is not working for iOS

**Comment by ykrishna1985** [comment]
Yes, Platform.OS is not working for iOS.

**Comment by Raymond-Cox** [comment]
Simply reporting in, no issues with it on 0.66.3.

**Comment by saad9624-tribalScale** [comment]
same
