### ISSUE TITLE
More information on: Unable to resolve module node:http

### ISSUE THREAD

**Issue by kabundege** [facebook/react-native#32997]
### Description

I'm trying to make an HTTP request on an API,
The implementation in use works fine (I've been using it for a while now).

![Screen Shot 2022-01-29 at 20 46 47](https://user-images.githubusercontent.com/50319826/151673573-d6dbb1bf-2950-4dd5-aa0a-1cd10caccde4.png)

i installed node-fetch `^3.2.0` with `yarn add node-fetch`, 
when i import the file above, I immediately get
`Unable to resolve module node:http` in my the console `cmd`, 
and when i comment the import the error goes away.

## Suggestion
I also get this suggestion below.

**If you are sure the module exists, try these steps:**
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
 
**Screenshots**
![Screen Shot 2022-01-29 at 20 51 57](https://user-images.githubusercontent.com/50319826/151673787-1769346c-8a1b-42d7-b8ef-10f0fb7e8e72.png)

### Version

0.64.3

### Output of `npx react-native info`

ystem:
    OS: macOS 11.5.2
    CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
    Memory: 252.47 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.2 - /usr/local/bin/npm
    Watchman: 2022.01.17.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 28, 29, 30, 32
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 32.0.0
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7935034
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.3 => 0.64.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. `npm` 8.1.2 | `node` 16.13.1 | ` expo `~44.0.0
2.  yarn add node-fetch
3. run the code in the image above

### Snack, code example, screenshot, or link to a repository

![Screen Shot 2022-01-29 at 20 46 47](https://user-images.githubusercontent.com/50319826/151673573-d6dbb1bf-2950-4dd5-aa0a-1cd10caccde4.png)

**Comment by cortinico** [comment]
> `Unable to resolve module node:http` in my the console `cmd`,

You're not supposed to use Node HTTP as it's not available at runtime on React Native. Here a guide on how to do networking with React Native https://reactnative.dev/docs/next/network#using-fetch
