### ISSUE TITLE
Is iOS 6 supported?

### ISSUE THREAD

**Issue by marynate** [facebook/react-native#330]
Build to simulator with deployment target set to 6.0 works (by some hacks), but build to iOS 6.0 device only show up blank white view. Before wasting more time on hacking around, I would like to know if iOS 7.0 is the minimum deployment target react-native will support?

Thanks!

**Comment by zetachang** [comment]
JavaScriptCore (which you react native code executed on) is officially supported only in iOS 7+, but according to [this stackoverflow answer](http://stackoverflow.com/questions/23514579/javascriptcore-framework-availability-on-ios), it's possible to make JavaScriptCore linked correctly on iOS 6 with some hacks.

**Comment by vjeux** [comment]
We started React Native on iOS 6 and recompiled JavaScript core to get it working. But since iOS 7 provides JSC for free, we dropped compatibility. There's nothing fundamental preventing React Native from working on iOS6, it's just that so far it hasn't been worth the trouble keeping the backward compatibility.

Can you expand on your use case for iOS6?

**Comment by marynate** [comment]
My iOS game is targeting iOS 6+ devices now, never publish non-game app before, not sure if now it's the time to drop iOS 6 support totally. ( Last time I checked there're about 5% or so devices on iOS 6, probably not quite worth the effort to support? )

**Comment by ide** [comment]
iOS 6 usage is really low (2% according to https://developer.apple.com/support/appstore/) and there were major changes to the UI and JavaScript environment from 6 to 7. To my knowledge none of Facebook's apps are targeting iOS 6 anymore so the biggest contributor to React Native is not going to be testing on iOS 6. So practically speaking while you might be able to get RN running on iOS 6 it might be a bit like pushing boulders uphill to keep it running as new versions of RN are constantly released.
