### ISSUE TITLE
TextInput multiline = { false } not working in iOS

### ISSUE THREAD

**Issue by dinesh-fareye** [facebook/react-native#33004]
![Simulator Screen Shot - iPhone 12 - 2022-01-31 at 18 38 01](https://user-images.githubusercontent.com/87294671/151799001-86e11a2a-bbc1-493e-b8b7-294df5d26d30.png)
### Description

TextInput Multiline={ false } is not working for iOS. After adding **textAlign:'left**' and **writingDirection: 'ltr',**

<TextInput
           defaultValue='Password'
           placeholder='Password'
           underlineColorAndroid='transparent'
           placeholderTextColor="#C0C0C0"
           secureTextEntry={true}
           style={ styles.rtlTextStyle }
           multiline={false}
           />

rtlTextStyle : {
    writingDirection: 'ltr',
    textAlign: 'left',
    height :40
}

### Version

0.66.3

### Output of `npx react-native info`

System:
    OS: macOS 11.5.2
    CPU: (8) x64 Apple M1
    Memory: 34.84 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.22.7 - ~/.nvm/versions/node/v12.22.7/bin/node
    Yarn: Not Found
    npm: 6.14.15 - ~/.nvm/versions/node/v12.22.7/bin/npm
    Watchman: 2021.06.07.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7486908
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.12 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.3 => 0.66.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Create a new Component with Text Input and add following Style Sheet for textInput

textStyle : {
    writingDirection: 'ltr',
    textAlign: 'left',
    height :40
}

**Comment by sarinashish** [comment]
I am also facing this issue
