### ISSUE TITLE
[RCTConvert] NSString cannot be converted to NSNumber on v0.12.0

### ISSUE THREAD

**Issue by yelled3** [facebook/react-native#3300]
I just upgraded from `v0.11.0` to  `v0.12.0`;
After the upgrade I started getting crashes with the following error:
```obj-c
[RCTConvert.m:55] Error setting property 'borderColor' of RCTView with tag #1838: 
JSON value '#dddddd' of type NSString cannot be converted to NSNumber
```

@ide @brentvatne /cc

**UPDATE**
it seems `react-devtools` has 2 related issues:
https://github.com/facebook/react-devtools/issues/223
https://github.com/facebook/react-devtools/issues/214

**Comment by ide** [comment]
Are you setting the border color directly on a View or using another component? If the latter you may need to update it to call `processColor('#dddddd')` instead.

**Comment by yelled3** [comment]
@ide yeah I was doing:
```js
this.refs.container.setNativeProps({'borderColor': '#dddddd'});
```
so I should change it to?
```js
import React from 'react-native';
import { processColor } from React;

this.refs.container.setNativeProps({'borderColor': processColor('#dddddd')});
```

in what other cases should I be using `processColor`? couldn't find it in the docs...
was this added in `v0.12.0`?

**Comment by brentvatne** [comment]
If that's necessary, I feel like setNativeProps or precomputeStyle (which is used by setNativeProps) should be updated to use processColor automatically. Can you let us know if that's required @yelled3?

**Comment by xinthink** [comment]
Facing the same problem.
I'm trying to call `processColor` myself, but got `undefined`

```
const {processColor} = React;
console.log(processColor);
```

**Comment by wtz** [comment]
use processColor works on me

**Comment by xinthink** [comment]
Sorry, I just saw `processColor` exported in `react-native.js` of RN 0.12.0. so it should work for me either.

**Comment by yelled3** [comment]
@brentvatne 
>  Can you let us know if that's required

yes it is :-)

> If that's necessary, I feel like setNativeProps or precomputeStyle (which is used by setNativeProps) should be updated to use processColor automatically

agreed.

**Comment by skyline75489** [comment]
@xinthink I'm using 0.12.0. Why am I still getting `processColor is undefined` ?

**Comment by skyline75489** [comment]
And the error is not even from my own code. It's from https://github.com/corymsmith/react-native-icons/blob/master/SMXIconImage.ios.js

**Comment by jsierles** [comment]
@facebook-github-bot answered

**Comment by renso3x** [comment]
proccessColor will be pull out from react-native.

import { processColor } from 'react-native';
