### ISSUE TITLE
[Releases] Add path-specified filters to `rn-changelog-generator`

### ISSUE THREAD

**Issue by lunaleaps** [facebook/react-native#33012]
Filter out commits that touch certain "internal" files.

We currently use the rn-changelog-generator to generate our React Native release changelog: https://github.com/facebook/react-native/blob/main/CHANGELOG.md

The release process involves sanitizing the changelog before release. There's usually a lot of noise (ie. commits that only touch RNTester) that we could provide some rules to filter out of the generated changelog.

This issue is about adding generic filters (first use-case could be path-based) to this script.
Code lives here: https://github.com/microsoft/rnx-kit/tree/main/packages/rn-changelog-generator

**Comment by gabrieldonadel** [comment]
Hi, quick question regarding what you meant by `adding generic filters`, would this be adding a --exclude flag that filters out files that match a specific pattern, or would this be adding hardcoded paths to the `rn-changelog-generator` repo?

**Comment by lunaleaps** [comment]
Hmm I originally was thinking hardcoding paths -- it'll probably have to be that every path in the commit is under the filter for us to filter it out of the changelog

**Comment by lunaleaps** [comment]
Closing this issue for now since it's not a priority
