### ISSUE TITLE
[Releases] Move our release wiki to `react-native-website`

### ISSUE THREAD

**Issue by lunaleaps** [facebook/react-native#33014]
The release wiki here: https://github.com/facebook/react-native/wiki/Releases is hard for contributors without write access to edit.

It would do well to serve this information directly on the React Native website.

My suggestions:
* Let's first change our current "communities" page to have a sidebar like we do with our "guides" section
* Then let's move the release wiki over page by page

**Comment by Megatron4537** [comment]
Gotcha! I can do this one 😄

**Comment by lunaleaps** [comment]
Closing this as this was resolved with https://github.com/facebook/react-native-website/pull/2961, thanks again @Megatron4537 for your help!
