### ISSUE TITLE
[Releases] Extract changelog validation logic from `rn-changelog-generator`

### ISSUE THREAD

**Issue by lunaleaps** [facebook/react-native#33013]
The changelog generator currently takes in a set of commits, reads their commit messages, and if they follow a certain changelog format, formats those commit messages to what we see in the React Native changelog today.

We want to extract the validation logic in this script so we can "test" a commit message to see if it is in our valid changelog format -- which is currently defined here: 

This will be useful for us to block shipping any changes internally or in OSS that don't comply with the format.

Feel free to ask for more clarification!

**Comment by Megatron4537** [comment]
Going to work on this issue over the weekend. `-- which is currently defined here` did you mean to insert a link there? @lunaleaps

**Comment by Megatron4537** [comment]
@lunaleaps I made this PR. Let's talk about whether we want to enforce this commit convention as a git hook or instead have a script to test a message independently of git hooks.

**Comment by cortinico** [comment]
@lunaleaps Should we close this?
