### ISSUE TITLE
Create 0.68 Blog post

### ISSUE THREAD

**Issue by lunaleaps** [facebook/react-native#33010]
We'll need to write a post about the changes for 0.68! Unfortunately we'll need someone who has signed up as a Release Supporter/tester for this as you'll need access to the Release discord. 

Generally our release post covers any breaking changes, new features, any notable gotchas or something we want our community to be aware of. See our last release post ([0.67](https://reactnative.dev/blog/2022/01/19/version-067), [0.66](https://reactnative.dev/blog/2021/10/01/version-066)) for inspiration.

If anyone wants to take this on this work involves:

1. Creating a public google doc and sharing with release community 
2. Looking over the [0.68 changelog PR](https://github.com/facebook/react-native/pull/32993) and pulling out any call-outs (new version dependencies, new notable features)
    --> you might be able to look over [React Native Weekly's newsletters](https://andrei-calazans.com/tags/react-native-weekly) for any points -- make sure to attribute if using any of this information! 
3. Share it around the release community discord and ask for feedback.

Here is the 0.68 branch: https://github.com/facebook/react-native/tree/0.68-stable

**Comment by lunaleaps** [comment]
cc @AndreiCalazans if you have any insights on 0.68 callouts!

**Comment by AndreiCalazans** [comment]
Hey @lunaleaps, sorry for the late reply. I am still improving my notification management.

I can write the v0.68 post or support anyone doing it. Let's discuss on Discord or here.

**Comment by AndreiCalazans** [comment]
Hey @lunaleaps, sorry for the late reply. I am still improving my notification management.

I can write the v0.68 post or support anyone doing it. Let's discuss on Discord or here.

**Comment by kelset** [comment]
@AndreiCalazans I think it'd be great to get your insights into what are the most interesting/relevant changes from 0.67 to 0.68 - you always pay close attention at the commit history with your newsletter and I think it'd be great to leverage your analytical skills :)

Me and @ShikaSD can figure out the skeleton of the blogpost and we could use your help for the classic "highlights of this release" section (for example, see the one in 0.67 -> https://reactnative.dev/blog/2022/01/19/version-067#highlights-of-067).

We are still in the RC so no rush, but let us know if it's something you could help with :) ofc we'll make sure to have you among the authors :)

**Comment by AndreiCalazans** [comment]
@kelset sounds good. I will have something for you tomorrow Eastern-US TMZ afternoon.

**Comment by AndreiCalazans** [comment]
_ps: adding this comment to show progress, I want to review the commits below and verifying and explaining them next._


Here is a list of commits that could be highlighted:

- Possible candidates
    - Fix: Use same implementation for performance.now() on iOS and Android ([[1721efb54f](https://github.com/facebook/react-native/commit/1721efb54ff9cc4f577b5ae27f13fcf56801a92c)](https://github.com/facebook/react-native/commit/1721efb54ff9cc4f577b5ae27f13fcf56801a92c) by [[@mrousavy](https://github.com/mrousavy)](https://github.com/mrousavy))
    - TypeScript support for codegen (this might be a WIP)
        - Tests for TypeScript support for Native Module Codegen spec parsing ([[821382b9f7](https://github.com/facebook/react-native/commit/821382b9f779d7d3998b8a816c447bd3f4829b71)](https://github.com/facebook/react-native/commit/821382b9f779d7d3998b8a816c447bd3f4829b71) by [[@charlesbdudley](https://github.com/charlesbdudley)](https://github.com/charlesbdudley))
        - Tests for TypeScript support for Native Component Codegen spec parsing ([[f9e512e8fe](https://github.com/facebook/react-native/commit/f9e512e8fe07a12eb3fc07d4119c728733b484b8)](https://github.com/facebook/react-native/commit/f9e512e8fe07a12eb3fc07d4119c728733b484b8) by [[@charlesbdudley](https://github.com/charlesbdudley)](https://github.com/charlesbdudley))
        - Choose Flow or WIP TypeScript Codegen parser based on spec's file extension ([[078f6310ba](https://github.com/facebook/react-native/commit/078f6310ba5008224e8683c1463b248f447fefa8)](https://github.com/facebook/react-native/commit/078f6310ba5008224e8683c1463b248f447fefa8) by [[@charlesbdudley](https://github.com/charlesbdudley)](https://github.com/charlesbdudley))
        - Add WIP TypeScript support for Native Module Codegen spec parsing ([[0d3036abde](https://github.com/facebook/react-native/commit/0d3036abdef0dfe9642a6513350fa5d84eb3c961)](https://github.com/facebook/react-native/commit/0d3036abdef0dfe9642a6513350fa5d84eb3c961) by [[@charlesbdudley](https://github.com/charlesbdudley)](https://github.com/charlesbdudley))
        - Add WIP TypeScript support for Native Component Codegen spec parsing ([[7615bde023](https://github.com/facebook/react-native/commit/7615bde023000bd8a71cfbb8f9f8796db04cd3b6)](https://github.com/facebook/react-native/commit/7615bde023000bd8a71cfbb8f9f8796db04cd3b6) by [[@charlesbdudley](https://github.com/charlesbdudley)](https://github.com/charlesbdudley))
        - Add foundation for WIP TypeScript parser for Codegen ([[114d5a8a17](https://github.com/facebook/react-native/commit/114d5a8a1764a4dd6300a295d132e10779b132d7)](https://github.com/facebook/react-native/commit/114d5a8a1764a4dd6300a295d132e10779b132d7) by [[@charlesbdudley](https://github.com/charlesbdudley)](https://github.com/charlesbdudley))
    - Stop RedBox from appearing for LogBox handled errors ([[9d2df5b8ae](https://github.com/facebook/react-native/commit/9d2df5b8ae95b3cfeae26f64bd1d50bd2b0bbae9)](https://github.com/facebook/react-native/commit/9d2df5b8ae95b3cfeae26f64bd1d50bd2b0bbae9) by [[@liamjones](https://github.com/liamjones)](https://github.com/liamjones))
    - Split screen commit - Don't reconstruct app components https://github.com/facebook/react-native/issues/25040 ([[fc962c9b6c](https://github.com/facebook/react-native/commit/fc962c9b6c4bf9f88decbe014ab9a9d5c1cf51bc)](https://github.com/facebook/react-native/commit/fc962c9b6c4bf9f88decbe014ab9a9d5c1cf51bc) by [[@Somena1](https://github.com/Somena1)](https://github.com/Somena1))
    - Enable hitSlop to be set using a single number. ([[589b129581](https://github.com/facebook/react-native/commit/589b129581903a737a64e14eab3f2e29620831d5)](https://github.com/facebook/react-native/commit/589b129581903a737a64e14eab3f2e29620831d5) by [[@javache](https://github.com/javache)](https://github.com/javache))
    - Fixed empty screen after retrying a BundleDownloader failure in dev mode ([[c8d823b9bd](https://github.com/facebook/react-native/commit/c8d823b9bd9619dfa1f5851af003cc24ba2e8830)](https://github.com/facebook/react-native/commit/c8d823b9bd9619dfa1f5851af003cc24ba2e8830) by [[@samkline](https://github.com/samkline)](https://github.com/samkline))
    - Fix crash from ScrollView that occurs while reporting an error from JS ([[2151d11527](https://github.com/facebook/react-native/commit/2151d1152719a230565165f1a8dcfab172689eb3)](https://github.com/facebook/react-native/commit/2151d1152719a230565165f1a8dcfab172689eb3) by [[@JoshuaGross](https://github.com/JoshuaGross)](https://github.com/JoshuaGross))
    - Modal accepts a testID but didn't forward it to RCTModalHostView, therefore not making it show up for e2e tests depending on viewhierarchy. ([[5050e7eaa1](https://github.com/facebook/react-native/commit/5050e7eaa17cb417baf7c20eb5c4406cce6790a5)](https://github.com/facebook/react-native/commit/5050e7eaa17cb417baf7c20eb5c4406cce6790a5) by [[@GijsWeterings](https://github.com/GijsWeterings)](https://github.com/GijsWeterings))
    - onLayout prop is handled correctly in <KeyboardAvoidingView> ([[9c5e177a79](https://github.com/facebook/react-native/commit/9c5e177a79c64c77f281ce727538973e8222e975)](https://github.com/facebook/react-native/commit/9c5e177a79c64c77f281ce727538973e8222e975))
    - AnimatedValue.__detach should store getValue result with offset deducted ([[fe53cae954](https://github.com/facebook/react-native/commit/fe53cae954b37528eeaa1258ac0060c4298473bb)](https://github.com/facebook/react-native/commit/fe53cae954b37528eeaa1258ac0060c4298473bb) by [[@rozele](https://github.com/rozele)](https://github.com/rozele))
    - AnimatedValue.stopAnimation callback with correct value for NativeAnimated ([[8ba771c3dd](https://github.com/facebook/react-native/commit/8ba771c3ddc00b1499e95a2812b4cd5ac904c8df)](https://github.com/facebook/react-native/commit/8ba771c3ddc00b1499e95a2812b4cd5ac904c8df) by [[@rozele](https://github.com/rozele)](https://github.com/rozele))
    - Continue deprecation of PropTypes
        - Accessing Image.propTypes, Text.propTypes, TextInput.propTypes, ColorPropType, EdgeInsetsPropType, PointPropType, or ViewPropTypes now emits a deprecation warning. ([[3f629049ba](https://github.com/facebook/react-native/commit/3f629049ba9773793978cf9093c7a71af15e3e8d)](https://github.com/facebook/react-native/commit/3f629049ba9773793978cf9093c7a71af15e3e8d) by [[@yungsters](https://github.com/yungsters)](https://github.com/yungsters))
    - Adds a setSelection imperative method to TextInput ([[771ca921b5](https://github.com/facebook/react-native/commit/771ca921b59cc3b3fd12c8fe3b08ed150bcf7a04)](https://github.com/facebook/react-native/commit/771ca921b59cc3b3fd12c8fe3b08ed150bcf7a04) by [[@lyahdav](https://github.com/lyahdav)](https://github.com/lyahdav))
    - Initial work for Animated.Color support
        - New Animated.Color node ([[ea90a76efe](https://github.com/facebook/react-native/commit/ea90a76efef60df0f46d29228289f8fc1d26f350)](https://github.com/facebook/react-native/commit/ea90a76efef60df0f46d29228289f8fc1d26f350))
        - Support string color values in Animated.Color ([[d3a0c4129d](https://github.com/facebook/react-native/commit/d3a0c4129d6a5a7beced4e9aa62b2da4e3f4fed4)](https://github.com/facebook/react-native/commit/d3a0c4129d6a5a7beced4e9aa62b2da4e3f4fed4))

**Comment by lunaleaps** [comment]
@AndreiCalazans That looks like a great list! Want to get that in a google doc and share it on Discord? It might get more eyes there too
