### ISSUE TITLE
pointerEvents prop not working for IOS scroll views

### ISSUE THREAD

**Issue by ryancat** [facebook/react-native#33022]
### Description

The pointerEvents prop is added for Android in [this commit](https://github.com/facebook/react-native/commit/48f6967ae88100110160e1faf03e6c0d37e404bd). However, the IOS counterpart is still not added. This issue is to track that work.

### Version

0.68.0

### Output of `npx react-native info`

$ npx react-native info
npx: installed 638 in 25.018s
error Unrecognized command "info".
info Run "react-native --help" to see a list of all available commands.

### Steps to reproduce

Adding `pointerEvents="box-none"` or `pointerEvents="none"` to a ScrollView component won't stop the ScrollView from scrolling.

### Snack, code example, screenshot, or link to a repository

https://snack.expo.dev/amGNLPiBj

**Comment by hetanthakkar1** [comment]
@ryancat Can you please review my pull request #32956

**Comment by liquidvisual** [comment]
Please don't close, this is still an issue.

**Comment by t0ma5h** [comment]
Still an issue for me as well. `box-none` seems to not do what it's supposed to for ScrollView

**Comment by matt-like-entity** [comment]
This is still an issue. There are work-arounds but it would be nice if this worked out of the box.
