### ISSUE TITLE
 contain blink effect while navigating to another screen

### ISSUE THREAD

**Issue by umer-viabletree** [facebook/react-native#33035]
### Description

only in android when navigating from one screen to another screen in different stack blinks occur

NOTE:
**In AndroidManifest 
android:windowSoftInputMode="adjustResize"
visible in dark mood** 

https://user-images.githubusercontent.com/81979880/152296674-a67e58a7-31dd-4698-9faa-2de1317af436.mp4

### Version

0.64.2

### Output of `npx react-native info`

    OS: macOS 11.6.1
    CPU: (8) x64 Intel(R) Core(TM) i7-4750HQ CPU @ 2.00GHz
    Memory: 96.89 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
    Yarn: 1.22.10 - ~/Documents/Projects/AHA/AHA-MobileApp/node_modules/.bin/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm
    Watchman: 2021.12.20.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 23, 28, 29, 30, 32
      Build Tools: 30.0.2, 32.0.0
      System Images: android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7935034
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.2 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

for navigation, i am using react-native-router-flux

### Snack, code example, screenshot, or link to a repository

for navigation, I am using react-native-router-flux

**Comment by ddikodroid** [comment]
maybe you can set toe root view background color to be dark color using [this package](https://www.npmjs.com/package/@pnthach95/react-native-root-view-background)
