### ISSUE TITLE
GIFs are being sped up on iPhone 13 pro max.

### ISSUE THREAD

**Issue by heydrigh** [facebook/react-native#33039]
### Description

Rendering GIFs on iPhone 13 pro max are being played super fast. I have tried to limit the frame rate on the gif itself to 30 fps or even 60 fps, however on iPhone 13 it still plays too fast.
The gifs are being rendered on a Image inside a flatlist.

### Version

0.63.4

### Output of `npx react-native info`

System:
    OS: macOS 12.2
    CPU: (8) arm64 Apple M1
    Memory: 113.09 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.0 - /usr/local/bin/npm
    Watchman: 2022.01.24.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
    Python: 2.7.18 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Create a flatlist with a gif being rendered with the Image tag.
### Expected behavior
play gif on normal speed.

**Comment by sannguyen1996** [comment]
+1

**Comment by vuhpquang** [comment]
Same issue on iPhone 13 Pro Max

**Comment by cto-varun** [comment]
Happing with me too. 
I have added a gif in splash screen in the expo, For all the devices, the running time of the gif was 5 seconds 
but for iPhone 13 pro max it got completed in 2.5 seconds, double the speed. 

So in the end the animation seems to be running twice.

**Comment by cto-varun** [comment]
+1

**Comment by BcueB1U3** [comment]
+1

**Comment by cq0702** [comment]
+1

**Comment by Fred0218** [comment]
+1
how to fix

**Comment by blueC1023** [comment]
RCTUIImageViewAnimated.m
NSTimeInterval duration = displayLink.duration * displayLink.frameInterval;
=>
NSTimeInterval duration = displayLink.targetTimestamp - displayLink.timestamp;

**Comment by tikkichan4** [comment]
> RCTUIImageViewAnimated.m NSTimeInterval duration = displayLink.duration * displayLink.frameInterval; => NSTimeInterval duration = displayLink.targetTimestamp - displayLink.timestamp;

Confirmed this changes is already on react-native 0.68.2. But the GIFs are having speed up issue on IOS.

**Comment by RashVenkat6795** [comment]
+1

**Comment by sansui-orz** [comment]
> RCTUIImageViewAnimated.m NSTimeInterval duration = displayLink.duration * displayLink.frameInterval; => NSTimeInterval duration = displayLink.targetTimestamp - displayLink.timestamp;

It work for me.

**Comment by cq0702** [comment]
> 

+1

**Comment by cq0702** [comment]
> > RCTUIImageViewAnimated.m NSTimeInterval duration = displayLink.duration * displayLink.frameInterval; => NSTimeInterval duration = displayLink.targetTimestamp - displayLink.timestamp;
> 
> Confirmed this change is already on react-native 0.68.2. But the GIFs are still having speed up issue on IOS.

+1
