### ISSUE TITLE
Apk not supporting in latest android versions

### ISSUE THREAD

**Issue by somagonda** [facebook/react-native#33031]
### Description

My react native app is not supporting in latest Android phone but working fine lower Android versions. Any solution please help me

### Version

0.66

### Output of `npx react-native info`

Not working react native apk

### Steps to reproduce

Ask minversion 21
Compilesdkversion 30

**Comment by cortinico** [comment]
> My react native app is not supporting in latest Android phone

Please provide more context and fill in the issue details (`npx react-native info`). A reproducer would also help.

**Comment by somagonda** [comment]
After Genrating signed apk it is working only in lower Android versions like 9 or below than 9.
It is not working in Android 10 and 11 
Login is not working but working in lower Android versions
