### ISSUE TITLE
Android headless JS timeouts not working

### ISSUE THREAD

**Issue by marcesengel** [facebook/react-native#33043]
### Description

Currently `TimingModule` related operations don't work reliably in background tasks, as noted in the [docs](https://reactnative.dev/docs/headless-js-android#caveats)
> The function passed to `setTimeout` does not always behave as expected. Instead the function is called only when the application is launched again. If you only need to wait, use the retry functionality.

this issue https://github.com/invertase/react-native-firebase/issues/3955
> Throwing a headlessJsTaskError seems the only way to make setTimeout work in the headless js task.

and [this StackOverflow question](https://stackoverflow.com/questions/45661676/timeout-in-a-react-native-headless-js-task/70971514#70971514).
> I am developing a react-native applicaton with a headless js task to make some background work.
>
> I need to execute some code after an amount of time, but noticed that using setTimeout execution gets suspended until the app is again in foreground.
> 
> Anyone has idea why this happens and know how to solve or workaround this?

I myself recently stumbled upon this issue as well and went into debugging it. For my findings and the solution I'll create a PR shortly.

### Version

all

### Output of `npx react-native info`

Issue is independent of build system and `react-native` version.

### Steps to reproduce

Create a headless JS task using some `TimingModule` related code (for example `setTimeout`) and execute it while the app is in background (for example using a FCM data-only message).

### Snack, code example, screenshot, or link to a repository

Example headless JS task handler:
```js
module.exports = async (taskData) => {
  console.log('started headless JS task')
  await new Promise(resolve => setTimeout(resolve, 1))
  console.log('resolved timeout')
}
```

**Comment by Alexufo** [comment]
have you solved it?
