### ISSUE TITLE
e2e tests failing

### ISSUE THREAD

**Issue by mkonicek** [facebook/react-native#3304]
Sample failure:
https://travis-ci.org/facebook/react-native/jobs/84474997

The error is "Cannot find module '../../babelRegisterOnly'" in `packager/packager.js`:
https://github.com/facebook/react-native/blob/master/packager/packager.js#L11

**Comment by ide** [comment]
The problem is that babelRegisterOnly needs to be included in the list of files published to npm. I'm about about to crash so if @martinbigio could get to this that'd be awesome.

**Comment by mkonicek** [comment]
Pinged Martín on messenger, he's in New York so will be around later today.

**Comment by martinbigio** [comment]
I'll move the file to `/packager` which is already exported

**Comment by martinbigio** [comment]
I need to wait for fb specific tests to run as we use this internally as well. The fix should land on github in about 2 hours :)

**Comment by mkonicek** [comment]
Thank you @martinbigio!

**Comment by ide** [comment]
Tests are green -- thanks!
