### ISSUE TITLE
textContentType ={'oneTimeCode'} not working in iOS

### ISSUE THREAD

**Issue by MiteshJabuani** [facebook/react-native#33059]
### Description

<TextInput
            placeholder="First Name"
            textContentType={'oneTimeCode'}
            autoCorrect={true}
            keyboardType={'numeric'}
            placeholderTextColor={'#262626'}
            style={{height: 50, backgroundColor: 'green'}}
          />

### Version

0.64.2

### Output of `npx react-native info`

I have iPhone 11 which has a 15.3.

### Steps to reproduce

Simply create a new react project with a new React-native version and I have iPhone 11 which has a 15.3 version but not working.

**Comment by Mitesh-2009** [comment]
![IMG_6709](https://user-images.githubusercontent.com/34374930/153192048-8a248474-fa38-4c20-b694-c5144320b0a5.jpg)
I need this type of functionality but not getting in my device, I have iPhone 11 with 15.3 IOS version

**Comment by MRezaBaiat** [comment]
Same here , not working...

**Comment by jp928** [comment]
Same. Is this related to iOS version, I remember it was working couple weeks ago.

**Comment by Mitesh-2009** [comment]
I do not find out the official link for apple that that type of functionality is not available for the next iOS version

**Comment by Mitesh-2009** [comment]
Anyone, please help me.....

**Comment by Mitesh-2009** [comment]
Anyone who gone help me, please....

**Comment by MortadhaFadhlaoui** [comment]
Same here

**Comment by nagasai65** [comment]
Any solution for this?
