### ISSUE TITLE
Unable to find a specification for `React-logger (= 0.67.2)` depended upon by `ReactCommon/turbomodule/core`

### ISSUE THREAD

**Issue by Manish2612** [facebook/react-native#33061]
### Description

I am using Monorepo for my react-native apps, App is working fine before trying to upgrade. I am trying to upgrade react-native version using web helper tool available in documentation. while doing pod install I am getting error 
 
 ```
[!] Unable to find a specification for `React-logger (= 0.67.2)` depended upon by `ReactCommon/turbomodule/core`

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```

### Version

0.67.2

### Output of `npx react-native info`

System:
    OS: macOS 11.3
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
    Memory: 182.65 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.4.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.3
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_222 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: 0.67.2 => 0.67.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. Update files according to web upgrade tool for v0.64.2 => v0.67.2
2. Install dependencies
3. `pod install` in ios folder

**Comment by ytl6547** [comment]
Add `pod 'React-logger', :path => '../node_modules/react-native/ReactCommon/logger'`

**Comment by cortinico** [comment]
Are you using `use_react_native` from `react_native_pods.rb`? Pods should already be configured for you. The solution provided by @ytl6547 should also work 👍
