### ISSUE TITLE
What did 0.12 change?

### ISSUE THREAD

**Issue by leafduo** [facebook/react-native#3307]
We found out that version 0.12 was released today, but not as usual, the change log contains almost nothing about what have changed.

Where can we find the change log? We need it to guide our upgrade process.

**Comment by chirag04** [comment]
Hopefully @ide will add some more info over time. It's a community effort, got to be patient :)

**Comment by ide** [comment]
FYI I'm focusing on the 0.13 release. @mkonicek has a better idea of what's in 0.12 than I do.

**Comment by yipengmu** [comment]
can Version 0.12  support load remoteJS by url?

**Comment by mkonicek** [comment]
@yipengmu Not yet on Android but there's a open PR which we can cherry-pick to 0.13.

**Comment by leafduo** [comment]
Anyone still on this?

**Comment by satya164** [comment]
@mkonicek +1 for cherry-picking it

**Comment by mkonicek** [comment]
For reference that PR is https://github.com/facebook/react-native/pull/3189

We're focused on the 0.13 release now, for now your best bet is looking at the commits, sorry there are no detailed release notes for 0.12: https://github.com/facebook/react-native/releases/tag/v0.12.0

**Comment by mschipperheyn** [comment]
Getting lots of weird errors after upgrading from 0.11.4 to 0.12. I feel there are some required upgrade aspects that are not documented and that are not solved by simply removing node-modules/react-native and reinstalling

**Comment by mschipperheyn** [comment]
This sometimes helps, but not in this case
* Close Xcode
* rm -rf ~/Library/Developer/Xcode/DerivedData/*
* cd $TMPDIR
* rm react-packager-cache-*

First, I get a syntax error in packager.js that is basically the parser not recognizing es6 object literal shorthand. After I manually fix this, I get

	Error: Error validating module options: child "platform" fails because ["platform" is required]
		at /Users/Shared/java/projects/project/node_modules/react-native/packager/react-packager/src/lib/declareOpts.js:60:13
		at /Users/Shared/java/projects/project/node_modules/react-native/packager/react-packager/src/Server/index.js:161:20
		at tryCallOne (/Users/Shared/java/projects/project/node_modules/react-native/node_modules/promise/lib/core.js:37:12)

So, I'm assuming some undocumented external dependency needs to be updated

**Comment by mschipperheyn** [comment]
https://github.com/facebook/react-native/issues/2645
