### ISSUE TITLE
IOS fetch发起网络请求，部分手机请求阶段报错TypeError: network request failed

### ISSUE THREAD

**Issue by 0906014109** [facebook/react-native#33080]
### Description

iphoneX，
系统版本15.2.1，
用fetch发起网络请求，
请求阶段报错 TypeError: network request failed。

目前仅发现IOS这个版本出现此问题

### Version

0.57.5

### Output of `npx react-native info`

React Native Environment Info:
    System:
      OS: macOS 12.1
      CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
      Memory: 46.05 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.16.3 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 7.23.0 - /usr/local/bin/npm
      Watchman: 2021.12.06.00 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
      Android SDK:
        API Levels: 23, 27, 28, 29
        Build Tools: 27.0.3, 28.0.2, 28.0.3, 29.0.2, 29.0.3
        System Images: android-23 | Intel x86 Atom_64, android-27 | Intel x86 Atom_64, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5977832
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.1 => 16.6.1 
      react-native: ^0.57.5 => 0.57.8 
    npmGlobalPackages:
      react-native-canvas: 0.1.24
      react-native-cli: 2.0.1
      react-native-code-push: 6.2.0
      react-native-highlight-words: 1.0.1

### Steps to reproduce

发送网络请求，提示此错误，无法抓包

**Comment by 0906014109** [comment]
<key>NSAppTransportSecurity</key> 
<dict> 
    <key>NSAllowsArbitraryLoads</key><true/>
</dict>
这种方法并未解决问题

**Comment by 0906014109** [comment]
“<key>NSAppTransportSecurity</key> 
<dict> 
    <key>NSAllowsArbitraryLoads</key><true/>
</dict>”

**Comment by 0906014109** [comment]
<key>NSAppTransportSecurity</key> 
<dict> 
    <key>NSAllowsArbitraryLoads</key><true/>
</dict>

**Comment by rockey2020** [comment]
我也碰到了这个问题

**Comment by cortinico** [comment]
Closing as we're accepting issues only in English. Please udpate the description and title and feel free to re-open
