### ISSUE TITLE
Build error on iOS (macOs 12.2.1) 

### ISSUE THREAD

**Issue by Ghoral** [facebook/react-native#33091]
### Description

I recently upgraded to macOS 12.2.1 and it won't build the app.

Error log: `Command PhaseScriptExecution failed with a nonzero exit code` this is the only error that shows in the log viewer.
No issue with the previous macOS version.

Versions:
react-native : "0.66.3"
react : "17.0.2"

### Version

0.66.3

### Output of `npx react-native info`

 OS: macOS 12.2.1
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 3.02 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.2 - /usr/local/bin/npm
    Watchman: 2022.01.03.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 28, 29, 30, 31, 32
      Build Tools: 28.0.2, 28.0.3, 29.0.2, 30.0.2, 30.0.3, 32.0.0
      System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8139111
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.3 => 0.66.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. Open Xcode.
2. Click build.
3. Build Failed

**Comment by uniquejava** [comment]
Same to me , fresh react native Hello world not running on my mac 2020

<img width="1104" alt="image" src="https://user-images.githubusercontent.com/1049271/160080577-6a9e71fc-20d8-404d-9fd8-0b041ddd596a.png">



```bash
$ pwd
/Users/cyper/github/AwesomeTSProject
$ react-native info
info Fetching system and libraries information...
System:
    OS: macOS 12.3
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Memory: 808.95 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.0 - ~/.nvs/node/16.14.0/x64/bin/node
    Yarn: 1.22.17 - ~/.nvs/node/16.14.0/x64/bin/yarn
    npm: 8.5.3 - ~/.nvs/node/16.14.0/x64/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 13.3/13E113 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.14.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.67.4 => 0.67.4
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by uniquejava** [comment]
Fixed by running the following command

```bash
NODE_BINARY=$(which node) npx react-native run-ios
```

From: https://stackoverflow.com/a/70012283
