### ISSUE TITLE
Examples license

### ISSUE THREAD

**Issue by Calinou** [facebook/react-native#331]
https://github.com/facebook/react-native/blob/master/LICENSE-examples

Please, consider putting the examples under BSD license or public domain (CC0).

**Comment by jaygarcia** [comment]
+1.  This is something that should be seriously considered.

**Comment by galoppa** [comment]
+1 Why have all the examples been [changed from BSD to a non-free license (just 19 hours ago)](https://github.com/facebook/react-native/commit/b1827af7dc6a03d687c3ab91bf0c6bc9f868e34f)?

**Comment by bootstraponline** [comment]
:+1: Please make it open source.

**Comment by zackp30** [comment]
:+1: Please consider open-sourcing the examples.

**Comment by spicyj** [comment]
I'm not a lawyer but my understanding is that this is the only license we felt comfortable releasing the examples under. Sorry I can't be more help.

**Comment by bootstraponline** [comment]
What does Facebook gain by [relicensing the examples](https://github.com/facebook/react-native/commit/b1827af7dc6a03d687c3ab91bf0c6bc9f868e34f) so they're no longer open source? It's a shame [regressive licensing](https://news.ycombinator.com/item?id=9271331) (starting as open then restricting rights) is overshadowing the actual technology in terms of the community reception.

It doesn't inspire confidence that Facebook randomly relicenses previously open sourced code.

**Comment by ProfessorKaos64** [comment]
> I'm not a lawyer but my understanding is that this is the only license we felt comfortable releasing the examples under. Sorry I can't be more help.

That's a peculiar "reason" by any stretch. Sad.

**Comment by bootstraponline** [comment]
Facebook [updated the patent grant](https://code.facebook.com/posts/1639473982937255/updating-our-open-source-patent-grant/). :+1:
