### ISSUE TITLE
Trying to convert starter project to Android library not building

### ISSUE THREAD

**Issue by anirudhagarwal1** [facebook/react-native#33106]
### Description

I have a react native Android application written which I am trying to export as a module(aar file), but facing some issues. 

To keep things simple I tried to first export a starter project as a library but facing issues there too 
Command used to create a starter react native project - 

`npx react-native init ExperimentApp`

I changed the applicationVariants to libraryVariants in the build.gradle file to support android libraries. 

The project fails in the gradle sync itself with and exception in react.gradle file

```
* Where:
Script '/Users/anirudhagarwal/work/Asgard/node_modules/react-native/react.gradle' line: 353
> Cannot invoke method doFirst() on null object
```

Is it not possible to export an android library with react native as a dependency?

Checked on 0.67, 0,66.0 and 0.63.4

### Version

0.63.4

### Output of `npx react-native info`

System:
    OS: macOS 12.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.66 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.16.2 - ~/.nvm/versions/node/v12.16.2/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.16.2/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 23, 25, 26, 28, 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0
      System Images: android-21 | Google APIs Intel x86 Atom_64, android-22 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8139111
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_202 - /usr/bin/javac
    Python: 2.7.16 - /Library/Frameworks/Python.framework/Versions/2.7/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages

### Steps to reproduce

1. Create a new app using 

`npx react-native init ExperimentApp`

2. In app level build.gradle file, in the first line, change com.android.application to com.android.library
3. In the same file, change applicationVariants to libraryVariants. 
4. Build the app using ./gradlew assembleDebug

**Comment by cortinico** [comment]
You're on a really old version of RN (0.63 while now we're about to release 0.68).
Could you update and try again? 

Also, can you please explain what you're trying to do? Why are you converting an app to a library? What's your use case?

**Comment by anirudhagarwal1** [comment]
Will try to get back with the latest version. 
For the use case, we have an existing brownfield app and now we want to add that as a module/sub-app inside another application.

**Comment by cortinico** [comment]
> Will try to get back with the latest version.

Closing due to no follow ups. Feel free to re-open once you have the requested informations 👍
