### ISSUE TITLE
Upgrading to 0.67.2 failed to build

### ISSUE THREAD

**Issue by wdjunaidi** [facebook/react-native#33109]
### New Version

0.67.2

### Old Version

0.66.4

### Build Target(s)

android simulator

### Output of `react-native info`

❯ npx react-native info
info Fetching system and libraries information...
System:
    OS: macOS 12.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 24.41 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: Not Found
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
    Watchman: 2022.01.31.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /var/folders/f8/nhj6gdrx6c557yr942xcs1xh0000gn/T/frum_21795_1644870251479/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 29.0.2, 29.0.3, 30.0.2
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom_64, android-30 | Google Play Intel x86 Atom
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7784292
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /Users/wirianto/.sdkman/candidates/java/current/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.67.2 => 0.67.2
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Issue and Reproduction Steps

Upgrading to `0.67.2` from `0.66.4` failed to build for Android, but fine for iOS.

**To reproduce:**
1. Create new react-native project with `npx react-native init TestUpgrade --version 0.66.4 --template react-native-template-typescript`
2. Go into the project folder - `cd TestUpgrade`
3. Check the package.json file to ensure it is having `react-native@0.66.4`. If not, downgrade by `npm I --save react-native@0.66.4`
4. Build and run the project - `npm run android`
5. Once the project run successfully, close the emulator and metro.
6. Upgrade to react-native@0.67.2 - `npx react-native upgrade`
7. Resolve any merge conflict
8. Reinstall dependencies - `npm i`
9. Run the project again - `npm run android`. The app will failed with message regarding DatePickerAndroid.
<img width="451" alt="Screen Shot 2022-02-15 at 9 13 21 AM" src="https://user-images.githubusercontent.com/1240283/153943121-95c1241a-17a3-41f7-ad05-aabbc7cd2897.png">

**Comment by wdjunaidi** [comment]
I found that inside `node_modules/react-native/Libraries/Components/DatePickerAndroid` there is indeed no files with those expected extensions, but there is a file named `NativeDatePickerAndroid.js`. When I manually rename the file to `DatePickerAndroid.js`, it builds successfully.

So something must be configured wrongly for _upgrade_ operation. Because when I create a fresh project directly using `0.67.2`, it builds successfully.

**Comment by joe-sam** [comment]
Not really a good idea to manually rename files in node_modules.
 These are special folders generated on each repo clone and npm build and can lead to strange bugs for those trying to reproduce from source .
 
 According to the doc from version 0.66.3 (?) due to the LeanCore approach, to quote

'**DatePickerAndroid** has been removed from React Native. 
 It can now be installed and imported from '@react-native-community/datetimepicker' instead of 'react-native'. 
 See [https://github.com/react-native-datetimepicker/datetimepicker](https://github.com/react-native-datetimepicker/datetimepicker)',
 
 NativeDatePickerAndroid.js appears not to have been removed by some minor oversight and may disappear eventually as an undocumented API.

**Comment by dexterowy** [comment]
In my case even more weird error. After building on iOS there is error about `DatePickerAndroid` which is not even used in my app

```
Unable to resolve module ./Libraries/Components/DatePickerAndroid/DatePickerAndroid from /Users/##/Documents/##/node_modules/react-native/index.js: 

None of these files exist:
  * node_modules/react-native/Libraries/Components/DatePickerAndroid/DatePickerAndroid(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.svg|.native.svg|.svg)
  * node_modules/react-native/Libraries/Components/DatePickerAndroid/DatePickerAndroid/index(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.svg|.native.svg|.svg)
> 1 | /**
  2 |  * Copyright (c) Facebook, Inc. and its affiliates.
  3 |  *
  4 |  * This source code is licensed under the MIT license found in the

RCTFatal
__28-[RCTCxxBridge handleError:]_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
-[NSRunLoop(NSRunLoop) runMode:beforeDate:]
-[NSRunLoop(NSRunLoop) runUntilDate:]
+[RNSplashScreen show]
-[AppDelegate application:didFinishLaunchingWithOptions:]
-[UIApplication(OneSignalReactNative) oneSignalApplication:didFinishLaunchingWithOptions:]
-[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:]
-[UIApplication _callInitializationDelegatesWithActions:forCanvas:payload:fromOriginatingProcess:]
-[UIApplication _runWithMainScene:transitionContext:completion:]
-[_UISceneLifecycleMultiplexer completeApplicationLaunchWithFBSScene:transitionContext:]
_UIScenePerformActionsWithLifecycleActionMask
__101-[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:]_block_invoke
-[_UISceneLifecycleMultiplexer _performBlock:withApplicationOfDeactivationReasons:fromReasons:]
-[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:]
-[_UISceneLifecycleMultiplexer uiScene:transitionedFromState:withTransitionContext:]
__186-[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:]_block_invoke
+[BSAnimationSettings(UIKit) tryAnimatingWithSettings:actions:completion:]
_UISceneSettingsDiffActionPerformChangesWithTransitionContext
-[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:]
__64-[UIScene scene:didUpdateWithDiff:transitionContext:completion:]_block_invoke.576
-[UIScene _emitSceneSettingsUpdateResponseForCompletion:afterSceneUpdateWork:]
-[UIScene scene:didUpdateWithDiff:transitionContext:completion:]
-[UIApplication workspace:didCreateScene:withTransitionContext:completion:]
-[UIApplicationSceneClientAgent scene:didInitializeWithEvent:completion:]
-[FBSScene _callOutQueue_agent_didCreateWithTransitionContext:completion:]
__94-[FBSWorkspaceScenesClient createWithSceneID:groupID:parameters:transitionContext:completion:]_block_invoke.180
-[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:]
__94-[FBSWorkspaceScenesClient createWithSceneID:groupID:parameters:transitionContext:completion:]_block_invoke
_dispatch_client_callout
_dispatch_block_invoke_direct
__FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__
-[FBSSerialQueue _targetQueue_performNextIfPossible]
-[FBSSerialQueue _performNextFromRunLoopSource]
__CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
__CFRunLoopDoSource0
__CFRunLoopDoSources0
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
-[UIApplication _run]
UIApplicationMain
main
start_sim
0x0
```

**Comment by dysfunctional-apps** [comment]
Having this exact issue in both Android and iOS (tested on both Windows and Mac with the reproduction steps), not quite sure how I'm supposed to upgrade if the out of the box template can't

**Comment by dysfunctional-apps** [comment]
After some head banging I managed to overcome this

First use the upgrade helper website to manually upgrade (adding/removing/modifying files as necessary), I went from 0.66.4 to 0.67.4: https://react-native-community.github.io/upgrade-helper/?from=0.66.4&to=0.67.4

NB: you shouldn't need to make any changed to the project.pbxproj file, it just regenerates ids and jiggles things around for no apparent reason, and never normally needs touching: 

Next if you are using android, do your npm install, and then go into the android directory and run "gradlew.bat clean" and the next run of "npx react-native run-android" should succeed

If you are using iOS however, it's a little bit more of a pain, I think it holds onto something that it can't let go of even if you do a clean in XCode, so check in all your changes, and push them to your remote repo, and then check them out afresh in a new path, run "npm install", "npx react-native link" (should be unnecessary but did get a "have you run link" message without), and finally a "pod install", running "npx react-native run-ios" should now work!!

This is not the first time the upgrade command has failed me, it is a waste if time!
