### ISSUE TITLE
[Android] fetch return Network Request failed with Letsencrypt HTTPS websites

### ISSUE THREAD

**Issue by Scarle-t** [facebook/react-native#33111]
### Description

Since [the issue](https://github.com/facebook/react-native/issues/25244#issue-455453713) has been closed and I've already tried numerous "solutions" from that issue/ SO/ Internet but still no hope. 
When doing a fetch request to a site using Letsencrypt certificate, it throws "Network Request failed" error on Android, works fine on iOS (both platforms' physical and emulator device behave the same)

The following code will return Network Request failed
```js
fetch([redacted url using letsencrypt certificate], {
method: 'POST',
headers: {
    'Accept': 'application/json',
    'Content-Type': 'application/json'
},
body: JSON.stringify(someData)
}).then(res => res.json()).then(res => someFn()).catch(e => console.error(e))
```

I tried the same fetch with ```https://google.com``` it worked

### Version

0.64.0

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 12.1
    CPU: (8) arm64 Apple M1
    Memory: 82.48 MB / 16.00 GB
    Shell: 3.3.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 17.5.0 - /opt/homebrew/bin/node
    Yarn: Not Found
    npm: 8.4.1 - /opt/homebrew/bin/npm
    Watchman: 2022.02.07.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0
      System Images: android-25 | Google APIs ARM EABI v7a, android-31 | ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7784292
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_302 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.0 => 0.64.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

create project
make a fetch request to a https site

### Snack, code example, screenshot, or link to a repository

```js
fetch([redacted url using letsencrypt certificate], {
method: 'POST',
headers: {
    'Accept': 'application/json',
    'Content-Type': 'application/json'
},
body: JSON.stringify(someData)
}).then(res => res.json()).then(res => someFn()).catch(e => console.error(e))
```

**Comment by vaibhawc** [comment]
I too am facing same issue with urls that would work on browser but not on the app on same android phone.

**Comment by hoaxvo16** [comment]
You can try my solution

https://github.com/facebook/react-native/issues/24627#issuecomment-1049496059

**Comment by flyskywhy** [comment]
[fixed `TypeError: Network request failed` when upload file to http not https with Android debug builds](https://github.com/facebook/react-native/issues/33217#issuecomment-1159844475)

**Comment by Aiosa** [comment]
I am facing the same problem. Moreover, I noticed that this occurs (at least for me) only for certificates using `2048 bit RSA`, `4096 bit` works well, and it happens only on older android devices (don't know the boundary but the guess is version 7 and below)

**Comment by Aiosa** [comment]
After some digging, all sites I've tried are missing the last part in the chain when they failed to load:
```Certificate chain
 0 s:CN = www.seznam.cz
   i:C = US, O = Let's Encrypt, CN = R3
 1 s:C = US, O = Let's Encrypt, CN = R3
   i:C = US, O = Internet Security Research Group, CN = ISRG Root X1
 2 s:C = US, O = Internet Security Research Group, CN = ISRG Root X1
   i:O = Digital Signature Trust Co., CN = DST Root CA X3                                   <--- this one
```
