### ISSUE TITLE
missing requests when we use cloudflare in Iran

### ISSUE THREAD

**Issue by ProMasoud** [facebook/react-native#33119]
### Description

Hi there,

We have a problem in ReactNative networking, when we sent a request in android after a while request missing and no response returned and we got a TIMEOUT error. It doesn't matter how much is timeout. we never get a response from server.
We checked server side to trace request we see the request never got to server. When we use Cloudflare as CDN and Proxy for our servers.
We tried multiple method for sending requests (Axios, Fetch) but same result. There is a problem in react native core networking module. This problem happen in just some ISPs like TCI, MCI in Iran. Others is ok.

We thought this is because of IPV6 but we could change priorates to IPV4 ([see this](https://github.com/facebook/react-native/issues/29608)) and now we are hopeless!

Also we test these requests in Flutter Dio package every thing working perfect.

Now we have some question?

1. How we can modify React native core networking module (OkHttp)?
2. Is there any way to trace request in android (problem not related to react native JS side)? 

### Version

0.65.1

### Output of `npx react-native info`

System:
    OS: macOS 12.2
    CPU: (8) arm64 Apple M1
    Memory: 85.56 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.4.0 - /opt/homebrew/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.3.1 - /opt/homebrew/bin/npm
    Watchman: 2022.01.24.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8092744
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.65.1 => 0.65.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. create new project
2. use axios or fetch to cloudflare behind api in Iran

**Comment by dawidzawadzki** [comment]
@ProMasoud Did you find a solution? I have a similar issue.
