### ISSUE TITLE
Application crashes when notification receive in background

### ISSUE THREAD

**Issue by yasir-systemplus** [facebook/react-native#33112]
### Description

Hi Folks!

I have been facing this issue for very long time. When notification is received in background, application crashes. We are using [Rn FIrebase FCM](https://rnfirebase.io/messaging/usage) 

App only crashes in quit state. It works fine in background and foreground. I am attaching the log from Crashlytics of firebase. 

```
Fatal Exception: com.facebook.react.common.JavascriptException
TypeError: Cannot read property 'insets' of null, js engine: hermes, stack: anonymous@1:1364715 loadModuleImplementation@1:80203 guardedLoadModule@1:79751 metroRequire@1:79379 anonymous@1:1362660 loadModuleImplementation@1:80203 guardedLoadModule@1:79751 metroRequire@1:79379 anonymous@1:600754 loadModuleImplementation@1:80203 guardedLoadModule@1:79751 metroRequire@1:79379 anonymous@1:86756 loadModuleImplementation@1:80203 guardedLoadModule@1:79708 metroRequire@1:79379 global@1:78965
```

### Version

0.67.2

### Output of `npx react-native info`

System:
    OS: Windows 10 10.0.22000
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
    Memory: 1.97 GB / 15.84 GB
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 29, 30, 32
      Build Tools: 30.0.2, 30.0.3, 32.0.0, 32.1.0
      System Images: android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: Not Found
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.67.2 => 0.67.2
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1) Quit app from minimized tray. 
2) Receive notification in quit state. 
3) Tap or receive more notifications. 

Application crashes. 

### Snack, code example, screenshot, or link to a repository

![Screenshot_2](https://user-images.githubusercontent.com/88422920/154014634-564c2ecc-652d-4fad-945b-6398fce51d0e.png)

https://user-images.githubusercontent.com/88422920/154014406-c919e646-c7bb-4998-81ec-674906c979c7.mp4

**Comment by gokul1099** [comment]
![image](https://user-images.githubusercontent.com/42144106/155324124-adcf4753-4d13-4ff0-924a-38253761bfa7.png)

I faced the same issue. then I tried removing the above line from  my android/app/src/main/AndroidManifest.xml file and it worked without any issues

**Comment by yasir-systemplus** [comment]
> ![image](https://user-images.githubusercontent.com/42144106/155324124-adcf4753-4d13-4ff0-924a-38253761bfa7.png)
> 
> I faced the same issue. then I tried removing the above line from my android/app/src/main/AndroidManifest.xml file and it worked without any issues

I dont use this line inside AndroidManifest.xml 

Here is AndroidManifest.xml 

`<manifest xmlns:android="http://schemas.android.com/apk/res/android" package=XXXXXX">
  <uses-permission android:name="android.permission.INTERNET" />
  
  <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
   <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
   <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
  <uses-permission android:name="android.permission.DOWNLOAD_WITHOUT_NOTIFICATION" />
   <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
  <application 
  android:name=".MainApplication" android:label="@string/app_name" android:icon="@mipmap/ic_launcher" android:roundIcon="@mipmap/ic_launcher_round" android:allowBackup="false" android:theme="@style/AppTheme">

     <meta-data
     android:name="com.google.android.geo.API_KEY"
     android:value="XXXXXXX"/>

   
   <uses-library android:name="org.apache.http.legacy" android:required="false"/>
    
    
    <activity android:name=".MainActivity" android:label="@string/app_name" android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode" android:launchMode="singleTask" android:windowSoftInputMode="adjustPan" android:screenOrientation="portrait">
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
        <action android:name="android.intent.action.DOWNLOAD_COMPLETE"/>

      </intent-filter>
    </activity>
  </application>
</manifest>`

**Comment by yasir-systemplus** [comment]
> There will be two AndroidManifest.xml one will be in android/app/src/main and another in android/app/src/debug. have you checked both. for me it was in main

Yes, I have checked. There was nothing relevant to firebase services.

**Comment by yasir-systemplus** [comment]
Anybody have any idea about it?
