### ISSUE TITLE
`useColorScheme` is using deprecated EventEmitter.removeListener(), causing yellow warning

### ISSUE THREAD

**Issue by cjpete** [facebook/react-native#33114]
### Description

When using the `useColorScheme()` hook, a warning in the console is printed:

> EventEmitter.removeListener('change', ...): Method has been deprecated. Please instead use `remove()` on the subscription returned by `EventEmitter.addListener`

### Version

0.67.2

### Output of `npx react-native info`

System:
    OS: macOS 11.6.2
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 102.17 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.3 - ~/.nvm/versions/node/v14.17.3/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.17.3/bin/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.3/bin/npm
    Watchman: 2021.10.18.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /Users/cjpitt/.rvm/gems/ruby-2.7.4/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 23, 26, 27, 28, 29, 30
      Build Tools: 27.0.3, 28.0.0, 28.0.2, 28.0.3, 29.0.2, 29.0.3, 30.0.2, 32.0.0
      System Images: android-22 | Google APIs Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8092744
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.12 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.2 => 0.67.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Self explanatory, use a fresh repo with a single App component, and use the useColorScheme hook.

### Snack, code example, screenshot, or link to a repository

```
import React from 'react';
import {useColorScheme} from 'react-native';

export function WarningComponent() {
  const colorScheme = useColorScheme();
  return (
    <View>
      <Text>{colorScheme}</Text>
    </View>
  )
}
```

**Comment by AntoineDoubovetzky** [comment]
@cjpete I initialized an application using RN 0.67.2 but can't reproduce your issue.
I believe this warning has been fixed in this commit: https://github.com/facebook/react-native/commit/305b4253c2a9ed4d71be33e02cb12b6d570e2fb1

Can you still reproduce the issue ?
