### ISSUE TITLE
Metro bundler not working on Android Simulator.

### ISSUE THREAD

**Issue by agusvazquez** [facebook/react-native#33136]
### Description

Hello!

I bought a new macbook pro 16' M1 Pro and I am setting up my work environment. iOS is working well, but on Android it is not. I am trying to set up the server and in none of my projects is working (I tried also a sample react native project that didn't work). On my other windows computer everything is working fine. So I am pretty sure that there is an issue with the instalation.

I ensured that my android simulator is not on airplane mode and that the metro server is running. iOS works, so there is no issue with firewall or something like that.

Also I tried adb reverse tcp:8081 tcp:8081

### Version

0.67.2

### Output of `npx react-native info`

System:
    OS: macOS 12.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 777.98 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.5.0 - /opt/homebrew/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.4.1 - /opt/homebrew/bin/npm
    Watchman: 2022.02.07.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8139111
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.2 => 0.67.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

`npx react-native init AwesomeProject`
`cd AwesomeProject`
`cd android`
`Launch Android simulator`
`./gradlew installDebug`
`cd ..`
`yarn start`
`Open app`

And I get the following error.
<img width="574" alt="Captura de Pantalla 2022-02-17 a la(s) 15 37 38" src="https://user-images.githubusercontent.com/1704434/154548386-b06b5929-e97f-4674-9100-53642a9c5c19.png">

Doing the same with iOS it works just fine.
<img width="506" alt="Captura de Pantalla 2022-02-17 a la(s) 15 39 46" src="https://user-images.githubusercontent.com/1704434/154548706-8365411e-2f93-4224-ae0a-013b44059ebd.png">

And also, if I go to localhost:8081 I see that metro it is running fine.
<img width="321" alt="Captura de Pantalla 2022-02-17 a la(s) 15 40 19" src="https://user-images.githubusercontent.com/1704434/154548818-4b5140a2-2875-4fdb-ba16-f4d77856b51b.png">

**Comment by agusvazquez** [comment]
Got it working by downgrading node version to 16.14.0

**Comment by Beamanator** [comment]
Didn't work for me 🤔

**Comment by utkarshhbtu2021** [comment]
did not work
