### ISSUE TITLE
Xcode - Library not found for -lDoubleConversion

### ISSUE THREAD

**Issue by sumantcodeclouds** [facebook/react-native#33132]
### Description

ld: library not found for -lDoubleConversion clang: error: linker command failed with exit code 1 (use -v to see invocation)

### Version

0.61.1

### Output of `npx react-native info`

ld: library not found for -lDoubleConversion clang: error: linker command failed with exit code 1 (use -v to see invocation)

### Steps to reproduce

1.Pod install.
2.Run project from xcode.

Any solution?.

**Comment by alexzobi** [comment]
I'm running into this issue as well. Version 0.68.2. There have been other tickets floating out there that have been closed, which suggested trying to delete pods, clean and re-install. did this over and over with no luck. all of my ios target versions match (11.0). I am sure I opened the .xcworkspace file. I have also tried deleting my derived data folder contents. My teammate even tried deleting xcode and reinstalling. nothing. My project supports mac catalyst and what's interesting is that if i run it targeting mac catalyst, it builds. it's targeting ios that i hit this error, regardless of the sim.

**Comment by alexzobi** [comment]
@sumantcodeclouds after all of the fumbling around I did above, I ran `npx react-native run-ios` and everything worked fine. After that, I was able to successfully build from xcode as well. so something that the `run-ios` command does on the first run resolves the issue for xcode permanently.

**Comment by cortinico** [comment]
Closing as you're using a really old version of React Native + @alexzobi suggested a workaround. Feel free the re-open if the issue persists
