### ISSUE TITLE
RangeError: com.facebook.hermes.intl.JSRangeErrorException: Invalid timezone name!

### ISSUE THREAD

**Issue by Rc85** [facebook/react-native#33147]
### Description

Trying to use `dayjs` with the `timezone` extension. Passing in a timezone like America/Vancouver throws this error. In the hermes repo, they mentioned that it is fixed is version 0.10 and I can see that RN 0.672 is still using version 9 and 0.68 is using version 0.11. Is this the cause of the issue?

### Version

0.67.2

### Output of `npx react-native info`

```
System:
    OS: Windows 10 10.0.19042
    CPU: (16) x64 AMD Ryzen 7 2700X Eight-Core Processor
    Memory: 10.14 GB / 31.93 GB
  Binaries:
    Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
    Watchman: 20210102.202219.0 - C:\Users\roger\watchman\bin\watchman.EXE
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7042882
    Visual Studio: 15.9.28307.1401 (Visual Studio Community 2017)
  Languages:
    Java: 17.0.1
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.2 => 17.0.2
    react-native: ^0.67.2 => 0.67.2
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

Use `dayjs` with `timezone` extension and pass in a valid timezone name, such as America/New_York.

**Comment by grifotv** [comment]
@Rc85 I'm having the same issue. Where can you see the Hermes version for a given RN version?

**Comment by SeongwoonHong** [comment]
any luck so far?

**Comment by Rc85** [comment]
@grifotv Sorry for the late reply. In `node_modules/hermes-engine`

@SeongwoonHong Workaround for me at the moment is using offsets.

**Comment by SeongwoonHong** [comment]
> @grifotv Sorry for the late reply. In `node_modules/hermes-engine`
> 
> @SeongwoonHong Workaround for me at the moment is using offsets.

could you please leave some example here?

**Comment by Rc85** [comment]
@SeongwoonHong For example, if you're using the America/Vancouver timezone which is sometimes -7 and -8 offset, you can add it to your timestamp. `dayjs('2022-06-08 7:00-7')`. If you do it this way, I think it's UTC to PST (might be the other way around). If you want the other way around, you can use the `utcOffset` function `dayjs('2022-06-08 7:00').utcOffset(-7)`, but you have to extend the library with the `utc` plugin for `dayjs`.

Or you can do all of that on your server where you can actually use the timezone name and send the converted time to your app.

**Comment by cortinico** [comment]
> they mentioned that it is fixed is version 0.10 and I can see that RN 0.672 is still using version 9 and 0.68 is using version 0.11. Is this the cause of the issue?

Most likely yes. Have you tried to update RN version to 0.68 + Hermes version to 0.11?

**Comment by cgorrieri** [comment]
Hello, I am still having this issue appearing with RN 0.71.7

**Comment by cgorrieri** [comment]
Hello,
After adding some logs before the app crashes, I believe that react-native doesn't support all time zones by default.
In my case, I believe it was crashing when using `Antarctica/Casey`.
