### ISSUE TITLE
SectionList section index is null

### ISSUE THREAD

**Issue by Fifaldi** [facebook/react-native#33141]
### Description

Hello, 
I am trying to use a sectionlist method scrollToSection, passing both sectionIndex and itemIndex, however SectionList seems to always scroll to first section. 
Inspecting this with prop onViewableItemsChanged and logging viewableItems to the console I found out that only children of section have the index prop but the sections themselves have it all set to null, thus causing method scrollToSection to fail I guess.
Is this a bug, or am I doing something wrong?
Best regards

https://user-images.githubusercontent.com/45095503/154677333-deace6fb-09f8-4c65-9c5e-eb0ffa401ebc.mp4

my code: 
`
import {SectionList} from 'react-native';
import React, {useRef} from 'react';
import {Box, Text, Center, Heading, HStack, Pressable} from 'native-base';

const Example = () => {
    const listRef = useRef<any>();

    const data = [
        {
            title: 'Cyan',
            data: ['cyan.100', 'cyan.200', 'cyan.300', 'cyan.400', 'cyan.500'],
        },
        {
            title: 'Yellow',
            data: ['yellow.100', 'yellow.200', 'yellow.300', 'yellow.400', 'yellow.500'],
        },
        {
            title: 'Violet',
            data: ['violet.100', 'violet.200', 'violet.300', 'violet.400', 'violet.500'],
        },
    ];
    return (
        <Box
            safeArea
            _light={{bg: 'platebook.white'}}
            _dark={{bg: 'platebook.secondary'}}
            flex={1}
            flexDirection="column"
            justifyContent="center">
            <HStack py={4} space={5} alignItems={'center'} justifyContent={'center'}>
                <Pressable
                    onPress={() => {
                        listRef.current.scrollToLocation({
                            animated: true,
                            sectionIdex: 0,
                            itemIndex: 0,
                        });
                    }}>
                    {({isPressed}) => (
                        <Center opacity={isPressed ? 0.5 : 1} px={6} py={2} bg={'cyan.100'}>
                            <Text fontSize={'lg'} color={'black'}>
                                cyan
                            </Text>
                        </Center>
                    )}
                </Pressable>

                <Pressable
                    onPress={() => {
                        listRef.current?.scrollToLocation({
                            animated: true,
                            sectionIdex: 1,
                            itemIndex: 0,
                        });
                    }}>
                    {({isPressed}) => (
                        <Center opacity={isPressed ? 0.5 : 1} px={6} py={2} bg={'yellow.100'}>
                            <Text fontSize={'lg'} color={'black'}>
                                yelllow
                            </Text>
                        </Center>
                    )}
                </Pressable>
                <Pressable
                    onPress={() => {
                        listRef.current?.scrollToLocation({
                            animated: true,
                            sectionIdex: 2,
                            itemIndex: 0,
                        });
                    }}>
                    {({isPressed}) => (
                        <Center opacity={isPressed ? 0.5 : 1} px={6} py={2} bg={'violet.100'}>
                            <Text fontSize={'lg'} color={'black'}>
                                violet
                            </Text>
                        </Center>
                    )}
                </Pressable>
            </HStack>
            <SectionList
                ref={listRef}
                onViewableItemsChanged={({viewableItems}) => {
                    console.tron.logImportant!(viewableItems);
                }}
                sections={data}
                stickySectionHeadersEnabled={false}
                keyExtractor={(item, index) => item + index}
                renderItem={({item}) => (
                    <Center py="4" bg={item}>
                        {item.split('.')[1]}
                    </Center>
                )}
                renderSectionHeader={({section: {title}}) => (
                    <Center>
                        <Heading fontSize="xl" mt="8" pb="4">
                            {title}
                        </Heading>
                    </Center>
                )}
            />
        </Box>
    );
};

export default Example;
`

output of the onViewableItemsChanged in Reactotron
![Screenshot 2022-02-18 at 12 47 20](https://user-images.githubusercontent.com/45095503/154677544-9ef93c87-7316-4159-9520-917017baf801.png)

### Version

0.64.3

### Output of `npx react-native info`

System:
    OS: macOS 12.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 3.11 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.0 - /usr/local/bin/npm
    Watchman: 2021.11.08.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7784292
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.3 => 0.64.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

paste conde in project, run npm install/yarn, start project

**Comment by BohdanSol** [comment]
Typo: replace `sectionIdex` to `sectionIndex` in your code

**Comment by Fifaldi** [comment]
@BohdanSol I cannot belive that! Thank you so much, shame on me! I would  never find it. It worked
