### ISSUE TITLE
 react native (0.67.2 and 0.68.0-rc.1) fresh project issue on IOS with mac m1

### ISSUE THREAD

**Issue by adil2166** [facebook/react-native#33154]
### Description

Library/documentation/DeveloperTools
    export SYSTEM_DEVELOPER_TOOLS_RELEASENOTES_DIR\=/Applications/Xcode.app/Contents/Developer/ADC\ Reference\ Library/releasenotes/DeveloperTools
    export SYSTEM_DEVELOPER_USR_DIR\=/Applications/Xcode.app/Contents/Developer/usr
    export SYSTEM_DEVELOPER_UTILITIES_DIR\=/Applications/Xcode.app/Contents/Developer/Applications/Utilities
    export SYSTEM_DEXT_INSTALL_PATH\=/System/Library/DriverExtensions
    export SYSTEM_DOCUMENTATION_DIR\=/Library/Documentation
    export SYSTEM_KEXT_INSTALL_PATH\=/System/Library/Extensions
    export SYSTEM_LIBRARY_DIR\=/System/Library
    export TAPI_VERIFY_MODE\=ErrorsOnly
    export TARGETED_DEVICE_FAMILY\=1,2
    export TARGETNAME\=FBReactNativeSpec
    export TARGET_BUILD_DIR\=/Users/adilkhan/Library/Developer/Xcode/DerivedData/WooNamal-aisopvytvgmwsmgusdhydiqnuwkx/Build/Products/Debug-iphonesimulator/FBReactNativeSpec
    export TARGET_DEVICE_IDENTIFIER\=37169CF8-A899-456A-80DC-2D1F90985F52
    export TARGET_DEVICE_MODEL\=iPhone14,5
    export TARGET_DEVICE_OS_VERSION\=15.2
    export TARGET_DEVICE_PLATFORM_NAME\=iphonesimulator
    export TARGET_NAME\=FBReactNativeSpec
    export TARGET_TEMP_DIR\=/Users/adilkhan/Library/Developer/Xcode/DerivedData/WooNamal-aisopvytvgmwsmgusdhydiqnuwkx/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FBReactNativeSpec.build
    export TEMP_DIR\=/Users/adilkhan/Library/Developer/Xcode/DerivedData/WooNamal-aisopvytvgmwsmgusdhydiqnuwkx/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FBReactNativeSpec.build
    export TEMP_FILES_DIR\=/Users/adilkhan/Library/Developer/Xcode/DerivedData/WooNamal-aisopvytvgmwsmgusdhydiqnuwkx/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FBReactNativeSpec.build
    export TEMP_FILE_DIR\=/Users/adilkhan/Library/Developer/Xcode/DerivedData/WooNamal-aisopvytvgmwsmgusdhydiqnuwkx/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FBReactNativeSpec.build
    export TEMP_ROOT\=/Users/adilkhan/Library/Developer/Xcode/DerivedData/WooNamal-aisopvytvgmwsmgusdhydiqnuwkx/Build/Intermediates.noindex
    export TEST_FRAMEWORK_SEARCH_PATHS\=\ /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks\ /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator15.2.sdk/Developer/Library/Frameworks
    export TEST_LIBRARY_SEARCH_PATHS\=\ /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/lib
    export TOOLCHAINS\=com.apple.dt.toolchain.XcodeDefault
    export TOOLCHAIN_DIR\=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
    export TREAT_MISSING_BASELINES_AS_TEST_FAILURES\=NO
    export UID\=501
    export UNSTRIPPED_PRODUCT\=NO
    export USER\=adilkhan
    export USER_APPS_DIR\=/Users/adilkhan/Applications
    export USER_LIBRARY_DIR\=/Users/adilkhan/Library
    export USE_DYNAMIC_NO_PIC\=YES
    export USE_HEADERMAP\=YES
    export USE_HEADER_SYMLINKS\=NO
    export USE_LLVM_TARGET_TRIPLES\=YES
    export USE_LLVM_TARGET_TRIPLES_FOR_CLANG\=YES
    export USE_LLVM_TARGET_TRIPLES_FOR_LD\=YES
    export USE_LLVM_TARGET_TRIPLES_FOR_TAPI\=YES
    export USE_RECURSIVE_SCRIPT_INPUTS_IN_SCRIPT_PHASES\=YES
    export VALIDATE_DEVELOPMENT_ASSET_PATHS\=YES_ERROR
    export VALIDATE_PRODUCT\=NO
    export VALIDATE_WORKSPACE\=YES_ERROR
    export VALID_ARCHS\=arm64\ arm64e\ i386\ x86_64
    export VERBOSE_PBXCP\=NO
    export VERSION_INFO_BUILDER\=adilkhan
    export VERSION_INFO_FILE\=FBReactNativeSpec_vers.c
    export VERSION_INFO_STRING\=\"@\(\#\)PROGRAM:FBReactNativeSpec\ \ PROJECT:Pods-\"
    export WRAP_ASSET_PACKS_IN_SEPARATE_DIRECTORIES\=NO
    export XCODE_APP_SUPPORT_DIR\=/Applications/Xcode.app/Contents/Developer/Library/Xcode
    export XCODE_PRODUCT_BUILD_VERSION\=13C100
    export XCODE_VERSION_ACTUAL\=1321
    export XCODE_VERSION_MAJOR\=1300
    export XCODE_VERSION_MINOR\=1320
    export XPCSERVICES_FOLDER_PATH\=/XPCServices
    export YACC\=yacc
    export arch\=undefined_arch
    export variant\=normal
    /bin/sh -c /Users/adilkhan/Library/Developer/Xcode/DerivedData/WooNamal-aisopvytvgmwsmgusdhydiqnuwkx/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FBReactNativeSpec.build/Script-46EB2E00014CD0.sh
/bin/sh: /Volumes/development/working: is a directory
Command PhaseScriptExecution failed with a nonzero exit code

** BUILD FAILED **

The following build commands failed:
        PhaseScriptExecution [CP-User]\ Generate\ Specs /Users/adilkhan/Library/Developer/Xcode/DerivedData/WooNamal-aisopvytvgmwsmgusdhydiqnuwkx/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FBReactNativeSpec.build/Script-46EB2E00014CD0.sh (in target 'FBReactNativeSpec' from project 'Pods')
(1 failure)

### Version

0.67.2

### Output of `npx react-native info`

System:
    OS: macOS 12.2.1
    CPU: (8) x64 Apple M1
    Memory: 37.65 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.5.0 - ~/.nvm/versions/node/v17.5.0/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 8.4.1 - ~/.nvm/versions/node/v17.5.0/bin/npm
    Watchman: 2022.02.14.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7678000
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.12 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.0-rc.1 => 0.68.0-rc.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

npx react-native run-ios    

also find this issue when **run pod install** in ios directory 

Pod installation complete! There are 55 dependencies from the Podfile and 46 total pods installed.

[!] Do not use "pod install" from inside Rosetta2 (x86_64 emulation on arm64).

[!]  - Emulated x86_64 is slower than native arm64

[!]  - May result in mixed architectures in rubygems (eg: ffi_c.bundle files may be x86_64 with an arm64 interpreter)

[!] Run "env /usr/bin/arch -arm64 /bin/bash --login" then try again.

**Comment by adil2166** [comment]
after installing 
  Managers:
    CocoaPods: 1.11.2 - /Users/adilkhan/.rvm/gems/ruby-2.7.4/bin/pod
    still facing the same issue

**Comment by Ice-MT** [comment]
https://github.com/CocoaPods/CocoaPods/issues/10220

sudo arch -x86_64 gem install ffi

**Comment by cortinico** [comment]
We've added a note about it in the website:
https://reactnative.dev/docs/next/environment-setup

<img width="1149" alt="Screenshot 2022-02-25 at 14 29 19" src="https://user-images.githubusercontent.com/3001957/155723401-4d4cdf6e-d61a-418f-9717-4f65da019a6a.png">

Closing as this is resolved

**Comment by adil2166** [comment]
these commands are not working 
now i am facing this issue with react native      "react-native": "0.68.0-rc.2"


** BUILD FAILED **


The following build commands failed:
        CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler (in target 'YogaKit' from project 'Pods')
        CompileC /Users/adilkhan/Library/Developer/Xcode/DerivedData/namal_woo_react_deliveryboy-eeheanngolwjdbapgcpujhhkrvli/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RCT-Folly.build/Objects-normal/x86_64/SysUio.o /Volumes/development/working\ dir/react-woocommerce/namal_woo_react_deliveryboy/ios/Pods/RCT-Folly/folly/portability/SysUio.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'RCT-Folly' from project 'Pods')
(2 failures)



PhaseScriptExecution [CP-User]\ Generate\ Specs /Users/adilkhan/Library/Developer/Xcode/DerivedData/namal_woo_react_deliveryboy-eeheanngolwjdbapgcpujhhkrvli/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FBReactNativeSpec.build/Script-46EB2E00014CD0.sh (in target 'FBReactNativeSpec' from project 'Pods')

**Comment by taylorkline** [comment]
Might be related to your node; cherry-picking 802b3f778b4d2ecd22882b371a84293421558b8a fixed the issue for a dev on my team who was stuck with this issue.
