### ISSUE TITLE
[iOS] Upgraded react native from 0.63 to 0.67 and RTC-Folly fails to builds

### ISSUE THREAD

**Issue by kshitej** [facebook/react-native#33150]
### Description

Running `npx react-native run-ios --verbose ` shows the following errors : 
```
The following build commands failed:
        CompileC /Users/username/Library/Developer/Xcode/DerivedData/ProjectName-awyiegslnefckyesnveuttxiurbm/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RCT-Folly.build/Objects-normal/arm64/SysUio.o /Users/username/Desktop/Personal/Personal\ Projects/ProjectName/ios/Pods/RCT-Folly/folly/portability/SysUio.cpp normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'RCT-Folly' from project 'Pods')
(1 failure)
```

Followed the steps mentioned in `https://github.com/facebook/react-native/issues/32253` and `https://github.com/facebook/react-native/issues/31480` with no avail

### Version

0.67

### Output of `npx react-native info`

System:
    OS: macOS 12.0.1
    CPU: (8) arm64 Apple M1
    Memory: 208.11 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.5.0 - /opt/homebrew/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.4.1 - /opt/homebrew/bin/npm
    Watchman: 2022.02.14.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /opt/homebrew/lib/ruby/gems/3.0.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.2 => 0.67.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. Run`npx react-native init ProjectName`
2. Follow steps mentioned in `https://github.com/facebook/react-native/issues/31480` for react native  > 0.64
3. Run `npx react-native run-ios --verbose`

Steps to debug this : 
Updated the podfile with steps mentioned in `https://github.com/facebook/react-native/issues/32253`, cleaned modules (node_modules, delele pods folder, delete podfile.lock ...) followed by `yarn install && pod install --repo-update`
Ran into the same build issue

**Comment by dangkhoa2708** [comment]
Have you figured it out what happened ?

**Comment by dineshchaudhary923092** [comment]
did anyone figured it out?

**Comment by JaeWangL** [comment]
Me too

**Comment by Yandamuri** [comment]
facing similar issue -> https://github.com/facebook/react-native/issues/33138

**Comment by nuvolarmobileteam** [comment]
Hi, we are facing a similar issue after the update. Did anyone find the source of the problem?

**Comment by nuvolarmobileteam** [comment]
We finally managed to fix it by updating the build target as mentioned here: https://github.com/facebook/react-native/issues/32097#issuecomment-908882241
