### ISSUE TITLE
React-Core Semantic Issue - Unknown type name 'RCT_EXTERN' in RCTBundleURLProvider

### ISSUE THREAD

**Issue by JananiR31** [facebook/react-native#33161]
### Description

Platform - iOS
Facing iOS compilation issue when trying to build with Xcode 13.x. This is occurring with react native versions above 0.64.2. Tried with versions 0.65.2 , 0.66.4 and 0.67.2
Semantic issue is thrown in React-Core library.
File : RCTBundleURLProvider
Error : 'Unknown type name 'RCT_EXTERN

<img width="986" alt="Screenshot 2022-02-22 at 2 47 48 PM" src="https://user-images.githubusercontent.com/94124177/155138862-a60df734-79c0-42e2-a41c-1127d1053c52.png">

### Version

0.65.2 , 0.66.4 and 0.67.2

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 11.5.2
    CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
    Memory: 153.75 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.1 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.15 - /usr/local/bin/npm
    Watchman: 2021.10.18.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.4 => 0.66.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. Upgrade react-native dependency version from 0.64.2 to 0.67.2
2. npm i - Packages are installed.
3. pod install - Pod installation worked.
4. On running the code with Xcode 13.x - it throws compilation errors in "React-Core" library.
Semantic Issue - Unknown type name 'RCT_EXTERN' in RCTBundleURLProvider (Refer screenshot)

**Comment by JananiR31** [comment]
Resolved this issue by changing the Xcode project setting as NO
CLANG_ENABLE_MODULES = NO;

**Comment by vhonLopez** [comment]
@JananiR31 where can i find this in my xcode workspace?
