### ISSUE TITLE
@react-native-community/eslint-config had dependency versions upgraded without a version bump

### ISSUE THREAD

**Issue by mwalkerr** [facebook/react-native#33169]
### Description

I'm trying to upgrade to eslint 8 but getting errors due to the versions of `eslint-plugin-eslint-comments`, `eslint-plugin-flowtype`, and probably other older dependencies as well. The latest version of `@react-native-community/eslint-config` is `3.0.1`, but the package downloaded from npm for 3.0.1 has this package.json (with old versions of dependencies)
```
{
  "name": "@react-native-community/eslint-config",
  "version": "3.0.1",
  "description": "ESLint config for React Native",
  "main": "index.js",
  "license": "MIT",
  "repository": {
    "type": "git",
    "url": "git@github.com:facebook/react-native.git",
    "directory": "packages/eslint-config-react-native-community"
  },
  "homepage": "https://github.com/facebook/react-native/tree/HEAD/packages/eslint-config-react-native-community#readme",
  "dependencies": {
    "@react-native-community/eslint-plugin": "^1.1.0",
    "@typescript-eslint/eslint-plugin": "^4.22.1",
    "@typescript-eslint/parser": "^4.22.1",
    "babel-eslint": "^10.1.0",
    "eslint-config-prettier": "^6.10.1",
    "eslint-plugin-eslint-comments": "^3.1.2",
    "eslint-plugin-flowtype": "2.50.3",
    "eslint-plugin-jest": "22.4.1",
    "eslint-plugin-prettier": "3.1.2",
    "eslint-plugin-react": "^7.20.0",
    "eslint-plugin-react-hooks": "^4.0.7",
    "eslint-plugin-react-native": "^3.10.0",
    "prettier": "^2.0.2"
  },
  "peerDependencies": {
    "eslint": ">=7",
    "prettier": ">=2"
  },
  "devDependencies": {
    "eslint": "7.12.0",
    "prettier": "^2.3.2"
  }
}

```
Compare to the latest in the repo for `3.0.1`: https://github.com/facebook/react-native/blob/main/packages/eslint-config-react-native-community/package.json
The same version number is used for this version (which appears to be what's on npm) https://github.com/facebook/react-native/blob/0.67-stable/packages/eslint-config-react-native-community/package.json

### Version

0.64.3

### Output of `npx react-native info`

```
info Fetching system and libraries information...
System:
    OS: macOS 11.5.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 211.74 MB / 32.00 GB
    Shell: 3.3.1 - /usr/local/bin/fish
  Binaries:
    Node: 14.17.6 - /usr/local/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 6.14.15 - /usr/local/bin/npm
    Watchman: 2022.02.07.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7678000
    Xcode: 13.2/13C90 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.13 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.4 => 0.63.4
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

Check https://github.com/facebook/react-native/blob/0.67-stable/packages/eslint-config-react-native-community/package.json and https://github.com/facebook/react-native/blob/0.68-stable/packages/eslint-config-react-native-community/package.json

**Comment by yahacom** [comment]
same issue

**Comment by cortinico** [comment]
I've just published `3.0.2` on NPM 👍

**Comment by BeeMargarida** [comment]
Why wasn't the dependency `babel-eslint` changed to `@babel/eslint-parser, since it is already deprecated? https://www.npmjs.com/package/babel-eslint

**Comment by cortinico** [comment]
> Why wasn't the dependency `babel-eslint` changed to `@babel/eslint-parser, since it is already deprecated?

Feel free to send over a PR with a string replace of that. I'm happy to review and merge it 👍
