### ISSUE TITLE
No member named 'cancelButtonTintColor' in 'JS::NativeActionSheetManager::SpecShowActionSheetWithOptionsOptions'

### ISSUE THREAD

**Issue by vsmobiledevs** [facebook/react-native#33174]
### Description

How to fix this error.    I have created simple project with latest version and when try to build the project via Xcode it generate error?

### Version

0.67.3

### Output of `npx react-native info`

System:
    OS: macOS 11.5.2
    CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
    Memory: 83.30 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.2 - /usr/local/opt/node@14/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 6.14.15 - /usr/local/opt/node@14/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7583922
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.3 => 0.67.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Please init new react native project with command and try to build the project in the xcode after pod install

### Snack, code example, screenshot, or link to a repository

![Uploading Screenshot 2022-02-24 at 11.34.31 AM.png]()

**Comment by talha-irshad-kodexo** [comment]
Having the same issue here
<img width="1280" alt="Screenshot 2022-03-02 at 6 05 59 PM" src="https://user-images.githubusercontent.com/99028409/156367168-204afe14-63bc-4cf4-8480-eb1da9365327.png">

**Comment by vsmobiledevs** [comment]
any one got the solution ?

**Comment by pietroanello** [comment]
Hey guys, same error here but with a strange behaviour. If I try to build from terminal with "npm run ios" i got the error, but if I open the xCode project with xCode and clean and rebuild everything works fine, even from the terminal.

**Comment by FilipMaslovaric** [comment]
Was having these same issues, and the problem for me ended up being that i had `postinstall` scripts ignored. Can't really confirm whether that's the root cause, but re-enabling `postinstall` (removing `--ignore-scripts` from `npm` or `yarn` whichever you use), fixed it for me 🤷

**Comment by clemlucas974** [comment]
@vsmobiledevs Thanks for the tip ! 
Here is the patch file content to create inside `patches` directory in root directory (`patches/react-native+0.67.3.patch`) for `npx patch-package` during postinstall script

```
diff --git a/node_modules/react-native/React/CoreModules/RCTActionSheetManager.mm b/node_modules/react-native/React/CoreModules/RCTActionSheetManager.mm
index 5cd782e..d60e510 100644
--- a/node_modules/react-native/React/CoreModules/RCTActionSheetManager.mm
+++ b/node_modules/react-native/React/CoreModules/RCTActionSheetManager.mm
@@ -94,8 +94,8 @@ RCT_EXPORT_METHOD(showActionSheetWithOptions
   UIViewController *controller = RCTPresentedViewController();
   NSNumber *anchor = [RCTConvert NSNumber:options.anchor() ? @(*options.anchor()) : nil];
   UIColor *tintColor = [RCTConvert UIColor:options.tintColor() ? @(*options.tintColor()) : nil];
-  UIColor *cancelButtonTintColor =
-      [RCTConvert UIColor:options.cancelButtonTintColor() ? @(*options.cancelButtonTintColor()) : nil];
+  UIColor *cancelButtonTintColor = [RCTConvert UIColor:options.tintColor() ?
+      @(*options.tintColor()) : nil];
 
   if (controller == nil) {
     RCTLogError(
```

**Comment by Talha-Irshad** [comment]
Update: resolved this error by clearing the build from xcode and building the app again

**Comment by JoseVov** [comment]
If you are installing new modules do the following:

1) Ensure to go to the IOS folder and run pod install. 
2) Open the `.workspace` file and run CMD + SHIFT + K (Clean the project)
3) Run Again.

**Comment by Z-LianYan** [comment]
The same problem happened.

error: no member named 'cancelButtonTintColor' in 'JS::NativeActionSheetManager::SpecShowActionSheetWithOptionsOptions'
