### ISSUE TITLE
RN Typedef redefinition with different types ('uint8_t' (aka 'unsigned char') vs 'enum clockid_t')

### ISSUE THREAD

**Issue by yodarango** [facebook/react-native#33178]
### Description

I am currently building a project with React Native 0.67 and and Monterey MacOS, intel Chip. 

I have tried about every possible solution, but yet, the problem persists. 

**The Problem is the following:**
after carefully following the instructions in [react setup page](https://reactnative.dev/docs/environment-setup)  to initialize a new app, when I execute the **run-ios** command I get the following error on my console, which seems to be related to Flipper: 

> ** BUILD FAILED **
> The following build commands failed:
>         CompileC /Users/dr/Library/Developer/Xcode/DerivedData/Test-gxglauoeoglzeobdubkxzgziurmr/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RCT-Folly.build/Objects-normal/x86_64/SysUio.o /Users/dr/Library/Mobile\ Documents/com~apple~CloudDocs/2.\ Business/2.\ Software\ As\ A\ Service.nosync/socholar-native.nosync/Test/ios/Pods/RCT-Folly/folly/portability/SysUio.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler **(in target 'RCT-Folly' from project 'Pods')**
> (1 failure)

When I try running it from Xcode I get the following Error in RCT_Folly directory:

> RN Typedef redefinition with different types ('uint8_t' (aka 'unsigned char') vs 'enum clockid_t')

### Version

0.67

### Output of `npx react-native info`

System:
    OS: macOS 12.2.1
    CPU: (8) x64 Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz
    Memory: 48.18 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.1 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 7.22.0 - /usr/local/bin/npm
    Watchman: 2022.02.14.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 28, 29, 30, 32
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 32.0.0, 32.1.0
      System Images: android-28 | Google APIs Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8139111
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.3 => 0.67.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps To Reproduce

1. init a new react project with macOS **Montery or Big Sur** and **React Native 0.67**
2. Execute run-ios command
3. See It Fail 

FYI works on Android

### When Runing with npx react-native run-ios
<img width="827" alt="Screen Shot 2022-02-24 at 9 00 30 PM" src="https://user-images.githubusercontent.com/61793148/155639518-2aff59e5-bed5-48bf-961d-0525447eb020.png">

### When running with Xcode in Time.h file
<img width="811" alt="Screen Shot 2022-02-24 at 9 02 23 PM" src="https://user-images.githubusercontent.com/61793148/155639733-91a02aab-a6f1-4f8f-8d3c-ea54c7850fa6.png">

**Comment by official-bharat** [comment]
I have also getting the same issue on last 3 days. can you please fixed that issue

**Comment by himanshuRedlist** [comment]
Facing same issue

**Comment by thomasMinshull** [comment]
same issue

**Comment by stefannilsson** [comment]
also troubled by this :-/

**Comment by ZeeshanTofiq** [comment]
also facing same issue

**Comment by official-bharat** [comment]
I have set up all things from the scratch then I didn’t get the same issue.

**Comment by akenarong999** [comment]
same here

**Comment by yodarango** [comment]
Found the solution guys, apparently it was a bug with that particular version of React Native, I regressed to version 64 and it is working great. I have not tried the newest version 0.67 to check if it works there though! 

Hop that helps!

@official-bharat what version are you using?

**Comment by KrisLau** [comment]
Still facing the same issue with upgrading React Native for months now. It's blocking the update of the other dependencies that depend on React Native being updated as well

**Comment by SergioSuarezDev** [comment]
same issue here

**Comment by kirill3333** [comment]
@yodarango I had the same issue on RN 0.67.4 and Xcode version 13.1.1
Fixed it by upgrading Xcode to 13.2.
Try to use RN 0.67.4 and Xcode to 13.2.*

**Comment by HarshMB** [comment]
in Time.h file you should do below changes at top:-

change this 
(TARGET_OS_IPHONE && (__IPHONE_OS_VERSION_MIN_REQUIRED < __IPHONE_**10**_0))

to this
(TARGET_OS_IPHONE && (__IPHONE_OS_VERSION_MIN_REQUIRED < __IPHONE_**12**_0))

just you have to make 10 to 12 and clean the project, run it.

I hope it will solve you issue.

**Comment by paulbtw** [comment]
> ![image](https://user-images.githubusercontent.com/46275463/171657731-6cd97dc2-6bd0-44c1-8d94-49e69eb22691.png) I couldn't find the actual comment that I got it from but this is a workaround I got from a forum. Just change this in your Podfile

Not working for me with react-native version 0.68.2

**Comment by shishir48** [comment]
> > ![image](https://user-images.githubusercontent.com/46275463/171657731-6cd97dc2-6bd0-44c1-8d94-49e69eb22691.png) I couldn't find the actual comment that I got it from but this is a workaround I got from a forum. Just change this in your Podfile
> 
> Not working for me with react-native version 0.68.2

worked by downgrading RCT-folly deployment target to ios 13.

**Comment by KrisLau** [comment]
> ![image](https://user-images.githubusercontent.com/46275463/171657731-6cd97dc2-6bd0-44c1-8d94-49e69eb22691.png) I couldn't find the actual comment that I got it from but this is a workaround I got from a forum. Just change this in your Podfile

Found the original comment just to give credit to @mikehardy for the solution I posted earlier: https://github.com/facebook/flipper/issues/834#issuecomment-902886771

**Comment by KrisLau** [comment]
https://github.com/facebook/flipper/issues/834#issuecomment-919816118

**Comment by AbdulmalekAlshugaa** [comment]
same thing with react native 0.66.0

**Comment by Solace-Studios** [comment]
Same thing with react native 0.70.0

**Comment by Cheongwenghong** [comment]
Same thing with react native 0.70.10

**Comment by Arjan-Zuidema** [comment]
> [facebook/flipper#834 (comment)](https://github.com/facebook/flipper/issues/834#issuecomment-919816118)

No, event without `use_frameworks!` I get this error.

**Comment by Arjan-Zuidema** [comment]
> ![image](https://user-images.githubusercontent.com/46275463/171657731-6cd97dc2-6bd0-44c1-8d94-49e69eb22691.png) I couldn't find the actual comment that I got it from but this is a workaround I got from a forum. Just change this in your Podfile

This seems to work for me (RN 0.72.5)

```code
`sed -i -e  $'s/__IPHONE_10_0/__IPHONE_13_0/' #{installer.sandbox.root}/RCT-Folly/folly/portability/Time.h`
```

**Comment by puretension** [comment]
Same thing with react native 0.72.8
