### ISSUE TITLE
ScrollView behavior on scroll. Android 10+

### ISSUE THREAD

**Issue by Oples** [facebook/react-native#33172]
### Description

When trying to scroll beyond the top and the bottom of the ScrollView the window "bounces" and moves in the opposite direction.
This leads to an unpleasant user experience and an unpredictable interaction with the UI.

### Version

0.67.3

### Output of `npx react-native info`

```
System:
    OS: Linux 5.15 Manjaro Linux
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
    Memory: 551.49 MB / 15.61 GB
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
    Yarn: 1.22.17 - /usr/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: AI-211.7628.21.2111.8139111
  Languages:
    Java: 11.0.13 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.3 => 0.67.3 
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

Create a ScrollView with enough content to scroll and build for an APK for Android
test with Android version 10 or above.

https://user-images.githubusercontent.com/21972291/155406343-2dbfaae5-e72d-4479-bffa-34fbc52db50d.mp4

I tested on Android 10 and 11 devices and the issue persists
However, on older Android 7 devices and the component works as intended.

### Snack, code example, screenshot, or link to a repository

Expo snack example <https://snack.expo.dev/@oples/scroll-view-example> it's possible to reproduce the bug in the appetize.io Android 10 emulator.

**Comment by thomasgrivet** [comment]
Hello, we also have this issue. Did you find any solution?

**Comment by Oples** [comment]
No, I did not find any solution.
In the meantime, I had to change my phone and I am now unable to reproduce the bug.

**Providing more information:**
I had a Ulefone 11P (Android 11) which has a 720x1600px display
And now a Oneplus Nord CE (Android 11) ‎1080x2400px display

I'm starting to think that is an issue related to the Android ROM provided by the vendor.
