### ISSUE TITLE
Getting error libc++abi: terminating with uncaught exception of type NSException while running ios app in release mode only.

### ISSUE THREAD

**Issue by akshaykatale99** [facebook/react-native#33171]
### Description

getting following error while running ios app in release mode only. when I run the app in debug mode then it's working as expected.

`libc++abi: terminating with uncaught exception of type NSException
dyld4 config: DYLD_ROOT_PATH=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot DYLD_LIBRARY_PATH=/Users/akshaykatale/Library/Developer/Xcode/DerivedData/psg-ccycswgfjgbdasgnfgncempudfzy/Build/Products/Release-iphonesimulator:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/introspection DYLD_INSERT_LIBRARIES=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libBacktraceRecording.dylib:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libMainThreadChecker.dylib:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib DYLD_FRAMEWORK_PATH=/Users/akshaykatale/Library/Developer/Xcode/DerivedData/psg-ccycswgfjgbdasgnfgncempudfzy/Build/Products/Release-iphonesimulator
*** Terminating app due to uncaught exception 'RCTFatalException: Unhandled JS Exception: TypeError: undefined is not an object (evaluating 't.insertRule=function(t,n){return t<=this.length&&(this.rules.splice(t,0,n),this.length++,!0)}')', reason: 'Unhandled JS Exception: TypeError: undefined is not an object (evaluating 't.insertRule=function(t,n){return t<=this.length&&(this.rules.splice(t,0,n),this.length++,!0)}'), stack:
<unknown>@1698:4861
<unknown>@1698:5082
v@2:1473
<unknown>@642:1256
v@2:1473
<unknown>@6:67
v@2:1473
d@2:875
global code@1704:3
'
terminating with uncaught exception of type NSException
CoreSimulator 783.5 - Device: iPhone 13 Pro Max (BBD052A5-2301-456E-99A2-DEEA030A242A) - Runtime: iOS 15.2 (19C51) - DeviceType: iPhone 13 Pro Max`

### Version

0.63.3

### Output of `npx react-native info`

System:
    OS: macOS 12.2.1
    CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
    Memory: 35.77 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 7.15.0 - /usr/local/bin/npm
    Watchman: 2022.01.17.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.2 - /usr/bin/javac
    Python: 2.7.18 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: ~0.63.3 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

running app in release mode.

### Snack, code example, screenshot, or link to a repository

![Screenshot 2022-02-24 at 12 11 17 AM](https://user-images.githubusercontent.com/12472207/155386655-d81ee558-4bb9-428a-afcd-65181c9208e2.png)

**Comment by JasonA-hoppa** [comment]
experiencing same problem. have out found a solution yet?

**Comment by akshaykatale99** [comment]
@JasonA-hoppa, in my case. got this error from js code. so as a workaround I have turned off js minify. **(Not recommended)**.

iOS -
Add `--minify false \ in node_modules/react-native/scripts/react-native-xcode.sh in side app config`

Android - 

```
Add extraPackagerArgs in /android/app/build.gradle

project.ext.react = [
    enableHermes: false,
    extraPackagerArgs: [ '--minify=false' ]
]
```

**Comment by thanghps** [comment]
experiencing same problem. have out found a solution yet?

**Comment by akjesto** [comment]
I also got same issue. Please give me any solution

**Comment by mehdiChibani** [comment]
> @JasonA-hoppa, in my case. got this error from js code. so as a workaround I have turned off js minify.
> 
> **(Not recommended)**.
> 
> iOS - Add `--minify false \ in node_modules/react-native/scripts/react-native-xcode.sh in side app config`
> 
> Android -
> 
> ```
> Add extraPackagerArgs in /android/app/build.gradle
> 
> project.ext.react = [
>     enableHermes: false,
>     extraPackagerArgs: [ '--minify=false' ]
> ]
> ```

this solution made my app work after months of debug , thanks a lot @akshaykatale99
