### ISSUE TITLE
Couldn't determine CLI location. Please set `project.ext.react.cliPath` to the path of the react-native cli.js

### ISSUE THREAD

**Issue by MisterMunchkin** [facebook/react-native#33170]
### Description

Error is happening when syncing the gradle file. I have been following expo docs on creating expo modules using `npx create-expo-module`

Here's my project gradle file:

apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'maven-publish'

apply from: new File(["node", "--print", "require.resolve('react-native-unimodules/package.json')"].execute(null, rootDir).text.trim(), "../gradle.groovy")
apply from: new File(["node", "--print", "require.resolve('react-native/package.json')"].execute(null, rootDir).text.trim(), "../react.gradle")
apply from: new File(["node", "--print", "require.resolve('expo-updates/package.json')"].execute(null, rootDir).text.trim(), "../scripts/create-manifest-android.gradle")

apply from: new File(["node", "--print", "require.resolve('@react-native-community/cli-platform-android/package.json')"].execute(null, rootDir).text.trim(), "../native_modules.gradle");
applyNativeModulesAppBuildGradle(project)

group = 'com.cardexchangesolutions.hidmobilelibrary'
version = '0.1.0'

buildscript {
  // Simple helper that allows the root project to override versions declared by this library.
  ext.safeExtGet = { prop, fallback ->
    rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
  }

  //ext.react.cliPath = '../node_modules/react-native/cli.js'

  repositories {
    mavenCentral()
    google()
   // jcenter()
  }

  dependencies {
    classpath("com.android.tools.build:gradle:7.3.0-alpha02")
    classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:${safeExtGet('kotlinVersion', '1.6.10')}")
  }
}

// Upload android library to maven with javadoc and android sources
configurations {
  deployerJars
}

// Creating sources with comments
task androidSourcesJar(type: Jar) {
  classifier = 'sources'
  from android.sourceSets.main.java.srcDirs
}

// Put the androidSources and javadoc to the artifacts
artifacts {
  archives androidSourcesJar
}

publishing {
  repositories {
    maven {
      url = uri("${rootProject.projectDir}/maven-repo")
    }
  }
}

android {
  compileSdkVersion safeExtGet("compileSdkVersion", 30)

  compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
  }
  
  kotlinOptions {
    jvmTarget = JavaVersion.VERSION_1_8
  }

  buildFeatures {
    viewBinding true
  }

  defaultConfig {
    minSdkVersion safeExtGet("minSdkVersion", 21)
    targetSdkVersion safeExtGet("targetSdkVersion", 30)
    versionCode 1
    versionName "0.1.0"
  }
  lintOptions {
    abortOnError false
  }
}

repositories {
  mavenCentral()
}

dependencies {
  implementation project(':expo-modules-core')
  implementation "com.android.tools.build:gradle:7.3.0-alpha02"
  implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:${safeExtGet('kotlinVersion', '1.6.10')}"
}

### Version

latest, 0.66stable, 0,64,3

### Output of `npx react-native info`

warn Package expo-modules-core has been ignored because it contains invalid configuration. Reason: "dependency.platforms.ios" must be of type object
info Fetching system and libraries information...
System:
    OS: macOS 12.2
    CPU: (8) arm64 Apple M1
    Memory: 126.41 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.5.0 - /opt/homebrew/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.5.0 - /opt/homebrew/bin/npm
    Watchman: 2022.02.14.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 23, 29, 30, 32
      Build Tools: 25.0.0, 28.0.3, 29.0.2, 29.0.3, 30.0.2, 32.0.0, 32.1.0, 33.0.0
      System Images: android-32 | Google APIs ARM 64 v8a, android-32 | Google Play ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8139111
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.2 - /Users/robindalmy/.jenv/shims/javac
  npmPackages:
    @react-native-community/cli: 2.10.0 => 2.10.0 
    react: 17.0.2 => 17.0.2 
    react-native: ^0.67.3 => 0.67.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

- Create expo module
- Sync Gradle

### Snack, code example, screenshot, or link to a repository

here's the link to the repository: https://github.com/MisterMunchkin/HIDMobileLibrary

**Comment by 3dylson** [comment]
Check if you have [NDK](https://developer.android.com/ndk) installed and the PATH on `local.properties`

**Comment by 3dylson** [comment]
Try to add this to your project gradle:
```
project.ext.react = [
        cliPath: ["node", "-e", "console.log(require('react-native/cli').bin);"].execute([], projectDir).text.trim(),
]
```

**Comment by 3dylson** [comment]
Try to add this to your project gradle (`android/app/build.gradle` file, right at the top level):
```
project.ext.react = [
        cliPath: ["node", "-e", "console.log(require('react-native/cli').bin);"].execute([], projectDir).text.trim(),
]
```

**Comment by cortinico** [comment]
The suggestion proposed by @3dylson is correct. Closing

**Comment by abhay-01** [comment]
in which portion of file need to add

**Comment by rudda-involves** [comment]
> in which portion of file need to add

inside the android/ folder ?
