### ISSUE TITLE
Repo size/binary files

### ISSUE THREAD

**Issue by friederbluemle** [facebook/react-native#33185]
I just fetched from facebook/react-native and was pretty shocked to see that it downloaded another ~**100 MB** of data.

A quick look at `--stat` revealed that 8 new binary jar files were added to the repo:

```
$ du -sh ReactAndroid/src/main/third-party/kotlin/1.6.10/
102M	ReactAndroid/src/main/third-party/kotlin/1.6.10/
```

Is there a way these files can be fetched on demand from a central repository like other Java/Maven dependencies instead?

As you probably know, the increase in repo size is **permanent** (even if the files are deleted/updated again later), except if the history is rewritten (which of course is not an option).

facebook/react-native is already up to >800 MB. That's just the repo size alone, without a checked out working tree.

#33168

**Comment by cortinico** [comment]
Thanks for raising this issue. @ShikaSD looked into making sure we don't bundle them inside the NPM package at least.

> As you probably know, the increase in repo size is permanent (even if the files are deleted/updated again later), except if the history is rewritten (which of course is not an option).

As you mentioned, now the "damage" is done. Sorry for that.
I think we should look into findign a different approach to make sure we don't add 100+ whenever we bump a minor version of Kotlin.

**Comment by ShikaSD** [comment]
You are right, sorry for the size increase. Buck is very weird about this, and requires .jar files to be always checked in, which caused the update.
What we can do in the future is update docker image instead, as most of the Android Buck related targets are using it anyway.

**Comment by cortinico** [comment]
> Buck is very weird about this, and requires .jar files to be always checked in, which caused the update.

Coulnd't we use `fb_native.remote_file` as we're doing for OkHTTP and others?

**Comment by ShikaSD** [comment]
> Buck is very weird about this, and requires .jar files to be always checked in, which caused the update.

I found some PRs mentioning support of tasks that provide Kotlin artifacts, but it seems like it was reverted and I don't see that this was landed again. In documentation, it only mentions `kotlin_home` as already existing directory, maybe we could preload it somehow?

**Comment by cortinico** [comment]
Will be addressed (partially) by #33209

**Comment by ShikaSD** [comment]
Aside from this, to battle the repo size, you can also use shallow clone by specifying `-depth 1` parameter when cloning the checkout :)
It should also be possible to prune the unused blocks and leave only checked in branches if the size is a concern.

**Comment by cortinico** [comment]
Closing as #33209 was merged

**Comment by friederbluemle** [comment]
Thanks @cortinico and @ShikaSD 👏  :+1:
