### ISSUE TITLE
iOS: Download in background mode is not working

### ISSUE THREAD

**Issue by Mant0shMishra57** [facebook/react-native#33199]
### Description

Using React-Native to build iOS App.

Using : https://github.com/joltup/rn-fetch-blob.git library to download files in iOS app.

When app is going to background mode by taping home button for more than 30 sec then getting message "Lost connection to background transfer service". And after 5min if we will try to come foregraound from background  then app will restart with completing download. Actually it is downloading only for 30 sec in background mode.

1. Is this "rn-fetch-blob" library is correct library?
2. If this library is correct then please suggest what I should do?
3. Is it any library that support large files download in background mode in React-Native?

### Version

0.66.2

### Output of `npx react-native info`

System:
    OS: macOS 11.4
    CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
    Memory: 524.76 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.2 - ~/.nvm/versions/node/v14.17.2/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.2/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7784292
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.12 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.2 => 0.66.2 
    react-native-macos: Not Found

### Steps to reproduce

When app is going to background mode by taping home button for more than 30 sec then getting message "Lost connection to background transfer service". And after 5min if we will try to come foregraound from background  then app will restart with completing download. Actually it is downloading only for 30 sec in background mode.

### Snack, code example, screenshot, or link to a repository

RNFetchBlob.config({
                IOSBackgroundTask: true,
                path: path,
                fileCache: true,
            }).fetch('POST', "downloadFileUrl}", {
                'Content-Type': 'application/json',
                'Authorization': 'Bearer ' + bearer_token,
            }, JSON.stringify(params));

**Comment by matinzd** [comment]
This issue is not related to react-native I think. Maybe you need to use another third-party module or write your own native service.
