### ISSUE TITLE
muliline is true doesn't allow to set returnLabelType='send' on Android

### ISSUE THREAD

**Issue by HeMa321** [facebook/react-native#33193]
### Description

Description
returnKeyType does not work on Android with multi line props set to true
returnLabelType seems to be the same. The problem is on iOS it works well, this is not persistent and be able to display a Text on multiple line without linebreak become too much hard.

Reproduction
<TextInput multiline={true} returnKeyType={"send"}/> works on iOS but not on Android.

### Version

0.66.4

### Output of `npx react-native info`

 "react": "17.0.2",
    "react-app-rewired": "^2.1.8",
    "react-native": "0.66.4",

### Steps to reproduce

 textInputProps={{
            ...props.textInputProps,
            onFocus,
            onBlur,
            placeholder: '',
            autoFocus: false,
            selectionColor: ScreenUtils.ANDROID?Colors.selectionColor:Colors.horbar_color,
            returnKeyLabel: 'send',
            returnKeyType:  'send',
            onSubmitEditing:  onSubmitEditing,
}}

 <TextInput
        ref={v => (this.inputRef = v)}
        testID={this.props.placeholder}
        accessible
        accessibilityLabel={this.props.placeholder}
        placeholder={this.props.placeholder}
        placeholderTextColor={this.props.placeholderTextColor}
        multiline={this.props.multiline}
        editable={!this.props.disableComposer}
        onChange={this.onContentSizeChange}
        onContentSizeChange={this.onContentSizeChange}
        onChangeText={this.onChangeText}
        style={[
          styles.textInput,
          this.props.textInputStyle,
          {
            height: this.props.composerHeight,
            ...Platform.select({
              web: {
                outlineWidth: 0,
                outlineColor: 'transparent',
                outlineOffset: 0,
              },
            }),
          },
        ]}
        autoFocus={this.props.textInputAutoFocus}
        value={this.props.text}
        enablesReturnKeyAutomatically
        underlineColorAndroid="transparent"
        keyboardAppearance={this.props.keyboardAppearance}
        {...this.props.textInputProps}
      />

**Comment by aprilmintacpineda** [comment]
@HeMa321 not related to the issue, but since you're using multiline, do you happen to experience this issue as well? https://github.com/facebook/react-native/issues/33165 were you able to fix it?
