### ISSUE TITLE
what's time for react native android support load remote-js instead of devPcHelper, v0.12? thks

### ISSUE THREAD

**Issue by yipengmu** [facebook/react-native#3319]

**Comment by mikearmstrong001** [comment]
@yipengmu Thanks for the interest.

I'll let @mkonicek comment on future plans, however we are more than happy to accept pull requests :)

**Comment by mkonicek** [comment]
What is devPcHelper?

There's a possibly related PR, see https://github.com/facebook/react-native/pull/3189
