### ISSUE TITLE
task :react-native-safe-area-context:compiledebugjavawithjavac failed

### ISSUE THREAD

**Issue by Pralad-Thapa** [facebook/react-native#33194]
### Description

I am working on a local news app in react native and I am getting this error whenever I run android emulator using npx react-native run_android
![Screenshot (1)](https://user-images.githubusercontent.com/92534390/156010532-b9163822-5847-439e-a243-330297b99bfb.png)
![Screenshot (2)](https://user-images.githubusercontent.com/92534390/156010569-e82c6bf9-71f8-4b01-9eb3-ec35a0b00fe5.png)
![Screenshot (75)](https://user-images.githubusercontent.com/92534390/156010633-bc413c9e-7f8c-425d-8ea7-4faf5b46915b.png)

### Version

0.64.3

### Output of `npx react-native info`

 (actual and formal argument lists differ in length)
    constructor Event.Event(int) is not applicable
      (actual and formal argument lists differ in length)
C:\Users\HP\projects\helloworld\Samprati\node_modules\react-native-safe-area-context\android\src\main\java\com\th3rdwave\safeareacontext\SafeAreaProviderManager.java:62: error: cannot find symbol
              UIManagerHelper.getSurfaceId(reactContext), reactTag, insets, frame));  
                             ^
  symbol:   method getSurfaceId(ReactContext)
  location: class UIManagerHelper
Note: C:\Users\HP\projects\helloworld\Samprati\node_modules\react-native-safe-area-context\android\src\main\java\com\th3rdwave\safeareacontext\SafeAreaUtils.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\HP\projects\helloworld\Samprati\node_modules\react-native-safe-area-context\android\src\main\java\com\th3rdwave\safeareacontext\SafeAreaContextPackage.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-safe-area-context:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 24s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081   
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/03 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/03 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/03 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/03 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
      (actual and formal argument lists differ in length)
    constructor Event.Event(int) is not applicable
      (actual and formal argument lists differ in length)
C:\Users\HP\projects\helloworld\Samprati\node_modules\react-native-safe-area-context\android\src\main\java\com\th3rdwave\safeareacontext\SafeAreaProviderManager.java:62: error: cannot find symbol----------------------------------------------------------------------------           ---------------------------------------------              UIManagerHelper.getSurfaceId(reactContext), reactTag, insets, frame));----------------------------------------------------------------------------         --------------                             ^
  symbol:   method getSurfaceId(ReactContext)------------------------------------------------------------- -------------------------------------------------------------  location: class UIManagerHelper
Note: C:\Users\HP\projects\helloworld\Samprati\node_modules\react-native-safe-area-context\android\src\main\java\com\th3rdwave\safeareacontext\SafeAreaUtils.java uses or overrides a deprecated API.----------------------------------------------------------------------------           ---------------------------------------------Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\HP\projects\helloworld\Samprati\node_modules\react-native-safe-area-context\android\src\main\java\com\th3rdwave\safeareacontext\SafeAreaContextPackage.java uses unchecked or unsafe operations.----------------------------------------------------------------------------           ---------------------------------------------Note: Recompile with -Xlint:unchecked for details.
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-safe-area-context:compileDebugJavaWithJavac'.> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 24s

    Visual Studio: Not Found
  Languages:
    Java: Not Found  npmPackages:    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.3 => 0.64.3    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
PS C:\Users\HP\projects\helloworld\Samprati> npx react-native info
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz
    Memory: 3.26 GB / 7.81 GB
  Binaries:
    Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version     2021.1.0.0 AI-211.7628.21.2111.8139111
    Visual Studio: Not Found
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.3 => 0.64.3
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

I was earlier working on my project on expo cli but then I ejected and began working on react-native cli. Even then the android simulator was working but after some day it started showing the error.

### Snack, code example, screenshot, or link to a repository

`This is my package.json file
{
  "name": "samprati",
  "version": "1.0.0",
  "scripts": {
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@react-native-community/checkbox": "^0.5.11",
    "@react-native-firebase/app": "^14.5.0",
    "@react-native-firebase/auth": "^14.5.0",
    "@react-navigation/native": "^6.0.8",
    "@react-navigation/native-stack": "^6.5.0",
    "expo": "~44.0.0",
    "expo-splash-screen": "~0.14.1",
    "expo-status-bar": "~1.2.0",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-native": "0.64.3",
    "react-native-safe-area-context": "^4.0.1",
    "react-native-screens": "^3.12.0",
    "react-native-web": "0.17.1",
    "react-redux": "^7.2.6",
    "redux": "^4.1.2"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9"
  },
  "private": true
}
`

**Comment by danilobuerger** [comment]
Duplicate of https://github.com/th3rdwave/react-native-safe-area-context/issues/245
