### ISSUE TITLE
Fast refresh works once and then doesn't work

### ISSUE THREAD

**Issue by romanakash** [facebook/react-native#33208]
### Description

After reloading an app when new code is saved, fast refresh works fine. But on further changes to the code fast refresh doesn't work and there is no toast as well.

### Version

0.67.2

### Output of `npx react-native info`

System:
    OS: Linux 5.16 Manjaro Linux
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 967.28 MB / 15.27 GB
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 3.1.1 - ~/.nvm/versions/node/v16.13.1/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: AI-203.7717.56.2031.7784292
  Languages:
    Java: 11.0.13 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.67.2 => 0.67.2
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. Reload App
2. Save new changes
3. Fast Refresh works
4. Save changes again
5. Fast Refresh doesn't work

EDIT: It looks like this only happens when you render an image with an internet URL. Fast refresh works normally then after adding an image it works once and stops working.

**Comment by tewedaj** [comment]
Have you tried deleting node-modules and also running "npx react-native run-android" again?

**Comment by romanakash** [comment]
I used yarn and tried the reset cache but that didn't work. My current workaround is to remove the Image component from my code when developing.
