### ISSUE TITLE
Could not build from Source

### ISSUE THREAD

**Issue by thuongtv-vn** [facebook/react-native#33206]
### Description

Hi all, 

I have followed the guide in this page:

https://github.com/facebook/react-native/wiki/Building-from-source

Unfortunately, I could not build it successful. I got some kind of different issues such as gradle, other library....

Do you guys know how to build react-native app from source. The purpose of this is I would like to add new feature/hot fix that currently is not supported yet. Create the pull request should be the right way, but it will take too long.

### Version

0.63.4

### Output of `npx react-native info`

    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 

### Steps to reproduce

Step 1. yarn install finished.
Step 2:Delete node_modules/react-native folder.
Step 3: clone react-native from repo: git clone https://github.com/facebook/react-native.git node_modules/react-native

And continue following steps:
https://github.com/facebook/react-native/wiki/Building-from-source#2-adding-gradle-dependencies

**Comment by cortinico** [comment]
> Unfortunately, I could not build it successful. I got some kind of different issues such as gradle, other library....

What's the error message?

**Comment by thuongtv-vn** [comment]
Hi @cortinico 

Sorry for delay answer. I got this message error: 

```node_modules/react-native/packages/react-native-gradle-plugin' does not exist.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
```

What i have done:
1. Run my app successful on Emulator/Devices.
2. I would like to apply new feature on Text component.
3. I followed this article "https://github.com/facebook/react-native/wiki/Building-from-source"
4. After adapt the changes, I delete node_modules and build app again.
5. Then i got this error message. I saw that this package is not exist "node_modules/react-native/packages/react-native-gradle-plugin" at this path.

That package is only available when I fork the react-native branch. Then i am very confused how to process, because when i run yarn install command line the react-native is installed normally without the package above.

Could you please help me on this?

**Comment by cortinico** [comment]
> 5\. Then i got this error message. I saw that this package is not exist "node_modules/react-native/packages/react-native-gradle-plugin" at this path.

Have you used `git clone` inside `node_modules`. If so, you'll have the `packages/` folder there with the `react-native-gradle-plugin` there. If not, you won't be able to build from source.

**Comment by thuongtv-vn** [comment]
Hi @cortinico 
I run into this error. Could you please help me on this?

android/gradle-maven-push.gradle': 46: unable to resolve class MavenDeployment 
   @ line 46, column 26.
             beforeDeployment { MavenDeployment deployment -> signing.signPom(deployment) }

**Comment by cortinico** [comment]
> Now i am using react-native version: 0.63.4

You can't use RN 0.63 AND build from source.
You first have to update your app to RN 0.68, and then switch to build from source.
