### ISSUE TITLE
Fetch HTTP Basic Authentication doesn't work

### ISSUE THREAD

**Issue by viveksatasiya** [facebook/react-native#3321]
When I am sending request like this http://username:password@example.com/ using fetch api. I got 401 unauthorized response.

Does Fetch support http basic authentication?? If yes then how to send a request???

Thanks.

**Comment by miolini** [comment]
Hi @viveksatasiya 

Fetch could send auth headers if you specify it in request object as second argument

http://stackoverflow.com/questions/30203044/using-an-authorization-header-with-fetch-in-react-native

**Comment by KelseyRegan** [comment]
miolini, can you provide more info?  This link does not solve the problem explicitly.

**Comment by atom992** [comment]
From [fetch spec!](https://fetch.spec.whatwg.org/#authentication-entries), fetch can set user and password,but there is no example and more doc info to describe it.
any one can give a example?

**Comment by christopherdro** [comment]
@atom992 If your endpoint requires some sort of authorization you'll need to pass that info inside the headers of your request.

```
fetch('/users', {
  method: 'post',
  headers: {
    'Accept': 'application/json',
    'Content-Type': 'application/json',
    'Authorization': token
  },
  body: JSON.stringify({
    name: 'Hubot',
    login: 'hubot',
  })
})
```

Closing this issue since it's unrelated to react native and we are trying to reduce issues down to core bugs. Hope the above snippet helps! Thanks!
