### ISSUE TITLE
addReactInstanceEventListener() does not call the listener if the ReactContext is already ready

### ISSUE THREAD

**Issue by jg210** [facebook/react-native#33219]
### Description

https://github.com/facebook/react-native/blob/v0.68.0-rc.2/ReactAndroid/src/main/java/com/facebook/react/ReactInstanceManager.java#L1008

This means that client code will only run these listeners if register the listeners early enough. I.e. client code using these listeners will generally only sometimes work correctly.

I don't know if it's safe to fix this directly - some client code might rely on the existing behaviour. It might be better to deprecate the API and just make people use RN modules, where can use the initialize() callback instead.

If reimplement the API, I think it would be good if the listeners were automatically unregistered after they are called.

It's not possible to wrap the existing implementation in client code and only use the listener if getCurrentReactContext() is null due to https://github.com/facebook/react-native/issues/33218. I'm not sure if it would be possible to do this even if fix that issue, since there are so many threads involved here. Also, getCurrentReactContext() is annotated as @VisbleForTesting too (which hasn't stopped us using it in our app).

### Version

0.68.0-rc.2

### Output of `npx react-native info`

N/A

### Steps to reproduce

Call addReactInstanceEventListener() long after the ReactContext is available. The listener won't get called.

**Comment by JeremyGreen-TomTom** [comment]
(https://github.com/facebook/react-native/issues/33210 is another bug I found in this code.)

**Comment by jg210** [comment]
The code is unchanged, so this issue still exists.
