### ISSUE TITLE
Switching between TextInputs with values set does something funny to the keyboard

### ISSUE THREAD

**Issue by hiral1987** [facebook/react-native#33216]
### Description

when i switch keyboard type from numeric to email-address , the keyboard open in Uppercase. if i make it lowercase it auto change to uppercase 

### Version

0.64.0

### Output of `npx react-native info`

System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i3-1005G1 CPU @ 1.20GHz
    Memory: 1.93 GB / 7.77 GB
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE      
    Yarn: Not Found
    npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7784292
    Visual Studio: Not Found
  Languages:
    Java: 17.0.1 - C:\Program Files\Common Files\Oracle\Java\javapath\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: ^0.64.0 => 0.64.0
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

set keyboardType={ 'numeric'} for TextInput & on button click change  keyboardType to  'email-address'

**Comment by dellert** [comment]
Same issue
