### ISSUE TITLE
On Android, textAlign={'justify'} does not work with selectable={true}

### ISSUE THREAD

**Issue by rauleffting** [facebook/react-native#33213]
### Description

On Android, textAlign={'justify'} does not work with selectable={true}.

I'm developing a reading book app. I need this to work, so I can publish my app...

This is a dumb bug.

### Version

0.67.3

### Output of `npx react-native info`

System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
    Memory: 5.09 GB / 11.88 GB
  Binaries:
    Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 23, 25, 28, 29
      Build Tools: 23.0.1, 28.0.3, 29.0.2, 29.0.3, 30.0.2
      System Images: android-28 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6626763
  Languages:
    Java: Not Found
    Python: 2.7.17
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: ^0.67.3 => 0.67.3
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. Create a fresh react native application
2. Insert sample component with style={{textAlign: 'justify'}} and selectable={true} properties into component

### Snack, code example, screenshot, or link to a repository

export default function App{
  return (
      <View>
        <Text style={{textAlign: 'justify'}} selectable={true}>
               Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud    exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
        </Text>
      </View>
  );
};

**Comment by jsmaroc** [comment]
On Android, the value 'justify' is only supported on Oreo (8.0) or above (API level >= 26)

**Comment by lanjinglingxx** [comment]
我的也没效果，不管是安卓几
