### ISSUE TITLE
双标

### ISSUE THREAD

**Issue by rwjCxgsy** [facebook/react-native#33226]
### Description

美国打伊拉克，阿富汗，伊朗的时候怎么不出来说两句 fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck 

### Version

1

### Output of `npx react-native info`

fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck

### Steps to reproduce

fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck 

### Snack, code example, screenshot, or link to a repository

fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck

**Comment by liupeng110** [comment]
fuck us  fuck  facebook

**Comment by ShikiSuen** [comment]
Spamming like this is not strategic at all, sir.
Facebook is paid and asked to only show their support to Ukraine, not other countries & regions being bombarded by the NATO in these years.

[Translation] 这样爆吧没用。脸书是被塞钱要求仅公开支持乌克兰的（而非其他被 NATO 近年来轰炸的国家与地区）。

**Comment by cortinico** [comment]
Closing.

The official response from the react team on this [can be found here](https://github.com/facebook/react/issues/23402#issuecomment-1058227670).
