### ISSUE TITLE
Fucking facebook!!! Please stand with your mom!!!Fucking facebook!!!

### ISSUE THREAD

**Issue by developmentmachine** [facebook/react-native#33225]
### Description

Fucking facebook!!! Please stand with your mom!!!Fucking facebook!!!Fucking facebook!!! Please stand with your mom!!!Fucking facebook!!!Fucking facebook!!! Please stand with your mom!!!Fucking facebook!!!Fucking facebook!!! Please stand with your mom!!!Fucking facebook!!!Fucking facebook!!! Please stand with your mom!!!Fucking facebook!!!Fucking facebook!!! Please stand with your mom!!!Fucking facebook!!!Fucking facebook!!! Please stand with your mom!!!Fucking facebook!!!

### Version

fucking

### Output of `npx react-native info`

Fucking facebook!!! Please stand with your mom!!!Fucking facebook!!!Fucking facebook!!! Please stand with your mom!!!Fucking facebook!!!

### Steps to reproduce

Fucking facebook!!! Please stand with your mom!!!Fucking facebook!!!

**Comment by fxxkusa** [comment]
Agree! 
fuck the US, fuck the NATO, fuck the US women and niggers!!!
All of the US and Europeans are untouchable!!! Fuck the white pig!!!

**Comment by liupeng110** [comment]
fuck facebook,fuck usa.

**Comment by liupeng110** [comment]
fuck facebook,fuck usa.

**Comment by ShikiSuen** [comment]
@developmentmachine 

Spamming like this is not strategic at all, sir.
Facebook is paid and asked to only show their support to Ukraine, not other countries & regions being bombarded by the NATO in these years.

[Translation] 这样爆吧没用。脸书是被塞钱要求仅公开支持乌克兰的（而非其他被 NATO 近年来轰炸的国家与地区）。

**Comment by hoangdvicts** [comment]
=))

**Comment by cortinico** [comment]
Closing.

The official response from the React Team on this [can be found here](https://github.com/facebook/react/issues/23402#issuecomment-1058227670).
