### ISSUE TITLE
双标

### ISSUE THREAD

**Issue by zwkkwz2** [facebook/react-native#33228]
### Description

双标

### Version

双标

### Output of `npx react-native info`

双标

### Steps to reproduce

双标

### Snack, code example, screenshot, or link to a repository

双标

**Comment by fisheye-123** [comment]
Fuck React, fuck USA

**Comment by fxxkusa** [comment]
Agree!
fuck the US, fuck the NATO, fuck the US women and niggers!!!
All of the US and Europeans are untouchable!!! Fuck the white pig!!!

**Comment by cortinico** [comment]
Closing.

The official response from the react team on this [can be found here](https://github.com/facebook/react/issues/23402#issuecomment-1058227670).
