### ISSUE TITLE
[ListView & ScrollView android] ListView can not drag only show blue light

### ISSUE THREAD

**Issue by hufeng** [facebook/react-native#3325]
![image](https://cloud.githubusercontent.com/assets/533008/10410858/0f16b088-6f82-11e5-9132-af531f2283d2.png)

**Comment by ide** [comment]
Are you referring to the fact that when you scroll down past the top, it does not bounce? If so, this is a "feature" of Android and not really something React Native can fix without reimplementing ScrollView.

**Comment by hufeng** [comment]
@ide thank you very much, I see.  Because I want to implement Pull refresh ListView, But I found that ListView has different appearance on different Android platform.

**Comment by ide** [comment]
There is a refresh component being worked on (see Known Issues section of the docs). The scroll view will still not let you pull it down though.

**Comment by hufeng** [comment]
ok,  let me try SwipeRefreshLayout

**Comment by jbrodriguez** [comment]
> There is a refresh component being worked on (see Known Issues section of the docs). The scroll view will still not let you pull it down though
@ide any timeframe on the swipe refresh component ?
@hufeng are you working on wrapping SwipeRefreshLayout right now ?

**Comment by ide** [comment]
@jbrodriguez not sure about the time frame for swipe refresh. My guess is 1-2 months?

**Comment by jbrodriguez** [comment]
@ide thanks ! I'll look for some alternatives in the mean time.

**Comment by hufeng** [comment]
@jbrodriguez Yes, SwipeRefreshLayout is ok。
![image](https://cloud.githubusercontent.com/assets/533008/10568915/01986976-7651-11e5-8618-d0cf607ed468.png)

**Comment by Emory-M** [comment]
@hufeng How to implement SwipeRefreshLayout in React-Native?

**Comment by hufeng** [comment]
@Emory-M  just like this. https://github.com/race604/ZhiHuDaily-React-Native/tree/master/android/app/src/main/java/com/race604/react/view/swiperefresh

**Comment by Emory-M** [comment]
@hufeng Thank you! : )

**Comment by LeoJiaXin** [comment]
In android native code，the blue fading effects can be removed. Could this work?
```java
someScrollView.setOverScrollMode(OVER_SCROLL_NEVER);
```
Could you please add a Prop to `ScrollView` for Android, so this blue fading effetcs could be optional?
@ide

**Comment by satya164** [comment]
Android now has Pull to refresh from 0.17
