### ISSUE TITLE
How to write custom native views(eg. WKWebView)?

### ISSUE THREAD

**Issue by imWildCat** [facebook/react-native#333]
Currently all the Views (Components) are produced by the official team. But I'd like to use some custom features such as WKWebView, [PNChart](https://github.com/kevinzhow/PNChart).
What is the elegant way to add custom native views in Objective-C?

**Comment by marciok** [comment]
You can extend PNChart for example, did you check https://github.com/facebook/react-native#extensibility ?

**Comment by imWildCat** [comment]
@marciok , Thanks a lot. I apologise for my careless.

**Comment by sahrens** [comment]
We're planning on writing a more complete guide/tutorial for plugging in your own native views, but that mini-guide + digging through code for the existing Views (e.g. RCTImageViewManager) will have to do for now.
