### ISSUE TITLE
IsConnected.fetch not passing correct value, tested on iOS

### ISSUE THREAD

**Issue by agmcleod** [facebook/react-native#3333]
Following the example in the netinfo docs. I setup the `NetInfo.IsConnected.fetch()` in `componentDidMount`. With airplane mode on the device, the callback passes true. I also attached the events as the example suggested. Those work fine, when i turned airplane mode off, it shows connected, when i turn it back on, connected is set to false. Here's my relevant component code:

```
const React = require('react-native');
const appStyles = require('../styles/app_styles');
const styles = require('../styles/form_page_styles');
const NavigationBar = require('react-native-navbar');

const {
  Component,
  NetInfo,
  Text,
  TextInput,
  TouchableHighlight,
  View
} = React;

class Login extends Component {
  static displayName = 'Login';
  static propTypes = {
    navigator: React.PropTypes.object
  };
  constructor(props) {
    super(props);
    this.state = {
      isConnected: null
    };
    this._handleReachabilityChange = this._handleReachabilityChange.bind(this);
  }

  componentDidMount() {
    NetInfo.isConnected.addEventListener('change', this._handleReachabilityChange);
    NetInfo.isConnected.fetch().done(
      (isConnected) => { this.setState({isConnected}); }
    );
  }

  componentWillUnmount() {
    NetInfo.isConnected.removeEventListener('change', this._handleReachabilityChange);
  }

  _handleReachabilityChange(isConnected) {
    this.setState({
      isConnected
    });
  }

  render() {
    return (
      <View style={appStyles.container}>
        <Text style={styles.header}>Login</Text>
        {this.state.isConnected ? null : <Text style={styles.globalError}>You must be online to login</Text>}
      </View>
    );
  }
}

module.exports = Login;
```

**Comment by vjeux** [comment]
Hey, do you mind trying to trace through the native implementation to figure out what's going on? :)

**Comment by agmcleod** [comment]
Did some break points, it would seem the getSuccess is receiving the correct status. However, I'm not sure how to debug the JS implementation from my device, to see if it's doing something wrong. I can connect to the packager, but once i turn on airplane mode, i'd lose that connection.

**Comment by christopherdro** [comment]
It seems like things are working fine for me on my end. When I switch to airplane mode i get false, then I swtich back it returns true.

The issue i'm noticing is that if you just tap wifi on and off it'll consistently return true.

**Comment by agmcleod** [comment]
Yeah switching airplane mode on & off works fine. It's just that when the app boots, and i have airplane mode on already, i get connected true from the `fetch()` call.

**Comment by christopherdro** [comment]
Had to switch between bundle builds to test this properly.

Looks like it was just a small thing that was overlooked when they decided to rename RCTReachability to RCTNetInfo.

**Comment by agmcleod** [comment]
@christopherdro awesome, thanks for finding a fix :)
