### ISSUE TITLE
run on device error(ios)

### ISSUE THREAD

**Issue by sherlock221** [facebook/react-native#3336]
I refer to this article （Running On Device）
http://facebook.github.io/react-native/docs/running-on-device-ios.html#content

ip4s(ios 7.0) not work  but  ip6(9.0.2) is ok
error detail:

![22](https://cloud.githubusercontent.com/assets/5842676/10415130/62743740-701e-11e5-98d5-df2416c7156f.jpg)

system 
os : 10.10
ios : 7.0.4
device : iphone4s

**Comment by sherlock221** [comment]
ps   react-native version 0.12

**Comment by brentvatne** [comment]
this should be fixed on master & upcoming 0.13 release @sherlock221: https://github.com/facebook/react-native/commit/e885628245193dfbd893ec27aed901607a543cdc

let me know if it still persists and I'll reopen the issue

**Comment by sherlock221** [comment]
@brentvatne  ok I will pay attention to this issue on 0.13
