### ISSUE TITLE
[Android] Display a clearer error message when native react artifact does not match npm artifact

### ISSUE THREAD

**Issue by zenlambda** [facebook/react-native#3337]
A user might update to the latest react-native in npm but forget to update the native dependency in gradle. Currently upgrading the npm dependency to 0.12.0 but leaving the native dependency at 0.11.0 by accident produces the following error `TypeError: expected dynamic type `string', but had type `int64'`.

(Full stack trace copied from [#3033](https://github.com/facebook/react-native/issues/3033#issuecomment-146516384))
```
E/unknown:React( 4614): Exception in native call from JS
E/unknown:React( 4614): com.facebook.react.bridge.UnexpectedNativeTypeException: TypeError: expected dynamic type `string', but had type `int64'
E/unknown:React( 4614):     at com.facebook.react.bridge.ReadableNativeMap.getString(Native Method)
E/unknown:React( 4614):     at com.facebook.react.uimanager.CatalystStylesDiffMap.getString(CatalystStylesDiffMap.java:72)
E/unknown:React( 4614):     at com.facebook.react.views.text.ReactTextShadowNode.updateProperties(ReactTextShadowNode.java:310)
E/unknown:React( 4614):     at com.facebook.react.views.textinput.ReactTextInputShadowNode.updateProperties(ReactTextInputShadowNode.java:102)
E/unknown:React( 4614):     at com.facebook.react.uimanager.UIManagerModule.createView(UIManagerModule.java:256)
E/unknown:React( 4614):     at java.lang.reflect.Method.invoke(Native Method)
E/unknown:React( 4614):     at java.lang.reflect.Method.invoke(Method.java:372)
E/unknown:React( 4614):     at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:106)
E/unknown:React( 4614):     at com.facebook.react.bridge.NativeModuleRegistry$ModuleDefinition.call(NativeModuleRegistry.java:126)
E/unknown:React( 4614):     at com.facebook.react.bridge.NativeModuleRegistry.call(NativeModuleRegistry.java:64)
E/unknown:React( 4614):     at com.facebook.react.bridge.CatalystInstance$NativeModulesReactCallback.call(CatalystInstance.java:326)
E/unknown:React( 4614):     at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
E/unknown:React( 4614):     at android.os.Handler.handleCallback(Handler.java:739)
E/unknown:React( 4614):     at android.os.Handler.dispatchMessage(Handler.java:95)
E/unknown:React( 4614):     at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
E/unknown:React( 4614):     at android.os.Looper.loop(Looper.java:135)
E/unknown:React( 4614):     at com.facebook.react.bridge.queue.MessageQueueThread$1.run(MessageQueueThread.java:137)
E/unknown:React( 4614):     at java.lang.Thread.run(Thread.java:831)
```

This is error is confusing, especially to newcomers. I'm also *guessing* this error will vary from release to release. So it would seem a good idea to try and detect when there is a miss-match and report that as the error. An alternative idea that @mkonicek [mentioned](https://twitter.com/martinkonicek/status/652958430009917440) might be to release the native artifact with npm. That way the two dependencies are changed in the same place or possibly expressed only as a single dependency.

The error message in question has been reproduced in the following issues #3033 #3329 #3146 .

**Comment by brentvatne** [comment]
Great point @zenlambda, this would be a very useful feature!

**Comment by chirag04** [comment]
we have the exact same problem and are solving this by always compiling react-native from node_modules. Even for third-party module, i recommend compiling rn from source, so that everything depends on the same source of truth in node_modules/react-native.

@ide @mkonicek  what do you guys think about compiling from node_modules as the default behaviour just like ios.

Below are the steps for doing that:

in ``andoid/build.gradle`` add ``gradle-download-task`` as dependency.
```gradle
dependencies {
        classpath 'com.android.tools.build:gradle:1.3.1'
        classpath 'de.undercouch:gradle-download-task:2.0.0'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
```

in ``andoid/settings.gradle``
```gradle
include ':app', ':ReactAndroid', ':RNMail'

project(':ReactAndroid').projectDir = new File(rootProject.projectDir, '../node_modules/react-native/ReactAndroid')

// third party rn npm deps
project(':RNMail').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-mail/android')
```

in ``app/build.gradle``
```gradle
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:23.0.1'

    compile project(':ReactAndroid')
    compile project(':RNMail')
}
```

For publishing third party components:
in ``react-native-mail/android/build.gradle``
```gradle
dependencies {
    compile project(':ReactAndroid')
}
```

**Comment by ide** [comment]
Compiling from source is too slow now. If we can get it down to 5 seconds from clicking Run to having the app running w/exopackage I think that would be acceptable.

**Comment by mkonicek** [comment]
Let's not build from source as it's too slow and requires and additional step in the already complex [setup](https://github.com/facebook/react-native/tree/master/ReactAndroid#prerequisites) - the NDK. I think we should distribute the Android artifacts (binaries) to npm, however. This way the version mismatch can't happen.

People writing 3rd-party modules should target a released version of React Native (could be a rc version if you want the "latest" code, up to two weeks old).

**Comment by chemuto** [comment]
@chirag04 That worked for me. Thanks!

**Comment by chirag04** [comment]
:+1:

**Comment by dsibiski** [comment]
:+1: For Chirag's approach. I've been getting reasonable compile times (never sub 5 second though) even with compiling from source. It's only the very first time I compile after a fresh `npm i` that it takes a lot longer. (Perhaps it makes a difference that I'm on a latest maxed out MacBook Pro)

```
BUILD SUCCESSFUL

Total time: 7.524 secs
```

**Comment by chirag04** [comment]
Nice. @mkonicek you can definitely check one approach described here while you are looking into this.
sub 5 second builds would be awesome.

**Comment by satya164** [comment]
React Native binaries are now distributed through NPM. So this is no longer relevant. Closing.
