### ISSUE TITLE
Facebook should not post tips on its React official website to support Ukraine

### ISSUE THREAD

**Issue by leeguooooo** [facebook/react-native#33377]
### Description

1

### Version

1

### Output of `npx react-native info`

1

### Steps to reproduce

1

**Comment by ShikiSuen** [comment]
It is not an issue of "should not", but Facebook should also show their support to all those innocent countries & regions bombarded by NATO and United States in the past few decades.

However, it is apparent that Facebook is paid and asked to show their public concerns to Ukraine only.
