### ISSUE TITLE
[Android] changing the TextInput's placeholder prop resets the text value back to its default value  

### ISSUE THREAD

**Issue by nadavbahalul** [facebook/react-native#33389]
### Description

Only on Android, if the `placeholder` prop of the `TextInput` component get changed, the `TextInput` value being reset to its default value, instead of keeping the same value it had.
This is a new issue started lately after we bumped react-native version.
This is reproduced only on Android (checked it on few different devices / emulators), works fine on iOS.

Here is the video of the issue (the expected result is that the value of the text input will be saved also even the placeholder being changed - by the button pressing):

https://user-images.githubusercontent.com/48596416/156921380-79a5bef5-008f-49e0-aeed-ef19e9810540.mov

I've created a project in this repo as an example: https://github.com/nadavbahalul/TextInputPlaceholderExample 

### Version

0.67.3 (also reproduced on 0.66.4)

### Output of `npx react-native info`

System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 438.97 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.4.0 - ~/.nvm/versions/node/v14.4.0/bin/node
    Yarn: Not Found
    npm: 6.14.5 - ~/.nvm/versions/node/v14.4.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.13 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.3 => 0.67.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1) git clone this repo: https://github.com/nadavbahalul/TextInputPlaceholderExample
2) run `npm install`
3) run `npx react-native start`  &  `npx react-native run-android`
4) edit the text input text, then press the button

**Comment by Emeka-Ugbanu-hub** [comment]
I would love to help with this

**Comment by feras-merwas** [comment]
@nadavbahalul 

you should add onChangeText and value to textinput 

without these props textinput did not save anything 

```
    <TextInput
        defaultValue="123"
        placeholder={placeholder}
        value={value}
        onChangeText={value => {
          setValue(value);
        }}
      />

````
