### ISSUE TITLE
iOS only issue : overflow "hidden" removes shadow styles

### ISSUE THREAD

**Issue by aditya-keri-betterhalf** [facebook/react-native#33380]
### Description

There are two issues that were open and closed without resolution which talks about the same issue that I am posting here :

https://github.com/facebook/react-native/issues/449
https://github.com/facebook/react-native/issues/26545

Issue : 

A View which has `elevation` (for **android**), `shadow` properties (for **iOS**) and `overflow: 'hidden'`, removes the shadow properties in iOS but preserves the elevation property in Android.

I want to know what is the best way around this ? Is there a clean-ish hack to solve this for iOS ?

### Version

0.66.4

### Output of `npx react-native info`

```
System:
    OS: macOS 12.0.1
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 172.01 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.5 - /usr/local/bin/node
    Yarn: 1.22.15 - ~/.yarn/bin/yarn
    npm: 7.24.1 - /usr/local/bin/npm
    Watchman: 2022.01.03.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 26, 28, 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7621141
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.4 => 0.66.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```
### Steps to reproduce

1. Create a View
2. Add elevation and shadow properties to this View
3. Add `overflow: 'hidden'` to the same View

Observe that elevation works but the shadow properties do not.

### Snack, code example, screenshot, or link to a repository

![image](https://user-images.githubusercontent.com/90186621/156750462-68b79079-1f7c-4de7-a5a3-bbc0a7dbc8b2.png)

Expo repro : 
https://snack.expo.dev/GC5aHueSp

**Comment by joaorr3** [comment]
related: #26545

**Comment by joaorr3** [comment]
#26545

**Comment by bimalgrg519** [comment]
I am facing same issue
