### ISSUE TITLE
How to use "flex" for "auto flow layout "?

### ISSUE THREAD

**Issue by KJlmfe** [facebook/react-native#334]
I have some Views that need to auto flow layout in parent View.

What styles can  achieve below result.

![2015-03-27 7 24 42](https://cloud.githubusercontent.com/assets/1238134/6867116/d859dd08-d4b9-11e4-9c7e-627a25c12f50.png)

**Comment by vjeux** [comment]
If you want 3 elements to take 1/3 of the space each, you can do

```
<View style={{flexDirection: row}}>
  <View style={{flex: 1}} />
  <View style={{flex: 1}} />
  <View style={{flex: 1}} />
</View>
```

each element is going to take 1/(1+1+1) of the space.

Is this what you want?

**Comment by KJlmfe** [comment]
@vjeux In your way is ok, but I have to make every three children in one row. 

I want to put all 33% children in one parent View and it can auto flow layout, is there a way?

**Comment by jsierles** [comment]
This is possible using the Dimensions class to calculate the width of the box from the viewport dimensions. However, the above solution is preferred as it would scale across devices and orientations. [Here's a more complex example of a grid view](https://github.com/lucholaf/react-native-grid-view/blob/master/index.js#L13).
