### ISSUE TITLE
Intermittent JavaScript-side connection issues on some networks on android (but not on the native side)

### ISSUE THREAD

**Issue by CatalinVoss** [facebook/react-native#33404]
### Description

We have been observing sporadic extreme network slowness in React Native that occurs on some network requests
- *only on android* (same app, same code completely fine on iOS)
- *only on some WiFi networks* (switch the tablet to a phone hotspot or a different WiFi network and the issue goes away. Always an issue on office WiFi (ubiquity mesh) never an issue at home (Google WiFi mesh))
- *only on the JavaScript side* (make a network request in `MainActivity.java` natively – no issue; make it in `App.js`, everything stalls)

The most basic way we've been able to isolate this is into a completely fresh `react-native` 0.67.3 project created with `npx react-native init NetTest` using only the `fetch` library. (Though the issue affects any other third party JS networking service as well, as best as we can tell, e.g. Apollo Client.)

Any ideas of what this might be or advice on how to go about debugging it?

### Version

0.67.3 and 0.66.3

### Output of `npx react-native info`

<details>
System:
    OS: macOS 12.2.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 1.04 GB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.9.0 - ~/.nvm/versions/node/v15.9.0/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 7.5.3 - ~/.nvm/versions/node/v15.9.0/bin/npm
    Watchman: 2021.11.08.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 28, 30, 31, 32
      Build Tools: 28.0.3, 30.0.2, 30.0.3, 31.0.0
      Android NDK: 21.4.7075529
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_131 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.3 => 0.67.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
</details>

### Steps to reproduce

Build a new vanilla react native project
```
npx react-native init NetTest
```

Add the following code to `App.js`

```
  const getMoviesFromApi = async () => {
    try {
      console.log('starting fetch');
      const response = await fetch('https://reactnative.dev/movies.json');
      const json = await response.json();
      console.log('got result');
      return json.movies;
    } catch (error) {
      console.error(error);
    }
  };

  useEffect(() => {
    console.log('app loading. making web request');
    getMoviesFromApi().then(result => console.log(result));
  });
```

Run on Android.

**Result**: On some WiFi networks, on all Android devices, the delay between "`starting fetch`" and "`got result`" is 5 mins, even though iOS on the same network is 5 seconds.

Now experiment with making the same request on the native side in `MainActivity.java`:
```
public class MainActivity extends ReactActivity {
  private OkHttpClient client = new OkHttpClient();

  /**
   * Returns the name of the main component registered from JavaScript. This is used to schedule
   * rendering of the component.
   */
  @Override
  protected String getMainComponentName() {
    return "NetTest";
  }

  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    run("https://reactnative.dev/movies.json");
  }

  void run(String url) {
    Request request = new Request.Builder().url(url).build();
    client.newCall(request).enqueue(new Callback() {
      @Override
      public void onResponse(@NonNull Call call, @NonNull Response response) throws IOException {
        Log.i("MainActivity", response.body().string());
      }

      @Override
      public void onFailure(@NonNull Call call, @NonNull IOException e) {
      }
    });
  }
}
```

Result: Returns instantaneously, no problem.

**Comment by CatalinVoss** [comment]
This issue appears to be related to fallbacks in the case of a bad IPv6 config (e.g. a DNS server that would time out). Applying a patch per https://github.com/facebook/react-native/issues/32730 via this [gist](https://gist.github.com/danmaas/c60af5fed9f55d2bc616ce302696540d) that forces OkHttpClient to fall back to IPv4 eagerly resolves the problem. However, I'm still not entirely sure why the issue didn't occur on the Java/Kotlin side?

**Comment by enlo314** [comment]
Hi, @andac-ozcan this solution works on development but not on the production release, any workaround?

**Comment by JKKholmatov** [comment]
Did you find any solution? I am having this issue in an Expo Project, cant find any solution
@CatalinVoss @enlo314
