### ISSUE TITLE
ReferenceError: Can't find variable: _UIManager

### ISSUE THREAD

**Issue by my-name-is-nheo** [facebook/react-native#33403]
### Description

Getting an error every time I try to run my app on the android and ios simulator. It'll work for one but error out when i try to navigate on the other. tried cleaning cache, reinstalling nodemodules, cleaning project, etc. 

### Version

0.67.3

### Output of `npx react-native info`

System:
    OS: macOS 12.0
    CPU: (8) x64 Apple M1 Pro
    Memory: 70.20 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: Not Found
    npm: 8.1.4 - ~/.nvm/versions/node/v16.13.1/bin/npm
    Watchman: 2021.10.18.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7784292
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.10 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.2 => 17.0.2 
    react-native: ^0.67.3 => 0.67.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

npm run ios and npm run android:devdebug

will run on ios but errors out on android with the error message `ReferenceError: Can't find variable: _UIManager`

**Comment by justinairbase** [comment]
![IMG_2F27D7FC1E63-1](https://user-images.githubusercontent.com/51368399/159924370-13fe58a4-1f16-490b-97b8-a2638e7b5eb7.jpeg)
![IMG_6B30D21CDC24-1](https://user-images.githubusercontent.com/51368399/159924389-539e185b-acf0-4a7b-9275-b602411495aa.jpeg)


Facing this error while testing simultaneously on Android and iOS

**Comment by justinairbase** [comment]
Output of npx react-native info

```
System:
    OS: macOS 12.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 147.21 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
    Watchman: 2022.02.28.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 23, 27, 28, 29, 30, 31
      Build Tools: 29.0.2, 29.0.3, 30.0.0, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 33.0.0
      System Images: android-26 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-Tiramisu | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 13.3/13E113 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.13 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.2 => 0.66.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

```

**Comment by justinairbase** [comment]
Logs from JS 

```
ReferenceError: Property '_UIManager' doesn't exist
  at _onFsPressForward_Pressability(app:///main.jsbundle:1:313479)
  at _performTransitionSideEffects(app:///main.jsbundle:1:312328)
  at _receiveSignal(app:///main.jsbundle:1:311833)
  at onResponderRelease(app:///main.jsbundle:1:311018)
  at apply(native)
  at invokeGuardedCallbackImpl(app:///main.jsbundle:1:127019)
  at apply(native)
  at invokeGuardedCallback(app:///main.jsbundle:1:126951)
  at apply(native)
  at invokeGuardedCallbackAndCatchFirstError(app:///main.jsbundle:1:127141)
  at executeDispatch(app:///main.jsbundle:1:127103)
  at executeDispatchesAndReleaseTopLevel(app:///main.jsbundle:1:130596)
  at forEach(native)
  at forEachAccumulated(app:///main.jsbundle:1:128709)
  at anonymous(app:///main.jsbundle:1:130953)
  at batchedUpdatesImpl(app:///main.jsbundle:1:186627)
  at batchedUpdates(app:///main.jsbundle:1:130513)
  at _receiveRootNodeIDEvent(app:///main.jsbundle:1:130790)
  at receiveTouches(app:///main.jsbundle:1:180700)
  at apply(native)
  at __callFunction(app:///main.jsbundle:1:117206)
  at anonymous(app:///main.jsbundle:1:115689)
  at __guard(app:///main.jsbundle:1:116652)
  at callFunctionReturnFlushedQueue(app:///main.jsbundle:1:115647)
```

**Comment by johnny-mcfadden-dailypay** [comment]
Seeing the exact same issue, but it seems fullstory related. I also see you've fullstory issues in your error logs.

**Comment by johnny-mcfadden-dailypay** [comment]
@justinairbase we removed full story and things are back to normal with no android issues. We are still investigating though, it did seem to be scoped to expo OTA updates.

**Comment by rcmaples** [comment]
Hi all,

RC here from FullStory's support engineering team. Sorry to hear about the trouble you're experiencing. If you haven't already please open a ticket with mobile-support@fullstory.com to work with our team to find a solution.

Thanks so much,
RC

**Comment by rcmaples** [comment]
Hey all, for anyone having trouble with FullStory please reach out to mobile-support@fullstory.com and we'll work with you to find a solution. Fwiw, if you're using Metro Server while running into this that might be the root cause. Currently we don't support working with Metro Server and generally when running into _UIManager errors, they're Metro related.

**Comment by justinairbase** [comment]
@rcmaples  I do not understand the "we don't support working with Metro Server" part. We are using [this official react-native package for FullStory](https://github.com/fullstorydev/fullstory-react-native). Which bundler does FS support on react-native?
