### ISSUE TITLE
React Native Android Leaves Transparent Space in 0.67.3 

### ISSUE THREAD

**Issue by tradebulls** [facebook/react-native#33408]
### Description

Hi,

I recently upgraded our project to latest RN 0.67.3 version, where I noticed that Android by default leaves some white/transparent space from top. Attaching ScreenShot
<img width="387" alt="Screenshot 2022-03-10 at 2 20 27 PM" src="https://user-images.githubusercontent.com/54740738/157822429-e1068e5a-1cb6-4cbf-bd32-8ce7f5fc0893.png">

The above grey area is also coming in a demo project that I created that has only react and react native lib added. I tried following other issues regarding status bar like
1. https://github.com/facebook/react-native/commit/9ed2df628ddd410cc3383e68b0386471432445c0
2.https://github.com/facebook/react-native/pull/32975

Tried to copy StatusBarModule.java and pasted it inside node-modules/react-native android folder but it didn't work. 

The same issue is happening on Devices with and above API 30. Any help would be helpful

### Version

0.67.3

### Output of `npx react-native info`

System:
    OS: macOS 12.2.1
    CPU: (4) x64 Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
    Memory: 78.15 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.18.1 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.14.15 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 23, 26, 27, 28, 29, 30, 31
      Build Tools: 28.0.3, 29.0.0, 29.0.2, 30.0.2, 30.0.3, 31.0.0
      System Images: android-28 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_191 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.3 => 0.67.3 
    react-native-macos: Not Found
  npmGlobalPackages:

### Steps to reproduce

Create a Demo Project and Run on Android Emulator API 30( Pixel 4 API 30)

**Comment by arish-panjwani** [comment]
I am facing the same issue..

**Comment by npjoge** [comment]
+1

**Comment by QureshiFaizan** [comment]
+1

**Comment by tradebulls** [comment]
Not facing the issue with Latest version of RN Safe Area Context. Thanks
