### ISSUE TITLE
XHR progress event not firing on iOS while downloading Blob/Arraybuffer response type

### ISSUE THREAD

**Issue by EmilianoMorghen** [facebook/react-native#33410]
### Description

Hello, 
as title says I've noticed a strange behaviour while trying to subscribe to the "progress" event that should be fired by an XHR call.

_NB: Links used below are just for testing purpose, I need to download a big file (about 100MB) and read how many bytes I've already downloaded from "progress" event. Sefram had some heavy file hosted online where I could test_

```Javascript
export default function dlTest(dlCalled, nextTest, settings) {

  if (dlCalled) return;

  dlCalled = true;

  let xhr = new XMLHttpRequest();

  xhr.addEventListener("progress", (e) => console.log("progress", e.loaded));
  xhr.addEventListener("load", (e) => console.log("loaded", e.loaded));
  xhr.addEventListener("error", () => console.log("error"));

  let zipAddress = "https://www.sefram.com/images/products/photos/hi_res/BK1760A.zip";
  let jpgAddress = "https://www.sefram.com/images/products/photos/hi_res/207030301.jpg";
  let documentAddress = "https://www.sefram.com/en/download/high-resolution-images.html";

  xhr.open("GET", zipAddress, true); 
  xhr.responseType = "blob";

  xhr.send();
}
```

Basically I need to read how much bytes I've downloaded since the call started.
To sum up my tests:

- iOS:
  - **Call `documentAddress && Response-Type: document`:**
  It does fire progress event but doesn't update `event.loaded` _(it remains 0)_.
  You can try this yourself with `documentAddress`.
  
  - **Call `documentAddress && Response-Type: blob/arraybuffer`:**
  It doesn't fire progress event at all
  
  - **Call `zipAddress && Response-Type: document`**
  It doesn't fire progress event at all
  
  - **Call `zipAddress && Response-Type: blob/arraybuffer`**
  It doesn't fire progress event at all
  
I can't really understand why this is happening.
I've done many tests on Android, progress mostly work fine, but this isn't the issue to discuss Android's problems.

I've opened this issue because I couldn't find any other discussion about this kind of problems. 
Thanks in advance for your work.

### Version

0.64.3

### Output of `npx react-native info`

```
System:
- OS: Windows 10 10.0.22000
- CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
- Memory: 4.21 GB / 15.85 GB

Binaries:
- Node: 14.17.6 - C:\Program Files\nodejs\node.EXE
- Yarn: Not Found
- npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
- Watchman: Not Found

SDKs:
- Android SDK: Not Found
- Windows SDK:
- AllowAllTrustedApps: Disabled

IDEs:
- Android Studio: Version     2021.1.0.0 AI-211.7628.21.2111.8139111
- Visual Studio: 17.1.32210.238 (Visual Studio Community 2022)

Languages:
- Java: 11.0.12 - C:\Program Files\Microsoft\jdk-11.0.12.7-hotspot\bin\javac.EXE

npmPackages:
- @react-native-community/cli: Not Found
- react: 17.0.1 => 17.0.1
- react-native: 0.64.3 => 0.64.3
- react-native-windows: Not Found

npmGlobalPackages:
- *react-native*: Not Found
```

### Steps to reproduce

1. Setup react-native project
2. Copy `dlTest` 
3. Call it from App.js
4. enjoy 

### Snack, code example, screenshot, or link to a repository

[Snack Example Download Test](https://snack.expo.dev/@lianmor/download-test)

**Comment by ElisabettaRuotolo** [comment]
Same

**Comment by CamilloPositano** [comment]
Same here!
