### ISSUE TITLE
REACT-NATIVE-NETWORKING

### ISSUE THREAD

**Issue by ELECTRO-2006** [facebook/react-native#33415]
### Description

i wanted to use websockets, which is declared in another page now i wanted to listen for the  
message coming how can i do that ?

### Version

66

### Output of `npx react-native info`

NULL

### Steps to reproduce

NULL

### Snack, code example, screenshot, or link to a repository

NULL

**Comment by haveneersrobin** [comment]
The issue tracker is used for bug reports, not for how-to's. Please refer to StackOverflow or similar for these types of questions. 

There are plenty of articles regarding websockets
- https://blog.logrocket.com/how-to-implement-websockets-in-react-native/
- https://ably.com/topic/websockets-react-native
- https://www.npmjs.com/package/react-native-use-websocket
