### ISSUE TITLE
KeyboardAvoidingView is not adjusting correctly because the coordinate system mismatch

### ISSUE THREAD

**Issue by summer-wu** [facebook/react-native#33421]
### Description

You are comparing height using different coordinate systems.
The keyboard frame is in window system, and the view's frame is in **parent view's coordinate system.**
We have to convert the frame to the same coordinate system then do compare.
Here is how I fix it:

```js
  _onLayout = (event: any) => {
    const measureCallback = (x: number, y: number, width: number, height: number) => {
      const wasFrameNull = this._frame == null;
      this._frame = { x, y, width, height };
      if (!this._initialFrameHeight) {
        // save the initial frame height, before the keyboard is visible
        this._initialFrameHeight = this._frame.height;
      }

      if (wasFrameNull) {
        this._updateBottomIfNecesarry();
      }
    };
    this.viewRef.current.measureInWindow(measureCallback);
  };
```

The buggy version:
```js
  _onLayout = (event: ViewLayoutEvent) => {
    const wasFrameNull = this._frame == null;
    this._frame = event.nativeEvent.layout;
    if (!this._initialFrameHeight) {
      // save the initial frame height, before the keyboard is visible
      this._initialFrameHeight = this._frame.height;
    }

    if (wasFrameNull) {
      this._updateBottomIfNecesarry();
    }
  };
```

### Version

0.66

### Output of `npx react-native info`

don't needed

### Steps to reproduce

don't needed

**Comment by drice** [comment]
Possibly related, I'm seeing when keyboard is opened in landscape then rotated to portrait, the _initialFrameHeight is a different value than when it was opened in portrait so it doesn't resize correctly.

**Comment by HacerBusraKILIC** [comment]
I'm having trouble switching from landscape to portrait and from portrait to landscape with KeyboardAvoidingView on android. Any idea how can i solve it?

https://user-images.githubusercontent.com/26281251/168608183-ba266ba1-df36-444a-9034-e73cef8d9ce4.mp4

**Comment by cortinico** [comment]
Closing as stale

**Comment by roniemartinez** [comment]
This bug still exists on Android (Samsung). Is anybody able to make a temporary fix?

Reproduction:
1. Use `padding` behavior for `KeyboardAvoidingView`
2. Put the phone in landscape
3. Click on an input to show the keyboard (steps 2 and 3 are interchangeable)
4. Close the keyboard (there is a arrow down button to close it)
5. Move the phone to portrait

After step 5, the view will become around half of the original height.
Unless you click again on an input to show the keyboard (which will then "remove" the padding), the height remains in half.
