### ISSUE TITLE
Disable HTTP-Cache on Android

### ISSUE THREAD

**Issue by MaganAnkur** [facebook/react-native#33429]
### Description

is there any way to avoid storing http cache on android rooted device.

I tried 'cache-control' : 'no-cache', 'no-store'

but still I can see request and response in http_cache folder.

### Version

0.63.4

### Output of `npx react-native info`

OS: macOS 12.2.1
    CPU: (4) x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
    Memory: 14.75 GB / 40.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
    Watchman: 2022.01.24.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /Users/ankur/.rvm/gems/ruby-3.0.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7486908
    Xcode: 13.0/13A233 - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.1 - /usr/bin/javac
    Python: 2.7.18 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

NA

**Comment by lijingchang** [comment]
you can try `OkHttpClientProvider.setOkHttpClientFactory` this api

**Comment by saumyabhatnagar1** [comment]
Any update on this?

**Comment by maxizhukov** [comment]
> you can try `OkHttpClientProvider.setOkHttpClientFactory` this api

This didn't worked, also didn't found any other way to disable it. 

Btw, it creates also security issue, even though other apps can't access it, but still device might stolen, jailbroken or using debug build
