### ISSUE TITLE
Error during react-native init

### ISSUE THREAD

**Issue by Anahkiasen** [facebook/react-native#3342]
I'm trying to setup the demo project, however when I run `react-native init AwesomeProject` it hangs for a while then fails. Running with `--verbose` gives this as last output:

```
npm info lifecycle fsevents@1.0.2~install: fsevents@1.0.2

> fsevents@1.0.2 install /Users/anahkiasen/Sites/anahkiasen/AwesomeProject/node_modules/fsevents
> node-pre-gyp install --fallback-to-build



`npm install --save react-native` failed
```

What I don't get is if I go into the folder an manually run `npm install react-native --save` it works fine. 

```bash
$ node --version && npm --version
v4.1.2
3.3.7
```

**Comment by tarun1793** [comment]
Same, +1

node@v4.1.2
npm@3.3.7
Mac - OS X El Capitan

**Comment by tarun1793** [comment]
As a temporary fix, 

1. `react-native init myProject`
2. `cd myProject && npm install react-native --save`
3. `cd ..`
4. `react-native init myProject`

say `yes` to overwrite the project.

**Comment by louisgv** [comment]
@tarun1793 Worked for me
Same environment
Linux - LMDE Betsy 2

**Comment by browniefed** [comment]
@facebook-github-bot close
