### ISSUE TITLE
[IOS] 'logger/react_native_log.h' file not found in CxxNativeModule.cpp Xcode

### ISSUE THREAD

**Issue by MarinaAmy** [facebook/react-native#33425]
### Description

Hello, 
I wanted to update my project from react-native 0.64 to 0.67. I updated well I deleted my nodes modules folder my package.lock, the podfile.lock and the Pods folder.

I then did an npm install, cd ios pod install and npx react-native bundle --entry-file='index.js' --bundle-output='./ios/main.jsbundle' --dev=false --platform='ios' --assets-dest='./ios'
and when I try to build my project on an iphone 8 ios 15.3.1 it does not work and the error:
'logger/react_native_log.h' file not found from CxxNativeModule.cpp file
appears

Can you help me please

### Version

0.67.3

### Output of `npx react-native info`

System:
    OS: macOS 12.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
    Memory: 25.86 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 8.3.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: ^7.0.1 => 7.0.3 
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.3 => 0.67.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Change version of React-native (0.64 to 0.67)
npm install
cd ios & pod install
npx react-native bundle --entry-file='index.js' --bundle-output='./ios/main.jsbundle' --dev=false --platform='ios' --assets-dest='./ios'

Build the project to xcode
 

### Snack, code example, screenshot, or link to a repository

_No response
![Capture d’écran 2022-03-14 à 16 32 00](https://user-images.githubusercontent.com/31924950/158207108-2a6170cc-fd75-4e16-9aff-fe7020a41c75.png)
_

**Comment by taekwon-oh** [comment]
@Marinaarimany i also had a problem exactly same with.. did you solve this?

**Comment by nikolai-git-house** [comment]
Has this been solved? I also have this issue.

**Comment by nikolai-git-house** [comment]
@Marinaarimany do you mean you didn't see such issue after creating new project with same package and pod file?

**Comment by Marinaarimany** [comment]
it doesn't seem to me, I had to update some packages that I was using

**Comment by dipendra-sharma** [comment]
Has this been solved?

**Comment by Yandamuri** [comment]
Here is solution

> Add pod 'React-logger', :path => '../node_modules/react-native/ReactCommon/logger'

Source: https://github.com/facebook/react-native/issues/33061#issuecomment-1033463246

**Comment by hrupesh** [comment]
A possible fix for this is to disintegrate pods from your project and reinstall pods

`pod deintegrate`

`pod install`
