### ISSUE TITLE
iOS App Build failed on M1 Pro Macbook

### ISSUE THREAD

**Issue by movpushmov** [facebook/react-native#33437]
### Description

iOS App version build crashes with exit code 1.

### Version

0.67.3

### Output of `npx react-native info`

System:
    OS: macOS 12.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 1.20 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - /usr/local/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 6.14.15 - /usr/local/bin/npm
    Watchman: 2022.02.07.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.3 => 0.67.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1) Create new project with command

`npx react-native init AwesomeTSProject --template react-native-template-typescript`

2) Run Metro Bundler

`npm run start`

3) Run iOS Build

`npm run ios`

4) See an Error

### Snack, code example, screenshot, or link to a repository

Crash log:

https://controlc.com/64ad9455

**Comment by khokanuzzman** [comment]
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
 
platform :ios, '11.0'
 
target 'TestApp' do
 config = use_native_modules!
 
 use_react_native!(
   :path => config[:reactNativePath],
   # to enable hermes on iOS, change `false` to `true` and then install pods
   :hermes_enabled => false
 )
 

 pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

 target 'testApp' do
   inherit! :complete
   # Pods for testing
 end
 # Enables Flipper.
 #
 # Note that if you have use_frameworks! enabled, Flipper will not work and
 # you should disable the next line.
 # use_flipper!()÷
 post_install do |installer|
   react_native_post_install(installer)
   __apply_Xcode_12_5_M1_post_install_workaround(installer)
 end
end

**Comment by movpushmov** [comment]
> use platform: ios,'11' and run pod install
> 
> ```
> require_relative '../node_modules/react-native/scripts/react_native_pods'
> require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
>  
> platform :ios, '11.0'
>  
> target 'TestApp' do
>  config = use_native_modules!
>  
>  use_react_native!(
>    :path => config[:reactNativePath],
>    # to enable hermes on iOS, change `false` to `true` and then install pods
>    :hermes_enabled => false
>  )
>  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
> 
>  target 'testApp' do
>    inherit! :complete
>    # Pods for testing
>  end
>  # Enables Flipper.
>  #
>  # Note that if you have use_frameworks! enabled, Flipper will not work and
>  # you should disable the next line.
>  # use_flipper!()÷
>  post_install do |installer|
>    react_native_post_install(installer)
>    __apply_Xcode_12_5_M1_post_install_workaround(installer)
>  end
> end
> ```

last version of React Native doesn't work with last iOS version?

**Comment by khokanuzzman** [comment]
> > use platform: ios,'11' and run pod install
> > ```
> > require_relative '../node_modules/react-native/scripts/react_native_pods'
> > require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
> >  
> > platform :ios, '11.0'
> >  
> > target 'TestApp' do
> >  config = use_native_modules!
> >  
> >  use_react_native!(
> >    :path => config[:reactNativePath],
> >    # to enable hermes on iOS, change `false` to `true` and then install pods
> >    :hermes_enabled => false
> >  )
> >  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
> > 
> >  target 'testApp' do
> >    inherit! :complete
> >    # Pods for testing
> >  end
> >  # Enables Flipper.
> >  #
> >  # Note that if you have use_frameworks! enabled, Flipper will not work and
> >  # you should disable the next line.
> >  # use_flipper!()÷
> >  post_install do |installer|
> >    react_native_post_install(installer)
> >    __apply_Xcode_12_5_M1_post_install_workaround(installer)
> >  end
> > end
> > ```
> 
> last version of React Native doesn't work with last iOS version?

one of the latest react native version 0.67.4 default use platform :ios, '11.0' in pods file

**Comment by movpushmov** [comment]
> > > use platform: ios,'11' and run pod install
> > > ```
> > > require_relative '../node_modules/react-native/scripts/react_native_pods'
> > > require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
> > >  
> > > platform :ios, '11.0'
> > >  
> > > target 'TestApp' do
> > >  config = use_native_modules!
> > >  
> > >  use_react_native!(
> > >    :path => config[:reactNativePath],
> > >    # to enable hermes on iOS, change `false` to `true` and then install pods
> > >    :hermes_enabled => false
> > >  )
> > >  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
> > > 
> > >  target 'testApp' do
> > >    inherit! :complete
> > >    # Pods for testing
> > >  end
> > >  # Enables Flipper.
> > >  #
> > >  # Note that if you have use_frameworks! enabled, Flipper will not work and
> > >  # you should disable the next line.
> > >  # use_flipper!()÷
> > >  post_install do |installer|
> > >    react_native_post_install(installer)
> > >    __apply_Xcode_12_5_M1_post_install_workaround(installer)
> > >  end
> > > end
> > > ```
> > 
> > 
> > last version of React Native doesn't work with last iOS version?
> 
> one of the latest react native version 0.67.4 default use platform :ios, '11.0' in pods file

<img width="733" alt="image" src="https://user-images.githubusercontent.com/49155506/160241666-7bfd89ef-b929-4329-afd7-ba0b5b64abac.png">

<img width="536" alt="image" src="https://user-images.githubusercontent.com/49155506/160241687-e53712db-d02d-4810-874c-c0a333cd32ce.png">

<img width="735" alt="image" src="https://user-images.githubusercontent.com/49155506/160241699-d6d07c0e-7ea4-4400-9bac-4145f081dcc9.png">

Well, this doesn't work.

**Comment by movpushmov** [comment]
@khokanuzzman
