### ISSUE TITLE
FlatList getItemLayout on horizontal lists

### ISSUE THREAD

**Issue by gabrielporcher** [facebook/react-native#33434]
### Description

I'm working with a horizontal FlatList wich render components with heigth 100 or 150 (depends on a prop the item receives).

So my code is:

```
renderList = () => {
    const renderItem = ({item, index}) => (
      <ForecastItem
        item={item}
        index={index}
        key={item.id}
        expand={item => {
          handleExpand(item);
        }}
      />
    );
    const keyExtractor = item => item.id;
    const ITEM_HEIGHT = item.applied ? 150 : 100;
    const getItemLayout = (data, index) => {
      return {
        length: ITEM_HEIGHT,
        offset: ITEM_HEIGHT * data.length,
        index,
      };
    };

    return (
      <FlatList
        data={item.forecast}
        horizontal={true}
        renderItem={renderItem}
        getItemLayout={getItemLayout}
        keyExtractor={keyExtractor}
        initialScrollIndex={4}
      />
    );
  };
```
What is happening is that initialScrollIndex isn't working properly, apparently because the getItemLayout prop is wrong.
I Tried to pass the width size to the getItemLayout length, but it doesnt work too.
So, what can I do to set getItemLayout length and offset properly in horizontal lists? 

EDIT: If I set ITEM_HEIGHT = 25 the list initialScrollIndex works fine. But my heights are 100 / 150 and width 90 (with marginVertical: 5 Idk if it should count in the size calculation).

### Version

0.67.2

### Output of `npx react-native info`

System:
    OS: Linux 5.13 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
    Memory: 1.31 GB / 11.60 GB
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 12.22.1 - ~/.nvm/versions/node/v12.22.1/bin/node
    Yarn: 1.22.11 - /usr/bin/yarn
    npm: 6.14.12 - ~/.nvm/versions/node/v12.22.1/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3
      System Images: android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 11.0.14 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.2 => 0.67.2 
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Calculate getItemLayout length and offset in horizontal lists.

**Comment by Sven2219** [comment]
Here is working code example (tested on iOS). The problem in your getItemLayout is if the Flatlist is horizontal you need to use width and add additional margin. 
[Here](https://stackoverflow.com/questions/48679272/flatlist-getitemlayout-usecase) you can see more detailed explanation

`import React from 'react';
import {FlatList, StyleSheet, View, Text, SafeAreaView} from 'react-native';

const items = new Array(10).fill(0).map((_, index) => ({
  id: index,
  applied: Boolean(index % 2),
  name: `Item${index}`,
}));

const ITEM_WIDTH = 90;
const ITEM_MARGIN_RIGHT = 10;

const App = () => {
  const renderItem = ({item}) => (
    <View style={[styles.item, {height: item.applied ? 150 : 100}]}>
      <Text>{item.name}</Text>
    </View>
  );

  const keyExtractor = item => item.id;

  const getItemLayout = (_, index) => {
    return {
      length: ITEM_WIDTH + ITEM_MARGIN_RIGHT,
      offset: (ITEM_WIDTH + ITEM_MARGIN_RIGHT) * (index - 1),
      index,
    };
  };

  return (
    <SafeAreaView>
      <FlatList
        data={items}
        horizontal={true}
        initialScrollIndex={4}
        renderItem={renderItem}
        getItemLayout={getItemLayout}
        keyExtractor={keyExtractor}
      />
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  item: {
    width: ITEM_WIDTH,
    marginRight: ITEM_MARGIN_RIGHT,
    borderWidth: 1,
  },
});

export default App;
`

**Comment by Sven2219** [comment]
[Here](https://github.com/Sven2219/FlatlistGetItemLayout) is working code example (tested on iOS). Everything is in App.js folder. The problem in your getItemLayout is if the Flatlist is horizontal you need to use width and add additional margin.
[Here](https://stackoverflow.com/questions/48679272/flatlist-getitemlayout-usecase) you can see more detailed explanation

**Comment by gabrielporcher** [comment]
@Sven2219 I will develop these changes when possible, following the example you sent me.

Thank you!!
