### ISSUE TITLE
ActivityIndicator is showing as reload icon in Android

### ISSUE THREAD

**Issue by malik-coachhub** [facebook/react-native#33433]
### Description

Description
When using ActivityIndicator in ReactNative, it works in IOS. But for Android, it is shown as a reload icon

Screenshots:
<img width="330" alt="Screenshot 2022-03-15 at 18 02 18" src="https://user-images.githubusercontent.com/97094483/158442551-9bf75bac-b676-4a8b-a5da-2f4394f12943.png">

### Version

66.4

### Output of `npx react-native info`

System:
    OS: macOS 12.2.1
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Memory: 799.34 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.22.8 - ~/.nvm/versions/node/v12.22.8/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v12.22.8/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v12.22.8/bin/npm
    Watchman: 2022.01.31.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 28, 29, 30, 31, 32
      Build Tools: 30.0.2, 30.0.3, 32.0.0, 32.1.0, 33.0.0
      System Images: android-25 | Google APIs Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-29 | Android TV Intel x86 Atom, android-29 | ARM 64 v8a, android-29 | Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs ARM 64 v8a, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play ARM 64 v8a, android-29 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64, android-30 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-31 | Intel x86 Atom_64, android-31 | Google APIs ARM 64 v8a, android-31 | Google APIs Intel x86 Atom_64, android-32 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8092744
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.4 => 0.66.4 
    react-native-macos: Not Found
  npmGlobalPackages:

### Steps to reproduce

Just running this code:

import {View, TouchableOpacity } from 'react-native';
  <View>
      <ActivityIndicator
        animating={true}
        style={{
          flex: 1,
          justifyContent: 'center',
          alignItems: 'center',
          height: 80
        }}
        color='#bc2b78'
        size="large" />
      <ActivityIndicator
        animating={true}
        color='red'
        size="large"
      />
      <ActivityIndicator
        color='blue'
        size="large"
      />
    </View>

### Snack, code example, screenshot, or link to a repository

<img width="296" alt="Screenshot 2022-03-15 at 18 04 18" src="https://user-images.githubusercontent.com/97094483/158442876-777537bf-10f8-4876-939d-0a20b0d8c353.png">

**Comment by haveneersrobin** [comment]
This is what is shown when animations are disabled: check under developer options that animations are not set to 'off'

![image](https://user-images.githubusercontent.com/7559898/158770441-f391ea17-5f3f-43ad-9d02-3f9c8010f49d.png)

**Comment by malik-coachhub** [comment]
Fixed, thank you
