### ISSUE TITLE
[Android] APK (release) working fine on emulator and device, published AAB in close testing fails. 

### ISSUE THREAD

**Issue by my-name-is-nheo** [facebook/react-native#33444]
### Description

Tried building the demo variant of my app in release mode. Dragged the file to the simulator (works), tested on a physical device (Pixel 6) working fine. But when I generate an app bundle, and publish it for close testing, the app fails to pass the login screen. (Google approved as well). Just wondering what could cause this sort of mix up. 

### Version

0.67.3

### Output of `npx react-native info`

System:
    OS: macOS 12.0
    CPU: (8) x64 Apple M1 Pro
    Memory: 34.02 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: Not Found
    npm: 8.1.4 - ~/.nvm/versions/node/v16.13.1/bin/npm
    Watchman: 2021.10.18.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7784292
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.10 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.2 => 17.0.2 
    react-native: ^0.67.3 => 0.67.3 

### Steps to reproduce

cd android && ./gradlew bundleRelease for app build builds. 

### Snack, code example, screenshot, or link to a repository

```
    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
         release {
            if (project.hasProperty('MYAPP_UPLOAD_STORE_FILE')) {
                storeFile file(MYAPP_UPLOAD_STORE_FILE)
                storePassword MYAPP_UPLOAD_STORE_PASSWORD
                keyAlias MYAPP_UPLOAD_KEY_ALIAS
                keyPassword MYAPP_UPLOAD_KEY_PASSWORD
            }
        }
    }
```

**Comment by cortinico** [comment]
> and publish it for close testing, the app fails to pass the login screen

Could you clarify what's the failure here?

**Comment by my-name-is-nheo** [comment]
Every component I written works when I build locally. On local the app is pointing to the right to env db, gcp authentication is working... etc, whenever I generate a signed APK and download it to the simulator or my physical device, it works as expected. However, every time i generate aab (appbundle) to upload to the google play store (for closed testing). liek 10% of my components fail (certain pickers, keyboard offset for certains screens are wrong) etc. How can I test if its my code or if its something that has to do with generated app bundle?
