### ISSUE TITLE
[Android] ScrollView jumps up/down the first time a large enough selectable Text is touched

### ISSUE THREAD

**Issue by artemiswkearney** [facebook/react-native#33440]
### Description

When a selectable `Text` component at least as tall as its containing ScrollView is touched for the first time, and is in a ScrollView but is not the only thing within its viewport, the scroll jumps so the text is the only thing within the viewport. This does not happen again for the same Text until it's rerendered by changing its `key`.

### Version

0.67.3 (originally observed on 0.64.1)

### Output of `npx react-native info`

```
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.22000
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
    Memory: 3.49 GB / 15.76 GB
  Binaries:
    Node: 17.7.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.5.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.10.31402.337 (Visual Studio Community 2019), 15.9.28307.1033 (Visual Studio Community 2017)
  Languages:
    Java: 1.8.0_282
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: ^0.67.3 => 0.67.3
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1. Render a ScrollView.
2. Render a `Text` element with the `selectable` prop set to true, and enough text to fill your device's screen, inside that ScrollView.
3. Add an element above or below the `Text` inside the `ScrollView`, or a `marginTop` or `marginBottom` value to the text.
4. Launch your app on an Android device.
5. Scroll so the text doesn't fill the screen.
6. Select the text, or tap on it without scrolling.
7. Observe that the scroll position jumped.

### Snack, code example, screenshot, or link to a repository

https://snack.expo.dev/TgWlz71JZ
Click the "Reset Bug" button to change the `Text`'s key, making the bug happen again the next time you touch the text.

**Comment by artemiswkearney** [comment]
May be related to #33419; the triggering circumstances seem similar.

**Comment by suwu150** [comment]
I have this problem too, is there a solution?

```
System:
    OS: macOS 12.2
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 29.38 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.14.0/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8139111
    Xcode: 13.3/13E113 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_291 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.3 => 0.67.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by artemiswkearney** [comment]
Still a problem

**Comment by kdotdot** [comment]
Same issue
