### ISSUE TITLE
Updated from 0.61.5 -> 0.67.4 & am encountering an issue with  @react-native/assets/registry

### ISSUE THREAD

**Issue by 0hio-creator** [facebook/react-native#33454]
### Description

error
 ```
Unable to resolve module @react-native/assets/registry from /Users/xx/Documents/tneapp/node_modules/react-native/Libraries/Image/resolveAssetSource.js

```

Line 15: of /Users/xx/Documents/tneapp/node_modules/react-native/Libraries/Image/resolveAssetSource.js
```
const AssetRegistry = require('@react-native/assets/registry');
```
Line 38 of  @react-native/assets/registry
```
module.exports = {registerAsset, getAssetByID};
```
Doesn't look like it is being exported?

### Version

0.67.4

### Output of `npx react-native info`

System:
    OS: macOS 10.15.7
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Memory: 377.96 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.16.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.11 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 28, 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2
      System Images: android-18 | Google APIs Intel x86 Atom, android-19 | Google APIs Intel x86 Atom, android-21 | Google APIs Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_232 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: ^7.0.3 => 7.0.3
    react: 17.0.2 => 17.0.2
    react-native: 0.67.4 => 0.67.4
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

I had a working version on 0.61.5 trying to follow the manual update to 0.67.4 when encountered the above error when running Android studio.

**Comment by developer-resources** [comment]
Unable to resolve module @react-native/assets/registry from /Users/xx/Documents/tneapp/node_modules/react-native/Libraries/Image/resolveAssetSource.js

**Comment by developer-resources** [comment]
+1

**Comment by kingsley9** [comment]
Having the same issue on react native 0.68.0

**Comment by 0hio-creator** [comment]
@kingsley9 I can't remember specifically if this was it. 
But the jdk needed to be updated. It wasn't mentioned in the manual update if i remember correctly. 

https://reactnative.dev/docs/environment-setup

**Comment by kingsley9** [comment]
> @kingsley9 I can't remember specifically if this was it. But the jdk needed to be updated. It wasn't mentioned in the manual update if i remember correctly.
> 
> https://reactnative.dev/docs/environment-setup

Could you elaborate a bit more if possible? My current JDK is v 17.0.2. 
Regarding the issue, I noticed that when I delete my node modules folder and run yarn or npm install the assets folder is installed correctly within @react-native so the compiler can find the registry.js file but literally after a few minutes I check the @react-native folder in node modules and the assets folder is missing again.

**Comment by 0hio-creator** [comment]
@kingsley9 Check your android studio compatibility. But i believe jdk 11 is the default.
 
https://github.com/facebook/react-native/issues/32948
This thread might help
