### ISSUE TITLE
pod install fails (not M1) — 401 when installing Boost

### ISSUE THREAD

**Issue by Tycholiz** [facebook/react-native#33462]
### Description

Following the [docs](https://reactnative.dev/docs/environment-setup), I'm initializing a new react-native with Typescript repo with the command
```
npx react-native init myproject --template react-native-template-typescript
```

Upon running that command, I get the following:
```
✔ Downloading template
✔ Copying template
✔ Processing template
✖ Installing CocoaPods dependencies (this may take a few minutes)
✖ Installing CocoaPods dependencies (this may take a few minutes)
error Error: Failed to install CocoaPods dependencies for iOS project, which is required by this template.
Please try again manually: "cd ./myproject/ios && pod install".
```

So I `cd` into the `ios/` directory and run `pod install`. Everything installs propery, but when I get to boost...
```
Installing boost (1.76.0)

[!] Error installing boost
[!] /usr/bin/curl -f -L -o /var/folders/55/_ncpv5xd2hj2q2_k5m2bmn6r0000gn/T/d20220321-2395-th53eu/file.tbz https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.bz2 --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.11.3 cocoapods-downloader/1.5.1'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0    80    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 401
```

I understand that it's the request to `jfrog.io` that's giving me the 401, but how do I get around this? I'm not even clear on why access to this package would be forbidden in the first place. Strangely, I can install the tar.bz2 file directly just by putting that URL into my address bar. Why would it return a 401 to cURL?

I'm a web developer so I'm used to the npm ecosystem and have never faced a 401 before.

What can I do to move past this?

### Version

0.67.4

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 12.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 294.95 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.19.1 - /usr/local/opt/node@14/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 6.14.16 - /usr/local/opt/node@14/bin/npm
    Watchman: 2021.10.18.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.3
      System Images: android-26 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: 12.0/12A7209 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_252 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.67.4 => 0.67.4
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. run npx react-native init myproject --template react-native-template-typescript
2. cd into `ios`
3. run `pod install`

**Comment by Tycholiz** [comment]
I found a workaround, though admittedly it's pretty lame and is no better than a bandaid solution. The approach is to download the file and then source it from the local filesystem, rather than making a network call:

1. Download the `tar.bz2` file from `https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.bz2`
2. move the (compressed) file to `node_modules/react-native/third-party-podspecs`
3. open `node_modules/react-native/third-party-podspecs/boost.podspec`
4. change the `spec.source` key to
```
spec.source = { :http => 'file:' + __dir__ + '/boost_1_76_0.tar.bz2',
                :sha256 => 'f0397ba6e982c4450f27bf32a2a83292aba035b827a5623a14636ea583318c41' }
```
5. run `pod install`

note: you may need to adjust the version of the boost package your project specifies.

**Comment by khokanuzzman** [comment]
try 
git config --global core.autocrlf false
brew install cocoapods

**Comment by rushi-b-vachhani** [comment]
@Tycholiz Have you got the solution? Actually, I got the same error but I am using Mac with M1 chip.

**Comment by Tycholiz** [comment]
No solution yet unfortunately. With my workaround above I haven't ran into the issue since. I expect it will poke its head soon though.

**Comment by Tycholiz** [comment]
bump on this issue

Tried to initialize a new project today and got the 401 again, this time on OpenSSL package.

**Comment by rushi-b-vachhani** [comment]
@Tycholiz I resolved my issue with command:
`pod repo update`

**Comment by Tycholiz** [comment]
No luck, still getting error:
```
[!] Error installing OpenSSL-Universal
[!] /usr/bin/curl -f -L -o /var/folders/55/_ncpv5xd2hj2q2_k5m2bmn6r0000gn/T/d20220415-48164-teg9l8/file.zip https://github.com/krzyzanowskim/OpenSSL/archive/1.1.1100.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.11.3 cocoapods-downloader/1.5.1'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 401
```

I also get the following error when running the initial `yarn install`
```
error An unexpected error occurred: "https://registry.yarnpkg.com/react-native-template-react-native-template-typescript: Not found".
info If you think this is a bug, please open a bug report with the information provided in "/Users/kyletycholiz/programming/projects/never-forget-rn/MyApp/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
yarn remove v1.22.18
[1/2] 🗑  Removing module react-native-template-react-native-template-typescript...
error This module isn't specified in a package.json file.
info Visit https://yarnpkg.com/en/docs/cli/remove for documentation about this command.
warn Failed to clean up template temp files in node_modules/react-native-template-react-native-template-typescript. This is not a critical error, you can work on your app.
```

Although as noted, it's not a critical error. 

Nonetheless I don't understand why any of these issues would be happening for only some people but not all.

**Comment by kei4eva4** [comment]
@Tycholiz I resolved this issue by removing the following line from ~/.netrc.

```
machine github.com
  login xxxxx
  password xxxxxx
````

**Comment by ghasemikasra39** [comment]
Updating cocoapods via `sudo gem install cocoapods` fixed this issue.

**Comment by mutablestudio** [comment]
still happening

**Comment by mariogruizdiaz** [comment]
> 

I am having the same error. @Tycholiz did you fix it?

**Comment by Tycholiz** [comment]
I did not. The workaround I posted above was sufficient to move past

**Comment by URvesh109** [comment]
1. open node_modules/react-native/third-party-podspecs/boost.podspec

Replaced

spec.source = { :http => 'https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.bz2',
                  :sha256 => 'f0397ba6e982c4450f27bf32a2a83292aba035b827a5623a14636ea583318c41' }
                  
                  with
                  
spec.source = { :http => 'https://sourceforge.net/projects/boost/files/boost/1.76.0/boost_1_76_0.tar.bz2'}

**Comment by Tycholiz** [comment]
I'm pretty sure this issue is related to something at the network level. I'm not sure what my exact setup was at the time, but see if you are on a VPN. Maybe even try a different wifi network to see if the result changes.

It's quite a strange issue and I'm not exactly sure what to think about it

**Comment by URvesh109** [comment]
@Tycholiz true it is strange issue
Now below link is also working
https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.bz2

Morning I was facing could not resolve host
<img width="1330" alt="boost" src="https://user-images.githubusercontent.com/26654227/179825417-9ee68eda-7bb4-4dce-9c04-effc9b524ecf.png">

**Comment by saadgulofficial** [comment]
> I found a workaround, though admittedly it's pretty lame and is no better than a bandaid solution. The approach is to download the file and then source it from the local filesystem, rather than making a network call:
> 
> 1. Download the **tar.bz2** file from `https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.bz2`
> 2. move the (compressed) file to `node_modules/react-native/third-party-podspecs`
> 3. open `node_modules/react-native/third-party-podspecs/boost.podspec`
> 4. change the `:http` part of the `spec.source` key to:
> 
> ```
> :http => 'file:' + __dir__ + '/boost_1_76_0.tar.bz2'
> ```
> 
> 5. run `pod install`
> 
> note: you may need to adjust the version of the boost package your project specifies.

Thanks

**Comment by toby-lei** [comment]
> I found a workaround, though admittedly it's pretty lame and is no better than a bandaid solution. The approach is to download the file and then source it from the local filesystem, rather than making a network call:
> 
> 1. Download the **tar.bz2** file from `https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.bz2`
> 2. move the (compressed) file to `node_modules/react-native/third-party-podspecs`
> 3. open `node_modules/react-native/third-party-podspecs/boost.podspec`
> 4. change the `:http` part of the `spec.source` key to:
> 
> ```
> :http => 'file:' + __dir__ + '/boost_1_76_0.tar.bz2'
> ```
> 
> 5. run `pod install`
> 
> note: you may need to adjust the version of the boost package your project specifies.

It works for me

**Comment by crackerack** [comment]
I am still seing this issue. Is there anything besides the workaround? A lot of people seem to have reported this.

**Comment by glhrmoura** [comment]
Work for me:

```
rm -rf ~/Library/Caches/CocoaPods
rm -rf Pods
rm -rf ~/Library/Developer/Xcode/DerivedData/*
pod deintegrate
pod setup
pod install
```

**Comment by glhrmoura** [comment]
Worked for me:

```
rm -rf ~/Library/Caches/CocoaPods
rm -rf Pods
rm -rf ~/Library/Developer/Xcode/DerivedData/*
pod deintegrate
pod setup
pod install
```

**Comment by williamgurzoni** [comment]
What worked for me was just waiting the download... The link was downloading on an average of 25KB/s.
After waiting for a loooong time it worked.

**Comment by runtimeterror1997** [comment]
> Worked for me:
> 
> ```
> rm -rf ~/Library/Caches/CocoaPods
> rm -rf Pods
> rm -rf ~/Library/Developer/Xcode/DerivedData/*
> pod deintegrate
> pod setup
> pod install
> ```

This worked for me. Thank you

**Comment by msahin35** [comment]
For workaround solution. You don't need to download the tar.bz2. And move to node_modules/react-native/third-party-podspecs.
Only change line
  spec.source = { :http => 'https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.bz2',
                  :sha256 => 'f0397ba6e982c4450f27bf32a2a83292aba035b827a5623a14636ea583318c41' }
to 
  spec.source = { :http => 'https://sourceforge.net/projects/boost/files/boost/1.76.0/boost_1_76_0.tar.bz2',
                  :sha256 => 'f0397ba6e982c4450f27bf32a2a83292aba035b827a5623a14636ea583318c41' }
in file node_modules/react-native/third-party-podspecs/boost.podspec

i think jfrog close their server. You may need to change 76 if you use another version

**Comment by built-by-as** [comment]
> @Tycholiz I resolved this issue by removing the following line from ~/.netrc.
> 
> ```
> machine github.com
>   login xxxxx
>   password xxxxxx
> ```

this worked for me

**Comment by vladanyes** [comment]
Connecting to another wifi(iPhone hotspot) solved the issue for me.

**Comment by react06** [comment]
hit the same command `pod install` after failing works for me, might be network issue.

**Comment by ricardodolnl** [comment]
I tried to run the curl command itself (`/usr/bin/curl -f -L -o ...` and i noticed that that command only works if the `-f` option is removed. Only than it'll use the .netrc file the way it should. But i don't know how to fix this of pod install.

**Comment by arunsa-hrbl** [comment]
> For workaround solution. You don't need to download the tar.bz2. And move to node_modules/react-native/third-party-podspecs. Only change line spec.source = { :http => 'https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.bz2', :sha256 => 'f0397ba6e982c4450f27bf32a2a83292aba035b827a5623a14636ea583318c41' } to spec.source = { :http => 'https://sourceforge.net/projects/boost/files/boost/1.76.0/boost_1_76_0.tar.bz2', :sha256 => 'f0397ba6e982c4450f27bf32a2a83292aba035b827a5623a14636ea583318c41' } in file node_modules/react-native/third-party-podspecs/boost.podspec
> 
> i think jfrog close their server. You may need to change 76 if you use another version

This is really worked for me. Thanks a lot :)

**Comment by mvn-sonnguyen3-hn** [comment]
> 1. open node_modules/react-native/third-party-podspecs/boost.podspec
> 
> Replaced
> 
> spec.source = { :http => 'https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.bz2', :sha256 => 'f0397ba6e982c4450f27bf32a2a83292aba035b827a5623a14636ea583318c41' }
> 
> ```
>               with
> ```
> 
> spec.source = { :http => '[https://sourceforge.net/projects/boost/files/boost/1.76.0/boost_1_76_0.tar.bz2'}](https://sourceforge.net/projects/boost/files/boost/1.76.0/boost_1_76_0.tar.bz2'%7D)

oh thank you, It's work for me.

**Comment by Adnan-Bacic** [comment]
running `pod deintegrate` as some people have suggested, deletes quite a few lines of code in `ios/projectName.xcodeproj/project.pbxproj` file.

is this okay?

either way, this solution sadly didnt work for me.

manually editing `node_modules/` would only work locally, and would still fail on CI builds.

is this a widespread problem people have?

**Comment by aleena-adnan1** [comment]
did you find out any work around @Adnan-Bacic  ?

**Comment by Adnan-Bacic** [comment]
@aleena-adnan1 as someone else suggested, i just waited. it takes a very long time. i honestly didnt look at the time but i guess it was at least 30 min, if not 60+

**Comment by Kawaljeet-AUI** [comment]
@Adnan-Bacic Despite waiting, did it work or no?

**Comment by Adnan-Bacic** [comment]
> @Adnan-Bacic Despite waiting, did it work or no?
> 

Yes it worked

**Comment by dohooo** [comment]
> @Tycholiz I resolved this issue by removing the following line from ~/.netrc.
> 
> ```
> machine github.com
>   login xxxxx
>   password xxxxxx
> ```

It works for me!!!!

**Comment by cairocampos** [comment]
Updating cocoapods via sudo gem install cocoapods fixed this issue.

**Comment by sathiyaraj45** [comment]
/usr/bin/tar xf /var/folders/_y/1jlgk27j6xz72bwmny4f2_cw0000gq/T/d20230915-6496-r9jxag/file.tbz -C /var/folders/_y/1jlgk27j6xz72bwmny4f2_cw0000gq/T/d20230915-6496-r9jxag

tar: Error opening archive: Unrecognized archive format

**Comment by sathiyaraj45** [comment]
@cairocampos we updated sudo command and manual steps also we are getting the below error

/usr/bin/tar xf /var/folders/_y/1jlgk27j6xz72bwmny4f2_cw0000gq/T/d20230915-6496-r9jxag/file.tbz -C /var/folders/_y/1jlgk27j6xz72bwmny4f2_cw0000gq/T/d20230915-6496-r9jxag

tar: Error opening archive: Unrecognized archive format

**Comment by tamdvyounetgroup** [comment]
> oh thank you, It's work for me.

**Comment by Roka20012** [comment]
Maybe it would be ridiculous but switching from WiFi to LTE makes it load in 2 minutes, WiFi it showed me like >2 hours btw my wifi is faster than LTE)

**Comment by TarifEzaz** [comment]
The build process stopped with errors the first time when I ran the command --platform ios --lcal once. But after running the command for the second time, boost installing took about 20 minutes and finally the build was successfully made.

**Comment by lalitshahi** [comment]
> Worked for me:
> 
> ```
> rm -rf ~/Library/Caches/CocoaPods
> rm -rf Pods
> rm -rf ~/Library/Developer/Xcode/DerivedData/*
> pod deintegrate
> pod setup
> pod install
> ```

This Worked for me as well.

**Comment by mehdiChibani** [comment]
> 1. open node_modules/react-native/third-party-podspecs/boost.podspec
> 
> Replaced
> 
> spec.source = { :http => 'https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.bz2', :sha256 => 'f0397ba6e982c4450f27bf32a2a83292aba035b827a5623a14636ea583318c41' }
> 
> ```
>               with
> ```
> 
> spec.source = { :http => '[https://sourceforge.net/projects/boost/files/boost/1.76.0/boost_1_76_0.tar.bz2'}](https://sourceforge.net/projects/boost/files/boost/1.76.0/boost_1_76_0.tar.bz2'%7D)

this solution saved my project 🥹

**Comment by hotrungnhan** [comment]
This not event fix yet.

**Comment by Oladapodaniel** [comment]
> Updating cocoapods via `sudo gem install cocoapods` fixed this issue.

Updating cocoapods with this helped me.

**Comment by AwolDes** [comment]
If you find yourself here on `react-native` `v0.69.4` like I did, getting this error:

```
Installing boost (1.76.0)
[!] Error installing boost
Verification checksum was incorrect, expected f0397ba6e982c4450f27bf32a2a83292aba035b827a5623a14636ea583318c41, got 79e6d3f986444e5a80afbeccdaf2d1c1cf964baa8d766d20859d653a16c39848
```

You will need to apply a patch to the package like so
```diff
diff --git a/node_modules/react-native/third-party-podspecs/boost.podspec b/node_modules/react-native/third-party-podspecs/boost.podspec
index 2f1fcc4..2377c4e 100644
--- a/node_modules/react-native/third-party-podspecs/boost.podspec
+++ b/node_modules/react-native/third-party-podspecs/boost.podspec
@@ -10,7 +10,7 @@ Pod::Spec.new do |spec|
   spec.homepage = 'http://www.boost.org'
   spec.summary = 'Boost provides free peer-reviewed portable C++ source libraries.'
   spec.authors = 'Rene Rivera'
-  spec.source = { :http => 'https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.bz2',
+  spec.source = { :http => 'https://sourceforge.net/projects/boost/files/boost/1.76.0/boost_1_76_0.tar.bz2',
                   :sha256 => 'f0397ba6e982c4450f27bf32a2a83292aba035b827a5623a14636ea583318c41' }
 
   # Pinning to the same version as React.podspec.
```

jfrog is now a paid service, which I verified running these commands:

```
» curl -O https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.bz2
file 
» file boost_1_76_0.tar.bz2                              
boost_1_76_0.tar.bz2: HTML document text, ASCII text, with CRLF line terminators
» cat boost_1_76_0.tar.bz2                                   
<html>
<head><title>302 Found</title></head>
<body>
<center><h1>302 Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by surajramayadav** [comment]
I encountered the same issue with React Native version 0.68.2 and managed to resolve it temporarily by following the suggestion below. Navigate to the boost.podspec file and replace the link from:

'https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.bz2'
to

'https://archives.boost.io/release/1.76.0/source/boost_1_76_0.tar.bz2'
This adjustment helped me address the problem for now.

**Comment by livingston12** [comment]
Going to node_modules/react-native/third-party-podspecs/boost.podspec

change 
'[](https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.bz2)'
To
http => '[](https://sourceforge.net/projects/boost/files/boost/1.76.0/boost_1_76_0.tar.bz2'),

**Comment by Samama-Zargham** [comment]
1. **Go to node_modules/react-native/third-party-podspecs from the root of your project
2. check the boost.podspec file**

See this line  **spec.source = { :http => 'https://boostorg.jfrog.io/artifactory/main/release/1.83.0/source/boost_1_83_0.tar.bz2',
                  :sha256 => '6478edfe2f3305127cffe8caf73ea0176c53769f4bf1585be237eb30798c3b8e' }**

only change this url **https://boostorg.jfrog.io/artifactory/main/release/1.83.0/source/boost_1_83_0.tar.bz2**
 to this 
**https://sourceforge.net/projects/boost/files/boost/1.83.0/boost_1_83_0.tar.bz2**

**and than make patch by installing 
patch-package postinstall-postinstall 
Run this Comand to create patch 
npx patch-package react-native**

and now BOOM😃 install pods by running
cd ios pod install
