### ISSUE TITLE
[Windows] Testing master on Windows 10

### ISSUE THREAD

**Issue by ide** [facebook/react-native#3348]
Could someone with Windows 10 try checking out master and seeing what works or doesn't work? Things to test:

- Make sure you have Node 4
- Does the CLI tool work?
 - Check out react-native
 - Modify https://github.com/facebook/react-native/blob/master/react-native-cli/index.js#L180 to install `facebook/react-native` instead of `react-native`
 - Install your copy of the CLI: `npm remove -g react-native-cli; npm i -g .\react-native-cli`
 - Run the CLI: `react-native init Test`
- Does the packager work?
 - From your new Test project directory, run `node node_modules\react-native\packager\packager.js`
 - It should start serving the sample app from http://localhost:8081/index.android.bundleplatform=android&?dev=true
- Does Android work?
 - This will be hard to test since there might be issues with building ReactAndroid from source. If you can get it to work, great, otherwise we'll look at finishing basic Windows support between the RC and final release.
 - Need to build ReactAndroid 0.13
 - Then build the sample Android app

**Comment by icyflash** [comment]
Win10 64bit
1. CLI work
2. Packager work

    it should be: http://localhost:8081/index.android.bundle?platform=android&dev=true
3. 

![error](https://cloud.githubusercontent.com/assets/578257/10422339/7649ed32-70eb-11e5-8a72-4f290ec53274.png)

**Comment by ide** [comment]
@icyflash thanks! When we publish the 0.13-rc JAR file I'll post an update here so you can test the last step again. Really helpful :)

**Comment by peduxe** [comment]
@icyflash I had the same error on rn 0.11.4 are you sure your app is using the right dependencies? Check build.gradle.

**Comment by yeso126** [comment]
Mine says:
    unable to download JS Bundle, did you forget to start the development server or connect your device? 
Then try to manually initiate it and get the following error: 

react-native start
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn sh ENOENT
    at exports._errnoException (util.js:874:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:439:9)
    at process._tickCallback (node.js:353:17)
    at Function.Module.runMain (module.js:469:11)
    at startup (node.js:134:18)
    at node.js:961:3

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/windows-testing-master-on-windows-10

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.
