### ISSUE TITLE
Javascript host environment documentation

### ISSUE THREAD

**Issue by aackerman** [facebook/react-native#335]
What I was lost on earliest attempting to get started with react-native was understanding the host environment. It's not Node, it's not a browser, it appears to be a raw VM context, with a whole bunch of polyfills. When I tried to require Bluebird, I ran into errors, likely due to assumptions made about APIs provided by the host environment.

Also, it would be important to know how third-party libs can run tests in the same type of environment to fix these issues.

Thanks.

**Comment by jaygarcia** [comment]
I agree that there could be some better documentation around this.   For example, the "light" implementation of the CommonJS module system, should be documented, if it's not already. 

(stuff is moving so quickly, it's hard for me to keep track of it all)

**Comment by daviskoh** [comment]
+1

**Comment by sahrens** [comment]
We always need more docs!

For testing in the full environment, check out the "Testing" section of the documentation - we have a harness for integration testing that should help you do what you want.

**Comment by amasad** [comment]
@aackerman can you list the issues you ran into by trying to use Bluebird? Maybe we can fix those quickly.

**Comment by aackerman** [comment]
I can give more detailed info about the issue with bluebird later tonight, but in the mean time, having installed bluebird with `npm install bluebird` and `var Promise = require('bluebird');` in `index.ios.js` will throw and error.

**Comment by vjeux** [comment]
Can you give the exact error?

Also note that there's a Promise global already existing in React Native

**Comment by aackerman** [comment]
It looks like a clear issue with bluebird from what I can tell. 

![screen shot 2015-03-27 at 18 21 29](https://cloud.githubusercontent.com/assets/786640/6878566/6408da2c-d4ae-11e4-94a3-4cff63fdae8c.png)
![screen shot 2015-03-27 at 18 21 57](https://cloud.githubusercontent.com/assets/786640/6878568/696d7c0c-d4ae-11e4-81ca-295af6876e2c.png)

The [block in `bluebird`](https://github.com/petkaantonov/bluebird/blob/master/src/schedule.js#L22) looks like this.

```
} else if (typeof MutationObserver !== "undefined") {
    schedule = function(fn) {
        var div = document.createElement("div");
        var observer = new MutationObserver(fn);
        observer.observe(div, {attributes: true});
        return function() { div.classList.toggle("foo"); };
    };
    schedule.isStatic = true;
} else if (typeof setTimeout !== "undefined") {
```

It's clearly throwing an error because the DOM is not available, but it's interesting that `MutationObserver` is available, otherwise it could not have made it into the block. The authors of `bluebird` probably didn't expect to be running in an environment that is neither `node` nor the browser.

@vjeux as you said a Promise implementation does exist already, and what I really wanted just simply `fetch`, so the `bluebird` issue is completely secondary to understanding the host environment.

I'll make a ticket on the `bluebird` repo to let them know about this particular issue, but at this point I don't think it needs to be a priority for anybody.

**Comment by vjeux** [comment]
Yeah, all those feature detection needs to be carefully considered when running in a different environment. The implementation of Promise that we have is using setImmediate that has been implemented to run before we hand back the process to obj-c

**Comment by vjeux** [comment]
By the way, fetch is there by default. It has a much nicer api than xhr :)

**Comment by petkaantonov** [comment]
`MutationObserver` is supposed to observe DOM elements, it doesn't make sense to expose one without the other. Also, there is not a single mention of MutationObserver in this entire repo so I am not sure how I would even fix it - what am I supposed to observe with it?

**Comment by vjeux** [comment]
This is where we mangle with the global environment. We should probably do `delete GLOBAL.MutationObserver;` (if we can). 
https://github.com/facebook/react-native/blob/master/Libraries/JavaScriptAppEngine/Initialization/InitializeJavaScriptAppEngine.js#L117

One issue if we do this is that it's now going to use setTimeout(0), which is going to do a round trip to native for every single call. Since when you are using promises, you tend to chain a lot of then, it's going to be much slower than needed. It really needs to use setImmediate.

**Comment by petkaantonov** [comment]
I can add setImmediate check after the MutationObserver check, np :)

**Comment by vjeux** [comment]
Okay perfect. I'm trying to remove MutationObserver right now, I'll report back in 2 minutes

**Comment by vjeux** [comment]
Bingo, it's working, it now falls through the setTimeout check. I'm sending an internal diff, it'll be updated in the next version.

**Comment by petkaantonov** [comment]
setImmediate check published in 2.9.16

**Comment by vjeux** [comment]
That was fast ;)

**Comment by petkaantonov** [comment]
yea the upside of lone cowboy projects :p

**Comment by vjeux** [comment]
Since I got you, I'd like to get your opinion on 
https://github.com/facebook/react-native/blob/master/Libraries/vendor/core/ES6Promise.js

This is the promise implementation that we're providing. Do you think it makes sense to use bluebird by default?

**Comment by petkaantonov** [comment]
Well I don't personally find the pure ES6 api enough for application development, I find stuff like `.finally`, predicated catches, long stack traces, unhandled rejection reporting  etc essential. Also in 3.0 bluebird debuggability is going to be turbo boosted by warnings that non-seasoned promise users commonly make, e.g. https://twitter.com/PetkaAntonov/status/565899315613540352

**Comment by vjeux** [comment]
Yeah, at Facebook we use a slightly improved version of Promises with .finally and .done

https://github.com/facebook/react-native/blob/master/Libraries/vendor/core/Promise.js#L42

Don't have the rest though. I'll poll people internally and see what they think.

**Comment by aackerman** [comment]
The warnings about uncaught promise rejections are the number 1 reason to use bluebird over the specced ES6 promises. Trying to find silently swallowed errors is developer hell.

**Comment by aackerman** [comment]
If I was intent on finding out more about the JS host environment is [here](https://github.com/facebook/react-native/tree/master/Libraries/JavaScriptAppEngine) the best place to look?

**Comment by vjeux** [comment]
This file is:
https://github.com/facebook/react-native/blob/master/Libraries/JavaScriptAppEngine/Initialization/InitializeJavaScriptAppEngine.js

**Comment by aackerman** [comment]
Awesome thanks, I'll do some reading and see if I can distill some of the information.

**Comment by petkaantonov** [comment]
btw I checked the finally implementation - just a note that `.finally` in bluebird doesn't behave like `.then(cb, cb);` instead it behaves like [this](https://github.com/domenic/promises-unwrapping/issues/18#issue-18889502)

**Comment by benjamingr** [comment]
@vjeux I think you really want to have long stack traces, unhandled rejection detection and better aggregation methods in your promises. You can always just use a special build of bluebird.

Facebook already has groups using bluebird internally (namely WhatsApp Web), I think having a robust promise implementation would be really nice for react native. (That said, things like a TableView would matter a lot more to me as a user :P)

**Comment by benjamingr** [comment]
@petkaantonov well, the general idea is to get the wins from bluebird like long stack traces and more debuggable and faster promises in react-native I think.

**Comment by petkaantonov** [comment]
Those are not compliant with es6- spec

**Comment by benjamingr** [comment]
So what? React is not world renowned for sticking to strict ES6 it's known for making pragmatic choices in order to make developer life easier. Adding long stack traces and enabling debuggable promises would be a huge deal.

**Comment by vjeux** [comment]
React native environment should look like the browser / node. By putting non standard primitives as global we would break all the existing code out there. This would be bad for the entire ecosystem.

In this case, people can just npm install bluebird to get all those non standard behavior if they want to

**Comment by brentvatne** [comment]
I believe that this is covered in this doc now: https://facebook.github.io/react-native/docs/javascript-environment.html#content
