### ISSUE TITLE
Build error when following steps in documentation for buidling from source

### ISSUE THREAD

**Issue by dyonende** [facebook/react-native#33503]
### Description

I followed all the steps from [the documentation](https://reactnative.dev/docs/environment-setup) for setting up my environment and had no problems here.
Then I carried out the instructions from the [Building from source](https://github.com/facebook/react-native/wiki/Building-from-source) for Android, but when I try to build an app I get the following error:

```
Build file '\MyTestApp\node_modules\react-native\ReactAndroid\build.gradle' line: 11

Plugin [id: 'org.jetbrains.kotlin.android'] was not found in any of the following sources:

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.plugins.UnknownPluginException: Plugin [id: 'org.jetbrains.kotlin.android'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Included Builds (None of the included builds contain this plugin)
- Plugin Repositories (plugin dependency must include a version number for this source)
```
I applied all the steps to the init MyTestApp.
I am aware of others who also encoutered the same error when following the documentation,
 so I suspect that the documentation for building from source might be outdated, but I'm not sure.

### Version

0.67.4

### Output of `npx react-native info`

```
System:
    OS: Windows 10 10.0.22000
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 5.55 GB / 15.84 GB
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.5.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      Android NDK: 21.4.7075529
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version     2021.1.0.0 AI-211.7628.21.2111.8193401
    Visual Studio: Not Found
  Languages:
    Java: 11.0.13
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.67.4 => 1000.0.0
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

The output says Windows 10, but I am using Windows 11.

### Steps to reproduce

First I set up my environment according to [the environment setup documentation](https://reactnative.dev/docs/environment-setup).
Then I created a test app with `npx react-native init MyTestApp`
I carried out all the step from [Building from source](https://github.com/facebook/react-native/wiki/Building-from-source).
At the [Building from Android Studio](https://github.com/facebook/react-native/wiki/Building-from-source#building-from-android-studio) step I get the error in Android Studio.

**Comment by Capsar** [comment]
Encountered the same error as above but build on actual Windows 10.
