### ISSUE TITLE
The minCompileSdk (31) specified in a dependency's AAR metadata

### ISSUE THREAD

**Issue by oguzhan10** [facebook/react-native#33501]
### Description

Hello, I am using version shown below. I need to downgrade sdkversion to 29 to run in my mobile phone, because it crashes when I install apk. When I changed sdk version to 29, and run gradlew assembleRelease It gives me below error.

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkReleaseAarMetadata'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
   > The minCompileSdk (31) specified in a
     dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
     is greater than this module's compileSdkVersion (android-29).
     Dependency: androidx.work:work-runtime:2.7.1.
     AAR metadata file: C:\Users\.gradle\caches\transforms-3\065a2447fd4e6c84e24a7e1c451d413f\transformed\work-runtime-2.7.1\META-INF\com\android\build\gradle\aar-metadata.properties.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.2/userguide/command_line_interface.html#sec:command_line_warnings

Execution optimizations have been disabled for 1 invalid unit(s) of work during this build to ensure correctness.
Please consult deprecation warnings for more details.

BU¦LD FAILED in 2m 26s
```

```
buildscript {
    ext {
        buildToolsVersion = "30.0.2"
        minSdkVersion = 29
        compileSdkVersion = 29
        targetSdkVersion = 29
        ndkVersion = "21.4.7075529"
    }

```
```
    "@notifee/react-native": "^5.0.0",
    "@react-navigation/native": "^6.0.8",
    "@react-navigation/stack": "^6.1.1",
    "native-base": "^2.15.2",
    "react": "17.0.2",
    "react-native": "^0.67.4",
    "react-native-gesture-handler": "^2.3.2",
    "react-native-paper": "^4.11.2",
    "react-native-reanimated": "^2.3.0",
    "react-native-safe-area-context": "^4.2.2",
    "react-native-screens": "^3.13.1",
    "react-native-vector-icons": "^9.1.0",
    "reanimated-bottom-sheet": "^1.0.0-alpha.22"
```

### Version

^0.67.4

### Output of `npx react-native info`

System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz 
    Memory: 16.76 GB / 31.82 GB
  Binaries:
    Node: 15.2.0 - C:\Program Files\nodejs\node.EXE        
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.9 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 23, 26, 28, 29, 30, 31
      Build Tools: 26.0.3, 28.0.3, 29.0.2, 30.0.0, 30.0.1, 30.0.2, 30.0.3, 31.0.0
      System Images: android-23 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom_64, android-30 | Google Play Intel x86 Atom, android-31 | ARM 64 v8a, android-31 | Intel x86 Atom_64
      Android NDK: 22.0.7026061
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.11.31702.278 (Visual Studio Community 2019)
  Languages:
    Java: 17.0.1 - C:\Program Files\Common Files\Oracle\Java\javapath\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: ^0.67.4 => 0.67.4
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

gradlew assembleRelease

**Comment by cortinico** [comment]
You (or one of your dependency) is using `work-runtime-2.7.1` from the Work Manager: https://developer.android.com/jetpack/androidx/releases/work which has a `minCompileSdk` to 31

You should either:
1. Bump your `minCompileSdk` to 31
2. Remove that dependency, use an older version of it or ask the maintainer to downgrade the WorkManager version.

As an alternative you could force a version of WorkManager to a older one, but that's not recommended.

Closing as this is not related to React Native but to another dependency.

**Comment by oguzhan10** [comment]
How can I find which dependency using work-runtime-2.7.1. Because app crash during installation apk. I know I need to write 31. But I need to downgrade to 29 and I have less knowledge about it. Because it I am writing here. @cortinico

**Comment by cortinico** [comment]
You can find it by doing so:

```
cd android && ./gradlew :app:dependencies
```

Post the output here.

**Comment by alexander01202** [comment]
@cortinico Please I am using expo managed workflow and I want to build it but I keep getting the same error. How do I find the dependency that is using this?? And what do I do to fix it? Thank you!!!
