### ISSUE TITLE
com.facebook.react.modules.core.ExceptionsManagerModule.reportException ExceptionsManagerModule.java, line 83

### ISSUE THREAD

**Issue by anasalsaadi14** [facebook/react-native#33514]
### Description

**com.facebook.react.common.JavascriptException: TypeError: n is not a function. (In 'n()', 'n' is an instance of _) This error is located at: in Unknown in Unknown in ForwardRef in Unknown in ForwardRef in H in RCTView in View in c in RCTView in View in Portal.Host in E in U in n in RCTView in View in React Native example in A in l in c in L in RCTView in View in RCTView in View in C**

i am facing this issue in app after publish new version without upgrade or update react native version ! 

i received this exception in google play  and firebase Crashlytics dashboard

![screencapture-console-firebase-google-u-1-project-soukare-9fe4b-crashlytics-app-android-com-soukare-issues-004ae19e3c0d47d5dde33c4761529798-2022-03-29-09_56_24](https://user-images.githubusercontent.com/55756222/160544147-127f9102-728b-4b2b-8e94-e32414edd2c0.png)

    "react": "16.13.1",
    "react-native": "0.63.3",

any solutions?
 

### Version

0.63.3

### Output of `npx react-native info`

attached in image

### Steps to reproduce

new install

**Comment by shatas** [comment]
any news on this? Seeing similar stuff in our app.

**Comment by govarthananve** [comment]
Any update on this? We also facing same issue
