### ISSUE TITLE
![image](https://user-images.githubusercontent.com/29938227/130439198-2ef3bb0e-8cf3-4d85-b612-bf891180059e.png)

### ISSUE THREAD

**Issue by vr0707** [facebook/react-native#33516]
![image](https://user-images.githubusercontent.com/29938227/130439198-2ef3bb0e-8cf3-4d85-b612-bf891180059e.png)

_Originally posted by @KingAmo in https://github.com/facebook/react-native/issues/32070#issuecomment-903677554_

**Comment by safaiyeh** [comment]
No need to have a new issue open for this, can continue in #32070
