### ISSUE TITLE
[Andriod]  ScrollView showsHorizontalScrollIndicator={false} does not work

### ISSUE THREAD

**Issue by timzaak** [facebook/react-native#3352]
however, showsVerticalScrollIndicator={false} works well

**Comment by ehourigan** [comment]
:+1:

**Comment by ehourigan** [comment]
:+1: 

The following function is exposed within ReactScrollViewManager.java
  @ReactProp(name = "showsHorizontalScrollIndicator")
  public void setShowsHorizontalScrollIndicator(ReactScrollView view, boolean value) {
    view.setHorizontalScrollBarEnabled(value);
  }

However it is not exposed inside ReactHorizontalScrollViewManager.java
should the two implementations match?

**Comment by ide** [comment]
Fixed in https://github.com/facebook/react-native/commit/e6ad91b5a218bec73a10a9064e9178235b12c557

**Comment by ehourigan** [comment]
@ide Thanks!
