### ISSUE TITLE
Perf monitor seem isn't working on android 

### ISSUE THREAD

**Issue by iamvucms** [facebook/react-native#33524]
### Description

Perf monitor seem isn't working on android. Actually I did stress test to make app laggy but fps still showing 61 here. Also it's making app become crash after restarting app with showing perf monitor
<img width="557" alt="image" src="https://user-images.githubusercontent.com/17398401/160900457-89623041-3c97-429a-8913-6b3b6613bd3b.png">

### Version

0.68.0

### Output of `npx react-native info`

System:
    OS: macOS 11.2.3
    CPU: (12) x64 Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
    Memory: 434.71 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.3.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.3.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8139111
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.68.0 => 0.68.0
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Step 1: react-native run-android
Step 2: enable showing perf monitor
Step 3: restarting app

**Comment by hannojg** [comment]
For me the crash happens explicitly when enabling newArch
