### ISSUE TITLE
[Android] Setting TextInput "selection" via setNativeProps creates cursor jump after invoked once

### ISSUE THREAD

**Issue by avishain** [facebook/react-native#33520]
### Description

If `setNativeProps` is fired once then each time that TextInput text-value is being changed, the cursor jumps like the `setNativeProps` was fired again, while [it should be completely ignored and overridden](https://reactnative.dev/docs/direct-manipulation#avoiding-conflicts-with-the-render-function).

 Easiest way to understand is with the short code example.

### Version

0.65.1

### Output of `npx react-native info`

System:
    OS: macOS 11.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 110.83 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.4.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.13 - /usr/local/bin/npm
    Watchman: 2021.06.07.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 28, 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3
      System Images: android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom_64, android-30 | Google Play Intel x86 Atom_64, android-32 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7351085
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.65.1 => 0.65.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

- Add content to `TextInput`
- Set the selection via setNativeProps
- Try to type and change the content of TextInput

### Code example (the reset function is the workaround)
```
import React from 'react';
import { Pressable, Text, TextInput, View } from 'react-native';

const App = () => {
  const [text, setText] = React.useState('initial text');
  
  const ref= React.useRef<TextInput>(null);

  const reset = () => ref.current?.setNativeProps({ selection: {start: 0} });

  const onPress = () => {
    ref.current?.setNativeProps({ selection: {start: 3, end: 7} });
    setTimeout(reset, 500);
  };
  
  return (
    <View style={{ flex: 1, justifyContent: 'space-evenly', alignItems: 'center' }}>
        <Pressable onPress={onPress}><Text>button</Text></Pressable>
        <TextInput ref={ref} value={text} onChangeText={setText} />
    </View>
  );
};

export default App;
```

**Comment by avishain** [comment]
> any workaround for this?

`    ref.current?.setNativeProps({selection: updateToSelection ?? selection});
    if (Platform.OS === 'android') {
      setTimeout(() => {
        ref.current?.setNativeProps({selection: {start: 0}});
      }, 250);
    }
`

**Comment by jordanade** [comment]
Is this why text editing on the Android version of Facebook is borked? I move the cursor back and type, and the typed characters are inserted at the end instead.

**Comment by necolas** [comment]
setNativeProps will not be supported in the new "Fabric" architecture, and should be considered deprecated

https://reactnative.dev/docs/new-architecture-library-intro#migrating-off-setnativeprops

**Comment by MarcHbb** [comment]
You can use `selectTextOnFocus`prop.
If you want to do it programmatically, link the prop to a boolean state ? I didn't try tho

**Comment by noumantahir** [comment]
I have started facing similar issue after enabling new architecture on RN 0.79. On Android, the selection is not being updated and on iOS the cursor jumps to wrong position.

Our in app editor depends heavily on setNativeProps to update text and selection, and moving away from setNativeProps is almost not an option.

Disabling New Arch fixes the issue, so it's safe to assume our culprit is indeed New Arch.

Any ideas...?
