### ISSUE TITLE
it's necessary to give an Interface to control the timeout of JS-bundle loading

### ISSUE THREAD

**Issue by yipengmu** [facebook/react-native#3353]
sometimes,when a problem occur ，the RN-app is stay loading more than severial  minutes as far as screenlock-key pressed( menukey , backkey ,Homekey of hardware both doesn't work  at the time)
![image](https://cloud.githubusercontent.com/assets/3232735/10422199/8f18e6ee-70e9-11e5-92b8-d5e64ca04778.png)

**Comment by satya164** [comment]
Related to this https://github.com/facebook/react-native/issues/3180

**Comment by yipengmu** [comment]
@satya164  tks
