### ISSUE TITLE
Testflight App Crash on startup

### ISSUE THREAD

**Issue by pjay79** [facebook/react-native#33531]
### Description

I have recently upgraded to RN 0.64.3 and Expo SDK 44.

In that process I have found that even though builds run locally (debug and release) on simulator and device, our Testflight build crashes on startup after the splashscreen loads.

The crash report looks like below:

<img width="695" alt="Screen Shot 2022-03-31 at 8 35 22 pm" src="https://user-images.githubusercontent.com/14052885/161025423-59b84b93-c828-424e-bb81-3f5b478f7868.png">

Struggling to decipher what this means and where the source of the errors are, is anybody able to shed some light on this?

Regards

### Version

0.64.3

### Output of `npx react-native info`

```System:
    OS: macOS 11.6.5
    CPU: (8) x64 Apple M1
    Memory: 20.27 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.1 - ~/.nvm/versions/node/v14.15.1/bin/node
    Yarn: 1.22.18 - ~/.nvm/versions/node/v14.15.1/bin/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v14.15.1/bin/npm
    Watchman: 2021.08.02.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7784292
    Xcode: 13.2/13C90 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.3 => 0.64.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

This issue occurs only on deployed builds on testflight.

**Comment by ApplicationNinja** [comment]
Experiencing same issue here...
