### ISSUE TITLE
FlatList very slow on Android only

### ISSUE THREAD

**Issue by stesvis** [facebook/react-native#33542]
### Description

I am experiencing a very slow FlatList on Android, despite the fact that I reduced my `renderItem` component to just text:

FlatList:
```js
<FlatList
        data={customers}
        ItemSeparatorComponent={(props) => <LineSeparator {...props} />}
        renderItem={ListItem}
        style={styles.list} />
```
Where:
```js
const ListItem = ({ item }) => (
    <Text style={{ paddingVertical: 10 }}>Customer {item.id}</Text>
  );
```

So as you can see, very simple.
I fetch `customers` from an API, but I use pagination so I only get 50 in this example.

See the video and notice how laggy it is to scroll:

https://user-images.githubusercontent.com/6062684/161183159-2fb40e5d-8161-409c-81ed-389ca5e93fa9.mp4

Note that in iOS it works perfectly, and I use RN on Expo.

### Version

0.64.3

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.19043
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
    Memory: 707.86 MB / 15.68 GB
  Binaries:
    Node: 16.5.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.5.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.17763.0, 10.0.19041.0
  IDEs:
    Android Studio: Version     2021.1.0.0 AI-211.7628.21.2111.8139111
    Visual Studio: 16.11.32126.315 (Visual Studio Community 2019), 16.10.31515.178 (Visual Studio Enterprise 2019)
  Languages:
    Java: 1.8.0_302 - C:\Program Files\Eclipse Foundation\jdk-8.0.302.8-hotspot\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.3 => 0.64.3
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

FlatList:
```js
<FlatList
        data={customers}
        ItemSeparatorComponent={(props) => <LineSeparator {...props} />}
        renderItem={ListItem}
        style={styles.list} />
```
Where:
```js
const ListItem = ({ item }) => (
    <Text style={{ paddingVertical: 10 }}>Customer {item.id}</Text>
  );
```

**Comment by sadiksdk64** [comment]
issue can be with style. remove style then try.

**Comment by psvnlsaikumar** [comment]
is this from a debug build? or also after the generation of an APK?

**Comment by stesvis** [comment]
> is this from a debug build? or also after the generation of an APK?

It's happening on both.
Today I figured out what's happening. In the video I posted you can see that there is a **Map** tab.
That map is loading a lot of **Markers** and when I comment out that tab everything scrolls fast again.

So it definitely looks like a MapView with many Markers slows down everything (not just the scrolling, everything else slows down, like: opening the drawer menu, navigation etc), but only on Android because on iOS you don't even notice a difference.

**Comment by psvnlsaikumar** [comment]
@stesvis got it.. lazy loading the components might be helpful maybe? https://reactjs.org/docs/react-api.html#reactsuspense

**Comment by henriquebarrosx** [comment]
Which style do you have for FlatList? I had similar problem that makes inverted Flatlist be too slow! Also when I removed the `inverted` prop and use `transform`. A workaround was to use the deprecated `scaleY`, for example!
