### ISSUE TITLE
How To Adopting New Architectures In Multi-Module Android Project?

### ISSUE THREAD

**Issue by zxcvbnm3057** [facebook/react-native#33556]
### New Version

0.68

### Old Version

0.65.1

### Build Target(s)

Android simulator in Debug flavor 

### Output of `react-native info`

info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
    Memory: 2.94 GB / 15.88 GB
  Binaries:
    Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: 17.1.32210.238 (Visual Studio Community 2022)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.68.0 => 0.68.0
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Issue and Reproduction Steps

I have a multi-module android App with a react native activity in a sub-library. It was configured following the guide [Integration with Existing Apps](https://reactnative.dev/docs/integration-with-existing-apps). And now I would like to upgrade the version and try new architectures. But don't know exactly which doc I should follow of ["Supporting the New Architecture in your Library
", "Supporting the New Architecture in your App"]. I also tried use `react-native init` to generate a new project and copy the configurations in *.gradle to my project but can't pass gradle sync. How can I achieve this goal?

My project directory is like this:
- Android(project)
- - module-A(application)
- - module-B(library)
- - module-C(library&RN-activity)
And module-B and module-C is dependencies of module-A, the `node_modules` dictionary is under module-C.

**Comment by cortinico** [comment]
Hey @zxcvbnm3057,
You can find documentation on the New Architecture here:
https://reactnative.dev/docs/next/new-architecture-intro
