### ISSUE TITLE
Initialize new react native app with version v0.68

### ISSUE THREAD

**Issue by huynextlevel** [facebook/react-native#33555]
### Description

Hi guys,
I got problems when I initialize a new app from version >= v0.67. I already installed cocoapods, but still get that fails.

Here is the error I got
![z3311341821113_b52d331c7b980b92b539459b7fbdd001](https://user-images.githubusercontent.com/73922436/161392708-e67067fa-9b5f-435a-a93f-c8ba8c544b04.jpg)

Cocoapods
<img width="587" alt="Screen Shot 2022-04-02 at 23 44 38" src="https://user-images.githubusercontent.com/73922436/161392830-af1cccf3-cf50-41e9-b71a-a793cb6c5ace.png">

### Version

0.68.0

### Output of `npx react-native info`

System:
    OS: macOS 12.3
    CPU: (10) x64 Apple M1 Pro
    Memory: 34.76 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
    Watchman: 2022.03.14.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 13.3/13E113 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.68.0 => 0.68.0
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

npx react-native init newApp

**Comment by danilobuerger** [comment]
For now you could try installing via homebrew instead of gem until this is fixed.

**Comment by huynextlevel** [comment]
Hi @danilobuerger,

Thanks for your reply. I already try that. But it still didn't work. Currently I used this way:
- cd testApp && run bundle install
- cd ios && pod install

Bu I don't know, is it ok?

**Comment by danilobuerger** [comment]
Yes, using `bundle install` should be preferred now. And then use `bundle exec pod install`. With its introduction in 0.68 it was forgotten to update `react-native init`. 

cc @barbieri

**Comment by pushpender-singh-ap** [comment]
Sometimes cocoapods give issues when you install with gem that is why I always install cocoapods with homebrew. `brew install cocoapods`

**Comment by danilobuerger** [comment]
> Sometimes cocoapods give issues when you install with gem that is why I always install cocoapods with homebrew. `brew install cocoapods`

Which you shouldn't do anymore with rn 0.68, as the `Gemfile` specifies which version of `cocoapods` is required. So you might run into problems if `homebrew` installs a different version than the one required by rn.

**Comment by huynextlevel** [comment]
Thanks, @danilobuerger  and @pushpender-singh-ap .
I just uninstall and install cocoapods again with homebrew. Unfortunately, it's still not working. So I think I will use `bundle install` until this issue has been fixed in the next version.

<img width="889" alt="Screen Shot 2022-04-03 at 00 42 32" src="https://user-images.githubusercontent.com/73922436/161394907-84b70dbf-549c-4b76-b568-8f3762dc74d7.png">

**Comment by pushpender-singh-ap** [comment]
@huynextlevel But in my case, it's working.

<img width="1440" alt="Screenshot 2022-04-02 at 11 22 39 PM" src="https://user-images.githubusercontent.com/73298854/161395273-ff9c0014-f26d-4508-9887-197adc03f049.png">

**Comment by huynextlevel** [comment]
@pushpender-singh-ap it's so weird here. Let me double-check again. Thanks @pushpender-singh-ap !

**Comment by huynextlevel** [comment]
Hi @pushpender-singh-ap ,
Do you use RVM? Which version of your RVM?

**Comment by pushpender-singh-ap** [comment]
> Hi @pushpender-singh-ap , Do you use RVM? Which version of your RVM?

It's already installed in my MacBook Pro so I don't update and install it and the version is `ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.arm64e-darwin21]`.

**Comment by mikehardy** [comment]
I have the same problem, using rvm I keep ruby and cocoapods (installed in the rvm-installed ruby's set of gems) current so I can help stop problems before others get them mostly (like this, was super fun https://github.com/CocoaPods/CLAide/issues/98)

the `.ruby-version` thing is what stops it from working for me. One of the first things I do is delete all the gemfile/bundle stuff post-0.67 then install

https://github.com/mikehardy/rnfbdemo/blob/1328c44290ff4d9e64004ffa68962982e6fe2107/make-demo.sh#L55-L62

```bash
# New versions of react-native include annoying Ruby stuff that forces use of old rubies. Obliterate.
if [ -f Gemfile ]; then
  rm -f Gemfile* .ruby*
fi


# Now run our initial dependency install
yarn
npm_config_yes=true npx pod-install
```
