### ISSUE TITLE
Padding does not apply to the top of multiline TextInput on iOS

### ISSUE THREAD

**Issue by mlazari** [facebook/react-native#33562]
### Description

On iOS in a multiline TextInput `padding: X` applies to all sides, except the top side.

A workaround is to add `paddingTop: X`.

This seems to happen because the multiline TextInput on iOS has a `paddingTop` value set to 5 in React Native and that takes precedence over the `padding` value we set since it's more specific: https://github.com/facebook/react-native/commit/1b013cd30ce201cafb376782bdf427f601940220#diff-846840f37831efe100d9ef18d888a2ef838ad986a8c0e3107bf8029b1401d0bfR875

### Version

0.66.4

### Output of `npx react-native info`

  System:
    OS: macOS 12.3.1
    CPU: (8) x64 Apple M1
    Memory: 29.53 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: Not Found
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
    Watchman: 2021.12.20.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 29, 30, 31
      Build Tools: 29.0.2, 30.0.2, 31.0.0
      System Images: android-24 | ARM 64 v8a, android-25 | Google APIs ARM 64 v8a, android-30 | Google APIs ARM 64 v8a, android-31 | Google APIs ARM 64 v8a, android-31 | Google Play ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8139111
    Xcode: 13.3/13E113 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.4 => 0.66.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

```
<TextInput
  style={{
    backgroundColor: 'white',
    borderWidth: 1,
    borderColor: 'black',
    height: 100,
    padding: 20, // <--- THIS DOES NOT APPLY TO THE TOP SIDE ON IOS
  }}
  multiline={true}
  placeholder={'write something...'}
  textAlignVertical={'top'}
/>
```

### Snack, code example, screenshot, or link to a repository

https://snack.expo.dev/@l3m3a3/multiline-textinput-padding-bug

**Comment by mlazari** [comment]
This issue seems to be related: https://github.com/facebook/react-native/issues/21720

**Comment by greffgreff** [comment]
Any updates? I am having the same issue.

**Comment by hichemfantar** [comment]
this fixes it for me https://github.com/facebook/react-native/issues/21720#issuecomment-532642093
