### ISSUE TITLE
yarn installation failed

### ISSUE THREAD

**Issue by midhuhu** [facebook/react-native#33568]
### Description

When my project is installed using yarn, the download dependencies are completed, but it fails when bob builds, prompting that there is no tsconfig file, but my project does not use ts。
![image](https://user-images.githubusercontent.com/57053885/161696249-a9d4f202-3f89-44ca-8356-d175824b08a7.png)
![image](https://user-images.githubusercontent.com/57053885/161696286-5a99ea62-87b3-4bbd-9ec4-0b45507676f4.png)
![image](https://user-images.githubusercontent.com/57053885/161696413-84d4b47e-1eae-475a-8d27-f67f2a0eb711.png)
![image](https://user-images.githubusercontent.com/57053885/161696451-bdfb00c4-c989-4e69-8c5c-6ae60f933e3d.png)

### Version

0.61.4

### Output of `npx react-native info`

System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz
    Memory: 6.96 GB / 15.83 GB
  Binaries:
    Node: 12.20.0 - C:\Software\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.8 - C:\Software\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: Not Found
  Languages:
    Java: 1.8.0_311
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

use yarn

### Snack, code example, screenshot, or link to a repository

What should I do to solve this problem

**Comment by akunal1** [comment]
create a tsconfig.ts file in your root level of project  and paste below code then try once.

// tsconfig.ts
```
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "jsx": "react-native",
    "lib": [
      "dom",
      "esnext"
    ],
    "moduleResolution": "node",
    "noEmit": true,
    "skipLibCheck": true,
    "resolveJsonModule": true,
    "strict": true
  },
  "extends": "expo/tsconfig.base"
}

```

**Comment by cortinico** [comment]
Closing as the RN version you're reporting this for is too old. Please update to 0.68 and try again
