### ISSUE TITLE
Unable download JS Bundle(Error) , while running the example Android Movies app?

### ISSUE THREAD

**Issue by prashanthnani** [facebook/react-native#3357]
./gradlew :Examples:Movies:android:app:installDebug

**Comment by cjmling** [comment]
I just had this issue and this solved mehttp://stackoverflow.com/a/32574231/507203

**Comment by nsisodiya** [comment]
http://stackoverflow.com/a/32574231/507203

**Comment by christopherdro** [comment]
@facebook-github-bot answered
