### ISSUE TITLE
Keyboard event listeners (keyboardDidHide) are not working properly for Android with notch 

### ISSUE THREAD

**Issue by Prutii35** [facebook/react-native#33571]
### Description

Since updating to the latest react native version (0.68.0) keyboard event listeners are not working as expected for some android devices with notch (in my case Pixel 3 XL). 

The problem seems to be on the keyboardDidHide event, which is not fired at all when the keyboard is dismissed.

I have the following listeners in my code. The problem is that keyboardDidShow event is called evey time the keyboard is dismissed, instead of the keyboardDidHide event. The problem occurs only on devices with notch, same code on another devices ( Pixel 3a XL for example ) is working as expected.
```
  useEffect(() => {
    const keyboardDidShowListener = Keyboard.addListener(
      'keyboardDidShow',
      () => {
        console.log('keyboardDidShow');
      },
    );
    const keyboardDidHideListener = Keyboard.addListener(
      'keyboardDidHide',
      () => {
        console.log('keyboardDidHide');
      },
    );

    return () => {
      keyboardDidHideListener?.remove();
      keyboardDidShowListener?.remove();
    };
  }, []);

```
Another usefull information that might help is that on the 0.66.0 version, the listeners are working as expected on all devices.

### Version

0.68.0

### Output of `npx react-native info`

System:
    OS: macOS 11.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 369.17 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.10.0 - /usr/local/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 7.24.2 - /usr/local/bin/npm
    Watchman: 2021.10.04.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 12.3/12C33 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.14 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.0 => 0.66.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. Run a project with react-native:0.68.0 and with a TextInput component displayed
2. Add event listeners for keyboardDidHide and keyboardDidShow on the component
3. Notice how only keyboardDidShow is fired

**Comment by galkinsden** [comment]
Maybe reason is `react-native-extra-dimensions-android` package https://github.com/facebook/react-native/issues/33056#issuecomment-1074791894

**Comment by Prutii35** [comment]
Indeed, the issue was because of the `react-native-extra-dimensions-android` library, removing this from the project is fixing all the keyboard events issues. Thank you @galkinsden

**Comment by minhpham1203** [comment]
hi @galkinsden, any solutions for the Keyboard Listener if I keep using this lib: react-native-extra-dimensions-android? Thanks

**Comment by elenitaex5** [comment]
What about experimenting same problem but not having `react-native-extra-dimensions-android` in my project???

**Comment by walidmaouche** [comment]
i have same problem any solution ?

**Comment by art3wol** [comment]
same problem here, it causing issues in android 15  only tho on rn version 0.68.3. its also causing my @react-navigation/material-bottom-tabs tab navigator to hide as soon as keyboard is opened in my file at some point

**Comment by walidmaouche** [comment]
i fixed the issue by adding this package react-native-keyboard-controller.
in your App.tsx add this 

import { KeyboardProvider } from 'react-native-keyboard-controller';
<KeyboardProvider>
   <App>
</KeyboardProvider>
https://github.com/kirillzyusko/react-native-keyboard-controller

**Comment by anuraguengage** [comment]
> [@anurawgdev](https://github.com/anurawgdev) were you able to solve this specific error ? I'm facing the same case...

no, I tried solving it by searching for keyboard listeners handling in tab navigator package but couldn't find any.

but after last android 15 update in my pixel 7 around last week, I'm not facing this issue anymore. Atleast the tab navigator issue, haven't checked if keyboard listeners are working as expected for text inputs or not

**Comment by anurawgdev** [comment]
> [@anurawgdev](https://github.com/anurawgdev) were you able to solve this specific error ? I'm facing the same case...

no, I tried solving it by searching for keyboard listeners handling in tab navigator package but couldn't find any.

but after last android 15 update in my pixel 7 around last week, I'm not facing this issue anymore. Atleast the tab navigator issue, haven't checked if keyboard listeners are working as expected for text inputs or not

**Comment by anuraguengage** [comment]
> [@anurawgdev](https://github.com/anurawgdev) were you able to solve this specific error ? I'm facing the same case...

@chapael i had stopped facing this issue earlier with no special handling, but now its happening again after updated my sdk version to 35. Were u able to resolve it anyhow?
