### ISSUE TITLE
Pod Outdated command gives React Pod deprecated output

### ISSUE THREAD

**Issue by snehalk-16** [facebook/react-native#33573]
### Description

I am using react-native 0.67.4 in the project. As a part of security review, we use 'Pod Outdated' command to check for any deprecated Pods. We are constantly getting a result- 
The following pods are deprecated:
-React

Is there any solution to resolve this? Or any documentation as to why is it shown as deprecated?

### Version

0.67.4

### Output of `npx react-native info`

System:
    OS: macOS 11.1
    CPU: (4) x64 Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz
    Memory: 91.92 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.3 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.5.2 - ~/Desktop/abott_care/abbott_acare_mobile_india/node_modules/.bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    Android SDK:
      API Levels: 23, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.3
      System Images: android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.2/12B45b - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_275 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: ^0.67.4 => 0.67.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Go to iOS directory in the react-native project. Run Pod Outdated command. It will show that React Pod is deprecated.

**Comment by netniV** [comment]
I have seen this too, but not found a solution yet.
