### ISSUE TITLE
Help: Do not run the project on IOS 7.1.2

### ISSUE THREAD

**Issue by zazerin** [facebook/react-native#3358]
I can't run the standard project on the device (IOS7.1.2). In the emulator (IOS8.4) the app runs successfully. Please tell me what could be the problem.
![img_0690](https://cloud.githubusercontent.com/assets/7760279/10399643/84e1d6c4-6ebc-11e5-84d5-fece072a8bde.jpg)

**Comment by javache** [comment]
This has been fixed already by https://github.com/facebook/react-native/commit/e885628245193dfbd893ec27aed901607a543cdc

**Comment by zazerin** [comment]
thanks

**Comment by MossP** [comment]
[Searchable Keywords] TypeError undefined is not an object evaluating originalConsole[methodName]
