### ISSUE TITLE
[CI] RN Tester iOS failing

### ISSUE THREAD

**Issue by matinzd** [facebook/react-native#33583]
### Description

RN Tester app cannot be built on CI.

```
/Users/distiller/react-native/ReactCommon/hermes/inspector/chrome/Connection.cpp:763:15: error: no member named 'sampledTraceToStreamInDevToolsFormat' in 'facebook::hermes::HermesRuntime'
    hermesRT->sampledTraceToStreamInDevToolsFormat(profileStream);
    ~~~~~~~~  ^
1 error generated.
```

Related commit:

https://github.com/facebook/hermes/commit/9757378b211d6fbce5432b15995a400b3901f12a

### Version

0.68.0

### Output of `npx react-native info`

System:
    OS: macOS 12.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 37.36 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.14.0/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
    Watchman: 2021.09.13.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /Users/matin/.rvm/gems/ruby-3.0.2/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 31.0.0
      System Images: android-27 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play ARM 64 v8a, android-30 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom_64, android-31 | Google APIs Intel x86 Atom_64, android-S | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7351085
    Xcode: 13.3/13E113 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.10 - /usr/local/opt/openjdk@11/bin/javac
  npmPackages:
    @react-native-community/cli: ^7.0.3 => 7.0.3 
    react: 17.0.2 => 17.0.2 
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Every build is failing on main branch.

**Comment by cortinico** [comment]
Fixed by #33585
