### ISSUE TITLE
why not publish reactNative to Maven/Jcenter/Google?

### ISSUE THREAD

**Issue by henryloveself** [facebook/react-native#33591]
### Description

8: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:mergeDebugNativeLibs'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.facebook.react:react-native:0.67.2.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/facebook/react/react-native/0.67.2/react-native-0.67.2.pom
       - https://repo.maven.apache.org/maven2/com/facebook/react/react-native/0.67.2/react-native-0.67.2.pom
       - https://jcenter.bintray.com/com/facebook/react/react-native/0.67.2/react-native-0.67.2.pom
     Required by:
         project :app

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

### Version

0.67.2

### Output of `npx react-native info`

npx react-native info
warn Package cjs-module-lexer has been ignored because it contains invalid configuration. Reason: Package subpath './package.json' is not defined by "exports" in /Users/hesheng/reactnative/MyTest/ReactNativeTest/node_modules/cjs-module-lexer/package.json
warn Package escalade has been ignored because it contains invalid configuration. Reason: Package subpath './package.json' is not defined by "exports" in /Users/hesheng/reactnative/MyTest/ReactNativeTest/node_modules/escalade/package.json
warn Package get-package-type has been ignored because it contains invalid configuration. Reason: Package subpath './package.json' is not defined by "exports" in /Users/hesheng/reactnative/MyTest/ReactNativeTest/node_modules/get-package-type/package.json
info Fetching system and libraries information...
System:
    OS: macOS 12.3.1
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 81.89 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.4 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 6.14.10 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7784292
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.14 - /Library/Java/JavaVirtualMachines/jdk-11.0.14.jdk/Contents/Home/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.2 => 17.0.2 
    react-native: ^0.67.2 => 0.67.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. Android studio- new project
2. npm install --save react-native@0.67.2
3. npm install --save react@17.0.2
4. add app/build.gradle(implementation "com.facebook.react:react-native:0.67.2" //与node_modules下的rn版本号一致
implementation "org.webkit:android-jsc:+")
5. add build.gradle in project(maven {
            url "$rootDir/node_modules/react-native/android"
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/node_modules/jsc-android/dist")
        })
6. sync       

### Snack, code example, screenshot, or link to a repository

- https://dl.google.com/dl/android/maven2/com/facebook/react/react-native/0.67.2/react-native-0.67.2.pom
- https://repo.maven.apache.org/maven2/com/facebook/react/react-native/0.67.2/react-native-0.67.2.pom
- https://jcenter.bintray.com/com/facebook/react/react-native/0.67.2/react-native-0.67.2.pom

I checked release version in these links, found only maven center has release version(latest version is [0.20.1/](https://repo.maven.apache.org/maven2/com/facebook/react/react-native/0.20.1/)), so why not publish react-native release version in those three lib center?

**Comment by cortinico** [comment]
> I checked release version in these links, found only maven center has release version(latest version is [0.20.1/](https://repo.maven.apache.org/maven2/com/facebook/react/react-native/0.20.1/)), so why not publish react-native release version in those three lib center?

That's intended.
Currently `com.facebook.react:react-native:+` should be consumed from the NPM package `react-native`. We added a directive to the build.gradle file to handle this specifically:

https://github.com/facebook/react-native/blob/f503b212039f79f00ea56b65ecf3cd150b82f087/template/android/build.gradle#L32-L46
