### ISSUE TITLE
[Fabric][ReactNative 0.68][IOS] Codegen parse error when running build 

### ISSUE THREAD

**Issue by Alaa-Ben** [facebook/react-native#33593]
### Description

Hi !
On IOS, when enabling Fabric, Pod installation goes well. Then, when starting a build, it fails with parsing errors, see screenshot.

### Version

0.68.0

### Output of `npx react-native info`

System:
    OS: macOS 12.3
    CPU: (10) x64 Apple M1 Pro
    Memory: 37.49 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.8.0 - ~/.nvm/versions/node/v17.8.0/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v17.8.0/bin/npm
    Watchman: 2022.03.14.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /Users/qucit/.rvm/gems/ruby-2.7.2/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 13.3/13E113 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.14.1 - /Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.0 => 0.68.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

- Enable fabric on IOS
- Install Pods
- Run build

### Snack, code example, screenshot, or link to a repository

![Capture d’écran 2022-04-08 à 09 45 31](https://user-images.githubusercontent.com/26058727/162389707-6b4a4776-9350-4170-8059-13dfbc2087e5.png)
![Capture d’écran 2022-04-08 à 09 45 56](https://user-images.githubusercontent.com/26058727/162389751-d8cc0fd2-387c-4483-908e-b13e4a012157.png)
![Capture d’écran 2022-04-08 à 09 46 45](https://user-images.githubusercontent.com/26058727/162389876-64d8afbe-aca7-4a2e-958f-ae6def7c34bf.png)

**Comment by cipolleschi** [comment]
Sorry, but we are not supporting 0.68 anymore and Codegen has changed a lot since that version.
Please update to a [supported version](https://github.com/reactwg/react-native-releases/blob/main/README.md?rgh-link-date=2023-11-02T11%3A07%3A37Z#releases-support-policy) and try again.
