### ISSUE TITLE
Websocket onmessage method triggering problem(Android)

### ISSUE THREAD

**Issue by dy2-X** [facebook/react-native#33600]
### Description

I see the packets is arrived When I trace the raw data packets using by wireshark. But, websocket listener callback function is not triggered, if packet size more than 1KB.(websocket connection is alive. Not crashed or any warning) It is working correctly when packet size is less 1KB.

React Native version: 0.67.1-0.68
Platform: Android (iOS is OK.)
Hermes is activated.

### Version

0.67.1

### Output of `npx react-native info`

System:
    OS: macOS 12.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
    Memory: 7.05 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.8.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.5.5 - /usr/local/bin/npm
    Watchman: 2022.03.21.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28, 29, 30, 31, 32
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.0, 30.0.2, 31.0.0
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-31 | Google Play Intel x86 Atom_64, android-32 | Google Play Intel x86 Atom_64, android-Tiramisu | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.1 => 0.67.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

const ws = new Websocket(url);
ws.onmessage = (e) => {
  console.log(e);
}

**Comment by dy2-X** [comment]
Developer facing similar issue can check below:

<Sec-WebSocket-Extensions= permessage-deflate> in Header of handshaking packet.

**Comment by ertandk** [comment]
> Developer facing similar issue can check below:
> 
> <Sec-WebSocket-Extensions= permessage-deflate> in Header of handshaking packet.

Hello, ws.onmessage works on the iOS side, but it does not even have this function on the Android side.
  Websocket is a websocket based on .net framework.
Which side should I write this title on? When connecting on my mobile app? Or when sending data on the server side?

Can you give more detailed information? I am faced with this problem. Thank you.
