### ISSUE TITLE
React Native: undefined is not an object (evaluating 'useContext.getItemsCount')

### ISSUE THREAD

**Issue by johannesorssichs** [facebook/react-native#33605]
### Description

I'm a beginner on React Native and I am getting this error when getItemsCount is called.

Please see attached screenshot of the error: 

![Uploading Screenshot 2022-04-10 at 13.10.10.png…]()

This is the code for CartIcon.js:

`import React, {useContext} from 'react';
import {View, Text, StyleSheet} from 'react-native';
import {CartContext} from './CartContext';
export function CartIcon({navigation}){
    const {getItemsCount} = useContext(CartContext);
    return(
        <View style = {styles.container}>
            <Text style = {styles.text}
                onPress = {() => { 
                navigation.navigate('Cart');
                }}
            >Cart ({getItemsCount()}) </Text>
        </View>
        );
}
const styles = StyleSheet.create({
    container: {
        marginHorizontal: 10,
        backgroundColor: '#515b8c',
        height: 40,
        padding: 15,
        borderRadius: 38/2,
        alignItems: 'center',
        justifyContent: 'center',
    },
    text: {
        color: '#ccc',
        fontWeight: 'normal',
    },
});
`

This is the code for CartContext.js:

`import React, {createContext, useState} from 'react';
import {getProduct} from './productService.js';
export const CartContext = createContext();
export function CartProvider(props){
	const [items, setItems] = useState([]);

	function addItemToCart(id){
		const product = getProduct(id);
		setItems((prevItems) => {
			const item = prevItems.find((item) => (item.id == id));
			if(!item){
				return [...prevItems, {
					id,
					qty: 1,
					product,
					totalPrice: product.price
				}];
			}
			else{
				return prevItems.map((item) => {
					if(item.id == id){
						item.qty++;
						item.totalPrice += product.price;
					}
					return item;
				});
			}
		});
	}
	function getItemsCount(){
		return items.reduce((sum,item) => (sum+item.qty),0);
	}
	function getTotalPrice(){
		return items.reduce((sum,item) => (sum+item.totalPrice),0);
	}

	return(
		<CartContext.Provider
		value = {{items,setItems,getItemsCount,addItemToCart,getTotalPrice}}>
		{props.children} 
		</CartContext.Provider>
	);
}`

### Version

0.67.4

### Output of `npx react-native info`

System:
    OS: macOS 11.3.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 81.11 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.8.0 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.5.5 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.4 => 0.67.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

![Uploading Screenshot 2022-04-10 at 13.11.54.png…]()

### Snack, code example, screenshot, or link to a repository

![Uploading Screenshot 2022-04-10 at 13.12.06.png…]()

**Comment by Luke-Tembani** [comment]
Hello,

Im not sure if you have found a solution to the above problem. I was having the same issue on a project lm working on. The solution is quite simple. Import ContextProvider as a component to your entry file (index.js/App.js) as follows:


![Screenshot (89)](https://user-images.githubusercontent.com/64020395/179395651-35b384b8-589a-46f5-be5a-fd26751a0b04.png)

Let me know if it works
