### ISSUE TITLE
[Native API] ReadableArray/Map <-> WritableArray/Map

### ISSUE THREAD

**Issue by vitaminwater** [facebook/react-native#3360]
Is there any way to convert say, a ReadableMap to a WritableMap ?

Or maybe you have a better way to handle this use case:
I have a component that receives objects as props or as method parameters.
This component should be able to emit an event with one of the received objects as property of the event.

Then you have problem, because the RCTEventEmitter API only sends WritableMaps/Arrays, and you have no way to go from readable to writable, you can't even store a readable object as a property of a writable one.

Deep copy is possible, but there should a better, lower level way I think.

I ended up passing ids back in the event, then do a match on the javascript side.

**Comment by ide** [comment]
cc @kmagiera @mikearmstrong001

**Comment by kmagiera** [comment]
except from making a copy there is no easy way right now. I think it shouldn't be that complicated to patch bridge to allow nesting readablemap in writablemap or just to allow readablemap/array as an argument.
I think that passing IDs is a better approach as it saves on bridge traffic. When you pass object to native and then pass it back to JS it'd still make a copy of that object (it will be serialized twice).

**Comment by vitaminwater** [comment]
Yes, and the IDs method doesn't even really add any boilerplate or other annoyance. thanks

**Comment by tomsdev** [comment]
It seems you are satisfied with using ids, if so could you close the issue?

**Comment by JeffGuKang** [comment]
Use `merge` method in WriteableMap.
