### ISSUE TITLE
React Native Network Request Failed when services are deployed through intranet

### ISSUE THREAD

**Issue by kafeelkhatri** [facebook/react-native#33617]
### Description

I am facing issues while consuming apis that are deployed on a server internally in department. I tried in ReactJS web application, got same issue but i resolved that by using a proxy domain. But the same thing is not resolving the issue in React Native.

Services endpoints are map through DNS by creating vhost on server machine. My endpoint is like: [https://abc.domain.com/api/..](https://abc.domain.com/).

Can anyone help me out resolving this issue. I have been trying all a long way out but nothing positive is coming out.

Thanks.

### Version

1.0

### Output of `npx react-native info`

npm@6.14.7 C:\Program Files\nodejs\node_modules\npm

### Steps to reproduce

When i call  API through fetch or axios i get result network request failed.
My services are deployed  to different machine and  endpoints are provided  DNS Vhost

**Comment by flyskywhy** [comment]
[fixed `TypeError: Network request failed` when upload file to http not https with Android debug builds](https://github.com/facebook/react-native/issues/33217#issuecomment-1159844475)
