### ISSUE TITLE
React-Native WebView iOS 13.2 Video does not play 

### ISSUE THREAD

**Issue by devalok1508** [facebook/react-native#33626]
### Description

React-native web view video does not play only iOS 13.2 version and all apart from 13.2 versions remaining device iOS it work.
Same issue with android version 10 . vivo devices.
Video not Play.

### Version

0.66.4

### Output of `npx react-native info`

In iOS version 13.2 when I click on video icon screen is freeze.
but when I click apart from 13.2 IOS devices this video play very good.

### Steps to reproduce

Click on play icon screen is freeze only iOS version 13.2 devices

### Snack, code example, screenshot, or link to a repository

import { StyleSheet, Text, View ,Dimensions} from 'react-native'
import React from 'react';
import { WebView } from 'react-native-webview';
const { height,width } = Dimensions.get('window');

const WebViewnew = () => {
  return (
    <View style={{
        backgroundColor:"yellow",
        height:height,
        width:width,
    }}>
         <WebView
          source={{uri: 'https://screencast-o-matic.com/embed?sc=qsN7&v=5&ff=1'}}
          javaScriptEnabled={true}
          domStorageEnabled={true}
          startInLoadingState={true}
          style={{
            height:height,
            width:width
          }}
        />
     </View>
  )
}

export default WebViewnew

const styles = StyleSheet.create({})

**Comment by gorbypark** [comment]
Hey @devalok1508,
react-native-webview is a separate project from react-native itself.  [Here's the repo for react-native-webview](https://github.com/react-native-webview/react-native-webview).

**Comment by devalok1508** [comment]
> Hey @devalok1508,
> react-native-webview is a separate project from react-native itself. [Here's the repo for react-native-webview](https://github.com/react-native-webview/react-native-webview).

Yes
but I use react-native webview inside react-native and I got error only IOS 13.2 device and remaining all device of iOS it is working react-native web view only issue come in IOS version 13.2

**Comment by devalok1508** [comment]
> `****`[](https://drive.google.com/file/d/12jEYYJr9EQzizUQucsgUKPVcKcqAy1Oq/view?usp=sharing)

**Comment by devalok1508** [comment]
https://drive.google.com/file/d/12jEYYJr9EQzizUQucsgUKPVcKcqAy1Oq/view?usp=sharing

**Comment by devalok1508** [comment]
https://drive.google.com/file/d/12jEYYJr9EQzizUQucsgUKPVcKcqAy1Oq/view?usp=sharing

This is a video you can see clearly issue with between device IOS 13.2 or IOS version 15.4

**Comment by cortinico** [comment]
> react-native-webview is a separate project from react-native itself. [Here's the repo for react-native-webview](https://github.com/react-native-webview/react-native-webview).

As suggested, please report this issue on the react-native-webview issue tracker, and get back to here once the investigation on their end confirms that is a React Native issue.
