### ISSUE TITLE
React native 0.68 new architecture view disappears when using state on IOS

### ISSUE THREAD

**Issue by vuonghvat** [facebook/react-native#33624]
### Description

I use state and setState then the view in the screen disappears for no reason, it doesn't on android:
In this case I used isLoading and setLoading like below: 

<img width="881" alt="Screen Shot 2022-04-13 at 09 51 01" src="https://user-images.githubusercontent.com/21377313/163091160-d51584aa-b294-4285-99a5-e657454499f7.png">

 ******* Before clicking login button: 

<img width="366" alt="Screen Shot 2022-04-13 at 09 51 30" src="https://user-images.githubusercontent.com/21377313/163091282-93e5f978-7990-401b-9954-8613bdb24050.png">

 ******* After clicking login and the view is gone. I'm sure none of the views are overwritten, it's magic: 

![Simulator Screen Shot - iPhone 13 - 2022-04-12 at 16 34 47](https://user-images.githubusercontent.com/21377313/163091428-6131e107-51c5-4e75-9754-7e804781a432.png)

### Version

0.68

### Output of `npx react-native info`

System:
    OS: macOS 12.0.1
    CPU: (8) arm64 Apple M1
    Memory: 450.13 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.8.0 - /opt/homebrew/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.5.5 - /opt/homebrew/bin/npm
    Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 29, 30, 31, 32
      Build Tools: 29.0.2, 30.0.0, 30.0.2, 30.0.3, 32.0.0
      System Images: android-32 | Google APIs ARM 64 v8a, android-32 | Google Play ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7935034
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.0 => 0.68.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

I use state and setState then the view in the screen disappears for no reason, it doesn't on android

**Comment by simonhoss** [comment]
I have the same issue. Is there a reason why this is closed?
