### ISSUE TITLE
Patch update for React Native app

### ISSUE THREAD

**Issue by oney** [facebook/react-native#3363]
Basically, the way of updating React Native app is making user download the new version `main.jsbundle`, and the `main.jsbundle` file is normally greater than 1MB. Although the change of new version is just tens of line to fix a bug, the users still need to download 1MB file. After gzip compressing, the file size can be reduced to about 300KB, but it still takes 1 second downloading. So, it's impossible to make users get new version app instantly. Users should use old version app first and downloading new version task will be executed in the background, and users get new version in next time.

Any idea to improve this issue? Maybe we can update app with a patch file by using library like [this](https://github.com/JanX2/google-diff-match-patch-Objective-C). It will simply send changed text to users to update app.

**Comment by satya164** [comment]
I guess you can write a library for this. I can be complex though, as it needs to take into account if any versions failed to download in middle and stuff.

**Comment by chirag04** [comment]
There is apphub.io and reploy.io for this i guess.

**Comment by oney** [comment]
Yeah, I am thinking to make a library for this, and I just want to make sure whether there is already a library or tool that implements this feature.

**Comment by javache** [comment]
There's a number of community solutions for this already. A generic library that would apply patches to a local bundle file would be really useful but not core to React Native.
