### ISSUE TITLE
2 borders in borderRadius style

### ISSUE THREAD

**Issue by work4m** [facebook/react-native#33632]
### Description

I am applying this style when I need radius but its showing two radius in Android working fine in iOS.

  ```
  container: {
        marginVertical: 8,
        borderRadius: 10,
        paddingHorizontal: 17,
        marginRight: 10,
        width: 160,
        backgroundColor: Colors.white,

        borderWidth: 0.3,
        borderColor: Colors.primary,

        shadowColor: Colors.primary,
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,

        elevation: 5,
    },
```

### Version

0.67.3

### Output of `npx react-native info`

error Unrecognized command "info".
info Run "react-native --help" to see a list of all available commands.

### Steps to reproduce

Follow given style

### Snack, code example, screenshot, or link to a repository

<img width="230" alt="Screenshot 2022-04-13 at 8 58 59 PM" src="https://user-images.githubusercontent.com/46574150/163216403-94e6e6bb-cd94-45df-b7e6-7bd113646994.png">

**Comment by dulmandakh** [comment]
@work4m it's due to shadow or elevation. Could you please try removing shadow and elevation styles.
