### ISSUE TITLE
[iOS] Failed to get image height and width correctly

### ISSUE THREAD

**Issue by wing-stampix** [facebook/react-native#33631]
### Description

With iOS devices, RN fails to get the correct width and height of certain images. There will be 1 pixel missing from both sides of the photo. 
We have tackled down it to the `loadImageWithURLRequest` in `RCTImageLoader` so far. 
 
While I tried to use `expo-media-library` to check on the same images, it reports the sizes correctly with the `PHAsset`. 

### Version

0.67.0

### Output of `npx react-native info`
```
System:
    OS: macOS 12.0.1
    CPU: (4) x64 Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz
    Memory: 1.19 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.0.1 - /var/folders/d9/vdt8j5211v37ryqz7c1nqdkm0000gn/T/yarn--1649843635419-0.6999506393815631/node
    Yarn: 1.22.17 - /var/folders/d9/vdt8j5211v37ryqz7c1nqdkm0000gn/T/yarn--1649843635419-0.6999506393815631/yarn
    npm: 7.24.2 - ~/Desktop/stampix/stampix-app-v3/node_modules/.bin/npm
    Watchman: 2021.11.15.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 30, 31, 32
      Build Tools: 30.0.2, 32.0.0, 32.1.0
      System Images: android-30 | Intel x86 Atom_64, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 13.3/13E113 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.0 => 0.67.0 
    react-native-macos: Not Found
```

### Steps to reproduce

![A0D64BD1-2583-46BB-A68A-4DD57909DA0E](https://user-images.githubusercontent.com/85339400/163216860-ffebd31b-1b96-4e3e-994d-261a120e8c76.jpeg)
<img width="319" alt="Screenshot 2022-04-13 at 17 34 07" src="https://user-images.githubusercontent.com/85339400/163216956-516f5389-0fda-49de-8152-afac7c12d784.png">

The image size of this sample image is 341 × 288 pixels

- Get this sample photo in an IOS device
- Get the size of the image, there is 1 pixel missing on the width and height.

### Snack, code example, screenshot, or link to a repository

```js
  Image.getSize(
    uri,
    (width, height) => {
      console.log(' width, height:', width, height);
    },
    () => console.error()
  );
//output: width, height: 340 287
```

**Comment by StampixSMO** [comment]
Also having this issue
