### ISSUE TITLE
How to use registerForActivityResult instead of onActivityResult

### ISSUE THREAD

**Issue by PritishSawant** [facebook/react-native#33639]
### Description

I am not able to use registerForActivityResult in Android custom Native module. I am stuck with the deprecated onActivityResult

### Version

0.68

### Output of `npx react-native info`

System:
OS: macOS 12.3.1
CPU: (8) x64 Apple M1
Memory: 50.59 MB / 8.00 GB
Shell: 5.8 - /bin/zsh
Binaries:
Node: 16.13.0 - /usr/local/bin/node
Yarn: 1.22.10 - /usr/local/bin/yarn
npm: 8.1.0 - /usr/local/bin/npm
Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
Managers:
CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
SDKs:
iOS SDK:
Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
Android SDK: Not Found
IDEs:
Android Studio: 2021.1 AI-211.7628.21.2111.8193401
Xcode: 13.3/13E113 - /usr/bin/xcodebuild
Languages:
Java: javac 16 - /usr/bin/javac
npmPackages:
@react-native-community/cli: Not Found
react: 17.0.2 => 17.0.2
react-native: 0.67.4 => 0.67.4
react-native-macos: Not Found
npmGlobalPackages:
react-native: Not Found

### Steps to reproduce

Try creating a native module and replacing onActivityResult with registerForActivityResult

**Comment by cortinico** [comment]
You can find documentation on `registerForActivityResult` here:
https://developer.android.com/training/basics/intents/result

**Comment by PritishSawant** [comment]
@cortinico but how to use this in a native module in react native. An example would be appreciated.

**Comment by cortinico** [comment]
@PritishSawant have you checked the examples on https://developer.android.com/training/basics/intents/result#launch ?

**Comment by PritishSawant** [comment]
@cortinico  yes but it is impossible to use this api given how react native is structured. An example would be appreciated.

**Comment by alarm109** [comment]
Is it impossible to use `registerForActivityResult` in react native module? Because you must extend `ComponentActivity` class and the only class which does so is `ReactActivity`.
But if you are creating a react native module, you cannot access `ReactActivity`, the best you can do is to get `Activity` from the method `getCurrentActivity` in `ReactContextBaseJavaModule`. 

In my module I can't use `startActivityForResult` and need to use `registerForActivityResult`, is there any way to do it?

**Comment by cortinico** [comment]
> @cortinico yes but it is impossible to use this api given how react native is structured. An example would be appreciated.

It depends on how your code is structured but something like:

```kotlin
// From ReactContextBaseJavaModule
val currentActivity = reactContext.currentActivity
if (currentActivity is AppCompatActivity) {
	currentActivity.registerForActivityResult() 
}
```

**Comment by alarm109** [comment]
> It depends on how your code is structured but something like:
> 
> ```kotlin
> // From ReactContextBaseJavaModule
> val currentActivity = reactContext.currentActivity
> if (currentActivity is AppCompatActivity) {
> 	currentActivity.registerForActivityResult() 
> }
> ```

@cortinico, I tried your example, but I still get an error:
`LifecycleOwner com.xxx.MainActivity@c3ccf41 is attempting to register while current state is RESUMED. LifecycleOwners must call register before they are STARTED.`

Code example:
```kotlin
val currentActivity = reactContext.currentActivity
if (currentActivity is AppCompatActivity) {
    healthConnectManager = HealthConnectManager(reactContext, currentActivity)
}

healthConnectManager.authorize(promise)
```

```kotlin
class HealthConnectManager(
    private val reactContext: ReactApplicationContext,
    private val currentActivity: AppCompatActivity
) {

    private val healthConnectClient = HealthConnectClient.getOrCreate(reactContext)
    private var permissions = HealthConnectPermissions.NONE

    private val myPluginScope = CoroutineScope(SupervisorJob() + Dispatchers.Main.immediate)

    fun authorize(promise: Promise) {
         myPluginScope.launch {
            val grantedPermissions =
                healthConnectClient.permissionController.getGrantedPermissions(PERMISSIONS)
            if (grantedPermissions.containsAll(PERMISSIONS)) {
                permissions = HealthConnectPermissions.ALL
                promise.resolve(true)
            } else {
                Log.d(TAG, "Request permissions.")
                requestPermissions.launch(PERMISSIONS)
            }
        }
    }

    // Create the permissions launcher.
    private val requestPermissionActivityContract =
        healthConnectClient.permissionController.createRequestPermissionActivityContract()

    private val requestPermissions =
        currentActivity.registerForActivityResult(requestPermissionActivityContract) { granted ->
            permissions = if (granted.containsAll(PERMISSIONS)) {
                Log.d(TAG, "All permissions granted")
                HealthConnectPermissions.ALL
            } else {
                Log.d(TAG, "Lack of permissions")
                HealthConnectPermissions.PARTIAL
            }
        }

    companion object {
        // build a set of permissions for required data types
        private val PERMISSIONS =
            setOf(
                HealthPermission.createReadPermission(StepsRecord::class),
                HealthPermission.createWritePermission(StepsRecord::class)
            )
    }
}
```

**Comment by cortinico** [comment]
> @cortinico, I tried your example, but now I get this error:
> LifecycleOwner com.xxx.MainActivity@c3ccf41 is attempting to register while current state is RESUMED. LifecycleOwners must call register before they are STARTED.
> ```

The problem is self explanatory: you can't call `registerForActivityResult` after the activity has started.

I suggest you move the:

```
    private val requestPermissions =
        currentActivity.registerForActivityResult(requestPermissionActivityContract) { granted ->
            permissions = if (granted.containsAll(PERMISSIONS)) {
                Log.d(TAG, "All permissions granted")
                HealthConnectPermissions.ALL
            } else {
                Log.d(TAG, "Lack of permissions")
                HealthConnectPermissions.PARTIAL
            }
        }
```

inside your MainActivity and then just call `healthConnectManager.authorize(promise)` as you're doing today. You'll have to get the `requestPermissions` as a field from the Activity.

**Comment by Legion2** [comment]
We are developing a SDK which provides React Native UI via a Fragment. We create a single React Native Context for multiple fragments, so we can preload and share the JS runtime and native modules, because react native startup time is a major issue. But then there is no single place where we can call registerForActivityResult. We could call registerForActivityResult in the first fragment's onCreate, but if the React Native Context is reused in a new Fragment later, the registered handler from the first Fragment becomes invalid and cannot be used anymore.

**Comment by alarm109** [comment]
> inside your MainActivity and then just call `healthConnectManager.authorize(promise)` as you're doing today. You'll have to get the `requestPermissions` as a field from the Activity.

Okay, understood. So there is no way of implementing this from the module side, the user of the module would still need to add some code to `MainActivity` of his RN project.

@cortinico Thank you for the replies!

**Comment by m-lce** [comment]
Hello,
I use registerForActivityResult in my code in my React Native project. The activity launch is ok with this, but I never get the callback of registerForActivityResult executed.
Have you any ideas of what could be going wrong ?

**Comment by HilSny** [comment]
@alarm109 did you ever get this to work, if so could you share a sample of how you did the permissions with registerForActivityResult. I'm currently working with the Health connect api and am looking for guidance on this specific issue :)

**Comment by yberstad** [comment]
Hi, this is how I set up the registerForActivityResult in my React Native project:
https://stackoverflow.com/a/75144449/3080858

**Comment by serybva** [comment]
I may have a slightly better solution using the process described here https://developer.android.com/training/basics/intents/result#separate declaring the callback in the MainActivity isn't required anymore therefore the app stays decoupled from any react native module.

In my case the callback wasn't called, maybe because ReactActivity declares a `onRequestPermissionsResult` methods which probably gets called instead, the solution is to dispatch the result from here.

Override `onRequestPermissionsResult` in your MainActivity with
```
public void onRequestPermissionsResult(int requestCode, String[] permissions, int[] grantResults) {
    this.getActivityResultRegistry().dispatchResult(requestCode, grantResults[0] == PackageManager.PERMISSION_GRANTED);
  }
```

And you're done

**Comment by BraveEvidence** [comment]
Yes actually this is how i got it to work in flutter as well

**Comment by BraveEvidence** [comment]
This can help https://www.youtube.com/watch?v=Bn-HIVb2ZIw

**Comment by BraveEvidence** [comment]
Can someone help with how to use it with TurboModules https://stackoverflow.com/questions/75576907/how-to-use-registerforactivityresult-with-turbomodules-in-react-natives-new-arc

**Comment by matinzd** [comment]
Let's see if this lands:

https://github.com/react/react-native/pull/57798
