### ISSUE TITLE
Newly Created React Native project fails to run iOS: Command PhaseScriptExecution failed

### ISSUE THREAD

**Issue by thechaudharysab** [facebook/react-native#33634]
### Description

I've created a new project using `react-native init` method and when I run `npx react-native run-ios` or even try to build the app on a simulator using XCode I get a long error 

```
N/A: version "default -> N/A" is not yet installed.

You need to run "nvm install default" to install it before using it.
Command PhaseScriptExecution failed with a nonzero exit code
```

I'm using Xcode v13.3 (13E113). My `npm -v` is **8.6.0** and my react-native version is **0.68.1** and react version is **17.0.2**. The node version I'm using is **v16.14.2**

I. have tried to clean the Derived Data folder `rm -rf ~/Library/Developer/Xcode/DerivedData` but still the error is the same. I'm trying to run it on a simulator. I have even tried the `nvm install default` but it gives me **Version 'default' not found - try `nvm ls-remote` to browse available versions.** I'm not sure if the versioning has something to do with it but I'm sharing what I can. My Mac is not M1, it has the old intel chip.

### Version

0.68.1

### Output of `npx react-native info`

System:
    OS: macOS 12.3.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 1.14 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: Not Found
    npm: 8.5.0 - /usr/local/bin/npm
    Watchman: 2021.10.18.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7784292
    Xcode: 13.3/13E113 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.10 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.1 => 0.68.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. Do `npx react-native init PROJECT_NAME`
2. Then `npx react-native run-ios`

### Snack, code example, screenshot, or link to a repository

<img width="907" alt="Screen Shot 2022-04-14 at 2 06 58 AM" src="https://user-images.githubusercontent.com/6399152/163243227-ae6b7395-e044-46ce-b7e6-4bd4a0a1bda8.png">
<img width="847" alt="Screen Shot 2022-04-14 at 2 24 38 AM" src="https://user-images.githubusercontent.com/6399152/163245786-5207f600-3545-4aa7-9b14-28a663356929.png">

**Comment by thechaudharysab** [comment]
Uninstall Node and npm and reinstall. This worked for me so far.

**Comment by bozaigao** [comment]
@thechaudharysab thank you very much!I tried everything and the final changes are as follows:
**nvm unalias default
nvm alias default node**
