### ISSUE TITLE
Facing white blank screen in iOS

### ISSUE THREAD

**Issue by Maharshi01** [facebook/react-native#33637]
### Description

In iOS device, when the app has been put in background overnight in recent apps and opening it in the next day causing the app the go blank white screen. But when it is killed and opened again it is working perfectly alright. This is happening even before the splash screen. Please refer the video to understand the issue. We have checked in local if there are any issues, however couldn't able to replicate or find errors. In firebase crashlytics also there are no crashes for that user. Could you please help us understand why this happens and how to avoid this

https://user-images.githubusercontent.com/48430425/163311975-fb5a0605-3aed-4d96-9f55-084a8c980701.mp4

Device Details :

iOS version : 15.3.1

device model : iPhone 13 

### Version

0.61.5

### Output of `npx react-native info`

System:
    OS: macOS 11.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 78.00 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.15.1 - /usr/local/bin/node
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 2021.08.23.00 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7486908
    Xcode: 13.0/13A233 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1

### Steps to reproduce

After installing the app, putting in background for more than 12+ hrs and opening the next day causing to face the white blank screen.

**Comment by Mai-Hong-Son** [comment]
same problem :((

**Comment by AnaisGalisson-ChillStudio** [comment]
I have the same problem since the upgrade of my iPhone from 14.X to 15.X. Exact same problem : after putting the app in background around one day, blank screen in my app. 

React Native version : 0.61.0

As we have old version of react-native, I suppose this is the issue. I'll tell you after upgrading if it has any effect !

**Comment by andrepharma** [comment]
Hello everyone!!!

Was anyone able to find the solution to this problem?

I'm testing my app on the iPhone and it's opening normally, but when I take the test on the iPad, it doesn't leave the white blank screen, so Apple is rejecting my app in the apple store!

Can you help me?

**Comment by itolegmysin** [comment]
Hi guys

Do you think it might be related to https://reactnative.dev/docs/publishing-to-app-store#pro-tips somehow ?

**Comment by Chill-Studio** [comment]
I resolved the problem by upgrading React Native at 0.65. I hope this will help you

**Comment by jitadlak** [comment]
i will solved this problem. please connect with me on jitadlak@gmail.com

**Comment by Sahilthakur7** [comment]
I'm also facing the same issue. Did anyone find a solution to this?

**Comment by AnaisGalisson-ChillStudio** [comment]
> I'm also facing the same issue. Did anyone find a solution to this?

Which version of RN are you using ?

**Comment by LunyovYuriy** [comment]
"react-native": "0.70.5", facing the same issue, did anyone find a solution?

**Comment by asadumair** [comment]
any sollution?

**Comment by julien-kv** [comment]
Any solution?

**Comment by naseerahmedaziz** [comment]
any solution for this issue? I am stuck with it as well

**Comment by joaolvcas** [comment]
any solution?

**Comment by chrisovato** [comment]
any solution?

**Comment by sleekLancelot** [comment]
For me I only get this problem on an iPhone 14, still searching for a solution.

**Comment by Farial-mahmod** [comment]
It might be due to a high number of API calls on the main (UI) thread. You may assign some networked tasks to a background thread and observe the result.

**Comment by kiroInn** [comment]
"react-native": "0.76.9", facing the same issue, did anyone find a solution?

**Comment by Yokool** [comment]
Facing the same issue but haven't figure out a solution yet - react-native 0.77.1
