### ISSUE TITLE
TextInput with editable set to false does not emit OnPressIn and OnPressOut

### ISSUE THREAD

**Issue by michalmaka** [facebook/react-native#33649]
### Description

Having `TextInput` component with `editable` prop set to `false` has different effect on iOS and Android.
On iOS `OnPressIn` and `OnPressOut` are emitted correctly, but on Android they're not triggered.

### Version

0.68.1

### Output of `npx react-native info`

It's clearly visible on snack, no need for my workspace configuration

### Steps to reproduce

1. Create `TextInput` component
2. Set `editable` prop to false
3. Use `OnPressIn` callback
4. See no execution of `OnPressIn` on Android

### Snack, code example, screenshot, or link to a repository

https://snack.expo.dev/@michal.maka/textinput-editable-android

**Comment by KanwarBhajneek** [comment]
Setting it to falsy value will work on both Android and iOS. In above snack link `editable={null}` works on both Android and iOS

**Comment by imhazige** [comment]
Encountered same problem

**Comment by tkud04** [comment]
> Setting it to falsy value will work on both Android and iOS. In above snack link `editable={null}` works on both Android and iOS

This worked for me on both Android and iOS

**Comment by davoam** [comment]
> > Setting it to falsy value will work on both Android and iOS. In above snack link `editable={null}` works on both Android and iOS
> 
> This worked for me on both Android and iOS

This works, but it causes a TypeScript error since type of `editable` is `boolean | undefined`.

**Comment by dnwjn** [comment]
> Setting it to falsy value will work on both Android and iOS. In above snack link `editable={null}` works on both Android and iOS

This works for me too!

**Comment by devjenildgohel** [comment]
not worked for me ! i tried passing null but textfield not disabled ! (on common component)

**Comment by ray-holland-es** [comment]
Have the same problem

**Comment by hssdiv** [comment]
apart from using editable={null}

I also added Keyboard.dismiss() at the end of event, as android was pulling up keyboard and still focusing that input

**Comment by laurisdedumets** [comment]
Setting `editable={null}` seems to emit the signal on Android because it doesn't actually prevent the field from being editable, so there is no point of even adding it as a property.

I'm not familiar with the source code of React Native, but I think this is the line that confirms this: https://github.com/facebook/react-native/blob/f30acc6f5c04857a3df47bb6f1b428af57a477b0/packages/react-native/Libraries/Components/TextInput/TextInput.js#L1409

Until this issue is fixed, the workaround of wrapping your input with some sort of Pressable is the only valid option to achieve this functionality.

**Comment by adesh1167** [comment]
> I found a solution to trigger a function on pressing the TextInput with editable set to false for both iOS and android.
> 
> * Wrap the TextInput component with a Pressable component.
> * Put your function in the onPress prop of the Pressable component. (This triggers the function on android)
> * Then add the same function to the onPressIn prop of the TextInput component. (This triggers the function on iOS)

this saved the day

**Comment by M-Arslan04** [comment]
> I found a solution to trigger a function on pressing the TextInput with editable set to false for both iOS and android.
> 
> * Wrap the TextInput component with a Pressable component.
> * Put your function in the onPress prop of the Pressable component. (This triggers the function on android)
> * Then add the same function to the onPressIn prop of the TextInput component. (This triggers the function on iOS)

This one works like a charm, Thanks 🙇

**Comment by spottenn** [comment]
This is still a problem and I don't think it should have been closed.

**Comment by AlexandreLira** [comment]
> I found a solution to trigger a function on pressing the TextInput with editable set to false for both iOS and android.
> 
> * Wrap the TextInput component with a Pressable component.
> * Put your function in the onPress prop of the Pressable component. (This triggers the function on android)
> * Then add the same function to the onPressIn prop of the TextInput component. (This triggers the function on iOS)

i added  pointerEvents='box-only' on Pressable and started to work
