### ISSUE TITLE
Website is currently down

### ISSUE THREAD

**Issue by mbabatunde** [facebook/react-native#33643]
### Description

Hi folks,

The React Native site is currently down and reporting a `521` error.

Is there an ETA when the site will be back up?

### Version

N/A

### Output of `npx react-native info`

N/A

### Steps to reproduce

Within your browser, go to https://reactnative.dev/

### Snack, code example, screenshot, or link to a repository

<img width="1391" alt="Screen Shot 2022-04-14 at 8 20 30 AM" src="https://user-images.githubusercontent.com/21072448/163389321-ce63dfa5-34d5-4cef-91a1-642771fa34b6.png">

**Comment by aspectxlol** [comment]
![image](https://github.com/user-attachments/assets/5e1c69e6-1667-4696-b008-4b7df2cae622)
still down??
