### ISSUE TITLE
Android - App crash with OutOfMemoryError when New Architecture is enabled

### ISSUE THREAD

**Issue by usmankhan495** [facebook/react-native#33640]
### Description

Tested app with new architecture enable on physical device and emulator. It is crashing on both with different logs.
**Physical device logs :**
A/libc: Fatal signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x6f53b77000 in tid 26254 (mqt_js), pid 21727

**Emulator logs:**
java.lang.OutOfMemoryError: Failed to allocate a 321682744 byte allocation with 4077047 free bytes and 188MB until OOM, target footprint 8186863, growth limit 201326592

**NDK version** :  24.0.8215888
1. Still crashing after updating  memory size.
```
 # Specifies the JVM arguments used for the daemon process.
 # The setting is particularly useful for tweaking memory settings.
 # Default value: -Xmx1024m -XX:MaxPermSize=256m
-# org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
+org.gradle.jvmargs=-Xmx4g -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
```

### Version

0.68.0

### Output of `npx react-native info`

System:
    OS: macOS 11.6
    CPU: (8) arm64 Apple M1
    Memory: 147.16 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.8.0 - /opt/homebrew/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 8.5.5 - /opt/homebrew/bin/npm
    Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8309675
    Xcode: 13.0/13A233 - /usr/bin/xcodebuild
  Languages:
    Java: javac 18 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.0 => 0.68.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Just created a new app using npx react-native init.

**Repo Link :**
https://github.com/usmankhan495/TestProject

### Snack, code example, screenshot, or link to a repository

https://github.com/usmankhan495/TestProject
_No response_

**Comment by cortinico** [comment]
Thanks for the report @usmankhan495 and thanks for sharing the repro.

I've tried to build your project and it runs fine on a Pixel 3 I'm testing on.
I'm not really able to reproduce at this stage.

The fact that you're having two different crashes makes me feel you're having a dirty environment maybe?

As a small nit: this line is wrong (you don't need the `+` in front).
https://github.com/usmankhan495/TestProject/blob/6f80bc10d40424da59c92f5b8740151e3449b444/android/gradle.properties#L15

**Comment by lindboe** [comment]
I also saw the same OutOfMemory error when trying to use the 0.68.1 template + the New Architecture. Old Architecture builds and runs normally. Emulator vs physical device did not seem to make a difference.

In both cases, `yarn android` succeeds, the app attempts to launch, shows only a gray screen for a few seconds, and then the app closes crashes back to home.

The OOM looks like it might be happening as the result of trying to report a different error, based on the stack trace:

```
04-13 22:04:57.893 20140 20140 W com.sixeighton: Throwing OutOfMemoryError "Failed to allocate a 316460232 byte allocation with 6291456 free bytes and 251MB until OOM, target footprint 10958688, growth limit 268435456" (VmSize 34207376 kB)
04-13 22:04:57.905 20140 20140 W com.sixeighton: Throwing OutOfMemoryError "Failed to allocate a 316460232 byte allocation with 6291456 free bytes and 251MB until OOM, target footprint 10893888, growth limit 268435456" (VmSize 34207376 kB)
04-13 22:04:57.916 20140 20140 W com.sixeighton: Throwing OutOfMemoryError "Failed to allocate a 320453672 byte allocation with 6291456 free bytes and 251MB until OOM, target footprint 10877576, growth limit 268435456" (VmSize 34207376 kB)
04-13 22:04:57.925 20140 20140 W com.sixeighton: Throwing OutOfMemoryError "Failed to allocate a 320453672 byte allocation with 6291456 free bytes and 251MB until OOM, target footprint 10877536, growth limit 268435456" (VmSize 34207376 kB)
04-13 22:04:57.926 20140 20140 E AndroidRuntime: Error reporting crash
04-13 22:04:57.926 20140 20140 E AndroidRuntime: java.lang.OutOfMemoryError: Failed to allocate a 320453672 byte allocation with 6291456 free bytes and 251MB until OOM, target footprint 10877536, growth limit 268435456
04-13 22:04:57.926 20140 20140 E AndroidRuntime:        at java.util.Arrays.copyOf(Arrays.java:3257)
04-13 22:04:57.926 20140 20140 E AndroidRuntime:        at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
04-13 22:04:57.926 20140 20140 E AndroidRuntime:        at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
04-13 22:04:57.926 20140 20140 E AndroidRuntime:        at java.lang.StringBuilder.append(StringBuilder.java:137)
04-13 22:04:57.926 20140 20140 E AndroidRuntime:        at java.lang.Throwable.toString(Throwable.java:493)
04-13 22:04:57.926 20140 20140 E AndroidRuntime:        at java.lang.String.valueOf(String.java:2924)
04-13 22:04:57.926 20140 20140 E AndroidRuntime:        at java.io.PrintWriter.println(PrintWriter.java:754)
04-13 22:04:57.926 20140 20140 E AndroidRuntime:        at java.lang.Throwable$WrappedPrintWriter.println(Throwable.java:778)
04-13 22:04:57.926 20140 20140 E AndroidRuntime:        at java.lang.Throwable.printStackTrace(Throwable.java:667)
04-13 22:04:57.926 20140 20140 E AndroidRuntime:        at java.lang.Throwable.printStackTrace(Throwable.java:735)
04-13 22:04:57.926 20140 20140 E AndroidRuntime:        at android.app.ApplicationErrorReport$CrashInfo.<init>(ApplicationErrorReport.java:407)
04-13 22:04:57.926 20140 20140 E AndroidRuntime:        at android.app.ApplicationErrorReport$ParcelableCrashInfo.<init>(ApplicationErrorReport.java:537)
04-13 22:04:57.926 20140 20140 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:173)
04-13 22:04:57.926 20140 20140 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
04-13 22:04:57.926 20140 20140 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
04-13 22:04:57.926 20140 20140 E AndroidRuntime:        at java.lang.Thread.dispatchUncaughtException(Thread.java:2200)
```

I'm not sure what the primary cause might be. The next most suspect item I saw in the logs was an SoLoader error about `libjscexecutor.so`:

```
04-13 22:04:54.594 20140 20140 E SoLoader: couldn't find DSO to load: libjscexecutor.so
04-13 22:04:54.594 20140 20140 E SoLoader:      SoSource 0: com.facebook.soloader.ApkSoSource[root = /data/data/com.sixeightone/lib-main flags = 1]
04-13 22:04:54.594 20140 20140 E SoLoader:      SoSource 1: com.facebook.soloader.DirectorySoSource[root = /data/app/~~dDY0D_9pcDAZuXQqITBU7A==/com.sixeightone-aPux_gOVJ2FfcEcR34LEIA==/lib/arm64 flags = 0]
04-13 22:04:54.594 20140 20140 E SoLoader:      SoSource 2: com.facebook.soloader.DirectorySoSource[root = /system/lib64 flags = 2]
04-13 22:04:54.594 20140 20140 E SoLoader:      SoSource 3: com.facebook.soloader.DirectorySoSource[root = /vendor/lib64 flags = 2]
04-13 22:04:54.594 20140 20140 E SoLoader:      Native lib dir: /data/app/~~dDY0D_9pcDAZuXQqITBU7A==/com.sixeightone-aPux_gOVJ2FfcEcR34LEIA==/lib/arm64
```

`npx react-native info`:

```info Fetching system and libraries information...
System:
    OS: macOS 12.2.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 1.24 GB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.6.0 - /opt/homebrew/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.5.1 - /opt/homebrew/bin/npm
    Watchman: 2022.03.07.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/lizzi/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 31, 32
      Build Tools: 30.0.2, 30.0.3, 32.0.0, 32.1.0, 33.0.0
      System Images: android-32 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
  Languages:
    Java: javac 18 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.68.1 => 0.68.1
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by usmankhan495** [comment]
@cortinico Thanks for reviewing code repo.
There is some issue with JDK installed form oracle for apple M1. After removing JDK and installing OpenJDK distribution from Zulu, it start working. 
@lindboe you can also try this, if you are not using Zulu OpenJDK.

**Comment by cortinico** [comment]
That's a good pointer. Was this solving for both Emulator and Device setup?

**Comment by usmankhan495** [comment]
Yes, Now it is working for both emulator and device.

**Comment by lindboe** [comment]
Ah, I had Zulu 18 installed. Downgrading to Zulu 11 works.
