### ISSUE TITLE
Unable to resolve module ./debugger-ui

### ISSUE THREAD

**Issue by Tycholiz** [facebook/react-native#33659]
### Description

Not sure what to say about this one. Encountered the [mega thread](https://github.com/facebook/react-native/issues/28844), took every last suggestion and still facing this issue. The thread was closed without an official comment, and it would seem this issue still persists. Not sure why this issue happens in the first place, but it does, and it seems that there are others who face this exact same issue.

### Version

0.67.4

### Output of `npx react-native info`

System:
    OS: macOS 12.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 78.37 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.19.1 - /usr/local/opt/node@14/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 6.14.16 - /usr/local/opt/node@14/bin/npm
    Watchman: 2021.10.18.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.3
      System Images: android-26 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: 13.3/13E113 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_252 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.67.4 => 0.67.4
    react-native-macos: Not Found
  npmGlobalPackages:

### Steps to reproduce

`yarn run-ios`
open debugger on ios simulator

**Comment by cipolleschi** [comment]
Hi @Tycholiz thanks for opening the issue.

In your repro steps, you say:

> yarn run-ios
> open debugger on ios simulator

When you say `open debugger` you mean the web debugger?

**Comment by Tycholiz** [comment]
I mean in the iOS simulator menu (opened by pressing cmd+d), there is an option to enable debugging
