### ISSUE TITLE
Throw "Property 'Proxy' doesn't exist" error due to dependencies update in 0.62.2

### ISSUE THREAD

**Issue by 8ugmaker** [facebook/react-native#33651]
### Description

when i got start in hermes, i found "RefrenceError: Property 'Proxy' doesn't exist, js engine: hermes" in my phone, which is  located in backend.js in react-devtools-core, and version of react-devtools-core is 0.42.4, i checked the source code, i found it use "new Proxy", which is not support in hermes.

### Version

0.62.2

### Output of `npx react-native info`

System:
    OS: macOS 12.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.65 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.4.2 - ~/.nvm/versions/node/v16.4.2/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.18.1 - ~/.nvm/versions/node/v16.4.2/bin/npm
    Watchman: 2021.06.07.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7486908
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
    Python: 2.7.18 - /Library/Frameworks/Python.framework/Versions/2.7/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

steps are simple
make sure your react-native version is 0.62.2
run it in hermes

**Comment by xinyujauchou** [comment]
I got the same error.
It seem to throw in backend.js file which locate in react-devtools-core library

My env are below:
**react-native:** 0.62.2

**Comment by czy0729** [comment]
> I got the same error. It seem to throw in backend.js file which locate in react-devtools-core library
> 
> My env are below: **react-native:** 0.62.2

i also use react-native@0.62.2, today i reinstall the packages then get the same issue which has never happened before
i find that react-native@0.62.2 package.json "react-devtools-core": "^4.0.6" has updated 3 month ago

so you can add this in the `package.json` into your project

```
"resolutions": {
    "react-devtools-core": "4.23.0"
 }
```

then reinstall your node_modules by yarn
