### ISSUE TITLE
Error Can't Find Module node_modules\react-native\node_modules\react-native\scripts\generate-specs-cli.js'

### ISSUE THREAD

**Issue by rabihiawaludin** [facebook/react-native#33663]
### Description

`Error: Cannot find module 'C:\Users\...\.....\...\...\...\...\node_modules\react-native\node_modules\react-native\scripts\generate-specs-cli.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}`

I found this error after upgrading to RN 0.68 when build with `npx react-native run-android`. I can't find this generate-specs-cli.js in node_modules. Some can help me?

### Version

0.68.0

### Output of `npx react-native info`

System:
    OS: Windows 10 10.0.16299
    CPU: (4) x64 Intel(R) Core(TM) i3 CPU       M 370  @ 2.40GHz
    Memory: 637.88 MB / 5.68 GB
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.16 - ~\AppData\Roaming\npm\npm.CMD
    Watchman: 4.9.0 - C:\Users\Administrator.DESKTOP-OJLOEQN\AppData\Local\watchman\watchman.EXE
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version     2021.1.0.0 AI-211.7628.21.2111.8193401
    Visual Studio: 16.8.30907.101 (Visual Studio Community 2019)
  Languages:
    Java: 11.0.14.1 - C:\Program Files\Eclipse Adoptium\jdk-11.0.14.101-hotspot\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: ^0.68.0 => 0.68.0
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

--

### Snack, code example, screenshot, or link to a repository

![image](https://user-images.githubusercontent.com/7922577/163927075-c2ab14c5-898b-439b-9cae-06e8f957fd61.png)

**Comment by vanja1993** [comment]
Hello @rabihiawaludin, I would like to help you with this issue by starting a conversation around it. 

You mentioned in description that this issue appeared after upgrading to RN 0.68. Let me clarify few things: 

- from which RN version did you upgrade?
- which steps did you take to upgrade? And related question - have you used [RN upgrade helper](https://react-native-community.github.io/upgrade-helper/)?
- did you install dependencies (e.g. `yarn install`) after the upgrade?
- have you tried cleaning cache? E.g. xcode, gradlew, node - there are different options depending on your project setup.

This might be helpful to trace any missed steps during the upgrade. Also this information will provide better understanding for anyone willing to help.

**Comment by rabihiawaludin** [comment]
Hi @vanja1993.

1. I upgraded from 0.63.4
2. I use https://reactnative.dev/docs/next/new-architecture-app-intro for step to upgrade, and [RN Upgrade Helper too](https://react-native-community.github.io/upgrade-helper/)
3. I use npm install after upgrade and 
4. I use, gradle / gradlew clean and react-native start --reset-cache for cleaning cache

**Comment by rabihiawaludin** [comment]
`Execution failed for task ':app:generateCodegenArtifactsFromSchema'.`

**Comment by rabihiawaludin** [comment]
Hi @vanja1993 , I have followed the upgrade steps from [RN Upgrade Helper](https://react-native-community.github.io/upgrade-helper/), but there is an error like this
`'java.lang.String com.android.utils.FileUtils.relativePossiblyNonExistingPath(java.io.File, java.io.File)'`

**Comment by rabihiawaludin** [comment]
I have done with this issue, but my apps crash when apps launching frm build, and show error:
` com.facebook.react.uimanager.IllegalViewOperationException: Trying to attach a ReactRootView with an explicit id already set to [1]. React Native uses the id field to track react tags and will overwrite this field. If that is fine, explicitly overwrite the id field to View.NO_ID.`
