### ISSUE TITLE
Error when start project

### ISSUE THREAD

**Issue by phuongit0301** [facebook/react-native#33662]
### Description

Hi team

Im just init project React Native 0.67.3 and running. But it show error like image below

![Screen Shot 2022-04-18 at 14 39 18](https://user-images.githubusercontent.com/3425152/163775042-e89f7ed6-e6a1-4185-a47b-37a4ca43877e.png)

### Version

0.67.3

### Output of `npx react-native info`

System:
    OS: macOS 12.3
    CPU: (8) arm64 Apple M1 Pro
    Memory: 129.89 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.18 - ~/.yarn/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
    Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 28, 30, 31, 32
      Build Tools: 28.0.1, 28.0.2, 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 33.0.0
      System Images: android-30 | ARM 64 v8a, android-30 | Intel x86 Atom_64, android-30 | Google APIs ARM 64 v8a, android-30 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom_64, android-31 | ARM 64 v8a, android-32 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 13.3/13E113 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.1 => 0.68.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. npx react-native init ReferreachMobileNew --template react-native-template-typescript
2. cd ReferreachMobileNew && npx react-native run-android

**Comment by Shanghai-** [comment]
According to the logs, you are using JDK version 1.8, while Gradle requires at least Java 11. You need to install the latest Java Development Kit.

**Comment by cortinico** [comment]
> According to the logs, you are using JDK version 1.8, while Gradle requires at least Java 11. You need to install the latest Java Development Kit.

@Shanghai- mentioned a valid solution. You need to be on Java 11 to run RN 0.67+
