### ISSUE TITLE
Way to retrieve TextInput value programmatically via property access or method call

### ISSUE THREAD

**Issue by manask88** [facebook/react-native#3367]
following up on #511

onChange is not always the solution. I am having issues when I use keyboard shorcuts on iOS:
This is the scenario: I am filling up a login form (username and password)
I set a shortcut for my username.
When I enter the shortcut and then I push on the return button, I go to the next field (password).
When I enter the last key for the shortcut, onChangeText and onChange will return the value of the shortcut.
When I push enter, none of those events are called up and therefore , I am not able to get the actual value for the shortcut. 
Sine there is no way to get the value of the input text other than using those callbacks, what would be a solution for this case?

**Comment by manask88** [comment]
found a way to do this. Not sure if this is the best way, but this is what I did:

taped into the onSubmitEditing. It returns an event object.
the text value can be retrieved by getting the value out of event.nativeEvent.text

**Comment by ios122** [comment]
onChangeText will be better.

> 
> onChangeText={
>                 (text)=>{
>                   this.state.items[0].content = text;
>                 }
>               }>
