### ISSUE TITLE
Error: ENOENT: no such file or directory, open 

### ISSUE THREAD

**Issue by 007jiang7442262** [facebook/react-native#33676]
### New Version

0.68.1

### Old Version

0.68.1

### Build Target(s)
android    qemu-system-x86_64

### Output of `react-native info`

Error: ENOENT: no such file or directory, open '/Users/jiangchao/Desktop/native/MyAPP/file:/private/var/folders/4n/23_ktqmn09dcf2k_ynkz8z5c0000gn/T/AppTranslocation/472E8D61-9B1C-43CA-AF6F-2516348153ED/d/React%20Native%20Debugger.app/Contents/Resources/app.asar/js/RNDebuggerWorker.js'
    at Object.openSync (node:fs:586:3)
    at Object.readFileSync (node:fs:454:35)
    at getCodeFrame (/Users/jiangchao/Desktop/native/MyAPP/node_modules/metro/src/Server.js:949:18)
    at Server._symbolicate (/Users/jiangchao/Desktop/native/MyAPP/node_modules/metro/src/Server.js:1022:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Server._processRequest (/Users/jiangchao/Desktop/native/MyAPP/node_modules/metro/src/Server.js:429:7) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/jiangchao/Desktop/native/MyAPP/file:/private/var/folders/4n/23_ktqmn09dcf2k_ynkz8z5c0000gn/T/AppTranslocation/472E8D61-9B1C-43CA-AF6F-2516348153ED/d/React%20Native%20Debugger.app/Contents/Resources/app.asar/js/RNDebuggerWorker.js'
}

### Issue and Reproduction Steps

npx react-native init MyAPP
cd  MyAPP
npm run start
npm run  android

{
  "name": "MyAPP",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@babel/plugin-proposal-decorators": "^7.17.9",
    "mobx": "^6.5.0",
    "mobx-react": "^7.3.0",
    "react": "17.0.2",
    "react-native": "0.68.1"
  },
  "devDependencies": {
    "@babel/core": "^7.17.9",
    "@babel/runtime": "^7.17.9",
    "@react-native-community/eslint-config": "^3.0.1",
    "babel-jest": "^27.5.1",
    "eslint": "^8.13.0",
    "jest": "^27.5.1",
    "metro-react-native-babel-preset": "^0.70.1",
    "react-devtools": "^4.14.0",
    "react-native-vector-icons": "^9.1.0",
    "react-test-renderer": "17.0.2"
  },
  "jest": {
    "preset": "react-native"
  },
  "resolutions": { "react-devtools-core": "4.14.0" }
}

**Comment by brahimmouhamou** [comment]
I'm having problems too with a fresh Expo projects where I use "expo-image-picker".
It successfully retrieves a file uri but when I want you upload it with `fetch` I get that same error;

`Error: ENOENT: no such file or directory, open`

**Comment by cipolleschi** [comment]
Hi! Where does these dependencies come from?
```
"mobx": "^6.5.0",
"mobx-react": "^7.3.0",
```

An `npx react-native init <AppName>` should create a `package.json` like this 

```json
{
  "name": "awesomeproject",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "react": "17.0.2",
    "react-native": "0.68.2"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "^7.32.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.67.0",
    "react-test-renderer": "17.0.2"
  },
  "jest": {
    "preset": "react-native"
  }
}
```
This is working fine to me, so I think is an issue related with some of your dependencies.

**Comment by Rakshith658** [comment]
> I'm having problems too with a fresh Expo projects where I use "expo-image-picker". It successfully retrieves a file uri but when I want you upload it with `fetch` I get that same error;
> 
> `Error: ENOENT: no such file or directory, open`



> I'm having problems too with a fresh Expo projects where I use "expo-image-picker". It successfully retrieves a file uri but when I want you upload it with `fetch` I get that same error;
> 
> `Error: ENOENT: no such file or directory, open`

how did you fix it

**Comment by colenndamn** [comment]
I had this exact same problem, it's because you are trying to install packages while expo is running

Go to the console, stop the execution (ctrl+c),

Install the package using either yarn or npm

Start the server again once the package has been installed using expo start.
 it worked for me, hope this helps

**Comment by jobayer977** [comment]
Facing Same issue

**Comment by brahimmouhamou** [comment]
> > I'm having problems too with a fresh Expo projects where I use "expo-image-picker". It successfully retrieves a file uri but when I want you upload it with `fetch` I get that same error;
> 
> > 
> 
> > `Error: ENOENT: no such file or directory, open`
> 
> 
> 
> 
> 
> 
> 
> > I'm having problems too with a fresh Expo projects where I use "expo-image-picker". It successfully retrieves a file uri but when I want you upload it with `fetch` I get that same error;
> 
> > 
> 
> > `Error: ENOENT: no such file or directory, open`
> 
> 
> 
> how did you fix it

I did not, started over without expo.

**Comment by cipolleschi** [comment]
This is more likely an Expo problem. Please, open the issue on their tracker.
