### ISSUE TITLE
error: package com.facebook.fbreact.specs does not exist

### ISSUE THREAD

**Issue by sunel** [facebook/react-native#33685]
### Description

Getting error when building android 

```
error: package com.facebook.fbreact.specs does not exist

error: cannot find symbol
public class JSDevSupport extends NativeJSDevSupportSpec {
                                  ^
  symbol: class NativeJSDevSupportSpec
```

### Version

0.68.0

### Output of `npx react-native info`

```
System:
    OS: macOS 12.3.1
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 9.00 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.19.1 - ~/.nvm/versions/node/v14.19.1/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 6.14.16 - ~/.nvm/versions/node/v14.19.1/bin/npm
    Watchman: 2022.03.21.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8309675
    Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.1 => 0.68.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

```

### Steps to reproduce

open in android studio and build

**Comment by Abhishek2250** [comment]
I can confirm this issue

**Comment by see** [comment]
same issue.

**Comment by cortinico** [comment]
Could you provide a reproducer or a sample project where this is happening?
It seems like the codegen is not running for you, but I can't investigate further without a sample project.

**Comment by sunel** [comment]
Bare react native project and enable Hermes

**Comment by see** [comment]
https://github.com/see/rn-action-test

**Comment by cipolleschi** [comment]
So, with Hermes it is working?

**Comment by cortinico** [comment]
Closing as I haven't got a follow up + I wasn't able to reproduce (ping @see)

> It seems generated code in wrong dir
> eg: com.facebook.fbreact.specs.NativeJSDevSupportSpec
> Expect in [ReactAndroid module]/build/generated/source/codegen But in [App module]/build/generated/source/codegen

The folder you're mentioning is actually the correct one.

Feel free to comment or re-open if you can provider further details 👍

**Comment by psionic12** [comment]
I have a way to reproduce this, add these lines in `ReactAndroid/build.gradle`:
```
    buildTypes {
        release {}
        beta {}
    }
```
Then compile `rn-tester`. The compiler won't find classes in `com.facebook.fbreact.specs` even though they are generated in `ReactAndroid/build/generated/source/codegen/java/com/facebook/fbreact/specs`

**Comment by cortinico** [comment]
> I have a way to reproduce this, add these lines in `ReactAndroid/build.gradle`:

I'm not sure why you're suggesting to enable `buildTypes` inside `ReactAndroid`. That build is part of the framework and is not something you're supposed to edit.
You should instead work on the template files and create a reproducer from there.

**Comment by psionic12** [comment]
@cortinico I just offered a way to reproduce this issue, and our team do modify RN framework for some reason (the main reason is to try to auto link fabric shared libraries), if you think it doesn't make sense, you can just ignore it.

**Comment by cortinico** [comment]
> I just offered a way to reproduce this issue, and our team do modify RN framework for some reason 

Thanks for sharing it. In general, we're looking into configuration in the user space that are resulting in build failures. Editing the files inside `node_modules` is outside of this scope.

> (the main reason is to try to auto link fabric shared libraries)

Just a heads up that Fabric Autolinking is coming with RN 0.70

**Comment by psionic12** [comment]
> Just a heads up that Fabric Autolinking is coming with RN 0.70
@cortinico hi, is there any documentation about this autolinking feature?

**Comment by cortinico** [comment]
@psionic12 Yes is documented here https://github.com/react-native-community/cli/blob/main/docs/autolinking.md
