### ISSUE TITLE
Random crash on Android (Animated node with tag (child) [xxxx] does not exist)

### ISSUE THREAD

**Issue by mk0116** [facebook/react-native#33686]
### Description

I can not find any pattern to get to the crash issue.

It randomly crashes on any screen.

Please help me if anyone knows about this issue.

### Version

0.67.1,0.68.1(no new arch)

### Output of `npx react-native info`

System:
    OS: macOS 12.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 108.63 MB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 8.5.0 - /usr/local/bin/npm
    Watchman: 2022.03.21.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/mike_1_2/.rvm/gems/ruby-2.7.4/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7935034
    Xcode: 13.3/13E113 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.4 => 0.67.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

I can not find any pattern to get to the crash issue.

It completely randomly crashes on any screen.

This is the stacktrace I got from bugsnag.

com.facebook.react.bridge.JSApplicationIllegalArgumentException: connectAnimatedNodes: Animated node with tag (child) [7965] does not exist
        at com.facebook.react.animated.NativeAnimatedNodesManager.connectAnimatedNodes(NativeAnimatedNodesManager.java:340)
        at com.facebook.react.animated.NativeAnimatedModule$15.execute(NativeAnimatedModule.java:681)
        at com.facebook.react.animated.NativeAnimatedModule.executeAllOperations(NativeAnimatedModule.java:258)
        at com.facebook.react.animated.NativeAnimatedModule.access$400(NativeAnimatedModule.java:85)
        at com.facebook.react.animated.NativeAnimatedModule$3.execute(NativeAnimatedModule.java:287)
        at com.facebook.react.uimanager.UIViewOperationQueue$UIBlockOperation.execute(UIViewOperationQueue.java:579)
        at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:915)
        at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1026)
        at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:47)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1086)
        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1106)
        at android.view.Choreographer.doCallbacks(Choreographer.java:866)
        at android.view.Choreographer.doFrame(Choreographer.java:792)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8663)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

**Comment by mk0116** [comment]
found the same issue
https://github.com/facebook/react-native/issues/33375

**Comment by thedycui** [comment]
For me, create a new project with 0.71 and copy old codes to new one resolve this issue for me. 
I tried other ways:
1) add `implementation 'androidx.work:work-runtime:2.7.1'` to build.gradle. (still in 0.71)
2) upgrade to 0.69.7 (with tools) and add `ReactFeatureFlags.enableSynchronizationForAnimated = true;` (not exist in 0.71) and never build success.

**Comment by gomezmark** [comment]
any solution for this one?

**Comment by usmanmalik333** [comment]
need solution for this ?

**Comment by usmanmalik333** [comment]
> @usmanmalik333 which version of react native are you using and on what devices (OS, OS version, brand) do you see it?

I'm facing issue on **Android 12 devices** and I'm using **"react-native": "0.66.3"**

**Comment by wouterds** [comment]
> > @usmanmalik333 which version of react native are you using and on what devices (OS, OS version, brand) do you see it?
> 
> I'm facing issue on **Android 12 devices** and I'm using **"react-native": "0.66.3"**

You should update to one of the later versions, it's been fixed I belive in 0.68 or 0.69.

**Comment by usmanmalik333** [comment]
> > > @usmanmalik333 which version of react native are you using and on what devices (OS, OS version, brand) do you see it?
> > 
> > 
> > I'm facing issue on **Android 12 devices** and I'm using **"react-native": "0.66.3"**
> 
> You should update to one of the later versions, it's been fixed I believe in 0.68, 0.69 or 0.70.

Okay i will try by upgrading the version

**Comment by bhavzie** [comment]
> > > @usmanmalik333 which version of react native are you using and on what devices (OS, OS version, brand) do you see it?
> > 
> > 
> > I'm facing issue on **Android 12 devices** and I'm using **"react-native": "0.66.3"**
> 
> You should update to one of the later versions, it's been fixed I believe in 0.68, 0.69 or 0.70.

We are on `0.69.7` and are still facing this crash on Android 12. Do you have a link to the commit which fixes it?

**Comment by LiuIos** [comment]
We are on 0.71.3 and are still facing this crash on Android 12

**Comment by saghul** [comment]
Also seeing this in 0.68. Any chance this can be reopened, since it does not seem to be fixed?

**Comment by wouterds** [comment]
@LiuIos @bhavzie as far as I know, it's never been explicitly fixed. The main topic (https://github.com/facebook/react-native/issues/33375) was closed and it wasn't really re-opened elsewhere / people stopped talking about it (assuming it had been unknowingly fixed along the way).

I tried creating an example repository to reproduce the issue but so far I could not. We do see the issue in our project at work though. What seems related is `useAnimatedDriver: true`. If we set this explicitly to false everywhere (also in all libraries used by the project) we see significantly fewer crashes.

I'm not saying it is the cause but it is definitely related. I don't have enough experience with native Android development to further debug this, unfortunately.

An [example repository](https://github.com/wouterds/react-native-tv-example) I once made is using the [`react-native-tvos`](https://github.com/react-native-tvos/react-native-tvos) fork which currently runs on 0.69.8. Compiles for both iOS, tvOS, Android Mobile & Android TV but essentially it's the same bug. However as mentioned above, I can not reproduce it in the example yet. Probably because it doesn't contain enough animations, I will look into adding some animated shimmer components that might help reproducing it.

**Comment by bhavzie** [comment]
Thanks for the detailed info @wouterds. 
We are getting fewer crashes on disabling `useAnimatedDriver: true` too. Although there is definitely a trade-off involved as you suggested.

**Comment by wouterds** [comment]
As @cortinico & @kelset mentioned over at #33375, the first step is creating an example project where this is consistently reproducible so people can investigate and pin down the issue. So all help welcome to create an example project where this can be reproduced easily.

**Comment by saghul** [comment]
I believe the problem here is the bug is not consistently reproducible to begin with. We've received 230 crashes in the last week for example, with the following distribution in devices / versions.

<img width="463" alt="Screen Shot 2023-04-25 at 15 12 06" src="https://user-images.githubusercontent.com/317464/234287186-12c9862a-c138-4d5d-a198-31f2821a1ebf.png">

Try as I might, can't reproduce it at will.

**Comment by bhavzie** [comment]
+1 very similar numbers ^
It's only on Android 12 and it isn't consistently reproducible, hence the numbers aren't exactly super high

**Comment by wouterds** [comment]
@bhavzie @saghul @liuIos @usmanmalik333; are you making use of react-navigation? If so, using the stack or native-stack package?

**Comment by saghul** [comment]
We do use react-navigation, with the JS stack navigator.

**Comment by bhavzie** [comment]
We are using react-navigation with stack navigator as well

**Comment by wouterds** [comment]
I was able to create a reproducible example in a test build where I added 20 swimlanes of which 2 out of 3 randomly animate, the screen is quite heavy but if you navigate a few times the app eventually crashes quite quickly with little effort.

Mostly with this exception:
```
04-27 13:20:21.717 27102 27102 E AndroidRuntime: FATAL EXCEPTION: main
04-27 13:20:21.717 27102 27102 E AndroidRuntime: Process: io.evix.reactnativetvexample, PID: 27102
04-27 13:20:21.717 27102 27102 E AndroidRuntime: com.facebook.react.bridge.JSApplicationIllegalArgumentException: connectAnimatedNodes: Animated node with tag (child) [5998] does not exist
04-27 13:20:21.717 27102 27102 E AndroidRuntime: 	at com.facebook.react.animated.NativeAnimatedNodesManager.connectAnimatedNodes(NativeAnimatedNodesManager.java:346)
04-27 13:20:21.717 27102 27102 E AndroidRuntime: 	at com.facebook.react.animated.NativeAnimatedModule$16.execute(NativeAnimatedModule.java:751)
04-27 13:20:21.717 27102 27102 E AndroidRuntime: 	at com.facebook.react.animated.NativeAnimatedModule$ConcurrentOperationQueue.executeBatch(NativeAnimatedModule.java:147)
04-27 13:20:21.717 27102 27102 E AndroidRuntime: 	at com.facebook.react.animated.NativeAnimatedModule$3.execute(NativeAnimatedModule.java:332)
04-27 13:20:21.717 27102 27102 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue$UIBlockOperation.execute(UIViewOperationQueue.java:579)
04-27 13:20:21.717 27102 27102 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:915)
04-27 13:20:21.717 27102 27102 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1026)
04-27 13:20:21.717 27102 27102 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:47)
04-27 13:20:21.717 27102 27102 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1086)
04-27 13:20:21.717 27102 27102 E AndroidRuntime: 	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
04-27 13:20:21.717 27102 27102 E AndroidRuntime: 	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
04-27 13:20:21.717 27102 27102 E AndroidRuntime: 	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
04-27 13:20:21.717 27102 27102 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1035)
04-27 13:20:21.717 27102 27102 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:845)
04-27 13:20:21.717 27102 27102 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:775)
04-27 13:20:21.717 27102 27102 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
04-27 13:20:21.717 27102 27102 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
04-27 13:20:21.717 27102 27102 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-27 13:20:21.717 27102 27102 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
04-27 13:20:21.717 27102 27102 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
04-27 13:20:21.717 27102 27102 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7839)
04-27 13:20:21.717 27102 27102 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-27 13:20:21.717 27102 27102 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
04-27 13:20:21.717 27102 27102 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
```

But sometimes also with this one:
```
04-27 13:18:32.957 26938 26938 E AndroidRuntime: FATAL EXCEPTION: main
04-27 13:18:32.957 26938 26938 E AndroidRuntime: Process: io.evix.reactnativetvexample, PID: 26938
04-27 13:18:32.957 26938 26938 E AndroidRuntime: java.lang.RuntimeException: java.lang.IllegalArgumentException: Mapped property node does not exists
04-27 13:18:32.957 26938 26938 E AndroidRuntime: 	at com.facebook.react.animated.NativeAnimatedModule$1.doFrameGuarded(NativeAnimatedModule.java:230)
04-27 13:18:32.957 26938 26938 E AndroidRuntime: 	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
04-27 13:18:32.957 26938 26938 E AndroidRuntime: 	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
04-27 13:18:32.957 26938 26938 E AndroidRuntime: 	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
04-27 13:18:32.957 26938 26938 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1035)
04-27 13:18:32.957 26938 26938 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:845)
04-27 13:18:32.957 26938 26938 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:775)
04-27 13:18:32.957 26938 26938 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
04-27 13:18:32.957 26938 26938 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
04-27 13:18:32.957 26938 26938 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-27 13:18:32.957 26938 26938 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
04-27 13:18:32.957 26938 26938 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
04-27 13:18:32.957 26938 26938 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7839)
04-27 13:18:32.957 26938 26938 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-27 13:18:32.957 26938 26938 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
04-27 13:18:32.957 26938 26938 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
04-27 13:18:32.957 26938 26938 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: Mapped property node does not exists
04-27 13:18:32.957 26938 26938 E AndroidRuntime: 	at com.facebook.react.animated.PropsAnimatedNode.updateView(PropsAnimatedNode.java:100)
04-27 13:18:32.957 26938 26938 E AndroidRuntime: 	at com.facebook.react.animated.NativeAnimatedNodesManager.updateNodes(NativeAnimatedNodesManager.java:690)
04-27 13:18:32.957 26938 26938 E AndroidRuntime: 	at com.facebook.react.animated.NativeAnimatedNodesManager.runUpdates(NativeAnimatedNodesManager.java:597)
04-27 13:18:32.957 26938 26938 E AndroidRuntime: 	at com.facebook.react.animated.NativeAnimatedModule$1.doFrameGuarded(NativeAnimatedModule.java:214)
04-27 13:18:32.957 26938 26938 E AndroidRuntime: 	... 15 more
```

Both seem to originate from NativeAnimatedNodesManager.java.

https://user-images.githubusercontent.com/1210628/234848355-ed5b4d7c-8d4d-43fe-bba7-286567cbc70b.mp4

A reproducible example can be found here: https://github.com/wouterds/react-native-tv-example/tree/bug/animation-crash

I can't attach the .apk because it's above the limits of GitHub file upload, but crashlog, video & apk can be found here:
https://drops.evix.io/rn-crash-connectAnimatedNodes/

**Comment by dprevost-LMI** [comment]
Is this close because the bug is actually in another repo? If so anyone knows where it was forwarded?

**Comment by wouterds** [comment]
> Is this close because the bug is actually in another repo? If so, could anyone know where it was forwarded?

The bug is inside `react-native`.

**Comment by MariamIdeen** [comment]
I'm getting random crashes with react native 0.69.9 and expo 46.0.16  in devices with Android 13 and getting this error
` E  Unhandled SoftException
                 com.facebook.react.bridge.ReactNoCrashSoftException: connectAnimatedNodeToView: Animated node could not be connected to UIManager - uiManager disappeared for tag: 1147
                 	at com.facebook.react.animated.NativeAnimatedNodesManager.connectAnimatedNodeToView(NativeAnimatedNodesManager.java:411)
                 	at com.facebook.react.animated.NativeAnimatedModule$18.execute(NativeAnimatedModule.java:813)
                 	at com.facebook.react.animated.NativeAnimatedModule$ConcurrentOperationQueue.executeBatch(NativeAnimatedModule.java:147)
                 	at com.facebook.react.animated.NativeAnimatedModule$3.execute(NativeAnimatedModule.java:332)
                 	at com.facebook.react.uimanager.UIViewOperationQueue$UIBlockOperation.execute(UIViewOperationQueue.java:579)
                 	at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:915)
                 	at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1026)
                 	at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:47)
                 	at com.facebook.react.uimanager.UIViewOperationQueue$2.runGuarded(UIViewOperationQueue.java:984)
                 	at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:31)
                 	at android.os.Handler.handleCallback(Handler.java:942)
                 	at android.os.Handler.dispatchMessage(Handler.java:99)
                 	at android.os.Looper.loopOnce(Looper.java:226)
                 	at android.os.Looper.loop(Looper.java:313)
                 	at android.app.ActivityThread.main(ActivityThread.java:8757)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)`

Is this error related

**Comment by usmanmalik333** [comment]
> > > > @usmanmalik333 which version of react native are you using and on what devices (OS, OS version, brand) do you see it?
> > > 
> > > 
> > > I'm facing issue on **Android 12 devices** and I'm using **"react-native": "0.66.3"**
> > 
> > 
> > You should update to one of the later versions, it's been fixed I believe in 0.68, 0.69 or 0.70.
> 
> Okay i will try by upgrading the version

I'm still facing this issue on Android 12

**Comment by wilav-dev** [comment]
Please, i'm getting many firebase crashes on Android 12 and can't reproduce. It started after an OS update without any app update.

**Comment by usmanmalik333** [comment]
any solution for this ? @saghul @wouterds @mk0116 @gomezmark @bhavzie

**Comment by JinYuSha0** [comment]
I am still facing this problem on react-native0.71.6, this frustrates me, I developed a babel plugin that globally turns useNativeDriver to false, hope it helps [babel-plugin-rn-disable-native-divider](https://github.com/JinYuSha0/babel-plugin-rn-disable-native-divider)

**Comment by wouterds** [comment]
Setting `useNativeDriver: false` everywhere is not a solution, it's a bad workaround imo. The UX suffers greatly.

**Comment by usmanmalik333** [comment]
any solution for this ?  I have removed all the animations in the project but still facing this crash on firebase.
now I'm not using any animation in the project or useNativeDriver.
@saghul @wouterds @mk0116 @gomezmark @JinYuSha0

**Comment by wouterds** [comment]
@usmanmalik333 it's not because you don't use it your dependencies don't, e.g. react-native-screens, react-navigation, ...

**Comment by usmanmalik333** [comment]
then what is the solution for this ? 
@saghul @wouterds @mk0116 @JinYuSha0

**Comment by wouterds** [comment]
There's no solution yet, we should provide the React Native maintainers with a vanilla project [[here](https://github.com/facebook/react-native/issues/37267)] that can reproduce the issue. What I made previously is a reproducible example on the react-native-tvos fork but that's strictly speaking not exactly the same.

**Comment by wouterds** [comment]
This workaround seems to be solid and as far as I noticed it doesn't really have other side effects, but it's not a real solution or fix for the underlying problem, we're just ignoring it. https://github.com/wouterds/react-native-tv-example/commit/7639c26c468a2e4f4f51ee728b040e989a8fff0d

**Comment by mohitarora777** [comment]
<img width="1417" alt="Screenshot 2023-07-28 at 1 10 19 AM" src="https://github.com/facebook/react-native/assets/107910744/38d55167-282c-4833-bf36-c02e8d59a255">

Started facing it after we upgraded from 0.66.3 to 0.71.7, 99% on android 12

**Comment by Biplovkumar** [comment]
please reopen

**Comment by wouterds** [comment]
@Biplovkumar it's being tracked here https://github.com/facebook/react-native/issues/37267

**Comment by jorgehclinhares** [comment]
same problem here, any solution?

**Comment by guhcostan-tw** [comment]
Any solutions?

**Comment by GustMelo** [comment]
Any solutions?

**Comment by LFMAKER** [comment]
It's incredible how this error has existed for years and still without any correction.

**Comment by felansu** [comment]
> It's incredible how this error has existed for years and still without any correction.

are you available this weekend? we can fix together.

**Comment by avlaev** [comment]
We also see this crash quite often. It is our top crash. Providing a reproducible sample is not possible as we don't know what exactly causes it and it happens only from time to time for our clients. Please reopen and investigate in more detail and spend more time as the clues clearly point to an issue in the react framework.

**Comment by ErikTromp** [comment]
Same here, facing this issue regularly without any way to reproduce or fix.

**Comment by AJV2018** [comment]
any possible solution?

**Comment by jpangan** [comment]
> For me, create a new project with 0.71 and copy old codes to new one resolve this issue for me. I tried other ways:
> 
> 1. add `implementation 'androidx.work:work-runtime:2.7.1'` to build.gradle. (still in 0.71)
> 2. upgrade to 0.69.7 (with tools) and add `ReactFeatureFlags.enableSynchronizationForAnimated = true;` (not exist in 0.71) and never build success.

Can you verify this if it worked for you? In case, can you provide some ways to replicate it? Thank you.

**Comment by trungledangAxonActive** [comment]
Any updates on this one?

**Comment by Akhil-PITS** [comment]
Any update on this?

**Comment by sourabh-appinlay** [comment]
Any update ?

**Comment by deepalon** [comment]
any possible solution?
