### ISSUE TITLE
FlatList的头部出现空白

### ISSUE THREAD

**Issue by maruihi** [facebook/react-native#33709]
### Description

React Native：0.64.1
Android设备系统版本：Android 12
FlatList的horizontal=true时，把列表滑动到底部，删除其中一条数据，更新列表后，列表的头部有一块空白区域。
向上滑动列表时，列表会弹回继续显示一个空白区域。其他的系统版本是正常的，只有Android 12上运行有这个问题。

### Version

0.64.1

### Output of `npx react-native info`

System:
    OS: macOS 12.0.1
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 133.27 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.22.12 - ~/.nvm/versions/node/v12.22.12/bin/node
    Yarn: 1.22.18 - ~/.nvm/versions/node/v12.22.12/bin/yarn
    npm: 6.14.16 - ~/.nvm/versions/node/v12.22.12/bin/npm
    Watchman: 2022.03.21.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8309675
    Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_322 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.1 => 0.64.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

步骤一：
this.state = {data: [{name: '11111'}, {name: '22222'}, {name: '33333'}, {name: '44444'}, {name: '55555'}]}
<FlatList
        style={{marginTop: 10}}
        data={this.state.data}
        renderItem={this.selectedRenderItem}
        horizontal={true}
        showsHorizontalScrollIndicator={false}
        keyExtractor={this._keyExtractor}
        alwaysBounceHorizontal={false}
        alwaysBounceVertical={false}
      />
步骤二：滑动列表显示最后一项数据。
步骤三：更新data数据，比如：this.setState({data: [{name: '11111'}, {name: '22222'}, {name: '33333'}, {name: '55555'}]})。然后列表向第一条数据滑动，这是头部就会出现一个空白区域。

**Comment by cortinico** [comment]
Closing as we're accepting issue only in English. Please update the description & re-open this or a new issue 👍
