### ISSUE TITLE
Application's user data folder grows by 16MB without storing any data locally

### ISSUE THREAD

**Issue by gdjicasonjakesic** [facebook/react-native#33712]
### Description

On Android devices application's user data folder grows by 16MB without storing any data locally.

By examining the contents of the user data folder its shown that the files copied to user data are .so files from the app.

This happens only if the bundle format is used for installing, which is a recommended Android application publishing file format.

### Version

0.63.4

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 11.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 154.07 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.8.0 - ~/.nvm/versions/node/v15.8.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v15.8.0/bin/yarn
    npm: 7.5.1 - ~/.nvm/versions/node/v15.8.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK: Not Found
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Java: 14.0.2 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Create empty react-native application and build app bundle:
`./gradlew bundle
`
Install the apk from a bundle to a device by using a bundle-tool:
```
bundletool get-device-spec --output=device-spec.json
bundletool build-apks --device-spec=device-spec.json --bundle=app/build/outputs/bundle/release/app-release.aab --output=app-release.apks
bundletool install-apks --apks=app-release.apks
```

Observe the size of the installed app in settings app.
Start the app and observe the size of the installed app in settings app.
There is an increase of around 16MB in total size after the app is started. Installed app storage details show that the user data folder grew by that amount even tho the app doesn't store anything locally.

**Comment by cortinico** [comment]
That's expected and is how Android handles native libraries.
If you're intersted in knowing more about Android & .so files, this answers clarifies in details: https://stackoverflow.com/a/44704840
