### ISSUE TITLE
Watchman preventing App from loading on emulator or phone

### ISSUE THREAD

**Issue by OrcunGuler1** [facebook/react-native#33710]
### Description

Watchman:  watchman --no-pretty get-sockname returned with exit code=3221225477, signal=null, stderr=

I'm getting this error whenever I start my app by npx react-native run-android command and it get's stuck after finishing the build process. 

### Version

0.66.4

### Output of `npx react-native info`

System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Memory: 1.73 GB / 15.76 GB
  Binaries:
    Node: 14.18.1 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
    Watchman: 20220416.121541.0 - C:\ProgramData\chocolatey\bin\watchman.EXE
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version     2021.1.0.0 AI-211.7628.21.2111.8309675
    Visual Studio: 15.9.28307.1778 (Visual Studio Community 2017)
  Languages:
    Java: javac 18 - C:\Program Files\Common Files\Oracle\Java\javapath\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.66.4 => 0.66.4
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Install watchman via chocolatey,
Run the emulator or connect a device,
Run npx react-native run-android,
After metro bundler opens up in a command line interface this error will pop-up
Watchman:  watchman --no-pretty get-sockname returned with exit code=3221225477, signal=null, stderr=

**Comment by buitrbao222** [comment]
Same error. This is urgent for me. Please help.

**Comment by igardenaua** [comment]
Same issue, on:
```
OS: Windows 10 10.0.19044
Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
npm: 8.5.0 - C:\Program Files\nodejs\npm.CMD
react: 17.0.2 => 17.0.2
react-native: 0.67.3 => 0.67.3
```

Additionally, [flipper debugger](https://fbflipper.com/) could not detect watchman version even though I has installed it.

# Solution
After some digging, I noticed this may be an issue with watchman newer versions. So for me the solution was:
1. `choco uninstall watchman`
2. `choco install watchman --version 2021.01.11.00 -y`

After that, the error message disappeared & flipper detected watchman successfully.

**Comment by cipolleschi** [comment]
Hi @OrcunGuler1 and @buitrbao222, does the @musikobios proposal solves your issue? Can we close this?
