### ISSUE TITLE
TextInput flickering when format the text

### ISSUE THREAD

**Issue by aJieBai** [facebook/react-native#33711]
### Description

(url)https://github.com/facebook/react-native/issues/24585#issue-436636470
Is there any solution to the problem here

### Version

0.65.1

### Output of `npx react-native info`

System:
    OS: macOS 12.1
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 1.83 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.2 - /usr/local/bin/npm
    Watchman: 2021.12.13.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7935034
    Xcode: 13.2/13C90 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.65.1 => 0.65.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Using the code sample:

Tap the text input
Type A
Type 1 repetitively

### Snack, code example, screenshot, or link to a repository

import React from 'react';
import { StyleSheet, Text, View, TextInput } from 'react-native';

export default class App extends React.Component {
  state = {
    text: ''
  }

  render() {
    return (
      <View style={styles.container}>
        <TextInput
          value={this.state.text}
          onChangeText={text => {
            
            text = text.replace(/[0-9]/g, '')

            this.setState({
              text
            })
          }}
          style={styles.input}
        />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  input: {
    width: '90%',
    height: 50,
    borderColor: 'gray',
    borderWidth: 1
  }
});

**Comment by tj-mc** [comment]
This is simply the nature of Text Inputs and the way React Native works. Text Input is a native component, being typed into with the Native keyboard. The `onChangeText` event is fired only after a new character has been typed, at which point it has probably already been rendered on the screen. Then, JavaScript modified the value, and asks the Native Text Input to re-render. This is why we see the flicker.

To truly get around this, you'll need to make a 'Virtual' text input that does not rely on the Native Text input. However, performance will be worse, you'll need to manage many more things manually, and this goes against the general approach of React Native.

You could consider not live-editing the user's input in this way, and just showing a validation message below. Alternatively, you can display a custom keyboard that only contains the characters you want to allow. These are the strategies I've used in the past to resolve issues like this.

I'm not sure if it is technically possible, but maybe new prop on `TextInput` could make this possible at the native level, as currently there is no clean way to do this.

**Comment by cortinico** [comment]
Closing as this was addressed by @tj-mc (thanks for clarifying 🙏 )

**Comment by markendy** [comment]
Progress never stands still, so perhaps the new solution described in this question will help you! https://stackoverflow.com/questions/79253174
