### ISSUE TITLE
Upgrade react-native version to 0.68, iOS release version crash

### ISSUE THREAD

**Issue by Maty0712** [facebook/react-native#33717]
### New Version

0.68.1

### Old Version

0.61.5

### Build Target(s)

ios release

### Output of `react-native info`

info Fetching system and libraries information...
(node:79026) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
System:
    OS: macOS 12.3.1
    CPU: (8) x64 Intel(R) Core(TM) i7-8557U CPU @ 1.70GHz
    Memory: 31.14 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.8.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.5.5 - /usr/local/bin/npm
    Watchman: 2022.03.21.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8309675
    Xcode: 13.2/13C90 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.14.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: 0.68.1 => 0.68.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Issue and Reproduction Steps

*** Terminating app due to uncaught exception 'RCTFatalException: Unhandled JS Exception: Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'DevSettings' could not be found. Verify that a module by this name is registered in the native binary.', reason: 'Unhandled JS Exception: Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'DevSettings' could not be found. Verify that a module by this name is registered in the na..., stack:

**Comment by cortinico** [comment]
> TurboModuleRegistry.getEnforcing(...): 'DevSettings' could not be found

Have you enabled the New Architecture as well? If yes, please consider updating to 0.68 without the New Architecture, and enable it afterwards.

**Comment by kyle-ssg** [comment]
Any information on how this was resolved? I'm on 0.69 and can't for the life of me figure this out, I don't have fabric enabled but do have hermes enabled.

**Comment by TomSwift** [comment]
Why does `DevSettings.addMenuItem` need to be gated like this?   Looking at the sources it appear that it's gated internally and routes calls to an effective noop.
