### ISSUE TITLE
KeyboardAvoidingView pushes bottom padding of SafeAreaView above keyboard only at first autofocus

### ISSUE THREAD

**Issue by myleshk** [facebook/react-native#33720]
### Description

When `KeyboardAvoidingView` is used with `SafeAreaView` and a `TextInput` with autofocus on, when navigated to the page, it adds an extra padding above the keyboard (should be the bottom padding of `SafeAreaView`). But the padding disappears after toggling off then on the keyboard.

### Version

0.63.4, 0.68.1

### Output of `npx react-native info`

```
System:
    OS: macOS 12.3.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 568.73 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.3 - ~/.nvm/versions/node/v14.18.3/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v14.18.3/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.3/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8309675
    Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.1 => 0.68.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

iOS only.
1. navigate to the page with `KeyboardAvoidingView` & `SafeAreaView` and a `TextInput` with autofocus on. -> extra padding shown.
2. press "return" on the keyboard to hide it, then press the input to open the keyboard. -> extra padding gone.

### Snack, code example, screenshot, or link to a repository

https://snack.expo.dev/8KC3IRriM

https://user-images.githubusercontent.com/15956924/165495566-d6411a89-053d-4704-857a-bac624d693c4.mp4

**Comment by myleshk** [comment]
Just a quick hack discovered: disable auto focus, and wait for the navigation transition to finish before manually calling `focus()`.
```
useFocusEffect(useCallback(() => {
    // wait for transition animation to finish
    InteractionManager.runAfterInteractions(() => {
      refInput.current?.focus();
    })
  }, []));
```

**Comment by on-stu** [comment]
I have same problem and also solve the problem with quick hack above. thank you

**Comment by myleshk** [comment]
Just found another workaround:  
use `useSafeAreaInsets` from package `react-native-safe-area-context` and specify the safe area paddings manually, instead of using `SafeAreaView`.

Snack: https://snack.expo.dev/@mylesf/keyboardavoidingview-bug-workaround-2
