### ISSUE TITLE
Slightly transparent background color on Speed Dial causing white polygon to appear behind it (Android only)

### ISSUE THREAD

**Issue by KrisLau** [facebook/react-native#33723]
### Description

For some reason, adding a slight opacity to the background color (in this case `#E85A19C2`) seems to cause a problem on only Android where a white polygon appears behind it. I also tried making it completely transparent to see what was behind it and there seems to be a weird octagonal shadow behind it.

Left Android & right iOS
![image](https://user-images.githubusercontent.com/46275463/165530959-35824071-e00f-4572-b87f-07e570227afa.png)

With completely transparent color:
![image](https://user-images.githubusercontent.com/46275463/165535505-f7a736a8-13f7-4cb7-9d8a-fb8c47795f87.png)

### Version

`0.64.3`

### Output of `npx react-native info`

```
System:
    OS: Windows 10 10.0.19043
    CPU: (4) x64 Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz
    Memory: 2.49 GB / 15.89 GB
  Binaries:
    Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.18.1 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7199119
    Visual Studio: Not Found
  Languages:
    Java: 11.0.10
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.2 => 17.0.2
    react-native: ^0.64.2 => 0.64.3
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1. Use a SpeedDial 
2. Use `backgroundColor: #E85A19C2` in `buttonStyle` or in `color` (happens on both)

**Comment by tj-mc** [comment]
This issue is probably better raised on `react-native-elements`.

**Comment by KrisLau** [comment]
@tj-mc Oh my bad I must've accidentally opened it here! Too many tabs 🤣
