### ISSUE TITLE
 I keep getting stuck in the "http" module, is there any way to fix it?

### ISSUE THREAD

**Issue by wonkyungup** [facebook/react-native#33737]
### Description

![스크린샷 2022-04-30 오후 4 17 21](https://user-images.githubusercontent.com/34180230/166096870-d4ef0980-3d3b-454a-9d05-d1002e2713e9.png)

I keep getting stuck in the http module, is there any way to fix it?

### Version

react-native-cli: 2.0.1 react-native: 0.68.1

### Output of `npx react-native info`

System:
    OS: macOS 12.3.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 9.39 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.8.0 - /usr/local/bin/npm
    Watchman: 2022.03.21.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7621141
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.1 => 0.68.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

npm i request

npm run android / npm run ios

**Comment by wonkyungup** [comment]
'net' module not require...

**Comment by isnifer** [comment]
@wonkyungup don't use modules for nodejs. Use fetch/axios for networking

**Comment by cipolleschi** [comment]
Hi @wonkyungup have you tried with the @isnifer suggestion? 
Does it solve the issue? If yes, can we close this?
