### ISSUE TITLE
Color different in android emulator and phone compared to computer browser

### ISSUE THREAD

**Issue by ProgrammingMuffin** [facebook/react-native#33741]
### Description

I was building a simple new app from scratch using React Native and I did a `yarn start` and selected android. It built the app and ran it on the android emulator (from the android studio AVD manager). The color on my browser is different from what is being displayed on both the android emulator (in the same computer) and on my android phone.

![41a9b513-c841-41b9-b6d9-98ccf2b691f2](https://user-images.githubusercontent.com/42649107/166151699-ebd80c06-daf4-4d53-9eb4-1c2dd3ec1e35.jpg)
The above picture is a screenshot from my computer.

![69bef046-ae27-4074-99f1-ccbc6a615fb0](https://user-images.githubusercontent.com/42649107/166151708-81b6f73e-bb09-4456-bf93-11d6b23aa6b4.jpg)
The above picture is a screenshot from my phone.

Here's a snippet of the CSS

The container class is a style added to the root <view></view> component.

I tried using a simple Hex code as well and the issue still persists.

Any idea as to why this is happening? Please let me know if you need more information.

### Version

0.68.1

### Output of `npx react-native info`

```
info Fetching system and libraries information...
System:
    OS: Linux 5.13 Zorin OS 16
    CPU: (8) x64 Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
    Memory: 10.37 GB / 15.47 GB
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.14.2 - /tmp/yarn--1651418089951-0.9801791225039398/node
    Yarn: 1.22.18 - /tmp/yarn--1651418089951-0.9801791225039398/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 1.8.0_312 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.68 => 0.68.1 
  npmGlobalPackages:
    *react-native*: Not Found
Done in 1.92s.

```

### Steps to reproduce

create a new app with a container using the above mentioned color.

`yarn start`

press a to run the app on an android emulator / phone

### Snack, code example, screenshot, or link to a repository

```js
import React from 'react';
import { View, StyleSheet } from 'react-native';

export default function App() {
  return (
    <View style={styles.container} >
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'rgba(130, 106, 170, 255)',
    alignItems: 'center',
    justifyContent: 'center',
  }
});
```

**Comment by cortinico** [comment]
> I am using Scaledsheet from "react-native-size-matters" instead of Stylesheet from react-native. However, I tried changing it back to Stylesheet and the issue still persisted. So I don't think this package is the issue.

You should open the issue against "react-native-size-matters" OR provide a snippet/reproducer that doesn't use Scaledsheet to verify what's going on

**Comment by ProgrammingMuffin** [comment]
Like I mentioned, the issue is not related to `react-native-size-matters`. I understand that having third party libraries may have been confusing. So I have replaced `ScaledSheet` with `StyleSheet` and gave it a test again. Issue still persists. I have made the snippet more simpler.

**Comment by tj-mc** [comment]
If you open that web address in your android emulator, what colour does it show?

**Comment by ProgrammingMuffin** [comment]
@tj-mc Assuming you meant to run the web version of this app and use that web address in the emulator

This is what it looks like in the emulator's browser
![Screenshot from 2022-05-06 10-03-21](https://user-images.githubusercontent.com/42649107/167067678-a00991a1-fb22-4435-9de7-290bbf5771e8.png)

This is what it looks like in the computer's browser.
![Screenshot from 2022-05-06 10-05-44](https://user-images.githubusercontent.com/42649107/167067761-060c9860-cf6f-49a0-b512-88447538afe4.png)

It seems that it's not the problem of the APK but something to do with any android device.

Thank you for your reply.

**Comment by tj-mc** [comment]
Great, at least we know it's not an issue with react native.

**Comment by cipolleschi** [comment]
Issue is not related to React Native, closing it.
