### ISSUE TITLE
Error: Cannot find module '@babel/parser'

### ISSUE THREAD

**Issue by Kay-Titulaer** [facebook/react-native#33748]
### Description

When running `npx react-native init myApp` it insalls all dependencies but eventually it will return `Error: Cannot find module '@babel/parser'`

### Version

i dont know. latest i supose

### Output of `npx react-native info`

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '@babel/parser'
Require stack:
- C:\Users\titul\AppData\Local\npm-cache\_npx\7930a8670f922cdb\node_modules\metro\src\Bundler\util.js
- C:\Users\titul\AppData\Local\npm-cache\_npx\7930a8670f922cdb\node_modules\metro\src\Assets.js
- C:\Users\titul\AppData\Local\npm-cache\_npx\7930a8670f922cdb\node_modules\metro\src\Server.js
- C:\Users\titul\AppData\Local\npm-cache\_npx\7930a8670f922cdb\node_modules\metro\src\shared\output\bundle.js
- C:\Users\titul\AppData\Local\npm-cache\_npx\7930a8670f922cdb\node_modules\@react-native-community\cli-plugin-metro\build\commands\bundle\buildBundle.js
- C:\Users\titul\AppData\Local\npm-cache\_npx\7930a8670f922cdb\node_modules\@react-native-community\cli-plugin-metro\build\commands\bundle\bundle.js
- C:\Users\titul\AppData\Local\npm-cache\_npx\7930a8670f922cdb\node_modules\@react-native-community\cli-plugin-metro\build\commands\bundle\index.js
- C:\Users\titul\AppData\Local\npm-cache\_npx\7930a8670f922cdb\node_modules\@react-native-community\cli-plugin-metro\build\commands\index.js
- C:\Users\titul\AppData\Local\npm-cache\_npx\7930a8670f922cdb\node_modules\@react-native-community\cli-plugin-metro\build\index.js
- C:\Users\titul\AppData\Local\npm-cache\_npx\7930a8670f922cdb\node_modules\@react-native-community\cli\build\commands\index.js
- C:\Users\titul\AppData\Local\npm-cache\_npx\7930a8670f922cdb\node_modules\@react-native-community\cli\build\index.js
- C:\Users\titul\AppData\Local\npm-cache\_npx\7930a8670f922cdb\node_modules\@react-native-community\cli\build\bin.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\titul\AppData\Local\npm-cache\_npx\7930a8670f922cdb\node_modules\metro\src\Bundler\util.js:12:17)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\titul\\AppData\\Local\\npm-cache\\_npx\\7930a8670f922cdb\\node_modules\\metro\\src\\Bundler\\util.js',
    'C:\\Users\\titul\\AppData\\Local\\npm-cache\\_npx\\7930a8670f922cdb\\node_modules\\metro\\src\\Assets.js',
    'C:\\Users\\titul\\AppData\\Local\\npm-cache\\_npx\\7930a8670f922cdb\\node_modules\\metro\\src\\Server.js',
    'C:\\Users\\titul\\AppData\\Local\\npm-cache\\_npx\\7930a8670f922cdb\\node_modules\\metro\\src\\shared\\output\\bundle.js',
    'C:\\Users\\titul\\AppData\\Local\\npm-cache\\_npx\\7930a8670f922cdb\\node_modules\\@react-native-community\\cli-plugin-metro\\build\\commands\\bundle\\buildBundle.js',
    'C:\\Users\\titul\\AppData\\Local\\npm-cache\\_npx\\7930a8670f922cdb\\node_modules\\@react-native-community\\cli-plugin-metro\\build\\commands\\bundle\\bundle.js',
    'C:\\Users\\titul\\AppData\\Local\\npm-cache\\_npx\\7930a8670f922cdb\\node_modules\\@react-native-community\\cli-plugin-metro\\build\\commands\\bundle\\index.js',
    'C:\\Users\\titul\\AppData\\Local\\npm-cache\\_npx\\7930a8670f922cdb\\node_modules\\@react-native-community\\cli-plugin-metro\\build\\commands\\index.js',
    'C:\\Users\\titul\\AppData\\Local\\npm-cache\\_npx\\7930a8670f922cdb\\node_modules\\@react-native-community\\cli-plugin-metro\\build\\index.js',
    'C:\\Users\\titul\\AppData\\Local\\npm-cache\\_npx\\7930a8670f922cdb\\node_modules\\@react-native-community\\cli\\build\\commands\\index.js',
    'C:\\Users\\titul\\AppData\\Local\\npm-cache\\_npx\\7930a8670f922cdb\\node_modules\\@react-native-community\\cli\\build\\index.js',
    'C:\\Users\\titul\\AppData\\Local\\npm-cache\\_npx\\7930a8670f922cdb\\node_modules\\@react-native-community\\cli\\build\\bin.js'
  ]
}

### Steps to reproduce

run `npx react-native init myApp`

**Comment by kaytitulaer2008** [comment]
brand new app

**Comment by cipolleschi** [comment]
Hi @Kay-Titulaer! 

To check which version of react-native you are installing, you can do something like:
`grep \"react-native\": AwesomeProject/package.json`
And get an answer.

Is this issue still valid? Could you try it again, please?

**Comment by Ammar2882** [comment]
facing the same issue

**Comment by AXiLiYa** [comment]
I also met this problem. I just follow the guide execute`npx react-native init AwesomeTSProject --template react-native-template-typescript`. And the error log is same with this issue. I check the node version is v16.15.

**Comment by AXiLiYa** [comment]
> Hi @Kay-Titulaer!
> 
> To check which version of react-native you are installing, you can do something like: `grep \"react-native\": AwesomeProject/package.json` And get an answer.
> 
> Is this issue still valid? Could you try it again, please?

I try this command. It's no use. Because there is no AwesomeProject directory and package.json file.

**Comment by AXiLiYa** [comment]
It seems node_modules's problem. I go to the npx directory in the error log(in my Mac is `~/.npm/_npx/7930a8670f922cdb`). And I execute

 ```shell
rm -rf the node_modules
rm package-lock.json
npm i
```
 
Then it can init project correctly.

**Comment by cortinico** [comment]
> Then it can init project correctly

Closing as the original author is unresponsive + there is a suggested workaround
