### ISSUE TITLE
ActionSheetIOS text tint color

### ISSUE THREAD

**Issue by iSimar** [facebook/react-native#3374]
Enhancement Suggestion - text tint color prop for ActionSheetIOS

**Comment by admmasters** [comment]
Hmmm - we should probably look at changing ActionSheetIOS's current implementation as it currently relies on UIActionSheet which was deprecated in iOS8. https://developer.apple.com/library/prerelease/ios/documentation/UIKit/Reference/UIActionSheet_Class/index.html changing the tint colour is trivial if we rely upon UIAlertController instead.

**Comment by christopherdro** [comment]
@admmasters Actionsheet with UIAlertcontroller has been implemented.

I played around a bit with setting the tint color on both action sheet and alert and it seems fairly straightforward. Just need to find a good way to expose this as props.

If anyone else manages to tackle this before me, make sure to set the tintColor AFTER presenting the view to the user. If not, the highlight tint of the buttons defaults back to blue regardless of the custom tintColor set.
