### ISSUE TITLE
Navigator flicker on push/pop

### ISSUE THREAD

**Issue by pangers** [facebook/react-native#3375]
There seems to be a white flicker across the top area of the screen whenever I push or pop from screen to screen using Navigator (NOT NavigatorIOS). It happens most of the time (maybe 70%) and of course is especially visible when the background color is not white. 

Has anyone else experienced this?

**Comment by abasak** [comment]
I am also seeing the same issue. I am using a `ToolbarAndroid` component with a dark background and the `configureScene` property for the `Navigator` is set to `Navigator.SceneConfigs.FadeAndroid`.

**Comment by aintnorest** [comment]
Same here as well. I also can't seem to change the animation. No matter what i return in configureScene I'm always just seeing a flicker of white as the transition between.

**Comment by lananelson** [comment]
I had the same issue which I was able to resolve by adding
```
sceneStyle={{ backgroundColor: 'transparent }}
```
property to `Navigator`

**Comment by grabbou** [comment]
@facebook-github-bot answered

**Comment by grabbou** [comment]
PS. If any of you feels like this is a bug - you can follow @lananelson reference fix in one of his projects, which should work
