### ISSUE TITLE
xcode archive report error: symbol(s) not found for architecture arm64

### ISSUE THREAD

**Issue by see** [facebook/react-native#33753]
### Description

Ld /Users/ying/Library/Developer/Xcode/DerivedData/RNApp-adjfeodugpcmenehbfjntjeibrdr/Build/Intermediates.noindex/ArchiveIntermediates/RNApp/InstallationBuildProductsLocation/Applications/RNApp.app/RNApp normal (in target 'RNApp' from project 'RNApp')
    cd /Users/ying/RNApp/ios
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -target arm64-apple-ios11.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.4.sdk -L/Users/ying/Library/Developer/Xcode/DerivedData/RNApp-adjfeodugpcmenehbfjntjeibrdr/Build/Intermediates.noindex/ArchiveIntermediates/RNApp/BuildProductsPath/Release-iphoneos -L/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.4.sdk/usr/lib/swift -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos -L/Users/ying/Library/Developer/Xcode/DerivedData/RNApp-adjfeodugpcmenehbfjntjeibrdr/Build/Intermediates.noindex/ArchiveIntermediates/RNApp/BuildProductsPath/Release-iphoneos/CocoaAsyncSocket -L/Users/ying/Library/Developer/Xcode/DerivedData/RNApp-adjfeodugpcmenehbfjntjeibrdr/Build/Intermediates.noindex/ArchiveIntermediates/RNApp/BuildProductsPath/Release-iphoneos/DoubleConversion -L/Users/ying/Library/Developer/Xcode/DerivedData/RNApp-adjfeodugpcmenehbfjntjeibrdr/Build/Intermediates.noindex/ArchiveIntermediates/RNApp/BuildProductsPath/Release-iphoneos/RCT-Folly -L/Users/ying/Library/Developer/Xcode/DerivedData/RNApp-adjfeodugpcmenehbfjntjeibrdr/Build/Intermediates.noindex/ArchiveIntermediates/RNApp/BuildProductsPath/Release-iphoneos/RCTTypeSafety -L/Users/ying/Library/Developer/Xcode/DerivedData/RNApp-adjfeodugpcmenehbfjntjeibrdr/Build/Intermediates.noindex/ArchiveIntermediates/RNApp/BuildProductsPath/Release-iphoneos/React-Codegen -L/Users/ying/Library/Developer/Xcode/DerivedData/RNApp-adjfeodugpcmenehbfjntjeibrdr/Build/Intermediates.noindex/ArchiveIntermediates/RNApp/BuildProductsPath/Release-iphoneos/React-Core -L/Users/ying/Library/Developer/Xcode/DerivedData/RNApp-adjfeodugpcmenehbfjntjeibrdr/Build/Intermediates.noindex/ArchiveIntermediates/RNApp/BuildProductsPath/Release-iphoneos/React-CoreModules -L/Users/ying/Library/Developer/Xcode/DerivedData/RNApp-adjfeodugpcmenehbfjntjeibrdr/Build/Intermediates.noindex/ArchiveIntermediates/RNApp/BuildProductsPath/Release-iphoneos/React-Fabric -L/Users/ying/Library/Developer/Xcode/DerivedData/RNApp-adjfeodugpcmenehbfjntjeibrdr/Build/Intermediates.noindex/ArchiveIntermediates/RNApp/BuildProductsPath/Release-iphoneos/React-RCTAnimation -L/Users/ying/Library/Developer/Xcode/DerivedData/RNApp-adjfeodugpcmenehbfjntjeibrdr/Build/Intermediates.noindex/ArchiveIntermediates/RNApp/BuildProductsPath/Release-iphoneos/React-RCTBlob -L/Users/ying/Library/Developer/Xcode/DerivedData/RNApp-adjfeodugpcmenehbfjntjeibrdr/Build/Intermediates.noindex/ArchiveIntermediates/RNApp/BuildProductsPath/Release-iphoneos/React-RCTFabric -L/Users/ying/Library/Developer/Xcode/DerivedData/RNApp-adjfeodugpcmenehbfjntjeibrdr/Build/Intermediates.noindex/ArchiveIntermediates/RNApp/BuildProductsPath/Release-iphoneos/React-RCTImage -L/Users/ying/Library/Developer/Xcode/DerivedData/RNApp-adjfeodugpcmenehbfjntjeibrdr/Build/Intermediates.noindex/ArchiveIntermediates/RNApp/BuildProductsPath/Release-iphoneos/React-RCTLinking -L/Users/ying/Library/Developer/Xcode/DerivedData/RNApp-adjfeodugpcmenehbfjntjeibrdr/Build/Intermediates.noindex/ArchiveIntermediates/RNApp/BuildProductsPath/Release-iphoneos/React-RCTNetwork -L/Users/ying/Library/Developer/Xcode/DerivedData/RNApp-adjfeodugpcmenehbfjntjeibrdr/Build/Intermediates.noindex/ArchiveIntermediates/RNApp/BuildProductsPath/Release-iphoneos/React-RCTSettings -L/Users/ying/Library/Developer/Xcode/DerivedData/RNApp-adjfeodugpcmenehbfjntjeibrdr/Build/Intermediates.noindex/ArchiveIntermediates/RNApp/BuildProductsPath/Release-iphoneos/React-RCTText -L/Users/ying/Library/Developer/Xcode/DerivedData/RNApp-adjfeodugpcmenehbfjntjeibrdr/Build/Intermediates.noindex/ArchiveIntermediates/RNApp/BuildProductsPath/Release-iphoneos/React-RCTVibration -L/Users/ying/Library/Developer/Xcode/DerivedData/RNApp-adjfeodugpcmenehbfjntjeibrdr/Build/Intermediates.noindex/ArchiveIntermediates/RNApp/BuildProductsPath/Release-iphoneos/React-cxxreact -L/Users/ying/Library/Developer/Xcode/DerivedData/RNApp-adjfeodugpcmenehbfjntjeibrdr/Build/Intermediates.noindex/ArchiveIntermediates/RNApp/BuildProductsPath/Release-iphoneos/React-graphics -L/Users/ying/Library/Developer/Xcode/DerivedData/RNApp-adjfeodugpcmenehbfjntjeibrdr/Build/Intermediates.noindex/ArchiveIntermediates/RNApp/BuildProductsPath/Release-iphoneos/React-hermes -L/Users/ying/Library/Developer/Xcode/DerivedData/RNApp-adjfeodugpcmenehbfjntjeibrdr/Build/Intermediates.noindex/ArchiveIntermediates/RNApp/BuildProductsPath/Release-iphoneos/React-jsi -L/Users/ying/Library/Developer/Xcode/DerivedData/RNApp-adjfeodugpcmenehbfjntjeibrdr/Build/Intermediates.noindex/ArchiveIntermediates/RNApp/BuildProductsPath/Release-iphoneos/React-jsiexecutor -L/Users/ying/Library/Developer/Xcode/DerivedData/RNApp-adjfeodugpcmenehbfjntjeibrdr/Build/Intermediates.noindex/ArchiveIntermediates/RNApp/BuildProductsPath/Release-iphoneos/React-jsinspector -L/Users/ying/Library/Developer/Xcode/DerivedData/RNApp-adjfeodugpcmenehbfjntjeibrdr/Build/Intermediates.noindex/ArchiveIntermediates/RNApp/BuildProductsPath/Release-iphoneos/React-logger -L/Users/ying/Library/Developer/Xcode/DerivedData/RNApp-adjfeodugpcmenehbfjntjeibrdr/Build/Intermediates.noindex/ArchiveIntermediates/RNApp/BuildProductsPath/Release-iphoneos/React-perflogger -L/Users/ying/Library/Developer/Xcode/DerivedData/RNApp-adjfeodugpcmenehbfjntjeibrdr/Build/Intermediates.noindex/ArchiveIntermediates/RNApp/BuildProductsPath/Release-iphoneos/ReactCommon -L/Users/ying/Library/Developer/Xcode/DerivedData/RNApp-adjfeodugpcmenehbfjntjeibrdr/Build/Intermediates.noindex/ArchiveIntermediates/RNApp/BuildProductsPath/Release-iphoneos/SocketRocket -L/Users/ying/Library/Developer/Xcode/DerivedData/RNApp-adjfeodugpcmenehbfjntjeibrdr/Build/Intermediates.noindex/ArchiveIntermediates/RNApp/BuildProductsPath/Release-iphoneos/Yoga -L/Users/ying/Library/Developer/Xcode/DerivedData/RNApp-adjfeodugpcmenehbfjntjeibrdr/Build/Intermediates.noindex/ArchiveIntermediates/RNApp/BuildProductsPath/Release-iphoneos/YogaKit -L/Users/ying/Library/Developer/Xcode/DerivedData/RNApp-adjfeodugpcmenehbfjntjeibrdr/Build/Intermediates.noindex/ArchiveIntermediates/RNApp/BuildProductsPath/Release-iphoneos/fmt -L/Users/ying/Library/Developer/Xcode/DerivedData/RNApp-adjfeodugpcmenehbfjntjeibrdr/Build/Intermediates.noindex/ArchiveIntermediates/RNApp/BuildProductsPath/Release-iphoneos/glog -L/Users/ying/Library/Developer/Xcode/DerivedData/RNApp-adjfeodugpcmenehbfjntjeibrdr/Build/Intermediates.noindex/ArchiveIntermediates/RNApp/BuildProductsPath/Release-iphoneos/libevent -L/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.4.sdk/usr/lib/swift -F/Users/ying/Library/Developer/Xcode/DerivedData/RNApp-adjfeodugpcmenehbfjntjeibrdr/Build/Intermediates.noindex/ArchiveIntermediates/RNApp/BuildProductsPath/Release-iphoneos -F/Users/ying/RNApp/ios/Pods/hermes-engine/destroot/Library/Frameworks/universal -F/Users/ying/Library/Developer/Xcode/DerivedData/RNApp-adjfeodugpcmenehbfjntjeibrdr/Build/Intermediates.noindex/ArchiveIntermediates/RNApp/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/hermes-engine -filelist /Users/ying/Library/Developer/Xcode/DerivedData/RNApp-adjfeodugpcmenehbfjntjeibrdr/Build/Intermediates.noindex/ArchiveIntermediates/RNApp/IntermediateBuildFilesPath/RNApp.build/Release-iphoneos/RNApp.build/Objects-normal/arm64/RNApp.LinkFileList -Xlinker -rpath -Xlinker /usr/lib/swift -Xlinker -rpath -Xlinker @executable_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/ying/Library/Developer/Xcode/DerivedData/RNApp-adjfeodugpcmenehbfjntjeibrdr/Build/Intermediates.noindex/ArchiveIntermediates/RNApp/IntermediateBuildFilesPath/RNApp.build/Release-iphoneos/RNApp.build/Objects-normal/arm64/RNApp_lto.o -fembed-bitcode -Xlinker -bitcode_verify -Xlinker -bitcode_hide_symbols -Xlinker -bitcode_symbol_map -Xlinker /Users/ying/Library/Developer/Xcode/DerivedData/RNApp-adjfeodugpcmenehbfjntjeibrdr/Build/Intermediates.noindex/ArchiveIntermediates/RNApp/BuildProductsPath/Release-iphoneos -Xlinker -final_output -Xlinker /Applications/RNApp.app/RNApp -fobjc-arc -fobjc-link-runtime -ObjC -lCocoaAsyncSocket -lDoubleConversion -lRCT-Folly -lRCTTypeSafety -lReact-Codegen -lReact-Core -lReact-CoreModules -lReact-Fabric -lReact-RCTAnimation -lReact-RCTBlob -lReact-RCTFabric -lReact-RCTImage -lReact-RCTLinking -lReact-RCTNetwork -lReact-RCTSettings -lReact-RCTText -lReact-RCTVibration -lReact-cxxreact -lReact-graphics -lReact-hermes -lReact-jsi -lReact-jsiexecutor -lReact-jsinspector -lReact-logger -lReact-perflogger -lReactCommon -lSocketRocket -lYoga -lYogaKit -lc++ -lc++abi -lfmt -lglog -licucore -llibevent -framework AudioToolbox -framework CFNetwork -framework JavaScriptCore -framework MobileCoreServices -framework Security -framework UIKit -framework hermes -ObjC -lc++ -lPods-RNApp -Xlinker -no_adhoc_codesign -Xlinker -dependency_info -Xlinker /Users/ying/Library/Developer/Xcode/DerivedData/RNApp-adjfeodugpcmenehbfjntjeibrdr/Build/Intermediates.noindex/ArchiveIntermediates/RNApp/IntermediateBuildFilesPath/RNApp.build/Release-iphoneos/RNApp.build/Objects-normal/arm64/RNApp_dependency_info.dat -o /Users/ying/Library/Developer/Xcode/DerivedData/RNApp-adjfeodugpcmenehbfjntjeibrdr/Build/Intermediates.noindex/ArchiveIntermediates/RNApp/InstallationBuildProductsLocation/Applications/RNApp.app/RNApp

Undefined symbols for architecture arm64:
  "folly::SharedMutexImpl<false, void, std::__1::atomic, false, false, false>::deferredReaders", referenced from:
      void folly::SharedMutexImpl<false, void, std::__1::atomic, false, false, false>::applyDeferredReaders<folly::SharedMutexImpl<false, void, std::__1::atomic, false, false, false>::WaitForever>(unsigned int&, folly::SharedMutexImpl<false, void, std::__1::atomic, false, false, false>::WaitForever&) in AppDelegate.o
      void folly::SharedMutexImpl<false, void, std::__1::atomic, false, false, false>::applyDeferredReaders<folly::SharedMutexImpl<false, void, std::__1::atomic, false, false, false>::WaitForever>(unsigned int&, folly::SharedMutexImpl<false, void, std::__1::atomic, false, false, false>::WaitForever&, unsigned int) in AppDelegate.o
  "folly::SharedMutexImpl<false, void, std::__1::atomic, false, false, false>::unlock()", referenced from:
      std::__1::unique_lock<folly::SharedMutexImpl<false, void, std::__1::atomic, false, false, false> >::~unique_lock() in AppDelegate.o
  "folly::SharedMutexImpl<false, void, std::__1::atomic, false, false, false>::~SharedMutexImpl()", referenced from:
      std::__1::__shared_ptr_emplace<facebook::react::ContextContainer const, std::__1::allocator<facebook::react::ContextContainer const> >::__on_zero_shared() in AppDelegate.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

### Version

0.68.1

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 12.3.1
    CPU: (6) x64 Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz
    Memory: 15.28 GB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.19.1 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 6.14.2 - /usr/local/bin/npm
    Watchman: 2022.03.21.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8309675
    Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.14 - /Library/Java/JavaVirtualMachines/jdk-11.0.14.jdk/Contents/Home/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.1 => 0.68.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

https://github.com/see/rn-action-test

### Snack, code example, screenshot, or link to a repository

https://github.com/see/rn-action-test

**Comment by cipolleschi** [comment]
Hi @see! It looks like you are having issues with Folly.

Have you tried to: 
1. Add [these flags](https://reactnative.dev/docs/next/new-architecture-app-intro#ios-turbomodules-ensure-your-app-provides-an-rctcxxbridgedelegate) -> scroll down to `## iOS: Setup Folly`
2. Update to version 0.68.2?

**Comment by see** [comment]
The second rule works for me.
