### ISSUE TITLE
AppClip Size too big

### ISSUE THREAD

**Issue by SaruwatariSagittario** [facebook/react-native#33757]
### Description

So, i have been trying to release some AppClip using React Native as the base since I wanted to create some mini introduction to the already released app of mine... The problem when i trying to do this was when i'm about to launch it to the AppStore, apple rejected it because after Apple process my AppClip, the size is become more then 10MB, even though previously when about to publish it it's around 9,8 something MB... 
So, my question was, does anybody have similar experience regarding AppClip in ReactNative, if so what you do to pass it? 

Thanks

### Version

0.66.4

### Output of `npx react-native info`

System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 596.56 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.2/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.13 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.4 => 0.66.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. Create new React Native project, run the yarn/npm install
2. add new AppClip target
3. append the appclip target to podfile, and do the pod install
4. put code below on the AppClip RCTRootView
`- (void)loadView {

  NSURL *jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index.appclip" fallbackResource:nil];

  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"AppClip"
                                               initialProperties:nil
                                                   launchOptions:nil];
  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];
  
  self.view = rootView;

}`
5. create index.appclip.js in the project 
`import { AppRegistry, View, Text, Button } from 'react-native';
import React from 'react';
const AppClip = () => (
    <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
        <Text style={{ fontSize: 22 }}>
            React Native App Clip
      </Text>
        <Button
            title="Learn More"
            color="#841584"
        />
    </View>
);

AppRegistry.registerComponent('AppClip', () => AppClip);`

6. Upon run and tested fine, try to archive it 
7. Afterwards try to release it on Apple AppStore, i have been trying with my project that have some library used for the purpose of the AppClip and kept getting the size too big problem

**Comment by tj-mc** [comment]
I have experimented with this for a Hackathon project, and Shopify [have a great blog article](https://shopify.engineering/building-app-clip-react-native) on their experience with RN app clips. However, even with their optimisations:

> Our final App Clip size was 9.1MB, just shy of the 10MB limit. Having such a hard constraint was a fun challenge. We managed to build most of what we initially had in mind, and there are further optimizations we can still make.

Your best options would be to slim the down the libraries / content in your app clip, or rewrite it in Native. Unfortunately, there's not much else we can do to reduce the size of RN at the moment.

App Clips are not really the intended use of RN so this ticket probably doesn't have a resolution. Hope that helps 😄
