### ISSUE TITLE
react-native app shows this error while running on a Mac Machine (M1) Parameter specified as non-null is null

### ISSUE THREAD

**Issue by emadbaqeri** [facebook/react-native#33759]
### Description

I have started a project with a linux machine (Ubuntu 20.04) and everything was going really well, While I have changed to Mac Machine I'm seeing this error while try to run the app.
I'm using latest version of `Monterey version 12.3.1`, trying to compile the application with the `android api 30` and I'm have test real devices and emulators.
The `react-native version` is `0.67.2`, I should also mention that I everything works fine while I'm trying to run the app on the same old Linux machine.
```bash 
Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter,parameterurl
```
This is the screenshot for the error I'm getting:

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/GoLLn.png

### Version

0.67.2

### Output of `npx react-native info`

System:
    OS: macOS 12.3.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 95.05 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.19.1 - ~/.nvm/versions/node/v14.19.1/bin/node
    Yarn: 1.22.18 - ~/.nvm/versions/node/v14.19.1/bin/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v14.19.1/bin/npm
    Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: Bumblebee 2021.1.1 Patch 2 Bumblebee 2021.1.1 Patch 2
    Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.67.2 => 0.67.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Just try to run the project as you do,
```markdown
1. npm install
2. npm start
3. npm run android
```
I'm getting this output which says that the build is successful,
```bash
BUILD SUCCESSFUL in 43s
359 actionable tasks: 10 executed, 349 up-to-date
info Connecting to the development server...
info Starting the app on "emulator-5554"...
Starting: Intent { cmp=com.dummy/.MainActivity }
✨  Done in 48.37s.
```
But as I have mentioned above I face with the page that I have attached the screen shot.

**Comment by emadbaqeri** [comment]
> ```shell
> ```shell
> Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter,parameterurl
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> 
> You most likely have a stacktrace in adb logcat. It seems like you have a parameterurl which was null while it should have not been null.
> Without the stacktrace we can't debug this further
> ```

Hi @cortinico, thanks for your quick reply.
Will share the log from adb in couple of minutes,

**Comment by emadbaqeri** [comment]
@cortinico sorry how am I supposed the prepare the log file for you? I'm not really familiar with `adb` tool.

**Comment by emadbaqeri** [comment]
I hope this helps
[file.txt](https://github.com/facebook/react-native/files/8622220/file.txt)

**Comment by cortinico** [comment]
Yup it does. The stacktrace is:
```
05-04 20:42:08.405  4430  4509 E unknown:ReactNative: Exception in native call
05-04 20:42:08.405  4430  4509 E unknown:ReactNative: java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter url
05-04 20:42:08.405  4430  4509 E unknown:ReactNative:   at okhttp3.Request$Builder.url(Unknown Source:2)
05-04 20:42:08.405  4430  4509 E unknown:ReactNative:   at com.facebook.react.modules.websocket.WebSocketModule.connect(WebSocketModule.java:98)
05-04 20:42:08.405  4430  4509 E unknown:ReactNative:   at java.lang.reflect.Method.invoke(Native Method)
05-04 20:42:08.405  4430  4509 E unknown:ReactNative:   at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
05-04 20:42:08.405  4430  4509 E unknown:ReactNative:   at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
05-04 20:42:08.405  4430  4509 E unknown:ReactNative:   at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
05-04 20:42:08.405  4430  4509 E unknown:ReactNative:   at android.os.Handler.handleCallback(Handler.java:938)
05-04 20:42:08.405  4430  4509 E unknown:ReactNative:   at android.os.Handler.dispatchMessage(Handler.java:99)
05-04 20:42:08.405  4430  4509 E unknown:ReactNative:   at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
05-04 20:42:08.405  4430  4509 E unknown:ReactNative:   at android.os.Looper.loop(Looper.java:223)
05-04 20:42:08.405  4430  4509 E unknown:ReactNative:   at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
05-04 20:42:08.405  4430  4509 E unknown:ReactNative:   at java.lang.Thread.run(Thread.java:923)
```

You're trying to connect to a WebSocket, and you're not passing the URL. So the app dies here: https://github.com/facebook/react-native/blob/709a459b1ef7968d447c0a5dbe5cd44d1e03fcb4/ReactAndroid/src/main/java/com/facebook/react/modules/websocket/WebSocketModule.java#L98

(The exception is raised by network library).

**Comment by emadbaqeri** [comment]
Thanks, but this is another thing that I have no idea.
I'm using Graphql and Apollo client, which I have a web socket connection there. It seems that everything is okay by my side.
And I'm using Fire Base package like `fire-base-messaging`.
What do you think about this. you think the problem should be on Graphql side which I'm connecting to a web socket. or maybe a web socket maybe firebase libraries rely on

**Comment by cortinico** [comment]
> I'm using Graphql and Apollo client, which I have a web socket connection there. It seems that everything is okay by my side.
> And I'm using Fire Base package like `fire-base-messaging`.

I don't have enough context to tell you where is the problem, but is definitely not related to  React Native. My suggestion is to try to exclude some of those libraries and try to bisect where the error is happening.

You should also consider opening an issue on the issue tracker of those projects you metnioned, as they have more context than us on this problem.

Closign as this is unrelated to RN, feel free to reopen if the issue persists.

**Comment by emadbaqeri** [comment]
Thanks for your help, the problem is solved and trying to know which package is exactly causing the problem.

**Comment by yonasyenew** [comment]
> Thanks for your help, the problem is solved and trying to know which package is exactly causing the problem.

can you tell us how you fix it?

**Comment by mikemangas** [comment]
@emadbaqeri how did you solve it?

**Comment by vladimirevstratov** [comment]
try to update library
