### ISSUE TITLE
React Native App Causing Phone to heat up extensively

### ISSUE THREAD

**Issue by Jaybee4real** [facebook/react-native#33750]
### Description

I have a react native app that worked seamlessly fine on android and ios a few days ago (no lags or slowdowns)

Until recently, I started noticing that mostly ios devices complain that their phones heat up immediately they enter into my app

Has anyone experienced such an issue before?, and If so what to do to fix it, I am memorizing most components and am caching some images that will render in my app multiple times as optimization efforts but the stats remain the same

I wish I had more info on this but this issue only surfaced when I had gone far into building the app

Below are some of the stats for the app from Xcode

**Memory Usage from xcode** 
<img width="241" alt="Screenshot 2022-05-03 at 16 27 09" src="https://user-images.githubusercontent.com/51276685/166484512-a0fa2876-bac7-415c-b2ac-24e58b5b430d.png">

**Cpu usage from xcode**
<img width="865" alt="Cpu usage from xcode" src="https://user-images.githubusercontent.com/51276685/166440934-46264584-5a83-42f1-804f-98fde90f37e0.png">

**Cpu usage from profiler**
<img width="1411" alt="Cpu usage from profiler" src="https://user-images.githubusercontent.com/51276685/166441017-7de00b6a-2c4b-4921-ba95-fabe8be59eda.png">

**Suspected Select Culprit**
<img width="1680" alt="Suspected Selected Culprit" src="https://user-images.githubusercontent.com/51276685/166441163-6afef99a-6ee3-42a5-8cf6-090f3ba9a8e3.png">

**More info about suspected selected culprit**
<img width="955" alt="Screenshot 2022-05-03 at 11 33 38" src="https://user-images.githubusercontent.com/51276685/166441238-d982e22e-046d-45cd-ade3-49e19a338430.png">

**Linked StackOverflow Issue**
https://stackoverflow.com/questions/72087926/react-native-app-causing-phone-to-heat-up-extensively?noredirect=1#comment127374016_72087926

### Version

0.68.1

### Output of `npx react-native info`

System:
    OS: macOS 12.1
    CPU: (8) arm64 Apple M1
    Memory: 101.39 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.8.0 - /opt/homebrew/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 8.5.5 - /opt/homebrew/bin/npm
    Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8309675
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.14.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.2 => 17.0.2 
    react-native: ^0.68.1 => 0.68.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

**

**Comment by Jaybee4real** [comment]
Update::

Just commented out all my useEffects in the codebase and it seems as if the app is stable and not heating up anymore
my bad.

**Comment by ddeschenes-lacapitale** [comment]
I have the same issue. How commenting out all useEffect could resolve this ? Do you have any clue why this happens ?

**Comment by Jaybee4real** [comment]
Sorry @ddeschenes-lacapitale forgot to post an update here too

UPDATE: I solved this issue, there were a number of reasons why it started

- I had an animation running in the background because a useEffect function cleanup did not stop the animation when navigating away from the screen 

- I had numerous useFocusEffect without a React.useCallback function so the useFocusEffect would have had a cleanup function through the React.useCallback

- Some useEffect functions had no cleanup- During the time I was facing the issue, I changed ALL (about 420 in total) of my components and screens from normal components to memoized (React.memo) which means that all my components were being stored in memory as soon as they rendered - which is bad because it obviously causes high RAM usage, so we had to delete those - and only use them on about 2 components that rendered multiple times and had costly computations that didn't need to run every time they rendered

After doing all of that, my CPU and memory usage drastically reduced to what it is below

![New CPU and memory usage](https://user-images.githubusercontent.com/51276685/170435278-ac0e88e4-7525-4771-9d3b-5f5fc85a88ad.png)

**Comment by jackimatin** [comment]
same issue
@Jaybee4real

can you explain it more?
is it possible to help me?

**Comment by Jaybee4real** [comment]
@jackimatin, sure, if you are still experiencing it, reach out to me via mail: okorojijaybee1@gmail.com

**Comment by jackimatin** [comment]
thank a lot,@Jaybee4real
I did it and everything is great now.

**Comment by ravikumarhb** [comment]
@jackimatin can you share what were the fixes.. any snippets can help ..

**Comment by Surender-m** [comment]
Hi @Jaybee4real , we are facing the exact similar issue what you have posted here,  surprisingly this is happening on iOS 17 and above devices only with our react native application which is built using React Native 0.72.0, any help will be highly appreciated. 
Thank you!
https://stackoverflow.com/questions/78049075/how-to-identify-and-fix-device-heat-in-ios-application-developed-using-react-nat
