### ISSUE TITLE
how to disable the top tooltip when run app on a real device

### ISSUE THREAD

**Issue by jabez128** [facebook/react-native#3376]
When I run my app on a real device, when app start up, there is a tooltip appear on the top say "Loading from pre-bundled file...", after 1 or 2 seconds, it will disappear. 

how to disable this tooltip. thanx!

**Comment by ide** [comment]
The notice hides itself in release builds or you can look at `RCTDevLoadingView` to disable it.

**Comment by jabez128** [comment]
en, I looked `RCTDevLoadingView` and I think I should set the `RCT_DEV = 0`, but I can't figure how to do this = =

**Comment by jabez128** [comment]
I think I know how to do it:

just add the below code in `AppDelegate.m` file: 

```objective-c
#define DEBUG 0
#define RCT_DEV 0
#define RCT_DEBUG 0
```

thx ~
