### ISSUE TITLE
running `pod install` throws CocoaPods could not find compatible versions for pod "FBLazyVector"

### ISSUE THREAD

**Issue by emadbaqeri** [facebook/react-native#33768]
### Description

While I'm trying to run `pod install` command I face this issue,
```bash
Using firebase.json from '/Users/emad/projects/dummy/frontend/firebase.json'
Adding a custom script phase for Pod RNFBApp: [RNFB] Core Configuration
Auto-linking React Native modules for target `univarsity`: RNCAsyncStorage, RNCMaskedView, RNDateTimePicker, RNFBApp, RNFBFirestore, RNFBInAppMessaging, RNFBMessaging, RNGestureHandler, RNImageCropPicker, RNNotifee, RNReanimated, RNSVG, RNScreens, RNSharedElement, RNVectorIcons, react-native-config, react-native-flipper, react-native-get-random-values, and react-native-safe-area-context
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `RCT-Folly` from `../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec`
Fetching podspec for `boost` from `../node_modules/react-native/third-party-podspecs/boost.podspec`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
[!] CocoaPods could not find compatible versions for pod "FBLazyVector":
  In Podfile:
    FBLazyVector (from `../node_modules/react-native/Libraries/FBLazyVector`)

Specs satisfying the `FBLazyVector (from `../node_modules/react-native/Libraries/FBLazyVector`)` dependency were found, but they required a higher minimum deployment target.

[!] Do not use "pod install" from inside Rosetta2 (x86_64 emulation on arm64).

[!]  - Emulated x86_64 is slower than native arm64

[!]  - May result in mixed architectures in rubygems (eg: ffi_c.bundle files may be x86_64 with an arm64 interpreter)

[!] Run "env /usr/bin/arch -arm64 /bin/bash --login" then try again.

```

### Version

0.67.2

### Output of `npx react-native info`

System:
    OS: macOS 12.3.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 125.13 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.19.1 - ~/.nvm/versions/node/v14.19.1/bin/node
    Yarn: 1.22.18 - ~/.nvm/versions/node/v14.19.1/bin/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v14.19.1/bin/npm
    Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: Bumblebee 2021.1.1 Patch 2 Bumblebee 2021.1.1 Patch 2
    Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

navigate to `ios` directory and run `pod install`

**Comment by Nacho-source** [comment]
Then what did you do to those firebase packages? I have them too (I've solved a deps issue during the installation with `npm i --legacy-peer-deps`) but what should I do with them?

**Comment by usmanhashmi2123** [comment]
#go to /ios and open  podfile 

the top of file 

platform :ios, '14.4.2'

'14.4.2' is the lastest verison

**Comment by MCervenka** [comment]
The platform :ios, '13.0'
was enough for me

**Comment by KarthiArcus** [comment]
thanks for your work @MCervenka

**Comment by harleenarora** [comment]
Without change the platform :ios, '11.0' how to solve this issue?

**Comment by sachinxagrawal** [comment]
12.4 is minimum requirement. update on top
platform :ios, '12.4'

**Comment by rus5665** [comment]
I commented on these lines, it works for me
` # use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end`

**Comment by carolinaknoll** [comment]
If anyone else is having this issue and don't want to update the iOS version, delete your `Podfile.lock` and run `pod install` again. It should complete successfully.

This issue is also related to the serialization/conflicting versions inside Podfile dependencies, and deleting it makes it so that the file can be recreated, and the versions updated, accordingly.

Just check with the team of your project if you can/should commit this, and check if your deploy pipelines will fail or not because if this issue. 🚀

**Comment by Cyberfolks** [comment]
> If anyone else is having this issue and don't want to update the iOS version, delete your `Podfile.lock` and run `pod install` again. It should complete successfully.
> 
> This issue is also related to the serialization/conflicting versions inside Podfile dependencies, and deleting it makes it so that the file can be recreated, and the versions updated, accordingly.
> 
> Just check with the team of your project if you can/should commit this, and check if your deploy pipelines will fail or not because if this issue. 🚀

it will not. I did many time but failed.

**Comment by romantylets-verint** [comment]
Also as an option you could use `min_ios_version_supported` function from `react_native_pods` in your pod file to be sure you are not using unsupported iOS version.

**Comment by badaz** [comment]
> @romantylets-verint I had `min_ios_version_supported` by default from the react native boilerplate and it didn't work until I replaced it with '13.4', so for me it didn't work for some reason.

12.4 and 13.0 did not work for me, but 13.4 did the trick. Does it mean that my project will now require to be run at minimum 13.4 version of ios?
