### ISSUE TITLE
Wrong return types for `addEventListener` in `AppStateStatic` and `LinkingStatic` 

### ISSUE THREAD

**Issue by mattg95** [facebook/react-native#33767]
### Description

![Screenshot 2022-05-05 at 12 27 53](https://user-images.githubusercontent.com/45606434/166914611-6bdf9475-7b0e-4575-b444-d98cdda6d3a9.png)

![Screenshot 2022-05-05 at 12 28 27](https://user-images.githubusercontent.com/45606434/166914612-855bdc2c-1522-4ff5-814f-e37d3ad746b9.png)

Return types for `addEventListener` in both `AppStateStatic` and `LinkingStatic` are 'void'. However if I console.log the following code:

```		
const appChangeListener = AppState.addEventListener('change', handleAppStateChange);
console.log(appChangeListener);
```
I see this in my console:
<img width="369" alt="Screenshot 2022-05-05 at 12 33 51" src="https://user-images.githubusercontent.com/45606434/166915092-85e81c4e-8979-4ab7-95f4-d4e9b403c48b.png">

I believe the return type of  `addEventListener` should be `NativeEventSubscription`. This is how it is typed in `BackHandlerStatic`:

![Screenshot 2022-05-05 at 12 35 09](https://user-images.githubusercontent.com/45606434/166915264-9470890b-8886-43aa-9c72-030f57cc4958.png)

### Version

0.68

### Output of `npx react-native info`

System:
    OS: macOS 11.5.2
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Memory: 41.42 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.5 - /usr/local/bin/node
    Yarn: 1.22.17 - ~/.npm-global/bin/yarn
    npm: 6.14.14 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.2 - /Users/matt/.gem/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7583922
    Xcode: 13.0/13A233 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.10 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.0 => 0.68.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

- Compare output of `AppState.addEventListener()` to output type

**Comment by AntoineDoubovetzky** [comment]
I believe this is not linked to the react-native repository, but rather to https://github.com/DefinitelyTyped/DefinitelyTyped/, and the types have been updated in this PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/55659

**Comment by cortinico** [comment]
> I believe this is not linked to the react-native repository, but rather to [DefinitelyTyped/DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/), and the types have been updated in this PR: [DefinitelyTyped/DefinitelyTyped#55659](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/55659)

Thanks for the heads up @AntoineDoubovetzky 

Closing, feel free to reopen @mattg95 if the issue persists
