### ISSUE TITLE
Picker is marked as deprecated in v0.68, but seems removed since v0.66

### ISSUE THREAD

**Issue by nmschulte-aviture** [facebook/react-native#33763]
### Description

[The Picker documentation](https://reactnative.dev/docs/picker) indicates the component is deprecated, though the [v0.66 changelog](https://github.com/facebook/react-native/blob/main/CHANGELOG.md#v0660) and [v0.67 changelog](https://github.com/facebook/react-native/blob/main/CHANGELOG.md#v0670) indicate the component has been removed.
> ### v0.66.0
> #### Breaking
> - Remove Picker and PickerIOS components [cddb97ad18](https://github.com/facebook/react-native/commit/cddb97ad18cfdb663dcf015af3c9426d5414e396), [77366cd869](https://github.com/facebook/react-native/commit/77366cd8696cb8ada3f84d7fb4d36a27f7007b06), [ad0ccac0d6](https://github.com/facebook/react-native/commit/ad0ccac0d6471fa5428bf137c3aa0646883e8446)
> ### v0.67.0
> #### Removed
> ##### Android specific
> - Remove DatePickerAndroid from react-native. ([7a770526c6](https://github.com/facebook/react-native/commit/7a770526c626e6659a12939f8c61057a688aa623) by [@andresantonioriveros](https://github.com/andresantonioriveros))

Further, none of the release notes indicate an change about the Picker component.
- https://reactnative.dev/blog/2020/03/26/version-0.62
- https://reactnative.dev/blog/2020/07/06/version-0.63
- https://reactnative.dev/blog/2021/03/12/version-0.64
- https://reactnative.dev/blog/2021/08/17/version-065
- https://reactnative.dev/blog/2021/10/01/version-066
- https://reactnative.dev/blog/2022/01/19/version-067
- https://reactnative.dev/blog/2022/03/30/version-068

I tried to find how transitions from deprecation to removal are handled about React Native, and found nothing except the [Deprecation Schedule document](https://docs.google.com/spreadsheets/d/1AtOTg_xfQOKgBWu6veCSXws19FDCHVtzfmm71XFYUHs/edit#gid=1483315145) which says nothing about the Picker.

What's the current status of the Picker in v0.68, and when was it officially removed?  My project has run into an issue about using the suggested `@react-native-picker/picker` (v2.2.1) on Android, seemingly because of this lack of communication though it's unclear:
> ```
> requireNativeComponent "RNCAndroidDropdownPicker" was not found in the UIManager
> ```

### Version

v0.68

### Output of `npx react-native info`

No thanks, please read the description.

### Steps to reproduce

View the documentation linked in the description.

**Comment by cortinico** [comment]
Yup this slipped through (cc @lunaleaps for context). 
Don't you mind sending a PR to update the RN website to update it to match the changelog?

**Comment by nmschulte-aviture** [comment]
> Yup this slipped through (cc @lunaleaps for context).

Thank you for the confirmation.  I don't know what's appropriate for the website as far as an update; I won't make a PR about it.

**Comment by cortinico** [comment]
Closing as this has been handled here https://github.com/facebook/react-native-website/pull/3110
