### ISSUE TITLE
How to create a npm package with multiple screens

### ISSUE THREAD

**Issue by rameshmkll** [facebook/react-native#33762]
### Description

I want to create a npm package for react native which has 2 screens. which displays a list and clicking on each list item should display details.

I found lot of articles and videos on creating npm packages with single file but i am not able to find is it possible to find an npm package with multiple screens and navigation within it.

### Version

0.66

### Output of `npx react-native info`

react-native : 0.66

### Steps to reproduce

I want to create a npm package for react native which has 2 screens. which displays a list and clicking on each list item should display details.

I found lot of articles and videos on creating npm packages with single file but i am not able to find is it possible to find an npm package with multiple screens and navigation within it.

**Comment by cortinico** [comment]
If you create a new app with `npx react-native init`, that already offers a top level `package.json` that you can use to publish to NPM.

If instead you want to create a library, you should use a tool like https://github.com/callstack/react-native-builder-bob
