### ISSUE TITLE
New architecture performance improvements

### ISSUE THREAD

**Issue by sridhard** [facebook/react-native#33771]
### New Version

0.68.1

### Old Version

0.63

### Build Target(s)

Android in release mode

### Output of `react-native info`

System:
    OS: macOS 11.2.2
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 2.50 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.12 - ~/.nvm/versions/node/v14.16.1/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29, 30, 31, 32
      Build Tools: 23.0.1, 23.0.2, 25.0.0, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.0, 28.0.2, 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 32.0.0
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.1 => 0.68.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Issue and Reproduction Steps

Hi,

My app is complex and it is laggy. So i upgraded to new architecture for performance improvement. I am able to build and run the app successfully. But There is no improvement in performance. App performance in old and new architecture is exactly same.

I have enabled new architecture and also when building C++ code is compiled.

I want to know the below:
1. Is performance improvement expected when we upgrade to new architecture? This improvement is mainly related to rendering of the screen. No native libraries are involved
2. Should we modify any code to get the benefits of performance from new architecture?

Thanks

**Comment by RowlandOti** [comment]
Also interested in this. Following closely.

**Comment by sridhard** [comment]
an anyone pls update? as per docs new architecture should improve performance. But we are not able to get any performance improvements.

**Comment by cipolleschi** [comment]
A few questions may help us here:

1. Have you tried using Hermes as JavaScript Engine?
1. Were you measuring performances before the upgrade and after the upgrade? 
    1. How? 
    1. What was the output?

**Comment by sridhard** [comment]
Sorry for the late reply:

1. Yes we are using hermes for both old and new architectures
2. Since our app response time like rendering of flatlists is laggy, we checked the rendering performance before and after upgrade. We have not used any tools but we can find manually/visually that both rendering performance is almost same.

@cipolleschi is it expected to improve rendering performance of flatlist, response time of button clicks etc? do we need to do any code changes?

**Comment by sridhard** [comment]
@cipolleschi can you pls help us

**Comment by jgx-jay** [comment]
Also interested in this. Following closely.

**Comment by JLucasCAmorim** [comment]
I'm also following this up

**Comment by sridhard** [comment]
@cipolleschi any updates?

**Comment by cortinico** [comment]
Writing `any updates?` once a month is not really useful, sadly.

I would advice anyone interested in knowing more about performance around the New Architecture to subscribe to the New Architecture working group here: github.com/reactwg/react-native-new-architecture/ (you can find instructions on the README).

> expected to improve rendering performance of flatlist, response time of button clicks etc? do we need to do any code changes?

Please direct specific questions in the Working Group. As a rule of thumb, yes. You can expect a performance improvement, but it's hard to give you exact numbers as it really depends on your current setup, how many native modules you have, how you're loading them, how many components you have, how many of those are Fabric compatible.
