### ISSUE TITLE
FBReactNativeSpec: Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by galihlprakoso** [facebook/react-native#33775]
### Description

The react-native is working fine on debug and release build running on iphone device and emulators. But when I tried to archive (preparation to be uploaded on ios app store). It's failing.

```
/Users/mymac/.asdf/shims/node: line 4: /opt/homebrew/Cellar/asdf/0.9.0/libexec/bin/asdf: No such file or directory
/Users/mymac/.asdf/shims/node: line 4: exec: /opt/homebrew/Cellar/asdf/0.9.0/libexec/bin/asdf: cannot execute: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code
```

I've tried some of available workarounds as discussed here: https://github.com/react-native-community/upgrade-support/issues/161 but none of them is working.

### Version

0.66.0

### Output of `npx react-native info`

System:
    OS: macOS 12.0.1
    CPU: (8) arm64 Apple M1
    Memory: 156.25 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.19.1 - /opt/homebrew/opt/node@14/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 6.14.16 - /opt/homebrew/opt/node@14/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 13.3/13E113 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.0 => 0.66.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Run Product >> Archive on XCode.

**Comment by cortinico** [comment]
> /Users/mymac/.asdf/shims/node: line 4: /opt/homebrew/Cellar/asdf/0.9.0/libexec/bin/asdf: No such file or directory

Build is failing as it's trying to search for `asdf`. Are you using any Node version manager? How have you configured them?

**Comment by bozaigao** [comment]
I tried everything and the final changes are as follows:
nvm unalias default
nvm alias default node

**Comment by galihlprakoso** [comment]
For now, I can hotfix it by following this step: https://github.com/react-native-community/upgrade-support/issues/161#issuecomment-1036014133 .
