### ISSUE TITLE
Xcode Archive Type "Generic Xcode Archive" 

### ISSUE THREAD

**Issue by auchaphon** [facebook/react-native#33772]
### Description

My react-native app Archive Type "Generic Xcode Archive"

Method of distribution 2 options not display App Store Connect Option

<img width="819" alt="Screen Shot 2565-05-06 at 12 47 03" src="https://user-images.githubusercontent.com/29698585/167074433-aa336cf1-3209-49b8-b8c4-bf76681d08f9.png">

<img width="1435" alt="Screen Shot 2565-05-06 at 12 12 21" src="https://user-images.githubusercontent.com/29698585/167074474-a2af80bf-1fce-45a4-8899-61111334ef78.png">

### Version

0.61.5

### Output of `npx react-native info`

System:
    OS: macOS 12.2.1
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 121.63 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v14.17.0/bin/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7935034
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  npmPackages:
    react: ^16.9.0 => 16.12.0 
    react-native: 0.61.5 => 0.61.5

### Steps to reproduce

Product => Archive

**Comment by cortinico** [comment]
> 0.61.5

Closing as that's a 3 years old version of RN. We can't offer support for that + the issue report is not entirely clear. Please consider updating and re-opening an issue on RN 0.68 if the problem persists.

**Comment by showtan001** [comment]
@auchaphon PROJECT and TARGETS => Build Settings
Search for "Skip Install" and set it to "NO"
