### ISSUE TITLE
Setting up develop environment for Android fails

### ISSUE THREAD

**Issue by YorkShen** [facebook/react-native#3377]
After setting up server host in my Android phone according to http://facebook.github.io/react-native/docs/running-on-device-android.html#content, I got the following error message when running UIExplorer example.

> [15:12:14] <START> request:/Examples/UIExplorer/UIExplorerApp.android.bundle?platform=android
[15:12:14] <START> find dependencies
[15:12:14] <END>   find dependencies (221ms)
[15:12:14] <START> transform
transforming [========================================] 100% 349/349
[15:12:14] <END>   transform (223ms)
[15:12:14] <END>   request:/Examples/UIExplorer/UIExplorerApp.android.bundle?platform=android (501ms)
::ffff:10.68.57.150 - - [Tue, 13 Oct 2015 07:12:18 GMT] "GET /flow/ HTTP/1.1" 404 - "-" "okhttp/2.4.0"

MAC OS X 10.11
node version 4.2.0
Android phone LG G2
Android version 4.2.2.

**Comment by jimtang9527** [comment]
+1

**Comment by sospartan** [comment]
@YorkShen it is not 'error'  ,you'd better take a screenshot of the redbox on your phone,that's the real error message .

**Comment by YorkShen** [comment]
@sospartan The App just crashed on my phone.

**Comment by sospartan** [comment]
@YorkShen get stack trace from logcat .

**Comment by YorkShen** [comment]
@sospartan 

> --------- beginning of /dev/log/system
--------- beginning of /dev/log/main
W/ReactNativeJS( 8860): 'Warning: Native component for "RCTModalHostView" does not exist'
D/ReactNativeJS( 8860): 'Running application "UIExplorerApp" with appParams: {"initialProps":{},"rootTag":1}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF'

**Comment by YorkShen** [comment]
Problem fixed.

The UIExplorer still have dependencies of React Native 0.11, which will cause the problem above and the logcat is shown as following.

> TypeError: expected dynamic type 'string', but had type 'int64

To fix this problem, one can follow the comment of https://github.com/facebook/react-native/issues/3033#issuecomment-146604308
