### ISSUE TITLE
The onPress event is invalid (android)

### ISSUE THREAD

**Issue by TangChanged** [facebook/react-native#33781]
### Description

view rotate 90 degrees, onPress doesn't work

<View style={{flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: 'rgba(51, 51, 51, 0.6)',}}>
      <View style={{backgroundColor: 'white',
        width: 290,
        paddingTop: 24,
        borderRadius: 10,
        paddingHorizontal: 24,
        justifyContent: 'center',
        alignItems: 'center',
        transform: [{ rotate: '90deg' }],}}>
        <Image source={require('../../../assets/in.png')} />
        <TouchableOpacity
          style={styles.btnView}
          onPress={() => {
            props.navigation.goBack();
          }}>
          <Text
            style={{
              fontSize: 14,
              color: 'white',
            }}>
            开始
          </Text>
        </TouchableOpacity>
      </View>
    </View>

### Version

0.60

### Output of `npx react-native info`

no

### Steps to reproduce

1. Draw the View
2. Rotate 90 degrees
3. TouchableOpacity onPress  don't work

**Comment by cortinico** [comment]
> 0.60

Sorry but that's a 3 years old version of React Native.
Please consider updating first or creating a reproducer from a fresh project on RN 0.68 as perhaps your issue is already resolved.

Closing for now, feel free to re-open if the issue persists on 0.68.

**Comment by TangChanged** [comment]
yes, new versions also exist,0.68.
