### ISSUE TITLE
npx react-native run-ios not working for react native fresh project

### ISSUE THREAD

**Issue by jaydave1412** [facebook/react-native#33793]
### Description

Based on the getting started guide provided here https://reactnative.dev/docs/environment-setup, I am trying to build a build a project using react native cli. I followed the exact steps provided in the article and the project starts for android but not for ios. The error I am getting is

```
2022-05-09 19:52:26.204 xcodebuild[27325:198569] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
2022-05-09 19:52:26.208 xcodebuild[27325:198569] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
```

and this

`Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening AwesomeProject.xcworkspace`

```
The following build commands failed:
	CompileC /Users/jaydave5/Library/Developer/Xcode/DerivedData/AwesomeProject-gypcnmvewcvovdgwbdrhxjrrxutt/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RCT-Folly.build/Objects-normal/x86_64/SysUio.o /Users/jaydave5/Documents/native\ projects/bare\ react\ native/AwesomeProject/ios/Pods/RCT-Folly/folly/portability/SysUio.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'RCT-Folly' from project 'Pods')
(1 failure)
```

On doing some research I saw a stackoverflow post where it said to try opening the xcode workspace in ios folder and trying to build from there I have attached the screenshot of the error I received there

<img width="1440" alt="Screenshot 2022-05-09 at 8 23 34 PM" src="https://user-images.githubusercontent.com/44256361/167438110-e13f0543-fa5f-4eaf-92a0-1e4b98284aec.png">

### Version

0.68.2

### Output of `npx react-native info`

System:
    OS: macOS 12.2.1
    CPU: (8) x64 Apple M1
    Memory: 43.58 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.1 - ~/.nvm/versions/node/v14.17.1/bin/node
    Yarn: 1.22.18 - ~/.nvm/versions/node/v14.17.1/bin/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.1/bin/npm
    Watchman: 2022.03.21.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.2 => 0.68.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Step 1
`npx react-native init AwesomeProject`

Step 2
`npx react-native start`

Step 3
`npx react-native run-ios`

**Comment by tj-mc** [comment]
Have you tried clearing your build folder, re-starting your computer and re-initialising the project? I have seen this error before but I can't remember what triggered it.

**Comment by jaydave1412** [comment]
@tj-mc I tried it multiple times As stated in description I even tried creating an expo project and running expo eject and trying to run that application but even that didnot work

**Comment by olga-giza** [comment]
Hey @jaydave1412 I'm facing the same issue now :D Looks like it's a problem with xcode 13, not react-native itself.
I found multiple threads on the apple forum and it looks like downgrading xcode to 13.2.1  should fix that until apple won't fix it on their side https://xcodereleases.com/ 
I am trying it now 😆

**Comment by JordanDDisch** [comment]
@olga-giza any luck with downgrading? I'm assuming this is tied to whatever react native version is used. For example i've created a bare bones react native app using (0.68) and it works fine with the latest xcode (13.3.1). But when I start my project using 0.64 it has the same issue described here. For what its worth this is happening to the flutter community as well. Same issue, seems downgrading is helping some. https://github.com/flutter/flutter/issues/98298

**Comment by olga-giza** [comment]
@JordanDDisch Yup - downgrading resolved mentioned issue 🎉  Then I faced another problem and for that error, I found this article which helped me run the app: https://khushwanttanwar.medium.com/xcode-12-compilation-errors-while-running-with-ios-14-simulators-5731c91326e9  😃

**Comment by jaydave1412** [comment]
I ran pod install normally it worked without any error but I faced this issue to resolve that I ran arch -x86_64 pod install and it worked flawlessly

**Comment by Vahabov** [comment]
> 

After running the arch -x86_64 pod install command, nothing starting with npx worked in my terminal. how do i return it?
