### ISSUE TITLE
When Overlay close then bottom tabs bar hide behind navigation bar

### ISSUE THREAD

**Issue by Mitesh-2009** [facebook/react-native#33796]
### Description

My Application has 5 tabs, when I click another tab then some progress bar overlay opens the bottom tabs display proper, and once the progress bar overlay closes the bottom tabs bar hides behind navigation bar (React Native Navigation library Version - 7.27.1 and React Native version - 0.68.0)

### Version

0.68.0

### Output of `npx react-native info`

react-native run-android

### Steps to reproduce

Use react native navigation library with create new react native app and user bottom tabs options and try to navigation bar property set to true

**Comment by cortinico** [comment]
> React Native Navigation library Version - 7.27.1

Please report this issue on the React Native Navigation Library issue tracker

**Comment by Mitesh-2009** [comment]
> 

This issue happen after upgrade react native version

**Comment by cortinico** [comment]
> reported issue in React Native Navigation Library issue tracker also

Could you link it here for reference?

**Comment by Mitesh-2009** [comment]
https://github.com/wix/react-native-navigation/issues/7508
