### ISSUE TITLE
Android TextInput Overflow hides start of line content

### ISSUE THREAD

**Issue by kav** [facebook/react-native#33794]
### Description

This issue is a repro of https://github.com/facebook/react-native/issues/25045 which was closed as stale but continues to occur in React Native 0.64.3 at the least (Expo 44). I'll update here when snacks move to Expo 45 or when I have a second to build out a local 0.66 repro.

If someone has a 0.66 project handy they can quickly overflow a TextInput on android and confirm I'd appreciate it. Given the previous issue I fully expect it will. 

### Version

0.64.3

### Output of `npx react-native info`

```
System:
    OS: macOS 12.3.1
    CPU: (10) x64 Apple M1 Max
    Memory: 1.02 GB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
    Watchman: 2022.01.31.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7935034
    Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
  Languages:
    Java: javac 17 - /opt/homebrew/opt/openjdk/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.64.3 => 0.64.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

Create a sample TextInput in your code.
Type a lengthy string in it.
First few letters are truncated
Actual Result:
Displaying the text at the end of the text field
Expected Result:
Display the text from beginning

### Snack, code example, screenshot, or link to a repository

https://snack.expo.dev/@kavla/android-textinput-overflow

**Comment by wonjin-dev** [comment]
i have same problem. it seems that a vertically fixed space has been allocated

**Comment by kav** [comment]
Updated the snack to Expo 47 
React Native 0.70.5 

Issue continues to repro.

https://snack.expo.dev/@kavla/android-textinput-overflow
