### ISSUE TITLE
RCTActionSheet.xcodeproj is missing.

### ISSUE THREAD

**Issue by dalinaum** [facebook/react-native#338]
![2015-03-27 9 58 24](https://cloud.githubusercontent.com/assets/145585/6868660/cbe11066-d4d0-11e4-84a5-76d8104adfa2.png)

`File not found` error occurs on `RCTActionSheet.xcodeproj`. I tested Sample `Examples/SampleApp` with Appcode.

**Comment by jaygarcia** [comment]
Works fine for me.  is that a JetBrains IDE?
![2015-03-27_09-48-21](https://cloud.githubusercontent.com/assets/180031/6869038/46d3bc20-d467-11e4-93b7-88232baea9d9.jpg)

**Comment by dalinaum** [comment]
@jaygarcia Right. That is Appcode, a JetBrains IDE.

**Comment by dalinaum** [comment]
@frantic Should this issue be closed?

**Comment by dalinaum** [comment]
It was fixed.
https://github.com/facebook/react-native/commit/31c4ff0dd62ee705353c2b4de916a151f89410d4
