### ISSUE TITLE
Declaration of 'YGValue' must be imported from module 'yoga.yoga.YGNode' before it is required

### ISSUE THREAD

**Issue by destinyxxl** [facebook/react-native#33815]
### Description

i run a react-navive project,  npm install and pod install succeed,when i run the project igot the error

### Version

0.67.4

### Output of `npx react-native info`

System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Memory: 652.55 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 18.0.0 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.6.0 - /usr/local/bin/npm
    Watchman: 2022.03.21.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/fengxiaolin/.rvm/rubies/ruby-2.7.4/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.4 => 0.67.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

built framework

### Snack, code example, screenshot, or link to a repository
![截屏2022-05-12 下午5 42 28](https://user-images.githubusercontent.com/13796652/168042329-a9393385-abe8-4b8d-a2e6-801b4fa82388.png)

**Comment by destinyxxl** [comment]
i noticed the issue [https://github.com/facebook/react-native/issues/28542](url), but my cocoapods version is latest（1.11.3）， i tried downgrade cocoapods version to 1.9.1，bug i got the error “React need at least 1.10.1”

**Comment by JB-CHAUVIN** [comment]
I have a similar issue on RC 0.69, don't know if it is related ?
```Use of undeclared identifier 'YGValue'``

![iScreen Shoter - 2022-06-07 16:39:46 538](https://user-images.githubusercontent.com/8957878/172408673-64250dda-e85a-4bce-ae48-0bac9430b83a.jpg)
`

**Comment by mfik** [comment]
As mentioned here https://github.com/facebook/react-native/issues/33648 , temporary solution is to add a line in the install / build proccess

```
rm -rf node_modules ios/Pods
yarn
sed -i -e "s/spec.module_name = 'yoga'/spec.module_name = 'Yoga'/g" node_modules/react-native/ReactCommon/yoga/Yoga.podspec
npx pod-install
expo run:ios
```

**Comment by ph4r05** [comment]
I figured that when Obj-C++ is used for given files, error is fixed https://github.com/facebook/react-native/issues/33976#issuecomment-1164973209
