### ISSUE TITLE
Android project not found

### ISSUE THREAD

**Issue by resaknitto11** [facebook/react-native#33835]
### Description

error Android project not found. Are you sure this is a React Native project? If your Android files are located in a non-standard location (e.g. not inside 'android' folder), consider setting `project.android.sourceDir` option to point to a new location.
info Run CLI with --verbose flag for more details.

### Version

0.68.2

### Output of `npx react-native info`

System:
    OS: Windows 10 10.0.19042
    CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
    Memory: 6.21 GB / 15.88 GB
  Binaries:
    Node: 14.19.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.15 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.16 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5522156
    Visual Studio: 17.1.32319.34 (Visual Studio Community 2022)
  Languages:
    Java: 1.8.0_312 - C:\Program Files\OpenJDK\openjdk-8u312-b07\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.68.2 => 0.68.2
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

bug

**Comment by 1adybug** [comment]
I had this problem too. Yesterday everything was ok. I tried the following ways:
1. delete `node_modules`, `yarn cache clean`, re-install all modules. It didnt work.
2. `npx react-native@otherversion init`. It didnt work.
3. delete `node_modules` and copy `node_modules` from an old project to this project. It really worked.
I'm guessing there's something wrong with a dependency.

**Comment by shxinlei** [comment]
Did the problem work out?

**Comment by VeoScript** [comment]
The same thing happened to me today, I also can't find a solution to this problem

**Comment by shxinlei** [comment]
> The same thing happened to me today, I also can't find a solution to this problem

The project I created for the first time yesterday is available, but the one I created today is not available

**Comment by alcristog** [comment]
Same here.

**Comment by junggernaut** [comment]
same here

**Comment by songzitao-hub** [comment]
same here

**Comment by shxinlei** [comment]
Do you guys have any temporary solutions

**Comment by sebastiansiedlarz409** [comment]
I have same problem. Few days ago everything works ok. After typing:
`npx react-native config`
I have no set android paths, but in my older project i have.

**Comment by shxinlei** [comment]
> 我有同样的问题。几天前一切都很好。打字后：我没有设置Android路径，但在我的旧项目中我有。`npx react-native config`

 "project": {
    "ios": {
      "sourceDir": "D:\\project\\Batters\\ios",
      "folder": "D:\\project\\Batters",
      "pbxprojPath": "D:\\project\\Batters\\ios\\Batters.xcodeproj\\project.pbxproj",
      "podfile": "D:\\project\\Batters\\ios\\Podfile",
      "podspecPath": null,
      "projectPath": "D:\\project\\Batters\\ios\\Batters.xcodeproj",
      "projectName": "Batters.xcodeproj",
      "libraryFolder": "Libraries",
      "sharedLibraries": [],
      "plist": [],
      "scriptPhases": []
    },
    "android": null
  }

Here? Can it be solved?

**Comment by sebastiansiedlarz409** [comment]
@shxinlei Yep, here. I have no clue what to do. I wast half a day today.

**Comment by AxanIqbal** [comment]
having the same issue with expo new projects

**Comment by VeoScript** [comment]
even in react native cli, the error is still the same

**Comment by PrestonThomas** [comment]
I encountered the exact same issue today when creating new projects, older projects are still fine.

**Comment by AnkitRoyy** [comment]
> I encountered the exact same issue today when creating new projects, older projects are still fine.

Same here

**Comment by GouravNainwaya** [comment]
having the same issue with react native new projects

**Comment by hafiz-sameed** [comment]
I'm also facing the same issue. Any solution?

**Comment by AnkitRoyy** [comment]
Is Facebook will solve it or do we have to find a solution?

**Comment by poolals** [comment]
Same here
  "project": {
    "ios": {
      "sourceDir": "C:\\Programacao\\pessoal\\react_native\\trademanager\\ios",
      "folder": "C:\\Programacao\\pessoal\\react_native\\trademanager",
      "pbxprojPath": "C:\\Programacao\\pessoal\\react_native\\trademanager\\ios\\trademanager.xcodeproj\\project.pbxproj",
      "podfile": "C:\\Programacao\\pessoal\\react_native\\trademanager\\ios\\Podfile",
      "podspecPath": null,
      "projectPath": "C:\\Programacao\\pessoal\\react_native\\trademanager\\ios\\trademanager.xcodeproj",
      "projectName": "trademanager.xcodeproj",
      "libraryFolder": "Libraries",
      "sharedLibraries": [],
      "plist": [],
      "scriptPhases": []
    },
    "android": null
  }

**Comment by THEG77** [comment]
```
"project": {
    "ios": {
      "sourceDir": "C:\\Users\\devre\\Desktop\\Study\\Code\\ReactNativeStuff\\msapp\\ios",
      "folder": "C:\\Users\\devre\\Desktop\\Study\\Code\\ReactNativeStuff\\msapp",
      "pbxprojPath": "C:\\Users\\devre\\Desktop\\Study\\Code\\ReactNativeStuff\\msapp\\ios\\msapp.xcodeproj\\project.pbxproj",
      "podfile": "C:\\Users\\devre\\Desktop\\Study\\Code\\ReactNativeStuff\\msapp\\ios\\Podfile",
      "podspecPath": null,
      "projectPath": "C:\\Users\\devre\\Desktop\\Study\\Code\\ReactNativeStuff\\msapp\\ios\\msapp.xcodeproj",
      "projectName": "msapp.xcodeproj",
      "libraryFolder": "Libraries",
      "sharedLibraries": [],
      "plist": [],
      "scriptPhases": []
    },
    "android": null
  }
```
My life is ruined

**Comment by VeoScript** [comment]
> Is this bug in react-native? Is Facebook will solve it or do we have to find a solution?

Mark Zuckerberg's birthday today, maybe tomorrow he'll fix this problem ✌️

**Comment by AnkitRoyy** [comment]
> Mark Zuckerberg's birthday today, maybe tomorrow he'll fix this problem ✌️

Maybe😁

**Comment by ilsochrist** [comment]
same problem here Android project not found. Are you sure this is a React Native project? If your Android files are located in a non-standard location (e.g. not inside 'android' folder), consider setting `project.android.sourceDir` option to point to a new location.       
info Run CLI with --verbose flag for more details. 

Any one know how fix it?

package.json
{
  "name": "org",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "react": "17.0.2",
    "react-native": "0.68.2"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "^7.32.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.67.0",
    "react-test-renderer": "17.0.2"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Comment by chirigutraul** [comment]
Same problem here. I have been troubleshooting for 5 hours, nothing works. Older projects still works, but every new project throws up that error. I noticed that the 'build' folder is missing from android/app/.

**Comment by Aqibiweb** [comment]
I also faced the same issue today. Yesterday, I created a project on Windows for android and it worked but today when I started a new project same issue occurred.

**Comment by mvhk** [comment]
Same Here not able to start the android

**Comment by mvhk** [comment]
> Same Here not able to start the android

C:\Users\haris\Desktop\ReactNative\newair>npm run android

> newair@0.0.1 android C:\Users\haris\Desktop\ReactNative\newair
> react-native run-android

error Android project not found. Are you sure this is a React Native project? If your Android files are located in a non-standard location (e.g. not inside 'android' folder), consider setting `project.android.sourceDir` option to point to a new location.
info Run CLI with --verbose flag for more details.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! newair@0.0.1 android: `react-native run-android`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the newair@0.0.1 android script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\haris\AppData\Roaming\npm-cache\_logs\2022-05-14T14_04_00_565Z-debug.log

**Comment by 007AxelBerkati** [comment]
same issue here

**Comment by ilsochrist** [comment]
@grabbou  You solved that??? i red a topic, https://github.com/facebook/react-native/issues/9312 but dont understand the final solution. Can you help me?

**Comment by Hlacer** [comment]
This problem occurred at the beginning of learning RN today, which makes me ready to give it up
恶魔🤔

**Comment by Hlacer** [comment]
This problem occurred at the beginning of learning RN today, which makes me ready to give it up🤔

**Comment by mvhk** [comment]
> > Same Here not able to start the android
> 
> C:\Users\haris\Desktop\ReactNative\newair>npm run android
> 
> > newair@0.0.1 android C:\Users\haris\Desktop\ReactNative\newair
> > react-native run-android
> 
> error Android project not found. Are you sure this is a React Native project? If your Android files are located in a non-standard location (e.g. not inside 'android' folder), consider setting `project.android.sourceDir` option to point to a new location. info Run CLI with --verbose flag for more details. npm ERR! code ELIFECYCLE npm ERR! errno 1 npm ERR! newair@0.0.1 android: `react-native run-android` npm ERR! Exit status 1 npm ERR! npm ERR! Failed at the newair@0.0.1 android script. npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in: npm ERR! C:\Users\haris\AppData\Roaming\npm-cache_logs\2022-05-14T14_04_00_565Z-debug.log

1. > Caused by: java.lang.Exception: React Native CLI failed to determine Android project configuration. This is likely due to misconfiguration. Config output:
2.   `React Native CLI failed to determine Android project configuration. This is likely due to misconfiguration. Config output:
[root:C:\Users\haris\Desktop\ReactNative\newair, reactNativePath:C:\Users\haris\Desktop\ReactNative\newair\node_modules\react-native, dependencies:[:], commands:[[name:log-ios, description:starts iOS device syslog tail], [name:run-ios, description:builds your app and starts it on iOS simulator, examples:[[desc:Run on a different simulator, e.g. iPhone SE (2nd generation), cmd:react-native run-ios --simulator "iPhone SE (2nd generation)"], [desc:Pass a non-standard location of iOS directory, cmd:react-native run-ios --project-path "./app/ios"], [desc:Run on a connected device, e.g. Max's iPhone, cmd:react-native run-ios --device "Max's iPhone"], [desc:Run on the AppleTV simulator, cmd:react-native run-ios --simulator "Apple TV"  --scheme "helloworld-tvOS"]], options:[[name:--simulator <string>, description:Explicitly set simulator to use. Optionally include iOS version between parenthesis at the end to match an exact version: "iPhone 6 (10.0)", default:iPhone 13], [name:--configuration <string>, description:Explicitly set the scheme configuration to use, default:Debug], [name:--scheme <string>, description:Explicitly set Xcode scheme to use], [name:--project-path <string>, description:Path relative to project root where the Xcode project (.xcodeproj) lives., default:ios], [name:--device [string], description:Explicitly set device to use by name.  The value is not required if you have a single device connected.], [name:--udid <string>, description:Explicitly set device to use by udid], [name:--no-packager, description:Do not launch packager while building], [name:--verbose, description:Do not use xcbeautify or xcpretty even if installed], [name:--port <number>, default:8081], [name:--terminal <string>, description:Launches the Metro Bundler in a new window using the specified terminal path.]]], [name:log-android, description:starts logkitty], [name:run-android, description:builds your app and starts it on a connected Android emulator or device, options:[[name:--root <string>, description:[DEPRECATED - root is discovered automatically] Override the root directory for the android build (which contains the android directory), default:], [name:--variant <string>, description:Specify your app's build variant, default:debug], [name:--appFolder <string>, description:[DEPRECATED â€“ use "project.android.appName" in react-native.config.js] Specify a different application folder name for the android source. If not, we assume is "app"], [name:--appId <string>, description:Specify an applicationId to launch after build. If not specified, `package` from AndroidManifest.xml will be used., default:], [name:--appIdSuffix <string>, description:Specify an applicationIdSuffix to launch after build., default:], [name:--main-activity <string>, description:Name of the activity to start, default:MainActivity], [name:--deviceId <string>, description:builds your app and starts it on a specific device/simulator with the given device id (listed by running "adb devices" on the command line).], [name:--no-packager, description:Do not launch packager while building], [name:--port <number>, default:8081], [name:--terminal <string>, description:Launches the Metro Bundler in a new window using the specified terminal path.], [name:--tasks <list>, description:Run custom Gradle tasks. By default it's "installDebug"], [name:--no-jetifier, description:Do not run "jetifier" â€“ the AndroidX transition tool. By default it runs before Gradle to ease working with libraries that don't support AndroidX yet. See more at: https://www.npmjs.com/package/jetifier.], [name:--active-arch-only, description:Build native libraries only for the current device architecture for debug builds., default:false]]]], assets:[], healthChecks:[], platforms:[ios:[:], android:[:]], project:[ios:[sourceDir:C:\Users\haris\Desktop\ReactNative\newair\ios, folder:C:\Users\haris\Desktop\ReactNative\newair, pbxprojPath:C:\Users\haris\Desktop\ReactNative\newair\ios\newair.xcodeproj\project.pbxproj, podfile:C:\Users\haris\Desktop\ReactNative\newair\ios\Podfile, podspecPath:null, projectPath:C:\Users\haris\Desktop\ReactNative\newair\ios\newair.xcodeproj, projectName:newair.xcodeproj, libraryFolder:Libraries, sharedLibraries:[], plist:[], scriptPhases:[]], android:null]]
`

**Comment by chirigutraul** [comment]
> This problem occurred at the beginning of learning RN today, which makes me ready to give it up 恶魔🤔

It is probably an update that doesn't work so well. Don't give up, mate, you got this. We are all facing this issue.

**Comment by mvhk** [comment]
> This problem occurred at the beginning of learning RN today, which makes me ready to give it up🤔

@Hlacer great start, atleast you know now that, the path is hard, and we need more efforts on RN

**Comment by radov97** [comment]
I have the same issue. The project was working fine yesterday, and after I run yarn install, I got the same error and I found this open issue.
Currently I am trying to understand what is the cause of this issue.

**Comment by Hlacer** [comment]
> 



> > This problem occurred at the beginning of learning RN today, which makes me ready to give it up🤔
> 
> @Hlacer great start, atleast you know now that, the path is hard, and we need more efforts on RN

 Thank you very much. This is really a difficult start

**Comment by Hlacer** [comment]
> > This problem occurred at the beginning of learning RN today, which makes me ready to give it up 恶魔🤔
> 
> It is probably an update that doesn't work so well. Don't give up, mate, you got this. We are all facing this issue.

 Thank you very much. Let's continue to refuel together ！

**Comment by enescang** [comment]
Hello everyone. I check this https://github.com/react-native-community/cli/issues/1608#issuecomment-1126581017 and solved with:

1. Clear node_modules
2. add this to package.json
`"resolutions": {
    "glob": "7.2.0"
  }`
3. Reinstall node_modules with `npm install`

**Comment by mouxuefei** [comment]
> Hello everyone. I check this [react-native-community/cli#1608 (comment)](https://github.com/react-native-community/cli/issues/1608#issuecomment-1126581017) and solved with:
> 
> 1. Clear node_modules
> 2. add this to package.json
>    `"resolutions": { "glob": "7.2.0"   }`
> 3. Reinstall node_modules with `npm install`
> 
> And you may vote this result on stackoverflow https://stackoverflow.com/questions/72239857/react-native-android-project-not-found/72241166#72241166

cool,bro

**Comment by radov97** [comment]
> Hello everyone. I check this [react-native-community/cli#1608 (comment)](https://github.com/react-native-community/cli/issues/1608#issuecomment-1126581017) and solved with:
> 
>     1. Clear node_modules
> 
>     2. add this to package.json
>        `"resolutions": { "glob": "7.2.0"   }`
> 
>     3. Reinstall node_modules with `npm install`
> 
> 
> And you may vote this result on stackoverflow https://stackoverflow.com/questions/72239857/react-native-android-project-not-found/72241166#72241166

This has worked for me!

**Comment by VeoScript** [comment]
> noticed

nice one

**Comment by VeoScript** [comment]
> Hello everyone. I check this [react-native-community/cli#1608 (comment)](https://github.com/react-native-community/cli/issues/1608#issuecomment-1126581017) and solved with:
> 
> 1. Clear node_modules
> 2. add this to package.json
>    `"resolutions": { "glob": "7.2.0"   }`
> 3. Reinstall node_modules with `npm install`
> 
> And you may vote this result on stackoverflow https://stackoverflow.com/questions/72239857/react-native-android-project-not-found/72241166#72241166

nice one

**Comment by AsuKaur** [comment]
> Hello everyone. I check this [react-native-community/cli#1608 (comment)](https://github.com/react-native-community/cli/issues/1608#issuecomment-1126581017) and solved with:
> 
> 1. Clear node_modules
> 2. add this to package.json
>    `"resolutions": { "glob": "7.2.0"   }`
> 3. Reinstall node_modules with `npm install`
> 
> And you may vote this result on stackoverflow https://stackoverflow.com/questions/72239857/react-native-android-project-not-found/72241166#72241166

This doesn't work for me.
Anything else I can try?

**Comment by sebastiansiedlarz409** [comment]
@AsuKaur Try:
`npm i glob@7.2.0`

**Comment by VeoScript** [comment]
> > Hello everyone. I check this [react-native-community/cli#1608 (comment)](https://github.com/react-native-community/cli/issues/1608#issuecomment-1126581017) and solved with:
> > 
> > 1. Clear node_modules
> > 2. add this to package.json
> >    `"resolutions": { "glob": "7.2.0"   }`
> > 3. Reinstall node_modules with `npm install`
> > 
> > And you may vote this result on stackoverflow https://stackoverflow.com/questions/72239857/react-native-android-project-not-found/72241166#72241166
> 
> This doesn't work for me. Anything else I can try?

try using
> yarn install glob@7.2.0

**Comment by AsuKaur** [comment]
@sebastiansiedlarz409 @VeoScript Yes this works. Thanks a lot!

**Comment by ilsochrist** [comment]
![image](https://user-images.githubusercontent.com/100448527/168432825-cec64b4e-64b3-4549-80cc-5b03380cab68.png)

Same problem here, dont fix it the solve

**Comment by ilsochrist** [comment]
i not using expo, im using android studio.

**Comment by ilsochrist** [comment]
![image](https://user-images.githubusercontent.com/100448527/168433349-fe98da56-0280-4c4b-8de4-3348d45db950.png)

Now i have this error, used npm i glob@7.2.0

**Comment by ilsochrist** [comment]
![image](https://user-images.githubusercontent.com/100448527/168433614-118b2a83-b3a9-490e-a1c7-f84e88e088db.png)


JAVA-HOME is not right?

**Comment by VeoScript** [comment]
> ![image](https://user-images.githubusercontent.com/100448527/168433614-118b2a83-b3a9-490e-a1c7-f84e88e088db.png)
> 
> JAVA-HOME is not right?

![image](https://user-images.githubusercontent.com/26340308/168434264-25afc23f-c1c8-480f-ad6e-d38151c2026f.png)

Check your path variable

**Comment by ilsochrist** [comment]
![image](https://user-images.githubusercontent.com/100448527/168434698-fc74f8fe-0424-4352-a9f3-5cb83ecdc35a.png)

**Comment by RicePudding0xL** [comment]
> @AsuKaur Try: `npm i glob@7.2.0`

This worked for me PogU

**Comment by THEG77** [comment]
> @AsuKaur Try: `npm i glob@7.2.0`

This worked for me PogU

**Comment by alzo91** [comment]
> Hello everyone. I check this [react-native-community/cli#1608 (comment)](https://github.com/react-native-community/cli/issues/1608#issuecomment-1126581017) and solved with:
> 
> 1. Clear node_modules
> 2. add this to package.json
>    `"resolutions": { "glob": "7.2.0"   }`
> 3. Reinstall node_modules with `npm install`
> 
> And you may vote this result on stackoverflow https://stackoverflow.com/questions/72239857/react-native-android-project-not-found/72241166#72241166
> 
> If this is not work please install glob with `npm i glob@7.2.0`

This worked for me. thanks a milion.

**Comment by shxinlei** [comment]
> This doesn't work for me. Anything else I can try?

This doesn't work for me. Anything else I can try? JAVA_HOME is correct and also tries' NPM I glob@7.2.0 '

**Comment by shxinlei** [comment]
> ![image](https://user-images.githubusercontent.com/100448527/168434698-fc74f8fe-0424-4352-a9f3-5cb83ecdc35a.png)

This doesn't work for me. Anything else I can try? JAVA_HOME is correct and also tries' NPM I glob@7.2.0 '

**Comment by shxinlei** [comment]
![image](https://user-images.githubusercontent.com/54462126/168437175-0776e91a-e6ac-4ab8-bc7a-fbcdf2a08a6c.png)
![image](https://user-images.githubusercontent.com/54462126/168437282-c03c603d-13cf-4ad6-8a39-bbb4eba2d513.png)
![image](https://user-images.githubusercontent.com/54462126/168437342-9572e74e-0352-402b-b9c5-197476b7adb2.png)

**Comment by leekhacnguyen156** [comment]
> @AsuKaur Try: `npm i glob@7.2.0`

it worked for me. Very cool bro <3

**Comment by AnkitRoyy** [comment]
> Hello everyone. I check this [react-native-community/cli#1608 (comment)](https://github.com/react-native-community/cli/issues/1608#issuecomment-1126581017) and solved with:
> 
> 1. Clear node_modules
> 2. add this to package.json
>    `"resolutions": { "glob": "7.2.0"   }`
> 3. Reinstall node_modules with `npm install`
> 
> And you may vote this result on stackoverflow https://stackoverflow.com/questions/72239857/react-native-android-project-not-found/72241166#72241166
> 
> If this is not work please install glob with `npm i glob@7.2.0`

Perfect! Thanks, Bro...

**Comment by ClenildoCardoso** [comment]
GALERA, A SOLUÇÃO É ESSA: 
npm i glob@7.2.0

**Comment by Aqibiweb** [comment]
> > Hello everyone. I check this [react-native-community/cli#1608 (comment)](https://github.com/react-native-community/cli/issues/1608#issuecomment-1126581017) and solved with:
> > 
> > 1. Clear node_modules
> > 2. add this to package.json
> >    `"resolutions": { "glob": "7.2.0"   }`
> > 3. Reinstall node_modules with `npm install`
> > 
> > And you may vote this result on stackoverflow https://stackoverflow.com/questions/72239857/react-native-android-project-not-found/72241166#72241166
> 
> nice one

Thanks, now it's working.

**Comment by t29gupta** [comment]
> @AsuKaur Try: `npm i glob@7.2.0`

This resolved the error for me...

**Comment by nc-devw** [comment]
@THEG77 try install jdk-11. It worked for me

**Comment by THEG77** [comment]
> @THEG77 try install jdk-11. It worked for me

Hey, yeah that should work.
Turns out my `JAVA_HOME` environment variable was pointing to some older version of java.
changed it to latest version of java i had installed "java 17" and had to create a new project from scratch and it is running fine now 👍

**Comment by MobileDevStar** [comment]
> Hello everyone. I check this [react-native-community/cli#1608 (comment)](https://github.com/react-native-community/cli/issues/1608#issuecomment-1126581017) and solved with:
> 
> 1. Clear node_modules
> 2. add this to package.json
>    `"resolutions": { "glob": "7.2.0"   }`
> 3. Reinstall node_modules with `npm install`
> 
> And you may vote this result on stackoverflow https://stackoverflow.com/questions/72239857/react-native-android-project-not-found/72241166#72241166
> 
> If this is not work please install glob with `npm i glob@7.2.0`

Thanks very much!
It saved me.

**Comment by pmg-codes** [comment]
> > Hello everyone. I check this [react-native-community/cli#1608 (comment)](https://github.com/react-native-community/cli/issues/1608#issuecomment-1126581017) and solved with:
> > 
> > 1. Clear node_modules
> > 2. add this to package.json
> >    `"resolutions": { "glob": "7.2.0"   }`
> > 3. Reinstall node_modules with `npm install`
> > 
> > And you may vote this result on stackoverflow https://stackoverflow.com/questions/72239857/react-native-android-project-not-found/72241166#72241166
> > If this is not work please install glob with `npm i glob@7.2.0`
> 
> This worked for me. thanks a milion.


Hello, this doesn't clear up things. Where will I put `"resolutions": { "glob": "7.2.0"   }` in package.json? 
![image](https://user-images.githubusercontent.com/84127179/168443448-772c24d7-3e18-4456-afe1-fd6b324169df.png)
thank you!! And also, do I just delete the node_modules folder? THank you so much!!!

**Comment by priami93** [comment]
> 



> Hello everyone. I check this [react-native-community/cli#1608 (comment)](https://github.com/react-native-community/cli/issues/1608#issuecomment-1126581017) and solved with:
> 
> 1. Clear node_modules
> 2. add this to package.json
>    `"resolutions": { "glob": "7.2.0"   }`
> 3. Reinstall node_modules with `npm install`
> 
> And you may vote this result on stackoverflow https://stackoverflow.com/questions/72239857/react-native-android-project-not-found/72241166#72241166
> 
> If this is not work please install glob with `npm i glob@7.2.0`

delete also package-lock.json file

**Comment by KeshavThosar** [comment]
> > > Hello everyone. I check this [react-native-community/cli#1608 (comment)](https://github.com/react-native-community/cli/issues/1608#issuecomment-1126581017) and solved with:
> > > 
> > > 1. Clear node_modules
> > > 2. add this to package.json
> > >    `"resolutions": { "glob": "7.2.0"   }`
> > > 3. Reinstall node_modules with `npm install`
> > > 
> > > And you may vote this result on stackoverflow https://stackoverflow.com/questions/72239857/react-native-android-project-not-found/72241166#72241166
> > > If this is not work please install glob with `npm i glob@7.2.0`
> > 
> > 
> > This worked for me. thanks a milion.
> 
> Hello, this doesn't clear up things. Where will I put `"resolutions": { "glob": "7.2.0" }` in package.json? ![image](https://user-images.githubusercontent.com/84127179/168443448-772c24d7-3e18-4456-afe1-fd6b324169df.png) thank you!! And also, do I just delete the node_modules folder? THank you so much!!!

Add "overrides" : {"glob" : "7.2.0"}
e.g.
![image](https://user-images.githubusercontent.com/46895675/168444243-4b31c7d5-daae-46a3-aaea-4eec935a4525.png)

Then delete `node_modules` folder and package-lock.json
Then run `npm install`

**Comment by pmg-codes** [comment]
> > 
> 
> > Hello everyone. I check this [react-native-community/cli#1608 (comment)](https://github.com/react-native-community/cli/issues/1608#issuecomment-1126581017) and solved with:
> > 
> > 1. Clear node_modules
> > 2. add this to package.json
> >    `"resolutions": { "glob": "7.2.0"   }`
> > 3. Reinstall node_modules with `npm install`
> > 
> > And you may vote this result on stackoverflow https://stackoverflow.com/questions/72239857/react-native-android-project-not-found/72241166#72241166
> > If this is not work please install glob with `npm i glob@7.2.0`
> 
> delete also package-lock.json file

Thank you! It fixed my problem!!

**Comment by mr-574rk** [comment]
![image](https://user-images.githubusercontent.com/66188165/168444972-5830ce62-1204-4db0-bd30-03be8e92daad.png)

Worked but i now get new error .

**Comment by B-Schmitz** [comment]
delete node_modules

npm i glob@7.2.0

npm install

npm run android

solved for me

**Comment by alionti998** [comment]
> @shxinlei Yep, here. I have no clue what to do. I wast half a day today.

Same here, first day learning

**Comment by mr-574rk** [comment]
Why the glob@7.2.0 .......... latest reactnative update or fix?

**Comment by juniorerivaldo** [comment]
> GALERA, A SOLUÇÃO É ESSA: npm i glob@7.2.0

valeu, deu certo aqui, achei que havia algum problema no pc até formatei ele kkk

**Comment by ilsochrist** [comment]
Ty guys solucionated

**Comment by mr-574rk** [comment]
![image](https://user-images.githubusercontent.com/66188165/168455239-92339c84-2658-4ec6-9163-1e06138bf0b5.png)
 thats working now but it says this and i nothing is wrong with the code

**Comment by opeque** [comment]
> > > Hello everyone. I check this [react-native-community/cli#1608 (comment)](https://github.com/react-native-community/cli/issues/1608#issuecomment-1126581017) and solved with:
> > > 
> > > 1. Clear node_modules
> > > 2. add this to package.json
> > >    `"resolutions": { "glob": "7.2.0"   }`
> > > 3. Reinstall node_modules with `npm install`
> > > 
> > > And you may vote this result on stackoverflow https://stackoverflow.com/questions/72239857/react-native-android-project-not-found/72241166#72241166
> > 
> > 
> > nice one
> 
> Thanks, now it's working.

It works for me, Thank you so much.

**Comment by tstampfel** [comment]
https://www.youtube.com/watch?v=AQqYPRHTTYI

**Comment by Ganeshguru5** [comment]
> delete node_modules
> 
> npm i glob@7.2.0
> 
> npm install
> 
> npm run android
> 
> solved for me

Yeah its also worked for me thank you so much

**Comment by ilsochrist** [comment]
not work solution

**Comment by somersets** [comment]
Updating Android Studio and the JDK to 18 helped me

**Comment by LeQuy-123** [comment]
the android studio not see android folder at an android project like it used to? anyone have ideal why?

**Comment by resaknitto11** [comment]
yeah works for now, thanks you for any solution

**Comment by locdo1005** [comment]
> ```
> "project": {
>     "ios": {
>       "sourceDir": "C:\\Users\\devre\\Desktop\\Study\\Code\\ReactNativeStuff\\msapp\\ios",
>       "folder": "C:\\Users\\devre\\Desktop\\Study\\Code\\ReactNativeStuff\\msapp",
>       "pbxprojPath": "C:\\Users\\devre\\Desktop\\Study\\Code\\ReactNativeStuff\\msapp\\ios\\msapp.xcodeproj\\project.pbxproj",
>       "podfile": "C:\\Users\\devre\\Desktop\\Study\\Code\\ReactNativeStuff\\msapp\\ios\\Podfile",
>       "podspecPath": null,
>       "projectPath": "C:\\Users\\devre\\Desktop\\Study\\Code\\ReactNativeStuff\\msapp\\ios\\msapp.xcodeproj",
>       "projectName": "msapp.xcodeproj",
>       "libraryFolder": "Libraries",
>       "sharedLibraries": [],
>       "plist": [],
>       "scriptPhases": []
>     },
>     "android": null
>   }
> ```
> 
> My life is ruined

Remove the android folder then run ```expo eject``` worked for me.

**Comment by aiya000** [comment]
I fixed same issue by `npx expo prebuild`
