### ISSUE TITLE
There is no Tab for Android yet ?

### ISSUE THREAD

**Issue by cjmling** [facebook/react-native#3383]
I see TabBarIOS but i can not find how to make something like that for Android. Is there way to make like that ?

I like this plugin but it often break with each update of react.
https://github.com/brentvatne/react-native-scrollable-tab-view

**Comment by mkonicek** [comment]
We don't have a core component like that, see: https://facebook.github.io/react-native/docs/known-issues.html#content

I suggest using the module you linked to and improving it.
