### ISSUE TITLE
Thread 1: "You must override the `supportedEvents` method of RCTJCoreModule"

### ISSUE THREAD

**Issue by showtan001** [facebook/react-native#33839]
### Description

Xcode run app error: 
Thread 1: "You must override the `supportedEvents` method of RCTJCoreModule"

I don't know why it's happening, can you tell me what's wrong?

### Version

0.67.2

### Output of `npx react-native info`

System:
    OS: macOS 11.5.2
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 63.46 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.10.0 - /usr/local/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 6.12.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 21, 23, 25, 26, 27, 28, 29, 30
      Build Tools: 26.0.2, 27.0.3, 28.0.2, 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7678000
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_181 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.2 => 0.67.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Xcode run app

### Snack, code example, screenshot, or link to a repository

![image](https://user-images.githubusercontent.com/32892347/168617120-61b79b5d-a2ac-4c1e-b880-8bb8917a13ff.png)

2022-05-16 22:27:16.639224+0800 PineConesGoField[59041:569305] *** Assertion failure in +[RCTEventEmitter initialize](), /Users/mac/pineconesgofield/node_modules/react-native/React/Modules/RCTEventEmitter.m:32
2022-05-16 22:27:16.759097+0800 PineConesGoField[59041:569305] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'You must override the `supportedEvents` method of RCTJCoreModule'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010e200fba __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00000001145a7ff5 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010e200de3 +[NSException raise:format:] + 0
	3   Foundation                          0x000000010f7d99b0 -[NSAssertionHandler handleFailureInFunction:file:lineNumber:description:] + 166
	4   PineConesGoField                    0x000000010894064e +[RCTEventEmitter initialize] + 334
	5   libobjc.A.dylib                     0x000000011458de53 CALLING_SOME_+initialize_METHOD + 17
	6   libobjc.A.dylib                     0x000000011458ed13 initializeNonMetaClass + 700
	7   libobjc.A.dylib                     0x000000011458fd89 _ZL24initializeAndMaybeRelockP10objc_classP11objc_objectR8mutex_ttILb0EEb + 173
	8   libobjc.A.dylib                     0x000000011459b879 lookUpImpOrForward + 668
	9   libobjc.A.dylib                     0x0000000114589d1b _objc_msgSend_uncached + 75
	10  Foundation                          0x000000010f8b4de1 _NSDescriptionWithStringProxyFunc + 41
	11  CoreFoundation                      0x000000010e198f2e __CFStringAppendFormatCore + 9154
	12  CoreFoundation                      0x000000010e19b589 _CFStringCreateWithFormatAndArgumentsReturningMetadata + 145
	13  CoreFoundation                      0x000000010e19b4f2 _CFStringCreateWithFormatAndArgumentsAux2 + 20
	14  Foundation                          0x000000010f8ada7c +[NSString stringWithFormat:] + 153
	15  PineConesGoField                    0x00000001088ddfae RCTRegisterModule + 62
	16  PineConesGoField                    0x00000001087dd239 +[RCTJCoreModule load] + 25
	17  libobjc.A.dylib                     0x0000000114595ff2 load_images + 1439
	18  ???                                 0x000000010d157e2c 0x0 + 4514479660
	19  ???                                 0x000000010d166ba5 0x0 + 4514540453
	20  ???                                 0x000000010d164ec7 0x0 + 4514533063
	21  ???                                 0x000000010d164f68 0x0 + 4514533224
	22  ???                                 0x000000010d15826b 0x0 + 4514480747
	23  ???                                 0x000000010d15cf56 0x0 + 4514500438
	24  ???                                 0x000000010d1571c2 0x0 + 4514476482
	25  ???                                 0x000000010ea05c27 0x0 + 4540357671
	26  ???                                 0x000000010ea0315e 0x0 + 4540346718
	27  ???                                 0x000000010e9fd224 0x0 + 4540322340
	28  ???                                 0x000000010e9fd025 0x0 + 4540321829
	29  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi: terminating with uncaught exception of type NSException
terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'You must override the `supportedEvents` method of RCTJCoreModule'
CoreSimulator 757.5 - Device: iPhone 11 (AB7146B7-B82B-4191-81BB-32F882405DCD) - Runtime: iOS 14.5 (18E182) - DeviceType: iPhone 11
(lldb)

**Comment by showtan001** [comment]
"Archive" is no problem, "Run" or "real machine" debugging will report this error.

**Comment by izozo** [comment]
same error help plz

**Comment by Maty0712** [comment]
在我更新到Xcode13.3.1之后也收到了这个问题

**Comment by saber-yy** [comment]
any solution here？

**Comment by wxp686** [comment]
这怎么解决的大哥？

**Comment by lhb11** [comment]
遇到同样的问题，请求解决方案

**Comment by tigerjiang** [comment]
Why close this issue. I have the same problem

**Comment by A-Happy-Fish** [comment]
update the version of jcore-react-native to V2.0.2

**Comment by PavelKabenets** [comment]
same

**Comment by KumoCloud0-0** [comment]
> update the version of jcore-react-native to V2.0.2

work for me
