### ISSUE TITLE
App Performance is very laggy after upgrade 0.64 to 0.68.1

### ISSUE THREAD

**Issue by abduliOS** [facebook/react-native#33846]
### New Version

0.68.1

### Old Version

0.64.0

### Build Target(s)

iOS and Android (both device and simulator)

### Output of `react-native info`

(node:74371) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
System:
    OS: macOS 12.0.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 505.84 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 8.5.0 - /usr/local/bin/npm
    Watchman: 2022.03.21.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7784292
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.1 => 0.68.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Issue and Reproduction Steps

I am trying to update app 0.64.0 to 0.68.1. App running successfully for both iOS and android but after that I got following issues.

1. Scrolling some what slow and laggy.
2. When I click any touchable opacity, button action trigger after 1 or  2 sec until it is just showing highlight on button.
3. Flat list render item with touchable opacity button are also behave same like point 2.
4. All kind of UI some what laggy compare with existing version.

**Comment by mtr1012** [comment]
My app has the same problem after upgrading to react native version 0.68.2 from 0.61.5

**Comment by cjhines** [comment]
I've seen a drop in performance from 0.62 to 0.68 on Android

**Comment by AbhiTomCsk** [comment]
Are your apps based on expo or bare native projects

**Comment by AbhiTomCsk** [comment]
is this for new Arch changes or without these changes

**Comment by cjhines** [comment]
> is this for new Arch changes or without these changes

New architecture not enabled. Bare native project.

**Comment by AbhiTomCsk** [comment]
I think with new arch changes are main cause for these degrading cause haven't seen anyone from new arch complaining about these issues

**Comment by AbhiTomCsk** [comment]
Did someone had any resolution for this

**Comment by abduliOS** [comment]
Actually now the problem is gone for me. 
I just do upgrade the packages related to navigation and some old libraries used in the app.
After upgrade pls clear all cache in react native, iOS and android, then run.

**Comment by cjhines** [comment]
> Actually now the problem is gone for me. I just do upgrade the packages related to navigation and some old libraries used in the app. After upgrade pls clear all cache in react native, iOS and android, then run.

Do you have a package.json diff for the library upgrades? It would be very useful to see whether I have similar dependencies.

**Comment by cjhines** [comment]
> some old libraries

This is a bit vague. Could you please share a package.json diff so other people could try what solved it for you?

**Comment by tangzonglin** [comment]
> [abduliOS](/abduliOS)

This is a bit vague. Could you please share a package.json diff so other people could try what solved it for you?

**Comment by cortinico** [comment]
> Actually now the problem is gone for me.

Closing as the root issue is reported as solved
