### ISSUE TITLE
node_modules/react-native/Libraries/Renderer/shims/ReactFabric.js:18:12: error: Expected "from" but found "{" 

### ISSUE THREAD

**Issue by bandhavya** [facebook/react-native#33849]
### New Version

0.68.2

### Old Version

0.64.3

### Build Target(s)

esbuild for web preview

### Output of `react-native info`

![Uploading Screenshot 2022-05-17 at 7.13.19 PM.png…]()

### Issue and Reproduction Steps

Im just running esbuild cmds to build the index.html and preview in web.

But it breaks with the below error.
<img width="997" alt="Screenshot 2022-05-17 at 7 14 58 PM" src="https://user-images.githubusercontent.com/12510202/168825600-c1be5537-bb09-4454-9a35-64b55d85e1be.png">

The above error mentioned file (ReactFabric.js) contains
`import type {ReactFabricType} from './ReactNativeTypes';`

This line throws the error as ` **Expected "from" but found "{"**`

Whereas ReactNativeViewConfigRegistry.js file contains
`import {type ViewConfig} from './ReactNativeTypes';`

How to resolve this issue ?

**Comment by dmitryrykun** [comment]
Hello @bandhavya! Could you please share the version of Node.js that you are using. Quick mitigation would probably be to upgrading to the latest version.

**Comment by cortinico** [comment]
Closing as the author is unresposnive
