### ISSUE TITLE
Error: Failed to load plugin 'flowtype' declared in '--config » @react-native-community/eslint-config#overrides[0]': Cannot find module 'eslint-plugin-flowtype'

### ISSUE THREAD

**Issue by astrahov** [facebook/react-native#33847]
### Description

Problem appears in PhpStorm 2022.1.1

`Error: Failed to load plugin 'flowtype' declared in '--config » @react-native-community/eslint-config#overrides[0]': Cannot find module 'eslint-plugin-flowtype'`

```
// package.json

{
  // ...
  "dependencies": {
    "react": "17.0.2",
    "react-native": "0.66.4",
  },
  "devDependencies": {
    "@babel/core": "^7.17.12",
    "@babel/eslint-parser": "^7.17.0",
    "@babel/plugin-transform-react-jsx": "^7.17.12",
    "@babel/runtime": "^7.17.9",
    "@react-native-community/eslint-config": "^3.0.2",
    "babel-jest": "^26.6.3",
    "babel-plugin-module-resolver": "^4.1.0",
    "eslint": "^7.32.0",
    "eslint-import-resolver-babel-module": "^5.3.1",
    "eslint-plugin-import": "^2.26.0",
    "jest": "^26.6.3",
    "metro": "^0.66.2",
    "metro-react-native-babel-preset": "^0.66.2",
    "react-test-renderer": "17.0.2"
  },
}
```

### Version

0.66.4

### Output of `npx react-native info`

System:
    OS: macOS 12.3.1
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 121.51 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.0.1 - /usr/local/bin/node
    Yarn: Not Found
    npm: 8.3.0 - /usr/local/bin/npm
    Watchman: 2021.11.15.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 30
      Build Tools: 30.0.2
      System Images: android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8309675
    Xcode: 13.3/13E113 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.4 => 0.66.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Provide a detailed list of steps that reproduce the issue.

npx react-native some
open app in PhpStorm

**Comment by astrahov** [comment]
Similar problem, but on version RN 0.68:

https://github.com/facebook/react-native/issues/33534

**Comment by cortinico** [comment]
Closing as this was fixed by https://github.com/facebook/react-native/pull/34020
