### ISSUE TITLE
react native android modify app_name to chinese language crash

### ISSUE THREAD

**Issue by wangi4myself** [facebook/react-native#33855]
### Description

when i want to change my app disPlayName in andriod, i follow guide in youtube and google
i found the android/app/src/main/res/values/strings.xml change the app_name to chinese language, then i run "yarn android"
it's success in terminal,when i open emulator and i saw app launch but app crash after few seconds.
it confuse me the whole day
by the way ios is okay.

### Version

7.0.3

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 12.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 265.68 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.10.0 - ~/.nvm/versions/node/v16.10.0/bin/node
    Yarn: 1.22.18 - ~/.nvm/versions/node/v16.10.0/bin/yarn
    npm: 7.24.0 - ~/.nvm/versions/node/v16.10.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8512546
    Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.2 => 0.68.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

change app_name to chinese language in android/app/src/main/res/values/strings.xml

**Comment by wangi4myself** [comment]
<img width="451" alt="image" src="https://user-images.githubusercontent.com/26651458/168954082-0e5a3736-858c-4ccc-b2be-56289b3d78fa.png">
but in pakage.json 
<img width="468" alt="image" src="https://user-images.githubusercontent.com/26651458/168954130-69be0a20-1a49-4ff4-aa64-aa735cc974ce.png">

**Comment by wangi4myself** [comment]
even i run npx react-native init App --title "中文" the new App also crash in android.it is terrble for me.

**Comment by wangi4myself** [comment]
i found the problem: i use mac with intel x86 and the emulator also is the  intel x86.i use a mac with arm64 and use emulator with arm64 then it fixed.after that i use a device and it's ok。i dont konw why x86 is failde but the promble is solved. the real fact is all android device is arm64,so don't worry about it.

**Comment by shanghongshen001** [comment]
这就是为啥很多人转投flutter，rn官方有的时候真无语

**Comment by shanghongshen001** [comment]
真是付了，只有部分中文汉子不支持，比如：\u7840  其他汉子不会导致崩溃
