### ISSUE TITLE
[iOS only] App crashes with weird EXC_BAD_INSTRUCTION native error

### ISSUE THREAD

**Issue by andersonmadeira** [facebook/react-native#33854]
### Description

I'm facing a weird issue on iOS devices (simulator or physical devices) where the app crashes out of nowhere.
In Flipper's Crash Reporter I see the following error (but nothing more). Does any of you would have any idea of what is causing this?

### Error Message:

**EXC_BAD_INSTRUCTION**

Detailed message from Flipper's Crash Reporter:

https://drive.google.com/file/d/103pBBckqEbQNd11L4zowKTWXY4rAejlq/view?usp=sharing

### Version

0.67.4

### Output of `npx react-native info`

System:
    OS: macOS 11.6
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 95.14 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.0 - ~/.nvm/versions/node/v14.18.0/bin/node
    Yarn: 1.22.15 - ~/.nvm/versions/node/v14.18.0/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.0/bin/npm
    Watchman: 2022.03.14.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/anderson/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 28, 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0
      System Images: android-24 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7784292
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.2 => 17.0.2 
    react-native: ^0.67.0 => 0.67.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Open the app and wait for a network request to be made.
After a few requests are successful, one crashes.

**Comment by cipolleschi** [comment]
Hi @andersonmadeira. Have you tried to make the app crash with a debugger attached? Where does it stops?

If the app doesn't perform any network request, does it crash or not?

**Comment by hidayatNgganteng** [comment]
same in here : (
