### ISSUE TITLE
zIndex not working correctly in RN 0.69.0-rc.1

### ISSUE THREAD

**Issue by computerjazz** [facebook/react-native#33866]
### Description

In previous versions of RN, I can give views a `zIndex` that allows items that are rendered "before" sibling items to layout above those later sibling views. In 0.69.0 with new architecture enabled, sibling views that render after are always on top of previous items. 

### Version

0.69.0-rc.1

### Output of `npx react-native info`

```
System:
    OS: macOS 11.6
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Memory: 337.35 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v14.18.1/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
    Watchman: 2022.03.21.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /Users/danielmerrill/.rvm/rubies/ruby-2.7.5/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 23, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0
      System Images: android-22 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: 21.1.6352462
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8139111
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.10 - /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.0-rc.1 => 0.69.0-rc.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

- Create several sibling views that overlap each other (either with a translate or negative margin)
- Give earlier siblings a greater zIndex than later siblings
- Notice that later siblings still layout above earlier sibling

### Snack, code example, screenshot, or link to a repository

Expected:
Expo 44 snack with expected zIndex behavior (earlier items are rendered with a greater zIndex and lay out above later items):
https://snack.expo.dev/80ezQL06q
<img width="331" alt="Screen Shot 2022-05-18 at 13 47 35 " src="https://user-images.githubusercontent.com/6730148/169152998-8a536be6-937e-452f-a27a-4fc918510e18.png">

Actual:
result of the same code running on RN 69 beta (earlier items are rendered with a greater zIndex but lay out below later items):
<img width="291" alt="Screen Shot 2022-05-18 at 11 27 17 " src="https://user-images.githubusercontent.com/6730148/169153058-aa0be091-a077-4ba3-8eb0-83442209807a.png">

**Comment by joe-sam** [comment]
![image](https://user-images.githubusercontent.com/2027039/169752710-2310261a-61b6-4699-8c53-35c88f516989.png)
Appears ok on later version 0.69.RC2 testing with Android. Not checked with IOS. Can you upgrade the RC and test both your platforms?

**Comment by jgx-jay** [comment]
I had the same problem

**Comment by jgx-jay** [comment]
I had the same issue

**Comment by nstoilov** [comment]
Having the same issue with elevation, can be fixed with negative elevation, but we lose the shadow.

**Comment by cortinico** [comment]
Closing as this is related to an RC version of React Native. If the issue persists on a stable version, let's opne a new issue

**Comment by szmarczak** [comment]
@cortinico There's already an open issue for this: https://github.com/facebook/react-native/issues/38513
