### ISSUE TITLE
Possible Unhandled Promise Rejection (id: 0): "Failed to connect to play.google.com/2a00:1450:4026:804::200e:443"

### ISSUE THREAD

**Issue by chiralium** [facebook/react-native#33873]
### Description

I have this error, so the app request the source. While request is pending my app is freezing.

What is that kind of request?

### Version

0.65.2

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: Linux 5.8 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (8) x64 AMD Ryzen 7 4700U with Radeon Graphics
    Memory: 1.50 GB / 15.02 GB
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.15.4 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.10 - /usr/local/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 11.0.10 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.2 => 17.0.2 
    react-native: ^0.65.2 => 0.65.2 
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

I cant describe this. I need only information

**Comment by semencher** [comment]
I have same problem.((
How I can resolve it?

**Comment by chiralium** [comment]
To resolve this problem, change maven repository url.

**Comment by semencher** [comment]
My problem was in npm dependency react-native-appstore-version-checker and no access to console of google play from Russia.
