### ISSUE TITLE
Android HeadlessJS Crash - Tried to finish non-existent task with id

### ISSUE THREAD

**Issue by pedrolopes10** [facebook/react-native#33883]
### Description

Hi there, I've seen this crash to happen much more since Android 12 and 96% Samsung devices. 

I cannot reproduce and I do not use any library that uses Headless tasks.

Crashlytics:
Fatal Exception: java.lang.AssertionError: Tried to finish non-existent task with id 1.
       at com.facebook.infer.annotation.Assertions.assertCondition(Assertions.java:88)
       at com.facebook.react.jstasks.HeadlessJsTaskContext.finishTask(HeadlessJsTaskContext.java:173)
       at com.facebook.react.jstasks.HeadlessJsTaskContext$3.run(HeadlessJsTaskContext.java:211)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
       at java.lang.Thread.run(Thread.java:920)

Related https://github.com/facebook/react-native/issues/27597

### Version

0.68.2

### Output of `npx react-native info`

npx react-native info
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
    Memory: 10.64 GB / 31.92 GB
  Binaries:
    Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.11 - ~\AppData\Roaming\npm\node_modules\yarn\bin\yarn.CMD
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
    Watchman: 20200816.222424.0 - C:\sites\tools\watchman\bin\watchman.EXE
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7199119
    Visual Studio: Not Found
  Languages:
    Java: 11.0.14.1 - /cygdrive/c/Program Files/Eclipse Adoptium/jdk-11.0.14.101-hotspot/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.2 => 17.0.2
    react-native: ^0.68.2 => 0.68.2
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Cannot reproduce it.

**Comment by RodolfoGS** [comment]
Same issue here on Android 9+ and 94% Samsung `react-native: 0.68.2`

<img width="332" alt="image" src="https://user-images.githubusercontent.com/870365/179636953-498a4484-9827-49c2-b6e7-c8ad68a941e2.png">

**Comment by dsipahioglu** [comment]
Having the same issue and I'm unable to reproduce the issue

**Comment by pedrolopes10** [comment]
That's the issue, I cannot reproduce it in any ways and I have a Samsung with Android 12. Never saw the crash happening but I have some users complaining about it.

**Comment by Saad-Bashar** [comment]
I am having this same as well. Mostly on android samsung 12. Not sure how to reproduce this issue.

**Comment by cortinico** [comment]
> That's the issue, I cannot reproduce it in any ways and I have a Samsung with Android 12. Never saw the crash happening but I have some users complaining about it.

We can't really help further without a reproducer

**Comment by Saad-Bashar** [comment]
Did you guys figure out any fix for this? It seems that this particular code is written here in react native repo, https://github.com/facebook/react-native/blob/main/ReactAndroid/src/main/java/com/facebook/react/jstasks/HeadlessJsTaskContext.java#L174

**Comment by pedrolopes10** [comment]
Nope, and yes it looks like that particular code is the responsible, maybe don't throw exception if doesn't find the task to finish?

**Comment by Saad-Bashar** [comment]
Yeah as long as the app does not crash :(

**Comment by amrit-sahoo** [comment]
Did any one got the fix for this crash?

**Comment by Saad-Bashar** [comment]
Nope happening still 😅

**Comment by paulkiren** [comment]
I am having same issue

**Comment by malikzype** [comment]
Still having same issue

**Comment by malikzype** [comment]
Did anyone got solution for this issue?

**Comment by malikzype** [comment]
@Saad-Bashar What did you comment on in HeadlessContext class? Can you please help

**Comment by malikzype** [comment]
@pedrolopes10 Did you find any solutions?

**Comment by pedrolopes10** [comment]
> @pedrolopes10 Did you find any solutions?

Nope, still happening here

**Comment by tsachit** [comment]
any update here?

**Comment by malikzype** [comment]
Yes, even we are facing this issue.

**Comment by HarshitMadhav** [comment]
facing this issue +1

**Comment by llamington** [comment]
Facing this issue

**Comment by michaelpomogajko** [comment]
Same issue here
