### ISSUE TITLE
[TOO BIG formatValueCalls 224 exceeded limit of 200]

### ISSUE THREAD

**Issue by Sreelakshmi192** [facebook/react-native#33886]
✋ To keep the backlog clean and actionable, issues will be
🚫 closed if they do not follow one of the issue templates:
👉 https://github.com/facebook/react-native/issues/new/choose

Getting this error frequently from app(xcode log)

My react native version :  "0.64.2",

  OS: macOS 11.4
    CPU: (8) x64 Apple M1
    Memory: 25.67 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.22.12 - ~/.nvm/versions/node/v12.22.12/bin/node
    Yarn: 1.22.18 - ~/Documents/Projects/mobileApp/node_modules/.bin/yarn
    npm: 8.10.0 - ~/.nvm/versions/node/v12.22.12/bin/npm
    Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7935034
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.2 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by cortinico** [comment]
Closing as this issue is not following the issue template
