### ISSUE TITLE
 Can not debug in react native for Android (v 0.12.0)  

### ISSUE THREAD

**Issue by awesomepankaj** [facebook/react-native#3389]
node(4.0) 
Ubuntu12.04
Chrome Version 44.0.2403.130 (64-bit)

Failed to run launchChromeDevTools.applescript { [Error: Command failed: /home/awesomepankaj/Work/lifemakerProjects/workingLifemaker/LifeMaker/node_modules/react-native/packager/launchChromeDevTools.applescript http://localhost:8081/debugger-ui
/usr/bin/env: osascript: No such file or directory
]
  killed: false,
  code: 127,
  signal: null,
  cmd: '/home/awesomepankaj/Work/lifemakerProjects/workingLifemaker/LifeMaker/node_modules/react-native/packager/launchChromeDevTools.applescript http://localhost:8081/debugger-ui' }

/usr/bin/env: osascript: No such file or directory

**Comment by ide** [comment]
The tools are supported only on OS X (osascript is Apple Script).

**Comment by awesomepankaj** [comment]
Then how do I make a react native app on ubuntu? I am a student from a village in Himachal Pradesh, India and I can't afford to buy a mac. Also have put so much effort in learning react native and making my app's static screens on it. It will go to waste :(

**Comment by morenoh149** [comment]
@awesomepankaj you'll only be able to build an android app if you don't have an apple computer.

**Comment by mastersilv3r** [comment]
@morenoh149 the idea is to build an android app only for MVP. IOS can come later. Is there a way to debug in ubuntu?

**Comment by morenoh149** [comment]
@mastersilv3r not sure. Though I'm pretty sure you can do android dev on linux. So you might be able to make it work.

**Comment by satya164** [comment]
Open http://localhost:8081/debugger-ui in a chrome tab when packager is running. And then choose "Debug in Chrome" in the device. You'll be able to use the dev tools.

The only part that doesn't work on Linux right now is opening Chrome automatically.

**Comment by awesomepankaj** [comment]
Thanks a lot it is life saver for me.
