### ISSUE TITLE
JSI Performance is noticeably poor when working with Arrays

### ISSUE THREAD

**Issue by friyiajr** [facebook/react-native#33898]
### Description

In order to learn the new React-Native JSI I've been playing around trying to re-implement Lodash to see if I can get any performance improvements from using C++. I noticed a major issue though when trying to reimplement the max function. Basically, in order to calculate max you need to iterate over an array and at each iteration check if a value is greater then a max and re-assign. The code looks like this:

```
/// Revieves an array of numbers and returns the max
JSI_HOST_FUNCTION(jsiMax) {
  auto rawArray = args[0].asObject(rt);
  auto array = rawArray.asArray(rt);
  
  auto rawLength = rawArray.getProperty(rt, "length");
  auto length = rawLength.asNumber();
  
  if(length == 0) {
    return jsi::Value(nullptr);
  }
  
  auto max = DBL_MIN;
  
  for(auto i = 0; i < length; i++) {
    auto currentVal = array.getValueAtIndex(rt, i).asNumber();
    if(currentVal > max) {
      max = currentVal;
    }
  }
  
  return jsi::Value(max);
}
```

The call looks like this:
```
const result = _.max(sampleVals);
```

Problem is, even though this function is in C++ it is visually slower then the equivalent JS function. I don't need to benchmark, the performance difference is obvious. 
```
  const max = (allNums: number[]) => {
    let max = -9999;

    for (let i = 0; i < allNums.length; i++) {
      if (allNums[i] > max) {
        max = allNums[i];
      }
    }

    return max;
  };
```

I seem to have isolated the performance issue down to this line:
```
auto currentVal = array.getValueAtIndex(rt, i).asNumber();
```

It seems `getValueAtIndex` is really slow for some reason. Is there a way to optimize? Or is this just slow for now?

### Version

0.64.0

### Output of `npx react-native info`

```
System:
    OS: macOS 12.3.1
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 483.99 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.3 - ~/.nvm/versions/node/v14.18.3/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8092744
    Xcode: 13.0/13A233 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.13 - /usr/bin/javac
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

JSI is really hard to set up so just clone my project here:

https://github.com/friyiajr/react-native-fast-lodash

Then check out the branch:

`bad-performance`

Run the app using:

`yarn example ios`

After that go the the example's  `App.tsx` file. After that you can go to line 42. Then comment and uncomment functions as necessary. 

```
  const computeResult = () => {
    // const result = _.max(sampleVals);
    const result = max(sampleVals);
    Alert.alert(`Your answer: ${result}`);
  };
```

The underscore implementation is C++ whereas the non underscore implementation is just some plain JS. When you click on Compute result it will be obvious how much slower the C++ implementation is. You can click `Compute Result` to see the function results

### Snack, code example, screenshot, or link to a repository

https://github.com/friyiajr/react-native-fast-lodash

**Comment by dmitryrykun** [comment]
@friyiajr thank you for flagging, we will definitely take a look!
