### ISSUE TITLE
react-native run-ios --verbose    ->  does not produce verbose output

### ISSUE THREAD

**Issue by stevenmathers** [facebook/react-native#33905]
### Description

title says it all.  

### Version

0.64.1

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 11.6.3
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Memory: 406.70 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.0.0 - ~/.nvm/versions/node/v12.0.0/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v12.0.0/bin/npm
    Watchman: 2021.09.13.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/stevemathers/.rvm/rubies/ruby-3.0.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 27, 28, 29, 30
      Build Tools: 22.0.1, 23.0.0, 23.0.1, 23.0.2, 23.0.3, 24.0.0, 24.0.1, 25.0.0, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 27.0.1, 27.0.3, 28.0.0, 28.0.3, 29.0.2, 30.0.3, 31.0.0, 32.0.0
      System Images: android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: 20.0.5594570
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7486908
    Xcode: 13.0/13A5212g - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_121 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: 4.13.0 => 4.13.0 
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.1 => 0.64.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

try it

### Snack, code example, screenshot, or link to a repository

react-native run-ios --verbose

**Comment by cortinico** [comment]
> react-native run-ios --verbose

Closing as this is duty of the CLI. Please open an issue here:
https://github.com/react-native-community/cli/issues

Plus consider updating the RN version
