### ISSUE TITLE
On iOS, Text lineheight does not take effect when an image is embedded in a Text and starts with a picture

### ISSUE THREAD

**Issue by lxqioscoder** [facebook/react-native#33903]
### Description

<img width="776" alt="image" src="https://user-images.githubusercontent.com/17696227/170039056-4ec11cdf-5f5a-4c5a-a217-0b1da18ead43.png">

On iOS, Text lineheight does not take effect when an image is embedded in a Text and starts with a picture

### Version

0.62.0

### Output of `npx react-native info`

System:
    OS: macOS 12.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 259.59 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
    Watchman: 2021.11.15.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /Users/lixiaoqiang/.rvm/gems/ruby-2.6.3/bin/pod
  SDKs:
    iOS SDK: Not Found
    Android SDK:
      API Levels: 25, 26, 28, 29, 30
      Build Tools: 26.0.1, 28.0.3, 29.0.2, 30.0.2, 30.0.3
      System Images: android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7935034
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_202 - /usr/bin/javac
    Python: 2.7.18 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.0 => 0.62.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

const styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    text: {
        lineHeight: 30,
    },
    img: {
        height: 20,
        width: 20,
    },
});

function App() {
    return (
        <View style={styles.container}>
            <Text style={styles.text}>
                <Image
                    source={require('./images/logo.png')}
                    style={styles.img}
                />
                  
                <Text>
                    hello world hello worldhello worldhello worldhello
                    worldhello worldhello world
                </Text>
            </Text>
        </View>
    );
}

export default App;

### Snack, code example, screenshot, or link to a repository

<img width="776" alt="image" src="https://user-images.githubusercontent.com/17696227/170039056-4ec11cdf-5f5a-4c5a-a217-0b1da18ead43.png">

**Comment by okaybeydanol** [comment]
I don't understand exactly what you want to do, but you need to write string data inside the text component. No other components are written. If you are doing it to show on the same line, you should do it like this.

```
import React from 'react';
import {View, Text, Image, StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  text: {
    lineHeight: 30,
  },
  img: {
    height: 20,
    width: 20,
  },
});

function App() {
  return (
    <View style={styles.container}>
      <View
        style={{
          flexDirection: 'row',
        }}>
        <Image
          source={require('./assets/images/rocket.png')}
          style={styles.img}
        />
        <Text style={styles.text}>
          hello world hello worldhello worldhello worldhello worldhello
          worldhello world
        </Text>
      </View>
    </View>
  );
}

export default App;

```

**Comment by lxqioscoder** [comment]
<img width="393" alt="image" src="https://user-images.githubusercontent.com/17696227/170414317-212cce7d-e11c-468d-bc59-b3e434307d90.png">

I want to embed images inside text, not one line of text, but multiple lines

**Comment by dmitryrykun** [comment]
@lxqioscoder, did @okaybeydanol 's code work for you?

**Comment by lxqioscoder** [comment]
It doesn't work for me

**Comment by dmitryrykun** [comment]
@lxqioscoder I would suggest trying the same thing on the latest version of React Native.
If that doesn't work, please attach a reproducer in a form of GitHub repo so we could take a look on the code ourselves. And provide a detailed description what is that you are trying to achieve.

**Comment by q1992077** [comment]
I have the same issue. I want to build a RichText with <Text>. when the RichText start with an image, the lineheight doesn't work on iOS.

For example：

Start with Image.
<img width="742" alt="image" src="https://user-images.githubusercontent.com/12030299/173488428-5e62bd66-6653-4bd8-b8d5-243d289d14de.png">
<img width="386" alt="WX20220614-113707@2x" src="https://user-images.githubusercontent.com/12030299/173488501-993ca072-94d3-48ac-8d85-2b164e9fa844.png">

Start with Text.
<img width="744" alt="image" src="https://user-images.githubusercontent.com/12030299/173488635-017fa8b4-ddd9-42a3-ad5c-e9dbff2ed1fc.png">
<img width="403" alt="WX20220614-113753@2x" src="https://user-images.githubusercontent.com/12030299/173488659-8138abe3-140c-4c62-80a9-56e9ab8ada66.png">

**Comment by DBCintron** [comment]
@dmytrorykun I'm also experiencing the same issue. It seems like the original post provides sufficient explanation of the issue. Why is author feedback required here?

**Comment by DBCintron** [comment]
@dmytrorykun It seems like this issue has been present for some time and mistakenly marked previously https://github.com/facebook/react-native/issues/17750
