### ISSUE TITLE
 libc.so unknown crash in firebase crashlytics dashboard

### ISSUE THREAD

**Issue by nmanvitha** [facebook/react-native#33917]
### Description

Andriod App is frequently crashing due to libc.so unknown error. can't able to reproduce the issue.
<img width="1700" alt="Screenshot 2022-05-26 at 6 21 49 PM" src="https://user-images.githubusercontent.com/103576205/170492717-86425327-958d-45df-8df9-75a98bf6edec.png">

Here are the dependencies
 "@burstware/react-native-portal": "^1.0.2",
    "@react-native-community/async-storage": "^1.9.0",
    "@react-native-community/datetimepicker": "3.0.0",
    "@react-native-community/geolocation": "^2.0.2",
    "@react-native-community/masked-view": "^0.1.7",
    "@react-native-community/netinfo": "^5.9.5",
    "@react-native-community/progress-bar-android": "^1.0.3",
    "@react-native-community/progress-view": "@1.1.1",
    "@react-native-firebase/analytics": "^7.4.2",
    "@react-native-firebase/app": "^8.3.1",
    "@react-native-firebase/crashlytics": "^8.3.3",
    "@react-navigation/bottom-tabs": "5.2.6",
    "@react-navigation/drawer": "5.0.5",
    "@react-navigation/material-bottom-tabs": "5.1.7",
    "@react-navigation/material-top-tabs": "5.1.7",
    "@react-navigation/native": "5.1.4",
    "@react-navigation/native-stack": "5.0.5",
    "@react-navigation/stack": "5.2.9",
    "android": "^0.0.8",
    "axios": "^0.19.2",
    "format-string-by-pattern": "^1.2.1",
    "jail-monkey": "^2.3.2",
    "jsc-android": "^245459.0.0",
    "moment": "^2.24.0",
    "patch-package": "^6.4.7",
    "prop-types": "^15.7.2",
    "react": "16.11.0",
    "react-native": "0.62.1",
    "react-native-add-calendar-event": "3.0.2",
    "react-native-awesome-card-io": "^0.8.3",
    "react-native-background-timer": "^2.2.0",
    "react-native-collapsible": "^1.5.2",
    "react-native-config": "1.3.3",
    "react-native-device-info": "^5.6.1",
    "react-native-document-picker": "^4.1.0",
    "react-native-easy-toast": "^1.2.0",
    "react-native-exit-app": "^1.1.0",
    "react-native-fs": "2.16.6",
    "react-native-gesture-handler": "1.8.0",
    "react-native-get-random-values": "^1.4.0",
    "react-native-htmlview": "^0.15.0",
    "react-native-image-base64": "0.1.4",
    "react-native-image-picker": "2.3.1",
    "react-native-image-resizer": "1.2.3",
    "react-native-image-zoom-viewer": "3.0.1",
    "react-native-in-app-review": "^2.1.5",
    "react-native-languages": "^3.0.2",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-localization": "^2.1.6",
    "react-native-map-clustering": "^3.3.4",
    "react-native-maps": "^0.27.1",
    "react-native-modal": "^11.5.6",
    "react-native-orientation-locker": "^1.0.21",
    "react-native-pdf": "^6.2.0",
    "react-native-permissions": "2.1.4",
    "react-native-picker-select": "^6.6.0",
    "react-native-rate": "^1.2.1",
    "react-native-reanimated": "^1.8.0",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-screens": "@2.4.0",
    "react-native-share": "^5.1.0",
    "react-native-signature-capture": "^0.4.11",
    "react-native-snap-carousel": "^3.9.0",
    "react-native-splash-screen": "^3.2.0",
    "react-native-sqlite-storage": "https://github.com/leorajdsouza/react-native-sqlite-storage.git",
    "react-native-svg": "^12.1.0",
    "react-native-tab-view": "2.13.0",
    "react-native-touch-id": "^4.4.1",
    "react-native-user-inactivity": "^1.1.0",
    "react-native-vector-icons": "6.6.0",
    "react-native-webview": "~9.1.4",
    "react-redux": "^7.2.0",
    "reanimated-bottom-sheet": "^1.0.0-alpha.19",
    "redux": "^4.0.5",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.3.0",
    "rn-fetch-blob": "^0.12.0",
    "rn-secure-storage": "^2.0.4",
    "underscore": "^1.12.0"

### Version

0.62.1

### Output of `npx react-native info`

<img width="1295" alt="Screenshot 2022-05-26 at 6 22 04 PM" src="https://user-images.githubusercontent.com/103576205/170493244-42b6bb7b-9cdb-4c56-992c-8bee003e25fc.png">

### Steps to reproduce

Got in Firebase Crashlytics

### Snack, code example, screenshot, or link to a repository

No response

**Comment by dmitryrykun** [comment]
Closing as duplicate of https://github.com/facebook/react-native/issues/33916

**Comment by HessiPard** [comment]
> Closing as duplicate of #33916

hi, i have the same issue and this is not duplicate of issue that you referred !!
it happens only on android 11 devices randomly and related to libc.so

**Comment by cortinico** [comment]
> it happens only on android 11 devices randomly and related to libc.so

libc is not part of React Native.

Moreover, without full stacktrace + reproducer, we can't really debug/fix this in any form.

Plus you're on a really old version of React Native. I would advice updating and re-opening a new issue on top of 0.68 if the issue persists

**Comment by cnx-caiobarroso** [comment]
This shouldn't be closed!
This issue is still occurring on react-native "0.72.3", hermes enabled.

Even if this isn't a part of react-native, could you please look at what could be causing it? We can't reproduce on our own and it is affecting the crash %.

Here are stack traces provided by Firebase Crashlytics on some of the crashes.

P.S: one of the stack traces below includes libreactnativejni.so, libfbjni.so, libopenjdk.so, so maybe it does makes part of react-native.

[br.com.myapp_issue_eb3e8632316c0c4166e96a314b244953_crash_session_65b6d6740326000161818e5dcc410bc2_DNE_0_v2_stacktrace.txt](https://github.com/facebook/react-native/files/14127157/br.com.myapp_issue_eb3e8632316c0c4166e96a314b244953_crash_session_65b6d6740326000161818e5dcc410bc2_DNE_0_v2_stacktrace.txt)

[br.com.myapp_issue_eb3e8632316c0c4166e96a314b244953_crash_session_65bb775301b800011a8ea48afb4106a2_DNE_0_v2_stacktrace.txt](https://github.com/facebook/react-native/files/14127159/br.com.myapp_issue_eb3e8632316c0c4166e96a314b244953_crash_session_65bb775301b800011a8ea48afb4106a2_DNE_0_v2_stacktrace.txt)

**Comment by cortinico** [comment]
> Even if this isn't a part of react-native, could you please look at what could be causing it? We can't reproduce on our own and it is affecting the crash %.

How can we take a look into it without a reproducre?

**Comment by cnx-caiobarroso** [comment]
I meant to take a look at the stack traces, sorry.

**Comment by cortinico** [comment]
> I meant to take a look at the stack traces, sorry.

The stack traces have no references of react-native. There is a reference of libjsc. I can suggest to move over to Hermes as, even if there were to be a bug inside jsc, we would not be able to fix.

There is not much we can do with the current information

**Comment by cnx-caiobarroso** [comment]
OK, I'll move over to Hermes to try and fix this, thanks.

**Comment by thisisadarshjaiswal** [comment]
Was it fixed @cnx-caiobarroso?This has given a spike in our matrix!!
