### ISSUE TITLE
TabBarIOS.Item expects a children?

### ISSUE THREAD

**Issue by dzannotti** [facebook/react-native#3391]
This being either a docs mistake or a un-necessary `onlyChild` requirement.
Currently having `selected={true}` requires an icon only tab bar item to have an empty view children to avoid an invariant.

See repro without:
https://rnplay.org/apps/VdDIog

And repro with:
https://rnplay.org/apps/8ESnuA

**Comment by brentvatne** [comment]
As discussed in Slack, this is actually intentional because the children are the content for that tab :)
