### ISSUE TITLE
Non-fatal Exception: JavaScriptError fetch is not a function. (In 'fetch(*URL*)', 'fetch' is false)

### ISSUE THREAD

**Issue by Himatheja** [facebook/react-native#33928]
### Description

Fatal Exception: RCTFatalException: Unhandled JS Exception: TypeError: fetch is not a function. (In 'fetch("https://maps.googleapis.com/maps/api/geocode/json?address="+t+","+n+"&key="+C.default.GOOGLE_MAPS_API_KEY)', 'fetch' is false)
0  CoreFoundation                 0x99288 __exceptionPreprocess
1  libobjc.A.dylib                0x16744 objc_exception_throw
2  React                          0x7780 (Missing UUID 420670176ef53399a442809d102c11d8)
3  CoreModules                    0x16638 (Missing UUID 1952104d40513806887c29fc46d14bec)
4  CoreModules                    0x16f4c (Missing UUID 1952104d40513806887c29fc46d14bec)
5  CoreFoundation                 0x21b24 __invoking___
6  CoreFoundation                 0x3f610 -[NSInvocation invoke]
7  CoreFoundation                 0x765fc -[NSInvocation invokeWithTarget:]
8  React                          0x38abc (Missing UUID 420670176ef53399a442809d102c11d8)
9  React                          0x3ac74 (Missing UUID 420670176ef53399a442809d102c11d8)
10 React                          0x3a9d8 (Missing UUID 420670176ef53399a442809d102c11d8)
11 libdispatch.dylib              0x1e6c _dispatch_call_block_and_release
12 libdispatch.dylib              0x3a30 _dispatch_client_callout
13 libdispatch.dylib              0xb124 _dispatch_lane_serial_drain
14 libdispatch.dylib              0xbc80 _dispatch_lane_invoke
15 libdispatch.dylib              0x16500 _dispatch_workloop_worker_thread
16 libsystem_pthread.dylib        0x10bc _pthread_wqthread
17 libsystem_pthread.dylib        0xe5c start_wqthread

This issue is happening on iOS real devices and not on simulator.

### Version

0.63.3

### Output of `npx react-native info`

System:
    OS: macOS 12.4
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 63.66 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 3.2.0 - /usr/local/bin/yarn
    npm: 8.11.0 - /usr/local/bin/npm
    Watchman: 2022.05.16.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 13.3/13E113 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.1 => 17.0.2 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

- Checked on simulator and is working fine.
- upload build to testflight and checked on real device. App is crashing when its calling the fetch function.

### Snack, code example, screenshot, or link to a repository

<img width="963" alt="Screenshot 2022-05-30 at 9 52 35 AM" src="https://user-images.githubusercontent.com/29119638/170923877-cf99e302-f253-4bf9-b068-27c64a296ac6.png">

**Comment by dmitryrykun** [comment]
Hello @Himatheja, I can see that you are using quite old version of react-native. I suggest updating it tho the latest one.
If problem persists, please create new issue, following the issue template.
