### ISSUE TITLE
PermissionsAndroid doesn't support READ_VOICEMAIL

### ISSUE THREAD

**Issue by babraham123** [facebook/react-native#33922]
### Description

PermissionsAndroid supports ADD_VOICEMAIL but not READ_VOICEMAIL. Looks like a simple oversight.
https://developer.android.com/reference/android/Manifest.permission#READ_VOICEMAIL

### Version

0.61.5

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 12.3.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 312.64 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.5.3 - /usr/local/bin/npm
    Watchman: 2022.03.21.00 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 23, 28, 29, 30, 32
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 32.0.0
      System Images: android-29 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7935034
    Xcode: 13.4/13F17a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
  npmGlobalPackages:
    react-native-safe-area-context: 4.2.5

### Steps to reproduce

Attempted to run `request` on the unsupported permission.

### Snack, code example, screenshot, or link to a repository

```
const granted = await PermissionsAndroid.request(
          PermissionsAndroid.PERMISSIONS.READ_VOICEMAIL);
```

**Comment by cortinico** [comment]
You're right. We actually miss both `READ_VOICEMAIL` and `WRITE_VOICEMAIL`. Don't you mind sending a PR with those two (should be as easy as #32282). I'll be happy to review and merge them @babraham123
