### ISSUE TITLE
[Android] ScrollView onScroll event is not smoothly when page changed with "pagingEnabled" even though using native animated driver.

### ISSUE THREAD

**Issue by bolan9999** [facebook/react-native#33925]
### Description

ScrollView onScroll event is not smoothly when page changed with "pagingEnabled" even though using native animated driver. Android so far.

### Version

0.66.3

### Output of `npx react-native info`

System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 6.50 GB / 15.80 GB
  Binaries:
    Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 28, 29, 30, 32
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 32.0.0, 32.1.0
      System Images: android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version     2021.1.0.0 AI-211.7628.21.2111.8193401
    Visual Studio: Not Found
  Languages:
    Java: 1.8.0_60 - /c/Program Files/Java/jdk1.8.0_60/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.66.3 => 0.66.3
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. open [the snack](https://snack.expo.dev/WoHXh2WAU)
2. run on android
3. try to drag to change page.
4. the red view will shake.

However, it will work fine if I disable `pagingEnabled`

### Snack, code example, screenshot, or link to a repository

The example is [here](https://snack.expo.dev/WoHXh2WAU)

**Comment by dmitryrykun** [comment]
Hello @bolan9999, I can't see any shaking in the suggested snack. Could you please update the snack so the problem is more evident.

**Comment by dmitryrykun** [comment]
@bolan9999 I've updated the snack a little bit, so it easier to see that something is actually scrolling. https://snack.expo.dev/uLA_LneN8
I can't see any shaking. Could you please record a video that shows the problem?

**Comment by bolan9999** [comment]
??? why did you update it like this ?

The point is the transform on the red view...................

**Comment by bolan9999** [comment]
Are you sure you ran it on Android? Swipe to switch page and then focus on the red view, is is shaking when page changed (note it appears only 0.1 second)..   For some reasons ,I can not upload video.

**Comment by bolan9999** [comment]
The red view follows the x offset of the scrollview, but it is not smoothly when swiping.

**Comment by bolan9999** [comment]
If you do not know what I say, you can set `pagingEnabled=false`,  compare the red view's effect.
