### ISSUE TITLE
:app:mergeReleaseResources Can't determine type for tag

### ISSUE THREAD

**Issue by jokernomade** [facebook/react-native#33926]
### Description

I'm running android studio to release an apk and suddenly I started getting the error

````
> Task :app:mergeReleaseResources FAILED
AGPBI: {"kind":"error","text":"Can't determine type for tag '<macro name=\"m3_comp_switch_disabled_selected_handle_color\">?attr/colorSurface</macro>'","sources":[{"file":"/Users/fausto/.gradle/caches/transforms-3/4948d05d0ff6027d2e3c9f4a6010103b/transformed/material-1.7.0-alpha02/res/values/values.xml"}],"tool":"Resource and asset merger"}
````

I already deleted res/drawable and run `watchman watch-del-all && rm -rf node_modules/ && yarn install && react-native start --reset-cache` and the problem still there. Last time I released an apk successfully.

### Version

0.63.4

### Output of `npx react-native info`

npx react-native info
info Fetching system and libraries information...
System:
    OS: macOS 11.6.5
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 1.17 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 17.3.0 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 8.3.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /Users/fausto/.rvm/gems/ruby-2.7.2/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      Android NDK: 16.0.4293906-beta1
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7678000
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.12 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:

### Steps to reproduce

I released the iphone sucessfully and it started happening on Android that I had released many times in the past. I didn't upgrade Android Studio, React Native, Gradle and other libs.

### Snack, code example, screenshot, or link to a repository

<img width="1440" alt="Screen Shot 2022-05-28 at 13 26 13" src="https://user-images.githubusercontent.com/3135444/170834135-c47cfbd4-bf9c-4ff9-9089-cb599824d873.png">

**Comment by jokernomade** [comment]
does anyone have a shot here ?

**Comment by jokernomade** [comment]
didn't find a solution so decided upgrade expo + react native which gave me a new problem/error https://github.com/expo/expo/issues/17692

**Comment by BegahanMan457** [comment]
Hi everybody
İ fix this problem with it
implementation 'androidx.appcompat:appcompat:1.4.1'
implementation 'com.google.android.material:material:1.6.0'

**Comment by jokernomade** [comment]
I fixed by installing fresh expo + react-native. Pain in the ass.

**Comment by BEHROUZ-RZ** [comment]
I fix this problem by changing the version of material design 
i hope this can help someone

**Comment by daniel-iroka** [comment]
@BegahanMan457 Thanks! It worked. Maybe there is a bug in the new version.

**Comment by heetsamber** [comment]
@BegahanMan457  Thanks !!! you are my life saver

**Comment by verkee** [comment]
> Hi everybody İ fixed this problem with it implementation 'androidx.appcompat:appcompat:1.4.1' implementation 'com.google.android.material:material:1.6.0'

but ，there is  an error about " Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.7.1, expected version is 1.5.1."

**Comment by xgenem** [comment]
> Hi everybody İ fixed this problem with it implementation 'androidx.appcompat:appcompat:1.4.1' implementation 'com.google.android.material:material:1.6.0'

Which file did you change this from? I don't see it on my app/build.gradle file

**Comment by webiworkdeepak** [comment]
i am getting error : Can't determine type for tag '<macro name="m3_comp_assist_chip_container_shape">?attr/shapeAppearanceCornerSmall</macro>'.  Does anybody have any idea.

**Comment by webiworkdeepak** [comment]
i am getting error : ERROR:/Users/mac/.gradle/caches/transforms-3/203761e2b95bb4e5462589fe8b85447f/transformed/material-1.8.0/res/values/values.xml: Resource and asset merger: Can't determine type for tag '<macro name="m3_comp_assist_chip_container_shape">?attr/shapeAppearanceCornerSmall</macro>' 

FAILURE: Build failed with an exception.  Does anybody have any idea??

**Comment by davshn** [comment]
> i am getting error : ERROR:/Users/mac/.gradle/caches/transforms-3/203761e2b95bb4e5462589fe8b85447f/transformed/material-1.8.0/res/values/values.xml: Resource and asset merger: Can't determine type for tag '?attr/shapeAppearanceCornerSmall'
> 
> FAILURE: Build failed with an exception. Does anybody have any idea??

i am getting the same, and the solution of @BegahanMan457 didn't fix that

**Comment by davshn** [comment]
@webiworkdeepak did you find a solution?

**Comment by scarlac** [comment]
To [the previous comment](https://github.com/facebook/react-native/issues/33926#issuecomment-1146785650) this is a dependency "bug" with the [Material (`com.google.android.material`) library](https://mvnrepository.com/artifact/com.google.android.material/material?repo=google), which in newer versions depend on a newer version of Gradle (based on other comments).

Your solution is to upgrade Gradle to 7.2.2 or newer if you need Material 1.8.0 or downgrade to version 1.6.0 if you don't really need the new features. You most likely don't need the features, so you are safe to downgrade to version 1.6.0 as upgrading Gradle usually is a large migration that is likely to break other things.

So search your codebase for (remove version to find all occurences):
```
implementation 'com.google.android.material:material:1.8.0'
```
And replace the version so it reads:
```
implementation 'com.google.android.material:material:1.6.0'
```

**Comment by neeleshyadav253** [comment]
getting an error not able to solved it tried evry solution 

.gradle/caches/transforms-3/9ce6f6a30dae8079bf3178590780931a/transformed/material-1.9.0/res/values/values.xml: Resource and asset merger: Can't determine type for tag '<macro name="m3_comp_assist_chip_container_shape">?attr/shapeAppearanceCornerSmall</macro>'

**Comment by rpdave** [comment]
If no matter what version you set, you still see the error `transformed/material-1.9.0/` then that means there is some dep that is asking for a newer version of material and so Gradle is providing that version.

One way to check who is asking for a newer version is to use the command `./gradlew build --scan` a scan can tell you who is bringing in a newer version.

Finally, to force your Gradle build to use a version you want is to downgrade the dependency using strictly - https://docs.gradle.org/current/userguide/dependency_downgrade_and_exclude.html#sec:enforcing_dependency_version

in your app/build.gradle add this

```
    implementation ('com.google.android.material:material:1.6.0') {
        version {
            strictly '1.6.0'
        }
    }
```

**Comment by neeleshyadav253** [comment]
> If no matter what version you set, you still see the error `transformed/material-1.9.0/` then that means there is some dep that is asking for a newer version of material and so Gradle is providing that version.
> 
> One way to check who is asking for a newer version is to use the command `./gradlew build --scan` a scan can tell you who is bringing in a newer version.
> 
> Finally, to force your Gradle build to use a version you want is to downgrade the dependency using strictly - https://docs.gradle.org/current/userguide/dependency_downgrade_and_exclude.html#sec:enforcing_dependency_version
> 
> in your app/build.gradle add this
> 
> ```
>     implementation ('com.google.android.material:material:1.6.0') {
>         version {
>             strictly '1.6.0'
>         }
>     }
> ```

this works for me thank you I was using node 14.20 and I changed it to 16.80 after that  I was able to build my code some libraries won't support 14.20 and for old application you may need to change native-base , 

implementation 'androidx.appcompat:appcompat:1.4.1'
implementation 'com.google.android.material:material:1.6.0'


used strictly after that my error was resolved

**Comment by FraserKemp** [comment]
> If no matter what version you set, you still see the error `transformed/material-1.9.0/` then that means there is some dep that is asking for a newer version of material and so Gradle is providing that version.
> 
> One way to check who is asking for a newer version is to use the command `./gradlew build --scan` a scan can tell you who is bringing in a newer version.
> 
> Finally, to force your Gradle build to use a version you want is to downgrade the dependency using strictly - https://docs.gradle.org/current/userguide/dependency_downgrade_and_exclude.html#sec:enforcing_dependency_version
> 
> in your app/build.gradle add this
> 
> ```
>     implementation ('com.google.android.material:material:1.6.0') {
>         version {
>             strictly '1.6.0'
>         }
>     }
> ```

This works for me as well, cant thank you enough. Makes total sense as well. going to scan anyway and try to find the root of the problem !

**Comment by vidurajith-darshana** [comment]
> If no matter what version you set, you still see the error `transformed/material-1.9.0/` then that means there is some dep that is asking for a newer version of material and so Gradle is providing that version.
> 
> One way to check who is asking for a newer version is to use the command `./gradlew build --scan` a scan can tell you who is bringing in a newer version.
> 
> Finally, to force your Gradle build to use a version you want is to downgrade the dependency using strictly - https://docs.gradle.org/current/userguide/dependency_downgrade_and_exclude.html#sec:enforcing_dependency_version
> 
> in your app/build.gradle add this
> 
> ```
>     implementation ('com.google.android.material:material:1.6.0') {
>         version {
>             strictly '1.6.0'
>         }
>     }
> ```

When upgrading to Android 14, API level 34 I had the same issue. one dependency breaks my app. I updated that dependency as below. then it worked with this solution

`"react-native-screens": "3.13.1",  ->  "react-native-screens": "3.25.0",`

**Comment by asifh2060** [comment]
thank you so much @vidurajith-darshana  after 2 days it's fixed with your give details
