### ISSUE TITLE
Not able to build android on Windows despite following documentation

### ISSUE THREAD

**Issue by frags51** [facebook/react-native#33921]
### Description

I am trying to build React-Native Android source on Windows. On running `yarn install-jsc-android` in rn-tester package, I get the following error:

```
Task :packages:rn-tester:android:app:buildCodegenCLI FAILED

`Execution failed for task ':packages:rn-tester:android:app:buildCodegenCLI'. A problem occurred starting process 'command 'bash''
```

I have the pre-requisites (SDK, NDK) installed. Can someone help on how to solve this? Is this a bug in documentation? https://github.com/facebook/react-native/wiki/Building-from-source#prerequisites seems outdated.

### Version

Latest main branch

### Output of `npx react-native info`

Latest main branch

### Steps to reproduce

Run `yarn install-jsc-android` on windows.

### Snack, code example, screenshot, or link to a repository

NA

**Comment by cortinico** [comment]
> I have the pre-requisites (SDK, NDK) installed. Can someone help on how to solve this?

Building the React Native Project (i.e. cloning this repo) is currently not supported at the moment (cc @kelset for visibility).

The problem are various, but essentially:
- There is a bash script that is invoked during the build setup, which is not playing well with Windows. Ideally rewriting that script from bash to node would help.
- There is a whole CMake build that would require you to setup Visual Studio community on your machine.
- I believe we have some hardcoded paths that are not Windows friendly somewhere in the build logic.

We're not currently focusing into supporting this at the moment, but we're focusing on offering better support for **users** of React Native on Windows.

Closing as this is a bit out of scope. Anyway if someone is looking into making the setup more Windows friendly, we'll be more than happy to review/merge.
