### ISSUE TITLE
Fabric is not The effect on Android FlatList

### ISSUE THREAD

**Issue by bozaigao** [facebook/react-native#33943]
### Description

When I turned on the Fabric switch on the Android terminal, I used the FlatList to render the long list of data, and the rendering was blank and the frame was dropped when I slid quickly

https://user-images.githubusercontent.com/12226661/171367859-a688a348-f837-48cb-b4e1-334ba1c00c04.mp4

### Version

0.68.2

### Output of `npx react-native info`

use RN 0.68.2

### Steps to reproduce

use RN 0.68.2

### Snack, code example, screenshot, or link to a repository

use RN 0.68.2

**Comment by cortinico** [comment]
> use RN 0.68.2

Could you share you repro?

**Comment by bozaigao** [comment]
@cortinico the repo url:https://github.com/bozaigao/FabircFlatListDemo,On Android I just set the newArchEnabled true and used the FlatList to render the long list

**Comment by sammy-SC** [comment]
Hello @bozaigao,

to clarify, you expect synchronous rendering to prevent white patches from appearing in flat list, is that correct?

If that's the case, that behaviour has not been implemented yet. FlatList, nor any other place in React Native, does not leverage synchronous rendering yet. The new architecture is an important milestone towards synchronous rendering but the capability is not in production at the moment.

I'm going to close this issue as the behaviour you are seeing is expected. Let me know if you have questions.

**Comment by HuJean** [comment]
> Hello @bozaigao,
> 
> to clarify, you expect synchronous rendering to prevent white patches from appearing in flat list, is that correct?
> 
> If that's the case, that behaviour has not been implemented yet. FlatList, nor any other place in React Native, does not leverage synchronous rendering yet. The new architecture is an important milestone towards synchronous rendering but the capability is not in production at the moment.
> 
> I'm going to close this issue as the behaviour you are seeing is expected. Let me know if you have questions.

When will synchronous rendering be implemented?

**Comment by sammy-SC** [comment]
hey,

some parts of it are already in the codebase, for example https://github.com/facebook/react-native/blob/main/Libraries/Components/TextInput/TextInput.js#L741

we haven't settled on how to bring synchronous rendering to React Native yet and are still iterating on it. It is challenging to make it performant and backwards compatible at the same time and evaluating what the options are.
