### ISSUE TITLE
Sometime <Text> don't render, if don't use on <View> 

### ISSUE THREAD

**Issue by thinnakrit** [facebook/react-native#33942]
### Description

I write ```<Text>``` on  ```<Fragment>``` or ```<>```,
sometime ```<Text>``` don't render and not have an error

Example my code
```
<Fragment>
    <Text>Hello</Text>
</Fragment>
```

```
<>
    <Text>Hello</Text>
</>
```

But i use on ```<View>``` can render every time

Example
```
<View>
   <Text>Hello</Text>
</View>
```

I want to know, why? and what's a problem ?

Thank for reply and answer

### Version

0.65.0

### Output of `npx react-native info`

System:
    OS: macOS 12.2
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Memory: 1.03 GB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.0 - /usr/local/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 6.14.15 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7678000
    Xcode: 13.3/13E113 - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.2 - /Library/Java/JavaVirtualMachines/jdk-15.0.2.jdk/Contents/Home/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.65.0 => 0.65.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

-

### Snack, code example, screenshot, or link to a repository

```
<Fragment>
    <Text>Hello</Text>
</Fragment>
```

```
<>
    <Text>Hello</Text>
</>
```

**Comment by dmitryrykun** [comment]
@thinnakrit could you please provide an example project. Ideally in a form of a GitHub repo.
