### ISSUE TITLE
Arabic Font getting disabled after sometime in IOS

### ISSUE THREAD

**Issue by aniketgupta8960** [facebook/react-native#33951]
### Description

I am building a gameApp which uses Arabic font.I have followed all the instruction to add the fonts .The fonts work well for sometime but after sometime suddenly the fonts gets disabled and default fonts of iphone is enabled.I am using GE SS two bold,Helsinki,KFGQPC Uthamic Regular and STC bold Font.All fonts are in ttf format.The Fonts are applied  initially and works fine in simulator but on actual device it get disabled after someTime. 

### Version

0.66.4

### Output of `npx react-native info`

System:
    OS: macOS 12.3.1
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 30.60 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.0.0 - /usr/local/bin/node
    Yarn: 1.22.10 - ~/‘~/.npm-global/bin/yarn
    npm: 8.5.5 - /usr/local/bin/npm
    Watchman: 2022.03.21.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 21, 23, 25, 27, 28, 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0
      System Images: android-28 | Google Play Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-30 | Google TV Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 13.4/13F17a - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.12 - /usr/local/opt/openjdk@11/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.4 => 0.66.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

NA

### Snack, code example, screenshot, or link to a repository

NA

**Comment by cortinico** [comment]
Closing as you left no reproducer, which is mandatory as per the issue template.
Please provide a reproducer otherwise we can't support you further.
Plus, consider also migrating to a recent version of RN
