### ISSUE TITLE
FlatList does not render item contents that are inside a "flex: 1" container when more items than initialNumToRender

### ISSUE THREAD

**Issue by philly-vanilly** [facebook/react-native#33957]
### Description

As the title explains, the problem is related to styles, but appears only on chunked results, making it very confusing. I expect either the bug to go away or some kind of a warning when "flex: 1" is used within a FlatList-item. 

I stumbled upon the solution on [Reddit](https://www.reddit.com/r/reactnative/comments/d5joqa/flatlist_breaking_above_10_items/), after wasting half a day on the problem, thinking it has something to do with key/uniqueness either of the FlatList itself or the data-provider loading the item-chunks (fetchMore/merge functions in Apollo in my case). For me, the empty content within the "flex: 1"-row was shown again after scrolling down, updating the items and as I assume, some internal counter how many items to render.

### Version

0.63.3

### Output of `npx react-native info`

```
System:    
    OS: macOS 12.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 30.32 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - /var/folders/49/bhb_wlzn3md5ml05v1rv26l00000gn/T/yarn--1654240917866-0.029791327238146037/node
    Yarn: 1.22.18 - /var/folders/49/bhb_wlzn3md5ml05v1rv26l00000gn/T/yarn--1654240917866-0.029791327238146037/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.9.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 28, 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2
      System Images: android-29 | Google APIs Intel x86 Atom, android-R | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7935034
    Xcode: 13.4/13F17a - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_242 - /usr/bin/javac
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: 0.63.3 => 0.63.3
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1. Create Flatlist with chunking (onEndReached => loadmore)
2. Load and display 10 items per chunk
3. Have a "flex: 1" row within a renderItem

### Snack, code example, screenshot, or link to a repository

![should be like this](https://preview.redd.it/egazgrb1n6n31.jpg?width=750&format=pjpg&auto=webp&s=404de8d9c9052442529ec9f725fdd78e2eebdbff)
![was like this](https://preview.redd.it/vexcb4q2n6n31.jpg?width=750&format=pjpg&auto=webp&s=cf298f3142aa5df1b8b6bec25bab5586c002c261)

**Comment by marksamfd** [comment]
I have the same problem it works well on the emulation doesn't it ??

**Comment by philly-vanilly** [comment]
@marksamfd I don't know, I was using only a real device for development and I am not working on that code/project anymore. But that would make the bug even more nasty :P
