### ISSUE TITLE
[iOS]Native UI Component didn't work

### ISSUE THREAD

**Issue by Prometheuser** [facebook/react-native#3395]
I just made a Native UI Component follow the doc:

http://facebook.github.io/react-native/docs/native-components-ios.html#content

Everything is same as the example except I use WKWebView instead MKMapView.

Here is the code:

![issue 1](https://cloud.githubusercontent.com/assets/13377095/10474578/d1b8291a-726a-11e5-8810-00a451580cf8.png)

![image](https://cloud.githubusercontent.com/assets/13377095/10474607/266eee4e-726b-11e5-9555-669adc33e7ab.png)

But when I use this component...

![image](https://cloud.githubusercontent.com/assets/13377095/10474669/fed20906-726b-11e5-8a77-3b3d9ed30684.png)

The WKWebView's frame looks strange，and I cannot scroll it, cannot click it , It just looks like not being here.And when I view UI hierarchy... The hierarchy is strange too.

![image](https://cloud.githubusercontent.com/assets/13377095/10474735/e2b5fde4-726c-11e5-8a12-bf19524f2cb3.png)

I am completely sure it is not the WKWebView issue, I tried to use UIWebView, MKMapView...

But why? I extremely suspect it is the Native UI component issue.

**Comment by jordansexton** [comment]
Do you have any info on how you resolved this issue?
