### ISSUE TITLE
Unable to resolve module perf_hooks in react native

### ISSUE THREAD

**Issue by luckyyaxianzhi** [facebook/react-native#33975]
### Description

error: Error: Unable to resolve module perf_hooks from /Users/develop/ReactNative/Test/node_modules/universal-speedtest/dist/Speedtest.js: perf_hooks could not be found within the project or in these directories: node_modules 2 | Object.defineProperty(exports, "__esModule", { value: true }); 3 | exports.Speedtest = void 0; > 4 | const perf_hooks_1 = require("perf_hooks"); | ^ 5 | const path = require("path"); 6 | const worker_threads_1 = require("worker_threads"); 7 | const UrllibHelper_1 = require("./helpers/UrllibHelper"); at ModuleResolver.resolveDependency (/Users/develop/ReactNative/Test/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:158:15) at DependencyGraph.resolveDependency (/Users/develop/ReactNative/Test/node_modules/metro/src/node-haste/DependencyGraph.js:231:43) at Object.resolve (/Users/develop/ReactNative/Test/node_modules/metro/src/lib/transformHelpers.js:129:24) at resolve (/Users/develop/ReactNative/Test/node_modules/metro/src/DeltaBundler/traverseDependencies.js:396:33) at /Users/develop/ReactNative/Test/node_modules/metro/src/DeltaBundler/traverseDependencies.js:412:26 at Array.reduce ()enter code here at resolveDependencies (/Users/develop/ReactNative/Test/node_modules/metro/src/DeltaBundler/traverseDependencies.js:411:33) at processModule (/Users/develop/ReactNative/Test/node_modules/metro/src/DeltaBundler/traverseDependencies.js:140:31) at async addDependency (/Users/develop/ReactNative/Test/node_modules/metro/src/DeltaBundler/traverseDependencies.js:230:18) at async Promise.all (index 4)

### Version

0.68.2

### Output of `npx react-native info`

system: OS: macOS 12.4 CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz Memory: 28.34 MB / 8.00 GB Shell: 5.8.1 - /bin/zsh Binaries: Node: 18.1.0 - /usr/local/bin/node Yarn: Not Found npm: 8.8.0 - /usr/local/bin/npm Watchman: 2022.03.21.00 - /usr/local/bin/watchman Managers: CocoaPods: 1.11.3 - /usr/local/bin/pod SDKs: iOS SDK: Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5 Android SDK: Not Found IDEs: Android Studio: Not Found Xcode: 13.4/13F17a - /usr/bin/xcodebuild Languages: Java: Not Found npmPackages: @react-native-community/cli: Not Found react: 17.0.2 => 17.0.2 react-native: 0.68.2 => 0.68.2 react-native-macos: Not Found npmGlobalPackages: react-native: Not Found

### Steps to reproduce

npm install --save universal-speedtest

import { UniversalSpeedtest, SpeedUnits } from "universal-speedtest";

const universalSpeedtest = new UniversalSpeedtest({
    measureUpload: true,
    downloadUnit: SpeedUnits.MBps
});
universalSpeedtest.runSpeedtestNet().then((result) => {
    console.log(result);
});

### Snack, code example, screenshot, or link to a repository

https://stackoverflow.com/questions/72514123/unable-to-resolve-module-perf-hooks-in-react-native

**Comment by cortinico** [comment]
Closing as:
- This involves this other library: https://github.com/karelkryda/universal-speedtest Please open it as an issue over there.
- You posted this also on StackOverflow so you might get a more valuable answer there.

**Comment by uthmanzaman** [comment]
did this issue get resolved?
