### ISSUE TITLE
Runtime JAR files in the classpath should have the same version. These files were found in the classpath

### ISSUE THREAD

**Issue by ezekel** [facebook/react-native#33971]
### Description

When I execute ./gradlew build, I always get this errors, and build Failed

> Task :react-native-gesture-handler:lintAnalyzeDebug
w: Runtime JAR files in the classpath should have the same version. These files were found in the classpath:
    C:/Users/taylor/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk8/1.4.10/998caa30623f73223194a8b657abd2baec4880ea/kotlin-stdlib-jdk8-1.4.10.jar (version 1.4)
    C:/Users/taylor/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.4.10/30e46450b0bb3dbf43898d2f461be4a942784780/kotlin-stdlib-jdk7-1.4.10.jar (version 1.4)
    C:/Users/taylor/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.5.20/9de35cc611bcecec8edce1d56d8e659953806751/kotlin-stdlib-1.5.20.jar (version 1.5)
    C:/Users/taylor/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.5.20/3d79dbd48bf605f4aac1e7028981a1953e245cbb/kotlin-stdlib-common-1.5.20.jar (version 1.5)
w: Some runtime JAR files in the classpath have an incompatible version. Consider removing them from the classpath

 Task :react-native-picker_picker:lintDebug FAILED
w: Runtime JAR files in the classpath have the version 1.4, which is older than the API version 1.5. Consider using the runtime of version 1.5, or pass '-api-version 1.4' explicitly to restrict the available APIs to the runtime of version 1.4. You can also pass '-la
nguage-version 1.4' instead, which will restrict not only the APIs to the specified version, but also the language features

### Version

0.68.2

### Output of `npx react-native info`

`System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 3.62 GB / 15.92 GB
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.15 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.9.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32
      Build Tools: 27.0.3, 28.0.3, 29.0.2, 29.0.3, 30.0.2, 31.0.0, 32.0.0, 32.1.0
      System Images: android-21 | Intel x86 Atom, android-21 | Intel x86 Atom_64, android-22 | Intel x86 Atom, android-22 | Intel x86 Atom_64, android-23 | Intel x86 Atom, android-23 | Intel x86 Atom_64, android-24 | Intel x86 Atom, android-24 | Intel x86 Atom_64, a
ndroid-25 | Intel x86 Atom, android-25 | Intel x86 Atom_64, android-26 | Intel x86 Atom, android-26 | Intel x86 Atom_64, android-27 | Intel x86 Atom, android-27 | Intel x86 Atom_64, android-28 | Intel x86 Atom, android-28 | Intel x86 Atom_64, android-29 | Intel x86 
Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: Not Found
  Languages:
    Java: 11.0.4 - C:\Program Files\Java\jdk-11.0.4\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.68.2 => 0.68.2
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
`

### Steps to reproduce

just run ./gradlew build

### Snack, code example, screenshot, or link to a repository

![image](https://user-images.githubusercontent.com/6830057/172359985-b06a1096-55f7-4dac-82e1-fdc524eacc36.png)

![image](https://user-images.githubusercontent.com/6830057/172360266-9c1d9f20-9bca-43cc-aa04-d936ba2666ec.png)

![image](https://user-images.githubusercontent.com/6830057/172360455-18f933da-a250-45c0-b4fb-59a5498fcba4.png)

**Comment by cortinico** [comment]
That's a warning caused by different Kotlin Jars in the classpath. You can read more about it here: 
- https://github.com/gradle/gradle/issues/16345

Practically there is no solution as of now, the warning can't be suppressed.

**Comment by minhchienwikipedia** [comment]
Any update?

**Comment by cortinico** [comment]
> Any update?

This error is resolved in the latest version of React Native (0.71+) due to updates in the Gradle version

**Comment by SirCameron** [comment]
Can the gradle version be updated with RN 0.66.5?
