### ISSUE TITLE
how to show the side menu in navigator.push

### ISSUE THREAD

**Issue by shaikhussian** [facebook/react-native#3398]
hai i am using react-native-side-menu, ,In my menu.js file,when i click on text side menu as to closed and new component as to be show,upto that part my code working,But what my problem is that when i press on button side menu as reopen again there my code not,i am struggling there 
here is my code is like this:

![screen shot 2015-10-14 at 11 45 25 am](https://cloud.githubusercontent.com/assets/11956308/10476190/29d3e51e-7269-11e5-8768-67ee56cd7f71.png)

what i want is when i press on leftButtonIcon again i want reopen the side-menu any one help me

**Comment by christopherdro** [comment]
@shaikhussian Were you able to get this working?

**Comment by christopherdro** [comment]
Hi there! This issue is being closed because it has been inactive for a while.
