### ISSUE TITLE
[iOS] Sending form data via fetch or axios leaks memory

### ISSUE THREAD

**Issue by dklymenk** [facebook/react-native#33998]
### Description

Sending files via form data with fetch or axios allocates memory 2-3 times the size of the file. The memory is not freed even after getting a response.

This is how memory usage spikes and stays the same until you kill the app.
<img width="872" alt="Screenshot 2022-06-11 at 21 40 11" src="https://user-images.githubusercontent.com/64093836/173200917-e8669736-7c31-46eb-a520-fdc6f400289f.png">

When uploading a 15.8MB file, the usage spikes by 42MB and only gets reduced by 5MB after upload finishes.
When uploading a 47.9MB file, the usage spikes by 115MB and gets reduced by 15MB after upload finishes.

This leads to crashes after uploading a few decently sized files.

### Version

0.68.2

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 12.3
    CPU: (8) arm64 Apple M1
    Memory: 99.58 MB / 16.00 GB
    Shell: 5.8.1 - /opt/homebrew/bin/zsh
  Binaries:
    Node: 18.0.0 - /opt/homebrew/bin/node
    Yarn: 1.22.18 - ~/.nvm/versions/node/v16.14.2/bin/yarn
    npm: 8.6.0 - /opt/homebrew/bin/npm
    Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.68.2 => 0.68.2
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. Create a form data object with a file attached to it
2. POST it via fetch or axios
3. Observe the app's memory usage

### Snack, code example, screenshot, or link to a repository

I have prepared a small demo project where you can upload 2 files of different sizes via fetch or axios to easily reproduce the issue.
https://github.com/dklymenk/rn-formdata-memory-leaks

<img width="300" alt="Simulator Screen Shot - iPhone 13 - 2022-06-11 at 21 55 33" src="https://user-images.githubusercontent.com/64093836/173201328-5c4b04b5-b456-4ddb-be3f-0beb1b175601.png">

**Comment by dklymenk** [comment]
I am not entirely sure if this issue is iOS-only since I wasn't able to measure the RAM usage on android because android studio profiler makes it so all the requests get aborted with Network Error, but I haven't experienced any crashes related to this issue on android, so if there is a memory leak on android, it's not as bad as on iOS.

**Comment by MichaelBorde** [comment]
Do you use Hermes or JSC ?
I don't use IOS so the following question might be irrelevant but do you think memory is used by JS runtime or native side ?
For instance on Android I monitor PSS usage and I can "guess" memory is used on Java side or JavaScript side based on where I allocate objects.

I had similar memory leak issues in the past: https://github.com/facebook/react-native/issues/26407.
I have fixed these issues by using hermes instead of JSC.

**Comment by dklymenk** [comment]
Thank you for the great tip.

Both the app I originally encountered the issue with and the demo app I created for this issue use the default JSC.

I tried Hermes on the demo app in iOS, but I encountered the issue there too.

I couldn't reliably determine if the issue occurs on android since attaching the android studio profiler to the app leads to all the requests being resulting in network error and none of my android users reported any crashes, but I can share the some additional data from xcode charts.

I am not exactly familiar with these tools but in xcode it seems like there are 2 main categories for the memory consumers: "All heap allocations" and "All anonymous VM". I can't tell which one represents JS runtime, but this is how it goes (in hermes):
<img width="991" alt="Screenshot 2022-06-13 at 17 18 33" src="https://user-images.githubusercontent.com/64093836/173376775-417fc0e4-a481-45aa-bc8f-35ff4aaa4a63.png">
There is an initial spike(at 37 sec) in "All heap allocations" about 2 times the file size. Eventually(at 42 sec) it grows up to 3 times the file size, about half way into the upload (at 57 sec) a third of that allocated memory switches to "All anonymous VM", and after that it stays like this forever. So in the end the "leaked" memory is allocated with a 2 to 1 split between "All heap allocations", "All anonymous VM".

As far as JSC goes, I think the picture is exactly the same. (Upload starts at 12 seconds mark).
<img width="527" alt="Screenshot 2022-06-13 at 17 37 37" src="https://user-images.githubusercontent.com/64093836/173378616-4ed56bac-605c-4685-b73b-f004a7ef9a45.png">

**Comment by MichaelBorde** [comment]
I have monitored PSS memory usage while uploading a 15 MB file multiple times with my application.

I have made some tests on both React Native 0.65.1 and 0.68.2.

I did not notice any significant memory increase (less than 1 MB).

**Comment by dklymenk** [comment]
This means the issue is indeed iOS only, right?

**Comment by MichaelBorde** [comment]
I have run your [rn-formdata-memory-leaks](https://github.com/dklymenk/rn-formdata-memory-leaks) project.

I have used a standalone debug apk with hermes enabled to get a very stable memory usage.

I do notice some memory increase corresponding to file size (15 MB or 50 MB) during total upload process.
I suspect this is due to the download of the file because you are creating a form data based on url.
In my test on my application, I upload a local file and I don't notice such memory increase.

Besides, after something like 20 attempts, I can see something like 30 MB of memory increase.
PSS usage was 91 MB at start then after my tests, usage was 122 MB.
I don't know if such memory will be released later (30 MB is not much).
