### ISSUE TITLE
Could not create a new pull request caused the Native codes changed could not be verified via RN Tester app.

### ISSUE THREAD

**Issue by thuongtv-vn** [facebook/react-native#33997]
### Description

Hi Guys,

I would like to add more stylistic for fontVariant by creating a new pull request. But i could not verify my locale code change via RN-TESTER app. 

I changed code directly in RCTFont.mm BUT it does not have any affect. I SAW "fontVariant=['small-caps'] BY DEFAULT also not working

I have followed this:
https://github.com/facebook/react-native/blob/main/CONTRIBUTING.md#contributing-code

**The guide is really not useful.**

Could you please help me on this? 

### Version

0.68.2

### Output of `npx react-native info`

react-native: 0.68.2

### Steps to reproduce

- Run RN-TESTER app on simulator.
- Change code RCTFont.mm file

### Snack, code example, screenshot, or link to a repository

![Simulator Screen Shot - iPhone 13 - 2022-06-10 at 17 33 47](https://user-images.githubusercontent.com/62107729/173194335-99609e10-696d-4f9b-ad8c-b258639a3ce9.png)

**Comment by cortinico** [comment]
> I changed code directly in RCTFont.mm BUT it does not have any affect. I SAW "fontVariant=['small-caps'] BY DEFAULT also not working

If you edit the code inside the `React`/`ReactAndroid` or `ReactCommon` folder and build RN-Tester, you're effectively seeing your changes.

If you don't see anything visual change, it means that there are missing implementations that needs to be written.
