### ISSUE TITLE
`contentOffset` is not working on Android

### ISSUE THREAD

**Issue by mtflud** [facebook/react-native#33994]
### Description

Passing `contentOffset` to any `ScrollView` on Android is not doing anything, looks like it's been broken since RN 0.67. Prior versions work as intended.

### Version

0.68.2

### Output of `npx react-native info`

System:
    OS: macOS 12.3.1
    CPU: (8) arm64 Apple M1
    Memory: 224.81 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.3 - ~/.nvm/versions/node/v14.17.3/bin/node
    Yarn: 1.22.11 - ~/.nvm/versions/node/v14.17.3/bin/yarn
    npm: 8.3.0 - ~/.nvm/versions/node/v14.17.3/bin/npm
    Watchman: 2022.02.21.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/mtflud/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 23, 25, 27, 28, 29, 30, 31
      Build Tools: 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0
      System Images: android-24 | ARM 64 v8a, android-30 | Google APIs ARM 64 v8a, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play ARM 64 v8a
      Android NDK: 23.1.7779620
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.68.2 => 0.68.2
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

- Create any screen with a `ScrollView` or any component that inherits from it
- Add a `contentOffset={{y: 50}}` prop to the `ScrollView`
- Observe how iOS respects this offset, but Android does nothing at all

### Snack, code example, screenshot, or link to a repository

Given the following code:

```js
import React from 'react';
import {
  SafeAreaView,
  ScrollView,
  StatusBar,
  StyleSheet,
  Text,
  useColorScheme,
  View,
} from 'react-native';

import {Colors} from 'react-native/Libraries/NewAppScreen';

const colors = ['red', 'blue', 'purple', 'green', 'black'];

const App: () => Node = () => {
  const isDarkMode = useColorScheme() === 'dark';

  const backgroundStyle = {
    backgroundColor: isDarkMode ? Colors.darker : Colors.lighter,
  };

  return (
    <SafeAreaView style={backgroundStyle}>
      <StatusBar barStyle={isDarkMode ? 'light-content' : 'dark-content'} />
      <ScrollView
        contentOffset={{y: 50}}
        contentInsetAdjustmentBehavior="automatic"
        style={backgroundStyle}>
        {Array.from({length: 5}).map((_, index) => (
          <View
            style={[styles.block, {backgroundColor: colors[index]}]}
            key={index}>
            {Array.from({length: 5}).map((_, index2) => (
              <View style={styles.line} key={`line_${index2}`}>
                <Text style={styles.text}>
                  Block {index} - Line {index2}
                </Text>
              </View>
            ))}
          </View>
        ))}
      </ScrollView>
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  block: {
    width: '100%',
  },
  line: {
    height: 50,
    width: '100%',
    borderBottomColor: 'white',
    borderBottomWidth: 1,
    justifyContent: 'center',
    paddingHorizontal: 15,
  },
  text: {
    color: 'white',
  },
});

export default App;
```

We can see that iOS is rendered initially from the desired offset (starting from Block 0 - Line 1), but Android is not.

<img width="578" alt="Screen Shot 2022-06-10 at 8 55 21" src="https://user-images.githubusercontent.com/2406654/173081801-958295c9-f107-49b2-b979-e5e97528dfbd.png">

**Comment by goriverna** [comment]
Hi all,

Any update about that ? 

In another thread I found this workaround: https://github.com/facebook/react-native/issues/30533#issuecomment-1158649237

but with this solution, we see the scroll when its already rendered

We're waiting for a fix. thank you all

**Comment by Gabrielhanna07** [comment]
Im having the same issue

**Comment by fusandy** [comment]
same with RN version 0.66.4

**Comment by Nikooos** [comment]
I still have this issue for RN version 0.70.4

**Comment by vivianmauer** [comment]
This is still an issue in version 0.71.4 🥲

**Comment by julian-jeong** [comment]
I still have this issue for RN version 0.68.7
