### ISSUE TITLE
Installing a native iOS Flipper plugin is trickier starting with 0.68.0

### ISSUE THREAD

**Issue by Almouro** [facebook/react-native#34005]
### Description

Hi, following up on a Twitter discussion, I'm opening this here.
But this is not exactly a bug, it's more like a Dev experience issue: something that used to be easy and isn't anymore.
Apologies if I shouldn't have opened an issue here! 😥

## Before v0.68.0

Adding a native iOS Flipper plugin used to be quite easy, a simple matter of adding 2 lines in `AppDelegate.m`.

For example for https://github.com/bamlab/react-native-performance, we add 2 lines:
```objc
#ifdef FB_SONARKIT_ENABLED
...
// Add this line
#import <FlipperPerformancePlugin.h>

static void InitializeFlipper(UIApplication *application) {
  ...
  // Add this line
  [client addPlugin:[FlipperPerformancePlugin new]];

  [client start];
}
#endif
```

## After 0.68.0

After this commit https://github.com/facebook/react-native/commit/73a04d145251ad2aad8afb587d3fd0c746c9f00f#diff-68bc28be95c8d0faa843c16d1c24d21731a744801e1ab5c55ce7342a399c1f54R13 refactoring a lot of the Flipper boilerplate out of the AppDelegate, it becomes a bit trickier:

Basically it seems to me we now have to do something like this:
https://github.com/bamlab/react-native-performance/commit/dbfc5b0d3bcb07ef3420ec8466231844e9a83f5f#diff-8cbfe8e3302494c09b6d055cfcf7ebd417ba43ffc8ebf6e4a00197dbd09895cbR28, putting back the `InitializeFlipper` function, to ensure we respect the `FB_SONARKIT_ENABLED` flag.

This is also inconsistent with Android, where it is still quite easy to add a plugin: https://github.com/bamlab/react-native-performance/pull/55/commits/dbfc5b0d3bcb07ef3420ec8466231844e9a83f5f#diff-1d79c2256ea334f818216fdbc4a091ddf26a03a5b4ddec457ffcd534def4ce78R39

It's not so difficult, that is true, and I'm sure we can easily live with that, especially since this change seems to be paving the way for neat rearchitecture changes!
I'm just wondering if we can still keep the simplified version, I'd be happy to raise a PR on the template to make it similar to Android -> adding a ReactNativeFlipper.mm file containing only the Flipper setup.

### Version

0.68.0

### Output of `npx react-native info`

```
info Fetching system and libraries information...
System:
    OS: macOS 12.2
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Memory: 8.63 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.2 - /var/folders/x6/jf0q0xr52rzckkbbb3q12xm40000gp/T/fnm_multishells/13745_1655043412092/bin/node
    Yarn: 1.22.18 - ~/.yarn/bin/yarn
    npm: 8.1.2 - /var/folders/x6/jf0q0xr52rzckkbbb3q12xm40000gp/T/fnm_multishells/13745_1655043412092/bin/npm
    Watchman: 2022.02.07.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /Users/almouro/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 23, 25, 27, 28, 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.0, 30.0.2, 30.0.3, 31.0.0, 33.0.0
      System Images: android-30 | Android TV Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom_64, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 13.0/13A233 - /usr/bin/xcodebuild
  Languages:
    Java: 14.0.1 - /Library/Java/JavaVirtualMachines/openjdk-14.0.1.jdk/Contents/Home/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.68.2 => 0.68.2
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
  ```

### Steps to reproduce

- Initialize a new react-native project with `npx react-native init`
- Try to install a native iOS Flipper plugin such as https://github.com/bamlab/react-native-performance

### Snack, code example, screenshot, or link to a repository

Reproduction: 

To install the plugin you now need to do something like this: https://github.com/bamlab/react-native-performance/pull/55/commits/dbfc5b0d3bcb07ef3420ec8466231844e9a83f5f#diff-8cbfe8e3302494c09b6d055cfcf7ebd417ba43ffc8ebf6e4a00197dbd09895cbR28

**Comment by mateioprea** [comment]
I'm just curious, why can't we do something like this before [this line](https://github.com/facebook/react-native/commit/73a04d145251ad2aad8afb587d3fd0c746c9f00f#diff-68bc28be95c8d0faa843c16d1c24d21731a744801e1ab5c55ce7342a399c1f54R13):

```objective-c
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{

FlipperClient *client = [FlipperClient sharedClient];
[client addPlugin:[FlipperPerformancePlugin new]];


[RCTAppSetupUtils prepareApp: application];

...
}
```
Adding the plugins _before_ the prepareApp method runs should do the trick. That's what I was also suggesting on twitter. I think I've tried this before and it worked.
