### ISSUE TITLE
library not found for -lDoubleConversion

### ISSUE THREAD

**Issue by alexzobi** [facebook/react-native#34007]
### Description

I upgraded my project from version 0.64 to 0.68, cleaned my derived data folder, cleaned pods and project, reinstalled pods and no matter what I did, got the `ld: library not found for -lDoubleConversion` error when I tried to build for ios. Oddly enough, our project supports mac catalyst and it built fine for mac catalyst. Then I ran `npx react-native run-ios` and it buiild with no issue. after that, I killed the sim and re-ran the build through xcode and it built with no issues. so something that the `run-ios` command does resolved this issue for xcode. 

### Version

0.68.2in

### Output of `npx react-native info`

System:
    OS: macOS 12.4
    CPU: (10) x64 Apple M1 Pro
    Memory: 24.56 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.19.2 - ~/.nvm/versions/node/v14.19.2/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 6.14.17 - ~/.nvm/versions/node/v14.19.2/bin/npm
    Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 29, 30, 31, 32
      Build Tools: 29.0.0, 29.0.1, 29.0.2, 29.0.3, 30.0.0, 30.0.1, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0
      System Images: android-31 | Google APIs ARM 64 v8a, android-32 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: ^0.68.2 => 0.68.2
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

- on macbook pro with m1 chip.  create react native project targeting version 0.64.
- upgrade to 0.68
- install node modules and pods using `arch -x86_64 pod install`
- run build through xcode.
- if build fails with the above error, run `npx react-native run-ios`
- kill the build and build through xcode
- should now work properly

### Snack, code example, screenshot, or link to a repository

this is a private repo and cannot be shared for NDA reasons.

**Comment by cortinico** [comment]
Have you been able to solve this as you mentioned here https://github.com/facebook/react-native/issues/33132#issuecomment-1154334388 @alexzobi ?

**Comment by Mr-Rith** [comment]
I have the same issue

**Comment by cortinico** [comment]
Hey,
I'm closing this issue as @alexzobi you're not responsive.
Feel free to re-open it or create a new issue if the problem persists.
Thanks
