### ISSUE TITLE
Model reopens right after closing it and unable to close it back again

### ISSUE THREAD

**Issue by rajtejani** [facebook/react-native#34018]
### Description

Modal reopens right after closing it and doesn't allow me to close it. I'm importing **Modal** from `react-native`.

could it be possible due to the `react-native-gesture-handler`

### Version

0.67.3

### Output of `npx react-native info`

System:
    OS: macOS 11.2
    CPU: (6) x64 Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
    Memory: 58.17 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v14.17.0/bin/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
    Watchman: 2021.10.18.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 23, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3
      System Images: android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7784292
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.3 => 0.67.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

I updated React Native version from 0.63.0 to 0.67.3 recently. And then I saw this issue happening to me. I also created one more React Native app with a 0.67.3 version and it was also happening to that app as well.  I found one solution to wrap <Modal></Modal> Component inside <View>. That worked on 2nd app which I created for test purposes but not working in my current app.

### Snack, code example, screenshot, or link to a repository

https://user-images.githubusercontent.com/49932204/174065274-015a44f0-ce15-41b4-80d6-106029411b72.mp4

**Comment by rajtejani** [comment]
Solved this problem by wrapping Modal inside `<View></View>` and conditionally rendering <Modal> depending on the state variable which we pass on the `show` property of the map. 

Example:

```
<View>
  {
    show &&
      <Modal show={show}>
      ....
      </Modal>
    </View>
  }
```

**Comment by lucienbl** [comment]
Hello, I'm facing the same issue after upgrading from 0.65.1 to 0.69.1 and sadly @rajtejani 's fix doesn't work here. Even if I conditionally don't render the modal when it's not supposed to be `visible` it still comes back and somehow freezes.

**Comment by psnfrench** [comment]
I am facing this issue also on `0.68.2`

1. rajtejani's fix doens't work for me
2. Only an issue when setting `transparent={true}`

**Comment by rajtejani** [comment]
> I am facing this issue also on `0.68.2`
> 
> 1. rajtejani's fix doens't work for me
> 2. Only an issue when setting `transparent={true}`

@psnfrench  I also had a problem in that version too and the fix which worked me for was just wrapping my Modal code with `<View>...</View>.`

The above fix which I suggested is not a full-proof solution. It doesn't work in situations where you have one common modal and you are trying to open and close using refs.

Something like this.

**CommonModal.js**
```
class CommonModal extends React.PureComponent {
  state = {
    show: false,
    },
  };

  
  openModal = () => {
    this.setState({
      show: true,
  };

  closeModal = () => {
    this.setState({show: false});
  };

  render() {
    const {show} = this.state;

    return (
      <Modal visible={show}>
          ........
      </Modal
    );
  }
}
```

**App.js**
```
const App = () => {

  const closeModal = () => {
      UTILS.ui.modal.closeModal();
  }
  
  const openModal = () => {
       UTILS.ui.modal.openModal();
  }
  
  console.disableYellowBox = true;
  return (
    <View style={[commonStyles.flex(1)]}>
      <SafeAreaProvider>
        <CommonModal ref={ref => (UTILS.ui.modal = ref)} />
        <Button title="Open" onPress={openModal}>
        <Button title="Close" onPress={closeModal}>
      </SafeAreaProvider>
    </View>
  );
};
```

**Comment by SerhiyZheliznjak** [comment]
> 2. Only an issue when setting `transparent={true}`
same for me
