### ISSUE TITLE
[0.68] redefinition of funcitons in Props.h generated by codegen

### ISSUE THREAD

**Issue by psionic12** [facebook/react-native#34028]
### Description

I found that codegen genated a cpp file which has two functions with the same signature, which will lead to redifine problem in C++:

```
 In file included from /Users/x/source/qrn-lib/yReact/Android/QRNLib/build/generated/source/codegen/jni/react/renderer/components/my_appmodules/ShadowNodes.cpp:11:
  In file included from /Users/x/source/qrn-lib/yReact/Android/QRNLib/build/generated/source/codegen/jni/react/renderer/components/my_appmodules/ShadowNodes.h:14:
  /Users/x/source/qrn-lib/yReact/Android/QRNLib/build/generated/source/codegen/jni/react/renderer/components/my_appmodules/Props.h:619:20: error: redefinition of 'fromRawValue'
  static inline void fromRawValue(const PropsParserContext& context, const RawValue &value, ArrayPropsNativeComponentViewSizesMask &result) {
                     ^
  /Users/x/source/qrn-lib/yReact/Android/QRNLib/build/generated/source/codegen/jni/react/renderer/components/my_appmodules/Props.h:524:20: note: previous definition is here
  static inline void fromRawValue(const PropsParserContext& context, const RawValue &value, ModalHostViewSupportedOrientationsMask &result) {
                     ^
  /Users/x/source/qrn-lib/yReact/Android/QRNLib/build/generated/source/codegen/jni/react/renderer/components/my_appmodules/Props.h:634:27: error: redefinition of 'toString'
  static inline std::string toString(const ArrayPropsNativeComponentViewSizesMask &value) {
                            ^
  /Users/x/source/qrn-lib/yReact/Android/QRNLib/build/generated/source/codegen/jni/react/renderer/components/my_appmodules/Props.h:551:27: note: previous definition is here
  static inline std::string toString(const ModalHostViewSupportedOrientationsMask &value) {
                            ^
  2 errors generated.
```

In Cpp file, type `ModalHostViewSupportedOrientationsMask` and type `ArrayPropsNativeComponentViewSizesMask` are both `uint32_t`.

I followed this [tutorial](https://reactnative.dev/docs/new-architecture-app-intro)

### Version

0.68.1

### Output of `npx react-native info`

I download react native source manually, didn't use npm.

### Steps to reproduce

I followed this [tutorial](https://reactnative.dev/docs/new-architecture-app-intro)

### Snack, code example, screenshot, or link to a repository

```
apply plugin: 'com.android.library'
apply plugin: "com.facebook.react"

react {
    root = rootDir
    reactNativeDir = rootDir
    libraryName = "my_appmodules"
}


android {
    compileSdkVersion rootProject.properties.compileSdkVersion as int

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        minSdkVersion rootProject.properties.minSdkVersion as int
        targetSdkVersion rootProject.properties.targetSdkVersion as int
        versionCode 1
        versionName "1.0"
        externalNativeBuild {
            ndkBuild {
                arguments "APP_PLATFORM=android-21",
                    "APP_STL=c++_shared",
                    "NDK_TOOLCHAIN_VERSION=clang",
                    "GENERATED_SRC_DIR=$buildDir/generated/source",
                    "PROJECT_BUILD_DIR=$buildDir",
                    "REACT_ANDROID_DIR=$rootDir/ReactAndroid",
                    "REACT_ANDROID_BUILD_DIR=$rootDir/ReactAndroid/build"
                cFlags "-Wall", "-Werror", "-fexceptions", "-frtti", "-DWITH_INSPECTOR=1"
                cppFlags "-std=c++17"
                targets "my_appmodules"
            }
        }
    }

    externalNativeBuild {
        ndkBuild {
            path "$projectDir/src/main/jni/Android.mk"
        }
    }

    def reactAndroidProjectDir = project(':ReactAndroid').projectDir
    def packageReactNdkLibs = tasks.register("packageReactNdkLibs", Copy) {
        dependsOn(":ReactAndroid:packageReactNdkLibsForBuck")
        dependsOn("generateCodegenArtifactsFromSchema")
        from("$reactAndroidProjectDir/src/main/jni/prebuilt/lib")
        into("$buildDir/react-ndk/exported")
    }

    afterEvaluate {
        preBuild.dependsOn(packageReactNdkLibs)
        configureNdkBuildDebug.dependsOn(preBuild)
        configureNdkBuildRelease.dependsOn(preBuild)
    }

    packagingOptions {
        pickFirst '**/libhermes.so'
        pickFirst '**/libjsc.so'
    }
   ...
}

buildscript {
    repositories {
        maven {
            url "https://repo1.maven.org/maven2"
        }
    }
}

allprojects {
    repositories {
        maven {
            url "https://repo1.maven.org/maven2"
        }
    }
}

dependencies {
    api fileTree(include: ['*.jar'], dir: 'libs')
    implementation project(":ReactAndroid")
    ...

}

```

**Comment by psionic12** [comment]
My project is a little complicated, I'll try if I can provide a minimum reproducible program.

**Comment by MichDreby** [comment]
[Android]
Hi guys, my problem looks quite similar, I try to migrate huge project with a lot of custom Native components, I'm following guides:
https://reactnative.dev/docs/0.68/new-architecture-library-intro
https://reactnative.dev/docs/0.68/new-architecture-app-intro
and also this repo:
https://github.com/react-native-community/RNNewArchitectureApp/tree/run/from-0.67-to-0.68

But once I've added the following line to MyComponentsRegistry.cpp file 
`providerRegistry->add(concreteComponentDescriptorProvider<RCTFocusWrapperComponentDescriptor>());`

where RCTFocusWrapperComponentDescriptor is my custom Native component, I've got the following error:

* What went wrong:
Execution failed for task ':app:buildNdkBuildDebug[myapplication_appmodules]'.
> Build command failed.
  Error while executing process /Users/michdreby/Library/Android/sdk/ndk/21.4.7075529/ndk-build with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=/Users/michdreby/Desktop/h3-fe-consumer/android/app/src/main/jni/Android.mk APP_ABI=armeabi-v7a NDK_ALL_ABIS=armeabi-v7a NDK_DEBUG=1 NDK_OUT=/Users/michdreby/Desktop/h3-fe-consumer/android/app/build/intermediates/cxx/Debug/2z3g402g/obj NDK_LIBS_OUT=/Users/michdreby/Desktop/h3-fe-consumer/android/app/build/intermediates/cxx/Debug/2z3g402g/lib APP_CFLAGS+=-Wall APP_CFLAGS+=-Werror APP_CFLAGS+=-fexceptions APP_CFLAGS+=-frtti APP_CFLAGS+=-DWITH_INSPECTOR=1 APP_CPPFLAGS+=-std=c++17 APP_PLATFORM=android-21 APP_STL=c++_shared NDK_TOOLCHAIN_VERSION=clang GENERATED_SRC_DIR=/Users/michdreby/Desktop/h3-fe-consumer/android/app/build/generated/source PROJECT_BUILD_DIR=/Users/michdreby/Desktop/h3-fe-consumer/android/app/build REACT_ANDROID_DIR=/Users/michdreby/Desktop/h3-fe-consumer/android/../node_modules/react-native/ReactAndroid REACT_ANDROID_BUILD_DIR=/Users/michdreby/Desktop/h3-fe-consumer/android/../node_modules/react-native/ReactAndroid/build myapplication_appmodules}
  [armeabi-v7a] Compile++ thumb: myapplication_appmodules <= OnLoad.cpp
  [armeabi-v7a] Compile++ thumb: myapplication_appmodules <= MyApplicationTurboModuleManagerDelegate.cpp
  [armeabi-v7a] Compile++ thumb: myapplication_appmodules <= MyApplicationModuleProvider.cpp
  [armeabi-v7a] Compile++ thumb: myapplication_appmodules <= MyComponentsRegistry.cpp
  
  In file included from /Users/michdreby/Desktop/h3-fe-consumer/android/app/src/main/jni/MyComponentsRegistry.cpp:7:
  In file included from /Users/michdreby/Desktop/h3-fe-consumer/android/app/build/generated/source/codegen/jni/react/renderer/components/AppSpec/ComponentDescriptors.h:13:
  In file included from /Users/michdreby/Desktop/h3-fe-consumer/android/app/build/generated/source/codegen/jni/react/renderer/components/AppSpec/ShadowNodes.h:13:
  /Users/michdreby/Desktop/h3-fe-consumer/android/app/build/generated/source/codegen/jni/react/renderer/components/AppSpec/EventEmitters.h:91:7: error: redefinition of 'ActivityIndicatorViewEventEmitter'
  class ActivityIndicatorViewEventEmitter : public ViewEventEmitter {
        ^
  /Users/michdreby/Desktop/h3-fe-consumer/android/../node_modules/react-native/ReactAndroid/build/generated/source/codegen/jni/react/renderer/components/rncore/EventEmitters.h:17:7: note: previous definition is here
  class ActivityIndicatorViewEventEmitter : public ViewEventEmitter {
        ^
  In file included from /Users/michdreby/Desktop/h3-fe-consumer/android/app/src/main/jni/MyComponentsRegistry.cpp:7:
  In file included from /Users/michdreby/Desktop/h3-fe-consumer/android/app/build/generated/source/codegen/jni/react/renderer/components/AppSpec/ComponentDescriptors.h:13:
  In file included from /Users/michdreby/Desktop/h3-fe-consumer/android/app/build/generated/source/codegen/jni/react/renderer/components/AppSpec/ShadowNodes.h:13:
  /Users/michdreby/Desktop/h3-fe-consumer/android/app/build/generated/source/codegen/jni/react/renderer/components/AppSpec/EventEmitters.h:99:7: error: redefinition of 'DatePickerEventEmitter'
  class DatePickerEventEmitter : public ViewEventEmitter {
        ^
  /Users/michdreby/Desktop/h3-fe-consumer/android/../node_modules/react-native/ReactAndroid/build/generated/source/codegen/jni/react/renderer/components/rncore/EventEmitters.h:25:7: note: previous definition is here
  class DatePickerEventEmitter : public ViewEventEmitter {
        ^
  In file included from /Users/michdreby/Desktop/h3-fe-consumer/android/app/src/main/jni/MyComponentsRegistry.cpp:7:
  In file included from /Users/michdreby/Desktop/h3-fe-consumer/android/app/build/generated/source/codegen/jni/react/renderer/components/AppSpec/ComponentDescriptors.h:13:
  In file included from /Users/michdreby/Desktop/h3-fe-consumer/android/app/build/generated/source/codegen/jni/react/renderer/components/AppSpec/ShadowNodes.h:13:
  /Users/michdreby/Desktop/h3-fe-consumer/android/app/build/generated/source/codegen/jni/react/renderer/components/AppSpec/EventEmitters.h:109:7: error: redefinition of 'AndroidDrawerLayoutEventEmitter'
  class AndroidDrawerLayoutEventEmitter : public ViewEventEmitter {
        ^
  /Users/michdreby/Desktop/h3-fe-consumer/android/../node_modules/react-native/ReactAndroid/build/generated/source/codegen/jni/react/renderer/components/rncore/EventEmitters.h:35:7: note: previous definition is here
  class AndroidDrawerLayoutEventEmitter : public ViewEventEmitter {
        ^
  In file included from /Users/michdreby/Desktop/h3-fe-consumer/android/app/src/main/jni/MyComponentsRegistry.cpp:7:
  In file included from /Users/michdreby/Desktop/h3-fe-consumer/android/app/build/generated/source/codegen/jni/react/renderer/components/AppSpec/ComponentDescriptors.h:13:
  In file included from /Users/michdreby/Desktop/h3-fe-consumer/android/app/build/generated/source/codegen/jni/react/renderer/components/AppSpec/ShadowNodes.h:13:
  /Users/michdreby/Desktop/h3-fe-consumer/android/app/build/generated/source/codegen/jni/react/renderer/components/AppSpec/EventEmitters.h:137:7: error: redefinition of 'RCTMaskedViewEventEmitter'
  class RCTMaskedViewEventEmitter : public ViewEventEmitter {
        ^
  /Users/michdreby/Desktop/h3-fe-consumer/android/../node_modules/react-native/ReactAndroid/build/generated/source/codegen/jni/react/renderer/components/rncore/EventEmitters.h:63:7: note: previous definition is here
  class RCTMaskedViewEventEmitter : public ViewEventEmitter {
        ^
  In file included from /Users/michdreby/Desktop/h3-fe-consumer/android/app/src/main/jni/MyComponentsRegistry.cpp:7:
  In file included from /Users/michdreby/Desktop/h3-fe-consumer/android/app/build/generated/source/codegen/jni/react/renderer/components/AppSpec/ComponentDescriptors.h:13:
  In file included from /Users/michdreby/Desktop/h3-fe-consumer/android/app/build/generated/source/codegen/jni/react/renderer/components/AppSpec/ShadowNodes.h:13:
  /Users/michdreby/Desktop/h3-fe-consumer/android/app/build/generated/source/codegen/jni/react/renderer/components/AppSpec/EventEmitters.h:145:7: error: redefinition of 'AndroidProgressBarEventEmitter'
  class AndroidProgressBarEventEmitter : public ViewEventEmitter {
        ^
  /Users/michdreby/Desktop/h3-fe-consumer/android/../node_modules/react-native/ReactAndroid/build/generated/source/codegen/jni/react/renderer/components/rncore/EventEmitters.h:71:7: note: previous definition is here
  class AndroidProgressBarEventEmitter : public ViewEventEmitter {
        ^
  In file included from /Users/michdreby/Desktop/h3-fe-consumer/android/app/src/main/jni/MyComponentsRegistry.cpp:7:
  In file included from /Users/michdreby/Desktop/h3-fe-consumer/android/app/build/generated/source/codegen/jni/react/renderer/components/AppSpec/ComponentDescriptors.h:13:
  In file included from /Users/michdreby/Desktop/h3-fe-consumer/android/app/build/generated/source/codegen/jni/react/renderer/components/AppSpec/ShadowNodes.h:13:
  /Users/michdreby/Desktop/h3-fe-consumer/android/app/build/generated/source/codegen/jni/react/renderer/components/AppSpec/EventEmitters.h:153:7: error: redefinition of 'RCTProgressViewEventEmitter'
  class RCTProgressViewEventEmitter : public ViewEventEmitter {
        ^
  /Users/michdreby/Desktop/h3-fe-consumer/android/../node_modules/react-native/ReactAndroid/build/generated/source/codegen/jni/react/renderer/components/rncore/EventEmitters.h:79:7: note: previous definition is here
  class RCTProgressViewEventEmitter : public ViewEventEmitter {
        ^
  In file included from /Users/michdreby/Desktop/h3-fe-consumer/android/app/src/main/jni/MyComponentsRegistry.cpp:7:
  In file included from /Users/michdreby/Desktop/h3-fe-consumer/android/app/build/generated/source/codegen/jni/react/renderer/components/AppSpec/ComponentDescriptors.h:13:
  In file included from /Users/michdreby/Desktop/h3-fe-consumer/android/app/build/generated/source/codegen/jni/react/renderer/components/AppSpec/ShadowNodes.h:13:
  /Users/michdreby/Desktop/h3-fe-consumer/android/app/build/generated/source/codegen/jni/react/renderer/components/AppSpec/EventEmitters.h:161:7: error: redefinition of 'AndroidSwipeRefreshLayoutEventEmitter'
  class AndroidSwipeRefreshLayoutEventEmitter : public ViewEventEmitter {
        ^
  /Users/michdreby/Desktop/h3-fe-consumer/android/../node_modules/react-native/ReactAndroid/build/generated/source/codegen/jni/react/renderer/components/rncore/EventEmitters.h:87:7: note: previous definition is here
  class AndroidSwipeRefreshLayoutEventEmitter : public ViewEventEmitter {
        ^
  In file included from /Users/michdreby/Desktop/h3-fe-consumer/android/app/src/main/jni/MyComponentsRegistry.cpp:7:
  In file included from /Users/michdreby/Desktop/h3-fe-consumer/android/app/build/generated/source/codegen/jni/react/renderer/components/AppSpec/ComponentDescriptors.h:13:
  In file included from /Users/michdreby/Desktop/h3-fe-consumer/android/app/build/generated/source/codegen/jni/react/renderer/components/AppSpec/ShadowNodes.h:13:
  /Users/michdreby/Desktop/h3-fe-consumer/android/app/build/generated/source/codegen/jni/react/renderer/components/AppSpec/EventEmitters.h:171:7: error: redefinition of 'PullToRefreshViewEventEmitter'
  class PullToRefreshViewEventEmitter : public ViewEventEmitter {
        ^
  /Users/michdreby/Desktop/h3-fe-consumer/android/../node_modules/react-native/ReactAndroid/build/generated/source/codegen/jni/react/renderer/components/rncore/EventEmitters.h:97:7: note: previous definition is here
  class PullToRefreshViewEventEmitter : public ViewEventEmitter {
        ^
  In file included from /Users/michdreby/Desktop/h3-fe-consumer/android/app/src/main/jni/MyComponentsRegistry.cpp:7:
  In file included from /Users/michdreby/Desktop/h3-fe-consumer/android/app/build/generated/source/codegen/jni/react/renderer/components/AppSpec/ComponentDescriptors.h:13:
  In file included from /Users/michdreby/Desktop/h3-fe-consumer/android/app/build/generated/source/codegen/jni/react/renderer/components/AppSpec/ShadowNodes.h:13:
  /Users/michdreby/Desktop/h3-fe-consumer/android/app/build/generated/source/codegen/jni/react/renderer/components/AppSpec/EventEmitters.h:181:7: error: redefinition of 'SafeAreaViewEventEmitter'
  class SafeAreaViewEventEmitter : public ViewEventEmitter {
        ^
  /Users/michdreby/Desktop/h3-fe-consumer/android/../node_modules/react-native/ReactAndroid/build/generated/source/codegen/jni/react/renderer/components/rncore/EventEmitters.h:107:7: note: previous definition is here
  class SafeAreaViewEventEmitter : public ViewEventEmitter {
        ^
  In file included from /Users/michdreby/Desktop/h3-fe-consumer/android/app/src/main/jni/MyComponentsRegistry.cpp:7:
  In file included from /Users/michdreby/Desktop/h3-fe-consumer/android/app/build/generated/source/codegen/jni/react/renderer/components/AppSpec/ComponentDescriptors.h:13:
  In file included from /Users/michdreby/Desktop/h3-fe-consumer/android/app/build/generated/source/codegen/jni/react/renderer/components/AppSpec/ShadowNodes.h:13:
  /Users/michdreby/Desktop/h3-fe-consumer/android/app/build/generated/source/codegen/jni/react/renderer/components/AppSpec/EventEmitters.h:189:7: error: redefinition of 'AndroidHorizontalScrollContentViewEventEmitter'
  class AndroidHorizontalScrollContentViewEventEmitter : public ViewEventEmitter {
        ^
  /Users/michdreby/Desktop/h3-fe-consumer/android/../node_modules/react-native/ReactAndroid/build/generated/source/codegen/jni/react/renderer/components/rncore/EventEmitters.h:115:7: note: previous definition is here
  class AndroidHorizontalScrollContentViewEventEmitter : public ViewEventEmitter {
        ^
  In file included from /Users/michdreby/Desktop/h3-fe-consumer/android/app/src/main/jni/MyComponentsRegistry.cpp:7:
  In file included from /Users/michdreby/Desktop/h3-fe-consumer/android/app/build/generated/source/codegen/jni/react/renderer/components/AppSpec/ComponentDescriptors.h:13:
  In file included from /Users/michdreby/Desktop/h3-fe-consumer/android/app/build/generated/source/codegen/jni/react/renderer/components/AppSpec/ShadowNodes.h:13:
  /Users/michdreby/Desktop/h3-fe-consumer/android/app/build/generated/source/codegen/jni/react/renderer/components/AppSpec/EventEmitters.h:197:7: error: redefinition of 'RCTSegmentedControlEventEmitter'
  class RCTSegmentedControlEventEmitter : public ViewEventEmitter {
        ^
  /Users/michdreby/Desktop/h3-fe-consumer/android/../node_modules/react-native/ReactAndroid/build/generated/source/codegen/jni/react/renderer/components/rncore/EventEmitters.h:123:7: note: previous definition is here
  class RCTSegmentedControlEventEmitter : public ViewEventEmitter {
        ^
  In file included from /Users/michdreby/Desktop/h3-fe-consumer/android/app/src/main/jni/MyComponentsRegistry.cpp:7:
  In file included from /Users/michdreby/Desktop/h3-fe-consumer/android/app/build/generated/source/codegen/jni/react/renderer/components/AppSpec/ComponentDescriptors.h:13:
  In file included from /Users/michdreby/Desktop/h3-fe-consumer/android/app/build/generated/source/codegen/jni/react/renderer/components/AppSpec/ShadowNodes.h:13:
  /Users/michdreby/Desktop/h3-fe-consumer/android/app/build/generated/source/codegen/jni/react/renderer/components/AppSpec/EventEmitters.h:208:7: error: redefinition of 'SliderEventEmitter'
  class SliderEventEmitter : public ViewEventEmitter {
        ^
  /Users/michdreby/Desktop/h3-fe-consumer/android/../node_modules/react-native/ReactAndroid/build/generated/source/codegen/jni/react/renderer/components/rncore/EventEmitters.h:134:7: note: previous definition is here
  class SliderEventEmitter : public ViewEventEmitter {
        ^
  In file included from /Users/michdreby/Desktop/h3-fe-consumer/android/app/src/main/jni/MyComponentsRegistry.cpp:7:
  In file included from /Users/michdreby/Desktop/h3-fe-consumer/android/app/build/generated/source/codegen/jni/react/renderer/components/AppSpec/ComponentDescriptors.h:13:
  In file included from /Users/michdreby/Desktop/h3-fe-consumer/android/app/build/generated/source/codegen/jni/react/renderer/components/AppSpec/ShadowNodes.h:13:
  /Users/michdreby/Desktop/h3-fe-consumer/android/app/build/generated/source/codegen/jni/react/renderer/components/AppSpec/EventEmitters.h:233:7: error: redefinition of 'AndroidSwitchEventEmitter'
  class AndroidSwitchEventEmitter : public ViewEventEmitter {
        ^
  /Users/michdreby/Desktop/h3-fe-consumer/android/../node_modules/react-native/ReactAndroid/build/generated/source/codegen/jni/react/renderer/components/rncore/EventEmitters.h:159:7: note: previous definition is here
  class AndroidSwitchEventEmitter : public ViewEventEmitter {
        ^
  In file included from /Users/michdreby/Desktop/h3-fe-consumer/android/app/src/main/jni/MyComponentsRegistry.cpp:7:
  In file included from /Users/michdreby/Desktop/h3-fe-consumer/android/app/build/generated/source/codegen/jni/react/renderer/components/AppSpec/ComponentDescriptors.h:13:
  In file included from /Users/michdreby/Desktop/h3-fe-consumer/android/app/build/generated/source/codegen/jni/react/renderer/components/AppSpec/ShadowNodes.h:13:
  /Users/michdreby/Desktop/h3-fe-consumer/android/app/build/generated/source/codegen/jni/react/renderer/components/AppSpec/EventEmitters.h:243:7: error: redefinition of 'SwitchEventEmitter'
  class SwitchEventEmitter : public ViewEventEmitter {
        ^
  /Users/michdreby/Desktop/h3-fe-consumer/android/../node_modules/react-native/ReactAndroid/build/generated/source/codegen/jni/react/renderer/components/rncore/EventEmitters.h:169:7: note: previous definition is here
  class SwitchEventEmitter : public ViewEventEmitter {
        ^
  In file included from /Users/michdreby/Desktop/h3-fe-consumer/android/app/src/main/jni/MyComponentsRegistry.cpp:7:
  In file included from /Users/michdreby/Desktop/h3-fe-consumer/android/app/build/generated/source/codegen/jni/react/renderer/components/AppSpec/ComponentDescriptors.h:13:
  In file included from /Users/michdreby/Desktop/h3-fe-consumer/android/app/build/generated/source/codegen/jni/react/renderer/components/AppSpec/ShadowNodes.h:13:
  /Users/michdreby/Desktop/h3-fe-consumer/android/app/build/generated/source/codegen/jni/react/renderer/components/AppSpec/EventEmitters.h:253:7: error: redefinition of 'InputAccessoryEventEmitter'
  class InputAccessoryEventEmitter : public ViewEventEmitter {
        ^
  /Users/michdreby/Desktop/h3-fe-consumer/android/../node_modules/react-native/ReactAndroid/build/generated/source/codegen/jni/react/renderer/components/rncore/EventEmitters.h:179:7: note: previous definition is here
  class InputAccessoryEventEmitter : public ViewEventEmitter {
        ^
  In file included from /Users/michdreby/Desktop/h3-fe-consumer/android/app/src/main/jni/MyComponentsRegistry.cpp:7:
  In file included from /Users/michdreby/Desktop/h3-fe-consumer/android/app/build/generated/source/codegen/jni/react/renderer/components/AppSpec/ComponentDescriptors.h:13:
  In file included from /Users/michdreby/Desktop/h3-fe-consumer/android/app/build/generated/source/codegen/jni/react/renderer/components/AppSpec/ShadowNodes.h:13:
  /Users/michdreby/Desktop/h3-fe-consumer/android/app/build/generated/source/codegen/jni/react/renderer/components/AppSpec/EventEmitters.h:261:7: error: redefinition of 'UnimplementedNativeViewEventEmitter'
  class UnimplementedNativeViewEventEmitter : public ViewEventEmitter {
        ^
  /Users/michdreby/Desktop/h3-fe-consumer/android/../node_modules/react-native/ReactAndroid/build/generated/source/codegen/jni/react/renderer/components/rncore/EventEmitters.h:187:7: note: previous definition is here
  class UnimplementedNativeViewEventEmitter : public ViewEventEmitter {
        ^
  In file included from /Users/michdreby/Desktop/h3-fe-consumer/android/app/src/main/jni/MyComponentsRegistry.cpp:7:
  In file included from /Users/michdreby/Desktop/h3-fe-consumer/android/app/build/generated/source/codegen/jni/react/renderer/components/AppSpec/ComponentDescriptors.h:13:
  In file included from /Users/michdreby/Desktop/h3-fe-consumer/android/app/build/generated/source/codegen/jni/react/renderer/components/AppSpec/ShadowNodes.h:13:
  /Users/michdreby/Desktop/h3-fe-consumer/android/app/build/generated/source/codegen/jni/react/renderer/components/AppSpec/EventEmitters.h:269:7: error: redefinition of 'ModalHostViewEventEmitter'
  class ModalHostViewEventEmitter : public ViewEventEmitter {
        ^
  /Users/michdreby/Desktop/h3-fe-consumer/android/../node_modules/react-native/ReactAndroid/build/generated/source/codegen/jni/react/renderer/components/rncore/EventEmitters.h:195:7: note: previous definition is here
  class ModalHostViewEventEmitter : public ViewEventEmitter {
        ^
  In file included from /Users/michdreby/Desktop/h3-fe-consumer/android/app/src/main/jni/MyComponentsRegistry.cpp:7:
  In file included from /Users/michdreby/Desktop/h3-fe-consumer/android/app/build/generated/source/codegen/jni/react/renderer/components/AppSpec/ComponentDescriptors.h:13:
  In file included from /Users/michdreby/Desktop/h3-fe-consumer/android/app/build/generated/source/codegen/jni/react/renderer/components/AppSpec/ShadowNodes.h:14:
  /Users/michdreby/Desktop/h3-fe-consumer/android/app/build/generated/source/codegen/jni/react/renderer/components/AppSpec/Props.h:226:12: error: redefinition of 'ActivityIndicatorViewSize'
  enum class ActivityIndicatorViewSize { Small, Large };
             ^
  /Users/michdreby/Desktop/h3-fe-consumer/android/../node_modules/react-native/ReactAndroid/build/generated/source/codegen/jni/react/renderer/components/rncore/Props.h:22:12: note: previous definition is here
  enum class ActivityIndicatorViewSize { Small, Large };
             ^
  In file included from /Users/michdreby/Desktop/h3-fe-consumer/android/app/src/main/jni/MyComponentsRegistry.cpp:7:
  In file included from /Users/michdreby/Desktop/h3-fe-consumer/android/app/build/generated/source/codegen/jni/react/renderer/components/AppSpec/ComponentDescriptors.h:13:
  In file included from /Users/michdreby/Desktop/h3-fe-consumer/android/app/build/generated/source/codegen/jni/react/renderer/components/AppSpec/ShadowNodes.h:14:
  /Users/michdreby/Desktop/h3-fe-consumer/android/app/build/generated/source/codegen/jni/react/renderer/components/AppSpec/Props.h:228:20: error: redefinition of 'fromRawValue'
  static inline void fromRawValue(const PropsParserContext& context, const RawValue &value, ActivityIndicatorViewSize &result) {
                     ^
  /Users/michdreby/Desktop/h3-fe-consumer/android/../node_modules/react-native/ReactAndroid/build/generated/source/codegen/jni/react/renderer/components/rncore/Props.h:24:20: note: previous definition is here
  static inline void fromRawValue(const PropsParserContext& context, const RawValue &value, ActivityIndicatorViewSize &result) {
                     ^
  fatal error: too many errors emitted, stopping now [-ferror-limit=]
  20 errors generated.
  make: *** [/Users/michdreby/Library/Android/sdk/ndk/21.4.7075529/build/core/build-binary.mk:478: /Users/michdreby/Desktop/h3-fe-consumer/android/app/build/intermediates/cxx/Debug/2z3g402g/obj/local/armeabi-v7a/objs-debug/myapplication_appmodules//Users/michdreby/Desktop/h3-fe-consumer/android/app/src/main/jni/MyComponentsRegistry.o] Error 1
  
Tried run this repo https://github.com/react-native-community/RNNewArchitectureApp/tree/run/from-0.67-to-0.68 - everything is OK,

@cortinico, @psionic12  do you have any ideas what might lead to redefinition issue?

**Comment by cortinico** [comment]
> Hi guys, my problem looks quite similar, I try to migrate huge project with a lot of custom Native components, I'm following guides:

Your problem is related but the error message is different.
Please open a separate issue, provide a reproducer and once you've done it, tag me there.
What is happening for your is that your codegen invocation is picking up files from React Native Core so you re-generate files for the core-library. And your build fails as files are imported twice.

Let's keep this issue focused on @psionic12 issue, which is currently needs a reproducer.
