### ISSUE TITLE
Flicker on image component when using borderRadius

### ISSUE THREAD

**Issue by aldoetobex** [facebook/react-native#34027]
### Description

Hello, i just found bug issue on image

When i tried put borderRadius : 5, the image appear like this (see image below)
![image](https://user-images.githubusercontent.com/896268/174521601-d5c96044-dd20-4700-b699-51f65069fb0a.png)

But when i tried remove that, the image show as well (see image below)
![image](https://user-images.githubusercontent.com/896268/174521857-4e6bac13-569a-48c8-b1bf-d767dc26ec4e.png)

I don't know wheter android or react native package issue or not, but i hope react native dev can further process this issue.

Thanks

### Version

0.68.2

### Output of `npx react-native info`

System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1
    Memory: 426.61 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.1 - /opt/homebrew/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 6.14.16 - /opt/homebrew/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 13.4/13F17a - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.12 - /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.2 => 0.68.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. import image from react native
2. Use image component 
3. Add borderRadius > 0 on style props

### Snack, code example, screenshot, or link to a repository

```
<Image
  style={{
    width: 32,
    height: 32,
    borderRadius: 32,
    resizeMode: 'contain',
  }}
  source={{
    uri: v.image,
  }}
  alt={v.value}
/>
```

**Comment by cortinico** [comment]
> I don't know wheter android or react native package issue or not, but i hope react native dev can further process this issue.

What is the bug specifically? Is it the horizontal blue line on the right?

**Comment by aldoetobex** [comment]
> > I don't know wheter android or react native package issue or not, but i hope react native dev can further process this issue.
> 
> What is the bug specifically? Is it the horizontal blue line on the right?

Yes, it is sir.
