### ISSUE TITLE
Flatlist doesn't invoke renderItems when data passed is array of nulls

### ISSUE THREAD

**Issue by imanshul** [facebook/react-native#34034]
### Description

When `numColumns` field is added to display Flatlist as gridView, the flatlist's `renderItem` method doesn't invoke when we pass array of nulls as data.

### Version

0.67.2

### Output of `npx react-native info`

System:
    OS: macOS 12.3.1
    CPU: (8) arm64 Apple M1
    Memory: 122.77 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.0 - /usr/local/bin/npm
    Watchman: 2021.10.18.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 17, 23, 28, 30, 31
      Build Tools: 29.0.2, 30.0.0, 30.0.1, 30.0.2, 31.0.0
      System Images: android-29 | Google Play ARM 64 v8a, android-30 | Google APIs ARM 64 v8a, android-31 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_311 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.2 => 0.67.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Use a flatlist and pass data to flatlist as `[null, null]` you'll see that it render the list but when you change the same flatlist to gridView by passing `numColumns` the same code stops working, the renderItem method is never invoked.

### Snack, code example, screenshot, or link to a repository

Flatlist code with array of nulls that invoke renderItem method and displays item.
```
 <FlatList
                            data={[null, null]}
                            keyExtractor={(item, index) => index.toString()}
                            renderItem={({item, index}) => this.renderItem(item, index)}                
/>
```
Adding the numColumns field doesn't call renderItem method. Below code doesn't work

```
<FlatList
                            data={[null, null]}
                            keyExtractor={(item, index) => index.toString()}
                            renderItem={({item, index}) => this.renderItem(item, index)}            
                            numColumns={2}    
/>
```

**Comment by AntoineDoubovetzky** [comment]
I opened a PR to fix this issue
