### ISSUE TITLE
app crashes when opening the app from deep link

### ISSUE THREAD

**Issue by soheilaGhayour** [facebook/react-native#34033]
### Description

Running application on M1 macbook air.
I've followed the structured mention in [deep linking section](https://reactnavigation.org/docs/5.x/deep-linking#ios). Updated delegate.m and run npx uri-scheme add myapplication --ios 
Evrything seemed to be fined utill I run the app and test the deep link with xcrun simctl openurl booted myapplication://home
This launches the app successfully, takes few moments in splash screen, then suddenly crashes without showing any logs. and closes the application.
This is all I get from xcode logs:
Thread 4: "-[APMMeasurement handleNonFirstOpenEventURL:eventTimestampInSeconds:]: unrecognized selector sent to instance 0x600001b64000"

### Version

0.63.3

### Output of `npx react-native info`

System:
    OS: macOS 12.2.1
    CPU: (8) arm64 Apple M1
    Memory: 83.42 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.4.0 - /opt/homebrew/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.3.1 - /opt/homebrew/bin/npm
    Watchman: 2022.02.07.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /Users/soheila/.rvm/rubies/ruby-3.0.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 28, 29, 30, 32
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.3, 32.0.0, 32.1.0
      System Images: android-29 | Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-30 | Google Play ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8139111
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
    Python: 2.7.18 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: ^4.10.1 => 4.13.0 
    react: 17.0.1 => 17.0.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

[add native changes](https://reactnavigation.org/docs/5.x/deep-linking#ios)

### Snack, code example, screenshot, or link to a repository

add this in delecate.m
```
// Add the header at the top of the file:
#import <React/RCTLinkingManager.h>

// Add this above `@end`:
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url
  sourceApplication:(NSString *)sourceApplication annotation:(id)annotation
{
  return [RCTLinkingManager application:application openURL:url
                      sourceApplication:sourceApplication annotation:annotation];
}
```

then run this command:
npx uri-scheme add mychat --ios
Build application by xcode
then run the following command:
xcrun simctl openurl booted myapplication://home

**Comment by cortinico** [comment]
> 0.63.3

Can you test on RN 0.68 and report if the issue is still happening?

**Comment by soheilaGhayour** [comment]
After hours of debugging I realized It was firebase related. Upgraded to the firebase latest version and resolved.
