### ISSUE TITLE
Debugging is broken on latest master

### ISSUE THREAD

**Issue by admmasters** [facebook/react-native#3403]
Hi,

As a result of commit: baf5b7b4d55e88bad232f57adb899b03028fb3fe - De-batch native->js calls and react updates - debugging no longer works as expected when using the iOS sim with Chrome debugging enabled. Our system is getting the red box socket closed error.

Using Xcode 7.01 plus El Cap with latest node.

M

**Comment by marcshilling** [comment]
Same here. Works without Chrome attached. As soon as I Command+D > Enable Chrome Debugging I get the "socket closed" red box error.

**Comment by martinbigio** [comment]
@admmasters, @marcshilling have you guys bisected the problem to @tadeuzagallo's rev?

**Comment by tadeuzagallo** [comment]
@martinbigio It was indeed my diff, I already shipped the fix, should be on github soon.

**Comment by javache** [comment]
Fixed by https://github.com/facebook/react-native/commit/529687f9234ae9730a2660a1fee10ce45319c3fb

**Comment by admmasters** [comment]
Was just about to close this as well, thanks!
