### ISSUE TITLE
[Build failed solution]Log Suggestion: use tools:overrideLibrary="com.facebook.react" to force usage

### ISSUE THREAD

**Issue by yipengmu** [facebook/react-native#3404]
when i wrap a framework-sdk by React as core lib and run application with the framework-sdk
Error:Execution failed for task ':app:processDebugAndroidTestManifest'.
> java.lang.RuntimeException: Manifest merger failed : uses-sdk:minSdkVersion 14 cannot be smaller than version 16 declared in library [com.facebook.react:react-native:0.12.0] /Users/luoyuan/dev/workspace/git_home/MyReactNative/android/ReactAndroid/android/app/build/intermediates/exploded-aar/com.facebook.react/react-native/0.12.0/AndroidManifest.xml
Suggestion: use tools:overrideLibrary="com.facebook.react" to force usage

solution: 
in application project,add < uses-sdk tools:overrideLibrary="com.facebook.react" /> like this,

    <manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="com.ali.reactandroid.rntest">
    <uses-sdk tools:overrideLibrary="com.facebook.react"/>
    <application
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:theme="@style/AppTheme" >
        <activity
            android:name=".MainActivity"
            android:label="@string/app_name"
            android:theme="@style/AppTheme.NoActionBar" >
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>

</manifest>

**Comment by monicaSmith** [comment]
solved my problem.that's awesome
