### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by SagarikaRyada** [facebook/react-native#34047]
### New Version

0.68.2

### Old Version

0.65.2

### Build Target(s)

iod

### Output of `react-native info`

duplicate symbol '_bridgeRef' in:
    /Users/ryadar/Library/Developer/Xcode/DerivedData/JAD-hdcfymxnabjlyzdffmqhhhkocrkg/Build/Products/Debug-iphonesimulator/react-native-blob-util/libreact-native-blob-util.a(ReactNativeBlobUtil.o)
    /Users/ryadar/Library/Developer/Xcode/DerivedData/JAD-hdcfymxnabjlyzdffmqhhhkocrkg/Build/Products/Debug-iphonesimulator/rn-fetch-blob/librn-fetch-blob.a(RNFetchBlob.o)
duplicate symbol '_fsQueue' in:
    /Users/ryadar/Library/Developer/Xcode/DerivedData/JAD-hdcfymxnabjlyzdffmqhhhkocrkg/Build/Products/Debug-iphonesimulator/react-native-blob-util/libreact-native-blob-util.a(ReactNativeBlobUtil.o)
    /Users/ryadar/Library/Developer/Xcode/DerivedData/JAD-hdcfymxnabjlyzdffmqhhhkocrkg/Build/Products/Debug-iphonesimulator/rn-fetch-blob/librn-fetch-blob.a(RNFetchBlob.o)
duplicate symbol '_commonTaskQueue' in:
    /Users/ryadar/Library/Developer/Xcode/DerivedData/JAD-hdcfymxnabjlyzdffmqhhhkocrkg/Build/Products/Debug-iphonesimulator/react-native-blob-util/libreact-native-blob-util.a(ReactNativeBlobUtil.o)
    /Users/ryadar/Library/Developer/Xcode/DerivedData/JAD-hdcfymxnabjlyzdffmqhhhkocrkg/Build/Products/Debug-iphonesimulator/rn-fetch-blob/librn-fetch-blob.a(RNFetchBlob.o)
duplicate symbol '_fileStreams' in:
    /Users/ryadar/Library/Developer/Xcode/DerivedData/JAD-hdcfymxnabjlyzdffmqhhhkocrkg/Build/Products/Debug-iphonesimulator/react-native-blob-util/libreact-native-blob-util.a(ReactNativeBlobUtilFS.o)
    /Users/ryadar/Library/Developer/Xcode/DerivedData/JAD-hdcfymxnabjlyzdffmqhhhkocrkg/Build/Products/Debug-iphonesimulator/rn-fetch-blob/librn-fetch-blob.a(RNFetchBlobFS.o)
duplicate symbol '_expirationTable' in:
    /Users/ryadar/Library/Developer/Xcode/DerivedData/JAD-hdcfymxnabjlyzdffmqhhhkocrkg/Build/Products/Debug-iphonesimulator/react-native-blob-util/libreact-native-blob-util.a(ReactNativeBlobUtilNetwork.o)
    /Users/ryadar/Library/Developer/Xcode/DerivedData/JAD-hdcfymxnabjlyzdffmqhhhkocrkg/Build/Products/Debug-iphonesimulator/rn-fetch-blob/librn-fetch-blob.a(RNFetchBlobNetwork.o)
ld: 5 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

### Issue and Reproduction Steps

Build is getting failed .

**Comment by cortinico** [comment]
> Issue and Reproduction Steps

We can't look into this without a reproducer
