### ISSUE TITLE
Unbalanced calls start/end for tag 1

### ISSUE THREAD

**Issue by chubo274** [facebook/react-native#34042]
### Description

Unbalanced calls start/end for tag 1 [RCTLog.js:47]

i see this log when i build success my template.
pls tell me what does this log mean?

### Version

0.67.4

### Output of `npx react-native info`

System:
    OS: macOS 12.3.1
    CPU: (8) x64 Apple M1
    Memory: 21.20 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.19.1 - ~/.nvm/versions/node/v14.19.1/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 6.14.16 - ~/.nvm/versions/node/v14.19.1/bin/npm
    Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8309675
    Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.14.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.4 => 0.67.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by cortinico** [comment]
> pls tell me what does this log mean?

Please provide a reproducer. Also which template are you using?
