### ISSUE TITLE
add support for `react-native run-ios --simulator booted`

### ISSUE THREAD

**Issue by pvinis** [facebook/react-native#34057]
### Description

`react-native run-ios --simulator booted` should use the simulator that is already booted.
`simctl` has this alias `booted` that will replace with whatever udid the booted simulator has.

### Version

any

### Output of `npx react-native info`

N/A

### Steps to reproduce

`react-native run-ios --simulator booted` gives `error No simulator available with name "booted".`

### Snack, code example, screenshot, or link to a repository

N/A

**Comment by cortinico** [comment]
Closing as I saw you have it tracked under https://github.com/react-native-community/cli/issues/1624 👍
