### ISSUE TITLE
getModule of AppRegistry is not an object

### ISSUE THREAD

**Issue by trilam1409** [facebook/react-native#34056]
### Description

I upgraded the version from 0.67.2 to 0.69.0

I got the issues when runtime:

E0623 17:04:48.910380 1879928832 bindingUtils.cpp:27] getModule of AppRegistry is not an object
E0623 17:04:48.910419 1879928832 bindingUtils.cpp:29] react_native_assert failure: moduleAsValue.isObject()
Assertion failed: (moduleAsValue.isObject()), function getModule, file bindingUtils.cpp, line 29.
dyld4 config: DYLD_LIBRARY_PATH=/usr/lib/system/introspection DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib:/Developer/Library/PrivateFrameworks/GPUTools.framework/libglInterpose.dylib

### Version

0.69.0

### Output of `npx react-native info`

System:
    OS: macOS 12.4
    CPU: (8) x64 Apple M1 Pro
    Memory: 38.02 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.12.1 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 13.3/13E113 - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.5 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.0 => 0.69.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

The build is successful but the runtime has errors

### Snack, code example, screenshot, or link to a repository

![Uploading Screen Shot 2022-06-23 at 17.05.23.png…]()

**Comment by cortinico** [comment]
You picked new architecture but I see no reference of it in your issue description. Was that correct?

**Comment by waqas19921** [comment]
I was getting this error when new architecture with hermes is enabled and some value is undefined and I am trying to access its props.
