### ISSUE TITLE
keep v 068.2 and 0.69 impossible ?

### ISSUE THREAD

**Issue by Productivix** [facebook/react-native#34051]
### New Version

0,69

### Old Version

0,68.2

### Build Target(s)

Android

### Output of `react-native info`

>npx react-native info
Need to install the following packages:
  react-native@0.69.0
Ok to proceed? (y) y
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: undefined@undefined
npm ERR! Found: react-native@0.68.2
npm ERR! node_modules/react-native
npm ERR!   peer react-native@"*" from @react-native-community/cli@7.0.3
npm ERR!   node_modules/@react-native-community/cli
npm ERR!     @react-native-community/cli@"^7.0.3" from react-native@0.68.2
npm ERR!   react-native@"0.69.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! react-native@"0.69.0" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: react@18.0.0
npm ERR! node_modules/react
npm ERR!   peer react@"18.0.0" from react-native@0.69.0
npm ERR!   node_modules/react-native
npm ERR!     react-native@"0.69.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps

### Issue and Reproduction Steps

I am developping on 0.68.2 some projects (on Windows)
I want to create a new project to test the new version 0.69, so I installed CMAKE and do : 

>npx react-native init test_RN69
Need to install the following packages:
  react-native@0.69.0
Ok to proceed? (y) y
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: undefined@undefined
npm ERR! Found: react-native@0.68.2
npm ERR! node_modules/react-native
npm ERR!   peer react-native@"*" from @react-native-community/cli@7.0.3
npm ERR!   node_modules/@react-native-community/cli
npm ERR!     @react-native-community/cli@"^7.0.3" from react-native@0.68.2
npm ERR!   react-native@"0.69.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! react-native@"0.69.0" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: react@18.0.0
npm ERR! node_modules/react
npm ERR!   peer react@"18.0.0" from react-native@0.69.0
npm ERR!   node_modules/react-native
npm ERR!     react-native@"0.69.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!

Where is the wrong manipulation please ?

**Comment by kockok** [comment]
Yes, I also encounter similar thing when I run:
`npx react-native init TYapp --template react-native-template-typescript`

```
Need to install the following packages:
  react-native@0.69.0
Ok to proceed? (y) y
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: undefined@undefined
npm ERR! Found: react-native@0.68.1
npm ERR! node_modules/react-native
npm ERR!   peer react-native@"*" from @react-native-community/cli@7.0.3
npm ERR!   node_modules/@react-native-community/cli
npm ERR!     @react-native-community/cli@"^7.0.3" from react-native@0.68.1
npm ERR!   react-native@"0.69.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! react-native@"0.69.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: react@18.0.0
npm ERR! node_modules/react
npm ERR!   peer react@"18.0.0" from react-native@0.69.0
npm ERR!   node_modules/react-native
npm ERR!     react-native@"0.69.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 

npm ERR! A complete log of this run can be found in:
```

And generating a new app was not successful.

**Comment by CodingItWrong** [comment]
I get the same error on an Intel Mac; all `npx react-native` commands fail with the same error.

**Comment by edwin-nel** [comment]
Removing the ~/.npm cache folder fixed the problem for me

**Comment by CodingItWrong** [comment]
@edwin-nel's fix worked for me on an Intel Mac as well.

**Comment by CodingItWrong** [comment]
I do kind of feel like this is still an issue the maintainers would ideally address. To me clearing NPM cache seems like a workaround, not what you'd ideally need to do when running an `npx` command.

**Comment by CodingItWrong** [comment]
@Productivix I think reopening is good, yes. It keeps it visible to the maintainers and they can decide about prioritization 👍

**Comment by cortinico** [comment]
@Productivix did you had any version of react-native installed globally before?
It seems like this is the case by:

```
npm ERR! While resolving: undefined@undefined
npm ERR! Found: react-native@0.68.1
npm ERR! node_modules/react-native
npm ERR!   peer react-native@"*" from @react-native-community/cli@7.0.3
npm ERR!   node_modules/@react-native-community/cli
npm ERR!     @react-native-community/cli@"^7.0.3" from react-native@0.68.1
npm ERR!   react-native@"0.69.0" from the root project
```

Specifically:
> @react-native-community/cli@"^7.0.3" from react-native@0.68.1

Not sure what is causing this, but RN 0.69 is depending on CLI v8. Therefore you should not be having CLI v7 during your install phase.

You should be good having both RN 0.68 and 0.69 as long as they're not global.

**Comment by CodingItWrong** [comment]
(If it is okay for me to chime in, I have not done the workaround on one computer, so I can still test the problem state.)

On an Apple M1 computer still experiencing the problem, I believe the following command confirms I don't have CLI installed globally, but the problem still happens:

```bash
$ npm list -g | grep react-native
(no output)
$ npx react-native init MyApp
Need to install the following packages:
  react-native@0.69.0
Ok to proceed? (y)
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: undefined@undefined
npm ERR! Found: react-native@0.68.2
```

etc

**Comment by cortinico** [comment]
> On an Apple M1 computer still experiencing the problem, I believe the following command confirms I don't have CLI installed globally, but the problem still happens:

I still believe it's a local setup problem. I'm on a Mac M1 and the same commands you posted lead to this:

```
$ npm list -g | grep react-native
(no-output)
$ npx react-native init MyApp
Need to install the following packages:
  react-native
Ok to proceed? (y) y

               ######                ######
             ###     ####        ####     ###
            ##          ###    ###          ##
            ##             ####             ##
            ##             ####             ##
            ##           ##    ##           ##
            ##         ###      ###         ##
             ##  ########################  ##
          ######    ###            ###    ######
      ###     ##    ##              ##    ##     ###
   ###         ## ###      ####      ### ##         ###
  ##           ####      ########      ####           ##
 ##             ###     ##########     ###             ##
  ##           ####      ########      ####           ##
   ###         ## ###      ####      ### ##         ###
      ###     ##    ##              ##    ##     ###
          ######    ###            ###    ######
             ##  ########################  ##
            ##         ###      ###         ##
            ##           ##    ##           ##
            ##             ####             ##
            ##             ####             ##
            ##          ###    ###          ##
             ###     ####        ####     ###
               ######                ######


                  Welcome to React Native!
                 Learn once, write anywhere
```

**Comment by CodingItWrong** [comment]
I agree; there is something wrong in my local setup that the workaround above clears up. Several of us have experienced the problem in the local setup, and we aren't aware of anything specific we've done wrong. Happy to help collaborate on an investigation here, or since there is a workaround y'all can of course choose to deprioritize until if/when more people report the problem.

**Comment by cortinico** [comment]
> I agree; there is something wrong in my local setup that the workaround above clears up.

I would try to see if there is anything global with:

```
npm list -g 
yarn global list
```

And uninstall everything.
If that helps, it works on npm version 8.5.0

**Comment by Productivix** [comment]
hi, 
I have on my windows machine still the error (I do not purge the .npm cache).
To help on the global installs : 
s>npm list -g
C:\Users\info\AppData\Roaming\npm
+-- eas-cli@0.54.1
+-- expo-cli@5.4.11
+-- npm-check-updates@14.0.1
+-- npm-check@5.9.2
+-- npm@8.12.2
+-- pm2@5.2.0
+-- upgrade-node-modules@1.4.0
`-- yarn@1.22.19

--> may be the expo ???

and : 
> yarn global list
yarn global v1.22.19
info "react-native-rename@2.9.0" has binaries:
   - react-native-rename
Done in 0.46s.
(this I do not know where it is coming from) 

hope that will help you !

**Comment by Productivix** [comment]
to complete the test : 
still same error with a global empty list in yarn and with only : 
npm list -g
C:\Users\info\AppData\Roaming\npm
+-- npm-check-updates@14.0.1
+-- npm-check@5.9.2
+-- npm@8.12.2
+-- pm2@5.2.0
+-- upgrade-node-modules@1.4.0
`-- yarn@1.22.19

**Comment by Productivix** [comment]
I re-read the erro message I put some days ago, 
and I suppressed the content of C:\Users\info\AppData\Local\npm-cache\_npx
and it runs ! 
( npx react-native init MyApp
Need to install the following packages:
  react-native
Ok to proceed? (y) y)
(tests on win10)

**Comment by utsavo-afk** [comment]
In my case i am using nvm, for me npm uninstall -g react-native-cli did the trick even though I had not globally installed this package

**Comment by Sharipkanov** [comment]
run command:
`npm config set legacy-peer-deps true`

**Comment by cortinico** [comment]
> I re-read the erro message I put some days ago,
> and I suppressed the content of C:\Users\me\AppData\Local\npm-cache_npx
> and it runs !

Closing as it's reported as solved

**Comment by jai1233** [comment]
beloe command worked for me into my M1 Mac 
npm config set legacy-peer-deps true

**Comment by lucalves** [comment]
> Removing the ~/.npm cache folder fixed the problem for me on Macbook M1

Thanks!

**Comment by itsmefordyfy** [comment]
> run command:
> `npm config set legacy-peer-deps true`
> after that you can create new project

This works for me. I'm using M1 Max.

**Comment by Bilal-Abdeen** [comment]
> Removing the ~/.npm cache folder fixed the problem for me on Macbook M1

On Windows: delete the folder:
`C:\Users\<UserName>\AppData\Local\npm-cache`

**Comment by Majid460** [comment]
For Mac:
After many tries i found that in 0.69 its bit different to create project with respect to 0.68. 
First you have to make a folder then run command  **npx react-native init yourProjectname** .
Second it shows the **cli-init** error then move into folder that you created **cd yourProjectname**
then run command **npm config set legacy-peer-deps true** again run  **npx react-native init yourProjectname** .
It works.

**Comment by esthor** [comment]
If you don't want to go the nuclear option of removing your entire npm cache, you can use a temporary, fresh cache:

`npx --cache /tmp/empty-cache react-native init AwesomeTSProject --template react-native-template-typescript`
or
`npx --cache /tmp/empty-cache react-native init AwesomeProject`

It's not a HUGE issue, but let me explain my nit here: `rm -rf ~/.npm` or `npm cache clean --force` are going to remove the _entire_ npm cache on your system, meaning _any_ js dep you need for _any_ project on your machine will need to be re-downloaded. The issue in this thread seems localized to `react-native` and the `@react-native-community/cli`, specifically for anyone trying to use React Native 0.69.x on a machine that has had a previous version of React Native on it, whether installed globally (please don't) or in the default npm cache.

**Comment by valonmulolli** [comment]
> run command: `npm config set legacy-peer-deps true` after that you can create new project

Thanks!!

**Comment by alan-alro** [comment]
Thanks @matheusgoc for the explanation. For me it's always good to know what happened instead of just how to fix it. But for the record, `npm config set legacy-peer-deps true` fixes the issue for me too.

**Comment by DeoclecioFilho** [comment]
> npm config set legacy-peer-deps true

Funcionou aqui também!!
here too!

Obrigado
Tanks

**Comment by samad324** [comment]
> npm config set legacy-peer-deps true

Works for me

**Comment by samad324** [comment]
for folks using `react-native init` use this comment instead
```npx @react-native-community/cli init AwesomeProject```
