### ISSUE TITLE
Is there any easy way to enable TurboModule and Fabric without custom stuffs?

### ISSUE THREAD

**Issue by psionic12** [facebook/react-native#34053]
### Description

I found that the [tutorial](https://reactnative.dev/docs/new-architecture-app-renderer-android) of enabling `TurboModule` and `Fabric` in Android part is way more complicated than it is in iOS part, it seems that the example in Android part contains a lot of custom stuffs, such as `NativeAwesomeManager`, `MyComponentsRegistry` and so on, which is not mentioned in iOS. I enabled these two features on iOS easily, but struggling on Android side.

I got some confusions about the tutorial:
1. The Android part contains tutorials about customize a TurbolModule and a Fabric engine, while iOS part only contains tutorials about how to enable TurbolModule and Fabric, right?
2. Even if I didn't custom TurbolModule and Fabric in Android, these two features should still be able to used, right? (I guessed so because I found that the RN framework use the techs in this tutorial to generate `rncore`)
3. If two is right, this there any easy way to just enable them without customizing?

### Version

0.68.1

### Output of `npx react-native info`

I build react from source.

### Steps to reproduce

I just follow the [tutorial](https://reactnative.dev/docs/new-architecture-app-renderer-android)

### Snack, code example, screenshot, or link to a repository

None

**Comment by Skullcan** [comment]
I'm trying the new architecture as well and I find really hard to understand all the code and changes they make in the java files.

Maybe a 'simpler' documentation would be nice to have for people who just want to use w/o custom components as you said.

**Comment by cortinico** [comment]
> I found that the [tutorial](https://reactnative.dev/docs/new-architecture-app-renderer-android) of enabling `TurboModule` and `Fabric` in Android part is way more complicated than it is in iOS part, it seems that the example in Android part contains a lot of custom stuffs, such as `NativeAwesomeManager`, `MyComponentsRegistry` and so on, which is not mentioned in iOS. I enabled these two features on iOS easily, but struggling on Android side.

Thanks for the report @psionic12 

Have you considered using the new app template (i.e. `npx react-native init`). All the extra stuff will be automatically generated for you.

And yes, those are necessary as the Android logic now needs to know which C++ modules to load. On iOS the setup was easier as we were already compiling native code in the past.

Closing as this was a question, not a real issue. Thanks for reporting it though 👍

**Comment by psionic12** [comment]
@cortinico thanks for helping, the template helps, I finally enable fabric without customizing any JS code. When I say "complicated", I don't mean to use C++ or JNI, I mean the Android tutorial teaches how to enable fabric and how to custom one with your own JS code in one place, which may lead to a reader to confuse which part is a necessary, and which part is optional. It looks to me that the iOS tutorial is much clearer.
