### ISSUE TITLE
Cannot read property 'resizeMode' of undefined

### ISSUE THREAD

**Issue by heekyu-pu** [facebook/react-native#34054]
### Description

**Error Occurred after upgrade to 0.69**

 ERROR  TypeError: Cannot read property 'resizeMode' of undefined, js engine: hermes
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes

 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes

### Version

0.69.0

### Output of `npx react-native info`

app % npx react-native info
warn Package @sentry/react-native has been ignored because it contains invalid configuration. Reason: "dependency.platforms.ios.sharedLibraries" is not allowed
warn Package appcenter has been ignored because it contains invalid configuration. Reason: "dependency.platforms.ios.podspecPath" is not allowed
warn Package appcenter-analytics has been ignored because it contains invalid configuration. Reason: "dependency.platforms.ios.podspecPath" is not allowed
warn Package appcenter-crashes has been ignored because it contains invalid configuration. Reason: "dependency.platforms.ios.podspecPath" is not allowed
warn Package react-native-appsflyer has been ignored because it contains invalid configuration. Reason: "dependency.platforms.ios.podspecPath" is not allowed
warn Package react-native-vector-icons has been ignored because it contains invalid configuration. Reason: "dependency.assets" is not allowed
info Fetching system and libraries information...
System:
    OS: macOS 11.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 104.66 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.1/bin/yarn
    npm: 8.3.0 - ~/.nvm/versions/node/v16.13.1/bin/npm
    Watchman: 2022.06.13.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.69.0 => 0.69.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. upgraded from 0.68.1
2. yarn android
3. android build success
4. metro bundler bundle success
5. app failed to launch with above error (resizeMode)

react-native/Libraries/NewAppScreen works well

### Snack, code example, screenshot, or link to a repository

<img width="574" alt="스크린샷 2022-06-23 오후 6 30 23" src="https://user-images.githubusercontent.com/67251827/175266867-96193106-fc1d-41fd-bb08-aba89840f517.png">

**Comment by cortinico** [comment]
> Snack, code example, screenshot, or link to a repository

Can you provide a reproducer?

**Comment by YangJonghun** [comment]
TypeError is not related with Invariant Violation Error
`TypeError: Cannot read property 'resizeMode' of undefined` just occurred when use `Image.propTypes.resizeMode` (it should be replaced by `deprecated-react-native-prop-types`).
If you don't use above code, please check your dependencies.

also, output of your react-native info is related with react-native-cli's breaking change about `react-native.config.js`
```
warn Package @sentry/react-native has been ignored because it contains invalid configuration. Reason: "dependency.platforms.ios.sharedLibraries" is not allowed
warn Package appcenter has been ignored because it contains invalid configuration. Reason: "dependency.platforms.ios.podspecPath" is not allowed
warn Package appcenter-analytics has been ignored because it contains invalid configuration. Reason: "dependency.platforms.ios.podspecPath" is not allowed
warn Package appcenter-crashes has been ignored because it contains invalid configuration. Reason: "dependency.platforms.ios.podspecPath" is not allowed
warn Package react-native-appsflyer has been ignored because it contains invalid configuration. Reason: "dependency.platforms.ios.podspecPath" is not allowed
warn Package react-native-vector-icons has been ignored because it contains invalid configuration. Reason: "dependency.assets" is not allowed
```
(FYI. https://reactnative.dev/blog/2022/06/21/version-069#breaking-changes)
(FYI2. https://github.com/react-native-community/cli/pull/1537)
so, you have to wait until library update or patch it

**Comment by heekyu-pu** [comment]
it turns out that react-native-video issue
https://github.com/react-native-video/react-native-video/issues/2752

Thanks!
