### ISSUE TITLE
TypeError: cli.init is not a function

### ISSUE THREAD

**Issue by marandaneto** [facebook/react-native#34055]
### Description

`npx react-native init Name` throws when creating a template with RN v0.69

### Version

0.69.0

### Output of `npx react-native info`

yarn v1.22.19
react-native-cli: 2.0.1
react-native: n/a - not inside a React Native project directory
So I can't `npx react-native info`

### Steps to reproduce

Just do `npx react-native init Name` using macOS 12.4, Intel.

### Snack, code example, screenshot, or link to a repository

/Users/user/.config/yarn/global/node_modules/react-native-cli/index.js:302
  cli.init(root, projectName);
      ^

TypeError: cli.init is not a function
    at run (/Users/user/.config/yarn/global/node_modules/react-native-cli/index.js:302:7)
    at createProject (/Users/user/.config/yarn/global/node_modules/react-native-cli/index.js:249:3)
    at init (/Users/user/.config/yarn/global/node_modules/react-native-cli/index.js:200:5)
    at Object.<anonymous> (/Users/user/.config/yarn/global/node_modules/react-native-cli/index.js:153:7)
    at Module._compile (node:internal/modules/cjs/loader:1112:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:834:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47

Node.js v18.4.0

**Comment by Naveen562117** [comment]
I am also getting same issue 
npx react-native init HeyGroopApp --template react-native-template-typescript

/usr/local/lib/node_modules/react-native-cli/index.js:302
  cli.init(root, projectName);
      ^

TypeError: cli.init is not a function
    at run (/usr/local/lib/node_modules/react-native-cli/index.js:302:7)
    at createProject (/usr/local/lib/node_modules/react-native-cli/index.js:249:3)
    at init (/usr/local/lib/node_modules/react-native-cli/index.js:200:5)
    at Object.<anonymous> (/usr/local/lib/node_modules/react-native-cli/index.js:153:7)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47

**Comment by OmarBasem** [comment]
That is error is from the new version 0.69.0
You can use `npx react-native init ProjectName --version 0.68.2` and then upgrade to v 0.69 later.

**Comment by evildevilnova** [comment]
> That is error is from the new version 0.69.0 You can use `npx react-native init ProjectName --version 0.68.2` and then upgrade to v 0.69 later. 
thank you it's working

**Comment by plipustel** [comment]
all of them not work

**Comment by olivertembo** [comment]
@plipustel what node version are you using?

I am on Mac,M1

Try using V14.19.1

Not quite sure but I have tried uninstalling node lts, clearing cache but using node version 14 runs without a problem.

**Comment by stefanoHTB** [comment]
getting the same error!

**Comment by spiroalisandratos** [comment]
Even if you down grade the version.  Once you try to run the project if fails anyway.  I think it's related to the new Mac OS upgrade and the hardening of permissions.

**Comment by krishna19982904** [comment]
> > That is error is from the new version 0.69.0
> > You can use `npx react-native init ProjectName --version 0.68.2` and then upgrade to v 0.69 later.
> 
> Thank You

Could you please explain how to upgrade to 0.69.0 later and what exactly is causing this issue  due to version change?

**Comment by stefanoHTB** [comment]
This error is happening on windows as well!  I temporarily fixed it by downgrading to last version

**Comment by krishna19982904** [comment]
> That is error is from the new version 0.69.0 You can use `npx react-native init ProjectName --version 0.68.2` and then upgrade to v 0.69 later.

Could you please explain how to upgrade to 0.69.0 later and what exactly is causing this issue due to version change?

**Comment by lcrossi** [comment]
I had the same issue on windows... using version 0.68.2 solved the problem

**Comment by chungtvdev** [comment]
> > That is error is from the new version 0.69.0
> > You can use `npx react-native init ProjectName --version 0.68.2` and then upgrade to v 0.69 later.
> 
> Thank You

Hi, How to upgrade ?

**Comment by hnasirzade310** [comment]
thank you so much

**Comment by cortinico** [comment]
> /Users/user/.config/yarn/global/node_modules/react-native-cli/index.js:302

The issue is caused by having some globally installed Yarn/NPM packages which is not generally recommended.

Depending on the commands you installed in the past with `-g`, you should be able to cleanup your environment with a combination of those commands:

```
yarn global remove react-native
yarn global remove react-native-cli
npm uninstall -g react-native
npm uninstall -g react-native-cli
```

Make sure the global packages are clean with:

```
yarn global list
npm -g list
```

(check that nothing react-native related is available in those lists).

**Comment by Bsingh2697** [comment]
> > > That is error is from the new version 0.69.0
> > > You can use `npx react-native init ProjectName --version 0.68.2` and then upgrade to v 0.69 later.
> > 
> > 
> > Thank You
> 
> Could you please explain how to upgrade to 0.69.0 later and what exactly is causing this issue due to version change?

just change the package version in package.json and npm install and if u wish u can remove node_modules before npm install

**Comment by spiroalisandratos** [comment]
If you go to yarn page they have global install

Sent from my iPhone

On 25 Jun 2022, at 10:59 pm, Bsingh2697 ***@***.***> wrote:

﻿

That is error is from the new version 0.69.0
You can use npx react-native init ProjectName --version 0.68.2 and then upgrade to v 0.69 later.

Thank You

Could you please explain how to upgrade to 0.69.0 later and what exactly is causing this issue due to version change?

just change the package version in package.json and npm install and if u wish u can remove node_modules before npm install

**Comment by devinkg** [comment]
> > /Users/user/.config/yarn/global/node_modules/react-native-cli/index.js:302
> 
> The issue is caused by having some globally installed Yarn/NPM packages which is not generally recommended.
> 
> Depending on the commands you installed in the past with `-g`, you should be able to cleanup your environment with a combination of those commands:
> 
> ```
> yarn global remove react-native
> yarn global remove react-native-cli
> npm uninstall -g react-native
> npm uninstall -g react-native-cli
> ```
> 
> Make sure the global packages are clean with:
> 
> ```
> yarn global list
> npm -g list
> ```
> 
> (check that nothing react-native related is available in those lists).

This worked for me. Thanks!

**Comment by vmobeedeveloper** [comment]
> > > /Users/user/.config/yarn/global/node_modules/react-native-cli/index.js:302
> > 
> > 
> > The issue is caused by having some globally installed Yarn/NPM packages which is not generally recommended.
> > Depending on the commands you installed in the past with `-g`, you should be able to cleanup your environment with a combination of those commands:
> > ```
> > yarn global remove react-native
> > yarn global remove react-native-cli
> > npm uninstall -g react-native
> > npm uninstall -g react-native-cli
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Make sure the global packages are clean with:
> > ```
> > yarn global list
> > npm -g list
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > (check that nothing react-native related is available in those lists).
> 
> This worked for me. Thanks!

**Comment by Hassaan0** [comment]
> That is error is from the new version 0.69.0
> You can use `npx react-native init ProjectName --version 0.68.2` and then upgrade to v 0.69 later.

This worked for me. Thanks!

**Comment by kevinsiregar22** [comment]
update react-native and react-native cli as global

**Comment by kevinsiregar22** [comment]
yarn global remove react-native
yarn global remove react-native-cli
npm uninstall -g react-native
npm uninstall -g react-native-cli

then install again 

yarn add global  react-native
yarn add global  react-native-cli
npm install -g react-native
npm install -g react-native-cli

good luck

**Comment by 365rafael** [comment]
Este comando funcionou perfeitamente aqui
npx react-native init ProjectName --version 0.68.2

**Comment by liresky** [comment]
> Este comando funcionou perfeitamente aqui npx react-native init ProjectName --version 0.68.2

error not resolved，but we have a way to avoid this error。

**Comment by horaczech** [comment]
I am not sure if status = close is correct, until they fix the current version.

**Comment by LeonardoMeneghini** [comment]
I had the same issue on Windows 10. Downgrade to 0.68.2 version solved my problem.

**Comment by trongduc03** [comment]
> That is error is from the new version 0.69.0 You can use `npx react-native init ProjectName --version 0.68.2` and then upgrade to v 0.69 later.

Thank you so muck.

**Comment by temiNoah** [comment]
> That is error is from the new version 0.69.0 You can use `npx react-native init ProjectName --version 0.68.2` and then upgrade to v 0.69 later.

thanks so much

**Comment by temiNoah** [comment]
> > > That is error is from the new version 0.69.0
> > > You can use `npx react-native init ProjectName --version 0.68.2` and then upgrade to v 0.69 later.
> > 
> > 
> > Thank You
> 
> Hi, How to upgrade ?

from the below info:
info React Native v0.69.1 is now available (your project is running on v0.68.2).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.69.1.
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.68.2.
info To upgrade, run "react-native upgrade".

**Comment by manisha351** [comment]
npx react-native init ProjectName --version 0.68.2 worked for me

**Comment by mrVancetti** [comment]
No problem now, you can build your project directly using `npx react-native init YourProject`. 
Happy coding :)

**Comment by ItsCDubb** [comment]
hen you use npx react-native init <insertProject name here> --version 0.68.2 --template react-native-template-typescript nothing happens exept it fails with RuntimeError: abort(Error: Command failed: yarn add react-native-template-react-native-template-typescript~)

how do you get around that? Because I want to use TypeScript not JavaScript

**Comment by benjamineruvieru** [comment]
> > /Users/user/.config/yarn/global/node_modules/react-native-cli/index.js:302
> 
> The issue is caused by having some globally installed Yarn/NPM packages which is not generally recommended.
> 
> Depending on the commands you installed in the past with `-g`, you should be able to cleanup your environment with a combination of those commands:
> 
> ```
> yarn global remove react-native
> yarn global remove react-native-cli
> npm uninstall -g react-native
> npm uninstall -g react-native-cli
> ```
> 
> Make sure the global packages are clean with:
> 
> ```
> yarn global list
> npm -g list
> ```
> 
> (check that nothing react-native related is available in those lists).

So after uninstalling what are we to do next?
Are we to reinstall globally again or we dont install globally this time or we dont install at all and give up
Your answer is not complete

**Comment by Keyur-RV** [comment]
@benjamineruvieru After uninstalling, reinstall globally and then create a project, it can be created successfully.

**Comment by emorilebo** [comment]
You might be using old react-native-cli. Maybe you should try uninstalling and react-native-cli globally and reinstalling it.
use:
**npm uninstall -g react-native-cli** to uninstall and **npx react-native init yourprojectname** to reinstall. You will be prompted to install react-native again, accepted it and proceed.

**Comment by ItsCDubb** [comment]
TY @emorilebo, That worked & I didn't even realize that I had the old version of the react-native-cli installed

**Comment by Dev-Vithushan** [comment]
I am using MacOS 12.4 for me When i creates the React Native app using npm it is showing like this
_I used cli 0.68.2_

`Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
Error: Command failed: yarn add react-native@0.68.2 --exact
    at checkExecSyncError (child_process.js:790:11)
    at execSync (child_process.js:863:15)
    at run (/Users/vithushan/.config/yarn/global/node_modules/react-native-cli/index.js:294:5)
    at createProject (/Users/vithushan/.config/yarn/global/node_modules/react-native-cli/index.js:249:3)
    at init (/Users/vithushan/.config/yarn/global/node_modules/react-native-cli/index.js:200:5)
    at Object.<anonymous> (/Users/vithushan/.config/yarn/global/node_modules/react-native-cli/index.js:153:7)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 36901,
  stdout: null,
  stderr: null
}
Command `yarn add react-native@0.68.2 --exact` failed.`


### Give me a solution for me!!!

**Comment by Bsingh2697** [comment]
Did you try without that exact flag?

**Comment by jalloh-codes** [comment]
> You might be using old react-native-cli. Maybe you should try uninstalling and react-native-cli globally and reinstalling it. use: **npm uninstall -g react-native-cli** to uninstall and **npx react-native init yourprojectname** to reinstall. You will be prompted to install react-native again, accepted it and proceed.

This works for me, thanks @emorilebo

**Comment by dmcchanaka** [comment]
Actually latest version (0.69.0) still not working. so please try below steps

yarn global remove react-native
yarn global remove react-native-cli
npm uninstall -g react-native
npm uninstall -g react-native-cli

then install again

yarn add global react-native
yarn add global react-native-cli
npm install -g react-native
npm install -g react-native-cli

**Comment by Bikash9609** [comment]
> > /Users/user/.config/yarn/global/node_modules/react-native-cli/index.js:302
> 
> The issue is caused by having some globally installed Yarn/NPM packages which is not generally recommended.
> 
> Depending on the commands you installed in the past with `-g`, you should be able to cleanup your environment with a combination of those commands:
> 
> ```
> yarn global remove react-native
> yarn global remove react-native-cli
> npm uninstall -g react-native
> npm uninstall -g react-native-cli
> ```
> 
> Make sure the global packages are clean with:
> 
> ```
> yarn global list
> npm -g list
> ```
> 
> (check that nothing react-native related is available in those lists).

Worked for me too. Thanks!

**Comment by zainulabideen-dev** [comment]
I just run below command and it works for me
npx react-native init StudentsHub --version 0.69.1

**Comment by pudgefury** [comment]
> 

What is your node version?

**Comment by zainulabideen-dev** [comment]
I fixed it. Thanks for replying

**Comment by ansarikhurshid786** [comment]
I fixed by deleting folder: 
(/Users/user/.config/yarn/global/node_modules/react-native-cli

Now it is working for me. I think it is old which is completely not deleted.

**Comment by pistolcaffe** [comment]
Are there any fixes in the latest version? When creating a project in `IntelliJ`, the same issue occurs with `npx --package react-native-cli react-native` script for installing the `react-native` module.

(I'm using `npx --package react-native-cli react-native --version 0.68.2` instead)

**Comment by kevinsiregar22** [comment]
If you previously installed a global react-native-cli package, please remove it as it may cause unexpected issues:

npm uninstall -g react-native-cli @react-native-community/cli . it works for me. good luck guys. 

from : https://reactnative.dev/docs/environment-setup

**Comment by alexeenka** [comment]
26 Dec. I have the same error: 


```
/Users/a.alexeenka/.nvm/versions/node/v19.3.0/lib/node_modules/react-native-cli/index.js:302
  cli.init(root, projectName);
      ^

TypeError: cli.init is not a function
```

Only running with 'react-native init MyApp  --version 0.68.2' fixed the issue

**Comment by msriaz** [comment]
Surprisingly none of above worked for me other than: 
```
yarn remove react-native -g
yarn remove react-native-cli -g
```
Please also make sure you've correct version of ruby
React Native uses [this version](https://github.com/facebook/react-native/blob/main/template/_ruby-version) of Ruby. You can also find which version your specific project needs in the .ruby-version file at root of your RN project

**Comment by Gattupatel05** [comment]
> Actually latest version (0.69.0) still not working. so please try below steps
> 
> yarn global remove react-native yarn global remove react-native-cli npm uninstall -g react-native npm uninstall -g react-native-cli
> 
> then install again
> 
> yarn add global react-native yarn add global react-native-cli npm install -g react-native npm install -g react-native-cli

It's do as **ran as administrator** mode ??

**Comment by horaczech** [comment]
I got it working after going to /Users/{{username}}/node_modules (using Mac), and manually removed folders "react-native", "react-native-cli", "@react-native"

**Comment by azizimusa** [comment]
> **npm uninstall -g react-native-cli**

thanks. This also work with WebStorm new react native project

# npx --package react-native-cli react-native --version 0.68.2
# Then inside project. Update manually from package.json, then run npm install on terminal

**Comment by SWS-5007** [comment]
Thanks.
`npx react-native init ProjectName --version 0.68.2`
This works well for me too
