### ISSUE TITLE
Unrecognized command "link"

### ISSUE THREAD

**Issue by danbudworthmead** [facebook/react-native#34069]
### Description

When trying to add a font I'm following guides that say I need to do `npx react-native link` command. But it throws the error of Unrecognized command "link" info Run "react-native --help" to see a list of all available commands.

### Version

0.69.0

### Output of `npx react-native info`

System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 AMD Ryzen 5 3600X 6-Core Processor
    Memory: 12.47 GB / 31.95 GB
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 24, 28, 29, 30, 31
      Build Tools: 28.0.3, 30.0.0, 30.0.3, 31.0.0
      System Images: android-31 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: Not Found
  Languages:
    Java: 18.0.1.1
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^18.2.0 => 18.2.0
    react-native: ^0.69.0 => 0.69.0
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Run npx react-native link

### Snack, code example, screenshot, or link to a repository

npx react-native info

**Comment by Kewal89** [comment]
I think `link` has been removed completely in `v0.69`

`link and unlink commands have been removed in the favour of autolinking` 

Ref : https://reactnative.dev/blog/2022/06/21/version-069

**Comment by cortinico** [comment]
> When trying to add a font I'm following guides that say I need to do `npx react-native link` command.

Which guide specifically?

Also closing as this was already answered by @Kewal89 + is a question for the CLI repo: github.com/react-native-community/cli/

**Comment by danbudworthmead** [comment]
> > When trying to add a font I'm following guides that say I need to do `npx react-native link` command.
> 
> Which guide specifically?
> 
> Also closing as this was already answered by @Kewal89 + is a question for the CLI repo: github.com/react-native-community/cli/

Every time I googled "how to add custom font to react native"

Thank you for your help folks

**Comment by cortinico** [comment]
> Every time I googled "how to add custom font to react native"

I was more wondering if this is an official guide or a blogpost you found on the web.
If it's an official guide: we need to update it.
If it's a blogpost, you can ask the author to mention that the command is deprecated. Otherwise there is not much more we can do.

**Comment by danbudworthmead** [comment]
> Otherwise there is not much more we can do.

Oh yeah I'm fully aware it's nothing to do with yous. Thank you for all of your help :)

**Comment by danbudworthmead** [comment]
I do have a question though.

I have a react-native.config.js file that looks like:
`module.exports = {    
   project: {
    ios: {},
    android: {}, // grouped into "project"
  },
  assets: ['./assets/fonts/'],
};
`

and I have a font in that directory, however using that font in fontFamily doesn't change the font. Is there something specific I need to do to enable autolinking? Or is there a way for me to see what is being "auto-linked"?

**Comment by cortinico** [comment]
> and I have a font in that directory, however using that font in fontFamily doesn't change the font. Is there something specific I need to do to enable autolinking? Or is there a way for me to see what is being "auto-linked"?

You can find docs on autolinking here: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md

Specific questions on autolinking should be asked on the https://github.com/react-native-community/cli repo so you can get exact answers
