### ISSUE TITLE
Android Studio Intellisense for New Architecture imports breaks after updating to RN 0.69.0

### ISSUE THREAD

**Issue by friyiajr** [facebook/react-native#34067]
### Description

When trying to code in Android Studio, pretty much all imports from React-Native say that they cannot be found after updating to React-Native 0.69.0. This seems like it's some kind of gradle issue since `yarn android` compiles the project and the code runs with no issues. Still, its very annoying if you want to write any custom TurboModules code. 

### Version

0.69.0

### Output of `npx react-native info`

```
System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1 Pro
    Memory: 168.73 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.0.0 - /opt/homebrew/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 8.6.0 - /opt/homebrew/bin/npm
    Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /Users/dfriyia/.gem/ruby/2.7.4/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 29, 30, 31, 32
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0
      System Images: android-29 | Google APIs ARM 64 v8a, android-29 | Google APIs Intel x86 Atom_64, android-30 | ARM 64 v8a, android-30 | Intel x86 Atom_64, android-30 | Google TV Intel x86 Atom, android-30 | Google APIs ARM 64 v8a, android-30 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom_64, android-30 | Google Play ARM 64 v8a, android-30 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom_64, android-32 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8309675
    Xcode: 13.3/13E113 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.14 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.0 => 0.69.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

Clone https://github.com/friyiajr/TurboAndroidReproducer and open it in Android Studio. Look at the `MainApplication.java` file. All imports will be red but the application will compile just fine if you run `yarn android`

### Snack, code example, screenshot, or link to a repository

https://github.com/friyiajr/TurboAndroidReproducer on master branch

**Comment by cortinico** [comment]
> When trying to code in Android Studio, pretty much all imports from React-Native say that they cannot be found after updating to React-Native 0.69.0. This seems like it's some kind of gradle issue since yarn android compiles the project and the code runs with no issues. Still, its very annoying if you want to write any custom TurboModules code.

Thanks for reporting this. I was aware of this issue sadly, as I was experincing it while working on `main`. Users on new arch will suffer this as well as they're building RN from source.

This is essentially a bug in Android Studio. What is happening is that we do have mixed sources (Java & C++) inside the React Native Core codebase. In mixed folders, Android Studio is assuming that all the sources are C++ (I'm oversimplifying, but that's the end result).

Practically, we should either:
- Open an issue against Android Studio
- Modify our source code structure of React Native to make Android Studio recognize the C++ source code as isolated.

**Comment by friyiajr** [comment]
Hi @VishalMishra0, thanks for your concern, since this is an issue with my tutorial can you please comment in YouTube and not here? I am not a maintainer of React-Native and so I don't want to concern these developers with issues on my content.

**Comment by cortinico** [comment]
Just a heads up that this is now fixed. With React Native 0.71 you won't have this problem anymore 👍

**Comment by cortinico** [comment]
Super small heads up: I took some time to write a short note about this specific issue which was affecting you and others on New Architecture on Android here: https://github.com/reactwg/react-native-new-architecture/discussions/102
We're going to highlight this in the blogpost of .71 as several users also reported it.
