### ISSUE TITLE
Using Flex component make the application crash on Android

### ISSUE THREAD

**Issue by Vincent-DARIBO** [facebook/react-native#34068]
### Description

Here is the error : ```Error while updating property 'flex' in shadow node of type: RCTView ```

### Version

3.4.x

### Output of `npx react-native info`

System:
    OS: Linux 5.17 Fedora 34 (Thirty Four) 34 (Thirty Four)
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
    Memory: 140.67 MB / 7.53 GB
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 14.17.4 - /usr/local/bin/node
    Yarn: 1.22.18 - ~/.yarn/bin/yarn
    npm: 8.12.2 - /usr/local/bin/npm
    Watchman: 0.0.0 - /usr/bin/watchman
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 18.0.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.2 => 17.0.2 
    react-native: 0.68.2 => 0.68.2 
  npmGlobalPackages:
    *react-native*: Not Found
info React Native v0.69.0 is now available (your project is running on v0.68.2).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.69.0.
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.68.2.

### Steps to reproduce

Install native base and launch the code above

### Snack, code example, screenshot, or link to a repository

`import React from 'react';
import { Box, Container, Flex, Text } from 'native-base';

type Props = {
  title: string;
  user: string;
};

export default function DetailsCardText({ title, user }: Props) {

  return (
    <Box>
      <Flex align="center" justify="center" flex="row">
        <Container>
          <Text fontSize={16} textTransform="uppercase">
            {title}
          </Text>
        </Container>
      </Flex>
      <Flex align="center" justify="center" flex="row">
        <Text>by</Text>
        <Flex align="center" justify="center" flex="row">
          <Text color={theme.colors.primary}>{user}</Text>
        </Flex>
      </Flex>
    </Box>
  );
}`

**Comment by cortinico** [comment]
Please open your issue against the native-base repo: https://github.com/GeekyAnts/nativebase
Re-open this issue once you had a proof that is a react-native core issue 👍
