### ISSUE TITLE
Android Getting error while compiling C++ codes. "Turbo Module error: redefinition of 'NativeDeviceInfoSpecJSI'"

### ISSUE THREAD

**Issue by ponikar** [facebook/react-native#34065]
### Description

ANDROID: I am trying to enable turbo modules in my project. I did all mentioned steps. 

1. Enable New Architecture
2. Enable Harmes 
3. Create Spec File 
4. Updated my `build.gradle.` file
5. Running this command to generate the boilerplate code and java specfile. 
`./gradlew generateCodegenArtifactsFromSchema`

Everything is working fine till here. 

But when I am running `npm run android` 

I am getting the following error 

```
error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:buildNdkBuildDebug[reactnativedeviceinfo2_appmodules]'.
> Build command failed.
  Error while executing process /Users/darshanponikar/Library/Android/sdk/ndk/21.4.7075529/ndk-build with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=/Users/darshanponikar/projects/ReactNative/JSIExample/ReactNativeDeviceInfo2/android/app/src/main/jni/Android.mk APP_ABI=armeabi-v7a NDK_ALL_ABIS=armeabi-v7a NDK_DEBUG=1 NDK_OUT=/Users/darshanponikar/projects/ReactNative/JSIExample/ReactNativeDeviceInfo2/android/app/build/intermediates/cxx/Debug/5k466a60/obj NDK_LIBS_OUT=/Users/darshanponikar/projects/ReactNative/JSIExample/ReactNativeDeviceInfo2/android/app/build/intermediates/cxx/Debug/5k466a60/lib APP_CFLAGS+=-Wall APP_CFLAGS+=-Werror APP_CFLAGS+=-fexceptions APP_CFLAGS+=-frtti APP_CFLAGS+=-DWITH_INSPECTOR=1 APP_CPPFLAGS+=-std=c++17 APP_PLATFORM=android-21 APP_STL=c++_shared NDK_TOOLCHAIN_VERSION=clang GENERATED_SRC_DIR=/Users/darshanponikar/projects/ReactNative/JSIExample/ReactNativeDeviceInfo2/android/app/build/generated/source PROJECT_BUILD_DIR=/Users/darshanponikar/projects/ReactNative/JSIExample/ReactNativeDeviceInfo2/android/app/build REACT_ANDROID_DIR=/Users/darshanponikar/projects/ReactNative/JSIExample/ReactNativeDeviceInfo2/android/../node_modules/react-native/ReactAndroid REACT_ANDROID_BUILD_DIR=/Users/darshanponikar/projects/ReactNative/JSIExample/ReactNativeDeviceInfo2/android/../node_modules/react-native/ReactAndroid/build reactnativedeviceinfo2_appmodules}
  [armeabi-v7a] Compile++ thumb: reactnativedeviceinfo2_appmodules <= OnLoad.cpp
  [armeabi-v7a] Compile++ thumb: reactnativedeviceinfo2_appmodules <= MainComponentsRegistry.cpp
  [armeabi-v7a] Compile++ thumb: reactnativedeviceinfo2_appmodules <= MainApplicationTurboModuleManagerDelegate.cpp
  [armeabi-v7a] Compile++ thumb: reactnativedeviceinfo2_appmodules <= MainApplicationModuleProvider.cpp
  
  In file included from /Users/darshanponikar/projects/ReactNative/JSIExample/ReactNativeDeviceInfo2/android/app/src/main/jni/MainApplicationModuleProvider.cpp:4:
  /Users/darshanponikar/projects/ReactNative/JSIExample/ReactNativeDeviceInfo2/android/app/build/generated/source/codegen/jni/deviceinfo.h:23:18: error: redefinition of 'NativeDeviceInfoSpecJSI'
  class JSI_EXPORT NativeDeviceInfoSpecJSI : public JavaTurboModule {
                   ^
  /Users/darshanponikar/projects/ReactNative/JSIExample/ReactNativeDeviceInfo2/android/../node_modules/react-native/ReactAndroid/build/generated/source/codegen/jni/rncore.h:183:18: note: previous definition is here
  class JSI_EXPORT NativeDeviceInfoSpecJSI : public JavaTurboModule {
                   ^
  1 error generated.
  make: *** [/Users/darshanponikar/Library/Android/sdk/ndk/21.4.7075529/build/core/build-binary.mk:478: /Users/darshanponikar/projects/ReactNative/JSIExample/ReactNativeDeviceInfo2/android/app/build/intermediates/cxx/Debug/5k466a60/obj/local/armeabi-v7a/objs-debug/reactnativedeviceinfo2_appmodules//Users/darshanponikar/projects/ReactNative/JSIExample/ReactNativeDeviceInfo2/android/app/src/main/jni/MainApplicationModuleProvider.o] Error 1


* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
```

### Version

0.68

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 12.4
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 41.95 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.18.0 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.3.1 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8309675
    Xcode: 13.4/13F17a - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.4 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.2 => 0.68.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1 create fresh react-native project 0.68 
Follow this step to enable turbo modules. 

https://reactnative.dev/docs/new-architecture-library-android

### Snack, code example, screenshot, or link to a repository

https://github.com/ponikar/react-native-turbo-module-example

**Comment by cortinico** [comment]
The issue you're having is because you're trying to generate a turbomodule called `NativeDeviceInfo` which is clashing with the same module from ReactNative Core:
https://github.com/facebook/react-native/blob/main/Libraries/Utilities/NativeDeviceInfo.js

It would work fine if you rename it.

Thanks for providing a reproducer 🙏

**Comment by istashak** [comment]
I get this same sort of behavior such that my ~./gradle/caches/... are conflicting with the generated AppSpec.h file that contains many prebuild React Native modules -- see below. Note, this sort of issue does not happen on iOS.

I'd like to either prevent AppSpec.h from including the redefinition of the prebuilt modules, or have the compilation only use the AppSpec.h file. 

Has anyone conquered this? Currently my codegenConfig in package.json looks like so:

"codegenConfig": {
    "libraries": [
      {
        "name": "NativeBleModuleSpec",
        "type": "modules",
        "jsSrcsDir": "src/modules/ble",
        "android": {
          "packageName": "com.foo.prysm.ble"
        }
      },
      {
        "name": "NativeDfuModuleSpec",
        "type": "modules",
        "jsSrcsDir": "src/modules/dfu",
        "android": {
          "packageName": "com.foo.prysm.dfu"
        }
      }
    ]
  },

In file included from /Users/ivanstashak/dev/foo/prysm-project/prysm/node_modules/react-native/ReactAndroid/cmake-utils/default-app-setup/OnLoad.cpp:38:
/Users/ivanstashak/dev/foo/prysm-project/prysm/android/app/build/generated/source/codegen/jni/./AppSpec.h:30:18: error: redefinition of 'NativeAccessibilityManagerSpecJSI'
   30 | class JSI_EXPORT NativeAccessibilityManagerSpecJSI : public JavaTurboModule {
      |                  ^
/Users/ivanstashak/.gradle/caches/9.0.0/transforms/6033e476c477e3b700e1f47f2159c326/transformed/react-android-0.81.0-debug/prefab/modules/reactnative/include/FBReactNativeSpec.h:30:18: note: previous definition is here
   30 | class JSI_EXPORT NativeAccessibilityManagerSpecJSI : public JavaTurboModule {
      | 
In file included from /Users/ivanstashak/dev/foo/prysm-project/prysm/node_modules/react-native/ReactAndroid/cmake-utils/default-app-setup/OnLoad.cpp:38:
/Users/ivanstashak/dev/foo/prysm-project/prysm/android/app/build/generated/source/codegen/jni/./AppSpec.h:38:18: error: redefinition of 'NativeActionSheetManagerSpecJSI'
   38 | class JSI_EXPORT NativeActionSheetManagerSpecJSI : public JavaTurboModule {
      |                  ^
/Users/ivanstashak/.gradle/caches/9.0.0/transforms/6033e476c477e3b700e1f47f2159c326/transformed/react-android-0.81.0-debug/prefab/modules/reactnative/include/FBReactNativeSpec.h:38:18: note: previous definition is here
   38 | class JSI_EXPORT NativeActionSheetManagerSpecJSI : public JavaTurboModule {
      |

**Comment by istashak** [comment]
For those struggling with this, note that codegenConfig.libraries has basically been deprecated, or whatever. It'll work on iOS, but on Android it will not. You get all the name redefinition errors. 

Put all your native module specs in a central directory and ensure they're named Native<YourModule>, then have this in your package.json:

"codegenConfig": {
    "name": "<NameOfYourChoice>", // must have a name to work on iOS. Android auto-names it to AppSpec if name is missing
    "type": "modules",
    "jsSrcsDir": "<path_to_native_specs_dir",
    "android": {
      "packageName": "com.your.package"
    }
  },
