### ISSUE TITLE
[Docs] Add (iOS/Android/Both) icon to Components/APIs in navigation sidebar

### ISSUE THREAD

**Issue by richarddewit** [facebook/react-native#3407]

**Comment by cosmith** [comment]
@facebook-github-bot label Documentation

**Comment by grabbou** [comment]
Anyone would mind adding more details here? Was thinking about closing & implementing as it sounds like a quick thing to do, however it's hard for me to get an idea behind the title

**Comment by lacker** [comment]
I think the sidebar is already super cluttery. Let's punt on this - it's not too hard to just click through and check.
