### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'ReactCurrentActQueue$1.isBatchingLegacy')

### ISSUE THREAD

**Issue by dcr31000** [facebook/react-native#34079]
### Description

Since this morning, I cannot launch my app in debug mode on Android.

My app build successfully but, I got this in metro:
`
BUNDLE  ./index.js 

 LOG  Running "MyApp" with {"rootTag":1}
 ERROR  TypeError: undefined is not an object (evaluating 'ReactCurrentActQueue$1.isBatchingLegacy')
 ERROR  TypeError: undefined is not an object (evaluating 'ReactCurrentActQueue$1.isBatchingLegacy')
`

My app has a blank page.

This is my dependencies:
` "dependencies": {
    "@react-native-masked-view/masked-view": "^0.2.6",
    "@react-navigation/bottom-tabs": "^6.3.1",
    "@react-navigation/native": "^6.0.10",
    "@react-navigation/native-stack": "^6.6.2",
    "@react-navigation/stack": "^6.2.1",
    "react": "18.0.0",
    "react-native": "0.69.0",
    "react-native-gesture-handler": "^2.4.2",
    "react-native-pager-view": "^5.4.15",
    "react-native-safe-area-context": "^4.2.5",
    "react-native-screens": "^3.13.1",
    "react-native-svg": "^12.3.0",
    "react-native-tab-view": "^3.1.1",
    "react-native-vector-icons": "^9.1.0"
  },`

I tried to downgrade/updgrade some dependencies (react and react-native in particular) but nothing works.
Also tried to clear cache from metro, gradlew...

Thanks for your help :)

### Version

0.69.0

### Output of `npx react-native info`

System:
    OS: macOS 12.4
    CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
    Memory: 370.74 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.16.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.12 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7351085
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 16.0.1 - /Library/Java/JavaVirtualMachines/jdk-16.0.1.jdk/Contents/Home/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.0 => 0.69.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

npm i
npx react-native run-android

### Snack, code example, screenshot, or link to a repository

Maybe, use this configuration
`"dependencies": {
    "@react-native-masked-view/masked-view": "^0.2.6",
    "@react-navigation/bottom-tabs": "^6.3.1",
    "@react-navigation/native": "^6.0.10",
    "@react-navigation/native-stack": "^6.6.2",
    "@react-navigation/stack": "^6.2.1",
    "react": "18.0.0",
    "react-native": "0.69.0",
    "react-native-gesture-handler": "^2.4.2",
    "react-native-pager-view": "^5.4.15",
    "react-native-safe-area-context": "^4.2.5",
    "react-native-screens": "^3.13.1",
    "react-native-svg": "^12.3.0",
    "react-native-tab-view": "^3.1.1",
    "react-native-vector-icons": "^9.1.0"
  },`

**Comment by daveytolindo** [comment]
I have same issue recently but still can't find the solution for this.

**Comment by JEGardner** [comment]
This probably means that, for whatever reason, React 18 is not being used despite being set in the dependencies. For me, I had resolutions set up to use React 17 in the root package.json of my lerna monorepo.

**Comment by cortinico** [comment]
Is this happening on a fresh project?

> Maybe, use this configuration

Could you provide a proper repro?

**Comment by dcr31000** [comment]
Yes, on a fresh project.

I created a new one with this versions:
"react": "17.0.2",
"react-native": "0.68.2",
and transfers all my previous development (dependencies, screens etc). It's working nice.

I got this issue only with the last version of react and/or react native. It's probably on my side.

**Comment by ybass** [comment]
> Yes, on a fresh project.
> 
> I created a new one with this versions: "react": "17.0.2", "react-native": "0.68.2", and transfers all my previous development (dependencies, screens etc). It's working nice.
> 
> I got this issue only with the last version of react and/or react native. It's probably on my side.

Personally this should still be open. I have created a new project using the latest CLI and I am getting the same problem. It looks like having Expo 45 with "react-native":"^0.69.0" is causing the problem

**Comment by ybass** [comment]
@cortinico Was hoping to get some input unless preferable to start a new issue

**Comment by RamizWas** [comment]
so what exactly is the solution to this Error?

**Comment by gpsolarco** [comment]
Facing the same issue. Please help.

**Comment by RamizWas** [comment]
I have created a new project and it worked
would recommend trying that and going from there

**Comment by Ezulu920** [comment]
I think this is a version compatibility issue. When I had the same error, I downgraded to this RN version: "npm install react-native@0.68.2 --force". And it worked for me.

**Comment by spinoza1791** [comment]
> I think this is a version compatibility issue. When I had the same error, I downgraded to this RN version: "npm install react-native@0.68.2 --force". And it worked for me.

This worked for me when I received the error when upgrading to 0.69.1
    "react": "17.0.1",
    "react-native": "^0.69.1",

"@types/react-native": "^0.64.5",

**Comment by Ezulu920** [comment]
> > I think this is a version compatibility issue. When I had the same error, I downgraded to this RN version: "npm install react-native@0.68.2 --force". And it worked for me.
> 
> Thank you, your solution worked for me when I received the error after upgrading to 0.69.1 "react": "17.0.1", "react-native": "^0.69.1",
> 
> "@types/react-native": "^0.64.5",


I'm glad it worked for you.. Happy Learning :)

**Comment by Jaserto** [comment]
> > I think this is a version compatibility issue. When I had the same error, I downgraded to this RN version: "npm install react-native@0.68.2 --force". And it worked for me.
> 
> I had to do something more drastic, by upgrading react 17->18.2.0 and react-native 0.64->0.69.1, like so: npm install react@latest react-dom@latest --force npm audit fix --force
> 
> Changes to: "react": "^18.2.0", "react-dom": "^18.2.0", "react-native": "^0.69.1",
> 
> I was then able to run the native base typescript template

I'ts works for me, thanks a lot!

**Comment by sandeeprajbhar1985** [comment]
"react": "18.2.0", 

"react-native": "0.69.3",

Solved the issue for me

**Comment by jasson0802** [comment]
> I think this is a version compatibility issue. When I had the same error, I downgraded to this RN version: "npm install react-native@0.68.2 --force". And it worked for me.

This worked for me. Thanks a lot!

**Comment by nandorojo** [comment]
Adding this to my `package.json` (at the root of my monorepo) fixed it for me:

```json
{
  "resolutions": {
    "react": "18.0.0"
  }
}
```

No need to downgrade anything. You can also set that `react` version to any 18+ version you're using.

**Comment by zachdorcinville21** [comment]
Still having this issue after trying all of the above solutions. I'm running an Expo 47 bare workflow and I get this error in the terminal at runtime, which causes the app to be stuck at the splash screen.

**Comment by mateoguzmana** [comment]
> Adding this to my `package.json` (at the root of my monorepo) fixed it for me:
> 
> ```json
> {
>   "resolutions": {
>     "react": "18.0.0"
>   }
> }
> ```
> 
> No need to downgrade anything. You can also set that `react` version to any 18+ version you're using.

Upgrading `react` from 17.0.2 to 18.0.0 and adding it to the resolutions worked for me

**Comment by eapunkers** [comment]
Changes to:
"react": "^18.2.0",
"react-dom": "^18.2.0",
"react-native": "^0.69.1", it's work for me... thx a lot dude
