### ISSUE TITLE
setNativeProps does not work with text property on Text component

### ISSUE THREAD

**Issue by tradebulls** [facebook/react-native#34091]
### Description

Hi,

This thread is opened with reference to a closed issue - #22855.setNativeProps does not work with text property on Text component.

Currently RN doesn't support to give references to textview and only to TextInput, I cannot use setNativeProps on TextView. For eg if I want to update my textview on frequent basis then its not possible. As compared to a textview, an TextInput is an heavy component and when there are more than 50-60 TextInputs then it lags on both Android and IOS. However it doesn't with TextView.

Please check Steps to Reproduce for a solution.

These changes works perfectly in all React Native Version. Can this be included in default RN package. It would be a great feature.

### Version

All React Native Versions

### Output of `npx react-native info`

NA

### Steps to reproduce

https://github.com/tychota/bugSetNativePropsText

### Snack, code example, screenshot, or link to a repository

We have already tried the solution given by @tychota 

IOS Solution Link - https://github.com/facebook/react-native/issues/22855#issuecomment-451166536

Android Solution - 
Modify TextView changes in ReactBaseTextShadowNode.java file
@ReactProp(name = "text")
public void setText(@Nullable String text) {
  int length = this.getChildCount();
  for (int i = 0; i < length; i++) {
    ReactShadowNode child = this.getChildAt(i);
    if (child instanceof ReactRawTextShadowNode) {
      ((ReactRawTextShadowNode) child).setText(text);
    }
  }
  markUpdated();
}

**Comment by arish-panjwani** [comment]
Yes, even we use this feature in our application. It would be great if it is added in the default RN package.

**Comment by necolas** [comment]
setNativeProps will not be supported in the new "Fabric" architecture, and should be considered deprecated

https://reactnative.dev/docs/new-architecture-library-intro#migrating-off-setnativeprops
