### ISSUE TITLE
New props infrastructure is not portable

### ISSUE THREAD

**Issue by asklar** [facebook/react-native#34090]
### Description

This commit: https://github.com/facebook/react-native/commit/47280de85e62f33f0b97bc1ed7c83bc6ca0dc7d4

Introduced a compile-time string hashing mechanism (perhaps inspired by [this](https://github.com/microsoft/react-native-windows/pull/9841)) to do `switch` statements on string values.

However the resulting code uses clang-specific pragmas, which won't work with other compilers (e.g. MSVC).
This breaks ingestion of RN core into React Native Windows.

![image](https://user-images.githubusercontent.com/22989529/176317233-4f5b2b02-53fe-4387-8091-ef41ec5bdfbe.png)

### Version

main

### Output of `npx react-native info`

n/a

### Steps to reproduce

n/a

### Snack, code example, screenshot, or link to a repository

n/a

**Comment by chiaramooney** [comment]
Pipeline showing break in RNW: https://dev.azure.com/ms/react-native-windows/_build/results?buildId=323774&view=results
Broken Files: Props.cpp and BaseTextProps.cpp.
Pragma Code: https://github.com/facebook/react-native/blob/577582e2303baa0ffce15e95cc406cf32cb5ceaa/ReactCommon/react/renderer/core/PropsMacros.h#L17-L25

**Comment by asklar** [comment]
Cc @JoshuaGross

**Comment by lyahdav** [comment]
Looks like it should be wrapped with `#if __clang__`. Example: https://github.com/facebook/react-native/blob/8bd3edec88148d0ab1f225d2119435681fbbba33/ReactCommon/cxxreact/ReactMarker.cpp#L14

**Comment by lyahdav** [comment]
@asklar do you know if in React Native Windows we'll get a warning or error if we had this code as-is without the pragma? The issue with Clang was that this code could introduce variables `len` and `hash` which could shadow variables with the same name in an outer scope. If React Native Windows has MSVC configured to produce an error for this situation we'll have to add the MSVC pragma equivalent. If so, do you know what that is?

**Comment by asklar** [comment]
if we remove the pragma, I imagine msvc might produce a warning if the right warning level flag is set, perhaps @chiaramooney can try it.
is there a reason why we need the extra variable? why not just say:
```cpp
#define CONSTEXPR_RAW_PROPS_KEY_HASH(s)    (folly::hash::fnv32_buf(s, sizeof(s) - 1))
```

is the problem that folly's fnv32_buf functions aren't constexpr? take a look at the PR I made a reference to originally and see if that helps, that does everything in constexpr without any funky macros

**Comment by JoshuaGross** [comment]
@asklar  I should be able to change the macro into a `consteval` function to enforce its evaluation at compile-time. Let me know if there are any concerns with doing that for MSVC. It looks like you're using consteval in https://github.com/microsoft/react-native-windows/pull/9841/files as well (I had not seen this PR previously) so maybe that's an acceptable solution here; I'll give it a shot.

**Comment by JoshuaGross** [comment]
Yeah we're not on C++20 yet either, so I'll have to find something that works with just constexpr. I'll play around a little bit. If y'all get to it faster, let me know if MSVC is fine with just removing the pragmas.

**Comment by JoshuaGross** [comment]
@asklar What version of C++ are you on? Can I assume at least C++17?

**Comment by asklar** [comment]
yes we're on cpp17

**Comment by JoshuaGross** [comment]
I have a local diff we can try out. @asklar want to see if this works for you?

```
// We need to use clang pragmas inside of a macro below,
// so we need to pull out the "if" statement here.
#if __clang__
#define CLANG_PRAGMA(s) _Pragma(s)
#else
#define CLANG_PRAGMA(s)
#endif

// Get hash at compile-time. sizeof(str) - 1 == strlen
#define CONSTEXPR_RAW_PROPS_KEY_HASH(s)                   \
  ({                                                      \
    CLANG_PRAGMA("clang diagnostic push")                 \
    CLANG_PRAGMA("clang diagnostic ignored \"-Wshadow\"") \
    constexpr RawPropsPropNameHash hash =                 \
        folly::hash::fnv32_buf(s, sizeof(s) - 1);         \
    return hash;                                          \
    CLANG_PRAGMA("clang diagnostic pop")                  \
  })
```

I'll have more commentary if/when I land the actual diff. I'm still trying to avoid doing this the "proper" way without macros because it results in 10x as much code and is IMO a lot less readable, though that's highly subjective. If this compiles on MSVC let's do this; if not, is there a scoped way to ignore shadowing warnings in MSVC?

**Comment by JoshuaGross** [comment]
https://github.com/facebook/react-native/commit/d1d11c7639246ac759a9d1eb496f6658319b2070

**Comment by JoshuaGross** [comment]
@asklar please reopen if this is still an issue on your end

**Comment by chiaramooney** [comment]
@JoshuaGross Error still present following attempt to integrate 7/4 nightly build. cc @asklar

**Comment by lyahdav** [comment]
@chiaramooney can you confirm it's coming from the same place that @JoshuaGross modified in https://github.com/facebook/react-native/commit/d1d11c7639246ac759a9d1eb496f6658319b2070? If so, can you see if somehow `__clang__` is defined in MSVC builds?

**Comment by chiaramooney** [comment]
Yes same place. @asklar Off the top of your head do you know if __clang__ is defined in MSVC builds, otherwise I can investigate?

**Comment by asklar** [comment]
Looks like I don't have permissions to reopen, @JoshuaGross mind reopening this?

**Comment by lyahdav** [comment]
> `__clang__` is not defined for MSVC: <img alt="image" width="1509" src="https://user-images.githubusercontent.com/22989529/178371010-86f64091-4385-4599-beb3-628ea09f6239.png">

@asklar so if `__clang__` is not defined, I'm confused how it's running code under `#if __clang__`. Can we get a link to the full build output and can we confirm that the RNW build included https://github.com/facebook/react-native/commit/d1d11c7639246ac759a9d1eb496f6658319b2070? Maybe it's coming from another file that needs a similar fix?

**Comment by chiaramooney** [comment]
@lyahdav https://dev.azure.com/ms/react-native-windows/_build/results?buildId=328217&view=results

**Comment by asklar** [comment]
it looks like the syntax `case ({something}):` is not valid for MSVC:
https://godbolt.org/z/P4qh7rKrf

**Comment by asklar** [comment]
ok, looks like that syntax is a language extension in GCC (and clang implements it too) but it is not standard C++:

https://gcc.gnu.org/onlinedocs/gcc/Statement-Exprs.html

@JoshuaGross could we write this in a way that is portable? maybe move the "statement expression" inside of a `#define` instead of just the pragma

**Comment by asklar** [comment]
an alternative approach is to use an immediate lambda instead of a statement expression:

```cpp
case [&]{ /* ... */ return something; }(): /* ... */
```

**Comment by lyahdav** [comment]
FYI @JoshuaGross is OOO until next week. If anyone from the MSFT side wants to put up a PR with a fix sooner, I can find someone on our side to review

**Comment by asklar** [comment]
@chiaramooney can you apply the change and send a PR to here?

**Comment by chiaramooney** [comment]
Trying 

```
#define CONSTEXPR_RAW_PROPS_KEY_HASH(s)                   \
  []{                                                     \
    CLANG_PRAGMA("clang diagnostic push")                 \
    CLANG_PRAGMA("clang diagnostic ignored \"-Wshadow\"") \
    return folly::hash::fnv32_buf(s, sizeof(s) - 1);      \
    CLANG_PRAGMA("clang diagnostic pop")                  \
    }()
```

still results in the same syntax errors as `case ({something}):` @rozele might be looking into it to see what's wrong

**Comment by JoshuaGross** [comment]
@asklar @chiaramooney I'm back from leave but not sure when I'll be able to prioritize this. The only hard requirement/goal from my end is that these blocks continue to be compile-time evaluated on iOS and Android; it would be nice if that were the case for all platforms, but there might not be a portable way of doing it. Can one of you iterate on this until it compiles for MSVC? And then we can make sure the solution is acceptable for iOS/Android as well. I don't normally compile using MSVC so I'd prefer not to drive the solution.

**Comment by chiaramooney** [comment]
Alright I believe we have a fix. Both BaseTextProps.cpp and PropsMacros.h need edits. New versions of files can be found here: 
https://github.com/microsoft/react-native-windows/blob/daf914bbb2d7ad7bc20cdac022818d0b65b3306b/vnext/ReactCommon/TEMP_UntilReactCommonUpdate/react/renderer/components/text/BaseTextProps.cpp

https://github.com/microsoft/react-native-windows/blob/daf914bbb2d7ad7bc20cdac022818d0b65b3306b/vnext/ReactCommon/TEMP_UntilReactCommonUpdate/react/renderer/core/PropsMacros.h

These changes use the approach of replacing all ({something}) syntax with lambda expressions in both the GET_FIELD_VALUE and CONSTEXPR_RAW_PROPS_KEY_HASH(s) macros and adding a semicolon to the end of the GET_FIELD_VALUE macro. @JoshuaGross @lyahdav

**Comment by chiaramooney** [comment]
@JoshuaGross @lyahdav If you have a moment to validate that the changes also work on your end. I can put out a PR.

**Comment by lyahdav** [comment]
@chiaramooney I'd say just put out a PR on this repo for it, and then we'll see if builds successfully in our CI.

**Comment by kelset** [comment]
@chiaramooney I noticed that your PR landed - do you need this in 0.70?

**Comment by lyahdav** [comment]
The PR was unlanded. Looks like it caused some regression. I'm awaiting some clarification internally on the status.

**Comment by lyahdav** [comment]
Looks like a fix for the regression is landing. The fix should work on MSVC, but we'll need someone from the MSFT side to verify. You can monitor for commits touching BaseTextProps.cpp to see when it's landed.

**Comment by kelset** [comment]
ok so let's delay this to the next RC - we'll do RC2 without this, and you all can let me know if this will need to be in RC3

**Comment by asklar** [comment]
This issue is blocking ingestion into RNW, so if we can get this sorted out sooner than later (in rc1) that'd be great.

**Comment by asklar** [comment]
@lyahdav can you reopen this issue if it still needs to be [re-]merged?

**Comment by lyahdav** [comment]
Looks like the fix has landed: https://github.com/facebook/react-native/commit/a142a784733bc7e37042a7e4d3cdbeff99aa1fa7. @rshest didn't test this on MSVC but it should work in theory. If there's an issue you can let us know here.
