### ISSUE TITLE
link and unlink commands have been removed in the favour of autolinking

### ISSUE THREAD

**Issue by zanyar3** [facebook/react-native#34095]
### Description

I want add custom fonts for react native project.
after add fonts and config files need link project  for  add font for Android and iOS respectively.

But when run `npx react-native link` have a error  `Unrecognized command "link".`

### Version

0.69

### Output of `npx react-native info`

```
System:
    OS: Windows 10 10.0.19042
    CPU: (4) x64 Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz
    Memory: 789.02 MB / 7.88 GB
  Binaries:
    Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: AI-212.5712.43.2112.8512546
    Visual Studio: 17.2.32602.215 (Visual Studio Community 2022)
  Languages:
    Java: 11.0.13
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0
    react-native: 0.69.0 => 0.69.0
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

- Added fonts for assets/fonts directory
- Created `react-native.config.js` in root project folder
- Added the following code inside `module.exports`
```
module.exports = {
    project: {
        ios:{},
        android:{}
    },
    assets:['./assets/fonts/'],
}
```

- Run `npx react-native link` 

### Snack, code example, screenshot, or link to a repository

```
> npm react-native link
  Unknown command: "react-native"

  To see a list of supported npm commands, run:
  npm help
```

**Comment by Gitarcitano** [comment]
@zanyar3 
I had the same problem yesterday, but I got around it by manually installing the font.

To manually install on Android, you need to drop the files on this folder:
`<yourApp>/android/app/src/main/assets/fonts`

create a file in `<yourApp>/android/app/src/main/java/com/<YourAppPackageName>/components/<NameThatYouWant>.java`

```java
package com.<YourAppPackageName>.components;

import android.content.Context;
import android.graphics.Typeface;
import androidx.appcompat.widget.AppCompatTextView;

import android.util.AttributeSet;

public class <NameThatYouWant> extends AppCompatTextView {

    public <NameThatYouWant>(Context context, AttributeSet attrs, int defStyle) {
        super(context, attrs, defStyle);
        init();
    }

    public <NameThatYouWant>(Context context, AttributeSet attrs) {
        super(context, attrs);
        init();
    }

    public <NameThatYouWant>(Context context) {
        super(context);
        init();
    }

    public void init() {
        Typeface tf = Typeface.createFromAsset(getContext().getAssets(), "fonts/<FontFileName>.ttf");
        setTypeface(tf ,Typeface.NORMAL);

    }
}
```


And on iOS you must follow this guide: https://developer.apple.com/documentation/uikit/text_display_and_fonts/adding_a_custom_font_to_your_app

**Comment by cortinico** [comment]
> But when run `npx react-native link` have a error `Unrecognized command "link".`

This is a question/issue for the CLI which lives here:
https://github.com/react-native-community/cli

**Comment by pogakuofie** [comment]
> @zanyar3 I had the same problem yesterday, but I got around it by manually installing the font.
> 
> To manually install on Android, you need to drop the files on this folder: `<yourApp>/android/app/src/main/assets/fonts`
> 
> create a file in `<yourApp>/android/app/src/main/java/com/<YourAppPackageName>/components/<NameThatYouWant>.java`
> 
> ```java
> package com.<YourAppPackageName>.components;
> 
> import android.content.Context;
> import android.graphics.Typeface;
> import androidx.appcompat.widget.AppCompatTextView;
> 
> import android.util.AttributeSet;
> 
> public class <NameThatYouWant> extends AppCompatTextView {
> 
>     public <NameThatYouWant>(Context context, AttributeSet attrs, int defStyle) {
>         super(context, attrs, defStyle);
>         init();
>     }
> 
>     public <NameThatYouWant>(Context context, AttributeSet attrs) {
>         super(context, attrs);
>         init();
>     }
> 
>     public <NameThatYouWant>(Context context) {
>         super(context);
>         init();
>     }
> 
>     public void init() {
>         Typeface tf = Typeface.createFromAsset(getContext().getAssets(), "fonts/<FontFileName>.ttf");
>         setTypeface(tf ,Typeface.NORMAL);
> 
>     }
> }
> ```
> 
> And on iOS you must follow this guide: https://developer.apple.com/documentation/uikit/text_display_and_fonts/adding_a_custom_font_to_your_app

Thanks this worked for me.

**Comment by zanyar3** [comment]
> Just use ` npx react-native-asset`

only supports font files, this tool supports all assets ?

What about other library for link native code ?

**Comment by AshirbadGudu** [comment]
> Just use ` npx react-native-asset`

Yes, this is working for in react-native 0.69

**Comment by iamyahia** [comment]
کاکە زانیار، اسلام علیکم
منیش هەمان ێشەم هەبوو بەڵام ئەم کێشەیە چارەسەر ئەبێت بەم هەنگاوانە:
١- فالێک بکەوە بە ناوی ـ(react-native.config.js)ـ
٢- ئەم کۆدەی تیا بنەسەرەوە: 
module.exports = {
    project: {
        ios:{},
        android:{}
    },
    assets:['./assets/fonts/'],
}
٣- فایلەکە سەیڤ کە، و ڕەنی ڕیئاکت لە کۆماند ڵاین ریستارت بکەوە، بەم کۆدە:
npx run start
٤- دوبارە ئەپڵیکەیشنەکە بویڵد کەوە لە ئامێرەکەت:
npx run android/ios
بە هیوای سوود

**Comment by Aszurar** [comment]
> Just use ` npx react-native-asset`

Wow, thanks, thank you very much!!!, my colleagues and I have been looking into this for about 2 weeks now!

**Comment by pankti-0627** [comment]
this works for android but on iOS device getting an error of "unrecognized font family". anyone can help please?

**Comment by cesarhilario** [comment]
> this works for android but on iOS device getting an error of "unrecognized font family". anyone can help please?

same here

**Comment by fkazemi5236** [comment]
in RN +0.69 sometimes when you are trying to add your custom fonts, you may saw this error :

**`'react-native-asset' is not recognized as an internal or external command`**

If you get this error first install` yarn add -D react-native-asset` as a dev dependency then run `npx react-native-asset`

it works for me ☺❤

**Comment by serge-psllc** [comment]
Doesn't work for me at all:
`npx react-native-asset        
node:internal/modules/cjs/loader:958
  throw err;
  ^

Error: Cannot find module '/Users/sergevanneck/dev/CFSS/room-scheduler/react-native-room-scheduler/react-native.config.js'
Require stack:
- /Users/sergevanneck/.npm/_npx/545c366a5ae830a2/node_modules/react-native-asset/lib/cli.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:955:15)
    at Module._load (node:internal/modules/cjs/loader:803:27)
    at Module.require (node:internal/modules/cjs/loader:1021:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/Users/sergevanneck/.npm/_npx/545c366a5ae830a2/node_modules/react-native-asset/lib/cli.js:45:27)
    at Module._compile (node:internal/modules/cjs/loader:1119:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at Module.load (node:internal/modules/cjs/loader:997:32)
    at Module._load (node:internal/modules/cjs/loader:838:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/sergevanneck/.npm/_npx/545c366a5ae830a2/node_modules/react-native-asset/lib/cli.js'
  ]
}

`

I don't use yarn so I tried with npm:

`% npm install react-native-asset --save-dev
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: RoomScheduler@0.0.1
npm ERR! Found: react-native@0.70.1
npm ERR! node_modules/react-native
npm ERR!   react-native@"0.70.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react-native@"^0.60.0" from react-native-asset@2.0.1
npm ERR! node_modules/react-native-asset
npm ERR!   dev react-native-asset@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/sergevanneck/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sergevanneck/.npm/_logs/2022-09-30T16_45_59_195Z-debug-0.log
`

With the Java code example, what am I supposed to use for <NameThatYouWant>?

**Comment by devuco** [comment]
> Doesn't work for me at all:
> 
> ```
> % npx react-native-asset        
> node:internal/modules/cjs/loader:958
>   throw err;
>   ^
> 
> Error: Cannot find module '/Users/my-app-directory/react-native.config.js'
> Require stack:
> - /Users/sergevanneck/.npm/_npx/545c366a5ae830a2/node_modules/react-native-asset/lib/cli.js
>     at Module._resolveFilename (node:internal/modules/cjs/loader:955:15)
>     at Module._load (node:internal/modules/cjs/loader:803:27)
>     at Module.require (node:internal/modules/cjs/loader:1021:19)
>     at require (node:internal/modules/cjs/helpers:103:18)
>     at Object.<anonymous> (/Users/sergevanneck/.npm/_npx/545c366a5ae830a2/node_modules/react-native-asset/lib/cli.js:45:27)
>     at Module._compile (node:internal/modules/cjs/loader:1119:14)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
>     at Module.load (node:internal/modules/cjs/loader:997:32)
>     at Module._load (node:internal/modules/cjs/loader:838:12)
>     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/Users/sergevanneck/.npm/_npx/545c366a5ae830a2/node_modules/react-native-asset/lib/cli.js'
>   ]
> }
> ```
> 
> I don't use yarn so I tried with npm:
> 
> ```
> % npm install react-native-asset --save-dev
> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE unable to resolve dependency tree
> npm ERR! 
> npm ERR! While resolving: RoomScheduler@0.0.1
> npm ERR! Found: react-native@0.70.1
> npm ERR! node_modules/react-native
> npm ERR!   react-native@"0.70.1" from the root project
> npm ERR! 
> npm ERR! Could not resolve dependency:
> npm ERR! peer react-native@"^0.60.0" from react-native-asset@2.0.1
> npm ERR! node_modules/react-native-asset
> npm ERR!   dev react-native-asset@"*" from the root project
> npm ERR! 
> npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force, or --legacy-peer-deps
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
> npm ERR! 
> npm ERR! See /Users/sergevanneck/.npm/eresolve-report.txt for a full report.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/sergevanneck/.npm/_logs/2022-09-30T16_45_59_195Z-debug-0.log
> ```
> 
> With the Java code example, what am I supposed to use for  "NameThatYouWant"?

Did you create the react-native.config.js?

**Comment by usfslk** [comment]
This is ridiculous

**Comment by sapsharma** [comment]
PS D:\Adminpanel> react-native link react-native-image-picker
error: unknown command 'link'

not wrking
