### ISSUE TITLE
React Native is not compatible with JDK 18

### ISSUE THREAD

**Issue by cortinico** [facebook/react-native#34103]
### Description

I'm opening this issue for the sake of visibility/transparency.

We received multiple reports of users on JDK 18 not being able to build app for Android using the **New Architecture**

I did a small investigation on the JDK 18 support.

There are a couple of things to note here:
1. Gradle don't formally support JDK 18 (https://docs.gradle.org/current/userguide/compatibility.html) as of today. The first version supporting it will be Gradle 7.5 (currently in RC).
2. I've tried the RC, but it still crashes. I believe the problem might be somewhere in the JDK standard libraries or in how we use it. There seems to be a memory leak somewhere. It's curious that this happens only on JDK 18 (and not on 17).
3. It would be interesting to try this on either a non-zulu or non-aarch64 jdk to understand if the problem is in the JDK distribution.
That's the JDK I was using:
```
openjdk version "18.0.1" 2022-04-19
OpenJDK Runtime Environment Zulu18.30+11-CA (build 18.0.1+10)
OpenJDK 64-Bit Server VM Zulu18.30+11-CA (build 18.0.1+10, mixed mode, sharing)
```
4. Having a heapdump of the crash would also be helpful. As the app instacrash, that's a bit tricky to do. I haven't managed to do this yet.

### Version

0.68.0

### Stacktrace

```
Error reporting crash
java.lang.OutOfMemoryError: Failed to allocate a 320848968 byte allocation with 4742061 free bytes and 187MB until OOM, target footprint 9582429, growth limit 201326592
	at java.util.Arrays.copyOf(Arrays.java:3257)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
	at java.lang.StringBuilder.append(StringBuilder.java:137)
	at java.lang.Throwable.toString(Throwable.java:493)
	at java.lang.String.valueOf(String.java:2924)
	at java.io.PrintWriter.println(PrintWriter.java:754)
	at java.lang.Throwable$WrappedPrintWriter.println(Throwable.java:778)
	at java.lang.Throwable.printStackTrace(Throwable.java:667)
	at java.lang.Throwable.printStackTrace(Throwable.java:735)
	at android.app.ApplicationErrorReport$CrashInfo.<init>(ApplicationErrorReport.java:354)
	at android.app.ApplicationErrorReport$ParcelableCrashInfo.<init>(ApplicationErrorReport.java:484)
	at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:157)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
	at java.lang.Thread.dispatchUncaughtException(Thread.java:2200)asdf
```

**Comment by leotm** [comment]
as an aside also spotted CPU/memory leak w Gradle 7.6 nightly bout month ago in CI w JDK 18
- https://github.com/leotm/react-native-template-new-architecture/issues/628

**Comment by leotm** [comment]
seems fine w AGP 7.2.1 (AGP 7.2.0 still causing the runtime error)
- https://github.com/leotm/react-native-template-new-architecture/issues/746

unsure which [commit](https://android.googlesource.com/platform/tools/base/+log) yet, can still check non-aarch64 if needed
so think can pick it into RN 0.69.x when appropriate (noting low priority)

**Comment by mikehardy** [comment]
still requires gradle 7.5+ though right? Which just released like, yesterday?

**Comment by leotm** [comment]
good point i don't think quite requires gradle 7.5+
7.4.2 debug/release builds/runtime still fine for me on Zulu18
(could still make sure on non-zulu's and aarch32's)

**Comment by leotm** [comment]
but yh now looks time to bump to 7.5 stable for official/full JDK 18 support (by full, not jus AGP bump to 7.2.1)
then provided the 20ish ci tests pass 🤞

> Gradle now checks the Adoptium API first when downloading JDKs, rather than only using the legacy AdoptOpenJDK API. This allows downloading the new JDK 18 releases, which are not available via AdoptOpenJDK, while still maintaining the ability to download versions that are no longer supported by Adoptium, such as JDK 9-10 and 12-16.

https://docs.gradle.org/7.5/release-notes.html#jvm-toolchains-improvements

again i'm not from android bg jus making sense of things
i'm going to check/run locally soon, debug/release builds looking good
- https://github.com/leotm/react-native-template-new-architecture/pull/775

**Comment by cortinico** [comment]
> still requires gradle 7.5+ though right? Which just released like, yesterday?

Just for sanity check: I'd like to bump Gradle to 7.5 to make sure the next version is JDK 18 compatible. Feel free to send a PR over and ping me there for a review :)

**Comment by varemenos** [comment]
Sorry for reviving this thread but is there no way to setup and utilize [gradle toolchains](https://docs.gradle.org/current/userguide/toolchains.html)?

My knowledge of Android and gradle is very limited but based on what little I understand, this should make it so gradle is using a specific version of Java specified in the config and therefore not have an expectation from the user to download and set up the "right" version of Java locally, right?

**Comment by muhammadalizkhan** [comment]
I am Using java 19+ with Gradle 7.6 Facing Same Issue

**Comment by cortinico** [comment]
The recommended version is Java 17
