### ISSUE TITLE
React-bridging wrong paths?

### ISSUE THREAD

**Issue by mm-webx** [facebook/react-native#34102]
### Description

![CleanShot 2022-06-29 at 18 44 51](https://user-images.githubusercontent.com/34196239/176491340-de578076-f6cc-420b-8cd5-b97a9348e007.png)
Wrong React-bridging directories structure:
`xxx/ios/Pods/Headers/Public/React-bridging/react/bridging/react/bridging/LongLivedObject.h`
should be:
`xxx/ios/Pods/Headers/Public/React-bridging/react/bridging/LongLivedObject.h`

So `xxx/node_modules/react-native/ReactCommon/react/nativemodule/core/ReactCommon/TurboModuleUtils.h` has wrong imports like 
```
#include <react/bridging/CallbackWrapper.h>
#include <react/bridging/LongLivedObject.h>
```

### Version

0.69.1

### Output of `npx react-native info`

warn Package react-native-appsflyer has been ignored because it contains invalid configuration. Reason: "dependency.platforms.ios.podspecPath" is not allowed
warn Package @svgr/webpack has been ignored because it contains invalid configuration. Reason: Package subpath './package.json' is not defined by "exports" in /Users/webx/_WEBX/gigaverse-mobile/node_modules/@svgr/webpack/package.json
info Fetching system and libraries information...
System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1
    Memory: 102.55 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v16.13.1/bin/npm
    Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /opt/homebrew/opt/openjdk@11/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^18.2.0 => 18.2.0 
    react-native: ^0.69.1 => 0.69.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

0.69.1 react native and for example install `react-native-vision-camera`

### Snack, code example, screenshot, or link to a repository

![CleanShot 2022-06-29 at 18 51 42](https://user-images.githubusercontent.com/34196239/176492449-fb76338a-02cd-45a7-887a-fe0828a5fa57.png)
![CleanShot 2022-06-29 at 18 52 03](https://user-images.githubusercontent.com/34196239/176492496-912b165a-a8b6-4fa5-ad32-877a16a772e7.png)
![CleanShot 2022-06-29 at 18 52 13](https://user-images.githubusercontent.com/34196239/176492521-e3a33756-f938-454f-b98b-85283040390b.png)

**Comment by rahulYaper** [comment]
Facing the same issue after upgrading to 0.69.1
<img width="273" alt="Screen Shot 2022-06-30 at 4 56 43 PM" src="https://user-images.githubusercontent.com/71073471/176666207-1df8dfda-379c-42f0-be95-67c91207ba0e.png">

**Comment by marquina-abreu** [comment]
Same issue

**Comment by karatekid430** [comment]
Same

**Comment by raufpratama** [comment]
same issue

**Comment by mm-webx** [comment]
Its possible to copy files to correct path, but its not long term solution

**Comment by mm-webx** [comment]
I think can be related to this: https://github.com/facebook/react-native/commit/f97c6a5b498eec95e99a02c7842cb2ae160cd6cd

**Comment by s5z6** [comment]
Changing header_dir to dot helps:
```diff
diff --git a/node_modules/react-native/ReactCommon/React-bridging.podspec b/node_modules/react-native/ReactCommon/React-bridging.podspec
index 5255c13..52a8eb0 100644
--- a/node_modules/react-native/ReactCommon/React-bridging.podspec
+++ b/node_modules/react-native/ReactCommon/React-bridging.podspec
@@ -30,7 +30,7 @@ Pod::Spec.new do |s|
   s.source                 = source
   s.source_files           = "react/bridging/**/*.{cpp,h}"
   s.exclude_files          = "react/bridging/tests"
-  s.header_dir             = "react/bridging"
+  s.header_dir             = "."
   s.header_mappings_dir    = "."
   s.compiler_flags         = folly_compiler_flags
   s.pod_target_xcconfig    = { "HEADER_SEARCH_PATHS" => "\"$(PODS_ROOT)/RCT-Folly\"",

```

**Comment by OlleThunbergDevoteam** [comment]
Same issue here

**Comment by rocket13011** [comment]
same issue here too.

**Comment by kierancrown** [comment]
> Changing header_dir to dot helps:
> 
> ```diff
> diff --git a/node_modules/react-native/ReactCommon/React-bridging.podspec b/node_modules/react-native/ReactCommon/React-bridging.podspec
> index 5255c13..52a8eb0 100644
> --- a/node_modules/react-native/ReactCommon/React-bridging.podspec
> +++ b/node_modules/react-native/ReactCommon/React-bridging.podspec
> @@ -30,7 +30,7 @@ Pod::Spec.new do |s|
>    s.source                 = source
>    s.source_files           = "react/bridging/**/*.{cpp,h}"
>    s.exclude_files          = "react/bridging/tests"
> -  s.header_dir             = "react/bridging"
> +  s.header_dir             = "."
>    s.header_mappings_dir    = "."
>    s.compiler_flags         = folly_compiler_flags
>    s.pod_target_xcconfig    = { "HEADER_SEARCH_PATHS" => "\"$(PODS_ROOT)/RCT-Folly\"",
> ```

After doing this I've not got a new error:
```
Use of undeclared identifier 'jsi'; did you mean 'facebook::jsi'?
```
![Screenshot 2022-07-06 at 16 02 00](https://user-images.githubusercontent.com/4990483/177582280-8bf0d9e5-8147-4898-bac9-3d91cfb45327.png)

**Comment by devinkg** [comment]
Same issue

**Comment by VanDinh18** [comment]
i added patch but not work
System:
    OS: macOS 12.3.1
    CPU: (8) x64 Apple M1
    Memory: 34.13 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.19 - ~/Documents/Adamo/keiyo-club-app/node_modules/.bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
    Watchman: 2022.05.16.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 29, 30, 31, 32
      Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0
      System Images: android-30 | Intel x86 Atom_64, android-31 | Google Play ARM 64 v8a, android-32 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.69.1 => 0.69.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by Kudo** [comment]
this may fix the header not found error:

```diff
--- a/ios/Podfile
+++ b/ios/Podfile
@@ -33,5 +33,14 @@ target 'RN069' do
   post_install do |installer|
     react_native_post_install(installer)
     __apply_Xcode_12_5_M1_post_install_workaround(installer)
+
+   installer.pods_project.targets.each do |target|
+     target.build_configurations.each do |config|
+       config.build_settings['HEADER_SEARCH_PATHS'] ||= '$(inherited) '
+       config.build_settings['HEADER_SEARCH_PATHS'] << '"$(PODS_ROOT)/Headers/Private/React-bridging/react/bridging" '
+       config.build_settings['HEADER_SEARCH_PATHS'] << '"$(PODS_CONFIGURATION_BUILD_DIR)/React-bridging/react_bridging.framework/Headers" '
+     end
+   end
+
   end
 end
```

if that works fine, maybe we could propose the fix to the [`react_native_post_install`](https://github.com/facebook/react-native/blob/23accbf58d2fa03ad020e07f00012a32609c7218/scripts/react_native_pods.rb#L287-L302) helper.

for `jsi::` -> `facebook::jsi::` namespace change, it is from 009d80bf5a55dd74be448960b1344ac7599c6bae and it's a better practice IMO even though that requires third party modules to fix the breaking code.

**Comment by nica0012** [comment]
How do you add patch? I am having this error in xcode. Been waiting for new release but I think I will try this to get things going.

**Comment by kierancrown** [comment]
> 

Create a `patches` directory in the root of your project and add your patches making sure they end in the `.patch` extension. Then install [patch-package](https://www.npmjs.com/package/patch-package) and follow the setup guide.

**Comment by Polyrion** [comment]
Hi I got this error too on react 0.69.0 and 0.69.1, the fact that I'm creating a bridge and turn on !use_framework to make a wrapper for MapBox Navigation SDK trough me that CallBackWrapper is not found and I tried any solution proposed and still got this error.

Did someone found how to fix this ?

**Comment by kierancrown** [comment]
> Hi I got this error too on react 0.69.0 and 0.69.1, the fact that I'm creating a bridge and turn on !use_framework to make a wrapper for MapBox Navigation SDK trow me that CallBackWrapper is not found and I tried any solution proposed and still got this error.
> 
> Did someone found how to fix this ?

Apply the mentioned patches above. Fixed for me in 0.69.1

**Comment by Polyrion** [comment]
@kierancrown you're talking about Kudo proposition with Podfile ? cause I tried too and didn't work or can you just tell me which one work for you.

**Comment by kierancrown** [comment]
> @kierancrown you're talking about Kudo proposition with Podfile ? cause I tried too and didn't work or can you just tell me which one work for you.

Sure. Create a file in your root directory called `patches/react-native+0.69.1.patch` with contents

```
diff --git a/node_modules/react-native/ReactCommon/React-bridging.podspec b/node_modules/react-native/ReactCommon/React-bridging.podspec
index 5255c13..52a8eb0 100644
--- a/node_modules/react-native/ReactCommon/React-bridging.podspec
+++ b/node_modules/react-native/ReactCommon/React-bridging.podspec
@@ -30,7 +30,7 @@ Pod::Spec.new do |s|
   s.source                  = source
   s.source_files           = "react/bridging/**/*.{cpp,h}"
   s.exclude_files          = "react/bridging/tests"
-  s.header_dir             = "react/bridging"
+  s.header_dir             = "."
   s.header_mappings_dir    = "."
   s.compiler_flags         = folly_compiler_flags
   s.pod_target_xcconfig    = { "HEADER_SEARCH_PATHS" => "\"$(PODS_ROOT)/RCT-Folly\"",
```

**Comment by Polyrion** [comment]
@kierancrown :/ still got the issue
![Capture d’écran 2022-07-15 à 16 25 35](https://user-images.githubusercontent.com/69394749/179243676-012583ed-5c2b-4266-bfc3-00c4e3ae427d.png)

there is my patch file that got applied successfully : 
```
diff --git a/node_modules/react-native/ReactCommon/React-bridging.podspec b/node_modules/react-native/ReactCommon/React-bridging.podspec
index 5255c13..52a8eb0 100644
--- a/node_modules/react-native/ReactCommon/React-bridging.podspec
+++ b/node_modules/react-native/ReactCommon/React-bridging.podspec
@@ -30,7 +30,7 @@ Pod::Spec.new do |s|
   s.source                 = source
   s.source_files           = "react/bridging/**/*.{cpp,h}"
   s.exclude_files          = "react/bridging/tests"
-  s.header_dir             = "react/bridging"
+  s.header_dir             = "."
   s.header_mappings_dir    = "."
   s.compiler_flags         = folly_compiler_flags
   s.pod_target_xcconfig    = { "HEADER_SEARCH_PATHS" => "\"$(PODS_ROOT)/RCT-Folly\"",
``` 

Podfile : 
```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.4'
install! 'cocoapods', :deterministic_uuids => false

use_frameworks!
target 'mapnav' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-LocationAccuracy', :path => "#{permissions_path}/LocationAccuracy"
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"

  # Pods for Mapbox navigation
  pod 'MapboxNavigation', '~> 2.6'

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'mapnavTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  if !ENV['CI']
    # local configuration
    # use_flipper!()
    post_install do |installer|
      installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings["ONLY_ACTIVE_ARCH"] = "NO"
        end
      end
      react_native_post_install(installer)
      __apply_Xcode_12_5_M1_post_install_workaround(installer) if defined?(__apply_Xcode_12_5_M1_post_install_workaround)
    end
  else
    # CI configuration
    post_install do |installer|
      react_native_post_install(installer)
      __apply_Xcode_12_5_M1_post_install_workaround(installer) if defined?(__apply_Xcode_12_5_M1_post_install_workaround)
    end
  end
end
```

Pod install was successful
```
Installing DoubleConversion (1.1.6)
Installing FBLazyVector (0.69.1)
Installing FBReactNativeSpec (0.69.1)
Installing MapboxCommon (22.0.0)
Installing MapboxCoreMaps (10.6.1)
Installing MapboxCoreNavigation (2.6.0)
Installing MapboxDirections (2.6.0)
Installing MapboxMaps (10.6.1)
Installing MapboxMobileEvents (1.0.8)
Installing MapboxNavigation (2.6.0)
Installing MapboxNavigationNative (106.0.0)
Installing MapboxSpeech (2.0.1)
Installing Permission-Camera (3.5.0)
Installing Permission-LocationAccuracy (3.5.0)
Installing Permission-LocationAlways (3.5.0)
Installing Permission-LocationWhenInUse (3.5.0)
Installing Polyline (5.0.2)
Installing RCT-Folly (2021.06.28.00-v2)
Installing RCTRequired (0.69.1)
Installing RCTTypeSafety (0.69.1)
Installing RNBootSplash (4.2.3)
Installing RNFastImage (8.5.11)
Installing RNGestureHandler (2.5.0)
Installing RNPermissions (3.5.0)
Installing RNReanimated (2.9.1)
Installing RNSVG (12.3.0)
Installing RNScreens (3.15.0)
Installing React (0.69.1)
Installing React-Codegen (0.69.1)
Installing React-Core (0.69.1)
Installing React-CoreModules (0.69.1)
Installing React-RCTActionSheet (0.69.1)
Installing React-RCTAnimation (0.69.1)
Installing React-RCTBlob (0.69.1)
Installing React-RCTImage (0.69.1)
Installing React-RCTLinking (0.69.1)
Installing React-RCTNetwork (0.69.1)
Installing React-RCTSettings (0.69.1)
Installing React-RCTText (0.69.1)
Installing React-RCTVibration (0.69.1)
Installing React-bridging (0.69.1)
Installing React-callinvoker (0.69.1)
Installing React-cxxreact (0.69.1)
Installing React-jsi (0.69.1)
Installing React-jsiexecutor (0.69.1)
Installing React-jsinspector (0.69.1)
Installing React-logger (0.69.1)
Installing React-perflogger (0.69.1)
Installing React-runtimeexecutor (0.69.1)
Installing ReactCommon (0.69.1)
Installing SDWebImage (5.11.1)
Installing SDWebImageWebPCoder (0.8.5)
Installing Solar-dev (3.0.1)
Installing Turf (2.4.0)
Installing Yoga (1.14.0)
Installing boost (1.76.0)
Installing fmt (6.2.1)
Installing glog (0.3.5)
Installing libwebp (1.2.1)
Installing react-native-geolocation (2.1.0)
Installing react-native-safe-area-context (4.3.1)
Installing react-native-spinkit (1.4.1)
```

but still can't understand why I still got the issue am I missing something ?

**Comment by s5z6** [comment]
@Polyrion it's not same issue. Try to remove `use_frameworks` and add `:modular_headers => true` only for mapbox pod

**Comment by kierancrown** [comment]
> @kierancrown :/ still got the issue ![Capture d’écran 2022-07-15 à 16 25 35](https://user-images.githubusercontent.com/69394749/179243676-012583ed-5c2b-4266-bfc3-00c4e3ae427d.png)
> 
> there is my patch file that got applied successfully :
> 
> ```
> diff --git a/node_modules/react-native/ReactCommon/React-bridging.podspec b/node_modules/react-native/ReactCommon/React-bridging.podspec
> index 5255c13..52a8eb0 100644
> --- a/node_modules/react-native/ReactCommon/React-bridging.podspec
> +++ b/node_modules/react-native/ReactCommon/React-bridging.podspec
> @@ -30,7 +30,7 @@ Pod::Spec.new do |s|
>    s.source                 = source
>    s.source_files           = "react/bridging/**/*.{cpp,h}"
>    s.exclude_files          = "react/bridging/tests"
> -  s.header_dir             = "react/bridging"
> +  s.header_dir             = "."
>    s.header_mappings_dir    = "."
>    s.compiler_flags         = folly_compiler_flags
>    s.pod_target_xcconfig    = { "HEADER_SEARCH_PATHS" => "\"$(PODS_ROOT)/RCT-Folly\"",
> ```
> 
> Podfile :
> 
> ```
> require_relative '../node_modules/react-native/scripts/react_native_pods'
> require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
> 
> platform :ios, '12.4'
> install! 'cocoapods', :deterministic_uuids => false
> 
> use_frameworks!
> target 'mapnav' do
>   config = use_native_modules!
> 
>   # Flags change depending on the env values.
>   flags = get_default_flags()
> 
>   permissions_path = '../node_modules/react-native-permissions/ios'
>   pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
>   pod 'Permission-LocationAccuracy', :path => "#{permissions_path}/LocationAccuracy"
>   pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways"
>   pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
> 
>   # Pods for Mapbox navigation
>   pod 'MapboxNavigation', '~> 2.6'
> 
>   use_react_native!(
>     :path => config[:reactNativePath],
>     # to enable hermes on iOS, change `false` to `true` and then install pods
>     :hermes_enabled => flags[:hermes_enabled],
>     :fabric_enabled => flags[:fabric_enabled],
>     # An absolute path to your application root.
>     :app_path => "#{Pod::Config.instance.installation_root}/.."
>   )
> 
>   target 'mapnavTests' do
>     inherit! :complete
>     # Pods for testing
>   end
> 
>   # Enables Flipper.
>   #
>   # Note that if you have use_frameworks! enabled, Flipper will not work and
>   # you should disable these next few lines.
>   if !ENV['CI']
>     # local configuration
>     # use_flipper!()
>     post_install do |installer|
>       installer.pods_project.targets.each do |target|
>         target.build_configurations.each do |config|
>           config.build_settings["ONLY_ACTIVE_ARCH"] = "NO"
>         end
>       end
>       react_native_post_install(installer)
>       __apply_Xcode_12_5_M1_post_install_workaround(installer) if defined?(__apply_Xcode_12_5_M1_post_install_workaround)
>     end
>   else
>     # CI configuration
>     post_install do |installer|
>       react_native_post_install(installer)
>       __apply_Xcode_12_5_M1_post_install_workaround(installer) if defined?(__apply_Xcode_12_5_M1_post_install_workaround)
>     end
>   end
> end
> ```
> 
> Pod install was successful
> 
> ```
> Installing DoubleConversion (1.1.6)
> Installing FBLazyVector (0.69.1)
> Installing FBReactNativeSpec (0.69.1)
> Installing MapboxCommon (22.0.0)
> Installing MapboxCoreMaps (10.6.1)
> Installing MapboxCoreNavigation (2.6.0)
> Installing MapboxDirections (2.6.0)
> Installing MapboxMaps (10.6.1)
> Installing MapboxMobileEvents (1.0.8)
> Installing MapboxNavigation (2.6.0)
> Installing MapboxNavigationNative (106.0.0)
> Installing MapboxSpeech (2.0.1)
> Installing Permission-Camera (3.5.0)
> Installing Permission-LocationAccuracy (3.5.0)
> Installing Permission-LocationAlways (3.5.0)
> Installing Permission-LocationWhenInUse (3.5.0)
> Installing Polyline (5.0.2)
> Installing RCT-Folly (2021.06.28.00-v2)
> Installing RCTRequired (0.69.1)
> Installing RCTTypeSafety (0.69.1)
> Installing RNBootSplash (4.2.3)
> Installing RNFastImage (8.5.11)
> Installing RNGestureHandler (2.5.0)
> Installing RNPermissions (3.5.0)
> Installing RNReanimated (2.9.1)
> Installing RNSVG (12.3.0)
> Installing RNScreens (3.15.0)
> Installing React (0.69.1)
> Installing React-Codegen (0.69.1)
> Installing React-Core (0.69.1)
> Installing React-CoreModules (0.69.1)
> Installing React-RCTActionSheet (0.69.1)
> Installing React-RCTAnimation (0.69.1)
> Installing React-RCTBlob (0.69.1)
> Installing React-RCTImage (0.69.1)
> Installing React-RCTLinking (0.69.1)
> Installing React-RCTNetwork (0.69.1)
> Installing React-RCTSettings (0.69.1)
> Installing React-RCTText (0.69.1)
> Installing React-RCTVibration (0.69.1)
> Installing React-bridging (0.69.1)
> Installing React-callinvoker (0.69.1)
> Installing React-cxxreact (0.69.1)
> Installing React-jsi (0.69.1)
> Installing React-jsiexecutor (0.69.1)
> Installing React-jsinspector (0.69.1)
> Installing React-logger (0.69.1)
> Installing React-perflogger (0.69.1)
> Installing React-runtimeexecutor (0.69.1)
> Installing ReactCommon (0.69.1)
> Installing SDWebImage (5.11.1)
> Installing SDWebImageWebPCoder (0.8.5)
> Installing Solar-dev (3.0.1)
> Installing Turf (2.4.0)
> Installing Yoga (1.14.0)
> Installing boost (1.76.0)
> Installing fmt (6.2.1)
> Installing glog (0.3.5)
> Installing libwebp (1.2.1)
> Installing react-native-geolocation (2.1.0)
> Installing react-native-safe-area-context (4.3.1)
> Installing react-native-spinkit (1.4.1)
> ```
> 
> but still can't understand why I still got the issue am I missing something ?

Also don't forget to do a pod install afterwards

**Comment by Kudo** [comment]
@Polyrion [my fix](https://github.com/facebook/react-native/commit/f97c6a5b498eec95e99a02c7842cb2ae160cd6cd) is originally to address `use_frameworks!`, so it doesn't make sense you have to turn off use_frameworks. do you have a minimal reproducible example repository? i can try to take a further look in case it helps.

**Comment by Polyrion** [comment]
@Kudo i was thinking the same about use_framework, I tried with : 
RN 68.2 Fresh install work well
RN 69 Fresh install broke a Path React Bridging Error :/ 
RN 69.1 Fresh install work Well 

I'm looking on my 69.1 project if the error could not come from a dependency 

there are the different public repo : 
https://github.com/Polyrion/mapnav
https://github.com/Polyrion/mapnav_rn69.0
https://github.com/Polyrion/mapnav_rn_69.1

Thanks for your help

**Comment by kelset** [comment]
since this is fixed in 0.69.1, does it mean we can close this off?

**Comment by Kudo** [comment]
@kelset i am thinking to propose [the workaround](https://github.com/facebook/react-native/issues/34102#issuecomment-1180727214) to react_native_pods.rb. that will fix the build errors from some third party modules like vision-camera.

**Comment by jpike88** [comment]
@kelset I'm on 0.69.1 and just run into this issue, as far as I know this is not fixed/release on a main branch yet.

**Comment by kelset** [comment]
hey folks - RN 0.69.3 is out and contains the fix from @Kudo; let us know if this issue is fixed now for you!

**Comment by mm-webx** [comment]
Thanks everyone, especially @Kudo 🎉

**Comment by shirakaba** [comment]
@Kudo @kelset still an issue in a project based on 0.69.3, I'm afraid. Here's a MWE. It's just the 0.69.3 starter template, with the files `JSIUtils.h` and `JSIUtils.mm` added to the iOS build target.

https://github.com/shirakaba/repro-react-bridging-header-not-found

It fails upon trying to build the file `JSIUtils.mm`, due to its include of `<ReactCommon/TurboModuleUtils.h>`.

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/14055146/183797792-cc920a01-380c-498f-9b7d-fb90b0369f90.png">

**Comment by Kudo** [comment]
@shirakaba #34214 was targeting for third party modules but not the app target. for app targets, please add the React-bridging search path to the [project.pbxproj](https://github.com/shirakaba/repro-react-bridging-header-not-found/blob/main/ios/rnobjc.xcodeproj/project.pbxproj)

**Comment by evelant** [comment]
Hmm I'm running into this one trying to transition to `use_frameworks!` for react-native-firebase v15+ support. In my case there seems to be an issue with paths when using `pnpm` that's preventing the headers from getting copied into the `ios/Pods/Headers/Private/React-bridging/react/bridging` folder like they should. Instead they get copied to `ios/build/Build/node_modules/.pnpm/react-native@0.69.5_unoo4p5zfjb5v6bnauqzc4ataq_lx6v52nf6lj3r6bs5j5fbvoknq/node_modules/react-native/ReactCommon/react/bridging` which is clearly not the correct location. This is on 0.69.5 expo 46.0.10 with dev-client .

@Kudo any idea where/when the paths get calculated for the copy step for header files on iOS? I have little familiarity with cocoapods so I haven't been able to find it.

**Comment by evelant** [comment]
I created a reproduction here https://github.com/evelant/test-pnpm-ios-headers-path-bug

**Comment by jorgegvallejo** [comment]
I still got this error on RN 0.70.3 and [this comment from Kudo](https://github.com/facebook/react-native/issues/34102#issuecomment-1180727214) helped me.

I'm not using `use_frameworks!` though

**Comment by kelset** [comment]
is `/React-bridging` something Expo specific? 🤔

need a repro for react-native init'd component

**Comment by evelant** [comment]
@kelset no it's part of react native core, here's a reproduction without expo: https://github.com/evelant/rnfbdemo

**Comment by adiffmike** [comment]
Hi all, I'm a bit late to the party here and can't remember all my steps, but I was running into this using React Native firebase with  use_frameworks! :linkage => :static and an Nx monorepo, I think it may be a combo of those two things that caused my issues.   I'm using "react-native": "0.70.1" which seems to have @Kudo's patch already in it to update the Header paths.  After digging around on where the headers ended up I emulated that in my Pod file  and added the PODS_TARGET_SRCROOT to it and my app was able to build properly.  YMMV. 

``
   __apply_Xcode_12_5_M1_post_install_workaround(installer) // after this
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["HEADER_SEARCH_PATHS"] ||= "$(inherited) "
        config.build_settings["HEADER_SEARCH_PATHS"] << '"$(PODS_TARGET_SRCROOT)" '
      end
    end
``

**Comment by meftunca** [comment]
![Screenshot 2022-12-02 at 17 14 53](https://user-images.githubusercontent.com/19187204/205316291-bb5b910d-b39e-4321-894c-7900cc40e630.jpg)

`"react-native": "0.71.0-rc.3"` same issue

**Comment by atanaskanchev** [comment]
Seems to be fixed in `0.71.0-rc.5`, but unfortunately this version is still not supported by expo, so my problem remains https://github.com/invertase/react-native-firebase/issues/6800

**Comment by jeremyblong** [comment]
> this may fix the header not found error:
> 
> ```diff
> --- a/ios/Podfile
> +++ b/ios/Podfile
> @@ -33,5 +33,14 @@ target 'RN069' do
>    post_install do |installer|
>      react_native_post_install(installer)
>      __apply_Xcode_12_5_M1_post_install_workaround(installer)
> +
> +   installer.pods_project.targets.each do |target|
> +     target.build_configurations.each do |config|
> +       config.build_settings['HEADER_SEARCH_PATHS'] ||= '$(inherited) '
> +       config.build_settings['HEADER_SEARCH_PATHS'] << '"$(PODS_ROOT)/Headers/Private/React-bridging/react/bridging" '
> +       config.build_settings['HEADER_SEARCH_PATHS'] << '"$(PODS_CONFIGURATION_BUILD_DIR)/React-bridging/react_bridging.framework/Headers" '
> +     end
> +   end
> +
>    end
>  end
> ```
> 
> if that works fine, maybe we could propose the fix to the [`react_native_post_install`](https://github.com/facebook/react-native/blob/23accbf58d2fa03ad020e07f00012a32609c7218/scripts/react_native_pods.rb#L287-L302) helper.
> 
> for `jsi::` -> `facebook::jsi::` namespace change, it is from [009d80b](https://github.com/facebook/react-native/commit/009d80bf5a55dd74be448960b1344ac7599c6bae) and it's a better practice IMO even though that requires third party modules to fix the breaking code.

You sir are an absolute legend. TY for the fix

**Comment by pottercomuneo** [comment]
I'm still facing @shirakaba's exact same issue, in RN 0.69.8 and react-native-vision-camera 2.15, and I already followed all the suggestions with no success. How did you solve?

**Comment by fontesrp** [comment]
It seems React Native 0.72.0 brought back this issue

**Comment by reedling78** [comment]
I'm still having this issue on 0.72.3 while trying to use react-native-vision-camera 2.15.4. None of the patches mentioned have worked.

**Comment by VitaliiBlack** [comment]
SAME ISSUE

**Comment by Risovas** [comment]
Same issue here, using `react-native`@`0.72.4`, `react-native-vision-camera`@`^2.15.6` and `@react-native-firebase/app`@`^18.3.1`.
Have to use `use_frameworks! :linkage => :static` in my Podfile as the firebase instructions say, but then I get the `'react/bridging/CallbackWrapper.h' file not found` error. Have tried pretty much all possible workarounds posted on many issues and the error persists.
Downgrading the `react-native` version is not an option for us, neither do I think it's a good a idea to downgrade the `@react-native-firebase/app` version so that `use_frameworks` is no longer required.
Does anyone have any clue on this?

**Comment by fontesrp** [comment]
@Risovas did you try the workarounds in [#38140](https://github.com/facebook/react-native/issues/38140)? I have yet to have time to try them, but they seem promising.

**Comment by sanderdewilde** [comment]
Also experiencing the issue (using use_frameworks! :linkage => :static for firebase), with
"react-native": "0.72.7",
"react-native-vision-camera": "^3.6.12",

**Comment by aybarska** [comment]
same on 
`"react-native": "^0.72.8"`
i have to use `use_modular_headers!`
and `use_frameworks!`

**Comment by Dharmik57** [comment]
@aybarska  Does it working?

**Comment by dharmik-valani** [comment]
hi @Amurmurmur , yes I have resolved it

**Comment by andvalsol** [comment]
@Amurmurmur what was your change?
