### ISSUE TITLE
Error build release (hermes enable)

### ISSUE THREAD

**Issue by cervisebas** [facebook/react-native#34116]
### Description

Console out:

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\cervi\Desktop\Escuela\proyecto-asistencia\@Reset2\TecnicaDigital\node_modules\react-native\react.gradle' line: 126

* What went wrong:
Execution failed for task ':app:bundleReleaseJsAndAssets'.
> java.lang.Exception: Couldn't determine Hermesc location. Please set `project.ext.react.hermesCommand` to the path of the hermesc binary file. node_modules/react-native/sdks/hermesc/%OS-BIN%/hermesc

### Version

0.69.1

### Output of `npx react-native info`

System:
    OS: Windows 10 10.0.22000
    CPU: (4) x64 Intel(R) Core(TM) i3-7020U CPU @ 2.30GHz
    Memory: 1.92 GB / 7.88 GB
  Binaries:
    Node: 16.13.1 - ~\AppData\Local\Temp\yarn--1656711531736-0.4762878003872508\node.CMD
    Yarn: 1.22.19 - ~\AppData\Local\Temp\yarn--1656711531736-0.4762878003872508\yarn.CMD
    npm: 8.12.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 28, 29, 30, 31, 32
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0
      System Images: android-24 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom
      Android NDK: 23.1.7779620
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.10240.0, 10.0.17763.0, 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Version     2021.1.0.0 AI-211.7628.21.2111.8193401
    Visual Studio: 15.9.28307.1919 (Visual Studio Community 2017), 16.11.32407.337 (Visual Studio Community 2019)
  Languages:
    Java: 11.0.13 - C:\Program Files\Common Files\Oracle\Java\javapath\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.69.1 => 0.69.1
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

.

### Snack, code example, screenshot, or link to a repository

.

**Comment by JoseLion** [comment]
I faced the same issue with a new application created with `react-native init`. The problem is that the `hermesCommand` extra property is missing in the app-level `build.gradle` file. I solved the problem by adding the correct Hermes Command path, like so:
```gradle
project.ext.react = [
    enableHermes: true,  // clean and rebuild if changing
    hermesCommand: '../../node_modules/react-native/sdks/hermesc/%OS-BIN%/hermesc'
]
```

> **NOTE:** Setting the path to `../../node_modules/hermes-engine/%OS-BIN%/hermesc` instead will cause a conflict between Hermes versions, which will throw the runtime error `Compiling JS failed: Wrong bytecode version. Expected 85 but got 84`, causing the app to crash as soon as it starts.  

I hope this helps 🙂

**Comment by aleluiah** [comment]
@[cervisebas](https://github.com/cervisebas) were you able to build successfully on windows 10 i have been having error with my build on windows checkout the issue here https://github.com/facebook/react-native/issues/34084

**Comment by cortinico** [comment]
> I solved the problem by adding the correct Hermes Command path, like so:

Thanks for sharing this @JoseLion That sounds like a potential bug though.
The `hermesCommand` config has a sensible default which is the same value you're setting:

https://github.com/facebook/react-native/blob/71e89213aad0b53e34674a502310adf9e98adab4/react.gradle#L117-L124

I wonder why you had to specify this value again.

**Comment by wfern** [comment]
I can confirm the @JoseLion's fix, adding ".exe" in the file path works:

```gradle
// 3. If the react-native contains a pre-built hermesc, use it.
def hermescBin = Os.isFamily(Os.FAMILY_WINDOWS) ? 'hermesc.exe' : 'hermesc'
def prebuiltHermesPath = ("node_modules/react-native/sdks/hermesc/%OS-BIN%/" + hermescBin)
        .replaceAll("%OS-BIN%", getHermesOSBin())
        .replace('/' as char, File.separatorChar);
```

Thanks @JoseLion!

**Comment by JoseLion** [comment]
I opened PR #34151 with this fix. I hope this helps 🎉

**Comment by nibblesnbits** [comment]
Still fails for me on a new project when I run `gradlew clean`.

```
> Task :ReactAndroid:hermes-engine:buildCMakeRelease[arm64-v8a][libhermes] FAILED
C/C++: ninja: error: 'C:/git-other/ostrichv2native/node_modules/react-native/ReactAndroid/hermes-engine/build/hermes/bin/Release/hermesc.exe', needed by 'lib/InternalBytecode/InternalBytecode.hbc', missing and no known rule to make it

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':ReactAndroid:hermes-engine:buildCMakeRelease[arm64-v8a][libhermes]'.
> Build command failed.
  Error while executing process C:\Users\sgcol\AppData\Local\Android\Sdk\cmake\3.18.1\bin\ninja.exe with arguments {-C C:\git-other\ostrichv2native\node_modules\react-native\ReactAndroid\hermes-engine\.cxx\Release\t4zh3s1n\arm64-v8a libhermes}
  ninja: Entering directory `C:\git-other\ostrichv2native\node_modules\react-native\ReactAndroid\hermes-engine\.cxx\Release\t4zh3s1n\arm64-v8a'

  ninja: error: 'C:/git-other/ostrichv2native/node_modules/react-native/ReactAndroid/hermes-engine/build/hermes/bin/Release/hermesc.exe', needed by 'lib/InternalBytecode/InternalBytecode.hbc', missing and no known rule to make it
```

Similar when running `npm run android`

```
error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
CMake Deprecation Warning at CMakeLists.txt:42 (cmake_policy):
  The OLD behavior for policy CMP0026 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


Using Windows 10 built-in ICU

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':ReactAndroid:hermes-engine:buildCMakeRelease[arm64-v8a][libhermes]'.
> Build command failed.
  Error while executing process C:\Users\sgcol\AppData\Local\Android\Sdk\cmake\3.18.1\bin\ninja.exe with arguments {-C C:\git-other\ostrichv2native\node_modules\react-native\ReactAndroid\hermes-engine\.cxx\Release\t4zh3s1n\arm64-v8a libhermes}
  ninja: Entering directory `C:\git-other\ostrichv2native\node_modules\react-native\ReactAndroid\hermes-engine\.cxx\Release\t4zh3s1n\arm64-v8a'

  ninja: error: 'C:/git-other/ostrichv2native/node_modules/react-native/ReactAndroid/hermes-engine/build/hermes/bin/Release/hermesc.exe', needed by 'lib/InternalBytecode/InternalBytecode.hbc', missing and no known rule to make it
```

**Comment by JoseLion** [comment]
@nibblesnbits I think the path for `hermesc` is incorrect when `hermes-engine` is built from source. Please take a look at [this comment](https://github.com/facebook/react-native/issues/34084#issuecomment-1180051198) for more details 🙂 

I can include a fix in the open PR, but I need some help to confirm if the proposed solution fixes the issue since I'm not currently using the new architecture 😅
