### ISSUE TITLE
CocoaPods could not find compatible versions for pod "React-bridging":

### ISSUE THREAD

**Issue by faz919** [facebook/react-native#34127]
### Description

When running `cd ios && pod install`, I receive the following error: 
`[!] CocoaPods could not find compatible versions for pod "React-bridging":
  In Podfile:
    React-bridging (from '../node_modules/react-native/ReactCommon')

    ReactCommon/turbomodule/core (from '../node_modules/react-native/ReactCommon') was resolved to 0.69.1, which depends on
      React-bridging (= 0.69.1)

Specs satisfying the 'React-bridging (from '../node_modules/react-native/ReactCommon'), React-bridging (= 0.69.1)' dependency were found, but they required a higher minimum deployment target.`

I'm using RN 0.67.2. Any suggestions?

### Version

0.67.2

### Output of `npx react-native info`

System:
    OS: macOS 12.2
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 793.25 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 18.3.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 8.12.1 - ~/Documents/ReactNative/[appname]/node_modules/.bin/npm
    Watchman: 2022.06.06.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 29, 30, 32
      Build Tools: 29.0.2, 30.0.2, 30.0.3, 32.0.0, 32.1.0
      System Images: android-23 | Google APIs Intel x86 Atom, android-29 | Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8139111
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 18.0.0 
    react-native: ^0.67.2 => 0.69.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. Create a react native app
2. Run `cd ios && pod install`

### Snack, code example, screenshot, or link to a repository

Unable to provide a link to a reproducer as the repository contains sensitive information.

**Comment by khacdai37** [comment]
I meet same this issue.
## Setup
Xcode Project: `iOS Development 11.0`
Podfile: 
```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'
install! 'cocoapods', :deterministic_uuids => false

```
RN: `"react": "18.0.0", "react-native": "0.69.1"`

## Output
```
[!] CocoaPods could not find compatible versions for pod "React-RCTText":
  In Podfile:
    React-RCTText (from `../node_modules/react-native/Libraries/Text`)

Specs satisfying the `React-RCTText (from `../node_modules/react-native/Libraries/Text`)` dependency were found, but they required a higher minimum deployment target.
```
