### ISSUE TITLE
android 12 crashed when open

### ISSUE THREAD

**Issue by Eumhongin** [facebook/react-native#34124]
### Description

build from local `yarn android` is working

but bundleRelease and download from play store version is crashed some android devices.

This is Report from google in play console error list

> 
> java.lang.RuntimeException: 
>   at android.app.ActivityThread.handleBindApplication (ActivityThread.java:7511)
>   at android.app.ActivityThread.access$1700 (ActivityThread.java:310)
>   at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2281)
>   at android.os.Handler.dispatchMessage (Handler.java:106)
>   at android.os.Looper.loopOnce (Looper.java:226)
>   at android.os.Looper.loop (Looper.java:313)
>   at android.app.ActivityThread.main (ActivityThread.java:8669)
>   at java.lang.reflect.Method.invoke (Native Method)
>   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:571)
>   at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1135)
> Caused by: java.lang.RuntimeException: 
>   at com.facebook.soloader.SoLoader.init (SoLoader.java:219)
>   at com.summitplay.MainApplication.onCreate (MainApplication.java:54)
>   at android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1211)
>   at android.app.ActivityThread.handleBindApplication (ActivityThread.java:7506)
> Caused by: java.io.FileNotFoundException: 
>   at libcore.io.IoBridge.open (IoBridge.java:575)
>   at java.io.FileOutputStream.<init> (FileOutputStream.java:236)
>   at java.io.FileOutputStream.<init> (FileOutputStream.java:186)
>   at com.facebook.soloader.FileLocker.<init> (FileLocker.java:36)
>   at com.facebook.soloader.FileLocker.lock (FileLocker.java:32)
>   at com.facebook.soloader.UnpackingSoSource.prepare (UnpackingSoSource.java:430)
>   at com.facebook.soloader.SoLoader.initSoSources (SoLoader.java:327)
>   at com.facebook.soloader.SoLoader.init (SoLoader.java:207)
>   at com.facebook.soloader.SoLoader.init (SoLoader.java:189)
>   at com.facebook.soloader.SoLoader.init (SoLoader.java:217)
> Caused by: android.system.ErrnoException: 
>   at libcore.io.Linux.open (Native Method)
>   at libcore.io.ForwardingOs.open (ForwardingOs.java:567)
>   at libcore.io.BlockGuardOs.open (BlockGuardOs.java:273)
>   at libcore.io.ForwardingOs.open (ForwardingOs.java:567)
>   at android.app.ActivityThread$AndroidOs.open (ActivityThread.java:8529)
>   at libcore.io.IoBridge.open (IoBridge.java:561)

### Version

0.66.3

### Output of `npx react-native info`

System:
    OS: macOS 12.4
    CPU: (16) x64 Intel(R) Xeon(R) W-2140B CPU @ 3.20GHz
    Memory: 1.26 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 8.5.5 - /usr/local/bin/npm
    Watchman: 2021.11.01.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7935034
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.5 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.3 => 0.66.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

cd android
./gradlew bundleRelease

### Snack, code example, screenshot, or link to a repository

-

**Comment by Eumhongin** [comment]
remove app cahce & data, it works,

but remove app and re-install,

it happen...

please help ! ;(

**Comment by GouravNainwaya** [comment]
I Have the Same issue in react native 0.69 version but After build not crashed in react native 0.68 version

**Comment by cortinico** [comment]
Is this happening on a blank app from the template?
Is this happening on every Android 12 emulator or on a specific device?
