### ISSUE TITLE
How are the original components compatible with or migrated to Fabric?

### ISSUE THREAD

**Issue by zhutc** [facebook/react-native#34130]
### Description

Our project uses a lot of third party components, if they don't support fabric, how should we be compatible on fabric?

### Version

0.69.0

### Output of `npx react-native info`

none

### Steps to reproduce

none

### Snack, code example, screenshot, or link to a repository

none

**Comment by cortinico** [comment]
cc @cipolleschi for visibility

> Our project uses a lot of third party components, if they don't support fabric, how should we be compatible on fabric?

Currently, you can enable Fabric on a Root-by-Root basis. If all the components in a Root View are Fabric compatible, you should be good to go.

We understand that this is not ideal, as most apps just have one root (i.e. only a MainActivity), so this would mean that all the libraries you depend on should be migrated to the New Architecture before you can enable Fabric. We're looking into solutions to make the migration easier for app users, and we'll share more in the near future.
