### ISSUE TITLE
[May off-topic]AGP Code indexing not working when update to 0.68

### ISSUE THREAD

**Issue by psionic12** [facebook/react-native#34139]
### New Version

0.68.1

### Old Version

0.65

### Build Target(s)

Andoid

### Output of `react-native info`

None

### Issue and Reproduction Steps

I found that when update the source code to 0.68, the Android Studio will not index all the codes in ReactAndroid folder, which makes it hard to read and navigate codes. Is this a common issue, or is there any possible reason to lead to this problem?

AGP: 7.2.0
Gradle: 7.3.3

**Comment by cortinico** [comment]
Thanks for mentioning this @psionic12 
I believe the issue is only for New Architecture right? Can you confirm?
I'm actively working on this.

**Comment by psionic12** [comment]
I guess so, I update RN from 0.63.2 to 0.68, and 0.63.2 does not have this problem.

Currently, I just right-click the `com.facebook` folder and select the "mark as source", and the index works until the next time the code compiles, so I guess AGP might update the configuration of IDE somehow.

I tried to add source folder entry manually in .idea/modules, but seems not working.

**Comment by cortinico** [comment]
> I guess so

Are you experiencing this on a project with New Architecture or not?

**Comment by psionic12** [comment]
Yes, this happens with a project with New Architecture on.

**Comment by cortinico** [comment]
Just a heads up that this has been fixed here:
https://github.com/reactwg/react-native-new-architecture/discussions/102
