### ISSUE TITLE
adjustsFontSizeToFit doesn't work

### ISSUE THREAD

**Issue by Chepman32** [facebook/react-native#34138]
### Description

adjustsFontSizeToFit parameter does not rescale text inside Text component

### Version

0.68.1

### Output of `npx react-native info`

There are no bug logs for this issue

### Steps to reproduce

Make a View component, place there Text component with some text and use adjustsFontSizeToFit parametr in <Text>

Environment: iOS Simulator

### Snack, code example, screenshot, or link to a repository

<View >
          <Text
            style={styles.intPart}
            adjustsFontSizeToFit
          >
            98798798
          </Text>

**Comment by Marcoo09** [comment]
Hi @Chepman32, I'm trying to reproduce this problem without success.
Could you provide more information about ios version and a code snippet of your example?
It would be great to have an expo snack with the problem.

**Comment by MrSquaare** [comment]
Hello!

The following snippet doesn't work on iOS nor Web (on iOS: shrunk by container size; on Web: overflow container)

<details>
<summary>Details</summary>

```js
import * as React from 'react';
import { Text, View, StyleSheet } from 'react-native';

export default function App() {
  return (
    <View style={styles.container}>
      <View style={styles.paragraphContainer}>
        <Text adjustsFontSizeToFit={true} style={styles.paragraph}>
          I am resized on Android, but I am not on iOS nor Web! Sad =(
        </Text>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  paragraphContainer: {
    width: 200,
    height: 50,
    borderWidth: 1,
    borderColor: "#ff0000",
  },
  paragraph: {
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
  },
});
```

</details>

See this snack for a demo: https://snack.expo.dev/32LBeFz7C

**Comment by fabriziobertoglio1987** [comment]
Do you still experience this issue? 

I have four years of experience maintaining facebook/react-native and I specialize in the Text and TextInput components. I currently have 58 [facebook/react-native PRs](https://github.com/facebook/react-native/pulls?q=is%3Apr+author%3Afabriziobertoglio1987+). 

If you still experience this issue, I will prepare a patched release with the fix.

Thanks a lot

**Comment by MrSquaare** [comment]
Hi @fabriziobertoglio1987 

It seems that the bug is still present, at least with Expo 49 (which is React Native 0.72.6)

See this snack for a demo:
- https://snack.expo.dev/jWTRElQs9?platform=ios
- https://snack.expo.dev/jWTRElQs9?platform=web

I'll try later with a bare latest React Native project

Thanks!

**Comment by vlanemcev** [comment]
Reopen it please :(

**Comment by vlanemcev** [comment]
@fabOnReact Hi! 

The issue is still persist, is it possible to ask you about prepare pathed release fix with this?

**Comment by cortinico** [comment]
If the bug is still present, please open a new issue, provide a reproducer and link against this one

**Comment by alexandreandriesse** [comment]
I have the same problem
