### ISSUE TITLE
Problem running the Movie example

### ISSUE THREAD

**Issue by stylesuxx** [facebook/react-native#3413]
Hey guys, I have problems running the Movie example on a physical (Android 5.1.1) device.
Build successfully, packager also starts without a problem.

When I open the app on the device it crashes instantly, the logcat output is as follows:
```
W/ReactNativeJS(16582): 'Warning: Native component for "RCTModalHostView" does not exist'
D/ReactNativeJS(16582): 'Running application "MoviesApp" with appParams: {"initialProps":{},"rootTag":1}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF'
W/ReactNativeJS(16582): 'Warning: Failed propType: Invariant Violation: Invalid prop `type` of value `ThemeAttrAndroid` supplied to `TouchableNativeFeedback`, expected one of ["RippleAndroid"].\nBad object: {\n  "type": "ThemeAttrAndroid",\n  "attribute": "selectableItemBackgroundBorderless"\n} Check the render method of `SearchBar`.'
```

**edit:** Similar thing is happening when I try the *UIExplorer* example:
```
W/ReactNativeJS(20859): 'Warning: Native component for "RCTModalHostView" does not exist'
```

In both cases I seem to at least be missing the component for *RCTModalHostView*.

May be a duplicate of #2868

**Comment by javache** [comment]
The RCTModalHostView is just a warning, so I don't think that's the issue here.

Invariant Violation: Invalid prop `type` of value `ThemeAttrAndroid` supplied to `TouchableNativeFeedback`, expected one of ["RippleAndroid"].  Check the render method of `SearchBar`.'

**Comment by andreicoman11** [comment]
You can ignore the warning.
I just pulled and it seems to work. It might have been a transient issue. Can you make sure you are using the latest versions of the code?

**Comment by stylesuxx** [comment]
Just wanted to confirm, that after pulling the current master everything is working as it should. Thank you.
