### ISSUE TITLE
React Native isn't build on latest version of SoLoader

### ISSUE THREAD

**Issue by seventhmoon** [facebook/react-native#34143]
### Description

SoLoader recently fixed a few app crashing issues. The latest version is `0.10.4`

However, the [ReactAndroid](
https://github.com/facebook/react-native/blob/303aaf88ed5e7d8b83dd3978a0b06b3a829a27ac/ReactAndroid/gradle.properties#L17) is still using `0.10.3`

### Version

0.69.1

### Output of `npx react-native info`

N/A

### Steps to reproduce

N/A

### Snack, code example, screenshot, or link to a repository

https://github.com/facebook/SoLoader/releases/tag/v0.10.4

**Comment by Yandamuri** [comment]
facing same issue. I am using 0.10.3

**Comment by simpleton** [comment]
Thanks for raising this issue. Updated in https://github.com/facebook/react-native/commit/1237952d070bfe28ff2c94cd9bf8ea19e6cdd395

**Comment by cortinico** [comment]
Closing as SoLoader has been updated in https://github.com/facebook/react-native/commit/1237952d070bfe28ff2c94cd9bf8ea19e6cdd395 as mentioned

**Comment by Yandamuri** [comment]
@cortinico @simpleton I am in `React-Native 0.67`.

I am able to get rid of this issue only by enabling `Hermes`. 

Can you please let me know hw can I resolve this issue with out enabling `Hermes`?

**Comment by cortinico** [comment]
> Can you please let me know hw can I resolve this issue with out enabling `Hermes`?

You can add a dependency in you `android/app/build.gradle` file as follows:

```
implementation("com.facebook.soloader:soloader:0.10.4")
```

**Comment by AamirHafiez** [comment]
@cortinico How do we get this fixed in an existing react native v0.64 project having Hermes enabled?

Thanks.

**Comment by cortinico** [comment]
> @cortinico How do we get this fixed in an existing react native v0.64 project having Hermes enabled?

The fixes I suggested adds a dependency that will get transitively applied to all the modules. So it should work for all the RN versions, modulo soloarders incompatibilities if the version bump is too high.
