### ISSUE TITLE
How to Customize selection menu of WebView

### ISSUE THREAD

**Issue by ZetaChow** [facebook/react-native#3414]
I consider show custom selection menu when user select some text on webview.
how to do?
dose need create custom component? or not?

**Comment by javache** [comment]
I'm not aware of any API available for this currently. If you're talking about iOS, you can consider an approach like http://stackoverflow.com/questions/2955354/showing-custom-menu-on-selection-in-uiwebview-in-iphone and create a custom native module that wraps this behaviour for you.

Feel free to submit a pull-request with this feature, or publish a library that provides this yourself.

**Comment by ZetaChow** [comment]
Thanks, I'll try it
