### ISSUE TITLE
TextInput keyboard closed for each character 

### ISSUE THREAD

**Issue by KabilLattice** [facebook/react-native#34144]
### Description

on custom component textinput keyboard getting closed for each character / each state update 

for example, i have page with 1 text comp, 1 textinput comp and a custom comp(textinput). the first textinput is working correctly no issues, but the second textinput (custom) keyboard closed for each state update 

export default function App() {
  const [value1, setValue1] = React.useState('');
  const [value2, setValue2] = React.useState('');

  const MyInput = () => (
    <TextInput
      value={value2}
      onChangeText={setValue2}
      placeholder={'Enter Value two'}
    />  );

  return (
    <View style={styles.container}>
      <Text>test</Text>
      <TextInput
        value={value1}
        onChangeText={setValue1}
        placeholder={'Enter Value one'}
      />
      <MyInput />
    </View>  );}

### Version

many versions

### Output of `npx react-native info`

null

### Steps to reproduce

null

### Snack, code example, screenshot, or link to a repository

![textinput state update](https://user-images.githubusercontent.com/69196041/177549322-3026091e-f478-4c2a-802c-9d561bd93444.png)

snack > https://snack.expo.dev/@ragu3535/text-input-state-test

**Comment by m7amad-7asan** [comment]
I just got this issue too, please share the solution when you find it

**Comment by sadiksdk64** [comment]
move MyInput outside App.

**Comment by KabilLattice** [comment]
> move MyInput outside App.

yeah, this is working, though not sure this is the correct approach. 

[snack](https://snack.expo.dev/@ragu3535/text-input-state-test)

![image](https://user-images.githubusercontent.com/69196041/178412906-4db1cfbd-59a3-4be9-911d-331ef659a9e6.png)

![image](https://user-images.githubusercontent.com/69196041/178412964-e765ba59-15ce-4610-b300-bbb8c3334a82.png)


` import * as React from 'react';
import {
  Text,
  View,
  StyleSheet,
  TextInput,
  TouchableOpacity,
} from 'react-native';

var value3 = '';

var txt_username, txt_password;
export default function App() {
  const [value1, setValue1] = React.useState('');

  const login = () => {
    console.log(`username >${txt_username} and password ${txt_password}`);
  };

  return (
    <View style={styles.container}>
      <Text style={styles.paragraph}>Login Form</Text>
      <LoginForm />
      <TouchableOpacity
        style={{ marginVertical: 20, borderWidth: 1, padding: 15 }}
        onPress={login}>
        <Text style={{ color: 'green' }}>login</Text>
      </TouchableOpacity>
    </View>
  );
}

const MyInput = () => {
  const [value2, setValue2] = React.useState('');
  return (
    <TextInput
      value={value2}
      onChangeText={(txt) => {
        value3 = txt;
        setValue2(txt);
      }}
      placeholder={'Enter Value two'}
    />
  );
};

const LoginForm = () => {
  const [username, setUsername] = React.useState('');
  const [password, setPassword] = React.useState('');

  return (
    <View>
      <TextInput
        value={username}
        onChangeText={(txt) => {
          txt_username = txt;
          setUsername(txt);
        }}
        placeholder={'Enter Username'}
      />
      <TextInput
        value={password}
        onChangeText={(txt) => {
          txt_password = txt;
          setPassword(txt);
        }}
        placeholder={'Enter Password'}
      />
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#ecf0f1',
    padding: 8,
  },
  paragraph: {
    margin: 24,
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
  },
});
 `

**Comment by KabilLattice** [comment]
> I just got this issue too, please share the solution when you find it

lets try the above
