### ISSUE TITLE
Android Flag Secure - Hide screen when app goes to background mode without block screenshots

### ISSUE THREAD

**Issue by caiohyppolito** [facebook/react-native#34157]
### Description

I would like to hide the screen when the app is in the background. On iOS I found a good solution using AppState. But on android it didn't work. So I looked for a native solution and found FLAG_SECURE. It works when I use it inside onCreate, but it also blocks users from taking screenshots. After that I tried setting the FLAG_SECURE when the app is onPause and clearing when the app is onResume but it didn't work. Can someone help me?

### Version

0.67.4

### Output of `npx react-native info`

System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-11390H @ 3.40GHz
    Memory: 3.45 GB / 15.74 GB
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.15 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 23, 28, 29, 30, 31, 32
      Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0
      System Images: android-26 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: AI-212.5712.43.2112.8609683
    Visual Studio: 17.2.32516.85 (Visual Studio Enterprise 2022)
  Languages:
    Java: 18.0.1.1 - C:\Program Files\Common Files\Oracle\Java\javapath\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.67.4 => 0.67.4
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

No steps to reproduce

### Snack, code example, screenshot, or link to a repository

 MainActivity:

 @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(null);
  }

  @Override
  protected void onResume() {
      super.onResume();
      getWindow().clearFlags(WindowManager.LayoutParams.FLAG_SECURE);
  }

  @Override
  protected void onPause() {
      super.onPause();
      getWindow().setFlags(WindowManager.LayoutParams.FLAG_SECURE, WindowManager.LayoutParams.FLAG_SECURE);
  }

**Comment by euthribeiro** [comment]
So guys, I found a solution to make this work. We created a library to help others who might have this problem in the future.

https://github.com/euthribeiro/react-native-background-secure

**Comment by euthribeiro** [comment]
So guys, I found a solution to make this work. We created a library to help others who might have this problem in the future.

https://github.com/euthribeiro/react-native-background-secure
