### ISSUE TITLE
Error installing OpenSSL-Universal

### ISSUE THREAD

**Issue by mariogruizdiaz** [facebook/react-native#34156]
No luck, still getting error:
```
Installing OpenSSL-Universal (1.1.1100)

[!] Error installing OpenSSL-Universal
[!] /usr/bin/curl -f -L -o /var/folders/95/ckg2y0m5175csw33_96kl9vh0000gn/T/d20220707-90149-xkc5ws/file.zip https://github.com/krzyzanowskim/OpenSSL/archive/1.1.1100.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.11.3 cocoapods-downloader/1.6.3'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404

```

**Comment by tom-hanks** [comment]
> 
我也是 怎么办

**Comment by mariogruizdiaz** [comment]
The real error is hidden because the flag -f is used. The real problem is that the installation process doesn't permissions to download a file into the "/var/folders/95/ckg2y0m5175csw33_96kl9vh0000gn/T/d20220707-90149-xkc5ws/"

And of course the installation process doesn't find the file.zip file and throw a 404 error. 
The funny think is that after updating the permission to the /var/folder/ recursively, the process try to do the same but this time pointing to another folfer "/tmp/..." folder.
BY doing the same, the process try to download the zip file into a temp folder created into the ios subfolder of the proyect that is trying to setup. Everytime the intallation process point to a different temp folder and it doesn't matter if the parent folder has setup the read&wite permissions recuresiverly. The process fails one and over again

**Comment by cortinico** [comment]
> The real error is hidden because the flag -f is used. The real problem is that the installation process doesn't permissions to download a file into the "/var/folders/95/ckg2y0m5175csw33_96kl9vh0000gn/T/d20220707-90149-xkc5ws/"

Closing this as it's essentially a CocoaPod/Mac Permission issue. Thanks for investigating and providing an explanation 👍

**Comment by built-by-as** [comment]
> The real error is hidden because the flag -f is used. The real problem is that the installation process doesn't permissions to download a file into the "/var/folders/95/ckg2y0m5175csw33_96kl9vh0000gn/T/d20220707-90149-xkc5ws/"
> 
> And of course the installation process doesn't find the file.zip file and throw a 404 error. The funny think is that after updating the permission to the /var/folder/ recursively, the process try to do the same but this time pointing to another folfer "/tmp/..." folder. BY doing the same, the process try to download the zip file into a temp folder created into the ios subfolder of the proyect that is trying to setup. Everytime the intallation process point to a different temp folder and it doesn't matter if the parent folder has setup the read&wite permissions recuresiverly. The process fails one and over again

did you ever fix this? i can't seem to fix the issue

**Comment by Jairwin-L** [comment]
is there a specific solution for this? this is my error message
```bash
[!] Error installing OpenSSL-Universal
[!] /usr/bin/unzip /var/folders/gy/6rw5t14n7wbf2hq4c961ww3h0000gn/T/d20230402-87422-rb3bmf/file.zip -d /var/folders/gy/6rw5t14n7wbf2hq4c961ww3h0000gn/T/d20230402-87422-rb3bmf

Archive:  /var/folders/gy/6rw5t14n7wbf2hq4c961ww3h0000gn/T/d20230402-87422-rb3bmf/file.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /var/folders/gy/6rw5t14n7wbf2hq4c961ww3h0000gn/T/d20230402-87422-rb3bmf/file.zip or
        /var/folders/gy/6rw5t14n7wbf2hq4c961ww3h0000gn/T/d20230402-87422-rb3bmf/file.zip.zip, and cannot find /var/folders/gy/6rw5t14n7wbf2hq4c961ww3h0000gn/T/d20230402-87422-rb3bmf/file.zip.ZIP, period.
```

**Comment by pvev** [comment]
> Still facing the same problem while trying to install pods:
> 
> ... Installing OpenSSL-Universal (1.1.1100)
> 
> [!] Error installing OpenSSL-Universal [!] /usr/bin/curl -f -L -o /var/folders/6y/sncz7wyx0992ytrjcwdz3v_r0000gn/T/d20230811-19451-1vci0r2/file.zip https://github.com/krzyzanowskim/OpenSSL/archive/1.1.1100.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.11.3 cocoapods-downloader/1.6.3'
> 
> % Total % Received % Xferd Average Speed Time Time Time Current Dload Upload Total Spent Left Speed 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0 curl: (22) The requested URL returned error: 401
> 
> [!] Do not use "pod install" from inside Rosetta2 (x86_64 emulation on arm64).
> 
> [!] - Emulated x86_64 is slower than native arm64
> 
> [!] - May result in mixed architectures in rubygems (eg: ffi_c.bundle files may be x86_64 with an arm64 interpreter)
> 
> [!] Run "env /usr/bin/arch -arm64 /bin/bash --login" then try again.
> 
> Env: MacOS Ventura 13.1 - M1 Max
> 
> did you ever find a solution @mariogruizdiaz ?

I just found the solution, the `--netrc-optional` option provided as part of the curl command was trying to pull the credentials contained in a old and unused `.netrc` file I had in my root dir, so just by removing this file (or if you need it, just temporarily rename it) I was able to run the pod install successfully.

**Comment by eBN-zzz** [comment]
sudo pod install --allow-root 可以解决问题

**Comment by rlhk** [comment]
Apparently custom `~/.curlrc` might cause the issue. I just renamed the file to resolve the error.

**Comment by yepe326** [comment]
> sudo pod install --allow-root 可以解決 太好了～成功了
