### ISSUE TITLE
[RN 0.69.1] - [Android] - Task :react-native-webview:compileReleaseKotlin FAILED

### ISSUE THREAD

**Issue by 19424056** [facebook/react-native#34152]
### Description

I can't compile android after upgrade RN form 0.68.2 to 0.69.1
I have tested for ios, works well

follow this website
https://react-native-community.github.io/upgrade-helper/?from=0.68.2&to=0.69.1

error appears in log :
> **Task :react-native-webview:compileReleaseKotlin FAILED**
e: Incompatible classes were found in dependencies. Remove them from the classpath or use '-Xskip-metadata-version-check' to suppress errors
e: /Users/194240/.gradle/caches/transforms-3/0b3ac82efd5eb9b138293354dbcbb483/transformed/jetified-kotlin-stdlib-jdk7-1.6.10.jar!/META-INF/kotlin-stdlib-jdk7.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
e: /Users/194240/.gradle/caches/transforms-3/3ad98ea5089aa7f57c6e123d9abb2142/transformed/jetified-kotlin-stdlib-jdk8-1.6.10.jar!/META-INF/kotlin-stdlib-jdk8.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
e: /Users/194240/.gradle/caches/transforms-3/83eb5f1a326602d40cd52eca35326f0b/transformed/jetified-kotlin-stdlib-common-1.6.10.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
e: /Users/194240/.gradle/caches/transforms-3/ae37e35be4f81fd0dc3858a055644750/transformed/jetified-kotlin-stdlib-1.6.10.jar!/META-INF/kotlin-stdlib.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
e: /Users/194240/.gradle/caches/transforms-3/e145c0d8e896cb82841e2180aff0493b/transformed/jetified-react-native-0.69.1-release-api.jar!/META-INF/ReactAndroid_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
e: /Users/procject/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewPackage.kt: (8, 77): Unresolved reference: listOf
e: /Users/procject/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewPackage.kt: (12, 76): Unresolved reference: listOf
e: /Users/procject/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/events/TopHttpErrorEvent.kt: (23, 21): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
The class is loaded from /Users/194240/.gradle/caches/transforms-3/ae37e35be4f81fd0dc3858a055644750/transformed/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: /Users/procject/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/events/TopLoadingErrorEvent.kt: (23, 21): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
The class is loaded from /Users/194240/.gradle/caches/transforms-3/ae37e35be4f81fd0dc3858a055644750/transformed/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: /Users/procject/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/events/TopLoadingFinishEvent.kt: (23, 21): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
The class is loaded from /Users/194240/.gradle/caches/transforms-3/ae37e35be4f81fd0dc3858a055644750/transformed/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: /Users/procject/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/events/TopLoadingProgressEvent.kt: (23, 21): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
The class is loaded from /Users/194240/.gradle/caches/transforms-3/ae37e35be4f81fd0dc3858a055644750/transformed/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: /Users/procject/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/events/TopLoadingStartEvent.kt: (23, 21): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
The class is loaded from /Users/194240/.gradle/caches/transforms-3/ae37e35be4f81fd0dc3858a055644750/transformed/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: /Users/procject/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/events/TopMessageEvent.kt: (22, 21): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
The class is loaded from /Users/194240/.gradle/caches/transforms-3/ae37e35be4f81fd0dc3858a055644750/transformed/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: /Users/procject/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/events/TopRenderProcessGoneEvent.kt: (24, 21): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
The class is loaded from /Users/194240/.gradle/caches/transforms-3/ae37e35be4f81fd0dc3858a055644750/transformed/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: /Users/procject/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/events/TopShouldStartLoadWithRequestEvent.kt: (16, 11): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
The class is loaded from /Users/194240/.gradle/caches/transforms-3/ae37e35be4f81fd0dc3858a055644750/transformed/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: /Users/procject/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/events/TopShouldStartLoadWithRequestEvent.kt: (18, 11): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
The class is loaded from /Users/194240/.gradle/caches/transforms-3/ae37e35be4f81fd0dc3858a055644750/transformed/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: /Users/procject/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/events/TopShouldStartLoadWithRequestEvent.kt: (28, 21): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
The class is loaded from /Users/194240/.gradle/caches/transforms-3/ae37e35be4f81fd0dc3858a055644750/transformed/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-webview:compileReleaseKotlin'.
> Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 40s

### Version

0.69.1

### Output of `npx react-native info`

System:
    OS: macOS 12.0.1
    CPU: (8) arm64 Apple M1
    Memory: 93.42 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.2.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.9.0 - /usr/local/bin/npm
    Watchman: 2022.05.23.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8512546
    Xcode: 13.4/13F17a - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.1 => 0.69.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
    
    
npmPackages:
    react (18.0.0)
    react-native (0.69.1)
    react-native-webview (11.22.4)
    expo 45.0.6
    expo-application (4.1.0)
    expo-constants (13.1.1)
    expo-file-system (14.0.0)
    expo-font (10.1.0)
    expo-image-loader (3.2.0)
    expo-image-manipulator (10.3.1)
    expo-in-app-purchases (13.0.0)
    expo-location (14.2.2)
    expo-modules-core (0.9.2)
   
    AGP version is 7.4.2
    classpath("com.android.tools.build:gradle:7.1.1")
    classpath("com.facebook.react:react-native-gradle-plugin")
    classpath("de.undercouch:gradle-download-task:5.0.1")

### Steps to reproduce
https://github.com/19424056/TestProjectWebView

Just upgrade to RN 0.69.1

### Snack, code example, screenshot, or link to a repository
https://github.com/19424056/TestProjectWebView

 npx react-native init TestProjectWebView
 yarn add react-native-webview
 
 cd android
 ./gradlew app:assembleRelease    or    npx react-native run-android
 
 FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-webview:compileReleaseKotlin'.
> Compilation error. See log for more details

**Comment by 19424056** [comment]
I need your help @Kudo kudo

**Comment by buidinhmanh14799** [comment]
same issue here. please help me

**Comment by henrik-d** [comment]
I think this is the same issue https://github.com/react-native-webview/react-native-webview/issues/2578

**Comment by 19424056** [comment]
> I think this is the same issue [react-native-webview/react-native-webview#2578](https://github.com/react-native-webview/react-native-webview/issues/2578)

link to a repository, please help me
https://github.com/19424056/TestProjectWebView

**Comment by henrik-d** [comment]
@19424056 
Adding 
```
buildscript {
    ext {
        buildToolsVersion = "31.0.0"
        minSdkVersion = 21
        compileSdkVersion = 31
        targetSdkVersion = 31
        kotlinVersion = "1.6.0" // <- add this line
       
       ...
   }
   ...
}
```
 in `android/build.gradle` will fix it. Not sure though if this is the best solution.

**Comment by 19424056** [comment]
thanks @henrik-d it working as a charm

**Comment by 19424056** [comment]
thanks @henrik-d it working as a charm
