### ISSUE TITLE
ReferenceError: Can't find variable: Intl

### ISSUE THREAD

**Issue by abisalde** [facebook/react-native#34162]
### Description

I wrote a simple JavaScript inbuilt function to format currency and got the error.

 ```
ReferenceError: Can't find variable: Intl
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
``

`
Currency = new Intl.NumberFormat("en-NG", {
  style: "currency",
  currency: "NGN",
});
`


### Version

0.68.2

### Output of `npx react-native info`

System:
    OS: Linux 5.15 Manjaro Linux
    CPU: (4) x64 Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz
    Memory: 5.53 GB / 15.52 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.3.0 - /usr/bin/node
    Yarn: 1.22.19 - ~/.local/bin/yarn
    npm: 8.6.0 - /usr/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: AI-212.5712.43.2112.8609683
  Languages:
    Java: 18.0.1.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.2 => 0.68.2 
  npmGlobalPackages:
    *react-native*: Not Found


### Steps to reproduce

Writing a JavaScript inbuilt function to format strings into currency

### Snack, code example, screenshot, or link to a repository


Currency = new Intl.NumberFormat("en-NG", {
  style: "currency",
  currency: "NGN",
});

<Text h1 center>{Currency.format(0)}</Text>

**Comment by komorebi64** [comment]
I also have this problemDoes React Native currently not support Intl?

**Comment by komorebi64** [comment]
> npx react-native info

System:
    OS: Windows 10 10.0.22000
    CPU: (12) x64 Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
    Memory: 507.41 MB / 15.75 GB
  Binaries:
    Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: Not Found
  Languages:
    Java: 1.8.0_202 - D:\Java\jdk-8.0.2\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.2 => 0.68.2 
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by cortinico** [comment]
Which JS engine are you using?

**Comment by kierangillen** [comment]
I'm not getting an error with `Int` but when I use `minimumSignificantDigits` or `maximumSignificantDigits` they have no effect:

```
        Intl.NumberFormat("en", {
          minimumSignificantDigits: 1,
          maximumSignificantDigits: 6,
        }).format(value)
```

**Comment by cortinico** [comment]
Hey @abisalde 
I'm closing this issue due to lack of response. I suppose you found a workaround or solved your issue. Feel free to re-open it or create a new issue if the problem persists.
Thanks

**Comment by alexkendall** [comment]
I have the same issue.

**Comment by cortinico** [comment]
> I have the same issue.

Please open a new issue, provide your code or a reproducer and we can help you over there. Thank you 👍
