### ISSUE TITLE
[PushNotificationIOS][Improvement] Handle push notification launch from background state vs active state

### ISSUE THREAD

**Issue by justinmakaila** [facebook/react-native#3416]
All,
I ran into issues while using `PushNotificationIOS` with distinguishing between a push notification launch from the background state vs a launch from the active state. In the `notification` event handler, I couldn't determine if the app was coming from the background or was active the entire time.

I ended up building a workaround into my AppDelegate which looks like this:
```
- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo {
  NSMutableDictionary *notificationUserInfo = [userInfo mutableCopy];
  [notificationUserInfo setValue:@(application.applicationState) forKey:@"applicationState"];
  
  [RCTPushNotificationManager application:application didReceiveRemoteNotification:notificationUserInfo];
}
```
and handling the notification in my `js` like so:
```
  _onPushNotification(notification) {
    const {
      receivePushNotification,
    } = this.props

    const notificationData = notification.getData()
    const notificationApplicationState = notificationData.applicationState

    // If the application state at the time of receiving the notification is
    // UIApplicationState.Inactive (1) or UIApplicationState.Background (2),
    // display the notification to the user
    if (notificationApplicationState == UIApplicationStateInactive
        || notificationApplicationState == UIApplicationStateBackground) {
      this.displayNotification(notification)
    }

    receivePushNotification(notification)
  }
```

I think it'd be ideal for `RCTPushNotificationManager` to include a key which has the application state included. I'm open to suggestions for a pure RN way, or some guidance on how the community would like to see this handled.

**Comment by javache** [comment]
You can use `AppStateIOS.currentState` to get the same information, and subscribe to that separately if you want to receive updates.

Feel free to re-open this issue if that approach doesn't work for you.

**Comment by justinmakaila** [comment]
Pieter,

I tried that, but the AppState handler would get called after the notification observer already fired, and it would indicate an active state. It may be worth mentioning that it transitioned from active to background when I go to the home screen, and then active to active on launch.



—Justin Makaila

**Comment by grabbou** [comment]
I can confirm that @javache solution works prefectly. If `AppStateIOS.currentState` is `background` - it means notification handler has been clicked when application was not in the foreground (hah, pretty obvious)

**Comment by joshuapinter** [comment]
Just an update with some code for `AppState`: 

```js
_onPushNotification(notification) {
  if (AppState.currentState != 'active') {
    console.log('Launched from notification');
  } 
  else {
    console.log('Not launched from notification');
  }
}
```
