### ISSUE TITLE
RNAdmobNativeAdsManager.java:42: error: getCurrentActivity() is not public in ReactContext; cannot be accessed from outside package

### ISSUE THREAD

**Issue by aleluiah** [facebook/react-native#34169]
### Description

() is not public in ReactContext; cannot be accessed from outside package
        Context context = getReactApplicationContext().getCurrentActivity();
                                                      ^
C:\Cliqueon\node_modules\react-native-admob-native-ads\android\src\main\java\com\ammarahmed\rnadmob\nativeads\RNAdmobNativeAdsManager.java:70: error: cannot find symbol
            configuration.setTestDeviceIds(Arguments.toList(config.getArray("testDeviceIds")));
                                                    ^
  symbol:   method toList(ReadableArray)
  location: class Arguments
C:\Cliqueon\node_modules\react-native-admob-native-ads\android\src\main\java\com\ammarahmed\rnadmob\nativeads\Utils.java:29: error: cannot find symbol
                    List list = Arguments.toList(target.getArray("value"));
                                         ^
  symbol:   method toList(ReadableArray)
  location: class Arguments
C:\Cliqueon\node_modules\react-native-admob-native-ads\android\src\main\java\com\ammarahmed\rnadmob\nativeads\Utils.java:58: error: cannot find symbol
            List list = Arguments.toList(options.getArray("neighboringContentUrls"));
                                 ^
  symbol:   method toList(ReadableArray)
  location: class Arguments

### Version

0.69.1

### Output of `npx react-native info`

C:\Cliqueon\node_modules\react-native-admob-native-ads\android\src\main\java\com\ammarahmed\rnadmob\nativeads\RNAdmobNativeAdsManager.java:42: error: getCurrentActivity() is not public in ReactContext; cannot be accessed from outside package
        Context context = getReactApplicationContext().getCurrentActivity();
                                                      ^
C:\Cliqueon\node_modules\react-native-admob-native-ads\android\src\main\java\com\ammarahmed\rnadmob\nativeads\RNAdmobNativeAdsManager.java:70: error: cannot find symbol
            configuration.setTestDeviceIds(Arguments.toList(config.getArray("testDeviceIds")));
                                                    ^
  symbol:   method toList(ReadableArray)
  location: class Arguments
C:\Cliqueon\node_modules\react-native-admob-native-ads\android\src\main\java\com\ammarahmed\rnadmob\nativeads\Utils.java:29: error: cannot find symbol
                    List list = Arguments.toList(target.getArray("value"));
                                         ^
  symbol:   method toList(ReadableArray)
  location: class Arguments
C:\Cliqueon\node_modules\react-native-admob-native-ads\android\src\main\java\com\ammarahmed\rnadmob\nativeads\Utils.java:58: error: cannot find symbol
            List list = Arguments.toList(options.getArray("neighboringContentUrls"));
                                 ^
  symbol:   method toList(ReadableArray)

### Steps to reproduce

npx react-native run-android on fabric with new architecture enable
![justnow](https://user-images.githubusercontent.com/65899491/178162178-b21a3ea8-178f-4a25-ac35-d35b6a324177.jpg)
d

### Snack, code example, screenshot, or link to a repository

![justnow](https://user-images.githubusercontent.com/65899491/178162180-a71de9cf-d0e9-4a5e-8c1a-5eda986bcd9a.jpg)

**Comment by cortinico** [comment]
Closing as your code is impossible to read and/or copy.
Please provide a reproducer in form of a repository that we can run and reopen
