### ISSUE TITLE
Facing Issue with new Architecture using (Microsoft Visual Studio 2022, CMake)  Task :ReactAndroid:hermes-engine:buildHermes FAILED  FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by gunjantaazaa** [facebook/react-native#34175]
### Description

Getting this issue while running android build. 
I have already check with gradle clean but failed.

Using Windows 10 built-in ICU
Warning: NMake does not support parallel builds. Ignoring parallel build command line option.
NMAKE : fatal error U1077: 'C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1432~1.313\bin\Hostx86\x86\cl.exe' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\bin\HostX86\x86\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\bin\HostX86\x86\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\bin\HostX86\x86\nmake.exe"' : return code '0x2'
Stop.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':ReactAndroid:hermes-engine:buildHermes'.
> Process 'command 'cmd'' finished with non-zero exit value 2

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

### Version

0.69.1

### Output of `npx react-native info`
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 AMD Ryzen 7 5700U with Radeon Graphics
    Memory: 734.17 MB / 7.34 GB
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.5.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version     2021.1.0.0 AI-211.7628.21.2111.8309675
    Visual Studio: 17.2.32616.157 (Visual Studio Community 2022)
  Languages:
    Java: 11.0.12
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0
    react-native: 0.69.1 => 0.69.1
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Environment configured with Java 11 and node 16.13.0
Install cmake with Set path on System Variable.
Install Visual Studio 2022
Open terminal in Visual Studio 2022.
Run command npx react-native run-android

### Snack, code example, screenshot, or link to a repository

I have also enableHermes but still not works

**Comment by rafaelfrancisco-dev** [comment]
Facing same issue here

**Comment by deepanshu770** [comment]
Same Issue in with me

**Comment by deepanshu770** [comment]
> Task :ReactAndroid:hermes-engine:configureBuildForHermes FAILED
-- Building for: NMake Makefiles
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
-- Configuring incomplete, errors occurred!
See also "C:/Users/Deepu/Desktop/New Arch/DaySchedule2/node_modules/react-native/ReactAndroid/hermes-engine/build/hermes/CMakeFiles/CMakeOutput.log".
See also "C:/Users/Deepu/Desktop/New Arch/DaySchedule2/node_modules/react-native/ReactAndroid/hermes-engine/build/hermes/CMakeFiles/CMakeError.log".

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings
25 actionable tasks: 25 executed
Note: C:\Users\Deepu\Desktop\New Arch\DaySchedule2\node_modules\react-native-gradle-plugin\src\main\java\com\facebook\react\codegen\generator\SchemaJsonParser.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
CMake Deprecation Warning at CMakeLists.txt:42 (cmake_policy):
  The OLD behavior for policy CMP0026 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


CMake Error at CMakeLists.txt:64 (project):
  The CMAKE_C_COMPILER:

    cl

  is not a full path and was not found in the PATH.

  To use the NMake generator with Visual C++, cmake must be run from a shell
  that can use the compiler cl from the command line.  This environment is
  unable to invoke the cl compiler.  To fix this problem, run cmake from the
  Visual Studio Command Prompt (vcvarsall.bat).

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


CMake Error at CMakeLists.txt:64 (project):
  The CMAKE_CXX_COMPILER:

    cl

  is not a full path and was not found in the PATH.

  To use the NMake generator with Visual C++, cmake must be run from a shell
  that can use the compiler cl from the command line.  This environment is
  unable to invoke the cl compiler.  To fix this problem, run cmake from the
  Visual Studio Command Prompt (vcvarsall.bat).

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.



FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':ReactAndroid:hermes-engine:configureBuildForHermes'.
> Process 'command 'cmd'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 33s

**Comment by cortinico** [comment]
> NMAKE : fatal error U1077: '"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\bin\HostX86\x86\nmake.exe"' : return code '0x2'

I'm not entirely sure why you're seeing this error code. According [to this article](https://www.ibm.com/support/pages/error-nmake-fatal-error-u1077-cl-return-code-0x80#:~:text=Answer%3A,correctly%20or%20use%20another%20compiler.) it seems like your Visual Studio installation is not complete and needs to be re-installed. Can you try to do so.

**Comment by HussainArif12** [comment]
Facing the same issue here as well. Here's what I tried to do to fix it:
- Reinstall Android SDK and NDK
- Reinstall Visual Studio and build tools
- Create a blank project and then enable fabric.
However, I still failed to resolve the issue.
Platform: Windows 10

**Comment by fr-an-k** [comment]
I have the same issue with a fresh Build Tools install, CL version 19.34.31933 for x86

**Comment by BubbleTrouble14** [comment]
Same issue here as well. Cant get react native 0.70.5 to run on windows

**Comment by cortinico** [comment]
> Task :ReactAndroid:hermes-engine:buildHermes FAILED FAILURE: Build failed with an exception

This issue is fixed in React Native 0.71 (as this task won't be executing anymore).
Please migrate to 0.71 and try again. If the issue persists, open a new issue. Thank you
