### ISSUE TITLE
Windows support long path in installed packages

### ISSUE THREAD

**Issue by aleluiah** [facebook/react-native#34174]
### Description

Although by using a pr fix in react.gradle (hermes.exe) seem to solve the hermes.exe not found issue on windows and the build is successful. but after installing react-native-gesture-handler with new architecture the build fails due to windows long path limit.

Task :react-native-gesture-handler:buildNdkBuildDebug[arm64-v8a][rngesturehandler_modules]
C/C++: C:/android-ndk-r21e/build//../toolchains/llvm/prebuilt/windows-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin\ld: cannot find C:\Cliqueon\node_modules\react-native-gesture-handler\android\build\intermediates\cxx\Debug\3x5p2864/obj/local/arm64-v8a/objs-debug/rngesturehandler_modules/C_/Cliqueon/node_modules/react-native-gesture-handler/android/src/main/jni/RNGestureHandlerComponentsRegistry.o: No such file or directory
C/C++: clang++: error: linker command failed with exit code 1 (use -v to see invocation)
C/C++: make: *** [C:/android-ndk-r21e/build//../build/core/build-binary.mk:725: C:\Cliqueon\node_modules\react-native-gesture-handler\android\build\intermediates\cxx\Debug\3x5p2864/obj/local/arm64-v8a/librngesturehandler_modules.so] Error

### Version

0.69.1

### Output of `npx react-native info`

Task :react-native-gesture-handler:buildNdkBuildDebug[arm64-v8a][rngesturehandler_modules]
C/C++: C:/android-ndk-r21e/build//../toolchains/llvm/prebuilt/windows-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin\ld: cannot find C:\Cliqueon\node_modules\react-native-gesture-handler\android\build\intermediates\cxx\Debug\3x5p2864/obj/local/arm64-v8a/objs-debug/rngesturehandler_modules/C_/Cliqueon/node_modules/react-native-gesture-handler/android/src/main/jni/RNGestureHandlerComponentsRegistry.o: No such file or directory
C/C++: clang++: error: linker command failed with exit code 1 (use -v to see invocation)
C/C++: make: *** [C:/android-ndk-r21e/build//../build/core/build-binary.mk:725: C:\Cliqueon\node_modules\react-native-gesture-handler\android\build\intermediates\cxx\Debug\3x5p2864/obj/local/arm64-v8a/librngesturehandler_modules.so] Error

### Steps to reproduce

![kk](https://user-images.githubusercontent.com/65899491/178366997-d3c67d45-442a-4a0e-84d2-420802d44289.jpg)

### Snack, code example, screenshot, or link to a repository

https://stackoverflow.com/questions/51226596/gradle-file-paths-too-long-for-windows

**Comment by cortinico** [comment]
You should open this issue against https://github.com/software-mansion/react-native-gesture-handler/

The issue is in this file: https://github.com/software-mansion/react-native-gesture-handler/blob/main/android/src/main/jni/Android.mk

They should either:
- Migrate to CMake 
- Apply the fix for Long Paths on Windows, like we did here https://github.com/facebook/react-native/pull/33707
