### ISSUE TITLE
[iOS][TextInput] Space doesn't switch back to default keyboard type

### ISSUE THREAD

**Issue by tomskopek** [facebook/react-native#34179]
### Description

Clicking space bar on the iOS numbers-and-punctuation type should switch to the iOS default type.
But it doesn't work as expected on TextInput.
What I found so far is

1. if you have value prop, it doesn't work.
2. if you have value and set multiline true, it works.
3. if you don't have value prop, it works

Refer to [here](https://lefkowitz.me/visual-guide-to-react-native-textinput-keyboardtype-options/) to see how each type looks.
Refer to [here](https://discussions.apple.com/thread/2417454?threadID=2417454) to understand better this behavior

Note: This a copy of [this ticket](https://github.com/facebook/react-native/issues/29216) which was closed by stalebot, but it still an issue

### Version

0.68.2

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 12.2.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 638.58 MB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.19.0 - ~/.nvm/versions/node/v16.14.0/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
    Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /Users/tom/.gem/ruby/3.1.1/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 30, 31, 32
      Build Tools: 30.0.2
      System Images: android-29 | Google APIs ARM 64 v8a, android-29 | Google Play ARM 64 v8a, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play ARM 64 v8a, android-32 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.68.2 => 0.68.2
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. Go to https://snack.expo.dev/yUoBqe3mk (it's a copy of https://reactnative.dev/docs/textinput snack example)
2. Run the code on iOS
3. Type some number and symbol, then type space
4. Confirm that it doesn't switch back to the default type
5. pass multiline prop in source code
6. Repeat number 3
7. Confirm that it switches back to the default
8. Remove value and multiline props
9. Repeat number 3, 7

### Snack, code example, screenshot, or link to a repository

https://snack.expo.dev/yUoBqe3mk

**Comment by ernestasgobionis** [comment]
Having the same issue

**Comment by cortinico** [comment]
> The info is right there ☝️... unless I'm mistaken? @cortinico

Yeah you're right, that's why I removed those labels :)

**Comment by tomskopek** [comment]
Oops, I misread 🤦‍♂️
Thanks!

**Comment by rdgomt** [comment]
I am developing a chat app and this feature would be nice to have.

**Comment by tomskopek** [comment]
Reopen?
