### ISSUE TITLE
Modal on iOS freeze and block app when use LayoutAnimation with presentationStyle prop not setted to fullscreen

### ISSUE THREAD

**Issue by Deodes** [facebook/react-native#34184]
### Description

Every time when I set modal's visibility to `false` with 

`transparent={true}` or

 `presentationStyle={'pageSheet' / 'formSheet' / 'overFullScreen'}` on iOS and before it I use 

`LayoutAnimation.easeInEaseOut();` 

Modal becomes visible and freeze mobile application. This is an old bug that hasn't been fixed for a long time..

### Version

* <=0.68.1 > *

### Output of `npx react-native info`

System:
    OS: macOS 12.3.1
    CPU: (8) arm64 Apple M1
    Memory: 124.75 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.0.0 - /opt/homebrew/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.6.0 - /opt/homebrew/bin/npm
    Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 23, 28, 29, 30, 31
      Build Tools: 29.0.2, 30.0.2, 31.0.0
      System Images: android-29 | ARM 64 v8a, android-29 | Intel x86 Atom_64, android-29 | Google APIs ARM 64 v8a, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play ARM 64 v8a, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play ARM 64 v8a, android-31 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7784292
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.1 => 0.68.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

You can just use code example below..

1. Provide `transparent={true}` on `<Modal>`
2. Use `LayoutAnimation.easeInEaseOut();` before setting modal visible to `true` and/or use `LayoutAnimation.easeInEaseOut();` when setting modal visible to `false`
3. Modal freeze

### Snack, code example, screenshot, or link to a repository

```
import React, {useState} from 'react';
import {
  StyleSheet,
  Modal,
  View,
  Text,
  Pressable,
  LayoutAnimation,
} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';

const Home = () => {
  const [visible, setVisible] = useState(false);
  const [anim, setAnim] = useState(false);

  return (
    <SafeAreaView style={styles.container}>
      <Pressable
        onPress={() => {
          LayoutAnimation.easeInEaseOut();
          setAnim(true);
        }}>
        {!anim && <Text>PRESS LAYOUT</Text>}
      </Pressable>
      {!anim && <Text>PLACEHOLDER TEXT</Text>}
      {!anim && <Text>PLACEHOLDER TEXT</Text>}
      {!anim && <Text>PLACEHOLDER TEXT</Text>}
      <Pressable
        onPress={() => {
          LayoutAnimation.easeInEaseOut();
          setVisible(true);
        }}>
        <Text>PRESS VISIBLE</Text>
      </Pressable>
      <Modal visible={visible} animationType={'fade'} transparent>
        <View style={styles.modal}>
          <Pressable
            onPress={() => {
              LayoutAnimation.easeInEaseOut();
              setAnim(false);
              setVisible(false);
            }}>
            <Text>PRESS</Text>
          </Pressable>
        </View>
      </Modal>
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modal: {
    width: 300,
    height: 300,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'pink',
  },
});

export default Home;
```

**Comment by dishantwalia** [comment]
https://github.com/facebook/react-native/issues/34018#issuecomment-1209286537

**Comment by fivecar** [comment]
Indeed, it doesn't seem like it has to do with `overFullScreen`, but instead happens whenever `transparent: true`, as @dishantwalia mentions above.

**Comment by anatooly** [comment]
Actual problem for 0.70.7

nothing help
animationType="fade" - app freeze and popup stay gray
animationType="none" - app freeze and popup show again
wrapper View not help

only transparent: false fix it

**Comment by anastasia-son** [comment]
I have the same issue. Modal is used inside swiper-carousel. When used outside carousel it works perfectly fine.

**Comment by camarasidi12** [comment]
I have facing this issue it's du to animationType="fade" so if IOS set it to None

`animationType="none"
`

**Comment by GuoXiaoyang** [comment]
Same issue here. Any progress?

**Comment by stianjensen** [comment]
This is not stale.
