### ISSUE TITLE
TypeScript files not compiled, uses .JS extension

### ISSUE THREAD

**Issue by ecnepsnai** [facebook/react-native#34199]
### Description

While trying to troubleshoot why an React Native iOS app wouldn't launch due to a JS syntax error, I discovered that there are some TypeScript files within React's Libraries that weren't being compiled, and that these TypeScript files incorrectly use `.js` extensions.

I admit I have no clue if this is intended or not, but I was able to identify that the following `.js` files are, in fact, TypeScript - and at least in the case of my app, it wasn't being compiled correctly.

https://github.com/facebook/react-native/tree/main/Libraries/Blob

### Version

0.69.1

### Output of `npx react-native info`

N/A

### Steps to reproduce

N/A

### Snack, code example, screenshot, or link to a repository

N/A

**Comment by ecnepsnai** [comment]
Related: https://stackoverflow.com/questions/70662596/react-native-build-error-unexpected-token-punc-expected-punc-in-file

**Comment by faheem-cmd** [comment]
you should save the typescript file in .tsx format

**Comment by cortinico** [comment]
> but I was able to identify that the following `.js` files are, in fact, TypeScript

Which file specifically?

**Comment by ecnepsnai** [comment]
@cortinico Apologies, I didnt word that clearly. All of the .js files in that directory are actually typescript files.

**Comment by cortinico** [comment]
> All of the .js files in that directory are actually typescript files.

They're actually Flow files (https://flow.org/)

**Comment by ecnepsnai** [comment]
Ah, I see. Reading Flow's docs it appears that despite Flow files not being JavaScript they still want you to use .js extensions.

That's... a choice.

Either way I'll close this issue since I suppose it's by design that the file extensions are incorrect.
