### ISSUE TITLE
Task :ReactAndroid:buildCMakeDebug[arm64-v8a][fabricjni,hermes-executor-debug,etc] FAILED

### ISSUE THREAD

**Issue by deepanshu770** [facebook/react-native#34194]
### Description

I have created a fresh react native project to try New Architecture but end up with this error.

> Task :ReactAndroid:downloadBoost UP-TO-DATE
Download https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.gz

> Task :ReactAndroid:downloadDoubleConversion UP-TO-DATE
Download https://github.com/google/double-conversion/archive/v1.1.6.tar.gz

> Task :ReactAndroid:downloadFmt UP-TO-DATE
Download https://github.com/fmtlib/fmt/archive/6.2.1.tar.gz

> Task :ReactAndroid:downloadFolly UP-TO-DATE
Download https://github.com/facebook/folly/archive/v2021.06.28.00.tar.gz

> Task :ReactAndroid:downloadGlog UP-TO-DATE
Download https://github.com/google/glog/archive/v0.3.5.tar.gz

> Task :ReactAndroid:downloadLibevent UP-TO-DATE
Download https://github.com/libevent/libevent/releases/download/release-2.1.12-stable/libevent-2.1.12-stable.tar.gz

> Task :ReactAndroid:hermes-engine:downloadHermes UP-TO-DATE
Download https://github.com/facebook/hermes/tarball/hermes-2022-05-20-RNv0.69.0-ee8941b8874132b8f83e4486b63ed5c19fc3f111

> Task :ReactAndroid:hermes-engine:configureBuildForHermes
-- Found the following ICU libraries:
--   uc (required)
--   i18n (required)
--   uc (required)
-- The following ICU libraries were not found:
--   data (required)
-- Failed to find all ICU components (missing: ICU_INCLUDE_DIR _ICU_REQUIRED_LIBS_FOUND) (Required is at least version "52")
-- Could NOT find Backtrace (missing: Backtrace_LIBRARY Backtrace_INCLUDE_DIR)
-- Threads enabled.
-- Doxygen disabled.
-- Go bindings disabled.
-- Could NOT find Python module pygments
-- Could NOT find Python module pygments.lexers.c_cpp
-- Could NOT find Python module yaml
-- CMAKE_HOST_SYSTEM_NAME = Windows
-- CMAKE_SYSTEM_NAME = Windows
-- HERMES_APPLE_TARGET_PLATFORM =
-- CMAKE_CROSSCOMPILING = FALSE
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/Deepu/Desktop/Testing/node_modules/react-native/ReactAndroid/hermes-engine/build/hermes

> Task :ReactAndroid:hermes-engine:buildHermes
[  0%] Built target LLVHDemangle
[ 25%] Built target LLVHSupport
[ 38%] Built target hermesOptimizer
[ 38%] Built target hermesFrontEndDefs
[ 41%] Built target hermesPlatformUnicode
[ 45%] Built target hermesRegex
[ 48%] Built target dtoa
[ 58%] Built target hermesSupport
[ 61%] Built target hermesAST
[ 64%] Built target hermesParser
[ 74%] Built target hermesFrontend
[ 74%] Built target hermesInst
[ 77%] Built target hermesAST2JS
[ 77%] Built target hermesADT
[ 77%] Built target hermesFlowParser
[ 80%] Built target hermesSourceMap
[ 83%] Built target hermesBackend
[ 96%] Built target hermesHBCBackend
[100%] Built target zip
[100%] Built target hermesCompilerDriver
[100%] Built target hermesc

> Task :ReactAndroid:buildCMakeDebug[arm64-v8a][fabricjni,hermes-executor-debug,etc] FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings
40 actionable tasks: 13 executed, 27 up-to-date
CMake Deprecation Warning at CMakeLists.txt:42 (cmake_policy):
  The OLD behavior for policy CMP0026 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

Using Windows 10 built-in ICU
Warning: NMake does not support parallel builds. Ignoring parallel build command line option.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':ReactAndroid:buildCMakeDebug[arm64-v8a][fabricjni,hermes-executor-debug,etc]'.
> Build command failed.
  Error while executing process C:\Users\Deepu\AppData\Local\Android\Sdk\cmake\3.18.1\bin\ninja.exe with arguments {-C C:\Users\Deepu\Desktop\Testing\node_modules\react-native\ReactAndroid\.cxx\Debug\3h3m3m6s\arm64-v8a fabricjni hermes-executor-debug jscexecutor jsijniprofiler reactnativeblob reactnativejni reactperfloggerjni turbomodulejsijni}
  ninja: Entering directory `C:\Users\Deepu\Desktop\Testing\node_modules\react-native\ReactAndroid\.cxx\Debug\3h3m3m6s\arm64-v8a'
  [0/2] Re-checking globbed directories...
  [1/3] Building CXX object ReactCommon/react/renderer/components/progressbar/CMakeFiles/rrc_progressbar.dir/android/react/renderer/components/progressbar/AndroidProgressBarMeasurementsManager.cpp.o
  [2/3] Linking CXX static library ReactCommon\react\renderer\components\progressbar\librrc_progressbar.a
  FAILED: ReactCommon/react/renderer/components/progressbar/librrc_progressbar.a
  cmd.exe /C "cd . && C:\Users\Deepu\AppData\Local\Android\Sdk\cmake\3.18.1\bin\cmake.exe -E rm -f ReactCommon\react\renderer\components\progressbar\librrc_progressbar.a && C:\Users\Deepu\AppData\Local\Android\Sdk\ndk\21.4.7075529\toolchains\llvm\prebuilt\windows-x86_64\bin\aarch64-linux-android-ar.exe qc ReactCommon\react\renderer\components\progressbar\librrc_progressbar.a  @ReactCommon\react\renderer\components\progressbar\CMakeFiles\rrc_progressbar.rsp && C:\Users\Deepu\AppData\Local\Android\Sdk\ndk\21.4.7075529\toolchains\llvm\prebuilt\windows-x86_64\bin\aarch64-linux-android-ranlib.exe ReactCommon\react\renderer\components\progressbar\librrc_progressbar.a && cd ."
  C:\Users\Deepu\AppData\Local\Android\Sdk\ndk\21.4.7075529\toolchains\llvm\prebuilt\windows-x86_64\bin\aarch64-linux-android-ar.exe: ReactCommon/react/renderer/components/progressbar/CMakeFiles/rrc_progressbar.dir/android/react/renderer/components/progressbar/AndroidProgressBarMeasurementsManager.cpp.o: No such file or directory

  ninja: build stopped: subcommand failed.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 28s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
CMake Deprecation Warning at CMakeLists.txt:42 (cmake_policy):
  The OLD behavior for policy CMP0026 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

Using Windows 10 built-in ICU
Warning: NMake does not support parallel builds. Ignoring parallel build command line option.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':ReactAndroid:buildCMakeDebug[arm64-v8a][fabricjni,hermes-executor-debug,etc]'.
> Build command failed.
  Error while executing process C:\Users\Deepu\AppData\Local\Android\Sdk\cmake\3.18.1\bin\ninja.exe with arguments {-C C:\Users\Deepu\Desktop\Testing\node_modules\react-native\ReactAndroid\.cxx\Debug\3h3m3m6s\arm64-v8a fabricjni hermes-executor-debug jscexecutor jsijniprofiler reactnativeblob reactnativejni reactperfloggerjni turbomodulejsijni}
  ninja: Entering directory `C:\Users\Deepu\Desktop\Testing\node_modules\react-native\ReactAndroid\.cxx\Debug\3h3m3m6s\arm64-v8a'
  [0/2] Re-checking globbed directories...
  [1/3] Building CXX object ReactCommon/react/renderer/components/progressbar/CMakeFiles/rrc_progressbar.dir/android/react/renderer/components/progressbar/AndroidProgressBarMeasurementsManager.cpp.o
  [2/3] Linking CXX static library ReactCommon\react\renderer\components\progressbar\librrc_progressbar.a
  FAILED: ReactCommon/react/renderer/components/progressbar/librrc_progressbar.a
  cmd.exe /C "cd . && C:\Users\Deepu\AppData\Local\Android\Sdk\cmake\3.18.1\bin\cmake.exe -E rm -f ReactCommon\react\renderer\components\progressbar\librrc_progressbar.a && C:\Users\Deepu\AppData\Local\Android\Sdk\ndk\21.4.7075529\toolchains\llvm\prebuilt\windows-x86_64\bin\aarch64-linux-android-ar.exe qc ReactCommon\react\renderer\components\progressbar\librrc_progressbar.a  @ReactCommon\react\renderer\components\progressbar\CMakeFiles\rrc_progressbar.rsp && C:\Users\Deepu\AppData\Local\Android\Sdk\ndk\21.4.7075529\toolchains\llvm\prebuilt\windows-x86_64\bin\aarch64-linux-android-ranlib.exe ReactCommon\react\renderer\components\progressbar\librrc_progressbar.a && cd ."
  C:\Users\Deepu\AppData\Local\Android\Sdk\ndk\21.4.7075529\toolchains\llvm\prebuilt\windows-x86_64\bin\aarch64-linux-android-ar.exe: ReactCommon/react/renderer/components/progressbar/CMakeFiles/rrc_progressbar.dir/android/react/renderer/components/progressbar/AndroidProgressBarMeasurementsManager.cpp.o: No such file or directory

  ninja: build stopped: subcommand failed.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 28s

    at makeError (C:\Users\Deepu\Desktop\Testing\node_modules\execa\index.js:174:9)
    at C:\Users\Deepu\Desktop\Testing\node_modules\execa\index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async runOnAllDevices (C:\Users\Deepu\Desktop\Testing\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:109:5)
    at async Command.handleAction (C:\Users\Deepu\Desktop\Testing\node_modules\@react-native-community\cli\build\index.js:192:9)
info Run CLI with --verbose flag for more details.

### Version

0.69.1

### Output of `npx react-native info`

System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
    Memory: 613.43 MB / 7.84 GB
  Binaries:
    Node: 14.17.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.15 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.19041.0
  IDEs:
    Android Studio: AI-212.5712.43.2112.8609683
    Visual Studio: 17.2.32630.192 (Visual Studio Community 2022)
  Languages:
    Java: 11.0.15 - C:\Program Files\OpenJDK\openjdk-11.0.15_10\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0
    react-native: 0.69.1 => 0.69.1
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

After creating this project I only edit-

1.  `newArchEnabled=true` in gradle.properties.

2. `project.ext.react = [
    enableHermes: true
]
` in android/app/build.gradle

### Snack, code example, screenshot, or link to a repository

![image](https://user-images.githubusercontent.com/84296468/178942946-713f3c12-dff8-48b8-bab5-296fde432f90.png)

**Comment by Keki91** [comment]
Probably this issue: #34084 - still waiting for a fix.

**Comment by cocadev** [comment]
I am waiting for fix.

**Comment by patBeltrani** [comment]
someone fix this issue?
