### ISSUE TITLE
NativeSoundManager.playTouchSound() undefined is not a function

### ISSUE THREAD

**Issue by aleluiah** [facebook/react-native#34208]
### Description

A simple button element imported from react native will trigger an error when pressed with new arch enabled <Button onPress={() => alert('yeah')} title={visible ? 'Hide' : 'Show'} /> 

### Version

0.69.1

### Output of `npx react-native info`

NativeSoundManager.playTouchSound() undefined is not a function in node_modules/react-native/libraries/components/sounds/soundManager.js

### Steps to reproduce

![Uploading git1.jpg…]()

### Snack, code example, screenshot, or link to a repository

![git1](https://user-images.githubusercontent.com/65899491/179450939-d633ecea-029d-4047-8428-792c70e8654a.jpg)

**Comment by aleluiah** [comment]
i later realised the nativeSoundManager return true but it was just an empty object with no method or properties

**Comment by Bob-JZhao** [comment]
hi @aleluiah, did you fix the issue? Is that because Native modules return empty object {} , right?
