### ISSUE TITLE
iOS Build with Hermes outputs an incorrect sourcemap file

### ISSUE THREAD

**Issue by louiszawadzki** [facebook/react-native#34212]
### Description

When generating a sourcemap file in a build with Hermes enabled in iOS, the generated file is incorrect.

When looking into the build logs from XCode, I realized that the `HBC_SOURCEMAP_FILE` and `PACKAGER_SOURCEMAP_FILE` shared the same location (if the `SOURCEMAP_FILE` is named `main.jsbundle.map`). 

I believe `HBC_SOURCEMAP_FILE` is not pointing to the right path, as it is in `$DEST` and not in `$CONFIGURATION_BUILD_DIR`.

This can be solved in `scripts/react-native-xcode.sh` if we move the line `BUNDLE_FILE="$DEST/main.jsbundle"` above the sourcemap composition command, like so:

```bash
  "$HERMES_CLI_PATH" -emit-binary $EXTRA_COMPILER_ARGS -out "$DEST/main.jsbundle" "$BUNDLE_FILE"
  BUNDLE_FILE="$DEST/main.jsbundle" # moving the line here works
  if [[ $EMIT_SOURCEMAP == true ]]; then
    HBC_SOURCEMAP_FILE="$BUNDLE_FILE.map"
    "$NODE_BINARY" "$COMPOSE_SOURCEMAP_PATH" "$PACKAGER_SOURCEMAP_FILE" "$HBC_SOURCEMAP_FILE" -o "$SOURCEMAP_FILE"
  fi
  # previous location of the line
```

I'm ok to open a Pull Request with this change :) 
This may be linked to https://github.com/facebook/react-native/issues/34043

### Version

0.69.0

### Output of `npx react-native info`

System:
    OS: macOS 12.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 184.34 MB / 32.00 GB
    Shell: 5.8.1 - /opt/homebrew/bin/zsh
  Binaries:
    Node: 18.0.0 - /opt/homebrew/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 8.6.0 - /opt/homebrew/bin/npm
    Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/louis.zawadzki/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8309675
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0
    react-native: 0.69.0 => 0.69.0
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. Create a new React Native project
2. Add a javascript error when clicking on a button
3. Enable Hermes in the `Podfile`, run `pod install`
4. Add an `export SOURCEMAP_FILE=./build/main.jsbundle.map` line at the top of the "Bundle React Native code and images" build phase
5. Build from xcode with Release build configuration
6. Trigger the error
7. Symbolicate the error with metro-symbolicate

### Snack, code example, screenshot, or link to a repository

Path to sourcemaps files without any change - they are identical:
<img width="967" alt="Capture d’écran 2022-07-18 à 18 53 17" src="https://user-images.githubusercontent.com/8973379/179563522-b5a845bc-69c8-4022-b35e-17523443065c.png">

After the change, `HBC_SOURCEMAP_FILE` points to the right location:
<img width="957" alt="Capture d’écran 2022-07-18 à 18 55 16" src="https://user-images.githubusercontent.com/8973379/179563603-e94f0e9a-4cbd-4144-9a6f-8622c861fe34.png">

**Comment by cortinico** [comment]
This shoudl be addressed by #34111
