### ISSUE TITLE
Cannot connect to Metro (Flipper)

### ISSUE THREAD

**Issue by Aleksandern** [facebook/react-native#34220]
### Description

Hello.

Hermes Debugger doesn't work in Flipper. 
Error:
```
Cannot connect to Metro. Please check that metro is running and Flipper can connect to it.
```

I'm not sure but as I know `localhost:8081/json` should work but in my case it returns error:
`Cannot GET /json/`

Metro is started and works well.

How it can be fixed?

Thank you.

### Version

0.68.2

### Output of `npx react-native info`

System:
    OS: macOS 12.4
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 29.08 MB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 1.22.11 - ~/.nvm/versions/node/v16.13.2/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
    Watchman: 2022.07.04.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      Android NDK: 21.3.6528147
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: 7.0.3 => 7.0.3
    react: 18.1.0 => 18.1.0
    react-native: 0.68.2 => 0.68.2
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Run the mobile app. Open the debug menu. Tap "open debugger". In Flipper choose "Hermes Debugger (RN)"

### Snack, code example, screenshot, or link to a repository

no code

**Comment by cortinico** [comment]
> How it can be fixed?

Not enough information to debug this. Are you on a Android or iOS emulator?
On Android have you tried to `adb reverse tcp:8081 tcp:8081` to see if this solves?

> localhost:8081/

Are you opening this from your computer or from the device? Does it work in any of the two?

**Comment by Aleksandern** [comment]
It happens on my computer (macOS).

`http://localhost:8081/json` returns error `Cannot GET /json/`
`http://localhost:8081` works fine.

So my question is how to fix `http://localhost:8081/json`

**Comment by cortinico** [comment]
Can I ask you to open an issue on https://github.com/facebook/metro/issues
explaining your environment and mentioning that `http://localhost:8081/json returns error Cannot GET /json/`

You can link this issue to speed up the triaging there.

Closing as this is not a React Native issue per se.

**Comment by jazib10218** [comment]
> > How it can be fixed?
> 
> Not enough information to debug this. Are you on a Android or iOS emulator? On Android have you tried to `adb reverse tcp:8081 tcp:8081` to see if this solves?
> 
> > localhost:8081/
> 
> Are you opening this from your computer or from the device? Does it work in any of the two?

it worked, thanks alot.

**Comment by Manikanta-GEP** [comment]
How to solved it for iOS simulator?

**Comment by shr-GE** [comment]
i am facing same issue with a live device
