### ISSUE TITLE
Flatlist Horizontal Scroll is not scrolling in Android in RN@0.66.4

### ISSUE THREAD

**Issue by ManeeshAkurathi** [facebook/react-native#34225]
### Description

It used to work earlier, after upgrading from RN to 0.66.4, i am not able to scroll horizontally, If i try hard with two fingers and use one to scroll then it's hardly scrolling. Any one experienced this behaviour mainly in Android and in IOS it's working fine.

### Version

0.66.4

### Output of `npx react-native info`

System:
    OS: macOS 12.2
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 52.55 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 15.1.0 - /usr/local/Cellar/node/15.1.0/bin/node
    Yarn: 1.22.10 - /usr/local/Cellar/node/15.1.0/bin/yarn
    npm: 8.11.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.4 => 0.66.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

The following code is the snippet and earlier it used to work, did i miss anything in this version??

### Snack, code example, screenshot, or link to a repository

                                       <View style={{flex:1} >
                                            <FlatList
                                                data={["a","b","c","d"]}
                                                renderItem={({ item, index }) => this.renderListViewItem(themeStyle, state, item, index)}
                                                horizontal
                                                ItemSeparatorComponent={() => {
                                                    return <View style={[{ width: 15 }]} />
                                                }}
                                                keyExtractor= (item, index) => index.toString();
                                                extraData={state}
                                            />
                                        </View>

**Comment by ManeeshAkurathi** [comment]
Sorted it by importing FlatList from react-native-gesture-handler.

**Comment by Emmybritt** [comment]
Thank

> Sorted it by importing FlatList from react-native-gesture-handler.

This works for me as well

**Comment by vikil143** [comment]
> Sorted it by importing FlatList from react-native-gesture-handler.

Y we need to import from gesture handler when we have react native import

**Comment by Raman225002** [comment]
@ManeeshAkurathi , thank you so much, it's working.

**Comment by ManeeshAkurathi** [comment]
> > Sorted it by importing FlatList from react-native-gesture-handler.
> 
> Y we need to import from gesture handler when we have react native import

Not sure about actual issue but it seems like in some scenario the native one is not able to handle gestures so that is the reason
