### ISSUE TITLE
ScrollView bounces back on some android devices

### ISSUE THREAD

**Issue by thomasgrivet** [facebook/react-native#34249]
### Description

Hello!
On all my previous and current projects, ScrollView based components (ScrollView, FlatList, ...) had this bug where the ScrollView would bounce back on some real android devices.
I tested on a OnePlus 5, OnePlus 5T, Huawei Honor 9 and all had this issue. Other devices such as Pixels do not.
You may reproduce by quickly swiping in one direction.
I do not have any problem with others application which are not built with react-native.
I [uploaded a video](https://user-images.githubusercontent.com/18561703/180514668-dea0ab11-843f-427e-af7b-77aa9d713b98.mp4) in which you can clearly see the list bouncing back randomly (I did not change direction in between swipes).
It is quite a frustrating bug which impact a lot of users, especially on low-end devices.
Do you need any example or infos? Let me know!

Thanks!

### Version

0.69.1

### Output of `npx react-native info`

System:
    OS: macOS 12.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 106.02 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 1.22.18 - ~/Dev/React Native/cocolis-react-native/node_modules/.bin/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8309675
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 18.0.1.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.1 => 0.68.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Inside a ScrollView based component and using a real android device such as a OnePlus 5 / 5T, swipe quickly in one direction multiple times. At some point you will experience this 'bounce-back' bahaviour.

### Snack, code example, screenshot, or link to a repository

https://github.com/thomasgrivet/FlashList-Android-Behaviour

**Comment by peteritvina** [comment]
same issue

**Comment by DaniyalShaikh-0** [comment]
Facing the same issue on Xiaomi device, even with the release build.

**Comment by mirik999** [comment]
Same issue on Xiaomi device.

**Comment by JencirJamal** [comment]
Yeah, i too face exactly the same issue with Flatlist bouncing back sometimes when swiped in the same direction. Hopefully this get's fixed soon.

**Comment by AdvMaple** [comment]
Facing the same issue on Android 13 with React 18, React Native 0.71.6

**Comment by thomasgrivet** [comment]
This issue does still exist, have to comment so it doesn't get closed.

**Comment by FatemaDholkawala** [comment]
Any solution for this issue?

**Comment by tamayo7** [comment]
I think it related to this issue [38236](https://github.com/facebook/react-native/issues/38236) ?
