### ISSUE TITLE
[iOS] Unable to archive & export build with bundled Hermes with mismatched Clang versions

### ISSUE THREAD

**Issue by Archez** [facebook/react-native#34240]
### Description

When using the bundled hermes engine for iOS, an error occurs when attempting to archive and export a release build through `xcodebuild`. The issue appears to be caused by a mismatch between the clang version used to compile the hermes engine extracted from the tarball, and the clang version used to build the app itself (host machine).

Below is the relevant error message from the xcodebuild output

```sh
    Command took 0 seconds
    Clang: cd /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tempsduxy68_
     ['/Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang', '-cc1', '-cc1', '-triple', 'arm64-apple-ios11.0.0', '-emit-obj', '--mrelax-relocations', '-disable-llvm-passes', '-target-sdk-version=15.4', '-fvisibility-inlines-hidden-static-local-var', '-target-abi', 'darwinpcs', '-O3', '-x', 'ir', '117', '-o', '117.o']
    -= Output =-
    error: Invalid value (Producer: 'APPLE_1_1316.0.21.2.3_0' Reader: 'LLVM APPLE_1_1300.0.29.30_0')
    1 error generated.
    Exited with 1

```

Specifically the thing of note is hermes is produced with a clang version of 13.1.6, and the react native app is being built with a clang version of 13.0.0

In my case I am on macOS 11 which has a max supported XCode version of 13.2.1 (clang 13.0.0)

I haven't tested if this only errors when using a clang version less than hermes (i.e. clang 14.x may work fine as its a higher version)

### Version

0.69.2

### Output of `npx react-native info`

System:
    OS: macOS 11.6.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 1.35 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.19.0 - ~/.nvm/versions/node/v14.19.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 6.14.16 - ~/.nvm/versions/node/v14.19.0/bin/npm
    Watchman: 2022.07.04.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/lib/ruby/gems/2.7.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 29, 30, 31, 32
      Build Tools: 29.0.3, 30.0.2, 30.0.3, 31.0.0
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.2 => 0.69.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

* Enable hermes on a RN 0.69.x project
* Ensure you have XCode <= 13.2.1 (or Clang < 13.1.6)
* Ensure codesign is setup
* Attempt to archive and export a release build using xcodebuild

### Snack, code example, screenshot, or link to a repository

Can use create-react-native-app or react-native init and setup codesigning to be able to produce an archive and export

**Comment by cortinico** [comment]
Thanks for reporting this @Archez 

> I haven't tested if this only errors when using a clang version less than hermes (i.e. clang 14.x may work fine as its a higher version)

Could you try with MacOS 12.x or anyway with a clang version which >= than the Hermes one and report back if possible?

**Comment by ZhigamovskyN** [comment]
For me the same. I have **enabled hermes** on **RN 0.69.2**: 
 - For **XCode 13.0 (locally)** - **ARCHIVE SUCCESS**
 - For **XCode 13.2.1 (via Azure Pipelines)** - **ERROR**
 - With **disabled hermes** - **SUCCESS**
 - With **enabled hermes** - **ERRORS**

**Errors**:
 - error: Invalid value (Producer: 'APPLE_1_1316.0.21.2.3_0' Reader: 'LLVM APPLE_1_1300.0.29.30_0')
 - Failed to compile bundle: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/hermes7ld5wn8c/hermes.arm64.xar
 - xcodebuild[63421:382443] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path "/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/bees_2022-08-02_10-16-12.689.xcdistributionlogs".
error: exportArchive: ipatool failed with an exception: #<CmdSpec::NonZeroExitException: $ /Applications/Xcode_13.2.1.app/Contents/Developer/usr/bin/python3 /Applications/Xcode_13.2.1.app/Contents/Developer/usr/bin/bitcode-build-tool -v -t /Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin --sdk /Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.2.sdk -o /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/ipatool20220802-63851-lgpf3c/thinned-out/arm64/Payload/bees.app/Frameworks/hermes.framework/hermes --generate-dsym /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/ipatool20220802-63851-lgpf3c/thinned-out/arm64/Payload/bees.app/Frameworks/hermes.framework/hermes.dSYM --strip-swift-symbols /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/ipatool20220802-63851-lgpf3c/thinned-in/arm64/Payload/bees.app/Frameworks/hermes.framework/hermes
 - ##[error]Error: /usr/bin/xcodebuild failed with return code: 70

**Comment by cortinico** [comment]
@ZhigamovskyN what's the CLang version you have in the 2 environment?

**Comment by ZhigamovskyN** [comment]
@cortinico  
Via command:
`clang --version`

**Azure Pipeline Env**: 
>  Apple clang version 13.0.0 (clang-1300.0.29.30)
>  Target: x86_64-apple-darwin20.6.0
>  Thread model: posix
>  InstalledDir: /Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Local Env**:
> Apple clang version 13.0.0 (clang-1300.0.29.3)
> Target: x86_64-apple-darwin20.6.0
> Thread model: posix
> InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by ZhigamovskyN** [comment]
@Archez  @cortinico I have changed **MacOS** version and **XCode** version for Virtual Machine in **Azure Pipelines** to:
> MacOS 12.5 (21G72)
> XCode 13.4.1
 
After that **CLang** version has been changed to:
> Apple clang version 13.1.6 (clang-1316.0.21.2.5)
>  Target: x86_64-apple-darwin21.6.0
>  Thread model: posix
>  InstalledDir: /Applications/Xcode_13.4.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**And build successfully archived and export without errors.**

Also we had one more try to archive and export application build locally. Our local environment:
 - **MacOS 11.6**
 - **XCode 13.2.1**
 - **CLang 13.0.0**
 - **RN 0.69.2**
 - **Hermes enabled**
 
**And build successfully archived and exported without errors.**

@cortinico Do you have some ideas why **hermes** requires on **Azure Pipeline** only the **latest MacOS** with **latest XCode** and appropriate **CLang**? Do you have some ideas, which additional dependencies from environment **hermes** has?

**Comment by cortinico** [comment]
> Do you have some ideas why hermes requires on Azure Pipeline only the latest MacOS with latest XCode and appropriate CLang?

Nope sorry, I don't have experience with Azure Pipelines so I can't tell. We're building Hermes both inside React Native and the Hermes repo using CircleCI (configs are public) and everything is green.

> Do you have some ideas, which additional dependencies from environment hermes has?

@neildhar can tell more about this. On Mac, once you have `cmake` and a compiler pipeline in place like `clang` you should be all set.
