### ISSUE TITLE
Didn't find subscribe to topic in websockets.

### ISSUE THREAD

**Issue by begouravdev** [facebook/react-native#34256]
### Description

Basically, the backend is using this lib `adonis-websocket-client` here is a function that `subscribe` to `topic`.
here is an example
`this.ws.withJwtToken(this.token).subscribe(channel)`

Sending a message to a specific topic
`socket.ws.getSubscription(topic).emit(event, message)` 

Didn't find anything related to websockets.

### Version

0.64.0

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1
    Memory: 105.48 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.11.0 - /usr/local/bin/npm
    Watchman: 2022.06.06.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: ^0.64.0 => 0.64.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

The above information is enough for this bug.

### Snack, code example, screenshot, or link to a repository

The above information is enough for this bug.

**Comment by cortinico** [comment]
You can find documentation about websockets here https://reactnative.dev/docs/network#websocket-support

**Comment by begouravdev** [comment]
@cortinico I know the basics have you found something `subscribe` to `topic`?

**Comment by giautm** [comment]
> @cortinico I know the basics have you found something `subscribe` to `topic`?

RN only provides the implementation for the WebSocket protocol, "`subscribe` to `topic`" is something else, that is abstracted by another protocol that builds on top of the WebSocket protocol. So, you need to find the library on the client, that accepts WebSocket object to initialize the connection.

For your case, I think you can override the `connect()` method the use the WebSocket from RN.

https://github.com/adonisjs/adonis-websocket-client/blob/develop/src/Connection/index.js#L576-L598
