### ISSUE TITLE
React Native 0.68~0.69.  A problem occurred configuring project ':react-native-gradle-plugin'.

### ISSUE THREAD

**Issue by wangyupeng993** [facebook/react-native#34258]
### Description

* What went wrong:
A problem occurred configuring project ':react-native-gradle-plugin'.
> Could not create service of type OutputFilesRepository using ExecutionGradleServices.createOutputFilesRepository().
   > Timeout waiting to lock Build Output Cleanup Cache (/Volumes/HPP500/project/ReactNative/Cmpanda/node_modules/react-native-gradle-plugin/.gradle/buildOutputCleanup). It is currently in use by this Gradle process.Owner Operation: unknown
     Our operation: 
     Lock file: /Volumes/HPP500/project/ReactNative/Cmpanda/node_modules/react-native-gradle-plugin/.gradle/buildOutputCleanup/buildOutputCleanup.lock

### Version

ex. 0.69.2

### Output of `npx react-native info`

System:
    OS: macOS 12.4
    CPU: (8) x64 Intel(R) Core(TM) i7-8557U CPU @ 1.70GHz
    Memory: 56.42 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.1 - /usr/local/bin/node
    Yarn: Not Found
    npm: 8.1.2 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

npm run android

### Snack, code example, screenshot, or link to a repository

<img width="892" alt="image" src="https://user-images.githubusercontent.com/39769538/180618300-24155605-3c97-4ee3-9156-5b4f6c91a5c7.png">

rootProject.name = 'Cmpanda'
apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
include ':app'
includeBuild('../node_modules/react-native-gradle-plugin')

if (settings.hasProperty("newArchEnabled") && settings.newArchEnabled == "true") {
    include(":ReactAndroid")
    project(":ReactAndroid").projectDir = file('../node_modules/react-native/ReactAndroid')
    include(":ReactAndroid:hermes-engine")
    project(":ReactAndroid:hermes-engine").projectDir = file('../node_modules/react-native/ReactAndroid/hermes-engine')
}

**Comment by cortinico** [comment]
This is unrelated to React Native but rather a problem with Gradle: https://github.com/gradle/gradle/issues/8750

I would try to delete the `.lock` file mentioned and rebuilt. Please reopen if the issue persists

**Comment by dev-dev-7** [comment]
Do **sudo** before any command. example: sudo ./gradlew assembleRelease

**Comment by PatricioIgnacio** [comment]
All errors can be due to different reasons, always in a permissions or gradle context.

In my personal case, updating through Android Studio the gradle version solved my problem, it is automatically given by gradle when starting Android Studio.

Also, you could modify the general permissions in your macOS or through the terminal using chmod -R 777 or chmod -R 755 with the specific path of your project.

Cheer up!

PS: Sorry for my English, I'm perfecting it, I'm from Chile
