### ISSUE TITLE
Text component in use numberOfLine in 2 or more then three dots not work proper in Ios

### ISSUE THREAD

**Issue by parth-shiroya** [facebook/react-native#34268]
### Description

![Screenshot at Jul 25 13-43-32](https://user-images.githubusercontent.com/102135385/180730462-a3892a7e-717a-4026-92af-3e13262d84da.png)
![Screenshot at Jul 25 13-44-26](https://user-images.githubusercontent.com/102135385/180730587-2d0f821e-09d8-4cc3-aaf1-c7b7b0a18cf4.png)

### Version

0.66.3

### Output of `npx react-native info`

System:
    OS: macOS 11.6
    CPU: (6) x64 Intel(R) Core(TM) i5-9500F CPU @ 3.00GHz
    Memory: 572.70 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.16.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 8.1.4 - ~/Documents/Parth/Projects/affirmation/node_modules/.bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 28, 29, 30, 31, 32
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 33.0.0
      System Images: android-25 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-30 | Google TV Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom_64
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8309675
    Xcode: 13.0/13A233 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.3 => 0.66.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

three dots only show when `numberofLine =4` whole line fill up in ios but new line available but not show
android work proper.  

### Snack, code example, screenshot, or link to a repository

<Text
                ellipsizeMode="tail"
                numberOfLines={4}
                style={{
                  textAlign: 'left',
                  includeFontPadding: false,
                  color: 'white',
                  fontSize: 35,
                }}>
                {'Asdasdsad \n asdasdasd \n  asdsadasd \n asdsadasd \n sdasdasdas \n'
               }
              </Text>

**Comment by Ainias** [comment]
We have the same problem with React Native 0.67.4

**Comment by poon00097** [comment]
Have same issue, any solution?

**Comment by Ainias** [comment]
@poon00097 we added a simple component which counts the linebreaks `\n`. If the linebreaks-count is equal or bigger to the numberOfLines of the component, add `...` to the end of the line at position numberOfLines. 
This obviously does not help every time, but in our case often there were only bullet points which do not cause a line break because of long text. Thus it is a low cost option for 85% of the cases.

**Comment by fabriziobertoglio1987** [comment]
Do you still experience this issue? 

I have four years of experience maintaining facebook/react-native and I specialize in the Text and TextInput components. I currently have 58 [facebook/react-native PRs](https://github.com/facebook/react-native/pulls?q=is%3Apr+author%3Afabriziobertoglio1987+). 

If you still experience this issue, I will prepare a patched release with the fix.

Thanks a lot

**Comment by oussamaennadafy** [comment]
@fabOnReact i still have this issue
