### ISSUE TITLE
[0.69.2 android-only accessibility] 'accessible' not working

### ISSUE THREAD

**Issue by wuyue1019** [facebook/react-native#34266]
### Description

'accessible' property not working on android.

### Version

0.69.2

### Output of `npx react-native info`

System:
    OS: macOS 12.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 37.68 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.15.0 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 8.5.5 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.1 AI-173.4907809
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.2 => 0.69.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1) Create an empty project
2) Add below code anywhere appropriate

```
<View accessible={true} accessibilityLabel={'three'}>
  <Text>one</Text>
  <Text>two</Text>
</View>
```

[Android-only]
Expected:  'three' only for accessibility
Got: 'one' and 'two' still focusable for accessibility

For now I have to add accessible={false} for both 'one' and 'two' as a workaround.

### Snack, code example, screenshot, or link to a repository
```

<View accessible={true} accessibilityLabel={'three'}>
  <Text>one</Text>
  <Text>two</Text>
</View>
```

**Comment by wuyue1019** [comment]
BTW, my RN was updated from 0.59.8, and the performance for accessibility is quite much better in 0.69.2. Thanks dudes for the efforts.

**Comment by cortinico** [comment]
@blavalla is this something for you to track?

**Comment by EdmundasR** [comment]
have run into this issues on 0.69.3-0.69.5 and it seems the issue is gone on 0.70.0

**Comment by paulosborne** [comment]
We've encountered this in 0.69.6 and we're currently unable to upgrade to 0.70 due to an issue with one of our other dependencies so if this could be patched in v69 it would be appreciated.

**Comment by AvielYosef** [comment]
I got the same issue, we upgrade to 0.70 and its gone

**Comment by acrojas2** [comment]
I have react-native 0.71.8 and still have the problem, accessible prop is not working. The pseudo code is something like this:
``` jsx
<View accessible={false}>
 <Pressable ...props />
</View>
```
anyone can help me pliss??
