### ISSUE TITLE
[macos-12] [0.70.0-rc.0-1] Release-iphonesimulator/MyApp.app/main.jsbundle does not exist

### ISSUE THREAD

**Issue by leotm** [facebook/react-native#34274]
### Description

_Note: macOS 13b builds/runs fine locally_

Similar older cases not on RN New arch
- https://github.com/facebook/react-native/issues/23943#issuecomment-486736335
- https://github.com/facebook/react-native/issues/29356
- https://github.com/facebook/react-native/issues/29690

```console
# ...
⚠️  ld: method '-compareToSize:thresholdRatio:' in category from /Users/runner/Library/Developer/Xcode/DerivedData/MyApp-brtubmujgpwqbxfcbmbgsgmzrura/Build/Products/Release-iphonesimulator/React-RCTText/libReact-RCTText.a(NSTextStorage+FontScaling.o) conflicts with same method from another category
⚠️  ld: method '-scaleFontSizeWithRatio:minimumFontSize:maximumFontSize:' in category from /Users/runner/Library/Developer/Xcode/DerivedData/MyApp-brtubmujgpwqbxfcbmbgsgmzrura/Build/Products/Release-iphonesimulator/React-RCTText/libReact-RCTText.a(NSTextStorage+FontScaling.o) conflicts with same method from another category
▸ Processing Info.plist
▸ Running script 'Bundle React Native code and images'
    the transform cache was reset.

❌  error: File /Users/runner/Library/Developer/Xcode/DerivedData/MyApp-brtubmujgpwqbxfcbmbgsgmzrura/Build/Products/Release-iphonesimulator/MyApp.app/main.jsbundle does not exist. This must be a bug with React Native, please report it here: https://github.com/facebook/react-native/issues

▸ Generating 'MyApp.app.dSYM'
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening MyApp.xcworkspace.
info Run CLI with --verbose flag for more details.
Error: Process completed with exit code 1.
```

[Example log](https://github.com/leotm/react-native-template-new-architecture/runs/7507151182?check_suite_focus=true) or latest [commits](https://github.com/leotm/react-native-template-new-architecture/pull/690/commits)

<details>

<summary>A suspicion :suspect:  (wasn't this, still happening on unpatched 0.70.0-rc.1)</summary>

- _possibly_ `react-native` Yarn v3 patches somehow cause this?
- i wanted this commit to build iOS Release https://github.com/facebook/react-native/pull/34234
- but yday's react-native@nightly builds but crashes on iOS Debug and Release
- so i patched RN instead similarly
  - issue: https://github.com/leotm/react-native-template-new-architecture/issues/794
  - pr: https://github.com/leotm/react-native-template-new-architecture/pull/795
  - _yarn v3 warns the 70mb patch is above the desired 50mb, for the 1-liner_

In which case reverting the Yarn v3 patch then re-applying
- https://github.com/leotm/react-native-template-new-architecture/pull/791

Should in theory fix

</details>

### Version

0.70.0-rc.0 (patched), 0.70.0-rc.1 (unpatched, current)

_Previously patched 0.70.0-rc.0 (1-liner) to allow `PRODUCTION=1 pod install`_

### Output of `npx react-native info`

<details>

<summary>remember to yarn install first</summary>

```console
Run npx react-native info
  npx react-native info
  shell: /bin/bash -e {0}
npm WARN exec The following package was not found and will be installed: react-native
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.[2](https://github.com/leotm/react-native-template-new-architecture/runs/7519128906?check_suite_focus=true#step:3:2).1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated source-map-resolve@0.5.[3](https://github.com/leotm/react-native-template-new-architecture/runs/7519128906?check_suite_focus=true#step:3:3): See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated uglify-es@3.3.[9](https://github.com/leotm/react-native-template-new-architecture/runs/7519128906?check_suite_focus=true#step:3:10): support for ECMAScript is superseded by `uglify-js` as of v3.13.0
error Failed to load configuration of your project.
info Run CLI with --verbose flag for more details.
Error: Process completed with exit code 1.
```

<s>Similar to</s>
- <s>https://github.com/react-native-community/cli/issues/1650</s>
- <s>https://github.com/facebook/react-native/issues/34052</s>

Nvm, forgot to run it after `Yarn`

</details>

```console
warn Package react-native-flipper contains invalid configuration: "dependency.platforms.ios.project" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
info Fetching system and libraries information...
System:
    OS: macOS 12.4
    CPU: (3) x[6](https://github.com/leotm/react-native-template-new-architecture/runs/7519237740?check_suite_focus=true#step:4:6)4 Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz
    Memory: 3.64 GB / 14.00 GB
    Shell: 3.2.5[7](https://github.com/leotm/react-native-template-new-architecture/runs/7519237740?check_suite_focus=true#step:4:7) - /bin/bash
  Binaries:
    Node: 16.16.0 - /usr/local/bin/node
    Yarn: 3.2.2 - ~/.yarn/bin/yarn
    npm: [8](https://github.com/leotm/react-native-template-new-architecture/runs/7519237740?check_suite_focus=true#step:4:8).11.0 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/lib/ruby/gems/3.0.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 27, 28, 2[9](https://github.com/leotm/react-native-template-new-architecture/runs/7519237740?check_suite_focus=true#step:4:9), 30, 31, 32, 33
      Build Tools: 27.0.0, 27.0.1, 27.0.2, 27.0.3, 28.0.0, 28.0.1, 28.0.2, 28.0.3, 29.0.0, 29.0.1, 29.0.2, 29.0.3, 30.0.0, 30.0.1, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 33.0.0
      Android NDK: 23.2.8568313
  IDEs:
    Android Studio: Not Found
    Xcode: 13.4.1/13F[10](https://github.com/leotm/react-native-template-new-architecture/runs/7519237740?check_suite_focus=true#step:4:10)0 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_332 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: next => 8.0.0-alpha.0 
    react: [18](https://github.com/leotm/react-native-template-new-architecture/runs/7519237740?check_suite_focus=true#step:4:18).1.0 => 18.1.0 
    react-native: 0.70.0-rc.0 => 0.70.0-rc.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

- try to build iOS Release on macOS 12 and Xcode 13.4.1
- https://github.com/leotm/react-native-template-new-architecture/pull/690

### Snack, code example, screenshot, or link to a repository

https://github.com/leotm/react-native-template-new-architecture/pull/690/files

**Comment by dmitryrykun** [comment]
Hey @leotm , thanks for posting. Just a quick sanity check, is bundler running without errors on the machine that produces this error?
```
❌  error: File /Users/runner/Library/Developer/Xcode/DerivedData/MyApp-brtubmujgpwqbxfcbmbgsgmzrura/Build/Products/Release-iphonesimulator/MyApp.app/main.jsbundle does not exist.
```

**Comment by leotm** [comment]
np ^ good question, i've added a bundle step before the build which looks fine, if you're able to spot anyth may have missed
- https://github.com/leotm/react-native-template-new-architecture/pull/690

```console
Run npx react-native bundle --entry-file='index.ts' --bundle-output='./ios/main.jsbundle' --dev=false --platform='ios' --assets-dest='./ios'
  npx react-native bundle --entry-file='index.ts' --bundle-output='./ios/main.jsbundle' --dev=false --platform='ios' --assets-dest='./ios'
  shell: /bin/bash -e {0}
warn Package react-native-flipper contains invalid configuration: "dependency.platforms.ios.project" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
                    Welcome to Metro!
              Fast - Scalable - Integrated


info Writing bundle output to:, ./ios/main.jsbundle
info Done writing bundle output
info Copying 1 asset files
info Done copying assets
```

**Comment by leotm** [comment]
jus spotted `@react-native-community/cli` seems to be `8.0.0-alpha.0` here in CI, but `9.0.0-alpha.4` locally :suspect:

**Comment by leotm** [comment]
next steps
- https://github.com/leotm/react-native-template-new-architecture/issues/805

update `project.pbxproj` seems missed in [0.63.4 to 0.64.0](https://react-native-community.github.io/upgrade-helper/?from=0.63.4&to=0.64.0) upg
- https://github.com/facebook/react-native/commit/6685aba462699c696cb6ac95626b9592deb292fc 
  - `Remove the main.jsbundle file that doesn't exists, this file is included automatically in the app bundle and doesn't need to be in xcode (it won't even be at that path).`

check
- https://github.com/facebook/react-native/search?q=main.jsbundle&type=code

**Comment by kelset** [comment]
@leotm can you help me understand the scope of this issue you are reporting? Is there a way to repro locally?

**Comment by leotm** [comment]
sure jus noticed been unable to build iOS Release since `0.69.0`, only in CI on [macOS-12](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-12-Readme.md) (so Xcode 13.4.1)

but had no prob locally on ye olde MBP M1 (might wait for the M3)
while upgrading early to (unsupported) macOS-13 beta and Xcode 14 beta

if you're still on macOS-12 stable then hopefully can repro locally here
- https://github.com/leotm/react-native-template-new-architecture/pull/690

exhausted most options can think of so think next step my side will be to try to repro in a new repo w vanilla `npx react-native init RN070RC1 --version 0.70.0-rc.1` w same CI (GitHub Actions, same workflow)

then if still getting the error try to dive deeper and come up w a PR

**Comment by leotm** [comment]
great [stuff](https://youtu.be/sdQHzjV90ow) so far, where them video chapters at (;

**Comment by leotm** [comment]
closing since `npx react-native init RN070RC1 --version 0.70.0-rc.1` w added CI works OOTB, couldn't repro
- https://github.com/leotm/RN070RC1/commit/f2f070efffc3da2dd71f7752398d07c2c3a167ed ✔️

will figure/fix eventually, betting my big bucks missed smth some point during the upg process since 0.61.5

so frequently glancing back n forth at our [template](https://github.com/facebook/react-native/tree/main/template) on `main`

**Comment by wustzhy** [comment]
https://github.com/facebook/react-native/issues/29356#issuecomment-658238011

works fine!!

when js code has error, main.bundle will create fail, then archive release package will fail too.
`npm run build:ios` helps to display the errro timely.
