### ISSUE TITLE
Dev server watches the whole node_modules directory causing "too many open files, watch" error in a big project on a not very powerful MacBook

### ISSUE THREAD

**Issue by serhiipalash** [facebook/react-native#34277]
### Description

We develop the app for pregnant [Preggers](https://apps.apple.com/us/app/id1363479578). The project is built with React Native and we are very grateful to you for making this possible!

Our project is very big with a lot of features and a lot of dependencies installed in `node_modules`. After making some refactoring and splitting the code into more files we faced the issue that the dev server can't be started for some of our teammates, which have an older MacBook. This is the error they see when running `react-native run-ios`

```
Error: EMFILE: too many open files, watch at FSEvent.FSWatcher._handle.onchange
```

What is possible to do to fix this, from our point of view

1. Increase system limit on watched files

Unfortunately, we were not able to do it and eventually it would only postponed the problem to the future.

2. Ignore `node_modules` directory from watching in dev mode

We don't see the point of watching the `node_modules` while working with code, but this is how it is in the latest React Native version official template, which we tested

```
react-native init testapp --template react-native-template-typescript
```

We don't add new dependencies every day. We can just restart the server in case we want to update `node_modules`.

3. Disable watching in dev mode completely

We found that this is possible to do by passing `CI` equal to `true`

```
export CI=true && npx react-native run-ios
```

In this way the bundler starts the app without errors, but when you reload the app the bundler doesn't collect the changes you have made in the code. So, it's like test mode, not dev mode. 

What we need is a dev mode without watching the file changes, but with code recompilation when you reload the Simulator manually.

----------------

Please help us to make either 2. or 3. work. Our team can't work without it.

Note: Here is the issue we submitted to Metro repository

https://github.com/facebook/metro/issues/834

### Version

0.69.2

### Output of `npx react-native info`

none

### Steps to reproduce

none

### Snack, code example, screenshot, or link to a repository

none

**Comment by cortinico** [comment]
Thanks for reporting this. Closing as this is a metro issue, let's track it inside https://github.com/facebook/metro/issues/834

**Comment by serhiipalash** [comment]
Yes, it looks like a metro issue. Let's close this.
