### ISSUE TITLE
[iOS] Changing style dynamically on `TextInput` with foreign character and `multiline` set to true won't work

### ISSUE THREAD

**Issue by thisisgit** [facebook/react-native#34285]
### Description

The style changes won't apply on `TextInput` if it has at least single foreign character as its value, and `multiline` property is set to `true`.
I haven't tried it on Android so I'm not sure if it has the same issue.

### Version

0.68.2

### Output of `npx react-native info`

System:
    OS: macOS 12.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 940.77 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.18 - ~/.nvm/versions/node/v16.14.2/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 12.0.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.2 => 0.68.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

See screenshot & snack demo below

### Snack, code example, screenshot, or link to a repository

https://snack.expo.dev/@trysnack/textinput-with-foreign-char-and-multiline

https://user-images.githubusercontent.com/13231564/181226133-9080c34b-3020-423c-9a82-5f78d940f41f.mp4

**Comment by yczeng** [comment]
I also have this problem

**Comment by thisisgit** [comment]
Not resolved yet

**Comment by thisisgit** [comment]
Not stale

**Comment by thisisgit** [comment]
Not stale

**Comment by cortinico** [comment]
> snack.expo.dev/@trysnack/textinput-with-foreign-char-and-multiline

@thisisgit can you provide a valid reproducer as this one returns a 404?

**Comment by thisisgit** [comment]
@cortinico Hi sorry for the confusion. I just tested the code and found out that it's fixed now. I don't know what fixed the issue but testing it on Expo SDK51 just works.

Thanks for checking this out
