### ISSUE TITLE
RN 0.68.2, jest upgrade v26 to 27 is not possible

### ISSUE THREAD

**Issue by kopax-polyconseil** [facebook/react-native#34289]
### Description

We are trying to upgrade our test environment from jest 26 to 27. This is our working branch : https://github.com/pass-culture/pass-culture-app-native/tree/update-jest-27

So far, we encounter a bunch of error that we are still unable to fix, for instance: 

### `TypeError: requestAnimationFrame is not a function`

```
    TypeError: requestAnimationFrame is not a function
      at start (node_modules/react-native/Libraries/Animated/animations/TimingAnimation.js:133:34)
```

### `TypeError: global.cancelAnimationFrame is not a function`

```
    TypeError: global.cancelAnimationFrame is not a function

      at TimingAnimation.stop (node_modules/react-native/Libraries/Animated/animations/TimingAnimation.js:176:12)
```

### `Exceeded timeout of 5000 ms for a hook`

```
    thrown: "Exceeded timeout of 5000 ms for a hook.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."
```

We have many test failing for this and have found a bunch of proposition but none worked to fix our test

This is the most present error.

## Related issues 

On jest repo: 

- https://github.com/facebook/jest/issues/13068
- https://github.com/facebook/jest/issues/13069

### Version

0.68.2

### Output of `npx react-native info`

```
info Fetching system and libraries information...
System:
    OS: Linux 5.8 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (8) x64 Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz
    Memory: 7.00 GB / 15.30 GB
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 1.22.15 - ~/.yarn/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
    Watchman: 20210124.162314.0 - /usr/local/bin/watchman
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 1.8.0_231 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.2 => 0.68.2 
  npmGlobalPackages:
    *react-native*: Not Found

```

### Steps to reproduce

1. Clone my repo `git clone --single-branch --branche update-jest-27 https://github.com/pass-culture/pass-culture-app-native.git`
2. `cd pass-culture-app-native`
3. `yarn`
4. `yarn test:unit`

### Snack, code example, screenshot, or link to a repository

https://github.com/pass-culture/pass-culture-app-native

**Comment by henrymoulton** [comment]
I've attempted this too and been unable to upgrade.

**Comment by kopax-polyconseil** [comment]
We are totally stuck with an old version of jest, especially because of this error `Exceeded timeout of 5000 ms for a hook`. Sad things, they did some improvement on jest 28, that we need.

**Comment by cortinico** [comment]
This is a known issue as we're still on Jest 26.
@kopax-polyconseil feel free to send a PR that addressed those breaking changes on React Native so that you can successfully update Jest in your project.

**Comment by kopax-polyconseil** [comment]
I don't know how to fix those, so either I am bad or the content of the change are not trivial
We'll have to stay on Jest 26 =/.
