### ISSUE TITLE
Unable to determine event type for "metadata": $ReadOnlyArray

### ISSUE THREAD

**Issue by jgx-jay** [facebook/react-native#34288]
### Description

Unable to determine event type for "metadata": $ReadOnlyArray

### Version

0.68.1

### Output of `npx react-native info`

System:
    OS: macOS 12.4
    CPU: (8) x64 Apple M1
    Memory: 87.59 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.20.0 - ~/.nvm/versions/node/v14.20.0/bin/node
    Yarn: 3.2.1 - ~/.nvm/versions/node/v14.20.0/bin/yarn
    npm: 6.14.17 - ~/.nvm/versions/node/v14.20.0/bin/npm
    Watchman: 2021.06.07.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: 22.0.6917172-beta1
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7199119
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_162 - /Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/bin/javac
  npmPackages:
    @react-native-community/cli: ^7.0.3 => 7.0.3 
    react: 17.0.2 => 17.0.2 
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

 Error encountered while writing spec file

### Snack, code example, screenshot, or link to a repository

 type OnTimedMetadataEvent = $ReadOnly<{|
    metadata: $ReadOnlyArray<{|
        value: string,
        identifier: string
    |}>,
    target: Int32
|}>;

**Comment by jgx-jay** [comment]
Please, any ideas?

**Comment by cipolleschi** [comment]
Hi @jgx-jay, are you using TypeScript or Flow to write your specs? If you are using typescript, the syntax is [slightly different](https://reactnative.dev/docs/new-architecture-library-intro#supported-types).

If you are using Flow, have you tried to create a separate type for the

```ts
{|
value: string,
identifier: string
|}
``` 

type?

Something like:

```ts 
type Entry = {|
  value: string,
  identifier: string
|}

type OnTimedMetadataEvent = $ReadOnly<{|
metadata: $ReadOnlyArray<Entry>,
target: Int32
|}>;
```
?

It could be that the parser can't understand properly that complex type.

**Comment by jgx-jay** [comment]
@cipolleschi Thanks for the reply, but still the same error. I think there is no support Array.

**Comment by cortinico** [comment]
> @cipolleschi Thanks for the reply, but still the same error. I think there is no support Array.

That's not correct, there is `Array` support for specs in both TypeScript and Flow:
https://reactnative.dev/docs/new-architecture-appendix

Can you provide a better description of what you're trying to do, provide a reproducer or give us more insights?

**Comment by jgx-jay** [comment]
@cortinico I hope I'm wrong too, but in react-native-codegen@0.0.13, https://github.com/facebook/react-native/blob/v0.68.1/packages/react-native-codegen/src/parsers/flow/components/events.js#L19

**Comment by cortinico** [comment]
Yup I see your point. There is Array support but only for props:
https://github.com/facebook/react-native/blob/v0.68.1/packages/react-native-codegen/src/parsers/flow/components/props.js

What you're looking for is Array support for events.

This is somehow related to https://github.com/facebook/react-native/issues/34072

**Comment by Milker90** [comment]
@cortinico I also encountered an Array property related issue when I tried to use fabric components

JavaScript Specification
```ts
interface AIRMapPolylineProps extends ViewProps {
  coordinates: ReadonlyArray<Readonly<{
    latitude: Double;
    longitude: Double;
  }>>;
}
```

Codegen
```C++

class AIRMapPolylineProps final : public ViewProps {
 public:
  AIRMapPolylineProps() = default;
  AIRMapPolylineProps(const PropsParserContext& context, const AIRMapPolylineProps &sourceProps, const RawProps &rawProps);

#pragma mark - Props

  std::vector<AIRMapPolylineCoordinatesStruct> coordinates{};
  SharedColor strokeColor{};
  std::vector<SharedColor> strokeColors{};
  Float strokeWidth{0.0};
  AIRMapPolylineLineCap lineCap{AIRMapPolylineLineCap::Butt};
  AIRMapPolylineLineJoin lineJoin{AIRMapPolylineLineJoin::Miter};
  Float miterLimit{0.0};
  Float lineDashPhase{0.0};
  std::vector<int> lineDashPattern{};
  bool geodesic{false};
};

struct AIRMapPolylineCoordinatesStruct {
  double latitude;
  double longitude;
};

static inline void fromRawValue(const PropsParserContext& context, const RawValue &value, AIRMapPolylineCoordinatesStruct &result) {
  auto map = (butter::map<std::string, RawValue>)value;

  auto tmp_latitude = map.find("latitude");
  if (tmp_latitude != map.end()) {
    fromRawValue(context, tmp_latitude->second, result.latitude);
  }
  auto tmp_longitude = map.find("longitude");
  if (tmp_longitude != map.end()) {
    fromRawValue(context, tmp_longitude->second, result.longitude);
  }
}

static inline std::string toString(const AIRMapPolylineCoordinatesStruct &value) {
  return "[Object AIRMapPolylineCoordinatesStruct]";
}
```

But compiling the project fails, please help me with some advice how to fix it, thanks!

<img width="1016" alt="截屏2022-08-12 15 03 22" src="https://user-images.githubusercontent.com/3938006/184302119-2b22d3d7-4362-4552-9d5b-af519f0052fa.png">

**Comment by cipolleschi** [comment]
We are tracking this use case internally to make the codegen more feature complete. Closing this issue for the time being.
