### ISSUE TITLE
Icons shown incorrectly in IOS device after build with TestFlight

### ISSUE THREAD

**Issue by alickcai** [facebook/react-native#34286]
### Description

After release build for IOS and open with TestFilght, icons are shown incorrectly:
![image](https://user-images.githubusercontent.com/110021679/181224003-4211df70-a4a2-4b5c-a408-4afee96a4cb3.png)

No issue for Android and before build IOS
![image](https://user-images.githubusercontent.com/110021679/181224149-e849eb8a-ee27-4e6c-99e5-c0d4866d090b.png)

All icons I put in asset folder are PNG file (converted from AI, not PNG 8, ~128*128 pixels)
![image](https://user-images.githubusercontent.com/110021679/181224304-b20106e7-fc20-482b-a509-22a72c917a20.png)

Can anybody help? thanks in advance

### Version

0.68.2

### Output of `npx react-native info`

    "expo": "~45.0.0",
    "expo-av": "~11.2.3",
    "expo-camera": "~12.2.0",
    "expo-dev-client": "~1.0.1",
    "expo-device": "~4.2.0",
    "expo-error-recovery": "~3.1.0",
    "expo-media-library": "~14.1.0",
    "expo-status-bar": "~1.3.0",
    "expo-video-player": "^2.1.0",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-native": "0.68.2",
    "react-native-animatable": "^1.3.3",
    "react-native-error-boundary": "^1.1.14",
    "react-native-exit-app": "^1.1.0",
    "react-native-safe-area-context": "4.2.4",
    "react-native-screens": "~3.11.1",
    "react-native-web": "0.17.7"

### Steps to reproduce

sample file for icon
![takePhoto](https://user-images.githubusercontent.com/110021679/181225232-eddaa0fb-cbe8-4edc-a7ba-32c98db66967.png)

built using Expo 
eas build --profile development --platform ios

Expo version:
├── eas-cli@0.55.1
└── expo-cli@5.5.1

### Snack, code example, screenshot, or link to a repository

nothing special, just like:

export function ButtonIcon(probs) {
  return (
    <Pressable
      ref={probs.ref}
      onPress={probs.onPress}
      style={({ pressed }) => [styles.buttonContainIcon, { backgroundColor: pressed ? Scolor.blueLL : Scolor.trans }]}
    >
      <Image style={styles.buttonIcon} source={probs.source}></Image>
    </Pressable>
  );

style--------------------
  buttonIcon: {
    width: 24,
    height: 24,
    resizeMode: "center",
  },

**Comment by cortinico** [comment]
> built using Expo

Have you opened an issue on the Expo repository as well?

**Comment by alickcai** [comment]
Yes, I have opened on the Expo repository as well, #4485

**Comment by cortinico** [comment]
> Yes, I have opened on the Expo repository as well, #4485

The issue you linked is 7 years old. Are you sure is the correct one?

**Comment by alickcai** [comment]
try this one:

https://github.com/expo/expo-cli/issues/4485

![image](https://user-images.githubusercontent.com/110021679/182012502-ccf3db1d-92cd-4204-89f3-5c9850b774a7.png)

**Comment by alickcai** [comment]
Solved by changing "resizeMode" to "contain" (previously was "center"):

  buttonIcon: {
    width: 24,
    height: 24,
    resizeMode: "contain",
  },
