### ISSUE TITLE
Why we need Object.freeze(obj[key]) in StyleSheet.create only in DEV?

### ISSUE THREAD

**Issue by Bibazavr** [facebook/react-native#34293]
### Description

It's strange and why only in dev?

First arrive Object.freeze:

- [was](https://github.com/facebook/react-native/blame/722f88ca9058c5d902c416b826a7a7ab347326b8/Libraries/StyleSheet/StyleSheet.js):
- [became](https://github.com/facebook/react-native/blame/a8e3c7f5780516eb0297830632862484ad032c10/Libraries/StyleSheet/StyleSheet.js):
- [and now Object.freeze still there](https://github.com/facebook/react-native/blob/main/Libraries/StyleSheet/StyleSheet.js#L364):

Do we really need it? Without freeze all works fine:o 

### Version

all from a8e3c7f5780516eb0297830632862484ad032c10

### Output of `npx react-native info`

dosent mater but if you want:

```
System:
    OS: macOS 12.4
    CPU: (10) arm64 Apple M1 Max
    Memory: 327.95 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.1 - /usr/local/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 8.12.1 - /opt/homebrew/bin/npm
    Watchman: 2022.06.20.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 28, 30, 31, 33
      Build Tools: 29.0.2, 30.0.2, 31.0.0, 33.0.0
      System Images: android-33 | Google Play ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.0 => 0.68.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

```

### Steps to reproduce

- change some value in StyleSheet.create obj like in code example

Expected result:

- value changed in DEV and prod variant

Actual result:

- value changed in prod variant and not changed in DEV variant

### Snack, code example, screenshot, or link to a repository

dummy example:

```ts
import {Button, StyleSheet, View} from 'react-native';
import React, {useState} from 'react';

export enum ITypes {
  primary = 'primary',
  disabled = 'disabled',
}

const primaryStyle = () => {
  return StyleSheet.create({
    container: {
      padding: 10,
      backgroundColor: 'red',
    },
  });
};

const disabledStyle = () => {
  const defaultStyles = primaryStyle();

  defaultStyles.container.backgroundColor = 'grey';

  return defaultStyles;
};

const stylesCreate = (type: ITypes) => {
  switch (type) {
    case ITypes.primary:
      return primaryStyle();
    case ITypes.disabled:
      return disabledStyle();
    default:
      return primaryStyle();
  }
};

const Test = () => {
  const [type, setType] = useState(ITypes.primary);
  const styles = stylesCreate(type);
  return (
    <View style={styles.container}>
      <Button
        title={type}
        onPress={() =>
          type === ITypes.primary
            ? setType(ITypes.disabled)
            : setType(ITypes.primary)
        }
      />
    </View>
  );
};


```

**Comment by danilobuerger** [comment]
You are not supposed to modify the values of a created stylesheet, thats why its frozen. Its enabled for dev only because it costs too much performance in prod.

**Comment by Bibazavr** [comment]
@danilobuerger, Thanks you for fast reply but why not supposed to modify? 

when I modified the values of a created stylesheet I didn't find memory leak or something like that  (or maybe I was blinded:c)

**Comment by danilobuerger** [comment]
Previously the function performed some more tasks:
* A check similar to prop-types which was removed in rn 66. (https://github.com/facebook/react-native/commit/2e8c0bd7ea7db1aac183eb7f656772d3cffcb132)
* A global style sheets registry which would return a number instead of the object allowing for further performance optimizations (which were never realised) of only sending the style sheet over the bridge once. Removed in rn 56 (https://github.com/facebook/react-native/commit/a8e3c7f5780516eb0297830632862484ad032c10)

Now a days its more of a convention and legacy. When using typescript you still get the right typings. Also future performance optimizations are still possible. 

Anyway, just create multiple style objects and select the one you need instead of modifying them.

**Comment by Bibazavr** [comment]
Thanks for the explanation:3

> Anyway, just create multiple style objects and select the one you need instead of modifying them.

This is a good idea when you don't have too many values in StyleSheet.create:)

But when there are a lot of them, it becomes difficult to maintain such code:o

---

Because instead of 1 change in the parent style, you need to make 5 (depends on count of objects from StyleSheet.create) changes to other StyleSheet.create 

For example, you have something like that:
```ts
const mainStyles = (theme) => StyleSheet.create({
    container: {
      padding: 10,
      margin: 10,
      padding: theme.spaces.Space8,
      borderRadius: theme.spaces.Space8,
      borderWidth: theme.spaces.Space2,
      borderColor: focused ? colors.BorderNormal : 'transparent',
      marginVertical: theme.spaces.Space8,
      minWidth: 120,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      backgroundColor: 'red',
    },
  });

const secondStyles = (theme) => StyleSheet.create({
    container: {
      padding: 10,
      margin: 10,
      padding: theme.spaces.Space8,
      borderRadius: theme.spaces.Space8,
      borderWidth: theme.spaces.Space2,
      borderColor: focused ? colors.BorderNormal : 'transparent',
      marginVertical: theme.spaces.Space8,
      minWidth: 120,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      backgroundColor: 'grey',
    },
  });
```
And when you need to change margins you have to do 2 changes instead of one in mainStyles:c

---

Or use a spread operator like `{...mainStyles, backgroundColor: 'red'}` but it can affect performance, especially when using big list or something like that

---

Hope I'm not bugging you up at all 

Anyway,  thank you one more time:)

**Comment by danilobuerger** [comment]
```
const styles = StyleSheet.create({
    container: {
      ...
    },
    primary: {
      backgroundColor: 'red',
    },
    disabled: {
      backgroundColor: 'grey',
    },
});
<View style={[styles.container, disabled ? styles.disabled : styles.primary]} />
```

**Comment by Bibazavr** [comment]
You code is good for simple disable style:o

But when you have a multi theme app with custom color's (like telegram with custom theme) or  a lot of style variants for component - all came complex:c
