### ISSUE TITLE
Android application is crashing in release mode

### ISSUE THREAD

**Issue by pushpender-singh-ap** [facebook/react-native#34297]
### Description

exception.class.missing._Unknown_: 
  at com.facebook.react.modules.core.ExceptionsManagerModule.reportException (Unknown Source:75)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.facebook.react.bridge.JavaMethodWrapper.invoke (Unknown Source:148)
  at com.facebook.react.bridge.JavaModuleWrapper.invoke (Unknown Source:147)
  at com.facebook.react.bridge.queue.NativeRunnable.run (Native Method)
  at android.os.Handler.handleCallback (Handler.java:938)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage (Unknown Source)
  at android.os.Looper.loopOnce (Looper.java:233)
  at android.os.Looper.loop (Looper.java:334)
  at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run (Unknown Source:37)
  at java.lang.Thread.run (Thread.java:920)

### Version

0.69.1

### Output of `npx react-native info`

System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1
    Memory: 113.94 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 8.3.1 - /usr/local/bin/npm
    Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 28, 29, 30, 31, 32
      Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0, 33.0.0, 33.0.0
      System Images: android-32 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 12.0.2 - /Library/Java/JavaVirtualMachines/jdk-12.0.2.jdk/Contents/Home/bin//javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.1 => 0.69.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

The issue was discovered in the Google Play Console for Vivo V2055 Android 12 (SDK 31).

<img width="1110" alt="Screenshot 2022-07-28 at 10 35 13 PM" src="https://user-images.githubusercontent.com/73298854/181596440-722615e7-9339-4871-89d8-4d87878d53ba.png">

### Snack, code example, screenshot, or link to a repository

My apologies for not being able to reproduce this issue.

**Comment by cortinico** [comment]
Are you able to provide a non obfuscated stacktrace?
Otherwise having a repro for this crash would be helpful, thanks.

**Comment by pushpender-singh-ap** [comment]
> My apologies for not being able to reproduce this issue.

My apologies for not being able to reproduce this issue.

**Comment by gentlemanJie** [comment]
牛逼

**Comment by bodrius** [comment]
the same issue

`FATAL EXCEPTION: mqt_native_modules
Process: com.online.vdf, PID: 23750
f7.c: TypeError: null is not an object (evaluating 'c.SIGN_IN_CANCELLED'), stack:
<unknown>@503:3985
h@2:1585
d@2:958
get@502:215
<unknown>@10:1338
Ul@64:66789
Ha@64:84456
<unknown>@64:82784
Y@180:2883
e@180:400
<unknown>@90:1256
k@90:499
callTimers@90:2652
value@45:3556
<unknown>@45:673
value@45:2503
value@45:645
value@-1
	at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(Unknown Source:134)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(Unknown Source:148)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(Unknown Source:147)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(Unknown Source:0)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(Unknown Source:37)
	at java.lang.Thread.run(Thread.java:1012)`

**Comment by Shmublon** [comment]
I have the same issue

**Comment by bodrius** [comment]
Hi everyone,
I have already fixed this error.
Please follow the next steps:
1) go to folder Android-->app-->src-->main-->assets  and find file name index.android.bundle
2) remove all data from this file 
3) generate new data, command: `react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res`

then, try to run your app through Android Studio

hope it is helpful

**Comment by pushpender-singh-ap** [comment]
> Hi everyone, I have already fixed this error. Please follow the next steps:
> 
> 1. go to folder Android-->app-->src-->main-->assets  and find file name index.android.bundle
> 2. remove all data from this file
> 3. generate new data, command: `react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res`
> 
> then, try to run your app through Android Studio
> 
> hope it is helpful

Because I do not use this command to build android applications, index.android.bundle is not available in my application. Instead I use `cd android && ./gradlew bundleRelease`.

**Comment by bodrius** [comment]
> > Hi everyone, I have already fixed this error. Please follow the next steps:
> > 
> > 1. go to folder Android-->app-->src-->main-->assets  and find file name index.android.bundle
> > 2. remove all data from this file
> > 3. generate new data, command: `react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res`
> > 
> > then, try to run your app through Android Studio
> > hope it is helpful
> 
> Because I do not use this command to build android applications, index.android.bundle is not available in my application. Instead I use `cd android && ./gradlew bundleRelease`.

everyone has this file, it is created when the project is initialized

**Comment by pushpender-singh-ap** [comment]
> > > Hi everyone, I have already fixed this error. Please follow the next steps:
> > > 
> > > 1. go to folder Android-->app-->src-->main-->assets  and find file name index.android.bundle
> > > 2. remove all data from this file
> > > 3. generate new data, command: `react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res`
> > > 
> > > then, try to run your app through Android Studio
> > > hope it is helpful
> > 
> > 
> > Because I do not use this command to build android applications, index.android.bundle is not available in my application. Instead I use `cd android && ./gradlew bundleRelease`.
> 
> everyone has this file, it is created when the project is initialized

but in my case, it’s not there.

**Comment by bodrius** [comment]
create this file 
and run this command `react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res`
<img width="294" alt="Screenshot 2022-08-15 at 15 11 48" src="https://user-images.githubusercontent.com/57833393/184632977-121a13ae-3898-4444-8e0f-8458586bffa0.png">

**Comment by pushpender-singh-ap** [comment]
> create this file and run this command `react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res` <img alt="Screenshot 2022-08-15 at 15 11 48" width="294" src="https://user-images.githubusercontent.com/57833393/184632977-121a13ae-3898-4444-8e0f-8458586bffa0.png">

using this command make sometimes duplicates of resources I prefer this command only in debug mode when I need to send apk and in release mode, it's not required.

**Comment by pushpender-singh-ap** [comment]
> create this file and run this command `react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res` <img alt="Screenshot 2022-08-15 at 15 11 48" width="294" src="https://user-images.githubusercontent.com/57833393/184632977-121a13ae-3898-4444-8e0f-8458586bffa0.png">

I don't think because of index.android.bundle file this problem occurs.

**Comment by maheshwarimrinal** [comment]
<img width="945" alt="Screenshot 2022-09-29 at 6 11 42 PM" src="https://user-images.githubusercontent.com/11848011/193034036-f65fe3a3-dcb8-4959-8f68-c54de49b89aa.png">

I am facing the same issue in release mode, got this error in **Logcat** after updating to 0.70.1. Anyone know the fix please let me know. Followed the [guide](https://reactnative.dev/docs/signed-apk-android) provided on website

**Comment by cortinico** [comment]
Asking again if someone can provide a reproducer.
Moreover, knowing if you're using flavors or not, would be helpful to understand what's the issue here.

**Comment by cortinico** [comment]
Closing as no one provided a reproducer for ~6 months
