### ISSUE TITLE
Native modules return empty object {}

### ISSUE THREAD

**Issue by aleluiah** [facebook/react-native#34309]
### Description

import { NativeModules } from 'react-native';
 const { MyModule } = NativeModules;
my MyModule is null and native modules return empty object it works in previous versions. This works in previous react native versions

### Version

0.69.1

### Output of `npx react-native info`

MyModule is null and NodeModules object is an empty object {}

### Steps to reproduce

![kk](https://user-images.githubusercontent.com/65899491/181914311-40e12ad4-5ed1-42e4-9115-79bb3cbf7bf6.jpg)

### Snack, code example, screenshot, or link to a repository

![kk](https://user-images.githubusercontent.com/65899491/181914411-b1844d8e-bfe3-4377-969e-63d3316ef042.jpg)

**Comment by runtothedoor** [comment]
Does your module have react methods? Otherwise the object will return empty. Are you sure you are registering the module correctly in the native files?

**Comment by cortinico** [comment]
Closing as your code is impossible to read. Please post a proper reproducer and re-open.

**Comment by Bob-JZhao** [comment]
Hey @runtothedoor , I having the same issue, the reproduce steps are: use `npx react-native init AwesomeProject` to create a new project with latest react native version, then follow this doc [native-modules-ios](https://reactnative.dev/docs/native-modules-ios) to try to add a native module, but the NativeModules always returns {}. Thanks in advance! 
> Does your module have react methods? Otherwise the object will return empty. Are you sure you are registering the module correctly in the native files?
