### ISSUE TITLE
Difference in emitting ScrollView `onScroll` events between Paper and Fabric on iOS

### ISSUE THREAD

**Issue by tomekzaw** [facebook/react-native#34327]
### Description

Hello! @naftalibeder reported an issue in Reanimated (https://github.com/software-mansion/react-native-reanimated/issues/3434) that seems to be caused by a difference in the behaviour of `ScrollView` in react-native on iOS between the old and the new architecture:
* https://github.com/software-mansion/react-native-reanimated/issues/3434

The root cause of the issue is that **on Paper, the `scrollTo` method did not trigger the `onScroll` callback if the previous and next offsets were identical**, but on iOS with Fabric enabled, the callback is invoked again, thus entering a loop in this specific case. Also, this doesn't match the behaviour of Android with Fabric enabled which is identical to Android and iOS on Paper.

| Platform | Paper | Fabric |
|:-:|:-:|:-:|
| Android | ✅ | ✅ |
| iOS | ✅ | 🤔 |

### Version

0.69.3

### Output of `npx react-native info`

```
System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1 Pro
    Memory: 315.94 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.0.0 - /opt/homebrew/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.6.0 - /opt/homebrew/bin/npm
    Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 28, 29, 30, 31, 32
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0
      System Images: android-31 | Google Play ARM 64 v8a, android-32 | Google APIs ARM 64 v8a, android-32 | Google Play ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1. Launch the app
2. Scroll the scroll view
3. Check logs in the console to see if the callback loops

### Snack, code example, screenshot, or link to a repository

https://snack.expo.dev/NM_FvvFI7

### Screen recordings

1. iOS with Fabric enabled (the issue occurs here):

https://user-images.githubusercontent.com/20516055/182342232-24d76e58-9337-4290-8236-baabf9238ecf.mov

2. Android with Fabric enabled (works as expected):

https://user-images.githubusercontent.com/20516055/182343433-c652d53e-71d2-4edf-a6fb-48665a7a5d60.mov

3. iOS with Paper (for comparision purposes):

https://user-images.githubusercontent.com/20516055/182343490-9f3f85e9-44d9-4b5c-89ec-bc32feb4ad13.mov

4. Android with Paper (for comparision purposes):

https://user-images.githubusercontent.com/20516055/182343543-945af616-cd92-4bd2-929a-73652a0ba25c.mov

**Comment by cortinico** [comment]
I believe @sammy-SC should be able to help here

**Comment by sammy-SC** [comment]
Hello @tomekzaw,

this indeed looks like intended behaviour. I created a fix for a review. Will keep you updated.

Thanks for the report!

**Comment by sammy-SC** [comment]
This should fix it: https://github.com/facebook/react-native/commit/dfbf7d4e142a35c5380019a3b485cbad0922e063

Let me know in case it is still an issue.

**Comment by tomekzaw** [comment]
@sammy-SC Thank you for your quick response and the fix.

I can confirm that this PR restores the original behaviour from the old architecture in React Native (see the attached screen recording) as well as resolves the related issue in Reanimated. 🎉 

https://user-images.githubusercontent.com/20516055/183507049-6295532c-55e6-4dcf-a418-ede014cb7d82.mov

**Comment by Nader-CS** [comment]
this issue still exist in "react-native": "0.81.6", and "react-native-reanimated": "3.19.5",
