### ISSUE TITLE
[Android] useWindowDimensions() hook behavior with PiP window on Android

### ISSUE THREAD

**Issue by BhargaviAnnadevara-MSFT** [facebook/react-native#34324]
### Description

We have observed that the RN hook [useWindowDimensions](https://reactnative.dev/docs/usewindowdimensions) does not return the correct **window** dimensions on **Android** when there is a **Picture-in-Picture (PiP)** layout involved.

We have an app that displays some cards on the screen. The dimensions of the cards (width/height) are calculated based on the application window's size. So, the cards are automatically rendered/re-rendered when the `useWindowDimensions` hook detects changes in screen size, making it responsive.

However, when there is a PiP window that overlays on the main screen, the `useWindowDimensions` hook returns the dimensions of the PiP window instead of the main application window, which impacts the size of the cards, resulting in a cluttered layout.

Here is how it looks:

https://user-images.githubusercontent.com/44050820/182227733-f8ddc663-8f15-4473-962f-f5c4a1e3ad63.mp4

In the above scenario, the cards assume 100% width of the screen, which works as expected, as can be seen when the device orientation changes from portrait to landscape mode. But, when a PiP window is spawned, subsequent UI redraws pick up the incorrect dimensions (that of the PiP window) that alters the card layout. Same is the behaviour when [useDimensions](https://github.com/react-native-community/react-native-hooks#usedimensions) hook from the community [React Native hooks](https://github.com/react-native-community/react-native-hooks) library is used.

While looking at some of the open issues reported about the `useWindowDimensions` hook, we came across a [comment](https://github.com/facebook/react-native/issues/30371#issuecomment-794430866) that suggests the [`useSafeAreaFrame()`](https://github.com/th3rdwave/react-native-safe-area-context#usesafeareaframe) hook from `react-native-safe-area-context` library as an alternative to using the underlying Dimensions API. And indeed, this issue does not occur when `useWindowDimensions()` is replaced with `useSafeAreaFrame()`.

The cards scale according to screen size with `useSafeAreaFrame()`:

https://user-images.githubusercontent.com/44050820/182231971-ce03616c-3fff-420d-87d5-bbc4e4371b32.mp4

While this can be a workaround, the issue with `useWindowDimensions` with PiP involved should be fixed.

### Version

0.64.2

### Output of `npx react-native info`

```
System:
    OS: macOS 12.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 17.85 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.15.4 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 6.14.10 - /usr/local/bin/npm
    Watchman: 2022.07.04.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 28, 29, 30, 31, 32
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 32.0.0
      System Images: android-31 | Intel x86 Atom_64, android-31 | Google APIs ARM 64 v8a, android-31 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8309675
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.3 => 0.64.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

Code repo for the sample RN app shown is linked below. Follow steps shown in the attached videos in the issue description above to repro the issue.

### Snack, code example, screenshot, or link to a repository

[Link to code repository](https://github.com/BhargaviAnnadevara-MSFT/RnAndroidPipSample)

**Comment by iway1** [comment]
If there's one thing I've learned about window dimensions in React Native, it's this: Don't use React Natives built in window dimensions APIs. They never work in all circumstances, and behavior is inconsistent across devices.

The best thing to do, IMO, is to just measure the root view yourself via `onLayout` and pass it via a context. It is guaranteed to work on any device and won't give you the strange behavior like you're describing. 

Not sure it's worth even bothering the React Native team with this type of thing at all, since there have been issues with their APIs for ages and it doesn't seem like they have any interest in prioritizing fixing them:

https://github.com/facebook/react-native/issues/23693

I love you, React Native Team btw, but it is pretty clear they're not going to fix the window dimensions bugs. Just default to measuring and you never have to worry about it.

**Comment by bryanltobing** [comment]
this is still an issue
