### ISSUE TITLE
Flipper not enabled for custom Xcode configurations

### ISSUE THREAD

**Issue by scarlac** [facebook/react-native#34332]
### Description

**The problem:**
Flipper does not find app if the Xcode build configuration is renamed from "Debug" to "Banana" (anything other than "Debug").

**The recommended workaround (does not work):**
Add your custom xcode build configuration name in the Podfile, such that cocoapods generates the correct xcconfig files, and `use_flipper(...)` must be passed a list of configurations that it should work for.

**The problem:**
The workaround does not work _fully_. It correctly adds `-DFB_SONARKIT_ENABLED=1` to the main project but fails to add it to the `React-Core` pod.
This causes Flipper to recoginize the simulator but fail to find the app, causing this message to appear in Flipper:
![Screen Shot 2022-08-02 at 12 20 30](https://user-images.githubusercontent.com/895369/182456107-2f44d924-72f6-4d55-8039-1df149a0229e.jpg)
("NO APPLICATION SELECTED")

**The actual workaround (works for me):**
- Use `patch-package` to add your debug configurations to React Native's `scripts/react_native_pods.rb` file such that it adds the preprocessor variable/value, or
- Manually add the flag in Xcode to the custom "Banana" config for "Other C Flags":
![Screen Shot 2022-08-02 at 12 26 48](https://user-images.githubusercontent.com/895369/182457396-e06aa93c-9ba4-49bf-a6c9-9e2b27bcc7e1.jpg)

**The cause:**
Some important definitions as I understand them - because they can be quite confusion to discuss otherwise:
- Xcode **scheme**: The top bar drop down in Xcode where you select a scheme. A scheme points to a build configuration and defines if a build is debuggable, among other things.
- Xcode **build configuration**: A scheme points to a build configuration, which is defined in part by the `.xcconfig` files
`react_native_post_install(installer)`: A function that calls `flipper_post_install` which installs Flipper in the build configurations. The default configurations are "Release" and "Debug".

While this change introduced a fix for standard installations, it fixes with a hardcoded configuration name, which silently fails/gets ignore despite all flags being set correctly for the project itself (for v0.68.2):
https://github.com/facebook/react-native/pull/33499/files#diff-adcf572f001c2b710d14f409c14763f1a50b08369b3034548f1602685d21f67f
(and [this line in main at the time of writing, from 'main' branch](https://github.com/cipolleschi/react-native/blob/f3db6cc52792e3006a16408df4ae40f3aee19a86/scripts/cocoapods/flipper.rb#L86))

**A proposal for a fix?**
Instead of a hardcoded `"Debug"` configuration, we should base it off of the list of provided configurations and their cocoapod mapping, e.g. the `Podfile` for this demo project is as such, and this should be the source of truth:
```ruby
project 'AwesomeProject',
  "Debug" => :debug,
  "Banana" => :debug,
  "Release" => :release
# ....
target 'AwesomeProject' do
  use_flipper!(configurations: ['Debug', 'Banana'])
  # ...
end
```

### Version

0.68.2

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 12.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 346.95 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.2/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
    Watchman: 2022.07.04.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/sesoliman/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 30, 31, 32
      Build Tools: 30.0.2, 32.0.0
      System Images: android-28 | ARM 64 v8a, android-32 | Google APIs ARM 64 v8a, android-32 | Google Play ARM 64 v8a, android-33 | Google Play ARM 64 v8a
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.2 => 0.68.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. Create a project using `npx react-native init AwesomeProject`, i.e. follow the general guide
2. `xed ios/` to open the workspace in Xcode
3. Rename or clone the build configuration from "Debug" to "Banana"
4. Add the recommended changes to `ios/Podfile`
```
project 'AwesomeProject',
  "Debug" => :debug, # in this case I cloned the config instead of renaming it
  "Banana" => :debug,
  "Release" => :release
```
and
```
use_flipper!(configurations: ['Debug', 'Banana'])
```
6. Run `cd ios && pod install`
7. Run the project
8. Open Flipper
9. No plugins will be available, the error "NO APPLICATION SELECTED" will appear

### Snack, code example, screenshot, or link to a repository

Banana config added to new project:
![Screen Shot 2022-08-02 at 12 38 05](https://user-images.githubusercontent.com/895369/182459222-a5b64242-a37e-42bf-8b26-fd6342ed85d3.jpg)

Confirmation that despite making the necessary `Podfile` changes,
the React-Config pod is still missing the correct build flag:
![Screen Shot 2022-08-02 at 12 40 59](https://user-images.githubusercontent.com/895369/182459645-03bcc328-ac82-4972-ab1d-e720a5c6c089.jpg)

**Comment by scarlac** [comment]
Generic workaround, that we should probably integrate into the actual flipper.rb file in main:
1. `Podfile` changes, add a call to `apply_flipper_fix(installer)` and then add the definition for the function shown below:
```ruby
target 'AwesomeProject' do
  # ...
  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    # add this AFTER react_native_post_install(...):
    apply_flipper_fix(installer) 
  end
end

# Fix for https://github.com/facebook/react-native/issues/34332
def apply_flipper_fix(installer)
  installer.pods_project.targets.each do |target|
    if target.name == 'React-Core'
      target.build_configurations.each do |config|
        if config.debug?
          puts "Enabling Flipper for build configuration '#{config.name}'"
          # For 0.68.2. Note that main branch now uses GCC_PREPROCESSOR_DEFINITIONS: 
          # https://github.com/cipolleschi/react-native/blob/f3db6cc52792e3006a16408df4ae40f3aee19a86/scripts/cocoapods/flipper.rb#L87
          config.build_settings['OTHER_CFLAGS'] = "$(inherited) -DFB_SONARKIT_ENABLED=1"
        end
      end
    end
  end
end
```

**Comment by plackyfantacky** [comment]
Had a similar problem and somehow this workaround fixed everything for me. The Pods project in my app didn't have a react-core target:

![Screenshot 2022-11-21 at 2 52 21 pm](https://user-images.githubusercontent.com/2724084/202984118-40d3f9e8-6d6a-498c-8f45-74aacd2b80c5.png)

...but I did have a `React-Core-1aa923ac` target which had no `-DFB_SONARKIT_ENABLED=1 ` flag. Once I added that in manually, Flipper started working for me (finally).

I did try the `apply_flipper_fix` code above but it didn't work for me. I suspect its because in my project the target is named `React-Core-1aa923ac` and not just `React-Core`. I don't suppose there is a way to search for a target name based on a partial name?

**Comment by flybluewolf** [comment]
> Had a similar problem and somehow this workaround fixed everything for me. The Pods project in my app didn't have a react-core target:
> 
> ![Screenshot 2022-11-21 at 2 52 21 pm](https://user-images.githubusercontent.com/2724084/202984118-40d3f9e8-6d6a-498c-8f45-74aacd2b80c5.png)
> 
> ...but I did have a `React-Core-1aa923ac` target which had no `-DFB_SONARKIT_ENABLED=1 ` flag. Once I added that in manually, Flipper started working for me (finally).
> 
> I did try the `apply_flipper_fix` code above but it didn't work for me. I suspect its because in my project the target is named `React-Core-1aa923ac` and not just `React-Core`. I don't suppose there is a way to search for a target name based on a partial name?

```
# if target.name == 'React-Core' 
if target.name.start_with?('React-Core')
```
I worked fine.

**Comment by nermeen2711** [comment]
@scarlac I tried your solution but it didn't work for me !!
when i run my app with custom configuration flipper not detect it also when i run pod install after adding your code and it gives me:
Enabling Flipper for build configuration: Debug
Enabling Flipper for build configuration: Custom.Debug

it run successfully but flipper not work !
