### ISSUE TITLE
Filled TextInput sends an event with empty ev.nativeEvent.text after switching secureTextEntry from false to true

### ISSUE THREAD

**Issue by ws-fegon** [facebook/react-native#34337]
### Description

This is a common situation when you need to make an password input with show/hide functionality.
Found the bug on iOS simulator. 
When you entered a few symblols on field then switched **secureTextEntry** to false and continue typing you lose the symbols entered before

I found an unexpected event with empty text appears after first changing after switching secureTextEntry from **false** to **true**
<img width="898" alt="Screenshot 2022-08-03 at 11 32 09" src="https://user-images.githubusercontent.com/6111214/182563932-7f0540db-cfb0-4fe3-83c0-838d973e7fc4.png">

https://user-images.githubusercontent.com/6111214/182563944-f87cd5ff-0376-4645-80f1-09b118f5daba.mov

It also reproducable on the sandbox on your official documentation (but only on iOS platform)

### Version

0.69.3

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 12.5
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 76.31 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.7.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.15.0 - /usr/local/bin/npm
    Watchman: 2022.07.04.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 13.4/13F17a - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: ^0.69.3 => 0.69.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. Enter some symbols 
2. Click on "show" button
3. Click on "hide" button
4. Enter 1 more symbol. 
5. You can see that symbols entered on the 1st step disappeared

### Snack, code example, screenshot, or link to a repository

https://snack.expo.dev/Xv_j_Aure (only iOS, can't reproduce on Web or Android)
<img width="960" alt="Screenshot 2022-08-03 at 11 39 13" src="https://user-images.githubusercontent.com/6111214/182564098-f583757b-965f-4b2d-b51b-ddf1818e79cf.png">

**Comment by AntoineDoubovetzky** [comment]
It seems to be a native behavior ([source](https://stackoverflow.com/questions/7305538/uitextfield-with-secure-entry-always-getting-cleared-before-editing)).

We could optionally override this behavior with a prop, but I am not sure we want to add another prop to the TextInput component.

I'd be happy to work on this, but I'll wait for confirmation from a maintainer that this is a feature we actually want.

**Comment by AlgoRoots** [comment]
I am facing the same issue. any solution please?

**Comment by 4yki** [comment]
would be nice to have option as a prop for this behavior...

**Comment by hendyyou** [comment]
would be nice to have option as a prop for this behavior...
