### ISSUE TITLE
Cannot use expo app in android 12.1

### ISSUE THREAD

**Issue by shvamabps** [facebook/react-native#34340]
### Description

I created the app using the command ` npx exp init myapp` and also installed the expo-cli globally. In both scenarios, the expo app present in the google play store was not able to detect the application running in the project. 

### Version

0.68.2

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: Linux 5.15 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
    Memory: 7.59 GB / 15.40 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.10.0 - ~/.nvm/versions/node/v16.10.0/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 7.24.0 - ~/.nvm/versions/node/v16.10.0/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.2 => 0.68.2 
  npmGlobalPackages:
    *react-native*: Not Found\

### Steps to reproduce

1. create the app using the command `npx expo init project`
2. install the expo application from the play store.
3. then run the application in the terminal
4. scan the qr code mentioned the temrinal

### Snack, code example, screenshot, or link to a repository

NONE

**Comment by runtothedoor** [comment]
I recommend opening an issue within the expo repository. Expo is a tool built on top of React Native but facebook doesn't take care of it

**Comment by cortinico** [comment]
> I recommend opening an issue within the expo repository. Expo is a tool built on top of React Native but facebook doesn't take care of it

Thanks for pointing this out @runtothedoor 
Please open an issue on github.com/expo/expo-cli
