### ISSUE TITLE
Date not working as expected when I am downgrading react-native version

### ISSUE THREAD

**Issue by TusharGameskraft** [facebook/react-native#34346]
### Description

I am trying to downgrade react-native version from 0.66.2 to 0.64.2 in order to fix some issue, I am successfully able to build the app, but there are multiple places where I am using js Date methods like toLocaleString, new Date etc, but is is giving wrong date or not formatting correctly, but works fine on version 0.66.2, any fix for the same?

System info:
(Issue in):
    "react": "^17.0.1",
    "react-native": "^0.64.2",

### Version

0.64.2

### Output of `npx react-native info`

NA

### Steps to reproduce

Expected output of :
new Date().toLocaleString('en-Us',{hour:'numeric',minute:'numeric',hour12:true})

is '3:59 AM'

but getting weird result

### Snack, code example, screenshot, or link to a repository

NA

**Comment by cortinico** [comment]
> but works fine on version 0.66.2, any fix for the same?

Most likely there was a bug in 0.64 which got fixed in a recent version.
I would suggest to don't try to downgrade and circumvent issues and instead try to update to a more recent version and handle those issues that are blocking you, as you will find more material about it.
