### ISSUE TITLE
Add types to "__mocks__/BackHandler.js"

### ISSUE THREAD

**Issue by douglasjunior** [facebook/react-native#34356]
### Description

Today when we need to mock the Android back press, the only way I found is using the `Libraries/Utilities/__mocks__/BackHandler.js` file, and then:

```js
jest.mock(
    'react-native/Libraries/Utilities/BackHandler',
    () => require('react-native/Libraries/Utilities/__mocks__/BackHandler'),
);
```

However, when using TypeScript we get an error:

```tsx
// my-test.spec.tsx

import { BackHandler } from 'react-native';

describe('My test', () => {
  it('BackHandler', () => {
      BackHandler.mockPressBack();
      // Error: Property 'mockPressBack' does not exist on type 'BackHandlerStatic'.ts(2339)
  });
});
```

My workaround is to create a `react-native.d.ts` file with:

```ts
import 'react-native';

declare module 'react-native' {
  interface BackHandlerStatic {
    mockPressBack(): void;
  }
}
```

### Version

0.68.2

### Output of `npx react-native info`

System:
    OS: macOS 12.3.1
    CPU: (8) arm64 Apple M1
    Memory: 173.70 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.16.0/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
    Watchman: 2022.05.16.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /Users/douglas.junior/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8139111
    Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.12 - /opt/homebrew/opt/openjdk@11/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.2 => 0.68.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Just create a new React Native project with TypeScript and try to create a mock for BackHandler.

### Snack, code example, screenshot, or link to a repository

N/A

**Comment by SparshaSaha** [comment]
@douglasjunior I checked the code. What seems to be happening here is that when you import BackHandler from `react-native`, you are basically requiring the backhandler that is exported from react-native and not it's mock.
<img width="896" alt="image" src="https://user-images.githubusercontent.com/22150821/183298728-39429679-d604-4b10-82a6-eac684dfd991.png">
 The type of BackHandler is BackHandlerStatic which does not have the mockOnBackPress method which is why you are getting the error.
 What you need to do is either import BackHandler from the mock directly like this:
 
```
import {BackHandler} from 'react-native/Libraries/Utilities/__mocks__/BackHandler';

describe('Test', () => {
  it('test', () => {
    console.log(BackHandler);
  });
});

```

Alternatively you could also do this in your typescript file:
```
jest.mock(
    'react-native',
    () => ({... White your own mock for BackHandler})
);
```

**Comment by douglasjunior** [comment]
@SparshaSaha thank you for your tips!

If I try to import the `BackHandler` mock directly, I got this TS error:

![image](https://user-images.githubusercontent.com/1512341/184124632-224d072f-a76c-4252-a1a5-7da1a6b1a48c.png)

So, the only solution is to add a `// @ts-ignore` to avoid the error. 😢

**Comment by douglasjunior** [comment]
About creating my on mock, the problem is that I need to dispatch the `BackHandler` listener inside the component that I'm testing.

So I'm forced to use the `Libraries/Utilities/__mocks__/BackHandler.js` to this.

**Comment by SparshaSaha** [comment]
Did you try doing this in your .ts file:

```
jest.mock(
    'react-native/Libraries/Utilities/BackHandler',
    () => require('react-native/Libraries/Utilities/__mocks__/BackHandler'),
);
```

this might also work.

**Comment by SparshaSaha** [comment]
@douglasjunior can you please share your code and also your test file. I am trying to figure out what you're exactly looking to test and why exactly do you need to call mockOnPress from your test file.

**Comment by douglasjunior** [comment]
I'm creating a Modal component that need to close when the "back button" was pressed.

So, in my tests I do:

```ts
import React from 'react';
import { StatusBar } from 'react-native';

import { render, act } from '@testing-library/react-native';
// @ts-ignore
import BackHandler from 'react-native/Libraries/Utilities/__mocks__/BackHandler';

import Modal from '.';

jest.mock('react-native/Libraries/Utilities/Platform', () => {
  const Platform = jest.requireActual(
    'react-native/Libraries/Utilities/Platform',
  );
  Platform.OS = 'android';
  return Platform;
});

const ANIMATION_DURATION = 10;

describe('Modal on Android', () => {
  it('dismissible', () => {
    const handleDismiss = jest.fn();
    const handleDismissEnd = jest.fn();

    render(
      <Modal
        visible
        onDismiss={handleDismiss}
        onDismissEnd={handleDismissEnd}
        animationDuration={ANIMATION_DURATION}
      />,
    );

    act(() => {
      BackHandler.mockPressBack();
    });

    expect(handleDismiss).toBeCalled();

    setTimeout(() => {
      expect(handleDismissEnd).toBeCalled();
    }, ANIMATION_DURATION);
  });
});
```

**Comment by SparshaSaha** [comment]
I see, so:
You are basically trying to test what happens in your code when backHandler's backPress is invoked right?
You don't really need BackHandler's implementation for that. You can very easily mock BackHandler, like this I think:

```
const handleDismiss = jest.fn();
const mockBackHandler = {
 addEventListener: jest.fn(),
 mockBackPress: jest.fn().mockImplementation(() => {
handleDismiss();
});
}

jest.mock("react-native", () => {
 return {
xyz...,
BackHandler: mockBackHandler
}
})
```

What this essentially does is that we create a mock of BackHandler which, when `mockBackPress` is called, invokes the `handleDismiss` method.

this should work fine with your code @douglasjunior . 
Let me know if this helps

**Comment by douglasjunior** [comment]
Hi @SparshaSaha, sorry for delay, I absolutely forgot about this issue.

> You are basically trying to test what happens in your code when backHandler's backPress is invoked right?
>
> You don't really need BackHandler's implementation for that. You can very easily mock BackHandler, like this I think:

I am not using using BackHandler implementation but rather own mock provided by React Native at `react-native/Libraries/Utilities/__mocks__/BackHandler`.

The only problem is that this mock has no types, so I am forced to use `// @ts-ignore`.

Except for types, everything works fine.

**Comment by jzaefferer** [comment]
While this issue is stale and closed, we've recently had the trouble of getting our customized BackHandler mock to work again. This issue was the only relevant result I found. For others running into the same issue, our solution might be useful.

With React Native 0.81.5 and new architecture, this implementation is working for us:
```ts
// yes, we mock the ios implementation to test an Android-only feature, why do you ask?
// mocking react-native/Libraries/Utilities/BackHandler directly doesn't work - that module isn't imported
jest.mock('react-native/Libraries/Utilities/BackHandler.ios', () => {
  const _backPressSubscriptions = new Set();
  const exitApp = jest.fn();
  return {
    __esModule: true,
    default: {
      exitApp,
      addEventListener: function (eventName, handler) {
        '';
        _backPressSubscriptions.add(handler);
        return {
          remove: () => {
            _backPressSubscriptions.delete(handler);
          },
        };
      },

      mockPressBack: function () {
        let invokeDefault = true;
        const subscriptions = [..._backPressSubscriptions].reverse();
        for (let i = 0; i < subscriptions.length; ++i) {
            if (subscriptions[i]()) {
              invokeDefault = false;
              break;
            }
          }
        if (invokeDefault) {
          exitApp();
        }
      },
    },
  };
});
```

**Comment by douglasjunior** [comment]
> While this issue is stale and closed, we've recently had the trouble of getting our customized BackHandler mock to work again. This issue was the only relevant result I found. For others running into the same issue, our solution might be useful.


You need to mock the iOS file because the default value of `Platform.OS` when running tests is `ios`. Try setting `Platform.OS = 'android'` in a `beforeAll` block.
