### ISSUE TITLE
Used Fabirc, how to use chrome to debug?

### ISSUE THREAD

**Issue by jgx-jay** [facebook/react-native#34365]
### Description

Before, I was using RN@0.63. 
Usually I would use debug in chrome, now how can I use it?
Or is there any other way to debug JS?
Thanks!

### Version

0.68.1

### Output of `npx react-native info`

System:
    OS: macOS 12.4
    CPU: (8) x64 Apple M1
    Memory: 23.96 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.20.0 - ~/.nvm/versions/node/v14.20.0/bin/node
    Yarn: 3.2.1 - ~/.nvm/versions/node/v14.20.0/bin/yarn
    npm: 6.14.17 - ~/.nvm/versions/node/v14.20.0/bin/npm
    Watchman: 2021.06.07.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: 22.0.6917172-beta1
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7199119
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_162 - /Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Debug in chrome

### Snack, code example, screenshot, or link to a repository

none

**Comment by cortinico** [comment]
Closing as this is a question.

> Or is there any other way to debug JS?

The recomended way to debug apps with the New Architecture is to use Flipper.
(cc @kelset for visibility + we should update the https://reactnative.dev/docs/next/debugging page).

**Comment by jgx-jay** [comment]
@cortinico 
I am still using the JSC engine, can I debug with breakpoints using Flipper?

**Comment by cortinico** [comment]
You can use the Hermes Debugger inside Flipper which offers the same debugging functionalities as the Chrome debugger
