### ISSUE TITLE
Setting Default Browser for React Native Webview 

### ISSUE THREAD

**Issue by manitalti** [facebook/react-native#34377]
### Description

Need to set Microsoft Edge as default browser for React Native Webview

### Version

0.68.2

### Output of `npx react-native info`

N/A

### Steps to reproduce

N/A

### Snack, code example, screenshot, or link to a repository

N/A

**Comment by cortinico** [comment]
> for React Native Webview

Please open this issue against: https://github.com/react-native-webview/react-native-webview
