### ISSUE TITLE
Unable to build with particular scheme for iOS with the new architecture

### ISSUE THREAD

**Issue by AbhiSharma722** [facebook/react-native#34382]
### New Version

0.69.4

### Old Version

0.68.2

### Build Target(s)

iOs Simulator in release or Dev.Debug

### Output of `react-native info`

System:
    OS: macOS 12.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 901.87 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.19.0 - ~/.nvm/versions/node/v14.19.0/bin/node
    Yarn: 3.2.1 - /usr/local/bin/yarn
    npm: 6.14.16 - ~/.nvm/versions/node/v14.19.0/bin/npm
    Watchman: 2022.05.16.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8512546
    Xcode: 13.4/13F17a - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.4 => 0.69.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Issue and Reproduction Steps

`npx react-native run-ios` is working fine, while running with scheme or configuration options, build is failing for ios with below error:
```
Undefined symbols for architecture x86_64:
  "folly::SharedMutexImpl<false, void, std::__1::atomic, false, false, false>::unlock()", referenced from:
      std::__1::unique_lock<folly::SharedMutexImpl<false, void, std::__1::atomic, false, false, false> >::~unique_lock() in AppDelegate.o
  "folly::SharedMutexImpl<false, void, std::__1::atomic, false, false, false>::lock()", referenced from:
      std::__1::unique_lock<folly::SharedMutexImpl<false, void, std::__1::atomic, false, false, false> >::unique_lock(folly::SharedMutexImpl<false, void, std::__1::atomic, false, false, false>&) in AppDelegate.o
  "folly::SharedMutexImpl<false, void, std::__1::atomic, false, false, false>::~SharedMutexImpl()", referenced from:
      facebook::react::ContextContainer::~ContextContainer() in AppDelegate.o
  "folly::SharedMutexImpl<false, void, std::__1::atomic, false, false, false>::SharedMutexImpl()", referenced from:
      facebook::react::ContextContainer::ContextContainer() in AppDelegate.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
iOS configurations:
1. Dev.Debug
2. Dev.Release
3. Release
4. Debug

Commands running successfully: 
npx react-native run-ios (picking up default scheme 'MyApplication')

Failing cmd:
npx react-native run-ios --configuration Release
npx react-native run-ios --scheme DevMyApplication --configuration Dev.Debug

**Comment by Abhi499196** [comment]
Duplicate https://github.com/facebook/react-native/issues/33764#issue-1226180208

**Comment by cortinico** [comment]
Potentially related to https://github.com/facebook/react-native/issues/33764

**Comment by AbhiSharma722** [comment]
In my case adding `PRODUCTION=1` is working but app is crashing at startup.
I have this config for flipper in `Podfile` :
```
use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :production => production,
    :hermes_enabled => true,
    :fabric_enabled => flags[:fabric_enabled],
    :flipper_configuration => FlipperConfiguration.enabled,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
 ```

**Comment by myou11** [comment]
Hello, is there any update on this issue? I am running into the same problem described above and specifying `PRODUCTION=1` is allowing me to archive the app successfully. I am not running into the issue where specifying `PRODUCTION=1` is causing the built app to crash at startup. My app is also spinning up fine on my simulator fwiw.

I'm just wondering if I have to do `PRODUCTION=1 pod install` each time I want to build the app so the Flipper dependencies get removed in the Podfile. I was under the impression that when archiving the app, the Flipper configuration should be smart enough to not bundle in Flipper. But it seems like that is not the case here as we have to manually remove the Flipper dependencies before archiving
