### ISSUE TITLE
What is the the replacement of setNativeProps in Fabric?

### ISSUE THREAD

**Issue by tufik2** [facebook/react-native#34391]
### Description

Hi ReactNative team, I know that in the new architecture you don't plan to give support to ref.setNativeProps.
So according to that premise, could you please give me an example of how is the new way to update the props of an element (View, TextInput) without forcing an update of the entire component?

I am looking around but don't find documentation yet and moving all to state generates performance issues...
forcing

### Version

0.68.0

### Output of `npx react-native info`

setNativeProps is not implemented in fabric

### Steps to reproduce

setNativeProps is not implemented in fabric

### Snack, code example, screenshot, or link to a repository

No extra data

**Comment by ecreeth** [comment]
FYI: https://reactnative.dev/docs/new-architecture-library-intro#migrating-off-setnativeprops Hope this helps

**Comment by tufik2** [comment]
thanks, @ecreeth but nop, the documentation said that now we need to move all to state, but that has a big performance impact, the idea of setNativeProp was to avoid re-render all the components and gain performance (very useful in some cases, but now without that option, we return to the same issue).

**Comment by marcaaron** [comment]
>that has a big performance impact, the idea of setNativeProp was to avoid re-render all the components and gain performance (very useful in some cases, but now without that option, we return to the previews issue, forced to re-render all the component in all cases)

I think the performance issue could in theory be resolved as there is no high bridge traffic cost? Still agree this is not a _super_ ideal migration strategy. Changing an entire application's inputs from uncontrolled to controlled is a bit rough, but unsure what the alternative would be or if it would be possible to layer the `setNativeProps()` behavior into the JSI components?

**Comment by tufik2** [comment]
In theory, should not, but the reality is different... I was testing with Fabric enabled to see if I can migrate a library that was using setNativeProp, but I found big performance issues after moving all to state, and in theory that is expected because each time you change a value, react have to validate and figure-out what to update. The original idea of setNativeProp was not to avoid all that pre-processing validations?.

**Comment by TheEhsanSarshar** [comment]
I'm also trying to create a layout animation library like framer motion that uses the FLIP technique, which basically on useLayoutEffect we should be able to use setNativeProps to reverse the current style of an Element.

**Comment by sammy-SC** [comment]
We have added setNativeProps support to Fabric. It is available in 0.72. Closing this.

Please open a new issue if you find any problems with setNativeProps in Fabric.
