### ISSUE TITLE
[Crash] React Native crashes when rendering some images

### ISSUE THREAD

**Issue by satya164** [facebook/react-native#3439]
Sometimes I'm getting this error when trying to upload an image, and the app crashes. It only happens when I'm not connected to debugger (both for dev and production builds).

10-15 17:58:50.124  15806-16396/io.scrollback.neighborhoods A/fbassert﹕ Assert (/Users/mkonicek/code/react-native/ReactAndroid/src/main/jni//first-party/jni/LocalString.cpp:36): 4 byte utf-8 encodings only valid for up to 21 bits
    --------- beginning of crash
10-15 17:58:50.124  15806-16396/io.scrollback.neighborhoods A/libc﹕ Fatal signal 11 (SIGSEGV), code 1, fault addr 0xdeadb00c in tid 16396 (b/1/480x960.jpg)

cc @mkonicek

**Comment by jaygarcia** [comment]
If you have those images, can you include them in a zip somewhere? Zip as a container so the images aren't altered so someone can test them as/is.

**Comment by satya164** [comment]
@jaygarcia Sorry for late reply. Was sick. Here is a link - https://hey-neighbor.s3.amazonaws.com/generated/content/satya164/3e8c1c34c0d9c771e159c993b43878e6/1/480x960.jpg

**Comment by satya164** [comment]
Ok, so this doesn't happen when rendering the image, but happens after uploading the image is complete. I'm not familiar with the C++ code, so cannot debug what's happening.

**Comment by satya164** [comment]
I'm gonna close this and file a new issue since it seems to be a string issue rather than image
