### ISSUE TITLE
App icon not working after upgrade from 0.64.2 to 0.69.3

### ISSUE THREAD

**Issue by AuroPick** [facebook/react-native#34393]
### Description

Recently I upgraded react-native version to 0.69.3 from 0.64.2.

Everything works normally but app icon is not working

If I change app icon file names to different names it works but I wonder why it's not working with old names

### Version

0.69.3

### Output of `npx react-native info`

System:
    OS: macOS 12.5
    CPU: (8) arm64 Apple M1
    Memory: 128.98 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.6.0 - /opt/homebrew/bin/node
    Yarn: 1.22.15 - /opt/homebrew/bin/yarn
    npm: 8.13.2 - /opt/homebrew/bin/npm
    Watchman: 2022.07.04.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8309675
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.14.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.3 => 0.69.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

upgrade react-native to 0.69.3 from 0.64.2

ic_launcher and ic_launcher_round not working

### Snack, code example, screenshot, or link to a repository

```xml
 <application android:name=".MainApplication" android:label="@string/app_name" android:icon="@mipmap/ic_launcher" android:roundIcon="@mipmap/ic_launcher_round" android:allowBackup="false" android:theme="@style/AppTheme" android:usesCleartextTraffic="true" android:largeHeap="true">
```

if I change @mipmap/ic_launcher and @mipmap/ic_launcher_round to @mipmap/ic_launche_new @mipmap/ic_launcher_round_new it works
![Ekran Resmi 2022-08-11 23 08 00](https://user-images.githubusercontent.com/53499802/184232481-6439e0fa-ecf2-41ea-8c50-96fb266f27d2.png)

**Comment by cortinico** [comment]
> Everything works normally but app icon is not working

Are you using a library to set it or are you just updating the icon asset?

**Comment by AuroPick** [comment]
> > Everything works normally but app icon is not working
> 
> Are you using a library to set it or are you just updating the icon asset?

I have my app icons under mipmap folders and I am using them in AnroidManifets.xml

if icon name is ic_launcher it is not working. if I change name to something else for example ic_launcher_new. It starts working

**Comment by cortinico** [comment]
> if icon name is ic_launcher it is not working. if I change name to something else for example ic_launcher_new. It starts working

Is this happening on a fresh project? Could you create a reproducer so I can take a look at it?

**Comment by minhas-weoveri** [comment]
I am also facing the same issue, after upgrading to o.69.4 android app icon does not showing anymore.

**Comment by basemanabulsi** [comment]
I am facing the same issue, I tried what @AuroPick suggest and it worked fine after renaming it.

**Comment by waleedshkt** [comment]
Same issue here too.

Icon with default "ic_launcher" name not showing in RN 0.69

**Comment by olrtg** [comment]
This is happening to us at work also.. after upgrading to 0.68.5 from 0.64.3. It works once after renaming the icons but then it doesn't work again.
