### ISSUE TITLE
redefinition of module 'YogaKit'

### ISSUE THREAD

**Issue by hiephuynhFDS** [facebook/react-native#34405]
### Description

redefinition of module 'yoga'
redefinition of module 'YogaKit'

### Version

0.69.4

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 12.4
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Memory: 2.16 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
    Watchman: 2022.08.08.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 23, 26, 27, 28, 29, 30, 31
      Build Tools: 26.0.2, 27.0.3, 28.0.3, 29.0.2, 29.0.3, 30.0.3, 31.0.0
      System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-31 | Google APIs ARM 64 v8a, android-31 | Google APIs Intel x86 Atom_64, android-31 | Google Play ARM 64 v8a, android-31 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.4 => 0.69.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

npx react-native init TestProject --template react-native-template-typescript 
npx react-native run-ios

### Snack, code example, screenshot, or link to a repository

TestProject/ios/Pods/Headers/Public/YogaKit/YogaKit.modulemap:1:8: redefinition of module 'YogaKit'

module yoga {

TestProject/ios/Pods/Headers/Public/yoga/Yoga.modulemap:1:8: redefinition of module 'yoga'

module YogaKit {

TestProject/ios/Pods/Headers/Public/YogaKit/YogaKit.modulemap:1:8: redefinition of module 'YogaKit'

module yoga {

**Comment by hiephuynhFDS** [comment]
there was a conflict version, I have tried to remove the react native & reinstall, worked for me

**Comment by joshua-smith4** [comment]
@hiephuynhFDS What does it mean that there was a conflict version? I have deleted node_modules and package-lock.json and reinstalled. Is that sufficient to address the "conflict version" issue?
