### ISSUE TITLE
Naming collision detected by packager when using cocoapods

### ISSUE THREAD

**Issue by hswolff** [facebook/react-native#3440]
Ran into this after upgrading from `0.11.0` to both `0.12.0` and `0.13.0-rc`.

This error didn't occur before as naming collisions were silently allowed, however now that an error is thrown I'm seeing this.

I have a pre-existing iOS app and I've integrated RN into it via Cocoapods. I also have my JavaScript source files using their own `node_modules` folder. My directory structure looks like this:

```
app/
  ios/
     Pods/
        React/
           node_modules/
  node_modules/
  src/
     index.ios.js
  package.json
```

When I now run the packager it reads the file system and reads the files found in both `node_modules`, which both have react-native installed and thus cause a name collision (as they're more or less duplicates).

I've resolved this when running the development server via:

```
./node_modules/react-native/packager/packager.sh --projectRoots `pwd`/src --projectRoots `pwd`/node_modules
```

However when trying to use the bundler it always implicitly adds the root folder as a project root, with no way to augment it or ignore a folder.

Happy to be told I'm 'doing it wrong' but I don't feel like this layout is completely abnormal.

**Comment by ide** [comment]
Good point. We might be better off pulling RN from the pod repo BUT keeping CocoaPods support alive in the form of a local podspec. The idea is that you get RN from npm and in your Podfile link to "./node_modules/react-native/React.podspec" so you can still use CocoaPods.

@hswolff would you mind giving that a try and seeing if it fixes your problem and unblocks you? If so then I'm leaning towards having this be the way that people use RN with CocoaPods.

**Comment by hswolff** [comment]
That did the trick!

I updated my `Podfile` to look like this:

```
pod 'React', :path => '../node_modules/react-native'
  pod 'React/ART', :path => '../node_modules/react-native'
  pod 'React/RCTActionSheet', :path => '../node_modules/react-native'
  pod 'React/RCTAdSupport', :path => '../node_modules/react-native'
  pod 'React/RCTGeolocation', :path => '../node_modules/react-native'
  pod 'React/RCTImage', :path => '../node_modules/react-native'
  pod 'React/RCTNetwork', :path => '../node_modules/react-native'
  pod 'React/RCTPushNotification', :path => '../node_modules/react-native'
  pod 'React/RCTSettings', :path => '../node_modules/react-native'
  pod 'React/RCTText', :path => '../node_modules/react-native'
  pod 'React/RCTVibration', :path => '../node_modules/react-native'
  pod 'React/RCTWebSocket', :path => '../node_modules/react-native'
  pod 'React/RCTLinkingIOS', :path => '../node_modules/react-native'
```

I used the [Cocoapods podfile documentation](https://guides.cocoapods.org/syntax/podfile.html#pod)
**Using the files from a local path** section for the proper syntax.

Bundling now works without issue and building from Xcode using this set-up worked as well.

**Comment by ide** [comment]
Cool, check out the `:subspecs` key too, which lets you accomplish the same thing but with a little less verbosity.

**Comment by ide** [comment]
In summary -- use the local podspec in your node_modules instead of installing from CocoaPods.

**Comment by hswolff** [comment]
Oooh awesome, nice suggestion w/ `:subspecs` @ide  - thanks!

Updated final version:

```
pod 'React', :path => '../node_modules/react-native',
    :subspecs => [
      'ART',
      'RCTActionSheet',
      'RCTAdSupport',
      'RCTGeolocation',
      'RCTImage',
      'RCTNetwork',
      'RCTPushNotification',
      'RCTSettings',
      'RCTText',
      'RCTVibration',
      'RCTWebSocket',
      'RCTLinkingIOS'
    ]
```

**Comment by corymsmith** [comment]
I have a similar issue #3558 but am not using Cocoapods, this happened after updating from 0.12.0-rc to 0.13.0-rc

**Comment by paramaggarwal** [comment]
@hswolff I am using locally linked Pods as suggested above, but still getting this:

```
Error building DependencyGraph:
 Error: Naming collision detected: /Users/Param/Documents/my-app-master/Pods/React/Libraries/ActionSheetIOS/ActionSheetIOS.js collides with /Users/Param/Documents/my-app-master/node_modules/react-native/Libraries/ActionSheetIOS/ActionSheetIOS.js
```

I believe you did not run into this at that time because the packager did not follow symlinks, but now it does!
