### ISSUE TITLE
 package management about pnpm

### ISSUE THREAD

**Issue by whaijungit** [facebook/react-native#34413]
### Description

I want to try using pnpm

### Version

0.69.4

### Output of `npx react-native info`

``` 
FAILURE: Build failed with an exception.

* Where:
Settings file 'C:\Users\whaij\Desktop\movie\android\settings.gradle' line: 2

* What went wrong:
A problem occurred evaluating settings 'movie'.
> Could not read script 'C:\Users\whaij\Desktop\movie\node_modules\@react-native-community\cli-platform-android\native_modules.gradle' as it does not exist.
```

### Steps to reproduce

```
FAILURE: Build failed with an exception.

* Where:
Settings file 'C:\Users\whaij\Desktop\movie\android\settings.gradle' line: 2

* What went wrong:
A problem occurred evaluating settings 'movie'.
> Could not read script 'C:\Users\whaij\Desktop\movie\node_modules\@react-native-community\cli-platform-android\native_modules.gradle' as it does not exist.
```

### Snack, code example, screenshot, or link to a repository

react-native cli

**Comment by whaijungit** [comment]
build successful Application flash back

**Comment by whaijungit** [comment]
The operation is as follows:
```sh
pnpm add -D @react-native-community/cli
pnpm add -D @react-native-community/cli-platform-android
```
exec scripts pnpm android 
```
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 1850 file(s) to forward-jetify. Using 8 workers...
info Starting JS server...
info Installing the app...

> Task :app:installDebug
Installing APK 'app-debug.apk' on 'SKW-A0 - 11' for :app:debug
Installed on 1 device.

BUILD SUCCESSFUL in 9s
38 actionable tasks: 2 executed, 36 up-to-date
info Connecting to the development server...
info Starting the app on "77e6c004"...
Starting: Intent { cmp=com.movie/.MainActivity }
```
In the mobile phone, click the movie app to directly flash back

**Comment by cortinico** [comment]
Closing as this looks like resolved + if this is an issue with the CLI should be opened on https://github.com/react-native-community/cli

**Comment by whaijungit** [comment]
thank your I try

**Comment by whaijungit** [comment]
> Closing as this looks like resolved + if this is an issue with the CLI should be opened on https://github.com/react-native-community/cli


thank your I try

**Comment by chenweigh** [comment]
same problem.

pnpm install 

android can not resolve many node libs

`/node_modules/@react-native-community/cli-platform-android/native_modules.gradle' as it does not exist.`

because of `@react-native-community/cli-platform-android` in .pnpm/@react-native-community/cli-platform-android@11.3.5/node_modules/@react-native-community/cli-platform-android
