### ISSUE TITLE
Fabric component update props failed

### ISSUE THREAD

**Issue by Milker90** [facebook/react-native#34412]
### Description

I implemented a fabric component of iOS datepicker, and it can be displayed normally now, but when I update the component properties in js, I don't see updateProps:oldProps: in C++ being called. I don't know what went wrong. Someone encountered this kind of problem?

### Version

0.69.2

### Output of `npx react-native info`

```js
System:
    OS: macOS 12.3.1
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 220.73 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v14.17.0/bin/npm
    Watchman: 2022.07.04.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/milker90/.rvm/gems/ruby-2.7.5/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 23, 25, 26, 28, 29, 30, 31
      Build Tools: 28.0.3, 29.0.0, 29.0.2, 29.0.3, 30.0.2, 30.0.3
      System Images: android-31 | Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7784292
    Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_291 - /Library/Java/JavaVirtualMachines/jdk1.8.0_291.jdk/Contents/Home/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0
    react-native: 0.69.2 => 0.69.2
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

react-native run-ios

### Snack, code example, screenshot, or link to a repository

this is fabric component code: [git repo](https://github.com/Milker90/BTDatePicker.git)

using component code, you can reproduce the problem by simply updating the mode from 'date' to 'datetime'
```js
<BTDatePicker
  style={{ height: 40, width: 180 }}
  date={date}
  mode={mode}
  onChange={onChange} 
/>
```

**Comment by Milker90** [comment]
I finally found the problem, where I needed the ViewManager to also declare these properties, and then the Fabric properties could be updated normally.

I don't understand why Fabric components still need to depend on ViewManager, ViewManager is an old implementation, shouldn't it be removed?

**Comment by cipolleschi** [comment]
Hi @Milker90, thanks for raising the issue.
As you correctly supposed `ViewManager` are something that Fabric Components will let you delete, eventually. 
To remove them completely, we need to rollout another piece of infrastructure that will come very soon.

**Comment by Milker90** [comment]
@cipolleschi cool, i'm looking forward to it

**Comment by kalyantm** [comment]
@cipolleschi Do we still have to declare these properties on the `ViewManager` as of React Native 0.70.2? I'm facing a similar issue when I'm trying to write a fabric native component as well!

**Comment by cipolleschi** [comment]
Yes. Unfortunately, we were not able to ship the piece of infra that allows us not to do it. 

But it is close to be released!

**Comment by cipolleschi** [comment]
Yes. Unfortunately, we were not able to ship the piece of infra that allows us not to do it. 

But it is close to be released!
