### ISSUE TITLE
Can't build from source

### ISSUE THREAD

**Issue by M1ck0** [facebook/react-native#34419]
### Description

I tried enabling new architecture and I can't build from source. Here is the error message

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDexRelease'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.DexMergingTaskDelegate
   > There was a failure while executing work items
      > A failure occurred while executing com.android.build.gradle.internal.tasks.DexMergingWorkAction
         > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
           Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
           Type com.facebook.react.viewmanagers.ActivityIndicatorViewManagerInterface is defined multiple times: /Users/micko/Desktop/projects/react-native/PomodoroTimer/android/app/build/intermediates/project_dex_archive/release/out/com/facebook/react/viewmanagers/ActivityIndicatorViewManagerInterface.dex, /Users/micko/Desktop/projects/react-native/PomodoroTimer/node_modules/react-native/ReactAndroid/build/.transforms/c32b107ab68b409a985007cb93ee8b39/transformed/classes/classes.dex
```

### Version

0.69.4

### Output of `npx react-native info`

```
System:
    OS: macOS 12.5
    CPU: (8) arm64 Apple M1
    Memory: 117.61 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: Not Found
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
    Watchman: 2022.07.04.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: Chipmunk 2021.2.1 Patch 2 Chipmunk 2021.2.1 Patch 2
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.4 => 0.69.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

I was just following the docs and couldn't build from source.

### Snack, code example, screenshot, or link to a repository

/

**Comment by cortinico** [comment]
> /

Sadly, I can't really help you without a reproducer.

Looking at your build failure:

> Type com.facebook.react.viewmanagers.ActivityIndicatorViewManagerInterface is defined multiple times: /Users/micko/Desktop/projects/react-native/PomodoroTimer/android/app/build/intermediates/project_dex_archive/release/out/com/facebook/react/viewmanagers/ActivityIndicatorViewManagerInterface.dex, /Users/micko/Desktop/projects/react-native/PomodoroTimer/node_modules/react-native/ReactAndroid/build/.transforms/c32b107ab68b409a985007cb93ee8b39/transformed/classes/classes.dex

It seems like what is happening is that you're running the codegen on the wrong folder. You're essentially re-generating the ViewManagers inside React Native and you end up with a duplicated class.

Can you share how you configured the codegen? I would suggest to place the spec file in a separate `src/` or `js/` folder and make sure the codegen is pointing against that folder.

**Comment by M1ck0** [comment]
This project actually consists of 2 JS files, nothing big. I just started it.

The project normally builds if I don't build it from the source. 

Do you need to see some specific file or something else?

**Comment by cortinico** [comment]
> Do you need to see some specific file or something else?

I would need to have a repo where I can checkout and build locally (or at least see how you configured the files). We might have a bigger bug that we'd like to address if this is the case.

**Comment by M1ck0** [comment]
Understood. I'll set it up today and send it here if that's okay. Unless I somehow fix it and post a solution.

**Comment by M1ck0** [comment]
I managed to fix something but now I have this

```Expected directory '/Users/micko/Desktop/projects/react-native/PomodoroTimer/node_modules/react-native/android' to contain exactly one file, however, it contains no files.```

Any ideas?

**Comment by M1ck0** [comment]
@cortinico any ideas?

**Comment by M1ck0** [comment]
It is all good now when using latest version.

**Comment by appdevwaleed** [comment]
> Understood. I'll set it up today and send it here if that's okay. Unless I somehow fix it and post a solution.

hello bro i am getting the same error if u got any solution kindly let me know

**Comment by M1ck0** [comment]
@appdevwaleed Just install the latest React Native version, and everything should work.
