### ISSUE TITLE
Execution failed for task ':react-native-gradle-plugin:compileKotlin'.

### ISSUE THREAD

**Issue by tsaurav18** [facebook/react-native#34410]
### New Version

0.69.0

### Old Version

0.64.2

### Build Target(s)

13

### Output of `react-native info`

(Use `node --trace-warnings ...` to show where the warning was created)
System:
    OS: macOS 12.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 174.05 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
    Watchman: 2022.07.04.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 23, 25, 27, 28, 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 33.0.0
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7322048
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /Library/Java/JavaVirtualMachines/jdk-11.0.15.jdk/Contents/Home/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.69.0 => 0.69.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Issue and Reproduction Steps

> Task :react-native-gradle-plugin:compileKotlin FAILED
e: /Users/wartan/Documents/internationthink/medic-react-native/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/TaskConfiguration.kt: (28, 33): Unresolved reference: replaceFirstChar
e: /Users/wartan/Documents/internationthink/medic-react-native/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/TaskConfiguration.kt: (28, 52): Unresolved reference: it
e: /Users/wartan/Documents/internationthink/medic-react-native/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/TaskConfiguration.kt: (252, 16): Unresolved reference: lowercase
e: /Users/wartan/Documents/internationthink/medic-react-native/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/utils/Os.kt: (13, 38): Unresolved reference: lowercase
e: /Users/wartan/Documents/internationthink/medic-react-native/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/utils/Os.kt: (15, 57): Unresolved reference: lowercase
e: /Users/wartan/Documents/internationthink/medic-react-native/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/utils/Os.kt: (18, 54): Unresolved reference: lowercase
e: /Users/wartan/Documents/internationthink/medic-react-native/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/utils/Os.kt: (19, 52): Unresolved reference: lowercase
e: /Users/wartan/Documents/internationthink/medic-react-native/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/utils/PathUtils.kt: (191, 27): Type mismatch: inferred type is Unit but CharSequence was expected
e: /Users/wartan/Documents/internationthink/medic-react-native/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/utils/PathUtils.kt: (191, 44): Unresolved reference: replaceFirstChar
e: /Users/wartan/Documents/internationthink/medic-react-native/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/utils/PathUtils.kt: (191, 63): Unresolved reference: it

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-gradle-plugin:compileKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 15s

**Comment by soundaryamecse** [comment]
No one replied this issue react native support. facing the same issues

**Comment by cortinico** [comment]
> Issue and Reproduction Steps

Please provide a reproducer. Your build log is not sufficient.
What is happening is that you're failing to compile some of the code inside the React Native Gradle Plugin. I can't tell the exact reason by just looking at your build log.

**Comment by mickeylam** [comment]
Same issue here. Trying to upgrade react-native version from `0.63.4` to `0.69.4`

**Comment by EJ132** [comment]
Receiving the same issue here upgrading react native from 0.67.3 to 0.69.3

**Comment by webdevchintan** [comment]
Hey @tsaurav18 @EJ132 @mickeylam @soundaryamecse  after version 0.68 RN introduce  New Architecture and for that they have upgrade the Gradle version to 7+ and you must have to upgrade your gradle  to 7+

so if you want to use the New Architecture then you must have to update the gradle 
for `0.69+` : that you have to add `distributionUrl=https\://services.gradle.org/distributions/gradle-7.3.3-all.zip` in `android/gradle/wrapper/gradle-wrapper.properties`

and in  `android/build.gradle` you have to add 
```

classpath("com.android.tools.build:gradle:7.1.1")
classpath("com.facebook.react:react-native-gradle-plugin")
classpath("de.undercouch:gradle-download-task:5.0.1")
```


for more information you can follow the [React Native Upgrade Helper](https://react-native-community.github.io/upgrade-helper)

hope this will work for you.

**Comment by amirkhanzada-iinv** [comment]
Facing the same issue on 0.70.1

**Comment by thangld322** [comment]
Same as @amirkhanzada-iinv

**Comment by SteveLai524** [comment]
Same Problem, waiting for resolve solution.

**Comment by willysxw** [comment]
same as @thangld322 @amirkhanzada-iinv 

info Starting JS server...
info Installing the app...
> Task :react-native-gradle-plugin:compileKotlin FAILED
1 actionable task: 1 executed

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-gradle-plugin:compileKotlin'.
> Failed to query the value of task ':react-native-gradle-plugin:compileKotlin' property 'compilerRunner$kotlin_gradle_plugin'.
   > Kotlin could not find the required JDK tools in the Java installation. Make sure Kotlin compilation is running on a JDK, not JRE.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-gradle-plugin:compileKotlin'.
> Failed to query the value of task ':react-native-gradle-plugin:compileKotlin' property 'compilerRunner$kotlin_gradle_plugin'.
   > Kotlin could not find the required JDK tools in the Java installation. Make sure Kotlin compilation is running on a JDK, not JRE.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s

    at makeError (C:\Users\will\prjwill\node_modules\execa\index.js:174:9)
    at C:\Users\will\prjwill\node_modules\execa\index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (C:\Users\will\prjwill\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:109:5)
    at async Command.handleAction (C:\Users\will\prjwill\node_modules\@react-native-community\cli\build\index.js:142:9)
info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

will@DESKTOP-151E8P0 MINGW64 ~/prjwill (master)
$ npx react-native upgrade
info No version passed. Fetching latest...
warn Specified version "0.70.4" is already installed in node_modules and it satisfies "0.70.4" semver range. No need to upgrade

will@DESKTOP-151E8P0 MINGW64 ~/prjwill (master)
$ yarn android
yarn run v1.22.19
warning ..\package.json: No license field
$ react-native run-android
info JS server already running.
info Installing the app...
> Task :react-native-gradle-plugin:compileKotlin FAILED
1 actionable task: 1 executed

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-gradle-plugin:compileKotlin'.
> Failed to query the value of task ':react-native-gradle-plugin:compileKotlin' property 'compilerRunner$kotlin_gradle_plugin'.
   > Kotlin could not find the required JDK tools in the Java installation. Make sure Kotlin compilation is running on a JDK, not JRE.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

**Comment by flyandi** [comment]
+1 on this issue. I tried downgrading to java 8 .. no go .. doesn't matter what Java env it's running on.

**Comment by SteveLai524** [comment]
I have tried it to compile a release package, and it has not reproduced.

**Comment by agrittiwari** [comment]
@cortinico  I followed the official support and way to update version, installed react-native-gradle-plugin and build compilation stucked at it, here's the log
```
info Starting JS server...
* daemon not running; starting now at tcp:5037
* daemon started successfully
info Launching emulator...
error Failed to launch emulator. Reason: Could not start emulator within 30 seconds..
warn Please launch an emulator manually or connect a device. Otherwise app may fail to launch.
info Installing the app...
Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details

> Task :react-native-gradle-plugin:compileKotlin

> Task :react-native-gradle-plugin:compileKotlin FAILED
1 actionable task: 1 executed
e: C:\Work\upgrade\truckjunctionnew\node_modules\react-native-gradle-plugin\src\main\kotlin\com\facebook\react\tasks\BundleHermesCTask.kt: (137, 11): This declaration is experimental and its usage must be marked with '@kotlin.ExperimentalStdlibApi' or '@OptIn(kotlin.ExperimentalStdlibApi::class)'

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-gradle-plugin:compileKotlin'.
> Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 46s
```

**Comment by cortinico** [comment]
> e: C:\Work\upgrade\truckjunctionnew\node_modules\react-native-gradle-plugin\src\main\kotlin\com\facebook\react\tasks\BundleHermesCTask.kt: (137, 11): This declaration is experimental and its usage must be marked with '@kotlin.ExperimentalStdlibApi' or '@OptIn(kotlin.ExperimentalStdlibApi::class)'

Which version of Kotlin are you using?
Which libraries are you using? I suspect some of them are pulling in Kotlin and resulting in a conflicting version

**Comment by RamboLouis** [comment]
> ### New Version
> 0.69.0
> 
> ### Old Version
> 0.64.2
> 
> ### Build Target(s)
> 13
> 
> ### Output of `react-native info`
> (Use `node --trace-warnings ...` to show where the warning was created) System: OS: macOS 12.1 CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz Memory: 174.05 MB / 16.00 GB Shell: 5.8 - /bin/zsh Binaries: Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node Yarn: 1.22.11 - /usr/local/bin/yarn npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm Watchman: 2022.07.04.00 - /usr/local/bin/watchman Managers: CocoaPods: 1.11.3 - /usr/local/bin/pod SDKs: iOS SDK: Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5 Android SDK: API Levels: 23, 25, 27, 28, 29, 30, 31 Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 33.0.0 System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom Android NDK: Not Found IDEs: Android Studio: 4.2 AI-202.7660.26.42.7322048 Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild Languages: Java: 11.0.15 - /Library/Java/JavaVirtualMachines/jdk-11.0.15.jdk/Contents/Home/bin/javac npmPackages: @react-native-community/cli: Not Found react: 18.2.0 => 18.2.0 react-native: 0.69.0 => 0.69.0 react-native-macos: Not Found npmGlobalPackages: _react-native_: Not Found
> 
> ### Issue and Reproduction Steps
> > Task :react-native-gradle-plugin:compileKotlin FAILED
> > e: /Users/wartan/Documents/internationthink/medic-react-native/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/TaskConfiguration.kt: (28, 33): Unresolved reference: replaceFirstChar
> > e: /Users/wartan/Documents/internationthink/medic-react-native/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/TaskConfiguration.kt: (28, 52): Unresolved reference: it
> > e: /Users/wartan/Documents/internationthink/medic-react-native/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/TaskConfiguration.kt: (252, 16): Unresolved reference: lowercase
> > e: /Users/wartan/Documents/internationthink/medic-react-native/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/utils/Os.kt: (13, 38): Unresolved reference: lowercase
> > e: /Users/wartan/Documents/internationthink/medic-react-native/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/utils/Os.kt: (15, 57): Unresolved reference: lowercase
> > e: /Users/wartan/Documents/internationthink/medic-react-native/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/utils/Os.kt: (18, 54): Unresolved reference: lowercase
> > e: /Users/wartan/Documents/internationthink/medic-react-native/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/utils/Os.kt: (19, 52): Unresolved reference: lowercase
> > e: /Users/wartan/Documents/internationthink/medic-react-native/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/utils/PathUtils.kt: (191, 27): Type mismatch: inferred type is Unit but CharSequence was expected
> > e: /Users/wartan/Documents/internationthink/medic-react-native/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/utils/PathUtils.kt: (191, 44): Unresolved reference: replaceFirstChar
> > e: /Users/wartan/Documents/internationthink/medic-react-native/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/utils/PathUtils.kt: (191, 63): Unresolved reference: it
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
>   Execution failed for task ':react-native-gradle-plugin:compileKotlin'.
> 
> > Compilation error. See log for more details
> 
> * Try:
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 15s

Try:
```
rm -rf ./node_modules
yarn
npm run android
```

**Comment by mshehrozsajjad-curevision** [comment]
Following this. I am facing the same issue.

**Comment by andre-luiz1997** [comment]
> Following this. I am facing the same issue.

I am also facing this issue with the react-native 0.68.2

**Comment by kwyg** [comment]
> > Following this. I am facing the same issue.
> 
> I am also facing this issue with the react-native 0.68.2

Same issue here. In package.json I prefixed the version with **`^`**, then `yarn install` and it started working.

`"react-native": "^0.68.2"`

**Comment by BilalKucuk491** [comment]
> > > Bunu ister. Aynı sorunla karşı karşıyayım.
> > 
> > 
> > Ayrıca bu sorunla tepki-yerel 0.68.2 ile karşı karşıyayım.
> 
> Burada da aynı sorun. package.json'da uygulamada , başladıktan sonra katıldım ve yayınlandı.**`^`**`yarn install`
> 
> `"react-native": "^0.68.2"`

Thank you so much

**Comment by Jayashreekm** [comment]
> > > Following this. I am facing the same issue.
> > 
> > 
> > I am also facing this issue with the react-native 0.68.2
> 
> Same issue here. In package.json I prefixed the version with **`^`**, then `yarn install` and it started working.
> 
> `"react-native": "^0.68.2"`

I am also facing same issue. Not resolved with above solution. can you tell me what is the gradle version in gradle-wrapper.properties file in your case.

**Comment by kwyg** [comment]
> > > > Following this. I am facing the same issue.
> > > 
> > > 
> > > I am also facing this issue with the react-native 0.68.2
> > 
> > 
> > Same issue here. In package.json I prefixed the version with **`^`**, then `yarn install` and it started working.
> > `"react-native": "^0.68.2"`
> 
> I am also facing same issue. Not resolved with above solution. can you tell me what is the gradle version in gradle-wrapper.properties file in your case.

My Gradle version is 7.3.3.

**Comment by andre-luiz1997** [comment]
I was able to make it work by doing the following: 

- in _package.json_:

replace 
`"react-native": "0.68.2" `
with      
`"react-native": "^0.68.2"`

- in _android/build.gradle_:

within
```
buildscript {
         ...
         ext {
                ...
                compileSdkVersion: '33'
                targetSdkVersion: '33'
                kotlinVersion: '1.6.20'
                ...
         }
         ...
         dependencies {
                  ...
                classpath('com.android.tools.build:gradle:7.3.0')
                classpath('com.facebook.react:react-native-gradle-plugin')
                classpath('de.undercouch:gradle-download-task:5.0.1')
                classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.20")
         }
}
```


I am not very familiar with gradle, but that was the config that worked for me for now.

**Comment by amirbhz86** [comment]
I have the same issue

**Comment by erenerogullari** [comment]
I'm having the same issue, the solutions above don't work for me..

**Comment by hamdidamar** [comment]
same here

**Comment by alanBriceno** [comment]
> @cortinico I followed the official support and way to update version, installed react-native-gradle-plugin and build compilation stucked at it, here's the log
> 
> ```
> info Starting JS server...
> * daemon not running; starting now at tcp:5037
> * daemon started successfully
> info Launching emulator...
> error Failed to launch emulator. Reason: Could not start emulator within 30 seconds..
> warn Please launch an emulator manually or connect a device. Otherwise app may fail to launch.
> info Installing the app...
> Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details
> 
> > Task :react-native-gradle-plugin:compileKotlin
> 
> > Task :react-native-gradle-plugin:compileKotlin FAILED
> 1 actionable task: 1 executed
> e: C:\Work\upgrade\truckjunctionnew\node_modules\react-native-gradle-plugin\src\main\kotlin\com\facebook\react\tasks\BundleHermesCTask.kt: (137, 11): This declaration is experimental and its usage must be marked with '@kotlin.ExperimentalStdlibApi' or '@OptIn(kotlin.ExperimentalStdlibApi::class)'
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':react-native-gradle-plugin:compileKotlin'.
> > Compilation error. See log for more details
> 
> * Try:
> > Run with --stacktrace option to get the stack trace.
> > Run with --info or --debug option to get more log output.
> > Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 1m 46s
> ```

same isue, any update?

**Comment by paulopgss** [comment]
As it worked for me, in `<PROJECT>/android/gradle/gradle/wrapper/gradle-wrapper.properties` i changed the line `distributionUrl=https\://services.gradle.org/distributions/gradle-7.5.1-all.zip` by `distributionUrl=https\://services.gradle.org/distributions/gradle-7.4-all.zip`.

in android/build.gradle:

```
buildscript {
         ...
         ext {
                ...
                compileSdkVersion = 33
                targetSdkVersion = 33
                kotlinVersion = '1.6.20'
                ...
         }
         ...
         dependencies {
                  ...
                classpath('com.android.tools.build:gradle:7.3.0')
                classpath('com.facebook.react:react-native-gradle-plugin')
                classpath('de.undercouch:gradle-download-task:5.0.1')
                classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.20")
         }
}
```

in the end in android/app/src/main/AndroidManifest.xml:

added the package

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="<com.<YOUR_PROJECT>" 
>
```

completed, opened Android Studio and synchronized the gradle...

hope to help

**Comment by ste7en** [comment]
Same issue. Can't set the `-opt-in` compiler flag.
My kotlin version is `1.6.10`

**Comment by alyssonee1010** [comment]
> Hey @tsaurav18 @EJ132 @mickeylam @soundaryamecse after version 0.68 RN introduce New Architecture and for that they have upgrade the Gradle version to 7+ and you must have to upgrade your gradle to 7+
> 
> so if you want to use the New Architecture then you must have to update the gradle for `0.69+` : that you have to add `distributionUrl=https\://services.gradle.org/distributions/gradle-7.3.3-all.zip` in `android/gradle/wrapper/gradle-wrapper.properties`
> 
> and in `android/build.gradle` you have to add
> 
> ```
> 
> classpath("com.android.tools.build:gradle:7.1.1")
> classpath("com.facebook.react:react-native-gradle-plugin")
> classpath("de.undercouch:gradle-download-task:5.0.1")
> ```
> 
> for more information you can follow the [React Native Upgrade Helper](https://react-native-community.github.io/upgrade-helper)
> 
> hope this will work for you.

it worked for me, thanks

**Comment by eunbok-bocoder** [comment]
I changed gradle version and solved it.
(*reference : https://bocoder.tistory.com/125)

//before
distributionUrl=https\://services.gradle.org/distributions/gradle-6.9-bin.zip

//after
distributionUrl=https\://services.gradle.org/distributions/gradle-7.5.1-all.zip

**Comment by nithin-304** [comment]
Same issue and when I typed react-native info this is what it showed but the thing is I have Sdk"s installed but it does not appear over here. Plz help me out


![Screenshot (91)](https://user-images.githubusercontent.com/65385383/206118381-36b8eece-b2a4-4c84-8dcb-c01e03511434.png)

**Comment by zahmadz** [comment]
i don't think my solution is work for you guys, but this is the solution for my case.

My case is I'm installing Minecraft game, and the installer automatically installs java 8.

So I just uninstall that java 8 and now the issue is fixed

**Comment by sparkdelta** [comment]
This might be an issue due to wrong version or absence of JDK (not JRE). 
Install JDK11 worked for me.
Run:
brew install java11

sudo ln -sfn /usr/local/opt/openjdk@11/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk-11.jdk

java --version

Thanks !!

**Comment by ashotosipyan** [comment]
I had a similar problem and after installing https://www.npmjs.com/package/react-native-gradle-plugin this package everything worked fine, maybe would be helpful for somebody.

**Comment by SherbekMavlonov** [comment]
1. open project on terminal
2. run this yarn add react-native-gradle-plugin
3. yarn android
it worked for me, thanks

**Comment by ramirobg94** [comment]
There are many things related to this.

1 - Open Android Studio and download the latest SDKS -> https://reactnative.dev/docs/environment-setup
2 -  In wrapper/gradle-wrapper.properties
`distributionUrl=https\://services.gradle.org/distributions/gradle-7.5.1-all.zip`

**Comment by rarenatoe** [comment]
> There are many things related to this.
> 
> 1 - Open Android Studio and download the latest SDKS -> https://reactnative.dev/docs/environment-setup 2 - In wrapper/gradle-wrapper.properties `distributionUrl=https\://services.gradle.org/distributions/gradle-7.5.1-all.zip`
> 
> This solved my problem ( Also downgrade some packages)

To my knowledge gradle 7.5 is only supported by react-native 0.70
is there a way to fix this in 0.68?

**Comment by ramirobg94** [comment]
> > There are many things related to this.
> > 1 - Open Android Studio and download the latest SDKS -> https://reactnative.dev/docs/environment-setup 2 - In wrapper/gradle-wrapper.properties `distributionUrl=https\://services.gradle.org/distributions/gradle-7.5.1-all.zip`
> > This solved my problem ( Also downgrade some packages)
> 
> To my knowledge gradle 7.5 is only supported by react-native 0.70 is there a way to fix this in 0.68?

@rarenatoe 
try with this:
`distributionUrl=https\://services.gradle.org/distributions/gradle-7.3.3-all.zip`

**Comment by SouzaVitoria** [comment]
Thank you, guys!

My problem `_[Task :react-native-gradle-plugin:compileKotlin FAILED, 'compileJava' task (current target is 1.8) and 'compileKotlin' task (current target is 11)](https://stackoverflow.com/questions/73768537/task-react-native-gradle-plugincompilekotlin-failed-compilejava-task-curre)..._`

was solved with two answers that were given here:

 1. Installed java 11 and uninstalled that java 8;
 2.  In `package.json` I prefixed the version with `^`, then `yarn install`. Update "react native" version `0.68.2` for `^0.68.2`


_I added the solve of this problem on stackoverflow too: https://stackoverflow.com/a/75907466/15748229_

**Comment by kdpadhiyar** [comment]
I am also facing same issue
I tried to upgrade react native project from 0.63.2  to 0.71.7

faced same issues like @tsaurav18 & [agrittiwari](https://github.com/agrittiwari)
Please help us to fix that issue.
To upgrade any project from that old to new is quite complex.
@cortinico

**Comment by michaelachrisco** [comment]
im getting the same error upgrading from 69 -> 71: 

```
| > Task :react-native-gradle-plugin:compileKotlin FAILED
| e: proj/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/tasks/BundleHermesCTask.kt: (138, 11): This declaration is experimental and its usage must be marked with '@kotlin.ExperimentalStdlibApi' or '@OptIn(kotlin.ExperimentalStdlibApi::class)'
```

I tried switching from gradle 7.5.1 back down to 7.3.3 but had the same error.

**Comment by eugipalazzi** [comment]
It works to me on RN 0.71 by upgrade Gradle to 7.5.1 on gradle-wrapper.properties
`distributionUrl=https\://services.gradle.org/distributions/gradle-7.5.1-all.zip`

and tehn added this two lines of code on build.gradle
`classpath('de.undercouch:gradle-download-task:5.0.1')
classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.20")`

**Comment by plonsik** [comment]
I've faced same issue, but after launching:
react-native run-andoid - wait till end
react-native start 
It started working normally

**Comment by ravindraguptacapgemini** [comment]
@cortinico I am getting the similar error with new release of React Native 0.72.1. 
distributionUrl=https\://services.gradle.org/distributions/gradle-8.0.1-all.zip

**Comment by ravindraguptacapgemini** [comment]
@cortinico I am getting the similar error with new release of React Native 0.72.1. 
distributionUrl=https\://services.gradle.org/distributions/gradle-8.0.1-all.zip

**Comment by AtypicalSysAdmin** [comment]
if you upgraded your expo like me from 46 to 48 and faced this, Rename` ./android` build folder in project dir to `./android.old` and run `expo prebuild`. 

It will add the correct gradle zip which in my case was` gradle-7.5.1-all.zip` as listed by poeple above. Finally, run `cd ./android && ./gradle clean`

react native version 0.71.8 in package json as time of the comment

**Comment by IgnacioRodriguez01** [comment]
In my case, I assured 3 things for it to work:

In `gradle/wrapper/gradle-wrapper.properties`:
`distributionUrl=https\://services.gradle.org/distributions/gradle-7.5.1-all.zip`

I checked for the last updates of the SDK Platform and tools on Android Studio, in the section `Preferences > Appearance & Behavior > System Settings > Android SDK`

And finally I uninstalled and reinstalled completely my Java JRE and JDK. Then I installed the last version of Java for my system (1.8.0_381-b09) and the JDK 11, recommended by React Native. After both procedures I restarted my computer, and after the last restart, I set my JAVA_HOME env variable to the place where JDK folder was placed.

Hope it helps.

P.D.: I am running react-native 0.71.8, and its worth to mention that my `android/build.gradle` file looks like this because of my implementation of VisionCamera to work:
```
buildscript {
    ext {
        buildToolsVersion = "33.0.0"
        kotlinVersion = "1.7.0"
        minSdkVersion = 21
        compileSdkVersion = 33
        targetSdkVersion = 33

  ...
```

**Comment by winnerdev2012** [comment]
I solve this problem!!!

If you are using React Native 0.60 or above, you can use the latest version of react-native-gradle-plugin, which is 2.0.0 at the time of writing. You can update your dependencies block to include:
groovy
Copy code

dependencies {
    // ...
    classpath("com.facebook.react:react-native-gradle-plugin:2.0.0")
    // ...
}
If you are using an older version of React Native, you can check the compatibility table provided by the react-native-gradle-plugin repository to find the suitable version for your React Native version. Here is the link to the compatibility table: [react-native-gradle-plugin Compatibility Table](https://github.com/facebook/react-native-gradle-plugin#compatibility).

**Comment by exseniarch** [comment]
> 1. open project on terminal
> 2. run this yarn add react-native-gradle-plugin
> 3. yarn android
>    it worked for me, thanks

Worked for me too! tnx!
