### ISSUE TITLE
Change in how layout is calculated on 0.12.0

### ISSUE THREAD

**Issue by hswolff** [facebook/react-native#3441]
When upgrading to `0.12.0` I noticed a change in how my content was laid out when nested in a `TabBarIOS` component.

Attached is an example code showing the behavior, but pretty much if I change the root element in my custom component at a later time then the height of the UITabBar is no longer taken into account. However if it's rendered synchronously then it is laid out correctly.

I'm also seeing this behavior with `Navigator`. Whenever I push anything onto the stack, and render its content - synch or async - it no longer takes into account the height of the NavBar or the UITabBar when rendering the new route component.

```javascript
import React from 'react-native';
const {
  AppRegistry,
  Component,
  TabBarIOS,
  View, ScrollView, Text
} = React;

class NestedView extends Component {
  constructor() {
    super();

    this.state = {
      isLoading: true
    };

    setTimeout(() => {
      this.setState({
        isLoading: false
      })
    }, 2000);
  }

  render() {
    if (this.state.isLoading) {
      return (
        <View style={{flex: 1, alignItems: 'center', justifyContent: 'center'}}>
          <Text>Loading</Text>
        </View>
      )
    } else {
      return (
        <ScrollView style={{flex: 1}}>
          {[1,2,3,4,5].map(index => {
            return (
              <View style={{height: 200, alignItems: 'center', justifyContent: 'center', borderColor: 'red', borderWidth: 1}}>
                <Text>{index}</Text>
              </View>
            )
          })}
        </ScrollView>
      )
    }
  }
}

class Example extends Component {
  render() {
    return (
      <TabBarIOS
        barTintColor="#ffffff"
        tintColor="blue">
        <TabBarIOS.Item
          selected={true}
          title="Test">
          <NestedView/>
        </TabBarIOS.Item>
      </TabBarIOS>
    );
  }
}


AppRegistry.registerComponent('Example', () => Example);
```

**Comment by admmasters** [comment]
Is this related to a commit around insets? I had this issue with TabBarIOS and Navigator. I'll dig out the commit that broke the layout for me.

**Comment by admmasters** [comment]
This was the commit that broke some of my layouts: bbeaac5d3bf48ba713c92ca9073a23ec9b05c87a

**Comment by IlyasM** [comment]
Having the same issue, @hswolff did you find a workaround?

**Comment by hswolff** [comment]
The workaround I found was that I changed my components so that the root node isn't changed. I had some pages where I first rendered a `Loading` view and then switched it to the actual content once the data loaded and that caused the layout to be calculated incorrectly. By only switching the children contents that helped make the rendering a little more reliable.

I also used this style for my container:

```
paddingTop: Navigator.NavigationBar.Styles.General.NavBarHeight,
```

To help offset the height. 

This workaround requires some massaging but at leasts gets things closer.

**Comment by ide** [comment]
You could also try `automaticallyAdjustContentInsets={false}`.

**Comment by IlyasM** [comment]
@ide, @hswolff  these workarounds do not work for me as I have NavigatorIOS nested inside TabBarIOS.Item - for me initial layout inconsistency is fixed once you push back to the scene but I can't find a workaround for the initial layout problem(all my views are slightly offset behind navBar on initial layout)

here is the illustration
![oct 19 2015 13 45](https://cloud.githubusercontent.com/assets/9557307/10572351/7612c220-7669-11e5-867b-0e52cbaa40c5.gif)

**Comment by umhan35** [comment]
Any update on this? `automaticallyAdjustContentInsets` is not consistent for my app too.

**Comment by maxdjohnson** [comment]
I'm also having this issue. Really tough to track down, I don't have a reliable repro since it seems to happen randomly.

**Comment by umhan35** [comment]
It seems happening when its content is dynamic, eg, loaded from local database

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/change-in-how-layout-is-calculated-on-0120

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
