### ISSUE TITLE
IOS Simulator stops working after few api calls while using debugging on react-native debugger  or chrome

### ISSUE THREAD

**Issue by tomerbraun** [facebook/react-native#34411]
### New Version

0.69.1

### Old Version

0.63.3

### Build Target(s)

IOS simulator in debugging

### Output of `react-native info`

warn Package react-native-vector-icons contains invalid configuration: "dependency.assets" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
info Found Xcode workspace "DoseApp.xcworkspace"
info Building (using "xcodebuild -workspace DoseApp.xcworkspace -configuration Debug -scheme DoseApp -destination id=B6F978D9-FCB2-4BB8-BCC9-863347F8A7F5")
success Successfully built the app
2022-08-14 12:07:05.611 xcodebuild[62336:3526739] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
2022-08-14 12:07:05.611 xcodebuild[62336:3526739] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
--- xcodebuild: WARNING: Using the first of multiple matching destinations:

### Issue and Reproduction Steps

After upgrading to react-native 0.69.1 we succeed in running and building new versions, but when trying to run IOS 
simulators on debugging the app stop working.
Can't find any logs connected to the debug issue.
When switching back to work without debugging the app works fine.

![image](https://user-images.githubusercontent.com/93592037/184530586-f09d7694-30e1-483d-bb7e-0e84406f7d4b.png)

![image](https://user-images.githubusercontent.com/93592037/184530634-609f2d88-16d5-4e44-8901-94ccc0134996.png)

The server is responding to the API calls but still, the app shows it is in pending mode.
We are using axios to send the API calls to the server

**Comment by elowareAdm** [comment]
up

**Comment by cristiano-futturis** [comment]
The same issue here.

**Comment by suyashvash** [comment]
Can you post the API call code? must be an issue while handling the response or error.
