### ISSUE TITLE
When I had a jsbundle 

### ISSUE THREAD

**Issue by jokunhe** [facebook/react-native#34426]
### Description

When I have a jsbundle, I perform release compilation on Xcode, but it will still be overwritten by the jsbundle generated by the bundle react native code and images. However, if I empty the contents of the bundle react native code and images, it is correct

### Version

any

### Output of `npx react-native info`

System:
    OS: macOS 12.5
    CPU: (8) arm64 Apple M1 Pro
    Memory: 95.64 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.7.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.15.0 - /opt/homebrew/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.68.2 => 0.68.2
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

When I have a jsbundle, I perform release compilation on Xcode, but it will still be overwritten by the jsbundle generated by the bundle react native code and images. However, if I empty the contents of the bundle react native code and images, it is correct

### Snack, code example, screenshot, or link to a repository

react native inti any

**Comment by cortinico** [comment]
> ### Snack, code example, screenshot, or link to a repository
> react native inti any

Please fill in the issue template + provide a reproducer as the current informations are not sufficient to triage this issue.

I'm closing for the time being, feel free to re-open once you can provide the details.
