### ISSUE TITLE
minHeight adds minHeight for each wrapped row

### ISSUE THREAD

**Issue by wolverineks** [facebook/react-native#34429]
### Description

os: android, ios

when `<View style={{ flexWrap: "wrap", flexDirection: row }} />` contains wrapping content, 
additional padding is added to bottom

larger text seems unaffected
smaller minHeight seems unaffected
expo web seems unaffected

### Version

0.64.2 (device), 0.69.4 (expo)

### Output of `npx react-native info`

System:
    OS: macOS 12.4
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 19.93 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.5.0 - ~/.nvm/versions/node/v16.5.0/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 7.19.1 - ~/.nvm/versions/node/v16.5.0/bin/npm
    Watchman: 2022.03.21.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/lib/ruby/gems/2.6.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 24, 26, 28, 29, 30, 31
      Build Tools: 23.0.3, 26.0.2, 26.0.3, 28.0.3, 29.0.0, 29.0.1, 29.0.2, 30.0.2, 31.0.0, 31.0.0, 31.0.0
      System Images: android-22 | Intel x86 Atom_64, android-22 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-32 | Google APIs ARM 64 v8a, android-33 | Google APIs ARM 64 v8a
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 13.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.64.2 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. create `<View style={{ flexWrap: "wrap", flexDirection: row }} />`
2. add content until content wraps

### Snack, code example, screenshot, or link to a repository

https://snack.expo.dev/@wolverineks/shallow-carrot

**Comment by kito-arch** [comment]
Add these styles to the parent, which has `minHeight` : 
`justifyContent : 'start',
alignItems : 'flex-start'`
