### ISSUE TITLE
Apple Silicon (M1) Error to create React Native app

### ISSUE THREAD

**Issue by Baxi19** [facebook/react-native#34449]
### Description

# Hello everyone 👋 

#### 1 - Create an empty project
```
npx react-native init AwesomeProjectExample
```

#### 2 - Move to the project folder
```
cd AwesomeProjectExample
```

#### 3 - Open the project using VS Code
```
code .
```

#### 4 - Install dependencies
```
npm install --save --legacy-peer-deps
```

#### 5 - Go to ios folder
```
cd ios
```

#### 6 -  Install Cocoapods
```
sudo arch -x86_64 gem install ffi
```

```
arch -x86_64 pod install
```

#### 7 - Go to root folder
```
cd ..
```

#### 8 - Run ios app
```
npx react-native run-ios
```

## But I am getting the following error:
<img width="1327" alt="Screen Shot 2022-08-18 at 17 20 43" src="https://user-images.githubusercontent.com/31778373/185511819-670f65e4-1f74-43df-9cf6-99e4d806172a.png">

#### I finally decide to move to another version of React Native(0.66.4) to solve the problem.

# Temporal Solution (React Native 0.66.4)
##### 1 - Create the project 📱 
```
npx react-native init AwesomeProjectExample --version 0.66.4
```

##### 2 - Go to project root 💻 
```
cd AwesomeProjectExample
```

##### 3 - Install the dependencies 👍 
```
npm install --save --legacy-peer-deps
```

##### 4 - Pod install 🗡️ 
```
cd ios && pod install && cd ..
```

##### 5 - Run the project 🔥 
```
npx react-native run-ios
```

### Version

0.69.4

### Output of `npx react-native info`

```
System:
    OS: macOS 12.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 769.19 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.6.0 - /opt/homebrew/bin/node
    Yarn: Not Found
    npm: 8.10.0 - ~/node_modules/.bin/npm
    Watchman: 2022.07.04.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7935034
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.4 => 0.69.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

#### 1 - Create an empty project
```
npx react-native init AwesomeProjectExample
```

#### 2 - Move to the project folder
```
cd AwesomeProjectExample
```

#### 3 - Open the project using VS Code
```
code .
```

#### 4 - Install dependencies
```
npm install --save --legacy-peer-deps
```

#### 5 - Go to ios folder
```
cd ios
```

#### 6 -  Install Cocoapods
```
sudo arch -x86_64 gem install ffi
```

```
arch -x86_64 pod install
```

#### 7 - Go to root folder
```
cd ..
```

#### 8 - Run ios app
```
npx react-native run-ios
```

### Snack, code example, screenshot, or link to a repository

Repository: `https://github.com/Baxi19/AwesomeProjectExample`

**Comment by Baxi19** [comment]
Somebody has a different solution to use latest version of React Native?

**Comment by kamolesh97** [comment]
Can you try building the app once from xcode itself, sometimes xcode gives more info regarding such errors.
