### ISSUE TITLE
setNativeProps is not currently supported in Fabric

### ISSUE THREAD

**Issue by mcalvinobrandcoders** [facebook/react-native#34457]
### Description

I have a bare react native repo with react 18 and all the new features enabled except for turbo modules. When adding react navigation to the repo I got a warning regarding react-navigation using a method that is not supported by the new Fabric render. My question is, will it be support in the future ?

![simulator_screenshot_44484F76-7AA8-4AEF-97F2-483D707FEC77](https://user-images.githubusercontent.com/84166590/185632906-7104015b-cfbc-46aa-a709-acaf58571bec.png)

### Version

0.69.4

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 11.6
    CPU: (4) x64 Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz
    Memory: 22.42 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.1.0 - ~/.nvm/versions/node/v17.1.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.1.3 - ~/.nvm/versions/node/v17.1.0/bin/npm
    Watchman: 2022.07.04.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8815526
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /Users/manuelcalvino/.sdkman/candidates/java/current/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.69.4 => 0.69.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Have a react native repo (0.69.4) w react and react-dom @18.2.0 with Fabric enabled, and install the @react-navigation package.

### Snack, code example, screenshot, or link to a repository

![simulator_screenshot_59BDB214-E8EF-4573-B407-607916DCD0CA](https://user-images.githubusercontent.com/84166590/185633569-e718fe49-1272-430a-a0e7-751ca7e63fdb.png)

**Comment by frankcalise** [comment]
As per the docs, it will not be supported in Fabric: https://reactnative.dev/docs/new-architecture-library-intro#migrating-off-setnativeprops

**Comment by mcalvinobrandcoders** [comment]
Thanks for the help!

**Comment by RichardLindhout** [comment]
It is now removed from docs?
