### ISSUE TITLE
Unable to set the application name to Chinese

### ISSUE THREAD

**Issue by Tzng** [facebook/react-native#34450]
### Description

当我修改app_name为中文的时候，应用程序会闪退

```
<resources>
    <string name="app_name">aaaa</string>
</resources>
```
[after modification](javascript:;)
```
<resources>
    <string name="app_name">测试</string>
</resources>
```

### Version

0.69.4

### Output of `npx react-native info`

Done in 8.39s.
    Java: 11.0.12
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0
    react-native: 0.69.4 => 0.69.4
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Change the name of the application to “你好”，

`npm run android`

When the app is opened, it will flash back

### Snack, code example, screenshot, or link to a repository

![image](https://user-images.githubusercontent.com/26215888/185549712-140cad67-a425-4d9b-b993-286a1935e580.png)

**Comment by lionet1224** [comment]
It will be like this in the emulator, I tried to package the release version to view on the phone, there is no flashback.
You can get a multi-language configuration, copy the `values` folder under `android/app/src/main/res` and rename it to `values-zh`, change the name to Chinese in `values-zh/string.xml`, and keep the English name in `values/string.xml`.
There may be a better solution, but this is all I can think of at the moment.

**Comment by kaindy7633** [comment]
I also encountered this problem. According to @lionet1224 practice, it didn't work. Should I test it in a Chinese environment, but the simulator can't seem to be set to Chinese

**Comment by Tzng** [comment]
> I also encountered this problem. According to @lionet1224 practice, it didn't work. Should I test it in a Chinese environment, but the simulator can't seem to be set to Chinese

You can modify it in the settings
