### ISSUE TITLE
[iOS] Modals Above Status Bar

### ISSUE THREAD

**Issue by MossP** [facebook/react-native#3446]
If you trigger a modal window it is not possible to have it show above the status bar. Unlike https://github.com/brentvatne/react-native-overlay which can do this.

**Comment by javache** [comment]
This not supported by UIKit's view controller presentation system: the status bar is presented in a window above the application window, all view controllers are presented inside one application window.

React-native-overlay will create separate windows to host parts of the react native view tree. We have an implementation of this internally as well, which we are trying to move away from, as UIWindows have notoriously bad support for rotation and don't support a number of other scenarios.

**Comment by ide** [comment]
Sounds like this may be filed under "intend not to fix".

**Comment by MossP** [comment]
No problem, that's a valid reason. Thanks for the feedback.
