### ISSUE TITLE
Yogakit and uint8_t errors after init and run new project (iOS)

### ISSUE THREAD

**Issue by osvald0** [facebook/react-native#34468]
### Description

After init a new project I got two errors:

```
Typedef redefinition with different types ('uint8_t' (aka 'unsigned char') vs 'enum clockid_t')
```

and 

```
CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'YogaKit' from project 'Pods')
```

### Version

0.69.4

### Output of `npx react-native info`

System:
    OS: macOS 12.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 132.14 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: Not Found
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
    Watchman: 2022.01.31.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 27, 28, 29, 30, 31, 32
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 32.0.0, 32.1.0
      System Images: android-31 | Google APIs ARM 64 v8a, android-31 | Google Play ARM 64 v8a, android-32 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0
    react-native: 0.69.4 => 0.69.4
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1- Init new project.
2- Run the project (iOS)

### Snack, code example, screenshot, or link to a repository

![Screen Shot 2022-08-22 at 09 23 34](https://user-images.githubusercontent.com/20977158/185922051-4d24632a-8687-4181-baa1-9702025ba807.png)
![Screen Shot 2022-08-22 at 09 22 49](https://user-images.githubusercontent.com/20977158/185922060-2b59cf5b-dc4a-490f-bfdb-69b77ea77e13.png)

**Comment by talaikis** [comment]
+1 with 0.69-0.70rc4

**Comment by MizukiHo** [comment]
+1 with 0.70.3
