### ISSUE TITLE
building for iOS Simulator-x86_64 but attempting to link with file built for iOS Simulator-arm64

### ISSUE THREAD

**Issue by Ahmetaksungur** [facebook/react-native#34461]
### Description

<img width="884" alt="Ekran Resmi 2022-08-20 13 39 45" src="https://user-images.githubusercontent.com/55207238/185742367-51233f5b-fbcc-4d30-8076-7b013988b190.png">

### Version

0.69.4

### Output of `npx react-native info`

System:
    OS: macOS 12.0.1
    CPU: (8) arm64 Apple M1
    Memory: 114.64 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.0.0 - /opt/homebrew/bin/node
    Yarn: Not Found
    npm: 8.6.0 - /opt/homebrew/bin/npm
    Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.4 => 0.69.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

<img width="743" alt="Ekran Resmi 2022-08-20 13 44 03" src="https://user-images.githubusercontent.com/55207238/185742424-6a615be4-43cd-41ff-b2c8-d425975d3d3b.png">

### Snack, code example, screenshot, or link to a repository

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end

**Comment by kabus202** [comment]
@Ahmetaksungur did you find any solution? facing the same issue

**Comment by Ahmetaksungur** [comment]
I can't find more
