### ISSUE TITLE
React native run-ios failed 

### ISSUE THREAD

**Issue by dazcalifornia** [facebook/react-native#34466]
### Description

I tried to create a new project in macOS  when I run-ios I got 1faliled

### Version

0.69.4

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Memory: 1.08 GB / 12.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 16.13.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 8.1.0 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8309675
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0
    react-native: 0.69.4 => 0.69.4
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1.init a project with react-native init Sandbox
2.run cd Sandbox and run npx react-native run-ios
I got the same error written in the Result

### Snack, code example, screenshot, or link to a repository

![Screen Shot 2565-08-22 at 06 51 51](https://user-images.githubusercontent.com/12984807/185816338-81751089-cc67-4b6a-af20-bf149d50a913.png)

**Comment by suyashvash** [comment]
Try changing iOS target to ios 12 in from Xcode.

**Comment by dazcalifornia** [comment]
> Try changing iOS target to ios 12 in from Xcode.

Not working btw I'm used expo instead
