### ISSUE TITLE
fabric(new arch): The app bundle includes both `Fabric` & `Paper` React Native renderers

### ISSUE THREAD

**Issue by ecreeth** [facebook/react-native#34464]
### Description

These always use the `paper` renderer: 
- `ScrollVIew`: https://github.com/facebook/react-native/blob/main/Libraries/Components/ScrollView/ScrollView.js#L15
- `findNodeHandle`: https://github.com/facebook/react-native/blob/main/index.js#L284
- and many more. Search `/Renderer/shims/ReactNative'`

### Version

0.70.0-rc.3

### Output of `npx react-native info`

System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (4) x64 Intel(R) Core(TM) i5-2400S CPU @ 2.50GHz
    Memory: 2.41 GB / 13.64 GB
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: Not Found
    Yarn: Not Found
    npm: Not Found
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 11.0.16
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.0-rc.3 => 0.70.0-rc.3 
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. Bundle the app
2. See both renderes shipped

### Snack, code example, screenshot, or link to a repository

![image](https://user-images.githubusercontent.com/20761166/185807225-66557a98-c072-4a9f-9033-1235de78c8ba.png)

**Comment by ecreeth** [comment]
@cipolleschi This should lead to unexpected behavior

**Comment by ecreeth** [comment]
This is now fixed by:
- https://github.com/facebook/react-native/commit/b06cae36819084061a159f5ddcee9bcd8ac02a8b
- https://github.com/facebook/react-native/commit/b06cae36819084061a159f5ddcee9bcd8ac02a8b

**Comment by ecreeth** [comment]
I can confirm that this happen even in 0.73.0-RC.1
![image](https://github.com/facebook/react-native/assets/20761166/8cefb24f-d668-43c8-9d9b-2a99559dda45)

**Comment by kesha-antonov** [comment]
> I can confirm that this happen even in 0.73.0-RC.1 ![image](https://user-images.githubusercontent.com/20761166/272655348-8cefb24f-d668-43c8-9d9b-2a99559dda45.png)

Same problem

Can't get rid of React-Fabric. It's always in Podfile.lock and flags are on

**Comment by cipolleschi** [comment]
The fact that React-Fabric is in the Podfile.lock is not bound to the renderer, which is a `.js` file.
The Podspecs only controls the iOS native side of things, no JS involved, and we need the React-Fabric pod in both the architectures for the RuntimeScheduler.

**Comment by javache** [comment]
This is a known issue, and will not be resolved until the new architecture is fully rolled out and paper removed.

You could consider patching `RendererImplementation` locally to remove references to `../Renderer/shims/ReactNative` if this is blocking you.
