### ISSUE TITLE
[TextInput] "tab" key inserts a tab, doesn't move to next input

### ISSUE THREAD

**Issue by Sidnicious** [facebook/react-native#3448]
On iOS, if I make an app with two UITextFields then I can tab between them (when a keyboard is connected, or in the simulator):

![](https://cloud.githubusercontent.com/assets/111870/10520203/040767e2-7337-11e5-9208-4df8014e8ce7.gif)

A react-native TextInput gets literal tabs:

![](https://cloud.githubusercontent.com/assets/111870/10520458/2739ab0c-7338-11e5-8492-d688bc53ac6b.gif)

How can I get the iOS behavior back?

**Comment by brentvatne** [comment]
Thanks for the report! Let's consolidate this into #641
