### ISSUE TITLE
RangeError: Maximum call stack size exceeded.

### ISSUE THREAD

**Issue by govarthananve** [facebook/react-native#34498]
### Description

From today(25.08.2022) morning getting this error on
 ERROR  RangeError: Maximum call stack size exceeded.
 ERROR  Error: Requiring module "node_modules/pretty-format/build/index.js", which threw an exception: RangeError: Maximum call stack size exceeded.

### Version

0.64.2

### Output of `npx react-native info`

` GROUP    %c action %cpersist/REHYDRATE %c@ 20:02:34.968 color: gray; font-weight: lighter; color: inherit; color: gray; font-weight: lighter;
 ERROR  RangeError: Maximum call stack size exceeded.
 ERROR  RangeError: Maximum call stack size exceeded.
 ERROR  Error: Requiring module "node_modules/pretty-format/build/index.js", which threw an exception: RangeError: Maximum call stack size exceeded.
 ERROR  Error: Requiring module "node_modules/pretty-format/build/index.js", which threw an exception: RangeError: Maximum call stack size exceeded.
 ERROR  Error: Requiring module "node_modules/pretty-format/build/index.js", which threw an exception: RangeError: Maximum call stack size exceeded.
 ERROR  Error: Requiring module "node_modules/pretty-format/build/index.js", which threw an exception: RangeError: Maximum call stack size exceeded.
 ERROR  Error: Requiring module "node_modules/pretty-format/build/index.js", which threw an exception: RangeError: Maximum call stack size exceeded.
 ERROR  Error: Requiring module "node_modules/pretty-format/build/index.js", which threw an exception: RangeError: Maximum call stack size exceeded.
 ERROR  Error: Requiring module "node_modules/pretty-format/build/index.js", which threw an exception: RangeError: Maximum call stack size exceeded.
 ERROR  Error: Requiring module "node_modules/pretty-format/build/index.js", which threw an exception: RangeError: Maximum call stack size exceeded.
 ERROR  Error: Requiring module "node_modules/pretty-format/build/index.js", which threw an exception: RangeError: Maximum call stack size exceeded.
 ERROR  Error: Requiring module "node_modules/pretty-format/build/index.js", which threw an exception: RangeError: Maximum call stack size exceeded.
 ERROR  Error: Requiring module "node_modules/pretty-format/build/index.js", which threw an exception: RangeError: Maximum call stack size exceeded.
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect. 
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
 ERROR  Error: Requiring module "node_modules/pretty-format/build/index.js", which threw an exception: RangeError: Maximum call stack size exceeded.
 ERROR  Error: Requiring module "node_modules/pretty-format/build/index.js", which threw an exception: RangeError: Maximum call stack size exceeded.
 ERROR  Error: Requiring module "node_modules/pretty-format/build/index.js", which threw an exception: RangeError: Maximum call stack size exceeded.
 ERROR  Error: Requiring module "node_modules/pretty-format/build/index.js", which threw an exception: RangeError: Maximum call stack size exceeded.
 ERROR  Error: Requiring module "node_modules/pretty-format/build/index.js", which threw an exception: RangeError: Maximum call stack size exceeded.
 ERROR  Error: Requiring module "node_modules/pretty-format/build/index.js", which threw an exception: RangeError: Maximum call stack size exceeded.
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect. 
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.`

### Steps to reproduce

after running the app in a metro server on

### Snack, code example, screenshot, or link to a repository

Don't have

**Comment by govarthananve** [comment]
we found the issue in core-js NPM 
I am closing this issue

**Comment by manojkyyba** [comment]
> 

How to close this issue?

**Comment by govarthananve** [comment]
We used core-js NPM so we removed it from our project
https://www.npmjs.com/package/core-js
