### ISSUE TITLE
Q: Any autocompletion plugins for CSS in JS notation?

### ISSUE THREAD

**Issue by roman01la** [facebook/react-native#345]
How do you write styles efficiently? Would be great to have `emmet` for CSS in JS notation.

**Comment by frantic** [comment]
I don't think RN project itself addresses this kind of problems. You can always configure your editor or submit a patch to emmet to support all the awesomeness you can think of.

**Comment by roman01la** [comment]
Yeah, just wondering if someone here have a solution already.

**Comment by joewood** [comment]
There are plenty of options for editors like Atom, with TypeScript/Flow plugins and type annotations RN. That's what I'm currently using. I couldn't see any support for Emmet though.

**Comment by cmnstmntmn** [comment]
soon it's own editor http://nuclide.io/
