### ISSUE TITLE
main.jsbundle does not exist in apple-m1 xcode13

### ISSUE THREAD

**Issue by ekamnh** [facebook/react-native#34509]
### Description

Hello

I am keep getting this error when generating archive

however build in simulator is working fine

getting beloe error

Showing Recent Messages
File /Users/simranjeet/Library/Developer/Xcode/DerivedData/ShhParty-csbogbjoovolurdbnvnwtayywufy/Build/Intermediates.noindex/ArchiveIntermediates/ShhParty/BuildProductsPath/Release-iphoneos/ShhParty.app/main.jsbundle does not exist. This must be a bug with

please help

Thanks

### Version

0.63.2

### Output of `npx react-native info`

System:
    OS: macOS 12.5
    CPU: (8) x64 Apple M1 Pro
    Memory: 62.90 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.20.0 - ~/.nvm/versions/node/v14.20.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 6.14.17 - ~/.nvm/versions/node/v14.20.0/bin/npm
    Watchman: 2022.08.22.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

when generating archive getting this issue

however build in simulator is working fine

### Snack, code example, screenshot, or link to a repository

<img width="1259" alt="image" src="https://user-images.githubusercontent.com/28934054/186927404-4d19110c-4780-4669-84ea-753f63b45fc2.png">

**Comment by Marcoo09** [comment]
Maybe this comment helps you: https://github.com/facebook/react-native/issues/29356#issuecomment-657944980

**Comment by saravanakumargn** [comment]
> Maybe this comment helps you: [#29356 (comment)](https://github.com/facebook/react-native/issues/29356#issuecomment-657944980)

This is not working

**Comment by divyangsolanki** [comment]
Same for me too. Not working with apple-m1.

**Comment by popking5466** [comment]
### This operation worked for me and saved my week :) 

Add this to the package.json - scripts

`"bundle:ios": "node ./node_modules/react-native/local-cli/cli.js bundle --platform ios --entry-file index.js --bundle-output ios/yourAppName/main.jsbundle --dev=false --verbose"`

Now you can run the command to generate main.jsbundle:

`npx yarn bundle:ios`

Open the Xcode -> Select project target -> add `main.jsbundle` to `Copy Bundle Resource` in `Build Phases`

`Archive` again.

[https://ananda-gopal.medium.com/react-native-main-jsbundle-does-not-exist-5e9c3527554f](url)
