### ISSUE TITLE
Modal animation issue

### ISSUE THREAD

**Issue by Willham12** [facebook/react-native#34518]
### Description

Modal not changed state if animationType !== 'none'
```js
<Modal
statusBarTranslucent={true}
animationType={'none'}
transparent={true}
visible={visible}>
...
</Modal>
```

### Version

0.67.5

### Output of `npx react-native info`

System:
    OS: macOS 12.5.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 17.51 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.13.2 - ~/.nvm/versions/node/v16.15.0/bin/npm
    Watchman: 2022.07.04.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 28, 29, 30, 31, 32, 33
      Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.1.0, 33.0.0, 33.0.0
      System Images: android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-31 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: Chipmunk 2021.2.1 Patch 2 Chipmunk 2021.2.1 Patch 2
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 18.0.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.4 => 0.67.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Check the snack example, the timeout is to reproduce a state changing from for example an API
Change the animationType to 'none' is working

### Snack, code example, screenshot, or link to a repository

https://snack.expo.dev/j6pllqH6a

**Comment by DoctorJohn** [comment]
Hi @Willham12, I took the [official modal example](https://reactnative.dev/docs/modal) and changed the animationType to none. That approach works for me. Maybe have a look (didn't spent time comparing it to your stack, sorry). https://snack.expo.dev/C0F7SNdOj

**Comment by Willham12** [comment]
@DoctorJohn the problem is that it works 2/3 times.

**Comment by dishantwalia** [comment]
Possible Fix https://github.com/facebook/react-native/issues/34018#issuecomment-1209286537
