### ISSUE TITLE
[Docs] Add note about Windows & Linux community responsibilities to the docs

### ISSUE THREAD

**Issue by ide** [facebook/react-native#3451]
For the forseeable future the OS X development experience (DX) is the highest priority because all of the core RN team and most of FB engineering uses Macs. Also you need OS X to build the iOS app anyway. The DX on OS X will naturally receive the most care and attention through extensive dogfooding and needing to support the large org. At the same time there are people in the community who are on Windows or Linux and would like to use RN. Since this is a community need, support for Windows and Linux is designated as a community responsibility.

So, communicating this clearly and helping people be aware of this is important. We should include it in the docs as well as have some text to paste or link people to in issues about Windows or Linux support. I don't have a specific place in the docs in mind but think we need to highlight this point somewhere in the setup flow.

cc @vjeux @mkonicek

**Comment by mkonicek** [comment]
I agree we should make this more obvious :)

**Comment by mkonicek** [comment]
How about a separate item 'Windows and Linux' support. At the beginning of the page you can explain the reasoning you already did very well in an issue I saw. Below could be the list of things that are known to work differently / not working yet on each platform.

**Comment by mkonicek** [comment]
I'm at a conf in Prague and a friend here is using RN on Windows. I will check how the experience is and get feedback.

**Comment by bestander** [comment]
done
