### ISSUE TITLE
Pod install Error

### ISSUE THREAD

**Issue by scott8013** [facebook/react-native#34519]
### Description

<img width="1679" alt="image" src="https://user-images.githubusercontent.com/26688426/187063207-e2c4dfdb-0c60-4300-99d8-37f636fa564b.png">

When init Project use 
```shell
npx react-native init udemy --template react-native-template-typescript
```

### Version

0.69.5

### Output of `npx react-native info`

System:
    OS: macOS 12.5.1
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 183.38 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
    Watchman: 2022.08.15.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 30, 31
      Build Tools: 29.0.2, 31.0.0
      System Images: android-25 | Google Play Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7784292
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 14.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

cd ios/ & pod install

### Snack, code example, screenshot, or link to a repository

https://github.com/scott8013/react-native-udemy.git

**Comment by scott8013** [comment]
repository site: https://github.com/scott8013/react-native-udemy

**Comment by DoctorJohn** [comment]
You'll probably get more help reporting this in the typescript templates repository. https://github.com/react-native-community/react-native-template-typescript

**Comment by scott8013** [comment]
I don't use typescript. Always has the same proplem.

**Comment by DoctorJohn** [comment]
In your issue description you wrote:

> When init Project use
> npx react-native init udemy --template react-native-template-typescript

Thats the typescript template. You should omit `--template react-native-template-typescript` if you don't want to use typescript.

**Comment by scott8013** [comment]
<img width="1196" alt="image" src="https://user-images.githubusercontent.com/26688426/187193880-4f55d7dc-ae18-49bb-8a36-67bece19cf3c.png">
Don't use ts template.  have same error message. 
I test clone ...

**Comment by scott8013** [comment]
<img width="1677" alt="image" src="https://user-images.githubusercontent.com/26688426/187194201-158a411a-562b-4a90-91be-3322041d50a9.png">

**Comment by scott8013** [comment]
It's OK, Thanks
