### ISSUE TITLE
react-native init creates an App.js file which contains TypeScript

### ISSUE THREAD

**Issue by HM-23-HM** [facebook/react-native#34511]
### Description

After running `react-native init <application-name>` the App.js file contains TypeScript code.

Here are some snippets;

Line 10: `import type {Node} from 'react';`
Line 29: `const Section = ({children, title}): Node => {`
Line 55: `const App: () => Node = () => {`

### Version

0.69.5

### Output of `npx react-native info`

System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz
    Memory: 9.33 GB / 15.88 GB
  Binaries:
    Node: 16.16.0 - C:\Program Files\nodejs\node.EXE     
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD     
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD        
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: AI-212.5712.43.2112.8609683
    Visual Studio: Not Found
  Languages:
    Java: 17.0.4 - C:\Program Files\Common Files\Oracle\Java\javapath\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0
    react-native: 0.69.5 => 0.69.5
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Run `react-native init <application-name>`

### Snack, code example, screenshot, or link to a repository

N/a

**Comment by DoctorJohn** [comment]
That's for [flow](https://flow.org/) and not for typescript. Is this causing issues for you?

**Comment by cortinico** [comment]
> That's for [flow](https://flow.org/) and not for typescript. Is this causing issues for you?

Closing because of this. Also starting from 0.71 we moved the template to TypeScript
