### ISSUE TITLE
Are there any plans to replace unsupported APIs (KEYCODE_BACK and #onBackPressed) to support Android's new Predictive back gesture? 

### ISSUE THREAD

**Issue by dzuluaga** [facebook/react-native#34529]
### Description

Apps using React Native targeting enableOnBackInvokedCallback might break if they use the code that references the unsupported APIs like KEYCODE_BACK and #onBackPressed). Therefore, we recommend migrating to OnBackPressedCallback to support the new back gesture experience and avoid any breakages. 

Are there any plans to replace these APIs?

## Context
Android 13 introduced [the Predictive Back gesture](https://android-developers.googleblog.com/2022/07/prepare-your-app-to-support-predictive-back-gestures.html), which enables users to visualize where they're going to land before completing a back swipe.

### Version

0.68

### Output of `npx react-native info`

N/A

### Steps to reproduce

1. EnableOnBackInvokedCallback=true in the AndroidManifest.xml of any given app
2. Target AndroidSdk 33
3. Use the back gesture in an app that uses unsupported APIS:
    * [OnBackPressed](https://github.com/search?l=&q=onbackpressed+repo%3Afacebook%2Freact-native&type=code) ReactActivity, ReactDelegate, ReactFragment, ReactActivityDelegate, ReactAppTestActivity, ReactInstanceManager
    * [KEYCODE_BACK](https://github.com/search?q=keycode_back+repo%3Afacebook%2Freact-native&type=code) ReactModalHostView

### Snack, code example, screenshot, or link to a repository

The new APIs, docs, and samples are available from the above link. Please reply if you need more info.

**Comment by cortinico** [comment]
@makovkastar has relevant context here 👍

**Comment by makovkastar** [comment]
Hi @dzuluaga, thanks for brining this to our attention. The predictive back gesture is a developer only feature in Android 13, so we have some future plans to migrate to the new APIs before they are enforced in the next Android release in 2023.

We've already started looking into the existing callsites, and currently investigating the migration paths.

**Comment by grahammendick** [comment]
@makovkastar Nice, thanks for the info. Any plans on working with authors of navigation libraries like me (Navigation router) or software mansion (react native screens cc @kkafar)? I think we both use the Fragment back stack so the predictive back gesture should work for us out of the box - as long as we can turn off React Native back handling.

**Comment by daniel-w00** [comment]
> Hi @dzuluaga, thanks for brining this to our attention. The predictive back gesture is a developer only feature in Android 13, so we have some future plans to migrate to the new APIs before they are enforced in the next Android release in 2023.
> 
> We've already started looking into the existing callsites, and currently investigating the migration paths.

Android 14 will be released soon. Is there an update on this?

**Comment by luluwu2032** [comment]
Hi @dzuluaga  @grahammendick @daniel-w00 I'm working on Android 14 readiness for RN, let me look into this and I'll keep you updated in this thread. From what we know Android 14 will be released in late Aug/early Sep so we should have enough time for this.

**Comment by kkafar** [comment]
Hey @luluwu2032,
have you had opportunity to push this topic forward?

**Comment by grahammendick** [comment]
I got [predictive back gesture working on the Navigation router](https://github.com/grahammendick/navigation/pull/781) as you can see in the vid below. It didn't require any changes to react native. You can try the Twitter sample for yourself on either [the old](https://github.com/grahammendick/navigation/tree/master/NavigationReactNative/sample/twitter) or [the new architecture](https://github.com/grahammendick/navigation/tree/master/NavigationReactNative/sample/fabric)

https://github.com/facebook/react-native/assets/1761227/ff136d82-60e0-4e99-9914-fbc1c7f09828

**Comment by grahammendick** [comment]
I got [predictive back gesture working inside a ComponentDialog](https://github.com/grahammendick/navigation/pull/787) (see attached vid). Although Android says that it calls the gesture back callbacks in the reverse order, it's actually not true for Dialog's. [The Dialog's close callback takes precedence over all other callbacks](https://issuetracker.google.com/issues/343750854). If you want your back callback to be called before the Dialog's close callback, you have to add it to the ComponentDialog's `onBackPressedDispatcher`.

I had to create [a custom FragmentHostCallback](https://github.com/grahammendick/navigation/blob/master/NavigationReactNative/src/android/src/main/java/com/navigation/reactnative/DialogRootView.java#L184) to get the Dialog back stack to receive the back gesture before the Dialog closed. @kkafar you probably don't need this if you're not using the `FragmentManager's` built-in back stack.

You can see it running in [the medley sample from the Navigation router](https://github.com/grahammendick/navigation/tree/master/NavigationReactNative/sample/medley).

https://github.com/facebook/react-native/assets/1761227/e419a282-c49b-49e5-b4ec-a7a01931cdfe

**Comment by Siddhantshelake** [comment]
I’m aware that disabling android:enableOnBackInvokedCallback="false" temporarily restores the old back behavior on Android 16, but that’s not a long-term solution.

Specifically, on Android 16 devices, pressing the physical back button should navigate to the previous screen in the navigation stack, rather than exiting the app or going to the device home screen.
Right now, returning to the main screen from a directed screen does not behave as expected when predictive back gestures are enabled.

I’m looking for guidance on the best way to handle this:

Are there recommended approaches in React Navigation to fully support Android 16+ predictive back gestures?

Are there plans for built-in support for this behavior in upcoming releases?

**Comment by Siddhantshelake** [comment]
Hi all,

I’m experiencing an issue on Android 16 — pressing the hardware back button causes the app to exit immediately instead of navigating to the previous screen within the stack.

Why This Happens

Android 16 no longer calls onBackPressed() or dispatches KEYCODE_BACK for apps targeting API level 36+.

React Native still depends on these legacy callbacks (onBackPressed() → ReactInstanceManager.onBackPressed() → JS BackHandler).

As a result, when predictive back is active, React Native never receives the back event, and Android assumes the activity should exit — causing the app to close.

Any sample code, patch, or guidance would be greatly appreciated 🙏

**Comment by nexquery** [comment]
> Hi all,
> 
> I’m experiencing an issue on Android 16 — pressing the hardware back button causes the app to exit immediately instead of navigating to the previous screen within the stack.
> 
> Why This Happens
> 
> Android 16 no longer calls onBackPressed() or dispatches KEYCODE_BACK for apps targeting API level 36+.
> 
> React Native still depends on these legacy callbacks (onBackPressed() → ReactInstanceManager.onBackPressed() → JS BackHandler).
> 
> As a result, when predictive back is active, React Native never receives the back event, and Android assumes the activity should exit — causing the app to close.
> 
> Any sample code, patch, or guidance would be greatly appreciated 🙏

I think it would be better to open a new topic for this.
