### ISSUE TITLE
[ScrollView] Children in a ScrollView don't always cancel touches when the ScrollView is scrolling

### ISSUE THREAD

**Issue by ide** [facebook/react-native#3452]
When scrolling through a ListView with lots of content, sometimes it is possible to trigger the `onPress` event of a Touchable row. The ListView keeps on scrolling while the `onPress` handler runs.

(In our code, the resulting UX is janky for a few reasons: 1/ this usually happens when new list rows are being rendered, so the UI is already a little choppy, 2/ the `onPress` handler in our case pushes a new route onto the Navigator stack, so it's trying to smoothly animate the scene transition, 3/ the ListView keeps on scrolling with inertia so you lose your position in the feed when you navigate back to it, 4/ because the ListView is scrolling and rendering new rows, that adds jank to the Navigator's ongoing transition.)

It seems to occur when the app chokes (not quite sure which thread). I suspect the JS doesn't learn that the ScrollView has begun scrolling, so it lets the Touchable component handle the press.

**Comment by negativetwelve** [comment]
+1 I've been experiencing this occasionally in our app but didn't really know how to describe it. This description is spot on @ide!

**Comment by MossP** [comment]
+1 I've been getting this more recently. Used to only get it on iPhone4 but assumed it was down to a lack of optimisation on my part for slower devices.

**Comment by mc-zone** [comment]
+1 have been obsessed with this problem for several days.  And it looks like result form my `renderRow` returns a complex row structure in the `ListVew` so that sometimes make my phone scroll slowly. It's more seriously in other slower devices too.

**Comment by mc-zone** [comment]
#2569

**Comment by gre** [comment]
Experiencing this too, do anyone have a workaround for this?

**Comment by kinhunt** [comment]
+1

**Comment by mc-zone** [comment]
There is a dirty way that I've found to bypass this case temporarily:
```jsx
var _dirtyListViewPressEnabled = true;
```
```jsx
<ListView 
    onTouchMove={(e)=>{
        _dirtyListViewPressEnabled = false;
    }}
    onTouchEnd={(e)=>{
        _dirtyListViewPressEnabled = true;
    }}
    renderRow={(rowData)=>{
        return (
            <TouchableOpacity
                onPress={()=>{
                    if( !_dirtyListViewPressEnabled ) return ;

                    //other...
                }}
            > 
                <RowItem rowData={rowData} />
            </TouchableOpacity>
        );
    }}
/>
```

But looking forward to real solutions.

**Comment by kinhunt** [comment]
@mc-zone clever

**Comment by mbrock** [comment]
We also have these problems in a semi-complex list view. No more complex than, say, Twitter; each row has an image plus some nested text views. The combination of jank and the mistaken touch activations make the app's main screen unusable, and thus unreleasable, so for us this issue is very important.

There are enough significant issues and complications related to performance in multi-page apps with some degree of complexity that I would consider adding a temporary warning to the main home page, e.g., "If you plan to create a relatively complex app, consider our notes on performance, and remember that the framework is still rather immature."

**Comment by arunshan** [comment]
@ide I still see this issue occurring on ListView with TouchableOpacity elements in renderRow. I used @mc-zone 's implementation and it still does not work fine for me. Is there a quick fix for the same? Also can I listen to events for scrollEnd for ListView or ScrollView ?

**Comment by arunshan** [comment]
This is a hack that works fine for me but we need a proper implementation.

```javascript
<ListView
              dataSource={this.state.dataSource}
              renderRow={this._renderRow}
              onChangeVisibleRows={this._renderSearchIcon}
              onScroll={this._onScrollListView}
              decelerationRate={0.9}
              onScrollBeginDrag={(e)=> {
                let listarraystates = this.state.scrollStates
                listarraystates.push("onScrollBeginDrag")
                this.setState({
                  scrollStates: listarraystates
                })
              }}
              onMomentumScrollEnd={(e) => {
                let listarraystates = this.state.scrollStates
                listarraystates.push("onMomentumScrollEnd")
                this.setState({
                  scrollStates: listarraystates
                })
              }}
              onTouchMove={(e) => {
                let listarraystates = this.state.scrollStates
                listarraystates.push("onTouchMove")
                this.setState({
                  scrollStates: listarraystates
                })
              }}
              onTouchStart={(e) => {
                let listarraystates = this.state.scrollStates
                listarraystates.push("onTouchStart")
                this.setState({
                  scrollStates: listarraystates
                })
              }}
              onTouchEnd={(e)=>{
                let listarraystates = this.state.scrollStates
                listarraystates.push("onTouchEnd")
                this.setState({
                  scrollStates: listarraystates
                })
              }}
            />
```
Then in the onPress Event for the items in the ListView

```javascript
let currliststatearr = this.state.scrollStates
    if(currliststatearr.length>2 &&
      ((currliststatearr[currliststatearr.length-2]==='onMomentumScrollEnd' && currliststatearr[currliststatearr.length-1]==='onTouchStart')
      || (currliststatearr[currliststatearr.length-2]==='onTouchEnd' && currliststatearr[currliststatearr.length-1]==='onTouchStart')))
      this.props.navigator.push({
        id: 9,
        passProps: {
          listingdata: THUMB_URLS[rowID]
        }
      })
```

**Comment by arunshan** [comment]
@ide and @brentvatne Any updates on this issue? My solution above does not work on iPhobe 6s and 6s plus as the touch is really sensitive (force touch probably).

**Comment by arunshan** [comment]
@brentvatne This is a pressing issue. What do you think is the easiest way to get around this issue for production?

**Comment by ranyefet** [comment]
+1 I also have the same issues.

**Comment by ninamanalo** [comment]
+1

**Comment by brentvatne** [comment]
@arunshan - sorry I don't have a solution for this, let's get the issue on [ProductPains](https://productpains.com/product/react-native/?tab=top) so we can be sure to get more attention to it.

cc @vjeux

**Comment by arunshan** [comment]
@brentvatne Here you go.
https://productpains.com/post/react-native-listview/onpress-event-triggered-while-scrolling-in-listview/

**Comment by gre** [comment]
@arunshan I think you have created with a wrong "product", it appears in "react native listview" not "react native"

**Comment by arunshan** [comment]
Thanks @gre. I made that change and it should appear in 'react native'

**Comment by ranyefet** [comment]
@ide @brentvatne @vjeux Any updates regarding this issue?
I'm about to launch an app i've been working on the last 4 months and I see this issue all the time. 

Is there any work around for this issue?

**Comment by ide** [comment]
You could maybe change the value of pointerEvents to block touches to children while the scroll view is scrolling. I haven't tested it though.

**Comment by kinhunt** [comment]
@ranyefet similar situation here.

@ide please tell us how to try your hack, thanks

**Comment by Sourcebits-Padmapreethi** [comment]
@all : Here is how , i was able to fix this issue,

<ScrollView style={styles.scrollView} 
horizontal={true} 
onScroll={this.handleScroll} 
onTouchMove={this.onTouchMove} 
onTouchEnd={this.onTouchEnd} />

The catch here is to use onTouchMove and onTouchEnd to know if the scroll state.

onTouchMove:function(){
    isScrollInProgress = true;
  },

  onTouchEnd:function(){
    isScrollInProgress = false;
  },

Keep a flag which indicates whether it's scrolling.based on the flag control the onPress method of TouchableHighlight component.

**Comment by gre** [comment]
@ide , i'll give a try to your `pointerEvents` workaround, thanks!

Why is this behavior not the default on ScrollView if it works? Any downsides?

**Comment by ide** [comment]
It's complicated and adding hacks to cover up a core issue in the gesture system (plus I haven't actually tried it.. just an idea that could work). We need to make the gesture system better and until then, make it possible for you to write the code to work around this issue.

**Comment by gre** [comment]
@ide Ok, make a lot of sense.
https://gist.github.com/gre/16f4235d23659c7d4374 : I've started a quick attempt following your idea.. it's a very naïve implementation (using onTouchStart & onTouchEnd, whatever the finger is) that unfortunately doesn't seem to work.. Maybe I need to give another try, but for now I guess I'll wait for that proper fix on gesture system.

**Comment by iostalk** [comment]
Watch

**Comment by iostalk** [comment]
Version 0.13 is ok?

**Comment by magicismight** [comment]
+1

**Comment by MiincGu** [comment]
+1

**Comment by majak** [comment]
I've landed few native diffs (last one 2e8eb652e10ba5d5419f277a98294faff4e46f56) that should make this issue virtually nonexistent. They are currently in the 0.20rc.
Feel free to try it out and let me know if it helps.

**Comment by pietropizzi** [comment]
\o/

**Comment by majak** [comment]
I'm closing this issue since I believe my changes have fixed this.

**Comment by oblador** [comment]
@majak: This still happens with RN 0.23RC, getting this on older devices when JS thread chokes. In rare really bad cases even longpress is triggered.

**Comment by majak** [comment]
@oblador That's not good. Thanks for reporting it. I'm not sure why it would still happen.
Could you tell me more about your case? Is scrollview involved?

A sample app that would demonstrate the issue would be ideal. Just run a long for-loop to make JS busy.

**Comment by oblador** [comment]
@majak: Will do when I get the time. Did also notice that elements positioned outside but over the scrollview/listview fail to register taps until the momentum scroll has come to a complete stop which I'm guessing is related to your changes.

**Comment by majak** [comment]
Ok, please file a new github issue for each of these things and cc me. I know that setting up a sample app could take a while, so a description of relevant component hierarchy would be useful for start (like you did here).

**Comment by zhuchuanwu** [comment]
+1

**Comment by hite** [comment]
+1 still bug in 0.24
