### ISSUE TITLE
Can't connect metro on real IOS device 

### ISSUE THREAD

**Issue by ArtemKosiakevych** [facebook/react-native#34531]
### Description

Works on simulator, can't connect packager on real device, fast refresh doesn't work, app is displayed, dev menu is opening, after click Debug with chrome throws red error described here https://reactnative.dev/docs/running-on-device#troubleshooting, if set airplane mode on the device, remove usb cable app is reloading through dev menu anyway (have no idea where app gets js bundle).

I double checked that:  
 - app is connected via USB
 - packager is running
 - changed localhost to machine IP in ` RCTWebSocketExecutor.mm` file
 - jscodeLocation url is correct in AppDelegate
 - device and computer are connected to the same network
 - device has correct certificates in xcode Signing
 - the IP address of computer is correct under Build process in xcode
 - tried to configure bundle through the dev menu on the device to computer IP
 - Schema in xcode has Debug build option 

### Version

0.66.3

### Output of `npx react-native info`

System:
    OS: macOS 12.5.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.56 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.8.0 - /usr/local/bin/node
    Yarn: 1.22.18 - ~/tp-mobile-app/packages/app/node_modules/.bin/yarn
    npm: 8.18.0 - /usr/local/bin/npm
    Watchman: 2022.08.22.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 28, 29, 30, 32
      Build Tools: 29.0.2, 30.0.2, 32.0.0
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.2 => 17.0.2
    react-native: ^0.66.3 => 0.66.3
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

 - create new app
 - launch on IOS real device 
 - Click debug remotely in dev menu

### Snack, code example, screenshot, or link to a repository

AppDelegate

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

Packager when press "r" to reload 

<img width="541" alt="image" src="https://user-images.githubusercontent.com/17948785/187405056-64329233-6e02-48a5-bd27-c57980c2d78a.png">

List of devices 

<img width="523" alt="image" src="https://user-images.githubusercontent.com/17948785/187405280-16595c3a-9b8d-4b6d-83f2-a8d5b81e5fdc.png">

Red error when press Debug remotely 

![photo_2022-08-30 12 45 38](https://user-images.githubusercontent.com/17948785/187405675-9be17455-7344-4646-9ec6-e79878b58a32.jpeg)

**Comment by robsonsr** [comment]
Hi @ArtemKosiakevych, I'm with the same problem.  Did you find a solution?

**Comment by kbirgoren** [comment]
I had the same issue but apparently, none of the suggested solutions worked for me.

Then I thought, this might be related to firewall settings set by Eset Security installed on my device.

I added the required ports to allow the list then everything started to work as normal.

But the weird thing is; Fast Reload was just working fine on Android devices but failing on iOS devices.

So, if you have a firewall in your system. Add the required ports to allowlist (it's 8081 by default)
