### ISSUE TITLE
updateExtraData not called

### ISSUE THREAD

**Issue by gaodengjiaoyu** [facebook/react-native#34543]
### Description

When I use new fabric Architecture version(0.68.1),my onCollectExtraUpdates&updateExtraData method both not be called, but I need use these methods to update my view.
So I want to know ,in the new fabric Architecture, which method should I replace the method ??
Look forward your reply.

### Version

0.68.1

### Output of `npx react-native info`

System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Memory: 359.79 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.20.0 - ~/.nvm/versions/node/v14.20.0/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 6.14.17 - ~/.nvm/versions/node/v14.20.0/bin/npm
    Watchman: 2022.06.06.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK: Not Found
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Java: javac 11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: 0.68.1 => 0.68.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

com.facebook.react.uimanager.LayoutShadowNode#onCollectExtraUpdates
com.facebook.react.uimanager.ViewManager#updateExtraData

### Snack, code example, screenshot, or link to a repository

as the above

**Comment by cortinico** [comment]
> When I use new fabric Architecture version(0.68.1),my onCollectExtraUpdates&updateExtraData method both not be called, but I need use these methods to update my view.
> So I want to know ,in the new fabric Architecture, which method should I replace the method ??
> Look forward your reply.

The method is actually called:
https://github.com/facebook/react-native/blob/49c90f7a7ee1290bc694184873bdc0e06318ba98/ReactAndroid/src/main/java/com/facebook/react/fabric/mounting/SurfaceMountingManager.java#L1068-L1089

Can you provide a small reproducer so that we can check what is going on?
