### ISSUE TITLE
Text Input multiple not working

### ISSUE THREAD

**Issue by Estroo** [facebook/react-native#34557]
### Description

Hello,

I just upgraded from RN 0.63.3 to RN 0.64.0, I'm using TextInput with the property multiple set to true. I don't have any issue on Android but on iOS when I set the build configuration from Debug to Release it doesn't work anymore. I can type but the onChangeText doesn't process.

My only think about it would be that I'm using App-Connect / MobileIron and on release mode there is a conflict preventing TextInput to work but I can't find anything about it

### Version

0.64.0

### Output of `npx react-native info`

System:
    OS: macOS 12.5
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 251.30 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.15.1 - ~/.nvm/versions/node/v14.15.1/bin/node
    Yarn: Not Found
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.1/bin/npm
    Watchman: 2022.03.21.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 27, 29, 32
      Build Tools: 29.0.2, 32.0.0
      System Images: android-27 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7935034
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_312 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.64.0 => 0.64.0
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Upgrade to React Native 0.64.0
Launch the app on release mode on iOS
try to type something in the textInput

### Snack, code example, screenshot, or link to a repository

```js
<View
    style={{
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: 'red',
    }}
  >
    <TextInput
      multiline
      style={{height: 200, width: 200, backgroundColor: '#FFFFFF'}}
      onChangeText={text => Alert.alert('text', text)}
    />
  </View>
```

**Comment by spyx08** [comment]
Hi @Estroo1 did you manage to fix your issue ? 
I encounter the same one

**Comment by fabriziobertoglio1987** [comment]
Do you still experience this issue? 

I have four years of experience maintaining facebook/react-native and I specialize in the Text and TextInput components. I currently have 58 [facebook/react-native PRs](https://github.com/facebook/react-native/pulls?q=is%3Apr+author%3Afabriziobertoglio1987+). 

If you still experience this issue, I will prepare a patched release with the fix.

Thanks a lot

**Comment by 3xpedia** [comment]
Hello @fabriziobertoglio1987 I was tracking this issue because I also have the problem in some iOS applications I maintain. I would be very glad if you could take a look.
If you need support to test a patch with the MobileIron wrapper, please let me know.

Many thanks for your help!

**Comment by spyx08** [comment]
Hi @fabriziobertoglio1987 same for me, I still have the issue, related to MobileIron and all RN version >= 0.64 on the multiline TextInput.

Thank you !

**Comment by fabriziobertoglio1987** [comment]
I added the issue to my todo list. I will keep you updated on my progress. Thanks for the support 🙏
