### ISSUE TITLE
While running command like  "react-native init AwesomeProject" am getting following error please tell me how to solve it  ?

### ISSUE THREAD

**Issue by prashanthnani** [facebook/react-native#3456]
Installing react-native package from npm...
/Users/vasavi/dev/CLOUDSEED_APP/AwesomeProject/node_modules/react-native/local-cli/init.js:7
class CreateSuppressingTerminalAdapter extends TerminalAdapter {
^^^^^
SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/vasavi/dev/CLOUDSEED_APP/AwesomeProject/node_modules/react-native/local-cli/cli.js:11:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

**Comment by eLBirador** [comment]
+1, I encountered the same issue.

**Comment by ide** [comment]
Make sure you have Node 4+ as explained in the setup instructions.

**Comment by sriharrsha** [comment]
Have the same issue im using 4.0.0 but still exists

**Comment by brentvatne** [comment]
Thanks for the followup @sriharrsha!

**Comment by ami44** [comment]
Thanks

**Comment by jickyi521** [comment]
Thanks

**Comment by g3r4** [comment]
@sriharrsha Thanks a lot man !

**Comment by lupugabriel1** [comment]
@sriharrsha You saved my day !

**Comment by super-coder** [comment]
ln: /usr/bin/node: Operation not permitted

**Comment by chalupien** [comment]
Same problem while running Node 5.2 Is there a new fix?

**Comment by petervavro** [comment]
Run `nvm install node && nvm alias default node`

**Comment by srinivasdamam** [comment]
@petervavro for me` nvm` didn't work, tried all the workarounds for it  and  finally used `n` package manager and it worked.

**Comment by alayo** [comment]
+1, I encountered the same issue.

**Comment by ssmlee04** [comment]
thanks

**Comment by markhache-imane** [comment]
thanks it Worked 👍

**Comment by nithinp** [comment]
use node version 4.4.4
