### ISSUE TITLE
Packager running in wrong directory when building in a monorepo

### ISSUE THREAD

**Issue by johanblumenberg** [facebook/react-native#34565]
## Description

When running `react-native run-android` the packager is running in the wrong directory, and fails to find the index file.

Example setup having two react native apps in a monorepo: https://github.com/johanblumenberg/react-native-monorepo-demo

To reproduce:

```
$ yarn install
$ cd apps/App1
$ yarn android
```

The packager opens in a new terminal, and fails to find the index file, with this error:

```
Error: Unable to resolve module ./index from /Users/code/react-native-monorepo-demo/.: 

None of these files exist:
  * index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * index/index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
    at ModuleResolver.resolveDependency (/Users/code/react-native-monorepo-demo/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:136:15)
    at DependencyGraph.resolveDependency (/Users/code/react-native-monorepo-demo/node_modules/metro/src/node-haste/DependencyGraph.js:231:43)
    at /Users/code/react-native-monorepo-demo/node_modules/metro/src/lib/transformHelpers.js:129:24
    at Server._resolveRelativePath (/Users/code/react-native-monorepo-demo/node_modules/metro/src/Server.js:1137:12)
    at async Server.requestProcessor [as _processBundleRequest] (/Users/code/react-native-monorepo-demo/node_modules/metro/src/Server.js:464:37)
    at async Server._processRequest (/Users/code/react-native-monorepo-demo/node_modules/metro/src/Server.js:420:9)
```

The reason that this command fails is that the packer is trying to figure out which directory to run in based on the location of the react-native script. it runs in the root directory of the repository.

However, starting the packager using `react-native start` works. This works since it runs in the `apps/App1` directory, where the command is executed.

```
$ yarn install
$ cd apps/App1
$ yarn start
```

### Version

0.69.5

### Output of `npx react-native info`

System:
    OS: macOS 12.5.1
    CPU: (8) arm64 Apple M1
    Memory: 98.86 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.19 - ~/.yvm/shim/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/lib/ruby/gems/3.0.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 30, 31
      Build Tools: 30.0.2, 30.0.3, 31.0.0
      System Images: android-29 | Google APIs ARM 64 v8a, android-30 | Google Play ARM 64 v8a, android-31 | Google APIs ARM 64 v8a, android-31 | Google Play ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.13 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

yarn install
cd apps/App1
yarn android

### Snack, code example, screenshot, or link to a repository

https://github.com/johanblumenberg/react-native-monorepo-demo

**Comment by johanblumenberg** [comment]
These two PRs fixes the problem:
- https://github.com/facebook/react-native/pull/34566
- https://github.com/react-native-community/cli/pull/1693

**Comment by cortinico** [comment]
Metro already supports this out of the box:
https://facebook.github.io/metro/docs/configuration

You can specify a `projectRoot` config and customize Metro as you wish

**Comment by johanblumenberg** [comment]
@cortinico 

Good to hear that this feature already exists!

I have read the documentation on how to configure metro. However, I could not make it work, so therefore I took the time to create a ticket and a patch.

This is a summary of what I have tried. Any pointers to where I made a mistake would be really helpful.

### metro.config.js

I have tried to set the `projectRoot` property to the relative path `.` or to an absolute path pointing to the `apps/App1` folder, but none of them work. I even put some invalid javascript code in `metro.config.js`, but nothing happens. I would expect it to fail completely.

However, when I put the `metro.config.js` file in the root folder of the project it is being read, and then the `yarn android` command successfully builds the project.

This doesn't work though, because it would make it impossible to build and run `apps/App2`, and I would have to keep duplicate configs.

### `metro` section in package.json

I ran into the same problem. If I add the config to `apps/App1/package.json` it doesn't seem to be applied. But when I add the config to `package.json` in the root folder, then it is applied.

### Passing `--projectRoot` or `--config` on command line

These options work when passed to `react-native start`, but as I described in the issue description, running `react-native start` directly is not a problem.

However, none of these options exist on the `react-native run-android` command.

**Comment by johanblumenberg** [comment]
The patch that I provided makes metro load the correct config file, `apps/App1/metro.config.js`, when running `react-native run-android` in that folder.
So as far as I understand, it does not only fix the problem with the project root being set wrong, it also makes metro read all configuration from the correct folder.

**Comment by cortinico** [comment]
Thanks for the thorough overview of your attempts.
Can I ask you to open an issue on https://github.com/facebook/metro/issues and link against this one? We can support you further there

> The patch that I provided makes metro load the correct config file, apps/App1/metro.config.js, when running react-native run-android in that folder.

Your original patch touched the packager.sh script which is something we use internally to start Metro for RN Tester. So you won't benefit from that changes as a user.
