### ISSUE TITLE
[Regression] [Layout] height:0 with overflow:hidden ignores height

### ISSUE THREAD

**Issue by MossP** [facebook/react-native#3458]
I'm not sure where this came in 0.12 or 0.13 but in 0.11 it appears to work fine.

This renders at full height on v0.13 (height is ignored) but renders correctly on v0.11.4
```
<View style={{height:0, overflow:'hidden', backgroundColor:'#ff0'}}>
  <Text>Content</Text>
</View>
```

This renders at 1 pixel height
```
<View style={{height:1, overflow:'hidden', backgroundColor:'#ff0'}}>
  <Text>Content</Text>
</View>
```

RNPlay of it on v11.4 working correctly
https://rnplay.org/apps/EsM5Qw

**Comment by browniefed** [comment]
This came in .12. There is another issue filed for this as well.

**Comment by MossP** [comment]
Ah, thanks. I did try to find if it had already been posted but I guess "0" and "height" crop up a lot. I'll close this one to keep the issues focused.
