### ISSUE TITLE
Disable Xiaomi Game Turbo programatically?

### ISSUE THREAD

**Issue by Gabotron-ES** [facebook/react-native#34582]
### Description

In some Xiaomi devices where I installed my react native apk I get a weird "Game Turbo" modal and a floating tab, is there a way to disable this programatically? Not from device settings but with code...

Also, what is Game Turbo for exactly, I haven't felt any difference?

### Version

0.68.2

### Output of `npx react-native info`

Xiaomi devices show a weird game turbo modal that can be disabled frommdevice settings but not ptogramatically

### Steps to reproduce

Xiaomi devices show a weird game turbo modal that can be disabled frommdevice settings but not ptogramatically

### Snack, code example, screenshot, or link to a repository

Xiaomi devices show a weird game turbo modal that can be disabled frommdevice settings but not ptogramatically

**Comment by iBotPeaches** [comment]
I think you are doing this backwards. You should go to MIUI and ask if they have a manifest/snippet/flag you can use to opt out of Game Turbo. I don't think RN Issues is your route for this one.

**Comment by cortinico** [comment]
> I think you are doing this backwards. You should go to MIUI and ask if they have a manifest/snippet/flag you can use to opt out of Game Turbo. I don't think RN Issues is your route for this one.

Exactly. We don't have control over this.
Closing
