### ISSUE TITLE
Separate website for each release

### ISSUE THREAD

**Issue by mkonicek** [facebook/react-native#3459]
People often send pull requests which update both code and /docs which makes sense. However, when the PR is merged, the docs go live immediately but the code is only released in up to 4 weeks. This means the docs are inconsistent with the APIs and CLI commands people get when using React Native.

Here's an idea:
- https://facebook.github.io/react-native/0.13/docs/ are docs for the 0.13.0-stable branch
- https://facebook.github.io/react-native/0.12/docs/ are docs for the 0.12.0-stable branch
- https://facebook.github.io/react-native/master/docs/ are docs for master (current version)
- https://facebook.github.io/react-native/docs/ are docs for the latest non-rc branch (same as 0.12/docs)

We could have one per release (0.12.1, 0.12.2, ...) but that seems unnecessary.

The website is generated by Travis running the [`publish.sh`](https://github.com/facebook/react-native/blob/master/website/publish.sh) script (see `travis.yml`) .

We could implement this by simply having subfolders in the static generated content: https://github.com/facebook/react-native/tree/gh-pages

**Comment by mkonicek** [comment]
@brentvatne, @ide Would you be interested in working on this? I'll be available sporadically because of a conference and vacation, plan to work on this unless someone picks it up.

**Comment by brentvatne** [comment]
I probably won't have time before the conference to do this but I agree that it's very important! This is a great task for someone looking to get their first contribution in. I'll send it out in the newsletter to see if anyone bites! :)

**Comment by kevinzzz007** [comment]
@mkonicek would love to help out, but feel like I am not exactly sure what you meant, could you elaborate and let me know what specifically I can do to help?

**Comment by brentvatne** [comment]
@kevinzzz007 - short version: we want to build a different version of the docs for every tagged release of React Native, and make it possible to switch between those :smile:

**Comment by kevinzzz007** [comment]
@brentvatne that makes sense, since I'm pretty new to doing this, are there recommended approaches?  Resources that would be helpful for me to read over for this task?

**Comment by brentvatne** [comment]
@kevinzzz007 - sorry I haven't done this before. You'll want to get familiar with the /website directory within react-native and how deployment to Github pages works.

**Comment by mihirsoni** [comment]
@brentvatne @mkonicek  Could you just provide little more information how you would be expecting to generate.

I tried to modified the *publish.sh* with taking respective tag version from `git describe` of the each MR. would it be fine if we update that particular directory ?

**Comment by rumal** [comment]
I will work on this. Quick questions
1. Do we need a navigation mechanism to navigate from different documentation sources? 
2. Rather than building from the last build shall I build from all the branches with `stable` suffix? This will allow them to grow/update over time. but it will take few minutes to generate all the sources.

**Comment by mkonicek** [comment]
> 1. Do we need a navigation mechanism to navigate from different documentation sources?

Feel free to leave this out for now.

> 2. Rather than building from the last build shall I build from all the branches with stable suffix? This will allow them to grow/update over time. but it will take few minutes to generate all the sources.

Travis runs on each branch every time there's a commit. It would be very wasteful to regenerate the website for every branch on every commit to master, and would get slower over time as we add more release branches.

**Comment by dabit3** [comment]
@udnisap @mkonicek Let me know if there's anything I can do here, I have some time opened up over the holidays. thanks.

**Comment by ide** [comment]
@dabit3 we'd love helping hands. Figuring out how to build the version-specific web pages (as outlined in @mkonicek's top post) in a way where we rebuild and redeploy the pages only when committing to a specific version's branch would be superb.

**Comment by udnisap** [comment]
I have a rough version at  #3459 which I committed while back.
I does what you asked. Sorry I didnt follow the thread for a while.

**Comment by bestander** [comment]
fixed by #5760 
When it lands we have docs for currently stable version at https://facebook.github.io/react-native.
Aside from that all versions of docs will be archived in https://facebook.github.io/react-native/releases path, e.g. https://facebook.github.io/react-native/releases/0.20 and master branch will be at https://facebook.github.io/react-native/releases/next.

In a following up PR we'll do a widget to switch between versions if people need a quick way to find docs for a specific version
