### ISSUE TITLE
BigInt literal support still missing

### ISSUE THREAD

**Issue by URvesh109** [facebook/react-native#34603]
### Description

**After adding this line in newly created project**
`const bigLiteral = 2n;`

**Unable to archive**

Error: error App.tsx: Unexpected token: name (n) in file App.tsx at 33:22.

Looks like BigInt literal still missing. 

### Version

0.70.0

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1
    Memory: 127.72 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.6.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.13.2 - /usr/local/bin/npm
    Watchman: 2022.08.15.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.0 => 0.70.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. created react-native project
2. Add this line:   const bigLiteral = 2n;
3. Try to archive

### Snack, code example, screenshot, or link to a repository

`const App = () => {
  const isDarkMode = useColorScheme() === 'dark';
  const bigLiteral = 2n;

  const backgroundStyle = {
    backgroundColor: isDarkMode ? Colors.darker : Colors.lighter,
  };

  return (
    <SafeAreaView style={backgroundStyle}>
      <StatusBar
        barStyle={isDarkMode ? 'light-content' : 'dark-content'}
        backgroundColor={backgroundStyle.backgroundColor}
      />
      <ScrollView
        contentInsetAdjustmentBehavior="automatic"
        style={backgroundStyle}>
        <Header />
        <View
          style={{
            backgroundColor: isDarkMode ? Colors.black : Colors.white,
          }}>
          <Section title="Step One">
            Edit <Text style={styles.highlight}>App.tsx</Text> to change this
            screen and then come back to see your edits.
          </Section>
          <Section title="See Your Changes">
            <ReloadInstructions />
          </Section>
          <Section title="Debug">
            <DebugInstructions />
          </Section>
          <Section title="Learn More">
            Read the docs to discover what to do next:
          </Section>
          <LearnMoreLinks />
        </View>
      </ScrollView>
    </SafeAreaView>
  );
};`

**Comment by thalesfp** [comment]
According to this blog post, support for BigInt is ongoing. 

https://reactnative.dev/blog/2022/07/08/hermes-as-the-default#ongoing-work

**Comment by URvesh109** [comment]
Hello @thalesfp

Change Log 0.70 Support BigInt in Hermes, please check this link: https://github.com/facebook/react-native/blob/main/CHANGELOG.md#added

const bI = BigInt(1) it is working
const bigIntLiteral = 1n it is not supported yet
