### ISSUE TITLE
scaleY and scaleX stylesheet properties don't work with RN 0.70.0+ on Android

### ISSUE THREAD

**Issue by retrixe** [facebook/react-native#34607]
### Description

Upon upgrading my app from React Native 0.69.5 to React Native 0.70.0, `scaleY` and `scaleX` are no longer functioning correctly (on Android, untested on iOS).

My app uses `scaleY` to work around https://github.com/facebook/react-native/issues/30034, however this no longer works, and it seems that `scaleY` is not working on any element, even outside a FlatList. I tested `scaleX` as well, and it stopped working as well.

### Version

0.70.0

### Output of `npx react-native info`

```
info Fetching system and libraries information...
System:
    OS: Linux 5.19 Fedora Linux 37 (Workstation Edition Prerelease)
    CPU: (4) x64 Intel(R) Core(TM) i5-4200M CPU @ 2.50GHz
    Memory: 951.54 MB / 7.67 GB
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.15.0 - /usr/local/bin/npm
    Watchman: 20210117.162252.0 - /usr/local/bin/watchman
  SDKs:
    Android SDK:
      API Levels: 31
      Build Tools: 30.0.2, 30.0.3, 31.0.0, 32.0.0
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 17.0.4.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.0 => 0.70.0 
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

- Apply `scaleY` and/or `scaleX` to any element like `Text`, `Pressable` or `FlatList` (the ones I've tested) in your application.
- See that nothing happens on React Native 0.70.0, while older versions work fine.

### Snack, code example, screenshot, or link to a repository

This issue occurs to me in https://github.com/retrixe/EnderChat/blob/main/src/screens/chat/ChatScreen.tsx, but the issue should be reproducible with the following code sample:
```js
import * as React from 'react';
import { Text, FlatList, Platform, StyleSheet } from 'react-native';

export default function App() {
  return (
    <FlatList
      data={['1', '2', '3', '4', '5']}
      style={styles.scaleInvert}
      renderItem={({ item }) => (<Text style={styles.scaleInvert}>{item}</Text>)}
    />
  );
}

const styles = StyleSheet.create({
  scaleInvert: {
    scaleY: -1
  },
});
```
This is intended to reimplement the `inverted` prop using `scaleY`, but it doesn't work under React Native 0.70.0.

**Comment by retrixe** [comment]
It seems this property was removed in #34050 due to being a deprecated property, however, this style property is still being used to work around the preferred `transform: [{ scaleY }]` being massively slower on Android devices.

**Comment by kelset** [comment]
cc @Zachinquarantine who did the PR and @cipolleschi who imported it, who might be able to provide some insights

**Comment by leethree** [comment]
yes I'm seeing the same issue. The workaround for the scrolling performance issue no longer works. `scaleY` should not be removed unless the perf issue #30034 is resolved.

**Comment by retrixe** [comment]
Since #30034 is solved, I think it's safe to close this

**Comment by fabriziobertoglio1987** [comment]
Do you still experience this issue? 

I have four years of experience maintaining facebook/react-native and I specialize in the Text and TextInput components. I currently have 58 [facebook/react-native PRs](https://github.com/facebook/react-native/pulls?q=is%3Apr+author%3Afabriziobertoglio1987+). 

If you still experience this issue, I will prepare a patched release with the fix.

Thanks a lot
