### ISSUE TITLE
[Image] With defaultSource set, it keep showing default image

### ISSUE THREAD

**Issue by zhuzhang** [facebook/react-native#3460]
When render *ImageView* on iOS platform like below :
``` xml
<Image
  source={{uri: "http://example.org/test.jpg"}}
  defaultSource={require('image!placeholder')} />
```
it would keep showing the placeholder all day long....

So I dig source file and find out that it really don't trigger *RCTImageView* to download wanted_image when set frame, related source in file "RCTImageView.m" shows as below:
``` objective-c
- (void)reactSetFrame:(CGRect)frame
{
  [super reactSetFrame:frame];
  if (self.image == nil) {
    _targetSize = frame.size;
    [self reloadImage];
  } else if ([RCTImageView srcNeedsReload:_src]) {
    CGSize imageSize = self.image.size;
    CGSize idealSize = RCTTargetSize(imageSize, self.image.scale, frame.size, RCTScreenScale(), self.contentMode, YES);

    if (RCTShouldReloadImageForSizeChange(imageSize, idealSize)) {
      if (RCTShouldReloadImageForSizeChange(_targetSize, idealSize)) {
        RCTLogInfo(@"[PERF IMAGEVIEW] Reloading image %@ as size %@", _src, NSStringFromCGSize(idealSize));

        // If the existing image or an image being loaded are not the right size, reload the asset in case there is a
        // better size available.
        _targetSize = idealSize;
        [self reloadImage];
      }
    } else {
      // Our existing image is good enough.
      [self cancelImageLoad];
      _targetSize = imageSize;
    }
  }
}
```
The problem is that it *reloadImage* when 
``` objective-c
RCTShouldReloadImageForSizeChange(imageSize, idealSize) &&
RCTShouldReloadImageForSizeChange(_targetSize, idealSize)
```
 and it should be
``` objective-c
RCTShouldReloadImageForSizeChange(_targetSize, idealSize) ||
RCTShouldReloadImageForSizeChange(imageSize, idealSize)
```

This is tested with version '0.13.0-rc', not tested on master yet. but it should have same result because of  the same source code related.

**Comment by zhuzhang** [comment]
Tested on branch master, have the same result as expected.

The key to reproduce it is that the default image size is similar to the ideaSize, i.e.
``` c
RCTShouldReloadImageForSizeChange(imageSize, idealSize) == true
```

Another question about the function *(void)reactSetFrame:(CGRect)frame*: should we set *_targetSize* only after load image successfully and not before it?

**Comment by jspahrsummers** [comment]
The reason this check uses `&&` is to avoid overeager reloading of the image when the current size is already good, or the desired size change is in-flight (which is why we set `_targetSize` before loading).

@javache @nicklockwood I understand why this is a bug, but what's the expected logic for loading `source` over `defaultSource`? Why does it depend on the frame size at all?

**Comment by nicklockwood** [comment]
It sounds like the issue is that it's not triggering a load of the *source* image if the *defaultSource* image is already the correct size to fill the view frame.

In other words, the logic that is used to prevent reloading of the source image if the frame size hasn't changed is wrongly being used to prevent the source image *ever* loading if the defaultSource already meets the size criteria.

But of course we should always load the source image in preference to the defaultSource.

**Comment by jspahrsummers** [comment]
Sorry, what I meant is: this is all happening in response to `-reactSetFrame:`. Shouldn't the loading of `source` over `defaultSource` be initiated automatically, without having anything to do with frame setting?

**Comment by nicklockwood** [comment]
OIC. Yes, it should.

**Comment by zhuzhang** [comment]
@jspahrsummers but what if we set image failed when reload image? then ```_targetSize``` would never change again, which won't trigger a reload of the source image. or should we reset ```_targetSize``` when load source image failed?

**Comment by jspahrsummers** [comment]
We should indeed reset `_targetSize` if loading fails. That needs to be fixed.

**Comment by zhuzhang** [comment]
@jspahrsummers, Will there be another commit to fix the ```_targetSize``` logic?

**Comment by jspahrsummers** [comment]
Yes, at some point, but we're going to discuss how `RCTImageView` handles errors more generally, since there are other things that need to be addressed too (like overwriting `self.image` on failure).
