### ISSUE TITLE
RN 0.70.0 ViewPropTypes & AppRegistry issue

### ISSUE THREAD

**Issue by hicath** [facebook/react-native#34611]
### Description

I upgraded my react-native project from `~0.67.1` to `0.70.0`, I followed all the guidance here: https://react-native-community.github.io/upgrade-helper/?from=0.67.1&to=0.70.0. 

After the upgrade process, error start showing up saying some errors below:
<img width="1014" alt="Screen Shot 2022-09-06 at 21 13 00" src="https://user-images.githubusercontent.com/86655213/188657941-ccf44766-6762-47c7-8b17-33204d4b9be5.png">

### Version

0.70.0

### Output of `npx react-native info`

System:
    OS: macOS 12.2.1
    CPU: (8) arm64 Apple M1
    Memory: 1.15 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.14.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.0 => 0.70.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

- Upgrade react native version to `0.70.0`
- Removed node_modules directory and `Pods` directory to get clean package installation
- Execute `yarn install` and `pod install` 
- Run the metro by using `yarn run start` 
- Run ios by `yarn ios`

The build works perfectly fine, but then when the emulator shows up, it stuck on the Splash Screen and console log shows the error like the attached file above.

### Snack, code example, screenshot, or link to a repository

Already provided above.

**Comment by rranjan14** [comment]
Same issue happening with me as well for android and haven't tried for iOS. I upgraded from 0.67.4 to 0.70.0. Tried the solution mentioned in [#32453](https://github.com/facebook/react-native/issues/32453#issuecomment-1065329455). Didn't help much.

**Comment by allemanfredi** [comment]
@hicath Try this

```diff
diff --git a/node_modules/react-native/index.js b/node_modules/react-native/index.js
index d59ba34..349b4dd 100644
--- a/node_modules/react-native/index.js
+++ b/node_modules/react-native/index.js
@@ -435,32 +435,16 @@ module.exports = {
   },
   // Deprecated Prop Types
   get ColorPropType(): $FlowFixMe {
-    invariant(
-      false,
-      'ColorPropType has been removed from React Native. Migrate to ' +
-        "ColorPropType exported from 'deprecated-react-native-prop-types'.",
-    );
+    return require('deprecated-react-native-prop-types').ColorPropType
   },
   get EdgeInsetsPropType(): $FlowFixMe {
-    invariant(
-      false,
-      'EdgeInsetsPropType has been removed from React Native. Migrate to ' +
-        "EdgeInsetsPropType exported from 'deprecated-react-native-prop-types'.",
-    );
+    return require('deprecated-react-native-prop-types').EdgeInsetsPropType
   },
   get PointPropType(): $FlowFixMe {
-    invariant(
-      false,
-      'PointPropType has been removed from React Native. Migrate to ' +
-        "PointPropType exported from 'deprecated-react-native-prop-types'.",
-    );
+    return require('deprecated-react-native-prop-types').PointPropType
   },
   get ViewPropTypes(): $FlowFixMe {
-    invariant(
-      false,
-      'ViewPropTypes has been removed from React Native. Migrate to ' +
-        "ViewPropTypes exported from 'deprecated-react-native-prop-types'.",
-    );
+    return require('deprecated-react-native-prop-types').ViewPropTypes
   },
 };
```

**Comment by allemanfredi** [comment]
@hicath Try this:

```diff
diff --git a/node_modules/react-native/index.js b/node_modules/react-native/index.js
index d59ba34..349b4dd 100644
--- a/node_modules/react-native/index.js
+++ b/node_modules/react-native/index.js
@@ -435,32 +435,16 @@ module.exports = {
   },
   // Deprecated Prop Types
   get ColorPropType(): $FlowFixMe {
-    invariant(
-      false,
-      'ColorPropType has been removed from React Native. Migrate to ' +
-        "ColorPropType exported from 'deprecated-react-native-prop-types'.",
-    );
+    return require('deprecated-react-native-prop-types').ColorPropType
   },
   get EdgeInsetsPropType(): $FlowFixMe {
-    invariant(
-      false,
-      'EdgeInsetsPropType has been removed from React Native. Migrate to ' +
-        "EdgeInsetsPropType exported from 'deprecated-react-native-prop-types'.",
-    );
+    return require('deprecated-react-native-prop-types').EdgeInsetsPropType
   },
   get PointPropType(): $FlowFixMe {
-    invariant(
-      false,
-      'PointPropType has been removed from React Native. Migrate to ' +
-        "PointPropType exported from 'deprecated-react-native-prop-types'.",
-    );
+    return require('deprecated-react-native-prop-types').PointPropType
   },
   get ViewPropTypes(): $FlowFixMe {
-    invariant(
-      false,
-      'ViewPropTypes has been removed from React Native. Migrate to ' +
-        "ViewPropTypes exported from 'deprecated-react-native-prop-types'.",
-    );
+    return require('deprecated-react-native-prop-types').ViewPropTypes
   },
 };
 ```

**Comment by hicath** [comment]
> @hicath Try this:
> 
> ```diff
> diff --git a/node_modules/react-native/index.js b/node_modules/react-native/index.js
> index d59ba34..349b4dd 100644
> --- a/node_modules/react-native/index.js
> +++ b/node_modules/react-native/index.js
> @@ -435,32 +435,16 @@ module.exports = {
>    },
>    // Deprecated Prop Types
>    get ColorPropType(): $FlowFixMe {
> -    invariant(
> -      false,
> -      'ColorPropType has been removed from React Native. Migrate to ' +
> -        "ColorPropType exported from 'deprecated-react-native-prop-types'.",
> -    );
> +    return require('deprecated-react-native-prop-types').ColorPropType
>    },
>    get EdgeInsetsPropType(): $FlowFixMe {
> -    invariant(
> -      false,
> -      'EdgeInsetsPropType has been removed from React Native. Migrate to ' +
> -        "EdgeInsetsPropType exported from 'deprecated-react-native-prop-types'.",
> -    );
> +    return require('deprecated-react-native-prop-types').EdgeInsetsPropType
>    },
>    get PointPropType(): $FlowFixMe {
> -    invariant(
> -      false,
> -      'PointPropType has been removed from React Native. Migrate to ' +
> -        "PointPropType exported from 'deprecated-react-native-prop-types'.",
> -    );
> +    return require('deprecated-react-native-prop-types').PointPropType
>    },
>    get ViewPropTypes(): $FlowFixMe {
> -    invariant(
> -      false,
> -      'ViewPropTypes has been removed from React Native. Migrate to ' +
> -        "ViewPropTypes exported from 'deprecated-react-native-prop-types'.",
> -    );
> +    return require('deprecated-react-native-prop-types').ViewPropTypes
>    },
>  };
> ```

Yep I saw that on React documentation, but I don't think we should modify any node_modules file manually.. is there any way to get the RN version that's coming with this update? I don't understand why React deprecated it too soon and it's not coming with proper import.

**Comment by hicath** [comment]
> Same issue happening with me as well for android and haven't tried for iOS. I upgraded from 0.67.4 to 0.70.0. Tried the solution mentioned in [#32453](https://github.com/facebook/react-native/issues/32453#issuecomment-1065329455). Didn't help much.

Which issue? `ViewPropTypes` or `AppRegistry` ? I posted 2 issues above.. I just need to make sure what's happening on your end after the upgrade.

**Comment by rranjan14** [comment]
> > Same issue happening with me as well for android and haven't tried for iOS. I upgraded from 0.67.4 to 0.70.0. Tried the solution mentioned in [#32453](https://github.com/facebook/react-native/issues/32453#issuecomment-1065329455). Didn't help much.
> 
> Which issue? `ViewPropTypes` or `AppRegistry` ? I posted 2 issues above.. I just need to make sure what's happening on your end after the upgrade. @rranjan14

Luckily, both the issues got solved with the solution mentioned by @hicath .

**Comment by rranjan14** [comment]
> @hicath Try this:
> 
> ```diff
> diff --git a/node_modules/react-native/index.js b/node_modules/react-native/index.js
> index d59ba34..349b4dd 100644
> --- a/node_modules/react-native/index.js
> +++ b/node_modules/react-native/index.js
> @@ -435,32 +435,16 @@ module.exports = {
>    },
>    // Deprecated Prop Types
>    get ColorPropType(): $FlowFixMe {
> -    invariant(
> -      false,
> -      'ColorPropType has been removed from React Native. Migrate to ' +
> -        "ColorPropType exported from 'deprecated-react-native-prop-types'.",
> -    );
> +    return require('deprecated-react-native-prop-types').ColorPropType
>    },
>    get EdgeInsetsPropType(): $FlowFixMe {
> -    invariant(
> -      false,
> -      'EdgeInsetsPropType has been removed from React Native. Migrate to ' +
> -        "EdgeInsetsPropType exported from 'deprecated-react-native-prop-types'.",
> -    );
> +    return require('deprecated-react-native-prop-types').EdgeInsetsPropType
>    },
>    get PointPropType(): $FlowFixMe {
> -    invariant(
> -      false,
> -      'PointPropType has been removed from React Native. Migrate to ' +
> -        "PointPropType exported from 'deprecated-react-native-prop-types'.",
> -    );
> +    return require('deprecated-react-native-prop-types').PointPropType
>    },
>    get ViewPropTypes(): $FlowFixMe {
> -    invariant(
> -      false,
> -      'ViewPropTypes has been removed from React Native. Migrate to ' +
> -        "ViewPropTypes exported from 'deprecated-react-native-prop-types'.",
> -    );
> +    return require('deprecated-react-native-prop-types').ViewPropTypes
>    },
>  };
> ```

Works perfectly for me.

**Comment by hicath** [comment]
Unfortunately it doesn't work for me here @allemanfredi @rranjan14 😢 
Also I don't think updating the node_modules manually is a proper way to fix this.

**Comment by rranjan14** [comment]
You can use [patch-package](https://www.npmjs.com/package/patch-package) to make and keep your patch.

**Comment by hicath** [comment]
@rranjan14 Yes I'm aware we can use `patch-package`, but beside that, the solution above also don't work for me here and I still can see the AppRegistry issue, so I don't think I need to use patch-package atm..

**Comment by allemanfredi** [comment]
It happened also to me but the error was different after having applied the patch

**Comment by hicath** [comment]
Good news, it finally works for me. I implemented the patch and upgraded some used dependencies that has some updates related to latest RN adjustments

**Comment by rranjan14** [comment]
> It happened also to me but the error was different after having applied the patch

Was it related to JS bundling or something different? Also, double check the steps to upgrade. You might have missed something.

**Comment by rickhanlonii** [comment]
## Recommend Fix

Hey all, sorry for the experience here. The recommended fix is to replace the usage of prop types with `deprecated-react-native-prop-types`, and/or move to typescript. More info here: https://github.com/facebook/react-native/issues/33734#issuecomment-1212215459
