### ISSUE TITLE
App is crashing in iOS emulator with release react-native version 0.70.0

### ISSUE THREAD

**Issue by jasonohdz1501** [facebook/react-native#34612]
### The app is not running in emulator iOS after new release to version react-native 0.70.0

Yesterday, I was trying to create a new project through `npx react-native init <project_name> --template react-native-template-typescript` and when I build the application with `npx react-native run-ios` the app installed at emulator but when I try to open it, it crash and send a notification that the application has been closed. 

Then I did a new app but defined the version `react-native init <project_name> --template react-native-template-typescript@6.11.9` and everything is working fine. 

In Android, I don't have the issue. It's just for iOS.

### Version

0.70.0

### Output of `npx react-native info`

System:
    OS: macOS 12.5.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 471.18 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.0.0 - ~/.nvm/versions/node/v18.0.0/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.9.0 - ~/.nvm/versions/node/v18.0.0/bin/npm
    Watchman: 2022.09.05.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.2 - /Users/<user>/.asdf/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8815526
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.2 - /Users/<user>/.sdkman/candidates/java/current/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.5 => 0.69.5 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. Create a new App using `npx react-native init <project_name> --template react-native-template-typescript`
2. cd <new_folder_app>
3. Init app using `npx react-native run-ios`
4. App crashes on iOS emulator. 

### Snack, code example, screenshot, or link to a repository

none

**Comment by rranjan14** [comment]
I am facing this issue for android as well. I upgraded from 0.67.4 to 0.70.0.

**Comment by Bayramito** [comment]
If you disable the hermes module on Podfile its working... but its not working on me too when its enabled idk why

**Comment by Adnan-Bacic** [comment]
mine still instantly crashes on ios on a new project even with hermes disabled

**Comment by Bayramito** [comment]
> mine still instantly crashes on ios on a new project even with hermes disabled

you have to run pod install again once disabled iy

**Comment by kelset** [comment]
I just tested your repro steps and it works fine on my machine:

<img width="954" alt="Screenshot 2022-09-12 at 12 02 45" src="https://user-images.githubusercontent.com/16104054/189637849-6652189a-adb4-48e2-bf64-f2b3b2f23bc8.png">

I didn't touch any configs, it worked out of the box.
My configuration:

```

System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 22.75 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.1 - /opt/homebrew/bin/npm
    Watchman: 2022.08.15.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/lsciandra/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 31, 32, 33
      Build Tools: 30.0.2, 30.0.3, 31.0.0, 33.0.0
      System Images: android-31 | Android TV ARM 64 v8a, android-31 | Google TV ARM 64 v8a, android-31 | Google APIs ARM 64 v8a, android-31 | Google Play ARM 64 v8a, android-33 | Google APIs ARM 64 v8a
      Android NDK: 24.0.8215888
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16 - /Users/lsciandra/.sdkman/candidates/java/current/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.0 => 0.70.0
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

so it's likely that there's something that needs to be updated on your machine (maybe thing that pops out to me is the cocoapods version)

**Comment by Allenkardic** [comment]
I am still having this issues are there any solutions for this yet

**Comment by Adnan-Bacic** [comment]
i updated from 0.70.0 to 0.70.6 and it works for me now

**Comment by kopax-polyconseil** [comment]
I have the same issue, in GitHub action macos-12.

We also use `bundle` , `bundle install`, `cd ios && bundle exec pod install`, we also use `ruby 2.7.5` , nothing we tried work. React Native 0.68.5, any clue how we can do ?
