### ISSUE TITLE
Open Debugger in iOS simulator not working in RN 0.70.0

### ISSUE THREAD

**Issue by rstor1** [facebook/react-native#34615]
### Description

I started the basic AwesomeProject from the getting started in the docs and found that the Open Debugger is not working. Actually, I am unable to debug in multiple ways (safari, standalone devtools, launch.json from React Native Tools in vscode). Is this a known issue? It was working with 0.69:

### Version

0.70.0

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 12.5.1
    CPU: (4) x64 Intel(R) Core(TM) i5-6287U CPU @ 3.10GHz
    Memory: 602.00 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.13.2/bin/yarn
    npm: 8.18.0 - ~/.nvm/versions/node/v16.13.2/bin/npm
    Watchman: 2022.08.29.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.0 => 0.70.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

In terminal run: npx react-native init AwesomeProject

In terminal run: npx react-native start

In vscode run: npx react-native run-ios

Once ios simulator(iPhone 13, ios 15.5) opens do CMD + D on the simulator to open the menu.

Click Open Debugger 

### Snack, code example, screenshot, or link to a repository

<img width="1300" alt="Screen Shot 2022-09-06 at 6 06 16 PM" src="https://user-images.githubusercontent.com/43070937/188750204-90e6c9e0-f94a-4604-99d0-d578957acaa5.png">

**Comment by Bayramito** [comment]
quick question do you ran it with hermes enabled on Podfile ?

**Comment by rstor1** [comment]
> quick question do you ran it with hermes enabled on Podfile ?

Podfile shows:
`:hermes_enabled => true`

**Comment by cuongvoong** [comment]
Got the same error after I just created a new project.  Setting `:hermes_enabled => false` resolves the problem.  I disabled Flipper as well, not sure if that had any effect.

**Comment by Bayramito** [comment]
> Got the same error after I just created a new project. Setting `:hermes_enabled => false` resolves the problem. I disabled Flipper as well, not sure if that had any effect.

This approacb may cause to not use all benefits of the new architecture

**Comment by justin-tay** [comment]
The approaches of debugging you have tried are likely for the JavaScriptCore engine and not the Hermes engine which is the default in 0.70.0. Hermes directly implements the Chrome inspector protocol.

See [Debugging JS on Hermes using Google Chrome's DevTools](https://reactnative.dev/docs/hermes#debugging-js-on-hermes-using-google-chromes-devtools) for debugging on Hermes.

For VSCode you should use the `Debug iOS Hermes - Experimental` launch configuration and not the `Debug iOS` launch configuration.

**Comment by rstor1** [comment]
> The approaches of debugging you have tried are likely for the JavaScriptCore engine and not the Hermes engine which is the default in 0.70.0. Hermes directly implements the Chrome inspector protocol.
> 
> See [Debugging JS on Hermes using Google Chrome's DevTools](https://reactnative.dev/docs/hermes#debugging-js-on-hermes-using-google-chromes-devtools) for debugging on Hermes.
> 
> For VSCode you should use the `Debug iOS Hermes - Experimental` launch configuration and not the `Debug iOS` launch configuration.

I did try both of those but it does not work for me. Following the link about debugging JS on Hermes using Google Chromes Devtools does not show the JS code to set breakpoints. I tried adding the folders to the Files tab in the tools but still nothing. As for the **Debug iOS Hermes - Experimental** launch config option here is what I get:

<img width="940" alt="Screen Shot 2022-09-07 at 7 34 35 AM" src="https://user-images.githubusercontent.com/43070937/188869270-8970185b-97f7-49fa-982f-95b88c474524.png">

**Comment by rstor1** [comment]
I can confirm that when creating an app with RN 0.69.0 it works as expected. CMD+D opens menu, click on Debug with Chrome opens up the debugger and there is no error in metro terminal.
<img width="1214" alt="Screen Shot 2022-09-07 at 12 38 55 PM" src="https://user-images.githubusercontent.com/43070937/188933312-f0d96f63-e981-46d9-851f-84dd6d020fc8.png">

**Comment by cuongvoong** [comment]
The issue with findXcodeProject is due to the VS Code react-native plugin needing an update.  A temp solution can be found here https://github.com/microsoft/vscode-react-native/issues/1781#issuecomment-1195610125

**Comment by panpan31415** [comment]
> The issue with findXcodeProject is due to the VS Code react-native plugin needing an update to fix the path. A temp solution can be found here [microsoft/vscode-react-native#1781 (comment)](https://github.com/microsoft/vscode-react-native/issues/1781#issuecomment-1195610125)

I tried as well, didn't work for me

**Comment by Siliconvelly** [comment]
I am also facing this issue. So, please fix this issue as soon as possible.

**Comment by Siliconvelly** [comment]
I think :hermes_enabled => true, making it false like :hermes_enabled => false, is working and i am able to debug with ios. but i want to know if i disable hermes then it can make any issue or problem in our development?

**Comment by KokoTa** [comment]
@Siliconvelly I have the same problem, i want to use hermes, but i can't debugger by phone

**Comment by maxmandia** [comment]
experiencing the same issue. My project has flipper disabled fyi

**Comment by Bayramito** [comment]
Try #34608

**Comment by Frit** [comment]
Same issue on RN 0.70.0.
Confirm that RN 0.69.0 works fine.

**Comment by maxmandia** [comment]
> Same issue on RN 0.70.0. Confirm that RN 0.69.0 works fine.

I just switched to expo...

**Comment by Frit** [comment]
> > Same issue on RN 0.70.0. Confirm that RN 0.69.0 works fine.
> 
> I just switched to expo...

It appears I have no other choice :)

**Comment by MahmoudAziz1996** [comment]
> Got the same error after I just created a new project. Setting `:hermes_enabled => false` resolves the problem. I disabled Flipper as well, not sure if that had any effect.

This works for me - thanks

**Comment by kelset** [comment]
A few things going on here:
1. the error (and you can see it in the screenshot too) is because clicking on "open debugger" triggers a command to connect to the [Flipper desktop app](https://fbflipper.com/): `info Opening flipper://null/Hermesdebuggerrn?device=React%20Native...` Because you don't have Flipper running, it tries to open it and fails with `error Browser exited with error:, Error: invalid url, missing http/https protocol
`
2. this is related to the fact that Hermes is on by default starting from 0.70.
3. as mentioned by @justin-tay, with Hermes you can not use the the "old way" of debugging via Chrome directly in browser.

All of that said:
* for some reason on my machine cmd+D didn't open the debugging menu, nor did pressing "d" in Metro. This is something that needs to be fixed.
* the overall debugging story for react-native at the moment is a bit weak, but we are trying to get a few engineers from our companies to focus on this a bit more to improve the situation.

For now, using Flipper as debugging tool is the solution you should go for.

**Comment by HoaiHuynh** [comment]
@kelset in the future is there a way to debug via Chrome?

**Comment by Mihai-github** [comment]
Hi, I can confirm that using:
`
"react": "18.1.0",
"react-native": "0.70.0",
`
and 
`
:hermes_enabled => true,
`
using for example google chrome to debug your code etc is not working, but white same configuration and hermes_enabled => false is working.

Maybe someone knows if there is a way to still use a browser to debug your app but with hermed_enabled => true?

**Comment by HaykZiphycare** [comment]
Hello everyone.
I'm also waiting for a fix and looking for a solution. I suggest using this before debugging is fixed.

https://github.com/infinitered/reactotron

**Comment by Hayk-Zohrabyan** [comment]
Hello everyone.
I'm also waiting for a fix and looking for a solution. I suggest using this before debugging is fixed.

https://github.com/infinitered/reactotron

**Comment by jyotiprakash111** [comment]
For me I have typed manually http://localhost:8081 then the debug console opened on chrome. #Hope This helps

**Comment by Azaz0723** [comment]
it does works on changing Hermes engine in pod file to false 
:hermes_enabled => true, 
If not working after this run pod install and build you project again. This worked for me

**Comment by mattbfb** [comment]
@HoaiHuynh there is currently a bug preventing the loading of source maps in that case. We are currently working on a fix.

In the meantime, the primary way to debug JavaScript running in Hermes is via [Flipper](https://fbflipper.com/).

**Comment by skurgansky-sugarcrm** [comment]
Flipper doesn't work well either

**Comment by mattbfb** [comment]
@skurgansky-sugarcrm can you share more details about your environment, the steps you've attempted, and any errors you receive?

Launching a new app via
`npx react-native init DebugProject && cd "./DebugProject" && npx react-native run-android`
and then opening the "Hermes Debugger (RN)" in Flipper should still work in RN 0.70 (e.g. you can press the pause button, then scroll the app to trigger a break. confirmed locally). Does this fail for you?

**Comment by skurgansky-sugarcrm** [comment]
@mattbfb 
i have node 18 if it matters
npx react-native init DebugProject && cd "./DebugProject" && npx react-native run-ios
Flipper is of latest version
just running template project on ios i go Cmd+D > Open Debugger > console logs

```
info Opening flipper://null/Hermesdebuggerrn?device=React%20Native...
error Browser exited with error:, Error: invalid url, missing http/https protocol
```
then i try to open Flipper manually because it's not started via upper steps
![image](https://user-images.githubusercontent.com/14196384/193038340-fbf4a5f6-9e31-43af-b406-5a18bc80796b.png)
1) File system panel is empty though Cmd+O can see project files
2) Breakpoints do not work at all (debugger statement helps a little here)

**Comment by mattbfb** [comment]
@skurgansky-sugarcrm Thanks for sharing those details.

The filesystem view is currently not populated by the Hermes debugger, but you can find an "Open file" menu item in the collapsed items under the vertical "..." to the right of the "Filesystem" and "Snippets" tab in your screenshot.

e.g. in the `DebugProject` that you created above, if you add some code to `App.js` and then open that file in the "Hermes Debugger (RN)", you should be able to set and reach a breakpoint e.g.:
<img width="506" alt="Screen Shot 2022-09-29 at 3 46 46 PM" src="https://user-images.githubusercontent.com/111091151/193128343-5c2df903-9db4-4e67-99bd-edaf2acd2a7c.png">

**Comment by skurgansky-sugarcrm** [comment]
@mattbfb i should be able to set breakpoint but i just can't. =( 

debugger in Flipper (Version 0.166.0 (50.0.0), RN 0.70.1) just does not want to:
1) pause where i clicked to create a breakpoint like if source maps were not correct
2) remove them when i try (Remove breakpoint or Remove all breakpoints )

**Comment by mattbfb** [comment]
@skurgansky-sugarcrm can you share more about the exact steps you're trying? Are you referring to putting the same code snippet (`setInterval(() => { const a = 1; const b = 2; const c = a + b; console.log(c); }, 1000);`) in the same file (`App.js` in the newly-created project), or are you trying a different scenario?

**Comment by skurgansky-sugarcrm** [comment]
![image](https://user-images.githubusercontent.com/14196384/193271605-ffdb243e-5f7e-4b6c-be81-7db3c8f442bb.png)
@mattbfb i use template project
running it right after it's installed and built. When i open Flipper i try to set breakpoint on line 61 on my screenshot
![image](https://user-images.githubusercontent.com/14196384/193272455-50e7d732-c63f-4ebe-9f06-69c46ce0d102.png)

flipper behaves itself strangely. when i reload app, breakpoint doesn't work and i can't remove it
if i write debugger in code. it works fine

**Comment by mattbfb** [comment]
@skurgansky-sugarcrm I'm not certain with when that `useEffect()` code will be invoked. Is it only breakpoints during startup that are missed, or can you not reach _any_ breakpoints, even ones that execute well after the debugger is attached?

**Comment by skurgansky-sugarcrm** [comment]
@mattbfb looks like i can pause in some onPress handler though breakpoint is not visible on line label position.
with the useEffect above. when i set a breakpoint inside of it and try to reload  the app, it didn't work for me

**Comment by HaykZiphycare** [comment]
Is this issue still unresolved?

**Comment by H4mxa** [comment]
It does work after changing from `:hermes_enabled => true` to `:hermes_enabled => false`, but why??

**Comment by RSchneider94** [comment]
> A few things going on here:
> 
> 1. the error (and you can see it in the screenshot too) is because clicking on "open debugger" triggers a command to connect to the [Flipper desktop app](https://fbflipper.com/): `info Opening flipper://null/Hermesdebuggerrn?device=React%20Native...` Because you don't have Flipper running, it tries to open it and fails with `error Browser exited with error:, Error: invalid url, missing http/https protocol `
> 2. this is related to the fact that Hermes is on by default starting from 0.70.
> 3. as mentioned by @justin-tay, with Hermes you can not use the the "old way" of debugging via Chrome directly in browser.
> 
> All of that said:
> 
> * for some reason on my machine cmd+D didn't open the debugging menu, nor did pressing "d" in Metro. This is something that needs to be fixed.
> * the overall debugging story for react-native at the moment is a bit weak, but we are trying to get a few engineers from our companies to focus on this a bit more to improve the situation.
> 
> For now, using Flipper as debugging tool is the solution you should go for.

hmmm, but if it's necessary to use `use_frameworks!` inside of the project, it's necessary to disable Flipper, any solution then? thanks!

**Comment by skurgansky-sugarcrm** [comment]
> It does work after changing from `:hermes_enabled => true` to `:hermes_enabled => false`, but why??

because Hermes can't use source maps now. it's fixed in 0.71 version. checkout that change log for RC of RN

**Comment by JeffGuKang** [comment]
You can use browser debugger temporarily.
1. Open the http://localhost:8081/debugger-ui/
2. Reload simulator

**Comment by caolong0204** [comment]
> 
i couldn't open flipper to debug

**Comment by Jonathan0wh** [comment]
Is there any possibility we can get [React Native Debugger](https://github.com/jhen0409/react-native-debugger) working with Hermes engine?

**Comment by skurgansky-sugarcrm** [comment]
> Is there any possibility we can get [React Native Debugger](https://github.com/jhen0409/react-native-debugger) working with Hermes engine?

use RN 0.71 RC version. Hermes should be fixed there. Or you can search older version which is not broken.

**Comment by emanueljcc** [comment]
react-native-debugger It doesn't work, it gives the flipper error.  When will version 0.71 stable come out?

**Comment by akkadaya** [comment]
Wonder if this is helpful for you  
https://reactnative.dev/docs/next/hermes#debugging-js-on-hermes-using-google-chromes-devtools

**Comment by Fredmensah** [comment]
Flipper is still working in the background, iOS is just not able to start the command to run the debugger. Disabling :hermes_enabled => false is not the ideal solution as it limits the use of the new features of 0.70. You can still access debugger-ui from [(http://localhost:8081/debugger-ui/)] till a fix is posted on this.

**Comment by OrestGeniusee** [comment]
follow this documentation from react-native https://reactnative.dev/docs/hermes to be able to debug your RN app where Hermes is used

**Comment by AbbasTheReckoner** [comment]
> It does work after changing from `:hermes_enabled => true` to `:hermes_enabled => false`, but why??

because you need to do  cd ios && pod install && cd ..  and then run "npx react-native run-ios"

**Comment by jaexplorer** [comment]
Any update? I'd like to use React Native Debugger

**Comment by caiodeambrosio** [comment]
Same here

**Comment by caiodeambrosio** [comment]
Same here, temporarily disable hermes ":hermes_enabled => false" works for me.

steps: 
- in the Podfile set ":hermes_enabled => false" 
- cd ios && rm -rf Pods Podfile.lock
- pod install --repo-update
- build ios

**Comment by skurgansky-sugarcrm** [comment]
you can't debug hermes app on React Native Debugger at all. It's possible only on flipper, chrome inspect or  React Native plugin for VSCode. Which i prefer for now because its support of source maps is better. Redux devtool is also available and can connect remotely. Check @redux-devtools/remote and [my issue for hermes app](https://github.com/reduxjs/redux-devtools/issues/1382). Network is visible in vscode plugin RN Devtools: Network inspector.

So you 2 option to debug
1) old non hermes app with React Native Debugger, chrome inspect or  React Native plugin for VSCode.
2) Flipper, chrome inspect or  React Native plugin for VSCode.

**Comment by gusgard** [comment]
I created a package to solve this issue

```js
yarn add react-native-devsettings
```
```js
import 'react-native-devsettings';
```

basically, it is doing `NativeModules.DevSettings.setIsDebuggingRemotely(true);`
https://www.npmjs.com/package/react-native-devsettings?activeTab=readme

**Comment by jaexplorer** [comment]
@gusgard trying now

**Comment by jaexplorer** [comment]
@gusgard Omg I love you this works.

**Comment by Barney4242** [comment]
> I created a package to solve this issue
> 
> ```js
> yarn add react-native-devsettings
> ```
> 
> ```js
> import 'react-native-devsettings';
> ```
> 
> basically, it is doing `NativeModules.DevSettings.setIsDebuggingRemotely(true);` https://www.npmjs.com/package/react-native-devsettings?activeTab=readme

It works now!

**Comment by sahilbakoru** [comment]
> hermes

Thank you it worked.

**Comment by ucheNkadiCode** [comment]
If you're on React Native 0.71 and using react-native-splash-screens, making your AppDelegate.mm like so 

```
@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [FIRApp configure]; // If you're using react-native firebase

  self.moduleName = @"main";
  // You can add your custom initial props in the dictionary below.
  // They will be passed down to the ViewController used by React Native.
  self.initialProps = @{};

  bool didFinish = [super application:application didFinishLaunchingWithOptions:launchOptions];
   
   [RNSplashScreen show];  // this needs to be called after [super application:application didFinishLaunchingWithOptions:launchOptions];
   
   return didFinish;
}
```

for android it's 

```
  @Override
  protected void onCreate(Bundle savedInstanceState) {
    SplashScreen.show(this);
    super.onCreate(savedInstanceState);
  }
```

**Comment by aravi365** [comment]
> https://www.npmjs.com/package/react-native-devsettings?activeTab=readme

Not able to use it on my project on latest RN with JS
https://github.com/gusgard/react-native-devsettings/issues/3

**Comment by SundaramSrivastava** [comment]
For React native verison 0.70.x use [https://fbflipper.com/](https://fbflipper.com/) for debugging.

```
info Opening flipper://null/Hermesdebuggerrn?device=React%20Native...
error Browser exited with error:, Error: invalid url, missing http/https protocol
```

In version 0.70.x metro is trying to reach the above URL which opens flipper debugging tool.

**Comment by marlti7** [comment]
use flipper

**Comment by vocoWone** [comment]
Set: `hermes_enabled => false`

Install pods: `cd ios && pod install && cd ..`

Build App: `npx react-native run-ios`

**Comment by HosamCS** [comment]
1-Navigate to chrome://inspect in a Chrome browser instance.

2- Use the Configure... button to add the Metro server address (typically localhost:8081 as described above).
3-You should now see a "Hermes React Native" target with an "inspect" link which can be used to bring up debugger. If you don't see the "inspect" link, make sure the Metro server is running.
see the docs 
[https://reactnative.dev/docs/hermes#debugging-js-on-hermes-using-google-chromes-devtools](url)

**Comment by jay-omio** [comment]
Debugger is working fine on Simulator with `hermes_enabled => true` , unfortunately it's not working when I run on physical device.

App on physical device is loading rn bundle from metro server hosted on computer within same network, somehow debugger is just not working.

Hermes React Native -> inspect link is visible, which on clicking displays empty source tab.
There is following error in console 

`Failed to fetch source map http://192.168.1.9:8081/index.map?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.goeuro.ios.ronald.dev: remote fetches not permitted`

Am I missing something?

**Comment by Dror-Bar** [comment]
> Hey, using React Native Debugger as well (on 0.70.6).
> 
> Preface: Not an RN contributor/expert.
> 
> Digging into this a bit more it seems the Dev Settings menu will default to trying to use Flipper if `devSettings.isDeviceDebuggingAvailable` is `true`. See:
> 
> https://github.com/facebook/react-native/blob/7620509b89e8205a6521b70d2942bca4012db6d2/React/CoreModules/RCTDevMenu.mm#L262
> 
> If you want a quick fix, we've had success with patching the dev menu to offer both Flipper and remote debugging, but it's a bit jank. Maybe someone from the core team can comment on why Device debugging being available removes the option to debug remotely?
> 
> ```
> diff --git a/node_modules/react-native/React/CoreModules/RCTDevMenu.mm b/node_modules/react-native/React/CoreModules/RCTDevMenu.mm
> index 83ddd83..e88afd3 100644
> --- a/node_modules/react-native/React/CoreModules/RCTDevMenu.mm
> +++ b/node_modules/react-native/React/CoreModules/RCTDevMenu.mm
> @@ -284,10 +284,9 @@ - (void)setDefaultJSBundle
>                                      withBundleURL:bundleManager.bundleURL
>                                   withErrorMessage:@"Failed to open Flipper. Please check that Metro is runnning."];
>                             }]];
> -    } else if (devSettings.isRemoteDebuggingAvailable) {
> -#else
> -    if (devSettings.isRemoteDebuggingAvailable) {
> +    }
>  #endif
> +    if (devSettings.isRemoteDebuggingAvailable) {
>        // For remote debugging, we open up Chrome running the app in a web worker.
>        // Note that this requires async communication, which will not work for Turbo Modules.
>        [items addObject:[RCTDevMenuItem
> ```
> 
> As for why switching from `hermes` to `jsc` works. I believe it's because `isDeviceDebuggingAvailable` is derived from a flag that `jsc` sets to false, but `hermes` sets to true (when built for debugging).

This did not work for me with react-native 0.72.3

**Comment by nchrisr** [comment]
React-Native newbie here. Not sure what Hermes or Flipper are, and also is there a fix that is ideal and works? or is it best to just revert to an oder version of React Native?

**Comment by Dror-Bar** [comment]
> React-Native newbie here. Not sure what Hermes or Flipper are, and also is there a fix that is ideal and works? or is it best to just revert to an oder version of React Native?

You don't really want to revert to an older version of React-Native. You gain a lot from newer versions and with older versions you might have some issues when uploading to google play store (they require target API 33 now).

I haven't tested the flipper debugger yet, but that might be a tool that could help. You might want to disable hermes for now and re-enable it before uploading.

**Comment by ReactNative06** [comment]
You can check the answer on this video https://www.youtube.com/watch?v=XCmmc7G5eXw

**Comment by ZoHayk** [comment]
@ReactNative06 Without shutting down Hermes. This has long been clear.

**Comment by henninghall** [comment]
> basically, it is doing `NativeModules.DevSettings.setIsDebuggingRemotely(true);`

Iterated on this 👆, to add it in the dev menu:
```ts
if (__DEV__) {
  DevSettings.addMenuItem('Debugging plz', () => {
    NativeModules.DevSettings.setIsDebuggingRemotely(true);
  });
}
```
<img width="276" alt="Screenshot 2023-09-22 at 11 09 21" src="https://github.com/facebook/react-native/assets/1652607/db20c02e-ce9c-4335-9208-5b464b266081">

**Comment by focux** [comment]
> 1-Navigate to chrome://inspect in a Chrome browser instance.
> 
> 2- Use the Configure... button to add the Metro server address (typically localhost:8081 as described above). 3-You should now see a "Hermes React Native" target with an "inspect" link which can be used to bring up debugger. If you don't see the "inspect" link, make sure the Metro server is running. see the docs [https://reactnative.dev/docs/hermes#debugging-js-on-hermes-using-google-chromes-devtools](url)

This is the way. It worked flawlessly, thank you!

**Comment by AndresHB** [comment]
I am updating my React Native project, now I am using RN 0.72.6 and I cannot deactivate Hermes because otherwise the pod install fails, I changed the following lines:

`
Default line:
:hermes_enabled => flags[:hermes_enabled],

Changed to:
:hermes_enabled => false,`

And the pod install fails.
