### ISSUE TITLE
invalid range "t-5" in string transliteration [iOS]

### ISSUE THREAD

**Issue by Romick2005** [facebook/react-native#34610]
### Description

Get this error on running **pod install** on Mac Mini m1:
![image](https://user-images.githubusercontent.com/17779660/188651117-10b51892-80be-429f-85e7-cb4f95e264ce.png)
![image](https://user-images.githubusercontent.com/17779660/188651187-2384763d-d39f-4958-98b8-a7cddc672bfa.png)
**ios/Podfile:**
![image](https://user-images.githubusercontent.com/17779660/188651417-20ae8525-647a-4b45-8d19-147063488d79.png)
node_modules/react-native/scripts/cocoapods/**utils.rb:144**:
![image](https://user-images.githubusercontent.com/17779660/188651339-2906aac6-ebb0-4d7b-bc64-bfa7ee6608fd.png)

Suggested change:
![image](https://user-images.githubusercontent.com/17779660/188652400-2edd84bb-af61-4825-a531-c27f05c9fa68.png)

### Version

0.70.0

### Output of `npx react-native info`

System:
    OS: macOS 12.5.1
    CPU: (8) arm64 Apple M1
    Memory: 553.00 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.18.0 - /usr/local/bin/npm
    Watchman: 2021.09.27.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

cd ios && pod install

### Snack, code example, screenshot, or link to a repository

Already provided

**Comment by Sam-Lam-Secret-Key-Labs** [comment]
Possible duplicate:
https://github.com/facebook/react-native/issues/34530

**Comment by Romick2005** [comment]
Escape **t** with **\t** character in node_modules/react-native/scripts/cocoapods/utils.rb:144 also works:
```
        lib_search_paths.delete("$(TOOLCHAIN_DIR)/usr/lib/swif\t-5.0/$(PLATFORM_NAME)")
        lib_search_paths.delete("\"$(TOOLCHAIN_DIR)/usr/lib/swif\t-5.0/$(PLATFORM_NAME)\"")
```

**Comment by hengkx** [comment]
same errors

**Comment by Romick2005** [comment]
Issue was introduced in this [commit](https://github.com/facebook/react-native/commit/4f732ba9ee2a1e162729c97d5c12ea771b3a424a#diff-adcf572f001c2b710d14f409c14763f1a50b08369b3034548f1602685d21f67f)

**Comment by ray-holland-es** [comment]
I am also getting this error when running `pod install` - This is on an Intel based Mac.

**Comment by Josh-Speser** [comment]
when release?

**Comment by mdeoliveira-hw** [comment]
I am also getting this on M1. Did the [fix](https://github.com/facebook/react-native/pull/34636) that had been merged, fix the problem for you ?

**Comment by Romick2005** [comment]
Yes it was merged and available starting from 0.70.1 version.

**Comment by Romick2005** [comment]
Now it works!

**Comment by mdeoliveira-hw** [comment]
I still got the issue after upgrading to RN 0.70.1. There is something wrong with my configuration ?

```
[!] An error occurred while processing the post-install hook of the Podfile.

invalid range "t-5" in string transliteration

/node_modules/react-native/scripts/cocoapods/utils.rb:145:in `delete'
/node_modules/react-native/scripts/cocoapods/utils.rb:145:in `fix_library_search_path'
/node_modules/react-native/scripts/cocoapods/utils.rb:85:in `block (2 levels) in fix_library_search_paths'
/node_modules/react-native/scripts/cocoapods/utils.rb:84:in `each'
/node_modules/react-native/scripts/cocoapods/utils.rb:84:in `block in fix_library_search_paths'
/node_modules/react-native/scripts/cocoapods/utils.rb:83:in `each'
/node_modules/react-native/scripts/cocoapods/utils.rb:83:in `fix_library_search_paths'
/node_modules/react-native/scripts/react_native_pods.rb:158:in `react_native_post_install'
/ios/Podfile:38:in `block (3 levels) in from_ruby'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-core-1.11.3/lib/cocoapods-core/podfile.rb:196:in `post_install!'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:945:in `run_podfile_post_install_hook'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:933:in `block in run_podfile_post_install_hooks'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:149:in `message'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:932:in `run_podfile_post_install_hooks'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:331:in `block (2 levels) in create_and_save_projects'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer/xcode/pods_project_generator/pods_project_writer.rb:61:in `write!'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:330:in `block in create_and_save_projects'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in `section'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:309:in `create_and_save_projects'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:301:in `generate_pods_project'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:180:in `integrate'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:167:in `install!'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/command/install.rb:52:in `run'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:52:in `run'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/bin/pod:55:in `<top (required)>'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/bin/pod:25:in `load'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/bin/pod:25:in `<main>'
```

Here is info about my project 
```
System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Pro
    Memory: 5.55 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.0/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
    Watchman: 2022.09.05.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8815526
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.1 => 0.70.1
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found```

**Comment by Romick2005** [comment]
Have you actually open this file on line 145?
node_modules/react-native/scripts/cocoapods/utils.rb:145

You can see code in action there and comment that line just check if it helps

**Comment by mdeoliveira-hw** [comment]
Yes, I checked the file. If I comment the line, pod install worked, but it's not a lasting solution
