### ISSUE TITLE
[AlertIOS] UIAlertView is deprecated in iOS 9.0

### ISSUE THREAD

**Issue by jadsonlourenco** [facebook/react-native#3461]
````
warning: 'UIAlertView' is deprecated: first deprecated in iOS 9.0 - UIAlertView is deprecated. Use UIAlertController with a preferredStyle of UIAlertControllerStyleAlert instead
````
Detecting the iOS version, and if is the 9+ use this new controller **UIAlertController**, if is old version use the *UIAlertView*.

**Comment by javache** [comment]
This would be a great PR, but I don't think it's urgent.

Even better than doing an explicit version check would be to use `if ([UIAlertController class]`.

**Comment by christopherdro** [comment]
@jadsonlourenco Looks like this has been fixed by https://github.com/facebook/react-native/commit/cf0a28265ab931acfd5d2db339c41f6cde800da5.

Can you double check and close the issue if everything works?

**Comment by jadsonlourenco** [comment]
@christopherdro Yes, I can confirm that! 
But I get the same warning on file **RCTUtils.h** yet, just one now.

**Comment by christopherdro** [comment]
@jadsonlourenco I think the warning is something that we're just going to have to live with for now and doesn't really require an open issue. Glad to hear it works for you now!

**Comment by jadsonlourenco** [comment]
@christopherdro I understand. Thanks for all!

**Comment by KeithZhang** [comment]
the same issue

![image](https://cloud.githubusercontent.com/assets/2190059/11555749/734f2fb4-99dd-11e5-8fc6-8373cf7e21e7.png)

**Comment by christopherdro** [comment]
@KeithZhang Could you provide us more info on how your calling it?

**Comment by jadsonlourenco** [comment]
@KeithZhang you can't call the Alert from a **Modal** component. I hope this to be possible in the near future.
