### ISSUE TITLE
Why is zindex not supported in Fabric ?

### ISSUE THREAD

**Issue by jgx-jay** [facebook/react-native#34617]
### Description

Why is zindex not supported in Fabric?
My page is not displaying properly now. Is there any alternative?
![7cbefc90-2eab-11ed-9e90-4b726e289004](https://user-images.githubusercontent.com/16551050/188882512-a7f87d5c-ea2d-452b-a746-c8266aa1700c.png)

### Version

0.68.1

### Output of `npx react-native info`

noop

### Steps to reproduce

noop

### Snack, code example, screenshot, or link to a repository

noop

**Comment by jgx-jay** [comment]
I need some help

**Comment by hannojg** [comment]
The commit message states that fabric supports `zIndex`, but they just turned off some no longer necessary functionality internally.

If you can provide a reproduction of your issue perhaps the community can assist you in fixing your problem.
