### ISSUE TITLE
'React/RCTComponentViewProtocol.h' file not found on Upgrade to v0.69.5

### ISSUE THREAD

**Issue by fawad-khalil-retailo** [facebook/react-native#34625]
### New Version

0.69.5

### Old Version

0.67.4

### Build Target(s)

iOS Simulator in debug mode

### Output of `react-native info`
System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1
    Memory: 479.03 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.0/bin/yarn
    npm: 8.1.4 - ~/.nvm/versions/node/v16.13.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7784292
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 12.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.5 => 0.69.5 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Issue and Reproduction Steps

1. npx react-native upgrade
2. Resolve conflicts
3. Verify the upgrade from RN upgrade helper 
4. Add the missing changes
5. yarn install
6. cd ios
7. Remove Pods folder
8. Remove Podfile.lock file
9. pod install
10. Clear Build from XCode
11. Build App

The XCode build process stops and reports that `'React/RCTComponentViewProtocol.h' file not found` in file `Pods/Development Pods/React-Codegen/RCTThirdPartyFabricComponentsProvider.h` on line `#import <React/RCTComponentViewProtocol.h>`.
PS: This didn't happen and the build passed successfully if initiated a clean RN project using `npx react-native init samplern --version 0.69.5`.

**Comment by fawad-khalil-retailo** [comment]
Updated the react-native info output

**Comment by zain610** [comment]
Running into the same issue. Any solutions highly appreciated 😄

**Comment by ste7en** [comment]
Same problem here

**Comment by ste7en** [comment]
I gitclean'd my workspace:
```sh
git clean -fxd
yarn install
cd ios
pod install
```
and it worked 💥 🤯

**Comment by ahsan-abrar** [comment]
Same issue 


Podfile

            $RNFirebaseAsStaticFramework = true

            require_relative '../node_modules/react-native/scripts/react_native_pods'
            require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

            platform :ios, '12.4'
            use_frameworks!
            install! 'cocoapods', :deterministic_uuids => false

            # todo custom add start
            pod 'rn-fetch-blob',
            :path => '../node_modules/rn-fetch-blob'
            # todo custom add end

            target 'jammAround' do
              config = use_native_modules!

              # Flags change depending on the env values.
              flags = get_default_flags()

              use_react_native!(
                :path => config[:reactNativePath],
                # Hermes is now enabled by default. Disable by setting this flag to false.
                # Upcoming versions of React Native may rely on get_default_flags(), but
                # we make it explicit here to aid in the React Native upgrade process.
                :hermes_enabled => true,
                :fabric_enabled => flags[:fabric_enabled],
                # Enables Flipper.
                #
                # Note that if you have use_frameworks! enabled, Flipper will not work and
                # you should disable the next line.
                # :flipper_configuration => FlipperConfiguration.enabled,
                # An absolute path to your application root.
                :app_path => "#{Pod::Config.instance.installation_root}/.."
              )

              target 'jammAroundTests' do
                inherit! :complete
                # Pods for testing
              end

              post_install do |installer|
                react_native_post_install(
                  installer,
                  # Set `mac_catalyst_enabled` to `true` in order to apply patches
                  # necessary for Mac Catalyst builds
                  :mac_catalyst_enabled => false
                )
                __apply_Xcode_12_5_M1_post_install_workaround(installer)
              end
            end


Package.json

           "@alessiocancian/react-native-actionsheet": "alessiocancian/react-native-actionsheet",
            "@aws-amplify/pushnotification": "^5.0.4",
            "@azure/core-asynciterator-polyfill": "^1.0.2",
            "@notifee/react-native": "^7.1.0",
            "@react-native-async-storage/async-storage": "^1.17.10",
            "@react-native-camera-roll/camera-roll": "^5.1.0",
            "@react-native-community/masked-view": "^0.1.11",
            "@react-native-community/netinfo": "^9.3.6",
            "@react-native-community/push-notification-ios": "^1.10.1",
            "@react-native-community/slider": "^4.3.3",
            "@react-native-firebase/app": "^16.4.6",
            "@react-native-picker/picker": "^2.4.7",
            "@react-navigation/bottom-tabs": "^6.3.3",
            "@react-navigation/native": "^6.0.8",
            "@react-navigation/stack": "^6.2.0",
            "@stream-io/flat-list-mvcp": "^0.10.2",
            "add": "^2.0.6",
            "amazon-cognito-identity-js": "^5.2.10",
            "aws-amplify": "^4.3.37",
            "aws-amplify-react-native": "^6.0.8",
            "lodash": "^4.17.21",
            "moment": "^2.29.4",
            "prop-types": "^15.8.1",
            "react": "18.1.0",
            "react-native": "0.70.4",
            "react-native-audio-recorder-player": "^3.5.1",
            "react-native-document-picker": "^8.1.2",
            "react-native-dotenv": "^3.4.2",
            "react-native-dropdown-picker": "^5.4.2",
            "react-native-fast-image": "^8.6.3",
            "react-native-floating-action": "^1.22.0",
            "react-native-fs": "^2.20.0",
            "react-native-gesture-handler": "^2.8.0",
            "react-native-image-crop-picker": "^0.38.1",
            "react-native-image-picker": "^4.10.0",
            "react-native-image-resizer": "^1.4.5",
            "react-native-inappbrowser-reborn": "^3.7.0",
            "react-native-iphone-x-helper": "^1.3.1",
            "react-native-linear-gradient": "^2.6.2",
            "react-native-pager-view": "^5.4.25",
            "react-native-raw-bottom-sheet": "^2.2.0",
            "react-native-reanimated": "^2.12.0",
            "react-native-safe-area-context": "^4.3.1",
            "react-native-screens": "^3.14.1",
            "react-native-share": "^8.0.0",
            "react-native-snackbar": "^2.4.0",
            "react-native-splash-screen": "^3.3.0",
            "react-native-svg": "^13.5.0",
            "react-native-svg-transformer": "^1.0.0",
            "react-native-uuid": "^2.0.1",
            "react-native-vector-icons": "^9.2.0",
            "react-redux": "^8.0.2",
            "reactotron-react-native": "^5.0.2",
            "redux": "^4.2.0",
            "redux-logger": "^3.0.6",
            "redux-storage": "^4.1.2",
            "redux-storage-decorator-filter": "^1.1.8",
            "redux-storage-engine-reactnativeasyncstorage": "^1.0.7",
            "remote-redux-devtools": "^0.5.16",
            "rn-fetch-blob": "0.13.0-beta.2",
            "seamless-immutable": "^7.1.4",
            "stream-chat-react-native": "^5.4.2",
            "twrnc": "^3.4.0",
            "yarn": "^1.22.19"

**Comment by ahsan-abrar** [comment]
> I gitclean'd my workspace:
> 
> ```shell
> git clean -fxd
> yarn install
> cd ios
> pod install
> ```
> 
> and it worked 💥 🤯

Not work for me

**Comment by mladen3** [comment]
Has anyone figured out the fix?

**Comment by tanisk27** [comment]
> I gitclean'd my workspace:
> 
> ```shell
> git clean -fxd
> yarn install
> cd ios
> pod install
> ```
> 
> and it worked 💥 🤯

This one fixed for me

**Comment by PunainenAurinko** [comment]
I had the same issue when upgrading to RN 0.73.3. 

Clean your project, delete yarn.lock and ios build folder. Run yarn and pod install. This should fix it. This has nothing to do with git, so do not attempt to do weird stuff with git, you will lose your files.

**Comment by badalsaibo** [comment]
```console
cd ios
rm -rf ./Pods
rm -rf ./build
pod install
```

**Comment by ejabu** [comment]
> > I gitclean'd my workspace:
> > ```shell
> > git clean -fxd
> > yarn install
> > cd ios
> > pod install
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and it worked 💥 🤯
> 
> This one fixed for me


I'm not sure with `git clean -fxd`. This line poses risk, and in my local, it works without `git clean`.

**Comment by Rebsos** [comment]
> I gitclean'd my workspace:
> 
> ```shell
> git clean -fxd
> yarn install
> cd ios
> pod install
> ```
> 
> and it worked 💥 🤯

@ste7en could you please add to your comment something like "Warning: all untracked files of your repo will be deleted".

It worked for me thanks, but I lost some of my files, which I had to recover from time machine

**Comment by therbta** [comment]
> **Warning: all untracked files of your repo will be deleted**
> 
> I gitclean'd my workspace:
> 
> ```shell
> git clean -fxd
> yarn install
> cd ios
> pod install
> ```
> 
> and it worked 💥 🤯

Thank you I've lost my project!

**Comment by Gattanjo-Extrapreneur** [comment]
> cd ios
> rm -rf ./Pods
> rm -rf ./build
> pod install

Destroyed my project. This guy should be banned.

**Comment by tanisk27** [comment]
> > cd ios
> > rm -rf ./Pods
> > rm -rf ./build
> > pod install
> 
> Destroyed my project. This guy should be banned.

Hey don't worry this should fix your issue, 

sudo rm -rf /
cd ios
pod install
