### ISSUE TITLE
Top level bundle errors are not displayed

### ISSUE THREAD

**Issue by rickhanlonii** [facebook/react-native#34649]
## Overview

If there's an error when evaluating a module, the app crashes and the stack trace is not reported in the console:

<img width="1728" alt="Screen Shot 2022-09-08 at 10 01 17 AM" src="https://user-images.githubusercontent.com/2440089/189388665-0cb44a56-4fad-4367-b85a-65990dc01397.png">

Expectation is that the app shows a LogBox with a code frame to the source of the issue, or at least a redbox with the error message and stack trace, and the console includes the stack trace so you can find the source of the problem.

### Version

0.70

### Output of `npx react-native info`

<details>
❯ npx react-native info
info Fetching system and libraries information...
System:
    OS: macOS 12.5
    CPU: (10) arm64 Apple M1 Max
    Memory: 3.51 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.7.0 - ~/.nvm/versions/node/v18.7.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.7.0/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v18.7.0/bin/npm
    Watchman: 20220829 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8815526
    Xcode: 13.4/13F17a - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.5 => 0.69.5 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
</details>

### Steps to reproduce

- Clone a new app
- Render any component with `propTypes`:

```
import {ViewPropTypes} from 'react-native';

const MyView = () => {
  return <Text>Hello World</Text>;
};

MyView.propTypes = ViewPropTypes;

//...

// In the App.js componet:
<MyView>
```

### Snack, code example, screenshot, or link to a repository

Above

**Comment by motiz88** [comment]
I believe this is fixable with a tweak to `react-native`'s `InitializeCore` module. There are side-effects in `AppRegistry` that never run if an error gets thrown very early in user code (at least the way the basic React Native template app is set up), thus preventing React Native from rendering LogBox for the error.

Specifically, by adding the line `require('../ReactNative/AppRegistry');` [here](https://github.com/facebook/react-native/blob/0f980419f28c4a9f6fd219ffec86de35b7d2e3b1/Libraries/Core/InitializeCore.js#L45) I was able to get an early error to consistently render a LogBox (with a valid secondary error saying that the app's root component wasn't registered).

![image](https://user-images.githubusercontent.com/2246565/189409598-8ffa028f-673f-4ab8-9efb-a181ede063f3.png)

![image](https://user-images.githubusercontent.com/2246565/189409616-3df3bae4-a402-4993-81a6-e2dde5ba0905.png)
