### ISSUE TITLE
Best practices for creating modules that reference 3rd party native libraries

### ISSUE THREAD

**Issue by chris-erickson** [facebook/react-native#3464]
I'm working on a custom module that makes use of and exposes the Google Analytics SDK, and got 90% of the way there.  I'm having a lot of trouble resolving the ```'RCTBridgeModule.h file not found'``` error in Xcode when trying to build my app.  The module builds successfully on it's own, but I get this error after installing it with npm/CocoaPods.

I've followed various [parts](http://blog.sigmapoint.pl/developing-static-library-for-ios-with-cocoapods/) of [multiple](http://brentvatne.ca/packaging-react-native-component/) [guides](http://eastcodes.com/packaging-and-sharing-react-native-modules) with no luck.  I'm mimicking what is done with the native Facebook [implementation](https://github.com/facebook/react-native-fbsdk/tree/master/react-native-fbsdklogin) where npm is used to distribute the code, and CocoaPods is used to gather the iOS dependencies.

I've tried all sorts of incantations of the `HEADER_SEARCH_PATHS` but nothing seems to work.  What am I missing?  Are there better guides on accomplishing what I'd like to do?  I may just contribute some docs if I can get it working, and there isn't anything better than what I have found thus far.

Current progress on this project can be found at [this repo](https://github.com/gsmke/react-native-google-analytics-sdk).

**Comment by jaygarcia** [comment]
This is a header search path issue.  Retrace your steps.  Is it recursive? Also, put a link to the repo here if possible so one of us can look at it with/for you.

**Comment by chris-erickson** [comment]
Thanks @jaygarcia.  I tried all sorts of permutations, and I don't think I missed making them recursive.  The repo is at the bottom of the issue.  Thanks!

**Comment by jaygarcia** [comment]
OK, here's what works for me.

In your library Xcode project:
add a recursive header search path `$(SRCROOT)/../react-native/React`

see if that helps @chris-erickson.

**Comment by chris-erickson** [comment]
Still no luck with these settings:

![screen shot 2015-10-18 at 6 10 28 pm](https://cloud.githubusercontent.com/assets/3322287/10567240/99150ad6-75c3-11e5-9d1c-e962acb83fcc.png)

With this error (no surprise):
![screen shot 2015-10-18 at 6 13 09 pm](https://cloud.githubusercontent.com/assets/3322287/10567250/edb14b2c-75c3-11e5-8b52-b15869113ed7.png)

Were you able to successfully include the project into another project using CocoaPods like this:

```ruby
pod 'react-native-google-analytics-sdk', :path => '../node_modules/react-native-google-analytics-sdk'
```

I guess this another thing I get hung up on - would this be used by installing the CocoaPod directly, or by `npm install` it, then link the CocoaPod as in my example above?

**Comment by jaygarcia** [comment]
So very strange. Any way i could ask you to email me a zip of your project so i can look at it?

jay@moduscreate.com

Thanks

**Comment by chris-erickson** [comment]
With some help from @jaygarcia I was able to get it working by adding `${PODS_ROOT}/../../node_modules/react-native/React` (recursive) to the Pod project header search paths.  This won't survive a `pod install` As far as I can tell, so it's not a long term solution.

Currently I'm developing this locally so it shows up in the Development Pods group in the Pods project.  Is this any part of the problem?

Starting to think I'm misunderstanding some critical piece to making this work.

**Comment by chris-erickson** [comment]
I'm starting to think that this is an issue with using CocoaPods this way (it gives the same error as _my_ custom module):
```ruby
target 'SmartCraft' do
  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
end
```
Maybe someone knows that this is a bad way to include the code?  I just don't love the option of manually dragging project files and linking libraries.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/best-practices-for-creating-modules-that-reference-3rd-party-native-libraries

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
