### ISSUE TITLE
Unable to install pods on bare project with new arch enabled

### ISSUE THREAD

**Issue by fawad-khalil** [facebook/react-native#34657]
### Description

I am unable to install pods with new arch enabled on bare RN 0.70.0 project. I get the following error:
```
[!] Invalid `Podfile` file: No such file or directory @ rb_sysopen - ../node_modules/react-native/package.json.

 #  from /Users/fawadkhalil/Documents/samplern/Cargr/ios/Podfile:13
 #  -------------------------------------------
 #  
 >    use_react_native!(
 #      :path => config[:reactNativePath],
 #  -------------------------------------------

[!] [Codegen] warn: using experimental new codegen integration
```

### Version

0.70.0

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1
    Memory: 826.41 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.0/bin/yarn
    npm: 8.1.4 - ~/.nvm/versions/node/v16.13.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8815526
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 12.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.0 => 0.70.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. Create new RN project with `npx react-native init sampleapp`
2. Run `USE_FABRIC=1 RCT_NEW_ARCH_ENABLED=1 pod install --project-directory=ios`

### Snack, code example, screenshot, or link to a repository

Not needed. It's just a bare RN project.

**Comment by team55** [comment]
use 
cd ios
USE_FABRIC=1 RCT_NEW_ARCH_ENABLED=1 pod install

**Comment by fawad-khalil** [comment]
Thank you. That has worked. So it won't work from the root dir.
