### ISSUE TITLE
Android 12 Crash Unhandled libhwui SkSurface getCanvas

### ISSUE THREAD

**Issue by putuoka** [facebook/react-native#34669]
### Description

  #00  pc 0x000000000066f40c  /system/lib64/libhwui.so (SkSurface::getCanvas())
  #00  pc 0x000000000075919c  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::GLFunctorDrawable::onDraw(SkCanvas*))
  #00  pc 0x0000000000727f70  /system/lib64/libhwui.so (SkDrawable::draw(SkCanvas*, SkMatrix const*))
  #00  pc 0x0000000000a2418c  /system/lib64/libhwui.so (SkGpuDevice::drawDrawable(SkDrawable*, SkMatrix const*, SkCanvas*))
  #00  pc 0x0000000000735c64  /system/lib64/libhwui.so (android::uirenderer::$_36::__invoke(void const*, SkCanvas*, SkMatrix const&) (.llvm.7336732046262659986))
  #00  pc 0x0000000000581600  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const)
  #00  pc 0x0000000000580698  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::onDraw(SkCanvas*))
  #00  pc 0x00000000004e237c  /system/lib64/libhwui.so (android::uirenderer::$_23::__invoke(void const*, SkCanvas*, SkMatrix const&) (.llvm.7336732046262659986))
  #00  pc 0x0000000000581600  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const)
  #00  pc 0x0000000000580698  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::onDraw(SkCanvas*))
  #00  pc 0x00000000004e237c  /system/lib64/libhwui.so (android::uirenderer::$_23::__invoke(void const*, SkCanvas*, SkMatrix const&) (.llvm.7336732046262659986))
  #00  pc 0x0000000000581600  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const)
  #00  pc 0x0000000000580698  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::onDraw(SkCanvas*))
  #00  pc 0x00000000004e237c  /system/lib64/libhwui.so (android::uirenderer::$_23::__invoke(void const*, SkCanvas*, SkMatrix const&) (.llvm.7336732046262659986))
  #00  pc 0x0000000000581600  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const)
  #00  pc 0x0000000000585258  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::forceDraw(SkCanvas*) const)
  #00  pc 0x00000000005ca628  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::SkiaPipeline::renderLayersImpl(android::uirenderer::LayerUpdateQueue const&, bool))
  #00  pc 0x00000000005c7b1c  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::SkiaPipeline::renderFrame(android::uirenderer::LayerUpdateQueue const&, SkRect const&, std::__1::vector<android::sp<android::uirenderer::RenderNode>, std::__1::allocator<android::sp<android::uirenderer::RenderNode> > > const&, bool, android::uirenderer::Rect const&, sk_sp<SkSurface>, SkMatrix const&))
  #00  pc 0x00000000005c7674  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::SkiaOpenGLPipeline::draw(android::uirenderer::renderthread::Frame const&, SkRect const&, SkRect const&, android::uirenderer::LightGeometry const&, android::uirenderer::LayerUpdateQueue*, android::uirenderer::Rect const&, bool, android::uirenderer::LightInfo const&, std::__1::vector<android::sp<android::uirenderer::RenderNode>, std::__1::allocator<android::sp<android::uirenderer::RenderNode> > > const&, android::uirenderer::FrameInfoVisualizer*))
  #00  pc 0x000000000063c200  /system/lib64/libhwui.so (android::uirenderer::renderthread::CanvasContext::draw())
  #00  pc 0x000000000063ab58  /system/lib64/libhwui.so (_ZNSt3__110__function6__funcIZN7android10uirenderer12renderthread13DrawFrameTask11postAndWaitEvE3$_0NS_9allocatorIS6_EEFvvEEclEv$c1671e787f244890c877724752face20)
  #00  pc 0x000000000064c4f8  /system/lib64/libhwui.so (android::uirenderer::WorkQueue::process())
  #00  pc 0x000000000064c258  /system/lib64/libhwui.so (android::uirenderer::renderthread::RenderThread::threadLoop())
  #00  pc 0x000000000001358c  /system/lib64/libutils.so (android::Thread::_threadLoop(void*))
  #00  pc 0x0000000000012de8  /system/lib64/libutils.so (thread_data_t::trampoline(thread_data_t const*))
  #00  pc 0x00000000000b6d54  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*))
  #00  pc 0x0000000000053370  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread)

### Version

0.63.4

### Output of `npx react-native info`

System:
    OS: Windows 10 10.0.17134
    CPU: (4) x64 Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
    Memory: 3.36 GB / 11.88 GB
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - D:\oka\app\node_modules\.bin\yarn.CMD
    npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.11.31605.320 (Visual Studio Community 2019)
  Languages:
    Java: Not Found
    Python: 3.9.5 - D:\Users\oka\AppData\Local\Programs\Python\Python39\python.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.4 => 0.63.4
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

N/A

### Snack, code example, screenshot, or link to a repository

N/A

**Comment by cortinico** [comment]
Closing as there is not a single element in the stacktrace that points to React Native.
Moreover you're on a old version of React Native. Re-try on 0.70 and reopen if the issue still happens.

**Comment by dsuryawanshirussell** [comment]
This crash is happening on latest react native version as well 0.72.1 for Android11 and 13
