### ISSUE TITLE
Can Not Find Symbol : BuildConfig

### ISSUE THREAD

**Issue by hicath** [facebook/react-native#34661]
### Description

I upgraded my react-native project from ~0.67.1 to 0.70.0, I followed all the guidance here: https://react-native-community.github.io/upgrade-helper/?from=0.67.1&to=0.70.0.

After the upgrade process, error start showing up saying 

```
cannot find symbol if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {
        ^
  symbol:   variable BuildConfig
  location: class MainApplication
```

and other similar BuildConfig error message on other files as well. 

### Version

0.70.0

### Output of `npx react-native info`

System:
OS: macOS 12.2.1
CPU: (8) arm64 Apple M1
Memory: 1.15 GB / 16.00 GB
Shell: 5.8 - /bin/zsh
Binaries:
Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
Yarn: 1.22.19 - /opt/homebrew/bin/yarn
npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
Watchman: Not Found
Managers:
CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
SDKs:
iOS SDK:
Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
Android SDK: Not Found
IDEs:
Android Studio: 2021.1 AI-211.7628.21.2111.8193401
Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
Languages:
Java: 11.0.14.1 - /usr/bin/javac
npmPackages:
@react-native-community/cli: Not Found
react: 18.1.0 => 18.1.0
react-native: 0.70.0 => 0.70.0
react-native-macos: Not Found
npmGlobalPackages:
react-native: Not Found

### Steps to reproduce

- Upgrade react native version to 0.70.0 according to this documentation: https://react-native-community.github.io/upgrade-helper/?from=0.67.1&to=0.70.0.
- Clean the gradle using `./gradlew clean`
- Run the metro by using `yarn run start`
- Run android with `yarn android`

### Snack, code example, screenshot, or link to a repository

Already provided above.

**Comment by cortinico** [comment]
> After the upgrade process, error start showing up saying

This usually happens if you haven't built the project once.
Where are those errors showing up? In the IDE or in the terminal?

**Comment by bukhari-flip** [comment]
is this related to this  #33623 ?

**Comment by cortinico** [comment]
Yes it's related to https://github.com/facebook/react-native/issues/33623 as @bukhari-flip suggested.
