### ISSUE TITLE
Error build new project Xcode 14

### ISSUE THREAD

**Issue by luism3861** [facebook/react-native#34677]
### Description

create a new project with new version react native when it finished build crashed
<img width="1184" alt="Screen Shot 2022-09-13 at 10 34 26" src="https://user-images.githubusercontent.com/36824170/189944805-dd6aec3b-de6c-4fb3-a6be-d6ec5b877b49.png">

### Version

0.70

### Output of `npx react-native info`

System:
    OS: macOS 12.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 178.63 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.18.0 - /usr/local/bin/npm
    Watchman: 2022.09.05.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 14.0/14A309 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.0 => 0.70.0
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

.

### Snack, code example, screenshot, or link to a repository

.

**Comment by yaroslavnikiforov** [comment]
This is not related to XCode 14. I have the same with XCode v13.4.1 and react-native 0.70.0.

**Comment by kelset** [comment]
refer to https://github.com/facebook/react-native/issues/34673 and https://github.com/facebook/react-native/issues/34608#issuecomment-1246730507

**Comment by t1gu1** [comment]
I got the same same error. (The one on the image)

For me everything build on XCode v13.4.1 but **not on XCode v14**.
We use react-native: **0.70.3**
