### ISSUE TITLE
keyboardWillShow not triggered in Android

### ISSUE THREAD

**Issue by ortutay** [facebook/react-native#3468]
I am registering for `keyboardWillShow` like this:

    this.addListenerOn(RCTDeviceEventEmitter, 'keyboardWillShow', this.updateKeyboardSpace);

This works fine in iOS, but in Android it does not trigger the event as expected. `keyboardDidShow` does work in Android.

**Comment by satya164** [comment]
I can confirm this.

**Comment by hufeng** [comment]
Yes, we have the same problem.

**Comment by yychun1217** [comment]
so it is not supported in Android?

**Comment by ide** [comment]
Keyboard events are unimplemented on Android.

**Comment by satya164** [comment]
@yychun1217 `KeyboardDidShow` and `KeyboardDidHide` works on Android, so I guess whatever you wanted to do with will show events, you could do on did show instead.

**Comment by matth3wga0** [comment]
@satya164 Both `KeyboardDidShow` and `keyboardWillShow` events will not been triggered on Android, as I've set `android:windowSoftInputMode` to `adjustResize`.

```js
componentDidMount() {
  DeviceEventEmitter.addListener('KeyboardDidShow', e => {
    // Nope
  });

  DeviceEventEmitter.addListener('keyboardWillShow', e => {
    // Nope
  });
}
```

**Comment by satya164** [comment]
@matth3wga0 I'm using `adjustResize` and `KeyboardDidShow` and `KeyboardDidHide` work just fine. - https://github.com/scrollback/io.scrollback.neighborhoods/blob/master/views/components/keyboard-spacer.js

**Comment by matth3wga0** [comment]
@satya164 I'm using v0.14.2 and running on Android 5.1, what's yours?

**Comment by satya164** [comment]
@matth3wga0 Was using 0.12 previously, now using 0.15-rc, on Android 5.0.

**Comment by matth3wga0** [comment]
@satya164 Thanks, I'll have a try with 0.15-rc.

**Comment by Sh3rawi** [comment]
Im using RN 0.18-rc with a Moto X 5.1, keyboardDidHide and keyboardDidShow are both triggered on the showing of the keyboard (Actually, keyboardDidHide is triggered before DidShow!).
<img width="788" alt="screen shot 2016-01-12 at 11 06 15 pm" src="https://cloud.githubusercontent.com/assets/13085991/12276916/25ffb422-b981-11e5-9f53-0f7813071e80.png">

**Comment by kristjanmik** [comment]
keyboardWillShow and keyboardDidHide ar not in RN 0.18-rc

**Comment by jblack10101** [comment]
+1 for interest

**Comment by motiazu** [comment]
+1
Iv'e been trying any way I could find, it looks like any method of knowing when the keyboard is up and it's height does not work anymore :(

Does anyone have a workaround for this?

**Comment by Iliyass** [comment]
+1 RN: 18.1, Android: 5.0.2, Device: LG G2

**Comment by skv-headless** [comment]
I use ```keyboardDidHide``` and ```keyboardDidHide```  here is source code https://github.com/facebook/react-native/blob/228a1fe7d48d57a0fbb2d852135ef94247198aaa/ReactAndroid/src/main/java/com/facebook/react/ReactRootView.java#L424

**Comment by zoharlevin** [comment]
+1 this still doesn't work in android

**Comment by zoharlevin** [comment]
ok, i somehow missed this, so...
for anybody who was confused (like me :)) i can confirm that `keyboardWillShow` + `keyboardWillHide` don't work on android but `keyboardDidShow` and `keyboardDidHide` **do** work on android.

thanks @skv-headless

**Comment by motiazu** [comment]
@zoharlevin  Holy crap it works! Thanks!

**Comment by Iliyass** [comment]
it works, thanks man

**Comment by GantMan** [comment]
@christopherdro 
I see this was closed, but I don't see why.   Is there a PR that fixes this?  I'd like to follow whatever version it will be released with, if so.

**Comment by christopherdro** [comment]
@GantMan 
This was closed because this is more of a missing feature than an actual bug.
Lately we've been trying to reduce the amount of issues down to actual bugs with the core project.

Feel free to submit a PR adding this functionality and link it back to this thread.

**Comment by pewh** [comment]
From the [docs](https://facebook.github.io/react-native/docs/keyboard.html) said it supports keyboardWillShow and keyboardWillHide. I tried it but not work. Are these supported right now?

**Comment by GantMan** [comment]
they have never been supported I think.

**Comment by seque1990** [comment]
Still not working for `keyboardWillShow` and `keyboardWillHide`

**Comment by otoinsa** [comment]
On Android it sort of works in React 0.41.2

I have noticed, that if I have set android:windowSoftInputMode to 'adjustNothing', these events are not fired.

Why? For me, the default behavior for android:windowSoftInputMode produces layout issues,
so i'd like these events to still fire even if I've set android:windowSoftInputMode to 'adjustNothing'

**Comment by superandrew213** [comment]
@GantMan can we reopen this? This feature is supposed to be implemented for both iOS and Android
https://facebook.github.io/react-native/docs/keyboard.html

Not all of the events work for Android and the docs don't mention this. If they have not been implemented on Android yet, then we should update the docs to reflect that.

**Comment by superandrew213** [comment]
@christopherdro why was this closed? In the docs it says that all event should fire for both iOS and Android: https://facebook.github.io/react-native/docs/keyboard.html

If some events have not been implemented yet, then the docs should be updated to reflect that some events are iOS only.

**Comment by superandrew213** [comment]
@otoinsa you can try using `react-native-android-keyboard-adjust` if it helps. It allows you to dynamically change the windowSoftInputMode

**Comment by rendomnet** [comment]
keyboardWillShow/keyboardWillHide still not working on Android?
I have no "android:windowSoftInputMode : adjustResize or adjustNothing" and still cant get keyboardWillShow/keyboardWillHide to work.

**Comment by m860** [comment]
same issue , react native version is 0.44.0

**Comment by carlos-peru** [comment]
This is working on 0.46

**Comment by MyTotoro** [comment]
@carlos-peru where is this documented? thanks

**Comment by Ashoat** [comment]
`keyboardWillShow`/`keyboardWillHide` still not working for me on Android and RN 0.47.0

**Comment by danReynolds** [comment]
The documentation says:

> Note that if you set android:windowSoftInputMode to adjustResize or adjustNothing, only keyboardDidShow and keyboardDidHide events will be available on Android. keyboardWillShow as well as keyboardWillHide are generally not available on Android since there is no native corresponding event.

Does that mean adjustPan works for example? That first sentence seems to imply keyboardWillShow and keyboardWillHide is available on other input modes.

**Comment by nik0lica** [comment]
> Note that if you set android:windowSoftInputMode to adjustResize or adjustNothing, only keyboardDidShow and keyboardDidHide events will be available on Android. keyboardWillShow as well as keyboardWillHide are generally not available on Android since there is no native corresponding event.

I can confirm that if you set android:windowSoftInputMode to adjustNothing **none** of events are available for Android.

**Comment by Titozzz** [comment]
I also need the event when android:windowSoftInputMode is adjustNothing 😢

**Comment by johngoren** [comment]
I can't get windowSoftInput mode to work reliably, and KeyboardAvoidingView is hard to debug so I was hoping to get at this feature more directly in Android. But it's not working. RN 49.

**Comment by sabbyt54** [comment]
+1 confirmed no event when android:windowSoftInputMode is adjustNothing

**Comment by northern** [comment]
I'm running into the same problem in that the `keyboardDidShow` and `keyboardDidHide` are only fired on Android when the `android:windowSoftInputMode` is set to `adjustResize`.

However, when the `android:windowSoftInputMode` is set to `adjustResize` then when you're using a `TabNavigator` from the React Navigation package, when the keyboard on Android shows, it pushes the tabbar (if it's aligned at the bottom) up with the keyboard. To work around this pushing up you can set `android:windowSoftInputMode` is set to `adjustNothing` but doing this means that your content (text fields etc.) are behind your keyboard.

On iOS I've been working around this problem by adding a spacer View with a height of the keyboard at the end of my view when the keyboard opens, but since the event doesn't fire, this work around doesn't work for Android.

So, at the moment, on Android you can either have keyboard events (with `adjustResize`) but you will have a pushed up TabNavigator or you can have a hidden TabNavigator and no keyboard events.

It's a bit of a pickle...

**Comment by kkotkkio** [comment]
It's works both iOS and Android.

```
state = {
 btnLocation: 0
}
  componentWillMount() {
    this.keyboardDidShowListener = Keyboard.addListener('keyboardDidShow', this._keyboardWillShow.bind(this));
    this.keyboardDidHideListener = Keyboard.addListener('keyboardDidHide', this._keyboardWillHide.bind(this));
  }
  componentWillUnmount () {
    this.keyboardDidShowListener.remove();
    this.keyboardDidHideListener.remove();
  }

  _keyboardWillShow(e) {
    this.setState({btnLocation: e.endCoordinates.height});
  }
  _keyboardWillHide(e) {
    this.setState({btnLocation: 0})
  }
```

**Comment by cathy810218** [comment]
@kkotkkio  I don't think that works the way we want it to. You're still doing `keyboardDidShow` and `keyboardDidHide`, you are just calling the functions and name those function WILL - `keyboardWillShow` and `keyboardWillHide` but it doesn't make sense. Because those functions are fired AFTER keyboard is shown instead of BEFORE.

**Comment by cihadturhan** [comment]
I know I'm beating the dead horse here but the issue opened in Oct 2015 and it's still not working in 2018 at RN 55.4

**Comment by ngocnguyen09910060** [comment]
I'm facing same issue when `android:windowSoftInputMode` is `adjustNothing`.
Hi Mr @northern, have you resolved this issue ?

**Comment by ArturDrozdz** [comment]
Still the same on Android. 

![re-open mkayyy](https://media.giphy.com/media/13PBOiVnRnbuZa/giphy.gif)

**Comment by Billy-** [comment]
@christopherdro @shergin Can someone explain why this was closed please?
