### ISSUE TITLE
 ERROR  Invariant Violation: ViewPropTypes has been removed from React Native. Migrate to ViewPropTypes exported from 'deprecated-react-native-prop-types'.

### ISSUE THREAD

**Issue by LuckyMadu** [facebook/react-native#34685]
### Description

I have searched the whole repository. But I couldn't find **ViewPropTypes** anywhere in the project.

```
// Deprecated Prop Types
  get ColorPropType(): $FlowFixMe {
    invariant(
      false,
      'ColorPropType has been removed from React Native. Migrate to ' +
      "ColorPropType exported from 'deprecated-react-native-prop-types'.",
    );
  },
  get EdgeInsetsPropType(): $FlowFixMe {
    invariant(
      false,
      'EdgeInsetsPropType has been removed from React Native. Migrate to ' +
      "EdgeInsetsPropType exported from 'deprecated-react-native-prop-types'.",
    );
  },
  get PointPropType(): $FlowFixMe {
    invariant(
      false,
      'PointPropType has been removed from React Native. Migrate to ' +
      "PointPropType exported from 'deprecated-react-native-prop-types'.",
    );
  },
  get ViewPropTypes(): $FlowFixMe {
    invariant(
      false,
      'ViewPropTypes has been removed from React Native. Migrate to ' +
      "ViewPropTypes exported from 'deprecated-react-native-prop-types'.",
    );
  },
```

Use this in node_modules -> react-native -> index.js

### Version

0.70

### Output of `npx react-native info`

System:
    OS: macOS 12.2.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 95.16 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.4.0 - /opt/homebrew/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.12.1 - /opt/homebrew/bin/npm
    Watchman: 2022.06.06.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8309675
    Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.70.0 => 0.70.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

When building the project

### Snack, code example, screenshot, or link to a repository

<img width="682" alt="Screenshot 2022-09-14 at 15 44 20" src="https://user-images.githubusercontent.com/19740478/190127535-afc06f17-4d5e-4181-9193-d320ea13859d.png">

**Comment by LuckyMadu** [comment]
And I tried this solution: https://stackoverflow.com/questions/71702392/viewproptypes-will-be-removed-from-react-native-migrate-to-viewproptypes-export/73313120#73313120

But it won't work.

**Comment by danilobuerger** [comment]
If you share a reproducible repository, I would take a look.

**Comment by Almas-Asghar-730** [comment]
Invariant Violation: ViewPropTypes has been removed from React Native. Migrate to ViewPropTypes exported from 'deprecated-react-native-prop-types'.
having the same issue is their any solution?

**Comment by Bayramito** [comment]
i actually applied the solution by adding `deprecated-react-native-prop-types` to the app but somehow external modules did not get effected from that. so result is, every external lib which used ViewPropTypes from `react-native` still keep crashing and need to be patched one by one.

**Comment by alexkendall** [comment]
Same problem. Swapped deprecated-react-native-prop-types in my code and can't find ViewPropTypes anywhere in the project.

**Comment by devDoubleH** [comment]
Hi, @LuckyMadu I found this [video](https://www.youtube.com/watch?v=Lk0PuqXa53Q) from youtube and this helped me.

1. open your node_modules/react-native/index.js
2. search for `get ViewPropTypes()`
3. replace this code :
 ```
get ViewPropTypes(): $FlowFixMe {
    invariant(
      false,
      'ViewPropTypes has been removed from React Native. Migrate to ' +
        "ViewPropTypes exported from 'deprecated-react-native-prop-types'.",
    );
  }
```
to this:
  ```
get ViewPropTypes(): $FlowFixMe {
    console.warn(
      'ViewPropTypes has been removed from React Native. Migrate to ' +
        "ViewPropTypes exported from 'deprecated-react-native-prop-types'.",
    );

    return require('deprecated-react-native-prop-types')
  }
```


happy coding !

**Comment by gabriellend** [comment]
I'm seeing this too, any updates? Is the above solution ok to do? Thanks!
