### ISSUE TITLE
[iOS] Undefined symbols for architecture arm64: "_RCTSharedApplication"

### ISSUE THREAD

**Issue by vitalbone** [facebook/react-native#3470]
Having similar problems to #2685 , however disabling 'Dead Code stripping' isn't solving the issue. Any help would be greatly appreciated.

El Capitan 10.11.1 (15B30a)
Xcode 7.0.1 (7A1001)
iPad (9.0.2) (13A452)

**Comment by christopherdro** [comment]
@vitalbone Try cleaning out your build and double checking that you restarted the packager. If that fails, try restarting your whole computer and see if that changes anything.

**Comment by vitalbone** [comment]
thanks @christopherdro but no luck with clean build, restarted package manager and/or a whole system restart. same error still persisting.

it builds on a simulated iPad (Retina / iOS 9.0) however the red screen of death appears with _No such file or directory_ . any link between the 2 errors?

**Comment by christopherdro** [comment]
@vitalbone Strange that it didn't work.

This might help you with your other issue.
https://github.com/facebook/react-native/issues/3174#issuecomment-145329802

**Comment by vitalbone** [comment]
Ok, was able to get it working on the simulator by following #3174. Guess that'll have to do for now. Thanks again @christopherdro for all your help.
