### ISSUE TITLE
Failed to call into JavaScript module method AppRegistry

### ISSUE THREAD

**Issue by Bayramito** [facebook/react-native#34706]
### Description

<img width="1209" alt="Ekran Resmi 2022-09-16 09 58 08" src="https://user-images.githubusercontent.com/44513402/190576150-ccd13a80-7e4e-48df-91de-f359c72f79c2.png">

I still get these errors even i patched with deprecated-react-native-prop-types

### Version

0.70.1

### Output of `npx react-native info`

System:
    OS: macOS 12.5.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 2.24 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.20.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 6.14.17 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK:
      API Levels: 29, 30, 31, 33
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 33.0.0
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-31 | Google APIs Intel x86 Atom_64
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 14.0/14A309 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.14 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.1 => 0.70.1
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

none

### Snack, code example, screenshot, or link to a repository

none

**Comment by efstathiosntonas** [comment]
Are you sure that you have patched all `node_modules` using it?

This should return all the found `ViewPropTypes` in your `node_modules` (including the patched ones):

`grep -F "ViewPropTypes" -l -r ./node_modules`

**Comment by Bayramito** [comment]
> grep -F "ViewPropTypes" -l -r ./node_modules

so is there any way to patch them all  at once or i should patch them one by one?

**Comment by efstathiosntonas** [comment]
the safest way is to patch them one by one imo

**Comment by rickhanlonii** [comment]
@Bayramito are you sure this error is related to patching the package?

Patching the package is _not_ the recommended solution for fixing the deprecated proptypes error. Before patching the packages, could you try to find the libraries you're using that are using the proptypes? What's the output of the grep command @efstathiosntonas shared?

**Comment by rickhanlonii** [comment]
I see, so this error can be shown if a package throws an error based on using deprecated types, but your error message is missing the original error that was throw. Can you confirm that error is present like @efstathiosntonas mentioned here? https://github.com/facebook/react-native/issues/34688#issuecomment-1249105861

**Comment by baedyl** [comment]
@cortinico I'm facing the same issue, I run the command you shared and here is the result:
`grep -F "ViewPropTypes" -l -r ./node_modules
./node_modules/@react-native-picker/picker/js/PickerIOS.ios.js
./node_modules/@react-native-picker/picker/js/PickerMacOS.macos.js
./node_modules/@react-native-picker/picker/dist/commonjs/PickerIOS.ios.js.map
./node_modules/@react-native-picker/picker/dist/commonjs/PickerMacOS.macos.js.map
./node_modules/@react-native-picker/picker/dist/module/PickerIOS.ios.js.map
./node_modules/@react-native-picker/picker/dist/module/PickerMacOS.macos.js.map
./node_modules/expo-modules-core/CHANGELOG.md
./node_modules/react-native/Libraries/Image/ImageBackground.js
./node_modules/react-native/Libraries/Image/ImageProps.js
./node_modules/react-native/Libraries/Image/ImageViewNativeComponent.js
./node_modules/react-native/Libraries/Image/TextInlineImageNativeComponent.js
./node_modules/react-native/Libraries/Components/ProgressBarAndroid/ProgressBarAndroid.android.js
./node_modules/react-native/Libraries/Components/ProgressBarAndroid/ProgressBarAndroidNativeComponent.js
./node_modules/react-native/Libraries/Components/Slider/Slider.js
./node_modules/react-native/Libraries/Components/Slider/SliderNativeComponent.js
./node_modules/react-native/Libraries/Components/DrawerAndroid/AndroidDrawerLayoutNativeComponent.js
./node_modules/react-native/Libraries/Components/View/ViewNativeComponent.js
./node_modules/react-native/Libraries/Components/View/View.js
./node_modules/react-native/Libraries/Components/ProgressViewIOS/RCTProgressViewNativeComponent.js
./node_modules/react-native/Libraries/Components/ProgressViewIOS/ProgressViewIOS.ios.js
./node_modules/react-native/Libraries/Components/UnimplementedViews/UnimplementedNativeViewNativeComponent.js
./node_modules/react-native/Libraries/Components/RefreshControl/AndroidSwipeRefreshLayoutNativeComponent.js
./node_modules/react-native/Libraries/Components/RefreshControl/PullToRefreshViewNativeComponent.js
./node_modules/react-native/Libraries/Components/RefreshControl/RefreshControl.js
./node_modules/react-native/Libraries/Components/MaskedView/MaskedViewIOS.ios.js
./node_modules/react-native/Libraries/Components/MaskedView/RCTMaskedViewNativeComponent.js
./node_modules/react-native/Libraries/Components/Switch/Switch.js
./node_modules/react-native/Libraries/Components/Switch/AndroidSwitchNativeComponent.js
./node_modules/react-native/Libraries/Components/Switch/SwitchNativeComponent.js
./node_modules/react-native/Libraries/Components/Keyboard/KeyboardAvoidingView.js
./node_modules/react-native/Libraries/Components/ScrollView/ScrollViewNativeComponentType.js
./node_modules/react-native/Libraries/Components/ScrollView/AndroidHorizontalScrollContentViewNativeComponent.js
./node_modules/react-native/Libraries/Components/ScrollView/ScrollView.js
./node_modules/react-native/Libraries/Components/ScrollView/ScrollContentViewNativeComponent.js
./node_modules/react-native/Libraries/Components/SafeAreaView/SafeAreaView.js
./node_modules/react-native/Libraries/Components/SafeAreaView/RCTSafeAreaViewNativeComponent.js
./node_modules/react-native/Libraries/Components/TextInput/RCTInputAccessoryViewNativeComponent.js
./node_modules/react-native/Libraries/Components/TextInput/TextInput.js
./node_modules/react-native/Libraries/Components/TextInput/AndroidTextInputNativeComponent.js
./node_modules/react-native/Libraries/Components/ActivityIndicator/ActivityIndicator.js
./node_modules/react-native/Libraries/Components/ActivityIndicator/ActivityIndicatorViewNativeComponent.js
./node_modules/react-native/Libraries/Components/DatePicker/RCTDatePickerNativeComponent.js
./node_modules/react-native/Libraries/Components/DatePicker/DatePickerIOS.ios.js
./node_modules/react-native/Libraries/Modal/Modal.js
./node_modules/react-native/Libraries/Modal/RCTModalHostViewNativeComponent.js
./node_modules/react-native/index.js
./node_modules/react-native/CHANGELOG.md
./node_modules/react-native-codegen/lib/parsers/flow/components/__test_fixtures__/fixtures.js
./node_modules/react-native-codegen/lib/parsers/flow/components/__test_fixtures__/failures.js
./node_modules/react-native-codegen/lib/parsers/flow/components/__test_fixtures__/fixtures.js.flow
./node_modules/react-native-codegen/lib/parsers/flow/components/__test_fixtures__/failures.js.flow
./node_modules/react-native-codegen/lib/parsers/typescript/components/__test_fixtures__/fixtures.js
./node_modules/react-native-codegen/lib/parsers/typescript/components/__test_fixtures__/failures.js
./node_modules/react-native-codegen/lib/parsers/typescript/components/__test_fixtures__/fixtures.js.flow
./node_modules/react-native-codegen/lib/parsers/typescript/components/__test_fixtures__/failures.js.flow
./node_modules/react-native-button/Button.js
./node_modules/react-native-fast-image/dist/index.js.flow
./node_modules/react-native-fast-image/dist/index.cjs.js.flow
./node_modules/babel-preset-expo/node_modules/metro-react-native-babel-preset/src/configs/lazy-imports.js`

How can I fixed this please ?

**Comment by mantegnous** [comment]
same problem here how to resolve?

**Comment by chernandezlt** [comment]
same problem here, I've implemented some solutions that I've found but nothing happens, any solutions?

**Comment by burhankaraman** [comment]
+1

**Comment by jamninetyfive** [comment]
+1

**Comment by jui9266** [comment]
+1
