### ISSUE TITLE
Font-feature-settings

### ISSUE THREAD

**Issue by pepsi-cola-vodka-hortiza** [facebook/react-native#34709]
### Description

Please add **font-feature-settings** for text style in react native

### Version

0.66.0

### Output of `npx react-native info`

System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 AMD Ryzen 7 PRO 4750U with Radeon Graphics
    Memory: 714.48 MB / 15.23 GB
  Binaries:
    Node: 16.13.2 - C:\Program Files\nodejs\node.EXE        
    Yarn: Not Found
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version     2021.1.0.0 AI-211.7628.21.2111.8309675
    Visual Studio: Not Found
  Languages:
    Java: javac 11 - C:\Program Files\Java\openjdk-11+28_windows-x64_bin\jdk-11\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.66.0 => 0.66.0
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

.

### Snack, code example, screenshot, or link to a repository

**what is meant:** https://developer.mozilla.org/en-US/docs/Web/CSS/font-feature-settings

**Comment by pke** [comment]
Much overdue feature. RN has partial support for setting font features internally but those APIs are not exposed from what I gathered so far. 
Maybe this could also be done in a separate package. The package just would need to make the font available to the RN typography system.

**Comment by bsheikh** [comment]
Is there an alternative solution in the meantime to achieve this?

**Comment by richcahill** [comment]
Bumping this issue.

Has anyone found an interim fix?

**Comment by pke** [comment]
This seems to be supported now https://github.com/facebook/react-native/pull/36740 just not documented.
