### ISSUE TITLE
Linking.addEventListener not working: url event never fires

### ISSUE THREAD

**Issue by leoparis89** [facebook/react-native#34701]
### Description

[Url event](https://reactnative.dev/docs/linking#addeventlistener) never fires

I followed the [indicated setup](https://reactnative.dev/docs/linking) to handle deep links in react native.

But when I have the app open in background or foreground and I execute command
`npx uri-scheme open "mychat://bar" --ios`, url event doesn't fire.

I saw there is a [similar issue in react-navigation](https://stackoverflow.com/questions/48188808/react-native-deep-link-event-listener-not-firing), but the fix indicated for AppDelegate.m doesn't work for me.

### Version

0.76

### Output of `npx react-native info`

System:
    OS: macOS 12.5.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 1.30 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.1 - /usr/local/opt/node@16/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 8.19.2 - /usr/local/opt/node@16/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK:
      API Levels: 28, 31, 33
      Build Tools: 30.0.2, 31.0.0, 33.0.0
      System Images: android-31 | Google APIs Intel x86 Atom_64, android-31 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8815526
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 13.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.6 => 0.70.6
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

clone repo https://github.com/leoparis89/deeplink

1. yarn
2. cd ios && pod install
3. yarn ios
4. put app in background
5. run command `npx uri-scheme open "mychat://bar" --ios`.
   App gets focused but url event never fires in `./App.js` line 121.

### Snack, code example, screenshot, or link to a repository

https://github.com/leoparis89/deeplink

**Comment by ariel-bentu** [comment]
I want to add to this issue what I researched, having similar issue:
- When the app is not running at all, and you select "share/open with" your app the following happens:
  - First, the `(BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions` is called, having the path to the file in the launch options under "UIApplicationLaunchOptionsURLKey" key.
    This path is not accessible (permission-wise to the app).
    This path is also what you'd get if you call Linking.getInitialURL
  - Then, the `(BOOL)application:(UIApplication *)application   openURL:(NSURL *)url   options:...` is called.
     This method receives a different URL, which is a copy of the file in your app's temp/inbox folder - fully accessible to your app. 
     And as suggested, it is implemented with one line: `return [RCTLinkingManager application:application openURL:url options:options];`, which triggers RCTLinkingManager to send notification via NSNotificationCenter with that (good) url. 
     **Now comes the issue**: at this point in time, the JS was not yet started and the JS part of the app did not register to listen to "url" event. That is why RCTEventEmitter did not call `RCTLinkingManager.startObserving` and the notification with the url is lost. and even if it would have been received, the JS did not register yet, and it would not have been fired to the JS part.


Here is how I solved it (and I suggest you implement something more generic/robust for Linking:
- when `RCTLinkingManager application:application openURL:url options:options` is called, I save the url in a object's local variable. the when `RCTLinkingManager.startObserving` is called, if this variable is not nil, I fire the url event.

- line 19: `static NSString *savedEvent = nil;`
at startObserving, at its end:
```
if (savedEvent != nil) {
        NSDictionary<NSString *, id> *payload = @{@"url": savedEvent};
        [self sendEventWithName:@"url" body:payload];
        savedEvent = nil;
    }
```

at application:openURL:options
```
    // if event was missed, save it for later firing
    savedEvent = URL.absoluteString;
```

I hope this helps.

**Comment by leoparis89** [comment]
> I want to add to this issue what I researched, having similar issue:
> 
> * When the app is not running at all, and you select "share/open with" your app the following happens:
>   
>   * First, the `(BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions` is called, having the path to the file in the launch options under "UIApplicationLaunchOptionsURLKey" key.
>     This path is not accessible (permission-wise to the app).
>     This path is also what you'd get if you call Linking.getInitialURL
>   * Then, the `(BOOL)application:(UIApplication *)application   openURL:(NSURL *)url   options:...` is called.
>     This method receives a different URL, which is a copy of the file in your app's temp/inbox folder - fully accessible to your app.
>     And as suggested, it is implemented with one line: `return [RCTLinkingManager application:application openURL:url options:options];`, which triggers RCTLinkingManager to send notification via NSNotificationCenter with that (good) url.
>     **Now comes the issue**: at this point in time, the JS was not yet started and the JS part of the app did not register to listen to "url" event. That is why RCTEventEmitter did not call `RCTLinkingManager.startObserving` and the notification with the url is lost. and even if it would have been received, the JS did not register yet, and it would not have been fired to the JS part.
> 
> Here is how I solved it (and I suggest you implement something more generic/robust for Linking:
> 
> * when `RCTLinkingManager application:application openURL:url options:options` is called, I save the url in a object's local variable. the when `RCTLinkingManager.startObserving` is called, if this variable is not nil, I fire the url event.
> * line 19: `static NSString *savedEvent = nil;`
>   at startObserving, at its end:
> 
> ```
> if (savedEvent != nil) {
>         NSDictionary<NSString *, id> *payload = @{@"url": savedEvent};
>         [self sendEventWithName:@"url" body:payload];
>         savedEvent = nil;
>     }
> ```
> 
> at application:openURL:options
> 
> ```
>     // if event was missed, save it for later firing
>     savedEvent = URL.absoluteString;
> ```
> 
> I hope this helps.

Could you specify in which file those modifications need to be made ?
Ideally could you also post a snippet of the modified code ?

Haven't been able to reproduce your instructions.
Thanks

**Comment by ariel-bentu** [comment]
The file is `react-native/Libraries/LinkingIOS/RCTLinkingManager.mm`
```
#import <React/RCTLinkingManager.h>

#import <FBReactNativeSpec/FBReactNativeSpec.h>
#import <React/RCTBridge.h>
#import <React/RCTUtils.h>
#import <React/RCTLog.h>

#import "RCTLinkingPlugins.h"

static NSString *const kOpenURLNotification = @"RCTOpenURLNotification";

static NSString *savedEvent = nil;
```

```
- (void)startObserving
{
    [[NSNotificationCenter defaultCenter] addObserver:self
                                             selector:@selector(handleOpenURLNotification:)
                                                 name:kOpenURLNotification
                                               object:nil];
    if (savedEvent != nil) {
        NSDictionary<NSString *, id> *payload = @{@"url": savedEvent};
        [self sendEventWithName:@"url" body:payload];
        savedEvent = nil;
    }
}
```
```
+ (BOOL)application:(UIApplication *)app
            openURL:(NSURL *)URL
            options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{
    postNotificationWithURL(URL, self);
    
    // if event was missed, save for firing later if event "url" is registered
    savedEvent = URL.absoluteString;
    
    return YES;
}
```

**Comment by edwardhsueh** [comment]
@ariel-bentu 
I try you solution , but url event doesn't fire when I have the app open in background or foreground. 
(when app closed , it's ok).
Do you have any suggestion ?

**Comment by ariel-bentu** [comment]
do you have this method added in your `AppDelegate.mm`:
```
- (BOOL)application:(UIApplication *)application
   openURL:(NSURL *)url
   options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{
  return [RCTLinkingManager application:application openURL:url options:options];
}
```

This is a prerequisite, also documented by react native (see [here](https://reactnative.dev/docs/linking))

**Comment by edwardhsueh** [comment]
Yes, I do follow the document but still fail. I can't run in simulator, so I use browser with button to call the url scheme. 
if app is closed, it works fine. But if app is in background, the url scheme called just bring app to foreground, but the url listener is not fired.
My RN is 0.68.2, older than yours. Will this be a problem?

**Comment by vickfan** [comment]
Hi @edwardhsueh, I was using react native 0.68.0 and facing the same problem 
One thing that you can try is adding the below code to the location that specified by [React Navigation Documentation](https://reactnavigation.org/docs/deep-linking)
as I am not familiar with Swift and placing the code in the wrong location
```swift
// Add the header at the top of the file:
#import <React/RCTLinkingManager.h>

// Add this inside `@implementation AppDelegate` above `@end`:
- (BOOL)application:(UIApplication *)application
   openURL:(NSURL *)url
   options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{
  return [RCTLinkingManager application:application openURL:url options:options];
}
```
It's working for me now

**Comment by leoparis89** [comment]
> 

Unfortunately this is not working for me.

I modified RTCLinkingManager.mm as follows:
```

/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

#import <React/RCTLinkingManager.h>

#import <FBReactNativeSpec/FBReactNativeSpec.h>
#import <React/RCTBridge.h>
#import <React/RCTUtils.h>
#import <React/RCTLog.h>

#import "RCTLinkingPlugins.h"

static NSString *const kOpenURLNotification = @"RCTOpenURLNotification";

static NSString *savedEvent = nil;

static void postNotificationWithURL(NSURL *URL, id sender)
{
  NSDictionary<NSString *, id> *payload = @{@"url": URL.absoluteString};
  [[NSNotificationCenter defaultCenter] postNotificationName:kOpenURLNotification
                                                      object:sender
                                                    userInfo:payload];
}

@interface RCTLinkingManager() <NativeLinkingManagerSpec>
@end

@implementation RCTLinkingManager

RCT_EXPORT_MODULE()

- (dispatch_queue_t)methodQueue
{
  return dispatch_get_main_queue();
}

- (void)startObserving
{
  [[NSNotificationCenter defaultCenter] addObserver:self
                                           selector:@selector(handleOpenURLNotification:)
                                               name:kOpenURLNotification
                                             object:nil];

    if (savedEvent != nil) {
        NSDictionary<NSString *, id> *payload = @{@"url": savedEvent};
        [self sendEventWithName:@"url" body:payload];
        savedEvent = nil;
    }
}

- (void)stopObserving
{
  [[NSNotificationCenter defaultCenter] removeObserver:self];
}

- (NSArray<NSString *> *)supportedEvents
{
  return @[@"url"];
}

+ (BOOL)application:(UIApplication *)app
            openURL:(NSURL *)URL
            options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{
  postNotificationWithURL(URL, self);

  // if event was missed, save for firing later if event "url" is registered
  savedEvent = URL.absoluteString;

  return YES;
}

// Corresponding api deprecated in iOS 9
+ (BOOL)application:(UIApplication *)application
            openURL:(NSURL *)URL
  sourceApplication:(NSString *)sourceApplication
         annotation:(id)annotation
{
  postNotificationWithURL(URL, self);
  return YES;
}

+ (BOOL)application:(UIApplication *)application
continueUserActivity:(NSUserActivity *)userActivity
  restorationHandler:
    #if defined(__IPHONE_OS_VERSION_MAX_ALLOWED) && (__IPHONE_OS_VERSION_MAX_ALLOWED >= 12000) /* __IPHONE_12_0 */
        (nonnull void (^)(NSArray<id<UIUserActivityRestoring>> *_Nullable))restorationHandler {
    #else
        (nonnull void (^)(NSArray *_Nullable))restorationHandler {
    #endif
  if ([userActivity.activityType isEqualToString:NSUserActivityTypeBrowsingWeb]) {
    NSDictionary *payload = @{@"url": userActivity.webpageURL.absoluteString};
    [[NSNotificationCenter defaultCenter] postNotificationName:kOpenURLNotification
                                                        object:self
                                                      userInfo:payload];
  }
  return YES;
}

- (void)handleOpenURLNotification:(NSNotification *)notification
{
  [self sendEventWithName:@"url" body:notification.userInfo];
}

RCT_EXPORT_METHOD(openURL:(NSURL *)URL
                  resolve:(RCTPromiseResolveBlock)resolve
                  reject:(RCTPromiseRejectBlock)reject)
{
  [RCTSharedApplication() openURL:URL options:@{} completionHandler:^(BOOL success) {
    if (success) {
      resolve(@YES);
    } else {
      #if TARGET_OS_SIMULATOR
        // Simulator-specific code
        if([URL.absoluteString hasPrefix:@"tel:"]){
          RCTLogWarn(@"Unable to open the Phone app in the simulator for telephone URLs. URL:  %@", URL);
          resolve(@NO);
        } else {
          reject(RCTErrorUnspecified, [NSString stringWithFormat:@"Unable to open URL: %@", URL], nil);
        }
      #else
        // Device-specific code
        reject(RCTErrorUnspecified, [NSString stringWithFormat:@"Unable to open URL: %@", URL], nil);
      #endif
    }
  }];
}

RCT_EXPORT_METHOD(canOpenURL:(NSURL *)URL
                  resolve:(RCTPromiseResolveBlock)resolve
                  reject:(__unused RCTPromiseRejectBlock)reject)
{
  if (RCTRunningInAppExtension()) {
    // Technically Today widgets can open urls, but supporting that would require
    // a reference to the NSExtensionContext
    resolve(@NO);
    return;
  }

  // This can be expensive, so we deliberately don't call on main thread
  BOOL canOpen = [RCTSharedApplication() canOpenURL:URL];
  NSString *scheme = [URL scheme];
  if (canOpen) {
    resolve(@YES);
  } else if (![[scheme lowercaseString] hasPrefix:@"http"] && ![[scheme lowercaseString] hasPrefix:@"https"]) {
    // On iOS 9 and above canOpenURL returns NO without a helpful error.
    // Check if a custom scheme is being used, and if it exists in LSApplicationQueriesSchemes
    NSArray *querySchemes = [[NSBundle mainBundle] objectForInfoDictionaryKey:@"LSApplicationQueriesSchemes"];
    if (querySchemes != nil && ([querySchemes containsObject:scheme] || [querySchemes containsObject:[scheme lowercaseString]])) {
      resolve(@NO);
    } else {
      reject(RCTErrorUnspecified, [NSString stringWithFormat:@"Unable to open URL: %@. Add %@ to LSApplicationQueriesSchemes in your Info.plist.", URL, scheme], nil);
    }
  } else {
    resolve(@NO);
  }
}

RCT_EXPORT_METHOD(getInitialURL:(RCTPromiseResolveBlock)resolve
                  reject:(__unused RCTPromiseRejectBlock)reject)
{
  NSURL *initialURL = nil;
  if (self.bridge.launchOptions[UIApplicationLaunchOptionsURLKey]) {
    initialURL = self.bridge.launchOptions[UIApplicationLaunchOptionsURLKey];
  } else {
    NSDictionary *userActivityDictionary =
      self.bridge.launchOptions[UIApplicationLaunchOptionsUserActivityDictionaryKey];
    if ([userActivityDictionary[UIApplicationLaunchOptionsUserActivityTypeKey] isEqual:NSUserActivityTypeBrowsingWeb]) {
      initialURL = ((NSUserActivity *)userActivityDictionary[@"UIApplicationLaunchOptionsUserActivityKey"]).webpageURL;
    }
  }
  resolve(RCTNullIfNil(initialURL.absoluteString));
}

RCT_EXPORT_METHOD(openSettings:(RCTPromiseResolveBlock)resolve
                  reject:(__unused RCTPromiseRejectBlock)reject)
{
  NSURL *url = [NSURL URLWithString:UIApplicationOpenSettingsURLString];
  [RCTSharedApplication() openURL:url options:@{} completionHandler:^(BOOL success) {
    if (success) {
      resolve(nil);
    } else {
      reject(RCTErrorUnspecified, @"Unable to open app settings", nil);
    }
  }];
}

RCT_EXPORT_METHOD(sendIntent:(NSString *)action
                  extras:(NSArray *_Nullable)extras
                  resolve:(RCTPromiseResolveBlock)resolve
                  reject:(RCTPromiseRejectBlock)reject)
{
  RCTLogError(@"Not implemented: %@", NSStringFromSelector(_cmd));
}

- (std::shared_ptr<facebook::react::TurboModule>)getTurboModule:(const facebook::react::ObjCTurboModule::InitParams &)params
{
  return std::make_shared<facebook::react::NativeLinkingManagerSpecJSI>(params);
}

@end

Class RCTLinkingManagerCls(void) {
  return RCTLinkingManager.class;
}

```

**Comment by leoparis89** [comment]
> The file is `react-native/Libraries/LinkingIOS/RCTLinkingManager.mm`
> 
> ```
> #import <React/RCTLinkingManager.h>
> 
> #import <FBReactNativeSpec/FBReactNativeSpec.h>
> #import <React/RCTBridge.h>
> #import <React/RCTUtils.h>
> #import <React/RCTLog.h>
> 
> #import "RCTLinkingPlugins.h"
> 
> static NSString *const kOpenURLNotification = @"RCTOpenURLNotification";
> 
> static NSString *savedEvent = nil;
> ```
> 
> ```
> - (void)startObserving
> {
>     [[NSNotificationCenter defaultCenter] addObserver:self
>                                              selector:@selector(handleOpenURLNotification:)
>                                                  name:kOpenURLNotification
>                                                object:nil];
>     if (savedEvent != nil) {
>         NSDictionary<NSString *, id> *payload = @{@"url": savedEvent};
>         [self sendEventWithName:@"url" body:payload];
>         savedEvent = nil;
>     }
> }
> ```
> 
> ```
> + (BOOL)application:(UIApplication *)app
>             openURL:(NSURL *)URL
>             options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
> {
>     postNotificationWithURL(URL, self);
>     
>     // if event was missed, save for firing later if event "url" is registered
>     savedEvent = URL.absoluteString;
>     
>     return YES;
> }
> ```

This solution is not working for me either.

I added the lines you described in RTCLinkingManager.mm.
I added the lines in AppDelegate.mm as instructed in [RN Linking docs](https://reactnative.dev/docs/linking).

Is there possibly some extra setup to do ?

I find it surprising that a major feature like deeplinking is currently broken.
Any clue on a possible workaround ?

**Comment by edwardhsueh** [comment]
Hi, 
Finally, I found that linking works correctly on iOS/android when I upgrade react-native from 0.68 to 0.70.1 and follow the setting requirement for Linking

**Comment by leoparis89** [comment]
> Hi, Finally, I found that linking works correctly on iOS/android when I upgrade react-native from 0.68 to 0.70.1 and follow the setting requirement for Linking

Could you post a link to a repo with the working config ?
I tried the specific version 0.70.1 and url event still doesn't fire if app is open in background.

**Comment by edwardhsueh** [comment]
@leoparis89 :    
the following is my react related repo.  
  "react": "18.1.0",
 "react-native": "0.70.1",
 I have url event fired in background by using
using Linking.addEventListener('url', callback)

**Comment by har2008preet** [comment]
working in android but only in killed state in iOS, very frustrating issue. do not know how to debug it.

**Comment by SerafinAna** [comment]
Do we have some update?
I have same problem.Working on android in killed state and background on iOS doesn't work in background.
My enviroment is :
 "react": "18.0.0",
 "react-native": "0.70.6"
 I use also some firebase packeges like (react-native-firebase/auth,react-native-firebase/app...) could this be a problem?

**Comment by leoparis89** [comment]
Solved. It was an error on my part:

**the bellow snippet must be added in @implementatione AppDelegat not @interface AppDelegate** 

    // For deep links
    - (BOOL)application:(UIApplication *)application
       openURL:(NSURL *)url
       options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
    {
      return [RCTLinkingManager application:application openURL:url options:options];
    }
    // For universal links
    - (BOOL)application:(UIApplication *)application continueUserActivity:(nonnull NSUserActivity *)userActivity
     restorationHandler:(nonnull void (^)(NSArray<id<UIUserActivityRestoring>> * _Nullable))restorationHandler
    {
     return [RCTLinkingManager application:application
                      continueUserActivity:userActivity
                        restorationHandler:restorationHandler];
    }

**Comment by SerafinAna** [comment]
Solved. It was error in my project. After upgrade of React Native version, I forgot to delete old settings file for iOS. (AppDelegat.m)
So, in project were AppDelegat.m and AppDelegat.mm. New version of React Native needs file with new extension .mm instead of .m and this caused problems with deep linking. When I removed old file with extension .m and move all logic for deep linking in file with extension .mm I got BINGO !!!

**Comment by LayMui** [comment]
@SerafinAna I upgrade to RN 0.71.6 and move the deep linking code from AppDelegate.m to AppDelegate.mm
but the link is still unable to open
i got this

 Error opening URL:  [Error: Unable to open URL: com.xxxxx://dev-xx.com/ios/com.xxxxx/login-callback?code=xxxxx. Add com.xxxxx to LSApplicationQueriesSchemes in your Info.plist.]


here is my AppDelegate.mm in case I missed out anything

```
#import "AppDelegate.h"

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import <React/RCTLinkingManager.h>


@implementation AppDelegate

- (BOOL)application:(UIApplication *)app
            openURL:(NSURL *)url
            options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{
  return [RCTLinkingManager application:app
                                openURL:url
                                options:options];
}

// For universal links
- (BOOL)application:(UIApplication *)application continueUserActivity:(nonnull NSUserActivity *)userActivity
 restorationHandler:(nonnull void (^)(NSArray<id<UIUserActivityRestoring>> * _Nullable))restorationHandler
{
 return [RCTLinkingManager application:application
                  continueUserActivity:userActivity
                    restorationHandler:restorationHandler];
}


- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  self.moduleName = @"nativeIntegration";
  // You can add your custom initial props in the dictionary below.
  // They will be passed down to the ViewController used by React Native.
  self.initialProps = @{};

  return [super application:application didFinishLaunchingWithOptions:launchOptions];
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index"];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

/// This method controls whether the `concurrentRoot`feature of React18 is turned on or off.
///
/// @see: https://reactjs.org/blog/2022/03/29/react-v18.html
/// @note: This requires to be rendering on Fabric (i.e. on the New Architecture).
/// @return: `true` if the `concurrentRoot` feature is enabled. Otherwise, it returns `false`.
- (BOOL)concurrentRootEnabled
{
  return true;
}

@end

```

**Comment by LayMui** [comment]
@ariel-bentu  how can you modified the library node_modules/react-native/Libraries/LinkingIOS/RCTLinkingManager.mm

this file will be restored when I run yarn 

anyway, it will cause this build error in xcode
Use of undeclared identifier 'savedEvent'


so this is deep linking broken issue is still an issue in react native 
I am using

 "react": "18.2.0",
    "react-native": "^0.71.6",

**Comment by pyrsmk** [comment]
We're affected as well by the bug.

**Comment by LayMui** [comment]
can we reopen this issue? this issue is not resolved yet

**Comment by aiwahchong** [comment]
I also faced the same problem. In Android works but in iOS Linking.addEventListener is not working.

My RN Version: "0.70.6"

**Comment by LayMui** [comment]
I manage to get it work on iOS
need to add the url to the xcode setting refer to 
    https://reactnavigation.org/docs/deep-linking/

**Comment by moustaouiSalaheddine** [comment]
if you use `react native +0.71 `

change  `AppDelegate.m` to  `AppDelegate.mm`

```
// Add the header at the top of the file:
#import <React/RCTLinkingManager.h>

// Add this inside `@implementation AppDelegate` above `@end`:
- (BOOL)application:(UIApplication *)application
   openURL:(NSURL *)url
   options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{
  return [RCTLinkingManager application:application openURL:url options:options];
}
// Add this inside `@implementation AppDelegate` above `@end`:
- (BOOL)application:(UIApplication *)application continueUserActivity:(nonnull NSUserActivity *)userActivity
 restorationHandler:(nonnull void (^)(NSArray<id<UIUserActivityRestoring>> * _Nullable))restorationHandler
{
 return [RCTLinkingManager application:application
                  continueUserActivity:userActivity
                    restorationHandler:restorationHandler];
}
```

**Comment by DenisBakh** [comment]
I have the same issue on android - Linking.addEventListener('url', callback) doesn't fire callback when the app in background.
"expo": "~48.0.18",
"react-native": "0.71.8",
"react": "18.2.0"

Does anyone have decision?

**Comment by Faisalnawaz953** [comment]
after trying all of the solutions this worked for me [solution](https://stackoverflow.com/a/74941214/17132874)

**Comment by AbhaySensation** [comment]
I m facing the same issue too . 

Steps to fix this problem :

1 . Made the changes in appdelegate.mm file and if the react native version > .71 for reference you can check React Native documentation. 
2. Use addEventListener in case if you are using addListener. 
3 . Rebuild your app 
Thanks
