### ISSUE TITLE
[Image] new image source will stuck to the old source if scaled (working in 0.11)

### ISSUE THREAD

**Issue by ms88privat** [facebook/react-native#3471]
The bug appears when you are trying to change the source of the `<Image />` .
It will stuck with the old source if 
- the style property of the `<Image />` is scaled
- and the new source has different dimensions (like landscape vs portrait or size)
      	
e.g. like changing a scaled landscape picture to another portrait picture 

copy the working playground version (v 0.11.0) to an 0.13.0-rc project and see this happen after the 4th cameraRoll picture change ~
https://rnplay.org/apps/Sp38_g

maybe related to https://github.com/facebook/react-native/issues/3460

**Comment by aroth** [comment]
@ms88privat Looks like the image is being cached at some level. @nicklockwood might know whether it's a bug or a feature in this situation. 

For a fix, set a key on the `<Image>` component:

```
      return (
        <TouchableOpacity style={styles.container} onPress={this._changePhoto.bind(this)}>
          <Image 
            key={ images[selected].uri }
            source={{uri: images[selected].uri}} 
      			style={imageSize}
            > 
          </Image>
        </TouchableOpacity>
    	);
```

**Comment by ms88privat** [comment]
@aroth thanks, this helped.

**Comment by browniefed** [comment]
@facebook-github-bot close

**Comment by Eyesonly88** [comment]
Without adding a key property to the Image on android, the updated image URI won't take effect. 

As @aroth mentioned: "Looks like the image is being cached at some level" -- how do we disable this caching for Android (so that the additional key property is not needed) ?

I'm using React Native 0.39 and this bug still exists.
