### ISSUE TITLE
The following build commands failed: PhaseScriptExecution Bundle\ React\ Native\ code\ and\ images /Users/runner/Library/Developer/Xcode/DerivedData

### ISSUE THREAD

**Issue by TonyFTannous** [facebook/react-native#34717]
### Description

Hello, i need help

in my mac using xcode 13.4.1, everything go well, but when publishing using azure/pipeline, the build failed
after the azure update (Updating readme file for macOS-11 version 20220906.1)
but before the update of azure everything go well and no build failed

The following build commands failed:
PhaseScriptExecution Bundle\ React\ Native\ code\ and\ images /Users/runner/Library/Developer/Xcode/DerivedData/myproject-hfznzxvrsqgfuzajavqfcfjkopph/Build/Intermediates.noindex/myproject.build/Dev-iphoneos/myproject-IOS.build/Script-00DD1BFF1BD5951E006B06BC.sh

please any help

### Version

0.64.3

### Output of `npx react-native info`

Pool: [Azure Pipelines]
Image: macOS-11
Agent: Azure Pipelines 3

### Steps to reproduce

Hello, i need help

in my mac using xcode 13.4.1, everything go well, but when publishing using azure/pipeline, the build failed
after the azure update (Updating readme file for macOS-11 version 20220906.1)
but before the update of azure everything go well and no build failed

The following build commands failed:
PhaseScriptExecution Bundle\ React\ Native\ code\ and\ images /Users/runner/Library/Developer/Xcode/DerivedData/myproject-hfznzxvrsqgfuzajavqfcfjkopph/Build/Intermediates.noindex/myproject.build/Dev-iphoneos/myproject-IOS.build/Script-00DD1BFF1BD5951E006B06BC.sh

please any help

### Snack, code example, screenshot, or link to a repository

...

**Comment by TonyFTannous** [comment]
Please, any update???

**Comment by cortinico** [comment]
> 0.64.3

You're on a tool old version of React Native. Please consider updating to 0.68 or later version and get back to us as it's impossible to help you right now.

**Comment by AsteriskZuo** [comment]
> > 0.64.3
> 
> You're on a tool old version of React Native. Please consider updating to 0.68 or later version and get back to us as it's impossible to help you right now.

0.64.3 A lot of people use it again

**Comment by AsteriskZuo** [comment]
My version 0.66.4 also has this problem.
