### ISSUE TITLE
Passing a multi-element array to Image causes a crash on Android

### ISSUE THREAD

**Issue by filipecatraia** [facebook/react-native#34711]
### Description

Hey RN maintainers,

[I've made a repo with this one](https://github.com/flowchase/break-image-component), which I hope is reproducible. The crash happens at least on Android Emulator, but we've also reproduced it on a Pixel 5. The repo was created with `expo`, but I'm not sure if that makes much of a difference.

The error message is `Error while updating property 'src' of a view managed by: RCTImageView`.

I've also [posted this question on StackOverflow](https://stackoverflow.com/questions/73743701/react-native-error-while-updating-property-src-of-a-view-managed-by-rctimagevie), as it might be a mistake on my end instead of an actual bug.

### Version

0.69.5

### Output of `npx react-native info`

```sh
info Fetching system and libraries information...
System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1
    Memory: 775.95 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.7.0 - ~/.nvm/versions/node/v18.7.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.7.0/bin/yarn
    npm: 8.18.0 - ~/.nvm/versions/node/v18.7.0/bin/npm
    Watchman: 2022.07.04.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8815526
    Xcode: 14.0/14A309 - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.5 => 0.69.5 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

[I've made a repo](https://github.com/flowchase/break-image-component), opening it on Android Emulator crashes the app on launch.

### Snack, code example, screenshot, or link to a repository

https://github.com/flowchase/break-image-component

**Comment by danilobuerger** [comment]
Does it work when you add width and height to each source object in the array?

**Comment by filipecatraia** [comment]
@danilobuerger Yes, that makes the problem go away. The issue is, with these network images, I can't be sure what width/heights I'll be getting as they are assets uploaded by the team.

**Comment by danilobuerger** [comment]
The error message could be better, but the docs are clear:

> This prop can also contain several remote URLs, specified together with their width and height and potentially with scale/other URI arguments.

https://reactnative.dev/docs/image#source

**Comment by filipecatraia** [comment]
Damn, I missed that. Do you know why it doesn't break on iOS?

**Comment by filipecatraia** [comment]
Interestingly this is recent, since we upgraded to RN 0.69.5. Android didn't crash in our last build.

**Comment by cortinico** [comment]
Can we consider this resolved?

**Comment by filipecatraia** [comment]
I'd argue the behavior is sub-optimal, especially considering it's more of a regression (it didn't happen in 0.64). But by all means, go ahead and close it, as it is technically the intended behavior on your end.
