### ISSUE TITLE
0.70.1 issue

### ISSUE THREAD

**Issue by billnbell** [facebook/react-native#34714]
### Description
```
└─┬ react-native@0.70.1
       ├─┬ @react-native-community/cli@9.1.1
        │      └─┬ @react-native-community/cli-plugin-metro@9.1.1
        │             └── metro-react-native-babel-transformer@0.72.3
       └── metro-react-native-babel-transformer@0.72.1
```

Notice react-native@0.70.1 has 2 versions of metro-react-native-babel-transformer which is causing issues on startup metro.

### Version

0.70.1

### Output of `npx react-native info`

See above

### Steps to reproduce

Starting RN

### Snack, code example, screenshot, or link to a repository

<img width="394" alt="Screen Shot 2022-09-16 at 10 47 22 PM" src="https://user-images.githubusercontent.com/25377089/190840921-1e6b616f-082f-4403-88f0-d3c64cfb0a0b.png">

**Comment by billnbell** [comment]
In package.json we need to set it to "9.0.0" and remove ^. @react-native-community/cli

**Comment by billnbell** [comment]
```
-    "@react-native-community/cli": "^9.0.0",
-    "@react-native-community/cli-platform-android": "^9.0.0",
-    "@react-native-community/cli-platform-ios": "^9.0.0",
+    "@react-native-community/cli": "9.0.0",
+    "@react-native-community/cli-platform-android": "9.0.0",
+    "@react-native-community/cli-platform-ios": "9.0.0",
```

**Comment by billnbell** [comment]
Actually not able to fix it... Trying to eliminate multiple metros is difficult.

**Comment by billnbell** [comment]
I cleaned and it went away after downgrading to  "metro-react-native-babel-preset": "0.72.1",

**Comment by billnbell** [comment]
I would still recommend that we go thru the dependent packages and those that are auto-upgrading to 0.72.3 should be set to not upgrade. Hence the removal of "^". But we need to check all of them to be consistent to 0.72.1. Or we should rush out a new build for 0.72.3 metro.

**Comment by cortinico** [comment]
Just a heads up: we're aware of this issue 
https://github.com/reactwg/react-native-releases/discussions/34#discussioncomment-3682962

We'll be fixing it most likely in 0.70.2
