### ISSUE TITLE
Shadow Not Display in Android

### ISSUE THREAD

**Issue by dippathak26** [facebook/react-native#34720]
### Description

Hello Team, 

I am currently working on react-native and I'm trying to display shadow to my view as shown below in Android. Same thing works well in IOS.
style={{
    backgroundColor: "#FFF",
        padding: 10,
        elevation: 2,
        shadowColor: "#000",
        shadowOffset: {
          width: 0,
          height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
  }}
  
  But unfortunately, I am not seeing any change in my UI. The following are the dependencies used:
   "dependencies": {
    "@react-native-community/async-storage": "^1.12.1",
    "@react-native-community/datetimepicker": "^6.2.0",
    "@react-native-community/push-notification-ios": "^1.10.1",
    "@react-native-firebase/app": "^15.2.0",
    "@react-native-firebase/messaging": "^15.2.0",
    "@react-navigation/native": "^6.0.11",
    "@react-navigation/stack": "^6.2.2",
    "bugsnag-react-native": "^2.23.10",
    "i18n-js": "^3.9.2",
    "lodash": "^4.17.21",
    "moment": "^2.29.4",
    "prop-types": "^15.8.1",
    "react": "17.0.2",
    "react-native": "0.68.2",
    "react-native-animatable": "^1.3.3",
    "react-native-background-timer": "^2.4.1",
    "react-native-config": "^1.4.6",
    "react-native-country-picker-modal": "^2.0.0",
    "react-native-datepicker": "^1.7.2",
    "react-native-document-picker": "^8.1.1",
    "react-native-gesture-handler": "^2.5.0",
    "react-native-image-crop-picker": "^0.38.0",
    "react-native-iphone-x-helper": "^1.3.1",
    "react-native-orientation-locker": "^1.5.0",
    "react-native-push-notification": "^8.1.1",
    "react-native-responsive-fontsize": "^0.5.1",
    "react-native-safe-area-context": "^3.4.1",
    "react-native-screens": "^3.15.0",
    "react-native-simple-toast": "^1.1.4",
    "react-native-splash-screen": "^3.3.0",
    "react-native-swipe-gestures": "^1.0.5",
    "react-native-vector-icons": "^9.2.0",
    "react-navigation-shared-element": "^3.1.3",
    "react-redux": "^8.0.2",
    "redux": "^4.2.0",
    "redux-persist": "^6.0.0",
    "redux-thunk": "^2.4.1",
    "sendbird": "^3.1.23"
  },
  
  It's been a week now trying to resolve this issue, but I'm unable to get any solution. Could you please help me out here?
  
  Thanks in advance

### Version

0.68.2

### Output of `npx react-native info`

System:
    OS: macOS 11.6.8
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 30.79 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.15.0 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.5.5 - /usr/local/bin/npm
    Watchman: 2022.03.21.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: javac 15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.2 => 0.68.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

<View style={{
backgroundColor: "#FFF",
padding: 10,
 elevation: 2,
          shadowColor: "#000",
          shadowOffset: {
            width: 0,
            height: 2,
          },
          shadowOpacity: 0.25,
          shadowRadius: 3.84,}}>
<Text>Hi</Text>
</View>

### Snack, code example, screenshot, or link to a repository

![image](https://user-images.githubusercontent.com/84957963/190954786-e97d21f3-d3f1-4db6-8fc8-78dfc289ac60.png)

**Comment by rahulnainwal107** [comment]
Hi @dippathak26, Can you please share your exact code snippet? I tried it with same configuration and it is working fine. Code snippet - 
```
      <View
        style={{
          backgroundColor: '#FFF',
          padding: 10,
          elevation: 2,
          shadowColor: '#000',
          shadowOffset: {
            width: 0,
            height: 2,
          },
          shadowOpacity: 0.25,
          shadowRadius: 3.84,
        }}>
        <Text>Hi</Text>
      </View>
      <View
        style={{
          backgroundColor: '#FFF',
          padding: 10,
          elevation: 2,
          shadowColor: '#000',
          shadowOffset: {
            width: 0,
            height: 2,
          },
          shadowOpacity: 0.25,
          shadowRadius: 3.84,
        }}>
        <Text>Hi</Text>
      </View>
      <View
        style={{
          backgroundColor: '#FFF',
          padding: 10,
          elevation: 2,
          shadowColor: '#000',
          shadowOffset: {
            width: 0,
            height: 2,
          },
          shadowOpacity: 0.25,
          shadowRadius: 3.84,
        }}>
        <Text>Hi</Text>
      </View>
```
![Screenshot_20221006-182441_newproject](https://user-images.githubusercontent.com/36499090/194319832-961d8d88-ede1-4cca-a2b6-fd27b017b249.jpg)

Add some margin in order to make it clear, just like this - 
```
       <View
        style={{
          backgroundColor: '#FFF',
          padding: 10,
          elevation: 2,
          shadowColor: '#000',
          shadowOffset: {
            width: 0,
            height: 2,
          },
          shadowOpacity: 0.25,
          shadowRadius: 3.84,
          margin:10
        }}>
        <Text>Hi</Text>
      </View>
```
![Screenshot_20221006-182416_newproject](https://user-images.githubusercontent.com/36499090/194319825-4c113bb8-10af-472b-8bce-f1f05836dc37.jpg)
