### ISSUE TITLE
When one border of View is transparent, all borders are not displayed

### ISSUE THREAD

**Issue by zhxlp** [facebook/react-native#34722]
### Description

When one border of View is transparent, all borders are not displayed

Only Android

### Version

0.70.1

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
    Memory: 6.34 GB / 15.96 GB
  Binaries:
    Node: 16.13.1 - C:\Program Files\nodejs\node.EXE    
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD      
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD        
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: AI-212.5712.43.2112.8609683
    Visual Studio: Not Found
  Languages:
    Java: 11.0.15 - C:\Program Files\Eclipse Adoptium\jdk-11.0.15.10-hotspot\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.1 => 0.70.1
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Starting RN

### Code 
```
  <View
        style={{
          width: 100,
          height: 100,
          borderWidth: 10,
          borderRadius: 100,
          borderColor: '#FF0000',
          borderBottomColor: 'transparent',
          justifyContent: 'center',
          alignItems: 'center',
        }}>
        <Text>1</Text>
      </View>
      <View
        style={{
          width: 100,
          height: 100,
          borderWidth: 10,
          borderRadius: 100,
          borderColor: '#FF0000',
          justifyContent: 'center',
          alignItems: 'center',
        }}>
        <Text>2</Text>
      </View>
```
### screenshot
![Snipaste_2022-09-19_17-10-28](https://user-images.githubusercontent.com/20200335/190985563-74bcef70-0066-41bc-8e9a-29e2d755cbf8.png)

**Comment by danilobuerger** [comment]
Does this also happen without a border radius?

**Comment by zhxlp** [comment]
![image](https://user-images.githubusercontent.com/20200335/191026950-bcec4536-5598-4764-ba80-9ac094e704a1.png)
@danilobuerger

**Comment by willLopesz** [comment]
I'm having the same problem, any solution?

**Comment by joaojeefer** [comment]
> Does this also happen without a border radius?

I'm having the same problem, but I noticed that it doesn't happen without a border radius.

**Comment by ErikHasp** [comment]
Took me some to get to the source of the problem and thanks to that found this thread. I found an imperfect quick workaround with using almost transparent color `#00000000` or `rgba(0, 0, 0, 0.01)`

**Comment by sumi-svmx** [comment]
> Took me some to get to the source of the problem and thanks to that found this thread. I found an imperfect quick workaround with using almost transparent color #00000001 or rgba(0, 0, 0, 0.01)

@ErikHasp the workaround seems to work. Do we know what the issue is? Happens in RN 0.70.6

**Comment by brunoro** [comment]
Just saw this on RN 0.71.6

**Comment by hduoc2003** [comment]
any solution for this bug, it's really ridiculous :((

**Comment by nazmeln** [comment]
Hey all,
The issue seems related to [fix](https://github.com/facebook/react-native/commit/a9659ce86d94dd34768b067763740a5c41917e42) by @mdvacca in the 0.70 version. Hence, when this condition is removed, everything works as expected. It can be patched(`yarn patch package) unless it's not fixed in an upcoming release.

**Comment by yrichard** [comment]
I saw this too in 0.70, and 0.66, when you render a view with a transparent border, things would not render properly unless you set a border radius.
Unfortunately that workaround is busted in 0.71.

**Comment by JoaoMosmann** [comment]
This issue still present on latest react-native release `0.73.6`.

**Comment by Zweird-958** [comment]
> This issue still present on latest react-native release `0.73.6`.

Still present on `0.74.3`

**Comment by matej-kaska** [comment]
Still present on `0.74.5`
