### ISSUE TITLE
embedding docs are incomplete/inaccurate, sample project is broken

### ISSUE THREAD

**Issue by andrewljohnson** [facebook/react-native#3472]
The docs here don't tell you to import react in your objective C code: https://facebook.github.io/react-native/docs/embedded-app-ios.html

This is made more confusing because the the linked sample project doesn't build (in XCode 7): https://github.com/tjwudi/EmbededReactNativeExample

It breaks on:

    #import "RCTRootView.h"

Which is also where my attempt to embed breaks.

**Comment by javache** [comment]
Did you run `pod install` after cloning the example project?

The linked project is quite out-of-date however, it was last updated March 31st. I'll try to add an up-to-date copy to this repository.

**Comment by brentvatne** [comment]
@andrewljohnson - does the docs update from #3490 help?

@javache - perhaps we can just link to this repo instead: https://github.com/dsibiski/react-native-embedded-app-example cc @dsibiski

**Comment by dsibiski** [comment]
@brentvatne @javache I've been meaning to re-write the iOS "embedded app" docs for a little while now. I think it's time now that what is there is no longer working. Perhaps I'll take a stab at it later this evening and submit a PR. I'll be adding Android example to this repo shortly as well.

**Comment by jwhitley** [comment]
AFAICT, the current embedding docs are also out of date at [§ Start Development Server](https://github.com/facebook/react-native/blob/master/docs/EmbeddedAppIOS.md#start-development-server).  That command tries to cd into `Pods/React` which doesn't exist after following the prior workflow.  The React pod appears to be installed, but that directory doesn't exist.  Nor is there any  `package.json` for the `npm run start ...` command to use anywhere under `Pods/`.  :neutral_face: 

I was hoping for a quick start into using React Native for some new feature work on an existing app, but it seems that I'm stuck on the proverbial on-ramp.

Any quick pointers on the current (v0.14.2) best practice for getting the dev server running?  Is it sufficient to just grab the custom build step from a new app template generated with react-native-cli?

**Comment by andrewljohnson** [comment]
I think I can fix the embedding docs now, I'll do a PR unless there is other action I'm missing? 

The main things that I had to work past were:

1. I needed to import RCTRootView.h like this:

    `#import <React/Base/RCTRootView.h> `
2. the jsCodeLocation needs a platform:

    ` NSURL *jsCodeLocation = [NSURL URLWithString:@"http://localhost:8081/index.ios.bundle?platform=ios"];  `

3. The RCTRootView *rootView in the example needs a property parameter.
    
        RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL: jsCodeLocation 
                                                            moduleName: @"SimpleApp" 
                                                     initialProperties: @{} 
                                                         launchOptions: nil];

**Comment by andrewljohnson** [comment]
@jwhitley dev server works for me when I run it in my the /ReactComponent directory that has index.ios.js

    (JS_DIR=`pwd`; cd /node_modules/React; npm run start -- --root $JS_DIR)

Here is the README I added to our app repo for my colleagues to run react when developing the iOS app:

# Using React Native, Embedded in iOS App

React Native is embedded [based on this guide](https://facebook.github.io/react-native/docs/embedded-app-ios.html), so we can use it only for specific views.

## Install React
This assumes you put your embedded React-Native code in a directory called ReactNativeComponents. React is installed via npm (using the package.json file in ReactNativeComponents), then connected to the iOS app via cocoapods (Podfile maps to React and specific modules we use). 

    cd ReactNativeComponents
    npm install
    cd ..
    pod install

## Start the React packager

This will conveniently hot reload your JavaScript as you edit it.

    cd ReactNativeComponents
    (JS_DIR=`pwd`; cd /node_modules/React; npm run start -- --root $JS_DIR)

## Run the App

   After that, you just run the app as usual in XCode simulator, and your React views show up.

   When you edit the JavaScript, you can used cmd-R to reload the simulator, and you don't need to recompile. Recompiling is only needed (as usual) if you edit the native code for the app.

[More docs here](http://facebook.github.io/react-native/docs/getting-started.html).

**Comment by DougBanksPersonal** [comment]
@jwhitley 
I had the same problems, got through them.  Documented here:
http://zeemeeeng.blogspot.com/

**Comment by brentvatne** [comment]
Thanks for sharing @DougBanksPersonal! :+1:

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/embedding-docs-are-incompleteinaccurate-sample-project-is-broken

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
