### ISSUE TITLE
There is a Helloworld.xcworkspace file in the ios folder every time I use the typescript template.

### ISSUE THREAD

**Issue by younisrahman** [facebook/react-native#34734]
### Description

Recently, I created a new project using react-native 0.70 with this command: `npx react-native init ExpenseTracker ---template react-native-template-typescript`. After creating it, I checked the ios folder and found the Helloworld.xcworkspace file. And when I try to run the app, it shows this error:`
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening Helloworld.xcworkspace.
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -workspace Helloworld.xcworkspace -configuration Debug -scheme Helloworld -destination id=1D32553F-4ADB-43DE-BD09-630294126564

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES
`

### Version

0.70

### Output of `npx react-native info`

```
info Fetching system and libraries information...
System:
    OS: macOS 12.6
    CPU: (8) x64 Apple M1
    Memory: 39.34 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.15.0 - /usr/local/bin/npm
    Watchman: 2022.09.05.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8815526
    Xcode: 14.0/14A309 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.1 => 0.70.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

```

### Steps to reproduce

Run this command on terminal `npx react-native init ExpenseTracker --template react-native-template-typescript`
And check ios folder

### Snack, code example, screenshot, or link to a repository

https://github.com/younisrahman/react-native-70-issue
<img width="684" alt="Screenshot 2022-09-20 at 6 56 48 PM" src="https://user-images.githubusercontent.com/51438421/191330604-e453ec19-ced1-4287-869e-970cef6282da.png">

<img width="585" alt="Screenshot 2022-09-21 at 12 00 35 AM" src="https://user-images.githubusercontent.com/51438421/191330928-d8f90205-7cd1-4c9c-9541-db565659ddee.png">

**Comment by cortinico** [comment]
You should open this same issue inside https://github.com/react-native-community/react-native-template-typescript

The typescript template is not part of this repo.

I have the suspect they're including the file:
https://github.com/react-native-community/react-native-template-typescript/blob/main/template/ios/Helloworld.xcworkspace/contents.xcworkspacedata 
while they should not.
