### ISSUE TITLE
Going in circles: "Multiple commands produce..." error is solved with "pod install --repo-update" but then React-Codegen missing shadow nodes appears.

### ISSUE THREAD

**Issue by MyPalVikram** [facebook/react-native#34732]
### Description

Ok, so I'm going through the setup process for [React Native Firebase](https://rnfirebase.io) and everything is working fine on Android. On iOS, after adding all the configurations I get a bunch of errors as follows:

<img width="276" alt="Screenshot 2022-09-20 at 9 36 08 AM" src="https://user-images.githubusercontent.com/6226652/191314913-c6afd8d5-6572-4f6b-b6f2-9580277e490b.png">

So I got into the `ios` directory and solve it by running a `pod install --repo-update`. I go back to Xcode to build on the simulator and I get React Codegen error saying missing shadow nodes.

<img width="341" alt="Screenshot 2022-09-20 at 9 27 56 AM" src="https://user-images.githubusercontent.com/6226652/191313304-75571be0-e794-41d4-8d6f-f7e731dadff3.png">

I return to my iOS folder and run `RCT_NEW_ARCH_ENABLED=1 bundle exec pod install` and that fixes the shadow nodes error but the `Multiple commands produce...` returns.

What is the proper way to handle these errors? Right now I'm just going in circles trying to fix both errors.

### Version

0.70.1

### Output of `npx react-native info`

```
System:
    OS: macOS 13.0
    CPU: (10) arm64 Apple M1 Max
    Memory: 423.63 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.9.0 - /opt/homebrew/bin/node
    Yarn: 1.22.18 - ~/.yarn/bin/yarn
    npm: 8.19.1 - /opt/homebrew/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /Users/vikrampal/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8815526
    Xcode: 14.0/14A309 - /usr/bin/xcodebuild
  Languages:
    Java: 18.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

The steps to reproduce are described above.

### Snack, code example, screenshot, or link to a repository

In regards to me setting up Firebase, here are those files:

Podfile - I commented out Flipper as the docs recommended.

```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

$RNFirebaseAsStaticFramework = true

platform :ios, '12.4'
install! 'cocoapods', :deterministic_uuids => false

target 'MyApp' do
  config = use_native_modules!
  use_frameworks! :linkage => :static

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    :hermes_enabled => true,
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    # :flipper_configuration => FlipperConfiguration.enabled,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'MyAppTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end

```

**Comment by cortinico** [comment]
> Ok, so I'm going through the setup process for [React Native Firebase](https://rnfirebase.io) and everything is working fine on Android. On iOS, after adding all the configurations I get a bunch of errors as follows:

I would suggest you open this issue against React Native Firebase. @mikehardy would be more this happy to support you over there 👍 Thanks

**Comment by mikehardy** [comment]
Read the comments in this script, run it, and examine the podfile that results: https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh

Start to finish + fully working react-native-firebase demo, debug + release, iOS + macCatalyst, with Hermes on react-native 0.70.1

Cheers

**Comment by MyPalVikram** [comment]
> 

Worked like a charm! Thank you so much.
