### ISSUE TITLE
Space in the folder name is creating problem on Build Execution.

### ISSUE THREAD

**Issue by rb185264** [facebook/react-native#34743]
### Description

I am trying to add react-native latest to the existing ios app. Unfortunately, the folder that is consisting of Podfile and Base xcode Project has a name with space like IFS Banking.

This is causing is directory error in FBReactNativeSpec

### Version

0.70.1

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 12.5.1
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 289.01 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.16.0 - /usr/local/opt/node@16/bin/node
    Yarn: 3.2.0 - /usr/local/bin/yarn
    npm: 8.11.0 - /usr/local/opt/node@16/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.2 - /Users/rb185264/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK:
      API Levels: 26, 27, 28, 29, 30, 31
      Build Tools: 27.0.3, 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0
      System Images: android-25 | Google APIs ARM 64 v8a, android-26 | Android Wear Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-28 | Wear OS Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-R | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7351085
    Xcode: 14.0/14A309 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_221 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^18.2.0 => 18.2.0 
    react-native: ^0.70.1 => 0.70.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Create any base project with space in folder name.

/Users/rb185264/Projects/mba-ios**/IFS Banking**

### Snack, code example, screenshot, or link to a repository

<img width="701" alt="Screen Shot 2022-09-20 at 10 31 42 PM" src="https://user-images.githubusercontent.com/86488957/191408322-bf580afb-8a4b-4e78-9886-fe52022439ae.png">

**Comment by rb185264** [comment]
it is saying no such a file or directory.

**Comment by micahlt** [comment]
Can confirm there is an issue on Windows as well

**Comment by cortinico** [comment]
Spaces are not supported in the folder name.

If you were to try to create a folder with a space with `npx react-native init` it would fail with:

```
npx react-native init "IFS Banking" --version latest
Need to install the following packages:
  react-native
Ok to proceed? (y) y
error "IFS Banking" is not a valid name for a project. Please use a valid identifier name (alphanumeric).
Error: "IFS Banking" is not a valid name for a project. Please use a valid identifier name (alphanumeric).
```

So you should rename your folder to remove the space.
