### ISSUE TITLE
Documentation clarification suggestion - Android Native modules section.

### ISSUE THREAD

**Issue by dsandor** [facebook/react-native#3475]
This paragraph is a bit confusing:

> The package needs to be provided to the ReactInstanceManager when it is built. See UIExplorerActivity.java for an example. The default package when you initialize a new project is MainReactPackage.java.

Could we include some additional details to telegraph to a new developer where to actually place the code listed below?

I suggest changing the paragraph to this:

The package needs to be provided to the ReactInstanceManager when it is built.  To accomplish this you will need to insert an `.addPackage(new YourPackageName())` call to the `mReactInstanceManager = ReactInstanceManager.builder()` call chain.

Refer to the code below and add the `addPackage ` statement to your application's `MainActivity.java` file.  This file exists under the android folder in your react-native application directory.  The path to this file is:  android/app/src/main/java/com/your-app-name/MainActivity.java.

**Comment by brentvatne** [comment]
Sounds good, please re-open as a PR! :smile: Thanks!
