### ISSUE TITLE
- (void)rootViewDidChangeIntrinsicSize:(RCTRootView *)rootView; Isn't call

### ISSUE THREAD

**Issue by wgywgy** [facebook/react-native#34765]
### Description

Which replace method can at right time get IntrinsicSize?
In the new arch(Enable fabric), RCTRootView's method: - (void)rootViewDidChangeIntrinsicSize:(RCTRootView *)rootView;
isn't call.

### Version

0.68.1

### Output of `npx react-native info`

[showLog] :::  9
[Q_PACK_LOG_LEVEL] :::  undefined
info Fetching system and libraries information...
System:
    OS: macOS 12.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
    Memory: 1.81 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.3.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.11.0 - /usr/local/bin/npm
    Watchman: 2022.07.04.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/d/.rvm/gems/ruby-2.7.4/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

none

### Snack, code example, screenshot, or link to a repository

none

**Comment by wgywgy** [comment]
mannal get RCTFabricSurface's intrinsicSize also get zero value.

**Comment by cortinico** [comment]
Hey @wgywgy 
Can I ask you to post this question inside the Working Group:
https://github.com/reactwg/react-native-new-architecture
You should already have access.

As a rule of thumb, questions should be posted there as we're tracking them more closely and they form a knowledge base that we'll use to expand our official docs.

We can totally answer on Github issues, but the information is easily lost 👍 Thank you.
