### ISSUE TITLE
`addUIBlock` not working in New Architecture.

### ISSUE THREAD

**Issue by psionic12** [facebook/react-native#34764]
### Description

When I enable fabric and turbomodule, `addUIBlock` seems not working because the callback will never be called: 
```
UIManagerModule uiManager = context.getNativeModule(UIManagerModule.class);
        uiManager.addUIBlock(new UIBlock() {
            @Override
            public void execute(NativeViewHierarchyManager nativeViewHierarchyManager) {
                HMapView hMapView;
                try {
                    hMapView = (HMapView) nativeViewHierarchyManager.resolveView(viewTag);
                } catch (Exception e) {
                    QLog.e(e);
                    hMapView = null;
                }
                if(hMapView != null){
                    WritableNativeMap map = hMapView.getLocationParams();
                    callback.invoke(map);
                }
            }
        });
```
If I understand the new architecture right, `uiManager` is not get used when fabric is enabled, but the `JSIModule`.  But I didn't find functions which act the same with `addUIBlock`.

So what is the solution when I want to use `addUIBlock` when fabric is on?

### Version

0.68.1

### Output of `npx react-native info`

System:
    OS: macOS 11.6.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 139.06 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.19.3 - ~/.nvm/versions/node/v14.19.3/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.17 - ~/.nvm/versions/node/v14.19.3/bin/npm
    Watchman: 2022.01.17.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK:
      Android NDK: 21.1.6352462
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: 0.68.1 => 0.68.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
info React Native v0.70.1 is now available (your project is running on v0.68.1).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.70.1.
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.68.1.
info To upgrade, run "react-native upgrade".

### Steps to reproduce

None.

### Snack, code example, screenshot, or link to a repository

```
UIManagerModule uiManager = context.getNativeModule(UIManagerModule.class);
        uiManager.addUIBlock(new UIBlock() {
            @Override
            public void execute(NativeViewHierarchyManager nativeViewHierarchyManager) {
                Log.i(TAG, "it works");
            }
        });
```
when fabric is on.

**Comment by cortinico** [comment]
Hey @psionic12  
Can I ask you to post this question inside the Working Group:
https://github.com/reactwg/react-native-new-architecture
If you don't have access, please request it via the form in the README

As a rule of thumb, questions should be posted there as we're tracking them more closely and they form a knowledge base that we'll use to expand our official docs.

We can totally answer on Github issues, but the information is easily lost 👍 Thank you.

**Comment by zabojad** [comment]
Hi @psionic12, I'm having the same problem... How did you solve it ?

**Comment by joemun** [comment]
I posted this question to the New Arch WG forum here:
https://github.com/reactwg/react-native-new-architecture/discussions/148

**Comment by erik-kallen** [comment]
I, too, am having the same problem. Is there a good solution?

**Comment by RP-alissonpaschoal** [comment]
`react-native-view-shot` doesn't working in the new architecture because of this `addUIBlock` as well

**Comment by rohit-jindal018** [comment]
What is the alternate for addUIBlock in Fabric in react native. As addUIBlock is not working

**Comment by VinPin** [comment]
Hello everyone, I am also facing the same problem. Do you have any alternative solutions to solve it?

**Comment by L0rdCr1s** [comment]
> `react-native-view-shot` doesn't work in the new architecture because of this `addUIBlock` as well

did you find a solution to this problem? I'm also facing the same situation, `react-native-view-shot` is not working on android because of this

**Comment by arushikesarwani94** [comment]
Yes, that's correct for New Arch [UIManagerModule.addUIBlock()](https://github.com/facebook/react-native/blob/4d9bd9040107661e336cddad1948f50b78ce8ad6/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/UIManagerModule.java#L753-L766) returns null on Bridgeless.

The replacement API added for Backwards Compatibility in Bridgeless is
https://github.com/facebook/react-native/blob/2483c63017b0d47c377bf67cb7c597e2d7e57897/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/fabric/FabricUIManager.java#L104

Sample fix PRs : https://github.com/expo/expo/pull/29500 https://github.com/react-native-maps/react-native-maps/pull/5061

**Comment by migueldaipre** [comment]
> Yes, that's correct for New Arch [UIManagerModule.addUIBlock()](https://github.com/facebook/react-native/blob/4d9bd9040107661e336cddad1948f50b78ce8ad6/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/UIManagerModule.java#L753-L766) returns [null](https://github.com/facebook/react-native/blob/main/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/runtime/ReactHostImpl.java#L600-L606) on Bridgeless.
> 
> The replacement API added for Backwards Compatibility in Bridgeless is
> https://github.com/facebook/react-native/blob/2483c63017b0d47c377bf67cb7c597e2d7e57897/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/fabric/FabricUIManager.java#L104
> 
> Sample fix PRs : https://github.com/expo/expo/pull/29500 https://github.com/react-native-maps/react-native-maps/pull/5061

Can you help me use addUIBlock on the new architecture without bridgeless mode? Only fabric component
