### ISSUE TITLE
How do react-native version relate to react versions?

### ISSUE THREAD

**Issue by mschipperheyn** [facebook/react-native#3476]
This is relevant for libraries (such as redux) that depend on specific versions of react (but don't publish react-native dependencies). Also, to know which API changes / improvements from react we're able to use.

**Comment by browniefed** [comment]
Soon https://github.com/facebook/react-native/issues/2985

**Comment by ide** [comment]
Currently it's running an RC of 0.14. In awhile we hope for RN to be using React from npm.

**Comment by skevy** [comment]
@ide, fwiw it's not running an RC. It's running 0.14-beta1 https://github.com/facebook/react/commit/b4e74e38e43ac53af8acd62c78c9213be0194245
