### ISSUE TITLE
Unable to build archive on xcode 14

### ISSUE THREAD

**Issue by waqas-ahmad762** [facebook/react-native#34760]
### Description

I am trying to build an archive of my app But it doesn’t been completed successfully. Following issues comes 
`error build: Build input file cannot be found: '/Users/myPCName/Library/Developer/Xcode/DerivedData/xyz-epljvllnlsnioqbzrozfbccnugpd/ArchiveIntermediates/Production/BuildProductsPath/GeneratedInfoPlistDotEnv.h'. Did you forget to declare this file as an output of a script phase or custom build rule which produces it?`

### Version

react-native-cli: 2.0.1 react-native: 0.63.3

### Output of `npx react-native info`

System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1
    Memory: 111.17 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.0 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8309675
    Xcode: 14.0/14A309 - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.1 - /usr/bin/javac
    Python: Not Found
  npmPackages:
    @react-native-community/cli: ^4.10.1 => 4.13.0 
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

hen I try to build an app for the simulator and build an archive for distribution this error comes

### Snack, code example, screenshot, or link to a repository

<img width="1280" alt="xcode-issue" src="https://user-images.githubusercontent.com/68920259/191664188-eb8d0d3c-4cc2-43cf-ae67-32924c0d2f44.png">

**Comment by pnthach95** [comment]
It looks like [react-native-config issue](https://github.com/luggit/react-native-config/issues/683), not relate to react-native in general

**Comment by cortinico** [comment]
Closing as the issue @pnthach95 seems like the correct one to follow over 👍
