### ISSUE TITLE
Build 'libturbomodulejsijni.so' with option -fstack-protector compile flag to enable Stack Smashing Protection (SSP)

### ISSUE THREAD

**Issue by jitendragupta24** [facebook/react-native#34770]
### Description

We use React-Native for our android/iOS application. Security team on a customer's behalf identified and reported a vulnerability - **libarcore_sdk_jni.so** library is not compiled with Stack smashing protection (SSP) in Android.

This is categorized as "Weak Binary Protection | Lacks Stack   smashing Protection (SSP) for Libraries".

https://wiki.osdev.org/Stack_Smashing_Protector#:~:text=The%20Stack%20Smashing%20Protector%20(SSP,mitigation%20against%20return%2Doriented%20programming.

Binary needs to be compiled with 'fstack-protector'. Here are couple of links which explains the required change:

- https://stackoverflow.com/questions/47822033/how-to-enable-fstack-protector-in-android-gradle-build-process
- https://android-review.googlesource.com/c/platform/ndk/+/785257/1/build/core/default-build-commands.mk

### Version

0.64.2

### Output of `npx react-native info`

System:
    OS: macOS 13.0
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 120.68 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.19.3 - ~/.nvm/versions/node/v14.19.3/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.17 - ~/.nvm/versions/node/v14.19.3/bin/npm
    Watchman: 2022.03.21.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 28, 29, 30, 32
      Build Tools: 27.0.3, 28.0.3, 29.0.2, 30.0.3
      System Images: android-31 | Google APIs Intel x86 Atom_64, android-31 | Google Play Intel x86 Atom_64, android-Tiramisu | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8309675
    Xcode: 14.1/14B5024i - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: ^4.13.0 => 4.14.0 
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.2 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

NA

### Snack, code example, screenshot, or link to a repository

NA

**Comment by cortinico** [comment]
> libarcore_sdk_jni.so library is not compiled with Stack smashing protection (SSP) in Android.

`libarcore_sdk_jni` is not a library we own. It's most likely a library from AR Core SDK from Google so you should open this issue against their issue tracker.

**Comment by jitendragupta24** [comment]
@cortinico There was a typo in description, though title was correct. I cannot reopen this bug, I will go ahead and create new one. Thanks.
