### ISSUE TITLE
Error: Cannot read property 'connect' of undefined

### ISSUE THREAD

**Issue by awesomepankaj** [facebook/react-native#3477]
I am using socket.io-client and trying to connect server but i am getting this error:-
Error: Cannot read property 'connect' of undefined
react native  0.13.0
in android

**Comment by satya164** [comment]
@awesomepankaj Have you updated the React Native version in both `package.json` and `build.gradle`?

**Comment by awesomepankaj** [comment]
yeah I update react native version to 0.13.0 in build.gradle file
and now I am  getting this error:
Error: `IconImage` has no propType for native prop `SMXIconImage.scaleX` of native type `number`

**Comment by sherlock221** [comment]
I also have the same problem   when I upgraded to 0.13     

so i edit build.gradle  now is work 
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:23.0.1'
    compile 'com.facebook.react:react-native:0.13.+'
}
