### ISSUE TITLE
Build 'libturbomodulejsijni.so' with option -fstack-protector compile flag to enable Stack Smashing Protection (SSP)

### ISSUE THREAD

**Issue by jitendragupta24** [facebook/react-native#34775]
### Description

We use React-Native for our android/iOS application. Security team on a customer's behalf identified and reported a vulnerability - 'libturbomodulejsijni.so' library is not compiled with Stack smashing protection (SSP) in Android.

This is categorized as "Weak Binary Protection | Lacks Stack smashing Protection (SSP) for Libraries".

https://wiki.osdev.org/Stack_Smashing_Protector#:~:text=The%20Stack%20Smashing%20Protector%20(SSP,mitigation%20against%20return%2Doriented%20programming.

Binary needs to be compiled with 'fstack-protector'. Here are couple of links which explains the required change:

https://stackoverflow.com/questions/47822033/how-to-enable-fstack-protector-in-android-gradle-build-process
https://android-review.googlesource.com/c/platform/ndk/+/785257/1/build/core/default-build-commands.mk

### Version

0.64.2

### Output of `npx react-native info`

System:
OS: macOS 13.0
CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
Memory: 120.68 MB / 16.00 GB
Shell: 5.8.1 - /bin/zsh
Binaries:
Node: 14.19.3 - ~/.nvm/versions/node/v14.19.3/bin/node
Yarn: 1.22.4 - ~/.yarn/bin/yarn
npm: 6.14.17 - ~/.nvm/versions/node/v14.19.3/bin/npm
Watchman: 2022.03.21.00 - /usr/local/bin/watchman
Managers:
CocoaPods: 1.11.3 - /usr/local/bin/pod
SDKs:
iOS SDK:
Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
Android SDK:
API Levels: 28, 29, 30, 32
Build Tools: 27.0.3, 28.0.3, 29.0.2, 30.0.3
System Images: android-31 | Google APIs Intel x86 Atom_64, android-31 | Google Play Intel x86 Atom_64, android-Tiramisu | Google APIs Intel x86 Atom_64
Android NDK: Not Found
IDEs:
Android Studio: 2021.1 AI-211.7628.21.2111.8309675
Xcode: 14.1/14B5024i - /usr/bin/xcodebuild
Languages:
Java: 11.0.11 - /usr/bin/javac
npmPackages:
@react-native-community/cli: ^4.13.0 => 4.14.0
react: 17.0.1 => 17.0.1
react-native: 0.64.2 => 0.64.2
react-native-macos: Not Found
npmGlobalPackages:
react-native: Not Found

### Steps to reproduce

NA

### Snack, code example, screenshot, or link to a repository

NA

**Comment by cortinico** [comment]
Thanks for reporting this @jitendragupta24 

> 0.64.2

First, your version of React Native is too old. Should we decided to add this flag, it will be released only of 0.71.0 and later versions.

To solve this, we would have to enable the `-fstack-protector` flag on the whole build. It's something we can discuss but I'm unsure what are the runtime implications.

The workaround for you are:
- Strip the library away as you're probably not using it, as it's related to the New Architecture which has flags to use it since 0.68+
- Move to a build from source, and recompile `libturbomodulejsijni.so` with the flag you need.

**Comment by jitendragupta24** [comment]
Thank you @cortinico for your response and proposed workarounds. 

We are in the final stage (should be merged by EOD this week) of upgrading our application to React Native 0.69.2 version.  So, picking up 0.71.0 or later will be the quicker and next step for us. 

As this fix is something which will be useful for all the partners to get adhere to security compliance, can you discuss this internally and figure out tentative versions/timelines? This is the only library reported so far.

Workaround #1 is ruled out, while the second one doesn't seem an efficient solution. Are there any instructions for #2?  Thanks.

**Comment by cortinico** [comment]
> Are there any instructions for workaround 2? Thanks.

The official guide is here: 
https://reactnative.dev/contributing/how-to-build-from-source
Please try it and let me know if you face any blockers.

Recently we update a lot of parts of the native build, so some steps might not work.
If so, we can totally update it and fix it 👍

**Comment by jitendragupta24** [comment]
@cortinico Thank you for your response. Building from the source to update a compile time flag for a tiny subset doesn't seem like a feasible solution for us and it will be difficult in terms of maintainability. 

This is reported only for 'libturbomodulejsijni.so'. So, can you please revisit this again and enable -fstack-protector just for this module? This will help everyone to be compliant. If this works out, we can share tentative timelines with the customer.

**Comment by cortinico** [comment]
> This is reported only for 'libturbomodulejsijni.so'. So, can you please revisit this again and enable -fstack-protector just for this module? This will help everyone to be compliant. If this works out, we can share tentative timelines with the customer.

In general, we can't add a build flag for everyone, to handle your specific use case.

> Building from the source to update a compile time flag for a tiny subset doesn't seem like a feasible solution for us

Why is this the case?
I actually believe that's the preferred way at this stage.
