### ISSUE TITLE
React-native version 0.70.0/0.70.1 ios build failed of fresh install on macbook pro(intel chip)

### ISSUE THREAD

**Issue by engr425imran** [facebook/react-native#34777]
### Description

Hi everyone I have installed 4 to 5 times react-native 0.70 but the ios build failed every time.
the version before 0.70 like 0.67 or 0.68 build perfectly 
I have also installed node lts v16.17.1 but 0.70 ios is not going to build

### Version

0.70 and 0.71

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
    Memory: 2.89 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 16.17.1 - /usr/local/bin/node
    Yarn: Not Found
    npm: 8.15.0 - /usr/local/opt/node@16/bin/npm
    Watchman: 2022.09.12.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8092744
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.1 => 0.70.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

 npx react-native init AwesomeProject
 cd AwesomeProject
 npx react-native run-ios 

### Snack, code example, screenshot, or link to a repository

error I get 
<img width="1088" alt="1" src="https://user-images.githubusercontent.com/70444687/192088677-36d5ba4a-4995-4361-b90a-b0f30c88eeec.png">
<img width="1088" alt="3" src="https://user-images.githubusercontent.com/70444687/192088683-3ba31221-3d06-44c4-b048-08c1705208ae.png">
<img width="1088" alt="2" src="https://user-images.githubusercontent.com/70444687/192088689-442e77d0-c06f-494f-bb21-d732cd77541d.png">

**Comment by anatooly** [comment]
I have some problem after upgrate 0.69.5 to 0.70.1

**Comment by cortinico** [comment]
> 0.70 and 0.71

I assume you meant 0.70.1

Is the same failure happening also on a empty project?

**Comment by jamninetyfive** [comment]
need more info.

**Comment by anatooly** [comment]
> 
Spec.:
```
anatooly@work RnEmptyProject % uname -a
Darwin work.local 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64 x86_64
```
```
anatooly@work RnEmptyProject % /Volumes/MacHD/usr/sbin/system_profiler SPHardwareDataType
Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: MacBookPro15,1
      Processor Name: 6-Core Intel Core i9
      Processor Speed: 2,9 GHz
      Number of Processors: 1
      Total Number of Cores: 6
      L2 Cache (per Core): 256 KB
      L3 Cache: 12 MB
      Hyper-Threading Technology: Enabled
      Memory: 32 GB
      System Firmware Version: 1715.40.15.0.0 (iBridge: 19.16.10548.0.0,0)
      OS Loader Version: 540.40.4~45
      Serial Number (system): C02X74SHJGH6
      Hardware UUID: AB263AA8-A684-5C63-B359-1EE5EBEC639F
      Provisioning UDID: AB263AA8-A684-5C63-B359-1EE5EBEC639F
      Activation Lock Status: Enabled
```
Errors:
```
anatooly@work RnEmptyProject % cd ios
anatooly@work ios % pod install
[Codegen] Generating ./build/generated/ios/React-Codegen.podspec.json
fatal: not a git repository (or any of the parent directories): .git
Analyzing dependencies
[Codegen] Found FBReactNativeSpec
Downloading dependencies
Generating Pods project
Setting REACT_NATIVE build settings
Setting CLANG_CXX_LANGUAGE_STANDARD to c++17 on /Users/anatooly/Developer/RnEmptyProject/ios/RnEmptyProject.xcodeproj
Pod install took 10 [s] to run
Integrating client project
Pod installation complete! There are 59 dependencies from the Podfile and 49 total pods installed.
```
```
anatooly@work RnEmptyProject % react-native run-ios
info Found Xcode workspace "RnEmptyProject.xcworkspace"
info Building (using "xcodebuild -workspace RnEmptyProject.xcworkspace -configuration Debug -scheme RnEmptyProject -destination id=7756C5B5-CAA5-4B4D-8633-77466F1625C1")
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening RnEmptyProject.xcworkspace.
```
run ios log:
[error.log](https://github.com/facebook/react-native/files/9645280/error.log)

**Comment by engr425imran** [comment]
just install a fresh react-native project but the error remains the same.
Xcode version =>  xcode Version 12.4 (12D4e) 
<img width="1075" alt="11" src="https://user-images.githubusercontent.com/70444687/192255341-2a3f6821-ef52-4666-bca3-b7a2e3e47aa3.png">
<img width="1081" alt="12" src="https://user-images.githubusercontent.com/70444687/192255384-6315ac55-a41a-4983-b131-3fdb0dc0672a.png">
what else info we need to give here

**Comment by jamninetyfive** [comment]
Can try to upgrade xcode version to 13 or 14.

**Comment by anatooly** [comment]
> Can try to upgrade xcode version to 13 or 14.

on my example Version 13.4.1, and same issue

**Comment by engr425imran** [comment]
> the error is that your Ruby version is not the right one - please follow the documentation here: https://reactnative.dev/docs/environment-setup#ruby
<img width="869" alt="Screenshot 2022-09-28 at 8 08 25 PM" src=
<img width="867" alt="Screenshot 2022-09-28 at 8 09 50 PM" src="https://user-images.githubusercontent.com/70444687/192816932-3e5c94ec-15af-4048-b6a2-ef50be130f61.png">
"https://user-images.githubusercontent.com/70444687/192816855-b43b8202-69c9-4540-b715-3bd4ad08dcfd.png">


I have updated the ruby version. but the error remains still the same

**Comment by engr425imran** [comment]
### If there is no one to solve this issue let me know so I can convert back my project to react-native 0.68.

**Comment by anatooly** [comment]
> ### If there is no one to solve this issue let me know so I can convert back my project to react-native 0.68.

I think create new project like `npx react-native init RnEmptyProject --version 0.68.3` and move you code or move to you project packages version/Podfile/bundle.grandle/etc :-)

**Comment by engr425imran** [comment]
I am closing issue  .. :) 
Problem was I need to update xcode version from 12.4 to 13
