### ISSUE TITLE
FlatList Error

### ISSUE THREAD

**Issue by JonhsonFu** [facebook/react-native#34783]
### Description

When I navigate to the page which has FlatList,it will send the error "TypeError: undefined is not an object (evaluating 'props.getItem')",I have no idea,help!!!
<img width="585" alt="image" src="https://user-images.githubusercontent.com/44105203/192256321-9f810bd5-27f3-4abf-afa6-8f7f647663e7.png">
<img width="1066" alt="image" src="https://user-images.githubusercontent.com/44105203/192256499-d0b92697-fcc0-43d3-9fad-0ebf772fdbb5.png">
<img width="439" alt="image" src="https://user-images.githubusercontent.com/44105203/192256686-8051328d-7631-4fab-807a-9905948a5e55.png">
And I checked my babel.config.js ,it's without "@babel/plugin-proposal-class-properties",but in my yarn.lock,it's came to my dependencies.
<img width="1061" alt="image" src="https://user-images.githubusercontent.com/44105203/192257251-1fe86d6a-0396-4c59-95e9-c15661b9bbc0.png">
<img width="619" alt="image" src="https://user-images.githubusercontent.com/44105203/192257397-b8a47700-a3d2-48f7-b299-eb2233a0eb9e.png">

### Version

0.66.0

### Output of `npx react-native info`

<img width="585" alt="image" src="https://user-images.githubusercontent.com/44105203/192257582-e48dc22c-5676-4412-96d0-84a98deb5afd.png">
<img width="585" alt="image" src="https://user-images.githubusercontent.com/44105203/192257627-f461ebe5-1d3d-4d2f-acd8-551c16bd6adb.png">

### Steps to reproduce

just goto the page which used FlatList

### Snack, code example, screenshot, or link to a repository

<img width="863" alt="image" src="https://user-images.githubusercontent.com/44105203/192257771-1b8c99c0-b396-4886-9815-5eeaed6297eb.png">

**Comment by JonhsonFu** [comment]
> try `const renderItem = ({item}) => ....` .... `renderItem={renderItem(item)}`

I tried, it didn't work; I have written before that this is OK, maybe it is my environment problem, I am going to create a new project to try this component

**Comment by JonhsonFu** [comment]
After I recreated the project, this component is fine, but the props are undefined in my current project
<img width="740" alt="企业微信截图_44d0ef06-d5e1-43ce-9b9f-d2ce758fc4c0" src="https://user-images.githubusercontent.com/44105203/192485532-cd2e22df-ef87-4a50-bde9-1ca06fdb6eae.png">

**Comment by leepowellnbs** [comment]
Yep, getting the same error, you can use patch-package to add `this.props = props` to the constructor, which should give you a temp workaround
```
constructor(props: Props<ItemT>) {
     super(props);
+    this.props = props;
     this._checkProps(this.props);
     if (this.props.viewabilityConfigCallbackPairs) {
       this._virtualizedListPairs =
```

**Comment by Emptyuu** [comment]
I also met the same problem. Have you found a more appropriate solution...

**Comment by DanielT777** [comment]
> I also met the same problem. Have you found a more appropriate solution...

Same here

**Comment by sidekick-richard** [comment]
`@babel/plugin-proposal-private-methods` was the culprit in my case. removing it, running `yarn start --reset-cache` and then running the app worked for me.
source: https://stackoverflow.com/questions/69922302/react-native-flatlist-undefined-is-not-an-object-evaluating-props-getitem

**Comment by 1mike12** [comment]
Even something as simple as this component results in an Error. 

```ts
import React from "react"
import { FlatList, Text } from "react-native"

export default function HomeScreen() {
  return (
    <FlatList
      data={[
        { title: "one", id: "1" },
        { title: "two", id: "2" }
      ]}
      renderItem={({ item }) => {
        return <Text key={item.id}>{item.title}</Text>
      }}
      keyExtractor={(item) => item.id}
    />
  )
}

```

```
TypeError: Cannot read property 'getItem' of undefined

This error is located at:
    in FlatList (created by HomeScreen)
    in HomeScreen (created by SceneView)

```
<img width="305" alt="image" src="https://user-images.githubusercontent.com/4983282/224434685-ea6b4a42-5620-48e4-b7c8-3d58c74dff40.png">

**Comment by ss1290** [comment]
> Even something as simple as this component results in an Error.
> 
> ```ts
> import React from "react"
> import { FlatList, Text } from "react-native"
> 
> export default function HomeScreen() {
>   return (
>     <FlatList
>       data={[
>         { title: "one", id: "1" },
>         { title: "two", id: "2" }
>       ]}
>       renderItem={({ item }) => {
>         return <Text key={item.id}>{item.title}</Text>
>       }}
>       keyExtractor={(item) => item.id}
>     />
>   )
> }
> ```
> 
> ```
> TypeError: Cannot read property 'getItem' of undefined
> 
> This error is located at:
>     in FlatList (created by HomeScreen)
>     in HomeScreen (created by SceneView)
> ```
> 
> <img alt="image" width="305" src="https://user-images.githubusercontent.com/4983282/224434685-ea6b4a42-5620-48e4-b7c8-3d58c74dff40.png">
> 
> So for some reason it seems like the props are not being passed at all here
> 
> https://github.com/facebook/react-native/blob/48c7adc3bf574c6d592e9d1c1c4bd266f88063f7/Libraries/Lists/FlatList.js#L480

Are you able to solve the issue ? I am facing the same issue

**Comment by ss1290** [comment]
> > Even something as simple as this component results in an Error.
> > ```ts
> > import React from "react"
> > import { FlatList, Text } from "react-native"
> > 
> > export default function HomeScreen() {
> >   return (
> >     <FlatList
> >       data={[
> >         { title: "one", id: "1" },
> >         { title: "two", id: "2" }
> >       ]}
> >       renderItem={({ item }) => {
> >         return <Text key={item.id}>{item.title}</Text>
> >       }}
> >       keyExtractor={(item) => item.id}
> >     />
> >   )
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > TypeError: Cannot read property 'getItem' of undefined
> > 
> > This error is located at:
> >     in FlatList (created by HomeScreen)
> >     in HomeScreen (created by SceneView)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > <img alt="image" width="305" src="https://user-images.githubusercontent.com/4983282/224434685-ea6b4a42-5620-48e4-b7c8-3d58c74dff40.png">
> > So for some reason it seems like the props are not being passed at all here
> > https://github.com/facebook/react-native/blob/48c7adc3bf574c6d592e9d1c1c4bd266f88063f7/Libraries/Lists/FlatList.js#L480
> 
> This became a nightmare for me at this point. A few days ago perfectly working app now stopped working without changing ANYTHING. It's literally the same code base, all I did was to close the emulator and code editor (not even the PC is restarted) and work on some other project for two days and come back and my apps were stuck on loading because of this error (App was already running fine)
> 
> So I close the terminals and re-run with npx react-native run-android and this appears. I don't know what happened. It seems to me the super(props) is not working but no idea why.


Are you able to solve the issue ? I am facing the same issue

**Comment by Sonu7759** [comment]
> ### Description
> When I navigate to the page which has FlatList,it will send the error "TypeError: undefined is not an object (evaluating 'props.getItem')",I have no idea,help!!! <img alt="image" width="585" src="https://user-images.githubusercontent.com/44105203/192256321-9f810bd5-27f3-4abf-afa6-8f7f647663e7.png"> <img alt="image" width="1066" src="https://user-images.githubusercontent.com/44105203/192256499-d0b92697-fcc0-43d3-9fad-0ebf772fdbb5.png"> <img alt="image" width="439" src="https://user-images.githubusercontent.com/44105203/192256686-8051328d-7631-4fab-807a-9905948a5e55.png"> And I checked my babel.config.js ,it's without "@babel/plugin-proposal-class-properties",but in my yarn.lock,it's came to my dependencies. <img alt="image" width="1061" src="https://user-images.githubusercontent.com/44105203/192257251-1fe86d6a-0396-4c59-95e9-c15661b9bbc0.png"> <img alt="image" width="619" src="https://user-images.githubusercontent.com/44105203/192257397-b8a47700-a3d2-48f7-b299-eb2233a0eb9e.png">
> 
> ### Version
> 0.66.0
> 
> ### Output of `npx react-native info`
> <img alt="image" width="585" src="https://user-images.githubusercontent.com/44105203/192257582-e48dc22c-5676-4412-96d0-84a98deb5afd.png">
> 
> <img alt="image" width="585" src="https://user-images.githubusercontent.com/44105203/192257627-f461ebe5-1d3d-4d2f-acd8-551c16bd6adb.png">
> 
> ### Steps to reproduce
> just goto the page which used FlatList
> 
> ### Snack, code example, screenshot, or link to a repository
> <img alt="image" width="863" src="https://user-images.githubusercontent.com/44105203/192257771-1b8c99c0-b396-4886-9815-5eeaed6297eb.png">

are you able to solve the problem

**Comment by uhgenie7** [comment]
> Fixed the issue,
> 
> Simply remove `@babel/plugin-proposal-class-properties` from the babel.config.js's plugins section.
> 
> Then run `npx react-native start --reset-cache`
> 
> Error will disappear.

Thank you, this worked for me. Importantly, must clear the cache.

**Comment by RamenSea** [comment]
> > Fixed the issue,
> > Simply remove `@babel/plugin-proposal-class-properties` from the babel.config.js's plugins section.
> > Then run `npx react-native start --reset-cache`
> > Error will disappear.
> 
> Thank you, this worked for me. Importantly, must clear the cache.

This doesn't work for those of us who need that babel plugin.

**Comment by misha-pavlov** [comment]
Any solution for the case when I need babel plugin?

**Comment by dieguezz** [comment]
Another (less ugly) way of fixing it is by moving the constructor to the top of the class, the problem, as stated in docs, is that tere are other statements between the begining of the class and the super(props). 
You can make the change locally on `node_modules/react-native/Libraries/Lists/FlatList.js` and then add [patch-package](https://github.com/ds300/patch-package) to fix it.

Just add  `"postinstall": "npx patch-package"`,  in your package.json.

You will need the fix until the bugfix is merged and then you will need to install the version with the fix
