### ISSUE TITLE
Failed to transform react-native-reanimated-69-jsc.aar

### ISSUE THREAD

**Issue by DevelopCarlosWM** [facebook/react-native#34810]
### Description

* What went wrong:
Execution failed for task ':react-native-vision-camera:extractJNIFiles'.
> Cannot expand ZIP 'react-native-reanimated/android/react-native-reanimated-69-jsc.aar' as it does not exist.

### Version

0.69.4

### Output of `npx react-native info`

System:
    OS: macOS 12.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 24.80 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.19.1 - /var/folders/dp/ft40z98n7h9dsr3_wx74f4k00000gp/T/yarn--1664379748146-0.4621005663857711/node
    Yarn: 1.22.15 - /var/folders/dp/ft40z98n7h9dsr3_wx74f4k00000gp/T/yarn--1664379748146-0.4621005663857711/yarn
    npm: 6.14.16 - ~/.nvm/versions/node/v14.19.1/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8309675
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: ^0.69.4 => 0.69.5 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found``

### Steps to reproduce

Install react native 0.69, react-native-vision-camera and react-native reanimated

### Snack, code example, screenshot, or link to a repository

Just install the dependencies mentioned above

**Comment by pnthach95** [comment]
What's reanimated version you use? If it's latest, the 69 aar file should be there

**Comment by cortinico** [comment]
> * Execution failed for task ':react-native-vision-camera:extractJNIFiles'.

Hi @DevelopCarlosWM 
Thanks for reporting this issue.

It seems like this issue is actually unrelated to React Native core but related to `react-native-vision-camera`. Please open this issue against this other repository:

https://github.com/mrousavy/react-native-vision-camera/issues

I'll be closing this but feel free to reopen if the other repo points back to us as a issue in the core of React Native.
