### ISSUE TITLE
JSObjectGetPrivate EXC_BAD_ACCESS (code=1, address=0xa028)

### ISSUE THREAD

**Issue by ajnozari** [facebook/react-native#34816]
### Description

Since updating to Xcode 14 from the beta I have seen a bug in the release version of our app that causes it to not even launch.  

The error in the debugger is 
`com.facebook.react.JavaScript (11): EXC_BAD_ACCESS (code=1, address=0xa028)`.

It fails at JSObjectGetPrivate(object).

### Version

0.68.0

### Output of `npx react-native info`

System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Max
    Memory: 4.31 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 3.2.3 - /opt/homebrew/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
    Watchman: 2022.08.22.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK: Not Found
  IDEs:
    Android Studio: Chipmunk 2021.2.1 Patch 1 Chipmunk 2021.2.1 Patch 1
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /opt/homebrew/opt/openjdk@11/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Nothing in my build environment has changed since using the beta, the app when built in release mode just crashes immediately upon launch.

### Snack, code example, screenshot, or link to a repository

<img width="1072" alt="Screen Shot 2022-09-29 at 3 57 02 AM" src="https://user-images.githubusercontent.com/1380829/192974059-e410e042-1796-4c21-939d-7bd490802a1f.png">

**Comment by roots-ai** [comment]
Any updates here?

**Comment by Saikedo** [comment]
Any updates on this? Facing the same issue.

**Comment by RomanSytnyk** [comment]
Any updates?

I'm facing this issue too

**Comment by ShaoGongBra** [comment]
me

**Comment by trickeyd** [comment]
me too - on react native 0.76
