### ISSUE TITLE
[Android] Gradle fails with `> BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 62`

### ISSUE THREAD

**Issue by ChurikiTenna** [facebook/react-native#34822]
### Description

```
warn Package react-native-navigation contains invalid configuration: "dependency.assets" is not allowed,"dependency.hooks" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
info Starting JS server...
info Installing the app...

FAILURE: Build failed with an exception.

* What went wrong:
Could not open settings remapped class cache for 2b2v1krlox0a6mjvnk5eb71wr (/Users/tenna/.gradle/caches/6.3/scripts-remapped/settings_1rtjkco7nerckjkpaki5l1zp5/2b2v1krlox0a6mjvnk5eb71wr/settingsdeec0faa97453e2ce860d75e6bf1604b).
> Could not open settings generic class cache for settings file '/Users/tenna/Desktop/aitem/android/settings.gradle' (/Users/tenna/.gradle/caches/6.3/scripts/2b2v1krlox0a6mjvnk5eb71wr/settings/settingsdeec0faa97453e2ce860d75e6bf1604b).
   > BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 62

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 649ms

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Could not open settings remapped class cache for 2b2v1krlox0a6mjvnk5eb71wr (/Users/tenna/.gradle/caches/6.3/scripts-remapped/settings_1rtjkco7nerckjkpaki5l1zp5/2b2v1krlox0a6mjvnk5eb71wr/settingsdeec0faa97453e2ce860d75e6bf1604b).
> Could not open settings generic class cache for settings file '/Users/tenna/Desktop/aitem/android/settings.gradle' (/Users/tenna/.gradle/caches/6.3/scripts/2b2v1krlox0a6mjvnk5eb71wr/settings/settingsdeec0faa97453e2ce860d75e6bf1604b).
   > BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 62

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 649ms

    at makeError (/Users/tenna/Desktop/aitem/node_modules/execa/index.js:174:9)
    at /Users/tenna/Desktop/aitem/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (/Users/tenna/Desktop/aitem/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:109:5)
    at async Command.handleAction (/Users/tenna/Desktop/aitem/node_modules/@react-native-community/cli/build/index.js:142:9)
info Run CLI with --verbose flag for more details.
```
I have done everything this page said: https://reactnative.dev/docs/environment-setup.
M1 Mac

### Version

0.7

### Output of `npx react-native info`

warn Package react-native-navigation contains invalid configuration: "dependency.assets" is not allowed,"dependency.hooks" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
info Fetching system and libraries information...
System:
    OS: macOS 12.5
    CPU: (8) arm64 Apple M1
    Memory: 114.81 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.11.0 - ~/.nodebrew/current/bin/node
    Yarn: 3.2.3 - ~/.yarn/bin/yarn
    npm: 8.0.0 - ~/.nodebrew/current/bin/npm
    Watchman: 2022.09.26.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 18.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^18.2.0 => 18.2.0 
    react-native: ^0.70.1 => 0.70.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

I can give an access to the repository if that'll help.

### Snack, code example, screenshot, or link to a repository

I can give an access to the repository if that'll help.
I am struggling with errors that coming on and on for days... Please help..

**Comment by cortinico** [comment]
> Java: 18.0.2 - /usr/bin/javac

What's your Gradle versions? You can find it inside the `android/gradle/gradle-wrapper.properties` file.

I believe you're on a old Gradle version which doesn't support Java 18.
As an alternative, movign to JDK 11 should solve your issue.

**Comment by Songlore** [comment]
I'm having the same error: 
A problem occurred configuring root project 'LittleLemonNewsletterFinal'.
> Could not open proj generic class cache for build file 'D:\LittleLemonNewsletterFinal\LittleLemonNewsletterFinal\android\build.gradle' (C:\Users\Owner\.gradle\caches\7.5.1\scripts\akkbmo69g46wo5egmq4ch1csu).
   > BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 63

**Comment by cortinico** [comment]
Closing as @ChurikiTenna is unresponsive. Feel free to re-open if the issue persists

**Comment by giovannicaprio** [comment]
Same issue here.

**Comment by Edgar256** [comment]
same issue here

**Comment by sundarsharma2018** [comment]
same issue here

**Comment by DragonStar373** [comment]
same issue here

**Comment by abeeku** [comment]
Try this
https://stackoverflow.com/questions/74695402/bug-exception-in-phase-semantic-analysis-in-source-unit-buildscript-unsup/74695403

Changing the distribution url in gradle-wrapper.properties to 7.6

**Comment by Hacimurad** [comment]
i face same error and  I solved my problem install idk 11;
follow this 
AndroidStudio->file->ProjectStructure->click Gradle Settings->choose idk 11 

[https://user-images.githubusercontent.com/12226661/170825694-d28dc202-d23d-4ed4-a2d8-035d84ad7b58.png](url)

**Comment by superdencho** [comment]
> Try this https://stackoverflow.com/questions/74695402/bug-exception-in-phase-semantic-analysis-in-source-unit-buildscript-unsup/74695403
> 
> Changing the distribution url in gradle-wrapper.properties to 7.6

That works! Thank you!

**Comment by moumen-engineer** [comment]
but which distribution of gradle (7.6-all.zip or 7.6-bin.zip . . .

**Comment by mattiarainieri** [comment]
What about eas build?

**Comment by ImadBouirmane** [comment]
> Try this https://stackoverflow.com/questions/74695402/bug-exception-in-phase-semantic-analysis-in-source-unit-buildscript-unsup/74695403
> 
> Changing the distribution url in gradle-wrapper.properties to 7.6

**The right solution, thanks men**

**Comment by tanmoy27112000** [comment]
SOLUTION:

go to android/gradle/wrapper/gradle-wrapper.properties

Find the distributionUrl variable and change the end path to gradle-7.6-all.zip

**Comment by ujangaripin24** [comment]
> Try this https://stackoverflow.com/questions/74695402/bug-exception-in-phase-semantic-analysis-in-source-unit-buildscript-unsup/74695403
> 
> Changing the distribution url in gradle-wrapper.properties to 7.6

thx dude, it's work for linux mint 21.1!!

**Comment by SushritPasupuleti** [comment]
> Try this https://stackoverflow.com/questions/74695402/bug-exception-in-phase-semantic-analysis-in-source-unit-buildscript-unsup/74695403
> 
> Changing the distribution url in gradle-wrapper.properties to 7.6

This doesn't seem to work anymore, as EAS just decides to use 7.5.1 no matter how many times gradle-wrapper.properties is changed.

**Comment by alz86** [comment]
If someone else is still in problems with this, the solution in my case was to align my version of Gradle with the Java one. There is a [compatibility matrix](https://docs.gradle.org/current/userguide/compatibility.html) that explains which version of Gradle works with which version of Java. By aligning them it worked on my env.

**Comment by YektaDev** [comment]
Can confirm. I started having this bug every now and then only after I upgraded the JDK version and the solution for me since I'm not planning on downgrading the JDK, was to instead **delete** the **`.gradle`** and **`build` directories** when this happens. Though it's strange that the behavior isn't deterministic. My guess is there are multiple versions of JDK being used by IDE/Gradle/etc.

**Comment by nikitaGrynch** [comment]
> <img alt="Screenshot 2023-12-15 at 12 07 04 PM" width="792" src="https://private-user-images.githubusercontent.com/142384733/290763364-d3230978-5586-447b-aa4d-b6db80916b09.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2NDc3NzgsIm5iZiI6MTcwMjY0NzQ3OCwicGF0aCI6Ii8xNDIzODQ3MzMvMjkwNzYzMzY0LWQzMjMwOTc4LTU1ODYtNDQ3Yi1hYTRkLWI2ZGI4MDkxNmIwOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNVQxMzM3NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMzg1Mjk5MDk1MmQzM2YyMDQzZjg5MjMyNzkwNDE2YTY1N2Y3OTM5OWNiMWFkZWE4YmMzMTc5MzIyOWYzMzEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RSLgS8LuHWJpRro6kXVy1ZDGCTmW2YwKR_Fkmp7GPHo">
> Any solution for React Native Expo ? expo run:android

same issue

**Comment by abdul-megadraws** [comment]
> > <img alt="Screenshot 2023-12-15 at 12 07 04 PM" width="792" src="https://private-user-images.githubusercontent.com/142384733/290763364-d3230978-5586-447b-aa4d-b6db80916b09.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2NDc3NzgsIm5iZiI6MTcwMjY0NzQ3OCwicGF0aCI6Ii8xNDIzODQ3MzMvMjkwNzYzMzY0LWQzMjMwOTc4LTU1ODYtNDQ3Yi1hYTRkLWI2ZGI4MDkxNmIwOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNVQxMzM3NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMzg1Mjk5MDk1MmQzM2YyMDQzZjg5MjMyNzkwNDE2YTY1N2Y3OTM5OWNiMWFkZWE4YmMzMTc5MzIyOWYzMzEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RSLgS8LuHWJpRro6kXVy1ZDGCTmW2YwKR_Fkmp7GPHo">
> > Any solution for React Native Expo ? expo run:android
> 
> same issue

Not Yet! Will update here once fix my side.

**Comment by ArnaudRm** [comment]
### For people using [Expo](https://expo.dev/) trying to build your app locally the "old way" with `expo run:android` or `npx react-native run-android` commands : 

 I came to understand that if you are in a managed Expo app, and you want to build your app locally , expo advises to use the "new way" of building locally with `eas build`(as documented [here](https://docs.expo.dev/build-reference/local-builds/))
The major issue for me here is that **creating the local build this way with `eas build` will count in your build usage on expo.dev**. 

Moreover, `ios` and `android` folders **are generated if you are in a managed workflow** , meaning you **cannot change the gradle version as advised [in this comment](https://github.com/facebook/react-native/issues/34822#issuecomment-1488013915) for example because this setting will be overriden the next time you perform a build via `eas build` command**

### **So, here's how I managed to run local builds with `expo run:android` or `react-native run-android`** 


- I checked the version of `gradle` used by Expo, in `android/gradle/wrapper/gradle-wrapper.properties`
- Then I looked at the [compatibility matrix](https://docs.gradle.org/current/userguide/compatibility.html) between java and gradle 
- Then, I **switched the java version that was installed locally to use one compatible with gradle version used by Expo**

**Comment by NaveenG46** [comment]
BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 65

what should i do ?
also having this error too - "Your project's Gradle version is incompatible with the Java version that Flutter is using for Gradle. "

Help me to overcome this ...

**Comment by Red3nzo** [comment]
@NaveenG46 having same issue as you, funny no one has found a solution

**Comment by AndreiSager** [comment]
@NaveenG46 @Red3nzo I have the same problem. I am trying to use realm with expo on a bare workflow but none of the solutions I've found have worked. 

I used the template given by expo. but I couldn't run it because I couldn't create a build.

```
> BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 66
```

**Comment by GStar718** [comment]
I'm sorry to hear that you're having trouble with using Realm in an Expo bare workflow. Here are some steps you might find helpful:

1. **Initialize the project**: You can start a new project with the `npx create-expo-app` command³. If you're using MongoDB Realm, you can use this command: `expo init ReplaceWithNameOfYourAPP --template @realm/expo-template-ts`².

2. **Rename App.js to App.tsx**: If you're using TypeScript, you'll need to rename your `App.js` file to `App.tsx`³.

3. **Create a tsconfig.json**: You'll need a `tsconfig.json` file in your project root. You can create one with the `touch tsconfig.json` command³.

4. **Run the project**: After setting up, you can run your project with `yarn start` or `npm run start`³.

**Comment by GStar718** [comment]
i've found this to be useful.
 
1. **Check the Java version used by Flutter**: You can do this by running `flutter doctor --verbose`.

2. **Update the Gradle version**: You need to update the Gradle version specified in your `android/gradle/wrapper/gradle-wrapper.properties` file to be compatible with the Java version. For Java 17, you should use Gradle 7.3 or newer.

3. **Change the Java version**: If updating Gradle doesn't work, you can change the Java version used by your project. You can do this by adding or changing `org.gradle.java.home` in your `gradle.properties` file to point to the appropriate Java version.

**Comment by GStar718** [comment]
Always good to recheck your basic steps as well.

if your having trouble with using Realm in an Expo bare workflow. Here are some steps you might find helpful:

1. **Initialize the project**: You can start a new project with the `npx create-expo-app` command³. If you're using MongoDB Realm, you can use this command: `expo init ReplaceWithNameOfYourAPP --template @realm/expo-template-ts`.

2. **Rename App.js to App.tsx**: If you're using TypeScript, you'll need to rename your `App.js` file to `App.tsx`.

3. **Create a tsconfig.json**: You'll need a `tsconfig.json` file in your project root. You can create one with the `touch tsconfig.json` command.

4. **Run the project**: After setting up, you can run your project with `yarn start` or `npm run start`.

Remember, the bare workflow requires a good understanding of native development for both iOS and Android platforms. Developers should be familiar with Objective-C, Swift, Java, and Kotlin, in addition to JavaScript.

**Comment by GStar718** [comment]
> @NaveenG46 having same issue as you, funny no one has found a solution

`scroll down`

**Comment by aaadhilll** [comment]
BUG! exception in phase 'semantic analysis' in source unit '/Users/aswin/Desktop/dev/flutter/packages/flutter_tools/gradle/src/main/groovy/app_plugin_loader.groovy' Unsupported class file major version 64

**Comment by aaadhilll** [comment]
what to do???

**Comment by AnuDesai-24** [comment]
BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 63
