### ISSUE TITLE
Trojan:Script/Wacatac.H!ml

### ISSUE THREAD

**Issue by kagaya25** [facebook/react-native#34839]
### Description

Trojan files founds after compile the files

Trojan:Script/Wacatac.H!ml

This program is dangerous and executes commands from an attacker.

file\android\app\build\outputs\apk\release\app-universal-release.apk

### Version

0.64.0

### Output of `npx react-native info`

there is no error this happen after making the signed apk file 

### Steps to reproduce

How this happen 
Publishing to Google Play Store
Generating an upload key
 Step 1 👍  keytool -genkeypair -v -storetype PKCS12 -keystore my-upload-key.keystore -alias my-key-alias -keyalg RSA -keysize 2048 -validity 10000

Step 2 
 Setting up Gradle variables
Place the my-upload-key.keystore file under the android/app directory in your project folder.
Edit the file ~/.gradle/gradle.properties or android/gradle.properties, and add the following (replace ***** with the correct keystore password, alias and key password),
MYAPP_UPLOAD_STORE_FILE=my-upload-key.keystore
MYAPP_UPLOAD_KEY_ALIAS=my-key-alias
MYAPP_UPLOAD_STORE_PASSWORD=*****
MYAPP_UPLOAD_KEY_PASSWORD=*****

Adding signing config to your app's Gradle config

...
android {
    ...
    defaultConfig { ... }
    signingConfigs {
        release {
            if (project.hasProperty('MYAPP_UPLOAD_STORE_FILE')) {
                storeFile file(MYAPP_UPLOAD_STORE_FILE)
                storePassword MYAPP_UPLOAD_STORE_PASSWORD
                keyAlias MYAPP_UPLOAD_KEY_ALIAS
                keyPassword MYAPP_UPLOAD_KEY_PASSWORD
            }
        }
    }
    buildTypes {
        release {
            ...
            signingConfig signingConfigs.release
        }
    }
}
...

Step 3 
Generating the release AAB
Run the following in a terminal:

cd android
./gradlew bundleRelease

### Snack, code example, screenshot, or link to a repository

![Capture](https://user-images.githubusercontent.com/69753843/193455504-224c530e-118c-4b54-b625-da6c11c6b49b.JPG)

**Comment by cortinico** [comment]
Thanks for reporting this @kagaya25 
I believe this could be related to some of your 3rd party dependency you import.

Please submit security related bugs like this one using the process described here: 
https://reactnative.dev/contributing/overview#security-bugs
