### ISSUE TITLE
Invariant Violation: "main" has not been registered. This can happen if: * Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.

### ISSUE THREAD

**Issue by mohit-garg-elentra** [facebook/react-native#34837]
### New Version

0.69.6

### Old Version

0.63.2

### Build Target(s)

iOS simulator in debug/release flavor

### Output of `react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 12.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 405.17 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.16.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.11.0 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.6 => 0.69.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Issue and Reproduction Steps

1. yarn install
2. yarn upgrade --latest  // at that time latest is react-native V0.69.6
3. yarn start
4. Press a │ open Android
› Press i │ open iOS simulator // iOS iPhone 8

Do follow above steps you can face this error on mobile screen while launching app, also same error on server terminal(yarn start) can be observed.

Thanks.
![Simulator Screen Shot - iPhone 8 - 2022-10-02 at 05 45 33](https://user-images.githubusercontent.com/113445609/193432732-867bbfc0-6811-4cc2-9a00-b65972cc7153.png)
![Simulator Screen Shot - iPhone 8 - 2022-10-02 at 05 45 49](https://user-images.githubusercontent.com/113445609/193432733-b302672f-d078-42f8-af02-5183fcabe63d.png)

**Comment by cortinico** [comment]
> yarn upgrade --latest // at that time latest is react-native V0.69.6\

As you're upgrading from 0.63 to 0.69, most likely you'll have to do some manual tweaking (as there are several versions in between). Usually this command will tell you if there are manual steps to do if the update failed.

Also having a reproducer would help here.

**Comment by dinbtechit** [comment]
same error here as well.

```
 ERROR  Invariant Violation: "APPName" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes
```
