### ISSUE TITLE
iOS iCloud+ "Hide My Email" feature freezes application if canceled

### ISSUE THREAD

**Issue by MyPalVikram** [facebook/react-native#34833]
### Description

I'm working through the sign-up portion of my auth flow and while testing on my device I noticed that the iCloud+ "Hide My Email" feature renders the application frozen if it's canceled.

### Version

0.70.1

### Output of `npx react-native info`

```
System:
    OS: macOS 13.0
    CPU: (10) arm64 Apple M1 Max
    Memory: 1.05 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.9.0 - /opt/homebrew/bin/node
    Yarn: 1.22.18 - ~/.yarn/bin/yarn
    npm: 8.19.2 - /opt/homebrew/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /Users/vikrampal/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8815526
    Xcode: 14.0/14A309 - /usr/bin/xcodebuild
  Languages:
    Java: 18.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.1 => 0.70.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

On an actual iOS device with iCloud+, tapping on the email address field of a signup form will present you with a quick action of "Hide My Email". Pressing on that will open up a menu about your email options. Once you cancel this/do not move forward when you return to the application it will be frozen.

### Snack, code example, screenshot, or link to a repository

While the iCloud+ menu is open, screenshots of the menu do not appear in the actual image.

**Comment by scalessec** [comment]
This was a bug in iOS 16, not React Native. It has been fixed as of iSO 16.1.1, so I believe this ticket can be closed.
