### ISSUE TITLE
Unable to find a specification for `React-Core` depended upon by `EXSplashScreen`

### ISSUE THREAD

**Issue by cankilinc** [facebook/react-native#34836]
### Description

When I trying pod install in ios folder I getting this error.

Unable to find a specification for `React-Core` depended upon by `EXSplashScreen`

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

### Version

0.69.6

### Output of `npx react-native info`

System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 117.50 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.2 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.7.0 - /usr/local/bin/npm
    Watchman: 2022.09.26.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: javac 19 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

When I trying pod install in ios folder I getting this error.

Unable to find a specification for `React-Core` depended upon by `EXSplashScreen`

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

### Snack, code example, screenshot, or link to a repository

When I trying pod install in ios folder I getting this error.

Unable to find a specification for `React-Core` depended upon by `EXSplashScreen`

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

**Comment by cortinico** [comment]
Hi @cankilinc 
Thanks for reporting this issue.

I believe this issue is related to `expo-splash-screen` and the way how it integrates with React Native core. Please open this issue against this other repository:

https://github.com/expo/expo/issues

I'll be closing this but feel free to reopen if the other repo points back to us as a issue in the core of React Native.
