### ISSUE TITLE
initialScrollIndex in flatlist is not working as expected

### ISSUE THREAD

**Issue by anisamirouche** [facebook/react-native#34832]
### Description

initialScrollIndex is not working as expected, always returing another element

### Version

0.69..5

### Output of `npx react-native info`

System:
    OS: macOS 12.5.1
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 57.20 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.15.0 - /usr/local/bin/npm
    Watchman: 2022.08.29.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK:
      API Levels: 26, 28, 29, 30, 31
      Build Tools: 29.0.0, 29.0.1, 29.0.2, 29.0.3, 30.0.0, 30.0.1, 30.0.2, 30.0.3, 31.0.0, 32.0.0
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom_64, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-30 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom_64, android-31 | Intel x86 Atom_64, android-31 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 18.0.1 - /usr/local/opt/openjdk/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0
    react-native: 0.69.6 => 0.69.6
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

new expo bare react native project with simple flatlist and array of elements

### Snack, code example, screenshot, or link to a repository

``` js
 <FlatList
        ref={listRef}
        initialScrollIndex={id}
        data={posts}
        renderItem={({ item }) => (
          <View style={styles.element} key={item.id}>
            <Post img={item.img} type="all" />
            <View>
              <Text>Liked by</Text>
            </View>
            <View>
              <Text>{item.date}</Text>
            </View>
          </View>
        )}
      />

```

Link to reproductible example:
https://github.com/anisamirouche/ig_example

**Comment by NickGerleman** [comment]
Could you help provide some more specifics? E.g. What are you passing to `initialScrollIndex`? A runnable repro would be helpful.

**Comment by anisamirouche** [comment]
> ⚠️	Missing Reproducible Example
> ℹ️	It looks like your issue is missing a reproducible example. Please provide a [Snack](https://snack.expo.dev) or a repository that demonstrates the issue you are reporting in a [minimal, complete, and reproducible](https://stackoverflow.com/help/minimal-reproducible-example) manner.


https://github.com/anisamirouche/ig_example

**Comment by anisamirouche** [comment]
> Could you help provide some more specifics? E.g. What are you passing to `initialScrollIndex`? A runnable repro would be helpful.

this is a a runnable repro, i'm passing to initialScrollIndex an index which i got it as props from another component

**Comment by anisamirouche** [comment]
> > Could you help provide some more specifics? E.g. What are you passing to `initialScrollIndex`? A runnable repro would be helpful.
> 
> this is a a runnable repro https://github.com/anisamirouche/ig_example.
I'm passing to initialScrollIndex an index (number) which i got it as props from another component
