### ISSUE TITLE
[iOS] Unable to archive & export build after updating react-native 0.70.1

### ISSUE THREAD

**Issue by harleenarora** [facebook/react-native#34841]
### Description

When using latest React-native version, an error occurs when attempting to archive and export a release build through xcodebuild.

```

`ipatool failed with an exception: #<CmdSpec::NonZeroExitException: $ Xcode.app/Contents/Developer/usr/bin/python3 /Xcode.app/Contents/Developer/usr/bin/bitcode-build-tool -v -t /Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin --sdk /Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.2.sdk -o /var/folders/v1/wd4zzzf10pzbbgtwf94wnb4h0000gn/T/ipatool20221003-10540-akdneb/thinned-out/arm64/Payload/BookingKoala\ For\ Providers.app/Frameworks/hermes.framework/hermes --generate-dsym /var/folders/v1/wd4zzzf10pzbbgtwf94wnb4h0000gn/T/ipatool20221003-10540-akdneb/thinned-out/arm64/Payload/BookingKoala\ For\ Providers.app/Frameworks/hermes.framework/hermes.dSYM --strip-swift-symbols /var/folders/v1/wd4zzzf10pzbbgtwf94wnb4h0000gn/T/ipatool20221003-10540-akdneb/thinned-in/arm64/Payload/BookingKoala\ For\ Providers.app/Frameworks/hermes.framework/hermes
Status: pid 10975 exit 1
Stdout:
    SDK path: /Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.2.sdk` 
```

### Version

0.70.1

### Output of `npx react-native info`

System:
    OS: macOS 11.3
    CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
    Memory: 384.45 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.1 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^18.2.0 => 18.2.0 
    react-native: ^0.70.1 => 0.70.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Updated react-native version 
Ensure you have XCode <= 13.2.1
Attempt to archive and export a release build using xcodebuild

### Snack, code example, screenshot, or link to a repository

Update the react-native version, not able to produce an archive and export

**Comment by cipolleschi** [comment]
Hi there, thank you for opening this. Can you try to archive a new app?
To create it:
`npx react-native init TestArchive --version 0.70.1`

Also, do you have a specific need to use Xcode <= 13.2.1? 
It is pretty outdated: the most recent Xcode 13 version is 13.4 and there is already Xcode 14 out of the beta.

I tried to reproduce it, but I don't have a team ID to sign them.

**Comment by wine1** [comment]
I have the same problem,if anybody resolve this,could you please tell me how :(

**Comment by cipolleschi** [comment]
☝️ Could you do the above test ad provide the requested information? We cannot help anyone if we don't establish a baseline and we don't have more informations.
