### ISSUE TITLE
'react-native init' error : npm ERR! Command failed: git fetch -a origin

### ISSUE THREAD

**Issue by mc-zone** [facebook/react-native#3484]
An error has occurred while I trying to initialize a react-native project by: `react-native init awesomeProject`:

    Installing react-native package from npm...
    `npm install --save react-native` failed

Then I run this npm command manually , the errors looks like happen here:
    
    npm verb afterAdd /Users/mc-zone/.npm/joi/6.9.1/package/package.json not in flight; writing
    npm verb afterAdd /Users/mc-zone/.npm/joi/6.9.1/package/package.json written
    npm ERR! git fetch -a origin (git://github.com/facebook/react.git) fatal: Unable to create temporary file '/Users/mc-zone/.npm/_git-remotes/git-github-com-facebook-react-git-baa2986b/./objects/pack/tmp_pack_XXXXXX': Permission denied
    npm ERR! git fetch -a origin (git://github.com/facebook/react.git) fatal: index-pack failed
    npm verb about to build /Users/mc-zone/_dev/rn/node_modules/react-native
    npm verb unlock done using /Users/mc-zone/.npm/_locks/react-native-ce52a7d7697a2d98.lock for /Users/mc-zone/_dev/rn/node_modules/react-native
    npm verb stack Error: Command failed: git fetch -a origin
    npm verb stack fatal: Unable to create temporary file '/Users/mc-zone/.npm/_git-remotes/git-github-com-facebook-react-git-baa2986b/./objects/pack/tmp_pack_XXXXXX': Permission denied
    npm verb stack fatal: index-pack failed
    npm verb stack
    npm verb stack     at ChildProcess.exithandler (child_process.js:203:12)
    npm verb stack     at emitTwo (events.js:87:13)
    npm verb stack     at ChildProcess.emit (events.js:172:7)
    npm verb stack     at maybeClose (internal/child_process.js:818:16)
    npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
    npm verb cwd /Users/mc-zone/_dev/rn
    npm ERR! Darwin 14.3.0
    npm ERR! argv "/Users/mc-zone/.nvm/versions/node/v4.2.1/bin/node" "/Users/mc-zone/.nvm/versions/node/v4.2.1/bin/npm" "install" "react-native" "--save"
    npm ERR! node v4.2.1
    npm ERR! npm  v2.14.7
    npm ERR! code 128
    
    npm ERR! Command failed: git fetch -a origin
    npm ERR! fatal: Unable to create temporary file '/Users/mc-zone/.npm/_git-remotes/git-github-com-facebook-react-git-baa2986b/./objects/pack/tmp_pack_XXXXXX': Permission denied
    npm ERR! fatal: index-pack failed
    npm ERR!
    npm ERR!
    npm ERR! If you need help, you may report this error at:
    npm ERR!     <https://github.com/npm/npm/issues>
    npm verb exit [ 1, true ]

Seems to be a permission problem, I also use `sudo chown -R $USER ~/.npm` still not working.

And this `npm install` is excuted by `react-native-cli` so I can't add the `sudo` command to `npm`  (`sudo react-native init ` still can't work )

How can I resolve this?

========

Other infomation: 

System: Mac OS X 10.10.3

`npm` is installed by `nvm` when install `node`.

`nvm` is installed by `brew`.

    $ npm -v 
    2.14.7
    $ node -v
    v4.2.1

And there is my folders permissions (want to init application in `_dev`):

    drwxrwxrwx  521 mc-zone  staff   17714 10 17 19:20 .npm
    -rw-------    1 mc-zone  staff      56 10 17 17:01 .npmrc
    drwxrwxrwx    5 mc-zone  staff     170 10 17 16:57 .nvm
    drwxrwxrwx    4 mc-zone  staff     136 10 16 23:15 _dev

**Comment by ide** [comment]
You could try blowing away `.npm` with `npm cache clean`. Barring that this might be a bug for npm upstream since react-native doesn't seem to be doing anything special here.

**Comment by mc-zone** [comment]
@ide  What should I do In this case?  Reinstall npm can resolve it ? 
Would be very grateful If you can provide some solutions. I  have been obsessed me for 2 days.

**Comment by mc-zone** [comment]
@ide  I tried `npm cache clean`, even uninstalled `npm` and completely reinstalled it again still not work. But it return to normal when I updated my OS X version to 10.11. Maybe there was some problem in my OS file system about permissions. So wierd.. Anyway, thank you for your tip.

**Comment by ide** [comment]
Using the OS X disk utility to repair file permissions + restarting your computer might have helped as well (this happens during upgrades). Glad you got it fixed.
