### ISSUE TITLE
There is a problem working with react-native (expo), it is not possible to connect with the phone at all!

### ISSUE THREAD

**Issue by ramiljs** [facebook/react-native#34840]
### Description

There is a problem working with react-native (expo), it is not possible to connect with the phone at all!

![photo_2022-10-02_20-42-32](https://user-images.githubusercontent.com/89657343/193466670-b751e42c-f48c-4f65-b9d1-fc5cb0655af8.jpg)

![Снимок](https://user-images.githubusercontent.com/89657343/193466516-a3f80216-dbe3-4fbd-ae24-0eb466ffd1ca.PNG)

### Version

0.69.6

### Output of `npx react-native info`

npx react-native info
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.19042
    CPU: (4) x64 Intel(R) Core(TM) i3-1005G1 CPU @ 1.20GHz
    Memory: 4.25 GB / 7.79 GB
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.5.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: Not Found
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0
    react-native: 0.69.6 => 0.69.6
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

There is a problem working with react-native (expo), it is not possible to connect with the phone at all!

### Snack, code example, screenshot, or link to a repository

https://snack.expo.dev/@ramildeveloper/8b5274

**Comment by cortinico** [comment]
> There is a problem working with react-native (expo), it is not possible to connect with the phone at all!

Hi @ramiljs 
Thanks for reporting this issue.

As you mentioned, it seems like this issue is actually unrelated to React Native core but related to Expo. Please open this issue against this other repository:

https://github.com/expo/epxo/issues

I'll be closing this but feel free to reopen if the other repo points back to us as a issue in the core of React Native.
