### ISSUE TITLE
The `pod' command exists in these Ruby versions

### ISSUE THREAD

**Issue by mantegnous** [facebook/react-native#34842]
### New Version

0.70.1

### Old Version

0.64

### Build Target(s)

ios build

### Output of `react-native info`

System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1 Pro
    Memory: 9.76 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.1 - /usr/local/bin/node
    Yarn: Not Found
    npm: 8.15.0 - /usr/local/bin/npm
    Watchman: 2022.07.04.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^18.2.0 => 18.2.0 
    react-native: ^0.70.1 => 0.70.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Issue and Reproduction Steps

just upgraded, and i see this error on build ios

rbenv: pod: command not found
The `pod' command exists in these Ruby versions:
2.6.9
command failed, error: exit status 127

cocoapods-install@2.3 (exit code: 1)

**Comment by cortinico** [comment]
> rbenv: pod: command not found
> The `pod' command exists in these Ruby versions:
> 2.6.9
> command failed, error: exit status 127

You're on the wrong Ruby version. You should be on 2.7.5.
Please follow the instructions here: https://reactnative.dev/docs/environment-setup#ruby and report if the issue persists

**Comment by mantegnous** [comment]
@cortinico i'm in 2.7.5, but this command is available in 2.6.9

**Comment by cortinico** [comment]
Do you also have `bundler` installed?

**Comment by mantegnous** [comment]
@cortinico the problem is on bitrise build, step CocoaPods because do "pod" command without bundler

**Comment by subwizzll** [comment]
try editing you pod.js file in the `./node_modules/@expo/build-tools/dist/ios/pod.js` file:

adding this seemed to help the file find pod:

```
    // Set Ruby version locally to 3.1.4
    await (0, turtle_spawn_1.default)('rbenv', ['local', '3.1.4'], {
        cwd: iosDir,
        logger: ctx.logger,
        env: ctx.env,
    });
```

```
"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.installPods = void 0;
const path_1 = __importDefault(require("path"));
const turtle_spawn_1 = __importDefault(require("@expo/turtle-spawn"));
async function installPods(ctx, { infoCallbackFn }) {
    const iosDir = path_1.default.join(ctx.getReactNativeProjectDirectory(), 'ios');

    // Set Ruby version locally to 3.1.4
    await (0, turtle_spawn_1.default)('rbenv', ['local', '3.1.4'], {
        cwd: iosDir,
        logger: ctx.logger,
        env: ctx.env,
    });

    // Now proceed with pod install
    return {
        spawnPromise: (0, turtle_spawn_1.default)('pod', ['install'], {
            cwd: iosDir,
            logger: ctx.logger,
            env: {
                ...ctx.env,
                LANG: 'en_US.UTF-8',
                ...(ctx.env.EAS_BUILD_COCOAPODS_CACHE_URL
                    ? { NEXUS_COCOAPODS_REPO_URL: ctx.env.EAS_BUILD_COCOAPODS_CACHE_URL }
                    : {}),
            },
            lineTransformer: (line) => {
                if (!line ||
                    /\[!\] '[\w-]+' uses the unencrypted 'http' protocol to transfer the Pod\./.exec(line)) {
                    return null;
                } else {
                    return line;
                }
            },
            infoCallbackFn,
        }),
    };
}
exports.installPods = installPods;
//# sourceMappingURL=pod.js.map
```
