### ISSUE TITLE
Error: Requiring module "node_modules/react-native-reanimated/src/index.ts

### ISSUE THREAD

**Issue by ru88s** [facebook/react-native#34856]
### Description

Error: Requiring module "node_modules/react-native-reanimated/src/index.ts", which threw an exception: Error: Failed to initialize react-native-reanimated library, make sure you followed installation steps here: https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation/ 
1) Make sure reanimated's babel plugin is installed in your babel.config.js (you should have 'react-native-reanimated/plugin' listed there - also see the above link for details) 
2) Make sure you reset build cache after updating the config, run: yarn start --reset-cache

### Version

0.69.6

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 11.6.8
    CPU: (8) x64 Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
    Memory: 1.46 GB / 32.00 GB
    Shell: 5.8 - /usr/local/bin/zsh
  Binaries:
    Node: 14.16.1 - /usr/local/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 6.14.12 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 19, 21, 22, 23, 24, 26, 27, 28
      Build Tools: 23.0.2, 23.0.3, 25.0.0, 26.0.2, 27.0.3, 28.0.3
      System Images: android-22 | Google APIs Intel x86 Atom, android-23 | Android TV ARM EABI v7a, android-23 | Android TV Intel x86 Atom, android-23 | Android Wear ARM EABI v7a, android-23 | Android Wear Intel x86 Atom, android-23 | ARM EABI v7a, android-23 | Intel x86 Atom, android-23 | Intel x86 Atom_64, android-23 | Google APIs ARM EABI v7a, android-23 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-24 | Google Play Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-N | Android TV Intel x86 Atom, android-N | Intel x86 Atom, android-N | Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6308749
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_131 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: ^0.69.6 => 0.69.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

"expo": "^46.0.14",
"react-native-reanimated": "^2.10.0",

```
module.exports = function (api) {
  api.cache(true);
  return {
    presets: ["babel-preset-expo"],
    plugins: ["react-native-reanimated/plugin"],
  };
};
```

### Snack, code example, screenshot, or link to a repository

![スクリーンショット 2022-10-04 13 59 02](https://user-images.githubusercontent.com/42270511/193737916-a119b23c-448b-477c-9aaa-ec51c5ba4373.png)

**Comment by cortinico** [comment]
> "node_modules/react-native-reanimated/src/index.ts"

Hi,
Thanks for reporting this issue.

It seems like this issue is actually unrelated to React Native core but related to Reanimated. Please open this issue against this other repository:

https://github.com/software-mansion/react-native-reanimated/issues

I'll be closing this but feel free to reopen if the other repo points back to us as a issue in the core of React Native.
