### ISSUE TITLE
Strange new dependencies in android bundle

### ISSUE THREAD

**Issue by nes123** [facebook/react-native#34852]
<img width="706" alt="Screen Shot 2022-10-04 at 9 47 08" src="https://user-images.githubusercontent.com/7921778/193776102-0a6cfdbe-a02f-41da-aadf-fc3eb4497110.png">
### Description

sqlite4java.dll is included in the base root directory in the bundle for mac, and windows. There is another IBM folder inside base/root/com that seems to be related to java runtime libraries that didn't show up before.

I didn't change anything in the configuration and it was not there in previous versions, so i am not sure where it came from. 

Any ideas?

### Version

0.68.3

### Output of `npx react-native info`

System:
    OS: macOS 12.6
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 28.41 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.0.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 8.8.0 - ~/workspace/****/node_modules/.bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8139111
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.3 => 0.68.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

./gradlew bundleRelease

### Snack, code example, screenshot, or link to a repository

N/A

**Comment by cortinico** [comment]
> sqlite4java.dll is included in the base root directory in the bundle for mac, and windows

Can you provide more context? What is the "bundle for man and windows"? Are you using react-native-macos or react-native-windows?

What is the screenshot you posted on top? Is that an unzip of the final apk/app bundle?

**Comment by nes123** [comment]
> sqlite4java.dll

Thank you for your reply. The screenshot shows the bundle composition. There is base/root/com/ibm folder that was not there before. There is also libsqlite4java.dll under windows and mac folders that didn't show up before.

I am not using  react-native-macos or react-native-windows

**Comment by cortinico** [comment]
> I am not using react-native-macos or react-native-windows. I am creating a bundle to be deployed on Android, and don't understand why windows/mac libraries are being bundled and causing the size to increase considerably.

Can you share your package.json?
Can you verify that this is happening also on a empty project?

**Comment by nes123** [comment]
`{
  "name": "***",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest",
    "postinstall": "npx jetify && patch-package",
    "lint": "eslint ."
  },
  "dependencies": {
    "@invertase/react-native-apple-authentication": "^2.2.2",
    "@react-native-community/audio-toolkit": "^2.0.3",
    "@react-native-community/geolocation": "^3.0.1",
    "@react-native-community/image-editor": "^2.3.0",
    "@react-native-community/netinfo": "^9.3.0",
    "@react-native-community/progress-bar-android": "^1.0.4",
    "@react-native-community/progress-view": "^1.3.1",
    "@react-native-community/slider": "^4.2.2",
    "@react-native-firebase/analytics": "^15.6.0",
    "@react-native-firebase/app": "^15.6.0",
    "@react-native-firebase/auth": "^15.6.0",
    "@react-native-firebase/crashlytics": "^15.6.0",
    "@react-native-firebase/database": "^15.6.0",
    "@react-native-firebase/dynamic-links": "^15.6.0",
    "@react-native-firebase/messaging": "^15.6.0",
    "@react-native-firebase/storage": "^15.6.0",
    "@react-native-google-signin/google-signin": "^8.0.0",
    "@react-native-picker/picker": "^2.4.2",
    "apsl-react-native-button": "^3.1.1",
    "autosuggest": "0.0.2",
    "deprecated-react-native-listview": "^0.0.8",
    "events": "^3.3.0",
    "fbjs": "^3.0.4",
    "geofire": "5.2.0",
    "geolib": "^3.3.3",
    "hermes-engine": "0.11.0",
    "i18n-js": "^4.1.1",
    "jsc-android": "^250230.2.1",
    "lodash": "^4.17.21",
    "prop-types": "^15.8.1",
    "react": "17.0.2",
    "react-native": "0.68.3",
    "react-native-action-button": "^2.8.5",
    "react-native-android-location-enabler": "^1.2.2",
    "react-native-animatable": "^1.3.3",
    "react-native-appsflyer": "^6.5.21",
    "react-native-autocomplete-input": "^5.1.0",
    "react-native-blob-util": "^0.16.0",
    "react-native-cached-image": "^1.4.3",
    "react-native-calendar-strip": "^2.2.6",
    "react-native-calendars": "^1.1285.0",
    "react-native-camera": "^4.2.1",
    "react-native-clean-project": "^4.0.1",
    "react-native-contacts": "^7.0.4",
    "react-native-deprecated-custom-components": "github:facebookarchive/react-native-custom-components",
    "react-native-exif": "github:francisco-sanchez-molina/react-native-exif",
    "react-native-fast-image": "^8.6.1",
    "react-native-geocoder-reborn": "^0.9.0",
    "react-native-geolocation-service": "github:Agontuk/react-native-geolocation-service",
    "react-native-htmlview": "^0.16.0",
    "react-native-i18n": "^2.0.15",
    "react-native-iap": "8.6.7",
    "react-native-image-pan-zoom": "^2.1.12",
    "react-native-image-picker": "^4.8.1",
    "react-native-image-progress": "^1.2.0",
    "react-native-image-resizer": "^1.4.5",
    "react-native-image-zoom-viewer": "^3.0.1",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-link-preview": "^1.4.2",
    "react-native-maps": "^1.3.1",
    "react-native-material-menu": "^2.0.0",
    "react-native-modalbox": "github:nes123/react-native-modalbox",
    "react-native-parsed-text": "0.0.22",
    "react-native-pdf": "^6.5.0",
    "react-native-permissions": "^3.4.0",
    "react-native-phone-input": "^1.3.3",
    "react-native-pinchable": "^0.2.1",
    "react-native-progress": "^5.0.0",
    "react-native-rate": "^1.2.9",
    "react-native-sha256": "^1.4.7",
    "react-native-shadow": "^1.2.2",
    "react-native-share": "^7.9.0",
    "react-native-side-menu": "^1.1.3",
    "react-native-sideswipe": "^1.5.0",
    "react-native-snap-carousel": "^3.9.1",
    "react-native-spinkit": "^1.5.1",
    "react-native-star-rating": "^1.1.0",
    "react-native-svg": "^12.3.0",
    "react-native-swipe-gestures": "^1.0.5",
    "react-native-swipe-list-view": "^3.2.9",
    "react-native-switch": "^2.0.0",
    "react-native-textinput-effects": "^0.6.2",
    "react-native-tracking-transparency": "^0.1.2",
    "react-native-view-shot": "^3.1.2",
    "react-native-webview": "^11.18.2",
    "tcomb-form-native": "^0.6.20",
    "util": "^0.12.4",
    "victory-native": "^36.5.3"
  },
  "devDependencies": {
    "@babel/core": "^7.17.10",
    "@babel/runtime": "^7.17.9",
    "@bugsnag/react-native": "^7.17.2",
    "@bugsnag/source-maps": "^2.3.1",
    "@grpc/grpc-js": "^1.6.7",
    "@react-native-community/eslint-config": "^3.0.1",
    "@welldone-software/why-did-you-render": "^7.0.1",
    "babel-jest": "^28.0.3",
    "babel-plugin-transform-remove-console": "^6.9.4",
    "eslint": "^8.14.0",
    "install": "^0.13.0",
    "jest": "^28.0.3",
    "jest-cli": "^28.0.3",
    "jetifier": "^2.0.0",
    "metro-bundler": "^0.22.1",
    "metro-react-native-babel-preset": "^0.70.3",
    "npm": "^8.8.0",
    "npm-check-updates": "^15.0.3",
    "patch-package": "^6.4.7",
    "postinstall-postinstall": "^2.1.0",
    "react-native-bundle-visualizer": "^3.1.1",
    "react-test-renderer": "17.0.2",
    "stacktrace-parser": "^0.1.10"
  },
  "resolutions": {
    "react-devtools-core": "4.10.0"
  },
  "jest": {
    "preset": "react-native"
  },
  "rnpm": {
    "assets": [
      "./assets/fonts"
    ]
  }
}
`

**Comment by nes123** [comment]
Didn't check it in empty project

**Comment by nes123** [comment]
Is there a simple way to find out where the com.ibm.icu dependency came from?

**Comment by nes123** [comment]
After some more investigation, I see that the bundle contains testing components in the dex classes and base folder. These are libraries that show up here:

https://github.com/facebook/react-native/blob/main/ReactAndroid/src/test/java/com/facebook/react/bridge/BaseJavaModuleTest.java

How come the release bundle suddenly started to include these files? Any help will be much appreciated.

**Comment by nes123** [comment]
Can close. The problem is with the new facebook SDK. 

com.facebook.android:facebook-android-sdk:15.0.1

I imported it with a + and the new version includes these unwanted dependencies.
