### ISSUE TITLE
I can't initialize the project with npx react-native init command

### ISSUE THREAD

**Issue by BerkePalamutcu** [facebook/react-native#34855]
### Description

I just try to create react native app without expo and I get this issue. I looked everywhere for solution but couldn't find an answer. I can create react native apps by expo and ignite but this just doesn't work and I don't want to use neither expo nor ignite for the project I want to make. Any solutions regarding this one?

### Version

0.70

### Output of `npx react-native info`

System:
    OS: Linux 5.15 Linux Mint 21 (Vanessa)
    CPU: (16) x64 Intel(R) Core(TM) i7-10870H CPU @ 2.20GHz
    Memory: 11.36 GB / 15.41 GB
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.17.1 - /usr/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.19.2 - /usr/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 11.0.16 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
  npmGlobalPackages:

I have android studio and android sdk installed already but I have no idea why I get this.

### Steps to reproduce

The command to install just doesnt work

### Snack, code example, screenshot, or link to a repository

![Screenshot from 2022-10-03 21-39-45](https://user-images.githubusercontent.com/78186900/193708585-2804a741-dcf3-460a-bf60-7c53d4569f1c.png)

**Comment by cortinico** [comment]
It seems like you have a really old version of yarn installed, potentially globally:
https://github.com/yarnpkg/yarn/issues/3377

You can check with `yarn --version`.
You should be fine by invoking `npm install -g yarn` to update it.

**Comment by BerkePalamutcu** [comment]
> It seems like you have a really old version of yarn installed, potentially globally: [yarnpkg/yarn#3377](https://github.com/yarnpkg/yarn/issues/3377)
> 
> You can check with `yarn --version`. You should be fine by invoking `npm install -g yarn` to update it.

I checked the yarn's last version and I have the last version. I still have the issue and I can't understand why bot closes the topic whereas I specified  my environment information?

**Comment by cortinico** [comment]
> I checked the yarn's last version and I have the last version.

What's the output of `yarn --version`?
