### ISSUE TITLE
com.facebook.react.JavaScript (9): EXC_BAD_ACCESS (code=1, address=0xffffa0000c250698 [iOS]

### ISSUE THREAD

**Issue by roots-ai** [facebook/react-native#34867]
### Description

I was facing the error
[TypeError: undefined is not an object 'installCoreFunctions' react-native-reanimated [iOS]](https://stackoverflow.com/questions/73917181/typeerror-undefined-is-not-an-object-installcorefunctions-react-native-reanim)

and after making the changes as mentioned above, the error went away, but the app started crashing with on the start with a new error `com.facebook.react.JavaScript (9): EXC_BAD_ACCESS (code=1, address=0xffffa0000c250698`.

### Version

0.70.1

### Output of `npx react-native info`

System:
    OS: macOS 12.6.1
    CPU: (4) x64 Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
    Memory: 1.00 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.17.6 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.18.0 - ~/Projects/Odo/node_modules/.bin/npm
    Watchman: 2022.07.04.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.4 - /Users/Test/.rvm/gems/ruby-2.4.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK:
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2.3 AI-162.4069837
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^18.1.0 => 18.1.0 
    react-native: ^0.70.1 => 0.70.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Tried with two version of podfile, but no changes
[Podfile](https://wtools.io/paste-code/bFAW)
[Podifle V2](https://wtools.io/paste-code/bFBc)

[package.json](https://wtools.io/paste-code/bFAY)
[AppDelegate.m](https://wtools.io/paste-code/bFAZ)
[AppDelegate.h](https://wtools.io/paste-code/bFBa)

### Snack, code example, screenshot, or link to a repository

<img width="730" alt="Screenshot 2022-10-04 at 12 58 13 PM" src="https://user-images.githubusercontent.com/1976061/193921587-182465b4-7445-45da-8f0a-61af1706f5eb.png">
<img width="1271" alt="Screenshot 2022-10-04 at 12 41 59 PM" src="https://user-images.githubusercontent.com/1976061/193921626-1fbc01bd-00d9-4bf1-a05f-9becb4861d16.png">

**Comment by cortinico** [comment]
> [TypeError: undefined is not an object 'installCoreFunctions' react-native-reanimated [iOS]](https://stackoverflow.com/questions/73917181/typeerror-undefined-is-not-an-object-installcorefunctions-react-native-reanim)

Hi,
Thanks for reporting this issue.

It seems like this issue is actually unrelated to React Native core but related to Reanimated. Please open this issue against this other repository:

https://github.com/software-mansion/react-native-reanimated/issues

I'll be closing this but feel free to reopen if the other repo points back to us as a issue in the core of React Native.

**Comment by RomanSytnyk** [comment]
Also facing this problem

Have you solved it @roots-ai?

Thanks

**Comment by roots-ai** [comment]
Yes, this got solved by following the RN upgrade guidelines, but other issues popped up https://github.com/facebook/react-native/issues/35029

**Comment by oceanwap** [comment]
I am getting same issue.

I am writing an SQLITE interface for react native application, right now I am stuck implementation of sqlite3_create_function_v2.

The end interface looks like this 

```typescript

db.function('add', (a, b) => a + b);

db.exec ('select add(?, ?)', [12, 4]);

```

Inside react native I pass the reference of this function to sqlite function `sqlite3_create_function_v2` which then executes this function.

I am able to execute this function if I don't pass it to `sqlite3_create_function_v2` but when it's executed by sqlite (sqlite3_create_function_v2) then I get this error `com.facebook.react.JavaScript (9): EXC_BAD_ACCESS (code=1, address=0x0)`.

@roots-ai  Is there any way to fix this issue?
