### ISSUE TITLE
React Native Android Build with new architecture enabled is failing 

### ISSUE THREAD

**Issue by nkjs-git** [facebook/react-native#34877]
### Description

When newArchEnabled is set to true in android/gradle.properties and do npm run android the build is failing in my local machine(as well as in pipeline).  

`> Task :react-native-reanimated:configureCMakeRelWithDebInfo FAILED
C/C++: release|x86 :CMake Error at CMakeLists.txt:74 (add_library):
C/C++: release|x86 :  Cannot find source file:
C/C++: release|x86 :    /home/vsts/work/1/s/node_modules/react-native-reanimated/Common/cpp/Fabric/FabricUtils.cpp
C/C++: release|x86 :  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
C/C++: release|x86 :  .hpp .hxx .in .txx
C/C++: release|x86 :CMake Error at CMakeLists.txt:74 (add_library):
C/C++: release|x86 :  No SOURCES given to target: reanimated
C/C++: release|x86 :CMake Generate step failed.  Build files cannot be regenerated correctly.
w: Detected multiple Kotlin daemon sessions at build/kotlin/sessions

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-reanimated:configureCMakeRelWithDebInfo'.
> [CXX1405] error when building with cmake using /home/vsts/work/1/s/node_modules/react-native-reanimated/android/CMakeLists.txt: Build command failed.
  Error while executing process /usr/local/lib/android/sdk/cmake/3.18.1/bin/cmake with arguments {-H/home/vsts/work/1/s/node_modules/react-native-reanimated/android -DCMAKE_SYSTEM_NAME=Android -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_SYSTEM_VERSION=21 -DANDROID_PLATFORM=android-21 -DANDROID_ABI=x86 -DCMAKE_ANDROID_ARCH_ABI=x86 -DANDROID_NDK=/usr/local/lib/android/sdk/ndk/21.4.7075529 -DCMAKE_ANDROID_NDK=/usr/local/lib/android/sdk/ndk/21.4.7075529 -DCMAKE_TOOLCHAIN_FILE=/usr/local/lib/android/sdk/ndk/21.4.7075529/build/cmake/android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=/usr/local/lib/android/sdk/cmake/3.18.1/bin/ninja -DCMAKE_CXX_FLAGS=-fstack-protector-all -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/vsts/work/1/s/node_modules/react-native-reanimated/android/build/intermediates/cxx/RelWithDebInfo/454f4f59/obj/x86 -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=/home/vsts/work/1/s/node_modules/react-native-reanimated/android/build/intermediates/cxx/RelWithDebInfo/454f4f59/obj/x86 -DCMAKE_BUILD_TYPE=RelWithDebInfo -B/home/vsts/work/1/s/node_modules/react-native-reanimated/android/.cxx/RelWithDebInfo/454f4f59/x86 -GNinja -DANDROID_STL=c++_shared -DNATIVE_DEBUG=false -DREACT_NATIVE_TARGET_VERSION=68 -DANDROID_TOOLCHAIN=clang -DBOOST_VERSION=1_63_0 -DNODE_MODULES_DIR=/home/vsts/work/1/s/node_modules -DJS_RUNTIME=jsc -DJS_RUNTIME_DIR=/home/vsts/work/1/s/node_modules/react-native/ReactCommon/jsi -DCLIENT_SIDE_BUILD=true -DIS_NEW_ARCHITECTURE_ENABLED=true -DPLAYGROUND_APP_NAME=s -DRNVERSION=68}
  -- Detecting C compiler ABI info`

### Version

0.68.2

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 12.3.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 28.55 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.17.0 - /usr/local/opt/node@16/bin/node
    Yarn: Not Found
    npm: 8.15.0 - /usr/local/opt/node@16/bin/npm
    Watchman: 2022.09.05.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8309675
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 18.0.1.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.2 => 0.68.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
info React Native v0.70.2 is now available (your project is running on v0.68.2).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.70.2.
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.68.2.
info To upgrade, run "react-native upgrade"

### Steps to reproduce

enable the newArchitecture in android/gradle.properties and do npm i && npm run android

### Snack, code example, screenshot, or link to a repository

package.json is as below

`{
  "name": "myclient-mobile-cross-platform",
  "version": "1.0.0",
  "scripts": {
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "android:dev": "npx react-native run-android --variant=devdebug",
    "android:qa": "npx react-native run-android --variant=qadebug",
    "android:demo": "npx react-native run-android --variant=demodebug",
    "android:prod": "npx react-native run-android --variant=proddebug",
    "ios:dev": "npx react-native run-ios --scheme \"plmtrustlinkmobilecrossplatformDev\"",
    "ios:prod": "npx react-native run-ios --scheme \"plmtrustlinkmobilecrossplatformProd\"",
    "ios:demo": "npx react-native run-ios --scheme \"plmtrustlinkmobilecrossplatformDemo\"",
    "ios:qa": "npx react-native run-ios --scheme \"plmtrustlinkmobilecrossplatformQA\""
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "~1.17.3",
    "@react-navigation/drawer": "^6.4.3",
    "@react-navigation/native": "^6.0.11",
    "@react-navigation/native-stack": "^6.7.0",
    "buffer": "^6.0.3",
    "expo": "~45.0.0",
    "expo-barcode-scanner": "~11.3.0",
    "expo-splash-screen": "~0.15.1",
    "expo-status-bar": "~1.3.0",
    "gs1-barcode-parser": "^1.0.1",
    "jexl": "^2.3.0",
    "jwt-decode": "^3.1.2",
    "moment": "^2.29.4",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-native": "0.68.2",
    "react-native-config": "^1.4.6",
    "react-native-dialog-input": "^1.0.8",
    "react-native-gesture-handler": "~2.2.1",
    "react-native-modal": "^13.0.1",
    "react-native-pager-view": "5.4.15",
    "react-native-reanimated": "^2.9.1",
    "react-native-restart": "^0.0.24",
    "react-native-safe-area-context": "4.2.4",
    "react-native-screens": "~3.11.1",
    "react-native-select-dropdown": "^2.0.4",
    "react-native-splash-screen": "^3.3.0",
    "react-native-step-indicator": "^1.0.3",
    "react-native-svg": "^12.4.3",
    "react-native-tab-view": "^3.1.1",
    "react-native-uuid": "^2.0.1",
    "react-native-vector-icons": "^9.2.0",
    "react-native-web": "0.17.7",
    "react-native-webview": "^11.22.7",
    "react-timer-mixin": "^0.13.4",
    "uuidv4": "^6.2.13",
    "expo-camera": "~12.2.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9"
  },
  "private": true
}
`

**Comment by cortinico** [comment]
> `> Task :react-native-reanimated:configureCMakeRelWithDebInfo FAILED

Hi,
Thanks for reporting this issue.

It seems like this issue is actually unrelated to React Native core, but from the build log it looks related to Reanimated and to the way how they interact with the native build. Please open this issue against this other repository:

https://github.com/software-mansion/react-native-reanimated/issues

I'll be closing this but feel free to reopen if the other repo points back to us as a issue in the core of React Native.
