### ISSUE TITLE
Build phase taking too long even with the correct flags

### ISSUE THREAD

**Issue by lucaswitch** [facebook/react-native#34873]
### Description

![image](https://user-images.githubusercontent.com/29023475/194141778-23d87fc8-31fb-4104-bb0a-b659cbe12215.png)

### Version

0.70.1

### Output of `npx react-native info`

After migrate from 0.63.4 to 0.70.1 the build takes about 20 minutes on task ReactAndroid:hermes-engine:buildCMakeRelease[arm64-v8a][libhermes]

### Steps to reproduce

Install 0.63.4 app
Upgrade to 0.70.1 using migration guide steps.
Gradle configuration as following:
![image](https://user-images.githubusercontent.com/29023475/194142394-e4586a75-0f3f-436b-accc-2e210ca217ba.png)
Hermes engine enabled

### Snack, code example, screenshot, or link to a repository

Also it comes with a bunch of warnings similar to this
![image](https://user-images.githubusercontent.com/29023475/194142692-70dc0d9a-99ac-4032-bba5-d3a1dba81057.png)

**Comment by cortinico** [comment]
> After migrate from 0.63.4 to 0.70.1 the build takes about 20 minutes on task ReactAndroid:hermes-engine:buildCMakeRelease[arm64-v8a][libhermes]

That's happening only for the New Architecture.

Are you using the `--active-arch-only` flag suggested here?
https://reactnative.dev/docs/build-speed#build-only-one-abi-during-development-android-only

Moreover, please look into setting up `ccache` as suggested in the same page.

Sadly this is "expected" as of now. React Native 0.71 will contain improvements on the build time that should alleviate those situations

**Comment by lucaswitch** [comment]
I'm always using --archive-arch-only and ccache is completely enabled and working.

**Comment by lucaswitch** [comment]
Thank you, we will wait until 0.71 for a upgrade.
