### ISSUE TITLE
[Text] Animated.Text not working as expected (0.12)

### ISSUE THREAD

**Issue by IlyasM** [facebook/react-native#3487]
```
<Animated.Text style={[{
					fontSize:12*k,
					height:this.showFloat.interpolate({inputRange:[0,1],outputRange:[0,14*k]})},
					styles.buttonText]}>Cancel</Animated.Text>
```
This used to work on 0.11 or earlier but on 0.12 text 'Cancel' always present no matter what this.showFloat value is. Seems like a bug

**Comment by brentvatne** [comment]
@IlyasM - please re-create this on rnplay.org so we can see it working on 0.11 :)

**Comment by IlyasM** [comment]
@brentvatne  here is the demo of it working on 0.11
 https://rnplay.org/apps/3W7DUA - thanks for sharing this awesome tool:)

**Comment by almasakchabayev** [comment]
Have the same issue

**Comment by brentvatne** [comment]
@browniefed - do you want to look into this? :)

**Comment by browniefed** [comment]
@brentvatne already know the issue. `height: 0` no longer works in .12 and after. You can see the issue logged here https://github.com/facebook/react-native/issues/3397

**Comment by browniefed** [comment]
@brentvatne looks like the fix is in, css-layout needs to probably get revved in React Native https://github.com/facebook/css-layout/pull/134

**Comment by jcsmesquita** [comment]
+1

**Comment by browniefed** [comment]
This can be closed @brentvatne solved with css-layout merged awhile ago
