### ISSUE TITLE
TextInput wrong onChange call after value set (multiline, ios)

### ISSUE THREAD

**Issue by eyshella** [facebook/react-native#34891]
### Description

`TextInput` component calls onChange callback with empty string right after `blur` method was called when backspace button was pressed few times on empty input. This can make it impossible to set value from outside in specific environment.
The issue reproducible only on `iOS` when `multiline` is set.
You can find more details in steps to reproduce.

### Version

0.70.2

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1
    Memory: 106.98 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: Not Found
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 14.0/14A309 - /usr/bin/xcodebuild
  Languages:
    Java: javac 19 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.2 => 0.70.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. Use iOS environment
1. Add `TextInput` component with `multiline` set to `true`
3. Add `onChangeCallback` callback and use it in `TextInput` `onChange` method (set `event` as an argument)
4. Add `inputRef` reference and use it as `TextInput` ref
5. Add a `TouchableOpacity` outside input
6. Add `onButtonPressCallback` callback and use it in `TouchableOpacity` `onPress` method
7. Add state value `inputValue` with `setInputValue` setter and use as `TextInput` `value` prop.
8. Add the following to the `onChangeCallback`: `
  setInputValue(event.nativeEvent.text)
`
9. Add the following to the `onButtonPressCallback`: `
  setInputValue("I am test string!")
  inputRef.current.blur()
`
10. Run the project
11. Focus input field and press backspace button on the keyboard few times
12. Press the button (`TouchableOpacity`) without manual  reseting focus from the input field
13. As you see - input value hasn't been set.

### Snack, code example, screenshot, or link to a repository

https://snack.expo.dev/@eyshella/textinput-multiline-weird-onchange

**Comment by bashen1** [comment]
same issue

**Comment by Limoer96** [comment]
how to fix that?

**Comment by akarri2001** [comment]
This is late, but instead of using onChange, I switched it out for onChangeText and it worked
