### ISSUE TITLE
<WebView> Make renderError and renderLoading optional

### ISSUE THREAD

**Issue by vjeux** [facebook/react-native#349]
Right now both of those props are required but if you forgot to add them, it crashes in a non obvious way. 

https://www.dropbox.com/s/j2ajkigbl5iae84/Screen%20Shot%202015-03-27%20at%2011.44.42%20PM.png?dl=0

We should make them optional and provide a good looking default. This is a good first task if anyone is interested in helping out.

**Comment by abarth** [comment]
Looks like this bug is fixed by #512.  Should we close this issue?

**Comment by donyu** [comment]
Yup thanks for catching this! I forgot to close it after the PR.
