### ISSUE TITLE
Using -PreactNativeArchitectures=x86 still builds all archetypes

### ISSUE THREAD

**Issue by Waltari10** [facebook/react-native#34902]
### Description

I would like to build different android production ABIs one at a time e.q. x86, x86_64, arm64-v8a and so on.

However when I try to use `-PreactNativeArchitectures=x86` it just anyway builds all archetypes at once. I believe this is the case because in the .aab `~/foo/android/app/build/outputs/bundle/release/app-release/base/lib` it has all 4 folders for each archetype as shown in the screenshot. Also the .aab file is exactly the same whether I run it with or whitout `PreactNativeArchitectures` argument.
<img width="984" alt="Screenshot 2022-10-08 at 10 44 42" src="https://user-images.githubusercontent.com/8919286/194716069-1bb36dd2-a710-429c-94c0-e75e06ae5bec.png">

Am I using `PreactNativeArchitectures` wrong or is there some other issue? It's a brand new project with zero changes so I don't think I could have broken it. How do you verify which ABI archetypes were actually built?

### Version

0.70.2

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 12.6
    CPU: (8) x64 Apple M1
    Memory: 117.55 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.18.3 - ~/.nvm/versions/node/v14.18.3/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.3/bin/npm
    Watchman: 2022.10.03.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/valtterilaine/.rvm/gems/ruby-3.0.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8815526
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.12 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.2 => 0.70.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Run in Android folder of project:
` ./gradlew clean bundleRelease -PreactNativeArchitectures=x86` 

Still get all archetypes and a perfectly identical .aab file as if you ran just ` ./gradlew clean bundleRelease` 

<img width="984" alt="Screenshot 2022-10-08 at 10 44 42" src="https://user-images.githubusercontent.com/8919286/194715935-a5ea6c3a-7ba2-4f35-92db-503ff3972887.png">

### Snack, code example, screenshot, or link to a repository

`npx react-native init foo`

`cd foo/android`

` ./gradlew clean bundleRelease -PreactNativeArchitectures=x86`

Still get all archetypes and a perfectly identical .aab file as if you ran just ` ./gradlew clean bundleRelease` 

<img width="984" alt="Screenshot 2022-10-08 at 10 44 42" src="https://user-images.githubusercontent.com/8919286/194715935-a5ea6c3a-7ba2-4f35-92db-503ff3972887.png">

**Comment by cortinico** [comment]
> Am I using `PreactNativeArchitectures` wrong or is there some other issue? It's a brand new project with zero changes so I don't think I could have broken it. How do you verify which ABI archetypes were actually built?

You're using the correct command, but if you want to build split bundles/APKs you'll have to enable it in the template:

https://github.com/facebook/react-native/blob/0db5178688d838689ece5cc246e4ec1ec7f2e607/template/android/app/build.gradle#L95

**Comment by Waltari10** [comment]
> > Am I using `PreactNativeArchitectures` wrong or is there some other issue? It's a brand new project with zero changes so I don't think I could have broken it. How do you verify which ABI archetypes were actually built?
> 
> You're using the correct command, but if you want to build split bundles/APKs you'll have to enable it in the template:
> 
> https://github.com/facebook/react-native/blob/0db5178688d838689ece5cc246e4ec1ec7f2e607/template/android/app/build.gradle#L95

Thanks, I did not spot that before! However it is still building everything.

Looking at the `app/build.gradle` file is `PreactNativeArchitectures` actually only available if you have fabric enabled, since `abiFilters` property is wrapped inside if clause with `isNewArchitectureEnabled`?

 ```
       buildConfigField "boolean", "IS_NEW_ARCHITECTURE_ENABLED", isNewArchitectureEnabled().toString()

        if (isNewArchitectureEnabled()) {
            // We configure the CMake build only if you decide to opt-in for the New Architecture.
            externalNativeBuild {
                cmake {
                    arguments "-DPROJECT_BUILD_DIR=$buildDir",
                        "-DREACT_ANDROID_DIR=$rootDir/../node_modules/react-native/ReactAndroid",
                        "-DREACT_ANDROID_BUILD_DIR=$rootDir/../node_modules/react-native/ReactAndroid/build",
                        "-DNODE_MODULES_DIR=$rootDir/../node_modules",
                        "-DANDROID_STL=c++_shared"
                }
            }
            if (!enableSeparateBuildPerCPUArchitecture) {
                ndk {
                    abiFilters (*reactNativeArchitectures())
                }
            }
        }
```

**Comment by Waltari10** [comment]
Even if I define `splits` like this in `app/build.gradle` it still builds everything and has zero effect. Bundle size is the same and all the architectures are seemingly included in the .aab file.

```
    splits {
        abi {
            reset()
            enable true
            universalApk false  // If true, also generate a universal APK
            include "x86"
        }
    }
```

**Comment by cortinico** [comment]
> However it is still building everything

Seems like App Bundles don't support ABI split. I believe this is because the ABI split is done by the Play Store so the `splits` configuration is ignored.

If you were to create an APK instead:

```
./gradlew clean assembleRelease -PreactNativeArchitectures=x86
```

You'll have a x86-only APK that you can install on your device directly.

**Comment by Waltari10** [comment]
Thank you, it seems to be finally working! 

A little bit disappointed though, it seems it takes about as long to generate all four builds as it takes to build just one :D Thought I'd save time by building them in parallel.
