### ISSUE TITLE
[Style] rotateY and rotateX transforms not working on Android

### ISSUE THREAD

**Issue by felipemartim** [facebook/react-native#3491]
Hi guys,

I'm trying to do implement a simple card flip animation on Android, but after some hours of messing with the Animated API I found out the 3D transforms are not working properly. I looked everywhere for a solution but I don't know what to do. Is there a workaround for this?

I created a simple RN Playground app in order to prove it: https://rnplay.org/apps/wOggQQ

As you can see, it works as expected in iOS.

**Comment by chirag04** [comment]
cc @mkonicek It can confirm this problem.

related: https://github.com/facebook/react-native/issues/2915, https://github.com/facebook/react-native/issues/2999

**Comment by danielbm** [comment]
This problem is also happening to me

**Comment by felipemartim** [comment]
It seems that rotateY and rotateX are not being set on the native android View component. React decomposes the transform matrix with the following properties:
```javascript
decomposedMatrix : {
    rotate: 0,
    scaleX: 1,
    scaleY: 1,
    translateX: 0,
    translateY: 0
}
```
I believe the solution would be to alter the return statement of the function "decomposeMatrix" of MatrixMath.js to

```javascript
    // expose both base data and convenience names
    return {
      rotationDegrees,
      perspective,
      quaternion,
      scale,
      skew,
      translation,

      rotateX: rotationDegrees[0],
      rotateY: rotationDegrees[1],
      rotateZ: rotationDegrees[2],
      scaleX: scale[0],
      scaleY: scale[1],
      translateX: translation[0],
      translateY: translation[1],
    };
```

and then, on BaseViewManager.java

```java
  private static final String PROP_DECOMPOSED_MATRIX = "decomposedMatrix";
  private static final String PROP_DECOMPOSED_MATRIX_ROTATE_X = "rotateX";
  private static final String PROP_DECOMPOSED_MATRIX_ROTATE_Y = "rotateY";
  private static final String PROP_DECOMPOSED_MATRIX_ROTATE_Z = "rotateZ";
  private static final String PROP_DECOMPOSED_MATRIX_SCALE_X = "scaleX";
  private static final String PROP_DECOMPOSED_MATRIX_SCALE_Y = "scaleY";
  private static final String PROP_DECOMPOSED_MATRIX_TRANSLATE_X = "translateX";
  private static final String PROP_DECOMPOSED_MATRIX_TRANSLATE_Y = "translateY";

  private static final String PROP_ROTATION_X = "rotationX";
  private static final String PROP_ROTATION_Y = "rotationY";
  private static final String PROP_ROTATION_Z = "rotation";
  private static final String PROP_SCALE_X = "scaleX";
  private static final String PROP_SCALE_Y = "scaleY";
  private static final String PROP_TRANSLATE_X = "translateX";
  private static final String PROP_TRANSLATE_Y = "translateY";

  @ReactProp(name = PROP_ROTATION_X)
  public void setRotationX(T view, float rotationX) {
    view.setRotationX(rotationX);
  }

  @ReactProp(name = PROP_ROTATION_Y)
  public void setRotationY(T view, float rotationY) {
    view.setRotationY(rotationY);
  }
```

Also, do that on BaseViewPropertyApplicator.java. The problem is that I have no clue on how to edit the Java classes and recompile it for my project. I'm completely new to React Nativa. Any ideas?

**Comment by chirag04** [comment]
you can follow the approach here: https://github.com/facebook/react-native/issues/3337#issuecomment-147243916 to compile react native with your changes from the node_modules/react-native dir in your project

Let me know if get it working with your changes.

Quick Tip: you may find redbox with inverse3x3 not found error. just replace inverse3x3 with inverse and transpose4x4 with transpose in matrixMath.js

**Comment by felipemartim** [comment]
@chirag04 It worked! 

However I had to implement a workaround for setting "perspective" in Android Views using the setCameraDistance() method with the same logic I used for setting rotationX and rotationY. I'm not sure if it's good for a PR though, because that perspectiveMatrix logic seems too complex for me.

```javascript
    // expose both base data and convenience names
    return {
      rotationDegrees,
      perspective,
      quaternion,
      scale,
      skew,
      translation,

      perspectiveZ: perspective[2] != 0 ? -1/perspective[2] : 0, //do not divide by 0!
      rotateX: rotationDegrees[0],
      rotateY: rotationDegrees[1],
      rotateZ: rotationDegrees[2],
      scaleX: scale[0],
      scaleY: scale[1],
      translateX: translation[0],
      translateY: translation[1],
    };
```

At least now I am able to reproduce the card flip effect I was hoping for.

**Comment by chirag04** [comment]
@felipemartim awesome. I wanted card flip in my app as well. I had the exact same problems as urs. I'm glad you could figure it out.

I can help you with the PR since i originally added perspective. First, can you share all the changes you made to get rotateX, etc working?

**Comment by browniefed** [comment]
Skewx and skewy are also supported properties in the iOS version. Does android support them?

**Comment by chirag04** [comment]
Looks like skewx,y is not supported. It would be easy to support them i guess once we get the changes from @felipemartim

**Comment by felipemartim** [comment]
@chirag04 I'll send a PR later today, whenever I can. Is perspective working already?

@browniefed I'm not an Android developer, but I think maybe by working with the [Matrix](http://developer.android.com/reference/android/graphics/Matrix.html) attribute of the View, we could implement this functionality.

**Comment by chirag04** [comment]
Awesome. I'm looking forward to your PR. perspective is working on ios. You can look at Matrixmath and add perspective stuff also in your PR. +100 for adding skewx,y also. ;)

**Comment by felipemartim** [comment]
@chirag04 here it goes https://github.com/facebook/react-native/pull/3522
@browniefed I believe skewX and skewY are ok!

**Comment by satya164** [comment]
rotateX and rotateY have been already implemented.
