### ISSUE TITLE
Bug when use value as children of TextInput

### ISSUE THREAD

**Issue by Pietro-Putelli** [facebook/react-native#34914]
### Description

I'm having some problems using <TextInput> component in React Native 0.70.2.
Specifically I need to put the text like this <TextInput> {children} </TextInput>, instead of passing a value prop, because I need to manipulate text for creating a mention text input. 
By doing this, in React Native before 0.70 it worked, but with the next version what happen is shown in the video.

https://user-images.githubusercontent.com/64473929/194781923-7a314cef-6522-424d-a085-9a70478bd390.MP4

### Version

0.70.2

### Output of `npx react-native info`

System:
    OS: macOS 12.6
    CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
    Memory: 171.40 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.3.2 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.2 => 0.70.2
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Create a TextInput component, set value using onChangeText and put this value as children of the tags.

### Snack, code example, screenshot, or link to a repository

https://snack.expo.dev/@pietroputelli/bbbed6

**Comment by birgernass** [comment]
This issue just got fixed with [0.70.3](https://github.com/facebook/react-native/releases/tag/v0.70.3).

**Comment by fabriziobertoglio1987** [comment]
Do you still experience this issue? 

I have four years of experience maintaining facebook/react-native and I specialize in the Text and TextInput components. I currently have 58 [facebook/react-native PRs](https://github.com/facebook/react-native/pulls?q=is%3Apr+author%3Afabriziobertoglio1987+). 

If you still experience this issue, I will prepare a patched release with the fix.

Thanks a lot
