### ISSUE TITLE
No suitable image URL loader found for (v0.13.0-rc)

### ISSUE THREAD

**Issue by olofd** [facebook/react-native#3494]
After upgrading to v0.13.0-rc i get the following error for images. (All images).

```No suitable image URL loader found for data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADIAAAAyCAYAAAAeP4ixAAAAAXNSR…35RAAD8pBj5vpZjZ71LXwgbV0vYXLj9NTZm6R7Dka7/Q+G5FcOipn+rwAAAABJRU5ErkJggg==.......```

have cleaned, restarted computer etc. defaultSource seems to display image, but not source. 
Images lock like this: 
```<Image source={require('image!logowhite')} style={styles.logo}/>```

Downgraded to v0.12.0-rc and all images workes fine again.

**Comment by marcshilling** [comment]
Subscribing, same issue here.

**Comment by ide** [comment]
cc @javache @jspahrsummers

**Comment by javache** [comment]
I think @nicklockwood fixed this in https://github.com/facebook/react-native/commit/1076f4a172069b4d9e8f9d194f0f924341e354e2

**Comment by grabbou** [comment]
@ide Can we please have 0.13.1? Otherwise, there's no way we can upgrade to 0.13 (and possibly other people as well?)

**Comment by despairblue** [comment]
Probably 0.13.2 since there is already a 0.13.1 patch release, but yeah, I'd appreciate this as well.

**Comment by ide** [comment]
Published 0.13.2 with some cherry-picks: https://github.com/facebook/react-native/commits/0.13-stable. Images worked in Movies and UIExplorer apps -- lmk how this is working for you.

**Comment by despairblue** [comment]
:clap: thank you. Loading base64 encoded images works fine.

**Comment by ide** [comment]
Thanks for the confirmation.
