### ISSUE TITLE
Cannot read property 'jsx' of undefined

### ISSUE THREAD

**Issue by kovkev** [facebook/react-native#34957]
### Description

Start up a new project and use module `@react-navigation/stack` . 

You will encounter this error

`Cannot read property 'jsx' of undefined` . It points to line 21 of `./node_modules/@react-navigation/stack/src/views/Screens.tsx` , which is simply a jsx component instantiation.

### Version

0.70.1

### Output of `npx react-native info`

```
% npx react-native info                                          
warn Package @sentry/react-native contains invalid configuration: "dependency.platforms.ios.sharedLibraries" is not allowed,"dependency.hooks" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
info Fetching system and libraries information...
System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 108.97 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.7.0 - /opt/homebrew/bin/node
    Yarn: 1.22.17 - /opt/local/bin/yarn
    npm: 8.4.0 - ~/node_modules/.bin/npm
    Watchman: 2022.08.08.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK:
      API Levels: 28, 29, 30, 31, 32
      Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs ARM 64 v8a, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play ARM 64 v8a, android-31 | ARM 64 v8a, android-31 | Google APIs ARM 64 v8a, android-32 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.1 => 0.70.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
% 
```

### Steps to reproduce

Create a new project

Use `@react-navigation/stack` 

### Snack, code example, screenshot, or link to a repository

<img width="434" alt="image" src="https://user-images.githubusercontent.com/30991911/195351473-15f0f111-c378-4114-a19a-e960da5a7618.png">

**Comment by Isopodus** [comment]
I can confirm the same behavior on this minimal example:
```
import React from 'react';
import {createStackNavigator} from '@react-navigation/stack';
import {NavigationContainer} from '@react-navigation/native';
import {Test} from 'Test';

const Stack = createStackNavigator();

const App = () => {
    return (
        <NavigationContainer>
            <Stack.Navigator initialRouteName={'test'}>
                <Stack.Screen name={'test'} component={Test} />
            </Stack.Navigator>
        </NavigationContainer>
    );
};

export default App;

```
Deps:
```
    "@react-navigation/native": "^6.0.13",
    "@react-navigation/stack": "^6.3.2",
    "react": "18.1.0",
    "react-native": "0.70.1",

**Comment by cortinico** [comment]
> Start up a new project and use module `@react-navigation/stack` .

Hi @kovkev 
Thanks for reporting this issue.

It seems like this issue is related to React Navigation. 
Please open this issue against this other repository:

https://github.com/react-navigation/react-navigation/issues

I'll be closing this but feel free to reopen if the other repo points back to us as a issue in the core of React Native.

**Comment by sefailyasoz95** [comment]
Hi @kovkev , you need to install this lib => react-native-screens

**Comment by AdiKhaparkar123** [comment]
it didnt work for me  still getting the same issue

**Comment by RogerioDoCarmo** [comment]
For me installing the react-native-screens lib also fixed the issue.

**Comment by elgambet** [comment]
> it didnt work for me still getting the same issue

Maybe you forgot to run pod install and yarn ios (on IOS) or yarn android (on Android)?

**Comment by ChanhyukPark-Tech** [comment]
npm install react-native-reanimated react-native-gesture-handler react-native-screens react-native-safe-area-context @react-native-community/masked-view

**Comment by azeezat** [comment]
On iOS, you also need to do the following after running `yarn add react-native-screens`

1. `cd ios`
2. `pod install`
3. restart your dev server

**Comment by MirzaYaseen** [comment]
> react-native-screens
Thank you so much, it's working for me
