### ISSUE TITLE
Image source URL properties containing `localhost` do not work

### ISSUE THREAD

**Issue by adamterlson** [facebook/react-native#3496]
Experienced behavior on iOS.

I'm serving an image locally from a web server, bound identically under two hostnames:  `http://localhost:3000/myImage.png` and `http://foobar:3000/myImage.png`

Works as expected:
`<Image source={{uri: 'http://foobar:3000/myImage.png'}} />`

However, the following does not work, and no request hits the server hosted server at all, so may not be making the request at all or it may be mangled/routed somewhere unexpected.
`<Image source={{uri: 'http://localhost:3000/myImage.png'}} />`

**Comment by nautical** [comment]
@adamterlson , Can you once try opening the same image in the simulators safari .

**Comment by adamterlson** [comment]
The image loads in Safari.

**Comment by nautical** [comment]
Also please make sure to allow http services in simulator (settings>developer) . I tried and its working perfectly , can you specify your version of react ntive and please assign width and height also to the image .

![screen shot 2015-10-19 at 4 07 58 am](https://cloud.githubusercontent.com/assets/4836107/10567086/05e15ec8-7617-11e5-96c2-1ac0002b7208.png)

**Comment by adamterlson** [comment]
Sorry, I didn't specify the width and height in my code to just focus on the bit that changed.

That Allow HTTP Services did it!  Why is that setting required to access an image hosted at `http://localhost` but not `http://foobar`, do you know?

**Comment by nautical** [comment]
Please refer to this https://forums.developer.apple.com/thread/6205 .

**Comment by adamterlson** [comment]
Sorry, can you link to the specific post that's relevant or summarize?  It's a bit dense for me to be honest and reading through it didn't find any explanation for this behavior. 

Otherwise, no problem, thanks for the help!

**Comment by browniefed** [comment]
@facebook-github-bot answered
