### ISSUE TITLE
Undefined symbols for architecture x86_64: "_jump_fcontext" & "_make_fcontext" 

### ISSUE THREAD

**Issue by rahulgpt1** [facebook/react-native#34982]
> @rahulgpt1 there is no expectation this will work below react-native 0.69.1
> 
> > The patch put into 0.69.1 explicitly defines those symbols via linker directives

Hi Mike,

As you said hermes wouldn't work in RN version 0.68.2, but you people resolved this issue in RN version 0.69.1 so I updated my RN version to 0.69.1 but it still gives the same error undefined symbol for "_jump_fcontext" & "_make_fcontext".

See the attached screenshot:
<img width="1374" alt="Hermes_Undefined_Symbol" src="https://user-images.githubusercontent.com/16076685/195770569-78fe1fd6-872a-411f-baf1-c68f9e91343e.png">

System Detail:
1. MacOS Monterey (12.2.1)
2. MacBook Pro (M1 Chip)
3. Xcode 13.0

Pod File Configuration Details:
1. use_frameworks! (Not using)
4. modular_headers => true (For some of the pods like below)
    pod 'CNIOLinux', '= 2.20.2',:modular_headers => true
    pod 'CNIODarwin', '= 2.20.2',:modular_headers => true
    pod 'CNIOAtomics', '= 2.20.2',:modular_headers => true
    pod 'CNIOSHA1', '= 2.20.2',:modular_headers => true
    pod 'CNIOHTTPParser', '= 2.20.2',:modular_headers => true
    pod 'CNIOBoringSSL','= 2.9',:modular_headers => true
    pod 'CNIOBoringSSLShims','= 2.9',:modular_headers => true
    pod 'CGRPCZlib', '= 1.0.0-alpha.18',:modular_headers => true
5. Bitcode : (Tried both by enabling and disabling)

Thanks

_Originally posted by @rahulgpt1 in https://github.com/facebook/react-native/issues/34030#issuecomment-1278516370_

**Comment by mikehardy** [comment]
Please make a reproduction and post it, starting with `npx react-native init ProjectName`, committing that, then just committing the changes required to show the error.

I do similar and do not reproduce, via my build test harness here https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh (but with `use_frameworks`, so may not apply, just saying you can make a reproduction

https://stackoverflow.com/help/minimal-reproducible-example

**Comment by rahulgpt1** [comment]
Hi Mike,

Now I am having another issue '**react/bridging/CallbackWrapper.h' file not found** when building the app(whether hermes is enabled or disabled). In my project I have already applied the path for **react-native+0.69.1.patch**
I tried https://github.com/facebook/react-native/issues/34102#issuecomment-1180727214 this solution but that doesn't work for me and also tried  https://github.com/facebook/react-native/issues/34102#issuecomment-1185518186 but no luck. Please have a look on attached screenshot.
<img width="1440" alt="RN-Callback-Wrapper-Issue" src="https://user-images.githubusercontent.com/16076685/196366978-25569bde-04bb-408c-ad19-69a18ca08b0f.png">

**Comment by rahulgpt1** [comment]
Sorry to forgot now we are using static linkage**(use_frameworks! :linkage => :static)**

**Comment by mikehardy** [comment]
With apologies this is not an open-ended tech support thread for me. I try to help when I can, but lacking reproducible examples and just looking at screenshots isn't the way. I link a reproducible example above, it works. I don't have time to participate in this discussion any more

**Comment by javi-additio** [comment]
@rahulgpt1 Hi, in our team we have the same problem. Any news about this? Did you solve this? Best

**Comment by adamsolomon1986** [comment]
+1

**Comment by dave-hunter-shopify** [comment]
We noticed that this seems to be an issue when we add the `-all_load` linker flag.  After a bit of research it looks like this might be a folly/boost issue?  Is boost up to date?

**Comment by SliverYuki** [comment]
> @rahulgpt1 Hi, in our team we have the same problem. Any news about this? Did you solve this? Best

May I ask if your team has finally resolved the issue? If possible, please let me know what to do. Thank you.

**Comment by yaminyassin** [comment]
I am still experiencing this issue on React native 0.73
