### ISSUE TITLE
Error installing CocoaAsyncSocket

### ISSUE THREAD

**Issue by tipsterz** [facebook/react-native#34996]
### Description

Environment set up failing running `pod install`

### Version

0.70.3

### Output of `npx react-native info`

System:
    OS: macOS 12.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.08 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 8.11.0 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 14.0/14A309 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.3 => 0.70.3
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

`npx react-native init AwesomeProject`

<img width="774" alt="Schermata 2022-10-15 alle 18 50 04" src="https://user-images.githubusercontent.com/102190429/195998920-93965bc8-ae36-478a-acbd-1879d6d46d02.png">

`cd ./AwesomeProject/ios && pod install`

<img width="1467" alt="Schermata 2022-10-15 alle 18 51 18" src="https://user-images.githubusercontent.com/102190429/195998934-c83e9dde-d57e-414e-bb69-236df7a3a2d4.png">

**Comment by cortinico** [comment]
This seems like a local networking issue as you're failing to resolve: https://github.com/robbiehanson

**Comment by tipsterz** [comment]
issue was related to my local `.gitconfig`, solved commenting:

```
[url "ssh://git@github.com:"]
	insteadOf = https://github.com/
```

**Comment by Moazzamhanif** [comment]
[url "ssh://git@github.com:"]
	insteadOf = https://github.com/.  where  this code  exist in my project no gitigconfig file added.
