### ISSUE TITLE
A/libc: /root/react-native/ReactCommon/jsi/JSCRuntime.cpp:397: virtual facebook::jsc::JSCRuntime::~JSCRuntime(): assertion "objectCounter_ == 0 && "JSCRuntime destroyed with a dangling API object""

### ISSUE THREAD

**Issue by exzos28** [facebook/react-native#34991]
### Description

A/libc: /root/react-native/ReactCommon/jsi/JSCRuntime.cpp:397: virtual facebook::jsc::JSCRuntime::~JSCRuntime(): assertion "objectCounter_ == 0 && "JSCRuntime destroyed with a dangling API object""

### Version

0.70.1

### Output of `npx react-native info`

System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1 Pro
    Memory: 112.72 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.17.6 - ~/.nvm/versions/node/v14.17.6/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.17.6/bin/npm
    Watchman: 2022.05.16.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK:
      API Levels: 28, 29, 30, 31, 32
      Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0
      System Images: android-30 | Google APIs ARM 64 v8a, android-30 | Google Play ARM 64 v8a, android-31 | Google Play ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: Dolphin 2021.3.1 Dolphin 2021.3.1
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /Users/exzos/.jenv/shims/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.1 => 0.70.1
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

After reload metro server and got error

### Snack, code example, screenshot, or link to a repository

<img width="1185" alt="image" src="https://user-images.githubusercontent.com/39951413/195979579-b6d07e77-6e2e-4773-bc69-03b3301c6407.png">

**Comment by Acetyld** [comment]
Same error here, any update?

**Comment by exzos28** [comment]
> Same error here, any update?

i couldn't solve it, i get one successful app launch every 10-15 times.
It looks like the only successful option is to update react-native.

**Comment by Acetyld** [comment]
Yhea i did that, updated to newest react-native, still nu success

**Comment by Acetyld** [comment]
We found a solution for now.
Upgraded whole project to newest react-native and enabling "hermes", we couldt do this before because we are using Realmsjs, but!! 1 week ago they finally released Hermes support!.

For now we finnaly got android and ios working with code push, lets hope for little bugs :S

**Comment by dhavalsulhuf** [comment]
getting same error here. any solution ?
![Screenshot 2023-04-17 at 11 35 37 AM](https://user-images.githubusercontent.com/109509977/232397673-89983043-b5dc-4f0e-8ee1-89bc35aef094.png)

**Comment by dhavalsulhuf** [comment]
getting same error here. any solution
![Screenshot 2023-04-17 at 11 35 37 AM](https://user-images.githubusercontent.com/109509977/232397928-7a562819-148f-413f-9659-b35d05860fec.png)

**Comment by mhsfh** [comment]
same error here

**Comment by SelfDestroyer** [comment]
same error... any updates?

**Comment by dangdo1** [comment]
same error here

**Comment by dangdo1** [comment]
@react-native-bot 
review it, please!

**Comment by donatoaguirre24** [comment]
FYI if you're using react-native-reanimated the crash is likely caused by this [issue](https://github.com/software-mansion/react-native-reanimated/issues/4783)

**Comment by donatoaguirre24** [comment]
Not stale

**Comment by tanishqkancharla** [comment]
Quick question here: the macro checks for the flag NDEBUG (which implies "not debug"), but we are running into the issue in production as well. Should we define the flag in production?

**Comment by redpredator8** [comment]
Not stale

**Comment by zeeshan-shabbir** [comment]
not stale still facing same

**Comment by yosukapro** [comment]
Comment these code in file ./node_modules/react-native/ReactCommon/jsc/JSCRuntime.cpp

`// #ifndef NDEBUG
//   assert(
//       objectCounter_ == 0 && "JSCRuntime destroyed with a dangling API object");
//   assert(
//       stringCounter_ == 0 && "JSCRuntime destroyed with a dangling API string");
// #endif`
