### ISSUE TITLE
[!] There are multiple dependencies with different sources for `ExpoModulesCore` in `Podfile`:

### ISSUE THREAD

**Issue by pascal-maker** [facebook/react-native#35007]
### Description

This is My Podfile  
```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

platform :ios, '12.4'

$FirebaseSDKVersion = '10.0.0'

target 'Instadating' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  config = use_native_modules!
  use_react_native!(
    :path => config[:"reactNativePath"]
  )
  pod 'ExpoModulesCore', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  $RNFirebaseAsStaticFramework = true

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
 use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end

  pod 'ReactNativeART', :path => '../node_modules/@react-native-community/art'

  use_unimodules!
  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'RNLocalize', :path => '../node_modules/react-native-localize'
 
end
```

This Is my podfile when i try to cd ios &&  pod install --repo-update i get this error  [!] There are multiple dependencies with different sources for `ExpoModulesCore` in `Podfile`:

- ExpoModulesCore
- ExpoModulesCore (from `../node_modules/expo/node_modules/expo-modules-core/ios`)

### Version

0.72.3

### Output of `npx react-native info`

warn Package react-native-ui-lib contains invalid configuration: "dependency.platforms.ios.project" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
info Fetching system and libraries information...
System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1
    Memory: 115.89 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.10.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - /opt/homebrew/bin/npm
    Watchman: 2022.10.10.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1) Open Terminal
2) cd Lovia-Master-Master-2
3) cd ios
4) pod install --repo-update

### Snack, code example, screenshot, or link to a repository

https://github.com/pascal-maker/Lovia-master-2-master-master

**Comment by cortinico** [comment]
Hi @pascal-maker 
Thanks for reporting this issue.

It seems like this issue is actually unrelated to React Native core but related to Expo. Please open this issue against this other repository:
https://github.com/expo/expo/issues

I'll be closing this but feel free to reopen if the other repo points back to us as a issue in the core of React Native.
