### ISSUE TITLE
When creating a new RN new project, no pod file is generated

### ISSUE THREAD

**Issue by pche2020** [facebook/react-native#35018]
### Description

Hello, I am creating the RN test project AwesomeProject, but there is no pod folder in the iOS directory, I will post the screenshot

"dependencies": {
    "react": "18.1.0",
    "react-native": "0.70.3"
  },

<img width="770" alt="image" src="https://user-images.githubusercontent.com/13309562/196583197-ba9296a6-1813-406e-8518-6dc0aa7acd9b.png">

The following figure is the creation process, and the error message, which can be reproduced according to this operation
<img width="1066" alt="image" src="https://user-images.githubusercontent.com/13309562/196583430-5a2abc69-e00c-42ae-9cbb-3f723b286977.png">

Next is info info
<img width="1054" alt="image" src="https://user-images.githubusercontent.com/13309562/196583598-a6adc0e6-0258-40a0-bc73-e2acd9a54f8c.png">

Next is doctor information
<img width="1059" alt="image" src="https://user-images.githubusercontent.com/13309562/196584296-ca494df7-6007-4cff-a548-95d0fbf36ecd.png">

Next is the env info
<img width="716" alt="image" src="https://user-images.githubusercontent.com/13309562/196584449-29e39bd5-ca24-43c0-bef1-43881b1b6705.png">

Finally, execute``` pod instal```l or ```pod install -- verbose ```under iOS
<img width="859" alt="image" src="https://user-images.githubusercontent.com/13309562/196585136-be824319-40fd-4f21-a541-d55fbdf74b39.png">

How to solve this problem，Then I would like to ask, when creating a new RN project, how to make the ios project of the word directory into the swift language instead of the oc language?

### Version

0.70.3

### Output of `npx react-native info`

╭─      ~/Desktop/TestRN/OC/AwesomeProject/ios                                                                1 ✘  2.7.5    10:01:15 
╰─ ```npx react-native info```
info Fetching system and libraries information...
System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Max
    Memory: 113.97 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 17.9.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - /opt/homebrew/bin/npm
    Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK:
      API Levels: 32, 33
      Build Tools: 32.0.0, 32.1.0, 33.0.0, 33.0.0
      System Images: android-32 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8309675
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 18.0.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

The specific operation steps have been shown in the screenshot above

Below is the Env 

TERM_SESSION_ID=w2t0p0:458E4C46-1D5E-4D30-B75D-DB876651C053
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.7e7Xc29z5H/Listeners
LC_TERMINAL_VERSION=3.4.15
COLORFGBG=15;0
ITERM_PROFILE=Hpc
XPC_FLAGS=0x0
LANG=zh_CN.UTF-8
PWD=/Users/hepengcheng/Desktop/TestRN/OC/AwesomeProject/ios
SHELL=/bin/zsh
__CFBundleIdentifier=com.googlecode.iterm2
TERM_PROGRAM_VERSION=3.4.15
TERM_PROGRAM=iTerm.app
PATH=/Users/hepengcheng/.rvm/gems/ruby-2.7.5/bin:/Users/hepengcheng/.rvm/gems/ruby-2.7.5@global/bin:/Users/hepengcheng/.rvm/rubies/ruby-2.7.5/bin:/Users/hepengcheng/.rvm/bin:/Users/hepengcheng/Documents/flutter/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/hepengcheng/Library/Android/sdk/tools:/Users/hepengcheng/Library/Android/sdk/platform-tools
LC_TERMINAL=iTerm2
COLORTERM=truecolor
COMMAND_MODE=unix2003
TERM=xterm-256color
HOME=/Users/hepengcheng
TMPDIR=/var/folders/j6/62b37k4x1z788t1shkyd_6tc0000gn/T/
USER=John_H
XPC_SERVICE_NAME=0
LOGNAME=John_H
ITERM_SESSION_ID=w2t0p0:458E4C46-1D5E-4D30-B75D-DB876651C053
__CF_USER_TEXT_ENCODING=0x0:25:52
SHLVL=1
OLDPWD=/Users/hepengcheng/Desktop/TestRN/OC
HOMEBREW_BOTTLE_DOMAIN=https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles/bottles
HOMEBREW_PREFIX=/opt/homebrew
HOMEBREW_CELLAR=/opt/homebrew/Cellar
HOMEBREW_REPOSITORY=/opt/homebrew
MANPATH=/opt/homebrew/share/man::
INFOPATH=/opt/homebrew/share/info:
P9K_TTY=old
_P9K_TTY=/dev/ttys005
PUB_HOSTED_URL=https://pub.flutter-io.cn
FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn
FLUTTER=/Users/hepengcheng/Documents/flutter
ANDROID_HOME=/Users/hepengcheng/Library/Android/sdk
ZSH=/Users/hepengcheng/.oh-my-zsh
PAGER=less
LESS=-R
LSCOLORS=Gxfxcxdxbxegedabagacad
P9K_SSH=0
AUTOJUMP_SOURCED=1
AUTOJUMP_ERROR_PATH=/Users/hepengcheng/Library/autojump/errors.log
rvm_prefix=/Users/hepengcheng
rvm_path=/Users/hepengcheng/.rvm
rvm_bin_path=/Users/hepengcheng/.rvm/bin
rvm_version=1.29.12 (latest)
GEM_HOME=/Users/hepengcheng/.rvm/gems/ruby-2.7.5
GEM_PATH=/Users/hepengcheng/.rvm/gems/ruby-2.7.5:/Users/hepengcheng/.rvm/gems/ruby-2.7.5@global
MY_RUBY_HOME=/Users/hepengcheng/.rvm/rubies/ruby-2.7.5
IRBRC=/Users/hepengcheng/.rvm/rubies/ruby-2.7.5/.irbrc
RUBY_VERSION=ruby-2.7.5
rvm_alias_expanded=
rvm_bin_flag=
rvm_docs_type=
rvm_gemstone_package_file=
rvm_gemstone_url=
rvm_niceness=
rvm_nightly_flag=
rvm_only_path_flag=
rvm_pretty_print_flag=
rvm_proxy=
rvm_quiet_flag=
rvm_ruby_bits=
rvm_ruby_file=
rvm_ruby_make=
rvm_ruby_make_install=
rvm_ruby_mode=
rvm_script_name=
rvm_sdk=
rvm_silent_flag=
rvm_use_flag=
rvm_delete_flag=0
rvm_file_name=
rvm_ruby_alias=
rvm_sticky_flag=
rvm_system_flag=
rvm_user_flag=
rvm_ruby_string=ruby-2.7.5

### Snack, code example, screenshot, or link to a repository

At present, the code level has not been involved. It is just a problem encountered when creating a new project. If there is a code problem in the future, I will give feedback in time.

**Comment by pche2020** [comment]
@cortinico  How am I going to deal with this problem?

**Comment by cortinico** [comment]
Have you followed the instructions on this page?
https://reactnative.dev/docs/environment-setup

It seems like you're failing to run `cocoapod` from Ruby.
