### ISSUE TITLE
创建新的RN新项目的时候，没有生成pod文件

### ISSUE THREAD

**Issue by pche2020** [facebook/react-native#35010]
### Description

![Uploading image.png…]()

### Version

0.70.3

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Max
    Memory: 113.97 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 17.9.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - /opt/homebrew/bin/npm
    Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK:
      API Levels: 32, 33
      Build Tools: 32.0.0, 32.1.0, 33.0.0, 33.0.0
      System Images: android-32 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8309675
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 18.0.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

"依赖": {"反应": "18.1.0","反应原生": "0.70.3"}，1.cocoapods 和 node ,watchman ,yarn,Xcode 都已安装完毕的条件下执行```npx react-native init Awesome``'之后✔下载模板✔复制模板✔处理模板i安装依赖项？CocoaPods（https://cocoapods.org/）未安装。iOS 项目需要 CocoaPods 才能正常运行。你想安装它吗？› - 使用箭头键。返回提交。？是的，有宝石（可能需要sudo）是的，用自制后选择其中一个出现以下提示✔安装CocoaPods✖安装CocoaPods依赖项（这可能需要几分钟）✖安装CocoaPods依赖项（这可能需要几分钟）错误错误：未能安装此模板要求的iOS项目CocoaPods依赖项。请手动重试：“cd。/AwesomeProject/ios && pod install"。CocoaPods文档：https://cocoapods.org/执行``cd。/AwesomeProject/ios && pod install```然后报错光盘。/AwesomeProject/ios && pod安装回溯（最近一次通话）：	4：来自/Users/hepengcheng/.rvm/gems/ruby-2.7.5/bin/ruby_executable_hooks:22:in `<main>'	3：来自/Users/hepengcheng/.rvm/gems/ruby-2.7.5/bin/ruby_executable_hooks:22:in `eval'	2：来自/Users/hepengcheng/.rvm/gems/ruby-2.7.5/bin/pod:23:in `<main>'	1：from/Users/hepengcheng/.rvm/rubies/ruby-2.7.5/lib/ruby/2.7.0/rubygems.rb:296:in `activate_bin_path'/Users/hepengcheng/.rvm/rubies/ruby-2.7.5/lib/ruby/2.7.0/rubygems.rb:277:in `find_spec_for_exe':找不到可执行pod的gem cocoapods (>= 0.a) (Gem::GemNotFoundException)

以下是Env信息
TERM_SESSION_ID=w2t0p0:458E4C46-1D5E-4D30-B75D-DB876651C053
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.7e7Xc29z5H/Listeners
LC_TERMINAL_VERSION=3.4.15
COLORFGBG=15;0
ITERM_PROFILE=Hpc
XPC_FLAGS=0x0
LANG=zh_CN.UTF-8
PWD=/Users/hepengcheng/Desktop/TestRN/OC/AwesomeProject/ios
SHELL=/bin/zsh
__CFBundleIdentifier=com.googlecode.iterm2
TERM_PROGRAM_VERSION=3.4.15
TERM_PROGRAM=iTerm.app
PATH=/Users/hepengcheng/.rvm/gems/ruby-2.7.5/bin:/Users/hepengcheng/.rvm/gems/ruby-2.7.5@global/bin:/Users/hepengcheng/.rvm/rubies/ruby-2.7.5/bin:/Users/hepengcheng/.rvm/bin:/Users/hepengcheng/Documents/flutter/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/hepengcheng/Library/Android/sdk/tools:/Users/hepengcheng/Library/Android/sdk/platform-tools
LC_TERMINAL=iTerm2
COLORTERM=truecolor
COMMAND_MODE=unix2003
TERM=xterm-256color
HOME=/Users/hepengcheng
TMPDIR=/var/folders/j6/62b37k4x1z788t1shkyd_6tc0000gn/T/
USER=John_H
XPC_SERVICE_NAME=0
LOGNAME=John_H
ITERM_SESSION_ID=w2t0p0:458E4C46-1D5E-4D30-B75D-DB876651C053
__CF_USER_TEXT_ENCODING=0x0:25:52
SHLVL=1
OLDPWD=/Users/hepengcheng/Desktop/TestRN/OC
HOMEBREW_BOTTLE_DOMAIN=https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles/bottles
HOMEBREW_PREFIX=/opt/homebrew
HOMEBREW_CELLAR=/opt/homebrew/Cellar
HOMEBREW_REPOSITORY=/opt/homebrew
MANPATH=/opt/homebrew/share/man::
INFOPATH=/opt/homebrew/share/info:
P9K_TTY=old
_P9K_TTY=/dev/ttys005
PUB_HOSTED_URL=https://pub.flutter-io.cn
FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn
FLUTTER=/Users/hepengcheng/Documents/flutter
ANDROID_HOME=/Users/hepengcheng/Library/Android/sdk
ZSH=/Users/hepengcheng/.oh-my-zsh
PAGER=less
LESS=-R
LSCOLORS=Gxfxcxdxbxegedabagacad
P9K_SSH=0
AUTOJUMP_SOURCED=1
AUTOJUMP_ERROR_PATH=/Users/hepengcheng/Library/autojump/errors.log
rvm_prefix=/Users/hepengcheng
rvm_path=/Users/hepengcheng/.rvm
rvm_bin_path=/Users/hepengcheng/.rvm/bin
rvm_version=1.29.12 (latest)
GEM_HOME=/Users/hepengcheng/.rvm/gems/ruby-2.7.5
GEM_PATH=/Users/hepengcheng/.rvm/gems/ruby-2.7.5:/Users/hepengcheng/.rvm/gems/ruby-2.7.5@global
MY_RUBY_HOME=/Users/hepengcheng/.rvm/rubies/ruby-2.7.5
IRBRC=/Users/hepengcheng/.rvm/rubies/ruby-2.7.5/.irbrc
RUBY_VERSION=ruby-2.7.5
rvm_alias_expanded=
rvm_bin_flag=
rvm_docs_type=
rvm_gemstone_package_file=
rvm_gemstone_url=
rvm_niceness=
rvm_nightly_flag=
rvm_only_path_flag=
rvm_pretty_print_flag=
rvm_proxy=
rvm_quiet_flag=
rvm_ruby_bits=
rvm_ruby_file=
rvm_ruby_make=
rvm_ruby_make_install=
rvm_ruby_mode=
rvm_script_name=
rvm_sdk=
rvm_silent_flag=
rvm_use_flag=
rvm_delete_flag=0
rvm_file_name=
rvm_ruby_alias=
rvm_sticky_flag=
rvm_system_flag=
rvm_user_flag=
rvm_ruby_string=ruby-2.7.5
_=/usr/bin/env

### Snack, code example, screenshot, or link to a repository

![Uploading image.png…]()

**Comment by cortinico** [comment]
Hi @pche2020 
In this issue tracker we accept only issues that are in English.
I'm closing this for now, please consider translating it to English and reopening it.
Thanks.
