### ISSUE TITLE
React native application created using expo not working if newArchitecture is not working

### ISSUE THREAD

**Issue by nkjs-git** [facebook/react-native#35023]
### Description

I have created a sample react native application using expo (followed https://reactnative.dev/docs/environment-setup) and run the app with newArchitecture disabled by doing expo eject and built it (using both 'expo run:android' and 'npx react-native run-android --active-arch-only' ). It worked fine.

But when I enabled the newArchitecture in 'android/gradle.properties' file generated by expo eject, the application build with the command 'npx react-native run-android --active-arch-only' (and also apk generated with 'cd android && ./gradlew app:assembleRelease -PreactNativeArchitectures=arm64-v8a,x86') is successful but the app is crashing with the below exception in mobile.

`com.facebook.react.common.JavascriptException: Error: Exception in HostObject::get(propName:UIManager): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Class.getSuperclass()' on a null object reference, stack:
l@52:427
@52:156
@157:695
h@2:1585
@156:62
h@2:1585
@153:64
h@2:1585
@139:569
h@2:1585
@192:153
h@2:1585
@191:61
h@2:1585
@311:113
h@2:1585
@348:693
h@2:1585
@339:757
h@2:1585
@412:35
h@2:1585
@9:70
h@2:1585
@8:314
h@2:1585
@6:45
h@2:1585
d@2:958
global code@472:3

at com.facebook.react.modules.core.ExceptionsManagerModule.reportException([ExceptionsManagerModule.java:72](http://exceptionsmanagermodule.java:72/))
at [com.facebook.react.bridge.queue.NativeRunnable.run](http://com.facebook.react.bridge.queue.nativerunnable.run/)(Native Method)
at android.os.Handler.handleCallback([Handler.java:873](http://handler.java:873/))
at android.os.Handler.dispatchMessage([Handler.java:99](http://handler.java:99/))
at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage([MessageQueueThreadHandler.java:27](http://messagequeuethreadhandler.java:27/))
at android.os.Looper.loop([Looper.java:201](http://looper.java:201/))
at com.facebook.react.bridge.queue.MessageQueueThreadImpl$[4.run](http://4.run/)([MessageQueueThreadImpl.java:228](http://messagequeuethreadimpl.java:228/))
at [java.lang.Thread.run](http://java.lang.thread.run/)([Thread.java:764](http://thread.java:764/))`

But the newArchitecture enabled is working in ios application. Can anyone please help me on this?  

### Version

0.69.6

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 12.3.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 26.92 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.17.1 - /usr/local/opt/node@16/bin/node
    Yarn: Not Found
    npm: 8.15.0 - /usr/local/opt/node@16/bin/npm
    Watchman: 2022.10.03.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8309675
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 18.0.1.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Create react-native application: **npx create-expo-app AwesomeProject**
expo eject to create android and ios native folders: **expo eject**
Build android by connecting physical device: (through any command)
**npx react-native run-android --active-arch-only**
**cd android && ./gradlew app:assembleRelease -PreactNativeArchitectures=arm64-v8a,x86**

### Snack, code example, screenshot, or link to a repository

followed react-native doc to create sample project

https://reactnative.dev/docs/environment-setup

**Comment by cortinico** [comment]
Hi @nkjs-git 
Thanks for reporting this issue.

As this is a expo-related setup, I would suggest you:
1. Re-open this issue against expo here https://github.com/expo/expo/issues
2. Re-try with the init flow using the React Native CLI, and re-open this issue if the crash persists.

I'll be closing this but feel free to reopen if the other repo points back to us as a issue in the core of React Native.

**Comment by nkjs-git** [comment]
Hi @cortinico,
Thank you for answering the issue. I have a doubt here, even though I have created the react-native project using expo. I have created android and ios folders by doing expo-eject. Does this not means converting the expo based project to react native CLI based (this is a basic question)? ( Actually I had tried this but still the expo module references are there in android folder generated.)

**Comment by 153** [comment]
cool

-- @153

**Comment by cortinico** [comment]
> Thank you for answering the issue. I have a doubt here, even though I have created the react-native project using expo. I have created android and ios folders by doing expo-eject. Does this not means converting the expo based project to react native CLI based (this is a basic question)? ( Actually I had tried this but still the expo module references are there in android folder generated.)

In theory yes, but for the sake of keeping our resources focues, we're now focusing our investigation only on projects created/built with the React Native CLI first. That's why if you can create a new project with the RN CLI and reproduce the crash, that's something we can totally look into.

**Comment by nkjs-git** [comment]
Got it, Thank you. As you said I have created the new react-native CLI project from scratch and tried to add dependencies in package.json as I have in my expo CLI project. But when I add the 'react-native-reanimated' using 'npm i react-native-reanimated' to new project of react-native CLI and do 'npx react-native run-android --active-arch-only' the build fails with the below mentioned error stacktrace.

**stacktrace**

`* Get more help at https://help.gradle.org

BUILD FAILED in 35s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081 -PreactNativeDebugArchitectures=x86 -PreactNativeArchitectures=x86
CMake Deprecation Warning at CMakeLists.txt:42 (cmake_policy):
  The OLD behavior for policy CMP0026 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


e: /Users/ee211312/Desktop/react-native/plmtrustlink_mobile/node_modules/react-native-gesture-handler/android/noreanimated/src/main/java/com/swmansion/gesturehandler/ReanimatedEventDispatcher.kt: (6, 7): Redeclaration: ReanimatedEventDispatcher
e: /Users/ee211312/Desktop/react-native/plmtrustlink_mobile/node_modules/react-native-gesture-handler/android/reanimated/src/main/java/com/swmansion/gesturehandler/ReanimatedEventDispatcher.kt: (5, 22): Unresolved reference: reanimated
e: /Users/ee211312/Desktop/react-native/plmtrustlink_mobile/node_modules/react-native-gesture-handler/android/reanimated/src/main/java/com/swmansion/gesturehandler/ReanimatedEventDispatcher.kt: (7, 7): Redeclaration: ReanimatedEventDispatcher
e: /Users/ee211312/Desktop/react-native/plmtrustlink_mobile/node_modules/react-native-gesture-handler/android/reanimated/src/main/java/com/swmansion/gesturehandler/ReanimatedEventDispatcher.kt: (8, 35): Unresolved reference: ReanimatedModule
e: /Users/ee211312/Desktop/react-native/plmtrustlink_mobile/node_modules/react-native-gesture-handler/android/reanimated/src/main/java/com/swmansion/gesturehandler/ReanimatedEventDispatcher.kt: (12, 56): Not enough information to infer type variable T
e: /Users/ee211312/Desktop/react-native/plmtrustlink_mobile/node_modules/react-native-gesture-handler/android/reanimated/src/main/java/com/swmansion/gesturehandler/ReanimatedEventDispatcher.kt: (12, 72): Unresolved reference: ReanimatedModule

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-gesture-handler:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 35s

    at makeError (/Users/ee211312/Desktop/react-native/plmtrustlink_mobile/node_modules/@react-native-community/cli-platform-android/node_modules/execa/index.js:174:9)
    at /Users/ee211312/Desktop/react-native/plmtrustlink_mobile/node_modules/@react-native-community/cli-platform-android/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (/Users/ee211312/Desktop/react-native/plmtrustlink_mobile/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:109:5)
    at async Command.handleAction (/Users/ee211312/Desktop/react-native/plmtrustlink_mobile/node_modules/@react-native-community/cli/build/index.js:142:9)
info Run CLI with --verbose flag for more details.`

**My package.json**

`{
  "name": "my_crossplatform_mobile",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "~1.17.3",
    "@react-navigation/drawer": "^6.4.3",
    "@react-navigation/native": "^6.0.11",
    "@react-navigation/native-stack": "^6.7.0",
    "buffer": "^6.0.3",
    "gs1-barcode-parser": "^1.0.1",
    "jetifier": "^2.0.0",
    "jexl": "^2.3.0",
    "jwt-decode": "^3.1.2",
    "moment": "^2.29.4",
    "react": "18.1.0",
    "react-dom": "^18.0.0",
    "react-native": "0.70.3",
    "react-native-config": "1.4.6",
    "react-native-dialog-input": "^1.0.8",
    "react-native-gesture-handler": "^2.7.1",
    "react-native-modal": "^13.0.1",
    "react-native-pager-view": "5.4.15",
    "react-native-reanimated": "^2.11.0",
    "react-native-restart": "^0.0.24",
    "react-native-safe-area-context": "^4.4.1",
    "react-native-screens": "^3.18.2",
    "react-native-select-dropdown": "^2.0.4",
    "react-native-splash-screen": "^3.3.0",
    "react-native-step-indicator": "^1.0.3",
    "react-native-svg": "^12.4.3",
    "react-native-tab-view": "^3.1.1",
    "react-native-uuid": "^2.0.1",
    "react-native-vector-icons": "^9.2.0",
    "react-native-web": "0.17.7",
    "react-native-webview": "^11.22.7",
    "react-timer-mixin": "^0.13.4",
    "uuidv4": "^6.2.13"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "^7.32.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "0.72.3",
    "react-test-renderer": "18.1.0"
  },
  "jest": {
    "preset": "react-native"
  }
}
`
**my index.js**

`/**
 * @format
 */
import 'react-native-gesture-handler';
import {AppRegistry} from 'react-native';
//import App from './App';
import App from './src'
import {name as appName} from './app.json';

AppRegistry.registerComponent(appName, () => App);`


src/index.js

`import 'react-native-gesture-handler';
import React from 'react';
import { NavigationContainer } from '@react-navigation/native';
import { createNativeStackNavigator } from '@react-navigation/native-stack';
import config from './config'
import screen2 from './containers/screen2'

const App = () => {

  const Stack = createNativeStackNavigator();
  console.log('Environment Type: ', config.ENVIRONMENT_TYPE)
  return (
      <NavigationContainer>
        <Stack.Navigator
          screenOptions={{
            headerShown: false,
            gestureEnabled: false
          }}> 
              {/* < Stack.Screen name="Helpdesk" component={Helpdesk} /> */}
              < Stack.Screen name="Root" component={screen2}/>
        </Stack.Navigator>
      </NavigationContainer>
    
  );
};

export default App;`

**src/screen2.js**

`import 'react-native-gesture-handler';
import * as React from 'react';
import { Button, View } from 'react-native';
import { createDrawerNavigator } from '@react-navigation/drawer';

function HomeScreen({ navigation }) {
  return (
    <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
      <Button
        onPress={() => navigation.navigate('Notifications')}
        title="Go to notifications"
      />
    </View>
  );
}

function NotificationsScreen({ navigation }) {
  return (
    <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
      <Button onPress={() => navigation.goBack()} title="Go back home" />
    </View>
  );
}

const Drawer = createDrawerNavigator();

export default function scrren2() {
  return (
      <Drawer.Navigator initialRouteName="Home">
        <Drawer.Screen name="Home" component={HomeScreen} />
        <Drawer.Screen name="Notifications" component={NotificationsScreen} />
      </Drawer.Navigator>
  );
}`

**babel.config.js**

`module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: ['react-native-reanimated/plugin'],
};
`

Could you please help me what I have done wrong?

**Comment by cortinico** [comment]
It seems like this issue is actually unrelated to React Native core but related to Reanimated. Can you opne your issue here?
https://github.com/software-mansion/react-native-reanimated/issues
