### ISSUE TITLE
Run web assembly on react-native

### ISSUE THREAD

**Issue by mattiaferrari02** [facebook/react-native#35026]
### Description

I have to use this lib https://github.com/bitcoinjs/tiny-secp256k1 that is written using webassembly but when i try to call it says `Assertion failed: no binaryen method succeeded.`
Is there a way to use a `.wasm` file in react-native?
I tried istantiating a webview to run the wasm on, but it changes drastically the approach to the lib because now everything is event based and it isn't what i want....

### Version

0.69.0

### Output of `npx react-native info`

`Assertion failed: no binaryen method succeeded.`

### Steps to reproduce

install this lib on a react-native project and try calling some methods

### Snack, code example, screenshot, or link to a repository

https://github.com/bitcoinjs/tiny-secp256k1

**Comment by cortinico** [comment]
> Is there a way to use a `.wasm` file in react-native?

Hi @mattiaferrari02 
I would suggest to rely on community built tools such as this one:
https://github.com/inokawa/react-native-wasm
Closing as not directly related to React native core.
