### ISSUE TITLE
App Crash on starting Fatal signal 11 (SIGSEGV), code 2, fault addr 0x7f7831fb80 in tid 5283 (mqt_native_modu)

### ISSUE THREAD

**Issue by roots-ai** [facebook/react-native#35029]
### Version

0.70.3

### Output of `npx react-native info`

System:
    OS: macOS 12.6.1
    CPU: (4) x64 Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
    Memory: 716.67 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.17.6 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.18.0 - ~/Projects/App/node_modules/.bin/npm
    Watchman: 2022.07.04.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.4 - /Users/IIUser/.rvm/gems/ruby-2.4.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK:
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2.3 AI-162.4069837
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: ^9.2.1 => 9.2.1 
    react: ^18.2.0 => 18.2.0 
    react-native: 0.70.3 => 0.70.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
(base) Users-MacBook-Pro:App I

### Steps to reproduce

Crashes after app starts on running `react-native run-android`

### Snack, code example, screenshot, or link to a repository

[Here is a minimum repo that crashes on startup](https://github.com/roots-ai/min)

I have hidden private passwords values in
- `android/app/google-services.json`
- `android/app/my-release-key.keystore`
- `android/gradle.properties`

**Comment by roots-ai** [comment]
@cortinico can you please help out? These is holding our production app release.

**Comment by Ruslan-BG** [comment]
This crash is Webview - Android 12

**Comment by cortinico** [comment]
> @cortinico can you please help out? This is holding our app release. I have been trying to resolve this since last 1 week

Could you provide a reproducer we can look into?

**Comment by roots-ai** [comment]
> > @cortinico can you please help out? This is holding our app release. I have been trying to resolve this since last 1 week
> 
> Could you provide a reproducer we can look into?

Made the changes in the question, please have a look

**Comment by roots-ai** [comment]
@cortinico

**Comment by HarshitMadhav** [comment]
Make sure Flipper is running

**Comment by roots-ai** [comment]
@HarshitMadhav As you can see in the repo that I shared, I have remove all the references of Flipper from the code. So was expecting to not start Flipper along.


Though, now trying to include all Flipper code and see if it works.

**Comment by cortinico** [comment]
@roots-ai thanky you for sending the repro.

Could you start removing your dependencies till you find the offending one:

https://github.com/roots-ai/min/blob/2202565d07f87050b63fadceb40cceb80b25bf9b/package.json#L30-L126

The `dependencies` block is quite big and is making the investigation quite hard.

**Comment by roots-ai** [comment]
Why aren't proper error logs possible, it's really tough to figure out what's happening?

**Comment by cortinico** [comment]
> @cortinico and is adding `Flipper` compulsory?

Nope it's not
