### ISSUE TITLE
Debugging errors in batched updates

### ISSUE THREAD

**Issue by aleclarson** [facebook/react-native#3503]
When `flattenStyle` throws [here](https://github.com/facebook/react-native/blob/master/Libraries/StyleSheet/flattenStyle.js#L30), I get a cryptic stack trace that doesn't let me figure out what's going wrong.

How am I expected to debug this?

Here's the stack trace:

```
Error: style may be false but not true

    file: /Users/aleclarsoniv/dev/modules/react-native/Libraries/StyleSheet/flattenStyle.js
    method: flattenStyle
    line: 30
    column: 0

    file: /Users/aleclarsoniv/dev/modules/react-native/Libraries/ReactNative/ReactNativeAttributePayload.js
    method: diffNestedProperty
    line: 77
    column: 0

    file: /Users/aleclarsoniv/dev/modules/react-native/Libraries/ReactNative/ReactNativeAttributePayload.js
    method: diffProperties
    line: 210
    column: 0

    file: /Users/aleclarsoniv/dev/modules/react-native/Libraries/ReactNative/ReactNativeAttributePayload.js
    method: addProperties
    line: 270
    column: 0

    file: /Users/aleclarsoniv/dev/modules/react-native/Libraries/ReactNative/ReactNativeAttributePayload.js
    method: Object.ReactNativeAttributePayload.create
    line: 291
    column: 0

    file: /Users/aleclarsoniv/dev/modules/react-native/Libraries/ReactNative/ReactNativeBaseComponent.js
    method: ReactNativeBaseComponent.Mixin.mountComponent
    line: 226
    column: 0

    file: /Users/aleclarsoniv/dev/modules/react-native/node_modules/react-tools/src/renderers/shared/reconciler/ReactReconciler.js
    method: Object.ReactReconciler.mountComponent
    line: 38
    column: 0

    file: /Users/aleclarsoniv/dev/modules/react-native/node_modules/react-tools/src/renderers/shared/reconciler/ReactCompositeComponent.js
    method: ReactCompositeComponentMixin.mountComponent
    line: 241
    column: 0

    file: /Users/aleclarsoniv/dev/modules/react-native/node_modules/react-tools/src/test/ReactPerf.js
    method: wrapper [as mountComponent]
    line: 71
    column: 0
```

Note: The line numbers are probably fudged due to my debugging calls to `console.log`.

**Comment by greglose** [comment]
I'm sure you've figured it out but I had the same issue tonight. In my case it was because I had a 'style' property on a tag but never included a style ie <View style=>

**Comment by christopherdro** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

If you'd like you can create an issue on [Product Pains](https://productpains.com/product/react-native
).
ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. 

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bug fixes as the core team is focused on performance. Thanks!
