### ISSUE TITLE
React native app not archiving in Xcode

### ISSUE THREAD

**Issue by firasabf** [facebook/react-native#35048]
Description

error build: File /Users/user/Library/Developer/Xcode/DerivedData/appName/Build/Intermediates.noindex/ArchiveIntermediates/AppName/BuildProductsPath/Release-iphoneos/Beano.app/main.jsbundle does not exist. This must be a bug with React Native, please report it here: https://github.com/facebook/react-native/issues

app not building in Xcode when Archiving project

Version

0.70.2

Output of npx react-native info

System:
OS: macOS 12.6
CPU: (8) arm64 Apple M1
Memory: 154.83 MB / 16.00 GB
Shell: 5.8.1 - /bin/zsh
Binaries:
Node: 18.10.0 - /opt/homebrew/bin/node
Yarn: 1.10.1 - /usr/local/bin/yarn
npm: 8.19.2 - /opt/homebrew/bin/npm
Watchman: 2022.10.03.00 - /opt/homebrew/bin/watchman
Managers:
CocoaPods: 1.11.3 - /Users/user/.rvm/gems/ruby-3.0.0/bin/pod
SDKs:
iOS SDK:
Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
Android SDK:
API Levels: 23, 25, 26, 27, 28, 29
Build Tools: 23.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.3, 29.0.2, 29.0.3
System Images: android-22 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | China version of Wear OS Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
Android NDK: Not Found
IDEs:
Android Studio: 4.0 AI-193.6911.18.40.6626763
Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
Languages:
Java: 1.8.0_131 - /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/bin/javac
npmPackages:
@react-native-community/cli: Not Found
react: 18.1.0 => 18.1.0
react-native: 0.70.2 => 0.70.2
react-native-macos: Not Found
npmGlobalPackages:
react-native: Not Found

Steps to reproduce

Create react native app, open xcode and try to archive app

Snack, code example, screenshot, or link to a repository

[Xcode Build Log.pdf](https://github.com/facebook/react-native/files/9841228/Xcode.Build.Log.pdf)

github repo: https://github.com/firasabf/firasabf-react-native-V0.70

_Originally posted by @firasabf in https://github.com/facebook/react-native/issues/35046#issuecomment-1287269097_

**Comment by cortinico** [comment]
Duplicates https://github.com/facebook/react-native/issues/35046

**Comment by Leonardo2604** [comment]
+1 I have the same issue
