### ISSUE TITLE
[iOS] Cannot start iOS in new project with react native cli

### ISSUE THREAD

**Issue by nix6839** [facebook/react-native#35041]
### Description

After I read the official documentation and installed all the prerequisites, I ran iOS, but it doesn't work with the following error:
```output
The following build commands failed:
        CompileC /Users/nix6839/Library/Developer/Xcode/DerivedData/LearnReactNative-dzwmqogxljyyslbxcmfxtuampfqc/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/Flipper-RSocket.build/Objects-normal/arm64/TcpDuplexConnection.o /Users/nix6839/programming/study/study/react-native/LearnReactNative/ios/Pods/Flipper-RSocket/rsocket/transports/tcp/TcpDuplexConnection.cpp normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'Flipper-RSocket' from project 'Pods')
(1 failure)
```

### Version

0.70.3

### Output of `npx react-native info`

System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M2
    Memory: 140.47 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.11.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - ~/Library/Application Support/nvm/versions/node/v16.16.0/bin/yarn
    npm: 8.19.2 - /opt/homebrew/bin/npm
    Watchman: 2022.10.17.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/nix6839/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 18.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.3 => 0.70.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

```cli
npx react-native init LearnReactNative
cd LearnReactNative
npx react-native run-ios
```

and output:
```output
...SKIP
The following build commands failed:
        CompileC /Users/nix6839/Library/Developer/Xcode/DerivedData/LearnReactNative-dzwmqogxljyyslbxcmfxtuampfqc/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/Flipper-RSocket.build/Objects-normal/arm64/TcpDuplexConnection.o /Users/nix6839/programming/study/study/react-native/LearnReactNative/ios/Pods/Flipper-RSocket/rsocket/transports/tcp/TcpDuplexConnection.cpp normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'Flipper-RSocket' from project 'Pods')
(1 failure)
```

### Snack, code example, screenshot, or link to a repository

no response

**Comment by bailinx** [comment]
+1

**Comment by jorgerojas26** [comment]
Same issue
