### ISSUE TITLE
React native app not archiving in Xcode

### ISSUE THREAD

**Issue by firasabf** [facebook/react-native#35046]
### Description

error build: File /Users/user/Library/Developer/Xcode/DerivedData/appName/Build/Intermediates.noindex/ArchiveIntermediates/AppName/BuildProductsPath/Release-iphoneos/Beano.app/main.jsbundle does not exist. This must be a bug with React Native, please report it here: https://github.com/facebook/react-native/issues

app not building in Xcode when Archiving project

### Version

0.70.2

### Output of `npx react-native info`

System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1
    Memory: 154.83 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.10.0 - /opt/homebrew/bin/node
    Yarn: 1.10.1 - /usr/local/bin/yarn
    npm: 8.19.2 - /opt/homebrew/bin/npm
    Watchman: 2022.10.03.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/user/.rvm/gems/ruby-3.0.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 23.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.3, 29.0.2, 29.0.3
      System Images: android-22 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | China version of Wear OS Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_131 - /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.2 => 0.70.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Create react native app, open xcode and try to archive app

### Snack, code example, screenshot, or link to a repository

<img width="1" alt="Screen Shot 2022-10-21 at 5 23 01 PM" src="https://user-images.githubusercontent.com/57911446/197218797-ce52b4c2-3065-4aad-b102-45018aa20557.png">

**Comment by cortinico** [comment]
I'm sorry but there is not enough info for us to actionate this. We would need the full build log and a reproducer.

I'm closing this now, please reopen once you can provide the requested information

**Comment by firasabf** [comment]
Hello Nicola,

So i need to add the packages used? please if you can provide more details
about the required information
you need the build log from xcode?

**Comment by firasabf** [comment]
[Xcode Build Log.pdf](https://github.com/facebook/react-native/files/9841228/Xcode.Build.Log.pdf)

github repo: https://github.com/firasabf/firasabf-react-native-V0.70

**Comment by Leonardo2604** [comment]
+1 I have the same issue

**Comment by affansk** [comment]
@firasabf did u figure out the issue

**Comment by Leonardo2604** [comment]
Yes, in my case the app was being built with an old node version (13). I
had to define in the .xcode.env file the version compatible with
react-native 0.70.4.

https://reactnative.dev/docs/environment-setup#optional-configuring-your-environment

Em sáb., 12 de nov. de 2022 às 08:52, Affan Sphereit <
***@***.***> escreveu:

**Comment by firasabf** [comment]
Downgraded to V0.69.0
