### ISSUE TITLE
WebView.ios.js startInLoadingState state is undefined when render and componentWillMount

### ISSUE THREAD

**Issue by xiekw2010** [facebook/react-native#3504]
<img width="656" alt="2015-10-19 12 00 28" src="https://cloud.githubusercontent.com/assets/1814071/10569509/80764378-7659-11e5-8957-39a7bff04221.png">

When I use a webview ,the loadingView can not be rendered due to this state is undefined

**Comment by browniefed** [comment]
It appears you are attempting to access a `state` variable as `props`.

**Comment by browniefed** [comment]
@facebook-github-bot answered
