### ISSUE TITLE
Invalid podfile after installing dependencies with --production flag

### ISSUE THREAD

**Issue by mhyassin** [facebook/react-native#35059]
### Description

`pod install` command fails after installing dependencies of a project using the `--production` flag. The issue can be reproduced using yarn or npm on a new project using (npx react-native init reactNative69 --version 0.69.0).

This was working fine before 0.69.0

### Version

0.69

### Output of `npx react-native info`

error Failed to load configuration of your project.
info Run CLI with --verbose flag for more details.

### Steps to reproduce

- `npx react-native init reactNative69 --version 0.69.0` (you can use 0.69 or later)
- `yarn --prod`
- `cd ios`
- `pod install`

### Snack, code example, screenshot, or link to a repository

![Screenshot 2022-10-24 at 10 49 23 AM](https://user-images.githubusercontent.com/2027112/197487335-d1c851db-4d7b-4f7e-bdd1-95e9ac46f5b5.png)

**Comment by DennisMatthiasScherf** [comment]
Hello,

I can confirm that we're also facing the same issue. 

RN Version: 70.1

As a workaround I'll include the devDependencies but this is - in my opinion - only a temporary solution.

First I thought that a dependency had slipped into the devDepencendy. But after some trial and error I realized that even excluding the typescript type packages was enough to get this error.
