### ISSUE TITLE
cannot initialize new project 

### ISSUE THREAD

**Issue by Bayramito** [facebook/react-native#35055]
### Description

simply `npx react-native init` command doens't work.

<img width="1221" alt="Ekran Resmi 2022-10-23 13 45 56" src="https://user-images.githubusercontent.com/44513402/197387760-45cb09c6-56fe-4411-9300-38817a1540ba.png">

I am using a Macbook pro 16 inch 2019 intel, with Monterey 12.6 macOS version.

I installed ruby 3.1.2 which is latest via `asdf` and setted it as global ruby version.

but still same issue.

UPDATE:
just tried now, i can initialize in Webstorm's terminal but still doens't work on normal terminal or Iterm2

### Version

0.70.3

### Output of `npx react-native info`

-

### Steps to reproduce

none

### Snack, code example, screenshot, or link to a repository

none

**Comment by cortinico** [comment]
> I installed ruby 3.1.2 which is latest via asdf and setted it as global ruby version.

As the terminal says, you need to be on Ruby 2.7.5.
You should look into setting up Rbenv to control the ruby version

**Comment by Bayramito** [comment]
> > I installed ruby 3.1.2 which is latest via asdf and setted it as global ruby version.
> 
> As the terminal says, you need to be on Ruby 2.7.5. You should look into setting up Rbenv to control the ruby version

As you can see on the console i am using 3.1.2 as local ruby

**Comment by elliotsoomro** [comment]
Had the same issue. Installing ruby 2.7.5, while still using a more recent global ruby version, resolved the error.

**Comment by abelbeak** [comment]
It turns out that the same issue exists.
https://github.com/facebook/react-native/issues/35053
