### ISSUE TITLE
While starting the npm start am getting following error ? 

### ISSUE THREAD

**Issue by prashanthnani** [facebook/react-native#3506]
request:/index.ios.bundle?platform=ios&dev=true (10885ms)
::1 - - [19/Oct/2015:04:08:22 +0000] "GET /flow/ HTTP/1.1" 404 18 "-" "cloudseed/1 CFNetwork/711.4.6 Darwin/14.3.0"

because of this error, if I update  the index.ios.js  ,those changes are not reflecting on the output.

**Comment by drizko** [comment]
I have this issue as well, currently troubleshooting.

So far I've tried:
Reinstalling Watchman
Reinstalling Flow
Rebuilding my app

Still no luck

@paramaggarwal did you figure out the issue?

**Comment by joewood** [comment]
Seeing this issue too. Did anybody work it out?

**Comment by felipeporto** [comment]
+1

**Comment by christopherdro** [comment]
Try running `brew update && brew upgrade`.

**Comment by christopherdro** [comment]
@facebook-github-bot stack-overflow

**Comment by rahul1346** [comment]
Was there ever an answer to this? I am getting this as well...
