### ISSUE TITLE
Ii get error in ios

### ISSUE THREAD

**Issue by ombogdan** [facebook/react-native#35072]
### New Version

0.64

### Old Version

0.63.3

### Build Target(s)

i don`t know

### Output of `react-native info`

System:
    OS: macOS 12.6
    CPU: (8) x64 Apple M1
    Memory: 27.44 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.16.1 - ~/Projects/WebstormProjects/ReactNativeProjects/mobilenew/node_modules/.bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 7.24.0 - ~/Projects/WebstormProjects/ReactNativeProjects/mobilenew/node_modules/.bin/npm
    Watchman: 2022.05.16.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 16.0.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.0 => 0.64.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Issue and Reproduction Steps

<img width="774" alt="image" src="https://user-images.githubusercontent.com/36894763/197693687-7ed34d6e-cd2f-4ec2-9a12-ab5397a859e7.png">
after upgrading RN version i getting error in ios. I disable hermes and build succesfull in ios. But when simulator connecting to js i getting many errors  com.facebook.react.JavaScript (12)
#0	0x0000000102ce57f5 in facebook::jsc::JSCRuntime::objectRef(facebook::jsi::Object const&) at /Users/ombogdan/Projects/WebstormProjects/ReactNativeProjects/mobilenew/node_modules/react-native/ReactCommon/jsi/JSCRuntime.cpp:1431

<img width="1240" alt="image" src="https://user-images.githubusercontent.com/36894763/197693843-f628f30f-cd23-4efe-ad31-061eef94a2c2.png">

**Comment by cortinico** [comment]
> 0.64

Closing as this version is too old and unsupported.
The versions we support are:
https://github.com/reactwg/react-native-releases/
