### ISSUE TITLE
ellipsizeMode="middle" numberOfLines={2} not work

### ISSUE THREAD

**Issue by ZAJ0711** [facebook/react-native#35073]
### Description

the react-native version is 0.59.10
the Text component parameter，'ellipsizeMode' and 'numberOfLines' can not work correctly
when the 'numberOfLines' is more than 1，'ellipsizeMode' dose not work when i choose 'head'、'middle'

thanks

### Version

0.59.10

### Output of `npx react-native info`

React Native Environment Info:
    System:
      OS: macOS 12.4
      CPU: (8) x64 Apple M2
      Memory: 18.52 MB / 16.00 GB
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.18.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 6.14.15 - /usr/local/bin/npm
      Watchman: 2022.07.04.00 - /opt/homebrew/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.10 => 0.59.10 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native: 0.69.1

### Steps to reproduce

1、input the params

### Snack, code example, screenshot, or link to a repository

<Text
                ellipsizeMode="middle"
                numberOfLines={2}
              >
testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttest
</Text>

**Comment by labaird** [comment]
This is also happening to me. Testing with Nexus S and Pixel 6 on emulator using Expo Go. NumberOfLines=2 and ellipsizeMode="middle" causes the text to simply be cut off. Example string has realistic spacing, meaning that even with normal spacing between words this is still a problem.

This occurs on a card component with a defined width of 300. Flex: 1 is applied to a View wrapping the Text component like this:

```
<Card style={{width: 300}}
titleContent={
  <View style={{flex: 1}}>
    <Text numberOfLines=2 ellipsizeMode="middle" style={{fontSize: 15, fontFamily: "helvetica"}}>
       "Name that is very long and for testing purposes and has ellipses I wonder how long I can go before 
        truncation"  
    </Text>
  </View>
}
BodyContent={<View></View>}
 />
```

![image](https://user-images.githubusercontent.com/81602150/227275912-faf96197-876f-4b3a-90ba-c52a54ea4615.png)

**Comment by fabriziobertoglio1987** [comment]
Do you still experience this issue? 

I have four years of experience maintaining facebook/react-native and I specialize in the Text and TextInput components. I currently have 58 [facebook/react-native PRs](https://github.com/facebook/react-native/pulls?q=is%3Apr+author%3Afabriziobertoglio1987+). 

If you still experience this issue, I will prepare a patched release with the fix.

Thanks a lot

**Comment by labaird** [comment]
Hey Fabrizio, thank you so much for checking in. I just got back from
vacation, but I’ll check tomorrow by end of day Friday
