### ISSUE TITLE
Upgrade Failed

### ISSUE THREAD

**Issue by radenlarko** [facebook/react-native#35087]
### New Version

0.70.4

### Old Version

0.70.3

### Build Target(s)

Android Virtual Device

### Output of `react-native info`

System:
    OS: Windows 10 10.0.19043
    CPU: (4) x64 Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
    Memory: 938.16 MB / 7.92 GB
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.5.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 30, 31, 33
      Build Tools: 30.0.2, 30.0.3, 31.0.0
      System Images: android-30 | Google Play Intel x86 Atom, android-31 | Intel x86 Atom_64, android-31 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: AI-213.7172.25.2113.9014738
    Visual Studio: Not Found
  Languages:
    Java: 1.8.0_262
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.3 => 0.70.3
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Issue and Reproduction Steps

Upgrade failed from RN 0.70.3 to 0.70.4

info No version passed. Fetching latest...
info Fetching diff between v0.70.3 and v0.70.4...
info Applying diff...
warn Excluding files that exist in the template, but not in your project:
  - ios/AdyawinsaApp.xcworkspace/contents.xcworkspacedata
error Automatically applying diff failed. We did our best to automatically upgrade as many files as possible
error Patch failed to apply for unknown reason. Please fall back to manual way of upgrading
info You may find these resources helpful:
• Release notes: https://github.com/facebook/react-native/releases/tag/v0.70.4
• Manual Upgrade Helper: https://react-native-community.github.io/upgrade-helper/?from=0.70.3&to=0.70.4
• Git diff: https://raw.githubusercontent.com/react-native-community/rn-diff-purge/diffs/diffs/0.70.3..0.70.4.diff
error Upgrade failed. Please see the messages above for details.
info Run CLI with --verbose flag for more details.

Please Help

**Comment by ohheyitskartik** [comment]
seems like you would have to manually upgrade using - https://react-native-community.github.io/upgrade-helper/?from=0.70.3&to=0.70.4 as suggested in the output, its a few line change

**Comment by radenlarko** [comment]
yes but i don't have _ios/RnDiffApp.xcodeproj/project.pbxproj_ file in my project

**Comment by selven** [comment]
It would be ios/YOURPROJECTNAME.xcodeproj/project.pbxproj

**Comment by radenlarko** [comment]
oh i see, thank you @selven
