### ISSUE TITLE
Supply access to UITextView.secureTextEntry attribute on <TextInput />

### ISSUE THREAD

**Issue by rmcvey** [facebook/react-native#351]
Currently there is no way to make a native password field (outside of manual text masking), due to the `UITextView.secureTextEntry` attribute not being implemented.

**Comment by vishnevskiy** [comment]
There is already a PR #265 that does this :)

**Comment by rmcvey** [comment]
Great, thank you!

**Comment by mkonicek** [comment]
@rmcvey #265 has been merged, you can close this task.
