### ISSUE TITLE
XCode build and run fails because of root_files missings

### ISSUE THREAD

**Issue by WikiOops** [facebook/react-native#3510]
I, a react-native noob. got errors of watchman when build and run xcode:
Experts, how to avoid it? Should I disable root_files ?
Thanks in advance.

![screen shot 2015-10-19 at 2 34 28 am](https://cloud.githubusercontent.com/assets/2350613/10574292/f416efa8-7609-11e5-9689-3b609121ef6e.png)

React packager ready.

 ERROR  resolve_projpath: none of the files listed in global config root_files are present in path `/Users/zhou/react/PropertyFinder` or any of its parent directories
{"watchmanResponse":{"version":"3.8.0","error":"resolve_projpath: none of the files listed in global config root_files are present in path `/Users/zhou/react/PropertyFinder` or any of its parent directories"}}
Error: resolve_projpath: none of the files listed in global config root_files are present in path `/Users/zhou/react/PropertyFinder` or any of its parent directories
    at BunserBuf.<anonymous> (/Users/zhou/react/PropertyFinder/node_modules/react-native/node_modules/sane/node_modules/fb-watchman/index.js:93:23)
    at emitOne (events.js:77:13)
    at BunserBuf.emit (events.js:169:7)
    at BunserBuf.process (/Users/zhou/react/PropertyFinder/node_modules/react-native/node_modules/bser/index.js:289:10)
    at /Users/zhou/react/PropertyFinder/node_modules/react-native/node_modules/bser/index.js:244:12
    at doNTCallback0 (node.js:417:9)
    at process._tickCallback (node.js:346:13)

**Comment by javache** [comment]
Can you try adding add a `.watchmanconfig` to the root of your repository with `{}` as its contents? See https://github.com/facebook/react-native/issues/2042 for details.

**Comment by WikiOops** [comment]
Thanks. It works, and has got fixed.

**Comment by bvaughn** [comment]
> Can you try adding add a `.watchmanconfig` to the root of your repository with `{}` as its contents?

Thanks! 2 years later, but this comment just helped me too. 😄
