### ISSUE TITLE
Why React-native@0.70.4 says has incorrect peer dependency "react@18.1.0"

### ISSUE THREAD

**Issue by CarlosSLoureiro** [facebook/react-native#35112]
### Description

And also when I run `yarn check` it return `error "react-native#react@18.1.0" doesn't satisfy found match of "react@18.2.0"`

### Version

0.70.4

### Output of `npx react-native info`

System:
    OS: macOS 13.0
    CPU: (8) arm64 Apple M1
    Memory: 96.33 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.12.1 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /Users/carlosloureiro/.rvm/gems/ruby-3.0.3/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 18.0.1.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^18.2.0 => 18.2.0 
    react-native: ^0.70.4 => 0.70.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Create a react native project with latest versions of react native and react

### Snack, code example, screenshot, or link to a repository

![image](https://user-images.githubusercontent.com/19580424/198499882-2f9b04b7-df1f-4d5b-838c-8f9032afc80a.png)

**Comment by cortinico** [comment]
That's happening as you bumped the react version in your package.json

React Native 0.70.x ships with React 18.1.0:
https://github.com/facebook/react-native/blob/54e666205b36e37c30d3b01684bbd1a84a666d4e/template/package.json#L13

That's the version you should use.
