### ISSUE TITLE
ScrollView Sticky View Element

### ISSUE THREAD

**Issue by Annotator** [facebook/react-native#3511]
Hi

I'm trying to get an element in a scrollview to always stay to the left of the screen.  Kinda like the number rows in Excel. They stay to the left when scrolling horizontally but scroll also down when scrolled vertically. So far I tried animating the element by hooking up the onscroll element to it but it feels very rough. Then I tried nested Scrollviews but I cant scroll diagonally. Just one or the other.

Are there any other techniques in react native to get the desired result?

![microsoft_office_excel_2007](https://cloud.githubusercontent.com/assets/1277763/10574536/de58df12-7656-11e5-93cb-097507c65905.png)

**Comment by brentvatne** [comment]
You can wrap the ScrollView in a View that has the container with your sticky rows absolute positioned on the left side, then do a transform: translate on them in response to `onScroll` on the ScrollView.

This question might be best suited for StackOverflow as we're more concerned with addressing bugs here :)

**Comment by Naoto-Ida** [comment]
@brentvatne Could you possibly elaborate on this a little bit more?
