### ISSUE TITLE
[Windows] Can't find "rn-cli.config.js" file in any parent folder (windows)

### ISSUE THREAD

**Issue by cenchy** [facebook/react-native#3512]
![image](https://cloud.githubusercontent.com/assets/11435955/10576304/d8817e58-7694-11e5-9dc0-af28f33fa038.png)
![image](https://cloud.githubusercontent.com/assets/11435955/10576320/f3a17dbe-7694-11e5-8833-21dbad741860.png)

in windows, 
node_modules\react-native\private-cli\src\util\Config.js line 57;

this will show how to fix it in my way:
![image](https://cloud.githubusercontent.com/assets/11435955/10576374/6183bc7a-7695-11e5-8d9b-f6ad38ffd9f2.png)

**Comment by foghina** [comment]
cc @mkonicek as this is Windows-related.

**Comment by martinbigio** [comment]
The fix looks great! Would you mind sending a pull request? :)

**Comment by martinbigio** [comment]
@cenchy: ^^^

**Comment by cenchy** [comment]
I have not test it in Mac, I only have windows pc , so .....you know.
