### ISSUE TITLE
returnKeyType is not updating after state has changed

### ISSUE THREAD

**Issue by rodrigoeidelvein** [facebook/react-native#35125]
### Description

I want to use the `returnKeyType` prop of the `TextInput` with a state, however, the keyboard is setting the return key type to the previous value.

I found an issue reporting the same thing but it was closed: #23362 

### Version

0.69.2

### Output of `npx react-native info`

System:
    OS: macOS 12.6
    CPU: (8) x64 Apple M1 Pro
    Memory: 36.23 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.20.1 - ~/.nvm/versions/node/v14.20.1/bin/node
    Yarn: Not Found
    npm: 6.14.17 - ~/.nvm/versions/node/v14.20.1/bin/npm
    Watchman: 2022.08.22.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/rodrigoeidelvein/.rvm/gems/ruby-2.7.6/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0
    react-native: 0.69.2 => 0.69.2
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. Open the snack
2. Select the first input
3. Click on next until the last input (you can see that the text shows "done", but the return key type is "next" on the keyboard
4. Focus other input (It'll show the "done" return key type, but the actual state is "next")

### Snack, code example, screenshot, or link to a repository

https://snack.expo.dev/NrNOoauGz

**Comment by giograf** [comment]
We are currently facing the same issue on v.0.69.7.
Our use case is TextInput used for search. We want to have a "done" returnKeyType when no text has been inputted in the field, and "search" returnKeyType when text.length > 0.
