### ISSUE TITLE
Your Ruby version is 3.1.2, but your Gemfile specified 2.7.5

### ISSUE THREAD

**Issue by SeongwoonHong** [facebook/react-native#35127]
### Description

I'm able to install react natver@0.66.4 but
when i run `npx react-native init AwesomeMyProject` to get the latest version of RN, I'm getting this
```
                                                          
               ######                ######               
             ###     ####        ####     ###             
            ##          ###    ###          ##            
            ##             ####             ##            
            ##             ####             ##            
            ##           ##    ##           ##            
            ##         ###      ###         ##            
             ##  ########################  ##             
          ######    ###            ###    ######          
      ###     ##    ##              ##    ##     ###      
   ###         ## ###      ####      ### ##         ###   
  ##           ####      ########      ####           ##  
 ##             ###     ##########     ###             ## 
  ##           ####      ########      ####           ##  
   ###         ## ###      ####      ### ##         ###   
      ###     ##    ##              ##    ##     ###      
          ######    ###            ###    ######          
             ##  ########################  ##             
            ##         ###      ###         ##            
            ##           ##    ##           ##            
            ##             ####             ##            
            ##             ####             ##            
            ##          ###    ###          ##            
             ###     ####        ####     ###             
               ######                ######               
                                                          

                  Welcome to React Native!                
                 Learn once, write anywhere               

✔ Downloading template
✔ Copying template
✔ Processing template
✖ Installing Bundler
error Your Ruby version is 3.1.2, but your Gemfile specified 2.7.5

```

### Version

latest version

### Output of `npx react-native info`

npx react-native info
error: unknown command 'info'
(Did you mean init?)

### Steps to reproduce

run `npx react-native init AwesomeMyProject`

### Snack, code example, screenshot, or link to a repository

![Screen Shot 2022-10-28 at 4 46 46 PM](https://user-images.githubusercontent.com/19713918/198730004-ef466cdd-e5bf-47f5-8b1c-984030cb2641.png)

**Comment by eagle-head** [comment]
Similar problem here, but my version is 2.6.10 M1 processor MacBook Pro

**Comment by sniib** [comment]
Install version 2.7.5 using one of the ruby version managers

https://reactnative.dev/docs/environment-setup#ruby

**Comment by erikbergAtTelekom** [comment]
This solution worked for me properly:

https://stackoverflow.com/questions/71371079/fix-your-ruby-version-is-2-6-8-but-your-gemfile-specified-2-5-5

**Comment by awefeng** [comment]
> Install version 2.7.5 using one of the ruby version managers
> 
> https://reactnative.dev/docs/environment-setup#ruby

@sniib but there is no 2.7.5 version ,  rvm list known.  what mean

**Comment by alabobriggs** [comment]
> https://stackoverflow.com/questions/71371079/fix-your-ruby-version-is-2-6-8-but-your-gemfile-specified-2-5-5

Worked for me

**Comment by twlkyao** [comment]
Problem solved by the following command.

`rvm` install "ruby-2.7.5"
`rvm` use 2.7.5

**Comment by Djhitman** [comment]
Founded solution for me: 

1. Clear **~/Library/Caches** folder
2. Make sure you are using the latest required by react-native ruby version 
>     ruby -v
3. Reboot terminal and try again

**Comment by ukWaqas** [comment]
> Problem solved by the following command.
> 
> `rvm` install "ruby-2.7.5" `rvm` use 2.7.5

The docs specifies that the react native version used is [here](https://github.com/facebook/react-native/blob/main/template/_ruby-version). 
At this time, it is 2.7.6. Isn't there a discrepancy in the [docs](https://reactnative.dev/docs/next/environment-setup) that links to the version if we have to use 2.7.5?

**Comment by ganeshsacharya** [comment]
What i tried is below:
1. when the this failure happens. Simply go to the Gemfile
2. change the existing version from whatever it is to the version the errors says it wants (for e.g. 3.1.2)
3. then do npm install and then run the respective command to launch on device.
Hope this helps others facing the issues

**Comment by BagoiDimari** [comment]
run 'rvm install "ruby-2.7.6' on Mac machine terminal
then run ruby --version
if you are still getting the old version,
run 'rvm use ruby-2.7.6 --default'

**Comment by 1mehdifaraji** [comment]
> 

Where is the gemfile and how can I edit the ruby version there ?

**Comment by 1mehdifaraji** [comment]
> What i tried is below:
> 
> 1. when the this failure happens. Simply go to the Gemfile
> 2. change the existing version from whatever it is to the version the errors says it wants (for e.g. 3.1.2)
> 3. then do npm install and then run the respective command to launch on device.
>    Hope this helps others facing the issues


Where is the gemfile and how can I edit the ruby version there ?

**Comment by nolife08021** [comment]
@1mehdifaraji  hi, do you found it?

**Comment by MohamedAhmed122** [comment]
There's a really easy solution for this issue works for me all the time 
1- Open the project in code editor 
2- Open `.ruby-version` file  and change ruby version to your current ruby version 
3- Open` Gemfile` file and change ruby version to your ruby version 
and you will have install the pods for iOS `cd ios && pod install` 

Note: in my case I change ruby from 2.7.5 to 2.7.7, So I am not sure it will work for versions that below 2.7.5

**Comment by hpardess** [comment]
> There's a really easy solution for this issue works for me all the time 1- Open the project in code editor 2- Open `.ruby-version` file and change ruby version to your current ruby version 3- Open` Gemfile` file and change ruby version to your ruby version and you will have install the pods for iOS `cd ios && pod install`
> 
> Note: in my case I change ruby from 2.7.5 to 2.7.7, So I am not sure it will work for versions that below 2.7.5

https://github.com/facebook/react-native/issues/35053#issuecomment-1445395116

I have set the ruby version to my local version (2.7.6 to 3.1.2) but still has issue
<img width="892" alt="Screen Shot 2023-02-26 at 8 11 40 PM" src="https://user-images.githubusercontent.com/6196491/221421777-da3c62fe-2f13-4faf-8512-81979f43651a.png">

**Comment by S-iddhartham** [comment]
you can install simple way. Install rbenv On macOS with Homebrew.

1. brew install rbenv ruby-build
2. vi ~/.zshrc // open
3. eval "$(rbenv init - zsh)" // paste it
4. rbenv install 3.1.2
5.  Close your Terminal window and open a new one so your changes take effect.

**Comment by S-iddhartham** [comment]
> Did anyone get the solution? I am also getting the same issue.
> 
> Just out of curiosity, what is the mac os of yours? Mine is big sur 11.2. Is this cud b the issue?

tomorrow i did it using this https://github.com/rbenv/rbenv, my os version is 13.2.1. you can try it. it may be help you

**Comment by githubissignedup** [comment]
I got the solution. Change the ruby version and close terminal and run npx react-native command. it will work.
rvm use (3.0.0) any version which will match gem
