### ISSUE TITLE
react native app cant install on android 11

### ISSUE THREAD

**Issue by rinaldycodes** [facebook/react-native#35120]
### Description

some user cant install react native app, on android 11 , why ?
#help

### Version

0.69.6

### Output of `npx react-native info`

npx react-native info
info Fetching system and libraries information...
error Unable to print environment info.
Error: Command failed: wmic os get Caption
ERROR:
Description = Invalid namespace

info React Native v0.70.4 is now available (your project is running on v0.69.6).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.70.4.
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.69.6.
info To upgrade, run "react-native upgrade".

### Steps to reproduce

help

### Snack, code example, screenshot, or link to a repository

npx react-native info
info Fetching system and libraries information...
error Unable to print environment info.
Error: Command failed: wmic os get Caption
ERROR:
Description = Invalid namespace

info React Native v0.70.4 is now available (your project is running on v0.69.6).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.70.4.
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.69.6.
info To upgrade, run "react-native upgrade".

**Comment by cortinico** [comment]
Hi @rinaldycodes 
Thanks for reporting this issue.

>  Error: Command failed: wmic os get Caption

According to this message, seems like this issue is actually unrelated to React Native core but is related to our CLI:
https://github.com/react-native-community/cli/issues

I'll be closing this but feel free to reopen if the other repo points back to us as a issue in the core of React Native.
