### ISSUE TITLE
Android build fails because of jcenter

### ISSUE THREAD

**Issue by dejawho** [facebook/react-native#35135]
### Description

Hi,
I have a react native project I was able to build until some days ago, now the build fails because it is not able to resolve anymore the dependency on jcenter, for example I get this kind of errors

`https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib/1.2.71/kotlin-stdlib-1.2.71.jar`

I tried to modify the build.gradle and replace the jcenter() with mavenCentral(), but I got the same error

### Version

0.64.0

### Output of `npx react-native info`

System:
    OS: Windows 10 10.0.19044
    CPU: (6) x64 Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz
    Memory: 6.14 GB / 15.96 GB
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\git\YouCoach\node_modules\.bin\yarn.CMD
    npm: 8.5.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 28, 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6953283
    Visual Studio: Not Found
  Languages:
    Java: 11.0.9 - C:\Program Files\Common Files\Oracle\Java\javapath\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

 ./gradlew bundleRelease

### Snack, code example, screenshot, or link to a repository

// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        googlePlayServicesVersion = "+" // default: "+"
        firebaseMessagingVersion = "21.1.0" // default: "21.1.0"
        buildToolsVersion = "30.0.2"
        minSdkVersion = 21
        compileSdkVersion = 31
        targetSdkVersion = 31
        ndkVersion = "20.1.5948944"
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:4.1.0")
        classpath('com.google.gms:google-services:4.3.3')
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        google()
        mavenCentral()
        maven { url 'https://www.jitpack.io' }
    }
}

**Comment by olcaneristi** [comment]
I'm also getting the same error (version 0.66.4). anyone know what should we do?

**Comment by LeeKyungJoon2** [comment]
https://github.com/facebook/react-native/issues/35136

**Comment by ZohaibAhmad786** [comment]
is there any update on this i have tried all the possible steps but could not resolved.

**Comment by saurabhkumar444** [comment]
I tried to modify the build.gradle and replace the jcenter() with mavenCentral(), but I got the same error. But another laptop it's working.

**Comment by dsipahioglu** [comment]
> I tried to modify the build.gradle and replace the jcenter() with mavenCentral(), but I got the same error. But another laptop it's working.

The other laptop is probably working because you haven't executed gradle clean from there.

**Comment by kurisu994** [comment]
I remove jcenter in `build.gradle` ,it resolved!

`project root` => `android` => `build.gradle`
```gradle
allprojects {
    repositories {
        all { ArtifactRepository repo ->
            if(repo instanceof MavenArtifactRepository){
                def url = repo.url.toString()
                if (url.startsWith('https://jcenter.bintray.com/')) {
                    remove repo
                }
            }
        }
    }
}

```

**Comment by Simoon-F** [comment]
has been restored

**Comment by cortinico** [comment]
Closing as this was a local outage
