### ISSUE TITLE
[SliderIOS] Suggestion: Add 'Disable' and Step" props

### ISSUE THREAD

**Issue by Bronts** [facebook/react-native#3513]
1.This Component lack userInteractionEnabled props like Native option
2.There is no props for setting step

**Comment by ide** [comment]
Use pointerEvents to disable user interaction. Step support is a good feature to add.

**Comment by manask88** [comment]
disable has been implemented. https://facebook.github.io/react-native/docs/sliderios.html. So this issue can probably be closed

**Comment by ide** [comment]
Ok, thanks for the note! `step` is also supported.
