### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by vaish8529** [facebook/react-native#35149]
Not working........
> > > > ```
> > > >         // jcenter()
> > > >         def REPOSITORY_URL = "https://repo1.maven.org/maven2"
> > > >         all { ArtifactRepository repo ->
> > > >             if(repo instanceof MavenArtifactRepository){
> > > >                 def url = repo.url.toString()
> > > >                 if (url.startsWith('https://jcenter.bintray.com/')) {
> > > >                     project.logger.lifecycle "Repository ${repo.url} replaced by $REPOSITORY_URL."
> > > >                     remove repo
> > > >                 }
> > > >             }
> > > >         }
> > > >         maven {
> > > >             url REPOSITORY_URL
> > > >         }
> > > > ```
> > > 
> > > 
> > > this solution work for me thanks
> > > ![asdqw](https://user-images.githubusercontent.com/33805731/198985671-d7a50150-8efa-4421-97ef-5470ecd10cd7.png)
> 
> > This solution worked for me. Thanks a lot!
> 
> still not working for me..... any one tell me what's going wrong here

Probably because you have some node_modules that doesn't contains `mavenCentral()` but only `jcenter()`. Add `mavenCentral()` in the build.gradle of the module that missing it should resolve it.

_Originally posted by @wbinarytree in https://github.com/facebook/react-native/issues/35136#issuecomment-1296880444_

After updating these changes......

Execution failed for task ':app:mergeDebugResources'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.facebook.flipper:flipper:0.39.0.
     Searched in the following locations:
       - https://repo1.maven.org/maven2/com/facebook/flipper/flipper/0.39.0/flipper-0.39.0.pom
       - file:/C:/Users/elite/.m2/repository/com/facebook/flipper/flipper/0.39.0/flipper-0.39.0.pom
       - file:/D:/Projects/MobileApp/poimobileapp/node_modules/react-native/android/com/facebook/flipper/flipper/0.39.0/flipper-0.39.0.pom      
       - file:/D:/Projects/MobileApp/poimobileapp/node_modules/jsc-android/dist/com/facebook/flipper/flipper/0.39.0/flipper-0.39.0.pom
       - file:/D:/Projects/MobileApp/poimobileapp/node_modules/@notifee/react-native/android/libs/com/facebook/flipper/flipper/0.39.0/flipper-0.39.0.pom
       - https://repo.maven.apache.org/maven2/com/facebook/flipper/flipper/0.39.0/flipper-0.39.0.pom
       - https://dl.google.com/dl/android/maven2/com/facebook/flipper/flipper/0.39.0/flipper-0.39.0.pom
     Required by:
         project :app
   > Could not find com.facebook.flipper:flipper-network-plugin:0.39.0.
     Searched in the following locations:
       - https://repo1.maven.org/maven2/com/facebook/flipper/flipper-network-plugin/0.39.0/flipper-network-plugin-0.39.0.pom
       - file:/C:/Users/elite/.m2/repository/com/facebook/flipper/flipper-network-plugin/0.39.0/flipper-network-plugin-0.39.0.pom
       - file:/D:/Projects/MobileApp/poimobileapp/node_modules/react-native/android/com/facebook/flipper/flipper-network-plugin/0.39.0/flipper-network-plugin-0.39.0.pom
       - file:/D:/Projects/MobileApp/poimobileapp/node_modules/jsc-android/dist/com/facebook/flipper/flipper-network-plugin/0.39.0/flipper-network-plugin-0.39.0.pom
       - file:/D:/Projects/MobileApp/poimobileapp/node_modules/@notifee/react-native/android/libs/com/facebook/flipper/flipper-network-plugin/0.39.0/flipper-network-plugin-0.39.0.pom
       - https://repo.maven.apache.org/maven2/com/facebook/flipper/flipper-network-plugin/0.39.0/flipper-network-plugin-0.39.0.pom
       - https://dl.google.com/dl/android/maven2/com/facebook/flipper/flipper-network-plugin/0.39.0/flipper-network-plugin-0.39.0.pom
     Required by:
         project :app
   > Could not find com.facebook.flipper:flipper-fresco-plugin:0.39.0.
     Searched in the following locations:
       - https://repo1.maven.org/maven2/com/facebook/flipper/flipper-fresco-plugin/0.39.0/flipper-fresco-plugin-0.39.0.pom
       - file:/C:/Users/elite/.m2/repository/com/facebook/flipper/flipper-fresco-plugin/0.39.0/flipper-fresco-plugin-0.39.0.pom
       - file:/D:/Projects/MobileApp/poimobileapp/node_modules/react-native/android/com/facebook/flipper/flipper-fresco-plugin/0.39.0/flipper-fresco-plugin-0.39.0.pom
       - file:/D:/Projects/MobileApp/poimobileapp/node_modules/jsc-android/dist/com/facebook/flipper/flipper-fresco-plugin/0.39.0/flipper-fresco-plugin-0.39.0.pom
       - file:/D:/Projects/MobileApp/poimobileapp/node_modules/@notifee/react-native/android/libs/com/facebook/flipper/flipper-fresco-plugin/0.39.0/flipper-fresco-plugin-0.39.0.pom
       - https://repo.maven.apache.org/maven2/com/facebook/flipper/flipper-fresco-plugin/0.39.0/flipper-fresco-plugin-0.39.0.pom
       - https://dl.google.com/dl/android/maven2/com/facebook/flipper/flipper-fresco-plugin/0.39.0/flipper-fresco-plugin-0.39.0.pom
     Required by:
         project :app
   > Could not find com.github.PhilJay:MPAndroidChart:v3.1.0.
     Searched in the following locations:
       - https://repo1.maven.org/maven2/com/github/PhilJay/MPAndroidChart/v3.1.0/MPAndroidChart-v3.1.0.pom
       - file:/C:/Users/elite/.m2/repository/com/github/PhilJay/MPAndroidChart/v3.1.0/MPAndroidChart-v3.1.0.pom
       - file:/D:/Projects/MobileApp/poimobileapp/node_modules/react-native/android/com/github/PhilJay/MPAndroidChart/v3.1.0/MPAndroidChart-v3.1.0.pom
       - file:/D:/Projects/MobileApp/poimobileapp/node_modules/jsc-android/dist/com/github/PhilJay/MPAndroidChart/v3.1.0/MPAndroidChart-v3.1.0.pom
       - file:/D:/Projects/MobileApp/poimobileapp/node_modules/@notifee/react-native/android/libs/com/github/PhilJay/MPAndroidChart/v3.1.0/MPAndroidChart-v3.1.0.pom
       - https://repo.maven.apache.org/maven2/com/github/PhilJay/MPAndroidChart/v3.1.0/MPAndroidChart-v3.1.0.pom
       - https://dl.google.com/dl/android/maven2/com/github/PhilJay/MPAndroidChart/v3.1.0/MPAndroidChart-v3.1.0.pom
     Required by:
         project :app > project :react-native-charts-wrapper
   > Could not find com.github.yalantis:ucrop:2.2.6-native.
     Searched in the following locations:
       - https://repo1.maven.org/maven2/com/github/yalantis/ucrop/2.2.6-native/ucrop-2.2.6-native.pom
       - file:/C:/Users/elite/.m2/repository/com/github/yalantis/ucrop/2.2.6-native/ucrop-2.2.6-native.pom
       - file:/D:/Projects/MobileApp/poimobileapp/node_modules/react-native/android/com/github/yalantis/ucrop/2.2.6-native/ucrop-2.2.6-native.pom
       - file:/D:/Projects/MobileApp/poimobileapp/node_modules/jsc-android/dist/com/github/yalantis/ucrop/2.2.6-native/ucrop-2.2.6-native.pom   
       - file:/D:/Projects/MobileApp/poimobileapp/node_modules/@notifee/react-native/android/libs/com/github/yalantis/ucrop/2.2.6-native/ucrop-2.2.6-native.pom
       - https://repo.maven.apache.org/maven2/com/github/yalantis/ucrop/2.2.6-native/ucrop-2.2.6-native.pom
       - https://dl.google.com/dl/android/maven2/com/github/yalantis/ucrop/2.2.6-native/ucrop-2.2.6-native.pom
     Required by:
         project :app > project :react-native-image-crop-picker

**Comment by ChanaChampsoft** [comment]
This is not work for me

**Comment by yylingsj** [comment]
Did you try to replace flipper to 0.162.0?
replace the flipper version like this, in the file android/gradle.properties,
```FLIPPER_VERSION=0.162.0```
It worked for me, after did this,
```
allprojects {
    repositories {
        all { ArtifactRepository repo ->
            println repo.url.toString()
            if (repo.url.toString().startsWith("https://jcenter.bintray.com/")) {
                project.logger.warn "Repository ${repo.url} removed."
                remove repo
                mavenCentral()
            }
        }
        ...
    }
}
````

**Comment by ChanaChampsoft** [comment]
> Did you try to replace flipper to 0.162.0? replace the flipper version like this, in the file android/gradle.properties, `FLIPPER_VERSION=0.162.0` It worked for me, after did this,
> 
> ```
> allprojects {
>     repositories {
>         all { ArtifactRepository repo ->
>             println repo.url.toString()
>             if (repo.url.toString().startsWith("https://jcenter.bintray.com/")) {
>                 project.logger.warn "Repository ${repo.url} removed."
>                 remove repo
>                 mavenCentral()
>             }
>         }
>         ...
>     }
> }
> ```
> 
> BTW,comment the jcenter() first.

Thank you. I will try

**Comment by Noumbi-joel** [comment]
> Did you try to replace flipper to 0.162.0? replace the flipper version like this, in the file android/gradle.properties, `FLIPPER_VERSION=0.162.0` It worked for me, after did this,
> 
> ```
> allprojects {
>     repositories {
>         all { ArtifactRepository repo ->
>             println repo.url.toString()
>             if (repo.url.toString().startsWith("https://jcenter.bintray.com/")) {
>                 project.logger.warn "Repository ${repo.url} removed."
>                 remove repo
>                 mavenCentral()
>             }
>         }
>         ...
>     }
> }
> ```
> 
> BTW,comment the jcenter() first.

This works my build is running well

**Comment by cortinico** [comment]
Closing as this was related to a JCenter outage
