### ISSUE TITLE
Unable to load Maven meta-data from bintray.com

### ISSUE THREAD

**Issue by a7chax** [facebook/react-native#35142]
### Description

i getting error when i run `./gradlew build`

```
Execution failed for task ':app:mergeDevelopmentDebugNativeLibs'.
> Could not resolve all files for configuration ':app:developmentDebugRuntimeClasspath'.
   > Could not resolve com.facebook.react:react-native:+.
     Required by:
         project :app
         project :app > project :react-native-maps
         project :app > project :react-native-async-storage_async-storage
         project :app > project :react-native-clipboard_clipboard
         project :app > project :react-native-community_datetimepicker
         project :app > project :react-native-community_geolocation
         project :app > project :react-native-community_masked-view
         project :app > project :react-native-community_progress-bar-android
         project :app > project :react-native-community_progress-view
         project :app > project :react-native-community_slider
         project :app > project :react-native-firebase_analytics
         project :app > project :react-native-firebase_app
         project :app > project :react-native-firebase_crashlytics
         project :app > project :react-native-firebase_messaging
         project :app > project :react-native-android-location-enabler
         project :app > project :react-native-cookies
         project :app > project :react-native-document-picker
         project :app > project :react-native-gesture-handler
         project :app > project :react-native-i18n
         project :app > project :react-native-image-picker
         project :app > project :react-native-linear-gradient
         project :app > project :react-native-notifications
         project :app > project :react-native-orientation-locker
         project :app > project :react-native-pdf
         project :app > project :react-native-photo-view
         project :app > project :react-native-picker
         project :app > project :react-native-reanimated
         project :app > project :react-native-safe-area-context
         project :app > project :react-native-screens
         project :app > project :react-native-select-contact
         project :app > project :react-native-svg
         project :app > project :react-native-video
         project :app > project :react-native-webview
         project :app > project :react-native-youtube
         project :app > project :rn-fetch-blob
      > Failed to list versions for com.facebook.react:react-native.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/facebook/react/react-native/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/com/facebook/react/react-native/maven-metadata.xml'.
               > Read timed out
```

when visit `https://jcenter.bintray.com/com/facebook/react/react-native/maven-metadata.xml`, showing like this : 
![image](https://user-images.githubusercontent.com/47318515/198935427-87683102-7949-4f32-a316-750f4114aabb.png)

i also try to curl `https://jcenter.bintray.com/com/facebook/react/react-native/maven-metadata.xml`, showing like this : 
![image](https://user-images.githubusercontent.com/47318515/198935720-159dcdf1-7858-4536-9a21-359b1a1c859d.png)

i also try solution from https://github.com/facebook/react-native/issues/32734, but it wont fix

### Version

0.64

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: Linux 5.4 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz
    Memory: 1.12 GB / 15.54 GB
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.18.0 - /usr/bin/node
    Yarn: Not Found
    npm: 8.19.2 - /usr/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 11.0.16.1 - /home/arungicahaya/.sdkman/candidates/java/current/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.0 => 0.64.0 
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

running `./gradlew build` in android directory

### Snack, code example, screenshot, or link to a repository

`build.gradle`

```
apply plugin: 'maven'

buildscript {
    ext {
        buildToolsVersion = "30.0.2"
        minSdkVersion = 21
        compileSdkVersion = 30
        targetSdkVersion = 30
        supportLibVersion = "30.0.0"
        versionCode=210023001 // 21 = minSdkVersion, 0, 02 24 00 = version code
        versionName="2.30.1"
        googlePlayServicesVersion = '16.+'
        androidMapsUtilsVersion = "2.2.5"
        ndkVersion = "20.1.5948944"
        
        kotlinVersion = "1.6.10" // add this line 
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:4.1.0")
        classpath 'com.google.gms:google-services:4.3.4'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.5.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion" // add this line 
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        google()
        jcenter()
        maven { url 'https://www.jitpack.io' }
    }
}
```

**Comment by ydv0121** [comment]
+1

**Comment by LeeKyungJoon2** [comment]
https://github.com/facebook/react-native/issues/35136

**Comment by umerdogar** [comment]
any proper solution to this?

**Comment by gonghanleiq** [comment]
+1

**Comment by toeytom** [comment]
+1

**Comment by sssajjad007** [comment]
this work for me.
```
buildscript {
    ext {
        buildToolsVersion = "30.0.2"
        minSdkVersion = 21
        compileSdkVersion = 30
        targetSdkVersion = 30
        ndkVersion = "21.4.7075529"

        // REACT-NATIVE-NAVIGATION
        kotlinVersion = "1.6.10"
        RNNKotlinVersion = kotlinVersion
    }
    repositories {
       google()
        mavenCentral()
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
        classpath("com.android.tools.build:gradle:4.2.2")
        classpath 'com.google.gms:google-services:4.3.10'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.8.1'
    }
}

allprojects {
    repositories {
        mavenCentral {
            // We don't want to fetch react-native from Maven Central as there are
            // older versions over there.
            content {
                excludeGroup "com.facebook.react"
            }
        }
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }


        maven { url "https://dl.google.com/dl/android/maven2/" }
        maven { url "https://jcenter.bintray.com/" }
        maven { url 'https://plugins.gradle.org/m2/'}
        maven { url "https://maven.google.com" }
        maven { url 'https://www.jitpack.io' }
        maven { url 'https://mvnrepository.com/artifact/com.android.tools.lint/lint-gradle-api' }

        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
        google()

        maven {
            url 'https://mvnrepository.com/artifact/com.android.tools.lint/lint-gradle-api'
        }
    }
}

```

**Comment by tegozen** [comment]
> this work for me.
> 
> ```
> buildscript {
>     ext {
>         buildToolsVersion = "30.0.2"
>         minSdkVersion = 21
>         compileSdkVersion = 30
>         targetSdkVersion = 30
>         ndkVersion = "21.4.7075529"
> 
>         // REACT-NATIVE-NAVIGATION
>         kotlinVersion = "1.6.10"
>         RNNKotlinVersion = kotlinVersion
>     }
>     repositories {
>        google()
>         mavenCentral()
>     }
>     dependencies {
>         classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
>         classpath("com.android.tools.build:gradle:4.2.2")
>         classpath 'com.google.gms:google-services:4.3.10'
>         classpath 'com.google.firebase:firebase-crashlytics-gradle:2.8.1'
>     }
> }
> 
> allprojects {
>     repositories {
>         mavenCentral {
>             // We don't want to fetch react-native from Maven Central as there are
>             // older versions over there.
>             content {
>                 excludeGroup "com.facebook.react"
>             }
>         }
>         mavenLocal()
>         maven {
>             // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
>             url("$rootDir/../node_modules/react-native/android")
>         }
>         maven {
>             // Android JSC is installed from npm
>             url("$rootDir/../node_modules/jsc-android/dist")
>         }
> 
> 
>         maven { url "https://dl.google.com/dl/android/maven2/" }
>         maven { url "https://jcenter.bintray.com/" }
>         maven { url 'https://plugins.gradle.org/m2/'}
>         maven { url "https://maven.google.com" }
>         maven { url 'https://www.jitpack.io' }
>         maven { url 'https://mvnrepository.com/artifact/com.android.tools.lint/lint-gradle-api' }
> 
>         maven {
>             url 'https://maven.google.com/'
>             name 'Google'
>         }
>         google()
> 
>         maven {
>             url 'https://mvnrepository.com/artifact/com.android.tools.lint/lint-gradle-api'
>         }
>     }
> }
> ```

I love you bro)

**Comment by yoonzm** [comment]
https://github.com/facebook/react-native/issues/35136#issuecomment-1296688691

**Comment by Simoon-F** [comment]
Has been restored.
JCenter works now.
