### ISSUE TITLE
tried but not working

### ISSUE THREAD

**Issue by vaish8529** [facebook/react-native#35150]
worked for me replacing jcenter() to mavenCentral()

_Originally posted by @Developeranees in https://github.com/facebook/react-native/issues/35136#issuecomment-1296584350_

Execution failed for task ':app:mergeDebugResources'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.facebook.flipper:flipper:0.39.0.
     Searched in the following locations:
       - file:/C:/Users/elite/.m2/repository/com/facebook/flipper/flipper/0.39.0/flipper-0.39.0.pom
       - file:/D:/Projects/MobileApp/poimobileapp/node_modules/react-native/android/com/facebook/flipper/flipper/0.39.0/flipper-0.39.0.pom      
       - file:/D:/Projects/MobileApp/poimobileapp/node_modules/jsc-android/dist/com/facebook/flipper/flipper/0.39.0/flipper-0.39.0.pom
       - file:/D:/Projects/MobileApp/poimobileapp/node_modules/@notifee/react-native/android/libs/com/facebook/flipper/flipper/0.39.0/flipper-0.39.0.pom
       - https://dl.google.com/dl/android/maven2/com/facebook/flipper/flipper/0.39.0/flipper-0.39.0.pom
       - https://www.jitpack.io/com/facebook/flipper/flipper/0.39.0/flipper-0.39.0.pom
       - https://maven.google.com/com/facebook/flipper/flipper/0.39.0/flipper-0.39.0.pom
       - https://repo.maven.apache.org/maven2/com/facebook/flipper/flipper/0.39.0/flipper-0.39.0.pom
     Required by:
         project :app
   > Could not find com.facebook.flipper:flipper-network-plugin:0.39.0.
     Searched in the following locations:
       - file:/C:/Users/elite/.m2/repository/com/facebook/flipper/flipper-network-plugin/0.39.0/flipper-network-plugin-0.39.0.pom
       - file:/D:/Projects/MobileApp/poimobileapp/node_modules/react-native/android/com/facebook/flipper/flipper-network-plugin/0.39.0/flipper-network-plugin-0.39.0.pom
       - file:/D:/Projects/MobileApp/poimobileapp/node_modules/jsc-android/dist/com/facebook/flipper/flipper-network-plugin/0.39.0/flipper-network-plugin-0.39.0.pom
       - file:/D:/Projects/MobileApp/poimobileapp/node_modules/@notifee/react-native/android/libs/com/facebook/flipper/flipper-network-plugin/0.39.0/flipper-network-plugin-0.39.0.pom
       - https://dl.google.com/dl/android/maven2/com/facebook/flipper/flipper-network-plugin/0.39.0/flipper-network-plugin-0.39.0.pom
       - https://www.jitpack.io/com/facebook/flipper/flipper-network-plugin/0.39.0/flipper-network-plugin-0.39.0.pom
       - https://maven.google.com/com/facebook/flipper/flipper-network-plugin/0.39.0/flipper-network-plugin-0.39.0.pom
       - https://repo.maven.apache.org/maven2/com/facebook/flipper/flipper-network-plugin/0.39.0/flipper-network-plugin-0.39.0.pom
     Required by:
         project :app
   > Could not find com.facebook.flipper:flipper-fresco-plugin:0.39.0.
     Searched in the following locations:
       - file:/C:/Users/elite/.m2/repository/com/facebook/flipper/flipper-fresco-plugin/0.39.0/flipper-fresco-plugin-0.39.0.pom
       - file:/D:/Projects/MobileApp/poimobileapp/node_modules/react-native/android/com/facebook/flipper/flipper-fresco-plugin/0.39.0/flipper-fresco-plugin-0.39.0.pom
       - file:/D:/Projects/MobileApp/poimobileapp/node_modules/jsc-android/dist/com/facebook/flipper/flipper-fresco-plugin/0.39.0/flipper-fresco-plugin-0.39.0.pom
       - file:/D:/Projects/MobileApp/poimobileapp/node_modules/@notifee/react-native/android/libs/com/facebook/flipper/flipper-fresco-plugin/0.39.0/flipper-fresco-plugin-0.39.0.pom
       - https://dl.google.com/dl/android/maven2/com/facebook/flipper/flipper-fresco-plugin/0.39.0/flipper-fresco-plugin-0.39.0.pom
       - https://www.jitpack.io/com/facebook/flipper/flipper-fresco-plugin/0.39.0/flipper-fresco-plugin-0.39.0.pom
       - https://maven.google.com/com/facebook/flipper/flipper-fresco-plugin/0.39.0/flipper-fresco-plugin-0.39.0.pom
       - https://repo.maven.apache.org/maven2/com/facebook/flipper/flipper-fresco-plugin/0.39.0/flipper-fresco-plugin-0.39.0.pom
     Required by:
         project :app

**Comment by Thirumalaisamy-paulraj** [comment]
https://stackoverflow.com/questions/70060992/react-native-please-remove-usages-of-jcenter-maven-repository-from-your-b
you will find the solution here ------>^^^
