### ISSUE TITLE
White rectangle appears in bottom right of screen when using TextInput with showSoftInputOnFocus={false}

### ISSUE THREAD

**Issue by chriscoomber** [facebook/react-native#35151]
### Description

This affects a limited set of iOS devices. So far I've only seen it on iPads, e.g. iPad mini (6th gen) at v15.3.1.

Background: I want a TextInput which can be focused, but which does not show the keyboard. This is because I have my own on-screen keyboard, or other buttons to manipulate the text. (In the following example, I don't make use of focus, but in my actual requirements I use focus to decide which TextInput receives input from my on-screen input - so making use of focus is important to me.)

Code sample:

```
export default function HomeScreen() {
  const [text, setText] = useState('');

  return <View style={{justifyContent: 'center', alignItems: 'center', height: '100%'}}>
    <TextInput showSoftInputOnFocus={false} value={text} onChangeText={setText} style={{width: 500, height: 100, borderWidth: 1}}/>
    <Button title='Add random digit' onPress={() => setText(old => old + Math.floor(Math.random()*10))}/>
    <Button title='Delete' onPress={() => setText(old => old.slice(0, -1))}/>
  </View>;
}
```

Expected result: no evidence of a keyboard appears, but focus works as normal.
Actual result: works fine on Android and most iOS devices, but on some iPads we see the following:

![IMG_0004](https://user-images.githubusercontent.com/4904335/198987747-f16ac630-5a2a-48e7-ad40-0d31a03bf0d7.PNG)

This is annoying, as we see the predictive text bar at the bottom. That is not something that I want.

I can mostly hide that by adding the prop `keyboardType='number-pad'` to the TextInput. This results in:

![IMG_0005](https://user-images.githubusercontent.com/4904335/198997973-35e117fa-b62c-4ec0-b599-8e1152b4e173.PNG)

There is still an annoying white rectangle in the bottom right, which appears precisely when the TextInput has focus. This interferes with our design. There is no way to eliminate this white rectangle whilst keeping the TextInput focusable. I have experimented with other props:

```
      contextMenuHidden={true}
      disableFullscreenUI={true}
      autoCorrect={false}
      spellCheck={false}
      autoComplete='password'
      textContentType='none'
      returnKeyType='none'
      inputAccessoryViewID="dummyEmptyView"
```

none of these help.

### Version

0.68.2

(Using expo version 45.0.6. I have verified that this is not an expo-go issue: the problem manifests for standalone builds.)

### Output of `npx react-native info`

```
info Fetching system and libraries information...
System:
    OS: macOS 12.5.1
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 1.43 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - /var/folders/tl/npj1w_357hq728xf88m189w00000gn/T/yarn--1667215960816-0.9847397295527662/node
    Yarn: 1.22.18 - /var/folders/tl/npj1w_357hq728xf88m189w00000gn/T/yarn--1667215960816-0.9847397295527662/yarn
    npm: 8.5.0 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.2 => 0.68.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
info React Native v0.70.4 is now available (your project is running on v0.68.2).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.70.4.
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.68.2.
info To upgrade, run "react-native upgrade".
✨  Done in 18.25s.
```

### Steps to reproduce

1. Use an iPad mini (6th gen)
2. Add a TextInput with props: `showSoftInputOnFocus={false} keyboardType='number-pad'`
3. Build the app
4. Click on the text input
5. Observe that the keyboard does not show (good!) but a white rectangle appears in the bottom right (bad!)

### Snack, code example, screenshot, or link to a repository

See description above for code sample and screenshot. This is not reproducible in snack, because the iOS simulator in snack is not one of the iOS devices which experiences this issue.

**Comment by hetoms** [comment]
That white rectangle seems to mess with keyboard aware views as well (at least for me), it seems like phantom keyboard. I also have not figured out how to get rid of it...

**Comment by fabriziobertoglio1987** [comment]
Do you still experience this issue? 

I have four years of experience maintaining facebook/react-native and I specialize in the Text and TextInput components. I currently have 58 [facebook/react-native PRs](https://github.com/facebook/react-native/pulls?q=is%3Apr+author%3Afabriziobertoglio1987+). 

If you still experience this issue, I will prepare a patched release with the fix.

Thanks a lot
