### ISSUE TITLE
[Flatlist] I want to adjust the scroll speed in android.

### ISSUE THREAD

**Issue by SangWonyy** [facebook/react-native#35171]
### New Version

0.66.3

### Old Version

0.66.3

### Build Target(s)

android

### Output of `react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 12.6
    CPU: (20) x64 Intel(R) Core(TM) i9-10910 CPU @ 3.60GHz
    Memory: 499.57 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.18 - ~/.nvm/versions/node/v16.13.0/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK: Not Found
  IDEs:
    Android Studio: Arctic Fox 2020.3.1 Patch 3 Arctic Fox 2020.3.1 Patch 3
    Xcode: 14.0/14A309 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.12 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.3 => 0.66.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Issue and Reproduction Steps

hello.
I am building a flatlist function with one video per page.

problem
 For Android only, the scrolling speed is very fast when turning one page. Especially if you snap your finger quickly, it goes through very quickly.
 We want to adjust this speed.
 
I've tried several methods.
 Attempted to control through the decelerationRate property. This confirms that it rises very slowly when you do a slow finger snap. But if you do it quickly, this is ignored. Also, the scrolling speed is not adjustable.
 
 
Is it possible to achieve a constant scroll speed regardless of the speed of the finger snap?

**Comment by fewoy** [comment]
![image](https://user-images.githubusercontent.com/14038970/207542105-79031206-e191-4d34-807a-1ca52af1a976.png)

**Comment by chaitanya71998** [comment]
@SangWonyy did you have done any custom implementations?

**Comment by wkz2003** [comment]
I've been looking for a solution for a long time,did you find a useful way??
