### ISSUE TITLE
Facing build time issue 18 duplicate symbols for architecture x86_64 in 0.70.4

### ISSUE THREAD

**Issue by keerthika-priya** [facebook/react-native#35184]
### New Version

0.70.4

### Old Version

0.61.2

### Build Target(s)

All

### Info
Build/Products/Debug-iphonesimulator/React-Core/React.framework/React(RCTTiming.o)
duplicate symbol '_OBJC_IVAR_$_RCTTiming._paused' in:
    /Users/keerthika.priya/Library/Developer/Xcode/DerivedData/Flipkart-bhnnxmwldjckhthhnqipiomorpyr/Build/Products/Debug-iphonesimulator/React-CoreModules/CoreModules.framework/CoreModules(RCTTiming.o)
    /Users/keerthika.priya/Library/Developer/Xcode/DerivedData/Flipkart-bhnnxmwldjckhthhnqipiomorpyr/Build/Products/Debug-iphonesimulator/React-Core/React.framework/React(RCTTiming.o)
duplicate symbol '_OBJC_IVAR_$__RCTTimer._callbackID' in:
    /Users/keerthika.priya/Library/Developer/Xcode/DerivedData/Flipkart-bhnnxmwldjckhthhnqipiomorpyr/Build/Products/Debug-iphonesimulator/React-CoreModules/CoreModules.framework/CoreModules(RCTTiming.o)
    /Users/keerthika.priya/Library/Developer/Xcode/DerivedData/Flipkart-bhnnxmwldjckhthhnqipiomorpyr/Build/Products/Debug-iphonesimulator/React-Core/React.framework/React(RCTTiming.o)
ld: 18 duplicate symbols for architecture x86_64

### Issue and Reproduction Steps

The react native pods for 0.70.4 gives the following error
<img width="873" alt="Screenshot 2022-11-03 at 12 24 11 PM" src="https://user-images.githubusercontent.com/108332636/199662337-db0647ce-211a-4c66-b992-2813e047be03.png">

There are 2 RCTTiming files in Core-Modules and Modules folders.
Please help regarding this.

**Comment by keerthika-priya** [comment]
Build/Products/Debug-iphonesimulator/React-Core/React.framework/React(RCTTiming.o)
duplicate symbol '_OBJC_IVAR_$_RCTTiming._paused' in:
    /Users/keerthika.priya/Library/Developer/Xcode/DerivedData/Flipkart-bhnnxmwldjckhthhnqipiomorpyr/Build/Products/Debug-iphonesimulator/React-CoreModules/CoreModules.framework/CoreModules(RCTTiming.o)
    /Users/keerthika.priya/Library/Developer/Xcode/DerivedData/Flipkart-bhnnxmwldjckhthhnqipiomorpyr/Build/Products/Debug-iphonesimulator/React-Core/React.framework/React(RCTTiming.o)
duplicate symbol '_OBJC_IVAR_$__RCTTimer._callbackID' in:
    /Users/keerthika.priya/Library/Developer/Xcode/DerivedData/Flipkart-bhnnxmwldjckhthhnqipiomorpyr/Build/Products/Debug-iphonesimulator/React-CoreModules/CoreModules.framework/CoreModules(RCTTiming.o)
    /Users/keerthika.priya/Library/Developer/Xcode/DerivedData/Flipkart-bhnnxmwldjckhthhnqipiomorpyr/Build/Products/Debug-iphonesimulator/React-Core/React.framework/React(RCTTiming.o)
ld: 18 duplicate symbols for architecture x86_64

**Comment by ana-nd-s** [comment]
@keerthika-priya We are also facing this issue after upgrading to the latest react native version

```
System:
    OS: macOS 12.5
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Memory: 55.71 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.1/bin/npm
    Watchman: 2022.09.19.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/anandkumar/.rvm/rubies/ruby-2.7.2/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 23, 25, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 32.0.0
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7351085
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.70.6 => 0.70.6
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by keerthika-priya** [comment]
My issue was a local script which was used to patch the RCTTiming file and thus kept adding it again and again.

**Comment by thisisadarshjais** [comment]
Any solution here??
