### ISSUE TITLE
Nested Virtualized Lists in opposing directions firing all onViewableItemsChanged

### ISSUE THREAD

**Issue by vincentvella** [facebook/react-native#35180]
## Nested Bidirectional FlatList onViewableItemsChanged Issue

| App Image | Layout Image |
| -- | -- | 
| <img src="https://user-images.githubusercontent.com/22749569/199587072-4e701960-70b8-4717-899d-5ec0d8b64c56.png" height="800" /> | <img src="https://user-images.githubusercontent.com/22749569/199590147-995eb9e8-d787-4b60-a191-118ef5515fe9.png" height="800" /> |

The above images describe the layout where this problem has arisen. Essentially it's a 2D FlatList.

When the Vertical FlatList mounts and the onViewableItemsChanged prop callbacks fire for each element on the screen, the expected behavior is working. 

However, once the nested FlatLists mount, instead of firing the onViewableItemsChanged callback for only the nested Horizontal FlatList items that are within the visible viewport, it fires for all rendered list items (including those that are out of the viewport). It seems that the correct viewability is determined on horizontal lists, however, the VirtualizedList doesn't check if those horizontal lists are vertically visible.

Below, I've illustrated the expected vs actual behavior with images/emojis

🎇 - Vertical FlatList onViewableItemsChanged callback fires
🔥 - Horizontal FlatList onViewableItemsChanged callback fires

| Expected | Actual | 
| -- | -- |
| ![Untitled-2022-08-26-1424](https://user-images.githubusercontent.com/22749569/199594546-539c3836-5d63-4b66-b2a4-f36648d12ac5.png) | ![Untitled-2022-08-26-1424](https://user-images.githubusercontent.com/22749569/199594749-bd59c667-4fb5-4ec1-bf74-de77edf66b68.png) |

### Version

0.70.4

### Output of `npx react-native info`

```
System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Max
    Memory: 204.02 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.18.0/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK:
      API Levels: 29, 30, 31, 32, 33
      Build Tools: 29.0.3, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 33.0.0, 33.0.0
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play ARM 64 v8a, android-29 | Google Play Intel x86 Atom_64, android-31 | Google Play ARM 64 v8a, android-32 | Google APIs ARM 64 v8a, android-32 | Google Play ARM 64 v8a, android-33 | Google Play ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /Users/vvella/.jenv/shims/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.4 => 0.70.4
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1. Create a vertical FlatList that contains a 2D data array with a length long enough to make the list run off of your screen and require scrolling
2. Create another FlatList (horizontal) to be rendered in the renderItem prop of the parent FlatList
3. Add a onViewableItemsChanged to the nested (horizontal) FlatList
4. Observe that all items rendered (regardless of vertical viewability) fire their onViewableItemsChanged callback

I provided a minimum setup repo below you can clone. Only changed the App.tsx file to recreate the above steps.

### Snack, code example, screenshot, or link to a repository

Snack: https://snack.expo.dev/@vincentvella/great-almond
Repo: https://github.com/vincentvella/bidirectional-virtualized-list-issue

**Comment by vincentvella** [comment]
![Simulator Screen Shot - iPhone 14 Pro - 2022-11-03 at 12 41 10](https://user-images.githubusercontent.com/22749569/199781716-c8220e07-4298-4af4-8435-c9361d4b6980.png)

Taken from the tester app
See that InnerViewable shows "56,57,58" 
All of which are horizontally viewable but not vertically shown in the viewport

**Comment by boltonotieno** [comment]
Facing a similar issue, I observed that the onViewableItemsChanged callbacks are triggered for items inside the nested horizontal list even before the horizontal list is within the viewport. This behavior seems to be caused by the windowSize prop, which pre-renders items outside the current viewable items. By default, the size is set to 21, so it pre-renders 21 items. If the nested horizontal list is part of these 21 items (the customized windowSize you have), it triggers callbacks for items inside the horizontal list that are horizontally viewable. However, the callback for the parent card is called as expected when it enters the viewport.

**Comment by micheleb** [comment]
for anyone landing on this issue like I did, it was actually reopened as #37833
