### ISSUE TITLE
Attribute statusBarTranslucent turns the Modal position to fixed

### ISSUE THREAD

**Issue by yurecouto** [facebook/react-native#35219]
### Description

I put an InputText in a Modal, and when the keyboard activated, the modal stayed fixed and the keyboard overlaps the modal, removing the attribute statusBarTranslucent, the modal started to work properly.

### Version

0.69.6

### Output of `npx react-native info`

System:
    OS: Linux 5.19 Fedora Linux 36 (Workstation Edition)
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
    Memory: 11.75 GB / 19.34 GB
    Shell: 5.2.2 - /bin/bash
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 1.22.17 - /usr/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.6 => 0.69.6 
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Put an InputText inside a Modal, in the Modal component, insert the attribute statusBarTranslucent, then tap the input and see the keyboard overlap.

### Snack, code example, screenshot, or link to a repository

<Modal
  visible={isOpen}
  transparent
  animationType="slide"
  hardwareAccelerated
  statusBarTranslucent
  onRequestClose={closeModal}
>

  <InputLimit
    mt={12}
    measure={greatness === "" ? "" : Measure[greatness]}
    value={limit.min ? limit.min.toString() : "0"}
    onChangeText={handleLimit}
  />

</Modal>

**Comment by fmendez89** [comment]
@yurecouto did you find any propper solution to this?
