### ISSUE TITLE
can not find symbol setBlurOnSubmit (ReactEditText)

### ISSUE THREAD

**Issue by fukemy** [facebook/react-native#35227]
### Description

Hi, today I suddenly got this error : 

***can not find symbol setBlurOnSubmit (ReactEditText)***

from wix/auto-grow-textinput

### Version

0.68.2

### Output of `npx react-native info`

System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1 Pro
    Memory: 104.56 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.10.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - ~/Documents/Work/VedaxLink/node_modules/.bin/npm
    Watchman: 2022.10.03.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: ^0.68.0 => 0.68.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

npm run android

=> got this error then can not build project

### Snack, code example, screenshot, or link to a repository

<img width="1153" alt="Screen Shot 2022-11-07 at 09 55 31" src="https://user-images.githubusercontent.com/8202437/200216938-d032d05a-7d49-4e54-8453-966e80aa5399.png">

**Comment by Pranav-yadav** [comment]
@fukemy the package you're using is _not_ updated as per the latest React Native version.
In short it look it's issue on their side(?) Others might suggest workarounds if any..

### Cause:
- The package `wix/react-native-autogrow-textinput` uses `setBlurOnSubmit` method;
Link: [wix/react-native-autogrow-textinput/blob/master/android/src/main/java/com/wix/autogrowtextinput/AutoGrowTextInputModule.java#L55](https://github.com/wix/react-native-autogrow-textinput/blob/master/android/src/main/java/com/wix/autogrowtextinput/AutoGrowTextInputModule.java#L55)

   Permalink: [wix/react-native-autogrow-textinput/blob/2bc3304/android/src/main/java/com/wix/autogrowtextinput/AutoGrowTextInputModule.java#L55](https://github.com/wix/react-native-autogrow-textinput/blob/2bc330439b95e748e92c34bbdff5473f5dc29b88/android/src/main/java/com/wix/autogrowtextinput/AutoGrowTextInputModule.java#L55)

- --  which was deprecated in `facebook/react-native`, here;
 Permalink:
https://github.com/facebook/react-native/commit/1e3cb9170794afa03a3b4b15f75b711dace7a774#diff-b941f6bcdff5060918b3091d619bae6ac105c05229ab635e33ded4fcba5bf2a7L383-L386

```diff
-  public void setBlurOnSubmit(@Nullable Boolean blurOnSubmit) {
-       mBlurOnSubmit = blurOnSubmit;
-  }
```

- You may have a look at the updated methods in `facebook/react-native` here;
   Permalinks:
   - https://github.com/facebook/react-native/blob/f0b7cbe22e2d67c102149d6d118b563b71a7fbb5/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactEditText.java#L426-L428
      and
    - https://github.com/facebook/react-native/blob/f0b7cbe22e2d67c102149d6d118b563b71a7fbb5/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactEditText.java#L386-L420

- consider updating code at `wix`s side.
PS:  _I may be wrong :)_

**Comment by fukemy** [comment]
yeah, I know problem now, thanks u so much <3

**Comment by rus5665** [comment]
@fukemy do you fix this error?

**Comment by fukemy** [comment]
change to setSubmitBehavior('') @rus5665

**Comment by sakthiyii** [comment]
@fukemy Can you please elaborate?

**Comment by fukemy** [comment]
> @fukemy Can you please elaborate?

please read above answer
