### ISSUE TITLE
Multiline TextInput's onContentSizeChange doesn't take horizontal padding into a consideration (IOS)

### ISSUE THREAD

**Issue by Redger1** [facebook/react-native#35234]
### Description

If you have multiline `<TextInput/>` with horizontal padding styles, `onContexntSizeChange` works as if horizontal padding is 0. So you can't set input's height of `nativeEvent.contentSize.height` correctly 

### Version

0.70.5

### Output of `npx react-native info`

System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i3-10100 CPU @ 3.60GHz
    Memory: 718.71 MB / 3.83 GB
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: Not Found
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^18.1.0 => 18.1.0
    react-native: ^0.70.5 => 0.70.5
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. Create `<TextInput multiline={true} blurOnSubmit={false}/>`
2. Add `onContentSizeChange` prop and inside log `nativeEvent.contentSize.height`
3. Type until the line breaks
4. Add horizontal padding and type for line break again

`onContentSizeChange` logs increased height too late when the input is already on the next line, but without padding it works correctly

### Snack, code example, screenshot, or link to a repository

```
import * as React from "react";
import { TextInput, View, StyleSheet } from 'react-native';

export default function App() {
  const [message, setMessage] = React.useState('')

  return (
    <View style={styles.container}>
      <TextInput
        placeholderTextColor="#909090"
        style={{...styles.input, height: 50}}
        placeholder="Message"
        blurOnSubmit={false}
        scrollEnabled={true}
        onChange={({nativeEvent}) => setMessage(nativeEvent.text)}
        multiline={true}
        value={message}
        onContentSizeChange={({nativeEvent}) => {
            console.log(nativeEvent.contentSize.height)
        }}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  input: {
    backgroundColor: "#F5F5F5",
    height: '100%',
    fontFamily: "Semibold",
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 10,
    maxHeight: 150,
    fontSize: 14,
    flex: 1,
  },
});
```

Expo Snack: https://snack.expo.dev/@redger1/multiline-text-input

**Comment by TheRealMentor** [comment]
@Redger1 I am also facing this issue. Can we tag someone to help look into this issue?

**Comment by TheRealMentor** [comment]
@Redger1 I have a workaround for this issue. Since, the issue with `onContentSizeChange` is mainly due to horizontal padding. I removed the padding from the `TextInput` style. Instead, I created a wrapper `View` which would handle the padding and other border styles for the `TextInput` component so the UI wise, there is no change and `TextInput` behaves same on both platform.

**Comment by oferRounds** [comment]
It looks like the origin of the bug is [here](https://github.com/facebook/react-native/blob/main/Libraries/Text/TextInput/RCTBaseTextInputShadowView.m#L225): it should count here for the padding. I wanted to send PR with a fix to this, but couldn’t find where can I take the padding value

**Comment by Panda-ref** [comment]
Can we reopen this?

**Comment by zyestin** [comment]
I solved the problem

FIX: The height returned by TextInput's 'onContentSizeChange' callback method is incorrect
Reason: Borderwidth and horizontal padding are not subtracted from the content width used to calculate the height of the text

Please use this patch
```
diff --git a/node_modules/react-native/Libraries/Text/TextInput/RCTBaseTextInputShadowView.m b/node_modules/react-native/Libraries/Text/TextInput/RCTBaseTextInputShadowView.m
index aac20ea..4bc7f9c 100644
--- a/node_modules/react-native/Libraries/Text/TextInput/RCTBaseTextInputShadowView.m
+++ b/node_modules/react-native/Libraries/Text/TextInput/RCTBaseTextInputShadowView.m
@@ -78,7 +78,9 @@ - (void)invalidateContentSize
     return;
   }
 
-  CGSize maximumSize = self.layoutMetrics.frame.size;
+  CGSize maximumSize = self.layoutMetrics.contentFrame.size;
 
   if (_maximumNumberOfLines == 1) {
     maximumSize.width = CGFLOAT_MAX;
```

**Comment by kokosky93** [comment]
@zyestin can you do a PR for that? Changing node modules is not the best thing :/

**Comment by Redger1** [comment]
@zyestin If I will use your patch, I will need to do this every time in a new project? Is there a way to make a pull request or something?

**Comment by zyestin** [comment]
> Same issue :/
> 
> @zyestin can you do a PR for that? Changing node modules is not the best thing :/

👌🏻 [react-native/pull/41803](https://github.com/facebook/react-native/pull/41803)
