### ISSUE TITLE
Hi, you have given solve for expo projects. This error is getting in react native cli after doing said solution for react-native project < 0.63

### ISSUE THREAD

**Issue by anirbanhazra** [facebook/react-native#35235]
Hi,

I did exactly what is said regarding **"Fix for older react-native (< 0.63)"**

After that, in main terminal, "**BUILD SUCCESSFUL** is showing but during bundling of the project, **Error: Cannot create a string longer than 0x1fffffe8 characters** - screenshot is attached as follows. 
![image](https://user-images.githubusercontent.com/116089600/200270407-5ed910c1-8ac5-4757-aae5-9bafc7fc5cd9.png)

_Originally posted by @anirbanhazra in https://github.com/facebook/react-native/issues/35210#issuecomment-1305295025_

**Comment by cortinico** [comment]
Essentially a duplicate of #35241
