### ISSUE TITLE
[Android] Debug in Chrome freezes with Navigator

### ISSUE THREAD

**Issue by aj9045** [facebook/react-native#3524]
I'm just trying to get familiar with the components for Android at the moment.  I was using React Native version 0.11 earlier, and debugging in Chrome was not an issue.  Then I updated the version to v0.12.  Now while debugging in Chrome, when I click a TouchableHighlight, which then pushes to the next view (using Navigator), it freezes.  Then over the next 16-17 minutes, it transitions to the next view.  Once it finishes loading after a good chunk of time, I can go back to the previous view, but the same thing happens.  The freezing/super slow transition.  However, if I disable Chrome debugging, everything works normally.

I decided to try to go back to version 0.11 of React Native, but it didn't help.  I had the same problem.  Then I thought it could be that I just need to restart everything.  So I restarted the terminal, the android avd, regenerated for the emulator, and then eventually my computer.  That didn't help either.  Then I decided to try a completely new project.  So I inited a new React Native project, and when trying to go between views while debugging in Chrome, it was still freezing.  Then I thought it might be my machine (it's 5 years old).  It's a MacBook Pro, Processor 2.4GHz Intel Core i5, Memory 8GB 1067 MHz DDR3.  I'm not sure why it was working before then...  

All in all, I'm pretty stumped.  I've heard it's a bit slow for Android, but 16 minutes seems awfully long.  I'm not sure if anyone else is having this problem, but it's nearly impossible to debug in Chrome.

This is what it looks like right after I click the TouchableHighlight.  It just freezes like this.   
![](https://cloud.githubusercontent.com/assets/8031694/10594305/c96b8364-7699-11e5-887d-32e452a03995.png)

After five minutes or so, it then freezes here.
![screen shot 2015-10-16 at 2 17 59 pm](https://cloud.githubusercontent.com/assets/8031694/10594330/0930be9c-769a-11e5-9538-86a7b9a1a3e7.png)

And then continues transitioning/freezing in different places until it gets to the next view.

**Comment by satya164** [comment]
http://facebook.github.io/react-native/docs/performance.html#slow-navigator-transitions

**Comment by aj9045** [comment]
@satya164 So I took a look at the link (thank you!).  Now the waiting/freezing time is down to 7-8 minutes, which is better, but still not ideal at all, especially since I was not having this issue previously for some reason.  Is there anything else that I can do to speed this process up?

**Comment by satya164** [comment]
@aj9045 Might be issues with the emulator I guess. Never had such lockups. Have you tried Genymotion? It's much faster than the Android emulator. Almost like a real phone.

**Comment by aj9045** [comment]
@satya164 That seemed to be my problem.  Something became off with the Android emulator.  Not sure what yet, but I do know that it works perfectly fine with Genymotion.  Thanks for your help!
