### ISSUE TITLE
Cannot create a string longer than 0x1fffffe8 characters

### ISSUE THREAD

**Issue by anirbanhazra** [facebook/react-native#35241]
### Description

The main problem occurs during bundling in android OS

After running **npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle**, process exited with thrown error **Failed to construct transformer: Error: Cannot create a string longer than 0x1fffffe8 characters** - screenshot -
![image](https://user-images.githubusercontent.com/116089600/200323832-e1cbb286-71f0-4f24-8b3c-320016ba4f78.png)

Have included kotlinVersion = "1.6.0" in android/build.gradle but still not working

Please help !!!

### Version

0.66.5

### Output of `npx react-native info`

System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
    Memory: 2.53 GB / 7.89 GB
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version     2021.1.0.0 AI-211.7628.21.2111.8309675
    Visual Studio: Not Found
  Languages:
    Java: 18.0.1 - C:\Program Files\Common Files\Oracle\Java\javapath\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.1 => 17.0.1
    react-native: ^0.66.5 => 0.66.5
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle

### Snack, code example, screenshot, or link to a repository

![image](https://user-images.githubusercontent.com/116089600/200323832-e1cbb286-71f0-4f24-8b3c-320016ba4f78.png)

**Comment by waltermvp** [comment]
Running into the same issue, did you ever figure out a solution or workaround? @anirbanhazra

**Comment by waltermvp** [comment]
I ran into this issue after editing my assets (icons, splash screens etc)

**Comment by fahry-mohammed** [comment]
Same here. I have created android flavors with different resources including splash. Getting exact same issue.

**Comment by diaa-ghonim2** [comment]
same issue here,
When I run detox build IOS or Android, I got this issue

**Comment by alecodesdancer** [comment]
After creating a bundle I ran into this error. 

I fixed it by deleting the **base.zip** file it created inside the folder:  
**_android/app/build/intermediates/module_bundle/release_**
