### ISSUE TITLE
iOS getting error RCTBridgeModule.h- Property with 'retain (or strong)' attribute must be of object type

### ISSUE THREAD

**Issue by heminicw** [facebook/react-native#35240]
### Description

iOS was working fine untill React Native version 0.71.0-rc0 published. After that iOS app failed to run on real device and simulator both. 
Getting error as .../node_modules/react-native/React/Base/RCTBridgeModule.h:132:1: Property with 'retain (or strong)' attribute must be of object type
![image](https://user-images.githubusercontent.com/87970264/200313618-6705ca28-c1cd-4b48-94e1-5bf5c55559ea.png)

### Version

0.61.5

### Output of `npx react-native info`

System:
    OS: macOS 12.5
    CPU: (6) x64 Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
    Memory: 42.50 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
    Watchman: 2022.08.29.00 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8815526
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  npmPackages:
    react-native: file:./packages/blocks/core/node_modules/react-native => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1

### Steps to reproduce

1. Uninstall `pods` and `Podfile.lock` file.
2. Again install pods by `pod install`
3. After successful install select simulator (iPhone 11 pro 13.5 ) or real device

Error will appear

### Snack, code example, screenshot, or link to a repository

![image](https://user-images.githubusercontent.com/87970264/200314477-dd3e09b9-4a36-46be-9b25-1d6ba9186fd7.png)

**Comment by raufpratama** [comment]
same issue

**Comment by heminicw** [comment]
It was firebase issue. Upgraded to firebase to latest version and started working.  Used below three dependencies of firebase
```
    "@react-native-firebase/analytics": "^16.4.3",
    "@react-native-firebase/app": "^16.4.3",
    "@react-native-firebase/messaging": "^16.4.3",
```
