### ISSUE TITLE
Build Failded when npx react-native run-ios

### ISSUE THREAD

**Issue by mellasystems** [facebook/react-native#35246]
### Description

i run the command for create a new app with ReactNative:

i get the next error: 
UserName = name for user mac.

```
** BUILD FAILED **


The following build commands failed:
	CompileC /Users/{UserName}/Library/Developer/Xcode/DerivedData/AwesomeProject-cwmjccyvpdetjnhjomqixwqlnadb/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-Codegen.build/Objects-normal/x86_64/FBReactNativeSpec-generated.o /Users/{UserName}/Projects/Movil/AwesomeProject/ios/build/generated/ios/FBReactNativeSpec/FBReactNativeSpec-generated.mm normal x86_64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```

### Version

0.70.5

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Memory: 1.00 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 18.11.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
    Watchman: 2022.10.31.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/{UserName}/.rvm/gems/ruby-2.7.5/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: Chipmunk 2021.2.1 Chipmunk 2021.2.1
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.5 => 0.70.5 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. `npx react-native init AwesomeProject`
2. `npx react-native start`
3. `npx react-native run-ios`

### Snack, code example, screenshot, or link to a repository

with a clean project this reproduce error.

**Comment by mellasystems** [comment]
I solved it changin `IPHONEOS_DEPLOYMENT_TARGET = 11.0;` to `IPHONEOS_DEPLOYMENT_TARGET = 12.4;` in file `ios/Pods/Pods.xcodeproj/project.pbxproj ` with VSCode.

(This step i feel can be sorted by updating your packages to the latest and re-run pod install/update but I had some packages that the latest update did not change it for me)
Under XCode top menu, Goto XCode->Preferences -> Locations -> Open Derived Data folder(By clicking the arrow button)
Finder will open Derived Data folder
Delete Derived Data Folder
Start Metro server using npm start or yarn start
In Xcode, perform Clean build using cmd+shift+k
In Xcode, run the application using cmd+r

**Comment by manojalwisnz** [comment]
Thanks it work

**Comment by fara0000** [comment]
what was flipperkit version?

**Comment by tcf01** [comment]
Thanks. It works for me too!! How do you find out this solution?

**Comment by mellasystems** [comment]
My Flipper versión is 0.174

**Comment by leobastiani** [comment]
Xcode 14.3 which is the latest at the time I'm writing this comment produces a very similar error. So if you are here and your Xcode is 14.3, consider reading this issue
https://github.com/facebook/react-native/issues/36739

**Comment by alroniks** [comment]
I've done as described [here](https://github.com/facebook/react-native/issues/36690#issuecomment-1493765601) and it solved my issue

**Comment by seheesf88** [comment]
I faced the same error, but I was not able to solve it with this [solution](https://github.com/facebook/react-native/issues/35246#issuecomment-1307723743)

is there any other solution?

```
The following build commands failed:
        CompileC /Users/myname/Library/Developer/Xcode/MyApp-eclfaotwufydlccnbbpdrgkgblbf/Build/Intermediates.noindex/MyApp.build/Debug-iphonesimulator/MyApp.build/Objects-normal/arm64/AppDelegate.o /Users/myname/Desktop/MyApp/ios/MyApp/AppDelegate.mm normal arm64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'MyApp' from project 'MyApp')
(1 failure)```
