### ISSUE TITLE
[Packager] Packager is bundling modules with conflicting names

### ISSUE THREAD

**Issue by ide** [facebook/react-native#3525]
When requiring an npm package that depends on `invariant` from npm (https://www.npmjs.com/package/invariant), the packager creates a bundle that contains `__d('invariant', ...)` twice because the npm package also declares `@providesModule invariant` in its docblock. Instead of defining two modules with the same name, the packager should namespace them differently. This is on master (pre 0.14-rc).

**Comment by martinbigio** [comment]
@ide this should be able to be avoided by blacklisting the node module invariant. On the new cli you should be able to define a file called `rn-cli.config.js` with a function named `getBlacklistedRE` which returns a regular expression for blacklisted modules. I'll close the issue but feel free to re-open it if you think this is not the right solution :)
