### ISSUE TITLE
The react-native run app suddenly failed to build this week

### ISSUE THREAD

**Issue by Wuhaojie1995** [facebook/react-native#35253]
### Description

When running react-native project this morning, the build could not be built, the dependencies all reported errors

### Version

0.59.10

### Output of `npx react-native info`

![image](https://user-images.githubusercontent.com/35724720/200505612-8c9fe631-5983-47c3-b787-765699fa9fc4.png)

### Steps to reproduce

Android sdudio failed to run react-native build android

### Snack, code example, screenshot, or link to a repository

![image](https://user-images.githubusercontent.com/35724720/200504955-ee2c4056-8bd2-44ff-a6cc-c4bb74b55767.png)

**Comment by Wuhaojie1995** [comment]
已解决

**Comment by cortinico** [comment]
Duplicates #35210
