### ISSUE TITLE
main.jsbundle does not exist. This must be a bug with

### ISSUE THREAD

**Issue by HamjethMisree** [facebook/react-native#35252]
### Description

Failed to construct transformer:  Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at stableHash (/Users/codelantic/Desktop/CL/spotonpay_mobile/node_modules/metro-cache/src/stableHash.js:19:8)
    at JsTransformer.getCacheKey (/Users/codelantic/Desktop/CL/spotonpay_mobile/node_modules/metro/src/JSTransformer/worker.js:478:7)
    at getTransformCacheKey (/Users/codelantic/Desktop/CL/spotonpay_mobile/node_modules/metro/src/DeltaBundler/Transformer/getTransformCacheKey.js:39:29)
    at new Transformer (/Users/codelantic/Desktop/CL/spotonpay_mobile/node_modules/metro/src/DeltaBundler/Transformer.js:147:28)
    at /Users/codelantic/Desktop/CL/spotonpay_mobile/node_modules/metro/src/Bundler.js:54:29 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
error Cannot read properties of undefined (reading 'transformFile'). Run CLI with --verbose flag for more details.
TypeError: Cannot read properties of undefined (reading 'transformFile')
    at /Users/codelantic/Desktop/CL/spotonpay_mobile/node_modules/metro/src/Bundler.js:91:34
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/codelantic/Desktop/CL/spotonpay_mobile/node_modules/metro/src/Bundler.js:14:24)
    at _next (/Users/codelantic/Desktop/CL/spotonpay_mobile/node_modules/metro/src/Bundler.js:34:9)
+ [[ false != true ]]
+ [[ ! -f /Users/codelantic/Library/Developer/Xcode/DerivedData/SpotonPay-ayrwuibscfwqvvfpjawgxchgstzr/Build/Intermediates.noindex/ArchiveIntermediates/SpotonPay/BuildProductsPath/Release-iphoneos/SpotonPay.app/main.jsbundle ]]
+ echo 'error: File /Users/codelantic/Library/Developer/Xcode/DerivedData/SpotonPay-ayrwuibscfwqvvfpjawgxchgstzr/Build/Intermediates.noindex/ArchiveIntermediates/SpotonPay/BuildProductsPath/Release-iphoneos/SpotonPay.app/main.jsbundle does not exist. This must be a bug with'
error: File /Users/codelantic/Library/Developer/Xcode/DerivedData/SpotonPay-ayrwuibscfwqvvfpjawgxchgstzr/Build/Intermediates.noindex/ArchiveIntermediates/SpotonPay/BuildProductsPath/Release-iphoneos/SpotonPay.app/main.jsbundle does not exist. This must be a bug with
+ echo 'React Native, please report it here: https://github.com/facebook/react-native/issues'
React Native, please report it here: https://github.com/facebook/react-native/issues
+ exit 2

! Need Help 

### Version

0.63.4

### Output of `npx react-native info`

System:
    OS: macOS 12.5.1
    CPU: (8) arm64 Apple M1
    Memory: 99.97 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.7.0 - ~/.nvm/versions/node/v18.7.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.7.0/bin/yarn
    npm: 8.18.0 - ~/.nvm/versions/node/v18.7.0/bin/npm
    Watchman: 2022.07.04.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16 - /usr/bin/javac
    Python: Not Found
  npmPackages:
    @react-native-community/cli: ^4.14.0 => 4.14.0 
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Hello, 

i get this issue when i try to archive my project for testFlight furthermore i have this issues "Failed to construct transformer:  Error: error:0308010C:digital envelope routines::unsupported"..

this is common in android and ios 

### Snack, code example, screenshot, or link to a repository

<img width="1440" alt="Screenshot 2022-11-08 at 11 23 28" src="https://user-images.githubusercontent.com/101192211/200485921-67be371c-94e3-4581-bf6a-5db1a87d8c5f.png">

**Comment by DanielT777** [comment]
Exact same probleme here with M1 Pro, Ventura

Already tried to : 
-> Upgrade / Downgrade NodeJS Version
-> Clear pods, yarn cache etc...
-> export NODE_OPTIONS=--openssl-legacy-provider but not really viable and not working on Xcode
-> ..... 

Tried all things about this problem, still not resolved :/

**Comment by AdeelTanveerM** [comment]
> Exact same probleme here with M1 Pro, Ventura
> 
> Already tried to : -> Upgrade / Downgrade NodeJS Version -> Clear pods, yarn cache etc... -> export NODE_OPTIONS=--openssl-legacy-provider but not really viable and not working on Xcode -> .....
> 
> Tried all things about this problem, still not resolved :/

Found any solution ? I am also facing the same issue.

**Comment by lchenfox** [comment]
+1

**Comment by AdeelTanveerM** [comment]
I have solved this issue by downgrading my Node version to 16.

**Comment by vishalhyperspace** [comment]
I have same problem after upgrading please help.

**Comment by HenriqueSuel** [comment]
+1

**Comment by DanielT777** [comment]
Fixed by adding an alias to my zsh and lauching it when i need to archive an project with this issue:

`vim ~/.zshrc`

```
clearwatch() {
 cd /usr/local/var/run/watchman/NAME_OF_YOUR_COMPUTER-state && rm log pid sock state
}
```

`source ~/.zshrc`

**Comment by alec-c4** [comment]
@DanielT777 what 'bout

```
clearwatch() {
 rm -rf /usr/local/var/run/watchman/*-state
}
```

**Comment by dulguuned** [comment]
![Screenshot 2023-04-28 at 19 17 15](https://user-images.githubusercontent.com/10085623/235133985-fce4f02c-4ae4-4c15-97db-aca68a96e770.png)
npm start works on vs code cli works but, npm run android opens terminal app of macos does not work for me.
<img width="1033" alt="Screenshot 2023-04-28 at 19 18 22" src="https://user-images.githubusercontent.com/10085623/235134198-fb8a8132-c080-4eff-9e2e-16f4cea3713f.png">

**Comment by pascal-maker** [comment]
downgrading to node 16.0 cleared the  failed to construct transformer problem.

**Comment by adriandiaz** [comment]
I've tried downgrading to 16.0 in addition to everything mentioned on this post, and what I could find on the internet. If anyone has found a solution not mentioned in this post, would greatly appreciate it

**Comment by Jamal-ReachFirst** [comment]
solution?

**Comment by maxweb4u** [comment]
I had the same problem, when upgrade my node version to the latest - 16.20.1. To fix this problem I've just downgraded to 16.13.0

**Comment by pascal-maker** [comment]
I found the solution I upgraded react native to latest version so 0.72 upgraded node js to 20.4 current latest and recrawled watchman I'm using a m1 MacBook Air .

**Comment by pbaral07** [comment]
Any solutions ?

**Comment by NSShentu** [comment]
Same here!
Now my workaround is add 'export NODE_OPTIONS=--openssl-legacy-provider' to Bundle react native code and image phase, and raise metro by 'yarn start' rather than Xcode run button.
Can someone give a better solution?

**Comment by Maddumage** [comment]
Is there any workable solution for this? I have tried all the solutions suggested above. But still getting the same error. :(

**Comment by Maddumage** [comment]
Finally, I was able to solve the problem by downgrading the Node version from 17 to 16 using nvm. Previously had an issue with user PREFIX for the node version. Able to run the project removing the old PREFIX and adding the new Node version PREFIX using nvm commands.
