### ISSUE TITLE
When the scrollview controls the scrollTo of another scrollview, it does not refresh in a timely manner. It seems that the delay is large

### ISSUE THREAD

**Issue by 1974892005** [facebook/react-native#35251]
### Description

When the scrollview controls the scrollTo of another scrollview, it does not refresh in a timely manner. It seems that the delay is large

### Version

0.69.6

### Output of `npx react-native info`

System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1155G7 @ 2.50GHz
    Memory: 6.24 GB / 15.79 GB
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.14.0 - ~\AppData\Roaming\npm\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Disabled
  IDEs:
    Android Studio: Not Found
    Visual Studio: Not Found
  Languages:
    Java: 11.0.16.1
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0
    react-native: 0.69.6 => 0.69.6
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

<ScrollView
     horizontal={true}
     bounces={false}
     scrollEventThrottle={16}
                onScroll={(event) => {
                    let offsetX = event.nativeEvent.contentOffset.x;
                    setScrollX(offsetX)
                     props.RightCoreRef.current.scrollTo({ x: offsetX, y: 0, animated: false })
                }}
            >

// table Container

</ScrollView>

 <ScrollView
horizontal={true}
showsHorizontalScrollIndicator={false}
ref={RightCoreRef}
bounces={false}
scrollEnabled={false}
>
// table title
</ScrollView>

### Snack, code example, screenshot, or link to a repository

![256ffd55ee364ed7addae564a6af34ae-Trim](https://user-images.githubusercontent.com/25133430/200470369-b7f841a8-8d27-4b9d-8cad-5e37f4fe40ef.gif)

**Comment by Sanath91009** [comment]
Yeah facing the same issue. Just and idea , How about having all components in 1 scroll view ?

**Comment by 1974892005** [comment]
> 

Fixed header and fixed first column cannot be used together

**Comment by Sanath91009** [comment]
Please let me know if you overcame this problem @1974892005 .
