### ISSUE TITLE
Instantly crash on Android

### ISSUE THREAD

**Issue by heekyu-pu** [facebook/react-native#35250]
### Description

My customers get an instant crash on Android
100+ incidents suddenly occurred (I received quick notification email from firebase)

crash stack:
`
Fatal Exception: java.lang.UnsatisfiedLinkError
couldn't find DSO to load: libjscexecutor.so SoSource 0: com.facebook.soloader.DirectorySoSource[root = /data/app/net.manta.comid-ZCnKBRhnHffzHdbVLUMKTA==/lib/arm flags = 0] SoSource 1: com.facebook.soloader.DirectApkSoSource[root = /data/app/net.manta.comid-ZCnKBRhnHffzHdbVLUMKTA==/base.apk!/lib/armeabi-v7a] SoSource 2: com.facebook.soloader.DirectorySoSource[root = /vendor/lib flags = 2] SoSource 3: com.facebook.soloader.DirectorySoSource[root = /system/lib flags = 2] Native lib dir: /data/app/net.manta.comid-ZCnKBRhnHffzHdbVLUMKTA==/lib/arm result: 0
`

`couldn't find DSO to load:`
This error occurs every day
But this is the first time there have been so many incidents at once.

The time was **2022-11-07 18:50(UTC)**
What happened then?

### Version

0.68.1

### Output of `npx react-native info`

```
System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Pro
    Memory: 387.58 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.0/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.17.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 14.0/14A309 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.1 => 0.68.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

```

### Steps to reproduce

Occurs only once and cannot be reproduced

### Snack, code example, screenshot, or link to a repository

<img width="1055" alt="스크린샷 2022-11-08 오전 10 01 39" src="https://user-images.githubusercontent.com/67251827/200448383-d9b7b954-f6bd-4de2-8c08-68439b2c28be.png">

**Comment by NavidAsadi** [comment]
Me too...

**Comment by kennCK** [comment]
Me too

**Comment by cortinico** [comment]
> The time was **2022-11-07 18:50(UTC)**
> What happened then?

Related to #35210 which is now closed/resolved. I'm closing here.
