### ISSUE TITLE
Archive in Xcode is getting failed with error: error node_modules/readable-stream/lib/ours/errors.js: Unexpected token name «n», expected punc «,» in file node_modules/readable-stream/lib/ours/errors.js at 296:28.

### ISSUE THREAD

**Issue by patriksharma** [facebook/react-native#35268]
### Description

After Installing the node_modules I was stuck in a wired situation where the Application is building fine in the device and simulator or we can say the app works fine in debug mode. when I try to produce an archive for the release build app is giving me a strange error.

I checked earlier issues where it was mentioned to update babel and update the config.js file but nothing works for me and I'm still getting this error when I try to produce an archive in Xcode

```
error node_modules/readable-stream/lib/ours/errors.js: Unexpected token name «n», expected punc «,» in file node_modules/readable-stream/lib/ours/errors.js at 296:28.
Error: Unexpected token name «n», expected punc «,» in file node_modules/readable-stream/lib/ours/errors.js at 296:28
    at minifyCode (/Users/patriksharma/laina-react-native-app/node_modules/metro-transform-worker/src/index.js:99:13)
    at transformJS (/Users/patriksharma/laina-react-native-app/node_modules/metro-transform-worker/src/index.js:317:28)
    at transformJSWithBabel (/Users/patriksharma/laina-react-native-app/node_modules/metro-transform-worker/src/index.js:408:16)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.transform (/Users/patriksharma/laina-react-native-app/node_modules/metro-transform-worker/src/index.js:569:12)
info Run CLI with --verbose flag for more details.
```

### Version

0.66.3

### Output of `npx react-native info`

```
System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1
    Memory: 130.80 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.11 - /opt/homebrew/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
    Watchman: 2022.09.05.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7935034
    Xcode: 14.0/14A309 - /usr/bin/xcodebuild
  Languages:
    Java: javac 19 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: ^6.3.1 => 6.4.0 
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.3 => 0.66.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

Open IOS folder.
Click on XXXX.xcworkspace
Choose the Team and Release configuration
Click on Archive 
<img width="1440" alt="Screenshot 2022-11-09 at 10 57 19 AM" src="https://user-images.githubusercontent.com/383524/200746346-b071605b-2c65-4500-aefe-e82c93942963.png">

### Snack, code example, screenshot, or link to a repository

<img width="1440" alt="Screenshot 2022-11-09 at 10 57 19 AM" src="https://user-images.githubusercontent.com/383524/200746483-c3031657-face-4c17-a214-69cc98ed4880.png">

**Comment by cnixbtc** [comment]
@patriksharma I'm having the same issue! Did you end up solving it? Any insights would be appreciated.

**Comment by cnixbtc** [comment]
Thanks for the reply @patriksharma!

I ended up switching out the minifcation lib metro uses which resolved the issue for me:

- `npm install --save-dev metro-minify-terser`.
- Added `minifierPath: 'metro-minify-terser',` to `metro.config.js`'s `transformer` settings.
