### ISSUE TITLE
[Android] App crash cause by KeyboardAvoidingView after upgrade from 0.64.3 to 0.69.6

### ISSUE THREAD

**Issue by tanthuann** [facebook/react-native#35278]
### Description

I've upgraded the app from 0.64.3 to 0.69.6
Expo: 44 -> 46.

Device not working:
Name: Galaxy S10+
One UI: 4.1
Android: 12

Device working:
Name: Nokia C30
Go Edition
Android: 11

No logs on device not working.

This is my package.json: 
```
"dependencies": {
    "@cucumber/cucumber": "^8.5.1",
    "@expo/vector-icons": "^13.0.0",
    "@react-native-async-storage/async-storage": "~1.17.3",
    "@react-navigation/bottom-tabs": "^6.3.1",
    "@react-navigation/material-top-tabs": "^6.2.2",
    "@react-navigation/native": "^6.0.8",
    "@react-navigation/native-stack": "^6.5.0",
    "detox": "^19.10.0",
    "expo": "^46.0.0",
    "expo-app-loading": "~2.1.0",
    "expo-barcode-scanner": "~11.4.0",
    "expo-camera": "~12.3.0",
    "expo-file-system": "~14.1.0",
    "expo-firebase-recaptcha": "~2.3.0",
    "expo-font": "~10.2.0",
    "expo-linking": "~3.2.2",
    "expo-notifications": "~0.16.1",
    "expo-splash-screen": "~0.16.2",
    "expo-status-bar": "~1.4.0",
    "expo-web-browser": "~11.0.0",
    "firebase": "9.7.0",
    "formik": "^2.2.9",
    "moment": "^2.29.3",
    "react": "18.0.0",
    "react-native": "0.69.6",
    "react-native-animatable": "^1.3.3",
    "react-native-confirmation-code-field": "^7.3.0",
    "react-native-elements": "^3.4.2",
    "react-native-markdown-display": "^7.0.0-alpha.2",
    "react-native-pager-view": "5.4.24",
    "react-native-root-siblings": "^4.1.1",
    "react-native-root-toast": "^3.4.0",
    "react-native-safe-area-context": "4.3.1",
    "react-native-screens": "~3.15.0",
    "react-native-tab-view": "^3.1.1",
    "react-native-webview": "11.23.0",
    "react-number-format": "^4.9.3",
    "shorthash": "^0.0.2",
    "yup": "^0.32.11"
  },
  "devDependencies": {
    "@babel/core": "^7.18.6",
    "@babel/plugin-proposal-optional-chaining": "^7.17.12",
    "@babel/preset-env": "^7.16.11",
    "@expo/webpack-config": "^0.17.0",
    "@react-native-community/eslint-config": "^3.0.1",
    "@testing-library/react-native": "^9.0.0",
    "babel-jest": "^27.5.1",
    "eslint": "^8.9.0",
    "eslint-config-airbnb": "^19.0.4",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-import": "^2.25.4",
    "eslint-plugin-jsx-a11y": "^6.5.1",
    "eslint-plugin-react": "^7.28.0",
    "eslint-plugin-react-native": "^4.0.0",
    "expo-cli": "^6.0.8",
    "husky": "4",
    "jest": "^26.6.3",
    "jest-circus": "^27.5.1",
    "jest-expo": "^46.0.0",
    "lint-staged": "^12.3.4",
    "prettier": "^2.5.1"
  },
```

### Version

0.69.3

### Output of `npx react-native info`

System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 4.09 GB / 15.73 GB
  Binaries:
    Node: 14.20.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.17 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: Not Found
  Languages:
    Java: 18.0.2 - /c/Program Files/Common Files/Oracle/Java/javapath/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0
    react-native: 0.69.6 => 0.69.6
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

My device use:

One UI: 4.1
Android: 12

### Steps to reproduce

Updated my app from expo sdk 44 to 46.

### Snack, code example, screenshot, or link to a repository

My code: 

```
 <KeyboardAvoidingView
    behavior="height"
    keyboardVerticalOffset={0}
    style={{ flex: 1 }}
  >
    <TouchableWithoutFeedback onPress={Keyboard.dismiss} accessible={false}>
      {children}
    </TouchableWithoutFeedback>
  </KeyboardAvoidingView>
```

I have debugged my code also packages `node_modules\react-native\Libraries\Components\Keyboard\KeyboardAvoidingView.js` to figure out the problem. So when i comment out the following code below:

![image](https://user-images.githubusercontent.com/44896550/200812178-730e1bbb-c00c-41f1-a504-58af0db56bb9.png)

After that my app working back again! I also log that line but receive nothing!!!! 😵‍💫 Help me!!!!!

**Comment by echolove38** [comment]
how to upgrade from 64 to 69

**Comment by tanthuan0809** [comment]
> how to upgrade from 64 to 69

I used command: `expo upgrade 43`
