### ISSUE TITLE
React Native project not running 

### ISSUE THREAD

**Issue by Saravananb123** [facebook/react-native#35275]
### Description

We have downloaded & installed RN Version 0.61.3 . Its working fine last week.Last two days to still not working.we have run the command ( npx react-native run-android ) . But its Not working (Could not resolve all files for configuration ':app:debugRuntimeClasspath'.) .Please suggest ..

   below software vesions we have used ..

         React Native Version - 0.61.5

      Node - v14.17.3

    Android Studio - 2021.3.1

  

   

### Version

0.61.3

### Output of `npx react-native info`

warn The following packages use deprecated "rnpm" config that will stop working from next release:
  - react-native-orientation: https://github.com/yamill/react-native-orientation#readme
Please notify their maintainers about it. You can find more details at https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide.
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.19043
    CPU: (6) x64 Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
    Memory: 753.25 MB / 7.95 GB
  Binaries:
    Node: 14.17.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 23, 28, 29, 30
      Build Tools: 28.0.3, 29.0.0, 29.0.1, 29.0.2, 29.0.3, 30.0.2, 30.0.3
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: AI-213.7172.25.2113.9123335
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: ^0.61.5 => 0.61.5
  npmGlobalPackages:
    react-native-cli: 2.0.1

### Steps to reproduce

npx react-native run-android to gave in command prompt,This Error (Could not resolve all files for configuration ':app:debugRuntimeClasspath'.) occured.

### Snack, code example, screenshot, or link to a repository

![image](https://user-images.githubusercontent.com/110403069/200790620-d3e35d02-e3ce-406b-bab7-cba388f12504.png)

**Comment by cortinico** [comment]
Closing as a byproduct of #35210
This should now be resolved
