### ISSUE TITLE
.gitignore ignores node_modules folder, but causes problem when deleting Libraries

### ISSUE THREAD

**Issue by kevinzzz007** [facebook/react-native#3528]
Currently `.gitignore` ignores the `node_modules` folder, this caused problem for me when I deleted `React.xcodeproj` and tried to get it back.  What happens is that the `.xcodeproj` file is gone and you can't see it in the `Libraries` folder in Xcode, build fails, but when you go back to the branch before you deleted this library, you can see `React.xcodeproj` in red letters in Xcode, this seems to imply that Xcode can't find it, but build succeeds...

Of course, after you deleted `React.xcodeproj`, the file is gone in the `node_modules` folder for good, changing branch won't get it back

After you delete everything in `Libraries`
<img width="300" alt="screen shot 2015-10-20 at 12 33 20 am" src="https://cloud.githubusercontent.com/assets/5249746/10597991/7fd10e1c-76c2-11e5-8345-c5018327d603.png">

Going back to the older branch, you see the following:
<img width="262" alt="screen shot 2015-10-20 at 12 35 25 am" src="https://cloud.githubusercontent.com/assets/5249746/10597995/9536e2d6-76c2-11e5-9d8e-bd683d5d4c3c.png">

Would it be a good idea to not ignore `node_modules` in the .gitignore file?  I am not completely sure about the upside and downside of this decision, so was just curious...

Thanks!

**Comment by satya164** [comment]
@kevindeleon not ignoring `node_modules` means that all the changes in that directory (which may be massive) and the code not written by you go to your version control. Also, some node modules are compiled on the system, and the binaries won't be cross platform.

**Comment by kevinzzz007** [comment]
@satya164 thanks!  That makes sense, I found a resolution which is delete the `node_modules` folder, type `npm install` into command line in the React Native project folder, then the `.xcodeproj` files will show up again, I just have to remove all the old references one by one and add in the new `.xcodeproj` files one by one
