### ISSUE TITLE
0.12 version builds are being rejected by Apple

### ISSUE THREAD

**Issue by alvinwoon** [facebook/react-native#3529]
Hi. My latest build has been rejected by Apple twice for crash reason. It works fine on simulator and device running latest version of iOS. 

> We were unable to review your app, as it crashed on launch on the following device(s): 
> iPhone 5S running iOS 9.1- iPhone 6 running iOS 9.0- iPhone 6 Plus running iOS 9.1- iPod Touch Fifth Generation running iOS 9.1- iPod Touch Sixth Generation running iOS 9.0

Here's the crash report they attached:

https://dl.dropboxusercontent.com/u/2533639/temp..vhfjjedl.txt
https://dl.dropboxusercontent.com/u/2533639/temp..cbpopqqq%20%281%29.txt

More info:
React native v 0.12
Submission step - react-native bundle --minify / product scheme change to release / archive / submit

CCing: @martinbigio

**Comment by nicklockwood** [comment]
Looking at the second crash report file that you've linked, I see the following:

`'Message: undefined is not an object (evaluating 'RCTScrollViewConsts.KeyboardDismiss...`

`RCTScrollViewConsts.KeyboardDismiss` was removed from the ScrollView.js several versions ago, which suggests to me that you may have a very old version of the React Native JS cached on your system somewhere, and unfortunately the app you submitted to Apple included that version of the JS, which probably isn't compatible with the native iOS release that you were using.

**Comment by chirag04** [comment]
@alvinwoon ``find . -name 'react-native' -print`` to see if you have multiple copies of react-native in node_modules.

**Comment by alvinwoon** [comment]
so I deleted node_modules and run npm install and this is what shows up on ```find```
```
./android/app/build/intermediates/exploded-aar/com.facebook.react/react-native
./node_modules/react-native
./node_modules/react-native/Libraries/react-native
```

Running a full repo search for 'KeyboardDismiss' returns
https://gist.github.com/alvinwoon/1c4bae4568de6660d1ee

I wish there's a way for me to reproduce this on my device or simulator. Right now it's pretty much trial and error. Submit -> pray -> rejected -> sad

**Comment by ide** [comment]
You can run release builds on your device or simulator. That should be enough to test the "production" build of RN. (In the general case building with RELEASE is *not* the same as production due to how entitlements work -- you need to export an adhoc signed IPA or something. it's not fun.)  Google around for how to test iOS apps before submitting.

**Comment by alvinwoon** [comment]
I did test the release build on simulator and on device and they ran fine. I will report back with the latest submission. :+1:

**Comment by chirag04** [comment]
Not sure if you are already doing this but we submit build for beta review first which only takes one or two days. enable testflight and then test from testflight. Can help save time in review.

**Comment by jaygarcia** [comment]
We followed the same process as @chirag04, testing via TestFlight on physical devices before production submission.  We found that it saved tons of time from rejections (non-RN related)

**Comment by alvinwoon** [comment]
It worked in testflight as well. 

Update: Finally approved after 11 days 'in review'. 
Lesson: When nothing else works, delete node_modules and reinstall everything.
