### ISSUE TITLE
Can't install specific version with TypeScript

### ISSUE THREAD

**Issue by jorgtz** [facebook/react-native#35291]
### Description

I want to use v0.68.5 with typescript but it install latest ReactNative version (0.70.5).

This is the command I run
npx react-native init MyApp --template react-native-template-typescript --version 0.68.5

### Version

0.68.5

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 13.0
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
    Memory: 752.56 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.10.0 - ~/.nvm/versions/node/v16.10.0/bin/node
    Yarn: Not Found
    npm: 7.24.0 - ~/.nvm/versions/node/v16.10.0/bin/npm
    Watchman: 2022.10.24.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK:
      API Levels: 28, 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 33.0.0
      System Images: android-28 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7351085
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.5 => 0.70.5
    react-native-macos: Not Found
  npmGlobalPackages:

### Steps to reproduce

npx react-native init MyApp --template react-native-template-typescript --version 0.68.5

### Snack, code example, screenshot, or link to a repository

<img width="574" alt="image" src="https://user-images.githubusercontent.com/66479719/200914503-40b09218-4cf2-4870-9029-f7ba6b68b660.png">
<img width="438" alt="image" src="https://user-images.githubusercontent.com/66479719/200914578-d86e93c0-169f-4980-a988-a6dc1382ad9c.png">

**Comment by cortinico** [comment]
That's a "known bug" of the CLI
It's also already fixed: https://github.com/react-native-community/cli/pull/1736
