### ISSUE TITLE
Build Error 

### ISSUE THREAD

**Issue by jijojohnweb** [facebook/react-native#35297]
### Description

When I try to build it get an error 

I have followed the react native setup guide correctly
but I don't know why I can't build

I appreciate any help you can provide.

### Version

0.70.0

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 388.81 MB / 7.70 GB
  Binaries:
    Node: 16.17.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.1 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: AI-213.7172.25.2113.9123335
    Visual Studio: Not Found
  Languages:
    Java: 11.0.16.1
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 16.11.0 
    react-native: 0.70.0 => 0.62.1 
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, {Component} from 'react';
import {StyleSheet, View} from 'react-native';

import VlcPlayer, { SURFACE_16_9 } from 'react-native-vlc-player';

export default class App extends Component {
  vlcplayer = React.createRef();

  componentDidMount() {
    console.log(this.vlcplayer);
  }

  render() {
    return (
      <View style={[styles.container]}>
        <VlcPlayer
          ref={this.vlcplayer}
          style={{
            width: 300,
            height: 200,
          }}
          speed={2}
          currentSize={SURFACE_16_9}
          paused={false}
          autoplay={true}
          source={{
            uri: 'https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/720/Big_Buck_Bunny_720_10s_10MB.mp4',
            autoplay: true,
            initOptions: ['--codec=avcodec'],
          }}
        />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    
    alignItems: 'center',
    backgroundColor: 'grey',
  },
});

### Snack, code example, screenshot, or link to a repository

I'm using this npm package 
![image](https://user-images.githubusercontent.com/104441631/200988104-d30f5fde-726e-450b-9e6f-13be37d664ec.png)

**Comment by NaitikDartexon** [comment]
can you check this one may be that one solution also works for you
https://github.com/facebook/react-native/issues/35286

**Comment by jijojohnweb** [comment]
@NaitikDartexon I had try what you say but it gives an error 



FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\Jijo\Desktop\react-native-vlc-player\example\android\build.gradle' line: 25

* What went wrong:
A problem occurred evaluating root project 'example'.
> Could not find method exclusiveContent() for arguments [build_5nlonjnegyd2r641vux26i1b5$_run_closure1$_closure2$_closure3@37622021] on repository container of type org.gradle.api.internal.artifacts.dsl.DefaultRepositoryHandler.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevSeles\@react-native-community\cli-platform-android\node_modules\execa\index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (C:\Users\Jijo\Desktop\react-native-vlc-player\example\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:109:5)
    at async Command.handleAction (C:\Users\Jijo\Desktop\react-native-vlc-player\example\node_modules\@react-native-community\cli\build\index.js:142:9)
info Run CLI with --verbose flag for more details.PS C:\Users\Jijo\Desktop\react-native-vlc-player\example>

> can you check this one may be that one solution also works for you #35286

**Comment by NaitikDartexon** [comment]
> d try what you say but it gives an error
> 
> FAILURE: Build failed with an exception.

it's look like a gradlew issue can you try to downgrade the react native version once 
in my case my react native version is 0.67

**Comment by cortinico** [comment]
> react-native: 0.70.0 => 0.62.1

I suspect you have a global version of React Native 0.62 installed.

> Build file 'C:\Users\Jijo\Desktop\react-native-vlc-player\example\android\build.gradle' line: 25

This is the indication that the issue you're having is on the `react-native-vlc-player` library and not react native. Please opne an issue for them
