### ISSUE TITLE
When keyboard covers cursor, cursor do not always move up above the keyboard

### ISSUE THREAD

**Issue by i-in-range** [facebook/react-native#35307]
### Description

I have a hughe text field that overflows screen size. I tried to make it with just `TextInput`, but when I overscroll it to the top or to the bottom, app manages this like just touch event and pops up keyboard when it actually do not needed. Sometimes even usual scrolling becomes considered as text selection. This is undesirable behaviour.

So, I put `TextInput` inside `ScrollView` and that inconveniences goes away, but becomes a new one - **the subject of this report**.

When I do want to edit my text at the bottom, I should touch some place there. If I touch some word (only letters characters), the keyboard pops up and text scrolls up concurrently to help me to see the cursor above the keyboard. With words it behaves as I want (screenshot below).

![1667352994339-2](https://user-images.githubusercontent.com/80415337/201097264-1d294ea6-2927-430a-9967-83112cfe23f9.jpg)

**The problem appears here>>** But when I point some **number, alpha-numeric, or blank row**, the keyboard appears, **but the text doesn't jump up**. So I can't see the text around the cursor and must scroll down manually (photo below: see the cursor leaved upon keyboard area).

![1667352994365-2](https://user-images.githubusercontent.com/80415337/201097287-9e28c902-e8d2-4edb-b2e6-21ae512ee5d9.jpg)

Why does the content of `TextInput` affect the behavior of the application?

Environment: React Native 69.6, Expo 46, Redmi Note 5 (MIUI 12.0.2, Android  9 PKQ1.180904.001), Android Studio (Pixel 4 API 30, Android 11.0)

### Version

0.69.6

### Output of `npx react-native info`

System:
    OS: Windows 10 10.0.19043
    CPU: (4) x64 Intel(R) Core(TM) i3-7020U CPU @ 2.30GHz
    Memory: 581.96 MB / 7.92 GB
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 9.1.1 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: Not Found
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0
    react-native: 0.69.6 => 0.69.6
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

In my example on Snack (find link below) just open screen on your device and at the bottom of the screen try to touch:

- **word without numbers** (cursor should jump up behind the keyboard)
- **numbers or empty row** (keyboard should cover cursor)

### Snack, code example, screenshot, or link to a repository

[Snack example](https://snack.expo.dev/nl7L2Fn-R)

**Comment by kr-yeon** [comment]
I have the same problem. I have a flexView in android not shrinking to fit the height of the keyboard. Can you confirm that you are too?
@i-in-range

**Comment by ShepelE** [comment]
please, try to set android:windowSoftInputMode="adjustResize" or switch it dynamically with react-native-android-keyboard-adjust simple module. It helped for me
https://developer.android.com/develop/ui/views/touch-and-input/keyboard-input/visibility?authuser=1
