### ISSUE TITLE
Native modules return empty object {} 

### ISSUE THREAD

**Issue by TusharGameskraft** [facebook/react-native#35302]
### Description

import { NativeModules } from 'react-native';
const { MyModule } = NativeModules;
my MyModule is null and native modules return empty object it works in previous versions. This works in previous react native versions

### Version

0.70.5

### Output of `npx react-native info`

NA

### Steps to reproduce

- use npx react-native init AwesomeProject to create a new project
- follow this doc [native-modules-ios](https://reactnative.dev/docs/native-modules-ios) to try to add a native module
- NativeModules always returns {}

### Snack, code example, screenshot, or link to a repository

NA

**Comment by silvabacc** [comment]
which version of react-native did this work for you? Currently I have a new react-native project and facing the same issue on android. Followed the guide on `0.71.3`, but would like to start again with a working version

**Comment by silvabacc** [comment]
Turns out... After looking into other [issues](https://github.com/facebook/react-native/issues/26813), it's possible that the object may appear as empty but it isn't the case. My NativeModule appears to be working
