### ISSUE TITLE
[Upgrade 0.66.5 - 0.71.0-rc0]: Caused by: groovy.lang.MissingPropertyException: Could not get unknown property 'composeSourceMapsPath' for extension 'react' of type com.facebook.react.ReactExtension.

### ISSUE THREAD

**Issue by bytewiz** [facebook/react-native#35301]
### New Version

0.71.0-rc.0

### Old Version

0.66.5

### Build Target(s)

Android build in debug flavour (custom with .env loaded)

### Output of `react-native info`

System:
    OS: macOS 13.0
    CPU: (10) arm64 Apple M1 Max
    Memory: 145.78 MB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.15 - ~/.nvm/versions/node/v16.16.0/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.4 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: ^0.71.0-rc.0 => 0.71.0-rc.0
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Issue and Reproduction Steps

Following the upgrade guide https://react-native-community.github.io/upgrade-helper/?from=0.66.5&to=0.71.0-rc.0

I managed to make build work on iOS for all my build flavours (I have multiple whitelabel apps too) 

So the issue only seems to exist for Android while running and indexing the build. Which exists with the following error:

```
Caused by: groovy.lang.MissingPropertyException: Could not get unknown property 'composeSourceMapsPath' for extension 'react' of type com.facebook.react.ReactExtension.
```

**Comment by cortinico** [comment]
Thank you very much for testing this, it's really valuable for us.

> So the issue only seems to exist for Android while running and indexing the build. Which exists with the following error:

Could you share your `build.gradle`?
Are you specifying a custom `composeSourceMapsPath`? If so, can I ask you what's your use case?

**Comment by cortinico** [comment]
Closing as the user is unresponsive
