### ISSUE TITLE
0.59.10 run android build failed this week

### ISSUE THREAD

**Issue by ducorizon** [facebook/react-native#35328]
### Description

It worked normally before, but build failed in recent days,when I run **npm run android**。
And all my projects build failed recent days, they have the same error。but they worked normally before,and I didn't change anything。

### Version

0.59.10

### Output of `npx react-native info`

`React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (6) x64 QEMU Virtual CPU version 2.5+
      Memory: 3.74 GB / 12.00 GB
    Binaries:
      Node: 14.17.5 - D:\nodejs\node.EXE
      npm: 6.14.14 - D:\nodejs\npm.CMD`

### Steps to reproduce

npm run android

**Comment by xyang0917** [comment]
I had the same problem, and the rn version I used was 0.57.8

**Comment by zpd106** [comment]
look this #35210

**Comment by ducorizon** [comment]
#35210 is answer

**Comment by cortinico** [comment]
Closing as https://github.com/facebook/react-native/issues/35210 is over
