### ISSUE TITLE
npx react-native run-ios runs forever

### ISSUE THREAD

**Issue by GSManganneau** [facebook/react-native#35325]
### Description

I created a react-native project using
`npx react-native init myProject --template react-native-template-typescript`

Everything works fine, the project is created with no errors

Then I run Metro server, still no errors.

But, when it comes to run the project for ios with this command 

`npx react-native run-ios`

The build runs forever and I am not even able to open the project on Xcode (load forever and crashes Xcode)

### Version

0.70.5

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 13.0.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 112.67 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.20.0 - ~/.nvm/versions/node/v14.20.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 6.14.17 - ~/.nvm/versions/node/v14.20.0/bin/npm
    Watchman: 2022.11.07.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.5 => 0.70.5
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

`npx react-native init myProject --template react-native-template-typescript`
`cd myProject && npx react-native run-ios`

### Snack, code example, screenshot, or link to a repository

Since I didn't change any code, I think it's irrelevant to provide a snack.
The issue appears with the code generated by `npx react-native init myProject --template react-native-template-typescript`

**Comment by cortinico** [comment]
> The build runs forever and I am not even able to open the project on Xcode (load forever and crashes Xcode)

Could you copy the build log you see so far?

**Comment by cortinico** [comment]
Closing as the log was not provided. Feel free to reopen or comment if you have further context to share
