### ISSUE TITLE
React Native application get slow after enabling Hermes Engine

### ISSUE THREAD

**Issue by CHYHUI** [facebook/react-native#35322]
### Description

[React Native application get slow after enabling Hermes Engine](https://stackoverflow.com/questions/74418338/react-native-application-get-slow-after-enabling-hermes-engine)

### Version

0.69.7

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 3.72 GB / 15.80 GB
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.5.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: Not Found
  Languages:
    Java: 11.0.16 - C:\Program Files\Eclipse Adoptium\jdk-11.0.16.8-hotspot\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0
    react-native: ^0.69.4 => 0.69.7
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Create application using official demo step by step.
Change
`project.ext.react = [
    enableHermes: false,  // clean and rebuild if changing
    hermesCommand: '../../node_modules/react-native/sdks/hermesc/%OS-BIN%/hermesc',
]` 
into 
`project.ext.react = [
    enableHermes: true,  // clean and rebuild if changing
    hermesCommand: '../../node_modules/react-native/sdks/hermesc/%OS-BIN%/hermesc',
]`

The application became very slow. The UI showed slowly.

### Snack, code example, screenshot, or link to a repository

After enabling Hermes: https://cdn.kapwing.com/final_63706fb6f238a300250643ab_920899.gif

Before enabling Hermes: https://cdn.kapwing.com/final_63706eadda957601151f3c33_364532.gif

**Comment by cortinico** [comment]
I can't see the GIFs you sent @CHYHUI
Can you re-upload them?

**Comment by CHYHUI** [comment]
![Before enabling Hermes](https://user-images.githubusercontent.com/33077215/204082943-d6fbc559-ebf2-4af0-9dd8-03491128b62c.gif)
![After enabling Hermes](https://user-images.githubusercontent.com/33077215/204082949-49955f06-cb4d-4856-813f-4226a5fc312b.GIF)
@cortinico Thanks for replying. Those are GIFs.

**Comment by cortinico** [comment]
Are you testing this in debug or release @CHYHUI ?

**Comment by CHYHUI** [comment]
> Are you testing this in debug or release @CHYHUI ?

```
@Override
public boolean getUseDeveloperSupport() {
      return Boolean.parseBoolean("false");
}
```

Is it meaning in release?
