### ISSUE TITLE
[iOS] overflow:hidden doesn't work correctly with events

### ISSUE THREAD

**Issue by gre** [facebook/react-native#3533]
An **absolute** element inside a **relative+overflow:hidden** container only visually hide the element outside of container, but does not prevent that absolute element to catch events outside of this container.

**Showcase:**
https://rnplay.org/apps/1TT9oA

<img width="251" alt="screen shot 2015-10-20 at 10 58 05" src="https://cloud.githubusercontent.com/assets/211411/10602588/8f4c7974-7719-11e5-87d2-9ec93542ecc4.png">

- tap on the RED area:
  - if you click on the y higher part of it, it highlight correctly
  - if you click on the y lower part of it, it doesn't work

BTW here is the same demo without `overflow: "hidden"` that helps to understand why the click don't go through:

<img width="243" alt="screen shot 2015-10-20 at 10 58 18" src="https://cloud.githubusercontent.com/assets/211411/10602604/a5b5260c-7719-11e5-9035-8e7812cef11d.png">

**One workaround:**
`<ScrollView scrollEnabled={false} ...` for the container. The ScrollView seems to correctly prevent outside events.

**Comment by jaygarcia** [comment]
Thanks @gre!

**Comment by gre** [comment]
@jaygarcia you're welcome.

the workaround is ugly and I hope this can be fixed soon.
It does not happen in Android but only in iOS.

**Comment by jaygarcia** [comment]
@gre , one thing that came to mind was modifying ListView, so that it actually removes items from the top of the view after it's scrolled out of the boundaries.  After a quick 5 minute review, i saw nothing that performs this action.

Can someone help me clarify this?

**Comment by jaygarcia** [comment]
The workaround doesn't seem to accomplish anything for me. 

I get a shit load of :
```ExceptionsManager.js:86 Warning: ScrollView doesn't take rejection well - scrolls anyway```

While recognizing that Listview extends beyond the height of the container's height. 
![listview1](https://cloud.githubusercontent.com/assets/180031/10698718/7c56bd3e-7980-11e5-928f-b76b05cfbe72.gif)

**Comment by browniefed** [comment]
Did this ever get fixed? It appears it may have through a series of PRs but I can't tell.

**Comment by gre** [comment]
I think it did

**Comment by gre** [comment]
yes, it is fixed. The rnplay example does not longer show the bug. It also doesn't repro in my app.

**Comment by browniefed** [comment]
@facebook-github-bot answered
