### ISSUE TITLE
App component is re-rendered after navigating away and back again

### ISSUE THREAD

**Issue by kdowswell** [facebook/react-native#35331]
## Summary
App is re-rendering after turning off screen or navigating to another app and back again. I reproduced this issue with the basic install of a fresh React Native app on IOS device. This issue was not present on v0.63.3.

## Description
To me this is a bug causing the app to re-render after turning off the screen as shown in repo steps or if navigating away to home screen or another app and back again.

This causes the app component context to reset and I lose any values I might have in a user session via the useContext hook.

I confirmed that doing the above steps but with version 0.63.3 does not do this re-rendering. I was upgrading an app I had been working on and relied on the context for prop sharing in some long lived component sessions and this is causing me a lot of issues.

### Version

0.70.5

### Output of `npx react-native info`

System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Pro
    Memory: 86.05 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.3.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.11.0 - /opt/homebrew/bin/npm
    Watchman: 2022.06.06.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK:
      API Levels: 30, 31, 32
      Build Tools: 29.0.0, 29.0.1, 29.0.2, 29.0.3, 30.0.0, 30.0.1, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0
      System Images: android-31 | ARM 64 v8a, android-31 | Google APIs ARM 64 v8a, android-31 | Google APIs Intel x86 Atom_64, android-31 | Google Play ARM 64 v8a, android-31 | Google Play Intel x86 Atom_64, android-32 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

Note: I'm having issues with my M1 mac and iOS simulator so I debug via my iPhone.

## Issue Repo Steps
- `npx react-native init AwesomeTSProject --template react-native-template-typescript`
- `cd AwesomeTSProject/ios`
- `pod install`
- Open App.tsx
- Add log statement to app
```
const App = () => {
  const isDarkMode = useColorScheme() === 'dark';

  const backgroundStyle = {
    backgroundColor: isDarkMode ? Colors.darker : Colors.lighter,
  };

  console.error('App Loaded');
...
```
- `cd ..`
- `npm start`
- Open ios folder in xcode
- set signing certificates
- debug to device / simulator
- allow app to build and run on phone
- observe debug error popup and close it
- hit power button on phone / simulator
- hit power button again to unlock phone and view app again
- observe debug error popup

## Works Correctly on v0.63.3
- `npx react-native init AwesomeProject --version 0.63.3`
-  NOTE: due to my iphone version I needed to disable flipper and set the minimum ios version to 11 instead of 10 that is defaulted on this version.
- `cd AwesomeProject/ios`
- `pod install`
- Open App.tsx
- Add log statement to app
- `cd ..`
- `npm start`
- Open ios folder in xcode
- set signing certificates
- debug to device / simulator
- allow app to build and run on phone
- observe debug error popup and close it
- hit power button on phone / simulator
- hit power button again to unlock phone and view app again
- debug popup does not appear. App is not re-rendered

### Snack, code example, screenshot, or link to a repository

```
const App = () => {
  const isDarkMode = useColorScheme() === 'dark';

  const backgroundStyle = {
    backgroundColor: isDarkMode ? Colors.darker : Colors.lighter,
  };

  console.error('App Loaded');
...

**Comment by lucianobracco-geojam** [comment]
Same here

**Comment by lucianobracco-geojam** [comment]
@kdowswell Hi there, I had the same issue with inside a Tab navigator and I fixed by supplying this `detachInactiveScreens={false}` (to the Tab.Navigator) for Android exclusively. If it is set to `true` or `undefined`, the issue persists. Hope this is helpful

**Comment by kdowswell** [comment]
Is there
