### ISSUE TITLE
Could not find com.facebook.react:react-native:0.71.0-rc.0

### ISSUE THREAD

**Issue by grant-solomons** [facebook/react-native#35339]
### Description

I keep getting this error for my libraries `Could not find com.facebook.react:react-native:0.71.0-rc.0`
This prevents me from making a release build.

### Version

react-native: ^0.70.0 => 0.70.0 

### Output of `npx react-native info`

System:
    OS: macOS 13.0
    CPU: (8) arm64 Apple M1
    Memory: 77.98 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.5.5 - /opt/homebrew/bin/npm
    Watchman: 2022.09.05.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8815526
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: ^0.70.0 => 0.70.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

cd android                                    
./gradlew bundleRelease

### Snack, code example, screenshot, or link to a repository

<img width="894" alt="Screenshot 2022-11-14 at 15 59 46" src="https://user-images.githubusercontent.com/100674583/201678965-4a8080d8-1540-483e-ae1d-4c9a8915013b.png">

**Comment by pnthach95** [comment]
Do you check https://github.com/facebook/react-native/issues/35210 for solution? What is your gesture handler version?
