### ISSUE TITLE
   > Could not find any matches for com.facebook.react:react-native:+ as no versions of com.facebook.react:react-native are available.

### ISSUE THREAD

**Issue by grant-solomons** [facebook/react-native#35336]
### Description

I came across an issue of not being able to an android apk. [https://github.com/facebook/react-native/issues/35210](url) points to hot fixes for those versions, but I am on version `react-native: 0.71.0-rc.0 => 0.71.0-rc.0` 

After upgrading to  0.71.0-rc.0 I now get the issue    `> Could not find any matches for com.facebook.react:react-native:+ as no versions of com.facebook.react:react-native are available.` after running `npx react-native run-android`

### Version

 0.71.0-rc.0 

### Output of `npx react-native info`

System:
    OS: macOS 13.0
    CPU: (8) arm64 Apple M1
    Memory: 129.47 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.5.5 - /opt/homebrew/bin/npm
    Watchman: 2022.09.05.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8815526
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.0-rc.0 => 0.71.0-rc.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

being on version 0.71.0-rc.0
run: `npx react-native run-android`

### Snack, code example, screenshot, or link to a repository

<img width="992" alt="Screenshot 2022-11-14 at 13 51 24" src="https://user-images.githubusercontent.com/100674583/201653298-9190b002-a64f-4c8b-b42a-ce741aa7a703.png">

**Comment by yanel777** [comment]
same issue. why is closed?

**Comment by rcaraway101** [comment]
@cortinico could you please explain why this was closed, I recently encountered the same issue ?

**Comment by cortinico** [comment]
The author closed it so I'm unsure why this was the case.
If you're having the same issue, please open a new issue

**Comment by jguipi** [comment]
having the same issues

**Comment by grant-solomons** [comment]
HI, I have updated to a specific RN version
namely 0.70.5

**Comment by brandon-austin-lark** [comment]
+1

**Comment by michakfromparis** [comment]
Running on 0.70.5 on an ejected bare expo and encountering the issue anyway:

```
* What went wrong:
Could not determine the dependencies of task ':app:processDebugResources'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find any matches for com.facebook.react:react-android:+ as no versions of com.facebook.react:react-android are available.
     Searched in the following locations:
       - file:/Users/michak/.m2/repository/com/facebook/react/react-android/
       - file:/Users/michak/021/tacktick/node_modules/react-native/android/com/facebook/react/react-android/maven-metadata.xml
       - file:/Users/michak/021/tacktick/node_modules/jsc-android/dist/com/facebook/react/react-android/maven-metadata.xml
       - https://dl.google.com/dl/android/maven2/com/facebook/react/react-android/maven-metadata.xml
       - https://www.jitpack.io/com/facebook/react/react-android/maven-metadata.xml
     Required by:
         project :app > project :react-native-mmkv
         ```

**Comment by cortinico** [comment]
> If you're having the same issue, please open a new issue

Please open separate issues. Commenting with +1 is not allowing us to properly investigate and debug your problem if any.
