### ISSUE TITLE
Canot install Pod in iOS

### ISSUE THREAD

**Issue by jbsolutions2008** [facebook/react-native#35338]
### Description

When I'm trying to install pod in old project it gets failed with below error.

First i have deleted the pod.lock file.
After that i have run the "pod install" command, but unfortunately pod it's not successfully installed.

So i have fetch some issue, please suggest me how can I solve this issue?

### Version

0.64.2

### Output of `npx react-native info`

System:
    OS: macOS 12.6
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
    Memory: 4.41 GB / 24.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
    Yarn: 1.22.18 - ~/.yarn/bin/yarn
    npm: 7.16.0 - /Volumes/Data(D)/Daryl/NewBackup/foodtrucking-app/node_modules/.bin/npm
    Watchman: 2022.11.07.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK:
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8815526
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 19.0.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.2 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. npm install
2. delete old pod.lock file
3. pod install

### Snack, code example, screenshot, or link to a repository

<img width="1030" alt="Pod install Error" src="https://user-images.githubusercontent.com/7472158/201676957-2543d1eb-2aca-446b-9cb5-a304c0bea50e.png">

**Comment by RalissonMattias** [comment]
same here in M2

**Comment by jbsolutions2008** [comment]
> same here in M2

@RalissonMattias  I

**Comment by jbsolutions2008** [comment]
> same here in M2

@RalissonMattias 
I have found the solution by removing '( )' brackets from the project drive.

For Instance, Data D from Data-(D)
