### ISSUE TITLE
Android resource linking failed

### ISSUE THREAD

**Issue by vaish8529** [facebook/react-native#35348]
### Description

> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Android resource linking failed
     ERROR:D:\project\android\app\build\intermediates\incremental\debug\mergeDebugResources\merged.dir\values\values.xml:831: AAPT: error: resource drawable/rn_edit_text_material (aka com.project:drawable/rn_edit_text_material) not found

### Version

0.70.5

### Output of `npx react-native info`

System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-12650H
    Memory: 2.18 GB / 15.68 GB
  Binaries:
    Node: 14.20.1 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.17 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 29, 30, 31, 33
      Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0, 33.0.0
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64, android-30 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-31 | Intel x86 Atom_64, android-31 | Google APIs ARM 64 v8a, android-31 | Google APIs Intel x86 Atom_64, android-33 | Google APIs ARM 64 v8a, android-33 | Google APIs Intel x86 Atom_64, android-33 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: AI-213.7172.25.2113.9014738
    Visual Studio: Not Found
  Languages:
    Java: 11.0.16 - /c/Program Files/Common Files/Oracle/Java/javapath/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.5 => 0.70.5
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

react-native run-android

### Snack, code example, screenshot, or link to a repository

In values.xml file.

<style name="Theme.AppCompat.DayNight" parent="Theme.AppCompat.Light"/>
        
        <item name="android:editTextBackground">@drawable/rn_edit_text_material</item>
    </style>

**Comment by shoaibarif244** [comment]
greetings☺ @vaish8529 did you find the solution I got stuck in this problem for the previous 3days. ☹

**Comment by shoaibarif244** [comment]
> Yes, I have copied the rn_edit_text_material file from another project and put them in the res/drawable folder of the current project.

@vaish8529 Thanks for your reply I'm trying this solution & will inform you

**Comment by ravikantverma167** [comment]
@vaishnavimaske  Thank you, it also works for me.


<?xml version="1.0" encoding="utf-8"?>

<inset xmlns:android="http://schemas.android.com/apk/res/android"
       android:insetLeft="@dimen/abc_edit_text_inset_horizontal_material"
       android:insetRight="@dimen/abc_edit_text_inset_horizontal_material"
       android:insetTop="@dimen/abc_edit_text_inset_top_material"
       android:insetBottom="@dimen/abc_edit_text_inset_bottom_material">
    <selector>
             
    </selector>
</inset>

**Comment by barmanrajdeep** [comment]
> Yes, I have copied the rn_edit_text_material file from another project and put them in the res/drawable folder of the current project.

https://github.com/nklmantey/react-native-travel-app/blob/main/android/app/src/main/res/drawable/rn_edit_text_material.xml

**Comment by nguyenthanhan201** [comment]
> @vaishnavimaske Thank you, it also works for me.
> 
> Paste the below lines of code at path: **android/app/src/main/res/drawable/rn_edit_text_material.xml**
> 
> `<?xml version="1.0" encoding="utf-8"?> <inset xmlns:android="http://schemas.android.com/apk/res/android" android:insetLeft="@dimen/abc_edit_text_inset_horizontal_material" android:insetRight="@dimen/abc_edit_text_inset_horizontal_material" android:insetTop="@dimen/abc_edit_text_inset_top_material" android:insetBottom="@dimen/abc_edit_text_inset_bottom_material"> <selector> </selector> </inset>`

thank you for help

**Comment by abhilashbhosle** [comment]
in my case **drawable/rn_edit_text_material.xml** was missing inside the res folder, I copied from the previous project.

**Comment by Sreekumaar** [comment]
@abhilashbhosle did u find the solution im also facing same 
 What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Android resource linking failed
     ERROR: C:\Users\Admin\ecommerce\build\app\intermediates\packaged_manifests\debug\processDebugManifestForPackage\AndroidManifest.xml:97: AAPT: error: resource xml/gma_ad_services_config (aka com.example.ecommerce:xml/gma_ad_services_config) not found.
