### ISSUE TITLE
npx react-native init AwesomeProject error

### ISSUE THREAD

**Issue by zhaoyiming0803** [facebook/react-native#35346]
### Description

run script by terminal:

```shell
npx react-native init AwesomeProject
```

The following error occurred：

error Failed to load configuration of your project.
info Run CLI with --verbose flag for more details.

### Version

init project error

### Output of `npx react-native info`

error Failed to load configuration of your project.
info Run CLI with --verbose flag for more details.

### Steps to reproduce

run script by terminal:

```shell
npx react-native init AwesomeProject
```

The following error occurred：

error Failed to load configuration of your project.
info Run CLI with --verbose flag for more details.

### Snack, code example, screenshot, or link to a repository

Error reported when initializing the project

**Comment by SATOKOKI645** [comment]
same issue
https://github.com/react-native-community/cli/issues/1681

**Comment by cortinico** [comment]
Closing as this is a CLI issue, like the one linked by @SATOKOKI645 
Plus there is no log or anything that can help us debug here, we would need more context.
