### ISSUE TITLE
Poor performance / app crash for inverted FlatList with RTL languages

### ISSUE THREAD

**Issue by Dukeman330** [facebook/react-native#35341]
### Description

It appears that with the FlatList component, any time
1. The FlatList is inverted
2. The FlatList `renderItem` is trying to render text in an RTL language, and
3. The user is trying to view this FlatList on a recent Google Pixel device, then
the performance of the FlatList is unusably slow.

This is exacerbated when the user is trying to interact with a TextInput in the same screen (as they would in a chat app) - the user is only able to type a few characters before app performance plummets (each frame takes a couple of seconds to render), then the app often crashes entirely.

This bug does not appear to exist with a non-inverted FlatList - the app behaves normally.

### Version

0.70.4 (also reproducible on 0.68.2 and 0.69.3)

### Output of `npx react-native info`

System:
    OS: macOS 13.0.1
    CPU: (8) arm64 Apple M2
    Memory: 492.23 MB / 24.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.13.2/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
    Watchman: 2022.10.24.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/chris/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 19.0.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.2 => 0.68.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. Set up a screen with an inverted FlatList and a TextInput (as in the attached snack)
2. For all FlatList elements render some RTL text (ie, Hebrew)
3. Run the app on a recent Google Pixel device running Android 13 (tested on Pixel 6 specifically)
4. Try scrolling the list, then typing a few characters into the TextInput. Within about 10 seconds of typing and/or deleting the app performance plummets

### Snack, code example, screenshot, or link to a repository

https://snack.expo.dev/@dukeman330/flatlist-example

**Comment by devoren** [comment]
Same issue with flash-list

**Comment by chlec** [comment]
Facing this issue as well
