### ISSUE TITLE
ERROR: * What went wrong: Execution failed for task ':app:mergeReleaseNativeLibs'.

### ISSUE THREAD

**Issue by Rasantis** [facebook/react-native#35357]
### Description

I'm trying to generate aab and when I run the command to generate aab, I get the following error: * What went wrong:
Execution failed for task ':app:mergeReleaseNativeLibs'.
How to solve ?

### Version

0.63.3

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
    Memory: 2.20 GB / 7.83 GB
  Binaries:
    Node: 16.18.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 29, 30, 31, 33
      Build Tools: 29.0.2, 30.0.2, 31.0.0, 33.0.0
      System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-31 | Android TV ARM 64 v8a, android-31 | Android TV Intel x86 Atom, android-31 | ARM 64 v8a, android-31 | Intel x86 Atom_64, android-31 | Google TV ARM 64 v8a, android-31 | Google TV Intel x86 Atom, android-31 | Google APIs ARM 64 v8a, android-31 | Google APIs Intel x86 Atom_64, android-31 | Google Play Intel x86 Atom_64, android-TiramisuPrivacySandbox | Google Play Intel x86 Atom_64
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: AI-213.7172.25.2113.9123335
    Visual Studio: 16.11.33027.164 (Visual Studio Community 2019)
  Languages:
    Java: 11.0.12
    Python: 3.10.5
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.1 => 17.0.1
    react-native: 0.63.3 => 0.63.3
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

gradlew bundleRelease

### Snack, code example, screenshot, or link to a repository

.

**Comment by gokul1099** [comment]
Have you tried adding this to the android/build.gradle

allprojects {
    repositories {
        exclusiveContent {
       // We get React Native's Android binaries exclusively through npm,
       // from a local Maven repo inside node_modules/react-native/.
       // (The use of exclusiveContent prevents looking elsewhere like Maven Central
       // and potentially getting a wrong version.)
       filter {
           includeGroup "com.facebook.react"
       }
       forRepository {
           maven {
               url "$rootDir/../node_modules/react-native/android"
           }
       }
   }

**Comment by safaiyeh** [comment]
Please use the issue template
