### ISSUE TITLE
Problem with kotlin for

### ISSUE THREAD

**Issue by VictorPulzz** [facebook/react-native#35355]
### Description

The project used to be built for android and just stopped doing it, reset the cache node_modules reinstalled, nothing will help, it just breaks and that's it
<img width="533" alt="image" src="https://user-images.githubusercontent.com/23406402/202009901-88348e90-c74e-4dee-bab3-313dbd432bbf.png">

### Version

0.67.4

### Output of `npx react-native info`

System:
    OS: macOS 12.2.1
    CPU: (8) x64 Apple M1
    Memory: 34.24 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.1/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
    Watchman: 2022.11.14.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 30, 31, 32
      Build Tools: 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0
      System Images: android-30 | ARM 64 v8a, android-30 | Intel x86 Atom_64, android-30 | Google APIs ARM 64 v8a, android-30 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom_64, android-30 | Google Play ARM 64 v8a, android-31 | Google APIs ARM 64 v8a, android-32 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.4 => 0.67.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

-

### Snack, code example, screenshot, or link to a repository

-

**Comment by kiko111pro** [comment]
Facing same issue since a day

**Comment by cortinico** [comment]
Hi,
Thanks for reporting this issue.

It seems like this issue is actually unrelated to React Native core but related to react-native screens. Please open this issue against this other repository:

https://github.com/software-mansion/react-native-screens/issues

I'll be closing this but feel free to reopen if the other repo points back to us as a issue in the core of React Native.
