### ISSUE TITLE
PushNotificationIOS.removeEventListener doesn't work

### ISSUE THREAD

**Issue by andreaslindahl** [facebook/react-native#3535]
I'm having trouble removing Push event listeners. I add an eventlistener in componentWillMount:

PushNotificationIOS.addEventListener('register', this._registeredForPush.bind(this));

And then I remove it in componentWillUnmount:

PushNotificationIOS.removeEventListener('register', this._registeredForPush.bind(this));

But it never gets removed. PushNotificationIOS doesn't seem to find the function to remove in the _notifHandlers Map object.

**Comment by andreaslindahl** [comment]
The problem seems to be .bind(this). But I need that to be able to access this in the listener callback function...

**Comment by ide** [comment]
`bind` creates a new function instance so figure out another way to bind it or retain the function reference. This is why I think add/removeEventListener isn't a good API =P but that's how it's worked for 15 years.

**Comment by alvaromb** [comment]
@andreaslindahl use something like:

```es6
this.bindedFunction = this._myFunction.bind(this)
PushNotificationIOS.addEventListener('register', this.bindedFunction)
PushNotificationIOS.removeEventListener('register', this.bindedFunction)
```
