### ISSUE TITLE
React Native 0.65.3 - no versions of com.facebook.react:hermes-engine are available.

### ISSUE THREAD

**Issue by Libero793** [facebook/react-native#35367]
### Description

Hey Guys, 

as we updated our React Native Version to 0.65.3 as recommended, we are facing an Error on Android exclusively:

`Could not find any matches for com.facebook.react:hermes-engine:0.65.+ as no versions of com.facebook.react:hermes-engine are available.`

I have to admit that im not quite sure what this error is related to, but could it be possible that there is no hermes version specifyed for the latest patch 065.3 as RN+Hermes Bundleing only starte later on?

Would be great if someone could help out with that!

### Version

0.65.3

### Output of `npx react-native info`

System:
    OS: Windows 10 10.0.19044
    CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor
    Memory: 39.18 GB / 63.91 GB
  Binaries:
    Node: 16.18.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowAllTrustedApps: Disabled
      Versions: 10.0.17763.0, 10.0.19041.0
  IDEs:
    Android Studio: AI-213.7172.25.2113.9123335
    Visual Studio: Not Found
  Languages:
    Java: 11.0.17 - C:\Program Files\Eclipse Adoptium\jdk-11.0.17.8-hotspot\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.65.3 => 0.65.3
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1) Install React Native 0.65.3
2) ./gradlew clean 
3) Run into the error 

### Snack, code example, screenshot, or link to a repository

    "react-native": "0.65.3",

**Comment by Libero793** [comment]
If you have those lines in your build.gradle from the old fix - remvoe them

`        exclusiveContent {
           // We get React Native's Android binaries exclusively through npm,
           // from a local Maven repo inside node_modules/react-native/.
           // (The use of exclusiveContent prevents looking elsewhere like Maven Central
          // and potentially getting a wrong version.)
           filter {
               includeGroup "com.facebook.react"
           }
           forRepository {
               maven {
                   url "$rootDir/../node_modules/react-native/android"
               }
           }
       }`

**Comment by sachiotomita** [comment]
as mentioned above,
 
removing these lines at build.gradle worked for me..

```
        exclusiveContent {
            // We get React Native's Android binaries exclusively through npm,
            // from a local Maven repo inside node_modules/react-native/.
            // (The use of exclusiveContent prevents looking elsewhere like Maven Central
            // and potentially getting a wrong version.)
            filter {
                includeGroup "com.facebook.react"
            }
            forRepository {
                maven {
                    url "$rootDir/../node_modules/react-native/android"
                }
            }
        }
```
