### ISSUE TITLE
Adding blurRadius to ImageBackground leads to crash

### ISSUE THREAD

**Issue by saurabhkanswal** [facebook/react-native#35364]
### Description

When i add blurRadius to <ImageBackground />, then it crashes the app.
Note: it is only happening on some images.

### Version

0.69.7

### Output of `npx react-native info`

System:
    OS: macOS 11.4
    CPU: (8) x64 Apple M1
    Memory: 30.04 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.15 - /usr/local/bin/npm
    Watchman: 2021.09.27.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 21, 31
      Build Tools: 21.1.2, 28.0.3, 29.0.2, 30.0.0, 30.0.2, 31.0.0
      System Images: android-22 | Google APIs ARM 64 v8a, android-22 | Google APIs Intel x86 Atom, android-23 | Google APIs ARM EABI v7a, android-23 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-24 | Google APIs ARM 64 v8a, android-24 | Google APIs Intel x86 Atom, android-25 | ARM 64 v8a, android-25 | Google Play Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-27 | Google APIs ARM 64 v8a, android-28 | Google APIs ARM 64 v8a, android-28 | Google APIs Intel x86 Atom_64, android-32 | Google Play ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 13.0/13A233 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

open snack link and add/remove blurRadius from  ImageBackground component.

### Snack, code example, screenshot, or link to a repository

https://snack.expo.dev/@saurabhkanswalquizizz/imagebackground-blurradius

**Comment by ababol** [comment]
May be related to this one https://github.com/facebook/react-native/issues/35706

(black and white + blur radius makes app crash)
