### ISSUE TITLE
Bundler issue. Infinite bundling when using certain libraries

### ISSUE THREAD

**Issue by Olegas** [facebook/react-native#3538]
Steps to reproduce
 1. Create a fresh project `react-native init testProject`
 1. Add `estraverse` library `npm install --save estraverse`
 1. Add link to `index.ios.js` with simple `require('estraverse')`
 1. Try to bundle `react-native bundle`

Latest command will never finish
react-native cli version is 0.1.5
OS is Mac OS X 10.11

**Comment by browniefed** [comment]
Is this still happening by chance?

**Comment by christopherdro** [comment]
@facebook-github-bot no-reply
