### ISSUE TITLE
iOS fetch() POST fails if called too soon, with app running in background

### ISSUE THREAD

**Issue by robsco** [facebook/react-native#35384]
### Description

I use deeplinks to launch/focus my app from a webpage.

The link looks like ttgm://something

I parse the "something" and immediately make a fetch call.

80% of the time this fetch call fails, IF it's a POST (switching it out for a GET works 100% of the time)...

TypeError: Network request failed
    at anonymous (http://192.168.0.20:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.thxyzabc.defhty:22664:33)
    at apply (native)
    at anonymous (http://192.168.0.20:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.thxyzabc.defhty:27853:26)
    at _callTimer (http://192.168.0.20:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.thxyzabc.defhty:27788:17)
    at callTimers (http://192.168.0.20:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.thxyzabc.defhty:27948:19)
    at apply (native)
    at __callFunction (http://192.168.0.20:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.thxyzabc.defhty:5307:36)
    at anonymous (http://192.168.0.20:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.thxyzabc.defhty:5057:31)
    at __guard (http://192.168.0.20:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.thxyzabc.defhty:5255:15)
    at callFunctionReturnFlushedQueue (http://192.168.0.20:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.thxyzabc.defhty:5056:21)

The fetch call is over https (no issues with NSAllowsArbitraryLoads, etc), and works "sometimes".

I am debugging with Flipper.

If I add a short sleep for 500ms before making the call it works.

e.g.

                try {
                    await new Promise( resolve => setTimeout( resolve, 500 ) );
                }
                catch ( error )
                {
                    this.showOverlay( { type: 'error' } );

                    Log.error( { function: _function, error: error } );
                }

I have seen this issue for many years and had old comments in my code to use GETs to work around this issue, but recently re-factored and used POSTs everywhere.

### Version

0.70

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 12.3.1
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Memory: 11.35 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 19.1.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 8.19.3 - /usr/local/bin/npm
    Watchman: 2022.11.14.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.6 => 0.70.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Create app that accepts deeplinks.

Linking.addEventListener( 'url', ... )

Link from a webpage to launch the app.

### Snack, code example, screenshot, or link to a repository

App.js

import { AppError, Log, API } from './src/Helpers';

export default class extends React.Component
{
    deeplinkListener( data )
    {
        this.handleDeeplink( data.url );
    }

    async componentDidMount()
    {
        try
        {
            Linking.addEventListener( 'url', this.deeplinkListener );
        }
        catch ( error )
        {
            console.log( error );
        }
    }

    async handleDeeplink( url )
    {
        try {

            let matches = url.match( /(\d+(a|g|u)[a-f0-9]+)/ );

            Log.debug( _function + ": matches: ", matches );

            if ( matches && matches[ 1 ] && matches[ 2 ] && matches[ 2 ] === 'a' )
            {
                const key = matches[ 1 ];

                Log.debug( _function + ": Calling getList with key " + key );

                const response = await API.getList( {
                    key: key,
                } );
            }
        }
        catch ( error )
        {
            this.hideOverlay();

            Log.error( { function: _function, error: error } );   // we include the _function again incase something deeper throws an error
        }
    }
}

Helpers.js

class API
{
    static async _call( path, timeout, args )
    {
        try {
            var url = 'https://www.mydomain.com' + path;

            if ( ! args )
            {
                args = {};
            }

            args._context = Platform.OS;

            args._version = VersionInfo.appVersion;

            let response = null;

            const options = {
                credentials: 'include',
                method: 'POST',
                headers: {
                    'Accept': 'application/json',
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify( args ),
            };

            response = await fetch( url, options );

            if ( ! response.ok )
            {
                throw new AppError( "Request Failed", { response } );
            }

            const json = await response.json();

            return json;        
        }
        catch ( error )
        {
            Log.debug( error, error.stack );

            throw error;
        }
    }

    static async getList( args )
    {
        return this._call( '/api/app/get-list.json', 0, args );
    }
}

**Comment by intergalacticspacehighway** [comment]
@robsco this is the behavior of native iOS NSURLRequest. I had encountered the same issue in past. Wrote it [over here](https://twitter.com/nishanbende/status/1486916721802104837). Sorry, it's on Twitter 😅. 

Apple developer thread of the issue https://developer.apple.com/forums/thread/106838

**Comment by robsco** [comment]
At least I'm not going mad.

I did find it a bit weird it only seems to happen with POST requests - did you see the same, or any type of request?

**Comment by intergalacticspacehighway** [comment]
yeah. I felt the same. It was surprising seeing requests getting cancelled. I am not sure about GET requests. I am out on a trip right now, would’ve tried it otherwise. Can you try a GET request with larger payload?
akaik iOS pauses downloads if not put in a background task, so might be same for GET requests?

This thread also highlights the same issue -  https://github.com/AFNetworking/AFNetworking/issues/4279

**Comment by anniewey** [comment]
Anyone able to solve this?
