### ISSUE TITLE
Method does not override or implement a method from a supertype @Override

### ISSUE THREAD

**Issue by Marcoantonio9** [facebook/react-native#35386]
### Description

Hi! I'm having trouble running my react-native project. Everything was fine until the update on November 4th, but since then I am not able to run my app anymore. I received the following error:

`/myapp/node_modules/react-native-sqlcipher-storage/src/android/src/main/java/org/pgsqlite/SQLitePluginPackage.java:44: error: method does not override or implement a method from a supertype
    @Override
`

I already followed some instructions in the link: [ref](https://github.com/facebook/react-native/issues/35210)

But I was not successful.

### Version

0,60,0

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: Linux 5.17 Pop!_OS 20.04 LTS
    CPU: (4) x64 Intel(R) Core(TM) i5-2430M CPU @ 2.40GHz
    Memory: 133.11 MB / 7.65 GB
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 10.24.1 - ~/.nvm/versions/node/v10.24.1/bin/node
    npm: 6.14.12 - ~/.nvm/versions/node/v10.24.1/bin/npm
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.0 => 0.60.0

### Steps to reproduce

react-native run-android

### Snack, code example, screenshot, or link to a repository

Android/build.gradle

```
def REACT_NATIVE_VERSION = new File(['node', '--print',"JSON.parse(require('fs').readFileSync(require.resolve('react-native/package.json'), 'utf-8')).version"].execute(null, rootDir).text.trim())
allprojects {
    configurations.all {
          resolutionStrategy {
            force "com.facebook.react:react-native:" + REACT_NATIVE_VERSION
          }
    }    


    repositories {
        maven { url "https://www.jitpack.io" }
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url ("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }      
        google()
        jcenter()      
    }
}

```

App/build.gradle

```
   dependencies {
     implementation project(':@react-native-community_netinfo')
     implementation project(':react-native-sqlcipher-storage')
     implementation fileTree(dir: "libs", include: ["*.jar"])
     implementation "com.facebook.react:react-native:+" 
     implementation 'com.google.firebase:firebase-analytics:17.2.0'
     implementation 'androidx.multidex:multidex:2.0.1'
    }
```

**Comment by cortinico** [comment]
Hi,
Thanks for reporting this issue.

It seems like this issue is actually unrelated to React Native core. Please open this issue against this other repository:

https://github.com/axsy-dev/react-native-sqlcipher-storage/issues

I'll be closing this but feel free to reopen if the other repo points back to us as a issue in the core of React Native.
