### ISSUE TITLE
HELP：how to integrate RN 0.70.x to app which support iOS9 ?  

### ISSUE THREAD

**Issue by zyy71104233** [facebook/react-native#35395]
### New Version

0.70.5

### Old Version

0.62

### Build Target(s)

iOS device

### Output of `react-native info`

![value is unavailable](https://user-images.githubusercontent.com/5689191/202724619-8ad61005-ca51-4678-9f7b-03c648da4a00.jpeg)

value is unavailable introduce in iOS12

### Issue and Reproduction Steps

dear friend:
	I need a help to solve a compile error. Detail is that, minimum iOS version of our bank app is iOS9, and we choose 0.70.5 RN to integrate to app, I know that 0.70.5 only support iOS12.4 and above.
	 so my question is that if there is a method to integrate 0.70.5 into app which target is iOS9. 
	 when app runs on 12.4 and above，we can use RN，when runs device which version is between iOS9 and iOS 12.4， we use webview to load page。  so we just need RN 0.70 compile successfully and get the building product。
	 I try to do this，when I set platform as iOS9 in podSpec and compile，some error happened，“ value is unavailable introduce in iOS 12 ”。 when I compile app which platform is iOS 12.4, it compile successfully， but crash when app launch。 It seems that libc++.1.dylib not found, error message is below
	
dyld: Symbol not found: __ZNSt19bad_optional_accessD1Ev
  Referenced from: /Users/zhengyueyang761/Library/Developer/CoreSimulator/Devices/50438C49-53E9-4F22-8495-9721BD60FE81/data/Containers/Bundle/Application/CD0D37C6-F4BF-4084-828C-A795988998FF/zyy.app/zyy
  Expected in: /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 10.3.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libc++.1.dylib
 in /Users/zhengyueyang761/Library/Developer/CoreSimulator/Devices/50438C49-53E9-4F22-8495-9721BD60FE81/data/Containers/Bundle/Application/CD0D37C6-F4BF-4084-828C-A795988998FF/zyy.app/zyy
dyld: launch, loading dependent libraries
DYLD_FRAMEWORK_PATH=/Users/zhengyueyang761/Library/Developer/Xcode/DerivedData/zyy-adjnucfudhfybpflkttitqinnylu/Build/Products/Debug-iphonesimulator
DYLD_FALLBACK_LIBRARY_PATH=/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 10.3.simruntime/Contents/Resources/RuntimeRoot/usr/lib
DYLD_ROOT_PATH=/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 10.3.simruntime/Contents/Resources/RuntimeRoot
DYLD_FALLBACK_FRAMEWORK_PATH=/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 10.3.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks
DYLD_INSERT_LIBRARIES=/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 10.3.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libBacktraceRecording.dylib:/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 10.3.simruntime/Contents/Resources/RuntimeRoot/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib
DYLD_SHARED_REGION=avoid
DYLD_LIBRARY_PATH=/Users/zhengyueyang761/Libra
(lldb) 

So if there is a way to compile RN 0.70.5 to iOS9, only build successfully and no crash that is OK, thanks a lot in advance

**Comment by iBotPeaches** [comment]
> I need a help to solve a compile error. Detail is that, minimum iOS version of our bank app is iOS9, and we choose 0.70.5 RN to integrate to app, I know that 0.70.5 only support iOS12.4 and above.

It looks like this is painfully obvious. If you ignore the platform requirements of a version then have issues when it doesn't work on that dropped version - what do you expect?

Its not like you can just change a few flags and expect it work - iOS versions are only dropped when its clear/cut that there is no longer an easy way to support it.

I'd say your option with these constraints is - use an older RN version.

**Comment by zyy71104233** [comment]
the reason why we choose RN 0.70.5 instead of 0.62 is that we think the latest version is more high performance than old version.  
as currently we use h5 which is bad for user experience,  we are afraid that 0.62 performance is not much good than h5 web view, of cause it's our guess, we firstly use rn .
maybe it's really not necessary to do adaptor work for lower iOS version ,thanks for your suggestion @iBotPeaches

**Comment by cortinico** [comment]
Closing as the @iBotPeaches already answered
