### ISSUE TITLE
RN does not support NSNotificationCenter(post & addObserver)

### ISSUE THREAD

**Issue by ToccaLeee** [facebook/react-native#3539]
As I kown, until now, RN still does not support NSNotificationCenter in iOS。Does RN has plan to support it or has other substitution ?

**Comment by kevinzzz007** [comment]
@ToccaLeee are you looking to implement Notifications in RN?  If so, check out this: https://facebook.github.io/react-native/docs/pushnotificationios.html#content

**Comment by ToccaLeee** [comment]
Yes, thanks @kevinzzz007

**Comment by kevinzzz007** [comment]
@ToccaLeee feel free to close this issue if it's solve :-)

**Comment by ide** [comment]
@ToccaLeee One of RN's goals is to let anyone expose native APIs to JS when they need them. Take a look at https://facebook.github.io/react-native/docs/native-modules-ios.html if you would like to write a module to call into NSNotificationCenter.
