### ISSUE TITLE
Android release bundle is not generated in the correct location on RN 0.71.0-rc.0

### ISSUE THREAD

**Issue by louiszawadzki** [facebook/react-native#35398]
### Description

When building for release on Android (`yarn android --variant=release`), the bundle file is located at `android/app/build/ASSETS/createBundleReleaseJsAndAssets/index.android.bundle`, which is a change from the previous location of `android/app/build/generated/assets/react/Release/index.android.bundle`.
The `android/app/build/generated` does not contain an `assets` directory anymore.

By looking at the [gradle-plugin code](https://github.com/facebook/react-native/blob/2df63e52f4570f348156bcd47696b8395a73fbc7/packages/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/TaskConfiguration.kt#L27), I'm assuming it's not supposed to have changed.

### Version

0.71.0-rc.0

### Output of `npx react-native info`

```
System:
    OS: macOS 12.6.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 3.37 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.11.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - ~/.npm-global/bin/yarn
    npm: 8.19.2 - /opt/homebrew/bin/npm
    Watchman: 2022.10.24.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.0-rc.0 => 0.71.0-rc.0
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

- Create a new app using the command: `npx react-native init <YourAppName> --version 0.71.0-rc.0`
- Manually download the [maven-local.zip](https://github.com/facebook/react-native/releases/download/v0.71.0-rc.0/maven-local.zip) archive (you can also find the link in [this release](https://github.com/facebook/react-native/releases/tag/v0.71.0-rc.0)).
- Unzip the `maven-local.zip` on a folder on your disk.
- Add the `REACT_NATIVE_MAVEN_LOCAL_REPO=<path_to_the_maven-local_unzipped_folder>` setting to the android/gradle.properties file
- Build with `yarn android --variant=release`

### Snack, code example, screenshot, or link to a repository

Screenshot of the `android` folder directory after a build:

<img width="388" alt="image" src="https://user-images.githubusercontent.com/8973379/202740627-e8d1faa8-6393-43a6-b342-0028ff861e79.png">

**Comment by louiszawadzki** [comment]
After a quick investigation, deleting [this line](https://github.com/facebook/react-native/blob/2df63e52f4570f348156bcd47696b8395a73fbc7/packages/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/TaskConfiguration.kt#L75) makes the bundle to be generated in the right location again:
```
variant.sources.assets?.addGeneratedSourceDirectory(bundleTask, BundleHermesCTask::jsBundleDir)
```

**Comment by louiszawadzki** [comment]
I work on the Datadog SDK, which provide an error tracking system. We use the bundle for adding more context to errors in Datadog, in addition to the sourcemaps.
We also provide users with a script that will locate that bundle and upload it. Currently it looks for `android/app/build/generated/assets/react/{variant}/index.android.bundle`.

If the location changes it's not so much of an issue for us, I wanted to raise this to get confirmation that this is indeed going to change before making the change on our side, and in case there was some bug hidden behind it.

**Comment by louiszawadzki** [comment]
I'll close this issue, as it seems there is no hidden bug behind it :)

**Comment by cortinico** [comment]
> I'll close this issue, as it seems there is no hidden bug behind it :)

Nope the change was intended. We now use the Artifacts API of AGP so we don't have to "hardcode" paths around anymore. As AGP changes paths, we won't be affected by future breakages.

**Comment by mym0404** [comment]
I am upload js bundle to Sentry manually.
It seems to generated js bundle path is changed in `0.71`.
Well, the release app is running well.
So I just changed generated bundle path to  `app/build/ASSETS/createBundleReleaseJsAndAssets/index.android.bundle`

I have no idea this is a correct fix.

**Comment by louiszawadzki** [comment]
Hi @mym0404,

This is indeed the correct fix from our conversation ahead. 
When you'll update the Android Gradle Plugin to `7.4.0` or above (probably with RN `0.72`) the new path will be `app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle`.

**Comment by mym0404** [comment]
AGP is `7.3.1` in my project (RN `0.71.0` default version).
Anyway, Thank you for response 👍🏻
