### ISSUE TITLE
Execution failed for task ':app:installDebug'.

### ISSUE THREAD

**Issue by webwork-dot** [facebook/react-native#35396]
### Description

Execution failed for task ':app:installDebug'.
> java.util.concurrent.ExecutionException: com.android.builder.testing.api.DeviceException: com.android.ddmlib.InstallException: INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl2114881157.tmp/base.apk (at Binary XML file line #137): com.braintreepayments.api.BraintreeBrowserSwitchActivity: Targeting S+ (version 31 and above) requires that an explicit value for android:exported be defined when intent filters are present

### Version

0.67.5

### Output of `npx react-native info`

System:
    OS: macOS 12.6.2
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Memory: 28.44 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.17.5 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.14 - /usr/local/bin/npm
    Watchman: 2022.11.07.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.5 => 0.67.5 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

After updating targetSdkVersion & compileSdkVersion to 31 errors showing.....

### Snack, code example, screenshot, or link to a repository

// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "30.0.3"
        minSdkVersion = 21
        compileSdkVersion = 31
        targetSdkVersion = 31
        androidXCore = "1.6.0"
        googlePlayServicesAuthVersion = "16.0.1"
        kotlinVersion = '1.5.0'
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:4.0.1")
        classpath 'com.google.gms:google-services:4.3.10'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        google()
        jcenter()
        maven { url 'https://www.jitpack.io' }
    }
}

**Comment by onatvaris** [comment]
_maybe_, buildToolsVersion upgrade to 31 and try again

**Comment by cortinico** [comment]
Can you share your `AndroidManifest` @webwork-dot ?

**Comment by webwork-dot** [comment]
Solved thanks.
