### ISSUE TITLE
Should ReadableMapKeySeyIterator be ReadableMapKeySetIterator?

### ISSUE THREAD

**Issue by emmoistner** [facebook/react-native#3540]
I'm curious if this is intentional. [Here](https://github.com/facebook/react-native/blob/1b55e4657cdde870a77a8360b5017f9282ffd33e/ReactAndroid/src/main/java/com/facebook/react/bridge/ReadableMapKeySeyIterator.java) and [here](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/bridge/ReadableMap.java#L27).

**Comment by ide** [comment]
cc @kmagiera @mikearmstrong001

**Comment by kmagiera** [comment]
Yeah, that's a typo. It should be "Set". Thanks

**Comment by browniefed** [comment]
@facebook-github-bot answered
