### ISSUE TITLE
How to disable Game Turbo in MIUI phones?

### ISSUE THREAD

**Issue by Gabotron-ES** [facebook/react-native#35403]
### Description

when I open my react native app a Game Turbo enabled modal shows up on start, I did some research and it says:

```
Game Turbo 4.0 is a new feature of MIUI that lets you customize and make your gaming experience better. With Game Turbo, you can choose to boost performance or battery life, depending on your needs. You can also customize or limit the display and sound settings to create the perfect environment for gaming.
```

But my app is not a game! I can disable Game Turbo from my phone settings but I'd like to disable it programatically for all MIUI devices.

Is there a snippet or manifest so I can disable Game Turbo for MIUI devices programatically?

### Version

0.68.2

### Output of `npx react-native info`

Can't post it right now, not really needed

### Steps to reproduce

Have a MIUI phone, on startup a Game Turbo enabled modal appears on the upper left corner

### Snack, code example, screenshot, or link to a repository

Don't have any code related to issue, wanna hear about other MIUI users.

**Comment by iBotPeaches** [comment]
@Gabotron-ES - You asked this already and got an answer - https://github.com/facebook/react-native/issues/34582

**Comment by Adnan-Bacic** [comment]
i had the same problem with samsung and game launcher. i had to write to samsung about my issue and they could do something so that the app was no longer treated as a game.

i wrote a small gist about it: https://gist.github.com/Adnan-Bacic/718eb3b4e70380696c91dc21c4804112
