### ISSUE TITLE
Task :expo-av:configureCMakeDebug[arm64-v8a] FAILED

### ISSUE THREAD

**Issue by theartificialguy** [facebook/react-native#35409]
### Description

I shifted to M1 machine and getting this error for expo-av, I couldn't find anything related to this error, it is happening only in android.

Command used to run project: npx react-native run-android Build Error:
```
> Task :expo-av:configureCMakeDebug[arm64-v8a] FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':expo-av:configureCMakeDebug[arm64-v8a]'.
> [CXX1405] exception while building Json A problem occurred starting process 'command '/Users/macbook/Library/Android/sdk/cmake/3.18.1/bin/cmake''

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
```
Package.json:
```
"expo": "^46.0.0",
"expo-av": "~12.0.4",
"react-native": "0.69.6",
```
I have created a detailed SO question also -> https://stackoverflow.com/q/74497904/11685381

If anyone need any more details, please feel free to ask, I'm happy to provide, I just can't get past this error.

### Version

0.69.6

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 12.5
    CPU: (8) arm64 Apple M1
    Memory: 551.00 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.0.1 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 7.24.2 - ~/Desktop/myproject/node_modules/.bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 29, 30, 31, 33
      Build Tools: 30.0.3, 31.0.0, 33.0.0
      System Images: android-31 | Google APIs ARM 64 v8a, android-31 | Google Play ARM 64 v8a, android-33 | Google APIs ARM 64 v8a, android-33 | Google Play ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.6 => 0.69.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

I was able to reproduce exact build issue, below are the steps that I followed, I have also created a repo if anyone wants...

1) on an M1 MacBook -> `npx react-native init m1project --version 0.69.6`
2) `npx react-native run-android` -> It was working.
3) `npx install-expo-modules@latest`
4) `npx expo install expo-av`
5) `npx react-native run-android` -> Got the same build error as mentioned in the title and SO question.

### Snack, code example, screenshot, or link to a repository

Here is the link of repo that I created: https://github.com/theartificialguy/rn-m1

**Comment by mai-hu-mukesh-parmar** [comment]
Open Android Studio -> SDK Manager -> SDK Tools -> CMake 
uncheck the check options and install it again and try to build it again

**Comment by cortinico** [comment]
That's unrelated to React Native but it's a Expo AV issue:
https://github.com/expo/expo/tree/master/packages/expo-av

So please an issue on https://github.com/expo/expo/issues instead

**Comment by jucoAllison** [comment]
Am trying to install expo-av and use it inside my bare react-native project. But after I follow all installation guild for expo, Am still getting Task :expo-av:configureCMakeDebug[arm64-v8a] FAILED
