### ISSUE TITLE
iOS build phase failed => The following build commands failed: CompileC ... (in target 'RCT-Folly' from project 'Pods')

### ISSUE THREAD

**Issue by ChrisCoder9000** [facebook/react-native#35405]
### Description

I'm not really sure if this is a bug or what but I cannot figure out how to get out of this situation, I will start by saying that I am on an M1 machine, I've read while searching online that the problem can be shite spaces on the path of the project, but that wasn't the case I've tried also to modify the pod file changing the useFlipper stuff in different ways (I'm not really sure how useFlipper works) I've tried different react native versions and reinstalled Xcode but nothing worked! 

my versions:
```
react-native 0.70.6
ruby 2.7.6 
```

### Version

0.70.6

### Output of `npx react-native info`

System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1
    Memory: 219.25 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.0.1 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.2 - /opt/homebrew/bin/npm
    Watchman: 2022.11.14.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/christiannonis/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 18.0.2.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Created the project with `npx react-native init xyz ` and tried both to run firstly `npm run ios` and also `pod install` and `bundle install` 

### Snack, code example, screenshot, or link to a repository

https://github.com/ChrisCoder9000/AirBnb

**Comment by snkvch** [comment]
Same issue

**Comment by akhalinem** [comment]
Same here

**Comment by jorgerojas26** [comment]
Same issue here
