### ISSUE TITLE
CanOpenUrl is giving false output for valid params

### ISSUE THREAD

**Issue by Tanvir-rahman** [facebook/react-native#35408]
### Description

`await Linking.canOpenURL('https://www.google.com/')` -> False
 
But If i use
` await Linking.openURL('https://www.google.com/')` ->  it's  been opening  with desired url.

In Previous builds it was working fine.

### Version

0.63.5

### Output of `npx react-native info`

System:
    OS: macOS 12.5
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 96.88 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
    Watchman: 2022.08.22.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK: Not Found
    Android SDK:
      API Levels: 29, 30, 32, 33
      Build Tools: 28.0.3, 29.0.2, 30.0.2
      System Images: android-30 | Intel x86 Atom_64, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8092744
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.5 => 0.63.5
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

await Linking.canOpenURL('https://www.google.com/')

### Snack, code example, screenshot, or link to a repository

```
  const openURL = async (url) => {
    console.log(
      'supported',
      await Linking.canOpenURL('https://www.google.com/'),
    );
    await Linking.openURL(url);
  };
```

**Comment by lovelytingy** [comment]
@Tanvir-rahman hi, I have checked this, you need to add QueriesSchemes for both Platforms. For Ios you need to add LSApplicationQueriesSchemes and for android you need to add queries in AndroidManifest.xml. The answer lies in a new Android security feature: [Package Visibility](https://developer.android.com/training/package-visibility/declaring).

Futher you can use this link (explains all): [Link](https://stackoverflow.com/questions/64699801/linking-canopenurl-returning-false-when-targeting-android-30-sdk-on-react-native#:~:text=The%20answer%20lies%20in%20a%20new%20Android%20security%20feature%3A%20Package%20Visibility.%20This%20works%20similar%20to%20iOS%27%20LSApplicationQueriesSchemes.)
