### ISSUE TITLE
Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.         A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.

### ISSUE THREAD

**Issue by jo780-full** [facebook/react-native#35411]
### Description

Hello , I am new to react native and react. I was expo and using maps. I have been breaking my head for the past 24hrs trying to figure out how and y my application keeps failing when I am using useSelector
to connect.

### Version

0.70.0

### Output of `npx react-native info`

ReferenceError: Can't find variable: mapStateToProps
at node_modules\react-native\Libraries\Core\ExceptionsManager.js:null in reportException
at node_modules\react-native\Libraries\Core\ExceptionsManager.js:null in handleException
at node_modules\react-native\Libraries\Core\setUpErrorHandling.js:null in handleError
at node_modules\expo\build\errors\ExpoErrorManager.js:null in errorHandler
at node_modules\expo\build\errors\ExpoErrorManager.js:null in <anonymous>
at node_modules\@react-native\polyfills\error-guard.js:null in ErrorUtils.reportFatalError
at node_modules\metro-runtime\src\polyfills\require.js:null in guardedLoadModule
at http://yw-5ax.anonymous.awesomeproject.exp.direct/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false&strict=false&minify=false:null in global code

Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
at node_modules\react-native\Libraries\Core\ExceptionsManager.js:null in reportException
at node_modules\react-native\Libraries\Core\ExceptionsManager.js:null in handleException
at node_modules\react-native\Libraries\Core\setUpErrorHandling.js:null in handleError
at node_modules\expo\build\errors\ExpoErrorManager.js:null in errorHandler
at node_modules\expo\build\errors\ExpoErrorManager.js:null in <anonymous>
at node_modules\@react-native\polyfills\error-guard.js:null in ErrorUtils.reportFatalError
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:null in __guard
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:null in callFunctionReturnFlushedQueue       

Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
at node_modules\react-native\Libraries\Core\ExceptionsManager.js:null in reportException
at node_modules\react-native\Libraries\Core\ExceptionsManager.js:null in handleException
at node_modules\react-native\Libraries\Core\setUpErrorHandling.js:null in handleError
at node_modules\expo\build\errors\ExpoErrorManager.js:null in errorHandler
at node_modules\expo\build\errors\ExpoErrorManager.js:null in <anonymous>
at node_modules\@react-native\polyfills\error-guard.js:null in ErrorUtils.reportFatalError
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:null in __guard
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:null in callFunctionReturnFlushedQueue       

### Steps to reproduce

Reference error is for maps

### Snack, code example, screenshot, or link to a repository

import { StyleSheet, Text, View,Image } from 'react-native'
import React from 'react'
import  { Component } from "react";
import tw from "tailwind-react-native-classnames";
import * as React from 'react';

import MapView,{Marker,Polygon} from 'react-native-maps';
import { useSelector } from 'react-redux';

import { selectOrigin } from '../slices/navSlice';

class Map extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      reports: [],
      latitude: 0,
      longitude: 0,
      error: null,

     
    }
    const mapStateToProps = (state) => {
      return {
        origin: selectOrigin

      }
  }
}
  
  
    componentDidMount() {
      fetch('https://gist.githubusercontent.com/jo780-full/c42f65154fac8d3d6e495326211e15b7/raw/20e8af7285f9ae5c1328e00cc79b1e2711bd446a/student.json',{
        method: 'GET',
        headers: {
          'Accept': 'application/json',
          'Content-Type': 'application/json',
        }

      })
      .then(res => res.json())
      .then(data => {
        this.setState({ reports: data.report })
      })
      .catch(console.error)
  }
  mapMarkers = () => {

    return this.state.reports.map((report) => <Marker
      key={report.id}
      coordinate={{ latitude: report.latitude, longitude: report.longitude }}
      title=" student parking spot"
      description="available"
    >
    </Marker >)
    
  }

  render() {
  
  return (
    
    <MapView

    
    mapType="mutedStandard"
    showsUserLocation={true}
        followUserLocation={true}
        zoomEnabled={true}
    style={tw`h-full w-full`}
    initialRegion={
      {
        latitude: this.mapStateToProps.origin.location.lat,
        longitude:this.mapStateToProps.origin.location.longitude,
        latitudeDelta: 0.0922,
        longitudeDelta: 0.0421,
      }
    }
  >
    
    
    

    {this.mapMarkers()}
  

      
  
  

 
    {/*student area*/}
    <Polygon
    coordinates={[
      { latitude: 12.908764862118488,   longitude: 77.56763368009942 },
      { latitude: 12.909351220825277,longitude:  77.56756522139399 },
      { latitude: 12.909496879375817,longitude:  77.56763847998074 },
      {latitude:12.909506790161094,longitude: 77.56779777527214},
      {latitude:12.909333117614427, longitude:77.56856604008081},
      {latitude:12.909124598612156,longitude: 77.56852690728837},
      { latitude: 12.909385294896701,  longitude: 77.5681230870149, },
      {latitude:12.909061025711033, longitude:77.5681799298621},
      {latitude:12.909050854045336,longitude:  77.56815645018665},
      { latitude:12.90868749725228, longitude: 77.56800790948633},
      { latitude: 12.908710622492181 , longitude: 77.56762153367315 },

    ]}
    fillColor="rgba(255, 0, 0, 0.1)"
    strokeColor="rgba(255, 0, 0, 0.5)" // fallback for when `strokeColors` is not supported by the map-provider
    strokeColors={[
      '#7F0000',
      '#00000000', // no color, creates a "long" gradient between the previous and next coordinate
      '#B24112',
      '#E5845C',
      '#238C23',
      '#7F0000'
    ]}
    strokeWidth={1}
  />
   <Polygon
    coordinates={[
      { latitude: 12.909394643253528,longitude:   77.56614422503371 },
      { latitude: 12.909456079146613, longitude:  77.56582255987011 },
{ latitude:12.90941582804595,longitude: 77.56577909160477},
{latitude:12.90938405085663, longitude:77.56579213208437},
{ latitude:12.909368162260469, longitude:77.56582255987011},
{latitude:12.90934168126461,longitude: 77.56586602813547},
{ latitude:12.908920103432747, longitude:77.56579430549765},
{latitude:12.908892563147631, longitude:77.56606489544944}
    ]}
    fillColor="rgba(0, 255, 0, 0.1)"
    strokeColor="rgba(0, 255, 0, 0.5)" // fallback for when `strokeColors` is not supported by the map-provider
    strokeColors={[
      '#7F0000',
      '#00000000', // no color, creates a "long" gradient between the previous and next coordinate
      '#B24112',
      '#E5845C',
      '#238C23',
      '#7F0000'
    ]}
    strokeWidth={1}
  />
  {/*Hospital  */}
     <Polygon
    coordinates={[
      { latitude:12.908518776874924,longitude:  77.56518322273905 },
      { latitude: 12.908724009086619,  longitude: 77.56522814973901 },
      { latitude:12.908739042012709,  longitude: 77.56516914114205 },
      { latitude: 12.908535770631334  ,longitude:   77.56512287303762},
    ]}
    fillColor="rgba(0, 0, 255, 0.1)"
    strokeColor="rgba(0, 0, 255, 0.5)" // fallback for when `strokeColors` is not supported by the map-provider
  
    strokeColors={[
      '#7F0000',
      '#00000000', // no color, creates a "long" gradient between the previous and next coordinate
      '#B24112',
      '#E5845C',
      '#238C23',
      '#7F0000'
    ]}
    strokeWidth={2}
  />
  {/*Vip Parking */}
   <Polygon
    coordinates={[
      { latitude:12.909451264916404, longitude:  77.5669158882026 },

      { latitude: 12.909262624852568,  longitude:  77.56687637127314 },

      { latitude: 12.90931398237095 ,longitude: 77.56748432403379},

      { latitude:12.909400895070368, longitude:  77.56744784686815 },
      {latitude:12.909426457234511, longitude:77.56698467532628},

    ]}
    fillColor="rgba(255, 255, 50, 0.3)"
    strokeColor="rgba(255, 255, 0, 0.6)"// fallback for when `strokeColors` is not supported by the map-provider
    strokeColors={[
      '#7F0000',
      '#00000000', // no color, creates a "long" gradient between the previous and next coordinate
      '#B24112',
      '#E5845C',
      '#238C23',
      '#7F0000'
    ]}
    strokeWidth={2}
  />
 
  </MapView>

 
  
    
  )
  }
}

export default  connect(mapStateToProps) (Map)

const styles = StyleSheet.create({
  text: {
    color: '#fff',
    fontSize: 30,
    fontWeight: 'bold',
  },

})

**Comment by MouhamedMokkhtar** [comment]
same error :
 Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.

**Comment by GouravNainwaya** [comment]
ReferenceError: Can't find variable: createMaterialTopTabNavigator
 ERROR  Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
 ERROR  Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.

me too same error

**Comment by jo780-full** [comment]
Atleast for me

**Comment by epickclient** [comment]
me too

**Comment by viniciussantos45** [comment]
How to solve it? :(

**Comment by Jmzp** [comment]
I have the same error

**Comment by dinesh-brilworks** [comment]
I am getting this error after upgrading to expo 47 from expo 45.

**Comment by UmarAbdullahi** [comment]
I have the same error. Any update on how to go around it?

**Comment by zeerakminecraft** [comment]
`
 ERROR  TypeError: undefined is not a function, js engine: hermes
 ERROR  Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 10): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient.
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes
 ERROR  Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 10): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient.
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes`

Any solutions to this? Kindly help

**Comment by zeerakminecraft** [comment]
ERROR  TypeError: undefined is not a function, js engine: hermes
 ERROR  Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 10): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient.
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes
 ERROR  Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 10): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient.
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes
        
        
        Getting this error after build successful and I am getting a blank white screen

**Comment by Jmzp** [comment]
On my side, this error was caused by an incompatible library, check your third-party libraries and if they are compatible with this React Native version.

**Comment by zeerakminecraft** [comment]
> ERROR TypeError: undefined is not a function, js engine: hermes ERROR Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 10): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient. A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes ERROR Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 10): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient. A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes
> 
> npx react-native info
> 
> ` System: OS: macOS 13.0.1 CPU: (8) arm64 Apple M1 Memory: 102.00 MB / 8.00 GB Shell: 5.8.1 - /bin/zsh Binaries: Node: 18.12.1 - /usr/local/bin/node Yarn: Not Found npm: 8.19.2 - /usr/local/bin/npm Watchman: 2022.11.14.00 - /usr/local/bin/watchman Managers: CocoaPods: 1.11.3 - /Users/syedafzal/.rbenv/shims/pod SDKs: iOS SDK: Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1 Android SDK: Not Found IDEs: Android Studio: Not Found Xcode: 14.1/14B47b - /usr/bin/xcodebuild Languages: Java: Not Found npmPackages: @react-native-community/cli: Not Found react: 18.1.0 => 18.1.0 react-native: 0.70.6 => 0.70.6 react-native-macos: Not Found npmGlobalPackages: *react-native*: Not Found`
> 
> Getting this error after build successful and I am getting a blank white screen on the simulator

So update on this. I made a new project and started copying components one by one from that project to this one and was running:

`react-native run-ios`

It was giving some minute syntax errors which I was fixing right away.  
It was working fine until, after installing react-native-i18n ^2.0.15 dependency, I did:

`react-native start --reset-cache`

and then when I did react-native run-ios this error showed up again. I think this error comes after react-native start --reset-cache command.

Does anyone know how undo "react-native start --reset-cache" or reinstall cache? 😅

**Comment by talesborn** [comment]
I have the same issue

**Comment by tobalo** [comment]
Experiencing same error as title, heres my package.json

```
"dependencies": {
    "@react-native-async-storage/async-storage": "^1.17.11",
    "@react-native-community/datetimepicker": "^6.6.0",
    "@react-native-community/slider": "^4.3.3",
    "@react-navigation/bottom-tabs": "^6.4.0",
    "@react-navigation/drawer": "^6.5.0",
    "@react-navigation/native": "^6.0.13",
    "@react-navigation/native-stack": "^6.9.1",
    "@tryghost/content-api": "^1.11.4",
    "axios": "^1.1.3",
    "babel-plugin-root-import": "^6.6.0",
    "deprecated-react-native-prop-types": "^2.3.0",
    "expo": "~47.0.3",
    "expo-device": "^5.0.0",
    "expo-linking": "^3.2.3",
    "expo-notifications": "^0.17.0",
    "expo-status-bar": "~1.4.2",
    "patch-package": "^6.5.0",
    "react": "18.1.0",
    "react-native": "0.70.5",
    "react-native-gesture-handler": "~2.8.0",
    "react-native-htmlview": "^0.16.0",
    "react-native-modal-selector": "^2.1.2",
    "react-native-paper": "^4.12.5",
    "react-native-reanimated": "~2.12.0",
    "react-native-safe-area-context": "4.4.1",
    "react-native-screens": "~3.18.0",
    "react-native-svg": "^13.5.0",
    "react-native-svg-charts": "^5.4.0",
    "react-native-swipe-list-view": "^3.2.9",
    "react-native-vector-icons": "^9.2.0",
    "react-table": "7.8.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9"
  },
```

**Comment by zeerakminecraft** [comment]
SyncStorage dependency was causing it in my case so i have commented it. So far its working

**Comment by kelset** [comment]
this seems to be an Expo specific problem, please open an issue there -> https://github.com/expo/expo

**Comment by ahmedyounes** [comment]
I have the same error and im not using expo 

System:
    OS: macOS 12.6.2
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 18.98 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - /usr/local/opt/node@18/bin/node
    Yarn: 1.22.19 - ~/dev/familyway/familyway-mob/node_modules/.bin/yarn
    npm: 8.19.2 - /usr/local/opt/node@18/bin/npm
    Watchman: 2022.11.14.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.5 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: ^0.70.5 => 0.70.6
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by error-try-again** [comment]
I get this error a lot, and haven't been able to diagnose what causes it exactly. It often occurs when I make a breaking change in code, the compiler spits out a warning, I correct the code and then reload the app. My quickfix is to just run `react-native start --reset-cache` which seems to fix it temporarily at least.

**Comment by jo780-full** [comment]
there must be some node module..that is not installed correctly
I initially got this error but if you do read it there always used to be some other error associated with this error, like sometimes the,
name of the module is wrong, or you not rendering correctly..in case it is just this error
the solution that works for me is to delete package-lock.json and node modules and run
`yarn install` or `npm install` ..if the problem still check you're code

**Comment by DFRZ7** [comment]
Hi, did anyone manage to solve this, I'm still getting this error in iOS. Thank you.

**Comment by developeromI89** [comment]
> Experiencing same error as title, heres my package.json
> 
> ```
> "dependencies": {
>     "@react-native-async-storage/async-storage": "^1.17.11",
>     "@react-native-community/datetimepicker": "^6.6.0",
>     "@react-native-community/slider": "^4.3.3",
>     "@react-navigation/bottom-tabs": "^6.4.0",
>     "@react-navigation/drawer": "^6.5.0",
>     "@react-navigation/native": "^6.0.13",
>     "@react-navigation/native-stack": "^6.9.1",
>     "@tryghost/content-api": "^1.11.4",
>     "axios": "^1.1.3",
>     "babel-plugin-root-import": "^6.6.0",
>     "deprecated-react-native-prop-types": "^2.3.0",
>     "expo": "~47.0.3",
>     "expo-device": "^5.0.0",
>     "expo-linking": "^3.2.3",
>     "expo-notifications": "^0.17.0",
>     "expo-status-bar": "~1.4.2",
>     "patch-package": "^6.5.0",
>     "react": "18.1.0",
>     "react-native": "0.70.5",
>     "react-native-gesture-handler": "~2.8.0",
>     "react-native-htmlview": "^0.16.0",
>     "react-native-modal-selector": "^2.1.2",
>     "react-native-paper": "^4.12.5",
>     "react-native-reanimated": "~2.12.0",
>     "react-native-safe-area-context": "4.4.1",
>     "react-native-screens": "~3.18.0",
>     "react-native-svg": "^13.5.0",
>     "react-native-svg-charts": "^5.4.0",
>     "react-native-swipe-list-view": "^3.2.9",
>     "react-native-vector-icons": "^9.2.0",
>     "react-table": "7.8.0"
>   },
>   "devDependencies": {
>     "@babel/core": "^7.12.9"
>   },
> ```

have you got chance to resolve it  . I am facing same issu

**Comment by developeromI89** [comment]
> I have the same issue
> 
> `Error: No Firebase App '[DEFAULT]' has been created - call firebase.initializeApp(), js engine: hermes ERROR Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter. A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes ERROR Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter. A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes`

Getting same for crashlytics. I am able  to import it but can not try a single function,
