### ISSUE TITLE
The android device show "App isn't installed" after upgrade React Native 0.70.5

### ISSUE THREAD

**Issue by tomcheung1208** [facebook/react-native#35417]
### Description

I upgraded my react-native project from 0.69.6 to 0.70.5

I run "npx react-native run-android" on my android device. It show "App isn't installed" when I click the app. If I go to device settings -> my app -> click "OPEN" button, then the app can run successfully. I can see the loading in bundle.

I have added applicationIdSuffix on android/app/build.grade. This setup always used.
`
buildTypes {
  debug: {
    applicationIdSuffix ".dev"
  }
}
`

My AndroidManifest package is "com.companyname.xxxx.android"

May I know how to solve this issue? Thank you everyone.

### Version

0.70.5

### Output of `npx react-native info`

System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M2
    Memory: 140.28 MB / 24.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.0 - /usr/local/bin/node
    Yarn: 1.19.2 - /usr/local/bin/yarn
    npm: 8.1.0 - /usr/local/bin/npm
    Watchman: 2022.09.05.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/cheungtom/.rubies/ruby-3.1.2/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.5 => 0.70.5
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. npx react-native run-android
2. install the dev app to my android device
3. click the dev app
4. show "App isn't installed"
5. go to device settings -> my dev app -> click "OPEN" button
6. it can open successfully, I can see the loading in bundle

### Snack, code example, screenshot, or link to a repository

android/app/build.grade
`
buildTypes {
  debug: {
    applicationIdSuffix ".dev"
  }
}
`

**Comment by tomcheung1208** [comment]
Anyone can help?
I built a standalone app, the app still show App isn't installed when I open the app

**Comment by MisterGoodDeal** [comment]
Same problem here

```
System:
    OS: macOS 13.0
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 73.67 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.17.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.0 => 0.64.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by Kenrik** [comment]
Also have this issue been fighting with it for a day. Clearly someone needs to look into this ASAP.

**Comment by Kenrik** [comment]
I'll leave another comment here for those who follow. 

In my case the splash screen had `exported="false" ` for the API 31 transition. 

**However!**

The splash screen activity must have `exported="true"`

Simple stupid bug.

**Comment by MisterGoodDeal** [comment]
> I'll leave another comment here for those who follow.
> 
> In my case the splash screen had `exported="false" ` for the API 31 transition.
> 
> **However!**
> 
> The splash screen activity must have `exported="true"`
> 
> Simple stupid bug.

Yes! That fixed my issue too 🙌

**Comment by shayanfarshad** [comment]
> exported="true"

where is the exported props ? on which file ?

**Comment by MisterGoodDeal** [comment]
@shayanfarshad It's in  the file `android/app/src/main/AndroidManifest.xml`

Then you need to add `android:exported="true"` in the `<activity>` tag:

```xml
<activity 
    android:name=".MainActivity" 
    android:label="@string/app_name"
    android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode" 
    android:launchMode="singleTask"
    android:windowSoftInputMode="adjustResize" 
    android:theme="@style/Theme.App.SplashScreen"
    android:screenOrientation="portrait" 
    android:exported="true">
    [...]
</activity>
```
