### ISSUE TITLE
fmt/core.h' file not found in xcode 13 

### ISSUE THREAD

**Issue by vaish8529** [facebook/react-native#35421]
### Description

I am running react native project in xcode 13 but it gives me flipper/folly, 'fmt/core.h' file not found error in socketaddress .cpp file.

### Version

0.63.3

### Output of `npx react-native info`

System:

OS: masOs 12.6
cpu arm64 apple m1 pro

### Steps to reproduce

In xcode Product-> Build

### Snack, code example, screenshot, or link to a repository

In xcode Product-> Build

**Comment by cortinico** [comment]
Closing as issue it's incomplete, on a too older version of React native.
