### ISSUE TITLE
Need to reload app when forcing rtl.

### ISSUE THREAD

**Issue by HodayaGruz** [facebook/react-native#35420]
### Description

i need to support Hebrew and english in my app,
that is mean rtl + ltr (depends on the user selection)
according to what i see i must reload my app in order to do this on runtime
its very very bad ux
threre is another solution or workaround without changing all my app? 

### Version

0.69.3

### Output of `npx react-native info`

  OS: macOS 13.0
    CPU: (8) arm64 Apple M1 Pro
    Memory: 537.06 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 8.11.0 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8815526
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.3 => 0.69.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

none

### Snack, code example, screenshot, or link to a repository

none

**Comment by b0iq** [comment]
You could present loading overlay with nice animation on top of your app by native code.

Changing language specially direction is tricky for the OS even on iOS or Android they need to recreate all the views.

**Comment by HodayaGruz** [comment]
ye, but what if i need t ave the selected language in my storage and load it with the selected one (with the correct direction)
