### ISSUE TITLE
How to detect Memory leaks in react native apps? Does leak canary really helpful to detect memory leaks in js code.

### ISSUE THREAD

**Issue by vinodkuumar** [facebook/react-native#35427]
### Description

In my application, iam facing many ANR'S and Out of Memory errors (OOM). so i thought memory leaks are happening in my application.So, I have integrated LeakCanary tool but it is detecting only android native side memory leaks only.
iam not able to find js memory leaks. so please tell me is there any way to detect Javascript code memory leaks.
Note:- I have used memory tab in chrome developer tools also, but it is not that much clear. so suggest me any tool or any other approach to detect memory leaks in my application.

### Version

0..65.2

### Output of `npx react-native info`

System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 693.51 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 16.18.1 - /usr/local/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 2.15.12 - ~/node_modules/.bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.5.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK: Not Found
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7678000
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.65.2 => 0.65.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

no steps

### Snack, code example, screenshot, or link to a repository

not available

**Comment by sampathkumarch** [comment]
@vinodkuumar can you solved the above problem am also facing same problem , how can I track  the leaks
