### ISSUE TITLE
Overscroll not working on Android

### ISSUE THREAD

**Issue by KrisLau** [facebook/react-native#35424]
### Description

I'm using `onScrollEndDrag` to decide when to collapse the header but on android, the overscroll doesn't seem to work so when the scroll view is empty or not more than the size of the screen so I can't trigger the the `onScrollEndDrag`.

So far I've tried adding `<item name="android:overScrollMode">always</item>` to the values.xml and also `overscrollMode={'always'}` to the `ScrollView`. For the relevant `SectionList` components I also tried adding  `scrollToOverflowEnabled={true}`. None of those worked. 

I also tried to use an Android 12 to see if it was caused by the os version but nothing seemed to change

Similar to:

- #27466 (opened by @ospfranco)
- #16144 (opened by @Symous)
- #18857 (opened by @mannok)

### Version

0.70.6

### Output of `npx react-native info`

```
System:
    OS: macOS 12.6.1
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Memory: 189.70 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.1 - /usr/local/bin/node
    Yarn: 1.22.18 - ~/.yarn/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
    Watchman: 2022.11.14.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 31, 33
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0
      System Images: android-30 | Google Play Intel x86 Atom, android-31 | Intel x86 Atom_64, android-31 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.12 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^18.2.0 => 18.2.0 
    react-native: ^0.70.6 => 0.70.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1. Create a `ScrollView` with not enough items to fill up the screen.
2. Try to scroll on it in IOS. Notice that it allows you to pull to the overflow.
3. Try on Android. Notice you can't overscroll.

### Snack, code example, screenshot, or link to a repository

https://snack.expo.dev/@kris_lau/android-overflow?platform=android

Notice that `onScrollEndDrag` is not triggered on android

**Comment by KrisLau** [comment]
Similar to:

- #27466 (opened by @ospfranco)

**Comment by KrisLau** [comment]
@ishigamii Did you ever figure it out? I noticed you left a comment on one of the similar issues

**Comment by rahulnikam2002** [comment]
Any updates on this?

**Comment by faljabi** [comment]
Any update on this?

**Comment by mysticmew7** [comment]
Same use case. This issue seems to be 8 years old.
https://github.com/facebook/react-native/issues/16144

Let's check back in 5 years, hopefully it's fixed by then.
