### ISSUE TITLE
main.jsbundle does not exist.

### ISSUE THREAD

**Issue by GKyomen** [facebook/react-native#35422]
### Description

Using expo, but can't build correctly, with fastlane error. Tried all sorts of things, none helped. Had an open issue at expo, but they closed without much help.
Fastlane logs:
[bb2373b4-a0f4-4e9b-968c-0d38a6a26516-run-fastlane.txt](https://github.com/facebook/react-native/files/10058047/bb2373b4-a0f4-4e9b-968c-0d38a6a26516-run-fastlane.txt)
Any ideas?

### Version

70.0 (expo 47)

### Output of `npx react-native info`

System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
    Memory: 10.05 GB / 15.54 GB
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.18.1/bin/yarn
    npm: 9.1.1 - ~/.nvm/versions/node/v16.18.1/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.5 => 0.70.5 
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

On a terminal, use:
expo init   /*Make sure to use v47*/
Use the dependencies in this package.json:
[package json.txt](https://github.com/facebook/react-native/files/10058078/package.json.txt)
install pods, etc.
configure eas (base config)
use "eas build -p ios"

### Snack, code example, screenshot, or link to a repository

https://snack.expo.dev/@gkyomen/fastlane-bug

**Comment by brentvatne** [comment]
hi there! I don't see an issue about this particular topic on the expo repo, I only see this unrelated question: https://github.com/expo/expo/issues/20005

see this related comment: https://github.com/expo/expo/issues/20001#issuecomment-1320922419

if the issue persists, please create a new issue on https://github.com/expo/expo/issues with a minimal reproducible example

**Comment by richyk1** [comment]
@GKyomen Hi there! Did you manage to solve this issue? I'm stuck

**Comment by savithrielangovan** [comment]
i am also stuck
