### ISSUE TITLE
Using both scrollEventThrottle and stickyHeaderIndices not working

### ISSUE THREAD

**Issue by anatoleblanc** [facebook/react-native#35446]
### Description

When using both attributes, onScroll function gets triggered multiple times, event when setting scrollEventThrottle={0}. 

### Version

0.68.2

### Output of `npx react-native info`

System:
    OS: macOS 12.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 2.06 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.11.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - /opt/homebrew/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.2 => 0.68.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
npm notice 
npm notice New major version of npm available! 8.19.2 -> 9.1.2
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.1.2
npm notice Run npm install -g npm@9.1.2 to update!
npm notice 

### Steps to reproduce

Just use the simple code provided below inside an App.js

### Snack, code example, screenshot, or link to a repository

````
<ScrollView
      contentContainerStyle={{ marginHorizontal: 20 }}
      onScroll={async ({ nativeEvent }) => {
        if (isCloseToBottom(nativeEvent)) {
          await setLoading(true);
          console.log("jai setloading");
          await leaderboard.fetchMore({
            variables: {
              offset: leaderboard.data.getLeaderboard2.generalRanking.length,
            },
          });
          console.log("jai fetch de la data");
          await setLoading(false);
        }
      }}
      stickyHeaderIndices={[1]}
      scrollEventThrottle={0}
    >
<FlatList
      renderItem={renderItem}
      data={leaderboard.data.getLeaderboard2.generalRanking.slice(3)}
      scrollEnabled={false}
    />
</ScrollView>

```

**Comment by Quintis1212** [comment]
For it works , without your onScroll function, maybe it is the cause
