### ISSUE TITLE
ScrollView React Native Horizontal Not Working

### ISSUE THREAD

**Issue by imanuelvic** [facebook/react-native#35440]
### Description

I am developing app with RN 0.69.6. I am trying to create scrollable view horizontally with ScrollView.

In IOS is work, but android doesn't work.

Here is basis of my code (sorry I couldn't share more detail):

### Version

0.69.6

### Output of `npx react-native info`

System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    Memory: 1.95 GB / 11.85 GB
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.17.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: Not Found
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0
    react-native: 0.69.6 => 0.69.6
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Cant scroll horizontally

### Snack, code example, screenshot, or link to a repository

```
renderHighlightVideoBanner = (banners) => {
    return (
      <View style={styles.highlightOverflowContainer}>
        <View style={styles.groupTitleContainer}>
          <AdjustableText additionalStyle={styles.headerLabel}>What To Watch</AdjustableText>
        </View>
        <ScrollView
          horizontal
          showsHorizontalScrollIndicator={false}
          contentContainerStyle={styles.horizontalScrollViewContainer}
        >
          {banners.data.map((value) => {
            return (
              <View style={styles.container}>
                <TouchableOpacity
                  style={styles.touchableHighlightSliderContainer}
                  onPress={() => this.navigateToVideoScreen(value)}
                >
                  <Image
                    resizeMode="cover"
                    style={styles.sliderImage}
                    source={{ uri: value.file_path + value.file_name }}
                  />
                </TouchableOpacity>
                <View style={styles.highlightTitleLabelContainer}>
                  <AdjustableText heading="label" additionalStyle={styles.headerLabel}>{value.title}</AdjustableText>
                  <AdjustableText heading="label">{value.subtitle}</AdjustableText>
                </View>
              </View>
            )
          })}
        </ScrollView>
      </View>
    )
  }
```

**Comment by kehobert** [comment]
Having the same issue as well

**Comment by soo9028** [comment]
same for me...

**Comment by actaruss** [comment]
> > same for me..., did anyone ever get around to fixing this bug?
> 
> is your ScrollView imported from react-native or react-native-gesture-handler? if you are using react-native try changing to react-native-gesture-handler and see if it works!

incredible, you saved my day. Why the react-native ScrollView doesn't work correctly on android? 😮

**Comment by kimjisena** [comment]
> > same for me..., did anyone ever get around to fixing this bug?
> 
> is your ScrollView imported from react-native or react-native-gesture-handler? if you are using react-native try changing to react-native-gesture-handler and see if it works!

This worked for me, thanks.
