### ISSUE TITLE
Error while evaluating property 'extraGeneratedResDir' of task ':app:mapReleaseSourceSetPaths'

### ISSUE THREAD

**Issue by rafaelbrunoss** [facebook/react-native#35447]
### Description

I tried to create a new project using react-native

```bash
npx react-native init Navigator --template react-native-template-typescript
```

After that, I tried to create the production files for Android using the command

```bash
cd android && ./gradlew assembleRelease
```

And it worked. But when I try to add some configuration to the initial project, the build starts to throw some errors. One of them I was able to solve executing

```bash
mkdir android/app/src/main/assets && react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
```

But then, for some reason, if I try to create the bundle again I get the error

```
error index.js: Import statement may only appear at top level in file index.js at 4:2.
Error: Import statement may only appear at top level in file index.js at 4:2
    at minifyCode (/home/rafael/Documents/Library/react-native-error/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro-transform-worker/src/index.js:99:13)
```

Using the last bundle file and then modifying the build command to

```bash
cd android && ./gradlew assembleRelease -x bundleReleaseJsAndAssets
```

I keep getting this error

```
Execution failed for task ':app:mapReleaseSourceSetPaths'.
> Error while evaluating property 'extraGeneratedResDir' of task ':app:mapReleaseSourceSetPaths'
   > Failed to calculate the value of task ':app:mapReleaseSourceSetPaths' property 'extraGeneratedResDir'.
      > Querying the mapped value of provider(java.util.Set) before task ':app:bundleReleaseJsAndAssets' has completed is not supported
```

### Version

0.70.6

### Output of `npx react-native info`

System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Memory: 3.13 GB / 31.17 GB
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 18.9.0 - ~/.asdf/installs/nodejs/18.9.0/bin/node
    Yarn: Not Found
    npm: 8.19.1 - ~/.asdf/plugins/nodejs/shims/npm
    Watchman: 20220924.070135.0 - /usr/local/bin/watchman
  SDKs:
    Android SDK:
      API Levels: 30, 31, 32, 33
      Build Tools: 30.0.3, 31.0.0, 33.0.0
      System Images: android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.6 => 0.70.6 
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

clone the project on this repository: https://github.com/rafaelbrunoss/react-native-error

run

```bash
npm install
npm run fix:bundle
npm run build:prod:android
```

### Snack, code example, screenshot, or link to a repository

You can find the project in this repository:

https://github.com/rafaelbrunoss/react-native-error

**Comment by cortinico** [comment]
> After that, I tried to create the production files for Android using the command

Is there a reason why you're not using?

```
npx react-native run-android --variant=release
```

**Comment by rafaelbrunoss** [comment]
> 

Not particularly. But it also gives me the same error

**Comment by cortinico** [comment]
Could you share the full build log?

**Comment by rafaelbrunoss** [comment]
I think I found the solution. It seems that the devDependency "react-native-gradle-plugin": "0.72.0" somehow messes with the build process. After I removed that, the build was successful.

Thank you all for trying to help me!

**Comment by cortinico** [comment]
> It seems that the devDependency "react-native-gradle-plugin": "0.72.0" somehow messes with the build process. After I removed that, the build was successful.

Why you had a devDependency on `"react-native-gradle-plugin": "0.72.0"`?
Was it inside your `package.json`?

Anyway I'm closing as resolved

**Comment by cortinico** [comment]
> @cortinico issue is related with react-navigation 's drawable icons clean drawable folders from android folder then ./gradlew clean fixed this issue.

Thanks for clarifying

> but I want to ask some different issue

Please refrain from highjacking other issues and open a new one, provide a reproducer, and we can look into it.

**Comment by GouravNainwaya** [comment]
> @cortinico issue is related with react-navigation 's drawable icons clean drawable folders from android folder then ./gradlew clean fixed this issue.
> 
> but I want to ask some different issue
> 
> ```
> > Task :app:signReleaseBundle FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:signReleaseBundle'.
> > A failure occurred while executing com.android.build.gradle.internal.tasks.FinalizeBundleTask$BundleToolRunnable
>    > java.lang.NullPointerException (no error message)
> 
> * Try:
> > Run with --stacktrace option to get the stack trace.
> > Run with --info or --debug option to get more log output.
> > Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
> 
> You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
> 
> See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings
> 
> Execution optimizations have been disabled for 11 invalid unit(s) of work during this build to ensure correctness.
> Please consult deprecation warnings for more details.
> 
> BUILD FAILED in 44s
> 522 actionable tasks: 14 executed, 508 up-to-date
> ```
> 
> release building is crashing in %99 did you faced with this

this issue same i have facing now time. anybody who can help

**Comment by gigby** [comment]
I got the same issue when upgraded Gradle and was preparing an Android build for release for SDK 33.
RN0.68.
To fix this I updated `classpath 'com.google.gms:google-services:4.3.14'`

Other settings:
buildToolsVersion = "31.0.0"
        minSdkVersion = 21
        compileSdkVersion = 33
        targetSdkVersion = 33
distributionUrl=https\://services.gradle.org/distributions/gradle-7.5.1-all.zip
classpath("com.android.tools.build:gradle:7.3.1")
