### ISSUE TITLE
Linking.addEventListener is not firing for app is background or foreground - IOS

### ISSUE THREAD

**Issue by Shridhar-CN** [facebook/react-native#35452]
### Description

this is my Hook implementation.

useEffect(() => {
    const subscription = Linking.addEventListener('url', (event) => {
      console.log("inside listener");
      let route = event.url?.replace(/.*?:\/\//g, "");
      deepLinkData = route?.split('&');
      if (deepLinkData.length) {
        fetchToken();
      }
    });

    prefix = Linking.getInitialURL().then((url) => {
      let route = url?.replace(/.*?:\/\//g, "");
      deepLinkData = route?.split('&');
      if (deepLinkData.length) {
        fetchToken();
      }
    }).catch(err => {
      return err;
    });

    closeActivityIndicator();
    return () => {
      subscription.remove();
    };

  },[]);
  
  
  and these are app delegate entries 
  //at the top
  #import <React/RCTLinkingManager.h>
  
// Add these inside `@implementation AppDelegate` above `@end`:
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url
  sourceApplication:(NSString *)sourceApplication annotation:(id)annotation
{
  return [RCTLinkingManager application:application openURL:url
                      sourceApplication:sourceApplication annotation:annotation];
}

- (BOOL)application:(UIApplication *)application
   openURL:(NSURL *)url
   options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{
  return [RCTLinkingManager application:application openURL:url options:options];
}

- (BOOL)application:(UIApplication *)application continueUserActivity:(nonnull NSUserActivity *)userActivity
 restorationHandler:(nonnull void (^)(NSArray<id<UIUserActivityRestoring>> * _Nullable))restorationHandler
{
 return [RCTLinkingManager application:application
                  continueUserActivity:userActivity
                    restorationHandler:restorationHandler];
}

### Version

0.69.3

### Output of `npx react-native info`

npx react-native info
info Fetching system and libraries information...
System:
    OS: macOS 12.6
    CPU: (8) x64 Apple M1
    Memory: 21.48 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.18.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 6.14.15 - /usr/local/bin/npm
    Watchman: 2022.11.07.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8815526
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 16.0.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.3 => 0.69.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

When the app is quit state: 

entered the Deeplink URL in mobile browser(safari) and the same was captured **Linking.getInitialURL()**

but when the app is open and entered the Deeplink URL in mobile browser(safari), app comes to foreground but 
url is not captured at all.

neither in **Linking.getInitialURL()** nor in **Linking.addEventListener('url', (event)** 

Note: I have added URL Scheme in xcode under URL types and this issue is not for universal link but deeplink.

### Snack, code example, screenshot, or link to a repository

<img width="621" alt="image" src="https://user-images.githubusercontent.com/118957941/203709624-3ce32b3a-6934-4069-93b1-dae4b791257b.png">

**Comment by leoparis89** [comment]
Were you able to solve the issue ?
On my side event does not fire if app is open or in background.

**Comment by Shridhar-CN** [comment]
> Were you able to solve the issue ? On my side event does not fire if app is open or in background.

Yes I was able to solve it.
For you is it working when app is in quit state at least?

**Comment by leoparis89** [comment]
> > Were you able to solve the issue ? On my side event does not fire if app is open or in background.
> 
> Yes I was able to solve it. For you is it working when app is in quit state at least?

- Url event fires when app was closed.
- Url event doesn't doesn't fire when app was in background.

Does it fire for you if app was in background ?

**Comment by Shridhar-CN** [comment]
yes, it does fire for me.

make sure the below import is at the top in app delegate 
#import <React/RCTLinkingManager.h>

and then these changes below

<img width="824" alt="image" src="https://user-images.githubusercontent.com/118957941/208658097-ecaed05a-963f-4a3f-ae8e-b5a4a8597556.png">

do a pod install , 
then build/launch the app.

**Comment by leoparis89** [comment]
Had already done all that and it still doesn't work.

**Comment by leoparis89** [comment]
Can you reproduce the bug with this repo ?
https://github.com/leoparis89/deeplink

**Comment by Shridhar-CN** [comment]
> Had already done all that and it still doesn't work.

There you go..  once you merge these changes you should be good

https://github.com/leoparis89/deeplink/pull/1
