### ISSUE TITLE
Clear AsyncStorage between integration tests

### ISSUE THREAD

**Issue by eapache** [facebook/react-native#3547]
We have some integration tests which, as side-effects, end up writing some state to AsyncStorage. This means that these tests can only be run once: on subsequent runs they pick up the existing state from the previous run and fail in interesting ways.

Ideally RN would automatically clear the AsyncStorage between each test, or at least export a synchronous function we could call in our `setup` method, but I haven't found *anything* we can use for this. All of the AsyncStorage methods are (of course) asynchronous, and there doesn't appear to be a way to make them synchronous.

How do others handle this problem? Is there interest in exposing a method like this to Objective C-land?

cc @boourns @carsonb

**Comment by rt2zz** [comment]
I do not believe there is any practical way to make AsyncStorage calls synchronous as they have have to cross the bridge. If you want to purge the entire storage you can call `AsyncStorage.clear`. 

Mocha/Ava or pretty much any test runner have the ability to [run asynchronous tests serially](https://github.com/sindresorhus/ava#running-tests-serially) so while it may result in slightly more boilerplate I think what you are looking for is achievable using the current api.

**Comment by christopherdro** [comment]
@facebook-github-bot answered
