### ISSUE TITLE
DistributeApp Error react-native help

### ISSUE THREAD

**Issue by aekurt41** [facebook/react-native#35485]
### Description

Hello,
I am using react-native-tvos@0.69.6-0 version, I have developed my application, but I am getting such an error when submitting to Apple Store.
I created a blank project and archived it, but it has the same problem.

how can i solve this error? I need to solve it urgently.

![WhatsApp Görsel 2022-11-25 saat 22 03 32](https://user-images.githubusercontent.com/55325987/204044809-0894a868-8219-47c8-9744-b88dcf02b34b.jpg)

### Version

0.69.6-0

### Output of `npx react-native info`

System:
OS: macOS 12.6
CPU: (8) arm64 Apple M1
Memory: 275.02 MB / 16.00 GB
Shell: 5.8.1 - /bin/zsh
Binaries:
Node: 16.15.0 - /usr/local/bin/node
Yarn: 1.22.19 - /opt/homebrew/bin/yarn
npm: 8.19.3 - ~/Documents/GitHub/d7ksuper-tv-app/node_modules/.bin/npm
Watchman: Not Found
Managers:
CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
SDKs:
iOS SDK:
Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
Android SDK: Not Found
IDEs:
Android Studio: Not Found
Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
Languages:
Java: 11.0.12 - /usr/bin/javac
npmPackages:
@react-native-community/cli: Not Found
react: 18.0.0 => 18.0.0
react-native: Not Found
react-native-macos: Not Found
react-native-tvos: 0.69.6-0
npmGlobalPackages:
react-native: Not Found

### Steps to reproduce

Create new project in react-native-tvos@0.69.6-0.
install pods
xed from the ios folder. open in xcode
archive
distiribute app

### Snack, code example, screenshot, or link to a repository

I wantto fix
![WhatsApp Görsel 2022-11-25 saat 22 03 32](https://user-images.githubusercontent.com/55325987/204044937-8c798aa4-48b8-412f-9764-34e2a970349b.jpg)

**Comment by cortinico** [comment]
> I am using react-native-tvos@0.69.6-0 version, I have developed my application, but I am getting such an error when submitting to Apple Store.

Hi @aekurt41 
Thanks for reporting this issue.

As you're using `react-native-tvos` please open your issue against:
https://github.com/react-native-tvos/react-native-tvos

I'll be closing this but feel free to reopen if the other repo points back to us as a issue in the core of React Native.
