### ISSUE TITLE
"Debug JS Remotely option not seen on IOS simulator

### ISSUE THREAD

**Issue by rukna123** [facebook/react-native#35493]
### Description

I want to set breakpoint at various point in code. But even after installing the react-native-debugger and restarting simulator, i don't see "Debug JS Remotely" option which hampers my debugging. Kindly help.

### Version

0.68.2

### Output of `npx react-native info`

info Fetching system and libraries information...
(node:69634) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1
    Memory: 182.97 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.0 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 13.3/13E113 - /usr/bin/xcodebuild
  Languages:
    Java: 18.0.1 - /usr/local/opt/openjdk/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.2 => 0.68.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. Run any app in IOS simulator.
2. In simulator menu, go to Device>Shake. 
3. you will see debugging options, but no option of "Debug JS Remotely".

### Snack, code example, screenshot, or link to a repository

![Screenshot 2022-11-28 at 7 11 38 AM](https://user-images.githubusercontent.com/15629915/204174480-40583296-28cf-4532-a94c-2b1e02ffaeb8.jpeg)

**Comment by lovelytingy** [comment]
hi @rukna123, I tried and found that you already have enabled "Debug JS Remotely" this text has changed to "Debug with Chrome". Also you need to close the default tab open in chrome or your preferred browser by react native default debugger than you need to reload the bundle by pressing r in metro terminal.

Let me know if this solves your issue or not.

![Screenshot 2022-11-28 at 12 26 35 PM](https://user-images.githubusercontent.com/25694318/204213455-3f74d1b2-bbbf-494c-9151-162b8ee9041d.png)

**Comment by rukna123** [comment]
You're right Lovely, thanks for helping out!!
