### ISSUE TITLE
[Packager] Drop babel (the CLI tool) and use only babel-core

### ISSUE THREAD

**Issue by ide** [facebook/react-native#3549]
The babel package includes a bunch of CLI stuff we don't need.

https://github.com/facebook/react-native/commit/2608efccb6d81e2abc5571522455e641caf330ea is going to be reverted for operational reasons. Leaving a note here to remove babel again later.

**Comment by martinbigio** [comment]
Cool, this is something we'll hopefully fix internally sometime soon as it's been quite problematic lately. Thanks!

**Comment by ide** [comment]
cc @martinbigio could you look into this and upgrade babel-core while you're at it? Somehow people are installing a buggy version of Babel but the latest 5.x release is good.

**Comment by jsierles** [comment]
Closing this since babel was removed.
