### ISSUE TITLE
`codegenDir` property in library is ignoring the value set in the `app` project.

### ISSUE THREAD

**Issue by cortinico** [facebook/react-native#35495]
@cortinico when you set the `codegenDir` property in the `react{}` block in the app's `build.gradle` it doesn't propagate to the third-party libraries. What I believe is happening is when a library applies `com.facebook.react` plugin in its `build.gradle` the plugin is using the default values for all the properties, even if some are set in the `app` project.

_Originally posted by @j-piasecki in https://github.com/facebook/react-native/issues/34372#issuecomment-1328668024_

**Comment by cortinico** [comment]
@j-piasecki we're going to pick the fix for this inside the next 0.71.x release

**Comment by smaslenko** [comment]
**The `codegenDir` property in the `react{}` block in the lib's build.gradle**


Still cannot build my react-native android project that is android library itself.

It looks like the same fix has to be applied for the ["com.android.library" section](https://github.com/facebook/react-native/commit/de512cd127dfa1d70b94344da65589492e0cbc14#diff-9ca1c97a718be1da688e30713ea3ec0cfd490a14eade4e61ceb98ef93ad04055R95
)

@cortinico Could you please take a look at my comment [here](https://github.com/facebook/react-native/commit/de512cd127dfa1d70b94344da65589492e0cbc14#r106094721)

Or should I create a separate issue instead?
Thanks.

**Comment by cortinico** [comment]
> The `codegenDir` property in the `react{}` block in the lib's `build.gradle` is ignored.

That's the intended behavior. `codegenDir` is set at the app level and ignored for libraries, as if you're inside a monorepo you have only one instance of codegen, and you don't want libraries to publish a `build.gradle` which contains a path to a codegen that doesn't make sense in your app setup.

**Comment by smaslenko** [comment]
> > The `codegenDir` property in the `react{}` block in the lib's `build.gradle` is ignored.
> 
> That's the intended behavior. `codegenDir` is set at the app level and ignored for libraries, as if you're inside a monorepo you have only one instance of codegen, and you don't want libraries to publish a `build.gradle` which contains a path to a codegen that doesn't make sense in your app setup.

Makes sense.

Then what would you suggest for the following scenario:
1. My ReactNative project is distributed as AAR (i.e. it's android library in gradle)
2. My ReactNative project resides in monorepo structure 

```
-Repo
  -package.json 
  -node_modules
  -app_1 
     ["com.android.library"] 
  -app_2 ["com.android.library"]
     ["com.android.library"]
        ....
  -app_N
     ["com.android.library"]
```

Thus, each of `app` can't access top-level shared `codegenDir`


Thanks.

**Comment by smaslenko** [comment]
> > The `codegenDir` property in the `react{}` block in the lib's `build.gradle` is ignored.
> 
> That's the intended behavior. `codegenDir` is set at the app level and ignored for libraries, as if you're inside a monorepo you have only one instance of codegen, and you don't want libraries to publish a `build.gradle` which contains a path to a codegen that doesn't make sense in your app setup.

Makes sense.

Then what would you suggest for the following scenario:
1. My ReactNative project is distributed as AAR (i.e. it's android library in gradle) into existing native app
2. My ReactNative project resides in monorepo structure 

```
-Repo
  -package.json 
  -node_modules
  -app_1 
     ["com.android.library"] 
  -app_2 ["com.android.library"]
     ["com.android.library"]
        ....
  -app_N
     ["com.android.library"]
```

Thus, each of `app` can't access top-level shared `codegenDir`


Thanks.

**Comment by smaslenko** [comment]
@cortinico 

Is there any chance that overwritten `codegenDir` path will also work for android-library monorepo projects?

Thanks.

**Comment by cortinico** [comment]
> My ReactNative project resides in monorepo structure

Sorry but I don't understand your setup. You have several `app_1`, `app_2`, etc. but they're applying `"com.android.library"` which seems wrong (they should apply `"com.android.application"`.

The current setup works for monorepo where you have multiple apps and libraries as long as you have only one copy of the codegen.

**Comment by smaslenko** [comment]
> > My ReactNative project resides in monorepo structure
> 
> Sorry but I don't understand your setup. You have several `app_1`, `app_2`, etc. but they're applying `"com.android.library"` which seems wrong (they should apply `"com.android.application"`.
> 
> The current setup works for monorepo where you have multiple apps and libraries as long as you have only one copy of the codegen.

The point here is that all the react-native `app_1` `app_2` etc are then published to Maven artifactory and finally are fetched by the native host android app (hybrid) in production.

In other words there is no `"com.android.application"` components in my react-native complex project repo, but only the bunch of distributable libs (or let's say "sdks"). And all of those libs are referring to the single shared `node-modules` location.

I hope it's more clear now.

Thanks.

**Comment by cortinico** [comment]
> The codegenDir is set in a top-level build.gradle in every app_1 app_2 ..., like this:

This should work correctly as you're configuring the same value for all the projects

**Comment by smaslenko** [comment]
> > The codegenDir is set in a top-level build.gradle in every app_1 app_2 ..., like this:
> 
> This should work correctly as you're configuring the same value for all the projects

Unfortunately it works incorrectly because in my project structure "all the projects" (i.e. underlying gradle modules) are `"com.android.library"` that your `codegenDir` fix is not applied for.

**Comment by cortinico** [comment]
> Unfortunately it works incorrectly because in my project structure "all the projects" (i.e. underlying gradle modules) are `"com.android.library"` that your `codegenDir` fix is not applied for.

Can you create a reproducer using this template https://github.com/react-native-community/reproducer-react-native/ to simulate your setup so I can better understand?

**Comment by smaslenko** [comment]
> > Unfortunately it works incorrectly because in my project structure "all the projects" (i.e. underlying gradle modules) are `"com.android.library"` that your `codegenDir` fix is not applied for.
> 
> Can you create a reproducer using this template https://github.com/react-native-community/reproducer-react-native/ to simulate your setup so I can better understand?

Sure. Here it is 
https://github.com/smaslenko/codegen-in-lib-repro

_(Please note, in real project there are multiple similar `"my-sdk", "my-another-sdk", ...` libraries reside inside enclosing repo)_

**STR1:**
```
$ cd my-sdk
$ npm run bundle-sdk // assemble js bundle
$ npm run publish-local-sdk // build AAR and publish it to local (or remote on demand) Maven
```
_OR_


**STR2:**
```
$ cd my-sdk/android
$ ./gradlew assembleDebug
```


**Actual Result:**
```
Execution failed for task ':app:buildCodegenCLI'.
> A problem occurred starting process 
'command '~/react/community/codegen-in-lib-repro/ReproducerApp/my-sdk/node_modules/@react-native/codegen/scripts/oss/build.sh''
```


**Expected Result:**
gradle build success, AAR is built in `app/build/outputs/aar`

-------------

The workaround I'm using so far is putting
`"@react-native/codegen": "^0.72.4"` dependency
inside `./my-sdk/package.json`. 
But I wouldn't like to keep one more extra codegen dependency while "default" one already exists in a shared top-level `node_modules`.

**Comment by cortinico** [comment]
> Sure. Here it is
> [smaslenko/codegen-in-lib-repro](https://github.com/smaslenko/codegen-in-lib-repro)

Thanks for sharing this.
The problem in your project is that you need at least one module that applies the `com.android.application` plugin. That's the assumption under which the React Gradle Plugin works. You can't just have a library module.

If you check tools like https://github.com/callstack/react-native-builder-bob/, they will always create a sample app to support those kind of scenarios.
