### ISSUE TITLE
0.67.5 - Android BigInt being NaN

### ISSUE THREAD

**Issue by khoanguyen-yang** [facebook/react-native#35504]
### Description

I tested using BigInt on Android `BigInt(1)` results in `NaN`.
On iOS it is working fine.

### Version

0.67.5

### Output of `npx react-native info`

```
System:
    OS: macOS 12.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 774.41 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
    Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 23, 29, 30, 31, 32
      Build Tools: 29.0.2, 30.0.2, 30.0.3, 32.0.0, 32.1.0
      System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play ARM 64 v8a, android-32 | Google APIs ARM 64 v8a
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8139111
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.67.5 => 0.67.5
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

Simply using BigInt on Android. No reproduce steps.

### Snack, code example, screenshot, or link to a repository

None

**Comment by cortinico** [comment]
> I tested using BigInt on Android `BigInt(1)` results in `NaN`.
> On iOS it is working fine.

Which JS Engine are you using? Hermes or JSC?

**Comment by khoanguyen-yang** [comment]
> Which JS Engine are you using? Hermes or JSC?

I am using JSC

**Comment by khoanguyen-yang** [comment]
> > Which JS Engine are you using? Hermes or JSC?
> 
> I am using JSC

Upgrade jsc-android to `294992.0.0` solves to problem. But the app bundle size increases significantly in variant=release (compare to `250230.2.1`)

**Comment by cortinico** [comment]
> But the app bundle size increases significantly in variant=release (compare to 250230.2.1) as we need to set def jscFlavor = 'org.webkit:android-jsc-intl:+' otherwise there will be error java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libjscexecutor.so caused by: dlopen failed: library "libjsc.so" not found.

Are you using flavors by any chance?

**Comment by khoanguyen-yang** [comment]
> Are you using flavors by any chance?

it is used here

<img width="494" alt="image" src="https://user-images.githubusercontent.com/84629610/204732634-bb0d322c-d87e-4e3c-85e3-cda2564b3828.png">

**Comment by cortinico** [comment]
> it is used here

I'm wondering if you're using Android flavors like `lite`, `full`, etc. to have different versions of your app. As those are a known issue of those kind of errors like `library "libjsc.so" not found`

What is happening in your app is that `libjsc.so` is stripped away so the app crashes at runtime as the engine is missing.

If you could create a minimal reproducer (i.e. empty project with JSC bumped to the version you're using) I could look into it and tell you if it's a bug inside React Native (and fix it) or a misconfig on your end.

**Comment by khoanguyen-yang** [comment]
> 'm wondering if you're using Android flavors like `lite`, `full`, etc. to have different versions of your app. As those are a known issue of those kind of errors like `library "libjsc.so" not found`

I am not using any of these flavors. Let me create a minimal reproducer then

**Comment by khoanguyen-yang** [comment]
> If you could create a minimal reproducer (i.e. empty project with JSC bumped to the version you're using) I could look into it and tell you if it's a bug inside React Native (and fix it) or a misconfig on your end.

Here is the reproducer repo: https://github.com/khoanguyen-yang/JscAndroidLibjsc

In `android/app/build.gradle`, if you use `def jscFlavor = 'org.webkit:android-jsc:+'` there will be `libjsc.so` error.
It will work with `def jscFlavor = 'org.webkit:android-jsc-intl:+'` but the app bundle size will significantly grow. This is not what I want, I just want to `BigInt` supports on Android.

It seems that I should rather ask the author of `jsc-android` though. But really appreciate if you have any advice.
Many thanks!

**Comment by cortinico** [comment]
> So it seems using `org.webkit:android-jsc-intl:+` for the latest JSC is a must.

Great thanks for clarifying.
@Kudo it seems like we need to update the template to remove the non-intl variant from it?

**Comment by Kudo** [comment]
yes, the Intl only is a breaking change from new jsc. that's why the new version is still `jsc-android@next` (not in latest dist-tag). since hermes is now acting as a default engine, i'm waiting a proper time when jsc-android is retired as a third-party package by lean core effort.
