### ISSUE TITLE
CocoaPods 0.39 breaks RN

### ISSUE THREAD

**Issue by nevir** [facebook/react-native#3550]
See https://github.com/CocoaPods/CocoaPods/pull/4057 - CocoaPods is no longer recursively expanding header paths. This breaks any code outside of RN that references its public headers, unfortunately. 

It's not clear to me what needs to change in RN's podspec to cause CocoaPods to expand out the search paths (but I'm not that deep into CocoaPods yet).

The CocoaPods folk are pushing for using qualified headers as the alternative (e.g. `#import <React/Base/RCTBridgeModule.h>`)

**Comment by ide** [comment]
@nevir, in 0.13-rc we got rid of `header_mappings_dir` in the podspec, which flattens all the public header files so they're in the same directory. Does that fix your issue?

**Comment by nevir** [comment]
Ah! It should. I won't be able to bump to that for a little while to test, though :(

**Comment by satya164** [comment]
Seems it's fixed. Let's reopen if that's not the case.
