### ISSUE TITLE
Trying to upgrade to support android 12 but getting - Unable to load script, make sure your bundle "index.android.bundle" is packaged correctly for release.

### ISSUE THREAD

**Issue by kapilraghuwanshi** [facebook/react-native#35501]
### New Version

0.66.5+

### Old Version

0.63.4 

### Build Target(s)

Android Emulator and release build as well

### Output of `react-native info`

System:
    OS: macOS 12.6.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 170.70 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 8.3.1 - /usr/local/bin/npm
    Watchman: 2022.10.03.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.2 - /Users/kapil.raghuwanshi/.sdkman/candidates/java/current/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 17.0.2 
    react-native: 0.63.4 => 0.66.5 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Issue and Reproduction Steps

We are trying to migrate our react native project in order to support android 12. 

https://reactnative.dev/blog/2021/09/01/preparing-your-app-for-iOS-15-and-android-12

We are struggling to resolve this issue past few days.

![screenshot](https://user-images.githubusercontent.com/38580123/204476440-3fcdee96-dc9d-4cb2-982f-d04c9e72bee6.png)
![screenshot](https://user-images.githubusercontent.com/38580123/204476466-d93331b1-b8f7-4b25-8d2e-a97005773ea1.png)

We searched on the internet
https://stackoverflow.com/questions/55441230/unable-to-load-script-make-sure-you-are-either-running-a-metro-server-or-that-yo/58570426#58570426

 and found a few solutions below:

1) `adb reverse tcp:8081 tcp:8081` 

2) setting port and host configs 

3) `react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res`

Out of which all are working fine in our local system and emulators 
but once we create a release build for the production environment, no luck with any of such hacks.

Since my final package was built using below react native bundle command but gets installed on the separate native android project. There it is still the same issue.

"react-native bundle --platform android --dev true --entry-file index.js --bundle-output ./android/app/src/main/assets/index.android.bundle --assets-dest ./server/dir/"

Could you please help us out in resolving this issue?

@sammy-SC

**Comment by chungweileong94** [comment]
If I understand correctly, you managed to solve it on local development, with `adb reverse tcp:8081 tcp:8081`, which is correct.
As for the release build, you might want to make sure you are using the correct version of `com.android.tools.build:gradle` that came with the current version of RN, else it might not able to bundle your JS code correctly.

**Comment by chungweileong94** [comment]
Actually, you shouldn't even need to run `react-native bundle`

**Comment by kapilraghuwanshi** [comment]
We are using `com.android.tools.build:gradle` 7.3.1 as per the https://reactnative.dev/blog/2021/09/01/preparing-your-app-for-iOS-15-and-android-12.

` classpath('com.android.tools.build:gradle:7.3.1')` inside build.gradle

`distributionUrl=https\://services.gradle.org/distributions/gradle-7.4-bin.zip` inside gradle-wrapper.properties

**Comment by chungweileong94** [comment]
@kapilraghuwanshi Based on the RN version (0.66~) that you provide, you should be using `com.android.tools.build:gradle:4.2.2` instead. 
https://github.com/react-native-community/rn-diff-purge/blob/version/0.66.5/RnDiffApp/android/build.gradle

I strongly advise you to use the Gradle version that comes with your current RN version, or else you might face some build issues as I mentioned earlier. Or you spend some time upgrading the RN version which supports a much higher Gradle version. 

Trust me, I literally face the exact same issue where I accidentally change the Gradle version via Android studio.

**Comment by kapilraghuwanshi** [comment]
Thanks for the reply bro [chungweileong94](https://github.com/chungweileong94)
as per your shared link https://github.com/react-native-community/rn-diff-purge/blob/version/0.66.5/RnDiffApp/android/build.gradle,
 targetSdkVersion = 30
we are planning to target android 12, so we must have targetSdkVersion=31.

Our build.gradle looks like below

```
buildscript {
    ext {
        buildToolsVersion = "30.0.3"
        minSdkVersion = 21
        compileSdkVersion = 31
        targetSdkVersion = 31
        hyperSDKVersion = "2.0.4-rc.34"
        kotlinVersion = "1.7.10"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath('com.android.tools.build:gradle:7.0.4')
    }
}
```

if you can help us [sammy-SC](https://github.com/sammy-SC)

**Comment by Fipsiflip** [comment]
We also face the same problem (Unable to load script, make sure your bundle "index.android.bundle" is packaged correctly for release)

Our build gradle looks like this:
```
ext {
        buildToolsVersion = "31.0.0"
        minSdkVersion = 21
        compileSdkVersion = 31
        targetSdkVersion = 31
        if (System.properties['os.arch'] == "aarch64") {
            // For M1 Users we need to use the NDK 24 which added support for aarch64
            ndkVersion = "24.0.8215888"
        } else {
            // Otherwise we default to the side-by-side NDK version from AGP.
            ndkVersion = "21.4.7075529"
        }
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:7.2.1")
        classpath("com.facebook.react:react-native-gradle-plugin")
        classpath("de.undercouch:gradle-download-task:5.0.1")
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
```
React native version 0.70.6

**Comment by Fipsiflip** [comment]
> @kapilraghuwanshi Based on the RN version (0.66~) that you provide, you should be using com.android.tools.build:gradle:4.2.2 instead.

I just tried it out with a different project setup. It works fine until launching in an emulator with API level 31, regardless of gradle / react native version.

RN v 0.70.6 + gradle 7.2.1 leads to this error message,
RN v 0.66.1 + gradle 4.2.2 also leads to this error message

but only on devices with API > 31 (Android 12)

**Comment by kapilraghuwanshi** [comment]
Thanks, @Fipsiflip. Yes, we tried all the above-mentioned RN and Gradle mappings which are leading us toward the same error message. Tried downgrading to RN66 and upgrading to the latest RN70 also but no luck.

**Comment by cortinico** [comment]
> RN v 0.70.6 + gradle 7.2.1 leads to this error message,

Am I reading right that this issue is happening on a empty 0.70.6 project?

**Comment by Fipsiflip** [comment]
@kapilraghuwanshi maybe this will also help you [#35523](https://github.com/facebook/react-native/issues/35523#issuecomment-1333734847), this solved the problem for me

**Comment by chungweileong94** [comment]
> @kapilraghuwanshi maybe this will also help you [#35523](https://github.com/facebook/react-native/issues/35523#issuecomment-1333734847), this solved the problem for me

Yes, sometimes you have to do this for development, but that shouldn't be the case for release build.

**Comment by chungweileong94** [comment]
> > RN v 0.70.6 + gradle 7.2.1 leads to this error message,
> 
> Am I reading right that this issue is happening on a empty 0.70.6 project?

From what I have tested on the fresh RN 0.70.6 project, both the dev & release build work fine, at least for me. 
@kapilraghuwanshi Is it possible for you to create a small example project that can reproduce this problem?

**Comment by kapilraghuwanshi** [comment]
> @kapilraghuwanshi maybe this will also help you [#35523](https://github.com/facebook/react-native/issues/35523#issuecomment-1333734847), this solved the problem for me

Yeah I already mentioned this in my original issue description but somehow it is not working on my final package built using react native but gets installed on seperate native android project. There it is still the same issue.

**Comment by kapilraghuwanshi** [comment]
> > > RN v 0.70.6 + gradle 7.2.1 leads to this error message,
> > 
> > 
> > Am I reading right that this issue is happening on a empty 0.70.6 project?
> 
> From what I have tested on the fresh RN 0.70.6 project, both the dev & release build work fine, at least for me. @kapilraghuwanshi Is it possible for you to create a small example project that can reproduce this problem?

let me give this a try.

**Comment by kapilraghuwanshi** [comment]
Somehow it did work on the release build with the below combination:

gradle plugin (build.gradle): 7.0.1
gradle: 7.3.3
Kotlin: 1.7.20
RN: 0.68.5
React: 17.0.2

looks like an android native side issue not react native.

**Comment by XilinJia** [comment]
> Somehow it did work on the release build with the below combination:
> 
> gradle plugin (build.gradle): 7.0.1 gradle: 7.3.3 Kotlin: 1.7.20 RN: 0.68.5 React: 17.0.2
> 
> looks like an android native side issue not react native.

How come?  the conclusion is not very obvious.
