### ISSUE TITLE
[iOS] TextInput inputView UIDatePicker

### ISSUE THREAD

**Issue by josev55** [facebook/react-native#3551]
Hi,

i was wondering if there is a chance to extend the TextInput so I can set a prop like mode='date' where instead of showing a keyboard it display a DatePicker.

I tried to create a Native component but it didn't work.

Tks in advance.

**Comment by aroth** [comment]
Have you checked out [DatePickerIOS](https://facebook.github.io/react-native/docs/datepickerios.html)? 

The functionality you're looking for can be created with existing React Native components.

![Screenshot](http://i.imgur.com/a4xRPjm.png)

Here's a quick example with code:
https://rnplay.org/apps/KX9lfA

**Comment by slightlytyler** [comment]
It's a nice example @aroth but it falls apart if your container does not extend to the bottom of the screen. How can we simulate the keyboard behavior but with other input components like the date picker? I don't think I've seen a solution yet

**Comment by aroth** [comment]
Absolute positioning and/or modals will get us most of the way there. 

My example was simple. Taken further, the date picker component can exist inside an absolutely positioned view, unaffected by the container size. I use a similar technique for a fairly large app and it works well.

**Comment by aroth** [comment]
The native solution would be quiet similar. From:

http://stackoverflow.com/questions/8354919/how-to-add-date-picker-in-action-sheet

"What you could very easily do is to create an UIView to hold the UIDatePicker and animate the view as appropriate. You can even add an UIToolbar to it if you need to."

**Comment by aroth** [comment]
Furthermore, bridging a library such as ActionSheetPicker would cover all of your needs and then some. Take a look:

https://github.com/skywinder/ActionSheetPicker-3.0

**Comment by slightlytyler** [comment]
@aroth thanks for the direction, looks like something like this library should do the trick.

https://github.com/eyaleizenberg/react-native-custom-action-sheet

Would love to see a bridge of ActionSheetPicker though

**Comment by josev55** [comment]
Thanks @aroth i've tried your first solution but i was looking for something like what @slightlytyler it would be awesome either way if we could set a RN View as the inputView of a TextInput because that gives you the native feeling that the keyboard provide.

Anyway thanks for the proposed solutions :)

**Comment by browniefed** [comment]
@facebook-github-bot answered

**Comment by wnr** [comment]
@josev55 did you find any satisfactory solution? I too am in the situation wanting to use the `inputView` field for native behaviour. Animating an absolute positioned picker from the bottom is not the same, as this will miss out on native behaviour such as scrolling to/from the selected input.

If it is not possible to do this with React Native APIs, do you think it is feasible to implement this using native code and bridge it to React Native?
