### ISSUE TITLE
Unimplemented component: <RNCWebView>

### ISSUE THREAD

**Issue by sohayb** [facebook/react-native#35515]
### Description

When enabling the new react native architecture, the WebView is not rendering and showing this message
`Unimplemented Component: <RNCWebView>`. I'm aware that `react-native-webview` is not yet migrated to the new architecture, so I don't think the issue is there. Maybe it's similar to [this issue](https://github.com/facebook/react-native/issues/33652)
![Simulator Screen Shot - iPhone 14 Pro - 2022-11-30 at 16 49 41](https://user-images.githubusercontent.com/2195533/204919613-b4745e73-d26d-45f0-a78e-ee4d8a7d26b3.png)

### Version

0.70.6

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 12.6.1
    CPU: (10) x64 Apple M1 Pro
    Memory: 187.43 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.17.6 - ~/.nvm/versions/node/v14.17.6/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 7.21.1 - ~/.nvm/versions/node/v14.17.6/bin/npm
    Watchman: 2022.11.07.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/sohayb/.rvm/gems/ruby-2.7.6/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK:
      API Levels: 28, 29, 30, 31, 32, 33
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 33.0.0, 33.0.1
      System Images: android-31 | Google APIs ARM 64 v8a, android-31 | Google Play ARM 64 v8a, android-33 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.13 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.6 => 0.70.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Just import and use `WebView` from  `react-native-webview`.

### Snack, code example, screenshot, or link to a repository

N/A

**Comment by cortinico** [comment]
Closing as this is related to https://github.com/react-native-webview/react-native-webview
You should open an issue on that repo to track the progress.

I know @Titozzz has been working on New Architecture support for this library, so hopefully you'll be unblocked soon.
