### ISSUE TITLE
Fresh project setup: Unable to load script. Make sure you're either running Metro (run 'npx react-native start')

### ISSUE THREAD

**Issue by Fipsiflip** [facebook/react-native#35523]
### Description

On a complete fresh init of a new react native project (npx react-native init ProjectName), the following error occurs for Emulators API < 31 (Android 12). (no changes made to the project)

<img width="223" alt="image" src="https://user-images.githubusercontent.com/71025588/205041926-7a13206b-6dbb-457c-ac98-4cb23ff976e8.png">

**build.gradle**
```
ext {
        buildToolsVersion = "31.0.0"
        minSdkVersion = 21
        compileSdkVersion = 31
        targetSdkVersion = 31

        if (System.properties['os.arch'] == "aarch64") {
            // For M1 Users we need to use the NDK 24 which added support for aarch64
            ndkVersion = "24.0.8215888"
        } else {
            // Otherwise we default to the side-by-side NDK version from AGP.
            ndkVersion = "21.4.7075529"
        }
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:7.2.1")
        classpath("com.facebook.react:react-native-gradle-plugin")
        classpath("de.undercouch:gradle-download-task:5.0.1")
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
```

### Version

0.70.6

### Output of `npx react-native info`

System:
    OS: macOS 11.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 755.84 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 8.1.0 - /usr/local/bin/npm
    Watchman: 2022.07.04.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7784292
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 16.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.6 => 0.70.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

https://reactnative.dev/docs/environment-setup

just follow the steps and init a completely new project. The error occurs every time

- npx react-native init AwesomeProject
- npx react-native start to start Metro
- then run the project in an emulator with API > 31 (Android 12)

### Snack, code example, screenshot, or link to a repository

Link to repo (as stated before, it is a fresh RN project): https://github.com/Fipsiflip/BugReport-SampleProject

**Comment by cortinico** [comment]
> On a complete fresh init of a new react native project (npx react-native init ProjectName), the following error occurs for Emulators API < 31 (Android 12). (no changes made to the project)

As the error message says, do you have Metro running? It should be in a separate console.

**Comment by cortinico** [comment]
> It also only affects Emulators with API > 31 with Android 12, the others start up perfectly fine with the exact same setup and steps

Could you try to run `adb reverse tcp:8081 tcp:8081` in a console, and check if it's working afterwards. We had reporting of emulators failing to connect in the past on Android 12+

**Comment by Fipsiflip** [comment]
Thanks a lot! That did the trick, works now
