### ISSUE TITLE
PhaseScriptExecution OpenSSL-Universal Xcode: 14.1

### ISSUE THREAD

**Issue by XiaoJiangMa** [facebook/react-native#35532]
### Description

** BUILD FAILED **

The following build commands failed:
        PhaseScriptExecution [CP]\ Copy\ XCFrameworks /Users/ma/Library/Developer/Xcode/DerivedData/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/OpenSSL-Universal.build/Script-46EB2E00018E30.sh (in target 'OpenSSL-Universal' from project 'Pods')
(1 failure)

### Version

0.68.1

### Output of `npx react-native info`

System:
    OS: macOS 13.0.1
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 24.29 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.2.0 - /var/folders/tr/5v_tb6ss1tlfv8tm58qtsy6r0000gn/T/yarn--1669947750187-0.45793265948926876/node
    Yarn: 1.22.19 - /var/folders/tr/5v_tb6ss1tlfv8tm58qtsy6r0000gn/T/yarn--1669947750187-0.45793265948926876/yarn
    npm: 9.1.3 - /usr/local/bin/npm
    Watchman: 2022.11.28.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.1 => 0.68.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

run ios

### Snack, code example, screenshot, or link to a repository

.

**Comment by XiaoJiangMa** [comment]
"${PODS_ROOT}/Target Support Files/OpenSSL-Universal/OpenSSL-Universal-xcframeworks.sh"

**Comment by cortinico** [comment]
Not enought info to debug this. We would need at least the full build log.

**Comment by XiaoJiangMa** [comment]
Permission issues

**Comment by julianD77** [comment]
For our project adding the path:

> "${PODS_ROOT}/Target Support Files/OpenSSL-Universal/OpenSSL-Universal-xcframeworks.sh"

as suggested by @XiaoJiangMa to Build Settings / Header Search Paths resolved our error:

>  "OpenSSL-Universal-xcframeworks.sh: No such file or directory"

**Comment by julianD77** [comment]
Also worth noting that we had the same error:

> "OpenSSL-Universal-xcframeworks.sh: No such file or directory"

when running `xcodebuild` from terminal as part of our Detox suite on migrating to Detox v20+ and the cause ended up being the `UseNewBuildSystem=NO` parameter that had been included in our `xcodebuild` command in error
