### ISSUE TITLE
[ListView] [cloneWithRowsAndSections] rowHasChanged compares new rows, not new and old.

### ISSUE THREAD

**Issue by irfaan** [facebook/react-native#3554]
When using ```cloneWithRowsAndSections```, it appears that ```rowHasChanged``` is comparing the updated row against itself, instead of against the old row. 

Checked using: ```rowHasChanged: (r1, r2) => (console.log(r1, r2))```, which outputs two identical rows, both reflecting the top-level object property change (e.g. obj[flagged] = true). 

Console output:
```
{
    id: [x],
    flagged: true
}
{
    id: [x],
    flagged: true
}
```

Expecting:
```
{
    id: [x],
    flagged: false
}
{
    id: [x],
    flagged: true
}
```

As a result, I am unable to compare on that heuristic (like suggested in https://github.com/facebook/react-native/issues/3518), or any other for that matter. 

How the property is updated--

Datasource initialized:
```
// Set state
this.setState({
    assetDataSource: this.state.assetDataSource.cloneWithRowsAndSections(this.asset_data),
    currentAssetSectionInfo: this.section_data
});
```

Datasource updated:
```
// Make changes
this.asset_data[id_to_update].flagged = true;

// Update
this.setState({
    assetDataSource: this.state.assetDataSource.cloneWithRowsAndSections(this.asset_data),
    currentAssetSectionInfo: this.section_data
});
```

Any ideas as to why this might be?

**Comment by ide** [comment]
Are your new rows actually your old rows? Try cloning with `JSON.parse(JSON.stringify(this.asset_data))` to debug.

**Comment by irfaan** [comment]
Agh - silly of me. That was it. Thank you!
