### ISSUE TITLE
react_native_post_install set main project EXCLUDED_ARCHS[sdk=iphonesimulator*] to empty string in iOS

### ISSUE THREAD

**Issue by swong-wavefin** [facebook/react-native#35544]
### Description

My project requires `EXCLUDED_ARCHS[sdk=iphonesimulator*]=arm64`.

In Podfile, found that `exclude_architectures` script under `react_native_post_install` set `EXCLUDED_ARCHS` as empty string in default.

My current workaround is to clone `exclude_architectures` into my podfile to override it.

Could we add a parameters on react_native_post_install to allow customized config on default exclude_architectures?

### Version

0.69.7

### Output of `npx react-native info`

System:
    OS: macOS 12.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.96 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.17.4 - ~/.nvm/versions/node/v14.17.4/bin/node
    Yarn: 1.22.11 - ~/Projects/argo/argo-mobile-ios/node_modules/.bin/yarn
    npm: 6.14.14 - ~/.nvm/versions/node/v14.17.4/bin/npm
    Watchman: 2022.11.07.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 29, 30, 31, 32
      Build Tools: 30.0.2, 30.0.3, 31.0.0
      System Images: android-30 | Google APIs Intel x86 Atom_64, android-30 | Google Play Intel x86 Atom, android-31 | Google APIs Intel x86 Atom_64, android-32 | Google APIs Intel x86 Atom_64, android-Tiramisu | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8815526
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: 0.69.7 => 0.69.7 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

pod install

### Snack, code example, screenshot, or link to a repository

![Screen Shot 2022-12-02 at 12 48 00 PM](https://user-images.githubusercontent.com/100863026/205354142-910ceefe-1713-4c05-a9f6-a9dfcd9d236b.png)
![Screen Shot 2022-12-02 at 12 48 14 PM](https://user-images.githubusercontent.com/100863026/205354173-da9ecd46-fbac-4126-82e3-a78f277c4c7d.png)

**Comment by je7ov** [comment]
Running into same issue still 5/19/23 on R.N. 0.71.4

**Comment by jpdriver** [comment]
just hit this too.

wondering if we need to run through `ReactNativePodsUtils.exclude_i386_architecture_while_using_hermes` at all if we aren't using Hermes..? 🤔
