### ISSUE TITLE
The text above the button component is automatically capitalized and cannot be modified.

### ISSUE THREAD

**Issue by AsteriskZuo** [facebook/react-native#35548]
### Description

Expect: button can be set to display raw character case.

### Version

0.68.5

### Output of `npx react-native info`

System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1
    Memory: 90.73 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.1 - /opt/homebrew/Cellar/node@16/16.18.1/bin/node
    Yarn: 1.22.19 - /opt/homebrew/Cellar/node@16/16.18.1/bin/yarn
    npm: 8.19.2 - /opt/homebrew/Cellar/node@16/16.18.1/bin/npm
    Watchman: 2022.10.31.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/opt/cocoapods/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 23, 28, 29, 30, 31, 32
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.1, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0
      System Images: android-28 | Google ARM64-V8a Play ARM 64 v8a, android-32 | Google APIs ARM 64 v8a
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.13 - /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.68.5 => 0.68.5
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

It's obvious.

### Snack, code example, screenshot, or link to a repository

none

**Comment by AsteriskZuo** [comment]
Can someone answer me??

**Comment by NickGerleman** [comment]
The Button.js component will automatically capitalize titles on Android. This and its styles kinda emulated a precious version of Material design, and I agree the capitalization may not make sense (along with its theming in general). 

Informally we don’t recommend using Button outside the barest cases, compared to using a higher level component library which would build something custom on Pressable. It’s a pain point in the RN API.
