### ISSUE TITLE
[Animated] Animated.sequence used for scale transform leads to null values in transformMatrix.

### ISSUE THREAD

**Issue by MattFoley** [facebook/react-native#3555]
I'm running v0.0.11. In this version, I'm attempting an animation like this:

```js
_loopScaleAnimation() {
    if (!this.scaling) {
      var sequenceArray = [];
      for (var i = 0; i < 1000; i++) {
        sequenceArray.push(Animated.timing(
                            this.state.bounceValue,
                            {
                              toValue: 0.895,
                              duration: 600,
                              easing: Easing.inOut(Easing.ease),
                            }));
        sequenceArray.push(Animated.timing(
                            this.state.bounceValue,
                            {
                              toValue: 1.0,
                              duration: 600,
                              easing: Easing.inOut(Easing.ease),
                            }));
      }

      var scaling = Animated.sequence(sequenceArray);
      scaling.start();
      this.scaling = scaling;
    }
  }
```

It's attached to a view like this:

```js
  <Animated.View style={{transform:[{scale: this.state.bounceValue}]}}
                     ref={(view) => this.cell = view}>
    <...>
  </Animated.View>
```

After a variable amount of time, sometimes after 5-10 seconds, sometimes almost instantly, sometimes never, it collapses. It spits out never ending dialog of the same line:

```
2015-10-20 18:13:43.126 [error][tid:main][RCTConvert.m:55] Error setting property 'transformMatrix' of RCTView with tag #299: JSON value '<null>' of type NSNull cannot be converted to NSNumber
2015-10-20 18:13:43.130 [error][tid:main][RCTConvert.m:55] Error setting property 'transformMatrix' of RCTView with tag #299: JSON value '<null>' of type NSNull cannot be converted to NSNumber
2015-10-20 18:13:43.133 [error][tid:main][RCTConvert.m:55] Error setting property 'transformMatrix' of RCTView with tag #299: JSON value '<null>' of type NSNull cannot be converted to NSNumber
2015-10-20 18:13:43.137 [error][tid:main][RCTConvert.m:55] Error setting property 'transformMatrix' of RCTView with tag #299: JSON value '<null>' of type NSNull cannot be converted to NSNumber
2015-10-20 18:13:43.140 [error][tid:main][RCTConvert.m:55] Error setting property 'transformMatrix' of RCTView with tag #299: JSON value '<null>' of type NSNull cannot be converted to NSNumber
```

I've tracked this down to null values being passed to RCTConvert CATransform3D. I'm not sure why this happens. I create the bounceValue object in the constructor() and in componentWillReceiveProps(), like so:

`setState({bounceValue: new Animated.Value(1),})`

Any ideas? Is this something that is fixed in the latest version?

**Comment by MattFoley** [comment]
A bit more information, if I remove the `easing: Easing.inOut(Easing.ease),` call, the issue doesn't happen. Possibly an issue with how that Easing object interpolates values? 

A similar issue happens if I instead do an opacity transform with that easing function. Rather than crashing however, the animation just stops running after about a second.

**Comment by MattFoley** [comment]
Can confirm this is still an issue as of 0.15rc

**Comment by ekonstantinidis** [comment]
I have the same issue in React Native 0.18.1. This currently happens on iOS (haven't tested Android). This error comes up only when I bundle the app. Using the dev server it works fine. It is happening when I'm pressing a `TouchableHighlight` which just toggles a boolean variable of the state. Any ideas?

**Comment by scaletimes** [comment]
+1

**Comment by javamonn** [comment]
Can confirm that this is still an issue as of RN 0.20.0. For me, this was limited to iOS only, being run on device (both bundled and dev server). I wasn't using any custom animations where this would break - just route transition animations - fix seems to be to remove a `Navigator.replace` call before the call to `Navigator.push` that this break would occur. 

I suspect that the route transition animations are using `Easing.inOut` under the hood causing the break in this case.

**Comment by lacker** [comment]
Hmm, I feel bad that nobody got to this before now, but since all of these comments are pretty old, refer to slightly different things, and there has been a decent amount of work on animation since then, it's hard for me to see how to make progress on this issue from here. I think the thing to do is to close out this issue but if tehre is a similar issue with nulls in animations on a recent version of RN with a small repro then that would be helpful and I suggest people with that info to open a new issue. So on that theory I am closing this issue.
