### ISSUE TITLE
Linking.canOpenURL(`tel:${phone}`) return false in android, but Linking.openURL(`tel:${phone}`) can work

### ISSUE THREAD

**Issue by OneHangH** [facebook/react-native#35556]
### Description

Linking.canOpenURL(`tel:${phone}`) return false in android, but Linking.openURL(`tel:${phone}`) can work
android targetSdkVersion = 31

### Version

0.70.4

### Output of `npx react-native info`

System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1
    Memory: 125.39 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 8.5.5 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 13.0/13A233 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /Users/cocytus/.jenv/shims/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.4 => 0.70.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Linking.canOpenURL(`tel:${phone}`)  // false
Linking.openURL(`tel:${phone}`) // work

### Snack, code example, screenshot, or link to a repository

Linking.canOpenURL(`tel:${phone}`)  // false
Linking.openURL(`tel:${phone}`) // work

**Comment by lovelytingy** [comment]
Hi @OneHangH  you must specify the intents for the schemes you want to handle in `AndroidManifest.xml`. Your app also needs to provide the LSApplicationQueriesSchemes key inside Info.plist for IOS.
here's the links to find common intents. [LINK](https://developer.android.com/guide/components/intents-common)

you can solve your issue by adding this code inside AndroidManifest.xml

`<manifest
  xmlns:android="http://schemas.android.com/apk/res/android"
  package="com.yourAppName"
>
    ...
     <queries> 
        <intent>
            <action android:name="android.intent.action.VIEW" />
            <data android:scheme="tel" />
        </intent>
    </queries>
    ...
</manifest>`

Although above code can help you, I am wondering why this not updated in [docs](https://reactnative.dev/docs/linking#built-in-url-schemes) yet [🤔](https://emojipedia.org/thinking-face/).

**Comment by OneHangH** [comment]
> Hi @OneHangH you must specify the intents for the schemes you want to handle in `AndroidManifest.xml`. Your app also needs to provide the LSApplicationQueriesSchemes key inside Info.plist for IOS. here's the links to find common intents for android. [LINK](https://developer.android.com/guide/components/intents-common)
> 
> You can solve your issue by adding this code inside AndroidManifest.xml
> 
> `<queries> <intent> <action android:name="android.intent.action.VIEW" /> <data android:scheme="tel" /> </intent> </queries>`

thanks,  It helped me solve the problem

**Comment by corbella83** [comment]
This solution is wrong. If you add the scheme in the android manifest, this will allow your application to handle 'tel' schemes, and that's not what you want. Every other app using "tel:" will be asked to open it with your app.

The **canOpenURL** still needs to be fixed. 

Alternatively, you could use the Linking.openURL() capturing the catch:
    `Linking.openURL().catch(e=>console.log('Could` not make the phone call'))`
