### ISSUE TITLE
36 duplicate symbols for architecture x86_64

### ISSUE THREAD

**Issue by ana-nd-s** [facebook/react-native#35558]
### New Version

0.70.6

### Old Version

0.63.3

### Build Target(s)

ios simulator in debug mode

### Output of `react-native info`

System:
    OS: macOS 12.5
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Memory: 55.71 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.1/bin/npm
    Watchman: 2022.09.19.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/anandkumar/.rvm/rubies/ruby-2.7.2/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 23, 25, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 32.0.0
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7351085
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.70.6 => 0.70.6
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Issue and Reproduction Steps

<img width="1440" alt="Screenshot 2022-12-05 at 12 51 13 PM" src="https://user-images.githubusercontent.com/65527953/205576886-8f927450-b797-4c7a-bd7f-b4d1bbff7ac8.png">

**Comment by benjamineruvieru** [comment]
I am facing same issue, I am so frustrated

**Comment by jaydeep911** [comment]
Same for me on macbook with m1.

**Comment by thisisadarshjais** [comment]
Any solution here??
