### ISSUE TITLE
`npx react-native init` fails with an unclear error on unsupported Node versions

### ISSUE THREAD

**Issue by motiz88** [facebook/react-native#35561]
### Description

When I try to initialise a React Native project on an old, unsupported version of Node, it fails with this unclear error message:

```
$ npx react-native init RN0710RC3 --version 0.71.0-rc.3


npx: installed 601 in 15.314s
Unexpected token '?'
```

**Expected behaviour:** There should be a message saying that my Node version is unsupported and which minimum version I should upgrade to.

### Version

0.71.0-rc.3

### Output of `npx react-native info`

`npx react-native info` itself fails with the same output:

```
$ npx react-native info
npx: installed 601 in 22.114s
Unexpected token '?'
```

### Steps to reproduce

1. Install an old version of Node (e.g. `nvm install 12`)
2. `npx react-native init RN0710RC3 --version 0.71.0-rc.3`

### Snack, code example, screenshot, or link to a repository

N/A (see above)

**Comment by cortinico** [comment]
This is a valid report but should be moved the CLI as that's where the `init` command logic is located: https://github.com/react-native-community/cli/issues
