### ISSUE TITLE
UI is not rendering properly when clicked on push notifications in iOS

### ISSUE THREAD

**Issue by PanamaxMobile** [facebook/react-native#35587]
### Description

I had integrated push notification in my react native application. when I click on the push notification (removed app instance) my application opens and it navigates to the Home screen but UI does not render properly (styles are not applied to UI). it happens only in iOS. Android works fine

### Version

0.61.5

### Output of `npx react-native info`

System:
    OS: macOS 13.0.1
    CPU: (8) arm64 Apple M1
    Memory: 65.70 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.1.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.3 - /opt/homebrew/bin/npm
    Watchman: 2022.11.14.00 - /opt/homebrew/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 22, 23, 25, 27, 28, 29, 30, 31, 32, 33
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.1, 30.0.2, 30.0.3, 31.0.0, 33.0.0
      System Images: android-29 | Google Play ARM 64 v8a, android-30 | AOSP ATD ARM 64 v8a, android-30 | Google APIs ARM 64 v8a, android-30 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom_64, android-30 | Google Play ARM 64 v8a, android-30 | Google APIs ATD ARM 64 v8a, android-32 | Google Play ARM 64 v8a
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-create-library: 3.1.2
    react-native-video-player: 0.12.0
    tp-react-native-bluetooth-printer: 1.0.1

### Steps to reproduce

I'm trying to send a push notification from the backend when the app is in close/kill state. Then clicked on the notification, it navigated to the home page but the UI didn't render properly.

```
"@react-native-firebase/app": "^13.1.0",
"@react-native-firebase/messaging": "^14.0.0",
```

### The following method is working well to get notification
firebase.messaging().getInitialNotification().then(notificationOpen => {
            console.warn('getInitialNotification: ', notificationOpen)
});

### Snack, code example, screenshot, or link to a repository

![IMG_20221207_133726](https://user-images.githubusercontent.com/106740388/206123396-1f0911e9-7cdb-4f39-b190-cc0f8b7ff3b7.png)

**Comment by Janviba911** [comment]
The issue has been resolved. Please check below link for ref
https://firebase.google.com/docs/cloud-messaging/http-server-ref

Set content_available to false in iOS FCM configuration
