### ISSUE TITLE
[!] Error installing CocoaAsyncSocket [!] /usr/bin/git clone https://github.com/robbiehanson/CocoaAsyncSocket.git /var/folders/44/p

### ISSUE THREAD

**Issue by dominicg666** [facebook/react-native#35589]
### Description

I'm trying to install pods. but it has shown these errors. 

fatal: not a git repository (or any of the parent directories): .git
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
[Codegen] Found FBReactNativeSpec
Fetching podspec for `RCT-Folly` from `../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec`
Fetching podspec for `boost` from `../node_modules/react-native/third-party-podspecs/boost.podspec`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
Fetching podspec for `hermes-engine` from `../node_modules/react-native/sdks/hermes/hermes-engine.podspec`
Downloading dependencies
Installing CocoaAsyncSocket (7.6.5)

[!] Error installing CocoaAsyncSocket
[!] /usr/bin/git clone https://github.com/robbiehanson/CocoaAsyncSocket.git /var/folders/44/pdz2cl0561z4jh2377tl293h0000gp/T/d20221207-3976-gkz985 --template= --single-branch --depth 1 --branch 7.6.5

Cloning into '/var/folders/44/pdz2cl0561z4jh2377tl293h0000gp/T/d20221207-3976-gkz985'...
ssh: Could not resolve hostname github.com:robbiehanson: nodename nor servname provided, or not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

### Version

0.70.6

### Output of `npx react-native info`

System:
    OS: macOS 13.0.1
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 829.48 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.5.5 - /usr/local/bin/npm
    Watchman: 2022.03.21.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8512546
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.6 => 0.70.6
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. got to the ios folder
2. try to run pod install

### Snack, code example, screenshot, or link to a repository

nil

**Comment by dominicg666** [comment]
No, we are not added any kind of restricted

**Comment by cortinico** [comment]
> ssh: Could not resolve hostname github.com:robbiehanson: nodename nor servname provided, or not known
fatal: Could not read from remote repository.

This is definitely a local issue you're having in failing to resolve `github.com` from your device.
