### ISSUE TITLE
'newArchEnabled=true' no trigger build source for fabricjni.so  v0.71.0-rc.3 

### ISSUE THREAD

**Issue by Smarking** [facebook/react-native#35593]
### Description

please help me , how trigger  build fabricjni.so ? 'yarn android ' + 'newArchEnabled=true' is no useful,

is need use './gradlew :ReactAndroid:installArchives' ? but show error 'Error: Cannot find module 'yargs''

### Version

0.71.0-rc.3

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 12.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 375.92 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.1.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.3 - /usr/local/bin/npm
    Watchman: 2022.12.05.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK:
      API Levels: 26, 28, 29, 30, 31, 32, 33
      Build Tools: 27.0.3, 28.0.0, 28.0.3, 29.0.0, 29.0.1, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 33.0.0
      System Images: android-29 | Google Play Intel x86 Atom
      Android NDK: 21.4.7075529
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9301383
    Xcode: 14.0/14A309 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.0-rc.3 => 0.71.0-rc.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. './gradlew :ReactAndroid:installArchives'    show error 'Error: Cannot find module 'yargs''
2. 'yarn android ' + 'newArchEnabled=true' is no useful,

### Snack, code example, screenshot, or link to a repository

https://github.com/facebook/react-native/tree/0.71-stable

**Comment by Smarking** [comment]
https://reactnative.dev/contributing/how-to-build-from-source . use [Docker] build mode  

Error: Cannot find module 'yargs'

**Comment by Smarking** [comment]
> Can I ask you to clarify why do you need `:ReactAndroid:installArchives` and `libfabric.so`?

i want to import  Skia[cpu|gpu]  as  RenderEngine  for  libfabric.so , so it run on  IOT devices  ,  now  v0.71  build from source error ,  0.70 is success

**Comment by cortinico** [comment]
> i want to import Skia[cpu|gpu] as RenderEngine for libfabric.so

Thanks. Can I ask you to clarify further on this?

**Comment by cortinico** [comment]
Closing as this issue was related to a RC for 0.71
