### ISSUE TITLE
[0.71] Release of React Native 0.71 is currently blocked by an AGP stable release

### ISSUE THREAD

**Issue by cortinico** [facebook/react-native#35592]
### Description

Hey all,
I'm opening this issue to track the current status of a blocker for the release of React Native 0.71.x. We'll use this issue to track the status and decide what to do next.

## The problem

We're about to ship `0.71.0` with a version of AGP (Android Gradle Plugin) which is `7.4.0-beta05`, the last known version of AGP that is working with the current setup of React Native.

https://github.com/facebook/react-native/blob/e6563daeeb35bd865d41ef2ee2f7fb480835eb3a/template/android/build.gradle#L18

This has the unfortunate side effect that users will be able to open **newly created projects** only inside Android Studio Electric Eel version **7.4.0-beta05**. When opening such a project with a different version of Android Studio (say 7.4.0 stable), they'll be prompted to "update" their Android project to the corresponding version, resulting in a build failure.

## Overview of AGP versions

Specifically, the offending API is the `addGeneratedSourceDirectory` method used to inject the JS bundle and the static asset inside the final APK:

https://github.com/facebook/react-native/blob/e3f24195c4ec82465492d8210240ae51e55c6c0b/packages/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/TaskConfiguration.kt#L73-L74

We've been investigating AGP versions and if we can use another non-broken versions of AGP. Here an overview.

* `7.2.x` -> Unusable as the `addGeneratedSourceDirectory` was not there
* `7.3.x` -> Unusable as `addGeneratedSourceDirectory` [is broken for resources](https://issuetracker.google.com/issues/237421684). This was causing #35439 on our previous RC. A fix has been shipped by Google's, and is available in `7.4`. I’ve asked for a backport of the fix in `7.3` but it seems like there are no more `7.3.x` releases planned.
* `7.4.0-beta05` -> That’s the last AGP version where this API is working (the one we're about to ship).
* `7.4.0-rc01` -> Unusable as `addGeneratedSourceDirectory` [got broken inside RC01](https://issuetracker.google.com/issues/261329823). I’ve reported the issue and got it fixed (which is great!)
* `7.4.0` -> Unusable as the fix for the broken API won’t land in `.0` but we’ll have to wait for `7.4.1` [apparently](https://issuetracker.google.com/issues/261329823).
* `7.4.1` -> Seems like we’ll have to wait for this version (sadly we don’t have an ETA from Google's end on this).

### Version

0.71.0

**Comment by cortinico** [comment]
I'm investigating the feasibility of not invoking:

```
variant.sources.res?.addGeneratedSourceDirectory(bundleTask, BundleHermesCTask::resourcesDir)
```

entirely as it's broken, pass and hardcoded `resourcesDir` similar to what we were doing in 0.70.x and use AGP `7.3.1` at least to unblock the release.

**Comment by Smarking** [comment]
me to

**Comment by Smarking** [comment]
please help me , how trigger build fabricC++ ? newArchEnabled=true is no useful,
and use './gradlew :ReactAndroid:installArchives' ? but show error 'Error: Cannot find module 'yargs''

**Comment by cortinico** [comment]
We ended up de-bumping AGP to 7.3 to unblock the release of RN 0.71 as Google is not providing any ETA on AGP 7.4 and the current releases are all broken.

The de-bump is circumventing the broken APIs on AGP 7.3 so we should be good to go.
This will also allow to open RN projects on .71 with both Android Studio Electric Eel and Dolphin.

**Comment by kelset** [comment]
(the commit will land in 0.71 RC5)

**Comment by cortinico** [comment]
Just a heads up that Google released AGP 7.4.1 which fixes the bug with `addGeneratedSourceDirectory` and we're bumping it in:
- https://github.com/facebook/react-native/pull/36039

**Comment by androideveloper** [comment]
Hi @cortinico! Thanks for the update here. Any known issues when running RN 0.70 with AGP 7.4.1?

**Comment by cortinico** [comment]
> Any known issues when running RN 0.70 with AGP 7.4.1?

We haven't tested it so that's not recommended.
