### ISSUE TITLE
2 pod versions of React-Core?

### ISSUE THREAD

**Issue by MicahDavid** [facebook/react-native#35607]
### Description

I noticed that I have 2 pods listed for React Core: 
React-Core 
React-Core-60309c9c-AccessibilityResources

along with the 2 versions of React Core, I also had the following pod folders: 
React-Core-AccessibilityResources
React-Core-60309c9c-AccessibilityResources

This was leading to an error: 
Multiple commands produce '.......AccessibilityResources.bundle'

To get past the error, i deleted one of the AccessibilityResources folder. But, of course, everytime I do a new pod install, it adds the deleted version back in. 

My question relates to this additional version *-60309c9c. Is doesn't seem like this is the expected behavior?  I've tried reinstalling the pods with without success: 
rm -rf Pods
pod install

Any suggestions on this one? 

### Version

0.70.6

### Output of `npx react-native info`

System:
    OS: macOS 12.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 27.39 MB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
    Yarn: 1.22.18 - ~/.nvm/versions/node/v14.18.1/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
    Watchman: 2022.03.21.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/micahsklut/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 29, 30, 31
      Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: ^0.70.4 => 0.70.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

pod install

### Snack, code example, screenshot, or link to a repository

![Screen Shot 2022-12-09 at 2 15 18 PM](https://user-images.githubusercontent.com/51126961/206780125-379c986d-971a-4a58-a76f-f9655dc19fbb.png)

**Comment by MartynasAndr** [comment]
Having exactly the same problem. Any ideas? Temp solution for me is removing "React-Core-AccessibilityResources" from pods project in Podfile.

<img width="559" alt="Screenshot 2022-12-13 at 11 17 41" src="https://user-images.githubusercontent.com/27691602/207277743-6d498210-e59e-4b84-9f6f-920b94c35e10.png">

**Comment by MicahDavid** [comment]
> Having exactly the same problem. Any ideas? Temp solution for me is removing "React-Core-AccessibilityResources" from pods project in Podfile.
> 

Thanks... Initially, I was removing 
React-Core-60309c9c-AccessibilityResources
And, i would get past the initial error, but then I got an error that was still looking for the POD i removed. 

Then, instead of removing:
React-Core-60309c9c-AccessibilityResources
I removed: 
React-Core-AccessibilityResources

And, this worked to successfully build the archive. 

While I got it to build, I would still like to figure out why I have multiple copies of React-Core and React-Core-AccessbilityResources

**Comment by MicahDavid** [comment]
Perhaps it has something to do with the Podfile configuration? 
Here is my Podfile: 

```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.4'
install! 'cocoapods', :deterministic_uuids => false

$RNFirebaseAnalyticsWithoutAdIdSupport = true

target 'SURF_CAPTAIN_NATIVE' do
  config = use_native_modules!

  # Flags change depending on  the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],

    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    :hermes_enabled => true,
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => FlipperConfiguration.enabled,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'SURF_CAPTAIN_NATIVETests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end

pod 'react-native-fbsdk-next', :path => '../node_modules/react-native-fbsdk-next'
```

**Comment by lepertRSU** [comment]
Also having the issue on React 70.4.

**Comment by MicahDavid** [comment]
@lepertRSU thanks for your response.  Would you mind elaborating a bit more, because I don't quite follow you. 

Are you saying you had to remove a line from the Podfile file? 

This is what my Podfile looks like: 
```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.4'
install! 'cocoapods', :deterministic_uuids => false

$RNFirebaseAnalyticsWithoutAdIdSupport = true

target 'SURF_CAPTAIN_NATIVE' do
  config = use_native_modules!

  # Flags change depending on  the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],

    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    :hermes_enabled => true,
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => FlipperConfiguration.enabled,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'SURF_CAPTAIN_NATIVETests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end

pod 'react-native-fbsdk-next', :path => '../node_modules/react-native-fbsdk-next'

```

The only thing that resembles what you are referring to is the last line with the react-native-fbsdk-next package. So, maybe I need to remove this line? 

Thank you!

**Comment by MicahDavid** [comment]
Sorry, I should have just tested this before commenting previous, but yes removing this: 
pod 'react-native-fbsdk-next', :path => '../node_modules/react-native-fbsdk-next'

Fixed the problem for me.  Now when I do a pod install I only get one of these pods: 
React-Core
React-Core-AccessibilityResources

Thanks @lepertRSU for the help!

**Comment by lepertRSU** [comment]
Yes...for us one of our developers had added a pod install of a react
native component directly in the podfile.  That needed to be removed.
Everything is setup and controlled from the package.json.

**Comment by ariyanashfaque** [comment]
Here's my podfile :

```
# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

# platform :ios, podfile_properties['ios.deploymentTarget'] || '13.0'
pod 'Firebase', :modular_headers =>  true
pod 'FirebaseCoreInternal', :modular_headers => true
pod 'GoogleUtilities', :modular_headers  => true
pod 'FirebaseCore', :modular_headers => true

pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

target 'beastCustomerCli' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'beastCustomerCliTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end
```

The error I am facing: 
Showing All Messages
Multiple commands produce '/Users/implevista/Library/Developer/Xcode/DerivedData/beastCustomerCli-aqrdzeqfntciyqbvakhsfexxykgc/Build/Intermediates.noindex/ArchiveIntermediates/beastCustomerCli/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/RCTI18nStrings.bundle'

If I remove `pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'` I am getting another error.
