### ISSUE TITLE
Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication()

### ISSUE THREAD

**Issue by AndrewDongminYoo** [facebook/react-native#35602]
### Description

Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.

### Version

0.70.5

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 13.0.1
    CPU: (8) arm64 Apple M1
    Memory: 93.25 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.5.5 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 29, 30, 31, 33
      Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0, 33.0.0, 33.0.1
      System Images: android-33 | Google APIs ARM 64 v8a
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.5 => 0.70.5 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

I was upgrade react-native from 0.67.3 to 0.70.3.

In my case problem was with: ColorPropType, EdgeInsetsPropType, PointPropType, ViewPropTypes.

My steps to resolve this issue:

yarn add patch-package
add script to the scripts at the package.json "postinstall": patch-package"
yarn add deprecated-react-native-prop-type
Go to node_modules/react-native/Libraries/InitializeCore.js
In 47 line (after require('../LogBox/LogBox').install(); } add: require('../ReactNative/AppRegistry');
npx patch-package react-native
Now should be visible errors related with ColorPropType, EdgeInsetsPropType, PointPropType, ViewPropTypes
To resolve it change all deprecated imports for example import { EdgeInsetsPropType } from 'react-native' on import { EdgeInsetsPropType } from 'deprecated-react-native-prop-types';
npx patch-package LIBRARY_NAME

### Snack, code example, screenshot, or link to a repository

diff --git a/node_modules/react-native/Libraries/Core/InitializeCore.js b/node_modules/react-native/Libraries/Core/InitializeCore.js
index ee7b99f..1591dcd 100644
--- a/node_modules/react-native/Libraries/Core/InitializeCore.js
+++ b/node_modules/react-native/Libraries/Core/InitializeCore.js
@@ -39,9 +39,10 @@ require('./setUpNavigator');
 require('./setUpBatchedBridge');
 require('./setUpSegmentFetcher');
 if (__DEV__) {
-  require('./checkNativeVersion');
-  require('./setUpDeveloperTools');
-  require('../LogBox/LogBox').install();
+    require('./checkNativeVersion');
+    require('./setUpDeveloperTools');
+    require('../LogBox/LogBox').install();
+    require('../ReactNative/AppRegistry');
 }
 
 const GlobalPerformanceLogger = require('../Utilities/GlobalPerformanceLogger');
@@ -49,7 +50,7 @@ const GlobalPerformanceLogger = require('../Utilities/GlobalPerformanceLogger');
 // but then we'd be excluding the time it took to require the logger.
 // Instead, we just use Date.now and backdate the timestamp.
 GlobalPerformanceLogger.markPoint(
-  'initializeCore_start',
-  GlobalPerformanceLogger.currentTimestamp() - (Date.now() - start),
+    'initializeCore_start',
+    GlobalPerformanceLogger.currentTimestamp() - (Date.now() - start),
 );
 GlobalPerformanceLogger.markPoint('initializeCore_end');

**Comment by DFRZ7** [comment]
Facing the same issue here, this was after installing https://www.npmjs.com/package/react-native-compressor, works in Android, but iOS will not budge. Not sure if anyone has any possible suggestions and thank you.
