### ISSUE TITLE
iOS network bug

### ISSUE THREAD

**Issue by malacca** [facebook/react-native#35610]
### Description

[  if (partContentType != nil) {](https://github.com/facebook/react-native/blob/main/Libraries/Network/RCTNetworking.mm#L114)

alwasy true

need to change to 

```
 if (![partContentType isEqual:[NSNull null]]) {
```

### Version

all

### Output of `npx react-native info`

none

### Steps to reproduce

none

### Snack, code example, screenshot, or link to a repository

none

**Comment by malacca** [comment]
@cortinico 

because `partContentType != nil` alwasy true,  so file content-type will never use a custom value

fox example

```
const form = new FormData();
form.append('raw', {
    uri: file,
    type: 'text/plain',
    name: 'raw',
});

fetch(url, {
  method:"POST",
   body: form
})

```

post file type never use  custom value

I don't know what else to provide, it's the obvious bug

**Comment by cortinico** [comment]
> need to change to
> ```
>  if (![partContentType isEqual:[NSNull null]]) {
> ```

Thanks for reporting this @malacca 
Don't you mind sending a PR for it?

**Comment by malacca** [comment]
@cortinico   Ok, i will sending a PR , let me test it first , make sure that it is correct，

**Comment by malacca** [comment]
https://github.com/facebook/react-native/pull/35640
