### ISSUE TITLE
[node or rn's bug] FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

### ISSUE THREAD

**Issue by fsp1990** [facebook/react-native#3561]
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
node_modules/react-native/packager/packager.sh: line 19: 84934 Abort trap: 6           node "$THIS_DIR/packager.js" "$@"

npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/8BitSpace/.nvm/versions/io.js/v3.1.0/bin/iojs" "/Users/8BitSpace/.nvm/versions/io.js/v3.1.0/bin/npm" "start"
npm ERR! node v3.1.0
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE
npm ERR! Demo@0.0.1 start: `node_modules/react-native/packager/packager.sh`
npm ERR! Exit status 134
npm ERR! 
npm ERR! Failed at the Demo@0.0.1 start script 'node_modules/react-native/packager/packager.sh'.
npm ERR! This is most likely a problem with the Demo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node_modules/react-native/packager/packager.sh
npm ERR! You can get their info via:
npm ERR!     npm owner ls Demo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

**Comment by jsierles** [comment]
@fsp1990 This is likely due to your machine running out of memory. Closing this issue out - feel free to reopen if you're still having this problem!
