### ISSUE TITLE
Compiling JS failed: 28252:33:'{' expected in function expression Buffer size 5748458 starts with: 766172205f5f42554e444c455f535441

### ISSUE THREAD

**Issue by keerthika-priya** [facebook/react-native#35618]
### New Version

0.70.4

### Old Version

0.61.2

### Build Target(s)

iOS simulator debug

### Output of `react-native info`

info Fetching system and libraries information...
(node:17510) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
System:
    OS: macOS 12.6.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 107.89 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.11.0 - /opt/homebrew/bin/npm
    Watchman: 2022.11.14.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 14.0/14A309 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.4 => 0.70.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Issue and Reproduction Steps

I am facing the following issue after upgrading to RN 0.70.4
`Compiling JS failed: 28252:33:'{' expected in
function expression Buffer size 5748458
starts with:
766172205f5f42554e444c455f535441`

**Comment by luutruong** [comment]
I have same issues.

```
"react": "18.1.0",
"react-native": "0.70.6",
```

```
System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 1.01 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.11.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - /opt/homebrew/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.6 => 0.70.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by thanggggg1** [comment]
does it has solution

**Comment by krushalikevadiya** [comment]
Same issue with "react-native": "^0.70.5"
Please suggest some solutions

**Comment by dhayaljaswantgit** [comment]
I'm getting the same, does it has solution?

**Comment by krushalikevadiya** [comment]
I have created new project and moved all the code into newly created project.

**Comment by bradydoll** [comment]
I ran into this issue, however for me it was caused by upgrading `metro-react-native-babel-preset` from 0.73.7 to 0.74.0 (with `react-native` 0.70.5 & 0.70.6). Changing it back to 0.73.7 resolved the issue for me.

**Comment by belkhoujaons** [comment]
changing the version to  0.73.7 of package metro-react-native-babel-preset resolved the issue for me

**Comment by sajadspeed** [comment]
I also had this problem until I realized that I had imported and used a `json` file, but it was empty.

**Comment by novejero95** [comment]
@sajadspeed How did you find out which JSON file was empty? I'm experiencing the same issue, but I didn't add any JSON file within my app. However, I did update several libraries

**Comment by Bar-Maz** [comment]
I've got the same issue because I've been missing a curly bracket in one of my `json` translation files, fixing the file reso;lved the issue.

**Comment by sajadspeed** [comment]
> @sajadspeed How did you find out which JSON file was empty? I'm experiencing the same issue, but I didn't add any JSON file within my app. However, I did update several libraries

This was just my problem, this error may occur for other reasons.

**Comment by 24greyhat** [comment]
this is due to importing an empty json file!

**Comment by vemarav** [comment]
happens after adding reanimated library

**Comment by majidalykhan** [comment]
> I think I have found a normal solution to this problem. I was getting exactly the same error. It's trite when starting and compiling an empty project. **decision**: You have a shortage of RAM memory and processor power. You need to close all unnecessary applications on the PC so that React Native can compile the application. When I tried to compile the application, my CPU was 85% busy, but I closed all unnecessary applications on the PC, now my processor was running at 8%. I only had VS Code open, and I tried to recompile the project. Everything went well. In my case, the problem was a lack of RAM and a lack of free processor power.

This was the issue for me. Thanks.

**Comment by sriharsha-bhasuru** [comment]
> I think I have found a normal solution to this problem. I was getting exactly the same error. It's trite when starting and compiling an empty project. **decision**: You have a shortage of RAM memory and processor power. You need to close all unnecessary applications on the PC so that React Native can compile the application. When I tried to compile the application, my CPU was 85% busy, but I closed all unnecessary applications on the PC, now my processor was running at 8%. I only had VS Code open, and I tried to recompile the project. Everything went well. In my case, the problem was a lack of RAM and a lack of free processor power.

This was the issue for me too. Thank you

**Comment by dukoo** [comment]
> this is due to importing an empty json file!

I confirm, in my project this issue was due to requiring an empty .json file.

**Comment by sntg-p** [comment]
In my case the problem was caused by using a Typescript feature not supported by the version used by the project.

If you are using VS Code, you can make it use the workspace version by calling the `Typescript: Select Typescript Version` command. This way it prevents you from using unsupported features.

**Comment by MbongeniMM** [comment]
> I ran into this issue, however for me it was caused by upgrading `metro-react-native-babel-preset` from 0.73.7 to 0.74.0 (with `react-native` 0.70.5 & 0.70.6). Changing it back to 0.73.7 resolved the issue for me.

How do I check for compatible packages and make sure they align?

**Comment by harutyunian** [comment]
are issue resolved and how? i have a some problem

**Comment by MbongeniMM** [comment]
> are issue resolved and how? i have a some problem

@harutyunian I still have the same issue, however I started using my physical device instead of Android studio and that works perfectly. Just need to make sure that your expo version on your physical device is the same as the one in your dependencies

**Comment by harutyunian** [comment]
i have that issue on my macbook but after restarting computer its fixed, here is my babel configs
`module.exports = function(api) {
  api.cache(true);
  return {
    presets: ["module:metro-react-native-babel-preset"],
    plugins: ['react-native-reanimated/plugin',
    ]
  };
};
`

**Comment by A-AllaaEddine** [comment]
Happened to me today, restarting my pc solved it.

**Comment by mateusmatosleonardo** [comment]
> Aconteceu comigo hoje, reiniciar meu pc resolveu.

Eu estou tendo esse problema depois que fui para o Windows, não acontecia comigo quando eu utilizava o Linux.
Quando isso acontece, eu excluo o meu device emulator e crio novamente.

**Comment by shedworth** [comment]
For me this was caused by a recent commit that included the `satisfies never` Typescript construct (introduced in Typescript 5). Our app still uses Typescript 4. Removing `satisfies never` made this somewhat cryptic error go away.

**Comment by ibrust** [comment]
Regarding the lack of CPU / RAM - when the is the issue the behavior may be inconsistent, but it's not a problem with your machine lacking resources, it's a problem with the emulator - the device has a certain amount of memory configured for it (far less than what any local machine you're using has available). Try increasing the devices heap size and RAM.

**Comment by Witzko** [comment]
Happened to me because of nativewind. Although it worked on iOS but with Android Studio it did not. In the end I guess some Babel issue as well, did not figure it out but removed nativewind from the project at early stage

**Comment by KiddoV** [comment]
> Happened to me today, restarting my pc solved it.

Thanks, solved by restating my PC.

**Comment by MaxInMoon** [comment]
In my case it was about a ";" expected.
It took me a while to notice it was **because I put an `await` at the top level of a .ts file**. It should be in a async fn.
Ironically, I put this `await` to fix an eslint warning.
It didn't trigger any lint or ts warn/error..

**Comment by serdarde** [comment]
> In my case it was about a ";" expected. It took me a while to notice it was **because I put an `await` at the top level of a .ts file**. It should be in a async fn. Ironically, I put this `await` to fix an eslint warning. It didn't trigger any lint or ts warn/error..

Same thing happened to me. This should definitely throw a proper error. 👍🏻
