### ISSUE TITLE
accessibilityLabelledBy Android has an issue when using accessibility scanner

### ISSUE THREAD

**Issue by rveruna** [facebook/react-native#35615]
### Description

When using accessibilityLabelledBy as shown in the [documentation](https://reactnative.dev/docs/accessibility#accessibilitylabelledby-android)

<img width="856" alt="image" src="https://user-images.githubusercontent.com/15161568/207004156-6d8e8346-7827-462e-95aa-193a317df1a0.png">

and running the accessibility scanner on Android, the scanner should show no issues, but instead, it shows 1 suggestion - "Editable item label. This editable TextView has an android:contentDescription. A screen render may read this attribute instead of the editable content when the user is navigating". 

When we run the accessibility scanner, it shouldn't show us any suggestions. 

https://user-images.githubusercontent.com/15161568/207005642-1d03e46a-fc50-49b2-92b6-bbc6fffcc11d.mov

### Version

0.70.6

### Output of `npx react-native info`

System:
    OS: macOS 13.0.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 411.58 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
    Watchman: 2022.10.03.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 28, 29, 30, 31
      Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0
      System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-31 | Google Play Intel x86 Atom_64, android-33 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.12 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.6 => 0.70.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. create a new project
2. add  accessible Text and TextInput as per [documentation](https://reactnative.dev/docs/accessibility#accessibilitylabelledby-android)
3. download the [accessibility scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_GB&gl=US&pli=1)
4. run the scanner on the page
5. notice the scanner shows a suggestion 

### Snack, code example, screenshot, or link to a repository

https://snack.expo.dev/@verunar/courageous-crackers

**Comment by yourjhay** [comment]
same here..
