### ISSUE TITLE
Could not get unknown property 'ExtractJniAndHeadersTask' for project ':ReactAndroid' of type org.gradle.api.Project.

### ISSUE THREAD

**Issue by auguyon** [facebook/react-native#35629]
### Description

I upgraded my RN app from 0.63.4 to 0.70.6, after fixing some issues, I got these two issues and found nothing to fix them.

1 -
>A problem occurred evaluating project ':ReactAndroid'.
> Could not get unknown property 'ExtractJniAndHeadersTask' for project ':ReactAndroid' of type org.gradle.api.Project.
Same as this one [#35441](https://github.com/facebook/react-native/issues/35441)

2 - 
> A problem occurred configuring project ':ReactAndroid'.
> com.android.builder.errors.EvalIssueException: compileSdkVersion is not specified. Please add it to build.gradle

### Version

0.70.6

### Output of `npx react-native info`

warn Package appcenter contains invalid configuration: "dependency.platforms.ios.podspecPath" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
warn Package appcenter-analytics contains invalid configuration: "dependency.platforms.ios.podspecPath" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
warn Package appcenter-crashes contains invalid configuration: "dependency.platforms.ios.podspecPath" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
warn Package native-base contains invalid configuration: "dependency.assets" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
warn Package react-native-background-fetch contains invalid configuration: "dependency.assets" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
warn Package react-native-background-geolocation contains invalid configuration: "dependency.platforms.ios.sharedLibraries" is not allowed,"dependency.assets" is not allowed,"dependency.hooks" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
warn Package react-native-vector-icons contains invalid configuration: "dependency.assets" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
info Fetching system and libraries information...
System:
    OS: macOS 13.0.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 68.17 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.2.0 - ~/.nvm/versions/node/v19.2.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v19.2.0/bin/npm
    Watchman: 2022.12.12.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.6 => 0.70.6
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

I used `npx react-native upgrade`

### Snack, code example, screenshot, or link to a repository

android/build.gradle : https://pastebin.com/LifME16R

android/settings.gradle : https://pastebin.com/XphTqmGt

android/app/build.gradle : https://pastebin.com/5jLy6M8E

./gradlew build --stacktrace --debug --info : https://pastebin.com/RMDUsrd2

**Comment by cortinico** [comment]
> android/app/build.gradle : [pastebin.com/5jLy6M8E](https://pastebin.com/5jLy6M8E)

There are various problems in your `android/app/build.gradle` file.

Specifically in the `dependencies{}` block:

```
dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    //noinspection GradleDynamicVersion
    implementation project(":ReactAndroid")  // From node_modules
    def multidex_version = "2.0.1"
    implementation "androidx.multidex:multidex:$multidex_version"
    implementation 'com.google.firebase:firebase-analytics:17.3.0'
    implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.0.0"
 
    debugImplementation("com.facebook.flipper:flipper:${FLIPPER_VERSION}") {
      exclude group:'com.facebook.fbjni'
    }
 
    debugImplementation("com.facebook.flipper:flipper-network-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.facebook.flipper'
        exclude group:'com.squareup.okhttp3', module:'okhttp'
    }
 
    debugImplementation("com.facebook.flipper:flipper-fresco-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.facebook.flipper'
    }
 
    if (enableHermes) {
        //noinspection GradleDynamicVersion
        implementation("com.facebook.react:hermes-engine:+") { // From node_modules
            exclude group:'com.facebook.fbjni'
        }
    } else {
        implementation jscFlavor
        configurations.all {
            resolutionStrategy.dependencySubstitution {
                substitute(module("com.facebook.react:react-native"))
                    .using(project(":ReactAndroid"))
                    .because("On New Architecture we're building React Native from source")
                substitute(module("com.facebook.react:hermes-engine"))
                    .using(project(":ReactAndroid:hermes-engine"))
                    .because("On New Architecture we're building Hermes from source")
            }
        }
    }
}
```

I would invite you to check the same file from the template:
https://github.com/facebook/react-native/blob/0.70-stable/template/android/app/build.gradle

and make sure you apply the same changes.
