### ISSUE TITLE
TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by mustafauysl** [facebook/react-native#35623]
### Description

It throws this error when focus on any text input.

### Version

0.70.6

### Output of `npx react-native info`

System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Pro
    Memory: 137.27 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.8.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.18.0 - /opt/homebrew/bin/npm
    Watchman: 2022.09.05.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.6 => 0.70.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

After updating the React Native version to 0.70.6, I get this error when I focus any textinput.

### Snack, code example, screenshot, or link to a repository
![Simulator Screen Shot - iPhone 14 - 2022-12-13 at 14 11 08](https://user-images.githubusercontent.com/105643149/207302878-3826716f-b8b7-4f3d-9a63-f60513d9e3f9.png)

**Comment by cortinico** [comment]
Does this happen on a blank project also?

**Comment by mandrewsan** [comment]
@mustafauysl Did you find a fix for this? I am encountering the same issue. Thanks in advance.

**Comment by Namangaraaz** [comment]
Any fixed guys, i am facing this after upgrading RN version 0.66.4 to 0.70.6.

**Comment by naim-lasker** [comment]
@mustafauysl did you fix it? Getting the same issue after upgrading 0.65 to 0.71

**Comment by Namangaraaz** [comment]
@cortinico Buddy! any updates? I can see you marked this issue as closed. But we are facing this in latest versions of RN. Plz help. It is breaking in prod also.

**Comment by Namangaraaz** [comment]
> Does this happen on a blank project also?

Yes @cortinico

**Comment by cortinico** [comment]
If you're facing htis issue on 0.71, on a blank project, please open a separate issue.
