### ISSUE TITLE
[XMLHttpRequest] uncaught exception while trying to upload an image 

### ISSUE THREAD

**Issue by ms88privat** [facebook/react-native#3563]
`xhr.send({uri: localFilePath})` is not working anymore in 0.13.0-rc. (it did work in 0.10.0 for sure)

can somebody read the exception thrown by Xcode7?

```
[tid:com.facebook.React.JavaScript] 'constructor'
2015-10-21 11:10:11.900 [info][tid:com.facebook.RCTAssetsLibraryImageLoader][RCTAssetsLibraryImageLoader.m:90] [PERF ASSETS] Loading IMG_0004.JPG at size {1668, 2500}, which is larger than screen size {750, 1334}
2015-10-21 11:10:31.433 Paramount[1563:8361] *** Assertion failure in -[RCTDownloadTask validateRequestToken:](), /Users/marcelschulze/dev/intern/paramount/paramount-rnapp/node_modules/react-native/Libraries/Network/RCTDownloadTask.m:69
2015-10-21 11:10:31.441 Paramount[1563:8361] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Unrecognized request token: (null)'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010daaec65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010cf22bb7 objc_exception_throw + 45
	2   CoreFoundation                      0x000000010daaeaca +[NSException raise:format:arguments:] + 106
	3   Foundation                          0x000000010cb37a57 -[NSAssertionHandler handleFailureInFunction:file:lineNumber:description:] + 169
	4   Paramount                           0x000000010c7c8687 -[RCTDownloadTask validateRequestToken:] + 391
	5   Paramount                           0x000000010c7c89fd -[RCTDownloadTask URLRequest:didReceiveResponse:] + 93
	6   Paramount                           0x000000010c7c1ec0 __43-[RCTImageLoader sendRequest:withDelegate:]_block_invoke + 624
	7   Paramount                           0x000000010c7c0910 RCTDispatchCallbackOnMainQueue + 160
	8   Paramount                           0x000000010c7c083b __87-[RCTImageLoader loadImageWithTag:size:scale:resizeMode:progressBlock:completionBlock:]_block_invoke120 + 107
	9   Paramount                           0x000000010c7bb7b0 __96-[RCTImageStoreManager loadImageForURL:size:scale:resizeMode:progressHandler:completionHandler:]_block_invoke + 96
	10  Paramount                           0x000000010c7ba7fb __49-[RCTImageStoreManager getImageForTag:withBlock:]_block_invoke + 91
	11  libdispatch.dylib                   0x0000000110fb8186 _dispatch_call_block_and_release + 12
	12  libdispatch.dylib                   0x0000000110fd7614 _dispatch_client_callout + 8
	13  libdispatch.dylib                   0x0000000110fbfa1c _dispatch_main_queue_callback_4CF + 1664
	14  CoreFoundation                      0x000000010da161f9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	15  CoreFoundation                      0x000000010d9d7dcb __CFRunLoopRun + 2043
	16  CoreFoundation                      0x000000010d9d7366 CFRunLoopRunSpecific + 470
	17  GraphicsServices                    0x0000000112a7aa3e GSEventRunModal + 161
	18  UIKit                               0x000000010f51b8c0 UIApplicationMain + 1282
	19  Paramount                           0x000000010c6eb56f main + 111
	20  libdyld.dylib                       0x000000011100b145 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 
```

**Comment by satya164** [comment]
@ms88privat Hey, out of topic, but can you point me to an example where you're doing this?

**Comment by ms88privat** [comment]
@satya164 not sure exactly what you mean. 

I can not provide working example because I upload the Image to my amazon s3 bucket via a signed_url. 

The image itself is cropped and the filepath looks something like that "rct-image-store://1"

```
var xhr = new XMLHttpRequest();
          xhr.open('PUT', resp.signed_request);
          xhr.setRequestHeader('x-amz-acl', 'public-read');
          xhr.setRequestHeader('Content-Type', type);
          xhr.onload = function() {
              if (xhr.status === 200) {
                  console.log('result', 'ok');
                  resolve({uri: resp.url});
              } else {
                console.log('result', 'err', xhr);
                reject('err xhr status');
              }
          };
          xhr.onerror = function(err) {
              console.log('err xhr', err);
              reject(err);
          };
          xhr.send({uri: filePath});
```

**Comment by satya164** [comment]
@ms88privat I just wanted to know how to upload files to aws. I aksed because I saw you sending file as uri. Didn't know we could do that. It would be great if you can point me to the docs, having a hrd time finding it. Thanks a lot.

**Comment by ms88privat** [comment]
@satya164 it worked like shown above in react native. There is an example in the UI Explorer, which works similar. In addition to that I found another github issue some time ago, which pointed me to use this pattern without the "Formdata" object. 

Or do you mean the server side implementation / amazon settings to get the signed_request_url?

**Comment by satya164** [comment]
I meant the upload handling code only. Thank you. I'll try the above example.

**Comment by ms88privat** [comment]
@satya164 did it work for you?

This is a serious problem for me right now :(

@nicklockwood Could you please have a look at my error message in the starting post? It was working before RN v. 0.11/0.12 ~

**Comment by satya164** [comment]
@ms88privat I couldn't get the above to work, the response from s3 was that it needs multipart/formdata. So, I changed it to formdata and it works for me.

I'm using it on Android though, and not iOS. So can't confirm about your issue.

**Comment by ms88privat** [comment]
@satya164 @nicklockwood Ok, I should have tried this more early, but it does still work with standard images / filePaths. Only if they get cropped and the filePath changes to `rct-image-store://1` it doesn't work anymore.

**Comment by nicklockwood** [comment]
Can you tell me what the actual "filePath" value you're using looks like?

Also, this looks suspiciously like an error that was fixed a while ago. Is this still happening for you with the latest version? (the latest master, I mean, not the latest release)

**Comment by ms88privat** [comment]
@nicklockwood I will test it with the latest version. But for now, the cropped filePath (with `ImageEditingManager.cropImage` )  looks exactly like `rct-image-store://0`. Not cropped it looks like this: `assets-library://asset/asset.JPG?id=152C49B3-1894-42E4-8AFD-86979BC84225&ext=JPG`. Both filePaths are working with the `<Image />`, but only the second one I can upload via xhr.

**Comment by ms88privat** [comment]
@nicklockwood YES, it did work with the latest master version! Thank you very much :+1: 
PS: the filePaths look still the same, but it is working now.
