### ISSUE TITLE
Horizontal Flatlist working on android but not working on iOS

### ISSUE THREAD

**Issue by MiteshJabuani** [facebook/react-native#35630]
### Description

Two Flatlist in page 
<View>
<FlatList
            bounces={false}
            scrollEnabled={true}
            automaticallyAdjustContentInsets={true}
            data={this.props.accountData}
            horizontal={true}
            keyExtractor={(item, index) => index.toString()}
            pagingEnabled={true}
            ref={r => this.accountDetailsListRef = r}
            renderItem={({item, index}) => this._renderItem(item, index)}
            showsHorizontalScrollIndicator={false}
            onViewableItemsChanged={this.onViewChanged}
            viewabilityConfig={{
              itemVisiblePercentThreshold: 100,
            }}
          />
</View>
<View>
            <FlatList
              bounces={false}
              scrollEnabled={true}
              automaticallyAdjustContentInsets={true}
              data={this.state.transactions}
              renderItem={({item}) => this.renderList(item)}
              keyExtractor={(item, index) => index.toString()}
            />
</View>

here second flatlist working fine as per android but in first flatlist not scrollable 

### Version

0.70.1

### Output of `npx react-native info`

npx react-native run-ios

### Steps to reproduce

create app with two view and add two flatlist

### Snack, code example, screenshot, or link to a repository

Two Flatlist in page 
<View>
<FlatList
            bounces={false}
            scrollEnabled={true}
            automaticallyAdjustContentInsets={true}
            data={this.props.accountData}
            horizontal={true}
            keyExtractor={(item, index) => index.toString()}
            pagingEnabled={true}
            ref={r => this.accountDetailsListRef = r}
            renderItem={({item, index}) => this._renderItem(item, index)}
            showsHorizontalScrollIndicator={false}
            onViewableItemsChanged={this.onViewChanged}
            viewabilityConfig={{
              itemVisiblePercentThreshold: 100,
            }}
          />
</View>
<View>
            <FlatList
              bounces={false}
              scrollEnabled={true}
              automaticallyAdjustContentInsets={true}
              data={this.state.transactions}
              renderItem={({item}) => this.renderList(item)}
              keyExtractor={(item, index) => index.toString()}
            />
</View>

**Comment by bael4** [comment]
i faced such problem i can't find any solution at first it worked on ios but now it doesn't work if you found a solution please share))

**Comment by MiteshJabuani** [comment]
Added scroll view and added horizontal flat list added verticle flat list added scroll view with horizontal={true} property.

**Comment by bael4** [comment]
I don't seem to understand you)

  <ScrollView style={{ backgroundColor: "green"}}>
          <FlatList
            horizontal={true}
            showsHorizontalScrollIndicator={false}
            data={categories}
            renderItem={({ item }) => (
              <CategoryCard
                item={item}
                onTap={() => {
                  alert("Category tapped");
                }}
              />
            )}
            keyExtractor={(item) => `${item.id}`}
          />
        </ScrollView>

**Comment by MiteshJabuani** [comment]
@bael4 Do you use multiple Flatlist in scroll view?

**Comment by bael4** [comment]
@MiteshJabuani  no just one, Well I'm going to use multiple Flatlist

**Comment by MiteshJabuani** [comment]
@bael4 

<Scrollview automaticallyAdjustContentInsets={false} bounces={true} showsVerticalScrollIndicator={false} contentContainerStyle={{flex grow:1}} nestedScrollEnabled={true}
<FlatList
horizontal={true}
…./>
<View style={flex:1}>
<ScrollView horizontal={true} bounces={false}>
  <FlatList
horizontal={false}
    ….
  />
</ScrollView>
</View>

<View style={flex:1}>
<ScrollView horizontal={true} contentContainerStyle={{flex: 1}}>
  <FlatList
horizontal={false}
    …..
  />
</ScrollView>
</View>

</Scrollview>

My structure someting like this and its working in both iOS and Android
