### ISSUE TITLE
Android 13 permission issue

### ISSUE THREAD

**Issue by Ghoral** [facebook/react-native#35638]
### Description

Hi,
I am unable to request permission for storage. It always returns `{"android.permission.READ_EXTERNAL_STORAGE": "never_ask_again", "android.permission.WRITE_EXTERNAL_STORAGE": "never_ask_again"}` whenever I try to ask for permission. I tried everything but still the the permission is not allowed on Android 13, sdk 33.

Your help will be really appreciated.

Thank you.

### Version

0.70.6

### Output of `npx react-native info`

System:
    OS: macOS 13.0
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 332.93 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
    Yarn: 1.22.19 - ~/node_modules/.bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.17.1/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: ^9.0.0 => 9.0.0 
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

- declare permission issue in manifest file
 `  <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />`

- request for storage permission
`const permission = [
      PermissionsAndroid.PERMISSIONS.READ_EXTERNAL_STORAGE,
      PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE,
    ]; 
 const granted = await PermissionsAndroid.requestMultiple(permission);
`

- result
`{"android.permission.READ_EXTERNAL_STORAGE": "never_ask_again", "android.permission.WRITE_EXTERNAL_STORAGE": "never_ask_again"}`

### Snack, code example, screenshot, or link to a repository

<img width="567" alt="Screenshot 2022-12-14 at 15 10 51" src="https://user-images.githubusercontent.com/49188349/207557517-9ba759ea-60f0-4dc7-b09e-b7973df94724.png">

**Comment by MohammadAzimi** [comment]
Based on android 13 behavior changes, maybe [this link](https://developer.android.com/about/versions/13/behavior-changes-13#granular-media-permissions), from the android document could help!

**Comment by divbhalala** [comment]
I am facing the same issue.

**Comment by yestay90** [comment]
@Ghoral , turns out that if you targed sdk 33 you dont need to ask permission. Here is code in AndroidManifest.xml:
` <uses-permission android:name="android.permission.READ_MEDIA_IMAGES" />
    <uses-permission android:name="android.permission.READ_MEDIA_VIDEO" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"
                 android:maxSdkVersion="32" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"
                 android:maxSdkVersion="29" />`

**Comment by MaximeBoceno** [comment]
@yestay90 thank's !
more détails on android doc:
[https://developer.android.com/reference/android/Manifest.permission#READ_EXTERNAL_STORAGE]
hope it helps

**Comment by abdullahIsa** [comment]
> WRITE_EXTERNAL_STORAGE

Hello, does this apply to all android versions or for lower android versions i still need to ask for permission ?

**Comment by Ghoral** [comment]
yes In android 13 no permission is needed

**Comment by abdullahIsa** [comment]
I was able to fix mine, you should do it this way, i am still testing across different tester devices.

```
// folder write permit/request example
const folderWritePermit = async () => {
  let deviceVersion = DeviceInfo.getSystemVersion();
  if (deviceVersion >= 13) return true;
  return await permitingsCheck(PERMISSIONS.ANDROID.WRITE_EXTERNAL_STORAGE);
};
const folderWritePermitReq = async () => {
  let deviceVersion = DeviceInfo.getSystemVersion();
  if (deviceVersion >= 13) return true;
  return await permitingsReq(PERMISSIONS.ANDROID.WRITE_EXTERNAL_STORAGE);
};

const permitingsCheck = data => {
  return new Promise((resolve, reject) => {
    check(data)
      .then(result => {
        switch (result) {
          case RESULTS.UNAVAILABLE:
            resolve(false);
            break;
          case RESULTS.DENIED:
            resolve(false);
            break;
          case RESULTS.LIMITED:
            resolve(false);
            break;
          case RESULTS.GRANTED:
            resolve(true);
            break;
          case RESULTS.BLOCKED:
            resolve(false);
            break;
        }
      })
      .catch(error => {
        resolve(false);
      });
  });
};

const permitingsReq = data => {
  return new Promise((resolve, reject) => {
    request(data)
      .then(result => {
        switch (result) {
          case RESULTS.UNAVAILABLE:
            resolve(false);
            break;
          case RESULTS.DENIED:
            resolve(false);
            break;
          case RESULTS.LIMITED:
            resolve(false);
            break;
          case RESULTS.GRANTED:
            resolve(true);
            break;
          case RESULTS.BLOCKED:
            resolve(false);
            break;
        }
      })
      .catch(error => {
        resolve(false);
      });
  });
};
```

**Comment by nikolal** [comment]
I can confirm that in SDK 33 changing:

 `READ_EXTERNAL_STORAGE` -------> `READ_MEDIA_IMAGES`
 
 fixes the issue for me.
 
 https://developer.android.com/reference/android/Manifest.permission#READ_EXTERNAL_STORAGE

**Comment by A-Vijay** [comment]
let deviceVersion = DeviceInfo.getSystemVersion();
let granted = PermissionsAndroid.RESULTS.DENIED;
if(deviceVersion >= 13){
   granted = PermissionsAndroid.RESULTS.GRANTED;
}else{
  granted = await PermissionsAndroid.request( PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE );
}

fixes the issue for me.
as Android version 13 no permission is needed.

**Comment by gkasireddy202** [comment]
@A-Vijay  - How can use below code for document picker(react-native-document-picker) for Android 13. 
let deviceVersion = DeviceInfo.getSystemVersion();
let granted = PermissionsAndroid.RESULTS.DENIED;
if(deviceVersion >= 13){
granted = PermissionsAndroid.RESULTS.GRANTED;
}else{
granted = await PermissionsAndroid.request( PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE );
}

**Comment by Mihai-github** [comment]
> deviceVersion

You are right, this is the way to go.
PS:

**Comment by Mihai-github** [comment]
> let deviceVersion = DeviceInfo.getSystemVersion(); let granted = PermissionsAndroid.RESULTS.DENIED; if(deviceVersion >= 13){ granted = PermissionsAndroid.RESULTS.GRANTED; }else{ granted = await PermissionsAndroid.request( PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE ); }
> 
> fixes the issue for me. as Android version 13 no permission is needed.



You are right, this is the way to go.

PS: device version returns a string, not a number so the if condition needs to be updated 👍

**Comment by Ghoral** [comment]
You dont need to add permission specifically.

If it is for notification you need to have  targetSdkVersion = 33 (at least) and change your code.

import messaging from '@react-native-firebase/messaging';

` await messaging().requestPermission();

    if (PlatformUtility.isAndroid) {
      PermissionUtility.requestPermission(
        'android.permission.POST_NOTIFICATIONS',
      );
    }`

for other permissions follow documentation.

> let deviceVersion = DeviceInfo.getSystemVersion(); let granted = PermissionsAndroid.RESULTS.DENIED; if (deviceVersion >= 13) { granted = PermissionsAndroid.RESULTS.GRANTED; }
> 
> is this one correct?

**Comment by abhishekjmd** [comment]
> let deviceVersion = DeviceInfo.getSystemVersion(); let granted = PermissionsAndroid.RESULTS.DENIED; if(deviceVersion >= 13){ granted = PermissionsAndroid.RESULTS.GRANTED; }else{ granted = await PermissionsAndroid.request( PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE ); }
> 
> fixes the issue for me. as Android version 13 no permission is needed.

dont we have to ask permissions

**Comment by eisodev** [comment]
I came here because of Googles new requirements to target Android 13 (API 33) by 31st of August 2023: https://support.google.com/googleplay/android-developer/answer/11926878?hl=en&sjid=9848068658593839850-EU 

We got 3 weeks notice of this (2 weeks essentially when the email was delayed by one week).

If you are on lower React Native version than 0.71 to handle all new Android 13 permissions which we now have to target before August 31st, might only be in EU, not sure! If you are on, say 0.68 like us, with limited resources to make this quite major upgrade (new architecture etc)), you could use react-native-permissions instead of permissions from react-native. react-native-permissions from version 3.6.0 has these new Android 13 permissions (https://github.com/zoontek/react-native-permissions/releases/tag/3.6.0). 3.6.0 only have: 
"react": ">=16.13.1",
"react-native": ">=0.63.3" 
set as peerDependencies, so you should be fine there.

**Comment by rexchoppers** [comment]
> 

^ This is the solution I went with in the end. On 0.63.5 (Upgrade coming soon) Uses react-native-permissions for completely everything instead and that seems to have worked, albeit we needed to update a few unrelated dependencies

**Comment by ajakka** [comment]
> I can confirm that in SDK 33 changing:
> 
> `READ_EXTERNAL_STORAGE` -------> `READ_MEDIA_IMAGES`
> 
> fixes the issue for me.
> 
> https://developer.android.com/reference/android/Manifest.permission#READ_EXTERNAL_STORAGE

This worked fine for until today when my phone got updated to Android 14 and now It shows me this:

![image](https://github.com/facebook/react-native/assets/25665218/b016d8f5-2542-4425-be84-637ad1567acc)

Any Idea why that happens?

**Comment by SanaTabassum25** [comment]
Granted Permissions: {"android.permission.CAMERA": "granted", "android.permission.POST_NOTIFICATIONS": "granted", "android.permission.READ_EXTERNAL_STORAGE": "never_ask_again", "android.permission.WRITE_EXTERNAL_STORAGE": "never_ask_again"}
im getting the same issue tried using MANAGE_EXTERNAL_STORAGE for android versions greater than 10 can anyone help?

**Comment by Samide47** [comment]
> @A-Vijay - How can use below code for document picker(react-native-document-picker) in Android 13. let deviceVersion = DeviceInfo.getSystemVersion(); let granted = PermissionsAndroid.RESULTS.DENIED; if(deviceVersion >= 13){ granted = PermissionsAndroid.RESULTS.GRANTED; }else{ granted = await PermissionsAndroid.request( PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE ); }

this works for me 🥇

**Comment by WebtualUtsav** [comment]
if (Platform.Version >= 33) {
        await fileDownload(url, fileType, downloadPath, dispatch);
      } else {
        const granted = await PermissionsAndroid.request(
          PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE,
          {
            title: 'Permission',
            message: 'App needs storage access to download.',
            // buttonNeutral: 'Ask Me Later',
            buttonNegative: 'Cancel',
            buttonPositive: 'Grant',
          },
        );
        console.log('granted' , PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE);
        if (granted == PermissionsAndroid.RESULTS.GRANTED) {
          await fileDownload(url, fileType, downloadPath, dispatch);
        } else {
          Alert.alert(
            'Permission Denied',
            `Kindly go to settings and allow storage permission to download.`,[
              ({
                text: 'Cancel',
                onPress: () => {},
                style: 'cancel',
              },
              {
                text: 'Go to Settings',
                onPress: () => {
                  Linking.openSettings();
                },
                style: 'default',
              })
            ],
          );
        }
      }
      
      i facing error in android version 11 and 10 
      if i give permission but stil shoe the alert pop up and in console get the never_ask_again error even i granted.

**Comment by NithinKulal** [comment]
Thanks
