### ISSUE TITLE
[iOS Security] Weak hashing Algorithms used in react-native

### ISSUE THREAD

**Issue by Manikanta-GEP** [facebook/react-native#35641]
### Description

Weak hashing algorithms like MD5 and SHA1 in the react-core libraries and these are identified as security vunarabilities.

### Version

0.62.2 and 0.68.0

### Output of `npx react-native info`

System:
    OS: macOS 12.3.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 346.29 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.6 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.1.0 - /usr/local/bin/npm
    Watchman: 2021.10.18.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 26, 27, 28, 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8815526
    Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. Open Xcode.
2. Search for CC_MD5 or SHA1

### Snack, code example, screenshot, or link to a repository

<img width="402" alt="RN-0 68 0-SHA1" src="https://user-images.githubusercontent.com/65960651/207581969-d68cc907-3c09-451e-ba5c-b2d9d364a44f.png">
<img width="404" alt="RN-0 68 0-MD5" src="https://user-images.githubusercontent.com/65960651/207582059-c8bf9af5-6a8c-449a-b7a5-19d33c59bc7d.png">

**Comment by KodeyThomas** [comment]
Hashing is only weak depending on the context of where it is used. For example, if you were storing sensitive information such as a password you would not use a weak hashing algorithm like those you have mentioned. 

However, if you needed to store the hash of a file then you could still use SHA1 or MD5. Also, there are a ton of cryptographic functions that still require the use of those functions.

**Comment by cortinico** [comment]
> Hashing is only weak depending on the context of where it is used. For example, if you were storing sensitive information such as a password you would not use a weak hashing algorithm like those you have mentioned.
> However, if you needed to store the hash of a file then you could still use SHA1 or MD5. Also, there are a ton of cryptographic functions that still require the use of those functions.

Thanks for providing this @KodeyThomas 
I'm closing for the aforementioned reason.
