### ISSUE TITLE
Combining stickyHeaderIndices with initialScrollIndex on a FlatList causes unexpected rendering and positioning

### ISSUE THREAD

**Issue by rjdestigter** [facebook/react-native#35653]
### Description

When using `initialScrollIndex` in combination with `stickyHeaderIndices` the list will start at the incorrect position or even render erratically  

https://user-images.githubusercontent.com/14314519/207951331-5e6c5eb3-1dc8-4d88-ba05-f279ee95ec11.mov

Should be starting at index 6 rather than 4 here:

<img width="408" alt="image" src="https://user-images.githubusercontent.com/14314519/207951429-446a0a7e-ea6f-492f-985f-e979cce6a062.png">

It behaves correctly when using only one the two problem props.

### Version

0.70.6

### Output of `npx react-native info`

```
System:
    OS: macOS 12.5
    CPU: (10) x64 Apple M1 Pro
    Memory: 42.86 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.21.2 - ~/.nvm/versions/node/v14.21.2/bin/node
    Yarn: Not Found
    npm: 6.14.17 - ~/.nvm/versions/node/v14.21.2/bin/npm
    Watchman: 2022.09.26.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/robertdestigter/.rvm/gems/ruby-2.7.5/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 14.0/14A309 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.6 => 0.70.6
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1. Create a new react-native project using the TypeScript template.
2. Add lodash as a dependency
3. Replace App.tsx with the provided code

### Snack, code example, screenshot, or link to a repository

```tsx
// App.tsx

/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * Generated with the TypeScript template
 * https://github.com/react-native-community/react-native-template-typescript
 *
 * @format
 */

import React from 'react';
import {FlatList, SafeAreaView, StyleSheet, Text, View} from 'react-native';
import {range} from 'lodash';

const dataSize = 12;
const contentSize = 550;
const data = range(0, dataSize);
const headerIndices = range(0, dataSize, 2);
const isEven = (value: number) => value % 2 === 0;

const getHeaderItemLayout = (index: number) => ({
  length: 50,
  index,
  offset: index === 0 ? 0 : (index / 2) * (50 + contentSize),
});

const getContentItemLayout = (index: number) => ({
  length: contentSize,
  index,
  offset: ((index - 1) / 2) * (50 + contentSize) + 50,
});

const renderHeader = (index: number) => (
  <View style={styles.header}>
    <Text>{index}</Text>
  </View>
);

const renderContent = (index: number) => (
  <View style={styles.content}>
    <Text>{index}</Text>
  </View>
);

const renderItem = ({index}: {index: number}) =>
  isEven(index) ? renderHeader(index) : renderContent(index);

const getItemLayout = (_: unknown, index: number) =>
  isEven(index) ? getHeaderItemLayout(index) : getContentItemLayout(index);

const App = () => {
  return (
    <SafeAreaView style={styles.container} key="4">
      <View style={styles.wrapper}>
        <FlatList
          data={data}
          windowSize={6}
          stickyHeaderIndices={headerIndices}
          getItemLayout={getItemLayout}
          renderItem={renderItem}
          initialScrollIndex={dataSize / 2}
        />
      </View>
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  container: {
    backgroundColor: 'limegreen',
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  wrapper: {
    backgroundColor: 'pink',
    width: 320,
    height: 600,
    // borderWidth: 1,
  },
  header: {
    height: 50,
    backgroundColor: 'cyan',
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    fontWeight: 'bold',
  },
  content: {
    height: contentSize,
    backgroundColor: 'yellow',
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    fontWeight: 'bold',
  },
});

export default App;
```

**Comment by NickGerleman** [comment]
Does the issue still repro without stickyHeaderIndices? The issue looks suspiciously like an offset from getItemLayout doesn’t jive with real usage.

I would also expect this to give a warning that the default keyExtractor fell back to index. Since there is not an “id” or “key” prop on the data to key on.

A lot of this code changed as well in 0.71. Much of the code is reused, but it is worth checking if the issue still reproes.

**Comment by rjdestigter** [comment]
> Does the issue still repro without stickyHeaderIndices? The issue looks suspiciously like an offset from getItemLayout doesn’t jive with real usage. But it looked sane at a glance.

No the issue specifically pops up combining `stickyHeaderIndices` with `initialScrollIndex`. Omitting either will cause the issue not to show up.

### With both:

https://user-images.githubusercontent.com/14314519/219406792-97c68aa5-a09c-4487-a8c9-5c9d69392b24.mov

### With `stickyHeaderIndices` but not `initialScrollIndex`

https://user-images.githubusercontent.com/14314519/219407203-2dc49ecb-53d6-4f18-804e-297c5e893106.mov

### With `initialScrollIndex` but not `stickyHeaderIndices`

https://user-images.githubusercontent.com/14314519/219408212-37c48827-f23c-4abb-93f7-ea0e606e312d.mov

**Comment by blanket-admin** [comment]
@rjdestigter how about it? did you find a solution? :(
