### ISSUE TITLE
NodeWatcher.watchdir error！！  what's this ?

### ISSUE THREAD

**Issue by fsp1990** [facebook/react-native#3565]
7:45:27 PM] <START> Building Dependency Graph
[7:45:27 PM] <START> Crawling File System
 ERROR  watch ENOSPC
{"code":"ENOSPC","errno":"ENOSPC","syscall":"watch"}
Error: watch ENOSPC
    at exports._errnoException (util.js:837:11)
    at FSWatcher.start (fs.js:1231:11)
    at Object.fs.watch (fs.js:1257:11)
    at NodeWatcher.watchdir (/home/iojsServer8083/node_modules/react-native/node_modules/sane/src/node_watcher.js:144:20)
    at Walker.<anonymous> (/home/iojsServer8083/node_modules/react-native/node_modules/sane/src/node_watcher.js:351:12)
    at emitTwo (events.js:87:13)
    at Walker.emit (events.js:172:7)
    at /home/iojsServer8083/node_modules/react-native/node_modules/sane/node_modules/walker/lib/walker.js:69:16
    at /home/iojsServer8083/node_modules/react-native/node_modules/graceful-fs/graceful-fs.js:140:16
    at FSReqWrap.oncomplete (fs.js:82:15)

See http://facebook.github.io/react-native/docs/troubleshooting.html
for common problems and solutions.

npm ERR! Linux 3.13.0-32-generic
npm ERR! argv "/root/.nvm/versions/io.js/v3.3.1/bin/iojs" "/root/.nvm/versions/io.js/v3.3.1/bin/npm" "start"
npm ERR! node v3.3.1
npm ERR! npm  v2.14.3
npm ERR! code ELIFECYCLE
npm ERR! BTYAppIos3React@3.1.2 start: `node_modules/react-native/packager/packager.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the BTYAppIos3React@3.1.2 start script 'node_modules/react-native/packager/packager.sh'.
npm ERR! This is most likely a problem with the BTYAppIos3React package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node_modules/react-native/packager/packager.sh
npm ERR! You can get their info via:

**Comment by ide** [comment]
We recommend installing watchman on Linux but officially support only OS X. There is a new page on the docs that mentions watchman on Linux which may fix your bug: https://facebook.github.io/react-native/docs/linux-windows-support.html#content

**Comment by ile** [comment]
This helped me:

http://stackoverflow.com/questions/34662574/node-js-getting-error-nodemon-internal-watch-failed-watch-enospc

```
echo fs.inotify.max_user_watches=582222 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
```
