### ISSUE TITLE
non-std c++ exception [turn of wifi]

### ISSUE THREAD

**Issue by meftunca** [facebook/react-native#35652]
### Description

![simulator_screenshot_E5999915-2347-4841-A6B2-84A9AAAB108A](https://user-images.githubusercontent.com/19187204/207833527-e7ec0865-7749-4338-a965-695072953020.png)
I get this error in the application when the internet is down. Probably because of the c++ library linked to server requests this error is happening

### Version

0.70.4

### Output of `npx react-native info`

System:
    OS: macOS 13.0
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 532.25 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.2.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 8.19.3 - /usr/local/bin/npm
    Watchman: 2022.12.12.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/devloops/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: Dolphin 2021.3.1 Patch 1 Dolphin 2021.3.1 Patch 1
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.0-rc.2 => 0.71.0-rc.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

I get this error in the application when the internet is down. Probably because of the c++ library linked to server requests this error is happening

### Snack, code example, screenshot, or link to a repository

![simulator_screenshot_E5999915-2347-4841-A6B2-84A9AAAB108A](https://user-images.githubusercontent.com/19187204/207833527-e7ec0865-7749-4338-a965-695072953020.png)
I get this error in the application when the internet is down. Probably because of the c++ library linked to server requests this error is happening

**Comment by murat-mehmet** [comment]
Having same problem at random times +1

**Comment by rathodnilesh99** [comment]
Having same problem

@react-native-bot  @reactjs-bot

**Comment by joacub** [comment]
Same problem

**Comment by SamucaDev** [comment]
The same problem, need to try if some lib I installed causes this

**Comment by neufeng** [comment]
Same problem after upgrade rn to 0.72.0

**Comment by l941230** [comment]
can you re open this issue. I am seeing the same crash on RN 0.72.5

**Comment by fantexi023** [comment]
I am seeing the same crash on RN 0.72.5 ,too
Why the feeling given to me is that some questions here won't be fixed but closed??

**Comment by fantexi023** [comment]
> can you re open this issue. I am seeing the same crash on RN 0.72.5

did u have fixed it?
