### ISSUE TITLE
Words predictions are hidden if keyboardType="url"

### ISSUE THREAD

**Issue by MykolaSauliak** [facebook/react-native#35651]
### Description

Autofill suggestions are not visible if keyboardType='url' for TextInput

Problem:
 
<img src="https://user-images.githubusercontent.com/16925900/207822208-ae6e7fa0-dd47-4050-9cb6-e335784ad7c2.jpeg" width=250 />

Without keyboardType prop:

<img alt="screenshot_without_keyboard_type" src="https://user-images.githubusercontent.com/16925900/207822343-139ea2f8-bbc6-4a05-8acf-52d133c4c3a6.jpeg" width=250 />

Mozilla browser:

<img alt="screenshot_20221215-111719_firefox" src="https://user-images.githubusercontent.com/16925900/207822445-607d0125-86c4-4a05-963a-df4b2e48699f.jpeg" width=250 />

### Version

0.7

### Output of `npx react-native info`

 Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
    Watchman: 2022.11.14.00 - /usr/local/bin/watchman

### Steps to reproduce

- Use current project or install with "npx react-native init ..."
- Put TextInput on the screen
- setup keyboardType="url"

### Snack, code example, screenshot, or link to a repository

import React from 'react';
import {
  SafeAreaView,
  StatusBar,
  TextInput,
  useColorScheme,
} from 'react-native';
import {
  Colors,
} from 'react-native/Libraries/NewAppScreen';

const App = () => {
  const isDarkMode = useColorScheme() === 'dark';

  const backgroundStyle = {
    flex:1,
    backgroundColor: isDarkMode ? Colors.darker : Colors.lighter,
  };

  return (
    <SafeAreaView style={{flex:1}}>
      <StatusBar
        barStyle={isDarkMode ? 'light-content' : 'dark-content'}
        backgroundColor={backgroundStyle.backgroundColor}
      />
      <TextInput 
        keyboardType='url'
      />
    </SafeAreaView>
  );
};

export default App;

**Comment by XantreGodlike** [comment]
I think in mozilla browser it's not url type of keyboard, because this field in browser includes regular search. So I think this issue should be closed, because no autocomplete for Urls is expected behaviour

**Comment by XantreGodlike** [comment]
> There are no text input in snack. I will try to reproduce by myself
```jsx
import React from "react";
import {
  SafeAreaView,
  StatusBar,
  TextInput,
  useColorScheme,
} from "react-native";
import { Colors } from "react-native/Libraries/NewAppScreen";

const App = () => {
  const isDarkMode = useColorScheme() === "dark";

  const backgroundStyle = {
    flex: 1,
    backgroundColor: isDarkMode ? Colors.darker : Colors.lighter,
  };

  return (
    <StatusBar
      barStyle={isDarkMode ? "light-content" : "dark-content"}
      backgroundColor={backgroundStyle.backgroundColor}
    />
  );
};

export default App;
```

**Comment by XantreGodlike** [comment]
### I think, that found source of the problem.

Consider android textview inputtype:
https://developer.android.com/reference/android/R.styleable#TextView_inputType
textUri should be 0x11 = InputType.TYPE_CLASS_TEXT |  InputType.TYPE_TEXT_VARIATION_URI.
InputType.TYPE_TEXT_VARIATION_URI = 0x10
InputType.TYPE_CLASS_TEXT = 0x1.
![image](https://user-images.githubusercontent.com/57757211/209438896-1fdcf5e5-5aa5-4c30-9f8e-aca71729d381.png)


But in React Native java code it is just InputType.TYPE_TEXT_VARIATION_URI:
`flagsToSet = InputType.TYPE_TEXT_VARIATION_URI;`
Path to place:
`ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactTextInputManager.java`
L876-L877

I think can fix it, but I am newbie and can't check this guess.
`flagsToSet = InputType.TYPE_TEXT_VARIATION_URI | InputType.TYPE_CLASS_TEXT`

**Comment by XantreGodlike** [comment]
@robhogan how can i edit labels?
