### ISSUE TITLE
Fabric `Text` elements don't respect `maxFontSizeMultiplier`

### ISSUE THREAD

**Issue by amgleitman** [facebook/react-native#35658]
### Description

While playing around with the new Dynamic Type feature, I found that `Text` elements don't respect the `maxFontSizeMultiplier` prop.

Expected behavior: The middle line never grows larger than `style.fontSize * maxFontSizeMultiplier` (17 &times; 2 = 34) points.

Actual behavior: At the largest accessibility setting, the middle line gets much bigger.

The following screenshots show the issue at the largest accessibility-associated content size, that is, [`UIContentSizeCategoryAccessibilityExtraExtraExtraLarge`](https://developer.apple.com/documentation/uikit/uicontentsizecategoryaccessibilityextraextraextralarge):

| Paper (right) | Fabric (wrong) |
|-|-|
| ![screenshot paper](https://user-images.githubusercontent.com/717674/208001879-fe866d96-0886-47f6-abe6-2deb3ff63731.png) | ![screenshot fabric](https://user-images.githubusercontent.com/717674/208001902-e17af2f6-6383-4547-9b8a-4aa2b6b61810.png) |

### Version

main

### Output of `npx react-native info`

```
System:
    OS: macOS 13.0.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 119.28 MB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.0/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
    Watchman: 2022.10.31.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1. Add the code snippet below to any RN app. (I used RNTester.)
2. Play around with the preferred content size in an iOS simulator, including the accessibility-specific content sizes.

### Snack, code example, screenshot, or link to a repository

``` jsx
<View>
  <Text allowFontScaling={false} style={{fontSize: 34}}>
    This is fixed at 34 pt
  </Text>
  <Text maxFontSizeMultiplier={2} style={{fontSize: 17}}>
    This is scaled automatically
  </Text>
  <Text allowFontScaling={false} style={{fontSize: 17}}>
    This is fixed at 17 pt
  </Text>
</View>
```

**Comment by aleksamrakovic** [comment]
This is still na issue, reproduced on react native 0.71

**Comment by mysport12** [comment]
This is still an issue on 0.76.1. Can this be reopened?

**Comment by cortinico** [comment]
> pe feature, I found that `Text` elem

Please open a new issue + provide a repro
