### ISSUE TITLE
[MapView] set customized ping dialog with Images or links

### ISSUE THREAD

**Issue by nosensezzz** [facebook/react-native#3566]
While I am using MapView, I found that I am only able to set title or subtitle as a String for ping dialog, is there anyway that I can make the display dialog a real <View>? So I can arrange layout, add Image or link into it, that would be much valuable mapview.

**Comment by jaygarcia** [comment]
Annotations don't do that out of the box.  :( 

From what I've seen: You'll need to extend Map View to include custom annotation implementations.

**Comment by jaygarcia** [comment]
This is supposed to be working as of 0.18.0.  @nosensezzz , please close this issue. 
/cc @brentvatne

**Comment by janicduplessis** [comment]
@facebook-github-bot close

**Comment by janicduplessis** [comment]
@facebook-github-bot close
