### ISSUE TITLE
Can't use PR artifact tarball in my react native App 

### ISSUE THREAD

**Issue by osama256** [facebook/react-native#35663]
### Description

I'm trying to test react native PR changes in my App, I downloaded the tarball from `CircleCI job`

![Screen Shot 2022-12-16 at 2 29 29 PM](https://user-images.githubusercontent.com/51829206/208098642-262e6e1a-9221-4aa3-8ea4-c9e12da77810.png)

I created a simple app using `npx react-native init test` and run `yarn add <path to tarball>` inside the root folder.

When run `nom run android` I get this error
 

"Could not read script '/Users/osama/Desktop/test/node_modules/react-native/react.gradle' as it does not exist."

### Version

0.72.3

### Output of `npx react-native info`

System:
    OS: macOS 11.6
    CPU: (4) x64 Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
    Memory: 76.81 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.15.1 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.11.0 - /usr/local/bin/npm
    Watchman: 2022.11.28.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    Android SDK:
      Android NDK: 21.4.7075529
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 13.0/13A233 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: ../react-native-1000.0.0-19f7106b6.tgz => 1000.0.0-19f7106b6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

- npx react-native init test
- cd test
- yarn add ../react-native-1000.0.0-19f7106b6.tgz
- npm run android

### Snack, code example, screenshot, or link to a repository

![Screen Shot 2022-12-16 at 2 22 21 PM](https://user-images.githubusercontent.com/51829206/208097399-35c2191a-34b9-453f-b87e-fe57f7ac05e9.png)

**Comment by cortinico** [comment]
> I created a simple app using `npx react-native init test` and run `yarn add <path to tarball>` inside the root folder.

I would suggest to do the following instead. 
Create simple app from the nightly:

```
npx react-native init RNNightly --version nightly
```

and then `yarn add <your tarball>`

**Comment by osama256** [comment]
Another error.

![Screen Shot 2022-12-16 at 7 36 27 PM](https://user-images.githubusercontent.com/51829206/208156590-da0ead4b-4555-4a1d-85d6-aa451aa6b793.png)
