### ISSUE TITLE
Execution failed for task ':react-native-navigation:compileReactNative63DebugKotlin'.

### ISSUE THREAD

**Issue by arihantop** [facebook/react-native#35660]
### Description

while running npx react-native run-android

### Version

0.63.5

### Output of `npx react-native info`

System:
    OS: macOS 12.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 65.30 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 8.17.0 - ~/.nvm/versions/node/v8.17.0/bin/node
    Yarn: Not Found
    npm: 6.14.10 - ~/Desktop/Work/RNMobileApp/node_modules/.bin/npm
    Watchman: 2022.12.12.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 13.0/13A233 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: ^0.63.5 => 0.63.5 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

npx react-native run-android

### Snack, code example, screenshot, or link to a repository

my package.json file :

{
  "name": "@halaplaytech/androidapp_india",
  "version": "1.1.0",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint .",
    "postinstall": "patch-package"
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "^1.13.4",
    "@react-native-community/art": "^1.2.0",
    "@react-native-community/clipboard": "^1.5.1",
    "@react-native-google-signin/google-signin": "^6.0.0",
    "@react-native-picker/picker": "^1.16.1",
    "@twotalltotems/react-native-otp-input": "^1.3.11",
    "antd-mobile-rn": "2.3.3",
    "appcenter": "4.1.0",
    "appcenter-analytics": "4.1.0",
    "appcenter-crashes": "4.1.0",
    "axios": "^0.26.1",
    "crypto-js": "3.3.0",
    "expo": "40.0.0",
    "fetch": "^1.1.0",
    "form-data": "^3.0.0",
    "html-entities": "^2.0.2",
    "install": "0.13.0",
    "lodash.debounce": "4.0.8",
    "mobx": "6.0.4",
    "mobx-react": "7.0.5",
    "moment": "2.29.1",
    "native-echarts": "0.5.0",
    "npm": "6.14.10",
    "numeral": "2.0.6",
    "patch-package": "^6.4.7",
    "payu-non-seam-less-react": "^2.4.0",
    "react": "17.0.1",
    "react-native": "^0.63.5",
    "react-native-android-location-enabler": "^1.2.2",
    "react-native-android-sms-listener": "^0.8.0",
    "react-native-backdrop": "^2.1.2",
    "react-native-chart-kit": "^6.11.0",
    "react-native-checkbox": "2.0.0",
    "react-native-code-push": "^7.0.1",
    "react-native-collapsible": "1.5.3",
    "react-native-datepicker": "1.7.2",
    "react-native-device-info": "^7.3.1",
    "react-native-document-picker": "^8.1.1",
    "react-native-elements": "3.4.1",
    "react-native-exit-app": "1.1.0",
    "react-native-fbsdk-next": "4.2.0",
    "react-native-fetch-blob": "0.10.8",
    "react-native-firebase": "5.6.0",
    "react-native-flash-message": "^0.1.23",
    "react-native-geocoding": "0.5.0",
    "react-native-geolocation-service": "^5.3.0-beta.2",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-heic-converter": "1.3.0",
    "react-native-image-crop-picker": "^0.35.2",
    "react-native-image-picker": "3.2.1",
    "react-native-iphone-x-helper": "1.3.1",
    "react-native-keyboard-aware-scroll-view": "0.9.3",
    "react-native-linear-gradient": "2.5.6",
    "react-native-loading-spinner-overlay": "2.0.0",
    "react-native-material-menu": "~1.2.0",
    "react-native-material-ui": "1.30.1",
    "react-native-message-bar": "2.0.10",
    "react-native-modal": "^11.10.0",
    "react-native-moengage": "^7.4.1",
    "react-native-navigation": "^7.14.0",
    "react-native-onesignal": "^4.4.1",
    "react-native-pager-view": "5.1.8",
    "react-native-picker-select": "^8.0.4",
    "react-native-popup-dialog": "0.18.3",
    "react-native-progress": "4.1.2",
    "react-native-progress-circle": "^2.1.0",
    "react-native-simple-radio-button": "2.7.4",
    "react-native-sms-retriever": "^1.1.1",
    "react-native-snap-carousel": "3.9.1",
    "react-native-splash-screen": "^3.2.0",
    "react-native-svg": "^12.1.1",
    "react-native-svg-charts": "^5.4.0",
    "react-native-swiper": "^1.6.0-nightly.5",
    "react-native-vector-icons": "7.1.0",
    "react-native-view-more-text": "^2.1.0",
    "react-native-webview": "^11.26.0",
    "react_native_mqtt": "^1.3.1",
    "realm": "10.1.2",
    "rn-content-loader": "0.0.6",
    "rn-sliding-up-panel": "1.3.1",
    "rn-viewpager": "^1.2.9",
    "singular-react-native": "^3.1.10",
    "socket.io-client": "2.4.0",
    "victory-native": "^35.5.5"
  },
  "devDependencies": {
    "@babel/core": "^7.12.10",
    "@babel/plugin-proposal-decorators": "^7.12.13",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "^7.18.0",
    "jest": "^26.6.3",
    "jetifier": "^2.0.0",
    "metro-react-native-babel-preset": "^0.64.0",
    "react-test-renderer": "16.13.1"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Comment by arihantop** [comment]
got the fix

**Comment by reymon359** [comment]
Hey @arihantop I am facing the same issue. 

Could you please share with me what fix did you apply? 😄
