### ISSUE TITLE
React native screen and react safe area view is crashing , my react native version is 0.70.6

### ISSUE THREAD

**Issue by oyis12** [facebook/react-native#35671]
### Description

i install 
"react-native-safe-area-context": "^4.4.1",
    "react-native-screens": "^3.18.2"
on my project and its crashing my project , i have try everything i could but no solution,,,please help

### Version

0.70.6

### Output of `npx react-native info`

* What went wrong:
A problem occurred configuring project ':react-native-safe-area-context'.
> Could not open cp_proj generic class cache for build file 'C:\Users\sam6ix\natives\project1\node_modules\react-native-safe-area-context\android\build.gradle' (C:\Users\sam6ix\.gradle\caches\7.5.1\scripts\ew8rpjljdg0mxo5hg38qk6hkd).
   > BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 63

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s

    at makeError (C:\Users\sam6ix\natives\project1\node_modules\@react-native-community\cli-platform-android\node_modules\execa\index.js:174:9)
    at C:\Users\sam6ix\natives\project1\node_modules\@react-native-community\cli-platform-android\node_modules\execa\index.js:278:16
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runOnAllDevices (C:\Users\sam6ix\natives\project1\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:109:5)
    at async Command.handleAction (C:\Users\sam6ix\natives\project1\node_modules\@react-native-community\cli\build\index.js:142:9)
info Run CLI with --verbose flag for more details.

### Steps to reproduce

when ever i run npm run android (am not using expo) it crashes

### Snack, code example, screenshot, or link to a repository

import React from 'react';

import {createNativeStackNavigator} from '@react-navigation/native-stack';
import {NavigationContainer, DefaultTheme} from '@react-navigation/native';
import Home from './screens/Home';
import Details from './screens/Details';
const Stack = createNativeStackNavigator();

const theme = {
  ...DefaultTheme,
  colors: {
    ...DefaultTheme.colors,
    backround: 'transparent',
  },
};

const App = () => {
  return (
    <NavigationContainer theme={theme}>
      <Stack.Navigator
        screenOptions={{headerShown: false}}
        initialRouteName="Home">
        <Stack.Screen name="Home" component={Home} />
        <Stack.Screen name="Details" component={Details} />
      </Stack.Navigator>
    </NavigationContainer>
  );
};

export default App;

**Comment by iBotPeaches** [comment]
My guess is I see this line

> Unsupported class file major version 63

Which I believe is Java 19 and v70 of RN only supports Gradle 7.5, which I believe stops at Java 18 support.

**Comment by oyis12** [comment]
so how do i fix it?

**Comment by hanarotg** [comment]
> so how do i fix it?

Try download java 18 or lower LTS version
