### ISSUE TITLE
onViewableItemsChanged is not working properly with the viewabilityConfig.minimumViewTime

### ISSUE THREAD

**Issue by RomeroDiver** [facebook/react-native#35682]
### What I'm trying to do?

I'm implementing a feature where I want to track what items of the FlatList are visible to the user - imagine a horizontal carousel. For this, I'm trying to use `onViewableItemsChanged` with the configuration like this 
```
viewabilityConfig={{
          minimumViewTime: 1000,
          itemVisiblePercentThreshold: 90,
}}
``` 

The problem here is that the `onViewableItemsChanged` is called a few times - mostly similar the way described in [this issue](https://github.com/facebook/react-native/issues/33110)

### What have I found?

I've been looking through the code of FlatList and its helpers, and this part of the code I can't reason about - in the ViewabilityHelper.onUpdate function the timeout is set based on the minimumViewTime value for every time the onUpdate function is called. And then in ViertualizedList, the function is called from a few places, which means that we queue few timeouts - with different values. In my case, e.g. I could spot `onScroll` and `updateCellsToRender` calling the onUpdate. If i add clearTimeout before adding a new timeout, everything seems to work properly. I'm not sure this solution is generic enough for the component, but for me at least it is what I would expect from the minimumViewTime setting. This is what I changed
```
if (this._config.minimumViewTime) {
      console.log('SETTING TIMEOUT')
      const handle = setTimeout(() => {
        /* $FlowFixMe[incompatible-call] (>=0.63.0 site=react_native_fb) This
         * comment suppresses an error found when Flow v0.63 was deployed. To
         * see the error delete this comment and run Flow. */
        this._timers.delete(handle);
        console.log('INSIDE TIMEOUT')
        this._onUpdateSync(
          viewableIndices,
          onViewableItemsChanged,
          createViewToken,
        );
      }, this._config.minimumViewTime);
      this._timers.forEach(clearTimeout); // <--- this line here
      /* $FlowFixMe[incompatible-call] (>=0.63.0 site=react_native_fb) This
       * comment suppresses an error found when Flow v0.63 was deployed. To see
       * the error delete this comment and run Flow. */
      this._timers.add(handle);
    }
```

### Version

0.66.4

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 13.0.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 700.16 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
    Watchman: 2022.07.04.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8512546
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.2 => 17.0.2 
    react-native: 0.66.4 => 0.66.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Not sure if this steps are universally reproducable(for me this happens 100%):

Prerequisites:
- view with a FlatList, horizontal, custom renderItem function, data with many items that user can scroll through

Steps to reproduce:
- Scroll the list left or right

Actual result:
- the onViewableItemsChanged is called a few times with different values

Expected result:
- the onViewableItemsChanged called once with the latest result

### Snack, code example, screenshot, or link to a repository

```
<FlatList
  data={data}
  initialNumToRender={6}
  onViewableItemsChanged={trackItemsPresented}
  viewabilityConfig={{
    minimumViewTime: 1000,
    itemVisiblePercentThreshold: 90,
  }}
  horizontal
  keyExtractor={(item) => item.id}
  renderItem={renderItem}
/>;

const renderItem = useCallback(
  ({ item, index }) => {
    return (
      <Component
        onTilePress={() => tilePressHandler(item, index)}
        item={item}
        styles={getStyles(itemType)}
        imageType={getImageType(itemType)}
      />
    );
  },
  [itemType, tilePressHandler]
);
```

**Comment by NickGerleman** [comment]
Hmm, yeah the code in ViewabilityHelper around this does seems kind of suspect. Contributions welcome here (esp if we can add test coverage).

**Comment by Aksana-Tsishchanka** [comment]
I have the same issue with react-native 0.72.6. minimumViewTime is ignored and does not work at all
