### ISSUE TITLE
Delay (freeze) of UI onPress in FlatLists on Android devices

### ISSUE THREAD

**Issue by maksimLobachevskiy** [facebook/react-native#35684]
### Description

On Android devices UI onPress freezes for 2-3 seconds when opening a screen or refreshing the list using pull to refresh, or when dispatching event (get new items from the server). All FlatList are optimized according to the react native recommendations.

### Version

0.66.5

### Output of `npx react-native info`

System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1
    Memory: 303.45 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: Not Found
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
    Watchman: 2022.07.04.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8309675
    Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: ^0.66.5 => 0.66.5 
    react-native-macos: Not Found

### Steps to reproduce

Enter the screen with FlatList (no matter how many items in list). First 2-3 seconds UI onPress is not responding. The same issue during the page refresh.
On some modern Android devices works fine or some less powerful the delay 3 seconds (for ex. Samsung X-cover 5).

### Snack, code example, screenshot, or link to a repository

```
const renderItem = useCallback(
    ({ item }) => {
      return <ListItem item={item} showPriority onPress={onPress} />;
    },
    [onPress],
  );

return (
        <FlatList
          data={data}
          renderItem={renderItem}
          keyExtractor={keyExtractor}
          maxToRenderPerBatch={10}
          initialNumToRender={10}
          refreshControl={<RefreshControl {...refreshControlProps} />}
        />
      );
```

**Comment by NickGerleman** [comment]
Best guess is your “onPress” is causing a state change which leads to some expensive operation. I think it’s unlikely FlatList is directly related.

**Comment by maksimLobachevskiy** [comment]
> Best guess is your “onPress” is causing a state change which leads to some expensive operation. I think it’s unlikely FlatList is directly related.

I tried to add a button with onPress simple function which returns console.log 'onpress'. And it works also with such delay when the screen loads for the first time or refresh
