### ISSUE TITLE
Animated component best practice 

### ISSUE THREAD

**Issue by aniss** [facebook/react-native#3568]
While I was playing with the Animated component I got confused as it provide many ways to use or update the value.

for example: 

```
 onScroll={this.AnimatedEvent(
   [{nativeEvent: {contentOffset: {x: this.state.scrollX}}}]
 )
```
If I want to pass down scrollX as props to another component 

```
<childComponent left={scrollX} />
```

What's the best case of using the animation inside the "childComponent" ?

#### Case 1
```
<Animated.View style={{opacity: this.props.left.interpolate({
inputRange: [0, 100],
outputRange: [0, 1]
})}} />
```
#### Case 2
```
Animated.spring(this.state.opacity, {
toValue: this.props.left.interpolate({
inputRange: [0, 100],
outputRange: [0, 1]
})});
```

**Comment by browniefed** [comment]
@facebook-github-bot stack-overflow

**Comment by browniefed** [comment]
I would pass down the animated value and let it do whatever it needs to do via interpolate.
