### ISSUE TITLE
> Task :app:processDebugResources FAILED w: Detected multiple Kotlin daemon sessions at build/kotlin/sessions  Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

### ISSUE THREAD

**Issue by wangyupeng993** [facebook/react-native#35688]
### Description

run ./gradlew --warning-mode all 

> Configure project :app
IncrementalTaskInputs has been deprecated. This is scheduled to be removed in Gradle 8.0. On method 'IncrementalTask.taskAction$gradle_core' use 'org.gradle.work.InputChanges' instead. Consult the upgrading guide for further information: https://docs.gradle.org/7.5.1/userguide/upgrading_version_7.html#incremental_task_inputs_deprecation
        at react_7phk1yqu1tkfobut62as3a0h3$_run_closure8$_closure11$_closure14.doCall(/Volumes/HPP500/project/ReactNative/RNCmpanda/node_modules/react-native/react.gradle:395)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)

### Version

0.70.6

### Output of `npx react-native info`

OS: macOS ventura 13.1
    CPU: (8) x64 Intel(R) Core(TM) i7-8557U CPU @ 1.70GHz
    Memory: 2.16 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - /usr/local/bin/node
    Yarn: Not Found
    npm: 8.19.2 - /usr/local/bin/npm
    Watchman: 2022.12.12.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.6 => 0.70.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

npm run android

### Snack, code example, screenshot, or link to a repository

1. npx react-native init AwesomeProject
2. npm run android

**Comment by Morton4idps** [comment]
Your IDEs:
`Android Studio: 2021.3 AI-213.7172.25.2113.9123335` is too old.

You have to download the latest Android Studio version Flamingo
https://developer.android.com/studio/preview?utm_source=android-studio

**Comment by motogod** [comment]
Your IDEs:
Android Studio: 2021.3 AI-213.7172.25.2113.9123335 is too old.

You have to download the latest Android Studio version Flamingo
https://developer.android.com/studio/preview?utm_source=android-studio

**Comment by motogod** [comment]
Try this way:
1. under `Preferences/Build, Execution, Deploument/Build Tools/Gradle`
set the Gradle JDK for 11

2. File/Invalidate Catches, execute restart

<img width="985" alt="截圖 2022-12-23 下午3 03 55" src="https://user-images.githubusercontent.com/17781603/209288704-b00c1b63-3d8f-444c-8869-e8d18f8838fe.png">

**Comment by wangyupeng993** [comment]
@motogod My android studio is like this
<img width="982" alt="image" src="https://user-images.githubusercontent.com/39769538/209439940-9009d649-295f-4967-96b1-bc1cede356fb.png">
