### ISSUE TITLE
Bump react peer dependency to 18.2.0

### ISSUE THREAD

**Issue by Soviut** [facebook/react-native#35683]
### Description

I'm installing `@testing-library/react-native@11.5.0` which has a peer dependency of `react@18.2.0`. I updated to React `18.2.0` but got a peer dependency error from `react-native@0.70.6` because it still has a peer dependency for `react@18.1.0`.

It would be good to push a version bump that updates the peer dependency for `react@18.2.0`

The latest master does have this version bump, it's just not in a release.

### Version

0.70.6

### Output of `npx react-native info`

```
System:
    OS: macOS 12.5
    CPU: (8) arm64 Apple M2
    Memory: 430.59 MB / 24.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.1 - /opt/homebrew/opt/node@16/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - /opt/homebrew/opt/node@16/bin/npm
    Watchman: 2022.11.14.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^18.2.0 => 18.2.0 
    react-native: github:facebook/react-native => 1000.0.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

- using npm 7+ which forces peer dependency installs
- install `react@18.2.0`
- install `react-native@0.70.6`
- install `@testing-library/react-native@11.5.0`
- observe the peer dependency warning

### Snack, code example, screenshot, or link to a repository

![image](https://user-images.githubusercontent.com/226882/208531629-d4d62208-e6bd-425c-8aa4-fa1128592744.png)

**Comment by NickGerleman** [comment]
React Native 0.70 is coupled to React 18.1. RN 0.71 allows React 18.2. You should keep these matched. 

From the screenshot and a quick check, @testing-library/react-native@11.5.0 allows any version of React after 16.

**Comment by Soviut** [comment]
I didn't realize there was a 0.71 version. The [docs](https://reactnative.dev/versions
) shows that 0.70 is the latest and the unreleased next version is master.

![image](https://user-images.githubusercontent.com/226882/208847738-d7cc8410-fe1d-4a61-8f32-839223cede54.png)

Similarly, installing `react-native@latest` from npm yields `0.70.6`.

Once I saw your message I checked the tags on npm. I can see the `0.71.0-rc.5` is under the `next` tag. This would be helpful to include in the docs (yes, I'd be willing to see if I can make a PR for it). It also might be useful to include what version of React the peer dependency expects in the versions table in the docs as well.

![image](https://user-images.githubusercontent.com/226882/208848444-b57cbbdd-9205-4ca7-b010-de3653e3f75a.png)

**Comment by Soviut** [comment]
@NickGerleman I'll close this thread but would still like to hear your feedback regarding the docs and whether I should attempt a PR.

**Comment by NickGerleman** [comment]
The docs will be bumped when 0.71 is released (early January). But TLDR, it is not safe to change the version of React out of band with the version of React Native, so an app targeting 0.70 should keep on 18.1.

**Comment by Soviut** [comment]
@NickGerleman it gets tricky when you have things like React Native Testing Library which are already targeting React 18.2.0 in its peer dependency.
