### ISSUE TITLE
Installing Bundler Error

### ISSUE THREAD

**Issue by ankurchauhan0701** [facebook/react-native#35696]
### Description

Ignoring executable-hooks-1.6.1 because its extensions are not built. Try: gem pristine executable-hooks --version 1.6.1
Ignoring ffi-1.15.5 because its extensions are not built. Try: gem pristine ffi --version 1.15.5
Ignoring gem-wrappers-1.4.0 because its extensions are not built. Try: gem pristine gem-wrappers --version 1.4.0

### Version

0.70.6

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 12.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 523.84 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.5.0 - /usr/local/bin/npm
    Watchman: 2022.12.12.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/madhu/.rvm/rubies/ruby-2.7.5/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.6 => 0.70.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

This issue is produced when I create new project with "npx react-native init AwesomeProject" command. 

### Snack, code example, screenshot, or link to a repository

<img width="1427" alt="Screenshot 2022-12-21 at 5 32 18 PM" src="https://user-images.githubusercontent.com/71865213/208900941-1e048b8d-80d8-40e1-a5a6-9608e23f04c1.png">

**Comment by khuongviettai** [comment]
cd ios 
bundle install
bundle exec pod install
