### ISSUE TITLE
inspector not show component path any more

### ISSUE THREAD

**Issue by wmuker** [facebook/react-native#35697]
### Description

after upgraded to  0.70.6,  we coudn't inspect component to figure their path any more

before 

![image](https://user-images.githubusercontent.com/102019520/208911533-5eaf28cd-12ea-45cd-af7d-179b0fd3923e.png)

now: 

<img width="341" alt="image" src="https://user-images.githubusercontent.com/102019520/208911979-c978ce8c-38c6-49f5-ad47-bc2f6f786443.png">

### Version

0.70.6

### Output of `npx react-native info`

System:
    OS: macOS 13.0
    CPU: (8) arm64 Apple M1 Pro
    Memory: 66.86 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.2 - /usr/local/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 8.1.2 - /usr/local/bin/npm
    Watchman: 2022.11.07.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.6 => 0.70.6
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

-

### Snack, code example, screenshot, or link to a repository

-

**Comment by wmuker** [comment]
the  first picture was copied from https://stackoverflow.com/questions/73171944/how-to-inspect-react-native-element-with-component-name

**Comment by danieloi** [comment]
same issue here

**Comment by cortinico** [comment]
Closing as the React Native version this report refers to is not supported anymore
