### ISSUE TITLE
FormData with Blob content does not work on mobile devices

### ISSUE THREAD

**Issue by jju-copsgmbh** [facebook/react-native#35698]
### Description

When we run fetch with FormData that contains a Blob, the fetch request crashes. 

No error is shown, but logcat logs

java.lang.IllegalStateException: Multipart body must have at least one part.
Observed on multiple versions of React native - from even 0.67.x up to 0.70.6

From my debugging attempts, I believe that the blob is destroyed on line 33 here:
https://github.com/facebook/react-native/blob/main/Libraries/Network/convertRequestBody.js

### Version

0.70.6-0.68.0

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: Linux 5.19 Ubuntu 22.10 22.10 (Kinetic Kudu)
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700H
    Memory: 3.61 GB / 31.08 GB
    Shell: 5.2.2 - /bin/bash
  Binaries:
    Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.18.0/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.0/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.6 => 0.70.6 
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

run "fetch" with a body that is FormData and contains a blob

In the attached example:
- run node mockApi.js to start the mock api
- install packages
- run yarn start -> the request fails and logcat displays the mentioned error
- When the same request is made from the browser (open demonstration.html from the example), it works

### Snack, code example, screenshot, or link to a repository

https://github.com/jju-copsgmbh/react-native-blob-error

**Comment by abdullahIsa** [comment]
Hello, I have the same issue on react-native 0.70.6, any solution?

Error 
![image](https://user-images.githubusercontent.com/49385380/210186752-04bd6322-687f-408d-85b1-0a50fd4b37cf.png)

**Comment by abdullahIsa** [comment]
Hello, does anyone have a solution for this, really dragging development down :(

**Comment by ellouzeskandercs** [comment]
Hi @abdullahIsa and @jju-copsgmbh, can you confirm that the bug exists on both android and ios ? 
In fact, using the FormData object in React Native is not similar to the web. You should pass a FormDataValue as second paramater of the `append` function : `FormDataValue = string | {name?: string, type?: string, uri: string}` (the uri can be a data-uri, but there is also a bug using data-uri on Android for which I have created a [PR](https://github.com/facebook/react-native/pull/36132)). So, there is probably a bug in the typing of the append function of FormData that should be fixed. Try to change your code to use the correct typing.
Hope this helps :)

**Comment by abdullahIsa** [comment]
> Hi @abdullahIsa and @jju-copsgmbh, can you confirm that the bug exists on both android and ios ? In fact, using the FormData object in React Native is not similar to the web. You should pass a FormDataValue as second paramater of the `append` function : `FormDataValue = string | {name?: string, type?: string, uri: string}` (the uri can be a data-uri, but there is also a bug using data-uri on Android for which I have created a [PR](https://github.com/facebook/react-native/pull/36132)). So, there is probably a bug in the typing of the append function of FormData that should be fixed. Try to change your code to use the correct typing. Hope this helps :)

Hello, i already fixed this in react-native 0.70.6 by reinstall whole project again, somehow that fixed it on my side, thanks.

**Comment by channeladam** [comment]
> You should pass a FormDataValue as second paramater of the `append` function :

Thank you @ellouzeskandercs !!!!!

**Comment by reyhanadp** [comment]
> Hi @abdullahIsa and @jju-copsgmbh, can you confirm that the bug exists on both android and ios ? In fact, using the FormData object in React Native is not similar to the web. You should pass a FormDataValue as second paramater of the `append` function : `FormDataValue = string | {name?: string, type?: string, uri: string}` (the uri can be a data-uri, but there is also a bug using data-uri on Android for which I have created a [PR](https://github.com/facebook/react-native/pull/36132)). So, there is probably a bug in the typing of the append function of FormData that should be fixed. Try to change your code to use the correct typing. Hope this helps :)

Hi @ellouzeskandercs , Can you tell me how to fix it without upgrading react native version?
