### ISSUE TITLE
[Crash] RCTImageBlurUtils.m BlurRadius Crash

### ISSUE THREAD

**Issue by OskarEichler** [facebook/react-native#35706]
### Description

We are having an issue with RCTImageBlurUtils.m causing a Kernel crash for some images.

The images we identified are all pretty minimal (black and white, with a lot of black pixels). Not sure if this is related and the blur algorithm simply doesn't have enough information to go by, for most other images everything works normal.

I attached some of the images that are causing the crash below. We tried both a blurRadius of 5, as well as 18. Behavior is the same and it always results in a crash:
`Thread 3: EXC_BAD_ACCESS (code=1, address=0x13d54c4c8)`

### Version

0.70.6

### Output of `npx react-native info`

System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 7.53 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.19.2 - ~/trackstats/node_modules/.bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /Users/Oskar/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.3.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^18.2.0 => 18.2.0 
    react-native: ^0.70.6 => 0.70.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

```
<ImageBackground
        blurRadius={18}
        source={{uri: 'https://i.scdn.co/image/ab67616d0000b2737663b2f75fe4d8fb2cac8c27'}}
/>

<ImageBackground
        blurRadius={5}
        source={{uri: 'https://i.scdn.co/image/ab67616d0000b273d5a219b270d74a266131df18'}}
/>

```
Both of those images are crashing the application for us (potentially because they are mostly black?)

### Snack, code example, screenshot, or link to a repository

![Screenshot 2022-12-23 at 10 48 55](https://user-images.githubusercontent.com/62393985/209261072-6f2fcd36-0fa4-4596-9b08-7cec39f408a4.jpg)

[crash-log.txt](https://github.com/facebook/react-native/files/10291642/crash-log.txt)

**Comment by OskarEichler** [comment]
Following up here as this is pretty serious and reproducible crash that occurs on our production apps.

**Comment by shohelahamad** [comment]
Good day to everyone. We are also having the same issue on our production app with version RN 0.70.6. any suggestions ?

**Comment by ababol** [comment]
I've the same issue ☝️  (blurRadius + black and white image cause a crash)

**Comment by OskarEichler** [comment]
Yes it seems to happen for images that don't have enough color information. Black / White / Grey all cause crashes. This is really bad as quite a lot of users are impacted by this. Would be great if someone from the React Native team can chime in here!

**Comment by Shaninnik** [comment]
Same issue here, started seeing this recently (probably have not seen this before just because it only happens for certain images). RN 0.70.5 / hermes enabled, old arch, production app

**Comment by OskarEichler** [comment]
Pretty serious issue... would be grateful if someone can look into this! 🙌🏼

**Comment by AdriaRios** [comment]
We can also reproduce the issue on production:

RN 0.71.6 / hermes enabled

**Comment by yevhenlv** [comment]
Faced with this bug. My styles for blured Image was

`image: {
    ...StyleSheet.absoluteFillObject,
   width: 'some width',
   height: 'some height',
}`

And if I change styles to 
`image: {
   position: 'absolute',
   width: 'some width',
   height: 'some height',
}` and (!important) don't use **top** property - have app without crash.

**Comment by yevhenlv** [comment]
Faced with this bug. My styles for blured Image was

`image: {
    ...StyleSheet.absoluteFillObject,
   width: 'some width',
   height: 'some height',
}`

And if I change styles to 
`image: {
   position: 'absolute',
   width: 'some width',
   height: 'some height',
}` and (!important) don't use **top** property - have app without crash.

**Comment by OskarEichler** [comment]
@matrush @sammy-SC @steveccable Sorry for tagging you here, but this is a pretty serious kernel crash, and I saw that the three of you previously fixed major issues with this function. Would really appreciate it you can have a look 🙏🏼

**Comment by OskarEichler** [comment]
Fix has been merged!

**Comment by OskarEichler** [comment]
Unfortunately this fix does not seem to reliably resolve the crashes. I created a second PR that addresses the issue:
https://github.com/facebook/react-native/pull/37546

**Comment by sammy-SC** [comment]
Hello @OskarEichler,

I would like to take a closer look at this but I can't reproduce your test plan. Is there anything I missed in test plan or is just just rendering those two images?

**Comment by OskarEichler** [comment]
@sammy-SC Yes correct, applying a blur-radius on those two images causes an immediate crash because the ARGB method can't handle the image. First I was under the impression that it was due to greyscaled images being excluded from the previous step of being converted to ARGB, which is why I opened the following PR: https://github.com/facebook/react-native/pull/37546

However, it turned out that they still caused a crash, possibly because of the new UIGraphicsImageRenderer not properly aligning the bitmap data. I opted to reverse back to the older UIGraphicsBeginImageContextWithOptions which works reliably, however might be a bit slower as the API is older: https://github.com/facebook/react-native/pull/37546

There could be a path to use the newer UIGraphicsImageRenderer, however as the new API does not provide a lot of customizability it would involve writing more code and dealing with additional complexity, particularly when dealing with memory management in order to manually ensure that the buffer is properly formatted and aligned. 

Are you able to reproduce the crash on your side when blurring the images?

**Comment by sammy-SC** [comment]
@OskarEichler I actually can't reproduce it. I have tried simulator and device both debug and production builds.

**Comment by OskarEichler** [comment]
@sammy-SC Maybe check if you can reproduce it based on what someone else experienced here: 
https://github.com/facebook/react-native/issues/35364

https://snack.expo.dev/@saurabhkanswalquizizz/imagebackground-blurradius

**Comment by sammy-SC** [comment]
@OskarEichler 
is the screenshot attached to this issue the same as the attached crashlog?
The screenshot has crash on thread 3. The attached crashlog crashes on thread 0 within destructor of `FFFastImageView`.

**Comment by sammy-SC** [comment]
@OskarEichler on the screenshot on the first message on this issue, what is value of `tempBufferSize`? It is not visible on the screenshot and I think it could give me a good pointer to where the crash is coming from.

My current theory is that it is 0. Calling malloc with 0 is legal but calling `vImageBoxConvolve_ARGB8888` with tempBuffer of size 0 leads to the same crash you have in the screenshot. We do not guard against that right now.

**Comment by OskarEichler** [comment]
@sammy-SC Just ran it again - right now it's only happening when building to physical device. Please find all of the info below, and let me know if you need anything else.

![Screenshot 2023-05-29 at 14 24 35](https://github.com/facebook/react-native/assets/62393985/16d222ee-7869-482f-936b-90822468ac30)

Error: Thread 32: EXC_BAD_ACCESS (code=1, address=0x1472a0438)

Debug Info:

```
dataSource	CFDataRef	0x283a8e760	0x0000000283a8e760
imageRef	CGImageRef	0x1380abb60	0x00000001380abb60
buffer1	vImage_Buffer	
data	void *	0x1471d8000	0x00000001471d8000
height	vImagePixelCount	640
width	vImagePixelCount	640
rowBytes	size_t	1280
bytes	size_t	819200
buffer2	vImage_Buffer	
data	void *	0x14b2c8000	0x000000014b2c8000
height	vImagePixelCount	640
width	vImagePixelCount	640
rowBytes	size_t	1280
tempBuffer	void *	0x14b5fc000	0x000000014b5fc000
boxSize	uint32_t	51dataSource	CFDataRef	0x283a8e760	0x0000000283a8e760
imageRef	CGImageRef	0x1380abb60	0x00000001380abb60
buffer1	vImage_Buffer	
data	void *	0x1471d8000	0x00000001471d8000
height	vImagePixelCount	640
width	vImagePixelCount	640
rowBytes	size_t	1280
bytes	size_t	819200
buffer2	vImage_Buffer	
data	void *	0x14b2c8000	0x000000014b2c8000
height	vImagePixelCount	640
width	vImagePixelCount	640
rowBytes	size_t	1280
tempBuffer	void *	0x14b5fc000	0x000000014b5fc000
boxSize	uint32_t	51
```

**Comment by OskarEichler** [comment]
@sammy-SC If this is not helpful, please let me know how I can export more helpful logs for you! 🙏🏼

**Comment by sammy-SC** [comment]
@OskarEichler thank you for providing the extra information.
I see you reproduce the crash inside app Songstats. Do you think you could try to repro it inside of RNTester? 
I still can't get a repro and without it, I'm just shooting in the dark.

**Comment by antoinerousseau** [comment]
I can still reproduce the crash, in the simulator even with this fix applied, with [this image](https://res.cloudinary.com/shotgun/image/upload/c_limit,f_auto,fl_lossy,q_1,w_80/v1668882551/production/artworks/artists/RonysooL) and `blurRadius: 50`

**Comment by tiagotwistag** [comment]
> I can still reproduce the crash, in the simulator even with this fix applied, with [this image](https://res.cloudinary.com/shotgun/image/upload/c_limit,f_auto,fl_lossy,q_1,w_80/v1668882551/production/artworks/artists/RonysooL) and `blurRadius: 50`

We still have this issue with expo-blur  12.9.2, just commenting so we don't lose track of it as it was marked as closed.
Is there any plan to address it?

**Comment by ababol** [comment]
I can still reproduce the crash in the simulator with [this image](https://res.cloudinary.com/shotgun/image/upload/c_limit,f_auto,fl_lossy,q_auto,w_1080/v1/production/artworks/FLYER_PHANTOM_bve5if) and blurRadius: 50

```
EXC_BAD_ACCESS
 
RCTBlurredImageWithRadius

New
Level: Fatal
Unhandled
Exception 1, Code 1, Subcode 140216553203528 > KERN_INVALID_ADDRESS at 0x7f86b5d86748.
```

<img width="1137" alt="Image" src="https://github.com/user-attachments/assets/03fa9a30-0cc0-4764-9876-f2f7194935b4" />

Applying this patch work:

```diff
diff --git a/Libraries/Image/RCTImageBlurUtils.mm b/Libraries/Image/RCTImageBlurUtils.mm
index e5a17309473b1283fd9c3545abee6a9576dafd15..16a1c69ba5b254d46504f8da69d7b621c9c224a4 100644
--- a/Libraries/Image/RCTImageBlurUtils.mm
+++ b/Libraries/Image/RCTImageBlurUtils.mm
@@ -20,14 +20,11 @@
 
   // convert to ARGB if it isn't
   if (CGImageGetBitsPerPixel(imageRef) != 32 || !((CGImageGetBitmapInfo(imageRef) & kCGBitmapAlphaInfoMask))) {
-    UIGraphicsImageRendererFormat *const rendererFormat = [UIGraphicsImageRendererFormat defaultFormat];
-    rendererFormat.scale = inputImage.scale;
-    UIGraphicsImageRenderer *const renderer = [[UIGraphicsImageRenderer alloc] initWithSize:inputImage.size
-                                                                                     format:rendererFormat];
-
-    imageRef = [renderer imageWithActions:^(UIGraphicsImageRendererContext *_Nonnull context) {
-                 [inputImage drawAtPoint:CGPointZero];
-               }].CGImage;
+    UIGraphicsBeginImageContextWithOptions(inputImage.size, NO, inputImage.scale);
+    [inputImage drawAtPoint:CGPointZero];
+    inputImage = UIGraphicsGetImageFromCurrentImageContext();
+    UIGraphicsEndImageContext();
+    imageRef = inputImage.CGImage;
   }
 
   vImage_Buffer buffer1, buffer2;
```

Could you maybe reopen the issue?
