### ISSUE TITLE
VirtualizedList horizontal pagingEnabled page count 0 of 9

### ISSUE THREAD

**Issue by MelihOzyurt** [facebook/react-native#35711]
### Description

Hello, I am using VirtualizedList, I have shared the example below. Although I have +10 pages of data, I cannot reach page 11.

### Version

0.64.2

### Output of `npx react-native info`

System:
    OS: macOS 12.6.1
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Memory: 23.78 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.5.0 - /usr/local/bin/npm
    Watchman: 2022.12.05.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.2 => 0.64.2
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

**Video**
https://streamable.com/4kxv7m

**Video File**
https://www.dosyaupload.com/48K6y/Screen_Recording_2022-12-24_at_3.54.04_AM.mov

### Snack, code example, screenshot, or link to a repository

```
<VirtualizedList
   data={userList}
   keyExtractor={(_item, index) => index?.toString()}
   horizontal
   pagingEnabled
   initialNumToRender={initialScrollIndex + 1}
   showsHorizontalScrollIndicator={false}
   onViewableItemsChanged={this.onViewableItemsChanged}   
   renderItem={this.renderItem}
   initialScrollIndex={initialScrollIndex}
   extraData={currentIndex}
   scrollEnabled
   getItemCount={() => slice || userList?.length || 10}   
   getItemLayout={(_, index) => ({
   length: width,
   offset: width * index,
   index,
   })}
        getItem={this.getItem}
        viewabilityConfig={{
          itemVisiblePercentThreshold: 50,
        }}
/>
```

**Comment by etiennelacoursiere** [comment]
Hi, i have a similar issue, how was this resolved?
