### ISSUE TITLE
[TextInput] onBlur not triggered when multiline is true

### ISSUE THREAD

**Issue by ranyefet** [facebook/react-native#3571]
Hi guys,

I have two ```TextInput``` with onBlur property. and I'm switching between them.
The input with multiline={true} does not trigger onBlur event.
```jsx
<TextInput 
  style={styles.input} 
  onBlur={() => console.log('onBlur - name')}
  placeholder="Your Name" />
<TextInput 
  style={styles.about} 
  multiline={true} 
  onBlur={() => console.log('onBlur - about')}  
  placeholder="Write a little bit about you..." />
``` 

Tested on RN v0.11.0

Thanks,
Ran.

**Comment by davidsims9t** [comment]
I'm having the same issue.

**Comment by davidsims9t** [comment]
This still seems to be an issue in v0.13. Any idea when this will be fixed?

**Comment by christopherdro** [comment]
@davidsims9t Just tested this on 0.14.2 and is working fine.
