### ISSUE TITLE
Render Error with empty App.js file

### ISSUE THREAD

**Issue by donchuru** [facebook/react-native#35729]
### Description

I'm getting the following error in the Node terminal:

ERROR  Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

This error is located at:
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in ShoppingList(RootComponent), js engine: hermes

This is reflected in my Android emulator this way:

![image](https://user-images.githubusercontent.com/90543559/209749498-b6e40680-2e2d-4714-b160-093365c34e50.png)

I've scanned through Stack for fixes but only found 1 person who experienced the same problem last month

### Version

8.11.0

### Output of `npx react-native info`

npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 399.36 MB / 11.90 GB
  Binaries:
    Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: Not Found
  Languages:
    Java: 11.0.16.1
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.6 => 0.70.6
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. Create react native project
2. Run Android Studio emulator with `create-react run-android`
3. Delete everything from the App.js as if to start a new project

The Render Error should show up

### Snack, code example, screenshot, or link to a repository

![image](https://user-images.githubusercontent.com/90543559/209752206-0e0e4f24-6be7-4282-9cf7-efe2a74c415d.png)

**Comment by jamsch** [comment]
@donchuru This is erroring out because your application is importing App.js from `index.js` and trying to render it. So App.js needs to export a react component, or `index.js` in your project root needs to import a different file.

**Comment by donchuru** [comment]
Thanks a lot @jamsch 

I was actually getting the same error yesterday even with the App component and an `export default App` line at the end but I guessed it resolved itself once I rebuilt my project today.
My guess is that maybe something was cached and my build was using that when I was troubleshooting.

**Comment by hotaryuzaki** [comment]
i get same error, exactly same error/warning message in log and white screen after splash screen got hide.
so what is the solution?
i already ```yarn cache clean``` many times

**Comment by hotaryuzaki** [comment]
i solved this error, i found that i import one of the expo packages but not installed.
```ERROR Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.```

but still i got white screen.
currently i have 4 warning logs about NativeEventEmitter, i dont know to fix this.

```
 WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method.
 WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `removeListeners` method.
 WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method.
 WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `removeListeners` method.
```

**Comment by hotaryuzaki** [comment]
i found that GestureHandlerRootView tag in app.js is the one that make the page get white.
if i remove GestureHandlerRootView the screen will be shown and i can see my react navigation bottom tab.
to fixed the issue set style flex:1
```
<GestureHandlerRootView style={{ flex: 1 }}>
```

but this warning still occur, and i have no clue
```
 WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method.
```

**Comment by donchuru** [comment]
@hotaryuzaki Hard to tell what's going on without seeing some code but I found something on Stack that could help:
[https://stackoverflow.com/a/69649068/16268781](url)

**Comment by donchuru** [comment]
@hotaryuzaki Hard to tell what's going on without seeing some code but I found something on Stack that could help:
[https://stackoverflow.com/a/69649068/16268781](url)

**Comment by Doko-Demo-Doa** [comment]
![image](https://user-images.githubusercontent.com/7723097/215043677-c847a4b7-c8ae-4034-b268-34dce0041cda.png)

I meet the same problem, new project too.

**Comment by Doko-Demo-Doa** [comment]
However, the problem only exists with default App.tsx. If I create another App2.tsx file and change the import in `index.js`, it works normally:

```jsx
import React from 'react';
import {Text} from 'react-native';

function App2() {
  return <Text>App2</Text>;
}

export default App2;
```
