### ISSUE TITLE
RN's demo proj for iOS failing to build; fresh MacOS install, fresh XCode install

### ISSUE THREAD

**Issue by kleydon** [facebook/react-native#35725]
### Description

Summary
===

React Native's [primary demo project](https://reactnative.dev/docs/environment-setup) (CLI Quick-Start, macOS + iOS) is failing to build for a fresh install of MacOS (13.1), running a fresh install of XCode (14.2).

When the demo's instructions are followed exactly:
```
npx react-native init AwesomeTSProject --template react-native-template-typescript

cd ./AwesomeTSProject && npx react-native run-android
```
...numerous errors of the form "`error: implicit declaration of function 'assert' is invalid in C99`" appear.

These errors occur when building the SocketRocket pod dependency, and when these errors  are silenced (by adding the C flag: `-Wno-error=implicit-function-declaration` for the SocketRocket target; not recommended [but possible](https://github.com/RTimothyEdwards/magic/issues/69)), more errors of the same form appear for the FlipperPeerTalk pod dependency. When _these_ errors in turn are silenced (with the same flag, for the FlipperPeerTalk target), compilation fails with:
```
Undefined symbols for architecture x86_64:
  "_assert", 
```
Somehow, `assert()` is getting lost - not just for SocketRocket, but also for FlipperPeerTalk.

Possible Work-Around (with Unknown Consequences)
===
If, in the XCode Settings for the "Pods" project, the `C Language Dialect` is changed from `gnu11` (the default for the react native demo) to `gnu99`, all errors magically disappear, and the code builds & runs. (But are there hidden consequences? Features that silently depend on c11? Why does RN's demo _not_ build and run with its given settings?)

Note: While the demo's _pod_ x-code project has the C Language Dialect setting:`gnu11`, the demo's _application_ project has the C Language Dialect setting: `gnu99`. Is it a problem that these two settings differ from each other? 

Environment
===
* MacBook Pro (Intel)
* MacOS: Ventura 13.1
* XCode 14.2
* XCode Tools 14.2 (14C18)
* Targets: iPhone 7 (iOs 15.5), Simulator (iOS 16.2)

### Version

Seen on RN 0.70.6, and also RN 0.69.5

### Output of `npx react-native info`

```
System:
    OS: macOS 13.1
    CPU: (4) x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
    Memory: 366.93 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 19.3.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.2.0 - /usr/local/bin/npm
    Watchman: 2022.12.12.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      Android NDK: 20.0.5594570
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 14.0.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.6 => 0.70.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

On an Intel Mac running MacOS 13.1 (Ventura), with XCode 14.2 / XCode Tools 14.2 (14C18), run the demo on React Native's site (for CLI, macOS, iOS):
```
npx react-native init AwesomeTSProject --template react-native-template-typescript

cd ./AwesomeTSProject && npx react-native run-android
```

### Snack, code example, screenshot, or link to a repository

To reproduce, just build React Native's CLI Quick-Start, macOS + iOS demo, on React Native's site, using React Native's instructions, with the environment described above.

Sample error output:

```
...

/Users/krispin/Desktop/test-rct-proj/AwesomeTSProject/ios/Pods/SocketRocket/SocketRocket/SRWebSocket.m:1230:9: error: implicit declaration of function 'assert' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        assert(consumer.bytesNeeded);
        ^
/Users/krispin/Desktop/test-rct-proj/AwesomeTSProject/ios/Pods/SocketRocket/SocketRocket/SRWebSocket.m:1399:5: error: implicit declaration of function 'assert' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    assert(frameBufferSize <= frameData.length);
    ^
/Users/krispin/Desktop/test-rct-proj/AwesomeTSProject/ios/Pods/SocketRocket/SocketRocket/SRWebSocket.m:1441:13: error: implicit declaration of function 'assert' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
            assert(_readBuffer);
            ^
...11 errors generated.

...

** BUILD FAILED **

The following build commands failed:
	CompileC /Users/krispin/Library/Developer/Xcode/DerivedData/AwesomeTSProject-fstqxvjpcmzswyepucfydwxyjbdx/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/SocketRocket.build/Objects-normal/x86_64/SRWebSocket.o /Users/krispin/Desktop/test-rct-proj/AwesomeTSProject/ios/Pods/SocketRocket/SocketRocket/SRWebSocket.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'SocketRocket' from project 'Pods')
(1 failure)

...
```

**Comment by jorgerojas26** [comment]
Having the same exact problem builiding a fresh project for ios with react-native run-ios
