### ISSUE TITLE
Execution failed for task ':app:processReleaseResources'.AAPT: error: resource android:attr/lStar not found.

### ISSUE THREAD

**Issue by RevivalDev** [facebook/react-native#35727]
### Description

No changes were made, and suddenly it started to fail

### Version

0.63.5

### Output of `npx react-native info`

System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 199.83 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.15.0 - ~/.nvm/versions/node/v14.15.0/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK: Not Found
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28, 29, 30, 31, 32
      Build Tools: 26.0.2, 26.0.3, 27.0.3, 28.0.2, 28.0.3, 29.0.0, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7199119
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_261 - /Library/Java/JavaVirtualMachines/jdk1.8.0_261.jdk/Contents/Home/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.5 => 0.63.5
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

first error " The binary version of its metadata is 1.6.1, expected version is 1.1.16"

so 
buildscript {
    ext {
        buildToolsVersion = "29.0.2"
        minSdkVersion = 21
        compileSdkVersion = 29
        targetSdkVersion = 29
        androidXCore = "1.6.0"
        kotlinVersion = "1.6.0" // new add
    }

And then started reporting errors,
 “ > Android resource linking failed
     /Users/revival/.gradle/caches/transforms-2/files-2.1/9c6c81038e4c01dabde31d5d71d4bfd8/core-1.7.0/res/values/values.xml:105:5-114:25: AAPT: error: resource android:attr/lStar not found.”

According to issues/35210，update RN version  0.63.2---->0.63.5
But it didn't work

### Snack, code example, screenshot, or link to a repository

// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "29.0.2"
        minSdkVersion = 21
        compileSdkVersion = 29
        targetSdkVersion = 29
        androidXCore = "1.6.0"
        kotlinVersion = "1.6.0" // new add
    }
    repositories {
        maven { url 'https://jitpack.io' }

        mavenCentral()
        google()
        jcenter()
    
        flatDir {
            dirs 'libs'
        }
    }
    dependencies {
        classpath("com.android.tools.build:gradle:4.0.1")
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        maven { url 'https://jitpack.io' }
       

        mavenLocal()
        mavenCentral()

        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        google()
        jcenter()
        maven { url 'https://www.jitpack.io' }

        maven {
            // expo-camera bundles a custom com.google.android:cameraview
            url "$rootDir/../node_modules/expo-camera/android/maven"
        }
    }
}

**Comment by projekt86** [comment]
jitpack is down https://github.com/jitpack/jitpack.io/issues/5239

**Comment by Ding-Fan** [comment]
Maybe you just need: `./gradlew app:assembleRelease` instead of the `./gradlew assembleRelease`

From: https://stackoverflow.com/a/75309297/6236633

**Comment by cortinico** [comment]
Closing as this issue is really old and probably not relevant anymore.
