### ISSUE TITLE
[Android] ListView navigator push

### ISSUE THREAD

**Issue by skv-headless** [facebook/react-native#3573]
I have ListView with 100 elements. When I tap to one of items I make ```navigator.push```. 
Transition starts with delay 1s and more. 

Video:
https://www.dropbox.com/s/ycmsolcwo3g43ti/VID_20151021_191331.mp4?dl=0

DemoApp:
https://github.com/sooth-sayer/react-native-listview-test

Transition animation is smooth.
It loads scene with ListView pretty well.
It works for ios pretty well.

**Comment by hufeng** [comment]
I have the same feeling as you. At last, I was used TouchableNativeFeedback to instead of TouchableHighlight or TouchableOpacity.

**Comment by vasth** [comment]
Do you solved it ?

**Comment by skv-headless** [comment]
Not really. I set ```scrollRenderAheadDistance``` to 200 and compiled js bundle in production mode. It helped but still I feel lag for old devices.
