### ISSUE TITLE
Editable image in TextInput

### ISSUE THREAD

**Issue by henke443** [facebook/react-native#35730]
### Description

Hello! I'm trying to recreate the functionality of the iOS notes app. In it you can insert images into the text and then select the image like text or delete it using backspace.

Other use-cases for this could be custom emojis.

This is possible in Flutter for all platforms with: [extended_text_field](https://pub.dev/packages/extended_text_field)

![image](https://user-images.githubusercontent.com/2922864/209801426-4d272433-c71d-479e-a5eb-487ae5bd689d.png)

It seems to be a duplicate of [this issue](https://github.com/facebook/react-native/issues/18566) from 2018 that was closed due to inactivity: 

If there's some alternate way to achieve this effect any suggestions would be greatly appreciated. Thanks :) 

### Version

0.70.5

### Output of `npx react-native info`

System:
    OS: Windows 10 10.0.22000
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
    Memory: 3.46 GB / 15.76 GB
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.19041.0, 10.0.22000.0, 10.0.22621.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 17.4.33205.214 (Visual Studio Community 2022)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.5 => 0.70.5
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Try to embed an image within a TextInput

### Snack, code example, screenshot, or link to a repository

    <View>
      <Text>The image below will be rendered as an uneditable placeholder image on iOS 16</Text>
      <TextInput>
          <Image src={{uri: "https://via.placeholder.com/100x100.jpg"}} style={{ width: 100, height: 100 }} />
      </TextInput>
    </View>

**Comment by henke443** [comment]
To my beginner eyes this seems related to <ImageSpan> on Android and and NSTextAttachment on iOS (as used in this [library](https://github.com/dzog/ImgGlyph))

**Comment by Arise-cn** [comment]
+1

**Comment by Arise-cn** [comment]
you can use react-native-variable-TextInput
