### ISSUE TITLE
Image gets loaded only after its visible on Android with FlatList --> leads to empty view

### ISSUE THREAD

**Issue by RRaideRR** [facebook/react-native#35736]
### Description

An Image gets loaded on Android only if its visible - iOS behaves different there. This results in an empty view during the first ms when the image is not being loaded yet. 

### Version

0.70.5

### Output of `npx react-native info`

warn Package @sentry/react-native contains invalid configuration: "dependency.platforms.ios.sharedLibraries" is not allowed,"dependency.hooks" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
info Fetching system and libraries information...
System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1
    Memory: 86.84 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.1 - /opt/homebrew/opt/node@16/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.19.2 - /opt/homebrew/opt/node@16/bin/npm
    Watchman: 2022.11.14.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 18.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.5 => 0.70.5 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

https://snack.expo.dev/@raider/horizontal_flatlist

On Android, you see the red background flashing up. However, on iOS, there is no red background flashing up. Please have a look at the attached videos.

https://user-images.githubusercontent.com/3411292/209842013-df0b18c5-1032-45f6-b363-5583ce0cc925.mov

https://user-images.githubusercontent.com/3411292/209842152-1f4c78f6-5723-4740-8292-d12855ab3469.mov

If you would log the `onLoadStart` method, you would notice that this method only gets called when the image is in the viewport.

### Snack, code example, screenshot, or link to a repository

https://snack.expo.dev/@raider/horizontal_flatlist

**Comment by yaroslavnikiforov** [comment]
is there any workaround for this?

**Comment by yaroslavnikiforov** [comment]
removeClippedSubviews={false}
