### ISSUE TITLE
Weird zIndex behavior when moving an element with transform translate, top/right etc

### ISSUE THREAD

**Issue by Nikos-96** [facebook/react-native#35740]
### Description

I'm trying to move an element with transform translate or top/right etc. but the element falls below others when i move it right or down, but if left or up then is above how i want it. I don't understand why this happens. I tried to change zIndex numbers, position absolute and make proper animation, didn't help. Why there is even different behavior for different directions? All cell elements are literally same, have same style etc. In normal css it works fine.

### Version

0.70.5

### Output of `npx react-native info`

System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i5-12600KF
    Memory: 20.19 GB / 31.86 GB
  Binaries:
    Node: 18.12.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: Not Found
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.5 => 0.70.5
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Shift an element above others in right or down directions. Sometimes zIndex might help, but not in my case. Open my snack and try to play with transform translate parameter where <View style={[styles.activeCell, {transform: [{ translateX: 40 }]}]}> is under my comment. It works with negative values X and Y directions, but not with positive.

### Snack, code example, screenshot, or link to a repository

https://snack.expo.dev/@nik96/sandbox-react-native

**Comment by risinglf** [comment]
Hello @Nikos-96 I have the same issue, did you solve it?
