### ISSUE TITLE
When secure Entry is true keypad value changing from numeric to numeric-pad in react native

### ISSUE THREAD

**Issue by imbibeks826** [facebook/react-native#35748]
### Description

with secure entry -<img width="195" alt="image" src="https://user-images.githubusercontent.com/30750076/210038859-fdff9bd5-813b-4b23-a960-d7219932f906.png">

without secure entry - <img width="205" alt="image" src="https://user-images.githubusercontent.com/30750076/210038875-81126176-2163-4563-8346-aa31b4521fa2.png">

Platform - Android

### Version

0.61.5

### Output of `npx react-native info`

System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 960.41 MB / 15.70 GB
  Binaries:
    Node: 14.18.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 23, 28, 30, 31, 32, 33
      Build Tools: 29.0.2, 30.0.2, 30.0.3, 33.0.1
      System Images: android-33 | Google APIs Intel x86 Atom_64
  IDEs:
    Android Studio: AI-213.7172.25.2113.9123335
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
  npmGlobalPackages:
    react-native: 0.70.6

### Steps to reproduce

1. give keyboard type as numeric in textinput 
2. keep secureEntry as true
3. change secure entry to false 

we will get two keypad when we changes secureEntry type without changing keyboard type

with secure entry -<img width="195" alt="image" src="https://user-images.githubusercontent.com/30750076/210038859-fdff9bd5-813b-4b23-a960-d7219932f906.png">

without secure entry - <img width="205" alt="image" src="https://user-images.githubusercontent.com/30750076/210038875-81126176-2163-4563-8346-aa31b4521fa2.png">

### Snack, code example, screenshot, or link to a repository

without secure entry - <img width="205" alt="image" src="https://user-images.githubusercontent.com/30750076/210038875-81126176-2163-4563-8346-aa31b4521fa2.png">

with secure entry -<img width="195" alt="image" src="https://user-images.githubusercontent.com/30750076/210038859-fdff9bd5-813b-4b23-a960-d7219932f906.png">

**Comment by mubrik** [comment]
Having this same issue.
@imbibeks826 any fix?
