### ISSUE TITLE
Using ".measure" on a View with a Ref, x and y coordinates always are 0 when run in Android but works fine on iOS (React Native)

### ISSUE THREAD

**Issue by minifisk** [facebook/react-native#35755]
### Description

I've assigned a view with a Ref, and I'm using this reference to get the coordinates of the view. It works fine on iOS, where I get a Y-value where the View is located. However, on Android, the Y-value is always zero.

I've read that you should use collapsable={false} on the View you are measuring, but the only thing that did was to no longer return "undefined" but instead return "0".

I've created a snack for the issue, will appreciate any feedback on how to resolve this.

### Version

0.68.2

### Output of `npx react-native info`

`System:
    OS: macOS 12.3.1
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Memory: 36.06 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.19.1 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.5.0 - /usr/local/bin/npm
    Watchman: 2022.03.21.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8309675
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.2 => 0.68.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found`

### Steps to reproduce

See attached snack

### Snack, code example, screenshot, or link to a repository

https://snack.expo.dev/@minifisk/quiet-cashew?platform=ios

**Comment by 635613589** [comment]
same on 0.67.3

**Comment by utkuimd** [comment]
You should try to use measureLayout(), not measure() or measureInWindow().
