### ISSUE TITLE
Error: "TypeError: Cannot read property 'SHORT' of null, js engine: hermes"

### ISSUE THREAD

**Issue by Vishnu-Nalagatla** [facebook/react-native#35758]
### New Version

0.66.4

### Old Version

0.70.6

### Build Target(s)

IOS

### Output of `react-native info`

System:
    OS: macOS 12.6.1
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 123.99 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.4.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.18.1 - /usr/local/bin/npm
    Watchman: 2022.12.26.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 31, 33
      Build Tools: 30.0.2, 30.0.3, 32.1.0, 33.0.1
      System Images: android-31 | Android TV ARM 64 v8a, android-31 | Android TV Intel x86 Atom, android-31 | ARM 64 v8a, android-31 | Intel x86 Atom_64, android-31 | Google TV ARM 64 v8a, android-31 | Google TV Intel x86 Atom, android-31 | Google APIs ARM 64 v8a, android-31 | Google APIs Intel x86 Atom_64, android-31 | Google Play ARM 64 v8a, android-31 | Google Play Intel x86 Atom_64, android-33 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 13.4/13F17a - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.2 => 18.3.0-next-fecc288b7-20221025 
    react-native: 0.70.6 => 0.70.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Issue and Reproduction Steps

just run npx react-native init testproject then cd testproject && npx react-native run-ios

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/87752276/210177577-32d2522d-d384-4cb6-9efc-c67935ace2f7.png">

**Comment by Vishnu-Nalagatla** [comment]
@cortinico I have followed this link :

https://github.com/facebook/react-native/commit/3f629049ba9773793978cf9093c7a71af15e3e8d#diff-8854d86a25d1052c7f65f4d7235198297464645255149b9700171beb00ca67ec

So I have manually updated node_modules react-native -> index.js and react-native/Libraries/Text -> Text.js then android worked fine.... but coming to the ios this error is coming.

**Comment by khanisak** [comment]
@Vishnu-Nalagatla  how you solve this issue ?

**Comment by Vishnu-Techtron** [comment]
> @Vishnu-Nalagatla how you solve this issue ?

yeah... that error occurred because of the package Razorpay. It has a dependency package of "react-native-simple-toast". so after installing it got resolved for me.

**Comment by khanisak** [comment]
in my case, I have imported wrong path of files in one of my ts file. so I guess this error is too generic but related to something wrong in our js / ts files. 

thanks @Vishnu-Nalagatla @Vishnu-Techtron
