### ISSUE TITLE
Keyboard is getting closed while focusing the textinput for the first time inside the intermediate tabs [Android only]

### ISSUE THREAD

**Issue by rifad4u** [facebook/react-native#35751]
### Description

Keyboard is getting closed while focusing the textinput for the first time inside the intermediate tabs , issue is happening in android only.

### Version

0.70.6

### Output of `npx react-native info`

System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M2
    Memory: 75.89 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.21.1 - /opt/homebrew/opt/node@14/bin/node
    Yarn: Not Found
    npm: 6.14.17 - /opt/homebrew/opt/node@14/bin/npm
    Watchman: 2022.11.14.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.6 => 0.70.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

I have attached the snack link , just run the same with bare react native project and try to focus the input fields from the intermediate tabs.

### Snack, code example, screenshot, or link to a repository

https://snack.expo.dev
[untitled.webm](https://user-images.githubusercontent.com/37132763/210059719-e92f6f96-f853-4d47-be6d-7f221a6b5f7c.webm)
/Tv9MitB0j

**Comment by rifad4u** [comment]
The issue is still there , not fixed yet.

**Comment by rifad4u** [comment]
Still facing this issue.

**Comment by hannojg** [comment]
what are "intermediate tabs" ?
