### ISSUE TITLE
[iOS] Unable to require native components using a fully qualified name that ends with `Manager`

### ISSUE THREAD

**Issue by angelodipaolo** [facebook/react-native#3575]
React Native fails to find a native component that subclasses `RCTViewManager` if the subclass's name ends with `Manager`. A demonstration project that reproduces this issue is available [here](https://github.com/angelodipaolo/ViewManagerTest)

### Example

Define a `RCTViewManager` subclass that ends with `Manager` in the name.

```
@interface FooViewManager : RCTViewManager
@end

@implementation FooViewManager

RCT_EXPORT_MODULE()

@end

```

Attempt to require it in react using the fully-qualified name:

```
var FooViewManager = React.requireNativeComponent('FooViewManager', null);

```

You get an error in the console:

```
'Warning: Native component for "FooViewManager" does not exist'
```

The component is found if you use a subset of the name when requiring it.

```
var FooViewManager = React.requireNativeComponent('FooView', null);

```

This only seems to affect subclasses of `RCTViewManager` that end with `Manager` in the name.

**Comment by brentvatne** [comment]
This is intentional -- what you really care about is the component eg: "FooView" -- the fact that the Manager class exists is an implementation detail. See these docs: https://facebook.github.io/react-native/docs/native-components-android.html#content

**Comment by angelodipaolo** [comment]
How is it intentional behavior that you cannot require a native module by its complete name?

My issue occurs on iOS, not Android, but I read through the doc you linked and I don't see any explaination as to why I cannot use the full component name if it ends with `Manager`. I understand that React Native is capable of resolving the name based on a subset but I don't see any mention that using a full name that ends with `Manager` will cause it to fail.

What am I missing?

**Comment by brentvatne** [comment]
Take a look at these and let me know if you're still confused:
https://github.com/facebook/react-native/blob/master/React/Views/RCTSliderManager.m
https://github.com/facebook/react-native/blob/master/React/Views/RCTSlider.m

**Comment by brentvatne** [comment]
Also, this is a little out of date but might be helpful:

http://brentvatne.ca/react-native-view-component-1/
http://brentvatne.ca/react-native-view-component-2/

Hope that clarifies things for you! :smile:

**Comment by ide** [comment]
@angelodipaolo When you define an Obj-C class called FooViewManager, you aren't implementing the FooView. You're implementing the logic to receive commands from JS and apply them to the actual FooView.

On the JS side you usually care about creating a UI component that is backed by a FooView. The FooViewManager is an implementation detail, and you almost certainly don't want to instantiate a FooViewManager in JS because what would you do with it?

Anyway, the docs mention this translation:
![screenshot 2015-10-21 11 32 53](https://cloud.githubusercontent.com/assets/379606/10646412/cb91f84a-77e7-11e5-92f4-dd817daa66b1.png)

If you do need to call methods on FooViewManager from JS, you can do that. It's a separate concern from UI components, though, so you need to mark FooViewManager as an exported module in Obj-C and access it from JS via NativeModules (also covered in the docs).

**Comment by angelodipaolo** [comment]
> and you almost certainly don't want to instantiate a FooViewManager in JS because what would you do with it?

I don't want to instantiate a `FooViewManager` in JS, I just want to use the full name when using `requireNativeComponent` to require it as part of my wrapper component. I understand that RN will automatically resolve `FooView` when requiring but it was very confusing as to why I would get a "does not exist" error when trying to use the full name.


If I were to rename my `RCTViewManager` subclass to `FooViewBar` and required it as `requireNativeComponent('FooViewBar', null)` RN will find the native component as expected. I really appreciate all of the help and info but it is still unclear to me as to why I can require any other native component by its full name as long as the `RCTViewManager` subclass does not end with `Manager`. This seems arbitrary and I have yet to find it documented anywhere.

thanks for all of the help!

**Comment by eJamesLin** [comment]
Thanks for pointing out this question, I've struggled with this issue, and rescue by your work-around solution using subset of the name at `requireNativeComponent`, or not using `Manager` at the end of name.
