### ISSUE TITLE
Fresh React Native 0.70.6 IOS export xcode IPA failed with compileBitcode true

### ISSUE THREAD

**Issue by Merlier** [facebook/react-native#35762]
### Description

React-Native's [primary init project](https://reactnative.dev/docs/environment-setup#creating-a-new-application) is failing on MacOS and xcode to be exported as IPA for development method with xcode or xcodebuild when compileBitcode is true.

If I set compileBitcode to false, the export is working well and I am getting an IPA.

### Version

0.70.6

### Output of `npx react-native info`

System:
    OS: macOS 11.7.2
    CPU: (8) x64 Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
    Memory: 3.44 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.21.2 - /usr/local/opt/node@14/bin/node
    Yarn: Not Found
    npm: 6.14.17 - /usr/local/opt/node@14/bin/npm
    Watchman: 2022.12.26.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/xxx/.rvm/gems/ruby-2.7.5/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7784292
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Java: 13.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.6 => 0.70.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. ## Init a new react-native project:

    $ npx react-native init labapp

2. ## Create a file exportOption.plist in labapp/ios/ directory with the following content:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>compileBitcode</key>
    <true />
    <key>method</key>
    <string>development</string>
    <key>destination</key>
    <string>export</string>
</dict>
</plist>
```

3. ## Archive and export IPA with xcodebuild

```
cd labapp

npm ci 

cd ios 

pod install

xcodebuild -workspace labapp.xcworkspace -scheme labapp -sdk iphoneos -configuration Release clean 

xcodebuild -workspace labapp.xcworkspace -scheme labapp -sdk iphoneos -configuration Release archive -archivePath $PWD/build/labapp.xcarchive 

xcodebuild -exportArchive -archivePath $PWD/build/labapp.xcarchive -exportOptionsPlist exportOption.plist -exportPath $PWD/build/
```

Then I get the error output.

### Snack, code example, screenshot, or link to a repository

Here the error output found at the end of the archive export:

```
** ARCHIVE SUCCEEDED **

2023-01-02 17:00:13.479 xcodebuild[31738:136390] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path "/var/folders/tg/r0d49l7x7pdcbtd0xx21r3w80000gn/T/labapp_2023-01-02_17-00-13.478.xcdistributionlogs".
2023-01-02 17:00:17.536 xcodebuild[31738:136461] CFURLRequestSetHTTPCookieStorageAcceptPolicy_block_invoke: no longer implemented and should not be called
2023-01-02 17:00:20.569 xcodebuild[31738:136390] -[NSNull path]: unrecognized selector sent to instance 0x7fff8083cea0
** INTERNAL ERROR: Uncaught exception **
Uncaught Exception: -[NSNull path]: unrecognized selector sent to instance 0x7fff8083cea0
Stack:
  0   __exceptionPreprocess (in CoreFoundation)
  1   objc_exception_throw (in libobjc.A.dylib)
  2   -[NSObject(NSObject) __retain_OA] (in CoreFoundation)
  3   ___forwarding___ (in CoreFoundation)
  4   _CF_forwarding_prep_0 (in CoreFoundation)
  5   -[IDEDistributionProcessingPipeline process:] (in IDEFoundation)
  6   -[IDEDistributionPackagingStep loadFromExportOptions:error:] (in IDEFoundation)
  7   -[IDEDistributionDriver runWithDestinationPath:error:] (in IDEFoundation)
  8   -[Xcode3CommandLineBuildTool _distributeArchiveAndExit] (in Xcode3Core)
  9   -[Xcode3CommandLineBuildTool run] (in Xcode3Core)
 10   main (in xcodebuild)
 11   start (in libdyld.dylib)
```

**Comment by Ahmadin29** [comment]
I have same issue

**Comment by odemolliens** [comment]
Bitcode is deprecated from XCode 14:

https://developer.apple.com/documentation/xcode-release-notes/xcode-14-release-notes

Starting with Xcode 14, bitcode is no longer required for watchOS and tvOS applications, and the App Store no longer accepts bitcode submissions from Xcode 14.

Xcode no longer builds bitcode by default and generates a warning message if a project explicitly enables bitcode: “Building with bitcode is deprecated. Please update your project and/or target settings to disable bitcode.” The capability to build with bitcode will be removed in a future Xcode release. IPAs that contain bitcode will have the bitcode stripped before being submitted to the App Store. Debug symbols for past bitcode submissions remain available for download.

**Comment by Merlier** [comment]
@odemolliens Thanks for your answer
