### ISSUE TITLE
[Android] need es6 tutorial

### ISSUE THREAD

**Issue by jnrepo** [facebook/react-native#3576]
Could we get an es6 tutorial for Android?

**Comment by jaygarcia** [comment]
How is ES6 different on Android than iOS?  They are both using the same transform/piler and both run JSContext (JavaScript runtime).

**Comment by brentvatne** [comment]
ES6 is the same regardless of the platform. https://facebook.github.io/react-native/docs/javascript-environment.html#content tells you what transforms are available and links to the Babel docs for each :smile:
