### ISSUE TITLE
[iOS] TouchableOpacity can be pressed off view when rendered in Section Header of ListView

### ISSUE THREAD

**Issue by jaygarcia** [facebook/react-native#3577]
It seems that TouchableOpacity can be pressed off view when rendered in Section Header. It even hooks drag events, which is quite strange.  Repo here: https://github.com/ModusCreateOrg/RN-touachable-opacity-bug

![listview1](https://cloud.githubusercontent.com/assets/180031/10644626/aae80f02-77f7-11e5-9889-d8c06dcdc14f.gif)

The main view is a modified "Hello world" boilerplate:
https://github.com/ModusCreateOrg/RN-touachable-opacity-bug/blob/master/index.android.js

The ListView is slightly modified: 
https://github.com/ModusCreateOrg/RN-touachable-opacity-bug/blob/master/ListViewExample.js

Any suggestions on where i can start troubleshooting would be greatly appreciated. :-\

**Comment by gre** [comment]
looks to be the same https://github.com/facebook/react-native/issues/3533 bug

**Comment by jaygarcia** [comment]
I might have found a permanent solution (For iOS anyway).

@ide @vjeux @nicklockwood  Please let me know if this is something that would be OK performance wise?  It definitely works. 

RCTScrollView::docClosestSectionHeader see comments marked `JG: ` below.
```


- (void)dockClosestSectionHeader
{
  UIView *contentView = [self contentView];
  CGFloat scrollTop = self.bounds.origin.y + self.contentInset.top;

  // Find the section headers that need to be docked
  __block UIView *previousHeader = nil;
  __block UIView *currentHeader = nil;
  __block UIView *nextHeader = nil;
  NSUInteger subviewCount = contentView.reactSubviews.count;
  [_stickyHeaderIndices enumerateIndexesWithOptions:0 usingBlock:
   ^(NSUInteger idx, __unused BOOL *stop) {

    if (idx >= subviewCount) {
      RCTLogError(@"Sticky header index %zd was outside the range {0, %zd}", idx, subviewCount);
      return;
    }

    UIView *header = contentView.reactSubviews[idx];

    // If nextHeader not yet found, search for docked headers
    if (!nextHeader) {
      CGFloat height = header.bounds.size.height;
      CGFloat top = header.center.y - height * header.layer.anchorPoint.y;
      if (top > scrollTop) {
        nextHeader = header;
      } else {
        previousHeader = currentHeader;
        currentHeader = header;
      }
    }

    // Reset transforms for header views
    header.transform = CGAffineTransformIdentity;
    header.layer.zPosition = ZINDEX_DEFAULT;

  }];

  // If no docked header, bail out
  if (!currentHeader) {
    return;
  }

  // Adjust current header to hug the top of the screen
  CGFloat currentFrameHeight = currentHeader.bounds.size.height;
  CGFloat currentFrameTop = currentHeader.center.y - currentFrameHeight * currentHeader.layer.anchorPoint.y;
  CGFloat yOffset = scrollTop - currentFrameTop;
  if (nextHeader) {
    // The next header nudges the current header out of the way when it reaches
    // the top of the screen
    CGFloat nextFrameHeight = nextHeader.bounds.size.height;
    CGFloat nextFrameTop = nextHeader.center.y - nextFrameHeight * nextHeader.layer.anchorPoint.y;
    CGFloat overlap = currentFrameHeight - (nextFrameTop - scrollTop);
    yOffset -= MAX(0, overlap);
  }
  // JG: Ensure that the current header is visible before making the transform.
  currentHeader.hidden = NO;
  currentHeader.transform = CGAffineTransformMakeTranslation(0, yOffset);
  currentHeader.layer.zPosition = ZINDEX_STICKY_HEADER;

  if (previousHeader) {
    // The previous header sits right above the currentHeader's initial position
    // so it scrolls away nicely once the currentHeader has locked into place
    CGFloat previousFrameHeight = previousHeader.bounds.size.height;
    CGFloat targetCenter = currentFrameTop - previousFrameHeight * (1.0 - previousHeader.layer.anchorPoint.y);
    yOffset = targetCenter - previousHeader.center.y;
    
    previousHeader.transform = CGAffineTransformMakeTranslation(0, yOffset);
    previousHeader.layer.zPosition = ZINDEX_STICKY_HEADER;
    // JG: Hide the previous header to prevent touches.
    previousHeader.hidden = YES;
  }
}
```

Demo: 
![listview1](https://cloud.githubusercontent.com/assets/180031/10711676/97da9258-7a50-11e5-9a1c-1dfde8a59b4a.gif)

**Comment by gre** [comment]
I'm not sure to understand what your solution does but that doesn't generically address https://github.com/facebook/react-native/issues/3533 bug that views positioned outside of a overflow container are still touchable right?
I'm not sure where the bug could be, but somewhere in the code is missing a check on `overflow: hidden` (for iOS only, in Android everything seem to work).

**Comment by jaygarcia** [comment]
@gre, yes. when the section header is scrolled out of bounds, the section header is hidden from view.
```
```

**Comment by ide** [comment]
@jaygarcia I believe your patch fixes the section headers but as @gre points out there's a more generic bug at play with clipped views receiving touches for some reason. We may need to check `clipsToBounds` in `-[UIView reactTagAtPoint:]` or override `hitTest:`.

**Comment by jaygarcia** [comment]
@ide , very good point. I honestly was not looking at scrollView outside the context of ListView. TBH, the only time I experienced this (again within the context of ListView), was with section headers.  That's why I targeted them specifically. =)

**Comment by jaygarcia** [comment]
@gre, @ide 

am hoping the above PR fixes things.
*Modify RCTView.m line 121 to the following*
```   
 if (!subview.clipsToBounds && !subview.isHidden && subview.isUserInteractionEnabled && subview.alpha > 0) {

```

@gre, I tested your use case as well as mine and everything seems to work as designed.  Am hoping this can be tested by others and verified for fixing.

**Comment by gre** [comment]
Cool :-)

**Comment by browniefed** [comment]
Hey @jaygarcia is this still happening, seems like it's been fixed

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/ios-touchableopacity-can-be-pressed-off-view-when-rendered-in-section-header-of-listview

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
