### ISSUE TITLE
项目非常棒 有flutter版本吗？？The project is great. Is there a flutter version?  https://github.com/flutter/flutter

### ISSUE THREAD

**Issue by gionlime** [facebook/react-native#35795]
### Description

项目非常棒 有flutter版本吗？？The project is great. Is there a flutter version?  https://github.com/flutter/flutter

### Version

ex0.0.70

### Output of `npx react-native info`

项目非常棒 有flutter版本吗？？The project is great. Is there a flutter version?  https://github.com/flutter/flutter

### Steps to reproduce

项目非常棒 有flutter版本吗？？The project is great. Is there a flutter version?  https://github.com/flutter/flutter

### Snack, code example, screenshot, or link to a repository

项目非常棒 有flutter版本吗？？The project is great. Is there a flutter version?  https://github.com/flutter/flutter

**Comment by iBotPeaches** [comment]
@gionlime - Why are you doing this? Its so spammy - you've spammed 150 projects in past 24 hours, including many of mine with this exact message.
