### ISSUE TITLE
error: warn Multiple Podfiles were found when trying to init react-native project in mac os

### ISSUE THREAD

**Issue by codersandipdas** [facebook/react-native#35801]
### Description

At first, when I tried to init a react-native project, "ruby version 2.5.7" error was shown.

I updated ruby successfully to the required version using the [guide](https://reactnative.dev/docs/next/environment-setup) and [rbenv](https://github.com/rbenv/rbenv)

Now, when I am trying to create a new project I am getting multiple pod file errors.

### Version

0.70.6

### Output of `npx react-native info`

`error warn Multiple Podfiles were found: ios/Podfile,vendor/bundle/ruby/2.7.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/Podfile. Choosing ios/Podfile automatically. If you would like to select a different one, you can configure it via "project.ios.sourceDir". You can learn more about it here: https://github.com/react-native-community/cli/blob/master/docs/configuration.md
`

### Steps to reproduce

I updated ruby successfully to the required version using the [guide](https://reactnative.dev/docs/next/environment-setup) and [benv](https://github.com/rbenv/rbenv)

### Snack, code example, screenshot, or link to a repository

![Error image](https://i.stack.imgur.com/xtX4I.png)

**Comment by Kompasua** [comment]
Exact same issue

**Comment by duranmla** [comment]
There is a section on the [docs](https://reactnative.dev/docs/environment-setup#command-line-tools) that suggests:

> Go to the Locations panel and install the tools by **selecting the most recent version** in the Command Line Tools dropdown.

What happen to me is that I went there and I saw the version _(only one in my case)_ and I assume it was selected already but you need to clicked and make sure it get selected by having a version under the select as the image below:

![CleanShot 2023-01-31 at 11 07 01@2x](https://user-images.githubusercontent.com/1425162/215730432-f6c6fd4b-32d5-46c2-8809-9fac25786604.png)

_At least that worked for me_

**Comment by tiagotedsky** [comment]
I have the same issue and just installed a clean react native 
```System:
    OS: macOS 13.0
    CPU: (12) arm64 Apple M2 Pro
    Memory: 466.11 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
    Yarn: Not Found
    npm: 8.19.3 - ~/.nvm/versions/node/v18.13.0/bin/npm
    Watchman: 2023.01.30.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/tiagosa/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.18 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.2 => 0.71.2
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found   
     ```

**Comment by arthurhts** [comment]
I have the same issue

**Comment by codersandipdas** [comment]
I was able to solve this issue by performing the following steps:

1. Updated ruby successfully to the required version using the [guide](https://reactnative.dev/docs/next/environment-setup) and [rbenv](https://github.com/rbenv/rbenv).
2. Installed the latest Xcode from Appstore.
3.  Done [this](https://reactnative.dev/assets/images/GettingStartedXcodeCommandLineTools-8259be8d3ab8575bec2b71988163c850.png) setting.

**Comment by anisamirouche** [comment]
did anyone find a solution ?

**Comment by anisamirouche** [comment]
> I have the same issue and just installed a clean react native
> 
> And my xcode shows exactly as @duranmla
> 
> ```
> System:
>     OS: macOS 13.0
>     CPU: (12) arm64 Apple M2 Pro
>     Memory: 466.11 MB / 32.00 GB
>     Shell: 5.8.1 - /bin/zsh
>   Binaries:
>     Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
>     Yarn: Not Found
>     npm: 8.19.3 - ~/.nvm/versions/node/v18.13.0/bin/npm
>     Watchman: 2023.01.30.00 - /opt/homebrew/bin/watchman
>   Managers:
>     CocoaPods: 1.11.3 - /Users/tiagosa/.rbenv/shims/pod
>   SDKs:
>     iOS SDK:
>       Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
>     Android SDK: Not Found
>   IDEs:
>     Android Studio: Not Found
>     Xcode: 14.2/14C18 - /usr/bin/xcodebuild
>   Languages:
>     Java: 11.0.18 - /usr/bin/javac
>   npmPackages:
>     @react-native-community/cli: Not Found
>     react: 18.2.0 => 18.2.0
>     react-native: 0.71.2 => 0.71.2
>     react-native-macos: Not Found
>   npmGlobalPackages:
>     *react-native*: Not Found   
> ```

did you find a solution ?

**Comment by cipolleschi** [comment]
Hi there!

The warning about multiple Podfile should not stop you from building the app. However, I put up a PR to fix this for new apps.

Probably, the problem is a misconfiguration of the environment. To make sure of it, could you try to manually install the pods by (from a Terminal):

1. navigate to your app folder
2. `cd ios`
3. `bundle install` (you need to run this only once)
4. `bundle exec pod install`
This should give us a better diagnostic of your problem.

Thank you so much.

**Comment by codersandipdas** [comment]
> Hi there!
> 
> The warning about multiple Podfile should not stop you from building the app. However, I put up a PR to fix this for new apps.
> 
> Probably, the problem is a misconfiguration of the environment. To make sure of it, could you try to manually install the pods by (from a Terminal):
> 
> 1. navigate to your app folder
> 2. `cd ios`
> 3. `bundle install` (you need to run this only once)
> 4. `bundle exec pod install`
>    This should give us a better diagnostic of your problem.
> 
> Thank you so much.

what to do when we get the error when trying to create a project not creating bulid?

**Comment by cipolleschi** [comment]
You should try the step I explained above.

There is something not correctly configured in the environment, thus the `init` command fails to install the pods.

By navigating into the `ios` folder, you can install the pods manually running `bundle install` (only once per project) and then `bundle exec pod install`.

This should output a more explorative message to help you fix the environment. Once fixed - and I can support you in setting that up once we have the right error - future `init` command will work!

**Comment by PrantoshB** [comment]
### Running `gem uninstall cocoapods` and `gem install cocoapods` helped me.

<img width="593" alt="Screenshot 2023-03-07 at 8 46 13 PM" src="https://user-images.githubusercontent.com/93311467/223465047-6a91378b-afc6-40cb-a6e9-cf6e4f2f0b67.png">

**Comment by artak-avanesian** [comment]
For me after doing `pod repo update` it crashed with some strange error:
```[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: https://www.ruby-lang.org/bugreport.html

[IMPORTANT]
Don't forget to include the Crash Report log file under
DiagnosticReports directory in bug reports.

zsh: abort      pod repo update```

**Comment by cipolleschi** [comment]
@artak-avanesian, this look like an incomplete stack trace. There is no error here at all. It just say that you _may have encountered a bug in the Ruby interpreter_ but there is nothing more... Could you provide some more info?

**Comment by skam22** [comment]
just created a new file using ```npx react-native@latest init AwesomeProject``` and encountered the same warning.

since I'm also using rbenv, and the ```AwesomeProject/.ruby-version``` file is included, I deleted the ```AwesomeProject/vendor``` folder.

project builds fine now without the warning.

**Comment by cipolleschi** [comment]
If you are concerned about the `multiple podfile` warning:
1. We already fixed and it will be removed in the next version of RN
2. It is just a warning: it won't prevent you from creating an app. If pod install is failing, the problem is somewhere else, not in the warning.

**Comment by erlandsen-tech** [comment]
Thanks @cipolleschi for the explanation. trying to create my first react native app, and have been battling this was not a great first impression, but I will still give it a go (y)

**Comment by cipolleschi** [comment]
I'm happy that you will try again! 😃 

Please, feel free to post any issues and reach out for help. We are committed in trying to improve the experience as much as we can (e.g.: solving that warning, or - spoiler for the next releases - removing the requirement of a specific ruby-version) so all your reports are extremely valuable for us!

**Comment by erlandsen-tech** [comment]
That sounds awesome. The whole thing was a bit of a nightmare with the ruby thing, but when I first got it up and running, it seems really nice. Currently making some exiting stuff, so stay tuned ;)

**Comment by prashanthpadimala07** [comment]
> There is a section on the [docs](https://reactnative.dev/docs/environment-setup#command-line-tools) that suggests:
> 
> > Go to the Locations panel and install the tools by **selecting the most recent version** in the Command Line Tools dropdown.
> 
> What happen to me is that I went there and I saw the version _(only one in my case)_ and I assume it was selected already but you need to clicked and make sure it get selected by having a version under the select as the image below:
> 
> ![CleanShot 2023-01-31 at 11 07 01@2x](https://user-images.githubusercontent.com/1425162/215730432-f6c6fd4b-32d5-46c2-8809-9fac25786604.png)
> 
> _At least that worked for me_. Also if you don't know how to open this panel just press `CMD + ,` ✌️

This worked for me also

**Comment by halilugur** [comment]
> > There is a section on the [docs](https://reactnative.dev/docs/environment-setup#command-line-tools) that suggests:
> > > Go to the Locations panel and install the tools by **selecting the most recent version** in the Command Line Tools dropdown.
> > 
> > 
> > What happen to me is that I went there and I saw the version _(only one in my case)_ and I assume it was selected already but you need to clicked and make sure it get selected by having a version under the select as the image below:
> > ![CleanShot 2023-01-31 at 11 07 01@2x](https://user-images.githubusercontent.com/1425162/215730432-f6c6fd4b-32d5-46c2-8809-9fac25786604.png)
> > _At least that worked for me_. Also if you don't know how to open this panel just press `CMD + ,` ✌️
> 
> This worked for me also

also me too

**Comment by biapar** [comment]
> > > There is a section on the [docs](https://reactnative.dev/docs/environment-setup#command-line-tools) that suggests:
> > > > Go to the Locations panel and install the tools by **selecting the most recent version** in the Command Line Tools dropdown.
> > > 
> > > 
> > > What happen to me is that I went there and I saw the version _(only one in my case)_ and I assume it was selected already but you need to clicked and make sure it get selected by having a version under the select as the image below:
> > > ![CleanShot 2023-01-31 at 11 07 01@2x](https://user-images.githubusercontent.com/1425162/215730432-f6c6fd4b-32d5-46c2-8809-9fac25786604.png)
> > > _At least that worked for me_. Also if you don't know how to open this panel just press `CMD + ,` ✌️
> > 
> > 
> > This worked for me also
> 
> also me too

me too

**Comment by mkabatek** [comment]
> 4\. bundle exec pod install

I did the following, and got the following error:

```
[!] CocoaPods could not find compatible versions for pod "hermes-engine":
  In snapshot (Podfile.lock):
    hermes-engine (from `../node_modules/react-native/sdks/hermes-engine/hermes-engine.podspec`)

  In Podfile:
    hermes-engine (from `../node_modules/react-native/sdks/hermes-engine/hermes-engine.podspec`)

It seems like you've changed the version of the dependency `hermes-engine` and it differs from the version stored in `Pods/Local Podspecs`.
You should run `pod update hermes-engine --no-repo-update` to apply changes made locally.
```

**Comment by cipolleschi** [comment]
@mkabatek your hermes version is not aligned with the one downloaded by react native. The error message contains instructions on how to fix it:
`pod update hermes-engine --no-repo-update`

Try to run this command and see if it fixes the issue! :D

**Comment by oneeb-asad** [comment]
> There is a section on the [docs](https://reactnative.dev/docs/environment-setup#command-line-tools) that suggests:
> 
> > Go to the Locations panel and install the tools by **selecting the most recent version** in the Command Line Tools dropdown.
> 
> What happen to me is that I went there and I saw the version _(only one in my case)_ and I assume it was selected already but you need to clicked and make sure it get selected by having a version under the select as the image below:
> 
> ![CleanShot 2023-01-31 at 11 07 01@2x](https://user-images.githubusercontent.com/1425162/215730432-f6c6fd4b-32d5-46c2-8809-9fac25786604.png)
> 
> _At least that worked for me_. Also if you don't know how to open this panel just press `CMD + ,` ✌️

this solution worked for me as well

**Comment by mkabatek** [comment]
@oneeb-asad this is properly setup in my environment in xcode and the problem persists.

**Comment by cipolleschi** [comment]
@mkabatek If I understand correctly:
1. `npx react-native init` fails due to incorrect hermes versions
2. when you run `pod update hermes-engine --no-repo-update`, you manage to update the pods successfully
3. You ca then open Xcode and build the project, right?

What happens if after step 2, you try to run `yarn ios` from the project root, instead?

Also, which version of React Native are you using?

**Comment by cipolleschi** [comment]
Hi @amypellegrini! Yes, you can create a new React Native app with `npx react-Native unit <AppName> --skip-install`.

This creates a new app from the React Native template, without installing **any** dependencies.

Which means that you have to run `yarn install` manually, but it will skip the iOS setup.

**Comment by haiqinJack** [comment]
What is the solution？I also encountered this problem

**Comment by flyskywhy** [comment]
I just `npx react-native@latest init AwesomeProject` in Linux Ubuntu, then found no `AwesomeProject/vendor/` exist, then copy `AwesomeProject/` (without `node_modules`) into macOS, `npm install` and `cd ios; pod install` and XCode 14 build and run on iPhone OK.

So I think the `vendor/` is meaningless.

**Comment by cipolleschi** [comment]
Hi @flyskywhy! That's expected. The iOS build chain does not exists on non-macOS machines, so the whole setup for iOS is expected not to work in those environments.

**Comment by HosamZewain** [comment]
> Hi there!
> 
> The warning about multiple Podfile should not stop you from building the app. However, I put up a PR to fix this for new apps.
> 
> Probably, the problem is a misconfiguration of the environment. To make sure of it, could you try to manually install the pods by (from a Terminal):
> 
>     1. navigate to your app folder
> 
>     2. `cd ios`
> 
>     3. `bundle install` (you need to run this only once)
> 
>     4. `bundle exec pod install`
>        This should give us a better diagnostic of your problem.
> 
> 
> Thank you so much.

This worked for me thanks

**Comment by diwakardayal** [comment]
Sometime your xcode env variable is not set correctly 
You can try doing this
`export PATH=$PATH:/Applications/Xcode.app/Contents/Developer/
`

**Comment by fxckdead** [comment]
TLTR; In my case the issue was with Pod having old repo db, fixed with `pod repo update` and then `bundle exec pod install`.

--- 
I found out this after doing a manual pod install:

```
$ cd ios/
$ bundle exec pod install

warn Multiple Podfiles were found: ios/Podfile,vendor/bundle/ruby/3.0.0/gems/cocoapods-core-1.12.1/lib/cocoapods-core/Podfile. Choosing ios/Podfile automatically. If you would like to select a different one, you can configure it via "project.ios.sourceDir". You can learn more about it here: https://github.com/react-native-community/cli/blob/master/docs/configuration.md
Framework build type is static library
[Codegen] Generating ./build/generated/ios/React-Codegen.podspec.json
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
[Codegen] Found FBReactNativeSpec
Fetching podspec for `RCT-Folly` from `../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec`
Fetching podspec for `boost` from `../node_modules/react-native/third-party-podspecs/boost.podspec`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
Fetching podspec for `hermes-engine` from `../node_modules/react-native/sdks/hermes-engine/hermes-engine.podspec`
[!] CocoaPods could not find compatible versions for pod "FlipperKit/FlipperKitLayoutPlugin":
  In Podfile:
    FlipperKit/FlipperKitLayoutPlugin (= 0.125.0)

None of your spec sources contain a spec satisfying the dependency: `FlipperKit/FlipperKitLayoutPlugin (= 0.125.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```

**Comment by LYevhen** [comment]
Having same issue on RN 0.71.11 and below, I'm migrating to new RN from 0.67.5, but had same issue with new project setup from scratch.
Mentioned method proposed by @duranmla with selecting command line tools does not help, and I have newer version
<img width="426" alt="image" src="https://github.com/facebook/react-native/assets/44976185/2c0b0e34-8fd3-4a73-a6ef-5c66332626a7">
and there is already update to x code

**Comment by cipolleschi** [comment]
@LYevhen, can you please open a different issue with your specific problem?

As I explained above, the `error: warn Multiple Podfiles were found when trying to init react-native project in mac os` is not an error but a `warning`. Multiple Podfiles does not blocks the pod install step. Likely, this warning - which, btw, is gone in 0.72 - is hiding the actual error.

Given that you are already updating, could you update to 0.72, rather than 0.71.11?
