### ISSUE TITLE
Error while updating property 'fontSize' in shadow node of type: RCTText

### ISSUE THREAD

**Issue by acscube360** [facebook/react-native#35811]
### Description

Any one can help to solve this error?

### Version

70.0

### Output of `npx react-native info`

System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
    Memory: 8.74 GB / 15.89 GB
  Binaries:
    Node: 18.10.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 28, 29, 30, 31, 32, 33
      Build Tools: 28.0.3, 29.0.2, 30.0.0, 30.0.1, 30.0.2, 30.0.3, 33.0.1
      System Images: android-33 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: AI-213.7172.25.2113.9123335
    Visual Studio: Not Found
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.5 => 0.70.5
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

{
  "name": "xxxxxxxxxxxxxxx",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@react-native-community/datetimepicker": "6.5.2",
    "@react-native-community/masked-view": "^0.1.11",
    "@react-navigation/bottom-tabs": "^6.4.0",
    "@react-navigation/drawer": "^6.5.0",
    "@react-navigation/native": "^6.0.13",
    "@react-navigation/native-stack": "^6.9.1",
    "@react-navigation/stack": "^6.3.4",
    "axios": "^1.1.3",
    "axios-auth-refresh": "^3.3.4",
    "base-64": "^1.0.0",
    "camelize": "^1.0.1",
    "expo": "~47.0.3",
    "expo-secure-store": "~12.0.0",
    "expo-status-bar": "~1.4.2",
    "react": "18.1.0",
    "react-native": "0.70.5",
    "react-native-date-picker": "^4.2.6",
    "react-native-dropdown-picker": "^5.4.2",
    "react-native-gesture-handler": "~2.8.0",
    "react-native-keyboard-aware-view": "^0.0.14",
    "react-native-keychain": "^8.1.1",
    "react-native-paper": "^5.0.0-rc.9",
    "react-native-reanimated": "~2.12.0",
    "react-native-safe-area-context": "4.4.1",
    "react-native-screens": "~3.18.0",
    "react-native-sticky-header-footer-scroll-view": "^2.1.3",
    "react-native-table-component": "^1.2.2",
    "uuidv4": "^5.0.1"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9"
  },
  "private": true
}

### Snack, code example, screenshot, or link to a repository

![Screenshot 2023-01-11 233441](https://user-images.githubusercontent.com/121781068/211883720-becd9867-5195-4306-a08c-6e7509951c2a.png)

**Comment by lovelytingy** [comment]
@acscube360 hi, you are passing string to fontSize property. It only accepts number.

**Comment by acscube360** [comment]
> 

@lovelytingy when I pass number into font size property also return that error

**Comment by lovelytingy** [comment]
@acscube360 could please paste the style or ssbof your code for better understanding.
