### ISSUE TITLE
NetInfo reports connected during startup 

### ISSUE THREAD

**Issue by mschipperheyn** [facebook/react-native#3581]
Hi,

I'm using redux and NetInfo to manager connection detection. It works correctly except during startup. If the phone is offline during startup, the result is that it reports itself as connected (tested in simulator) when it is not. Any suggestions?

	import createOneShotMiddleware from 'redux-middleware-oneshot';
	import { NetInfo } from 'react-native';
	import netInfo from './actions/actions';

	export const middleware = createOneShotMiddleware((dispatch) => {
		const handle = (isConnected) => dispatch(netInfo(isConnected));
		NetInfo.isConnected.fetch().done(handle);
		NetInfo.isConnected.addEventListener('change', handle);
	});

--
	import { combineReducers } from 'redux';

	import status from '../modules/status/reducers/reducer';
	import connection from '../modules/connection/reducers/reducer';

	export default combineReducers({
	  connection,
	  status,
	});

--

	import {createStore, applyMiddleware} from 'redux';

	import thunkMiddleware from 'redux-thunk';
	import loggerMiddleware from 'redux-logger';
	import netInfoMiddleware from 'redux-middleware-react-native-netinfo';
	import rootReducer from './reducers';

	const createStoreWithMiddleware = applyMiddleware(
	  thunkMiddleware,
	  netInfoMiddleware,
	  loggerMiddleware
	)(createStore);

	export default function configureStore(initialState) {
	  return createStoreWithMiddleware(rootReducer, initialState);
	}

**Comment by christopherdro** [comment]
Testing on the simulator will always return `wifi`.
You will need to test on a device to trigger between states.

**Comment by sarovin** [comment]
I have the same issue.

I have tested on simulator and device...

`import createOneShotMiddleware from 'redux-middleware-oneshot';
import { NetInfo } from 'react-native';
import { checkConnection } from '../actions/networkActions';

export const middleware = createOneShotMiddleware((dispatch) => {
    const handle = (isConnected) => dispatch(checkConnection(isConnected));
    NetInfo.isConnected.fetch().done(handle);
    NetInfo.isConnected.addEventListener('change', handle);
});
`

Actions
`import * as types from './actionTypes';

export function checkConnection(isConnected) {
  return {
    type: types.CHECK_CONNECTION,
    isConnected: isConnected
  };
}
`
Reducers

`import { CHECK_CONNECTION } from '../actions/actionTypes';

const initialState = {
  isConnected: false,
};


export default function network(state = initialState, action = {}) {
    switch (action.type) {
        case CHECK_CONNECTION:
            return Object.assign({}, state, {isConnected: action.isConnected})
        default:
            return state;
    }
}

`

`import React, { Component } from 'react-native';
import { createStore, applyMiddleware, combineReducers } from 'redux';
import { middleware as netInfo } from './Middleware/redux-middleware-react-native-netinfo';
import { Provider } from 'react-redux';
import thunk from 'redux-thunk';
import createLogger from 'redux-logger'

import * as reducers from './reducers';

import NavigationScreen from './Containers/NavigationScreen';

const logger = createLogger()
const createStoreWithMiddleware = applyMiddleware(thunk, logger, netInfo)(createStore)
const reducer = combineReducers(reducers);
const store = createStoreWithMiddleware(reducer)

export default class App extends Component {
  render() {
    return (
      <Provider store={store}>
        <NavigationScreen />
      </Provider>
    );
  }
}
`

Any suggestions?

**Comment by kodatech** [comment]
Hi @sarovin, did you find solution for this?. Anyway, the issue I've been faced is a little bit different. If the device is connected to a modem but the modem don't have connection to internet, I get isConnected as true. Any idea? Thanks

**Comment by sarovin** [comment]
@kodatech no, i am sorry
