### ISSUE TITLE
Creating a new project is stuck at Installing cocoapods dependencies

### ISSUE THREAD

**Issue by PritishSawant** [facebook/react-native#35819]
### Description

I have all the necessary dependencies like Xcode, home-brew, cocoapods etc installed on my device. I am able to work with previous of react native as well. For react native 0.71 when I try to create a new project it is stuck on Installing cocoapods dependencies

### Version

0.71

### Output of `npx react-native info`

error Unrecognized command "info".
info Run "react-native --help" to see a list of all available commands.

### Steps to reproduce

Create a new project using `npx react-native init MyApp`

### Snack, code example, screenshot, or link to a repository

<img width="571" alt="Screenshot 2023-01-13 at 1 48 30 PM" src="https://user-images.githubusercontent.com/24708929/212271791-26aaa91a-d8b8-4994-835e-f487c643adf4.png">

**Comment by bbredewold** [comment]
What do you mean stuck? This step could take a very long time!

**Comment by PritishSawant** [comment]
I am waiting for more than an hour. If it takes this long for a bare bones project then something might be wrong

**Comment by vincicat** [comment]
I got an error instead: `Error: Failed to install CocoaPods dependencies for iOS project, which is required by this template.
Please try again manually`

so your pod install may be failed but the tool don't know it for some reason

after I run the pod install manually I found out that is one of the podspec failed like this issue https://github.com/facebook/react-native/issues/35818
```
Fetching podspec for `hermes-engine` from `../node_modules/react-native/sdks/hermes-engine/hermes-engine.podspec`
[!] Failed to load 'hermes-engine' podspec: 
[!] Invalid `hermes-engine.podspec` file: undefined method `exists?' for File:Class.
 #  from [..]/node_modules/react-native/sdks/hermes-engine/hermes-engine.podspec:46
 #  -------------------------------------------
 #    source[:http] = "file://#{destination_path}"
 >  elsif File.exists?(hermestag_file) && isInCI
 #    Pod::UI.puts '[Hermes] Detected that you are on a React Native release branch, building Hermes from source but fetched from tag...'.yellow if Object.const_defined?("Pod::UI")
 #  -------------------------------------------
```
so this is the hermes-engine podspec using deprecated ruby function. Check your pod environment `pod env` to see if it is using ruby 3.2:
```
CocoaPods : 1.11.3
Ruby : ruby 3.2.0 (2022-12-25 revision a528908271)
```

solution: a. downgrade your ruby (see comment in #35818) or  b. patch the podspec in `node_modules/react-native/sdks/hermes-engine/hermes-engine.podspec` like https://github.com/software-mansion/react-native-gesture-handler/pull/2368

**Comment by PritishSawant** [comment]
@vincicat How long did you wait to get this error? I waited an hour and ran out of patience and gave up on it

**Comment by PritishSawant** [comment]
I tried it again and it is resolved

**Comment by insanebear** [comment]
This issue has been closed, but hopefully it might help someone experiencing this problem.
I had the same problem and found one [solution](https://github.com/facebook/react-native/issues/31505#issuecomment-1245424395)

You can download tar.gz from Chrome and then let the command know the location first with installation command.

Anyhow this step took a lot of time. In my case, more than a half hour.
You can check the progress using `--verbose`.

**Comment by insanebear** [comment]
@hpelitebook745G2 Yeah, I forgot to mention it. I was also struggling to find the file. Since the time passed by, it is little vague for me to reccall now, but I tried a url link that was printed in the console with verbose mode on a browser and it asked me where to download. Trying installing CocoaPods with `--verbose` and check if there is the url.

**Comment by cortinico** [comment]
> You can download tar.gz from Chrome and then let the command know the location first with installation command.

This is not the solution, it's just a workaround.

@insanebear i understand that you have to download the tarball first. however, the link you provided didn't mention the source he got it from. i can't find hermes-runtime-darwin-v0.70.0.tar.gz here ([facebook/hermes/releases](https://github.com/facebook/hermes/releases)) either.

We moved Hermes artifacts to Maven Central so you won't find them in the Hermes repo itself. 
Please open a separate issue, share your log, and we can try to fix this rather than suggesting manual workarounds

**Comment by insanebear** [comment]
@cortinico You have a point. My bad. It should be mentioned as a workaround. English is not my primary language and I missed it.    Thanks.
