### ISSUE TITLE
Hey, where can I find MacOS `hermes` binary for 0.71?

### ISSUE THREAD

**Issue by zloirock** [facebook/react-native#35817]
### New Version

0.71

### Old Version

0.70

### Build Target(s)

MacOS

### Output of `react-native info`

...

### Issue and Reproduction Steps

In 0.69 and 0.70, it was attached to the release, but in 0.71 it's missed, in the package present `hermesc`, but not `hermes`.

**Comment by cipolleschi** [comment]
Hi @zloirock, thank you for raising the problem.
If I'm not mistaken, you should be able to use the same framework we are using for iOS.

This [job](https://app.circleci.com/pipelines/github/facebook/react-native/18784/workflows/61fdf7b5-9547-48aa-b39c-3333b7bebd46/jobs/411856/steps) builds Hermes for iOS **and for Mac** and creates a fat binary that should support both platforms.

The binary is then uploaded to Maven and you should be able to use it from there. The url to download should be: https://repo1.maven.org/maven2/com/facebook/react/react-native-artifacts/0.71.0/react-native-artifacts-0.71.0-hermes-ios-release.tar.gz.

The way we install it in iOS is via cocoapods. This is the podspec for the [`hermes-engine`](https://github.com/facebook/react-native/blob/0.71-stable/sdks/hermes-engine/hermes-engine.podspec#L54) at the line where we set the source to download the framework.

I don't know how MacOS is installing its dependency.

Could you try this out and let me know if it works?

**Comment by zloirock** [comment]
Thank you. That's what I was looking for.

**Comment by zloirock** [comment]
It seems that from `0.83` the process was changed.

I need a simple way to get `hermes` binary for a specific React Native version to test compatibility with `core-js`. Could you help me with this?

**Comment by zloirock** [comment]
up
