### ISSUE TITLE
Upgrade from 0.70.6 to 0.71.0 (FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory)

### ISSUE THREAD

**Issue by OskarEichler** [facebook/react-native#35821]
### New Version

0.71.0

### Old Version

0.70.6

### Build Target(s)

33

### Output of `react-native info`

info Installing "react-native@0.71.0" and its peer dependencies...
error Command failed: yarn add react-native@0.71.0 react@18.2.0
warning ../package.json: No license field
warning " > @mui/styles@5.10.3" has incorrect peer dependency "react@^17.0.0".
warning " > @react-native-async-storage/async-storage@1.17.10" has incorrect peer dependency "react-native@^0.0.0-0 || 0.60 - 0.70 || 1000.0.0".
warning "@typescript-eslint/eslint-plugin > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
warning " > eslint-plugin-flowtype@8.0.3" has unmet peer dependency "@babel/plugin-syntax-flow@^7.14.5".
warning " > eslint-plugin-flowtype@8.0.3" has unmet peer dependency "@babel/plugin-transform-react-jsx@^7.14.9".
warning " > react-async-script-loader@0.3.0" has incorrect peer dependency "react@^15.5.4".
warning "react-dev-utils > fork-ts-checker-webpack-plugin@6.5.2" has unmet peer dependency "typescript@>= 2.7".
warning " > react-facebook-login@4.1.1" has incorrect peer dependency "react@^16.0.0".
warning " > react-highcharts@16.1.0" has incorrect peer dependency "react@~0.14 || ^15.0.0 || ^16.0.0".
warning " > react-highcharts@16.1.0" has incorrect peer dependency "react-dom@~0.14 || ^15.0.0 || ^16.0.0".
warning "react-router > mini-create-react-context@0.4.1" has incorrect peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0 || ^17.0.0".
warning " > react-stripe-elements@6.1.2" has incorrect peer dependency "react@^15.5.4 || ^16.0.0-0".
warning " > react-stripe-elements@6.1.2" has incorrect peer dependency "react-dom@^15.5.4 || ^16.0.0-0".
warning Workspaces can only be enabled in private projects.

<--- Last few GCs --->

[86273:0x120008000]    49837 ms: Scavenge 4038.8 (4120.2) -> 4036.6 (4123.7) MB, 8.2 / 0.0 ms  (average mu = 0.569, current mu = 0.374) allocation failure 
[86273:0x120008000]    49858 ms: Scavenge 4042.0 (4123.7) -> 4039.4 (4141.2) MB, 9.5 / 0.0 ms  (average mu = 0.569, current mu = 0.374) allocation failure 
[86273:0x120008000]    51452 ms: Mark-sweep 4052.1 (4141.2) -> 4043.8 (4149.7) MB, 1566.0 / 0.0 ms  (average mu = 0.378, current mu = 0.175) allocation failure scavenge might not succeed

<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0x104dc6260 node::Abort() [/usr/local/bin/node]
 2: 0x104dc63e8 node::errors::TryCatchScope::~TryCatchScope() [/usr/local/bin/node]
 3: 0x104f14e88 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 4: 0x104f14e1c v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 5: 0x105098534 v8::internal::Heap::GarbageCollectionReasonToString(v8::internal::GarbageCollectionReason) [/usr/local/bin/node]
 6: 0x105097054 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/bin/node]
 7: 0x1050a239c v8::internal::Heap::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]
 8: 0x1050a2430 v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]
 9: 0x1050752c4 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/usr/local/bin/node]
10: 0x1053ad3c8 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/usr/local/bin/node]
11: 0x1056c1a4c Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/usr/local/bin/node]
12: 0x1056d722c Builtins_ArrayPrototypeJoin [/usr/local/bin/node]
13: 0x1098c8448 
14: 0x109a93ad0 
15: 0x109a966d8 
16: 0x1098d19a0 
17: 0x1056556d8 Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
18: 0x1056556d8 Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
19: 0x105686eac Builtins_GeneratorPrototypeNext [/usr/local/bin/node]
20: 0x109a15e94 
21: 0x109a5ee5c 
22: 0x1056556d8 Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
23: 0x1056556d8 Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
24: 0x105686eac Builtins_GeneratorPrototypeNext [/usr/local/bin/node]
25: 0x109a15e94 
26: 0x109a5ee5c 
27: 0x1056556d8 Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
28: 0x1056556d8 Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
29: 0x105686eac Builtins_GeneratorPrototypeNext [/usr/local/bin/node]
30: 0x109a60b28 
31: 0x1097667f4 
32: 0x105709b78 Builtins_PromiseFulfillReactionJob [/usr/local/bin/node]
33: 0x1056770b4 Builtins_RunMicrotasks [/usr/local/bin/node]
34: 0x1056533a4 Builtins_JSRunMicrotasksEntry [/usr/local/bin/node]
35: 0x105024ce4 v8::internal::(anonymous namespace)::Invoke(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) [/usr/local/bin/node]
36: 0x105025118 v8::internal::(anonymous namespace)::InvokeWithTryCatch(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) [/usr/local/bin/node]
37: 0x105025204 v8::internal::Execution::TryRunMicrotasks(v8::internal::Isolate*, v8::internal::MicrotaskQueue*, v8::internal::MaybeHandle<v8::internal::Object>*) [/usr/local/bin/node]
38: 0x105047e40 v8::internal::MicrotaskQueue::RunMicrotasks(v8::internal::Isolate*) [/usr/local/bin/node]
39: 0x1050486d4 v8::internal::MicrotaskQueue::PerformCheckpoint(v8::Isolate*) [/usr/local/bin/node]
40: 0x104d12db4 node::InternalCallbackScope::Close() [/usr/local/bin/node]
41: 0x104d1348c node::InternalMakeCallback(node::Environment*, v8::Local<v8::Object>, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*, node::async_context) [/usr/local/bin/node]
42: 0x104d284c0 node::AsyncWrap::MakeCallback(v8::Local<v8::Function>, int, v8::Local<v8::Value>*) [/usr/local/bin/node]
43: 0x104dca41c node::fs::FSReqCallback::Reject(v8::Local<v8::Value>) [/usr/local/bin/node]
44: 0x104dcabe8 node::fs::FSReqAfterScope::Reject(uv_fs_s*) [/usr/local/bin/node]
45: 0x104dcaca4 node::fs::AfterNoArgs(uv_fs_s*) [/usr/local/bin/node]
46: 0x105633a5c uv__work_done [/usr/local/bin/node]
47: 0x1056371f8 uv__async_io [/usr/local/bin/node]
48: 0x105648f70 uv__io_poll [/usr/local/bin/node]
49: 0x105637688 uv_run [/usr/local/bin/node]
50: 0x104d13ccc node::SpinEventLoop(node::Environment*) [/usr/local/bin/node]
51: 0x104dff440 node::NodeMainInstance::Run(int*, node::Environment*) [/usr/local/bin/node]
52: 0x104dff10c node::NodeMainInstance::Run(node::EnvSerializeInfo const*) [/usr/local/bin/node]
53: 0x104d98080 node::Start(int, char**) [/usr/local/bin/node]
54: 0x1959bbe50 start [/usr/lib/dyld]
yarn add v1.22.17
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
.
Error: Command failed: yarn add react-native@0.71.0 react@18.2.0
warning ../package.json: No license field
warning " > @mui/styles@5.10.3" has incorrect peer dependency "react@^17.0.0".
warning " > @react-native-async-storage/async-storage@1.17.10" has incorrect peer dependency "react-native@^0.0.0-0 || 0.60 - 0.70 || 1000.0.0".
warning "@typescript-eslint/eslint-plugin > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
warning " > eslint-plugin-flowtype@8.0.3" has unmet peer dependency "@babel/plugin-syntax-flow@^7.14.5".
warning " > eslint-plugin-flowtype@8.0.3" has unmet peer dependency "@babel/plugin-transform-react-jsx@^7.14.9".
warning " > react-async-script-loader@0.3.0" has incorrect peer dependency "react@^15.5.4".
warning "react-dev-utils > fork-ts-checker-webpack-plugin@6.5.2" has unmet peer dependency "typescript@>= 2.7".
warning " > react-facebook-login@4.1.1" has incorrect peer dependency "react@^16.0.0".
warning " > react-highcharts@16.1.0" has incorrect peer dependency "react@~0.14 || ^15.0.0 || ^16.0.0".
warning " > react-highcharts@16.1.0" has incorrect peer dependency "react-dom@~0.14 || ^15.0.0 || ^16.0.0".
warning "react-router > mini-create-react-context@0.4.1" has incorrect peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0 || ^17.0.0".
warning " > react-stripe-elements@6.1.2" has incorrect peer dependency "react@^15.5.4 || ^16.0.0-0".
warning " > react-stripe-elements@6.1.2" has incorrect peer dependency "react-dom@^15.5.4 || ^16.0.0-0".
warning Workspaces can only be enabled in private projects.

<--- Last few GCs --->

[86273:0x120008000]    49837 ms: Scavenge 4038.8 (4120.2) -> 4036.6 (4123.7) MB, 8.2 / 0.0 ms  (average mu = 0.569, current mu = 0.374) allocation failure 
[86273:0x120008000]    49858 ms: Scavenge 4042.0 (4123.7) -> 4039.4 (4141.2) MB, 9.5 / 0.0 ms  (average mu = 0.569, current mu = 0.374) allocation failure 
[86273:0x120008000]    51452 ms: Mark-sweep 4052.1 (4141.2) -> 4043.8 (4149.7) MB, 1566.0 / 0.0 ms  (average mu = 0.378, current mu = 0.175) allocation failure scavenge might not succeed

<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0x104dc6260 node::Abort() [/usr/local/bin/node]
 2: 0x104dc63e8 node::errors::TryCatchScope::~TryCatchScope() [/usr/local/bin/node]
 3: 0x104f14e88 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 4: 0x104f14e1c v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 5: 0x105098534 v8::internal::Heap::GarbageCollectionReasonToString(v8::internal::GarbageCollectionReason) [/usr/local/bin/node]
 6: 0x105097054 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/bin/node]
 7: 0x1050a239c v8::internal::Heap::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]
 8: 0x1050a2430 v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]
 9: 0x1050752c4 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/usr/local/bin/node]
10: 0x1053ad3c8 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/usr/local/bin/node]
11: 0x1056c1a4c Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/usr/local/bin/node]
12: 0x1056d722c Builtins_ArrayPrototypeJoin [/usr/local/bin/node]
13: 0x1098c8448 
14: 0x109a93ad0 
15: 0x109a966d8 
16: 0x1098d19a0 
17: 0x1056556d8 Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
18: 0x1056556d8 Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
19: 0x105686eac Builtins_GeneratorPrototypeNext [/usr/local/bin/node]
20: 0x109a15e94 
21: 0x109a5ee5c 
22: 0x1056556d8 Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
23: 0x1056556d8 Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
24: 0x105686eac Builtins_GeneratorPrototypeNext [/usr/local/bin/node]
25: 0x109a15e94 
26: 0x109a5ee5c 
27: 0x1056556d8 Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
28: 0x1056556d8 Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
29: 0x105686eac Builtins_GeneratorPrototypeNext [/usr/local/bin/node]
30: 0x109a60b28 
31: 0x1097667f4 
32: 0x105709b78 Builtins_PromiseFulfillReactionJob [/usr/local/bin/node]
33: 0x1056770b4 Builtins_RunMicrotasks [/usr/local/bin/node]
34: 0x1056533a4 Builtins_JSRunMicrotasksEntry [/usr/local/bin/node]
35: 0x105024ce4 v8::internal::(anonymous namespace)::Invoke(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) [/usr/local/bin/node]
36: 0x105025118 v8::internal::(anonymous namespace)::InvokeWithTryCatch(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) [/usr/local/bin/node]
37: 0x105025204 v8::internal::Execution::TryRunMicrotasks(v8::internal::Isolate*, v8::internal::MicrotaskQueue*, v8::internal::MaybeHandle<v8::internal::Object>*) [/usr/local/bin/node]
38: 0x105047e40 v8::internal::MicrotaskQueue::RunMicrotasks(v8::internal::Isolate*) [/usr/local/bin/node]
39: 0x1050486d4 v8::internal::MicrotaskQueue::PerformCheckpoint(v8::Isolate*) [/usr/local/bin/node]
40: 0x104d12db4 node::InternalCallbackScope::Close() [/usr/local/bin/node]
41: 0x104d1348c node::InternalMakeCallback(node::Environment*, v8::Local<v8::Object>, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*, node::async_context) [/usr/local/bin/node]
42: 0x104d284c0 node::AsyncWrap::MakeCallback(v8::Local<v8::Function>, int, v8::Local<v8::Value>*) [/usr/local/bin/node]
43: 0x104dca41c node::fs::FSReqCallback::Reject(v8::Local<v8::Value>) [/usr/local/bin/node]
44: 0x104dcabe8 node::fs::FSReqAfterScope::Reject(uv_fs_s*) [/usr/local/bin/node]
45: 0x104dcaca4 node::fs::AfterNoArgs(uv_fs_s*) [/usr/local/bin/node]
46: 0x105633a5c uv__work_done [/usr/local/bin/node]
47: 0x1056371f8 uv__async_io [/usr/local/bin/node]
48: 0x105648f70 uv__io_poll [/usr/local/bin/node]
49: 0x105637688 uv_run [/usr/local/bin/node]
50: 0x104d13ccc node::SpinEventLoop(node::Environment*) [/usr/local/bin/node]
51: 0x104dff440 node::NodeMainInstance::Run(int*, node::Environment*) [/usr/local/bin/node]
52: 0x104dff10c node::NodeMainInstance::Run(node::EnvSerializeInfo const*) [/usr/local/bin/node]
53: 0x104d98080 node::Start(int, char**) [/usr/local/bin/node]
54: 0x1959bbe50 start [/usr/lib/dyld]
yarn add v1.22.17
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...

    at makeError (/Users/Oskar/trackstats/node_modules/execa/index.js:174:9)
    at /Users/Oskar/trackstats/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async installDeps (/Users/Oskar/trackstats/node_modules/@react-native-community/cli/build/commands/upgrade/upgrade.js:231:3)
    at async Object.upgrade [as func] (/Users/Oskar/trackstats/node_modules/@react-native-community/cli/build/commands/upgrade/upgrade.js:371:9)
    at async Command.handleAction (/Users/Oskar/trackstats/node_modules/@react-native-community/cli/build/index.js:142:9)
info Run CLI with --verbose flag for more details.

### Issue and Reproduction Steps

npx react-native upgrade

**Comment by samuelhulla** [comment]
Usually in issues like this it's just enough to close down applications (including the simulator) and try again. Obviously if it's something more complex it won't help, but sometimes the occam's razor applies (and at least for me when i got the error this always did the trick).

**Comment by OskarEichler** [comment]
Hmm tried closing down all applications (including the simulator) and rebooted, but still running into the same error :/

**Comment by firasbou** [comment]
I am facing the same issue after upgrading from 0.69.7 to 0.71.0
I tried what @samuelhulla suggested but still running into the same error.

**Comment by cortinico** [comment]
> FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory

This is generally related to your machine running out of memory. You should be able to change the amount of memory allocated to Node with `—max-old-space-size=8192` or similar values.

**Comment by douglasndm** [comment]
I had the same problem, and I was able to fix it by deleting "node_modules" folder and resetting the cache.

I used this script `rm -rf node_modules **/node_modules && rm -rf yarn.lock **/yarn.lock && yarn cache clean && yarn install`

**Comment by ttdatt** [comment]
![image](https://user-images.githubusercontent.com/6084022/212448487-f6210791-1eb2-4f44-8a3f-3495fe646ee9.png)
node consumes 4gb RAM when I run `yarn` after that it throws `JavaScript heap out of memory`

**Comment by OskarEichler** [comment]
> I had the same problem, and I was able to fix it by deleting "node_modules" folder and resetting the cache.
> 
> I used this script `rm -rf node_modules **/node_modules && rm -rf yarn.lock **/yarn.lock && yarn cache clean && yarn install`

Legend!! This worked! Thanks a bunch everyone 🤘🏼

**Comment by stianjensen** [comment]
Deleting the yarn.lock file is not a proper solution. This should be reopened, and deleting the lockfile shouldn't be necessary to upgrade react native.

**Comment by deflexable** [comment]
@janlat thanks it works

**Comment by gilluminate** [comment]
rather than removing the yarn.lock file, I was able to solve this by first removing react-native and re-adding it. This cleared out the bad stuff from the yarn.lock file first. Then by re-adding it, it updated the yarn.lock with relevant stuff.

`yarn remove react-native`

`yarn add react-native@latest`

**Comment by AdamGerthel** [comment]
I have the same issue with one project running RN `0.70.5` and I'm pretty sure the problem started after upgrading to MacOS Ventura. I don't have this issue with any other RN project, and I don't have any problems with actual memory on my device.

**Comment by wajahat959** [comment]
in my case only by updating my babel/core helped fixed my issue  from @babel/core: ^7.12.9, i updated to  @babel/core: ^7.24.0,

**Comment by ayush-leap** [comment]
> I had the same problem, and I was able to fix it by deleting "node_modules" folder and resetting the cache.
> 
> I used this script `rm -rf node_modules **/node_modules && rm -rf yarn.lock **/yarn.lock && yarn cache clean && yarn install`

you can also try running `npx react-native clean`, more elegant than this if clearing project is your intention.

<img width="725" alt="image" src="https://github.com/facebook/react-native/assets/163592678/d22bca3c-f3ef-4b66-ac91-723ed92faa90">
