### ISSUE TITLE
Image component in Android has horizontal lines on either side of it #35815

### ISSUE THREAD

**Issue by shreya-as** [facebook/react-native#35833]
### New Version

0.66

### Old Version

0.66

### Build Target(s)

8.6

### Output of `react-native info`

Image component in Android has horizontal lines on either side of it #35815Image component in Android has horizontal lines on either side of it #35815

### Issue and Reproduction Steps

Image component in Android has horizontal lines on either side of it #35815

**Comment by cipolleschi** [comment]
@shreya-as sorry but version 0.66 is not supported anymore. Update to a more recent version of react native (you can find the list [here](https://github.com/reactwg/react-native-releases#releases-support-policy)) and reopen the issue if the problem persists. Thanks.
