### ISSUE TITLE
Not building new project in MAC OS Ventura 13.1

### ISSUE THREAD

**Issue by cl3i550n** [facebook/react-native#35836]
### Description

npx react-native init test    

                  Welcome to React Native!                
                 Learn once, write anywhere               

✔ Downloading template
✔ Copying template
✔ Processing template
✖ Installing Bundler
error Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/Users/clandrade/Documents/RD/PainelRD_New/RN/test/vendor/bundle/ruby/2.7.0/gems/json-2.6.3/ext/json/ext/generator
/Users/clandrade/.rbenv/versions/2.7.6/bin/ruby -I
/Users/clandrade/.rbenv/versions/2.7.6/lib/ruby/2.7.0 -r
./siteconf20230115-89464-1rjt96z.rb extconf.rb
creating Makefile

current directory:
/Users/clandrade/Documents/RD/PainelRD_New/RN/test/vendor/bundle/ruby/2.7.0/gems/json-2.6.3/ext/json/ext/generator
make "DESTDIR=" clean

current directory:
/Users/clandrade/Documents/RD/PainelRD_New/RN/test/vendor/bundle/ruby/2.7.0/gems/json-2.6.3/ext/json/ext/generator
make "DESTDIR="
compiling generator.c
linking shared-object json/ext/generator.bundle
ld: building for iOS Simulator, but linking in dylib built for macOS, file
'/Users/clandrade/.rbenv/versions/2.7.6/lib/libruby.2.7.dylib' for architecture
arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [generator.bundle] Error 1

make failed, exit code 2

Gem files will remain installed in
/Users/clandrade/Documents/RD/PainelRD_New/RN/test/vendor/bundle/ruby/2.7.0/gems/json-2.6.3
for inspection.
Results logged to
/Users/clandrade/Documents/RD/PainelRD_New/RN/test/vendor/bundle/ruby/2.7.0/extensions/arm64-darwin-22/2.7.0/json-2.6.3/gem_make.out

An error occurred while installing json (2.6.3), and Bundler cannot continue.
Make sure that `gem install json -v '2.6.3' --source 'https://rubygems.org/'`
succeeds before bundling.

In Gemfile:
  cocoapods was resolved to 1.11.3, which depends on
    cocoapods-core was resolved to 1.11.3, which depends on
      algoliasearch was resolved to 1.27.5, which depends on
        json

✖ Installing Bundler
error Error: Looks like your iOS environment is not properly set. Please go to https://reactnative.dev/docs/next/environment-setup and follow the React Native CLI QuickStart guide for macOS and iOS.
Error: Error: Looks like your iOS environment is not properly set. Please go to https://reactnative.dev/docs/next/environment-setup and follow the React Native CLI QuickStart guide for macOS and iOS.
    at createFromTemplate (/Users/clandrade/.npm/_npx/7930a8670f922cdb/node_modules/@react-native-community/cli/build/commands/init/init.js:129:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.initialize [as func] (/Users/clandrade/.npm/_npx/7930a8670f922cdb/node_modules/@react-native-community/cli/build/commands/init/init.js:181:3)
    at async Command.handleAction (/Users/clandrade/.npm/_npx/7930a8670f922cdb/node_modules/@react-native-community/cli/build/index.js:106:9)
info Run CLI with --verbose flag for more details.

any help to solve this?

### Version

0.71.x

### Output of `npx react-native info`

npx react-native info don’t work

### Steps to reproduce

Starting new project in MAC OS Ventura 13.1
npx react-native init

### Snack, code example, screenshot, or link to a repository

<img width="1550" alt="Captura de Tela 2023-01-15 às 13 01 07" src="https://user-images.githubusercontent.com/80117221/212552302-c42819bf-6fa7-4125-8950-3afc985374e8.png">

**Comment by Roka20012** [comment]
@cl3i550n  Which version of ruby do you use?
You need to use 2.7.6 for RN 0.71

I would suggest using _rvm_ to manage the default version of ruby, **I have a Ventura 13.1, works well for me**
https://reactnative.dev/docs/environment-setup#ruby

**Comment by Adnanakhter321** [comment]
[PAK301 Mid Term Important.docx](https://github.com/facebook/react-native/files/10420927/PAK301.Mid.Term.Important.docx)

**Comment by cl3i550n** [comment]
> @cl3i550n  Which version of ruby do you use?
> You need to use 2.7.6 for RN 0.71
> 
> I would suggest using _rvm_ to manage the default version of ruby, **I have a Ventura 13.1, works well for me**
> https://reactnative.dev/docs/environment-setup#ruby
> 

Okay, I'll try.

**Comment by cl3i550n** [comment]
> @cl3i550n Which version of ruby do you use? You need to use 2.7.6 for RN 0.71
> 
> I would suggest using _rvm_ to manage the default version of ruby, **I have a Ventura 13.1, works well for me** https://reactnative.dev/docs/environment-setup#ruby

Not working... 

I use rbenv 
and ruby -v
ruby 3.1.3p185 (2022-11-24 revision 1a6b16756e) [arm64-darwin22]

**Comment by Roka20012** [comment]
I had problems with rbenv, that why I switched to renv

**Comment by cl3i550n** [comment]
> 

https://www.moncefbelyamani.com/how-to-install-xcode-homebrew-git-rvm-ruby-on-mac/#step-2-install-chruby-and-the-latest-ruby-with-ruby-install

I'm following this tutorial, but I can't get back to "Command Tools Xcode" version 13.x to install ruby 2.7.6

**Comment by cl3i550n** [comment]
But... a change to 3.1.3.... show this
 
<img width="1375" alt="Captura de Tela 2023-01-15 às 19 00 55" src="https://user-images.githubusercontent.com/80117221/212569505-62e6f51d-f922-46ae-96b8-be65c32989fe.png">

**Comment by cl3i550n** [comment]
> I had problems with rbenv, that why I switched to rvm
> 
> And I use specifically 2.7.6 version


https://www.moncefbelyamani.com/how-to-install-xcode-homebrew-git-rvm-ruby-on-mac/#step-2-install-chruby-and-the-latest-ruby-with-ruby-install

I'm following this tutorial, but I can't get back to "Command Tools Xcode" version 13.x to install ruby 2.7.6

But... a change to 3.1.3.... show this
<img width="1375" alt="Captura de Tela 2023-01-15 às 19 00 55" src="https://user-images.githubusercontent.com/80117221/212569570-3ef5ab00-af1a-4e43-b69f-49f938a53b63.png">

**Comment by Roka20012** [comment]
You on the right way, I had this too, you just need to switch from 3.1.3 to 2.7.6 with your ruby version manager

for rvm I use `rvm use 2.7.6`

ps. rvm give you a tip when you go to a project folder which version of ruby you need to use

**Comment by cl3i550n** [comment]
> You on the right way, I had this too, you just need to switch from 3.1.3 to 2.7.6 with your ruby version manager
> 
> for rvm I use `rvm use 2.7.6`
> 
> ps. rvm give you a tip when you go to a project folder which version of ruby you need to use


Same error


ruby 2.7.6p219 (2022-04-12 revision c9c2245c0a) [arm64-darwin22]

which -a ruby

- /opt/rubies/ruby-2.7.6/bin/ruby
- /usr/bin/ruby

which ruby

- /opt/rubies/ruby-2.7.6/bin/ruby
<img width="1375" alt="Captura de Tela 2023-01-15 às 19 00 55" src="https://user-images.githubusercontent.com/80117221/212569966-4555afb4-784b-42ab-84f1-59561efc3089.png">

**Comment by Roka20012** [comment]
For me still looks like something wrong with ruby

<img width="438" alt="image" src="https://user-images.githubusercontent.com/32239452/212570338-fe92af83-cb73-46be-8d83-6e439b74afad.png">

**Comment by cl3i550n** [comment]
> For me still looks like something wrong with ruby
> 
> <img alt="image" width="438" src="https://user-images.githubusercontent.com/32239452/212570338-fe92af83-cb73-46be-8d83-6e439b74afad.png">

Any idea?  this folder was create after npx react-native init <name>

<img width="1032" alt="Captura de Tela 2023-01-15 às 19 25 09" src="https://user-images.githubusercontent.com/80117221/212570442-1c969317-28f5-44c8-94ec-9d7a5335f57f.png">

**Comment by Roka20012** [comment]
Unfortunately not :/

**Comment by Roka20012** [comment]
Have you tried this?

<img width="674" alt="image" src="https://user-images.githubusercontent.com/32239452/212570650-422b9baa-bfb8-487e-a741-49ca563aa5d5.png">

**Comment by cl3i550n** [comment]
> Unfortunately not :/

Makefile show 

topdir = /opt/rubies/ruby-2.7.6/include/ruby-2.7.0
arch_hdrdir = /opt/rubies/ruby-2.7.6/include/ruby-2.7.0/arm64-darwin22

<img width="619" alt="Captura de Tela 2023-01-15 às 19 30 31" src="https://user-images.githubusercontent.com/80117221/212570645-3bdf297c-b2eb-4d82-ab45-71d29f2dfd08.png">

**Comment by cl3i550n** [comment]
> Have you tried this?
> 
> https://reactnative.dev/docs/environment-setup#creating-a-new-application
> 
> <img alt="image" width="674" src="https://user-images.githubusercontent.com/32239452/212570650-422b9baa-bfb8-487e-a741-49ca563aa5d5.png">

Yes, the bundle works, but yarn start or npm start stops working because the new project didn't come complete, missing files to start.

**Comment by cl3i550n** [comment]
> Have you tried this?
> 
> https://reactnative.dev/docs/environment-setup#creating-a-new-application
> 
> <img alt="image" width="674" src="https://user-images.githubusercontent.com/32239452/212570650-422b9baa-bfb8-487e-a741-49ca563aa5d5.png">

```
ios % bundle install
Fetching gem metadata from https://rubygems.org/........
Resolving dependencies...
Using rexml 3.2.5
Using CFPropertyList 3.0.5
Using concurrent-ruby 1.1.10
Using i18n 1.12.0
Using minitest 5.17.0
Using tzinfo 2.0.5
Using zeitwerk 2.6.6
Using activesupport 6.1.7
Using public_suffix 4.0.7
Using addressable 2.8.1
Using httpclient 2.8.3
Fetching json 2.6.3
Installing json 2.6.3 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/Users/clandrade/Documents/RD/PainelRD_New/RN/test/vendor/bundle/ruby/2.7.0/gems/json-2.6.3/ext/json/ext/generator
/opt/rubies/ruby-2.7.6/bin/ruby -I /opt/rubies/ruby-2.7.6/lib/ruby/2.7.0 -r
./siteconf20230115-51998-jzvpvi.rb extconf.rb
creating Makefile

current directory:
/Users/clandrade/Documents/RD/PainelRD_New/RN/test/vendor/bundle/ruby/2.7.0/gems/json-2.6.3/ext/json/ext/generator
make "DESTDIR=" clean

current directory:
/Users/clandrade/Documents/RD/PainelRD_New/RN/test/vendor/bundle/ruby/2.7.0/gems/json-2.6.3/ext/json/ext/generator
make "DESTDIR="
compiling generator.c
linking shared-object json/ext/generator.bundle
ld: building for iOS Simulator, but linking in dylib built for macOS, file
'/opt/rubies/ruby-2.7.6/lib/libruby.2.7.dylib' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [generator.bundle] Error 1

make failed, exit code 2

Gem files will remain installed in
/Users/clandrade/Documents/RD/PainelRD_New/RN/test/vendor/bundle/ruby/2.7.0/gems/json-2.6.3
for inspection.
Results logged to
/Users/clandrade/Documents/RD/PainelRD_New/RN/test/vendor/bundle/ruby/2.7.0/extensions/arm64-darwin-22/2.7.0/json-2.6.3/gem_make.out

An error occurred while installing json (2.6.3), and Bundler cannot
continue.
Make sure that `gem install json -v '2.6.3' --source 'https://rubygems.org/'`
succeeds before bundling.

In Gemfile:
  cocoapods was resolved to 1.11.3, which depends on
    cocoapods-core was resolved to 1.11.3, which depends on
      algoliasearch was resolved to 1.27.5, which depends on
        json

```

**Comment by Roka20012** [comment]
Could be this issue

https://stackoverflow.com/a/19532316

**Comment by cl3i550n** [comment]
> Installing json 2.6.3 with native extensions
> Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

This new mac M2 is a hard config of ruby... i have four days trying building new RN project...

**Comment by Roka20012** [comment]
> This new mac M2 is a hard config of ruby... i have four days trying building new RN project...

@cl3i550n then I can't help you with that(
Maybe anyone else with new macs have this issue

**Comment by cl3i550n** [comment]
> > This new mac M2 is a hard config of ruby... i have four days trying building new RN project...
> 
> @cl3i550n then I can't help you with that( Maybe anyone else with new macs have this issue

This link is a best tutorial... but not have sucesse because i not have "develop account" to downgrade xcode commands tools... this works fine with 13.x version... 

My version is 14.x 

<img width="942" alt="Captura de Tela 2023-01-15 às 20 06 25" src="https://user-images.githubusercontent.com/80117221/212572226-c3a987bd-254f-4575-9246-550cf59f0891.png">

**Comment by Roka20012** [comment]
I have the same xcode version

**Comment by cl3i550n** [comment]
> I have the same xcode version 🤷‍♂️

do you remember how your solved problem?

**Comment by Roka20012** [comment]
> do you remember how your solved problem?
Yes, I just switched to rvm to manage ruby, I h've used rbenv but didn't work for me


```
export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"
```

**Comment by cl3i550n** [comment]
> > do you remember how your solved problem?
> Yes, I just switched to rvm to manage ruby, I h've used rbenv but didn't work for me
> 
> 
> ```
> export ANDROID_HOME=$HOME/Library/Android/sdk
> export PATH=$PATH:$ANDROID_HOME/emulator
> export PATH=$PATH:$ANDROID_HOME/tools
> export PATH=$PATH:$ANDROID_HOME/tools/bin
> export PATH=$PATH:$ANDROID_HOME/platform-tools
> 
> # Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
> export PATH="$PATH:$HOME/.rvm/bin"
> ```
> 

I really don't understand... Five days... Try...

**Comment by SeekUpBeach** [comment]
I just did a fresh install and have the exact same issue. I have tried the above still with no luck. I have an M1 chip.

**Comment by kirbyjs** [comment]
I was also running into this issue on my m1 pro, but @Roka20012's comment about the ios workaround worked for me. https://github.com/facebook/react-native/issues/35836#issuecomment-1383270551

**Comment by cl3i550n** [comment]
> I just did a fresh install and have the exact same issue. I have tried the above still with no luck. I have an M1 chip.

Downgrade version of RN to 0.6.x

And try this

https://www.moncefbelyamani.com/how-to-install-xcode-homebrew-git-rvm-ruby-on-mac/#step-2-install-chruby-and-the-latest-ruby-with-ruby-install

Or this 

![received_727934915365272 (convert.io).png](https://user-images.githubusercontent.com/80117221/212763378-dc48317f-72b1-4d10-955a-a61a908c4f0a.png)

Works for me old version of RN

**Comment by cl3i550n** [comment]
> I was also running into this issue on my m1 pro, but @Roka20012's comment about the ios workaround worked for me. https://github.com/facebook/react-native/issues/35836#issuecomment-1383270551

But my problem is create a new project... :(

**Comment by kirbyjs** [comment]
@cl3i550n right - it fails for me as well when creating a new project, but even tho it fails there, it still creates the new project directory structure, so you should still be able to `cd test` (in your example) and then follow those steps.

Or does the directory `test` not even exist for you?

**Comment by cl3i550n** [comment]
> @cl3i550n right - it fails for me as well when creating a new project, but even tho it fails there, it still creates the new project directory structure, so you should still be able to `cd test` (in your example) and then follow those steps.
> 
> Or does the directory `test` not even exist for you? 

Exist... But not working bundle install and pod install... Inside folder ios create

**Comment by cl3i550n** [comment]
> > Have you tried this?
> > 
> > https://reactnative.dev/docs/environment-setup#creating-a-new-application
> > 
> > <img alt="image" width="674" src="https://user-images.githubusercontent.com/32239452/212570650-422b9baa-bfb8-487e-a741-49ca563aa5d5.png">
> 
> ```
> ios % bundle install
> Fetching gem metadata from https://rubygems.org/........
> Resolving dependencies...
> Using rexml 3.2.5
> Using CFPropertyList 3.0.5
> Using concurrent-ruby 1.1.10
> Using i18n 1.12.0
> Using minitest 5.17.0
> Using tzinfo 2.0.5
> Using zeitwerk 2.6.6
> Using activesupport 6.1.7
> Using public_suffix 4.0.7
> Using addressable 2.8.1
> Using httpclient 2.8.3
> Fetching json 2.6.3
> Installing json 2.6.3 with native extensions
> Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
> 
> current directory:
> /Users/clandrade/Documents/RD/PainelRD_New/RN/test/vendor/bundle/ruby/2.7.0/gems/json-2.6.3/ext/json/ext/generator
> /opt/rubies/ruby-2.7.6/bin/ruby -I /opt/rubies/ruby-2.7.6/lib/ruby/2.7.0 -r
> ./siteconf20230115-51998-jzvpvi.rb extconf.rb
> creating Makefile
> 
> current directory:
> /Users/clandrade/Documents/RD/PainelRD_New/RN/test/vendor/bundle/ruby/2.7.0/gems/json-2.6.3/ext/json/ext/generator
> make "DESTDIR=" clean
> 
> current directory:
> /Users/clandrade/Documents/RD/PainelRD_New/RN/test/vendor/bundle/ruby/2.7.0/gems/json-2.6.3/ext/json/ext/generator
> make "DESTDIR="
> compiling generator.c
> linking shared-object json/ext/generator.bundle
> ld: building for iOS Simulator, but linking in dylib built for macOS, file
> '/opt/rubies/ruby-2.7.6/lib/libruby.2.7.dylib' for architecture arm64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make: *** [generator.bundle] Error 1
> 
> make failed, exit code 2
> 
> Gem files will remain installed in
> /Users/clandrade/Documents/RD/PainelRD_New/RN/test/vendor/bundle/ruby/2.7.0/gems/json-2.6.3
> for inspection.
> Results logged to
> /Users/clandrade/Documents/RD/PainelRD_New/RN/test/vendor/bundle/ruby/2.7.0/extensions/arm64-darwin-22/2.7.0/json-2.6.3/gem_make.out
> 
> An error occurred while installing json (2.6.3), and Bundler cannot
> continue.
> Make sure that `gem install json -v '2.6.3' --source 'https://rubygems.org/'`
> succeeds before bundling.
> 
> In Gemfile:
>   cocoapods was resolved to 1.11.3, which depends on
>     cocoapods-core was resolved to 1.11.3, which depends on
>       algoliasearch was resolved to 1.27.5, which depends on
>         json
> 
> ```

@kirbyjs 


This error show after bundle install...

**Comment by SeekUpBeach** [comment]
I was able to get it working.

1. Install XCode
2. Install brew
3. Install rvm 
4. brew install node
5. brew install watchman
6. rvm Install 2.7.6
7. rvm use 2.7.6 --default

8. On an intel based mac with Ventura I had to do the recommend above after the init of the project.
https://reactnative.dev/docs/environment-setup#creating-a-new-application

9. On the M1 based mac with Ventura I had to open XCode and select the command line tools even though it showed them in there, I had to open the drop down which had no other options. It triggered something because I had to re-login after that it would run "bundle exec pod install". After that it would build install the pod then would run.

**Comment by restarajat** [comment]
use `rvm install 2.7.6` and then `rvm --default use 2.7.6`

**Comment by daviz00** [comment]
> 

this worked very well, thanks.
remove the cocoapods installation by brew and do it using sudo gem install cocoapods

**Comment by cl3i550n** [comment]
<img width="1295" alt="Captura de Tela 2023-01-19 às 10 25 26" src="https://user-images.githubusercontent.com/80117221/213454236-c4349a88-7c00-4bbe-9438-c0d3876cd231.png">


i try all.... not install or work


> I was able to get it working.
> 
> 1. Install XCode
> 2. Install brew
> 3. Install rvm
> 4. brew install node
> 5. brew install watchman
> 6. rvm Install 2.7.6
> 7. rvm use 2.7.6 --default
> 8. sudo gem install cocoapods
> 9. npx react-native init TestProject (it fails but adds the project)
> 10. On an intel based mac with Ventura I had to do the recommend above after the init of the project.
>     https://reactnative.dev/docs/environment-setup#creating-a-new-application
> 11. On the M1 based mac with Ventura I had to open XCode and select the command line tools even though it showed them in there, I had to open the drop down which had no other options. It triggered something because I had to re-login after that it would run "bundle exec pod install". After that it would build install the pod then would run.

**Comment by cl3i550n** [comment]
guys..... 
@cortinico 
@kirbyjs 
@Roka20012 
@daviz00 

Guys, don't ask me why, but when using the `sudo npx react-native init project` command.
It worked 100% 😳😳😳😳

**Comment by cortinico** [comment]
> Guys, don't ask me why, but when using the sudo npx react-native init project command.
It worked 100% 😳😳😳😳

Great, so I'm closing this 👍

**Comment by cl3i550n** [comment]
Note for this post.
Don't use sudo to install any dependencies

I unistalling all, literally...
And install all again **winthout sudo**!!!!

after 7 days... my problem was permissions because
i installed some dependencies with sudo and any rubys versions and etc......

delete all cache or folders, and start of zero inside of opt/homebrew erease all 

now go your folder <YourUser>
now use cmd + shift + .


your see hide folders
delete all... caution this!
delete only what you are sure are remnants of a bad installation of the environment

try install all again winthout sudo

homebrew
watchman
node (lts)
Zulu11 (Java)
cocoa pods gem

Only in my .zshrc path envrioments
Rbenv,
homebrew
gem (see docs)

My OS

macOS 13.1 Ventura
Apple Silicon M2
Tools of Xode 14.x (lts)

**Comment by cl3i550n** [comment]
![received_3372063893043435 (convert.io).png](https://user-images.githubusercontent.com/80117221/213567098-c90dc9bf-938c-4380-a1bf-5cccd60a39a8.png)

**Comment by joshuadiezmo** [comment]
change ruby version to `2.7.6` close terminal, reopen terminal and create new app.
