### ISSUE TITLE
[iOS][0.13.0-rc] Null jsBundleLocation throws error instead of RedBox

### ISSUE THREAD

**Issue by arbesfeld** [facebook/react-native#3583]
In 0.12.0 there would be a red box error when an `RCTRootView` was created with a bundleURL that did not exist.

In 0.13.0-rc an error is thrown:
```
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'It looks like the implementationof __DEV__ has changed. Update -[RCTBatchedBridge loadSource:].'
```

**Comment by nosensezzz** [comment]
Same here, after I update ios to 9.1 and xcode to 7.1, it happened.

**Comment by christopherdro** [comment]
@arbesfeld Looks like this issue has been resolved. Are you still running into this problem?
