### ISSUE TITLE
App not behaving when not debugging

### ISSUE THREAD

**Issue by mangogogos** [facebook/react-native#3584]
I recently changed around some of my logic for the initialization of my application, but I think I've introduced a bug. The problem is that for whatever reason, when I load my app I am faced with only an empty screen but when I connect to the chrome debugging tools everything works exactly as it should. I think that there must be something cached or different between what the js is doing when run through the debugging tools, but without access to console Im having trouble finding the location of what I assume is a bug I introduced. Does anyone know what would cause the app to behave differently when debugging or how I could trace the issue?

**Comment by jaygarcia** [comment]
this is very very strange.  I've never run into this.  take a look at the packaged output and run it through a linter.  See if there may be erroneous statements or syntax errors that may be causing this.

**Comment by mangogogos** [comment]
Where can I find the packaged output?

**Comment by mangogogos** [comment]
I FOUND THE ISSUE! One of my many stylesheets had a couple of duplicates, specifically

>blah = StyleSheet.create(
>{
>  blah1: {
>    flexDirection: 'row',
>    flexDirection: 'row, // aw come on it's just a duplicate you should know what to do!
>    ...
>  },
>  blah2: {
>    justifyContent: 'center',
>    ...
>    justifyContent: 'flex-start', //whoops this one is pretty erroneous my bad!
>  },
>  ...
>}
>} );

when I would start the application normally having either one of those would independently cause the loading to fail and I would be left with a hanging, empty screen

when I debug the application in chrome, the application runs exactly as it should with blah2 using flex-start IIRC

Hopefully someone can confirm this issue and then add a check for it in stylesheet.create as having this fail silently was a serious head scratcher, especially since everything worked in debugging!

**Comment by satya164** [comment]
@mangogogos You should use a linter like `eslint` which can catch these kinds of errors early.

**Comment by caohongtao** [comment]
I encountered the same problem. And I found the following reason.
I used ECMAScript 6 Features,the keyword "const".  and I'm not sure if these features are only surpported in a browser.

I changed `const SERVER = 'http://www.yudianer.com/api';` to `var SERVER = 'http://www.yudianer.com/api';` ,  then the problem is fixed.

Maybe you can check if you use some ECMAScript 6 Features.

**Comment by satya164** [comment]
@caohongtao You can easily add a custom `.babelrc` to enable ES6 features you need.

**Comment by mangogogos** [comment]
I still think there should be a check in place in the stylesheet create method so that this isn't a silent issue but Im going to mark this as closed

**Comment by satya164** [comment]
@mangogogos I don't think you can catch duplicate properties in objects. It is handled by runtime itself. I strongly suggest you use a linter to avoid obvious programmer errors.

**Comment by mangogogos** [comment]
@satya164 just wanted to give a huge thanks for insisting I use eslint!

**Comment by satya164** [comment]
@mangogogos Glad it helped you :D
