### ISSUE TITLE
[0.13] Changes for next release

### ISSUE THREAD

**Issue by ide** [facebook/react-native#3585]
- https://github.com/facebook/react-native/pull/3347 for web sockets
- Stop publishing to CocoaPods. I'll write up how to migrate off of using the podspec repo. The reason for this is that the packager gets confused when there are two copies of RN which happens if you have one in your Pods folder and one in node_modules. This doesn't mean that people need to stop using CocoaPods -- just that they'll get the source from npm.

Everything else will go out with 0.14-rc.

**Comment by ide** [comment]
I'd also like to move off of Maven and centralize distribution through npm. It'd be super great to get the Android build fast enough so we can always build from source (e.g. use buck instead of gradle and perhaps include the Boost libs with RN so we don't download from sourceforge all the time).

**Comment by jaygarcia** [comment]
Does this mean that support for CocoaPods is now removed as of 0.13?

**Comment by ide** [comment]
No -- using CocoaPods the tool is supported. The pods repository may not be supported.

**Comment by jaygarcia** [comment]
Copy.  Thanks.

**Comment by hufeng** [comment]
buck is awesome.

**Comment by ide** [comment]
0.13 was published awhile ago - closing
