### ISSUE TITLE
Failed to install CocoaPods dependencies when creating a new project

### ISSUE THREAD

**Issue by mrsants** [facebook/react-native#35852]
### Description

✔ Downloading template
✔ Copying template
✔ Processing template
✖ Installing CocoaPods dependencies (this may take a few minutes)
✖ Installing CocoaPods dependencies (this may take a few minutes)
error Error: Failed to install CocoaPods dependencies for iOS project, which is required by this template.

### Version

0.71.0

### Output of `npx react-native info`

I am using rbenv to manage ruby versions

 rbenv versions
  system
  2.7.6

### Steps to reproduce

npx react-native init PandaParking --template react-native-template-typescript

### Snack, code example, screenshot, or link to a repository

![image](https://user-images.githubusercontent.com/59406899/212791138-33173653-845f-4696-81e4-42f2f3360d90.png)

**Comment by cipolleschi** [comment]
Hi @mrsants. The `--template react-native-template-typescript` is not required anymore, as we are shipping typescript types by default. See [here](https://reactnative.dev/blog/2023/01/12/version-071) for more details.

We need more information to help you out, but it looks like a problem in your local setup. 
Could you try to install the pods manually? To do so:

```
cd PandaParking/ios
bundle install # you need to run this only once
bundle exec pod install
```  
This will output a more informative error and we can continue from there. 

Thank you so much for your patience.

**Comment by migueldaipre** [comment]
@mrsants what version of ruby ​​are you on?

**Comment by mrsants** [comment]
> Hi @mrsants. The `--template react-native-template-typescript` is not required anymore, as we are shipping typescript types by default. See [here](https://reactnative.dev/blog/2023/01/12/version-071) for more details.
> 
> We need more information to help you out, but it looks like a problem in your local setup. Could you try to install the pods manually? To do so:
> 
> ```
> cd PandaParking/ios
> bundle install # you need to run this only once
> bundle exec pod install
> ```
> 
> This will output a more informative error and we can continue from there.
> 
> Thank you so much for your patience.

i tested only with npx react-native init AwesomeProject and have the same error

<img width="2560" alt="Captura de Tela 2023-01-23 às 23 45 12" src="https://user-images.githubusercontent.com/59406899/214202044-a0d61019-4772-4ff8-84ed-990aacc54b28.png">

Details, I can install the pods with pod install

**Comment by cipolleschi** [comment]
The image posted in the last message does not present any error. It looks it is taking more time to install them.

You can confirm that you can successfully run
```
cd AwesomePandaParking/ios
bundle install
bundle exec pod install
```
And these commands does not output any error?

----
Another test you can do is to run
```
npx react-native init AwesomePandaParking --skip-install
cd AwesomePandaParking
yarn install
cd ios
bundle install
bundle exec pod install
```

This basically create the app without installing the dependencies, so you have to install them yourself, but at least we can try to understand what's going wrong.

Thank you for your patience!

**Comment by mrsants** [comment]
> npx react-native init AwesomePandaParking --skip-install

using skip install and installing the pods manually works fine, I don't know if there's a need to keep the issue open, but it would be interesting to investigate the other possibility

**Comment by cipolleschi** [comment]
it's weird that the automatic process fails and if we run the same exact steps manually, it works. 😕
unfortunately, without a proper error message, there is nothing much we can do.

**Comment by betomoedano** [comment]
Same issue 😕

**Comment by cipolleschi** [comment]
@betomoedano can you try to manually install the dependencies by:
1. `cd <yourProject>/ios`
2. `bundle install`
3. `bundle exec pod install`
?

If it fails, can you report the error?

**Comment by betomoedano** [comment]
Installing manually works fine. Thanks for your reply. 👋🏼

**Comment by mrsants** [comment]
manual works for version 0.71.0 and 0.73.0

**Comment by tuanhuynhdev** [comment]
RN  version: 0.72.3

I hard try with this solution:

```
npx react-native init AwesomePandaParking --skip-install
cd AwesomePandaParking
yarn install
cd ios
bundle install
bundle exec pod install

```

but **FAILED**.

`Installing hermes-engine (0.72.3)`

and, nothing next, i wait 30 mins !!

```
[Hermes] Using the release tarball from Maven Central
Downloading dependencies
Installing CocoaAsyncSocket (7.6.5)
Installing DoubleConversion (1.1.6)
Installing FBLazyVector (0.72.3)
Installing FBReactNativeSpec (0.72.3)
Installing Flipper (0.182.0)
Installing Flipper-Boost-iOSX (1.76.0.1.11)
Installing Flipper-DoubleConversion (3.2.0.1)
Installing Flipper-Fmt (7.1.7)
Installing Flipper-Folly (2.6.10)
Installing Flipper-Glog (0.5.0.5)
Installing Flipper-PeerTalk (0.0.4)
Installing FlipperKit (0.182.0)
Installing OpenSSL-Universal (1.1.1100)
Installing RCT-Folly (2021.07.22.00)
Installing RCTRequired (0.72.3)
Installing RCTTypeSafety (0.72.3)
Installing React (0.72.3)
Installing React-Codegen (0.72.3)
Installing React-Core (0.72.3)
Installing React-CoreModules (0.72.3)
Installing React-NativeModulesApple (0.72.3)
Installing React-RCTActionSheet (0.72.3)
Installing React-RCTAnimation (0.72.3)
Installing React-RCTAppDelegate (0.72.3)
Installing React-RCTBlob (0.72.3)
Installing React-RCTImage (0.72.3)
Installing React-RCTLinking (0.72.3)
Installing React-RCTNetwork (0.72.3)
Installing React-RCTSettings (0.72.3)
Installing React-RCTText (0.72.3)
Installing React-RCTVibration (0.72.3)
Installing React-callinvoker (0.72.3)
Installing React-cxxreact (0.72.3)
Installing React-debug (0.72.3)
Installing React-hermes (0.72.3)
Installing React-jsi (0.72.3)
Installing React-jsiexecutor (0.72.3)
Installing React-jsinspector (0.72.3)
Installing React-logger (0.72.3)
Installing React-perflogger (0.72.3)
Installing React-rncore (0.72.3)
Installing React-runtimeexecutor (0.72.3)
Installing React-runtimescheduler (0.72.3)
Installing React-utils (0.72.3)
Installing ReactCommon (0.72.3)
Installing SocketRocket (0.6.1)
Installing Yoga (1.14.0)
Installing YogaKit (1.18.1)
Installing boost (1.76.0)
Installing fmt (6.2.1)
Installing glog (0.3.5)
Installing hermes-engine (0.72.3)
```

Thank in advanced for any solution!
Thanks!

**Comment by sathiyaraj45** [comment]
@cipolleschi I tried you suggest command but I got the following error. 

[!] Error installing boost
[!] /usr/bin/curl -f -L -o /var/folders/_y/1jlgk27j6xz72bwmny4f2_cw0000gq/T/d20230915-11391-i08i2k/file.tbz https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.bz2 --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.12.1 cocoapods-downloader/1.6.3'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
 99  104M   99  104M    0     0  2012k      0  0:00:53  0:00:53 --:--:--     0
curl: (56) LibreSSL SSL_read: error:02FFF036:system library:func(4095):Connection reset by peer, errno 54

**Comment by cipolleschi** [comment]
The error says: `Connection reset by peer, errno 54` which means that your connection dropped. Try again, please.

**Comment by sathiyaraj45** [comment]
We tried many time but we got the same error.

**Comment by sathiyaraj45** [comment]
we tried ping https://boostorg.jfrog.io but we unable to reach the data.

**Comment by popejrh19** [comment]
Stop unsubscribe

William Pope Jr

**Comment by cortinico** [comment]
Closing as stale + most likely related to a local network flakyness
