### ISSUE TITLE
Error when updating to v0.71.0 from 0.70.6

### ISSUE THREAD

**Issue by marcofuentes05** [facebook/react-native#35884]
### New Version

0.71.0

### Old Version

0.70.6

### Build Target(s)

iOS simulator in dev mode

### Output of `react-native info`

```info Fetching system and libraries information...
System:
    OS: macOS 13.0
    CPU: (8) arm64 Apple M1
    Memory: 199.20 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.3.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.2.0 - /opt/homebrew/bin/npm
    Watchman: 2023.01.09.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.70.6 => 0.70.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Issue and Reproduction Steps

When I try to upgrade to the new version using `npx react-native upgrade` I get the following error: 
```
error Excluding files that failed to apply the diff:
  - android/app/src/main/java/com/reactnativemobileworker/newarchitecture/modules/MainApplicationTurboModuleManagerDelegate.java
  - android/app/src/main/jni/CMakeLists.txt
  - ios/Podfile
Please make sure to check the actual changes after the upgrade command is finished.
You can find them in our Upgrade Helper web app: https://react-native-community.github.io/upgrade-helper/?from=0.70.6&to=0.71.0
error Automatically applying diff failed. We did our best to automatically upgrade as many files as possible
warn Continuing after failure. Some of the files are upgraded but you will need to deal with conflicts manually
```

and then I get an `error code 65` when I try to run the app on the iOS simulator (which was working before). 

NOTE: When I downgrade back to 0.70.6 I can get it to work again.

**Comment by cortinico** [comment]
> When I try to upgrade to the new version using `npx react-native upgrade` I get the following error:

The message is suggesting you what to do, have you followed the steps @marcofuentes05 ?
Specifically you need to:

Delete:
  - android/app/src/main/java/com/reactnativemobileworker/newarchitecture/modules/MainApplicationTurboModuleManagerDelegate.java
  - android/app/src/main/jni/CMakeLists.txt

Manually merge using  https://react-native-community.github.io/upgrade-helper/?from=0.70.6&to=0.71.0
  - ios/Podfile

You won't be able to run the app till you do those steps.

**Comment by cortinico** [comment]
Closing as the author is unresponsive
