### ISSUE TITLE
[0.71.0] [ANDROID 9] Keyboard events do not fire on Android 9

### ISSUE THREAD

**Issue by bigcupcoffee** [facebook/react-native#35894]
### Brief
After upgrading an app to 0.71 everything depending on keyboard events didn't work. After short investigation issue has been narrowed down to Android 9, as my real device is android 9, another real device that works perfectly is Android 12.

Issue is reproducible on AVD with Android 9 Pie.

Downgrading to 0.70.6 fixes this.

### What exactly happens
Noticed that if subscribed to the events in App.js, the show event fires once as soon as app starts up. Could be related I guess?

### Version

0.71.0

### Output of `npx react-native info`

Is not necessary

### Steps to reproduce

1. Tap input
2. Keyboard pops up, events do not

### Snack, code example, screenshot, or link to a repository

I simply used fresh new app with these insertions:
```js
  useEffect(() => {
    const didShow = Keyboard.addListener('keyboardDidShow', event => {
      console.log('keyboard did show');
    });
    const didHide = Keyboard.addListener('keyboardDidHide', event => {
      console.log('keyboard did hide');
    });

    return () => {
      didShow.remove();
      didHide.remove();
    };
  }, []);
  // add to the bottom of ScrollView
  <TextInput placeholder="input is here" />
```

**Comment by NickGerleman** [comment]
RN 0.71 moved to the androidx WindowInsetsCompat for keyboard events on recent-ish versions of Android, which fixes some other longstanding issues https://github.com/facebook/react-native/commit/1e48274223ee647ac4fc2c21822b5240f3c47e4c

The API is documented by Google to be reliable on Android 6+, but maybe that isn't the case...

Out of curiosity, what softInputMode is your activity? Could imagine that being a factor, but if WindowInsetsCompat isn't working as expected, the legacy code is still there, gated by an OS version check already.

**Comment by bigcupcoffee** [comment]
> Out of curiosity, what softInputMode is your activity? Could imagine that being a factor

@NickGerleman `adjustResize` of course (reproducible on template app).
Doesn't look very reliable if it's I could repro it on recommended Android 9 AVD image 🤷, can't blame my specific brand image here

**Comment by NickGerleman** [comment]
Whelp... that's not good. If we aren't firing events at all, then `isVisible(WindowInsetsCompat.Type.ime())` seems to not be returning correctly. 

The documentation for that method is:
> Returns whether a set of windows that may cause insets is currently visible on screen, regardless of whether it actually overlaps with this window. When running on devices with API Level 29 and before, the returned value is an approximation based on the information available. This is especially true for the [IME](https://developer.android.com/reference/androidx/core/view/WindowInsetsCompat.Type#ime()) type, which currently only works when running on devices with SDK level 23 and above.

If it isn't returning at all, on API 28, the last sentence doesn't seem accurate. The logic can be changed to avoid WindowInsetsCompat, and just use WindowInsets when natively present, falling back to RN's old heuristic for anything before.

**Comment by bigcupcoffee** [comment]
> Noticed that if subscribed to the events in App.js, the show event fires once as soon as app starts up. Could be related I guess?
It appears it does return something? Excuse if I'm being lost since I'm not friendly with native side, but apparently it just thinks that keyboard is permanently open 🤔

**Comment by fabriziobertoglio1987** [comment]
https://github.com/facebook/react-native/issues/14887#issuecomment-810427685

https://android.googlesource.com/platform/frameworks/base/+/d54f3f41c4b41955b7b4382a08b97a356b31fde4/core/java/android/view/View.java#5316

<img width="962" alt="Screenshot 2023-01-20 at 9 17 39 AM" src="https://user-images.githubusercontent.com/24992535/213648492-49127287-9aa8-429f-8725-fa5b2672a8fc.png">

Not sure if this is relevant. I did not work on this for a long time. I am adding it for reference and documentation.
