### ISSUE TITLE
Not able to use --simulator when a device is plugged trough USB

### ISSUE THREAD

**Issue by clucasalcantara** [facebook/react-native#35907]
### Description

I use an AirPad as side car and even triggering `react-native run-ios --simulator="iPhone 14 Pro"` the CLI still tries to build and install the app on the iPad

### Version

0.71.1

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 1.14 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
    Yarn: 1.22.19 - ~/projects/primal/primal-app/node_modules/.bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.1/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 18.0.1.1 - /opt/homebrew/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

With an USB plugged device try to run on simulator `react-native run-ios --simulator="iPhone 14 Pro"`

### Snack, code example, screenshot, or link to a repository

<img width="595" alt="Screenshot 2023-01-19 at 3 15 00 PM" src="https://user-images.githubusercontent.com/6919712/213583157-5a5bd205-8074-4731-8a4e-1f2729897541.png">

Destination showed is the iPad address

**Comment by gtokman** [comment]
```
[build] info Found Xcode workspace "mobile.xcworkspace"
[build] info Found booted MacBook Pro
[build] info Building (using "xcodebuild -workspace mobile.xcworkspace -configuration Debug -scheme mobile -destination id=DDE54B8C-3398-566D-A929-C18D2E1D8FBB")
[build] - Building the app......
[build] error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 70. To debug build logs further, consider building your app with Xcode.app, by opening mobile.xcworkspace.
[build] Command line invocation:
[build]     /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -workspace mobile.xcworkspace -configuration Debug -scheme mobile -destination id=DDE54B8C-3398-566D-A929-C18D2E1D8FBB
[build] 
[build] User defaults from command line:
[build]     IDEPackageSupportUseBuiltinSCM = YES
```

Also seeing this when building in the CLI. Building in Xcode directly works fine.

**Comment by wouterds** [comment]
I see the same behavior if the device is detected through network that is enabled for development.

**Comment by adamTrz** [comment]
That's a bug @ react-native-cli. We're currently working on it and have a fix soon :)

**Comment by wouterds** [comment]
@adamTrz great!

**Comment by szymonrybczak** [comment]
Let's close this issue 😄 cc. @cortinico
