### ISSUE TITLE
Could not find com.facebook.react:react-android:0.71.1

### ISSUE THREAD

**Issue by brokenpieworld** [facebook/react-native#35904]
### Description

0.71.1 version not working on android and getting below error on normal react native installation.

`Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not find com.facebook.react:react-android:0.71.1.
     Required by:
         project :app
   > Could not find com.facebook.react:hermes-android:0.71.1.
     Required by:
         project :app
   > Could not find com.facebook.react:react-android:0.71.1.
     Required by:
         project :app > project :react-native-firebase_app
         project :app > project :react-native-firebase_auth
         project :app > project :react-native-firebase_firestore
         project :app > project :react-native-firebase_in-app-messaging
         project :app > project :react-native-firebase_messaging
         project :app > project :timwangdev_react-native-geocoder
         project :app > project :react-native-encrypted-storage

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

`

### Version

0.71.1

### Output of `npx react-native info`

System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1
    Memory: 48.86 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.4.0 - /opt/homebrew/bin/node
    Yarn: Not Found
    npm: 9.3.0 - /opt/homebrew/bin/npm
    Watchman: 2023.01.16.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/fullmad/.rvm/gems/ruby-2.7.6/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9477386
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.1 => 0.71.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Just install the react native and run on android using `npm run android`

### Snack, code example, screenshot, or link to a repository

N/A

**Comment by kelset** [comment]
yes, we know and we are sorry for the disruption: for some reason despite our release pipeline [going all green](https://app.circleci.com/pipelines/github/facebook/react-native/18921/workflows/902b1bb7-98bb-4300-a5ad-b7e8de25ddd8/jobs/417780) and the maven central toolchain too, [the artifacts are not appearing](https://repo1.maven.org/maven2/com/facebook/react/react-native-artifacts/0.71.1/) where they should be. We have opened [a ticket on them](https://issues.sonatype.org/browse/OSSRH-88055) and we'll update you all once it's fixed.

Hopefully it's just some of their infra being slow to propagate the artifacts, it looks like they have been doing [some scaling over the last few days](https://status.maven.org/).

**Comment by enahum** [comment]
I'm getting this

```
> Task :react-native-gradle-plugin:compileKotlin FAILED
e: /Users/enahum/Projects/go/src/github.com/mattermost/react-native-turbo-log/example/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/tasks/BundleHermesCTask.kt: (137, 11): This declaration is experimental and its usage must be marked with '@kotlin.ExperimentalStdlibApi' or '@OptIn(kotlin.ExperimentalStdlibApi::class)'
```

related?

**Comment by kelset** [comment]
@enahum no, not as far as we know. That seems to be a different problem. This one is only about the maven artifacts not being there.

**Comment by kelset** [comment]
quick update from the Sonatype team:
> I don't think there's anything wrong on your end. We are currently running some other sync jobs on oss.sonatype.org that have resulted in artifacts from earlier today taking longer to sync. We don't believe that there is any widespread or permanent degradation in sync performance, but we also don't have a good ETA on when things will be back on their normal schedule.

soooo yeah it's literally that we have to wait for things to fix themselves 😓

**Comment by kelset** [comment]
aaaand ofc not even 5 mins later the [artifacts actually appear](https://repo1.maven.org/maven2/com/facebook/react/hermes-android/0.71.1/) and everything is back to normal 🤣

Just did a quick local test, now everything is working as expected:
<img width="1686" alt="Screenshot 2023-01-19 at 20 21 10" src="https://user-images.githubusercontent.com/16104054/213551596-8281e6a4-f3ac-493c-8567-b85396255a88.png">

sorry about this disruption folks, all good now. I'll close this one.
