### ISSUE TITLE
FAILURE: Build failed with an exception.  * What went wrong: Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'. > Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.    > Could not find com.facebook.react:react-android:0.71.1.      Required by:          project :app    > Could not find com.facebook.react:hermes-android:0.71.1. 

### ISSUE THREAD

**Issue by hamdij0maa** [facebook/react-native#35903]
Pleasse test before releasing 😭
### Description

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not find com.facebook.react:react-android:0.71.1.
     Required by:
         project :app
   > Could not find com.facebook.react:hermes-android:0.71.1.
     Required by:
         project :app
   > Could not find com.facebook.react:react-android:0.71.1.

### Version

0.71.1

### Output of `npx react-native info`

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not find com.facebook.react:react-android:0.71.1.
     Required by:
         project :app
   > Could not find com.facebook.react:hermes-android:0.71.1.
     Required by:
         project :app
   > Could not find com.facebook.react:react-android:0.71.1.

### Steps to reproduce

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not find com.facebook.react:react-android:0.71.1.
     Required by:
         project :app
   > Could not find com.facebook.react:hermes-android:0.71.1.
     Required by:
         project :app
   > Could not find com.facebook.react:react-android:0.71.1.

### Snack, code example, screenshot, or link to a repository

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not find com.facebook.react:react-android:0.71.1.
     Required by:
         project :app
   > Could not find com.facebook.react:hermes-android:0.71.1.
     Required by:
         project :app
   > Could not find com.facebook.react:react-android:0.71.1.

**Comment by kelset** [comment]
Duplicate https://github.com/facebook/react-native/issues/35904
