### ISSUE TITLE
iOS works - Android Does not 

### ISSUE THREAD

**Issue by tyhudson** [facebook/react-native#35905]
### Description

I have been working on this issue for a few days now I don't know what else to do.  

When I build a new react native app ios will work just fine but Android will not.  So, I am assuming that my environment is messed up but when I run npx react-native doctor everything is green and checks out.  I have tried this on 0.70.6 and 0.71.0. 

My old apps still work and compile on 0.67.2.  

![image](https://user-images.githubusercontent.com/118188666/213569539-4abecab2-51a4-4e32-8fd2-b77e736f7331.png)

![image](https://user-images.githubusercontent.com/118188666/213569719-687349dd-5237-492a-b493-ceefcc9c8b8e.png)

### Version

0.70.6

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 372.72 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 17.9.1 - ~/.nvm/versions/node/v17.9.1/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v17.9.1/bin/npm
    Watchman: 2022.11.28.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/tyhudson/.gem/ruby/2.7.5/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 28, 31, 33
      Build Tools: 30.0.2, 30.0.3, 31.0.0, 33.0.0, 33.0.1
      System Images: android-31 | Google APIs ARM 64 v8a, android-31 | Google Play ARM 64 v8a
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9477386
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 19.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.6 => 0.70.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

npx react-native init AnyProject

cd AnyProject

npx react-native run-android

### Snack, code example, screenshot, or link to a repository

I just started this project this week.  Android has never worked.

**Comment by Titozzz** [comment]
Have you tried adding compileSdkVersion as requested by the error message ?

**Comment by tyhudson** [comment]
Ah, I thought that it is in the build.gradle.  
![image](https://user-images.githubusercontent.com/118188666/213722990-6486e1d9-1eb1-4fc0-bd54-77816e73bb7c.png)

Why doesn't this just work out of the box just like older versions of react-native?

**Comment by cortinico** [comment]
> Ah, I thought that it is in the build.gradle.

Can you share also your `android/app/build.gradle` file?

**Comment by cortinico** [comment]
The issue is in your `android/app/build.gradle` file:

```
android {
    ndkVersion rootProject.ext.ndkVersion
-   compileSdk compileSdkVersion
+   compileSdkVersion rootProject.ext.compileSdkVersion
```


https://github.com/facebook/react-native/blob/fdd8002f1951007c85f1e5fe1b61fd16fe68f463/template/android/app/build.gradle#L132-L135
