### ISSUE TITLE
Could not resolve com.facebook.react:react-android:0.71.1

### ISSUE THREAD

**Issue by RamanDEEP225** [facebook/react-native#35909]
### Description

Could not determine the dependencies of task ':app:mergeReleaseNativeLibs'.
> Could not resolve all task dependencies for configuration ':app:releaseRuntimeClasspath'.
   > Could not find com.facebook.fresco:fresco:2.2.0.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/facebook/fresco/fresco/2.2.0/fresco-2.2.0.pom
       - https://oss.sonatype.org/content/repositories/snapshots/com/facebook/fresco/fresco/2.2.0/fresco-2.2.0.pom
        node_modules/jsc-android/dist/com/facebook/fresco/fresco/2.2.0/fresco-2.2.0.pom
       - https://dl.google.com/dl/android/maven2/com/facebook/fresco/fresco/2.2.0/fresco-2.2.0.pom
       - https://www.jitpack.io/com/facebook/fresco/fresco/2.2.0/fresco-2.2.0.pom
     Required by:
         project :app
   > Could not find com.facebook.react:react-android:0.71.0.
     Searched in the following locations:
     node_modules/react-native/android/com/facebook/react/react-android/0.71.0/react-android-0.71.0.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :app
   > Could not find com.facebook.react:hermes-android:0.71.0.
     Searched in the following locations:
    node_modules/react-native/android/com/facebook/react/hermes-android/0.71.0/hermes-android-0.71.0.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :app
   > Could not find com.facebook.react:react-android:0.71.0.
     Searched in the following locations:
  react-native/android/com/facebook/react/react-android/0.71.0/react-android-0.71.0.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :app > project :react-native-splash-screen
         project :app > project :react-native-restart
         project :app > project :@react-native-firebase_analytics
         project :app > project :@react-native-community_art
         project :app > project :@react-native-firebase_app
         project :app > project :@react-native-firebase_database
         project :app > project :@react-native-firebase_messaging
         project :app > project :@react-native-community_clipboard
         project :app > project :react-native-add-calendar-event
         project :app > project :intercom-react-native
         project :app > project :@react-native-community_toolbar-android
         project :app > project :@react-native-community_blur
         project :app > project :react-native-gesture-handler
         project :app > project :react-native-device-info
         project :app > project :react-native-background-timer
         project :app > project :lottie-react-native
         project :app > project :react-native-picker
         project :app > project :react-native-maps
         project :app > project :rn-fetch-blob
         project :app > project :react-native-permissions
         project :app > project :react-native-geolocation-service
         project :app > project :react-native-navigation
         project :app > project :@react-native-firebase_crashlytics
         project :app > project :react-native-orientation
         project :app > project :react-native-pager-view
         project :app > project :@react-native-community_async-storage
         project :app > project :react-native-keychain
         project :app > project :intercom_intercom-react-native
         project :app > project :invertase_react-native-apple-authentication
         project :app > project :react-native-community_art
         project :app > project :react-native-community_async-storage
         project :app > project :react-native-community_blur
         project :app > project :react-native-community_cameraroll
         project :app > project :react-native-community_checkbox
         project :app > project :react-native-community_clipboard
         project :app > project :react-native-community_datetimepicker
         project :app > project :react-native-community_netinfo
         project :app > project :react-native-community_picker
         project :app > project :react-native-community_toolbar-android
         project :app > project :react-native-firebase_analytics
         project :app > project :react-native-firebase_app
         project :app > project :react-native-firebase_crashlytics
         project :app > project :react-native-firebase_database
         project :app > project :react-native-firebase_dynamic-links
         project :app > project :react-native-firebase_messaging
         project :app > project :react-native-google-signin_google-signin
         project :app > project :bugsnag-react-native
         project :app > project :react-native-device-country
         project :app > project :react-native-fast-image
         project :app > project :react-native-fs
         project :app > project :react-native-image-crop-picker
         project :app > project :react-native-inappbrowser-reborn
         project :app > project :react-native-linear-gradient
         project :app > project :react-native-localization
         project :app > project :react-native-month-year-picker
         project :app > project :react-native-snackbar
         project :app > project :react-native-spinkit
         project :app > project :react-native-vector-icons
         project :app > project :react-native-video
         project :app > project :react-native-webview
         project :app > project :rn-sms-retriever
   > Could not find com.eightbitlab:blurview:1.6.3.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/eightbitlab/blurview/1.6.3/blurview-1.6.3.pom
       - https://oss.sonatype.org/content/repositories/snapshots/com/eightbitlab/blurview/1.6.3/blurview-1.6.3.pom
       - /node_modules/jsc-android/dist/com/eightbitlab/blurview/1.6.3/blurview-1.6.3.pom
       - https://dl.google.com/dl/android/maven2/com/eightbitlab/blurview/1.6.3/blurview-1.6.3.pom
       - https://www.jitpack.io/com/eightbitlab/blurview/1.6.3/blurview-1.6.3.pom
     Required by:
         project :app > project :@react-native-community_blur
         project :app > project :react-native-community_blur
   > Could not find com.facebook.react:react-android:0.71.0.
     Searched in the following locations:
       - node_modules/react-native/android/com/facebook/react/react-android/0.71.0/react-android-0.71.0.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :app > project :react-native-mmkv

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

### Version

0.71.0

### Output of `npx react-native info`

After running npx react-native upgrade I got conflicts in the below files so I made manually changes in the below files according to this link
https://react-native-community.github.io/upgrade-helper/?from=0.70.5&to=0.71.0

 - .flowconfig 
 - .gitignore 
 - android/app/build.gradle
 - android/app/src/main/AndroidManifest.xml
 - android/app/src/main/java/com/app-name/MainActivity.java
 - android/app/src/main/java/com/app-name/MainApplication.java 
 - android/build.gradle 
 - android/gradle.properties
 - android/settings.gradle 
 - ios/Podfile

### Steps to reproduce

After upgrading the react-native project from 0.70.5 to 0.71.0 I'm receiving these errors.  

### Snack, code example, screenshot, or link to a repository

thanks

**Comment by cortinico** [comment]
> * android/app/build.gradle
> * android/build.gradle
> * android/gradle.properties
> * android/settings.gradle

Can you share the content of those 4 files?

**Comment by RamanDEEP225** [comment]
-  android/app/build.gradle

apply plugin: "com.android.application"
apply plugin: "com.facebook.react"
import com.android.build.OutputFile

/* * This is the configuration block to customize your React Native Android app.
 * By default you don't need to apply any configuration, just uncomment the lines you need.
 */

react {
    /* Folders */
    //   The root of your project, i.e. where "package.json" lives. Default is '..'
    // root = file("../")
    //   The folder where the react-native NPM package is. Default is ../node_modules/react-native
    // reactNativeDir = file("../node_modules/react-native")
    //   The folder where the react-native Codegen package is. Default is ../node_modules/react-native-codegen
    // codegenDir = file("../node_modules/react-native-codegen")
    //   The cli.js file which is the React Native CLI entrypoint. Default is ../node_modules/react-native/cli.js
    // cliFile = file("../node_modules/react-native/cli.js")
    /* Variants */
    //   The list of variants to that are debuggable. For those we're going to
    //   skip the bundling of the JS bundle and the assets. By default is just 'debug'.
    //   If you add flavors like lite, prod, etc. you'll have to list your debuggableVariants.
    // debuggableVariants = ["liteDebug", "prodDebug"]
    /* Bundling */
    //   A list containing the node command and its flags. Default is just 'node'.
    // nodeExecutableAndArgs = ["node"]
    //
    //   The command to run when bundling. By default is 'bundle'
    // bundleCommand = "ram-bundle"
    //
    //   The path to the CLI configuration file. Default is empty.
    // bundleConfig = file(../rn-cli.config.js)
    //
    //   The name of the generated asset file containing your JS bundle
    // bundleAssetName = "MyApplication.android.bundle"
    //
    //   The entry file for bundle generation. Default is 'index.android.js' or 'index.js'
    // entryFile = file("../js/MyApplication.android.js")
    //
    //   A list of extra flags to pass to the 'bundle' commands.
    //   See https://github.com/react-native-community/cli/blob/main/docs/commands.md#bundle
    // extraPackagerArgs = []
    /* Hermes Commands */
    //   The hermes compiler command to run. By default it is 'hermesc'
    // hermesCommand = "$rootDir/my-custom-hermesc/bin/hermesc"
    //
    //   The list of flags to pass to the Hermes compiler. By default is "-O", "-output-source-map"
    // hermesFlags = ["-O", "-output-source-map"]
}
/**

/**
 * Set this to true to create four separate APKs instead of one,
 * one for each native architecture. This is useful if you don't
 * use App Bundles (https://developer.android.com/guide/app-bundle/)
 * and want to have separate APKs to upload to the Play Store.
 */
def enableSeparateBuildPerCPUArchitecture = false

/**
 * Set this to true to Run Proguard on Release builds to minify the Java bytecode.
 */
def enableProguardInReleaseBuilds = false

/**
 * The preferred build flavor of JavaScriptCore.
 *
 * For example, to use the international variant, you can use:
 * `def jscFlavor = 'org.webkit:android-jsc-intl:+'`
 *
 * The international variant includes ICU i18n library and necessary data
 * allowing to use e.g. `Date.toLocaleString` and `String.localeCompare` that
 * give correct results when using with locales other than en-US.  Note that
 * this variant is about 6MiB larger per architecture than default.
 */
def jscFlavor = 'org.webkit:android-jsc:+'

/**
 * Whether to enable the Hermes VM.
 *
 * This should be set on project.ext.react and mirrored here.  If it is not set
 * on project.ext.react, JavaScript will not be compiled to Hermes Bytecode
 * and the benefits of using Hermes will therefore be sharply reduced.
 */
//def enableHermes = project.ext.react.get("enableHermes", false);

android {
    compileSdkVersion rootProject.ext.compileSdkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    namespace "package name"
    defaultConfig {
        applicationId "package name"
        minSdkVersion 23
        missingDimensionStrategy "RNN.reactNativeVersion", "reactNative68"
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 81
        versionName "2.65"
        multiDexEnabled true
        aaptOptions { cruncherEnabled = false }
        ndk {
            abiFilters "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
        }
        dexOptions {
            javaMaxHeapSize "8g"
        }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
        }
    }
    signingConfigs {
        release {
            if (project.hasProperty('MYAPP_RELEASE_STORE_FILE')) {
                storeFile file(MYAPP_RELEASE_STORE_FILE)
                storePassword MYAPP_RELEASE_STORE_PASSWORD
                keyAlias MYAPP_RELEASE_KEY_ALIAS
                keyPassword MYAPP_RELEASE_KEY_PASSWORD
            }
        }
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            // Caution! In production, you need to generate your own keystore file.
            // see https://facebook.github.io/react-native/docs/signed-apk-android.
            signingConfig signingConfigs.release
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // https://developer.android.com/studio/build/configure-apk-splits.html
            def versionCodes = ["armeabi-v7a": 1, "x86": 2, "arm64-v8a": 3, "x86_64": 4]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }

        }
    }
}

dependencies {
    implementation "androidx.core:core-splashscreen:1.0.0"
    implementation project(':react-native-splash-screen')
    implementation("com.squareup.okhttp3:okhttp-urlconnection:4.9.1")
    implementation project(':react-native-restart')
    implementation 'com.google.firebase:firebase-dynamic-links:11.0.4'
    implementation project(path: ":@react-native-firebase_analytics")
    implementation 'com.google.code.gson:gson:2.8.6'
    implementation project(path: ":@react-native-community_art")
    implementation project(path: ":@react-native-firebase_app")
    implementation project(path: ":@react-native-firebase_database")
    implementation project(path: ":@react-native-firebase_messaging")
    implementation project(path: ":@react-native-community_clipboard")
    implementation project(':react-native-add-calendar-event')
    implementation 'io.intercom.android:intercom-sdk-base:7.2.0'
    implementation 'io.intercom.android:intercom-sdk-fcm:5.5.1'
    implementation project(':intercom-react-native')
    implementation project(':@react-native-community_toolbar-android')
    implementation project(':@react-native-community_blur')
    implementation project(':react-native-gesture-handler')
    implementation project(':react-native-device-info')
    implementation project(':react-native-background-timer')
    implementation project(':lottie-react-native')
    implementation 'com.facebook.fresco:fresco:2.2.0'
    implementation 'com.facebook.fresco:animated-gif:2.0.0'
    implementation 'com.facebook.fresco:animated-base-support:0.14.1'
    implementation project(':react-native-picker')
    implementation project(':react-native-maps')
    implementation project(':rn-fetch-blob')
    implementation project(':react-native-permissions')
    implementation(project(':react-native-geolocation-service')) {
        exclude group: 'com.google.android.gms', module: 'play-services-location'
    }
    implementation("com.facebook.react:react-android")
    implementation project(':react-native-navigation')
    implementation project(path: ":@react-native-firebase_crashlytics")
    // Firebase dependencies
    implementation "com.google.android.gms:play-services-base:17.6.0"
    implementation "com.google.firebase:firebase-core:18.0.2"
    implementation "com.google.firebase:firebase-messaging:21.0.1"
    implementation 'me.leolin:ShortcutBadger:1.1.22@aar'
    implementation "com.google.firebase:firebase-database:19.6.0"
    implementation "com.google.android.gms:play-services-location:17.1.0"
    implementation 'androidx.multidex:multidex:2.0.1'

    implementation project(':react-native-orientation')
    implementation project(':react-native-pager-view')
    implementation project(path: ':@react-native-community_async-storage')

    implementation("androidx.swiperefreshlayout:swiperefreshlayout:1.0.0")
    debugImplementation("com.facebook.flipper:flipper:${FLIPPER_VERSION}")
    implementation project(':react-native-keychain')
    
    debugImplementation("com.facebook.flipper:flipper-network-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.squareup.okhttp3', module:'okhttp'
    }

    debugImplementation("com.facebook.flipper:flipper-fresco-plugin:${FLIPPER_VERSION}")
    if (hermesEnabled.toBoolean()) {
        implementation("com.facebook.react:hermes-android")
    } else {
        implementation jscFlavor
    }
}

apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.crashlytics'



android/build.gradle

// Top-level build file where you can add configuration options common to all sub-projects/modules.
def googlePlayServicesVersion = '16.0.0'
def REACT_NATIVE_VERSION = new File(['node', '--print',"JSON.parse(require('fs').readFileSync(require.resolve('react-native/package.json'), 'utf-8')).version"].execute(null, rootDir).text.trim())

buildscript {
    ext {
        RNNKotlinVersion = "1.3.61"
        buildToolsVersion = "33.0.0"
        minSdkVersion = 22
        compileSdkVersion = 33
        targetSdkVersion = 33
        androidXCore = "1.0.2"
        supportLibVersion = "29.0.0"
        androidXAnnotation = "1.1.0"
        androidXBrowser = "1.0.0"
        ndkVersion = "23.1.7779620"
    }
    repositories {
        google()
        mavenLocal()
        mavenCentral()
        jcenter()

    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.20"
        classpath('com.android.tools.build:gradle:7.3.1')
        classpath("com.facebook.react:react-native-gradle-plugin")
        classpath 'com.google.gms:google-services:4.3.4'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.3.0'
    
    }
}


subprojects { subproject ->
    afterEvaluate {
        if ((subproject.plugins.hasPlugin('android') || subproject.plugins.hasPlugin('android-library'))) {
            android {
                variantFilter { variant ->
                    def names = variant.flavors*.name
                    if (names.contains("reactNative51") || names.contains("reactNative55")||names.contains("reactNative56")||names.contains("reactNative57")||names.contains("reactNative57_5")||names.contains("reactNative57WixFork")||names.contains("ReactNative57Wix")) {
                        setIgnore(true)
                    }
                }
            }
        }
        if (subproject.hasProperty("android")) {
            android {
                compileSdkVersion 33
                buildToolsVersion "28.0.3"
                lintOptions {
                    checkReleaseBuilds false
                    // Or, if you prefer, you can continue to check for errors in release builds,
                    // but continue the build even when errors are found:
                    abortOnError false
                }
            }
        }
    }
}

android/gradle.properties

FLIPPER_VERSION=0.54.0
android.useAndroidX=true
android.enableJetifier=true
org.gradle.jvmargs=-Xms128m -Xmx1024m -XX:+CMSClassUnloadingEnabled
# Use this property to enable or disable the Hermes JS engine.
# If set to false, you will be using JSC instead.
hermesEnabled= true



android/settings.gradle

distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-7.5.1-all.zip

Here you go,
@cortinico thanks for your reply, i now i upgraded react-native version from 0.70.5 to 0.71.1 as per below link but still getting issue related to "com.facebook.react:react-android:0.71.1 "
https://github.com/facebook/react-native/issues/35828

This is the error, i'm getting in android studio
Null extracted folder for artifact: ResolvedArtifact(componentIdentifier=com.facebook.react:react-android:0.71.1, variant=com.facebook.react:react-android:0.71.1 variant releaseVariantDefaultApiPublication, variantName=null, artifactFile = gradle/caches/modules-2/files-2.1/com.facebook.react/react-android/0.71.1/7a8f48d7355d9d0174cd88a99ddeb0576b714564/react-android-0.71.1-release.aar, isTestFixturesArtifact=false, extractedFolder=null, publishedLintJar=null, dependencyType=ANDROID, isWrappedModule=false, buildMapping={__current_build__=/Users/skycap/Documents/Expin/android, react-native-gradle-plugin=/node_modules/react-native-gradle-plugin})

**Comment by iBotPeaches** [comment]
@RamanDEEP225 - If you use the triple tick (```) - it would be much easier to parse those files you posted.

Take this example of `android/settings.gradle`

```
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https://services.gradle.org/distributions/gradle-7.5.1-all.zip
```

**Comment by RamanDEEP225** [comment]
@iBotPeaches I updated files with triple tick, can you please check now.
I tried deleting the node modules folder, still not working.
https://github.com/facebook/react-native/issues/35900#issuecomment-1398696462

**Comment by birdofpreyru** [comment]
Hey @cortinico , I am facing the same issue trying to upgrade to RN@0.71.0 or RN@0.71.1. To reproduce, just try to init a new RN library using https://github.com/callstack/react-native-builder-bob, _i.e._
```shell
$ npx create-react-native-library@latest react-native-awesome-module
```
Select type _Turbo module with backward compat_. After initialization do `npm install`; then go into `android` folder, it does not have `gradlew`, so I just copied it in from another project, which I am actually trying to upgrade, alongside with `gradle/wrapper/gradle-wrapper.jar` and `gradle/wrapper/gradle-wrapper.properties`. Now, if I do `./gradlew lint` I this resolution error, the same as in my actual project:
```shell
Could not find com.facebook.react:react-native
```
I tried to change build.gradle to have `implementation "com.facebook.react:react-android"`, then getting
```shell
Could not find com.facebook.react:react-android
```

And with RN@0.70.x I had no problem running gradle lint and build on my project.

**Comment by RamanDEEP225** [comment]
@cortinico, after removing implementation project(':...') lines 
```
dependencies {
    implementation "androidx.core:core-splashscreen:1.0.0"
    implementation("com.squareup.okhttp3:okhttp-urlconnection:4.9.1")
    implementation 'com.google.firebase:firebase-dynamic-links:11.0.4'
    implementation 'com.google.code.gson:gson:2.8.6'
    implementation 'io.intercom.android:intercom-sdk-base:7.2.0'
    implementation 'io.intercom.android:intercom-sdk-fcm:5.5.1'
    implementation 'com.facebook.fresco:fresco:2.2.0'
    implementation 'com.facebook.fresco:animated-gif:2.0.0'
    implementation 'com.facebook.fresco:animated-base-support:0.14.1'
    implementation("com.facebook.react:react-android")

    // Firebase dependencies
    implementation "com.google.android.gms:play-services-base:17.6.0"
    implementation "com.google.firebase:firebase-core:18.0.2"
    implementation "com.google.firebase:firebase-messaging:21.0.1"
    implementation 'me.leolin:ShortcutBadger:1.1.22@aar'
    implementation "com.google.firebase:firebase-database:19.6.0"
    implementation "com.google.android.gms:play-services-location:17.1.0"
    implementation 'androidx.multidex:multidex:2.0.1'
    implementation("androidx.swiperefreshlayout:swiperefreshlayout:1.0.0")
    implementation(project(':react-native-geolocation-service')) {
        exclude group: 'com.google.android.gms', module: 'play-services-location'
    }
    debugImplementation("com.facebook.flipper:flipper:${FLIPPER_VERSION}")
    debugImplementation("com.facebook.flipper:flipper-network-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.squareup.okhttp3', module:'okhttp'
    }
   debugImplementation("com.facebook.flipper:flipper-fresco-plugin:${FLIPPER_VERSION}")
    if (hermesEnabled.toBoolean()) {
        implementation("com.facebook.react:hermes-android")
    } else {
        implementation jscFlavor
    }
}
```
but facing the same issue. Can you please suggest any other solution?

**Comment by cortinico** [comment]
> but facing the same issue. Can you please suggest any other solution?

Nope at this point we need a reproducer (i.e. a Github repo we can close and reproduce your error locally).

**Comment by birdofpreyru** [comment]
@cortinico Have you seen my message just above, I bump into this error if just run gradle lint on the standard template for library. Doesn't it count as a repro?

**Comment by jorgerojas26** [comment]
I'm having the exact same error
