### ISSUE TITLE
Issue with ViewPropTypes, the deprecated import and stuff. Both iOS and Android apps are crashing in production.

### ISSUE THREAD

**Issue by st3fus** [facebook/react-native#35914]
### Description

So basically, We had to update our app for new EAS Build on Expo, which meant upgrading Expo SDK to 46.0.0

I managed to do that and after many trials and errors, the build finally passed on Expo. But here's the catch, both iOS and Android apps are crashing in production, straight on startup. You click to open the app and boom, it crashes. 

Note: App works fine locally on emulators and tested on a real device with Expo Go. Works like charm there.

I can provide you with crashlogs.crash reports and other stuff you'd need to help me identify the issue. I'm blocked by NDA to share the whole app here, but if you need something, I can ask rest of my team is it okay to share it and I will do so.

Android crash stack trace:
https://paste.pics/1e3297c8b382d597f2d34b8b4b003f18

I can provide other crashlogs at request. Thanks in advance

### Version

0.69.5

### Output of `npx react-native info`

`System:
    OS: Linux 6.0 Pop!_OS 22.04 LTS
    CPU: (8) x64 Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz
    Memory: 10.36 GB / 15.59 GB
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.18.0/bin/yarn
    npm: 9.3.1 - ~/.nvm/versions/node/v16.18.0/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: AI-213.7172.25.2113.9123335
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: ^0.69.5 => 0.69.7 
  npmGlobalPackages:
    *react-native*: Not Found
info React Native v0.71.1 is now available (your project is running on v0.69.7).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.71.1.
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.69.7.
info To upgrade, run "react-native upgrade"`

### Steps to reproduce

Live app, can't share it's code.

### Snack, code example, screenshot, or link to a repository

I can provide what's necessary if you point me to a part of code you'd like to see. The app is live and NDA is not allowing me to share it.

**Comment by cortinico** [comment]
We can't really help without:
1. The stacktrace of the crash
2. A minimal reproducer

Plus you should consider opening this issue against the Expo repo:
https://github.com/expo/expo/issues
as they can help you further over there

**Comment by st3fus** [comment]
Solved it with a resolver library. Thanks, you can close this

**Comment by Praveen-CP** [comment]
> Solved it with a resolver library. Thanks, you can close this

can you please share how do you solve this issue.

**Comment by st3fus** [comment]
> > Solved it with a resolver library. Thanks, you can close this
> 
> can you please share how do you solve this issue.

```
plugins: [
			"@babel/plugin-proposal-export-namespace-from",
			"react-native-reanimated/plugin",
			[
				"module-resolver",
				{
					root: ["."],
					resolvePath(sourcePath, currentFile, opts) {
						if (
							sourcePath === "react-native" &&
							!(
								(
									currentFile.includes("node_modules/react-native/") || // macos/linux paths
									currentFile.includes("node_modules\\react-native\\")
								) // windows path
							) &&
							!(currentFile.includes("resolver/react-native/") || currentFile.includes("resolver\\react-native\\"))
						) {
							return path.resolve(__dirname, "resolver/react-native")
						}
						/**
						 * The `opts` argument is the options object that is passed through the Babel config.
						 * opts = {
						 *   extensions: [".js"],
						 *   resolvePath: ...,
						 * }
						 */
						return undefined
					},
				},
			],
		],
```

Pasted this in babel.config.js

And installed these two libraries:
```
"@babel/plugin-proposal-export-namespace-from": "^7.18.9",
"deprecated-react-native-prop-types": "^4.0.0",
```

Found it somewhere on GitHub in issues, can't remember exactly where. If this doesn't fix your issue, I'll dig the solution out. Cheers!

**Comment by Praveen-CP** [comment]
> > > Solved it with a resolver library. Thanks, you can close this
> > 
> > 
> > can you please share how do you solve this issue.
> 
> ```
> plugins: [
> 			"@babel/plugin-proposal-export-namespace-from",
> 			"react-native-reanimated/plugin",
> 			[
> 				"module-resolver",
> 				{
> 					root: ["."],
> 					resolvePath(sourcePath, currentFile, opts) {
> 						if (
> 							sourcePath === "react-native" &&
> 							!(
> 								(
> 									currentFile.includes("node_modules/react-native/") || // macos/linux paths
> 									currentFile.includes("node_modules\\react-native\\")
> 								) // windows path
> 							) &&
> 							!(currentFile.includes("resolver/react-native/") || currentFile.includes("resolver\\react-native\\"))
> 						) {
> 							return path.resolve(__dirname, "resolver/react-native")
> 						}
> 						/**
> 						 * The `opts` argument is the options object that is passed through the Babel config.
> 						 * opts = {
> 						 *   extensions: [".js"],
> 						 *   resolvePath: ...,
> 						 * }
> 						 */
> 						return undefined
> 					},
> 				},
> 			],
> 		],
> ```
> 
> Pasted this in babel.config.js
> 
> And installed these two libraries:
> 
> ```
> "@babel/plugin-proposal-export-namespace-from": "^7.18.9",
> "deprecated-react-native-prop-types": "^4.0.0",
> ```
> 
> Found it somewhere on GitHub in issues, can't remember exactly where. If this doesn't fix your issue, I'll dig the solution out. Cheers!

Still the same anything else needs to be added here?

**Comment by st3fus** [comment]
> > > > Solved it with a resolver library. Thanks, you can close this
> > > 
> > > 
> > > can you please share how do you solve this issue.
> > 
> > 
> > ```
> > plugins: [
> > 			"@babel/plugin-proposal-export-namespace-from",
> > 			"react-native-reanimated/plugin",
> > 			[
> > 				"module-resolver",
> > 				{
> > 					root: ["."],
> > 					resolvePath(sourcePath, currentFile, opts) {
> > 						if (
> > 							sourcePath === "react-native" &&
> > 							!(
> > 								(
> > 									currentFile.includes("node_modules/react-native/") || // macos/linux paths
> > 									currentFile.includes("node_modules\\react-native\\")
> > 								) // windows path
> > 							) &&
> > 							!(currentFile.includes("resolver/react-native/") || currentFile.includes("resolver\\react-native\\"))
> > 						) {
> > 							return path.resolve(__dirname, "resolver/react-native")
> > 						}
> > 						/**
> > 						 * The `opts` argument is the options object that is passed through the Babel config.
> > 						 * opts = {
> > 						 *   extensions: [".js"],
> > 						 *   resolvePath: ...,
> > 						 * }
> > 						 */
> > 						return undefined
> > 					},
> > 				},
> > 			],
> > 		],
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Pasted this in babel.config.js
> > And installed these two libraries:
> > ```
> > "@babel/plugin-proposal-export-namespace-from": "^7.18.9",
> > "deprecated-react-native-prop-types": "^4.0.0",
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Found it somewhere on GitHub in issues, can't remember exactly where. If this doesn't fix your issue, I'll dig the solution out. Cheers!
> 
> Still the same anything else needs to be added here?

Woops, my bad. I forgot that you need another file. In the meantime, I found the repo which's instructions I've followed. 

Here's the link, you have it step by step
https://github.com/psycheangel/deprecated-with-module-resolver
