### ISSUE TITLE
how to release ios app when there is no xcworkspace folder under ios for react native 0.71

### ISSUE THREAD

**Issue by xiongemi** [facebook/react-native#35916]
### Description

i generate an empty workspace with react native 0.71.1, i noticed there is no longer an xcworkspace folder under ios.
based on the template folder https://github.com/facebook/react-native/tree/main/template/ios, it is no longer generated. i notice it is under the xcodeproj.

however, for the docs https://reactnative.dev/docs/publishing-to-app-store, i notice in the steps, it says
"Double click on YOUR_APP_NAME.xcworkspace. It should launch XCode."

how do i currently publish my ios app now?

### Version

0.71.1

### Output of `npx react-native info`

System:
    OS: macOS 12.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 1.01 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.13.0 - ~/.volta/tools/image/node/18.13.0/bin/node
    Yarn: 1.22.10 - ~/.volta/bin/yarn
    npm: 8.19.3 - ~/.volta/tools/image/node/18.13.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8815526
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/javac
  npmPackages:
    @react-native-community/cli: 10.1.3 => 10.1.3 
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.1 => 0.71.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

- generate a new workspace with `npx react-native init`
- try to publish the ios app

### Snack, code example, screenshot, or link to a repository

<img width="295" alt="Screen Shot 2023-01-20 at 5 14 55 PM" src="https://user-images.githubusercontent.com/16211801/213814792-f68f642e-406d-455e-8d9e-264f942b5dd6.png">

**Comment by ChadyAyoub4** [comment]
Any updates on this? I am trying to upgrade React native project and in the diff it says to delete the file .xcshareddata. however if i delete it i am unable to run the app from xcodeproj
