### ISSUE TITLE
Animation paused when app in background

### ISSUE THREAD

**Issue by andreav** [facebook/react-native#35918]
### Description

I have a react native animation built with Animated.sequence

If I put my App in background during the animation (i.e. on Android the user presses home button) the animation stops when current Animated.timing is terminated. The animation restarts when the app comes back in foreground.

The animation should continue to run even while the application is in the background.

### Version

0.70.6

### Output of `npx react-native info`

```
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz       
    Memory: 4.41 GB / 19.88 GB
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: AI-212.5712.43.2112.8609683
    Visual Studio: 17.0.32112.339 (Visual Studio Community 2022)
  Languages:
    Java: 18.0.2 - /c/Program Files/OpenJDK/jdk-18.0.2/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.6 => 0.70.6
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

Please run this component attached to the issue and put the app in background before the first Animation.timing has completed.
Wait some seconds so that the animation should have finished.
If you put the app again in foreground, you will see the animation instead restarting from the second Animated.timing.

### Snack, code example, screenshot, or link to a repository

```
import {Animated, StyleSheet} from 'react-native';
import React, {useEffect, useRef} from 'react';
import MaterialCommIcons from 'react-native-vector-icons/MaterialCommunityIcons';

const AnimationExample = () => {
  const scaleAniVal = useRef(new Animated.Value(1)).current;

  useEffect(() => {
    const animationLoopScale = Animated.sequence([
      Animated.timing(scaleAniVal, {
        toValue: 0,
        duration: 3 * 1000,
        useNativeDriver: false,
      }),
      Animated.timing(scaleAniVal, {
        toValue: 1,
        duration: 3 * 1000,
        useNativeDriver: false,
      }),
    ]);
    animationLoopScale.start();
  }, []);

  return (
    <Animated.View
      style={[
        {
          transform: [
            {
              translateX: scaleAniVal.interpolate({
                inputRange: [0, 1],
                outputRange: [250, 0],
              }),
            },
          ],
        },
      ]}>
      <MaterialCommIcons name="react" style={styles.icon} />
    </Animated.View>
  );
};

export default AnimationExample;

const styles = StyleSheet.create({
  icon: {
    fontSize: 30,
    color: 'red',
  },
});

```

**Comment by sajid7053** [comment]
Please refer to the below link once.

https://github.com/lottie-react-native/lottie-react-native/issues/412

**Comment by andreav** [comment]
Thank you @sajid7053, but I think my problem is a bit different because when the app comes in foreground, the animation correctly restarts.
My problem is about the restart point.

As far as I can see, the animation restarts from the first animation following the one that was playing when the app was in background, no matter how long I wait.
In my opinion, it should restart from the "correct" point in time.

For example, suppose this:
- both animation A and B last 5 seconds.
- I start animation A and immedeately put the app in background
- I wait 10 secs and put the app again in foreground
- Then there is no more animations to play (after 10 seconds both animations are finished)
- Instead I see the animation B starting to play

In this example instead:
- I start animation A and immedeately put the app in background
- I wait 7 secs and put the app again in foreground
- I would like to see the animation B running for its 3 remaining seconds
- Instead I see the animation B starting to play from its starting position

If this is not possible, the only solution I can see is to keep track of the elapsed time between the background and foreground events.
Then, when the app comes to foreground I have calculate and set the right "animated values" before the animation starts again.
But this seems quite complicated.

**Comment by sajid7053** [comment]
Yes @andreav, The approach you are suggesting is complicated and if we try to achieve this based on background and foreground state then it may affect the application performance also.

**Comment by zereight** [comment]
same issue
