### ISSUE TITLE
React Native "TypeError: Network request failed" on Fetch

### ISSUE THREAD

**Issue by FengZi-lv** [facebook/react-native#35911]
### Description

# Problem description

React Native throws an error when I try to use the fetch request

When I continue to use this request without headers, React Native does not throw an error

And errors occur in Android emulators and Android phones

Error log:
```
TypeError: Network request failed
```

![image](https://user-images.githubusercontent.com/59948673/213712969-705b8636-71c6-4549-a94c-823c75afdec4.png)

# Try

I tried the following methods, but it still doesn't work

- [Github Issues #610053724](https://github.com/facebook/react-native/issues/28551#issuecomment-610053724)
- [Github Issues #610652110](https://github.com/facebook/react-native/issues/28551#issuecomment-610652110)
- [Github Issues #611085378](https://github.com/facebook/react-native/issues/28551#issuecomment-611085378)

What can I do? Thanks.

### Version

0.70.6

### Output of `npx react-native info`

System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
    Memory: 1.62 GB / 15.97 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.24.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: AI-213.7172.25.2113.9123335
    Visual Studio: Not Found
  Languages:
    Java: 11.0.17
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.6 => 0.70.6
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

The following is the code for reporting errors, and you can use these codes to reproduce errors.

```js
let header = {
			Cookie: 'account_id_v2=xxxx; account_mid_v2=0xpvondsl7_mhy; cookie_token_v2=xxxxxxxx; ltmid_v2=xxxxx; ltoken_v2=xxxxxxxxxxx-xxxxxxxxx-xxx; ltuid_v2=xxxx; aliyungf_tc=xxxxxxxxxxx',
			DS: '1674207860,753043,e07214c71a00375565a2cc6714e9a27b',
			Referer: 'https://webstatic.mihoyo.com',
			'User-Agent':
				'Mozilla/5.0 (Linux; Android 12; 61249) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.73 Mobile Safari/537.36 miHoYoBBS/2.37.1',
			'x-rpc-app_version': '2.37.1',
			'x-rpc-client_type': 5,
		}


fetch(
			'https://api-takumi.mihoyo.com/game_record/app/genshin/api/index',
			{
				method: 'POST',
				body: '{"role_id":"208574599","server":"cn_gf01"}',
                // No error will be reported when header is not set
				headers:header,
			},
		)
			.then(response => {
				return response.text();
			})
			.then(data => {
				console.log(data);
				CallBack(data);
			})
			.catch(error => {
				console.log(error);
			});
```

### Snack, code example, screenshot, or link to a repository

[skip]

**Comment by mym0404** [comment]
1. Check your emulator is connected with network with in app webview or browser.
2. Check `AndroidManifest.xml` `INTERNET` permission

**Comment by Kontsedal** [comment]
Have a similar issue, sometimes I'm starting to get network errors even though internet is working. Only app reinstall helps.
