### ISSUE TITLE
[local-cli] Unable to resolve module image! ... from ...

### ISSUE THREAD

**Issue by timzaak** [facebook/react-native#3592]
Buid with the master branch, and run `node ./node_modules/react-native/local-cli/cli.js start`
all the images in Android can not be resolved. I dont know if it is ok for IOS.

**Comment by timzaak** [comment]
and can not run the UIExplore Example

**Comment by volkrass** [comment]
Same issue here on iOS. Tested with Examples/UIExplorer

**Comment by fangmobile** [comment]
ditto.
![screen shot 2015-10-22 at 1 58 58 pm](https://cloud.githubusercontent.com/assets/3377899/10678102/1153c60a-78c5-11e5-80e5-6970bd0a810b.png)

**Comment by fangmobile** [comment]
same here.
![screen shot 2015-10-22 at 1 58 58 pm](https://cloud.githubusercontent.com/assets/3377899/10678179/8d460ffc-78c5-11e5-9bf0-cf3994b44ca1.png)

**Comment by negativetwelve** [comment]
Looks like the asset system was updated. https://github.com/facebook/react-native/pull/3545 I'm updating our app right now, will report back to see if that is the issue.

**Comment by timzaak** [comment]
thanks for @negativetwelve.
I build successfully as #3545 mentioned.

**Comment by timzaak** [comment]
how could I require gif image?
require('./xxx.png') can get the png image correctly!
require('./xxx.gif') or {uri:'./xxx.gif'} could not get the gif image.

**Comment by martinbigio** [comment]
`require('./xxx.gif')` should work. @frantic is this a kp?

**Comment by aj9045** [comment]
Sorry, I'm a tad confused.  I'm trying to run the UIExplorer on Android--what should I be changing to make it work?

**Comment by martinbigio** [comment]
This is a legimit bug. I submitted a pull request to fix it: https://github.com/facebook/react-native/pull/3640 :)

**Comment by bibodeng** [comment]
fangmobile is right, but how to fix it

**Comment by onpaws** [comment]
I upgrade my RN project to latest (0.42) and having same issue as @fangmobile. Anyone have insights on this?
