### ISSUE TITLE
Error: Naming collision detected

### ISSUE THREAD

**Issue by awesomepankaj** [facebook/react-native#3594]
when I start development server using this command:
react-native start

then I am getting error this:
Error building DepdendencyGraph:
 Error: Naming collision detected: /home/awesomepankaj/Work/lifemakerProjects/workingLifemaker/LifeMaker/node_modules/react-native/node_modules/react-tools/src/shared/vendor/core/dom/focusNode.js collides with /home/awesomepankaj/Work/lifemakerProjects/workingLifemaker/LifeMaker/node_modules/react-native-modalbox/node_modules/react-native/node_modules/react-tools/src/shared/vendor/core/dom/focusNode.js

react-native version 0.13
Ubuntu 14.04

**Comment by oblador** [comment]
Delete the extra react-native folder in `node_modules/react-native-modalbox/node_modules/`.

**Comment by awesomepankaj** [comment]
thanks
