### ISSUE TITLE
 TypeError: Cannot read properties of undefined (reading 'getItem') with RN 0.71.1

### ISSUE THREAD

**Issue by LayMui** [facebook/react-native#35948]
### New Version

0.71.1

### Old Version

0.67.1

### Build Target(s)

iOS Simulator

### Output of `react-native info`

react-native info
info Fetching system and libraries information...
(node:22495) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
System:
    OS: macOS 13.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.64 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/Library/Caches/fnm_multishells/16855_1674563217976/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.5.0 - ~/Library/Caches/fnm_multishells/16855_1674563217976/bin/npm
    Watchman: 2022.03.21.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 28, 29, 31, 32
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 31.0.0, 32.0.0, 32.1.0
      System Images: android-30 | Google Play Intel x86 Atom, android-31 | Google APIs Intel x86 Atom_64, android-31 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8309675
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.1 => 0.71.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Issue and Reproduction Steps

in package.json
```  
"ts-jest": "^28.0.5",
"babel-jest": "^29.2.1",
 "@types/jest": "^29.2.1",
"@types/react-test-renderer": "^18.0.0",
```

yarn test -u

 FAIL  screens/__tests__/UniversalLogin.test.js (12.085 s)
  Login Page With Universal Auth0 Login
    ✕ Matches snapshots (1920 ms)

  ● Login Page With Universal Auth0 Login › Matches snapshots

    TypeError: Cannot read properties of undefined (reading 'getItem')

      42 |
      43 |   test('Matches snapshots', () => {
    > 44 |     const snapshot = render(instance).toJSON();
         |                            ^
      45 |     expect(snapshot).toMatchSnapshot();
      46 |   });
      47 | });

**Comment by parnekov** [comment]
The same problem: 
<img width="501" alt="image" src="https://user-images.githubusercontent.com/29271613/220901848-48e50f31-27b1-418a-9506-e71fd543868c.png">

**Comment by professorkolik** [comment]
Same thing with Amplify.Auth, did anyone find a solution?
