### ISSUE TITLE
ERROR TypeError: Cannot read property 'createElement' of undefined, js engine: hermes 

### ISSUE THREAD

**Issue by 98rahul** [facebook/react-native#35958]
### Description

migrate to current version of RN-0.71.1
using flipper
enable hermes engine
run the app

### Version

0.71.1

### Output of `npx react-native info`

 ERROR  TypeError: Cannot read property 'createElement' of undefined, js engine: hermes
 ERROR  TypeError: Cannot read property 'createElement' of undefined, js engine: hermes
 ERROR  TypeError: Cannot read property 'createElement' of undefined, js engine: hermes
 ERROR  TypeError: Cannot read property 'createElement' of undefined, js engine: hermes

### Steps to reproduce

migrate to current version of RN-0.71.1
using flipper
enable hermes engine
run the app

this is related to --->> path: node_modules/react-devtools-core/dist/backend.js
function initialize() {
  canvas = window.document.createElement('canvas');
  canvas.style.cssText = "\n    xx-background-color: red;\n    xx-opacity: 0.5;\n    bottom: 0;\n    left: 0;\n    pointer-events: none;\n    position: fixed;\n    right: 0;\n    top: 0;\n    z-index: 1000000000;\n  ";
  var root = window.document.documentElement;
  root.insertBefore(canvas, root.firstChild);
}
[check here](https://github.com/facebook/react/issues/26042#issue-1556179961)

### Snack, code example, screenshot, or link to a repository

function initialize() {
  canvas = window.document.createElement('canvas');   // error found here 
  canvas.style.cssText = "\n    xx-background-color: red;\n    xx-opacity: 0.5;\n    bottom: 0;\n    left: 0;\n    pointer-events: none;\n    position: fixed;\n    right: 0;\n    top: 0;\n    z-index: 1000000000;\n  ";
  var root = window.document.documentElement;
  root.insertBefore(canvas, root.firstChild);
}

**Comment by iBotPeaches** [comment]
@98rahul - Take a look at these. I believe this is a known issue with workaround. Try disabling "Highlight updates when components render"

 * https://github.com/facebook/flipper/issues/4046#issuecomment-1252790246
 * https://github.com/facebook/flipper/issues/4131

**Comment by 98rahul** [comment]
@iBotPeaches i didn't find the **supportsTraceUpdates**  in order to make it comment .
can you specify the path as i go through the whole  _node_modules\react-devtools-core\dist\backend.js_ ..

**Comment by iBotPeaches** [comment]
@98rahul - Sorry mate. I just found some links to try and help you. Best of luck.

**Comment by 98rahul** [comment]
@iBotPeaches  always welcome! 
but i'm using flipper to debug the RN-app ,as mmkv does not supporting on chrome to debug bcz of sync behaviour so, i'm unaware about  how to **Highlight updates when components render** .
i was expecting some code break around [initialize ](https://github.com/facebook/react-native/issues/35958#issue-1556258460)function .

**Comment by pierrecanthelou** [comment]
Probably a duplicate of #26060 https://github.com/facebook/react/pull/26060

**Comment by koeika** [comment]
<img width="1521" alt="image" src="https://github.com/facebook/react-native/assets/53003947/a9bbf568-1cf4-4866-af3a-73ce6604559d">
ignore the error log and enter profiler , uncheck this hightlight option work for me.
