### ISSUE TITLE
[Android][RN@0.71.1] Could not find com.facebook.react:react-native

### ISSUE THREAD

**Issue by birdofpreyru** [facebook/react-native#35950]
### Description

@cortinico Essentially, I believe, I encountered the same issue with RN@0.71.0&ndash;0.71.1 as #35909 and #35945. As I mentioned in #35909 (I think you overlooked my message in the thread there), I also encounter this problem when I create a standard scaffolding for a library using 
```shell
$ npx create-react-native-library@latest react-native-awesome-module
```
With _Turbo module with backward compat_, _Java and Objective-C_; then installing NPM dependencies, copying in Gradle (thus, looking into Android build), and running `./gradlew lint` &lArr; I guess, this should do as a repro?

### Version

0.71.1

### Output of `npx react-native info`

N/A

### Steps to reproduce

N/A

### Snack, code example, screenshot, or link to a repository

N/A

**Comment by cortinico** [comment]
> I also encounter this problem when I create a standard scaffolding for a library using

So let's try to keep things separate. The problem you faced with `create-react-native-library` should be reported here:
https://github.com/callstack/react-native-builder-bob/issues

Anyway I'm going to answer here as I already have an answer for you:

> copying in Gradle (thus, looking into Android build), and running ./gradlew lint ⇐ I guess, this should do as a repro?

You're not supposed to copy `gradlew` there and you're also not supposed to run `./gradlew lint` from that folder. The reason being that inside the `./android` folder you just have a library, but not a full Gradle build (previously it was probably working for you by chance, but you're not supposed to invoke Gradle from there anyway. You're missing crucial files like `settings.gradle` and other files there).

You should be invoking `gradlew` from the `./example/android` folder instead (or generally from the app project, not from the library project). Specifically `create-react-native-library` creates for you an example app in the `./example` folder that you can use to test your library.

So to invoke lint in your case you will have to:

```
npx create-react-native-library@latest react-native-awesome-module && cd react-native-awesome-module && yarn && cd example/android && ./gradlew lint
```

(Note that this will run lint on both the app and the library module. If you want to lint only the library you'll have to `./gradlew react-native-awesome-module:lint`

**Comment by birdofpreyru** [comment]
Thanks @cortinico ! It turns out I misread the new architecture migration guide when upgrading my library to RN@0.69 and the new architecture, and when it says to configure gradle plugin for the app, I also added it to the library, and somehow it worked fine prior to RN@0.71.

**Comment by Sunbreak** [comment]
Probably duplicate of https://github.com/callstack/react-native-builder-bob/issues/361, fixed by https://github.com/callstack/react-native-builder-bob/pull/362

Try add `+` back

```diff
   // For < 0.71, this will be from the local maven repo
   // For > 0.71, this will be replaced by `com.facebook.react:react-android:$version` by react gradle plugin
   //noinspection GradleDynamicVersion
-  implementation "com.facebook.react:react-native"
+  implementation "com.facebook.react:react-native:+"
```
