### ISSUE TITLE
iOS App Crash right after active state

### ISSUE THREAD

**Issue by trilliwon** [facebook/react-native#35956]
### Description

*** Terminating app due to uncaught exception ‘NSInternalInconsistencyException’, reason: ‘ModuleRegistry must be set to properly init dimensions.’

React/CoreModules/RCTDeviceInfo.mm:106

### Version

0.68.2

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Max
    Memory: 986.00 MB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
    Yarn: 3.2.1 - ~/.nodenv/shims/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.1/bin/npm
    Watchman: 2023.01.16.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.2 => 0.68.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
info React Native v0.71.1 is now available (your project is running on v0.68.2).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.71.1.
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.68.2.
info To upgrade, run "react-native upgrade".

### Steps to reproduce

After passing certain time in background, open the app.
`UIApplicationDidBecomeActiveNotification` called and `interfaceFrameDidChange` method called.
App stops at  

#3	0x00000001059d4b28 in RCTExportedDimensions(RCTModuleRegistry*) at /Users/xxxxxxxxx/node_modules/react-native/React/CoreModules/RCTDeviceInfo.mm:106

    RCTAssert(false, @"ModuleRegistry must be set to properly init dimensions.");

### Snack, code example, screenshot, or link to a repository

.

**Comment by jonalocum** [comment]
I'm getting a lot of these. Any reason this was closed without resolution?
