### ISSUE TITLE
Local  and https images are not rendering in iOS, working fine for android using Image component

### ISSUE THREAD

**Issue by Pankaj-Intrado** [facebook/react-native#35955]
### Description

When i try to render local image or https image using react native's Image component, it doesn't render on iOS devices but works fine for android.

**Following cases dont work on iOS, works fine on android:**

`<Image
                    onError={nativeEvent => console.log(nativeEvent)}
                    source={require('@assets/icons/Avatar.png')}
                    style={{ width: 50, height: 50, borderWidth: 1 }}
                />`
OR

`<Image
                    onError={nativeEvent => console.log(nativeEvent)}
                    source={{
          uri: 'https://reactnative.dev/img/tiny_logo.png',
        }}
                    style={{ width: 50, height: 50, borderWidth: 1 }}
                />`

**onError is logging following error for iOS :**

![Screen Shot 2023-01-24 at 10 29 50 PM](https://user-images.githubusercontent.com/114941523/214473906-0211aa72-781e-4db7-ba8a-7d20207f13af.png)

**If i put uri as follows, it works for both devices:**
`<Image
                    onError={nativeEvent => console.log(nativeEvent)}
                    source={{uri: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADMAAAAzCAYAAAA6oTAqAAAAEXRFWHRTb2Z0d2FyZQBwbmdjcnVzaEB1SfMAAABQSURBVGje7dSxCQBACARB+2/ab8BEeQNhFi6WSYzYLYudDQYGBgYGBgYGBgYGBgYGBgZmcvDqYGBgmhivGQYGBgYGBgYGBgYGBgYGBgbmQw+P/eMrC5UTVAAAAABJRU5ErkJggg=='}}
                    style={{ width: 50, height: 50, borderWidth: 1 }}
                />`

### Version

0.70.3

### Output of `npx react-native info`

System:
    OS: macOS 12.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 42.40 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.3.0 - ~/.nvm/versions/node/v19.3.0/bin/node
    Yarn: 1.22.19 - ~/Documents/Reliance/comm-recipientapp/node_modules/.bin/yarn
    npm: 9.2.0 - ~/.nvm/versions/node/v19.3.0/bin/npm
    Watchman: 2022.10.10.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

`<Image
                    onError={nativeEvent => console.log(nativeEvent)}
                    source={{
          uri: 'https://reactnative.dev/img/tiny_logo.png',
        }}
                    style={{ width: 50, height: 50, borderWidth: 1 }}
                />`

### Snack, code example, screenshot, or link to a repository

`<Image
                    onError={nativeEvent => console.log(nativeEvent)}
                    source={require('@assets/icons/Avatar.png')}
                    style={{ width: 50, height: 50, borderWidth: 1 }}
                />`

iOS:
![Screen Shot 2023-01-24 at 10 30 48 PM](https://user-images.githubusercontent.com/114941523/214473988-3be7b19b-b1e5-4d55-90fe-9fc5849d6205.png)

android:
<img width="401" alt="Screen Shot 2023-01-24 at 10 33 38 PM" src="https://user-images.githubusercontent.com/114941523/214474267-230e60c3-8e7d-4d7c-9061-cbc7098f194e.png">

**Comment by Mandela17** [comment]
I am facing the same issue.

**Comment by lexNwimue** [comment]
@Mandela17 we fixed it. In our case it had something to do with bundling the assets in the metro file.
