### ISSUE TITLE
`Error while updateing property 'justifycontent' in shadow node of type: RTCView` followed by crashing on Android devices

### ISSUE THREAD

**Issue by RichardBrowning** [facebook/react-native#35966]
### Description

My app crashes on Android devices. (iOS is fine) 
 with the error `Error while updating property 'justifyContent' in shadow node of type: RTCView`

null

invalid value of justifyContent: center

The record of crashing:
![crach_report](https://user-images.githubusercontent.com/46521212/214631966-8afa940e-cef9-4073-8ac6-f8eae4cacff6.gif)

### Version

0.70.5

## My project is an expo project

info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.22621
    CPU: (6) x64 Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
    Memory: 17.63 GB / 31.83 GB
  Binaries:
    Node: 19.3.0 - ~\Documents\GitHub\paipai-master\node_modules\.bin\node.CMD
    Yarn: Not Found
    npm: 9.3.1 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: AI-221.6008.13.2211.9477386
    Visual Studio: 17.4.33213.308 (Visual Studio Community 2022)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.5 => 0.70.5
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found 

### Steps to reproduce

my app has a navigation structure that looks like this:

rootnavigator
|                       
| -- tabnavigator -- ...
|                       
| - loginScreen
...

upon login is verified, the app will navigate to a default routine in tabnavigator, during which process the crash is observed.

### Snack, code example, screenshot, or link to a repository

```javascript
/** This is a business application, I cannot share the repository and I do not know which part is causing the problem.
If there is any part you think will be helpful, please ask me. I will provide anything possible */
```

**Comment by samon11** [comment]
Experiencing same exact behavior on android after user goes through our onboarding/login stack except I get this error
`Error while updating property 'position' in shadow node of type: RCTText`

I am on `"react-native": "0.71.1"`
