### ISSUE TITLE
[iOS] [TextInput] Chinese font changes on focus

### ISSUE THREAD

**Issue by seph14** [facebook/react-native#3596]
So if you create a new text input, type in some chinese/japanese (or more languages?) characters, once the text input is on focus, the font seems to have changed.

**Comment by mkonicek** [comment]
@facebook-github-bot stack-overflow

**Comment by shanqinghuayuran** [comment]
@seph14. When input Chinese characters, once the text input is on focus, the font position move down, then click outside text input space, the font position move up. Is right?
@mkonicek.  What cause this issue or do you have solution?
