### ISSUE TITLE
No bundle URL present error on iOS real device

### ISSUE THREAD

**Issue by shahjahansnapraise** [facebook/react-native#35968]
### Description

I am running a project on 0.70.1 version. The issue appears to be on the real device, on simulator it works fine. It narrows down to RNSplashScreen implementation in my case.

### Version

0.70.1

### Output of `npx react-native info`

System:
    OS: macOS 12.6.2
    CPU: (4) x64 Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
    Memory: 861.44 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
    Watchman: 2022.10.24.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8512546
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.1 => 0.70.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Install the app on Release mode or make an archive and install on real device. 

### Snack, code example, screenshot, or link to a repository

<img width="719" alt="Screenshot 2023-01-25 at 11 45 09 PM" src="https://user-images.githubusercontent.com/112865340/214654787-ac1c12c9-54b9-4c4c-8560-df69a9493277.png">

<img width="766" alt="Screenshot 2023-01-25 at 11 37 16 PM" src="https://user-images.githubusercontent.com/112865340/214654667-9ffa9d99-c178-4b5e-a01c-413878e16db0.png">

**Comment by 12ya** [comment]
uninstall the app and run "yarn ios" again

**Comment by shahjahansnapraise** [comment]
> uninstall the app and run "yarn ios" again

Did that, no luck.

**Comment by shahjahanpak** [comment]
In my case it is due to [Sentry](https://github.com/getsentry/sentry-react-native), 'cause auto-linking doesn't work as it should for version `4.14.0` so patching the module as described [here](https://docs.sentry.io/platforms/react-native/troubleshooting/#react-native-069-and-higher) resolved the issue.
