### ISSUE TITLE
(SMART ROTATE New feature from Android 12 Onwards) useWindowDimensions or Dimensions both dont update on coming back to Device Portrait from Landscape's Smart rotate Portrait in Lenovo M10 plus Tab

### ISSUE THREAD

**Issue by eziomaran619** [facebook/react-native#35964]
### Description

Newer tabs have something called as Smart rotate, which basically renders a smaller portrait version of the app (height as width of the device and width as proportionate value preserving the aspect ratio). When going from device portrait to device landscape, device auto re-renders the app in the new smaller portrait when smart rotate option is on. in this case the useWindowDimensions hook updates the dimensions to the new smaller portrait dimensions. but this isnt the case vise-versa. going back from the smart-rotate portrait (device is in landscape) to device portrait, neither the hook nor the Dimensions function from react-native seems to update to the newer dimensions. 

### Version

0.70.5

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
    Memory: 6.08 GB / 15.71 GB
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.3 - D:\...(sensitive)...\...(sensitive)...\node_modules\.bin\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: AI-212.5712.43.2112.8609683
    Visual Studio: Not Found
  Languages:
    Java: 11.0.15 - C:\Program Files\Common Files\Oracle\Java\javapath\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.5 => 0.70.5
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
info React Native v0.71.1 is now available (your project is running on v0.70.5).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.71.1
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.70.5
info For more info, check out "https://reactnative.dev/docs/upgrading".

### Steps to reproduce

1) Smart rotate ON (Smart rotate is an add on to Auto-rotate, so keeping Auto-rotate On goes without saying)
2) make sure to log the dimensions
3) go form Device PORTRAIT to Device LANDSCAPE (Device LANDSCAPE should render a smaller Portrait version of the app)
4) go from Device LANDSCAPE to Device PORTRAIT

### Snack, code example, screenshot, or link to a repository

Just console log the dimensions. Smart rotate reruns the App.js file by itself

**Comment by andriikovall** [comment]
Any updates on that? We ran into this issue as well.
