### ISSUE TITLE
React-native-geolocation with maximumAge: 0, is still getting cached location

### ISSUE THREAD

**Issue by afu1995** [facebook/react-native#35962]
### Description

Yo guys,
I'm using Geolocation from 'react-native-geolocation-service' library and the details are as follows. The problem I am facing is that android & iOS is returning the cached position. I have maximumAge set to 0, so it should never get any cached location and always get new location. 
Is there a way, an other approach, that I can always get the current location from the GPS in react native using this library? Any help is appreciated. Thanks. 

NOTE:
It's very hard to reproduce. This doesn't happen that often, but still occurs very few times.

```
export function getLocation(onSuccess: (position: GeoPosition) => void, onError?: (error: GeoError) => void) {
  Geolocation.getCurrentPosition(onSuccess, onError, {
    maximumAge: 0,
    accuracy: { ios: 'hundredMeters' },
    distanceFilter: 0,
    enableHighAccuracy: isAndroid,
    showLocationDialog: false,
    forceRequestLocation: true,
  });
}
```

### Version

0.70.0

### Output of `npx react-native info`

System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 73.42 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
    Watchman: 2022.11.14.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9477386
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.70.6 => 0.70.6
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

 When asking the package for location

### Snack, code example, screenshot, or link to a repository

  When asking the package for location

**Comment by iBotPeaches** [comment]
Let me add my 2c.

There is a reason Geolocation was moved out of the core - with how much it changes on each platform each release means its complex. I'm not sure why you believe there is a more accurate option that lies within React Native that you can simply query.

It was removed probably years ago and you can confirm it no longer exists in libraries here - https://github.com/facebook/react-native/tree/main/Libraries

So then if we jump back to your question.

> Is there a way, an other approach, that I can always get the current location from the GPS in react native using this library? Any help is appreciated. Thanks.

It doesn't really make any sense. No you cannot use React Native in a different way to use that package. However, you could triage the package and investigate yourself as I see it logs some information whether a cache location is in use at least on Android [here](https://github.com/Agontuk/react-native-geolocation-service/blob/master/android/src/main/java/com/agontuk/RNFusedLocation/FusedLocationProvider.java#L104):

So I believe your report is more meant for the plugin repo. As you can see the debated details pretty often about this same issue:

 * https://github.com/Agontuk/react-native-geolocation-service/issues/205
 * https://github.com/Agontuk/react-native-geolocation-service/issues/307
 
So with the 4 minutes of research I did you could try to upgrade to that plugin version of at least 5.3 and use play services of at least 18. 

With my final note we used this package for one application that needed far more control over GPS, it costs money but works well - https://www.transistorsoft.com/shop/products/react-native-background-geolocation
