### ISSUE TITLE
Error when trying to bundle release in Android studio react native 

### ISSUE THREAD

**Issue by sheggietyn** [facebook/react-native#35978]
### Description

I have been getting this error anytime i try to bundle my project for Release or ABB in android Studio 

below is the error i get 

### Version

0.67.2

### Output of `npx react-native info`

System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
    Memory: 29.07 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.6.1 - ~/node_modules/.bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v19.1.0/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v19.1.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.10.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK: Not Found
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Java: 12.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.2 => 0.67.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Error is coming from the final Release... I have tried everything I could but still the same thing 

### Snack, code example, screenshot, or link to a repository

the transform cache was reset.

Failed to construct transformer:  Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:140:10)
    at stableHash (/Users/SalamiEmmanuel/Awesomeproject/node_modules/metro-cache/src/stableHash.js:19:8)
    at Object.getCacheKey (/Users/SalamiEmmanuel/Awesomeproject/node_modules/metro-transform-worker/src/index.js:593:7)
    at getTransformCacheKey (/Users/SalamiEmmanuel/Awesomeproject/node_modules/metro/src/DeltaBundler/getTransformCacheKey.js:24:19)
    at new Transformer (/Users/SalamiEmmanuel/Awesomeproject/node_modules/metro/src/DeltaBundler/Transformer.js:48:9)
    at /Users/SalamiEmmanuel/Awesomeproject/node_modules/metro/src/Bundler.js:22:29 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
error Cannot read properties of undefined (reading 'transformFile').

**Comment by cortinico** [comment]
Error seems unrelated to React Native:
https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported

**Comment by Jamal-ReachFirst** [comment]
Reopen this issue

**Comment by Senninseyi** [comment]
Any fix on this issue

**Comment by Hamza-Khurshid** [comment]
Any fix?
