### ISSUE TITLE
Webview opening an URL with 'https:/domain.com' crashes the app

### ISSUE THREAD

**Issue by exoer** [facebook/react-native#35973]
### Description

Using a faulty URL, with only one /, in a WebView crashes the app.

### Version

0.70.5

### Output of `npx react-native info`

System:
    OS: macOS 13.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 20.98 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - /usr/local/opt/node@18/bin/node
    Yarn: 1.22.0 - ~/.yarn/bin/yarn
    npm: 8.19.2 - /usr/local/opt/node@18/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 28, 30
      Build Tools: 29.0.2, 30.0.1, 30.0.2
      System Images: android-33 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.5 => 0.70.5 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
info React Native v0.71.1 is now available (your project is running on v0.70.5).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.71.1
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.70.5
info For more info, check out "https://reactnative.dev/docs/upgrading".

### Steps to reproduce

Open a screen with WebView and a faulty URL. It just crashes on the iOS simulator

<img width="249" alt="image" src="https://user-images.githubusercontent.com/557371/214777345-c8a2eade-3e75-4178-b84a-59372376458e.png">

### Snack, code example, screenshot, or link to a repository

<WebView

          source={{ uri:'https:/domain.com' }}
          thirdPartyCookiesEnabled={false}
          javaScriptEnabled={false}
          onLoadEnd={() => setLoading(false)}
          onError={()=>setError('noe feilet')}
        />

**Comment by tarouboy** [comment]
Isn't WebView depreciated? Try https://github.com/react-native-webview/react-native-webview

**Comment by exoer** [comment]
Yes, I use `import WebView from 'react-native-webview';`  
So then i close the issue on this repo.
