### ISSUE TITLE
TypeError: registration.listener.apply is not a function

### ISSUE THREAD

**Issue by AntonioLi1** [facebook/react-native#35976]
### Description

Hi,
I have built a RN app with Firebase. When running it on IOS i sometimes receive this errror:
TypeError: registration.listener.apply is not a function. (In 'registration.listener.apply(registration.context, args)', 'registration.listener.apply' is undefined). It only sometimes appears and dismissing it will not affect the run of the app.
Does anyone know what is causing this issue and how to fix it?
My Call stack from top to bottom is:
Emit
EventEmit.js: 105:36
__callFunction
MessageQueue.js: 423:32
__guar$argument_0
MessageQueue.js: 113:26
__guard
MessageQueue.js: 367:11
callFunctionReturnFlushedQueue
MessageQueue.js: 112:17
callFunctionReturnFlushedQueue
[native code]

### Version

0.70.6

### Output of `npx react-native info`

System:
    OS: macOS 12.5.1
    CPU: (8) arm64 Apple M2
    Memory: 96.48 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.3.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.2.0 - /opt/homebrew/bin/npm
    Watchman: 2022.12.26.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/antonioli/.rvm/gems/ruby-2.7.5/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.70.6 => 0.70.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    react-native: Not Found

### Steps to reproduce

1. Develop in RN
2. Build on XCode 
3. Error occurs once in a while

### Snack, code example, screenshot, or link to a repository

Im not sure how to provide a Snack, Github link or minimal code example to reproduce the problem as I dont know what prouces the problem
![image0](https://user-images.githubusercontent.com/98675667/214799859-52c5665b-f7f9-4aba-86aa-9a8d3a7a7af3.png)

**Comment by iBotPeaches** [comment]
It looks like you might want to add your thoughts to this thread: https://github.com/facebook/react-native/issues/35577

**Comment by PPMike** [comment]
Do you repair this?

**Comment by Yogeshwar267** [comment]
this issue still persisits in my app, i am using  @react-native-voice/voice while i tap on microphone and start recording after few secs , error pops
