### ISSUE TITLE
[iOS] useColorScheme changes value when app is backgrounded

### ISSUE THREAD

**Issue by ealmiladi** [facebook/react-native#35972]
### Description

On a fresh `npx react-native init {appName}` project on iOS, if you `console.log({isDarkMode})` and move the app to the background, you'll notice these sets of logs. It seems that the `useColorScheme` hook is reporting that the user's theme setting has been changed, although it hasn't changed at all. Bringing the app to the foreground again resolves the issue, but causes screen flickers on elements that rely on the value.  This issue does not affect Android.

```
 LOG  {"isDarkMode": true} // app is in foreground and is currently in dark mode
 LOG  {"isDarkMode": false} // app is backgrounded and is _still_ in dark mode
 LOG  {"isDarkMode": true} // app is in foreground
```

### Version

0.70.6 - 0.71.1

### Output of `npx react-native info`

System:
    OS: macOS 12.5.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 45.07 MB / 32.00 GB
    Shell: 5.8.1 - /usr/local/bin/zsh
  Binaries:
    Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /Users/ealimadi/.rvm/gems/ruby-2.7.5/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.13 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.6 => 0.70.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. npx react-native init demo
2. Run iOS
4. console.log({isDarkMode})
5. Put app into background
6. Put app back into foreground
7. Review generated logs

### Snack, code example, screenshot, or link to a repository

```
function App(): JSX.Element {
  const isDarkMode = useColorScheme() === 'dark';
  console.log({isDarkMode})

  const backgroundStyle = {
    backgroundColor: isDarkMode ? Colors.darker : Colors.lighter,
  };

  return (
    <SafeAreaView style={backgroundStyle}>
      <StatusBar
        barStyle={isDarkMode ? 'light-content' : 'dark-content'}
        backgroundColor={backgroundStyle.backgroundColor}
      />
      <ScrollView
        contentInsetAdjustmentBehavior="automatic"
        style={backgroundStyle}>
        <Header />
        <View
          style={{
            backgroundColor: isDarkMode ? Colors.black : Colors.white,
          }}>
          <Section title="Step One">
            Edit <Text style={styles.highlight}>App.tsx</Text> to change this
            screen and then come back to see your edits.
          </Section>
          <Section title="See Your Changes">
            <ReloadInstructions />
          </Section>
          <Section title="Debug">
            <DebugInstructions />
          </Section>
          <Section title="Learn More">
            Read the docs to discover what to do next:
          </Section>
          <LearnMoreLinks />
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}
```

**Comment by sdmoir** [comment]
I'm experiencing this same issue on React Native 0.67.4.

My workaround for the time being to prevent screen flickering:
```typescript
const colorScheme = useColorScheme()
const [currentColorScheme, setCurrentColorScheme] = useState(colorScheme)
const onColorSchemeChange = useRef<NodeJS.Timeout>()

// Add a 1 second delay before switching color scheme
// Cancel if color scheme immediately switches back
useEffect(() => {
  if (colorScheme !== currentColorScheme) {
    onColorSchemeChange.current = setTimeout(() => setCurrentColorScheme(colorScheme), 1000)
  } else if (onColorSchemeChange.current) {
    clearTimeout(onColorSchemeChange.current)
  }
}, [colorScheme])

// <App theme={currentColorScheme}> ...
```

**Comment by ealmiladi** [comment]
> I'm experiencing this same issue on React Native 0.67.4.
> 
> My workaround for the time being to prevent screen flickering:
> 
> ```ts
> const colorScheme = useColorScheme()
> const [currentColorScheme, setCurrentColorScheme] = useState(colorScheme)
> const onColorSchemeChange = useRef<NodeJS.Timeout>()
> 
> // Add a 1 second delay before switching color scheme
> // Cancel if color scheme immediately switches back
> useEffect(() => {
>   if (colorScheme !== currentColorScheme) {
>     onColorSchemeChange.current = setTimeout(() => setCurrentColorScheme(colorScheme), 1000)
>   } else if (onColorSchemeChange.current) {
>     clearTimeout(onColorSchemeChange.current)
>   }
> }, [colorScheme])
> 
> // <App theme={currentColorScheme}> ...
> ```

Here's my workaround avoiding the `useColorScheme` hook completely:

```
    useEffect(() => {
        AppState.addEventListener('change', nextAppState => {
            if (nextAppState === 'active') {
                const theme = getColorScheme();
                setTheme(theme);
            }
        });
    }, []);
```

**Comment by batuhansahan** [comment]
i am experiencing this one on 0.71.8

**Comment by TheEhsanSarshar** [comment]
this hook might help, didn't test it tbh 😀
```js
function useForegroundColorScheme() {

   const colorScheme = useColorScheme()
   const lastCorrectColorScheme = useRef(null)
   if(!lastCorrectColorScheme.current) {
       lastCorrectColorScheme.current = colorScheme
   }
   return React.useMemo(() => {
     const appState = AppState.currentState
     if(Platform.OS === 'ios' && appState.match(/inactive|background/)) {
        return lasCorrectColorScheme.current
     } else {
        lastCorrectColorScheme.current = appState
        return lastCorrectColorScheme.current
     }
   }, [colorScheme])
}
```

**Comment by visoft** [comment]
`useColorScheme` changing in the background is causing `Rendered fewer hooks than expected. This may be caused by an accidental early return statement.` in React Native 0.71.10 when I use it in App.tsx.

**Comment by YaoHuiJi** [comment]
It happens on RN 0.72.0 too

**Comment by mhaanstra-wearetriple** [comment]
This is a result of the OS taking what is called a 'snapshot' on iOS, to facilitate the preview when you browse your open applications

**Comment by MateWW** [comment]
I've done a deeper investigation on that topic and it is the expected behavior of a native IOS application.

### Outcomes
As @mhaanstra-wearetriple mentioned it is called a "snapshot" that IOS will take when you go to the background.
IOS is preparing screenshots of your application in both **light** and **dark** mode and will use them in app switcher view.
This mechanism is not perfect in my opinion but on the other hand, it seems to be the only option to handle app switcher especially since a lot of users have tons of applications. Trying to rerender all applications that are open at once to change appearance sounds like an overkill.

### React native behaviour
I've validated that mechanism and as you may see in the attached video this works correctly for native apps.
However, react-native stays in one initial appearance mode.

#### Hypothesis
I've noticed that render on the JS side is done properly but the draw phase is not happening.
It seems to be happening right after the foreground as we see a smooth transition while the mode is changed.

### Questions:
- Do you think this feature should be supported by react native?
- If not can we trigger an appearance update only if a state is different than `background`?

https://github.com/facebook/react-native/assets/16048381/5dcbbf25-b77c-42fe-9538-e579dab5b467

**Comment by salman-ar-sar** [comment]
This is still an issue on 0.72.6, why was it closed?

**Comment by MateWW** [comment]
@salman-ar-sar
Fix will be available in 0.73

**Comment by salman-ar-sar** [comment]
> @salman-ar-sar Fix will be available in 0.73 based on changelog

Oh okay. That's good to hear. Do we have an estimated timeline for the 0.73 release?

**Comment by timothyerwin** [comment]
yeah, I think I'm seeing something similar. when I bring it back it's redrawing the entire screen first in dark mode, then back to the light mode...

**Comment by timothyerwin** [comment]
> This is a result of the OS taking what is called a 'snapshot' on iOS, to facilitate the preview when you browse your open applications; a snapshot is required for both light & dark mode in case you change modes while on the open application screen, so the OS will report a brief moment in time both light & dark mode where the app should respond to these modes, or risk a flawed snapshot

"in case"? lol, seems very lazy and inefficient of the iOS developers here...wouldn't they know when the color scheme changes and only trigger a snapshot then?

**Comment by Darren120** [comment]
still exist on new version. using expo. RN 0.73

**Comment by git-user-1337** [comment]
Why was this closed if it's still not fixed?

**Comment by marcos-vinicius-mafei** [comment]
Still not fixed :/

**Comment by Georg7** [comment]
This is a terrible user experience - and still not fixed

**Comment by RhonnieAl** [comment]
RN 0.74 and still not fixed 🥲

**Comment by chichilatte** [comment]
The crappy thing is iOS doesn't even manage to take a snapshot of your app in both light and dark themes, since it's preventing JavaScript from doing a rerender until your app foregrounds again! 

So when you background your app and go change the system theme, then bring up the app switcher again, your app's snapshot is still in the old theme. It's a tough problem! For now the best solution seems to be to stop iOS taking two snapshots by debouncing your system theme change listener. Not ideal but better than the default behaviour.

**Comment by MihirP24** [comment]
I am also having the same issue, does anybody know any solution , this is my code

const updateTheme = (newTheme) => {
    let mode;
    if (
      (newTheme.system === theme.system && theme.mode === newTheme.mode) ||
      (newTheme.mode === undefined &&
        theme.system === true &&
        newTheme.system === true)
    ) {
      return;
    }
    if (newTheme) {
      if (newTheme.system) {
        // for autoBGChange, to avoid calling the Appearance.getColorScheme
        if (newTheme.bgChange) {
          mode = newTheme.mode === "dark" ? "dark" : "light";
          newTheme = { ...newTheme, mode, system: true };
        } else {
          mode = systemColorScheme === "dark" ? "dark" : "light";
          newTheme = { ...newTheme, mode, system: true };
        }
      } else {
        newTheme = { ...newTheme, system: false };
      }
    }
    setTheme(newTheme);
    storeData("Theme", newTheme);
  };
  
  useEffect(() => {
    const onColorSchemeChange = (colorScheme) => {
      if (theme.system) {
        updateTheme({
          system: true,
          bgChange: true,
          mode: colorScheme.colorScheme,
        });
      }
    };

    const appearanceListener =
      Appearance.addChangeListener(onColorSchemeChange);

    // Cleanup listener when component unmounts
    return () => appearanceListener.remove();
  }, [theme.system, theme.bgChange, theme.mode]);

**Comment by andresribeiro** [comment]
@MihirP24 the solution provided by @ealmiladi above worked for me

**Comment by IntStud** [comment]
this works for me:

{
  "expo": {
    "userInterfaceStyle": "automatic",
    "ios": {
      "userInterfaceStyle": "automatic"
    },
    "android": {
      "userInterfaceStyle": "automatic"
    }
  }
}

**Comment by janoslc** [comment]
Hey followers! As of my research on this topic ReactNative 0.77.0 includes the modifications to fix this behaviour. It will be released next week. 
Relevant changes: https://github.com/facebook/react-native/commit/6118aff69d69dce557b1c9d217c538f5670afed1

Release info: https://github.com/facebook/react-native/releases/tag/v0.77.0-rc.6

In my case a simple workaround just wasn't enough since I use [react-native-ui-lib](https://github.com/wix/react-native-ui-lib) and it has it's own internal reference to `useColorScheme()` in order to automatically set its theme.

**Comment by artur-burlak** [comment]
@janoslc This changes were included in RN 0.73


Problem still exists RN 076.5, bridgelessMode ON

**Comment by janoslc** [comment]
> @janoslc This changes were included in RN 0.73
> 
> 
> Problem still exists RN 076.5, bridgelessMode ON

You may be right, it's confusing to follow the modification chains to me. I could be wrong.

**Comment by artur-burlak** [comment]
@janoslc No problem 

https://github.com/facebook/react-native/blob/main/CHANGELOG.md#v0730

you see it in **iOS specific**, line 9

**Comment by artur-burlak** [comment]
> [@MihirP24](https://github.com/MihirP24) the solution provided by [@ealmiladi](https://github.com/ealmiladi) above worked for me

This workaround doesn't work for changes of appearance when the app is opened, for example for schedule changes (sunrise, sunset). His code is checking appearance only on appState changes. 
**useColorScheme** hook is exactly for it. Somehow it doesn't work correctly again on latest versions with bridgeless mode ON.

**Comment by artur-burlak** [comment]
@alanjhughes Are you able to reopen the issue?

**Comment by janoslc** [comment]
Please leave a reaction here if you agree to re-report this issue. I'll schedule some time to prepare all the details for it.

**Comment by janoslc** [comment]
Feel free to contribute, add missing information to the ticket linked above. Thank you!

**Comment by oliverdolgener** [comment]
Can confirm this is still an issue. We never had any problems on the old architecture. But last week we enabled the new architecture and the issue arised.

RN 0.78 + new arch

**Comment by bryanmylee** [comment]
Leaving a note for anyone else running into this issue, but this patch works as expected.

https://github.com/facebook/react-native/issues/49330

**Comment by bryanmylee** [comment]
> This is my solution:
> 
> ```
> import {
>   Appearance,
>   AppState,
>   AppStateStatus,
>   ColorSchemeName,
> } from 'react-native';
> import {useEffect, useRef, useState} from 'react';
> import getColorScheme = Appearance.getColorScheme;
> 
> // There is a bug in iOS regarding the color scheme flickering while app being in the background or taking a screenshot
> // We'll make a custom logic then
> // https://github.com/facebook/react-native/issues/35972
> export const useColorScheme = () => {
>   const [scheme, setScheme] = useState<ColorSchemeName>(getColorScheme());
>   const appStateRef = useRef<AppStateStatus>(AppState.currentState);
> 
>   // Get the current app state (so that we don't update color scheme in the background)
>   useEffect(() => {
>     const subscription = AppState.addEventListener('change', nextAppState => {
>       appStateRef.current = nextAppState;
> 
>       if (nextAppState === 'active') {
>         setScheme(getColorScheme());
>       }
>     });
> 
>     return () => {
>       subscription.remove();
>     };
>   }, []);
> 
>   useEffect(() => {
>     const subscription = Appearance.addChangeListener(({colorScheme}) => {
>       if (appStateRef.current === 'active') {
>         setScheme(colorScheme);
>       }
>     });
> 
>     return () => {
>       subscription.remove();
>     };
>   }, []);
> 
>   return scheme;
> };
> ```

You'll be setting up new state and listeners for every invocation of your `useColorScheme` hook. Just patch the underlying framework and recompile.
