### ISSUE TITLE
[Android] Border is gone when using underlayColor

### ISSUE THREAD

**Issue by PhilippKrone** [facebook/react-native#3597]
Hello,

when having a button with an e.g. red border and an underlayColor of red, the moment you release the button press (and the underlayColor is removed again), the border is gone as well. See sample app:

https://rnplay.org/apps/m9cARA

Please note that this is only when choosing 0.13-rc on RNPlay - its still this way on current master.

Thanks
Philipp

**Comment by PhilippKrone** [comment]
@kmagiera As far as I have seen from other issues, you might be the one with the best knowledge here. Any idea?

**Comment by PhilippKrone** [comment]
@mkonicek @kmagiera Sorry for pushing this. If you can gimme a hint as to where to look, I can try to fix it as well. However, I'm not used (yet) to the ReactAndroid internals

**Comment by browniefed** [comment]
Is this still happening?

**Comment by damusnet** [comment]
@facebook-github-bot no-reply

**Comment by damusnet** [comment]
@facebook-github-bot no-reply

**Comment by facebook-github-bot-0** [comment]
Closing this issue as more information is needed to debug this and we haven't heard back from the author. Once there's more information we can reopen the issue.
