### ISSUE TITLE
ReactAndroid:downloadBoost is not cached anymore

### ISSUE THREAD

**Issue by zxccvvv** [facebook/react-native#35985]
### Description

Everytime i clean my android project using `./gradlew clean` and start `npx react-native run-android` there's a task to download [ReactAndroid:downloadBoost](https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.gz) (120MB+), since my internet provider is not really fast enough (only have 500kbps) it takes too long to build apk

I just search something like cached those task and found it already solved here https://github.com/facebook/react-native/issues/13773 but it seems the cached is not working anymore

### Version

0.70.6

### Output of `npx react-native info`

System:
    OS: macOS 12.5
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 2.31 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.0 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.19.3 - /usr/local/bin/npm
    Watchman: 2023.01.16.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK:
      API Levels: 27, 28, 29, 30, 31, 33
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 33.0.0
      System Images: android-23 | Intel x86 Atom_64, android-27 | Google APIs ARM 64 v8a, android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. init project
2. enable new arch in `gradle.properties`
3. run `npx react-native run-android` [should running ReactAndroid:downloadBoost download]
4. clean android project using `cd android && ./gradlew clean`
5. run `npx react-native run-android` will re-download ReactAndroid:downloadBoost

### Snack, code example, screenshot, or link to a repository

<img width="519" alt="Screen Shot 2023-01-27 at 09 01 59" src="https://user-images.githubusercontent.com/19633881/214994507-aaf4549a-4e0a-4951-b4e8-22c15ee4e7d7.png">

**Comment by UNIDY2002** [comment]
I found a way to make it work. Set the environment variable `REACT_NATIVE_DOWNLOADS_DIR` to be a local directory on your computer. In this case, the dependencies (such as boost) will be downloaded to `REACT_NATIVE_DOWNLOADS_DIR` for the first time, and as long as you do not clean the `REACT_NATIVE_DOWNLOADS_DIR`, the downloaded results will be cached.

Reference: https://github.com/facebook/react-native/blob/0.70-stable/ReactAndroid/build.gradle#L34

**Comment by cortinico** [comment]
> I found a way to make it work. Set the environment variable `REACT_NATIVE_DOWNLOADS_DIR` to be a local directory on your computer. In this case, the dependencies (such as boost) will be downloaded to `REACT_NATIVE_DOWNLOADS_DIR` for the first time, and as long as you do not clean the `REACT_NATIVE_DOWNLOADS_DIR`, the downloaded results will be cached.

This is the correct answer.
Plus from React Native 0.71, Gradle will handle the caching of Boost for you so you won't see the `downloadBoost` task anymore
