### ISSUE TITLE
FBReactNativeSpecJSI-generated.cpp normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'React-Codegen' from project 'Pods') (1 failure)

### ISSUE THREAD

**Issue by devDoubleH** [facebook/react-native#35986]
### Description

Hi there I am trying to run on the ios simulator but I am facing this error I have tried all StackOverflow and github issues but it didn't work I thought this error was by react-native cli and I have downgraded to 0.69.0 pod install works fine but `npx react-native run-ios` not working facing this error: 

```
FBReactNativeSpecJSI-generated.cpp normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'React-Codegen' from project 'Pods')
(1 failure)
```

### Version

0.69.0

### Output of `npx react-native info`

System:
    OS: macOS 13.0.1
    CPU: (8) arm64 Apple M2
    Memory: 82.19 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.19 - ~/Desktop/IOS-version-0.2/node_modules/.bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
    Watchman: 2023.01.23.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/abdukakhkhorovismoiljon/.rvm/gems/ruby-2.7.5/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: ^0.69.0 => 0.69.7
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

`npx react-native run-ios`    not working

[link](https://user-images.githubusercontent.com/83258481/215018990-2d0002ce-3835-4c91-a02d-ece2e5f31153.png)

**Comment by Saad-Bashar** [comment]
Weird, I am getting the same error today all of a sudden. My react native version is 0.68.5. This is what when I try to build it in Xcode. Not sure what am I doing wrong. I did all the things with POD. pod install, pod disintegrate, remove pod, etc. But this is coming up every time.

![Screenshot 2023-01-31 at 1 53 18 PM](https://user-images.githubusercontent.com/13269141/215740905-88a00c59-35ec-451c-a2a4-fd1c43f9f4d4.png)

**Comment by devDoubleH** [comment]
@Saad-Bashar Hi ) arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler this error is appearing in my terminal every time when I run `npx react-native run-ios` I can't solve this for two weeks

**Comment by devDoubleH** [comment]
> Did you try building the app from Xcode?

yep 
![Uploading Screenshot 2023-01-31 at 18.54.49.png…]()

**Comment by Saad-Bashar** [comment]
Your picture was not uploaded, what errors did you get? Did you get same like mine?

**Comment by devDoubleH** [comment]
> Your picture was not uploaded, what errors did you get? Did you get same like mine?

No there is another issue in Xcode

**Comment by devDoubleH** [comment]
@Saad-Bashar Lot's RN developers say it is because of the ruby version mine is 2.7.5 now and when I want to create a new
 app using `npx react-native init` I am getting an error ruby version which I need a 2.7.6 version of ruby to run this command.
What is your ruby version?

**Comment by vanGalilea** [comment]
Having the same issue here, all of a sudden 😢

**Comment by devDoubleH** [comment]
@kaushal9808 I would kindly suggest updating the Ruby version to the latest available version if that is feasible for your project.

**Comment by sanoofrahiman960** [comment]
> ### Description
> Hi there I am trying to run on the ios simulator but I am facing this error I have tried all StackOverflow and github issues but it didn't work I thought this error was by react-native cli and I have downgraded to 0.69.0 pod install works fine but `npx react-native run-ios` not working facing this error:
> 
> ```
> FBReactNativeSpecJSI-generated.cpp normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'React-Codegen' from project 'Pods')
> (1 failure)
> ```
> 
> ### Version
> 0.69.0
> 
> ### Output of `npx react-native info`
> System: OS: macOS 13.0.1 CPU: (8) arm64 Apple M2 Memory: 82.19 MB / 8.00 GB Shell: 5.8.1 - /bin/zsh Binaries: Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node Yarn: 1.22.19 - ~/Desktop/IOS-version-0.2/node_modules/.bin/yarn npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm Watchman: 2023.01.23.00 - /opt/homebrew/bin/watchman Managers: CocoaPods: 1.11.3 - /Users/abdukakhkhorovismoiljon/.rvm/gems/ruby-2.7.5/bin/pod SDKs: iOS SDK: Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1 Android SDK: Not Found IDEs: Android Studio: Not Found Xcode: 14.2/14C18 - /usr/bin/xcodebuild Languages: Java: 1.8.0_292 - /usr/bin/javac npmPackages: @react-native-community/cli: Not Found react: 18.1.0 => 18.1.0 react-native: ^0.69.0 => 0.69.7 react-native-macos: Not Found npmGlobalPackages: _react-native_: Not Found
> 
> ### Steps to reproduce
> `npx react-native run-ios` not working
> 
> [link](https://user-images.githubusercontent.com/83258481/215018990-2d0002ce-3835-4c91-a02d-ece2e5f31153.png)

i got issue like this 

"/ios/build/generated/ios/react/renderer/components/rncore/ShadowNodes.cpp normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'React-Codegen' from project 'Pods')
(1 failure)"


**my pod file below attached  please i stuck with this error-----**
<img width="1093" alt="Screenshot 2023-07-10 at 3 19 55 PM" src="https://github.com/facebook/react-native/assets/81160871/f225716e-e509-4898-ac53-d19dec5eca85">

**my system info** 

  OS: macOS 12.5
    CPU: (8) arm64 Apple M1
    Memory: 107.34 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.4.1 - ~/.nvm/versions/node/v16.17.1/bin/npm
    Watchman: 2023.02.27.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /Users/sanoofrahimanj/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9619390
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 19.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^18.1.0 => 18.2.0 
    react-native: ^0.70.6 => 0.70.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
