### ISSUE TITLE
android.view.View.getParent() invoked on a null object

### ISSUE THREAD

**Issue by PhilippKrone** [facebook/react-native#3599]
Hi,

I have an Animated view as follows:
````javascript
        <Animated.View ref='detailedCard' key={'card'} panResponder={this._panResponder} style={[
          {flex: 1},
          {transform: [
            {translateX: this.state.x}, {translateY: this.state.y},
          ]}]}>       
            {this.renderComponent}
        </Animated.View>
````

In the _handlePanResponderMove method, I'm doing - besides others - the following:
````javascript
    this.state.x.setValue(dx);
    this.state.y.setValue(0);
````

I immediately get the following redbox:
![bildschirmfoto 2015-10-22 um 12 30 38](https://cloud.githubusercontent.com/assets/11861008/10663074/d9166ba0-78b8-11e5-932a-aeddef408ede.png)

Any idea what this might be?

Regards
Philipp

**Comment by PhilippKrone** [comment]
Update: I was able to "fix" it by specifying 

````javascript
      onShouldBlockNativeResponder: (evt, gestureState) => {
        // Returns whether this component should block native components from becoming the JS
        // responder. Returns true by default. Is currently only supported on android.
        return false;
      },
`````
although I'm not exactly sure what other kind of consequences that has. Any idea?

**Comment by ide** [comment]
@kmagiera and @mkonicek might have an idea of what is happening here. The native layer shouldn't get what looks like a NPE.

**Comment by mkonicek** [comment]
Haven't had time to look into this closely yet but NPE is definitely a bug. At the very least it should be handled gracefully.

**Comment by satya164** [comment]
Any updates on this?

**Comment by kmagiera** [comment]
@PhilippKrone would be helpful to get the stacktrace in a better resolution if possible. One thing that comes to my mind is that JS may try to set JS responder on a view that has been removed by layout-only nodes optimisation. In that case I'd try adding `collapsable={false}` to your animated view component and checking if it helped

**Comment by satya164** [comment]
@PhilippKrone Can you provide a stacktrace?

**Comment by damusnet** [comment]
@facebook-github-bot no-reply

**Comment by damusnet** [comment]
@facebook-github-bot no-reply

**Comment by facebook-github-bot-0** [comment]
Closing this issue as more information is needed to debug this and we haven't heard back from the author. Once there's more information we can reopen the issue.
