### ISSUE TITLE
Copy / Select / Select all menu is not displayed when selecting Text (ios only)

### ISSUE THREAD

**Issue by idanlevi1** [facebook/react-native#35997]
### Description

I use `selectable` props in `Text` to give the user option to copy the text, I want the typical behavior in ios (show small menu with options like select, select all, copy...) but only "copy" option is shown
<img width="747" alt="image" src="https://user-images.githubusercontent.com/21155847/215292902-e3ebe833-eeea-44db-aaaa-e65651978056.png">

### Version

0.68.2

### Output of `npx react-native info`

System:
    OS: macOS 12.0
    CPU: (10) arm64 Apple M1 Pro
    Memory: 885.97 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 19.2.0 - ~/.nvm/versions/node/v19.2.0/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v19.2.0/bin/npm
    Watchman: 2022.12.12.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/isracardteam/.rvm/gems/ruby-2.7.4/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.2 => 0.68.2 

### Steps to reproduce

use `<Text selectable={true}>Some Text</Text>` 
and click and hold to select text using a text component on iOS 

### Snack, code example, screenshot, or link to a repository

`<Text selectable={true}>Some Text</Text>`

**Comment by lovelytingy** [comment]
Hi @idanlevi1 Currently, only copy option is available on IOS. But you can use [react-native-selectable-text](https://www.npmjs.com/package/@alentoma/react-native-selectable-text) in order to achieve your requirement. 
Further, you can vote [feature-request](https://react-native.canny.io/feature-requests/p/support-selecting-text-within-text-elements-for-copypaste-etc) to add native options in react-native.
