### ISSUE TITLE
ReactNative ToastAndroid

### ISSUE THREAD

**Issue by TomWq** [facebook/react-native#36006]
### Description

ToastAndroid's showWithGravity method doesn't work. Hasn't anyone noticed that on Android, centring doesn't work at all

### Version

0.71.1

### Output of `npx react-native info`

System:
    OS: macOS 13.1
    CPU: (10) x64 Apple M1 Pro
    Memory: 29.37 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.17.5 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.1.2 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29, 30, 31, 32, 33
      Build Tools: 26.0.1, 27.0.2, 27.0.3, 28.0.3, 29.0.1, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 32.0.0
      System Images: android-26 | ARM 64 v8a, android-29 | Android TV Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-32 | Google APIs ARM 64 v8a
      Android NDK: 23.0.7196353-beta2
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.1 => 0.71.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Add a toast display toa button button

### Snack, code example, screenshot, or link to a repository

ToastAndroid.showWithGravity('This is a toast', ToastAndroid.SHORT, ToastAndroid.CENTER)

**Comment by mensonones** [comment]
Hi, @wq13718048209! I tested it and it's working on the same version of react native
[Gravação de tela de 31-01-2023 08:16:11.webm](https://user-images.githubusercontent.com/5387202/215745821-6a1808c3-f376-4b39-89fc-3cb5610f6734.webm)

**Comment by laohuzhigege** [comment]
good project thankyou
