### ISSUE TITLE
React native expo cannot resolve font file

### ISSUE THREAD

**Issue by labadcloyd** [facebook/react-native#36015]
### Description

Im using react native@0.70.5 with expo@~47.0.8 Im trying to use custom fonts and whenever I import them using expo font I get this error: Unable to resolve "../../assets/fonts/Montserrat-Regular.tff" from "core\hooks\useFonts.js"

### Version

0.70.5

### Output of `npx react-native info`

System:
    OS: Windows 10 10.0.22000
    CPU: (6) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
    Memory: 3.13 GB / 15.79 GB
  Binaries:
    Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 30, 31, 33
      Build Tools: 30.0.2, 31.0.0, 33.0.0
      System Images: android-30 | Google Play Intel x86 Atom, android-31 | Intel x86 Atom_64, android-31 | Google APIs Intel x86 Atom_64, android-31 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: AI-212.5712.43.2112.8609683
    Visual Studio: Not Found
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.5 => 0.70.5
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

I just implemented the code based on the documentation of expo: https://docs.expo.dev/guides/using-custom-fonts/

### Snack, code example, screenshot, or link to a repository

here is my react-native.config.js file:

```
module.exports = {
  project: {
    ios: {},
    android: {},
  },
  assets: ["./assets/fonts/"],
};
```

here's the use font hook
```
import * as Font from "expo-font";

export default useFonts = async () =>
  await Font.loadAsync({
    "Montserrat-Regular": require("../../assets/fonts/Montserrat-Regular.tff"),
  });
```

and here's the app.js:
```
import { View } from "react-native";
import AppLoading from "expo-app-loading";

import MainNavigator from "./core/navigation/main";
import useFonts from "./core/hooks/useFonts";

export default function App() {
  const [IsReady, SetIsReady] = useState(false);

  const LoadFonts = async () => {
    await useFonts();
  };

  if (!IsReady) {
    return (
      <AppLoading
        startAsync={LoadFonts}
        onFinish={() => SetIsReady(true)}
        onError={() => {}}
      />
    );
  }
  return (
    <View>
      <MainNavigator></MainNavigator>;
    </View>
  );
}
```
I've tried moving the useFont hook directly to App.js and it still can't resolve the font file. Take note, the path file is absolutely accurate.

 Here is my folder structure

```
ROOT
  App.js
  react-native.config.js
  core
  --hooks
  ----useFonts.js
  assets
  --fonts
  ----Montserrat-Regular.ttf
```

**Comment by cortinico** [comment]
> Im using react native@0.70.5 with expo@~47.0.8

Hi,
Thanks for reporting this issue.

It seems like this issue is actually unrelated to React Native core but related to Expo. Please open this issue against this other repository:

https://github.com/expo/expo/issues

I'll be closing this but feel free to reopen if the other repo points back to us as a issue in the core of React Native.
