### ISSUE TITLE
iOS KeyboardAvoidingView not updating if the view behind it gets updated

### ISSUE THREAD

**Issue by tnguyen42** [facebook/react-native#36027]
### Description

While working totally fine on Android, the KeyboardAvoidingView does not update the keyboard's position when the view changes, pushing the input down behind the keyboard:

https://user-images.githubusercontent.com/12211685/215985943-3316d089-087c-44cc-bdd3-6193b6e7c660.mov

I tried all the 3 different behaviors of KeyboardAvoidingView to see if it would fix anything: in the video above, `padding` is used, but `position` just renders a white View, and `height` doesn't seem to do much either.

### Version

0.68.5

### Output of `npx react-native info`

System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 95.92 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.21.2 - ~/.nvm/versions/node/v14.21.2/bin/node
    Yarn: 1.22.17 - ~/freelance/2301-Bouygues/mcare/node_modules/.bin/yarn
    npm: 6.14.17 - ~/.nvm/versions/node/v14.21.2/bin/npm
    Watchman: 2023.01.09.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9477386
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.2 => 17.0.2 
    react-native: 0.68.x => 0.68.5 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Use a TextInput with some validation that creates an error above if certain conditions are met, and make the error "push the TextInput down".

### Snack, code example, screenshot, or link to a repository

https://user-images.githubusercontent.com/12211685/215985943-3316d089-087c-44cc-bdd3-6193b6e7c660.mov

**Comment by akshgods** [comment]
yes facing same issue, any solution
