### ISSUE TITLE
FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by HM-23-HM** [facebook/react-native#36021]
### New Version

0.71.1

### Old Version

0.70.6

### Build Target(s)

Android emulator

### Output of `react-native info`

warn Package react-native-safe-area-context has been ignored because it contains invalid configuration. Reason: "dependency.platforms.android.libraryName" is not allowed
warn Package react-native-screens has been ignored because it contains invalid configuration. Reason: "dependency.platforms.android.componentDescriptors" is not allowed
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz
    Memory: 18.60 GB / 31.88 GB
  Binaries:
    Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: AI-212.5712.43.2112.8609683
    Visual Studio: Not Found
  Languages:
    Java: 11.0.15.1
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.6 => 0.70.6
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Issue and Reproduction Steps

Ran `yarn add react-native@0.71.1` and received the following error: 

```
<--- Last few GCs --->

[23848:0000020FDBE6EBD0]   733305 ms: Mark-sweep 16128.2 (16420.6) -> 16120.3 (16429.8) MB, 8696.8 / 0.0 ms  (average mu = 0.458, current mu = 0.313) allocation failure scavenge might not succeed
[23848:0000020FDBE6EBD0]   753983 ms: Mark-sweep 16136.4 (16430.1) -> 16127.9 (16436.8) MB, 20545.6 / 0.0 ms  (average mu = 0.241, current mu = 0.006) allocation failure scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF6A53D7C4F v8::internal::CodeObjectRegistry::~CodeObjectRegistry+114207
 2: 00007FF6A5365EC6 DSA_meth_get_flags+65542
 3: 00007FF6A5366D7D node::OnFatalError+301
 4: 00007FF6A5C9B6CE v8::Isolate::ReportExternalAllocationLimitReached+94
 5: 00007FF6A5C85CAD v8::SharedArrayBuffer::Externalize+781
 6: 00007FF6A5B2907C v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1468
 7: 00007FF6A5B26194 v8::internal::Heap::CollectGarbage+4244
 8: 00007FF6A5B23B10 v8::internal::Heap::AllocateExternalBackingStore+2000
 9: 00007FF6A5B48696 v8::internal::Factory::NewFillerObject+214
10: 00007FF6A587AB65 v8::internal::DateCache::Weekday+1797
11: 00007FF6A5D293C1 v8::internal::SetupIsolateDelegate::SetupHeap+494417
12: 00007FF6A5D3F575 v8::internal::SetupIsolateDelegate::SetupHeap+584965
13: 0000020FDDC53157
```

NODE_OPTIONS "--max-old-space-size" was changed from 4096 to 16384, but this did not solve the problem.

**Comment by LonguCodes** [comment]
Getting the same issue with this version

**Comment by janlat** [comment]
In my case, upgrading RN and Babel at the same time (`yarn add react-native @babel/core`) helped. Looks like yarn falls into an infinite loop when trying to resolve conflicting babel versions or something ¯\\\_(ツ)_/¯

It's probably best to update everything in package.json according to the [Upgrade Helper](https://react-native-community.github.io/upgrade-helper/) and just run `yarn` afterwards

**Comment by paradite** [comment]
For anyone getting this error when upgrading Expo SDK to 48, the trick above works.

Just run:
```
yarn add react-native@0.71.8 @babel/core@^7.20.0
```
manually, which installs the required version by Expo.

**Comment by cortinico** [comment]
Duplicates https://github.com/facebook/react-native/issues/35821
