### ISSUE TITLE
IOS test flight crashes on launch

### ISSUE THREAD

**Issue by sandeeptheminery** [facebook/react-native#36022]
### Description

IOS test flight crashes on launch, it works fine with simulator, here is the error trace

Last Exception Backtrace:
0 CoreFoundation 0x1b9036248 _exceptionPreprocess + 164 (NSException.m:202)
1 libobjc.A.dylib 0x1b23f7a68 objc_exception_throw + 60 (objc-exception.mm:356)
2 AppName 0x10238db70 RCTFatal + 668 (RCTAssert.m:146)
3 AppName 0x1023fe4f0 -[RCTExceptionsManager reportFatalException:stack:exceptionId:] + 496 (RCTExceptionsManager.mm:65)
4 CoreFoundation 0x1b90a0a14 invoking + 148 (:-1)
5 CoreFoundation 0x1b904cf2c -[NSInvocation invoke] + 428 (NSForwarding.m:3377)
6 CoreFoundation 0x1b904c944 -[NSInvocation invokeWithTarget:] + 64 (NSForwarding.m:3474)
7 AppName 0x1023bf0e0 -[RCTModuleMethod invokeWithBridge:module:arguments:] + 460 (RCTModuleMethod.mm:569)
8 AppName 0x1023c1238 facebook::react::invokeInner(RCTBridge*, RCTModuleData*, unsigned int, folly::dynamic const&) + 244 (RCTNativeModule.mm:108)
9 AppName 0x1023c0fa8 operator() + 44 (RCTNativeModule.mm:73)
10 AppName 0x1023c0fa8 invocation function for block in facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int) + 88 (RCTNativeModule.mm:65)
11 libdispatch.dylib 0x1c04b04b4 _dispatch_call_block_and_release + 32 (init.c:1518)
12 libdispatch.dylib 0x1c04b1fdc _dispatch_client_callout + 20 (object.m:560)
13 libdispatch.dylib 0x1c04b9694 _dispatch_lane_serial_drain + 672 (inline_internal.h:2632)
14 libdispatch.dylib 0x1c04ba1e0 _dispatch_lane_invoke + 384 (queue.c:3940)
15 libdispatch.dylib 0x1c04c4e10 _dispatch_workloop_worker_thread + 652 (queue.c:6846)
16 libsystem_pthread.dylib 0x205954df8 _pthread_wqthread + 288 (pthread.c:2618)
17 libsystem_pthread.dylib 0x205954b98 start_wqthread + 8 (:-1)

### Version

0.61.5

### Output of `npx react-native info`

info Fetching system and libraries information...
(node:30517) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use node --trace-warnings ... to show where the warning was created)
System:
OS: macOS 12.2.1
CPU: (8) x64 Apple M1
Memory: 48.98 MB / 8.00 GB
Shell: 5.8 - /bin/zsh
Binaries:
Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
Yarn: 1.22.18 - ~/.nvm/versions/node/v16.13.1/bin/yarn
npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
SDKs:
iOS SDK:
Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
IDEs:
Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
npmPackages:
react: 16.9.0 => 16.9.0
react-native: 0.61.5 => 0.61.5

### Steps to reproduce

No particular steps but It cause random crash when app starts, it works with simulator

### Snack, code example, screenshot, or link to a repository

Test Device OS Version: iPhone OS 16.0.3
Release Type: User
Code Type: ARM-64 (Native)

**Comment by iBotPeaches** [comment]
@sandeeptheminery - Saying this respectfully, but RN61 is almost 4+ years old. You might as well close this and upgrade through the last few years and see what new problems you face.

No one is going to triage something that old and out of scope.
