### ISSUE TITLE
[Android] Pressable ripple fires twice when color is changed on press

### ISSUE THREAD

**Issue by JoshuaJADaniel** [facebook/react-native#36033]
### Description

On Android, changing the color of the `<Pressable />` ripple via the `android_ripple` prop during `onPress` causes the ripple effect to render twice: once from the location of the press and a second time from the top left. The extra ripple only appears when the `<Pressable />` is clicked rather than held down.

### Version

0.70.5

### Output of `npx react-native info`

```
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 1.45 GB / 15.69 GB
  Binaries:
    Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 9.1.1 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version     2021.1.0.0 AI-211.7628.21.2111.8193401
    Visual Studio: 16.11.32630.194 (Visual Studio Professional 2019), 17.0.32112.339 (Visual Studio Professional 2022)
  Languages:
    Java: 11.0.14 - /c/Program Files/Common Files/Oracle/Java/javapath/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.5 => 0.70.5
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

Assuming you are on Android:
1. Use `<Pressable />` component
2. Set the ripple color via the `android_ripple` prop
3. Change the ripple color during the `onPress` prop
4. Click (do not hold) the `<Pressable />`

### Snack, code example, screenshot, or link to a repository

Snack: [https://snack.expo.dev/@joshuajadaniel/pressable-ripple-fires-twice-when-color-is-changed-on-press](https://snack.expo.dev/@joshuajadaniel/pressable-ripple-fires-twice-when-color-is-changed-on-press)

https://user-images.githubusercontent.com/30093054/216097507-d75a7c46-dd8f-4a1f-b9de-dd39d82608f0.mp4

**Comment by lovelytingy** [comment]
@JoshuaJADaniel  hi, I tried you code in my 0.71.1 RN project, with debug and release mode, It is working fine. But when I am trying in the snack with their provided android emulator in site. Issue raised as you mentioned. But It doesn't come on when I choose my Device with latest Expo version.
Trying on Real Device may help.

**Comment by JoshuaJADaniel** [comment]
@lovelytingy I have not tried yet with RN 0.71.1 since the latest Expo version (47) comes with RN 0.70.5.

> But It doesn't come on when I choose my Device with latest Expo version.

That's interesting, the issue persists on my end even when running it on a physical Android device through Expo. Moreover, it does not seem to be a debug versus release bug since the same behavior occurs after creating a fresh Expo project and generating a production APK.

**Comment by lovelytingy** [comment]
I think this has to releted to expo sdk then.

**Comment by nethriis** [comment]
The issue is still there
