### ISSUE TITLE
iOS speech-to-text entered twice into TextInput

### ISSUE THREAD

**Issue by CodingItWrong** [facebook/react-native#36031]
### Description

Since iOS 16.0, sometimes when I use iOS speech-to-text to input text into a `TextInput`, the text is entered twice. This does not happen every time, but it is frequent.

### Version

0.71.1

### Output of `npx react-native info`

```
System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 2.82 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.13.0/bin/yarn
    npm: 9.2.0 - ~/.nvm/versions/node/v18.13.0/bin/npm
    Watchman: 2023.01.09.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/josh/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.1 => 0.71.1
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

- Run any RN app with a `TextInput`, such as [the minimal repro repo](https://github.com/CodingItWrong/rn-speech-to-text-bug), on iOS 16.2 (earlier iOS 16.x releases may have the issue too)
- Tap the text input
- On the iOS keyboard, tap the microphone icon
- Say something
- Tap the microphone icon again when done
- Not every time, but much of the time, the text will be entered twice.

### Snack, code example, screenshot, or link to a repository

- [Minimal repro repo](https://github.com/CodingItWrong/rn-speech-to-text-bug)
- Video of the bug happening on my first try:

https://user-images.githubusercontent.com/15832198/216072469-35d4c8bc-a6fc-4098-a212-4b870ec1f2f2.mov

(Device in use was a hardware iPhone 12)

**Comment by hareshtech** [comment]
here is the solution for this issue. 

Remove the **value** field in TextInput and check this. if you want to clear value then use reference of TextInput and clear value too. 

<TextInput
        editable
        onChangeText={text => onChangeText(text)}
        style={{padding: 10}}
      />


if you want to clear the value then use below code:
 texttInputRef.current?.clear()

**Comment by CodingItWrong** [comment]
@hareshtech If this workaround works, it doesn't provide a way to set the initial value of the TextInput, which is often necessary.

**Comment by jsworyk** [comment]
Also experiencing this issue on RN V 0.71.8

**Comment by fabriziobertoglio1987** [comment]
Do you still experience this issue? 

I have four years of experience maintaining facebook/react-native and I specialize in the Text and TextInput components. I currently have 58 [facebook/react-native PRs](https://github.com/facebook/react-native/pulls?q=is%3Apr+author%3Afabriziobertoglio1987+). 

If you still experience this issue, I will prepare a patched release with the fix.

Thanks a lot

**Comment by CodingItWrong** [comment]
Thank you for your offer. I migrated my project off of React Native, so I have not had the opportunity to check recently to see if this is still happening. Maybe @jsworyk has more recent info.

**Comment by jonathanh-goodmaps** [comment]
@fabOnReact We're still seeing this behavior in our app. We're on RN 0.70.8 but are planning to upgrade to the latest soon. I was hoping that the issue might be fixed as part of the update but it seems like that may not be true?

In the short term, I've removed the value field from our text input. In our case, we were using it to clear the entered text and we can do that with a ref.

If possible, it would be nice to have a fix for this so we're able to utilize the value field when using dictation. This poses certain issues with accessibility in particular if the user is reliant on text dictation.

**Comment by LeonelRiera** [comment]
I also figured out this happens when multiline={false}. But still, when multiline={true} it won't enter text twice but add a weird space.

**Comment by georgekal2798** [comment]
I also face the same issue. We have 3 different apps with versions 0.64.0, 0.72.7 and 0.78.2. We use [react-native-paper](https://github.com/callstack/react-native-paper)'s `TextInput`s but we tried with [react-native](https://github.com/facebook/react-native)'s `TextInput`s as well and the issue persists.

**Comment by DylanWard14** [comment]
This is still an issue. @fabOnReact did you end up looking into this?
