### ISSUE TITLE
react-native start not working in Examples

### ISSUE THREAD

**Issue by florianpnn** [facebook/react-native#3603]
I tried to play with the examples and got this error when I want to run the dev server.
It doesn't launch automatically from xCode either.

```
react-native/Examples/2048
$ react-native start
Command `start` unrecognized. Did you mean to run this inside a react-native project?
```

**Comment by jaygarcia** [comment]
Do you have the project properly bootstrapped? (cd to project dir and run `npm i` after cloning)


These steps work. :-\
```
jgarcia-15in:UIExplorer jgarcia$ cd ..
jgarcia-15in:Examples jgarcia$ cd 2048/
jgarcia-15in:2048 jgarcia$ npm start

> react-native@0.12.0 start /www/ios/react-native.fresh
> ./packager/packager.sh || true

 ┌────────────────────────────────────────────────────────────────────────────┐ 
 │  You are currently running io.js v2.3.3.                                   │ 
 │                                                                            │ 
 │  React Native runs on Node 4.0 or newer. There a
```

**Comment by jonathanngkh** [comment]
I'm having the exact same issue
```
Jonathans-MacBook-Air:2048 JonathanNg$ npm start

> react-native@0.12.0 start /Users/JonathanNg/Code/react-native
> react-native start || true

Command `start` unrecognized. Did you mean to run this inside a react-native project?
Jonathans-MacBook-Air:2048 JonathanNg$
```

When I try to run it on xcode, the packager comes up but terminates itself, with the error message saying 
```
/Users/JonathanNg/Code/react-native/packager/launchPackager.command: line 15: /Users/JonathanNg/Code/react-native/packager/packager.sh: No such file or directory
```

**Comment by florianpnn** [comment]
@jaygarcia I did `npm i` straight after cloning

**Comment by jaygarcia** [comment]
That tells me that bad something happened during install :(.  Maybe remove react-native npm module and re-install?

**Comment by florianpnn** [comment]
Things are getting weird if I try to uninstall :

```
react-native/Examples/2048
▶ npm ls | grep react
react-native@0.12.0 /Users/Florian/Development/react-native
│ ├── babel-plugin-react-constant-elements@1.0.3
│ ├── babel-plugin-react-display-name@1.0.3
├── eslint-plugin-react@3.3.1
├── react-timer-mixin@0.13.2
├─┬ react-tools@0.14.0-beta1 (git://github.com/facebook/react.git#b4e74e38e43ac53af8acd62c78c9213be0194245)

react-native/Examples/2048
▶ npm uninstall react-native
npm WARN uninstall not installed in /Users/Florian/Development/react-native/node_modules: "react-native"
```

**Comment by niftylettuce** [comment]
https://github.com/facebook/react-native/blob/master/Libraries/react-native/react-native.js#L20

Needs to be lowercase `react`?

**Comment by niftylettuce** [comment]
See <https://github.com/t4t5/react-native-router/issues/67>

**Comment by niftylettuce** [comment]
I'll submit a PR right now

**Comment by niftylettuce** [comment]
See <https://github.com/mjohnston/react-native-webpack-server/issues/50>

**Comment by jaygarcia** [comment]
Was this resolved?

**Comment by funerr** [comment]
I have this problem too. When I try to run `react-native start` in the UIExplorer folder I get: 
> Command `start` unrecognized. Did you mean to run this inside a react-native project

**Comment by niftylettuce** [comment]
@jaygarcia @funerr @florianpnn You can fix this by editing your `package.json`'s `start` command to look something like this:

```json
"start": "node node_modules/react-native/local-cli/cli.js start"
```

I'm on RN v0.17 so this might be different for you guys

**Comment by funerr** [comment]
My solutions was to fix it by installing cygwin and running: 
`cd package`
`sh package.sh`

**Comment by jsierles** [comment]
Each example has instructions on how to run the packager, using `./packager/packager.sh`.

https://github.com/facebook/react-native/tree/master/Examples/UIExplorer#running-on-ios

**Comment by NicoHinderling** [comment]
@jsierles Why does are the `react-native run-ios` and `react-native run-android` commands not functioning for the example apps?

I can build TicTacToe, for example, using Xcode but I'd love to know what the "missing piece" is that would make these commands work. Even directing me in the right direction would be wonderful 😁 thanks in advance!

**Comment by somanathtv** [comment]
i had similar issue "$ react-native start
Command `start` unrecognized" when i tried in windows command prompt. issue resolved by running commands in command prompt with "run ad administrator"
