### ISSUE TITLE
Build failed when upgrading to newer React-Native version 0.71.2

### ISSUE THREAD

**Issue by Malik-Usman17** [facebook/react-native#36047]
### Description

So I tried to update my existing react-native app (older version is 0.66.0) to the current version of react-native but now it was not working.
Give the below error when I am running my app.
`* What went wrong:
A problem occurred configuring root project 'CreekVista'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find com.facebook.react:react-native-gradle-plugin:.
     Required by:
         project :`

### Version

0.71.2

### Output of `npx react-native info`

warn Package react-native-vector-icons contains invalid configuration: "dependency.assets" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
warn Package rn-fetch-blob contains invalid configuration: "dependency.hooks" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
info Fetching system and libraries information...
error Unable to print environment info.
Error: Command failed: wmic os get Caption
'wmic' is not recognized as an internal or external command,
operable program or batch file.

### Steps to reproduce

`* What went wrong:
A problem occurred configuring root project 'CreekVista'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find com.facebook.react:react-native-gradle-plugin:.
     Required by:
         project :`

### Snack, code example, screenshot, or link to a repository

`* What went wrong:
A problem occurred configuring root project 'CreekVista'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find com.facebook.react:react-native-gradle-plugin:.
     Required by:
         project :`

**Comment by khadeshyam** [comment]
The above error  is saying that  'react-native-vector-icons' and 'rn-fetch-blob' packages contain invalid configuration and they are not linked properly .
Run "react-native config" command in the root directory of your project and verify linking of packages.

**Comment by cortinico** [comment]
> Could not find com.facebook.react:react-native-gradle-plugin:.

Can you share your `android/settings.gradle` file?

**Comment by wkwyatt** [comment]
I am getting a similar error when building 
`Could not find com.facebook.react:react-native:0.71.2.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/facebook/react/react-native/0.71.2/react-native-0.71.2.pom`

**Comment by Vibinreji** [comment]
> I am getting a similar error when building @cortinico
> 
> ```
> Could not find com.facebook.react:react-native:0.71.2.
>      Searched in the following locations:
>        - https://dl.google.com/dl/android/maven2/com/facebook/react/react-native/0.71.2/react-native-0.71.2.pom
> ```

same error i am getting.any solution?

**Comment by nagimule** [comment]
> > I am getting a similar error when building @cortinico
> > ```
> > Could not find com.facebook.react:react-native:0.71.2.
> >      Searched in the following locations:
> >        - https://dl.google.com/dl/android/maven2/com/facebook/react/react-native/0.71.2/react-native-0.71.2.pom
> > ```
> 
> same error i am getting.any solution?

Hi, apply plugin: "com.facebook.react"   Add this line for =>  android/app/build.grade file.

**Comment by nagimule** [comment]
apply plugin: "com.android.application"
apply plugin: "com.facebook.react"


---> android/app/build.grade

**Comment by Malik-Usman17** [comment]
> 

Sorry i didn't see your comment earlier, so here my settings.gradle file:
`rootProject.name = 'CreekVista'
include ':react-native-otp-verify'
project(':react-native-otp-verify').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-otp-verify/android')

include ':react-native-file-viewer'
project(':react-native-file-viewer').projectDir = new File(rootProject.projectDir, 	'../node_modules/react-native-file-viewer/android')

include ':rn-fetch-blob'
project(':rn-fetch-blob').projectDir = new File(rootProject.projectDir, '../node_modules/rn-fetch-blob/android')

// include ':react-native-vector-icons'
// project(':react-native-vector-icons').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-vector-icons/android')

// include ':react-native-vector-icons'
// project(':react-native-vector-icons').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-vector-icons/android')

apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
include ':app'
includeBuild('../node_modules/react-native-gradle-plugin')`

**Comment by nagimule** [comment]
See below screenshot
![Screenshot 2023-02-15 at 10 33 43 AM](https://user-images.githubusercontent.com/112949701/218936923-e221cad9-367b-40ee-a38b-6593dd15d421.png)
1) Add same as above.
2) Clean build folder then run

**Comment by nagimule** [comment]
> 

Add classpath("com.facebook.react:react-native-gradle-plugin") in your build.gradle file.
![Screenshot 2023-02-15 at 10 43 26 AM](https://user-images.githubusercontent.com/112949701/218938596-07187a00-718a-44bf-8310-15e6d5799c6b.png)

**Comment by cortinico** [comment]
Hey @Malik-Usman17
Your `settings.gradle` file looks correct. Could you share a reproducer?

**Comment by Malik-Usman17** [comment]
> Hey @Malik-Usman17 Your `settings.gradle` file looks correct. Could you share a reproducer?

Hello @cortinico thanks for the comment, and sorry didn't understand it about reproducer, what do you mean by that?

**Comment by Malik-Usman17** [comment]
> > 
> 
> Add classpath("com.facebook.react:react-native-gradle-plugin") in your build.gradle file. ![Screenshot 2023-02-15 at 10 43 26 AM](https://user-images.githubusercontent.com/112949701/218938596-07187a00-718a-44bf-8310-15e6d5799c6b.png)

I already did it, but no luck

**Comment by cortinico** [comment]
> Hello @cortinico thanks for the comment, and sorry didn't understand it about reproducer, what do you mean by that?

I would suggest to read this page: https://stackoverflow.com/help/minimal-reproducible-example
Plus what I'm asking is to create a new project with `npx react-native init` and edit it so it fails in your same way. Put it on Github to that I can look into it

**Comment by wkwyatt** [comment]
> > 
> 
> Add classpath("com.facebook.react:react-native-gradle-plugin") in your build.gradle file. ![Screenshot 2023-02-15 at 10 43 26 AM](https://user-images.githubusercontent.com/112949701/218938596-07187a00-718a-44bf-8310-15e6d5799c6b.png)

Would it be the same for kotlin?  Also, I have a slightly different build config as I am bringing in the RN project as part of an Android build.  Is that still the same configuration?

**Comment by nagimule** [comment]
> > > 
> > 
> > 
> > Add classpath("com.facebook.react:react-native-gradle-plugin") in your build.gradle file. ![Screenshot 2023-02-15 at 10 43 26 AM](https://user-images.githubusercontent.com/112949701/218938596-07187a00-718a-44bf-8310-15e6d5799c6b.png)
> 
> Would it be the same for kotlin? Also, I have a slightly different build config as I am bringing in the RN project as part of an Android build. Is that still the same configuration?

Yes

**Comment by wkwyatt** [comment]
https://github.com/facebook/react-native/issues/36047#issuecomment-1446326701

```
Could not resolve all files for configuration ':android:classpath'
     Could not find com.facebook.react:react-native-gradle-plugin:.
     Required by: project :android
```
Running into this when adding the rn gradle plugin to dependencies

**Comment by nagimule** [comment]
> [#36047 (comment)](https://github.com/facebook/react-native/issues/36047#issuecomment-1446326701)
> 
> ```
> Could not resolve all files for configuration ':android:classpath'
>      Could not find com.facebook.react:react-native-gradle-plugin:.
>      Required by: project :android
> ```
> 
> Running into this when adding the rn gradle plugin to dependencies

Add below line for settings.gradle file
 includeBuild('../node_modules/react-native-gradle-plugin')

**Comment by wkwyatt** [comment]
We have included the `react-native-gradle-plugin` and used the `implementation("com.facebook.react:react-android")`

But we are using the React Native module as a Android library.  Are there any docs that display how we should be changing our build files to accommodate the changes in 0.71.2?

**Comment by cortinico** [comment]
> But we are using the React Native module as a Android library. Are there any docs that display how we should be changing our build files to accommodate the changes in 0.71.2?

That's the upgrade helper:
https://react-native-community.github.io/upgrade-helper/?from=0.70.7&to=0.71.3

I'm also closing this as @Malik-Usman17 (the OP) is unresponsive.

Folks are commenting below diverging the discussion making it harder for us to follow through and to provide specific support. Please open separate issues if you're looking for specific support.
