### ISSUE TITLE
A blank space shows on screen after keyboard closed

### ISSUE THREAD

**Issue by phuongnguyenzoi** [facebook/react-native#36041]
### Description

As in the video, you can see after keyboard close, and navigating back, there's a blank space that match exactly the height of keyboard showing on the screen.

I suspect that this is because of react native version.
Just upgrade from 0.67.5 to 0.70.6 and this happen.

When I roll back the version in package.json ( not npm install yet ) the issue is not happen again

https://user-images.githubusercontent.com/110972245/216342981-7ce17605-a7be-4ac3-93db-9c2575ce9fd3.mov

### Version

^0.70.6

### Output of `npx react-native info`

em:
    OS: macOS 12.6.1
    CPU: (8) x64 Apple M1 Pro
    Memory: 26.19 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.17.3 - /usr/local/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 7.15.1 - /opt/homebrew/bin/npm
    Watchman: 2021.06.07.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 23, 26, 28, 29, 30, 31, 32, 33
      Build Tools: 28.0.3, 29.0.0, 29.0.2, 30.0.2, 30.0.3, 31.0.0
      System Images: android-28 | Google Play Intel x86 Atom, android-30 | ARM 64 v8a, android-30 | Google Play ARM 64 v8a, android-31 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: ^0.70.6 => 0.70.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

tech stack:
- React native navigation, text input
- From Screen A => navigate to B => open keyboard in B => close keyboard => navigate back to A
then the blank space shows

### Snack, code example, screenshot, or link to a repository

https://user-images.githubusercontent.com/110972245/216343911-a2e5b6c9-76a6-4f59-9b95-03671d715527.mov

**Comment by RamanDEEP225** [comment]
Has anyone found solution?

**Comment by T-Lukashevich** [comment]
Same problem

**Comment by haripatel-mobio** [comment]
Same problem with the multiple user are using iOS 16+, When user tap on numeric keyboard done button screen goes blank accept header and bottom bar.

**Comment by sammiepls** [comment]
Same issue for me, has anyone found a fix?
