### ISSUE TITLE
java.lang.NoClassDefFoundError: com.facebook.react.jscexecutor.JSCExecutor

### ISSUE THREAD

**Issue by mkui233** [facebook/react-native#36048]
### Description

![49E6F3D0-F5C0-4816-925A-27CC2FFD6A0A](https://user-images.githubusercontent.com/43899634/216554865-d663aa15-1808-4897-bc28-85659157237b.png)

### Version

0.71.1

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.22000
    CPU: (12) x64 Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
    Memory: 2.54 GB / 15.75 GB
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.11 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.22.0 - ~\AppData\Roaming\npm\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: AI-213.7172.25.2113.9123335
    Visual Studio: Not Found
  Languages:
    Java: 11.0.13 - C:\Program Files\Android\Android Studio\jre\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: ^0.71.1 => 0.71.1
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Integration with Existing Apps，First jump AppletActivity no problem，Return to the previous activity，Second jump AppletActivity  Errors

### Snack, code example, screenshot, or link to a repository

https://gitee.com/yangguizhong/issue

**Comment by onisaint** [comment]
e

**Comment by vtn-dev-manish** [comment]
+1

**Comment by mkui233** [comment]
try again

**Comment by vtn-dev-manish** [comment]
were you able to fix it?

**Comment by YangX29** [comment]
same problem

**Comment by mkui233** [comment]
将ReactInstanceManager放入ReactApplication的ReactNativeHost这样就不会崩溃，但是我没办法替换Bundle文件。

**Comment by vtn-dev-manish** [comment]
I had to disable hermes to resolve this issue.

**Comment by satheshrgs** [comment]
Is there any way without disabling hermes ?

**Comment by cipolleschi** [comment]
@cortinico Do you know what's happening here?

**Comment by bendaniel10** [comment]
I had this issue and I solved it by calling `.setJavaScriptExecutorFactory(HermesExecutorFactory())` on the object returned by `ReactInstanceManager.builder()`. This works if you're using `Hermes`

**Comment by piccinnigius** [comment]
> I had this issue and I solved it by calling `.setJavaScriptExecutorFactory(HermesExecutorFactory())` on the object returned by `ReactInstanceManager.builder()`. This works if you're using `Hermes`

thanks! this solved for me!

**Comment by satheshrgs** [comment]
> I had this issue and I solved it by calling `.setJavaScriptExecutorFactory(HermesExecutorFactory())` on the object returned by `ReactInstanceManager.builder()`. This works if you're using `Hermes`

Thanks! Working fine for me

**Comment by cortinico** [comment]
As mentioned, the problem is that you're not creating a `ReactInstanceManager` correctly. That's how the `ReactNativeHost` is doing it:

https://github.com/facebook/react-native/blob/6439baaca12f844b2192740bbaa5ee61edcba608/ReactAndroid/src/main/java/com/facebook/react/ReactNativeHost.java#L69-L84

You should either follow this pattern or use `DefaultReactNativeHost` as the template is doing which simplifies this setup for you

**Comment by master96** [comment]
> As mentioned, the problem is that you're not creating a `ReactInstanceManager` correctly. That's how the `ReactNativeHost` is doing it:
> 
> https://github.com/facebook/react-native/blob/6439baaca12f844b2192740bbaa5ee61edcba608/ReactAndroid/src/main/java/com/facebook/react/ReactNativeHost.java#L69-L84
> 
> You should either follow this pattern or use `DefaultReactNativeHost` as the template is doing which simplifies this setup for you

This worked for me also for those still facing issue on 0.71.2 

```
reactInstanceManager = ReactInstanceManager.builder().setJavaScriptExecutorFactory(new HermesExecutorFactory()).setApplication(activity.getApplication())
                    .setCurrentActivity(activity).setBundleAssetName("index.android.bundle")
                    .setJSMainModulePath("index.android").addPackages(this.getPackages(_env.getValue()))
                    .setUseDeveloperSupport(BuildConfig.DEBUG).setInitialLifecycleState(LifecycleState.RESUMED).build();
```

This worked more me.

**Comment by sanjeevyadavIT** [comment]
Hi @cortinico I am also facing the same issue after upgrading RN from `0.63.4` to `0.70.7` and I have not enabled new architecture and hermes is enabled, but I am not creating `reactInstanceManager` manually anywhere, all I am doing is creating `ReactNativeHost` manually, not able to figure out the issue

Error
```
Fatal Exception: java.lang.NoClassDefFoundError: com.facebook.react.jscexecutor.JSCExecutor
       at com.facebook.react.ReactInstanceManagerBuilder.getDefaultJSExecutorFactory(ReactInstanceManagerBuilder.java:387)
       at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:343)
       at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:96)
       at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:42)
       at com.facebook.react.ReactDelegate.loadApp(ReactDelegate.java:104)
       at com.facebook.react.ReactDelegate.loadApp(ReactDelegate.java:95)

Caused by java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libjscexecutor.so
	SoSource 0: com.facebook.soloader.a[root = /data/data/in.mohalla.sharechat/lib-main flags = 1]
	SoSource 1: com.facebook.soloader.a[root = /data/data/in.mohalla.sharechat/lib-0 flags = 1]
	SoSource 2: com.facebook.soloader.a[root = /data/data/in.mohalla.sharechat/lib-1 flags = 1]
	SoSource 3: com.facebook.soloader.a[root = /data/data/in.mohalla.sharechat/lib-2 flags = 1]
	SoSource 4: com.facebook.soloader.a[root = /data/data/in.mohalla.sharechat/lib-3 flags = 1]
	SoSource 5: com.facebook.soloader.a[root = /data/data/in.mohalla.sharechat/lib-4 flags = 1]
	SoSource 6: com.facebook.soloader.a[root = /data/data/in.mohalla.sharechat/lib-5 flags = 1]
	SoSource 7: com.facebook.soloader.a[root = /data/data/in.mohalla.sharechat/lib-6 flags = 1]
	SoSource 8: com.facebook.soloader.a[root = /data/data/in.mohalla.sharechat/lib-7 flags = 1]
	SoSource 9: com.facebook.soloader.a[root = /data/data/in.mohalla.sharechat/lib-8 flags = 1]
	SoSource 10: com.facebook.soloader.a[root = /data/data/in.mohalla.sharechat/lib-9 flags = 1]
	SoSource 11: com.facebook.soloader.a[root = /data/data/in.mohalla.sharechat/lib-10 flags = 1]
	SoSource 12: com.facebook.soloader.a[root = /data/data/in.mohalla.sharechat/lib-11 flags = 1]
	SoSource 13: com.facebook.soloader.a[root = /data/data/in.mohalla.sharechat/lib-12 flags = 1]
	SoSource 14: com.facebook.soloader.d[root = /data/app/~~onGKrhQHmv1cUu3oD3wUNg==/in.mohalla.sharechat-zJfOG0Nh5A0BGLIJ6DQN7w==/lib/arm64 flags = 0]
	SoSource 15: com.facebook.soloader.d[root = /system/lib64 flags = 2]
	SoSource 16: com.facebook.soloader.d[root = /vendor/lib64 flags = 2]
	Native lib dir: /data/app/~~onGKrhQHmv1cUu3oD3wUNg==/in.mohalla.sharechat-zJfOG0Nh5A0BGLIJ6DQN7w==/lib/arm64
 result: 0
       at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:1132)
       at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:948)
       at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:860)
       at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:807)
       at com.facebook.react.jscexecutor.JSCExecutor.<clinit>(JSCExecutor.java:3)
       at com.facebook.react.ReactInstanceManagerBuilder.getDefaultJSExecutorFactory(ReactInstanceManagerBuilder.java:387)
       at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:343)
       at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:96)
       at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:42)
```

Code
```
@Provides
    @Singleton
    internal fun getReactNativeHost(...): ReactNativeHost {

        return object : ReactNativeHost(application) {
            override fun getPackages(): List<ReactPackage> {....}

            override fun getUseDeveloperSupport(): Boolean {
                return appBuildConfig.DEBUG
            }

            override fun getJSBundleFile(): String? {
                return CodePush.getJSBundleFile()
            }

            override fun createReactInstanceManager(): ReactInstanceManager {
                return super.createReactInstanceManager()
            }
        }
    }
```

**Comment by cortinico** [comment]
> Hi @cortinico I am also facing the same issue after upgrading RN from `0.63.4` to `0.70.7`

Please open a separate issue + provide a reproducer using the default template and we can look into it

**Comment by bendaniel10** [comment]
@sanjeevyadavIT in your case, because you've overriding the `ReactNativeHost`, you can specify the `HermesExecutorFactory()` like this:

```
        object : ReactNativeHost(activity.application) {
            ...
            override fun getJavaScriptExecutorFactory() = HermesExecutorFactory() // <-- override this and set.
        }
```
