### ISSUE TITLE
Controlled TextInput duplicates dictated text in iOS 16

### ISSUE THREAD

**Issue by jpdriver** [facebook/react-native#36045]
### Description

- When trying to use dictation with a controlled `<TextInput />` in iOS 16, entered text is duplicated
- This issue does not affect iOS 15
- This issue does not affect uncontrolled `<TextInput />`s
- Text seems to be being duplicated within native code
  - by the time an `onChangeText` callback is called, the incoming `text` contains the duplication
- Originally noticed on RN 0.68.2 but confirmed it is still happening with latest (0.71.2 at time of writing)

### Version

0.71.2

### Output of `npx react-native info`

```
info Fetching system and libraries information...
System:
    OS: macOS 13.2
    CPU: (10) arm64 Apple M1 Max
    Memory: 992.61 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.1.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.3 - /opt/homebrew/bin/npm
    Watchman: 2022.11.14.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9477386
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.2 => 0.71.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

- tap a controlled `<TextInput />` on iOS 16
- dictate something

## Snack

https://snack.expo.dev/@jpmigueldriver/dictation-dictation

### iOS 15
- demonstrates expected behaviour
- no difference between controlled vs. uncontrolled

https://user-images.githubusercontent.com/2393035/216429025-27e6b28f-c56a-4e0e-b918-6f0fb77074b9.MP4

### iOS 16
- uncontrolled input works as expected
- controlled input duplicates dictated text

https://user-images.githubusercontent.com/2393035/216429413-e96eacf1-1056-444a-89f2-fee0cbe11f44.MP4

**Comment by mog3n** [comment]
A lot of our users use dictation and this is also happening with our controlled textinput as well.

**Comment by fabriziobertoglio1987** [comment]
https://user-images.githubusercontent.com/24992535/235432612-8a333e2a-beb0-40d9-8452-05d52d2feef4.mp4

**Comment by jpdriver** [comment]
@fabriziocucci I think it depends how the keyboard dictation behaves.

In both my original iOS 15 video and your iOS 16.4 video, the keys on the keyboard disappear. Whenever this happens, everything seems to work as expected.

**But** if you're using dictation where the keys remain visible then the issue seems to appear..??

I thought this was something introduced with iOS 16 -- but could it maybe be a regional thing..??

I also had one other thought -- can you try tapping the microphone in the bottom right to stop dictation, instead of the inline tooltip?

I guess there are multiple ways of stopping dictation and inserting the text 😅

**Comment by fabriziobertoglio1987** [comment]
https://github.com/Expensify/App/issues/17174#issuecomment-1534278842

**Comment by Letty** [comment]
Is there a reason why the PR is not part of the releases? I see the changes on `main` but none of the released versions have the file changes and the bug is still reproduceable.

**Comment by jpdriver** [comment]
Only because a new release hasn't been cut since this commit (https://github.com/facebook/react-native/commit/e8b4bb0684eed2acdb4648205893ee372f7ac1c7) was merged.

It should be included in 0.73+

**Comment by Letty** [comment]
Thank you for pointing out the discussion! <3 Would have thought this is possibly a hotfix, since it is a crutial part over most apps.
I guess patching react-native would be the best for pre 0.73 versions.

**Comment by ehabhosam** [comment]
I was working on a react native project where I have a feature that consumes the dictation and I faced the same issue on iOS only.

I found a very simple solution that fixes this bug: 

`function handleTextChange(text) {
    if (text.length - value.length > 10) return;
    onChange(text);
  }` 

It's of course not the best solution, but it's good for now until I find a better one.

**Comment by jgillick** [comment]
> I can not reproduce it on iOS 16.4.
> 
>  2023-05-01.17-02-03.mp4

In my tests, this only happens when the `multiline` prop is `false`.

**Comment by jgillick** [comment]
> I'm working on a react native project where I have a feature that consumes the dictation and I faced the same issue on iOS only.
> 
> I found a very simple solution that overcomes this bug:
> 
> `function handleTextChange(text) { if (text.length - value.length > 10) return; onChange(text); }`
> 
> It's of course not the best solution, but it's good for now until I find a better one.

How is `value` being set?

**Comment by jgillick** [comment]
It looks like React Native 0.73 fixes this issue. I just did a cursory check on my end. Can anyone else confirm this?

**Comment by svdgoor** [comment]
Still happens. This issue should be reopened.
