### ISSUE TITLE
0.71.2 still uses Hermes in android even after disabling it

### ISSUE THREAD

**Issue by rajeshrasch** [facebook/react-native#36059]
### Description

Hi team,

I am using the latest React Native version at this time which is 0.71.2, I have disabled the hermes flag from gradle.properties

`# Use this property to enable or disable the Hermes JS engine.
# If set to false, you will be using JSC instead.
hermesEnabled=false`

But still i see its being enabled because i am seeing bytecode issue when used to .toString() approach

This is fine in IOS with disabled hermes flag however in android i am facing this issue. Could you please help me out here

### Version

0.71.2

### Output of `npx react-native info`

1 gradle.properties disable hermes adding the flag
`hermesEnabled=false`

One can still its using hermes even though the implementation is going from JSC

### Steps to reproduce

1 gradle.properties disable hermes adding the flag
`hermesEnabled=false`

One can still its using hermes even though the implementation is going from JSC

### Snack, code example, screenshot, or link to a repository

na

**Comment by rajeshrasch** [comment]
Looks like some other config issue from my end this is working as expected. Sorry for the confusion around

**Comment by harendrasaini01** [comment]
After disabling the Hermes , So loader error is coming and App throw the ANR.

**Comment by pokhiii** [comment]
@chenop How did you resolve it?
