### ISSUE TITLE
Getting Soloader(DSO) issue from play console, but I haven't written anywhere Soloader version,

### ISSUE THREAD

**Issue by vaish8529** [facebook/react-native#36054]
### Description

https://stackoverflow.com/questions/75343583/getting-soloaderdso-issue-from-play-console-but-i-havent-written-anywhere-so

### Version

0.63.3

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
OS: Windows 10 10.0.22621
CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-12650H
Memory: 5.91 GB / 15.68 GB
Binaries:
Node: 14.20.1 - C:\Program Files\nodejs\node.EXE
Yarn: Not Found
npm: 6.14.17 - C:\Program Files\nodejs\npm.CMD
Watchman: Not Found
SDKs:
Android SDK:
API Levels: 29, 30, 31, 33
Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0, 33.0.0
System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64, android-30 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-31 | Intel x86 Atom_64, android-31 | Google APIs ARM 64 v8a, android-31 | Google APIs Intel x86 Atom_64, android-33 | Google APIs ARM 64 v8a, android-33 | Google APIs Intel x86 Atom_64, android-33 | Google Play Intel x86 Atom_64
Android NDK: Not Found
Windows SDK: Not Found
IDEs:
Android Studio: AI-213.7172.25.2113.9014738
Visual Studio: Not Found
Languages:
Java: 11.0.16 - C:\Program Files\Common Files\Oracle\Java\javapath\javac.EXE
Python: Not Found
npmPackages:
@react-native-community/cli: Not Found
react: 16.13.1 => 16.13.1
react-native: 0.63.3 => 0.63.3
react-native-windows: Not Found
npmGlobalPackages:
react-native: Not Found

### Steps to reproduce

Crash reports on Play Console

### Snack, code example, screenshot, or link to a repository

![3](https://user-images.githubusercontent.com/105700183/216760811-aca10d96-cb1b-46a3-beb3-a029be9ed2eb.png)

**Comment by iBotPeaches** [comment]
@vaish8529 - Sadly RN 63 is very old and out of scope for support. A good few years of upgrades you are missing out on there.

https://github.com/reactwg/react-native-releases#which-versions-are-currently-supported
