### ISSUE TITLE
Exporting constants from iOS TurboModule

### ISSUE THREAD

**Issue by birdofpreyru** [facebook/react-native#36057]
### Description

Hi. Not sure is it a bug, an overlook in the current documentation, or me missing something; but I just bumped into the following issue with exporting constants from a TurboModule on iOS.

I had a native module exporting constants as [said here](https://reactnative.dev/docs/next/native-modules-ios#exporting-constants) (for old arch): it overrode `- (NSDictionary *)constantsToExport`, and all worked fine. I am migrating it to the new arch,  with backward compatibility. When I build it and run in compatibility mode (old arch) - it still works fine; if I build and run for new arch - no constants are exported (I checked, `constantsToExport` is never called, and on JS side `getConstants()` returns `null`). I looked into RN documentation, have not found any mentions of changes in exporting constants for iOS TurboModules, nor in the New Arch sections, nor in Migration to the New Arch sections. I looked into the generated Specs for my TurboModule, it has these both:
```
- (facebook::react::ModuleConstants<JS::NativeReactNativeStaticServer::Constants::Builder>)constantsToExport;
- (facebook::react::ModuleConstants<JS::NativeReactNativeStaticServer::Constants::Builder>)getConstants;
```
thus I've tried to override `getConstants` method instead, and it then works fine for the new arch. But leaves me confused: if we are supposed to override `getConstants` instead of `constantsToExport` in the new arch, why the previous `constantsToExport` is still in specs? If not, why the override is not called - a bug? And why nothing is mentioned in the docs in this regard, am I missing something here?

### Version

0.71.2

### Output of `npx react-native info`

N/A

### Steps to reproduce

N/A

### Snack, code example, screenshot, or link to a repository

N/A

**Comment by cortinico** [comment]
> If not, why the override is not called - a bug? And why nothing is mentioned in the docs in this regard, am I missing something here?

Can you share your spec file? Also a reproducer would help here to debug what's going on

**Comment by birdofpreyru** [comment]
Hey @cortinico , I just wanna say, I still remember about this issue I reported, but I had no time yet to look into creating a minimal reproducer.

Though, the library I am working on is public, here: https://github.com/birdofpreyru/react-native-static-server, and the piece of code which I was refering to is this one: https://github.com/birdofpreyru/react-native-static-server/blob/3bd511dbb70bb3fc18b7b346af0db9a83c6602f8/ios/ReactNativeStaticServer.mm#L26-L36

```objective-c
- (NSDictionary*) constantsToExport {
  return @{
    @"CRASHED": CRASHED,
    @"LAUNCHED": LAUNCHED,
    @"TERMINATED": TERMINATED
  };
}

- (NSDictionary*) getConstants {
  return [self constantsToExport];
}
```

as I said, from the docs it sounds like just having `constantsToExport()` should make it work, but in my experience with the new arch the JS side actually calls `getConstants()` instead, thus I had to add that method.

**Comment by ospfranco** [comment]
I'm trying to export constants from my Turbo Module on RN 0.73 and `- (NSDictionary *) getConstants` is not working for me. I don't quite understand the generated code, so not sure how to create an instance of the generated constants struct:

<img src="https://github.com/facebook/react-native/assets/1634213/4eed9147-554e-412b-8dc1-05295cf80c7f" width="200"/>

Any help would be greatly appreciated

**Comment by ospfranco** [comment]
Codegen doesn't seem to be generating any initialization code, just another method

Here is my spec

```ts
import { TurboModuleRegistry, TurboModule } from 'react-native';

export interface Spec extends TurboModule {
  getConstants: () => {
    IOS_DOCUMENT_PATH: string;
    IOS_LIBRARY_PATH: string;
    ANDROID_DATABASE_PATH: string;
    ANDROID_FILES_PATH: string;
    ANDROID_EXTERNAL_FILES_PATH: string;
  };

  install(): boolean;
}

export default TurboModuleRegistry.getEnforcing<Spec>('OPSQLite');
```
Here is the generated code

```objective-c
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleObjCpp
 *
 * We create an umbrella header (and corresponding implementation) here since
 * Cxx compilation in BUCK has a limitation: source-code producing genrule()s
 * must have a single output. More files => more genrule()s => slower builds.
 */

#import "OPSQLiteSpec.h"


namespace facebook {
  namespace react {
    
    static facebook::jsi::Value __hostFunction_NativeOPSQLiteSpecJSI_install(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, BooleanKind, "install", @selector(install), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeOPSQLiteSpecJSI_getConstants(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, ObjectKind, "getConstants", @selector(getConstants), args, count);
    }

    NativeOPSQLiteSpecJSI::NativeOPSQLiteSpecJSI(const ObjCTurboModule::InitParams &params)
      : ObjCTurboModule(params) {
        
        methodMap_["install"] = MethodMetadata {0, __hostFunction_NativeOPSQLiteSpecJSI_install};
        
        
        methodMap_["getConstants"] = MethodMetadata {0, __hostFunction_NativeOPSQLiteSpecJSI_getConstants};
        
    }
  } // namespace react
} // namespace facebook

```

**Comment by ospfranco** [comment]
It seems on Android the generated code is different and getConstants is shared between the old-arch and codegen, but this is also means it is not overridable and will not work when creating modules that keep compatibility

<img src="https://github.com/facebook/react-native/assets/1634213/5869d593-50b4-45ce-8eaa-ec0437f6f163" width="400"/>

**Comment by birdofpreyru** [comment]
Can’t keep myself from saying — auto-closing issues by GitHub actions is stupid and harmful — hiding dirt under the carpet doesn’t help solving the issue, if the issue remained open and visible, perhaps it helped to avoid degrading the constant problem even further 🤷‍♂️

**Comment by ospfranco** [comment]
The amount of rubbish issues is hard to manage in a repo like react-native, I have sympathy for the maintainers. I think I will create a new issue. I managed to get it working on Android by just implementing the `getTypedConstants` method. But in any case, the documentation is missing. I also found this small disclaimer on the old arch modules page:

![Oscar Franco Screen 000515](https://github.com/facebook/react-native/assets/1634213/272e6ad7-debc-4d8e-a1ae-7771839b23ef)

**Comment by cortinico** [comment]
> The amount of rubbish issues is hard to manage in a repo like react-native, I have sympathy for the maintainers.

That's the underlying problem @birdofpreyru 

If the issue gets stale and closed by the bot, let's open a new one. If an issue has a a linked reproducer, it won't stale.
Honestly we receive so many bugs that we can't cope with the traffic so that's a necessary measure.

@ospfranco let's create a new issue for your particular case. We're specifically prioritizing New Architecture bugs as of now, so this would be really precious

**Comment by ospfranco** [comment]
ok, awesome, will create later

**Comment by birdofpreyru** [comment]
Hmm... I am working on migrating [my up-to-date fork of `react-native-fs`](https://github.com/birdofpreyru/react-native-fs/tree/dev-2.22) to RN v0.73; I just got it working for Android with both new and old archs, and I haven't noticed any significant issues with constants so far (beside a lack of documentation in RN web).

On TS side I have the constants method defined as `getConstants()`. Codegen seems to work fine and for new arch it generates me the specs like:
```java
protected abstract Map<String, Object> getTypedExportedConstants();

@Override
@DoNotStrip
public final @Nullable Map<String, Object> getConstants() {
  Map<String, Object> constants = getTypedExportedConstants();
  // Here codegen adds a bunch of assertion code for debug & internal builds.
  return constants;
}

```
so I just implement `getTypedExportedConstants()` function, and for the old arch I have a stub specs file that just does:
```kotlin
  abstract fun getTypedExportedConstants(): Map<String, Object>

  override fun getConstants(): Map<String, Any>? {
    return getTypedExportedConstants()
  }
```
So far so good, very curious to see how (whether) it will work for me with iOS.

**Comment by birdofpreyru** [comment]
Yeah, works fine for me with RN v0.73 on iOS, macOS, and Windows as well. I mean, there is no behavior changes from v0.72 to v0.73, only pre-existing issues with logic (which can be worked around) and documentation.

**Comment by ospfranco** [comment]
I also managed to get it working, there is just a lot of disparity and missing info in the documentation. @cortinico do you still want me to create a new issue?
