### ISSUE TITLE
Touchable opacity not work randomly 1-5 days and it work later on iOS only

### ISSUE THREAD

**Issue by ldrive-company** [facebook/react-native#36063]
### Description

Touchable opacity not work randomly 1-5 days and it work later on iOS only please see the steps below for more details

1. download app from app store (iOS) and install
2. touchable opacity work well 
3. in some week later touchable opacity in app not working
4. when facing the issue in app store, we facing it on development mode in same time
5. not found any log error in console
6. do nothing ~ 1-5 days
7. the issue disappear, app work fine both of app store and development mode
8. the issue will be back 3-4 time in 5 months

NOTE: last time of issue occur about 25 jan 2023 - 1 feb 2023 (iOS only)

I known this issue is not make sense, please help me to guess some possible cause of the issue

### Version

0.64.2

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 12.6.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 359.25 MB / 16.00 GB
    Shell: 5.8 - /usr/local/bin/zsh
  Binaries:
    Node: 16.19.0 - ~/.asdf/installs/nodejs/16.19.0/bin/node
    Yarn: Not Found
    npm: 8.19.3 - ~/.asdf/plugins/nodejs/shims/npm
    Watchman: 2023.01.16.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 28, 29, 30, 31, 33
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 33.0.1
      System Images: android-25 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_275 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.64.2 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

do not thing this issue occurring at some week and disappear in 1-5 days later.

### Snack, code example, screenshot, or link to a repository

import { TouchableOpacity } from 'react-native'

I use this component

**Comment by iBotPeaches** [comment]
> I known this issue is not make sense, please help me to guess some possible cause of the issue

You render the components in an odd order that messes with the touchable? You use absolute positioning on it but draw it first? Some race condition makes component x slower than y temporarily to expose issue?

Who knows.

You are a few years out of date and out of scope though, so I doubt you'll get any help until you upgrade further - https://github.com/reactwg/react-native-releases#which-versions-are-currently-supported. RN64 is no longer support.

**Comment by necolas** [comment]
Closing this as it's old, has no test case, isn't using a supported version of React Native, and there is a similar report (#36710) that will track any potential issue with the press logic
