### ISSUE TITLE
Appearance.getColorScheme() doesn't return the correct color scheme

### ISSUE THREAD

**Issue by j-jonathan** [facebook/react-native#36061]
### Description

Appearance.getColorScheme() function doesn't always return the correct value after the user has switched from one theme to another (eg: from dark theme to light theme) and changes the orientation of the phone.

The bug is on Android 11, 12, 13 (not previous versions nor iOS).

From what i've seen, the issue is that `context.getResources().getConfiguration().uiMode & Configuration.UI_MODE_NIGHT_MASK` in `react-native/ReactAndroid/src/main/java/com/facebook/react/modules/appearance/AppearanceModule.java` doesn't return the correct theme.

### Version

0.71.2

### Output of `npx react-native info`

❯ npx react-native info
info Fetching system and libraries information...
System:
    OS: macOS 13.0
    CPU: (10) arm64 Apple M1 Pro
    Memory: 37.31 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    Yarn: Not Found
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
    Watchman: 2022.09.05.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9477386
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16.1 - /Users/jonathan/.sdkman/candidates/java/current/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.2 => 0.71.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. Create an empty react native project

```bash
npx react-native init
```

2. Edit the app.tsx. Here is a simple example to get the value of Appearance.getColorScheme() each second.

```tsx
import React, {useEffect} from 'react';
import {Appearance, Text, View} from 'react-native';

function App(): JSX.Element {
  const [colorScheme, setColorScheme] = React.useState(
    Appearance.getColorScheme(),
  );

  useEffect(() => {
    const interval = setInterval(() => {
      setColorScheme(Appearance.getColorScheme());
    }, 1000);
    return () => clearInterval(interval);
  }, []);

  const isDarkMode = colorScheme === 'dark';

  return (
    <View style={{flex: 1, backgroundColor: isDarkMode ? 'black' : 'white'}}>
      <Text style={{color: isDarkMode ? 'white' : 'black'}}>
        isDarkMode: {isDarkMode ? 'true' : 'false'}
      </Text>
    </View>
  );
}

export default App;
```

3. Add in MainActivity.java the code to enable phone orientation support

```java
@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_SENSOR);
}
```

### Snack, code example, screenshot, or link to a repository

Repository to reproduce the issue: https://github.com/j-jonathan/react-native-uimode-issue

https://user-images.githubusercontent.com/78229184/216827509-6488aeaa-f51b-422c-ac77-261e1dee2a78.mp4

Here you can see that at 0:22 / 0:34 the Appearance.getColorScheme() value changes when I just changed the orientation of the phone.

**Comment by carlosalmonte04** [comment]
I was able to replicate this. You can try using the event listener from `Appearance.addChangeListener` like the code below. It updated properly, including after updating theme while app in background.

``` javascript
function App(): JSX.Element {
  const [colorScheme, setColorScheme] = React.useState(
    Appearance.getColorScheme(),
  );

  useEffect(() => {
    Appearance.addChangeListener(({colorScheme}) => setColorScheme(colorScheme));
  }, []);

  const isDarkMode = colorScheme === 'dark';

  return (
    <View style={{flex: 1, backgroundColor: isDarkMode ? 'black' : 'white'}}>
      <Text style={{color: isDarkMode ? 'white' : 'black'}}>
        isDarkMode: {isDarkMode ? 'true' : 'false'}
      </Text>
    </View>
  );
}
```

**Comment by izichtl** [comment]
> ```js
> function App(): JSX.Element {
>   const [colorScheme, setColorScheme] = React.useState(
>     Appearance.getColorScheme(),
>   );
> 
>   useEffect(() => {
>     Appearance.addChangeListener(({colorScheme}) => setColorScheme(colorScheme));
>   }, []);
> 
>   const isDarkMode = colorScheme === 'dark';
> 
>   return (
>     <View style={{flex: 1, backgroundColor: isDarkMode ? 'black' : 'white'}}>
>       <Text style={{color: isDarkMode ? 'white' : 'black'}}>
>         isDarkMode: {isDarkMode ? 'true' : 'false'}
>       </Text>
>     </View>
>   );
> }
> ```

I have the same issue, try this and not work on iOS 15

**Comment by carlosalmonte04** [comment]
> > ```js
> > function App(): JSX.Element {
> >   const [colorScheme, setColorScheme] = React.useState(
> >     Appearance.getColorScheme(),
> >   );
> > 
> >   useEffect(() => {
> >     Appearance.addChangeListener(({colorScheme}) => setColorScheme(colorScheme));
> >   }, []);
> > 
> >   const isDarkMode = colorScheme === 'dark';
> > 
> >   return (
> >     <View style={{flex: 1, backgroundColor: isDarkMode ? 'black' : 'white'}}>
> >       <Text style={{color: isDarkMode ? 'white' : 'black'}}>
> >         isDarkMode: {isDarkMode ? 'true' : 'false'}
> >       </Text>
> >     </View>
> >   );
> > }
> > ```
> 
> I have the same issue, try this and not work on iOS 15

It's working fine for me on iOS.

https://user-images.githubusercontent.com/25206487/219064353-5b7832c5-903f-4fed-8cd4-665b3ee838a9.mov

**Comment by izichtl** [comment]
Hey @carlosalmonte04, i forgot to delete it, i had disabled dark mode in build settings, then it worked ok.

sorry
