### ISSUE TITLE
[Android][NewArch][0.71.2]java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libapp_appmodules.so

### ISSUE THREAD

**Issue by MonsterDonkey** [facebook/react-native#36064]
### Description

App works normally in version rn-v0.70.6
After upgrade to v0.71.2, the app crashed
soLoader version: 0.10.4

### Version

0.71.2

### Output of `npx react-native info`

System:
    OS: macOS 12.6
    CPU: (8) x64 Apple M1
    Memory: 272.49 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - /usr/local/opt/node@16/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.5.0 - /usr/local/opt/node@16/bin/npm
    Watchman: 2022.03.21.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 23, 28, 29, 30, 31, 32, 33
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0
      System Images: android-32 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.14 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.71.2 => 0.71.2
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. upgrade package.json rn version to 0.71.2
2. modified the app/build.gradle and project/settings.gradle(https://github.com/facebook/react-native/blob/main/template/android/app/build.gradle)
3. clear all caches
4. rebuild debug module

### Snack, code example, screenshot, or link to a repository

<img width="1418" alt="image" src="https://user-images.githubusercontent.com/19199671/216933272-e727f55b-2005-4ca2-b8e2-ba2ddca66335.png">

**Comment by MonsterDonkey** [comment]
MainApplicationTurboModuleManagerDelegate.java load app_appmodules

**Comment by MonsterDonkey** [comment]
update Mainapplication.java and remove new arch folder, work fine.

**Comment by atn508** [comment]
can you explain your solution?

What is arch folder? where is it?

@MonsterDonkey
