### ISSUE TITLE
{flex:1} gets ignored on ScrollView

### ISSUE THREAD

**Issue by getsetbro** [facebook/react-native#3606]
See here: https://rnplay.org/apps/avReqQ

**Comment by mkonicek** [comment]
There are two ScrollViews in your example? Can you be more specific / provide a minimal repro?

**Comment by getsetbro** [comment]
The app above works for me in latest FF and Chrome but not Safari. If you cannot view it here is a gist that I pasted: https://gist.github.com/getsetbro/fd587a8b334b744765ed

**Comment by ms88privat** [comment]
not sure about this, but I think you are missing a style property with flex: 1 on the scrollview itself

**Comment by getsetbro** [comment]
It has 'flex: 2' so it should take up more than half of the space.

**Comment by ms88privat** [comment]
@getsetbro flex: 2 is for the contentContainer and not for the scrollviw itself? But I'm not sure about this right now. Try adding style={{flex: 1}} to the ScrollView in addition to contentContainerSytle!

**Comment by ms88privat** [comment]
Ok. I missed the playground app. I have absolutely no idea what you are trying to archive. Please be more specific about your Goal :)

**Comment by getsetbro** [comment]
I'd like the ScrollView to take up more than half of the space.

**Comment by ms88privat** [comment]
@getsetbro Ok, here you go: <ScrollView style={{flex: 2}} contentContainerStyle={styles.r1}

Like i said, the ScrollView need a style property by itself! Hope this fixes your issue :)

**Comment by getsetbro** [comment]
Alright thanks. I didn't understand that it would only work if inline. Is that documented? Will that change?

**Comment by ms88privat** [comment]
@getsetbro no, it is not like that. You can do it like <ScrollView style={styles.rX} contentContainerStyle={styles.r1}>

The important part is, that the ScrollView has the style property and the Container of the ScrollView (which will get added automatically) has the contentContainerStyle if needed.
