### ISSUE TITLE
Text input spell check is not working on some Android and iOS devices

### ISSUE THREAD

**Issue by wasiquehaider** [facebook/react-native#36072]
### Description

Text input spell check is not working on some Android and iOS devices in our React Native app. The issue affects both Android and iOS versions of the app.

### Actual behavior
On some Android and iOS devices, the spell check is not working, making it difficult for users to correct spelling mistakes.

### Expected behavior
The text input spell check should be working on all Android and iOS devices, allowing users to easily identify and correct spelling mistakes.

### Environment
React Native version: 0.70.0
React: 18.1.0
Affected Android devices: [Samsung A52, Android 13, Huawei Y9 Prime, Android 10  ]
Affected iOS devices: [IPhone 14 Pro Max, IOS 16, IPhone 6S Plus, IOS 15.5]

### Additional context
We are using react-native-paper: "5.0.0-rc.5", in which we have experienced this issue, we tried to reproduce it on default TextInput from react native as well but the issue remains same. 

### Version

0.70.0

### Output of `npx react-native info`

System:
    OS: macOS 12.6.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Memory: 104.30 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.20.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 6.14.17 - /usr/local/bin/npm
    Watchman: 2022.11.28.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/digitaldividend/.rvm/gems/ruby-2.7.5/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.0 => 0.70.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce
Launch the React Native app on an affected Android or iOS device.
Attempt to use the text input feature.
Observe that spell check is not functioning as expected.

### Snack, code example, screenshot, or link to a repository

```
<TextInput
        testID="@test-TextInput"
        autoCapitalize={'words'}
        spellCheck={true}
        editable={editable}
        label={placeholder}
        value={text}
        onChangeText={onChangeHandler}
        mode="flat"
        theme={{
          roundness: 5,
          colors: {primary: '#003E51', placeholder: '#fff', text: '#fff'},
        }}
        style={[customStyle.input, disabled && customStyle.inputDisabled]}
        left={
          iconLeft && <TextInput.Icon icon={iconLeft} size={iconLeftSize} />
        }
        right={
          iconRight && <TextInput.Icon icon={iconRight} size={iconRightSize} />
        }
      />
```

**Comment by fabriziobertoglio1987** [comment]
Do you still experience this issue? 

I have four years of experience maintaining facebook/react-native and I specialize in the Text and TextInput components. I currently have 58 [facebook/react-native PRs](https://github.com/facebook/react-native/pulls?q=is%3Apr+author%3Afabriziobertoglio1987+). 

If you still experience this issue, I will prepare a patched release with the fix.

Thanks a lot
