### ISSUE TITLE
Unknown Error 

### ISSUE THREAD

**Issue by Rananjaya** [facebook/react-native#36073]
### Description

I have this Unknown error when run react-native run-android
![Screenshot_1675707456](https://user-images.githubusercontent.com/34897947/217053421-e731c78d-b446-41d6-b94f-f73a65b05bda.png)

### Version

~0.63.4

### Output of `npx react-native info`

System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i3-10100 CPU @ 3.60GHz
    Memory: 1.68 GB / 15.87 GB
  Binaries:
    Node: 14.17.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.11 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowAllTrustedApps: Enabled
      AllowDevelopmentWithoutDevLicense: Enabled
  IDEs:
    Android Studio: Version  4.2.0.0 AI-202.7660.26.42.7486908
    Visual Studio: Not Found
  Languages:
    Java: 11.0.14
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

run React-native run-android after the run bundle

### Snack, code example, screenshot, or link to a repository

![Screenshot_1675707456](https://user-images.githubusercontent.com/34897947/217053739-05cf2d59-3e55-4475-a409-f21302c14569.png)

**Comment by migueldaipre** [comment]
This version is no longer maintained and unsupported.

Sounds like an error with your development environment.

**Comment by Rananjaya** [comment]
@migueldaipre Yes This Project is old one. my other Projects runs fine. any solution for  this. Thanks
