### ISSUE TITLE
Task 'javadoc' not found in root project 'appname'.

### ISSUE THREAD

**Issue by 98rahul** [facebook/react-native#36070]
### New Version

0.71.1

### Old Version

0.63.4

### Build Target(s)

android

### Output of `react-native info`

FAILURE: Build failed with an exception.

* What went wrong:
Task 'javadoc' not found in root project 'appname'.

### Issue and Reproduction Steps

on cleaning the caches in order to get rid of
 **React Native version mismatch. JavaScript version: 0.63.4 Native version: 0.71.1** [this error](https://github.com/facebook/react-native/issues/36014#issue-1564187093)

**Comment by cortinico** [comment]
> * Task 'javadoc' not found in root project 'appname'.

Please also share your `android/app/build.gradle` and `android/build.gradle`

**Comment by 98rahul** [comment]
**android\build.gradle**
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "33.0.0"
        minSdkVersion = 23
        compileSdkVersion = 33
        targetSdkVersion = 33
        androidXCore = "1.7.0"
        kotlin_version = '1.6.10'

          // We use NDK 23 which has both M1 support and is the side-by-side NDK version from AGP.
        ndkVersion = "23.1.7779620"

    }
    repositories {
        google()
        mavenCentral()
        //mavenCentral()
    }
    dependencies {
      
        classpath('com.android.tools.build:gradle:7.3.1')
        classpath("com.facebook.react:react-native-gradle-plugin")
        
    }
}

// will checkout later on
subprojects { subproject ->
        if(project['name'] == 'react-native-reanimated'){
            project.configurations { compile { } }
        }
}


**android\app\build.gradle**
apply plugin: "com.android.application"
apply plugin: "com.facebook.react"

import com.android.build.OutputFile

/**
 * This is the configuration block to customize your React Native Android app.
 * By default you don't need to apply any configuration, just uncomment the lines you need.

 */

// project.ext.react = [
//     entryFile: "index.js",
//     enableHermes: true, //false
//     // deleteDebugFilesForVariant: { false }
//       deleteDebugFilesForVariant: {
//         def variant -> variant.name.toLowerCase().contains("release") || variant.name.toLowerCase().contains("canary") ||
//         variant.name.toLowerCase().contains("beta")
//     }
//     //bundleCommand: "ram-bundle",
//     // bundleInDebug: true,
//  ]

// apply from: '../../node_modules/react-native-unimodules/gradle.groovy'
// apply from: "../../node_modules/react-native/react.gradle"
//apply from: "../../node_modules/expo-updates/scripts/create-manifest-android.gradle" //*&


react {
    /* Folders */
    //   The root of your project, i.e. where "package.json" lives. Default is '..'
    // root = file("../")
    //   The folder where the react-native NPM package is. Default is ../node_modules/react-native
    // reactNativeDir = file("../node_modules/react-native")
    //   The folder where the react-native Codegen package is. Default is ../node_modules/react-native-codegen
    // codegenDir = file("../node_modules/react-native-codegen")
    //   The cli.js file which is the React Native CLI entrypoint. Default is ../node_modules/react-native/cli.js
    // cliFile = file("../node_modules/react-native/cli.js")
    /* Variants */
    //   The list of variants to that are debuggable. For those we're going to
    //   skip the bundling of the JS bundle and the assets. By default is just 'debug'.
    //   If you add flavors like lite, prod, etc. you'll have to list your debuggableVariants.
    // debuggableVariants = ["liteDebug", "prodDebug"]
    /* Bundling */
    //   A list containing the node command and its flags. Default is just 'node'.
    // nodeExecutableAndArgs = ["node"]
    //
    //   The command to run when bundling. By default is 'bundle'
    // bundleCommand = "ram-bundle"
    //
    //   The path to the CLI configuration file. Default is empty.
    // bundleConfig = file(../rn-cli.config.js)
    //
    //   The name of the generated asset file containing your JS bundle
    // bundleAssetName = "MyApplication.android.bundle"
    //
    //   The entry file for bundle generation. Default is 'index.android.js' or 'index.js'
    // entryFile = file("../js/MyApplication.android.js")
    //
    //   A list of extra flags to pass to the 'bundle' commands.
    //   See https://github.com/react-native-community/cli/blob/main/docs/commands.md#bundle
    // extraPackagerArgs = []
    /* Hermes Commands */
    //   The hermes compiler command to run. By default it is 'hermesc'
    // hermesCommand = "$rootDir/my-custom-hermesc/bin/hermesc"
    //
    //   The list of flags to pass to the Hermes compiler. By default is "-O", "-output-source-map"
    // hermesFlags = ["-O", "-output-source-map"]
}


/**
 * Set this to true to create two separate APKs instead of one:
 * Set this to true to create four separate APKs instead of one,
 * one for each native architecture. This is useful if you don't
 * use App Bundles (https://developer.android.com/guide/app-bundle/)
 * and want to have separate APKs to upload to the Play Store.
 */
def enableSeparateBuildPerCPUArchitecture = false

/**
 * Set this to true to Run Proguard on Release builds to minify the Java bytecode.
 */
def enableProguardInReleaseBuilds = true

/**
  * The preferred build flavor of JavaScriptCore (JSC)
 *
 * For example, to use the international variant, you can use:
 * `def jscFlavor = 'org.webkit:android-jsc-intl:+'`
 *
 * The international variant includes ICU i18n library and necessary data
 * allowing to use e.g. `Date.toLocaleString` and `String.localeCompare` that
 * give correct results when using with locales other than en-US.  Note that
 * this variant is about 6MiB larger per architecture than default.
 */
def jscFlavor = 'org.webkit:android-jsc:+'

/**
 * Private function to get the list of Native Architectures you want to build.
 * This reads the value from reactNativeArchitectures in your gradle.properties
 * file and works together with the --active-arch-only flag of react-native run-android
 */
// def enableHermes = project.ext.react.get("enableHermes", false)//false


/**
 * Architectures to build native code for.
 */
def reactNativeArchitectures() {
    def value = project.getProperties().get("reactNativeArchitectures")
    return value ? value.split(",") : ["armeabi-v7a", "x86", "x86_64", "arm64-v8a"]
}

android {   

    compileSdkVersion rootProject.ext.compileSdkVersion
    namespace "com.pushthivardhan.foods.consumer"
    defaultConfig {
        applicationId "com.pushthivardhan.foods.consumer"
        minSdkVersion rootProject.ext.minSdkVersion
        // compileSdkVersion rootProject.ext.compileSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 235 
        versionName "2.3.5"
        missingDimensionStrategy 'react-native-camera', 'general'
        multiDexEnabled true
        vectorDrawables.useSupportLibrary = true
        ndk {
            abiFilters 'armeabi-v7a','arm64-v8a','x86','x86_64'
        }

        
    }

  
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            // include "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
            include (*reactNativeArchitectures())
        }
    }
    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
        release {
            storeFile file('release.keystore')
            storePassword 'pushthivardhan'
            keyAlias 'pushthivardhan'
            keyPassword 'pushthivardhan'
        }
        staging {
            storeFile file('release.keystore')
            storePassword 'passme'
            keyAlias 'dummy'
            keyPassword 'toolDummy'
        }
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            // Caution! In production, you need to generate your own keystore file.
            // see https://reactnative.dev/docs/signed-apk-android.
            signingConfig signingConfigs.release
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }

    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // https://developer.android.com/studio/build/configure-apk-splits.html
            def versionCodes = ["armeabi-v7a": 1, "x86": 2, "arm64-v8a": 3, "x86_64": 4]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                defaultConfig.versionCode * 1000 + versionCodes.get(abi)
                        
            }

        }
    }
}

dependencies {
    // Execution failed for task ':react-native-keychain:processDebugUnitTestManifest'.
    // implementation "androidx.test:core:1.4.0"
    // The version of react-native is set by the React Native Gradle Plugin
    implementation("com.facebook.react:react-android")

    implementation("androidx.swiperefreshlayout:swiperefreshlayout:1.1.0")

    debugImplementation("com.facebook.flipper:flipper:${FLIPPER_VERSION}")
    debugImplementation("com.facebook.flipper:flipper-network-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.squareup.okhttp3', module:'okhttp'
    }

    debugImplementation("com.facebook.flipper:flipper-fresco-plugin:${FLIPPER_VERSION}")
    if (hermesEnabled.toBoolean()) {
        implementation("com.facebook.react:hermes-android")
    } else {
        implementation jscFlavor
    }
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.implementation
    into 'libs'
}

apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)

 // Execution failed for task ':react-native-keychain:processDebugUnitTestManifest'.
// project(':react-native-keychain').tasks.withType(Test) {
//     enabled = false
// }



> > * Task 'javadoc' not found in root project 'appname'.
> 
> Please also share your `android/app/build.gradle` and `android/build.gradle`

**Comment by cortinico** [comment]
Your file looks fine. I'm unsure what's causing the "Task 'javadoc' not found in root project 'appname'." Error. Are you able to provide a reproducer?

**Comment by 98rahul** [comment]
just like to closed as it's already been resloved long days back.🏁

**Comment by 98rahul** [comment]
[closed](https://github.com/facebook/react-native/issues/36070#issuecomment-1669487728)
