### ISSUE TITLE
[React] react-tools dependency

### ISSUE THREAD

**Issue by skevy** [facebook/react-native#3607]
In ref to: https://github.com/facebook/react-native/commit/58ea08dfdb4f9279eb9071f9e179ae882185ff45

So, this particular commit of React, because it is 0.14-beta1, contains broken context reconciliation.

It was fixed in this commit:  https://github.com/facebook/react/commit/9baaeec21d05c717e1fa02f72de458c1df257f8a

I tried updating the dependency to something a bit more recent, but, it breaks other things.

This relates to https://github.com/facebook/react-native/issues/2985, but I just wanted to make you guys aware.

Currently fixing by cherry-picking this commit and using a custom branch of react-tools. :(

cc @mkonicek @spicyj @foghina who made/reviewed the referenced commit.

**Comment by mkonicek** [comment]
@spicyj you have the most context on React. Can you take a look please?

**Comment by spicyj** [comment]
This is not a new issue in 58ea08d, which uses the same version as the previous package.json. We are aware that RN is not yet on 0.14; I'm hoping to upgrade it soon.

**Comment by skevy** [comment]
I'm going to close this, as its related specifically to #2985, and also, RN is now using React 0.14 :-)
