### ISSUE TITLE
Android - React-Native-render-html  - Wont show all content

### ISSUE THREAD

**Issue by afu1995** [facebook/react-native#36088]
### Description

On Android it wont show all content from the source. I don't know if it's the contentWidth or source prop that fails. It works perfectly fine on iOS. 

### Version

0.70.8

### Output of `npx react-native info`

System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 73.19 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
    Watchman: 2022.11.14.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9477386
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.70.6 => 0.70.6
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Open app, go to PDP page, tap on "description". 

### Snack, code example, screenshot, or link to a repository

{description ? (
        <Accordion title={translate(WebshopTranslations.ProductDescription, 'Beskrivelse')!}>
          <Text>
            <RenderHtml contentWidth={Screen.width} source={{ html: description }} />
          </Text>
        </Accordion>
      ) : null}

**Comment by cortinico** [comment]
Hi,
Thanks for reporting this issue.

It seems like this issue is actually unrelated to React Native core. Please open this issue against this other repository:

https://github.com/meliorence/react-native-render-html/issues

I'll be closing this but feel free to reopen if the other repo points back to us as a issue in the core of React Native.
