### ISSUE TITLE
Gradle does not apply patch-package patches.

### ISSUE THREAD

**Issue by nmateo** [facebook/react-native#36082]
### Description

gradlew assembleRelease / assembleDebug does not apply patch-package, whereas npx react-native start & npx react-native run-android does.

"postinstall":  "patch-package"

How can i make gradle build apply my patches ?

### Version

0.70.5

### Output of `npx react-native info`

````info Fetching system and libraries information...
System:
    OS: Linux 6.1 Ultramarine Linux
    CPU: (16) x64 Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
    Memory: 3.86 GB / 15.47 GB
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 18.1.0 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 11.0.16.1 - /home/nmateo/Documents/react/amazon-corretto-11-x64-linux-jdk/amazon-corretto-11.0.16.9.1-linux-x64/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.5 => 0.70.5 
  npmGlobalPackages:
    *react-native*: Not Found
````

### Steps to reproduce

Patch a dependency with patch-package, add "postinstall": "patch-package" to "scripts", in package.json

### Snack, code example, screenshot, or link to a repository

![image](https://user-images.githubusercontent.com/9270970/217296713-a53c1c0a-5971-4b39-b980-8410cd890147.png)

Here's my simple patch that get applied using expo go app or react-native binaries but not during gradle builds.

**Comment by cortinico** [comment]
> gradlew assembleRelease / assembleDebug does not apply patch-package, whereas npx react-native start & npx react-native run-android does.

What's the reason why you're using directly Gradle commands?

**Comment by nmateo** [comment]
> > gradlew assembleRelease / assembleDebug does not apply patch-package, whereas npx react-native start & npx react-native run-android does.
> 
> What's the reason why you're using directly Gradle commands?

To test/distribute the apk's  (x86, arm64 arm32, universal...) internally

**Comment by cortinico** [comment]
> To test/distribute the apk's (x86, arm64 arm32, universal...) internally

You should be able to just use `react-native run-android` and find the APKs inside the `android/app/build/outputs/apk/` folder anyway

**Comment by nmateo** [comment]
> > To test/distribute the apk's (x86, arm64 arm32, universal...) internally
> 
> You should be able to just use `react-native run-android` and find the APKs inside the `android/app/build/outputs/apk/` folder anyway

Thanks, i did not realise that! 
One last question where can i see exactly what does react-native run-android does more than assemble & adb install ?
Thanks in advance
