### ISSUE TITLE
Unable to run iOS on Device from Command Line - Simulator Works. 

### ISSUE THREAD

**Issue by ko-devHong** [facebook/react-native#36086]
### Description

I want to connect and run the device through the command line. However, I can only see the error that there is no connected device.

```
error No iOS devices connected.
✨  Done in 2.92s.
```

```
❯ xcrun xctrace list devices
== Devices ==
user’s MacBook Pro (*********-***-**-*******)
iPhone (2) (15.2) (*******-*********)
```

```
❯ ios-deploy -c
[....] Waiting up to 5 seconds for iOS device to be connected
[....] Found ******-****** (D53gAP, iPhone 12, iphoneos, arm64e, 15.2, 19C56) a.k.a. 'iPhone (2)' connected through USB
```

### Version

0.71.1

### Output of `npx react-native info`

System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Pro
    Memory: 140.91 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.0.0 - /usr/local/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 8.6.0 - /usr/local/bin/npm
    Watchman: 2023.01.16.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/user/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9477386
    Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.1 => 0.71.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. create react-native project
2. setting react-native
3. register scripts in package.json `"ios" : "react-native run-ios --device"`
4. run ios `yarn ios`

### Snack, code example, screenshot, or link to a repository

1. create react-native project
2. setting react-native
3. register scripts in package.json `"ios" : "react-native run-ios --device"`
4. run ios `yarn ios`

**Comment by cortinico** [comment]
Does it work for you if you do `react-native run-ios --device` from the command line?

**Comment by cortinico** [comment]
That's an issue with the CLI. Please open the same issue with:
https://github.com/react-native-community/cli/issues

I'll be closing this but feel free to reopen if the CLI folks points back to us as a issue in the core of React Native.
