### ISSUE TITLE
[iOS/iPadOS] - icons/icon font not loading correctly

### ISSUE THREAD

**Issue by coolersham** [facebook/react-native#36090]
### Description

When using either of the well-known vector icon packages (`@expo/vector-icons` OR `react-native-vector-icons`), not a single icon loads and instead a question mark is rendered (it is even coloured in the correct way).

I am using the latest version of the package in connection with the new `react-native` architecture 
on version 0.71.2. Fabric renderer and concurrency are additionally enabled. 

All steps in the documentation were considered but the outcome is still the same.

The icons are displayed as following:
<img width="71" alt="showcase" src="https://user-images.githubusercontent.com/123668138/217560298-cb74503c-876f-45a5-b702-4cec392d214d.png">

Android devices are not affected by this issue.

### Version

0.71.2

### Output of `npx react-native info`

[...]
@expo/webpack-config: 0.17.4
babel-preset-expo: 9.2.2
expo: 48.0.0-beta.0 (also on 47.X.X)
react: 18.2.0
react-dom: 18.2.0
react-native: 0.71.2
react-native-web: 0.18.12

@expo/vector-icons: 13.0.0
OR
react-native-vector-icons: 9.2.0 (even with the latest commit/status of the repository)
[...]

### Steps to reproduce

Use the mentioned packages in an environment with new architecture, fabric and concurrency enabled while using a virtualised or physical iOS/iPadOS device.

### Snack, code example, screenshot, or link to a repository

```
import { MaterialCommunityIcons } from "@expo/vector-icons"

[...]

<MaterialCommunityIcons color="blue" name="close" size={24} />
```

OR

```
import MaterialCommunityIcon from "react-native-vector-icons/MaterialCommunityIcons"

[...]

<MaterialCommunityIcon color="blue" name="close" size={24} />
```

**Comment by cortinico** [comment]
You should open this issue against the issue tracker of the packages like:
https://github.com/oblador/react-native-vector-icons/issues

Please get back here if they point you in this being a problem of React Native core
