### ISSUE TITLE
[Android Native UI Components] Creating a MapView / passing fragments to createViewInstance

### ISSUE THREAD

**Issue by cosmith** [facebook/react-native#3609]
I'm trying to build a Google Maps Native UI Component for Android and I'm having trouble getting the map to display.

My code:

- basic ReactPackage
```java
public class GoogleMapPackage implements ReactPackage {
    @Override
    public List<NativeModule> createNativeModules(ReactApplicationContext reactContext) {
        List<NativeModule> modules = new ArrayList<>();
        modules.add(new GoogleMapModule(reactContext));
        return modules;
    }

    @Override
    public List<Class<? extends JavaScriptModule>> createJSModules() {
        return Collections.emptyList();
    }

    @Override
    public List<ViewManager> createViewManagers(ReactApplicationContext reactContext) {
        return Arrays.<ViewManager>asList(new GoogleMapViewManager());
    }
}
```

- ViewManager
```java
public class GoogleMapViewManager extends SimpleViewManager<GoogleMapView> {
    public static final String REACT_CLASS = "RCTGoogleMap";

    @UIProp(UIProp.Type.BOOLEAN)
    public static final String PROP_TRAFFIC_ENABLED = "trafficEnabled";

    @Override
    public String getName() {
        return REACT_CLASS;
    }

    @Override
    public GoogleMapView createViewInstance(ThemedReactContext context) {
        return new GoogleMapView(context);
    }

    @Override
    public void updateView(final GoogleMapView view, final CatalystStylesDiffMap props) {
        super.updateView(view, props);
    }
}
```

- my GoogleMapView
```java
public class GoogleMapView extends MapView implements OnMapReadyCallback {
    private GoogleMap mMap;

    public GoogleMapView(Context context) {
        super(context);
        getMapAsync(this);
    }

    @Override
    public void onMapReady(GoogleMap map) {
        mMap = map;
        Log.d("MAP", "MAP READY");
    }
}
```

`onMapReady` is never called and nothing shows on the screen (if I inspect the component it is there though, with the correct dimensions).

I'm not sure if my problem is with the Maps SDK or if there is a specific way to display views that I don't understand... The recommended way is to use a Fragment but I couldn't figure out how to use fragments with the `createViewInstance` API. I tried creating and inflating layouts, passing the activity to the `ViewManager`... no luck.

So I guess I have 2 questions:

- is there a way to use `Fragment` in a Native UI Component?

- or does anyone have a better understanding than me of either the Maps SDK or the way views are handled after they are passed to `createViewInstance`?

Thanks!

**Comment by cosmith** [comment]
I needed to call `onCreate` for the map to show... closing this.

**Comment by ehourigan** [comment]
@cosmith Where are you making the call to onCreate to show the map?

**Comment by cosmith** [comment]
My constructor looks like this

```java
public GoogleMapView(Context context) {
        super(context);
        onCreate(null);
        onResume();
        getMapAsync(this);

        mMarkerCache = new HashMap<>();
        mMarkerKeys = new HashMap<>();
        mMarkerIcons = new HashMap<>();
    }
```

I don't really know enough about Android / Java to know if it's a terrible idea, but it works :)

**Comment by ehourigan** [comment]
@cosmith thanks for the context!
