### ISSUE TITLE
react-packager: Use Bluebird (or others) instead of Q as Promises library

### ISSUE THREAD

**Issue by pilwon** [facebook/react-native#361]
[Q](https://github.com/kriskowal/q) is very slow and eats so much memory compared to alternative Promises libraries as shown [here](https://github.com/petkaantonov/bluebird/tree/master/benchmark).

Consider switching to [Bluebird](https://github.com/petkaantonov/bluebird) or something else to squeeze out performance for `react-packager`.

**Comment by amasad** [comment]
I think most bottleneck are transformation filesystem. If you want to give it a go and report back numbers, I'll happily consider it :)

**Comment by petkaantonov** [comment]
The benchmark isn't really relevant as it runs with N=10000 and (I assume) packager is always N=1 - if you run the benchmark with N=1 you will hopefully not see any difference between implementations as anything is fast for a small N.

**Comment by amasad** [comment]
Thanks for the clarification @petkaantonov 
If we end up standardizing on Bluebird in React Native we'll switch the packager to it as well.

**Comment by pilwon** [comment]
@amasad @petkaantonov

I probably picked an irrelevant benchmark there depending on what it really tested, but I still think I identified a real performance bottleneck here.

I ran a quick test just on `DependencyGraph` and here's the result:

--

### Test Summary

Bluebird performed almost 2x faster :facepunch: 

#### DependencyGraph with `Q` ([current code](https://github.com/facebook/react-native/blob/3c4341084396a56d66b9ebc9fb0be1d315cd43ff/packager/react-packager/src/DependencyResolver/haste/DependencyGraph/index.js))

```
#ofRuns:  100
Average: 5016 ms
Median:  4879.5 ms
Minimum: 4079 ms
Maximum: 7744 ms
StdDev:  639.8 ms
```

#### DependencyGraph with `Bluebird` ([modified code](https://gist.github.com/pilwon/82a70ad5f8e3c817d129))

```
#ofRuns:  100
Average: 2742.3 ms
Median:  2648 ms
Minimum: 2043 ms
Maximum: 5034 ms
StdDev:  504.6 ms
```

### System Info

* MacBook Pro (Retina, 13-inch, Early 2015)
* 2.7 GHz Intel Core i5
* 6 GB 1867 MHz DDR3

### Test Script & Full Result

You can find the test script and full result [here](https://gist.github.com/pilwon/4bf8d9ace820673ca77b).

--

Note that I only replaced `DependencyGraph` module for this test. Imagine how much performance gain you can have if all modules using `Q` make a switch to `Bluebird`. There are even (presumably) faster (less features) promise libraries such as [es6-promise](https://github.com/jakearchibald/es6-promise).

I discovered this problem while trying to [integrate](https://github.com/facebook/react-native/issues/395#issuecomment-87294565) [with](https://github.com/facebook/react-native/issues/278#issuecomment-871978410) [webpack](https://github.com/facebook/react-native/issues/274#issuecomment-87191121) as the solution I found was to query `DependencyGraph` for internal dependencies to resolve `react-native` modules from `webpack`. It always took way too long.

**Comment by petkaantonov** [comment]
That's surprising that so many promises are being created that there is actually a difference. It would be interesting to know how many. The bluebird sequential benchmark creates 80000 promises with N=10000 and 8 promises with N=1, hence why you wouldn't see any difference with N=1.

**Comment by pilwon** [comment]
@petkaantonov This particular case (`DependencyGraph`) that I tested with hits the filesystem like crazy as it scans the entire file tree to extract dependencies information and Promise library is the glue for all IO and transformation operations. What's the best way to measure how many promises are created?

**Comment by petkaantonov** [comment]
@pilwon In bluebird I have just ad hoc edited the promise constructor code by doing Promise.promisesCreated++ inside the constructor and then reading it out and the end of benchmark

Also results for 3.0 would be interesting too as it provides some significant performance improvements to Promise.all and promisify

**Comment by pilwon** [comment]
@petkaantonov Is [this](https://github.com/petkaantonov/bluebird/blob/89c27e46ba1f99a56946d30adea0c94ae4e05c7a/src/promise.js#L40-L62) the right place?

**Comment by petkaantonov** [comment]
@pilwon Yes it is

**Comment by pilwon** [comment]
46039 promises are created in each run. :scream: :astonished: :unamused:

**Comment by petkaantonov** [comment]
Ok, that's shocking and my earlier point doesn't make sense any more.. I was expecting more like 10-100 promises being created

**Comment by amasad** [comment]
This awesome, thanks for digging into it.

**Comment by amasad** [comment]
fixed
