### ISSUE TITLE
app becomes stateless after couple of navigation RN-0.71.1

### ISSUE THREAD

**Issue by 98rahul** [facebook/react-native#36114]
### New Version

0.71.1

### Old Version

0.63.4

### Build Target(s)

Android

### Output of `react-native info`

without logging any error app becomes stateless as it moves to loading state because of not making any API call.

### Issue and Reproduction Steps

on navigating couple of screens , suddenly it stops making any API call and app becomes idle without throwing any error.
[gradle setup](https://github.com/facebook/react-native/issues/36070#issuecomment-1422075380).

**Comment by cortinico** [comment]
Hey @98rahul 
Sorry but this issue is invalid as it contains too little information for us to debug.
You need to provide a reproducer, follow the issue template, and provide the output of `react-native info` for us to even start looking into this
