### ISSUE TITLE
IOS Crash App when build to simulator

### ISSUE THREAD

**Issue by lehuydev2203** [facebook/react-native#36124]
### Description

Now, my project is having issues when running app on simulator.
When click app alway crash app 

### Version

0.70.0

### Output of `npx react-native info`

System:
    OS: macOS 13.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 39.01 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
    Watchman: 2023.02.06.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/huyldt/.rvm/gems/ruby-2.7.6/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9514443
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.6 => 0.70.6
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Xcode -> run 

### Snack, code example, screenshot, or link to a repository

![Screenshot 2023-02-10 at 20 41 06](https://user-images.githubusercontent.com/41155784/218106874-ad90c606-0ae7-498d-a5ed-c7b5400f2496.jpg)

**Comment by carlosalmonte04** [comment]
Is this on a new `npx react-native init AwesomeProject --version 0.70.0` app? Worked fine for me.
```
System:
    OS: macOS 12.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 471.53 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
    Yarn: 1.15.2 - ~/.yarn/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v18.13.0/bin/npm
    Watchman: 2023.01.30.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/carlosalmonte/.rvm/gems/ruby-2.7.6/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      Android NDK: 17.2.4988734
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9477386
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 18.0.1.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.0 => 0.70.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by lehuydev2203** [comment]
> Is this on a new `npx react-native init AwesomeProject --version 0.70.0` app? Worked fine for me.
> 
> ```
> System:
>     OS: macOS 12.4
>     CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
>     Memory: 471.53 MB / 16.00 GB
>     Shell: 5.8.1 - /bin/zsh
>   Binaries:
>     Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
>     Yarn: 1.15.2 - ~/.yarn/bin/yarn
>     npm: 8.19.3 - ~/.nvm/versions/node/v18.13.0/bin/npm
>     Watchman: 2023.01.30.00 - /usr/local/bin/watchman
>   Managers:
>     CocoaPods: 1.11.3 - /Users/carlosalmonte/.rvm/gems/ruby-2.7.6/bin/pod
>   SDKs:
>     iOS SDK:
>       Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
>     Android SDK:
>       Android NDK: 17.2.4988734
>   IDEs:
>     Android Studio: 2022.1 AI-221.6008.13.2211.9477386
>     Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
>   Languages:
>     Java: 18.0.1.1 - /usr/bin/javac
>   npmPackages:
>     @react-native-community/cli: Not Found
>     react: 18.1.0 => 18.1.0 
>     react-native: 0.70.0 => 0.70.0 
>     react-native-macos: Not Found
>   npmGlobalPackages:
>     *react-native*: Not Found
> ```

I found issues with a version of realm. I did down version realm and it's run.
