### ISSUE TITLE
Multiple commands produce CallbackWrapper.h

### ISSUE THREAD

**Issue by TomNes94** [facebook/react-native#36120]
### New Version

0.71.2

### Old Version

0.70.6

### Build Target(s)

iOS

### Output of `react-native info`

System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1
    Memory: 373.80 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.8.0 - ~/.nvm/versions/node/v18.8.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.8.0/bin/yarn
    npm: 8.18.0 - ~/.nvm/versions/node/v18.8.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.18 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^18.2.0 => 18.2.0 
    react-native: 0.71.2 => 0.71.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Issue and Reproduction Steps

I have upgraded to 0.71.2. I have rewritten the AppDelegate file to Swift to have an easier integration with some native code we had to write. When upgrading I get the error that copy commands produce CallbackWrapper.h multiple times. Error is as follows:

I get a build error for React Native 0.71.2 when running "Build" in XCode: 

`Multiple commands produce '../Library/Developer/Xcode/DerivedData/App-hdbxjwxynzrirjamwnukgbyqmimm/Build/Products/Debug-iphoneos/ReactCommon/ReactCommon.framework/Headers/CallbackWrapper.h'`

The two commands are:

`Target 'ReactCommon' (project 'Pods') has copy command from '../Documents/App/app/node_modules/react-native/ReactCommon/react/bridging/CallbackWrapper.h' to '/../Library/Developer/Xcode/DerivedData/App-hdbxjwxynzrirjamwnukgbyqmimm/Build/Products/Debug-iphoneos/ReactCommon/ReactCommon.framework/Headers/CallbackWrapper.h'`

`Target 'ReactCommon' (project 'Pods') has copy command from '../Documents/App/app/node_modules/react-native/ReactCommon/react/nativemodule/core/ReactCommon/CallbackWrapper.h' to '/../Library/Developer/Xcode/DerivedData/App-hdbxjwxynzrirjamwnukgbyqmimm/Build/Products/Debug-iphoneos/ReactCommon/ReactCommon.framework/Headers/CallbackWrapper.h'`

Removing ReactBridge headers from my Objective C bridging header made no difference. My Podfile looks very similar to the one generated for a fresh project. Upgrading from 0.70.6 to 0.71.0 gives the same result. I have tried cleaning DerivedData folder, removing yarn.lock/node_modules but nothing seems to help.

**Comment by cortinico** [comment]
> I have upgraded to 0.71.2. I have rewritten the AppDelegate file to Swift to have an easier integration with some native code we had to write. When upgrading I get the error that copy commands produce CallbackWrapper.h multiple times. Error is as follows:

@cipolleschi can give you insights here. I believe this is somehow related to how `use_frameworks` ends up merging headers with the same name.

**Comment by TomNes94** [comment]
I do use `use_frameworks! :linkage => :static` because of @react-native-firebase. Podfile contents are:

```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '14.0'
install! 'cocoapods', :deterministic_uuids => false

target 'App' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()
  
  use_react_native!(
    :path => config[:reactNativePath],

    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # Disables Flipper.
    :flipper_configuration => FlipperConfiguration.disabled,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  pod 'NewRelicAgent'
  pod 'FBAudienceNetwork'
  pod "PromiseKit", "~> 6.8"

  use_frameworks! :linkage => :static

  post_install do |installer|
    react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    # Prevents RCT-Folly build from failing
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["ONLY_ACTIVE_ARCH"] = "NO"
      end
      if target.name == 'RCT-Folly'
          target.build_configurations.each do |config|
              config.build_settings['HEADER_SEARCH_PATHS'] = "$(inherited) ${PODS_ROOT}/fmt/include"
          end
      end
      installer.pods_project.build_configurations.each do |config|   
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      end
  end
  end
end

$NotifeeExtension = true

target 'NotifeeNotificationService' do
  use_frameworks! :linkage => :static

  pod 'RNNotifeeCore', :path => '../node_modules/@notifee/react-native/RNNotifeeCore.podspec'
end
```

**Comment by cipolleschi** [comment]
Hi there! The solution is to move the `use_frameworks! :linkage => :static` before the `use_react_native!()` function call.

What's happening is that `use_react_native!()` installs the dependencies and [understands](https://github.com/facebook/react-native/blob/0.71-stable/scripts/react_native_pods.rb#L69) whether you are using the frameworks setup or not.

When you are using frameworks, we need to fix some search paths in order to make them work as expected. And to do so, we need to do some shenanigans with files. Practically, when `use_frameworks!` is enabled, we need to [exclude](https://github.com/facebook/react-native/blob/0.71-stable/ReactCommon/ReactCommon.podspec#L70-L72) some files from the builds (are just forwarding files).

Putting the `use_framework!` instruction *after* the invocation of `use_react_native!` prevents us from automatically detect that setup, that's why moving it before should fix the issue.

Let me know if it fixes!

**Comment by TomNes94** [comment]
Fixes like a charm 🙏

**Comment by dilipchandima** [comment]
this is not working for me :( 
@cipolleschi 

```

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, min_ios_version_supported
prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'imcoming' do
  config = use_native_modules!

  use_frameworks! :linkage => :static
  $RNFirebaseAsStaticFramework = true

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    # :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'imcomingTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end

```

**Comment by cipolleschi** [comment]
@dilipchandima I'm sorry its not working.

A few question to understand better your issue:
1. Which version of ReactNative are you using?
2. What is this line: `$RNFirebaseAsStaticFramework = true`? It's settingg a global variable called `RNFirebaseAsStaticFramework` to `true`but I can't see where it is used.
3. Could you try to put the `use_frameworks! :linkage => :static` before the `target 'imcoming' do` and try again?
4. if you are upgrading to Version 0.71 from a previous one, have you run `yarn install` in the root of the project and reinstalled cocoapods?

Also, as you can see, there is already a block to setup `use_frameworks!` before the `target 'imcoming'`

**Comment by Dajust** [comment]
I am still experiencing this issue even when I totally remove `use_frameworks! :linkage => :static`.

**Comment by sjamr10** [comment]
> Hi there! The solution is to move the `use_frameworks! :linkage => :static` before the `use_react_native!()` function call.
> 
> What's happening is that `use_react_native!()` installs the dependencies and [understands](https://github.com/facebook/react-native/blob/0.71-stable/scripts/react_native_pods.rb#L69) whether you are using the frameworks setup or not.
> 
> When you are using frameworks, we need to fix some search paths in order to make them work as expected. And to do so, we need to do some shenanigans with files. Practically, when `use_frameworks!` is enabled, we need to [exclude](https://github.com/facebook/react-native/blob/0.71-stable/ReactCommon/ReactCommon.podspec#L70-L72) some files from the builds (are just forwarding files).
> 
> Putting the `use_framework!` instruction **after** the invocation of `use_react_native!` prevents us from automatically detect that setup, that's why moving it **before** should fix the issue.
> 
> Let me know if it fixes!

Thank you! I struggled for a couple of hours with this problem!

**Comment by ucheNkadiCode** [comment]
@dilipchandima have you tried placing `  $RNFirebaseAsStaticFramework = true` at the top of your podfile? that's how I have it

**Comment by manchoudhary** [comment]
> Hi there! The solution is to move the `use_frameworks! :linkage => :static` before the `use_react_native!()` function call.
> 
> What's happening is that `use_react_native!()` installs the dependencies and [understands](https://github.com/facebook/react-native/blob/0.71-stable/scripts/react_native_pods.rb#L69) whether you are using the frameworks setup or not.
> 
> When you are using frameworks, we need to fix some search paths in order to make them work as expected. And to do so, we need to do some shenanigans with files. Practically, when `use_frameworks!` is enabled, we need to [exclude](https://github.com/facebook/react-native/blob/0.71-stable/ReactCommon/ReactCommon.podspec#L70-L72) some files from the builds (are just forwarding files).
> 
> Putting the `use_framework!` instruction **after** the invocation of `use_react_native!` prevents us from automatically detect that setup, that's why moving it **before** should fix the issue.
> 
> Let me know if it fixes!

It worked!! You are a saviour.

**Comment by R4DIC4L** [comment]
@cipolleschi Thank you for the solution!
I was also experiencing below errors:

```
Undefined symbol: google::InitVLOG3__(google::SiteFlag*, int*, char const*, int)
Undefined symbol: google::ErrnoLogMessage::ErrnoLogMessage(char const*, int, int, long long, void (google::LogMessage::*)())
```

After I disabled Flipper in my podfile and reinstalled the pods, the app worked again.

Before:
`flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled`
After:
`flipper_config = FlipperConfiguration.disabled`

Modified the value directly since Flipper doesn't work with use_frameworks! anyway.

**Comment by adilijaz** [comment]
> Hi there! The solution is to move the `use_frameworks! :linkage => :static` before the `use_react_native!()` function call.
> 
> What's happening is that `use_react_native!()` installs the dependencies and [understands](https://github.com/facebook/react-native/blob/0.71-stable/scripts/react_native_pods.rb#L69) whether you are using the frameworks setup or not.
> 
> When you are using frameworks, we need to fix some search paths in order to make them work as expected. And to do so, we need to do some shenanigans with files. Practically, when `use_frameworks!` is enabled, we need to [exclude](https://github.com/facebook/react-native/blob/0.71-stable/ReactCommon/ReactCommon.podspec#L70-L72) some files from the builds (are just forwarding files).
> 
> Putting the `use_framework!` instruction **after** the invocation of `use_react_native!` prevents us from automatically detect that setup, that's why moving it **before** should fix the issue.
> 
> Let me know if it fixes!

I tried but now Its showing this error "eact/debug/react_native_assert.h' file not found". anyone face it?

**Comment by cipolleschi** [comment]
@adilijaz to help out, can you share the podfile, wrapping it into some code tags?

A part from this, some common questions:
- are you using RN CLI or Expo?
- do you have `use_frameworks` enabled?
- are you using libraries like react-native-permissions?
- are you calling `use_react_native!` and `react_native_post_install` in your podfile?
- are all the extra pod dependencies installed **after** the call to `use_react_native!`?
- does the issue reproduce in a newly created app?

**Comment by marcusrrall** [comment]
> @cipolleschi Thank you for the solution! I was also experiencing below errors:
> 
> ```
> Undefined symbol: google::InitVLOG3__(google::SiteFlag*, int*, char const*, int)
> Undefined symbol: google::ErrnoLogMessage::ErrnoLogMessage(char const*, int, int, long long, void (google::LogMessage::*)())
> ```
> 
> After I disabled Flipper in my podfile and reinstalled the pods, the app worked again.
> 
> Before: `flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled` After: `flipper_config = FlipperConfiguration.disabled`
> 
> Modified the value directly since Flipper doesn't work with use_frameworks! in ios anyway.

This worked for me

**Comment by eedeebee** [comment]
Seein this in 0.72 and the above fixes don't help.

```
Multiple commands produce '/Users/XXX/Library/Developer/Xcode/DerivedData/YYY/Build/Products/Debug-iphoneos/ReactCommon/ReactCommon.framework/Headers/LongLivedObject.h'


Multiple commands produce '/Users/XXX/Library/Developer/Xcode/DerivedData/YYY/Build/Products/Debug-iphoneos/ReactCommon/ReactCommon.framework/Headers/CallbackWrapper.h'
```

My podfile looks like this:

```use_frameworks! :linkage => :static
$RNFirebaseAsStaticFramework = true

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

# platform :ios, min_ios_version_supported (auth0 requires iOS 13 or later)
platform :ios, '13.0'
prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
# flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

# linkage = ENV['USE_FRAMEWORKS']
# if linkage != nil
#   Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
#   use_frameworks! :linkage => linkage.to_sym
# end

target 'YYY' do
  
  
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()



  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    # :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    # :app_path => "#{Pod::Config.instance.installation_root}/.."
  )



  target 'YYY' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end```

**Comment by eedeebee** [comment]
Fwiw I tried disabling all sorts of things in the Podfile and the issue remains.

**Comment by cipolleschi** [comment]
Hi @eedeebee, can you provide a reproducer using https://github.com/react-native-community/reproducer-react-native? In that way, I would be able to investigate the issue.

In the pod you shared you have two `'YYY'` targets. I don't think that it is allowed.

**Comment by eedeebee** [comment]
Thanks - I am honestly not sure what was going on but since I upgraded from node 18.16 to 18.17 this issue has gone away ; this seems to be an unrelated change but  I can no longer repro the issue.  Perhaps somehow the reordering of commands didn’t somehow take until now I’m just not sure.Thanks for checking!On Dec 18, 2023, at 6:39 AM, Riccardo Cipolleschi ***@***.***> wrote:﻿
Hi @eedeebee, can you provide a reproducer using https://github.com/react-native-community/reproducer-react-native? In that way, I would be able to investigate the issue.
In the pod you shared you have two 'YYY' targets. I don't think that it is allowed.

**Comment by Yandamuri** [comment]
> Hi there! The solution is to move the `use_frameworks! :linkage => :static` before the `use_react_native!()` function call.
> 
> What's happening is that `use_react_native!()` installs the dependencies and [understands](https://github.com/facebook/react-native/blob/0.71-stable/scripts/react_native_pods.rb#L69) whether you are using the frameworks setup or not.
> 
> When you are using frameworks, we need to fix some search paths in order to make them work as expected. And to do so, we need to do some shenanigans with files. Practically, when `use_frameworks!` is enabled, we need to [exclude](https://github.com/facebook/react-native/blob/0.71-stable/ReactCommon/ReactCommon.podspec#L70-L72) some files from the builds (are just forwarding files).
> 
> Putting the `use_framework!` instruction **after** the invocation of `use_react_native!` prevents us from automatically detect that setup, that's why moving it **before** should fix the issue.
> 
> Let me know if it fixes!

This solution worked for me with Xcode 15, react-native 0.73.6
