### ISSUE TITLE
Packager doesn't like package names ending in -react

### ISSUE THREAD

**Issue by cwikla** [facebook/react-native#3613]
If I have a package named tgp-base-react packager won't load it and I get "Unable to resolve module tgp-base-react from ...."

It works if it's named tgp_base_react or even tgp-base-react-hello.  Just don't end a package with -react I guess.

**Comment by jsierles** [comment]
@cwikla is this still an issue?

**Comment by christopherdro** [comment]
@facebook-github-bot no-reply
