### ISSUE TITLE
How do I set utf8 to an Text

### ISSUE THREAD

**Issue by vincent-cihan** [facebook/react-native#36147]
### Description

In my APP, I import ttf fonts using ICONS through fontFamily and it always works fine.
Recently, in the latest version of Samsung OS (oneui5.0), inconsistencies occur when bold characters are set in the system Settings. 
After experiments, it was found that the problem was caused by coding format, which could be solved by StandardCharsets.UTF_8, but I could not change the code in react-native. Thanks for your help and guidance.
The modified code of my experiment is as follows：
`public static void showIcon(TextView view) { 
Typeface font = Typeface.createFromAsset(view.getContext().getAssets(), "iconfont.ttf"); 
view.setTypeface(font); 
String iconText = view.getResources().getString(R.string.mine); 
iconText = new String(iconText.getBytes(StandardCharsets.UTF_8)); view.setText(iconText); 
}`

### Version

0.63.3

### Output of `npx react-native info`

NA

### Steps to reproduce

Import custom icon fonts and open bold in the latest version of Samsung System Settings
![showimage-9841907-4806ef000bad3475140decb93b155923_b0b64f2eac2fc41393a6f0bd5704edcb-thumb](https://user-images.githubusercontent.com/16432385/218741918-30f64372-fa30-4776-b632-23532674c0eb.jpg)

### Snack, code example, screenshot, or link to a repository

<img width="756" alt="截屏2023-02-14 20 44 16" src="https://user-images.githubusercontent.com/16432385/218742164-6ae89c65-568d-4936-a8fb-bb5d2539050b.png">
<img width="402" alt="截屏2023-02-14 20 44 28" src="https://user-images.githubusercontent.com/16432385/218742251-08944352-2e86-4872-a384-63ca46729386.png">

`<Text selectable={false}
            style={[style,{
              fontFamily: 'iconfont'
            }]}>
        {String.fromCharCode(parseInt('e96a', 16))}
      </Text>`

**Comment by vincent-cihan** [comment]
Thanks for your reply. I have not found any support for encoding format setting of Text component in the current and later versions. I would like to ask if there is any solution or support plan for later versions.

**Comment by cortinico** [comment]
> Thanks for your reply. I have not found any support for encoding format setting of Text component in the current and later versions. I would like to ask if there is any solution or support plan for later versions.

Sadly, we don't backport fixes to older versions of RN as we're a really small team and our capacity is limited. As you confirmed that this issue is fixed in the latest version of RN, this issue can now be closed
