### ISSUE TITLE
PermissionsAndroid.PERMISSIONS.POST_NOTIFICATIONS is undefined

### ISSUE THREAD

**Issue by humble-programmer** [facebook/react-native#36141]
### Description

The PermissionsAndroid API provides the Android permission strings as constants under PermissionsAndroid.PERMISSIONS. The list of these constants is listed in the documentation. One of these constants is PermissionsAndroid.PERMISSIONS.POST_NOTIFICATIONS that represents the 'android.permission.POST_NOTIFICATIONS' permission.

However, the PermissionsAndroid.PERMISSIONS object actually has no key named POST_NOTIFICATIONS, and the actual key used for the 'android.permission.POST_NOTIFICATIONS' permission is POST_NOTIFICATION (i.e., without an "S" at the end).

### Version

0.70.3

### Output of `npx react-native info`

System:
    OS: macOS 12.3.1
    CPU: (8) arm64 Apple M1
    Memory: 117.19 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.4.0 - /opt/homebrew/bin/node
    Yarn: Not Found
    npm: 8.3.1 - /opt/homebrew/bin/npm
    Watchman: 2022.01.17.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 21, 23, 29, 30, 31, 32, 33
      Build Tools: 30.0.2, 30.0.3, 31.0.0, 33.0.0, 33.0.0
      System Images: android-23 | Google APIs ARM EABI v7a, android-23 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-24 | Google APIs ARM 64 v8a, android-31 | Google APIs ARM 64 v8a, android-33 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 13.3/13E113 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.12 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.3 => 0.70.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

 Import PermissionsAndroid API from react-native and log PermissionsAndroid.PERMISSIONS.POST_NOTIFICATIONS and PermissionsAndroid.PERMISSIONS.POST_NOTIFICATION to the console to see which key has the correct value.

### Snack, code example, screenshot, or link to a repository

import {PermissionsAndroid} from 'react-native';

console.log(PermissionsAndroid.PERMISSIONS.POST_NOTIFICATIONS);
console.log(PermissionsAndroid.PERMISSIONS.POST_NOTIFICATION);

**Comment by lunaleaps** [comment]
Closing as its been addressed

**Comment by rastogi95** [comment]
check POST_NOTIFICATION spelling in react-native/Libraries/PermissionAndroid file and AndroidManifest.xml file
