### ISSUE TITLE
onPress props : TouchableOpacity is not working in the latest version RN-0.71.1

### ISSUE THREAD

**Issue by 98rahul** [facebook/react-native#36157]
### New Version

0.71.1

### Old Version

0.63.4

### Build Target(s)

Android

### Output of `react-native info`

onPress prop is not working..
`<View style={[styles.linkStyle, { backgroundColor: "green" }]}>
                  <TouchableOpacity
                    onPress={() => {
                      console.log("onPress");
                    }}
                  >
                    <Text>Use Registered Alternate Number</Text>
                  </TouchableOpacity>`

### Issue and Reproduction Steps

migrate to the latest RN-0.71.1

**Comment by 98rahul** [comment]
due to the layout had fixed height 
now,issue been resolved

**Comment by SakeFabi** [comment]
Hello @98rahu,l how did you fix? I cannot run it anymore after an upgrade to the newest version of RN.

**Comment by 98rahul** [comment]
> Hello @98rahu,l how did you fix? I cannot run it anymore after an upgrade to the newest version of RN.

check height of layout screen (TouchableOpacity  expected to be under the height define in wrapper View/TouchableOpacity .. ).

**Comment by avoloshko** [comment]
@98rahul what was the problem? I noticed that with 0.71.4 TouchableOpacity sometimes ignores onPress. It's somewhat inconsistent... I have not ideas.

**Comment by 98rahul** [comment]
> @98rahul what was the problem? I noticed that with 0.71.4 TouchableOpacity sometimes ignores onPress. It's somewhat inconsistent... I have not ideas.

insect the **View** wrapper(parent) of TouchableOpacity , make sure it should under the fixed height( probably you had fixed the layout height).
