### ISSUE TITLE
[iOS/iPadOS] - Modal `supportedOrientations` are explicitly required 

### ISSUE THREAD

**Issue by coolersham** [facebook/react-native#36153]
### Description

Since upgrading to the new architecture it seems like the `Modal` component no longer supports all orientations by default. Since the actual supported orientations must be defined in the application's corresponding `.plist` file anyway, this approach seems rather strange and leads to confusion when using the `Modal` component.

I am not sure whether this is intentionally introduced or not, but I think this should behave the same on both platforms.

### Version

0.71.3

### Output of `npx react-native info`

Not relevant for this issue.

### Steps to reproduce

Create a new `react-native` project with the help of the CLI, install all dependencies and pods and build the application on a new iOS/iPadOS device.

### Snack, code example, screenshot, or link to a repository

```
import React, { useState } from "react"

import { Button, Modal, Text, View } from "react-native"

export default function App(): JSX.Element {
  const [visible, setVisible] = useState(false)

  return (
    <View
      style={{
        flex: 1,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "white",
      }}
    >
      <Button title={"Show modal"} onPress={() => setVisible(true)} />
      <Modal visible={visible}>
        <Text>Random content for showcase! :)</Text>
        <Button title={"Hide modal"} onPress={() => setVisible(false)} />
      </Modal>
    </View>
  )
}
```

**Comment by coolersham** [comment]
This problem still persists and should not have been closed.

**Comment by JoaoMosmann** [comment]
This problem still persists.
Also, If you provide a value on the prop that is not on the plist, the app crashes when the modal opens.
