### ISSUE TITLE
[Android] [Android 13] System context menu flickering when trying to double tap to  highlight text

### ISSUE THREAD

**Issue by Roamer77** [facebook/react-native#36168]
### Description

I use `<TextInput/>.` When I try to highlight the entered text with a double tap, the system context menu appears and starts flickering. This error can only be reproduced on physical devices with Android 13. In the Steps to reproduce section, I mention which devices I tested it on

https://user-images.githubusercontent.com/47222852/219026542-24c182ec-cd65-4d55-8194-6c29c8549bc8.mp4

### Version

0.70.3

### Output of `npx react-native info`

System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 878.86 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.1.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.3 - /opt/homebrew/bin/npm
    Watchman: 2022.11.14.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/valiantsin/.rvm/rubies/ruby-2.7.5/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 24, 26, 28, 29, 30, 31, 32, 33
      Build Tools: 26.0.3, 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0
      System Images: android-28 | Google ARM64-V8a Play ARM 64 v8a, android-32 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.3 => 0.70.3 

### Steps to reproduce

1. Add text input component to screen 
2. Enter any text into text input
3. Try to double tap  entered text to highlight it 

Expected result: 
System context menu opens

Actual result: 
System context menu opens and starts flickering

Issue can be reproduced on physical devices with Android 13 :
-  Pixel 7, Android 13; 
-  Galaxy S22 Ultra, Android 13

### Snack, code example, screenshot, or link to a repository

https://snack.expo.dev/@roamer777/android-13-text-highlighting-issue-

**Comment by fabriziobertoglio1987** [comment]
Do you still experience this issue? 

I have four years of experience maintaining facebook/react-native and I specialize in the Text and TextInput components. I currently have 58 [facebook/react-native PRs](https://github.com/facebook/react-native/pulls?q=is%3Apr+author%3Afabriziobertoglio1987+). 

If you still experience this issue, I will prepare a patched release with the fix.

Thanks a lot
