### ISSUE TITLE
Failed to load the app data ,Cannot start the App.

### ISSUE THREAD

**Issue by hemasaitudo** [facebook/react-native#36167]
### Description

App is successfully published to google play console which is released as a beta version .
When i was trying to install the Beta version of apk it is not opening instead it is saying "Failed to read the app data.Cannot start the app".
But the debug apk is working fine which was generated using ./gradlew assembleDebug.
For Generating the release Apk i was using ./gradlew assembleRelease,The build is successfull.when I try to install that release apk it is not opening and throwing the error as mentioned above.
How to resolve this issue Manifest.xml has all the activities as mentioned and no error while publishing to the google play console.
I was running the app in android verison 12. 

### Version

0.63.3

### Output of `npx react-native info`

System:
    OS: Windows 10 10.0.19045
    CPU: (4) x64 Intel(R) Core(TM) i5-2410M CPU @ 2.30GHz
    Memory: 1.22 GB / 7.84 GB
  Binaries:
    Node: 14.17.3 - C:\Program Files\nodejs\node.EXE     
    Yarn: Not Found
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD       
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 23, 27, 29, 30, 31, 32
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 31.0.0
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-31 | Intel x86 Atom_64, android-31 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      Versions: 10.0.17763.0
  IDEs:
    Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7678000
    Visual Studio: Not Found
  Languages:
    Java: 11.0.16 - C:\Program Files\Common Files\Oracle\Java\javapath\javac.EXE
    Python: 3.11.0 - C:\Python311\python.EXE
  npmPackages:
    @react-native-community/cli: ^4.13.0 => 4.14.0
    react: ^16.13.1 => 16.14.0
    react-native: ^0.63.3 => 0.63.5
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

cd android && ./gradlew assembleRelease

### Snack, code example, screenshot, or link to a repository

 <activity android:name="com.facebook.FacebookActivity" android:exported="true" tools:node="merge"
        android:configChanges=
                "keyboard|keyboardHidden|screenLayout|screenSize|orientation"
        android:label="@string/app_name" />
        
    <activity
        android:name="com.facebook.CustomTabActivity"
        android:exported="false"
        tools:node="merge"
        tools:replace="android:exported">
        <intent-filter>
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.DEFAULT" />
            <category android:name="android.intent.category.BROWSABLE" />
            <data android:scheme="@string/fb_login_protocol_scheme" />
        </intent-filter>
    </activity>

**Comment by hemasaitudo** [comment]
> It looks like your issue or the example you provided uses an [unsupported version of React Native](https://github.com/reactwg/react-native-releases/blob/main/README.md#releases-support-policy). Due to the amount of issues we receive, we're currently accepting only new issues against one of the supported version. Please open your issue on [StackOverflow](https://stackoverflow.com/questions/tagged/react-native) to get further community support.

What are the issues that will cause if upgraded to the react-native version 0.71 and what changes should be done to manifest.xml and build.gradle to make the assembleRelease successfull?

**Comment by cortinico** [comment]
> What are the issues that will cause if upgraded to the react-native version 0.71 and what changes should be done to manifest.xml and build.gradle to make the assembleRelease successfull?

Sorry but it's impossible to tell without seeing your project. Please update your project to a later verison of RN and open a new issue.
