### ISSUE TITLE
Invariant Violation: requireNativeComponent: "RNSScreenStackHeaderConfig" was not found in the UIManager.

### ISSUE THREAD

**Issue by mansi-acquaintsoft** [facebook/react-native#36183]
### Description

This is my package.json

"dependencies": {
    "@react-native-community/masked-view": "^0.1.11",
    "@react-navigation/bottom-tabs": "^6.5.4",
    "@react-navigation/native": "^6.1.3",
    "@react-navigation/native-stack": "^6.9.9",
    "@react-navigation/stack": "^6.3.12",
    "react": "17.0.2",
    "react-native": "0.66.4",
    "react-native-gesture-handler": "^2.1.0",
    "react-native-screens": "^3.20.0",
  },

I have also added react-native-reanimated, but getting another issue.
Can anybody suggest on this ?

Thank You

### Version

0.66.4

### Output of `npx react-native info`

System:
    OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
    Memory: 155.03 MB / 15.51 GB
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
    Watchman: 4.9.0 - /usr/bin/watchman
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: AI-213.7172.25.2113.9123335
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.4 => 0.66.4 
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

After installed an application in android, getting this issue

### Snack, code example, screenshot, or link to a repository

![Screenshot_1676551775](https://user-images.githubusercontent.com/119397479/219369513-e3c600ec-e713-4c57-b7ba-8d5e1eeaef94.png)

**Comment by cortinico** [comment]
Hi @mansi-acquaintsoft 
Thanks for reporting this issue.

It seems like this issue is actually unrelated to React Native core but it's realted to react-native-screens. Please open this issue against this other repository:

https://github.com/software-mansion/react-native-screens/issues

I'll be closing this but feel free to reopen if the other repo points back to us as a issue in the core of React Native.
