### ISSUE TITLE
Unable to pass `height`, `width` props to `Image` component 

### ISSUE THREAD

**Issue by rawatnaresh** [facebook/react-native#36182]
### Description

Passing props such as `height`, `width`, `crossOrigin` to the `Image` component throws an error.

![Screen Shot 2023-02-16 at 16 50 06](https://user-images.githubusercontent.com/29520305/219348169-4ddf4b41-6ff9-48f8-8a6f-2b09d209cabf.png)

### Version

>0.71.0

### Output of `npx react-native info`

System:
    OS: macOS 12.6.2
    CPU: (4) x64 Intel(R) Core(TM) i7-5650U CPU @ 2.20GHz
    Memory: 72.01 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nodenv/versions/16.16.0/bin/node
    Yarn: 1.22.19 - ~/.nodenv/versions/16.16.0/bin/yarn
    npm: 8.11.0 - ~/.nodenv/versions/16.16.0/bin/npm
    Watchman: 2022.07.04.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/nareshrawat/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /Users/nareshrawat/.jenv/shims/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.3 => 0.71.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

- Init a new RN project
- Add a `Image` component 
- All the props that are mentioned in the [docs](https://reactnative.dev/docs/image#props) are not supported

### RN > 0.71.0
![Screen Shot 2023-02-16 at 16 58 56](https://user-images.githubusercontent.com/29520305/219350125-9115c59d-0a2c-4986-a5aa-d8683fbab134.png)
### RN < 0.71.0
![Screen Shot 2023-02-16 at 16 59 59](https://user-images.githubusercontent.com/29520305/219350365-e4a1b69a-b11d-41f0-a3ee-49670206a284.png)

**Comment by carlosalmonte04** [comment]
I was able to reproduce. I vote for the typescript interface of Image props needing an update to match the docs.

It also works like this `source={{uri: 'some-uri', height: 200, width: 200}}`.

**Comment by alvessteve** [comment]
Indeed, those props are missing in the .d file. Just did a PR for that

**Comment by carlosalmonte04** [comment]
Nice, thanks @alvessteve. `height` and `width` alone for this PR would have made it cleaner. Did you confirm that `crossOrigin` is still in use?

**Comment by alvessteve** [comment]
yep still in use.

**Comment by rawatnaresh** [comment]
types for following props are also missing 🙏 

- [objectFit](https://reactnative.dev/docs/image#objectfit)
- [referrerPolicy](https://reactnative.dev/docs/image#referrerpolicy)
- [source](https://reactnative.dev/docs/image#source)
- [src](https://reactnative.dev/docs/image#src)
- [srcSet](https://reactnative.dev/docs/image#srcset)
- [tintColor](https://reactnative.dev/docs/image#tintcolor)

**Comment by alvessteve** [comment]
thank you @rawatnaresh ! will do a separate PR for that
