### ISSUE TITLE
[Android] Using relative paths for `ENTRY_FILE` now end up in build failure

### ISSUE THREAD

**Issue by DomiR** [facebook/react-native#36186]
### Description

Before https://github.com/facebook/react-native/commit/bb02ccf13f76f46b8572e2a85d578fd8d4fd9467 we were able to run `ENTRY_FILE="./index.custom.js" npx react-native android --variant="release"` but now I get:
```bash
* What went wrong:
A problem was found with the configuration of task ':app:createBundleConnectdevReleaseJsAndAssets' (type 'BundleHermesCTask').
  - In plugin 'com.facebook.react' type 'com.facebook.react.tasks.BundleHermesCTask' property 'entryFile' specifies file '$HOME/rn-project/android/app/index.custom.js' which doesn't exist.
```

It seems that the entry file is now resolved relative to the android root project. Not sure if this was intended.

### Version

0.71.3

### Output of `npx react-native info`

```bash
System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 799.56 MB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.14.0 - ~/.cache/fnm_multishells/16825_1676559821539/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.3.1 - ~/.cache/fnm_multishells/16825_1676559821539/bin/npm
    Watchman: 2023.01.23.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/lib/ruby/gems/3.1.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      System Images: android-30 | ARM 64 v8a
      Android NDK: 24.0.8215888
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9477386
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.3 => 0.71.3
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

Build release variant while passing in relative path for ENTRY_FILE.

### Snack, code example, screenshot, or link to a repository

```bash
* What went wrong:
A problem was found with the configuration of task ':app:createBundleConnectdevReleaseJsAndAssets' (type 'BundleHermesCTask').
  - In plugin 'com.facebook.react' type 'com.facebook.react.tasks.BundleHermesCTask' property 'entryFile' specifies file '$HOME/rn-project/android/app/index.custom.js' which doesn't exist.
```

**Comment by cortinico** [comment]
> property 'entryFile' specifies file '$HOME/rn-project/android/app/index.custom.js' which doesn't exist.

Does the file `'$HOME/rn-project/android/app/index.custom.js'` exists?

**Comment by DomiR** [comment]
It is still placed in the root folder: `'$HOME/rn-project/index.custom.js'`

Now it expects the path of the entry file to be relative to the android root: `'$HOME/rn-project/android/app'` which was not the case before. I guess `ENTRY_FILE="../../index.custom.js" npx react-native android --variant="release"` would work but it's not consistent with iOS.

**Comment by DomiR** [comment]
@cortinico Thank you very much for looking into this! Cheers 🍻

**Comment by Gijuno** [comment]
The same error shows in react-native 0.71.11. Is there any new way?

**Comment by marouane-edghoughi** [comment]
> A similar error shows in react-native 0.71.11 ("`specifies file '$HOME/PROJECT/android/app/index.js' which doesn't exist.`"), while `> Task :app:createBundleDevelopmentJsAndAssets`, when run `./gradlew clean assembleDevelopment`in `android/`. I set entryFile paths already ("`src/index.tsx`"). Is there any new way? @cortinico

I was able to solve this error by setting the entryFile path inside `android/app/build.gradle`
Navigating from the actual file: `entryFile = file("../../index.tsx")`, knowing that my index.tsx is located in the root of my project. So make sure you're going back to the root from your current location then to your src folder.

**Comment by charlee-dev** [comment]
in my case i had to add this in the android/app/build.gradle.kts:
```gradle
react {
  entryFile = file("../../index.tsx")
}
```

**Comment by eman747** [comment]
change index.ts or index.tsx to index.js

**Comment by PaulHryn** [comment]
> how to skip bundle generation step? i have a brown field android app，and my React-Native code is in another project，when integration with react native, i have this error.

did you found any solution?

**Comment by KingAmo** [comment]
> > how to skip bundle generation step? i have a brown field android app，and my React-Native code is in another project，when integration with react native, i have this error.
> 
> did you found any solution?

see https://github.com/facebook/react-native/issues/44035
