### ISSUE TITLE
YogaKit not installed when flipper is disabled

### ISSUE THREAD

**Issue by gabriellend** [facebook/react-native#36185]
### Description

I was upgrading to React Native 0.71.2 and while I was going through my Podfile I noticed this line:
```
# Note that if you have use_frameworks! enabled, Flipper will not work and
# you should disable the next line.
:flipper_configuration => flipper_config,
```
React Native does seem to enable `use_frameworks!` (as do newer versions of `react-native-firebase`, which I also use), and I don't use flipper anyway, so I commented that line out to adhere to the guidelines. This resulted in the following error in Xcode which no amount of cleaning/restarting/reinstalling could fix:

> Library not found for -lYogaKit

When I check my Podfile.lock, indeed, it is no longer there. If I uncomment the flipper line and `pod install` again, it reappears and builds fine. This isn't a blocker for me, as I can just leave that line uncommented with no consequences, and maybe it isn't even a bug, but I thought I'd bring it to the attention of the community because you never know, it might be important.

### Version

0.71.2 (only one I've tested on)

### Output of `npx react-native info`

System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1
    Memory: 105.11 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 6.14.15 - ~/node_modules/.bin/npm
    Watchman: 2022.06.06.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 31, 33
      Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 33.0.0
      System Images: android-31 | Google Play ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9477386
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.2 => 0.71.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

This is probably as simple as commenting/uncommenting that line in tandem with deleting your Pods folder and doing a fresh pod install for each state, then checking if YogaKit was installed.

### Snack, code example, screenshot, or link to a repository

No need.

**Comment by cortinico** [comment]
> React Native does seem to enable `use_frameworks!` (as do newer versions of `react-native-firebase`, which I also use),

cc @cipolleschi which has more context than me on `use_frameworks!` support

**Comment by cipolleschi** [comment]
I'm sorry for this extremely late reply.

The right way to disable flipper is not to comment that line: commenting that line will result in having Flipper installed, honestly, as that's the default.

The right way to disable flipper is to replace that line with:
```diff
-  flipper_configuration: flipper_config,
+ flipper_configuration: FlipperConfiguration.disabled
```
