### ISSUE TITLE
onPress in ListView require different syntax from onPress outside ListView

### ISSUE THREAD

**Issue by kevinzzz007** [facebook/react-native#3619]
Hi so when I use `ListView` and add a `TouchableHighlight` in it, as following:
```
<ListView
                  dataSource={this.state.dataSource}
                  renderRow={(rowData) => 
                    <View style = {styles.container}>
                      <TouchableHighlight 
                      style = {styles.container}
                      onPress={()=>this._onPressSingleRequest(rowData)}>
```
why do I have to write `()=>this._onPressSingleRequest(rowData)` in the onPress?  In my other view where the `TouchableHighlight` is not in a ListView, I can just use `this._onPressSingleRequest(rowData)`, is this an issue or is there a reason for this?

Thanks!

**Comment by gre** [comment]
you mean

```js
()=>this._onPressSingleRequest(rowData)
```

VS

```js
this._onPressSingleRequest(rowData)
```
?

the first one is a callback that will call your onPressSingleRequest, the second one is **calling directly** that onPressSingleRequest, so if you give this to onPress, it is directly called at `render()` time which is probably not what you want.

---

Also you can rewrite:
```js
()=>this._onPressSingleRequest(rowData)
```
into
```js
this._onPressSingleRequest.bind(this, rowData)
```

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind?redirectlocale=en-US&redirectslug=JavaScript%2FReference%2FGlobal_Objects%2FFunction%2Fbind

**Comment by brentvatne** [comment]
@gre is 100% correct :)

**Comment by kevinzzz007** [comment]
@gre thanks a bunch!

**Comment by kevinzzz007** [comment]
@gre I guess my follow up question would be why does sometimes 
```
()=>this._onPressSingleRequest(rowData)
```
works and sometimes 
```
this._onPressSingleRequest(rowData)
```
works?

**Comment by gre** [comment]
Please show example where the second works

**Comment by satya164** [comment]
@kevindeleon https://babeljs.io/docs/learn-es2015/

**Comment by kevinzzz007** [comment]
@gre here it is in this link: https://github.com/facebook/react-native/blob/62e8ddc20561a39c3c839ab9f83c95493df117c0/Examples/UIExplorer/PushNotificationIOSExample.js
```
var Button = React.createClass({
  render: function() {
    return (
      <TouchableHighlight
        underlayColor={'white'}
        style={styles.button}
        onPress={this.props.onPress}>
        <Text style={styles.buttonLabel}>
          {this.props.label}
        </Text>
      </TouchableHighlight>
    );
  }
});
```

**Comment by gre** [comment]
In your example, there are nothing related to your snippet.

`onPress={ this._sendNotification }` works but `onPress={ this._sendNotification(something) }` wouldn't..

you need to think in term of types. `this._sendNotification` is a function. `this._sendNotification(something)` is **not** a function, it is the result of calling the function which is undefined in this case.

I recommend you to learn a bit more JS, the concept of closure, functions, etc..
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Closures

**Comment by kevinzzz007** [comment]
Ah I see! Thank you so much! I do need to learn more JS, it's something I
need to do ASAP

On Sunday, October 25, 2015, Gaëtan Renaudeau <notifications@github.com>
wrote:

> In your example, there are nothing related to your snippet.
>
> onPress={ this._sendNotification } works but onPress={
> this._sendNotification(something) } wouldn't..
>
> you need to think in term of types. this._sendNotification is a function.
> this._sendNotification(something) is *not* a function, it is the result
> of calling the function which is undefined in this case.
>
> I recommend you to learn a bit more JS, the concept of closure, functions,
> etc..
> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Closures
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/facebook/react-native/issues/3619#issuecomment-150897997>
> .
>


-- 
Kevin Zhao | LinkedIn <http://www.linkedin.com/in/kevinzhaouva> | Personal
Blog <https://medium.com/@kevinzhao> | Github
<https://github.com/kevinzzz007>
(434) 282-5369
Computer Science and Information Technology | University of Virginia 2016
Alpha Kappa Psi Professional Business Fraternity
<http://www.akpsiatuva.org/>

**Comment by chetankotkar** [comment]
@gre thanks a lot sir.. I am new to react native.

**Comment by dobrienlzd** [comment]
@chetankotkar @gre yep this post continues to be important in react native lists. Just ran into the same issue. Thanks to  @kevinzzz007 for bringing up this important issue. I just spent an hour tangling with an alert box going up for every element in my FlatList. So this also is factor with new list types.

**Comment by ayazzali** [comment]
and add my own. Both works:
 <Button title="signUp" onPress={() => {
          debugger;
          if (this.state.isSignUping)
            return this._SignUp.bind(this)()
          else
            this.setState({ isSignUping: true })
        }} />
and second:
 <Button title="login" onPress={this._LogIn.bind(this)} />


maybe this will be helped to someone...
