### ISSUE TITLE
After updating React native to 0.69.8 got following error.

### ISSUE THREAD

**Issue by vaish8529** [facebook/react-native#36204]
### Description

 ERROR  Invariant Violation: ViewPropTypes has been removed from React Native. Migrate to ViewPropTypes exported from 'deprecated-react-native-prop-types'.
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.  
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.

### Version

0.69.8

### Output of `npx react-native info`

npx react-native info
warn Package native-base contains invalid configuration: "dependency.assets" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
warn Package react-native-vector-icons contains invalid configuration: "dependency.assets" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-12650H
    Memory: 1.76 GB / 15.68 GB
  Binaries:
    Node: 14.20.1 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.17 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 29, 30, 31, 33
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 33.0.0
      System Images: android-28 | Google APIs Intel x86 Atom_64, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64, android-30 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-31 | Intel x86 Atom_64, android-31 | Google APIs ARM 64 v8a, android-31 | Google APIs Intel x86 Atom_64, android-33 | Google APIs ARM 64 v8a, android-33 | Google APIs Intel x86 Atom_64, android-33 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: AI-213.7172.25.2113.9014738
    Visual Studio: Not Found
  Languages:
    Java: 11.0.16 - C:\Program Files\Common Files\Oracle\Java\javapath\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.69.8 => 0.69.8
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

react-native run-android

### Snack, code example, screenshot, or link to a repository

![test2](https://user-images.githubusercontent.com/105700183/219848012-e51c139e-0f25-43a3-b0bd-e913c063ba4b.png)

**Comment by ErickMaeda** [comment]
As shown in the error. React Native has removed the `PropTypes` and advise you to migrate to `deprecated-react-native-prop-types`.

You can install the library and migrate it.

`npm i deprecated-react-native-prop-types`

And replace where you have the import

From:
~~`import { ViewPropTypes } from 'react-native';`~~
To:
 `import { ViewPropTypes } from 'deprecated-react-native-prop-types';`

Since release `0.71.0`. They have added it back due to some issues. But they are still planning to remove it on future.

You can check more [here](https://reactnative.dev/blog/2023/01/12/version-071#restoring-proptypes)
