### ISSUE TITLE
iOS: When opening link it won't refresh

### ISSUE THREAD

**Issue by afu1995** [facebook/react-native#36213]
### Description

Hey guys!
I'm having a bug where the first time I open a link it works fine, but the second time it doesn't refresh or reload. The link is for tracking orders, so the URL is different for each order. The first time I open the link in Safari, the website provides the expected information. However, if I go to another order and click on a link with a different URL, the website gives me an error saying it couldn't find the order. But if I refresh or reload the website, it loads the current package.

I've checked the local settings for Safari, and it's set to "Open new tab" when clicking on links, but that doesn't seem to be working. Is there a way to make it open a new tab or refresh the website every time I click on a link?

On Android, it works perfectly. It opens a new browser every time I click on a link, which is what I want to happen on iOS.. ### 

### Version

0.70.6

### Output of `npx react-native info`

System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 43.53 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
    Watchman: 2022.11.14.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9514443
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.70.6 => 0.70.6
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Find order -> Press link -> Opening external link (safari) -> shows current order info -> Go back to app -> Go back to list of orders -> Select different order -> open external link (safari) -> gives "couldn't find order" on safari -> refresh page -> gives the information we need about order

### Snack, code example, screenshot, or link to a repository

`Link.openURL(url)`

**Comment by ysng007** [comment]
How did you solve it? @afu1995
