### ISSUE TITLE
On Android API 31, PermissionsAndroid.request(POST_NOTIFICATIONS) always returns never_ask_again

### ISSUE THREAD

**Issue by Bilal-Abdeen** [facebook/react-native#36212]
### Description

To support the new notifications permission requirements for Android API 33, I added the following call to my code. 
`PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.POST_NOTIFICATIONS)`. 

On an Android API 33 emulator, it works perfectly fine - the user is asked to grant permission, and the returned result is correct. 

However, on an Android API 31 emulator, it always returns `PermissionsAndroid.RESULTS.NEVER_ASK_AGAIN`. I expected it to return `PermissionsAndroid.RESULTS.GRANTED`.

By the way, on an Android API 31 emulator, there are NO problems with the other permissions, e.g. `PERMISSIONS.READ_CONTACTS`. The user is asked, and it returns the user's selection correctly.

### Version

0.71.2

### Output of `npx react-native info`

npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 11.20 GB / 31.90 GB
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.4.1 - C:\Program Files\nodejs\npm.CMD
    Watchman: 20220614.153706.0 - C:\ProgramData\chocolatey\bin\watchman.EXE
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowAllTrustedApps: Disabled
      Versions: 10.0.17763.0, 10.0.19041.0
  IDEs:
    Android Studio: AI-212.5712.43.2112.8512546
    Visual Studio: Not Found
  Languages:
    Java: 11.0.15 - C:\Program Files\Common Files\Oracle\Java\javapath\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.2 => 0.71.2
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

`await PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.POST_NOTIFICATIONS);`

### Snack, code example, screenshot, or link to a repository

```javascript
const checkResult = await PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.POST_NOTIFICATIONS);
console.log("checkResult:", checkResult);
```

**Comment by rufat** [comment]
I'm having the same issue with Bluetooth permissions. Always returns never_ask_again. RN 0.71.3.

**Comment by tahatekin** [comment]
Before android api level 33, you do not need ask permission. You can compile api level 33 ehich change on build.gradle file and use android 33 emulator. You will see notification permission dialog.

**Comment by Bilal-Abdeen** [comment]
> Before android api level 33, you do not need ask permission. You can compile api level 33 which change on build.gradle file and use android 33 emulator. You will see notification permission dialog.

@tahatekin Thank you for your feedback. I don't understand what you are suggesting. Following are my `build.gradle` settings. When I use an Android API 33 emulator, the code works perfectly OK. The user is asked for permission. 

However, when I use an Android API 31 emulator, the code returns `NEVER_ASK_AGAIN`. I understand that the user should NOT be asked for permission on versions earlier than 33. However, I expected the code (on this version) to return `GRANTED`, rater than `NEVER_ASK_AGAIN`.

```gradle
buildToolsVersion = "33.0.0"
minSdkVersion = 21
compileSdkVersion = 33
targetSdkVersion = 33
ndkVersion = "23.1.7779620"
googlePlayServicesAuthVersion = "19.2.0"
```

**Comment by Avishayy** [comment]
Don't ask for the permission if the API level is below 33, as Android doesn't recognize the permission for these versions, you could write it as:
```typescript
let notificationsPermissionCheck: PermissionStatus = "granted";
// The permission exists only for Android API version bigger than 33 (Android 13),
// we can assume it's always granted beforehand
if (Platform.Version >= 33) {
  notificationsPermissionCheck = await PermissionsAndroid.request(
    PermissionsAndroid.PERMISSIONS.POST_NOTIFICATIONS
  );
}

console.log("notificationsPermissionCheck:", notificationsPermissionCheck);
```

**Comment by Bilal-Abdeen** [comment]
> Don't ask for the permission if the API level is below 33, as Android doesn't recognize the permission for these versions, you could write it as:
> 
> ```ts
> let notificationsPermissionCheck: PermissionStatus = "granted";
> // The permission exists only for Android API versions bigger than 33 (Android 13),
> // we can assume it's always granted beforehand
> if (Platform.Version >= 33) {
>   notificationsPermissionCheck = await PermissionsAndroid.request(
>     PermissionsAndroid.PERMISSIONS.POST_NOTIFICATIONS
>   );
> }
> 
> console.log("notificationsPermissionCheck:", notificationsPermissionCheck);
> ```
@Avishayy Thanks, this works perfectly. 

I thought that calling `PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.POST_NOTIFICATIONS)` should return `granted` for earlier versions. If my understanding is correct, I think this needs to be fixed. I am happy to use this workaround until the bug is fixed. 

If my understanding is incorrect, I think the documentation should clarify that clearly. If this is the case, I am happy to submit a PR to update the documentation. Please, confirm.

**Comment by Avishayy** [comment]
I'm not affiliated with react-native's team, I'm just a passer-by.

Either way, your understanding is incorrect. Android doesn't know the permission on older APIs as it simply doesn't exist. 
If Android doesn't recognize a permission when requesting it, it would ask you to "never_ask_again", as in "I don't what's that permission, don't ask me again".

The confusion rises from the fact that notifications are a resource that exists before API 33, it's just that after Android 13, they are locked behind a permission. The correct way to handle it is to explicitly check for the Android version before requesting the permission, it's not a workaround.

**Comment by alex-mironov** [comment]
Weirdly enough I see the same issue on version 33 when requesting that permission:
```
    await PermissionsAndroid.request(
      PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE,
    );
```

It resolves to `never_ask_again` and doesn't pop the permissions modal.

**Comment by vasylnahuliak** [comment]
@alex-mironov

 In Android 13 no WRITE_EXTERNAL_STORAGE permission is needed 
 https://github.com/facebook/react-native/issues/35638#issuecomment-1455114109

For example:

```js
async function hasAndroidPermission() {
  if (Number(Platform.Version) >= 33) {
    return true;
  }

  const permission = PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE;

  const hasPermission = await PermissionsAndroid.check(permission);
  if (hasPermission) {
    return true;
  }

  const status = await PermissionsAndroid.request(permission);
  return status === 'granted';
}
```

**Comment by arsensgitacc** [comment]
Yeah, but the issue is that with < 33 Android versions, user still can manually disable notifications permission from settings of the app. And PermissionsAndroid doesn't give a way to check that, cause it always returns false

**Comment by akshay-engage** [comment]
I encountered this issue while using `targetSdkVersion: 33`.

The required permission was missing from the manifest. After adding the following line, the issue was resolved and the push notification permission prompt started appearing:

`<uses-permission android:name="android.permission.POST_NOTIFICATIONS" />`
