### ISSUE TITLE
NativeEventEmitter: Invariant violation new nativeeventemitter() requires a non-null argument

### ISSUE THREAD

**Issue by pcsaunak** [facebook/react-native#36231]
### Description

I have a custom react native wrapper which works absolutely fine in RN version 0.68 and less, however when I try to upgrade my application to 0.69, I am facing the above error - 

`Invariant violation new nativeeventemitter() requires a non-null argument`

I have also tried to implement other ways of event emitter by following a separate medium article, even if the sample application fails. 

The official documentation does not mention any change when we are upgrading to 0.69 and above; hence, there is no reference for why this is failing. This feels like an issue with the core React Native library.

### Version

0.69 and above 

### Output of `npx react-native info`

System:
    OS: macOS 12.6
    CPU: (10) x64 Apple M1 Pro
    Memory: 43.19 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.15.0/bin/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.5 => 0.69.5 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

I have a link to a repo which has the code implemented. If we execute that code it will simply give us the above error. 
Additionally, I have another library which is 'react-native-zendrive' which has been build by using  this  tutorial https://gist.github.com/brennanMKE/1ebba84a0fd7c2e8b481e4f8a5349b99 
however in this case as well, when we upgrade from 0.68 to 0.69 and above it simply fails. 

### Snack, code example, screenshot, or link to a repository

https://github.com/pcsaunak/JS_Proj_69 

This repository has an example where I have implemented native event emitter for my native module and this does not work.

**Comment by carlosalmonte04** [comment]
`RNCounter` instead of `Counter` on the JavaScript side works for me.

I'm not sure why Counter would have worked before but the code is using `RCT_EXTERN_REMAP_MODULE` to change the name of the module from `Counter` to `RNCounter`.

https://github.com/facebook/react-native/blob/main/Libraries/EventEmitter/NativeEventEmitter.js#L45.
https://github.com/facebook/react-native/blob/main/React/Base/RCTBridgeModule.h#L307.

**Comment by charles-nasd** [comment]
> ### Description
> I have a custom react native wrapper which works absolutely fine in RN version 0.68 and less, however when I try to upgrade my application to 0.69, I am facing the above error -
> 
> `Invariant violation new nativeeventemitter() requires a non-null argument`
> 
> I have also tried to implement other ways of event emitter by following a separate medium article, even if the sample application fails.
> 
> The official documentation does not mention any change when we are upgrading to 0.69 and above; hence, there is no reference for why this is failing. This feels like an issue with the core React Native library.
> 
> ### Version
> 0.69 and above
> 
> ### Output of `npx react-native info`
> System: OS: macOS 12.6 CPU: (10) x64 Apple M1 Pro Memory: 43.19 MB / 16.00 GB Shell: 5.8.1 - /bin/zsh Binaries: Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node Yarn: 1.22.19 - ~/.nvm/versions/node/v16.15.0/bin/yarn npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm Watchman: Not Found Managers: CocoaPods: 1.11.2 - /usr/local/bin/pod SDKs: iOS SDK: Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1 Android SDK: Not Found IDEs: Android Studio: 2021.3 AI-213.7172.25.2113.9123335 Xcode: 14.2/14C18 - /usr/bin/xcodebuild Languages: Java: 11.0.15 - /usr/bin/javac npmPackages: @react-native-community/cli: Not Found react: 18.0.0 => 18.0.0 react-native: 0.69.5 => 0.69.5 react-native-macos: Not Found npmGlobalPackages: _react-native_: Not Found
> 
> ### Steps to reproduce
> I have a link to a repo which has the code implemented. If we execute that code it will simply give us the above error. Additionally, I have another library which is 'react-native-zendrive' which has been build by using this tutorial https://gist.github.com/brennanMKE/1ebba84a0fd7c2e8b481e4f8a5349b99 however in this case as well, when we upgrade from 0.68 to 0.69 and above it simply fails.
> 
> ### Snack, code example, screenshot, or link to a repository
> https://github.com/pcsaunak/JS_Proj_69
> 
> This repository has an example where I have implemented native event emitter for my native module and this does not work.

Any solution to this yet?

**Comment by Neelshah768** [comment]
if you have used react-native-push-notification in your code then please remove that package for iOS in my case I got the error when I used that in iOS.
which run perfectly in android.
