### ISSUE TITLE
[Android] ListView can't scroll when set position:'absolute' in style

### ISSUE THREAD

**Issue by misakuo** [facebook/react-native#3623]
I wanna add a 
mask layer on the ListView, I wrote JSX like this `<View>
                <ListView
                    style={{flex:1,position:'absolute',width:300}}
                    ....../>
                <Mask ....../>
            </View>`, now the ListView can't vertical scrolling, BUT the ListItem still can be clicked and the ViewPager rendered by method `renderHeader` can horizontal scrolling too. It bothered me for a long time. my react-native library's version is 0.12.0, seeking help and very grateful

**Comment by ide** [comment]
Try top: 0, bottom: 0 instead of flex:1 with absolute positioning.

**Comment by misakuo** [comment]
@ide Amazing!!!!! it works!!!! thanks a lot

**Comment by anAngryAnt** [comment]
but why  use 'top: 0, bottom: 0' instead of 'flex:1' works!?
I am confused!

**Comment by oriharel** [comment]
@ide you are awesome!

**Comment by ihewro** [comment]
@ide  you are good!
