### ISSUE TITLE
library not found for -lBase64

### ISSUE THREAD

**Issue by afeichuanqi** [facebook/react-native#36245]
### Description

<img width="812" alt="image" src="https://user-images.githubusercontent.com/51334360/220574072-8fe123f4-76dc-438c-bed7-1e64785dbf21.png">

### Version

0.61.5

### Output of `npx react-native info`

System:
    OS: macOS 11.3.1
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 165.21 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.0 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.3.1 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 27.0.3, 28.0.0, 28.0.2, 28.0.3
      System Images: android-26 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: ^0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1

### Steps to reproduce

An error occurred during the xcode compilation. I don't know if it is the xcode update problem. It can be compiled normally before

### Snack, code example, screenshot, or link to a repository

xcode

**Comment by cortinico** [comment]
> 0.61.5

Closing as this version of React Native is too old and no longer supported.
