### ISSUE TITLE
CustomEvent not Usable under RN Android

### ISSUE THREAD

**Issue by golorry** [facebook/react-native#3624]
The code used to declare the event is as below

var oriEvent = new CustomEvent("oriEvent");

The code works fine in Chrome console but RN Android returns the error message: "Can't find variable: CustomEvent"

I am using RN 0.12.0 version.

Same question is raised in StackOverflow under "React-Native" label: http://stackoverflow.com/questions/33294728/customevent-not-usable-under-rn-android

Thank you!!

**Comment by ide** [comment]
CustomEvent is not an API that is defined by React Native. It is a browser API as you've pointed out. If you want to use it, you could define your own version of CustomEvent e.g. https://github.com/krambuhl/custom-event-polyfill.

**Comment by golorry** [comment]
Thanks. I am using CustomEvent for communication between peer components that aren't in parent-child relationship. The design was one component would trigger an event with data and the other component would subscribe to the event. Is there an alternative way to do this instead of using CustomEvent? Thank you. @ide

**Comment by ide** [comment]
You could use an EventEmitter. There are various libraries like fbemitter and eventemitter3 that work with React Native, and they let you emit any kind of object.

**Comment by golorry** [comment]
@ide Thanks a lot! I used fbemitter. It works!
