### ISSUE TITLE
compile error when integrate react native  with existing android app 

### ISSUE THREAD

**Issue by mistletoe5215** [facebook/react-native#36246]
### Description

 - build error
```
/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/tasks/BundleHermesCTask.kt: (138, 11): This declaration is experimental and its usage must be marked with '@kotlin.ExperimentalStdlibApi' or '@OptIn(kotlin.ExperimentalStdlibApi::class)'
```
 - env
   - agp:7.0.3
   - kotlin:1.6.10
   - react-native:0.71
 

### Version

0.71.3

### Output of `npx react-native info`

System:
    OS: macOS 11.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 198.67 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.13.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.1.2 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.14 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

 intergate rn  latest version into pure native app -> sync 
 - env
   - agp:7.0.3
   - kotlin:1.6.10
   - react-native:0.71
 

### Snack, code example, screenshot, or link to a repository

buildscript {
   
    dependencies {
        classpath Gradle.agp <---- 7.0.3
        classpath "com.facebook.react:react-native-gradle-plugin"
    }

}

**Comment by cortinico** [comment]
Can you re-run your Gradle build with `--scan` and send over the Gradle Scan?
I believe there is somethign else in your project which is overriding the Kotlin version somehow.

**Comment by debian789** [comment]
I have the same problem https://scans.gradle.com/s/acl2xejf3ctj6

**Comment by cortinico** [comment]
> I have the same problem [scans.gradle.com/s/acl2xejf3ctj6](https://scans.gradle.com/s/acl2xejf3ctj6)

From the Gradle scan, it seems like you have Kotlin 1.7.20 inside your `build.gradle.kts` file. Could you share it?

**Comment by debian789** [comment]
> > I have the same problem [scans.gradle.com/s/acl2xejf3ctj6](https://scans.gradle.com/s/acl2xejf3ctj6)
> 
> From the Gradle scan, it seems like you have Kotlin 1.7.20 inside your `build.gradle.kts` file. Could you share it?

The content of the file is as follows





/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import org.gradle.api.internal.classpath.ModuleRegistry
import org.gradle.api.tasks.testing.logging.TestExceptionFormat
import org.gradle.configurationcache.extensions.serviceOf
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
  kotlin("jvm") version "1.6.10"
  id("java-gradle-plugin")
}

repositories {
  google()
  mavenCentral()
}

gradlePlugin {
  plugins {
    create("react") {
      id = "com.facebook.react"
      implementationClass = "com.facebook.react.ReactPlugin"
    }
  }
}

group = "com.facebook.react"

dependencies {
  implementation(gradleApi())
  implementation("com.android.tools.build:gradle:7.3.1")
  implementation("com.google.code.gson:gson:2.8.9")
  implementation("com.google.guava:guava:31.0.1-jre")
  implementation("com.squareup:javapoet:1.13.0")

  testImplementation("junit:junit:4.13.2")

  testRuntimeOnly(
      files(
          serviceOf<ModuleRegistry>()
              .getModule("gradle-tooling-api-builders")
              .classpath
              .asFiles
              .first()))
}

java {
  sourceCompatibility = JavaVersion.VERSION_11
  targetCompatibility = JavaVersion.VERSION_11
}

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile> {
  kotlinOptions { jvmTarget = JavaVersion.VERSION_11.majorVersion }
}

tasks.withType<Test>().configureEach {
  testLogging {
    exceptionFormat = TestExceptionFormat.FULL
    showExceptions = true
    showCauses = true
    showStackTraces = true
  }
}

**Comment by mistletoe5215** [comment]
as i know，kotlin 1.7 has more strict rules than the versions below，but… why not add the ExperimentalStdApi to the warnning Task to avoid the problem🥹

**Comment by cortinico** [comment]
I've investigate this issue, and the root cause seems to be your Gradle version.
Moving to Gradle 7.6 should fix this issue.

Also I've updated RNGP to use code that is compatible down to Kotlin 1.5 (and tested also with 1.4) so this warning will go away:

```
/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/tasks/BundleHermesCTask.kt: (138, 11): This declaration is experimental and its usage must be marked with '@kotlin.ExperimentalStdlibApi' or '@OptIn(kotlin.ExperimentalStdlibApi::class)'
```

**Comment by AnatuGreen** [comment]
For those having this issue when building their react native apps using Expo's EAS service, I deleted my entire Android folder in my project and when I tried eas build again the build was completed successfully.
I hope someone will find this helpful. This gave me a hardddd time.
