### ISSUE TITLE
 Reason: ZipException, message: invalid entry size (expected 911696 but got 911758 bytes). (Run with --stacktrace for more details.)

### ISSUE THREAD

**Issue by ShaoGongBra** [facebook/react-native#36257]
### Description

Execution failed for task ':expo-modules-core:generateReleaseRFile'.
> Could not resolve all files for configuration ':expo-modules-core:releaseCompileClasspath'.
   > Failed to transform react-native-0.70.6-release.aar (com.facebook.react:react-native:0.70.6) to match attributes {artifactType=android-symbol-with-package-name, com.android.build.api.attributes.BuildTypeAttr=release, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Execution failed for JetifyTransform: /Volumes/DATA/project/meisucrm/node_modules/react-native/android/com/facebook/react/react-native/0.70.6/react-native-0.70.6-release.aar.
         > Failed to transform '/Volumes/DATA/project/meisucrm/node_modules/react-native/android/com/facebook/react/react-native/0.70.6/react-native-0.70.6-release.aar' using Jetifier. Reason: ZipException, message: invalid entry size (expected 911696 but got 911758 bytes). (Run with --stacktrace for more details.)
           Suggestions:
            - Check out existing issues at https://issuetracker.google.com/issues?q=componentid:460323&s=modified_time:desc, it's possible that this issue has already been filed there.
            - If this issue has not been filed, please report it at https://issuetracker.google.com/issues/new?component=460323 (run with --stacktrace and provide a stack trace if possible).

### Version

0.70.6

### Output of `npx react-native info`

System:
    OS: macOS 13.1
    CPU: (16) x64 Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
    Memory: 19.16 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - /var/folders/5j/t9hd6v1d3s902h5xb3g1rmv40000gn/T/yarn--1677113236882-0.7892754250112233/node
    Yarn: 1.22.18 - /var/folders/5j/t9hd6v1d3s902h5xb3g1rmv40000gn/T/yarn--1677113236882-0.7892754250112233/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^18.2.0 => 18.2.0 
    react-native: ^0.70.6 => 0.70.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Package release

### Snack, code example, screenshot, or link to a repository

no

**Comment by cortinico** [comment]
> Execution failed for task ':expo-modules-core:generateReleaseRFile'.

Closing as this needs to be reported to Expo here:
https://github.com/expo/expo/issues

I'll be closing this but feel free to reopen if the other repo points back to us as a issue in the core of React Native.
