### ISSUE TITLE
[0.71.3] Unable to resolve modules

### ISSUE THREAD

**Issue by IAndreaGiuseppe** [facebook/react-native#36256]
### Description

After installing the 0.71.3 version my code is unable to resolve any module not related to the application (sub dependencies).
I install "aws-amplify" that depends on "@aws-sdk" and all packages on aws. When I build my application I get:

```
Error: While trying to resolve module `@aws-sdk/util-hex-encoding` from file `C:\Users\...\node_modules\@aws-amplify\core\lib-esm\Signer.js`, the package `C:\Users\...\node_modules\@aws-sdk\util-hex-encoding\package.json` was successfully found. However, this 
package itself specifies a `main` module field that could not be resolved (`C:\Users\...\node_modules\@aws-sdk\util-hex-encoding\dist\cjs\index.js`. Indeed, none of these files exist:
```

The package is installed and the file: `@aws-sdk\util-hex-encoding\dist\cjs\index.js` exists but it cannot be resolved

I try:

change metro config:
metro.config.js - `useWatchman = false` but the error shift to another package, same error.

change metro resolver extensions
see this topic https://stackoverflow.com/a/60126739

Any idea?
Thanks

### Version

0.71.3

### Output of `npx react-native info`

Not able to get this output on windows

### Steps to reproduce

- install a new react-native app: `npx react-native init AwesomeProj`
- install aws-amplify: `npm install aws-amplify amazon-cognito-identity-js @react-native-community/netinfo @react-native-async-storage/async-storage`
- run the application: `npx react-native start --reset-cache`

### Snack, code example, screenshot, or link to a repository

private project

**Comment by cortinico** [comment]
> After installing the 0.71.3 version my code is unable to resolve any module not related to the application (sub dependencies).
> I install "aws-amplify" that depends on "@aws-sdk" and all packages on aws. When I build my application I get:

Have you reported this to AWS?

**Comment by carlosalmonte04** [comment]
i followed the steps and the app is working fine for me.

**Comment by IAndreaGiuseppe** [comment]
Ok, I rebuild a new project from scratch and found where the problem is.

In this project I use `amplify` with `amplify-cli` to setup Lambda functions for the auth flow on the cloud.

Amplify creates a folder inside the project that is read during the build step by the process of react-native and probably try to build all the internal dependencies of the folder.

With the amplify folder I get various dependencies errors, without it all seems to work.

So, is there a way to exclude an entire folder from the building step of react-native? o a better approach? (I would like to mantain the folder on the project)

**Comment by cortinico** [comment]
> Actually I'm investigating on aws sdk for some hint

Can you open an issue on AWS's end here? https://github.com/aws-amplify/amplify-js

**Comment by Soltus** [comment]
Unable to resolve module any module in node_module
