### ISSUE TITLE
Unable to find destination - error code 70

### ISSUE THREAD

**Issue by mertafor** [facebook/react-native#36254]
### Description

This issue has already been reported several times. Unfortunately creating a new project or upgrading results the same . Somehow a simulator cannot be found after running `react-native run-ios`. Only workaround is to use "udid" to target a simulator. Result is same for creating a new project and upgrading.

I also have a project using RN 0.70.6. What I noticed is when I run `react-native run-ios` with 0.71+ on a new project, I see an additional line after workspace follows (there is no psychical iPhone connected, only simulator is available) : 
`info Found Xcode workspace "AwesomeProject.xcworkspace"`
`info Found booted Mert's MacBook Pro, iPhone 14`

As far as I can see, "Mert's MacBook Pro" is my notebook and it shouldn't be in the list. In fact before 0.71, there is no such a message at all. I guess it tries to use notebook's itself as a device and it fails. What I'm saying may not be making sense at all but I'm out options to overcome this problem. I tried since 0.71 released. Tried with 0.71.1, 0.71.2 and today 0.71.3. I don't feel comfortable using udid workaround because it feels like there is something wrong with my setup. I'm reporting this just in case it's related to this problem.

### Version

0.71.3

### Output of `npx react-native info`

System:
    OS: macOS 12.6.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 33.76 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.4.0 - ~/.nvm/versions/node/v19.4.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v19.4.0/bin/yarn
    npm: 9.2.0 - ~/.nvm/versions/node/v19.4.0/bin/npm
    Watchman: 2023.01.30.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/mertdaglaroglu/.rvm/gems/ruby-2.7.6/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9477386
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.5 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.3 => 0.71.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Installing react-native by running : 
`npx react-native@latest init AwesomeProject`

Then going into project folder and running : 
`npx react-native run-ios`

Here is the response :
```
warn Multiple Podfiles were found: ios/Podfile,vendor/bundle/ruby/2.7.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/Podfile. Choosing ios/Podfile automatically. If you would like to select a different one, you can configure it via "project.ios.sourceDir". You can learn more about it here: https://github.com/react-native-community/cli/blob/master/docs/configuration.md
info Found Xcode workspace "AwesomeProject.xcworkspace"
info Found booted Mert’s MacBook Pro, iPhone 14
info Building (using "xcodebuild -workspace AwesomeProject.xcworkspace -configuration Debug -scheme AwesomeProject -destination id=56C0B22D-E1B4-5092-B122-3CED13189C9A")
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 70. To debug build logs further, consider building your app with Xcode.app, by opening AwesomeProject.xcworkspace.
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -workspace awesomeProject.xcworkspace -configuration Debug -scheme awesomeProject -destination id=56C0B22D-E1B4-5092-B122-3CED13189C9A

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES

2023-02-22 20:30:39.052 xcodebuild[48214:3955741] Writing error result bundle to /var/folders/1_/yfl2dbx120s6ckd6x89l6hx00000gn/T/ResultBundle_2023-22-02_20-30-0039.xcresult
xcodebuild: error: Unable to find a destination matching the provided destination specifier:
                { id:56C0B22D-E1B4-5092-B122-3CED13189C9A }

        Available destinations for the "awesomeProject" scheme:
                { platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
                { platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
                { platform:iOS Simulator, id:5FC91CA6-332E-484F-9CB8-EEE2E8032FAF, OS:16.2, name:iPad (10th generation) }
                { platform:iOS Simulator, id:6F54453F-318A-4ECE-9335-2F29831F2059, OS:16.2, name:iPad Air (5th generation) }
                { platform:iOS Simulator, id:ACECE7F8-8871-454E-94C5-B4B351E6672A, OS:16.2, name:iPad Pro (11-inch) (4th generation) }
                { platform:iOS Simulator, id:BAC84EEE-3F0C-479B-9C55-52B048074834, OS:16.2, name:iPad Pro (12.9-inch) (6th generation) }
                { platform:iOS Simulator, id:7290D316-DB28-484A-89A1-C5FFC77DD091, OS:16.2, name:iPad mini (6th generation) }
                { platform:iOS Simulator, id:82739BA2-58BC-433D-B030-A14192B66763, OS:16.2, name:iPhone 14 }
                { platform:iOS Simulator, id:4245305B-548E-442E-8F70-243256CFB731, OS:16.2, name:iPhone 14 Plus }
                { platform:iOS Simulator, id:828DEF9F-2272-4655-8692-A7E154C4F72F, OS:16.2, name:iPhone 14 Pro }
                { platform:iOS Simulator, id:93BDF11C-2793-4D67-A330-98A3BB9E2537, OS:16.2, name:iPhone 14 Pro Max }
                { platform:iOS Simulator, id:908D97E3-049E-42E0-9E88-B8FFC31608EA, OS:16.2, name:iPhone SE (3rd generation) }

```

### Snack, code example, screenshot, or link to a repository

-

**Comment by cortinico** [comment]
> This issue has already been reported several times. Unfortunately creating a new project or upgrading results the same . Somehow a simulator cannot be found after running `react-native run-ios`. Only workaround is to use "udid" to target a simulator. Result is same for creating a new project and upgrading.

Hi @mertafor 

Please report this issue to the CLI repo as the logic to control `run-ios` lives there:
https://github.com/react-native-community/cli/issues

I'll be closing this but feel free to reopen if the other repo points back to us as a issue in the core of React Native.
