### ISSUE TITLE
Build on new app using create-react-native-app give the error on iOS simulator No bundle URL present

### ISSUE THREAD

**Issue by LayMui** [facebook/react-native#36261]
### New Version

0.70.5

### Old Version

NA

### Build Target(s)

ios simulator

### Output of `react-native info`

react-native info
info Fetching system and libraries information...
(node:14280) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
System:
    OS: macOS 13.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 131.64 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.5.5 - /usr/local/bin/npm
    Watchman: 2022.03.21.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8309675
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.14 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.5 => 0.70.5 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
info React Native v0.71.3 is now available (your project is running on v0.70.5).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.71.3
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.70.5
info For more info, check out "https://reactnative.dev/docs/upgrading".

### Issue and Reproduction Steps

https://github.com/LayMui/MyReactNative
run 
```
yarn ios
```

**Comment by cortinico** [comment]
> Build on new app using create-react-native-app

Hi @LayMui 
Thanks for reporting this issue.

It seems like this issue is actually unrelated to React Native core but to Create React Native App. Please open this issue against this other repository:

https://github.com/expo/create-react-native-app/issue

I'll be closing this but feel free to reopen if the other repo points back to us as a issue in the core of React Native.
