### ISSUE TITLE
Execution failed for task ':app:mapDevDebugSourceSetPaths'.  Could not resolve all files for configuration ':app:devDebugRuntimeClasspath'.

### ISSUE THREAD

**Issue by NikhilMasurkar** [facebook/react-native#36264]
### New Version

0.71.3

### Old Version

0.64.2

### Build Target(s)

Could not resolve com.facebook.react:react-native:0.71.3.

### Output of `react-native info`

Task :app:mapDevDebugSourceSetPaths FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5/userguide/command_line_interface.html#sec:command_line_warnings
92 actionable tasks: 92 executed

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mapDevDebugSourceSetPaths'.
> Could not resolve all files for configuration ':app:devDebugRuntimeClasspath'.
   > Could not resolve com.facebook.react:react-native:0.71.3.
     Required by:
         project :app
         project :app > project :react-native-razorpay
         project :app > project :invertase_react-native-apple-authentication
         project :app > project :react-native-async-storage_async-storage
         project :app > project :react-native-community_datetimepicker
         project :app > project :react-native-community_masked-view
         project :app > project :react-native-community_netinfo
         project :app > project :react-native-firebase_analytics
         project :app > project :react-native-firebase_app
         project :app > project :react-native-firebase_crashlytics
         project :app > project :react-native-firebase_dynamic-links
         project :app > project :react-native-firebase_messaging
         project :app > project :react-native-firebase_perf
         project :app > project :react-native-google-signin_google-signin
         project :app > project :lottie-react-native
         project :app > project :react-native-app-signature-helper
         project :app > project :react-native-code-push
         project :app > project :react-native-config
         project :app > project :react-native-device-info
         project :app > project :react-native-document-picker
         project :app > project :react-native-email-link
         project :app > project :react-native-exception-handler
         project :app > project :react-native-fbsdk-next
         project :app > project :react-native-file-viewer
         project :app > project :react-native-freshchat-sdk
         project :app > project :react-native-fs
         project :app > project :react-native-image-crop-picker
         project :app > project :react-native-in-app-review
         project :app > project :react-native-linear-gradient
         project :app > project :react-native-orientation
         project :app > project :react-native-pg-react-native-sdk
         project :app > project :react-native-restart
         project :app > project :react-native-safe-area-context
         project :app > project :react-native-screens
         project :app > project :react-native-share
         project :app > project :react-native-sms-retriever
         project :app > project :react-native-splash-screen
         project :app > project :react-native-svg
         project :app > project :react-native-vector-icons
         project :app > project :react-native-video
         project :app > project :react-native-webview
      > Could not resolve com.facebook.react:react-native:0.71.3.
         > Could not get resource 'https://maven.cashfree.com/release/com/facebook/react/react-native/0.71.3/react-native-0.71.3.pom'.
            > Could not GET 'https://maven.cashfree.com/release/com/facebook/react/react-native/0.71.3/react-native-0.71.3.pom'. Received status code 403 from server: Forbidden
   > Could not find com.facebook.react:react-android:.
     Required by:
         project :app > project :react-native-gesture-handler

### Issue and Reproduction Steps

I'm typing to build the app after upgrade all the packages but still I'm getting this error. can you tell me where I'm wrong

**Comment by cortinico** [comment]
Can you share your `android/app/build.gradle` and `android/build.gradle`?

**Comment by NikhilMasurkar** [comment]
> Can you share your `android/app/build.gradle` and `android/build.gradle`?

yes i will share you

**Comment by NikhilMasurkar** [comment]
this is android/build.gradle

// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "31.0.0"
        minSdkVersion = 21
        compileSdkVersion = 31
        targetSdkVersion = 30
        ndkVersion = "20.1.5948944"
        googlePlayServicesAuthVersion = "16.0.1"
        firebaseIidVersion = "18.0.0"
        kotlin_version = '1.6.10' // <- add this line

    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
         classpath 'com.android.tools.build:gradle:7.4.1'
         classpath 'com.google.gms:google-services:4.3.14'
         classpath 'com.google.firebase:firebase-crashlytics-gradle:2.9.4'
         classpath 'com.google.firebase:perf-plugin:1.4.2'
         classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.8.10" // <- add this line

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {

    def REACT_NATIVE_VERSION = new File(['node', '--print',"JSON.parse(require('fs').readFileSync(require.resolve('react-native/package.json'), 'utf-8')).version"].execute(null, rootDir).text.trim())

    configurations.all {
        resolutionStrategy {
            // Remove this override in 0.65+, as a proper fix is included in react-native itself.
            force "com.facebook.react:react-native:" + REACT_NATIVE_VERSION
             }
        }
        
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        google()
        jcenter()
        maven { url 'https://www.jitpack.io' }
        maven { url 'https://maven.google.com' }
        maven {
              url "https://github.com/VdoCipher/maven-repo/raw/master/repo"
        }
    }
}

**Comment by cortinico** [comment]
The issue you're having is because you haven't followed the upgrade helper.
This is how the `android/app/build.gradle` on a fresh 0.71 project should look like:
https://github.com/facebook/react-native/blob/0.71-stable/template/android/app/build.gradle

**Comment by NikhilMasurkar** [comment]
thank you @cortinico
