### ISSUE TITLE
TypeScript transform error when upgrade react native from 0.70.7 to 0.71.3

### ISSUE THREAD

**Issue by huanguolin** [facebook/react-native#36266]
### Description

TypeScript transform error when upgrade react native from 0.70.7 to 0.71.3.
Work fine with 0.70.x, 0.66.3.

### React Native Version

0.71.3

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 12.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
    Memory: 724.33 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
    Watchman: 2023.02.20.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/leyserkids/.rvm/rubies/ruby-2.7.7/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.3 => 0.71.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. clone mini reproduce repo: https://github.com/huanguolin/rn-0.71-ts-transform-error/tree/master
2. yarn
3. yarn iOS

### Snack, code example, screenshot, or link to a repository

mini reproduce repo: https://github.com/huanguolin/rn-0.71-ts-transform-error/tree/master

error info:
error: asyncThrottle.ts: /Users/leyserkids/Desktop/sourcecode/AwesomeProject/asyncThrottle.ts: Property types[0] of UnionTypeAnnotation expected node to be of a type ["FlowType"] but instead got "TSTypeReference"

error screenshoot:
![Screen Shot 2023-02-23 at 19 19 14](https://user-images.githubusercontent.com/12430413/220880415-af4fcf10-32ac-43a8-9f95-1b0a1b517d63.png)

**Comment by SharvanTech5** [comment]
Can setup typescript properly 
Share package.json

**Comment by huanguolin** [comment]
@SharvanTech5 see mini reproduce repo: https://github.com/huanguolin/rn-0.71-ts-transform-error/tree/master

**Comment by huanguolin** [comment]
Now this issue also reproduce to 0.73.
