### ISSUE TITLE
StyleSheet.create typing not working 

### ISSUE THREAD

**Issue by SusulAdam** [facebook/react-native#36276]
### Description

I noticed that after adding a type to StyleSheet.create<{link: ViewStyle}>, the link object is not checked if it is a ViewStyle and allows to add e.g. fontSize 

### React Native Version

0.70.5, 0.67.5

### Output of `npx react-native info`

Android Studio: 2021.1 AI-211.7628.21.2111.8139111
Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild

Languages:
    Java: 15.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.5 => 0.70.5 

### Steps to reproduce

Add for example this style code with StyleSheet.create typing:

```
const styles = StyleSheet.create<{
  container: ViewStyle
}>({
  container: {
    alignItems: 'center',
    fontSize: 15,
    fontWeight: '500',
  },
})
```

It should be type error because ViewStyle doesn't have e.g. fontSize and fontWeight
```
    fontSize: 15,
    fontWeight: '500',
```

It seems to me that in older versions react native this type error appears.

### Snack, code example, screenshot, or link to a repository

<img width="300" alt="Screenshot 2023-02-24 at 09 10 47" src="https://user-images.githubusercontent.com/64583871/221126422-016aa8e6-7aad-4832-9192-81b60df84c13.png">

**Comment by camilossantos2809** [comment]
I also have a problem with typing in StyleSheet, but in my case it doesn't infer functions correctly.

```
const styles = StyleSheet.create({
  bgExample: (val: boolean) => {
    if (val) return { backgroundColor: "red" };
    return { backgroundColor: "green" };
  },
});

const SomeScreen = () => {
  return <View style={styles.bgExample(refreshing)}>
}
```
This example using 0.71.4 shows a typescript error: 
`This expression is not callable.
  No constituent of type 'ViewStyle | TextStyle | ImageStyle' is callable.ts(2349)`

**Comment by xDreamLand** [comment]
Having the same issue as @camilossantos2809.

Code works fine at runtime. I don't see anything in the StyleSheet types which indicates that it accepts functions.

[**typescriptlang.org - Playground link**](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgZRgTwDYFNkAstbwC+cAZlBCHAERRYCGAxjALQB29MwAbltQNwAoQYwhsAzvEmYs4uAF4U6bHgIwAdIzqcsACgSC4cUWxj1gbLFABciQ0bLYAHrYCMAGntGAVgFdJwKRoAMJiMFimttSMEeFQ1J4OcPQYwADmbACS4SDiUTGmVtT2RIlwAEYwbLa6AEIAqgAqjQDyAHIA+siZAFoAorZsviDlVgCUCgB8cPpecADuwAAmMLi2Dc3tXb19ZUb04mBYzABKnMAQbnsVTADWaRS+bEuhGNBRdEvFRkRjgr9CQRYJyQWBwJZYUj0XwYKTKWRCIA)

**Comment by dcjones1** [comment]
From https://github.com/facebook/react-native/blob/d2a873956520806e434084d2d48dc0a4ee913f07/Libraries/StyleSheet/StyleSheet.d.ts#L31 we can see the types that are allowed to be returned.

Updating those types to the following 
```typescript
export namespace StyleSheet {
  type NamedStyles<T> = {[P in keyof T]: ViewStyle | TextStyle | ImageStyle | ((...props: unknown[]) => ViewStyle | TextStyle | ImageStyle)};

  /**
   * Creates a StyleSheet style reference from the given object.
   */
  export function create<T extends NamedStyles<T> | NamedStyles<any>>(
    styles: T | NamedStyles<T>,
  ): T;
    
  /** other exports... **/
}
```

Then if there are any type issues with your styles, you'll see errors surfaced like this:
<img width="837" alt="Screenshot 2023-06-01 at 5 03 41 PM" src="https://github.com/facebook/react-native/assets/45345625/3103be2c-6ef9-4687-b19d-8e6311be2e00">

**Comment by camilossantos2809** [comment]
Is there already a PR for this?
It's an interesting feature of the StyleSheet, and having type declarations could make it easier to use and discover.
