### ISSUE TITLE
RefreshControlPropsAndroid.size has wrong type

### ISSUE THREAD

**Issue by donaldkwong** [facebook/react-native#36274]
### Description

RefreshControlPropsAndroid.size is [currently typed](https://github.com/facebook/react-native/blob/5d26ceaa236684c7bd6d0d9001ff2c8908d88c29/Libraries/Components/RefreshControl/RefreshControl.d.ts#L52) to be `number | undefined`, but the [documentation](https://reactnative.dev/docs/refreshcontrol#size-android)  indicates this should be `string | undefined` instead. Additionally, the underlying Java code tries to cast this to a String and, if given a number, will throw a runtime exception.

### React Native Version

0.71.0

### Output of `npx react-native info`

Not relevant to this bug.

### Steps to reproduce

Make a `RefreshControl` with a `size` prop whose value is a number. Run on an Android device and notice that it throws a runtime exception. Change the value to `large` and you'll get a typescript error (but no more Java runtime exception).

### Snack, code example, screenshot, or link to a repository

https://snack.expo.dev/@donaldkwong/refreshcontrol-bug

**Comment by donaldkwong** [comment]
This repos in the latest version.

**Comment by carlosalmonte04** [comment]
Hey @donaldkwong thanks for finding this. I can submit a PR.

**Comment by roniemartinez** [comment]
I cannot see any fix related to this.

```
TS2769: No overload matches this call.
Overload 1 of 2, (props: RefreshControlProps): RefreshControl, gave the following error.
Type string is not assignable to type number
```
