### ISSUE TITLE
React Portal children gets overriden in Fabric

### ISSUE THREAD

**Issue by intergalacticspacehighway** [facebook/react-native#36273]
### Description

Portals are not officially documented in RN. But I think it can be a very useful feature and it almost works! 

## Why do we need Portals?
Modal component cannot be used as a general-purpose overlay solution as multiple modals on iOS are [tricky](https://github.com/facebook/react-native/pull/31498#issuecomment-906078310) and Modal also prevents behind view touches. [Userland solution ](https://github.com/gorhom/react-native-portal) loses React context when children are mounted.

## Issue
I got createPortal working on Paper architecture [by removing this assertion](https://github.com/intergalacticspacehighway/react-native/commit/e4d59954f2b049860cdf1bc78d24c265bde300ed). However I ran into an issue on Fabric. After some digging, I found that the issue is in the React Fabric JS renderer, not native side. The Portal gets mounted momentarily but gets overridden by the HostRoot children.

Here is the [repro](https://github.com/intergalacticspacehighway/react-native/blob/fix/react-portals/packages/rn-tester/js/RNTesterAppShared.js). In the repro, two calls are made to `updateHostContainer`. [1](https://github.com/facebook/react-native/blob/85245af8801240555e51fe7193b99da665974317/Libraries/Renderer/implementations/ReactFabric-dev.js#L17544) and [2](https://github.com/facebook/react-native/blob/85245af8801240555e51fe7193b99da665974317/Libraries/Renderer/implementations/ReactFabric-dev.js#L17301). The second call from HostRoot overrides the children mounted by Portal. These findings are with some console.logs, I have no clue how it works. I'll try to dig more and update. I think @rickhanlonii can help 🙏 

### React Native Version

0.71.3

### Output of `npx react-native info`
```
System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 417.80 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.15 - ~/.nvm/versions/node/v16.13.1/bin/yarn
    npm: 8.12.1 - ~/.nvm/versions/node/v16.13.1/bin/npm
    Watchman: 2022.03.14.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9514443
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.13 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: 10.0.0 => 10.0.0 
    react: 18.2.0 => 18.2.0 
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

- Run the [RN Tester Repro](https://github.com/intergalacticspacehighway/react-native/blob/fix/react-portals/packages/rn-tester/js/RNTesterAppShared.js), portal gets mounted and unmounted (not visible, it happens fast). It only stays mounted if you [comment this line](https://github.com/facebook/react-native/blob/85245af8801240555e51fe7193b99da665974317/Libraries/Renderer/implementations/ReactFabric-dev.js#L17301)
- Make sure you're on Fabric
- If you change arch to Paper, it'll work as expected.

### Snack, code example, screenshot, or link to a repository

[RNTester Repro](https://github.com/intergalacticspacehighway/react-native/blob/fix/react-portals/packages/rn-tester/js/RNTesterAppShared.js)

**Comment by intergalacticspacehighway** [comment]
More findings - 

[createContainerChildSet](https://github.com/facebook/react-native/blob/6e28e2dc99dd385354d9c833f1d3b413bbba0de4/Libraries/Renderer/implementations/ReactFabric-dev.js#L16869) gets called twice. As it returns a [new childSet](https://github.com/facebook/react-native/blob/6e28e2dc99dd385354d9c833f1d3b413bbba0de4/ReactCommon/react/renderer/uimanager/UIManagerBinding.cpp#L359), second call overrides the children added previously. I think we might have to append if it's already created.

**Comment by javache** [comment]
Portals are not supported in React Native. You can achieve similar behaviour with custom native components by manually "portalling" children to a different container.

**Comment by natew** [comment]
@javache they aren't supported, but is there any plan to support them? They are a pretty big missing gap between web and native, would be nice to have a place to track their plan.

Manually moving things around will break context entirely, which makes them very awkward in practice.

**Comment by kirillzyusko** [comment]
@natew @intergalacticspacehighway @Braden1996 as @javache said - it's most likely will not be part of a `react-native` anytime soon, so I created a library that does that. It's called [react-native-teleport](https://github.com/kirillzyusko/react-native-teleport) and is designed to use all native primitives (i. e. `createPortal` on web), but in a declarative way to deliver true portal experience in `react-native`.

It should not have all limitations that JS based solutions have and should bring even more advanced features, such as "teleporting" (moving view across tree while preserving its internal state) and some others (they are planned) 👀

**Comment by natew** [comment]
That’s huge. It’s hard to understate how big of a missing primitive it is to not have portals on native, so many bad APIs and workarounds.

**Comment by Braden1996** [comment]
> [@natew](https://github.com/natew) [@intergalacticspacehighway](https://github.com/intergalacticspacehighway) [@Braden1996](https://github.com/Braden1996) as [@javache](https://github.com/javache) said - it's most likely will not be part of a `react-native` anytime soon, so I created a library that does that. It's called [react-native-teleport](https://github.com/kirillzyusko/react-native-teleport) and is designed to use all native primitives (i. e. `createPortal` on web), but in a declarative way to deliver true portal experience in `react-native`.
> 
> It should not have all limitations that JS based solutions have and should bring even more advanced features, such as "teleporting" (moving view across tree while preserving its internal state) and some others (they are planned) 👀

Absolutely incredible @kirillzyusko! Very excited to try this out.
