### ISSUE TITLE
Execution failed for task ':app:mergeReleaseNativeLibs'.

### ISSUE THREAD

**Issue by hrichi-kabil** [facebook/react-native#36288]
### Description

Hello,
 When I trying to build Android I always receive this error

I am using Expo 47

![Capture d’écran 2023-02-24 à 17 19 10](https://user-images.githubusercontent.com/60201696/221230909-6e3b9de6-3d03-4347-b163-d4168e533bba.png)

### React Native Version

0.70.5

### Output of `npx react-native info`

System:
    OS: macOS 11.4
    CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
    Memory: 96.59 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.14.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 9.5.1 - ~/hrichi/seven-mobile.fr/node_modules/.bin/npm
    Watchman: 2023.02.06.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 13.0/13A233 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^18.1.0 => 18.1.0 
    react-native: 0.70.5 => 0.70.5 
    react-native-macos: Not Found

### Steps to reproduce

.

### Snack, code example, screenshot, or link to a repository

![Capture d’écran 2023-02-24 à 17 25 16](https://user-images.githubusercontent.com/60201696/221232456-c94208e3-5119-4b53-9c29-bf8d0b9f07a3.png)

**Comment by cortinico** [comment]
Hi @hrichi-kabil 
Thanks for reporting this issue.

As you said you're using Expo, please open this issue against this other repository:

https://github.com/expo/expo/issues

I'll be closing this but feel free to reopen if the other repo points back to us as a issue in the core of React Native.

**Comment by hrichi-kabil** [comment]
> Hi @hrichi-kabil Thanks for reporting this issue.
> 
> As you said you're using Expo, please open this issue against this other repository:
> 
> https://github.com/expo/expo/issues
> 
> I'll be closing this but feel free to reopen if the other repo points back to us as a issue in the core of React Native.

done
