### ISSUE TITLE
[Android] AlertIOS for android: AlertDialog.Builder

### ISSUE THREAD

**Issue by PhilippKrone** [facebook/react-native#3628]
Hello,

I've written a component which unifies AlertIOS and AlertDialog.Builder by creating "GenericAlert.show" which takes exactly the same parameters as AlertIOS.alert() does and either shows AlertIOS or a custom AlertDialog.Builder, depending on Platform.OS. 

What is the best solution for publishing? Does it make sense to make a PR for this repo or should I publish it as npm package? I guess - as its so basic - it's getting implemented for this repo anyway.

@ide you might know how to best handle it :)

Thanks!
Philipp

**Comment by ide** [comment]
It seems reasonable to provide a cross-platform component in this case because RN already ships with AlertIOS, and if people are going to be writing the exact same Platform.OS checks many times, your component can take care of that job.

I would mainly want to know if there are some platform-specific features that we'd lose by having a cross-platform component (and that we can't address by having one or two platform-specific options, similar to how the View component has a small number of platform-specific props like renderToHardwareTextureAndroid and shouldRasterizeIOS).

cc @sahrens, this sounds like the Alert equivalent of what you did for Switch.

**Comment by PhilippKrone** [comment]
Another question is whether there is already something like this in the internal FB repository - then it might not be worth making the PR right now.

**Comment by ide** [comment]
cc @mkonicek: is there a cross-platform Alert component that you are planning to open source? I see `Alert` is listed on the Known Issues page, but not sure if that's Android-only or works across both platforms.

**Comment by cosmith** [comment]
Did you find a solution for dialogs that have both 3 buttons or more and a title and a description? There is an old Android bug that makes doing this cleanly difficult.

**Comment by PhilippKrone** [comment]
@cosmith Indeed my solution is only for 2 or less buttons.

**Comment by mkonicek** [comment]
See https://facebook.github.io/react-native/docs/known-issues.html#platform-parity

**Comment by mkonicek** [comment]
The idea it to simply support `alert()`.

**Comment by mkonicek** [comment]
On Android there will also be a separate Dialog module.

**Comment by mkonicek** [comment]
`alert()` would delegate to `AlertIOS` and the Android dialog Module. Does that make sense? Haven't thought about alerts that much yet, plan to work on Intent next.

**Comment by chirag04** [comment]
@mkonicek if alert is just going to delegate to AlertIOS and Android dialog Module then it can live outside of react-native core. One less thing to maintain. \_(ツ)_/¯

**Comment by mkonicek** [comment]
Although `alert()` is a very basic function and having it by default would be nice, wouldn't it?

**Comment by cosmith** [comment]
+1 for `alert()` available by default, I think most apps are going to have at least one alert dialog.

**Comment by chirag04** [comment]
``alert()`` by default would definitely be handy. In general i have observed that things that can be in user land should be in user land rather than core. Less maintenance. We can always make exceptions for small things like ``alert()``

@vjeux and @ide thoughts?

**Comment by vjeux** [comment]
We should definitely get alert working on android as well

**Comment by PhilippKrone** [comment]
@chirag04 @mkonicek @cosmith My solution is currently exactly like AlertIOS.alert() except that it is working for two buttons only. Is AlertIOS working for more than 2? What other features are required / possible on android which should be included in your opinion? I'm using 

````javascript
AlertDialog.Builder ad = ...
ad.setTitle..
ad.setMessage...
ad.setPositiveButton...
ad.setNegativeButton...
````

I'm not really used to android development but would be glad to help here.

Regards
Philipp

**Comment by mkonicek** [comment]
@PhilippKrone we already have a `Dialog` module, just need to look into how good the API is and open sourcing it. I might not have bandwidth to reply here for a while because of other features, conference and PTO but definitely want to get `alert()` working.

Just an idea: someone could already get `alert()` working now by showing a Toast on Android (the module is already open source).

**Comment by felipebueno** [comment]
Hi, @PhilippKrone !

Any updates on this ```Dialog``` module? :smiley:

**Comment by PhilippKrone** [comment]
@felipebueno I have not worked on it as @mkonicek has said that its already done internally. If you need one now, look at https://github.com/aakashns/react-native-dialogs

**Comment by felipebueno** [comment]
Hey sorry, @PhilippKrone I mentioned your name by mistake. It should be @mkonicek 😅

**Comment by lucasferreira** [comment]
I made another module to help in show alerts for Android, I think that could help some https://github.com/lucasferreira/react-native-simpledialog-android

**Comment by mkonicek** [comment]
Open sourcing internal modules is the highest-pri for the community: https://productpains.com/product/react-native/

I'll work on that.

**Comment by cosmith** [comment]
:+1: thanks!

**Comment by johanatan** [comment]
@PhilippKrone Did you release your project anywhere?

**Comment by PhilippKrone** [comment]
@johanatan No, but take a look at https://github.com/aakashns/react-native-dialogs - I didnt bother to release it as 1) there are already such components 2) its going to be open sourced anyway as its worked on with the highest priority

**Comment by dzannotti** [comment]
@mkonicek any updates on this one?

**Comment by cosmith** [comment]
It has been open sourced in RN 0.17, see https://github.com/facebook/react-native/commit/3a3af8a385583c7aabfad5f8ff5daa69aa29953f

You can use `alert` directly or the `Alert` module.

**Comment by cosmith** [comment]
This issue should be closed BTW.

**Comment by dzannotti** [comment]
thanks @cosmith
