### ISSUE TITLE
Unable to install apk file on android emulator

### ISSUE THREAD

**Issue by Waltari10** [facebook/react-native#36289]
### Description

I'm trying to create an apk file of my app and then run it on emulator. However upon installing it I am receiving the error: adb: failed to install app/android/app/build/outputs/apk/dev/release/app-dev-release-unsigned.apk: Failure [INSTALL_FAILED_INVALID_APK: Failed to extract native libraries, res=-2]

What could be going wrong?

### React Native Version

0.71.3

### Output of `npx react-native info`

System:
    OS: macOS 13.2.1
    CPU: (8) x64 Apple M1
    Memory: 28.57 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
    Watchman: 2022.10.17.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/valtterilaine/.rvm/gems/ruby-3.0.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 31, 32
      Build Tools: 28.0.3, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 33.0.2
      System Images: android-23 | Google APIs ARM EABI v7a, android-31 | Google APIs ARM 64 v8a, android-31 | Google Play ARM 64 v8a, android-32 | Google APIs ARM 64 v8a, android-32 | Google Play ARM 64 v8a, android-32 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8815526
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.12 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. ./gradlew bundledevRelease
2. sign with jarsigner -keystore ./app.keystore -storepass <secret> ~/app/android/app/build/outputs/apk/dev/release/app-dev-release-unsigned.apk app
3. adb install ~/app/android/app/build/outputs/apk/dev/release/app-dev-release-unsigned.apk

receive error:
adb: failed to install ~/app/android/app/build/outputs/apk/dev/release/app-dev-release-unsigned.apk: Failure [INSTALL_FAILED_INVALID_APK: Failed to extract native libraries, res=-2]

Expecting not to get error

### Snack, code example, screenshot, or link to a repository

-

**Comment by Waltari10** [comment]
Let me know if there some info I should provide still.

**Comment by cortinico** [comment]
Can you try on the latest patch as suggested by the bot?

**Comment by Waltari10** [comment]
> Can you try on the latest patch as suggested by the bot?

Sorry, yes tried upgrading to 70.7 but had same issue still.

**Comment by dezudas** [comment]
I upgraded to 0.71.3 still not able to run in android emulator

**Comment by cortinico** [comment]
Does this happen also on a empty project from template?

**Comment by Waltari10** [comment]
With a fresh npx react-native init it seems to work with
```
./gradlew assembleRelease
adb install app-release.apk
```

**Comment by Waltari10** [comment]
Got it now! Seems doing `zipalign -p -f -v 4 app.apk` and then using `apksigner` instead of `jarsigner` fixed it!

**Comment by cortinico** [comment]
> Got it now! Seems doing `zipalign -p -f -v 4 app.apk` and then using `apksigner` instead of `jarsigner` fixed it!

Closing then 👍

**Comment by harisbaig100** [comment]
Here's a shorter version of the solution:

### Solution:

1. **Remove Corrupted System Images**:
   - Delete corrupted system images from:
     ```bash
     ~/Library/Android/sdk/system-images
     ```

2. **Delete Existing AVD**:
   - In **Android Studio**, go to **AVD Manager** and delete the problematic AVD. Alternatively, remove it from:
     ```bash
     ~/.android/avd
     ```

3. **Reinstall Correct System Image (Google Play)**:
   - In **SDK Manager**, install the **Google Play** system image (do not select Google APIs with 16 KB page size).

4. **Create New AVD**:
   - Create a new AVD using the **Google Play** image.

5. **Run React Native App**:
   - Run your app on the new, properly configured emulator.

This should fix the **"install_failed_invalid_apk"** error.
