### ISSUE TITLE
ReactInstanceManager.builder() causing a crash on the second time starting MyReactActivity. The first time it is working without any issues.

### ISSUE THREAD

**Issue by amitsri007** [facebook/react-native#36284]
### Description

java.lang.NoClassDefFoundError: com.facebook.react.jscexecutor.JSCExecutor
                                                                                                    	at com.facebook.react.ReactInstanceManagerBuilder.getDefaultJSExecutorFactory(ReactInstanceManagerBuilder.java:363)
                                                                                                    	at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:316)
                                                                                                    	at com.example.demointegrationrnjava.MyReactActivity.onCreate(MyReactActivity.java:40)

Souce Code (Currently implementing with Android only)

https://github.com/Amit-Sri-007/RN_Integraton

### React Native Version

0.71.3

### Output of `npx react-native info`

System:
    OS: macOS 12.6.3
    CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
    Memory: 27.81 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.2.0 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 9.3.1 - /usr/local/bin/npm
    Watchman: 2022.11.28.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 28, 29, 30, 31, 32, 33
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0
      Android NDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9514443
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.3 => 0.71.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

I'm using the following link for integration.

https://reactnative.dev/docs/integration-with-existing-apps

### Snack, code example, screenshot, or link to a repository

![image](https://user-images.githubusercontent.com/67737510/221172861-6061aebb-5e61-4cad-baf3-2b519924855d.png)

![image](https://user-images.githubusercontent.com/67737510/221173427-d8e31329-a6c8-475d-8ec7-ed13072efde2.png)

**Comment by Amit-Sri-007** [comment]
[settings.gradle.txt](https://github.com/facebook/react-native/files/10823790/settings.gradle.txt)
[build.gradle.txt](https://github.com/facebook/react-native/files/10823794/build.gradle.txt)
[build.gradle.txt](https://github.com/facebook/react-native/files/10823797/build.gradle.txt)

**Comment by Amit-Sri-007** [comment]
The source code can be found below. Currently, I'm only working on Android integration.

https://github.com/Amit-Sri-007/RN_Integraton

**Comment by MintBerrry** [comment]
Ran into the same issue following the integration guide for android
