### ISSUE TITLE
[iOS] Multiline TextInput fires onFocus() at the end of scroll

### ISSUE THREAD

**Issue by UGhari** [facebook/react-native#36295]
### Description

I'm not one to normally create issues for bugs as usually i find solutions online or figure it out eventually but this one has been persistent for over a week now. Very strange issue **only occuring on iOS devices.**. Both simulator and real iOS device (iPhone 13 Pro Max) behave the same way.

The only source online i've been able to find that accurately describes the issue is [here](https://stackoverflow.com/questions/38885599/prevent-textinput-to-focus-while-scrolling-on-ios)

**The problem**
If I have a large multiline TextInput filled with text and the keyboard is currently dismissed, when I scroll up/down on the TextInput at the end of the touch event the keyboard will appear. However, this is a scroll event not a touch event the keyboard should not appear in this instance. I can also confirm at the end of the scroll event onFocus() is fired. On Android the TextInput works as it should.

Wrapping the TextInput in a scrollview and disabling scroll of TextInput hasn't helped.

I have confirmed this behavior doesn't happen in for example the iOS notes application. This issue can be fustrating say if the user inputs a large amount of information and wants to proof read the extract without keyboard present

Happy to try other solutions listed in comments.

### React Native Version

0.70.6

### Output of `npx react-native info`

System:
    OS: macOS 13.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 35.34 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 18.7.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.15.0 - /usr/local/bin/npm
    Watchman: 2022.08.15.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 28, 30, 31, 33
      Build Tools: 28.0.3, 29.0.2, 30.0.0, 30.0.2, 30.0.3, 31.0.0
      System Images: android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8815526
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.5 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.6 => 0.70.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. Create a TextInput component with `multiline={true}`
2. Fill the TextInput so the user needs to scroll the input to read more text entered
3. Dismiss the keyboard
4. Scroll up or down on the TextInput
5. The keybaord will reappear when it shouldn't and the user will be sent back to last selection point

I've noticed the keyboard only appears if the touch end occurs inside the TextInput. Say for example your TextInput isn't 100% height if you scroll but finger ends outside of TextInput the keyboard will not appear and onFocus will not be triggered

### Snack, code example, screenshot, or link to a repository

```
import React, { useState } from 'react';
import { Keyboard, TextInput, TouchableOpacity } from 'react-native';

export const Description = () => {
    const [inputDescription, setInputDescription] = useState<string>('');
    return (
        <TouchableOpacity style={{ flex: 1, backgroundColor: 'yellow' }} onPress={() => Keyboard.dismiss()}>
            <TextInput
                style={{ height: '100%', width: '80%', backgroundColor: 'pink' }}
                multiline={true}
                onChangeText={text => setInputDescription(text)}
                value={inputDescription}
            />
        </TouchableOpacity>
    );
};
```
![testinput-scroll](https://user-images.githubusercontent.com/15021364/221387167-5e8053b8-f959-4712-bcfa-71c33c38a3b1.gif)

**Comment by UGhari** [comment]
Can confirm it occurs on latest version

**Comment by UGhari** [comment]
Anybody got any updates for this issue?

**Comment by fabriziobertoglio1987** [comment]
Do you still experience this issue? 

I have four years of experience maintaining facebook/react-native and I specialize in the Text and TextInput components. I currently have 58 [facebook/react-native PRs](https://github.com/facebook/react-native/pulls?q=is%3Apr+author%3Afabriziobertoglio1987+). 

If you still experience this issue, I will prepare a patched release with the fix.

Thanks a lot

**Comment by LuanNguyen-HnL** [comment]
Any updates on this? This still occurs on 0.79
