### ISSUE TITLE
Flatlist freezes after closing the modal window (iOS)

### ISSUE THREAD

**Issue by R0LLeX** [facebook/react-native#36298]
### Description

Sometimes, after closing the modal window, all the content that is inside the flatlist freezes, while everything that is outside the flatlist is completely clickable and workable. Only restarting the application helps. This problem appeared after updating RN from 0.70.5 to 0.71.1
react-native-reanimated from 2.14.1 to 2.14.4 (with version 3.0.0-rc.10 also freezes)

### React Native Version

0.71.1

### Output of `npx react-native info`

System:
    OS: macOS 12.5
    CPU: (4) x64 Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
    Memory: 5.85 GB / 20.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.7.0 - /var/folders/cz/lxmgg7bd08lf1m_bsjpw4ml80000gn/T/yarn--1677430909452-0.38245306054555117/node
    Yarn: 1.22.19 - /var/folders/cz/lxmgg7bd08lf1m_bsjpw4ml80000gn/T/yarn--1677430909452-0.38245306054555117/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v18.7.0/bin/npm
    Watchman: 2022.12.05.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9514443
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.1 => 0.71.1
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

no answer

### Snack, code example, screenshot, or link to a repository

no answer

**Comment by manosKas** [comment]
this happens to me too

i suspect that it occurs either when a modal is shown and then dismissed, or when opening another app from withing my app, like for example, when you press a link and safari opens up and then when I return to my app, some flatlist items are unresponsive
