### ISSUE TITLE
class android.view.alpha not found

### ISSUE THREAD

**Issue by jiqimaogou** [facebook/react-native#3629]
![f203959f-0e5d-4a34-8f0b-b3ed0dbac05f](https://cloud.githubusercontent.com/assets/1407040/10688141/afbb80c8-79a4-11e5-913b-7101ffd38d0e.jpeg)

**Comment by astreet** [comment]
Are you sure you don't have local changes to one of the `redbox_*.xml` layout files. We don't reference that package from those layouts. Alternately, this could be an Android framework issue in which case I suggest searching google or asking on stackoverflow.com
