### ISSUE TITLE
main.jsbundle does not exist. This must be a bug with React Native!

### ISSUE THREAD

**Issue by kurucaner** [facebook/react-native#36294]
### Description

I ran `eas build --platform ios` and console threw an error.

![Screenshot 2023-02-25 at 1 58 09 PM](https://user-images.githubusercontent.com/86489794/221374901-998a9b1c-31a7-42a1-9d47-8aa5eef07a4f.png)

### React Native Version

0.70.5

### Output of `npx react-native info`

System:
    OS: macOS 13.2
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 106.86 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 9.2.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /Users/canerkuru/.rvm/gems/ruby-3.0.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.5 => 0.70.5 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

- eas login
- eas build:configure
- eas build --platform ios

### Snack, code example, screenshot, or link to a repository

 eas build --platform ios

**Comment by marcodluz** [comment]
I'm having the same problem for a few days already! Can we get support on this?
