### ISSUE TITLE
Building RCT-Folly can't find `json_pointer.h` when archiving with custom build configuration

### ISSUE THREAD

**Issue by sanderdewilde** [facebook/react-native#36299]
### New Version

0.71.1

### Old Version

0.68.2

### Build Target(s)

Any ios device (arm64)

### Output of `react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 12.5.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 260.41 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.13.1/bin/yarn
    npm: 8.7.0 - ~/.nvm/versions/node/v16.13.1/bin/npm
    Watchman: 2023.01.30.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/sander/.rvm/gems/ruby-3.0.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.1 => 0.71.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Issue and Reproduction Steps

We've upgraded our application to use hermes.

Archiving gives issues as building RCT-Folly does not find `json_pointer.h`:
```
/Users/sander/src/qargo/mobile-app/ios/Pods/RCT-Folly/folly/json_pointer.cpp:17:10: fatal error: 'folly/json_pointer.h' file not found
#include <folly/json_pointer.h>
         ^~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```
The file however exists, I can resolve it in `/Users/sander/src/qargo/mobile-app/ios/Pods/RCT-Folly/json_pointer.h`.

The error only appears when archiving for a non-default build configuration (we have a `Test` build configuration next to `Debug` and `Release`). To rule out any configuration discrepancies, I've removed and re-created the build configuration from the `Release` one. The only properties that are different are the Pods configuration file (although their content is the same), the product name, the bundle identifier and the entitlements.

So archiving the `Release` build works fine, building and running the `Test` build (e.g. on a device) works fine as well. It's specifically the archive that fails.

My Podfile:
```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

pod 'RNSentry', :path => '../node_modules/@sentry/react-native/RNSentry.podspec'

platform :ios, min_ios_version_supported
prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
flipper_config = FlipperConfiguration.disabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => false
end

target 'QargoMobileApp' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )


  target 'QargoMobileAppTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )
    
    ENVFILES = {
      'Debug' => '$(PODS_ROOT)/../../environment/dev.env',
      'Release' => '$(PODS_ROOT)/../../environment/prod.env',
      'Test' => '$(PODS_ROOT)/../../environment/test.env'
    }

    # see https://github.com/CocoaPods/CocoaPods/issues/11402
    installer.generated_projects.each do |project|
      project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings["DEVELOPMENT_TEAM"] = "XXX"
          end
      end
    end

    installer.pods_project.targets.each do |target|
      # https://stackoverflow.com/questions/64040154/xcode-12-error-multiple-commands-produce-accessibilityresources-bundle
      if target.name == "React-Core-AccessibilityResources"
        target.remove_from_project
      end
      if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
        target.build_configurations.each do |config|
          config.build_settings["DEVELOPMENT_TEAM"] = "XXX"
        end
      end

      if target.name == 'react-native-config'
        target.build_configurations.each do |config|
          config.build_settings['ENVFILE'] = ENVFILES[config.name]
        end
      end
    end
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
```

Inspired by https://github.com/facebook/react-native/issues/32451 I've tried adding
```
if target.name == 'RCT-Folly'
  target.build_configurations.each do |config|
    config.build_settings['HEADER_SEARCH_PATHS'] = "$(inherited) ${PODS_ROOT}/RCT-Folly/folly"
  end
end
```
but without luck.

**Comment by cipolleschi** [comment]
Hi @sanderdewilde, thanks for the issue.

Could you provide a small repo with a repro? 

My feeling is that 
```ruby
if target.name == 'RCT-Folly'
  target.build_configurations.each do |config|
    config.build_settings['HEADER_SEARCH_PATHS'] = "$(inherited) ${PODS_ROOT}/RCT-Folly/folly"
  end
end
```
this should work, but the right line should be:
```diff
if target.name == 'RCT-Folly'
  target.build_configurations.each do |config|
-    config.build_settings['HEADER_SEARCH_PATHS'] = "$(inherited) ${PODS_ROOT}/RCT-Folly/folly"
+    config.build_settings['HEADER_SEARCH_PATHS'] = "$(inherited) \"${PODS_ROOT}/RCT-Folly\""
  end
end
```

Notice that the escaped `\"` are needed! 

Let me know if it works.

**Comment by sanderdewilde** [comment]
Hi @cipolleschi, during the creation of the repro I discovered it was caused by Sentry, which included
```
pod 'RNSentry', :path => '../node_modules/@sentry/react-native/RNSentry.podspec'
```
in our Podfile somehow, while this should be auto-linked instead.

Removing the line resolved the issue.
