### ISSUE TITLE
npx react-native init issue

### ISSUE THREAD

**Issue by grandwaterman** [facebook/react-native#36290]
### Description

Downloading template
✖ Copying template
error Error: Couldn't find the "/var/folders/6k/j31dr17d75b0dbs96wyrcv9h0000gn/T/rncli-init-template-wQ7wAu/node_modules/react-native/template.config.js file inside "react-native" template. Please make sure the template is valid.

I followed the instruction step by step from React Native Document, but keep getting this error. No problem starting with Expo, it is smooth and good. 

### React Native Version

@latest

### Output of `npx react-native info`

error: unknown command 'info'
(Did you mean init?)

### Steps to reproduce

npx react-native init reactnew

               ######                ######
             ###     ####        ####     ###
            ##          ###    ###          ##
            ##             ####             ##
            ##             ####             ##
            ##           ##    ##           ##
            ##         ###      ###         ##
             ##  ########################  ##
          ######    ###            ###    ######
      ###     ##    ##              ##    ##     ###
   ###         ## ###      ####      ### ##         ###
  ##           ####      ########      ####           ##
 ##             ###     ##########     ###             ##
  ##           ####      ########      ####           ##
   ###         ## ###      ####      ### ##         ###
      ###     ##    ##              ##    ##     ###
          ######    ###            ###    ######
             ##  ########################  ##
            ##         ###      ###         ##
            ##           ##    ##           ##
            ##             ####             ##
            ##             ####             ##
            ##          ###    ###          ##
             ###     ####        ####     ###
               ######                ######

                  Welcome to React Native!
                 Learn once, write anywhere

✔ Downloading template
✖ Copying template
error Error: Couldn't find the "/var/folders/6k/j31dr17d75b0dbs96wyrcv9h0000gn/T/rncli-init-template-lVm17w/node_modules/react-native/template.config.js file inside "react-native" template. Please make sure the template is valid. Read more: https://github.com/react-native-community/cli/blob/master/docs/init.md#creating-custom-template.

###     ####        ####     ###
            ##          ###    ###          ##
            ##             ####             ##
            ##             ####             ##
            ##           ##    ##           ##
            ##         ###      ###         ##
             ##  ########################  ##
          ######    ###            ###    ######
      ###     ##    ##              ##    ##     ###
   ###         ## ###      ####      ### ##         ###
  ##           ####      ########      ####           ##
 ##             ###     ##########     ###             ##
  ##           ####      ########      ####           ##
   ###         ## ###      ####      ### ##         ###
      ###     ##    ##              ##    ##     ###
          ######    ###            ###    ######
             ##  ########################  ##
            ##         ###      ###         ##
            ##           ##    ##           ##
            ##             ####             ##
            ##             ####             ##
            ##          ###    ###          ##
             ###     ####        ####     ###
               ######                ######

                  Welcome to React Native!
                 Learn once, write anywhere

✔ Downloading template
✖ Copying template
error Error: Couldn't find the "/var/folders/6k/j31dr17d75b0dbs96wyrcv9h0000gn/T/rncli-init-template-lVm17w/node_modules/react-native/template.config.js file inside "react-native" template. Please make sure the template is valid. Read more: https://github.com/react-native-community/cli/blob/master/docs/init.md#creating-custom-template.

**Comment by ThakurBallary** [comment]
0.71.4

**Comment by jsoneaday** [comment]
Adding --npm fixed this for me. I used reactnative@latest which gave me version 0.71.6

By way you're too robotic about your demands the point is to make a better product not to follow rules that do not help devs. You could get the likely version by just checking the timestamp of his post and that would limit the possible versions he is using. Then you would do some due diligence and find the nature of the issue.

Very disappointing.

**Comment by atlj** [comment]
Another fix would be to use an older version of `yarn` such as `1.22.19`

**Comment by Ali33hamdaoua** [comment]
> Based on this [Stackoverflow Answer](https://stackoverflow.com/a/71725307/8833362) adding `--npm` resolved the issue for me.
> 
> Full command: `npx react-native@latest init AwersomeProject --npm`
> 
> From github repo [react-native-community-cli](https://github.com/react-native-community/cli/blob/main/docs/init.md#initializing-project-with-custom-template)

The best answer

**Comment by Irtiza-Atiq** [comment]
> Based on this [Stackoverflow Answer](https://stackoverflow.com/a/71725307/8833362) adding `--npm` resolved the issue for me.
> 
> Full command: `npx react-native@latest init AwersomeProject --npm`
> 
> From github repo [react-native-community-cli](https://github.com/react-native-community/cli/blob/main/docs/init.md#initializing-project-with-custom-template)

Yess this command worked like a charm! <3
