### ISSUE TITLE
KeyboardAvoidingView in Android does not work when setDecorFitsSystemWindows is set to false

### ISSUE THREAD

**Issue by vkundapur** [facebook/react-native#36306]
### Description

I am trying to draw the background of the view behind the navigation bars.
<img width="400" alt="image" src="https://user-images.githubusercontent.com/104626733/221534332-eb716e66-af7e-4bc6-a42e-80d7fc4f88ca.png">

For this, I tried setting `WindowCompat.setDecorFitsSystemWindows(getWindow(), false);` which draws the content behind the navigation bar but `KeyboardAvoidingView` stops working.

### React Native Version

0.71.3

### Output of `npx react-native info`

System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 2.23 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 1.22.18 - ~/.nvm/versions/node/v16.15.0/bin/yarn
    npm: 8.10.0 - ~/.nvm/versions/node/v16.15.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /Users/vivek/.rvm/gems/ruby-2.7.6/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 21, 23, 28, 29, 30, 31, 33, 33
      Build Tools: 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0, 33.0.0, 33.0.1, 33.0.2
      System Images: android-27 | Google APIs ARM 64 v8a, android-33 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9514443
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.18 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.5 => 0.70.5
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. In the Code sample provided, comment the `onCreateView` and `onCreate` methods
2. Run the sample code.
3. Click on the input box in the screen

Notice that the `KeyboardAvoidingView` works as expected. But also, we see the navigation bar as a white stip.
<img width="400" alt="image" src="https://user-images.githubusercontent.com/104626733/221539611-00dd1648-765e-4ed3-8af5-81f8bd375da7.png">

1. Uncomment the `onCreateView` and `onCreate` methods
2. Run the sample code.
3. Click on the input box in the screen

The background is drawn behind the navigation bar. But notice that the `KeyboardAvoidingView` does not work as expected. The bottom buttons get hidden behind the keyboard.
<img width="400" alt="image" src="https://user-images.githubusercontent.com/104626733/221540399-58ca387c-f281-420e-98e1-ab349c3e36fa.png">

### Snack, code example, screenshot, or link to a repository

```
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * @format
 */

import React from 'react';
import {
  KeyboardAvoidingView,
  Platform,
  SafeAreaView,
  ScrollView,
  StatusBar,
  Text,
  TextInput,
  useColorScheme,
  View,
} from 'react-native';

const backgroundColor = '#FEA47F';
const inputBackgroundColor = '#F97F51';

function App(): JSX.Element {
  const isDarkMode = useColorScheme() === 'dark';

  return (
    <SafeAreaView style={[{flexGrow: 1, backgroundColor}]}>
      <StatusBar
        barStyle={isDarkMode ? 'light-content' : 'dark-content'}
        backgroundColor={backgroundColor}
      />
      <KeyboardAvoidingView
        style={{flexGrow: 1, justifyContent: 'space-between'}}
        behavior={Platform.OS === 'ios' ? 'padding' : undefined}>
        <ScrollView
          contentInsetAdjustmentBehavior="automatic"
          contentContainerStyle={{flexGrow: 1}}
          style={{backgroundColor}}>
          <View
            style={[
              {
                backgroundColor,
                flex: 1,
                marginHorizontal: 16,
                justifyContent: 'space-between',
              },
            ]}>
            <View style={{marginTop: 12}}>
              <InputBox />
            </View>
            <View style={{marginBottom: 24}}>
              <Button />
            </View>
          </View>
        </ScrollView>
      </KeyboardAvoidingView>
    </SafeAreaView>
  );
}

const InputBox = () => {
  return (
    <View
      style={{
        flex: 1,
        backgroundColor: inputBackgroundColor,
        borderRadius: 8,
      }}>
      <TextInput placeholder={'Enter something'} />
    </View>
  );
};

const Button = () => {
  return (
    <View
      style={{
        backgroundColor: inputBackgroundColor,
        borderRadius: 12,
        paddingVertical: 20,
        paddingHorizontal: 12,
        alignItems: 'center',
      }}>
      <Text>Button</Text>
    </View>
  );
};

export default App;
```

```
package com.keyboardtest;

import android.content.Context;
import android.os.Bundle;
import android.util.AttributeSet;
import android.view.View;
import android.view.ViewGroup;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.core.graphics.Insets;
import androidx.core.view.ViewCompat;
import androidx.core.view.WindowCompat;
import androidx.core.view.WindowInsetsCompat;

import com.facebook.react.ReactActivity;
import com.facebook.react.ReactActivityDelegate;
import com.facebook.react.defaults.DefaultNewArchitectureEntryPoint;
import com.facebook.react.defaults.DefaultReactActivityDelegate;

public class MainActivity extends ReactActivity {

    /**
     * Returns the name of the main component registered from JavaScript. This is used to schedule
     * rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "KeyboardTest";
    }

    /**
     * Returns the instance of the {@link ReactActivityDelegate}. Here we use a util class {@link
     * DefaultReactActivityDelegate} which allows you to easily enable Fabric and Concurrent React
     * (aka React 18) with two boolean flags.
     */
    @Override
    protected ReactActivityDelegate createReactActivityDelegate() {
        return new DefaultReactActivityDelegate(
                this,
                getMainComponentName(),
                // If you opted-in for the New Architecture, we enable the Fabric Renderer.
                DefaultNewArchitectureEntryPoint.getFabricEnabled(), // fabricEnabled
                // If you opted-in for the New Architecture, we enable Concurrent React (i.e. React 18).
                DefaultNewArchitectureEntryPoint.getConcurrentReactEnabled() // concurrentRootEnabled
        );
    }

    @Nullable
    @Override
    public View onCreateView(@Nullable View parent, @NonNull String name, @NonNull Context context, @NonNull AttributeSet attrs) {
        if (parent != null) {
            ViewCompat.setOnApplyWindowInsetsListener(parent, (v, windowInsets) -> {
                Insets insets = windowInsets.getInsets(WindowInsetsCompat.Type.systemBars());
                // Apply the insets as a margin to the view. Here the system is setting
                // only the bottom, left, and right dimensions, but apply whichever insets are
                // appropriate to your layout. You can also update the view padding
                // if that's more appropriate.
                ViewGroup.MarginLayoutParams mlp = (ViewGroup.MarginLayoutParams) v.getLayoutParams();
                mlp.topMargin = insets.top;
                v.setLayoutParams(mlp);

                // Return CONSUMED if you don't want want the window insets to keep being
                // passed down to descendant views.
                return WindowInsetsCompat.CONSUMED;
            });
        }
        return super.onCreateView(parent, name, context, attrs);
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        WindowCompat.setDecorFitsSystemWindows(getWindow(), false);
    }

}
```

**Comment by vkundapur** [comment]
The same issue is present in `0.71.3`

**Comment by Aalian2241** [comment]
I spent 2 hours on this sounds crazy yes and I'm a beginner at this, but from all I've checked out, tested, and researched, on android, the navigation strip is always going to have its own space and background, however on iOS, you can draw your View Component behind the navigation strip.

Though if you want your View's background to be drawn behind the Navigation Bar **on android,**  I found an alternate to use a third-party library to set its background color. You can set it to have the same background color as your View Component


`import { useEffect } from 'react';
import NavigationBarColor from 'react-native-navigation-bar-color';

function MyComponent() {
  useEffect(() => {
    // Change the navigation strip color to red when the component mounts
    NavigationBarColor.setColor('#ff0000');

    // Reset the navigation strip color when the component unmounts
    return () => NavigationBarColor.setColor('#000000');
  }, []);

  return (
    <View style={{ flex: 1 }}>
      {/* your component content here */}
    </View>
  );
}`

The KeyboardAvoidingView issue isn't connected to that, I feel that trying to achieve the View component being drawn behind the navigation strip is breaking your code atm. 
Please update me and correct me on where I might be off

**Comment by vkundapur** [comment]
Thanks @Aalian2241. `react-native-navigation-bar-color` would be useful in some scenarios but would not work if we use images at the bottom and if the screens have different background colours.

**Comment by Aalian2241** [comment]
> Thanks @Aalian2241. `react-native-navigation-bar-color` would be useful in some scenarios but would not work if we use images at the bottom and if the screens have different background colours.

I understand, this is how it will stay for android, the max we could do is probably code it so that the `react-native-navigation-bar-color` sets the navigation strip color according to the background screen's color

Though if you're on iOS, you can just use the background View instead as intended. Would be keen to know if there is a way to work around it for android

**Comment by niteshdangi** [comment]
@vkundapur try setting behavior="padding" for android too, I was able to fix mine with this.
` <KeyboardAvoidingView
            behavior="padding" // <-- add this
       >
                ...
  </KeyboardAvoidingView>
`

**Comment by antoncojocaru** [comment]
Try to set  value of `behavior` prop (on` KeyboardAvoidingView`) to `height`

Like this:
`<KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : 'height'}>`

**Comment by aurelticot** [comment]
I faced the exact same issue (RN 0.73).

I was using the `height` behaviour as recommended by RN and it was working as expected until I set `window.setDecorFitsSystemWindows(false)` in `MainActivity.java` to draw under the Android navigation bar.

Setting the behaviour to `padding` solved the issue and I don't see any impacts where it's used, so far so good.

It still looks a bug somewhere in the KeyboardAvoidingView.
