### ISSUE TITLE
RCTCxxBridge.mm line 1528 Thread 5: EXC_BAD_ACCESS (code=1, address=0x0)

### ISSUE THREAD

**Issue by Mr-Persona** [facebook/react-native#36301]
### Description

There's been a weird crash on the iOS app. Now we haven't a clue. An error occurred in this line of code: 
_jsMessageThread->runonQueue(onComplete);

### React Native Version

0.68.2

### Output of `npx react-native info`

System:
    OS: macOS 13.1
    CPU: (8) x64 Apple M1 Pro
    Memory: 16.71 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.0.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
    Watchman: 2022.07.04.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.68.2 => 0.68.2
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Random crash

### Snack, code example, screenshot, or link to a repository

https://note.youdao.com/yws/api/personal/file/WEBce570f7f409763aed46202541a16fca3?method=download&shareKey=3a9c43f5eb48d0ed93ac80de53c8ce37

**Comment by Mr-Persona** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by cortinico** [comment]
Please provide at least the full stacktrace

**Comment by Mr-Persona** [comment]
> Please provide at least the full stacktrace

I got some information from Xcode, and information about the crash is limited. Xcode -> Organizer -> Crashes

first step: https://note.youdao.com/yws/api/personal/file/WEB20365ef70f60b885007875b783e383df?method=download&shareKey=794d272ebf34379ba3537677c3e0b1d2

second step: https://note.youdao.com/yws/api/personal/file/WEB59e047093a45005d9c3a2ed7b679eec3?method=download&shareKey=4a37e48a032cbef7d2683eba58e59dbb

third step: https://note.youdao.com/yws/api/personal/file/WEB50a3e2212275bd435c5259489d4ee4c3?method=download&shareKey=aade8f03e59650ede9b77c24f8a2b415

**Comment by Mr-Persona** [comment]
> Please provide at least the full stacktrace

I got some information from Xcode, and information about the crash is limited. Xcode -> Organizer -> Crashes

first step: [image](https://note.youdao.com/yws/api/personal/file/WEB20365ef70f60b885007875b783e383df?method=download&shareKey=794d272ebf34379ba3537677c3e0b1d2)

second step: [image](https://note.youdao.com/yws/api/personal/file/WEB59e047093a45005d9c3a2ed7b679eec3?method=download&shareKey=4a37e48a032cbef7d2683eba58e59dbb)

third step: [image](https://note.youdao.com/yws/api/personal/file/WEB50a3e2212275bd435c5259489d4ee4c3?method=download&shareKey=aade8f03e59650ede9b77c24f8a2b415)

**Comment by Mr-Persona** [comment]
> Please provide at least the full stacktrace

I got some information from Xcode, and information about the crash is limited. Xcode -> Organizer -> Crashes

<img width="1488" alt="1 (1)" src="https://user-images.githubusercontent.com/81129400/221738299-27fe00ad-eef2-44f1-9031-a0972f73a7b2.png">
<img width="1490" alt="2 (1)" src="https://user-images.githubusercontent.com/81129400/221738316-9082f269-6191-4e3e-9484-d3ce01e079da.png">
<img width="1496" alt="3 (1)" src="https://user-images.githubusercontent.com/81129400/221738330-7d332c0f-53b9-4990-b960-0f31aad2796c.png">

**Comment by maheshannu** [comment]
@Mr-Persona  I am Also getting same issue for RN 0.71.0. Do you have any solution for that?

**Comment by Mr-Persona** [comment]
> @Mr-Persona @cortinico I am Also getting same crashes for RN 0.71.0. Do you have any solution for that?

This is a bizarre question. I don't have a solution right now.

**Comment by Praveer-grover** [comment]
@Mr-Persona Did you manage to fix this somehow?

**Comment by jcgertig** [comment]
@cortinico Hi
Im having that same issue react native 0.68 
OS version: iOS 15.6.1
Model: iPhone XS Max

It was caught via crashalytics and have not seen it myself

```
Fatal Exception: RCTFatalException: non-std C++ exception
0  CoreFoundation                 0x99288 __exceptionPreprocess
1  libobjc.A.dylib                0x16744 objc_exception_throw
2  mobile                         0x185558 RCTFormatError + 166 (RCTAssert.m:166)
3  mobile                         0x19a6f8 -[RCTCxxBridge handleError:] + 1222 (RCTCxxBridge.mm:1222)
4  mobile                         0x198f94 __34-[RCTCxxBridge _initializeBridge:]_block_invoke + 730 (RCTCxxBridge.mm:730)
5  mobile                         0x1aba20 facebook::react::RCTMessageThread::tryFunc(std::__1::function<void ()> const&) + 73 (RCTMessageThread.mm:73)
6  mobile                         0x1ab7b4 invocation function for block in facebook::react::RCTMessageThread::runAsync(std::__1::function<void ()>) + 46 (RCTMessageThread.mm:46)
7  CoreFoundation                 0x725a4 __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__
8  CoreFoundation                 0x73500 __CFRunLoopDoBlocks
9  CoreFoundation                 0xb048 __CFRunLoopRun
10 CoreFoundation                 0x1ebc8 CFRunLoopRunSpecific
11 mobile                         0x196918 +[RCTCxxBridge runRunLoop] + 378 (RCTCxxBridge.mm:378)
12 Foundation                     0x6941c __NSThread__start__
13 libsystem_pthread.dylib        0x19ac _pthread_start
14 libsystem_pthread.dylib        0xe68 thread_start
```

**Comment by Mr-Persona** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by WayneKim92** [comment]
I got the same issue

**Comment by Mr-Persona** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by cortinico** [comment]
Hi,
In this issue tracker we accept only issues that are in English.
I'm closing this for now, please consider translating your comments to English and we can keep on following up.
Thanks.

**Comment by jesse-one-app** [comment]
@cortinico can you re open this issue. I am seeing the same crash on RN 0.71.11

**Comment by Mr-Persona** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by l941230** [comment]
can you re open this issue. I am seeing the same crash on RN 0.72.5

**Comment by Mr-Persona** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。
