### ISSUE TITLE
Execution failed for task ':app:bundleReleaseJsAndAssets'.

### ISSUE THREAD

**Issue by AhmadAl-Ghalban** [facebook/react-native#36303]
### Description

when create version aab to upload to google play Don't make the apk And return this error 
* What went wrong:
Execution failed for task ':app:bundleReleaseJsAndAssets'.
> Process 'command 'cmd'' finished with non-zero exit value 1

### React Native Version

0.67.1

### Output of `npx react-native info`

System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
    Memory: 4.40 GB / 15.73 GB
  Binaries:
    Node: 14.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: AI-221.6008.13.2211.9514443
    Visual Studio: Not Found
  Languages:
    Java: 11.0.17 - C:\Program Files\Common Files\Oracle\Java\javapath\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.67.1 => 0.67.1
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

cd Android
./gradlew bundleRelease
can show issue

### Snack, code example, screenshot, or link to a repository

![Errr](https://user-images.githubusercontent.com/70822571/221510177-1861f20f-56df-482c-83df-3be32b691688.PNG)

**Comment by cortinico** [comment]
As the bot said, you're on a unsupported version + we would need the full debug log.

**Comment by AhmadAl-Ghalban** [comment]
> As the bot said, you're on a unsupported version + we would need the full debug log.

upgrade react native version ??

**Comment by cortinico** [comment]
Correct, we offer support only for RN 0.69+:
https://github.com/reactwg/react-native-releases/

**Comment by cortinico** [comment]
Closing as per my previous comments
