### ISSUE TITLE
[Android] Failed to build Release Version

### ISSUE THREAD

**Issue by vanillatte09** [facebook/react-native#36324]
### New Version

0.69.8

### Old Version

0.66.5

### Build Target(s)

12.4

### Output of `react-native info`

System:
    OS: macOS 12.2
    CPU: (8) arm64 Apple M1 Pro
    Memory: 162.73 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.11.1 - ~/.nvm/versions/node/v16.11.1/bin/node
    Yarn: Not Found
    npm: 8.0.0 - ~/.nvm/versions/node/v16.11.1/bin/npm
    Watchman: 2022.06.27.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.8 => 0.69.8 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Issue and Reproduction Steps

Hi, I'm trying to upgrade to RN 0.69.8 from 0.66.5 and getting failed to build the Release version of Android, while Debug Version is working fine.

```
Execution failed for task ':app:bundleStagingReleaseJsAndAssets'.
> Process 'command '../../node_modules/react-native/sdks/hermesc/osx-bin/hermesc'' finished with non-zero exit value 2

```
Have read and followed the related issue but seems nothing is working.

Here is my Gradle:
```
project.ext.react = [
    enableHermes: true,
    hermesCommand: '../../node_modules/react-native/sdks/hermesc/%OS-BIN%/hermesc',
 ]
 
if (enableHermes) {
    implementation("com.facebook.react:hermes-engine:+") {
       exclude group:'com.facebook.fbjni'
    } 
} else {
    implementation jscFlavor
}
``` 

Changed package.json

```
    "patch-package": "^6.5.1",
    "react": "17.0.2" => "18.0.0",
    "react-native": "0.66.5" => "0.69.8",
    "react-test-renderer": "17.0.2" => "18.0.0",
```
 
Try to build a release build with

`npm run android:prebuild && cd android && ./gradlew assembleStagingRelease`

Error Screenshot:
![Screen Shot 2023-02-28 at 20 46 24](https://user-images.githubusercontent.com/15572748/221873197-9248a8b1-57e4-4fe6-91f6-099952ae3938.png)

Upgrade Command: `npx react-native upgrade 0.69.8`
Reference for Upgrade: https://react-native-community.github.io/upgrade-helper/?from=0.66.5&to=0.69.8

Anything that I've missed or my step is wrong? Please help for advice, thank you.

**Comment by cortinico** [comment]
Can you share the full build log?

**Comment by vanillatte09** [comment]
Hi @cortinico 
i've scanned the error on this link https://scans.gradle.com/s/2sdpo2vmdewf6/console-log?task=:app:bundleStagingReleaseJsAndAssets

It is informative enough or needs something else?

**Comment by vanillatte09** [comment]
Build is successful but when trying to configure project gets failed

```
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 10s
41 actionable tasks: 35 executed, 6 up-to-date
> Configure project :
https://repo.maven.apache.org/maven2/
file:/Users/.m2/repository/
file:/Users/Documents/development/frontend/react-native/node_modules/react-native/android/
```

**Comment by vanillatte09** [comment]
Solved. 
Main Issue:  `Quantifier has nothing to repeat`
Solution installing https://babeljs.io/docs/babel-plugin-transform-named-capturing-groups-regex
