### ISSUE TITLE
[iOS] How to disable to long press & move it to other TextInput?

### ISSUE THREAD

**Issue by fullstack17** [facebook/react-native#36326]
### Description

I would like to copy & paste the password fields from TextInput to other TextInput.
I set as `contextMenuHidden` as `true` to hide the context menu, as a result, context menu no longer is displayed. 
But I still can select the value and move it to other TextInput.

### React Native Version

0.70.5

### Output of `npx react-native info`

System:
    OS: macOS 13.0.1
    CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
    Memory: 138.89 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/fairy/.rvm/gems/ruby-2.7.4/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.5 => 0.70.5 
    react-native-macos: Not Found

### Steps to reproduce

Assuming there are multi TextInput fields on one screen:
- Input the values on the first TextInput
- Select the value from first one.
- Holding long-press the selected string, then you are able to move it to other TextInput
- Move it to other TextInput
- Selected value is copied into other TextInput

### Snack, code example, screenshot, or link to a repository

Please check the attached video.
https://user-images.githubusercontent.com/44271282/221897215-7add662c-b5b3-4a80-be57-5fbb51698640.mov

**Comment by carlosalmonte04** [comment]
Hello. What you are describing can already be done on iOS by default and there is no way to alter this behavior from the react native side unfortunately.

I tried creating this but later found out that this is already implemented natively, on both android and ios actually.

There is some minimal customization that can be done on the native side of iOS, however this needs to be connected to react native yet. One way would be TextInput to have a connection to drag and drop customization from iOS.

https://reactnative.dev/docs/textinput
https://developer.apple.com/documentation/uikit/views_and_controls/drag_and_drop_customization

Thanks for submitting this issue, it was entertaining to figure this one out. Please let me know if you have further questions/comments. And sorry it's not the answer you were hoping to read.

**Comment by fullstack17** [comment]
Hmm.. still no updates. seems like React-Native is maintained or no longer alive?
