### ISSUE TITLE
Text Component ellipsis is not displayed correctly in Android (sometimes the three dots are cut-off)

### ISSUE THREAD

**Issue by alexxxwork** [facebook/react-native#36336]
### Description

This is a duplicate report of this old bug https://github.com/facebook/react-native/issues/33487 on a supported version of RN

When I set numberOfLines={1} on a Text component, if the parent's component width is fixed, sometimes the ellipsis is cut-off strangely. For example, in the below screenshot, you can see that only 1 and a half dots of the ellipsis are shown.

It seems to only happen on Android and on most devices that I've tried.

<img src=https://user-images.githubusercontent.com/43996225/221724143-0a4622c3-fcd5-4d34-b65c-1aab417644b8.jpg />

### React Native Version

0.70.4

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Memory: 26.04 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: Not Found
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
    Watchman: 2023.02.13.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9514443
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 14.0.2 - /usr/bin/javac
  npmPackages:
    @expensify/react-native:  0.70.4-alpha.2 
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Here is the minimal reproducible code. [Link to snack](https://snack.expo.dev/@ismart-expo/android-ellipsis-issue).

### Snack, code example, screenshot, or link to a repository

```
import React from 'react'
import { View, Text } from 'react-native'

export default () =>
  <View style={{alignItems: 'center', justifyContent: 'center', height: '100%'}}>
    <View style={{width: 173, padding: 24, backgroundColor: 'yellow'}}>
      <Text style={{fontSize: 30}} numberOfLines={1}>This text will be cut-off strangely in Android</Text>
    </View>
  </View>
```

**Comment by bernhardoj** [comment]
@alexxxwork I think it's better to create a new project with the minimum reproducible code on the latest RN version.

**Comment by cortinico** [comment]
> 0.70.4-alpha.2

This is not a valid RN version + I second what @bernhardoj mentioned:

> @alexxxwork I think it's better to create a new project with the minimum reproducible code on the latest RN version.

**Comment by alexxxwork** [comment]
> > 0.70.4-alpha.2
> 
> This is not a valid RN version + I second what @bernhardoj mentioned:
> 
> > @alexxxwork I think it's better to create a new project with the minimum reproducible code on the latest RN version.

That's a fork from 0.70.4 RN version
https://github.com/Expensify/react-native/compare/Expensify-0.70.4-alpha.2...facebook:react-native:v0.70.4

Ok I'll test on latest RN version

**Comment by cortinico** [comment]
> That's a fork from 0.70.4 RN version

Then please open a issue on their fork and get back to use if it ends up being a React Native core issue.
