### ISSUE TITLE
[Animated] Make __getValue() public

### ISSUE THREAD

**Issue by cosmith** [facebook/react-native#3633]
I'm trying to change a prop based on a the value of an `Animated.Value`. Is there currently a better way to do this than getting the actual value with `__getValue()`? I'd rather not call private methods if I can avoid it.

```js
<Animated.View 
    style={[styles.dim, {opacity: this.state.opacity}]}
    pointerEvents={this.state.opacity.__getValue() === 0 ? "none" : undefined}
>
    <TouchableOpacity onPress={this.props.onPressOutside} style={{flex: 1}}/>
</Animated.View>
```

As far as I can see simply adding a public `getValue()` / renaming `__getValue()` would be enough but maybe there's a good reason for it to be private. I'd be happy to submit a PR if you think it's a good idea.

**Comment by chirag04** [comment]
I get there is ``this.state.opacity._value`` property for animated values. I'm not sure.

**Comment by cosmith** [comment]
Yes but it's still a private member... from the source:
```js
  __getValue(): number {
    return this._value + this._offset;
  }
```

I haven't really studied the source so I'm not sure what this offset is, but that's why I'd feel safer using a public method.

**Comment by chirag04** [comment]
Oh Ok. I think @sahrens or @vjeux  can help here.

**Comment by willatthewindow** [comment]
I think this is the relevant passage from the docs: https://facebook.github.io/react-native/docs/animations.html#responding-to-the-current-animation-value
It's a little bit hand-wavy in the explanation but presumably just because of the complexity involved.

If you go down the addListener() route be aware that it will be fired a lot, there's a good chance you'll want to throttle it requestAnimationFrame().

**Comment by ide** [comment]
@sahrens, @vjeux what do you think about adding s convenience API that adds an animated value listener, caches the latest value whenever there's an event, and makes it synchronously available via a method like getRecentValue()? (Need to think more about the naming, getPreviousValue or getLastValue may be more accurate.)

**Comment by sahrens** [comment]
A convenience method like that could be ok - would it really be that
helpful.

**Comment by cosmith** [comment]
@willatthewindow thanks for the link, my fault for not reading the docs thoroughly. I realized I could do what I wanted without using `__getValue` so it's not top priority.
