### ISSUE TITLE
Undefined symbols for architecture arm64 - React Native - Archive Failed - AppCenter - iOS

### ISSUE THREAD

**Issue by AndresHMosqueda** [facebook/react-native#36339]
### Description

I'm upgrading a react native app from 0.68.1 to the latest at the moment "0.71.3".
I'm able to build and run the app in my local machine but in Appcenter I'm seeing the following error:

`Undefined symbols for architecture arm64:
  "_RCTLogSetBridgeCallableJSModules", referenced from:
      **-[RCTCxxBridge initWithParentBridge:] in libReact-Core.a(RCTCxxBridge.o)**
  "_RCTLogSetBridgeModuleRegistry", referenced from:
      **-[RCTCxxBridge initWithParentBridge:] in libReact-Core.a(RCTCxxBridge.o)**
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** ARCHIVE FAILED **`

### React Native Version

0.71.3

### Output of `npx react-native info`
System:
    OS: macOS 12.6.3
    CPU: (3) x64 Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz
    Memory: 449.95 MB / 14.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.21.3 - ~/.nvm/versions/node/v14.21.3/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 6.14.18 - ~/.nvm/versions/node/v14.21.3/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/lib/ruby/gems/3.0.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 27, 28, 29, 30, 31, 32, 33, 33
      Build Tools: 27.0.0, 27.0.1, 27.0.2, 27.0.3, 28.0.0, 28.0.1, 28.0.2, 28.0.3, 29.0.0, 29.0.1, 29.0.2, 29.0.3, 30.0.0, 30.0.1, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 33.0.0, 33.0.1, 33.0.2
      Android NDK: 25.2.9519653
  IDEs:
    Android Studio: Not Found
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_362 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.3 => 0.71.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Archive failure in AppCenter

### Code example

My Podfile looks like:
[Link](https://stackoverflow.com/questions/75576315/undefined-symbols-for-architecture-arm64-react-native-appcenter)

Build parameters in Appcenter -> Xcode version 14.2,
Node.js version 14.x

**Comment by AndresHMosqueda** [comment]
@cortinico my bad, I meant to say "0.71.3". I have updated the first comment.

**Comment by rusteyy** [comment]
Hi guys, was there a solution here?
@AndresHMosqueda
