### ISSUE TITLE
Document Object.assign perf non-spec optimisation

### ISSUE THREAD

**Issue by RyGuyM** [facebook/react-native#3634]
When sending a file through FormData Object.assign throws an error:

```
TypeError: One of the sources to assign has an enumerable key on the prototype chain. This is an edge case that we do not support. This error is a performance optimization and not spec compliant.
```

This error come from the Object.assign polyfill. Is this the expected outcome? If so I will just overwrite the polyfill for this use case.

**Comment by seanlau555** [comment]
I also got the same problem. Could anyone answer that?

**Comment by satya164** [comment]
Can you share a code sample?

**Comment by AwesomeJerry** [comment]
I think any prototype extending causes this problem. I was polyfill my App by using something like:
```
Array.prototype.find = function () {};
```
and the error was caught.

**Comment by anback** [comment]
AwesomeJerry, thx, your comment solved my issue, something should scream when people does this, lets create a PR for it.

**Comment by christopherdro** [comment]
@anback Any chance on putting that PR together?

**Comment by grabbou** [comment]
I have updated the title and added `Documentation` label so hopefully it gets more attention :)

**Comment by sharnik** [comment]
@christopherdro @grabbou I can put it together, just confirm that I got the idea right:

What we want to achieve here is to give the developer a better error message. Something along the lines of: "We don't allow assigning to prototype properties. This error is a performance optimization and not spec compliant."

**Comment by ide** [comment]
In the PR could you also add a comment in the Object.assign polyfill saying that it's there only for iOS 8? If/when we upgrade the version of JSC on Android, which is similar to iOS 8's right now, we can probably make the polyfill be spec-compliant since it will only make iOS 8 devices slow but that's fine -- only 8% or fewer of active iOS devices use iOS 8: https://developer.apple.com/support/app-store/

**Comment by sharnik** [comment]
Okay, the PR is here. Let me know if that's enough to close this issue and I'll look for a real problem to solve :)

**Comment by sharnik** [comment]
We can close this issue, it's been solved in https://github.com/facebook/react-native/pull/10472
