### ISSUE TITLE
AppDelegate.mm:12:8: error: property 'initialProps' not found on object of type 'AppDelegate *'   self.initialProps = @{};

### ISSUE THREAD

**Issue by matrix3d** [facebook/react-native#36351]
### Description

AppDelegate.mm:12:8: error: property 'initialProps' not found on object of type 'AppDelegate *'
  self.initialProps = @{};

### React Native Version

0.71.0

### Output of `npx react-native info`

AppDelegate.mm:12:8: error: property 'initialProps' not found on object of type 'AppDelegate *'
  self.initialProps = @{};

### Steps to reproduce

AppDelegate.mm:12:8: error: property 'initialProps' not found on object of type 'AppDelegate *'
  self.initialProps = @{};

### Snack, code example, screenshot, or link to a repository

AppDelegate.mm:12:8: error: property 'initialProps' not found on object of type 'AppDelegate *'
  self.initialProps = @{};

**Comment by cipolleschi** [comment]
Hi @matrix3d we introduced the `initialProps` property in RN 0.71 ([this commit](https://github.com/facebook/react-native/commit/89be5ab02382a9313242e0f606be1e861e21c9a7)) to address the possibility to customize some of them.

Just upgrade to the latest patch version and it will work.

**Comment by zakharchenkoAndrii** [comment]
Hi @cipolleschi , but according to the description he is using 0.71 already. I am currently upgrading to Expo 48 (which is using react-native 0.71.3) and I have the same problem that Xcode cannot find methods from `<RCTAppDelegate.h>` 

<img width="762" alt="image" src="https://user-images.githubusercontent.com/23197387/222680728-481fca4c-6f93-4b2b-8f2f-aa9e7e2f176d.png">

any help or advice would be highly appreciated :)

P.S. I reinstalled node_modules, cleared and reinstalled Pods, and Cleaned Xcode Project. Thanks in advance

**Comment by cipolleschi** [comment]
@zakharchenkoAndrii no, they are 2 different versions.

From the description, @matrix3d is using 0.71.**0**, which has no `initialProps` property as we released it in 0.71.**1** (note the different patch version). For completeness, the most recent version is **0.71.3**.

---

You have a different problem. Your `AppDelegate.h` is not extending the right class.

If you open the header `AppDelegate.h`, your base class is probably something like:

```objc
@interface AppDelegate : UIResponder <UIApplicationDelegate>
```
For a vanilla React Native project, that should instead be
```objc
@interface AppDelegate : RCTAppDelegate
```
However, you are using an Expo project and they support the `RCTAppDelegate`, it should probably worth it to open an issue in their repository, if you are actually using a base class provided by Expo.

**Comment by zakharchenkoAndrii** [comment]
Thanks, this [thread](https://github.com/expo/expo/issues/20850) helped me to resolve the issue

**Comment by ahsan-abrar** [comment]
Upgrading 0.71.0 to 0.71.1 resolved the issue for me.
