### ISSUE TITLE
Duplicate classes error for ReactNativeFlipper with react-native 0.71.3 Upgrade

### ISSUE THREAD

**Issue by ursnj** [facebook/react-native#36362]
### New Version

0.71.3

### Old Version

0.69.6

### Build Target(s)

Android Device

### Output of `react-native info`

warn Package rn-fetch-blob contains invalid configuration: "dependency.hooks" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
info Fetching system and libraries information...
System:
    OS: macOS 12.6.1
    CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
    Memory: 26.34 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.19.3 - /usr/local/bin/npm
    Watchman: 2022.07.04.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK: Not Found
    Android SDK:
      API Levels: 28, 29, 30, 31, 32, 33
      Build Tools: 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0, 33.0.0
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8309675
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.3 => 0.71.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Issue and Reproduction Steps

Note: Recompile with -Xlint:unchecked for details.
/Users/nj/Desktop/projects/worklage/conectr/app/android/app/src/debug/java/njsolutions/worklage/ReactNativeFlipper.java:30: error: duplicate class: njsolutions.worklage.ReactNativeFlipper
public class ReactNativeFlipper {
       ^
Note: /Users/nj/Desktop/projects/worklage/conectr/app/android/app/src/main/java/njsolutions/worklage/MainApplication.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 4m 6s

    at makeError (/Users/nj/Desktop/projects/worklage/conectr/app/node_modules/execa/index.js:174:9)
    at /Users/nj/Desktop/projects/worklage/conectr/app/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (/Users/nj/Desktop/projects/worklage/conectr/app/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:82:7)

**Comment by cortinico** [comment]
> /Users/nj/Desktop/projects/worklage/conectr/app/android/app/src/debug/java/njsolutions/worklage/ReactNativeFlipper.java:30: error: duplicate class: njsolutions.worklage.ReactNativeFlipper
> public class ReactNativeFlipper {

It seems like you have a duplicate `ReactNativeFlipper`. Can you share your file structure (how many `ReactNativeFlipper` you have and where are they located/what's their content?).

Also this is essentially a duplicate of:
#36179
#36154
#36327
so please refer to the workarounds there and get back to us 👍

**Comment by ursnj** [comment]
@cortinico Thanks for the Quick reply, i tried above mentioned work arrounds but no luck, the issue is not with other libraries, its with there are 2 React native flipper classes one in debug and another one in main folder, if i remove release Flipper class its working fine, but building apk is failing.

**Comment by vlad-ps** [comment]
I have the same issue and am getting the same error. If I comment out the code in ReactNativeFlipper.java file that's in android/app/src/main/java/com folder, the app builds locally in Debug, but fails on the CI/CD pipeline that's making a release build. So far, I've been commenting out the contents of ReactNativeFlipper file for local builds, and putting them back on when it's time to push out a build. That's not ideal. I'm on RN 0.71.3.

**Comment by emilstepanian** [comment]
Hi @cortinico,  
I just upgraded, and I have the same error. 

This is my file structure:
<img width="317" alt="Skærmbillede 2023-03-04 kl  19 24 01" src="https://user-images.githubusercontent.com/16006899/222922572-1f171717-6e6c-4f91-9f07-36b2c9fec96e.png">

Content of android/app/src/main/java/com/workbreak/ReactNativeFlipper.java
```
/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * <p>This source code is licensed under the MIT license found in the LICENSE file in the root
 * directory of this source tree.
 */
package com.emilstepanian.workbreak;
import android.content.Context;
import com.facebook.react.ReactInstanceManager;

/**
 * Class responsible of loading Flipper inside your React Native application. This is the release
 * flavor of it so it's empty as we don't want to load Flipper.
 */
public class ReactNativeFlipper {
  public static void initializeFlipper(Context context, ReactInstanceManager reactInstanceManager) {
    // Do nothing as we don't want to initialize Flipper on Release.
  }
}

```

Content of android/app/src/debug/java/com/workbreak/ReactNativeFlipper.java
```
/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * <p>This source code is licensed under the MIT license found in the LICENSE file in the root
 * directory of this source tree.
 */
package com.emilstepanian.workbreak;

import android.content.Context;
import com.facebook.flipper.android.AndroidFlipperClient;
import com.facebook.flipper.android.utils.FlipperUtils;
import com.facebook.flipper.core.FlipperClient;
import com.facebook.flipper.plugins.crashreporter.CrashReporterPlugin;
import com.facebook.flipper.plugins.databases.DatabasesFlipperPlugin;
import com.facebook.flipper.plugins.fresco.FrescoFlipperPlugin;
import com.facebook.flipper.plugins.inspector.DescriptorMapping;
import com.facebook.flipper.plugins.inspector.InspectorFlipperPlugin;
import com.facebook.flipper.plugins.network.FlipperOkhttpInterceptor;
import com.facebook.flipper.plugins.network.NetworkFlipperPlugin;
import com.facebook.flipper.plugins.sharedpreferences.SharedPreferencesFlipperPlugin;
import com.facebook.react.ReactInstanceEventListener;
import com.facebook.react.ReactInstanceManager;
import com.facebook.react.bridge.ReactContext;
import com.facebook.react.modules.network.NetworkingModule;
import okhttp3.OkHttpClient;

/**
 * Class responsible of loading Flipper inside your React Native application. This is the debug
 * flavor of it. Here you can add your own plugins and customize the Flipper setup.
 */

public class ReactNativeFlipper {
  public static void initializeFlipper(Context context, ReactInstanceManager reactInstanceManager) {
    if (FlipperUtils.shouldEnableFlipper(context)) {
      final FlipperClient client = AndroidFlipperClient.getInstance(context);

      client.addPlugin(new InspectorFlipperPlugin(context, DescriptorMapping.withDefaults()));
      client.addPlugin(new DatabasesFlipperPlugin(context));
      client.addPlugin(new SharedPreferencesFlipperPlugin(context));
      client.addPlugin(CrashReporterPlugin.getInstance());

      NetworkFlipperPlugin networkFlipperPlugin = new NetworkFlipperPlugin();
      NetworkingModule.setCustomClientBuilder(
          new NetworkingModule.CustomClientBuilder() {
            @Override
            public void apply(OkHttpClient.Builder builder) {
              builder.addNetworkInterceptor(new FlipperOkhttpInterceptor(networkFlipperPlugin));
            }
          });
      client.addPlugin(networkFlipperPlugin);
      client.start();

      // Fresco Plugin needs to ensure that ImagePipelineFactory is initialized
      // Hence we run if after all native modules have been initialized
      ReactContext reactContext = reactInstanceManager.getCurrentReactContext();
      if (reactContext == null) {
        reactInstanceManager.addReactInstanceEventListener(
            new ReactInstanceEventListener() {
              @Override
              public void onReactContextInitialized(ReactContext reactContext) {
                reactInstanceManager.removeReactInstanceEventListener(this);
                reactContext.runOnNativeModulesQueueThread(
                    new Runnable() {
                      @Override
                      public void run() {
                        client.addPlugin(new FrescoFlipperPlugin());
                      }
                    });
              }
            });
      } else {
        client.addPlugin(new FrescoFlipperPlugin());
      }
    }
  }
}

```

**Comment by emilstepanian** [comment]
I read this: [https://stackoverflow.com/questions/56240965/android-two-buildtypes-error-duplicate-class](url)

I realized I assumed that my 'main' folder was the same as 'release' folder, which is non-existent in my project.

I created the 'release' folder and subpath and moved the new ReactNativeFlipper file to this location, and the issue was fixed immediately

**Comment by efstathiosntonas** [comment]
@emilstepanian can you share your folder structure on a screenshot?

**Comment by CazumaNC** [comment]
> I read this: [https://stackoverflow.com/questions/56240965/android-two-buildtypes-error-duplicate-class](url)

Thank you! That worked for me.

But the link at your comment is hyperlinked to a different URL (something on github).

**Comment by cortinico** [comment]
@emilstepanian your issue is probably related to you using 5 flavors: main, Development, debug, Production, Staging.

@vlad-ps you said:
> file that's in android/app/src/main/java/com folder

The problem is that you should **not** have a `ReactNativeFlipper` file in the **main** source set at all.

Please refer to the official template:
https://github.com/facebook/react-native/tree/main/template/android

You should have only two ReactNativeFlipper in the following locations:

```
android/app/src/debug/java/com/helloworld/ReactNativeFlipper.java
android/app/src/release/java/com/helloworld/ReactNativeFlipper.java
```

Also please make sure the content is correct as provided by the template.
@vlad-ps you should NOT be needing to comment out code to build either debug or release.

**Comment by ursnj** [comment]
Thanks guys for the Quick responses, Issues came because i have created ReactNativeFlipper class inside main folder instead of release, moving that back to release folder solved issue,

**Comment by RadekKosiada** [comment]
> 

@cortinico  thanks for the explanation. Could you provide a new link to the official template, as the one in your response gives 404?

**Comment by cortinico** [comment]
yup @RadekKosiada I've updated the link: https://github.com/facebook/react-native/tree/main/packages/react-native/template/android

**Comment by elgambet** [comment]
> I read this: [https://stackoverflow.com/questions/56240965/android-two-buildtypes-error-duplicate-class](url)
> 
> I realized I assumed that my 'main' folder was the same as 'release' folder, which is non-existent in my project.
> 
> I created the 'release' folder and subpath and moved the new ReactNativeFlipper file to this location, and the issue was fixed immediately

This fixes it. My problem was that I was following the [react-native upgrade instructions](https://react-native-community.github.io/upgrade-helper/?from=0.70.6&to=0.71.10) blindly, and in those instructions, the production Flipper file was located in the main folder.
