### ISSUE TITLE
How to use registerForActivityResult with TurboModules in react native's new architecture?

### ISSUE THREAD

**Issue by BraveEvidence** [facebook/react-native#36377]
### Description

Firstly I am not talking about the old architecture and I have already gone through [this](https://github.com/facebook/react-native/issues/33639)

This method does not really works for new architecture given how the files are structured

registerForActivityResult can only be used in MainActivity. I need registerForActivityResult for my intent to pick images.

[Here](https://github.com/BraveEvidence/ReactNativeNewArchregisterForActivityResultTry) is the complete code sample

The issue is I can't call my MainActivity in my Module as the Module file is not part of the main android folder but a separate folder called RTNImagePicker in my case

I get below error if I try to refer MainActivity in my module

<img width="742" alt="hEmqe" src="https://user-images.githubusercontent.com/24708929/222967438-f6f07b84-60a3-42e1-9243-0682c0b88580.png">
<img width="894" alt="zYrD9" src="https://user-images.githubusercontent.com/24708929/222967450-b8ed0a81-0562-4214-80dc-20104ccebe24.png">

I cannot add it as dependency on module as well as it results in circular dependency

<img width="527" alt="DFFg1" src="https://user-images.githubusercontent.com/24708929/222967464-7c5cb8ac-9d41-421d-ba0a-bced94da2bba.png">

### React Native Version

0.71.0

### Output of `npx react-native info`

error Unrecognized command "info".
info Run "react-native --help" to see a list of all available commands.

### Steps to reproduce

You can download the sample from [here](https://github.com/BraveEvidence/ReactNativeNewArchregisterForActivityResultTry) and try it out

### Snack, code example, screenshot, or link to a repository

https://github.com/BraveEvidence/ReactNativeNewArchregisterForActivityResultTry

**Comment by BraveEvidence** [comment]
I already upgraded to 0.71.3 and still face the issue

**Comment by cortinico** [comment]
Answering here as I haven't got the time to get back to it.

As per Android documentation, `registerForActivityResult` can be called only during the Activity/Fragment creation. So this will have to happen inside the MainActivity (you'll have to instruct your users to do an invocation of a class of your library like this:

```kotlin
class MainActivity : ReactActivity() {
  
+ override fun onCreate(savedInstanceState: Bundle?) {
+   super.onCreate(savedInstanceState)
+   // Initialize my library here.
+   MyLibrary.intialize(this)
+ }
```

You can then call `registerForActivityResult` inside your library code, and retain the `ActivityResultLauncher` that gets returned, and invoke it inside your module whenever needed.

**Comment by cortinico** [comment]
Also this is unchanged between old and new architecture

**Comment by matinzd** [comment]
Let's see if this lands:

https://github.com/react/react-native/pull/57798
