### ISSUE TITLE
[react-native-gradle-plugin] Incompatibility with monorepos

### ISSUE THREAD

**Issue by hyoretsu** [facebook/react-native#36378]
### Description

When trying to build my app, I get this error.
```
A problem occurred configuring project ':app'.
> Failed to notify project evaluation listener.
   > /home/hyoretsu/@Projects/ton/mobile/node_modules/react-native/ReactAndroid/gradle.properties (No such file or directory)
```

That happens because PNPM installed `react-native` to the "global" `node_modules`, not the project's. (it should be `/home/hyoretsu/@Projects/ton/node_modules/react-native/ReactAndroid/gradle.properties`)

### React Native Version

0.71.3

### Output of `npx react-native info`

System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 4.30 GB / 11.55 GB
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.15 - ~/.nvm/versions/node/v16.16.0/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 28, 29, 30, 31, 33
      Build Tools: 28.0.3, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 33.0.0, 33.0.1
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 11.0.18 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Just run `npm run android`

### Snack, code example, screenshot, or link to a repository

https://github.com/hyoretsu/ton

**Comment by cortinico** [comment]
Have you configured your `reactNativeDir` property as suggested in the template (file `android/app/build.gradle`) and in the documentation: https://reactnative.dev/docs/react-native-gradle-plugin#reactnativedir
?

**Comment by hyoretsu** [comment]
That's what's I was missing, tyvm.

**Comment by elton11220** [comment]
> Have you configured your `reactNativeDir` property as suggested in the template (file `android/app/build.gradle`) and in the documentation: https://reactnative.dev/docs/react-native-gradle-plugin#reactnativedir ?

Excellent!
