### ISSUE TITLE
Cannot find type 'RCTAppDelegate' in scope

### ISSUE THREAD

**Issue by tapz** [facebook/react-native#36383]
### Description

When trying to build I get this error:

Cannot find type 'RCTAppDelegate' in scope

<img width="1040" alt="Screenshot 2023-03-06 at 12 56 08" src="https://user-images.githubusercontent.com/11726387/223091308-a3a86dda-aa29-460b-adbd-84425c0aaf4a.png">

Used to work just fine before switching from Intel to M2 MacBook Pro. I have moved all dependencies from pod file to Swift packager. But as React Native still uses legacy objective-c and is not modern full Swift, the CocoaPod makes life a hell.

### React Native Version

0.71.3

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 13.2.1
    CPU: (12) arm64 Apple M2 Max
    Memory: 9.31 GB / 96.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.14.2 - ~/.nvm/versions/node/v18.14.2/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.14.2/bin/yarn
    npm: 9.6.0 - ~/.nvm/versions/node/v18.14.2/bin/npm
    Watchman: 2023.02.27.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 27, 28, 29, 30, 31, 33
      Build Tools: 33.0.0
      Android NDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9619390
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 19.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Try to build and start in a real device in Xcode.

### Snack, code example, screenshot, or link to a repository

x

**Comment by cipolleschi** [comment]
Hi @tapz!

What do you mean with:

> Used to work just fine before switching from Intel to M2 MacBook Pro.

Were you able to use the current setup with Swift?

I'm not sure that that was the case as `RCTAppDelegate` does not support Swift yet. It does not defines a module so it's unlikely that it was working.

I think that your problem resides in:

>  I have moved all dependencies from pod file to Swift packager

As we can't support SPM yet. One of the limitation of SPM is that the code in each package must be from a single language (e.g.: only Swift) and so far we have modules with multiple languages. So we can't really move to that, although I'd love to.

---

To make RCTAppDelegate work with Swift, we have to update the `React-RCTAppDelegate.podspec` to:
- set the build configuration `DEFINES_MODULE` to true
- define a `module_name`
- pass some compilation flags to make it work with the New Architecture.

We also accepts contributions! :D

**Comment by tapz** [comment]
@cipolleschi So, what you are saying is that the most recent RN version does not support Swift?

**Comment by cipolleschi** [comment]
@tapz disclaimer that I joined the React Native team from slightly less than 1 year, so I don't have full context on all the historical reasons why end up in this situation.

My understanding is that React Native never officially declared Swift support. It was a happy accident bound to the usage of ObjectiveC. Recently, to get better performances and a shared implementation between our platforms, we are moving more and more toward a C++ shared core, and, unfortunately, there is no direct interoperability between Swift and C++. This makes it harder to fully offer Swift support.

You **can** use Swift with React Native, but with limitations. 
For example, right now, you **can't** replace the AppDelegate (as you are trying to do) with a Swift implementation as you'll incur in the errors you are facing. You **can** have other objects written in Swift and you **can** use them in your AppDelegate.

**Is this ideal? Of course not.** We are working to simplify as much as we can the upgrade experience and we are working toward offering the support for Swift as a first-class language.

The `RCTAppDelegate` is a first step in that direction. Before we introduced it, it was impossible to adopt Swift as the previous `AppDelegate` ([this](https://github.com/facebook/react-native/blob/0.70-stable/template/ios/HelloWorld/AppDelegate.mm#L25) from 0.70, for example) used to have bits written in C++ that would have made it fail the compilation step.

We are committed to make it easier and easier to adopt Swift, but we are not there yet.

I hope this help in sharing some context and shed some light on the technical reasons why Swift is not supported yet.

---

For your specific problem there are a couple of solutions:
1. I can create a PR that will solve the problem at hand, but you'll have to wait for a Release which includes it
2. You can create an XCConfig for React-RCTAppDelegate, fixing the settings I described above and replace the one generated by Cocoapods
3. You can move back to an Objective-C++ implementation of the AppDelegate. I don't know how many things your AppDelegate is doing, but most of them could be delegated to other Swift objects and used in the ObjectiveC AppDelegate, eventually.
4. You can avoid adopting the RCTAppDelegate (as it is optional) and reimplement yourself all the bits and pieces required to setup React Native properly

Let me know if I can help you in any way!

**Comment by tapz** [comment]
@cipolleschi Thanks for the clarification! The alternative 4 was the easies way for me.
