### ISSUE TITLE
Execution failed for task ':app:bundleDebugJsAndAssets'. > Process 'command 'node'' finished with non-zero exit value 1

### ISSUE THREAD

**Issue by dzwangfan** [facebook/react-native#36399]
### Description

Execution failed for task ':app:bundleDebugJsAndAssets'. > Process 'command 'node'' finished with non-zero exit value 1

### React Native Version

0.64.4

### Output of `npx react-native info`

![22222](https://user-images.githubusercontent.com/28337668/223673913-6c01eead-1238-47bf-8d33-f45acb767e97.png)
![111111](https://user-images.githubusercontent.com/28337668/223673932-f4a139b4-4aae-4c2e-81bd-7204ae29dcba.png)

### Steps to reproduce

Execution failed for task ':app:bundleDebugJsAndAssets'. > Process 'command 'node'' finished with non-zero exit value 1

### Snack, code example, screenshot, or link to a repository

![22222](https://user-images.githubusercontent.com/28337668/223674155-0cfe5326-6a89-48fe-9ec2-d6c8a4706dee.png)

**Comment by cortinico** [comment]
You're on a old version of React Native that we don't support at this stage. Please consider updating to the latest version.
