### ISSUE TITLE
The app references non-public selectors: getAuthorizationStatus:, setHighlightsToday:

### ISSUE THREAD

**Issue by tapz** [facebook/react-native#36392]
### Description

I get this warning when uploading a build to App Store Connect (for TestFlight). This probably would cause the app to be rejected in the Apple review.

`The app references non-public selectors in Payload/MyApp.app/MyApp: getAuthorizationStatus:, setHighlightsToday:`

### React Native Version

0.71.3

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 13.2.1
    CPU: (12) arm64 Apple M2 Max
    Memory: 37.74 GB / 96.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.14.2 - ~/.nvm/versions/node/v18.14.2/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.14.2/bin/yarn
    npm: 9.6.0 - ~/.nvm/versions/node/v18.14.2/bin/npm
    Watchman: 2023.02.27.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 27, 28, 29, 30, 31, 33
      Build Tools: 33.0.0
      Android NDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9619390
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 19.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.3 => 0.71.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Archive a release version in Xcode and upload to App Store Connect.

### Snack, code example, screenshot, or link to a repository

getAuthorizationStatus is not in my code, but in RN codegen.

Minimum deployment: iOS 13.0

**Comment by joaopauloppeixoto** [comment]
Hi @tapz,

I had had kind of the same issue, but I founded [this](https://developer.apple.com/forums/thread/714996) on the apple's forum and changing the "Minimum Deployments" version to the lowest worked for me.

**Comment by tapz** [comment]
@joaopauloppeixoto I can't set the minimum deployment lower because the app uses apis not available in the lower versions. And that is just a workaround, not a fix.
