### ISSUE TITLE
Styles with percentage values

### ISSUE THREAD

**Issue by fnky** [facebook/react-native#364]
When using a property with the type of `number`, it's not possible to use percentage-based values.

```js
var styles = StyleSheet.create({
  myStyle: {
    position: 'absolute',
    width: '100%' // throws an error
  }
});
```

It would be nice to support this, so you don't have to calculate the value to `px` yourself. Using a `string` would also allow other units to be used — If using `number` type, it would still be `px`-based value.

This would also make it easy to make things responsive.

**Comment by joshaber** [comment]
`flex` can be used for this. For example:

```js
// In render:
return (
  <View>
    // The width will be split evenly between the two views.
    <View style={{flex: 1}}/>
    <View style={{flex: 1}}/>
  </View>
)

// Or:
return (
  <View>
    // The second view will be double the width of the first.
    <View style={{flex: 0.5}}/>
    <View style={{flex: 1}}/>
  </View>
)
```

**Comment by lucamezzalira** [comment]
I agree with you, having percentage will help a lot on styling the components

**Comment by despairblue** [comment]
Also this won't work for images.

**Comment by roman01la** [comment]
+1

**Comment by a-botermans** [comment]
+1

**Comment by ide** [comment]
Send a PR to https://github.com/facebook/css-layout, which is the layout engine that React Native uses.

**Comment by brentvatne** [comment]
```
position: 'absolute',
left: 0,
right: 0,
```

This is a good way to get 100%. If you add `top: 0, bottom: 0` also it will take up the entire screen

**Comment by tommcgurl** [comment]
This would definitely be nice to have for images as @despairblue mentioned. +1

**Comment by brentvatne** [comment]
Sounds reasonable @tommcgurl - check out [facebook/css-layout](https://github.com/facebook/css-layout) and create an issue there, maybe someone will be up for implementing it :smile:

**Comment by tommcgurl** [comment]
Thanks @brentvatne, I'll definitely check that out :+1:

**Comment by vitalets** [comment]
Until this is supported natively you can try https://github.com/vitalets/react-native-extended-stylesheet that supports percentage in styles for single orientation.

**Comment by note89** [comment]
Why not just write flex like this if you want %
```
flex:0.6 --> 60%
flex:0.4 --> 40% spacer
```
just add a empty view as the spacer and your of to the races

**Comment by andrioid** [comment]
Has this been changed recently? I have working code, that uses '100%' in width and height. I also came across Yellobox.js in the RN repo that uses percentages (https://github.com/facebook/react-native/blob/9f33fe258312987f490cc0f3a71c0c4f93494e7f/Libraries/ReactNative/YellowBox.js). However, I can't find any mention of this in the documentation

Is this unintended or is the documentation lacking?

**Comment by tomfordweb** [comment]
I was able to do something similar with display: flex on a parent container:

```
export const ColumnPreviewBox = (props) => {
	const percentage = 100 * (1 / props.totalCount);
	const styles = {
		width:  percentage + '%',
		display: 'inline-block',
	}
	return (
		<div style={styles}>
			<div className="well"></div>
		</div>	
	)
}
```

**Comment by fnky** [comment]
@andrioid Yeah, this was introduced in https://github.com/facebook/react-native/commit/3f49e743bea730907066677c7cbfbb1260677d11

**Comment by Jun711** [comment]
Percentage value is not supported for transform yet, I guess. 
[transform](https://facebook.github.io/react-native/docs/transforms.html#transform)

**Comment by sgskylark** [comment]
How to add condition landscape in hide some section. using react-native.
