### ISSUE TITLE
Separator not being rendered

### ISSUE THREAD

**Issue by diegolmello** [facebook/react-native#36408]
### Description

There are a few issues about this topic, but none of them have a solution:
- https://github.com/facebook/react-native/issues/28575
- https://github.com/facebook/react-native/issues/22927
- https://github.com/facebook/react-native/issues/13959

I've attached a simple FlatList snack showing the separator isn't rendering sometimes.
It can be reproduced both on iOS and Android.
The easier way to do it is to decrease display size on a11y, but it can be reproduced on default as well.

### React Native Version

0.71.4

### Output of `npx react-native info`

Expo 47 from snack.

### Steps to reproduce

Add a separator to a FlatList with hairlineWidth or 1.

### Snack, code example, screenshot, or link to a repository

https://snack.expo.dev/@diegolmello/f6c27a

Note missing separators on 2-3, 7-8, etc
<img src="https://user-images.githubusercontent.com/804994/223789219-d48c95b8-9730-4c4c-a0cc-5e8952a23e03.jpg" width="350" />

**Comment by diegolmello** [comment]
It's still an issue on 0.71.4.

**Comment by priyaWedo** [comment]
yes, i have checked it, it is working fine in android but does not working in ios 
i have attached a expo snack here 
https://snack.expo.dev/ELGB5axVt?platform=ios

**Comment by nabilfreeman** [comment]
Still a problem on Android (we are on 0.70.4).

Have temporarily set everything 1dp for Android platform.

Going to try an updated version of this old PR that never got merged as a patch later

https://github.com/facebook/react-native/pull/30481/files
