### ISSUE TITLE
How to be compatible with iOS 11.0?

### ISSUE THREAD

**Issue by yupuyang** [facebook/react-native#36412]
### Description

How to be compatible with iOS 11.0? needs to be compatible with iOS 11.0

### React Native Version

0.71

### Output of `npx react-native info`

Latest version

### Steps to reproduce

Latest version

### Snack, code example, screenshot, or link to a repository

Latest version

**Comment by iBotPeaches** [comment]
RN71 is not compatible with anything lower than 12.4 so you don't. They don't move the minimum iOS version without consideration, so if it was that easy to support - it would have.

You could downgrade a bunch of RN versions to get iOS 11 support, but I don't recommend that.

**Comment by cortinico** [comment]
> RN71 is not compatible with anything lower than 12.4 so you don't. They don't move the minimum iOS version without consideration, so if it was that easy to support - it would have.
> You could downgrade a bunch of RN versions to get iOS 11 support, but I don't recommend that.

The answer @iBotPeaches provided is correct (thanks for doing it).
I'll be closing this.
