### ISSUE TITLE
Rotating View appears jagged on Android

### ISSUE THREAD

**Issue by AvdeenkoArtem** [facebook/react-native#36437]
### Description

Rotating view with border appears to be jagged  on Android. On IOS, this is fixed by adding shouldRasterizeIOS prop.
![IMAGE 2023-03-10 18:09:22](https://user-images.githubusercontent.com/103595162/224351409-1326d20e-a646-49f8-82d7-18f82e937fe9.jpg)

### React Native Version

0.70.6

### Output of `npx react-native info`

System:
    OS: macOS 12.6.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 506.82 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.16.0/bin/yarn
    npm: 8.19.1 - ~/.nvm/versions/node/v16.16.0/bin/npm
    Watchman: 2022.12.26.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 28, 29, 30, 31, 33
      Build Tools: 28.0.0, 28.0.3, 29.0.0, 29.0.2, 29.0.3, 30.0.0, 30.0.2, 30.0.3, 31.0.0
      System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-31 | Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.6 => 0.70.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. Create the View component.
2. Add transform: [{rotateZ: '5deg'}] style to View.

### Snack, code example, screenshot, or link to a repository

![IMAGE 2023-03-10 18:09:22](https://user-images.githubusercontent.com/103595162/224352294-cd492027-7b26-41e4-b030-4b661c353a5f.jpg)

**Comment by natuanorg** [comment]
I also have the same problem, @AvdeenkoArtem have you found a solution for this problem?

**Comment by AvdeenkoArtem** [comment]
@natuanorg  no, left this behavior
