### ISSUE TITLE
Import from another file not working in new architecture 

### ISSUE THREAD

**Issue by shagun-firstlight** [facebook/react-native#36431]
### Description

export type PlayerConfig = {
  mediaURL: string;
  mediaType: MediaTypeValue;
  drmLicenseURL?: string | undefined | null;
  drmType?: DrmTypeValue | undefined | null;
}

export interface Spec extends TurboModule {
  initWithConfig(playerConfig: PlayerConfig): Promise<number>;
  getNativeID(): Promise<number>;
  load(): Promise<void>;
  play(): Promise<void>;
  pause(): Promise<void>;
  stop(): Promise<void>;
  dispose(): Promise<void>;
  seek(seekPosition: number): Promise<void>;
}
it works for me 

but 
NativePlayer.ts
import { PlayerConfig } from '../typings/data.ts';

export interface Spec extends TurboModule {
  initWithConfig(playerConfig: PlayerConfig): Promise<number>;
}

data.ts
export type PlayerConfig = {
  mediaURL: string;
  mediaType: MediaTypeValue;
  drmLicenseURL?: string | undefined | null;
  drmType?: DrmTypeValue | undefined | null;
}
it does not work for me

### React Native Version

0.71.4

### Output of `npx react-native info`

System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 628.36 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.18.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 6.14.15 - /usr/local/bin/npm
    Watchman: 2022.11.07.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.4 => 0.71.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

importing a type from another file is not working for me giving error 

UnsupportedGenericParserError: Module NativePlayer: Unrecognized generic type ‘ PlayerConfig’ in NativeModule spec.

### Snack, code example, screenshot, or link to a repository

https://github.com/shagun-firstlight/testNewArch1.git

**Comment by shagun-firstlight** [comment]
> ⚠️	Newer Version of React Native is Available!
> ℹ️	You are on a supported minor version, but it looks like there's a newer patch available. Please [upgrade](https://reactnative.dev/docs/upgrading) to the highest patch for your minor or latest and verify if the issue persists (alternatively, create a new project and repro the issue in it). If it does not repro, please let us know so we can close out this issue. This helps us ensure we are looking at issues that still exist in the most recent releases.

still not working for me

**Comment by Rafael3326** [comment]
I have the same problem, unfortunately I have to use version 0.70.7 to continue with my studies, has anyone managed to solve this error in version 0.71.4?
