### ISSUE TITLE
Creating a TurboModule in the app causes it to be undefined

### ISSUE THREAD

**Issue by BraveEvidence** [facebook/react-native#36430]
### Description

I am trying to create a TurboModule for my app. I don't want to create it as a separate module as mentioned over [here](https://reactnative.dev/docs/next/the-new-architecture/pillars-turbomodules). I want it to be part of my app So I created a RTNCalculator folder inside that a js folder and created NativeCalculator.ts file. Then in the package.json of my application I added the following code

```
  "codegenConfig": {
    "libraries": [
      {
        "name": "NativeCalculator",
        "type": "modules",
        "jsSrcsDir": "./RTNCalculator/js"
      }
    ]
  }
```

Then I ran .`/gradlew generateCodegenArtifactsFromSchema` and in the main android folder I created the following files

CalculatorModule.kt and CalculatorPackage.kt

```
class CalculatorPackage : TurboReactPackage() {
    override fun getModule(name: String, reactContext: ReactApplicationContext): NativeModule? {
        return if (name == CalculatorModule.NAME) {
            CalculatorModule(reactContext)
        } else {
            null
        }
    }

    override fun getReactModuleInfoProvider(): ReactModuleInfoProvider? {
        return ReactModuleInfoProvider {
            val moduleInfos: MutableMap<String, ReactModuleInfo> = HashMap()
            moduleInfos[CalculatorModule.NAME] = ReactModuleInfo(
                CalculatorModule.NAME,
                CalculatorModule.NAME,
                false,  // canOverrideExistingModule
                false,  // needsEagerInit
                true,  // hasConstants
                false,  // isCxxModule
                true // isTurboModule
            )
            moduleInfos
        }
    }
}

```

```
class CalculatorModule(context: ReactApplicationContext): NativeCalculatorSpec(context) {
    override fun getName(): String {
        return NAME
    }

    override fun add(a: Double, b: Double, promise: Promise?) {
        promise!!.resolve(a+b)
    }

    override fun pickImage(promise: Promise?) {

    }

    override fun someDummyMethod(promise: Promise?) {

    }

    override fun addTwo(a: Double, b: Double, promise: Promise?) {
        
    }

    companion object {
        const val NAME = "RTNCalculator"
    }



}

```

Then in MainApplication.java I added `packages.add(new CalculatorPackage());`

Then to use it in my App.tsx

import RTNCalculator from './RTNCalculator/js/NativeCalculator';

Now when I call the add method of RTNCalculator I get undefined. What am I missing?

### React Native Version

0.71.4

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1
    Memory: 139.70 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
    Watchman: 2023.02.06.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /Users/transformhub/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 31, 32, 33
      Build Tools: 30.0.3, 31.0.0, 32.0.0, 33.0.0
      System Images: android-31 | Google APIs ARM 64 v8a, android-33 | Google APIs ARM 64 v8a, android-33 | Google Play ARM 64 v8a
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9477386
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: javac 16 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.4 => 0.71.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

You can try running the code from [here](https://github.com/BraveEvidence/TMTry) and click the Get addition button

### Snack, code example, screenshot, or link to a repository

https://github.com/BraveEvidence/TMTry

**Comment by cipolleschi** [comment]
The TM system starts from JS. You need to write a typed Spec in JS or TS of your TurboModule in order to make it work. I cant't see that file in the  description. 

I'd say that:
1. let's try to update to 0.73
2. let's create a reproducer using this [template](https://github.com/react-native-community/reproducer-react-native). 
3. If the problem is fixed, please close the issue, otherwise, we can look into it.
