### ISSUE TITLE
@hramos reproducible with RN 0.56. Reopen?

### ISSUE THREAD

**Issue by axelmy318** [facebook/react-native#36445]
@hramos reproducible with RN 0.56. Reopen?
If need, i can create repo or expo snack, but all info is here.

@remicoges @windev92 @TiagoCoelhoB 
First of all, this is not a bug or metro bundler problem.

Real cause is that Image.resolveAssetSource (`react-native/blob/master/Libraries/Image/resolveAssetSource.js`) in android release builds returns resource identifier instead of file path (see `react-native/Libraries/Image/AssetSourceResolver.js:80`). 
So that any non-native rendering (like webview / html) can't use resolved identifier "as is".
But there is a "workaround": assets and resources are accessible using `file:///android_asset` and `file:///android_res` (info from official android docs).

So in my case it worked as: 

```
// ./utils/getAndroidReleaseImageURI.ts
// require'd image returns resource identifier in uri on android
// see react-native/Libraries/Image/AssetSourceResolver.js:80
const androidDrawableResPath = `file:///android_res/drawable`;
const getAndroidReleaseImageURI = (sourceURI: string) => `${androidDrawableResPath}/${sourceURI}`;
```

```
// ./Component.tsx
...
import { Image, Platform } from 'react-native';
import getAndroidReleaseImageURI from './utils/getAndroidReleaseImageURI';

const isAndroidRelease = (Platform.OS ==='android' && !__DEV__);
...
render() {
  const image = Image.resolveAssetSource(require('./rn-required-image.png'));
  const uri = isAndroidRelease ? getAndroidReleaseImageURI(image.uri) : image.uri;
  return (
    <Webview 
      html={`<html><body><img src="${uri}"></body></html>`}
    />
  );
}
...
```

It doesn't work with run-android in release mode (set from rn android developer config), but production build is ok.

As fast fix for run-android - for example, check if resolved uri not to be url to remote file or file with extension from drawableFileTypes (`react-native/local-cli/bundle/assetPathUtils.js:38`) before call to getAndroidReleaseImageURI

```
const drawableFileTypes = new Set([
  'gif',
  'jpeg',
  'jpg',
  'png',
  'svg',
  'webp',
  'xml',
]);
```

But, of course, it could be much better, if it will work "out-of-the-box". 

@hramos 
As i see, it need to be fixed inside AssetSourceResolver.defaultAsset (`react-native/Libraries/Image/AssetSourceResolver.js:80`) but not sure, if it affects somewhere else.

_Originally posted by @ponomarevv in https://github.com/facebook/react-native/issues/18216#issuecomment-412569517_
            

Since it doesn't work in run:android release mode, is there any way to test this on a windows machine without making a `eas build` ? Since I have only can make 30 per month I'd hate to have to make 2 different build with 1h30+ queue time just to see which one of the "android_asset"/"android_res" is working...

Since the originial issue is dated in 2018, has there been any new developement for this ? I feel like this is really complicating things for no reason at all...

**Comment by iBotPeaches** [comment]
@axelmy318 - I don't think anyone can follow a bump of a 5+ year old ticket like this to be honest. I'd just recommend you submit a pull request if you spend this effort and tracked down an issue, since its too difficult to follow otherwise.

**Comment by axelmy318** [comment]
> @axelmy318 - I don't think anyone can follow a bump of a 5+ year old ticket like this to be honest. I'd just recommend you submit a pull request if you spend this effort and tracked down an issue, since its too difficult to follow otherwise.

I don't have a fix for it though...
I'm just asking if anyone has found a workaround since it's been 5 years but I'm beginning to be kinda hopeless.

**Comment by cortinico** [comment]
> Since the originial issue is dated in 2018, has there been any new developement for this ? I feel like this is really complicating things for no reason at all...

As @iBotPeaches mentioned, please open a new issue and describe what's the expected behavior vs the intended behavior. Things have changed drastically since 2018 and is really complicated to follow over such a old conversation.
