### ISSUE TITLE
Documentation Issue: RCT_ENUM_CONVERTER example syntax error

### ISSUE THREAD

**Issue by ronenbar** [facebook/react-native#3644]
The example in the documentation (https://facebook.github.io/react-native/docs/native-modules-ios.html) for how to create a RCT_ENUM_CONVERTER has an error. It is a missing a closing curly braces. It should be:

@implementation RCTConvert (StatusBarAnimation)
RCT_ENUM_CONVERTER(UIStatusBarAnimation, (@{ @"statusBarAnimationNone" : @(UIStatusBarAnimationNone),
                                               @"statusBarAnimationFade" : @(UIStatusBarAnimationFade),
                                               @"statusBarAnimationSlide" : @(UIStatusBarAnimationSlide)},
                      UIStatusBarAnimationNone, integerValue)
@end

**Comment by cosmith** [comment]
:+1: I got bit by this before, I'll submit a PR later!
