### ISSUE TITLE
The Metro bundler does not connect to iOS devices

### ISSUE THREAD

**Issue by taZik616** [facebook/react-native#36444]
### Description

By installing according to the instructions all the libraries that worked in another project (with the react native version 0.70.6), the application is assembled without problems, but metro does not want to connect to the device, in addition, the developer menu does not open in the application

<details><summary>List of libraries</summary>

```json
{
   "@react-native-async-storage/async-storage": "^1.17.11",
    "@react-native-community/datetimepicker": "^6.7.5",
    "@react-navigation/bottom-tabs": "^6.5.7",
    "@react-navigation/native": "^6.1.6",
    "@react-navigation/native-stack": "^6.9.12",
    "date-fns": "^2.29.3",
    "events": "^3.3.0",
    "markdown-it-block-embed": "^0.0.3",
    "react": "18.2.0",
    "react-hook-form": "^7.43.5",
    "react-native": "0.71.4",
    "react-native-gesture-handler": "^2.9.0",
    "react-native-orientation-locker": "^1.5.0",
    "react-native-permissions": "^3.7.3",
    "react-native-reanimated": "^3.0.2",
    "react-native-safe-area-context": "^4.5.0",
    "react-native-screens": "^3.20.0",
    "react-native-size-matters": "^0.4.0",
    "react-native-spinkit": "^1.5.1",
    "react-native-splash-screen": "^3.3.0",
    "react-native-svg": "^13.8.0",
    "react-native-vector-icons": "^9.2.0"
}
```
</details>

> I think it's more of a problem, most likely the splash-screen library

![camphoto_684387517](https://user-images.githubusercontent.com/94304770/224477780-f8b9f412-2d16-4a3c-a7bd-12cee8366726.JPG)

To make sure that my environment is properly configured, I completely formatted the mac os disk and reinstalled the OS
After that, I followed all the necessary installations according to official instructions

### React Native Version

0.71.4

### Output of `npx react-native info`

System:
    OS: macOS 13.2.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 24.32 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.15.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.5.0 - /usr/local/bin/npm
    Watchman: 2023.03.06.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /Users/gendalf/.rvm/rubies/ruby-2.7.6/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.4 => 0.71.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. Init new react native app v0.71.4
2. Install libraries from my list. and setup their
3. Configure pods
4. `yarn ios`
5. Metro doesn't want to connect

### Snack, code example, screenshot, or link to a repository

https://github.com/taZik616/cleaning-services-app

**Comment by carlosalmonte04** [comment]
I agree with you, it may be a problem with react-native-splash-screen. Your app connects to metro after removing the splash screen from AppDelegate.m -_and adding the missing fonts_.

```objective-c
// ios/CleaningServicesApp/AppDelegate.m

//  [RNSplashScreen show];

```

**Comment by iBotPeaches** [comment]
@taZik616 - Possibly a duplicate of https://github.com/facebook/react-native/issues/36389#issuecomment-1464472145, maybe the next patch release or next major version of RN will have a patch for this.

**Comment by emmarq** [comment]
Maybe is because of this instead https://github.com/crazycodeboy/react-native-splash-screen/issues/606#issuecomment-1401875339

**Comment by msaadqureshi** [comment]
> ### Description
> By installing according to the instructions all the libraries that worked in another project (with the react native version 0.70.6), the application is assembled without problems, but metro does not want to connect to the device, in addition, the developer menu does not open in the application
> 
> List of libraries
> > I think it's more of a problem, most likely the splash-screen library
> 
> ![camphoto_684387517](https://user-images.githubusercontent.com/94304770/224477780-f8b9f412-2d16-4a3c-a7bd-12cee8366726.JPG)
> 
> To make sure that my environment is properly configured, I completely formatted the mac os disk and reinstalled the OS After that, I followed all the necessary installations according to official instructions
> 
> ### React Native Version
> 0.71.4
> 
> ### Output of `npx react-native info`
> System: OS: macOS 13.2.1 CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz Memory: 24.32 MB / 8.00 GB Shell: 5.8.1 - /bin/zsh Binaries: Node: 18.15.0 - /usr/local/bin/node Yarn: 1.22.19 - /usr/local/bin/yarn npm: 9.5.0 - /usr/local/bin/npm Watchman: 2023.03.06.00 - /usr/local/bin/watchman Managers: CocoaPods: 1.12.0 - /Users/gendalf/.rvm/rubies/ruby-2.7.6/bin/pod SDKs: iOS SDK: Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1 Android SDK: Not Found IDEs: Android Studio: Not Found Xcode: 14.2/14C18 - /usr/bin/xcodebuild Languages: Java: Not Found npmPackages: @react-native-community/cli: Not Found react: 18.2.0 => 18.2.0 react-native: 0.71.4 => 0.71.4 react-native-macos: Not Found npmGlobalPackages: _react-native_: Not Found
> 
> ### Steps to reproduce
> 1. Init new react native app v0.71.4
> 2. Install libraries from my list. and setup their
> 3. Configure pods
> 4. `yarn ios`
> 5. Metro doesn't want to connect
> 
> ### Snack, code example, screenshot, or link to a repository
> https://github.com/taZik616/cleaning-services-app

Same issue, i update Xcode 14 yesterday 
have you got any solution help me please

**Comment by carlosalmonte04** [comment]
@msaadqureshi did you try with this solution? https://github.com/crazycodeboy/react-native-splash-screen/issues/606#issuecomment-1401875339

**Comment by SandraHicks** [comment]
I need to take Screenshots for a client on an iOS 13.7 Simulator (as Apple requires screenshots on iPad Pro 2nd Gen), we have this issue without using react-native-spash-screen. Is there any workaround?

**Comment by carlosalmonte04** [comment]
@SandraHicks can you please share your `AppDelegate.m`?

**Comment by taZik616** [comment]
> @SandraHicks can you please share your `AppDelegate.m`?

I have already changed the react native version to 0.73.3 in the project, there were no changes other than adding a Splash screen display in this file

**Comment by carlosalmonte04** [comment]
@taZik616 I had your https://github.com/taZik616/cleaning-services-app connecting to metro bundler by confirming `[RNSplashScreen show]` is called **after** `[super application:application didFinishLaunchingWithOptions:launchOptions];`, like so: https://github.com/crazycodeboy/react-native-splash-screen/issues/606#issuecomment-1401875339.

**Comment by taZik616** [comment]
> Maybe is because of this instead [crazycodeboy/react-native-splash-screen#606 (comment)](https://github.com/crazycodeboy/react-native-splash-screen/issues/606#issuecomment-1401875339)

YES YES YES, it's work

I ignored this option at first, but now I tried it and made sure that you are right. Thanks )

**Comment by NikhilCodeblaze** [comment]
its stuck on splashscreen @redpanda-bit
