### ISSUE TITLE
Dimensions.get('window').height still returns wrong height on Android with notch

### ISSUE THREAD

**Issue by iway1** [facebook/react-native#36447]
### Description

As described in https://github.com/facebook/react-native/issues/23693, `useWindowDimensions` and `Dimension.get('window').height` can return the wrong value on android devices with a notch.

This can lead to unexpected behavior and cause device specific layout issues on Android React Native apps.

### React Native Version

0.71.4

### Output of `npx react-native info`

System:
    OS: macOS 13.2.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 117.25 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - /usr/local/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 8.11.0 - /usr/local/bin/npm
    Watchman: 2022.11.07.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8815526
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

See https://github.com/facebook/react-native/issues/23693. 

1. Call Dimensions.get('window').height on android devices with a notch.
2. Note that the returned screen height value is not the height of the window

### Snack, code example, screenshot, or link to a repository

https://snack.expo.dev/@iway1/carefree-popsicle

**Comment by brandonfonseca** [comment]
This **needs** to be fixed. This is core functionality for any mobile library. Please prioritize this RN team!!

**Comment by shiftytab** [comment]
I think the iphone 11s are affected by the same problem.  (for other iphones, it seems to be good)

The values returned seem to be erroneous.
I have to check with another device on the same version

**Comment by Panda-ref** [comment]
Still an issue on react-native@0.72.4

**Comment by ImRoodyDev** [comment]
facing the same issue right now
