### ISSUE TITLE
React Native KeyboardAvoidingView not working with ImageBackground

### ISSUE THREAD

**Issue by OguzEkinci** [facebook/react-native#36451]
### Description

KeyboardAvoidingView stopped working once I added ImageBackground. Actually it's working but really bad working because when i open the keyboard, picture is broken

### React Native Version

0.68.0

### Output of `npx react-native info`

System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 3.27 GB / 15.65 GB
  Binaries:
    Node: 14.17.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.6.0 - ~\AppData\Roaming\npm\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: Not Found
  Languages:
    Java: 12.0.2 - C:\Program Files\Common Files\Oracle\Java\javapath\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.68.0 => 0.68.0
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

first pic is my layout with imagebackground and second pic is children that i sent props to  my BGImage layout.

### Snack, code example, screenshot, or link to a repository

![image](https://user-images.githubusercontent.com/45782857/224579474-e6decbb8-6384-4cc6-9ae5-3c6944f73367.png)
![image](https://user-images.githubusercontent.com/45782857/224579515-056fb4bf-70ab-41a9-a4eb-52adb48d0924.png)

**Comment by alainib** [comment]
any fix ? i have the same issus
