### ISSUE TITLE
[TypeError: Network request failed]

### ISSUE THREAD

**Issue by hoatenhu** [facebook/react-native#36456]
### Description

When I call fetch on my local

### React Native Version

0.70.3

### Output of `npx react-native info`

System:
    OS: macOS 13.0
    CPU: (8) arm64 Apple M1 Pro
    Memory: 65.52 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.0/bin/npm
    Watchman: 2022.10.03.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8815526
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.3 => 0.70.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

fetch('https://192.168.1.5:8443/nexo', {
                      method: 'POST',
                      headers: {
                        'Content-Type': 'application/json',
                        'x-API-key': '{your-api-key}',
                      },
                      body: JSON.stringify({
                        ...securedMessage,
                        MessageHeader: requestBody.MessageHeader,
                      }),
                    })
                      .then(response => {
                        console.log('2');
                        console.log(response);
                       
                      })
                      .catch(error => {
                        console.log(error);
                      })

### Snack, code example, screenshot, or link to a repository

<img width="647" alt="image" src="https://user-images.githubusercontent.com/84147184/224653470-48a912c2-c3fb-48db-a54d-a2bae59ab52b.png">

**Comment by lunaleaps** [comment]
Closing as this issue is not descriptive enough on how this is a React Native issue.

**Comment by efstathiosntonas** [comment]
@lunaleaps sorry for bumping this, I think there's something going on with network requests either with fetch or axios 1.x.x and rn 0.71.x

I get tons of `network_error` from many different users and during our QA process on staging servers which have 0 traffic. There's definitely nothing wrong with our servers since I do not see any 4xx,5xx errors at all. It happens on our aws lambda functions and firebase functions, there's no chance both to have networking issues. 

It's really weird.

**Comment by hypnocill** [comment]
> @lunaleaps sorry for bumping this, I think there's something going on with network requests either with fetch or axios 1.x.x and rn 0.71.x
> 
> I get tons of `network error` or `ERR_NETWORK` with **NO status code** on **both** platforms from many different users and during our QA process on staging servers which have 0 traffic and real testing devices have stable internet. There's definitely nothing wrong with our servers since I do not see any 4xx,5xx errors at all. It happens on our aws lambda functions and firebase functions, there's no chance both to have networking issues.
> 
> It's really weird.

Same here. As far as I read, it has something to do with app's changing state cancelling fetch requests but I could not reproduce it in any way (not on Android nor on iOS) yet many of our users seem to get this error.
Anyone has an idea what's going on?

**Comment by efstathiosntonas** [comment]
@hypnocill we’ve solved the aws lambda errors by changing the domain name from aaa.xyz to aaa.com and since then it works as expected. The reason was the user’s router was cutting off all .xyz (it was actually a .xyz domain, this is not a placeholder),  request as it was considered spam. The users where at AT&T provider. 

Based on that, either your domain is “firewalled” by the router or probably a dns issue thus the no status code, the request never reached our .xyz domain.

**Comment by efstathiosntonas** [comment]
@hypnocill damn that’s a really long lasting bug as it seems on native level, I wasn’t aware of it. I need to perform tests now 🤣

**Comment by hypnocill** [comment]
@efstathiosntonas Yeah... I just checked the error reports and they seem completely random. Some of the users that get them are in wifi, while others are on cellular so probably it's not a router issue. Will continue looking into it, fingers crossed

**Comment by Phong-TH** [comment]
@efstathiosntonas @lunaleaps we have the same issue, it happens randomly on production on both fetch and axios but can not be replicated. The domain does not have any problem with CORS or SSL and works perfectly. The number of reports is increasing, still a pain for our clients.

**Comment by daheeahn** [comment]
@hypnocill @Phong-TH 
Me too. It's very random.
My SSL is no problem.

**Comment by lunaleaps** [comment]
Hm, I don't have any additional insight but perhaps you can trace into what is triggering ERR_NETWORK? Seems like iOS there is a known case where this fires, but what about for Android? Is this something you can put in a loop and see if it's reproducible x% of the time?

**Comment by anniewey** [comment]
I'm observing this error on every iOS physical device but cant reproduce on simulator though. Android is all good.

It happens when app is fetching POST request and user switch to another app causing the RN app pushed to background and then request failed. 

For my case, the RN app crashed when user return to the app. When i check my Crashlytics it's returning `Network request failed` error. Weirdly I'm calling the fetch in try catch block, no idea why it crashed. Anyway back to topic, the fetching seems to fail when app move to background state.

**Comment by tiagomelilo** [comment]
Hi @anniewey. I'm passing to the same problem here. Have you found a solution yet? 

> I'm observing this error on every iOS physical device but cant reproduce on simulator though. Android is all good.
> 
> It happens when app is fetching POST request and user switch to another app causing the RN app pushed to background and then request failed.
> 
> For my case, the RN app crashed when user return to the app. When i check my Crashlytics it's returning `Network request failed` error. Weirdly I'm calling the fetch in try catch block, no idea why it crashed. Anyway back to topic, the fetching seems to fail when app move to background state.

Hi @anniewey. I'm passing to the same problema here. I've tried some plugins (background-fetch, background-taks, background-actions), I've too tried using axios, fetch and XMLHttpRequest to make this POST request, but none successfully. Have you found the solution? Thanks!

**Comment by anniewey** [comment]
@tiagomelilo no, unfortunately i've not found any solution to this yet. was thinking to try out those bg fetch library but plans changed and i haven't try it out yet.

**Comment by newyoung21** [comment]
@hypnocill 
Have you found a solution?

**Comment by hypnocill** [comment]
> @hypnocill 
> Have you found a solution?

Not really. Just catching it and ignoring it wherever possible

**Comment by efstathiosntonas** [comment]
Hey guys, axios 1.6.1 was released few hours ago that contains a fix for the headers, can you please check it out? 

This is the [PR](https://github.com/axios/axios/pull/6056) that contains the fix

**Comment by CiprianDraghici** [comment]
> Hey guys, axios 1.6.1 was released few hours ago that contains a fix for the headers, can you please check it out?
> 
> This is the [PR](https://github.com/axios/axios/pull/6056) that contains the fix

Hey @efstathiosntonas ,
I have a similar issue issue even if I updated the axios to the latest version (not sure if is the same).

I just trying to do a simple post-request but the issue still persists
 `URL`: `https://localhost:1234/api/auth/signIn `
 `body`: `{"email": "user@gmail.com", "password": "user-pass123"} `
 `config`: `{"headers": {"Accept": "application/json", "Authorization": null, "Content-Type": "application/json"}}`
 
 error: `AxiosError: Network Error\n    at handleError (http://[ip]:19000/node_modules/expo/AppEntry.bundle/...`
 
 Looks like the issue is related to the `localhost`, reproducible only on `android` emulator. Everything is working fine on the web or using a remote server endpoint.

**Comment by L-x-C** [comment]
We have also encountered this issue. It seems to occur after users minimize the app and then reopen it after a while, which leads to a loss of network connection. Additionally, on Android devices, the network connection tends to recover upon entering the next page after the disconnection. However, on iOS, the disconnection persists indefinitely unless the app is completely closed and restarted from the background.

Is there something to do with AppState in background?

**Comment by L-x-C** [comment]
> Hey guys, axios 1.6.1 was released few hours ago that contains a fix for the headers, can you please check it out?
> 
> This is the [PR](https://github.com/axios/axios/pull/6056) that contains the fix

We have tried upgrading Axios to version 1.6.1, but it did not work.

**Comment by hanwenbo** [comment]
This problem still exists

**Comment by johnfanyong** [comment]
This problem is still present in version 0.74.5

**Comment by Nader-CS** [comment]
the problem still exist , when query about to start and put app in bacgrkound , queries return fetch error or network error

**Comment by AymaneShadow** [comment]
Problem still persists. Tested using react-native v0.79.5.

**Comment by AymaneShadow** [comment]
Problem still persists.

In my case, I'm using:

    react-native v0.79.5.
    expo v53.0.20
    axios v1.11.0.
    expo-task-manager v13.1.6
    expo-background-task v0.2.8

I defined a task using expo-task-manager's TaskManager.defineTask(taskName, callback) and registered it using expo-background-task's BackgroundTask.registerTaskAsync(taskName, taskOptions). This task is supposed to run periodically when the app is in the background whenever the callback is called by the OS.

Within the callback of TaskManager.defineTask(taskName, callback) I try to use axios to make a request to a certain URL. However, I get the following error:

    { "message": "Network Error", "name": "AxiosError", "stack": "AxiosError: Network Error\n    at handleError (http://192.168.0.100:8081/index.ts.bundle//&platform=android&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.bytecode=1&transform.routerRoot=app&unstable_transformProfile=hermes-stable:238567:32)\n    at call (native)\n    at dispatchEvent (http://192.168.0.100:8081/index.ts.bundle//&platform=android&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.bytecode=1&transform.routerRoot=app&unstable_transformProfile=hermes-stable:63080:31)\n    at setReadyState (http://192.168.0.100:8081/index.ts.bundle//&platform=android&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.bytecode=1&transform.routerRoot=app&unstable_transformProfile=hermes-stable:65434:33)\n    at __didCompleteResponse (http://192.168.0.100:8081/index.ts.bundle//&platform=android&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.bytecode=1&transform.routerRoot=app&unstable_transformProfile=hermes-stable:65250:29)\n    at apply (native)\n    at anonymous (http://192.168.0.100:8081/index.ts.bundle//&platform=android&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.bytecode=1&transform.routerRoot=app&unstable_transformProfile=hermes-stable:65370:124)\n    at apply (native)\n    at emit (http://192.168.0.100:8081/index.ts.bundle//&platform=android&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.bytecode=1&transform.routerRoot=app&unstable_transformProfile=hermes-stable:12288:40)\n    at apply (native)\n    at anonymous (http://192.168.0.100:8081/index.ts.bundle//&platform=android&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.bytecode=1&transform.routerRoot=app&unstable_transformProfile=hermes-stable:12147:200)\n    at emit (http://192.168.0.100:8081/index.ts.bundle//&platform=android&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.bytecode=1&transform.routerRoot=app&unstable_transformProfile=hermes-stable:12161:66)\n    at ?anon_0_ (http://192.168.0.100:8081/index.ts.bundle//&platform=android&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.bytecode=1&transform.routerRoot=app&unstable_transformProfile=hermes-stable:239213:64)\n    at throw (native)\n    at asyncGeneratorStep (http://192.168.0.100:8081/index.ts.bundle//&platform=android&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.bytecode=1&transform.routerRoot=app&unstable_transformProfile=hermes-stable:11157:19)\n    at _throw (http://192.168.0.100:8081/index.ts.bundle//&platform=android&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.bytecode=1&transform.routerRoot=app&unstable_transformProfile=hermes-stable:11174:29)\n    at tryCallOne (address at InternalBytecode.js:1:1180)\n    at anonymous (address at InternalBytecode.js:1:1874)", "config": { "transitional": { "silentJSONParsing": true, "forcedJSONParsing": true, "clarifyTimeoutError": false }, "adapter": [ "xhr", "http", "fetch" ], "transformRequest": [ null ], "transformResponse": [ null ], "timeout": 0, "xsrfCookieName": "XSRF-TOKEN", "xsrfHeaderName": "X-XSRF-TOKEN", "maxContentLength": -1, "maxBodyLength": -1, "env": {}, "headers": { "Accept": "application/json, text/plain, */*", "Content-Type": "application/json", "Authorization": "Bearer SecretToken", "User-Agent": "SecretName/SecretVersion" }, "method": "post", "url": "SecretURL", "data": "SecretData", "allowAbsoluteUrls": true }, "code": "ERR_NETWORK" }

This means that the request didn't even reach the server (I checked the server logs). Something is preventing axios from working when the app is in the background.

I also tried react-native's fetch and I got:

    [TypeError: Network request failed]

Which makes me think this is not a problem with axios but rather react-native.

Could this issue be reopened?

**Comment by Nader-CS** [comment]
yes this problem stil exist

**Comment by Yashveer-Soni** [comment]
this problem still exists in my app 
api is working on some device well
but some device we got instant error like network request failed.
and the server support ipv4 and ipv6

**Comment by thisisadarshjaiswal** [comment]
This is becoming super painful, Any resolution yet?

**Comment by Yashveer-Soni** [comment]
> This is becoming super painful, Any resolution yet?

The problem is not from react native.
I has two circumstances 
1. Add network configuration in manifest file.
2. The server you are using are not ipv6
It is ipv4

Update ipv4 to ipv6
