### ISSUE TITLE
Different react native apps having the same MD5, sha1 and sha256

### ISSUE THREAD

**Issue by ai-dev-official** [facebook/react-native#36455]
### Description

Debug keystores
![Screenshot 2023-03-13 055940](https://user-images.githubusercontent.com/85434811/224624443-00602ca3-e949-41b2-875c-6f817cd904cc.png)
 of different react-native apps contain the same MD5, sha1, sha256 signing keys. As a result, when trying to use google firebase authentication, it is rejected as app with same signing already exist. 
![Screenshot 2023-03-13 060041](https://user-images.githubusercontent.com/85434811/224622142-6d2256d6-ebe1-406b-b413-204fafe2f237.png)
![Screenshot 2023-03-13 060245](https://user-images.githubusercontent.com/85434811/224622145-22921871-f639-46c1-99c6-5aebf74eee72.png)

![Screenshot 2023-03-13 063542](https://user-images.githubusercontent.com/85434811/224625593-f20b577c-47e0-48a6-8c13-e9b4771e5fd9.png)

### React Native Version

0.71.4

### Output of `npx react-native info`

$ npx react-native info
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 Intel(R) Core(TM) i5-10400T CPU @ 2.00GHz
    Memory: 2.00 GB / 7.81 GB
  Binaries:
    Node: 19.3.0 - A:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.2.0 - A:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 28, 30, 31, 32, 33
      Build Tools: 30.0.3, 31.0.0, 33.0.0
      System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-31 | Google APIs Intel x86 Atom_64, android-31 | Google Play Intel x86 Atom_64, android-33 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Disabled
      Versions: 10.0.19041.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 17.3.32922.545 (Visual Studio Community 2022)
  Languages:
    Java: 18.0.2 - C:\Program Files\Common Files\Oracle\Java\javapath\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.4 => 0.71.4
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

create a react native app

npm install firebase

create firebase folder

create FirebaseConfig and add the initialization generated by firebase console when you create an authentication app

Run the following to generate keys: keytool -list -v \
-alias androiddebugkey -keystore %USERPROFILE%\.android\debug.keystore 

cd android && ./gradlew signingReport

### Snack, code example, screenshot, or link to a repository

https://github.com/ai-dev-official/React-Native-Google-Auth

**Comment by cortinico** [comment]
> of different react-native apps contain the same MD5, sha1, sha256 signing keys. As a result, when trying to use google firebase authentication, it is rejected as app with same signing already exist.

That's because you're using the same debug keystore for different apps.
You should create a release keystore as described here: https://reactnative.dev/docs/signed-apk-android
