### ISSUE TITLE
Android Spinner does not change value in react native's new architecture

### ISSUE THREAD

**Issue by BraveEvidence** [facebook/react-native#36457]
### Description

I am trying to implement android spinner/dropdown in react native's new architecture. I have managed to implement it but the only issue being when I select a value from the spinner it does not change. Please check below video for understanding 

https://user-images.githubusercontent.com/24708929/224664284-a4860fa5-9ee8-4920-9b74-7aabb4b0705f.mov

I have done the same project in android as well and it works fine. [Here](https://github.com/BraveEvidence/NativeSpinner) is the native  android source code and [here](https://github.com/BraveEvidence/ReactNativeNewArch2023DropDownSpinnerIosPickerView) is the react native project 

### React Native Version

0.71.3

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1
    Memory: 114.03 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
    Watchman: 2023.02.06.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /Users/transformhub/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 31, 32, 33
      Build Tools: 30.0.3, 31.0.0, 32.0.0, 33.0.0
      System Images: android-31 | Google APIs ARM 64 v8a, android-33 | Google APIs ARM 64 v8a, android-33 | Google Play ARM 64 v8a
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9477386
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: javac 16 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.3 => 0.71.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Download the project from https://github.com/BraveEvidence/ReactNativeNewArch2023DropDownSpinnerIosPickerView and try running it with the new architecture enabled

### Snack, code example, screenshot, or link to a repository

https://github.com/BraveEvidence/ReactNativeNewArch2023DropDownSpinnerIosPickerView

Uploading android dropdown.mov…

**Comment by cortinico** [comment]
I've looked into this, and the problem is that you're not implementing the custom view correctly. This issue is not related to the New Architecture at all, and your code would fail to work also on the Old Architecture.

I suggest that you look into how other spinners are implemented. Specifically I've tried your code and if you add those lines:
https://github.com/chymtt/ReactNativeDropdownAndroid/blob/d76ba6ff236722f01ccf3d53cbd08306fee6b9b3/android/src/main/java/com/chymtt/reactnativedropdown/Dropdown.java#L94-L107

from `react-native-dropdown-android` your project will work correctly
