### ISSUE TITLE
[0.14] Commits to cherry-pick

### ISSUE THREAD

**Issue by mkonicek** [facebook/react-native#3646]
I've cut the branch at https://github.com/facebook/react-native/commit/dad45aa8f2eac98f52c76e73d8eaa50587861888, haven't pushed to npm yet.

We should cherry-pick the following into 0.14-stable before pushing to npm:
- [x] Chrome debugging: https://github.com/facebook/react-native/commit/f0cf0b0288729c657d07eb955015386567690751, https://github.com/facebook/react-native/commit/c1faabcdf6f4fd15643743d23ebda556c4f49045, https://github.com/facebook/react-native/commit/271de0f9b64576fa8747fc7adc17ac435561248b
- [x] Fix for old asset system: 47926abca9d60b0a6090c3e82f50fb75ec659c6c (https://github.com/facebook/react-native/pull/3640)

Here are all the commits on master since the branch cut:
https://github.com/facebook/react-native/compare/0.14-stable...master

cc @martinbigio, @ide

**Comment by arbesfeld** [comment]
Any chance https://github.com/facebook/react-native/pull/3189 could make it into 0.14? Happy to help debug tests

**Comment by mkonicek** [comment]
I'm close to merging #3189, fingers crossed :) Got a bit stuck on some github sync issues. It's a pretty big change but tested so hopefully safe. I'll test again and see if we can pick this, would be cool.

**Comment by mkonicek** [comment]
Just released 0.14.0-rc. Hopefully we can still cherry-pick https://github.com/facebook/react-native/pull/3189 to a followup rc.

**Comment by martinbigio** [comment]
Awesome!

**Comment by mkonicek** [comment]
For the 0.14.0 release, we should cherry-pick:
- [ ] https://github.com/facebook/react-native/commit/500ffa9b763d03e759e9b2897da7f4f7904934cf (fix for https://github.com/facebook/react-native/issues/3782)

**Comment by mkonicek** [comment]
@arbesfeld I'll be away all of this week (conference and then vacation), might not get to cherry-picking https://github.com/facebook/react-native/commit/3a743ef228a14e07c77c5488b080413643ec9c4b. We should probably also cherry-pick this followup fix: https://github.com/facebook/react-native/commit/88655001e36315c2a8f3bebc1b33e5b0cad9d077. Worst case the bundle loading will go out in 0.15-rc which will be out early next week.

**Comment by ide** [comment]
I merged 500ffa9b763d03e759 into 0.14-stable. Let's ship the other commits with 0.15 so that they have two weeks of testing.

**Comment by satya164** [comment]
Closing since the release is already done.
