### ISSUE TITLE
Strange behavior of tsconfig target and lib options

### ISSUE THREAD

**Issue by NinjaDevRN** [facebook/react-native#36474]
### Description

Hi! There is a strange behaviour, as for me. I set `target` to `'ES5'` in tsconfig.json. Then i wrote different variants of BigInt inside *.ts file. I added this file inside `useEffect` hook. I received typescript error in the VsCode problems window. But my application still have worked correctly.
I restarted TS-server, rebuilt applications, restarted metro.
So, did I miss anything? I expected that the application would crash.

### tsconfig.json:
```json
{
  "compilerOptions": {
    "target": "ES5",
    "module": "commonjs",
    "types": ["react-native", "jest"],
    "allowJs": true,
    "jsx": "react-native",
    "noEmit": true,
    "isolatedModules": true,
    "strict": true,
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "allowSyntheticDefaultImports": true,
    "forceConsistentCasingInFileNames": true,
    "esModuleInterop": true,
    "skipLibCheck": true,

    "alwaysStrict": true,
    "experimentalDecorators": true,
    "noFallthroughCasesInSwitch": true,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "strictFunctionTypes": true,
    "strictNullChecks": true,
    "strictPropertyInitialization": true,
  },
}
```
### BigInt
```ts
const checkBigInt = () => {
  console.log('1', 9007199254740991n);
  // ↪ 9007199254740991n

  console.log('2', BigInt(9007199254740991));
  // ↪ 9007199254740991n

  console.log('3', BigInt('9007199254740991'));
  // ↪ 9007199254740991n

  console.log('4', BigInt('0x1fffffffffffff'));
  // ↪ 9007199254740991n

  console.log(
    '5',
    BigInt('0b11111111111111111111111111111111111111111111111111111'),
  );
  // ↪ 9007199254740991n
};
```

### Custom hook
```ts
import {useEffect} from 'react';
import checkBigInt from './checkBigInt';

export const useEsNextFeatures = () => {
  useEffect(() => {
    checkBigInt();
  }, []);
};
```
### Usage of the custom hook
```tsx
import React, {FC} from 'react';
import {Text, View} from 'react-native';
import {useEsNextFeatures} from './src/ecmaScriptFeatures/esNext/useEsNextFeatures';

const App: FC = () => {
  useEsNextFeatures();

  const itsWorked = 9007199254740991n;

  return (
    <>
      <View>
        <Text>{`${itsWorked}`}</Text>
      </View>
    </>
  );
};

export default App;
```

### VSCode Problems
![Screenshot 2023-03-14 at 22 05 44](https://user-images.githubusercontent.com/126331230/225026830-aea4bcfd-150b-49ad-8846-57234a9d928c.png)

### Screenshot of running applications with console.log output
![Screenshot 2023-03-14 at 22 09 04](https://user-images.githubusercontent.com/126331230/225027721-7afc09ae-a05e-4b31-b0ba-aa577b068906.png)

### React Native Version

0.71.4

### Output of `npx react-native info`

```
System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 301.88 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.6.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.4.0 - /opt/homebrew/bin/npm
    Watchman: 2023.01.30.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9514443
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.18 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.4 => 0.71.4
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

I set `target` to `'ES5'` in tsconfig.json. Then i wrote different variants of BigInt inside *.ts file. I added this file inside `useEffect` hook. I received typescript error in the VsCode problems window. But my application still have worked correctly.
I restarted TS-server, rebuilt applications, restarted metro.
So, did I miss anything? I expected that the application would crash.

### Snack, code example, screenshot, or link to a repository

[Github repo](https://github.com/NinjaDevRN/rn-ecmascript-support)

**Comment by blakef** [comment]
My reading of that is that Hermes, our JS engine, ships with [BigInt support since version 0.70](https://github.com/facebook/docusaurus/blob/2f75979bc5b4fd971225098e1c122efdd71d6e6f/packages/docusaurus/src/client/exports/__tests__/useBaseUrl.test.tsx#L70).

We could maybe do more in our [shipped typings](https://github.com/facebook/react-native/blob/57a2508ae6e8b33fb556c1e194f81a65b6784a8f/types/index.d.ts#L4) to be explicit about this, I don't see it in there.

**Comment by NinjaDevRN** [comment]
@blakef Thank you for this clarifying. Ok, I understand. It will be good to have such a table like [this](https://github.com/NinjaDevRN/react-native-ecmascript-support) for Hermes versions and ECMAScript features connections

**Comment by blakef** [comment]
Is this useful: https://kangax.github.io/compat-table/es6/

**Comment by NickGerleman** [comment]
`lib` field in template tsconfig has been updated for BigInt and other JS support in RN 0.72.
