### ISSUE TITLE
[Mac] > Process 'command '/Users/username/Library/Android/ndk/ndk-build'' finished with non-zero exit value 2

### ISSUE THREAD

**Issue by yychun1217** [facebook/react-native#3647]
* What went wrong:
Execution failed for task ':ReactAndroid:buildReactNdkLib'.

It also mentions that:
/Users/username/Library/Android/ndk/build/core/add-application.mk:49: Native/react-native/ReactAndroid/src/main/jni/Application.mk: No such file or directory
Android NDK: NDK_PROJECT_PATH==null.  Please explicitly set APP_BUILD_SCRIPT.

**Comment by bozzmob** [comment]
@yychun1217 Were you able to find a solution? I am stuck with a similar problem on Linux. Need to know what you did to resolve the issue.

**Comment by christopherdro** [comment]
@facebook-github-bot stack-overflow
