### ISSUE TITLE
What is the latest all dependencies for RN 0.70.7 (reanimated , screens ,guesture-handler , safe-area-context , all navigation & firebase )

### ISSUE THREAD

**Issue by harendrasaini01** [facebook/react-native#36473]
### New Version

0.70.7

### Old Version

0.66.4

### Build Target(s)

Android

### Output of `react-native info`

What is the latest all dependencies for RN 0.70.7 (reanimated , screens ,guesture-handler , safe-area-context , all navigation & firebase )

In android, OTA crashes multiple times... please suggest 

{
  "name": "ketchapp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@magicpixel/rn-mp-client-sdk": "^0.8.0",
    "@react-native-async-storage/async-storage": "^1.17.11",
    "@react-native-community/eslint-config": "^3.2.0",
    "@react-native-community/push-notification-ios": "aasatech/push-notification-ios",
    "@react-native-firebase/analytics": "^16.0.0",
    "@react-native-firebase/app": "^16.0.0",
    "@react-native-firebase/crashlytics": "^16.0.0",
    "@react-native-firebase/dynamic-links": "^16.0.0",
    "@react-native-firebase/messaging": "^16.0.0",
    "@react-native-firebase/perf": "^16.0.0",
    "@react-native-masked-view/masked-view": "^0.2.8",
    "@react-navigation/bottom-tabs": "^6.5.4",
    "@react-navigation/drawer": "^6.5.8",
    "@react-navigation/native": "^6.1.3",
    "@react-navigation/native-stack": "^6.9.9",
    "@react-navigation/stack": "^6.3.12",
    "@redux-devtools/extension": "^3.2.5",
    "@shopify/flash-list": "^1.4.1",
    "axios": "^1.3.2",
    "babel-plugin-transform-remove-console": "^6.9.4",
    "babel-preset-react-native": "^4.0.1",
    "moment": "^2.29.4",
    "prettier": "^2.8.3",
    "react": "18.1.0",
    "react-native": "0.70.7",
    "react-native-appsflyer": "^6.9.4",
    "react-native-autoscroll-flatlist": "^1.11.2",
    "react-native-barcode-mask": "^1.2.4",
    "react-native-code-push": "^7.1.0",
    "react-native-device-info": "^10.3.0",
    "react-native-fast-image": "^8.6.3",
    "react-native-fbsdk-next": "^11.1.0",
    "react-native-gesture-handler": "^2.8.0",
    "react-native-global-font": "^1.0.3",
    "react-native-image-base64": "^0.1.4",
    "react-native-image-pan-zoom": "^2.1.12",
    "react-native-image-picker": "^5.0.1",
    "react-native-infy-camera": "^1.0.3",
    "react-native-infy-qrcode-scanner": "^1.0.3",
    "react-native-modal": "^13.0.1",
    "react-native-network-info": "^5.2.1",
    "react-native-paper": "^5.2.0",
    "react-native-permissions": "^3.6.1",
    "react-native-push-notification": "^8.1.1",
    "react-native-ratings": "^8.1.0",
    "react-native-razorpay": "^2.3.0",
    "react-native-reanimated": "2.13.0",
    "react-native-render-html": "^6.3.4",
    "react-native-safe-area-context": "^4.4.1",
    "react-native-screens": "^3.18.2",
    "react-native-snackbar": "^2.4.0",
    "react-native-snapmint3": "^1.0.20",
    "react-native-swiper": "^1.6.0",
    "react-native-text-ticker": "^1.14.0",
    "react-native-toast-message": "^2.1.5",
    "react-native-uuid": "^2.0.1",
    "react-native-vector-icons": "^9.2.0",
    "react-native-version-check": "^3.4.7",
    "react-native-webview": "^11.26.1",
    "react-navigation": "^4.4.4",
    "react-redux": "^8.0.5",
    "redux": "^4.2.0",
    "redux-logger": "^3.0.6",
    "redux-persist": "^6.0.0",
    "redux-thunk": "^2.4.2",
    "sp-react-native-in-app-updates": "^1.3.1"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/preset-env": "^7.14.0",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^3.0.0",
    "@tsconfig/react-native": "^2.0.2",
    "@types/jest": "^29.2.1",
    "@types/react": "^18.0.24",
    "@types/react-native": "^0.71.3",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.2.1",
    "eslint": "^8.19.0",
    "jest": "^29.2.1",
    "metro-react-native-babel-preset": "0.72.3",
    "prettier": "^2.4.1",
    "react-test-renderer": "18.1.0",
    "typescript": "4.8.4"
  },
  "jest": {
    "preset": "react-native"
  },
  "rnpm": {
    "assets": [
      "./assets/fonts/"
    ]
  }
}

### Issue and Reproduction Steps

{
  "name": "ketchapp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@magicpixel/rn-mp-client-sdk": "^0.8.0",
    "@react-native-async-storage/async-storage": "^1.17.11",
    "@react-native-community/eslint-config": "^3.2.0",
    "@react-native-community/push-notification-ios": "aasatech/push-notification-ios",
    "@react-native-firebase/analytics": "^16.0.0",
    "@react-native-firebase/app": "^16.0.0",
    "@react-native-firebase/crashlytics": "^16.0.0",
    "@react-native-firebase/dynamic-links": "^16.0.0",
    "@react-native-firebase/messaging": "^16.0.0",
    "@react-native-firebase/perf": "^16.0.0",
    "@react-native-masked-view/masked-view": "^0.2.8",
    "@react-navigation/bottom-tabs": "^6.5.4",
    "@react-navigation/drawer": "^6.5.8",
    "@react-navigation/native": "^6.1.3",
    "@react-navigation/native-stack": "^6.9.9",
    "@react-navigation/stack": "^6.3.12",
    "@redux-devtools/extension": "^3.2.5",
    "@shopify/flash-list": "^1.4.1",
    "axios": "^1.3.2",
    "babel-plugin-transform-remove-console": "^6.9.4",
    "babel-preset-react-native": "^4.0.1",
    "moment": "^2.29.4",
    "prettier": "^2.8.3",
    "react": "18.1.0",
    "react-native": "0.70.7",
    "react-native-appsflyer": "^6.9.4",
    "react-native-autoscroll-flatlist": "^1.11.2",
    "react-native-barcode-mask": "^1.2.4",
    "react-native-code-push": "^7.1.0",
    "react-native-device-info": "^10.3.0",
    "react-native-fast-image": "^8.6.3",
    "react-native-fbsdk-next": "^11.1.0",
    "react-native-gesture-handler": "^2.8.0",
    "react-native-global-font": "^1.0.3",
    "react-native-image-base64": "^0.1.4",
    "react-native-image-pan-zoom": "^2.1.12",
    "react-native-image-picker": "^5.0.1",
    "react-native-infy-camera": "^1.0.3",
    "react-native-infy-qrcode-scanner": "^1.0.3",
    "react-native-modal": "^13.0.1",
    "react-native-network-info": "^5.2.1",
    "react-native-paper": "^5.2.0",
    "react-native-permissions": "^3.6.1",
    "react-native-push-notification": "^8.1.1",
    "react-native-ratings": "^8.1.0",
    "react-native-razorpay": "^2.3.0",
    "react-native-reanimated": "2.13.0",
    "react-native-render-html": "^6.3.4",
    "react-native-safe-area-context": "^4.4.1",
    "react-native-screens": "^3.18.2",
    "react-native-snackbar": "^2.4.0",
    "react-native-snapmint3": "^1.0.20",
    "react-native-swiper": "^1.6.0",
    "react-native-text-ticker": "^1.14.0",
    "react-native-toast-message": "^2.1.5",
    "react-native-uuid": "^2.0.1",
    "react-native-vector-icons": "^9.2.0",
    "react-native-version-check": "^3.4.7",
    "react-native-webview": "^11.26.1",
    "react-navigation": "^4.4.4",
    "react-redux": "^8.0.5",
    "redux": "^4.2.0",
    "redux-logger": "^3.0.6",
    "redux-persist": "^6.0.0",
    "redux-thunk": "^2.4.2",
    "sp-react-native-in-app-updates": "^1.3.1"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/preset-env": "^7.14.0",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^3.0.0",
    "@tsconfig/react-native": "^2.0.2",
    "@types/jest": "^29.2.1",
    "@types/react": "^18.0.24",
    "@types/react-native": "^0.71.3",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.2.1",
    "eslint": "^8.19.0",
    "jest": "^29.2.1",
    "metro-react-native-babel-preset": "0.72.3",
    "prettier": "^2.4.1",
    "react-test-renderer": "18.1.0",
    "typescript": "4.8.4"
  },
  "jest": {
    "preset": "react-native"
  },
  "rnpm": {
    "assets": [
      "./assets/fonts/"
    ]
  }
}

**Comment by cam-shaw** [comment]
Run `yarn outdated` or equivalent and it should output the latest versions.
