### ISSUE TITLE
Problems to setup a react-native project in m1 cpu in macOS Ventura 13.2.1

### ISSUE THREAD

**Issue by zhouhao27** [facebook/react-native#36482]
### Description

Suddenly have issues to create new RN project and run old RN project. Then I reset my Mac to a fresh system and struggled for a day and failed to solve the issue. There are different types of problems. Here are what I did:

- Install Xcode 14.2 and Command Line tools
- Install brew with command:

`/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`

- Install node

`brew install node@14`

- Install watchman

`brew install watchman`

- Install cocoa pods

`brew install cocoapods`

If I run `npx react-native init App`, got the following error messages:

> ✖ Installing Bundler
error Your Ruby version is 2.6.10, but your Gemfile specified 2.7.6

> ✖ Installing Bundler
error Error: Looks like your iOS environment is not properly set. Please go to https://reactnative.dev/docs/next/environment-setup and follow the React Native CLI QuickStart guide for macOS and iOS.
Error: Error: Looks like your iOS environment is not properly set. Please go to https://reactnative.dev/docs/next/environment-setup and follow the React Native CLI QuickStart guide for macOS and iOS.
    at createFromTemplate (/Volumes/T7/Users/zhouhao/.npm/_npx/31043/lib/node_modules/react-native/node_modules/@react-native-community/cli/build/commands/init/init.js:131:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.initialize [as func] (/Volumes/T7/Users/zhouhao/.npm/_npx/31043/lib/node_modules/react-native/node_modules/@react-native-community/cli/build/commands/init/init.js:184:3)
    at async Command.handleAction (/Volumes/T7/Users/zhouhao/.npm/_npx/31043/lib/node_modules/react-native/node_modules/@react-native-community/cli/build/index.js:106:9)

I don't want to install new ruby (I tried a few times with a lot of other errors, so I gave up). Then I try `npx react-native@0.64.4 init App2 --version 0.64.4`. This time I got this error:

> error Error: Failed to install CocoaPods dependencies for iOS project, which is required by this template.

It turns out the real problem is:

> xcrun: error: SDK "iphoneos" cannot be located

The brew install `Xcode command line tools` in somewhere other than `/Applications/Xcode.app/Contents/Developer`, then I change it back. The `pod install` success.

Then I got the compiling error in Xcode:

<img width="533" alt="Screenshot 2023-03-15 at 10 40 02 PM" src="https://user-images.githubusercontent.com/8099731/225344176-b6c6723e-3830-47c4-97e4-8332cac0ab90.png">

I changed the Podfile based on a suggestion:

```
  post_install do |installer|
    react_native_post_install(installer)
    flipper_post_install(installer)

    # The real directory is /Users/<user>/Library.
    # In case-sensitive file systems the file won't exists.
    unless File.exist? "pods"
      system('cd Pods/Headers/Public; ln -s Protobuf protobuf')
      system('cd Pods/OpenSSL-Universal/Frameworks/OpenSSL.xcframework/ios-arm64_arm64e_armv7_armv7s; ln -sfh OpenSSL.framework openssl.framework')
      system('cd Pods/OpenSSL-Universal/Frameworks/OpenSSL.xcframework/ios-arm64_i386_x86_64-simulator; ln -sfh OpenSSL.framework openssl.framework')
      system('cd Pods/OpenSSL-Universal/Frameworks/OpenSSL.xcframework/ios-arm64_x86_64-maccatalyst; ln -sfh OpenSSL.framework openssl.framework')
      system('cd Pods/OpenSSL-Universal/Frameworks/OpenSSL.xcframework/macos-arm64_arm64e_x86_64; ln -sfh OpenSSL.framework openssl.framework')
    end

  end
```

The error becomes different now.

<img width="571" alt="Screenshot 2023-03-15 at 10 47 46 PM" src="https://user-images.githubusercontent.com/8099731/225346531-53fc3a18-efad-43d9-8257-5740285e7ad7.png">

Then I set the **Excluded Architectures** for simulator to `arm64` and add the following lines in Podfile:

```
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = "arm64"
      end
    end
```

It finally can be compiled. But it crashes. 

<img width="244" alt="Screenshot 2023-03-15 at 10 51 07 PM" src="https://user-images.githubusercontent.com/8099731/225348210-12d21c7d-7d75-47f7-8a7d-e83ff37c8ad4.png">

Really don't know which step is wrong. Please advise if you have any suggestion. Thanks.

### React Native Version

0.64.4

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1
    Memory: 652.83 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.21.3 - /opt/homebrew/bin/node
    Yarn: Not Found
    npm: 6.14.18 - /opt/homebrew/bin/npm
    Watchman: 2023.03.13.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.4 => 0.64.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

I have all my steps in the description section. Please refer to it.

### Snack, code example, screenshot, or link to a repository

It's just a new application. I didn't add any my own code yet.

**Comment by cortinico** [comment]
> error Your Ruby version is 2.6.10, but your Gemfile specified 2.7.6

@zhouhao27 have you looked at this error message? What's your ruby version?

**Comment by zhouhao27** [comment]
My Ruby version is 2.6.10

**Comment by cortinico** [comment]
Then you need to update to 2.7.6

**Comment by zhouhao27** [comment]
I don’t want to upgrade my ruby because it caused a lot of other issues so that I used old RN version. It urns out all the issues are from brew. If I don’t install anything from brew. It’s running fine.

**Comment by cortinico** [comment]
> I don’t want to upgrade my ruby because it caused a lot of other issues so that I used old RN version. It urns out all the issues are from brew. If I don’t install anything from brew. It’s running fine.

Then I'm sorry, I don't know how to help you further.
We're going to relax the ruby requirements in the next versions of React Native (we'll also most likely backport this to 0.71), so you'll be able to use 2.6.x to run your project. This is not possible as of today.
