### ISSUE TITLE
RCTEventEmitter.startObserving is not called when app is refreshed by pressing `r`

### ISSUE THREAD

**Issue by normanzb** [facebook/react-native#36481]
### Description

We have a module that implement RCTEventEmitter and override `startObserving` and `stopObserving`. startObserving is suppose to be called when event handler is attached on js side, it is working on first startup, but when app is refreshed by pressing `r`, the `startObserving` is not called.

### React Native Version

0.70.7

### Output of `npx react-native info`

System:
    OS: macOS 12.6.3
    CPU: (10) arm64 Apple M1 Max
    Memory: 566.72 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 8.19.2 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /Users/xxx/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.13 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.7 => 0.70.7 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

we have a event emitter native module that only emit events when hasListener property is set to true:

```
import Foundation
import React

@objc(GlobalEvent)
class GlobalEvent: RCTEventEmitter {
  private var hasListener = false
  
  override init() {
    super.init()
  }
  
  deinit {
  }
  
  override func startObserving() {
    hasListener = true
    super.startObserving()
  }
  
  override func stopObserving() {
    hasListener = false
    super.stopObserving()
  }
  
  open override func supportedEvents() -> [String] {
    ["onEvent"]
  }
  
  @objc func handleEvent() {
    if !hasListener {
      return
    }
    self.sendEvent(withName: "onEvent", body: [])
  }
}
```

It is working on the first startup,however when we refresh the app by using `r`, `stopObserving` was called but `startObserving` wasn't.

the js code always attach events when app starting up:
```
GlobalEvent.addListener('onEvent', () => {
      console.log('native onEvent called');
    });
```

### Snack, code example, screenshot, or link to a repository

code example provided in description

**Comment by kirito47-cn** [comment]
same issue.

**Comment by kirito47-cn** [comment]
> same issue.

my react-native version is 0.66.4

**Comment by LichKing-2234** [comment]
same on 0.71.4

**Comment by LichKing-2234** [comment]
> same on 0.71.4

I found it causes by making your module a singleton instance.

**Comment by CaptainJeff** [comment]
> > same on 0.71.4
> 
> I found it causes by making your module a singleton instance.

@LichKing-2234  Can you explain that a little more? How can we prevent this from happening?

**Comment by LichKing-2234** [comment]
> > > same on 0.71.4
> > 
> > 
> > I found it causes by making your module a singleton instance.
> 
> @LichKing-2234 Can you explain that a little more? How can we prevent this from happening?

If make module singleton instance, will cause this issue.
<img width="664" alt="image" src="https://github.com/facebook/react-native/assets/9312526/bdb671c5-3a81-4cb8-86d8-e6ec9fadacf1">

but you can make some different
<img width="676" alt="image" src="https://github.com/facebook/react-native/assets/9312526/aed9a196-25e0-4093-b873-0babb4dc875e">

**Comment by CaptainJeff** [comment]
@LichKing-2234 understood! Thanks for the explanation. Appreciate it
