### ISSUE TITLE
[iOS] change keyboard color theme?

### ISSUE THREAD

**Issue by seph14** [facebook/react-native#3649]
We are refactoring our iOS app with react-native. 
There is a screen where the background is all white and we need a numeric keyboard in dark theme - to separate the keyboard with the background.

I did't find anywhere in the doc or existing parts that allow me to do this, could anyone point me the files that are responsible for this so that I could take a look in?

**Comment by christopherdro** [comment]
@seph14 Just added a PR to for this. It might take some time to get this merged but you can cherry pick this commit if you need this feature immediately.

**Comment by ide** [comment]
Thanks @christopherdro. Looks like your PR is merged into master.

**Comment by christopherdro** [comment]
:+1:
