### ISSUE TITLE
PermissionsAndroid POST_NOTIFICATIONS always return denied

### ISSUE THREAD

**Issue by hotaryuzaki** [facebook/react-native#36499]
### Description

i just followed the code from [here](https://reactnative.dev/docs/permissionsandroid) to request PermissionsAndroid.
but any button i press always returns denied.
NOTE: i'm using android 13 emulator

```
  const requestPostNotification = async () => {
    try {
      const granted = await PermissionsAndroid.request(
        PermissionsAndroid.PERMISSIONS.POST_NOTIFICATIONS,
        {
          title: 'Cool Photo App Camera Permission',
          message:
            'Cool Photo App needs access to your camera ' +
            'so you can take awesome pictures.',
          buttonNeutral: 'Ask Me Later',
          buttonNegative: 'Cancel',
          buttonPositive: 'OK',
        },
      );

      console.log('granted =============', granted);

      if (granted === PermissionsAndroid.RESULTS.GRANTED) {
        console.log('You can use the camera');
      } else {
        console.log('Camera permission denied');
      }
    } catch (err) {
      console.warn(err);
    }
  };
```

### React Native Version

0.70.7

### Output of `npx react-native info`

System:
    OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
    Memory: 1.21 GB / 15.55 GB
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.13.2/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
    Watchman: 20220123.190932.0 - /usr/local/bin/watchman
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 11.0.18 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: ^0.70.7 => 0.70.7 
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

copy the code from [here](https://reactnative.dev/docs/permissionsandroid)

### Snack, code example, screenshot, or link to a repository

no

**Comment by dharma-tv** [comment]
I am also facing same issue. Did you get solution ?

**Comment by dharma-tv** [comment]
Found the root cause of my - issue was with the Emulator API version. 

**You need to use Emulator with API 33 version.** 

It is working for me now. Hope it helps you.

**Comment by hotaryuzaki** [comment]
> I am also facing same issue. Did you get solution ?

As I said before I used android 13 emulator

I solved it with change the code to this 
``` 
await PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.POST_NOTIFICATIONS);
``` 

There is an issue though if we choose "allow" it returns "never ask again", but notification permission succeeds.
So I check again the permission after that to make sure.
