### ISSUE TITLE
After update from version 0.70.5 to 0.71.4 there was an error:   Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by valery-lavrik** [facebook/react-native#36492]
### Description

I am getting an error after updating react-native from version **0.70.5 to 0.71.4**. Previously (before the update) this error was not.

_And it happens when debug mode is enabled._

After a long search, I found that the error appears with the line:
```
import { createDrawerNavigator } from '@react-navigation/drawer';
...
const Drawer = createDrawerNavigator();
```

I understand what needs to be written in react-navigation (and I already wrote - [there](https://github.com/react-navigation/react-navigation/issues/11284)), but I have a feeling that the error is not related to them, but to react-native

Any ideas why this happened?

This issue is discussed at
https://stackoverflow.com/questions/74859163/typeerror-cannot-read-property-createdrawernavigator-of-undefined/75753538#75753538
but no solution yet

Here is the screenshot of the error:
![image](https://user-images.githubusercontent.com/8047999/225561708-a6416290-240a-4f32-81a7-e0f066c8c3c1.png)

### React Native Version

0.71.4

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.22000
    CPU: (4) x64 Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
    Memory: 1.11 GB / 7.92 GB
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.15 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: AI-212.5712.43.2112.8609683
    Visual Studio: Not Found
  Languages:
    Java: 11.0.18 - /c/Program Files/Microsoft/jdk-11.0.18.10-hotspot/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.4 => 0.71.4
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Install the Drawer Navigator according to their instructions
https://reactnavigation.org/docs/drawer-navigator#installation

try code:
```
import { createDrawerNavigator } from '@react-navigation/drawer';
...
const Drawer = createDrawerNavigator();
```

### Snack, code example, screenshot, or link to a repository

Unfortunately, I can't choose the option yet.

**Comment by fachrighiffary** [comment]
I just installed React Native version 0.71.4
but for ios it can't be run
only on android

have you experienced it?

**Comment by valery-lavrik** [comment]
> I just installed React Native version 0.71.4 but for ios it can't be run only on android
> 
> have you experienced it?

what mistake?

**Comment by ldiasm** [comment]
Same problem here:

![image](https://github.com/facebook/react-native/assets/4728408/5c517b51-9027-44d1-81fa-b1a67861ce7d)


```
System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 688.16 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v18.15.0/bin/npm
    Watchman: 2023.05.08.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/ldpm/.gem/ruby/2.6.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 21, 23, 28, 29, 30, 31, 32, 33, 33
      Build Tools: 30.0.2, 30.0.3, 31.0.0, 33.0.0, 33.0.1
      System Images: android-21 | Google APIs ARM 64 v8a, android-22 | Google APIs ARM 64 v8a, android-31 | Google Play ARM 64 v8a, android-33 | Google Play ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9477386
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.1 => 0.69.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Plus: Since the app keep showing errors after reloading or reinstalling we are unable to deactivate Debug With Chrome options because the dev menu can't be showed. Only way is using reacttotron too.
