### ISSUE TITLE
Build Failed while running: npx react-native run-ios --simulator='iPhone 14 Pro Max'

### ISSUE THREAD

**Issue by belarbi104** [facebook/react-native#36506]
### Description

Hello,
this is the error I receive:

** BUILD FAILED **

The following build commands failed:
        CompileC /Users/karimbelarbi/Library/Developer/Xcode/DerivedData/LUX-ftoquogruetxvsabynhgbejyamvj/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-logger.build/Objects-normal/x86_64/react_native_log.o /Users/karimbelarbi/Desktop/lux-app-4a2685acb9e123bad56c76850eb007fcec49211b/node_modules/react-native/ReactCommon/logger/react_native_log.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'React-logger' from project 'Pods')
(1 failure)

info Run CLI with --verbose flag for more details.

I would be really thankful for the help.

### React Native Version

0.69.6

### Output of `npx react-native info`

System:
    OS: macOS 12.6.3
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 47.45 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.15.0 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.5.5 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.12.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.6 => 0.69.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

npx react-native run-ios --simulator='iPhone 14 Pro Max'

### Snack, code example, screenshot, or link to a repository

Package.json

{
  "name": "lux",
  "version": "1.0.0",
  "scripts": {
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@emailjs/browser": "^3.7.0",
    "@react-google-maps/api": "^2.17.0",
    "@react-native-community/netinfo": "^9.3.7",
    "@react-native-firebase/app": "~15.4.0",
    "@react-native-picker/picker": "^2.4.8",
    "@react-navigation/bottom-tabs": "^6.4.0",
    "@react-navigation/native": "^6.0.13",
    "@react-navigation/stack": "^6.3.1",
    "@stripe/react-stripe-js": "^1.14.2",
    "@stripe/stripe-react-native": "^0.2.3",
    "axios": "^0.27.2",
    "expo": "~46.0.13",
    "expo-build-properties": "~0.3.0",
    "expo-firebase-analytics": "~7.2.0",
    "expo-font": "~10.2.0",
    "expo-linear-gradient": "~11.4.0",
    "expo-splash-screen": "~0.16.2",
    "expo-status-bar": "~1.4.0",
    "expo-updates": "~0.14.6",
    "firebase": "^9.6.11",
    "react": "18.0.0",
    "react-dom": "18.0.0",
    "react-native": "0.69.6",
    "react-native-calendar-range-picker": "^1.5.3",
    "react-native-geocoding": "^0.5.0",
    "react-native-maps": "^1.3.2",
    "react-native-maps-directions": "^1.9.0",
    "react-native-paper": "^4.12.5",
    "react-native-paper-dates": "^0.9.2",
    "react-native-phone-number-input": "^2.1.0",
    "react-native-responsive-fontsize": "^0.5.1"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9"
  },
  "private": true
}

**Comment by cipolleschi** [comment]
Hi @belarbi104, thank for opening the issue. However, I tried the following instructions:
```
npx react-native init MyApp --version 0.69.6
cd MyApp
npx react-native run-ios --simulator='iPhone 14 Pro Max'  
```
and it worked fine.

I think you have something in your dependencies that prevents your app to build properly. 
The first thing you can do is to prepare a repro we can use to reproduce the problem

Secondly, I suggest you to start a new project and pregressively add your dependencies one-by-one to see which one break the build and then open an issue in that repo.

**Comment by belarbi104** [comment]
One time I had a more detailed console error and it was the React Native Logger which prevented it. Furthermore I don't know how to solve it because I am not able to uninstall the React Native Logger.

**Comment by cipolleschi** [comment]
How did you create the project?
From what I can see, you also have some dependencies from Expo.

As shown above, react native is creating a proper project. It is probably a problem due to some incompatible dependency, or a problem due to Expo.

If you created the project using `npx react-native init` my suggestion is to create a new project and start adding one dep at a time to see which one is creating the problem.

**Comment by belarbi104** [comment]
That worked for me thank you.
