### ISSUE TITLE
Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication().

### ISSUE THREAD

**Issue by IzusaE** [facebook/react-native#36509]
### Description

Hi, just after adding a new package, a get a big error, and I can't start my application (it block on slapsh screen picture)

 ERROR  [Reanimated] Couldn't determine the version of the native part of Reanimated. Did you forget to re-build the app after upgrading react-native-reanimated? If you use Expo Go, you must use the exact version which is bundled into Expo SDK.
 ERROR  Error: Requiring module "node_modules/react-native-reanimated/src/index.ts", which threw an exception: TypeError: this.InnerNativeModule.makeShareableClone is not a function. (In 'this.InnerNativeModule.makeShareableClone(value, shouldPersistRemote)', 'this.InnerNativeModule.makeShareableClone' is undefined)
 ERROR  Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
 ERROR  Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.

I don't understand the problem and I ignore how to solve it...

### React Native Version

0.70.5

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: Linux 5.15 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
    Memory: 2.93 GB / 7.65 GB
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.14.2 - ~/.nvm/versions/node/v18.14.2/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.14.2/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.5 => 0.70.5 
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

I do this line of command to add a package : 
yarn add react-native-reanimated react-native-safe-area-context
And after nothing works again, I can't load my app on expo

### Snack, code example, screenshot, or link to a repository

This is my package.json : 

`{
  "name": "testApp",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@emotion/react": "^11.10.6",
    "@emotion/styled": "^11.10.6",
    "@fortawesome/fontawesome-free-solid": "^5.0.13",
    "@fortawesome/fontawesome-svg-core": "^6.3.0",
    "@fortawesome/free-brands-svg-icons": "^6.3.0",
    "@fortawesome/free-regular-svg-icons": "^6.3.0",
    "@fortawesome/free-solid-svg-icons": "^6.3.0",
    "@fortawesome/react-fontawesome": "^0.2.0",
    "@fortawesome/react-native-fontawesome": "^0.3.0",
    "@mui/material": "^5.11.12",
    "@react-native-async-storage/async-storage": "^1.17.11",
    "@react-native-community/datetimepicker": "6.5.2",
    "@react-navigation/bottom-tabs": "^6.5.4",
    "@react-navigation/native": "^6.1.3",
    "@react-navigation/stack": "^6.3.12",
    "@shopify/flash-list": "1.3.1",
    "axios": "^1.3.4",
    "eas-cli": "^0.60.0",
    "expo": "~47.0.12",
    "expo-linear-gradient": "^12.0.1",
    "expo-status-bar": "~1.4.2",
    "react": "18.1.0",
    "react-dom": "18.1.0",
    "react-native": "0.70.5",
    "react-native-animated-dots-carousel": "^1.0.2",
    "react-native-animated-pagination-dot": "^0.4.0",
    "react-native-encrypted-storage": "^4.0.3",
    "react-native-gesture-handler": "~2.8.0",
    "react-native-map-clustering": "^3.4.2",
    "react-native-maps": "^1.3.2",
    "react-native-reanimated": "^3.0.1",
    "react-native-reanimated-carousel": "^3.3.0",
    "react-native-safe-area-context": "^4.5.0",
    "react-native-screens": "~3.18.0",
    "react-native-snap-carousel": "^3.9.1",
    "react-native-svg": "13.4.0",
    "react-native-ui-lib": "^6.31.0",
    "react-native-vector-icons": "^9.2.0",
    "react-native-web": "~0.18.9"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@types/lodash": "^4.14.191",
    "@types/react": "~18.0.14",
    "@types/react-native": "~0.70.6",
    "@types/react-native-snap-carousel": "^3.8.5",
    "@types/react-native-vector-icons": "^6.4.13",
    "typescript": "^4.6.3"
  },
  "private": true
}
`

**Comment by cortinico** [comment]
> ERROR [Reanimated] Couldn't determine the version of the native part of Reanimated

Hi,
Thanks for reporting this issue.

It seems like this issue is actually unrelated to React Native core but related to Reanimated. Please open this issue against this other repository:

https://github.com/software-mansion/react-native-reanimated/issues

I'll be closing this but feel free to reopen if the other repo points back to us as a issue in the core of React Native.
