### ISSUE TITLE
I upgraded my ruby version but it still doesn't work 

### ISSUE THREAD

**Issue by egecanyldrm** [facebook/react-native#36518]
### Description

hey guys ı got issue when install new react-native cli version about my ruby version then i removed watchman and ruby packages from my brew and reinstall now my ruby version is ruby 2.7.6p219 (2022-04-12 revision c9c2245c0a) [arm64-darwin22] everything it's okey when init any project but now i get issue when open my project on ios simulator my error like below 

### React Native Version

0.71.4

### Output of `npx react-native info`

RVM used your Gemfile for selecting Ruby, it is all fine - Heroku does that too,
you can ignore these warnings with 'rvm rvmrc warning ignore /Users/egecanmac/Desktop/Documents/React Native Documents/demo/Gemfile'.
To ignore the warning for all files run 'rvm rvmrc warning ignore allGemfiles'.

Unknown ruby interpreter version (do not know how to handle): File.readFile.join__dir__,.ruby-version.strip.
egecanmac@egecan-mbp demo % npx react-native info
info Fetching system and libraries information...
System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1
    Memory: 124.73 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.13.0/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.13.0/bin/npm
    Watchman: 2023.03.13.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /Users/egecanmac/.rvm/gems/ruby-2.7.6/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.4 => 0.71.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
egecanmac@egecan-mbp demo % 

### Steps to reproduce

RVM used your Gemfile for selecting Ruby, it is all fine - Heroku does that too,
you can ignore these warnings with 'rvm rvmrc warning ignore /Users/egecanmac/Desktop/Documents/React Native Documents/demo/Gemfile'.
To ignore the warning for all files run 'rvm rvmrc warning ignore allGemfiles'.

Unknown ruby interpreter version (do not know how to handle): File.readFile.join__dir__,.ruby-version.strip.
egecanmac@egecan-mbp demo % yarn start
yarn run v1.22.19
warning ../../../../package.json: No license field
$ react-native start

                        ▒▒▓▓▓▓▒▒
                     ▒▓▓▓▒▒░░▒▒▓▓▓▒
                  ▒▓▓▓▓░░░▒▒▒▒░░░▓▓▓▓▒
                 ▓▓▒▒▒▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▓▓
                 ▓▓░░░░░▒▓▓▓▓▓▓▒░░░░░▓▓
                 ▓▓░░▓▓▒░░░▒▒░░░▒▓▒░░▓▓
                 ▓▓░░▓▓▓▓▓▒▒▒▒▓▓▓▓▒░░▓▓
                 ▓▓░░▓▓▓▓▓▓▓▓▓▓▓▓▓▒░░▓▓
                 ▓▓▒░░▒▒▓▓▓▓▓▓▓▓▒░░░▒▓▓
                  ▒▓▓▓▒░░░▒▓▓▒░░░▒▓▓▓▒
                     ▒▓▓▓▒░░░░▒▓▓▓▒
                        ▒▒▓▓▓▓▒▒

                Welcome to Metro v0.73.8
              Fast - Scalable - Integrated

r - reload the app
d - open developer menu
i - run on iOS
a - run on Android

warning: Watchman `watch-project` returned a warning: Recrawled this watch 1 times, most recently because:
MustScanSubDirs UserDroppedTo resolve, please review the information on
https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
To clear this warning, run:
`watchman watch-del '/Users/egecanmac/Desktop/Documents/React Native Documents/demo' ; watchman watch-project '/Users/egecanmac/Desktop/Documents/React Native Documents/demo'`

warning: Watchman `query` returned a warning: Recrawled this watch 1 times, most recently because:
MustScanSubDirs UserDroppedTo resolve, please review the information on
https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
To clear this warning, run:
`watchman watch-del '/Users/egecanmac/Desktop/Documents/React Native Documents/demo' ; watchman watch-project '/Users/egecanmac/Desktop/Documents/React Native Documents/demo'`

Recrawled this watch 1 times, most recently because:
MustScanSubDirs UserDroppedTo resolve, please review the information on
https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
To clear this warning, run:
`watchman watch-del '/Users/egecanmac/Desktop/Documents/React Native Documents/demo' ; watchman watch-project '/Users/egecanmac/Desktop/Documents/React Native Documents/demo'`

info Opening the app on iOS...
info Found Xcode workspace "demo.xcworkspace"
info Found booted iPhone 14 Plus
info Launching iPhone 14 Plus
info Building (using "xcodebuild -workspace demo.xcworkspace -configuration Debug -scheme demo -destination id=F66635AB-2918-4A57-9C8C-EC2C29401927")
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -workspace demo.xcworkspace -configuration Debug -scheme demo -destination id=F66635AB-2918-4A57-9C8C-EC2C29401927

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES

Prepare packages

Computing target dependency graph and provisioning inputs

Create build description
Build description signature: cd5bd5ab189fd9cdbd95134ade41df00
Build description path: /Users/egecanmac/Library/Developer/Xcode/DerivedData/demo-bdabeyxesqofeeaadnqykvqzehbb/Build/Intermediates.noindex/XCBuildData/cd5bd5ab189fd9cdbd95134ade41df00-desc.xcbuild

note: Building targets in dependency order
PhaseScriptExecution [CP-User]\ Generate\ Specs /Users/egecanmac/Library/Developer/Xcode/DerivedData/demo-bdabeyxesqofeeaadnqykvqzehbb/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FBReactNativeSpec.build/Script-46EB2E00018F30.sh (in target 'FBReactNativeSpec' from project 'Pods')
    cd /Users/egecanmac/Desktop/Documents/React\ Native\ Documents/demo/ios/Pods
    export ACTION\=build
    export AD_HOC_CODE_SIGNING_ALLOWED\=YES
    export ALLOW_TARGET_PLATFORM_SPECIALIZATION\=NO
    export ALTERNATE_GROUP\=staff
    export ALTERNATE_MODE\=u+w,go-w,a+rX
    export ALTERNATE_OWNER\=egecanmac
    export ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES\=NO
    export ALWAYS_SEARCH_USER_PATHS\=NO
    export ALWAYS_USE_SEPARATE_HEADERMAPS\=NO
    export APPLE_INTERNAL_DEVELOPER_DIR\=/AppleInternal/Developer
    export APPLE_INTERNAL_DIR\=/AppleInternal
    export APPLE_INTERNAL_DOCUMENTATION_DIR\=/AppleInternal/Documentation
    export APPLE_INTERNAL_LIBRARY_DIR\=/AppleInternal/Library
    export APPLE_INTERNAL_TOOLS\=/AppleInternal/Developer/Tools
    export APPLICATION_EXTENSION_API_ONLY\=NO
    export APPLY_RULES_IN_COPY_FILES\=NO
    export APPLY_RULES_IN_COPY_HEADERS\=NO
    export ARCHS\=arm64
    export ARCHS_STANDARD\=arm64\ x86_64
    export ARCHS_STANDARD_32_64_BIT\=arm64\ i386\ x86_64
    export ARCHS_STANDARD_32_BIT\=i386
    export ARCHS_STANDARD_64_BIT\=arm64\ x86_64
    export ARCHS_STANDARD_INCLUDING_64_BIT\=arm64\ x86_64
    export ARCHS_UNIVERSAL_IPHONE_OS\=arm64\ i386\ x86_64
    export ASSETCATALOG_COMPILER_APPICON_NAME\=AppIcon
    export ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME\=AccentColor
    export ASSETCATALOG_FILTER_FOR_DEVICE_MODEL\=iPhone14,8
    export ASSETCATALOG_FILTER_FOR_DEVICE_OS_VERSION\=16.2
    export ASSETCATALOG_FILTER_FOR_THINNING_DEVICE_CONFIGURATION\=iPhone14,8
    export AVAILABLE_PLATFORMS\=appletvos\ appletvsimulator\ driverkit\ iphoneos\ iphonesimulator\ macosx\ watchos\ watchsimulator
    export BITCODE_GENERATION_MODE\=marker
    export BUILD_ACTIVE_RESOURCES_ONLY\=YES
    export BUILD_COMPONENTS\=headers\ build
    export BUILD_DIR\=/Users/egecanmac/Library/Developer/Xcode/DerivedData/demo-bdabeyxesqofeeaadnqykvqzehbb/Build/Products
    export BUILD_LIBRARY_FOR_DISTRIBUTION\=NO
    export BUILD_ROOT\=/Users/egecanmac/Library/Developer/Xcode/DerivedData/demo-bdabeyxesqofeeaadnqykvqzehbb/Build/Products
    export BUILD_STYLE\=
    export BUILD_VARIANTS\=normal
    export BUILT_PRODUCTS_DIR\=/Users/egecanmac/Library/Developer/Xcode/DerivedData/demo-bdabeyxesqofeeaadnqykvqzehbb/Build/Products/Debug-iphonesimulator/FBReactNativeSpec
    export BUNDLE_CONTENTS_FOLDER_PATH_deep\=Contents/
    export BUNDLE_EXECUTABLE_FOLDER_NAME_deep\=MacOS
    export BUNDLE_EXTENSIONS_FOLDER_PATH\=Extensions
    export BUNDLE_FORMAT\=shallow
    export BUNDLE_FRAMEWORKS_FOLDER_PATH\=Frameworks
    export BUNDLE_PLUGINS_FOLDER_PATH\=PlugIns
    export BUNDLE_PRIVATE_HEADERS_FOLDER_PATH\=PrivateHeaders
    export BUNDLE_PUBLIC_HEADERS_FOLDER_PATH\=Headers
    export CACHE_ROOT\=/var/folders/92/wd03f3xs06g7ykt_fsv3yq9h0000gn/C/com.apple.DeveloperTools/14.2-14C18/Xcode
    export CCHROOT\=/var/folders/92/wd03f3xs06g7ykt_fsv3yq9h0000gn/C/com.apple.DeveloperTools/14.2-14C18/Xcode
    export CHMOD\=/bin/chmod
    export CHOWN\=/usr/sbin/chown
    export CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED\=YES
    export CLANG_ANALYZER_NONNULL\=YES
    export CLANG_ANALYZER_NUMBER_OBJECT_CONVERSION\=YES_AGGRESSIVE
    export CLANG_CXX_LANGUAGE_STANDARD\=c++17
    export CLANG_CXX_LIBRARY\=libc++
    export CLANG_ENABLE_MODULES\=YES
    export CLANG_ENABLE_OBJC_ARC\=YES
    export CLANG_ENABLE_OBJC_WEAK\=NO
    export CLANG_MODULES_BUILD_SESSION_FILE\=/Users/egecanmac/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation
    export CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING\=YES
    export CLANG_WARN_BOOL_CONVERSION\=YES
    export CLANG_WARN_COMMA\=YES
    export CLANG_WARN_CONSTANT_CONVERSION\=YES
    export CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS\=YES
    export CLANG_WARN_DIRECT_OBJC_ISA_USAGE\=YES_ERROR
    export CLANG_WARN_DOCUMENTATION_COMMENTS\=YES
    export CLANG_WARN_EMPTY_BODY\=YES
    export CLANG_WARN_ENUM_CONVERSION\=YES
    export CLANG_WARN_INFINITE_RECURSION\=YES
    export CLANG_WARN_INT_CONVERSION\=YES
    export CLANG_WARN_NON_LITERAL_NULL_CONVERSION\=YES
    export CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF\=YES
    export CLANG_WARN_OBJC_LITERAL_CONVERSION\=YES
    export CLANG_WARN_OBJC_ROOT_CLASS\=YES_ERROR
    export CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER\=NO
    export CLANG_WARN_RANGE_LOOP_ANALYSIS\=YES
    export CLANG_WARN_STRICT_PROTOTYPES\=YES
    export CLANG_WARN_SUSPICIOUS_MOVE\=YES
    export CLANG_WARN_UNGUARDED_AVAILABILITY\=YES_AGGRESSIVE
    export CLANG_WARN_UNREACHABLE_CODE\=YES
    export CLANG_WARN__DUPLICATE_METHOD_MATCH\=YES
    export CLASS_FILE_DIR\=/Users/egecanmac/Library/Developer/Xcode/DerivedData/demo-bdabeyxesqofeeaadnqykvqzehbb/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FBReactNativeSpec.build/JavaClasses
    export CLEAN_PRECOMPS\=YES
    export CLONE_HEADERS\=NO
    export CODESIGNING_FOLDER_PATH\=/Users/egecanmac/Library/Developer/Xcode/DerivedData/demo-bdabeyxesqofeeaadnqykvqzehbb/Build/Products/Debug-iphonesimulator/FBReactNativeSpec/
    export CODE_SIGNING_ALLOWED\=NO
    export CODE_SIGNING_REQUIRED\=YES
    export CODE_SIGN_CONTEXT_CLASS\=XCiPhoneSimulatorCodeSignContext
    export CODE_SIGN_IDENTITY\=-
    export CODE_SIGN_INJECT_BASE_ENTITLEMENTS\=YES
    export COLOR_DIAGNOSTICS\=NO
    export COMBINE_HIDPI_IMAGES\=NO
    export COMPILER_INDEX_STORE_ENABLE\=Default
    export COMPOSITE_SDK_DIRS\=/Users/egecanmac/Library/Developer/Xcode/DerivedData/demo-bdabeyxesqofeeaadnqykvqzehbb/Build/Intermediates.noindex/CompositeSDKs
    export COMPRESS_PNG_FILES\=YES
    export CONFIGURATION\=Debug
    export CONFIGURATION_BUILD_DIR\=/Users/egecanmac/Library/Developer/Xcode/DerivedData/demo-bdabeyxesqofeeaadnqykvqzehbb/Build/Products/Debug-iphonesimulator/FBReactNativeSpec
    export CONFIGURATION_TEMP_DIR\=/Users/egecanmac/Library/Developer/Xcode/DerivedData/demo-bdabeyxesqofeeaadnqykvqzehbb/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator
    export COPYING_PRESERVES_HFS_DATA\=NO
    export COPY_HEADERS_RUN_UNIFDEF\=NO
    export COPY_PHASE_STRIP\=NO
    export COPY_RESOURCES_FROM_STATIC_FRAMEWORKS\=YES
    export CORRESPONDING_DEVICE_PLATFORM_DIR\=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform
    export CORRESPONDING_DEVICE_PLATFORM_NAME\=iphoneos
    export CORRESPONDING_DEVICE_SDK_DIR\=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk
    export CORRESPONDING_DEVICE_SDK_NAME\=iphoneos16.2
    export CP\=/bin/cp
    export CREATE_INFOPLIST_SECTION_IN_BINARY\=NO
    export CURRENT_ARCH\=undefined_arch
    export CURRENT_VARIANT\=normal
    export DEAD_CODE_STRIPPING\=YES
    export DEBUGGING_SYMBOLS\=YES
    export DEBUG_INFORMATION_FORMAT\=dwarf
    export DEFAULT_COMPILER\=com.apple.compilers.llvm.clang.1_0
    export DEFAULT_DEXT_INSTALL_PATH\=/System/Library/DriverExtensions
    export DEFAULT_KEXT_INSTALL_PATH\=/System/Library/Extensions
    export DEFINES_MODULE\=NO
    export DEPLOYMENT_LOCATION\=NO
    export DEPLOYMENT_POSTPROCESSING\=NO
    export DEPLOYMENT_TARGET_SETTING_NAME\=IPHONEOS_DEPLOYMENT_TARGET
    export DEPLOYMENT_TARGET_SUGGESTED_VALU

### Snack, code example, screenshot, or link to a repository

idont have

**Comment by iBotPeaches** [comment]
You removed ruby from brew and installed RVM?

Either way - the error looks pretty self explanatory. You are somehow on a version of RN that removed a line that an error message says you have. See this commit for details and double check your Gemfile

https://github.com/facebook/react-native/commit/1d22e291462ac452f2bb6b1b6af11986944ec54a

**Comment by PanArnaud** [comment]
Same problem here :(

**Comment by blakef** [comment]
What's the output from [Step 2](https://reactnative.dev/docs/environment-setup?guide=native&platform=ios&os=macos#step-2-start-your-application) `yarn run ios`?

**Comment by egecanyldrm** [comment]
> You removed ruby from brew and installed RVM?
> 
> Either way - the error looks pretty self explanatory. You are somehow on a version of RN that removed a line that an error message says you have. See this commit for details and double check your Gemfile
> 
> [1d22e29](https://github.com/facebook/react-native/commit/1d22e291462ac452f2bb6b1b6af11986944ec54a)

yeah i just remove ruby from homebrew also i have rvm already but stil getting error like that

**Comment by egecanyldrm** [comment]
i wanna ask that am i need to any ruby managers for react native cli ? i removed ruby from homebrew and install rvm stil doesn't work after than i removed rvm and ran the command ruby --version it give me output at below i don't have any ruby package manager  : 
~ % ruby --version
ruby 2.6.10p210 (2022-04-12 revision 67958) [universal.arm64e-darwin22]
