### ISSUE TITLE
Android build issue with Expo - java.lang.ClassNotFoundException: Didn't find class "com.myapp.MainApplication" on path: DexPathLis

### ISSUE THREAD

**Issue by IgorRomanvsky** [facebook/react-native#36519]
### Description

Im facing issue durning and after building a fresh project with Expo v 48.0.6 and react native 0.71.3.
I've created a repo that contains the project and the output android build folder.

### React Native Version

0.71.3

### Output of `npx react-native info`

```
info Fetching system and libraries information...
System:
    OS: macOS 13.0.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 37.08 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.21.1 - ~/.nvm/versions/node/v14.21.1/bin/node
    Yarn: Not Found
    npm: 6.14.17 - ~/.nvm/versions/node/v14.21.1/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9619390
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.5 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.3 => 0.71.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
info React Native v0.71.4 is now available (your project is running on v0.71.3).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.71.4
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.71.3
info For more info, check out "https://reactnative.dev/docs/upgrading".
```

### Steps to reproduce

**Create a new typescript project with:**

`npx create-expo-app -t expo-template-blank-typescript`

**Add the packages details in `app.json`**

```
{
  "expo": {
    "name": "my-app",
    "slug": "my-app",
    "version": "1.0.0",
    "scheme": "com.company.myapp",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "userInterfaceStyle": "light",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true,
      "bundleIdentifier": "com.company.myapp"
    },
    "android": {
      "package": "com.company.myapp",
      "adaptiveIcon": {
        "foregroundImage": "./assets/adaptive-icon.png",
        "backgroundColor": "#ffffff"
      }
    },
    "web": {
      "favicon": "./assets/favicon.png"
    }
  }
}
```

**Pre building the project:**

`npx expo prebuild`

<br>

**First error durning  the build:**

![Screenshot 2023-03-18 at 11 37 35](https://user-images.githubusercontent.com/41449840/226101340-f6664969-e439-433a-b31a-9867a8ff3229.png)

solved by creating `local.properties`  file and add this line:

`sdk.dir = /Users/myname/Library/Android/sdk`

<br>

**Second error during the build**

![Screenshot 2023-03-18 at 11 39 12](https://user-images.githubusercontent.com/41449840/226101460-244e2151-9f48-4939-a6bf-32a7dcf811ee.png)

Solved my adding those imports to the `MainActivity` class

```
import com.myapp.BuildConfig;
import com.myapp.R; 
```

<br>

**Third error during the build**

![Screenshot 2023-03-18 at 11 41 08](https://user-images.githubusercontent.com/41449840/226101550-fb2b12a5-b037-43b3-87f9-ff980bfc864a.png)

Solved by adding the same imports into `MainApplication`

After the project is finally was built, the app crushes right on start with this error:

` java.lang.RuntimeException: Unable to instantiate application com.myapp.MainApplication package com.company.myapp: java.lang.ClassNotFoundException: Didn't find class "com.myapp.MainApplication" on path: DexPathList[[zip file "/data/app/~~KfhNSPp_-WalUe43r5gRKQ==/com.company.myapp-h5cScg5X5ccRLzTtnPbe6A==/base.apk"],nativeLibraryDirectories=[/data/app/~~KfhNSPp_-WalUe43r5gRKQ==/com.company.myapp-h5cScg5X5ccRLzTtnPbe6A==/lib/arm64, /data/app/~~KfhNSPp_-WalUe43r5gRKQ==/com.company.myapp-h5cScg5X5ccRLzTtnPbe6A==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]`

![Screenshot 2023-03-18 at 11 45 04](https://user-images.githubusercontent.com/41449840/226101633-30197d60-e451-456c-9a94-76c666af3978.png)

Tried to do clean => rebuild using Android studio, but nothing worked 

### Snack, code example, screenshot, or link to a repository

https://github.com/IgorRomanvsky/expo-android-build

**Comment by IgorRomanvsky** [comment]
Problem solve after installing the lates expo CLI **and** running:

npx expo prebuild 
npx expo run:android 

**And not:**

expo prebuild 
expo run:android

**Comment by pcsaunak** [comment]
I tried following the above approach but it did not help. 
Additionally, I found that running `npx expo prebuild` - removes the build directory and after that, I get an error mentioning that the package does not exist. Please refer to the screenshot

![image](https://github.com/facebook/react-native/assets/23631671/c017f169-0193-475e-980d-7edefce6bba6)

Additionally I did a bit more digging to see when it exactly arises - 
IF I create a default expo app, and run it it works perfectly fine. 
Now when I try to eject it and try to run it after that it starts failing and throwing all the errors mentioned above. 

Seems there is a bug in the `expo eject` command

**Comment by pcsaunak** [comment]
Kindly reopen the issue

**Comment by Shahbaz898414** [comment]
@IgorRomanvsky 
Hi, i got same error in react native CLI, can this work on CLI?

**Comment by Shahbaz898414** [comment]
any one can you to solve this problem on react native cli? plz , i am working on my company project, while trying to build the features.

@cortinico @pcsaunak @IgorRomanvsky @mojodna

**Comment by carloscurcino** [comment]
Have you solved this??
