### ISSUE TITLE
When using Linking with sms on ios it fail 

### ISSUE THREAD

**Issue by jeffelector** [facebook/react-native#36528]
### Description

To open sms application with text attached i use this code block:
```
 const separator = Platform.OS === 'ios' ? '&' : '?';
    const url = `sms:${phone}${separator}body=${text}`;
    console.log("url",url)
    Linking.openURL(url);
```

when i remove the body part its work fine.

using this code i get error:
Possible Unhandled Promise Rejection (id: 0):
Error: Unable to open URL: file:///private/var/containers/Bundle/Application/E18703D3-1FB9-49B0-BC6E-DA8C4FEFF458/xxx.app/sms:00000000%3Fbody=%D7%A9%D7%9C%D7%95%D7%9D%20%D7%94%D7%9B%20%D7%A0%D7%94%D7%A2,%0A

### React Native Version

0.71.4

### Output of `npx react-native info`

System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
    Memory: 17.19 GB / 31.91 GB
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.18.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 23, 28, 29, 30, 31, 32, 33
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 33.0.0
      System Images: android-30 | Google TV Intel x86 Atom, android-33 | Google APIs Intel x86 Atom_64, android-33 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: AI-213.7172.25.2113.9123335
    Visual Studio: Not Found
  Languages:
    Java: 18.0.1.1 - C:\Program Files\Common Files\Oracle\Java\javapath\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.4 => 0.71.4
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

```

 const separator = Platform.OS === 'ios' ? '&' : '?';
    const url = `sms:${phone}${separator}body=${text}`;
    console.log("url",url)
    Linking.openURL(url);

```
call this code block and got the error 

### Snack, code example, screenshot, or link to a repository

```

 const separator = Platform.OS === 'ios' ? '&' : '?';
    const url = `sms:${phone}${separator}body=${text}`;
    console.log("url",url)
    Linking.openURL(url);

```

**Comment by tzur-ash** [comment]
Face it every time!!!
Please help.

Jeff - Thanks for bringing it up

**Comment by BakkerTom** [comment]
We seem to have the same problem but with a `mailto:` link.

**Comment by jeffelector** [comment]
> We seem to have the same problem but with a `mailto:` link.

yes i can tell i have also the problem with mailto when adding text to it (only on iphone)

**Comment by jeffelector** [comment]
@react-native-bot ?

**Comment by tomo10** [comment]
we are having exactly the same issue

**Comment by timhooker** [comment]
Same problem here as well. I'm finding that if you wrap your link in encodeURI, that allows you to still include the body.

**Comment by jeffelector** [comment]
i can say this is working good, thanks

**Comment by tomo10** [comment]
appreciate this is a different issue but seems there's some expertise on this thread that may know the answer:

have you guys been able to send an SMS to multiple users on iOS?  

if i pass multiple phone numbers, in correct format, to the openURL function, only the first number provided appears in the 'To:' window on the external SMS screen. any advice much appreciated !

**Comment by jde8aa** [comment]
Looks like the issue is that the Linking.openURL call isn't allowing spaces anymore as of RN 0.71, but thankfully like @timhooker said up above, wrapping it all in encodeURI() makes it work again.
