### ISSUE TITLE
[Android] borderColor is broken for transparent colors

### ISSUE THREAD

**Issue by cosmith** [facebook/react-native#3652]
Setting `borderColor: "rgba(255, 255, 255, 0.5)"` works but `borderColor: "rgba(255, 255, 255, 0.6)"` gives a black border.

Expected: 
![screen shot 2015-10-24 at 10 39 16 am](https://cloud.githubusercontent.com/assets/1194749/10709787/810488e6-7a3b-11e5-83c7-0862a6460d93.png)

Android:
![screen shot 2015-10-24 at 10 39 10 am](https://cloud.githubusercontent.com/assets/1194749/10709786/80f1dbe2-7a3b-11e5-9f8d-91aaf381d032.png)

Sample app: https://rnplay.org/apps/l1bw2A

**Comment by satya164** [comment]
@cosmith Is this still an issue?

**Comment by cosmith** [comment]
Sorry for the delay, still an issue on 0.16 but I haven't had the time to upgrade to 0.17 or 0.18.

**Comment by ataber** [comment]
I'm seeing this in 0.17, however opacity of 0.5 also appears as black.

**Comment by scgough** [comment]
I'm also seeing this in 0.17 on Android

I've tried a number of combinations...for e.g.

`mystyle: {
    height:1,
    borderBottomWidth:1,
    borderColor:'rgba(255,255,255,0.5)',
    borderTopWidth:0,
    borderLeftWidth:0,
    borderRightWidth:0,
  },`

**Comment by foghina** [comment]
Seeing this on master, seems related to color parsing? cc @andreicoman11

**Comment by Strainy** [comment]
Can confirm on 0.18, still an issue.

**Comment by trave7er** [comment]
There was a PR addressed to this issue: https://github.com/facebook/react-native/pull/5911, does your RN include it?

**Comment by slamus** [comment]
+1

**Comment by marcshilling** [comment]
Happening in 0.22 still. Black border for any alpha value except `1.0`.

**Comment by IanVS** [comment]
Happening still in 0.23.0-rc.  It seems like instead of a real opacity being calculated, a different color value is being applied.  So, the blacks turn into greys, but are fully opaque.

**Comment by jsangilve** [comment]
Still happening on 0.23-rc1

**Comment by trave7er** [comment]
anybody working on this??

**Comment by samuelpismel** [comment]
Still happening on 0.26

**Comment by omeid** [comment]
I have the same issue with 0.26 on **ios** as well.

**Comment by robertftw** [comment]
Still happens on 0.27.2

**Comment by mattvot** [comment]
@foghina, @andreicoman11, Is fixing this issue scheduled or in a backlog?

**Comment by foghina** [comment]
Not that I know of. Added some tags to encourage people to send a PR to fix it :)

**Comment by fxhereng** [comment]
+1

**Comment by anuragdadheech** [comment]
Waiting for the fix.

**Comment by trave7er** [comment]
I'll work on it. anyone who has already started, please let me know here.

**Comment by trave7er** [comment]
can anyone confirm this issue still exists? I think it's already fixed in the latest build.

**Comment by manicakes** [comment]
Hi all, I have a pull request fixing this here: https://github.com/facebook/react-native/pull/9380

Problem had to do with storing `int` value as `float`. This is lossy when converting back to `int`. Need to use `double` instead.

**Comment by manicakes** [comment]
Many thanks to @foghina for reviewing and getting the pull request merged in today - if @cosmith and others here can confirm this bug is fixed that would be appreciated!

**Comment by satya164** [comment]
Closing this due to 8095707

Let's reopen if it's not fixed.
