### ISSUE TITLE
iOS dictation is adding OBJ to string value

### ISSUE THREAD

**Issue by gkasireddy202** [facebook/react-native#36521]
### Description

Hi,

When I use dictation adding text to TextInput in iOS.
OBJ is added to the text input value.
I am using iOS 16.
Please find the attached screenshot.

Thanks,
<img width="346" alt="Screenshot 2023-03-15 at 6 43 07 PM" src="https://user-images.githubusercontent.com/90603484/226117079-2ff89fb4-2c9b-47f4-8c9e-eac2b407c95a.png">

### React Native Version

0.71.4

### Output of `npx react-native info`

System:
    OS: macOS 13.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 118.30 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.8.1 - /usr/local/bin/node
    Yarn: Not Found
    npm: 9.5.1 - /usr/local/bin/npm
    Watchman: 2023.03.13.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /Users/gopi/.rvm/gems/ruby-2.7.6/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0
      System Images: android-30 | Google APIs Intel x86 Atom, android-32 | Google APIs Intel x86 Atom_64, android-32 | Google Play Intel x86 Atom_64, android-33 | Google APIs Intel x86 Atom_64, android-33 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.4 => 0.71.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1) Click on dictation and start speaking.
2) After the ending of the sentence. 
<img width="346" alt="Screenshot 2023-03-15 at 6 43 07 PM" src="https://user-images.githubusercontent.com/90603484/226117288-17a4d6d2-9a6f-4a2f-8aca-2b5d1c8e6195.png">
A unique character OBJ is added to the text input value.

### Snack, code example, screenshot, or link to a repository

import React, { Component } from 'react';
import { StyleSheet, View, Text, TouchableOpacity, TextInput } from 'react-native';
export default class App extends Component {

  constructor(props) {
    super(props);
    this.state = {

      internalValue: ''

    }

  }

  render() {
    return (<View style={{ flex: 1 }}>

      <View style={{ flex: 1 }}>

      </View>

      <View style={{ flex: 2 }}>
        <View style={{ flex: 8 }}>
          <TextInput
            style={styles.textarea}
            onChangeText={(text) => this.setState({ internalValue: text })}
            value={this.state.internalValue}
            maxLength={120}
            multiline={true}
            placeholder={'Enter Text'}
            placeholderTextColor={'#c7c7c7'}
            underlineColorAndroid={'transparent'}
          />

        </View>
        <TouchableOpacity onPress={() => this.handleClickMe()} style={{ flex: 2, backgroundColor: 'green', margin: 20, alignItems: 'center', justifyContent: 'center' }}>

          <Text>Click me</Text>

        </TouchableOpacity>
      </View>
      <View style={{ flex: 3 }}>

      </View>

    </View>)
  }

}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 30,
    justifyContent: 'center',
    alignItems: 'center',
  },
  textareaContainer: {
    height: 180,
    padding: 5,
    backgroundColor: '#F5FCFF',
  },
  textarea: {
    textAlignVertical: 'top',  // hack android
    height: 170,
    fontSize: 14,
    color: '#333',
    backgroundColor: 'white'
  },
});

**Comment by chrisbobbe** [comment]
#22139 may be related.

**Comment by gkasireddy202** [comment]
#22139  having any solutions. Please provide a solution.


Gopi Kasireddy

A: 12802 Tampa Oaks Boulevard, Suite 100
.   Temple Terrace, FL 
33637
www.khamsoft.com
________________________________

**Comment by gkasireddy202** [comment]
please provide a solution.
This is an odd issue faced by many users.

**Comment by zhurylo** [comment]
onPress has nothing to do with this.

The "OBJ" character bug OR duplicate text bug only appears on iOS 16+ only and is due to "_continuous dictation_" introduced in iOS 16, - https://github.com/facebook/react-native/issues/36045. 

This issue has open peer review on React Native - https://github.com/facebook/react-native/pull/37188

Also, you can verify this by logging text.codePointAt(...) within the onChange method, which returns the value 65532, corresponding to the U+FFFC character.


The **solution**, for now, is to remove that char from the input:

onChangeText={this.handleOnChangeText}

  handleOnChangeText = (text: string) => {
    const { onChangeText } = this.props;

    if (onChangeText) {
      onChangeText(isIos ? text.replace(/\uFFFC/g, '') : text);
    }
  }

**Comment by hellohublot** [comment]
Maybe it's because of the iOS saves  `\UFFFC` to the `back-end`, so I assume the `OBJ` in your screenshot comes from other platforms such as Android platform, because on iOS platform this `\UFFFC` will actually be displayed as an dictation  recognizing indicator

<img src="https://user-images.githubusercontent.com/20135674/238712579-ae484425-5338-498e-8013-31f536f2e742.jpeg" width="300" />


If you are using  iOS native app, It will also have this \uFFFC, but when the dictation recognition ends, or you click other buttons, such as the send message button, the system will forcibly end the dictation, and this `\UFFFC` will also be removed by the system and will not be sent to the server


So I think https://github.com/facebook/react-native/pull/37188 may be able to solve your problem, because it can make the behavior consistent with iOS native

**Comment by SiobhyB** [comment]
Noting that this is also an issue in the WordPress mobile app, which we've worked around via the following code:

https://github.com/WordPress/gutenberg/blob/7cd7a0f53efc0af629ac211e10bd689fcc124e23/packages/react-native-aztec/ios/RNTAztecView/RCTAztecView.swift#L768-L771

Following this issue so we can remove the hack when this is resolved.

**Comment by stharvey** [comment]
I'm encountering this exact same problem. My current workaround involves eliminating the problematic character when the data is received on the server side. I accomplish this using the PHP function below. The second replacement operation includes the "[OBJ]" character, which might not be visible if you're viewing this on an iOS/MacOS device.

```
function removeUfffc($text) {
  $text = str_replace("\ufffc", "", $text);
  $text = str_replace("￼", "", $text);

  return $text;
}
```

**Comment by gkasireddy202** [comment]
@stharvey - Thanks for the reply. I worked on this example. The below one is working fine.
@zhurylo - suggested the below example.


handleOnChangeText = (text: string) => {
  const { onChangeText } = this.props;

  if (onChangeText) { 
     onChangeText(isIos ? text.replace(/\uFFFC/g, '') : text); 
  }
}

<TextInput>
   ...
   onChangeText={this.handleOnChangeText} 
   ...
</TextInput>

**Comment by fabriziobertoglio1987** [comment]
Do you still experience this issue? 

I have four years of experience maintaining facebook/react-native and I specialize in the Text and TextInput components. I currently have 58 [facebook/react-native PRs](https://github.com/facebook/react-native/pulls?q=is%3Apr+author%3Afabriziobertoglio1987+). 

If you still experience this issue, I will prepare a patched release with the fix.

Thanks a lot

**Comment by gkasireddy202** [comment]
I tested the Textinput component on iOS 15,react-native version:0.68.7.
I didn’t face this iOS dictation issue. Are any fixes done?

Thanks a lot.

Gopi Kasireddy
Khameleon Software
e: ***@***.***
a: 12802 Tampa Oaks Boulevard, Suite 100 
Temple Terrace 
FL 
33637
Don't miss the 2024 Khameleon Client Conference May 14 – May 17, 2024! Join us at the beautiful Sandpearl Resort located on Clearwater Beach, Florida. 
To register, click the link below or for more information please contact Carolyn Walden at 813-414-5424 or ***@***.***
2024 Khameleon Client Conference Company Registration Form
________________________________
