### ISSUE TITLE
Facing Crash on launch Android 11 SIGSEGV

### ISSUE THREAD

**Issue by paryanihitesh** [facebook/react-native#36527]
### Description

Facing this crash on only android 11 devices during launch and not able to reproduce this, but there are a lot of logs on firebase for the same

Hermes enabled

StackTrace

Crashed: Thread: SIGSEGV  0x0000000000000000
#00 pc 0x0
#01 pc 0x312008 libart.so (BuildId: 8464040debd8d3c0689bb9e4dae6aedf)
#02 pc 0x686eb0 libart.so (BuildId: 8464040debd8d3c0689bb9e4dae6aedf)
#03 pc 0x12d814 libart.so (BuildId: 8464040debd8d3c0689bb9e4dae6aedf)
#04 pc 0x687150 libart.so (BuildId: 8464040debd8d3c0689bb9e4dae6aedf)
#05 pc 0x12d814 libart.so (BuildId: 8464040debd8d3c0689bb9e4dae6aedf)
#06 pc 0x6897d8 libart.so (BuildId: 8464040debd8d3c0689bb9e4dae6aedf)
#07 pc 0x12d914 libart.so (BuildId: 8464040debd8d3c0689bb9e4dae6aedf)
#08 pc 0x687150 libart.so (BuildId: 8464040debd8d3c0689bb9e4dae6aedf)
#09 pc 0x12d814 libart.so (BuildId: 8464040debd8d3c0689bb9e4dae6aedf)
#10 pc 0x687150 libart.so (BuildId: 8464040debd8d3c0689bb9e4dae6aedf)
#11 pc 0x12d814 libart.so (BuildId: 8464040debd8d3c0689bb9e4dae6aedf)
#12 pc 0x687150 libart.so (BuildId: 8464040debd8d3c0689bb9e4dae6aedf)
#13 pc 0x12d814 libart.so (BuildId: 8464040debd8d3c0689bb9e4dae6aedf)
#14 pc 0x688b94 libart.so (BuildId: 8464040debd8d3c0689bb9e4dae6aedf)
#15 pc 0x12da14 libart.so (BuildId: 8464040debd8d3c0689bb9e4dae6aedf)
#16 pc 0x309460 libart.so (BuildId: 8464040debd8d3c0689bb9e4dae6aedf)
#17 pc 0x6758c0 libart.so (BuildId: 8464040debd8d3c0689bb9e4dae6aedf)
#18 pc 0x13cff8 libart.so (BuildId: 8464040debd8d3c0689bb9e4dae6aedf)
#19 pc 0x74941f1ddd

### React Native Version

0.69.6

### Output of `npx react-native info`

System:
    OS: macOS 12.6
    CPU: (10) x64 Apple M1 Max
    Memory: 22.01 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
    Yarn: 1.22.18 - ~/.nvm/versions/node/v14.17.0/bin/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 26, 28, 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.1, 30.0.2, 30.0.3, 31.0.0, 33.0.0
      System Images: android-22 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, a4
      Android NDK: Not Found
  IDEs:
    Android Studio: Dolphin 2021.3.1 Patch 1 Dolphin 2021.3.1 Patch 1
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0
    react-native: 0.69.6 => 0.69.6
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

On Launch in Android 11 expo react native app

### Snack, code example, screenshot, or link to a repository

NA

**Comment by cortinico** [comment]
> Crashed: Thread: SIGSEGV 0x0000000000000000
> #00 pc 0x0
> #1 pc 0x312008 libart.so (BuildId: 8464040debd8d3c0689bb9e4dae6aedf)
> #2 pc 0x686eb0 libart.so (BuildId: 8464040debd8d3c0689bb9e4dae6aedf)
> #3 pc 0x12d814 libart.so (BuildId: 8464040debd8d3c0689bb9e4dae6aedf)
> #4 pc 0x687150 libart.so (BuildId: 8464040debd8d3c0689bb9e4dae6aedf)
> #5 pc 0x12d814 libart.so (BuildId: 8464040debd8d3c0689bb9e4dae6aedf)
> #6 pc 0x6897d8 libart.so (BuildId: 8464040debd8d3c0689bb9e4dae6aedf)
> #7 pc 0x12d914 libart.so (BuildId: 8464040debd8d3c0689bb9e4dae6aedf)
> #8 pc 0x687150 libart.so (BuildId: 8464040debd8d3c0689bb9e4dae6aedf)
> #9 pc 0x12d814 libart.so (BuildId: 8464040debd8d3c0689bb9e4dae6aedf)
> #10 pc 0x687150 libart.so (BuildId: 8464040debd8d3c0689bb9e4dae6aedf)
> #11 pc 0x12d814 libart.so (BuildId: 8464040debd8d3c0689bb9e4dae6aedf)
> #12 pc 0x687150 libart.so (BuildId: 8464040debd8d3c0689bb9e4dae6aedf)
> #13 pc 0x12d814 libart.so (BuildId: 8464040debd8d3c0689bb9e4dae6aedf)
> #14 pc 0x688b94 libart.so (BuildId: 8464040debd8d3c0689bb9e4dae6aedf)
> #15 pc 0x12da14 libart.so (BuildId: 8464040debd8d3c0689bb9e4dae6aedf)
> #16 pc 0x309460 libart.so (BuildId: 8464040debd8d3c0689bb9e4dae6aedf)
> #17 pc 0x6758c0 libart.so (BuildId: 8464040debd8d3c0689bb9e4dae6aedf)
> #18 pc 0x13cff8 libart.so (BuildId: 8464040debd8d3c0689bb9e4dae6aedf)
> #19 pc 0x74941f1ddd

There is nothing in this crash that points at React Native.
