### ISSUE TITLE
While I update my react app from 0.64.2 to 0.71.3 build failed with the exception app:installDevDebug 

### ISSUE THREAD

**Issue by NikhilMasurkar** [facebook/react-native#36536]
### New Version

0.71.3

### Old Version

0.64.2

### Build Target(s)

java.util.concurrent.ExecutionException: org.gradle.api.GradleException: Failed to install on any devices

### Output of `react-native info`

```
> Task :app:installDevDebug FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings
785 actionable tasks: 780 executed, 5 up-to-date
Note: C:\Project_Repo\App_Frontend\IndigoLearn\node_modules\lottie-react-native\src\android\src\main\java\com\airbnb\android\react\lottie\LottieAnimationViewManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Project_Repo\App_Frontend\IndigoLearn\node_modules\lottie-react-native\src\android\src\main\java\com\airbnb\android\react\lottie\LottieAnimationViewManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: C:\Project_Repo\App_Frontend\IndigoLearn\node_modules\@react-native-async-storage\async-storage\android\src\main\java\com\reactnativecommunity\asyncstorage\AsyncStorageModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Project_Repo\App_Frontend\IndigoLearn\node_modules\@react-native-async-storage\async-storage\android\src\main\java\com\reactnativecommunity\asyncstorage\AsyncStoragePackage.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Project_Repo\App_Frontend\IndigoLearn\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushNativeModule.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Project_Repo\App_Frontend\IndigoLearn\node_modules\react-native-document-picker\android\src\main\java\com\reactnativedocumentpicker\DocumentPickerModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Project_Repo\App_Frontend\IndigoLearn\node_modules\react-native-email-link\android\src\main\java\agency\flexible\react\modules\email\EmailModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
C:\Project_Repo\App_Frontend\IndigoLearn\node_modules\react-native-fbsdk-next\android\src\main\java\com\facebook\reactnative\androidsdk\FBProfileModule.java:50: warning: non-varargs call of varargs method with inexact argument type for last parameter;
                callback.invoke(null);
                                ^
  cast to Object for a varargs call
  cast to Object[] for a non-varargs call and to suppress this warning
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Project_Repo\App_Frontend\IndigoLearn\node_modules\react-native-fbsdk-next\android\src\main\java\com\facebook\reactnative\androidsdk\Utility.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 warning
Note: C:\Project_Repo\App_Frontend\IndigoLearn\node_modules\@invertase\react-native-apple-authentication\android\src\main\java\com\RNAppleAuthentication\AppleAuthenticationAndroidModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Project_Repo\App_Frontend\IndigoLearn\node_modules\@react-native-firebase\crashlytics\android\src\main\java\io\invertase\firebase\crashlytics\ReactNativeFirebaseCrashlyticsModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Project_Repo\App_Frontend\IndigoLearn\node_modules\@react-native-firebase\dynamic-links\android\src\main\java\io\invertase\firebase\dynamiclinks\ReactNativeFirebaseDynamicLinksModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Project_Repo\App_Frontend\IndigoLearn\node_modules\@react-native-firebase\perf\android\src\main\java\io\invertase\firebase\perf\UniversalFirebasePerfModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Project_Repo\App_Frontend\IndigoLearn\node_modules\@react-native-google-signin\google-signin\android\src\main\java\com\reactnativegooglesignin\RNGoogleSigninModule.java uses or overrides a deprecated API. 
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Project_Repo\App_Frontend\IndigoLearn\node_modules\@react-native-google-signin\google-signin\android\src\main\java\com\reactnativegooglesignin\RNGoogleSigninModule.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Project_Repo\App_Frontend\IndigoLearn\node_modules\react-native-orientation\android\src\main\java\com\github\yamill\orientation\OrientationModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Project_Repo\App_Frontend\IndigoLearn\node_modules\react-native-razorpay\android\src\main\java\com\razorpay\rn\RazorpayModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Project_Repo\App_Frontend\IndigoLearn\node_modules\react-native-svg\android\src\main\java\com\horcrux\svg\VirtualView.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Project_Repo\App_Frontend\IndigoLearn\node_modules\react-native-video\android\src\main\java\com\brentvatne\react\ReactVideoViewManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Project_Repo\App_Frontend\IndigoLearn\node_modules\react-native-webview\android\src\main\java\com\reactnativecommunity\webview\RNCWebViewManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: C:\Project_Repo\App_Frontend\IndigoLearn\android\app\src\debug\java\com\fin1\ReactNativeFlipper.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:installDevDebug'.
> java.util.concurrent.ExecutionException: org.gradle.api.GradleException: Failed to install on any devices.
```

### Issue and Reproduction Steps

my package Json file 
`{
  "name": "Fin1",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android:dev": "ENVFILE=./env/.env.dev npx react-native run-android --variant=devDebug --appIdSuffix=dev",
    "android:prod": "ENVFILE=./env/.env.prod npx react-native run-android --variant=prodDebug",
    "android:prodBundle": "cd android && ENVFILE=./env/.env.prod ./gradlew clean && ./gradlew bundleProdRelease",
    "android:prodApk": "cd android && ENVFILE=./env/.env.prod ./gradlew clean && ./gradlew assembleProdRelease",
    "android:devRelease": "cd android && ENVFILE=./env/.env.dev ./gradlew clean && ./gradlew assembleDevRelease",
    "ios:dev": "ENVFILE=./env/.env.dev react-native run-ios --scheme \"Fin1Dev\" --configuration \"Dev.Debug\"",
    "codepush:androidDev": "appcenter codepush release-react -a IndigoLearn/1FIN-by-Indigolearn -d Dev -m -t 2.1.2",
    "codepush:iosDev": "appcenter codepush release-react -a IndigoLearn/1FIN-by-Indigolearn-1 -d Dev -m -t 2.1.2",
    "codepush:iosProd": "appcenter codepush release-react -a IndigoLearn-Prod/1FIN-By-IndigoLearn-1 -d Production -m -t 2.1.2",
    "codepush:androidProd": "appcenter codepush release-react -a IndigoLearn-Prod/1FIN-By-IndigoLearn -d Production -m -t 2.1.2",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint .",
    "repo:cleanup": "rm -rf node_modules & rm -rf yarn.lock & yarn install & cd ios & rm -rf Podfile.lock & pod install & cd ..",
    "android:winDev": "set \"ENVFILE=./env/.env.dev\" && npx react-native run-android --variant=devDebug --appIdSuffix=dev"
  },
  "dependencies": {
    "@invertase/react-native-apple-authentication": "^2.2.2",
    "@native-html/table-plugin": "^5.3.1",
    "@react-native-async-storage/async-storage": "^1.17.12",
    "@react-native-community/datetimepicker": "^6.7.5",
    "@react-native-community/netinfo": "^9.3.7",
    "@react-native-firebase/analytics": "^15.7.0",
    "@react-native-firebase/app": "^15.7.0",
    "@react-native-firebase/crashlytics": "^15.7.0",
    "@react-native-firebase/dynamic-links": "^15.7.0",
    "@react-native-firebase/messaging": "^15.7.0",
    "@react-native-firebase/perf": "^15.7.0",
    "@react-native-google-signin/google-signin": "^9.0.2",
    "@react-native-masked-view/masked-view": "^0.2.8",
    "@react-navigation/drawer": "^6.6.2",
    "@react-navigation/native": "^6.1.6",
    "@react-navigation/stack": "^6.3.16",
    "axios": "^1.3.4",
    "lottie-ios": "^4.1.3",
    "lottie-react-native": "^5.1.5",
    "metro": "^0.75.1",
    "react": "18.2.0",
    "react-native": "0.71.3",
    "react-native-animatable": "^1.3.3",
    "react-native-calendars": "^1.1293.0",
    "react-native-canvas": "^0.1.38",
    "react-native-cashfree-pg-sdk": "^2.0.2",
    "react-native-circular-progress": "^1.3.8",
    "react-native-code-push": "^7.1.0",
    "react-native-config": "^1.5.0",
    "react-native-deck-swiper": "^2.0.13",
    "react-native-device-info": "^10.4.0",
    "react-native-document-picker": "^8.1.3",
    "react-native-email-link": "^1.14.3",
    "react-native-exception-handler": "^2.10.10",
    "react-native-fbsdk-next": "^11.1.0",
    "react-native-file-viewer": "^2.1.5",
    "react-native-flash-message": "^0.4.0",
    "react-native-freshchat-sdk": "^4.2.2",
    "react-native-fs": "^2.20.0",
    "react-native-gesture-handler": "^2.9.0",
    "react-native-gifted-charts": "^1.2.42",
    "react-native-hyperlink": "^0.0.22",
    "react-native-image-crop-picker": "^0.39.0",
    "react-native-image-zoom-viewer": "^3.0.1",
    "react-native-in-app-review": "^4.2.1",
    "react-native-linear-gradient": "^2.6.2",
    "react-native-material-ripple": "^0.9.1",
    "react-native-modal": "^13.0.1",
    "react-native-modal-datetime-picker": "^14.0.1",
    "react-native-multicolor-progress-bar": "^2.0.0",
    "react-native-offline": "^6.0.2",
    "react-native-orientation": "^3.1.3",
    "react-native-paper": "^5.2.0",
    "react-native-pg-react-native-sdk": "^2.1.6",
    "react-native-play-install-referrer": "^1.1.8",
    "react-native-progress": "^5.0.0",
    "react-native-razorpay": "^2.3.0",
    "react-native-reanimated": "^2.14.4",
    "react-native-render-html": "^6.3.4",
    "react-native-restart": "^0.0.27",
    "react-native-safe-area-context": "^4.5.0",
    "react-native-screens": "^3.20.0",
    "react-native-share": "^8.2.0",
    "react-native-shimmer-placeholder": "^2.0.9",
    "react-native-slider": "^0.11.0",
    "react-native-sms-retriever": "^1.1.1",
    "react-native-splash-screen": "^3.3.0",
    "react-native-svg": "^13.8.0",
    "react-native-swipe-gestures": "^1.0.5",
    "react-native-swipeable-rating": "^0.2.1",
    "react-native-swiper-flatlist": "^3.0.18",
    "react-native-vector-icons": "^9.2.0",
    "react-native-video": "file:../Resources/vdocipher_iOS/react-native-video-fix-fairplay",
    "react-native-video-vdo": "file:../Resources/vdocipher_iOS/react-native-video-vdo-master",
    "react-native-webview": "^11.26.1",
    "react-native-youtube-iframe": "^2.2.2",
    "react-navigation-backhandler": "^2.0.1",
    "react-redux": "^8.0.5",
    "recyclerlistview": "^4.2.0",
    "redux": "^4.2.1",
    "redux-persist": "^6.0.0",
    "redux-thunk": "^2.4.2",
    "vdocipher-rn-bridge": "^1.12.2"
  },
  "devDependencies": {
    "@babel/core": "^7.20.12",
    "@babel/runtime": "^7.20.13",
    "@react-native-community/eslint-config": "^3.2.0",
    "babel-jest": "^29.4.3",
    "eslint": "^8.34.0",
    "jest": "^29.4.3",
    "metro-react-native-babel-preset": "^0.75.0",
    "react-test-renderer": "18.2.0",
    "redux-logger": "^3.0.6"
  },
  "jest": {
    "preset": "react-native"
  }
}
`

**Comment by cortinico** [comment]
> java.util.concurrent.ExecutionException: org.gradle.api.GradleException: Failed to install on any devices.

Your build failed to install the app on the device.
I can't help you further with more debugging information.
Do you have a device connected? Can you share the output of `adb devices`?

**Comment by NikhilMasurkar** [comment]
yes my device connected 
`List of devices attached
c7a98d09        device`
but in metro, it gives me one error continuously 

`Error: EPERM: operation not permitted, lstat 'C:\Project Repo\App_Frontend\IndigoLearn\android\app\build\intermediates\i ncremental\devDebug\mergeDevDebugResources\merged.dir\values-lv\values-lv.xml' Emitted 'error' event on NodeWatcher instance at:

at C:\Project Repo\App_Frontend\IndigoLearn\node_modules\@react-native-community\cli-plugin-metro\node_modules\metro -file-map\src\watchers\NodeMatcher.js:235:14

at FSReqCallback, oncomplete (fs.js:192:21) {

errno: -4848,

code: EPERH

syscall: 'lstat',

path: C:\\Project Repo\\App Frontend\\IndigoLearn\\android\\app\\build\\intermediates\\incremental\\devDebug\\mergeDe DebugResources\\serged.dir\\values-ly\\values-lv.xml'`

what does that means I Dont Know.

**Comment by NikhilMasurkar** [comment]
yes, List of devices attached
c7a98d09        device

it build successfully but sometime metro crash with the exception 
`Error: EPERM: operation not permitted, lstat 'C:\Project Repo\App_Frontend\IndigoLearn\android\app\build\intermediates\i ncremental\devDebug\mergeDevDebugResources\merged.dir\values-lv\values-lv.xml' Emitted 'error' event on NodeWatcher instance at:

at C:\Project Repo\App_Frontend\IndigoLearn\node_modules\@react-native-community\cli-plugin-metro\node_modules\metro -file-map\src\watchers\NodeMatcher.js:235:14

at FSReqCallback, oncomplete (fs.js:192:21) {

errno: -4848,

code: EPERH

syscall: 'stat',

path: C:\\Project Repo\\App Frontend\\IndigoLearn\\android\\app\\build\\intermediates\\incremental\\devDebug\\mergeDe DebugResources\\serged.dir\\values-ly\\values-lv.xml'`


**or sometime it build fail with the error** 

BUILD FAILED in 25s

Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Task 'installDebug' not found in project ':app'. Some candidates are: 'installDevDebug'.

* Try:
> Run gradlew tasks to get a list of available tasks.
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by Samsonnyyeet** [comment]
Please let me know how you fixed the first error which said:
java.util.concurrent.ExecutionException: org.gradle.api.GradleException: Failed to install on any devices.
