### ISSUE TITLE
Android build fails for any Gradle build type other than `debug` or `release`

### ISSUE THREAD

**Issue by alexeystrakh** [facebook/react-native#36530]
### Description

I have an android application with react native integration. After adding a new Android Gradle build configuration unable to build my app for any build type other than `debug` or `release`. 

I have created a [new build type](https://github.com/alexeystrakh/react-native-screens-android-issue/blob/main/android/app/build.gradle#L132-L138) `myRelease` in the app module Gradle which is identical to the `release` configuration:

```
buildTypes {
   release {
      …
   } 
   myRelease {
      …
   }
}
```

And when I build the app with that flavor:

> ./gradlew assembleMyRelease
or
> npx react-native run-android --mode=myRelease

It fails with the following error:

```
> Could not resolve com.facebook.react:react-android.
     Required by:
         project :app
      > No matching variant of com.facebook.react:react-android:0.71.4 was found. The consumer was configured to find a runtime of a component, preferably optimized for Android, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'myRelease'…
```

The full error output is [here](https://github.com/alexeystrakh/react-native-screens-android-issue/blob/main/react-native-custom-build-type-error.log)

The build works with no issue in `debug` or `release` configurations but not the new `myRelease` which should be the same as `release`. 

I have also found [this StackOverflow topic](https://stackoverflow.com/a/60427868/1561937) which suggests a solution to use `matchingFallbacks` parameter as part of any custom build type configuration to specify fallback used by other native modules, but it is marked as deprecated by Gradle.

### React Native Version

0.71.4

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1
    Memory: 67.67 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.6.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.4.2 - /opt/homebrew/bin/npm
    Watchman: 2023.02.06.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /Users/<user>/.rvm/gems/ruby-2.7.6/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9619390
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.4 => 0.71.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. Create a new react native project (non expo):

> npx react-native init NewApp22

2. Modify Android app build.gradle file to include a new build type `myRelease`
3. Run the app with the new configuration:

> ./gradlew assembleMyRelease
or
> npx react-native run-android --mode=myRelease

### Snack, code example, screenshot, or link to a repository

https://github.com/alexeystrakh/react-native-screens-android-issue

**Comment by cortinico** [comment]
> buildTypes {
>    release {
>       …
>    } 
>    myRelease {
>       …
>    }
> }

Coud you share the full `buildTypes` block with all the values?

**Comment by cortinico** [comment]
And yes, you're correct that you should use `matchingFallbacks`. Could you point out to where you discovered that is deprecated?
The docs for it are here https://developer.android.com/reference/tools/gradle-api/7.3/com/android/build/api/dsl/BuildType#matchingFallbacks()

Using `initWith` should also work:
https://developer.android.com/reference/tools/gradle-api/7.3/com/android/build/api/dsl/BuildType#initWith(com.android.build.api.dsl.BuildType)

**Comment by alexeystrakh** [comment]
> Coud you share the full `buildTypes` block with all the values?

I used the default [content of that block](https://github.com/alexeystrakh/react-native-screens-android-issue/blob/main/android/app/build.gradle#L125-L138) created with a default RN template and for my new build type I just copied the content on the `release` block (release works just fine).

> Could you point out to where you discovered that is deprecated?

It's reported by Android Studio as deprecated:
<img width="741" alt="image" src="https://user-images.githubusercontent.com/3697084/226391556-797b1877-9bbb-4996-af5c-55424f707879.png">

**Comment by alexeystrakh** [comment]
I've tried the `initWith` before and it let me define a new build type without copying all the previously set settings but I still need `matchingFallbacks` to make the build type work with RN.

Thanks for the new notation example, I have set it and now it works great 👍 

```
        myRelease {
            initWith release
            matchingFallbacks.add("release")
        }
```
