### ISSUE TITLE
IOS: Include of non-modular header inside framework module 'yoga.YGNode':

### ISSUE THREAD

**Issue by Gabotron-ES** [facebook/react-native#36538]
### Description

In my react native IOS app (android works fine) when I run npx react-native run ios I get a few errors related to react-native-image-picker and Yoga (whatever that is).

Screenshot of errors in xcode where I can see more detailed errors info:
https://i.imgur.com/KzzYR1a.png

In cli error looks like this (less detailed):

```
CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler (in target 'react-native-video' from project 'Pods')
	CompileC /Users/gabriel/Library/Developer/Xcode/DerivedData/wooapp-ecvnzpvdhxltnxeoglpliezckkzc/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-image-picker.build/Objects-normal/x86_64/ImagePickerManager.o /Users/gabriel/Desktop/proyectos/wiii/node_modules/react-native-image-picker/ios/ImagePickerManager.mm normal x86_64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'react-native-image-picker' from project 'Pods')
````
I'm not using M1 chip or Rosetta. My xcode version is 13.

```
"react-native": "0.68.5",
"react-native-image-picker": "^5.1.0",
```

My pod file:
```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
#$RNFirebaseAsStaticFramework = true
platform :ios, '11.0'
install! 'cocoapods', :deterministic_uuids => false

target 'wooapp' do
  config = use_native_modules!
  #use_frameworks!
  use_frameworks! :linkage => :static
  $RNFirebaseAsStaticFramework = true
  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'wooappTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  #use_flipper!()

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        target.build_settings(config.name)['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
      end
    end
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end

```
Thanks in advance

### React Native Version

0.68.5

### Output of `npx react-native info`

System:
    OS: macOS 12.6.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 455.92 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.9.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 8.19.1 - /usr/local/bin/npm
    Watchman: 2022.09.05.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.5 => 0.68.5 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

npx pod-install ios
npx react-native run-ios -- --reset-cache

Error shows up in cli

Building in xcode I get same error but with more info (error is related to Yoga modules)

### Snack, code example, screenshot, or link to a repository

Can't share reproducible example

**Comment by cortinico** [comment]
> ###
> In my react native IOS app (android works fine) when I run npx react-native run ios I get a few errors related to react-native-image-picker and Yoga (whatever that is).

Hi @Gabotron-ES 
Thanks for reporting this issue.

It seems like this issue is actually unrelated to React Native core. Please open this issue against this other repository:

https://github.com/react-native-image-picker/react-native-image-picker/issues

I'll be closing this but feel free to reopen if the other repo points back to us as a issue in the core of React Native.
