### ISSUE TITLE
Can't force switch comma and dot for IOS Native keyboard

### ISSUE THREAD

**Issue by maye1115** [facebook/react-native#36554]
### Description

https://stackoverflow.com/questions/71678466/get-system-region-in-safari-for-ios,
When the user set the Region from Singapore to Vietnam in the system config Language & Region, the IOS Native keyboard can not see the dot(.) anymore,  will default use comma(,). Need a params to force the switching of symbols.
![image](https://user-images.githubusercontent.com/56068387/226601047-73798a9e-5614-4e12-bc99-f42a559110b1.png)
![image](https://user-images.githubusercontent.com/56068387/226601085-db1e9ef9-ff1f-4a42-a4a1-92fb3a5924b3.png)

### React Native Version

0.63.3

### Output of `npx react-native info`

System:
    OS: macOS 11.7.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 2.11 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.5 - /usr/local/bin/node
    Yarn: 3.2.0 - /usr/local/bin/yarn
    npm: 6.14.14 - /usr/local/bin/npm
    Watchman: 2021.08.30.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK: Not Found
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.3 => 0.63.3
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

set the Region from Singapore to Vietnam in the system config Language & Region,

### Snack, code example, screenshot, or link to a repository

apply <TextInput keyboardType='numeric' ....

**Comment by mickey35vn** [comment]
It is not possible to force keyboard to use comma, just can replace comma for decimal with point once comma is entered
