### ISSUE TITLE
yarn ios一直卡在这里，动都不动一下?有谁遇到过吗

### ISSUE THREAD

**Issue by sparGuan** [facebook/react-native#36555]
### Description

<img width="761" alt="image" src="https://user-images.githubusercontent.com/28480563/226604817-6eab5756-7b32-4e23-9bdd-f3123e14dfe9.png">
<img width="761" alt="image" src="https://user-images.githubusercontent.com/28480563/226604974-8c5967ba-ed78-44ac-99f4-7b427d53d8e1.png">

### React Native Version

0.71

### Output of `npx react-native info`

System:
    OS: macOS 13.2.1
    CPU: (4) x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
    Memory: 34.47 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.15.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 9.5.0 - /usr/local/bin/npm
    Watchman: 2023.03.13.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /Users/mac/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_211 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.4 => 0.71.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

按照官网
1.翻墙
2. npx react-native init project
3.sceessed
4. yarn ios
5.一直卡死

### Snack, code example, screenshot, or link to a repository

npx react-native init project

**Comment by kelset** [comment]
I'm not sure what the report is about here - the screenshots only show a warning?

**Comment by sparGuan** [comment]
"I tried to use the react-native doc command to fix it, but an error occurred. An error occurred while xocde was running native, and it was automatically fixed by pressing e"

**Comment by sparGuan** [comment]
我尝试使用了react-native doctor命令去修复它，产生了一个错误，xocde运行native中出错了，按e自动被修复掉

**Comment by cortinico** [comment]
Hi @sparGuan 
In this issue tracker we accept only issues that are in English.
Sadly we can't support you further if your issue is not in English. I'm closing this for now, please consider translating it to English and reopening it.
Thanks.

**Comment by sparGuan** [comment]
This problem has reappeared. I have been stuck in Yarn IOS all the time. Finally, I found out that it was due to the icloud cloud folder that caused xcode to fail to open. Just move it out of the icloud cloud folder

**Comment by sparGuan** [comment]
Developing with Xcloud and never using iccloud cloud have many problems

**Comment by sparGuan** [comment]
After I removed it from the icloud cloud, it now runs normally with xcode!!!!, Yarn ios is not stuck either!!!!

**Comment by sparGuan** [comment]
https://www.5axxw.com/questions/content/j43wlo  

谢谢他给了我灵感
