### ISSUE TITLE
Character "￼" inserted at end of dictation text input on iOS.

### ISSUE THREAD

**Issue by gkasireddy202** [facebook/react-native#36551]
You are right, this seems like this is a real issue but unfortunately it's unlikely anyone will be able to spend time on this anytime soon. I'm going to close this issue but we are more than happy to receive a pull request with a fix for this!

_Originally posted by @cpojer in https://github.com/facebook/react-native/issues/22139#issuecomment-479058793_

**Comment by gkasireddy202** [comment]
Can you please provide a solution?

https://github.com/facebook/react-native/issues/36497

**Comment by NickGerleman** [comment]
I don't think posting a new issue when your last last was closed as duplicate is going to help here.
