### ISSUE TITLE
[iOS] ActivityIndicator incorrectly centered (few pixels off)

### ISSUE THREAD

**Issue by dylancom** [facebook/react-native#36564]
### Description

I have noticed that the ActivityIndicator is positioned a few pixels off when in a box.
(top: approx -1.5 pixels, left: approx -1,5 pixels)

I have tried changing the native code but couldn't figure how to fix this without a hack.

<img width="94" alt="Scherm­afbeelding 2023-03-22 om 09 24 03" src="https://user-images.githubusercontent.com/12894112/226843977-8f5a2708-07df-4105-bb9a-849b439301d3.png">

### React Native Version

0.71.4

### Output of `npx react-native info`

System:
    OS: macOS 13.2.1
    CPU: (12) arm64 Apple M2 Pro
    Memory: 941.72 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.1 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 8.11.0 - /usr/local/bin/npm
    Watchman: 2023.02.13.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /Users/***/.rvm/gems/ruby-2.7.6/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9514443
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.4 => 0.71.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

`<View style={{backgroundColor: 'red'}}><ActivityIndicator size="large" color="yellow" /></View>`

### Snack, code example, screenshot, or link to a repository

<img width="94" alt="Scherm­afbeelding 2023-03-22 om 09 24 03" src="https://user-images.githubusercontent.com/12894112/226843176-701e9a50-dc96-4eac-b3b7-82031646ea29.png">

**Comment by gbalduzzi** [comment]
I'm seeing the same issue on react-native `0.72.3`

I resolved adding the following style to the activity indicator on size large:

```
{
  marginTop: Platform.OS === 'ios' ? 3 : 0,
  marginLeft: Platform.OS === 'ios' ? 3 : 0,
}
```

**Comment by andresribeiro** [comment]
+1

**Comment by JackFord18** [comment]
Still seeing this with RN 0.76.7 as well.

**Comment by Pnlvfx** [comment]
+1

**Comment by Pnlvfx** [comment]
Why is this closed?

**Comment by szymonWCa** [comment]
Same issue on RN 0.79.5
