### ISSUE TITLE
having same issue with lowercasing, every time a capital case character is entered, the text that is passed to onChangeText function contains exact duplicate of existing text plus last entered character. it happens only on android devices, on ios it works fine

### ISSUE THREAD

**Issue by shuklaharshit** [facebook/react-native#36563]
having same issue with lowercasing, every time a capital case character is entered, the text that is passed to onChangeText function contains exact duplicate of existing text plus last entered character. it happens only on android devices, on ios it works fine

_Originally posted by @magneticz in https://github.com/facebook/react-native/issues/11068#issuecomment-277206568_

**Comment by efstathiosntonas** [comment]
This [PR](https://github.com/facebook/react-native/pull/35929) solves this

**Comment by fabriziobertoglio1987** [comment]
Do you still experience this issue? 

I have four years of experience maintaining facebook/react-native and I specialize in the Text and TextInput components. I currently have 58 [facebook/react-native PRs](https://github.com/facebook/react-native/pulls?q=is%3Apr+author%3Afabriziobertoglio1987+). 

If you still experience this issue, I will prepare a patched release with the fix.

Thanks a lot

**Comment by cimpianRadu** [comment]
It still happens on react-native: 0.75 | expo:51 😞
