### ISSUE TITLE
[Android] [Image] tintColor is broken

### ISSUE THREAD

**Issue by cosmith** [facebook/react-native#3657]
Setting `tintColor` on Android has no effect.

iOS:
![screen shot 2015-10-24 at 4 50 58 pm](https://cloud.githubusercontent.com/assets/1194749/10711024/75dda356-7a6f-11e5-96d1-e6c449fa1269.png)

Android:
![screen shot 2015-10-24 at 4 51 14 pm](https://cloud.githubusercontent.com/assets/1194749/10711025/75dde140-7a6f-11e5-97e2-f612bbdda3b7.png)

Sample app: https://rnplay.org/apps/oA7vIg

**Comment by ide** [comment]
Can you give it border radius of 1 or some small value?

cc @kmagiera This might be a known problem. Is it easy to fix?

**Comment by cosmith** [comment]
It works with a border radius of 1, thanks for the workaround :+1:

**Comment by isair** [comment]
@ide I've found that if the Image component has `resizeMode="contain"`, having `borderRadius: 1` in style doesn't fix it. Haven't test with other resizeMode values.

**Comment by jcsmesquita** [comment]
Seems that the fix also doesn't work if the Image component is wrapping any children component.

**Comment by ide** [comment]
I bet this could end up being easy to fix because tintColor is already implemented -- it just doesn't activate in certain cases. If there's a performance reason (the tint color code path is slower) then we could apply the tint color only when tintColor is set. I'm going to mark this as Help Wanted.

**Comment by msathis** [comment]
This seems to be working in latest master. But shows wrong warning 
```Failed propType: Invariant Violation: Invalid props.style key `tintColor` supplied to `Image`.```

![screen](https://cloud.githubusercontent.com/assets/2977899/11592367/0d1811b0-9ac4-11e5-89c8-fb1dd3e38da8.png)

**Comment by ahanriat** [comment]
Yes it looks like it doesn't have the correct `style` props like on [iOS](https://github.com/facebook/react-native/blob/master/Libraries/Image/Image.ios.js#L58)

**Comment by scruff311** [comment]
This an old thread, but I find it still does not work on Android sometimes. I've tried adding `borderRadius: 1` and removing the `resizeMode="contain"` but still nothing.

Is it size dependent by chance? I have one component with larger (60x60) images where it works, but another component with smaller images (14x14) where it doesn't.

I'm using React Native 49.5.

**Comment by jpmazza** [comment]
HI! I'm having the same issue here. Any updates? 

I'm using ReactNative `0.51.0`
