### ISSUE TITLE
MaxBufferError: stderr MaxBuffer exceeded

### ISSUE THREAD

**Issue by aannaassalam** [facebook/react-native#36595]
### Description

Hi I am trying to run my project when I am getting this error.

```
C:\Users\aannaassalam\Documents\Github\dealzup>npm run android

> dealzup@0.0.1 android
> react-native run-android

info JS server already running.
info Installing the app...
<========-----> 66% CONFIGURING [4s]
> :app

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
MaxBufferError: stderr maxBuffer exceeded
    at PassThrough.<anonymous> (C:\Users\aannaassalam\Documents\Github\dealzup\node_modules\get-stream\index.js:41:19)
    at PassThrough.emit (node:events:525:35)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:293:11)
    at Readable.push (node:internal/streams/readable:234:10)
    at node:internal/streams/transform:182:12
    at PassThrough._transform (node:internal/streams/passthrough:46:3)
    at Transform._write (node:internal/streams/transform:175:8)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
info Run CLI with --verbose flag for more detai5 actionable tasks: 5 up-to-date

```

I tried searching for a working solution but was unable to. I also tried setting up react native enviroment but this doesn't solve anything. I am not quite sure if this error is related to android studio, react-native or nodejs. Coz the very same repo is working absolutely fine in my colleagues laptop but not mine. 

I quick guide, help or solution will be highly appriciated.

### React Native Version

0.71.4

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.23403
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
    Memory: 396.23 MB / 7.83 GB
  Binaries:
    Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 9.6.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 33, 33
      Build Tools: 33.0.0, 33.0.1, 33.0.2
      System Images: android-33 | Google APIs Intel x86_64 Atom
      Android NDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Disabled
      Versions: 10.0.19041.0
  IDEs:
    Android Studio: AI-221.6008.13.2211.9619390
    Visual Studio: Not Found
  Languages:
    Java: 11.0.18 - C:\Program Files\Microsoft\jdk-11.0.18.10-hotspot\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.4 => 0.71.4
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

It happened automatically, there are no steps that in particular caused this issue.

### Snack, code example, screenshot, or link to a repository

https://github.com/aannaassalam/dealzup

**Comment by CongDuongLe** [comment]
same errror, waiting for reply

**Comment by cortinico** [comment]
> same errror, waiting for reply

Hey,
This issue is actually unrelated to React Native core but related to our CLI. Please open this issue against this other repository:

https://github.com/react-native-community/cli/issues

Folks over there can support you better @CongDuongLe 

I'll be closing this but feel free to reopen if the other repo points back to us as a issue in the core of React Native.
