### ISSUE TITLE
How do I get property defined in 'gradle.properties in react-native-gradle-plugin/setting.gradle.kts ?

### ISSUE THREAD

**Issue by wanxue0804** [facebook/react-native#36592]
### New Version

0.71.3

### Old Version

0.62.2

### Build Target(s)

android

### Output of `react-native info`

Node: 18.14.2
React: 18.2.0
React-native: 0.71.3

### Issue and Reproduction Steps

I upgraded from 0.62 to 0.71.3
The usname and password used to configure the local maven address are placed in the android/gradle.properties file.
Now I am in node_modules/react-native-gradle-plugin/settings_gradle.kts, how do I get usname and password from android/gradle.properties

android/gradle.properties
```
username=testAdmin
password=test123
```

In settings_gradle.kts I tried
```
pluginManagement {
  val userName: String by settings
  val password: String by settings
  /*
  or
  val userName: String by project
  val password: String by project
  */
  
  repositories: {
    maven {
      url = uri('....')
      credentials{
        username = userName
        password=password
      }
    }
  }
}
```
and
```
val usernameProvider = providers.gradleProperty("username")
val passwordProvider = providers.gradleProperty("password")
pluginManagement {
  repositories: {
    maven {
      url = uri('....')
      credentials{
        username = usernameProvider.getOrNull()
        password = passwordProvider.getOrNull()
      }
    }
  }
}
```

None of the above work

**Comment by cortinico** [comment]
> Now I am in node_modules/react-native-gradle-plugin/settings_gradle.kts, how do I get usname and password from android/gradle.properties

Why do you want to do that?

**Comment by wanxue0804** [comment]
> > Now I am in node_modules/react-native-gradle-plugin/settings_gradle.kts, how do I get usname and password from android/gradle.properties
> 
> Why do you want to do that?

Because we are using Intranet development, installing dependency packages requires an internal proxy.
Now we put the account number and password of the intranet address in the android/gradle.properties file, and modify the moven() of the .gradle file of the dependent package through scripts. This operation is normal, but the .kts cannot be recognized

The .gradle file is modified like
```
builsscript {
  repositories {
    moven {
      url "https://proxy.com.url"
      credentials {
        username "${username}"
        password "${password}"
      }
    }
  }
}
```
The same writing method cannot be recognized in the .kts file, and it prompts that there is no permission.
but it is possible to write the username and password into the real account and password in string form
```
repositories {
    moven {
      url= uri("https://proxy.com.url"),
      credentials {
        username="${username}"
        password="${password}"
      }
    }
  }
```

**Comment by cortinico** [comment]
I understand your problem, thanks for clarifying 👍 

You should be able to specify this in the `settings.gradle` file of your project, as described here https://docs.gradle.org/current/userguide/declaring_repositories.html#sub:centralized-repository-declaration
You can find examples for both Groovy and Kotlin DSL variants of Gradle.

This will allow to specify the proxy that will work for all the app & libraries in your project.

**Comment by wanxue0804** [comment]
[https://docs.gradle.org/current/userguide/build_environment.html](https://docs.gradle.org/current/userguide/build_environment.html)
I found the answer, thanks
```
repositories {
    maven {
      url= uri("https://proxy.com.url"),
      credentials {
        username= System.getProperty("username")
        password= System.getProperty("password")
      }
    }
  }
```
