### ISSUE TITLE
React native Discussions

### ISSUE THREAD

**Issue by boopathi** [facebook/react-native#366]
Can we have a place to discuss doubts, how-tos and more on mailing lists or Gitter.im ? Or do we use this only - https://groups.google.com/forum/#!forum/reactjs ?

**Comment by ide** [comment]
There's a new group (public) at https://www.facebook.com/groups/586400221495560.

**Comment by jordwalke** [comment]
Please let us know if that group isn't meeting the needs of the community and we'll work something else out.

**Comment by boopathi** [comment]
This should work. But sometimes, writing markdown or syntax highlighted code snippets can be useful.

**Comment by jordwalke** [comment]
I totally agree. Feel free to link to gists from the Facebook group.
