### ISSUE TITLE
Horizontal FlatList on Android doesn't recalculate layout/width after dynamically removing items

### ISSUE THREAD

**Issue by joshrounsville** [facebook/react-native#36617]
### Description

I have a horizontal flatlist that contains enough items to overflow the screen. If I scroll to the last item, then dynamically remove all but the first item, the flatlist fails to scroll back to the first item, leaving me with what appears to be an empty flatlist. 

I can swipe the flatlist to get back to the first item, but often times this results in the first item jumping to the left and right side of the screen.

I'm only able to reproduce on Android.

### React Native Version

0.70.7

### Output of `npx react-native info`

System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 109.23 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.18 - ~/.dev/yarn/1.22.18/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
    Watchman: 2023.03.06.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /Users/joshrounsville/.gem/ruby/3.1.2/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK:
      API Levels: 28, 29, 30, 32, 33
      Build Tools: 30.0.2, 32.0.0
      System Images: android-28 | Google APIs ARM 64 v8a, android-30 | Google APIs ARM 64 v8a, android-30 | Google APIs Intel x86 Atom_64, android-32 | Google APIs ARM 64 v8a, android-32 | Google Play ARM 64 v8a, android-32 | Google Play Intel x86 Atom_64, android-33 | Google APIs ARM 64 v8a, android-33 | Google APIs Intel x86 Atom_64, android-33 | Google Play ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7935034
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /opt/homebrew/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.7 => 0.70.7 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

- create a horizontal flatlist with enough items to overflow the screen
- scroll to the last item
- dynamically remove all but first item
- on Android notice that the layout is not updated to put the remaining item in the correct position
- notice that on scroll the remaining item "jumps" to either side of the screen

### Snack, code example, screenshot, or link to a repository

Snack link: https://snack.expo.dev/l5vcCjBGb

On device (Pixel 7):
<video src="https://user-images.githubusercontent.com/338056/227386728-5b8a08d2-fa09-49ea-985c-f05ca74f6f3a.mp4" />

**Comment by jonathanackerson** [comment]
I'm seeing this same issue

**Comment by atulbrydotintuit** [comment]
Its similar to [https://github.com/facebook/react-native/issues/36845#issuecomment-1508369640](url)

**Comment by atulbrydotintuit** [comment]
Similar issue, please refer to this comment:
https://github.com/facebook/react-native/issues/36845#issuecomment-1508369640

**Comment by johnhaup** [comment]
Please don't close this baby this issue is as valid as they come

**Comment by ashwinmridul** [comment]
call `flatListRef.current.scrollToEnd()` inside `onEndReached` callback of FlatList to scroll to end whenever you reach to the end because of dynamically remove any item.

Can do more optimisations to restrict calling `scrollToEnd` forcefully everytime the scroll position reaches end of list.

```
<FlatList
    ref={flatListRef}
    onEndReached={() => {
        if (Platform.OS === 'android') flatListRef.current.scrollToEnd();
    }}
/>
```
