### ISSUE TITLE
'react-native init AwesomeProject' failed. How to solve it???

### ISSUE THREAD

**Issue by jikaigit** [facebook/react-native#3662]
The system is windows 10 64bit.

The information show me is:
C:\Users\jikai\Desktop>react-native init AwesomeProject
This will walk you through creating a new React Native project in C:\Users\jikai\Desktop\AwesomeProject
Installing react-native package from npm...

> bufferutil@1.2.1 install C:\Users\jikai\Desktop\AwesomeProject\node_modules\react-native\node_modules\ws\node_modules\bufferutil
> node-gyp rebuild

C:\Users\jikai\Desktop\AwesomeProject\node_modules\react-native\node_modules\ws\node_modules\bufferutil>if not defined npm_config_node_gyp (node "D:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
�ڴ˽���������һ������һ����Ŀ����Ҫ���ò������ɣ������ӡ�/m�����ء�
MSBUILD : error MSB3428: δ�ܼ��� Visual C++ ������VCBuild.exe����Ҫ���������⣬1) ��װ .NET Framework 2.0 SDK��2) ��װ Microsoft Visual Studio 2005���� 3) ��������������װ��������λ�ã��뽫��λ�����ӵ�ϵͳ·���С� [C:\Users\jikai\Desktop\AwesomeProject\node_modules\react-native\node_modules\ws\node_modules\bufferutil\build\binding.sln]

> utf-8-validate@1.2.1 install C:\Users\jikai\Desktop\AwesomeProject\node_modules\react-native\node_modules\ws\node_modules\utf-8-validate
> node-gyp rebuild

C:\Users\jikai\Desktop\AwesomeProject\node_modules\react-native\node_modules\ws\node_modules\utf-8-validate>if not defined npm_config_node_gyp (node "D:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
�ڴ˽���������һ������һ����Ŀ����Ҫ���ò������ɣ������ӡ�/m�����ء�
MSBUILD : error MSB3428: δ�ܼ��� Visual C++ ������VCBuild.exe����Ҫ���������⣬1) ��װ .NET Framework 2.0 SDK��2) ��װ Microsoft Visual Studio 2005���� 3) ��������������װ��������λ�ã��뽫��λ�����ӵ�ϵͳ·���С� [C:\Users\jikai\Desktop\AwesomeProject\node_modules\react-native\node_modules\ws\node_modules\utf-8-validate\build\binding.sln]

> spawn-sync@1.0.13 postinstall C:\Users\jikai\Desktop\AwesomeProject\node_modules\react-native\node_modules\yeoman-generator\node_modules\cross-spawn\node_modules\spawn-sync
> node postinstall

gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\jikai\Desktop\AwesomeProject\node_modules\react-native\node_modules\ws\node_modules\bufferutil
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\jikai\Desktop\AwesomeProject\node_modules\react-native\node_modules\ws\node_modules\utf-8-validate
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN optional dep failed, continuing bufferutil@1.2.1
npm WARN optional dep failed, continuing utf-8-validate@1.2.1
npm WARN optional dep failed, continuing fsevents@1.0.2
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "react-native"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! path C:\Users\jikai\AppData\Roaming\npm-cache\code-point-at\1.0.0\package\package.json.4c2999ff403dd6144eb195aa221a6180
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename

npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\jikai\AppData\Roaming\npm-cache\code-point-at\1.0.0\package\package.json.4c2999ff403dd6144eb195aa221a6180' -> 'C:\Users\jikai\AppData\Roaming\npm-cache\code-point-at\1.0.0\package\package.json'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM: operation not permitted, rename 'C:\Users\jikai\AppData\Roaming\npm-cache\code-point-at\1.0.0\package\package.json.4c2999ff403dd6144eb195aa221a6180' -> 'C:\Users\jikai\AppData\Roaming\npm-cache\code-point-at\1.0.0\package\package.json']
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'rename',
npm ERR!   path: 'C:\\Users\\jikai\\AppData\\Roaming\\npm-cache\\code-point-at\\1.0.0\\package\\package.json.4c2999ff403dd6144eb195aa221a6180',
npm ERR!   dest: 'C:\\Users\\jikai\\AppData\\Roaming\\npm-cache\\code-point-at\\1.0.0\\package\\package.json',
npm ERR!   parent: 'string-width' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\jikai\Desktop\AwesomeProject\npm-debug.log

`npm install --save react-native` failed

**Comment by jikaigit** [comment]
Oh, I think it just because china's GFW. I open the VPN and type the command again. This time it works well.

**Comment by hufeng** [comment]
F*ck GFW.
