### ISSUE TITLE
[!] Invalid `Podfile` file: cannot load such file -- /xxx/rndemo/node_modules/@react-native-community/cli-platform-ios/native_modules.

### ISSUE THREAD

**Issue by Jairwin-L** [facebook/react-native#36639]
### Description

**first**
```bash
npx react-native init rndemo --skip-install
cd testproject
pnpm i
```
**next**
this section of the documentation to operate

<img width="683" alt="image" src="https://user-images.githubusercontent.com/32570960/227707261-219e56f2-55a5-4f47-8bf2-af11aa605c89.png">

then perform the last step above：bundle exec pod install
error occurred
<img width="1168" alt="image" src="https://user-images.githubusercontent.com/32570960/227707334-b4f5da3a-1c2d-4451-b985-3de0d3772d98.png">

but I see that officially `@react-native-community/cli` is no longer needed

### React Native Version

0.71.4

### Output of `npx react-native info`

```bash
System:
    OS: macOS 13.2
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Memory: 1.04 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.19.3 - ~/.nvm/versions/node/v14.19.3/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 6.14.17 - ~/.nvm/versions/node/v14.19.3/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.12.0 - /Users/xxx/.rvm/gems/ruby-2.7.6/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 28, 30
      Build Tools: 28.0.3, 30.0.2
      System Images: android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_281 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.4 => 0.71.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

repo：https://github.com/Jairwin-L/rndemo
```bash
git@github.com:Jairwin-L/rndemo.git
```

### Snack, code example, screenshot, or link to a repository

repo：https://github.com/Jairwin-L/rndemo
```bash
git@github.com:Jairwin-L/rndemo.git
```

**Comment by blakef** [comment]
This is a known limitation of our codegen at the moment.  There is some work to improve this happening, but you can mitigate by using yarn or npm instead of pnpm (we're actively working on resolving issues we've had with symlinks in React Native).
