### ISSUE TITLE
Building Release apk Causes Crash

### ISSUE THREAD

**Issue by humble-programmer** [facebook/react-native#36633]
### New Version

0.71

### Old Version

0.70

### Build Target(s)

Android release

### Output of `react-native info`

System:
    OS: macOS 12.3.1
    CPU: (8) arm64 Apple M1
    Memory: 95.72 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.14.2 - /opt/homebrew/opt/node@18/bin/node
    Yarn: Not Found
    npm: 9.5.0 - /opt/homebrew/opt/node@18/bin/npm
    Watchman: 2023.02.13.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 21, 23, 29, 30, 31, 32, 33
      Build Tools: 30.0.2, 30.0.3, 31.0.0, 33.0.0, 33.0.0
      System Images: android-23 | Google APIs ARM EABI v7a, android-23 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-24 | Google APIs ARM 64 v8a, android-31 | Google APIs ARM 64 v8a, android-33 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 13.3/13E113 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.12 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.4 => 0.71.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Issue and Reproduction Steps

When trying to build the release apk, the command I always use is now crashing after upgrading to version 0.71. The command is:
```./gradlew clean assembleRelease -x bundleReleaseJsAndAssets```

The error message is:
Task 'bundleReleaseJsAndAssets' not found in root project 'ProjectName'

After looking deeper, I figured out that this is happening because react.gradle has been deprecated on version 0.71. It is unclear how else I should build the release apk, because running it without the "-x bundleReleaseJsAndAssets" flag doesn't work either (I started adding the flag long ago because it was always a hassle without it).

**Comment by Neba-Emmanuel** [comment]
Basically as-is you were telling it to exclude a task that might not be part of your project.
So possibly try running this instead:

`./gradlew assembleRelease -x bundleDevReleaseJsAndAssets`

**Comment by cortinico** [comment]
> When trying to build the release apk, the command I always use is now crashing after upgrading to version 0.71. The command is:
> `./gradlew clean assembleRelease -x bundleReleaseJsAndAssets`

You should just `./gradlew assembleRelease` to create a release APK

**Comment by popejrh19** [comment]
Unsubscribe

William Pope Jr

**Comment by cortinico** [comment]
Closing as answered
