### ISSUE TITLE
Static Images wrong mapping in some devices 

### ISSUE THREAD

**Issue by iasreact1** [facebook/react-native#36647]
### Description

I used static images that are all png files and are stored within the assets folder from src that are created by me all are and then created .js file to export all the images like  `export const Im_ico_lock = require('../assets/lock.png');` and then import the Im_ico_lock file from that js file and used in `<Image source={Im_ico_lock} />` in the rendering component and it is working fine but when make apk file using 
`npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res`
then `cd android` and lastly `./gradlew assembleDebug` 
In most devices images are okay but in some devices these static images are wrongly mapped i.e, instead of lock image there is another image displayed ...not understand that please explain this behaviour was happening and please help what is the wrong and what is the  solution here to remove that problem.

### React Native Version

0.70.6

### Output of `npx react-native info`

It is the related issue of UI rendering static images that are stored in are displayed but wrongly mapped in UI in some devices.

### Steps to reproduce

when i make apk file using 
`react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res`
making an assets directory in the following src/main/ directory 
'cd android' and `./gradlew assembleDebug`
to produce the apk file and install in the devices and produce this behaviour in some of the devices 

### Snack, code example, screenshot, or link to a repository

images are exported from somewhere like `export const Im_ico_lock = require('../assets/lock.png')` after storing the .png file in assets directory and then `import {Im_ico_lock} from '../location';`
and used in `<Image  source={Im_ico_lock} />`

**Comment by iasreact1** [comment]
upgraded to the latest one already but the problem still exist please help what may be the wrong here? for that type behaviour

**Comment by efstathiosntonas** [comment]
this a problem with `Fresco`, duplicate of: https://github.com/facebook/react-native/issues/32884

only solution is to uninstall the app and reinstall.

**Comment by iasreact1** [comment]
@efstathiosntonas  i already added ` implementation 'com.facebook.fresco:animated-gif:2.5.0'` i have to upgraded it to 3.0.0 ??

**Comment by efstathiosntonas** [comment]
@iasreact1 yes but I could not make it build on rn 0.71.6 

@cortinico is there something we can do or we’ll have to wait for 0.72+? Thanks

**Comment by cortinico** [comment]
> @cortinico is there something we can do or we’ll have to wait for 0.72+? Thanks

You can manually update the Fresco version in your project to 3.x, you don't have to wait for us to do it. We won't be updating the default Fresco version till we've fully tested it and make sure there are no major regressions.

**Comment by quantiantechnologies** [comment]
Please fix this issue. fresco 3.0.0 crashseh my app
