### ISSUE TITLE
Can't turn off dark mode on android

### ISSUE THREAD

**Issue by zhenguet** [facebook/react-native#36646]
### Description

I have tried many ways to turn off (block) night mode on Android.

It's working well on some apps I have written.

[Follow this](https://github.com/facebook/react-native/issues/27876#issuecomment-707866409)

But now it's not working on my new project, in **styles.xml**
```
<!-- Base application theme. -->
  <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
    <!-- Customize your theme here. -->
    <item name="android:textColor">#4d4d4d</item>
    <item name="android:forceDarkAllowed">false</item>
  </style>
```
</application>
Does anyone have a solution for this?

### React Native Version

0.71.4

### Output of `npx react-native info`

System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Memory: 2.37 GB / 15.82 GB
  Binaries:
    Node: 16.18.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: 20220614.153706.0 - C:\ProgramData\chocolatey\bin\watchman.EXE
  SDKs:
    Android SDK:
      API Levels: 23, 27, 28, 29, 30, 31, 32, 33
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 33.0.0, 33.0.1, 34.0.0
      System Images: android-25 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom_64, android-31 | Intel x86 Atom_64, android-31 | Google APIs Intel x86 Atom_64, android-31 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: AI-213.7172.25.2113.9123335
    Visual Studio: 16.11.33423.256 (Visual Studio Professional 2019)
  Languages:
    Java: 13.0.2 - C:\Program Files\Common Files\Oracle\Java\javapath\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.4 => 0.71.4
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Init project

### Snack, code example, screenshot, or link to a repository

Init project

**Comment by cortinico** [comment]
This is a valid alternative to turn off Dark mode entirely in your app:
https://stackoverflow.com/a/57175501
