### ISSUE TITLE
/android/node_modules/react-native/ReactAndroid/gradle.properties (No such file or directory)

### ISSUE THREAD

**Issue by Sahand-Stefan** [facebook/react-native#36649]
### Description

It suddenly faced an issue on this topic
/android/node_modules/react-native/ReactAndroid/gradle.properties (No such file or directory)

### React Native Version

0.71.4

### Output of `npx react-native info`

System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M2
    Memory: 74.38 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.4.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.2.0 - /opt/homebrew/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /Users/sahandmahdavi/.rvm/gems/ruby-2.7.5/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.4 => 0.71.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

when I trigger yarn android the issue raises.

### Snack, code example, screenshot, or link to a repository

**Commented this:**
apply from: "../../node_modules/react-native/react.gradle"

**Added This:**
apply plugin: "com.facebook.react"

`* What went wrong:
A problem occurred configuring project ':app'.
> Failed to notify project evaluation listener.
   > /Users/sahandmahdavi/Documents/GitHub/letsact-app/android/node_modules/react-native/ReactAndroid/gradle.properties (No such file or directory)`

**Comment by Sahand-Stefan** [comment]
Fixed thanks.

**Comment by ceberm** [comment]
for React Native 0.72.6 I solved this issue with the above solution and also including the configuration mentioned here https://reactnative.dev/docs/react-native-gradle-plugin

**Comment by Balaji1809** [comment]
@ceberm I have done the changes mention in the docs but still i'm facing this issue. React Native - 0.73.0

**Comment by DivyatejaChe** [comment]
I am facing a similar issue too. 

I have a monorepo of two RN Apps (both running on RN 0.73.2) and a shared JS module. When I try running the first app on Android, it throws me the error - 

<img width="478" alt="Screenshot 2024-01-27 at 21 06 15" src="https://github.com/facebook/react-native/assets/54347537/a3b3e5c1-efda-44a2-8c3d-5f9a1bd51270">

Did anyone face/ solve this?

**Comment by kapobajza** [comment]
> This is how my `build.gradle` looks like (android/app)
> 
> <img alt="Screenshot 2024-01-27 at 21 11 04" width="841" src="https://private-user-images.githubusercontent.com/54347537/300187919-9ed8f969-4549-42f8-b145-24b65b7c9291.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0NjkwMTQsIm5iZiI6MTcwODQ2ODcxNCwicGF0aCI6Ii81NDM0NzUzNy8zMDAxODc5MTktOWVkOGY5NjktNDU0OS00MmY4LWIxNDUtMjRiNjViN2M5MjkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDIyMzgzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5ZjIwZGEzYzYzNWI4ODZkYjAxNzZjYTJlYzMyNzYzMTc4YTRmZGZjNTlhOTdiN2EwMDliZTI5OGY4ZmU2MGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DX_tOc7D52r7DLI5MN7V-MGgGaTNH1IqeNM141YZgVs">

@DivyatejaChe I am not sure how your folder structure looks like, but you may need to add another double dot slash:

```
reactNativeDir = file("../../../../node_modules/react-native")
codegenDir = file("../../../../node_modules/@react-native/codegen")
cliFile = file("../../../../node_modules/react-native/cli.js")
```

That's where I made a mistake, because I forgot that I am in the **android/app/build.gradle** file

**Comment by SandraBLOK** [comment]
> https://reactnative.dev/docs/react-native-gradle-plugin

You saved my day!

**Comment by SandraBLOK** [comment]
> > This is how my `build.gradle` looks like (android/app)
> > <img alt="Screenshot 2024-01-27 at 21 11 04" width="841" src="https://private-user-images.githubusercontent.com/54347537/300187919-9ed8f969-4549-42f8-b145-24b65b7c9291.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0NjkwMTQsIm5iZiI6MTcwODQ2ODcxNCwicGF0aCI6Ii81NDM0NzUzNy8zMDAxODc5MTktOWVkOGY5NjktNDU0OS00MmY4LWIxNDUtMjRiNjViN2M5MjkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDIyMzgzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5ZjIwZGEzYzYzNWI4ODZkYjAxNzZjYTJlYzMyNzYzMTc4YTRmZGZjNTlhOTdiN2EwMDliZTI5OGY4ZmU2MGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DX_tOc7D52r7DLI5MN7V-MGgGaTNH1IqeNM141YZgVs">
> 
> @DivyatejaChe I am not sure how your folder structure looks like, but you may need to add another double dot slash:
> 
> ```
> reactNativeDir = file("../../../../node_modules/react-native")
> codegenDir = file("../../../../node_modules/@react-native/codegen")
> cliFile = file("../../../../node_modules/react-native/cli.js")
> ```
> 
> That's where I made a mistake, because I forgot that I am in the **android/app/build.gradle** file and not in **android/build.gradle** 😅

You saved my day!

**Comment by trungaioz30** [comment]
I also have the same problem
* Where:
Build file 'E:\aiozswap\apps\interface\android\build.gradle' line: 21

* What went wrong:
A problem occurred evaluating root project 'aiozswapapp'.
> Failed to apply plugin 'com.facebook.react.rootproject'.
   > A problem occurred configuring project ':app'.
      > Failed to notify project evaluation listener.
         > E:\aiozswap\apps\interface\node_modules\react-native\ReactAndroid\gradle.properties (The system cannot find the path specified)
         
with settings.gradle using monorepo was hoisted module to root folder:
pluginManagement { includeBuild("../../../node_modules/@react-native/gradle-plugin") }
plugins { id("com.facebook.react.settings") }
extensions.configure(com.facebook.react.ReactSettingsExtension){ ex -> ex.autolinkLibrariesFromCommand() }
rootProject.name = 'aiozswapapp'
include ':app'
includeBuild('../../../node_modules/@react-native/gradle-plugin')

metro.config.js:
`const { getDefaultConfig, mergeConfig } = require('@react-native/metro-config')
const { FileStore } = require('metro-cache')
const path = require('node:path')
const { wrapWithReanimatedMetroConfig } = require('react-native-reanimated/metro-config')

const projectRoot = __dirname
const workspaceRoot = path.resolve(projectRoot, '../..')

const configRoot = getDefaultConfig(projectRoot)

configRoot.watchFolders = [workspaceRoot]
configRoot.resolver.nodeModulesPaths = [
  path.resolve(projectRoot, 'node_modules'),
  path.resolve(workspaceRoot, 'node_modules'),
]

configRoot.cacheStores = [new FileStore({ root: path.join(projectRoot, 'node_modules', '.cache', 'metro') })]

/**
 * Metro configuration
 * https://reactnative.dev/docs/metro
 *
 * @type {import('metro-config').MetroConfig}
 */
const config = {}

module.exports = mergeConfig(configRoot, wrapWithReanimatedMetroConfig(configRoot))
`

**Comment by hoangtrung03** [comment]
I also have the same problem

* Where:
Build file 'E:\project\apps\interface\android\build.gradle' line: 21

* What went wrong:
A problem occurred evaluating root project 'project'.
> Failed to apply plugin 'com.facebook.react.rootproject'.
   > A problem occurred configuring project ':app'.
      > Failed to notify project evaluation listener.
         > E:\project\apps\interface\node_modules\react-native\ReactAndroid\gradle.properties (The system cannot find the path specified)
         
settings.gradle:
```
pluginManagement { includeBuild("../../../node_modules/@react-native/gradle-plugin") }
plugins { id("com.facebook.react.settings") }
extensions.configure(com.facebook.react.ReactSettingsExtension){ ex -> ex.autolinkLibrariesFromCommand() }
rootProject.name = 'project'
include ':app'
includeBuild('../../../node_modules/@react-native/gradle-plugin')
```

metro.config.js:
```
const { getDefaultConfig, mergeConfig } = require('@react-native/metro-config')
const { FileStore } = require('metro-cache')
const path = require('node:path')
const { wrapWithReanimatedMetroConfig } = require('react-native-reanimated/metro-config')

const projectRoot = __dirname
const workspaceRoot = path.resolve(projectRoot, '../..')

const configRoot = getDefaultConfig(projectRoot)

configRoot.watchFolders = [workspaceRoot]
configRoot.resolver.nodeModulesPaths = [
  path.resolve(projectRoot, 'node_modules'),
  path.resolve(workspaceRoot, 'node_modules'),
]

configRoot.cacheStores = [new FileStore({ root: path.join(projectRoot, 'node_modules', '.cache', 'metro') })]

/**
 * Metro configuration
 * https://reactnative.dev/docs/metro
 *
 * @type {import('metro-config').MetroConfig}
 */
const config = {}

module.exports = mergeConfig(configRoot, wrapWithReanimatedMetroConfig(configRoot))

```
