### ISSUE TITLE
[Layout] How can I get height of text or how to converts a font size to layout size (dp)?

### ISSUE THREAD

**Issue by LeoJiaXin** [facebook/react-native#3665]
I wanna to make this:
![2015-10-25 19 26 39](https://cloud.githubusercontent.com/assets/7020278/10715334/6db7558e-7b4e-11e5-95ce-c63feb582686.png)

**Question**
--------------
the `borderRadius` must be half of the height of `View` whose `backgroundColor` is white.(call it `White View`). But I use the default `fontSize` and I don't know how to get the height of my `White View`

**My solution**
----------------------
> * implement `onLayout` of `White View` .(`borderRadius` is unknown ,set it to 0)
* get height of `White View` in `onLayout` .(so I get `borderRadius` now)
* then call `forceUpdate` of `White View` .

**Help**
--------------------
Am I right? Is there any awesome ways to achieve this?
By the way, the platform is Android

**Comment by ide** [comment]
Using onLayout is the best approach now.

Instead of view.forceUpdate you should call this.setState in on your component that owns the white view. (That is how to use react in general and is not specific to react native.)
