### ISSUE TITLE
Execution failed for task ':app:bundleReleaseJsAndAssets'. > Process 'command 'node'' finished with non-zero exit value 1

### ISSUE THREAD

**Issue by Garrysahota** [facebook/react-native#36660]
### Description

Configure project :react-native-reanimated
AAR for react-native-reanimated has been found
/Users/garry/Desktop/ALL APP PROJECTS/gtc-app-demo/node_modules/react-native-reanimated/android/react-native-reanimated-70-jsc.aar

> Task :app:bundleReleaseJsAndAssets FAILED
warning: the transform cache was reset.
                Welcome to Metro v0.72.3
              Fast - Scalable - Integrated

2023-03-27T21:32:32,600: [] the owner of /opt/homebrew/var/run/watchman/root-state is uid 501 and doesn't match your euid 0

Watchman:  watchman --no-pretty get-sockname returned with exit code=1, signal=null, stderr= 2023-03-27T21:32:32,600: [] the owner of /opt/homebrew/var/run/watchman/root-state is uid 501 and doesn't match your euid 0

node:events:490
      throw er; // Unhandled 'error' event
      ^

Error: watchman --no-pretty get-sockname returned with exit code=1, signal=null, stderr= 2023-03-27T21:32:32,600: [] the owner of /opt/homebrew/var/run/watchman/root-state is uid 501 and doesn't match your euid 0

    at ChildProcess.<anonymous> (/Users/garry/Desktop/ALL APP PROJECTS/gtc-app-demo/node_modules/fb-watchman/index.js:203:18)
    at ChildProcess.emit (node:events:512:28)
    at maybeClose (node:internal/child_process:1098:16)
    at Socket.<anonymous> (node:internal/child_process:456:11)
    at Socket.emit (node:events:512:28)
    at Pipe.<anonymous> (node:net:332:12)
Emitted 'error' event on Client instance at:
    at spawnError (/Users/garry/Desktop/ALL APP PROJECTS/gtc-app-demo/node_modules/fb-watchman/index.js:174:10)
    at ChildProcess.<anonymous> (/Users/garry/Desktop/ALL APP PROJECTS/gtc-app-demo/node_modules/fb-watchman/index.js:203:7)
    at ChildProcess.emit (node:events:512:28)
    [... lines matching original stack trace ...]
    at Pipe.<anonymous> (node:net:332:12)

Node.js v19.8.1

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:bundleReleaseJsAndAssets'.
> Process 'command 'node'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 21s
6 actionable tasks: 1 executed, 5 up-to-date

### React Native Version

0.70.5

### Output of `npx react-native info`

gtc-app-demo git:(garry) ✗ npx react-native info
info Fetching system and libraries information...
System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1
    Memory: 136.25 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.8.1 - /opt/homebrew/bin/node
    Yarn: Not Found
    npm: 9.5.1 - /opt/homebrew/bin/npm
    Watchman: 2023.03.27.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 30, 31, 32, 33, 33
      Build Tools: 19.1.0, 20.0.0, 21.1.2, 22.0.1, 23.0.1, 23.0.2, 23.0.3, 24.0.0, 24.0.1, 24.0.2, 24.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.1, 27.0.2, 27.0.3, 28.0.0, 28.0.1, 28.0.2, 28.0.3, 29.0.0, 29.0.1, 29.0.2, 29.0.3, 30.0.0, 30.0.1, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0, 33.0.1, 33.0.2, 34.0.0, 34.0.0
      System Images: android-30 | Android TV Intel x86 Atom, android-30 | China version of Wear OS 3 - Preview ARM 64 v8a, android-30 | China version of Wear OS 3 - Preview Intel x86 Atom, android-30 | Wear OS 3 ARM 64 v8a, android-30 | Wear OS 3 Intel x86 Atom, android-30 | AOSP ATD ARM 64 v8a, android-30 | AOSP ATD Intel x86 Atom, android-30 | ARM 64 v8a, android-30 | Intel x86_64 Atom, android-30 | Google TV Intel x86 Atom, android-30 | Google APIs ARM 64 v8a, android-30 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86_64 Atom, android-30 | Google Play ARM 64 v8a, android-30 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86_64 Atom, android-30 | Google APIs ATD ARM 64 v8a, android-30 | Google APIs ATD Intel x86 Atom, android-33 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.18 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.5 => 0.70.5 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

sudo ./gradlew clean
Password:
Starting a Gradle Daemon (subsequent builds will be faster)

> Task :react-native-gradle-plugin:compileKotlin
w: /Users/garry/Desktop/ALL APP PROJECTS/gtc-app-demo/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/ReactExtension.kt: (10, 37): 'BaseVariant' is deprecated. Deprecated in Java
w: /Users/garry/Desktop/ALL APP PROJECTS/gtc-app-demo/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/ReactExtension.kt: (119, 30): 'BaseVariant' is deprecated. Deprecated in Java
w: /Users/garry/Desktop/ALL APP PROJECTS/gtc-app-demo/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/ReactExtension.kt: (135, 26): 'BaseVariant' is deprecated. Deprecated in Java
w: /Users/garry/Desktop/ALL APP PROJECTS/gtc-app-demo/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/ReactExtension.kt: (157, 32): 'BaseVariant' is deprecated. Deprecated in Java
w: /Users/garry/Desktop/ALL APP PROJECTS/gtc-app-demo/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/ReactExtension.kt: (163, 31): 'BaseVariant' is deprecated. Deprecated in Java
w: /Users/garry/Desktop/ALL APP PROJECTS/gtc-app-demo/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/ReactExtension.kt: (171, 36): 'BaseVariant' is deprecated. Deprecated in Java
w: /Users/garry/Desktop/ALL APP PROJECTS/gtc-app-demo/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/ReactPlugin.kt: (114, 48): 'reactRoot: DirectoryProperty' is deprecated. reactRoot was confusing and has been replace with root to point to your root project and reactNativeDir to point to the folder of the react-native NPM package
w: /Users/garry/Desktop/ALL APP PROJECTS/gtc-app-demo/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/TaskConfiguration.kt: (10, 37): 'ApplicationVariant' is deprecated. Deprecated in Java
w: /Users/garry/Desktop/ALL APP PROJECTS/gtc-app-demo/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/TaskConfiguration.kt: (11, 37): 'BaseVariant' is deprecated. Deprecated in Java
w: /Users/garry/Desktop/ALL APP PROJECTS/gtc-app-demo/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/TaskConfiguration.kt: (12, 37): 'LibraryVariant' is deprecated. Deprecated in Java
w: /Users/garry/Desktop/ALL APP PROJECTS/gtc-app-demo/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/TaskConfiguration.kt: (27, 51): 'BaseVariant' is deprecated. Deprecated in Java
w: /Users/garry/Desktop/ALL APP PROJECTS/gtc-app-demo/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/TaskConfiguration.kt: (130, 12): 'ApplicationVariant' is deprecated. Deprecated in Java
w: /Users/garry/Desktop/ALL APP PROJECTS/gtc-app-demo/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/TaskConfiguration.kt: (131, 12): 'LibraryVariant' is deprecated. Deprecated in Java
w: /Users/garry/Desktop/ALL APP PROJECTS/gtc-app-demo/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/TaskConfiguration.kt: (251, 14): 'BaseVariant' is deprecated. Deprecated in Java

> Configure project :expo-application
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-barcode-scanner
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-clipboard
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-constants
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-error-recovery
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-file-system
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-font
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-haptics
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-image-loader
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-keep-awake
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-local-authentication
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-modules-core
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.
C/C++: Could not execute cmake at '/Users/garry/Library/Android/sdk' to get version. Skipping.
C/C++: Could not execute cmake at '/Users/garry/Library/Android/sdk' to get version. Skipping.
WARNING:C/C++: Could not execute cmake at '/Users/garry/Library/Android/sdk' to get version. Skipping.
C/C++: Could not execute cmake at '/Users/garry/Library/Android/sdk' to get version. Skipping.
WARNING:C/C++: Could not execute cmake at '/Users/garry/Library/Android/sdk' to get version. Skipping.
C/C++: Could not execute cmake at '/Users/garry/Library/Android/sdk' to get version. Skipping.

> Configure project :expo-splash-screen
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo

Using expo modules
  - expo-application (5.0.1)
  - expo-barcode-scanner (12.1.0)
  - expo-clipboard (4.0.2)
  - expo-constants (14.0.2)
  - expo-error-recovery (4.0.1)
  - expo-file-system (15.1.1)
  - expo-font (11.0.1)
  - expo-haptics (12.0.1)
  - expo-image-loader (4.0.0)
  - expo-keep-awake (11.0.1)
  - expo-local-authentication (13.0.2)
  - expo-modules-core (1.1.1)
  - expo-splash-screen (0.17.5)

WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :react-native-reanimated
AAR for react-native-reanimated has been found
/Users/garry/Desktop/ALL APP PROJECTS/gtc-app-demo/node_modules/react-native-reanimated/android/react-native-reanimated-70-jsc.aar

The Kotlin Gradle plugin was loaded multiple times in different subprojects, which is not supported and may break the build. 
This might happen in subprojects that apply the Kotlin plugins with the Gradle 'plugins { ... }' DSL if they specify explicit versions, even if the versions are equal.
Please add the Kotlin plugin to the common parent project or the root project, then remove the versions in the subprojects.
If the parent project does not need the plugin, add 'apply false' to the plugin line.
See: https://docs.gradle.org/current/userguide/plugins.html#sec:subprojects_plugins_dsl
The Kotlin plugin was loaded in the following projects: ':expo', ':expo-modules-core'

The Kotlin Gradle plugin was loaded multiple times in different subprojects, which is not supported and may break the build. 
This might happen in subprojects that apply the Kotlin plugins with the Gradle 'plugins { ... }' DSL if they specify explicit versions, even if the versions are equal.
Please add the Kotlin plugin to the common parent project or the root project, then remove the versions in the subprojects.
If the parent project does not need the plugin, add 'apply false' to the plugin line.
See: https://docs.gradle.org/current/userguide/plugins.html#sec:subprojects_plugins_dsl
The Kotlin plugin was loaded in the following projects: ':react-native-gesture-handler', ':react-native-screens'

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 22s
33 actionable tasks: 8 executed, 25 up-to-date
➜  android git:(garry) ✗ sudo ./gradlew assembleRelease

> Configure project :expo-application
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-barcode-scanner
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-clipboard
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-constants
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-error-recovery
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-file-system
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-font
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-haptics
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-image-loader
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-keep-awake
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-local-authentication
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-modules-core
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.
C/C++: Could not execute cmake at '/Users/garry/Library/Android/sdk' to get version. Skipping.
C/C++: Could not execute cmake at '/Users/garry/Library/Android/sdk' to get version. Skipping.
WARNING:C/C++: Could not execute cmake at '/Users/garry/Library/Android/sdk' to get version. Skipping.
C/C++: Could not execute cmake at '/Users/garry/Library/Android/sdk' to get version. Skipping.
WARNING:C/C++: Could not execute cmake at '/Users/garry/Library/Android/sdk' to get version. Skipping.
C/C++: Could not execute cmake at '/Users/garry/Library/Android/sdk' to get version. Skipping.

> Configure project :expo-splash-screen
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo

Using expo modules
  - expo-application (5.0.1)
  - expo-barcode-scanner (12.1.0)
  - expo-clipboard (4.0.2)
  - expo-constants (14.0.2)
  - expo-error-recovery (4.0.1)
  - expo-file-system (15.1.1)
  - expo-font (11.0.1)
  - expo-haptics (12.0.1)
  - expo-image-loader (4.0.0)
  - expo-keep-awake (11.0.1)
  - expo-local-authentication (13.0.2)
  - expo-modules-core (1.1.1)
  - expo-splash-screen (0.17.5)

WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :react-native-reanimated
AAR for react-native-reanimated has been found
/Users/garry/Desktop/ALL APP PROJECTS/gtc-app-demo/node_modules/react-native-reanimated/android/react-native-reanimated-70-jsc.aar

> Task :app:bundleReleaseJsAndAssets FAILED
warning: the transform cache was reset.
                Welcome to Metro v0.72.3
              Fast - Scalable - Integrated

2023-03-27T21:32:32,600: [] the owner of /opt/homebrew/var/run/watchman/root-state is uid 501 and doesn't match your euid 0

Watchman:  watchman --no-pretty get-sockname returned with exit code=1, signal=null, stderr= 2023-03-27T21:32:32,600: [] the owner of /opt/homebrew/var/run/watchman/root-state is uid 501 and doesn't match your euid 0

node:events:490
      throw er; // Unhandled 'error' event
      ^

Error: watchman --no-pretty get-sockname returned with exit code=1, signal=null, stderr= 2023-03-27T21:32:32,600: [] the owner of /opt/homebrew/var/run/watchman/root-state is uid 501 and doesn't match your euid 0

    at ChildProcess.<anonymous> (/Users/garry/Desktop/ALL APP PROJECTS/gtc-app-demo/node_modules/fb-watchman/index.js:203:18)
    at ChildProcess.emit (node:events:512:28)
    at maybeClose (node:internal/child_process:1098:16)
    at Socket.<anonymous> (node:internal/child_process:456:11)
    at Socket.emit (node:events:512:28)
    at Pipe.<anonymous> (node:net:332:12)
Emitted 'error' event on Client instance at:
    at spawnError (/Users/garry/Desktop/ALL APP PROJECTS/gtc-app-demo/node_modules/fb-watchman/index.js:174:10)
    at ChildProcess.<anonymous> (/Users/garry/Desktop/ALL APP PROJECTS/gtc-app-demo/node_modules/fb-watchman/index.js:203:7)
    at ChildProcess.emit (node:events:512:28)
    [... lines matching original stack trace ...]
    at Pipe.<anonymous> (node:net:332:12)

Node.js v19.8.1

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:bundleReleaseJsAndAssets'.
> Process 'command 'node'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 21s
6 actionable tasks: 1 executed, 5 up-to-date

### Snack, code example, screenshot, or link to a repository

please help...

**Comment by cortinico** [comment]
> Configure project :react-native-reanimated

Hi @Garrysahota 
Thanks for reporting this issue.

It seems like this issue is actually unrelated to React Native core but related to Reanimated. Please open this issue against this other repository:

https://github.com/software-mansion/react-native-reanimated/issues

I'll be closing this but feel free to reopen if the other repo points back to us as a issue in the core of React Native.

**Comment by RushitaRn25** [comment]
Execution failed for task ':app:createBundleDevDebugJsAndAssets'.
> Process 'command 'node'' finished with non-zero exit value 1
