### ISSUE TITLE
App crashing when load list of more than 200 items in scroll view in iOS.

### ISSUE THREAD

**Issue by RutvinBhanderi** [facebook/react-native#36674]
### Description

when load or render more than 200 items in scroll view then the app is crashing in physical iOS device but in simulator it is working fine. I have tried lazy loading but that is also not working. I tried  to load first 20 items then based on scrolling it render more items but it is blocking the ui thread but then  app got stuck. want some help to load data in background without blocking ui thread.

### React Native Version

0.69.4

### Output of `npx react-native info`

System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1
    Memory: 75.86 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.0.1 - /opt/homebrew/bin/node
    Yarn: Not Found
    npm: 8.19.2 - /opt/homebrew/bin/npm
    Watchman: 2022.11.07.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9514443
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.18 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.4 => 0.69.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. i am using @gorhom/bottom-sheet.
2. Inside I am using scroll view
3. when load more items it is crashing in iOS.

### Snack, code example, screenshot, or link to a repository

![Simulator Screen Shot - iPhone 14 Pro Max - 2023-03-28 at 11 14 55](https://user-images.githubusercontent.com/86949269/228139799-ff100e7d-aca8-4a57-ab53-b3a8c7572721.png)

**Comment by efstathiosntonas** [comment]
why not using `Flatlist` or `FlashList` and `numColumns={3}`?

**Comment by RutvinBhanderi** [comment]
> why not using `Flatlist` or `FlashList` and `numColumns={3}`?

Thank you!!.I was not aware of FlashList. I will try. In FlatList also if there is more items then  sometimes it blocks the ui thread.
