### ISSUE TITLE
onTextLayout returns different values for Android and iOS

### ISSUE THREAD

**Issue by khamui** [facebook/react-native#36675]
### Description

When retrieving the number of `lines` with the `onTextLayout` as
suggested in the docs (https://reactnative.dev/docs/text#textlayoutevent)

The number of lines returned are different for Android and iOS.
For Android (emulator: Pixel 5) it returns 6 lines
And for iOS (simulator: Iphone 12 Pro) it returns 2 lines.

### React Native Version

0.71.4

### Output of `npx react-native info`

System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 710.13 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.14.0 - ~/.nvm/versions/node/v18.14.0/bin/node
    Yarn: Not Found
    npm: 9.3.1 - ~/.nvm/versions/node/v18.14.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9514443
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.4 => 0.71.4
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1.) Adding a `<Text>` component with a longer text
2.) Writing a handler for the onTextLayout event of that `<Text>`
3.) Console.log the returned object
4.) Boot up Android
5.) Boot up Simulator
6.) Compare console.logs

### Snack, code example, screenshot, or link to a repository

```
  const onTextLayout = useCallback(e => {
    console.log('LINES', e.nativeEvent.lines.length)
  }, [])
```

**Comment by khamui** [comment]
Making `numberOfLines` dynamic seems to fix this issue. Two snippets to show what worked and what did not.

❌ This did not work as expected for iOS
```
  <TextSourceSans
    numberOfLines={2}
    onTextLayout={({nativeEvent: ne}) => setLines(ne.lines)}
  >
      some text
  </Text>
```

✅ This works for both platforms:
```
  const LIMIT_NUM = 2
  ...
  const [numOfLines, setNumOfLines] = useState(0)
  ...
  
  <TextSourceSans
    numberOfLines={numOfLines}
    onTextLayout={({nativeEvent: ne}) => {
        setNumOfLines(LIMIT_NUM)
        setLines(ne.lines)
   }
  >
      some text
  </Text>
```

Nevertheless Android and iOS are returning different values if `numOfLines` is already defined on mount. I think this should be returning the same value. Closing as this is not a blocking issue!

**Comment by sbouchard-stratejia** [comment]
> Making `numberOfLines` dynamic seems to fix this issue. Two snippets to show what worked and what did not.
> 
> ❌ This did not work as expected for iOS
> 
> ```
>   <Text
>     numberOfLines={2}
>     onTextLayout={({nativeEvent: ne}) => setLines(ne.lines)}
>   >
>       some text
>   </Text>
> ```
> 
> ✅ This works for both platforms:
> 
> ```
>   const LIMIT_NUM = 2
>   ...
>   const [numOfLines, setNumOfLines] = useState(0)
>   ...
>   
>   <Text
>     numberOfLines={numOfLines}
>     onTextLayout={({nativeEvent: ne}) => {
>         setNumOfLines(LIMIT_NUM)
>         setLines(ne.lines)
>    }
>   >
>       some text
>   </Text>
> ```
> 
> Nevertheless Android and iOS are returning different values if `numOfLines` is already defined on mount. I think this should be returning the same value. Closing as this is not a blocking issue!

The problem with this solution is that there is a short timespan where the Text render with a numberOfLines of 0(so the text render fully). This is noticeable, the text render fully then shrink and the ViewMore button appears after that, do you know of a solution where we dont have to put an inital numOfLines of 0?

**Comment by singh-026** [comment]
@sbouchard-stratejia  the above solution is not working , idk how it's running on your device ....
do you know any alternative to this ?

**Comment by alesdvorakcz** [comment]
It looks like ios respects numOfLines and does not return more items in the array. However android returns all lines even when they are not visible due ellipsis. It would be nice to have same behaviour on ios too, because it can be used to detect ellipsis...

**Comment by falk-stefan** [comment]
Looks like this is still not resolved?

**Comment by artur-burlak** [comment]
Still not resolved. If you want to have dynamic `numberOfLines`, it works only on iOS, when the text container is `flex: 1` and is cut by View. 
For Android it returns full lines like it's not cut. 

Workaround: define numberOfLines by wrapping the text with View, get it height from onLayout and then calculate it. 

`const numberOfLines = viewHeight / lineHeight `

**Comment by tranguv** [comment]
This issue is still not resolved
