### ISSUE TITLE
iOS: Linking not working with mailto when subject or body has spaces or quotes

### ISSUE THREAD

**Issue by ale917k** [facebook/react-native#36680]
### Description

We're using `Linking` to allow users to open pre-filled emails from the mobile app. 

On `react-native@0.67.5` it was just working fine with the below code:
```js
import { Linking } from "react-native";

const subject = "Hello!"
const body = "Hello World"

Linking.openURL(
  `mailto:feedback@company.com?subject=${subject}&body=${body}`,
)
```

We recently upgraded the project to latest version (`0.71.4`), and the functionality no longer works. This seems to happen whenever either the "subject" or "body" contains any space or quote (same fails when trying to add spaces with `\s`).

I've added the code on `AppDelegate.mm` to enable Deep Links on iOS as defined [here](https://reactnative.dev/docs/linking#enabling-deep-links):
```objective-c
#import <React/RCTLinkingManager.h>

// Listen to incoming app links during app's execution, iOS 9.x or newer
- (BOOL)application:(UIApplication *)application
   openURL:(NSURL *)url
   options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{
  return [RCTLinkingManager application:application openURL:url options:options];
}

// Enable Universal links
- (BOOL)application:(UIApplication *)application continueUserActivity:(nonnull NSUserActivity *)userActivity
 restorationHandler:(nonnull void (^)(NSArray<id<UIUserActivityRestoring>> * _Nullable))restorationHandler
{
 return [RCTLinkingManager application:application
                  continueUserActivity:userActivity
                    restorationHandler:restorationHandler];
}
```
After the above changes, if we check whether the link can be opened with `Linking.canOpenURL`, it'd still fail with:
> Error opening URL: [Error: Unable to open URL: file:///private/var/containers/Bundle/Application/457E6674-DA77-4676-A2CF-3F21C9572B57/... Add file to LSApplicationQueriesSchemes in your Info.plist.]

So after doing the final tweak on info.plist, 
```xml
<key>LSApplicationQueriesSchemes</key>
<array>
  <string>file</string>
</array>
```
the error would now no longer appear, but at the same time `Linking.canOpenURL` would still return `false` every time, regardless of whether the device can actually support the url or not (I have the Mail app installed on the device, and yet I only get `false`; It works just fine after removing the spaces from the `subject` and `body` on the email to compose).

### React Native Version

0.71.4

### Output of `npx react-native info`

```
System:
  OS: macOS 13.2.1
  CPU: (10) arm64 Apple M1 Pro
  Memory: 542.67 MB / 16.00 GB
  Shell: 5.8.1 - /bin/zsh
Binaries:
  Node: 19.7.0 - /usr/local/bin/node
  Yarn: 1.22.19 - /opt/homebrew/bin/yarn
  npm: 9.5.0 - /opt/homebrew/bin/npm
  Watchman: 2023.02.13.00 - /opt/homebrew/bin/watchman
Managers:
  CocoaPods: 1.12.0 - /var/folders/xz/4k_9k8bd3z71087z867ns7tc0000gn/T/frum_68587_1680009253739/bin/pod
SDKs:
  iOS SDK:
    Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
  Android SDK: Not Found
IDEs:
  Android Studio: 2021.2 AI-212.5712.43.2112.8609683
  Xcode: 14.2/14C18 - /usr/bin/xcodebuild
Languages:
  Java: 11.0.17 - /usr/bin/javac
npmPackages:
  @react-native-community/cli: Not Found
  react: 18.2.0 => 18.2.0 
  react-native: 0.71.4 => 0.71.4 
  react-native-macos: Not Found
npmGlobalPackages:
  *react-native*: Not Found
```

### Steps to reproduce

1. Clone public repo with simplest reproducible example: `git clone https://github.com/ale917k/RNMailLink` (It's an empty project created only to allow for reproducing the bug; Initialised with `npx react-native@latest init RNMailLink`)
2. `App.tsx` only returns a button that when clicked will try to open the email with subject and body. Because the body has a space, `Linking.canOpenURL` will deem the link unsupported. If you try to directly call `Linking.openURL`, it'll fail altogether with an error.

### Snack, code example, screenshot, or link to a repository

https://github.com/ale917k/RNMailLink

**Comment by dotsenko** [comment]
To fix it problem you can wrap your subject and body in encodeURIComponent to replace the space to %20.

**Comment by braandl** [comment]
Which is imho the same for almost all protocol based email [etc] handling, not only within react-native, since you can always only transfer valid URIs.
