### ISSUE TITLE
Fabric Component: Can't call native method on iOS via Native Commands

### ISSUE THREAD

**Issue by damianzdunekgecko** [facebook/react-native#36684]
### Description

I created the RTNCenteredText Fabric native component based on [this page](https://reactnative.dev/docs/the-new-architecture/pillars-fabric-components). Additionally this component implements native command named `trigger`. The method was created according to the information available [here](https://reactnative.dev/docs/new-architecture-library-intro#migrating-off-dispatchviewmanagercommand). 

While `trigger` method works fine on Android (it's possible to catch its call via `receiveCommand` method of the `CenteredTextManager` class), it doesn't work on iOS.

Possibly I miss an important detail or just misunderstand the concept of calling native methods of Fabric components, so I'd be grateful for any help.

### React Native Version

0.71.4

### Output of `npx react-native info`

```
System:
    OS: macOS 13.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 83.18 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.6.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.0 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9619390
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.4 => 0.71.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1. Clone the [repository](https://github.com/damianzdunekgecko/RNNewArchitectureNativeCommands).
2. Open the terminal and navigate to the `NewArchitectureIOSIssue` directory.
3. Execute 'npm install' command.
4. Navigate to the `NewArchitectureIOSIssue/ios` directory.
5. Run `bundle install && RCT_NEW_ARCH_ENABLED=1 bundle exec pod install`
6. Run app via XCode to be able to see all logs in the console.
7. When app runs, click the `Trigger native method` button.

**Expected result**

Below logs should be printed by the app:
```
*** Fabric component initWithFrame
*** Fabric component updateProps
[javascript] [*** Capturing reference ref: [object Object] this.ref: undefined
[javascript] [*** Capturing reference ref: [object Object] this.ref: [object Object]
*** Fabric component updateProps
[javascript] [*** Trigger native method
[javascript] [*** Reference is not null [object Object]
*** Native method triggered via Manager
```
or
```
*** Fabric component initWithFrame
*** Fabric component updateProps
[javascript] [*** Capturing reference ref: [object Object] this.ref: undefined
[javascript] [*** Capturing reference ref: [object Object] this.ref: [object Object]
*** Fabric component updateProps
[javascript] [*** Trigger native method
[javascript] [*** Reference is not null [object Object]
*** Fabric component trigger method called directly
```

**Actual result**

App logs:
```
*** Fabric component initWithFrame
*** Fabric component updateProps
[javascript] [*** Capturing reference ref: [object Object] this.ref: undefined
[javascript] [*** Capturing reference ref: [object Object] this.ref: [object Object]
*** Fabric component updateProps
[javascript] [*** Trigger native method
[javascript] [*** Reference is not null [object Object]
```

### Snack, code example, screenshot, or link to a repository

The applied approach is using the `RCT_EXPORT_METHOD` macro in `RTNCenteredTextManager`, like:

```
RCT_EXPORT_METHOD(trigger:(nonnull NSNumber *)reactTag) {
    NSLog(@"*** Native method triggered");
}
```

Also `RTNCenteredText` implements the `trigger` method but it doesn't work either, like:

```
- (void)trigger {
    NSLog(@"*** Fabric component trigger called directly");
}
```

Please see my [repository](https://github.com/damianzdunekgecko/RNNewArchitectureNativeCommands) reproducing the issue.

**Comment by carlosalmonte04** [comment]
Looks like the docs are missing calling native methods of Fabric components.

**Comment by damianzdunekgecko** [comment]
Thank you, @carlosalmonte04 - it works like a charm. Indeed it would be nice if documentation will show handling commands within native Java/Obj-C code.
