### ISSUE TITLE
Unable to fetch data from non SSL verified host

### ISSUE THREAD

**Issue by SubramanyaKS** [facebook/react-native#36691]
### Description

> Fetching data from Non SSL verified host is giving network error 

### React Native Version

0.71.3

### Output of `npx react-native info`

OS: Windows 10 10.0.22
Node: 16.17.0
npm: 8.15.0
Java: 17.06
react: 18.2.0
react-native: 0.71.3

### Steps to reproduce

1. run the react-native using npm run
2. after fetching it is giving this issue

### Snack, code example, screenshot, or link to a repository

const res=fetch(<url without ssl>);

**Comment by Tyson39** [comment]
No se puede
