### ISSUE TITLE
Appearance.getColorScheme() return wrong color schema for when call first time only in ios

### ISSUE THREAD

**Issue by thtRajasthaniGuy** [facebook/react-native#36713]
### Description

Appearance.getColorScheme() rerturn wrong color schema when app come from background to foreground mode everytime.

https://user-images.githubusercontent.com/33393692/228739284-23707b9f-73ad-410c-b7e3-c8d53fc029ff.mp4

### React Native Version

0.70.6

### Output of `npx react-native info`

System:
    OS: macOS 13.1
    CPU: (8) x64 Intel(R) Core(TM) i5-1030NG7 CPU @ 1.10GHz
    Memory: 98.94 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.11.0 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.10.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.6 => 0.70.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

minimize the app from background to foreground.

### Snack, code example, screenshot, or link to a repository

                 import {Appearance, useColorScheme} from 'react-native';
                console.log(' Appearance.getColorScheme()', Appearance.getColorScheme());

**Comment by effektsvk** [comment]
I can confirm that this is happening on RN 0.71.7 and according to changelog it's not fixed in 0.71.8 either.

**Comment by YaoHuiJi** [comment]
It happens on RN 0.72.0 too

**Comment by haikov** [comment]
Just adding that `useColorScheme` hook is also affected by the same issue. When the system is in the dark mode, it returns `light` on the first render followed up by correct `dark` value.

**Comment by Robert27** [comment]
Happens to me after upgrading to RN version 0.74

**Comment by DanielKuhn** [comment]
Happening for me as well: only on first start (after fresh install of the app) `useColorScheme` returns light. Works fine later (manual or auto-switching theme is handled correctly)

**Comment by BrianAutomatize** [comment]
Updating react-native from 71.6 to 74.0, now 74.0 causes useColorScheme() and Appearance.getColorScheme() to always be 'light' when app first loads.
Happening only on ios first load of app, will recognize changes but everytime open ios app it is 'light' irregardless of settings.

Output of npx react-native info
System:
  OS: macOS 14.6.1
  CPU: (10) arm64 Apple M1 Max
  Memory: 1.74 GB / 64.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.16.0
    path: ~/.nvm/versions/node/v18.16.0/bin/node
  Yarn:
    version: 3.6.0
    path: ~/.nvm/versions/node/v18.16.0/bin/yarn
  npm:
    version: 9.5.1
    path: ~/.nvm/versions/node/v18.16.0/bin/npm
  Watchman:
    version: 2024.08.05.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.18034.62.2411.12071903
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.11
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.74.0
    wanted: 0.74.0
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

**Comment by rajatkantinandi** [comment]
This is still happening on RN 0.76.7 when running in the new architecture.
One workaround I am using is keeping track of app state and only allow changing color scheme when app is in foreground:

```tsx
  const colorSchemeFromRN = useColorScheme();
  const [systemColorScheme, setSystemColorScheme] = useState<ColorSchemeName>(colorSchemeFromRN);
  const [isAppActive, setIsAppActive] = useState(false);

  useEffect(() => {
    const subscription = AppState.addEventListener('change', (state) => {
      setIsAppActive(state === 'active');
    });

    return () => subscription.remove();
  }, []);

  useEffect(() => {
    if (isAppActive) {
      setSystemColorScheme(colorSchemeFromRN);
    }
  }, [isAppActive, colorSchemeFromRN]);
```
