### ISSUE TITLE
Jest: TypeError: Class constructor NodeEnvironment cannot be invoked without 'new'

### ISSUE THREAD

**Issue by nazmeln** [facebook/react-native#36720]
### New Version

0.71.4

### Old Version

0.70.7

### Build Target(s)

local environment

### Output of `react-native info`

System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 94.08 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.5.0 - /var/folders/j8/2560qd0953n9c2cn56dvjz600000gn/T/yarn--1680179739469-0.26832671741691994/node
    Yarn: 1.23.0-20220130.1630 - /var/folders/j8/2560qd0953n9c2cn56dvjz600000gn/T/yarn--1680179739469-0.26832671741691994/yarn
    npm: 9.3.1 - /opt/homebrew/bin/npm
    Watchman: 2023.03.27.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/Nazarii.Melnyk/.rvm/gems/ruby-2.7.6/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9619390
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.4 => 0.71.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Issue and Reproduction Steps

Jest tests fail since I've upgraded the `jest` library from **~26** to **^29.2.1**.
Here are my configurations:
**JSON**
```
    "@babel/core": "^7.20.0",
    "@babel/plugin-proposal-export-namespace-from": "7.12.13",
    "@babel/preset-env": "^7.20.0",
    "@babel/preset-typescript": "^7.21.0",
    "@babel/runtime": "^7.20.0",
    "@types/jest": "^29.2.1",
    "babel-jest": "^29.2.1",
    "jest": "^29.2.1",
    "ts-jest": "^29.0.5",
    "typescript": "4.8.4"
```

**jest.config.json**

```
{
  "preset": "react-native",
  "collectCoverage": true,
  "testRegex": "__tests__/.*\\.test\\.(ts|tsx)$",
  "coverageReporters": ["json-summary"],
  "moduleDirectories": ["node_modules", "src"],
  "setupFiles": ["<rootDir>/__tests__/setup.ts"],
  "transformIgnorePatterns": [
    "node_modules/(?!(jest-)?react-native|@react-native|react-navigation|react-clone-referenced-element|@react-native-firebase|react-native-branch|@react-native-community|react-native-permissions|react-native-device-country)"
  ],
  "transform": {
    "^.+\\.(js)$": "<rootDir>/node_modules/babel-jest",
    "\\.(ts|tsx)$": "ts-jest"
  },
  "setupFilesAfterEnv": [
    "<rootDir>/__mocks__/globalMock.ts"
  ],
  "moduleFileExtensions": [
    "ts",
    "tsx",
    "js",
    "json",
    "node"
  ],
  "coveragePathIgnorePatterns": ["/node_modules/", "/jest"],
  "globals": {
    "ENV": "test",
    "__DEV__": true,
    "__RCTProfileIsProfiling": false
  }
}
```

**Comment by blakef** [comment]
Are you doing something custom with NodeEnvironment in your jest setup scripts?  A quick search on the jest repo showed this: facebook/jest#13914.

You could probably get away with wrapping what you export in a function? `module.exports = () => new FooEnvironment`, or something like that.

**Comment by nazmeln** [comment]
Hey @blakef,
I've fixed it by upgrading `jest` to the latest version, removing `babel-typescript` from package.json, and re-creating the `ts-jest` config file as stated in a [guide](https://kulshekhar.github.io/ts-jest/docs/guides/react-native) for RN projects.

**p.s. It seems to be related to jest upgrade from 26 version to 29.**

**Comment by chky-nmnsoftware** [comment]
For anyone who might have this problem in the future and the above solutions don't work (or do not fit your requirements), I was able to fix mine by upgrading my `tsconfig.json` target from "es5" to "es6". This was because I was importing files from another project which used es6 but the main one used es5. You can read more about it [here](https://stackoverflow.com/a/50203532).
