### ISSUE TITLE
Cant bundle locally on port 8080 after init on 0.72.0-rc.0 and bug in the template

### ISSUE THREAD

**Issue by shamilovtim** [facebook/react-native#36730]
### New Version

0.72.0-rc.0

### Old Version

0.71.4

### Build Target(s)

iOS

### Output of `react-native info`

```
System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 24.11 GB / 64.00 GB
    Shell: 3.5.1 - /usr/local/bin/fish
  Binaries:
    Node: 16.18.0 - /var/folders/wh/3w785sdn0dj57ljs45b_70dc0000gn/T/yarn--1680208974095-0.6799107890616574/node
    Yarn: 1.22.18 - /var/folders/wh/3w785sdn0dj57ljs45b_70dc0000gn/T/yarn--1680208974095-0.6799107890616574/yarn
    npm: 9.4.2 - ~/.nvm/versions/node/v16.18.0/bin/npm
    Watchman: 2023.03.27.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /Users/admin/.rvm/gems/ruby-2.7.4/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 28, 29, 30, 31, 33
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 33.0.0
      System Images: android-30 | AOSP ATD ARM 64 v8a, android-30 | ARM 64 v8a, android-30 | Google Play Intel x86 Atom, android-31 | Intel x86 Atom_64, android-31 | Google APIs Intel x86 Atom_64, android-31 | Google Play ARM 64 v8a
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9514443
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16.1 - /opt/homebrew/opt/openjdk@11/bin/javac
    Ruby: 2.7.4 - /Users/admin/.rvm/rubies/ruby-2.7.4/bin/ruby
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.72.0-rc.0 => 0.72.0-rc.0
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Issue and Reproduction Steps

The `0.72.0-rc.0` template does not bundle locally with Metro on port 8080 and has a number of bugs that appear immediately after init.

1. `npx react-native@latest init rn72test --version 0.72.0-rc.0`
2. `yarn start --reset-cache`
3. receive a terminal prompt:
<img width="666" alt="Screenshot 2023-03-30 at 4 08 06 PM" src="https://user-images.githubusercontent.com/3495974/228952530-caefca72-b437-4415-8514-66d9d77a035d.png">

4. click 'i' to open iOS simulator  
6. receive error, unable to bundle  
<img width="469" alt="Screenshot 2023-03-30 at 4 07 55 PM" src="https://user-images.githubusercontent.com/3495974/228952592-f851566f-c2f3-49c8-a58e-e721ad677bbd.png">
7. shake gesture does not work to try to select a different port

checked open ports, node is there at 8080:
<img width="1029" alt="Screenshot 2023-03-30 at 4 34 46 PM" src="https://user-images.githubusercontent.com/3495974/228958098-7b12a297-4a57-40bb-89d9-63fc5217b576.png">

alternatively, try a different process for opening metro:
- `killall node` 
- open the .xcworkspace
- run iOS simmulator
- same problem. bundler runs at 8080, iOS simulator cannot find it. 

alternatively, try port 8081:
- `killall node`
- `yarn react-native start --port 8081`
- check port 8081, it's there.
- this time it bundles but throws a new error:
```
error: Error: Unable to resolve module missing-asset-registry-path from /Users/admin/Documents/Development/block/rn72wallet/node_modules/react-native/Libraries/LogBox/UI/LogBoxImages/close.png: missing-asset-registry-path could not be found within the project or in these directories:
  node_modules/react-native/node_modules
  ```
<img width="469" alt="Screenshot 2023-03-30 at 4 38 09 PM" src="https://user-images.githubusercontent.com/3495974/228958624-db00c776-7067-4c5a-a5a0-449a1f6cdc51.png">

**Comment by huntie** [comment]
Hey @shamilovtim! 

> `npx react-native@latest init rn72test --version 0.72.0-rc.0`

I believe the RC branch was not stable at the point that `0.72.0-rc.0` was cut. Please check that your `metro.config.js` file contents match the latest template version ([permalink](https://github.com/facebook/react-native/blob/392a8434941f08b095d3b4d12e785f2b0a7d2aaf/packages/react-native/template/metro.config.js#L8-L20)). 

(`Unable to resolve module missing-asset-registry-path` is a tell that you might be missing Metro config for React Native, for which we moved the defaults into a new package recently.)

- https://github.com/facebook/react-native/pull/36502
    - This PR also includes a Test Plan where end-to-end behaviour was validated.

cc @kelset Shall we release `0.72-rc.1` soon to include the hotfixes?

**Comment by kelset** [comment]
(yeah ETA for RC1 is early next week)
