### ISSUE TITLE
0.71.5 View onLayout event.target typescript error

### ISSUE THREAD

**Issue by onlyling** [facebook/react-native#36736]
### Description

in 0.70.x width `"@types/react-native": "^0.70.8"`

<img width="893" alt="image" src="https://user-images.githubusercontent.com/9999765/229062454-651bc0e6-120f-4267-b8ad-887c9a954c5e.png">

in 0.71.5

<img width="882" alt="image" src="https://user-images.githubusercontent.com/9999765/229062746-97f280f5-ed37-495d-9a3e-2862fc77c3d9.png">

### React Native Version

0.71.5

### Output of `npx react-native info`

System:
    OS: macOS 13.3
    CPU: (10) arm64 Apple M1 Pro
    Memory: 95.28 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.19.1 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.19.3 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.12.0 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.18 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.5 => 0.71.5 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

just like `Description`

### Snack, code example, screenshot, or link to a repository

just like `Description`

**Comment by NickGerleman** [comment]
Fixed by https://github.com/facebook/react-native/pull/38600
