### ISSUE TITLE
turbomodule/core/TurboModuleUtils.h: No such file or directory

### ISSUE THREAD

**Issue by kofkgoing** [facebook/react-native#36738]
### Description

I can't build my company's 0.65 project after upgrading xcode to 14.3 today.

however I can build my personal 0.69 project.

I can't solve even after removing cache folders and npm modules.. Pods...

### React Native Version

0.65.3

### Output of `npx react-native info`

System:
    OS: macOS 13.0.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 150.35 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 18.15.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.5.0 - /usr/local/bin/npm
    Watchman: 2023.02.06.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: 6.0.0 => 6.0.0 
    react: 17.0.2 => 17.0.2 
    react-native: 0.65.3 => 0.65.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. Upgrade Xcode to 14.3
2. rebuild project based 0.65

### Snack, code example, screenshot, or link to a repository

<img width="1057" alt="스크린샷 2023-03-31 오후 9 03 19" src="https://user-images.githubusercontent.com/85471652/229115539-5424a60f-37d5-4c22-bc5a-4b67fd743d71.png">

I can't understand why xcode is trying to find ```ReactCommon/turbomodule/core/TurboModuleUtils.h``` not ```ReactCommon/react/nativemodule/core/ReactCommon/TurboModuleUtils.h```

<img width="292" alt="스크린샷 2023-03-31 오후 9 09 02" src="https://user-images.githubusercontent.com/85471652/229116118-8fbd5064-7d84-428d-82df-0cec912779e9.png">

**Comment by kelset** [comment]
duplicate https://github.com/facebook/react-native/issues/36739
