### ISSUE TITLE
Failed to do drawer navigation after react active upgrading

### ISSUE THREAD

**Issue by juzitadi** [facebook/react-native#36753]
### Description

![cannot switch menu components](https://user-images.githubusercontent.com/95951684/229225689-ad2e353b-41ff-4bf3-a7f0-c24989ed374e.gif)

When I tried to switch from Home component to Scan History and Settings component, there was nothing happen but just close the menu and stay in the Home.

This function works fine before upgrading, with the react-native version 0.63.4.

### React Native Version

0.66.5

### Output of `npx react-native info`

System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Memory: 16.68 GB / 31.85 GB
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.6.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      Android NDK: 22.1.7171670
    Windows SDK: Not Found
  IDEs:
    Android Studio: AI-213.7172.25.2113.9014738
    Visual Studio: Not Found
  Languages:
    Java: 11.0.17
    Python: 3.9.7
  npmPackages:
    @react-native-community/cli: ^4.14.0 => 4.14.0
    react: 16.13.1 => 16.13.1
    react-native: 0.66.5 => 0.66.5
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. Run `npx react-native start`
2. Test on `emulator -avd "Pixel_3a_API_33"`

### Snack, code example, screenshot, or link to a repository

This is the output of `react-native run android`

PS C:\Users\ezhalej\Downloads\Received Project\20230330-Throughput Test 0\phone> react-native run-android
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
(node:4608) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Jetifier found 1265 file(s) to forward-jetify. Using 8 workers...
info Starting JS server...
info Installing the app...
Starting a Gradle Daemon, 2 incompatible and 1 stopped Daemons could not be reused, use --status for details

> Configure project :app
Using force on a dependency has been deprecated. This is scheduled to be removed in Gradle 7.0. Consider using strict version constraints instead (version { strictly ... } }). Consult the upgrading guide for further information: https://docs.gradle.org/6.7.1/userguide/upgrading_version_5.html#forced_dependencies
        at build_7yax5sfg1lpa62obwkneujqjp$_run_closure2$_closure23.doCall(C:\Users\ezhalej\Downloads\Received Project\20230330-Throughput Test 0\phone\android\app\build.gradle:220)      
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)
WARNING:: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed in version 7.0 of the Android Gradle plugin.
For more information, see http://d.android.com/r/tools/update-dependency-configurations.html.
WARNING:: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01  
Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
WARNING:: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
WARNING:: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01      
Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
WARNING:: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/03 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/03 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
WARNING:: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
WARNING:: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/03 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/03 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
WARNING:: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/03 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/03 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
WARNING:: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
WARNING:: unexpected element (uri:"", local:"base-extension"). Expected elements are <{}codename>,<{}layoutlib>,<{}api-level> 
unexpected element (uri:"", local:"base-extension"). Expected elements are <{}codename>,<{}layoutlib>,<{}api-level>
WARNING:: unexpected element (uri:"", local:"extension-level"). Expected elements are <{}codename>,<{}layoutlib>,<{}api-level>
unexpected element (uri:"", local:"extension-level"). Expected elements are <{}codename>,<{}layoutlib>,<{}api-level>
WARNING:: unexpected element (uri:"", local:"base-extension"). Expected elements are <{}codename>,<{}api-level>
unexpected element (uri:"", local:"base-extension"). Expected elements are <{}codename>,<{}api-level>
WARNING:: unexpected element (uri:"", local:"extension-level"). Expected elements are <{}codename>,<{}api-level>
unexpected element (uri:"", local:"extension-level"). Expected elements are <{}codename>,<{}api-level>
WARNING:: unexpected element (uri:"", local:"base-extension"). Expected elements are <{}vendor>,<{}codename>,<{}abi>,<{}api-level>,<{}tag>
unexpected element (uri:"", local:"base-extension"). Expected elements are <{}vendor>,<{}codename>,<{}abi>,<{}api-level>,<{}tag>
WARNING:: Errors limit exceeded. To receive all errors set com.sun.xml.bind logger to FINEST level.
Errors limit exceeded. To receive all errors set com.sun.xml.bind logger to FINEST level.

> Configure project :react-native-reanimated
AAR for react-native-reanimated has been found
C:\Users\ezhalej\Downloads\Received Project\20230330-Throughput Test 0\phone\node_modules\react-native-reanimated\android\react-native-reanimated-66-jsc.aar

> Configure project :react-native-webview
Adding a Configuration as a dependency is a confusing behavior which isn't recommended. This behaviour has been deprecated and is scheduled to be removed in Gradle 8.0. If you're interested in inheriting the dependencies from the Configuration you are adding, you should use Configuration#extendsFrom instead. See https://docs.gradle.org/6.7.1/dsl/org.gradle.api.artifacts.Configuration.html#org.gradle.api.artifacts.Configuration:extendsFrom(org.gradle.api.artifacts.Configuration[]) for more details.
WARNING:: The specified Android SDK Build Tools version (29.0.2) is ignored, as it is below the minimum supported version (30.0.2) for Android Gradle Plugin 4.2.2.
Android SDK Build Tools 30.0.2 will be used.
To suppress this warning, remove "buildToolsVersion '29.0.2'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

> Task :app:processDebugMainManifest
[:@react-native-community_datetimepicker] C:\Users\ezhalej\Downloads\Received Project\20230330-Throughput Test 0\phone\node_modules\@react-native-community\datetimepicker\android\build\intermediates\merged_manifest\debug\AndroidManifest.xml Warning:
        Package name 'com.reactcommunity.rndatetimepicker' used in: :@react-native-community_datetimepicker, :react-native-community_datetimepicker.

> Task :app:generateJsonModelDebug
C:\Users\ezhalej\Downloads\Received Project\20230330-Throughput Test 0\phone\android\app\CMakeLists.txt : C/C++ debug|armeabi-v7a : CMake Warning at C:/Users/ezhalej/AppData/Local/Android/Sdk/ndk/25.1.8937393/build/cmake/android-legacy.toolchain.cmake:415 (message):
  An old version of CMake is being used that cannot automatically detect
  compiler attributes.  Compiler identification is being bypassed.  Some
  values may be wrong or missing.  Update to CMake 3.19 or newer to use
  CMake's built-in compiler identification.
Call Stack (most recent call first):
  C:/Users/ezhalej/AppData/Local/Android/Sdk/ndk/25.1.8937393/build/cmake/android.toolchain.cmake:54 (include)
  C:/Users/ezhalej/AppData/Local/Android/Sdk/cmake/3.10.2.4988404/share/cmake-3.10/Modules/CMakeDetermineSystem.cmake:94 (include)
  CMakeLists.txt

C:\Users\ezhalej\Downloads\Received Project\20230330-Throughput Test 0\phone\android\app\CMakeLists.txt : C/C++ debug|armeabi-v7a : CMake Warning at C:/Users/ezhalej/AppData/Local/Android/Sdk/ndk/25.1.8937393/build/cmake/android-legacy.toolchain.cmake:415 (message):
  An old version of CMake is being used that cannot automatically detect
  compiler attributes.  Compiler identification is being bypassed.  Some
  values may be wrong or missing.  Update to CMake 3.19 or newer to use
  CMake's built-in compiler identification.
Call Stack (most recent call first):
  C:/Users/ezhalej/AppData/Local/Android/Sdk/ndk/25.1.8937393/build/cmake/android.toolchain.cmake:54 (include)
  C:/Users/ezhalej/AppData/Local/Android/Sdk/cmake/3.10.2.4988404/share/cmake-3.10/Modules/CMakeDetermineSystem.cmake:94 (include)
  CMakeLists.txt

C:\Users\ezhalej\Downloads\Received Project\20230330-Throughput Test 0\phone\android\app\CMakeLists.txt : C/C++ debug|armeabi-v7a : CMake Warning at C:/Users/ezhalej/AppData/Local/Android/Sdk/ndk/25.1.8937393/build/cmake/android-legacy.toolchain.cmake:415 (message):
  An old version of CMake is being used that cannot automatically detect
  compiler attributes.  Compiler identification is being bypassed.  Some
  values may be wrong or missing.  Update to CMake 3.19 or newer to use
  CMake's built-in compiler identification.
Call Stack (most recent call first):
  C:/Users/ezhalej/AppData/Local/Android/Sdk/ndk/25.1.8937393/build/cmake/android.toolchain.cmake:54 (include)
  C:/Users/ezhalej/Downloads/Received Project/20230330-Throughput Test 0/phone/android/app/.cxx/cmake/debug/armeabi-v7a/CMakeFiles/3.10.2/CMakeSystem.cmake:6 (include)
  C:/Users/ezhalej/Downloads/Received Project/20230330-Throughput Test 0/phone/android/app/.cxx/cmake/debug/armeabi-v7a/CMakeFiles/CMakeTmp/CMakeLists.txt:2 (project)

C:\Users\ezhalej\Downloads\Received Project\20230330-Throughput Test 0\phone\android\app\CMakeLists.txt : C/C++ debug|armeabi-v7a : CMake Warning at C:/Users/ezhalej/AppData/Local/Android/Sdk/ndk/25.1.8937393/build/cmake/android-legacy.toolchain.cmake:415 (message):
  An old version of CMake is being used that cannot automatically detect
  compiler attributes.  Compiler identification is being bypassed.  Some
  values may be wrong or missing.  Update to CMake 3.19 or newer to use
  CMake's built-in compiler identification.
Call Stack (most recent call first):
  C:/Users/ezhalej/AppData/Local/Android/Sdk/ndk/25.1.8937393/build/cmake/android.toolchain.cmake:54 (include)
  C:/Users/ezhalej/Downloads/Received Project/20230330-Throughput Test 0/phone/android/app/.cxx/cmake/debug/armeabi-v7a/CMakeFiles/3.10.2/CMakeSystem.cmake:6 (include)
  C:/Users/ezhalej/Downloads/Received Project/20230330-Throughput Test 0/phone/android/app/.cxx/cmake/debug/armeabi-v7a/CMakeFiles/CMakeTmp/CMakeLists.txt:2 (project)

C:\Users\ezhalej\Downloads\Received Project\20230330-Throughput Test 0\phone\android\app\CMakeLists.txt : C/C++ debug|x86_64 : CMake Warning at C:/Users/ezhalej/AppData/Local/Android/Sdk/ndk/25.1.8937393/build/cmake/android-legacy.toolchain.cmake:415 (message):
  An old version of CMake is being used that cannot automatically detect
  compiler attributes.  Compiler identification is being bypassed.  Some
  values may be wrong or missing.  Update to CMake 3.19 or newer to use
  CMake's built-in compiler identification.
Call Stack (most recent call first):
  C:/Users/ezhalej/AppData/Local/Android/Sdk/ndk/25.1.8937393/build/cmake/android.toolchain.cmake:54 (include)
  C:/Users/ezhalej/AppData/Local/Android/Sdk/cmake/3.10.2.4988404/share/cmake-3.10/Modules/CMakeDetermineSystem.cmake:94 (include)
  CMakeLists.txt

C:\Users\ezhalej\Downloads\Received Project\20230330-Throughput Test 0\phone\android\app\CMakeLists.txt : C/C++ debug|x86_64 : CMake Warning at C:/Users/ezhalej/AppData/Local/Android/Sdk/ndk/25.1.8937393/build/cmake/android-legacy.toolchain.cmake:415 (message):
  An old version of CMake is being used that cannot automatically detect
  compiler attributes.  Compiler identification is being bypassed.  Some
  values may be wrong or missing.  Update to CMake 3.19 or newer to use
  CMake's built-in compiler identification.
Call Stack (most recent call first):
  C:/Users/ezhalej/AppData/Local/Android/Sdk/ndk/25.1.8937393/build/cmake/android.toolchain.cmake:54 (include)
  C:/Users/ezhalej/AppData/Local/Android/Sdk/cmake/3.10.2.4988404/share/cmake-3.10/Modules/CMakeDetermineSystem.cmake:94 (include)
  CMakeLists.txt

C:\Users\ezhalej\Downloads\Received Project\20230330-Throughput Test 0\phone\android\app\CMakeLists.txt : C/C++ debug|x86_64 : CMake Warning at C:/Users/ezhalej/AppData/Local/Android/Sdk/ndk/25.1.8937393/build/cmake/android-legacy.toolchain.cmake:415 (message):
  An old version of CMake is being used that cannot automatically detect
  compiler attributes.  Compiler identification is being bypassed.  Some
  values may be wrong or missing.  Update to CMake 3.19 or newer to use
  CMake's built-in compiler identification.
Call Stack (most recent call first):
  C:/Users/ezhalej/AppData/Local/Android/Sdk/ndk/25.1.8937393/build/cmake/android.toolchain.cmake:54 (include)
  C:/Users/ezhalej/Downloads/Received Project/20230330-Throughput Test 0/phone/android/app/.cxx/cmake/debug/x86_64/CMakeFiles/3.10.2/CMakeSystem.cmake:6 (include)
  C:/Users/ezhalej/Downloads/Received Project/20230330-Throughput Test 0/phone/android/app/.cxx/cmake/debug/x86_64/CMakeFiles/CMakeTmp/CMakeLists.txt:2 (project)

C:\Users\ezhalej\Downloads\Received Project\20230330-Throughput Test 0\phone\android\app\CMakeLists.txt : C/C++ debug|x86_64 : CMake Warning at C:/Users/ezhalej/AppData/Local/Android/Sdk/ndk/25.1.8937393/build/cmake/android-legacy.toolchain.cmake:415 (message):
  An old version of CMake is being used that cannot automatically detect
  compiler attributes.  Compiler identification is being bypassed.  Some
  values may be wrong or missing.  Update to CMake 3.19 or newer to use
  CMake's built-in compiler identification.
Call Stack (most recent call first):
  C:/Users/ezhalej/AppData/Local/Android/Sdk/ndk/25.1.8937393/build/cmake/android.toolchain.cmake:54 (include)
  C:/Users/ezhalej/Downloads/Received Project/20230330-Throughput Test 0/phone/android/app/.cxx/cmake/debug/x86_64/CMakeFiles/3.10.2/CMakeSystem.cmake:6 (include)
  C:/Users/ezhalej/Downloads/Received Project/20230330-Throughput Test 0/phone/android/app/.cxx/cmake/debug/x86_64/CMakeFiles/CMakeTmp/CMakeLists.txt:2 (project)

> Task :app:dexBuilderDebug
WARNING:: D8: An API level of 31 is not supported by this compiler. Please use an API level of 30 or earlier
WARNING:: D8: An API level of 31 is not supported by this compiler. Please use an API level of 30 or earlier
WARNING:: D8: An API level of 31 is not supported by this compiler. Please use an API level of 30 or earlier
WARNING:: D8: An API level of 31 is not supported by this compiler. Please use an API level of 30 or earlier
WARNING:: D8: An API level of 31 is not supported by this compiler. Please use an API level of 30 or earlier
WARNING:: D8: An API level of 31 is not supported by this compiler. Please use an API level of 30 or earlier
WARNING:: D8: An API level of 31 is not supported by this compiler. Please use an API level of 30 or earlier
WARNING:: D8: An API level of 31 is not supported by this compiler. Please use an API level of 30 or earlier

> Task :app:externalNativeBuildDebug
Build native-lib_armeabi-v7a
ninja: Entering directory `C:\Users\ezhalej\Downloads\Received Project\20230330-Throughput Test 0\phone\android\app\.cxx\cmake\debug\armeabi-v7a'
../../../../src/main/cpp/iperf_error.c:118:1: warning: function declared 'noreturn' should not return [-Winvalid-noreturn]
../../../../src/main/cpp/cjson.c:369:19: warning: implicit conversion from 'long long' to 'double' changes value from 9223372036854775807 to 9223372036854775808 [-Wimplicit-const-int-float-conversion]
C:/Users/ezhalej/AppData/Local/Android/Sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/windows-x86_64/lib64/clang/14.0.6/include/limits.h:100:20: note: expanded from macro 'LLONG_MAX'      
<built-in>:45:27: note: expanded from here
../../../../src/main/cpp/cjson.c:391:19: warning: implicit conversion from 'long long' to 'double' changes value from 9223372036854775807 to 9223372036854775808 [-Wimplicit-const-int-float-conversion]
C:/Users/ezhalej/AppData/Local/Android/Sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/windows-x86_64/lib64/clang/14.0.6/include/limits.h:100:20: note: expanded from macro 'LLONG_MAX'      
<built-in>:45:27: note: expanded from here
../../../../src/main/cpp/cjson.c:2425:20: warning: implicit conversion from 'long long' to 'double' changes value from 9223372036854775807 to 9223372036854775808 [-Wimplicit-const-int-float-conversion]
C:/Users/ezhalej/AppData/Local/Android/Sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/windows-x86_64/lib64/clang/14.0.6/include/limits.h:100:20: note: expanded from macro 'LLONG_MAX'      
<built-in>:45:27: note: expanded from here
../../../../src/main/cpp/iperf_api.c:1580:1: warning: non-void function does not return a value [-Wreturn-type]
../../../../src/main/cpp/NativeHelloWorld.cpp:191:38: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
../../../../src/main/cpp/NativeHelloWorld.cpp:200:38: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
../../../../src/main/cpp/NativeHelloWorld.cpp:207:38: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
Build native-lib_arm64-v8a
ninja: Entering directory `C:\Users\ezhalej\Downloads\Received Project\20230330-Throughput Test 0\phone\android\app\.cxx\cmake\debug\arm64-v8a'
Build native-lib_x86
ninja: Entering directory `C:\Users\ezhalej\Downloads\Received Project\20230330-Throughput Test 0\phone\android\app\.cxx\cmake\debug\x86'
../../../../src/main/cpp/iperf_error.c:118:1: warning: function declared 'noreturn' should not return [-Winvalid-noreturn]
../../../../src/main/cpp/cjson.c:369:19: warning: implicit conversion from 'long long' to 'double' changes value from 9223372036854775807 to 9223372036854775808 [-Wimplicit-const-int-float-conversion]
C:/Users/ezhalej/AppData/Local/Android/Sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/windows-x86_64/lib64/clang/14.0.6/include/limits.h:100:20: note: expanded from macro 'LLONG_MAX'      
<built-in>:45:27: note: expanded from here
../../../../src/main/cpp/cjson.c:391:19: warning: implicit conversion from 'long long' to 'double' changes value from 9223372036854775807 to 9223372036854775808 [-Wimplicit-const-int-float-conversion]
C:/Users/ezhalej/AppData/Local/Android/Sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/windows-x86_64/lib64/clang/14.0.6/include/limits.h:100:20: note: expanded from macro 'LLONG_MAX'      
<built-in>:45:27: note: expanded from here
../../../../src/main/cpp/cjson.c:2425:20: warning: implicit conversion from 'long long' to 'double' changes value from 9223372036854775807 to 9223372036854775808 [-Wimplicit-const-int-float-conversion]
C:/Users/ezhalej/AppData/Local/Android/Sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/windows-x86_64/lib64/clang/14.0.6/include/limits.h:100:20: note: expanded from macro 'LLONG_MAX'      
<built-in>:45:27: note: expanded from here
../../../../src/main/cpp/iperf_api.c:1580:1: warning: non-void function does not return a value [-Wreturn-type]
../../../../src/main/cpp/NativeHelloWorld.cpp:191:38: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
../../../../src/main/cpp/NativeHelloWorld.cpp:200:38: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
../../../../src/main/cpp/NativeHelloWorld.cpp:207:38: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
Build native-lib_x86_64
ninja: Entering directory `C:\Users\ezhalej\Downloads\Received Project\20230330-Throughput Test 0\phone\android\app\.cxx\cmake\debug\x86_64'
../../../../src/main/cpp/iperf_error.c:118:1: warning: function declared 'noreturn' should not return [-Winvalid-noreturn]
../../../../src/main/cpp/cjson.c:369:19: warning: implicit conversion from 'long long' to 'double' changes value from 9223372036854775807 to 9223372036854775808 [-Wimplicit-const-int-float-conversion]
C:/Users/ezhalej/AppData/Local/Android/Sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/windows-x86_64/lib64/clang/14.0.6/include/limits.h:100:20: note: expanded from macro 'LLONG_MAX'
<built-in>:45:27: note: expanded from here
../../../../src/main/cpp/cjson.c:391:19: warning: implicit conversion from 'long long' to 'double' changes value from 9223372036854775807 to 9223372036854775808 [-Wimplicit-const-int-float-conversion]
C:/Users/ezhalej/AppData/Local/Android/Sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/windows-x86_64/lib64/clang/14.0.6/include/limits.h:100:20: note: expanded from macro 'LLONG_MAX'
<built-in>:45:27: note: expanded from here
../../../../src/main/cpp/cjson.c:2425:20: warning: implicit conversion from 'long long' to 'double' changes value from 9223372036854775807 to 9223372036854775808 [-Wimplicit-const-int-float-conversion]
C:/Users/ezhalej/AppData/Local/Android/Sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/windows-x86_64/lib64/clang/14.0.6/include/limits.h:100:20: note: expanded from macro 'LLONG_MAX'      
<built-in>:45:27: note: expanded from here
../../../../src/main/cpp/iperf_api.c:1580:1: warning: non-void function does not return a value [-Wreturn-type]
../../../../src/main/cpp/NativeHelloWorld.cpp:191:38: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
../../../../src/main/cpp/NativeHelloWorld.cpp:200:38: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
../../../../src/main/cpp/NativeHelloWorld.cpp:207:38: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]

> Task :app:installDebug
Installing APK 'app-debug.apk' on 'Taro for arm64 - 13' for app:debug
Installing APK 'app-debug.apk' on 'Pixel_3a_API_31(AVD) - 12' for app:debug
Installed on 2 devices.

BUILD SUCCESSFUL in 4m 39s

**Comment by cortinico** [comment]
Which navigation library are you using? You should open this issue against them
