### ISSUE TITLE
Yoga.cpp issue with Xcode 14.3 (14E222b)

### ISSUE THREAD

**Issue by nicolasdevienne** [facebook/react-native#36758]
### Description

An issue occurs when we try to build project : "Yoga.cpp : Use of bitwise '|' with boolean operands".
When we double the '|', it works...

### React Native Version

0.66.4

### Output of `npx react-native info`

System:
    OS: macOS 13.3
    CPU: (8) arm64 Apple M1 Pro
    Memory: 90.30 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 19.7.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.5.0 - /opt/homebrew/bin/npm
    Watchman: 2023.02.27.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9619390
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /opt/homebrew/opt/openjdk@11/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.4 => 0.66.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Update Xcode with last version 14.3 (14E222b) and try to build project.

### Snack, code example, screenshot, or link to a repository

<img width="1500" alt="Capture d’écran 2023-04-01 à 10 35 06" src="https://user-images.githubusercontent.com/65358122/229275802-9d4b7296-e36b-43f6-83ae-61f732998491.png">

**Comment by keisan1231** [comment]
> double the '|', it works

Me too. Thanks

**Comment by kelset** [comment]
duplicate https://github.com/facebook/react-native/issues/36739

**Comment by sunnylqm** [comment]
@kelset this is NOT a dulicate issue

**Comment by kelset** [comment]
I see, thanks for clarifying. But 0.69 is the [lowest version supported](https://github.com/reactwg/react-native-releases#which-versions-are-currently-supported), so is there a specific reason we should keep this one one if it's only for versions lower than 0.69?

**Comment by sunnylqm** [comment]
at least i thought https://github.com/facebook/react-native/issues/36739 is the correct way to fix this yoga.cpp issue, but it turned out not later. Feel free to close it, but with a link to a correct commit or comment.

**Comment by xhirazi** [comment]
+1

double the | can solve the issue but what about he permanent solution?

**Comment by Abhishek2250** [comment]
I'm also getting this issue on xcode cloud CI using react-native version 0.68.4. How can I fix the issue there?
Any ideas?

Thanks

**Comment by awatt-cox** [comment]
We have a pipeline that reinstalls all of the dependencies when it builds the app. Does anyone have a post-install script that can fix the broken line of code so our pipeline can build successfully? We have a large, complex app using react-native 67.5, so "just update to 0.69" is not a quick change.

**Comment by sunnylqm** [comment]
1. install patch-package https://github.com/ds300/patch-package
2. Modify the source code like this commit https://github.com/facebook/react-native/commit/52d8a797e7a6be3fa472f323ceca4814a28ef596
3. run `npx patch-package react-native`
4. commit your changes. Done.

**Comment by kthilagarajan** [comment]
> 1. install patch-package https://github.com/ds300/patch-package
> 2. Modify the source code like this commit [52d8a79](https://github.com/facebook/react-native/commit/52d8a797e7a6be3fa472f323ceca4814a28ef596)
> 3. run `npx patch-package react-native`
> 4. commit your changes. Done.

I was in react-native 0.66.4. Xcode version 14.3. 

This worked for me. Thankyou.

**Comment by shinnthantminn** [comment]
fix error 

i am add || [Logical OR] operator in hadOverflow() fix this error

**Comment by DIOGO-MOTA** [comment]
![image](https://user-images.githubusercontent.com/53905314/230918523-c9856ca4-2051-476c-9955-5b511ab5f55d.png)

remove this line of code

it worked for me

**Comment by dgdapp** [comment]
> ![image](https://user-images.githubusercontent.com/53905314/230918523-c9856ca4-2051-476c-9955-5b511ab5f55d.png)
> 
> remove this line of code
> 
> it worked for me

Yes, it worked for me too!! thankk

**Comment by andreas-bergstrom** [comment]
Not sure removing that line is such a good move... Just use patch-package and apply the fix

**Comment by miallo** [comment]
If you don't want to use patch-package, but rather add a singe line in post install you can just run:
```sh
sed -i.bo 's/    node->getLayout()\.hadOverflow() |$/\0|/' ./node_modules/react-native/ReactCommon/yoga/yoga/Yoga.cpp
```

**Comment by a7chax** [comment]
i fix it by downgrading my xcode to version  14.2 , https://github.com/facebook/yoga/issues/1224

**Comment by pvshum** [comment]
> If you don't want to use patch-package, but rather add a singe line in post install you can just run:
> 
> ```shell
> sed -i.bo 's/    node->getLayout()\.hadOverflow() |$/\0|/' ./node_modules/react-native/ReactCommon/yoga/yoga/Yoga.cpp
> ```

When I run this code, it unfortunately replaces `node->getLayout().hadOverflow() |` to `0|` instead of adding one more pipe.

**Comment by AsteriskZuo** [comment]
> @kelset this is NOT a dulicate issue.
> 
> This affects rn version < 0.69 with Xcode 14.3 [52d8a79](https://github.com/facebook/react-native/commit/52d8a797e7a6be3fa472f323ceca4814a28ef596)

rn version 0.71.8 with xcode 14.3.1 issue too.

**Comment by yorickshan** [comment]
> 

worked for me

**Comment by yorickshan** [comment]
> 1. install patch-package https://github.com/ds300/patch-package
> 2. Modify the source code like this commit [52d8a79](https://github.com/facebook/react-native/commit/52d8a797e7a6be3fa472f323ceca4814a28ef596)
> 3. run `npx patch-package react-native`
> 4. commit your changes. Done.

worked for me

**Comment by TatianaMatumoto** [comment]
> ![image](https://user-images.githubusercontent.com/53905314/230918523-c9856ca4-2051-476c-9955-5b511ab5f55d.png)
> 
> remove this line of code
> 
> it worked for me

i don't know if this is a good solution, but that worked for me. Adding more '|' throws error on everything on my project. 

Tranks for the solution!

**Comment by fondue-tech** [comment]
Another day another Yoga issue.
The patch file is the best solution right now, especially if you can't just migrate to another react native version.

**Comment by danmoz** [comment]
> > If you don't want to use patch-package, but rather add a singe line in post install you can just run:
> > sed -i.bo 's/    node->getLayout()\.hadOverflow() |$/\0|/' ./node_modules/react-native/ReactCommon/yoga/yoga/Yoga.cpp

> When I run this code, it unfortunately replaces node->getLayout().hadOverflow() | to 0| instead of adding one more pipe.

Try this instead:

`sed -i -e 's/ \|$/ ||/g' ./node_modules/react-native/ReactCommon/yoga/yoga/Yoga.cpp`

**Comment by miallo** [comment]
> > If you don't want to use patch-package, but rather add a singe line in post install you can just run:
> 
> > 
> 
> > ```shell
> 
> > sed -i.bo 's/    node->getLayout()\.hadOverflow() |$/\0|/' ./node_modules/react-native/ReactCommon/yoga/yoga/Yoga.cpp
> 
> > ```
> 
> 
> 
> When I run this code, it unfortunately replaces `node->getLayout().hadOverflow() |` to `0|` instead of adding one more pipe.

Are you sure that you have the `\` in front of the `0`? `\0` is referencing the matched search instead of the literal "0". Otherwise you can just type the same thing again that was in the search part of the command...

**Comment by fujikazu** [comment]
./node_modules/react-native/ReactCommon/yoga/yoga/Yoga.cpp

sed -i.bo 's/    node->getLayout()\.hadOverflow() |$/\0|/' ./node_modules/react-native/ReactCommon/yoga/yoga/Yoga.cpp



this worked for me .

**Comment by richarddrum** [comment]
> > If you don't want to use patch-package, but rather add a singe line in post install you can just run:
> > ```shell
> > sed -i.bo 's/    node->getLayout()\.hadOverflow() |$/\0|/' ./node_modules/react-native/ReactCommon/yoga/yoga/Yoga.cpp
> > ```
> 
> When I run this code, it unfortunately replaces `node->getLayout().hadOverflow() |` to `0|` instead of adding one more pipe.

You can try this instead:

**Comment by jerodji** [comment]
it works for me，add `(int)`
```
    node->setLayoutHadOverflow(
        (int)node->getLayout().hadOverflow |
        (int)currentRelativeChild->getLayout().hadOverflow);
```

**Comment by sufyansalim** [comment]
> > > If you don't want to use patch-package, but rather add a singe line in post install you can just run:
> > > ```shell
> > > sed -i.bo 's/    node->getLayout()\.hadOverflow() |$/\0|/' ./node_modules/react-native/ReactCommon/yoga/yoga/Yoga.cpp
> > > ```
> > 
> > 
> > When I run this code, it unfortunately replaces `node->getLayout().hadOverflow() |` to `0|` instead of adding one more pipe.
> 
> You can try this instead: `sed -i.bo 's/ node->getLayout()\.hadOverflow() |/ node->getLayout()\.hadOverflow() ||/' ./node_modules/react-native/ReactCommon/yoga/yoga/Yoga.cpp `

after adding this line i get the following build commands failed: CompileC /Users/myname/projects/projectname/ios/DerivedData/aido/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RCT-Folly.build/Objects-normal/arm64/json.o /Users/myname/projects/projectname/ios/Pods/RCT-Folly/folly/json.cpp normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'RCT-Folly' from project 'Pods') (1 failure)

**Comment by matthewbal** [comment]
> You can try this instead: `sed -i.bo 's/ node->getLayout()\.hadOverflow() |/ node->getLayout()\.hadOverflow() ||/' ./node_modules/react-native/ReactCommon/yoga/yoga/Yoga.cpp `

By the way, for our version of RN/Yoga, this sed command will also find replace 2 other occurrences which should not be changed and may cause subtle build issues.

We recommend using sed with a line number restriction so that it only changes the one line causing the issue, here is the completed command that we are using in our pipeline to make yoga work with node 16.

`sed -i.bo '2289s/    node->getLayout()\.hadOverflow() |/    node->getLayout()\.hadOverflow() ||/' ./node_modules/react-native/ReactCommon/yoga/yoga/Yoga.cpp `

For us the line number was 2289 with react native 0.64.0, for other versions of RN/yoga it may be a different line number so make sure you check your xcode error and only replace the specific line number you have the issue on.

**Comment by sufyansalim** [comment]
i

> > You can try this instead: `sed -i.bo 's/ node->getLayout()\.hadOverflow() |/ node->getLayout()\.hadOverflow() ||/' ./node_modules/react-native/ReactCommon/yoga/yoga/Yoga.cpp `
> 
> By the way, for our version of RN/Yoga, this sed command will also find replace 2 other occurrences which should not be changed and may cause subtle build issues.
> 
> We recommend using sed with a line number restriction so that it only changes the one line causing the issue, here is the completed command that we are using in our pipeline to make yoga work with node 16.
> 
> `sed -i.bo '2289s/ node->getLayout()\.hadOverflow() |/ node->getLayout()\.hadOverflow() ||/' ./node_modules/react-native/ReactCommon/yoga/yoga/Yoga.cpp `
> 
> For us the line number was 2289 with react native 0.64.0, for other versions of RN/yoga it may be a different line number so make sure you check your xcode error and only replace the specific line number you have the issue on.

i even manually changed the line didnt work work me instead i get
after adding this line i get the following build commands failed: CompileC /Users/myname/projects/projectname/ios/DerivedData/aido/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RCT-Folly.build/Objects-normal/arm64/json.o /Users/myname/projects/projectname/ios/Pods/RCT-Folly/folly/json.cpp normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'RCT-Folly' from project 'Pods') (1 failure)

**Comment by moustaouiSalaheddine** [comment]
install [patch-package](https://github.com/ds300/patch-package) 
**solution** [commit](https://github.com/facebook/react-native/commit/52d8a797e7a6be3fa472f323ceca4814a28ef596)
in `yoga/Yoga.cpp`
change this
        `node->getLayout().hadOverflow() |`
to this
        `node->getLayout().hadOverflow() ||`
        
run patch-package to create a .patch file
`npx patch-package react-native`

after that commit and push your changes

**Comment by Symous** [comment]
use patch-packgae or modify the source code is too heavy, I provide aother  elegant way.

in ios/Podfile add find_add_replace method (I copy this method from the community to solve other XCode related issue before):
```
def find_and_replace(dir, findstr, replacestr)
  Dir[dir].each do |name|
      text = File.read(name)
      replace = text.gsub(findstr,replacestr)
      if text != replace
          puts "Fix: " + name
          File.open(name, "w") { |file| file.puts replace }
          STDOUT.flush
      end
  end
  Dir[dir + '*/'].each(&method(:find_and_replace))
end
```

in pod_install section use find_and_replace to replace the related lines:
```
find_and_replace("../node_modules/react-native/ReactCommon/yoga/yoga/Yoga.cpp",
  "node->getLayout().hadOverflow() |\n","node->getLayout().hadOverflow() ||\n")
```

**Comment by mochadwi** [comment]
> use patch-packgae or modify the source code manually is too heavy, I provide another elegant way.
> 
> in ios/Podfile add find_add_replace method (I copy this method from the community to solve other XCode related issue before):
> 
> ```
> def find_and_replace(dir, findstr, replacestr)
>   Dir[dir].each do |name|
>       text = File.read(name)
>       replace = text.gsub(findstr,replacestr)
>       if text != replace
>           puts "Fix: " + name
>           File.open(name, "w") { |file| file.puts replace }
>           STDOUT.flush
>       end
>   end
>   Dir[dir + '*/'].each(&method(:find_and_replace))
> end
> ```
> 
> in pod_install section use find_and_replace to replace the related lines:
> 
> ```
> find_and_replace("../node_modules/react-native/ReactCommon/yoga/yoga/Yoga.cpp",
>   "node->getLayout().hadOverflow() |\n","node->getLayout().hadOverflow() ||\n")
> ```
> 
> execute `pod install` and run again.

unfortunately, when run in CI this is not possible. I tried to run through Xcode Cloud, it failed.

**Comment by andreas-bergstrom** [comment]
> use patch-packgae or modify the source code manually is too heavy, I provide another elegant way.
> 
> in ios/Podfile add find_add_replace method (I copy this method from the community to solve other XCode related issue before):
> 
> ```
> def find_and_replace(dir, findstr, replacestr)
>   Dir[dir].each do |name|
>       text = File.read(name)
>       replace = text.gsub(findstr,replacestr)
>       if text != replace
>           puts "Fix: " + name
>           File.open(name, "w") { |file| file.puts replace }
>           STDOUT.flush
>       end
>   end
>   Dir[dir + '*/'].each(&method(:find_and_replace))
> end
> ```
> 
> in pod_install section use find_and_replace to replace the related lines:
> 
> ```
> find_and_replace("../node_modules/react-native/ReactCommon/yoga/yoga/Yoga.cpp",
>   "node->getLayout().hadOverflow() |\n","node->getLayout().hadOverflow() ||\n")
> ```
> 
> execute `pod install` and run again.

How is it "too heavy", it's just a few steps and a few min at most?

Shameless plug:
https://dev.to/andreasbergstrom/patch-package-the-essential-tool-for-managing-dependencies-in-both-modern-and-legacy-projects-4hnn

**Comment by Symous** [comment]
@andreas-bergstrom what I said "too heavy" is that use patch-package to apply the changes will generate extra but not "important and necessary" patch files.
