### ISSUE TITLE
Cannot read properties of undefined (reading 'transformFile')

### ISSUE THREAD

**Issue by my-name-is-nheo** [facebook/react-native#36760]
### Description

The build process I'm running with node version 18.15.0 is failing and throwing an error code that says it cannot read properties of undefined. Specifically, it's trying to read the 'transformFile' property and failing to do so. I tried cleaning the build, fresh installing the packages and pods, but cannot get past this error. 

1. I see that from 0.68+, RN has been updated to Node 16, meaning users are now required to use a version of Node >= 14. Could updating my RN version fix this error? ( I personally don't think so, but trying to hear different answers)

2. My start command is
```typescript
   "start": "NODE_OPTIONS=--openssl-legacy-provider react-native start"
```
This command instructs Node.js to use the legacy OpenSSL provider instead of the default provider. I don't particularly feel comfortable forcing node to use a legacy provider, basically a deprecated option, when I can use node 16.

3. I feel like when XCode is building the app, possible when it starts the metro server, it's not running with the command --openssl-legacy... . Did I miss a step here? Where can I update this?

Thank you in advance

### React Native Version

0.67.5

### Output of `npx react-native info`

System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 88.20 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
    Yarn: 1.22.15 - ~/.nvm/versions/node/v16.15.1/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v18.13.0/bin/npm
    Watchman: 2023.01.02.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /Users/nheo/.rvm/gems/ruby-3.0.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7784292
    Xcode: 14.0/14A309 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.10 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.2 => 17.0.2 
    react-native: ^0.67.5 => 0.67.5 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found <--- using pnpm

### Steps to reproduce

1. rm -rf node_modules
2. pnpm i 
3. cd ios &&  pod install
4. Open XCode and Build

### Snack, code example, screenshot, or link to a repository

![image](https://user-images.githubusercontent.com/58013260/229322812-e76ba6be-7f12-4301-b592-942144440b18.png)

![image](https://user-images.githubusercontent.com/58013260/229322834-0718bf94-635b-470d-ba74-5e00c7f92d4e.png)

![image](https://user-images.githubusercontent.com/58013260/229322841-2d5d51b6-1998-4aae-9ea9-351cb050b741.png)

**Comment by my-name-is-nheo** [comment]
Just updated RN to 0.71 and react to 18.2. Rebuilding now. Will update soon

**Comment by VikasTiwari7** [comment]
its not resolved

**Comment by tructtyoong** [comment]
its not resolved

**Comment by phamhieu1412** [comment]
it not resolved with react-native 0.63.4, node 18

**Comment by elaoshi** [comment]
It's gone by downgrading my version to react-native 0.62.2, node 14.18.1,  I think it happens in the new version.

**Comment by seetha-nandhagopal** [comment]
The issue was closed by downgrading my node version 16 to 14

**Comment by ant100** [comment]
with RN 0.72 you can't downgrade to node version below 16, issue is happening

**Comment by RohithPalagiri-BO** [comment]
Like @ant100 this is still an issue and incredibly frustrating.

**Comment by matt-dalton** [comment]
In case anyone else is struggling after reading the whole internet, for me the answer was to upgrade `react-native-svg-transformer` from [1.10 to 1.30](https://github.com/kristerkari/react-native-svg-transformer/releases). I had already tried things like passing `--openssl-legacy-provider` so that might also be necessary as well.

**Comment by muskan6898** [comment]
I have an another solution for this, please try this one, worked for me.
Fix for ios
In project.pbxproj file, add the below code:
buildSettings = {
NODE_OPTIONS = "--openssl-legacy-provider";
}

For android 
On mac, just run the below command :
export NODE_OPTIONS=--openssl-legacy-provider
then install npm by using npm install

**Comment by kuldeep-maker** [comment]
i am get this issue in android can anyone give me the perfect solution for this

**Comment by wajahat959** [comment]
in my case i have installed "react-native-svg-transformer": "^1.0.0" and the issue is gone everything now working fine.

**Comment by kuldeep-maker** [comment]
@wajahat959 but in my case issue is still there like its born with this project . please suggest me wht to do cause i have chnge the node versions and all installed svg transformer but project still give that error if you have anything that may work for me so please let me know 
thanku

**Comment by sachinar941** [comment]
try https://github.com/facebook/metro/issues/1205#issuecomment-2126933695

**Comment by muskan6898** [comment]
> @wajahat959 but in my case issue is still there like its born with this project . please suggest me wht to do cause i have chnge the node versions and all installed svg transformer but project still give that error if you have anything that may work for me so please let me know thanku

You are facing this on windows or mac?
Try using this solution:

To resolve the issue, set the following environment variable on your system. The method varies depending on whether you're using Windows or macOS.

For Windows
Open Command Prompt (as Administrator).
Run the following command - setx NODE_OPTIONS "--openssl-legacy-provider"

For macOS
Open Terminal & run the following command - export NODE_OPTIONS=--openssl-legacy-provider

After setting this environment variable, your issue should be resolved.

**Comment by mssvijaykumar** [comment]
It works for me :- Open Terminal & run the following command - export NODE_OPTIONS=--openssl-legacy-provider

**Comment by freddi-kit** [comment]
I faced same issue and installing [metro-react-native-babel-transformer](https://www.npmjs.com/package/metro-react-native-babel-transformer) solved it

**Comment by abdulmoizshaikh** [comment]
Here’s a well-formatted GitHub comment to help others facing the same issue:  

---  

### **🚀 Solution for `TypeError: Cannot read properties of undefined (reading 'transformFile')` in React Native 0.73**  

I faced this issue while upgrading React Native from **0.72.17 to 0.73.0** and was able to resolve it by upgrading `react-native-svg-transformer`.  

### **🔍 Error:**  
```bash
error: TypeError: Cannot read properties of undefined (reading 'transformFile')
```

### **✅ Solution:**  
Upgrade **`react-native-svg-transformer`** to the latest compatible version:  
```diff
- "react-native-svg-transformer": "1.0.0"
+ "react-native-svg-transformer": "1.3.0"
```

### **📌 Complete Dependency Update:**  
To ensure full compatibility with React Native 0.73, I also updated these dependencies:  

```diff
- "@babel/core": "^7.20.0"
- "@babel/runtime": "^7.20.0"
- "react-native-svg-transformer": "1.0.0"
- "react-native-gesture-handler": "^2.9.0"
  
+ "@babel/core": "^7.26.10"
+ "@babel/runtime": "^7.27.0"
+ "react-native-svg-transformer": "1.3.0"
+ "react-native-gesture-handler": "2.16.1"
+ "metro-react-native-babel-preset": "^0.77.0"
```

### **🔄 Steps to Apply Fix:**  
1. Update the dependencies in your `package.json`.  
2. Remove `node_modules` and reinstall packages:  
   ```bash
   rm -rf node_modules package-lock.json && npm install
   ```
3. Restart Metro Bundler with cache reset:  
   ```bash
   npx react-native start --reset-cache
   ```

After making these updates, my project built successfully without the `transformFile` error. 🚀  

Hope this helps! Let me know if you have any questions. 😊  

---  

This format makes it easy to read and follow, and it’s structured to help others quickly find the fix. 🚀

**Comment by rustgjini** [comment]
i am getting this issue when i upgraded on expo 54 . I have tried everything whats comented up, any idea what should i try else?
