### ISSUE TITLE
Background blur happens on triggering Keyboard.dismiss in android

### ISSUE THREAD

**Issue by sanjeevkumar91** [facebook/react-native#36774]
### Description

In react-native 0.71.3, Triggering the `Keyboard.dismiss()` function is changing the background color to grey or some overlay to appear. Added minimal code version of snack expo link. Please refer attached screenshots.

Before Keyboard Dismiss:
<img width="317" alt="Screenshot 2023-04-03 at 6 31 28 PM" src="https://user-images.githubusercontent.com/17902574/229517457-66cb533d-9db2-42da-b6e3-e8925b70ce88.png">

After KeyBoard Dismiss:
<img width="324" alt="Screenshot 2023-04-03 at 6 27 26 PM" src="https://user-images.githubusercontent.com/17902574/229516532-1d4ca147-0846-4311-9761-a3d1e786d9b8.png">

Note: We tried removing `react-native-keyboard-aware-scroll-view` we still faced the same blur issue with some other elements, But we couldn't able to create this behavior in snack eg shared.

### React Native Version

0.71.3

### Output of `npx react-native info`

System:
    OS: macOS 12.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 64.08 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.10.0 - ~/.nvm/versions/node/v16.10.0/bin/node
    Yarn: 3.2.0 - ~/.nvm/versions/node/v16.10.0/bin/yarn
    npm: 7.24.0 - ~/.nvm/versions/node/v16.10.0/bin/npm
    Watchman: 2022.10.17.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/lib/ruby/gems/2.7.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 27, 28, 29, 30, 31, 33
      Build Tools: 25.0.3, 26.0.3, 27.0.3, 28.0.3, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 33.0.0
      System Images: android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-31 | Intel x86 Atom_64, android-31 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.3
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: 0.71.3

### Steps to reproduce

- Open the snack expo link - https://snack.expo.dev/@a.sanjeevkumar91/textinput-example
- Enter more than 5 characters in the Text Input
- Background color is greyed out when the keyboard is dismissed.

### Snack, code example, screenshot, or link to a repository

https://snack.expo.dev/@a.sanjeevkumar91/textinput-example

**Comment by sanjeevkumar91** [comment]
We tried it on the react native version 0.71.3 and faced the same issue.

**Comment by sanjeevkumar91** [comment]
@TheMissouri We checked removing the keyboard-aware scroll view as well. It is still happening for other elements like buttons and icons. 

Please refer to this snack expo link -- https://snack.expo.dev/@a.sanjeevkumar91/keyboard-blur-issue-button

Steps to reproduce without keyboard-aware scroll view:
- Enter more than 5 characters in the Text Input
- The color of the Button will get changed since it is focused/highlighted.

**Comment by correadevuk** [comment]
I'm experiencing the same issue with ScrollView when programmatically dismissing the keyboard using the Keyboard.dismiss() function in React Native. After calling Keyboard.dismiss(), all children inside the ScrollView are rendered with an unwanted grey background. This occurs every time the keyboard is dismissed.

@sanjeevkumar91 I'm setting "scrollEnabled" to false before calling Keyboard.dismiss() and that resolved the issue for me.

`<ScrollView
            keyboardShouldPersistTaps="always"
            contentContainerStyle={{
              flexGrow: 1,
              justifyContent: "space-between",
            }}
            scrollEnabled={!isLoading}
          >
            {children}
          </ScrollView>`

**Comment by sanjeevkumar91** [comment]
@correadevuk For me this issue is happening without a scroll view as well. Refer: [https://snack.expo.dev/@a.sanjeevkumar91/keyboard-blur-issue-button](snack)

**Comment by alainib** [comment]
i have the same bug with FlatList but not able to fix it yet
