### ISSUE TITLE
My App is crashing when I invoke RN.restart or Reload on Terminal, with IOS 

### ISSUE THREAD

**Issue by Sekiro-kost** [facebook/react-native#36776]
### Description

Hello

My App is crashing when I invoke RN.restart or Reload on Terminal, with IOS 

```
import RNRestart from "react-native-restart";


 const resetButton = () => {
    dispatch(deleteAllBoxs());
    dispatch(deleteMarket());
    dispatch(clearGeoloc());
    dispatch(clearNotif());
    setTimeout(()=>{
      RNRestart.restart();
    },300);
  } 

```
ERROR LOG XCODE:

2023-03-31 15:47:23.359754+0200 mycompany[64349:14228430] [native] Invalidating <RCTCxxBridge: 0x10ae1c010> (parent: <RCTBridge: 0x282533d40>, executor: (null))

I tried to comment my dispatch, and leave only restart, but I have the same issue. 

### React Native Version

0.71.5

### Output of `npx react-native info`

System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1
    Memory: 62.84 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.8.1 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.5.1 - /opt/homebrew/bin/npm
    Watchman: 2023.03.13.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0-adoptopenjdk - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.5 => 0.71.5 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Everything else in the application works fine (data collection via my home automation controller, data synchronization, custom menu creation, etc.)

I need to reload the application to check the action of the notifications, geolocation etcc. 

### Snack, code example, screenshot, or link to a repository

![Capture d’écran 2023-04-03 à 17 32 05](https://user-images.githubusercontent.com/85112677/229557425-e139c1f9-41d0-412d-9423-e328eed26c0d.png)

**Comment by blakef** [comment]
This is a question best put to the 3rd part extension, maybe file the issue there? https://github.com/avishayil/react-native-restart
