### ISSUE TITLE
Android debugging in Chrome is not working: 'Uncaught NetworkError'

### ISSUE THREAD

**Issue by Reparadocs** [facebook/react-native#3677]
I am creating an Android React Native application and everything seems to be working fine except when I attempt to debug the program. When I attempt to do this, the app just becomes a blank white screen and the Chrome console has this error:

Uncaught NetworkError: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'http://localhost:8081/index.android.bundle?platform=android&dev=true' failed to load.

A few seconds later the app crashes. I don't think I'm doing anything out of the ordinary, just started this project

**Comment by kevtastic** [comment]
what did you do to fix this?

**Comment by ashleydw** [comment]
Would also like to know @Reparadocs

**Comment by Reparadocs** [comment]
Apologies guys, I completely forgot what I did to rectify the problem, the next time I close an issue I'll be sure to include what I did to fix it, sorry again :(

**Comment by mateuszwozniak** [comment]
I have actually the same issue but on iOS after updating react-native from version 0.11.0 to 0.14.2. I guess it's not about enabled debugging because I just get empty screen right after app starts no matter if debugging is enabled or not.

**Comment by adarshmuthappa** [comment]
I disabled chrome debugging and the error went away. Don't know why though.

**Comment by adarshmuthappa** [comment]
Ah, my mistake. 
In **AppDelegate.m** I had commented out - 
  jsCodeLocation = [NSURL URLWithString:@"http://localhost:8081/index.ios.bundle?platform=ios&dev=true"];

and uncommented - 
  jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];

Did this to run on device. Works now.

**Comment by danawoodman** [comment]
For me, going into XCode and in the main menu going to `Product => Clean` did the trick.
