### ISSUE TITLE
[Upgrade Issue] React Native 0.71.6 is missing in via yarn repository

### ISSUE THREAD

**Issue by JacobFJ** [facebook/react-native#36786]
### Description

Unable to retrieved 071.6 on yarn repository

### React Native Version

0.71.5-0.71.6

### Output of `npx react-native info`

n/a

### Steps to reproduce

Upgrade React-native using yarn.

### Snack, code example, screenshot, or link to a repository
<img width="468" alt="Screenshot 2023-04-04 at 12 57 32 PM" src="https://user-images.githubusercontent.com/40719101/229691006-b2594d34-42fd-41e1-9fea-1ee6b916865e.png">

https://snack.expo.dev/

**Comment by blakef** [comment]
You were just a little ahead of us 😀.  [Just released](https://github.com/facebook/react-native/issues/36739#issuecomment-1495818734)

<img width="259" alt="CleanShot 2023-04-04 at 12 43 55@2x" src="https://user-images.githubusercontent.com/49578/229781153-23492efc-1125-480d-af75-1140b53fa78c.png">

**Comment by JacobFJ** [comment]
@blakef sorry to mention you. It seems okay with npm but as I said to the title it cannot resolved the 0.71.6 on ```yarrn``` repository.

**Comment by JacobFJ** [comment]
As of now:
<img width="495" alt="Screenshot 2023-04-04 at 10 38 19 PM" src="https://user-images.githubusercontent.com/40719101/229827727-e36583a3-52e7-411b-977f-e0cdd4db2b60.png">

**Comment by blakef** [comment]
No worries 😋, but there's something going on with your setup (maybe it's a [yarn thing](https://yarnpkg.com/cli/cache/clean)?):

<img width="299" alt="CleanShot 2023-04-04 at 16 01 35@2x" src="https://user-images.githubusercontent.com/49578/229834881-f67abe85-7219-427d-af04-1b5b71b63880.png">
