### ISSUE TITLE
React Native Flatlist Performance Issues

### ISSUE THREAD

**Issue by iasreact1** [facebook/react-native#36818]
### Description

I used Flatlist and my item render video or may be image, video  using `react-native-video` and now when scroll it stucks and some times it shows ANR and app get crashed,
some times it shows ` VirtualizedList: You have a large list that is slow to update - make sure your renderItem function renders components that follow React performance best practices like PureComponent, shouldComponentUpdate, etc. {"contentLength": 11372.3330078125, "dt": 559, "prevDt": 11728}` and when i use modal open for that flatlist open and pass data to the modal using state varibale it is too much slow to process for the later items of the flatlist and some times it showing the warning `Please report: Excessive number of pending callbacks: 501. Some pending callbacks that might have leaked by never being called from native code: {"126615":{"module":"NativeAnimatedModule","method":"startAnimatingNode"}` 
please help to overcome it..new to react-Native, i used `react-native-functional-component` and  cannot use pureComponent as it class component, and my flatlist is like that 
`   <FlatList
                removeClippedSubviews={true}
                maxToRenderPerBatch={3}
                initialNumToRender={2}
                data={postListData}
                onEndReached={LoadMore}
                onEndReachedThreshold={0}
                style={{ marginBottom: height * 0.06 }}
                showsVerticalScrollIndicator={false}
                keyExtractor={(item, index) => item.id + index.toString()}
                renderItem={({ item, index }) => (
                    <RenderFeed
                        index={index}
                        item={item}
                        viewable={Viewable}
                    />
                )}
            />`

### React Native Version

0.70.6

### Output of `npx react-native info`

..

### Steps to reproduce

When i scroll the flatlis , that conatin video or Image

### Snack, code example, screenshot, or link to a repository

`   <FlatList
                removeClippedSubviews={true}
                maxToRenderPerBatch={3}
                initialNumToRender={2}
                data={postListData}
                onEndReached={LoadMore}
                onEndReachedThreshold={0}
                style={{ marginBottom: height * 0.06 }}
                showsVerticalScrollIndicator={false}
                // refreshing={refresh}
                // onRefresh={handleRefresh}
                keyExtractor={(item, index) => item.id + index.toString()}
                renderItem={({ item, index }) => (
                    <RenderFeed
                        index={index}
                        item={item}
                        viewable={Viewable}
                    />
                )}
            />`

**Comment by iasreact1** [comment]
Same Problem for the latest version Please help

**Comment by iasreact1** [comment]
Please help some one, i am new to react-native, and here is also some problem when i open a modal from later item (i.e, next to 10 th or next index) and pass value to the modal using state hook then it becomes too much slow during its open and some times it gets crash the app...please help what to do ?

**Comment by vishalSharmaCfcs** [comment]
show me the code brother

**Comment by iasreact1** [comment]
` const RenderFeed = React.memo(({ index, item }) => {
        let textLength = item.post.postCaption.length;
        let newtext = item.post.postCaption.slice(0, 117);
        let totalImageLength = item.post.content.length;
        const HASHTAG_FORMATTER = string => {
            return string.split(/((?:^|\s)(?:#[a-z\d-] || @[a-z\d-]+))/gi).filter(Boolean).map((v, i) => {
                if (v.includes('#') || v.includes('@')) {
                    return <Text key={i} onPress={() => {
                        props.navigation.navigate('HashPage', {
                            hashVal: v,
                            idCheck: "post",
                        })
                    }
                    } style={{ color: '#a93efc' }}>{v}</Text>
                } else {
                    return <Text key={i}>{v}</Text>
                }
            })
        };
        let newVideourl;
        let thumbImagee;
        if (item.post.content[0].fileType == 'VIDEO') {
            newVideourl = `${item.post.content[0].file}`
            thumbImagee = `${item.post.content[0].thumb}`
        }
        let newArray = Array();
        if (item.post.content[0].fileType == 'IMAGE') {
            for (let i = 0; i < totalImageLength; i++) {
                newArray.push(`${item.post.content[i].file}`)
            }
        }
        if (indexValue != null && comCount != null) {
            console.log("commented index", indexValue);
            console.log("commented count", comCount);
            postListData[indexValue].post.totalComment = comCount;
        }
        const dLike = (index) => {
            if (postListData[index].isLiked == 1) {
                postListData[index].isLiked = 0;
                postListData[index].post.totalLike = postListData[index].post.totalLike - 1;
            } else {
                postListData[index].isLiked = 1;
                postListData[index].post.totalLike = postListData[index].post.totalLike + 1;
            }
            setVal(!val);
        }
        const [curInd, setCurIndex] = useState('');
        const [videoLoadOpacity, setVideoLoadOpacity] = useState(0);
        const [isPlaying, setIsPlaying] = useState(true);
        const [viewPausedIccon, setViewPausedIcon] = useState(false);
        const [isMuted, setIsMuted] = useState(false);
        const [val, setVal] = useState(false);
        let commentTime = new Date(item.post.createdAt);
        let exact_date = item.post.createdAt.split(" ")[0];
        let date = new Date(exact_date);
        let post_date = date.toDateString();
        let currentTime = new Date();
        let gap = currentTime - commentTime;
        let gapinSec = gap / 1000;
        let gapinMin = gapinSec / 60;
        let gapinHour = gapinMin / 60;
        let gapinDays = gapinHour / 24;
        let gapinMonth = gapinDays / 30;
        let gapinYr = gapinMonth / 12;
        let actualgap;
        if (gapinYr > 1) {
            let gaping = Math.floor(gapinYr);
            actualgap = post_date;
        } else if (gapinMonth > 1) {
            let gaping = Math.floor(gapinMonth);
            actualgap = post_date;
        } else if (gapinDays == 1) {
            let gaping = Math.floor(gapinDays);
            actualgap = "yesterday";
        } else if (gapinDays > 1) {
            actualgap = post_date;
        }
        else if (gapinHour > 1) {
            let gaping = Math.floor(gapinHour);
            actualgap = gaping + 'hr';
        } else if (gapinMin > 1) {
            let gaping = Math.floor(gapinMin);
            actualgap = gaping + "min"
        } else if (gapinSec > 1) {
            let gaping = Math.floor(gapinSec);
            actualgap = gaping + "sec"
        }

        return (
            <View style={{ width: "100%", alignSelf: 'center', marginTop: height * 0.01, backgroundColor: '#fff', borderRadius: 4, elevation: 5, shadowColor: '#cccccc' }}>
                <View style={{ width: "98%", height: height * 0.06, alignSelf: "center", flexDirection: 'row', marginTop: height * 0.014, }}>
                    <TouchableOpacity style={{ flexDirection: 'row' }}
                        onPress={() => {
                            AsyncStorage.setItem("uniqueId", JSON.stringify(item.user.userId));
                            if (item.user.userId != user.user.userId) {
                                props.navigation.navigate('IndividualProfile', {
                                    userData: item.user,
                                })
                            }
                        }}
                        disabled={item.user.userId == user.user.userId ? true : false}
                    >
                        <Image source={item.user.profilePic != "NA" ? { uri: item.user.profilePic } : MyProfile} resizeMode="contain" style={{ width: width * 0.1, height: width * 0.1, borderRadius: width * 0.1 / 2, marginLeft: width * 0.02, marginTop: height * 0.003, }} />
                        <View>
                            <View style={{flexDirection:'row',width:width*0.6}}>
                            <Text style={{ marginLeft: width * 0.03, marginTop: height * 0.005, fontSize: width * 0.045, fontWeight: "bold", color: "#4b164c", height: height * 0.03 }}>{item.user.name}</Text>
                            {  item.user.isNewUser == 1 &&
                             <Image  source={NewUserBadge} resizeMode="contain" style={{width:width*0.07, height:width*0.05,marginLeft:6,marginTop:6}}/>
                            }
                            </View>
                            <Text style={{ fontSize: 8, marginLeft: width * 0.03 }}>{actualgap}</Text>
                        </View>
                    </TouchableOpacity>
                    <Pressable disabled={(item.user.userId == user.user.userId) ? true : false}
                        onPress={() => { 
                            openFeedMoreModel(item); 
                            // openTypeModal(item);
                        }}
                    >
                        <Image source={More} resizeMode="contain" style={{ width: width * 0.044, height: width * 0.044, marginLeft: width * 0.13, marginTop: height * 0.03, borderRadius: 22, }} />
                    </Pressable>
                     {showFeedMoreModal == true &&
                        <FeedMoreModal
                            showModal={showFeedMoreModal}
                            showingModal={openFeedMoreModel}
                            onTouchOutside={closeFeedMoreModal}
                            setmodal={setShowFeedMoreModal}
                            title="Create"
                            navigation={props.navigation}
                            okButtonClicked={() => {
                                goReportOption();
                            }}
                            goItemUserClicked={() =>{
                                goProfile();
                            }}
                        />
                    } 
                </View>
                {item.post.postCaption != "NA" &&
                    <View style={{ width: "98%", alignSelf: "center", flexDirection: 'row', }}>
                        <Text style={{ fontSize: width * 0.03, color: "#4b164c", marginLeft: width * 0.02, marginRight: width * 0.02, marginBottom: 2 }}>{item.post.postCaption == "NA" ? undefined : HASHTAG_FORMATTER(item.post.postCaption)}</Text>
                    </View>
                }
                <View style={{ width: "100%", height: height * 0.4, marginTop: 2 }}>
                    {item.post.content[0].fileType == 'IMAGE' ?
                        <SliderBox
                            images={newArray}
                            style={styles.slide}
                            sliderBoxHeight={300}
                            currentImageEmitter={(index) => setCurIndex(index)}
                            dotColor="yellow"
                            disableOnPress={true}
                            inactiveDotColor="#90A4AE"
                            dotStyle={{
                                width: 4,
                                height: 2,
                                borderRadius: 2,
                                marginHorizontal: 0,
                                padding: 0,
                                margin: 0,
                            }}
                        /> :
                        <View>
                            {/* <PlayVideos videoUrl={newVideourl} "https://www.rmp-streaming.com/media/big-buck-bunny-360p.mp4"
                             viewable={viewable} 
                             postid={item.post.postId}
                             /> */}
                            <Video source={{ uri: convertToProxyURL(newVideourl) }}
                                ref={player}
                                poster={thumbImagee}
                                posterResizeMode='cover'
                                onBuffer={onBuffer}
                                useTextureView={false}
                                playInBackground={false}
                                playWhenInactive={false}
                                disableFocus={true}
                                onError={onError}
                                resizeMode="cover"
                                muted={isMuted}
                                paused={isPlaying}
                                onLoadStart={() => {
                                    setVideoLoadOpacity(1);
                                }}
                                onLoad={() => {
                                    // player.current.seek(0);
                                    setVideoLoadOpacity(0);
                                }}
                                onEnd={() => console.log("end Video")}
                                style={styles.backgroundVideo} />
                            <ActivityIndicator
                                animating
                                size="large"
                                color="red"
                                style={[styles.activityIndicator, { opacity: videoLoadOpacity }]}
                            />
                            <TouchableOpacity
                                onPress={() => { setIsMuted(m => !m) }}
                            >
                                <Image source={isMuted == false ? IcSound : IcMute} resizeMode="contain" style={{ width: width * 0.05, height: width * 0.05, position: 'absolute', bottom: 0, marginBottom: height * 0.362, marginLeft: width * 0.91 }} />
                            </TouchableOpacity>
                            <TouchableOpacity style={{ width: "70%", height: height * 0.27, position: 'absolute', marginLeft: width * 0.1, justifyContent: 'center', alignItems: 'center' }}
                                onPress={() => {
                                    setIsPlaying(p => !p); setViewPausedIcon(true);
                                }}
                            >
                                {viewPausedIccon == true &&
                                    <Image source={isPlaying == false ? PauseIc : PlayIc} resizeMode="contain" style={{ width: width * 0.07, height: width * 0.07, marginLeft: width * 0.08, marginTop: 100 }} />
                                }
                            </TouchableOpacity>
                            {/* <TouchableOpacity style={{ width: "100%", height: height * 0.4, backgroundColor: "#BFC0C1" }} activeOpacity={0.8}
                                onPress={() => props.navigation.navigate('SeenVideos', {
                                    videofile: newVideourl
                                })}
                            >
                                <Image source={{ uri: thumbImagee }} resizeMode="cover" style={{ width: "100%", height: height * 0.4 }} />
                                <Image source={require('../assets/icon_play_5.png')} resizeMode="contain" style={{ width: width * 0.18, height: width * 0.18, position: 'absolute', top: height * 0.15, marginLeft: width * 0.42 }} />
                            </TouchableOpacity> */}
                        </View>
                    }
                    {item.post.content[0].fileType == 'IMAGE' ? totalImageLength != 1 &&
                        <View style={{ width: width * 0.13, height: 25, borderRadius: 8, backgroundColor: '#4b164c', position: 'absolute', marginLeft: width * 0.83, marginTop: height * 0.02, justifyContent: 'center', alignItems: 'center' }}>
                            <Text style={{ color: "#fff" }}>{curInd + 1}/{totalImageLength}</Text>
                        </View> : undefined
                    }
                </View>
                <View style={{ width: "96%", height: height * 0.08, alignSelf: "center", marginTop: height * 0.01, flexDirection: 'row' }}>
                    <View style={{ width: "40%", height: height * 0.05, flexDirection: "row", justifyContent: 'space-evenly' }}>
                        <TouchableOpacity
                            onPress={() => {

                                dLike(index); doLikeOnPost(item.post.postId, index)

                            }}
                        >
                            <Image source={item.isLiked == 0 ? Heart : HeartRed} resizeMode="contain" style={{ width: width * 0.075, height: width * 0.075, marginTop: height * 0.01 }} />
                            <TouchableOpacity
                                style={{ marginLeft: 3, marginTop: 2, width: 25, justifyContent: 'center', alignItems: 'center' }}
                                onPress={() => props.navigation.navigate('CountLikes', {
                                    postId: item.post.postId,
                                })}>
                                <Text style={{ fontSize: 10, fontWeight: '600', color: isDarkMode ? "#000" : undefined }}>{item.post.totalLike}</Text>
                            </TouchableOpacity>
                        </TouchableOpacity>
                        <TouchableOpacity
                            onPress={() => {
                                Global.indexVal = index; indexCount(index);
                                props.navigation.navigate('CommentPage', {
                                    postId: item.post.postId,
                                    userId: item.user.userId,
                                });
                            }}
                        >
   `This is the renderItem and the flatlist is 
   `<FlatList removeClippedSubviews={true} maxToRenderPerBatch={3} initialNumToRender={2} data={postListData} onEndReached={LoadMore} onEndReachedThreshold={0} style={{ marginBottom: height * 0.06 }} showsVerticalScrollIndicator={false} keyExtractor={(item, index) => item.id + index.toString()} renderItem={({ item, index }) => ( <RenderFeed index={index} item={item} viewable={Viewable} /> )} />`

**Comment by NickGerleman** [comment]
There are a lot of variables that can effect performance, so I don't think the React Native team will be able to debug your specific scenario/code, but here's a resource you might find useful. Esp the guidance on memoization (your components will otherwise be re-rendered many times). https://reactnative.dev/docs/optimizing-flatlist-configuration
