### ISSUE TITLE
React Native Auto refreshing is not working

### ISSUE THREAD

**Issue by salahbm** [facebook/react-native#36829]
### Description

I dont really know the exact reason why auto refreshing is stopped but know that it happened I installed react-native-reanimated library. After that I uninstalled and run git reset --hard to undo all, unfortunately didnt help.
THE PROBLEM is whenever I edit something it does not edit nor log anything in terminal(metro). But I can see my logs through the chrome debugger, and also able to fast refresh.

### React Native Version

0.73.7

### Output of `npx react-native info`

System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i3-10105 CPU @ 3.70GHz
    Memory: 5.21 GB / 15.87 GB
  Binaries:
    Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 28, 31, 33
      Build Tools: 28.0.3, 30.0.3, 31.0.0, 33.0.0
      System Images: android-28 | Google APIs Intel x86 Atom, android-31 | Intel x86 Atom_64, android-31 | Google Play Intel x86 Atom_64, android-33 | Google APIs Intel x86_64 Atom
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: AI-213.7172.25.2113.9123335
    Visual Studio: Not Found
  Languages:
    Java: 11.0.18
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.3 => 0.71.3
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. Install the react-native-reanimated library in your project.
2. Observe that the auto-refreshing functionality has stopped working after installing the library.
3. Uninstall the react-native-reanimated library and run "git reset --hard" to undo all changes.
4. Verify that the auto-refreshing functionality is still not working.
5. Try editing some code and observe that the changes are not reflected in the app.
6. Check the terminal (metro) for any error messages or logs related to the issue.
7. Verify that you can see the logs through the Chrome debugger.
8. Confirm that you are able to use fast refresh to see the changes you make in the code.

Provide any additional information that might be helpful for developers to identify and fix the issue.

### Snack, code example, screenshot, or link to a repository

 const checkLoggedInUser = async () => {
      try {
        const user = await AsyncStorage.getItem('loggedInUser');
        console.log(user);
        if (user) {
          setLoggedInUser(JSON.parse(user));
        }
      } catch (error) {
        console.log(error);
      }
    };
    checkLoggedInUser();
  }, []);
  
// LOG In Terminal
 // Does not display anything
  info Reloading app...
 BUNDLE  ./index.js

**Comment by cortinico** [comment]
> but know that it happened I installed react-native-reanimated library

Hi @salahbm 
Thanks for reporting this issue.

As this happens as soon as you install reanimated, you should open this issue against them:

https://github.com/software-mansion/react-native-reanimated/issues

Also please clarify which version you're using as there is no React Native 0.73.x

I'll be closing this but feel free to reopen if the other repo points back to us as a issue in the core of React Native.

**Comment by salahbm** [comment]
Thanks for your reply, actually I found the solution . I have removed   ### "plugins": ["@babel/plugin-proposal-class-properties"] and  [ '@babel/plugin-proposal-private-methods', { loose: true, }, ], from ### babel.config.js; made the project work again. Leaving this comment incase someone needs in the future. Thanks

**Comment by mattpatterson94** [comment]
Thank you so much for your comment @salahbm. Was bashing my head against a wall and this fixed my issue. You legend!

Did you manage to find a way to keep the plugins and fast refresh?

**Comment by Moatezz** [comment]
still having the same problem and I have none of the babel preset you mentioned to remove, and I'm using android 13 and RN v0.72.6

**Comment by raazseth** [comment]
Does anyone have some idea on how to solve this issue?
