### ISSUE TITLE
Template `tsconfig.json` does not support BigInts

### ISSUE THREAD

**Issue by paulmillr** [facebook/react-native#36830]
### Description

RN 0.70 introducted partial bigint support: `BigInt(1) + BigInt(2)` now works.

But it is not full. `1n + 2n` still doesn't work.

This is a big deal.

This is continuation of facebook/react-native#34603 which was unnecessarily closed.

### React Native Version

0.71.0

**Comment by cortinico** [comment]
Moving back to React Native.
We need some investigation to understand what's going on with BigInt.

A repro would be a good starting point. Here a template to create them: https://github.com/react-native-community/reproducer-react-native

**Comment by robhogan** [comment]
@paulmillr I haven't been able to reproduce this on iOS with Hermes, RN 0.71.6, with an out-of-the-box `react-native init` app. I've also checked that production bundles are correctly minified with both `terser` (the new default) and `uglify-es` (the old one). A colleague has checked Android as well. Could you share a bit more?

<img width="488" alt="image" src="https://user-images.githubusercontent.com/2590098/230455415-fd68ed39-4284-4919-b7ec-3407da037f99.png">

**Comment by paulmillr** [comment]
@robhogan if you can't reproduce, that's another question.

On it. Will repro and ping you back.

**Comment by sethwebster** [comment]
Hey, @paulmillr -- thanks for your persistence here.

To provide a bit of context, while we do get paid to work on React, historically we haven't been able to prioritize incoming issue triage compared to the work on already confirmed issues. This may come across as bureaucratic, but it was mostly due to support being ad-hoc and dependent on individual engineers' availability. This is something we're working to fix. We finally have a dedicated team for managing our OSS repos/issues, and I expect this to improve this year. 🎉 

We appreciate your work on Chokidar. I know doing OSS work can feel pretty thankless but you're doing awesome work.

**Comment by paulmillr** [comment]
Appreciate for understanding folks.

I've just tested it: the issue can be reproduced by running `npx tsc` in the project directory, or using an editor, linter, other tool (vscode). Not sure what's the best way to commit this to run on github CI.

Reason for this is the default `tsconfig` setting: `lib: es2019`. es2019 does not support bigints, only es2020 does. Bigints seem to work both with and without hermes; there is no necessity to use es2019 at this point.

<img width="661" alt="tooling" src="https://user-images.githubusercontent.com/574696/230474960-8bb7f587-2d08-4220-8a5a-74131294df1e.png">

**Comment by robhogan** [comment]
Ah, that makes sense! Thanks - we’ll get that fixed.

**Comment by NickGerleman** [comment]
@lunaleaps @rickhanlonii should both have merge permissions to https://github.com/tsconfig/bases/blob/main/bases/react-native.json

Note that, at least in the default template we provide, tsc is used for type checking, but not code generation.

**Comment by robhogan** [comment]
We’ll want to be a bit careful about the choice here too - we support parts of ES2020 on all engines (after transforms), including `es2020.bigint`, but not others (`es2020.sharedmememory`?), so entirely switching to `es2020` isn’t going to be quite right.

`tsconfig.json` allows us to pick and choose, so we’ll need to check our capabilities against the choices here:
https://github.com/microsoft/TypeScript/tree/main/src/lib

**Comment by blakef** [comment]
@paulmillr while we get that sorted out, are you unblocked by adjusting your project config tot use `es2020.bigint`?

**Comment by paulmillr** [comment]
@blakef

```
"target": "es2019",
"lib": ["es2019", "es2020.bigint"],
```

^ This doesn't work for bigint literals (`123n`).


```
"target": "es2020",
"lib": ["es2019", "es2020.bigint"],
```

^ This works properly for bigint literals and non-literals.

Target is what defines syntax; lib defines features if i'm not mistaken.

**Comment by NickGerleman** [comment]
The template tsconfig already uses `target: esnext`, so no changes needed to target.

There are some libs we should add like "bigint" and "intl". Will do a quick audit of what polyfills we should add.

**Comment by NickGerleman** [comment]
https://github.com/reactwg/react-native-releases/discussions/54#discussioncomment-5650114 requests picking into 0.72 before we release.
