### ISSUE TITLE
Text component adds a linebreak when string content is equal to width of component

### ISSUE THREAD

**Issue by Sameer-Chhadia** [facebook/react-native#36831]
### Description

Describe what you expected to happen:
Some text should either wrap to the new line or a new line should not be created.

Actual Behavior
In my case only in Android but for some other user's issues in both IOS and Android (ex. #27172 and #24674), when the length of the text string is the width of the Text component, it adds a linebreak, creating extra space below text elements.

My guess is that there's some sort of improper rounding happening with float density pixels or something.

ANDROID:
![Screenshot_20230406-173331_2](https://user-images.githubusercontent.com/115687024/230374187-0c669bbc-2394-4d7f-ae11-1fcdce227533.png)

IOS:
![simulator_screenshot_4D7CEBAE-61B4-4773-8C19-21FF8ED4503F](https://user-images.githubusercontent.com/115687024/230374425-4350e2e5-d52e-404e-9ad2-060c181d9808.png)

### React Native Version

0.70.6

### Output of `npx react-native info`

System:
    OS: macOS 12.6
    CPU: (12) x64 Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz
    Memory: 46.98 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 9.6.3 - /usr/local/bin/npm
    Watchman: 2023.03.27.00 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8512546
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  npmPackages:
    react-native: ^0.61.3 => 0.61.3 
  npmGlobalPackages:
    react-native: 0.61.3

### Steps to reproduce

1. Add a Text component anywhere in project (add another component underneath it or use a border - needed to see the issue)
2. Add some text to get it to reach the exact width of the Text component - this may take a few attempts as not all characters have the same width and may require using some punctuation as well
3. The text will introduce an unwanted linebreak without any characters moving with it, creating a new blank line with no text

### Snack, code example, screenshot, or link to a repository

ANDROID:
![Screenshot_20230406-173331_2](https://user-images.githubusercontent.com/115687024/230375336-45f84245-0397-41b3-b3ed-3d27302dd871.png)

IOS:
![simulator_screenshot_6B682798-50E3-4ACC-8D3E-55CF34A9BDD7](https://user-images.githubusercontent.com/115687024/230375415-6d3283c4-96f0-443b-a696-015eb701ff0c.png)

**Comment by fabriziobertoglio1987** [comment]
Do you still experience this issue? 

I have four years of experience maintaining facebook/react-native and I specialize in the Text and TextInput components. I currently have 58 [facebook/react-native PRs](https://github.com/facebook/react-native/pulls?q=is%3Apr+author%3Afabriziobertoglio1987+). 

If you still experience this issue, I will prepare a patched release with the fix.

Thanks a lot

**Comment by Im2rnado** [comment]
I still experience this when text align is justify.

**Comment by awj5** [comment]
A little hack that worked for me was setting the width of the text component to 100.1%.

**Comment by PointMountain** [comment]
I temporarily fixed it using the letter-spacing property.
