### ISSUE TITLE
Android Push Notification

### ISSUE THREAD

**Issue by jihopark** [facebook/react-native#3683]
Hi, I am now experimenting with React Native to build apps for both platforms to be on production.
However, I cannot find enough resources to work push notifications in Android platform (using GCM). Is it yet to be implemented? Can anyone give me some resource to test if it works?

**Comment by divyenduz** [comment]
You get a generated Android project with a React Native app. You can always jump into Java and implement push notification the old way. I will share any react native specific resources I come across in a while.

**Comment by hswolff** [comment]
I recently got this working in my project. Deserves a mini write up but the short of it is you need to do some native Java/Android work to set-up GCM in there. FYI I used this example project as a working example and it proved immensely helpful when setting up my own code: https://github.com/googlesamples/google-services/tree/master/android/gcm

**Comment by mlabrum** [comment]
Looks like someone has implemented it https://github.com/oney/react-native-gcm-android

**Comment by liesislukas** [comment]
https://github.com/oney/react-native-gcm-android works well with current RN version (v0.20) :+1:

**Comment by satya164** [comment]
Duplicate of #3423
