### ISSUE TITLE
[Android] Horizontal ScrollView doesn't update its width on children update

### ISSUE THREAD

**Issue by sergionsz** [facebook/react-native#36845]
### Description

On Android, after scrolling all the way to the end, when removing an item from a horizontal ScrollView, the width of the ScrollView doesn't update, leaving empty space at the end

**How it looks on Android**
![Android](https://user-images.githubusercontent.com/4761560/230499239-e517947a-891d-404b-83fc-df10124d8175.gif)

**How it looks on iOS**
![ios](https://user-images.githubusercontent.com/4761560/230499265-11fef489-f048-49b9-82cc-6ab8d4eba880.gif)

You can see it in action [here](https://snack.expo.dev/9BvcfYiY0?platform=android)

### React Native Version

0.70.8

### Output of `npx react-native info`

System:
    OS: macOS 13.0
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 226.39 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.18.2 - ~/.volta/tools/image/node/14.18.2/bin/node
    Yarn: 1.22.10 - ~/.volta/tools/image/yarn/1.22.10/bin/yarn
    npm: 6.14.15 - ~/.volta/tools/image/node/14.18.2/bin/npm
    Watchman: 2023.01.23.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 23, 29, 30, 33
      Build Tools: 28.0.2, 28.0.3, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 31.0.0, 33.0.0
      System Images: android-28 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom_64, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.13 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.8 => 0.70.8
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

- Create a horizontal ScrollView
- Open on Android
- Scroll to the end
- Remove some children

### Snack, code example, screenshot, or link to a repository

https://snack.expo.dev/9BvcfYiY0?platform=android

**Comment by Navipro70** [comment]
Do we have a solution except scrollToEnd()?

**Comment by rankangkang** [comment]
It seems to work well on iOS and Android 12 and above, but this issue occurs on Android versions below 12. Manually triggering `scrollTo` might be a solution.
