### ISSUE TITLE
[Android] [TextInput] Error while updating property 'textAlign' of a view managed by: AndroidTextInput

### ISSUE THREAD

**Issue by kusamakura** [facebook/react-native#3684]
I get the following error when I use `textAlign` in the `style` prop of TextInput in Android.

I'm using react-native 0.13.1.

![screenshot 2015-10-26 18 20 03](https://cloud.githubusercontent.com/assets/882152/10726533/2fcbef58-7c0e-11e5-950a-b48fc52460b4.png)

**Comment by ide** [comment]
Text align on android is a top level prop instead of a style prop like it is on the other platforms. We should probably fix this.

**Comment by trave7er** [comment]
I opened a PR regarding this issue: https://github.com/facebook/react-native/pull/4364

**Comment by soxunyi** [comment]
<TextInput style={styles.textInput} textAlign='center' placeholder='input text'/>

**Comment by trave7er** [comment]
https://github.com/facebook/react-native/pull/4481

**Comment by bartolkaruza** [comment]
Following #4481 it suggests that this should be fixed in 0.19. I'm still getting this issue after upgrading. Did the fix make it in 0.19?

**Comment by mkonicek** [comment]
@bartolkaruza Yes the fix is in 0.19, here's the 0.19 branch: https://github.com/facebook/react-native/commits/0.19-stable

**Comment by satya164** [comment]
Closing this since this seems to be fixed. Let's re-open if this is not the case.
