### ISSUE TITLE
Keyboard freeze on production mode after writing

### ISSUE THREAD

**Issue by tomasruffa** [facebook/react-native#36859]
### Description

Hi guys I'm facing an issue using React native that happens in iOS that is when I'm typing with the keyboard after few typings start to be freezing I will attach a video bellow. The funny thing its only happening in prod mode (app on Testflight or App store) but when Im trying to reproduce into the debug mode never happens :(. On my real device Iphone 14 Pro Max I tried on OS 16.2.0 And 16.4.1. Btw I tried to report the crash but there is no information attached on that report from Testflight too

"react": "18.1.0",
"react-native": "0.70.4",

### React Native Version

0.70.4

### Output of `npx react-native info`

System:
    OS: macOS 13.0
    CPU: (10) x64 Apple M1 Pro
    Memory: 348.55 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7935034
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.4 => 0.70.4
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Just need to try write into a text field and starts to write quickly, then the app starts to be freezing.

### Snack, code example, screenshot, or link to a repository

https://user-images.githubusercontent.com/45461281/230972071-4ba7df13-cb25-47d8-869b-1b73e3c9056c.MP4

**Comment by tomasruffa** [comment]
> @tomasruffa Just curious, what was the resolution here? Upgrading RN?

I just updated the Xcode into the cicd machine to the latest one and fix library versions on package.json :)

**Comment by kalyantm** [comment]
@tomasruffa I'm assuming you are using Xcode 14 for your builds in CI/CD right? Also, could you please confirm what version of react-native you upgraded to (that fixed the issue)? Thanks!

**Comment by tomasruffa** [comment]
I not upgraded react-native version, I used the same one and Xcode 14 for builds

**Comment by kalyantm** [comment]
You said you fixed the library versions on package.json - which libraries did you update or fix? Sorry, just trying to understand what the change exactly was that fixed it!

**Comment by FernandoLooplan** [comment]
@tomasruffa What library did you update or what modifications did you make? I'm having the same problem
"react-native": "^0.73.0"

**Comment by maratkarelov** [comment]
remove KeyboardAvoidingView

**Comment by Jmzp** [comment]
This is the main issue -> https://github.com/facebook/react-native/issues/42939
