### ISSUE TITLE
TextInput (Web) - Same code logic but got different behavior with TextInput

### ISSUE THREAD

**Issue by tjcchen** [facebook/react-native#36856]
### Description

Hello Team,

Recently, I was building an application with ReactNative & Expo. A piece of simple logic concerning TextInput encounters an issue. It works fine on my Android device, but on the web side, the UI behavior looks different. Here are my code snippets & screenshot, and I assume this problem relates to the return value of `onChange` prop.

code:
```jsx
// ... 
const [searchTerm, setSearchTerm] = useState('');

<View style={styles.searchWrapper}>
  <TextInput
    style={styles.searchInput}
    value={searchTerm}
    onChange={(text) => {console.log(text); setSearchTerm(text);}} {/* inconsistency occurs here, the return value of onChange prop */}
    placeholder="What job are you looking for?"
  />
</View>
// ...
```

On the web side:

<img width="1310" alt="web-input-error" src="https://user-images.githubusercontent.com/6133656/230817859-152b7c06-d9c0-43fe-a1f5-9cb4fd1fc9fb.png">

Could someone help to resolve this inconsistency issue. Thanks a lot!

Regards,
Andy

### React Native Version

0.71.3

### Output of `npx react-native info`

System:
    OS: macOS 11.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 791.50 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK: Not Found
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7935034
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Java: 14.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.3 => 0.71.3
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Please refer to my description & screenshot. Thanks

### Snack, code example, screenshot, or link to a repository

https://github.com/tjcchen/react-native-demo/blob/main/components/home/welcome/Welcome.jsx

**Comment by carlosalmonte04** [comment]
Hey @tjcchen you should try using [`onChangeText`](https://reactnative.dev/docs/textinput#onchangetext) instead of `onChange`. 

[`onChange`](https://reactnative.dev/docs/textinput#onchange) callback receives the `nativeEvent` object as the argument.

**Comment by tjcchen** [comment]
@carlosalmonte04 Thanks much for your reply. Yeah, I finally fixed this issue by using `onChangeText`. 

<img width="998" alt="Screen Shot 2023-04-29 at 10 22 34 AM" src="https://user-images.githubusercontent.com/6133656/235279449-de3a9420-6bfd-4006-9b66-cc7afec1a1cd.png">

Repo link: https://github.com/tjcchen/react-native-demo/blob/main/components/home/welcome/Welcome.jsx

Previously, I saw a lot of their docs still using `onChange` for reference, but it seems they've changed them now.

Doc link: https://reactnative.dev/docs/textinput

Anyway, thanks a lot! 👍

**Comment by tjcchen** [comment]
> Hey @tjcchen you should try using [`onChangeText`](https://reactnative.dev/docs/textinput#onchangetext) instead of `onChange`.
> 
> [`onChange`](https://reactnative.dev/docs/textinput#onchange) callback receives the `nativeEvent` object as the argument, hence why you are seeing `[object Object]` as the value of the TextInput in web.
> 
> Can you please point me to the tool you used to setup your web react native project?

I'm using `Expo` to bootstrap my project as referred from the reactjs website. Hope this helps!

https://react.dev/learn/start-a-new-react-project#expo
