### ISSUE TITLE
FlatList: Invariant Violation: Tried to get frame for out of range index -1

### ISSUE THREAD

**Issue by tibbe** [facebook/react-native#36850]
### Description

I'm trying to upgrade our app from 0.70.8 to 0.71.6 and I think I've found a bug in `FlatList`. Here's the error:

Invariant Violation: Tried to get frame for out of range index -1, js engine: hermes

Here are two stack traces, both involving `scrollToEnd` and one involving `onLayout` and the other `onContentSizeChanged`. Unfortunately they are screenshots as it's nay impossible to get RN to give up the stack trace as text, especially since Flipper debugging doesn't seem to work with 0.71.

![Simulator Screenshot - iPhone 14 - 2023-04-07 at 10 31 08](https://user-images.githubusercontent.com/17277/230573702-f5f29d99-0d44-4f7d-b82c-01d954d67f47.png)
![Simulator Screenshot - iPhone 14 - 2023-04-07 at 10 31 18](https://user-images.githubusercontent.com/17277/230573707-eddf69a8-2983-48a8-8300-f1ff15585e7d.png)

### React Native Version

0.71.6

### Output of `npx react-native info`

System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 697.50 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
    Watchman: 2023.02.27.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /Users/tibbe/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.6 => 0.71.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Use a `FlatList`, `scrollToEnd`, and `onLayout`/`onContentSizeChanged`.

### Snack, code example, screenshot, or link to a repository

Too hard to slim down.

**Comment by NickGerleman** [comment]
Fixed by https://github.com/facebook/react-native/commit/98009ad94b92320307f2721ee39dbeb9152c0a58 in 0.72.
