### ISSUE TITLE
RNBridge Does Not support Swift Package Manager

### ISSUE THREAD

**Issue by nplasterer** [facebook/react-native#36863]
### Description

We are looking for some sort of work around to help with a RN native bridge that depends on a iOS SDK that uses Swift package manager. We've explored trying to make the iOS SDK into a Cocoapod but unfortunately it depends on other packages that have entirely dropped Cocoapod support and we weren't able to find any alternative cocoapod packages to substitute in. 
Is there anyway to make a react native bridge to native iOS work with a swift package manager? Appreciate any guidance you can offer for others who've faced this challenge.

### React Native Version

0.71.4

### Output of `npx react-native info`

System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 340.55 MB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.16.0/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
    Watchman: 2023.02.20.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/naomiplasterer/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 28, 29, 30, 31, 32, 33
      Build Tools: 29.0.2, 30.0.3, 31.0.0, 33.0.1
      System Images: android-31 | Google APIs ARM 64 v8a, android-33 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.4 => 0.71.4
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Create a react native bridge to iOS that depends on a SDK that is not a cocoapod like https://github.com/xmtp/xmtp-ios and cannot become a cocoapod because it depends on `swiftnio` https://forums.swift.org/t/swiftnio-is-dropping-support-for-cocoapods/56840

### Snack, code example, screenshot, or link to a repository

https://github.com/xmtp/xmtp-react-native

**Comment by nplasterer** [comment]
It is in issue in the latest version I accidentally forgot to update what the version was that we were actually on but it is 71.4.

**Comment by cortinico** [comment]
Closing as this is discussion and should be moved here:
- https://github.com/react-native-community/discussions-and-proposals/issues/587

**Comment by nplasterer** [comment]
Hey @cortinico I did add the discussion over there but was wondering if there was any work around anybody has found in the meantime? The discussion doesn't appear to offer any solutions or is it just you can't do anything and we should be encouraging people to use flutter instead?

**Comment by cortinico** [comment]
> The discussion doesn't appear to offer any solutions or is it just you can't do anything 

We're trying to keep the Issue Tracker of react-native focused on bugs and practical issues folks are having. Discussions and proposals should happen instead in the dedicated repo so we can keep the conversation focused and we don't fragment it in multiple places.

> and we should be encouraging people to use flutter instead?

How is this related?

**Comment by nplasterer** [comment]
> How is this related?

You're right it's not totally related but our Flutter SDK does work and our React Native SDK does not work. And I guess the answer I'm getting is that supporting swift in react native bridges is not a bug or a practical issue folks are having so there won't be a fix for it anytime soon. 👍
