### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by dzwangfan** [facebook/react-native#36869]
### Description

![171681203533_ pic_hd](https://user-images.githubusercontent.com/28337668/231109785-a6d99d6e-d347-41d8-a54c-a0a2caab9633.jpg)

### React Native Version

0.64.4

### Output of `npx react-native info`

<img width="848" alt="image" src="https://user-images.githubusercontent.com/28337668/231124238-cbf9645a-77d5-45a1-9721-135a22f06a53.png">

### Steps to reproduce

no

### Snack, code example, screenshot, or link to a repository

No

**Comment by dinhtrumdieu** [comment]
@dzwangfan same issues ? have you solved it yet?
