### ISSUE TITLE
Android `TextInput` has a different height compared to a `Text`

### ISSUE THREAD

**Issue by ahmafi** [facebook/react-native#36861]
### Description

As you can see in the image below, I have created a `TextInput` on the bottom (red one) and a `Text` above that (green one). They have the same font, font size, and font weight and nothing more. But the `TextInput` (in my case) is 28dp when I inspect it with devtools and the `Text` is 23dp, it's also obvious from the picture that the `TextInput` height is bigger. I have tried setting `padding`, `paddingBottom`, `paddingTop` and `paddingVertical` to 0, but it didn't help. I have even tried adding underline to the `Text`, but It didn't change its height.

![image](https://user-images.githubusercontent.com/12560109/230983078-d8a0ebb7-1772-4773-b351-45e3219ac775.png)

### React Native Version

0.71.6

### Output of `npx react-native info`

System:
    OS: Linux 6.1 Fedora Linux 37 (Workstation Edition)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 2.77 GB / 15.41 GB
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 18.14.0 - ~/.nvm/versions/node/v18.14.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.14.0/bin/yarn
    npm: 9.3.1 - ~/.nvm/versions/node/v18.14.0/bin/npm
    Watchman: 20230402.003234.0 - /usr/local/bin/watchman
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 17.0.6 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.6 => 0.71.6 
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Just add two simple `TextInput` and `Text` as explained in the description.

### Snack, code example, screenshot, or link to a repository

https://snack.expo.dev/@ahmafi/textinput-height-bug

**Comment by the-mysterious-kid** [comment]
From what I have observed `TextInput` has a default padding added to it. And to overcome that, my only solution was to give a constant height to the `TextInput`. You can see a slight difference by giving `paddingVertical: 0` or `padding: 0` to the styling of that text input

**Comment by ahmafi** [comment]
> my only solution was to give a constant height to the `TextInput`.

Then, how do you handle text overflowing boundaries when user changes default font size of the device?

> You can see a slight difference by giving `paddingVertical: 0` or `padding: 0` to the styling of that text input

As you can see in the expo snack I provided in the OP, it doesn't make any difference.

**Comment by hanarotg** [comment]
Any updates on this issue?

**Comment by the-mysterious-kid** [comment]
@ahmafi  You can try setting up dynamic height by using `Dimension`

**Comment by fabriziobertoglio1987** [comment]
Do you still experience this issue? 

I have four years of experience maintaining facebook/react-native and I specialize in the Text and TextInput components. I currently have 58 [facebook/react-native PRs](https://github.com/facebook/react-native/pulls?q=is%3Apr+author%3Afabriziobertoglio1987+). 

If you still experience this issue, I will prepare a patched release with the fix.

Thanks a lot

**Comment by the-mysterious-kid** [comment]
@fabriziobertoglio1987 I just checked this in a project with the following RN version`"react-native": "0.72.3"`. And I still saw a default padding in the Android devices. On giving `padding: 0` there is a small change, but still, there is a difference in Android and iOS.

**Comment by hanarotg** [comment]
The fundamental problem is that the react-native regulates textinput border through the padding of the parent component. 

The simplest solution is to have an additional parent view component.

**Comment by SamakaCD** [comment]
Setting `@null` for as a default  `EditText` (a.k.a. `TextInput`) background fixes the issue:

```
<resources>

    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        ...
        <item name="android:editTextStyle">@style/CustomEditText</item>
    </style>

    ...

    <style name="CustomEditText" parent="Widget.AppCompat.EditText">
        <item name="android:background">@null</item>
    </style>
</resources>
```

**Comment by SamakaCD** [comment]
Setting `@null` for as a default `EditText` (a.k.a. `TextInput`) background fixes the issue.

In `android/app/src/main/res/values/styles.xml`:
```
<resources>

    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        ...
        <item name="android:editTextStyle">@style/CustomEditText</item>
    </style>

    ...

    <style name="CustomEditText" parent="Widget.AppCompat.EditText">
        <item name="android:background">@null</item>
    </style>
</resources>
```

**Comment by SamakaCD** [comment]
Setting `@null` as a default `EditText` (a.k.a. `TextInput`) background fixes the issue.

In `android/app/src/main/res/values/styles.xml`:

```
<resources>

    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        ...
        <item name="android:editTextStyle">@style/CustomEditText</item>
    </style>

    ...

    <style name="CustomEditText" parent="Widget.AppCompat.EditText">
        <item name="android:background">@null</item>
    </style>
</resources>
```

**Comment by devtm1123** [comment]
Settings padding 0 fixed the issue for me.
