### ISSUE TITLE
TextInput make app freeze while typing when I add multiline prop

### ISSUE THREAD

**Issue by ahmedfouad01099** [facebook/react-native#36872]
### Description

TextInput make app freeze while typing when I add multiline prop

### React Native Version

0.69.8

### Output of `npx react-native info`

System:
    OS: macOS 12.6
    CPU: (8) x64 Apple M1 Pro
    Memory: 32.82 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.1.4 - /opt/homebrew/bin/npm
    Watchman: 2021.12.13.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9514443
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.5 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.8 => 0.69.8 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

create an application with react native v0.69.8 and create a TextInput and add a multiline prop to it and start typing the whole app will freeze

### Snack, code example, screenshot, or link to a repository

https://user-images.githubusercontent.com/63275575/231156443-1ce3ecb1-a35c-447e-ab8f-2ab4ca0c0cfc.mp4

**Comment by kalyantm** [comment]
No, it's happening on iOS!

**Comment by RalissonMattias** [comment]
I can reproduce in ios simulator and physical devices too

**Comment by kalyantm** [comment]
Yup, I can reproduce this too on the iOS simulator when I build in release mode (iOS 16.4.1 and RN 0.71.6)

**Comment by hichemfantar** [comment]
Please try the latest patch release and confirm if the problem still exists.

**Comment by kalyantm** [comment]
Yup, it still happens on 0.71.7

**Comment by Hady207** [comment]
Still happening after the upgrade.

**Comment by hichemfantar** [comment]
@kalyantm @Hady207  Please test this in a fresh React Native project to make sure It's not caused by any external dependencies then report back.

**Comment by kalyantm** [comment]
@hichemfantar I tried it in a fresh project on release mode and it works as expected, no lag. could you confirm this behaviour too, @Hady207 ?

**Comment by Sumit2202** [comment]
If any of you folks are using UXCam then that is the culprit here, downgrade UXCam to 5.3.4 and it should work now, https://github.com/uxcam/react-native-ux-cam/issues/86

**Comment by alecdewitz** [comment]
Version 5.4.6 seems to fix the issue for me

**Comment by CMLCNL** [comment]
any update for this issue

**Comment by hichemfantar** [comment]
> any update for this issue

this was fixed a long time ago
