### ISSUE TITLE
Error Building the app in release mode "main.jsbundle does not exist"

### ISSUE THREAD

**Issue by MohammedWaheeb** [facebook/react-native#36886]
### Description

We are building a react native application and we are facing this issue sometimes, without any changes building can work or fail 

`▸ Running script 'Bundle React Native code and images'
    the transform cache was reset.

❌  error: File /Users/runner/Library/Developer/Xcode/DerivedData/**********-eulgfyrcmjmgohfphedrvfvwygma/Build/Products/Release-iphoneos/*************.app/main.jsbundle does not exist. This must be a bug with React Native, please report it here: https://github.com/facebook/react-native/issues

▸ Generating '**********.app.dSYM'
** BUILD FAILED **

The following build commands failed:
	PhaseScriptExecution Bundle\ React\ Native\ code\ and\ images /Users/runner/Library/Developer/Xcode/DerivedData/**************-eulgfyrcmjmgohfphedrvfvwygma/Build/Intermediates.noindex/**********.build/Release-iphoneos/**************.build/Script-00DD1BFF1BD5951E806B06BC.sh 
(1 failure)
##[error]Error: /usr/bin/xcodebuild failed with return code: 65`

th

### React Native Version

0.71.6

### Output of `npx react-native info`

System:
    OS: macOS 12.6.4
    CPU: (3) x64 Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz
    Memory: 5.16 GB / 14.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.16.0 - ~/hostedtoolcache/node/16.16.0/x64/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.11.0 - ~/hostedtoolcache/node/16.16.0/x64/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.12.0 - /usr/local/lib/ruby/gems/3.0.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 27, 28, 29, 30, 31, 32, 33, 33, 33
      Build Tools: 27.0.0, 27.0.1, 27.0.2, 27.0.3, 28.0.0, 28.0.1, 28.0.2, 28.0.3, 29.0.0, 29.0.1, 29.0.2, 29.0.3, 30.0.0, 30.0.1, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 33.0.0, 33.0.1, 33.0.2
      Android NDK: 25.2.9519653
  IDEs:
    Android Studio: Not Found
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_362 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.6 => 0.71.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Build the app, in an azure pipeline enviroemnt, and its not stable on my local machine, I get 

### Snack, code example, screenshot, or link to a repository

npx react-native run-ios --configuration Release

**Comment by blakef** [comment]
I can't reproduce it using these steps:
```
npx react-native@latest init RN0716 --version 0.71.6
cd RN0716/ios
bundle install && bundle exec pod install
npx react-native run-ios --configuration Release
```
![CleanShot 2023-04-13 at 11 51 34](https://user-images.githubusercontent.com/49578/231737042-9f11e86a-f0cb-42bb-ae29-b51d8f644206.png)

**Comment by segebee** [comment]
I had this same issue

Realized it was because I changed the `index.js` file to `index.tsx`

Discovered this error by adding the below to package.json

``"build:ios": "react-native bundle --entry-file='index.js' --bundle-output='./ios/main.jsbundle' --dev=false --platform='ios'"``

and running `yarn build:ios` or `npm run build:ios`

**Comment by viettranbhtech** [comment]
I had to update `export NODE_BINARY=/usr/local/bin/node ` in ios/.xcode.env and it worked. 
My project had same issue after upgrading to new RN 0.71.7

**Comment by sportakal** [comment]
> I had to update `export NODE_BINARY=/usr/local/bin/node ` in ios/.xcode.env and it worked. My project had same issue after upgrading to new RN 0.71.7

Thanks for resolution. It works for me with a minor difference.

My node binary was `/opt/homebrew/bin/node`. I found it run `command -v node`in terminal.

Hope helps to other.

**Comment by usedlife** [comment]
I solved it with this:
https://github.com/facebook/react-native/issues/34768#issuecomment-1256895362

background with me:
I use nvm to manage the node version, and the system default node version is very low (<12).

When packaging `mainbundle.js`, `/bin/sh` uses the default node version, resulting in a syntax error exception.
<img width="584" alt="image" src="https://github.com/facebook/react-native/assets/40729282/a0094cae-60ee-430d-9bf2-afc6005cc46c">

**The key to the solution is to use the correct node version when packaging.**

**Comment by usedlife** [comment]
> I solved it with this: [#34768 (comment)](https://github.com/facebook/react-native/issues/34768#issuecomment-1256895362)
> 
> background with me: I use nvm to manage the node version, and the system default node version is very low (<12).
> 
> When packaging `mainbundle.js`, `/bin/sh` uses the default node version, resulting in a syntax error exception. <img alt="image" width="584" src="https://user-images.githubusercontent.com/40729282/251323481-a0094cae-60ee-430d-9bf2-afc6005cc46c.png">
> 
> **The key to the solution is to use the correct node version when packaging.**

And the official documentation has given the hint:

https://reactnative.dev/docs/environment-setup?guide=native#optional-configuring-your-environment

<img width="865" alt="image" src="https://github.com/facebook/react-native/assets/40729282/4f00330f-9d25-433e-9cfd-796739cfb73d">

**Comment by ajayhcode** [comment]
Hi same issue after updating react-native to 0.72.4 from 0.70.5.
Able to fix it by build:ios command but I need to run the build:ios command every time before creating ios archive.
Which was not default behavior.
Please let know if there is any other fix for this.

**Comment by amorimcode** [comment]
I need to run 
react-native bundle --entry-file='index.js' --bundle-output='./ios/main.jsbundle' --dev=false --platform='ios'

everytime im creating archive, please some tips?

**Comment by segebee** [comment]
It solved our issue... but I do not know if we still do that for every build

> I need to run react-native bundle --entry-file='index.js' --bundle-output='./ios/main.jsbundle' --dev=false --platform='ios'
> 
> everytime im creating archive, please some tips?

**Comment by usedlife** [comment]
> I need to run react-native bundle --entry-file='index.js' --bundle-output='./ios/main.jsbundle' --dev=false --platform='ios'
> 
> everytime im creating archive, please some tips?

react-native repo will automatically bundle when create iOS archive

**Comment by ItaloVCosta** [comment]
After I forced Xcode to use the same Node.js version as my project, this issue stopped happening. To force the Node.js version, I simply set the default version to the correct one using the command:

`nvm alias default 12.22.12`

**Comment by segebee** [comment]
> After I forced Xcode to use the same Node.js version as my project, this issue stopped happening. To force the Node.js version, I simply set the default version to the correct one using the command:
> 
> `nvm alias default 12.22.12`

thanks for sharing

**Comment by edcity-charlie** [comment]
> export PATH=/opt/homebrew/bin:$PATH export NODE_BINARY=node ../node_modules/react-native/scripts/react-native-xcode.sh
> 
> Add the following lines in build phases under "Bundle React Native Code and Images" Hope it will remove the error :)

Thanks for sharing, it works in my trial. 
My project is an expo project and native build with XCode.
My XCode version is Version 15.2 (15C500b)
My expo version is 49

**Comment by roancoetzee** [comment]
Posting my experiece since it might help someone else. 
react-native: 0.70.15
xcode: 15.1

I had a look at the script responsible for building the `main.jsbundle` at `node_modules/react-native/scripts/react-native-xcode.sh`.
The script was failling on this line `"$HERMES_CLI_PATH" -emit-binary $EXTRA_COMPILER_ARGS -out "$DEST/main.jsbundle" "$BUNDLE_FILE"`.

To get to this line `USE_HERMES` would need to be anything but `false`. Since we haven't swapped over to hermes yet and we explicitly set `hermes_enabled => false` in our PODS file, I expected that `USE_HERMES` would be false. However when I `echo`ed `USE_HERMES`, it resulted in being empty. This meant that the check `if [[ $USE_HERMES == false ]]` would fail and the code for a hermes enabled environment would be run, which is not what we want. 

I haven't figure out why `USE_HERMES` is not being set but as temp work around I am setting it manually in `Bundle React Native code and images` like below. 

![Screenshot 2024-02-26 at 10 48 01](https://github.com/facebook/react-native/assets/2031707/0a20a1eb-15ed-4fed-bc6c-0acca26dff1c)

If anyone knows why `USE_HERMES` is not getting set let me know.

**Comment by tux2nicolae** [comment]
@roancoetzee you won't believe it, but you already helped someone (10h from your comment).

Thank you, for pointing it out! Just noticed the same thing even on the lates react native version (0.73.5).

**Comment by VitDev17** [comment]
@roancoetzee  You are super on point here! Can you explain to us how you came to this solution? What was the debugging process?
Thank you a lot my man!

**Comment by e3bmo3ty** [comment]
> Posting my experiece since it might help someone else. react-native: 0.70.15 xcode: 15.1
> 
> I had a look at the script responsible for building the `main.jsbundle` at `node_modules/react-native/scripts/react-native-xcode.sh`. The script was failling on this line `"$HERMES_CLI_PATH" -emit-binary $EXTRA_COMPILER_ARGS -out "$DEST/main.jsbundle" "$BUNDLE_FILE"`.
> 
> To get to this line `USE_HERMES` would need to be anything but `false`. Since we haven't swapped over to hermes yet and we explicitly set `hermes_enabled => false` in our PODS file, I expected that `USE_HERMES` would be false. However when I `echo`ed `USE_HERMES`, it resulted in being empty. This meant that the check `if [[ $USE_HERMES == false ]]` would fail and the code for a hermes enabled environment would be run, which is not what we want.
> 
> I haven't figure out why `USE_HERMES` is not being set but as temp workaround I am setting it manually in `Bundle React Native code and images` like below.
> 
> ![Screenshot 2024-02-26 at 10 48 01](https://private-user-images.githubusercontent.com/2031707/307757789-0a20a1eb-15ed-4fed-bc6c-0acca26dff1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzNzcxMTksIm5iZiI6MTcxMDM3NjgxOSwicGF0aCI6Ii8yMDMxNzA3LzMwNzc1Nzc4OS0wYTIwYTFlYi0xNWVkLTRmZWQtYmM2Yy0wYWNjYTI2ZGZmMWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTRUMDA0MDE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTEwYjk4ZThjZDc1MWRhNTg4YTc0MWFlY2Q1NDI2MzU4NjEzNDdlNTM2MWQ1YTAyNzNiOTM4YTJkYTFkMjliOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.B7YOAGkADTpZMz5pn3s0jS8sxxw_AJyP_f9vtXJL6Dc)
> 
> If anyone knows why `USE_HERMES` is not getting set let me know.

thanks, after hours of debugging this is the only solution works for me

**Comment by duirron** [comment]
> I solved it with this: [#34768 (comment)](https://github.com/facebook/react-native/issues/34768#issuecomment-1256895362)
> 
> background with me: I use nvm to manage the node version, and the system default node version is very low (<12).
> 
> When packaging `mainbundle.js`, `/bin/sh` uses the default node version, resulting in a syntax error exception. <img alt="image" width="584" src="https://private-user-images.githubusercontent.com/40729282/251323481-a0094cae-60ee-430d-9bf2-afc6005cc46c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3NjE4ODQsIm5iZiI6MTcxNDc2MTU4NCwicGF0aCI6Ii80MDcyOTI4Mi8yNTEzMjM0ODEtYTAwOTRjYWUtNjBlZS00MzBkLTliZjItYWZjNjAwNWNjNDZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAzVDE4Mzk0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwNjE3NzQwNjJmY2MyMzAwNTI3M2I1NmVkOWQ0ZjY0MmE3NDRmMTkwMTBhM2IyZDVkMWE3ZWY0NTRjMmQzODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KI6X8U5j60qOdbvcOqKNldktjj-FvpUQ9ToBfn3Piis">
> 
> **The key to the solution is to use the correct node version when packaging.**

this help-me with error "Make sure you're running a packager server or have included a .jsbundle file in your application bundle." Thank you man.

**Comment by React-RN-Pratik** [comment]
> export PATH=/opt/homebrew/bin:$PATH export NODE_BINARY=node ../node_modules/react-native/scripts/react-native-xcode.sh
> 
> Add the following lines in build phases under "Bundle React Native Code and Images" Hope it will remove the error :)

I appreciate your response, as it is very useful for my React-Native version 0.63.4.

**Comment by minikdev** [comment]
> > I had to update `export NODE_BINARY=/usr/local/bin/node ` in ios/.xcode.env and it worked. My project had same issue after upgrading to new RN 0.71.7
> 
> Thanks for resolution. It works for me with a minor difference.
> 
> My node binary was `/opt/homebrew/bin/node`. I found it run `command -v node`in terminal.
> 
> Hope helps to other.

This worked for my case, thanks. `"react-native": "0.72.4"`

**Comment by anwargul0x** [comment]
what worked for me

- `cd ios`
- `nano .xcode.env`
- paste `export NODE_BINARY=$(command -v node)`

![Screenshot 2024-07-01 at 7 32 52 PM](https://github.com/facebook/react-native/assets/26444582/71730725-a0e7-44e8-b852-a1074920a2c6)

**Comment by Wesleyomnion** [comment]
> export PATH=/opt/homebrew/bin:$PATH
export NODE_BINARY=node
../node_modules/react-native/scripts/react-native-xcode.sh

@PLKHawaR , 
Thanks man, I was going crazy. It worked for me

**Comment by redbluenat** [comment]
I have version react-native 0.73.6, and this is what worked for me: 
1. Open Bundle React Native code and images in Targets -> Build Phases
2. Add following lines:

```
set -e

WITH_ENVIRONMENT="../node_modules/react-native/scripts/xcode/with-environment.sh"
REACT_NATIVE_XCODE="../node_modules/react-native/scripts/react-native-xcode.sh"

/bin/sh -c "$WITH_ENVIRONMENT $REACT_NATIVE_XCODE"
```

**Comment by nguyentrancong** [comment]
It was working with me
Maby should try it.

open ios folder > .xcode.env file > change the same

`# export NODE_BINARY=$(command -v node)
export PATH=/opt/homebrew/bin:$PATH
export NODE_BINARY=node
../node_modules/react-native/scripts/react-native-xcode.sh`
<img width="816" alt="image" src="https://github.com/user-attachments/assets/85d07978-6c08-4212-aee6-f86049a7d2a2">

**Comment by mharrison-nzme** [comment]
> Posting my experiece since it might help someone else. react-native: 0.70.15 xcode: 15.1
> 
> I had a look at the script responsible for building the `main.jsbundle` at `node_modules/react-native/scripts/react-native-xcode.sh`. The script was failling on this line `"$HERMES_CLI_PATH" -emit-binary $EXTRA_COMPILER_ARGS -out "$DEST/main.jsbundle" "$BUNDLE_FILE"`.
> 
> To get to this line `USE_HERMES` would need to be anything but `false`. Since we haven't swapped over to hermes yet and we explicitly set `hermes_enabled => false` in our PODS file, I expected that `USE_HERMES` would be false. However when I `echo`ed `USE_HERMES`, it resulted in being empty. This meant that the check `if [[ $USE_HERMES == false ]]` would fail and the code for a hermes enabled environment would be run, which is not what we want.
> 
> I haven't figure out why `USE_HERMES` is not being set but as temp workaround I am setting it manually in `Bundle React Native code and images` like below.
> 
> ![Screenshot 2024-02-26 at 10 48 01](https://private-user-images.githubusercontent.com/2031707/307757789-0a20a1eb-15ed-4fed-bc6c-0acca26dff1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2MjI5OTAsIm5iZiI6MTcyODYyMjY5MCwicGF0aCI6Ii8yMDMxNzA3LzMwNzc1Nzc4OS0wYTIwYTFlYi0xNWVkLTRmZWQtYmM2Yy0wYWNjYTI2ZGZmMWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTFUMDQ1ODEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2JkM2ZiNTgzYjBlMTU5ZTk1MmQ2ZjA2ZGQ3ZWZmNTE4NjY3MjU1YmI0ZjIwYTM3MDJmMzY4NzY0YzA1NTVlOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.vglWURC3VC_vfWLOkBcQtPMLzGHDGtFikWNy8D8Oux0)
> 
> If anyone knows why `USE_HERMES` is not getting set let me know.

As someone upgrading from RN0.69 to RN0.70, this saved me - thank you

**Comment by ssthil** [comment]
@PLKHawaR 

Thanks for sharing the solution, it worked!

`export PATH=/opt/homebrew/bin:$PATH
export NODE_BINARY=node
../node_modules/react-native/scripts/react-native-xcode.sh`

**Comment by Solaimanx** [comment]
adding `export NODE_BINARY=/Users/mohammadsolaiman/.nvm/versions/node/v20.16.0/bin/node ` in ./ios/.xcode.env solved my issue . 😌😌😌
