### ISSUE TITLE
React Native crash after installing any pods

### ISSUE THREAD

**Issue by elmcapp** [facebook/react-native#36911]
### Description

If I create and build a new project everything works However
Any time that I install any package that has pods after I do ```pod install``` then run the project ```yarn ios``` it will fail. 

dyld[1691]: Library not loaded: @rpath/hermes.framework/hermes
  Referenced from: <1CE10342-16E5-356A-AA19-8744974DC9F7> /private/var/containers/Bundle/Application/CC7B7B6F-C200-4D43-ABA7-F316257C8277/demo.app/demo
  Reason: tried: '/usr/lib/swift/hermes.framework/hermes' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/hermes.framework/hermes' (errno=2), '/usr/lib/swift/hermes.framework/hermes' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/hermes.framework/hermes' (errno=2), '/private/var/containers/Bundle/Application/CC7B7B6F-C200-4D43-ABA7-F316257C8277/demo.app/Frameworks/hermes.framework/hermes' (errno=2), '/private/var/containers/Bundle/Application/CC7B7B6F-C200-4D43-ABA7-F316257C8277/demo.app/Frameworks/hermes.framework/hermes' (errno=2), '/private/var/containers/Bundle/Application/CC7B7B6F-C200-4D43-ABA7-F316257C8277/demo.app/Frameworks/hermes.framework/hermes' (errno=2), '/usr/lib/swift/hermes.framework/hermes' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/hermes.framework/hermes' (errno=2), '/usr/lib/swift/hermes.framework/hermes' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/hermes.framework/hermes' (errno=2), '/private/var/containers/Bundle/Application/CC7B7B6F-C200-4D43-ABA7-F316257C8277/demo.app/Frameworks/hermes.framework/hermes' (errno=2), '/private/var/containers/Bundle/Application/CC7B7B6F-C200-4D43-ABA7-F316257C8277/demo.app/Frameworks/hermes.framework/hermes' (errno=2), '/private/var/containers/Bundle/Application/CC7B7B6F-C200-4D43-ABA7-F316257C8277/demo.app/Frameworks/hermes.framework/hermes' (errno=2), '/private/preboot/Cryptexes/OS@rpath/hermes.framework/hermes' (errno=2), '/usr/lib/swift/hermes.framework/hermes' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/hermes.framework/hermes' (errno=2), '/usr/lib/swift/hermes.framework/hermes' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/hermes.framework/hermes' (errno=2), '/private/var/containers/Bundle/Application/CC7B7B6F-C200-4D43-ABA7-F316257C8277/demo.app/Frameworks/hermes.framework/hermes' (errno=2), '/private/var/containers/Bundle/Application/CC7B7B6F-C200-4D43-ABA7-F316257C8277/demo.app/Frameworks/hermes.framework/hermes' (errno=2), '/private/var/containers/Bundle/Application/CC7B7B6F-C200-4D43-ABA7-F316257C8277/demo.app/Frameworks/hermes.framework/hermes' (errno=2), '/usr/lib/swift/hermes.framework/hermes' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/hermes.framework/hermes' (errno=2), '/usr/lib/swift/hermes.framework/hermes' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/hermes.framework/hermes' (errno=2), '/private/var/containers/Bundle/Application/CC7B7B6F-C200-4D43-ABA7-F316257C8277/demo.app/Frameworks/hermes.framework/hermes' (errno=2), '/private/var/containers/Bundle/Application/CC7B7B6F-C200-4D43-ABA7-F316257C8277/demo.app/Frameworks/hermes.framework/hermes' (errno=2), '/private/var/containers/Bundle/Application/CC7B7B6F-C200-4D43-ABA7-F316257C8277/demo.app/Frameworks/hermes.framework/hermes' (errno=2), '/System/Library/Frameworks/hermes.framework/hermes' (errno=2, not in dyld cache)
Library not loaded: @rpath/hermes.framework/hermes
  Referenced from: <1CE10342-16E5-356A-AA19-8744974DC9F7> /private/var/containers/Bundle/Application/CC7B7B6F-C200-4D43-ABA7-F316257C8277/demo.app/demo
  Reason: tried: '/usr/lib/swift/hermes.framework/hermes' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/hermes.framework/hermes' (errno=2), '/usr/lib/swift/hermes.framework/hermes' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/hermes.framework/hermes' (errno=2), '/private/var/containers/Bundle/Application/CC7B7B6F-C200-4D43-ABA7-F316257C8277/demo.app/Frameworks/hermes.framework/hermes' (errno=2), '/private/var/containers/Bundle/Application/CC7B7B6F-C200-4D43-ABA7-F316257C8277/demo.app/Frameworks/hermes.framework/hermes' (errno=2), '/private/var/containers/Bundle/Application/CC7B7B6F-C200-4D43-ABA7-F316257C8277/demo.app/Frameworks/hermes.framework/hermes' (errno=2), '/usr/lib/swift/hermes.framework/hermes' (errno=2, not in dyld cache), '/private/preboot
dyld config: DYLD_LIBRARY_PATH=/usr/lib/system/introspection DYLD_INSERT_LIBRARIES=/usr/lib/libBacktraceRecording.dylib:/usr/lib/libMainThreadChecker.dylib:/usr/lib/libRPAC.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib

### React Native Version

0.71.6

### Output of `npx react-native info`

System:
    OS: macOS 13.3
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 761.41 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.15.0 - /usr/local/bin/node
    Yarn: 1.22.17 - ~/.yarn/bin/yarn
    npm: 9.5.0 - /usr/local/bin/npm
    Watchman: 2022.02.07.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 23, 28, 29, 30, 31, 33
      Build Tools: 30.0.2, 30.0.3, 31.0.0, 33.0.0
      System Images: android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom_64, android-31 | Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9619390
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.6 => 0.71.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. npx react-native@latest init demo
2. yarn ios

The project will run on device or simulator 

3. yarn add <any package that has pods>
4. cd ios && pod install && ..//
5. yarn ios

Then everything fails with error show above

### Snack, code example, screenshot, or link to a repository

```There is no example code to show```

**Comment by govindat415** [comment]
I also just initialized a new react native project and I am getting the same error. I tried running it without doing pod install and also after doing pod install. I saw several threads about updating ruby and cocoa pods to match the versions in the Gemfile. I checked my dependencies and yours and they seem to be good (ruby >= 2.6.10 and cocoa pods >= 1.11.3). I am also searching for a solution.

**Comment by blakef** [comment]
Just to confirm:
1. created your project
2. `yarn add <foo-native-module>`
3. [_exactly_ followed the steps here](https://developer.android.com/training/articles/security-config#CleartextTrafficPermitted): `(cd ios && bundle install && bundle exec pod install)` (note the prefixed `bundle`)
4. `yarn run ios`
