### ISSUE TITLE
A function declaration without a prototype is deprecated in all versions of C for RCT_EXTERN_MODULE

### ISSUE THREAD

**Issue by unamed000** [facebook/react-native#36918]
### Description

After updating to xcode 14.3 with RN 0.69.9, my project can't build anymore. It's throwing the error for all of my custom view managers.

The error i'm getting is: A function declaration without a prototype is deprecated in all versions of C

![image](https://user-images.githubusercontent.com/10647722/232283904-a91332e5-9dfe-480f-a351-030ad77ef4b1.png)

### React Native Version

0.69.9

### Output of `npx react-native info`

System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 179.11 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.11.0 - /opt/homebrew/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - /opt/homebrew/bin/npm
    Watchman: 2023.01.02.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK:
      API Levels: 29, 30, 31, 32, 33
      Build Tools: 29.0.3, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0
      System Images: android-25 | Google Play Intel x86 Atom, android-32 | Google APIs ARM 64 v8a, android-32 | Google Play ARM 64 v8a, android-33 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_362 - /Users/huyvu/.sdkman/candidates/java/current/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: ^0.69.9 => 0.69.9 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

- Use xcode 14.3 with RN 0.69.9 and try to create a RCN_EXTERN_MODULE (ViewManager)

### Snack, code example, screenshot, or link to a repository

N/A

**Comment by glorynguyen** [comment]
I also faced the same issue like this
https://developer.apple.com/forums/thread/725753

I have to modify the error library manually

**Comment by unamed000** [comment]
> I also faced the same issue like this https://developer.apple.com/forums/thread/725753
> 
> I have to modify the error library manually


@glorynguyen glory, how did you fix the error manually? From the link you sent, it's not like the code i'm working. This is my code for creating custom module. Not from any packages

**Comment by GyroJoe** [comment]
It seems like this problem ultimately comes from `RCT_EXPORT_MODULE_NO_LOAD`'s `RCT_CONCAT` definition:
```
  __attribute__((constructor)) static void RCT_CONCAT(initialize_, objc_name)() \
  {                                                                             \
    RCTRegisterModule([objc_name class]);                                       \
  }
```

This needs to be:
```
  __attribute__((constructor)) static void RCT_CONCAT(initialize_, objc_name)(void) \
```

**Comment by ClayGriifith** [comment]
If you come across this and see GyroJoe's response about correcting the empty parenthesis in RCT_EXPORT_MODULE_NO_LOAD, the code to edit is found at node_modules>react-native>React>Base>RCTBridgeModule.h
