### ISSUE TITLE
Activity Class {[package name]/[package name].MainActivity} Does Not Exist

### ISSUE THREAD

**Issue by db-flutterwave** [facebook/react-native#36926]
### Description

I initialised a fresh React Native app on my Intel mac and tried running the `react-native run-android` command and the app builds but fails to start on my emulator with the following error.

```text
Starting: Intent { cmp=com.testproject/.MainActivity }
Error type 3
Error: Activity class {com.testproject/com.testproject.MainActivity} does not exist.
```

- The emulator runs Android 12.
- I also tried on my physical android devices running android twelve.
- I was able to run a fresh React Native project running version 0.70.8 successfully and it worked fine.
Please how can I resolve this issue as I want to upgrade our app running 0.64.4 and would like to upgrade to 0.71.6 but this error currently serves as a hinderance.

Note: My issue is not how to upgrade but rather how to resolve the launch bug for development so I can run my app in development.

### React Native Version

0.71.6

### Output of `npx react-native info`

System:
    OS: macOS 13.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 125.73 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.9.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.6.3 - /usr/local/bin/npm
    Watchman: 2023.04.10.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9619390
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.18 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.6 => 0.71.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

- Start a fresh react native project on a Macbook (maybe running intel as mine is running on intel).
- Try running `react-native run-android` on the newly initialised project.

### Snack, code example, screenshot, or link to a repository

https://github.com/db-flutterwave/react-native-0.71.6-test

**Comment by singh-sukhmanjit** [comment]
Am also facing a similar issue on Android 13 emulator and physical device. Project has been upgraded from RN 0.69.6 to 0.71.6. It works fine on Android 11.

CommandError: Couldn't open Android app with activity "com.caavo.careadmin/.MainActivity" on device "Pixel_5_API_33".
The app might not be installed, try installing it with: npx expo run:android -d Pixel_5_API_33
Activity class {com.caavo.careadmin/com.caavo.careadmin.MainActivity} does not exist.

**Output of npx react-native info**
System:
    OS: Linux 5.15 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
    Memory: 5.41 GB / 15.39 GB
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.20.0 - ~/.nvm/versions/node/v16.20.0/bin/node
    Yarn: Not Found
    npm: 8.19.4 - ~/.nvm/versions/node/v16.20.0/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK:
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
  Languages:
    Java: 15.0.2 - /opt/jdk-15.0.2/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.6 => 0.71.6 
  npmGlobalPackages:
    *react-native*: Not Found

**Logs**
04-20 10:34:14.458   602   630 I ActivityManager: Force stopping com.caavo.careadmin appid=10159 user=-1: installPackageLI
04-20 10:34:14.476   602   653 I PackageManager: Update package com.caavo.careadmin code path from /data/app/~~2xJZTin_5_SWI5OWmXxgcg==/com.caavo.careadmin-BTnDsbcAJ5f5t6WZS7IFPw== to /data/app/~~Z7NKlsWnovZ9eXk440R1cQ==/com.caavo.careadmin-2l9R4XnBFtVNIH--v3C_bA==; Retain data and using new
04-20 10:34:14.698   602   653 I ActivityManager: Force stopping com.caavo.careadmin appid=10159 user=0: pkg removed
04-20 10:34:14.756  1522  1522 I MediaProvider: Invalidating LocalCallingIdentity cache for package com.caavo.careadmin. Reason: package android.intent.action.PACKAGE_REMOVED
04-20 10:34:14.874   839   839 D MediaPlayerList: Name of package changed: com.caavo.careadmin
04-20 10:34:14.906  1522  1522 I MediaProvider: Invalidating LocalCallingIdentity cache for package com.caavo.careadmin. Reason: package android.intent.action.PACKAGE_ADDED
04-20 10:34:14.908   839   839 D MediaPlayerList: Name of package changed: com.caavo.careadmin
04-20 10:34:15.091   938   938 D CarrierSvcBindHelper: onPackageUpdateFinished: com.caavo.careadmin
04-20 10:34:15.094   938   938 D CarrierSvcBindHelper: onPackageModified: com.caavo.careadmin
04-20 10:34:15.181   602   602 I Telecom : CarModeTracker: Package com.caavo.careadmin is not tracked.: SSH.oR@AM0
04-20 10:34:15.226   938   938 D ImsResolver: maybeAddedImsService, packageName: com.caavo.careadmin
04-20 10:34:15.439   602  1940 W PackageManager: Intent does not match component's intent filter: Intent { act=android.intent.action.RUN flg=0x30000000 cmp=com.caavo.careadmin/.MainActivity }
04-20 10:34:15.439   602  1940 W PackageManager: Access blocked: ComponentInfo{com.caavo.careadmin/com.caavo.careadmin.MainActivity}
04-20 10:34:15.439   602  1940 I ActivityTaskManager: START u0 {act=android.intent.action.RUN flg=0x30000000 cmp=com.caavo.careadmin/.MainActivity} from uid 2000
04-20 10:34:15.450  1499  4822 W SQLiteLog: (28) double-quoted string literal: "com.caavo.careadmin"
04-20 10:34:15.461   602   650 E VerityUtils: Failed to measure fs-verity, errno 1: /data/app/~~Z7NKlsWnovZ9eXk440R1cQ==/com.caavo.careadmin-2l9R4XnBFtVNIH--v3C_bA==/base.apk
04-20 10:34:15.504   602   602 W AlarmManager: Package com.caavo.careadmin, uid 10159 lost permission to set exact alarms!
04-20 10:34:16.247   602   650 E VerityUtils: Failed to measure fs-verity, errno 1: /data/app/~~Z7NKlsWnovZ9eXk440R1cQ==/com.caavo.careadmin-2l9R4XnBFtVNIH--v3C_bA==/base.apk

**Comment by Tavernari** [comment]
I am having the same issue here.

info Fetching system and libraries information...

System:
    OS: macOS 13.2
    CPU: (8) arm64 Apple M1
    Memory: 124.30 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.9.0 - /opt/homebrew/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 9.6.4 - /opt/homebrew/bin/npm
    Watchman: 2023.04.10.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK:
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9477386
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.19 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.6 => 0.71.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by singh-sukhmanjit** [comment]
@Tavernari I was facing the same issue, https://github.com/facebook/react-native/issues/36995 fixed it for me.
