### ISSUE TITLE
run error with _RCTInjectedAssertFunction

### ISSUE THREAD

**Issue by passol1988** [facebook/react-native#3692]
is it a version problem? I use react-native 0.11.3
> Undefined symbols for architecture x86_64:
>   "_RCTInjectedAssertFunction", referenced from:
>       -[RCTWebSocketExecutor executeJSCall:method:arguments:callback:] in libRCTWebSocketDebugger.a(RCTWebSocketExecutor.o)
 >      -[RCTWebSocketExecutor dealloc] in libRCTWebSocketDebugger.a(RCTWebSocketExecutor.o)
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by ide** [comment]
This has been fixed in newer version of RN (0.13 for certain).

**Comment by telesoho** [comment]
I got same error on react-native 0.41.2, I build by Xcode Version 8.2.1 (8C1002)
