### ISSUE TITLE
using `selection` on `<TextInput />` causes cursor to jump around

### ISSUE THREAD

**Issue by normanzb** [facebook/react-native#36938]
### Description

When `selection` is controlled and stored inside a state, typing quickly can cause the cursor in `<TextInput />` to jump around.

My speculation is the typing and char processing is running on native side, and when the a char arrives if the react rendering  didn't catch up and update the `selection` to latest value, it causes the char to be inserted into "old" cursor location held in the state.

This is a very basic usage of the `selection` property, if due to technical difficulty this can't be fixed, I suggest to deprecate the property, and in the document ask the user to use `.setNativeProps` instead to set the `selection`. having a partially working `selection` property in the official doc can cause new users to spend hours to figure out what is going on with their code.

### React Native Version

0.70.7

### Output of `npx react-native info`

System:
    OS: macOS 12.6.5
    CPU: (10) arm64 Apple M1 Max
    Memory: 361.81 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 8.19.2 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /Users/xxx/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.13 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.7 => 0.70.7 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. open snack: https://snack.expo.dev/@normanzb/jump-cursor
2. Select iOS to test
3. In the input box, quickly type "123", keep repeating 

expect result:
everytime when finish typing "123", we expect to see 123 in the text input, the cursor should be at the end.

actual result:
if you type quick enough you will see "312", with cursor at position 1 (between letter "3" and "1")

### Snack, code example, screenshot, or link to a repository

https://snack.expo.dev/@normanzb/jump-cursor

**Comment by fabriziobertoglio1987** [comment]
Do you still experience this issue? 

I have four years of experience maintaining facebook/react-native and I specialize in the Text and TextInput components. I currently have 58 [facebook/react-native PRs](https://github.com/facebook/react-native/pulls?q=is%3Apr+author%3Afabriziobertoglio1987+). 

If you still experience this issue, I will prepare a patched release with the fix.

Thanks a lot

**Comment by normanzb** [comment]
thanks @fabriziobertoglio1987 , i just tested the snack with exp48 (with react native 0.71.x) the issue still exist:

https://snack.expo.dev/@normanzb/jump-cursor

just type quickly in the input box with random key strokes, at some point you will see the cursor jumps to the beginning.

**Comment by erksch** [comment]
Having the same problem! Did anyone find a solution? :)
