### ISSUE TITLE
react-native ActivityIndicator breaks react-bootstrap Form.Control

### ISSUE THREAD

**Issue by AudaxDevelopment** [facebook/react-native#36953]
### Description

I use react-bootstrap (v. 2.7.2) for styling. On several places in my app I use Form.Control input box. It has nice "x" shaped button on the right side, which clears content of Form.Control and fires OnChange event. 
Since I started to use react-native ActivityIndicator (btw, very nice and easy to use), Form.Control does not contain clear button any more.
This is easily repeatable. I included simple app below.
Not sure if this is react-native or react-bootstrap error. No error is generated in React on compile.

### React Native Version

0.71.6

### Output of `npx react-native info`

    OS: Windows 10 10.0.17763
    CPU: (4) x64 Intel(R) Xeon(R) Gold 5218 CPU @ 2.30GHz
    Memory: 2.07 GB / 7.77 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: Not Found
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^18.2.0 => 18.2.0
    react-native: ^0.71.6 => 0.71.6
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

I pasted as simple as possible app below. 
If ActivityIndicator is included, Form.Control does not have clear button. 
If one comments import of ActivityIndicator and comments Spinner function, Form.Control does have clear button.
Spinner is not used at all, just included in React compile.

### Snack, code example, screenshot, or link to a repository

import React from 'react';
import {ActivityIndicator} from 'react-native';
import { Form } from 'react-bootstrap';

const Spinner = ({size}) => {
  return (
    <ActivityIndicator size={size || 'large'} style={{ flex: 1 }}/>
  );
 };

function App() {
  return (
    <div >
          <Form.Control type="search" placeholder="enter text" 
          />
    </div>
  );
}

export default App;

**Comment by cortinico** [comment]
Hi @AudaxDevelopment 
Thanks for reporting this issue.

I would suggest you open this issue against `react-bootstrap` first:
https://github.com/react-bootstrap/react-bootstrap/issues

We receive a huge quantity of issues and we try to prioritize those that have a clear reproducer which don't involve 3rd party libraries. This doesn't exclude a bug in React Native core though, but we can't investigate every possible library combination.

I'll be closing this for now, but feel free to reopen if the other repo points back to us as a issue in the core of React Native.
