### ISSUE TITLE
Build Failled when yarn run iOS

### ISSUE THREAD

**Issue by NicolasMentat** [facebook/react-native#36969]
### Description

I run this command do build my app and get this error:
FBReactNativeSpec-generated.mm normal arm64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'React-Codegen' from project 'Pods')

<img width="909" alt="Screenshot 2023-04-18 at 21 30 09" src="https://user-images.githubusercontent.com/125375345/232935563-267b7070-1b70-4724-a39a-efe7e97c8aa6.png">

### React Native Version

0.71.6

### Output of `npx react-native info`

System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M2
    Memory: 154.31 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.15.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.5.0 - /usr/local/bin/npm
    Watchman: 2023.04.17.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.6 => 0.71.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1- yarn install
2- pod install
3- yarn run iOS

### Snack, code example, screenshot, or link to a repository

is a private project

**Comment by dopplerDistortion** [comment]
for a little tip I've been having an issue like this after Xcode 14.3 update. With that update apple moved rosetta simulators to xcode. Make sure to launch a simulator with rosetta variant then try to run from terminal again. This might be a workaround until rn cli finds a way to launch rosetta variants from terminal.

**Comment by NicolasMentat** [comment]
> for a little tip I've been having an issue like this after Xcode 14.3 update. With that update apple moved rosetta simulators to xcode. Make sure to launch a simulator with rosetta variant then try to run from terminal again. This might be a workaround until rn cli finds a way to launch rosetta variants from terminal.

thx, its worked!!

**Comment by w1687021088** [comment]
> 小提示我在 Xcode 14.3 更新后遇到了这样的问题。通过该更新，苹果将 rosetta 模拟器移至 xcode。确保启动带有 rosetta 变形的模拟器，然后再试一次从终端运行。在rn cli找到从最终启动rosetta 变体的方法之前，这可能是一种解决方法。

Hello, how did you solve it, I am a React-native and Xcode novice

**Comment by onatvaris** [comment]
can you give xcode build error log
