### ISSUE TITLE
Animation is Slow and Janky

### ISSUE THREAD

**Issue by gilbox** [facebook/react-native#3696]
Demo:

https://rnplay.org/apps/_AOS_A

Tested on 

- Android (nexus 5) in prod mode. 
- iOS simulator

![rndrops](https://cloud.githubusercontent.com/assets/2136203/10738300/03c6efb4-7bd4-11e5-9d2c-2e249ef2a909.gif)

@vjeux

**Comment by sgonyea** [comment]
I'm seeing this as well in iOS on my Phone.  Even a simple ScrollView has a continuous stutter as it scrolls down the view.

**Comment by astreet** [comment]
We really need documentation on how to debug performance issues.

**Comment by sgonyea** [comment]
My suspicion is that this could be related to Image objects.  The ScrollView that has this issue is filled with a ~dozen images… mostly small; 4 squares lined up in a row, at the bottom, and a larger image at the top.

But yeah, docs on how to debug perf issues would be great.

**Comment by brentvatne** [comment]
There's this one: https://facebook.github.io/react-native/docs/performance.html#content

But that's just a first pass at it.. needs much more work!

**Comment by browniefed** [comment]
This will hopefully be resolved with #6466

**Comment by brentvatne** [comment]
I think this particular issue isn't specific enough to keep it open :)
