### ISSUE TITLE
Why blurOnSubmit={false} can't work in TextInput

### ISSUE THREAD

**Issue by Rr7716** [facebook/react-native#36978]
### Description

Why TextInput can't focus after submiting? I have already added blurOnSubmit={false}. I also use useRef focus function to implement it. However, it still can't work. Any help would be really amazing thank you 

### React Native Version

0.71.4

### Output of `npx react-native info`

System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i5-12400F
    Memory: 7.34 GB / 15.86 GB
  Binaries:
    Node: 18.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: 17.3.32922.545 (Visual Studio Enterprise 2022)
  Languages:
    Java: 17.0.6 - C:\Program Files\Common Files\Oracle\Java\javapath\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.4 => 0.71.4
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Click the TextInput component and type in some text.
Press 'enter' key to submit.
The TextInput component wouldn't be focused after that.

### Snack, code example, screenshot, or link to a repository

```javascript
<TextInput
style={{
  paddingHorizontal: 10,
  width: 230,
}}
onFocus={handleTextInputFocus}
value={text}
onChangeText={setText}
returnKeyType='none'
onSubmitEditing={sendMessage}
blurOnSubmit={false}
/>

const sendMessage = async () => {
    let temp = text;
    setText('');
    // scrollViewRef.current.scrollToEnd({ animated: true });
    try {
      const data = await FetchFromBackend(
        'http://192.168.31.119:8080/message/send_group_messages',
        SendGroupMessagesRequest({ user_id, group_id, text: temp })
      );
      if (data.data.ActionStatus === 'FAIL') {
        console.error(`send message fail: ${JSON.stringify(data)}`);
        return;
      }
      console.log(`send message success: ${JSON.stringify(data)}`);
    } catch (error) {
      console.log(err.message);
    }
    getMessages();
  };
```

**Comment by aziyatali** [comment]
@Rr7716 
Add input ref.

Default inputRef for blurOnSubmit is true, so just remove the blurOnSubmit={false}


```
  const inputRef = React.useRef<TextInput>(null);
  
<TextInput
style={{
  paddingHorizontal: 10,
  width: 230,
}}
onFocus={handleTextInputFocus}
value={text}
onChangeText={setText}
returnKeyType='none'
onSubmitEditing={sendMessage}
blurOnSubmit={true}
`ref={inputRef}`
/>
```

**Comment by Rr7716** [comment]
> 

I'm sorry. It doesn't work.

**Comment by Rr7716** [comment]
Any one can help me?

**Comment by fabriziobertoglio1987** [comment]
Do you still experience this issue? 

I have four years of experience maintaining facebook/react-native and I specialize in the Text and TextInput components. I currently have 58 [facebook/react-native PRs](https://github.com/facebook/react-native/pulls?q=is%3Apr+author%3Afabriziobertoglio1987+). 

If you still experience this issue, I will prepare a patched release with the fix.

Thanks a lot

**Comment by merfmango** [comment]
I'm having a similar issue, where pressing submit makes the soft keyboard go away, even though blurOnSubmit is false. I notice it only happens when returnKeyType is set to "none". When the prop is set to a different value or is not set, it seems to be fine.
