### ISSUE TITLE
When create a google meet Extra blank tab open

### ISSUE THREAD

**Issue by Dev-Demons** [facebook/react-native#36977]
### Description

I am developing an chat app.
Action Performed:
open any user chat
click on call icon select google meet option
automatic create extra blank tab on google chrome.
User gets confused due to extra blank tab. Because only white screen is shown in extra tab. The user does not know that this second tab has been opened. He will feel that there is an error.

Interesting; I can reproduce in iOS on Chrome, but in iOS on Safari it doesn't open that blank tab.

This is my code.

```
import {
          View, Pressable, Dimensions, Linking,
      } from 'react-native';
      this.menuItemData = [
                     {
                icon: GoogleMeetIcon,
                text: props.translate('videoChatButtonAndMenu.googleMeet'),
                onPress: () => {
                    this.toggleVideoChatMenu();
                    Linking.openURL(this.props.googleMeetURL);
                },
            },
        ];
```

### React Native Version

0.71.2

### Output of `npx react-native info`

It seems use the RCTLinkingManager.mm

+ (BOOL)application:(UIApplication *)app
            openURL:(NSURL *)URL
            options:(NSDictionary<UIApplicationOpenURLOptionsKey, id> *)options
{
  postNotificationWithURL(URL, self);
  return YES;
}

### Steps to reproduce

Action Performed:
open any user chat
click on call icon select google meet option
automatic create extra blank tab on google chrome.
User gets confused due to extra blank tab. Because only white screen is shown in extra tab. The user does not know that this second tab has been opened. He will feel that there is an error.

### Snack, code example, screenshot, or link to a repository

![googlemeet](https://user-images.githubusercontent.com/104343228/233087317-d8b3cdc5-6f26-45b7-82e6-ab3e541f3fb0.png)

**Comment by cortinico** [comment]
> 0.71.2-alpha.3

THis is not a valid React Native version. Can you clarify which version are you using?

**Comment by Dev-Demons** [comment]
It's v0.71.2.
