### ISSUE TITLE
unwanted top & bottom black border iphone 5

### ISSUE THREAD

**Issue by nvcken** [facebook/react-native#3698]
I tried run on device iphone 5 with simple app by react-native init command.
I get welcome to React Native screen
But It seem screen scaled because existing top & bottom black border
What I do wrong here ?
Help

**Comment by nvcken** [comment]
ios 7.1.1
Does it matter ?

**Comment by jaygarcia** [comment]
Screenshot?

**Comment by nvcken** [comment]
![12182283_420764984778638_686049295_n](https://cloud.githubusercontent.com/assets/3489866/10748007/3c4ed882-7c8e-11e5-87f2-f19295d97a24.jpg)

**Comment by nvcken** [comment]
![_420764984778638_686049295_n](https://cloud.githubusercontent.com/assets/3489866/10748064/da4269e6-7c8e-11e5-89f5-4f22478db76f.gif)

**Comment by ide** [comment]
Read these answers: https://stackoverflow.com/questions/12395200/how-to-develop-or-migrate-apps-for-iphone-5-screen-resolution

**Comment by nvcken** [comment]
I tried add LauchImage to Images.xcassets
And checked iOS 7.0 and later : iphone Portrait.
But still now work.
What I miss ?

**Comment by nvcken** [comment]
Figured out.
Thank you guys

**Comment by umfana** [comment]
@nvcken I have this same issue on an iPhone 4S with iOS 7 - what did you do in the end to fix it?

**Comment by nvcken** [comment]
I follow this http://stackoverflow.com/questions/18758882/launch-images-in-ios-7-with-xcode-5

**Comment by unicornRainbows** [comment]
I also have the same issue.. Might be after an update to react-native... I feel like its a Xcode issue.
I am running on device and simulator for iPhone 5 and get the dimensions for height and width as 480 X 320 which is not correct, it should be 320 × 568...

Any ideas? :)

**Comment by unicornRainbows** [comment]
I solved the issue...

Delete all the launch images, and when prompted by xCode to auto create the launch image "Default-568h@2x.png" say yes and BOOM it works..

To adapt your app to the new taller screen, the first thing you do is to change the launch image to: Default-568h@2x.png. Its size should be 1136x640 (HxW). Yep, having the default image in the new screen size is the key to let your app take the whole of new iPhone 5's screen.

<3

**Comment by Tiendq** [comment]
@unicornRainbows how did you do it exactly? It doesn't work for me :(

**Comment by unicornRainbows** [comment]
@Tiendq Remove all your launch screen assets, clean project, close Xcode, open it up again.. when you select the project and select iPhone5 simulator Xcode should prompt you to add in this image when you select the launch image asset drop down... Hope this helps.. this happened to me awhile back and was an Xcode related issue.

**Comment by fwchen** [comment]
any one help? all not work for me. i am crazy

**Comment by luqmanrom** [comment]
@fwchen 

I had this issues and solved it with this way, 

1. Go to XCode, and General tab
2. In App Icons and Launch Image sections, 
2.1. Click the dropdown Launch Image Source, and a pop up 
will come out, click Migrate
2.2. Click the dropdown Launch Screen File, and select the very first one


I had this issues after updating assets for AppIcons and SplashScreen

Hope it helps!

**Comment by fwchen** [comment]
@luqmanrom thank you. i fixed it. but i don't remember how 😂

**Comment by sfm2222** [comment]
@luqmanrom I just did till step 2 and it worked for me. Can you explain why it's happening and how migrate fixes it?
