### ISSUE TITLE
Activity class {com.package/com.package.MainActivity} does not exist.

### ISSUE THREAD

**Issue by singh-sukhmanjit** [facebook/react-native#36995]
### New Version

0.71.6

### Old Version

0.70.5

### Build Target(s)

Android Emulator - Android 13

### Output of `react-native info`

System:
    OS: Linux 5.15 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
    Memory: 5.26 GB / 15.39 GB
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.20.0 - ~/.nvm/versions/node/v16.20.0/bin/node
    Yarn: Not Found
    npm: 8.19.4 - ~/.nvm/versions/node/v16.20.0/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK:
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
  Languages:
    Java: 15.0.2 - /opt/jdk-15.0.2/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.6 => 0.71.6 
  npmGlobalPackages:
    *react-native*: Not Found

### Issue and Reproduction Steps

Issue is happening on Emulator as well as Physical Device with Android 13. Works fine on Android 11.

**Logs**
04-20 10:34:14.458   602   630 I ActivityManager: Force stopping com.package appid=10159 user=-1: installPackageLI
04-20 10:34:14.476   602   653 I PackageManager: Update package com.package code path from /data/app/~~2xJZTin_5_SWI5OWmXxgcg==/com.package-BTnDsbcAJ5f5t6WZS7IFPw== to /data/app/~~Z7NKlsWnovZ9eXk440R1cQ==/com.package-2l9R4XnBFtVNIH--v3C_bA==; Retain data and using new
04-20 10:34:14.698   602   653 I ActivityManager: Force stopping com.package appid=10159 user=0: pkg removed
04-20 10:34:14.756  1522  1522 I MediaProvider: Invalidating LocalCallingIdentity cache for package com.package. Reason: package android.intent.action.PACKAGE_REMOVED
04-20 10:34:14.874   839   839 D MediaPlayerList: Name of package changed: com.package
04-20 10:34:14.906  1522  1522 I MediaProvider: Invalidating LocalCallingIdentity cache for package com.package. Reason: package android.intent.action.PACKAGE_ADDED
04-20 10:34:14.908   839   839 D MediaPlayerList: Name of package changed: com.package
04-20 10:34:15.091   938   938 D CarrierSvcBindHelper: onPackageUpdateFinished: com.package
04-20 10:34:15.094   938   938 D CarrierSvcBindHelper: onPackageModified: com.package
04-20 10:34:15.181   602   602 I Telecom : CarModeTracker: Package com.package is not tracked.: SSH.oR@AM0
04-20 10:34:15.226   938   938 D ImsResolver: maybeAddedImsService, packageName: com.package
04-20 10:34:15.439   602  1940 W PackageManager: Intent does not match component's intent filter: Intent { act=android.intent.action.RUN flg=0x30000000 cmp=com.package/.MainActivity }
04-20 10:34:15.439   602  1940 W PackageManager: Access blocked: ComponentInfo{com.package/com.package.MainActivity}
04-20 10:34:15.439   602  1940 I ActivityTaskManager: START u0 {act=android.intent.action.RUN flg=0x30000000 cmp=com.package/.MainActivity} from uid 2000
04-20 10:34:15.450  1499  4822 W SQLiteLog: (28) double-quoted string literal: "com.package"
04-20 10:34:15.461   602   650 E VerityUtils: Failed to measure fs-verity, errno 1: /data/app/~~Z7NKlsWnovZ9eXk440R1cQ==/com.package-2l9R4XnBFtVNIH--v3C_bA==/base.apk
04-20 10:34:15.504   602   602 W AlarmManager: Package com.package, uid 10159 lost permission to set exact alarms!
04-20 10:34:16.247   602   650 E VerityUtils: Failed to measure fs-verity, errno 1: /data/app/~~Z7NKlsWnovZ9eXk440R1cQ==/com.package-2l9R4XnBFtVNIH--v3C_bA==/base.apk

**Comment by singh-sukhmanjit** [comment]
Issue is fixed after adding the following intent filter inside MainActivity in AndroidManifest.xml
```
<activity android:name=".MainActivity" ...>
    ...
    <intent-filter>
        <action android:name="android.intent.action.RUN"/>
    </intent-filter>
</activity>
```

**Comment by mksglu** [comment]
> Issue is fixed after adding the following intent filter inside MainActivity in AndroidManifest.xml
> 
> ```
> <activity android:name=".MainActivity" ...>
>     ...
>     <intent-filter>
>         <action android:name="android.intent.action.RUN"/>
>     </intent-filter>
> </activity>
> ```

You saved my time. Thanks a lot. @singh-sukhmanjit

**Comment by joshua-revolutions** [comment]
> Issue is fixed after adding the following intent filter inside MainActivity in AndroidManifest.xml
> 
> ```
> <activity android:name=".MainActivity" ...>
>     ...
>     <intent-filter>
>         <action android:name="android.intent.action.RUN"/>
>     </intent-filter>
> </activity>
> ```

This fixed it for me. Can you explain where you got this fix from?

**Comment by singh-sukhmanjit** [comment]
@joshua-revolutions I couldn't find any fix online so I was reading about what's new in Android 13 and found that intents are more strict and in the logs the issue was  "Intent does not match component's intent filter: Intent { **act=android.intent.action.RUN** flg=0x30000000 cmp=com.package/.MainActivity }". I guessed that act is action and added an action intent. It fixed the issue.

**Comment by ubaidmoin** [comment]
@singh-sukhmanjit 
I am facing this issue:

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
<application android:name=".MainApplication" ...>
    <activity android:name=".MainActivity" ...>
        <intent-filter>  
            <action android:name="android.intent.action.MAIN" />
            <action android:name="android.intent.action.RUN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
    </activity>
</application>
</manifest>
```

react-native: 0.72.4
react: 18.2.0
react-native-reanimated: 3.5.1
gradle: 7.5.1

Any suggestions, how can I fix this?

**Comment by ThaoDinh** [comment]
> @singh-sukhmanjit I am facing this issue:
> 
> ```
> <manifest xmlns:android="http://schemas.android.com/apk/res/android">
> <application android:name=".MainApplication" ...>
>     <activity android:name=".MainActivity" ...>
>         <intent-filter>  
>             <action android:name="android.intent.action.MAIN" />
>             <action android:name="android.intent.action.RUN" />
>             <category android:name="android.intent.category.LAUNCHER" />
>         </intent-filter>
>     </activity>
> </application>
> </manifest>
> ```
> 
> Error:
> 
> > BUILD SUCCESSFUL in 2m 13s
> > 714 actionable tasks: 37 executed, 677 up-to-date
> > info Connecting to the development server...
> > info Starting the app on "emulator-5554"...
> > Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.urbanasolutions.toolkit/.MainActivity }
> > Error type 3
> > Error: Activity class {com.urbanasolutions.toolkit/com.urbanasolutions.toolkit.MainActivity} does not exist.
> 
> react-native: 0.72.4 react: 18.2.0 react-native-reanimated: 3.5.1 gradle: 7.5.1
> 
> Any suggestions, how can I fix this?

@ubaidmoin I had the same issue with 0.72.5 and [this stackoverflow](https://stackoverflow.com/questions/76004854/error-activity-class-com-testapp-com-testapp-mainactivity-does-not-exist) fixed it for me. The solution is slitting into 2 `<intent-filter>`. Here my code
```
<intent-filter>
     <action android:name="android.intent.action.MAIN" />
     <category android:name="android.intent.category.LAUNCHER" />
 </intent-filter>
 <intent-filter>
     <action android:name="android.intent.action.VIEW"/>
     <category android:name="android.intent.category.DEFAULT"/>
     <category android:name="android.intent.category.BROWSABLE"/>
     <data  android:scheme="my-scheme-name"/>
 </intent-filter>
```

**Comment by ThaoDinh** [comment]
> ```
> <manifest xmlns:android="http://schemas.android.com/apk/res/android">
> <application android:name=".MainApplication" ...>
>     <activity android:name=".MainActivity" ...>
>         <intent-filter>  
>             <action android:name="android.intent.action.MAIN" />
>             <action android:name="android.intent.action.RUN" />
>             <category android:name="android.intent.category.LAUNCHER" />
>         </intent-filter>
>     </activity>
> </application>
> </manifest>
> ```
> 
> Error:
> 
> > BUILD SUCCESSFUL in 2m 13s
> > 714 actionable tasks: 37 executed, 677 up-to-date
> > info Connecting to the development server...
> > info Starting the app on "emulator-5554"...
> > Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.urbanasolutions.toolkit/.MainActivity }
> > Error type 3
> > Error: Activity class {com.urbanasolutions.toolkit/com.urbanasolutions.toolkit.MainActivity} does not exist.
> 
> react-native: 0.72.4 react: 18.2.0 react-native-reanimated: 3.5.1 gradle: 7.5.1
> 
> Any suggestions, how can I fix this?

@ubaidmoin I had the same issue with react-native 0.72.5 and this [stackoverflow](https://stackoverflow.com/questions/76004854/error-activity-class-com-testapp-com-testapp-mainactivity-does-not-exist) helped me. The fix is splitting into 2 `<intent-filter>`, here is mine:

```
<intent-filter>
    <action android:name="android.intent.action.MAIN" />
    <category android:name="android.intent.category.LAUNCHER" />
</intent-filter>
<intent-filter>
    <action android:name="android.intent.action.VIEW"/>
    <category android:name="android.intent.category.DEFAULT"/>
    <category android:name="android.intent.category.BROWSABLE"/>
    <data android:scheme="scheme-name"/>
</intent-filter>
```

**Comment by Gaspode69** [comment]
I am still facing problems with a rather old app, i.e. I am still getting this error under Android 14 (no problem with older Android versions):

`Error type 3
Error: Activity class {de.my.test/.HOMain} does not exist.
`

Can anyone give me a hint what's wrong? Here is my manifest:

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="de.my.test"
    android:versionCode="1"  
    android:versionName="1.0" >  
    <uses-sdk  
        android:minSdkVersion="11"
        android:targetSdkVersion="15" />
    <uses-permission android:name="android.permission.INTERNET"/>
    <application
        android:icon="@drawable/ic_launcher"
        android:label="@string/app_name"
        android:theme="@android:style/Theme.Holo" >
        <activity
            android:name=".HOMain"
            android:configChanges="keyboardHidden|orientation|screenSize"
            android:label="@string/title_activity_homain" 
            android:launchMode="singleTask" >
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
            <intent-filter>
                <action android:name="android.intent.action.RUN"/>
            </intent-filter>
        </activity>
    </application>
</manifest>
```

**Comment by Gaspode69** [comment]
OK, issue found:
```xml
    <uses-sdk
        android:minSdkVersion="15"
        android:targetSdkVersion="23" />
```
Solves it.
