### ISSUE TITLE
Text Cut Off on Android 13

### ISSUE THREAD

**Issue by im-minsung** [facebook/react-native#36992]
### React Native Version

0.71.4

### Output of `npx react-native info`

System:
    OS: macOS 12.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 25.00 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.1/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.1/bin/npm
    Watchman: 2022.09.26.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.4 => 0.71.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

Android SDK now using version is 33.

### Steps to reproduce

![Screenshot](https://user-images.githubusercontent.com/88317846/233252253-ae30ac2b-2008-4b0a-87ad-0978bd13255c.jpg)

Android 12 works fine.
However, this phenomenon occurs from Android 13.

The height doesn't cut when the line is changed.

If you enter special characters or certain languages on a single line, the height is cut off.

For example, special characters are cut off in height using ༒ or ༺.

Special Character Site url: https://unicodes.jessetane.com/%E0%BC%92

I tried to fix the height with text onlayout, but it didn't work out.

### Snack, code example, screenshot, or link to a repository

```
import React, { memo } from "react"
import { Text, View } from "react-native"

const AppContainer = memo(() => {
    return (
        <View style={{ flex: 1, justifyContent: "center" }}>
            <Text>ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZ</Text>
            <Text>{"\n"}</Text>
            <Text>かお 얼굴 さる 원숭이 たこ</Text>
            <Text>{"\n"}</Text>
            <Text>かお 얼굴 さる 원숭이 たこ༒</Text>
            <Text>{"\n"}</Text>
            <Text>かお 얼굴 さる 원숭이 たこ༺</Text>
            <Text>{"\n"}</Text>
            <Text>かお 얼굴 さる 원숭이 たこかお 얼굴 さる 원숭이 たこ かお 얼굴 ༒</Text>
        </View>
    )
})

export default AppContainer

```

**Comment by aziyatali** [comment]
@im-minsung  Please provide your device info. If its emulator then what kind of emulator. There has been duplicate issue in case it is one such as this: https://stackoverflow.com/questions/54750503/text-is-getting-cut-off-in-android-for-react-native

**Comment by im-minsung** [comment]
> @im-minsung Please provide your device info. If its emulator then what kind of emulator. There has been duplicate issue in case it is one such as this: https://stackoverflow.com/questions/54750503/text-is-getting-cut-off-in-android-for-react-native

༺ Thank you for apply!! ༻

I tested only with several Samsung devices.
It happens when it is Android 13 version on Samsung devices.
The writing is not cut off in version 12.

**Comment by jcdhlzq** [comment]
That the `Layout` instance is different between yoga and native may be responsible for such a problem. I've researched serveral cases and found that the width from `BoringMetrics` may cause that `TextView` makes a new `Layout` instance.
However, the new `Layout` instance has some differences from that in yoga. So, unify the measure method maybe a resolution. I still verify that.

**Comment by im-minsung** [comment]
> That the `Layout` instance is different between yoga and native may be responsible for such a problem. I've researched serveral cases and found that the width from `BoringMetrics` may cause that `TextView` makes a new `Layout` instance. However, the new `Layout` instance has some differences from that in yoga. So, unify the measure method maybe a resolution. I am still verifying that.

Thank you for apply.

I've been searching for a few days. Unlike other words, if a special word is included, the height does not seem to be as high as the descender value of the onTextLayout value in that word. Is this part related to padding top you modified?

**Comment by jcdhlzq** [comment]
> 

I'm trying to find a solution in native, namely YogaMeasureFunction. As you mentioned above, the onTextLayout has something wrong. The callback is releated `Layout` instance in YogaMeasureFunction. And that callback also has something abnormal when the text is RTL string like arabic.

By the way, in your case, is it normal in native view on Android 13?

**Comment by im-minsung** [comment]
> > 
> 
> I'm trying to find a solution in native, namely YogaMeasureFunction. As you mentioned above, the onTextLayout has something wrong. The callback is releated `Layout` instance in YogaMeasureFunction. And that callback also has something abnormal when the text is RTL string like arabic.
> 
> By the way, in your case, is it normal in native view on Android 13?

I've tested on native, and the words are cut equally...

I will try to solve it using padding and line height. If the line of text exceeds 2 lines, I will delete the style and apply it only when it is 1 line.
This method is not perfect, but I don't have time

If i succeed, I'll comment the code.

**Comment by im-minsung** [comment]
> 
I checked and found that if you use 'wrapcontent' in native, it won't cut. So I tried to find an option similar to 'wrapcontent' on RN but it was hard to find :(

Anyway, below is the code I worked on.

When I looked for a value similar to the previous one, I found 1.38.

I replaced the existing <text/> with the following components.

If you find a better way, I would appreciate it if you could reply :)

```
export default memo(({ style, numberOfLines, children }: IProps): React.ReactElement => {
    const fontSize = style?.fontSize ? style?.fontSize : 14
    const [lines, setLines] = useState(0)

    const onTextLayout = useCallback(
        ({
            nativeEvent: {
                lines: { length }
            }
        }: {
            nativeEvent: any
        }) => {
            setLines(length)
        },
        []
    )

    const customTextStyle = useCallback(() => {
        if (Platform.OS === "ios") return
        if (lines === 1) {
            return { lineHeight: fontSize * 1.38, paddingTop: fontSize - fontSize * 1.38 }
        }
    }, [])

    return (
        <Text style={[style, { alignSelf: "flex-start", ...customTextStyle() }]} onTextLayout={onTextLayout} numberOfLines={numberOfLines}>
            {children}
        </Text>
    )
})
```

**Comment by jcdhlzq** [comment]
Whether you are using Fabric arch?

**Comment by jcdhlzq** [comment]
I've created a PR for fixing such text cutoff phenomenon  #37271. Would you like to have a test? It will be very nice if you have a try and let me know the effect.

Remem to try it in non-Fabric mode! @im-minsung

**Comment by jimforever** [comment]
I have a Samsung S22 (Android 13) mobile phone and a Samsung A51 (Android 12) mobile phone. The fonts on the S22 mobile phone are intercepted, but the fonts on the A51 mobile phone are not intercepted. So I think this problem is likely to only appear on Android 13 Samsung phones. Try setting fontfamily:“ ” or fontWeight:'normal', the problem of characters being intercepted is gone

**Comment by fabriziobertoglio1987** [comment]
Do you still experience this issue? 

I have four years of experience maintaining facebook/react-native and I specialize in the Text and TextInput components. I currently have 58 [facebook/react-native PRs](https://github.com/facebook/react-native/pulls?q=is%3Apr+author%3Afabriziobertoglio1987+). 

If you still experience this issue, I will prepare a patched release with the fix.

Thanks a lot

**Comment by prashik0202** [comment]
You can refer this if helps in case!

https://blog.stackademic.com/mastering-ui-precision-solving-text-cut-off-in-react-native-android-apps-b8082da05fd3
