### ISSUE TITLE
[Docs] Document Platform in the modules section of the docs

### ISSUE THREAD

**Issue by ide** [facebook/react-native#3701]
Add basic docs for Platform and how it has the `OS` property that is equal to ios or android.

**Comment by zelahi** [comment]
@ide I would like to help out.  Would it be possible to take this on as a first issue?

**Comment by brentvatne** [comment]
@zelahi - sure! looking forward to the PR

**Comment by grabbou** [comment]
Would be way easier if my english was gramaticaly correct :D

**Comment by satya164** [comment]
Closing this since the relevant pull request has been merged.
