### ISSUE TITLE
[Android] Debugging in Android

### ISSUE THREAD

**Issue by PhilippKrone** [facebook/react-native#3702]
Hello,

is there any tutorial on how to debug RN code in android - especially core code?
@ide @brentvatne If you can gimme a hint as to how to actually do it, I can write a PR for the docs :)

Thanks
Philipp

**Comment by ide** [comment]
The gist is: build from source, use Android Studio, click the button with the Bug button, use breakpoints. I I think it's a pretty normal workflow but wish that building from source were a lot faster so people would do it a lot more -- it takes about 10-15 seconds to get a basic app on a device/simulator.

**Comment by astreet** [comment]
Debugging core RN code (Java I assume?) is the same as debugging any other Android application. We'd definitely appreciate some docs on it for developers working on native modules!

**Comment by PhilippKrone** [comment]
@astreet I was a little bit confused concerning the setup, but this thread helped me:

https://github.com/facebook/react-native/issues/3337

Especially the first answer from @chirag04 was extremely helpful and it would be nice to have it documented for other users as well I think.
