### ISSUE TITLE
npm start error, TypeError: Cannot read property 'root' of null

### ISSUE THREAD

**Issue by yuchao86** [facebook/react-native#3703]
yuchao@localhost: ~/GitHub/react-native master
 $ sudo npm start                                                    [14:01:49]

> react-native@0.12.0 start /Users/yuchao/GitHub/react-native
> ./packager/packager.sh || true

 ┌────────────────────────────────────────────────────────────────────────────┐
 │  Running packager on port 8081.                                            │
 │                                                                            │
 │  Keep this packager running while developing on any JS projects. Feel      │
 │  free to close this tab and run your own packager instance if you          │
 │  prefer.                                                                   │
 │                                                                            │
 │  https://github.com/facebook/react-native                                  │
 │                                                                            │
 └────────────────────────────────────────────────────────────────────────────┘
Looking for JS files in
   /Users/yuchao/GitHub/react-native

[14:01:52] <START> Building Dependency Graph
[14:01:52] <START> Crawling File System
[14:01:52] <START> Loading bundles layout
[14:01:52] <END>   Loading bundles layout (0ms)

React packager ready.

Error building DepdendencyGraph:
 TypeError: Cannot read property 'root' of null
    at /Users/yuchao/GitHub/react-native/packager/react-packager/src/DependencyResolver/crawlers/index.js:16:84
    at tryCallOne (/Users/yuchao/GitHub/react-native/node_modules/promise/lib/core.js:37:12)
    at /Users/yuchao/GitHub/react-native/node_modules/promise/lib/core.js:103:15
    at flush (/Users/yuchao/GitHub/react-native/node_modules/promise/node_modules/asap/raw.js:50:29)
    at doNTCallback0 (node.js:417:9)
    at process._tickCallback (node.js:346:13)

yuchao@localhost: ~/GitHub/react-native master

**Comment by astreet** [comment]
At the least, sounds like we need a better error message

**Comment by martinbigio** [comment]
I cannot repro this on the examples on the latest master
> cd Examples/2048
> npm start -> works fine

This would happen if the projet roots are not configured correctly. Have you created your own `rn-cli.config.js`?

**Comment by liuwin7** [comment]
upgrading watchman  works for me

**Comment by liuwin7** [comment]
Upgrading watchman works for me.

**Comment by yuchao86** [comment]
thanks all gays , when I was upgrade my node.js and npm , then start the RN again,  it's work good.

**Comment by uldza** [comment]
Have the same issue. 
I was following Getting Started guide from React Native websiste:
- Installed node with nvm
- installed watchman and flow with brew.
- npm install -g react-native-cli
- react-native init AwesomeProject
- opened AwesomeProject in Xcode, built it. 
- had the same error in terminal:
Error building DepdendencyGraph:
 TypeError: Cannot read property 'root' of null
    at /Users/uldza/dev/AwesomeProject/node_modules/react-native/packager/react-packager/src/DependencyResolver/crawlers/index.js:16:84
    at tryCallOne (/Users/uldza/dev/AwesomeProject/node_modules/promise/lib/core.js:37:12)
    at /Users/uldza/dev/AwesomeProject/node_modules/promise/lib/core.js:103:15
    at flush (/Users/uldza/dev/AwesomeProject/node_modules/asap/raw.js:50:29)
    at doNTCallback0 (node.js:428:9)
    at process._tickCallback (node.js:357:13)

My environment:
OSX 10.10.3
node v5.0.0
npm 3.3.6
watchman 3.0.0
flow 0.2.0

**Comment by qudao** [comment]
@uldza i'm the same as you.

**Comment by Hi-Rube** [comment]
@qudao brew update && brew reinstall watchman have fixed this problem

**Comment by uldza** [comment]
@Hi-Rube thanks that fixed the problem

**Comment by rogeliog** [comment]
@qudao :+1:

**Comment by hussfelt** [comment]
:+1:

**Comment by xushvai** [comment]
@qudao   :smile:

Thanks ！！！
