### ISSUE TITLE
YogaKit.modulemap not found when archiving with Xcode 14

### ISSUE THREAD

**Issue by justinrclarke** [facebook/react-native#37035]
### Description

Each time when I attempt to Archive the iOS version of the application to get ready to submit it to the Apple Store, I get the same error over and over. It doesn't matter if I delete my pod files and regenerate them with the latest updates to the podfiles, it still happens. **The app runs fine when I build and run the app with Metro, and everything is successful there.** The application will build fine, if I run it via the workspace, just can't Archive the app.

`/Users/user/Library/Developer/Xcode/DerivedData/LifeToday-caskrvjsffghbleogspftkkdkjla/Build/Intermediates.noindex/ArchiveIntermediates/LifeToday/IntermediateBuildFilesPath/LifeToday.build/Release-iphoneos/LifeToday.build/DerivedSources/LifeToday_vers.c module map file '/Users/user/Library/Developer/Xcode/DerivedData/LifeToday-caskrvjsffghbleogspftkkdkjla/Build/Intermediates.noindex/ArchiveIntermediates/LifeToday/BuildProductsPath/Release-iphoneos/YogaKit/YogaKit.modulemap' not found
`

**Below are my npm dependencies.**

`"dependencies": {
    "@react-native-async-storage/async-storage": "github:react-native-async-storage/async-storage",
    "@react-native-community/slider": "^4.4.2",
    "@react-navigation/bottom-tabs": "^6.5.7",
    "@react-navigation/drawer": "^6.6.2",
    "@react-navigation/native": "^6.1.6",
    "@react-navigation/native-stack": "^6.9.12",
    "@react-navigation/stack": "^6.3.16",
    "axios": "^1.3.4",
    "babel-plugin-module-resolver": "^5.0.0",
    "react": "18.2.0",
    "react-native": "0.71.6",
    "react-native-airplay-btn": "^1.1.0",
    "react-native-expo-viewport-units": "^0.0.8",
    "react-native-fast-image": "^8.6.3",
    "react-native-gesture-handler": "^2.9.0",
    "react-native-google-cast": "^4.6.2",
    "react-native-rate": "^1.2.12",
    "react-native-reanimated": "^3.0.2",
    "react-native-render-html": "^6.3.4",
    "react-native-safe-area-context": "^4.5.0",
    "react-native-screens": "^3.20.0",
    "react-native-simple-audio-player": "^1.0.3",
    "react-native-snap-carousel": "^3.9.1",
    "react-native-splash-screen": "^3.3.0",
    "react-native-vector-icons": "^9.2.0",
    "react-native-video": "^5.2.1",
    "react-native-video-controls": "^2.8.1",
    "react-native-webview": "^12.0.0",
    "react-redux": "^8.0.5",
    "redux": "^4.2.1",
    "redux-persist": "^6.0.0",
    "redux-thunk": "^2.4.2"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native-community/eslint-config": "^3.2.0",
    "@tsconfig/react-native": "^2.0.2",
    "@types/jest": "^29.2.1",
    "@types/react": "^18.0.24",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.2.1",
    "eslint": "^8.19.0",
    "jest": "^29.2.1",
    "metro-react-native-babel-preset": "0.73.9",
    "prettier": "^2.4.1",
    "react-test-renderer": "18.2.0",
    "typescript": "4.8.4"
  },`

### React Native Version

0.71.6

### Output of `npx react-native info`

System:
    OS: macOS 13.3.1
    CPU: (12) arm64 Apple M2 Pro
    Memory: 169.80 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.0.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.6.4 - /opt/homebrew/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.9862592
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.6 => 0.71.6
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. npm install
2. cd ios && pod install
3. Open XCode Project
4. Select Target
5. Product -> Archive

### Snack, code example, screenshot, or link to a repository

<img width="1728" alt="Screenshot 2023-04-21 at 4 20 34 PM" src="https://user-images.githubusercontent.com/1985762/233736586-580e1dee-928b-4a60-95e8-1e5cecee2495.png">

**Comment by justinrclarke** [comment]
> Did you solve this problem? I am also facing this problem. It just happened after upgrading Xcode 14.3 today.

I have not.

**Comment by mfalcone** [comment]
i had the same issue.
i installed an old version of xcode: 13
https://developer.apple.com/download/all/
and move it to Application folder/ old_xcode/
then i run the project with it.
voila!

**Comment by dariuszsobkowicz** [comment]
same issue but with FirebaseCoreInternal

**Comment by davitsargsyan92** [comment]
I've the same issue on Mac M1 . Is there oany solution for this ?

**Comment by dariuszsobkowicz** [comment]
> I've the same issue on Mac M1 . Is there any solution for this ?

2 things:
- set Pods -> Excluded Architectures to arm64, this allow you to built
- softwareupdate --install-rosetta --agree-to-license, this allow you to run app in simulator

**Comment by chrismerino** [comment]
> I've the same issue on Mac M1 . Is there any solution for this ?

Same issue with FirebaseCoreInternal and many others, I even downgraded to Xcode 14.2.
Archive works for some reason but trying to run the app, then it shows many errors with "Module map file ... FirebaseCoreInternal.modulemap" not found.

**Comment by dariuszsobkowicz** [comment]
> > I've the same issue on Mac M1 . Is there any solution for this ?
> 
> Same issue with FirebaseCoreInternal and many others, I even downgraded to Xcode 14.2. Archive works for some reason but trying to run the app, then it shows many errors with "Module map file ... FirebaseCoreInternal.modulemap" not found.

downgrade to 13 or https://github.com/facebook/react-native/issues/37035#issuecomment-1600571386

**Comment by AaronYin0514** [comment]
这个可以解决
https://sarunw.com/posts/open-using-rosetta-in-xcode-14-3/

**Comment by pablo4lvarez** [comment]
Hi! i'm having a similar Issue trying to run a build but in commandline: 
`xcodebuild build -scheme "Glik" -sdk iphoneos -destination generic/platform=iOS`
i can perfectly do a Build using XCode app, but i can't using commandline
