### ISSUE TITLE
[Android] 0.13 Error when ToolbarAndroid config actions

### ISSUE THREAD

**Issue by bastengao** [facebook/react-native#3704]
Show error `undefine is not an object RCTUIManager.ToolbarAndroid.Constants.ShowAsAction` when ToolbarAndroid config actions such as `<ToolbarAndroid actions={[{title: 'test', show: 'always'}]} />`.

This error disappears using 0.12 version instead of 0.13.

**Comment by yychun1217** [comment]
I encountered the same issue, i am using 0.14.2 version

I cleaned the project in Android Studio, yet still not ok

**Comment by MuruganDurai** [comment]
I am also facing the same issue with 0.13.2 at windows setup. Can you check please?

**Comment by bastengao** [comment]
I console `RCTUIManager.ToolbarAndroid.Constants` in ToolbarAndroid.android.js, it's undefined. It seems `ReactToolbarManager.getExportedViewConstants` doesn't work. No more help I can do.

**Comment by satya164** [comment]
@bastengao Is this still an issue with 0.17?

**Comment by bastengao** [comment]
@satya164 This issue doesn't  occur on 0.17.

**Comment by satya164** [comment]
Thanks.
