### ISSUE TITLE
Dialog TextInput Cursor Flickering

### ISSUE THREAD

**Issue by tingan** [facebook/react-native#37048]
### Description

when use react native paper dialog with input:
 <Portal>
       <Dialog visible={visible} onDismiss={hideDialog} style={styles.dialog}>
      <Dialog.Content scrollEnabled={false}>
     <TextInput
         multiline={true}
        mode={'outlined'}
          value={importText}
          onChangeText={text => handleTextChange(text)}
         style={styles.input}
         />
</Dialog.Content>

I reported first to react native paper github issues, but they say it's issue with react native itself. https://stackoverflow.com/questions/64921365/react-native-paper-textinput-in-modal-cursor-flashes-backwards-after-a-characte

### React Native Version

0.71.6

### Output of `npx react-native info`

System:
    OS: macOS 13.2.1
    CPU: (10) x64 Apple M1 Pro
    Memory: 21.62 MB / 16.00 GB
    Shell: 5.8 - /usr/local/bin/zsh
  Binaries:
    Node: 18.10.0 - /usr/local/bin/node
    Yarn: 3.5.0 - /usr/local/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
    Watchman: 2022.10.24.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.2 - /Library/Java/JavaVirtualMachines/jdk-17.0.2.jdk/Contents/Home/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.7 => 0.71.7 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

https://stackoverflow.com/questions/64921365/react-native-paper-textinput-in-modal-cursor-flashes-backwards-after-a-characte

### Snack, code example, screenshot, or link to a repository

https://stackoverflow.com/questions/64921365/react-native-paper-textinput-in-modal-cursor-flashes-backwards-after-a-characte

**Comment by AFDHAL2009** [comment]
This issue still on expo 52 react native 0.76 in New architecture after upgrade from 51 android
