### ISSUE TITLE
Unicode LINE SEPARATOR (U+2028) Got JS Exception: SyntaxError

### ISSUE THREAD

**Issue by Emory-M** [facebook/react-native#3705]
In my Android React Native project, fetch url content contain LINE SEPARATOR (U+2028) Got JS Exception!
But same content can parse in React-Native Debug Mode and Node.js REPL

**Comment by astreet** [comment]
Can you post a demo app on rnplay.org so we can reproduce this?

**Comment by Emory-M** [comment]
var str = 'test test';//the unicode LINE SEPARATOR(\u2028) between 'test' with 'test'
<Text>{str}</Text>
Content just like this.
I post the demo on
https://rnplay.org/apps/Bhqo8w

**Comment by astreet** [comment]
Using a unicode escape sequence in source code should be an option. What is 'normal' dev mode vs 'debug' dev mode?

**Comment by Emory-M** [comment]
@astreet 
'normal' dev mode without chrome debugging
'debug' dev mode use chrome debugging(press F2 in Android emulator to enabled)

some time we can't to escape the Unicode from web
PS:iOS NSJSONSerialization and Node.js can parse this json

**Comment by sandect** [comment]
@astreet 
I got the same issue,  the same code worked on IOS platform, but broken down on Android, after replacing the \u2028, worked.

**Comment by satya164** [comment]
Is this still an issue?

**Comment by satya164** [comment]
Duplicate of #4961
