### ISSUE TITLE
[Expo][Realm] Cannot read property 'Helpers_get_table' of undefined, js engine: hermes

### ISSUE THREAD

**Issue by RonaldDBezerra** [facebook/react-native#37056]
![WhatsApp Image 2023-04-23 at 17 06 58](https://user-images.githubusercontent.com/87492867/233863092-4deac504-b754-4884-bc47-478c2aa513f0.jpeg)
### Description

I was trying to use realmDB in my react native application, but it had some problems in the current version, so I downloaded the "^12.0.0-alpha.2" version, apparently it solved it, but I have an error appearing, and I don't know how to solve...

TypeError: Cannot read property 'Helpers_get_table' of undefined, js engine: hermes
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:102:17 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:148:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:39 in handleError
at node_modules/expo/build/errors/ExpoErrorManager.js:25:19 in errorHandler
at node_modules/expo/build/errors/ExpoErrorManager.js:30:24 in <anonymous>
at node_modules/@react-native/polyfills/error-guard.js:49:36 in ErrorUtils.reportFatalError
at node_modules/metro-runtime/src/polyfills/require.js:225:40 in guardedLoadModule
at node_modules/metro-runtime/src/polyfills/require.js:127:23 in metroRequire
at http://192.168.1.70:19000/index.bundle?platform=android&dev=true&hot=false&strict=false&minify=false:null in global

### React Native Version

0.71.6

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: Linux 5.19 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz
    Memory: 7.03 GB / 15.32 GB
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.6 => 0.71.6 
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

. npm install realm@^12.0.0-alpha.2
. Error "Cannot read property 'Helpers_get_table' of undefined, js engine: hermes"

### Snack, code example, screenshot, or link to a repository

![Captura de tela de 2023-04-23 16-44-08](https://user-images.githubusercontent.com/87492867/233861611-585ef3fb-4695-4ec3-847e-31bdf28e7f14.png)

**Comment by cortinico** [comment]
Please also consider reporting this to Realm here:
https://github.com/realm/realm-js
