### ISSUE TITLE
Xcode warnings for main.jsbundle

### ISSUE THREAD

**Issue by yvbeek** [facebook/react-native#37051]
### Description

When I build my React-Native project in Xcode, I get about 38 warnings for the `main.jsbundle` file. Here's a screenshot of some of the warnings.

<img width="365" alt="image" src="https://user-images.githubusercontent.com/966500/233806668-f063aa55-b76f-4746-ab48-7864778fc0e5.png">

It looks like these warnings are caused by the `hermesc` step in the build process:
```
[snip]/ios/Pods/hermes-engine/destroot/bin/hermesc -emit-binary -Og -out 
[snip]/Library/Developer/Xcode/DerivedData/[snip]/Build/Products/Debug-iphoneos/[snip]/main.jsbundle 
[snip]/Library/Developer/Xcode/DerivedData/[snip]/Build/Products/Debug-iphoneos/main.jsbundle
```

Is there a way to get rid of these warnings?

### React Native Version

0.71.7

### Output of `npx react-native info`

```
System:
    OS: macOS 13.3.1
    CPU: (12) arm64 Apple M2 Max
    Memory: 1.30 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.14.2 - ~/.nvm/versions/node/v18.14.2/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.14.2/bin/yarn
    npm: 9.6.4 - ~/.nvm/versions/node/v18.14.2/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.12.0 - /Users/206637259/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.9862592
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.18 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.7 => 0.71.7 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

- Create a React-Native project
- Build the project in Xcode

### Snack, code example, screenshot, or link to a repository

No example because this is a build issue

**Comment by molenick** [comment]
Seeing this in the latest RN as well, and can also confirm I found the same source, `hermesc`.

It would be useful to be able to suppress these (maybe there's already a way to pass flags to hermesc?), but it'd also be useful to see warnings for my Javascript during build without noise.
