### ISSUE TITLE
Android 7.1.2 large screen device crash, crash in libjsc.so library

### ISSUE THREAD

**Issue by newbieyhj** [facebook/react-native#37054]
### Description

 **libjsc.so library, stack as follows:**

Operating system: Android
                  0.0.0 Linux 4.4.126 #5 SMP PREEMPT Wed May 13 14:57:57 CST 2020 aarch64
CPU: arm64
     6 CPUs

GPU: UNKNOWN

Crash reason:  SIGILL
Crash address: 0x76f5eacfc0
Process uptime: not available

Thread 61 (crashed)
 0  0x76f5eacfc0
     x0 = 0xffff000000000004    x1 = 0x0000000000000000
     x2 = 0x0000000000000000    x3 = 0x0000000000000030
     x4 = 0x00000076f5afe1b0    x5 = 0x0000000000000000
     x6 = 0x0000006d82966e60    x7 = 0x0000000000000000
     x8 = 0x0000000000000004    x9 = 0xffff000000000002
    x10 = 0xc49d3b1eed66a617   x11 = 0xc49d3b736ff0c857
    x12 = 0x0000000000000003   x13 = 0x0000000000000000
    x14 = 0xd4200000d4200000   x15 = 0x0000000000000000
    x16 = 0x0000007701767368   x17 = 0x00000076f5c0ccc8
    x18 = 0x0000000000000000   x19 = 0x00000076f5c00000
    x20 = 0x00000076fdeb3438   x21 = 0x00000076f5a1bdb0
    x22 = 0x0000000000000002   x23 = 0x00000076ff2b9d60
    x24 = 0x00000076f49916b0   x25 = 0x00000076e72d1410
    x26 = 0x00000076f42144b0   x27 = 0xffff000000000000
    x28 = 0xffff000000000002    fp = 0x00000076ff2b8d80
     lr = 0x00000076f5eacfbc    sp = 0x00000076ff2b8d00
     pc = 0x00000076f5eacfc0
    Found by: given as instruction pointer in context
 1  0x76f5eacfb8
     fp = 0x00000076ff2b8e30    lr = 0x00000076f5ea8648
     sp = 0x00000076ff2b8d90    pc = 0x00000076f5eacfbc
    Found by: previous frame's frame pointer
 2  0x76f5ea8644
     fp = 0x00000076ff2b8f30    lr = 0x00000076f5eabb3c
     sp = 0x00000076ff2b8e40    pc = 0x00000076f5ea8648
    Found by: previous frame's frame pointer
 3  0x76f5eabb38
     fp = 0x00000076ff2b8fd0    lr = 0x00000077011cf538
     sp = 0x00000076ff2b8f40    pc = 0x00000076f5eabb3c
    Found by: previous frame's frame pointer
 4  libjsc.so + 0x2f5534
     fp = 0x00000076ff2b9080    lr = 0x00000077011cf538
     sp = 0x00000076ff2b8fe0    pc = 0x00000077011cf538
    Found by: previous frame's frame pointer
 5  libjsc.so + 0x2f5534
     fp = 0x00000076ff2b9130    lr = 0x00000077011d0a24
     sp = 0x00000076ff2b9090    pc = 0x00000077011cf538
    Found by: previous frame's frame pointer
 6  libjsc.so + 0x2f6a20
     fp = 0x00000076ff2b91c0    lr = 0x00000077011cf538
     sp = 0x00000076ff2b9140    pc = 0x00000077011d0a24
    Found by: previous frame's frame pointer
 7  libjsc.so + 0x2f5534
     fp = 0x00000076ff2b9270    lr = 0x00000077011cf538
     sp = 0x00000076ff2b91d0    pc = 0x00000077011cf538
    Found by: previous frame's frame pointer
 8  libjsc.so + 0x2f5534
     fp = 0x00000076ff2b92f0    lr = 0x00000077011cf5e0
     sp = 0x00000076ff2b9280    pc = 0x00000077011cf538
    Found by: previous frame's frame pointer
 9  libjsc.so + 0x2f55dc
     fp = 0x00000076ff2b9370    lr = 0x00000077011cf5e0
     sp = 0x00000076ff2b9300    pc = 0x00000077011cf5e0
    Found by: previous frame's frame pointer
10  libjsc.so + 0x2f55dc
     fp = 0x00000076ff2b9400    lr = 0x00000076f5f023a0
     sp = 0x00000076ff2b9380    pc = 0x00000077011cf5e0
    Found by: previous frame's frame pointer
11  0x76f5f0239c
     fp = 0x00000076ff2b94a0    lr = 0x00000077011cf5e0
     sp = 0x00000076ff2b9410    pc = 0x00000076f5f023a0
    Found by: previous frame's frame pointer
12  libjsc.so + 0x2f55dc
     fp = 0x00000076ff2b9530    lr = 0x00000076f5f023a0
     sp = 0x00000076ff2b94b0    pc = 0x00000077011cf5e0
    Found by: previous frame's frame pointer
13  0x76f5f0239c
     fp = 0x00000076ff2b95d0    lr = 0x00000077011cf538
     sp = 0x00000076ff2b9540    pc = 0x00000076f5f023a0
    Found by: previous frame's frame pointer
14  libjsc.so + 0x2f5534
     fp = 0x00000076ff2b9660    lr = 0x00000077011cf5e0
     sp = 0x00000076ff2b95e0    pc = 0x00000077011cf538
    Found by: previous frame's frame pointer
15  libjsc.so + 0x2f55dc
     fp = 0x00000076ff2b96e0    lr = 0x00000077011cf5e0
     sp = 0x00000076ff2b9670    pc = 0x00000077011cf5e0
    Found by: previous frame's frame pointer
16  libjsc.so + 0x2f55dc
     fp = 0x00000076ff2b9770    lr = 0x00000077011cf538
     sp = 0x00000076ff2b96f0    pc = 0x00000077011cf5e0
    Found by: previous frame's frame pointer
17  libjsc.so + 0x2f5534
     fp = 0x00000076ff2b9810    lr = 0x00000077011d0a24
     sp = 0x00000076ff2b9780    pc = 0x00000077011cf538
    Found by: previous frame's frame pointer
18  libjsc.so + 0x2f6a20
     fp = 0x00000076ff2b98a0    lr = 0x00000077011cf5e0
     sp = 0x00000076ff2b9820    pc = 0x00000077011d0a24
    Found by: previous frame's frame pointer
19  libjsc.so + 0x2f55dc
     fp = 0x00000076ff2b9940    lr = 0x00000077011cf538
     sp = 0x00000076ff2b98b0    pc = 0x00000077011cf5e0
    Found by: previous frame's frame pointer
20  libjsc.so + 0x2f5534
     fp = 0x00000076ff2b99b0    lr = 0x00000077011cf538
     sp = 0x00000076ff2b9950    pc = 0x00000077011cf538
    Found by: previous frame's frame pointer
21  libjsc.so + 0x2f5534
     fp = 0x00000076ff2b9a20    lr = 0x00000077011cf538
     sp = 0x00000076ff2b99c0    pc = 0x00000077011cf538
    Found by: previous frame's frame pointer
22  libjsc.so + 0x2f5534
     fp = 0x00000076ff2b9a90    lr = 0x00000077011cf538
     sp = 0x00000076ff2b9a30    pc = 0x00000077011cf538
    Found by: previous frame's frame pointer
23  libjsc.so + 0x2f5534
     fp = 0x00000076ff2b9b00    lr = 0x00000077011cf5e0
     sp = 0x00000076ff2b9aa0    pc = 0x00000077011cf538
    Found by: previous frame's frame pointer
24  libjsc.so + 0x2f55dc
     fp = 0x00000076ff2b9b90    lr = 0x00000077011cf538
     sp = 0x00000076ff2b9b10    pc = 0x00000077011cf5e0
    Found by: previous frame's frame pointer
25  libjsc.so + 0x2f5534
     fp = 0x00000076ff2b9bc0    lr = 0x00000076f5e00f00
     sp = 0x00000076ff2b9ba0    pc = 0x00000077011cf538
    Found by: previous frame's frame pointer
26  0x76f5e00efc
     fp = 0x00000076ff2b9ca0    lr = 0x00000077011b2138
     sp = 0x00000076ff2b9bd0    pc = 0x00000076f5e00f00
    Found by: previous frame's frame pointer
27  libjsc.so + 0x2d8134
     fp = 0x00000076ff2b9f10    lr = 0x0000007701105818
     sp = 0x00000076ff2b9cb0    pc = 0x00000077011b2138
    Found by: previous frame's frame pointer
28  libjsc.so + 0x22b814
     fp = 0x00000076ff2ba1d0    lr = 0x0000007701105868
     sp = 0x00000076ff2b9f20    pc = 0x0000007701105818
    Found by: previous frame's frame pointer
29  libjsc.so + 0x22b864
     fp = 0x00000076ff2ba250    lr = 0x0000007701906f98
     sp = 0x00000076ff2ba1e0    pc = 0x0000007701105868
    Found by: previous frame's frame pointer
30  libjscexecutor.so + 0x1ef94
     fp = 0x00000076ff2ba2d0    lr = 0x0000007701906d88
     sp = 0x00000076ff2ba260    pc = 0x0000007701906f98
    Found by: previous frame's frame pointer
31  libjscexecutor.so + 0x1ed84
     fp = 0x00000076ff2ba310    lr = 0x00000077018b9414
     sp = 0x00000076ff2ba2e0    pc = 0x0000007701906d88
    Found by: previous frame's frame pointer
32  libreactnativejni.so + 0x97410
     fp = 0x00000076ff2ba340    lr = 0x00000077018ba0f4
     sp = 0x00000076ff2ba320    pc = 0x00000077018b9414
    Found by: previous frame's frame pointer
33  libreactnativejni.so + 0x980f0
     fp = 0x00000076ff2ba3f0    lr = 0x0000007701898798
     sp = 0x00000076ff2ba350    pc = 0x00000077018ba0f4
    Found by: previous frame's frame pointer

### React Native Version

0.67.3

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: Linux 5.10 Deepin 20.2.3 20.2.3
    CPU: (16) x64 Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
    Memory: 727.42 MB / 31.11 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 16.13.0 - /usr/local/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 8.1.0 - /usr/local/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 19, 21, 22, 23, 25, 26, 28, 29, 30, 31
      Build Tools: 27.0.3, 28.0.2, 28.0.3, 29.0.1, 29.0.2, 30.0.0, 30.0.1, 30.0.2, 30.0.3, 31.0.0
      System Images: android-24 | ARM EABI v7a, android-29 | Google Play ARM 64 v8a, android-30 | Google APIs Intel x86 Atom, android-31 | ARM 64 v8a, android-31 | Intel x86 Atom_64, android-TiramisuPrivacySandbox | Google Play ARM 64 v8a
      Android NDK: 21.1.6352462
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 1.8.0_301 - /home/xieyuan/soft/work_soft/jdk/jdk1.8.0_301/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.3 => 0.67.3 
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

There is a certain probability that the app will blink back when opened

### Snack, code example, screenshot, or link to a repository

There is no

**Comment by cortinico** [comment]
Sadly this stacktrace is inactionalbe. We don't maintain libjsc + the stacktrace is not symbolicated so there is really nothing we can do here.
