### ISSUE TITLE
Black Screen on RN 0.71.6

### ISSUE THREAD

**Issue by richardReitz** [facebook/react-native#37057]
### Description

Hey guys,

I did a zero install and am facing a black screen.
I put logs on the home screen (App.tsx) and they come out normally, but the App remains on a black screen.

The home screen is simple:
```JS
import React from "react";
import { Text, View } from "react-native";

console.log("Call App TSX");

function App(): JSX.Element {
  return (
    <View>
      <Text>Hello World</Text>
    </View>
  );
}

export default App;
```

The AppDelegate.m
```C++
#import "AppDelegate.h"

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  self.moduleName = @"MyApp";
  // You can add your custom initial props in the dictionary below.
  // They will be passed down to the ViewController used by React Native.
  self.initialProps = @{};

 return [super application:application didFinishLaunchingWithOptions:launchOptions];
}
```

I tried using [react-native-bootsplash](https://github.com/zoontek/react-native-bootsplash) to see if it changed anything, but I had the same problem.

The most interesting thing is that I have console.logs outputs, but the screen is black. It's like React Native is not "plugged" into the Native view.

Any suggestion?

### React Native Version

0.71.6

### Output of `npx react-native info`

System:
    OS: macOS 12.6.4
    CPU: (4) x64 Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz
    Memory: 29.32 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.20.0 - ~/.nvm/versions/node/v16.20.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.4 - ~/.nvm/versions/node/v16.20.0/bin/npm
    Watchman: 2023.04.03.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.9862592
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.18 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. Open XCode and Build or run npx react-native run-ios
2. Wait for build and launch
3. See the black screen

### Snack, code example, screenshot, or link to a repository

See the bug description for code snippets.

**Comment by cortinico** [comment]
```
react: Not Found
react-native: Not Found
react-native-macos: Not Found
```

The fact that your `react-native` version is missing here in the info is suspicious.
How are you creating the project?

**Comment by richardReitz** [comment]
Yes, I have now updated to RN 0.71.7 and I am facing the same issue.

The code is simple, it should work.

It could be that it occurred right after I installed other libraries. But anyway, I'm not calling them in the code and isn't this part of the AppDelegate responsible for displaying the RN on the simulator screen?

**Comment by richardReitz** [comment]
I think my command was updated, I ran it again now.

```
System:
    OS: macOS 12.6.4
    CPU: (4) x64 Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz
    Memory: 800.28 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.20.0 - ~/.nvm/versions/node/v16.20.0/bin/node
    Yarn: 1.22.19 - ~/Documents/client-mobile-v2/node_modules/.bin/yarn
    npm: 8.19.4 - ~/.nvm/versions/node/v16.20.0/bin/npm
    Watchman: 2023.04.03.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.9862592
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.18 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.7 => 0.71.7 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by richardReitz** [comment]
Reading other comments with the same problem, it seems something that was related to this code snippet in Info.plist.
```
<key>UIApplicationSceneManifest</key>
	<dict>
		<key>UIApplicationSupportsMultipleScenes</key>
		<true/>
	</dict>
```
Removing this brought the application's home screen back to display.

**Comment by Pranav-yadav** [comment]
>Yes, I have now updated to RN 0.71.7 and I am facing the same issue.

@richardReitz Please update issue description as well to avoid confusion.

**Comment by cortinico** [comment]
Closing as @richardReitz is unresponsive
