### ISSUE TITLE
Upload to TestFlight error: Binary file not valid on RN 0.71.7

### ISSUE THREAD

**Issue by develgooapps** [facebook/react-native#37062]
### New Version

0.71.7

### Old Version

0.69.7

### Build Target(s)

iOS upload to Testflight

### Output of `react-native info`

System:
    OS: macOS 12.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 63.23 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
    Watchman: 2022.10.10.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/robertoperez/.rvm/gems/ruby-2.7.5/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8309675
    Xcode: 14.0/14A309 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /Users/robertoperez/.jenv/shims/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.7 => 0.71.7 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Issue and Reproduction Steps

After upgrading React Native to 0.71.7, our app executes without problem in an iPhone simulator and a in physical device. It algo archives successfully and apparently uploads to Testflight, but within 5 to 10 minutes, we get an email from Apple saying that the app wasn't uploaded due to the followinrgproblem: 

ITMS-90429: Invalid Swift Support - The files libswiftDarwin.dylib, libswiftMetal.dylib, libswiftCoreAudio.dylib, libswiftsimd.dylib, libswiftQuartzCore.dylib, libswift_Concurrency.dylib, libswiftos.dylib, libswiftObjectiveC.dylib, libswiftDispatch.dylib, libswiftCoreLocation.dylib, libswiftCoreGraphics.dylib, libswiftCoreData.dylib, libswiftCoreFoundation.dylib, libswiftUIKit.dylib, libswiftCoreMedia.dylib, libswiftAVFoundation.dylib, libswiftCore.dylib, libswiftFoundation.dylib, libswiftPhotos.dylib, libswiftCoreImage.dylib aren’t at the expected location /Payload/******.app/Frameworks. Move the file to the expected location, rebuild your app using the current public (GM) version of Xcode, and resubmit it.

We have tries to reinstall pods and yarn dependencies, but it seems to be a problem with the way XCode is packing the archive. We have searched the internet for an answer for this problem, but we did not come across any solutions... Is anyone else having this problem? Thank you in advance!

**Comment by radko93** [comment]
You're running an old Xcode version. It's not supported anymore by Apple.
