### ISSUE TITLE
UI freezes while API calls are active

### ISSUE THREAD

**Issue by riya-coddle** [facebook/react-native#37064]
### Description

I'm facing an issue in react native application where the UI freezes if any network requests are in progress. Every time that I do a request to API the UI freezes until the request is responded.

### React Native Version

0.70.6

### Output of `npx react-native info`

System:
    OS: macOS 12.6.2
    CPU: (4) x64 Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
    Memory: 539.96 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
    Yarn: Not Found
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
    Watchman: 2023.01.30.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK: Not Found
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9514443
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.6 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.6 => 0.70.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Create a heavy API request by using Axios / fetch()

### Snack, code example, screenshot, or link to a repository

nil

**Comment by zhangsl1987** [comment]
is here any solutions?
