### ISSUE TITLE
Black Screen on RN 0.69.0

### ISSUE THREAD

**Issue by julien-kv** [facebook/react-native#37060]
### Description

Hello guys!

I am having this issue.

Description
When I launch my RN iOS app (release build) from the background to the foreground after a long time, the App remains on a black screen. When we kill and open it again it will work as expected

### React Native Version

0.69.0

### Output of `npx react-native info`

System:
    OS: macOS 13.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.49 GB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.16.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 8.11.0 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.12.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 19.0.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Steps to reproduce
Open XCode and Build or run npx react-native run-ios
Wait for build and launch
See the black screen

### Snack, code example, screenshot, or link to a repository

See the bug description

**Comment by cortinico** [comment]
I believe this is a duplicate of #37057
