### ISSUE TITLE
iOS bug: rotated view gets clipped by background image

### ISSUE THREAD

**Issue by a-nico** [facebook/react-native#37078]
### Description

If I rotate a view in the out-of-plane direction (rotateX or rotateY transform) the view goes "behind" the background and gets clipped. Happens only on iOS (works fine on Android). I tried setting the zIndex and the issue persists.

![bug_screenshot](https://user-images.githubusercontent.com/26286173/234161076-ed990d74-3410-4af5-a10b-0c720540517b.jpg)

### React Native Version

0.71.6

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 6.79 GB / 15.83 GB
  Binaries:
    Node: 18.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\node_modules\.bin\yarn.CMD
    npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowAllTrustedApps: Disabled
      Versions: 10.0.17134.0
  IDEs:
    Android Studio: AI-221.6008.13.2211.9619390
    Visual Studio: 15.7.27703.2000 (Visual Studio Community 2017)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.7 => 0.71.7
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Put any View on top of an ImageBackground and transform the view with rotateX or rotateY. See my example code below (works in a Snack).

### Snack, code example, screenshot, or link to a repository

```
import {ImageBackground, StyleSheet, Text, View} from 'react-native';

const image = {uri: 'https://upload.wikimedia.org/wikipedia/commons/5/5a/Sand.jpg'};

const App = () => (
  <View style={styles.container}>
    <ImageBackground source={image} resizeMode="cover" style={styles.image}>
      <Text style={styles.text}>LOL</Text>
    </ImageBackground>
  </View>
);

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  image: {
    flex: 1,
    justifyContent: 'center',
  },
  text: {
    color: 'black',
    fontSize: 100,
    textAlign: 'center',
    transform: [
      { perspective: 300 },
      { rotateX: '30deg'},
    ],
  },
});

export default App;
```

**Comment by AlexanderBich** [comment]
so, did anyone find a solution?

**Comment by AlexanderBich** [comment]
okay, if someone faces this what helped to me is to set: transform: [{ rotateX: '0deg' }] to the wrapper
