### ISSUE TITLE
Open Debugger fails on IOS out of the box.

### ISSUE THREAD

**Issue by dcorbin** [facebook/react-native#37080]
### Description

I create a new project, run the IOS Simulator and Open Debug on the developer menu fails with 
```
Opening flipper://null/Hermesdebuggerrn?device=React%20Native...
error Browser exited with error:, Error: invalid url, missing http/https protocol
``` 
In the metro output

This seems very similar to some other reported bugs, but they are closed so presumably.  Disabling Hermes in the Podfile and rebuilding will avoid the error.

### React Native Version

0.71.7

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 13.3
    CPU: (10) arm64 Apple M1 Max
    Memory: 3.03 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.16.0/bin/yarn
    npm: 9.6.4 - ~/.nvm/versions/node/v16.16.0/bin/npm
    Watchman: 2023.04.03.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK:
      API Levels: 33
      Build Tools: 30.0.3, 33.0.0
      System Images: android-33 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: Flamingo 2022.2.1 Flamingo 2022.2.1
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: javac 20 - /Users/dcorbin/.jenv/shims/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.7 => 0.71.7 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

```
npx react-native init BrokenDebugger
```
In another shell:
```
cd BrokenDebugger && npx react-native start
```
and then back in the original window
```
npx react-native run-ins
```

Once the app starts, open the Developer Menu and select "Open Debugger".

### Snack, code example, screenshot, or link to a repository

It literally happens for me with only standard RN provided code.

**Comment by krisidmisso** [comment]
same error on 0.72.3
