### ISSUE TITLE
Unable to Build for IOS after enabling new architecture, 

### ISSUE THREAD

**Issue by kaushal9808** [facebook/react-native#37102]
### Description

We are using react native 0.71.7 version without enabling new architecture its working fine for both platform android and ios.
But After Enabling New Architecture build failing for Ios, Android Build working fine.
we are getting linking error

Undefined symbols for architecture x86_64:
  "_RCTAppSetupDefaultModuleFromClass", referenced from:
      -[RCTAppDelegate getModuleInstanceFromClass:] in libReact-RCTAppDelegate.a(RCTAppDelegate.o)
  "RCTAppSetupDefaultJsExecutorFactory(RCTBridge*, RCTTurboModuleManager*)", referenced from:
      -[RCTAppDelegate jsExecutorFactoryForBridge:] in libReact-RCTAppDelegate.a(RCTAppDelegate.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

### React Native Version

0.71.7

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 13.3.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 897.02 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 19.9.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 9.6.3 - /usr/local/bin/npm
    Watchman: 2023.04.10.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /Users/XYZ/.rvm/gems/ruby-2.7.6/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9619390
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.18 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Enable New Architecture using RCT_NEW_ARCH_ENABLED=1 && pod install
and build from xcode version 14.3

### Snack, code example, screenshot, or link to a repository

I have tried with arm64 active arch.

**Comment by cortinico** [comment]
cc @cipolleschi

**Comment by cipolleschi** [comment]
Hi @kaushal9808, thanks for the issue. Could you please provide a reproducer?

I tried to create a new app, install the pods and build with Xcode 14.3 as you suggested, but new apps build fine, so I guess there is something specific of your setup... 

What I run:
```
npx react-native init NewArchTest --version 0.71.7 --skip-install
cd NewArchTest
yarn
cd ios
bundle install
RCT_NEW_ARCH_ENABLED=1 bundle exec pod install
open NewArchTest.xcworkspace
```
<kbd>⌘</kbd> + <kbd>r</kbd>

**Comment by kaushal9808** [comment]
we have migrated our app from RN - 0.67.0 version to 0.71.7, Android and IOS version without new architecture working fine,
After Enable the New Architecture Android is also working fine, But we are facing this issues only for iOS. I am working on it if I found more information then will update here, repository is private so currently we can unable to share the same.
we are checking with new init project and migrating our project, if that's work then great. 

Could you please share ruby version with using -> npx react-native info

we can check that if that will create issues or not.

**Comment by cipolleschi** [comment]
I think I got the problem. The error reports that the `RCTAppSetupDefaultModuleFromClass` and `RCTAppSetupDefaultJsExecutorFactory` symbols are not found.

If we look at the [`RCTAppSetupUtils`](https://github.com/facebook/react-native/blob/0.71-stable/React/AppSetup/RCTAppSetupUtils.h#L33-L39) class, this symbols are protected behind a flag `RCT_NEW_ARCH_ENABLED=1`.

What's happening is that the flag is not propagated to the pod, so those symbols are actually excluded from the build. [This code](https://github.com/facebook/react-native/blob/0.71-stable/scripts/cocoapods/new_architecture.rb#L41-L63) should make sure that those flag are set, but there could be a bug there. Or there could be some other pieces of infra that tinkers with the C/CXX flags we are setting up.

To double check that that's the problem, you can: 
1. open the `xcworkspace`, 
2. open the Pods project,
3. select the `React-Core` pod,  // <-- this changed in 0.72
4. select Build Settings
5. filter for `OTHER_CPLUSPLUS_FLAGS`
6. You should see that like this:

<img width="1278" alt="Screenshot 2023-05-04 at 15 01 04" src="https://user-images.githubusercontent.com/11162307/236230707-1d93045c-83d4-44cf-a6b2-c71f27148097.png">

**Comment by douglowder** [comment]
@cipolleschi It is very possible to have two React-Core if you have multiple targets, as we do for the TV repo. In this case, instead of just 'React-Core', we have 'React-Core-iOS' and 'React-Core-tvOS'.

This patch fixed the issue for me. If you agree that this is reasonable, I can open a PR to the core repo.

```patch
diff --git a/node_modules/react-native/scripts/cocoapods/new_architecture.rb b/node_modules/react-native/scripts/cocoapods/new_architecture.rb
index 90141cd..6ef1de9 100644
--- a/node_modules/react-native/scripts/cocoapods/new_architecture.rb
+++ b/node_modules/react-native/scripts/cocoapods/new_architecture.rb
@@ -16,7 +16,7 @@ class NewArchitectureHelper
         language_standard = nil
 
         installer.pods_project.targets.each do |target|
-            if target.name == 'React-Core'
+            if target.name.include? 'React-Core'
                 language_standard = target.resolved_build_setting("CLANG_CXX_LANGUAGE_STANDARD", resolve_against_xcconfig: true).values[0]
             end
         end
@@ -54,7 +54,7 @@ class NewArchitectureHelper
 
         # Add RCT_NEW_ARCH_ENABLED to generated pod target projects
         installer.target_installation_results.pod_target_installation_results.each do |pod_name, target_installation_result|
-            if pod_name == 'React-Core'
+            if pod_name.include? 'React-Core'
                 target_installation_result.native_target.build_configurations.each do |config|
                     config.build_settings['OTHER_CPLUSPLUSFLAGS'] = @@new_arch_cpp_flags
                 end
```
