### ISSUE TITLE
Not able to build IOS

### ISSUE THREAD

**Issue by NitinSinghElegant** [facebook/react-native#37101]
### Description

I am using macbook pro with m2 chip. I setup react-native-firebase in my project. But it is working fine in android
and giving error in macbook.

### React Native Version

0.71.3

### Output of `npx react-native info`

<img width="1440" alt="Screenshot 2023-04-26 at 2 56 33 PM" src="https://user-images.githubusercontent.com/130339696/234540789-3245a03b-d413-41cc-9cdf-6a202967cc1e.png">

### Steps to reproduce

I follow the official documention to setup FCM in ios. after setting everything up I run the command yarn run ios || npx react-native run-ios. It throws this error in xcode.

### Snack, code example, screenshot, or link to a repository

<img width="1440" alt="Screenshot 2023-04-26 at 2 56 33 PM" src="https://user-images.githubusercontent.com/130339696/234541161-84ce0af6-5a0c-491a-b815-defec099830f.png">

**Comment by cortinico** [comment]
> I setup react-native-firebase in my project

Hi @NitinSinghElegant 
Thanks for reporting this issue.

As you mentioned you're having this problem with react-native-firebase, you should open this issue against this other repository:

https://github.com/invertase/react-native-firebase/issues

I'll be closing this but feel free to reopen if the other repo points back to us as a issue in the core of React Native. 

If you're having the same problem on a empty react-native project, please reopen.

**Comment by NitinSinghElegant** [comment]
Thanks @cortinico
