### ISSUE TITLE
[android]Unable to resolve module image!android_search_white when run Examples/Movies?

### ISSUE THREAD

**Issue by yanggeorge** [facebook/react-native#3711]
from #3545  When I put `android_search_white.png` in the same folder as  JS files, and modify the `searchBar.android.js` as below
```javacript
 source={require('./android_search_white.png')}
```
the Movie app is running OK. 
Why  `require('image!android_search_white')` not work ?
I have checked the png files path, they are right in `Examples/Movies/android/app/src/main/res/drawable-hdpi`  .

**Comment by jinhui185190197** [comment]
you can try to create the folder "drawable"

**Comment by yanggeorge** [comment]
@jinhui185190197  I have tried, not work also.

**Comment by wunnath** [comment]
can someone share the sample project for loading a static image on android please.

**Comment by satya164** [comment]
@wunnath http://facebook.github.io/react-native/docs/images.html#content

**Comment by satya164** [comment]
@yanggeorge You need to use `<Image source={{ uri: "android_search_white.png" }} />`
