### ISSUE TITLE
Keyboard events not firing on Android

### ISSUE THREAD

**Issue by avr6ude** [facebook/react-native#37111]
### Description

On Android API 26 and higher keyboard events break if you use any flags for transparent navigation bar. Thus rendering InputField unusable.

### React Native Version

0.71.7

### Output of `npx react-native info`

System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 753.00 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    Yarn: 3.3.0 - /opt/homebrew/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
    Watchman: 2023.01.16.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /Users/avrdude/.rvm/gems/ruby-3.0.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.3/14E222a - /usr/bin/xcodebuild
  Languages:
    Java: javac 17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Add `<InputField>` to any of your components
Wrap it in `<KeyboardAvoidingView>`
Add flags `SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION` and `SYSTEM_UI_FLAG_LAYOUT_STABLE` to `MainActivity.java`
Try clicking on the input field. It will be under the keyboard.

### Snack, code example, screenshot, or link to a repository

```java
public class MainActivity extends ReactActivity {
  @Override
  protected void onCreate(Bundle savedInstanceState) {
    Window w = getWindow();
    w.setStatusBarColor(Color.TRANSPARENT);
    w.setNavigationBarColor(Color.TRANSPARENT);
    w.getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION | View.SYSTEM_UI_FLAG_LAYOUT_STABLE);

    super.onCreate(savedInstanceState);
  }
```
```js
<KeyboardAvoidingView
        keyboardVerticalOffset={headerHeight}
        behavior={commonKeyboardBehavior()}
        >
          <View style={inputWrapper(isKeyboardVisible)}>
           ...
            <View style={..}>
              <TextInput
                ...
              />
            </View>
            ...
          </View>
</KeyboardAvoidingView>
```

**Comment by T-Damer** [comment]
Having this as well, KeyboardAvoidingView is not working properly
