### ISSUE TITLE
How to Disable Display Size/Zoom on Android/iOS

### ISSUE THREAD

**Issue by NomanUmar** [facebook/react-native#37119]
### Description

"react-native": "0.70.6"
"react": "18.1.0",

### React Native Version

0.70.6

### Output of `npx react-native info`

System:
    OS: macOS 13.2.1
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
    Memory: 236.07 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 18.12.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
    Watchman: 2023.01.02.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9477386
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.6 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.6 => 0.70.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

(Android) - Settings > Display > Display Size > Grow or Shrink and see how app adjusts
(iOS) - Settings > Display & Brightness > View > Zoomed - see how app adjusts

### Snack, code example, screenshot, or link to a repository

![Screenshot_1682575863](https://user-images.githubusercontent.com/34022608/234799153-f33f629a-9b85-4726-aa79-8449be011ed6.png)

**Comment by URvesh109** [comment]
@NomanUmar 

use this

```
import DeviceInfo from 'react-native-device-info'
import { moderateScale } from 'react-native-size-matters

const isZoomed = DeviceInfo.isDisplayZoomed()

return moderateScale(size, isZoomed ? 3 : -3)

```

In zoom state the moderateScale function works inverted.
