### ISSUE TITLE
Getting length of the Flatlist

### ISSUE THREAD

**Issue by Hardik3296** [facebook/react-native#37129]
### Description

I have a flatlist and I want to get the total length of the flatlist once it is rendered. I came across the onLayout method which provides the height as event.nativeEvent.layout.height. But it is giving me a constant value irrespective of the number of items in the list. It provides me same value if I have 15 elements or if I have 1 element. I have created a sample here for the same

`<View style={{ flex: 1, backgroundColor: "lightgreen" }}>
  <FlatList
    onLayout={event => {
      console.log(
        "height of list",
        event.nativeEvent.layout.height,
        Dimensions.get("screen").height
      );
    }}
    contentContainerStyle={{ backgroundColor: "red" }}
    data={[12, 35, 45, 78, 89, 56]}
    renderItem={({ item }) => {
      return <Text>{item}</Text>;
    }}
    keyExtractor={item => item}
  />
</View>`

The output of the above console.log is 

> height of list 812 812

I am attaching a screenshot for the visual reference of the same.

As seen in the image the length of flatlist **_(in red)_** is not comparable to the length of the screen **_(in green)_** but the consoled output values looks pretty close to one another.

Any help in this matter will be highly appreciated.

### React Native Version

0.71.7

### Output of `npx react-native info`

**System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 1.18 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.8.1 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.5.1 - /opt/homebrew/bin/npm
    Watchman: 2023.04.03.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.7 => 0.71.7 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

The code to reproduce is pasted above

### Snack, code example, screenshot, or link to a repository
![Simulator Screen Shot - iPhone 11 Pro - 2023-04-28 at 09 21 19](https://user-images.githubusercontent.com/20360325/235050147-c89d4791-52cc-4a99-943f-57157da30327.png)

**Comment by Hardik3296** [comment]
Checked the same thing on latest react native version

**Comment by carlosalmonte04** [comment]
Seems like the FlatList fills the entire container even when it does not have `flex: 1`. How is that possible?
