### ISSUE TITLE
Build fails when try to upgrade to 0.70+ version from 0.62.

### ISSUE THREAD

**Issue by shashi2459** [facebook/react-native#37138]
### New Version

0.71.7

### Old Version

0.62.2

### Build Target(s)

Android API 33

### Output of `react-native info`

System:
    OS: macOS 13.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 55.48 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.17.3 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 6.14.13 - /usr/local/bin/npm
    Watchman: 2021.06.07.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 23, 28, 29, 30, 31, 33
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 33.0.0
      System Images: android-30 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.12 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.7 => 0.71.7 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Issue and Reproduction Steps

1: Task failed with an exception.
-----------
* Where:
Build file '~/mobile-app/android/app/build.gradle' line: 2

A problem occurred evaluating project ':app'.
> **Could not find method aaply() for arguments [{plugon=com.facebook.react}] on project ':app' of type org.gradle.api.Project.**

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':app'.
> **com.android.builder.errors.EvalIssueException: compileSdkVersion is not specified. Please add it to build.gradle**

**Comment by cortinico** [comment]
Not enough information to debug this.
We would need:
1. the full build log
2. your `android/app/build.gradle` file

**Comment by shashi2459** [comment]
Sure @cortinico.

### 1. full build log:

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file '/Users/ssule/Documents/ReactNativeApps/resolve/mobile-app/android/app/build.gradle' line: 2

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not find method aaply() for arguments [{plugon=com.facebook.react}] on project ':app' of type org.gradle.api.Project.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':app'.
> com.android.builder.errors.EvalIssueException: compileSdkVersion is not specified. Please add it to build.gradle

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

### 2. `android/app/build.gradle:`
`
apply plugin: "com.android.application"
aaply plugon: "com.facebook.react"
apply plugin: "com.google.gms.google-services"
// apply from: project(':react-native-config').projectDir.getPath() + "/dotenv.gradle"
import com.android.build.OutputFile

react {
    /* Folders */
    //   The root of your project, i.e. where "package.json" lives. Default is '..'
    // root = file("../")
    //   The folder where the react-native NPM package is. Default is ../node_modules/react-native
    // reactNativeDir = file("../node_modules/react-native")
    //   The folder where the react-native Codegen package is. Default is ../node_modules/react-native-codegen
    // codegenDir = file("../node_modules/react-native-codegen")
    //   The cli.js file which is the React Native CLI entrypoint. Default is ../node_modules/react-native/cli.js
    // cliFile = file("../node_modules/react-native/cli.js")
    /* Variants */
    //   The list of variants to that are debuggable. For those we're going to
    //   skip the bundling of the JS bundle and the assets. By default is just 'debug'.
    //   If you add flavors like lite, prod, etc. you'll have to list your debuggableVariants.
    // debuggableVariants = ["liteDebug", "prodDebug"]
    /* Bundling */
    //   A list containing the node command and its flags. Default is just 'node'.
    // nodeExecutableAndArgs = ["node"]
    //
    //   The command to run when bundling. By default is 'bundle'
    // bundleCommand = "ram-bundle"
    //
    //   The path to the CLI configuration file. Default is empty.
    // bundleConfig = file(../rn-cli.config.js)
    //
    //   The name of the generated asset file containing your JS bundle
    // bundleAssetName = "MyApplication.android.bundle"
    //
    //   The entry file for bundle generation. Default is 'index.android.js' or 'index.js'
    // entryFile = file("../js/MyApplication.android.js")
    //
    //   A list of extra flags to pass to the 'bundle' commands.
    //   See https://github.com/react-native-community/cli/blob/main/docs/commands.md#bundle
    // extraPackagerArgs = []
    /* Hermes Commands */
    //   The hermes compiler command to run. By default it is 'hermesc'
    // hermesCommand = "$rootDir/my-custom-hermesc/bin/hermesc"
    //
    //   The list of flags to pass to the Hermes compiler. By default is "-O", "-output-source-map"
    // hermesFlags = ["-O", "-output-source-map"]
}


/**
 * Set this to true to create two separate APKs instead of one:
 *   - An APK that only works on ARM devices
 *   - An APK that only works on x86 devices
 * The advantage is the size of the APK is reduced by about 4MB.
 * Upload all the APKs to the Play Store and people will download
 * the correct one based on the CPU architecture of their device.
 */
def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = true

/**
 * The preferred build flavor of JavaScriptCore.
 *
 * For example, to use the international variant, you can use:
 * `def jscFlavor = 'org.webkit:android-jsc-intl:+'`
 *
 * The international variant includes ICU i18n library and necessary data
 * allowing to use e.g. `Date.toLocaleString` and `String.localeCompare` that
 * give correct results when using with locales other than en-US.  Note that
 * this variant is about 6MiB larger per architecture than default.
 */
def jscFlavor = 'org.webkit:android-jsc:+'

/**
 * Whether to enable the Hermes VM.
 *
 * This should be set on project.ext.react and mirrored here.  If it is not set
 * on project.ext.react, JavaScript will not be compiled to Hermes Bytecode
 * and the benefits of using Hermes will therefore be sharply reduced.
 */
def enableHermes = project.ext.react.get("enableHermes", false);

android {
    ndkVersion rootProject.ext.ndkVersion
    compileSdkVersion rootProject.ext.compileSdkVersion
    namespace "com.abc.def"

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

     dexOptions {
        javaMaxHeapSize "4g"
    }

    defaultConfig {
        applicationId "com.abc.def"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 10
        versionName "1.6.3"
        multiDexEnabled true
        ndk {
            abiFilters "x86"
            abiFilters 'armeabi-v7a', 'arm64-v8a', 'x86' ,'x86_64'
        }

    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
        }
    }
    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
     release {
         ...
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            // Caution! In production, you need to generate your own keystore file.
            // see https://facebook.github.io/react-native/docs/signed-apk-android.
            signingConfig signingConfigs.release
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // https://developer.android.com/studio/build/configure-apk-splits.html
            def versionCodes = ["armeabi-v7a": 1, "x86": 2, "arm64-v8a": 3, "x86_64": 4]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }

        }
    }
}

dependencies {

    implementation project(':react-native-vector-icons')
    implementation("com.facebook.react:react-android")

    implementation("androidx.swiperefreshlayout:swiperefreshlayout:1.0.0")
    debugImplementation("com.facebook.flipper:flipper:${FLIPPER_VERSION}")
    debugImplementation("com.facebook.flipper:flipper-network-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.squareup.okhttp3', module:'okhttp'
    }

    debugImplementation("com.facebook.flipper:flipper-fresco-plugin:${FLIPPER_VERSION}")
    if (hermesEnabled.toBoolean()) {
        implementation("com.facebook.react:hermes-android")
    } else {
        implementation jscFlavor
    }
}


task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.implementation
    into 'libs'
}

apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)

project.ext.vectoricons = [
    iconFontNames: [ 'MaterialIcons.ttf', 'Ionicons.ttf', 'MaterialCommunityIcons.ttf' ] // Name of the font files you want to copy
]

apply from: "../../node_modules/react-native-vector-icons/fonts.gradle"
`

**Comment by cortinico** [comment]
Can you provide the full build log, from the console input of your build command, till the end (till you see the console again)? What you provided is just the error message.

Also can you provide another file `android/build.gradle` as well?

**Comment by shashi2459** [comment]
Okay. 

### Build log

yarn run v1.22.17
error Could not open cafile: ENOENT: no such file or directory, open '/Users/ssule/Documents/ReactNativeApps/resolve/mobile-app/gd_bundle.crt'
$ react-native run-android
warn Package react-native-vector-icons contains invalid configuration: "dependency.assets" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
warn Multiple Podfiles were found: ios/Podfile,vendor/bundle/ruby/2.6.0/gems/cocoapods-core-1.12.1/lib/cocoapods-core/Podfile. Choosing ios/Podfile automatically. If you would like to select a different one, you can configure it via "project.ios.sourceDir". You can learn more about it here: https://github.com/react-native-community/cli/blob/master/docs/configuration.md
info Starting JS server...
info Installing the app...
5 actionable tasks: 5 up-to-date

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file '/Users/ssule/Documents/ReactNativeApps/resolve/mobile-app/android/app/build.gradle' line: 2

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not find method aaply() for arguments [{plugon=com.facebook.react}] on project ':app' of type org.gradle.api.Project.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':app'.
> com.android.builder.errors.EvalIssueException: compileSdkVersion is not specified. Please add it to build.gradle

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 6s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file '/Users/ssule/Documents/ReactNativeApps/resolve/mobile-app/android/app/build.gradle' line: 2

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not find method aaply() for arguments [{plugon=com.facebook.react}] on project ':app' of type org.gradle.api.Project.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':app'.
> com.android.builder.errors.EvalIssueException: compileSdkVersion is not specified. Please add it to build.gradle

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 6s

    at makeError (/Users/ssule/Documents/ReactNativeApps/resolve/mobile-app/node_modules/execa/index.js:174:9)
    at /Users/ssule/Documents/ReactNativeApps/resolve/mobile-app/node_modules/execa/index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async runOnAllDevices (/Users/ssule/Documents/ReactNativeApps/resolve/mobile-app/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:82:7)
    at async Command.handleAction (/Users/ssule/Documents/ReactNativeApps/resolve/mobile-app/node_modules/@react-native-community/cli/build/index.js:108:9)
info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.


###  android/build.gradle
`// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "33.0.0"
        minSdkVersion = 21
        compileSdkVersion = 33
        targetSdkVersion = 33

        // We use NDK 23 which has both M1 support and is the side-by-side NDK version from AGP.
        ndkVersion = "23.1.7779620"
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:7.3.1")
        classpath("com.google.gms:google-services:4.3.3")
        
        classpath("com.facebook.react:react-native-gradle-plugin")

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

`

**Comment by cortinico** [comment]
Can you share your `package.json` file also?

**Comment by shashi2459** [comment]
Here it is.

{
  "name": "Abc",
  "version": "1.6.3",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "preinstall": "npm install --package-lock-only --ignore-scripts && npx npm-force-resolutions",
    "test": "jest",
    "clean": "cd android && ./gradlew clean",
    "lint": "eslint .",
    "test:watch": "jest --watchAll",
    "set:stage": "gulp set --env=stage",
    "set:stage2": "gulp set --env=stage2",
    "set:prod": "gulp set --env=production",
    "set:uat": "gulp set --env=uat",
    "set:dint": "gulp set --env=dint",
    "set:local-cloud": "gulp set --env=local-cloud",
    "set:local": "gulp set --env=local",
    "sonar": "node sonar-project.js"
  },
  "dependencies": {
    "@pnp-blox/conversation-client": "1.0.0-build.2",
    "@react-native-async-storage/async-storage": "^1.13.2",
    "@react-native-community/art": "^1.2.0",
    "@react-native-community/datetimepicker": "^2.4.0",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-community/netinfo": "^6.2.1",
    "@react-native-community/toolbar-android": "^0.2.1",
    "@react-native-firebase/analytics": "^10.4.0",
    "@react-native-firebase/app": "^10.4.0",
    "@react-native-firebase/messaging": "^10.4.1",
    "@react-navigation/drawer": "^5.8.1",
    "@react-navigation/material-bottom-tabs": "^5.2.9",
    "@react-navigation/material-top-tabs": "^5.2.10",
    "@react-navigation/native": "^5.5.1",
    "@react-navigation/stack": "^5.5.1",
    "axios": "^0.21.0",
    "html-entities": "^2.1.0",
    "jwt-decode": "^3.1.2",
    "moment": "^2.29.1",
    "moment-range": "^4.0.2",
    "prop-types": "^15.7.2",
    "react": "18.2.0",
    "react-dom": "^16.13.1",
    "react-native": "0.71.7",
    "react-native-animatable": "^1.3.3",
    "react-native-base64": "^0.1.0",
    "react-native-calendars": "^1.300.0",
    "react-native-config": "^1.4.1",
    "react-native-device-info": "^7.0.2",
    "react-native-dropdown-picker": "^2.1.8",
    "react-native-elements": "^2.0.0",
    "react-native-error-boundary": "^1.1.6",
    "react-native-file-logger": "^0.4.1",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-image-crop-picker": "^0.32.2",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-keychain": "^6.2.0",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-progress": "^4.1.2",
    "react-native-progress-circle": "^2.1.0",
    "react-native-raw-bottom-sheet": "^2.2.0",
    "react-native-reanimated": "^3.1.0",
    "react-native-restart": "0.0.24",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-screens": "^2.8.0",
    "react-native-snap-carousel": "^3.9.1",
    "react-native-svg": "12.2.0",
    "react-native-swipe-gestures": "^1.0.5",
    "react-native-swipe-list-view": "^3.2.9",
    "react-native-swipe-up-down": "^1.0.7",
    "react-native-switch": "^2.0.0",
    "react-native-tab-view": "^2.14.4",
    "react-native-vector-icons": "^6.6.0",
    "react-redux": "^7.2.0",
    "react-stomp": "^5.0.0",
    "redux": "^4.0.5",
    "redux-logger": "^3.0.6",
    "redux-saga": "^1.1.3",
    "socket.io-client": "^4.1.3",
    "sockjs-client": "^1.4.0",
    "stompjs": "^2.3.3"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native-community/eslint-config": "^3.2.0",
    "@testing-library/react-native": "^7.0.2",
    "@tsconfig/react-native": "^2.0.2",
    "@types/jest": "^29.2.1",
    "@types/react": "^18.0.24",
    "axios-mock-adapter": "^1.19.0",
    "babel-jest": "^29.2.1",
    "enzyme": "^3.11.0",
    "enzyme-adapter-react-16": "^1.15.2",
    "enzyme-to-json": "^3.5.0",
    "eslint": "^8.19.0",
    "gulp": "^4.0.2",
    "gulp-clean": "^0.4.0",
    "gulp-rename": "^2.0.0",
    "jest": "^29.2.1",
    "jest-enzyme": "^7.1.2",
    "jest-serializer-enzyme": "^1.0.0",
    "metro": "^0.59.0",
    "metro-react-native-babel-preset": "0.73.9",
    "prettier": "^2.4.1",
    "react-addons-test-utils": "^15.6.2",
    "react-test-renderer": "18.2.0",
    "redux-mock-store": "^1.5.4",
    "typescript": "4.8.4"
  },
  "jest": {
    "preset": "react-native",
    "snapshotSerializers": [
      "enzyme-to-json/serializer"
    ],
    "setupFiles": [
      "<rootDir>/jest/setup/jest.mock.js"
    ]
  }
}

**Comment by shashi2459** [comment]
Hi @cortinico, the issue is build/update related, so I am not able to build the app. Please let me know if you need more details.

**Comment by cortinico** [comment]
> Please let me know if you need more details.

Yes. Please use this template https://github.com/react-native-community/reproducer-react-native/generate and create a sample app that fails in the same way as yours.
Once you're able to do so, share it here in this issue, and we can look into it.

**Comment by shashi2459** [comment]
Hi, I removed the below lines from app/build.gradle and the app is getting built.

`
def enableHermes = project.ext.react.get("enableHermes", false);

implementation project(':react-native-config')
`

Thanks.

**Comment by cortinico** [comment]
> Hi, I removed the below lines from app/build.gradle and the app is getting built.

Closing as of this
