### ISSUE TITLE
[Android] Modal dialog

### ISSUE THREAD

**Issue by PhilippKrone** [facebook/react-native#3713]
Hello,

when taking a look at the docs, it seems like "Modal" is implemented for Android already (can not find it in the "Known Issues" section + the first line of the help for "modal" is:
````javascript
A Modal component covers the native view (e.g. UIViewController, Activity) that contains the React Native root.
````

However, I can not make it work somehow - is there something special to know compared to the iOS version?

@ide: I remember you saying that one should not use Modal when having a RN app (no hybrid app) but to use Navigator. How do you mean that? The modal dialog has a feature that its transparent and you see the scene below it. With navigator - as far as I was able to understand the code - the disabledScenes are always pushed out of the screen, which means that you can not see them even if you have the main scene transparent.

**Comment by satya164** [comment]
I think Modal is not implemented for Android yet.

**Comment by astreet** [comment]
Yeah, we haven't open sourced this yet, I'll update the docs. Thanks!
