### ISSUE TITLE
[Android] TypeError: expected dynamic type `int64', but has type `double` when lineHeight in styles not integer.

### ISSUE THREAD

**Issue by AlexErofeev** [facebook/react-native#3715]
Possibly have similar reasons to https://github.com/facebook/react-native/issues/3344

When style looks like
```javascript
var styles = StyleSheet.create({
callButtonText: {
		color: 'white',
		fontSize: 18,
		lineHeight: 21.5,
	},
})
```
after running we get red screen with error 
>TypeError: expected dynamic type `int64', but has type `double` 
and exception

After changing lineHeight to 21 everything works well.
Problem exists only on Android

**Comment by astreet** [comment]
We were only accepting ints for this property on Android, I've now updated that. You should see a fix in the next release.

I've also filed a task to improve this error message to make it more clear that this is the framework rejecting the supplied argument.

**Comment by SudoPlz** [comment]
I still get this error on `React Native 26.1`
