### ISSUE TITLE
Android: ToolbarAndroid: Error while updating property logo 

### ISSUE THREAD

**Issue by stevelacy** [facebook/react-native#3716]
react-native: 0.13.2
react-native-cli: 0.1.5

View:
mostly following the example in the docs
```js

import React from 'react-native';

var {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  ToolbarAndroid
} = React;

var View = React.createClass({
  render: function() {
    return (
      <View style={styles.container}>
        <ToolbarAndroid
          logo={require('image!ic_launcher')}
          title="AwesomeApp"
          actions={[
            {
              title: 'Settings', 
              icon: require('image!ic_launcher'), 
              show: 'always'
            }
          ]}
         />
        </View>
    );
  }
});

AppRegistry.registerComponent('View', () => View);


```

both `logo={require('image!ic_launcher')}` and `logo={require('./ic_launcher.png')}` fails with the error
I am unable to create an example on https://rnplay.org/ due to the image asset.
Also, the ToolBar does not show when there isn't any `logo` property. It should always show since android v5+ removes the ActionBar Icon with just the title.

![selection_012](https://cloud.githubusercontent.com/assets/5648999/10759222/625e0630-7c73-11e5-9c57-4f8346deca3e.png)

**Comment by astreet** [comment]
Thanks for the report!

**Comment by stevelacy** [comment]
I noticed that there is support for `uri` here: https://github.com/facebook/react-native/blob/05015e8d360d5275497c40cf14170a5ef4110f43/ReactAndroid/src/main/java/com/facebook/react/views/toolbar/ReactToolbar.java#L159 (though the docs say it should not be used)

So I tested it here: https://rnplay.org/apps/-JgaWA
It generates an empty error

**Comment by leftstick** [comment]
I have the same issue. Seems requiring static resource doesn't work.

**Comment by satya164** [comment]
@stevelacy Is this still an issue?

**Comment by stevelacy** [comment]
using:
- react-native: 0.17.0
- react-native-cli: 0.1.7

Remote resource images work:
![selection_0142015dt](https://cloud.githubusercontent.com/assets/5648999/12024607/9705a38a-ad5a-11e5-888a-3e6c5aaf83dd.png)
```js
logo={{uri: 'http://slacy.me/images/favicon.png'}}
```

Local resources also load perfectly:
```js
logo={require('./ic_launcher.png')}
```

![selection_0152015dt](https://cloud.githubusercontent.com/assets/5648999/12024672/51ffdb38-ad5b-11e5-9f35-c309ab0ef949.png)


Cheers!

**Comment by mikenk2010** [comment]
As stevelacy said "navIcon={{uri: "ic_arrow_back_white_24dp", isStatic: true}}".

Work like a charm !!!
