### ISSUE TITLE
Dashed border on iOS displays extra black solid line on the bottom

### ISSUE THREAD

**Issue by SpertsyanKM** [facebook/react-native#37177]
### Description

I have a view with a dashed border. It is displayed correctly on Android but sometimes it shows unexpected solid black line below the dashed line at the bottom of the view (see the picture).

It works not anywhere. Also if I change the border width it can disappear or appear again for different sizes.

Here is a view style (I use styled-components): 
```
  border-radius: 16px;
  overflow: hidden;
  border: 1px dashed #FF9800;
```

Without `overflow: hidden` the line still exists and takes the whole screen width. No other stiles are assigned.

### React Native Version

0.71.7 (but is also reproducible in 0.70.5)

### Output of `npx react-native info`

System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Pro
    Memory: 99.16 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.1 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.1.2 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.12.0 - /Users/kamospertsyan/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9619390
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.7 => 0.71.7 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Create a view with a described style and add some content in it. The problem is floating - it appears in some positions of a screen with some combination of border width. I wasn't able to calculate the dependency. The problem occurs both on a simulator and a real device.

### Snack, code example, screenshot, or link to a repository

<img width="358" alt="image" src="https://user-images.githubusercontent.com/13959241/235299968-2ebc8c00-8e39-4c44-981e-cb9e072d62c5.png">

**Comment by gorkemunluyurt** [comment]
Did you find the solution to the problem?

**Comment by gorkemunluyurt** [comment]
> Hey, I'm also facing the same issue. Did you find a solution?

No. Did you find it?

**Comment by AmitNewme** [comment]
Still exists
