### ISSUE TITLE
Text is cropped by surrounded View on Android but not on iOS

### ISSUE THREAD

**Issue by aichi** [facebook/react-native#3719]
Check the code here which is and showcase of rounded buttons: https://rnplay.org/apps/yxQaQw or snippet bellow:

```
<View style={styles.container}>
        <View style={styles.box}>
          <TouchableHighlight style={styles.button}>
            <Text style={styles.icon}>WW</Text>
          </TouchableHighlight>
        </View>
            
        <View style={styles.box}>
          <View style={styles.button}>
            <Text style={styles.icon}>WW</Text>
          </View>
        </View>
</View>

```
```
var styles = StyleSheet.create({
  container: {
  },
  box: {
    margin: 50
  },
  icon: {
    fontSize: 68,
    textAlign: 'center',
    color: 'red',
    backgroundColor: 'transparent'
  },
  button: {
    backgroundColor: 'lightblue',
    width: 40,
    height: 40,
    borderRadius: 20,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center'
  },
});
```

You can see that on Android it is rendered in a way that text is clipped by View boundaries, not on iOS. 

This should behave same and I think the Android behavior is better, or we can have both with supporting style overflow:hidden.

**Comment by oblador** [comment]
This is a [known issue](https://facebook.github.io/react-native/docs/known-issues.html#the-overflow-style-property-defaults-to-hidden-and-cannot-be-changed-on-android)

**Comment by aichi** [comment]
I see but I think it should still behave consistently like on e.g. Android.

**Comment by astreet** [comment]
If you have any suggestions on how to communicate this better or make it more consistent, we accept pull requests and doc updates

**Comment by Kishanjvaghela** [comment]
![screenshot from 2017-09-11 15-37-26](https://user-images.githubusercontent.com/11232063/30269641-29a5f216-9707-11e7-9e25-8c534a47b054.png)
Same things happen to me.
