### ISSUE TITLE
Build failed - upgraded Xcode to 14.3 

### ISSUE THREAD

**Issue by woals4815** [facebook/react-native#37193]
### Description

When trying to run an app for iOS on Apple Silicon Mac and Xcode upgraded to 14.3 opening, build process failed.
So, I am temporarily modifying the node_modules/react-native/ReactCommon/yoga/yoga/Yoga.cpp file directly to run the application. 
The modification is within the 
```
node->setLayoutHadOverflow(
node->getLayout().hadOverflow() |
currentRelativeChild->getLayout().hadOverflow());
```
code, where using the OR operator to represent a boolean seems incorrect. 
Therefore, I searched throughout the file and replaced all instances of "|" with "||" for boolean.

When I checked the ReactCommon/yoga/yoga/Yoga.cpp file within the react-native([0.71.7](https://github.com/facebook/react-native/releases/tag/v0.71.7)) packages, I found that there is a problem with the OR operator within the setLayoutHadOverflow() function in one section.

+ I checked release 0.68.7. [c3ad8](https://github.com/facebook/react-native/commit/c3ad8ec7eb01b7236e0081ac7c7f888630caac21) included bool problem. 

### React Native Version

0.66.4

### Output of `npx react-native info`

```
System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 201.22 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.18.1/bin/yarn
    npm: 7.24.2 - ~/treasurer/node_modules/.bin/npm
    Watchman: 2023.04.17.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.9862592
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.19 - /opt/homebrew/opt/openjdk@11/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^18.2.0 => 18.2.0 
    react-native: 0.66.4 => 0.66.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1. deleted all node_modules and Pods, Podfile.lock
2. yarn install && pod install
3. npx react-native run-ios

### Snack, code example, screenshot, or link to a repository

```
023-05-02 20:38:58.848 xcodebuild[1724:2573445] DVTCoreDeviceEnabledState: DVTCoreDeviceEnabledState_Disabled set via user default (DVTEnableCoreDevice=disabled)
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:iOS Simulator, id:E3FB5CF8-5AA7-4236-9367-723C0D0A780E, OS:15.4, name:iPhone 13 }
{ platform:iOS Simulator, id:E3FB5CF8-5AA7-4236-9367-723C0D0A780E, OS:15.4, name:iPhone 13 }
** BUILD FAILED **


The following build commands failed:
        CompileC /Users/woals4815/Library/Developer/Xcode/DerivedData/Treasurer-expaulejrsifxsbnepqmmrqpfvew/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/Yoga.build/Objects-normal/arm64/Yoga.o /Users/woals4815/test-project/packages/app/node_modules/react-native/ReactCommon/yoga/yoga/Yoga.cpp normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'Yoga' from project 'Pods')
(1 failure)
```

**Comment by guttymora** [comment]
Same problem here

**Comment by cortinico** [comment]
> 0.66.4

You're on a old version of RN that most likely won't work with XCode 14. Please update to a later version and report back

**Comment by woals4815** [comment]
@cortinico 
Thanks for comment! 0.7.17 version of RN does work normally in XCode 14.
But i think this part should be fixed. 

```
node->setLayoutHadOverflow(
node->getLayout().hadOverflow() |
currentRelativeChild->getLayout().hadOverflow());
```

**Comment by cortinico** [comment]
> Thanks for comment! 0.7.17 version of RN does work normally in XCode 14.

Closing because of this.

> But i think this part should be fixed.

I'm unsure what are you asking us to fix @woals4815 can you clarify?

**Comment by fusandy** [comment]
I have the same error when running the RN project.

M1 silicon
macOS 13.4
Xcode 14.3.1
RN 0.66.5

I am wondering that only M1 should update to the later RN version to avoid this issue ?
Cuz none of my colleagues who are using Intel silicon face this error while all of us are on the same version of macOS, Xcode and RN....



> > 0.66.4
> 
> You're on a old version of RN that most likely won't work with XCode 14. Please update to a later version and report back

**Comment by sylvainp** [comment]
I've got the same issue

**Comment by yoonzm** [comment]
use xcode 14.1 is work

https://download.developer.apple.com/Developer_Tools/Xcode_14.1/Xcode_14.1.xip

**Comment by sufyansalim** [comment]
> @cortinico Thanks for comment! 0.7.17 version of RN does work normally in XCode 14. But i think this part should be fixed.
> 
> ```
> node->setLayoutHadOverflow(
> node->getLayout().hadOverflow() |
> currentRelativeChild->getLayout().hadOverflow());
> ```

after adding this line i get the following build commands failed: CompileC /Users/myname/projects/projectname/ios/DerivedData/aido/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RCT-Folly.build/Objects-normal/arm64/json.o /Users/myname/projects/projectname/ios/Pods/RCT-Folly/folly/json.cpp normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'RCT-Folly' from project 'Pods') (1 failure)
