### ISSUE TITLE
React Native New Architecture (turbo modules) still use the old Bridge

### ISSUE THREAD

**Issue by KamalSilva007** [facebook/react-native#37218]
### Description

As I'm aware, react native bridge is replaced with the new architecture. But when I'm going to create a new react native turbo module, it still uses the bridge packages. Why is that?

Example RTN Calculator app
import com.facebook.react.bridge.NativeModule;

Ref - https://reactnative.dev/docs/the-new-architecture/pillars-turbomodules#1-folder-setup

### React Native Version

0.70

### Output of `npx react-native info`

-

### Steps to reproduce

-

### Snack, code example, screenshot, or link to a repository

https://reactnative.dev/docs/the-new-architecture/pillars-turbomodules#1-folder-setup

**Comment by cortinico** [comment]
> As I'm aware, react native bridge is replaced with the new architecture. But when I'm going to create a new react native turbo module, it still uses the bridge packages. Why is that?
> Example RTN Calculator app import com.facebook.react.bridge.NativeModule; 
> Ref - [reactnative.dev/docs/the-new-architecture/pillars-turbomodules#1-folder-setup](https://reactnative.dev/docs/the-new-architecture/pillars-turbomodules#1-folder-setup)

Yup that's confusing. Historically, those packages were called `com.facebook.react.bridge.*` and they grew to contain several of our classes, such as `NativeModule` and others.

The fact that you import something from `com.facebook.react.bridge.*` however **does not** mean you'll be using the bridge. Agree that this is confusing though, and we're looking into it. Thanks for spotting it.

**Comment by yousefelgoharyx** [comment]
But we're still returning a promise
Shouldn't the new arch eliminate the need to make everything async?
