### ISSUE TITLE
Require .js file on specific directory

### ISSUE THREAD

**Issue by oscarvgg** [facebook/react-native#3722]
Hi, great job with this framework, I absolutely love it. 

I'm building an iOS app that allows users to download special extensions or plug-ins. The files are downloaded to the `Library/Application Support/` folder inside the app. However, when I try to require the file I'm getting the following error: "Requiring unknown module ..."

![simulator screen shot oct 27 2015 11 08 24 am](https://cloud.githubusercontent.com/assets/1580214/10764783/e4ccb6b0-7ca1-11e5-822e-da72dbd5c3e2.png)

I am sure the module is there and restarting the packager does not help.

Any ideas?

Thanks for your help in advance.

**Comment by ide** [comment]
require is not the same as Node's require. Node reads the modules off of disk, while React Native (and other clientside environments for that matter) first bundle up all the JS into one file that has an implementation of require embedded in it. Basically require never looks at the contents of your app's file system.

You could either read through require.js and see how to dynamically define modules (might be a dead end though) or take an approach of reimplementing a version of require that reads from disk and evaluates the script.
