### ISSUE TITLE
secureTextEntry option is triggering password autofill 

### ISSUE THREAD

**Issue by limsohee1002** [facebook/react-native#37236]
### Description

I set  `textContentType='none'` and  `autoComplete='off'` to the input field, but it still triggers password autofill. I have `secureTextEntry` option on that input field, and it turns out that if I remove `secureTextEntry`, it won't trigger password autofill. 

[React Native doc](https://reactnative.dev/docs/textinput#textcontenttype-ios) said if we set `textContentType='none'` it will disable autofill. However, it doesn't work if we add `secureTextEntry` 🤔

Is there any workaround? I tried using `textContentType='oneTimeCode'` as well, but it didn't fix it.
Please let me know if I am doing something wrong 🙏

### React Native Version

0.71.7

### Output of `npx react-native info`

System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 2.35 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.15.1 - ~/.asdf/installs/nodejs/16.15.1/bin/node
    Yarn: Not Found
    npm: 8.11.0 - ~/.asdf/plugins/nodejs/shims/npm
    Watchman: 2022.09.05.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /Users/soheelim/.asdf/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8815526
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.12 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.7 => 0.71.7 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

- Make input component with `textContentType='none'`,  `autoComplete='off'`, and `secureTextEntry=true`
-> it will trigger password autofill

- Make input component with `textContentType='none'`, and  `autoComplete='off'`
-> it will not trigger password autofill

### Snack, code example, screenshot, or link to a repository

```
<TextInput
  autoCorrect={false}
  autoCapitalize="none"
  onFocus={handleOnFocus}
  onBlur={handleOnBlur}
  secureTextEntry={isInputObscured} // boolean value
  textContentType='none'
  autoComplete='off'
/>
```

**Comment by limsohee1002** [comment]
Updated react native to the latest version and tested it again. Still has the issue 😞

**Comment by nikolal** [comment]
I can confirm that this is happening on `"react-native": "0.73.2"`.

**Comment by gfirmill** [comment]
Still happening to us as well.

**Comment by ChronoByteCosmonaut** [comment]
Yeah same, pretty annoying!!!

**Comment by pvev** [comment]
I found a workaround by using: 

```
keyboardType={isPasswordVisible ? 'visible-password' : 'default'}
secureTextEntry={!isPasswordVisible}
```

with this, you should remove the autofill and even better avoid your password to get saved as a potential suggestion (that was happening when using Swiftkey and you used an special character at the end of the password).

**Comment by UGzeg** [comment]
Has anyone found a solution to this issue? I'm having this issue with React Native 0.73.6.

autoComplete="off"
secureTextEntry=true
textContentType=none

**Comment by amorimcode** [comment]
still hapenning on 0.81.5 version
