### ISSUE TITLE
[Android] ListView onScroll api inconsistency 

### ISSUE THREAD

**Issue by maraujop** [facebook/react-native#3725]
Hi there,

Today I was trying [react-native-refreshable-listview](https://github.com/jsdf/react-native-refreshable-listview) and found it only works in iOS. The reason is that it uses a `ListView` which contains an `onScroll` event attached that in iOS gets fired when pulling to refresh, but in Android doesn't. Would it be possible to make the api work the same way in both platforms?

I've been having a look at the internals of `ListView` and `ScrollView`, and I've seen they end up using Android [ScrollView](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/views/scroll/ReactScrollView.java). This component behaves this way AFAIK, so there is no easy fix.

How about adding `SwipeRefreshLayout` there, to trigger an onRefresh prop only for Android in ListView/ScrollView ? 

Thanks, cheers,
Miguel

**Comment by astreet** [comment]
On Android, pull to refresh is implemented via a separate component (SwipeRefreshLayout, as you mentioned). If you need extra events to support this usecase, we would probably accept a PR :)

**Comment by ide** [comment]
@astreet FYI SwipeRefreshLayout isn't in the OSS repo yet

**Comment by maraujop** [comment]
As this has been added in 0.16.0 I'm closing this issue
