### ISSUE TITLE
No bundle URL present

### ISSUE THREAD

**Issue by VictorPulzz** [facebook/react-native#37261]
### Description

I upgraded macbook m1 to Ventura 13.3.1 and upgraded xcode to 14.3. 
I want to start my project with "react-native": "0.70.6", on simulator with IOS 14.5  and it throws an error like this:
<img width="360" alt="Снимок экрана 2023-05-05 в 02 45 42" src="https://user-images.githubusercontent.com/23406402/236352845-96cfc1bf-d066-4273-9bb0-b9af1e645c7d.png">

However, when I run the latest iOS 16.4 project, it runs without issue. This, oddly enough, because before updating to the new version of xcode, this project ran without problems for me.

### React Native Version

0.70.6

### Output of `npx react-native info`

System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M1
    Memory: 1.33 GB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.16.0/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
    Watchman: 2023.05.01.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /Users/****/.rvm/gems/ruby-2.7.5/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.6 => 0.70.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Install project with "react-native": "0.70.6",
Try to start project with simulator IPhone 11 and IOS 14.5 

### Snack, code example, screenshot, or link to a repository

I can't add link

**Comment by AhteshamKhanCoder** [comment]
Basically you needs to run the npm start

**Comment by VictorPulzz** [comment]
@AhteshamKhanCoder Sry? Npm start autostart when I running npm run ios

**Comment by AhteshamKhanCoder** [comment]
@VictorPulzz still try running this in the separate terminal

**Comment by VictorPulzz** [comment]
I tryed, I found problem, this was happening version ios 14.5. When I launched the project on 15.0 everything started up, it's certainly weird, but I'm already glad that at least it works: D

**Comment by Pouria22** [comment]
Add localhost inside Exception Domains, similar to the picture below:

![Screenshot 2024-02-28 at 3 22 19 PM](https://github.com/facebook/react-native/assets/20810109/ebbc0a97-efa6-4354-9b72-73d6ea8d4902)

**Comment by chucnqicetea** [comment]
> Add localhost inside Exception Domains, similar to the picture below:
> 
> ![Screenshot 2024-02-28 at 3 22 19 PM](https://private-user-images.githubusercontent.com/20810109/308535419-ebbc0a97-efa6-4354-9b72-73d6ea8d4902.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3MDg5MzgsIm5iZiI6MTcxMTcwODYzOCwicGF0aCI6Ii8yMDgxMDEwOS8zMDg1MzU0MTktZWJiYzBhOTctZWZhNi00MzU0LTliNzItNzNkNmVhOGQ0OTAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDEwMzcxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyYjRiZmY2NWMyNTMxMjQ2ZjE2ZDkwMzllZjBlNmJhMzJlMzc1ZDY5YjQxMjA1NzJhYjdhMjY3NGZkMWQwOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EW641aW8nqywKfbefDgPNHXdVyRQZqTDIBx70aQF7lQ)

This worked for me. I'm using xcode 15.1.
