### ISSUE TITLE
App getting crashed when installed in any device but working fine in debug mode

### ISSUE THREAD

**Issue by vaibhav71** [facebook/react-native#37298]
### Description

I am having one app which I am able to run perfectly in the debug mode, but as soon as I am creating apk and trying to install the apk, app is directly getting crash and I am getting error in the android studio.

Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x4 in tid 17862 (.expeditesocial), pid 17862 (.expeditesocial)
=> This is the error which I am getting in android studio when I am opening the app which I installed after creating apk.

Here is the package.json file
"dependencies": {
"@react-native-async-storage/async-storage": "^1.17.12",
"@react-native-community/netinfo": "^9.3.7",
"@react-native-google-signin/google-signin": "^9.0.2",
"@react-navigation/bottom-tabs": "^6.5.7",
"@react-navigation/drawer": "^6.6.2",
"@react-navigation/material-bottom-tabs": "^6.2.15",
"@react-navigation/material-top-tabs": "^6.6.2",
"@react-navigation/native": "^6.1.6",
"@react-navigation/stack": "^6.3.16",
"axios": "^1.3.2",
"moment": "^2.29.4",
"react": "18.2.0",
"react-native": "0.71.4",
"react-native-actions-sheet": "^0.8.29",
"react-native-calendars": "^1.1294.0",
"react-native-date-picker": "^4.2.11",
"react-native-eject": "^0.2.0",
"react-native-element-dropdown": "^2.9.0",
"react-native-gesture-handler": "^2.9.0",
"react-native-image-picker": "^5.3.1",
"react-native-modal": "^13.0.1",
"react-native-pager-view": "^6.2.0",
"react-native-paper": "^5.5.1",
"react-native-reanimated": "^3.0.2",
"react-native-safe-area-context": "^4.5.0",
"react-native-screens": "^3.20.0",
"react-native-scrollable-tab-view": "^1.0.0",
"react-native-svg": "^13.8.0",
"react-native-svg-transformer": "^1.0.0",
"react-native-switch-toggle": "^2.2.1",
"react-native-tab-view": "^3.5.1",
"react-native-toast-message": "^2.1.6",
"react-native-vector-icons": "^9.2.0",
"react-native-video": "^5.2.1",
"react-native-webview": "^11.26.1"
},
"devDependencies": {
"@babel/core": "^7.20.0",
"@babel/preset-env": "^7.20.0",
"@babel/runtime": "^7.20.0",
"@react-native-community/eslint-config": "^3.2.0",
"@tsconfig/react-native": "^2.0.2",
"@types/jest": "^29.2.1",
"@types/react": "^18.0.24",
"@types/react-test-renderer": "^18.0.0",
"babel-jest": "^29.2.1",
"eslint": "^8.19.0",
"jest": "^29.2.1",
"metro-react-native-babel-preset": "0.73.8",
"prettier": "^2.4.1",
"react-test-renderer": "18.2.0",
"typescript": "4.8.4"
},
"jest": {
"preset": "react-native"
}

Really need help
Thanks

### React Native Version

0.71.4

### Output of `npx react-native info`

System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 13th Gen Intel(R) Core(TM) i5-13400F
    Memory: 2.19 GB / 15.84 GB
  Binaries:
    Node: 19.8.1 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: AI-221.6008.13.2211.9619390
    Visual Studio: Not Found
  Languages:
    Java: 1.8.0_362
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.4 => 0.71.4
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

I have created the release apk file and when I am install in any device app is getting crashed

### Snack, code example, screenshot, or link to a repository

![error](https://user-images.githubusercontent.com/27612292/236668812-be554f82-d836-45a4-a5be-0f9fc6214da1.png)

**Comment by vaibhav71** [comment]
> ⚠️	Newer Version of React Native is Available!
> ℹ️	You are on a supported minor version, but it looks like there's a newer patch available. Please [upgrade](https://reactnative.dev/docs/upgrading) to the highest patch for your minor or latest and verify if the issue persists (alternatively, create a new project and repro the issue in it). If it does not repro, please let us know so we can close out this issue. This helps us ensure we are looking at issues that still exist in the most recent releases.

I tried with latest version of react-native but I am still getting error.

{
  "name": "newproject",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "lint": "eslint .",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "^1.17.12",
    "@react-native-community/netinfo": "^9.3.7",
    "@react-native-google-signin/google-signin": "^9.0.2",
    "@react-navigation/bottom-tabs": "^6.5.7",
    "@react-navigation/drawer": "^6.6.2",
    "@react-navigation/material-bottom-tabs": "^6.2.15",
    "@react-navigation/material-top-tabs": "^6.6.2",
    "@react-navigation/native": "^6.1.6",
    "@react-navigation/stack": "^6.3.16",
    "axios": "^1.3.2",
    "moment": "^2.29.4",
    "react": "18.2.0",
    "react-native": "0.71.7",
     "react-native-actions-sheet": "^0.8.29",
    "react-native-calendars": "^1.1294.0",
    "react-native-date-picker": "^4.2.11",
    "react-native-element-dropdown": "^2.9.0",
    "react-native-fbsdk-next": "^11.1.0",
    "react-native-gesture-handler": "^2.9.0",
    "react-native-image-picker": "^5.3.1",
    "react-native-modal": "^13.0.1",
    "react-native-pager-view": "^6.2.0",
    "react-native-paper": "^5.5.1",
    "react-native-reanimated": "^3.0.2",
    "react-native-safe-area-context": "^4.5.0",
    "react-native-screens": "^3.20.0",
    "react-native-scrollable-tab-view": "^1.0.0",
    "react-native-svg": "^13.8.0",
    "react-native-svg-transformer": "^1.0.0",
    "react-native-switch-toggle": "^2.2.1",
    "react-native-tab-view": "^3.5.1",
    "react-native-toast-message": "^2.1.6",
    "react-native-vector-icons": "^9.2.0",
    "react-native-video": "^5.2.1"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native-community/eslint-config": "^3.2.0",
    "@tsconfig/react-native": "^2.0.2",
    "@types/jest": "^29.2.1",
    "@types/react": "^18.0.24",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.2.1",
    "eslint": "^8.19.0",
    "jest": "^29.2.1",
    "metro-react-native-babel-preset": "0.73.9",
    "prettier": "^2.4.1",
    "react-test-renderer": "18.2.0",
    "typescript": "4.8.4"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Comment by cortinico** [comment]
Hi @vaibhav71 
Thanks for reporting this issue.

It seems like this issue is actually unrelated to React Native core but related to Reanimated (from the stacktrace). Please open this issue against this other repository:

https://github.com/software-mansion/react-native-reanimated/issues

I'll be closing this but feel free to reopen if the other repo points back to us as a issue in the core of React Native.
