### ISSUE TITLE
when use aab architecture, after installed, app crash at the first time,but ok on the second time

### ISSUE THREAD

**Issue by LiuLeiThreestone** [facebook/react-native#37294]
### Description

05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681] Runtime aborting...
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681] Dumping all threads without mutator lock held
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681] All threads:
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681] DALVIK THREADS (159):
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681] "mqt_js" prio=5 tid=143 Runnable
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681]   | group="" sCount=0 ucsCount=0 flags=0 obj=0x134955c0 self=0x7bfd16b960
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681]   | sysTid=6033 nice=0 cgrp=system sched=0/0 handle=0x795bc4fcb0
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681]   | state=R schedstat=( 455341475 120430945 582 ) utm=43 stm=2 core=4 HZ=100
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681]   | stack=0x795bb4c000-0x795bb4e000 stackSize=1039KB
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681]   | held mutexes= "abort lock" "mutator lock"(shared held)
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681]   native: #00 pc 00000000006b13a0  /apex/com.android.art/lib64/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, int, BacktraceMap*, char const*, art::ArtMethod*, void*, bool)+128) (BuildId: 12e00d030bcfeb51f978c01791e0cd24)
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681]   native: #01 pc 0000000000719cf0  /apex/com.android.art/lib64/libart.so (art::Thread::DumpStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, bool, BacktraceMap*, bool) const+236) (BuildId: 12e00d030bcfeb51f978c01791e0cd24)
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681]   native: #02 pc 0000000000729248  /apex/com.android.art/lib64/libart.so (art::DumpCheckpoint::Run(art::Thread*)+216) (BuildId: 12e00d030bcfeb51f978c01791e0cd24)
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681]   native: #03 pc 0000000000374f6c  /apex/com.android.art/lib64/libart.so (art::ThreadList::RunCheckpoint(art::Closure*, art::Closure*)+448) (BuildId: 12e00d030bcfeb51f978c01791e0cd24)
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681]   native: #04 pc 0000000000727728  /apex/com.android.art/lib64/libart.so (art::ThreadList::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, bool)+292) (BuildId: 12e00d030bcfeb51f978c01791e0cd24)
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681]   native: #05 pc 00000000006ffa28  /apex/com.android.art/lib64/libart.so (art::AbortState::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const+212) (BuildId: 12e00d030bcfeb51f978c01791e0cd24)
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681]   native: #06 pc 00000000006fa194  /apex/com.android.art/lib64/libart.so (art::Runtime::Abort(char const*)+964) (BuildId: 12e00d030bcfeb51f978c01791e0cd24)
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681]   native: #07 pc 0000000000016ea8  /apex/com.android.art/lib64/libbase.so (android::base::SetAborter(std::__1::function<void (char const*)>&&)::$_3::__invoke(char const*)+80) (BuildId: 420d56eac27a210c92900f3ddb760c86)
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681]   native: #08 pc 0000000000009de0  /system/lib64/liblog.so (__android_log_assert+292) (BuildId: 1f951eeceedbbe038f287e24d36cbd34)
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681]   native: #09 pc 0000000000181f04  /data/app/~~CC--iOXbIlUhPaGAYaOydw==/com.shopee.bke.digitalbank.enterprise-oluQMyZBtk9NYE77RE5GgA==/split_config.arm64_v8a.apk (offset 257c000) (???) (BuildId: 19cf666039ce5d2aeca3909963853ad955e8839d)
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681]   native: #10 pc 00000000001824bc  /data/app/~~CC--iOXbIlUhPaGAYaOydw==/com.shopee.bke.digitalbank.enterprise-oluQMyZBtk9NYE77RE5GgA==/split_config.arm64_v8a.apk (offset 257c000) (???) (BuildId: 19cf666039ce5d2aeca3909963853ad955e8839d)
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681]   native: #11 pc 000000000017e1b8  /data/app/~~CC--iOXbIlUhPaGAYaOydw==/com.shopee.bke.digitalbank.enterprise-oluQMyZBtk9NYE77RE5GgA==/split_config.arm64_v8a.apk (offset 257c000) (???) (BuildId: 19cf666039ce5d2aeca3909963853ad955e8839d)
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681]   native: #12 pc 00000000000bae68  /data/app/~~CC--iOXbIlUhPaGAYaOydw==/com.shopee.bke.digitalbank.enterprise-oluQMyZBtk9NYE77RE5GgA==/split_config.arm64_v8a.apk (offset 257c000) (???) (BuildId: 19cf666039ce5d2aeca3909963853ad955e8839d)
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681]   native: #13 pc 000000000003efac  /data/app/~~CC--iOXbIlUhPaGAYaOydw==/com.shopee.bke.digitalbank.enterprise-oluQMyZBtk9NYE77RE5GgA==/split_config.arm64_v8a.apk (offset 257c000) (???) (BuildId: 19cf666039ce5d2aeca3909963853ad955e8839d)
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681]   native: #14 pc 000000000004d9f0  /data/app/~~CC--iOXbIlUhPaGAYaOydw==/com.shopee.bke.digitalbank.enterprise-oluQMyZBtk9NYE77RE5GgA==/split_config.arm64_v8a.apk (offset 257c000) (???) (BuildId: 19cf666039ce5d2aeca3909963853ad955e8839d)
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681]   native: #15 pc 0000000000050e34  /data/app/~~CC--iOXbIlUhPaGAYaOydw==/com.shopee.bke.digitalbank.enterprise-oluQMyZBtk9NYE77RE5GgA==/split_config.arm64_v8a.apk (offset 257c000) (???) (BuildId: 19cf666039ce5d2aeca3909963853ad955e8839d)
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681]   native: #16 pc 000000000004e93c  /data/app/~~CC--iOXbIlUhPaGAYaOydw==/com.shopee.bke.digitalbank.enterprise-oluQMyZBtk9NYE77RE5GgA==/split_config.arm64_v8a.apk (offset 257c000) (???) (BuildId: 19cf666039ce5d2aeca3909963853ad955e8839d)
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681]   native: #17 pc 000000000003eb0c  /data/app/~~CC--iOXbIlUhPaGAYaOydw==/com.shopee.bke.digitalbank.enterprise-oluQMyZBtk9NYE77RE5GgA==/split_config.arm64_v8a.apk (offset 257c000) (???) (BuildId: 19cf666039ce5d2aeca3909963853ad955e8839d)
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681]   native: #18 pc 000000000004da08  /data/app/~~CC--iOXbIlUhPaGAYaOydw==/com.shopee.bke.digitalbank.enterprise-oluQMyZBtk9NYE77RE5GgA==/split_config.arm64_v8a.apk (offset 257c000) (???) (BuildId: 19cf666039ce5d2aeca3909963853ad955e8839d)
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681]   native: #19 pc 0000000000050e34  /data/app/~~CC--iOXbIlUhPaGAYaOydw==/com.shopee.bke.digitalbank.enterprise-oluQMyZBtk9NYE77RE5GgA==/split_config.arm64_v8a.apk (offset 257c000) (???) (BuildId: 19cf666039ce5d2aeca3909963853ad955e8839d)
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681]   native: #20 pc 000000000004e93c  /data/app/~~CC--iOXbIlUhPaGAYaOydw==/com.shopee.bke.digitalbank.enterprise-oluQMyZBtk9NYE77RE5GgA==/split_config.arm64_v8a.apk (offset 257c000) (???) (BuildId: 19cf666039ce5d2aeca3909963853ad955e8839d)
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681]   native: #21 pc 000000000003eb0c  /data/app/~~CC--iOXbIlUhPaGAYaOydw==/com.shopee.bke.digitalbank.enterprise-oluQMyZBtk9NYE77RE5GgA==/split_config.arm64_v8a.apk (offset 257c000) (???) (BuildId: 19cf666039ce5d2aeca3909963853ad955e8839d)
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681]   native: #22 pc 000000000004da08  /data/app/~~CC--iOXbIlUhPaGAYaOydw==/com.shopee.bke.digitalbank.enterprise-oluQMyZBtk9NYE77RE5GgA==/split_config.arm64_v8a.apk (offset 257c000) (???) (BuildId: 19cf666039ce5d2aeca3909963853ad955e8839d)
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681]   native: #23 pc 0000000000050e34  /data/app/~~CC--iOXbIlUhPaGAYaOydw==/com.shopee.bke.digitalbank.enterprise-oluQMyZBtk9NYE77RE5GgA==/split_config.arm64_v8a.apk (offset 257c000) (???) (BuildId: 19cf666039ce5d2aeca3909963853ad955e8839d)
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681]   native: #24 pc 000000000004e93c  /data/app/~~CC--iOXbIlUhPaGAYaOydw==/com.shopee.bke.digitalbank.enterprise-oluQMyZBtk9NYE77RE5GgA==/split_config.arm64_v8a.apk (offset 257c000) (???) (BuildId: 19cf666039ce5d2aeca3909963853ad955e8839d)
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681]   native: #25 pc 00000000000bfdb0  /data/app/~~CC--iOXbIlUhPaGAYaOydw==/com.shopee.bke.digitalbank.enterprise-oluQMyZBtk9NYE77RE5GgA==/split_config.arm64_v8a.apk (offset 257c000) (???) (BuildId: 19cf666039ce5d2aeca3909963853ad955e8839d)
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681]   native: #26 pc 000000000003efac  /data/app/~~CC--iOXbIlUhPaGAYaOydw==/com.shopee.bke.digitalbank.enterprise-oluQMyZBtk9NYE77RE5GgA==/split_config.arm64_v8a.apk (offset 257c000) (???) (BuildId: 19cf666039ce5d2aeca3909963853ad955e8839d)
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681]   native: #27 pc 000000000004d9f0  /data/app/~~CC--iOXbIlUhPaGAYaOydw==/com.shopee.bke.digitalbank.enterprise-oluQMyZBtk9NYE77RE5GgA==/split_config.arm64_v8a.apk (offset 257c000) (???) (BuildId: 19cf666039ce5d2aeca3909963853ad955e8839d)
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681]   native: #28 pc 0000000000050e34  /data/app/~~CC--iOXbIlUhPaGAYaOydw==/com.shopee.bke.digitalbank.enterprise-oluQMyZBtk9NYE77RE5GgA==/split_config.arm64_v8a.apk (offset 257c000) (???) (BuildId: 19cf666039ce5d2aeca3909963853ad955e8839d)
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681]   native: #29 pc 000000000004e93c  /data/app/~~CC--iOXbIlUhPaGAYaOydw==/com.shopee.bke.digitalbank.enterprise-oluQMyZBtk9NYE77RE5GgA==/split_config.arm64_v8a.apk (offset 257c000) (???) (BuildId: 19cf666039ce5d2aeca3909963853ad955e8839d)
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681]   native: #30 pc 00000000000bfdb0  /data/app/~~CC--iOXbIlUhPaGAYaOydw==/com.shopee.bke.digitalbank.enterprise-oluQMyZBtk9NYE77RE5GgA==/split_config.arm64_v8a.apk (offset 257c000) (???) (BuildId: 19cf666039ce5d2aeca3909963853ad955e8839d)
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681]   native: #31 pc 000000000003efac  /data/app/~~CC--iOXbIlUhPaGAYaOydw==/com.shopee.bke.digitalbank.enterprise-oluQMyZBtk9NYE77RE5GgA==/split_config.arm64_v8a.apk (offset 257c000) (???) (BuildId: 19cf666039ce5d2aeca3909963853ad955e8839d)
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681]   native: #32 pc 000000000004d9f0  /data/app/~~CC--iOXbIlUhPaGAYaOydw==/com.shopee.bke.digitalbank.enterprise-oluQMyZBtk9NYE77RE5GgA==/split_config.arm64_v8a.apk (offset 257c000) (???) (BuildId: 19cf666039ce5d2aeca3909963853ad955e8839d)
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681]   native: #33 pc 0000000000050e34  /data/app/~~CC--iOXbIlUhPaGAYaOydw==/com.shopee.bke.digitalbank.enterprise-oluQMyZBtk9NYE77RE5GgA==/split_config.arm64_v8a.apk (offset 257c000) (???) (BuildId: 19cf666039ce5d2aeca3909963853ad955e8839d)
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681]   native: #34 pc 000000000004e93c  /data/app/~~CC--iOXbIlUhPaGAYaOydw==/com.shopee.bke.digitalbank.enterprise-oluQMyZBtk9NYE77RE5GgA==/split_config.arm64_v8a.apk (offset 257c000) (???) (BuildId: 19cf666039ce5d2aeca3909963853ad955e8839d)
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681]   native: #35 pc 000000000003de28  /data/app/~~CC--iOXbIlUhPaGAYaOydw==/com.shopee.bke.digitalbank.enterprise-oluQMyZBtk9NYE77RE5GgA==/split_config.arm64_v8a.apk (offset 257c000) (???) (BuildId: 19cf666039ce5d2aeca3909963853ad955e8839d)
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681]   native: #36 pc 00000000000bfb60  /data/app/~~CC--iOXbIlUhPaGAYaOydw==/com.shopee.bke.digitalbank.enterprise-oluQMyZBtk9NYE77RE5GgA==/split_config.arm64_v8a.apk (offset 257c000) (???) (BuildId: 19cf666039ce5d2aeca3909963853ad955e8839d)
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681]   native: #37 pc 000000000003efac  /data/app/~~CC--iOXbIlUhPaGAYaOydw==/com.shopee.bke.digitalbank.enterprise-oluQMyZBtk9NYE77RE5GgA==/split_config.arm64_v8a.apk (offset 257c000) (???) (BuildId: 19cf666039ce5d2aeca3909963853ad955e8839d)
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681]   native: #38 pc 000000000004d9f0  /data/app/~~CC--iOXbIlUhPaGAYaOydw==/com.shopee.bke.digitalbank.enterprise-oluQMyZBtk9NYE77RE5GgA==/split_config.arm64_v8a.apk (offset 257c000) (???) (BuildId: 19cf666039ce5d2aeca3909963853ad955e8839d)
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681]   native: #39 pc 0000000000050e34  /data/app/~~CC--iOXbIlUhPaGAYaOydw==/com.shopee.bke.digitalbank.enterprise-oluQMyZBtk9NYE77RE5GgA==/split_config.arm64_v8a.apk (offset 257c000) (???) (BuildId: 19cf666039ce5d2aeca3909963853ad955e8839d)
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681]   native: #40 pc 000000000004e93c  /data/app/~~CC--iOXbIlUhPaGAYaOydw==/com.shopee.bke.digitalbank.enterprise-oluQMyZBtk9NYE77RE5GgA==/split_config.arm64_v8a.apk (offset 257c000) (???) (BuildId: 19cf666039ce5d2aeca3909963853ad955e8839d)
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681]   native: #41 pc 000000000003eb0c  /data/app/~~CC--iOXbIlUhPaGAYaOydw==/com.shopee.bke.digitalbank.enterprise-oluQMyZBtk9NYE77RE5GgA==/split_config.arm64_v8a.apk (offset 257c000) (???) (BuildId: 19cf666039ce5d2aeca3909963853ad955e8839d)
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681]   native: #42 pc 000000000004da08  /data/app/~~CC--iOXbIlUhPaGAYaOydw==/com.shopee.bke.digitalbank.enterprise-oluQMyZBtk9NYE77RE5GgA==/split_config.arm64_v8a.apk (offset 257c000) (???) (BuildId: 19cf666039ce5d2aeca3909963853ad955e8839d)
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681]   native: #43 pc 0000000000050e34  /data/app/~~CC--iOXbIlUhPaGAYaOydw==/com.shopee.bke.digitalbank.enterprise-oluQMyZBtk9NYE77RE5GgA==/split_config.arm64_v8a.apk (offset 257c000) (???) (BuildId: 19cf666039ce5d2aeca3909963853ad955e8839d)
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681]   native: #44 pc 000000000004e93c  /data/app/~~CC--iOXbIlUhPaGAYaOydw==/com.shopee.bke.digitalbank.enterprise-oluQMyZBtk9NYE77RE5GgA==/split_config.arm64_v8a.apk (offset 257c000) (???) (BuildId: 19cf666039ce5d2aeca3909963853ad955e8839d)
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681]   native: #45 pc 000000000003eb0c  /data/app/~~CC--iOXbIlUhPaGAYaOydw==/com.shopee.bke.digitalbank.enterprise-oluQMyZBtk9NYE77RE5GgA==/split_config.arm64_v8a.apk (offset 257c000) (???) (BuildId: 19cf666039ce5d2aeca3909963853ad955e8839d)
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681]   native: #46 pc 000000000002f108  /data/app/~~CC--iOXbIlUhPaGAYaOydw==/com.shopee.bke.digitalbank.enterprise-oluQMyZBtk9NYE77RE5GgA==/split_config.arm64_v8a.apk (offset 257c000) (facebook::hermes::HermesRuntimeImpl::call(facebook::jsi::Function const&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long)+444) (BuildId: 19cf666039ce5d2aeca3909963853ad955e8839d)
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681]   native: #47 pc 0000000000028384  /data/data/com.shopee.bke.digitalbank.enterprise/lib-0/libhermes-executor-release.so (facebook::jsi::Value facebook::jsi::Function::call<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, facebook::jsi::Value>(facebook::jsi::Runtime&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, facebook::jsi::Value&&) const+240) (BuildId: 6930bdd2436403483d3ba9cf78b0cbdd63b3b7ad)
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681]   native: #48 pc 00000000000281e0  /data/data/com.shopee.bke.digitalbank.enterprise/lib-0/libhermes-executor-release.so (???) (BuildId: 6930bdd2436403483d3ba9cf78b0cbdd63b3b7ad)
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681]   native: #49 pc 00000000000226fc  /data/data/com.shopee.bke.digitalbank.enterprise/lib-0/libhermes-executor-release.so (void std::__ndk1::__invoke_void_return_wrapper<void>::__call<void (*&)(std::__ndk1::function<void ()> const&, std::__ndk1::function<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > ()>), std::__ndk1::function<void ()> const&, std::__ndk1::function<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > ()> >(void (*&)(std::__ndk1::function<void ()> const&, std::__ndk1::function<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > ()>), std::__ndk1::function<void ()> const&, std::__ndk1::function<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > ()>&&)+116) (BuildId: 6930bdd2436403483d3ba9cf78b0cbdd63b3b7ad)
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681]   native: #50 pc 000000000002503c  /data/data/com.shopee.bke.digitalbank.enterprise/lib-0/libhermes-executor-release.so (facebook::react::JSIExecutor::callFunction(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, folly::dynamic const&)+1160) (BuildId: 6930bdd2436403483d3ba9cf78b0cbdd63b3b7ad)
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681]   native: #51 pc 00000000000a0778  /data/data/com.shopee.bke.digitalbank.enterprise/lib-0/libreactnativejni.so (???) (BuildId: 238180fbfd276ac9690482b0f0f0d859c1986561)
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681]   native: #52 pc 00000000000a1ba4  /data/data/com.shopee.bke.digitalbank.enterprise/lib-0/libreactnativejni.so (???) (BuildId: 238180fbfd276ac9690482b0f0f0d859c1986561)
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681]   native: #53 pc 0000000000065f98  /data/data/com.shopee.bke.digitalbank.enterprise/lib-0/libreactnativejni.so (???) (BuildId: 238180fbfd276ac9690482b0f0f0d859c1986561)
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681]   native: #54 pc 0000000000055b00  /data/data/com.shopee.bke.digitalbank.enterprise/lib-0/libreactnativejni.so (facebook::jni::detail::MethodWrapper<void (facebook::react::JNativeRunnable::*)(), &(facebook::react::JNativeRunnable::run()), facebook::react::JNativeRunnable, void>::dispatch(facebook::jni::alias_ref<facebook::jni::detail::JTypeFor<facebook::jni::HybridClass<facebook::react::JNativeRunnable, facebook::react::Runnable>::JavaPart, facebook::react::Runnable, void>::_javaobject*>)+32) (BuildId: 238180fbfd276ac9690482b0f0f0d859c1986561)
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681]   native: #55 pc 0000000000055a7c  /data/data/com.shopee.bke.digitalbank.enterprise/lib-0/libreactnativejni.so (facebook::jni::detail::FunctionWrapper<void (*)(facebook::jni::alias_ref<facebook::jni::detail::JTypeFor<facebook::jni::HybridClass<facebook::react::JNativeRunnable, facebook::react::Runnable>::JavaPart, facebook::react::Runnable, void>::_javaobject*>), &(facebook::jni::detail::MethodWrapper<void (facebook::react::JNativeRunnable::*)(), &(facebook::react::JNativeRunnable::run()), facebook::react::JNativeRunnable, void>::dispatch(facebook::jni::alias_ref<facebook::jni::detail::JTypeFor<facebook::jni::HybridClass<facebook::react::JNativeRunnable, facebook::react::Runnable>::JavaPart, facebook::react::Runnable, void>::_javaobject*>)), facebook::jni::detail::JTypeFor<facebook::jni::HybridClass<facebook::react::JNativeRunnable, facebook::react::Runnable>::JavaPart, facebook::react::Runnable, void>::_javaobject*, void>::call(_JNIEnv*, _jobject*)+52) (BuildId: 238180fbfd276ac9690482b0f0f0d859c1986561)
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681]   native: #56 pc 0000000000461554  /apex/com.android.art/lib64/libart.so (art_quick_generic_jni_trampoline+148) (BuildId: 12e00d030bcfeb51f978c01791e0cd24)
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681]   at com.facebook.react.bridge.queue.NativeRunnable.run(Native method)
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681]   at android.os.Handler.handleCallback(Handler.java:942)
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681]   at android.os.Handler.dispatchMessage(Handler.java:99)
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681]   at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(SourceFile:1)
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681]   at android.os.Looper.loopOnce(Looper.java:201)
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681]   at android.os.Looper.loop(Looper.java:288)
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681]   at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(SourceFile:8)
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681]   at java.lang.Thread.run(Thread.java:1012)
05-06 16:14:11.653  5657  6033 F bank.enterprise: runtime.cc:681] 

### React Native Version

0.63.3

### Output of `npx react-native info`

System:
    OS: macOS 11.5.2
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 847.02 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.17.4 - ~/.nvm/versions/node/v14.17.4/bin/node
    Yarn: 1.22.11 - ~/.nvm/versions/node/v14.17.4/bin/yarn
    npm: 6.14.14 - ~/.nvm/versions/node/v14.17.4/bin/npm
    Watchman: 2021.08.30.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-31 | Google Play ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7486908
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_282 - /Users/tranduythien/.sdkman/candidates/java/current/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.2 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1.run bundleDebug to produce ***.aab file
2.change the ***.aab file to ***.apks
3.bundletool install-apks --apks ***.apks
4.start app,and will crash at the first time,but ok on the second time

### Snack, code example, screenshot, or link to a repository

unavailable

**Comment by cortinico** [comment]
Sorry the information you provide is unnecessary to debug this issue.
Please provide a reproducer so we can look into it.

**Comment by cortinico** [comment]
@LiuLeiThreestone Closing as without a reproducer we can't actionate this issue.
