### ISSUE TITLE
[Discussion] Event Loop API

### ISSUE THREAD

**Issue by ide** [facebook/react-native#373]
A small API for working with the event loop would be very helpful when writing native modules that want to interact with the JS context directly. These are "synchronous native modules" that don't go over the batched JSON message queue. This is particularly important when the module deals with resource management -- a more concrete example is a camera component that can capture UIImages and wants to let JS issue commands to resize/crop/filter the image.

In that example, the UIImage is never saved to the camera roll so there is no assets URL that can be used to reference it from JS, and nor do we want to persist the UIImage to a temp directory due to I/O costs, so the UIImage needs to reside in memory. The hard part is knowing when to release the UIImage; either JS needs to explicitly issue some kind of free/release command or we can rely on the JSC garbage collector. I want to experiment with the latter (although there are tradeoffs, such as not being able to use the Chrome debugger if you are using one of these synchronous native modules). The main point is that it could be smart to leverage the garbage collector for resource management.

To enable experiments of this nature I need a way to pump the event loop when directly calling into the JS context since the calls are side-stepping the batched message queue. I believe this API could be really small with two functions:
```objc
// Tell the bridge that we're transitioning from Obj-C to JS. If it needs to set up data
// structures to do bookkeeping to capture calls to native modules or setTimeout
// scheduling, this is where it would do so. In the current implementation of
// React Native, this happens to be a no-op.
[reactBridge willExecuteJavaScript];

/* Execute code using the JSContext */

// Tell the bridge we're done executing JS. This is where calls to native modules
// are executed. In the current implementation, I believe this would call
// -[RCTBridge _handleBuffer:]
[reactBridge didExecuteJavaScript];
```

I believe this would be sufficient to build advanced native modules that don't use the message queue, while being simple enough that it's hopefully not a burden to maintain in the React Native core. Later, if hooks into the event loop were exposed, several tools could be built on top of it as well (http://blog.trevnorris.com/2015/02/asyncwrap-tutorial-introduction.html) but my primary motivation is to enable better resource management with synchronous native modules.

**Comment by sahrens** [comment]
Definitely some interesting ideas here we'll need to think more about.

Another approach to the resource management specifically is to tie it to the component lifecycle - e.g. native could pass an image tag to JS, and JS could tell native that it's done with the tag in componentDidUnmount (which could be handled automatically through a container component).

**Comment by ide** [comment]
Thanks for reading through it. I guess there are two topics at hand -- resource management and the event loop (which could enable synchronous modules which enables using the GC). Resource management actually seems like more of a priority since apps need to be able to work with images, etc. while some of the more advanced event loop features enable higher-order infra. It'd be great if a small event loop API could help solve some resource management issues though.

One real-world scenario dealing with resource management that doesn't quite fit a component life cycle is an image uploader, where you want to upload an image taken by the camera that hasn't been saved to the camera roll. Since the network could be flaky and require retry logic or the upload could just be slow, you might want the upload task to outlive the lifetime of the camera component. And the NSData or UIImage being uploaded should live for as long as there's a reference to it (components may reference it, as may the uploader module).

The uploader could tell the native code to decrement a reference count when the image has been uploaded (or if the upload failed and the uploader decides not to retry). I believe this would achieve the correct behavior and can work over the batched message queue. This is essentially pre-ARC Manual Retain Release though and in this case leaks could lead to OOM since we're working with images and other heavier resources. It should be possible to let the GC take care of this so I'd like to see experiments in that direction so we can understand the tradeoffs.

**Comment by facebook-github-bot-3** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by ide** [comment]
Still relevant for scheduling!

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/discussion-event-loop-api

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.
