### ISSUE TITLE
cocoapods parallel_pod_download shows failure with DoubleConversion and libevents but completes

### ISSUE THREAD

**Issue by FrederickEngelhardt** [facebook/react-native#37318]
### Description

When applying concurrent downloading to cocoapods both libevent and DoubleConversion will fail initially and then install later. Concurrent downloading is supported in cocoapods `=>1.12.0`.

**Noting that this is a reported failure but it seems like things work still as both libevent and DoubleConversion are installed after boost is extracted.** The project will build using these parallel scripts with all caches removed.

To apply concurrent downloading with cocoapods the following must be done:
1. Install cocoapods >= 1.12.0
2. For RN >=0.71 override the cocoapods ruby script method **prepare_react_native_project**  inside of `node_modules/react-native/scripts/react_native_pods.rb`, or remove it from the Podfile and replace with a similar script.

```diff
 def prepare_react_native_project!
     # Temporary solution to suppress duplicated GUID error.
     # Can be removed once we move to generate files outside pod install.
-    install! 'cocoapods', :deterministic_uuids => false
+    install! 'cocoapods', :parallel_pod_downloads => true,
+    :parallel_pod_download_thread_pool_size => 40, :deterministic_uuids => false

     ReactNativePodsUtils.create_xcode_env_if_missing
   end
```
3. The pod cache must be cleaned `cd ios; pod cache clean --all`. Otherwise the next install will use the cache and not have the error.

When applying these changes and getting concurrent downloading. The following error shows up.

```
[!] Error installing libevent

[!] Error installing DoubleConversion
```

Full output
```
Downloading DoubleConversion (1.1.6)
Downloading FBLazyVector (0.71.7)
Downloading FBReactNativeSpec (0.71.7)
Downloading RCT-Folly (2021.07.22.00)
Downloading RCTRequired (0.71.7)
Downloading RCTTypeSafety (0.71.7)
Downloading React (0.71.7)
Downloading React-Codegen (0.71.7)
Downloading React-Core (0.71.7)
Downloading React-CoreModules (0.71.7)
Downloading React-RCTActionSheet (0.71.7)
Downloading React-RCTAnimation (0.71.7)
Downloading React-RCTAppDelegate (0.71.7)
Downloading React-RCTBlob (0.71.7)
Downloading React-RCTImage (0.71.7)
Downloading React-RCTLinking (0.71.7)
Downloading React-RCTNetwork (0.71.7)
Downloading React-RCTSettings (0.71.7)
Downloading React-RCTText (0.71.7)
Downloading React-RCTVibration (0.71.7)
Downloading React-callinvoker (0.71.7)
Downloading React-cxxreact (0.71.7)
Downloading React-hermes (0.71.7)
Downloading React-jsi (0.71.7)
Downloading React-jsiexecutor (0.71.7)
Downloading React-jsinspector (0.71.7)
Downloading React-logger (0.71.7)
Downloading React-perflogger (0.71.7)
Downloading React-runtimeexecutor (0.71.7)
Downloading ReactCommon (0.71.7)
Downloading Yoga (1.14.0)
Downloading boost (1.76.0)
Downloading fmt (6.2.1)
Downloading glog (0.3.5)
Downloading hermes-engine (0.71.7)
Downloading libevent (2.1.12)

[!] Error installing libevent

[!] Error installing DoubleConversion
Installing DoubleConversion (1.1.6)
Installing FBLazyVector (0.71.7)
Installing FBReactNativeSpec (0.71.7)
Installing RCT-Folly (2021.07.22.00)
Installing RCTRequired (0.71.7)
Installing RCTTypeSafety (0.71.7)
Installing React (0.71.7)
Installing React-Codegen (0.71.7)
Installing React-Core (0.71.7)
Installing React-CoreModules (0.71.7)
Installing React-RCTActionSheet (0.71.7)
Installing React-RCTAnimation (0.71.7)
Installing React-RCTAppDelegate (0.71.7)
Installing React-RCTBlob (0.71.7)
Installing React-RCTImage (0.71.7)
Installing React-RCTLinking (0.71.7)
Installing React-RCTNetwork (0.71.7)
Installing React-RCTSettings (0.71.7)
Installing React-RCTText (0.71.7)
Installing React-RCTVibration (0.71.7)
Installing React-callinvoker (0.71.7)
Installing React-cxxreact (0.71.7)
Installing React-hermes (0.71.7)
Installing React-jsi (0.71.7)
Installing React-jsiexecutor (0.71.7)
Installing React-jsinspector (0.71.7)
Installing React-logger (0.71.7)
Installing React-perflogger (0.71.7)
Installing React-runtimeexecutor (0.71.7)
Installing ReactCommon (0.71.7)
Installing Yoga (1.14.0)
Installing boost (1.76.0)
Installing fmt (6.2.1)
Installing glog (0.3.5)
Installing hermes-engine (0.71.7)
Installing libevent (2.1.12)
Generating Pods project
Setting REACT_NATIVE build settings
Setting CLANG_CXX_LANGUAGE_STANDARD to c++17 on /Users/XYZ/path/to/repo/rRN71Project/ios/RN71Project.xcodeproj
Pod install took 98 [s] to run
Integrating client project
Pod installation complete! There are 36 dependencies from the Podfile and 36 total pods installed.
```

~These errors seem to be related to dependencies specified within Folly's podspec file.~
Edit: Commenting out these dependencies still allows for a build and still throws an error for both DoubleConversion and libevent when pod switches over from download to install

```
  ...
  spec.dependency 'boost'
  spec.dependency 'DoubleConversion'
  spec.dependency 'glog'
  ...
...
  spec.subspec 'Futures' do |futures|
    futures.dependency 'libevent'
```

### React Native Version

0.71.7

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 13.3.1
    CPU: (12) arm64 Apple M2 Pro
    Memory: 477.06 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.20.0 - ~/Library/Caches/fnm_multishells/10299_1682566412504/bin/node
    Yarn: 1.22.19 - ~/Library/Caches/fnm_multishells/10299_1682566412504/bin/yarn
    npm: 8.19.4 - ~/Library/Caches/fnm_multishells/10299_1682566412504/bin/npm
    Watchman: 2023.04.24.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /Users/xyz/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.9971841
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.7 => 0.71.7
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. npx react-native init RN71Project --version 0.71.7
2. Replace any `install cocopod` references with parallel syntax
```diff
 def prepare_react_native_project!
     # Temporary solution to suppress duplicated GUID error.
     # Can be removed once we move to generate files outside pod install.
-    install! 'cocoapods', :deterministic_uuids => false
+    install! 'cocoapods', :parallel_pod_downloads => true,
+    :parallel_pod_download_thread_pool_size => 40, :deterministic_uuids => false

     ReactNativePodsUtils.create_xcode_env_if_missing
   end
```
3. Clean the pod cache and delete pods. SO article [link](https://stackoverflow.com/questions/16427421/how-to-remove-cocoapods-from-a-project) 
4. To install `gem install cocoapods-deintegrate cocoapods-clean`
5. Clean script `cd ios; pod deintegrate; pod cache clean --all`
6. `cd ios; pod install`

Noting that boost takes a while to extract so you can replace the tar extract with something multithreaded such as [pbzip2](https://github.com/ruanhuabin/pbzip2). `brew install pbzip2`. Should speedup extraction by 5-10x.

## Benchmarks:
-M2 Pro Macbook Pro takes about 114s to run the full cache clean install
- i7 (2019 macbook pro) it would be 15-30minutes to extract all the files.

```shell
tar(){  
  if [ $(command -v ) ]; then
    command pbzip2 -dkv file.tbz | tar $1 $2.out $3 $4 ${5:@}
    else
    command tar $@
  fi
}
```

Notice that both libevents and DoubleConversion fail to install initially then install later.

### Snack, code example, screenshot, or link to a repository

https://github.com/FrederickEngelhardt/rn71-pod-dl-concurrency

Please reference this section:
https://github.com/FrederickEngelhardt/rn71-pod-dl-concurrency/blob/main/ios/Podfile#L8C7-L9

**Comment by cipolleschi** [comment]
Hi @FrederickEngelhardt, thanks for the report. 
Am I understanding correctly that these are just false errors, meaning that they fire but, at the end of the process, everything works well?

What do you mean with:

> These errors seem to be related to dependencies specified within Folly's podspec file.
>```ruby
>  # ...
>  spec.dependency 'boost'
>  spec.dependency 'DoubleConversion'
>  spec.dependency 'glog'
>  # ...
># ...
>  spec.subspec 'Futures' do |futures|
>    futures.dependency 'libevent'
>```

Have you tried removing/rearranging these dependencies to see if something changes?

**Comment by FrederickEngelhardt** [comment]
I have tried that, seems to do nothing. It's probably not related to that file. I even commented out both of those dependencies and it still builds fine.

Also did not submit an error to cocoapods due to this being react-native related and they specifically saying it needs to be submitted to react-native issues. Might need to still CC: this problem to them to see if there's something missing in documentation related to subspecs and podspecs.

**Comment by cipolleschi** [comment]
Yes, this is probably something we need to investigate. I hope to find some time in the next weeks.
