### ISSUE TITLE
[Asset System] Does not support gifs

### ISSUE THREAD

**Issue by brentvatne** [facebook/react-native#3731]
The new asset system described here: https://github.com/facebook/react-native/pull/3545 does not currently support gifs - it throws an unable to resolve module error when I try.

cc @frantic

**Comment by frantic** [comment]
@brentvatne can you try and add `gif` [here](https://github.com/facebook/react-native/blob/master/packager/react-packager/src/Bundler/index.js#L67) and tell me if it works? @martinbigio would be nice to have `gif` and `jpg`/`jpeg` there by default.

**Comment by brentvatne** [comment]
@frantic - same error with gif there

**Comment by frantic** [comment]
Strange. @amasad, @martinbigio are there any other configs?

**Comment by martinbigio** [comment]
Hmm the values are coming from `local-cli/server/runServer.js` which doesn't include `gif`. Do you mind changing the array for this? ` ['png', 'jpg', 'jpeg', 'bmp', 'gif', 'webp'],`. If it works could you submit a pull request? :)

**Comment by brentvatne** [comment]
@martinbigio - tested that, it worked, updated!

**Comment by martinbigio** [comment]
Awesome, thanks a lot for submitting the pull request!

**Comment by jacobbubu** [comment]
@martinbigio, I'm just curious that does RN support webp image?
