### ISSUE TITLE
Text color not working in tablet android

### ISSUE THREAD

**Issue by carlosfelipepg** [facebook/react-native#37313]
### Description

Running a new project on a tablet, it's not possible to change the colors.
**Tablet specifications**
Android 11
Model: T810 Positivo

When I try to change the color of some text, it doesn't work.

### React Native Version

0.71.7

### Output of `npx react-native info`

System:
    OS: Linux 5.19 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (4) x64 Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz
    Memory: 4.50 GB / 15.51 GB
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - /snap/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.7 => 0.71.7 
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

- npx react-native init teste_tablet   
- npx react-native run-android
- npm start
- change color text 

### Snack, code example, screenshot, or link to a repository

![Captura de tela de 2023-05-08 16-32-07](https://user-images.githubusercontent.com/17533966/236915928-8471e59a-7e0b-43cf-b3e2-b0a66eaae695.png)
![Captura de tela de 2023-05-08 16-32-14](https://user-images.githubusercontent.com/17533966/236915933-599c3807-1efd-48ce-b705-c82bd0ff37f0.png)
![Captura de tela de 2023-05-08 16-32-16](https://user-images.githubusercontent.com/17533966/236915935-0471e513-d3c9-4730-ab9c-acf7c60cf9f0.png)
![Screenshot_20230508-163428](https://user-images.githubusercontent.com/17533966/236916468-989595ef-5848-4bca-af22-4a0ba7887525.png)

**Comment by cortinico** [comment]
> Running a new project on a tablet, it's not possible to change the colors.

* Have you tried on a emulator?
* Also have you tried on a phone?

**Comment by carlosfelipepg** [comment]
> > Executando um novo projeto em um tablet, não é possível alterar as cores.
> 
> * Já tentou em um emulador?
> * Você também já tentou em um telefone?

Yes, emulators, real devices, and iPhone. I also tested it on other devices from the same brand (tablet and phone).
The only one that had an issue was this tablet.
I took devices with the same Android version and resolution, and it works correctly.

**Comment by fabriziobertoglio1987** [comment]
Do you still experience this issue? 

I have four years of experience maintaining facebook/react-native and I specialize in the Text and TextInput components. I currently have 58 [facebook/react-native PRs](https://github.com/facebook/react-native/pulls?q=is%3Apr+author%3Afabriziobertoglio1987+). 

If you still experience this issue, I will prepare a patched release with the fix.

Thanks a lot

**Comment by TQCasey** [comment]
@fabOnReact  yes , still experience this issue (0.72.10),event 0.78 still experience this issue on my PDA (android 12 device)
<Text> change the color not work at all .
The Text color is affected by styles.xml (<item name="android:textColor">#ffffff</item>)
