### ISSUE TITLE
Text Rendering on Top of Status Bar on IOS

### ISSUE THREAD

**Issue by cancan101** [facebook/react-native#3732]
my render method:
```js
        return (
             <View>
                 <Text>Hello World!. Why am I here?</Text>
             </View>
        );
```
I am running in an emulator I see the text on top of the status bar. Is this an emulator issue or something else?:
![image](https://cloud.githubusercontent.com/assets/51059/10775039/c854021a-7cdb-11e5-810d-16a0de5740da.png)

**Comment by ide** [comment]
This is how all iOS apps work. You're in charge of positioning your text.

**Comment by cancan101** [comment]
@ide and text is relative to the top of the screen rather than the bottom of the status bar? i.e. it's actually possible to render on top of the status bar?

**Comment by ide** [comment]
Yes, that's an Apple thing (and Android too with the right config).

**Comment by cancan101** [comment]
@ide Is this related: http://stackoverflow.com/a/18785646/2638485 ?

**Comment by ide** [comment]
Yes but React Native doesn't use view controllers really.

**Comment by cancan101** [comment]
This actually seemed to work: http://stackoverflow.com/questions/18886195/ios-7-status-bar-overlapping-ui/18886468#18886468

**Comment by cancan101** [comment]
@ide Do you think it makes to wrap up the functionality of doing positioning relative to the bottom of the status bar? It seems less than ideal to have to hardcode a padding value.

It looks like there is [some chatter](https://botbot.me/freenode/reactnative/search/?q=edgesForExtendedLayout) on the view controller setting

**Comment by ide** [comment]
No, because you want to be able to place content (e.g. a navigation bar) relative to the top of the screen. You can write some Obj-C/Java to get the height of the native status bar if you need to, or hardcode it.

**Comment by cancan101** [comment]
@ide Hard  coding seems like a bad idea. In fact there is [even a project](https://github.com/brentvatne/react-native-status-bar-size) to help get the status bar size.

**Comment by benirose** [comment]
This is a helpful resource on the topic from Apple: https://developer.apple.com/ios/human-interface-guidelines/ui-bars/status-bars/

I wanted to share since I had the same disbelief until I read it.

**Comment by mikeaustin** [comment]
That's great how iOS works, but I'm curious what is a cross-platform solution?

**Comment by VarshaJadhav** [comment]
Alternate solution will be
`import {Platform} from 'react-native';`
`let platform = Platform.OS;`

`<View style={platform}>
<Text>Hello</Text>
<View>`
