### ISSUE TITLE
Problem to build a blank project in IOS

### ISSUE THREAD

**Issue by odevnicolas** [facebook/react-native#37325]
### Description

I just created a blank project, and the first time I tried to run it through x-code it returns this print problem

### React Native Version

0.70.0

### Output of `npx react-native info`

System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M2
    Memory: 144.05 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.15.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.5.0 - /usr/local/bin/npm
    Watchman: 2023.05.08.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /Users/nicolassousa/.rvm/rubies/ruby-2.7.5/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.0 => 0.70.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

npc react-native init "projectName'

### Snack, code example, screenshot, or link to a repository

<img width="244" alt="Screenshot 2023-05-08 at 20 06 19" src="https://user-images.githubusercontent.com/125375345/236962737-d5e1d93a-b376-422c-a287-8f7f4532bfb2.png">
<img width="694" alt="Screenshot 2023-05-08 at 21 11 53" src="https://user-images.githubusercontent.com/125375345/236962821-1414442d-db1f-44da-9756-c22916d8aacc.png">

**Comment by cipolleschi** [comment]
Thank you for opening the issue.

We solved this in the latest release patches of 0.70, specifically in 0.70.8.
The latest patch version for 0.70 is 0.70.9.

Please upgrade to that version and it would work!
