### ISSUE TITLE
WebSocket error

### ISSUE THREAD

**Issue by shiwuqi** [facebook/react-native#37331]
### Description

react-native 0.71.7
react 18.2.0

### React Native Version

0.71.7

### Output of `npx react-native info`

{"isTrusted":false,"message":"Failed to connect to /127.0.0.1:3000"}

### Steps to reproduce

yarn android

### Snack, code example, screenshot, or link to a repository

`const socket = new WebSocket('http://127.0.0.1:3000');
    socket.addEventListener('error', (err: any) => {
      console.log('============', err);
    })`

**Comment by Deepak-1D** [comment]
HI @shiwuqi may I know how did you solve the above error
