### ISSUE TITLE
E/SoLoader: couldn't find DSO to load: libjscexecutor.so

### ISSUE THREAD

**Issue by emel95** [facebook/react-native#37336]
### Description

hello 
When I run the project, the app crashes and Android logcat gives this error
 "react-native": "0.71.2",
 "react": "18.2.0",
Help me please 

### React Native Version

0.71.2

### Output of `npx react-native info`

System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 68.70 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
    Watchman: 2023.01.16.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/emelmousavi/.rvm/gems/ruby-2.7.6/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 23, 28, 29, 31, 32, 33
      Build Tools: 30.0.2, 30.0.3, 31.0.0, 33.0.0
      System Images: android-30 | Google APIs ARM 64 v8a, android-30 | Google Play ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

....

### Snack, code example, screenshot, or link to a repository

...

**Comment by shubhamdeol** [comment]
same here. We are getting this only nexus 5 devices android 8.0.1

**Comment by cortinico** [comment]
@emel95 can you provide a reproducer and update to the latest patch as suggested by the bot, and report back?

**Comment by emel95** [comment]
android/build.gradle ==>

buildscript {
    ext {
        buildToolsVersion = "33.0.0"
        minSdkVersion = 21
        compileSdkVersion = 33
        targetSdkVersion = 33
        // We use NDK 23 which has both M1 support and is the side-by-side NDK version from AGP.
        ndkVersion = "23.1.7779620"
        kotlinVersion = "1.6.10"
    }
    repositories {
        mavenLocal()
        mavenCentral()

        google()
    }
    dependencies {
         
        classpath("com.facebook.react:react-native-gradle-plugin")
        classpath("com.android.tools.build:gradle:7.3.1")

        classpath 'com.google.gms:google-services:4.3.14'
        classpath 'com.google.firebase:perf-plugin:1.4.1'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.6.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
    }
}


allprojects {
    buildscript { 
        repositories {
            mavenLocal() 
            mavenCentral()
        }
    }
    repositories {

        mavenLocal()
        mavenCentral()
        
        google()

        maven {url "https://www.jitpack.io"}
        maven {url "https://mobilesdk.useinsider.com/android"}
        maven {
            url "https://sdk.mydigipay.info/artifactory/android-payment-module"
            credentials {
                username = "digikala"
                password = "qK4LvJPZsba9PN4U"
            }
        }
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../../node_modules/jsc-android/dist")
        }

         configurations.all {
            resolutionStrategy {

                // use 0.9.0 to fix crash on Android 11
                force "com.facebook.soloader:soloader:0.9.0"
			}
		}
        
    }
  project.pluginManager.withPlugin("com.facebook.react") {
        react {
            reactNativeDir = rootProject.file("../../node_modules/react-native/")
            codegenDir = rootProject.file("../../node_modules/react-native-codegen/")
        }
    }
}

android/app/build.gradle

project.ext.react = [
    enableHermes: true,  // clean and rebuild if changing
     deleteDebugFilesForVariant: { false },
    enableVmCleanup: false,
    entryFile: "client/index.tsx",
    root: "$rootDir/../",
    cliPath: "$rootDir/../../node_modules/react-native/cli.js",
    bundleCommand: "webpack-bundle",
]

dependencies {

      if (hermesEnabled.toBoolean()) {
        implementation("com.facebook.react:hermes-android")
    } else {
        implementation jscFlavor
    }

    // if (useIntlJsc) {
    //  implementation 'org.webkit:android-jsc-intl:+'
    //  } else {
    // implementation 'org.webkit:android-jsc:+'
    // }
    // The version of react-native is set by the React Native Gradle Plugin
    implementation("com.facebook.react:react-android")

    implementation "com.android.installreferrer:installreferrer:1.1"

    debugImplementation("com.facebook.flipper:flipper:${FLIPPER_VERSION}")
    debugImplementation("com.facebook.flipper:flipper-network-plugin:${FLIPPER_VERSION}") {
        exclude group:"com.squareup.okhttp3", module:"okhttp"
    }

    debugImplementation("com.facebook.flipper:flipper-fresco-plugin:${FLIPPER_VERSION}")
    if (hermesEnabled.toBoolean()) {
        implementation("com.facebook.react:hermes-android")
    } else {
        implementation jscFlavor
    }

    // Animated Gif Images
    implementation "com.facebook.fresco:animated-gif:2.0.0"

    // Google Maps
    implementation "com.google.android.gms:play-services-maps:17.0.0"
    implementation "com.google.maps.android:android-maps-utils:0.5"

    // Android X
    implementation "androidx.appcompat:appcompat:1.1.0"
    implementation "androidx.coordinatorlayout:coordinatorlayout:1.1.0"
    implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.1.0-alpha03"
    implementation "androidx.multidex:multidex:2.0.1"
    implementation "org.apache.commons:commons-imaging:1.0-alpha3"

    // Import the BoM for the Firebase platform
    // ⚠️ When using the BoM, you don"t specify versions in Firebase library dependencies
    implementation platform("com.google.firebase:firebase-bom:31.1.1")

    // Declare the dependency for the Firebase Crashlytics NDK library.
    // If you previously declared the Firebase Crashlytics dependency, replace it.
    //  implementation "com.google.firebase:firebase-crashlytics-ndk"
    implementation 'com.google.firebase:firebase-crashlytics:17.2.2'
    implementation 'com.facebook.soloader:soloader:0.9.0+'

    implementation("androidx.swiperefreshlayout:swiperefreshlayout:1.0.0")

    debugImplementation("com.facebook.flipper:flipper:${FLIPPER_VERSION}")
    debugImplementation("com.facebook.flipper:flipper-network-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.squareup.okhttp3', module:'okhttp'
    }
    // firebase messaging need for metrix uninstall measurement
    implementation "com.google.firebase:firebase-messaging"

    implementation("androidx.work:work-runtime:2.7.1") {
        force = true
    }

    def work_version = "2.7.1"
    // Force WorkManager 2.7.1 for transitive dependency
    implementation("androidx.work:work-runtime-ktx:$work_version") {
        force = true
    }
}

**Comment by cortinico** [comment]
> If your bug is build/update related: use our [Reproducer Template](https://github.com/react-native-community/reproducer-react-native/generate)

Please use this reproducer template @emel95

**Comment by yberstad** [comment]
This fixed it for me, https://github.com/facebook/react-native/issues/35693#issuecomment-1362700965
