### ISSUE TITLE
TypeError: Cannot read property 'start' of null, js engine hermes

### ISSUE THREAD

**Issue by i-am-developer-maybe** [facebook/react-native#37341]
### Description

Hi Team!

 I get BUILD SUCCESSFUL when i run npx react-native run-android. But   there is an error 'TypeError: Cannot read property 'start' of null, js engine hermes' in the Android emulator. I get the same error with react native  v0.70.9.

### React Native Version

0.70.7

### Output of `npx react-native info`

System:
    OS: macOS 13.3.1
    CPU: (4) x64 Intel(R) Core(TM) i3-8100B CPU @ 3.60GHz
    Memory: 982.02 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 14.21.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.13.2 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK:
      API Levels: 28, 29, 30, 31, 32, 33
      Build Tools: 28.0.3, 29.0.0, 29.0.1, 29.0.2, 29.0.3, 30.0.0, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0, 33.0.0
      System Images: android-29 | Google APIs ARM 64 v8a, android-29 | Google Play ARM 64 v8a, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs ARM 64 v8a, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play ARM 64 v8a, android-30 | Google Play Intel x86 Atom, android-31 | ARM 64 v8a, android-31 | Intel x86_64 Atom, android-31 | Google TV Intel x86 Atom, android-31 | Google APIs ARM 64 v8a, android-31 | Google APIs Intel x86_64 Atom, android-31 | Google Play Intel x86 Atom_64, android-32 | Google APIs Intel x86 Atom_64, android-33 | Google Play Intel x86 Atom_64, android-TiramisuPrivacySandbox | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.12 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.7 => 0.70.5 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

I run  npx react-native run-android
![Screenshot_1683668107](https://github.com/facebook/react-native/assets/53443993/3551bb71-5c8b-4965-9f34-74b98bdbc0b1)

### Snack, code example, screenshot, or link to a repository

.....

**Comment by pavlov-sergey-alexandr** [comment]
i solved this problem. Another program running on the port 8081.

For check i used next comand 
     sudo lsof -i :8081
For terminate program 
    sudo kill -9 59

https://stackoverflow.com/questions/43425754/react-native-error-packager-cant-listen-on-port-8081/70046852#70046852

**Comment by cortinico** [comment]
> i solved this problem. Another program running on the port 8081.

Closing because of this
