### ISSUE TITLE
Need to remove rn_dev_prefrence.xml from release build on decompile build

### ISSUE THREAD

**Issue by nirajc4409** [facebook/react-native#37348]
### Description

we used the RN version 0.63.4 and somehow in the release build, we are getting rn_dev_preference XML in the build.

we need to remove the file for some security issues. 
please suggest a way to remove the file from the release build. 

The path on decompile build: res/XML/rn_dev_preference The path

### React Native Version

0.63.4

### Output of `npx react-native info`

<img width="782" alt="Screenshot 2023-05-10 at 1 05 41 PM" src="https://github.com/facebook/react-native/assets/30557945/9ab50773-cbbd-4b0d-8d96-c607250ba679">

### Steps to reproduce

create a build and just decompile the build you can see the file in res/xml/ folder the 

### Snack, code example, screenshot, or link to a repository

res/xml/rn_dev_preference.xml

**Comment by nirajc4409** [comment]
@cortinico Can you help me with this issue? if you have any idea about this.

**Comment by cortinico** [comment]
> @cortinico Can you help me with this issue? if you have any idea about this.

Sadly we cannot. Firsy, you're using a too old version of React Native.

> we need to remove the file for some security issues.

Moreover, it's unclear what are the security issues with this file, so we can't help you further.
