### ISSUE TITLE
Is this New Architecture still in beta or stable?

### ISSUE THREAD

**Issue by KamalSilva007** [facebook/react-native#37346]
### Description

Can you please confirm is this New Architecture still in beta or stable? If it is in beta, how long it will take to be stable?

### React Native Version

0.71.0

### Output of `npx react-native info`

-

### Steps to reproduce

-

### Snack, code example, screenshot, or link to a repository

-

**Comment by cortinico** [comment]
> Can you please confirm is this New Architecture still in beta or stable? If it is in beta, how long it will take to be stable?

As described on the New Architecture landing page, it's still experimental:
https://reactnative.dev/docs/the-new-architecture/landing-page
