### ISSUE TITLE
Got a task FAILED for the task generateCodegenSchemaFromJavaScript when executing `yarn install-android-jsc` with nothing modified

### ISSUE THREAD

**Issue by jcdhlzq** [facebook/react-native#37353]
### Description

Got the FAILED without modification and it just occurs suddenly.
![image](https://github.com/facebook/react-native/assets/23273745/c2935a7e-f0b6-4e4b-ab71-c92bc4ec7bd3)

### React Native Version

0.72.0-rc2

### Output of `npx react-native info`

System:
  OS: macOS 13.3.1
  CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Memory: 127.24 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 16.13.1
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.19
    path: /usr/local/bin/yarn
  npm:
    version: 8.1.2
    path: /usr/local/bin/npm
  Watchman:
    version: 2023.03.13.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.11.3
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK:
    Android NDK: 22.1.7171670
IDEs:
  Android Studio: 2022.1 AI-221.6008.13.2211.9619390
  Xcode:
    version: 14.3/14E222b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.12
    path: /usr/bin/javac
  Ruby:
    version: 3.0.5
    path: /usr/local/opt/ruby@3.0/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: true
  newArchEnabled: Not found

### Steps to reproduce

On the main branch:
1. yarn
2. yarn install-android-jsc

### Snack, code example, screenshot, or link to a repository

no

**Comment by jcdhlzq** [comment]
> Hi @jcdhlzq, can you try to `rm -rf packages/react-native-codegen/lib` folder and try again?
> 
> What I think has happened is that you had an outdated version of codegen. You pulled in some changes we landed last week, and when building again, rn-tester is not rebuilding codegen as it can find an existing prebuilt already on disk.
> 
> By deleting the lib folder, we should force it to rebuild Codegen and it should work. Let me know if that helps.

It's helpful! Thanks!

**Comment by harisbitsol123** [comment]
Where we have to run this command?

**Comment by ngxhuyhoang** [comment]
> Where we have to run this command?

Same question

**Comment by cipolleschi** [comment]
@harisbitsol123 @ngxhuyhoang:  are you trying to run RN-Tester from the React Native repo?

If yes, you have to run it from the main folder of the repository.

This command does not work for regular apps, as regular apps don't have the `packages/react-native-codegen` package.

**Comment by Kavahardik** [comment]
Hello everyone after update my RN project from 070.4 to 0.75.4 react native and i am facing below error any one has any solution for this?

 What went wrong:
Execution failed for task ':datadog_mobile-react-native:generateCodegenSchemaFromJavaScript'.
> Process 'command 'node'' finished with non-zero exit value 7

**Comment by cipolleschi** [comment]
@Kavahardik Can you try the following:
1. run `yarn install`
2. run `cd android && ./gradlew clean`
3. Try to build 

It could be that there are some stale files

**Comment by cortinico** [comment]
> Hello everyone after update my RN project from 0.70.4 to 0.75.4 react native and i am facing below error any one has any solution for this?

Please open a new task and provide the FULL build log
