### ISSUE TITLE
react-native 0.69.9  ios 11  crash

### ISSUE THREAD

**Issue by yxwandroid** [facebook/react-native#37351]
### Description

crash info 

dyld: Symbol not found: __ZNSt19bad_optional_accessD1Ev
  Referenced from: /private/var/containers/Bundle/Application/18A8216C-D9DE-4985-A873-5B90C503041C/OPTapp.app/Frameworks/CoreModules.framework/CoreModules
  Expected in: /usr/lib/libc++.1.dylib
 in /private/var/containers/Bundle/Application/18A8216C-D9DE-4985-A873-5B90C503041C/OPTapp.app/Frameworks/CoreModules.framework/CoreModules
(lldb)

### React Native Version

0.69.9

### Output of `npx react-native info`

System:
    OS: macOS 13.2.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 97.16 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.10.0 - ~/.nvm/versions/node/v16.10.0/bin/node
    Yarn: 1.22.17 - ~/.yarn/bin/yarn
    npm: 7.24.0 - ~/.nvm/versions/node/v16.10.0/bin/npm
    Watchman: 2022.03.21.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 18, 19, 23, 25, 26, 27, 28, 29, 30, 31, 32, 33
      Build Tools: 23.0.3, 26.0.2, 28.0.3, 29.0.0, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0
      System Images: android-23 | Google APIs ARM EABI v7a, android-25 | Google APIs ARM EABI v7a, android-29 | Google Play Intel x86 Atom, android-31 | Google APIs Intel x86 Atom_64
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8512546
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.9 => 0.69.9 
    react-native-macos: Not Found

### Steps to reproduce

Create a sample 0.69.9 project running on an ios11 phone that will reproduce

### Snack, code example, screenshot, or link to a repository

Create a sample 0.69.9 project running on an ios11 phone that will reproduce

**Comment by kingzeng** [comment]
System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M1
    Memory: 126.73 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.18.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
    Watchman: 2022.06.06.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK:
      API Levels: 23, 25, 26, 28, 30, 31, 32, 33
      Build Tools: 28.0.3, 30.0.2, 30.0.3, 31.0.0, 33.0.0
      System Images: android-33 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.9971841
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^18.2.0 => 18.2.0 
    react-native: 0.71.4 => 0.71.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found


Have the same exception

**Comment by rearlytang** [comment]
You can try:
Build Phases-Link Binary With Libraries    add       libc++.tbd (Optional)
