### ISSUE TITLE
Does RN support loading several bundles and merging the bundles ?

### ISSUE THREAD

**Issue by ToccaLeee** [facebook/react-native#3736]
Does RN support loading several bundles and merging the bundles or have this plan? For example, in order to reduce the loading bundle size, we can package the RN's JS into a bundle and package the application JS into anther bundle. Then every time the client just load the new updated package bundle(RN bundle or Application bundle) from server .

**Comment by brentvatne** [comment]
Hi there!

This is not currently available but bundle splitting is a work in progress :) This is definitely something that many of us are interested in so stay tuned.
