### ISSUE TITLE
React Native "TypeError: Network request failed" on Fetch Please

### ISSUE THREAD

**Issue by ehdaydkv112** [facebook/react-native#37382]
### Description

**React Native "TypeError: Network request failed" on Fetch Please**

I'm suffering continuously.

Help me, please.

FIx Please.

If you don't

Be ready for it.

### React Native Version

0.67.4

### Output of `npx react-native info`

System:
    OS: macOS 13.0
    CPU: (12) arm64 Apple M2 Max
    Memory: 110.09 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.6.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.0 - /usr/local/bin/npm
    Watchman: 2023.05.01.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK:
      API Levels: 23, 28, 29, 30, 31, 32, 33
      Build Tools: 30.0.2, 30.0.3, 33.0.2, 34.0.0
      System Images: android-33 | Google APIs ARM 64 v8a, android-33 | Google APIs Intel x86_64 Atom, android-33 | Google Play ARM 64 v8a, android-33 | Google Play Intel x86_64 Atom, android-TiramisuPrivacySandbox | Google Play ARM 64 v8a, android-TiramisuPrivacySandbox | Google Play Intel x86_64 Atom, android-UpsideDownCake | Google APIs ARM 64 v8a, android-UpsideDownCake | Google APIs Intel x86_64 Atom, android-UpsideDownCake | Google Play ARM 64 v8a, android-UpsideDownCake | Google Play Intel x86_64 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.9971841
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.4 => 0.67.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. fetch

2. error

:)

### Snack, code example, screenshot, or link to a repository

*

**Comment by ehdaydkv112** [comment]
Be quiet, GitHub Bot.

The latest version is getting the same error.

Everyone else is going through the same thing.

**Comment by AntoineDoubovetzky** [comment]
@ehdaydkv112 Can you provide a repository with a minimal reproducible example?

**Comment by molo0** [comment]
In my case, it was my server's tls version problem. I found that my fetch with https api is not working. After I changed by api address https to http, it worked. I wondered why and found that my server protocol is only supports tls version 1.3. Devices up to Android Pie use TLS 1.2 so I changed by protocol both support tls1.2 and tls1.3. This is how solved my problem.
