### ISSUE TITLE
Debug Menu, "Debug in Chrome" shown *sometimes*

### ISSUE THREAD

**Issue by robsco** [facebook/react-native#37406]
### Description

When in dev mode on iPhone, I shake to show the debug menu.

**Sometimes** I get the option to "Debug in Chrome", which I believe is supposed to be phased out in favour of a different debug method?

(I usually see 2 debug menus, sometimes they're both identical, but sometimes one has the Chrome option).

I love this Chrome method as it allows me to open an instance of Chrome that's NOT on my mac and navigate to http://192.168.0.20:8081/debugger-ui/

To then open the Chrome console and see super-fast debug statements, and full dumps of objects.

192.168.0.20 is my mac IP, but I don't develop directly on that machine.

I never have much joy with the other/new way of debugging in Flipper, as I have to remote desktop to my mac, and even then the debugging is nowhere near as quick or as detailed as in the Chrome console (e.g. dumping objects).

This only happens randomly - how can I access the Chrome debug option all the time?

### React Native Version

0.70.6

### Output of `npx react-native info`

% npx react-native info
info Fetching system and libraries information...
System:
    OS: macOS 13.0.1
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Memory: 7.40 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.1.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 8.19.3 - /usr/local/bin/npm
    Watchman: 2022.11.14.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /Users/rob/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.6 => 0.70.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
npm notice 
npm notice New major version of npm available! 8.19.3 -> 9.6.6
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.6.6
npm notice Run npm install -g npm@9.6.6 to update!
npm notice 

### Steps to reproduce

Install debug/dev version in Xcode, shake to open debug menu, and hope that the Chrome option appears.

### Snack, code example, screenshot, or link to a repository

N/A.

**Comment by cortinico** [comment]
cc @huntie
