### ISSUE TITLE
When I run my app via npx react-native run-ios --simulator 'iPhone 14 Pro Max' I get the error Firebase is not configured

### ISSUE THREAD

**Issue by belarbi104** [facebook/react-native#37416]
### Description

I use the expo-firebase-analytics library. On Expo it works fine because it's via web. But when I run it via npx react-native run-ios it builds the app and I can use everything except Analytics even though I configured the plist file like below. I tried everything I could I really need the help.

PLIST:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CLIENT_ID</key>
    <string>xxxxx</string>
    <key>REVERSED_CLIENT_ID</key>
    <string>xxxx</string>
    <key>API_KEY</key>
    <string>xxxx</string>
    <key>GCM_SENDER_ID</key>
    <string>xxxxx</string>
    <key>PLIST_VERSION</key>
    <string>1</string>
    <key>BUNDLE_ID</key>
    <string>xxxx</string>
    <key>PROJECT_ID</key>
    <string>xxxx</string>
    <key>STORAGE_BUCKET</key>
    <string>xxxx</string>
    <key>IS_ADS_ENABLED</key>
    <false></false>
    <key>IS_ANALYTICS_ENABLED</key>
    <true></true>
    <key>IS_APPINVITE_ENABLED</key>
    <true></true>
    <key>IS_GCM_ENABLED</key>
    <true></true>
    <key>IS_SIGNIN_ENABLED</key>
    <true></true>
    <key>GOOGLE_APP_ID</key>
    <string>xxxx</string>
    <key>DATABASE_URL</key>
    <string>xxxx</string>
</dict>
</plist>
```

app.json:

```
{
  "expo": {
    "name": "LUX",
    "slug": "lux",
    "owner": "lux_kaso",
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./Pics/logo.png",
    "userInterfaceStyle": "automatic",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#000000"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true,
      "googleServicesFile": "./GoogleService-Info.plist",
      "bundleIdentifier": "lux.ios"
    },
    "android": {
      "googleServicesFile": "./google-services.json",
      "adaptiveIcon": {
        "foregroundImage": "./assets/adaptive-icon.png",
        "backgroundColor": "#FFFFFF"
      },
      "package": "lux.android"
    },
    "web": {
      "config": {
        "firebase": {
          "apiKey": "xxxx",
          "authDomain": "xxxx",
          "projectId": "xxxx",
          "storageBucket": "xxxx",
          "messagingSenderId": "xxxx",
          "appId": "xxxx",
          "measurementId": "xxxx"
        }
      },
      "favicon": "./assets/favicon.png"
    },
    "extra": {
      "eas": {
        "projectId": "xxxx"
      }
    },
    "plugins": [
      [
        "expo-build-properties",
        {
          "ios": {
            "useFrameworks": "static",
            "deploymentTarget": "13.0"
          }
        }
      ]
    ]
  }
}
```

### React Native Version

0.69.6

### Output of `npx react-native info`

System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M2 Pro
    Memory: 162.64 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 9.5.1 - /usr/local/bin/npm
    Watchman: 2023.05.01.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /Users/karimbelarbi/.rvm/gems/ruby-2.7.5/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.9971841
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.6 => 0.69.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Just use the versions of mine:
"expo": "~46.0.13",
"expo-firebase-analytics": "7.2.0",

### Snack, code example, screenshot, or link to a repository

Written in description

**Comment by cortinico** [comment]
Hi @belarbi104 
Thanks for reporting this issue.

It seems like this issue is actually unrelated to React Native core but related to `expo-firebase-analytics`. Please open this issue against this other repository:

https://github.com/expo/expo/issues

I'll be closing this but feel free to reopen if the other repo points back to us as a issue in the core of React Native.
