### ISSUE TITLE
Modal push elements down when it's open ANDROID

### ISSUE THREAD

**Issue by FedeBatt** [facebook/react-native#37418]
### Description

I create a tooltip component, but when i open the modal with the property "transparent", the elements are pushed down only happend in Android. In iOS work's well.

### React Native Version

0.70.6

### Output of `npx react-native info`

System:
OS: macOS 13.3.1
CPU: 2,6 GHz Intel Core i7 de seis núcleos
Memory: 162.64 MB / 16.00 GB
Shell: 5.9 - /bin/zsh
Binaries:
Node: 18.16.0 - /usr/local/bin/node
Yarn: Not Found
npm: 9.5.1 - /usr/local/bin/npm
Watchman: 2023.05.01.00 - /opt/homebrew/bin/watchman
Managers:
CocoaPods: 1.12.1 - /Users/karimbelarbi/.rvm/gems/ruby-2.7.5/bin/pod
SDKs:
iOS SDK:
Platforms: 
Android SDK: Pixel4 SDK 33
IDEs: 
Android Studio: 2022.2 AI-222.4459.24.2221.9971841
Xcode: 14.3/14E222b - /usr/bin/xcodebuild
Languages:
Java: Not Found
npmPackages:
@react-native-community/cli: Not Found
react: 18.1.0
react-native: 0.70.6
react-native-macos: Not Found
npmGlobalPackages:
react-native: Not Found

### Steps to reproduce

Paste the follow code and you should see

![Captura de pantalla 2023-05-12 a la(s) 16 35 32](https://github.com/facebook/react-native/assets/59941634/f03aea49-a718-4504-b579-d9883f887c0c)

![Captura de pantalla 2023-05-12 a la(s) 16 35 51](https://github.com/facebook/react-native/assets/59941634/ff9d6b91-6f23-45d2-bc8c-3cd0fb984f51)

### Snack, code example, screenshot, or link to a repository

` <View style={{ justifyContent: 'center', alignItems: 'center', flex: 1 }}>
      <Text>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed volutpat lacus in massa
        eleifend blandit. Donec sit amet ipsum sed odio bibendum facilisis a eu lorem. Fusce
        consequat felis at massa rhoncus, a faucibus sapien interdum.
        <Modal transparent visible={true}>
          <View
            style={{
              width: '100%',
              height: '100%',
              backgroundColor: 'red',
            }}
          ></View>
        </Modal>
      </Text>
    </View>`

**Comment by hanarotg** [comment]
In Android platform, you need to set `statusBarTranslucent` to `true` in your modal

- [React-Native statusBarTranslucent](https://reactnative.dev/docs/modal#statusbartranslucent-android)

## Edited code

```JSX
import React, {useState} from 'react';
import {Text, View, Modal} from 'react-native';

export default function App() {
  return (
    <View style={{justifyContent: 'center', alignItems: 'center', flex: 1}}>
      <Text>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed volutpat
        lacus in massa eleifend blandit. Donec sit amet ipsum sed odio bibendum
        facilisis a eu lorem. Fusce consequat felis at massa rhoncus, a faucibus
        sapien interdum.
        <Modal transparent visible={true} statusBarTranslucent={true}>
          <View
            style={{
              width: '100%',
              height: '100%',
              backgroundColor: 'red',
            }}></View>
        </Modal>
      </Text>
    </View>
  );
}

```


## Screenshot 

<img width="219" alt="스크린샷 2023-06-21 오후 6 05 42" src="https://github.com/facebook/react-native/assets/34812887/38a24863-ab59-444d-b6b1-946dd1918343">
