### ISSUE TITLE
iOS Hermes bytecode bundle not produced in React Native 0.70

### ISSUE THREAD

**Issue by yhkaplan** [facebook/react-native#37419]
### Description

I noticed the following important commits to `scripts/react-native-xcode.sh` aren't included in RN 0.70.x, resulting in the following issues with even the latest 0.70 patch version, the most important of which is that the **iOS hermes bytecode bundle is not produced** without USE_HERMES being set to true. 

RN 0.70 was [publicly announced as having hermes as the default engine](https://reactnative.dev/blog/2022/09/05/version-070#hermes-as-default-engine) and there is no mention in the community run [upgrade helper](https://react-native-community.github.io/upgrade-helper) nor official React Native docs nor changelog for 0.70.x about USE_HERMES that I could see, so I think many people missed this. 

I think this warrants a new patch release backporting these commits. Please tell me what you think 🙏 

- Hermes bytecode bundle not created; instead only the standard js bundle created but hermes library is in iOS app
  - https://github.com/facebook/react-native/commit/03de19745eec9a0d4d1075bac48639ecf1d41352
- Broken sourcemaps:
   - https://github.com/facebook/react-native/commit/61106ac6805cddef97e16e473b155abdad701797
   - https://github.com/facebook/react-native/commit/a98da322293e2db777bcc599b5abb10f750a7816
- Unneeded sourcemaps included in app when USE_HERMES is true
  - https://github.com/facebook/react-native/commit/e0a71fc7b5cb8c264000147099be5b2575931193

### React Native Version

0.70.9

### Output of `npx react-native info`

System:
    OS: macOS 12.6.3
    CPU: (10) arm64 Apple M1 Max
    Memory: 538.73 MB / 64.00 GB
    Shell: 5.8.1 - /opt/homebrew/bin/zsh
  Binaries:
    Node: 18.16.0 - /private/var/folders/kb/43z97t0s60b19n7jssrt0_x80000gp/T/xfs-5c644398/node
    Yarn: 3.4.1 - /private/var/folders/kb/43z97t0s60b19n7jssrt0_x80000gp/T/xfs-5c644398/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
    Watchman: 2023.01.16.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/josh/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 28, 29, 30, 31, 32, 33, 33
      Build Tools: 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0
      System Images: android-30 | Google Play ARM 64 v8a, android-32 | Google APIs ARM 64 v8a, android-33 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9619390
    Xcode: 14.1/14B47 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.9 => 0.70.9
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. Build release iOS app with RN 0.70.x

### Snack, code example, screenshot, or link to a repository

N/A

**Comment by dmytrorykun** [comment]
Thank you for reporting!
These commits will be picked in 0.70.10 (https://github.com/reactwg/react-native-releases/discussions/66#discussioncomment-5904073).
