### ISSUE TITLE
TextEdit in correct "onChange/onTextChange"

### ISSUE THREAD

**Issue by jeokeefe** [facebook/react-native#37426]
### Description

TextEdit if value and editable are fired at or near the same time. onChangeText fires twice with the OLD value the 2nd time not the new value.

### React Native Version

0.71.7

### Output of `npx react-native info`

System:
    OS: macOS 13.3.1
    CPU: (12) arm64 Apple M2 Max
    Memory: 1.53 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.6.6 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: ^0.71.7 => 0.71.7 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1) Preset value to "VALUE1" via a useState - [value, setValue] = useState('VALUE1')
2) set TextEdit value={value}
2) Present value of editable to try via a useState - [editable, setEditable] = useState(true)
4) set TextEdit editable={editable}
2) Manually type/set contents of TextEdit to "VALUE2"
3) Use a button that will fire this code:
setValue("VALUE1");
setEditable(false);

The "value" of the TextEdit initially changes to 'VALUE1' as observed by onChangeText, however onChangeText fires a second time (why?) with the previous value ('VALUE2').

### Snack, code example, screenshot, or link to a repository

unable to provide

**Comment by jeokeefe** [comment]
https://snack.expo.dev/@xpario/textedit---react-native-bug?platform=web

the issue started with 0.71.7 - i understand there is a newer version - ill have to wait until expo updates it. I am not able to test on 0.7.1.8

**Comment by elbadrawy** [comment]
our observation is that this issue happens only on IOS 16.4 
we didn't test it on IOS 16.5 as it is still beta 
we have also tried this fix  0.7.1.8  and it doesn't work 

this issue is related to the IOS version not react native version

**Comment by elbadrawy** [comment]
I have retested this issue on IOS 16.4.1 and working fine
