### ISSUE TITLE
Unrecognized font family

### ISSUE THREAD

**Issue by namikarif** [facebook/react-native#37425]
### Description

I'm getting an error with the fonts I added. I have no idea how to solve the problem. I tried all the suggestions I found on the internet, but the problem is not solved.

### React Native Version

0.71.7

### Output of `npx react-native info`

System:
    OS: macOS 11.6.8
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 271.63 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.16.0 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 9.6.5 - /usr/local/bin/npm
    Watchman: 2022.12.12.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 28, 29, 30, 31, 33
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 33.0.0
      System Images: android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8815526
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.7 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.7 => 0.71.7 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

`
 fontFamily: 'SF-Pro-Text-Medium',
        fontSize: 18,
        lineHeight: 20,
        textAlign: 'center',
        letterSpacing: -0.01,
        marginHorizontal: 16,
        color: '#00000040'
`

### Snack, code example, screenshot, or link to a repository

`react-native.config.js`

`module.exports = { 
    project: {
        ios: {},
        android: {}, // grouped into "project"
    },
    assets: ["./assets/fonts/"], // stays the same
    dependencies: {
        ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
    },
};`

`package.json`

`
"rnpm": {
    "assets": [
      "./assests/fonts/"
    ]
  }
`

`Screen Shots`

<b>1. Resources</b>
<img width="215" alt="Ekran Resmi 2023-05-13 23 37 34" src="https://github.com/facebook/react-native/assets/45629136/b04aa527-637e-49f9-acdc-41cd4553b477">

<br />

<b>

<b>2. Copy Bundle Resources in Build Phases</b>
<img width="387" alt="Ekran Resmi 2023-05-13 23 37 51" src="https://github.com/facebook/react-native/assets/45629136/e43559d6-1be1-49fd-a362-5d7373454d4e">

<br />

<b>3. Info.plist</b>
<img width="571" alt="Ekran Resmi 2023-05-13 23 38 27" src="https://github.com/facebook/react-native/assets/45629136/c46332a8-0b83-4ac9-892b-b1f7401334c2">

<br />

<b>4. Error Screen</b>
<img width="328" alt="Ekran Resmi 2023-05-13 23 38 40" src="https://github.com/facebook/react-native/assets/45629136/15cf0773-5618-4b0e-a2fe-a8fc73dbcae5">

**Comment by DigitalZebra** [comment]
In my experience, this type of error can happen if the name of the font (in the font file itself) doesn't match what's expected (i.e. the file name).

I would navigate to a tool like [FontDrop](https://fontdrop.info/), drop one of your font files there, and see what the values for `fontFamily` and `fullName` are on the `Data` tab. Try one of those values in your RN styles instead of `SF-Text-Pro-Regular`. 

Here's an example of Font Drop's output for Roboto Black:
<img width="371" alt="image" src="https://github.com/facebook/react-native/assets/1010583/b7752b38-4fce-4598-917f-c63ddfa59964">

You could also try debugging on the native side to see which fonts are available, that would tell you definitively what font names are available.

**Comment by emmbyiringiro** [comment]
The name you are using for font  family does not match the font PostScript name. Replace `SF-Pro-text-regular` with `SFPro-Regular`

<img width="360" alt="Screenshot 2023-05-22 at 00 03 09" src="https://github.com/facebook/react-native/assets/46843540/f3c8691a-6438-492e-99c8-611f8b3faee8">

**Comment by ellouzeskandercs** [comment]
If you are still struggling to add a font in your react-native application, I strongly recommend the ["Add a custom font to your React Native app"](https://www.bam.tech/en/article/add-a-custom-font-to-your-react-native-app) article which is one of the best article when it comes to adding font to react-native (although it is 6 years old).

**Comment by meixiaoLi** [comment]
I'm facing the same problem in React Native version 0.72.3.
I'm using the 'Font Awesome 5 Pro' font.
The font file's name is FontAwesome5_Pro_Light.ttf.
I have added it to the 'fonts' folder and copied the 'bundle resources' as well as the 'info.plist' files.
However, I'm still encountering this error.

**Comment by mathews-p** [comment]
@meixiaoLi Can you please provide guidance on resolving the "Unrecognized font family" error in React Native version 0.72.3? We are currently facing challenges in addressing this issue.

**Comment by MXLI88** [comment]
> @meixiaoLi Can you please provide guidance on resolving the "Unrecognized font family" error in React Native version 0.72.3? We are currently facing challenges in addressing this issue.

ended up upgrading to font awesome 6.

**Comment by cortinico** [comment]
Closing as users already provided some viable solutions

**Comment by Mansourx** [comment]
> The name you are using for font family does not match the font PostScript name. Replace `SF-Pro-text-regular` with `SFPro-Regular`
> 
> <img alt="Screenshot 2023-05-22 at 00 03 09" width="360" src="https://private-user-images.githubusercontent.com/46843540/239770250-f3c8691a-6438-492e-99c8-611f8b3faee8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MTA0NzQsIm5iZiI6MTcwNTkxMDE3NCwicGF0aCI6Ii80Njg0MzU0MC8yMzk3NzAyNTAtZjNjODY5MWEtNjQzOC00OTJlLTk5YzgtNjExZjhiM2ZhZWU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDA3NTYxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzNzU3M2JiY2YyZTkyZjFhMzI2NzcxYmUyZDFiZTQ2YTgzNDFiYzM3Y2VkNWRhY2M0OWJmZTk5MjE4YzljYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kCJ4Z3ignrlGF8nlmB_ntL_VbSsXOfeB1ZAiB4Asypw">

This fixed my problem. +1

**Comment by kleviss** [comment]
> If you are still struggling to add a font in your react-native application, I strongly recommend the ["Add a custom font to your React Native app"](https://www.bam.tech/en/article/add-a-custom-font-to-your-react-native-app) article which is one of the best article when it comes to adding font to react-native (although it is 6 years old).

2025 revalidation of the solution here. Seems like I had installed fonts the wrong way, and a combination of the steps above worked. As this issue mostly comes from not using the _PostScript_ name for the font, and if you are like me and _**did not know where to get this**_, just double-click the downloaded font, install it, and it will open the `FontBook` app. There you can filter down for the font you installed, in my case "Inter," and look for the double chevron right `>>` icon in the top bar, to toggle the pane to see the Infos like https://github.com/facebook/react-native/issues/37425#issuecomment-1556305802 is doing  : 

<img width="1086" alt="Image" src="https://github.com/user-attachments/assets/51fe2ca4-49d8-4ecb-91e0-10b4834f7707" />
