### ISSUE TITLE
TextInput color not working.

### ISSUE THREAD

**Issue by sankhadeeproy007** [facebook/react-native#3742]
Hi, I have a problem. I have a TextInput and I want the text that would be typed in there to be white in color. So, I add the style, color: '#fff' to it. It worked on a previous project but somehow renders the text in black now. I've run out of ideas and I know stackoverlfow is probably a better place for such a question. But frankly, there aren't too many people there either. So please let me know if anyone can help me. Thank you.

**Comment by astreet** [comment]
What platform is this? Can you post a rnplay.org example?

**Comment by sankhadeeproy007** [comment]
@astreet https://rnplay.org/apps/vPqdqA

**Comment by astreet** [comment]
Ok, thanks for the report. @andreicoman11 is this something you're aware of?

**Comment by sankhadeeproy007** [comment]
@astreet Did you also notice that the transitions were working on iOS and not on Android? Is there something wrong with the code?

**Comment by maraujop** [comment]
I've just hit this bug in Android too, just confirming it.

**Comment by andreicoman11** [comment]
Fixed by https://github.com/facebook/react-native/commit/5ed8c6732ee0636143f62e7495c67de93d1db1d7

**Comment by louuysison** [comment]
Anybody experiencing this issue when secureTextEntry={true}  _**after**_ the fix?

**Comment by sankhadeeproy007** [comment]
Me.

**Comment by slavik0329** [comment]
@louuysison I'm having the same issue. I have a username and password inputbox. Both styled with color:white. The one without secureTextEntry works as expected, but when secureTextEntry is enabled, the text color becomes black and I see no way of correcting it

**Comment by sskrla** [comment]
I am experiencing the same issue with `secureTextEntry`, does it need to be tracked a separate issue?

**Comment by christopherdro** [comment]
@sskira There is already a issue open on that. See #4435.

**Comment by surdu** [comment]
This will not added to v0.30 release candidate ? It was fixed months ago :disappointed:

**Comment by taobad** [comment]
I am having the same issue too, is it fixed yet

**Comment by EugeneBichel** [comment]
"react-native": "0.44.2" I have the same issue for android.

**Comment by Gp2mv3** [comment]
I have the same issue with React Native 53.3 on Android. Still no solution ?

**Comment by imakin** [comment]
hey, still not supported here on android yo
