### ISSUE TITLE
Using CameraRoll on Android throws TypeError [RCTCameraRollManager is undefined]

### ISSUE THREAD

**Issue by leeyeh** [facebook/react-native#3743]
Is CameraRoll available on Android now, or am I missing some kind of  linking steps like iOS?

**Comment by cosmith** [comment]
It hasn't been open sourced yet. See http://facebook.github.io/react-native/docs/known-issues.html#content

**Comment by leeyeh** [comment]
Thanks for pointing it out. However, it will be really helpful if the document for CameraRoll have mentioned it.

**Comment by whokilledtheelectricmonk** [comment]
@cosmith Is there an ETA for the API?

**Comment by cosmith** [comment]
I don't know, maybe someone at facebook has more info?

**Comment by turka50** [comment]
+1
