### ISSUE TITLE
三层scrollview没法正常使用

### ISSUE THREAD

**Issue by cmdparkour** [facebook/react-native#37449]
### Description

场景如下：我有一个复杂的页面，页面有头部，以及一个列表，当头部滑动的时候，列表tab项需要悬浮，底下的列表还需要可以进行左右切换，并且列表内的数据可以正常上下滚动
<ScrollView style={{ flex: 1 }}>
        <View style={{ height: 600 }}><Text>789</Text></View>
        <ScrollView horizontal={true} style={{ height: 800 }}>
          <ScrollView style={{ flex: 1, backgroundColor: '#999', width: $.pxToDp(750) }}>
            <View style={{ height: 300 }}><Text>123</Text></View>
            <View style={{ height: 500 }}><Text>123</Text></View>
            <View style={{ height: 900 }}><Text>456</Text></View>
          </ScrollView>
          <ScrollView style={{ flex: 1, backgroundColor: '#ffffff', width: $.pxToDp(750) }}>
            <View style={{ height: 300 }}><Text>123</Text></View>
            <View style={{ height: 500 }}><Text>123</Text></View>
            <View style={{ height: 900 }}><Text>456</Text></View>
          </ScrollView>
        </ScrollView>
      </ScrollView>

### React Native Version

0.68

### Output of `npx react-native info`

三层scrollview没法正常使用

### Steps to reproduce

三层scrollview没法正常使用

### Snack, code example, screenshot, or link to a repository

三层scrollview没法正常使用

**Comment by cortinico** [comment]
Hi @cmdparkour 
In this issue tracker we accept only issues that are in English.
I'm closing this for now, please consider translating it to English and reopening it.
Thanks.
