### ISSUE TITLE
React Native Crashed: Thread: SIGSEGV  0x41a774784173d1a8

### ISSUE THREAD

**Issue by vaibsshukla** [facebook/react-native#37446]
### Description

Random crashes in prod env:

Insufficient info in crash report:

🚨🚨🚨🚨Need urgent help

Crashed: Thread: SIGSEGV  0x41a774784173d1a8
#00 pc 0x11957c libGLESv2_POWERVR_ROGUE.so (BuildId: f3ecde2889a8beaaaebecf30d9bd436a)
#01 pc 0xb81d8 libGLESv2_POWERVR_ROGUE.so (BuildId: f3ecde2889a8beaaaebecf30d9bd436a)
#02 pc 0xb81d8 libGLESv2_POWERVR_ROGUE.so (BuildId: f3ecde2889a8beaaaebecf30d9bd436a)
#03 pc 0xb7188 libGLESv2_POWERVR_ROGUE.so (BuildId: f3ecde2889a8beaaaebecf30d9bd436a)
#04 pc 0xb5324 libGLESv2_POWERVR_ROGUE.so (BuildId: f3ecde2889a8beaaaebecf30d9bd436a)
#05 pc 0xb5f4c libGLESv2_POWERVR_ROGUE.so (BuildId: f3ecde2889a8beaaaebecf30d9bd436a)
#06 pc 0xcba30 libGLESv2_POWERVR_ROGUE.so (BuildId: f3ecde2889a8beaaaebecf30d9bd436a)
#07 pc 0x2a7e0 libGLESv2_POWERVR_ROGUE.so (BuildId: f3ecde2889a8beaaaebecf30d9bd436a)
#08 pc 0x1b8ff88 libmonochrome.so (BuildId: 307c8a7721b48514900dddece4cfad8afad4210b)
#09 pc 0x25b6dd8 libmonochrome.so (BuildId: 307c8a7721b48514900dddece4cfad8afad4210b)
#10 pc 0x259a540 libmonochrome.so (BuildId: 307c8a7721b48514900dddece4cfad8afad4210b)
#11 pc 0x259955c libmonochrome.so (BuildId: 307c8a7721b48514900dddece4cfad8afad4210b)
#12 pc 0x2599478 libmonochrome.so (BuildId: 307c8a7721b48514900dddece4cfad8afad4210b)
#13 pc 0x2d48474 libmonochrome.so (BuildId: 307c8a7721b48514900dddece4cfad8afad4210b)
#14 pc 0x2d4834c libmonochrome.so (BuildId: 307c8a7721b48514900dddece4cfad8afad4210b)
#15 pc 0x2d03b9c libmonochrome.so (BuildId: 307c8a7721b48514900dddece4cfad8afad4210b)
#16 pc 0x2cc3c64 libmonochrome.so (BuildId: 307c8a7721b48514900dddece4cfad8afad4210b)
#17 pc 0x2cc3a9c libmonochrome.so (BuildId: 307c8a7721b48514900dddece4cfad8afad4210b)
#18 pc 0x2ce3a38 libmonochrome.so (BuildId: 307c8a7721b48514900dddece4cfad8afad4210b)
#19 pc 0x2d18574 libmonochrome.so (BuildId: 307c8a7721b48514900dddece4cfad8afad4210b)
#20 pc 0x2ce35c0 libmonochrome.so (BuildId: 307c8a7721b48514900dddece4cfad8afad4210b)
#21 pc 0x2ce2edc libmonochrome.so (BuildId: 307c8a7721b48514900dddece4cfad8afad4210b)
#22 pc 0x208eae8 libmonochrome.so (BuildId: 307c8a7721b48514900dddece4cfad8afad4210b)
#23 pc 0x208f3dc libmonochrome.so (BuildId: 307c8a7721b48514900dddece4cfad8afad4210b)
#24 pc 0x208e580 libmonochrome.so (BuildId: 307c8a7721b48514900dddece4cfad8afad4210b)
#25 pc 0x208e34c libmonochrome.so (BuildId: 307c8a7721b48514900dddece4cfad8afad4210b)
#26 pc 0x208e0d8 libmonochrome.so (BuildId: 307c8a7721b48514900dddece4cfad8afad4210b)
#27 pc 0x208ded0 libmonochrome.so (BuildId: 307c8a7721b48514900dddece4cfad8afad4210b)
#28 pc 0x208dbac libmonochrome.so (BuildId: 307c8a7721b48514900dddece4cfad8afad4210b)
#29 pc 0xe1100 libc.so (BuildId: 676a709a0ee633ec9cf6ab05ec6410ae)
#30 pc 0x83ab0 libc.so (BuildId: 676a709a0ee633ec9cf6ab05ec6410ae)

### React Native Version

0.71.2

### Output of `npx react-native info`

warn Package rn-fetch-blob contains invalid configuration: "dependency.hooks" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
info Fetching system and libraries information...
System:
    OS: macOS 13.2
    CPU: (8) x64 Apple M1
    Memory: 21.91 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.17.6 - /usr/local/bin/node
    Yarn: 1.22.11 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - /opt/homebrew/bin/npm
    Watchman: 2021.08.30.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.10 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.2 => 0.71.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

this happens in Prod env could not able to replicate

### Snack, code example, screenshot, or link to a repository

Insufficient info from Firebase

<img width="1106" alt="Screenshot 2023-05-16 at 12 33 00 PM" src="https://github.com/facebook/react-native/assets/40901524/ea6bdbf0-7135-44b7-a036-43472879236b">

**Comment by cortinico** [comment]
Closing as none of the libs in the stacktrace are React Native related.
The information is unsufficient to debug.
