### ISSUE TITLE
Layout shift when using snapToInterval, getItemLayout and an ItemSeparatorComponent in a FlatList

### ISSUE THREAD

**Issue by BboyKeen** [facebook/react-native#37448]
### Description

Hi there,

First off all, well done for the work done on the VirtualizedList.

I faced a strange issue which took me few days to diagnose but with a really simple fix. I don't know if the fix is the standard way of doing or not so I prefer to report.

To understand the problem, a video is attached with a FlatList having multiple components at same height (600pt) each separated by an ItemSeparator (50pt). The FlatList is configured with a windowSize of 4 and with a getItemLayout respecting the documentation. (See the code below)

At first, when we scroll the first elements, we can see there is no issue but once we reach the 4th, we can notice some kind of glitch which is actually a repositioning. After digging in the internals, what seems to happen behind the scene are the following steps : 
- The user snaps on elements already rendered 
- The VirtualizedList detects we have almost reached the maximum windowSize so it decides to virtualize the first element by replacing it by a spacer.
- The spacer height is less than the previous item height, so the Native Scrollview detects the contentSize has changed by looking at the frame size
- The Native Scrollview notifies the FlatList of this content size changed which re-renders with the good size.

I reproduced this issue using the latest VirtualizedList package (https://github.com/facebook/react-native/tree/main/packages/virtualized-lists) and with the 0.70.1. It's still present in the latest version even if a side-effect I detected in the 0.70.1 was fixed by the rendering refactoring.

To fix it, I had to change my getItemLayout function from 

```
const getItemLayout = useCallback((data, index) => {
    return {
      length: ITEM_HEIGHT,
      offset: (ITEM_HEIGHT + SEPARATOR_HEIGHT) * index,
      index,
    };
  }, []);
  ```
  
  to 
  ```
const getItemLayout = useCallback((data, index) => {
    return {
      length: (ITEM_HEIGHT + SEPARATOR_HEIGHT),
      offset: (ITEM_HEIGHT + SEPARATOR_HEIGHT) * index,
      index,
    };
  }, []);
```

Like I said before, I don't know if it's intended or not but it's not the documentation recommandation. However, now that I'm aware of the rendering internals, I think this is a documentation issue as the separator is included in the CellRendererComponent which is then replaced by the spacer when virtualization occurs.

Hope this helps !

https://github.com/facebook/react-native/assets/1192309/808f03e3-6341-46d6-82e6-e93f319c976a

### React Native Version

0.70.1

### Output of `npx react-native info`

System:
    OS: macOS 12.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 80.30 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.1 - /var/folders/nv/71361px56lb5bljzqqjwrphr0000gn/T/yarn--1684228862197-0.3293063607752016/node
    Yarn: 1.22.19 - /var/folders/nv/71361px56lb5bljzqqjwrphr0000gn/T/yarn--1684228862197-0.3293063607752016/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.1/bin/npm
    Watchman: 2023.05.01.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /opt/homebrew/opt/ruby/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 20.0.1 - /opt/homebrew/opt/openjdk/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.1 => 0.70.1
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
✨  Done in 4.96s.

### Steps to reproduce

Just create a FlatList with the provided code

### Snack, code example, screenshot, or link to a repository

```
  const getItemLayout = useCallback((data, index) => {
    return {
      length: ITEM_HEIGHT,
      offset: ITEM_HEIGHT * index,
      index,
    };
  }, []);
```

```
  const renderItem = useCallback(({item, index}) => {
    return (
      <Item
        index={index}
      />
    );
  }, []);
```

```
<FlatList
        initialScrollIndex={initialScrollIndex}
        ref={flatListRef}
        data={items}
        windowSize={4}
        initialNumToRender={1}
        maxToRenderPerBatch={2}
        removeClippedSubviews={false}
        renderItem={renderItem}
        pagingEnabled
        inverted
        decelerationRate={'fast'}
        snapToInterval={MESSAGE_HEIGHT + SEPARATOR_HEIGHT}
        snapToAlignment={'center'}
        ItemSeparatorComponent={
          <View style={{height: SEPARATOR_HEIGHT, backgroundColor: 'green'}} />
        }
        getItemLayout={getItemLayout}
/>
```

**Comment by BboyKeen** [comment]
The version was updated few days ago 😉

**Comment by iledzka** [comment]
Thanks @BboyKeen , this helped me to understand the bug in my implementation, it was really baffling. I also experienced layout shift, but I don't use ItemSeparatorComponent and my list is horizontal. I'm using snapToOffsets and I tried to adapt your solution to my code, without luck. So far, I can only get it to work by increasing the windowSize :(

**Comment by BboyKeen** [comment]
Hi @iledzka,
Are your list's components fixed size ?

At the end, I decided to use the snapToInterval and snapToAlignment props which worked well with the last virtualized-list package.

To use the last virtualized list and flatlist, I just added two components to override them this way 👍 

```
import React from 'react';
import {VirtualizedList} from '@react-native/virtualized-lists';

export class CustomVirtualizedList extends VirtualizedList {
  constructor(props) {
    super(props);
  }
}
```

```
import React from 'react';
import {FlatList} from 'react-native';
import {CustomVirtualizedList} from './CustomVirtualizedList';

export class CustomFlatList extends FlatList {
  render() {
    return (
      <CustomVirtualizedList
        {...this.props}
        ref={this._captureRef}
        getItem={this._getItem}
        getItemCount={this._getItemCount}
      />
    );
  }
}
```

Hope this can help!

**Comment by iledzka** [comment]
@BboyKeen  yes, my components are fixed size and each component is the same. I use ListFooterComponent and ListHeaderComponent, but the behaviour is the same even if I remove them. I'll try your solution with VirtualisedList, thanks :)
