### ISSUE TITLE
iOS: autoComplete='streetAddressLine2', organizationName  does not work.

### ISSUE THREAD

**Issue by DIPANSHU61** [facebook/react-native#37468]
### Description

We store the address in ios contact card. we passed the property streetAddressLine2. It does not work.

### React Native Version

0.70.9

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
OS: macOS 13.2.1
CPU: (8) arm64 Apple M2
Memory: 73.70 MB / 16.00 GB
Shell: 5.8.1 - /bin/zsh
Binaries:
Node: 19.6.0 - /opt/homebrew/bin/node
Yarn: 1.22.19 - /opt/homebrew/bin/yarn
npm: 9.4.0 - /opt/homebrew/bin/npm
Watchman: 2023.01.30.00 - /opt/homebrew/bin/watchman
Managers:
CocoaPods: 1.11.3 - /usr/local/bin/pod
SDKs:
iOS SDK:
Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
Android SDK:
Android NDK: 22.1.7171670
IDEs:
Android Studio: 2022.1 AI-221.6008.13.2211.9619390
Xcode: 14.3/14E222b - /usr/bin/xcodebuild
Languages:
Java: 11.0.17 - /usr/bin/javac
npmPackages:
@react-native-community/cli: Not Found
react: Not Found
react-native: 0.70.9 => 0.70.9
react-native-macos: Not Found
npmGlobalPackages:
react-native: Not Found

### Steps to reproduce

Open the Contact Card and save the address .

We stored  the address in all Input Fields of Contact Card.

Open the App and open the keyboard, address is not appearing over the keyboard.

### Snack, code example, screenshot, or link to a repository

<TextInput
        style={styles.input}
        onChangeText={onChangeText}
        value={text}
        textContentType="streetAddressLine2"
      />

 <TextInput
        style={styles.input}
        onChangeText={onChangeText}
        value={text}
        textContentType="organizationName"
    />

**Comment by fabriziobertoglio1987** [comment]
Do you still experience this issue? 

I have four years of experience maintaining facebook/react-native and I specialize in the Text and TextInput components. I currently have 58 [facebook/react-native PRs](https://github.com/facebook/react-native/pulls?q=is%3Apr+author%3Afabriziobertoglio1987+). 

If you still experience this issue, I will prepare a patched release with the fix.

Thanks a lot

**Comment by riti123gupta** [comment]
HI @fabOnReact  this issue still exist with react-native ,I have opened this issue here [https://github.com/facebook/react-native/issues/42764](url) .can u please check it .thanks

**Comment by keshavvarma** [comment]
hey @fabOnReact is there any update on this. I am facing same issue now.
