### ISSUE TITLE
onChangeText is working automatically  in the app built in rosetta mode when keyboard closes.

### ISSUE THREAD

**Issue by rifad4u** [facebook/react-native#37478]
### Description

onChangeText of TextInput is working automatically when keyboard closes in rosetta mode. but there is no issue when built the app in apple silicon mode.

### React Native Version

0.71.8

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M2
    Memory: 104.89 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 14.21.3 - /opt/homebrew/bin/node
    Yarn: Not Found
    npm: 6.14.18 - /opt/homebrew/bin/npm
    Watchman: 2023.03.13.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK:
      API Levels: 27, 28, 29, 30, 31, 32, 33
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 33.0.0, 33.0.2
      System Images: android-27 | Google APIs ARM 64 v8a, android-27 | Google Play Intel x86 Atom, android-29 | Google APIs ARM 64 v8a, android-29 | Google Play ARM 64 v8a, android-30 | Google Play ARM 64 v8a, android-32 | Google Play ARM 64 v8a, android-33 | Google APIs ARM 64 v8a, android-33 | Google Play ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.9971841
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.18 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.8 => 0.71.8 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

I have provided the github link below.
Steps to reproduce the issue.
1. Clone the project.
2. Open the xcworkspace in Xcode
3. Click on Product --> Destination --> Destination Architectures -- > select Show Rosetta Destination.
4. Run the application.
5. Type something in the input field.
6. Click on the return button
7. Check the metro bundler , you can see text came twice.

https://github.com/facebook/react-native/assets/37132763/bb394835-2348-46d0-9009-42354f163dbd

### Snack, code example, screenshot, or link to a repository

https://github.com/rifad4u/TextInputIssue.git

**Comment by ChenAndKai** [comment]
same issue

**Comment by kkoudev** [comment]
same issue.
Probably, it is thought that it is the cause of the following modifications from v0.71.8.
https://github.com/facebook/react-native/commit/a804c0f22b4b11b3d9632dc59a6da14f6c4325e3

**Comment by fabriziobertoglio1987** [comment]
Do you still experience this issue? 

I have four years of experience maintaining facebook/react-native and I specialize in the Text and TextInput components. I currently have 58 [facebook/react-native PRs](https://github.com/facebook/react-native/pulls?q=is%3Apr+author%3Afabriziobertoglio1987+). 

If you still experience this issue, I will prepare a patched release with the fix.

Thanks a lot
