### ISSUE TITLE
ERROR:R8: java.lang.ArrayIndexOutOfBoundsException: Index 91 out of bounds for length 30

### ISSUE THREAD

**Issue by ShaoGongBra** [facebook/react-native#37480]
### Description

> Task :app:minifyReleaseWithR8 FAILED
ERROR:R8: java.lang.ArrayIndexOutOfBoundsException: Index 91 out of bounds for length 30
w: Detected multiple Kotlin daemon sessions at build/kotlin/sessions

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:minifyReleaseWithR8'.
> com.android.tools.r8.CompilationFailedException: Compilation failed to complete

### React Native Version

0.68.5

### Output of `npx react-native info`

System:
    OS: macOS 13.3.1
    CPU: (16) x64 Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
    Memory: 2.33 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.14.2 - /var/folders/5j/t9hd6v1d3s902h5xb3g1rmv40000gn/T/yarn--1684404269037-0.21723990340083832/node
    Yarn: 1.22.18 - /var/folders/5j/t9hd6v1d3s902h5xb3g1rmv40000gn/T/yarn--1684404269037-0.21723990340083832/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.2 => 17.0.2 
    react-native: ^0.68.5 => 0.68.5 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

build error

### Snack, code example, screenshot, or link to a repository

![WX20230518-180541](https://github.com/facebook/react-native/assets/31879769/0c599b4d-8baa-42cc-b7f9-7b6e1123babe)

**Comment by cortinico** [comment]
Please try to `cd android && ./gradlew --stop` and try to build again.
You most likely have some stale compilation daemon which is causing this.

**Comment by ShaoGongBra** [comment]
This doesn't seem to work. I can't even delete the project, reload it, or restart the computer @cortinico

**Comment by ShaoGongBra** [comment]
Not long ago, I was able to package normally, but yesterday it was not working. The 0.70 project was still working properly, and the 0.68 project was not working properly. I suspect it may be due to some library update

**Comment by cortinico** [comment]
> I can't even delete the project, reload it, or restart the computer @cortinico

Can you share more information on what are the error messages?
