### ISSUE TITLE
DrawerLayoutAndroid background overlay issues

### ISSUE THREAD

**Issue by KirubaGhoshak** [facebook/react-native#37495]
### Description

DrawerLayoutAndroid functions properly without the need for any routing or navigation library. However, when incorporating a navigation library to enable screen switching and utilizing the drawer, certain overlay issues arise.

### React Native Version

0.71.8

### Output of `npx react-native info`

  System:
    OS: macOS 12.5
    CPU: (8) arm64 Apple M2
    Memory: 116.64 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.6.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - ~/Documents/ghoshak_app/node_modules/.bin/yarn
    npm: 9.4.0 - /opt/homebrew/bin/npm
    Watchman: 2023.02.13.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK: Not Found
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: ^0.71.3 => 0.71.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

- Click the navigate to profile screen.

- Go back to the home screen.

- And clicking the open drawer.

![WhatsApp Image 2023-05-19 at 11 42 21 PM](https://github.com/facebook/react-native/assets/122986899/0697a39b-129a-41a1-8d14-c4ba44b419f6)

### Snack, code example, screenshot, or link to a repository

https://snack.expo.dev/@kiruba26/drawerlayoutandroid-component-example

**Comment by KirubaGhoshak** [comment]
the issue exists in the latest version also

**Comment by Gregoirevda** [comment]
```js
function Drawer({children, ...}) { 
  const isFocused = useIsFocused();

  return <DrawerLayoutAndroid  key={isFocused}
}
```
Solves it, but adding a `visible` prop would probably solve this problem in a better way

**Comment by sadeghte** [comment]
I have same problem:

System:
  OS: Linux 6.11 Ubuntu 24.04 LTS 24.04 LTS (Noble Numbat)
Binaries:
  Node:
    version: 22.19.0
  Yarn:
    version: 1.22.22
  npm:
    version: 10.9.3
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
IDEs:
  Android Studio: AI-251.27812.49.2514.14217341
npmPackages:
  "@react-native-community/cli":
    installed: 20.0.0
    wanted: 20.0.0
  react:
    installed: 19.1.0
    wanted: 19.1.0
  react-native:
    installed: 0.81.1
    wanted: 0.81.1

![Image](https://github.com/user-attachments/assets/55c358a3-6f3a-4658-b599-0d460bb7eec3)
