### ISSUE TITLE
Cannot compile react native project 0.64.2 after upgrading to xcode 14 and macos ventura

### ISSUE THREAD

**Issue by Tudor16c** [facebook/react-native#37491]
### Description

I have made an app 8 months ago and everything was working perfectly, recently i got a new Macbook pro and I can only install Xcode 14 on it and i cannot compile my app anymore. I don't want to update to 0.71.8 because is breaking too many things on my app. 

The Error i get is this

`warning: Run script build phase 'Bundle React Native code and images' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'MyApp' from project 'MyApp')
warning: Run script build phase 'Start Packager' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'MyApp' from project 'MyApp')
/Users/tudor/Documents/GitHub/MyApp/ios/MyApp.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.4.99. (in target 'MyApp' from project 'MyApp')`

and this one 
`fatal error: module map file '/Users/tudor/Library/Developer/Xcode/DerivedData/MyApp-ccbdugiatqfbkcfmewioiplthzjb/Build/Products/Debug-iphonesimulator/YogaKit/YogaKit.modulemap' not found`

### React Native Version

0.64.2

### Output of `npx react-native info`

System:
    OS: macOS 13.2.1
    CPU: (12) arm64 Apple M2 Pro
    Memory: 247.36 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.1.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 7.11.2 - /opt/homebrew/bin/npm
    Watchman: 4.9.0 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.9 => 0.69.9 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

xcode -> build or  npx react-native run-ios --simulator='iPhone 14 Pro'

### Snack, code example, screenshot, or link to a repository

-

**Comment by zhuiye** [comment]
i also use m2/mini run my rn0.67.5 project in xcode14.3 ,the same error. then i set the follow code in  podfile .it can work ,hope can help you 
```
   installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end  
```
this is relation question `https://github.com/facebook/react-native/issues/28503#issuecomment-1125975278`

**Comment by emmbyiringiro** [comment]
With Xcode 14.3, you can either target the simulator with  Rosetta or ARM64 architecture.

Targeting the simulator with Rosetta should fix the issue.
<img width="278" alt="Screenshot 2023-05-22 at 00 15 57" src="https://github.com/facebook/react-native/assets/46843540/0c0e1899-8643-40f3-887f-1a83befee9bf">
