### ISSUE TITLE
requiring npm modules fails

### ISSUE THREAD

**Issue by markthethomas** [facebook/react-native#375]
Was hoping to try out using something like request or superagent (as suggested in docs) to handle network calls, but when I `npm install -S` them, I get `requiring unknown module [MODULE_NAME]` for both superagent and request. Could it be that the deps for each `require`d module aren't being recursively looked at? Is this expected behavior And, furthermore, is there a best way to go about `requiring` modules for React-Native specifically that would differ from a more straightforward/typical JS use-case?

example thrown error for `require('request')` or related npm modules
![tbhp8x_qovrt0mo09jvfjsy8fcz4knf4jnwcpxcxotm](https://cloud.githubusercontent.com/assets/4926721/6878914/32488ab4-d4a4-11e4-9231-792d68ab1ad8.png)

**Comment by aackerman** [comment]
For this specific case you'll likely want to use the `fetch` API which is provided by the environment. React Native does not run inside of the `node` runtime.

**Comment by markthethomas** [comment]
Yeah, had a major "doh" moment after posting. But superagent and most browser friendly modules should work, no?

**Comment by chetstone** [comment]
I'm having this issue trying to require fluxxor. After doing `npm install fluxxor`

![untitled](https://cloud.githubusercontent.com/assets/976343/6883661/d9a48266-d57d-11e4-82f3-4105b4ba5530.png)

**Comment by isikfsc** [comment]
What? Isn't it supoorted to use ordinary npm modules şna  react native project by simply npm installing.
For example npm install socket.io.

**Comment by markthethomas** [comment]
It is, but not the ones that rely on a node runtime environment.

**Comment by isikfsc** [comment]
Huh! Thanks, I am really relaxed, serious.

**Comment by isikfsc** [comment]
What was the problem when you were installing superagent or request?

**Comment by niftylettuce** [comment]
Was this resolved?

**Comment by maluramichael** [comment]
@markthethomas then how do i use other modules like lodash or xml2js?

**Comment by SudoPlz** [comment]
@isikfsc The problem when I installed `request` was that it used dependencies like `require('os')` or `require('crypto')` that were simply not there, since the environment was not a node environment.
