### ISSUE TITLE
ellipsizeMode="middle" with letterSpacing on Android

### ISSUE THREAD

**Issue by pwltr** [facebook/react-native#37511]
### Description

When using `<Text numberOfLines={1} ellipsizeMode="middle" />` with text using `letterSpacing` !== 0 there is additional space after the ellipsis on Android.

**Expected behavior (iOS):**
<img width="280" alt="Screenshot 2023-05-22 at 14 56 26" src="https://github.com/facebook/react-native/assets/8538369/7fa8777a-ece4-4905-a708-476944b3e4c1">

**Actual behavior (Android):**
<img width="280" alt="Screenshot 2023-05-22 at 14 54 14" src="https://github.com/facebook/react-native/assets/8538369/c7f0fb04-2383-46e2-87c5-7a1da275d90e">

### React Native Version

0.71.8

### Output of `npx react-native info`

```
System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 49.06 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.1/bin/npm
    Watchman: 2023.05.08.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.9862592
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.19 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.7 => 0.71.7 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

```js
import React, {useState} from 'react';
import {Text, StyleSheet} from 'react-native';

const text = 'long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text '

const Example = () => {
  return <Text style={styles.text} numberOfLines={1} ellipsizeMode="middle">{text}</Text>;
};

const styles = StyleSheet.create({
  text: {
    letterSpacing: 0.4,
    marginTop: 50,
  },
});

export default Example;
```

### Snack, code example, screenshot, or link to a repository

https://snack.expo.dev/Q7xRONoVS

**Comment by BeeMargarida** [comment]
I'm currently investigating this issue. My findings so far:
It's reproducible in a native Android app when we have a similar setup (`AppCompatTextView` with ellipsize Middle and letter spacing of `0.05F`) but only if we use `textView.setSingleLine();`, if we remove this line and only use `textView.setMaxLines(1);`, it works correctly.
From what I gather, react-native is not using `setSingleLine` so I'm searching for the root cause of the behaviour and if there's anything that be causing this as well

**Comment by pwltr** [comment]
Still an issue with `0.73.1`.

**Comment by fabriziobertoglio1987** [comment]
Do you still experience this issue? 

I have four years of experience maintaining facebook/react-native and I specialize in the Text and TextInput components. I currently have 58 [facebook/react-native PRs](https://github.com/facebook/react-native/pulls?q=is%3Apr+author%3Afabriziobertoglio1987+). 

If you still experience this issue, I will prepare a patched release with the fix.

Thanks a lot
