### ISSUE TITLE
Navigator.NavigationBar does not call the ref callback

### ISSUE THREAD

**Issue by despairblue** [facebook/react-native#3752]
As mentioned [here](https://github.com/facebook/react-native/issues/3005#issuecomment-151921137), it's not possible to get a reference to the NavigationBar, as the callback is never called.

I adapted the NavBar Example in the UIExplorer [here](https://gist.github.com/despairblue/1f46df10020cc4a7c6c5). I added a ref callback to the Navigator and the NavigationBar. The one for the Navigator is called, the one for the NavigationBar isn't.

I'm trying to hide and show the navigation bar on demand, but that is impossible without a ref to it.

**Comment by ide** [comment]
If you change https://github.com/facebook/react-native/blob/master/Libraries/CustomComponents/Navigator/Navigator.js#L1075 to use something like https://github.com/ide/react-native-clone-referenced-element it will honor the ref you pass in.

**Comment by despairblue** [comment]
Already made a PR. Hope the way I did it is also ok.

**Comment by christopherdro** [comment]
@facebook-github-bot answered
