### ISSUE TITLE
WebSocket.binaryType should be set to `"blob"` by default

### ISSUE THREAD

**Issue by jeremymeng** [facebook/react-native#37524]
### Description

After creating a `WebSocket` instance, its `binaryType` is undefined. This is different from the web spec

> Each [WebSocket](https://websockets.spec.whatwg.org/#websocket) object has an associated binary type, which is a [BinaryType](https://websockets.spec.whatwg.org/#enumdef-binarytype). Initially it must be "[blob](https://websockets.spec.whatwg.org/#dom-binarytype-blob)".

### React Native Version

0.71.8

### Output of `npx react-native info`

System:
    OS: Linux 6.2 Arch Linux
    CPU: (8) x64 Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
    Memory: 23.18 GB / 31.11 GB
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.16.0/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: AI-222.4459.24.2221.9971841
  Languages:
    Java: 17.0.7 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.8 => 0.71.8
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. `npx react-native@latest init AwesomeProject`
2. Add a line `const ws = new WebSocket("wss://reactnative.dev/");` in `App()` function in App.tsx
3. Replace the text value of Step One section with 
```
          <Section title="Step One">
            <Text style={styles.highlight}>App.tsx </Text>{ws.binaryType || "<binaryType undefined>"}
          </Section>
```
4. run the app on Android

### Snack, code example, screenshot, or link to a repository

https://snack.expo.dev/@jeremymeng/laughing-popsicle

**Comment by cortinico** [comment]
This is a valid report, are you up for sending a PR here to fix this:

https://github.com/facebook/react-native/blob/d470dee0c53993cf0c46e50d3594da6738a87f69/packages/react-native/Libraries/WebSocket/WebSocket.js#L71-L85

**Comment by jeremymeng** [comment]
sure! I will give it a try.

**Comment by jeremymeng** [comment]
PR https://github.com/facebook/react-native/pull/37529
