### ISSUE TITLE
console.clear() make app crash on IOS in release mode

### ISSUE THREAD

**Issue by alainib** [facebook/react-native#37532]
### Description

console.clear() make app crash on IOS in release mode
even with Error-boundary

log was not helpfull at all 

"react-native": "0.71.4",

### React Native Version

 0.71.4

### Output of `npx react-native info`

System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M2 Pro
    Memory: 58.81 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 19.8.1 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.5.1 - /opt/homebrew/bin/npm
    Watchman: 2023.03.27.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9619390
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.18 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.4 => 0.71.4
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

put console.clear() and run release mode 

npx react-native run-ios --mode Release

### Snack, code example, screenshot, or link to a repository

<img width="812" alt="Capture d’écran 2023-05-23 à 10 11 50" src="https://github.com/facebook/react-native/assets/7910081/782722a3-9a4a-4023-8b20-7c9afe152fed">

**Comment by blakef** [comment]
`console.clear` isn't supported, see the [Javascript Environment Polyfills](https://reactnative.dev/docs/javascript-environment#polyfills) for the full list:

> [console.{log, warn, error, info, trace, table, group, groupEnd}](https://developer.chrome.com/devtools/docs/console-api)

If you don't want to track these platform "quirks" yourself, using [TypeScript would have prevented this](https://github.com/facebook/react-native/blob/03f70bf995379f08a77abcf96bb0e31ff75ca8c3/packages/react-native/types/index.d.ts#L174-L189).

**Comment by alainib** [comment]
sorry but how to use Console polyfill ? 
i had new error about undefined console.info ( declared in package i use )
