### ISSUE TITLE
Concurrency is only available in iOS 15.0.0 or newer

### ISSUE THREAD

**Issue by renanbronchart** [facebook/react-native#37544]
### New Version

0.71.8

### Old Version

0.68.7

### Build Target(s)

iiOS Simulator in dev

### Output of `react-native info`

System:
    OS: macOS 12.6.5
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 42.54 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 18.16.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 9.5.1 - /usr/local/bin/npm
    Watchman: 2023.05.22.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /Users/renanbronchart/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 26, 27, 28, 29, 30, 31, 32, 33
      Build Tools: 28.0.3, 29.0.2, 30.0.0, 30.0.2, 30.0.3, 31.0.0, 31.0.0, 32.0.0, 33.0.0, 33.0.1, 34.0.0
      System Images: android-26 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.8 => 0.71.8 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Issue and Reproduction Steps

I can't build and launch my project in development after upgrading at new latest version 0.71.8.
I have react-native-stripe ( module stripe-react-native twiith he latest verrsio too)
I see this error when II run `yarn react-native run-ios`:

```
** BUILD FAILED **


The following build commands failed:
        CompileC /Users/renanbronchart/Library/Developer/Xcode/DerivedData/wenoseapp-bzderrvvyrhuobbzaqcrujulwywv/Build/Intermediates.noindex/wenose.build/Debug-iphonesimulator/wenoseapp.build/Objects-normal/x86_64/AppDelegate.o /Users/renanbronchart/sites/wenose/wenose-app/ios/wenoseapp/AppDelegate.mm normal x86_64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'wenoseapp' from project 'wenose')
(1 failure)
]

Node.js v18.16.0
error Command failed with exit code 
```

**Comment by cortinico** [comment]
> I have react-native-stripe ( module stripe-react-native twiith he latest verrsio too)

Hi,
Thanks for reporting this issue.

It seems like this issue is actually unrelated to React Native core but related to react-native-stripe. Please open this issue against this other repository:

https://github.com/stripe/stripe-react-native/issues

I'll be closing this but feel free to reopen if the other repo points back to us as a issue in the core of React Native.

**Comment by renanbronchart** [comment]
Thanks for your answer @cortinico , but the problem comes with the update of react-native from 0.68 to 0.71. 
So maybe it's a shared problem don't you think?

**Comment by cortinico** [comment]
> So maybe it's a shared problem don't you think?

That can very much be, but we can't offer support for every possible library combination in the ecosystem. As you mentioned you're with `stripe-react-native`, please report the issue to them and verify that their library works with 0.71.

If it works, please create a reproduce and open a new issue.
