### ISSUE TITLE
`transform` style property missing `string` type

### ISSUE THREAD

**Issue by nmccrea** [facebook/react-native#37543]
### Description

As part of [the incredible effort to move RN APIs towards web APIs](https://github.com/facebook/react-native/issues/34425), the `transform` style property [was updated to support strings](https://github.com/facebook/react-native/commit/34db2d4e939cab4c37e5a8e6ec95800cce227c98). However, the `string` type [has not been added for this property](https://github.com/facebook/react-native/blob/671ea383fe45dd9834a0c0481360de050df7f0c9/packages/react-native/Libraries/StyleSheet/StyleSheetTypes.d.ts#L176).

`react-native-web` has now [deprecated all other forms of this prop](https://github.com/necolas/react-native-web/pull/2377/commits/831f59e003203854b0320656bbfca418e29fac3e), so using the old array syntax produces a console warning:

<img width="812" alt="Screenshot 2023-05-23 at 12 31 37 PM" src="https://github.com/facebook/react-native/assets/459954/e627ef08-fc12-4c38-852a-62dcef3755d3">

But updating the syntax produces a type error:

<img width="760" alt="Screenshot 2023-05-23 at 12 32 50 PM" src="https://github.com/facebook/react-native/assets/459954/d89f726c-0440-4b2a-b746-24f20e4b1699">

### React Native Version

0.71.6

### Output of `npx react-native info`

```
System:
  Binaries:
    Node: 18.6.0 - ~/.nvm/versions/node/v18.6.0/bin/node
    Yarn: Not Found
    npm: 9.1.2 - ~/.nvm/versions/node/v18.6.0/bin/npm
    Watchman: 2022.11.14.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8309675
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: ^0.71.6 => 0.71.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

Use the string syntax for the `transform` style property in a TypeScript project.

### Snack, code example, screenshot, or link to a repository

Attached above

**Comment by Pranav-yadav** [comment]
Thanks for reporting this @nmccrea 🙏
The PR with fix has been submitted [PR#37569](https://github.com/facebook/react-native/pull/37569) and will be merged soon.
Hope this helps. If any other concerns please let us know. 😃
