### ISSUE TITLE
Insecure Pseudo-Random Number Generator Used

### ISSUE THREAD

**Issue by DJDeth** [facebook/react-native#37583]
### Description

A security vulnerability was discovered in React Native Core during a recent penetration test. Although the React application itself did not utilize arc4random(), it was observed that this function is employed within React Native Core. Supporting evidence in the form of screenshots is provided below:

![image004](https://github.com/facebook/react-native/assets/16957567/c090ce05-1324-47ff-ba71-a5c331259b62)
![image003](https://github.com/facebook/react-native/assets/16957567/5266dc99-3cc9-437e-8d0b-eb37ca63fc98)

We kindly request the security team to conduct a comprehensive evaluation of the vulnerability, assessing its potential risks, impact and if we should be worried about it. Your attention to this matter is greatly appreciated, and we eagerly await your prompt response.

### React Native Version

0.68.2

### Output of `npx react-native info`

System:
    OS: macOS 13.3.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Memory: 41.79 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 18.10.0 - ~/.nvm/versions/node/v18.10.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.10.0/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.10.0/bin/npm
    Watchman: 2023.05.15.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.2 => 0.68.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Penetration testing

### Snack, code example, screenshot, or link to a repository

-

**Comment by DJDeth** [comment]
This function is still appearing in a freshly generated project (RN 0.71.8)

**Comment by cortinico** [comment]
For Security issues, please use our Security disclosure process so that this can get properly prioritized: https://reactnative.dev/contributing/overview#security-bugs
