### ISSUE TITLE
[TabBarIOS] Translucent property not working properly

### ISSUE THREAD

**Issue by anneunjungkim** [facebook/react-native#3758]
Even when the translucent boolean of TabBarIOS is set to false, the tab bar still covers the main view.
For example, the end of the tableview is covered by the tab bar in the screen shot below.

![tabbarios](https://cloud.githubusercontent.com/assets/8837544/10808782/455e4970-7dac-11e5-9d3f-8974e517f65b.jpg)

**Comment by ffxsam** [comment]
+1, I noticed this too.

**Comment by h3l** [comment]
+1

**Comment by jedt** [comment]
This only happens if you set the barTintColor to a color. Remove the property then set the translucent={true} to make it translucent


How to correctly set a translucent TabBarIOS:

```
<TabBarIOS
          tintColor='#222222'
          translucent={true}
        >
...
</TabBarIOS
```

**Comment by christopherdro** [comment]
@jedt Thanks!

**Comment by ffxsam** [comment]
Using `tintColor` instead of `barTintColor` made no difference. The TabBar is still not translucent.
