### ISSUE TITLE
[iOS] Have a back-swipe option setting as prop? 

### ISSUE THREAD

**Issue by djchie** [facebook/react-native#3759]
I was looking around to disable the back-swipe in the NavigationController and I was able to do that in RCTNavigator.m on line 384 via interactivePopGestureRecognizer. I was thinking though that it'd be great if this option could be set on the JS side. Maybe set it'd be great to set it up as a prop in the component? Let me know what you guys think!

**Comment by cancan101** [comment]
Set gestures to `null`: https://github.com/facebook/react-native/blob/62e8ddc20561a39c3c839ab9f83c95493df117c0/Libraries/CustomComponents/Navigator/NavigatorSceneConfigs.js#L525-L531
