### ISSUE TITLE
App Crash on open

### ISSUE THREAD

**Issue by mohitarora777** [facebook/react-native#37607]
### Description

Fatal Exception: com.facebook.jni.CppException: facebook::react::Recoverable: Could not open file/data/user/0/in.mohalla.video/files/CodePush/4adb53238f96cb818fe4edd33d9ae00c8750c2186a87cadd2a51c0bd6f14669d/data/data/in.mohalla.video/files/CodePush/unzipped/CodePush/index.android.bundle: No such file or directory
       at com.facebook.react.bridge.CatalystInstanceImpl.jniLoadScriptFromFile(CatalystInstanceImpl.java)
       at com.facebook.react.bridge.CatalystInstanceImpl.loadScriptFromFile(CatalystInstanceImpl.java:245)
       at com.facebook.react.bridge.JSBundleLoader$2.loadScript(JSBundleLoader.java:48)
       at com.facebook.react.bridge.CatalystInstanceImpl.runJSBundle(CatalystInstanceImpl.java:268)
       at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1371)
       at com.facebook.react.ReactInstanceManager.access$1100(ReactInstanceManager.java:136)
       at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1065)
       at java.lang.Thread.run(Thread.java:923)

### React Native Version

0.71.7

### Output of `npx react-native info`

System:
    OS: macOS 13.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 2.77 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.1.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.6.4 - /opt/homebrew/bin/npm
    Watchman: 2023.05.08.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.3 => 0.66.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

App Crashes as soon as u open it. Not able to reproduce though but it is being reported in Crashlytics and had been happening in 0.66.3 also. I recently upgraded to 0.71.7, but still hapening

### Snack, code example, screenshot, or link to a repository

<img width="1422" alt="Screenshot 2023-05-28 at 3 25 47 AM" src="https://github.com/facebook/react-native/assets/107910744/0ec5526a-ac35-45a8-9af8-8c72cb3cf05e">

**Comment by cortinico** [comment]
> file/data/user/0/in.mohalla.video/files/CodePush/4adb53238f96cb818fe4edd33d9ae00c8750c2186a87cadd2a51c0bd6f14669d/data/data/in.mohalla.video/files/CodePush/unzipped/CodePush/index.android.bundle: No such file or directory

That's an issue with CodePush

Hi @mohitarora777 
Thanks for reporting this issue.

It seems like this issue is actually unrelated to React Native core but related to Microsoft's CodePush. Please open this issue against this other repository:

https://github.com/microsoft/code-push/issues 

I'll be closing this but feel free to reopen if the other repo points back to us as a issue in the core of React Native.

**Comment by arpit203** [comment]
hi was there any resolution to this issue @mohitarora777  ? Getting the same crash
