### ISSUE TITLE
Integration into exist IOS project will be crash with error EXC_BAD_ACCESS (code=EXC_I386_GPFLT)  in RCTUtils

### ISSUE THREAD

**Issue by carl1990** [facebook/react-native#3761]
I Integration into exist IOS project by pods `pod 'React', '~> 0.13.0-rc'`

then add a react page according to this page  

http://facebook.github.io/react-native/docs/embedded-app-ios.html#content

when I open this page, app will crash,

this error info is `EXC_BAD_ACCESS (code=EXC_I386_GPFLT)`

happen error code in RCTUtils.m this method

	NSString *RCTJSONStringify(id jsonObject, NSError **error)
	{
  	static SEL JSONKitSelector = NULL;
  	static NSSet *collectionTypes;
  	static dispatch_once_t onceToken;
  	dispatch_once(&onceToken, ^{
    SEL selector = NSSelectorFromString(@"JSONStringWithOptions:error:");
    if ([NSDictionary instancesRespondToSelector:selector]) {
      JSONKitSelector = selector;
      collectionTypes = [NSSet setWithObjects:
                         [NSArray class], [NSMutableArray class],
                         [NSDictionary class], [NSMutableDictionar class], nil];
    }
  	});

  	// Use JSONKit if available and object is not a fragment
 	 if (JSONKitSelector && [collectionTypes containsObject:[jsonObject classForCoder]]) {
    return ((NSString *(*)(id, SEL, int, NSError **))objc_msgSend)(jsonObject, JSONKitSelector, 0, error);  
  	}

  	// Use Foundation JSON method
 	 NSData *jsonData = [NSJSONSerialization
                      dataWithJSONObject:jsonObject
                      options:		(NSJSONWritingOptions)NSJSONReadingAllowFragments
                      error:error];
  	return jsonData ? [[NSString alloc] initWithData:jsonData 	encoding:NSUTF8StringEncoding] : nil;
	}

in this line :

 `return ((NSString *(*)(id, SEL, int, NSError **))objc_msgSend)(jsonObject, JSONKitSelector, 0, error); `

How can I resovle this issue? I was very anxious, please help me to solve this problem

**Comment by carl1990** [comment]
I debug this method it jsonobject is:<br>
	
	{
    remoteModuleConfig =     {
        RCTAccessibilityManager =         {
            methods =             {
                getCurrentVoiceOverState =                 {
                    methodID = 2;
                    type = remote;
                };
                getMultiplier =                 {
                    methodID = 1;
                    type = remote;
                };
                setAccessibilityContentSizeMultipliers =                 {
                    methodID = 0;
                    type = remote;
                };
            };
            moduleID = 19;
        };
        RCTActivityIndicatorViewManager =         {
            methods =             {
            };
            moduleID = 21;
        };
        RCTAlertManager =         {
            methods =             {
                alertWithArgs =                 {
                    methodID = 0;
                    type = remote;
                };
            };
            moduleID = 15;
        };
        RCTAppState =         {
            methods =             {
                getCurrentAppState =                 {
                    methodID = 0;
                    type = remote;
                };
            };
            moduleID = 1;
        };
        RCTAsyncLocalStorage =         {
            methods =             {
                clear =                 {
                    methodID = 4;
                    type = remote;
                };
                getAllKeys =                 {
                    methodID = 5;
                    type = remote;
                };
                multiGet =                 {
                    methodID = 0;
                    type = remote;
                };
                multiMerge =                 {
                    methodID = 2;
                    type = remote;
                };
                multiRemove =                 {
                    methodID = 3;
                    type = remote;
                };
                multiSet =                 {
                    methodID = 1;
                    type = remote;
                };
            };
            moduleID = 16;
        };
        RCTContextExecutor =         {
            methods =             {
                setContextName =                 {
                    methodID = 0;
                    type = remote;
                };
            };
            moduleID = 0;
        };
        RCTDatePickerManager =         {
            constants =             {
                ComponentHeight = 216;
                ComponentWidth = 320;
            };
            methods =             {
            };
            moduleID = 32;
        };
        RCTDevLoadingView =         {
            methods =             {
            };
            moduleID = 23;
        };
        RCTDevMenu =         {
            methods =             {
                reload =                 {
                    methodID = 1;
                    type = remote;
                };
                show =                 {
                    methodID = 0;
                    type = remote;
                };
            };
            moduleID = 8;
        };
        RCTEventDispatcher =         {
            methods =             {
            };
            moduleID = 2;
        };
        RCTExceptionsManager =         {
            methods =             {
                reportFatalException =                 {
                    methodID = 1;
                    type = remote;
                };
                reportSoftException =                 {
                    methodID = 0;
                    type = remote;
                };
                reportUnhandledException =                 {
                    methodID = 3;
                    type = remote;
                };
                updateExceptionMessage =                 {
                    methodID = 2;
                    type = remote;
                };
            };
            moduleID = 14;
        };
        RCTKeyboardObserver =         {
            methods =             {
            };
            moduleID = 4;
        };
        RCTMapManager =         {
            methods =             {
            };
            moduleID = 24;
        };
        RCTModalHostViewManager =         {
            methods =             {
            };
            moduleID = 29;
        };
        RCTNavItemManager =         {
            methods =             {
            };
            moduleID = 10;
        };
        RCTNavigatorManager =         {
            methods =             {
                requestSchedulingJavaScriptNavigation =                 {
                    methodID = 0;
                    type = remote;
                };
            };
            moduleID = 20;
        };
        RCTPerfStats =         {
            methods =             {
            };
            moduleID = 22;
        };
        RCTPerformanceLogger =         {
            methods =             {
            };
            moduleID = 13;
        };
        RCTPickerManager =         {
            constants =             {
                ComponentHeight = 216;
                ComponentWidth = 320;
            };
            methods =             {
            };
            moduleID = 9;
        };
        RCTProgressViewManager =         {
            constants =             {
                ComponentHeight = 2;
            };
            methods =             {
            };
            moduleID = 6;
        };
        RCTRedBox =         {
            methods =             {
            };
            moduleID = 12;
        };
        RCTScrollViewManager =         {
            constants =             {
                DecelerationRate =                 {
                    fast = "0.99";
                    normal = "0.998";
                };
            };
            methods =             {
                calculateChildFrames =                 {
                    methodID = 1;
                    type = remote;
                };
                getContentSize =                 {
                    methodID = 0;
                    type = remote;
                };
            };
            moduleID = 7;
        };
        RCTSegmentedControlManager =         {
            constants =             {
                ComponentHeight = 28;
            };
            methods =             {
            };
            moduleID = 28;
        };
        RCTSliderManager =         {
            methods =             {
            };
            moduleID = 11;
        };
        RCTSourceCode =         {
            constants =             {
                scriptURL = "file:///Users/carlwei/Library/Developer/CoreSimulator/Devices/1E3571EA-E457-454A-9DBF-427843F78692/data/Containers/Bundle/Application/D0060A7B-C6FD-487A-8204-55BC06BECB21/im4ps-teacher.app/main.jsbundle";
            };
            methods =             {
                getScriptText =                 {
                    methodID = 0;
                    type = remote;
                };
            };
            moduleID = 26;
        };
        RCTStatusBarManager =         {
            methods =             {
                setHidden =                 {
                    methodID = 1;
                    type = remote;
                };
                setNetworkActivityIndicatorVisible =                 {
                    methodID = 2;
                    type = remote;
                };
                setStyle =                 {
                    methodID = 0;
                    type = remote;
                };
            };
            moduleID = 18;
        };
        RCTSwitchManager =         {
            methods =             {
            };
            moduleID = 25;
        };
        RCTTabBarItemManager =         {
            methods =             {
            };
            moduleID = 3;
        };
        RCTTabBarManager =         {
            methods =             {
            };
            moduleID = 30;
        };
        RCTTiming =         {
            methods =             {
                createTimer =                 {
                    methodID = 0;
                    type = remote;
                };
                deleteTimer =                 {
                    methodID = 1;
                    type = remote;
                };
            };
            moduleID = 33;
        };
        RCTUIManager =         {
            constants =             {
                Dimensions =                 {
                    modalFullscreenView =                     {
                        height = 568;
                        width = 320;
                    };
                    window =                     {
                        height = 568;
                        scale = 2;
                        width = 320;
                    };
                };
                RCTActivityIndicatorView =                 {
                    NativeProps =                     {
                        animating = BOOL;
                        color = UIColor;
                        hidesWhenStopped = BOOL;
                        size = UIActivityIndicatorViewStyle;
                    };
                };
                RCTDatePicker =                 {
                    Constants =                     {
                        ComponentHeight = 216;
                        ComponentWidth = 320;
                    };
                    NativeProps =                     {
                        date = NSDate;
                        maximumDate = NSDate;
                        minimumDate = NSDate;
                        minuteInterval = NSInteger;
                        mode = UIDatePickerMode;
                        onChange = BOOL;
                        timeZoneOffsetInMinutes = NSTimeZone;
                    };
                };
                RCTMap =                 {
                    NativeProps =                     {
                        annotations = RCTPointAnnotationArray;
                        legalLabelInsets = UIEdgeInsets;
                        mapType = MKMapType;
                        maxDelta = CGFloat;
                        minDelta = CGFloat;
                        onChange = BOOL;
                        onPress = BOOL;
                        pitchEnabled = BOOL;
                        region = MKCoordinateRegion;
                        rotateEnabled = BOOL;
                        scrollEnabled = BOOL;
                        showsUserLocation = BOOL;
                        zoomEnabled = BOOL;
                    };
                };
                RCTModalHostView =                 {
                    NativeProps =                     {
                        animated = BOOL;
                        transparent = BOOL;
                    };
                };
                RCTNavItem =                 {
                    NativeProps =                     {
                        backButtonIcon = UIImage;
                        backButtonTitle = NSString;
                        barTintColor = UIColor;
                        leftButtonIcon = UIImage;
                        leftButtonTitle = NSString;
                        navigationBarHidden = BOOL;
                        onNavLeftButtonTap = BOOL;
                        onNavRightButtonTap = BOOL;
                        rightButtonIcon = UIImage;
                        rightButtonTitle = NSString;
                        shadowHidden = BOOL;
                        tintColor = UIColor;
                        title = NSString;
                        titleTextColor = UIColor;
                        translucent = BOOL;
                    };
                };
                RCTNavigator =                 {
                    NativeProps =                     {
                        onNavigationComplete = BOOL;
                        onNavigationProgress = BOOL;
                        requestedTopOfStack = NSInteger;
                    };
                };
                RCTPicker =                 {
                    Constants =                     {
                        ComponentHeight = 216;
                        ComponentWidth = 320;
                    };
                    NativeProps =                     {
                        items = NSDictionaryArray;
                        onChange = BOOL;
                        selectedIndex = NSInteger;
                    };
                };
                RCTProgressView =                 {
                    Constants =                     {
                        ComponentHeight = 2;
                    };
                    NativeProps =                     {
                        progress = float;
                        progressImage = UIImage;
                        progressTintColor = UIColor;
                        progressViewStyle = UIProgressViewStyle;
                        trackImage = UIImage;
                        trackTintColor = UIColor;
                    };
                };
                RCTScrollView =                 {
                    Constants =                     {
                        DecelerationRate =                         {
                            fast = "0.99";
                            normal = "0.998";
                        };
                    };
                    NativeProps =                     {
                        alwaysBounceHorizontal = BOOL;
                        alwaysBounceVertical = BOOL;
                        automaticallyAdjustContentInsets = BOOL;
                        bounces = BOOL;
                        bouncesZoom = BOOL;
                        canCancelContentTouches = BOOL;
                        centerContent = BOOL;
                        contentInset = UIEdgeInsets;
                        contentOffset = CGPoint;
                        decelerationRate = CGFloat;
                        directionalLockEnabled = BOOL;
                        keyboardDismissMode = UIScrollViewKeyboardDismissMode;
                        maximumZoomScale = CGFloat;
                        minimumZoomScale = CGFloat;
                        pagingEnabled = BOOL;
                        scrollEnabled = BOOL;
                        scrollEventThrottle = NSTimeInterval;
                        scrollIndicatorInsets = UIEdgeInsets;
                        scrollsToTop = BOOL;
                        showsHorizontalScrollIndicator = BOOL;
                        showsVerticalScrollIndicator = BOOL;
                        snapToAlignment = NSString;
                        snapToInterval = int;
                        stickyHeaderIndices = NSIndexSet;
                        zoomScale = CGFloat;
                    };
                };
                RCTSegmentedControl =                 {
                    Constants =                     {
                        ComponentHeight = 28;
                    };
                    NativeProps =                     {
                        enabled = BOOL;
                        momentary = BOOL;
                        onChange = BOOL;
                        selectedIndex = NSInteger;
                        tintColor = UIColor;
                        values = NSStringArray;
                    };
                };
                RCTSlider =                 {
                    NativeProps =                     {
                        maximumTrackTintColor = UIColor;
                        maximumValue = float;
                        minimumTrackTintColor = UIColor;
                        minimumValue = float;
                        onChange = BOOL;
                        value = float;
                    };
                };
                RCTSwitch =                 {
                    NativeProps =                     {
                        disabled = BOOL;
                        onChange = BOOL;
                        onTintColor = UIColor;
                        thumbTintColor = UIColor;
                        tintColor = UIColor;
                        value = BOOL;
                    };
                };
                RCTTabBar =                 {
                    NativeProps =                     {
                        barTintColor = UIColor;
                        tintColor = UIColor;
                        translucent = BOOL;
                    };
                };
                RCTTabBarItem =                 {
                    NativeProps =                     {
                        badge = NSString;
                        icon = id;
                        onPress = BOOL;
                        selected = BOOL;
                        selectedIcon = UIImage;
                        title = NSString;
                    };
                };
                RCTView =                 {
                    NativeProps =                     {
                        accessibilityLabel = NSString;
                        accessibilityTraits = UIAccessibilityTraits;
                        accessible = BOOL;
                        alignItems = "css_align_t";
                        alignSelf = "css_align_t";
                        backfaceVisibility = "css_backface_visibility_t";
                        backgroundColor = UIColor;
                        borderBottomColor = UIColor;
                        borderBottomLeftRadius = CGFloat;
                        borderBottomRightRadius = CGFloat;
                        borderBottomWidth = CGFloat;
                        borderColor = CGColor;
                        borderLeftColor = UIColor;
                        borderLeftWidth = CGFloat;
                        borderRadius = CGFloat;
                        borderRightColor = UIColor;
                        borderRightWidth = CGFloat;
                        borderTopColor = UIColor;
                        borderTopLeftRadius = CGFloat;
                        borderTopRightRadius = CGFloat;
                        borderTopWidth = CGFloat;
                        borderWidth = CGFloat;
                        bottom = CGFloat;
                        flex = CGFloat;
                        flexDirection = "css_flex_direction_t";
                        flexWrap = "css_wrap_type_t";
                        height = CGFloat;
                        justifyContent = "css_justify_t";
                        left = CGFloat;
                        margin = CGFloat;
                        marginBottom = CGFloat;
                        marginHorizontal = CGFloat;
                        marginLeft = CGFloat;
                        marginRight = CGFloat;
                        marginTop = CGFloat;
                        marginVertical = CGFloat;
                        onAccessibilityTap = BOOL;
                        onLayout = BOOL;
                        onMagicTap = BOOL;
                        opacity = CGFloat;
                        overflow = "css_clip_t";
                        padding = CGFloat;
                        paddingBottom = CGFloat;
                        paddingHorizontal = CGFloat;
                        paddingLeft = CGFloat;
                        paddingRight = CGFloat;
                        paddingTop = CGFloat;
                        paddingVertical = CGFloat;
                        pointerEvents = RCTPointerEvents;
                        position = "css_position_type_t";
                        removeClippedSubviews = BOOL;
                        right = CGFloat;
                        shadowColor = CGColor;
                        shadowOffset = CGSize;
                        shadowOpacity = float;
                        shadowRadius = CGFloat;
                        shouldRasterizeIOS = BOOL;
                        testID = NSString;
                        top = CGFloat;
                        transformMatrix = CATransform3D;
                        width = CGFloat;
                    };
                };
                RCTWebView =                 {
                    Constants =                     {
                        JSNavigationScheme = "react-js-navigation";
                        NavigationType =                         {
                            BackForward = 2;
                            FormResubmitted = 4;
                            FormSubmitted = 1;
                            LinkClicked = 0;
                            Other = 5;
                            Reload = 3;
                        };
                    };
                    NativeProps =                     {
                        automaticallyAdjustContentInsets = BOOL;
                        bounces = BOOL;
                        contentInset = UIEdgeInsets;
                        html = NSString;
                        injectedJavaScript = NSString;
                        onLoadingError = BOOL;
                        onLoadingFinish = BOOL;
                        onLoadingStart = BOOL;
                        scalesPageToFit = BOOL;
                        scrollEnabled = BOOL;
                        url = NSURL;
                    };
                };
                customBubblingEventTypes =                 {
                    topBlur =                     {
                        phasedRegistrationNames =                         {
                            bubbled = onBlur;
                            captured = onBlurCapture;
                        };
                    };
                    topChange =                     {
                        phasedRegistrationNames =                         {
                            bubbled = onChange;
                            captured = onChangeCapture;
                        };
                    };
                    topEndEditing =                     {
                        phasedRegistrationNames =                         {
                            bubbled = onEndEditing;
                            captured = onEndEditingCapture;
                        };
                    };
                    topFocus =                     {
                        phasedRegistrationNames =                         {
                            bubbled = onFocus;
                            captured = onFocusCapture;
                        };
                    };
                    topNavLeftButtonTap =                     {
                        phasedRegistrationNames =                         {
                            bubbled = onNavLeftButtonTap;
                            captured = onNavLeftButtonTapCapture;
                        };
                    };
                    topNavRightButtonTap =                     {
                        phasedRegistrationNames =                         {
                            bubbled = onNavRightButtonTap;
                            captured = onNavRightButtonTapCapture;
                        };
                    };
                    topNavigationComplete =                     {
                        phasedRegistrationNames =                         {
                            bubbled = onNavigationComplete;
                            captured = onNavigationCompleteCapture;
                        };
                    };
                    topPress =                     {
                        phasedRegistrationNames =                         {
                            bubbled = onPress;
                            captured = onPressCapture;
                        };
                    };
                    topSubmitEditing =                     {
                        phasedRegistrationNames =                         {
                            bubbled = onSubmitEditing;
                            captured = onSubmitEditingCapture;
                        };
                    };
                    topTouchCancel =                     {
                        phasedRegistrationNames =                         {
                            bubbled = onTouchCancel;
                            captured = onTouchCancelCapture;
                        };
                    };
                    topTouchEnd =                     {
                        phasedRegistrationNames =                         {
                            bubbled = onTouchEnd;
                            captured = onTouchEndCapture;
                        };
                    };
                    topTouchMove =                     {
                        phasedRegistrationNames =                         {
                            bubbled = onTouchMove;
                            captured = onTouchMoveCapture;
                        };
                    };
                    topTouchStart =                     {
                        phasedRegistrationNames =                         {
                            bubbled = onTouchStart;
                            captured = onTouchStartCapture;
                        };
                    };
                };
                customDirectEventTypes =                 {
                    topAccessibilityTap =                     {
                        registrationName = onAccessibilityTap;
                    };
                    topLayout =                     {
                        registrationName = onLayout;
                    };
                    topLoadingError =                     {
                        registrationName = onLoadingError;
                    };
                    topLoadingFinish =                     {
                        registrationName = onLoadingFinish;
                    };
                    topLoadingStart =                     {
                        registrationName = onLoadingStart;
                    };
                    topMagicTap =                     {
                        registrationName = onMagicTap;
                    };
                    topMomentumScrollBegin =                     {
                        registrationName = onMomentumScrollBegin;
                    };
                    topMomentumScrollEnd =                     {
                        registrationName = onMomentumScrollEnd;
                    };
                    topNavigationProgress =                     {
                        registrationName = onNavigationProgress;
                    };
                    topScroll =                     {
                        registrationName = onScroll;
                    };
                    topScrollAnimationEnd =                     {
                        registrationName = onScrollAnimationEnd;
                    };
                    topScrollBeginDrag =                     {
                        registrationName = onScrollBeginDrag;
                    };
                    topScrollEndDrag =                     {
                        registrationName = onScrollEndDrag;
                    };
                };
            };
            methods =             {
                blur =                 {
                    methodID = 7;
                    type = remote;
                };
                clearJSResponder =                 {
                    methodID = 18;
                    type = remote;
                };
                configureNextLayoutAnimation =                 {
                    methodID = 19;
                    type = remote;
                };
                createView =                 {
                    methodID = 4;
                    type = remote;
                };
                findSubviewIn =                 {
                    methodID = 8;
                    type = remote;
                };
                focus =                 {
                    methodID = 6;
                    type = remote;
                };
                manageChildren =                 {
                    methodID = 3;
                    type = remote;
                };
                measure =                 {
                    methodID = 9;
                    type = remote;
                };
                measureLayout =                 {
                    methodID = 10;
                    type = remote;
                };
                measureLayoutRelativeToParent =                 {
                    methodID = 11;
                    type = remote;
                };
                measureViewsInRect =                 {
                    methodID = 12;
                    type = remote;
                };
                removeRootView =                 {
                    methodID = 1;
                    type = remote;
                };
                removeSubviewsFromContainerWithID =                 {
                    methodID = 0;
                    type = remote;
                };
                replaceExistingNonRootView =                 {
                    methodID = 2;
                    type = remote;
                };
                scrollTo =                 {
                    methodID = 14;
                    type = remote;
                };
                scrollWithoutAnimationTo =                 {
                    methodID = 15;
                    type = remote;
                };
                setJSResponder =                 {
                    methodID = 17;
                    type = remote;
                };
                setMainScrollViewTag =                 {
                    methodID = 13;
                    type = remote;
                };
                updateView =                 {
                    methodID = 5;
                    type = remote;
                };
                zoomToRect =                 {
                    methodID = 16;
                    type = remote;
                };
            };
            moduleID = 31;
        };
        RCTViewManager =         {
            methods =             {
            };
            moduleID = 5;
        };
        RCTWebViewExecutor =         {
            methods =             {
            };
            moduleID = 27;
        };
        RCTWebViewManager =         {
            constants =             {
                JSNavigationScheme = "react-js-navigation";
                NavigationType =                 {
                    BackForward = 2;
                    FormResubmitted = 4;
                    FormSubmitted = 1;
                    LinkClicked = 0;
                    Other = 5;
                    Reload = 3;
                };
            };
            methods =             {
                goBack =                 {
                    methodID = 0;
                    type = remote;
                };
                goForward =                 {
                    methodID = 1;
                    type = remote;
                };
                reload =                 {
                    methodID = 2;
                    type = remote;
                };
            };
            moduleID = 17;
        };
    };
	
	}

**Comment by hite** [comment]
@carl1990 i have same problem. I work around by Commenting 3 lines, and still i don't the reason it crashes.

**Comment by MeganZhou** [comment]
@carl1990 the same as you, how did you solve you issue?  Folllow @hite's solution?

**Comment by MeganZhou** [comment]
update openQQ to a higher version solved the issue.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/integration-into-exist-ios-project-will-be-crash-with-error-excbadaccess-codeexci386gpflt-in-rctutils

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
