### ISSUE TITLE
TextInput - sometimes 'onChangeText' callback doesn't work

### ISSUE THREAD

**Issue by APavlov97** [facebook/react-native#37612]
### Description

I find out that the issue is reproducible in 0.71.8 or higher version of react-native on iOS platform.

### React Native Version

0.71.8

### Output of `npx react-native info`

System:
    OS: macOS 13.0
    CPU: (8) arm64 Apple M1
    Memory: 86.42 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.1.0 - /opt/homebrew/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 8.19.3 - /opt/homebrew/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.12.0 - /Users/antoniopavlov/.gem/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK:
      API Levels: 28, 29, 31, 33
      Build Tools: 29.0.2, 29.0.3, 30.0.3, 31.0.0, 33.0.0
      System Images: android-18 | Google APIs Intel x86 Atom, android-29 | Google APIs ARM 64 v8a, android-29 | Google APIs Intel x86 Atom, android-31 | Google APIs ARM 64 v8a, android-31 | Google APIs Intel x86 Atom_64, android-33 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8815526
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.8 => 0.71.8
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. Render controlled **multiline** 'TextInput'.
2. Press on the button to change input value to '$' and after that delete it. Do this step several times.

### Snack, code example, screenshot, or link to a repository

https://github.com/APavlov97/demo

**Comment by harisbaig100** [comment]
I think that is fixed in this commit

https://github.com/jeongshin/react-native/commit/4d32a342cc7123b679cc9cd8334d65adb62e3997

don't know when it will be released but you can change native code to fix your problem.

**Comment by moriax** [comment]
> I think that is fixed in this commit
> 
> [jeongshin@4d32a34](https://github.com/jeongshin/react-native/commit/4d32a342cc7123b679cc9cd8334d65adb62e3997)
> 
> don't know when it will be released but you can change native code to fix your problem.

yes its broken since this patch.
The OnChange Event for my TextInput used for a Chat Box is not working anylonger.
After reset the text state to '' (after sending a message), the first character is always lost and the onChange event is not fired.

If I add (&& [_lastStringStateWasUpdatedWith isEqual:_backedTextInputView.attributedText]) again back to the code its fixed and working.

**Comment by zcdev02** [comment]
I confirm the issue. Indeed, when using multiline, OnChangeText starts to fire a large number of times. Disabling this setting resolves the issue. 0.72.3 react
