### ISSUE TITLE
Could not find module ... for target 'x86_64-apple-ios-simulator'; found: arm64-apple-ios-simulator,

### ISSUE THREAD

**Issue by solveit-andrey-savich** [facebook/react-native#37627]
### Description

Hello.

## Context
We have RN iOS project with CocoaPods dependecies, but we want to add some dependencies via SPM.
In our Podfile, we have following lines: 
```
 installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
end
```
Without this lines — build fails by different errors from Pods

Right now if we will try to add SPM package to project, we have two scenarios:
- *Option 1* : Rosetta — turn on, project with connected SPM + Pods builds correctly. We don't want to use Rosetta at all
- *Option 2* : Rosetta — turn off, project build with connected SPM + Pods fails with an error `Could not find module PACKAGE NAME for target 'x86_64-apple-ios-simulator'; found: arm64-apple-ios-simulator`

## What we want to achive
We want to be able to add SPM packages to Xcode project, continue to use Pods and don't use Rosetta . Does any one faced with this problem or has some solutions?

### React Native Version

0.7

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 13.1
    CPU: (10) x64 Apple M1 Pro
    Memory: 227.15 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.20.0 - /usr/local/opt/node@16/bin/node
    Yarn: 1.22.11 - ~/Documents/WORK/Breadfast/ReactNative-customer-app/node_modules/.bin/yarn
    npm: 6.14.13 - ~/Documents/WORK/Breadfast/ReactNative-customer-app/node_modules/.bin/npm
    Watchman: 2023.04.10.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

- Xcode project generated by RN tools
- Any SPM package
- Turn off Rosetta on Mac

### Snack, code example, screenshot, or link to a repository

<img width="1331" alt="Screenshot 2023-05-30 at 21 41 51" src="https://github.com/facebook/react-native/assets/85870338/5e9c60ec-4613-4004-b316-e8371d72e541">

**Comment by rvasseur31** [comment]
Hi, you can use this in your podfile :
```
post_install do |installer|
      installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings["ONLY_ACTIVE_ARCH"] = "NO"
        end
      end
end
```
