### ISSUE TITLE
Hi Please help me to solve this issue. I have this issue after the build app on xcode

### ISSUE THREAD

**Issue by Rananjaya** [facebook/react-native#37630]
### Description

I have this issue after the build my react native app in xcode. anyone have this issues please help. Thanks.

![image](https://github.com/facebook/react-native/assets/34897947/48d7bc00-764f-48c6-8bb6-976960128824)

### React Native Version

0.63.4

### Output of `npx react-native info`

System:
    OS: macOS 13.0.1
    CPU: (8) x64 Apple M1
    Memory: 27.29 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
    Watchman: 2023.03.20.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/saniranimantha/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 19.0.1 - /usr/bin/javac
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: ~16.11.0 => 16.11.0 
    react-native: ~0.63.4 => 0.63.5 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

clean the Project and build it in xcode this issues came.

### Snack, code example, screenshot, or link to a repository

![image](https://github.com/facebook/react-native/assets/34897947/5a70335b-e6a9-4acb-92d2-6c690bac1b1b)

**Comment by cortinico** [comment]
Closing as the version of React Native you're building on is too old. Please update to the latest and try again.
