### ISSUE TITLE
Return type of out-of-line definition of 'facebook::react::JSINativeModules::createModule' differs from that in the declaration

### ISSUE THREAD

**Issue by gtokman** [facebook/react-native#37639]
### New Version

0.72.0-rc.4

### Old Version

0.71.8

### Build Target(s)

iOS debug build

### Output of `react-native info`

info Fetching system and libraries information...
System:
  OS: macOS 13.3.1
  CPU: (8) arm64 Apple M1
  Memory: 106.19 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.16.0
    path: ~/.nvm/versions/node/v18.16.0/bin/node
  Yarn:
    version: 1.22.19
    path: ~/.volta/bin/yarn
  npm:
    version: 9.5.1
    path: ~/.nvm/versions/node/v18.16.0/bin/npm
  Watchman:
    version: 2023.03.27.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.0
    path: /Users/gary/.rvm/gems/ruby-2.7.6/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: Dolphin 2021.3.1 Dolphin 2021.3.1
  Xcode:
    version: 14.3/14E222b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.2
    path: /usr/bin/javac
  Ruby:
    version: 2.7.6
    path: /Users/gary/.rvm/rubies/ruby-2.7.6/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.0-rc.4
    wanted: 0.72.0-rc.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

### Issue and Reproduction Steps

Follow the steps to upgrade from the react native upgrade helper.

Run bundle install, pod install, yarn ios

```
Return type of out-of-line definition of 'facebook::react::JSINativeModules::createModule' differs from that in the declaration
```

<img width="1109" alt="CleanShot 2023-05-31 at 11 49 03@2x" src="https://github.com/facebook/react-native/assets/12258850/037b6575-02e6-4f65-9066-c55957e375c2">

**Comment by fortmarek** [comment]
Hey @gtokman 👋 

Thanks a lot for trying `0.72` RC 🙌 The React Native iOS build is tested on CI and it was tested locally, so it might be related to your local setup or project.

Would you able to post reproduction steps or a reproduction project? You might want to try clean your Xcode build, too 🙏

**Comment by gtokman** [comment]
@fortmarek thanks for the response, was an issue with reanimated. I upgraded to 3.2.0 and the error went away.
