### ISSUE TITLE
The react native page is not updated after modification

### ISSUE THREAD

**Issue by aibihub** [facebook/react-native#37631]
### Description

React Native Debugger app version: 0.13.0
React Native version: 0.71.3
Platform: iOS & Android
Is real device of platform: Yes, using a real device
Operating System: mac

**new ，The react native page is not updated after modification.**

### React Native Version

0.71.3

### Output of `npx react-native info`

Input is normal, no problem

### Steps to reproduce

new ，The react native page is not updated after modification，why? I try to used

npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/ && react-native run-android

Although the effect is achieved, I don't want to need such an operation every time I view the modified page. Is there a more elegant solution?

### Snack, code example, screenshot, or link to a repository

import React, { Component } from "react";
import { View, Text } from "react-native";
import { Button } from '@rneui/themed';

class App extends Component {
  render() {
    return (
      <View
        style={{
          flexDirection: "row",
          height: 100,
          padding: 20
        }}
      >
         <Button size="sm">Small</Button>
          <Button size="md">Medium</Button>
          <Button size="lg">Large</Button>

        <View style={{ backgroundColor: "blue", flex: 0.3 }} />
        <View style={{ backgroundColor: "red", flex: 0.5 }} />
        <Text>Hello World!</Text>
      </View>
    );
  }
}

export default App;

**Comment by aibihub** [comment]
I tried with the latest version （"react-native": "0.71.8"）and have the same problem

**Comment by cortinico** [comment]
> npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/ && react-native run-android
> 
> Although the effect is achieved, I don't want to need such an operation every time I view the modified page. Is there a more elegant solution?

You don't need to invoke any external command.
`npm run android` should set up everything for you.

**Comment by amansinghsom** [comment]
problem

**Comment by aibihub** [comment]
> Thank you very much for your help, but I try 
 npx react-native bundle --platform android --dev true

but I still haven't achieved the hot update effect 。

**Comment by cortinico** [comment]
@aibihub can you just run `npx react-native run-android` and provide a video of what you're experiencing please?

**Comment by itsukcode** [comment]
Hey **aibihub** can plzz explain in detail, 
**Ques 1 ** : Have you use Expo go app or Developer build??
**Ques 2 ** : Is your laptop and mobile is connected to same your  wifi or internet connection ??
