### ISSUE TITLE
SyntaxError: Unexpected token '}'. Expected a statement as the body of a for loop.

### ISSUE THREAD

**Issue by oney** [facebook/react-native#3763]
I run `react-native init TestProject` to create a project, then I run the app with iOS and it works fine.
I add `socket.io-client` in my dependencies, and run `npm install`.
```json
"dependencies": {
  "react-native": "^0.13.2",
  "socket.io-client": "^1.3.7"
}
```
And add 
```javascript
window.navigator.userAgent = "react-native";
var io = require('socket.io-client/socket.io');

var TestProject = React.createClass({
...
```
I got
```
SyntaxError: Unexpected token '}'. Expected a statement as the body of a for loop.
```
![image](http://i.imgur.com/UZZvfT9.png)
I use socket.io before, and it works. However, every my React Native project that uses socket.io is broken now. So strange...
Line 60582 of `http://localhost:8081/index.ios.bundle?platform=ios&dev=true` is
```javascript
for(length = members.length;property = members[--length];hasProperty.call(object,property) && callback(property))}}else 
```

It seems that many `;` symbol is gone in my js bundle file.

**Comment by ide** [comment]
I am seeing this too (without socket.io). There is something unexpected happening with the bundled JavaScript -- we should run a parser over it to see if the bundled JS is invalid.

**Comment by ide** [comment]
Looks like the packager could be stripping out newlines that ASI relied on, or perhaps is inserting a closing curly brace before a newline that triggered ASI?

```js
function hmmm() { for (var i = 0; i < 10; i++); }
undefined

function hmmm() { for (var i = 0; i < 10; i++) }
VM262:2 Uncaught SyntaxError: Unexpected token }(…)InjectedScript._evaluateOn @ VM100:875InjectedScript._evaluateAndWrap @ VM100:808InjectedScript.evaluate @ VM100:664
```

**Comment by ide** [comment]
cc @martinbigio any commits come to mind?

**Comment by ntuckerxx** [comment]
I just narrowed this down and came here to report it and found this bug.  My repro steps were just to create a freshly inited project and add socket.io-client, with the corresponding `require()` in my index.ios.js.  The last time I tried this was in 0.4.4, which I think was pre-babel, and it worked then.

**Comment by oney** [comment]
@ide  Thanks for confirming this issue.
Is there any way to temporarily solve the problem?
Use the past react-native version in package.json? Or, downgrade react-native-cli?

**Comment by ntuckerxx** [comment]
I came up with a hacky workaround.  There's this in socket.io.js, line 6395:

```javascript
for (length = members.length; property = members[--length]; hasProperty.call(object, property) && callback(property));
```

Modifying it to include an empty for loop body did the trick.  Looking at the output of the packager, it looks like the transformation caused the semicolons to get stripped from this line and the one immediately following it, and the two following closing braces to get stuck on the same line, resulting in a transformation from:

```javascript
        for( ... );
    };
}
```

to:

```
    for( ... ) }}
```

**Comment by oney** [comment]
@ntuckerxx Thanks, the hack works.
I modify 3 places.
Line 6395, 6624, 6632 in socket.io.js (package version 1.3.7)
make `for( ... );` to `for( ... ){}`

**Comment by martinbigio** [comment]
looks like the problem was fixed on babel 5.8.33.

**Comment by christopherdro** [comment]
I too noticed this issue come up when using socket.io

You shouldn't have to really make any changes. I made sure to update all my dependencies and homebrew (although it might be unrelated) and restarted my computer to get it to disappear.

@oney Are you still having issues?

**Comment by oney** [comment]
No, updating packages solves the problem.
