### ISSUE TITLE
React Native - 0.66.4 application not open in Android 10 devices

### ISSUE THREAD

**Issue by NimeshMadhushka** [facebook/react-native#37654]
### Description

This project is an ongoing project, which is about two years old. The application is working fine on all other devices except in android 10.

### React Native Version

0.66.4

### Output of `npx react-native info`

System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
    Memory: 2.00 GB / 15.84 GB
  Binaries:
    Node: 16.20.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.20.3 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 23, 28, 29, 30, 31, 32, 33
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 33.0.0
      System Images: android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-31 | Google APIs Intel x86 Atom_64, android-33 | Google APIs ARM 64 v8a
      Android NDK: Not Found
    Windows SDK:
      AllowAllTrustedApps: Disabled
  IDEs:
    Android Studio: AI-213.7172.25.2113.9123335
    Visual Studio: Not Found
  Languages:
    Java: 11.0.15
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.66 => 0.66.4 
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

There is no error in the node server or in the build process. Don't know what to do. Only output I was able to get was the Android logs.

### Snack, code example, screenshot, or link to a repository

06-01 13:01:14.789  2653  2653 E QuickstepAppTransitionManagerImpl: getActivityLaunchOptions   iconLoc=Rect(589, 1104 - 757, 1272)
06-01 13:01:14.795  1531  2554 E ANDR-PERF-JNI: com_qualcomm_qtiperformance_native_perf_io_prefetch_start
06-01 13:01:14.802  1848  1864 E ANDR-IOP: io prefetch is disabled
06-01 13:01:14.810  1531  1738 E system_server: Invalid ID 0x00000000.
06-01 13:01:14.822  1531  1736 W ActivityManager: ProcessRecord{5f8e146 0:com.mark8.agent/u0a463}: ART verification disabled
06-01 13:01:14.876 27228 27228 E com.mark8.agen: Unknown bits set in runtime_flags: 0x8000
06-01 13:01:14.900  2653  3524 E LauncherAnimationRunner: onAnimationStart
06-01 13:01:14.900  2653  3524 E LauncherAnimationRunner: onAnimationStart:   mode=0   taskId=98646
06-01 13:01:14.900  2653  3524 E LauncherAnimationRunner: onAnimationStart:   mode=1   taskId=1
06-01 13:01:14.901  2653  2653 E QuickstepAppTransitionManagerImpl: startIconLaunchAnimator:launcherClosing=true   iconLoc=Rect(589, 1104 - 757, 1272)
06-01 13:01:14.901  2653  2653 E QuickstepAppTransitionManagerImpl: startOpeningWindowAnimators:rotation0IconLoc=Rect(589, 1104 - 757, 1272)
06-01 13:01:14.902  2653  2653 E ClipAnimationHelper: updateSourceStack  mSourceInsets=Rect(0, 0 - 0, 130), mSourceStackBounds=Rect(0, 0 - 1080, 2400)
06-01 13:01:14.902  2653  2653 E ClipAnimationHelper: updateHomeStack  mSourceInsets=Rect(0, 0 - 0, 130), mHomeStackBounds=Rect(0, 0 - 1080, 2400)
06-01 13:01:14.902  2653  2653 E ClipAnimationHelper: updateTargetRect  mSourceRect=RectF(0.0, 0.0, 1080.0, 2400.0)   mTargetRect=RectF(0.0, 0.0, 1080.0, 2400.0)   mSourceWindowClipInsets=RectF(0.0, 0.0, 0.0, 0.0)   mHomeStackBounds=Rect(0, 0 - 1080, 2400)   targetRect=Rect(0, 0 - 1080, 2400)
06-01 13:01:14.904  2653  5502 W FloatingIconLayer: getFloatingIconLayer
06-01 13:01:14.904  2653  2653 E QuickstepAppTransitionManagerImpl: startLauncherContentAnimator:isAppOpening=true
06-01 13:01:14.906  2653  5502 W FloatingIconLayer: drawIcon
06-01 13:01:14.928  1531  2554 W AlarmManager: Window length 1383505805502436352ms suspiciously long; limiting to 1 hour
06-01 13:01:14.999  2653  5502 W FloatingIconLayer: release
06-01 13:01:15.049 27228 27228 W Firebase-Messag: type=1400 audit(0.0:69642): avc: denied { read } for name="u:object_r:vendor_default_prop:s0" dev="tmpfs" ino=24642 scontext=u:r:untrusted_app:s0:c207,c257,c512,c768 tcontext=u:object_r:vendor_default_prop:s0 tclass=file permissive=0
06-01 13:01:15.063 27228 27251 E libc    : Access denied finding property "ro.vendor.df.effect.conflict"
06-01 13:01:15.118 27228 27228 W System.err: java.lang.UnsatisfiedLinkError: dlopen failed: library "libjsc.so" not found
06-01 13:01:15.118 27228 27228 W System.err:    at java.lang.Runtime.load0(Runtime.java:938)
06-01 13:01:15.118 27228 27228 W System.err:    at java.lang.System.load(System.java:1631)
06-01 13:01:15.118 27228 27228 W System.err:    at com.facebook.soloader.SoLoader$1.load(SoLoader.java:405)
06-01 13:01:15.118 27228 27228 W System.err:    at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:77)
06-01 13:01:15.118 27228 27228 W System.err:    at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:50)
06-01 13:01:15.118 27228 27228 W System.err:    at com.facebook.soloader.ApplicationSoSource.loadLibrary(ApplicationSoSource.java:89)
06-01 13:01:15.118 27228 27228 W System.err:    at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:860)
06-01 13:01:15.118 27228 27228 W System.err:    at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:740)
06-01 13:01:15.118 27228 27228 W System.err:    at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:654)
06-01 13:01:15.118 27228 27228 W System.err:    at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:634)
06-01 13:01:15.118 27228 27228 W System.err:    at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:582)
06-01 13:01:15.119 27228 27228 W System.err:    at com.facebook.react.ReactInstanceManagerBuilder.getDefaultJSExecutorFactory(ReactInstanceManagerBuilder.java:305)
06-01 13:01:15.119 27228 27228 W System.err:    at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:277)
06-01 13:01:15.119 27228 27228 W System.err:    at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:89)
06-01 13:01:15.119 27228 27228 W System.err:    at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:39)
06-01 13:01:15.119 27228 27228 W System.err:    at com.mark8.agent.MainApplication.onCreate(MainApplication.java:66)
06-01 13:01:15.119 27228 27228 W System.err:    at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1190)
06-01 13:01:15.119 27228 27228 W System.err:    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6582)
06-01 13:01:15.119 27228 27228 W System.err:    at android.app.ActivityThread.access$1400(ActivityThread.java:224)
06-01 13:01:15.119 27228 27228 W System.err:    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1887)
06-01 13:01:15.119 27228 27228 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:107)
06-01 13:01:15.119 27228 27228 W System.err:    at android.os.Looper.loop(Looper.java:224)
06-01 13:01:15.119 27228 27228 W System.err:    at android.app.ActivityThread.main(ActivityThread.java:7562)
06-01 13:01:15.119 27228 27228 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
06-01 13:01:15.119 27228 27228 W System.err:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
06-01 13:01:15.119 27228 27228 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
06-01 13:01:15.119 27228 27228 E SoLoader: couldn't find DSO to load: libjscexecutor.so caused by: dlopen failed: library "libjsc.so" not found result: 0
06-01 13:01:15.137 27228 27256 W com.mark8.agen: Accessing hidden field Lsun/misc/Unsafe;->theUnsafe:Lsun/misc/Unsafe; (greylist, reflection, allowed)
06-01 13:01:15.137 27228 27256 W com.mark8.agen: Accessing hidden method Lsun/misc/Unsafe;->objectFieldOffset(Ljava/lang/reflect/Field;)J (greylist,core-platform-api, linking, allowed)
06-01 13:01:15.137 27228 27256 W com.mark8.agen: Accessing hidden method Lsun/misc/Unsafe;->arrayBaseOffset(Ljava/lang/Class;)I (greylist,core-platform-api, linking, allowed)
06-01 13:01:15.137 27228 27256 W com.mark8.agen: Accessing hidden method Lsun/misc/Unsafe;->arrayIndexScale(Ljava/lang/Class;)I (greylist, linking, allowed)       
06-01 13:01:15.191 27228 27280 W System.err: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_Unwind_Backtrace" referenced by "/data/app/com.mark8.agent-cqncFD5uZr4Ko2n_6Wn_Ng==/lib/arm64/libflipper.so"...
06-01 13:01:15.191 27228 27280 W System.err:    at java.lang.Runtime.load0(Runtime.java:938)
06-01 13:01:15.191 27228 27280 W System.err:    at java.lang.System.load(System.java:1631)
06-01 13:01:15.192 27228 27280 W System.err:    at com.facebook.soloader.SoLoader$1.load(SoLoader.java:405)
06-01 13:01:15.192 27228 27280 W System.err:    at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:77)
06-01 13:01:15.192 27228 27280 W System.err:    at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:50)
06-01 13:01:15.192 27228 27280 W System.err:    at com.facebook.soloader.ApplicationSoSource.loadLibrary(ApplicationSoSource.java:89)
06-01 13:01:15.192 27228 27280 W System.err:    at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:860)
06-01 13:01:15.192 27228 27280 W System.err:    at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:740)
06-01 13:01:15.192 27228 27280 W System.err:    at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:654)
06-01 13:01:15.192 27228 27280 W System.err:    at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:634)
06-01 13:01:15.192 27228 27280 W System.err:    at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:582)
06-01 13:01:15.192 27228 27280 W System.err:    at com.facebook.flipper.android.EventBase.<clinit>(EventBase.java:19)
06-01 13:01:15.193 27228 27280 W System.err:    at com.facebook.flipper.android.FlipperThread.run(FlipperThread.java:25)
06-01 13:01:15.193 27228 27280 E SoLoader: couldn't find DSO to load: libflipper.so caused by: dlopen failed: cannot locate symbol "_Unwind_Backtrace" referenced by "/data/app/com.mark8.agent-cqncFD5uZr4Ko2n_6Wn_Ng==/lib/arm64/libflipper.so"... result: 0
06-01 13:01:15.194 27228 27280 E AndroidRuntime: FATAL EXCEPTION: FlipperConnectionThread
06-01 13:01:15.194 27228 27280 E AndroidRuntime: Process: com.mark8.agent, PID: 27228
06-01 13:01:15.194 27228 27280 E AndroidRuntime: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libflipper.so caused by: dlopen failed: cannot locate symbol "_Unwind_Backtrace" referenced by "/data/app/com.mark8.agent-cqncFD5uZr4Ko2n_6Wn_Ng==/lib/arm64/libflipper.so"... result: 0
06-01 13:01:15.194 27228 27280 E AndroidRuntime:        at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:918)
06-01 13:01:15.194 27228 27280 E AndroidRuntime:        at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:740)
06-01 13:01:15.194 27228 27280 E AndroidRuntime:        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:654)
06-01 13:01:15.194 27228 27280 E AndroidRuntime:        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:634)
06-01 13:01:15.194 27228 27280 E AndroidRuntime:        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:582)
06-01 13:01:15.194 27228 27280 E AndroidRuntime:        at com.facebook.flipper.android.EventBase.<clinit>(EventBase.java:19)
06-01 13:01:15.194 27228 27280 E AndroidRuntime:        at com.facebook.flipper.android.FlipperThread.run(FlipperThread.java:25)
06-01 13:01:15.194 27228 27280 E AndroidRuntime: Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_Unwind_Backtrace" referenced by "/data/app/com.mark8.agent-cqncFD5uZr4Ko2n_6Wn_Ng==/lib/arm64/libflipper.so"...
06-01 13:01:15.194 27228 27280 E AndroidRuntime:        at java.lang.Runtime.load0(Runtime.java:938)
06-01 13:01:15.194 27228 27280 E AndroidRuntime:        at java.lang.System.load(System.java:1631)
06-01 13:01:15.194 27228 27280 E AndroidRuntime:        at com.facebook.soloader.SoLoader$1.load(SoLoader.java:405)
06-01 13:01:15.194 27228 27280 E AndroidRuntime:        at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:77)
06-01 13:01:15.194 27228 27280 E AndroidRuntime:        at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:50)
06-01 13:01:15.194 27228 27280 E AndroidRuntime:        at com.facebook.soloader.ApplicationSoSource.loadLibrary(ApplicationSoSource.java:89)
06-01 13:01:15.194 27228 27280 E AndroidRuntime:        at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:860)
06-01 13:01:15.194 27228 27280 E AndroidRuntime:        ... 6 more
06-01 13:01:15.195 27228 27279 E AndroidRuntime: FATAL EXCEPTION: FlipperEventBaseThread
06-01 13:01:15.195 27228 27279 E AndroidRuntime: Process: com.mark8.agent, PID: 27228
06-01 13:01:15.195 27228 27279 E AndroidRuntime: java.lang.NoClassDefFoundError: <clinit> failed for class com.facebook.flipper.android.EventBase; see exception in other thread
06-01 13:01:15.195 27228 27279 E AndroidRuntime:        at com.facebook.flipper.android.FlipperThread.run(FlipperThread.java:25)
06-01 13:01:15.197   682 27285 E ResolverController: No valid NAT64 prefix (108, <unspecified>/0)
06-01 13:01:15.197   682 27286 E ResolverController: No valid NAT64 prefix (108, <unspecified>/0)
06-01 13:01:15.215  3888  4138 W JavaExceptionHandler: Too noisy! skip duplicate java exception report:com.mark8.agent now=1685604675215 mLastReportTime=1685604621006 interval=60000
06-01 13:01:15.215  1531  2554 W ActivityTaskManager:   Force finishing activity com.mark8.agent/.MainActivity
06-01 13:01:15.223  1531 27292 W DropBoxManagerService: Dropping: data_app_crash (1651 > 0 bytes)
06-01 13:01:15.226  1531  1767 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
06-01 13:01:15.226  1531  1767 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
06-01 13:01:15.229  1531  3445 W ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.bindService:1659 android.content.ContextWrapper.bindService:715 miui.os.DropBoxManager.bindService:361 miui.os.DropBoxManager.addEntry:350 miui.os.DropBoxManager.addText:314
06-01 13:01:15.233  3888  4138 W JavaExceptionHandler: Too noisy! skip duplicate java exception report:com.mark8.agent now=1685604675233 mLastReportTime=1685604675215 interval=60000

**Comment by cortinico** [comment]
Hi @NimeshMadhushka 
Thanks for reporting this issue.

> 06-01 13:01:15.193 27228 27280 E SoLoader: couldn't find DSO to load: libflipper.so caused by: dlopen failed: cannot locate symbol "_Unwind_Backtrace" referenced by "/data/app/com.mark8.agent-cqncFD5uZr4Ko2n_6Wn_Ng==/lib/arm64/libflipper.so"... result: 0

From the error log, looks like is Flipper related. So perhaps removing Flipper from your project could help.

Also I'll be closing this as sadly you're reporting an issue with an [unsupported version of React Native](https://github.com/reactwg/react-native-releases#releases-support-policy) which we can't offer support for.

Our team is really small and we'd like to focus our effort on users on the latest 3 stable release, so please consider updating and re-open this issue if still persists.
