### ISSUE TITLE
Pod install error glog

### ISSUE THREAD

**Issue by megabeehothanhminh** [facebook/react-native#37655]
### Description

Help me!

### React Native Version

0.68.5

### Output of `npx react-native info`

   OS: macOS 13.0
    CPU: (8) arm64 Apple M1
    Memory: 173.92 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 20.2.0 - ~/.nvm/versions/node/v20.2.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.6.6 - ~/.nvm/versions/node/v20.2.0/bin/npm
    Watchman: 2023.05.22.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK:
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.19 - /opt/homebrew/opt/openjdk@11/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.68.5 => 0.68.5 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

cd ios && pod install

### Snack, code example, screenshot, or link to a repository

-> Installing glog (0.3.5)
 > Git download
 > Git download
     $ /opt/homebrew/bin/git clone https://github.com/google/glog.git /var/folders/dl/kh3bh2wn39j3d11ptk4x_z640000gn/T/d20230601-17190-sikz1b --template=
     --single-branch --depth 1 --branch v0.3.5
     Cloning into '/var/folders/dl/kh3bh2wn39j3d11ptk4x_z640000gn/T/d20230601-17190-sikz1b'...
 > Running prepare command
   $ /bin/bash -c  set -e #!/bin/bash # Copyright (c) Meta Platforms, Inc. and affiliates. # # This source code is licensed under the MIT license found in the #
   LICENSE file in the root directory of this source tree.  set -e  PLATFORM_NAME="${PLATFORM_NAME:-iphoneos}" CURRENT_ARCH="${CURRENT_ARCH}"  if [ -z
   "$CURRENT_ARCH" ] || [ "$CURRENT_ARCH" == "undefined_arch" ]; then     # Xcode 10 beta sets CURRENT_ARCH to "undefined_arch", this leads to incorrect linker
   arg.     # it's better to rely on platform name as fallback because architecture differs between simulator and device      if [[ "$PLATFORM_NAME" ==
   *"simulator"* ]]; then         CURRENT_ARCH="x86_64"     else         CURRENT_ARCH="arm64"     fi fi  if [ "$CURRENT_ARCH" == "arm64" ]; then     cat <<\EOF
   >>fix_glog_0.3.5_apple_silicon.patch diff --git a/config.sub b/config.sub index 1761d8b..43fa2e8 100755 --- a/config.sub +++ b/config.sub @@ -1096,6 +1096,9
   @@ case $basic_machine in            basic_machine=z8k-unknown               os=-sim                 ;; +    arm64-*) +              basic_machine=$(echo $basic_machine | sed 's/arm64/aarch64/') +         ;;  
   none)                basic_machine=none-none                 os=-none EOF      patch -p1 config.sub fix_glog_0.3.5_apple_silicon.patch fi  export CC="$(xcrun -find -sdk
   $PLATFORM_NAME cc) -arch $CURRENT_ARCH -isysroot $(xcrun -sdk $PLATFORM_NAME --show-sdk-path)" export CXX="$CC"  # Remove automake symlink if it exists if [
   -h "test-driver" ]; then     rm test-driver fi  # Manually disable gflags include to fix issue https://github.com/facebook/react-native/issues/28446 sed -i
   '' 's/\@ac_cv_have_libgflags\@/0/' src/glog/logging.h.in sed -i '' 's/HAVE_LIB_GFLAGS/HAVE_LIB_GFLAGS_DISABLED/' src/config.h.in  ./configure --host
   arm-apple-darwin  cat << EOF >> src/config.h /* Add in so we have Apple Target Conditionals */ #ifdef __APPLE__ #include <TargetConditionals.h> #include
   <Availability.h> #endif  /* Special configuration for ucontext */ #undef HAVE_UCONTEXT_H #undef PC_FROM_UCONTEXT #if defined(__x86_64__) #define
   PC_FROM_UCONTEXT uc_mcontext->__ss.__rip #elif defined(__i386__) #define PC_FROM_UCONTEXT uc_mcontext->__ss.__eip #endif EOF  # Prepare exported header
   include EXPORTED_INCLUDE_DIR="exported/glog" mkdir -p exported/glog cp -f src/glog/log_severity.h "$EXPORTED_INCLUDE_DIR/" cp -f src/glog/logging.h
   "$EXPORTED_INCLUDE_DIR/" cp -f src/glog/raw_logging.h "$EXPORTED_INCLUDE_DIR/" cp -f src/glog/stl_logging.h "$EXPORTED_INCLUDE_DIR/" cp -f
   src/glog/vlog_is_on.h "$EXPORTED_INCLUDE_DIR/"
   patching file config.sub
   checking for a BSD-compatible install... /usr/bin/install -c
   checking whether build environment is sane... yes
   /Users/thanhminh/Library/Caches/CocoaPods/Pods/External/glog/2263bd123499e5b93b5efe24871be317-476ee/missing: Unknown `--is-lightweight' option
   Try `/Users/thanhminh/Library/Caches/CocoaPods/Pods/External/glog/2263bd123499e5b93b5efe24871be317-476ee/missing --help' for more information
   configure: WARNING: 'missing' script is too old or missing
   checking for arm-apple-darwin-strip... no
   checking for strip... strip
   checking for a thread-safe mkdir -p... ./install-sh -c -d
   checking for gawk... gawk
   checking whether make sets $(MAKE)... yes
   checking whether make supports nested variables... yes
   checking for arm-apple-darwin-gcc... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.4.sdk
   checking whether the C compiler works... yes
   checking for C compiler default output file name... a.out
   checking for suffix of executables...

**Comment by cortinico** [comment]
Can you provide the full build log?

**Comment by megabeehothanhminh** [comment]
> Can you provide the full build log?

cd ios && pod install 

It run to -> Installing glog (0.3.5). 

-> Installing glog (0.3.5)
 > Git download
 > Git download
     $ /opt/homebrew/bin/git clone https://github.com/google/glog.git /var/folders/dl/kh3bh2wn39j3d11ptk4x_z640000gn/T/d20230601-31316-t5pu --template=
     --single-branch --depth 1 --branch v0.3.5
     Cloning into '/var/folders/dl/kh3bh2wn39j3d11ptk4x_z640000gn/T/d20230601-31316-t5pu'...
 > Running prepare command
   $ /bin/bash -c  set -e #!/bin/bash # Copyright (c) Meta Platforms, Inc. and affiliates. # # This source code is licensed under the MIT license found in the #
   LICENSE file in the root directory of this source tree.  set -e  PLATFORM_NAME="${PLATFORM_NAME:-iphoneos}" CURRENT_ARCH="${CURRENT_ARCH}"  if [ -z
   "$CURRENT_ARCH" ] || [ "$CURRENT_ARCH" == "undefined_arch" ]; then     # Xcode 10 beta sets CURRENT_ARCH to "undefined_arch", this leads to incorrect linker
   arg.     # it's better to rely on platform name as fallback because architecture differs between simulator and device      if [[ "$PLATFORM_NAME" ==
   *"simulator"* ]]; then         CURRENT_ARCH="x86_64"     else         CURRENT_ARCH="arm64"     fi fi  if [ "$CURRENT_ARCH" == "arm64" ]; then     cat <<\EOF
   >>fix_glog_0.3.5_apple_silicon.patch diff --git a/config.sub b/config.sub index 1761d8b..43fa2e8 100755 --- a/config.sub +++ b/config.sub @@ -1096,6 +1096,9
   @@ case $basic_machine in            basic_machine=z8k-unknown               os=-sim                 ;; +    arm64-*) +              basic_machine=$(echo $basic_machine | sed 's/arm64/aarch64/') +         ;;  
   none)                basic_machine=none-none                 os=-none EOF      patch -p1 config.sub fix_glog_0.3.5_apple_silicon.patch fi  export CC="$(xcrun -find -sdk
   $PLATFORM_NAME cc) -arch $CURRENT_ARCH -isysroot $(xcrun -sdk $PLATFORM_NAME --show-sdk-path)" export CXX="$CC"  # Remove automake symlink if it exists if [
   -h "test-driver" ]; then     rm test-driver fi  # Manually disable gflags include to fix issue https://github.com/facebook/react-native/issues/28446 sed -i
   '' 's/\@ac_cv_have_libgflags\@/0/' src/glog/logging.h.in sed -i '' 's/HAVE_LIB_GFLAGS/HAVE_LIB_GFLAGS_DISABLED/' src/config.h.in  ./configure --host
   arm-apple-darwin  cat << EOF >> src/config.h /* Add in so we have Apple Target Conditionals */ #ifdef __APPLE__ #include <TargetConditionals.h> #include
   <Availability.h> #endif  /* Special configuration for ucontext */ #undef HAVE_UCONTEXT_H #undef PC_FROM_UCONTEXT #if defined(__x86_64__) #define
   PC_FROM_UCONTEXT uc_mcontext->__ss.__rip #elif defined(__i386__) #define PC_FROM_UCONTEXT uc_mcontext->__ss.__eip #endif EOF  # Prepare exported header
   include EXPORTED_INCLUDE_DIR="exported/glog" mkdir -p exported/glog cp -f src/glog/log_severity.h "$EXPORTED_INCLUDE_DIR/" cp -f src/glog/logging.h
   "$EXPORTED_INCLUDE_DIR/" cp -f src/glog/raw_logging.h "$EXPORTED_INCLUDE_DIR/" cp -f src/glog/stl_logging.h "$EXPORTED_INCLUDE_DIR/" cp -f
   src/glog/vlog_is_on.h "$EXPORTED_INCLUDE_DIR/"
   patching file config.sub
   checking for a BSD-compatible install... /usr/bin/install -c
   checking whether build environment is sane... yes
   /Users/thanhminh/Library/Caches/CocoaPods/Pods/External/glog/2263bd123499e5b93b5efe24871be317-476ee/missing: Unknown `--is-lightweight' option
   Try `/Users/thanhminh/Library/Caches/CocoaPods/Pods/External/glog/2263bd123499e5b93b5efe24871be317-476ee/missing --help' for more information
   configure: WARNING: 'missing' script is too old or missing
   checking for arm-apple-darwin-strip... no
   checking for strip... strip
   checking for a thread-safe mkdir -p... ./install-sh -c -d
   checking for gawk... gawk
   checking whether make sets $(MAKE)... yes
   checking whether make supports nested variables... yes
   checking for arm-apple-darwin-gcc... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.4.sdk
   checking whether the C compiler works... yes
   checking for C compiler default output file name... a.out
   checking for suffix of executables... 
^C   checking whether we are cross compiling...

**Comment by megabeehothanhminh** [comment]
I'm fixed by upgrade MACOS. I will close issue this. Thanks

**Comment by redpredator8** [comment]
it did fix it for me too, but came back on Sequoia 15.2
anyone got another fix?

**Comment by kms1212** [comment]
> it did fix it for me too, but came back on Sequoia 15.2 anyone got another fix?

I'm experiencing the same issue.

**Comment by iw4p** [comment]
Same here. Sequoia 15.3.2

**Comment by iw4p** [comment]
This worked for me

```
sudo xcode-select --switch /Applications/Xcode.app
cd ios && pod install
```
