### ISSUE TITLE
FBReactNativeSpec ios/build/generated/ wrong output path

### ISSUE THREAD

**Issue by midrizi** [facebook/react-native#37705]
### Description

I'm using pnpm as package manager in a monorepo setup, and for some reason the generated output goes one directory above where the project root is.

This is what the output path looks like in `Pods/FBReactNativeSpec`
```
outputPaths = (
	"${DERIVED_FILE_DIR}/codegen-FBReactNativeSpec.log",
	"${PODS_TARGET_SRCROOT}/../../../../../../../apps/native/ios/build/generated/ios/./FBReactNativeSpec/FBReactNativeSpec.h",
	"${PODS_TARGET_SRCROOT}/../../../../../../../apps/native/ios/build/generated/ios/./FBReactNativeSpec/FBReactNativeSpec-generated.mm",
);
```

![image](https://github.com/facebook/react-native/assets/56638730/33062d4a-b38b-49a7-bb1b-b11ec89ae62c)

### React Native Version

0.71.7

### Output of `npx react-native info`

```
System:
    OS: macOS 13.4
    CPU: (8) arm64 Apple M2
    Memory: 232.77 MB / 24.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.16.0/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.9971841
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 20.0.1 - /opt/homebrew/opt/openjdk/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.7 => 0.71.7
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

Just installing the App generates folder in the wrong path.

### Snack, code example, screenshot, or link to a repository

You can try it by running the demo project I created: https://github.com/midrizi/fbreactnativespec-path-issue

After running the `pnpm install:ios` this is how it looks like:

![image](https://github.com/facebook/react-native/assets/56638730/0b5be3bc-9fdd-42e9-be44-3fd70711978e)

**Comment by kekami** [comment]
Did you manage to resolve it? Experiencing the same thing.
