### ISSUE TITLE
Running app on Android emulator, build failed, react-native run-android

### ISSUE THREAD

**Issue by jonolock91** [facebook/react-native#3770]
Hi, hopefully it's just a small thing I'm missing but hope someone can help me. I have my app working on iOS and wanted to test it on an Android emulator. I have the Android SDK and emulator set up, the Android emulator starts up but with a black screen (I presume because react-native run-android fails). 

When I run 'react-native run-android' inside my app project I get the following error:

Jonathans-MacBook-Pro:PamperPad jono$ react-native run-android
JS server already running.
Building and installing the app on the device (cd android && ./gradlew installDebug)...

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not find com.android.support:appcompat-v7:23.0.1.
     Searched in the following locations:
         file:/Users/jono/.m2/repository/com/android/support/appcompat-v7/23.0.1/appcompat-v7-23.0.1.pom
         file:/Users/jono/.m2/repository/com/android/support/appcompat-v7/23.0.1/appcompat-v7-23.0.1.jar
         https://jcenter.bintray.com/com/android/support/appcompat-v7/23.0.1/appcompat-v7-23.0.1.pom
         https://jcenter.bintray.com/com/android/support/appcompat-v7/23.0.1/appcompat-v7-23.0.1.jar
     Required by:
         PamperPad:app:unspecified
         PamperPad:app:unspecified > com.facebook.react:react-native:0.12.0
   > Could not find com.android.support:support-v4:21.0.3.
     Searched in the following locations:
         file:/Users/jono/.m2/repository/com/android/support/support-v4/21.0.3/support-v4-21.0.3.pom
         file:/Users/jono/.m2/repository/com/android/support/support-v4/21.0.3/support-v4-21.0.3.jar
         https://jcenter.bintray.com/com/android/support/support-v4/21.0.3/support-v4-21.0.3.pom
         https://jcenter.bintray.com/com/android/support/support-v4/21.0.3/support-v4-21.0.3.jar
     Required by:
         PamperPad:app:unspecified > com.facebook.react:react-native:0.12.0 > com.facebook.fresco:fresco:0.6.1 > com.facebook.fresco:drawee:0.6.1
         PamperPad:app:unspecified > com.facebook.react:react-native:0.12.0 > com.facebook.fresco:fresco:0.6.1 > com.facebook.fresco:imagepipeline:0.6.1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 8.317 secs
Could not install the app on the device, see the error above.

**Comment by flipskills25** [comment]
Go to your build.gradle file in [your project name]\android\app and under "dependencies", change the 'com.android.support:appcompat-v7:23.0.1' dependency to 23.0.0.

**Comment by jonolock91** [comment]
Thanks for your help, I think that may have altered something, I've changed that, however the error still says 'Could not find com.android.support:appcompat-v7:23.0.1.', How do I reset it so it sees the new value?

**Comment by whokilledtheelectricmonk** [comment]
Do you have the v23 SDKs?

**Comment by jonolock91** [comment]
I installed the android SDK using 'brew install android-idk' and here is what is installed when I run 'android':
<img width="679" alt="screen shot 2015-10-30 at 09 07 48 copy" src="https://cloud.githubusercontent.com/assets/11156990/10841960/e664ccb0-7ee5-11e5-9f4c-08f1c2c4ea18.png">

**Comment by whokilledtheelectricmonk** [comment]
You also need the Android support repository: 

http://facebook.github.io/react-native/docs/android-setup.html#content

If it is running slowly, make sure you configured HAXM correctly for the emulator.

**Comment by jonolock91** [comment]
That solved that problem, thanks, but now I'm getting this error which should be a small thing.

Execution failed for task ':app:installDebug'.
> com.android.builder.testing.api.DeviceException: No online devices found.

I have my AVD open and it has a black screen on it before running the 'react-native run-android'

**Comment by jonolock91** [comment]
It also comes back with:
Skipping device 'emulator-5554' (emulator-5554): Device is OFFLINE.
Which would seem to be my simulator.

**Comment by jonolock91** [comment]
I have it working now thanks.

**Comment by iroy2000** [comment]
The document is not really updated, they said to install `Android Support Repository`.

But `Android Support Repository` is actually renamed to `Local Maven repository for Support Libraries`.

**Comment by rodneysantos** [comment]
Same problem here and @iroy2000 comment saved me, thanks :)

**Comment by ryngonzalez** [comment]
Same issue as @rodneysantos—thanks @iroy2000!

**Comment by dhrrgn** [comment]
I have submitted a PR to fix the docs here: #6185

**Comment by dannysindra** [comment]
Now the "Local Maven repo ..." not available anymore, and I still get the error. Any other suggestions?
