### ISSUE TITLE
网络请求无法发出

### ISSUE THREAD

**Issue by BianXuerui** [facebook/react-native#37711]
### Description

 - 在安卓设备上面，经常会出现网络请求无法请求成功，一直处在一个加载中的状态，这时候需要杀死app重新打开，才可以。
 - Android Studio 4.2
 - 好像是切换了一次Android Studio版本，不知道是否会影响，现在记不清之前的Android Studio版本了。

### React Native Version

0.62.2

### Output of `npx react-native info`

System:
    OS: macOS 13.0.1
    CPU: (8) arm64 Apple M1
    Memory: 203.58 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK:
      API Levels: 28, 29, 31, 32, 33
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 33.0.0, 33.0.2
      System Images: android-28 | Intel x86 Atom_64, android-29 | Intel x86 Atom_64, android-31 | ARM 64 v8a, android-31 | Intel x86 Atom_64, android-33 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7322048
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_282 - /usr/bin/javac
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^16.13.1 => 16.14.0
    react-native: 0.62.2 => 0.62.2
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

打开app的时候 时不时的就会出现（很频繁），没有什么规律。

### Snack, code example, screenshot, or link to a repository

https://github.com/facebook/react-native/assets/50104688/f43572e7-ac80-4459-9143-d84f6089fd87

**Comment by BianXuerui** [comment]
即使在加载框中设置超时时间，加载框超时消失，再次请求还是会出现同样情况，只有把app杀死重新打开才可以暂时缓解。

**Comment by cortinico** [comment]
Hi @BianXuerui 
In this issue tracker we accept only issues that are in English.
I'm closing this for now, please consider translating it to English and reopening it.
Thanks.
