### ISSUE TITLE
Show download progress bar during 'react-native init'

### ISSUE THREAD

**Issue by mkonicek** [facebook/react-native#3771]
'react-native init' spends almost all its time in 'npm install':
https://github.com/facebook/react-native/blob/master/react-native-cli/index.js#L191

It would be cool to show a progress bar during the download.

A quick Google search returns: https://github.com/npm/npm/issues/6911

**Comment by udnisap** [comment]
It is there in node v5 or npm 3.3.6 If we use `spawn` instead of `exec` we can show it with a pipe like we do in https://github.com/facebook/react-native/blob/master/react-native-cli/index.js#L207
in previous versions of node it would be bit tricky.

**Comment by christopherdro** [comment]
Nice one @udnisap! Just tested it out. 
Could you submit a PR with this change?

**Comment by mkonicek** [comment]
Thanks for adding it! I've put this behavior behind a --debug flag, realized showing it by default was not a good experience: https://github.com/facebook/react-native/commit/6af7ae55b1ccffd185eb269b81f9ed1ee9f77cc7

--verbose still works as before.
