### ISSUE TITLE
Network request progress on Android

### ISSUE THREAD

**Issue by nucleartux** [facebook/react-native#3772]
Currently on android xhr `onreadystatechange` fires only on xhr.DONE, but not on HEADERS_RECEIVED or LOADING. It seems OkHTTP doesn't support this events.
Does anyone have ideas how to realize this events for full consistency with iOS?
Maybe we should change OkHTTP to another library?

PS. And sorry for me english :)

**Comment by nucleartux** [comment]
@ide can you help?:)

**Comment by ide** [comment]
cc @kmagiera @mkonicek do you know of a Java HTTP library that notifies you of more fine-grained events, like when headers have been downloaded? (Also: it might make sense to look into HTTP/2 libraries now that it's popular, but that's a separate task.)

**Comment by kmagiera** [comment]
OkHttp that we use as a default http client have interceptors API that allows for tracking the progress (see https://github.com/square/okhttp/blob/master/samples/guide/src/main/java/com/squareup/okhttp/recipes/Progress.java). It also supports SPDY and HTTP/2 support is definitely on the works (if not already there https://github.com/square/okhttp/commit/21dc92f967d01c2da3ace57b7cc04421e2fd296b)

**Comment by nucleartux** [comment]
Hm, but how realize HEADERS_RECEIVED event? I can read length of bytes send, but how I can intercept what headers was received?

**Comment by kmagiera** [comment]
Not an expert in OkHttp API but it looks like when `Chain.proceed` returns headers are available (or maybe you need to call `Response.headers()` on the result of `Chain.proceed` and it's blocking). Those are questions you perhaps want to ask on okhttp github project rather than here

**Comment by nucleartux** [comment]
thank you, I will try realize this events :)
