### ISSUE TITLE
[Android] [Navigator] HorizonalSwipeJump animation overlap

### ISSUE THREAD

**Issue by dgladkov** [facebook/react-native#3773]
Device: Nexus 5
OS: Android 6.0
React-native: 0.14.0-rc

Scenes overlap during HorizonalSwipeJump animation. Problem is not reproduced in both Android and iOS with react-native 0.12.x and iOS with react-native 0.14.0-rc

Example with 2 scenes and a Navigator with HorizontalSwipeJump
![2015_10_29_17_23_11](https://cloud.githubusercontent.com/assets/98132/10823299/b2a66960-7e63-11e5-8cc7-64f5d49a74c0.gif)

**Comment by dgladkov** [comment]
Found that the problem is in ReactAndroid. bf598647d2ff7aad1d29c7c5d28d816c01941c1c breaks it for me

**Comment by dgladkov** [comment]
Added example project to reproduce the bug at https://github.com/dgladkov/react-native-3773

**Comment by ide** [comment]
cc @kmagiera
