### ISSUE TITLE
URI::BadURIError - relative URI: /third-party-podspecs/DoubleConversion.podspec in pod install when upgrading react-native from 0.69.10 to 0.70.0

### ISSUE THREAD

**Issue by tarotsurugalnk** [facebook/react-native#37749]
### Description

In 0.69.10, pod install and IOS build were working fine, but as soon as I upgraded to 0.70, pod install started giving me errors. (Details to follow).

### React Native Version

0.70.0

### Output of `npx react-native info`

System:
    OS: macOS 13.3.1
    CPU: (8) x64 Apple M1 Pro
    Memory: 84.31 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v14.17.0/bin/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
    Watchman: 2023.05.22.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /Users/username/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0
    react-native: ^0.70.0 => 0.70.9
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

The following error log was output when `pod install` was performed.

----------------------------------------------------------------

RNFBAnalytics: Using default Firebase/Analytics with Ad Ids. May require App Tracking Transparency. Not allowed for Kids apps.
RNFBAnalytics: You may set variable `$RNFirebaseAnalyticsWithoutAdIdSupport=true` in Podfile to use analytics without ad ids.
Adding a custom script phase for Pod RNFBApp: [RNFB] Core Configuration
Adding a custom script phase for Pod RNFBCrashlytics: [RNFB] Crashlytics Configuration
Auto-linking React Native modules for target `Project`: BVLinearGradient, RNAppleAuthentication, RNBootSplash, RNCAsyncStorage, RNCPicker, RNCPushNotificationIOS, RNDateTimePicker, RNDeviceInfo, RNFBAnalytics, RNFBApp, RNFBCrashlytics, RNFBMessaging, RNFS, RNFastImage, RNGestureHandler, RNI18n, RNImageCropPicker, RNLocalize, RNPermissions, RNReactNativeHapticFeedback, RNSVG, RNShare, RNVectorIcons, ReactNativeART, react-native-ad-manager, react-native-add-calendar-event, react-native-adjust, react-native-background-upload, react-native-blob-util, react-native-camera, react-native-cameraroll, react-native-contacts, react-native-device-brightness, react-native-document-picker, react-native-fbsdk, react-native-get-random-values, react-native-in-app-review, react-native-in-app-utils, react-native-keep-awake, react-native-maps, react-native-netinfo, react-native-pdf, react-native-slider, react-native-twitter-signin, react-native-version-number, react-native-video, react-native-view-shot, react-native-viewpager, react-native-webview, and rn-media-meta
[Codegen] Generating ios/build/generated/ios/React-Codegen.podspec.json
Analyzing dependencies
Pre-downloading: `DCTAuth` from `https://github.com/danielctull/DCTAuth.git`, commit `0a8091a3fc165fb99a6f70cf15b3aed25252dad9`
Fetching podspec for `DoubleConversion` from `/third-party-podspecs/DoubleConversion.podspec`

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/Users/username/.rbenv/versions/3.2.2/bin/pod install --project-directory=ios
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.12.1
        Ruby : ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin22]
    RubyGems : 3.4.10
        Host : macOS 13.3.1 ((a))
       Xcode : 14.2 (14C18)
         Git : git version 2.37.1 (Apple Git-137.1)
Ruby lib dir : /Users/username/.rbenv/versions/3.2.2/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
platform :ios, '13.0'

target 'Project' do
  config = use_native_modules!
  use_react_native!(
    :path => config["reactNativePath"],
    # Consider to apply hermes engine
    :hermes_enabled => false
  )
  # Pods for Project
  pod 'FBSDKCoreKit', :modular_headers => true
  pod 'FBSDKShareKit'
  pod 'FBSDKLoginKit'
  pod 'TwitterCore', '3.1.0'
  pod 'TwitterKit', '3.3.0'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
  pod 'DCTAuth', :git => 'https://github.com/danielctull/DCTAuth.git'
  pod 'RSKImageCropper'

  # React Native Maps dependencies
  pod 'react-native-google-maps', :path => '../node_modules/react-native-maps'
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'

  pod 'react-native-geolocation', path: '../node_modules/@react-native-community/geolocation'

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse.podspec"

  target 'ProjectTests' do
    inherit! :complete
    # Pods for testing
  end

  # use_flipper!()

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
        target.build_configurations.each do |config|
            config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      else
        react_native_post_install(installer)
        __apply_Xcode_12_5_M1_post_install_workaround(installer)
        installer.pods_project.build_configurations.each do |config|
          config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
        end
      end
    end
  end
end
```

### Error

```
URI::BadURIError - relative URI: /third-party-podspecs/DoubleConversion.podspec
/Users/username/.rbenv/versions/3.2.2/lib/ruby/3.2.0/uri/generic.rb:1500:in `find_proxy'
/Users/username/.rbenv/versions/3.2.2/lib/ruby/3.2.0/open-uri.rb:197:in `block in open_loop'
/Users/username/.rbenv/versions/3.2.2/lib/ruby/3.2.0/open-uri.rb:214:in `block in open_loop'
/Users/username/.rbenv/versions/3.2.2/lib/ruby/3.2.0/open-uri.rb:212:in `catch'
/Users/username/.rbenv/versions/3.2.2/lib/ruby/3.2.0/open-uri.rb:212:in `open_loop'
/Users/username/.rbenv/versions/3.2.2/lib/ruby/3.2.0/open-uri.rb:153:in `open_uri'
/Users/username/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.12.1/lib/cocoapods/external_sources/podspec_source.rb:19:in `block in fetch'
/Users/username/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.12.1/lib/cocoapods/user_interface.rb:86:in `titled_section'
/Users/username/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.12.1/lib/cocoapods/external_sources/podspec_source.rb:11:in `fetch'
/Users/username/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.12.1/lib/cocoapods/installer/analyzer.rb:997:in `fetch_external_source'
/Users/username/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.12.1/lib/cocoapods/installer/analyzer.rb:976:in `block (2 levels) in fetch_external_sources'
/Users/username/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.12.1/lib/cocoapods/installer/analyzer.rb:975:in `each'
/Users/username/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.12.1/lib/cocoapods/installer/analyzer.rb:975:in `block in fetch_external_sources'
/Users/username/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.12.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/username/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.12.1/lib/cocoapods/installer/analyzer.rb:974:in `fetch_external_sources'
/Users/username/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.12.1/lib/cocoapods/installer/analyzer.rb:118:in `analyze'
/Users/username/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:422:in `analyze'
/Users/username/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:244:in `block in resolve_dependencies'
/Users/username/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.12.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/username/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:243:in `resolve_dependencies'
/Users/username/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:162:in `install!'
/Users/username/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.12.1/lib/cocoapods/command/install.rb:52:in `run'
/Users/username/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/Users/username/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.12.1/lib/cocoapods/command.rb:52:in `run'
/Users/username/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.12.1/bin/pod:55:in `<top (required)>'
/Users/username/.rbenv/versions/3.2.2/bin/pod:25:in `load'
/Users/username/.rbenv/versions/3.2.2/bin/pod:25:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

### Snack, code example, screenshot, or link to a repository

<img width="733" alt="Screenshot 2023-06-07 at 15 51 49" src="https://github.com/facebook/react-native/assets/116240657/3672b22f-75d0-4e36-a8d5-e7ed52a75353">

**Comment by tarotsurugalnk** [comment]
I upgraded to the latest 0.71.8, but I get the same error output.

**Comment by Asscher** [comment]
@tarotsurugalnk did you find a solution ? I'm having the same issue going from 0.70.0 to 0.71.0
