### ISSUE TITLE
[Android] ReactMethod Callback arguments are null when passed first but not when passed last

### ISSUE THREAD

**Issue by cosmith** [facebook/react-native#3776]
Calling
```java
@ReactMethod
public void getCurrentPosition(final Integer timeout,
                                   final Integer maximumAge,
                                   final Boolean enableHighAccuracy,
                                   final Callback onSuccess,
                                   final Callback onError) {
        ...
}
```
works but this:
```java
@ReactMethod
public void getCurrentPosition(final Callback onSuccess,
                                   final Callback onError,
                                   final Integer timeout,
                                   final Integer maximumAge,
                                   final Boolean enableHighAccuracy) {
}
```

gives `onSuccess` and `onError` as `null`.

I don't really have time to dig more into this right now but just putting it here in case someone is struggling to understand what's going on like me... try with your Callbacks at the end of the argument list :smile: 

If someone who knows what's happening deep inside looks at this: the parameters are already null in the call to `public void call(int moduleId, int methodId, ReadableNativeArray parameters)` in `CatalystInstance.java`

**Comment by ide** [comment]
This doesn't directly address your issue but in 0.15-rc we now have support for proper async functions. So you'll be able to take in one object at the end of your param list that has a `resolve` and a `reject` method and automatically define an async function on the JS side.

**Comment by hufeng** [comment]
thanks @ide , Cool.
