### ISSUE TITLE
Android 14 Broadcast Receiver flag 

### ISSUE THREAD

**Issue by mvn-hungtruong-dn** [facebook/react-native#37769]
### Description

Android 14 requires the flag `RECEIVER_NOT_EXPORTED` or `RECEIVER_EXPORTED` when `registerReceiver`

Maybe related to this issue
https://github.com/facebook/react-native/issues/31870

### React Native Version

0.71.10

### Output of `npx react-native info`

System:
    OS: macOS 13.4
    CPU: (8) arm64 Apple M2
    Memory: 55.25 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.0.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.6.4 - /opt/homebrew/bin/npm
    Watchman: 2023.05.15.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.10121639
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.6 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.10 => 0.71.10 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Set `targetSdkPreview` and `compileSdkPreview` to `UpsideDownCake` and build an app for Android.
The application will be crashed immediately after opening.

### Snack, code example, screenshot, or link to a repository

![Screenshot 2023-06-08 at 17 25 28](https://github.com/facebook/react-native/assets/16176383/8f8680fa-791d-4374-a9ec-183baf748adf)

**Comment by cortinico** [comment]
That's a valid report, thanks for sharing. We're tracking this and other Android 14 required tasks internally.

**Comment by LeonidKokhnovich** [comment]
Hi! My understanding it's a blocker for Android 14 support with RN integration. Do we need help to get a code change for this issue or there is already something working on it? Thank you!

**Comment by DaAitch** [comment]
Same here.

- RN: 0.71.2
- updating `compileSdkVersion` and `targetSdkVersion` to API 34 (Android 14) for testing
- `java.lang.SecurityException` for debug and release (in debug this error is nested in one of the "causes", but they are same)

```groovy
buildscript {
    ext {
        // ...
        compileSdkVersion = 34 // Android 14
        targetSdkVersion = 34 // Android 14
        // ...
    }
}
```

```
java.lang.SecurityException: XYZ: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
```

**Comment by cortinico** [comment]
> Hi! My understanding it's a blocker for Android 14 support with RN integration. Do we need help to get a code change for this issue or there is already someone working on it? If yes, what's the timeline for this fix? Thank you!

@LeonidKokhnovich if you wish to send a PR, please do. We could backport it to 0.71/0.72 if needed

**Comment by StevenBarnett1** [comment]
Im running into the same problem
```
        buildToolsVersion = findProperty('android.buildToolsVersion') ?: '34.0.0'
        minSdkVersion = Integer.parseInt(findProperty('android.minSdkVersion') ?: '21')
        compileSdkVersion = Integer.parseInt(findProperty('android.compileSdkVersion') ?: '34')
        targetSdkVersion = Integer.parseInt(findProperty('android.targetSdkVersion') ?: '34')
```

**Comment by dominikwagner** [comment]
PR was merged [#38256](https://github.com/facebook/react-native/pull/38256)
Does anybody know when this will be available in a new release? Thanks!

**Comment by cortinico** [comment]
> PR was merged https://github.com/facebook/react-native/pull/38256

Closing as for this

> Does anybody know when this will be available in a new release? Thanks!

It will make it in 0.73 or you can ask for a backport in this working group:
https://github.com/reactwg/react-native-releases/discussions

**Comment by dominikwagner** [comment]
> 

Thanks!
I asked for a backport. Because this is blocking Android 14 support which is released next week. So  I was wondering if there was a temporarily solution for this until there is a backport or a new release.

**Comment by cortinico** [comment]
> Because this is blocking Android 14 support which is released next week

Could you link the source of this statement?

**Comment by dominikwagner** [comment]
> Could you link the source of this statement?

Sorry, it was just my conclusion after reading this thread, seeing the code changes in the PR and fighting with this problem for several hours while attempting to upgrade to Android 14

**Comment by dominikwagner** [comment]
Has anyone solved this problem without upgrading RN? We're currently using RN 0.69, and we haven't found a way to make it work with Android 14.

**Comment by DaAitch** [comment]
@dominikwagner as long as you do not target a new Android version it should not break your running app, at least for while, so you have time to update RN.

**Comment by ThushalIntervest** [comment]
Does anyone know an alternative solution?

**Comment by renanzalheiros** [comment]
Any ideia when this fix will be applied?

**Comment by BrianCodeItUp** [comment]
I'm having this issue on RN 0.73.2

error log:
```
01-25 11:41:07.965  8055  8712 E unknown:ReactNative: java.lang.SecurityException: app.zqb.android.dev: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
01-25 11:41:07.965  8055  8712 E unknown:ReactNative:   at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
01-25 11:41:07.965  8055  8712 E unknown:ReactNative:   at android.os.Parcel.createException(Parcel.java:3041)
01-25 11:41:07.965  8055  8712 E unknown:ReactNative:   at android.os.Parcel.readException(Parcel.java:3024)
01-25 11:41:07.965  8055  8712 E unknown:ReactNative:   at android.os.Parcel.readException(Parcel.java:2966)
01-25 11:41:07.965  8055  8712 E unknown:ReactNative:   at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5684)
01-25 11:41:07.965  8055  8712 E unknown:ReactNative:   at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1852)
01-25 11:41:07.965  8055  8712 E unknown:ReactNative:   at android.app.ContextImpl.registerReceiver(ContextImpl.java:1792)
01-25 11:41:07.965  8055  8712 E unknown:ReactNative:   at android.app.ContextImpl.registerReceiver(ContextImpl.java:1780)
01-25 11:41:07.965  8055  8712 E unknown:ReactNative:   at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:755)
01-25 11:41:07.965  8055  8712 E unknown:ReactNative:   at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:755)
01-25 11:41:07.965  8055  8712 E unknown:ReactNative:   at org.wonday.orientation.OrientationModule.start(OrientationModule.java:356)
01-25 11:41:07.965  8055  8712 E unknown:ReactNative:   at org.wonday.orientation.OrientationActivityLifecycle.registerListeners(OrientationActivityLifecycle.java:30)
01-25 11:41:07.965  8055  8712 E unknown:ReactNative:   at org.wonday.orientation.OrientationModule.<init>(OrientationModule.java:134)
01-25 11:41:07.965  8055  8712 E unknown:ReactNative:   at org.wonday.orientation.OrientationPackage.createNativeModules(OrientationPackage.java:28)
01-25 11:41:07.965  8055  8712 E unknown:ReactNative:   at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:43)
01-25 11:41:07.965  8055  8712 E unknown:ReactNative:   at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:42)
01-25 11:41:07.965  8055  8712 E unknown:ReactNative:   at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1458)
01-25 11:41:07.965  8055  8712 E unknown:ReactNative:   at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1429)
01-25 11:41:07.965  8055  8712 E unknown:ReactNative:   at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1331)
01-25 11:41:07.965  8055  8712 E unknown:ReactNative:   at com.facebook.react.ReactInstanceManager.lambda$runCreateReactContextOnNewThread$2(ReactInstanceManager.java:1101)
01-25 11:41:07.965  8055  8712 E unknown:ReactNative:   at com.facebook.react.ReactInstanceManager.$r8$lambda$AwGS8CysOZmWJw3kRVARHQvw9Ew(Unknown Source:0)
01-25 11:41:07.965  8055  8712 E unknown:ReactNative:   at com.facebook.react.ReactInstanceManager$$ExternalSyntheticLambda5.run(Unknown Source:4)
01-25 11:41:07.965  8055  8712 E unknown:ReactNative:   at java.lang.Thread.run(Thread.java:1012)
```
