### ISSUE TITLE
AppState.currentState returning unknown in iOS when app launched in release mode.

### ISSUE THREAD

**Issue by rifad4u** [facebook/react-native#37793]
### Description

AppState.currentState returning unknown in iOS when app launched and this is not happening in debug mode.

### React Native Version

0.70.10

### Output of `npx react-native info`

System:
    OS: macOS 13.4
    CPU: (8) arm64 Apple M2
    Memory: 86.84 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 14.21.3 - /opt/homebrew/bin/node
    Yarn: Not Found
    npm: 6.14.18 - /opt/homebrew/bin/npm
    Watchman: 2023.03.13.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK:
      API Levels: 27, 28, 29, 30, 31, 32, 33
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 33.0.0, 33.0.2
      System Images: android-27 | Google APIs ARM 64 v8a, android-27 | Google Play Intel x86 Atom, android-29 | Google APIs ARM 64 v8a, android-29 | Google Play ARM 64 v8a, android-30 | Google Play ARM 64 v8a, android-32 | Google Play ARM 64 v8a, android-33 | Google APIs ARM 64 v8a, android-33 | Google Play ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.10121639
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.18 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.10 => 0.70.10
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Clone the project from the below link , run the iOS and check the console once the app launched.

### Snack, code example, screenshot, or link to a repository
https://github.com/rifad4u/AppStateIssue
--

**Comment by rifad4u** [comment]
> ⚠️	Missing Reproducible Example
> ℹ️	It looks like your issue is missing a reproducible example. Please provide either:
> * If your bug is UI related: a [Snack](https://snack.expo.dev)
> * If your bug is build/update related: use our [Reproducer Template](https://github.com/react-native-community/reproducer-react-native/generate)

Updated

**Comment by mayying** [comment]
i am facing the same issue, please help

**Comment by Panda-ref** [comment]
Same on react-native 0.71.12

**Comment by yaniv-blink** [comment]
same on react-native 0.72.3

**Comment by YKSing** [comment]
Same on react-native 0.72.4

**Comment by AuroPick** [comment]
same on 0.72.6

**Comment by juanelo97** [comment]
Still happening on 0.71.8

**Comment by shubhamguptadream11** [comment]
This doesn't seems to be an issue with latest RN version: 0.75.2.
I tested this on release mode.
@rifad4u Please confirm here. If it is resolved we can close this issue.
