### ISSUE TITLE
 [ios] react-native 0.71.4 : use navigation 6 , Do not call dealloc function 

### ISSUE THREAD

**Issue by sunhongda** [facebook/react-native#37794]
### Description

code:

My app is a native app that has infiltrated the RN module. When closing RN and returning to the native module, RTCxxxView cannot trigger the dealloc function . (The RTCxxxViewManage dealloc function will trigger)

bad code:

```
 const {Navigator, Screen} = createStackNavigator();

        return <Navigator initialPage={'App3'}
                          headerShown={false}>

            <Screen name='App3' component={App3}
                    initialParams={nativeInitialParams.props}/>

        </Navigator>;

```
If the following code is used, the dealloc function can be triggered normally :

work code:

`        return   <App3/>`

### React Native Version

0.71.4

### Output of `npx react-native info`

 
System:
    OS: macOS 13.3.1
    CPU: (8) x64 Apple M1
    Memory: 22.06 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.17.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.6.3 - /usr/local/bin/npm
    Watchman: 2023.03.06.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /Users/jenkins/.rvm/gems/ruby-2.7.6/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: Flamingo 2022.2.1 Flamingo 2022.2.1
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.4 => 0.71.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

react": "18.2.0",
"react-native": "0.71.4",
"@react-navigation/bottom-tabs": "^6.5.7",
"@react-navigation/native": "^6.1.6",
"@react-navigation/stack": "^6.3.16",
"react-native-reanimated": "^3.2.0"
xcode 14.3

### Snack, code example, screenshot, or link to a repository

na

**Comment by cortinico** [comment]
> "@react-navigation/bottom-tabs": "^6.5.7",
> "@react-navigation/native": "^6.1.6",
> "@react-navigation/stack": "^6.3.16",

Hi @sunhongda 
Thanks for reporting this issue.

It seems like this issue is actually unrelated to React Native core but related to react-navigation. Please open this issue against this other repository:

https://github.com/react-navigation/react-navigation/issues

I'll be closing this but feel free to reopen if the other repo points back to us as a issue in the core of React Native.
