### ISSUE TITLE
Decode iOS module / method IDs from MessageQueue.spy() in prod build?

### ISSUE THREAD

**Issue by mikelehen** [facebook/react-native#37806]
### Description

I have a few iOS users hitting performance issues in my app that I can't reproduce.  I'm trying to leverage [MessageQueue.spy()](https://partiellkorrekt.de/2021/02/05/spy-on-the-react-native-messagequeue-in-style/) to debug their issue.  In dev builds, it seems very promising, but in the prod builds that I push to them via TestFlight, the `module`s and `method`s I receive in the spy() events are opaque integers.  Is there a way to decode them?  Maybe there's at least a lookup table of ModuleName=>id somewhere that I can use to resolve the modules I'm most interested in?

If this isn't possible / supported, no worries. Thanks for your time regardless.

### React Native Version

0.71.7

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 70.44 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
    Watchman: 2023.05.22.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.9862592
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 20.0.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: ^0.71.7 => 0.71.7
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Add this to an iOS React Native app:

```
import MessageQueue from 'react-native/Libraries/BatchedBridge/MessageQueue';
MessageQueue.spy((data) => {
  console.log(`${data.module}::${data.method}`);
});
```

Build / run debug version of app. See useful outputs:
```
NativeAnimatedModule::connectAnimatedNodeToView
NativeAnimatedModule::connectAnimatedNodes
KeyboardObserver::addListener
...
```

Build / run production version of app. See useless outputs:
```
64::12
64:11
10::12
...
```

### Snack, code example, screenshot, or link to a repository

See above

**Comment by Pranav-yadav** [comment]
https://github.com/facebook/react-native/blob/03f70bf995379f08a77abcf96bb0e31ff75ca8c3/packages/react-native/Libraries/BatchedBridge/MessageQueue.js#L91-L105

If I understood correctly what you're trying to do, then;
when calling the static `spy(...)`, *try* passing a `boolean` (`true`) instead of explicit `cb`, let me know if that helps, although, theoretically the explicitly passed cb is also trying to access the same things as in the implicitly assigned cb.

**Comment by mikelehen** [comment]
@Pranav-yadav Thanks for the reply.  Unfortunately `spy(true)` does not work properly for me because it ends up in an infinite loop, logging something like:

> 2023-06-09 21:55:25.062096-0700 MyApp[39526:8956099] [javascript] JS->N : 80.11([{"timestamp":1686372919.03,"category":"console","data":{"arguments":["JS->N : 80.11([{\"timestamp\":1686372918.653,\"category\":\"console\",\"data\":{\"arguments\":[\"JS->N : 80.11([{\\\"timestamp\\\":1686372918.572,\\\"category\\\":\\\"console\\\",\\\"data\\\":{\\\"arguments\\\":[\\\"JS->N :
> ...

I'm guessing the `console.log()` ends up triggering a call to a bridged module which triggers a (basically recursive) call of the spy() handler, and you end up with these log lines that look like some text has been JSON-encoded over and over...  My actual spy handler isn't actually logging directly to the console in order to avoid that.

But looking at the `spy()` code you pasted, I'm 98% sure it would have the same issue as my code, where the `module` / `method` end up being opaque ids in prod builds. 😢
