### ISSUE TITLE
Node 5 and npm 3

### ISSUE THREAD

**Issue by ide** [facebook/react-native#3780]
Node 5 is shipping with npm in less than an hour. Just a heads up that things like the website generation need to be updated to work with npm 3 before we can update the Travis suite to run Node 5.

**Comment by pangers** [comment]
Are we able to safely update to node 5 and npm 3?

**Comment by ide** [comment]
I haven't tried it but I believe it works if you're willing to take a 2-3x perf hit from npm 3.

**Comment by grabbou** [comment]
Haven't run into issues with npm 3 so far.

**Comment by satya164** [comment]
@ide It's been working great for me with Node 5 and npm 3.

**Comment by ide** [comment]
I'm going to close this since things have been working fine for several weeks with the latest Node, and the unit tests and website deployment now run on Node: https://github.com/facebook/react-native/pull/3802
