### ISSUE TITLE
Add class name into "View" tag in react native web

### ISSUE THREAD

**Issue by PurpleMonkey729** [facebook/react-native#37816]
### Description

Hello, everyone.
I want to add class name into "View" tag in react native web.
What is the most important is to not use Stylesheet.
I typed the code like following:

`<Image className="img_item_active" source={img_icon} style={styles.img_icon]} />`

But it didn't work.
So I covered this part with "div" tag like following.

`<div className="img_item_active"><Image source={img_icon} style={styles.img_icon]} /></div>`

But as I see, it's not perfect coding.
I want to add class name in "View" absolutely.
Is there any other method?
Please help me.

### React Native Version

0.71.7

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i9-10470 CPU @ 3.80GHz
    Memory: 15.37 GB / 31.52 GB
  Binaries:
    Node: 18.14.1 - C:\Program Files\nodejs\node.EXE    
    Yarn: Not Found
    npm: 9.3.1 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: Not Found
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.7 => 0.71.7
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

How to add class name into "View" tag in react native web.

### Snack, code example, screenshot, or link to a repository

`<Image className="img_item_active" source={img_icon} style={styles.img_icon]} />`

**Comment by PurpleMonkey729** [comment]
Thanks, @github-actions
But I think your reply is not related to my request.

**Comment by emmbyiringiro** [comment]
It's understandable to have a common styling  API  for both web and mobile platforms.  Adding CSS-like styling to React Native core is not technically supported by React staying engine - https://yogalayout.com/

Use recommended  styling pattern - https://necolas.github.io/react-native-web/docs/styling/#how-it-works 

You can convert existing CSS styles to JS objects - https://transform.tools/css-to-js

**Comment by PurpleMonkey729** [comment]
Thanks, @emmbyiringiro.
3 advises are helpful for me.
Can I use psuedo class in React Native Web?

**Comment by cortinico** [comment]
> I want to add class name into "View" tag in react native web.

Please open this question against react-native-web:
https://github.com/necolas/react-native-web/issues
