### ISSUE TITLE
[0.14-rc] Error running bundle with --dev=true

### ISSUE THREAD

**Issue by Purii** [facebook/react-native#3782]
I did an upgrade of two independent projects and always get an error, while launching them through their offline bundles.

**Upgrade:**
1. Update package.json
2. `npm i`
3. `react-native upgrade`: allow everything

I created the bundle with the following command:
`react-native bundle --entry-file index.ios.js --dev true --bundle-output ios/main.jsbundle --platform ios`

And now the app breaks while launching through the bundle with the following error, triggered by `RCTBatchedBridge.m`:
```
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'It looks like the implementationof __DEV__ has changed. Update -[RCTBatchedBridge loadSource:].'
```

Creating the bundle via `--dev false` seems fine.
Correct me, if this is a client error and none of RN itself.

**Comment by ide** [comment]
We probably need to cherry-pick https://github.com/facebook/react-native/commit/500ffa9b763d03e759e9b2897da7f4f7904934cf

**Comment by Purii** [comment]
Works for me :+1:

**Comment by eyaleizenberg** [comment]
I had the same issue on 0.14.1
Had to delete the main.jsbundle, fix all the image requirements according to the new api and then everything worked.

**Comment by luoyibu** [comment]
me too on 0.14.1. and how to fix it?

**Comment by satya164** [comment]
Closing this since it's been fixed. Feel free to reopen if it's still an issue for you.
