### ISSUE TITLE
Permission is null issue in android 12

### ISSUE THREAD

**Issue by ravindra3003** [facebook/react-native#37825]
### Description

Hello team,

According to android api leavel 31 I have updated code. before I am trying to enable bluetooth using `PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION)`. for android 12 I have tried with multiple request like this `const granted = await PermissionsAndroid.requestMultiple([ PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION, PermissionsAndroid.PERMISSIONS.BLUETOOTH_SCAN, PermissionsAndroid.PERMISSIONS.BLUETOOTH_CONNECT]);`.

I am getting error on only on android 12

### React Native Version

0.64.2

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 13.4
    CPU: (8) arm64 Apple M2
    Memory: 39.41 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.1.0 - /opt/homebrew/bin/node
    Yarn: Not Found
    npm: 8.19.4 - ~/Desktop/Ravindra/All_apps/My_player_perks/node_modules/.bin/npm
    Watchman: 2023.03.20.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /Users/macmini/.rvm/rubies/ruby-2.7.6/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK:
      API Levels: 23, 27, 28, 29, 30, 31, 33, 33
      Build Tools: 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 33.0.2
      System Images: android-31 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9619390
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.2 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

add bluetooth permission in android manifest file and try BleManager.enableBluetooth() it throws error on andorid 12 only

### Snack, code example, screenshot, or link to a repository

**Error is :** 
![image](https://github.com/innoveit/react-native-ble-manager/assets/96780748/c0493edd-ee29-4972-9148-16dd10f033e7)

**Code :**
### Old code that not compatible with android 12
![image](https://github.com/innoveit/react-native-ble-manager/assets/96780748/a25551e2-7f46-4491-b620-a5392431804a)

**Old AndroidManifest.xml**
![image](https://github.com/innoveit/react-native-ble-manager/assets/96780748/5a7c3966-f70e-4d9f-b57a-02a0b62db795)

**Android/build.gradle**
![image](https://github.com/innoveit/react-native-ble-manager/assets/96780748/1c7eabfc-af7b-48c2-b9d5-63a344f1f9ca)

Versions :
![image](https://github.com/innoveit/react-native-ble-manager/assets/96780748/74949ef5-4fcb-40c3-a943-7452f45e0d7b)

### After I updating this code for android 12 I got Permission is null Error
![image](https://github.com/innoveit/react-native-ble-manager/assets/96780748/a9584cb3-c70a-42b4-8c80-1b8546f13129)
**Updated AndroidManifest.xml**

![image](https://github.com/innoveit/react-native-ble-manager/assets/96780748/be9cb46c-af0a-457d-b532-82dc515c6a92)
![image](https://github.com/innoveit/react-native-ble-manager/assets/96780748/1c40fce4-9698-446e-a2cc-e27450ed7ebc)

please let me know what I am missing, what i need to update or upgrade

**Comment by Martyneris** [comment]
This issue still persists on react-native 0.64.2, when trying to check `PermissionsAndroid.PERMISSIONS.READ_MEDIA_IMAGES and PermissionsAndroid.PERMISSIONS.READ_MEDIA_VIDEO`
