### ISSUE TITLE
Layout inconsistency between Switch & SwitchAndroid

### ISSUE THREAD

**Issue by christopherdro** [facebook/react-native#3785]
### Switch

![Switch](http://www.chris.si/img/Screenshot_2015-10-30-02-45-13.png)
### SwitchAndroid
![SwtichAndroid](http://www.chris.si/img/Screenshot_2015-10-30-02-45-00.png)

The width value here seems to be incorrect.
https://github.com/facebook/react-native/blob/master/Libraries/Components/Switch/Switch.js#L113

No exactly sure if this applies to all devices so I wanted to check before making any kind of PR.

**Comment by brentvatne** [comment]
@christopherdro - images seem to be broken :O could you update?

**Comment by christopherdro** [comment]
@brentvatne loads for me on mobile

**Comment by christopherdro** [comment]
So there are a couple ways this can be fixed but wanted to get some feedback before submitted a PR. After talking to @mkonicek this last week at Reactive2015 he mentioned that size of the switch for android is calculated automatically whereas it need to be defined for IOS. 

So I'm wondering if we should remove this section entirely https://github.com/facebook/react-native/blob/2c7de35dee347b5d9a40b4e87862622e60ddf7d9/Libraries/Components/Switch/Switch.js#L111-L114, and then remove ``` props.style = [styles.rctSwitchAndroid, this.props.style];``` or alter it to ``` props.style = this.props.style;```

**Comment by mkonicek** [comment]
This looks like a bug, thanks for reporting!

@sahrens I think the fixed size was added as part of the universal Switch, can we remove this?
https://github.com/facebook/react-native/blob/2c7de35dee347b5d9a40b4e87862622e60ddf7d9/Libraries/Components/Switch/Switch.js#L111-L114
