### ISSUE TITLE
Destroy app on Android after tapping home button or back button

### ISSUE THREAD

**Issue by oney** [facebook/react-native#3790]
Running real Android device by signed APK. After tapping home button or back button, the app is destroyed. Then tap app icon, the app restarts. How to make the app not to be destroyed?
Some infos below.
The project is created by version 0.11.0, but I have added `onBackPressed` to `MainActivity`
```java
@Override
public void onBackPressed() {
    if (mReactInstanceManager != null) {
        mReactInstanceManager.onBackPressed();
    } else {
        super.onBackPressed();
    }
}
```
I run these command to generate apk
```
$ react-native bundle --platform android --dev false --entry-file index.android.js \
  --bundle-output android/app/src/main/assets/index.android.bundle \
  --assets-dest android/app/src/main/res/
$ cd android && ./gradlew assembleRelease
```
However, `__DEV__` in `index.android.bundle` is `true`
```
__DEV__ =
true;
```

**Comment by oney** [comment]
I am not familiar with Android. It's not related to React Native.
The following code makes it not destroy app when pressing back button.
In `MainActivity.java`
```
@Override
public void invokeDefaultOnBackPressed() {
    Intent setIntent = new Intent(Intent.ACTION_MAIN);
    setIntent.addCategory(Intent.CATEGORY_HOME);
    setIntent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
    startActivity(setIntent);
}
```

**Comment by grabbou** [comment]
CC: @mkonicek might be worth putting that into FAQ (had the same issue today)

**Comment by satya164** [comment]
Doesn't that just start a new activity when you press the back button? Not sure it's the ideal way.

**Comment by esutton** [comment]
https://github.com/react-navigation/react-navigation/issues/1372#issuecomment-299432731

Putting snippet below in your MainActivity will prevent back button from killing the activity. I'm not sure when you click the back button, on which screen, or what does exiting app mean. The snippet above prevents back button from executing the change or exiting the app if AppStack is the top router.

````
@Override
public void invokeDefaultOnBackPressed() {
    moveTaskToBack(true);
}
````

**Comment by tonywump** [comment]
I am able to block the Back button click by adding the following code.

```
import {BackHandler} from 'react-native';
...
componentDidMount(){
  BackHandler.addEventListener('hardwareBackPress', function () {
      return true;
    });
}
...
```

"react": "^16.3.1",
"react-native": "0.54.1",
