### ISSUE TITLE
Deep linking is not automatically opening when app in background mode on Android 12 but was working fine in Android 11.

### ISSUE THREAD

**Issue by Nilkanth2002** [facebook/react-native#37934]
### Description

I am encountering an issue where deep linking is not automatically opening my React Native app in Android 12 devices. However, deep linking functionality was working perfectly fine in Android 11.

**Expected behavior:**
The app should open automatically when a deep link is triggered, as it does in Android 11.

**Actual behavior:**
The app does not open automatically when a deep link is triggered in Android 12. Instead, the deep link URL opens in the web browser.

**Additional information:**
- I have verified that the intent filter for deep linking is correctly set up in the AndroidManifest.xml file.
- The app has the necessary QUERY_ALL_PACKAGES permission requested in the AndroidManifest.xml file.
- I am using the latest version of the react-native-navigation library (specify version number).
- Gradle and Android Gradle Plugin (AGP) versions are up to date (provide version numbers).
- The issue is reproducible on multiple physical devices and emulators running Android 12.
- There are no error messages or warnings related to deep linking in the logs.

### React Native Version

0.68.5

### Output of `npx react-native info`

OS: macOS 12.6.5
    CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
    Memory: 114.34 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 20.0.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.6.4 - /usr/local/bin/npm
    Watchman: 2023.05.01.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 23, 26, 27, 28, 29, 30, 31, 33
      Build Tools: 27.0.3, 28.0.3, 29.0.0, 29.0.1, 29.0.2, 29.0.3, 30.0.1, 30.0.2, 30.0.3, 31.0.0, 31.0.0, 31.0.0, 33.0.0, 33.0.1, 34.0.0, 34.0.0
      System Images: android-29 | Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-31 | Google Play Intel x86 Atom_64, android-34 | Google APIs Intel x86_64 Atom, android-Tiramisu | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.10121639
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.19 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.2 => 17.0.2 
    react-native: ^0.68.5 => 0.68.7 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

- Configure deep linking in AndroidManifest.xml as per the library documentation.
- Implement deep link handling in the MainActivity file.
- Test the app on a physical device running Android 12.
- Go to app in background mode.

### Snack, code example, screenshot, or link to a repository

**AndroidManifest.xml** 

       <intent-filter android:autoVerify="true" tools:targetApi="m">
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.BROWSABLE"/>
                <data android:scheme="http" />
                <data android:scheme="https" />
                <data android:host="ursafestaging.page.link" />
                <data android:host="ursafestaging.page.link" />
                <data android:scheme="https" />
                <data android:scheme="http" />
                <data android:host="ursafe.com" />
                <data android:host="ursafe.com" />
                <data android:scheme="https" android:host="*" />
                 <data android:scheme="ursafe-staging" />
                 <data android:scheme="ursafe-cba93" />
            </intent-filter>

**Comment by Pranav-yadav** [comment]
@Nilkanth2002 as the bot commented above you're on an unsupported version of RN, please either upgrade to one of the supported versions or search for a solution on StackOverflow.
Thanks.
