### ISSUE TITLE
React native android absolute position flatlist problem?

### ISSUE THREAD

**Issue by gorkemunluyurt** [facebook/react-native#37966]
### Description

In android, my absolute components do not appear in the flatlist. There is no such problem on iOS. Does anyone have any idea how to solve this problem?

### React Native Version

0.71.7

### Output of `npx react-native info`

I expect absolute positioned FlatList items to be visible on Android, just as they are on iOS.

### Steps to reproduce

Create Flatlist and render absolute positioned items.
Items are visible on ios but not on android

### Snack, code example, screenshot, or link to a repository

  const renderItem = ({ item, index }) => {
    

    if (item.name) {
      

      return (
        <View style={[styles.nextMatchContainer, { zIndex: 5 - index }]}>
          <SwipeableCard match={item} />
        </View>
      )
    }
  }

**Comment by Pranav-yadav** [comment]
@gorkemunluyurt
Please execute `npx react-native info` in your project directory and paste the output of the same under the "Output of `npx react-native info`" subheading in the issue description.
