### ISSUE TITLE
Add support for WebView component on Android

### ISSUE THREAD

**Issue by tomkur** [facebook/react-native#3796]
It is mentioned in [several](https://facebook.github.io/react-native/docs/known-issues.html) [different](https://github.com/facebook/react-native/issues/2701) [places](https://github.com/facebook/react-native/pull/3604) that react-native does not offer currently WebView component on Android.
I think it's good to have a dedicated issue to keep track of the progress of this task.

**Comment by thstarshine** [comment]
+1. It'll be great if there's a dedicated schedule for the release.

**Comment by kinhunt** [comment]
+1

**Comment by watzak** [comment]
+1

**Comment by gerbenupinion** [comment]
+1

**Comment by bergl** [comment]
+1

**Comment by dgoujard** [comment]
+1

**Comment by AlexErofeev** [comment]
+1

**Comment by macnibblet** [comment]
+1

**Comment by lucasferreira** [comment]
I don't know if helps to much, but I made a module for Android WebView:
https://github.com/lucasferreira/react-native-webview-android

I think that can be util, it was simple, but do the main work of shows web pages inside android apps built in React Native.

**Comment by leeight** [comment]
+1

**Comment by aleki** [comment]
+1

**Comment by prenaux** [comment]
+1

**Comment by qbig** [comment]
+1, though it's very handy to just add custom native mod for the moment like how ppl did it here.
https://github.com/race604/ZhiHuDaily-React-Native

**Comment by mkonicek** [comment]
Thanks for the +1s, I'll work on this.

**Comment by mkonicek** [comment]
ETA sometime end of next week.

**Comment by alvaromb** [comment]
Very interested in having this feature too :smile:

**Comment by aleki** [comment]
ETA?

**Comment by satya164** [comment]
@aleki It's on the 0.16.0 roadmap - https://github.com/facebook/react-native/issues/4327

**Comment by aleki** [comment]
@satya164 Thank you!

**Comment by kabukky** [comment]
Looks like it didn't make it into 0.16.

**Comment by tomkur** [comment]
Apparently the support was added in 0.17:
https://github.com/facebook/react-native/releases/tag/v0.17.0.

Thanks, @mkonicek!
