### ISSUE TITLE
Text style: text transformation

### ISSUE THREAD

**Issue by mschipperheyn** [facebook/react-native#3797]
I find myself wishing for the option of text transformation: uppercase etc.

Even though these things can be easily achieved with Javascript, when your theming e.g. Material Design, with its penchant for capitalized buttons, it would make life easier.

**Comment by jsierles** [comment]
Hey mschipperheyn, thanks for reporting this issue!

React Native, as you've probably heard, is getting really popular and truth is we're getting a bit overwhelmed by the activity surrounding it. There are just too many issues for us to manage properly.

- If you **don't know how to do something** or **something is not working as you expect but not sure it's a bug**, please ask on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native) with the tag `react-native` or for more real time interactions, ask on [Discord](https://discord.gg/0ZcbPKXt5bZjGY5n) in the #react-native channel.

- If this is a **feature request or a bug** that you would like to be fixed, please report it on [Product Pains](https://productpains.com/product/react-native/). It has a ranking feature that lets us focus on the most important issues the community is experiencing.

- We welcome clear issues and PRs that are ready for in-depth discussion. Please provide **screenshots** where appropriate and always mention the **version** of React Native you're using. Thank you for your contributions!
