### ISSUE TITLE
Execution failed for task ':app:signReleaseBundle'. > A failure occurred while executing com.android.build.gradle.internal.tasks.FinalizeBundleTask$BundleToolRunnable    > java.lang.NullPointerException (no error message)

### ISSUE THREAD

**Issue by GouravNainwaya** [facebook/react-native#37988]
@cortinico issue is related with react-navigation 's drawable icons clean drawable folders from android folder then ./gradlew clean fixed this issue. 

but I want to ask some different issue
```
> Task :app:signReleaseBundle FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:signReleaseBundle'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.FinalizeBundleTask$BundleToolRunnable
   > java.lang.NullPointerException (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings

Execution optimizations have been disabled for 11 invalid unit(s) of work during this build to ensure correctness.
Please consult deprecation warnings for more details.

BUILD FAILED in 44s
522 actionable tasks: 14 executed, 508 up-to-date
```
release building is crashing in %99 
did you faced with this

_Originally posted by @necpfzlakay in https://github.com/facebook/react-native/issues/35447#issuecomment-1327632626_

**Comment by iamevansobeng** [comment]
This happens when you don't add your key.properties in the root of your android folder

**Comment by Gabriele042010** [comment]
> > This happens when you don't add your key.properties in the root of your android folder
> 
> Uff, I guess I lost my file some day and didn't notice. Just wasted 3 hours on that, thank you so much!

I have the same issue, but I can't find my key.properties file, where I have to search?

**Comment by micahlt** [comment]
@GouravNainwaya did you ever solve this?  I'm encountering the same issue.

**Comment by billylo1** [comment]
> > > This happens when you don't add your key.properties in the root of your android folder
> > 
> > 
> > Uff, I guess I lost my file some day and didn't notice. Just wasted 3 hours on that, thank you so much!
> 
> I have the same issue, but I can't find my key.properties file, where I have to search?

If you are on Mac, Time machine backups.

**Comment by Modi08** [comment]
I have the key properties file but it still doesn't work

**Comment by iamevansobeng** [comment]
> > > This happens when you don't add your key.properties in the root of your android folder
> > 
> > 
> > Uff, I guess I lost my file some day and didn't notice. Just wasted 3 hours on that, thank you so much!
> 
> I have the same issue, but I can't find my key.properties file, where I have to search?

this is a sample content of the key.properties file. the file should be in the root of the android folder

```
storePassword=XXXXXXXX
keyPassword=XXXXXXXX
keyAlias=alias
storeFile=/Users/blackjack/somekey.jks
```

**Comment by pirzada-jahanzaib** [comment]
> This happens when you don't add your key.properties in the root of your android folder

i added and issue is resolved.
