### ISSUE TITLE
debug Running command "cd android && gradlew.bat app:installDebug -PreactNativeDevServerPort=8081"

### ISSUE THREAD

**Issue by gwonsuji** [facebook/react-native#37990]
### Description

As mentioned in previous issues, running npx react-native run-android on the current vscode or terminal in Android studio won't install the app.
![image](https://github.com/facebook/react-native/assets/60372704/220ed1b8-4772-4a13-92ef-9477201aa9b7)

```
$ npx react-native run-android --verbose
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 1873 file(s) to forward-jetify. Using 6 workers...
info Starting JS server...
info Launching emulator...
info Successfully launched emulator.
info Installing the app...
debug Running command "cd android && gradlew.bat app:installDebug -PreactNativeDevServerPort=8081"
Error: Could not find or load main class
Caused by: java.lang.ClassNotFoundException:

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
Error: Could not find or load main class
```

Even apps that haven't touched any settings since creation won't run on my emulator. The emulator runs, but only the app cannot be installed. I'm testing it by downloading an app through run in Android studio or by dragging it myself after making an apk. :(

It's an issue that I left behind before. I think it would be good to refer to it.
https://github.com/microsoft/vscode-react-native/issues/1978

### React Native Version

0.63.4

### Output of `npx react-native info`

System:
OS: Windows 10 10.0.19045
CPU: (6) x64 Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
Memory: 2.17 GB / 15.94 GB
Binaries:
Node: 16.14.1 - C:\Program Files\nodejs\node.EXE
Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
npm: 8.5.0 - C:\Program Files\nodejs\npm.CMD
Watchman: Not Found
SDKs:
Android SDK:
Android NDK: 22.1.7171670
Windows SDK: Not Found
IDEs:
Android Studio: Version 2020.3.0.0 AI-203.7717.56.2031.7678000
Visual Studio: Not Found
Languages:
Java: 11.0.18 - C:\Program Files\Common Files\Oracle\Java\javapath\javac.EXE
Python: 2.7.9 - C:\Users\weits\AppData\Local\python2\python.EXE
npmPackages:
@react-native-community/cli: Not Found
react: 16.13.1 => 16.13.1
react-native: 0.63.4 => 0.63.4
react-native-windows: Not Found
npmGlobalPackages:
react-native: Not Found

### Steps to reproduce

1. I created a project with `npx react-native init appName`.
2. I ran the server with `npx react-native start`.
3. I ran it as `npx react-native run-android`.

### Snack, code example, screenshot, or link to a repository

I don't think you need an example because you just need to start the project.

**Comment by hanarotg** [comment]
Hi @gwonsuji , I'm not sure if it's helpful because I don't know much about vscode-react-native, not the Windows environment.

It seems android SDK is not applied. even if your android SDK installed.

please check some instructions below.

## check the actual location of your Android SDK 

Android Studio "Settings" dialog, under Appearance & Behavior → System Settings → Android SDK.

> If you cannot find the actual location, please install the SDK in the correct way.

## check ANDROID_HOME environment variable

please check your ANDROID_HOME user variable that points to the path to your Android SDK. 

![image](https://github.com/facebook/react-native/assets/34812887/89e56f35-f67b-4418-b25e-1a9d49e113c2)

> If you cannot find ANDROID_HOME or ANDROID_HOME isn't point your Android SDK path, follow [official instruction](https://reactnative.dev/docs/environment-setup?guide=native&os=windows&platform=android)

## check ANDROID_HOME has been added

Open your powershell, Copy and paste `Get-ChildItem -Path Env:\` into powershell. 

If your SDK is well applied, you may verify ANDROID_HOME has been added

**Comment by gwonsuji** [comment]
Hello. I already added Android_home. I also added Android_home to the Path.

Not only that, but I also added tools, platform-tools, emulator, cmdline-tools\latest\bin in the SDK folder to Path.

Even if it's not just vscode, but if you run it with the command `npx react-native run-android` in the terminal of Android Studio, the app won't be installed equally.

**Comment by gwonsuji** [comment]
Hello @hanarotg. I already added Android_home. I also added Android_home to the Path.

Not only that, but I also added tools, platform-tools, emulator, cmdline-tools\latest\bin in the SDK folder to Path.

Even if it's not just vscode, but if you run it with the command npx react-native run-android in the terminal of Android Studio, the app won't be installed equally.
