### ISSUE TITLE
ScrollView onScroll only fires once

### ISSUE THREAD

**Issue by nick** [facebook/react-native#38]
I have a component that looks something like this:

```
var ScrollTest = React.createClass({

  render() {
    return (
      <ScrollView onScroll={this.onScroll}>
        <View style={{ height: 2000 }} />
      </ScrollView>
    );
  },

  onScroll: function(e) {
    console.log("Scroll", e)
  }
});
```

Right now I'm only seeing the log message when I start a new scroll action. Is there a way to get that onScroll event to fire on every frame? I want the height of another component to depend on the scroll position of this ScrollView component. (trying to duplicate the behavior you see on the iOS Weather app when you scroll down).

**Comment by cleercode** [comment]
I set `throttleScrollCallbackMS={16}` and the warning doesn't show but I seem to still only get one event fired.

**Comment by ssssssssssss** [comment]
Don't work for listview

**Comment by nicklockwood** [comment]
The throttleScrollCallbacksMS property is now called scrollEventThrottle.

**Comment by nicklockwood** [comment]
Looks like the warning wasn't updated when the property name was changed.
