### ISSUE TITLE
Getting com.facebook.react.bridge.ReactNoCrashSoftException: Cannot find EventEmitter for receivedTouches in my native library

### ISSUE THREAD

**Issue by zabojad** [facebook/react-native#38000]
### Description

I'm currently trying to make an existing lib compatible with both old and new architecture. [Here is my current work on this](https://github.com/zabojad/react-native-hole-view/tree/%40thomasfetiveau/new-architecture).

I'm almost done on Android but when new arch is enabled, I'm getting this error:

```
 E  Unhandled SoftException
      com.facebook.react.bridge.ReactNoCrashSoftException: Cannot find EventEmitter for receivedTouches: ReactTag[10] UIManagerType[2] EventName[topTouchStart]
      at com.facebook.react.uimanager.events.ReactEventEmitter.receiveTouches(ReactEventEmitter.java:103)
      at com.facebook.react.uimanager.events.TouchEvent.dispatchModern(TouchEvent.java:192)
      at com.facebook.react.uimanager.events.EventDispatcherImpl$DispatchEventsRunnable.run(EventDispatcherImpl.java:370)
      at android.os.Handler.handleCallback(Handler.java:938)
      at android.os.Handler.dispatchMessage(Handler.java:99)
      at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
      at android.os.Looper.loopOnce(Looper.java:226)
      at android.os.Looper.loop(Looper.java:313)
      at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
      at java.lang.Thread.run(Thread.java:1012)
```

This happens [there in the code of the native component](https://github.com/zabojad/react-native-hole-view/blob/%40thomasfetiveau/new-architecture/android/src/main/java/com/ibitcy/react_native_hole_view/RNHoleView.kt#L250).

```java
    private fun passTouchEventToViewAndChildren(v: ViewGroup, ev: MotionEvent) {
        val childrenCount = v.childCount
        for (i in 0 until childrenCount) {
            val child = v.getChildAt(i)
            if (child.id > 0 && isViewInsideTouch(ev, child) && child.visibility == View.VISIBLE) {
                try {
                    mEventDispatcher.dispatchEvent(
                            TouchEvent.obtain(
                                    child.id,
                                    TouchEventType.START,
                                    ev,
                                    ev.eventTime,
                                    ev.x,
                                    ev.y,
                                    TouchEventCoalescingKeyHelper()
                            )
                    )
                } catch (e: Exception) {}
                if (child is ViewGroup && child.childCount > 0) {
                    passTouchEventToViewAndChildren(child, ev)
                }
            }
        }
    }
```

Is there anything I should know about the new arch to make this work?

### React Native Version

0.71.8

### Output of `npx react-native info`

$ npx react-native info
info Fetching system and libraries information...
System:
    OS: macOS 13.0.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 923.66 MB / 64.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.14.2/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
    Watchman: 2022.12.05.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /Users/thomasfetiveau/.rvm/gems/ruby-3.0.3/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK:
      API Levels: 18, 23, 24, 25, 26, 27, 28, 29, 30, 31, 33
      Build Tools: 23.0.1, 23.0.3, 25.0.0, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.2, 28.0.3, 29.0.0, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 31.0.0, 33.0.0
      System Images: android-19 | Google APIs Intel x86 Atom, android-21 | Google APIs Intel x86 Atom, android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-25 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-28 | Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-29 | Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: 20.1.5948944
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.8 => 0.71.8 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Just run the example app of the module with an Android project with new arch enabled and touch through the hole on the elements (button) behind it.

### Snack, code example, screenshot, or link to a repository

https://github.com/zabojad/react-native-hole-view/tree/%40thomasfetiveau/new-architecture

**Comment by zabojad** [comment]
Hey @cortinico ! Sorry to disturb but I saw your answer on this issue https://github.com/facebook/react-native/issues/37462 

I thought you might be able to help here...

**Comment by javache** [comment]
The new architecture requires you to pass a `surfaceId` to [`TouchEvent.obtain`](https://github.com/facebook/react-native/blob/main/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/events/TouchEvent.java#L56). [Example of how it's used](https://github.com/facebook/react-native/blob/main/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/JSTouchDispatcher.java#L134).

**Comment by cortinico** [comment]
Thanks for the response @javache 👍 That's the correct one.

**Comment by zabojad** [comment]
Thank you @javache and @cortinico for your answers but it doesn't solve the problem. Even with this param, I'm getting:

```
E  Unhandled SoftException
com.facebook.react.bridge.ReactNoCrashSoftException: Cannot find EventEmitter for receivedTouches: ReactTag[10] UIManagerType[2] EventName[topTouchStart]
	at com.facebook.react.uimanager.events.ReactEventEmitter.receiveTouches(ReactEventEmitter.java:103)
	at com.facebook.react.uimanager.events.TouchEvent.dispatchModern(TouchEvent.java:192)
	at com.facebook.react.uimanager.events.EventDispatcherImpl$DispatchEventsRunnable.run(EventDispatcherImpl.java:370)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
	at java.lang.Thread.run(Thread.java:1012)
```

I do not know if that is related but I'm getting the `EventDispatcher` I use like this:

```kotlin
// ...
        val uiManager = (context as ReactContext).getNativeModule(UIManagerModule::class.java)
        mEventDispatcher = uiManager!!.eventDispatcher
// ...
```

Is that wrong with the new arch? The use of `UIManagerModule` isn't deprecated with Fabric?

**Comment by zabojad** [comment]
Also, I'm always getting the value `1` when getting a surface if:

```kotlin
println("debug 1 "+UIManagerHelper.getSurfaceId(v))
println("debug 2 "+UIManagerHelper.getSurfaceId(getRoot()))
println("debug 3 "+UIManagerHelper.getSurfaceId(this as ViewGroup))
```

**Comment by zabojad** [comment]
OK, I've managed to fix the problem by chaging the way to get the EventDispatcher I'm using.

I do not use this anymore:

```kotlin
        val uiManager = (context as ReactContext).getNativeModule(UIManagerModule::class.java)
        mEventDispatcher = uiManager!!.eventDispatcher
```

I now do this:

```kotlin

    private fun passTouchEventToViewAndChildren(v: ViewGroup, ev: MotionEvent) {
        val childrenCount = v.childCount
        for (i in 0 until childrenCount) {
            val child = v.getChildAt(i)
            if (child.id > 0 && isViewInsideTouch(ev, child) && child.visibility == View.VISIBLE) {
                try {
                    val mmEventDispatcher = UIManagerHelper.getEventDispatcherForReactTag((context as ReactContext), child.id) ;
                    mmEventDispatcher!!.dispatchEvent(
                            TouchEvent.obtain(
                                    UIManagerHelper.getSurfaceId(child),
                                    child.id,
                                    TouchEventType.START,
                                    ev,
                                    ev.eventTime,
                                    ev.x,
                                    ev.y,
                                    TouchEventCoalescingKeyHelper()
                            )
                    )
                } catch (e: Exception) {
                }
                if (child is ViewGroup && child.childCount > 0) {
                    passTouchEventToViewAndChildren(child, ev)
                }
            }
        }
    }
```

And it now works ! Thank you guys for your help ! :)

**Comment by zabojad** [comment]
And the best part is that works on both old and new arch...

**Comment by ElangoPrince** [comment]
@zabojad Can you tell me which file i need to update above code?
