### ISSUE TITLE
Typescript DimensionValue custom UI libraries and variables ( react-native-extended-stylesheet )

### ISSUE THREAD

**Issue by meabed** [facebook/react-native#38027]
### Description

The new types for DimensionValue is strongly typed and throw error when using custom libraries the use custom variables for padding / margin / sizes etc.. 

https://github.com/facebook/react-native/blob/main/packages/react-native/Libraries/StyleSheet/StyleSheetTypes.d.ts#L21C26-L26C10

For example: when using this library with the new types https://github.com/vitalets/react-native-extended-stylesheet#local-variables 
 
```
  card: {
    justifyContent: 'center',
    padding: '$spacing2',
    backgroundColor: '$surfaceColor',
    borderWidth: 4,
    borderStyle: 'solid',
    borderColor: '$surfaceVariant2Color',
    borderRadius: 16,
  }
# where $spacing2 is variable, it will fail in types because it doesn't match the typescript string pattern
```

It would be great to have flexibility for this type to enable easy integration of UI and styling libraries 
 

### React Native Version

0.72.0

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 13.4.1
    CPU: (12) arm64 Apple M2 Max
    Memory: 34.44 GB / 96.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.3.1 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.7.2 - /opt/homebrew/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: Flamingo 2022.2.1 Patch 2 Flamingo 2022.2.1 Patch 2
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.6 - /java/current/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.11 => 0.71.11
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
info React Native v0.72.0 is now available (your project is running on v0.71.11).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.72.0
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.71.11
info For more info, check out "https://reactnative.dev/docs/upgrading".

### Steps to reproduce

- Start project with typesprect and react native 0.72.0 
- install react-native-extended-stylesheet
- add types to styling method 
```
import { Dimensions, ImageStyle, TextStyle, ViewStyle } from 'react-native';
import EStyleSheet from 'react-native-extended-stylesheet';

EStyleSheet.build({
  $spacing1: 2
});
type NamedStyles<T> = { [P in keyof T]: ViewStyle | TextStyle | ImageStyle };

function createEStyleSheet<T extends NamedStyles<T> | { $outline?: boolean }>(
  styles: T | NamedStyles<T> | NamedStyles<any>
): T {
  return EStyleSheet.create(styles) as T;
}

// this will fail in typescript
const styles = createEStyleSheet({
  card: {
    paddingVertical: '$spacing1',
  }
});

```

### Snack, code example, screenshot, or link to a repository

https://snack.expo.dev/@meabed/rn72stylets

**Comment by lunaleaps** [comment]
Hmm should `react-native-extended-stylesheet` be updating their types to be taking a superset of styles?

Like `EStyleSheet.create: EStyleSheet -> StyleSheet`

**Comment by meabed** [comment]
I tried that, but the override or change in the string type pattern will break any other UI library because they depends on react native types imported like ViewStyle.

So i have modified e style sheet but the types will be accepted by View or Text unless it's casted back to original react native types 'as ViewStyle'

**Comment by kelset** [comment]
I agree with Luna, it's on the `react-native-extended-stylesheet` to adjust their typings
