### ISSUE TITLE
I get an error when I start my react-native app in version 0.72 (FAILURE: Build failed with an exception.)

### ISSUE THREAD

**Issue by honeybadger4768** [facebook/react-native#38034]
### Description

after the released update i created a new app to try version 0.72 but when i start the app gradle gives me an error message

### React Native Version

0.72.0

### Output of `npx react-native info`

furkan@furkan-MS-7C13:~/Desktop/hellorn$ npx react-native info
info Fetching system and libraries information...
System:
  OS: Linux 5.15 Linux Mint 21.1 (Vera)
  CPU: (4) x64 Intel(R) Core(TM) i3-9100F CPU @ 3.60GHz
  Memory: 3.96 GB / 15.56 GB
  Shell:
    version: 5.1.16
    path: /bin/bash
Binaries:
  Node:
    version: 18.16.1
    path: /opt/nodejs/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/nodejs/bin/yarn
  npm:
    version: 9.5.1
    path: /opt/nodejs/bin/npm
  Watchman:
    version: 4.9.0
    path: /usr/bin/watchman
SDKs:
  Android SDK:
    API Levels:
      - "33"
      - "34"
    Build Tools:
      - 30.0.3
      - 33.0.0
      - 34.0.0
    System Images:
      - android-30 | Google APIs Intel x86_64 Atom
      - android-33 | Google APIs Intel x86_64 Atom
      - android-33 | Google Play Intel x86_64 Atom
      - android-34 | Google APIs Intel x86_64 Atom
    Android NDK: Not Found
IDEs:
  Android Studio: Not Found
Languages:
  Java: Not Found
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.0
    wanted: 0.72.0
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

### Steps to reproduce

furkan@furkan-MS-7C13:~/Desktop/hellorn$ yarn start
yarn run v1.22.19
$ react-native start

                        ▒▒▓▓▓▓▒▒
                     ▒▓▓▓▒▒░░▒▒▓▓▓▒
                  ▒▓▓▓▓░░░▒▒▒▒░░░▓▓▓▓▒
                 ▓▓▒▒▒▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▓▓
                 ▓▓░░░░░▒▓▓▓▓▓▓▒░░░░░▓▓
                 ▓▓░░▓▓▒░░░▒▒░░░▒▓▒░░▓▓
                 ▓▓░░▓▓▓▓▓▒▒▒▒▓▓▓▓▒░░▓▓
                 ▓▓░░▓▓▓▓▓▓▓▓▓▓▓▓▓▒░░▓▓
                 ▓▓▒░░▒▒▓▓▓▓▓▓▓▓▒░░░▒▓▓
                  ▒▓▓▓▒░░░▒▓▓▒░░░▒▓▓▓▒
                     ▒▓▓▓▒░░░░▒▓▓▓▒
                        ▒▒▓▓▓▓▒▒

                Welcome to Metro v0.76.5
              Fast - Scalable - Integrated

r - reload the app
d - open developer menu
i - run on iOS
a - run on Android

a

info Opening the app on Android...
info JS server already running.
info Launching emulator...

info 💡 Tip: Make sure that you have set up your development environment correctly, by running react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor 

FAILURE: Build failed with an exception.

* Where:
Build file '/home/furkan/Desktop/hellorn/android/app/build.gradle' line: 1

* What went wrong:
A problem occurred evaluating project ':app'.
> Failed to apply plugin 'com.android.internal.version-check'.
   > Could not create plugin of type 'VersionCheckPlugin'.
      > Could not generate a decorated class for type VersionCheckPlugin.
         > Lcom/android/ide/common/repository/GradleVersion;

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 34s

### Snack, code example, screenshot, or link to a repository

no code

**Comment by clexanp** [comment]
how you solved that error ?

**Comment by honeybadger4768** [comment]
hello, after deleting $HOME/.gradle folder
i restarted application and problem got solved

**Comment by AustineGwa** [comment]
This issue is caused by a corrupted gradle in cache  or incomplete download .

**Comment by EngPeterAtef** [comment]
same issue

**Comment by cetfu** [comment]
you need to delete the gradle folder in your home directory
/home/user/.gradle for linux 
/Users/username/.gradle for windows

this is how I solved my problem

**Comment by BrittosMonteiro** [comment]
That worked here, man.

Thank you for your help!

**Comment by cetfu** [comment]
You are welcome. I apologize for seeing your message late
but here is how I wrote about my problem https://github.com/facebook/react-native/issues/38034#issuecomment-1616615329
