### ISSUE TITLE
while doing pod install, encountering following error Invalid `Podfile` file: /node_modules/react-native/scripts/react_native_pods_utils/script_phases.rb:39: syntax error, unexpected <<     template =<<~EOS

### ISSUE THREAD

**Issue by himanshuzeptonow** [facebook/react-native#38032]
### New Version

0.71.11

### Old Version

0.68.7

### Build Target(s)

iOS, while doing pod install

### Output of `react-native info`

System:
    OS: macOS 13.2.1
    CPU: (12) arm64 Apple M2 Pro
    Memory: 112.66 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.16.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.5.1 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.5.2 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.10121639
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 20.0.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.10 => 0.71.10
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Issue and Reproduction Steps

run command - pod install

error - 

[!] Invalid `Podfile` file: /node_modules/react-native/scripts/react_native_pods_utils/script_phases.rb:39: syntax error, unexpected <<
    template =<<~EOS
                ^
/node_modules/react-native/scripts/react_native_pods_utils/script_phases.rb:40: unknown regexp options - ll
/node_modules/react-native/scripts/react_native_pods_utils/script_phases.rb:41: dynamic constant assignment
        RCT_SCRIPT_POD_INSTALLATION_ROOT=$(pwd)
                                         ^
/node_modules/react-native/scripts/react_native_pods_utils/script_phases.rb:41: `$(' is not allowed as a global variable name
/node_modules/react-native/scripts/react_native_pods_utils/script_phases.rb:41: syntax error, unexpected end-of-input
        RCT_SCRIPT_POD_INSTALLATION_ROOT=$(pwd)
                                          ^.

 #  from ios/Podfile:1
 #  -------------------------------------------
 >  require_relative '../node_modules/react-native/scripts/react_native_pods'
 #  require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

**Comment by blakef** [comment]
That's an unexpected error.  Before we go any deeper can you:
1. `node_modules` and run `yarn install` or `npm install` (whichever you normally do)
2. _exactly follow_ the [INFO steps in the guide](https://reactnative.dev/docs/environment-setup?platform=ios#creating-a-new-application). 

That way we'll have a good baseline to figure out what's happening.

**Comment by himanshuzeptonow** [comment]
even after crating a new project getting same issue

**Comment by blakef** [comment]
A couple of more steps will be really helpful 😀, I appreciate your patience. 

From inside your project folder can you share the output of these commands exactly (copy and paste please):
```
❯ bundle exec pod --version
1.12.1
❯ bundle exec ruby --version
ruby 2.7.6p219 (2022-04-12 revision c9c2245c0a) [arm64-darwin21]
❯ cd ios
❯ bundle exec pod install
Framework build type is static library
[Codegen] Generating ./build/generated/ios/React-Codegen.podspec.json
Analyzing dependencies
[Codegen] Found FBReactNativeSpec
[Codegen] Found rncore
Downloading dependencies
Generating Pods project
Setting REACT_NATIVE build settings
Setting CLANG_CXX_LANGUAGE_STANDARD to c++17 on /Users/blakef/src/rn/RN073/ios/RN073.xcodeproj
Pod install took 8 [s] to run
Integrating client project
Pod installation complete! There are 63 dependencies from the Podfile and 53 total pods installed.

```

**Comment by Pranav-yadav** [comment]
Well, with Blake's suggestion the root cause will be clear which is likely due to a version mismatch (wrong version) of the pod or something else.

P.S. As a last go, you may try 2nd and 3rd answer from the below thread _only after verifying_ :)
https://stackoverflow.com/questions/72130276/invalid-podfile-file-unexpected-template-eos

**Comment by himanshuzeptonow** [comment]
bundle exec pod --version
 > 1.5.2
 bundle exec ruby --version
 > ruby 2.6.10p210 (2022-04-12 revision 67958) [universal.arm64e-darwin22]
 cd ios && bundle exec pod install
 > [!] Invalid `Podfile` file: node_modules/react-native/scripts/react_native_pods_utils/script_phases.rb:39: syntax error, unexpected <<
    template =<<~EOS
                ^
node_modules/react-native/scripts/react_native_pods_utils/script_phases.rb:40: unknown regexp options - ll
node_modules/react-native/scripts/react_native_pods_utils/script_phases.rb:41: dynamic constant assignment
        RCT_SCRIPT_POD_INSTALLATION_ROOT=$(pwd)
                                         ^
node_modules/react-native/scripts/react_native_pods_utils/script_phases.rb:41: `$(' is not allowed as a global variable name
node_modules/react-native/scripts/react_native_pods_utils/script_phases.rb:41: syntax error, unexpected end-of-input
        RCT_SCRIPT_POD_INSTALLATION_ROOT=$(pwd)
                                          ^.

ios/Podfile:1
 #  -------------------------------------------
 >  require_relative '../node_modules/react-native/scripts/react_native_pods'
 #  require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
 #  -------------------------------------------

**Comment by himanshuzeptonow** [comment]
issue is fixed. https://stackoverflow.com/a/75890143
