### ISSUE TITLE
Blob.slice Parameter contentType does not exists in iOS and Android.

### ISSUE THREAD

**Issue by trashcoder** [facebook/react-native#38058]
### Description

In react natives implementation of blob.slice the contentType parameter is missing:

https://developer.mozilla.org/en-US/docs/Web/API/Blob/slice

### React Native Version

0.71.6

### Output of `npx react-native info`

error: unknown command 'info'
(Did you mean init?)

### Steps to reproduce

Open a new react native project and add a line with a blob.slice command. There is no contentType parameter. And so you will not see a value for .type on Android and iOS on a sliced blob. On React Native Web slicing works as expected.

### Snack, code example, screenshot, or link to a repository

https://snack.expo.dev/kS7da4tSk

**Comment by trashcoder** [comment]
i upgraded to 0.71.11. 
Within the class "Blob" the method "slice" still doesn't support the third parameter contentType.

**Comment by trashcoder** [comment]
System:
    OS: macOS 13.4
    CPU: (8) arm64 Apple M1 Pro
    Memory: 67.23 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 19.1.0 - ~/.nvm/versions/node/v19.1.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v19.1.0/bin/yarn
    npm: 9.3.1 - ~/.nvm/versions/node/v19.1.0/bin/npm
    Watchman: 2023.05.22.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: Flamingo 2022.2.1 Patch 2 Flamingo 2022.2.1 Patch 2
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.11 => 0.71.11
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by blakef** [comment]
I can confirm this.  Would you be interested in putting together a fix as a pull request?  It looks reasonably straightforward between updating [Blob#slice](https://github.com/facebook/react-native/blob/main/packages/react-native/Libraries/Blob/Blob.js#L84-L119) and adding a test to confirm the parameter is passed.

**Comment by trashcoder** [comment]
I could try. But i never made a pull request before and i'm not familiar with the react-native code.

**Comment by trashcoder** [comment]
ok, i made a change to the parameters. But i don't know how to test it.
How can i make "npx react-native init AwesomeProject" with my local react-native repo?

**Comment by blakef** [comment]
Great!  You're not far off now, I'd recommend:
- updating the [unit test](https://github.com/facebook/react-native/blob/main/packages/react-native/Libraries/Blob/__tests__/Blob-test.js#L58-L79) with your change to check that the `Blob` it generates has the correct type.
- run the test locally to confirm it: `yarn run test Blob-test.js`
- [create a PR](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) for us to review.  You'll want to work through the [contributing steps](https://reactnative.dev/contributing/overview#contributing-code).
