### ISSUE TITLE
Android XMLHttpRequest "onreadystatechange" event only fired once when "readyState == 4"

### ISSUE THREAD

**Issue by qbig** [facebook/react-native#3805]
The same code when run on iOS, onreadystatechange would be fired 3 times with request.readyState equals 2, 3, 4 respectively.

**Comment by nucleartux** [comment]
I think this is duplicate of my issue https://github.com/facebook/react-native/issues/3772

**Comment by qbig** [comment]
As @nucleartux mentioned. Closed as dup.
