### ISSUE TITLE
onFocus not being called in Touchable* Android

### ISSUE THREAD

**Issue by ayush547** [facebook/react-native#38055]
### Description

[onFocus](https://reactnative.dev/docs/touchablewithoutfeedback#onfocus) is provided as a part of TouchableWithoutFeedback and is also inherited by other [Touchables](https://reactnative.dev/docs/touchableopacity#touchablewithoutfeedback-props). 

This callback is not being executed even when focus is being placed onto the touchable.

Tested with expo and rn-cli both on emulator and physical device.

Additionally, it would be nice to have focus events be applicable for all view in general on Android atleast, this would enable custom styling and a11y specific changes.

### React Native Version

0.71.10

### Output of `npx react-native info`

System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 8.76 GB / 31.71 GB
  Binaries:
    Node: 18.5.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.12.1 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.19041.0
  IDEs:
    Android Studio: AI-212.5712.43.2112.8609683
    Visual Studio: 16.11.33801.447 (Visual Studio Community 2019)
  Languages:
    Java: 11.0.15
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: ^0.71.0 => 0.71.10
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Create a Touchable and verify focus callbacks on it using a hardware keyboard / mirror screen and use desktop keyboard for focus

### Snack, code example, screenshot, or link to a repository

      <TouchableOpacity
        accessible={true}
        onPress={() => console.log('Pressed')}
        onFocus={() => console.log('Focused')}
        onBlur={() => console.log('Blurred')}
      >
        <Text>Button</Text>
      </TouchableOpacity>

Snack link - https://snack.expo.dev/@ayush547/touchableopacitybug

**Comment by ayush547** [comment]
Added snack [link](https://snack.expo.dev/@ayush547/touchableopacitybug) as well, again this issue is for Android

**Comment by Pranav-yadav** [comment]
> Added snack [link](https://snack.expo.dev/@ayush547/touchableopacitybug) as well, again this issue is for Android

Thanks, Ayush for the repro. Someone will take a look into it. Also, did you check this on the latest patch?

**Comment by carlosalmonte04** [comment]
Hey Ayush how exactly are you testing this?
