### ISSUE TITLE
Unable create new react-native project

### ISSUE THREAD

**Issue by suneel-eng** [facebook/react-native#38054]
### Description

Unable to create react-native project with ```npx react-native@latest init AwesomeProject```
I tried to create other project with previous version of react-native ```npx react-native@0.71.8 init AwesomeProject```. but it is not working.

I am getting error as below.
<img width="1437" alt="Screenshot 2023-06-25 at 3 59 25 PM" src="https://github.com/facebook/react-native/assets/53301692/219fcd81-4caf-42cc-ad55-9a9c005916d9">

### React Native Version

0.72.0

### Output of `npx react-native info`

If run the command from old active project. I am getting response as below.
<img width="596" alt="Screenshot 2023-06-25 at 4 07 18 PM" src="https://github.com/facebook/react-native/assets/53301692/b8572c86-2925-4f0f-97a3-249fae3ed8db">

And if run the command in teminal where package.json is not present then I am getting response as below.
<img width="483" alt="Screenshot 2023-06-25 at 4 09 42 PM" src="https://github.com/facebook/react-native/assets/53301692/da11622a-9b20-4f6e-91dc-752d186fca3c">

### Steps to reproduce

Run the command ```npx react-native@latest init AwesomeProject``` on macOS with M1 chip.

### Snack, code example, screenshot, or link to a repository

Unable to create new react-native project.

**Comment by suneel-eng** [comment]
### React Native Version
0.72.0

**Comment by TheSavior** [comment]
Is your hard drive out of disk space?

**Comment by Pranav-yadav** [comment]
@suneel-eng As Eli pointed out this is due to the below error from `yarn`:
`"ENOSPC": No space left on device`
while installing dependencies. 😅
