### ISSUE TITLE
I'm getting PhaseScriptExecution failed with a nonzero exit code in xcode 13.2 and react native version is 0.72.0

### ISSUE THREAD

**Issue by Junucp** [facebook/react-native#38064]
### Description

I'm creating a new project in react native and project is running fine in android. But in IOS when I tried to build the project I'm getting PhaseScriptExecution failed with a nonzero exit code.
![Screen Shot 2023-06-26 at 3 30 35 PM](https://github.com/facebook/react-native/assets/137775917/a8d6ae68-4d6c-4a22-847d-3fa013bcba86)

### React Native Version

0.72.0

### Output of `npx react-native info`

System:
  OS: macOS 12.6.6
  CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
  Memory: 31.55 MB / 8.00 GB
  Shell:
    version: 5.8.1
    path: /bin/zsh
Binaries:
  Node:
    version: 18.16.0
    path: ~/.nvm/versions/node/v18.16.0/bin/node
  Yarn:
    version: 1.22.19
    path: /usr/local/bin/yarn
  npm:
    version: 9.5.1
    path: ~/.nvm/versions/node/v18.16.0/bin/npm
  Watchman:
    version: 2023.05.22.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /Users/macbook/.rvm/gems/ruby-3.0.0/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 21.2
      - iOS 15.2
      - macOS 12.1
      - tvOS 15.2
      - watchOS 8.3
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
  Xcode:
    version: 13.2/13C90
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.19
    path: /usr/local/opt/openjdk@11/bin/javac
  Ruby:
    version: 3.0.0
    path: /Users/macbook/.rvm/rubies/ruby-3.0.0/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.0
    wanted: 0.72.0
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

### Steps to reproduce

Xcode version is 13.2 and react-native version is 0.72.0.
yarn  => install all the dependancies.
cd ios && pod install
cd ..
yarn run ios

### Snack, code example, screenshot, or link to a repository

git clone -b development https://Junaifcp@bitbucket.org/formfit/form-fit-mobile.git

Clone this repository to find out the issue.

**Comment by cipolleschi** [comment]
Hi there, can you try this out with Xcode 14?

Starting from 25th April of 2023, apple would not accept apps built with Xcode 13 anymore: https://developer.apple.com/news/?id=jd9wcyov

So there is no point for us to support Xcode 13

**Comment by Pranav-yadav** [comment]
>Starting from 25th April of 2023, apple would not accept apps built with Xcode 13 anymore: https://developer.apple.com/news/?id=jd9wcyov
>
>So there is no point for us to support Xcode 13

Maybe we should highlight this in the environment setup guide or is it already?

**Comment by NiravSa** [comment]
same issue with Xcode 14.3.1
any workaround?
