### ISSUE TITLE
Missing Class "File" in react-native

### ISSUE THREAD

**Issue by trashcoder** [facebook/react-native#38061]
### Description

In react-native there is no class "File". It would make Uploads easier with appwrite because their storage.createFile method only supports File.

### React Native Version

0.71.11

### Output of `npx react-native info`

System:
OS: macOS 13.4
CPU: (8) arm64 Apple M1 Pro
Memory: 67.23 MB / 16.00 GB
Shell: 5.9 - /bin/zsh
Binaries:
Node: 19.1.0 - ~/.nvm/versions/node/v19.1.0/bin/node
Yarn: 1.22.19 - ~/.nvm/versions/node/v19.1.0/bin/yarn
npm: 9.3.1 - ~/.nvm/versions/node/v19.1.0/bin/npm
Watchman: 2023.05.22.00 - /opt/homebrew/bin/watchman
Managers:
CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
SDKs:
iOS SDK:
Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
Android SDK: Not Found
IDEs:
Android Studio: Flamingo 2022.2.1 Patch 2 Flamingo 2022.2.1 Patch 2
Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
Languages:
Java: Not Found
npmPackages:
@react-native-community/cli: Not Found
react: 18.2.0 => 18.2.0
react-native: 0.71.11 => 0.71.11
react-native-macos: Not Found
npmGlobalPackages:
react-native: Not Found

### Steps to reproduce

Create new react-native project, edit app.tsx and try to use the common "new File()" command.

### Snack, code example, screenshot, or link to a repository

no

**Comment by cortinico** [comment]
> In react-native there is no class "File". It would make Uploads easier with appwrite because their storage.createFile method only supports File.

Which langauge are you referring to? JS/Java/Kotlin/ObjC/C++?
Also what is appwrite?
Could you link a reference to `storage.createFile`?

**Comment by cortinico** [comment]
> Could you link a reference to `storage.createFile`?

**Comment by trashcoder** [comment]
https://github.com/appwrite/sdk-for-web/blob/master/src/services/storage.ts#L76

**Comment by trashcoder** [comment]
Now that i'm a little bit familiar with the react-native code i see, that there is a File class in the library:
[packages/react-native/Libraries/Blob/File.js](https://github.com/facebook/react-native/blob/main/packages/react-native/Libraries/Blob/File.js)

But this Class does not show up in my IDEs like webstorm or VSCode. Is there something wrong with its export?

**Comment by cortinico** [comment]
> But this Class does not show up in my IDEs like webstorm or VSCode. Is there something wrong with its export?

Yup that's most likely because we are not exporting Blob from the `index.js` file (not sure why this is the case). You should be able to import that `File.js` file directly though in your project

**Comment by trashcoder** [comment]
Sorry, but i can't import the class File directly. 
I tried ist this way:
```
import File from 'react-native/Libraries/Blob/File.js';
const file = new File(blob, "test.jpg");
```
 and get a undefined is not a function:

**Comment by trashcoder** [comment]
I found out, that File is missing in the file "globals.d.ts". I'll make a pull request to add the declaration.

**Comment by NickGerleman** [comment]
> You should be able to import that File.js file directly though in your project

With limited exceptions, almost all of RN’s public JS APIs should be imported directly from “react-native”. Concrete “.js” files should generally not be imported. We will be limiting the ability to do this for files not meant to be public in the future via the “package.json” exports field.

**Comment by NickGerleman** [comment]
Closing bc the PR was merged.

**Comment by trashcoder** [comment]
> With limited exceptions, almost all of RN’s public JS APIs should be imported directly from “react-native”. Concrete “.js” files should generally not be imported. We will be limiting the ability to do this for files not meant to be public in the future via the “package.json” exports field.

Yes, i thought that importing File cannot be the right way.
