### ISSUE TITLE
(iOS Only) The onChangeText Event for my TextInput used for a Chat Box is not working.

### ISSUE THREAD

**Issue by dhayaljaswantgit** [facebook/react-native#38094]
### Description

The OnChange Event for my TextInput used for a Chat Box is not working.
After reset the text state to '' (after sending a message), the first character is always lost and the onChange event is not fired.

If I add (&& [_lastStringStateWasUpdatedWith isEqual:_backedTextInputView.attributedText]) again back to the code its fixed and working.

### React Native Version

0.71.8

### Output of `npx react-native info`

System:
    OS: macOS 12.6.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 41.24 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - /usr/local/bin/node
    Yarn: 1.22.17 - ~/n/bin/yarn
    npm: 9.5.1 - /usr/local/bin/npm
    Watchman: 2023.01.30.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK:
      API Levels: 32, 33
      Build Tools: 30.0.3, 33.0.0
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.9971841
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_202 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.8 => 0.71.8

### Steps to reproduce

Install package [[that](https://github.com/FaridSafi/react-native-gifted-chat)](https://github.com/FaridSafi/react-native-gifted-chat) and in chat input iOS first charter will be unidentified, no call back in onChangeText

Solution for the same (apply patch) => 

<pre>
diff --git a/node_modules/react-native/Libraries/Text/TextInput/RCTBackedTextInputDelegateAdapter.m b/node_modules/react-native/Libraries/Text/TextInput/RCTBackedTextInputDelegateAdapter.m
index 1c8f8e0..9dca6a5 100644
--- a/node_modules/react-native/Libraries/Text/TextInput/RCTBackedTextInputDelegateAdapter.m
+++ b/node_modules/react-native/Libraries/Text/TextInput/RCTBackedTextInputDelegateAdapter.m
@@ -256,7 +256,7 @@ static void *TextFieldSelectionObservingContext = &TextFieldSelectionObservingCo
 
 - (void)textViewDidChange:(__unused UITextView *)textView
 {
-  if (_ignoreNextTextInputCall) {
+  if (_ignoreNextTextInputCall && [_lastStringStateWasUpdatedWith isEqual:_backedTextInputView.attributedText]) {
     _ignoreNextTextInputCall = NO;
     return;
   }
</pre>

### Snack, code example, screenshot, or link to a repository

<pre>
import React, { useState, useCallback, useEffect } from 'react'
import { GiftedChat } from 'react-native-gifted-chat'

export function Example() {
  const [messages, setMessages] = useState([])

  useEffect(() => {
    setMessages([
      {
        _id: 1,
        text: 'Hello developer',
        createdAt: new Date(),
        user: {
          _id: 2,
          name: 'React Native',
          avatar: 'https://placeimg.com/140/140/any',
        },
      },
    ])
  }, [])

  const onSend = useCallback((messages = []) => {
    setMessages(previousMessages =>
      GiftedChat.append(previousMessages, messages),
    )
  }, [])

  return (
    <GiftedChat
      messages={messages}
      onSend={messages => onSend(messages)}
      user={{
        _id: 1,
      }}
    />
  )
}
</pre>

**Comment by Pranav-yadav** [comment]
Adding to what the bot commented above, please provide a repro _without_ using any 3rd party libraries, frameworks, etc.

**Comment by swizes** [comment]
I can confirm that this patch works

**Comment by Pranav-yadav** [comment]
> I can confirm that this patch works

Thanks.

@dhayaljaswantgit if u can confirm we can close this issue.

**Comment by fabriziobertoglio1987** [comment]
Do you still experience this issue? 

I have four years of experience maintaining facebook/react-native and I specialize in the Text and TextInput components. I currently have 58 [facebook/react-native PRs](https://github.com/facebook/react-native/pulls?q=is%3Apr+author%3Afabriziobertoglio1987+). 

If you still experience this issue, I will prepare a patched release with the fix.

Thanks a lot
