### ISSUE TITLE
Modal doesn't work on Android

### ISSUE THREAD

**Issue by niftylettuce** [facebook/react-native#3810]
When will we get Modal support for Android?

**Comment by AaaChiuuu** [comment]
t8776300 (removing BaseViewPropertyApplicator broke it)

**Comment by trave7er** [comment]
here is a community version: https://github.com/maxs15/react-native-modalbox

**Comment by mbrgm** [comment]
@trave7er This project does not seem to have Android support yet.

**Comment by machnicki** [comment]
Modal doesn't work on 0.16.0-rc

Screen above:
![emulator-5554_snapshot_2015-12-04_16-43-19](https://cloud.githubusercontent.com/assets/3697551/11595072/8d7424bc-9aa5-11e5-8488-8d7330402b6d.png)

Code based on https://rnplay.org/apps/2Ko3iQ

**Comment by satya164** [comment]
Modal component is not implemented on Android and listed unde "Known issues" - https://facebook.github.io/react-native/docs/known-issues.html#views
