### ISSUE TITLE
V 0.72.0 init project crashed on Linux

### ISSUE THREAD

**Issue by Productivix** [facebook/react-native#38113]
### Description

bug to create a blanck new project on Linux, 
I am / was developping for 2 years on RN and V071.11 was running well just before.

### React Native Version

0.72.0

### Output of `npx react-native info`

error: unknown command 'info'
(Did you mean init?)

### Steps to reproduce

$ npx react-native init test_rn72_sounds

Downloading template
⠙ Copying template/home/william/.npm/_npx/7930a8670f922cdb/node_modules/graceful-fs/polyfills.js:265
        if (!chownErOk(er)) throw er
                            ^
Error: ENOENT: no such file or directory, chmod '/home/william/logiciels/logiciels-windows/dev_RN-Node-GIT/test_rn72_sounds/metro.config.js'
    at Object.chmodSync (node:fs:1888:3)
    at Object.chmodSync (/home/william/.npm/_npx/7930a8670f922cdb/node_modules/graceful-fs/polyfills.js:263:21)
    at ReadStream.<anonymous> (/home/william/.npm/_npx/7930a8670f922cdb/node_modules/@react-native-community/cli/build/tools/copyFiles.js:105:19)
    at ReadStream.emit (node:events:513:28)
    at emitCloseNT (node:internal/streams/destroy:132:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21) {
  errno: -2,
  syscall: 'chmod',
  code: 'ENOENT',
  path: '/home/william/logiciels/logiciels-windows/dev_RN-Node-GIT/test_rn72_sounds/metro.config.js'
}
Node.js v18.14.0

### Snack, code example, screenshot, or link to a repository

it is just the basic test of init

**Comment by cortinico** [comment]
Does `/home/william/logiciels/logiciels-windows/dev_RN-Node-GIT/test_rn72_sounds/metro.config.js` exists?

**Comment by Productivix** [comment]
hi, yes it exists but empty (0 bytes). Same for tsconfig.json

**Comment by Productivix** [comment]
Since, in between, I upgraded a project from RN71.11 into 0.72.0 and compiled it. 
And now on the same machine, when I made npx react-native init test_rn72_sounds2
I have got a normal behaviour.
So it is as usual (it is not the 1st time I report that issue on some versions), the fact that we develop and compile / build in a previous version that block the npx init of the 1st new version.

**Comment by bastien8060** [comment]
@cortinico I am affected by this bug, 

```
bastien@Unknown:~/Projects/youngapply/ui$ npm list
ui@ /home/bastien/Project/ui
├── @react-native-community/cli-platform-android@11.3.8
└── react-native@0.72.5
```

Should I open another issue?

**Comment by bastien8060** [comment]
Nevermind, I found a definite fix... I'll leave it here if anyone stumbles on it.

- Deleting every react packages installed globally (As advised by the official docs at `Getting started`). I double checked them with:
`npm list -g`.
- I installed locally at the CWD the packages: 
@react-native-community/cli-platform-android@11.3.8
@react-native-community/cli@11.3.8
react-native@0.72.5

I ran the init command again and it worked

**Comment by yogesh6260** [comment]
I stuck into this issue getting same error with different commands of react native. Rt now, I'm initiating new react native project with the latest version 0.72, but I'm not able to do so, getting the error ⠋ Downloading templateerror Cannot parse yarn version: 
Please, can anyone help me to solve the issue or help me create a brand new react native project ?

**Comment by yogesh6260** [comment]
> Nevermind, I found a definite fix... I'll leave it here if anyone stumbles on it.
> 
> * Deleting every **react** packages that were installed globally (As advised by the official docs at `Getting started`). I double checked them with:
>   `npm list -g`.
> * I installed locally at the CWD the packages:
>   @react-native-community/cli-platform-android@11.3.8
>   @react-native-community/cli@11.3.8
>   react-native@0.72.5
> 
> I ran the init command again and it worked

Please, explain me in detail how you solved it.

**Comment by bastien8060** [comment]
Actually I didn't update this issue, but I'm not sure anymore that did solve it, but it just worked after I ran this. It seems to be a race condition bug. After more testing across different machines, I can reproduce this bug on both WSL2, and dual booted Ubuntu (20.04, 21.10 and 22.04 tested, and reproduced the bug). Running this init command multiple times produces an EOENT error on a different files.

Running this command multiple time (and deleting the generated folder) will eventually successfully init the project.

**Comment by bastien8060** [comment]
@yogesh6260 so no definite fix sorry :(

**Comment by cortinico** [comment]
Please open those kind of issues against the CLI here:
https://github.com/react-native-community/cli/issues

As the code that is failing is there and not inside react-native

**Comment by yogesh6260** [comment]
Yes, after i tried for so many hours, then finally i'm able to create reactnative app using this command - 

`react-native init myProjectName`. 

Don't know how I solved this, but it works. Previously, I had installed react-native-community/cli globally using npm.

Thanks to all for your responses.

**Comment by treez** [comment]
@techUdayMungalpara Downgrade node version. `18.18.2` helped me
