### ISSUE TITLE
[v0.72.0][Android] Native build fails with "ld: error: --fix-cortex-a53-843419 is only supported on AArch64 targets"

### ISSUE THREAD

**Issue by birdofpreyru** [facebook/react-native#38111]
### Description

I am trying to upgrade an existing library project from RN v0.71.10 to v0.72.0. The library uses native build step, which after the upgrade fails to link on Android with such error:

> C/C++: ninja: Entering directory `/path/to/project/react-native-static-server/android/.cxx/Debug/j5o4kv1u/arm64-v8a'
> C/C++: ld: error: --fix-cortex-a53-843419 is only supported on AArch64 targets
> C/C++: clang: error: linker command failed with exit code 1 (use -v to see invocation)

I currently have no idea what does it mean, but my very naive blind guess, it might be somehow related to removing "separate builds per CPU architecture" from Gradle config (I mean the following change from RN upgrade helper)?
![image](https://github.com/facebook/react-native/assets/20144632/979ef348-2301-4840-915f-0aeca8dc4fdd)

Please, help, at very least with some guidance how to further troubleshoot it.

### React Native Version

0.72.0

### Output of `npx react-native info`

System:
  OS: Linux 5.19 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
  CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  Memory: 3.24 GB / 11.58 GB
  Shell:
    version: 5.1.16
    path: /bin/bash
Binaries:
  Node:
    version: 18.16.1
    path: ~/.nvm/versions/node/v18.16.1/bin/node
  Yarn: Not Found
  npm:
    version: 9.5.1
    path: ~/.nvm/versions/node/v18.16.1/bin/npm
  Watchman:
    version: 20230101.175141.0
    path: /usr/local/bin/watchman
SDKs:
  Android SDK:
    API Levels:
      - "33"
    Build Tools:
      - 30.0.3
      - 33.0.0
      - 33.0.2
    System Images:
      - android-33 | Google APIs ARM 64 v8a
      - android-33 | Google APIs Intel x86_64 Atom
      - android-33 | Google Play ARM 64 v8a
      - android-33 | Google Play Intel x86 Atom_64
    Android NDK: Not Found
IDEs:
  Android Studio: Not Found
Languages:
  Java:
    version: 11.0.19
    path: /usr/bin/javac
  Ruby:
    version: 3.0.2
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.0
    wanted: 0.72.0
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: Not found

### Steps to reproduce

See below.

### Snack, code example, screenshot, or link to a repository

https://github.com/birdofpreyru/react-native-static-server/tree/dev-0.8

:point_up: This is my library project I am trying to upgrade. If you want to give it a try:
- Clone & checkout branch **dev-0.8**
- `git submodule update --init --recursive` in the codebase root.
- `npm install` in the codebase root, and in the `example` sub-folder.
- Then `npm run android` inside `example` subfolder &mdash; it will crash during the build.

**Comment by cortinico** [comment]
Thanks for reporting this @birdofpreyru 

> * Clone & checkout branch **dev-0.8**
> * `git submodule update --init --recursive` in the codebase root.
> * `npm install` in the codebase root, and in the `example` sub-folder.
> * Then `npm run android` inside `example` subfolder — it will crash during the build.

I am not able to reproduce your issue, as I'm actually able to build and run correctly your sample app. So there might be something going on with your environment

**Comment by birdofpreyru** [comment]
@cortinico did you test it on MacOS build host? Probably, the issue is specific to Ubuntu build host I am using for Android development? I've just tried to clean-up and re-build the codebase, it still fails the same way; and then I tried to build the previous version, which still works for me without problems. The difference between those two versions is just what I did trying to upgrade RN:

https://github.com/birdofpreyru/react-native-static-server/compare/f0ee71205dd01ae2755e23a09a688f7f0cd9a992..12ef55f777be9d0e5e00e1099e93b55d4dfcf5db

**Comment by cortinico** [comment]
> did you test it on MacOS build host

Yes I did build on MacOS. I don't have a Linux machine where I can try this so I'm a bit stuck here. Are you able to build without any problems on Linux a vanilla project? Is the problem specific to this library?

**Comment by birdofpreyru** [comment]
Ogh... a vanilla project works fine, a vanilla project with added dummy CMake build step also works fine. I guess, it is something specific to the C project in my library.

**Comment by birdofpreyru** [comment]
Comparing the failing (new) build against the old (working) one, I tracked the difference down to an additional link flag `-L/usr/lib/x86_64-linux-gnu` appearing in the failing (new) build's `build.ninja` script &mdash; at least when I run ninja directly it fails with that script when the flag is present, and it works if I manually remove the flag from the script. Just have to figure out why it appears there :)
