### ISSUE TITLE
0.72.0 init project get error on Mac m1 

### ISSUE THREAD

**Issue by TranTuanNghia94** [facebook/react-native#38115]
### Description

I met an error when init project

### React Native Version

0.72.0

### Output of `npx react-native info`

error Failed to load configuration of your project.

### Steps to reproduce

npx react-native@latest init F3tProvider

### Snack, code example, screenshot, or link to a repository

it is just the basic test of init

**Comment by cortinico** [comment]
Closing as invalid as you don't even share the error message, so it's impossible for us to support you here.
