### ISSUE TITLE
[0.72.0][Android only] child view with border radius is not displayed correctly with `transform rotate` using  in parent view.

### ISSUE THREAD

**Issue by lchenfox** [facebook/react-native#38124]
### Description

Child view is not displayed correctly with the border radius set when the transform  `rotate` is set in parent view. This happens on part of Android devices only.

**iOS screenshot**
![IMG_2C4C340EE1BB-1](https://github.com/facebook/react-native/assets/22851821/228d8bf0-18d4-4724-aa36-d92e2a4adb74)

**Android screenshot**
![WechatIMG1](https://github.com/facebook/react-native/assets/22851821/2e8d397f-7a7a-4253-9f31-b20d66634008)

### React Native Version

0.72.0

### Output of `npx react-native info`

```
info Fetching system and libraries information...
System:
  OS: macOS 12.5
  CPU: (8) arm64 Apple M2
  Memory: 113.22 MB / 16.00 GB
  Shell:
    version: 5.8.1
    path: /bin/zsh
Binaries:
  Node:
    version: 19.6.0
    path: /opt/homebrew/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 9.4.0
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2023.02.06.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.11.3
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.2
      - iOS 16.2
      - macOS 13.1
      - tvOS 16.1
      - watchOS 9.1
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.2 AI-222.4459.24.2221.10121639
  Xcode:
    version: 14.2/14C18
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.17
    path: /usr/bin/javac
  Ruby:
    version: 2.7.5
    path: /Users/chenlong/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.0
    wanted: 0.72.0
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Steps to reproduce

- Creates a latest version project `0.72.0` using `npx react-native init newrnversion`
- Set the transform  `rotate` in parent view and borderRadius in child view.
- Run the project and check the UI on real devices.
- It works perfectly on iOS and some Android devices.

### Snack, code example, screenshot, or link to a repository

```
render() {

	return (
		<View style={{ flex: 1, backgroundColor: 'white' }}>
			<View style={{ height: 300 }} />
			<View style={{ backgroundColor: 'red', transform: [{ rotate: `45deg` }] }}>
				<View style={{
					width: 50,
					height: 50,
					backgroundColor: 'green',
					borderRadius: 25,
				}} />
			</View>
		</View>
	);
}
```

**Comment by Pranav-yadav** [comment]
The newer Patch is Available: [v0.72.1](https://github.com/facebook/react-native/releases/tag/v0.72.1)

**Comment by lchenfox** [comment]
@Pranav-yadav The same issue still exists in the latest version `0.72.1`(**Only Android 8.0 or lower versions**). The example code snippet: 

```
import React from "react";
import { SafeAreaView, View } from "react-native";

function App(): JSX.Element {
  return (
    <SafeAreaView style={{flex: 1, backgroundColor: "white" }}>
      <View style={{ height: 300 }} />
      <View style={{ backgroundColor: "red", width: 300, height: 60, transform: [{ rotate: `45deg` }] }}>
        <View style={{
          width: 50,
          height: 50,
          backgroundColor: "green",
          borderRadius: 25
        }} />
      </View>
    </SafeAreaView>
  );
}

export default App;
```

**Screenshot-Emulator Pixel XL (Edited) API 25(Android 7.1.1)**
<img width="1041" alt="截屏2023-07-01 23 37 08" src="https://github.com/facebook/react-native/assets/22851821/04d4c96e-6d2a-4df0-b05f-7d9ea1358ccf">

**Screenshot-Emulator Pixel XL (Edited) API 26(Android 8.0)**
<img width="1041" alt="截屏2023-07-01 23 18 25" src="https://github.com/facebook/react-native/assets/22851821/af10d34e-8ec7-4893-a444-b59e64ec332c">

**Screenshot-Emulator Pixel XL (Edited) API 27(Android 8.1)**
<img width="1047" alt="截屏2023-07-01 23 07 15" src="https://github.com/facebook/react-native/assets/22851821/a13d04fc-1513-46b5-bbb0-e94adc08505f">

**Please note that it works well on API 28(Android 9.0) or above**  

`Pixel XL (Edited) API 28(Android 9.0)`(Screentshot)
<img width="1047" alt="截屏2023-07-01 23 28 31" src="https://github.com/facebook/react-native/assets/22851821/8811ecff-cf9d-4a1a-add6-8cb229dd51d0">

`Pixel XL (Edited) API 34`(Screentshot)
<img width="1035" alt="截屏2023-07-01 23 11 50" src="https://github.com/facebook/react-native/assets/22851821/fc089c56-d6f3-4125-a0cf-1d5ff942f0ba">

So I'm sure that this must be bug. Also is that an Android system problem rather than `React native`. If it's Android system issue, please close this issue. And if you need more other info, please let me know. Thanks U.

**Comment by Pranav-yadav** [comment]
cc: @cortinico ^

Thanks @lchenfox for investigating.
