### ISSUE TITLE
Build fails when installing AWS Amplify dependencies

### ISSUE THREAD

**Issue by Themrpie** [facebook/react-native#38136]
### Description

After failing to build a project, created another project to see exactly what packages were causing the error, so I can confirm the error starts when you add one of these: 
@react-native-community/netinfo, @react-native-async-storage/async-storage, aws-amplify, npm i aws-sdk or react-native-responsive-screen.
If you install those and you execute "eas build p -ios" you get this error:

> Executing faceCompareFinal » [CP] Check Pods Manifest.lock
> › Executing faceCompareFinal » Start Packager on http://localhost:8081
> › Copying   ios/faceCompareFinal/Supporting/Expo.plist ➜ ./Expo.plist
> › Compiling faceCompareFinal » SplashScreen.storyboard
> › Preparing faceCompareFinal » Info.plist
> › Compiling faceCompareFinal » noop-file.swift
> › Compiling faceCompareFinal » main.m
> › Compiling faceCompareFinal » faceCompareFinal_vers.c
> › Compiling faceCompareFinal » AppDelegate.mm
> › Linking   faceCompareFinal » faceCompareFinal
> ⚠️  ld: duplicate method '+moduleName' in
> ┌─[category]: ExpoBridgeModule-c8cf1057414f438d7b7b465c98de9005.o ExpoModulesCore/libExpoModulesCore.a
> └─[class]: ExpoBridgeModule-44dcc1d614b6278ae7a3d38b9d3e0eac.o ExpoModulesCore/libExpoModulesCore.a
> › Generating debug faceCompareFinal » faceCompareFinal.app.dSYM
> › Executing faceCompareFinal » Bundle React Native code and images
>     the transform cache was reset.
> 
> ❌  error: File /Users/expo/Library/Developer/Xcode/DerivedData/faceCompareFinal-bqvqbicvmlfmpncjojyaopvajvmh/Build/Intermediates.noindex/ArchiveIntermediates/faceCompareFinal/BuildProductsPath/Release-iphoneos/faceCompareFinal.app/main.jsbundle does not exist. This must be a bug with React Native, please report it here: https://github.com/facebook/react-native/issues
> 
>     Run script build phase '[CP-User] Generate app.config for prebuilt Constants.manifest' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'EXConstants' from project 'Pods')
> ▸ ** ARCHIVE FAILED **
> ▸ The following build commands failed:
> ▸ 	PhaseScriptExecution Bundle\ React\ Native\ code\ and\ images /Users/expo/Library/Developer/Xcode/DerivedData/faceCompareFinal-bqvqbicvmlfmpncjojyaopvajvmh/Build/Intermediates.noindex/ArchiveIntermediates/faceCompareFinal/IntermediateBuildFilesPath/faceCompareFinal.build/Release-iphoneos/faceCompareFinal.build/Script-00DD1BFF1BD5951E006B06BC.sh (in target 'faceCompareFinal' from project 'faceCompareFinal')
> ▸ (1 failure)
> ** ARCHIVE FAILED **

I never had issues building apps with Amplify dependencies installed, maybe it's because I updated expo some time ago? 
I'm posting here since that what the log says. Hopefully somebody will know if I'm doing something wrong or it's really a react native bug. 

Just in case here it is my package.json:
```
{
  "name": "facecomparefinal",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "1.17.11",
    "@react-native-community/netinfo": "9.3.7",
    "amazon-cognito-identity-js": "^6.3.1",
    "aws-amplify": "^5.3.3",
    "aws-sdk": "^2.1408.0",
    "axios": "^1.4.0",
    "expo": "~48.0.18",
    "expo-image-manipulator": "~11.1.1",
    "expo-image-picker": "~14.1.1",
    "expo-linear-gradient": "~12.1.2",
    "expo-status-bar": "~1.4.4",
    "react": "18.2.0",
    "react-native": "0.71.8",
    "react-native-paper": "^5.9.0",
    "react-native-responsive-screen": "^1.4.2"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0"
  },
  "private": true
}
```

### React Native Version

0.71.8

### Output of `npx react-native info`

System:
    OS: macOS 13.0
    CPU: (8) arm64 Apple M1
    Memory: 87.14 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 18.7.0 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.15.0 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9477386
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.8 => 0.71.8 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
info React Native v0.72.0 is now available (your project is running on v0.71.8).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.72.0
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.71.8
info For more info, check out "https://reactnative.dev/docs/upgrading".

### Steps to reproduce

npm install aws-amplify amazon-cognito-identity-js @react-native-community/netinfo @react-native-async-storage/async-storage
npm install react-native-responsive-screen.
eas build -p ios

### Snack, code example, screenshot, or link to a repository

<img width="880" alt="Captura de pantalla 2023-06-29 a la(s) 19 58 52" src="https://github.com/facebook/react-native/assets/73369706/86644a79-b46f-4ef2-9163-45b58bb9dc6d">

**Comment by cipolleschi** [comment]
This is not an issue of React Native, but it seems more an Expo issue and/or a library configuration issue. 

We cannot solve the build issues for all the 3rd party libraries that use React Native.

Please open an issue in the Expo repo (as the build is happening through `eas build` command) and/or on the AWS amplify repo.
