### ISSUE TITLE
build failed in xcode - ios

### ISSUE THREAD

**Issue by DARPANMANEK** [facebook/react-native#38157]
### Description

react native xcode build failed with "command phase script execution failed with a nonzero exit code"  this error 

my xcode version : 14.3
react-native version : 6.4.0
node version : v19.3.0
os : macOS ventura 13.3

### React Native Version

6.4.0

### Output of `npx react-native info`

OS: macOS 13.3
    CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
    Memory: 1.35 GB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 19.3.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 9.2.0 - /usr/local/bin/npm
    Watchman: 2023.06.26.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.10121639
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.19 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.3 => 0.67.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

whenever i tried to run my native app in xcode and trying to build then i got issue that i mention in description.

### Snack, code example, screenshot, or link to a repository

whenever i tried to run my native app in xcode and trying to build then i got issue that i mention in description.

**Comment by cortinico** [comment]
> react native xcode build failed with "command phase script execution failed with a nonzero exit code" this error

Closing as you provided no information to help you debug.
Plus there is no React Native 6.4.0

**Comment by venux92** [comment]
I have the same issue. I tried:

opening the Pods > Target Support Files > Pods-APP > Pods-APP-frameworks file

And replace `source="$(readlink "${source}")"` by `source="$(readlink -f "${source}")"`

But still have the same issue
React-native: `0.68.5`
Xcode: `14.3.1`
