### ISSUE TITLE
Regression -- fails to compile with Xcode 14.3.1

### ISSUE THREAD

**Issue by jinhale** [facebook/react-native#38160]
### Description

Any project built using `npx react-native init <AnyProject>` fails to build in Xcode version 14.3.1. The errors are different based on whether or not `pod install` was first run. 

[...]/AwesomeProject_vers.c module map file '[...]/Build/Products/Debug-iphoneos/YogaKit/YogaKit.modulemap' not found

### React Native Version

0.72.1

### Output of `npx react-native info`

System:
  OS: macOS 13.4.1
  CPU: (4) x64 Intel(R) Core(TM) i3-8100B CPU @ 3.60GHz
  Memory: 25.91 MB / 8.00 GB
  Shell:
    version: 3.2.57
    path: /bin/bash
Binaries:
  Node:
    version: 20.3.1
    path: /usr/local/bin/node
  Yarn:
    version: 1.21.1
    path: ~/npm-global/bin/yarn
  npm:
    version: 9.6.7
    path: /usr/local/bin/npm
  Watchman:
    version: 2023.06.12.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /Users/stewarthealey/.rvm/gems/ruby-2.7.5/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.19
    path: /usr/bin/javac
  Ruby:
    version: 2.7.5
    path: /Users/stewarthealey/.rvm/rubies/ruby-2.7.5/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.1
    wanted: 0.72.1
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

### Steps to reproduce

npx react-native init AwesomeProject 
yarn
cd ios && pod install
open AwesomeProject/ios/AwesomeProject.xcodeproj
Product > Build

It fails to build regardless of `cd ios && pod install` or `cd ios && pod install --repo-update`. It fails with or without `Gemfile` and `Gemfile.lock`. It fails after `Clean Build Folder` and `Clear All Issues`. I have never used xworkspace files and there is no way to build after opening it. Are xcodeproj files are not supported? Am I missing something basic?

### Snack, code example, screenshot, or link to a repository

// Here is AwesomeProject_vers.c which open from clicking the error message: 

 extern const unsigned char AwesomeProjectVersionString[];
 extern const double AwesomeProjectVersionNumber;

 const unsigned char AwesomeProjectVersionString[] __attribute__ ((used)) = "@(#)PROGRAM:AwesomeProject  PROJECT:AwesomeProject-1" "\n";
 const double AwesomeProjectVersionNumber __attribute__ ((used)) = (double)1.;

**Comment by jinhale** [comment]
I get the same error, `[...]/AwesomeProject_vers.c module map file '[...]/Build/Products/Debug-iphonesimulator/YogaKit/YogaKit.modulemap' not found`, after disabling flipper in `Podfile` in `use_react_native!`.

**Comment by minhchienwikipedia** [comment]
@jinhale do you have solution to fix this issue?
