### ISSUE TITLE
0.72.1 -> 'React/RCTAppSetupUtils.h' file not found

### ISSUE THREAD

**Issue by asjustis** [facebook/react-native#38193]
### New Version

0.72.1

### Old Version

0.70.4

### Build Target(s)

iOS 16.5 for both device and simulator

### Output of `react-native info`

System:
  OS: macOS 13.4.1
  CPU: (10) arm64 Apple M2 Pro
  Memory: 1.64 GB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.3.1
    path: /opt/homebrew/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 9.6.7
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2023.07.03.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java: Not Found
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.1
    wanted: 0.72.1
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: false
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

### Issue and Reproduction Steps

Trying to run the project on a new Macbook Pro M2. Project fails both with `yarn run ios` and running 'play' straight from XCode. 

Got into it after trying to resolve another issue (in the link) using this solution: https://github.com/facebook/react-native/issues/34106#issuecomment-1524819646 

Any help is appreciated! 

<img width="1398" alt="Screenshot 2023-07-05 at 13 24 56" src="https://github.com/facebook/react-native/assets/1465112/4a8e93aa-03b7-4d2a-ad1d-6cf0f01303d4">

**Comment by tamil-rss** [comment]
saadsadsadasdas

**Comment by abdi4** [comment]
+1

**Comment by canderson402** [comment]
I was running into this same issue after upgrading, did you use the upgrade helper? I did, but missed some needed changes.  I ended up going through the list again copying each and every file to upgrade properly, here are the versions I went from and to.  [Upgrade Link](https://react-native-community.github.io/upgrade-helper/?from=0.70.6&to=0.72.1)

It appears that RCTAppSetupUtils is no longer used in this context, my AppDelegate.mm has no reference to it now.

**Comment by abdi4** [comment]
I double-checked and can confirm I copied everything correctly. Getting rid of that line leads to the other errors. That import is used by Flipper and after stripping it out everything works fine. I'm gona revisit my flipper config might've missed something there

**Comment by helottosornas** [comment]
I followed the steps in this comment, which solved the issue for me: https://github.com/facebook/react-native/issues/37102#issuecomment-1534841673. Seems like some changes in React-Core aren't being properly ported over when upgrading react-native. 

I am now unable to build due to `RCTViewComponentView.h` not being found instead, but that's another issue (I hope).

**Comment by ImReyon** [comment]
+1 having same error after upgrading to 0.72.1

**Comment by MensurRasic** [comment]
Same issue on my side, upgraded from 0.69.1 to 0.72.1 and I am facing the same error : 
`'React/RCTAppSetupUtils.h' file not found`

Using Mac M1

**Comment by tranductanz** [comment]
+1, same problem when upgrade from 0.70.7 -> 0.72.1, hope this can be fixed :(

**Comment by asjustis** [comment]
> I was running into this same issue after upgrading, did you use the upgrade helper? I did, but missed some needed changes. I ended up going through the list again copying each and every file to upgrade properly, here are the versions I went from and to. [Upgrade Link](https://react-native-community.github.io/upgrade-helper/?from=0.70.6&to=0.72.1)
> 
> It appears that RCTAppSetupUtils is no longer used in this context, my AppDelegate.mm has no reference to it now.

Definitely an idea! I used only `npx react-native upgrade` for upgrading, but in the Upgrade Helper I can see the AppDelegate.mm indeed was not updated, so maybe the upgrade process silently failed somewhere.

Currently, I just downgraded the RN version and tried to solve the initial problem in a different way, as going through every change and applying it manually seems too much work at this point. Hopefully, we'll get a fix at some point!

**Comment by nishivinodbhatt** [comment]
+1 Getting the same error after upgrading to 0.72.2

**Comment by nishivinodbhatt** [comment]
> > I was running into this same issue after upgrading, did you use the upgrade helper? I did, but missed some needed changes. I ended up going through the list again copying each and every file to upgrade properly, here are the versions I went from and to. [Upgrade Link](https://react-native-community.github.io/upgrade-helper/?from=0.70.6&to=0.72.1)
> > It appears that RCTAppSetupUtils is no longer used in this context, my AppDelegate.mm has no reference to it now.
> 
> Definitely an idea! I used only `npx react-native upgrade` for upgrading, but in the Upgrade Helper I can see the AppDelegate.mm indeed was not updated, so maybe the upgrade process silently failed somewhere.
> 
> Currently, I just downgraded the RN version and tried to solve the initial problem in a different way, as going through every change and applying it manually seems too much work at this point. Hopefully, we'll get a fix at some point!

I would like to know to which version did you downgrade? and is it working for you now.
Thanks :)

**Comment by humbertocg** [comment]
facing the same issue.

**Comment by nishivinodbhatt** [comment]
> software-mansion/react-native-reanimated#3823 (comment)

Thanks. But sadly did not work for me. Getting the same error

**Comment by gvete** [comment]
Same issue after upgrading to 0.72.2. Using Xcode 15 beta, IOS 17.0

**Comment by gvete** [comment]
@mciechanowicz you don't need to downgrade.. just follow the upgrade guide : [React Native Upgrade Guide](https://react-native-community.github.io/upgrade-helper/?from=0.71.12&to=0.72.3)

**Comment by asjustis** [comment]
> @mciechanowicz you don't need to downgrade.. just follow the upgrade guide : [React Native Upgrade Guide](https://react-native-community.github.io/upgrade-helper/?from=0.71.12&to=0.72.3)

@gvete but does that mean applying each code change manually? I personally am quite reluctant to do that as it is time-consuming, and feels like hardcoding a quick fix for a broken update.

**Comment by canderson402** [comment]
> 

It only takes like 30 minutes if that, and the changes are required for future upgrades anyways so unless you never want to upgrade you will have to do it eventually.

**Comment by canderson402** [comment]
> > @mciechanowicz you don't need to downgrade.. just follow the upgrade guide : [React Native Upgrade Guide](https://react-native-community.github.io/upgrade-helper/?from=0.71.12&to=0.72.3)
> 
> @gvete but does that mean applying each code change manually? I personally am quite reluctant to do that as it is time-consuming, and feels like hardcoding a quick fix for a broken update.

It only takes like 30 minutes if that, and the changes are required for future upgrades anyways so unless you never want to upgrade you will have to do it eventually.

**Comment by oduonye1992** [comment]
Use instead

#import <RCTAppSetupUtils.h>

**Comment by esvanegas** [comment]
> Use instead
> 
> #import <RCTAppSetupUtils.h>

This solution doesn't work, because a lot of dependencies couldn't be found on RCTAppSetupUtils.h but React/RCTAppSetupUtils.h, Did you do an additional step to get this work?

**Comment by mxnuchim** [comment]
+1, same problem when upgrade from 0.70.1 -> 0.72.3, Did anyone figure this out?

**Comment by Dassine** [comment]
Same here.  upgraded from 0.70.6 -> 0.72.3. Any solution?

**Comment by murliswamig** [comment]
Same here. upgraded from 0.70.6 -> 0.72.3. Any solution?

**Comment by JunboJ** [comment]
I firstly ran the `npx react-native upgrade`, it will automatically apply as many changes as it can. Then I applied the changes shown in upgrade helper to AppDelegate.mm and AppDelegate.h file. I can see the `#import <React/RCTAppSetupUtils.h>` line here has been removed along with many other things.
<img width="1276" alt="image" src="https://github.com/facebook/react-native/assets/48075577/484603d4-7e9b-440f-8fcd-4593f7478143">

Upgrade helper - https://react-native-community.github.io/upgrade-helper/?from=0.70.6&to=0.72.3
(Remember to change the from/to version)

**Comment by serhiy-z-israelit-pro** [comment]
> Use instead
> 
> #import <RCTAppSetupUtils.h>

In my case this solved the issue.

To add more details, the project is setup with `wix/react-native-navigation`. It requires in `AppDelegate -> didFinishLaunchingWithOptions` to `return YES;` instead of `return [super application:application didFinishLaunchingWithOptions:launchOptions];`
When I tried to switch back to `return [super application:application didFinishLaunchingWithOptions:launchOptions];` Flipper did see the app without `#import <RCTAppSetupUtils.h>`, but the app was broken.

**Comment by MaysharaF** [comment]
Same problem here! ;-; upgraded from 0.70.5 -> 0.72.3. Any solution?

**Comment by MashoodAli-Official** [comment]
I have also facing the same problem since i have updated(0.70 to 0.72) the project and transfer my project from Intel Mac to Macbook Air M1. 
<img width="764" alt="Screenshot" src="https://github.com/facebook/react-native/assets/54344218/1d42b257-1745-4fce-8c1e-ce58cdee9b33">

**Comment by humbertocg** [comment]
well, Finally I complete a succesfully upgrade.

the "merging" is not working. 

1. run npx react-native upgrade on your project.
2. open helper (verify your previos react native version ) https://react-native-community.github.io/upgrade-helper/?from=0.70.6&to=0.72.4 and change it on dropdown for your "current version"
3. on "What's your app name?" change into app name (important).
4.  click on "Show me how to upgrade!"
5. copy and paste or delete acording to the differencies on every file. Be careful and search on "seach tool" in visual studio code for "RnDiffApp" and change it for your app name. The tool some times did not change for your app name.
6. On package.json change by hand if you have already added packages for your dependencies (axios, pickers, etc.) or copy and paste the info from helper and reinstall your packages (npm install PACKAGE_NAME for 0.72.4 is not working (no for me), use yarn add PACKAGE_NAME instead)
7. delete package.lock.json file and node_modules folder.
8. run npm install
9. navigate to ios folder and run pod install
10. finally, run for android and ios to check if everything is ok.

Hope React native team, fix this one, is not clear how to update and the instructions are assuming that you know some steps.

**Comment by chachaxw** [comment]
> I firstly ran the `npx react-native upgrade`, it will automatically apply as many changes as it can. Then I applied the changes shown in upgrade helper for AppDelegate.mm and AppDelegate.h file. I can see the `#import <React/RCTAppSetupUtils.h>` line here has been removed along with many other things. <img alt="image" width="1276" src="https://user-images.githubusercontent.com/48075577/257822804-484603d4-7e9b-440f-8fcd-4593f7478143.png">
> 
> Upgrade helper - https://react-native-community.github.io/upgrade-helper/?from=0.70.6&to=0.72.3 (Remember to change the from/to version)

This way worked for me, very nice.

**Comment by alienbalcorp** [comment]
> Use instead
> 
> #import <RCTAppSetupUtils.h>

It helped me! Thanks a lot. 💪

**Comment by bszyman** [comment]
> I firstly ran the `npx react-native upgrade`, it will automatically apply as many changes as it can. Then I applied the changes shown in upgrade helper for AppDelegate.mm and AppDelegate.h file. I can see the `#import <React/RCTAppSetupUtils.h>` line here has been removed along with many other things. <img alt="image" width="1276" src="https://user-images.githubusercontent.com/48075577/257822804-484603d4-7e9b-440f-8fcd-4593f7478143.png">
> 
> Upgrade helper - https://react-native-community.github.io/upgrade-helper/?from=0.70.6&to=0.72.3 (Remember to change the from/to version)

Chiming in that this worked for me too.

Apparently when we had done earlier upgrades from 0.69.7, this was overlooked. Cleaning this cruft out fixed the issue.

**Comment by Darrick-Oliver** [comment]
What worked for me was deleting the `ios/` folder that was generated with the old RN version, and re-running `npm run ios`. This made the correct modifications to the `AppDelegate.mm` and other files mentioned above.

**Comment by dre-on** [comment]
> What worked for me was deleting the `ios/` folder that was generated with the old RN version, and re-running `npm run ios`. This made the correct modifications to the `AppDelegate.mm` and other files mentioned above.

Thank you, kind sir.

**Comment by MendyK** [comment]
If you are using expo, delete your `ios/` folder and run `npx expo run:ios`

CC @hassanharoon321

**Comment by hassanharoon321** [comment]
> If you are using expo, delete your `ios/` folder and run `npx expo run:ios`
> 
> CC @hassanharoon321 

Not using expo I just downgrade version

**Comment by MendyK** [comment]
@hassanharoon321 I'm on react native 0.72.5

**Comment by austimkelly** [comment]
Changing from `#import <React/RCTAppSetupUtils.h>` to `#import <RCTAppSetupUtils.h>` fixed for me. I'm building with expo, so I had to fix this. Versions:

* "expo": "^49.0.13",
* "react-native": "^0.72.5",
* "react": "18.2.0",

The RCTAppSetUpUtils is under a different project. I'm not sure if that changed during a react native upgrade.

<img width="647" alt="Screenshot 2023-10-06 at 2 35 55 PM" src="https://github.com/facebook/react-native/assets/1355145/de274ad7-27f4-4fb5-895e-e10439f9737f">

Here's where the <React/*> includes are:
<img width="739" alt="Screenshot 2023-10-06 at 2 36 34 PM" src="https://github.com/facebook/react-native/assets/1355145/b4055667-946c-47d1-9349-1f178e62920c">

Maybe some include paths are messed up?

**Comment by surasit-int-trueid** [comment]
I just changed to new format
#import <React/RCTAppSetupUtils.h>

change to
#import "RCTAppSetupUtils.h"

**Comment by SalmanFaris53** [comment]
iam also facing the same issue:-

<img width="1440" alt="Screenshot 2024-01-25 at 9 38 37 AM" src="https://github.com/facebook/react-native/assets/138652295/75a8d997-7476-4ed2-b1e7-7c1c1fb91bf4">

any one got the solution?

**Comment by FladioArmandika** [comment]
after i changed `#import <React/RCTAppSetupUtils.h>`
into `#import "RCTAppSetupUtils.h"`


I got another error

```
/Build/Products/Debug-iphonesimulator/RCT-Folly/folly.framework/Headers/folly/Optional.h:614:10 
'folly/experimental/coro/Coroutine.h' file not found
```

**Comment by JoDerGraf** [comment]
> after i changed `#import <React/RCTAppSetupUtils.h>` into `#import "RCTAppSetupUtils.h"`
> 
> I got another error
> 
> ```
> /Build/Products/Debug-iphonesimulator/RCT-Folly/folly.framework/Headers/folly/Optional.h:614:10 
> 'folly/experimental/coro/Coroutine.h' file not found
> ```

Have you found a solution for it? I have the same problem.

**Comment by rocketraman** [comment]
> Changing from `#import <React/RCTAppSetupUtils.h>` to `#import <RCTAppSetupUtils.h>` fixed for me.

This solves not finding `RCTAppSetupUtils`, but then for me leads to:

```
In file included from /.../MyRNProject/AppDelegate.mm:8:
/.../Pods/Headers/Public/React-RCTAppDelegate/RCTAppSetupUtils.h:23:9: fatal error: 'React/JSCExecutorFactory.h' file not found
#import <React/JSCExecutorFactory.h>
^~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by rocketraman** [comment]
I can see that `React/JSCExecutorFactory.h` is not supposed to be included unless hermes is disabled:

https://github.com/facebook/react-native/blob/972b42016ef02dc3cecf9743bad82c9fd2068805/packages/react-native/Libraries/AppDelegate/RCTAppSetupUtils.h#L16C1-L24C21

and that the CxxBridge pod that contains `JSCExecutorFactory.h` is not included in my `Podfile.lock`, also presumably because Hermes is now enabled by default.

I can also confirm that by manually deleting the `#if USE_HERMES` check, and the #else block that loads `JSCExecutorFactory.h`, the build works. So it seems that the `#if USE_HERMES` macro is somehow failing to return true for this header.

**Comment by rocketraman** [comment]
Looking at the output of `clang`, the parameter passed to copmile `RCTAppSetupUtils.mm` is `-DUSE_HERMES`, not `-DUSE_HERMES\=1` as all the other files.

I'm guessing this is due to this line:

https://github.com/facebook/react-native/blob/098454d4250127a8b6dea8d8b36b2754953ed118/packages/react-native/Libraries/AppDelegate/React-RCTAppDelegate.podspec#L28

**Comment by hoonjoo-park** [comment]
As @rocketraman suggested, it seems like `USE_HERMES` isn't working properly.
As a workaround, I've done the following below:

1. Go to the Xcode project's Build Settings.
2. Navigate to Preprocessor Macros.
3. Add `USE_HERMES=1` for both Debug and Release configurations.

**Comment by SunZhiC** [comment]
> iam also facing the same issue:-
> 
> <img alt="Screenshot 2024-01-25 at 9 38 37 AM" width="1440" src="https://private-user-images.githubusercontent.com/138652295/299548185-75a8d997-7476-4ed2-b1e7-7c1c1fb91bf4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1NTUzMzYsIm5iZiI6MTcxNzU1NTAzNiwicGF0aCI6Ii8xMzg2NTIyOTUvMjk5NTQ4MTg1LTc1YThkOTk3LTc0NzYtNGVkMi1iMWU3LTdjMWMxZmI5MWJmNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNVQwMjM3MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02M2NiNTdkMGFiYWEyYWJmYWI5ZWNmNTAwZTIwZjBmNWE4ODc0ZGIzMmQzOTRhOGEzZDUyNjRjNGZlMGIwZjgxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.X_yU8gQk740oNforZQfNaSW4CtMVs_5oZr5FkgGonUs">
> any one got the solution?

They have changed the default content in AppDelegate.m and AppDeleagate.h file, try to create a new project with react-native 0.72.4, then compare these two new files with old files.

**Comment by Ahsanali012** [comment]
any fix for this as same error in 0.72.3 project having xcode 15.4

**Comment by Ahsanali012** [comment]
Is this error related to Flipper? I am already installing pod using NO_FLIPPER = 1 pod install

**Comment by Ahsanali012** [comment]
> npx expo run:ios

Any solution ?

**Comment by abhayagrawal-fareye** [comment]
> I can see that `React/JSCExecutorFactory.h` is not supposed to be included unless hermes is disabled:
> 
> https://github.com/facebook/react-native/blob/972b42016ef02dc3cecf9743bad82c9fd2068805/packages/react-native/Libraries/AppDelegate/RCTAppSetupUtils.h#L16C1-L24C21
> 
> and that the CxxBridge pod that contains `JSCExecutorFactory.h` is not included in my `Podfile.lock`, also presumably because Hermes is now enabled by default.
> 
> I can also confirm that by manually deleting the `#if USE_HERMES` check, and the `#else` block that loads `JSCExecutorFactory.h`, the build works. So it seems that the `#if USE_HERMES` macro is somehow failing to return true for this header file.

Is there any fix for it ? I am having the same problem while upgrading to 0.74.5
