### ISSUE TITLE
React Native 0.72.1 issue

### ISSUE THREAD

**Issue by sonjaie** [facebook/react-native#38191]
### New Version

0.72.1

### Old Version

0.64.0

### Build Target(s)

react-native-reanimated

### Output of `react-native info`

System:
    OS: macOS 12.1
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 436.95 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
    Watchman: 2022.07.04.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 23, 27, 28, 29, 30, 31, 32, 33
      Build Tools: 28.0.3, 29.0.2, 30.0.0, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 33.0.0
      System Images: android-30 | ARM 64 v8a, android-30 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-31 | Intel x86 Atom_64, android-31 | Google APIs Intel x86_64 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9619390
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.72.1 => 0.71.12 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Issue and Reproduction Steps

When I try to "yarn android"
> Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.facebook.react:react-android:.
     Required by:
         project :app
         project :app > project :react-native-reanimated

**Comment by onatvaris** [comment]
there seems to be a lack of "reanimated" installation steps here. What is the package version?

**Comment by sonjaie** [comment]
thank you @onatvaris already fix the problem but the issue i encounter is when i try to use "yarn start" ( in order to run the metro ) the error show like this

error: Error: Unable to resolve module ./app.json

----

but when i try just yarn android its fine but the app is last update and when i try to update it, its not working

my react-native version is 0.72.1

**Comment by guisszo** [comment]
to make my build i added this:  pod 'FlipperKit', '~> 0.167.0' into my Pod file.

And it works when you disable Flipper like this:

flipper_config = FlipperConfiguration.disabled

Hope it will help 🙏🏾
