### ISSUE TITLE
React-Codegen error

### ISSUE THREAD

**Issue by kshiteejjain** [facebook/react-native#38190]
### Description

Facing build error, using below versions

Xcode: 14.3.1
react-native: "0.70.6",
ruby 2.7.5p203
Node: 20.3.1 

<img width="907" alt="Screenshot 2023-07-05 at 2 39 20 PM" src="https://github.com/facebook/react-native/assets/10721667/3783a797-e751-4f60-9b8e-f59ee4ae4ed2">

### React Native Version

0.70.6

### Output of `npx react-native info`

System:
    OS: macOS 13.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 337.14 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 20.3.1 - /var/folders/qx/y0zl51b177369vfxd1k7zm800000gp/T/yarn--1688548302361-0.16423721237798738/node
    Yarn: 1.22.19 - /var/folders/qx/y0zl51b177369vfxd1k7zm800000gp/T/yarn--1688548302361-0.16423721237798738/yarn
    npm: 9.6.7 - /usr/local/bin/npm
    Watchman: 2023.06.12.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /Users/kshiteejjain/.rvm/gems/ruby-2.7.5/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.10121639
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.19 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.6 => 0.70.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
✨  Done in 3.42s.

### Steps to reproduce

yarn ios

### Snack, code example, screenshot, or link to a repository

<img width="907" alt="Screenshot 2023-07-05 at 2 39 20 PM" src="https://github.com/facebook/react-native/assets/10721667/c10f9b77-b13d-4a48-8e9b-1596c8729bc8">

**Comment by cortinico** [comment]
@kshiteejjain are you using the New Architecture?

**Comment by kshiteejjain** [comment]
I am using below versions:

Xcode: 14.3.1
react-native: "0.70.6",
ruby 2.7.5p203
Node: 20.3.1

**Comment by cortinico** [comment]
Please upgrade to the latest version of RN and try again. As this is  New Architecture related, we accept bugs for it only agains the latest stable
