### ISSUE TITLE
Dev Menu button is not updating label properly

### ISSUE THREAD

**Issue by szymonrybczak** [facebook/react-native#38192]
### Description

When pressing "Enable Sampling Profiler" on Android, it should change the label to "Disable Sampling Profiler", but it doesn't.

### React Native Version

0.72.1

### Output of `npx react-native info`

System:
  OS: macOS 13.3.1
  CPU: (8) arm64 Apple M1 Pro
  Memory: 106.09 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 16.18.1
    path: ~/.nvm/versions/node/v16.18.1/bin/node
  Yarn:
    version: 1.22.19
    path: ~/.nvm/versions/node/v16.18.1/bin/yarn
  npm:
    version: 9.7.2
    path: ~/.nvm/versions/node/v16.18.1/bin/npm
  Watchman:
    version: 2023.06.08.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /Users/szymonrybczak/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK:
    API Levels:
      - "28"
      - "30"
      - "31"
      - "33"
      - "33"
    Build Tools:
      - 30.0.3
      - 33.0.0
      - 34.0.0
    System Images:
      - android-33 | Google APIs ARM 64 v8a
      - android-TiramisuPrivacySandbox | Google Play ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2022.1 AI-221.6008.13.2211.9619390
  Xcode:
    version: 14.3/14E222b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 19.0.2
    path: /usr/bin/javac
  Ruby:
    version: 2.7.6
    path: /Users/szymonrybczak/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: false
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

### Steps to reproduce

1. Init app with `npx react-native@latest init App`.
2. Run app with `npx react-native run-android`.
3. Open Dev Menu by clicking `d` inside terminal.
4. Press "Enable Sampling Profiler".
5. Open again Dev Menu.

"Disable Sampling Profiler" button should be visible instead of "Enable Sampling Profiler". 

### Snack, code example, screenshot, or link to a repository

https://github.com/facebook/react-native/assets/63900941/7ae77cf4-d539-4fe5-96d6-dceb0c71e581

**Comment by cortinico** [comment]
This is a known issue, thanks for reporting it @szymonrybczak

**Comment by cortinico** [comment]
This was fixed recently on main 0cbd2a345d613b1b6e6a5b1c2965018adfb45f6f
