### ISSUE TITLE
0.72 Regression in Direct Debugging on Android

### ISSUE THREAD

**Issue by lunaleaps** [facebook/react-native#38204]
### Description

When bootstrapping a new 0.72.x app, I am unable to debug the app following the direct debugging instructions.

### React Native Version

0.72

### Output of `npx react-native info`

N/A

### Steps to reproduce

* `npx react-native init MyApp`
* Add `debugger;` statement to `App.tsx`
* Have metro running via `yarn start` in my project
* Follow instructions for direct debugging via `chrome://inspect`, open devtools
* Reload the app, the debugger does not stop at the breakpoint

### Snack, code example, screenshot, or link to a repository

See instructions above

https://github.com/facebook/react-native/assets/1309636/d5befe38-6ba9-46cf-90e7-8d5290a14133

**Comment by lunaleaps** [comment]
Fix is here: https://github.com/facebook/react-native/commit/41477c898cf5726eae9edbb1596366a6eea2b01e
TBD, verify fix

**Comment by faheem-cmd** [comment]
i have still this issue on RN 0.72

**Comment by emanuelasistensi** [comment]
same problem here

**Comment by lunaleaps** [comment]
What version are you guys in? The fix was picked into 0.72.2, we just released 0.72.3. Have you tried those versions?

**Comment by emanuelasistensi** [comment]
0.72.1, 0.72.2 and 0.72.3

**Comment by emanuelasistensi** [comment]
![Captura de pantalla 2023-07-12 a la(s) 11 59 57 a  m](https://github.com/facebook/react-native/assets/102984009/6dfece05-9a92-4c84-b72d-a655c514ccae)
![Captura de pantalla 2023-07-12 a la(s) 12 00 13 p  m](https://github.com/facebook/react-native/assets/102984009/817c3be0-3829-4d65-bb46-9c6db4725174)

**Comment by 20chad16** [comment]
Any fix?

**Comment by Lakston** [comment]
same problem here since updating to 0.73.8, what are we supposed to debug with ?
I cant even access my app since updating because of this error
