### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code - Error when buils on Xcode 14.3

### ISSUE THREAD

**Issue by saravana-mitrah** [facebook/react-native#38211]
### Description

I'm facing this issue while running the IOS app on M1 Mac only. It works fine in an intel chip Mac.

<img width="1489" alt="image" src="https://github.com/facebook/react-native/assets/136422487/3131c809-1083-4bf7-9844-72451e0ecc05">

### React Native Version

0.72.1

### Output of `npx react-native info`

 OS: macOS 13.2.1
  CPU: (8) arm64 Apple M1 Pro
  Memory: 80.50 MB / 16.00 GB
  Shell:
    version: 5.8.1
    path: /bin/zsh
Binaries:
  Node:
    version: 16.14.0
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.17
    path: /usr/local/bin/yarn
  npm:
    version: 8.3.1
    path: /usr/local/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.12.1
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK:
    API Levels:
      - "29"
      - "30"
      - "31"
      - "32"
      - "33"
    Build Tools:
      - 28.0.3
      - 30.0.2
      - 30.0.3
      - 31.0.0
      - 32.0.0
      - 32.1.0
      - 33.0.0
    System Images:
      - android-29 | Google APIs ARM 64 v8a
      - android-30 | Google Play ARM 64 v8a
      - android-31 | Google TV ARM 64 v8a
      - android-32 | Google APIs ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2021.1 AI-211.7628.21.2111.8193401
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 1.8.0_202
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

### Steps to reproduce

There is no special steps to reproduce this.  I'm  getting this issue within 5 sec when start the build.

<img width="1489" alt="image" src="https://github.com/facebook/react-native/assets/136422487/c86742f2-72c3-47c3-bb41-18bfb3768197">

### Snack, code example, screenshot, or link to a repository

There are no code changes in local, I have created the new project after running that getting this issue in m1 Mac.

**Comment by ameer-taghavi** [comment]
same issue with Xcode 14.3.1 and M1

**Comment by migsandia-1984** [comment]
Same issue with Xcode 14.2 and Intel

**Comment by ssimoe50** [comment]
Same issue is found on Xcode 14.3.1 and Xcode 15 Beta 3.
All on M1 devices, and react-native 0.71.11.

I didn't change anything but the last builds I had done on this project more or less a month didn't had any issues, so it's something fairly recent.

**Comment by ameer-taghavi** [comment]
I restarted my MacBook and solved my problem

**Comment by Saravana2108** [comment]
It is fixed after updating the react native version to 0.72.3

**Comment by saravana-mitrah** [comment]
Again I'm getting the issue.

**Comment by xjoshuaxchow** [comment]
other linker flags  -ld64

**Comment by laurensius** [comment]
Same issue. Xcode 14.3. M1

**Comment by kwanso-safyan** [comment]
I am getting the same error on Xcode 14.2 and react native - 0.72.4.
Any solution to resolve it?

**Comment by nboxill** [comment]
Same issue Xcode 14.3.1 - M1 - Ventura 13.5

**Comment by FawadMahmood** [comment]
I am also facing this issue on Github Actions; this error has nothing to do with the Xcode or MacOS versions. I have tried many combinations there already. 

Below a log from Xcode when expanding info on this error: 

```
Showing Recent Messages
Node found at: /usr/local/bin/node

internal/modules/cjs/loader.js:1131

      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);

      ^



Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/fawadmahmood/Documents/latest-mobile-fax/node_modules/wrap-ansi/index.js

require() of ES modules is not supported.

require() of /Users/fawadmahmood/Documents/latest-mobile-fax/node_modules/wrap-ansi/index.js from /Users/fawadmahmood/Documents/latest-mobile-fax/node_modules/cliui/build/index.cjs is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.

Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/fawadmahmood/Documents/latest-mobile-fax/node_modules/wrap-ansi/package.json.



    at new NodeError (internal/errors.js:322:7)

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1131:13)

    at Module.load (internal/modules/cjs/loader.js:979:32)

    at Function.Module._load (internal/modules/cjs/loader.js:819:12)

    at Module.require (internal/modules/cjs/loader.js:1003:19)

    at require (internal/modules/cjs/helpers.js:107:18)

    at Object.<anonymous> (/Users/fawadmahmood/Documents/latest-mobile-fax/node_modules/cliui/build/index.cjs:293:14)

    at Module._compile (internal/modules/cjs/loader.js:1114:14)

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)

    at Module.load (internal/modules/cjs/loader.js:979:32) {

  code: 'ERR_REQUIRE_ESM'

}

**Comment by FawadMahmood** [comment]
use: npm i --legacy-peer-deps fix the problem for me.
