### ISSUE TITLE
Fatal Exception: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes.so in release from firebase crashlytics

### ISSUE THREAD

**Issue by stewartcintra** [facebook/react-native#38216]
### Description

Fatal Exception: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes.so
	SoSource 0: com.facebook.soloader.ApkSoSource[root = /data/data/com.app_land_pp/lib-main flags = 1]
	SoSource 1: com.facebook.soloader.ApkSoSource[root = /data/data/com.app_land_pp/lib-0 flags = 1]
	SoSource 2: com.facebook.soloader.ApkSoSource[root = /data/data/com.app_land_pp/lib-1 flags = 1]
	SoSource 3: com.facebook.soloader.ApkSoSource[root = /data/data/com.app_land_pp/lib-2 flags = 1]
	SoSource 4: com.facebook.soloader.ApkSoSource[root = /data/data/com.app_land_pp/lib-3 flags = 1]
	SoSource 5: com.facebook.soloader.ApkSoSource[root = /data/data/com.app_land_pp/lib-4 flags = 1]
	SoSource 6: com.facebook.soloader.ApkSoSource[root = /data/data/com.app_land_pp/lib-5 flags = 1]
	SoSource 7: com.facebook.soloader.ApkSoSource[root = /data/data/com.app_land_pp/lib-6 flags = 1]
	SoSource 8: com.facebook.soloader.ApkSoSource[root = /data/data/com.app_land_pp/lib-7 flags = 1]
	SoSource 9: com.facebook.soloader.ApkSoSource[root = /data/data/com.app_land_pp/lib-8 flags = 1]
	SoSource 10: com.facebook.soloader.ApkSoSource[root = /data/data/com.app_land_pp/lib-9 flags = 1]
	SoSource 11: com.facebook.soloader.ApkSoSource[root = /data/data/com.app_land_pp/lib-10 flags = 1]
	SoSource 12: com.facebook.soloader.ApkSoSource[root = /data/data/com.app_land_pp/lib-11 flags = 1]
	SoSource 13: com.facebook.soloader.ApkSoSource[root = /data/data/com.app_land_pp/lib-12 flags = 1]
	SoSource 14: com.facebook.soloader.ApkSoSource[root = /data/data/com.app_land_pp/lib-13 flags = 1]
	SoSource 15: com.facebook.soloader.ApkSoSource[root = /data/data/com.app_land_pp/lib-14 flags = 1]
	SoSource 16: com.facebook.soloader.ApkSoSource[root = /data/data/com.app_land_pp/lib-15 flags = 1]
	SoSource 17: com.facebook.soloader.ApkSoSource[root = /data/data/com.app_land_pp/lib-16 flags = 1]
	SoSource 18: com.facebook.soloader.ApkSoSource[root = /data/data/com.app_land_pp/lib-17 flags = 1]
	SoSource 19: com.facebook.soloader.ApkSoSource[root = /data/data/com.app_land_pp/lib-18 flags = 1]
	SoSource 20: com.facebook<truncated: 7223 chars>
       at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:896)
       at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:725)
       at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:649)
       at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:629)
       at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:577)
       at com.facebook.hermes.reactexecutor.HermesExecutor.<clinit>(HermesExecutor.java:20)
       at com.facebook.hermes.reactexecutor.HermesExecutorFactory.create(HermesExecutorFactory.java:29)
       at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1017)
       at java.lang.Thread.run(Thread.java:923)
       
       "react-native": "0.63.2"

### React Native Version

0.63.2

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 13.0
    CPU: (8) arm64 Apple M1
    Memory: 54.73 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.1 - /opt/homebrew/Cellar/node@16/16.13.1/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.1.2 - /opt/homebrew/Cellar/node@16/16.13.1/bin/npm
    Watchman: 2021.12.06.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16.1 - /usr/bin/javac
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

error caught by firebase crashlytics from app in production

### Snack, code example, screenshot, or link to a repository

h

**Comment by cortinico** [comment]
> 0.63.2

Closing as this version of React Native is too old and we're not currently supporting it
