### ISSUE TITLE
One of Text's characters is just half rendered on Android

### ISSUE THREAD

**Issue by jcdhlzq** [facebook/react-native#38219]
### Description

Test case : https://snack.expo.dev/vyBu3Fm-d
The text "已售5.15万哈哈哈哈哈哈哈" is expected to be rendered on the screen with some of the text characters, but we got one of the characters is half rendered as the following image shows on Android. On iOS devices, it can work around with `ellipsizeMode = {'wordWrapping'} `.

### React Native Version

0.72.1

### Output of `npx react-native info`

System:
    OS: macOS 13.3.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 29.83 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.13.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.6.7 - /usr/local/bin/npm
    Watchman: 2023.03.13.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33
      Build Tools: 23.0.1, 25.0.3, 26.0.1, 26.0.3, 28.0.3, 29.0.0, 29.0.2, 29.0.3, 30.0.0, 30.0.2, 30.0.3, 31.0.0, 33.0.0
      System Images: android-18 | Intel x86 Atom, android-18 | Google APIs ARM EABI v7a, android-22 | Google APIs ARM EABI v7a, android-30 | Google Play Intel x86 Atom
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9619390
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_291 - /usr/bin/javac
    Python: 2.7.5 - /Users/lzq/Library/Android/sdk/ndk-bundle/prebuilt/darwin-x86_64/bin/python
  npmPackages:
    @react-native-community/cli: 4.14.0 => 4.14.0
    react: 16.11.0 => 16.11.0
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Run the code example below

### Snack, code example, screenshot, or link to a repository

https://snack.expo.dev/vyBu3Fm-d

<img width="461" alt="image" src="https://github.com/facebook/react-native/assets/23273745/9c8605c8-9366-4c02-b760-0c9bf74dc2ad">

**Comment by jcdhlzq** [comment]
> still exist in the most recent releases.

Yes, it still exists in the most recent releases.

**Comment by jcdhlzq** [comment]
> ⚠️	Newer Version of React Native is Available!
> ℹ️	You are on a supported minor version, but it looks like there's a newer patch available - 0.72.1. Please [upgrade](https://reactnative.dev/docs/upgrading) to the highest patch for your minor or latest and verify if the issue persists (alternatively, create a new project and repro the issue in it). If it does not repro, please let us know so we can close out this issue. This helps us ensure we are looking at issues that still exist in the most recent releases.

Yes, it still exists in the most recent releases.

**Comment by jcdhlzq** [comment]
I've tested the issue with the pr #37667. The issue doesn't occurred on Android. The effect now is equal to that on iOS with `ellipsizeMode = {'wordWrapping'}`.  I doubt that we get a new problem about consistency of 'clip'. I'm not certain for no iOS devices on hand now.

**Comment by jcdhlzq** [comment]
<img width="1036" alt="image" src="https://github.com/facebook/react-native/assets/23273745/64569c48-48e1-4d58-b53e-daea7df7678a">

**Comment by jcdhlzq** [comment]
![image](https://github.com/facebook/react-native/assets/23273745/7661b1e6-3305-4dcc-83c0-77387bbf3957)

**Comment by fabriziobertoglio1987** [comment]
I believe that the PR was reverted
