### ISSUE TITLE
<React/RCTBridgeModule.h> file not found

### ISSUE THREAD

**Issue by SnehaFirodiya** [facebook/react-native#38215]
### Description

I have created iOS native module for swift using command `npx create-react-native-library@latest react-native-awesome-module`

and build the iOS project under `react-native-awesome-module/iOS`

but its giving error like `<React/RCTBridgeModule.h> file not found`

On the opposite side , iOS native module created with Objective C is working fine.

### React Native Version

0.71.0

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 13.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 2.40 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 19.9.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.6.3 - /opt/homebrew/bin/npm
    Watchman: 2023.04.10.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /Users/snehafirodiya/.rvm/gems/ruby-2.7.6/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: ^0.71.6 => 0.71.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
info React Native v0.72.1 is now available (your project is running on v0.71.6).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.72.1
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.71.6
info For more info, check out "https://reactnative.dev/docs/upgrading".

### Steps to reproduce

1. npx create-react-native-library@latest react-native-awesome-module
2. run iOS project which is under `react-native-awesome-module/ios`

### Snack, code example, screenshot, or link to a repository

NA

**Comment by cortinico** [comment]
> I have created iOS native module for swift using command `npx create-react-native-library@latest react-native-awesome-module`

Can you please report this issue against:
https://github.com/callstack/react-native-builder-bob/issues/
