### ISSUE TITLE
I can't change a component's property values in react-native IOS

### ISSUE THREAD

**Issue by siomar** [facebook/react-native#38218]
### Description

I can't change a component's property values in react-native IOS, android I managed to change a value or overwrite it, in IOS I can't.

` React.Children.forEach(children, (child: any) => {
    if (child.props) {
      Object.entries(child.props).map(([key, value]) => {
        if (value === 'sd:context:action') {
          child.props[key] = context.setShow;
        }
      });
    }
  });`

### React Native Version

0.64.4

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 438.20 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.0.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.6.4 - /opt/homebrew/bin/npm
    Watchman: 2023.04.17.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8139111
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.14 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.4 => 0.64.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
npm notice 
npm notice New minor version of npm available! 9.6.4 -> 9.8.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.8.0
npm notice Run npm install -g npm@9.8.0 to update!
npm notice

### Steps to reproduce

const ContextShare: React.FC = ({children}): JSX.Element => {
  const context = React.useContext(ContextAPI);

  React.Children.forEach(children, (child: any) => {
    if (child.props) {
      Object.entries(child.props).map(([key, value]) => {
        if (value === 'sd:context:action') {
          child.props[key] = context.setShow;
        }
      });
    }
  });

  return <>{children}</>;
};

### Snack, code example, screenshot, or link to a repository

 ERROR  [TypeError: onPress is not a function. (In 'onPress(event)', 'onPress' is "sd:context:action")]

**Comment by cortinico** [comment]
> 0.64.4

Sadly this version of React Native is unsupported. We'll have to close this issue as we can't really actionate anything here.
