### ISSUE TITLE
Ability to detect iOS vs Android and load differing components?

### ISSUE THREAD

**Issue by niftylettuce** [facebook/react-native#3822]
In case I want to just have `index.js` instead of `index.ios.js` and `index.android.js`.

Most of my components are all shared, with exception of `react-native-facebook-login` (since there is now Android support at <https://github.com/lwhiteley/react-native-facebook-login/blob/master/Android.md> and the `require` call is different).

**Comment by niftylettuce** [comment]
For example, something like:

```js
if (android)
  return (
    <SomeAndroidComponent />
  )
else
  return (
    <SomeIOSComponent />
  )
```

**Comment by ide** [comment]
You can do `require('react-native').Platform.OS === 'android' / 'ios'` to do a runtime check. The packager will still bundle all requires that it statically discovers.

**Comment by BigPun86** [comment]
Just use Platform.OS where you need a specification:

var {Platform} = React;

if (Platform.OS === 'ios')
  return (
    <SomeAndroidComponent />
  )
else
  return (
    <SomeIOSComponent />
  )

**Comment by niftylettuce** [comment]
Very cool.  Can this get documented on the site?  I'm finding myself being
able to write components that work both platforms so I only need one index
file.

**Comment by ide** [comment]
Task to add docs here: https://github.com/facebook/react-native/issues/3701

**Comment by niftylettuce** [comment]
Great @ide !

**Comment by jsierles** [comment]
@facebook-github-bot answered

**Comment by Brhernann** [comment]
`                       { (Platform.OS === 'ios') ? [CODE] : [CODE] }`

**Comment by imtmh** [comment]
import {Platform, StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  height: Platform.OS === 'ios' ? 200 : 100,
});
