### ISSUE TITLE
Lazy view-pager and scrollview

### ISSUE THREAD

**Issue by ssssssssssss** [facebook/react-native#3823]
Android ViewPager and iOS ScrollView {{pageEnable:true}} needs to load all the data in advance which is slow for a large data set, so we'd like to implement a lazy view pager that only loads several siblings of current page. It works in iOS, but Android version suffers the rendering issue which makes the lazily added view not shown.

Here is the repo to reproduce, we take 5 pages as sliding window.
https://github.com/ssssssssssss/react-native-lazy-view-pager

Any idea? Thanks.

**Comment by jackyanjiaqi** [comment]
the same question,switching between two long lists costs long time.

**Comment by brentvatne** [comment]
@ssssssssssss - can you create an issue for this on [ProductPains](https://productpains.com/product/react-native/)? I would definitely upvote it!

**Comment by ssssssssssss** [comment]
https://productpains.com/post/react-native/lazy-view-pager-and-scrollview/1

**Comment by dsibiski** [comment]
Upvoted, very much needed for the viewPager.

**Comment by braco** [comment]
@ssssssssssss: did you make any progress on this by chance?

**Comment by braco** [comment]
There's this, which I haven't tried yet: https://github.com/magicismight/react-native-lazyload

**Comment by ssssssssssss** [comment]
@braco IMHO the repo you mentioned did do a more generic lazy loading, but may lack of view recycling which is very important for an infinite view pager.
