### ISSUE TITLE
upgrade "com.facebook.soloader:soloader:0.10.4" to 0.10.5

### ISSUE THREAD

**Issue by billnbell** [facebook/react-native#38259]
### Description

Been out since 2022

### React Native Version

0.72.1

### Output of `npx react-native info`

no

### Steps to reproduce

no

### Snack, code example, screenshot, or link to a repository

no

**Comment by billnbell** [comment]
OK question. I have this in my build.gradle. No idea why. Is it needed there?

**Comment by cortinico** [comment]
> OK question. I have this in my build.gradle. No idea why. Is it needed there?

Nope is not needed, you should not have it in your build.gradle file
