### ISSUE TITLE
ios not running

### ISSUE THREAD

**Issue by sanoofrahiman960** [facebook/react-native#38269]
i got issue like this 

"/ios/build/generated/ios/react/renderer/components/rncore/ShadowNodes.cpp normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'React-Codegen' from project 'Pods')
(1 failure)"   please help i stuck with this error

**my pod file below attached-----**
<img width="1093" alt="Screenshot 2023-07-10 at 3 19 55 PM" src="https://github.com/facebook/react-native/assets/81160871/f225716e-e509-4898-ac53-d19dec5eca85">

**my system info** 

  OS: macOS 12.5
    CPU: (8) arm64 Apple M1
    Memory: 107.34 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.4.1 - ~/.nvm/versions/node/v16.17.1/bin/npm
    Watchman: 2023.02.27.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /Users/sanoofrahimanj/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9619390
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 19.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^18.1.0 => 18.2.0 
    react-native: ^0.70.6 => 0.70.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

_Originally posted by @sanoofrahiman960 in https://github.com/facebook/react-native/issues/35986#issuecomment-1628619829_

**Comment by cortinico** [comment]
@sanoofrahiman960 could you fill the issue templatE?

**Comment by sanoofrahiman960** [comment]
when just run code using "npx react-native run-ios" when that time getting an error


** BUILD FAILED **


The following build commands failed:
        CompileC /Users/sanoofrahimanj/Library/Developer/Xcode/DerivedData/milmaDataEntry-awvvzufrdwnctpalvkdkgvyaxbpw/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNCAsyncStorage.build/Objects-normal/arm64/RNCAsyncStorage.o /Users/sanoofrahimanj/Desktop/Workspace/DonamsTechLabs/milma-pms-app/node_modules/@react-native-async-storage/async-storage/ios/RNCAsyncStorage.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'RNCAsyncStorage' from project 'Pods')
        CompileC /Users/sanoofrahimanj/Library/Developer/Xcode/DerivedData/milmaDataEntry-awvvzufrdwnctpalvkdkgvyaxbpw/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNBootSplash.build/Objects-normal/arm64/RNBootSplash.o /Users/sanoofrahimanj/Desktop/Workspace/DonamsTechLabs/milma-pms-app/node_modules/react-native-bootsplash/ios/RNBootSplash.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'RNBootSplash' from project 'Pods')
(2 failures)

**Comment by ravindraguptacapgemini** [comment]
@cortinico facing the same error.

**Comment by sanoofrahiman960** [comment]
> @cortinico facing the same error.

i resolve this issue please send your podfile or attach podfile

**Comment by cortinico** [comment]
@sanoofrahiman960, can you please fill the issue template and share a reproducer? Thanks
