### ISSUE TITLE
openURL() not respecting deep links / universal links

### ISSUE THREAD

**Issue by Estevete** [facebook/react-native#38266]
### Description

I have configured deep links & Universal Linking in my app (AASA, Assetlinks...). Let's say my Universal Link is https://example.com/profile. If I tap on that link outside the app, it opens correctly the app.

The issue comes when I use `Linking.openURL("https://example.com/profile")` inside the app. It opens the WebBrowser instead of opening in the app (since it's a universal link).

If I try to open for example instagram `openURL("https://instagram.com")`, it opens the instagram app (and not the web browser)...

The reason of this is because I have implemented the redirectURL, so if I send any link through the email and the user has to be logged in in order to access to it, then I redirect the user after he logs in.

Some months ago, this used to work correctly. This is happening on Android and iOS.

The same behavior happens if I use `expo-linking` package instead.

### React Native Version

0.71.8

### Output of `npx react-native info`

```
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 AMD Ryzen 7 5800X 8-Core Processor
    Memory: 20.96 GB / 31.93 GB
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 9.6.2 - ~\node_modules\.bin\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.18362.0, 10.0.19041.0, 10.0.22000.0, 10.0.22621.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 17.5.33627.172 (Visual Studio Community 2022)
  Languages:
    Java: 11.0.16.1
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.8 => 0.71.8
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
info React Native v0.72.1 is now available (your project is running on v0.71.8).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.72.1
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.71.8
info For more info, check out "https://reactnative.dev/docs/upgrading".
```

### Steps to reproduce

1. Configure your app to use universal links / deep links
2. Set openURL("..") to your configured universal link
3. It will open the webbrowser

**Comment by RajithaKumara** [comment]
Hi @Estevete, do you have any solution for this? I also have the same issue.

**Comment by collinahn** [comment]
Facing the same problem, I managed to open a hidden webview and open the universal links inside the webview.
works in iOS when the target app is installed, and no success in android.
