### ISSUE TITLE
unabled to load script.Make sure're  either runnin Metro or that your bundle index.android,bundle is packaged corre.....

### ISSUE THREAD

**Issue by fnandofalotico** [facebook/react-native#38277]
### Description

Not Working npx react-native@latest init AwesomeProject

not even the web sample following the start instructions.
I am standing about to abandon the use of react which I have started a few months ago

### React Native Version

0.72.1

### Output of `npx react-native info`

ApInCo>react-native info
info Fetching system and libraries information...
System:
  OS: Windows 10 10.0.19044
  CPU: (4) x64 Intel(R) Core(TM) i7-3540M CPU @ 3.00GHz
  Memory: 9.64 GB / 15.90 GB
Binaries:
  Node:
    version: 18.16.1
    path: C:\Program Files\nodejs\node.EXE
  Yarn:
    version: 1.22.19
    path: C:\Program Files (x86)\Yarn\bin\yarn.CMD
  npm:
    version: 9.8.0
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK:
    API Levels:
      - "33"
    Build Tools:
      - 30.0.3
      - 33.0.0
      - 34.0.0
    System Images:
      - android-33 | Google APIs Intel x86_64 Atom
      - android-34 | Google APIs Intel x86_64 Atom
      - android-UpsideDownCakePrivacySandbox | Google Play Intel x86_64 Atom
    Android NDK: Not Found
  Windows SDK: Not Found
IDEs:
  Android Studio: AI-222.4459.24.2221.10121639
  Visual Studio: Not Found
Languages:
  Java: 17.0.7
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.1
    wanted: 0.72.1
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

C:\Users\ferna\ApInCo>cd/

C:\>react-native info
error: unknown command 'info'
(Did you mean init?)

C:\>

### Steps to reproduce

npm uninstall -g react-native-cli @react-native-community/cli
npx react-native@latest init AwesomeProject
npm start
npm run android

### Snack, code example, screenshot, or link to a repository

![Screenshot_20230710-133657](https://github.com/facebook/react-native/assets/135785991/db6a2a80-1d78-4b6d-8f87-97ecd9c66d78)

**Comment by cortinico** [comment]
Can you provide more context on what you're doing?
Are you on a device or on a emulator?
Did the problem happened after you did something?
Also what is the Metro console window saying?

**Comment by aqigif** [comment]
i got same issue. and solved by adding android:usesCleartextTraffic="true" in AndroidManifest.xml > application

kinda looks like this : 
`
<?xml version="1.0" encoding="utf-8"?>
<manifest ...>
    <uses-permission android:name="android.permission.INTERNET" />
    <application
        ...
        android:usesCleartextTraffic="true"
        ...>
        ...
    </application>
</manifest>`

**Comment by aqigif** [comment]
I encountered a similar issue and was found temporary solution by adding `android:usesCleartextTraffic="true"` in the AndroidManifest.xml file. 

```html
<manifest ...>
    <uses-permission android:name="android.permission.INTERNET" />
    <application
        ...
        android:usesCleartextTraffic="true"
        ...>
        ...
    </application>
</manifest>

``` 

This attribute allows the app to make clear text (non-HTTPS) network requests. I think the RN app cannot request jsbundle from metro because of this issue.

**Comment by cortinico** [comment]
@aqigif that's already in the template:
https://github.com/facebook/react-native/blob/06668fcbacd750771f1d53cce829dc55e86f3f3c/packages/react-native/template/android/app/src/debug/AndroidManifest.xml#L6

So that's definitely not a fix (unless the user removed that line for a valid reason)

**Comment by aqigif** [comment]
> @aqigif that's already in the template:
> 
> https://github.com/facebook/react-native/blob/06668fcbacd750771f1d53cce829dc55e86f3f3c/packages/react-native/template/android/app/src/debug/AndroidManifest.xml#L6
> 
> So that's definitely not a fix (unless the user removed that line for a valid reason)

oya, thanks. yea just checked my code. my androidmanifest.xml was removed in debug. i forgot why, we remove that.


but that's the case on my side is related to usesCleartextTraffic

**Comment by fnandofalotico** [comment]
Change last versión. 
Thanks

**Comment by fnandofalotico** [comment]
Thanks

**Comment by Haidar-786** [comment]
I'm facing the same issue both in the debug Apk and internal Testing release Apk.  Did anyone sloved this issue?  Please comment below  

bulid.gradle   (android/bulid.gradle)
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "33.0.0"
        minSdkVersion = 24
        compileSdkVersion = 33
        targetSdkVersion = 33
        kotlin_version = '1.8.10'
        //OLD CODE 
        // buildToolsVersion = "31.0.0"
        // minSdkVersion = 24
        // compileSdkVersion = 31
        // targetSdkVersion = 31
        // kotlin_version = '1.6.0'

        
        if (System.properties['os.arch'] == "aarch64") {
            // For M1 Users we need to use the NDK 24 which added support for aarch64
            ndkVersion = "24.0.8215888"
        } else {
            // Otherwise we default to the side-by-side NDK version from AGP.
            ndkVersion = "21.4.7075529"
        }
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:7.2.1")
        classpath("com.facebook.react:react-native-gradle-plugin")
        classpath("de.undercouch:gradle-download-task:5.0.1")
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
         // Firebase dependencies
        classpath 'com.google.gms:google-services:4.3.14'
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version")
    }
}

allprojects {
    repositories {
    //      exclusiveContent {
    //        filter {
    //            includeGroup "com.facebook.react"
    //        }
    //        forRepository {
    //            maven {
    //                url "$rootDir/../node_modules/react-native/android"
    //            }
    //        }
    //    }
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }
          maven {
            url "$rootDir/../node_modules/react-native-video-cache/android/libs"
        }
         // ADD THIS
        mavenCentral {
            // We don't want to fetch react-native from Maven Central as there are
            // older versions over there.
            content {
                excludeGroup "com.facebook.react"
            }
        }
        maven { // <---- Add this block
            url "https://github.com/jitsi/jitsi-maven-repository/raw/master/releases"
        }
        google()
         maven { url 'https://maven.google.com' }
        maven { url 'https://www.jitpack.io' }
    }
}

subprojects {
    if(project['name'] == 'react-native-reanimated'){
        project.configurations { compile { } }
    }
}


Android.manifest      (android/app/src/debug /android.manifest)
v<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools">

    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>

    <application
        android:usesCleartextTraffic="true"
        tools:targetApi="28"
        tools:ignore="GoogleAppIndexingWarning">
        <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" android:exported="false" />
    </application>
</manifest>
