### ISSUE TITLE
Request of adding Responder / callback function while swiping back the navigators

### ISSUE THREAD

**Issue by DickyT** [facebook/react-native#3827]
Hi,
Can we add the Responder method / callback function to access the current coordinate(x, y) of the current touch point? Because in some cases we need to get this data.

I went through the documentation and I cannot find the solution. There is a few resources about the Navigator.SceneConfigs.

Thanks

![react-native-issue](https://cloud.githubusercontent.com/assets/4535844/10872046/cc27580e-80cf-11e5-801f-8d34299a6fe7.gif)

**Comment by DickyT** [comment]
PS
I tried to use event responder to catch the root <View/>, but once the side to back triggered, the gesture recognizer is rejected, I can no more get the onResponderMove call

**Comment by christopherdro** [comment]
@facebook-github-bot stack-overflow
