### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by hrutik7** [facebook/react-native#38285]
### Description

when I am trying to run android emulator i am getting this error .

![image](https://github.com/facebook/react-native/assets/62372737/a359d766-a963-428c-a12a-96567ea65b08)

### React Native Version

 0.72.1

### Output of `npx react-native info`

System:
  OS: Windows 10 10.0.22621
  CPU: "(16) x64 AMD Ryzen 7 5700U with Radeon Graphics         "
  Memory: 1.14 GB / 13.86 GB
Binaries:
  Node:
    version: 18.12.0
    path: C:\Program Files\nodejs\node.EXE
  Yarn:
    version: 1.22.19
    path: C:\Program Files\nodejs\yarn.CMD
  npm:
    version: 8.19.2
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK:
    API Levels:
      - "30"
      - "31"
      - "33"
    Build Tools:
      - 30.0.2
      - 30.0.3
      - 31.0.0
      - 33.0.0
    System Images:
      - android-31 | Google APIs Intel x86 Atom_64
    Android NDK: Not Found
  Windows SDK: Not Found
IDEs:
  Android Studio: Not Found
  Visual Studio: Not Found
Languages:
  Java: 1.8.0_372
  Ruby:
    version: 2.7.5
    path: C:\Ruby27-x64\bin\ruby.EXE
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.1
    wanted: 0.72.1
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

### Steps to reproduce

1 . hit npm start
2 . press a

### Snack, code example, screenshot, or link to a repository

![image](https://github.com/facebook/react-native/assets/62372737/4c4b908d-f7aa-4c10-a743-8be1c3acf998)

**Comment by cortinico** [comment]
> Java: 1.8.0_372

The issue happens as you're on Java 8, while you should be on Java >= 11 for React Native 0.72

Also if you run `react-native doctor` it should tell you about this problem
