### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by hrutik7** [facebook/react-native#38284]
### New Version

 0.72.1

### Old Version

 0.6

### Build Target(s)

android simulator

### Output of `react-native info`

System:
  OS: Windows 10 10.0.22621
  CPU: "(16) x64 AMD Ryzen 7 5700U with Radeon Graphics         "
  Memory: 1.14 GB / 13.86 GB
Binaries:
  Node:
    version: 18.12.0
    path: C:\Program Files\nodejs\node.EXE
  Yarn:
    version: 1.22.19
    path: C:\Program Files\nodejs\yarn.CMD
  npm:
    version: 8.19.2
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK:
    API Levels:
      - "30"
      - "31"
      - "33"
    Build Tools:
      - 30.0.2
      - 30.0.3
      - 31.0.0
      - 33.0.0
    System Images:
      - android-31 | Google APIs Intel x86 Atom_64
    Android NDK: Not Found
  Windows SDK: Not Found
IDEs:
  Android Studio: Not Found
  Visual Studio: Not Found
Languages:
  Java: 1.8.0_372
  Ruby:
    version: 2.7.5
    path: C:\Ruby27-x64\bin\ruby.EXE
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.1
    wanted: 0.72.1
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

### Issue and Reproduction Steps

1. Hit command npm start
2 . type a

**Comment by cortinico** [comment]
Closing as invalid as you provided no information at all.
We would need at least the full build log.
