### ISSUE TITLE
React Native unable to find files/frameworks during build

### ISSUE THREAD

**Issue by tried-n-true** [facebook/react-native#38309]
### Description

When I go to build, it basically goes one by one of things I've imported or Pods that I have any it can't find them.

I'm able to add them to the schema and build them, and then the error moves onto the next import/Pod. It feels like React Native doesn't know where to look for my imported files, but they're there... somewhere.

### React Native Version

0.71.8

### Output of `npx react-native info`

System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1
    Memory: 66.98 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 20.4.0 - /opt/homebrew/bin/node
    Yarn: Not Found
    npm: 9.7.2 - /opt/homebrew/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.12.1 - /Users/xyz/.gem/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.8 => 0.71.8 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Here's a sample pattern:

1. Build main project
2. 'React/RCTBridgeDelegate.h' file not found
3. Add React schema & Build it
4. Build main project
5. 'FirebaseCore/FirebaseCore.h' file not found
6. Add Firebase schema & Build it
7. Build main project
8. Next unfound file...
9. The same is true for my Pods, it will say "framework not found for AppAuth"

### Snack, code example, screenshot, or link to a repository

<img width="261" alt="Screenshot 2023-07-12 at 1 05 36 AM" src="https://github.com/facebook/react-native/assets/1616865/bf990be3-eb49-40eb-b2d1-b0bae84e6911">
<img width="566" alt="Screenshot 2023-07-12 at 1 06 29 AM" src="https://github.com/facebook/react-native/assets/1616865/cc1d420f-30b1-4d9e-b994-729f11a80573">
<img width="274" alt="Screenshot 2023-07-12 at 1 07 45 AM" src="https://github.com/facebook/react-native/assets/1616865/09429e58-09a9-4cb5-93a9-6f4d7cabb9b5">
<img width="249" alt="Screenshot 2023-07-12 at 1 08 30 AM" src="https://github.com/facebook/react-native/assets/1616865/87621403-ee53-4f2d-a9ef-b5a91d0df8ee">

**Comment by tried-n-true** [comment]
Upgraded to latest patch, issue persists.

**Comment by Milutin-P** [comment]
Can you verify that you're opening `./ios/projectname.xcworkspace` and not `./ios/projectname.xcodeproj` file in XCode?

**Comment by yurberz** [comment]
**I have a similar situation.**

info Fetching system and libraries information...
System:
  OS: macOS 13.3.1
  CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Memory: 786.46 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 16.14.0
    path: ~/.nvm/versions/node/v16.14.0/bin/node
  Yarn:
    version: 1.22.17
    path: /usr/local/bin/yarn
  npm:
    version: 9.7.2
    path: ~/.nvm/versions/node/v16.14.0/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.12.1
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.2
      - iOS 16.2
      - macOS 13.1
      - tvOS 16.1
      - watchOS 9.1
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.2 AI-222.4459.24.2221.10121639
  Xcode:
    version: 14.2/14C18
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 19.0.1
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.2
    wanted: 0.72.2
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
  
###   Steps to reproduce
1. npx react-native@latest init AwesomeProject
2. run in simulator or device

###  Screenshot
<img width="334" alt="Знімок екрана 2023-07-12 о 11 39 49" src="https://github.com/facebook/react-native/assets/71183793/7657d3b7-3fc2-4405-95db-4bb01b6026ad">

**Comment by cortinico** [comment]
> When I go to build, it basically goes one by one of things I've imported or Pods that I have any it can't find them.
> I'm able to add them to the schema and build them, and then the error moves onto the next import/Pod. It feels like React Native doesn't know where to look for my imported files, but they're there... somewhere. Any ideas?

Thanks for the report, but I'm unsure what are we supposed to do here. This is a place to report bug, not a place to seek support for your specific project.

**Comment by tried-n-true** [comment]
> Can you verify that you're opening `./ios/projectname.xcworkspace` and not `./ios/projectname.xcodeproj` file in XCode?

Yep this is xcworkspace. I'm reporting it as it seems like a bug.
