### ISSUE TITLE
SocketRocket not found in spec

### ISSUE THREAD

**Issue by Milutin-P** [facebook/react-native#38300]
### Description

I have several react-native apps that are successfully using react-native 0.71.12 in production. 
Since 0.72.x came out I've followed for each of them upgrade guide from 0.71.12 to 0.72.0, 0.72.1 and 0.72.2. Every time I get the very same error when performing `pod install`.

I initialized a new react-native-cli project using `npx react-native@latest init` for each of the versions when they were released, but unfortunately no luck. This is the output when I perform `pod install` in a fresh project.

```
Framework build type is static library
[Codegen] Generating ./build/generated/ios/React-Codegen.podspec.json
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
[Codegen] Found FBReactNativeSpec
Fetching podspec for `RCT-Folly` from `../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec`
[Codegen] Found rncore
Fetching podspec for `boost` from `../node_modules/react-native/third-party-podspecs/boost.podspec`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
Fetching podspec for `hermes-engine` from `../node_modules/react-native/sdks/hermes-engine/hermes-engine.podspec`
[Hermes] Using the release tarball from Maven Central
[!] CocoaPods could not find compatible versions for pod "SocketRocket":
  In Podfile:
    React-Core/RCTWebSocket (from `../node_modules/react-native/`) was resolved to 0.72.2, which depends on
      SocketRocket (= 0.6.1)

None of your spec sources contain a spec satisfying the dependency: `SocketRocket (= 0.6.1)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
 ```
 
 My cocoapods is above v1.12 and ruby is above v2.6.10 as specified in `Gemfile`. I've also tried `arch -x86_64 pod install`, `RCT_NEW_ARCH_ENABLED=1 pod install` and disabling hermes, fabric, flipper but still no luck.

My `node_modules/react-native/React-Core.podspec` is exactly the same as the one from the source code https://github.com/facebook/react-native/blob/0.72-stable/packages/react-native/React-Core.podspec
As well as the `node_modules/react-native/React.podspec` https://github.com/facebook/react-native/blob/0.72-stable/packages/react-native/React.podspec

### React Native Version

0.72.2

### Output of `npx react-native info`

```
System:
  OS: macOS 13.4.1
  CPU: (8) arm64 Apple M1
  Memory: 496.00 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.16.0
    path: ~/.nvm/versions/node/v18.16.0/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 9.5.1
    path: ~/.nvm/versions/node/v18.16.0/bin/npm
  Watchman:
    version: 2023.07.10.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /Users/____/.asdf/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
IDEs:
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Ruby:
    version: 2.7.5
    path: /Users/___/.asdf/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Steps to reproduce

1. Initialize project with`npx react-native@latest init testproject`
2. Wait for the CocoaPods installation to fail
3. `cd ./testproject/ios`
4. pod install

### Snack, code example, screenshot, or link to a repository

Output of `pod install --verbose`

<img width="1268" alt="image" src="https://github.com/facebook/react-native/assets/7932073/8cbb4ee7-6052-4c14-a021-44954b9c114d">

**Comment by fortmarek** [comment]
Hey @Milutin-P 👋 

Have you actually run the command `pod install` suggests: `pod install --repo-update`?

**Comment by Milutin-P** [comment]
Hey @fortmarek 👋🏼 

Thank you very much, that was the solution. Main problem was that I just ignored deep diving into the error that it threw.
That command was automatically executed when `pod install` failed. Just to be sure I've run it again and it threw an error again.

`Errno::EACCES - Permission denied @ rb_sysopen - /Users/___/.cocoapods/repos/trunk/all_pods_versions_a_9_3.txt.etag`

`pod install --repo-update` failed because of insufficient permissions. So, all I had to do was 
`sudo chown -R $(whoami) ~/.cocoapods` in order to set the permissions.

And re-execute `pod install --repo-update` again.

Thanks again, I'll close my issue because it has nothing to do with react-native library.

**Comment by alexghi** [comment]
this is interesting, because even though I did **exactly** how it's supposed to (with the flag `--repo-update`) I still get that same error no matter what. Any suggestions?  
<img width="708" alt="image" src="https://github.com/facebook/react-native/assets/11394898/d3ff13f6-9633-4b2e-8481-76f9fdc7b881">

**Comment by witekmikolajczak** [comment]
> this is interesting, because even though I did **exactly** how it's supposed to (with the flag `--repo-update`) I still get that same error no matter what. Any suggestions? <img alt="image" width="708" src="https://user-images.githubusercontent.com/11394898/262343941-d3ff13f6-9633-4b2e-8481-76f9fdc7b881.png">

I had same issue, try run following command: 
`bundle exec pod install --repo-update` in ios folder. For me it worked!

**Comment by vasylnahuliak** [comment]
My solution using https://github.com/ds300/patch-package

```ruby
diff --git a/node_modules/react-native/React-Core.podspec b/node_modules/react-native/React-Core.podspec
index 56b9bc0..f49ea03 100644
--- a/node_modules/react-native/React-Core.podspec
+++ b/node_modules/react-native/React-Core.podspec
@@ -18,7 +18,7 @@ end
 
 folly_compiler_flags = '-DFOLLY_NO_CONFIG -DFOLLY_MOBILE=1 -DFOLLY_USE_LIBCPP=1 -Wno-comma -Wno-shorten-64-to-32'
 folly_version = '2021.07.22.00'
-socket_rocket_version = '0.6.1'
+socket_rocket_version = '0.7.0'
 boost_compiler_flags = '-Wno-documentation'
 
 use_hermes = ENV['USE_HERMES'] == '1'
```

**Comment by ucheNkadiCode** [comment]
@vasylnahuliak what do I name the file in the patches folder?

**Comment by vasylnahuliak** [comment]
> @vasylnahuliak what do I name the file in the patches folder?

`react-native+0.72.4.patch`

FYI: use your version of react native

**Comment by microJ** [comment]
I got same error when exec `npx pod-install`.

works for me from [react-native docs](https://reactnative.dev/docs/0.72/environment-setup#creating-a-new-application):
1. `bundle install --full-index --redownload`
2. `cd ios && bundle exec pod install --repo-update && cd ..`
