### ISSUE TITLE
Can react-native used in swift application

### ISSUE THREAD

**Issue by zixun** [facebook/react-native#3830]
Can react-native used in swift application？ and how to import it ?

**Comment by DickyT** [comment]
I think it is hard to configure React Native in a Swift Project. But you can bridge swift file to the existing Objective C project.

For example, I want to export a Swift Class call ```MyExportSwiftClass```

1. right click the file tree and add a swift file to existing project, and create a bridging file while creating swift file. If XCode did not ask you to do so, you can create yourself. The filename of the bridging file will be ```{YourProjectName}-Bridging-Header.h```, and the file should be empty.

2. create a Obj C file, which ends with *.m

```
#import "RCTBridgeModule.h"

@interface RCT_EXTERN_MODULE(MyExportSwiftClass, NSObject)

RCT_EXTERN_METHOD(helloWorld)

@end
```

3. create a swift file, with ends with *.swift

```
@objc(MyExportSwiftClass)
class MyExportSwiftClass: NSObject {
  
  @objc func helloWorld() {
    print("hello from swift")
  }
}
```

4. And you can call wherever in you React Native project like this
```
const React = require('react-native');
const {
  helloWorld
} = React.NativeModules.MyExportSwiftClass;

helloWorld();
```
![screen shot 2015-11-02 at 02 39 24](https://cloud.githubusercontent.com/assets/4535844/10875619/fb28c580-810a-11e5-8af9-05637f5e43bf.png)

enjoy!

**Comment by ide** [comment]
@DickyT's answer is right. Thanks for answering!

**Comment by DickyT** [comment]
@ide ur welcome LOL
