### ISSUE TITLE
Can't use the new performance.reactNativeStartupTiming

### ISSUE THREAD

**Issue by saif-o99** [facebook/react-native#38316]
### Description

Thank you for keep improving RN.

im trying to use the new `performance.reactNativeStartupTiming`
which in https://github.com/facebook/react-native/commit/c1023c73b010245f2e8182b75cc3bccd112d5e2e
it says 'This diff adds the `performance.reactNativeStartupTiming` API to the performance global object for RN.'
so when i try to log the `global.performance` object it just gives me one function `{"now": [Function anonymous]}`.

there something wrong or the feature is not completed yet?

### React Native Version

0.72.3

### Output of `npx react-native info`

System:
  OS: Windows 10 10.0.22621
  CPU: "(12) x64 AMD Ryzen 5 5600X 6-Core Processor             "
  Memory: 2.41 GB / 15.94 GB
Binaries:
  Node:
    version: 18.12.1
    path: C:\Program Files\nodejs\node.EXE
  Yarn:
    version: 1.22.19
    path: ~\AppData\Roaming\npm\yarn.CMD
  npm:
    version: 8.19.2
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK: Not Found
IDEs:
  Android Studio: AI-212.5712.43.2112.8609683
  Visual Studio:
    - 16.11.32510.428 (Visual Studio Community 2019)
    wanted: 0.72.2
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

### Steps to reproduce

write `console.log(global.performance);` in App.tsx

### Snack, code example, screenshot, or link to a repository

https://github.com/saif-o99/Awesome-project

**Comment by robrechtme** [comment]
Same, would be nice if this API is a bit more documented.

**Comment by sidferreira** [comment]
Not working indeed... it is like it is not loading...

**Comment by sidferreira** [comment]
No news here?

**Comment by saif-o99** [comment]
> No news here?

Not for me. I just gave up on it

**Comment by abdelhamid-f-nasser** [comment]
It got renamed from `performance.reactNativeStartupTiming` to `performance.rnStartupTiming` and it is still private as mentioned [here](https://github.com/facebook/react-native/pull/42762#issue-2109898426).
