### ISSUE TITLE
How to achieve both horizontal & vertical scrollView for macos App 

### ISSUE THREAD

**Issue by musheer-ahamed** [facebook/react-native#38313]
### Description

I want to give Horizontal and vertical scroll for one Screen. this should work simultaneously.
How we can achieve this scenario? 

### React Native Version

 "react-native-macos": "^0.66.58",

### Output of `npx react-native info`

Not able to enable horizontal & vertical scrollView for single scrollview

### Steps to reproduce

Add scrollView on the screen.
 If I set horizontal ={true} then vertical is not working or   If I set horizontal ={false} then horizontal is not working

### Snack, code example, screenshot, or link to a repository

 <ScrollView
          showsHorizontalScrollIndicator={true}
          showsVerticalScrollIndicator={true}
          nestedScrollEnabled={true}
          bounces={true}
          hasHorizontalScroller={true}
          hasVerticalScroller={true}
          horizontal={false}
          contentContainerStyle={[MACOS && styles.srcollContainerStyle]}
          onLayout={event => setRootWidth(event.nativeEvent.layout.width)}>
          </ScrollView>

**Comment by cortinico** [comment]
> "react-native-macos": "^0.66.58",

Also please report this to `react-native-macos`
