### ISSUE TITLE
How do we retrieve phone number and device information with React Native Android?

### ISSUE THREAD

**Issue by ACCTFORGH** [facebook/react-native#3832]
I don't see related API in the doc. It was not in the API roadmap either. Do we have to wrap the native API ourselves? Sorry if I missed any information.

Thank you!

Same question is asked in StackOverflow: http://stackoverflow.com/questions/33472742/how-do-we-retrieve-phone-number-and-device-information-with-react-native-android

**Comment by ide** [comment]
There isn't a module for this so you should write one if you need it.
