### ISSUE TITLE
How to send event to Javascript when use Turbo Native Module?

### ISSUE THREAD

**Issue by zhuliminl** [facebook/react-native#38330]
### Description

How to send event to Javascript when use Turbo Native Module?

### React Native Version

0.72.2

### Output of `npx react-native info`

How to send event to Javascript when use Turbo Native Module?

### Steps to reproduce

How to send event to Javascript when use Turbo Native Module?

### Snack, code example, screenshot, or link to a repository

How to send event to Javascript when use Turbo Native Module?

**Comment by birdofpreyru** [comment]
Hey @zhuliminl , you can check the code of this library of mine: https://github.com/birdofpreyru/react-native-static-server
It uses New Arch, with backward compatibility with Old Arch, for Android, iOS, Mac Catalyst, and Windows as target platforms, and it sends Native > JS events in on all platforms, so you should be able to use it as the practical example.
