### ISSUE TITLE
app is not starting in emulator and showing this on console Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.tadashidate/.MainActivity }

### ISSUE THREAD

**Issue by hrutik7** [facebook/react-native#38332]
### Description

When I hit command npm run android . its saying app keep stoping

### React Native Version

 0.72.1

### Output of `npx react-native info`

System:
  OS: Windows 10 10.0.22621
  CPU: "(16) x64 AMD Ryzen 7 5700U with Radeon Graphics         "
  Memory: 1.96 GB / 13.86 GB
Binaries:
  Node:
    version: 18.12.0
    path: C:\Program Files\nodejs\node.EXE
  Yarn:
    version: 1.22.19
    path: C:\Program Files\nodejs\yarn.CMD
  npm:
    version: 8.19.2
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK: Not Found
IDEs:
  Android Studio: Not Found
  Visual Studio: Not Found
Languages:
  Java: 1.8.0_372
  Ruby:
    version: 2.7.5
    path: C:\Ruby27-x64\bin\ruby.EXE
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.2
    wanted: 0.72.2
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

### Steps to reproduce

npm run android

### Snack, code example, screenshot, or link to a repository

![image](https://github.com/facebook/react-native/assets/62372737/8e1a5e24-0e6b-4b82-8085-9b240c71cf03)

**Comment by cortinico** [comment]
> When I hit command npm run android . its saying app keep stoping

Can you clarify? Who is "it"?
Can you provide a screenshot?

**Comment by hrutik7** [comment]
terminal 
![image](https://github.com/facebook/react-native/assets/62372737/3bbe646b-bfc6-4d57-addd-151863e798de)

emulator

![image](https://github.com/facebook/react-native/assets/62372737/205c07ab-83e5-4c58-905f-670d39db19ed)

**Comment by cortinico** [comment]
We would need your app source code, as there is something going on over there.

**Comment by hrutik7** [comment]
here is the repo 
https://github.com/hrutik7/Tadashi

**Comment by francis-Paul-code** [comment]
I seem to have the same exact problem  @hrutik7  could you post how you solved this

**Comment by hrutik7** [comment]
hey @francis-Paul-code 
the problem was in gradle files . I did a lot of changes in that that's why overall code was messed up
I will suggest look carefully on those android/ios files

**Comment by francis-Paul-code** [comment]
@hrutik7 alright thanks for the feedback I'll try your suggestion

**Comment by syedzubyl** [comment]
i face same problem 😢 , i stuck with 2 weeks , here (156 warnings whats meant to be)

![Image](https://github.com/user-attachments/assets/e55ff0d5-a062-4188-a5e9-d8337e833279)

**Comment by whY-note** [comment]
Have you solve this problem? I met the same problem with you. Could you teach me how to solve it?
Your early reply will be highly appreciated.

![Image](https://github.com/user-attachments/assets/3d36071b-1469-4979-b89e-17211e03a02a)

**Comment by Optimus-NP** [comment]
I'm experiencing the same issue as described above. Has anyone found a reliable solution or workaround for this problem? Any help would be greatly appreciated!
![Image](https://github.com/user-attachments/assets/a4273394-39f2-413a-8df1-365e57cbd4a5)
