### ISSUE TITLE
Unhandled JS Exception: Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'DevSettings' could not be found. Verify that a module by this name is registered in the na..., stack:

### ISSUE THREAD

**Issue by alicanccelikk** [facebook/react-native#38346]
### Description

Im trying to use release mode to send my application to store. But i couldn't do that. Its working debug mode, android release mode but in ios release mode its not working. Im using default schemes without any changes and my important packages;

expo 48.0.18,
react-native 0.71.8
react 18.2.0
react-native-reanimated ~2.14.4
react-native-gesture-handler ~2.9.0

### React Native Version

 0.71.8

### Output of `npx react-native info`

System:
    OS: macOS 12.6.3
    CPU: (10) arm64 Apple M1 Pro
    Memory: 79.31 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - ~/Desktop/Projects/OkayAnketForm/node_modules/.bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
    Watchman: 2023.03.13.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /Users/alicanca/.rvm/rubies/ruby-2.7.6/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9477386
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

open xcode -> edit scheme -> run release mode -> build successfully but stuck in splash screen and throw an error as i shared in screen shoot 

### Snack, code example, screenshot, or link to a repository

<img width="1048" alt="image" src="https://github.com/facebook/react-native/assets/121544157/726687c9-8a96-402d-a412-454329f9b181">

**Comment by JustinRohweller** [comment]
I'm experiencing the same issue, even when I set react-native to 0.71.12.

**Comment by JustinRohweller** [comment]
I upgraded my SDK to 49 and now the Release configuration works properly.

**Comment by KingAmo** [comment]
see: https://github.com/facebook/react-native/issues/38445#issuecomment-2128828381
