### ISSUE TITLE
TextLayout doesn't work as expected on Android.

### ISSUE THREAD

**Issue by Zombie1995** [facebook/react-native#38341]
### Description

When change the value of a Text with a View inside, the View is not always set after the text. For example, if there are two lines, then the view will not be moving on the second line while typing. It works fine on iOS and Web.

### React Native Version

0.73.0

### Output of `npx react-native info`

null

### Steps to reproduce

Start the snack and type the text until you see the issue.
`import React, { useState } from 'react';
import {
  TextInput,
  View,
  Text,
} from 'react-native';

export default function App() {
  const [state, setState] = useState();
  return (
    <View>
      <Text>
        {state}
        <View style={{ backgroundColor: 'grey' }}>
          <Text>dddddd</Text>
        </View>
      </Text>
      <TextInput
        multiline
        onChangeText={(text) => setState(text)}
      />
    </View>
  );
}
`

### Snack, code example, screenshot, or link to a repository

https://snack.expo.dev/@zombie1995/text-issue

**Comment by cortinico** [comment]
> 0.73.0

Closing as this version of React Native doesn't exists.
Plus you haven't provided the output of `npx react-native info` which is mandatory.

**Comment by cortinico** [comment]
Please provide them and re-open the issue

**Comment by Zombie1995** [comment]
Reopened

**Comment by Zombie1995** [comment]
Reopen please
