### ISSUE TITLE
[PickerIOS] Is not correctly rendered if hide and show

### ISSUE THREAD

**Issue by elisei-timofte** [facebook/react-native#3835]
I'm using this [technique](http://stackoverflow.com/questions/30266831/hide-show-components-in-react-native) for hide and show react component. I have two pickers. One for the book, one for the chapter. If I render them without hide and show (set the "showPicker: false" it is rendered well) 
<img width="376" alt="screen shot 2015-11-02 at 10 27 52 am" src="https://cloud.githubusercontent.com/assets/6162068/10877193/8184b99a-814c-11e5-9709-c2e3f8950fbe.png">
 P.S Colors are for a better view of the changes :)
 
but if I render it with hide and show (showPicker: false) and click on the trigger button it will render like this: 
<img width="380" alt="screen shot 2015-11-02 at 10 28 04 am" src="https://cloud.githubusercontent.com/assets/6162068/10877209/b9851a88-814c-11e5-9e9a-d61ebe3028d1.png">

It seems to me that the first pickerIOS doesn't set it's css style and take the whole screen (320 px, like in the foto 
<img width="372" alt="screen shot 2015-11-02 at 10 32 36 am" src="https://cloud.githubusercontent.com/assets/6162068/10877238/1d786fc2-814d-11e5-800d-b1c201367872.png"> 
The second one it is rendered from the right spot, but also takes 320 px
<img width="366" alt="screen shot 2015-11-02 at 10 33 45 am" src="https://cloud.githubusercontent.com/assets/6162068/10877253/3beb4902-814d-11e5-851a-2d62c013eee1.png">

Is there a solution for this? Am I doing something wrong?

Here is my code source:

```javascript
React.createClass({
  getInitialState: function() {
    return {
      bcode: this.props.rowData.bcode,
      chapter: this.props.rowData.chapter,
      showPicker: true,
    }
  },
  togglePicker: function () {
    this.setState({
      showPicker: !this.state.showPicker,
    });
  },
  _renderPicker: function () {
    if(this.state.showPicker) {
      return (
        <View style={styles.pickerContainer}>
          <PickerIOS
            style={styles.bcode}
            onValueChange={(b) => this.setState({bcode: b})}
            selectedValue={this.state.bcode} >
            {_.keys(bibleChapters).map((bcode) => (
              <PickerItemIOS
                value={bcode}
                label={bibleChapters[bcode].title}
                />
              )
            )}
          </PickerIOS>
          <PickerIOS  style={styles.chapter}
            onValueChange={(c) => this.setState({chapter: c})}
            selectedValue={this.state.chapter} >
            {_.range(1, bibleChapters[this.state.bcode].chapters + 1).map((chapter) => (
              <PickerItemIOS
                value={chapter}
                label={chapter.toString()}
                />
              )
            )}
          </PickerIOS>
          <Button textStyle={styles.go} text="&gt;" style={styles.goContainer} onPress={screenUtils.pushRoute.bind(this, ['bible', 'chapter', [this.state.bcode, this.state.chapter]])}/>
        </View>
      );
    } else {
      return
    }
  },
  render: function() {
    var joinedText= "" + bibleChapters[this.state.bcode].title + " " + this.state.chapter
    return (
      <View style={styles.bibleNav}>
        <Button text={joinedText} textStyle={[gStyles.btnLink, styles.btn]} onPress={this.togglePicker}/>
        {this._renderPicker()}
      </View>
    );
  }
});

var styles = StyleSheet.create({
  pickerContainer: {
    flex: 1,
    flexDirection: 'row',
  },
  bcode: {
    width: 150,
    backgroundColor: 'blue'
  },
  chapter: {
    width: 170,
    backgroundColor: 'yellow'
  },
  goContainer: {
    paddingTop: 81,
  },
  go: {
    fontSize: 40,
    fontWeight: '200',
  },
  bibleNav: {
    padding: 10,
    paddingLeft: 30,
  },
  btn: {
    fontSize: 25
  },
});
```

**Comment by elisei-timofte** [comment]
after more debugging I saw that if I change the book value, the chapter picker is rendered correctly
<img width="379" alt="screen shot 2015-11-02 at 11 41 48 am" src="https://cloud.githubusercontent.com/assets/6162068/10878513/bb94cbb6-8156-11e5-9796-264d34f493ea.png">
This is a very strange bug. ;(

Any ideas of how can I fix thid? Thanks

**Comment by christopherdro** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

If you'd like you can create an issue on [Product Pains](https://productpains.com/product/react-native).
ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. 

Also, if this issue is a bug, please consider sending a PR with a fix. Thanks!
