### ISSUE TITLE
Error: Unable to resolve module

### ISSUE THREAD

**Issue by ghost** [facebook/react-native#38360]
### Description
Happens only in iOS

Error: Unable to resolve module ./Libraries/Components/DatePicker/DatePickerIOS from /Library/MyFolder/App/Mobile App/App/node_modules/react-native/index.js

None of these files exist:
* node_modules/react-native/Libraries/Components/DatePicker/DatePickerIOS(.native|.native.ts|.ts|.native.tsx|.tsx|.native.js|.js|.native.jsx|.jsx|.native.json|.json)

### React Native Version

0.70.8

### Output of `npx react-native info`

System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M1
    Memory: 67.48 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 19.8.1 - /opt/homebrew/bin/node
    Yarn: Not Found
    npm: 9.5.1 - /opt/homebrew/bin/npm
    Watchman: 2023.03.27.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.8 => 0.70.8 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Open terminal
enter: npx expo start
enter: i
After opening app in iOS simulator the console shows the error.

### Snack, code example, screenshot, or link to a repository

.

**Comment by tarunrajput** [comment]
DatePickerIOS is deprecated. Please consider using one of the [community packages](https://reactnative.directory/?search=datepicker) instead.

**Comment by JOHNPAULNAIJU** [comment]
> DatePickerIOS is deprecated. Please consider using one of the [community packages](https://reactnative.directory/?search=datepicker) instead.

That is not the issue. I tried commenting the line causing the warning. Then the same warning occurs with component in the next line, say for example TextField.

**Comment by tarunrajput** [comment]
@JOHNPAULNAIJU,  Would you mind sharing a reproducer, please?

**Comment by kiranNegiloni** [comment]
Hi Team, I am unable to import / require 3gp extension files. Able to require mp3, mp4 extension files. Tried adding the 3gp extension to .flow_config. But still facing the same issue. Kindly help.
