### ISSUE TITLE
[0.15] Things we need to get in for 0.15

### ISSUE THREAD

**Issue by mkonicek** [facebook/react-native#3836]
Main thing to do: Cut the 0.15-stable branch, ideally Friday 6/11.

You need to make sure everything works on master (especially the "Getting started" flow on iOS and Android). If something's broken, fix it or chase people to fix it. Once master is in good state, cut the branch. Start testing everything on Thursday morning so you have a buffer and cut the branch on Friday.

Publishing is then easy, I'll be on messenger and can help with publishing to Maven Central.

cc @ide, @vjeux, @foghina

**Comment by mkonicek** [comment]
Here are the steps for cutting the branch:

- Make sure iOS and Android Getting Started flow works on master.
- Edit `ReactAndroid/gradle.properties`
- git checkout -b 0.15-stable
- In package.json, set version to e.g. 0.15.0-rc.
- In React.podspec, set version to e.g. 0.15.0-rc.
- In `local-cli/generator-android/templates/src/app/build.gradle` update the dependency to e.g. com.facebook.react:react-native:0.15.+
- git commit -m "[0.15] Bump versions"
- git push origin 0.15-stable

Publishing to Maven Central (I'm happy to do that):

- Edit `ReactAndroid/release.gradle` and uncomment Javadoc generation
- `./gradlew :ReactAndroid:installArchives` (java -version should print 1.7 which is currently needed for Javadoc generation). This creates artifacts in `~/.m2/repository`.
- Log into Sonatype and go to Staging upload: https://oss.sonatype.org/#staging-upload
- Select Artifact(s) with a POM (to publish to a local Maven repo for testing run ./gradlew :ReactAndroid:installArchives)
- Add all files: .aar, sources jar, javadoc jar, .asc for everything (including the POM file)

**Comment by chirag04** [comment]
@mkonicek is 0.15 going to be published this week?

**Comment by chirag04** [comment]
@mkonicek closing this since 0.15 is already released. I think we should document the "steps for cutting the branch"
