### ISSUE TITLE
[Android] Headers not present in fetch() response

### ISSUE THREAD

**Issue by mbajur** [facebook/react-native#3837]
Hello,
I'm trying to get headers of response returned and consumed by react-native's `fetch()` method but it seems there is something not right with it and the headers aren't there. 

I've seen few issues and commits that might be related to such issue (like for example here: https://github.com/facebook/react-native/commit/fe42a28de12926c7b3254420ccb85bef5f46327f ) but i'm not sure if it targets the issue i'am currently facing. Anyway, i have installed a react-native from master (to have that recent PR applied) and my api endpoint retuns the following headers:

    > curl --include 'http://192.168.0.111:3000/api/v1/items?limit=1'
    
    HTTP/1.1 200 OK
    X-Frame-Options: SAMEORIGIN
    X-XSS-Protection: 1; mode=block
    X-Content-Type-Options: nosniff
    Link: <http://192.168.0.111:3000/api/v1/items?limit=1&page=32>; rel="last", <http://192.168.0.111:3000/api/v1/items?limit=1&page=2>; rel="next"
    Total: 32
    Per-Page: 1
    Content-Type: application/json; charset=utf-8
    Cache-Control: no-store, must-revalidate, private, max-age=0

    (...)

But, my fetch method can't see them for some reason:

    fetch(CONFIG.api_url + '/items?limit=25').then(function(resp) {
      console.log(resp.headers)
      console.log(resp.headers.getAll())
      console.log(resp.headers.get('Link'))
    })

[![fetch output][1]][1]

Thanks in advance for any tips on how to access those headers (dirty hot-fixes welcome :)!

  [1]: http://i.stack.imgur.com/mfTob.png

**Comment by nucleartux** [comment]
Fixed in master. So I'm not sure you installed react from master.

**Comment by mbajur** [comment]
If it has been fixed in the linked commit (https://github.com/facebook/react-native/commit/fe42a28de12926c7b3254420ccb85bef5f46327f) i can confirm that i have those changes inside my `/node_modules/react_native/*` and the issue is still there.

**Comment by nucleartux** [comment]
Updating npm module not help, you should also build react native from java sources.

**Comment by mbajur** [comment]
That's what i've done to use it:

1. Changed `react-native` line in `package.json` to:  

        (...)
        "react-native": "facebook/react-native#master",
        (...)

2. Removed `node_modules/react-native` dir
3. `npm install`
4. react-native run-android

However, i'm not an node/js/npm ace so please forgive me if i've done some rediculous mistake in here :)

**Comment by nucleartux** [comment]
Building from react native from sources(not from npm module) is very hard and complex process. I think you can just wait for new release https://github.com/facebook/react-native/issues/3836

**Comment by mbajur** [comment]
Oh i see, thanks for the info! I'm closing this then.

**Comment by ram535ii** [comment]
It doesn't look like that fix went out in #3836 since I updated to 0.15.0 through npm and am still experiencing it. Any idea when it might go out?
