### ISSUE TITLE
How can I put a ListView inside a ScrollView using React Native iOS?

### ISSUE THREAD

**Issue by wootwoot1234** [facebook/react-native#3839]
I'm building an iOS React Native app. I have some test content and then a list of items below it. If I put both the text content and the listview inside a scrollview the listview does't work properly (only shows some of the items) but if I don't put the listview inside the scrollview, the listview scrolls but the text content stays locked to the top of the screen. How do I get the text content to scroll with the listview?

Here's an example of my issue:
https://rnplay.org/apps/GWoFWg

**Comment by jjshammas** [comment]
This is more of a general mobile question. Typically, it's an anti-pattern to put a list/table view inside of a ScrollView, as the list/table view has a scrollable element in itself.

What I've done both native and in React Native is use only a ListView, and make the first cell include all of my top static content. Thus, it all scrolls as one scrollable region fluidly.

**Comment by wootwoot1234** [comment]
That's at least a workaround.  I could put the text above the listview in the render function so it's just part of the listview.  I don't know if it's the best solution but that will work, thanks!

I feel like I could use the``` renderScrollComponent``` function but I'm not sure how.  I couldn't find any examples.

**Comment by jaygarcia** [comment]
Couldn't you setup listview to flex:1 and maybe it doesn't scroll?

**Comment by wootwoot1234** [comment]
@jaygarcia It is set to flex = 1.  See this example:  https://rnplay.org/apps/GWoFWg

**Comment by ms88privat** [comment]
@wootwoot1234 I had the same problem. The solution is the "renderHeader" property on the ListView (it does scroll away!)

https://rnplay.org/apps/0RMTVg

**Comment by christopherdro** [comment]
@ms88privat Is right, the correct way to achieve appending content either before or after the listview is to use either renderHeader or renderFooter.

@wootwoot1234 Hopefully this is the functionality your looking for. If it works, go ahead and close the issue.
