### ISSUE TITLE
Center an image?

### ISSUE THREAD

**Issue by pwnsdx** [facebook/react-native#384]
Hello everyone,

I'm trying to make an image centered using reactjs but it don't work.

Here is my code:

```
                <Image
                  source={{uri: 'http://facebook.github.io/react/img/logo_og.png'}}
                  style={styles.image}
                />
```

```
var styles = StyleSheet.create({
  image: {
        width: 40,
        height: 40,
        flex: 1
  }
});
```
I've tried alignItems, textAlign, justifyContent = center but it still don't want to work.

Anyone can help me please?

Thanks!

**Comment by ide** [comment]
Try this on your parent component:
```
  style={{
    justifyContent: 'center',
    alignItems: 'center',
  }}
```

No need for 'flex: 1' on the image -- that just sets its size.

**Comment by pwnsdx** [comment]
Hey @ide, thanks for helping me. I tried and unfortunately it didn't worked.

Here is the code I've done:

```
            <View style={{
                justifyContent: 'center',
                alignItems: 'center',
              }}>
                <Image
                    source={{uri: 'http://facebook.github.io/react/img/logo_og.png'}}
                    style={styles.image}>

                    <Text style={{backgroundColor: 'transparent'}}>Inside{'\n'}Test</Text>
                </Image>
            </View>
```

I have another problem, I'm also trying to get Background Image via Nesting ( https://facebook.github.io/react-native/docs/image.html#background-image-via-nesting ): it works but the text erase the image. Here is an screenshot of what is happening:
![screen shot 2015-03-28 at 08 33 37](https://cloud.githubusercontent.com/assets/2057765/6880188/76f1d842-d525-11e4-87bb-8b38486e9abd.png)

Thanks for helping :)

**Comment by pwnsdx** [comment]
Hm. Looks like I found where was the problem. I had 2 master views:
```
      <View style={styles.container}>
         <View style={styles.display}>
            <View style={{
                justifyContent: 'center',
                alignItems: 'center',
              }}>
                <Image
                    source={{uri: 'http://facebook.github.io/react/img/logo_og.png'}}
                    style={styles.image}>

                    <Text style={{backgroundColor: 'transparent'}}>Inside{'\n'}Test</Text>
                </Image>
            </View>

……
```

and the style.display didn't had "flex:1"… Without this everything inside the View looks weird, however the 2nd problem is still present, the text is still on the image.

**Comment by ide** [comment]
It's expected that the text overlays the image (I assume that's what you want because you're nesting it). I would expect the transparent background color to take effect though.

**Comment by jsierles** [comment]
Working example of both centered image and transparent text backrground here: https://rnplay.org/plays/PCqivA

**Comment by kerrison24** [comment]
m,,

**Comment by lengerrong** [comment]
I made a example
https://errong.win/react-native-center-an-image-example/
