### ISSUE TITLE
Text component will not center inside a View component

### ISSUE THREAD

**Issue by CorpusCallosum** [facebook/react-native#3841]
Hi I think should should be simple, but I cannot get it to work. Seems like no matter what I do, I cannot get the text component to center horizontally inside the view. I have tried using alignItems:center, justifyContent:center, alignSelf:center, textAlign:center, nothing works. I can get it to center vertically, but not horizontally. Whyyyyy dear lord?

    <Animated.View style={[styles.titleContainer]}>
        <Text style={styles.title}>App logo here</Text>
    </Animated.View>

How can I get the text to center both vertically and horizontally?

Here is my CSS:

    titleContainer: {
        flex: 1,
        marginTop:30,
        marginBottom:30,
        justifyContent:'center'
    },
    title:{
        color:'white',
        textAlign:'center',
        alignSelf:'center'
    },

This is my result:
![screen shot 2015-11-02 at 12 32 27 pm](https://cloud.githubusercontent.com/assets/609852/10889077/d03e14d0-815d-11e5-9c0d-5a664eac4015.png)

**Comment by whokilledtheelectricmonk** [comment]
`flex:1` the text, not the container (unless that needs to be flex'd as well)

**Comment by CorpusCallosum** [comment]
When I do that, my top and bottom margins stop working, and the text is still not centered. Here is my new css:
    titleContainer: {
        marginTop:30,
        marginBottom:30,
        backgroundColor:'rgba(255,0,0,0.1)',
        justifyContent:'center',
        alignItems:'center',
    },
    title:{
        flex: 1,    
        color:'white',
        backgroundColor:'rgba(255,0,0,0.1)',
        textAlign:'center',
        alignSelf:'center',
    },

Here is the result:
![screen shot 2015-11-02 at 12 54 32 pm](https://cloud.githubusercontent.com/assets/609852/10889594/e6b09992-8160-11e5-97ce-4275d37eae1b.png)

**Comment by whokilledtheelectricmonk** [comment]
Note that the default flex direction (`flexDirection`) in RN is `column`, not `row` like in browser flexbox. So your snippet could be as simple as: 

```
<View style={{flex: 1, alignItems: 'center'}}>
  <Text style={{fontSize: 16}}>
    App
  </Text>
</View>
```
[More about flex layout](http://moduscreate.com/aligning-children-using-flexbox-in-react-native/)

Also, for implementation-related questions like this, you may get a faster response on StackOverflow.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/text-component-will-not-center-inside-a-view-component

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
