### ISSUE TITLE
no way to change color of nontinted icons in tabbar?

### ISSUE THREAD

**Issue by kevtastic** [facebook/react-native#3842]
there doesnt seem to be any prop for it in the TabBarIOS or in TabBarIOS.Item

just to be clear im talking about the color if the icons in the tab bar while they arent selected

**Comment by mbrochh** [comment]
I'm interested in this as well. Currently they are just gray and most of the time that looks terrible, if you have a non-default tintColor for the TabBar.

**Comment by christopherdro** [comment]
@kevtastic @mbrochh 
Let's go ahead and start tracking this on #3083 since this is a duplicate issue.
