### ISSUE TITLE
UIExamples using FB CDN not showing images

### ISSUE THREAD

**Issue by jaygarcia** [facebook/react-native#3843]
Is there a plan to replace these images? I've been doing meetup demo with UI explorer and have noticed that the've been broken for at least 5 months :(

![](http://content.screencast.com/users/djliquidice/folders/Snagit/media/6e4ce88e-c2b4-406d-a363-05b657681ca6/2015-11-02_15-11-58.png)

```
var THUMB_URLS = ['https://fbcdn-dragon-a.akamaihd.net/hphotos-ak-ash3/t39.1997/p128x128/851549_767334479959628_274486868_n.png', 'https://fbcdn-dragon-a.akamaihd.net/hphotos-ak-prn1/t39.1997/p128x128/851561_767334496626293_1958532586_n.png', ...
```

**Comment by browniefed** [comment]
@facebook-github-bot close

**Comment by browniefed** [comment]
This has been fixed https://github.com/facebook/react-native/commit/6e01c514d2ca7e1ab10e94c04822c183825ba5e3
