### ISSUE TITLE
Missing babel plugins

### ISSUE THREAD

**Issue by elliotdickison** [facebook/react-native#3844]
Freshly initialized react-native projects are breaking for me. When I run `react-native init <ProjectName>`, build the project with Xcode, and run `npm run start` the simulator displays an RSoD message saying `Unknown plugin: "node-env-inline"`. I dug around a bit and discovered I was missing two babel plugins: `babel-plugin-node-env-inline` and `babel-plugin-dunderscore-dev-inline`. After installing those I can get a project running again. Should those be listed as dev dependencies somewhere? It's possible I've screwed something up locally, but this occurs for fresh projects and I'm not the only one having [this issue](http://stackoverflow.com/questions/33179018/react-native-0-1-5-transformerror-path-to-app-index-ios-js-unknown-plugin-nod).

---

node 4.1.1
npm 2.14.4
react-native 0.1.5
Xcode 7.1
OSX 10.10.5

**Comment by niftylettuce** [comment]
Same issue.

**Comment by christopherdro** [comment]
@elliotdickison @niftylettuce Any updates on this?

**Comment by christopherdro** [comment]
@facebook-github-bot no-reply
