### ISSUE TITLE
[WebSocket] On iOS, web sockets aren't being closed under the UIExplorer sample project

### ISSUE THREAD

**Issue by stephenelliott** [facebook/react-native#3846]
When running the UIExplorer sample project on iOS: in the WebSocketBase.js class, the close() function is returning immediately due to this.readyState being undefined.

As a consequence, the array of _sockets in the RCTWebSocketModule class continues to grow until all sockets are consumed on device.

Checking that this.readyState is defined before evaluating the state seems to fix the issue, though I'm not sure if that solution has other side effects.

**Comment by jherr** [comment]
This bug relates to the websocket that's opened to support the hot reload functionality in dev mode. It's not a production issue.

**Comment by stephenelliott** [comment]
I'm seeing this issue when compiled for release; I've made sure debug mode is off when profiling.

**Comment by stephenelliott** [comment]
Excellent! Thanks, Ken.

**Comment by jherr** [comment]
:+1:
