### ISSUE TITLE
WritableMap fromBundle cannot handle array

### ISSUE THREAD

**Issue by Matthew-C** [facebook/react-native#3847]
Arguments.java line 122:
value.getClass().isArray() always return false cause ArrayList is not array! 

Note bundle.putStringArray takes an ArrayList as parameter so this code never works.

Also is there a way to allow user to directly put JSONObject as initial properties?

**Comment by yychun1217** [comment]
You should convert ArrayList to Array

**Comment by christopherdro** [comment]
@Matthew-C Your going to have to convert the array to a `WritableArray`.

**Comment by christopherdro** [comment]
@facebook-github-bot answered
