### ISSUE TITLE
Content in TabBarIOS.Item overlapped by TabBar?

### ISSUE THREAD

**Issue by mbrochh** [facebook/react-native#3848]
I have combined the AwesomeProject tutorial example with the movie list with a TabBarIOS and I'm now rendering the movie list in one of the tabs. When I scroll down all the way in the ListView, I can see that the TabBar is overlapping the last item in the list.

Shouldn't the children of the TabBarIOS.Item somehow only extend to the available device-height minus the TabBar?

What is the best-practice approach to shrink down the actual view-content so that it is not overlapped by the TabBar?

**Comment by ide** [comment]
This is intended behavior on iOS 7+. You should set the bottom padding / margin / content inset yourself depending on how you want your app to look.

**Comment by mbrochh** [comment]
Alright, thank you very much for the fast reply!

**Comment by lvcmenezes** [comment]
Sorry for resurrecting this topic, but how do you guys handle the content padding/margin/content inset when the keyboard appears and you don't want any kind of space at the bottom, since the tabbar doesn't appear along with the keyboard..
