### ISSUE TITLE
Issue in exporting iOS debug build [IPA]

### ISSUE THREAD

**Issue by ravindraguptacapgemini** [facebook/react-native#38498]
### Description

We are getting build error while trying to export IPA with fabric enabled with command

`xcodebuild archive -workspace intelexMobile.xcworkspace -scheme intelexMobile -archivePath intelexMobile.xcarchive`

This command works fine on the code before migrating to new architecture, please suggest if we need to change the command.
Here is the stack-trace of the build:

CompileC /Users/****/Library/Developer/Xcode/DerivedData/intelexMobile-gtkwrtoxelwalvdqwqtdymemagxo/Build/Intermediates.noindex/ArchiveIntermediates/intelexMobile/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/React-Fabric.build/Objects-normal/arm64/States.o /Users/****/JenkinsAgentUsevol/workspace/ev2_ILX-44410-Create-debug-build/native/node_modules/react-native/ReactCommon/react/renderer/components/rncore/States.cpp normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'React-Fabric' from project 'Pods')
    cd /Users/****/JenkinsAgentUsevol/workspace/ev2_ILX-44410-Create-debug-build/native/ios/Pods
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c++ -target arm64-apple-ios12.4 -fmessage-length\=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -std\=c++1z -stdlib\=libc++ -fmodules -fmodules-cache-path\=/Users/****/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -fmodules-prune-interval\=86400 -fmodules-prune-after\=345600 -fbuild-session-file\=/Users/****/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror\=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -Os -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror\=return-type -Wdocumentation -Wunreachable-code -Werror\=deprecated-objc-isa-usage -Werror\=objc-root-class -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -pedantic -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wno-newline-eof -Wno-c++11-extensions -Wno-implicit-fallthrough -DPOD_CONFIGURATION_RELEASE\=1 -DCOCOAPODS\=1 -D_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.1.sdk -fstrict-aliasing -Wdeprecated-declarations -Winvalid-offsetof -g -Wno-sign-conversion -Winfinite-recursion -Wmove -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wrange-loop-analysis -Wno-semicolon-before-method-body -Wunguarded-availability -iquote /Users/****/Library/Developer/Xcode/DerivedData/intelexMobile-gtkwrtoxelwalvdqwqtdymemagxo/Build/Intermediates.noindex/ArchiveIntermediates/intelexMobile/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/React-Fabric.build/React-Fabric-generated-files.hmap -I/Users/****/Library/Developer/Xcode/DerivedData/intelexMobile-gtkwrtoxelwalvdqwqtdymemagxo/Build/Intermediates.noindex/ArchiveIntermediates/intelexMobile/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/React-Fabric.build/React-Fabric-own-target-headers.hmap -I/Users/****/Library/Developer/Xcode/DerivedData/intelexMobile-gtkwrtoxelwalvdqwqtdymemagxo/Build/Intermediates.noindex/ArchiveIntermediates/intelexMobile/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/React-Fabric.build/React-Fabric-all-non-framework-target-headers.hmap -ivfsoverlay /Users/****/Library/Developer/Xcode/DerivedData/intelexMobile-gtkwrtoxelwalvdqwqtdymemagxo/Build/Intermediates.noindex/ArchiveIntermediates/intelexMobile/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/React-Fabric.build/all-product-headers.yaml -iquote /Users/****/Library/Developer/Xcode/DerivedData/intelexMobile-gtkwrtoxelwalvdqwqtdymemagxo/Build/Intermediates.noindex/ArchiveIntermediates/intelexMobile/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/React-Fabric.build/React-Fabric-project-headers.hmap -I/Users/****/Library/Developer/Xcode/DerivedData/intelexMobile-gtkwrtoxelwalvdqwqtdymemagxo/Build/Intermediates.noindex/ArchiveIntermediates/intelexMobile/BuildProductsPath/Release-iphoneos/React-Fabric/include -I/Users/****/JenkinsAgentUsevol/workspace/ev2_ILX-44410-Create-debug-build/native/ios/Pods/Headers/Private -I/Users/****/JenkinsAgentUsevol/workspace/ev2_ILX-44410-Create-debug-build/native/ios/Pods/Headers/Private/React-Fabric -I/Users/****/JenkinsAgentUsevol/workspace/ev2_ILX-44410-Create-debug-build/native/ios/Pods/Headers/Public -I/Users/****/JenkinsAgentUsevol/workspace/ev2_ILX-44410-Create-debug-build/native/ios/Pods/Headers/Public/DoubleConversion -I/Users/****/JenkinsAgentUsevol/workspace/ev2_ILX-44410-Create-debug-build/native/ios/Pods/Headers/Public/FBLazyVector -I/Users/****/JenkinsAgentUsevol/workspace/ev2_ILX-44410-Create-debug-build/native/ios/Pods/Headers/Public/RCT-Folly -I/Users/****/JenkinsAgentUsevol/workspace/ev2_ILX-44410-Create-debug-build/native/ios/Pods/Headers/Public/RCTRequired -I/Users/****/JenkinsAgentUsevol/workspace/ev2_ILX-44410-Create-debug-build/native/ios/Pods/Headers/Public/RCTTypeSafety -I/Users/****/JenkinsAgentUsevol/workspace/ev2_ILX-44410-Create-debug-build/native/ios/Pods/Headers/Public/React-Core -I/Users/****/JenkinsAgentUsevol/workspace/ev2_ILX-44410-Create-debug-build/native/ios/Pods/Headers/Public/React-Fabric -I/Users/****/JenkinsAgentUsevol/workspace/ev2_ILX-44410-Create-debug-build/native/ios/Pods/Headers/Public/React-callinvoker -I/Users/****/JenkinsAgentUsevol/workspace/ev2_ILX-44410-Create-debug-build/native/ios/Pods/Headers/Public/React-cxxreact -I/Users/****/JenkinsAgentUsevol/workspace/ev2_ILX-44410-Create-debug-build/native/ios/Pods/Headers/Public/React-debug -I/Users/****/JenkinsAgentUsevol/workspace/ev2_ILX-44410-Create-debug-build/native/ios/Pods/Headers/Public/React-graphics -I/Users/****/JenkinsAgentUsevol/workspace/ev2_ILX-44410-Create-debug-build/native/ios/Pods/Headers/Public/React-jsc -I/Users/****/JenkinsAgentUsevol/workspace/ev2_ILX-44410-Create-debug-build/native/ios/Pods/Headers/Public/React-jsi -I/Users/****/JenkinsAgentUsevol/workspace/ev2_ILX-44410-Create-debug-build/native/ios/Pods/Headers/Public/React-jsiexecutor -I/Users/****/JenkinsAgentUsevol/workspace/ev2_ILX-44410-Create-debug-build/native/ios/Pods/Headers/Public/React-jsinspector -I/Users/****/JenkinsAgentUsevol/workspace/ev2_ILX-44410-Create-debug-build/native/ios/Pods/Headers/Public/React-logger -I/Users/****/JenkinsAgentUsevol/workspace/ev2_ILX-44410-Create-debug-build/native/ios/Pods/Headers/Public/React-perflogger -I/Users/****/JenkinsAgentUsevol/workspace/ev2_ILX-44410-Create-debug-build/native/ios/Pods/Headers/Public/React-runtimeexecutor -I/Users/****/JenkinsAgentUsevol/workspace/ev2_ILX-44410-Create-debug-build/native/ios/Pods/Headers/Public/React-runtimescheduler -I/Users/****/JenkinsAgentUsevol/workspace/ev2_ILX-44410-Create-debug-build/native/ios/Pods/Headers/Public/React-utils -I/Users/****/JenkinsAgentUsevol/workspace/ev2_ILX-44410-Create-debug-build/native/ios/Pods/Headers/Public/ReactCommon -I/Users/****/JenkinsAgentUsevol/workspace/ev2_ILX-44410-Create-debug-build/native/ios/Pods/Headers/Public/SocketRocket -I/Users/****/JenkinsAgentUsevol/workspace/ev2_ILX-44410-Create-debug-build/native/ios/Pods/Headers/Public/Yoga -I/Users/****/JenkinsAgentUsevol/workspace/ev2_ILX-44410-Create-debug-build/native/ios/Pods/Headers/Public/fmt -I/Users/****/JenkinsAgentUsevol/workspace/ev2_ILX-44410-Create-debug-build/native/ios/Pods/Headers/Public/glog -I/Users/****/JenkinsAgentUsevol/workspace/ev2_ILX-44410-Create-debug-build/native/ios/Pods/Headers/Private/React-Core -I/Users/****/JenkinsAgentUsevol/workspace/ev2_ILX-44410-Create-debug-build/native/ios/Pods/boost -I/Users/****/JenkinsAgentUsevol/workspace/ev2_ILX-44410-Create-debug-build/native/node_modules/react-native/ReactCommon/ReactCommon -I/Users/****/JenkinsAgentUsevol/workspace/ev2_ILX-44410-Create-debug-build/native/ios/Pods/RCT-Folly -I/Users/****/Library/Developer/Xcode/DerivedData/intelexMobile-gtkwrtoxelwalvdqwqtdymemagxo/Build/Intermediates.noindex/ArchiveIntermediates/intelexMobile/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/React-Fabric.build/DerivedSources-normal/arm64 -I/Users/****/Library/Developer/Xcode/DerivedData/intelexMobile-gtkwrtoxelwalvdqwqtdymemagxo/Build/Intermediates.noindex/ArchiveIntermediates/intelexMobile/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/React-Fabric.build/DerivedSources/arm64 -I/Users/****/Library/Developer/Xcode/DerivedData/intelexMobile-gtkwrtoxelwalvdqwqtdymemagxo/Build/Intermediates.noindex/ArchiveIntermediates/intelexMobile/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/React-Fabric.build/DerivedSources -F/Users/****/Library/Developer/Xcode/DerivedData/intelexMobile-gtkwrtoxelwalvdqwqtdymemagxo/Build/Intermediates.noindex/ArchiveIntermediates/intelexMobile/BuildProductsPath/Release-iphoneos/React-Fabric -DRN_FABRIC_ENABLED -fmodule-map-file\=/Users/****/JenkinsAgentUsevol/workspace/ev2_ILX-44410-Create-debug-build/native/ios/Pods/Headers/Public/RCTTypeSafety/RCTTypeSafety.modulemap -fmodule-map-file\=/Users/****/JenkinsAgentUsevol/workspace/ev2_ILX-44410-Create-debug-build/native/ios/Pods/Headers/Public/React/React-Core.modulemap -fmodule-map-file\=/Users/****/JenkinsAgentUsevol/workspace/ev2_ILX-44410-Create-debug-build/native/ios/Pods/Headers/Public/ReactCommon/ReactCommon.modulemap -fmodule-map-file\=/Users/****/JenkinsAgentUsevol/workspace/ev2_ILX-44410-Create-debug-build/native/ios/Pods/Headers/Public/folly/RCT-Folly.modulemap -fmodule-map-file\=/Users/****/JenkinsAgentUsevol/workspace/ev2_ILX-44410-Create-debug-build/native/ios/Pods/Headers/Public/yoga/Yoga.modulemap -DNDEBUG -DRN_FABRIC_ENABLED -DNDEBUG -DFOLLY_NO_CONFIG -DFOLLY_MOBILE\=1 -DFOLLY_USE_LIBCPP\=1 -Wno-comma -Wno-shorten-64-to-32 -Wno-gnu-zero-variadic-macro-arguments -include /Users/****/JenkinsAgentUsevol/workspace/ev2_ILX-44410-Create-debug-build/native/ios/Pods/Target\ Support\ Files/React-Fabric/React-Fabric-prefix.pch -MMD -MT dependencies -MF /Users/****/Library/Developer/Xcode/DerivedData/intelexMobile-gtkwrtoxelwalvdqwqtdymemagxo/Build/Intermediates.noindex/ArchiveIntermediates/intelexMobile/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/React-Fabric.build/Objects-normal/arm64/States.d --serialize-diagnostics /Users/****/Library/Developer/Xcode/DerivedData/intelexMobile-gtkwrtoxelwalvdqwqtdymemagxo/Build/Intermediates.noindex/ArchiveIntermediates/intelexMobile/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/React-Fabric.build/Objects-normal/arm64/States.dia -c /Users/****/JenkinsAgentUsevol/workspace/ev2_ILX-44410-Create-debug-build/native/node_modules/react-native/ReactCommon/react/renderer/components/rncore/States.cpp -o /Users/****/Library/Developer/Xcode/DerivedData/intelexMobile-gtkwrtoxelwalvdqwqtdymemagxo/Build/Intermediates.noindex/ArchiveIntermediates/intelexMobile/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/React-Fabric.build/Objects-normal/arm64/States.o
error: Build input file cannot be found: '/Users/****/JenkinsAgentUsevol/workspace/ev2_ILX-44410-Create-debug-build/native/node_modules/react-native/ReactCommon/react/renderer/components/rncore/States.cpp'. Did you forget to declare this file as an output of a script phase or custom build rule which produces it? (in target 'React-Fabric' from project 'Pods')

warning: Run script build phase 'Start Packager' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'intelexMobile' from project 'intelexMobile')
warning: Run script build phase 'Bundle React Native code and images' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'intelexMobile' from project 'intelexMobile')
warning: Run script build phase '[CP-User] [RNFB] Core Configuration' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'intelexMobile' from project 'intelexMobile')
** ARCHIVE FAILED **

The following build commands failed:
	CompileC /Users/****/Library/Developer/Xcode/DerivedData/intelexMobile-gtkwrtoxelwalvdqwqtdymemagxo/Build/Intermediates.noindex/ArchiveIntermediates/intelexMobile/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/React-Fabric.build/Objects-normal/arm64/States.o /Users/****/JenkinsAgentUsevol/workspace/ev2_ILX-44410-Create-debug-build/native/node_modules/react-native/ReactCommon/react/renderer/components/rncore/States.cpp normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'React-Fabric' from project 'Pods')
(1 failure)
rake aborted!
FAILED TO EXECUTE COMMAND => xcodebuild archive -workspace intelexMobile.xcworkspace -scheme intelexMobile -archivePath intelexMobile.xcarchive

### React Native Version

0.72.3

### Output of `npx react-native info`

System:
  OS: macOS 13.4
  CPU: (12) arm64 Apple M2 Pro
  Memory: 2.93 GB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 16.20.0
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 8.19.4
    path: /usr/local/bin/npm
  Watchman:
    version: 2023.06.26.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /Users/ravindragupta/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.2 AI-222.4459.24.2221.10121639
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.19
    path: /usr/bin/javac
  Ruby:
    version: 3.0.4
    path: /Users/ravindragupta/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: ^18.2.0
  react-native:
    installed: 0.72.3
    wanted: 0.72.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: false
  newArchEnabled: true
iOS:
  hermesEnabled: false
  newArchEnabled: true

### Steps to reproduce

Try to create IPA with command:

xcodebuild archive -workspace AwesomeProject.xcworkspace -scheme AwesomeProject -archivePath AwesomeProject.xcarchive

### Snack, code example, screenshot, or link to a repository

https://github.com/ravindraguptacapgemini/AwesomeProject_Latest

**Comment by ravindraguptacapgemini** [comment]
reproducer can't replicate the scenario

**Comment by ravindraguptacapgemini** [comment]
@cortinico created a reproducer [here](https://github.com/ravindraguptacapgemini/AwesomeProject_Latest).

Steps to reproduce the issue:
1. Setup provisioning and certificates
2. try to archive the project with command
xcodebuild archive -workspace AwesomeProject_Latest.xcworkspace -scheme AwesomeProject_Latest -archivePath AwesomeProject_Latest.xcarchive -destination 'generic/platform=iOS'

You will get the error like:

Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_FKUserDefaultsPlugin", referenced from:
      objc-class-ref in libReact-RCTAppDelegate.a(RCTAppSetupUtils.o)
  "_OBJC_CLASS_$_FlipperClient", referenced from:
      objc-class-ref in libReact-RCTAppDelegate.a(RCTAppSetupUtils.o)
  "_OBJC_CLASS_$_FlipperKitLayoutPlugin", referenced from:
      objc-class-ref in libReact-RCTAppDelegate.a(RCTAppSetupUtils.o)
  "_OBJC_CLASS_$_FlipperKitNetworkPlugin", referenced from:
      objc-class-ref in libReact-RCTAppDelegate.a(RCTAppSetupUtils.o)
  "_OBJC_CLASS_$_FlipperKitReactPlugin", referenced from:
      objc-class-ref in libReact-RCTAppDelegate.a(RCTAppSetupUtils.o)
  "_OBJC_CLASS_$_SKDescriptorMapper", referenced from:
      objc-class-ref in libReact-RCTAppDelegate.a(RCTAppSetupUtils.o)
  "_OBJC_CLASS_$_SKIOSNetworkAdapter", referenced from:
      objc-class-ref in libReact-RCTAppDelegate.a(RCTAppSetupUtils.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by cipolleschi** [comment]
Hi, sorry to be late here. To archive an app with React Native < 0.73 you have to reinstall pods with:
```
# Old Architecture
NO_FLIPPER=1 PRODUCTION=1 bundle exec pod install

# New Architecture
NO_FLIPPER=1 PRODUCTION=1 RCT_NEW_ARCH_ENABLED=1 bundle exec pod install
```

That's because Flipper is not compatible with the Release configuration, unfortunately.

**Comment by ravindraguptacapgemini** [comment]
@cortinico Thanks for the update. 

Is there any change for android build because currently I had to use `./gradlew bundleRelease` before `./gradlew assembleRelease` command to make android production build.
