### ISSUE TITLE
textTransform uppercase does not work on Android

### ISSUE THREAD

**Issue by Arron-Gill** [facebook/react-native#38499]
### Description

When passing in a style to the Text component with TextStyle.textTransform set to "uppercase" it works on iOS but not Android. This is specific to when new architecture is enabled. 

### React Native Version

0.72.0

### Output of `npx react-native info`

System:
  OS: macOS 13.4.1
  CPU: (10) arm64 Apple M1 Max
  Memory: 345.33 MB / 64.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 16.14.2
    path: ~/.nvm/versions/node/v16.13.0/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 8.1.0
    path: ~/.nvm/versions/node/v16.13.0/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.12.1
    path: /Users/arron.gill/.asdf/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK:
    API Levels:
      - "27"
      - "28"
      - "31"
      - "32"
      - "33"
    Build Tools:
      - 27.0.3
      - 28.0.0
      - 28.0.3
      - 30.0.2
      - 30.0.3
      - 31.0.0
      - 32.0.0
      - 33.0.0
    System Images:
      - android-23 | Google APIs ARM 64 v8a
      - android-28 | ARM 64 v8a
      - android-28 | Intel x86 Atom_64
      - android-28 | Google ARM64-V8a Play ARM 64 v8a
      - android-29 | Google Play ARM 64 v8a
      - android-30 | Google APIs ARM 64 v8a
      - android-30 | Google Play ARM 64 v8a
      - android-30 | Google APIs ATD ARM 64 v8a
      - android-32 | Google APIs ARM 64 v8a
      - android-32 | Google Play ARM 64 v8a
      - android-33 | Google Play ARM 64 v8a
    Android NDK: 22.1.7171670
IDEs:
  Android Studio: Flamingo 2022.2.1 Patch 2 Flamingo 2022.2.1 Patch 2
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.16.1
    path: /usr/bin/javac
  Ruby:
    version: 3.0.3
    path: /Users/arron.gill/.asdf/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: true

### Steps to reproduce

Assign a style to the RN Text Component where you have property textTransform set to "uppercase". It will work on iOS Sim but not Android emulator.

### Snack, code example, screenshot, or link to a repository

` <Text style={{textTransform: 'uppercase'}}>{label}</Text>`

**Comment by AhmadAlz7** [comment]
any updates on this usse, I face the same issue using this example:
`<Text style={{ textTransform: 'uppercase' }}>any text</Text>`

"react": "18.2.0",
"react-native": "0.72.1",

**Comment by retrixe** [comment]
I'm experiencing this issue as well, this affects my screen labels in `@react-navigation/material-top-tabs` in my application when testing it with the new architecture.

**Comment by retrixe** [comment]
This bug is still applicable and isn't missing a reproducible example? It's a super simple bug to reproduce and is really annoying since it even affects react-navigation tab labels, this issue should be reopened (not sure who to ping for this)

**Comment by cortinico** [comment]
> It's a super simple bug to reproduce and is really annoying since it even affects react-navigation tab labels, this issue should be reopened (not sure who to ping for this)

As it's super simple to reproduce, please open a new issue, provide a reproducer, and we'll properly triage it 👍

**Comment by retrixe** [comment]
#39524 alright, done here

**Comment by td-tomasz-joniec** [comment]
@cortinico Is the code for android platform even implemented? I see that one exists for iOS, not the other way around.
