### ISSUE TITLE
Adding CHANGELOG

### ISSUE THREAD

**Issue by zetachang** [facebook/react-native#385]
Is it possible to maintain a CHANGELOG for each release (or just use the github's builtin feature to describe what's new in each release)?

**Comment by ide** [comment]
This would be really good for major releases that aren't drop-in upgrades for the old version. See hapi as an example of a project that does this well.

**Comment by vjeux** [comment]
Yeah, we're going to have proper api releases with documentation in the future. But, in the next few days after the announcement it's better to move fast and ship often to fix critical issues that people are facing.

**Comment by leecade** [comment]
:+1:

**Comment by jsierles** [comment]
We have changelogs now here: https://github.com/facebook/react-native/releases

**Comment by jsierles** [comment]
Better changlogs are on the way with the upcoming 2 week release process.
