### ISSUE TITLE
init project fails on Mac OS 13.4.1

### ISSUE THREAD

**Issue by saadalla** [facebook/react-native#38523]
### Description

I have been using react native for over 2 years on windows. I failed to make it work on my new Mac.
I followed the steps in https://reactnative.dev/docs/environment-setup
but have failed to make it work for 3 days now.

npx react-native@latest --verbose init AwesomeProject 

### React Native Version

0.72.3

### Output of `npx react-native info`

saadalla@Saadallas-MacBook-Pro awesomeproject % npx react-native info                                 
info Fetching system and libraries information...
warn Multiple Podfiles were found: ios/Podfile,AwesomeProject/ios/Podfile. Choosing ios/Podfile automatically. If you would like to select a different one, you can configure it via "project.ios.sourceDir". You can learn more about it here: https://github.com/react-native-community/cli/blob/master/docs/configuration.md
System:
  OS: macOS 13.4.1
  CPU: (10) arm64 Apple M2 Pro
  Memory: 390.81 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.16.1
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.19
    path: /usr/local/bin/yarn
  npm:
    version: 9.5.1
    path: /usr/local/bin/npm
  Watchman:
    version: 2023.07.10.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /Users/saadalla/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.19
    path: /usr/bin/javac
  Ruby:
    version: 2.7.5
    path: /Users/saadalla/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.3
    wanted: 0.72.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

### Steps to reproduce

npx react-native@latest --verbose init AwesomeProject 

build fails:
...
debug Replacing in /Users/saadalla/Development/AwesomeProject/AwesomeProject/_bundle/config
debug Renaming /Users/saadalla/Development/AwesomeProject/AwesomeProject/_bundle/config -> file:/Users/saadalla/Development/AwesomeProject/AwesomeProject/_bundle/config
debug Renaming /Users/saadalla/Development/AwesomeProject/AwesomeProject/_bundle -> file:/Users/saadalla/Development/AwesomeProject/AwesomeProject/.bundle
debug Replacing in /Users/saadalla/Development/AwesomeProject/AwesomeProject/__tests__/App.test.tsx
debug Replacing in /Users/saadalla/Development/AwesomeProject/AwesomeProject/__tests__/App.test.tsx
debug Replacing in /Users/saadalla/Development/AwesomeProject/AwesomeProject/README.md
debug Replacing in /Users/saadalla/Development/AwesomeProject/AwesomeProject/README.md
debug Replacing in /Users/saadalla/Development/AwesomeProject/AwesomeProject/Gemfile
debug Replacing in /Users/saadalla/Development/AwesomeProject/AwesomeProject/Gemfile
debug Replacing in /Users/saadalla/Development/AwesomeProject/AwesomeProject/App.tsx
debug Replacing in /Users/saadalla/Development/AwesomeProject/AwesomeProject/App.tsx
yarn install v1.22.19
info No lockfile found.
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
warning react-native > @react-native-community/cli > @react-native-community/cli-plugin-metro > metro > metro-minify-uglify > uglify-es@3.3.9: support for ECMAScript is superseded by `uglify-js` as of v3.13.0
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
[5/5] 🔨  Building fresh packages...
success Saved lockfile.
✨  Done in 34.00s.
error Framework build type is static library
[Codegen] Generating ./build/generated/ios/React-Codegen.podspec.json
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
[Codegen] Found FBReactNativeSpec
Fetching podspec for `RCT-Folly` from `../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec`
[Codegen] Found rncore
Fetching podspec for `boost` from `../node_modules/react-native/third-party-podspecs/boost.podspec`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
Fetching podspec for `hermes-engine` from `../node_modules/react-native/sdks/hermes-engine/hermes-engine.podspec`
[Hermes] Using the release tarball from Maven Central
[!] CDN: trunk Repo update failed - 2 error(s):
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/0/9/9/libevent/2.1.11/libevent.podspec.json Response: SSL connect error
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/0/9/9/libevent/2.1.12/libevent.podspec.json Response: SSL connect error
error Looks like your iOS environment is not properly set. Please go to https://reactnative.dev/docs/environment-setup?os=macos&platform=android and follow the React Native CLI QuickStart guide for macOS and iOS.

### Snack, code example, screenshot, or link to a repository

No code created, just using standard template from init

**Comment by cortinico** [comment]
```
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/0/9/9/libevent/2.1.11/libevent.podspec.json Response: SSL connect error
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/0/9/9/libevent/2.1.12/libevent.podspec.json Response: SSL connect error
```

That's a network error on your end. If you click on those links in your browser they will also fail to load.
You most likely have a problem with your local setup (like wrong time) or similar.

Also please seek further support for this kind of problems on StackOverflow: 
https://stackoverflow.com/questions/tagged/react-native

**Comment by saadalla** [comment]
Thank you the feedback.
It seems this server [cdn.jsdelivr.net] is blocking access from my country.

are the required cocoa pods files required by react-native available on another server ?
How can I tell react to use this other server ?
can I escape this issue if I downgrade the react native version ?
Or may be downgrade any other tools version Xcode, Ruby, etc ?
