### ISSUE TITLE
Android gestures pop slow

### ISSUE THREAD

**Issue by niftylettuce** [facebook/react-native#3852]
E.g. you have a `navigator.pop` event with a `Navigator.SceneConfigs.FloatFromRight` scene config.  The transition from right to left is SUPER slow/laggy.

**Comment by browniefed** [comment]
This is known in React Native debug mode on Android. Animations are ridiculously slow. Put it in production mode to test out if it's actually fast.

**Comment by niftylettuce** [comment]
Ah!  Can we get this documented?

**Comment by satya164** [comment]
@niftylettuce http://facebook.github.io/react-native/docs/performance.html#slow-navigator-transitions

**Comment by brentvatne** [comment]
I think @satya164 meant http://facebook.github.io/react-native/docs/performance.html#development-mode-dev-true  :)
