### ISSUE TITLE
java.lang.IndexOutOfBoundsException: getChildDrawingOrder() returned invalid index 1 (child count is 1)

### ISSUE THREAD

**Issue by ldevLucasl** [facebook/react-native#38534]
### New Version

0.72.3

### Old Version

0.72.0

### Build Target(s)

Android 11.0

### Output of `react-native info`

(node:24279) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
System:
  OS: macOS 13.4.1
  CPU: (8) arm64 Apple M1 Pro
  Memory: 91.31 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 16.19.0
    path: ~/.nvm/versions/node/v16.19.0/bin/node
  Yarn:
    version: 1.22.19
    path: ~/.nvm/versions/node/v16.19.0/bin/yarn
  npm:
    version: 8.19.3
    path: ~/.nvm/versions/node/v16.19.0/bin/npm
  Watchman:
    version: 2023.01.23.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods: Not Found
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.1 AI-221.6008.13.2211.9477386
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 1.8.0_292
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.3
    wanted: ^0.72.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

### Issue and Reproduction Steps

I have a FlatList that is populated by a data that is a useState, and when the component mounts I fetch the data in my API using a useEffect, when the data changes from a filter and I need to call my useEffect again, I end up taking this `java.lang.IndexOutOfBoundsException: getChildDrawingOrder() returned invalid index 1 (child count is 1)` crash.

I tried several solutions but without success, until I finally tried to change the FlatList import from `react-native` to `gesture-handler` and vuala, it worked.

im using `expo@^49.0.3` e `react-native@0.72.3` and `Android 11.0` simulator,  this error only occurs on android, on iOS with FlatList from RN everything works normal.

**Comment by cortinico** [comment]
> im using expo@^49.0.3 e react-native@0.72.3 and Android 11.0 simulator, this error only occurs on android, on iOS with FlatList from RN everything works normal.

Hi @ldevLucasl 
Thanks for reporting this issue.

It seems like this issue is actually unrelated to React Native core but related to Expo. Please open this issue here:

https://github.com/expo/expo/issues

I'll be closing this but feel free to reopen if the other repo points back to us as a issue in the core of React Native.

**Comment by sn4f** [comment]
I have the same issue after upgrading to 0.72.3 and I'm not using expo.
