### ISSUE TITLE
Buildphase error after installing facebook/idb and pyenv (python 3.6.15) for Flipper debugger

### ISSUE THREAD

**Issue by JinxMan25** [facebook/react-native#38555]
### Description

CommandError: Failed to build iOS project. "xcodebuild" exited with error code 65.
To view more error logs, try building the app with Xcode directly, by opening /Users/testuser/testapp/ios_app/ios/iosapp.xcworkspace.

Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -workspace /Users/testuser/testapp/ios_app/ios/iosapp.xcworkspace -configuration Debug -scheme iosapp -destination id=913DB190-280F-49C9-A48A-50B37F82802B

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES

Prepare packages

Computing target dependency graph and provisioning inputs

Create build description
Build description signature: d489800058fe84a78be26e239e86d8cd
Build description path: /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Intermediates.noindex/XCBuildData/d489800058fe84a78be26e239e86d8cd.xcbuilddata

note: Building targets in dependency order
ClangStatCache /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang-stat-cache /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.4.sdk /Users/testuser/Library/Developer/Xcode/DerivedData/SDKStatCaches.noindex/iphonesimulator16.4-20E238-.sdkstatcache
    cd /Users/testuser/testapp/ios_app/ios
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang-stat-cache /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.4.sdk -o /Users/testuser/Library/Developer/Xcode/DerivedData/SDKStatCaches.noindex/iphonesimulator16.4-20E238-.sdkstatcache

CreateBuildDirectory /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Products
    cd /Users/testuser/testapp/ios_app/ios
    builtin-create-build-directory /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Products

CreateBuildDirectory /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Intermediates.noindex
    cd /Users/testuser/testapp/ios_app/ios
    builtin-create-build-directory /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Intermediates.noindex

CreateBuildDirectory /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Products/Debug-iphonesimulator
    cd /Users/testuser/testapp/ios_app/ios
    builtin-create-build-directory /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Products/Debug-iphonesimulator

CreateBuildDirectory /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Intermediates.noindex/EagerLinkingTBDs/Debug-iphonesimulator
    cd /Users/testuser/testapp/ios_app/ios
    builtin-create-build-directory /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Intermediates.noindex/EagerLinkingTBDs/Debug-iphonesimulator

CreateBuildDirectory /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Products/Debug-iphonesimulator/react-native-slider
    cd /Users/testuser/testapp/ios_app/ios
    builtin-create-build-directory /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Products/Debug-iphonesimulator/react-native-slider

CreateBuildDirectory /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Products/Debug-iphonesimulator/react-native-skia
    cd /Users/testuser/testapp/ios_app/ios
    builtin-create-build-directory /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Products/Debug-iphonesimulator/react-native-skia

CreateBuildDirectory /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Products/Debug-iphonesimulator/react-native-safe-area-context
    cd /Users/testuser/testapp/ios_app/ios
    builtin-create-build-directory /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Products/Debug-iphonesimulator/react-native-safe-area-context

CreateBuildDirectory /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Products/Debug-iphonesimulator/react-native-ble-manager
    cd /Users/testuser/testapp/ios_app/ios
    builtin-create-build-directory /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Products/Debug-iphonesimulator/react-native-ble-manager

CreateBuildDirectory /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Products/Debug-iphonesimulator/react-native-ble-plx
    cd /Users/testuser/testapp/ios_app/ios
    builtin-create-build-directory /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Products/Debug-iphonesimulator/react-native-ble-plx

CreateBuildDirectory /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Products/Debug-iphonesimulator/react-native-background-timer
    cd /Users/testuser/testapp/ios_app/ios
    builtin-create-build-directory /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Products/Debug-iphonesimulator/react-native-background-timer

CreateBuildDirectory /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Products/Debug-iphonesimulator/fmt
    cd /Users/testuser/testapp/ios_app/ios
    builtin-create-build-directory /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Products/Debug-iphonesimulator/fmt

CreateBuildDirectory /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Products/Debug-iphonesimulator/glog
    cd /Users/testuser/testapp/ios_app/ios
    builtin-create-build-directory /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Products/Debug-iphonesimulator/glog

CreateBuildDirectory /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Products/Debug-iphonesimulator/boost
    cd /Users/testuser/testapp/ios_app/ios
    builtin-create-build-directory /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Products/Debug-iphonesimulator/boost

CreateBuildDirectory /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Products/Debug-iphonesimulator/Yoga
    cd /Users/testuser/testapp/ios_app/ios
    builtin-create-build-directory /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Products/Debug-iphonesimulator/Yoga

CreateBuildDirectory /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Products/Debug-iphonesimulator/SocketRocket
    cd /Users/testuser/testapp/ios_app/ios
    builtin-create-build-directory /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Products/Debug-iphonesimulator/SocketRocket

CreateBuildDirectory /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Products/Debug-iphonesimulator/ReactCommon
    cd /Users/testuser/testapp/ios_app/ios
    builtin-create-build-directory /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Products/Debug-iphonesimulator/ReactCommon

CreateBuildDirectory /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Products/Debug-iphonesimulator/React-utils
    cd /Users/testuser/testapp/ios_app/ios
    builtin-create-build-directory /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Products/Debug-iphonesimulator/React-utils

CreateBuildDirectory /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Products/Debug-iphonesimulator/React-runtimescheduler
    cd /Users/testuser/testapp/ios_app/ios
    builtin-create-build-directory /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Products/Debug-iphonesimulator/React-runtimescheduler

CreateBuildDirectory /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Products/Debug-iphonesimulator/React-runtimeexecutor
    cd /Users/testuser/testapp/ios_app/ios
    builtin-create-build-directory /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Products/Debug-iphonesimulator/React-runtimeexecutor

CreateBuildDirectory /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Products/Debug-iphonesimulator/React-rncore
    cd /Users/testuser/testapp/ios_app/ios
    builtin-create-build-directory /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Products/Debug-iphonesimulator/React-rncore

CreateBuildDirectory /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Products/Debug-iphonesimulator/React-perflogger
    cd /Users/testuser/testapp/ios_app/ios
    builtin-create-build-directory /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Products/Debug-iphonesimulator/React-perflogger

CreateBuildDirectory /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Products/Debug-iphonesimulator/React-logger
    cd /Users/testuser/testapp/ios_app/ios
    builtin-create-build-directory /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Products/Debug-iphonesimulator/React-logger

CreateBuildDirectory /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Products/Debug-iphonesimulator/React-jsinspector
    cd /Users/testuser/testapp/ios_app/ios
    builtin-create-build-directory /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Products/Debug-iphonesimulator/React-jsinspector

CreateBuildDirectory /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Products/Debug-iphonesimulator/React-jsiexecutor
    cd /Users/testuser/testapp/ios_app/ios
    builtin-create-build-directory /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Products/Debug-iphonesimulator/React-jsiexecutor

CreateBuildDirectory /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Products/Debug-iphonesimulator/React-jsi
    cd /Users/testuser/testapp/ios_app/ios
    builtin-create-build-directory /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Products/Debug-iphonesimulator/React-jsi

CreateBuildDirectory /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Products/Debug-iphonesimulator/React-jsc
    cd /Users/testuser/testapp/ios_app/ios
    builtin-create-build-directory /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Products/Debug-iphonesimulator/React-jsc

CreateBuildDirectory /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Products/Debug-iphonesimulator/React-debug
    cd /Users/testuser/testapp/ios_app/ios
    builtin-create-build-directory /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Products/Debug-iphonesimulator/React-debug

CreateBuildDirectory /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Products/Debug-iphonesimulator/React-cxxreact
    cd /Users/testuser/testapp/ios_app/ios
    builtin-create-build-directory /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Products/Debug-iphonesimulator/React-cxxreact

CreateBuildDirectory /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Products/Debug-iphonesimulator/React-callinvoker
    cd /Users/testuser/testapp/ios_app/ios
    builtin-create-build-directory /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Products/Debug-iphonesimulator/React-callinvoker

CreateBuildDirectory /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Products/Debug-iphonesimulator/React-RCTVibration
    cd /Users/testuser/testapp/ios_app/ios
    builtin-create-build-directory /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Products/Debug-iphonesimulator/React-RCTVibration

CreateBuildDirectory /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Products/Debug-iphonesimulator/React-RCTText
    cd /Users/testuser/testapp/ios_app/ios
    builtin-create-build-directory /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Products/Debug-iphonesimulator/React-RCTText

CreateBuildDirectory /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Products/Debug-iphonesimulator/React-RCTSettings
    cd /Users/testuser/testapp/ios_app/ios
    builtin-create-build-directory /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Products/Debug-iphonesimulator/React-RCTSettings

CreateBuildDirectory /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Products/Debug-iphonesimulator/React-RCTNetwork
    cd /Users/testuser/testapp/ios_app/ios
    builtin-create-build-directory /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Products/Debug-iphonesimulator/React-RCTNetwork

CreateBuildDirectory /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Products/Debug-iphonesimulator/React-RCTLinking
    cd /Users/testuser/testapp/ios_app/ios
    builtin-create-build-directory /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Products/Debug-iphonesimulator/React-RCTLinking

CreateBuildDirectory /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Products/Debug-iphonesimulator/React-RCTImage
    cd /Users/testuser/testapp/ios_app/ios
    builtin-create-build-directory /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Products/Debug-iphonesimulator/React-RCTImage

PhaseScriptExecution [CP-User]\ Generate\ Specs /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-rncore.build/Script-46EB2E00017EB0.sh (in target 'React-rncore' from project 'Pods')
    cd /Users/testuser/testapp/ios_app/ios/Pods
    export ACTION\=build
    export AD_HOC_CODE_SIGNING_ALLOWED\=YES
    export ALLOW_TARGET_PLATFORM_SPECIALIZATION\=NO
    export ALTERNATE_GROUP\=staff
    export ALTERNATE_MODE\=u+w,go-w,a+rX
    export ALTERNATE_OWNER\=testuser
    export ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES\=NO
    export ALWAYS_SEARCH_USER_PATHS\=NO
    export ALWAYS_USE_SEPARATE_HEADERMAPS\=NO
    export APPLE_INTERNAL_DEVELOPER_DIR\=/AppleInternal/Developer
    export APPLE_INTERNAL_DIR\=/AppleInternal
    export APPLE_INTERNAL_DOCUMENTATION_DIR\=/AppleInternal/Documentation
    export APPLE_INTERNAL_LIBRARY_DIR\=/AppleInternal/Library

ProcessProductPackaging "" /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Intermediates.noindex/iosapp.build/Debug-iphonesimulator/WorkoutStatusExtension.build/WorkoutStatusExtension.appex.xcent (in target 'WorkoutStatusExtension' from project 'iosapp')
    cd /Users/testuser/testapp/ios_app/ios
    
    Entitlements:
    
    {
    "com.apple.security.get-task-allow" = 1;
}
    
    builtin-productPackagingUtility -entitlements -format xml -o /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Intermediates.noindex/iosapp.build/Debug-iphonesimulator/WorkoutStatusExtension.build/WorkoutStatusExtension.appex.xcent

ProcessProductPackaging "" /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Intermediates.noindex/iosapp.build/Debug-iphonesimulator/WorkoutStatusExtension.build/WorkoutStatusExtension.appex-Simulated.xcent (in target 'WorkoutStatusExtension' from project 'iosapp')
    cd /Users/testuser/testapp/ios_app/ios
    
    Entitlements:
    
    {
    "application-identifier" = "476R87526Y.io.expo.client.ios.WorkoutStatus";
}
    
    builtin-productPackagingUtility -entitlements -format xml -o /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Intermediates.noindex/iosapp.build/Debug-iphonesimulator/WorkoutStatusExtension.build/WorkoutStatusExtension.appex-Simulated.xcent

WriteAuxiliaryFile /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/SocketRocket.build/all-product-headers.yaml (in target 'SocketRocket' from project 'Pods')
    cd /Users/testuser/testapp/ios_app/ios/Pods
    write-file /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/SocketRocket.build/all-product-headers.yaml

WriteAuxiliaryFile /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/SocketRocket.build/SocketRocket.hmap (in target 'SocketRocket' from project 'Pods')
    cd /Users/testuser/testapp/ios_app/ios/Pods
    write-file /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/SocketRocket.build/SocketRocket.hmap

2023-07-21 12:44:43.053 xcodebuild[27750:454453] DVTCoreDeviceEnabledState: DVTCoreDeviceEnabledState_Disabled set via user default (DVTEnableCoreDevice=disabled)
** BUILD FAILED **

The following build commands failed:
	PhaseScriptExecution [CP-User]\ Generate\ Specs /Users/testuser/Library/Developer/Xcode/DerivedData/iosapp-bvhreowvaeayafcgvfxrlielkgtl/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-rncore.build/Script-46EB2E00017EB0.sh (in target 'React-rncore' from project 'Pods')
(1 failure)
Build logs written to /Users/testuser/testapp/ios_app/.expo/xcodebuild.log

### React Native Version

0.72.1

### Output of `npx react-native info`

System:
  OS: macOS 13.4.1
  CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Memory: 81.64 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.4.0
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.19
    path: /usr/local/bin/yarn
  npm:
    version: 9.7.2
    path: /usr/local/bin/npm
  Watchman:
    version: 2023.07.10.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java: Not Found
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.1
    wanted: 0.72.1
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: false
  newArchEnabled: false
iOS:
  hermesEnabled: false
  newArchEnabled: false

### Steps to reproduce

1. Install Flipper
2. Flipper dependencies like facebook/idb (go to github.com/facebook/idb to install two packages for idb)
3. One idb dependency is python 3.6.15 so I used pyenv to install that. previously python did not exist on my $PATH

### Snack, screenshot, or link to a repository

I started getting this obscure buildphase error ever since I installed the Flipper debugger dependencies. 

I reverted everything. Uninstalled all the deps for the Flipper that I assume caused this. I don't think I did anything before that would cause this error. I cleaned the build folder on Xcode, cleaned and purged everything I could for the react native app, deleted Podfile.lock, deleted node_modules folder, Pod folder. Installed Xcode 15 beta 4. Still getting the same error. I git stashed to make sure there wasn't a build setting that caused this but I'm still getting this error. 

Any ideas?

**Comment by cortinico** [comment]
> I started getting this obscure buildphase error ever since I installed the Flipper debugger dependencies.

Please report this issue on facebook/flipper as we don't offer direct Flipper support here.
