### ISSUE TITLE
Debugger Unavailable

### ISSUE THREAD

**Issue by luvnishCapgemini** [facebook/react-native#38550]
### Description

When I open developer menu, it is saying **Debugger Unavailable** and on tap it is showing alert box with **Debugging with Chrome is not supported when TurboModules are enabled.** 
Here are the screenshots:

![Simulator Screenshot - iPhone 14 Pro - 2023-07-21 at 18 35 57](https://github.com/facebook/react-native/assets/132471357/63e4641b-cec1-431a-aeca-b17416dc023c)
![Simulator Screenshot - iPhone 14 Pro - 2023-07-21 at 18 35 49](https://github.com/facebook/react-native/assets/132471357/1b4e6781-d125-4c9c-889f-ca666091ba5a)

### React Native Version

0.72.1

### Output of `npx react-native info`

Output is attached in both screenshots.

### Steps to reproduce

Using: 
fabric_enabled=> true 
hermes_enabled => false

Steps:
1. Launch app
2. Open Developer Menu

### Snack, code example, screenshot, or link to a repository

Screenshot is attached in description.

**Comment by luvnishCapgemini** [comment]
Hi,
I am not able to debug application. Please provide a solution for this.

**Comment by ravindraguptacapgemini** [comment]
@cortinico Is there any alternative to debug the application with new architecture (Turbo Modules) enabled? 
CC: @cipolleschi

**Comment by cortinico** [comment]
> I am not able to debug application. Please provide a solution for this.

Hi @ravindraguptacapgemini @luvnishCapgemini 
The New Architecture is still **experimental** as written in several pages on the reactnative.dev website.
We're working towards offering the same developer experience as Old Architecture to the New Architecture and updates on this front will come in 0.73 and 0.74

**Comment by luvnishCapgemini** [comment]
Thanks @cortinico for the update.
