### ISSUE TITLE
Clean Build Archive issue in Xcode Cloud

### ISSUE THREAD

**Issue by rnkdsh** [facebook/react-native#38560]
### Description

I have setup Xcode Cloud workflow to distribute artifact in Internal Testing and External Testing in iOS.
Internal Testing workflow works perfectly and the build is uploaded and distributed.
But, External Testing is not working.

### React Native Version

0.72.3

### Output of `npx react-native info`

System:
  OS: macOS 13.4.1
  CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Memory: 231.13 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.2.0
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.18
    path: ~/.yarn/bin/yarn
  npm:
    version: 9.8.1
    path: /usr/local/bin/npm
  Watchman:
    version: 2023.05.22.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK:
    Android NDK: 23.0.7344513-beta4
IDEs:
  Android Studio: 2022.2 AI-222.4459.24.2221.10121639
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 12.0.2
    path: /usr/bin/javac
  Ruby:
    version: 3.2.2
    path: /usr/local/opt/ruby/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.3
    wanted: 0.72.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

### Steps to reproduce

Setup Xcode Cloud for iOS build distribution to App Store.

### Snack, screenshot, or link to a repository

<img width="1116" alt="Screenshot 2023-07-23 at 7 23 50 PM" src="https://github.com/facebook/react-native/assets/16722278/91c7ab1c-1431-4af6-aec5-2db00239966d">

**Comment by cortinico** [comment]
Not enough information to debug or support you here. This feel more like a question you should ask on StackOverflow
