### ISSUE TITLE
onDetachedFromWindow is called immediately after initializing the View - android only

### ISSUE THREAD

**Issue by hoyelo** [facebook/react-native#38567]
### Description

Sample code: [https://github.com/hoyelo/rn-demo](https://github.com/hoyelo/rn-demo)

This is a React Native library created using `npx create-react-native-library@latest rn-sdk`. Inside the library, there is only a simple View created with no other functionalities. However, `onDetachedFromWindow` is called during the creation of this View, which should not happen. After all, I have a lot of destruction logic placed in this method, and if this happens, it will cause many other problems. This issue has been noticed since the commit [da5ed0d10b9813e650b342dcc63a0af4d4af9dea](https://github.com/facebook/react-native/commit/da5ed0d10b9813e650b342dcc63a0af4d4af9dea), which means it has been occurring since version `0.71.12`.

### React Native Version

0.72.3

### Output of `npx react-native info`

System:
  OS: macOS 13.1
  CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Memory: 124.12 MB / 16.00 GB
  Shell:
    version: 5.8.1
    path: /bin/zsh
Binaries:
  Node:
    version: 20.4.0
    path: ~/.nvm/versions/node/v20.4.0/bin/node
  Yarn:
    version: 1.22.19
    path: ~/.yarn/bin/yarn
  npm:
    version: 9.7.2
    path: ~/.nvm/versions/node/v20.4.0/bin/npm
  Watchman:
    version: 2023.07.10.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /Users/Victor/.rvm/gems/ruby-2.7.5/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK:
    API Levels:
      - "26"
      - "28"
      - "29"
      - "30"
      - "31"
      - "32"
      - "33"
    Build Tools:
      - 19.1.0
      - 20.0.0
      - 21.1.2
      - 22.0.1
      - 23.0.1
      - 23.0.2
      - 23.0.3
      - 24.0.0
      - 24.0.1
      - 24.0.2
      - 24.0.3
      - 25.0.0
      - 25.0.1
      - 25.0.2
      - 25.0.3
      - 26.0.0
      - 26.0.1
      - 26.0.2
      - 26.0.3
      - 27.0.0
      - 27.0.1
      - 27.0.2
      - 27.0.3
      - 28.0.0
      - 28.0.1
      - 28.0.2
      - 28.0.3
      - 29.0.0
      - 29.0.1
      - 29.0.2
      - 29.0.3
      - 30.0.0
      - 30.0.1
      - 30.0.2
      - 30.0.3
      - 31.0.0
      - 32.0.0
    System Images:
      - android-23 | Google APIs Intel x86 Atom
      - android-30 | Google APIs Intel x86 Atom
      - android-31 | Google APIs Intel x86 Atom_64
    Android NDK: Not Found
IDEs:
  Android Studio: 2022.1 AI-221.6008.13.2211.9477386
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.14
    path: /usr/bin/javac
  Ruby:
    version: 2.7.5
    path: /Users/Victor/.rvm/rubies/ruby-2.7.5/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.3
    wanted: 0.72.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

### Steps to reproduce

1. git clone git@github.com:hoyelo/rn-demo.git
2. run yarn
3. set breakpoints in both onAttachedToWindow and onDetachedFromWindow functions, and debug it on AndroidStudio

class WidgetView constructor(
  context: Context,
) : View(context) {

  init {
  }

  override fun onAttachedToWindow() {
    super.onAttachedToWindow()
  }

  override fun onDetachedFromWindow() {
    super.onDetachedFromWindow()
  }
}
4. onDetachedFromWindow is called immediately after onAttachedToWindow

### Snack, screenshot, or link to a repository

https://github.com/hoyelo/rn-demo

**Comment by wangdaliu** [comment]
+1 to this issue
