### ISSUE TITLE
Metro disconnect when the emulator network is Off

### ISSUE THREAD

**Issue by saif-o99** [facebook/react-native#38579]
### Description

Before i upgrade RN to the latest, disabling the emulator network wasn't disconnecting the metro. for example if i wanted add a listener to listen for the network status this listener will be invoked even when the network is Off. now its not doing that

when i try to refresh metro and the network is off it shows this warning:
````
warn No apps connected. Sending "reload" to all React Native apps failed. Make sure your app is running in the simulator or on a phone connected via USB.
info Reloading app...
````
and when i connect the network again and refresh metro it works again.

### React Native Version

0.72.3

### Output of `npx react-native info`

System:
  OS: Windows 10 10.0.22621
  CPU: "(12) x64 AMD Ryzen 5 5600X 6-Core Processor             "
  Memory: 2.98 GB / 15.94 GB
Binaries:
  Node:
    version: 18.12.1
    path: C:\Program Files\nodejs\node.EXE
  Yarn:
    version: 1.22.19
    path: ~\AppData\Roaming\npm\yarn.CMD
  npm:
    version: 8.19.2
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK: Not Found
IDEs:
  Android Studio: AI-212.5712.43.2112.8609683
  Visual Studio:
    - 16.11.32510.428 (Visual Studio Community 2019)
    - 17.5.33414.496 (Visual Studio Community 2022)
Languages:
  Java:
    version: 1.8.0_352
    path: C:\Program Files\Eclipse Adoptium\jdk-8.0.352.8-hotspot\bin\javac.EXE
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.3
    wanted: 0.72.3
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

### Steps to reproduce

1- run the application
2- metro works well
3- disconnect wifi & celluar data
4- now metro disconnects

### Snack, screenshot, or link to a repository

https://github.com/saif-o99/Awesome-project

**Comment by vagnerlandio** [comment]
The device is connected on Metro from USB debugging or from Wifi Debugging?

**Comment by saif-o99** [comment]
> The device is connected on Metro from USB debugging or from Wifi Debugging?

its an Android Emulator

**Comment by cortinico** [comment]
> 1- run the application
> 2- metro works well
> 3- disconnect wifi & celluar data
> 4- now metro disconnects

This is the intended behavior. The device talks to Metro via the http protocol. If network is down, the connection is lost.

**Comment by saif-o99** [comment]
@cortinico can you explain how it was working fine before the update?
before closing the issue...

**Comment by cortinico** [comment]
> it should be okay that i want to see the behaviour of my application when the network is off

You can do so by disabling wifi and mobile data, and the Metro connection won't be lost.
But if you also turn on AirPlane mode, you will lose the connection to Metro

**Comment by saif-o99** [comment]
> > it should be okay that i want to see the behaviour of my application when the network is off
> 
> You can do so by disabling wifi and mobile data, and the Metro connection won't be lost. But if you also turn on AirPlane mode, you will lose the connection to Metro

if you please look at this case i have:
i have a listener which tell me when the network is on or off to show indicator to the user.
before the update i was checking if everything is okay by disabling wifi and mobile data on the emulator and the listener will return network off
but after the update i can't do that because whenever the wifi or mobile data is off the metro disconnect and shows this warn 
````
warn No apps connected. Sending "reload" to all React Native apps failed. Make sure your app is running in the simulator or on a phone connected via USB.
info Reloading app...
````

**Comment by saif-o99** [comment]
@cortinico

**Comment by Xmaxer** [comment]
> This is the intended behavior. The device talks to Metro via the http protocol. If network is down, the connection is lost.

> You can do so by disabling wifi and mobile data, and the Metro connection won't be lost.

Seems like two contradictory statements? I don't understand why this is closed, and I see @saif-o99 opened a new issue. It's been some time, did you mange to find a fix for it?

**Comment by saif-o99** [comment]
@Xmaxer No solution/workaround for this. Look like if you want to upgrade your react native version you will lose the ability to test your app on no network, sounds like a downgrade for me not upgrade.
maybe open a new issue so they start pay attention to it idk.

**Comment by cortinico** [comment]
Hey @saif-o99 

My apologies but this statement of mine was incorrect:

> You can do so by disabling wifi and mobile data, and the Metro connection won't be lost.

Your device talks to metro via the HTTP protocol though, so you need to create a tunnel via `localhost` for it to work properly.

To do so you can run the following in a terminal:
```
adb root
adb reverse tcp:8081 tcp:8081
adb shell setprop metro.host "localhost"
```

That will make sure that your app will attempt to search for Metro in `localhost:8081` rather than `10.0.2.2` (the default). With this you can keep the connection to Metro alive, even if the internet connection (Wifi/Mobile) goes down. Hope this clarifies.
