### ISSUE TITLE
Where to change the registered project name for Android and iOS?

### ISSUE THREAD

**Issue by sulliwane** [facebook/react-native#3857]
I'd like to change below 'registered_name':
```AppRegistry.registerComponent('registered_name', () => test);```

Where should I change this name in Android and iOS files?

Thank you.

**Comment by nicklockwood** [comment]
For iOS you just need to change it in the JS file and then the `AppDelegate.m` file, file, find a line that looks like this:

    RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"registered_name"
                                            initialProperties:nil];

And change the `@"registered_name"` to whatever the new name is as well.

I'm not sure what the equivalent code is for Android though. @mkonicek?

**Comment by cosmith** [comment]
I think it's this line in `MainActivity.java`

        mReactRootView.startReactApplication(mReactInstanceManager, "registered_name", null);

**Comment by sulliwane** [comment]
Thanks a lot to both of you. It's working :)
