### ISSUE TITLE
Update to v0.14.0-RC, how to update android/iOS project files?

### ISSUE THREAD

**Issue by sulliwane** [facebook/react-native#3858]
After updating react-native package version in my **package.json** to -> **0.14.0-rc**, and running ```npm update```, I'm wondering: **How should I update the xcodeproj and Android gradle files to their latest version as well?**

* I don't think they are being updated when doing ```npm update```.
* I cannot use the global cli ```react-native init``` as it will only init 0.13.0 related xcode/android files.

Thank you.

**Comment by Bhullnatik** [comment]
http://facebook.github.io/react-native/docs/upgrading.html#content

**Comment by sulliwane** [comment]
@Bhullnatik I knew this page, but I thought that ```react-native upgrade```calls the global ```react-native-cli``` and I guess it is instead calling the local and updated **v0.14.0-rc** react-native-cli , is that correct? Anyway, I'm a bit confused on which react-native is called (global or local).

 thanks a lot! ```react-native upgrade```does work...
