### ISSUE TITLE
is it possible to run `renderToStaticMarkup` in react-native

### ISSUE THREAD

**Issue by gorangajic** [facebook/react-native#3859]
I have tried running renderToStaticMarkup in react-native but it's complaining that two versions of react are running. 

```
Invariant Violation: EventPluginRegistry: Cannot inject event plugin ordering more than once. You are likely trying to load more than one copy of React.
```

I have also tried to load local ReactDomServer from react-native module but error is the same
```
import { renderToStaticMarkup } from 'react-native/node_modules/react-tools/src/renderers/dom/ReactDOMServer'
```

Is it possible something like that in react-native, or I need to create new renderer? I just want to get jsx/xml that is passed to my Component. I will also be happy with json output, something like this

```
componentDidMount() {
   var json = renderToJson(this.props.children);
}
```

Thanks

**Comment by ide** [comment]
Rendering to markup is a feature of react-dom, not react nor react-native. What are you trying to do? If you want to render to divs and spans you should write/find a project (there are some out there) that reimplements View.js, ScrollView.js, etc and renders divs/spans.

**Comment by gorangajic** [comment]
I was able to hack quick solution https://github.com/gorangajic/react-render-to-json

**Comment by cancan101** [comment]
Now react has been de-vendored, any hope of being able to use react-dom in react-native?
```
import ReactDOMServer from 'react-dom/server';
```
still yields:
![image](https://cloud.githubusercontent.com/assets/51059/12460140/44d1a810-bf80-11e5-91e3-f69dd61b68a6.png)

**Comment by jgibbons** [comment]
@cancan101 did you have any luck since your post? I was hoping to use react-dom to render html so that it could be passed into the RN webview.

**Comment by andresn** [comment]
+1 @ide the usecase is for quick visualization and debugging output of a complex module with nested components. Btw: The quick toJson solution @gorangajic mentioned seems to no longer play nice with Babel: http://screencast.com/t/y6fAV3OIJg
