### ISSUE TITLE
🐞 iOS: Paste doesn't work properly with TextInput multiline

### ISSUE THREAD

**Issue by imransilvake** [facebook/react-native#38602]
### Description

I tried using paste on iOS with TextInput. It works fine when multiline is OFF. But it doesn't work if multiline is set to true.

### React Native Version

0.71.11

### Output of `npx react-native info`

```
System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M1
    Memory: 79.02 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.0.0 - ~/.nvm/versions/node/v18.0.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.6.0 - ~/.nvm/versions/node/v18.0.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.11 => 0.71.11 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

Use the following Input and play with the paste.
```
const [message, setMessage] = useState('');
<TextInput onChangeText={setMessage} value={message} multiline={true} />
```

### Snack, code example, screenshot, or link to a repository

Minimal reproduction case is to just use TextInput with multiline set to True
```
<TextInput onChangeText={setMessage} value={message} multiline={true} />
```

**Comment by derekchan916** [comment]
I'm having the exact issue to. It's as simple as the code provided above.

**Comment by imransilvake** [comment]
> ⚠️	Missing Reproducible Example
> ℹ️	We could not detect a reproducible example in your issue report. Please provide either:
> * If your bug is UI related: a [Snack](https://snack.expo.dev)
> * If your bug is build/update related: use our [Reproducer Template](https://github.com/react-native-community/reproducer-react-native/generate). A reproducer needs to be in a GitHub repository under your username.

The reproducible step is provided above

**Comment by cortinico** [comment]
@imransilvake please provide a repro link (not just the code)
