### ISSUE TITLE
Fetch image from android phone returning Failed to construct 'Response': The status provided (0) is outside the range [200, 599].

### ISSUE THREAD

**Issue by Punit-Vajpeyi** [facebook/react-native#38625]
### Description

While trying to read image from android phone internal storage, I am getting Failed to construct 'Response': The status provided (0) is outside the range [200, 599].

fetch(imagePath) 

sample url: file:///data/user/0/com.test_app/cache/rn_image_picker_lib_temp_5c90be23-f414-4a9f-978a-cae5239fdd25.jpg 

### React Native Version

0.72.3

### Output of `npx react-native info`

System:
  OS: macOS 13.4.1
  CPU: (8) arm64 Apple M2
  Memory: 126.95 MB / 8.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.3.0
    path: /opt/homebrew/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 9.6.7
    path: /opt/homebrew/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.12.1
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.2 AI-222.4459.24.2221.9971841
  Xcode:
    version: 14.3/14E222b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.19
    path: /opt/homebrew/opt/openjdk@11/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.3
    wanted: 0.72.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

### Steps to reproduce

        fetch('file:///data/user/0/com.test_app/cache/rn_image_picker_lib_temp_5c90be23-f414-4a9f-978a-cae5239fdd25.jpg ')
          .then(response => {
            console.log('Fetch response', response);
          })
          .catch(error => {
            console.log('fetch error', error);
          });

### Snack, screenshot, or link to a repository

![Screenshot_20230725_235947](https://github.com/facebook/react-native/assets/13044487/e1fc1b62-c799-4796-91d7-85d28f66158a)

**Comment by iBotPeaches** [comment]
@Punit-Vajpeyi - Fetch won't work against filesystem files. Thus you get a `0` because you didn't get an HTTP response back and thus failed.

> The [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) provides a JavaScript interface for accessing and manipulating parts of the [protocol](https://developer.mozilla.org/en-US/docs/Glossary/Protocol), such as requests and responses. It also provides a global [fetch()](https://developer.mozilla.org/en-US/docs/Web/API/fetch) method that provides an easy, logical way to fetch resources asynchronously across the network.
https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch

So that error looks intended and thus not a bug.

**Comment by Punit-Vajpeyi** [comment]
But it was working for working for last 2 months the same code. I was
uploading files to the server using following code snippet.

const response = await fetch(imagePath);
const imageData = await response.blob();
await fetch(url, {
body: imageData,
method: ‘PUT’
});

Can you suggest what to do?

**Comment by iBotPeaches** [comment]
Sorry @Punit-Vajpeyi I shouldn't have responded. I'm either completely wrong and somehow fetch() supports `file://` properties in RN or I am still right and you aren't providing context and doing something that frankly makes no sense.

You mention things worked for last 2 months, but RN72 hasn't been out that long. That code above appears to be working with HTTP as you aren't sending PUT method calls to a filesystem.

So I'm sorry - nothing posted here makes sense to me and I shouldn't have responded. Best of luck.

**Comment by Punit-Vajpeyi** [comment]
The above snippet worked on RN71 then I upgraded to RN72 and it started to
return the error status.
RN71 used to support file://.

I will check the change log for this, seems like the version issue, will
also try to downgrade once again to RN71.

**Comment by MGuerra17** [comment]
@Punit-Vajpeyi  I was facing the same issue. This StackOverflow solution helped me. 

https://stackoverflow.com/questions/55957683/get-picked-image-on-android-with-react-native-fetch-api

I hope it helps you too.

**Comment by hgb072082** [comment]
i am facing this error only in android

**Comment by AlexanderEggers** [comment]
We faced the same issue using RN 0.71 and the root cause was related to an intended upgrade of whatwg-fetch to latest version 3.6.17. As soon as we downgraded to the previous used version, everything worked again. It seems that a newer version than 3.6.2 is causing these issues for some reasons.

The suggestion by @MGuerra17 unfortunately didn't work for us.

**Comment by yuvrajchaudhari03** [comment]
how to use `whatwg-fetch` in react native?
const getBlob = useCallback(fileUri => {
        return fetch("file://" + fileUri).then(
            response => {
                console.log("getBlob res=>,", response)
                return response.blob()
            },
            error => {
                console.log(`Error in converting image to blob - ${error}`)
            },
        )
    }, [])

**Comment by 19424056** [comment]
same issue

**Comment by mschervesnquy** [comment]
same issue here, and nothing on the web can fix it

**Comment by stefan-schweiger** [comment]
Just use this as as workaround for now:

https://stackoverflow.com/a/76761937/503059

```
/**
 * Function to convert a URI to a Blob object
 * @param {string} uri - The URI of the file
 * @returns {Promise} - Returns a promise that resolves with the Blob object
 */
export function uriToBlob(uri: string): Promise<Blob> {
  return new Promise((resolve, reject) => {
    const xhr = new XMLHttpRequest();

    // If successful -> return with blob
    xhr.onload = function () {
      resolve(xhr.response);
    };

    // reject on error
    xhr.onerror = function () {
      reject(new Error('uriToBlob failed'));
    };

    // Set the response type to 'blob' - this means the server's response 
    // will be accessed as a binary object
    xhr.responseType = 'blob';

    // Initialize the request. The third argument set to 'true' denotes 
    // that the request is asynchronous
    xhr.open('GET', uri, true);

    // Send the request. The 'null' argument means that no body content is given for the request
    xhr.send(null);
  });
};
```

Usage `const blob = await uriToBlob(fileUri)`

**Comment by meteorlxy** [comment]
Per [this issue](https://github.com/JakeChampion/fetch/issues/1213), it's as expected to throw an error on `0` status code according to fetch spec. That's why `whatwg-fetch` updated like this.

---

According to [fetch spec - Schema fetch](https://fetch.spec.whatwg.org/#scheme-fetch):

> "file"
> For now, unfortunate as it is, file: [URLs](https://www.w3.org/TR/pub-manifest/#dfn-url) are left as an exercise for the reader.
>
> When in doubt, return a [network error](https://fetch.spec.whatwg.org/#concept-network-error).

I'm not sure what's the exact meaning of the spec - whether should fetch API support `file://` uri or not?

Regardless the fetch spec and the updates of whatwg-fetch package, using [the snippet in the previous comment](https://github.com/facebook/react-native/issues/38625#issuecomment-1691864081) should always be a safe solution.

**Comment by PedroH183** [comment]
@stefan-schweiger tyy ! Its worked for me. But i maked the mistake don't use `await` when call this function.
