### ISSUE TITLE
React native 0.72 new version error 

### ISSUE THREAD

**Issue by priyaWedo** [facebook/react-native#38621]
### Description

i created project in react native 0.72 and when i run this it gives me error 
![Screenshot 2023-07-25 at 7 35 24 PM](https://github.com/facebook/react-native/assets/126875445/95f67fca-e66a-49b7-aa62-d7b8625332b8)

### React Native Version

0.72.3

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
  OS: macOS 13.4
  CPU: (8) arm64 Apple M2
  Memory: 61.06 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.3.0
    path: /usr/local/bin/node
  Yarn: Not Found
  npm:
    version: 9.7.1
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2023.05.22.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /Users/priyabapodra/.rvm/gems/ruby-3.0.0/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.2
      - iOS 16.2
      - macOS 13.1
      - tvOS 16.1
      - watchOS 9.1
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.2 AI-222.4459.24.2221.10121639
  Xcode:
    version: 14.2/14C18
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 20.0.2
    path: /usr/bin/javac
  Ruby:
    version: 3.0.0
    path: /Users/priyabapodra/.rvm/rubies/ruby-3.0.0/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.3
    wanted: 0.72.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

### Steps to reproduce

---

### Snack, screenshot, or link to a repository

![Screenshot 2023-07-25 at 7 36 51 PM](https://github.com/facebook/react-native/assets/126875445/92628304-287a-4546-8722-394ee6d91bce)
![Screenshot 2023-07-25 at 7 37 00 PM](https://github.com/facebook/react-native/assets/126875445/01ef92dd-289b-4954-adca-6e61ed8b7e5b)

**Comment by iBotPeaches** [comment]
@priyaWedo where is the error? That looks fine and a regular expected warning.

**Comment by cortinico** [comment]
Closing as the error you're reporting is actually a warning as is expected

**Comment by priyaWedo** [comment]
![Screenshot 2023-07-26 at 10 07 23 AM](https://github.com/facebook/react-native/assets/126875445/fb4abcd6-2e85-458d-82fc-448e2c5358e4)
@iBotPeaches

**Comment by priyaWedo** [comment]
> Closing as the error you're reporting is actually a warning as is expected

@cortinico please review the above image

**Comment by lunaleaps** [comment]
I found this: https://stackoverflow.com/questions/67240279/could-not-open-settings-generic-class-cache-for-settings-file
Have you looked into this?
