### ISSUE TITLE
maxLength support for Android?

### ISSUE THREAD

**Issue by niftylettuce** [facebook/react-native#3864]
Right now docs say it only works on iOS:

![screen shot 2015-11-03 at 10 21 08 am](https://cloud.githubusercontent.com/assets/523141/10911829/ae0363c2-8214-11e5-8d9d-211c1e160f8b.png)

**Comment by niftylettuce** [comment]
This is a prop for `<TextInput />` btw

**Comment by jforaker** [comment]
+1  This is a fundamental necessity
