### ISSUE TITLE
App getting crashed after upgradation

### ISSUE THREAD

**Issue by vksgautam1986** [facebook/react-native#38650]
### New Version

0.72.3

### Old Version

0.67.5

### Build Target(s)

12.4

### Output of `react-native info`

System:
  OS: macOS 13.4.1
  CPU: (8) arm64 Apple M1
  Memory: 111.20 MB / 8.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 16.11.0
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.19
    path: ~/Desktop/Swatched/Final/swatched-mobile/node_modules/.bin/yarn
  npm:
    version: 8.0.0
    path: /usr/local/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.12.0
    path: /Users/test/.rvm/gems/ruby-3.0.0/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.1
      - iOS 16.1
      - macOS 13.0
      - tvOS 16.1
      - watchOS 9.1
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.2 AI-222.4459.24.2221.9862592
  Xcode:
    version: 14.1/14B47
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.12
    path: /usr/bin/javac
  Ruby:
    version: 3.0.0
    path: /Users/test/.rvm/rubies/ruby-3.0.0/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.3
    wanted: ^0.72.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

### Issue and Reproduction Steps

<RBSTerminateContext| domain:10 code:0x8BADF00D explanation:[application<com.swatched>:23258] failed to terminate gracefully after 5.0s

For android it is working fine and for ios it is giving issue
i have upgraded the application from 0.67.5 to 0.72.3 and after this app get stuck in simulator and in metro it shows
-- warn No apps connected. Sending "reload" to all React Native apps failed. Make sure your app is running in the simulator or on a phone connected via USB.

after few minutes it shows the crash window. I have attached package, pdfile, appdelegate.mm , crash file and pbxproject.
i think there is some issue in my appdelegate file but im not sure about it

[untitled folder.zip](https://github.com/facebook/react-native/files/12181941/untitled.folder.zip)

**Comment by cortinico** [comment]
> untitled folder.zip

Could you put it in a git repo?

**Comment by vksgautam1986** [comment]
ok sure

**Comment by vksgautam1986** [comment]
here is the repo. if there is anything specific you guys want, please let me know. Till then i am just trying to do it with fresh 0.72 project and checking if it's working fine with it or not

**Comment by vksgautam1986** [comment]
as inspecting i am getting issues logs in Xcode. so fixing one by one. one of them is for splash screen
https://github.com/crazycodeboy/react-native-splash-screen/issues/606

after this there was orientation
https://github.com/wonday/react-native-orientation-locker/pull/243

but after this i am stuck again with things

**Comment by vksgautam1986** [comment]
Thanks its working fine now. Those were the two libraries which was creating issues and also updated the react native reanimated to 3.4.1
