### ISSUE TITLE
Failed to install the app. Make sure you have the Android development environment

### ISSUE THREAD

**Issue by gwonsuji** [facebook/react-native#38657]
### Description

I've completed the setup according to the manual below, but it doesn't run on the emulator in Visual Studio Code, even if it runs on Android Studio. Is there anything else I need to set up?

https://reactnative.dev/docs/0.70/troubleshooting

After creating a project of 0.70.5 version of react native cli, the app will not be installed on the emulator without any modifications.

This is my error
```
npx react-native run-android
info Starting JS server...
* daemon not running; starting now at tcp:5037
* daemon started successfully
info Launching emulator...
info Successfully launched emulator.
info Installing the app...
Unrecognized option: -xmx64m
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
Unrecognized option: -xmx64m
Error: A fatal exception has occurred. Program will exit.

    at makeError (D:\Android\AwesomeProject\node_modules\@react-native-community\cli-platform-android\node_modules\execa\index.js:174:9)
    at D:\Android\AwesomeProject\node_modules\@react-native-community\cli-platform-android\node_modules\execa\index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (D:\Android\AwesomeProject\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:109:5)     
    at async Command.handleAction (D:\Android\AwesomeProject\node_modules\@react-native-community\cli\build\index.js:142:9)
info Run CLI with --verbose flag for more details.
```

android studio setting
![image](https://github.com/facebook/react-native/assets/60372704/c35a0b9f-6b01-4cdc-9a38-9c17cea0bf67)
![image](https://github.com/facebook/react-native/assets/60372704/68142650-0540-4f69-ad7a-db1c7fbb1d57)
![image](https://github.com/facebook/react-native/assets/60372704/512586d4-d43b-40d7-ab8a-fd9d533bc245)
![image](https://github.com/facebook/react-native/assets/60372704/d7b0897f-8963-45eb-849c-e4f70038bb80)

System environment variables
![image](https://github.com/facebook/react-native/assets/60372704/d245952a-e147-42c3-b195-e27e50eb330f)
![image](https://github.com/facebook/react-native/assets/60372704/03fffc9f-d909-47c4-aa85-c83b17506a90)

The problem occurs as soon as you create and run a react native cli project, but if you don't have an example, just attach a git link for the project that doesn't run because the issues close.

### React Native Version

0.70.5

### Output of `npx react-native info`

System:
    OS: Windows 10 10.0.19045
    CPU: (6) x64 Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
    Memory: 1.44 GB / 15.94 GB
  Binaries:
    Node: 16.14.1 - C:\Program Files\nodejs\node.EXE     
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD       
      Android NDK: 22.1.7171670
    Windows SDK: Not Found
  IDEs:
    Android Studio: AI-223.8836.35.2231.10406996
    Visual Studio: Not Found
  Languages:
    Java: 11.0.18 - C:\Program Files\Java\jdk-11\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.5 => 0.70.5
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. Create a project of 0.70.5 version of react nativecli.
2. Run `npx react-native start` in Visual Studio Code.
3. Open a new terminal in Visual Studio Code to run `npx react-native run-android`.

### Snack, screenshot, or link to a repository

https://github.com/gwonsuji/ErrorExampleApp.git

**Comment by cortinico** [comment]
> Unrecognized option: -xmx64m

You have this property somewhere in the repo or in your environment.
Not sure what is causing this, but this is effectively making your entire build failing.

I checked in your repo and the property is configured correctly:
https://github.com/gwonsuji/ErrorExampleApp/blob/master/android/gradle.properties#L13

So I'm unsure what is causing this but is a local environment problem of yours sadly.

**Comment by gwonsuji** [comment]
@cortinico I added all the environmental variables in the manual. Is there anything else I need to set up?
 If it's an environmental problem, is there no way I can get support? If so, is there no way for me to run react native?

**Comment by cortinico** [comment]
> If it's an environmental problem, is there no way I can get support? If so, is there no way for me to run react native?
> It's not just that it's not running, I can't even debug it because of this.

Sorry but this issue tracker is for bug inside react-native core. We can't offer support to every environment setup issue.

Unless we confirm that this is an issue that **everyone** has, and needs a bugfix inside core, we can't offer support here.

Your best best is to ask on StackOverflow https://stackoverflow.com/questions/tagged/react-native or on other forums

**Comment by 111Tashmo** [comment]
i got the same issue... any suggestion?

**Comment by atharvbhute** [comment]
Got the same issue

**Comment by skillnull** [comment]
+1

**Comment by gaokun0422** [comment]
+1
