### ISSUE TITLE
Consuming Hermes from source in a React Native app

### ISSUE THREAD

**Issue by carlosalmonte04** [facebook/react-native#38658]
## Bug Description

My goal is to make use of a custom build of hermes running in a react native app. Following the docs works fine for me until I have to run the command below.

– The only thing that comes to mind is that I had to add `ANDROID_SDK_ROOT` to my environment, I made it the same as `ANDROID_SDK`. [_Also `ANDROID_SDK_ROOT` is deprecated._](https://developer.android.com/tools/variables#envar)

```
$ ninja github-cli-release
ninja: error: unknown target 'github-cli-release'
```

- [ ] I have run `gradle clean` and confirmed this bug does not occur with JSC

Hermes version: 0.12.0
React Native version (if any): 0.72.3
OS version (if any): N/A
Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64):

## Steps To Reproduce

1. Run the commands below to build a release version of Hermes:
`cmake -S hermes -B build_release -G Ninja -DCMAKE_BUILD_TYPE=Release`
`cmake --build ./build_release`
2. Run the command below to package CLI binaries for the current platform
`cd $HERMES_WS_DIR/build_release && ninja github-cli-release`

Produces error "ninja: error: unknown target 'github-cli-release'" 

code example:
N/A

## The Expected Behavior
Command `ninja github-cli-release` should run successfully.

**Comment by cortinico** [comment]
@carlosalmonte04 to unblock yourself, I would just comment out the Flipper initialization on `MainApplication.java:60`

> at com.awesomeproject072.MainApplication.onCreate(MainApplication.java:60)

**Comment by carlosalmonte04** [comment]
Finally got it working! Gosh, that took some time to build. Thanks @cortinico. I don't even know where to start from or what usages I can have have with this power. Thanks again.

**Comment by cortinico** [comment]
Great thanks for reporting back 👍

**Comment by carlosalmonte04** [comment]
How can I accomplish this same task on iOS?

**Comment by cipolleschi** [comment]
Hi @carlosalmonte04, I haven't test it and right now I really can't, but if you install pods with:
```
BUILD_FROM_SOURCE=true bundle exec pod install
```
It should take the commit of Hermes we are using for the version of react native and build it from source.
Beware, it will take some time to build.

- [`hermes-utils.rb`](https://github.com/facebook/react-native/blob/0.72-stable/packages/react-native/sdks/hermes-engine/hermes-utils.rb#L38-L43)
- [`hermes-engine.podspec`](https://github.com/facebook/react-native/blob/0.72-stable/packages/react-native/sdks/hermes-engine/hermes-engine.podspec#L20)

**Comment by carlosalmonte04** [comment]
Thanks @cipolleschi. In addition to that I also had to change the git url in [`hermes-utils.rb`](https://github.com/facebook/react-native/blob/0.72-stable/packages/react-native/sdks/hermes-engine/hermes-utils.rb#L131) to point to my fork of hermes. 

That url should probably be an environment variable, similar to Android's `REACT_NATIVE_OVERRIDE_HERMES_DIR` variable.

Thanks again for responding even though the issue was already closed.

😃
