### ISSUE TITLE
✖ Android Studio - Required for building and installing your app on Android

### ISSUE THREAD

**Issue by rjl-cli** [facebook/react-native#38663]
### Description

PS C:\Users\renjiali\Desktop\test\AwesomeProject> yarn doctor
yarn run v1.22.19
$ react-native doctor
Common
 ✓ Node.js - Required to execute JavaScript code
 ✓ yarn - Required to install NPM dependencies

Android
 ✖ Adb - No devices and/or emulators connected. Please create emulator with Android Studio or connect Android device.
 ✓ JDK - Required to compile Java code
 ✖ Android Studio - Required for building and installing your app on Android
 ✖ Android SDK - Required for building and installing your app on Android
   - Versions found: N/A
   - Version supported: 33.0.0
 ✓ ANDROID_HOME - Environment variable that points to your Android SDK installation

Errors:   3
Warnings: 0

Attempting to fix 3 issues...

### React Native Version

0.71.0

### Output of `npx react-native info`

![Uploading image.png…]()

### Steps to reproduce

如何解决？已经安装但是提示没有

### Snack, screenshot, or link to a repository

如何解决？已经安装但是提示没有

**Comment by tarunrajput** [comment]
@rjl-cli, do you have Android Studio installed?

**Comment by cortinico** [comment]
Hi @rjl-cli Please follow the instructions on this page:
https://reactnative.dev/docs/environment-setup

**Comment by longnguyen2508** [comment]
This may help

https://github.com/react-native-community/cli/issues/1220#issuecomment-1688272156

**Comment by ZarcoOscarDSM31** [comment]
¿Logró solucionarlo?
Yo también tengo ese problema y quisera saber como lo solucionó (Uso Manjaro Linux KDE)

**Comment by abrahamt17** [comment]
> @rjl-cli, do you have Android Studio installed?

yes but still doesn't work

**Comment by vladi965** [comment]
Necesito ayuda, porfavor ya instale el sdk pero nada 

![image](https://github.com/facebook/react-native/assets/91103840/50166047-dce4-49c3-8fc5-d58a61c75f74)

**Comment by velrino** [comment]
I've problem here!

✖ Android Studio - Required for building and installing your app on Android

Runnign in android-studio 🤡

![image](https://github.com/user-attachments/assets/e0a9ce57-e235-495b-ab1b-b233565754b6)

**Comment by fondue-tech** [comment]
@velrino did you fix the issue ? I have exactly the same issue as you had.
