### ISSUE TITLE
RN v0.14.0-rc running on device, “it looks like the implementation of __DEV__ has changed”

### ISSUE THREAD

**Issue by sulliwane** [facebook/react-native#3866]
I'm trying to load bundle from iphone disk with v0.14.0-rc. 

I uncommented this line in **AppDelegate.m**:

```jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];```

then I created the bundle with this command:

```react-native bundle --entry-file index.ios.js --platform ios --bundle-output main.jsbundle --verbose```

Finally, after installing the app on the iphone, it starts and then hang on white screen, and here is the error screen from xcode:
![screenshot from 2015-11-04 00 01 48](https://cloud.githubusercontent.com/assets/1733686/10913070/51999cdc-8287-11e5-9f75-935af48f334b.png)
Thank you for your help :)

**Comment by Purii** [comment]
Look at #3782

**Comment by ide** [comment]
Closing this since it's tracked in #3782 and will be fixed in 0.14 final (coming in a few days).
