### ISSUE TITLE
2 files found with path 'lib/arm64-v8a/libc++_shared.so' from inputs:

### ISSUE THREAD

**Issue by AdarshJais** [facebook/react-native#38665]
### New Version

0.68.5

### Old Version

0.67.5

### Build Target(s)

Android

### Output of `react-native info`

`System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M2
    Memory: 130.89 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.11.0 - /usr/local/bin/npm
    Watchman: 2023.07.24.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/adarshjaiswal/.rvm/gems/ruby-2.7.5/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK:
      API Levels: 28, 29, 30, 31, 32, 33
      Build Tools: 21.1.2, 23.0.1, 23.0.2, 23.0.3, 24.0.0, 24.0.1, 24.0.2, 25.0.1, 25.0.2, 26.0.2, 26.0.3, 27.0.2, 27.0.3, 28.0.0, 28.0.1, 28.0.2, 28.0.3, 29.0.0, 29.0.1, 29.0.2, 29.0.3, 30.0.0, 30.0.1, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0
      System Images: android-31 | Google Play ARM 64 v8a, android-33 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2022.3 AI-223.8836.35.2231.10406996
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.20 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found`

### Issue and Reproduction Steps

(new architecture false)
> Task :app:mergeDebugNativeLibs
Execution optimizations have been disabled for task ':app:mergeDebugNativeLibs' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '/Users/adarshjaiswal/Development/MyApp-fe/react-native/MyApp/android/app/build/intermediates/merged_jni_libs/debug/out'. Reason: Task ':app:mergeDebugNativeLibs' uses this output of task ':app:copyDebugReactNativeVectorIconFonts' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.4/userguide/validation_problems.html#implicit_dependency 
  
  Upgrading react-native-vector-icons `v9.2.0` to seems to solve the above warning but the below error still remains the same.
  
  - 
![image](https://github.com/facebook/react-native/assets/40723757/2e31a8ad-3d70-4ff4-8995-cba7cb05f963)

**This is all that I tried**

- I also came to this official fix: (https://github.com/facebook/react-native/issues/35210) , But as you can see I am using 68.5 and still facing this issue

- I followed https://react-native-community.github.io/upgrade-helper/?from=0.67.5&to=0.68.5 for upgrading.

- I also tried commands like these multiple times : rm -rf $HOME/.gradle/caches   rm -rf ~/.gradle   ./gradlew clean yarn cache clean 

Here is my `build.gradel` file : 

`buildscript {
    ext {
            buildToolsVersion = "31.0.0"
            minSdkVersion = 21
	        compileSdkVersion = 33
	        targetSdkVersion = 33
	        // ndkVersion = "20.1.5948944"
            ndkVersion = "21.4.7075529"
            androidXCore = "1.7.0" // <-- Add this. Check versions here: https://developer.android.com/jetpack/androidx/releases/core
    }
    repositories {
        google()
        mavenCentral()
      
    }
    dependencies {
        classpath('com.android.tools.build:gradle:7.3.1')
        classpath("com.google.gms:google-services:4.3.10")  // Google Services plugin
        classpath("com.facebook.react:react-native-gradle-plugin")
        classpath("de.undercouch:gradle-download-task:4.1.2")
        classpath 'com.guardsquare:proguard-gradle:7.2.1'  // The ProGuard Gradle plugin.

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
        repositories {
            exclusiveContent {
                // We get React Native's Android binaries exclusively through npm,
                // from a local Maven repo inside node_modules/react-native/.
                // (The use of exclusiveContent prevents looking elsewhere like Maven Central
                // and potentially getting a wrong version.)
                filter {
                    includeGroup "com.facebook.react"
                }
                forRepository {
                    maven {
                        url "$rootDir/../node_modules/react-native/android"
                    }
                }
            }
            maven {
                // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
                url("$rootDir/../node_modules/react-native/android")
            }
             maven { url 'https://maven.zohodl.com' }
            maven {
                // Android JSC is installed from npm
                url("$rootDir/../node_modules/jsc-android/dist")
            }
            mavenCentral {
                // We don't want to fetch react-native from Maven Central as there are
                // older versions over there.
                content {
                    excludeGroup "com.facebook.react"
                }
            }
            google()
            maven { url 'https://www.jitpack.io' }
             jcenter() {
                content {
                    // these groups only available in jcenter otherwise we don't want to rely on jcenter.

                    includeModule("com.wei.android.lib", "fingerprintidentify") // <== Add this line
                }
            }
        }
   
}`

Also attaching complete package.json. If it could be of any help 

{
  "name": "MyApp",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "resolve": "npx npm-force-resolutions && npm install",
    "npm-old": "npm i --legacy-peer-deps",
    "postinstall": "npx jetify",
    "start": "react-native start",
    "test": "jest",
    "preversion": "./npm-version/pre-version.sh",
    "version": "./npm-version/version-ios.sh",
    "postversion": "./npm-version/post-version.sh",
    "clean": "yarn clean-ios && yarn clean-android && yarn clean-node && watchman watch-del-all && rm -rf /tmp/metro-*",
    "clean-android": "rm -rf android/.gradle android/.idea android/build android/app/build",
    "clean-ios": "cd ios && pod deintegrate && cd .. && pod cache clean --all && rm -rf ios/build ios/Podfile.lock",
    "clean-node": "rm -rf node_modules yarn.lock",
    "clean-npm": "npm cache clean --force",
    "storybook": "start-storybook -c .storybook -p 7007 -h 192.168.0.111",
    "build-storybook": "build-storybook"
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "^1.15.7",
    "@react-native-clipboard/clipboard": "^1.9.0",
    "@react-native-community/art": "^1.2.0",
    "@react-native-community/datetimepicker": "^3.5.2",
    "@react-native-community/netinfo": "9.1.0",
    "@react-native-community/progress-bar-android": "^1.0.4",
    "@react-native-community/progress-view": "^1.3.1",
    "@react-native-firebase/app": "^12.7.3",
    "@react-native-firebase/messaging": "^12.9.3",
    "@react-native-firebase/remote-config": "^12.7.3",
    "@react-native-picker/picker": "^2.2.0",
    "@react-navigation/bottom-tabs": "^6.0.5",
    "@react-navigation/elements": "^1.2.1",
    "@react-navigation/native": "^6.0.2",
    "@react-navigation/native-stack": "^6.1.0",
    "@react-navigation/stack": "^6.0.7",
    "@sentry/react-native": "^3.2.3",
    "appcenter": "4.4.3",
    "appcenter-analytics": "4.4.3",
    "appcenter-crashes": "4.4.3",
    "babel-traverse": "^6.26.0",
    "babylon": "^6.18.0",
    "cashfree-pg-api-contract": "2.0.0",
    "digio-sdk-rn": "^0.1.0",
    "eslint-plugin-react-hooks": "^4.2.0",
    "get-dev-paths": "^0.1.0",
    "immutable": "^4.0.0-rc.12",
    "jail-monkey": "^2.6.0",
    "lodash": "^4.17.21",
    "lodash.isplainobject": "4.0.6",
    "lottie-ios": "3.2.3",
    "lottie-react-native": "5.0.1",
    "mixpanel-react-native": "^1.3.4",
    "mobile-ui-components": "file:../mobile-ui-components",
    "moment": "^2.22.2",
    "native-base": "3.2.2",
    "raven-for-redux": "^1.4.0",
    "raven-js": "^3.27.2",
    "react": "17.0.2",
    "react-native": "^0.68.5",
    "react-native-animatable": "^1.3.0",
    "react-native-biometrics": "2.1.4",
    "react-native-calendar-picker": "^7.1.2",
    "react-native-cashfree-pg-sdk": "2.0.1",
    "react-native-code-push": "^7.0.1",
    "react-native-collapsible": "^1.6.0",
    "react-native-country-picker-modal": "^2.0.0",
    "react-native-date-picker": "^4.0.0",
    "react-native-device-info": "^8.3.1",
    "react-native-document-picker": "^8.0.0",
    "react-native-encrypted-storage": "4.0.2",
    "react-native-file-viewer": "^2.1.4",
    "react-native-fingerprint-scanner": "^6.0.0",
    "react-native-fs": "2.19.0",
    "react-native-geolocation-service": "^5.3.0-beta.4",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-image-picker": "^4.1.2",
    "react-native-in-app-review": "^3.2.3",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-material-textfield": "^0.12.0",
    "react-native-modal": "^13.0.0",
    "react-native-moengage": "8.0.0",
    "react-native-obfuscating-transformer": "^1.0.0",
    "react-native-otp-textinput": "git+https://github.com/d49mark/react-native-otp-textinput.git",
    "react-native-pager-view": "5.4.24",
    "react-native-pdf": "6.3.0",
    "react-native-progress": "^5.0.0",
    "react-native-reanimated": "2.14.4",
    "react-native-safe-area-context": "^3.3.2",
    "react-native-screens": "^3.8.0",
    "react-native-share": "^7.1.0",
    "react-native-signature-capture": "git+https://github.com/vinhtnk/react-native-signature-capture.git",
    "react-native-sms-retriever": "^1.0.3",
    "react-native-snackbar": "^2.4.0",
    "react-native-splash-screen": "^3.3.0",
    "react-native-svg": "12.1.1",
    "react-native-svg-charts": "^5.4.0",
    "react-native-swiper": "^1.6.0",
    "react-native-system-setting": "^1.7.6",
    "react-native-tab-view": "^3.1.1",
    "react-native-ux-cam": "5.3.1",
    "react-native-vector-icons": "^8.1.0",
    "react-native-version-check": "3.4.3",
    "react-native-video": "^5.0.2",
    "react-native-view-shot": "3.0.2",
    "react-native-webview": "^11.13.0",
    "react-native-zohosalesiq-mobilisten": "4.2.13",
    "react-redux": "^7.2.5",
    "redux": "^4.1.1",
    "redux-saga": "^1.1.3",
    "rn-fetch-blob": "^0.12.0",
    "rn-range-slider": "^1.2.9",
    "rupee-formatter": "^1.0.5",
    "shallow-equals": "1.0.0",
    "simple-selectors": "1.0.3",
    "styled-components": "^5.3.1",
    "styled-system": "^5.1.5",
    "urijs": "^1.19.1"
  },
  "devDependencies": {
    "@babel/core": "^7.15.4",
    "@babel/runtime": "^7.15.4",
    "@react-native-community/eslint-config": "^3.0.1",
    "@storybook/addon-actions": "^5.3.21",
    "@storybook/addon-knobs": "^5.3.21",
    "@storybook/addon-links": "^5.3.21",
    "@storybook/addon-ondevice-actions": "^5.3.23",
    "@storybook/addon-ondevice-knobs": "^5.3.25",
    "@storybook/react-native": "^5.3.25",
    "@storybook/react-native-server": "^5.3.23",
    "babel-jest": "^27.1.0",
    "babel-loader": "^8.2.2",
    "eslint": "^7.32.0",
    "jest": "^27.1.0",
    "metro-react-native-babel-preset": "^0.67.0",
    "prop-types": "^15.6.2",
    "react-dom": "17.0.2",
    "react-native-codegen": "0.0.8",
    "react-test-renderer": "17.0.2",
    "redux-devtools-extension": "^2.13.9"
  },
  "jest": {
    "preset": "react-native",
    "setupFiles": [
      "<rootDir>/node_modules/appcenter/test/AppCenterMock.js",
      "<rootDir>/node_modules/appcenter-analytics/test/AppCenterAnalyticsMock.js",
      "<rootDir>/node_modules/appcenter-crashes/test/AppCenterCrashesMock.js"
    ],
    "transformIgnorePatterns": [
      "node_modules/(?!(jest-)?react-native|react-clone-referenced-element|@react-native-community|expo(nent)?|@expo(nent)?/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base)"
    ],
    "setupFilesAfterEnv": [
      "<rootDir>/__mocks__/globalMock.js"
    ]
  }
}

**Comment by AdarshJais** [comment]
Facing it on v0.69.12 as well!

**Comment by cortinico** [comment]
> * Reason: Task ':app:mergeDebugNativeLibs' uses this output of task ':app:copyDebugReactNativeVectorIconFonts'

Hi,
Thanks for reporting this issue.

It seems like this issue is actually unrelated to React Native core, but related to React Native Vector Icons.
Please open this issue against this other repository:

https://github.com/oblador/react-native-vector-icons/issues

I'll be closing this but feel free to reopen if the other repo points back to us as a issue in the core of React Native.

**Comment by AdarshJais** [comment]
For anyone else facing a similar issue, Combination of `react-native 0.72.3` and  `react-native-vector-icons:10.0.0` works for me.
