### ISSUE TITLE
[Android] Scrollview "scrollEnabled"

### ISSUE THREAD

**Issue by PhilippKrone** [facebook/react-native#3868]
Hello,

I'm looking forward to implement "scrollEnabled" in Android as well. I think its straight forward for simple scrollviews in android, but I'm not so sure concerning passing the MotionEvent to children of the scrollview. 

I was digging around in https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/views/scroll/ReactScrollView.java but without luck until now. My idea was to implement OnTouchEvents and return either true or false depending on whether a boolean variable (which is by default true and can be set via the respective scrollview manager) is set or not.

I'd appreciate any help / any information :)

Thanks
Philipp

**Comment by browniefed** [comment]
@facebook-github-bot label Android

**Comment by browniefed** [comment]
@facebook-github-bot answered

**Comment by browniefed** [comment]
https://github.com/facebook/react-native/commit/82b0df9d2a6163879647691235f01b3067c471b8
