### ISSUE TITLE
[iOS] Cannot use HERMES_ENGINE_TARBALL_PATH with pod install in 0.72.3

### ISSUE THREAD

**Issue by pnthach95** [facebook/react-native#38689]
### Description

I usually use `HERMES_ENGINE_TARBALL_PATH` with `pod install` because `curl` downloads it too slow. However, it can't be used in latest version (0.72.3). I don't test on version 0.72.0 to 0.72.2. Older versions (0.70.x, 0.71.x) can use `HERMES_ENGINE_TARBALL_PATH`.

### React Native Version

0.72.3

### Output of `npx react-native info`

```bash
System:
  OS: macOS 13.4.1
  CPU: (8) arm64 Apple M1
  Memory: 94.16 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.16.1
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.19
    path: /usr/local/bin/yarn
  npm:
    version: 9.5.1
    path: /usr/local/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.12.1
    path: /Users/pnthach/.rvm/rubies/ruby-2.7.5/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK:
    API Levels:
      - "33"
    Build Tools:
      - 28.0.3
      - 30.0.2
      - 30.0.3
      - 31.0.0
      - 32.0.0
      - 33.0.0
      - 33.0.2
    System Images:
      - android-33 | Google APIs ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10406996
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.20
    path: /usr/bin/javac
  Ruby:
    version: 2.7.5
    path: /Users/pnthach/.rvm/rubies/ruby-2.7.5/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.3
    wanted: 0.72.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Steps to reproduce

- Download hermes tarball at https://repo1.maven.org/maven2/com/facebook/react/react-native-artifacts/0.72.3/react-native-artifacts-0.72.3-hermes-ios-debug.tar.gz
- Create new project with version 0.72.3 using `--skip-install`: `npx react-native init AwesomeProject --skip-install`
- Run `cd AwesomeProject;yarn;cd ios`
- Run `HERMES_ENGINE_TARBALL_PATH=... pod install --verbose`, replace `...` with your path to tarball and see result

### Snack, screenshot, or link to a repository

v0.72.3
<img width="939" alt="Screenshot 2023-07-31 at 2 31 20 PM" src="https://github.com/facebook/react-native/assets/31266357/6baf4e7c-9e56-40d6-85d6-67b909e05349">
<img width="1157" alt="Screenshot 2023-07-31 at 2 31 27 PM" src="https://github.com/facebook/react-native/assets/31266357/98450e03-a2c4-4ceb-9ad0-4a8add153757">

v0.71.12
<img width="1046" alt="Screenshot 2023-07-31 at 3 02 23 PM" src="https://github.com/facebook/react-native/assets/31266357/1385b26f-b36d-4ae2-995b-97cdec067900">
<img width="1006" alt="Screenshot 2023-07-31 at 3 06 41 PM" src="https://github.com/facebook/react-native/assets/31266357/33758fe7-a1a1-4ede-8332-0a5fff4a1185">

**Comment by cipolleschi** [comment]
Hi @pnthach95, thanks for opening this issue.

I actually followed your steps, but it is working correctly:

- `npx react-native init HermesTarball --version latest --skip-install`
- `cd HermesTarball`
- `yarn`
- `cd ios`
- `bundle install`
- `HERMES_ENGINE_TARBALL_PATH=~/Downloads/hermes-ios.tar.gz bundle exec pod install --verbose`

And I get:
- Using Hermes engine locally
<img width="1077" alt="Screenshot 2023-07-31 at 12 05 35" src="https://github.com/facebook/react-native/assets/11162307/57b1a3bd-5981-4943-a0fc-ec17a711809c">

- The "download" happens from the local file
<img width="1644" alt="Screenshot 2023-07-31 at 12 06 18" src="https://github.com/facebook/react-native/assets/11162307/3662038e-3281-421f-9b0d-e80ee759400a">

So... probably there is something off in your local setup?

**Comment by pnthach95** [comment]
Thanks for your response. It works when using with `bundle exec`. I guess my local is mess up.

**Comment by ulik88** [comment]
it works for me on react native app but not on expo, is there any suggestions for expo to build the app on ios?

**Comment by cipolleschi** [comment]
I suggest you to open a similar issue on the [expo repository](https://github.com/expo/expo) to ask for their guidance.
