### ISSUE TITLE
normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler

### ISSUE THREAD

**Issue by nsh635211** [facebook/react-native#38682]
### Description

Hello. After Xcode upgrade 14.3, an error is reported in the picture after the yarn ios command is executed. What can I do? Project needs to go live. Mayday! Help me!

### React Native Version

 "react-native": "0.67.2",

### Output of `npx react-native info`

System:
    OS: macOS 13.4.1
    CPU: (8) x64 Apple M1
    Memory: 10.33 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 14.21.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 6.14.18 - /usr/local/bin/npm
    Watchman: 2023.03.13.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /Users/gml/.rvm/gems/ruby-2.7.4/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9619390
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.18 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

yarn ios 

The following build commands failed:
        CompileC /Users/gml/Library/Developer/Xcode/DerivedData/superdriver-bjcjwgnifkjcapazofrqqvcpnoxk/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/Yoga.build/Objects-normal/arm64/Yoga.o /Users/gml/Desktop/cjdj/oss-spcar-app/node_modules/react-native/ReactCommon/yoga/yoga/Yoga.cpp normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'Yoga' from project 'Pods')

### Snack, screenshot, or link to a repository

<img width="1440" alt="截屏2023-07-29 22 44 13" src="https://github.com/facebook/react-native/assets/78367271/2c2612ca-8605-43bd-a689-82978c8da6a4">

**Comment by alizain31** [comment]
@nsh635211 can you please tell me how you resolved this issue ?i am using mac and in ios app run ,i am facing same issue
