### ISSUE TITLE
duplicate gradle files

### ISSUE THREAD

**Issue by vigyanhoon** [facebook/react-native#38684]
### Description

Hi,

I am not sure why but after upgrading to latest react native, I see lot of duplicate files getting created like build 2.gradle, settings 2.gradle. I event saw duplicate files in node modules and also saw Flipper 2.java. Not sure why this is happening after upgrade.
<img width="348" alt="image" src="https://github.com/facebook/react-native/assets/8503526/cbc3bc68-6499-4e43-ac5e-f69f840e7e30">

### React Native Version

0.72.3

### Output of `npx react-native info`

npx react-native info
info Fetching system and libraries information...
System:
  OS: macOS 13.4.1
  CPU: (10) arm64 Apple M2 Pro
  Memory: 115.53 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 16.20.0
    path: ~/.nvm/versions/node/v16.20.0/bin/node
  Yarn:
    version: 1.22.19
    path: ~/.nvm/versions/node/v16.20.0/bin/yarn
  npm:
    version: 8.19.4
    path: ~/.nvm/versions/node/v16.20.0/bin/npm
  Watchman:
    version: 2023.07.10.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /usr/local/bin/pod
SDKs:
  iOS SDK: Not Found
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.2 AI-222.4459.24.2221.10121639
  Xcode:
    version: /undefined
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.20
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.3
    wanted: 0.72.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

 ~/Desktop/projects/0.72  main ?2                                                          ✔  12:07:15 

### Steps to reproduce

Just build the project

### Snack, screenshot, or link to a repository

I dont have a snack.

**Comment by vigyanhoon** [comment]
<img width="768" alt="image" src="https://github.com/facebook/react-native/assets/8503526/8d86b3bb-ca6e-4e14-a710-8da1e99e25f8">

Duplicate flipper file getting generated again and again.

**Comment by cortinico** [comment]
> I see lot of duplicate files getting created like build 2.gradle, settings 2.gradle. I event saw duplicate files in node modules and also saw Flipper 2.java. Not sure why this is happening after upgrade.

I don't know what's causing this, maybe your IDE or other tools. 
You should not have any `... 2.java` files at all so make sure you remove them.
