### ISSUE TITLE
[Android] How to call native method from javascript?

### ISSUE THREAD

**Issue by atom992** [facebook/react-native#3869]
Hi,all
I want to get the result from javascript of calling a native method. Not send a event to a native method. How can I do?

**Comment by hufeng** [comment]
like this,

```java
@ReactMethod
public void add(int a, int b, Callback callback) {
  callback.invoke(a + b);
}
```
js:
```javascript
XXXModule.add(1, 2, function(result) {
  console.log(result);
});
```

**Comment by atom992** [comment]
Thanks, I will try.

**Comment by mihirsoni** [comment]
@atom992 

Here is the complete tutorial how to expose NATIVE method to JS.

Please visit here :- https://facebook.github.io/react-native/docs/native-modules-android.html#content

From next time , please use http://stackoverflow.com/ with react-native tag , issues are limited only to issues.

**Comment by atom992** [comment]
ok,Thank you.
