### ISSUE TITLE
Dark NavigatorIOS

### ISSUE THREAD

**Issue by pwnsdx** [facebook/react-native#387]
I would like to set the background color of NavigatorIOS dark and text white, any idea of how to do this please? Thanks!

**Comment by iostalk** [comment]
I wanna do this

**Comment by pwnsdx** [comment]
:)

Here's an example:

**Comment by iostalk** [comment]
Where

**Comment by nim23** [comment]
I can only see the [tintColor] (https://github.com/facebook/react-native/blob/72d3d724a3a0c6bc46981efd0dad8f7f61121a47/Libraries/Components/Navigation/NavigatorIOS.ios.js#L550) being passed around and not [barTintColor] (https://github.com/facebook/react-native/blob/72d3d724a3a0c6bc46981efd0dad8f7f61121a47/Libraries/Components/Navigation/NavigatorIOS.ios.js#L46) so not sure if it is doable at the moment.

**Comment by pwnsdx** [comment]
Oops, I sent attachment via e-mail. It looks like GitHub do not accept it. Here is it:

![image1](https://cloud.githubusercontent.com/assets/2057765/6882109/1c1fe93a-d57b-11e4-88cf-7bb67b77694a.PNG)

@nim23: Both does not works :/

**Comment by nim23** [comment]
Pull request pending #318 for the bug.

**Comment by pwnsdx** [comment]
Sounds good!

**Comment by pwnsdx** [comment]
#318 looks accepted! Problem fixed.
