### ISSUE TITLE
[New Architecture]  iOS - Unable to read Text attribute from TextInput with testId

### ISSUE THREAD

**Issue by ravindraguptacapgemini** [facebook/react-native#38709]
### Description

Recently after migrating to new architecture we are facing issue in locating TextInput in the automation test cases. Specifically we are not able to read the text value and the length of text of a TextInput element in Appium test cases.

What exactly happening here is that with new architecture is setting the specified testID to TextInput's direct parent view (refer screenshot - **New Architecture - Value available on child of element with specified testID.png**) instead of setting it directly to the TextInput (as it works in old architecture, screenshot - **Old Architecture.png**).

### React Native Version

0.72.3

### Output of `npx react-native info`

System:
  OS: macOS 13.4.1
  CPU: (12) arm64 Apple M2 Pro
  Memory: 936.34 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 16.20.0
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 8.19.4
    path: /usr/local/bin/npm
  Watchman:
    version: 2023.06.26.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /Users/ravindragupta/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.2 AI-222.4459.24.2221.10121639
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.19
    path: /usr/bin/javac
  Ruby:
    version: 3.0.4
    path: /Users/ravindragupta/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.1
    wanted: 0.72.1
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: false
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: true

### Steps to reproduce

Add testId for TextInput and try to read text value from the element in automation test case (i.e. Appium)

### Snack, code example, screenshot, or link to a repository

<img width="1494" alt="Old Architecture" src="https://github.com/facebook/react-native/assets/97147467/faf6e179-f904-40ab-92e1-789fb580f9f3">

<img width="1094" alt="New Architecture - Value not available on element with specified testID" src="https://github.com/facebook/react-native/assets/97147467/ea63349f-53fd-498a-a723-fa0eb7341423">

<img width="1283" alt="New Architecture - Value available on child of element with specified testID" src="https://github.com/facebook/react-native/assets/97147467/60f6d641-d641-4773-8ed7-93e0c219e4c4">

Reproducer App Link: https://github.com/ravindraguptacapgemini/reproducer-react-native-maps-events/tree/layout-animation-issue

**Comment by ravindraguptacapgemini** [comment]
@cortinico please provide a path to look for the possible issue, I will try to fix it myself.

**Comment by ravindraguptacapgemini** [comment]
@cortinico I am ready to help here, can you please give me a hint of area to look for possible bug.

**Comment by ravindraguptacapgemini** [comment]
@cortinico found out that now with new architecture, the testID is mapped to accessibilityIdentifier of a native component, previously it was being mapped to accessibilityLabel, that's why the Appium was not able find the element (with accessibility-id).  

We were used to passed testID for iOS and accessibilityLabel for android but now have to used both for iOS, as:

export default function getAutomationID(automationID) {
 ```
 return Platform.OS === 'ios' ? { testID: automationID, accessibilityLabel: automationID } : { accessibilityLabel: automationID };
}
```

**Comment by umangdivyanshucapgemini** [comment]
@ravindraguptacapgemini @cortinico 
Here is another issue that I have observed after fabric enablement. For some of the icons, the name/accessibility id has changed to special characters. Attaching screenshots for reference.

**Before fabric enablement -** 
![image](https://github.com/facebook/react-native/assets/132474826/9c01e188-7bfb-4fc4-ae68-4f4e8821846e)

**After fabric enablement -** 
![image](https://github.com/facebook/react-native/assets/132474826/b4cc228a-8110-40d2-8d16-84586a80f2df)

**Comment by umangdivyanshucapgemini** [comment]
@cortinico Just checking if you got some time to check this? We are getting these issues throughout the application after the fabric upgrade. In addition to these issues, after setting the accessibility label we were able to find out the elements but the element's text is returning the accessibility id itself.

driver.find_element(:accessibility_id, 'urlField').text

![image](https://github.com/facebook/react-native/assets/132474826/3246e4bf-b9f8-426b-a180-56ced3c052c2)

Instead of "https://" we are getting "urlField"

**Comment by ravindraguptacapgemini** [comment]
@cortinico Do we have some update on this issue?

**Comment by cortinico** [comment]
> @cortinico Do we have some update on this issue?

Nope I'm sorry

**Comment by ravindraguptacapgemini** [comment]
@cortinico We have seen the child components are being arranged as siblings in the Dom hierarchy, does it has something to do with View Flattening or it's a bug in react native new architecture?

**Comment by ravindraguptacapgemini** [comment]
> > @cortinico Do we have some update on this issue?
> 
> Nope I'm sorry

Are you checking on these issue related to accessibility and end-to-end test, because there are lots of issues regarding locating elements. I know we are going to get major release 0.73, but can you please target this fix it in the coming releases?

**Comment by gedeagas** [comment]
Related Issues 
https://github.com/facebook/react-native/issues/43648

**Comment by cortinico** [comment]
This is probably fixed by: 
- https://github.com/facebook/react-native/pull/45003

Need to be cross checked in 0.75 and eventually closed.

**Comment by blakef** [comment]
I've reproduced this and confirmed it's a New Architecture specific issue.  Fix on the way.

**Comment by cortinico** [comment]
Fixed by https://github.com/facebook/react-native/pull/45379
