### ISSUE TITLE
How to use Android Intent.createChooser get gallery image

### ISSUE THREAD

**Issue by Emory-M** [facebook/react-native#3871]
I use startActivity can open gallery chooser, but I don't know how to get the image result
    
    Intent intent = new Intent(Intent.ACTION_GET_CONTENT);
    intent.setType("image/*");

    Intent chooser = Intent.createChooser(intent, "Choose a Picture");
    chooser.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
    this.reactContext.startActivity(chooser);

**Comment by PhilippKrone** [comment]
@Emory-M 

1) I think those questions should go to stackoverflow :)
2) You need to use startActivityWithResult combined with an implementation handleActivityResult, e.g.

````javascript
    @ReactMethod
    public void showImagePicker(final Callback callback) {
        mImageCallback = callback;
        Intent photoPickerIntent = new Intent(Intent.ACTION_PICK);
        photoPickerIntent.setType("image/*");
        mActivity.startActivityForResult(photoPickerIntent, 1);
    }
...
    public boolean handleActivityResult(final int requestCode, final int resultCode, final Intent data) {
        if (requestCode != 1) return false;
        if (resultCode == Activity.RESULT_OK) {
            try {
                Uri selectedImage = data.getData();
                ...
            } catch (Exception e) {

            }
        }
        return true;

    }
````

Please don't forget to pass the activityResult into your module

**Comment by Emory-M** [comment]
@PhilippKrone Thank you

I found a React Native module implemented the ImagePicker: 
https://github.com/marcshilling/react-native-image-picker

**Comment by Emory-M** [comment]
@PhilippKrone Thank you

I found a React Native module implemented the ImagePicker: 
https://github.com/marcshilling/react-native-image-picker
