### ISSUE TITLE
[iOS] JS Timers (setTimeout) don't fire when app is launched in background

### ISSUE THREAD

**Issue by mikelehen** [facebook/react-native#38711]
### Description

**Summary:**
Timers (setTimeout, etc.) don't run when iOS launches your React Native app in the background, because RCTTiming [initializes _inBackground=NO](https://github.com/facebook/react-native/blob/8bcfc493eae3686986372b3764995ba80e7e46fb/packages/react-native/React/CoreModules/RCTTiming.mm#L130).

**More detail**: https://github.com/facebook/react-native/pull/23674 added support for iOS timers to run when the app is in the background, but I believe I'm running into a case not covered by this code. In particular I'm implementing "[background updates](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/pushing_background_updates_to_your_app)" for my app. If the app is not running when the background update arrives (e.g. after a reboot, or presumably if iOS has killed the app to free resources), iOS will launch the app from scratch in the background (as opposed to the more normal background case of being launched in the foreground and then later transitioning to the background which is handled by [appDidMoveToBackground](https://github.com/facebook/react-native/blob/8bcfc493eae3686986372b3764995ba80e7e46fb/packages/react-native/React/CoreModules/RCTTiming.mm#L168)), and in this case timers (setTimeout, etc.) do not work.

It looks like if I change RCTTiming to initialize _inBackground=YES [here](https://github.com/facebook/react-native/blob/8bcfc493eae3686986372b3764995ba80e7e46fb/packages/react-native/React/CoreModules/RCTTiming.mm#L130), then my background code works as expected. But this isn't a good fix because in the normal foreground app launch case `_inBackground` will still be `YES` so it will end up using the "background" timers logic until you transition to background and then back to foreground.

I think the correct fix would be something like:

```
_inBackground = [UIApplication sharedApplication].applicationState == UIApplicationStateBackground;
```

But that can only be called from the main thread.  So you'd need to dispatch to the main thread, and I'm not sure how to do that safely without introducing race conditions.

**Vague repro:**
Sorry, to repro this you need to send specific push notifications from a backend server to the app. And you also need to potentially wait ~3 hours for iOS to run your background code.  So I can't provide a direct repro.

1. Per the [background updates](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/pushing_background_updates_to_your_app) docs, I've enabled the "Remote notifications" background mode on my app so iOS will run my app in the background for remote notification background updates.
2. I reboot my phone to make sure my app is not running in the background (I am assuming this could also happen if iOS has terminated the app to free resources, but rebooting is the best way I've found to test this).
3. I send a push notification from the backend to my app with "content-available=1" in order to trigger the background update code.
4. I wait ~3 hours for iOS to decide to run the background sync code (I don't know what heuristics iOS uses, but after a reboot it seems to be ~3 hours before it triggers).
3. iOS launches my app in the background and runs my [application(_:didReceiveRemoteNotification:fetchCompletionHandler:)](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1623013-application) delegate method.
4. I use that delegate to fire an `RCTEventEmitter` event that I listen for in JavaScript, in order to run my background update code.

**Result:** My JavaScript code handles that event and successfully runs in the background, but any calls to `setTimeout()` or `setInterval()` do not work (my callbacks never run).

### React Native Version

0.72.0

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
  OS: macOS 13.4
  CPU: (10) arm64 Apple M1 Max
  Memory: 72.59 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.16.0
    path: ~/.nvm/versions/node/v18.16.0/bin/node
  Yarn:
    version: 1.22.19
    path: ~/.yarn/bin/yarn
  npm:
    version: 9.5.1
    path: ~/.nvm/versions/node/v18.16.0/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods: Not Found
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.2 AI-222.4459.24.2221.9862592
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 20.0.1
    path: /usr/bin/javac
  Ruby:
    version: 3.2.2
    path: /opt/homebrew/opt/ruby/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.1
    wanted: ^0.72.0
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

### Steps to reproduce

Sorry, I am not providing specific repro steps since it would rely on backend code sending push notifications to the app.  My repro steps also rely on rebooting the device and waiting 3 hours, which isn't a very friendly repro. So I'm providing this bug in the hope that it is useful to somebody, but I understand it is not directly actionable.  I understand if that means this bug gets closed. At least it will be in the searchable history of the repro.

### Snack, screenshot, or link to a repository

Unavailable, sorry. See above.

**Comment by mikelehen** [comment]
In my case, I was able to work around it by adding this code to my app (e.g. in AppViewController.loadView()):

```
        let timing = bridge.loadModule(for: RCTTiming.self)
        if UIApplication.shared.applicationState == UIApplication.State.background {
            if timing.responds(to: Selector("appDidMoveToBackground")) {
                timing.perform(Selector("appDidMoveToBackground"))
            }
        }
```

**Comment by zhongwuzw** [comment]
@mikelehen Hi, I made a PR to fix this, please see #39347 , Does it work for you?

**Comment by mikelehen** [comment]
@zhongwuzw Thanks for making the PR!  Yes, it does work, though I am wondering if there's a potential race condition now that it's running async.  Left a comment on the PR.  Either fix (yours or the one I suggested) seems to resolve my use case though. Thanks for working on this!

**Comment by cheehieu** [comment]
@mikelehen, Did you also run into this issue on Android?

I am trying to implement remote background pushes to wake up my app when it is force quit. I have it mostly working using [rn-firebase](https://rnfirebase.io/messaging/usage#background-application-state) and this merged PR, but I noticed that a `setTimeout()` is not being called in my background handler on Android (via HeadlessJS task). It is working fine on iOS, but I realize the behavior is slightly different as it launches the entire app into the background.

**Comment by mikelehen** [comment]
@cheehieu Sorry, my react native app is iOS-only so I can't speak to any Android issues. Good luck!
