### ISSUE TITLE
Something strange with the console polyfill?

### ISSUE THREAD

**Issue by aphillipo** [facebook/react-native#38712]
### Description

Has anyone ever seen this, I'm super stumped, everything was working great.

error: node_modules/@react-native/js-polyfills/console.js: /Users/aphillipo/Code/startup/veloa/Veloa/node_modules/@react-native/js-polyfills/console.js: Cannot read properties of undefined (reading 'name')

I have tried everything from a full react native upgrade to commenting out huge parts of my codebase. Nothing seems to fix it unfortunately. Ideas welcome. A clean react native build works fine, but I really don't want to have to copy everything into a new RN repo.

### React Native Version

0.70.0 (upgraded to 0.72.3)

### Output of `npx react-native info`

System:
  OS: macOS 13.1
  CPU: (10) arm64 Apple M1 Max
  Memory: 785.64 MB / 32.00 GB
  Shell:
    version: 5.8.1
    path: /bin/zsh
Binaries:
  Node:
    version: 18.17.0
    path: ~/.nvm/versions/node/v18.17.0/bin/node
  Yarn:
    version: 1.22.19
    path: ~/.nvm/versions/node/v18.17.0/bin/yarn
  npm:
    version: 9.6.7
    path: ~/.nvm/versions/node/v18.17.0/bin/npm
  Watchman:
    version: 2023.06.12.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK:
    API Levels:
      - "29"
      - "30"
      - "32"
    Build Tools:
      - 29.0.2
      - 29.0.3
      - 30.0.2
      - 32.0.0
    System Images:
      - android-30 | Google Play ARM 64 v8a
      - android-32 | Google APIs ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2020.3 AI-203.7717.56.2031.7935034
  Xcode:
    version: 14.3/14E222b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 1.8.0_312
    path: /Users/aphillipo/.jenv/shims/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: false
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

### Steps to reproduce

Launch the app and try all the usual stuff of clearing caches etc.

### Snack, screenshot, or link to a repository

<img width="1194" alt="image" src="https://github.com/facebook/react-native/assets/52347/9054b46b-483a-4600-bfb0-be3020fb41e1">

**Comment by natanfeitosa** [comment]
Can you show the code? Maybe you are using an anonymous function, but the RN console polyfill requires a named function in your case

**Comment by aphillipo** [comment]
Well it’s a whole project that I can’t really just drop in here, I’ll take a branch and rip everything out and then we’ll see I guess 🤷🏻‍♂️

**Comment by liplylie** [comment]
Was able to resolve this by removing some unneeded babel dev dependencies. 

My team has a pretty old react-native project, and we needed to change the config for some babel packages to work with libraries in the past.

Removing the babel plugin libraries, as well as preset-env worked
