### ISSUE TITLE
selectable property on text component is not working on oppo and samsung devices.

### ISSUE THREAD

**Issue by neo-karishmakavankar** [facebook/react-native#38722]
### Description

I have tested it on other real devices and emulators, and Selectable is working fine on it. whereas when I tried to tap and hold to select the text it didn't work on Oppo and Samsung devices.

### React Native Version

0.71.11

### Output of `npx react-native info`

System:
    OS: macOS 13.3
    CPU: (8) x64 Apple M1
    Memory: 22.56 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.3.1 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/Desktop/myProject/node_modules/.bin/yarn
    npm: 9.6.7 - /usr/local/bin/npm
    Watchman: 2023.06.12.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /Users/neosoft/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9619390
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.19 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.11 => 0.71.11 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

add a selectable true text component

<Text selectable={true} >You can select me</Text>

### Snack, screenshot, or link to a repository

.

**Comment by cortinico** [comment]
> Snack, screenshot, or link to a repository

Reproducers are mandatory. Can you please provide it?

**Comment by fabriziobertoglio1987** [comment]
Do you still experience this issue? 

I have four years of experience maintaining facebook/react-native and I specialize in the Text and TextInput components. I currently have 58 [facebook/react-native PRs](https://github.com/facebook/react-native/pulls?q=is%3Apr+author%3Afabriziobertoglio1987+). 

If you still experience this issue, I will prepare a patched release with the fix.

Thanks a lot
