### ISSUE TITLE
viewabilityConfig viewAreaCoveragePercentThreshold is actually related to view height only

### ISSUE THREAD

**Issue by fcole90** [facebook/react-native#38721]
### Description

Components based on [VirtualizedList](https://github.com/facebook/react-native/blob/main/packages/virtualized-lists/Lists/VirtualizedList.js) (such as FlatList), accept a `viewabilityConfig` prop. The config then has a `viewAreaCoveragePercentThreshold` prop [described as](https://reactnative.dev/docs/flatlist#viewareacoveragepercentthreshold)

> Percent of viewport that must be covered for a partially occluded item to count as "viewable", 0-100. Fully visible items are always considered viewable. A value of 0 means that a single pixel in the viewport makes the item viewable, and a value of 100 means that an item must be either entirely visible or cover the entire viewport to count as viewable.

However, in my experiments, it doesn't look like this is based on the area, but on the viewport height alone, and checking the source it looks like [I might be right](https://github.com/facebook/react-native/blob/bfd5fe27b302c5483f929bd2f730d1b4f3915b80/packages/virtualized-lists/Lists/ViewabilityHelper.js#L312).

If this is the case, I suggest updating the comment and documentation to clarify this detail, as it can make a big impact depending on how items are displayed in the list (e.g. when an item doesn't fill the whole width) or based on the scroll direction of the list (what happens when the list scrolls horizontally).

### React Native Version

0.72.0 and most likely previous versions as well

### Output of `npx react-native info`

Doesn't matter for this issue.

### Steps to reproduce

Double-check the code at https://github.com/facebook/react-native/blob/bfd5fe27b302c5483f929bd2f730d1b4f3915b80/packages/virtualized-lists/Lists/ViewabilityHelper.js#L312 and verify if the "area" is actually just height.

### Snack, screenshot, or link to a repository

https://github.com/facebook/react-native/blob/bfd5fe27b302c5483f929bd2f730d1b4f3915b80/packages/virtualized-lists/Lists/ViewabilityHelper.js#L312

**Comment by fcole90** [comment]
> ⚠️	Missing Reproducible Example
> ℹ️	We could not detect a reproducible example in your issue report. Please provide either:
> * If your bug is UI related: a [Snack](https://snack.expo.dev)
> * If your bug is build/update related: use our [Reproducer Template](https://github.com/react-native-community/reproducer-react-native/generate). A reproducer needs to be in a GitHub repository under your username.

No example needed, I think. Let me know if you think otherwise, I'll work one out 😊

**Comment by cortinico** [comment]
> If this is the case, I suggest updating the comment and documentation to clarify this detail, as it can make a big impact depending on how items are displayed in the list (e.g. when an item doesn't fill the whole width) or based on the scroll direction of the list (what happens when the list scrolls horizontally).

Could you open a PR against: https://github.com/facebook/react-native-website and let's move the conversation there (also from the technical standpoint).
