### ISSUE TITLE
image will be stretched when borderRadius appears

### ISSUE THREAD

**Issue by developerpritam** [facebook/react-native#38725]
### Description

When borderRadius is included in <Image /> style, the entire image range will be forced to fill according to resizeMode.

Example Image
<Image
    source={{ uri: 'image_url' }}
    style={{ height: 200, borderRadius: 10 }}
    resizeMethod={"auto"}
    resizeMode={'contain'}
/>

This problem appeared in 0.72 Version

Version
0.72

### React Native Version

0.72

### Output of `npx react-native info`

When borderRadius is included in <Image /> style, the entire image range will be forced to fill according to resizeMode.

Example Image
<Image
    source={{ uri: 'image_url' }}
    style={{ height: 200, borderRadius: 10 }}
    resizeMethod={"auto"}
    resizeMode={'contain'}
/>

This problem appeared in 0.72 Version

Version
0.72

### Steps to reproduce

image not show properly while using border radius in image tag

### Snack, screenshot, or link to a repository

https://lightrun.com/answers/facebook-react-native-image-will-be-stretched-when-borderradius-appears

https://user-images.githubusercontent.com/93700457/175787669-f9f74112-cda0-4ce1-bd61-6d6ce7f947a8.png

**Comment by cortinico** [comment]
Can you provide a repro or a code snippet and not links to other resources please?
