### ISSUE TITLE
Crash cause:com.facebook.react.bridge.RetryableMountingLayerException: Unable to find viewState for tag

### ISSUE THREAD

**Issue by LiuLeiThreestone** [facebook/react-native#38743]
### Description

app crash while starting:
com.facebook.react.fabric.mounting.SurfaceMountingManager.getViewState (SurfaceMountingManager.java:968)
com.facebook.react.fabric.mounting.SurfaceMountingManager.addViewAt (SurfaceMountingManager.java:310)
com.facebook.react.fabric.mounting.mountitems.IntBufferBatchMountItem.execute (IntBufferBatchMountItem.java:153)
com.facebook.react.fabric.mounting.MountItemDispatcher.executeOrEnqueue (MountItemDispatcher.java:352)
com.facebook.react.fabric.mounting.MountItemDispatcher.dispatchMountItems (MountItemDispatcher.java:275)
com.facebook.react.fabric.mounting.MountItemDispatcher.tryDispatchMountItems (MountItemDispatcher.java:120)
com.facebook.react.fabric.FabricUIManager$DispatchUIFrameCallback.doFrameGuarded (FabricUIManager.java:1163)
com.facebook.react.fabric.GuardedFrameCallback.doFrame (GuardedFrameCallback.java:31)
com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame (ReactChoreographer.java:175)
com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame (ChoreographerCompat.java:85)
android.view.Choreographer$CallbackRecord.run (Choreographer.java:1386)
android.view.Choreographer$CallbackRecord.run (Choreographer.java:1396)
android.view.Choreographer.doCallbacks (Choreographer.java:1033)
android.view.ChoreographerExtImpl.checkScrollOptSceneEnable (ChoreographerExtImpl.java:411)
android.view.Choreographer.doFrame (Choreographer.java:900)
android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:1371)
android.os.Handler.handleCallback (Handler.java:942)
android.os.Handler.dispatchMessage (Handler.java:99)
android.os.Looper.loopOnce (Looper.java:240)
android.os.Looper.loop (Looper.java:351)
android.app.ActivityThread.main (ActivityThread.java:8381)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:584)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1013)

### React Native Version

0.72.0

### Output of `npx react-native info`

System:
OS: macOS 12.3
CPU: (10) arm64 Apple M1 Pro
Memory: 103.38 MB / 32.00 GB
Shell: 5.8 - /bin/zsh
Binaries:
Node: 14.21.3 - /opt/homebrew/opt/node@14/bin/node
Yarn: 1.22.19 - /opt/homebrew/bin/yarn
npm: 6.14.18 - /opt/homebrew/opt/node@14/bin/npm
Watchman: 2023.05.08.00 - /opt/homebrew/bin/watchman
Managers:
CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
SDKs:
iOS SDK:
Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
Android SDK: Not Found
IDEs:
Android Studio: 2022.1 AI-221.6008.13.2211.9619390
Xcode: 13.4/13F17a - /usr/bin/xcodebuild
Languages:
Java: 11.0.17 - /usr/bin/javac
npmPackages:
@react-native-community/cli: Not Found
react: 18.2.0 => 18.2.0
react-native: 0.72.0 => 0.72.0
react-native-macos: Not Found
npmGlobalPackages:
react-native: Not Found
Android:
hermesEnabled: true
newArchEnabled: true
iOS:
hermesEnabled: true
newArchEnabled: true

### Steps to reproduce

start app

### Snack, code example, screenshot, or link to a repository

app crash while starting:
com.facebook.react.fabric.mounting.SurfaceMountingManager.getViewState (SurfaceMountingManager.java:968)
com.facebook.react.fabric.mounting.SurfaceMountingManager.addViewAt (SurfaceMountingManager.java:310)
com.facebook.react.fabric.mounting.mountitems.IntBufferBatchMountItem.execute (IntBufferBatchMountItem.java:153)
com.facebook.react.fabric.mounting.MountItemDispatcher.executeOrEnqueue (MountItemDispatcher.java:352)
com.facebook.react.fabric.mounting.MountItemDispatcher.dispatchMountItems (MountItemDispatcher.java:275)
com.facebook.react.fabric.mounting.MountItemDispatcher.tryDispatchMountItems (MountItemDispatcher.java:120)
com.facebook.react.fabric.FabricUIManager$DispatchUIFrameCallback.doFrameGuarded (FabricUIManager.java:1163)
com.facebook.react.fabric.GuardedFrameCallback.doFrame (GuardedFrameCallback.java:31)
com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame (ReactChoreographer.java:175)
com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame (ChoreographerCompat.java:85)
android.view.Choreographer$CallbackRecord.run (Choreographer.java:1386)
android.view.Choreographer$CallbackRecord.run (Choreographer.java:1396)
android.view.Choreographer.doCallbacks (Choreographer.java:1033)
android.view.ChoreographerExtImpl.checkScrollOptSceneEnable (ChoreographerExtImpl.java:411)
android.view.Choreographer.doFrame (Choreographer.java:900)
android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:1371)
android.os.Handler.handleCallback (Handler.java:942)
android.os.Handler.dispatchMessage (Handler.java:99)
android.os.Looper.loopOnce (Looper.java:240)
android.os.Looper.loop (Looper.java:351)
android.app.ActivityThread.main (ActivityThread.java:8381)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:584)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1013)

**Comment by cortinico** [comment]
Can you share:
1. the full crash log. What you have here is truncated
2. a reproducer for the crash

**Comment by LiuLeiThreestone** [comment]
1、the crash log are all above
2、the crash are occasional
3、i wonder know,in what case, the source code of "SurfaceMountingManager.addViewAt "and "SurfaceMountingManager.getViewState"may cause throw new RetryableMountingLayerException("Unable to find viewState for tag " + tag);
app crash while starting:
com.facebook.react.fabric.mounting.SurfaceMountingManager.getViewState (SurfaceMountingManager.java:968)
com.facebook.react.fabric.mounting.SurfaceMountingManager.addViewAt (SurfaceMountingManager.java:310)
com.facebook.react.fabric.mounting.mountitems.IntBufferBatchMountItem.execute (IntBufferBatchMountItem.java:153)
com.facebook.react.fabric.mounting.MountItemDispatcher.executeOrEnqueue (MountItemDispatcher.java:352)
com.facebook.react.fabric.mounting.MountItemDispatcher.dispatchMountItems (MountItemDispatcher.java:275)
com.facebook.react.fabric.mounting.MountItemDispatcher.tryDispatchMountItems (MountItemDispatcher.java:120)
com.facebook.react.fabric.FabricUIManager$DispatchUIFrameCallback.doFrameGuarded (FabricUIManager.java:1163)
com.facebook.react.fabric.GuardedFrameCallback.doFrame (GuardedFrameCallback.java:31)
com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame (ReactChoreographer.java:175)
com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame (ChoreographerCompat.java:85)
android.view.Choreographer$CallbackRecord.run (Choreographer.java:1386)
android.view.Choreographer$CallbackRecord.run (Choreographer.java:1396)
android.view.Choreographer.doCallbacks (Choreographer.java:1033)
android.view.ChoreographerExtImpl.checkScrollOptSceneEnable (ChoreographerExtImpl.java:411)
android.view.Choreographer.doFrame (Choreographer.java:900)
android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:1371)
android.os.Handler.handleCallback (Handler.java:942)
android.os.Handler.dispatchMessage (Handler.java:99)
android.os.Looper.loopOnce (Looper.java:240)
android.os.Looper.loop (Looper.java:351)
android.app.ActivityThread.main (ActivityThread.java:8381)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:584)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1013)

**Comment by cortinico** [comment]
Without a stable reproducer, this is practically impossible to fix

**Comment by cortinico** [comment]
Closing as the author provided no reproducer

**Comment by fawaz-ahmed** [comment]
Facing this issue in rn version 0.76.5. Stacktrace:
`Exception com.facebook.react.bridge.RetryableMountingLayerException:
  at com.facebook.react.fabric.mounting.SurfaceMountingManager.getViewState (SurfaceMountingManager.java:1111)
  at com.facebook.react.fabric.mounting.SurfaceMountingManager.addViewAt (SurfaceMountingManager.java:360)
  at com.facebook.react.fabric.mounting.mountitems.IntBufferBatchMountItem.execute (IntBufferBatchMountItem.java:119)
  at com.facebook.react.fabric.mounting.MountItemDispatcher.executeOrEnqueue (MountItemDispatcher.java:387)
  at com.facebook.react.fabric.mounting.MountItemDispatcher.dispatchMountItems (MountItemDispatcher.java:293)
  at com.facebook.react.fabric.mounting.MountItemDispatcher.tryDispatchMountItems (MountItemDispatcher.java:126)
  at com.facebook.react.fabric.FabricUIManager$DispatchUIFrameCallback.doFrameGuarded (FabricUIManager.java:1394)
  at com.facebook.react.fabric.GuardedFrameCallback.doFrame (GuardedFrameCallback.kt:22)
  at com.facebook.react.modules.core.ReactChoreographer.frameCallback$lambda$1 (ReactChoreographer.kt:60)
  at android.view.Choreographer$CallbackRecord.run (Choreographer.java:1153)
  at android.view.Choreographer.doCallbacks (Choreographer.java:946)
  at android.view.Choreographer.doFrame (Choreographer.java:857)
  at android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:1140)
  at android.os.Handler.handleCallback (Handler.java:938)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loopOnce (Looper.java:201)
  at android.os.Looper.loop (Looper.java:288)
  at android.app.ActivityThread.main (ActivityThread.java:8077)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:568)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1047)`

**Comment by fawaz-ahmed** [comment]
Issue still persists with rn version `0.76.6`

**Comment by anyaSychugina** [comment]
Any news regarding this?
Also had the same issue on android. React Native Version is 0.76.6 
with new architecture

**Comment by steavenb** [comment]
Received similar Sentry errors from devices running Android 12. Cannot be produced on my side but there was a pattern - it occurred on devices with low RAM (2GB) ram. The devices on which it occurred were a ZTE P630 and a Vivo V2118.

**Comment by patilmahantesh67** [comment]
What I found out was, I was on react-navigation version 6 and when I upgraded the nested back buttons started to fail
https://reactnavigation.org/docs/upgrading-from-6.x
In this document it is clearly said that nested navigation support will not be provided in version 7 onwards of reactnavigation.

So when I created a separate Navigator for each of the nested ones the issue got resolved.

**Comment by dcorbin** [comment]
I've had something very similar (could be exactly the same) to this showing up frequently for 1 user
```Exception com.facebook.jni.CppException:
  at com.facebook.react.fabric.mounting.SurfaceMountingManager.getViewState (SurfaceMountingManager.java:1103)
  at com.facebook.react.fabric.mounting.SurfaceMountingManager.updateProps (SurfaceMountingManager.java:688)
  at com.facebook.react.fabric.mounting.mountitems.IntBufferBatchMountItem.execute (IntBufferBatchMountItem.java:145)
  at com.facebook.react.fabric.mounting.MountItemDispatcher.executeOrEnqueue (MountItemDispatcher.java:370)
  at com.facebook.react.fabric.mounting.MountItemDispatcher.dispatchMountItems (MountItemDispatcher.java:265)
  at com.facebook.react.fabric.mounting.MountItemDispatcher.tryDispatchMountItems (MountItemDispatcher.java:122)
  at com.facebook.react.fabric.FabricUIManager$3.runGuarded (FabricUIManager.java:823)
  at com.facebook.react.bridge.GuardedRunnable.run (GuardedRunnable.java:29)
  at com.facebook.react.fabric.FabricUIManager.scheduleMountItem (FabricUIManager.java:827)
  at com.swmansion.worklets.AndroidUIScheduler.triggerUI
  at com.swmansion.worklets.AndroidUIScheduler.lambda$new$0 (AndroidUIScheduler.java:28)
  at com.swmansion.worklets.AndroidUIScheduler.$r8$lambda$Owjjhl033zNSHsU6ZfWQNbZEGbI (Unknown Source)
  at com.swmansion.worklets.AndroidUIScheduler$$ExternalSyntheticLambda0.run (D8$$SyntheticClass)
  at com.swmansion.worklets.AndroidUIScheduler$1.runGuarded (AndroidUIScheduler.java:49)
  at com.facebook.react.bridge.GuardedRunnable.run (GuardedRunnable.java:29)
  at android.os.Handler.handleCallback (Handler.java:959)
  at android.os.Handler.dispatchMessage (Handler.java:100)
  at android.os.Looper.loopOnce (Looper.java:257)
  at android.os.Looper.loop (Looper.java:342)
  at android.app.ActivityThread.main (ActivityThread.java:9634)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:619)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:929)```

## npx react-native info
```info Fetching system and libraries information...
System:
  OS: macOS 15.5
  CPU: (10) arm64 Apple M1 Max
  Memory: 651.39 MB / 64.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.19.0
    path: ~/.nvm/versions/node/v20.19.0/bin/node
  Yarn:
    version: 3.6.1
    path: ~/.nvm/versions/node/v20.19.0/bin/yarn
  npm:
    version: 10.8.2
    path: ~/.nvm/versions/node/v20.19.0/bin/npm
  Watchman:
    version: 2024.12.02.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.16.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.5
      - iOS 18.5
      - macOS 15.5
      - tvOS 18.5
      - visionOS 2.5
      - watchOS 11.5
  Android SDK: Not Found
IDEs:
  Android Studio: 2025.1 AI-251.25410.109.2511.13665796
  Xcode:
    version: 16.4/16F6
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.9
    path: /Users/dcorbin/.jenv/shims/javac
  Ruby:
    version: 3.4.1
    path: /Users/dcorbin/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 15.1.3
    wanted: ^15.0.1
  react:
    installed: 19.0.0
    wanted: 19.0.0
  react-native:
    installed: 0.79.4
    wanted: 0.79.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

info React Native v0.80.1 is now available (your project is running on v0.79.4).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.80.1
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.79.4&to=0.80.1
info For more info, check out "https://reactnative.dev/docs/upgrading?os=macos".
```

Gemini suggested it might be worklet releated. (my app heavily uses react-native-renaimated, though nothing 'custom' and my one worklet is very minimal).

I'm a touch out-of-date on some libraries, including RN and will upgrade and see if it continues.

**Comment by akshayshedgehusk** [comment]
+1.

**Comment by akshayshedgehusk** [comment]
100% on android 12 devices with vivo mobiles
