### ISSUE TITLE
MainActivity.java:47: error: method does not override or implement a method from a supertype @Override ^

### ISSUE THREAD

**Issue by DomnicAmalan** [facebook/react-native#38744]
### Description

`@Override
    protected boolean isConcurrentRootEnabled() {
      // If you opted-in for the New Architecture, we enable Concurrent Root (i.e.
      // React 18).
      // More on this on https://reactjs.org/blog/2022/03/29/react-v18.html
      return BuildConfig.IS_NEW_ARCHITECTURE_ENABLED;
    }`

### React Native Version

0.72.3

### Output of `npx react-native info`

System:
  OS: macOS 13.4.1
  CPU: (10) arm64 Apple M1 Max
  Memory: 2.27 GB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 16.15.1
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.19
    path: /usr/local/bin/yarn
  npm:
    version: 8.11.0
    path: /usr/local/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.12.1
    path: /Users/dommnicamalan/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK:
    API Levels:
      - "27"
      - "30"
      - "31"
      - "32"
      - "33"
    Build Tools:
      - 29.0.2
      - 30.0.3
      - 31.0.0
      - 33.0.0
    System Images:
      - android-33 | Google APIs ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2021.2 AI-212.5712.43.2112.8609683
  Xcode:
    version: 14.3/14E222b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 18.0.1.1
    path: /usr/bin/javac
  Ruby:
    version: 2.7.5
    path: /Users/dommnicamalan/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: ^18.2.0
  react-native:
    installed: 0.72.3
    wanted: ^0.72.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

### Steps to reproduce

yarn android

### Snack, code example, screenshot, or link to a repository

<img width="1344" alt="Screenshot 2023-08-02 at 9 25 48 AM" src="https://github.com/facebook/react-native/assets/21099294/9e6d201b-d967-4a1f-8749-072932b1bd9b">

**Comment by cortinico** [comment]
Can you share:
1. The full build log (**not** as an image)
2. The `MainActivity.java` file?

**Comment by samarth25992** [comment]
did you find the solution for it? I am facing the same issue. I am trying to update RN version from 0.68.3 to 0.70.0. I did all the changes listed in https://react-native-community.github.io/upgrade-helper/?from=0.68.3&to=0.70.0

**Comment by cortinico** [comment]
Closing as @DomnicAmalan is unresponsive
