### ISSUE TITLE
WARNING reanimated - no version-specific reanimated AAR for react-native version 72 found.

### ISSUE THREAD

**Issue by priyaWedo** [facebook/react-native#38751]
### Description

WARNING reanimated - no version-specific reanimated AAR for react-native version 72 found.
Falling back to AAR for react-native version 71.
The react-native JSI interface is not ABI-safe yet, this may result in crashes.
Please post a pull request to implement support for react-native version 72 to the reanimated repo.
Thanks!

### React Native Version

0.72.1

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
  OS: macOS 13.4
  CPU: (8) arm64 Apple M2
  Memory: 64.00 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.3.0
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 9.7.1
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2023.05.22.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /Users/priyabapodra/.rvm/gems/ruby-3.0.0/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.2
      - iOS 16.2
      - macOS 13.1
      - tvOS 16.1
      - watchOS 9.1
  Android SDK:
    API Levels:
      - "10"
      - "11"
      - "12"
      - "13"
      - "14"
      - "15"
      - "16"
      - "17"
      - "18"
      - "19"
      - "20"
      - "21"
      - "22"
      - "23"
      - "24"
      - "25"
      - "26"
      - "27"
      - "28"
      - "29"
      - "30"
      - "31"
      - "32"
      - "33"
      - "33"
      - "33"
      - "34"
      - "7"
      - "8"
      - "9"
    Build Tools:
      - 29.0.2
      - 30.0.2
      - 30.0.3
      - 33.0.0
      - 33.0.1
      - 33.0.2
      - 34.0.0
      - 34.0.0
    Android NDK: 22.1.7171670
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10406996
  Xcode:
    version: 14.2/14C18
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.8
    path: /usr/bin/javac
  Ruby:
    version: 3.0.0
    path: /Users/priyabapodra/.rvm/rubies/ruby-3.0.0/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.1
    wanted: 0.72.1
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: false
  newArchEnabled: false

### Steps to reproduce

npx react-native run-android 

### Snack, code example, screenshot, or link to a repository

https://github.com/software-mansion/react-native-reanimated/discussions/3461

**Comment by cortinico** [comment]
Hi @priyaWedo 
Thanks for reporting this issue.

It seems like this issue is actually unrelated to React Native core but related to Reanimated. Please open this issue against this other repository:

https://github.com/software-mansion/react-native-reanimated/issues

I'll be closing this but feel free to reopen if the other repo points back to us as a issue in the core of React Native.
