### ISSUE TITLE
Codegen chokes on imported types

### ISSUE THREAD

**Issue by birdofpreyru** [facebook/react-native#38769]
### Description

It seems codegen currently chokes on types imported from a different module, _i.e._ consider this example:
```ts
// types.ts
export type MyType = {
  field: string;
};

// NativeReactNativeMyModule.ts
import type { TurboModule } from 'react-native';
import { TurboModuleRegistry } from 'react-native';

import { type MyType } from './types';

export interface Spec extends TurboModule {
  myMethod(arg: MyType): void;
}

export default TurboModuleRegistry.getEnforcing<Spec>('ReactNativeMyModule');
```

When running the build (for Android on Ubuntu system) the codegen chokes on the method definition saying `UnsupportedGenericParserError: Module NativeReactNativeMyModule: Unrecognized generic type 'MyType' in NativeModule spec.`

This equivalent code works fine though:
```ts
import type { TurboModule } from 'react-native';
import { TurboModuleRegistry } from 'react-native';

export type MyType = {
  field: string;
};

export interface Spec extends TurboModule {
  myMethod(arg: MyType): void;
}

export default TurboModuleRegistry.getEnforcing<Spec>('ReactNativeMyModule');
```

### React Native Version

v0.72.3

### Output of `npx react-native info`

N/A

### Steps to reproduce

N/A

### Snack, code example, screenshot, or link to a repository

N/A

**Comment by cipolleschi** [comment]
Yes, that is a currently known limitation of codegen. The (very ugly) workaround is to copy-and-paste the types you need in the module definition. 

We are currently working on solving this, so it will be hopefully available soon.

cc. @dmytrorykun

**Comment by FouadMagdy01** [comment]
@cipolleschi  any updates about this ?
I am having this issue while i was trying to build a library using react-native-builder-bob

I had to hardcode all my types in one file and this is very disgusting  tbh

**Comment by cipolleschi** [comment]
I know it is very disgusting, but unfortunately the issue is not trivial. Importing types from other files in Codegen requires some refactoring and crawling the files has some implications that we need to be careful about.

Unfortunately, we haven't set aside any time to work on this in the next future.

**Comment by FouadMagdy01** [comment]
@cipolleschi thank you for your reply

No problem for now, i think we can handle this for now it is not breaking 
My problem is that i spent 6 hours of debugging this to find a solution 😂

**Comment by eithe** [comment]
Are there any plans for this? Been a few years :D
