### ISSUE TITLE
如何在安卓TV元素被选择的时候加一些样式提示用户当前元素已经被选择

### ISSUE THREAD

**Issue by renjiali** [facebook/react-native#38766]
### Description

![image](https://github.com/facebook/react-native/assets/94222668/9f2fc714-f05d-4511-a4ad-0e7324b4e875)
![image](https://github.com/facebook/react-native/assets/94222668/0634af38-553a-4abc-9c43-32a4e070b756)
加一个白色边框，提示用户
部分代码
import {Dimensions, Image, Text, Pressable, View} from 'react-native';
import LinearGradient from 'react-native-linear-gradient';
import {FoodCardProps} from './types.d';
import {baseUrl} from '@/config';
const window = Dimensions.get('window');
const scale = window.width / 1920;
export const FoodCard = (props: FoodCardProps) => {
  return (
    <Pressable
      style={[
        props.style,
        {
          position: 'relative',
          marginBottom: 32 * scale,
          elevation: 1,
        },
      ]}
      android_disableSound={false}
      android_ripple={{foreground: true, borderless: false}}>
      <View>
        <Image
          style={{width: 564 * scale, height: 282 * scale}}
          source={{uri: baseUrl + props.data.image}}></Image>
        <LinearGradient
          colors={['#00B1FF', '#0BCAFF', '#3EF2B6']}
          start={{x: 0, y: 0}}
          end={{x: 1, y: 0}}
          style={{
            width: 564 * scale,
            height: 216 * scale,
            padding: 32 * scale,
          }}>
          <Text
            style={{
              fontFamily: 'PingFangSC-Medium',
              fontSize: 40 * scale,
              color: '#fff',
              letterSpacing: 0,
              lineHeight: 50 * scale,
              fontWeight: '500',
              marginBottom: 10 * scale,
            }}>
            {props.data.name}
          </Text>
          <View
            style={{
              display: 'flex',
              flexDirection: 'row',
              alignItems: 'center',
              marginRight: 16 * scale,
            }}>
            {props.data.tags.map(tag => {
              return (
                <Text
                  style={{
                    borderWidth: 1.5 * scale,
                    borderRadius: 22 * scale,
                    borderColor: 'rgba(255,255,255,0.4)',
                    paddingHorizontal: 15 * scale,
                    paddingVertical: 6 * scale,
                    marginRight: 16 * scale,
                    color: '#fff',
                  }}
                  key={tag}>
                  {tag}
                </Text>
              );
            })}
          </View>
          <Text
            style={{
              fontFamily: 'PingFangSC-Medium',
              fontSize: 28 * scale,
              color: '#fff',
              letterSpacing: 0,
              lineHeight: 32 * scale,
              fontWeight: '400',
              marginTop: 24 * scale,
            }}>
            {props.data.shop_name}
          </Text>

          <Text
            style={{
              position: 'absolute',
              bottom: 12 * scale,
              right: 16 * scale,
              fontFamily: 'PingFangSC-Medium',
              fontSize: 44 * scale,
              color: '#fff',
              letterSpacing: 0,
              lineHeight: 44 * scale,
              fontWeight: '900',
            }}>
            ¥ {props.data.price}
          </Text>
        </LinearGradient>
      </View>
    </Pressable>
  );
};

### React Native Version

0.72.3

### Output of `npx react-native info`

或者可以告诉我一下第三方库也可以

### Steps to reproduce

谢谢

### Snack, code example, screenshot, or link to a repository

感谢

**Comment by renjiali** [comment]
> ⚠️	Missing Reproducible Example
> ℹ️	We could not detect a reproducible example in your issue report. Please provide either:
> * If your bug is UI related: a [Snack](https://snack.expo.dev)
> * If your bug is build/update related: use our [Reproducer Template](https://github.com/react-native-community/reproducer-react-native/generate). A reproducer needs to be in a GitHub repository under your username.

已经给了，不需要示例，看设计稿即可  ，就是被划过 加一个被选中的样式

**Comment by cortinico** [comment]
Hi @renjiali 
In this issue tracker we accept only issues that are in English.
I'm closing this for now, please consider translating it to English and reopening it.
Thanks.
