### ISSUE TITLE
Why when React Native 0.68.2 requests external API endpoints gets the responses with delay?

### ISSUE THREAD

**Issue by AliBahaari** [facebook/react-native#38760]
### Description

- React Native Version: 0.68.2
- Axios Version: 1.4.0

Hello everyone! I've been developing an app with React Native. Also, I've developed API endpoints with Express.js.
The problem is when I request to the API endpoints locally, it works like a charm and everything is well. But when I deploy it to a VPS, it requests and show me the response with a long delay. I considered it may be my API endpoints fault, so I copied this snippet from React Native docs:
```javascript
  useEffect(() => {
    async function request() {
      try {
        const response = await fetch('https://reactnative.dev/movies.json');
        const json = await response.json();
        console.log(json.movies);
      } catch (error) {
        console.error(error);
      }
    }

    request();
  }, []);
```
First, it seems it doesn't do anything.
One hour later, I found out that the response is logged.

Even, I checked version 0.72.3 out but everything was the same.

What's the problem? Why it doesn't interact immediately with external API endpoints? Please guide me by your knowledge. 

### React Native Version

0.68.2

### Output of `npx react-native info`

  System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-4702MQ CPU @ 2.20GHz
    Memory: 1.16 GB / 11.76 GB

  Binaries:
    Node: 16.20.0 - D:\NodeJS\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.4 - D:\NodeJS\npm.CMD
    Watchman: Not Found

  SDKs:
    Android SDK:
      API Levels: 31, 33
      Build Tools: 30.0.2, 30.0.3, 31.0.0, 33.0.0
      System Images: android-33 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
    Windows SDK: Not Found

  IDEs:
    Android Studio: Not Found
    Visual Studio: 17.4.33213.308 (Visual Studio Community 2022)

  Languages:
    Java: 18.0.2 - C:\Program Files\Common Files\Oracle\Java\javapath\javac.EXE     

  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.68.2 => 0.68.2
    react-native-windows: Not Found

  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. Request to an external API endpoint
2. It doesn't do anything
3. After a while, it shows me the response

### Snack, screenshot, or link to a repository

Nothing

**Comment by JKKholmatov** [comment]
@AliBahaari Hi! I'm also having this problem, fetch sends a request after ~2 minutes, did you find a solution?

**Comment by AliBahaari** [comment]
Not actually
But when I tried it multiple times, it corrected nicely.
