### ISSUE TITLE
UI breaks on rendering after enable new architecture

### ISSUE THREAD

**Issue by meghvarse** [facebook/react-native#38773]
### Description

Used bottom sheet as parent, screen is inside the createStackNavigator (react-navigation version 4.4.4). UI breaks on rendering after enable new architecture.

### React Native Version

0.72.3

### Output of `npx react-native info`

System:
  OS: macOS 13.3.1
  CPU: (8) arm64 Apple M1
  Memory: 78.75 MB / 8.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 16.13.2
    path: ~/.nvm/versions/node/v16.13.2/bin/node
  Yarn:
    version: 1.22.18
    path: /usr/local/bin/yarn
  npm:
    version: 8.1.2
    path: ~/.nvm/versions/node/v16.13.2/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.12.1
    path: /Users/abc/.rvm/rubies/ruby-3.0.0/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK:
    API Levels:
      - "23"
      - "28"
      - "29"
      - "30"
      - "31"
      - "32"
      - "33"
    Build Tools:
      - 28.0.3
      - 29.0.2
      - 30.0.2
      - 30.0.3
      - 31.0.0
      - 32.0.0
      - 33.0.0
      - 34.0.0
    System Images:
      - android-32 | Google APIs ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2022.1 AI-221.6008.13.2211.9619390
  Xcode:
    version: 14.3/14E222b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.2
    path: /usr/bin/javac
  Ruby:
    version: 3.0.0
    path: /Users/abc/.rvm/rubies/ruby-3.0.0/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: ^18.2.0
  react-native:
    installed: 0.72.3
    wanted: ^0.72.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: true

### Steps to reproduce

Open layout multiple times and UI breaks.

### Snack, code example, screenshot, or link to a repository

https://github.com/facebook/react-native/assets/140066955/c76a7464-a48c-40d0-aa35-c56fe51a586d

**Comment by cortinico** [comment]
> Used bottom sheet as parent, screen is inside the createStackNavigator (react-navigation version 4.4.4)

Can you open this issue against `react-navigation` as well?

**Comment by Yagnesh7028** [comment]
@cortinico , Trying with removing the createStackNavigator but still getting same issue.

**Comment by meghvarse** [comment]
@cortinico , Trying with removing the createStackNavigator but still facing same issue.

**Comment by cipolleschi** [comment]
@meghvarse are you still facing the issue?
Could you provide a reproducer using [this template](https://github.com/react-native-community/reproducer-react-native)?

**Comment by cortinico** [comment]
> @meghvarse are you still facing the issue? Could you provide a reproducer using [this template](https://github.com/react-native-community/reproducer-react-native)?

Closing as we got no response.
Please provide a reproducer and we can help you further
