### ISSUE TITLE
onCreate not call for startService - Native-modules

### ISSUE THREAD

**Issue by SavinienBarbotaud** [facebook/react-native#38770]
### Description

I use react-native modules.

I create a java class that extend service to create a foreground notification.
Inside my primary module java class i try to start service with  : 
``` 
getReactApplicationContext()
                .startService(
                  new Intent(
                    getReactApplicationContext(),
                    ForegroundService.class
                  )
                );
```
In android documentation it should call 
```
  @Override
  public void onCreate() {
    super.onCreate();
} 
``` 
inside my ForegroundService class.

No error are throwing so i believe the service is started without any errors.
But this onCreate method is never call.
I add ```<service android:name="com.mediarecorder.ForegroundService"/>``` already.

Thanks for helping.

### React Native Version

0.72.3

### Output of `npx react-native info`

System:
  OS: Linux 5.19 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
  CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
  Memory: 6.89 GB / 15.46 GB
  Shell:
    version: 5.1.16
    path: /bin/bash
Binaries:
  Node:
    version: 16.19.0
    path: ~/.nvm/versions/node/v16.19.0/bin/node
  Yarn:
    version: 1.22.19
    path: /usr/bin/yarn
  npm:
    version: 9.7.1
    path: ~/.nvm/versions/node/v16.19.0/bin/npm
  Watchman: Not Found
SDKs:
  Android SDK:
    API Levels:
      - "23"
      - "28"
      - "31"
      - "32"
      - "33"
      - "33"
    Build Tools:
      - 29.0.2
      - 30.0.3
      - 33.0.0
      - 33.0.2
    System Images:
      - android-30 | Google APIs Intel x86 Atom
    Android NDK: Not Found
IDEs:
  Android Studio: Not Found
Languages:
  Java:
    version: 17.0.8
    path: /usr/bin/javac
  Ruby:
    version: 3.0.2
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.3
    wanted: 0.72.3
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

### Steps to reproduce

Create simple react native modules.
Create another java class in same package as your primary module.
Extends this class with ``` Service ``` and add necessary dependencies. (Like override onCreate() method) 
Update your manifest. ``` <service android:name="com.yourPackageName.YourClassJava"/> ```
In primary module try to start the service.

### Snack, screenshot, or link to a repository

https://github.com/SavinienBarbotaud/mediaRecorder

in android/src/main/java/com/mediarecorder

**Comment by cortinico** [comment]
Please follow the Android documentation for ForegroundServices:
https://developer.android.com/guide/components/foreground-services

Specifically you should use `.startForegroundService()` and they suggest to use the `onStartCommand()` callback
