### ISSUE TITLE
Contact Picker API not works in case of webview

### ISSUE THREAD

**Issue by GKM12345** [facebook/react-native#38772]
### Description

I have implemented a react js code in which I have written a logic if the browser support contact access and then shows the <Browse from Contact> button(to access contacts from mobile.) it works correctly on web pages or PWA but in react native web view <Browse From Contact> Button are there which means web view support Contact Picker API But on clicking on that does not work.

### React Native Version

Latest

### Output of `npx react-native info`

NA

### Steps to reproduce

NA

### Snack, screenshot, or link to a repository

NA

**Comment by cortinico** [comment]
Can you provide a repro?

**Comment by rickitan** [comment]
Hi @GKM12345 were you able to find a fix for this?

I turned the "Contact Picker API" advanced beta flag on Safari. And it makes it work on Safari.

But it doesn't work on WebViews.

Any tips? Thank you 🙏

**Comment by SULEIMANU02** [comment]
> ### Description
> I have implemented a react js code in which I have written a logic if the browser support contact access and then shows the button(to access contacts from mobile.) it works correctly on web pages or PWA but in react native web view Button are there which means web view support Contact Picker API But on clicking on that does not work.
> 
> ### React Native Version
> Latest
> 
> ### Output of `npx react-native info`
> NA
> 
> ### Steps to reproduce
> NA
> 
> ### Snack, screenshot, or link to a repository
> NA

Hello please did you get to solve that issue
If yes, how please
