### ISSUE TITLE
VisionOS Support for RN Pods

### ISSUE THREAD

**Issue by mojavad** [facebook/react-native#38782]
### Description

Currently, when running `pod install` on a React Native Project, you get an error prompting that 'React-RCTAppDelegate' is not compatible with `visionos` as a platform. 

Cocoapods is set to release `visionos` support as a platform in `v1.13` (this has already been merged to master and can be used with the unreleased version of Cocoapods). It would be good to support VisionOS with RN's pods.

### React Native Version

0.72.3

### Output of `npx react-native info`

```
System:
  OS: macOS 13.5
  CPU: (8) arm64 Apple M1
  Memory: 96.89 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 16.20.0
    path: ~/.nvm/versions/node/v16.20.0/bin/node
  Yarn:
    version: 1.22.19
    path: ~/.yarn/bin/yarn
  npm:
    version: 9.8.0
    path: ~/.nvm/versions/node/v16.20.0/bin/npm
  Watchman:
    version: 2023.06.12.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.1 AI-221.6008.13.2211.9619390
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.18
    path: /usr/bin/javac
  Ruby:
    version: 2.7.8
    path: /opt/homebrew/opt/ruby@2.7/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native:
    installed: 0.72.3
    wanted: ^0.72.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Steps to reproduce

- Create an empty VisionOS app. 
- Move it to an `ios` directory and create a barebones RN app.
- Create a basic default `Podfile` inside the `ios` directory.
- Create a `Gemfile` in the `ios` directory to point to Cocoapods's `master` branch: 
```
gem 'cocoapods', git: 'https://github.com/CocoaPods/CocoaPods', ref: '400f290cb9269ea342948f629525a5542933627f'
gem 'cocoapods-core', git: 'https://github.com/CocoaPods/Core', ref: '9320bf557741d7ae80eda4415bc6fb2b0b3a8b9c'
```
- Run `bundle install` in the `ios` directory
- Run `bundle exec pod install`.
- See error below:

### Snack, screenshot, or link to a repository

<img width="967" alt="image" src="https://github.com/facebook/react-native/assets/34189022/9d92f0b0-6f9b-4f9a-9077-726563147d3c">

**Comment by cipolleschi** [comment]
@mojavad, thanks for opening the issue.
We don't have immediate plans to supporting the VisionOS APIs and we are prioritizing other work. React Native can already execute iOS apps on the VisionPro in compatibility mode.

However, we are very open in accepting contributions that can enable the community creating wrappers around the VisionPRO APIs. Feel free to open a PR with the changes needed to support the VisionPRO and we will be super happy to review and land it.

Likely, you just have to update this line: https://github.com/facebook/react-native/blob/main/packages/react-native/Libraries/AppDelegate/React-RCTAppDelegate.podspec#L69

**Comment by mojavad** [comment]
Hi @cipolleschi , thanks for the quick reply. 

I'll take a quick look and see if I can get it up and working with just changing the Podspec, and open up a PR if I can :)

**Comment by mojavad** [comment]
@cipolleschi, just wondering what the best way is to test this. I was hoping to build from source and point it to my local build of RN in a VisionOS project, but it seems like the docs on building from source are Android only: 
https://reactnative.dev/contributing/how-to-build-from-source

Any suggestions on how to go about testing it?

**Comment by cipolleschi** [comment]
React Native for iOS always builds from source.

If you are using a custom app, you can go into the `node_modules/react-native/packages/react-native` and there yyou have the repo. If you modify the iOS code in React or ReactCommon, you'll see it reflected in your app.
Notice that:
1. as soon as you `yarn` you'll lose all your changes
2. once you are happy, you'll have to copy all the changes in the React Native repo. :( 

Otherwise, you can clone the React Native repo and use the app in `packages/rn-tester`. This is an app that builds React Native from source and every change you perform in the React Native code are reflected in RNTester.
There is a Readme on how to build RNTester in `packages/rn-tester/README.md`.

NOTE: to build RNTester you'll need CMake. We need it to build Hermes. `brew install cmake` will help! :D

**Comment by mojavad** [comment]
Thanks for the feedback @cipolleschi. 

Makes sense. 

I've gone ahead and changed AppDelegate and unsurprisingly, there's far more than needs the platform changed. Here's the full list of files that need modification for their platform: 
```
hermes-engine.podspec
hermes-utils.rb
hermes-engine.podspec
Yoga.podspec
React-logger.podspec
React-jsinspector.podspec
React-cxxreact.podspec
React-jsi.podspec
React-rncore.podspec
React-Fabric.podspec
React-perflogger.podspec
React-runtimeexecutor.podspec
ReactCommon.podspec
React-hermes.podspec
React-callinvoker.podspec
React-jsc.podspec
React-NativeModulesApple.podspec
ReactCommon-Samples.podspec
React-ImageManager.podspec
React-graphics.podspec
React-utils.podspec
React-debug.podspec
FBLazyVector.podspec
React-RCTActionSheet.podspec
RCTRequired.podspec
RCTTypeSafety.podspec
React-RCTPushNotification.podspec
codegen_utils.rb
boost.podspec
RCT-Folly.podspec
DoubleConversion.podspec
glog.podspec
FBReactNativeSpec.podspec
React-RCTFabric.podspec
```
At this point, we've hit two external dependencies that don't support `visionos` as a platform. 

1. For `React-Core`, we need to have `SocketRocket` support. I'm going to see if I can get it working on VisionOS and open up a PR. 
2. For hermes, we need `libevent` to support `visionos`. This seems like a harder task, not sure if you have any idea on this?

**Comment by mojavad** [comment]
Opened an issue with `libevent`. I'll have a crack at `SocketRocket` soon and see if I can get it up and running. :)

My one question: 
Given VisionOS support not been released to Cocoapods yet (i'm working off an unreleased branch), what's the best way of adding VisionOS as a platform to Podfiles without breaking it for users not on the latest version of Cocoapods? 

Is this something the RN team has faced in the past?

**Comment by cipolleschi** [comment]
@mojavad no, I never faced that issue, unfortunately.

What I think you can do is to check whether the VisionOS platform is a recognized symbol in the Cocoapods DSL (Ruby has a good reflection support). If yes, you can add it as additional platform. If not, you don't add it.

How does this sound?

**Comment by kaangrimdev** [comment]
ffgfgfgd
