### ISSUE TITLE
PanResponder mock behavior

### ISSUE THREAD

**Issue by thomasviaud** [facebook/react-native#38792]
### Description

Hello I'm updating from RN 0.71.8 to 0.72.3.
I'm using jest and mocking react-native **PanResponder** like this in `jest.setup.js`:
```
jest.mock('./node_modules/react-native/Libraries/Interaction/PanResponder', () => ({
  create: (config) => ({ panHandlers: config }),
}))
```

Without any change, the tests are not passing anymore on the latest versions of RN (0.72.X).

```
TypeError: Cannot read properties of undefined (reading 'create')

      1 | import * as React from 'react'
    > 2 | import Svg, { SvgProps, Path } from 'react-native-svg'
```

After some digging, it appears that the package `react-native-svg` is also using the PanResponder, and the internal import from RN resolves to undefined (calling create on an undefined object). I have some trouble finding the change that is causing this new behavior.

I also did not change the jest config:
```
// jest.config.js
const config = {
  preset: '@testing-library/react-native',
  testPathIgnorePatterns: ['/helpers', '/responses'],
  setupFilesAfterEnv: ['@testing-library/jest-native/extend-expect', './jest.setup.js'],
  transformIgnorePatterns: [
    'node_modules/(?!(jest-)?@?react-native|@react-native-community|@react-navigation/.*|@sentry/react-native)',
  ],
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
  moduleNameMapper: {
    '\\.(jpg|ico|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$':
      '<rootDir>/__mocks__/fileMock.js',
  },
  fakeTimers: {
    enableGlobally: true,
  },
  testTimeout: 20000,
  clearMocks: true,
}

module.exports = config
```

Thanks in advance.

### React Native Version

0.72.3

### Output of `npx react-native info`

System:
  OS: macOS 13.4.1
  CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
  Memory: 341.94 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.12.1
    path: ~/.nvm/versions/node/v18.12.1/bin/node
  Yarn:
    version: 1.22.19
    path: ~/.nvm/versions/node/v18.12.1/bin/yarn
  npm:
    version: 8.19.2
    path: ~/.nvm/versions/node/v18.12.1/bin/npm
  Watchman:
    version: 2023.05.22.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /Users/thomasviaud/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2020.3 AI-203.7717.56.2031.7935034
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.19
    path: /usr/bin/javac
  Ruby:
    version: 3.1.1
    path: /Users/thomasviaud/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.3
    wanted: ^0.72.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

### Steps to reproduce

- Install jest
- Mock PanResponder in jest.setup.js:
```
jest.mock('./node_modules/react-native/Libraries/Interaction/PanResponder', () => ({
  create: (config) => ({ panHandlers: config }),
}))
```
- Run a test rendering a screen that is showing a svg from react-native-svg
- Get an error:
```
TypeError: Cannot read properties of undefined (reading 'create')

      1 | import * as React from 'react'
    > 2 | import Svg, { SvgProps, Path } from 'react-native-svg'
```

### Snack, screenshot, or link to a repository

/

**Comment by neemssoni** [comment]
I am also facing the same issue

**Comment by thomasviaud** [comment]
This is not fixing on my side because you are mocking the whole svg package with only a PanResponder.

**Comment by neemssoni** [comment]
then you can do as shown in the image, also do not mock panrespnder from ./node_modules/react-native/Libraries/Interaction/PanResponder
<img width="593" alt="Screenshot 2023-11-28 at 5 01 43 PM" src="https://github.com/facebook/react-native/assets/18548951/eadbe7fd-2375-4065-94aa-99c7fb19678b">

**Comment by thomasviaud** [comment]
Well, I fixed my problem by not mocking PanResponder at all.
Instead I'm using close-to-reality events that will update my UI (in my tests):
```
  act(() =>
    panHandler.props.onResponderMove({
      touchHistory: {
        indexOfSingleActiveTouch: 1,
        mostRecentTimeStamp: 411733262.676947,
        numberActiveTouches: 1,
        touchBank: [
          undefined,
          {
            currentPageX: 192,
            currentPageY: 124,
            currentTimeStamp: 411733262.676947,
            previousPageX: 192,
            previousPageY: 324,
            previousTimeStamp: 411733234.333552,
            startPageX: 202.66665649414062,
            startPageY: 647.6666564941406,
            startTimeStamp: 411731079.78750896,
            touchActive: true,
          },
        ],
      },
    }),
  )
  act(() => panHandler.props.onResponderRelease({}))
```
But in the end I did not understand this mock change behaviour when updating RN 🤷‍♂️
