### ISSUE TITLE
[Packager] Add option to configure extensions DependencyGraph uses in module DFS.

### ISSUE THREAD

**Issue by pilwon** [facebook/react-native#388]
It'd be convenient to be able to configure module file extensions similar to `webpack`'s [resolve.extensions](http://webpack.github.io/docs/configuration.html#resolve-extensions).

**Comment by amasad** [comment]
Do you have a use case?

**Comment by joewood** [comment]
I was thinking about this too. For example, configure the packager to use a TypeScript transformer for **.ts** files before it processes the regular transformer.  I think just a glob pattern would do, with a way of specifying a packager plugin.

**Comment by pilwon** [comment]
@amasad I like keeping `.js` separate from `.jsx`. `react-packager` currently processes all `.js` files with `jstransform`. In my other projects built with `webpack`, I like reserving `.js` extension for plain JS files that doesn't need to be transformed. I just run them and it saves me some time. My text editor also selects appropriate syntax highlighters based on the extensions. I'd like to do the same with `react-native`. (without this feature I need to write `require('./module.jsx')` all the time)

**Comment by pilwon** [comment]
I know some people write react code with `.react.js` extension. (probably for the same reason)

**Comment by joewood** [comment]
It would be great to have a root level config file for the packager that included a callback to resolve the transform to apply.  This way it could require in transforms loaded from npm and maybe use webpack's loaders.

**Comment by facebook-github-bot-3** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by brentvatne** [comment]
It looks like this has been around for a long time so I've marked it as community responsibility as there doesn't seem to be an internal need at Facebook and @amasad has enough on his plate already :) @pilwon @joewood - please feel free to take a stab at this and submit a PR!

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/packager-add-option-to-configure-extensions-dependencygraph-uses-in-module-dfs

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.

**Comment by kgroat** [comment]
Above link is broken; actual link is now:
https://productpains.com/post/react-native/packager-add-option-to-configure-extensions-dependencygraph

**Comment by orta** [comment]
There is a PR which addresses this here: https://github.com/facebook/react-native/pull/11932
