### ISSUE TITLE
Animated.View do not expose test ids of views inside it for android build 

### ISSUE THREAD

**Issue by MahmoudMabrok** [facebook/react-native#38809]
### Description

We have RN app and a part of app we are using `Animated.View` that holds other views but with Appium Inspector we can not locate views inside that view. 

 

### React Native Version

v0.70.6

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 48.95 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.18.0 - ~/.nvm/versions/node/v14.18.0/bin/node
    Yarn: Not Found
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /Users/XXXX//.rvm/gems/ruby-2.7.5/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 30, 31, 33
      Build Tools: 30.0.3, 31.0.0, 33.0.0, 33.0.2, 34.0.0
      System Images: android-30 | Google APIs ARM 64 v8a, android-30 | Google Play ARM 64 v8a, android-33 | Google APIs ARM 64 v8a, android-33 | Google Play ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.9971841
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.19 - /Users/XXXX/Library/Java/JavaVirtualMachines/corretto-11.0.19/Contents/Home/bin/javac
  npmPackages:
    @react-native-community/cli: 9.3.2 => 9.3.2 
    react: ^18.2.0 => 18.2.0 
    react-native: 0.70.6 => 0.70.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
info React Native v0.72.3 is now available (your project is running on v0.70.6).

### Steps to reproduce

create any view inside an Animated.View and try to locate it by id in Ai

```
 <Animated.View
          testID={ID1}
        >
          <Text
              testKey={ID2}
            >

 </Animated.View>
```

### Snack, screenshot, or link to a repository

![Screenshot 2023-08-06 at 2 40 19 PM](https://github.com/facebook/react-native/assets/13488900/d6e7f1a3-2d52-4da6-9031-8d94523825f7)

**Comment by wswebcreation** [comment]
This can be closed, it's related to [this](https://engineering.fb.com/2015/11/23/android/making-react-native-apps-accessible/)

**Comment by MahmoudMabrok** [comment]
I remember migrated to version  `0.70.13` solved the issue. 
but it is not easy for all to migrate.
