### ISSUE TITLE
Trying to run the app, and app run to failed

### ISSUE THREAD

**Issue by saggy** [facebook/react-native#38807]
### Description

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not determine the dependencies of null.
   > SDK location not found. Define a valid SDK location with an ANDROID_HOME environment variable or by setting the sdk.dir path in your project's local properties file at

### React Native Version

0.72.3

### Output of `npx react-native info`

C:\Users\Admin>npx react-native info
error: unknown command 'info'
(Did you mean init?)

### Steps to reproduce

After creating the app, later, try to run the android app from cmd

### Snack, screenshot, or link to a repository

![error screenshot](https://github.com/facebook/react-native/assets/2518796/a1c0147c-2300-4997-a3b2-72e59f107cc8)

**Comment by tarunrajput** [comment]
@saggy, looks like your environment is not setup properly. Pls follow instructions on this page https://reactnative.dev/docs/environment-setup?os=windows&platform=android

**Comment by cortinico** [comment]
> SDK location not found. Define a valid SDK location with an ANDROID_HOME environment variable or by setting the sdk.dir path in your project's local properties file at

Closing as @tarunrajput provided the right answer. Also please use `react-native doctor` to verify your environment is all green
