### ISSUE TITLE
removeClippedSubviews & stickyHeaderIndices do not interoperate correctly in ScrollView (iOS)

### ISSUE THREAD

**Issue by unstableair** [facebook/react-native#38817]
### Description

In a **ScrollView** with multiple **stickyHeaderIndices**, clipped sticky headers are not correctly removed by **removeClippedSubviews**. The contents of the subview are removed but the elements themselves are still drawn on top of the screen.

This causes problems because the rogue elements prevent touch events for any elements below them. 

In the image below we see the element inspector highlighting Header 1s Text element which has just scrolled off the top of the screen. The contents are removed but the element is not.

This only seems to be an issue on iOS.

![Simulator Screenshot - iPhone 13 - 2023-08-07 at 14 31 32](https://github.com/facebook/react-native/assets/13333972/0784dd81-9972-4f9a-959e-5bcd3105e5e8)

### React Native Version

0.72.3

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
  OS: macOS 13.5
  CPU: (6) x64 Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
  Memory: 3.74 GB / 48.00 GB
  Shell:
    version: 3.2.57
    path: /bin/bash
Binaries:
  Node:
    version: 16.13.2
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.19
    path: ~/.yarn/bin/yarn
  npm:
    version: 9.4.0
    path: /usr/local/bin/npm
  Watchman:
    version: 2021.11.15.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.11.2
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.2 AI-222.4459.24.2221.10121639
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.15
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.3
    wanted: 0.72.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

### Steps to reproduce

1. Start the provided expo snack on an iOS device.
2. Scroll until sticky "Header 2" forces "Header 1" off screen. 
3. Open the developer menu and start the Inspector
4. Search the screen for the invisible elements which overlap the 3rd & 4th line below the "Header 2".
Alternatively copy the App.js from the Snack into a freshly installed RN project & compile.

### Snack, screenshot, or link to a repository

https://snack.expo.dev/stYqaDHQR

**Comment by EJohnF** [comment]
I'm facing similar issues, although not related to sticky scroll view. But element is highlighted not where it's displayed
