### ISSUE TITLE
Android TV development issues

### ISSUE THREAD

**Issue by renjiali** [facebook/react-native#38811]
### Description

Some issues found when adapting to Android TV

1. There is a lack of events that define the selection of elements, such as onSelect. We need to set the card selection status based on it (with white borders, shadows, zooming in, etc.). The design effect is as follows
![微信截图_20230807161351](https://github.com/facebook/react-native/assets/94222668/5c3675a8-7214-4abb-a68b-ca3107aa4fef)

2. Can you provide a scrollview API similar to web to scroll to the center of the view when elements are focused

3. After adding onFocus={()=>console. log ('--------')} to the example code below, the card was selected, but the onFocus example was not triggered
`
import {Dimensions, Image, Text, Pressable, View} from 'react-native';
import LinearGradient from 'react-native-linear-gradient';
import {FoodCardProps} from './types.d';
import {baseUrl} from '@/config';
import {useNavigation} from '@react-navigation/native';
const window = Dimensions.get('window');
const scale = window.width / 1920;
export const FoodCard = (props: FoodCardProps) => {
  const navigation: any = useNavigation();
  return (
    <Pressable
      onPress={() =>
        navigation.navigate('ShopView', {
          id: props.data.id,
          shop_id: props.data.shop_id,
          name: props.data.name,
        })
      }
      style={[
        props.style,
        {
          position: 'relative',
          marginBottom: 32 * scale,
          elevation: 1,
        },
      ]}
      android_disableSound={false}
      android_ripple={{foreground: true, borderless: false, color: '#0052d9'}}>
      <View>
        <Image
          resizeMode="cover"
          style={{width: 564 * scale, height: 282 * scale}}
          source={{uri: baseUrl + props.data.image}}
        />
        <LinearGradient
          colors={['#00B1FF', '#0BCAFF', '#3EF2B6']}
          start={{x: 0, y: 0}}
          end={{x: 1, y: 0}}
          style={{
            width: 564 * scale,
            height: 216 * scale,
            padding: 32 * scale,
          }}>
          <Text
            style={{
              fontFamily: 'PingFangSC-Medium',
              fontSize: 40 * scale,
              color: '#fff',
              letterSpacing: 0,
              lineHeight: 50 * scale,
              fontWeight: '500',
              marginBottom: 10 * scale,
            }}>
            {props.data.name}
          </Text>
          <View
            style={{
              display: 'flex',
              flexDirection: 'row',
              alignItems: 'center',
              marginRight: 16 * scale,
            }}>
            {props.data.tags.map(tag => {
              return (
                <Text
                  style={{
                    borderWidth: 1.5 * scale,
                    borderRadius: 22 * scale,
                    borderColor: 'rgba(255,255,255,0.4)',
                    paddingHorizontal: 15 * scale,
                    paddingVertical: 6 * scale,
                    marginRight: 16 * scale,
                    color: '#fff',
                  }}
                  key={tag}>
                  {tag}
                </Text>
              );
            })}
          </View>
          <Text
            style={{
              fontFamily: 'PingFangSC-Medium',
              fontSize: 28 * scale,
              color: '#fff',
              letterSpacing: 0,
              lineHeight: 32 * scale,
              fontWeight: '400',
              marginTop: 24 * scale,
            }}>
            {props.data.shop_name}
          </Text>

          <Text
            style={{
              position: 'absolute',
              bottom: 12 * scale,
              right: 16 * scale,
              fontFamily: 'PingFangSC-Medium',
              fontSize: 44 * scale,
              color: '#fff',
              letterSpacing: 0,
              lineHeight: 44 * scale,
              fontWeight: '900',
            }}>
            ¥ {props.data.price}
          </Text>
        </LinearGradient>
      </View>
    </Pressable>
  );
};

`
Of course, perhaps I am not familiar with the Android TV development process. If you have better suggestions, we can communicate with you

### React Native Version

0.72.3

### Output of `npx react-native info`

no

### Steps to reproduce

no

### Snack, screenshot, or link to a repository

no

**Comment by renjiali** [comment]
`import {Dimensions, Image, Text, Pressable, View} from 'react-native';
import LinearGradient from 'react-native-linear-gradient';
import {FoodCardProps} from './types.d';
import {baseUrl} from '@/config';
import {useNavigation} from '@react-navigation/native';
const window = Dimensions.get('window');
const scale = window.width / 1920;
export const FoodCard = (props: FoodCardProps) => {
  const navigation: any = useNavigation();
  return (
    <Pressable
      onFocus={() => console.log('---------')}
      onPress={() =>
        navigation.navigate('ShopView', {
          id: props.data.id,
          shop_id: props.data.shop_id,
          name: props.data.name,
        })
      }
      style={[
        props.style,
        {
          position: 'relative',
          marginBottom: 32 * scale,
          elevation: 1,
        },
      ]}
      android_disableSound={false}
      android_ripple={{foreground: true, borderless: false, color: '#0052d9'}}>
      <View>
        <Image
          resizeMode="cover"
          style={{width: 564 * scale, height: 282 * scale}}
          source={{uri: baseUrl + props.data.image}}
        />
        <LinearGradient
          colors={['#00B1FF', '#0BCAFF', '#3EF2B6']}
          start={{x: 0, y: 0}}
          end={{x: 1, y: 0}}
          style={{
            width: 564 * scale,
            height: 216 * scale,
            padding: 32 * scale,
          }}>
          <Text
            style={{
              fontFamily: 'PingFangSC-Medium',
              fontSize: 40 * scale,
              color: '#fff',
              letterSpacing: 0,
              lineHeight: 50 * scale,
              fontWeight: '500',
              marginBottom: 10 * scale,
            }}>
            {props.data.name}
          </Text>
          <View
            style={{
              display: 'flex',
              flexDirection: 'row',
              alignItems: 'center',
              marginRight: 16 * scale,
            }}>
            {props.data.tags.map(tag => {
              return (
                <Text
                  style={{
                    borderWidth: 1.5 * scale,
                    borderRadius: 22 * scale,
                    borderColor: 'rgba(255,255,255,0.4)',
                    paddingHorizontal: 15 * scale,
                    paddingVertical: 6 * scale,
                    marginRight: 16 * scale,
                    color: '#fff',
                  }}
                  key={tag}>
                  {tag}
                </Text>
              );
            })}
          </View>
          <Text
            style={{
              fontFamily: 'PingFangSC-Medium',
              fontSize: 28 * scale,
              color: '#fff',
              letterSpacing: 0,
              lineHeight: 32 * scale,
              fontWeight: '400',
              marginTop: 24 * scale,
            }}>
            {props.data.shop_name}
          </Text>

          <Text
            style={{
              position: 'absolute',
              bottom: 12 * scale,
              right: 16 * scale,
              fontFamily: 'PingFangSC-Medium',
              fontSize: 44 * scale,
              color: '#fff',
              letterSpacing: 0,
              lineHeight: 44 * scale,
              fontWeight: '900',
            }}>
            ¥ {props.data.price}
          </Text>
        </LinearGradient>
      </View>
    </Pressable>
  );
};
`
代码片段

**Comment by cortinico** [comment]
Hi @renjiali 
Thanks for reporting this issue.

It seems like this issue is actually unrelated to React Native core. Please open this issue against this other repository:

https://github.com/react-native-tvos/react-native-tvos/issues

I'll be closing this but feel free to reopen if the other repo points back to us as a issue in the core of React Native.
