### ISSUE TITLE
[Android] JSON to WritableMap

### ISSUE THREAD

**Issue by PhilippKrone** [facebook/react-native#3881]
Hello,

is there currently a way to convert a common JSON (received e.g. as response to a HttpUrlConnection) to a WritableMap? I'm thinking of something like

````javascript
WriteableMap map = Arguments.createMap(JSON);
````

or

````javascript
WriteableMap map = Arguments.createMap();
map.loadFromJson(JSON);
````

If not, I'd be happy to provide a PR with a little bit of guidance as to where to put it and whether there are any preferences concerning implementation.

Thanks
Philipp

**Comment by PhilippKrone** [comment]
**Update**: found the solution after all:

````javascript
import com.facebook.internal.BundleJSONConverter;
...

JSONObject mainObject = new JSONObject(sb.toString());
if (mainObject != null) {
   BundleJSONConverter bjc = new BundleJSONConverter();
   Bundle bundle = bjc.convertToBundle(mainObject);
   WritableMap map = Arguments.fromBundle(bundle);
}
````

**Comment by kapv89** [comment]
@PhilippKrone hey, can you link to react source code where this is used? can't find `BundleJSONConverter` in react@0.25

**Comment by kohver** [comment]
@kapv89 https://github.com/facebook/facebook-android-sdk/blob/master/facebook/src/main/java/com/facebook/internal/BundleJSONConverter.java

**Comment by snowjade** [comment]
sorry , what can I do if I do not use facebook-android-sdk ?

**Comment by clarle** [comment]
Very late response, but what I ended up doing was just bringing in the BundleJSONConverter.java file as a standalone class. 

It doesn't have any other custom dependencies, so it can be used as is.

**Comment by nicholasareed** [comment]
An easier file to use: https://github.com/remobile/react-native-cordova/blob/master/android/src/main/java/com/remobile/cordova/JsonConvert.java

    JSONObject mainObject;
    WritableMap map;
    try {
        mainObject = new JSONObject("{}");
        map = BundleJSONConverter.jsonToReact(mainObject);
    }catch(org.json.JSONException ex){
        System.out.println("Exception: " + ex);
    }
