### ISSUE TITLE
post-install hook of the Podfile.  no implicit conversion of String into Array -enabling new arch

### ISSUE THREAD

**Issue by vksgautam1986** [facebook/react-native#38833]
### Description

I  have just tried to use New Architecture for ios. but during pod installation it is giving error .

```
[!] An error occurred while processing the post-install hook of the Podfile.

no implicit conversion of String into Array

/Users/company/Desktop/Swatched/Final/swatched-mobile/node_modules/react-native/scripts/cocoapods/new_architecture.rb:73:in `+'
/Users/company/Desktop/Swatched/Final/swatched-mobile/node_modules/react-native/scripts/cocoapods/new_architecture.rb:73:in `block (2 levels) in modify_flags_for_new_architecture'
/Users/company/Desktop/Swatched/Final/swatched-mobile/node_modules/react-native/scripts/cocoapods/new_architecture.rb:70:in `each'
/Users/company/Desktop/Swatched/Final/swatched-mobile/node_modules/react-native/scripts/cocoapods/new_architecture.rb:70:in `block in modify_flags_for_new_architecture'
/Users/company/Desktop/Swatched/Final/swatched-mobile/node_modules/react-native/scripts/cocoapods/new_architecture.rb:63:in `each'
/Users/company/Desktop/Swatched/Final/swatched-mobile/node_modules/react-native/scripts/cocoapods/new_architecture.rb:63:in `modify_flags_for_new_architecture'
/Users/company/Desktop/Swatched/Final/swatched-mobile/node_modules/react-native/scripts/react_native_pods.rb:251:in `react_native_post_install'
/Users/company/Desktop/Swatched/Final/swatched-mobile/ios/Podfile:71:in `block (3 levels) in from_ruby'
/Users/company/.rvm/gems/ruby-3.0.0/gems/cocoapods-core-1.12.1/lib/cocoapods-core/podfile.rb:196:in `post_install!'
/Users/company/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:1013:in `run_podfile_post_install_hook'
/Users/company/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:1001:in `block in run_podfile_post_install_hooks'
/Users/company/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.12.1/lib/cocoapods/user_interface.rb:149:in `message'
/Users/company/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:1000:in `run_podfile_post_install_hooks'
/Users/company/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:337:in `block (2 levels) in create_and_save_projects'
/Users/company/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.12.1/lib/cocoapods/installer/xcode/pods_project_generator/pods_project_writer.rb:61:in `write!'
/Users/company/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:336:in `block in create_and_save_projects'
/Users/company/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.12.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/company/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:315:in `create_and_save_projects'
/Users/company/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:307:in `generate_pods_project'
/Users/company/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:183:in `integrate'
/Users/company/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:170:in `install!'
/Users/company/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.12.1/lib/cocoapods/command/install.rb:52:in `run'
/Users/company/.rvm/gems/ruby-3.0.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/Users/company/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.12.1/lib/cocoapods/command.rb:52:in `run'
/Users/company/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.12.1/bin/pod:55:in `<top (required)>'
/Users/company/.rvm/gems/ruby-3.0.0/bin/pod:23:in `load'
/Users/company/.rvm/gems/ruby-3.0.0/bin/pod:23:in `<main>'
/Users/company/.rvm/gems/ruby-3.0.0/bin/ruby_executable_hooks:22:in `eval'
/Users/company/.rvm/gems/ruby-3.0.0/bin/ruby_executable_hooks:22:in `<main>'

[!] [Codegen] warn: using experimental new codegen integration

[!] The platform of the target `Swatched` (iOS 12.4) may not be compatible with `RNCAsyncStorage (1.19.1)` which has a minimum requirement of iOS 13.4 - tvOS 11.0 - macOS 10.15.
```

### React Native Version

0.72.3

### Output of `npx react-native info`

System:
  OS: macOS 13.4.1
  CPU: (8) arm64 Apple M1
  Memory: 114.81 MB / 8.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 16.11.0
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.19
    path: ~/Desktop/Swatched/Final/swatched-mobile/node_modules/.bin/yarn
  npm:
    version: 8.0.0
    path: /usr/local/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.12.1
    path: /Users/company/.rvm/gems/ruby-3.0.0/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.1
      - iOS 16.1
      - macOS 13.0
      - tvOS 16.1
      - watchOS 9.1
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.2 AI-222.4459.24.2221.9862592
  Xcode:
    version: 14.1/14B47
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.12
    path: /usr/bin/javac
  Ruby:
    version: 3.0.0
    path: /Users/company/.rvm/rubies/ruby-3.0.0/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.3
    wanted: ^0.72.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: true

### Steps to reproduce

During running pod installation command , i am facing this issue..
// https://reactnative.dev/docs/new-architecture-app-intro?run-app=npm

RCT_NEW_ARCH_ENABLED=1 bundle exec pod install

### Snack, code example, screenshot, or link to a repository

```ruby
# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip
platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'Swatched' do
  config = use_native_modules!
  use_frameworks! :linkage => :static
  $RNFirebaseAsStaticFramework = true
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
   
    :hermes_enabled => true,
    :fabric_enabled => true,
   
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'GoogleSignIn', '~> 7.0'


  post_install do |installer|
      # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
      react_native_post_install(
        installer,
        config[:reactNativePath],
        :mac_catalyst_enabled => false
      )
    installer.pods_project.targets.each do |target|
      if target.name == 'RCT-Folly'
        target.build_configurations.each do |config|
          config.build_settings['HEADER_SEARCH_PATHS'] = "$(inherited) ${PODS_ROOT}/fmt/include"
        end
      end
    end
    react_native_post_install(installer)
      __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
  end
```

**Comment by vksgautam1986** [comment]
i removed this part and able to install the pods but not sure if it is correct approach or not.


react_native_post_install(
installer,
config[:reactNativePath],
:mac_catalyst_enabled => false
)

**Comment by cipolleschi** [comment]
Hi @vksgautam1986.

You need to leave that block in the post install, otherwise the project will not build correctly.
The error you are facing is a bit weird, as it seems like a Ruby error, but our CI is building the app correctly.

Can you try to:
- add back the post install hook
- navigate to the `ios` folder.
- run `bundle install`
- run `RCT_NEW_ARCH_ENABLED=1 bundle exec pod install`

and let me know what's the output.

then try again with this command:
- `USE_FRAMEWORKS=static _NEW_ARCH_ENABLED=1 bundle exec pod instal`.
I see that you are using firebase, which requires use frameworks set to static.

**Comment by cipolleschi** [comment]
I just tried with a newly created app and it works properly, without changing anything.

**Comment by vksgautam1986** [comment]
Hi , i have followed your steps and ran this command
RCT_NEW_ARCH_ENABLED=1 bundle exec pod install

but it is giving the same error  of this.
[!] An error occurred while processing the post-install hook of the Podfile.

no implicit conversion of String into Array

/Users/netsmartz/Desktop/Swatched/Final/swatched-mobile/node_modules/react-native/scripts/cocoapods/new_architecture.rb:73:in `+'
/Users/netsmartz/Desktop/Swatched/Final/swatched-mobile/node_modules/react-native/scripts/cocoapods/new_architecture.rb:73:in `block (2 levels) in modify_flags_for_new_architecture'
/Users/netsmartz/Desktop/Swatched/Final/swatched-mobile/node_modules/react-native/scripts/cocoapods/new_architecture.rb:70:in `each'
/Users/netsmartz/Desktop/Swatched/Final/swatched-mobile/node_modules/react-native/scripts/cocoapods/new_architecture.rb:70:in `block in modify_flags_for_new_architecture'
/Users/netsmartz/Desktop/Swatched/Final/swatched-mobile/node_modules/react-native/scripts/cocoapods/new_architecture.rb:63:in `each'
/Users/netsmartz/Desktop/Swatched/Final/swatched-mobile/node_modules/react-native/scripts/cocoapods/new_architecture.rb:63:in `modify_flags_for_new_architecture'
/Users/netsmartz/Desktop/Swatched/Final/swatched-mobile/node_modules/react-native/scripts/react_native_pods.rb:251:in `react_native_post_install'
/Users/netsmartz/Desktop/Swatched/Final/swatched-mobile/ios/Podfile:71:in `block (3 levels) in from_ruby'
/Users/netsmartz/.rvm/gems/ruby-2.7.4/gems/cocoapods-core-1.12.1/lib/cocoapods-core/podfile.rb:196:in `post_install!'
/Users/netsmartz/.rvm/gems/ruby-2.7.4/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:1013:in `run_podfile_post_install_hook'
/Users/netsmartz/.rvm/gems/ruby-2.7.4/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:1001:in `block in run_podfile_post_install_hooks'
/Users/netsmartz/.rvm/gems/ruby-2.7.4/gems/cocoapods-1.12.1/lib/cocoapods/user_interface.rb:149:in `message'
/Users/netsmartz/.rvm/gems/ruby-2.7.4/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:1000:in `run_podfile_post_install_hooks'
/Users/netsmartz/.rvm/gems/ruby-2.7.4/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:337:in `block (2 levels) in create_and_save_projects'
/Users/netsmartz/.rvm/gems/ruby-2.7.4/gems/cocoapods-1.12.1/lib/cocoapods/installer/xcode/pods_project_generator/pods_project_writer.rb:61:in `write!'
/Users/netsmartz/.rvm/gems/ruby-2.7.4/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:336:in `block in create_and_save_projects'
/Users/netsmartz/.rvm/gems/ruby-2.7.4/gems/cocoapods-1.12.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/netsmartz/.rvm/gems/ruby-2.7.4/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:315:in `create_and_save_projects'
/Users/netsmartz/.rvm/gems/ruby-2.7.4/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:307:in `generate_pods_project'
/Users/netsmartz/.rvm/gems/ruby-2.7.4/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:183:in `integrate'
/Users/netsmartz/.rvm/gems/ruby-2.7.4/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:170:in `install!'
/Users/netsmartz/.rvm/gems/ruby-2.7.4/gems/cocoapods-1.12.1/lib/cocoapods/command/install.rb:52:in `run'
/Users/netsmartz/.rvm/gems/ruby-2.7.4/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/Users/netsmartz/.rvm/gems/ruby-2.7.4/gems/cocoapods-1.12.1/lib/cocoapods/command.rb:52:in `run'
/Users/netsmartz/.rvm/gems/ruby-2.7.4/gems/cocoapods-1.12.1/bin/pod:55:in `<top (required)>'
/Users/netsmartz/.rvm/gems/ruby-2.7.4/bin/pod:23:in `load'
/Users/netsmartz/.rvm/gems/ruby-2.7.4/bin/pod:23:in `<main>'
/Users/netsmartz/.rvm/gems/ruby-2.7.4/bin/ruby_executable_hooks:22:in `eval'
/Users/netsmartz/.rvm/gems/ruby-2.7.4/bin/ruby_executable_hooks:22:in `<main>'



after this i ran this command of  `USE_FRAMEWORKS=static _NEW_ARCH_ENABLED=1 bundle exec pod install`
and i am able to install pods successfully and able to run the ios development build in simulator and also able to make archive build also

**Comment by vksgautam1986** [comment]
Hi [cipolleschi](https://github.com/cipolleschi) , I have created a new project for 0.72.3 and ran this command 
`RCT_NEW_ARCH_ENABLED=1 bundle exec pod install`
it worked fine.

after that i copied my current project dependencies into this new fresh project package json and copied the same setting of pods file into this new project podfile and ran the command `yarn install` and after that i ran `RCT_NEW_ARCH_ENABLED=1 bundle exec pod install` and i got the same error.
i have created a repo and if you wanna look into it. 
https://github.com/vksgautam1986/TestSeventyTwo
https://github.com/vksgautam1986/TestSeventyTwo

**Comment by cipolleschi** [comment]
So... if a new projects works fine, it means that there is some dependency in your specific project that is messing up with the setup.

I'll suggest you to remove all the dependencies and start adding one dep at the time to see which one is breaking it.
My guess is `pod 'GoogleSignIn', '~> 7.0'` because we know that RN works with Firebase.

**Comment by vksgautam1986** [comment]
Ya i was able to solve it by comparing it with fresh project podfile.
i removed this part from the excisting podfile '    react_native_post_install(installer)' and able to install pods
RCT_NEW_ARCH_ENABLED=1 bundle exec pod install


```# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip
platform :ios, min_ios_version_supported
prepare_react_native_project!
# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'Swatched' do
  config = use_native_modules!
  use_frameworks! :linkage => :static
  $RNFirebaseAsStaticFramework = true
# Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
   
    # Hermes is now enabled by default. Disable by setting this flag to false.
    :hermes_enabled => true,
    :fabric_enabled => true,
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'GoogleSignIn', '~> 7.0'
  # pod 'Firebase/Core', '~> 6.13.0'
  # pod 'Firebase/Messaging', '~> 6.13.0'

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  #  use_flipper!()


  post_install do |installer|
      # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
      react_native_post_install(
        installer,
        config[:reactNativePath],
        :mac_catalyst_enabled => false
      )
      __apply_Xcode_12_5_M1_post_install_workaround(installer)

    installer.pods_project.targets.each do |target|
      if target.name == 'RCT-Folly'
        target.build_configurations.each do |config|
          config.build_settings['HEADER_SEARCH_PATHS'] = "$(inherited) ${PODS_ROOT}/fmt/include"
        end
      end
    end
  end
  end
```

**Comment by vksgautam1986** [comment]
Hi @cipolleschi just closing this , as pods installation is working for me by removing 'react_native_post_install(installer) ' and above is my podfile having the final changes. Just letting you know about this . Thanks.

**Comment by Paulraj153u1** [comment]
[!] An error occurred while processing the post-install hook of the Podfile.

no implicit conversion of nil into Array

/Users/bsoft-imac/Documents/kaptrack/node_modules/react-native/scripts/cocoapods/privacy_manifest_utils.rb:115:in `+'
/Users/bsoft-imac/Documents/kaptrack/node_modules/react-native/scripts/cocoapods/privacy_manifest_utils.rb:115:in `block (5 levels) in get_used_required_reason_apis'
/Users/bsoft-imac/Documents/kaptrack/node_modules/react-native/scripts/cocoapods/privacy_manifest_utils.rb:111:in `each'
/Users/bsoft-imac/Documents/kaptrack/node_modules/react-native/scripts/cocoapods/privacy_manifest_utils.rb:111:in `block (4 levels) in get_used_required_reason_apis'
/Users/bsoft-imac/Documents/kaptrack/node_modules/react-native/scripts/cocoapods/privacy_manifest_utils.rb:106:in `each'
/Users/bsoft-imac/Documents/kaptrack/node_modules/react-native/scripts/cocoapods/privacy_manifest_utils.rb:106:in `block (3 levels) in get_used_required_reason_apis'
/Users/bsoft-imac/Documents/kaptrack/node_modules/react-native/scripts/cocoapods/privacy_manifest_utils.rb:105:in `each'
/Users/bsoft-imac/Documents/kaptrack/node_modules/react-native/scripts/cocoapods/privacy_manifest_utils.rb:105:in `block (2 levels) in get_used_required_reason_apis'
/Users/bsoft-imac/Documents/kaptrack/node_modules/react-native/scripts/cocoapods/privacy_manifest_utils.rb:104:in `each'
/Users/bsoft-imac/Documents/kaptrack/node_modules/react-native/scripts/cocoapods/privacy_manifest_utils.rb:104:in `block in get_used_required_reason_apis'
/Users/bsoft-imac/Documents/kaptrack/node_modules/react-native/scripts/cocoapods/privacy_manifest_utils.rb:102:in `each'
/Users/bsoft-imac/Documents/kaptrack/node_modules/react-native/scripts/cocoapods/privacy_manifest_utils.rb:102:in `get_used_required_reason_apis'
/Users/bsoft-imac/Documents/kaptrack/node_modules/react-native/scripts/cocoapods/privacy_manifest_utils.rb:18:in `add_aggregated_privacy_manifest'
/Users/bsoft-imac/Documents/kaptrack/node_modules/react-native/scripts/react_native_pods.rb:301:in `react_native_post_install'
/Users/bsoft-imac/Documents/kaptrack/ios/Podfile:44:in `block (3 levels) in from_ruby'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-core-1.15.2/lib/cocoapods-core/podfile.rb:196:in `post_install!'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:1013:in `run_podfile_post_install_hook'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:1001:in `block in run_podfile_post_install_hooks'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/user_interface.rb:149:in `message'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:1000:in `run_podfile_post_install_hooks'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:337:in `block (2 levels) in create_and_save_projects'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/installer/xcode/pods_project_generator/pods_project_writer.rb:61:in `write!'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:336:in `block in create_and_save_projects'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/user_interface.rb:64:in `section'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:315:in `create_and_save_projects'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:307:in `generate_pods_project'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:183:in `integrate'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:170:in `install!'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/command/install.rb:52:in `run'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/command.rb:52:in `run'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/bin/pod:55:in `<top (required)>'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/bin/pod:25:in `load'

/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/bin/pod:25:in `<main>'


The above code is not working for me, any other solution

**Comment by losheredos** [comment]
_cd ios_

`bundle install`
then
`pod install`

solved the issue for me

**Comment by G3z** [comment]
This fixed the problem for me
https://github.com/facebook/react-native/commit/47b42dc84560aa66af4b7dcfa5886af66d175c3c
I applied the patch by hand

**Comment by zcmgyu** [comment]
@G3z Thanks. This worked for me after the upgrade from 0.74.1 to 0.74.2
