### ISSUE TITLE
Linking 'mailto' fails on Arabic chars in subject or body

### ISSUE THREAD

**Issue by saadalla** [facebook/react-native#38834]
### Description

I am using Linking to send email.

    const subject = 'Hello!';
    const body = 'Hello-World';
    const email = 'feedback@company.com';
    const url = `mailto:${email}?subject=${subject}&body=${body}`;

    console.log("Call Email",url);

    Linking.canOpenURL(url).then(supported => {
      if (supported) {
        Linking.openURL(
         url,
        );
      } else {
        console.log('Link not supported');
      }
    });

on IOS Simulator:
  Call Email mailto:feedback@company.com?subject=Hello!&body=Hello-World
  Link not supported

on Real Device:
  if latin text, email starts
  if a single Arabic letter is used in either subject or body, linking fails:

2023-08-08 10:19:11.825896+0300 ReproducerApp[1093:82746] -canOpenURL: failed for URL: "file:///private/var/containers/Bundle/Application/3D8C6C2C-8A93-4B38-839B-B16E6D0B0E35/ReproducerApp.app/mailto:feedback@comany.com%3Fsubject=Hello!&body=Hello-%D8%A7%D9%93%D8%AE%D9%85%D8%AD" 
- error: "The operation couldn’t be completed. (OSStatus error -10814.)"
2023-08-08 10:19:11.827546+0300 ReproducerApp[1093:82956] [javascript] Link not supported

### React Native Version

0.72.3

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
  OS: macOS 13.4.1
  CPU: (10) arm64 Apple M2 Pro
  Memory: 520.55 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.16.1
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.19
    path: /usr/local/bin/yarn
  npm:
    version: 9.5.1
    path: /usr/local/bin/npm
  Watchman:
    version: 2023.07.10.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /Users/saadalla/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.19
    path: /usr/bin/javac
  Ruby:
    version: 2.7.5
    path: /Users/saadalla/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.3
    wanted: 0.72.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

### Steps to reproduce

run code using Xcode on real iOS device
add any Arabic chars [آخنميشثص] to subject or body, email fails

### Snack, screenshot, or link to a repository

https://github.com/saadalla/RN-Linking-email-error.git

**Comment by jakex7** [comment]
Hi @saadalla, due to the fact that Arabic is not in a standard encoding, you need to use encodeURIComponent to convert specific characters into escape sequences representing the UTF-8 encoding of the character before executing the `Linking.canOpenURL`/`Linking.openURL` function, as shown in the example below:
```js
const email = 'feedback@company.com';
const subject = 'Hello!';
const body = 'آخنميشثص';
const url = `mailto:${email}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
Linking.openURL(url);
```
