### ISSUE TITLE
unable to build from source on react native 0.71.12

### ISSUE THREAD

**Issue by himanshuzeptonow** [facebook/react-native#38843]
### Description

I am trying to build from source, 
following https://reactnative.dev/contributing/how-to-build-from-source documentation 

gettting following error -> Project with path ':packages:react-native:ReactAndroid' not found in build 'react-native'.

### React Native Version

0.71.12

### Output of `npx react-native info`

System:
    OS: macOS 13.2.1
    CPU: (12) arm64 Apple M2 Pro
    Memory: 93.80 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.16.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.5.1 - /usr/local/bin/npm
    Watchman: 2023.07.03.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.3 AI-223.8836.35.2231.10406996
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.19 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.12 => 0.71.12
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce
https://github.com/himanshuzeptonow/build-from-source-repro
added 

+ includeBuild('../node_modules/react-native') {
+     dependencySubstitution {
+         substitute(module("com.facebook.react:react-android")).using(project(":packages:react-native:ReactAndroid"))
+         substitute(module("com.facebook.react:react-native")).using(project(":packages:react-native:ReactAndroid"))
+         substitute(module("com.facebook.react:hermes-android")).using(project(":packages:react-native:ReactAndroid:hermes-engine"))
+         substitute(module("com.facebook.react:hermes-engine")).using(project(":packages:react-native:ReactAndroid:hermes-engine"))
+     }
+ }

to gradle.settings, 
try to gradle sync project

### Snack, screenshot, or link to a repository

<img width="773" alt="Screenshot 2023-08-08 at 7 44 34 PM" src="https://github.com/facebook/react-native/assets/107403489/277d6235-2e9a-40e5-95c7-a66b6b79f852">

**Comment by himanshuzeptonow** [comment]
Reproduce on this - https://github.com/himanshuzeptonow/build-from-source-repro

**Comment by cortinico** [comment]
Those instructions are valid only for React Native 0.72
Please update the version and try again

**Comment by himanshuzeptonow** [comment]
> 

what we can do for 0.71.12 
can't update to latest version for now

**Comment by himanshuzeptonow** [comment]
we want to patch some changes to 0.71.12 any other way?

**Comment by himanshuzeptonow** [comment]
@cortinico Please lookinto this, we are blocked.

**Comment by cortinico** [comment]
> can't update to latest version for now

Building from source is supported only for 0.72
You can find the older documentation for 0.71 here, but that flow it's not officially supported (hence I'm closing this issue): 
https://github.com/facebook/react-native-website/pull/3659/files
