### ISSUE TITLE
Horizontal FlatList scrolls in the opposite direction of swipe

### ISSUE THREAD

**Issue by ryl** [facebook/react-native#38859]
### Description

On an Android device, when swiping back to the beginning of a FlatList with `horizontal={true}` the FlatList often scrolls in the opposite direction of your swipe, sending you away from the beginning and back towards end. The problem does not seem to occur on iOS.

https://github.com/ryl/carouselTest/assets/702146/3cc1a499-e90e-496d-982d-28ffc152c382

### React Native Version

0.72.3

### Output of `npx react-native info`

System:
  OS: macOS 13.3.1
  CPU: (10) arm64 Apple M1 Max
  Memory: 9.14 GB / 64.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 16.19.0
    path: ~/.nvm/versions/node/v16.19.0/bin/node
  Yarn:
    version: 1.22.19
    path: ~/.nvm/versions/node/v16.19.0/bin/yarn
  npm:
    version: 8.19.3
    path: ~/.nvm/versions/node/v16.19.0/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.12.1
    path: /Users/ryl/.rvm/gems/ruby-2.7.5/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK:
    API Levels:
      - "29"
      - "30"
      - "31"
      - "32"
      - "33"
    Build Tools:
      - 30.0.2
      - 30.0.3
      - 32.0.0
      - 32.1.0
      - 33.0.0
    System Images:
      - android-26 | Google APIs ARM 64 v8a
      - android-28 | Google APIs ARM 64 v8a
      - android-29 | Google APIs ARM 64 v8a
      - android-30 | Google APIs ARM 64 v8a
      - android-30 | Google Play ARM 64 v8a
      - android-31 | Google APIs ARM 64 v8a
      - android-32 | Google APIs ARM 64 v8a
      - android-32 | Google Play ARM 64 v8a
      - android-33 | Google APIs ARM 64 v8a
      - android-TiramisuPrivacySandbox | Google Play ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2022.1 AI-221.6008.13.2211.9619390
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.15
    path: /Users/ryl/.sdkman/candidates/java/current/bin/javac
  Ruby:
    version: 2.7.5
    path: /Users/ryl/.rvm/rubies/ruby-2.7.5/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.3
    wanted: 0.72.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

### Steps to reproduce

- Create a FlatList with the `horizontal={true}` flag
- Scroll to the end of the list.
- Scroll back to the beginning.
- Note that you are often scrolled back towards the end if you swipe towards the beginning after reaching the beginning.

### Snack, screenshot, or link to a repository

https://github.com/ryl/carouselTest

**Comment by james-cohen** [comment]
Having exactly the same issue on Android.

After experimenting further, the problem only occurs if you try to swipe beyond the final element in the list. When you return to the 0th element, it performs the reverse scroll once for each time you tried to "over swipe" i.e. If i swipe past the final element 3 times, the reverse swipe will happen on the 0th element 3 times and then stop

**Comment by NickGerleman** [comment]
Fixed at L612 in https://github.com/facebook/react-native/commit/30c7e9dfa41348e96e946384c76f038ccd859896

**Comment by Leena-Sharma-rsys** [comment]
hii, having the similar issue on 0.69.6

**Comment by FouadMagdy01** [comment]
Did you find a solution?
I am also facing the same problem

**Comment by limyira** [comment]
It's a temporary solution, but try setting it to <Flatlist overScrollMode="never"/>

**Comment by limyira** [comment]
안녕하세요

**Comment by limyira** [comment]
It's a temporary solution, but try setting it to <Flatlist overScrollMode="never"/>

**Comment by FouadMagdy01** [comment]
The issue was fixed in the latest RN version
