### ISSUE TITLE
I can't open Chrome to debug 

### ISSUE THREAD

**Issue by iplus26** [facebook/react-native#3885]
It worked fine yesterday, but not since today. 

When I opened Chrome and <kbd>⌘+D</kbd> in my iOS Simulator, the Chrome shows 'Page couldn't be opened' while the simulator shows error. 

![chrome error](https://cloud.githubusercontent.com/assets/6082721/10937676/941ed0f6-832f-11e5-8c16-80a41adc0edc.png)
<img width="393" alt="simulator error" src="https://cloud.githubusercontent.com/assets/6082721/10937685/a13b2ff0-832f-11e5-83e7-b7f5b1cc95c0.png">
<img width="762" alt="node error" src="https://cloud.githubusercontent.com/assets/6082721/10937703/b7efc97c-832f-11e5-8da7-d0d903bb2fe7.png">

However, Safari can visit the `http://localhost:8081/debugger-ui` page. 

I don't know what is wrong and any help will be appreciate!

**Comment by mihirsoni** [comment]
Hi , 

If you restart everything properly it should work properly.
Please use http://stackoverflow.com/ with react-native tags to get answer.

**Comment by christopherdro** [comment]
@iplus26 
@mihirsoni Is right. This usually happens when you have a tab open from a previous packager instance. Close chrome and try rebuilding the project.

**Comment by iplus26** [comment]
@mihirsoni @christopherdro I have restarted my computer and the project for many times but it still doesn't work.

**Comment by iplus26** [comment]
I don't know why but it works now.
