### ISSUE TITLE
Plugin [id: 'org.jetbrains.kotlin.jvm', version: '1.7.22'] was not found in new CLI generated project

### ISSUE THREAD

**Issue by daileytj** [facebook/react-native#38853]
### Description

I am getting the following output when building the out-of-the-box CLI project on Android.

```
Build file '.../AwesomeProject/node_modules/@react-native/gradle-plugin/build.gradle.kts' line: 13

Plugin [id: 'org.jetbrains.kotlin.jvm', version: '1.7.22'] was not found in any of the following sources:

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Exception is:
org.gradle.api.plugins.UnknownPluginException: Plugin [id: 'org.jetbrains.kotlin.jvm', version: '1.7.22'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin:1.7.22')
  Searched in the following repositories:
    MavenRepo
    Google
    Gradle Central Plugin Repository
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.resolveToFoundResult(DefaultPluginRequestApplicator.java:237)
```

### React Native Version

0.72.3

### Output of `npx react-native info`

```
System:
  OS: macOS 13.4
  CPU: (12) arm64 Apple M2 Pro
  Memory: 95.66 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 16.20.1
    path: /opt/homebrew/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 8.19.4
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2023.07.10.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /Users/<redacted>/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10406996
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.20
    path: /usr/bin/javac
  Ruby:
    version: 3.2.0
    path: /Users/<redacted>/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.3
    wanted: 0.72.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Steps to reproduce

```npx react-native@latest init AwesomeProject```
```yarn android```

### Snack, screenshot, or link to a repository

I'm not even getting the out-of-the-box CLI project to run on android so there isn't a snack or screenshot that is relevant to the issue.

https://github.com/daileytj/reproducer-react-native

**Comment by cortinico** [comment]
The CI for the project you shared is green:
https://github.com/daileytj/reproducer-react-native/actions/runs/5799873078/job/15720809672

Is this happening for any project you use?

**Comment by daileytj** [comment]
> The CI for the project you shared is green: https://github.com/daileytj/reproducer-react-native/actions/runs/5799873078/job/15720809672
> 
> Is this happening for any project you create?

Yes, turns out this was a proxy issue with android studio.

**Comment by michaeljr007** [comment]
> > The CI for the project you shared is green: https://github.com/daileytj/reproducer-react-native/actions/runs/5799873078/job/15720809672
> > Is this happening for any project you create?
> 
> Yes, turns out this was a proxy issue with android studio.

Hello. I'm facing the exact issue. How did you fix yours?

**Comment by lukakkyk** [comment]
hello, i have this issue, m1 pro, Ventura any fixes?

**Comment by lucasArena** [comment]
I'm having a similar problem, but with a different version.

`System:
    OS: macOS 13.2
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 40.59 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
    Watchman: 2023.09.04.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK:
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2022.3 AI-223.8836.35.2231.10671973
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.20.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.7 => 0.68.7 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found`
    
    
   Here is the message
   `FAILURE: Build failed with an exception.

* Where:
Build file '/Users/lucas.santos-sc@airliquide.com/Projects/Airliquide/DeltaMobile/node_modules/react-native-gradle-plugin/build.gradle.kts' line: 11

* What went wrong:
Plugin [id: 'org.jetbrains.kotlin.jvm', version: '1.6.10'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Included Builds (None of the included builds contain this plugin)
- Plugin Repositories (could not resolve plugin artifact 'org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin:1.6.10')
  Searched in the following repositories:
    MavenRepo
    Google
    Gradle Central Plugin Repository

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s`

**Comment by joselmarianocreateape** [comment]
same here :(

**Comment by SruthiVj** [comment]
Facing exact same issue

**Comment by AndersonVanzo** [comment]
For me the problem was that I had the Gradle Offline Mode on, found this solution [here](https://stackoverflow.com/a/73682835/14671422)

**Comment by williamgurzoni** [comment]
If that helps someone: I was having the same issue and as funny as it sounds, the problem was my firewall.

**Comment by sqeedward** [comment]
I am proud to say : Same here :)

**Comment by kneel2023** [comment]
[React Native](https://reactnative.dev/docs/environment-setup) says:
If you already have a JDK on your system, we recommend JDK17. You may encounter problems using higher JDK versions.

If you're using the latest version of Java Development Kit, you'll need to change the Gradle version of your project so it can recognize the JDK. You can do that by going to`{project root folder}\android\gradle\wrapper\gradle-wrapper.properties` and changing the distributionUrl value to upgrade the Gradle version. You can check out [here the latest releases of Gradle](https://gradle.org/releases/).

Things that worked for me was to run the following command :
`choco install -y microsoft-openjdk17`
 to install the correct version of JDK and install the required Android SDK's and ensure that they are corrctly present in the environment Variables.

Copy and paste Get-ChildItem -Path Env:\ into powershell to verify that JAVA_HOME and ANDROID_HOME path is present in environment variables

Result should look like this:
![Screenshot 2024-03-19 174745](https://github.com/facebook/react-native/assets/148936893/7f7e96fc-4eea-47e6-ad94-19a694127573)

Hope it solves your Problem

Thanks,
Keep Coding

**Comment by kneel2023** [comment]
> still not resolve

Can you provide more information about the environment and other steps you are following

**Comment by Platycodon** [comment]
> [React Native](https://reactnative.dev/docs/environment-setup) says: If you already have a JDK on your system, we recommend JDK17. You may encounter problems using higher JDK versions.
> 
> If you're using the latest version of Java Development Kit, you'll need to change the Gradle version of your project so it can recognize the JDK. You can do that by going to`{project root folder}\android\gradle\wrapper\gradle-wrapper.properties` and changing the distributionUrl value to upgrade the Gradle version. You can check out [here the latest releases of Gradle](https://gradle.org/releases/).
> 
> Things that worked for me was to run the following command : `choco install -y microsoft-openjdk17` to install the correct version of JDK and install the required Android SDK's and ensure that they are corrctly present in the environment Variables.
> 
> Copy and paste Get-ChildItem -Path Env:\ into powershell to verify that JAVA_HOME and ANDROID_HOME path is present in environment variables
> 
> Result should look like this: ![Screenshot 2024-03-19 174745](https://github.com/facebook/react-native/assets/148936893/7f7e96fc-4eea-47e6-ad94-19a694127573)
> 
> Hope it solves your Problem
> 
> Thanks, Keep Coding

work for me. i used java11

**Comment by sheshaAthenaDev** [comment]
For anyone else having issues with this, after a couple of days of troubleshooting I just opened Android Studio and clicked on "Download Sources" and this finally seemed to download the JVM for me. Nothing else worked, neither yarn build or downloading any other version of JDK, or doing a gradle cleanup. Here's the config that I'm on-

RN Version- 0.72
JDK- 11 (installed using homebrew via `brew install openjdk@11`)

<img width="335" alt="Image" src="https://github.com/user-attachments/assets/bd8bb032-631b-4dde-b4a7-abf9c32206c2" />
