### ISSUE TITLE
Push Notification for Android.

### ISSUE THREAD

**Issue by vaibhavmule** [facebook/react-native#3886]
I have searched a lot and not able to find impementation of Push Notification for Android in React-Native.

**Comment by yychun1217** [comment]
you need to implement it in the native side, PushNotification is only supported in iOS currently, as in PushNotificationIOS

**Comment by vaibhavmule** [comment]
How do I go about implement in native side?

**Comment by ehourigan** [comment]
@vaibhavmule start here:
https://developers.google.com/cloud-messaging/android/client
https://facebook.github.io/react-native/docs/native-modules-android.html#content

**Comment by brentvatne** [comment]
This is listed in our known issues: https://facebook.github.io/react-native/docs/known-issues.html#modules

So it's on the roadmap! :smile:
