### ISSUE TITLE
New asset system uses incorrect bundle

### ISSUE THREAD

**Issue by negativetwelve** [facebook/react-native#3888]
I've been working on compiling the app I'm working on for production purposes with the new asset system and I have been running into an issue. The images show up in development mode but do not show up at all (and no warning) when built for production.

I found the problem but am not sure if this is the correct solution. The production app is using the wrong bundle to find the assets. This might be because I'm using cocoapods (treating react as a dynamic framework) but I haven't quite figured out if that's the cause or not.

Using:

```
[NSBundle bundleForClass[self class]] ...
```

[on this line](https://github.com/facebook/react-native/blob/c5b990f65f0791041378a61cd503ccf686b00bb1/React/Base/RCTConvert.m#L104) is causing my app to look up assets in `.../React.framework/assets/...` instead of `.../MyApp.app/assets.../`

Switching the bundle back to `[NSBundle mainBundle]` does fix the issue for me but I'm not sure if that's the overall correct fix. Any guidance here would be appreciated, I'd love to help fix this up with a PR.

cc @javache & @nicklockwood

**Comment by nicklockwood** [comment]
Yeah, this should probably be [NSBundle mainBundle] given that it's typically used for images, which only work from the mainBundle.

**Comment by nicklockwood** [comment]
I can't remember exactly why it was changed to bundleForClass though. @javache, do you recall?

**Comment by javache** [comment]
Yeah, we changed this to bundleForClass so the URL resolving would work correctly when invoked from a test bundle. We made some changes afterwards to how we load images with imageNamed: afterwards so this might no longer be necessary.

Running the unit tests should show if it's safe to change this.

**Comment by negativetwelve** [comment]
sweet, should I go ahead and only change this one line? there were a bunch more instances in [this commit](https://github.com/facebook/react-native/commit/9076b71ac307d2a45b30efec41414862638c6aeb#diff-99f3601ec9fb0cc23570af725a27781e) where we're using `resourcePath`. Should those be changed as well?

**Comment by nicklockwood** [comment]
I think the ones in RCTAssetBundleImageLoader.m and RCTImageDownloader have already been changed (those classes no longer exist, actually).

**Comment by nicklockwood** [comment]
You'll probably have to change RCTConvert_NSURLTests.m too because that's specifically testing the output of the [RCTConvert NSURL:] function!

**Comment by negativetwelve** [comment]
oh yeah definitely right about the test + missing classes. Made the changes and submitted at #3889!

**Comment by ippy04** [comment]
:+1:

**Comment by ippy04** [comment]
This was breaking not only assets using the new packaging mode but also static assets being loaded from Images.xcassets after I upgraded to 0.13.0. (using cocopods). This fix saved me from 24 hours of frustration - thanks!

**Comment by hswolff** [comment]
Just found this issue after spelunking down the RN code base for the past hour. Glad to see it's fixed! Just wish I had found this before going down that rabbit hole ;).

Would it be possible to release this on the `0.14.0` branch as it is broken?
