### ISSUE TITLE
"TypeError: undefined is not a function" from react-native-camera

### ISSUE THREAD

**Issue by ajdnakljdkjasdnasdad** [facebook/react-native#38897]
### Description

I have been trying to use react-native-camera in my react native project but whenever I try to load RNCamera in the code it immediately throws a "TypeError: undefined is not a function". I have checked all my dependencies and they are properly installed so that is not the issue. I also get this error "ViewPropTypes will be removed from React Native, along with all other PropTypes. We recommend that you migrate away from PropTypes and switch to a type system like TypeScript. If you need to continue using ViewPropTypes, migrate to the 'deprecated-react-native-prop-types' package." whenever I first load the app. Any help would be appreciated, thanks in advance.

code:

```
import React, { useRef, useState } from 'react';
import { View, Text, StyleSheet } from 'react-native';
import { RNCamera } from 'react-native-camera';

export default TextScanner = () => {
  const cameraRef = useRef(null);

 return (
   <View style={{ flex: 1 }}>
     <RNCamera ref={cameraRef} style={{ flex: 1 }} />
     <View style={{ position: 'absolute', bottom: 0 }}>
     </View>
   </View>
 );
};
```

### React Native Version

0.71.8

### Output of `npx react-native info`

System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 13th Gen Intel(R) Core(TM) i7-13620H
    Memory: 4.21 GB / 15.70 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 9.8.1 - ~\OneDrive\Dokument\VisulaStudio Projects\FoodCheck\node_modules\.bin\npm.CMD        
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: AI-223.8836.35.2231.10406996
    Visual Studio: Not Found
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.8 => 0.71.8
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
info React Native v0.72.3 is now available (your project is running on v0.71.8).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.72.3
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.71.8
info For more info, check out "https://reactnative.dev/docs/upgrading".

### Steps to reproduce

npm start

### Snack, screenshot, or link to a repository

Error: ViewPropTypes will be removed from React Native, along with all other PropTypes. We recommend that you migrate away from PropTypes and switch to a type system like TypeScript. If you need to continue using ViewPropTypes, migrate to the 'deprecated-react-native-prop-types' package.

TypeError: undefined is not a function
TypeError: undefined is not a function

**Comment by ajdnakljdkjasdnasdad** [comment]
Did not realize the react-native-camera was deprecated

**Comment by songssong** [comment]
@ajdnakljdkjasdnasdad have you found a solution??
