### ISSUE TITLE
How to get and execute a  js file thorough async request 

### ISSUE THREAD

**Issue by iostalk** [facebook/react-native#389]
Maybe it will become something like lua Hotpatch ,update app online

**Comment by amasad** [comment]
We have plans to do that. For production it's a bit tricky and needs some thought.
Do you want it for production or development use?

**Comment by iostalk** [comment]
Production use, because my product managers hope publish every week

**Comment by jhdxr** [comment]
@amasad , is there any possibility to execute another js in main.jsbundle now?

**Comment by amasad** [comment]
@jhdxr what do you mean by that? You can always `require` modules. If you want to dynamically load files you can use XHR and eval

**Comment by jsierles** [comment]
After some tests using eval, I couldn't get it to work for hot reloading an RN app from javascript. It's probably a safer solution to load a new native js context. [Here's some sample code](https://gist.github.com/jsierles/53fd0514d6f48e0c5872) from the http://rnplay.org iOS app that implements this in Objective C and exports a method for its use.

You could use a similar method to load a downloaded bundle.

**Comment by amasad** [comment]
@jsierles don't most async JS loaders do xhr+eval? I'm sure require.js and webpack do. The old ones too (like LAB.js etc)

**Comment by jsierles** [comment]
@amasad yep they do. I think what jhdxr meant was loading an whole new app bundle, replacing the current one. I tried this by evaluating fetched javascript in a simple test in React Native and nothing happened. No console output, nor did the app reload. It was not a very good test, I'll admit, so might be worth looking into more.

That said, loading a new js context works pretty well for us. [Here's a more involved example](https://github.com/rnplay/rnplay-ios/blob/master/iOS/AppDelegate.m) where we switch between RCTRootViews which have their own JS context.

**Comment by amasad** [comment]
Oh cool. cc @philikon who could be interested in this.
