### ISSUE TITLE
Error When Trying to Run React Native Project - Support Issue

### ISSUE THREAD

**Issue by dszcarlin** [facebook/react-native#38906]
### Description

Hello React Native project support team,

I am encountering an issue when trying to run my React Native project and would like to seek assistance in resolving it. Here are the details of the error I am facing:

Error:

vbnet
Copy code
info 💡 Tip: Make sure that you have set up your development environment correctly, by running react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor

:ReactNative:Unexpected empty result of running '[node, C:\Users\carlo\OneDrive�?rea de Trabalho\Pessoal\barbersoft-app\node_modules@react-native-community\cli\build\bin.js, config]' command.
:ReactNative:Running '[node, C:\Users\carlo\OneDrive�?rea de Trabalho\Pessoal\barbersoft-app\node_modules@react-native-community\cli\build\bin.js, config]' command failed.

FAILURE: Build failed with an exception.

Where:
Script 'C:\Users\carlo\OneDrive�rea de Trabalho\Pessoal\barbersoft-app\node_modules@react-native-community\cli-platform-android\native_modules.gradle' line: 389

What went wrong:
A problem occurred evaluating script.
node:internal/modules/cjs/loader:1078  throw err;  ^Error: Cannot find module 'C:\Users\carlo\OneDriveÃ�rea de Trabalho\Pessoal\barbersoft-app\node_modules@react-native-community\cli\build\bin.js'    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)    at Module._load (node:internal/modules/cjs/loader:920:27)    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)    at node:internal/main/run_main_module:23:47 {  code: 'MODULE_NOT_FOUND',  requireStack: []}Node.js v18.14.2

Try:
Run with --stacktrace option to get the stack trace.
Run with --info or --debug option to get more log output.
Run with --scan to get full insights.
After running the diagnosis using the react-native doctor command, I received the following result:

Diagnosis:

✓ Node.js - Required to execute JavaScript code
✓ npm - Required to install NPM dependencies

Android
✓ Adb - Required to verify if the android device is attached correctly
✓ JDK - Required to compile Java code
✓ Android Studio - Required for building and installing your app on Android
✖ Android SDK - Required for building and installing your app on Android

Versions found: N/A
Version supported: 33.0.0
✓ ANDROID_HOME - Environment variable that points to your Android SDK installation
Errors: 1
Warnings: 0

Request:

I am seeking assistance to resolve the error I am encountering when attempting to run my React Native project. The error seems to be related to the location of a specific module within the @react-native-community/cli package. I have already verified the installation of Node.js, npm, and the Android environment dependencies as suggested by the react-native doctor command.

I kindly request guidance on resolving this issue and being able to successfully run my project. Any help or direction you can provide would be greatly appreciated.

Thank you very much for your attention and assistance!

Best regards,
Carlos Almeida

### React Native Version

0.72.3

### Output of `npx react-native info`

System:
  OS: Windows 10 10.0.22621
  CPU: (8) x64 Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz
  Memory: 1.23 GB / 7.75 GB
Binaries:
  Node:
    version: 18.14.2
    path: C:\Program Files\nodejs\node.EXE
  Yarn: Not Found
  npm:
    version: 9.5.0
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK: Not Found
IDEs:
  Android Studio: AI-223.8836.35.2231.10406996
  Visual Studio: Not Found
Languages:
  Java: 11.0.20
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.3
    wanted: 0.72.3
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

### Steps to reproduce

Make de evironment setup and try to run a react-native project

### Snack, screenshot, or link to a repository

![Captura de tela 2023-08-09 162117](https://github.com/facebook/react-native/assets/101726446/1b676076-345f-4795-aa1a-b1f4b0f7f0cc)
![Captura de tela 2023-08-09 162131](https://github.com/facebook/react-native/assets/101726446/4df08411-6951-44f0-b93c-695a209f365f)
![image](https://github.com/facebook/react-native/assets/101726446/368e025d-caea-4585-8775-ba689a3ced30)

**Comment by Jarvie789** [comment]
Can you try installing command-line Tools 10.0 and adding it to your environment variables?

However, even if the react-native doctor fails the check, the new project can still run normally. I don't know the specific reason for the time being.

**Comment by cortinico** [comment]
Hi @dszcarlin 
This issue is related to the React Native CLI.

Please open this issue against this other repository:
https://github.com/react-native-community/cli/issues

And you can get support over there for this specific issue.

**Comment by tewodrosasfaw** [comment]
please give the support for this error

**Comment by estebansabo** [comment]
I have the exact same problem!

**Comment by PastorCoder** [comment]
I have the same problem, i have not found solution.

**Comment by Jobaer-hassan-orangetoolz** [comment]
same problem here.
info 💡 Tip: Make sure that you have set up your development environment correctly, by running npx react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor 


info Run CLI with --verbose flag for more details.

**Comment by amaldominic816** [comment]
To resolve this issue Open workspace in xcode and try to build 
If the Build Fssiled You can see the issues 
Solve it and Clean Project And rebuild it if the Build Success The Go to you project and Stsrt running And It will Run Smoothly 

In My case I did'nt link the Assets/font to ios 
To link it I Run the Command For those running on react-native version >= 0.69.x, Since link is deprecated so react-native link will not work anymore, the command react-native link is replaced by `npx react-native-asset`.

Let me know if the Issue Resolved
