### ISSUE TITLE
Property 'document' doesn't exist - iOS only

### ISSUE THREAD

**Issue by SavinienBarbotaud** [facebook/react-native#38917]
### Description

I know it's look like the common mistake.

Append on iOS only, android version work fine.

I search on my project to see if im using 'document' statement somewhere but never found it.

### React Native Version

0.72.3

### Output of `npx react-native info`

System:
  OS: macOS 13.5
  CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Memory: 25.20 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.17.0
    path: /usr/local/bin/node
  Yarn: Not Found
  npm:
    version: 9.8.1
    path: /usr/local/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.12.1
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java: Not Found
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.3
    wanted: 0.72.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: false
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

### Steps to reproduce

Start a react-native project on linux.
import necessary libs (npm list bottom)

Moving to iOS : npm run iOS, compiling is fine the error is show up when the app launch

### Snack, screenshot, or link to a repository

output of npm list, maybe some package are wrong but don't know why : 
├── @apirtc/apirtc@5.0.13
├── @babel/core@7.22.5
├── @config-plugins/react-native-webrtc@6.0.0
├── @expo/webpack-config@18.1.0
├── @notifee/react-native@7.8.0
├── @react-native-picker/picker@2.4.8
├── expo-splash-screen@0.18.2
├── expo-status-bar@1.4.4
├── expo@48.0.20
├── hermes-engine@0.11.0
├── react-dom@18.2.0
├── react-native-device-info@10.6.0
├── react-native-gesture-handler@2.12.1
├── react-native-svg@13.9.0
├── react-native-web@0.18.12
├── react-native-webrtc@111.0.1
├── react-native@0.72.3
├── react@18.2.0
└── socket.io-client@4.6.2

**Comment by cortinico** [comment]
> I search on my project to see if im using 'document' statement somewhere but never found it.

Can you share more information on your code and the exact error message?
Also please provide a reproducer.

**Comment by SavinienBarbotaud** [comment]
Hi,
sorry for the late response, one of my dependencies have a web dependencies.
The package was marked supported by react-native.
