### ISSUE TITLE
App crash: parameter must be a descendant of this view

### ISSUE THREAD

**Issue by vladimir-vasilev** [facebook/react-native#38925]
### Description

cannot reproduce by myself, this is the report from Firebase Crashlytics:

Fatal Exception: java.lang.IllegalArgumentException
parameter must be a descendant of this view

android.view.ViewGroup.offsetRectBetweenParentAndChild (ViewGroup.java:6326)
android.view.ViewGroup.offsetDescendantRectToMyCoords (ViewGroup.java:6245)
android.view.ViewRootImpl.scrollToRectOrFocus (ViewRootImpl.java:4554)
android.view.ViewRootImpl.draw (ViewRootImpl.java:4120)
android.view.ViewRootImpl.performDraw (ViewRootImpl.java:3964)
android.view.ViewRootImpl.performTraversals (ViewRootImpl.java:3228)
android.view.ViewRootImpl.doTraversal (ViewRootImpl.java:2079)
android.view.ViewRootImpl$TraversalRunnable.run (ViewRootImpl.java:8416)
android.view.Choreographer$CallbackRecord.run (Choreographer.java:972)
android.view.Choreographer.doCallbacks (Choreographer.java:796)
android.view.Choreographer.doFrame (Choreographer.java:731)
android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:957)
android.os.Handler.handleCallback (Handler.java:938)
android.os.Handler.dispatchMessage (Handler.java:99)
android.os.Looper.loop (Looper.java:223)
android.app.ActivityThread.main (ActivityThread.java:7989)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:635)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:947)

reproduces on some devices like Samsung Galaxy A03 Core, ZTE Blade A3 2019 android v. 8,9,11,12

### React Native Version

0.71.2

### Output of `npx react-native info`

no problem with my own environment

### Steps to reproduce

cannot reproduce by myself

### Snack, screenshot, or link to a repository

cannot provide

**Comment by cortinico** [comment]
Duplicates #32649

Sadly, without a reproducer we can't fix this in any form practically.
