### ISSUE TITLE
Different fontSize in simulator than physical device

### ISSUE THREAD

**Issue by patoroco** [facebook/react-native#3892]
We're having some issues related to font sizing, because it's rendered differently in iOS simulator than in the device.

I created a small app to reproduce it (https://rnplay.org/apps/VP0enw), including only a Text component with fontSize = 40.

Left side is how  the app looks in iPhone 6 (iOS 9.1), and at the right is the same app running in  simulator (iPhone 6, iOS 9.1). (updated with the correct image. Thanks @ide )

<img width="1115" alt="screen shot 2015-11-04 at 22 23 19" src="https://cloud.githubusercontent.com/assets/701909/10952435/fd9f476e-8342-11e5-89c1-41d1032fa802.png">

I ran the same app on android simulator / android device, and apparently returns the same result without issues, but in our real-app it returns some different sizes too (I didn't found a pattern for that issue on android).

I was reading about [Pixel Ratio](https://facebook.github.io/react-native/docs/pixelratio.html), but I don't think that this is the issue, because simulator and physical device represent the same device (iPhone 6 in this case).

Any suggestion about what is happening?

**Comment by ide** [comment]
You might not be running the same code -- your screenshot on the right is missing a colon after fontSize. I'm not sure what else could be the cause here.

**Comment by patoroco** [comment]
I just updated image with two correct snapshops. I was doing several tests to reproduce the issue, and I choose bad when I compose image with comparation, thanks @ide for your advise.

Anyway, it's easy to reproduce the issue render a simple `Text` component as follows:

```
<View style={{ justifyContent: 'center', flex: 1}}>
   <Text style={{ alignSelf: 'center', fontSize: 40, backgroundColor: 'red' }}>fontSize: 40</Text>
 </View>
```

**Comment by patoroco** [comment]
Finally I found the source of my problems: Dynamic Type.

It's a feature introduced on iOS7 which allows to user to change size of font "multiplier" depending his preferences. Here is a [good article talking about how to implement it](http://useyourloaf.com/blog/supporting-dynamic-type.html).

I usually designed UI with storyboard (before react-native), so I've never had this "problem", but some similar happens on Android, so I suppose that there are the same feature on android too.


Please, feel free to close this issue :)

**Comment by ide** [comment]
Good to know that was the issue. Thanks for following up!

**Comment by uc-hus** [comment]
Hello,
I'm working for android UI. My UI showing correct in emulator but its not showing correctly in real device. I think this is pixel ratio issue, Currently I'm using 5.5" Android device.  Please help!
![image](https://cloud.githubusercontent.com/assets/12196308/18609975/ba06fe7c-7d2c-11e6-9d48-70bd6d87fe89.png)
![image](https://cloud.githubusercontent.com/assets/12196308/18609979/f318dc62-7d2c-11e6-880d-f4e620f73ced.png)

**Comment by siddharthchugh** [comment]
Hi,

Place the EditText of both fields in LInearLayouts in vertical orientation
that's it and place the button below the Linear layout. The UI will display
correct. Make the RelativeLayout your parent in xml.

Hope this helps you, as I have done this a long time ago.

Regards,

Siddharth Chugh.

**Comment by uc-asa** [comment]
Hi Siddharth,

In which file change linear layout to relative layout and  how. Plz provide steps

**Comment by uc-hus** [comment]
Hello,
Please reply if anyone have solution.

**Comment by shridharmalagi** [comment]
Did you try **Pixel Ratio** ?

**Comment by uc-asa** [comment]
Hi,

I have done by using following code


import React from "react-native";

import {
	Dimensions,
	Platform
} from 'react-native';

let { height, width }   = Dimensions.get('window');
const deviceType 			= Platform.OS === 'ios' ? true : false ;

if( width > height ) {
	height = width;
	width = height;
}

// Calculating ratio from iPhone breakpoints
const ratioX = deviceType ? ( width < 550 ? ( width < 430 ? ( width < 375 ? (width < 320 ? 0.75 : 0.875) : 1 ) : 1.125 ) : 1.25 ) : 1;
const ratioY = deviceType ? ( height < 800 ? ( height < 640 ? ( height < 568 ? (height < 480 ? 0.75 : 0.875) : 1 ) : 1.125 ) : 1.25 ) : 1;

// We set our base font size value
const base_unit = 16;

// We're simulating EM by changing font size according to Ratio
const unit = base_unit * ratioX;

// We add an em() shortcut function 
function em(value) {
  return unit * value;
}
// Then we set our styles with the help of the em() function
export default Style = {
  // FONT
  FONT_SIZE				: em(1),
  FONT_SIZE_SMALLER		: em(0.75),
  FONT_SIZE_SMALL		: em(0.875),
  FONT_SIZE_TITLE		: em(1.25),
  
};

**Comment by yasir-netlinks** [comment]
@uc-hus Hi , can you please show an example of how to use this ?
