### ISSUE TITLE
rbenv: pod: command not found  The `pod' command exists in these Ruby versions:   2.7.6

### ISSUE THREAD

**Issue by MiteshJabuani** [facebook/react-native#38921]
### Description

when pod install command fire

### React Native Version

0.70.1

### Output of `npx react-native info`

<img width="373" alt="Screenshot 2023-08-10 at 5 45 21 PM" src="https://github.com/facebook/react-native/assets/34374930/575d9d24-7fe8-4122-bde4-0027bf6c964c">

### Steps to reproduce

<img width="373" alt="Screenshot 2023-08-10 at 5 45 21 PM" src="https://github.com/facebook/react-native/assets/34374930/6ee96741-5ba5-4891-b389-5b77ceaf083f">

### Snack, screenshot, or link to a repository

<img width="373" alt="Screenshot 2023-08-10 at 5 45 21 PM" src="https://github.com/facebook/react-native/assets/34374930/b856563c-1a0f-4a18-83a1-0c60aeea0916">

**Comment by cortinico** [comment]
Please follow the setup instructions from this page,
https://reactnative.dev/docs/environment-setup?guide=native&os=macos&platform=ios#creating-a-new-application

Specifically you should be running: `bundle install && bundle exec pod install` as suggested
