### ISSUE TITLE
AlertIOS to Support Additional UIAlertViewStyle

### ISSUE THREAD

**Issue by cancan101** [facebook/react-native#3893]
Currently `UIAlertViewStyleDefault` and `UIAlertViewStylePlainTextInput` are supported but not: `UIAlertViewStyleSecureTextInput` or `UIAlertViewStyleLoginAndPasswordInput`.

**Comment by gpbl** [comment]
Yes this would be a nice addition. If you look at https://github.com/facebook/react-native/blob/master/React/Modules/RCTAlertManager.m it doesn't seem hard to add this option.

**Comment by christopherdro** [comment]
Worked on this a bit the other day and have it working where we can have the follow type options:
`'plain-text', 'secure', 'login-password'`

I would like to improve upon it before making a PR so hopefully I can get that out soon.

**Comment by christopherdro** [comment]
This feature has been merged into master thanks to the help of @nicklockwood.
