### ISSUE TITLE
Access ApplicationContext from within NativeModule

### ISSUE THREAD

**Issue by beatscode** [facebook/react-native#3895]
I have an existing android application and I've built a view using react native. In the RN UI I have a button that I'd like,when clicked, to navigate to an activity that is not managed by react native. Is this possible?

I have created a native module already to do some other things. So i've been able to talk back and forth . How should I gain access to the Application Context from within a class that extends ReactContextBaseJavaModule?

**Comment by satya164** [comment]
You can just call the method `getApplicationContext`, e.g. -

```java
mReactContext.getApplicationContext();
```

**Comment by christopherdro** [comment]
@facebook-github-bot answered
