### ISSUE TITLE
Suspense's fallback component is never displayed

### ISSUE THREAD

**Issue by pritsawa** [facebook/react-native#38976]
### Description

I am trying to use Suspense with react native's new architecture for ios. 

Below is my code

  ```
<Suspense
        fallback={
          <View style={{height: '100%', width: '100%', alignItems: 'center'}}>
            <ActivityIndicator size="large" color={'#00ff00'} />
          </View>
        }>
        <MyComponents />
      </Suspense>
```

I have enabled the new architecture but the fallback component is never displayed 

### React Native Version

0.72.3

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
  OS: macOS 13.5
  CPU: (8) x64 Apple M1
  Memory: 16.04 MB / 8.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.17.0
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.19
    path: /usr/local/bin/yarn
  npm:
    version: 9.6.7
    path: /usr/local/bin/npm
  Watchman:
    version: 2023.07.10.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /Users/transformhub/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK:
    Android NDK: 22.1.7171670
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10406996
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: javac 16
    path: /usr/bin/javac
  Ruby:
    version: 2.7.6
    path: /Users/transformhub/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.3
    wanted: 0.72.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: true

### Steps to reproduce

Create  a react native project
Enable new architecture

Wrap any async  component with Supense and add a fallback

### Snack, code example, screenshot, or link to a repository

https://github.com/pritsawa/reactnativesuspense

**Comment by hanarotg** [comment]
i think... 

this is not a problem of react-native. `Suspense` is not used correctly in your project.

in [https://react.dev/reference/react/Suspense](https://react.dev/reference/react/Suspense)

> Suspense does not detect when data is fetched inside an Effect or event handler.

## Sample

I made a sample example of applying `Suspense` based on your project. 

You can check it out.

<details>
<summary>MyComponents.tsx code</summary>

```typescript
import React, {useEffect, useState} from 'react';
import {FlatList, Text} from 'react-native';

const MyComponent = () => {
  const [data, setData] = useState([]);

  // wrapPromise
  const wrapPromise = (promise: Promise<any>) => {
    let status = 'pending';
    let result: Promise<any>;

    const suspender = promise.then(
      res => {
        status = 'success';
        result = res;
      },
      err => {
        status = 'error';
        result = err;
      },
    );

    return () => {
      switch (status) {
        case 'pending':
          throw suspender;
        case 'error':
          throw result;
        default:
          return result;
      }
    };
  };

  const callApi = async () => {
    const url = 'https://jsonplaceholder.typicode.com/todos';

    const response = await fetch(url);
    const result = await response.json();
    return result;
  };

  useEffect(() => {
    const dataPromise = callApi();
    setData(wrapPromise(dataPromise));
  }, []);

  return (
    <FlatList
      data={data}
      renderItem={({item}) => <Text>{item.title}</Text>}
      keyExtractor={item => String(item.id)}
    />
  );
};

export default MyComponent;
```

</details>

<img src="https://github.com/facebook/react-native/assets/34812887/bf6700c5-e4cf-4916-81fc-e3dac155d17e" width="360px;"/>

**Comment by pritsawa** [comment]
Thanks, man this is complicated. I wish it was more simple
