### ISSUE TITLE
Documentation missed the openDrawer() and closeDrawer() functions of DrawerLayoutAndroid

### ISSUE THREAD

**Issue by ACCTFORGH** [facebook/react-native#3897]
These two functions are working and useful for pulling out and closing the drawer as the name suggests. However, I was not able to find formal documentation of these two in the RN website. I suggest an update to the doc about these two functions.

**Comment by satya164** [comment]
@ACCTFORGH Can you send a pull request?

**Comment by golorry** [comment]
@satya164  sure will do.

**Comment by ACCTFORGH** [comment]
@satya164  sure will do.
