### ISSUE TITLE
iOS Text Input - Secure Text Input

### ISSUE THREAD

**Issue by pangers** [facebook/react-native#3898]
Hi, in my UI I have a TextInput and Button. The onPress of the button toggles a state called secureTextEntry like so:

this.setState({ secureTextEntry: !this.secureTextEntry });

This state is passed into the TextInput as a property for its secureTextEntry property. The secureTextEntry state is initially set as true.

I am encountering some strange issues with this set up.

1) While secureTextEntry === true and there is some text in the input, AND THEN I click the toggle button AFTER the last character turns into the secure text circle (now secureTextEntry === false), all the text in the input loses its styling (font etc.).  

2) While secureTextEntry === true and there is some text in the input, AND THEN I click the toggle button BEFORE the last character turns into the secure text circle (now secureTextEntry === false), the text that were originally circles loses its styling (font etc.), while the last character and any characters onwards have the correct styling.  

3) While secureTextEntry === false and there is some text in the input, AND THEN I click the toggle button (now secureTextEntry === true), when I start typing, the original input value disappears (it is lost) and I have to start typing from a blank input (However the font styling is fine, which I can see for a split second before the characters turn to the secure text circle).

**Comment by izaakrogan** [comment]
@pangers for a quick and dirty fix try toggling the fontFamily

**Comment by christopherdro** [comment]
Hey @pangers!

This issue has been inactive for a while. Were you ever able to resolve this issue?

**Comment by christopherdro** [comment]
@facebook-github-bot no-reply

**Comment by baldurpan** [comment]
I'm having the same issue (Point no. 3).
Is there any workaround?

**Comment by tomas-paronai** [comment]
Having this issue on RN 0.49.0

**Comment by joaomilho** [comment]
Same on 0.49.5

**Comment by tetogomez** [comment]
This issues still happen, any solution ?

**Comment by tomas-paronai** [comment]
This is an iOS native behavior so I don't think this well get resolved. Will need to come up with a different solution..
