### ISSUE TITLE
Upgrade 0.70.6 to 0.72

### ISSUE THREAD

**Issue by featlast** [facebook/react-native#39006]
### New Version

0.72

### Old Version

0.70

### Build Target(s)

Android

### Output of `react-native info`

Greetings, there is a way to upgrade from react native 0.70.6 to 0.72, with some command to perform the entire process, and to perform the npx react-native upgrade. I stay tuned thanks

### Issue and Reproduction Steps

Greetings, there is a way to upgrade from react native 0.70.6 to 0.72, with some command to perform the entire process, and to perform the npx react-native upgrade. I stay tuned thanks

**Comment by selven** [comment]
Follow the guide and update with a specific issue you are having
https://reactnative.dev/docs/upgrading

**Comment by cortinico** [comment]
> Follow the guide and update with a specific issue you are having [reactnative.dev/docs/upgrading](https://reactnative.dev/docs/upgrading)

Closing as this is the right answer
