### ISSUE TITLE
Error building DepdendencyGraph

### ISSUE THREAD

**Issue by tells** [facebook/react-native#3902]
Getting this error message when creating my first app.  Went to the line error in index.js and saw comments mentioning that the code should check if it's 'dealing with a version of watchman that's using "watch-project"'.  I threw in a null check to short circuit the following error.  Branch name is 'crawler-watchProjectInfo'. 

```
Error building DepdendencyGraph:
 TypeError: Cannot read property 'root' of null
    at /Users/mike/AwesomeProject/node_modules/react-native/packager/react-packager/src/DependencyResolver/crawlers/index.js:16:84
    at tryCallOne (/Users/mike/AwesomeProject/node_modules/promise/lib/core.js:37:12)
    at /Users/mike/AwesomeProject/node_modules/promise/lib/core.js:103:15
    at flush (/Users/mike/AwesomeProject/node_modules/asap/raw.js:50:29)
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
```

**Comment by chirag04** [comment]
Refer below issues if its still a problem:
https://github.com/facebook/react-native/issues/1875
https://github.com/facebook/react-native/issues/3703
https://github.com/facebook/react-native/issues/2231
