### ISSUE TITLE
[Android]Value for IS_HERMES_ENABLED cannot be cast from Boolean to String

### ISSUE THREAD

**Issue by riteshshukla04** [facebook/react-native#39025]
### Description

Hi, I am facing below error after upgrading to RN 0.72.3 from 0.69.3 in Release APK. While debug mode works fine .

Any help would be appreciated . Thanks in advance :).

### React Native Version

0.72.3

### Output of `npx react-native info`

System:
  OS: macOS 13.4.1
  CPU: (8) arm64 Apple M2
  Memory: 79.19 MB / 16.00 GB
  Shell:
    version: 3.2.57
    path: /bin/bash
Binaries:
  Node:
    version: 20.5.0
    path: /opt/homebrew/bin/node
  Yarn:
    version: 1.22.10
    path: ~/Desktop/RN/Mobile/node_modules/.bin/yarn
  npm:
    version: 9.8.0
    path: /opt/homebrew/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods: Not Found
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2021.3 AI-213.7172.25.2113.9123335
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.17
    path: /usr/bin/javac
  Ruby:
    version: 2.7.5
    path: /Users/riteshshukla2/.rvm/rubies/ruby-2.7.5/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.3
    wanted: 0.72.3
  react-native-macos: Not Found
npmGlobalPackages:

  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

### Steps to reproduce

Install the app in release mode
<img width="1416" alt="Screenshot 2023-08-16 at 12 31 43 AM" src="https://github.com/facebook/react-native/assets/75062358/e7abcb78-7ba1-422a-9e24-23c73b773205">

**Comment by cortinico** [comment]
Hi,
Thanks for reporting this issue.

It seems like this issue is actually unrelated to React Native core but related to React Native firebase. Please open this issue against this other repository:

https://github.com/invertase/react-native-firebase/issues

I'll be closing this but feel free to reopen if the other repo points back to us as a issue in the core of React Native.

**Comment by riteshshukla04** [comment]
You are right . The issue was due to Crashlytics not React native core . My bad of assuming the Crashlytics log is to post the crash to Crashlytics . Thanks for the help :)
