### ISSUE TITLE
What's this mean in Js?

### ISSUE THREAD

**Issue by zhangjg** [facebook/react-native#3905]
In the file of  UIExplorer/ListViewExample.js  at the lines 63 and 83, there define two methods as fellow:

```js
 _renderRow: function(rowData: string, sectionID: number, rowID: number) {
    var rowHash = Math.abs(hashCode(rowData));
    var imgSource = {
      uri: THUMB_URLS[rowHash % THUMB_URLS.length],
    };
    return (
      <TouchableHighlight onPress={() => this._pressRow(rowID)}>
        <View>
          <View style={styles.row}>
            <Image style={styles.thumb} source={imgSource} />
            <Text style={styles.text}>
              {rowData + ' - ' + LOREM_IPSUM.substr(0, rowHash % 301 + 10)}
            </Text>
          </View>
          <View style={styles.separator} />
        </View>
      </TouchableHighlight>
    );
  },

  _genRows: function(pressData: {[key: number]: boolean}): Array<string> {
    var dataBlob = [];
    for (var ii = 0; ii < 100; ii++) {
      var pressedText = pressData[ii] ? ' (pressed)' : '';
      dataBlob.push('Row ' + ii + pressedText);
    }
    return dataBlob;
  },

```
the code ` _renderRow: function(rowData: string, sectionID: number, rowID: number) ` and ` _genRows: function(pressData: {[key: number]: boolean}): Array<string> ` looks like Swift but not like  Javascript.
Do them have some special mean? Or this is ES6? 
Some body can give some tips?

**Comment by zhangjg** [comment]
@sahrens Can you give me some tips?

**Comment by mihirsoni** [comment]
@zhangjg  

First thing first, this is wrong place to ask questions , from next time please use http://stackoverflow.com/ and tag them react-native.

Now regarding the signatures , React is using https://github.com/facebook/flow for type scripts. Please look at flow you will be able to understand that.

If this answer the question , please close the issue.
