### ISSUE TITLE
TextInput inside of AlertiOS

### ISSUE THREAD

**Issue by sankhadeeproy007** [facebook/react-native#3906]
Hi, is there any way we can use a TextInput inside a AlertiOS? I checked the docs for AlertiOS but couldn't find any mention of it. Is that a negative? Also, there are no references to it on SO as well. So any help here would be appreciated.

**Comment by gpbl** [comment]
Are you looking for [AlertIOS.prompt](https://facebook.github.io/react-native/docs/alertios.html#prompt)? 

```js
AlertIOS.prompt("Type a value", null, [
     { text: "Confirm", onPress: (value) => { console.log("You typed", value) } }
]);
```

**Comment by christopherdro** [comment]
@sankhadeeproy007 
Lets go ahead and start tracking this here #3893.
