### ISSUE TITLE
<Image aspectRatio={…} /> produces an error in TypeScript despite having an effect

### ISSUE THREAD

**Issue by wojtekmaj** [facebook/react-native#39073]
### Description

Passing `aspectRatio` prop to Image component works, but produces an error in TypeScript:

```
error TS2769: No overload matches this call.
  Overload 1 of 2, '(props: ImageProps | Readonly<ImageProps>): Image', gave the following error.
    Type '{ aspectRatio: number; height: number | undefined; resizeMode: "contain"; source: { uri: string; }; style: any; width: number | undefined; accessibilityLabel: string | undefined; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Image> & Readonly<ImageProps>'.
      Property 'aspectRatio' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Image> & Readonly<ImageProps>'.
  Overload 2 of 2, '(props: ImageProps, context: any): Image', gave the following error.
    Type '{ aspectRatio: number; height: number | undefined; resizeMode: "contain"; source: { uri: string; }; style: any; width: number | undefined; accessibilityLabel: string | undefined; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Image> & Readonly<ImageProps>'.
      Property 'aspectRatio' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Image> & Readonly<ImageProps>'.

35       aspectRatio={4 / 3}
```

### React Native Version

0.72.3

### Output of `npx react-native info`

System:
  OS: macOS 13.5
  CPU: (8) arm64 Apple M2
  Memory: 37.58 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.17.0
    path: /private/var/folders/3y/swkjq1x101b76mzjgt4pm2d80000gp/T/xfs-ac03ab9d/node
  Yarn:
    version: 3.5.1
    path: /private/var/folders/3y/swkjq1x101b76mzjgt4pm2d80000gp/T/xfs-ac03ab9d/yarn
  npm:
    version: 9.8.1
    path: /usr/local/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.12.1
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java: Not Found
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.3
    wanted: ^0.72.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

### Steps to reproduce

```ts
<Image 
  // …
  aspectRatio={4 / 3}
/> 
```

### Snack, screenshot, or link to a repository

https://snack.expo.dev/eHW3LA8QD

**Comment by AntoineDoubovetzky** [comment]
This is also the case for other [Layout Props](https://reactnative.dev/docs/layout-props) (I tested `height`, `margin`/`padding` and `borderWidth`/`borderColor` using the example provided).

Are these props supposed to work like that? They are labeled "props", but they are used via style prop in the documentation.

**Comment by NickGerleman** [comment]
Style props are flattened when passed to native components for historical reasons. I would recommend not relying on it, and keeping style props on style. I.e. we would like to fix this in the future, but it’s scary to because existing untyped code may be using these as top level props with everything working.
