### ISSUE TITLE
Pod install issues

### ISSUE THREAD

**Issue by AhmedK-Fawry** [facebook/react-native#39087]
### Description

---
**Issue Description: Error in React Native Module for FawryPay SDK Integration on iOS**

**Problem Overview:**

We are encountering an issue while creating a React Native module that wraps the FawryPay SDK pod for iOS integration. It's important to note that the FawryPay SDK pod itself works flawlessly on iOS. However, the issue arises when we attempt to integrate this pod into our React Native module.

**Error Details:**

The following build commands failed:
```
SwiftVerifyEmittedModuleInterface normal arm64 Verifying emitted module interface YogaKit.swiftinterface /Users/ahmed.kamal/Library/Developer/Xcode/DerivedData/RnFawryPaySdkExample-dteovgnshotjkhcosevlfkujtkrf/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/YogaKit.build/Objects-normal/arm64/YogaKit.swiftinterface (in target 'YogaKit' from project 'Pods')
```
(1 failure)

**Steps to Replicate:**

1. Run the command `yarn` in the root folder of the project.
2. Navigate to the 'example' folder and run `pod install` in the 'ios' subfolder.
3. Execute `yarn ios` in the 'example' folder.

**Additional Context:**

While the FawryPay SDK pod functions correctly on iOS, we are encountering challenges when integrating it into our React Native module. This issue does not affect the Android version of the React Native project, which is working as expected.

**Previous Approaches Attempted:**

1. Transitioned the React Native SDK to use a `.xcframework` target instead of a fat `.a` static library target. However, the issue persists.
2. Enabled the "build for distribution" flag with "try," leading to a different RN error due to conflicts with flipper and yogakit. These components are essential for the layers linking process.
3. Successfully introduced dynamic pods like Alamofire. The issue seems to be specific to our FawryPay SDK pod.
4. Explored using the FawryPay framework as a file import instead of a pod, resulting in errors similar to old iOS native errors prior to pod publication.

**Repository Information:**

- Repository: [React Native FawryPay SDK Repository](https://github.com/FawryPay/ReactNative-Fawrypay-Anonymous-sample)

### React Native Version

0.71.8

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 61.28 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.5.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.8.0 - /opt/homebrew/bin/npm
    Watchman: 2023.07.24.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK:
      API Levels: 31, 33, 34
      Build Tools: 29.0.2, 30.0.2, 30.0.3, 34.0.0
      System Images: android-34 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.10121639
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.19 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.8 => 0.71.8 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
info React Native v0.72.4 is now available (your project is running on v0.71.8).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.72.4
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.71.8
info For more info, check out "https://reactnative.dev/docs/upgrading".

### Steps to reproduce

**OPTION 1**

-Create React Native Module
-Import FawryPaySDK

**OPTION 2**
-Run the SDK App Sample provided by doing this :
1. Run the command `yarn` in the root folder of the project.
2. Navigate to the 'example' folder and run `pod install` in the 'ios' subfolder.
3. Execute `yarn ios` in the 'example' folder.

### Snack, screenshot, or link to a repository

https://github.com/FawryPay/ReactNative-Fawrypay-Anonymous-sample

**Comment by cipolleschi** [comment]
Hi there, thanks for surfacing this issue.
I'm having a look at the repro, but I have a few questions:
1. Do you have control over the Fawry dependencies? I can see that all the source code is closed source, so I'm trying to understand how much flexibility do we have.
2. Which setup were you using? Hermes on or off? New or old architecture?
Notice that, given that the code is closed source, I may not be able to help you out completely.

**Comment by cipolleschi** [comment]
Second thing, as soon as I opened Xcode and started building, I received this dialog:
![Screenshot 2023-08-21 at 09 32 37](https://github.com/facebook/react-native/assets/11162307/78376dd7-4df4-42b8-885c-74a197969918)
After telling Xcode `build for Rosetta` it build successfully.

**Comment by AhmedK-Fawry** [comment]
Hi @cipolleschi,

Thank you so much for your willingness to assist!

1- Absolutely, I have full control over Fawry's dependencies, given that I'm a software engineer at Fawry. I've prepared a version of the project that incorporates an open-source Fawry SDK for React Native. You can access it here: [Open Source Fawry SDK React Native Version](https://drive.google.com/file/d/15QX96146EE9os0AF1rNjbyWal4B2Rd4x/view?usp=sharing). I'd greatly appreciate it if you could take a look at this.

2- Hermes is enabled, and we're using the new architecture.

3- Yes, I've already performed the necessary `pod install` step.

4- I also experimented with React Native 0.72 to see if it made a difference , It didn't.

5- Attempting to build for Rosetta still resulted in failure. Here's a screenshot illustrating the issue: ![Screenshot](https://github.com/facebook/react-native/assets/138766115/e1647b6b-2a76-47a9-a6c8-14c51748afd9)

Once again, thank you for your time and assistance.

**Comment by cipolleschi** [comment]
I cannot reproduce this issue.
This morning I followed these steps:
1. `git clone https://github.com/FawryPay/ReactNative-Fawrypay-Anonymous-sample.git`
2. `cd ReactNative-Fawrypay-Anonymous-sample`
3. `yarn`
4. `cd ios`
5. ` bundle install`
6. `NO_FLIPPER=1 USE_HERMES=0 bundle exec pod install` (<-- avoiding building Flipper saves a bit of time)
7. `open FawryPaySample.xcworkspace` 
8. <kbd>⌘</kbd>+<kbd>B</kbd>
9. Click on Build for Rosetta
=> And Xcode built everything without issues.

Have you tried to clean the environment and to clean the derived data folder and then to build again?

**Comment by AhmedK-Fawry** [comment]
Hey @cipolleschi 

I've gone through all the steps you followed, and I managed to get the build to succeed. However, I'm running into an immediate crash issue when trying to open the app – it doesn't even launch. The error message that's coming up is:

```
dyld[91953]: Library not loaded: @rpath/Alamofire.framework/Alamofire
  Referenced from: <7E06AEE0-0F7D-32B4-82DB-B6EAD7298501>
```
<img width="1112" alt="Screenshot 2023-08-22 at 9 54 39 AM" src="https://github.com/facebook/react-native/assets/138766115/b62b40fe-0608-433a-b200-59b917edc020">

Interestingly, I've seen others facing the same hiccup. I tried various solutions mentioned on this GitHub thread (https://github.com/Alamofire/Alamofire/issues/3051), but none of them seemed to do the trick for me.

By the way, Does it build fine on your side and then crash immediately upon opening, just like it's happening in my case? Or Does the app work smoothly with you ?

**Comment by cipolleschi** [comment]
Honestly, I haven't run it, as the issue was building. I'm a bit puzzled by the error, as we are not building using dynamic frameworks and, usually, the `dyld` are related to the app not finding a dynamic library... which is not there as everything is static. 

I need to carve some time to investigate this further, but please continue trying.
In some cases, I managed to fix this kind of errors updating the Framework Search Paths. Cocoapods should do it automatically, but with React Native we have to manipulate those value so it could be that we are clashing with the default behavior of Cocoapods. Try to play with those settings to see if you manage to get it working! 😉

**Comment by FWMilad** [comment]
Dear @cipolleschi , 
I have sent you an email with more details about the issue 
could you please check it

**Comment by cipolleschi** [comment]
I made some extra tests. Seems like that some of your dependencies requires for the project to use frameworks.
Firebase is another library that asks their users to turn on `use_frameworks` which is NOT the default settings for react native.

Can you make a test and install cocoapods running:
`USE_FRAMEWORKS=dynamic NO_FLIPPER=1 bundle exec pod install`?

Flipper is not compatible with `use_frameworks!`, unfortunately, so we have to disable it.
