### ISSUE TITLE
Single dashed border for View or Text on iOS

### ISSUE THREAD

**Issue by IvanAfonin** [facebook/react-native#39088]
### Description

Currently,  if I'm trying to use `borderBottom` and `borderStyle: 'dashed'` it shows a solid line. There are a lot of workarounds but all of them are a painful way to implement a simple style.

FYI: I'm using Expo SDK 49.0.6

<img src="https://github.com/facebook/react-native/assets/60844028/2ddc059b-4533-45d8-8241-8ac70173b935" width="300px"/>

### React Native Version

0.72.3

### Output of `npx react-native info`

```
Info Fetching system and libraries information...
System:
  OS: macOS 13.4.1
  CPU: (10) arm64 Apple M1 Pro
  Memory: 71.30 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 16.13.0
    path: ~/.nvm/versions/node/v16.13.0/bin/node
  Yarn: Not Found
  npm:
    version: 8.1.0
    path: ~/.nvm/versions/node/v16.13.0/bin/npm
  Watchman:
    version: 2023.04.10.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: Electric Eel 2022.1.1 Electric Eel 2022.1.1
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.17
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.3
    wanted: 0.72.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found


```

### Steps to reproduce

```
	<View
	style={{
		borderBottomWidth: 1,
		borderBottomColor: 'red',
		borderRadius: 4,
		borderStyle: 'dashed',
		}}
		>
			 <Text>Test</Text>
	</View>
```

### Snack, screenshot, or link to a repository

https://snack.expo.dev/8tjUQAn_8

<img width="812" alt="image" src="https://github.com/facebook/react-native/assets/60844028/8c4c944d-4847-4e8e-976f-1fa96ffd0325">

**Comment by IvanAfonin** [comment]
@byCedric @Kudo Sorry for tagging you guys, but I know that you are making React Native and Expo great again!
I saw a lot of issues regarding this bug, but unfortunately all of them are stale or closed, I will be happy to provide details, help or contribute :))

**Comment by IvanAfonin** [comment]
I'm not sure if it's expo issue, I'm using pure react native styling

**Comment by IvanAfonin** [comment]
@cortinico Can you re-open this issue, please :))

**Comment by cortinico** [comment]
> I'm not sure if it's expo issue, I'm using pure react native styling

Then why have you tagged two Expo employee?

Also have you checked other opened issues which might be duplicate?
https://github.com/facebook/react-native/issues/32918
https://github.com/facebook/react-native/issues/37177

**Comment by IvanAfonin** [comment]
I checked these issues, and they're describing different behaviour, these two guys are collaborators in React Native, so it makes too, anyway it's a pure React Native issue

**Comment by IvanAfonin** [comment]
Seems like dashed border bottom triggers this error handler

https://github.com/facebook/react-native/blob/main/packages/react-native/React/Views/RCTBorderDrawing.m#L473C1-L473C1
