### ISSUE TITLE
By default RTL layout in android

### ISSUE THREAD

**Issue by omaranwaar** [facebook/react-native#39082]
I'm on RN 0.72.3 and I tried to set the  `sharedI18nUtilInstance.forceRTL(this, true);`  in mainApplication.java, it works as expected and change the layout to RTL by default, but when I try to change the language to english and change the layout to LTR it just updates the language to english but layout stays the same RTL. 
if we don't use the  `sharedI18nUtilInstance.forceRTL(this, true);` in mainApplication.java then we it looks impossible to make the layout RTL by default (on first launch after app install)

**Comment by cortinico** [comment]
This issue report is invalid. Please open a new one filling the issue template

**Comment by Hamidrezana** [comment]
@omaranwaar I have this issue, Did you find any solution?

**Comment by omaranwaar** [comment]
I solved this issue by making some changes in mainApplication.java flie.
```
     SharedPreferences preferences = PreferenceManager.getDefaultSharedPreferences(this);
      boolean rtlSetupCompleted = preferences.getBoolean(RTL_SETUP_COMPLETED_KEY, false);

    if (!rtlSetupCompleted) {
      Locale.setDefault(new Locale("ar"));
      I18nUtil sharedI18nUtilInstance = I18nUtil.getInstance();
      sharedI18nUtilInstance.forceRTL(this, true);
      sharedI18nUtilInstance.allowRTL(this, true);

      SharedPreferences.Editor editor = preferences.edit();
      editor.putBoolean(RTL_SETUP_COMPLETED_KEY, true);
      editor.apply();
    }
```
I added a flag in sharedPreference and use the  sharedI18nUtilInstance.forceRTL(this, true); only when its needed.

**Comment by mimo-10** [comment]
hello, thank you so much, what about imports ?, also do you use i18next ?

**Comment by omaranwaar** [comment]
> hello, thank you so much, what about imports ?, also do you use i18next ?

yes, i18next
@mimo-10

**Comment by mimo-10** [comment]
Thanks you much, but I did figure it out

**Comment by mimo-10** [comment]
What about ios ?!

**Comment by kbqdev** [comment]
Can you create an example please, i'm trying do same thing but not working at all. @omaranwaar

**Comment by mimo-10** [comment]
Sorry, i'm late but i hope i could help, actual i managed to fix it for both android and ios, and here is the code snippets , android  : u  need to add it to MainApplication.java inside the onCreate function 
` 
SharedPreferences preferences = PreferenceManager.getDefaultSharedPreferences(this);
      boolean rtlSetupCompleted = preferences.getBoolean(RTL_SETUP_COMPLETED_KEY, false);

    if (!rtlSetupCompleted) {
      Locale.setDefault(new Locale("ar"));
      I18nUtil sharedI18nUtilInstance = I18nUtil.getInstance();
      sharedI18nUtilInstance.forceRTL(this, true);
      sharedI18nUtilInstance.allowRTL(this, true);

      SharedPreferences.Editor editor = preferences.edit();
      editor.putBoolean(RTL_SETUP_COMPLETED_KEY, true);
      editor.apply();
    }
    I18nUtil sharedI18nUtilInstance = I18nUtil.getInstance();
sharedI18nUtilInstance.allowRTL(getApplicationContext(), true);
`

ios :  u need to add it to AppDelegate.m(m) inside didFinishLaunchingWithOptions function 
` 
  NSUserDefaults *defaults = [NSUserDefaults standardUserDefaults];
  BOOL rtlSetupCompleted = [defaults boolForKey:@"RTL_SETUP_COMPLETED_KEY"];

  if (!rtlSetupCompleted) {
    [[RCTI18nUtil sharedInstance] allowRTL:YES];
    [[RCTI18nUtil sharedInstance] forceRTL:YES];
    [defaults setBool:YES forKey:@"RTL_SETUP_COMPLETED_KEY"];
  } else {
    [[RCTI18nUtil sharedInstance] allowRTL:YES];
  }
`


happy coding : )

**Comment by Ahsanabid27** [comment]
Thanks guys

**Comment by kbqdev** [comment]
@mimo-10 thank you so much
