### ISSUE TITLE
Run Example UIExplore error

### ISSUE THREAD

**Issue by naxiaoguang** [facebook/react-native#3908]
[error][tid:main][RCTBatchedBridge.m:425] Error while loading: The operation couldn’t be completed. No such file or directory

why this happen?
1,cd react-native
2,npm install
3,npm start 
4,run UIExplorer.xcodeproj on xcode .

then error

**Comment by browniefed** [comment]
@facebook-github-bot label Needs more information

**Comment by browniefed** [comment]
@facebook-github-bot close
