### ISSUE TITLE
@react-native-communit/eslint-config not found

### ISSUE THREAD

**Issue by ShahilMangroliya** [facebook/react-native#39090]
### Description

`https://registry.yarnpkg.com/@react-native-communit%2feslint-config`
`https://registry.npmjs.org/@react-native-communit%2feslint-config`
giving not found error while running `yarn` and `npm i --f`
also 
`https://github.com/facebook/react-native/tree/HEAD/packages/eslint-config-react-native-community#readme`
It has not found error

### React Native Version

0.71.12

### Output of `npx react-native info`

System:
  OS: macOS 13.5
  CPU: (10) arm64 Apple M2 Pro
  Memory: 80.22 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.2.0
    path: /opt/homebrew/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 9.6.7
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2023.05.22.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10406996
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.19
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

### Steps to reproduce

run npm i or yarn
It's installation issue

### Snack, screenshot, or link to a repository

![Screenshot 2023-08-21 at 3 57 38 PM](https://github.com/facebook/react-native/assets/60001265/1799b513-9792-4fe0-99c4-5207509c1649)
<img width="1094" alt="Screenshot 2023-08-21 at 3 58 26 PM" src="https://github.com/facebook/react-native/assets/60001265/f73d4ad1-3a49-4194-b23f-7c37c0676ba4">
[yarn-error.log](https://github.com/facebook/react-native/files/12395079/yarn-error.log)

**Comment by iBotPeaches** [comment]
Your error looks like you typo the package name no? `@react-native-communit/eslint-config`

**Comment by cortinico** [comment]
As @iBotPeaches mentioned, you have a typo in the package name + the correct URL is:
https://github.com/facebook/react-native/blob/main/packages/eslint-config-react-native/README.md
