### ISSUE TITLE
Cannot read properties of undefined (reading 'transformFile')

### ISSUE THREAD

**Issue by SanamdeepSingh-826** [facebook/react-native#39105]
### Description

Previously I was running my React native App with node 16 without any issue, now I have updated the node version to 18 and tried to run my app, I am getting the following error, What solution can be tried for fixing it ?

```
error: TypeError: Cannot read properties of undefined (reading 'transformFile')
    at Bundler.transformFile (/Users/apple/Desktop/.../.../node_modules/metro/src/Bundler.js:48:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.transform `(/Users/apple/Desktop/.../.../node_modules/metro/src/lib/transformHelpers.js:101:12)`

```

**!! I dont want to upgrade React native Version or downgrade Node version !!**

**React Native Version**
0.67.3

Node version
18.16.1

 

### React Native Version

0.67.3

### Output of `npx react-native info`

System:
    OS: macOS 13.5
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 36.91 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.1 - ~/.nvm/versions/node/v18.16.1/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.1/bin/npm
    Watchman: 2022.09.26.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/apple/.rvm/gems/ruby-2.7.5/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 28, 29, 30, 31, 33
      Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0, 33.0.0
      System Images: android-29 | Google APIs Intel x86 Atom, android-33 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.3 => 0.67.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

start the metro bundler -> during the building, you can see the issue

### Snack, screenshot, or link to a repository

<img width="825" alt="Screenshot 2023-08-22 at 4 27 31 PM" src="https://github.com/facebook/react-native/assets/77355835/a40f1f9f-35b9-491a-8cd0-a508fa489be3">

**Comment by DevVibhor** [comment]
Facing the same issue
