### ISSUE TITLE
Type issue: removeSubscription function has been removed from NativeEventEmitter, but its type is not updated

### ISSUE THREAD

**Issue by Yupeng-li** [facebook/react-native#39111]
### Description

`removeSubscription(subscription: EmitterSubscription): void;` has been removed from NativeEventEmitter in this [commit](https://github.com/facebook/react-native/commit/d39643b9de11c6b44984166ede34a7f44de76fe5). However, [the type file](https://github.com/facebook/react-native/blob/main/packages/react-native/Libraries/EventEmitter/NativeEventEmitter.d.ts#L68) is not updated.

### React Native Version

0.71.12

### Output of `npx react-native info`

  ```info Fetching system and libraries information...
System:
    OS: macOS 13.5.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 711.83 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
Binaries:
    Node: 18.17.0 - ~/Library/Caches/fnm_multishells/24849_1670237417415/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.6.7 - ~/Library/Caches/fnm_multishells/24849_1670237417415/bin/npm
    Watchman: 2023.06.26.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.19 - /Users/yupeng/.sdkman/candidates/java/11.0.19-tem/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.12 => 0.71.12
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

The details are in the "Description" section above. 

### Snack, screenshot, or link to a repository

https://snack.expo.dev/@yupeng_li/nativeeventemitter-removesubscription

**Comment by Yupeng-li** [comment]
> ⚠️	Add or Reformat Version Info
> ℹ️	We could not find or parse the version number of React Native in your issue report. Please use the template, and report your version including major, minor, and patch numbers - e.g. 0.70.2

The version has been updated in the original issue report.

**Comment by cortinico** [comment]
Thanks for the report @Yupeng-li 
This is up for grab if someone wants to contribute to React Native
