### ISSUE TITLE
Add new repositories by maven in android buid.gradle, not work when build project

### ISSUE THREAD

**Issue by Andersonfrfilho** [facebook/react-native#39114]
### Description

When I add a new external repository with 

`android/build.gradle`

```gradle
  repositories {
    google()
    mavenCentral()
    maven { url "https://zendesk.jfrog.io/zendesk/repo/" }
  }
```

when building the project with:
npm run android, it doesn't search the referenced repositories.
I'm try change order the called but not work:

```gradle
  repositories {
    google()
    maven { url "https://zendesk.jfrog.io/zendesk/repo/" }
    mavenCentral()
  }
```

when removed `maveCentral()` - is called but the main ones are not

### React Native Version

0.72.4

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
  OS: Linux 5.14 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
  CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
  Memory: 6.82 GB / 15.40 GB
  Shell:
    version: 5.8.1
    path: /usr/bin/zsh
Binaries:
  Node:
    version: 16.14.2
    path: ~/.nvm/versions/node/v16.14.2/bin/node
  Yarn:
    version: 1.22.19
    path: ~/.nvm/versions/node/v16.14.2/bin/yarn
  npm:
    version: 8.5.0
    path: ~/.nvm/versions/node/v16.14.2/bin/npm
  Watchman: Not Found
SDKs:
  Android SDK:
    API Levels:
      - "29"
      - "30"
      - "31"
      - "32"
      - "33"
      - "34"
    Build Tools:
      - 29.0.2
      - 30.0.2
      - 30.0.3
      - 34.0.0
    System Images:
      - android-UpsideDownCakePrivacySandbox | Google Play Intel x86_64 Atom
    Android NDK: Not Found
IDEs:
  Android Studio: AI-213.7172.25.2113.9123335
Languages:
  Java:
    version: 11.0.20
    path: /usr/bin/javac
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

### Steps to reproduce

- git clone - https://github.com/Andersonfrfilho/sunshine-module-react-native
- run 
  - cd example
  - npm run android

### Snack, screenshot, or link to a repository

git clone - https://github.com/Andersonfrfilho/sunshine-module-react-native

**Comment by cortinico** [comment]
Hey @Andersonfrfilho 
I advice you to do the following:
1. I see you're specifying the repository in two places:
```
buildscript {
  repositories {
    google()
    mavenCentral()
    maven { url "https://zendesk.jfrog.io/zendesk/repo/" }
  }
}

...

repositories {
  mavenCentral()
  google()
  maven { url "https://zendesk.jfrog.io/zendesk/repo/" }
}
```

you practically need only this:

```
repositories {
  maven { url "https://zendesk.jfrog.io/zendesk/repo/" }
}
```

as `mavenCentral()` and `google()` are already included for you if you're in React Native 0.72

2. I'll be closing this issue as the problem you're having is with the library template, so you will have to open another issue here https://github.com/callstack/react-native-builder-bob/issues and ask for further support

**Comment by Andersonfrfilho** [comment]
@cortinico, I believe you did not understand the problem, we were developing a test of a new native module for react-native, the example project requires that the repository be added to the folders:
https://github.com/Andersonfrfilho/sunshine-module-react-native/blob/main/example/android/build.gradle, but when adding it there it has no effect except when we remove mavenCentral()
The problem is not in the library but in the react-native android build

**Comment by eduardoborges** [comment]
Hey @Andersonfrfilho you have some progress in this issue?
I had the same problem with Maven URL repos.

**Comment by eduardoborges** [comment]
@Andersonfrfilho in the library on directly on your rn app? Can you give me more details?

**Comment by GeraldoLimaGlance** [comment]
I'm facing the same problem too

**Comment by wirrareka** [comment]
stumbled upon this one too, wrapping the repositories inside allprojects solved it for me

allprojects {
    repositories {
        maven { url "https://maven.yolo.com/android-releases/" }
    }
}

**Comment by BenniHackstock** [comment]
I couldn't quite solve it using @wirrareka's method, but changing it like this solved it for me:

```groovy
rootProject.allprojects { Project subproject ->
    subproject.repositories {
        maven { url "https://maven.yolo.com/android-releases/" }
    }
}
```

**Comment by shovel-kun** [comment]
The solution @BenniHackstock proposed worked for me.

One quirk I've found is that using gradle from Android Studio results in gradle correctly picking up the repository, but not from the command line (`./gradlew`).

**Comment by theambidextrous** [comment]
@BenniHackstock  solution worked for me with a very tiny change, removed the type `Project`

```
rootProject.allprojects { subproject ->
    subproject.repositories {
        maven { url "https://maven.yolo.com/android-releases/" }
    }
}
```
