### ISSUE TITLE
Android Release App crashes when opening the App

### ISSUE THREAD

**Issue by biosrndeveloper** [facebook/react-native#39125]
### Description

Updated into the latest React-Native version. Tested the debug app and it's fine but for the **Android release** app crashes when opening the app on the real device

### React Native Version

0.72.4

### Output of `npx react-native info`

System:
  OS: macOS 13.4
  CPU: (8) arm64 Apple M1
  Memory: 109.61 MB / 8.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 16.13.0
    path: ~/.nvm/versions/node/v16.13.0/bin/node
  Yarn: Not Found
  npm:
    version: 8.1.0
    path: ~/.nvm/versions/node/v16.13.0/bin/npm
  Watchman:
    version: 2023.07.24.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.2 AI-222.4459.24.2221.9971841
  Xcode:
    version: 14.3/14E222b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 13.0.14
    path: /usr/bin/javac
  Ruby:
    version: 3.2.2
    path: /opt/homebrew/opt/ruby/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
  react-native-macos: Not Found
npmGlobalPackages:
  "react-native": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

### Steps to reproduce

- npm install
- cd android 
- ./gradlew assembleRelease

### Snack, screenshot, or link to a repository

""

**Comment by cortinico** [comment]
What's the stacktrace?
