### ISSUE TITLE
some way to hide scrollbar in ScrollView

### ISSUE THREAD

**Issue by guanyuxin** [facebook/react-native#3912]
Is there some way to hide the scrollbar of the ScrollView

**Comment by guanyuxin** [comment]
seems horizontal scrollbar is hidden in iOS,but not android

**Comment by jforaker** [comment]
Did you read the docs?  https://facebook.github.io/react-native/docs/scrollview.html#showshorizontalscrollindicator

`showsHorizontalScrollIndicator={false]`

**Comment by guanyuxin** [comment]
yeah, showsHorizontalScrollIndicator={false} works on iOS,but not android

**Comment by guanyuxin** [comment]
Fond it, it's a bug and have been fixed in 14-rc  https://github.com/facebook/react-native/commit/e6ad91b5a218bec73a10a9064e9178235b12c557

**Comment by yasicmd** [comment]
set 
<ListView
                        showsVerticalScrollIndicator={false}
/>

**Comment by uc-hus** [comment]
Thank you! Yasicmd

**Comment by hodangquocdat** [comment]
thanks! jforaker

**Comment by adarshTS** [comment]
can someone help here : [https://stackoverflow.com/questions/45568086/how-to-select-the-center-item-in-a-scroll-view-from-a-list-of-items](https://stackoverflow.com/questions/45568086/how-to-select-the-center-item-in-a-scroll-view-from-a-list-of-items)

**Comment by mustafakucuk** [comment]
`
<ScrollView showsVerticalScrollIndicator={false}>
/* Your Codes */
</ScrollView>
`

**Comment by adarshTS** [comment]
thanks @mustafakucuk  I have done this long before forgot to mention it here

**Comment by janaka120** [comment]
showsVerticalScrollIndicator={false} works on iOS, android perfectly. I use it to hide vertical-scrollbar in ListView.

`<ListView showsVerticalScrollIndicator={false}/>`

**Comment by Jacckashakashkumar** [comment]
thank you  jforaker
