### ISSUE TITLE
Warning "incompatible with Gradle 9.0" with RN 0.72.4

### ISSUE THREAD

**Issue by bnobre** [facebook/react-native#39147]
### Description

When creating an app and running it, I always get the warning: "Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/8.0.1/userguide/command_line_interface.html#sec:command_line_warnings"

### React Native Version

0.72.4

### Output of `npx react-native info`

System:
  OS: Windows 10 10.0.18362
  CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  Memory: 418.70 MB / 7.88 GB
Binaries:
  Node:
    version: 18.17.1
    path: C:\Program Files\nodejs\node.EXE
  Yarn:
    version: 1.22.5
    path: C:\Program Files (x86)\Yarn\bin\yarn.CMD
  npm:
    version: 9.6.7
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK:
    AllowDevelopmentWithoutDevLicense: Enabled
    Versions:
      - 10.0.18362.0
      - 10.0.19041.0
IDEs:
  Android Studio: AI-223.8836.35.2231.10406996
  Visual Studio:
    - 16.8.30804.86 (Visual Studio Community 2019)
Languages:
  Java: 11.0.20
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

### Steps to reproduce

Create a new project:
npx react-native@latest init AwesomeProject

Running:
yarn start
yarn android

### Snack, screenshot, or link to a repository

*

**Comment by iBotPeaches** [comment]
@bnobre - am I correct you are just reporting a warning about the impending Gradle 9.0 release? I can assure you from watching the commits here over the years - The team is probably well aware of those deprecations and consistently moves to the latest Gradle & tools.

They probably track that internally is my guess.

**Comment by bnobre** [comment]
@iBotPeaches Yes, I am just reporting a warnin. 
But why does this warning appear? Gradle 9.0 doesn't even exist yet.

**Comment by iBotPeaches** [comment]
> @iBotPeaches Yes, I am just reporting a warning. But why does this warning appear? Gradle 9.0 doesn't even exist yet.

How else do you warn about upcoming deprecations and removals? It's telling you that in future you should stop doing something before Gradle 9 comes out and breaks it.

**Comment by bnobre** [comment]
> > @iBotPeaches Yes, I am just reporting a warning. But why does this warning appear? Gradle 9.0 doesn't even exist yet.
> 
> How else do you warn about upcoming deprecations and removals? It's telling you that in future you should stop doing something before Gradle 9 comes out and breaks it.

I understand now, nice. And these deprecations and removals are in the code of the packages used by RN 0.72.4, correct?

**Comment by cortinico** [comment]
I've investigated this, and already sorted all the Gradle 9 warnings here 41af21b42dd51868ade23402774a61c8acca8d7c

The warning will still show up on `main` as we need to wait for a version of AGP that does support Gradle 9. So by the time Gradle 9 will be out, we'll be fine.

I'm closing this as there is nothing more to do

**Comment by rumirinbrah** [comment]
In my case the problem was kapt. I changed it to ksp & now it works just fine
