### ISSUE TITLE
upgrade 0.72.3 to  0.72.4, iOS release failed

### ISSUE THREAD

**Issue by TristanLudrow** [facebook/react-native#39143]
### New Version

0.72.4

### Old Version

0.72.3

### Build Target(s)

iOS release 

### Output of `react-native info`

  OS: macOS 13.5.1
  CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  Memory: 123.45 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.16.1
    path: ~/.nvm/versions/node/v18.16.1/bin/node
  Yarn:
    version: 1.22.19
    path: /usr/local/bin/yarn
  npm:
    version: 9.5.1
    path: ~/.nvm/versions/node/v18.16.1/bin/npm
  Watchman:
    version: 2023.07.10.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: ~/.rvm/gems/ruby-2.7.6/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK:
    API Levels:
      - "28"
      - "29"
      - "30"
      - "31"
      - "32"
      - "33"
    Build Tools:
      - 25.0.2
      - 28.0.3
      - 29.0.2
      - 29.0.3
      - 30.0.2
      - 30.0.3
      - 31.0.0
      - 32.0.0
      - 32.1.0
      - 33.0.0
      - 34.0.0
    Android NDK: Not Found
IDEs:
  Android Studio: 2022.2 AI-222.4459.24.2221.10121639
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 20.0.1
    path: /usr/bin/javac
  Ruby:
    version: 2.7.6
    path: ~/.rvm/rubies/ruby-2.7.6/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

### Issue and Reproduction Steps

xcode release failed, and exit 1

~/React_uniapp/ios/Pods/../../node_modules/react-native/sdks/hermes-engine/utils/build-hermesc-xcode.sh: line 20: : command not found

++ echo 'Failed to configure Hermesc cmake project.'

Failed to configure Hermesc cmake project.

++ exit 1

**Comment by ngxhuyhoang** [comment]
Same facing error

**Comment by geronimosua** [comment]
Were you able to fix it?

**Comment by geronimosua** [comment]
I just got rid of that error by changing the js engine from hermes to jsc. I'm not using vanilla react native but in Expo you can achieve that by adding these lines to your app.json

![Screenshot 2024-01-11 at 10 17 11](https://github.com/facebook/react-native/assets/97196583/cf956485-2bc8-4b38-b7a2-fa9fde8ec95a)
