### ISSUE TITLE
Android Fetch and Graphql requests hang for several minutes

### ISSUE THREAD

**Issue by JKKholmatov** [facebook/react-native#39181]
### Description

in a Expo project Fetch and Graphql requests sometimes hang for several minutes before being sent, even after APK build,
I tried to fetch jsonplaceholder.typicode.com and hanging still occurs

Here is Logs:
LOG  12:53:17 Fetch start
LOG  {"completed": false, "id": 1, "title": "delectus aut autem", "userId": 1}
LOG  12:55:39 Fetch End

Sometimes it takes 2 seconds to get response, sometimes it waits ~2 minutes to send request,
And this happens with every web requests

### React Native Version

0.72.4

### Output of `npx react-native info`

System:
  OS: Windows 10 10.0.19045
  CPU: (4) x64 Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz
  Memory: 1.01 GB / 3.88 GB
Binaries:
  Node:
    version: 18.17.1
    path: C:\Program Files\nodejs\node.EXE
  Yarn: Not Found
  npm:
    version: 9.6.6
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK:
    AllowDevelopmentWithoutDevLicense: Enabled
    Versions:
      - 10.0.19041.0
IDEs:
  Android Studio: Not Found
  Visual Studio: Not Found
Languages:
  Java: Not Found
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

### Steps to reproduce

1 - npx create-expo-app my-app
2 - Added a TouchabpleOpacity  button that calls fetchJson function
3 - Open via Expo Go
4 - Leave the phone for 5 minutes
5 - Press button
6 - Loading for ~2 minutes (if not again leave for 5 minutes)

That's it

```
import React, { useState } from "react";
import {
  ActivityIndicator,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from "react-native";

export default function App() {
  const [loading, setLoading] = useState(false);

  const fetchJson = async () => {
    setLoading(true);
    console.log(new Date().toLocaleTimeString() + " Fetch start");
    await fetch("https://jsonplaceholder.typicode.com/todos/1")
      .then((response) => response.json())
      .then((json) => console.log(json));
    console.log(new Date().toLocaleTimeString() + " Fetch End");
    setLoading(false);
  };

  return (
    <View style={styles.container}>
      <TouchableOpacity style={styles.button} onPress={() => fetchJson()}>
        {loading ? <ActivityIndicator color={"#fff"} /> : <Text>Fetch Json</Text>}
      </TouchableOpacity>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
  button: {
    height: 50,
    width: 100,
    borderRadius: 15,
    backgroundColor: "#007AFF",
    alignItems: "center",
    justifyContent: "center",
  },
});

```

### Snack, screenshot, or link to a repository

https://snack.expo.dev/@kholmatov/github.com-jkkholmatov-my-app
https://github.com/JKKholmatov/my-app/tree/master

UPDATE:
I tested with VPN on Android and it works as expected
Also tested with iPhone and  it works as expected

**Comment by cortinico** [comment]
Duplicates https://github.com/facebook/react-native/issues/37907
