### ISSUE TITLE
Modal looks jumpy when shown with `statusBarTranslucent={false}`

### ISSUE THREAD

**Issue by szmarczak** [facebook/react-native#39182]
### Description

<details>

<summary>bug</summary>

![vlcsnap-2023-08-28-13h03m39s265](https://github.com/facebook/react-native/assets/36894700/86ee07c9-6b76-4adf-8578-18b1b71bd4e2)

</details>

<details>

<summary>a few rendered frames later (there is **no animation**)</summary>

![vlcsnap-2023-08-28-13h03m45s244](https://github.com/facebook/react-native/assets/36894700/9c96f673-72b3-43f5-a279-503ad0d7a4e6)

</details>

### React Native Version

0.72.4

### Output of `npx react-native info`

```
> npx react-native info
info Fetching system and libraries information...
System:
  OS: Windows 10 10.0.22621
  CPU: "(12) x64 AMD Ryzen 5 5600 6-Core Processor              "
  Memory: 16.14 GB / 31.91 GB
Binaries:
  Node:
    version: 20.2.0
    path: C:\Program Files\nodejs\node.EXE
  Yarn: Not Found
  npm:
    version: 9.7.2
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK: Not Found
IDEs:
  Android Studio: AI-222.4459.24.2221.9971841
  Visual Studio:
    - 17.5.33424.131 (Visual Studio Community 2022)
Languages:
  Java:
    version: 17.0.6
    path: C:\Program Files\Eclipse Adoptium\jdk-17.0.6.10-hotspot\bin\javac.EXE
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Steps to reproduce

The code below.

### Snack, screenshot, or link to a repository

```js
        <Modal visible={open} transparent={true}>
            <View style={{ flexGrow: 1, flexDirection: 'column', justifyContent: 'flex-end', }}>
                <Pressable style={{ position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: 'rgba(0, 0, 0, 0.2)' }} onPress={() => setOpen(false)} />
                <View style={{ backgroundColor: 'white', borderTopLeftRadius: 10, borderTopRightRadius: 10, padding: 10 }}>
                    <Text>foobar</Text>
                </View>
            </View>
        </Modal>
```

**Comment by szmarczak** [comment]
Here's a Snack for the lazy: https://snack.expo.dev/@szmarczak/blessed-apple?platform=android

**Comment by szmarczak** [comment]
After many weeks I found the culprit and it's the `statusBarTranslucent` option. Setting this to `true` fixes the issue, but a translucent status bar is not desirable.

**Comment by alanleedev** [comment]
@szmarczak could you confirm if this is till an issue? With the provided snack I don't see any issue.

**Comment by szmarczak** [comment]
I'm unable to confirm this as I don't do React Native anymore. If you've checked this on a physical device, go ahead and close this.

I don't consider emulators trustworthy.

**Comment by alanleedev** [comment]
Closing.
Tested on a device using Expo Go. I don't see any issues although the content of the Modal does not match the screenshot of the issue but is just a simple text. I do not see any jumpy behavior. Also since there are some fixes being made to Modal, we'll fix things later if they come up again.
