### ISSUE TITLE
Error creating LLDB target at path

### ISSUE THREAD

**Issue by rigodamir** [facebook/react-native#39180]
### Description

When iOS app is build, it crashed on start and get this logs in XCode

```
Warning: Error creating LLDB target at path '/Users/damirrigo/Library/Developer/Xcode/DerivedData/loyalty-eqbitahuqdywnefiuzwugdkdjweh/Build/Products/Debug-prod-iphonesimulator/loyalty.app'- using an empty LLDB target which can cause slow memory reads from remote devices.
2023-08-28 10:38:08.771130+0200 loyalty[26420:1628391] [native] No bundle URL present.

Make sure you're running a packager server or have included a .jsbundle file in your application bundle.
2023-08-28 10:38:08.776539+0200 loyalty[26420:1628391] *** Terminating app due to uncaught exception 'RCTFatalException: No bundle URL present.

Make sure you're running a packager server or have included a .jsbundle file in your application bundle.', reason: 'No bundle URL present.

Make sure you're running a packager server or have included a .jsbundle file in your application bundle.'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010e1bc78b __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x000000010c5a3b73 objc_exception_throw + 48
	2   loyalty                             0x0000000100bb23f5 RCTGetFatalHandler + 0
	3   loyalty                             0x0000000100bcbbd5 __28-[RCTCxxBridge handleError:]_block_invoke + 581
	4   libdispatch.dylib                   0x00000001105a954f _dispatch_call_block_and_release + 12
	5   libdispatch.dylib                   0x00000001105aa7ec _dispatch_client_callout + 8
	6   libdispatch.dylib                   0x00000001105bb6e2 _dispatch_main_queue_drain + 1462
	7   libdispatch.dylib                   0x00000001105bb11e _dispatch_main_queue_callback_4CF + 31
	8   CoreFoundation                      0x000000010e11a6cc __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	9   CoreFoundation                      0x000000010e114fbe __CFRunLoopRun + 2429
	10  CoreFoundation                      0x000000010e114264 CFRunLoopRunSpecific + 560
	11  GraphicsServices                    0x0000000114b8e24e GSEventRunModal + 139
	12  UIKitCore                           0x00000001233bd7bf -[UIApplication _run] + 994
	13  UIKitCore                           0x00000001233c25de UIApplicationMain + 123
	14  loyalty                             0x0000000100afc2b0 main + 96
	15  dyld                                0x000000010adb7384 start_sim + 10
	16  ???                                 0x0000000202854310 0x0 + 8632222480
)
libc++abi: terminating due to uncaught exception of type NSException
Message from debugger: Terminated due to signal 6

```

### React Native Version

0.71.6

### Output of `npx react-native info`

System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 255.19 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
    Watchman: 2023.05.15.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK:
      API Levels: 28, 29, 30, 31, 32, 33
      Build Tools: 28.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0
      System Images: android-28 | Google ARM64-V8a Play ARM 64 v8a, android-30 | Google APIs Intel x86 Atom, android-32 | Google APIs ARM 64 v8a, android-32 | Google Play ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  Languages:
    Java: 19.0.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.6 => 0.71.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Install deps and pods in app then run the app inside XCode.

### Snack, screenshot, or link to a repository

https://github.com/facebook/react-native/assets/11744443/cb0c70f2-6022-4ba5-bd6b-e40d8e4dbafc

**Comment by nourhanana** [comment]
Any updates ?

**Comment by cortinico** [comment]
We can't help without a reproducer

**Comment by rickhanlonii** [comment]
@rigodamir the "LLDB target at path" warning is not the issue here, as that warning will slow down development but not crash the app. The real issue here is the next errors in the console:

> No bundle URL present.

and 

> Make sure you're running a packager server or have included a .jsbundle file in your application bundle.

This happens when (for example) you have not provided a valid bundleURL to `initWithBundleURL`, but I'd need to see the code for your AppDelegate to help debug it more.

**Comment by JustineUIT** [comment]
Any updates? I face the same error message when I upgrade to Xcode15, everything in the old Xcode(14.1) is working fine.  I clear all cache in Pods/ builds/ in ios but it still not work???

**Comment by JulioAugustoS** [comment]
I have the same problem here!

Note: I use MacOS Sonoma with M2 Pro

**Comment by namangoel11** [comment]
I have the same problem here!
 I use MacOS Sonoma with M2 Max

**Comment by rigodamir** [comment]
![image](https://github.com/facebook/react-native/assets/11744443/5b85dc4d-c53d-4b79-97df-6f884fc86ab9)
I had this issue because for some reason project configuration names were not `Debug` and `Release`. After renaming them correctly to `Debug` and `Release` app started successfully.

**Comment by SaatwikRishi** [comment]
Hi bumping it up, any fixes?

**Comment by faizantariq2** [comment]
Hi, facing the same issue. any fix? did you find anything? @JustineUIT  @JulioAugustoS @namangoel11 @shashwats-greytip

**Comment by shashwats-greytip** [comment]
@SaatwikRishi , @faizantariq2, for it fixed after upgrading the react-native version to **72.5**.

**Comment by MouhamedMokkhtar** [comment]
Hi, facing the same issue. any fix?

**Comment by RanaAwais3553** [comment]
react-native:0.72.5:

Steps How I do fixe this issue:
1- Open iOS project in Xcode
2- Select -> Target → Build Phases
3- under Copy Bundle Resources click on the plus button as following screenshot.
4- It will show you the prompt as shown below. Then select the file main.jsbundle and click on the Add button. ( If main.jsbundle file is not there then create first by running this command in terminal into your root project folder: **react-native bundle --entry-file='index.js' --bundle-output='./ios/main.jsbundle' --dev=false --platform='ios'**
)
5- Try to re-run your app

The crash will gone by using these steps but that warning is still there: **Warning: Error creating LLDB target at path '/Users/hafizranamawais/Library/Developer/Xcode/DerivedData/ShopCash-gdtskdgmiaxjtselannjqozvodmi/Build/Products/Debug-iphonesimulator/ShopCash.app'- using an empty LLDB target which can cause slow memory reads from remote devices.**

**Comment by obahareth** [comment]
Seems like there's a lot of different issues reported here related to crashes.

I am not having any crashes, just the warning on slow memory reads on React Native 0.72.7
Is there anything that can be done about this?

**Comment by raginisahu** [comment]
HI, Did anyone find solution , i'm having same issue in release build of IOS in debug build it is working for me .

*** Terminating app due to uncaught exception 'RCTFatalException: Unhandled JS Exception: TypeError: Cannot read property 'emitExpiredEvent' of null, js engine: hermes', reason: 'Unhandled JS Exception: TypeError: Cannot read property 'emitExpiredEvent' of null, js engine: hermes, stack:
anonymous@90969:54
anonymous@50006:27
emit@1620:39
emit@15290:49
anonymous@49982:24
__invokeCallback@2400:22
anonymous@2200:33
__guard@2317:14
invokeCallbackAndReturnFlushedQueue@2199:20
'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001804ae138 __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x0000000180087db4 objc_exception_throw + 56
	2   weightwonder                        0x00000001046bf794 RCTFormatError + 0
	3   weightwonder                        0x000000010472d14c -[RCTExceptionsManager reportFatal:stack:exceptionId:extraDataAsJSON:] + 488
	4   weightwonder                        0x000000010472d960 -[RCTExceptionsManager reportException:] + 1308
	5   CoreFoundation                      0x00000001804b4760 __invoking___ + 144
	6   CoreFoundation                      0x00000001804b1ac4 -[NSInvocation invoke] + 276
	7   CoreFoundation                      0x00000001804b1d5c -[NSInvocation invokeWithTarget:] + 60
	8   weightwonder                        0x00000001046ee77c -[RCTModuleMethod invokeWithBridge:module:arguments:] + 388
	9   weightwonder                        0x00000001046f07d0 _ZN8facebook5reactL11invokeInnerEP9RCTBridgeP13RCTModuleDatajRKN5folly7dynamicEiN12_GLOBAL__N_117SchedulingContextE + 456
	10  weightwonder                        0x00000001046f0420 ___ZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEi_block_invoke + 112
	11  libdispatch.dylib                   0x0000000105f97ec4 _dispatch_call_block_and_release + 24
	12  libdispatch.dylib                   0x0000000105f9973c _dispatch_client_callout + 16
	13  libdispatch.dylib                   0x0000000105fa1a30 _dispatch_lane_serial_drain + 916
	14  libdispatch.dylib                   0x0000000105fa2774 _dispatch_lane_invoke + 420
	15  libdispatch.dylib                   0x0000000105faf1a8 _dispatch_root_queue_drain_deferred_wlh + 324
	16  libdispatch.dylib                   0x0000000105fae604 _dispatch_workloop_worker_thread + 488
	17  libsystem_pthread.dylib             0x0000000105f23924 _pthread_wqthread + 284
	18  libsystem_pthread.dylib             0x0000000105f226e4 start_wqthread + 8
)
libc++abi: terminating due to uncaught exception of type NSException

Thanks

**Comment by shriya-begalileo** [comment]
Did you get any solution

**Comment by raginisahu** [comment]
> Did you get any solution

Yes, It was the problem with react-native-fetch-blob package. I removed that package and then it worked for me.

**Comment by shriya-begalileo** [comment]
i dont have this package in my package.json file although i have
react-native-blob-util package
