### ISSUE TITLE
VirtualizedList jumps when scrolling on variable-height elements

### ISSUE THREAD

**Issue by Almamu** [facebook/react-native#39187]
### Description

I'm writting a post reader for lemmy instances and I've come accross (what I think is) an issue with VirtualizedLists. A post can either have an image, a video or an external link + a title and some text. The issue appears with images. No post contains the image's width and height, so there's no way of knowing the image size until the image is downloaded and rendering has started.

The way I deal with it right now is that any image starts with a height of 350px. Once the image is loaded, a new new size is calculated based on the width of the container to keep the image's proportions. If the post is on-screen at the time of calculation, the image is not resized (this is done to prevent jumps in the UI while an user looks at an image, text, or something else that happened to be near the image). Once the post is not visible, the new size is applied.

This approach works fine when the user only scrolls down, but once the user wants to scroll up, the VirtualizedList starts to jump all over the place, making it hard to use.

Shouldn't the VirtualizedList take this into account and adjust when content changes size? Or is this something the VirtualizedList doesn't support? Is there any way of preventing this behaviour?

### React Native Version

0.72.4

### Output of `npx react-native info`
```
System:
  OS: macOS 13.4
  CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
  Memory: 252.36 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.17.0
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.19
    path: /usr/local/bin/yarn
  npm:
    version: 9.6.7
    path: /usr/local/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.11.3
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 20.0.1
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Steps to reproduce

1. Open the Snack link in any Android phone (haven't tested with iOS).
2. Scroll down and click the "Fetch next page" button 5 or 6 times so a lot of images are loaded
3. Scroll to the end
4. Now start scrolling up slowly
5. The VirtualizedList will start jumping all over the place

### Snack, screenshot, or link to a repository

Snack repro: https://snack.expo.dev/XgNLAWyjo

**Comment by NickGerleman** [comment]
ScrollView and by extension VirtualizedList maintain a constant offset from the start of content by default, so if something above the screen shifts layout dimension, you get this jump.

A prop "maintainVisibleContentPosition" may be used to change behavior to instead keep the position of the top visible element stable. VirtualizedList supoort for it is new in 0.72, so please let us know if you run into any issues with it.

**Comment by Almamu** [comment]
> A prop "maintainVisibleContentPosition" may be used to change behavior to instead keep the position of the top visible element stable. VirtualizedList supoort for it is new in 0.72, so please let us know if you run into any issues with it. 

I've tried using that prop before, but the documentation isn't really clear how "autoscrollToTopThreshold" is measured, and just setting "minIndexForVisible" doesn't seem to solve the issue (but it does help a tiny bit on some situations). 

https://github.com/facebook/react-native/assets/751307/64f5393f-1c70-4394-8738-082c51f971f3

This is the updated snack, in case it's useful: https://snack.expo.dev/oUwlxmmyk

**Comment by cortinico** [comment]
Duplicates #31510 - Please post your reproducer over there
