### ISSUE TITLE
onMomentumScrollEnd doesn't triggered on ios when I slowly scrolling

### ISSUE THREAD

**Issue by LastStranger** [facebook/react-native#39189]
### Description

I add a listener on ScrollView's onMomentumScrollEnd, but it doesn't triggered when I scrolling slowly manually,

### React Native Version

0.71.4

### Output of `npx react-native info`

System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M1
    Memory: 92.48 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.19.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.6.6 - /usr/local/bin/npm
    Watchman: Not Found
  Languages:
    Java: 11.0.18 - /opt/homebrew/opt/openjdk@11/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.4 => 0.71.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

scrolling slowly

### Snack, screenshot, or link to a repository

I can't provided any link for now

**Comment by LastStranger** [comment]
https://snack.expo.dev/9mDAteZdaV, I made a demo here,

**Comment by kunal-d11** [comment]
This [PR](https://github.com/facebook/react-native/pull/35926) fixes this issue.

**Comment by wilav-dev** [comment]
I'm using RN 0.75.4 and found this issue. Was it fixed?
