### ISSUE TITLE
New Architecture: Failed to trigger c++ turbo module codegen for android build

### ISSUE THREAD

**Issue by ToolmanP** [facebook/react-native#39188]
### Description

I'm following the c++ turbo module setup which is documented [here](https://reactnative.dev/docs/next/the-new-architecture/cxx-cxxturbomodules). I'm using `expo SDK` and I've already pre-build it and get the `NativeSampleModule` sample running which works pretty smoothly. The Question is when I tried to rename the `NativeSampleModule.ts` into something else (e.g. FooBar.ts and delete the build cache. The codegen failed instantly with build process complaining there's no template called `NativeSampleCxxSpec`. I've checked the generated files (android/app/build/generated/source/codegen/jni/Appspec.h) and the original spec template is missing.  My question is how this codegen is performed and how the cxx spec template is generated? I believe this can help uncovering some of toolchain puzzles here.

### React Native Version

0.72.4

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
  OS: Linux 6.1 Gentoo Linux
  CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
  Memory: 50.11 GB / 62.66 GB
  Shell:
    version: 5.1.16
    path: /bin/bash
Binaries:
  Node:
    version: 20.5.1
    path: /tmp/yarn--1693289599125-0.5205430889365983/node
  Yarn:
    version: 1.22.19
    path: /tmp/yarn--1693289599125-0.5205430889365983/yarn
  npm:
    version: 9.8.0
    path: /usr/bin/npm
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
IDEs:
  Android Studio: AI-231.9011.34.2311.10366083
Languages:
  Java:
    version: 17.0.6
    path: /usr/bin/javac
  Ruby:
    version: 3.1.4
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

Done in 1.52s.

### Steps to reproduce

1. Reproducing the original `NativeSampleModule` exmaple.
2. Rename `tm/NativeSampleModule.ts` into `tm/foobar.ts`
3. Run `yarn android`
4. Failed.

### Snack, code example, screenshot, or link to a repository

I believe this is a toolchain issue and not related to the main javascript part. Therefore, no snack is provided here.

**Comment by ToolmanP** [comment]
It seems only certain files beginning with `Native` will be selected?

**Comment by cortinico** [comment]
> It seems only certain files beginning with `Native` will be selected?

That's correct, the codegen picks only files that are called `Native*` when looking for TurboModule specs

**Comment by Daavidaviid** [comment]
> > It seems only certain files beginning with `Native` will be selected?
> 
> That's correct, the codegen picks only files that are called `Native*` when looking for TurboModule specs

Somehow, I missed that part
