### ISSUE TITLE
Error - Unable to Send Events to JS from Native Android Module

### ISSUE THREAD

**Issue by SwhiteMHC** [facebook/react-native#39193]
### Description

I am following the instructions presented here: https://reactnative.dev/docs/next/native-modules-android#sending-events-to-javascript.

sendEvent Method

```
 private void sendEvent(ReactContext reactContext,
                           String eventName,
                           @Nullable WritableMap params) {
        reactContext
                .getJSModule(DeviceEventManagerModule.RCTDeviceEventEmitter.class)
                .emit(eventName, params);
    }
```

Method to Trigger sendEvent
```
@Override
        public void BACtrackBatteryVoltage(float voltage) {
            Log.d("BACModule", "BACTrackBatteryVoltage");
            WritableMap params = Arguments.createMap();
            params.putString("status", String.valueOf(voltage));
            sendEvent(mCurrentActivity.getReactApplicationContext(), "BACTrackBatteryVoltage", params);
        }

```

Error: 

Method threw 'com.facebook.react.bridge.ObjectAlreadyConsumedException' exception. Cannot evaluate com.facebook.react.bridge.WritableNativeMap.toString()

### React Native Version

0.72.4

### Output of `npx react-native info`

System:
  OS: macOS 13.4
  CPU: (10) arm64 Apple M2 Pro
  Memory: 75.13 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.5.1
    path: /opt/homebrew/bin/node
  Yarn: Not Found
  npm:
    version: 9.8.0
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2023.08.14.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10406996
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.20
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

### Steps to reproduce

I am not sure how to provide steps to reproduce, as the native module I am building makes use of a 3rd party SDK BACTrack, that makes callbacks e.g. I invoke a method, and the SDK calls the BACtrackBatteryVoltage method above, which in turn triggers the sendEvent that fails.

### Snack, screenshot, or link to a repository

N/A

**Comment by AndreiCalazans** [comment]
According to the [internal ObjectAlreadyConsumedException](https://github.com/facebook/react-native/blob/2423342004c1e764a4c8a2ccdde80442f9f65b10/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/bridge/ObjectAlreadyConsumedException.java#L13-L18), that error suggests your WritableMap params is being consumed more than once which is not allowed since they move that memory place. 

You could be double sending the same event possibly from different threads, hard to tell just from what you provided. I suggest you do some logging and try catching to understand what's going on. There could be a race condition with the same event happening on different threads. Add some logs and investigate:

Possible logs:

```java
public void BACtrackBatteryVoltage(float voltage) {
    try {
        Log.d("BACModule", "BACTrackBatteryVoltage");
        WritableMap params = Arguments.createMap();
        params.putString("status", String.valueOf(voltage));
        Log.d("BACModule", "Sending event...");
        sendEvent(mCurrentActivity.getReactApplicationContext(), "BACTrackBatteryVoltage", params);
        Log.d("BACModule", "Event sent.");
    } catch (Exception e) {
        Log.e("BACModule", "Exception:", e);
    }
}
```
